### ISSUE TITLE
paddle cluster_train

### ISSUE THREAD

**Issue by cbstyle** [PaddlePaddle/Paddle#10009]
麻烦问一下， 集群提交任务时，paddle cluster_train ** ，0.11版的没有cluster_train这个参数，怎么修改？
paddle cluster_train ** 
paddle_trainer ***
paddle train *** 
这几个提交方式有啥区别啊？

**Comment by dzhwinter** [comment]
请参考paddlepaddle.org中的集群训练方式

**Comment by cbstyle** [comment]
没有找到解释这几个区别的doc，paddle版本太多了，好像也不兼容前面的版本吧

**Comment by dzhwinter** [comment]
cluster_train是一个0.9中的l脚本，可以参考对应的文档。集群训练方式是后向兼容的
