### ISSUE TITLE
如何使用Paddle编写CNN attention代码，有示例么？

### ISSUE THREAD

**Issue by chenbblei** [PaddlePaddle/Paddle#10013]
希望大家给我一个回复，谢谢各位

**Comment by dzhwinter** [comment]
参考https://github.com/PaddlePaddle/Paddle/blob/develop/benchmark/fluid/machine_translation.py

**Comment by chenbblei** [comment]
@dzhwinter  这个是GRU的并不是CNN的呀

**Comment by chenbblei** [comment]
暂时不用此种方法
