### ISSUE TITLE
build error : cp: ‘/some/path/Paddle/python/paddle’ and ‘/some/path/Paddle/python/paddle’ are the same file

### ISSUE THREAD

**Issue by cogmeta** [PaddlePaddle/Paddle#10033]
[ 56%] Built target create_multi_pass_reader_op
[ 56%] Built target create_random_data_generator_op
[ 56%] Built target create_recordio_file_reader_op
[ 56%] Built target create_shuffle_reader_op
[ 56%] Built target create_threaded_reader_op
[ 56%] Built target open_files_op
[ 57%] Built target paddle_pybind
[ 57%] Built target paddle_fluid_api
[100%] Built target paddle_fluid
[100%] Built target paddle_fluid_shared
[100%] Built target copy_paddle_pybind
[100%] Generating build/.timestamp
cp: ‘/some/path/Paddle/python/paddle’ and ‘/some/path/Paddle/python/paddle’ are the same file
make[2]: *** [python/build/.timestamp] Error 1
make[1]: *** [python/CMakeFiles/paddle_python.dir/all] Error 2
make: *** [all] Error 2

**Comment by dzhwinter** [comment]
Did you build paddle in the directory of `build`? Please refer to the cmake document, you should create a build directory first.

**Comment by cogmeta** [comment]
Thanks.
