### ISSUE TITLE
无法安装paddlepaddle

### ISSUE THREAD

**Issue by cuiyan265626** [PaddlePaddle/Paddle#10057]
我是在虚拟机上安装的centos6.4,所有环境以及pathon库都正常安装了，但是在安装paddlepaddle时显示以下错误信息，请求解决
 Could not find a version that satisfies the requirement paddlepaddle (from versions: )
No matching distribution found for paddlepaddle

**Comment by yeyupiaoling** [comment]
@cuiyan265626 
你使用的命令是
```
pip install paddlepaddle
```
吗？
请确认你的版本是Python2.7
