### ISSUE TITLE
paddlepaddle支持树莓派吗

### ISSUE THREAD

**Issue by kingdsz** [PaddlePaddle/Paddle#10066]
我最近想把深度学习部署在树莓派上，不知道支持不。paddle是用什么语言实现的？小白一个。。。。。

**Comment by jacquesqiao** [comment]
主体用C++实现的，paddle支持android的预测，所以理论上支持树莓派的ARM CPU，需要你编译一下试试。

**Comment by kingdsz** [comment]
paddle.topology.Topology这个我怎么在API中没找到，还有我自己可以写激活函数吗。😁😁😁😁

**Comment by yeyupiaoling** [comment]
@jacquesqiao 
在树莓派上安装PaddlePaddle，然后使用Python直接操作PaddlePaddle这样不会更好一些吗？

**Comment by yeyupiaoling** [comment]
@kingdsz 
应该是可以的，fluid会更灵活一些
