### ISSUE TITLE
ctr model的例子中，如果每次batch_size里只有正例或者只有负例，但整个pass里有正例也有负例，这样对模型最后auc影响很大吗

### ISSUE THREAD

**Issue by macomzzl** [PaddlePaddle/Paddle#10077]
http://www.paddlepaddle.org/docs/develop/models/ctr/README.cn.html
ctr model的例子中，如果每次batch_size里只有正例或者只有负例，但整个pass里有正例也有负例，这样对模型最后auc影响很大吗

**Comment by seiriosPlus** [comment]
还是建议把数据均匀分布，不然会影响到最终的精度
