### ISSUE TITLE
paddlepadle book

### ISSUE THREAD

**Issue by almostday** [PaddlePaddle/Paddle#10074]
Hello,I have connect the paddle book

![image](https://user-images.githubusercontent.com/32328478/39024828-e08d8888-4475-11e8-8322-2ab81e664439.png)

but the local host refused my request

![image](https://user-images.githubusercontent.com/32328478/39024857-173a7968-4476-11e8-8f23-1d44a984ff56.png)

how to solve this problem?

**Comment by kingdsz** [comment]
I have a same problem,

**Comment by seiriosPlus** [comment]
are you running the book with the help doc ```https://github.com/PaddlePaddle/book/blob/develop/README.md``` ?

**Comment by yeyupiaoling** [comment]
@almostday @kingdsz 
What system are you using? Windows or Ubuntu？
You can try this command：
```
docker run -d -p 8888:8888 docker.paddlepaddlehub.com/book
```

**Comment by chengduoZH** [comment]
该issue长时间没有回复，暂时先关闭了。

**Comment by duanlin0505** [comment]
https://github.com/PaddlePaddle/book/issues/610

**Comment by duanlin0505** [comment]
使用的就是https://github.com/PaddlePaddle/book/blob/develop/README.md 的方法，有相同的问题
