### ISSUE TITLE
Evaluation Methods and Tools

### ISSUE THREAD

**Issue by wangkuiyi** [PaddlePaddle/Paddle#10078]
Because engineers working on the tools are mostly located in Beijing, I am writing this document in Chinese.

## 评估指标

PaddlePaddle 是被设计来方便大家写深度学习程序（**应用程序**，比如人脸识别）的，包括训练程序和inference 程序。

我们希望用 PaddlePaddle 描述的应用程序时：

1. 应用程序编程简便、易读易懂易维护
2. 应用程序的执行速度快
3. 应用程序的 KPI（比如人脸识别的准确率）高
4. 应用程序对产品的影响正面（比如人脸识别程序的准确率提升让门禁系统更好用，订单量增加）

其中 4. 的评估依赖产品团队，和 PaddlePaddle 团队关系不大。

其中 1. 的评估比较主观，所以暂时不考虑。比如“编程简便”可以通过实现一个具体应用需要开发者投入的平均时间来衡量。但是这个标准在测量时误差容易比较大。“易读易懂易维护”可以通过用户问卷等形式调查，但是主观性比较强，问卷发放难以全面覆盖用户。“简便”的另一个容易测量的指标是代码行数，但是不易全面描述“简便”。

其中 2.中的“执行速度”可以用**inference时，每秒处理多少个instance**来衡量。训练时的速度的度量也可以参考之，但是一个更常用的度量应该是**投入一定量硬件资源时，某个特定KPI达到指定阈值的最短训练时间长度**，具体请看 3.。

其中 3. 中 inference时候的KPI（比如人脸识别的准确率），是可以在训练过程中测试出来的。具体地说，训练的时候，KPI随着时间（以及消耗掉的trainng data instances）增长并且收敛。我们关注
   1. KPI 收敛到的值尽量高（优）
   1. 达到足够高（优）的KPI 值所需的时间尽量短
   1. 达到足够高（忧）的KPI 值所消耗的 instances 尽量少

上述分析把需要监控的指标重新整理成了两类：

1. inference 时指标：**给定一定量的硬件资源，每秒钟inference的instance的数量**
2. training 时指标，细分为：
   1. 效果：**最优KPI值**
   2. 性能：**每秒处理的instance**、**达到特定KPI需要的最短时间**、**达到指定KPI需要的最少instance数量**。
   效果和性能指标都可以从每个应用的每个KPI随着（1）时间（3）消耗掉的instance数量 的增长曲线得到。

这篇文档专注于 2. training 时的指标 —— 我们希望对于特定应用，使用特定训练数据的时候，新版本的 PaddlePaddle 能让这个应用得到更好的指标度量。

## 评估方法

对于 training 时的指标，TensorFlow 的评测值方法得我们学习。以下是用TensorFlow实现的一个应用（图像分类）在使用特定数据（ResNet50）时的KPI（每秒处理的instance）随着 TensorFlow 的演进（从2018年1月到4月）而变化的曲线。我们可以看到，KPI总体上升（更优），虽然有些 TensorFlow 的演进导致了 KPI 的局部下跌：

<img width="1035" alt="screen shot 2018-04-19 at 9 30 20 pm" src="https://user-images.githubusercontent.com/1548775/39031873-c30ba9a8-441f-11e8-87f7-3c694f7d4d1a.png">

上图中横坐标是时间，表示TensorFlow的演进。实际上主干 Git branch 上每个 merge commit 都是 TensorFlow 的一个版本，都有时间标志。这一系列的 commits 就表示了 TensorFlow的演进。PaddlePaddle 也一样。

上图中纵轴是一个具体应用（图像分类）的一个具体 KPI（每秒处理的instance个数）。对不同应用会有应用相关的API。比如机器翻译的BLEU值，比如对排序模型的 Kendall Tau 值。

## 评估工具

和 @dzhwinter 以及 @Superjomn 讨论时，我们想到可以写一个 `evaluate.bash`，来评估一个特定应用的各个 KPI 随着 PaddlePaddle 版本演进的变化。

使用方式：

```bash
evaluate.bash <time-range> resnet50.fluid.py ./resnet50_data
```

运行上述命令的时候，`evaluate.bash` 

1. 把指定时间段 <time-range> 里的 PaddlePaddle 的 Git commits（源码）依次 checkout，
1. 并且 build 每个 Git commit 的 PaddlePaddle，
1. 用这个 Git commit 的PaddlePaddle 执行应用程序 `resnet50.fluid.py`，让它读取特定的数据集 `./resnet50_data`
1. 这个专门用来测试性能的应用程序 `resnet50.fluid.py` 应该在每个迭代打印以下 log:
   1. iteration id: i
   1. iteration start time: S(i)
   1. iteration end time: E(i)
   1. minibatch size: M(i)
   1. 计算并且打印此时模型的每个KPI，比如 precision P(i), recall R(i), etc

有了上述log信息，我们可以很容易地计算很多度量

1. 总训练时间：
   <img src="http://latex.codecogs.com/gif.latex?\sum_i&space;E(i)&space;-&space;S(i)" title="\sum_i E(i) - S(i)" />

1. accuracy 达到 λ 需要的训练时间：
   <img src="http://latex.codecogs.com/gif.latex?\sum_{i&space;\text{&space;s.t.&space;}&space;P(i)&space;\ge&space;\lambda}&space;E(i)&space;-&space;S(i)" title="\sum_{i \text{ s.t. } P(i) \ge \lambda} E(i) - S(i)" />

1. accuracy 达到 λ 需要的 instance 个数：
   <img src="http://latex.codecogs.com/gif.latex?\sum_{i&space;\text{&space;s.t.&space;}&space;P(i)&space;\ge&space;\lambda}&space;M(i)" title="\sum_{i \text{ s.t. } P(i) \ge \lambda} M(i)" />

也可以很容易地画出上面TensorFlow 的评估图。

**Comment by dzhwinter** [comment]
Thanks for such a great proposal! 
我理解continues evaluation 就是用图表反映**量化指标随commit id的变化**过程。
>1. 应用程序编程简便、易读易懂易维护
2. 应用程序的执行速度快
3. 应用程序的 KPI（比如人脸识别的准确率）高
4. 应用程序对产品的影响正面（比如人脸识别程序的准确率提升让门禁系统更好用，订单量增加）

所以在单机单卡上对指标2,3 补充一个显存消耗的指标。显存消耗决定了单个GPU上batch size的上限，也影响训练速度和收敛速度。
https://github.com/PaddlePaddle/Paddle/issues/9467

对于指标
>KPI 收敛到的值尽量高（优)

有一个问题是KPI 达到最优时间可能很久，例如 机器翻译的BLEU值，需要train很长时间BLEU值才有参考价值，收敛到最优大约为一周。这样的KPI代价很大。

**Comment by shanyi15** [comment]
您好，此issue在近一个月内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题，我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持! 
 Hello, this issue has not been updated in the past month. We will close it today for the sake of other user‘s experience. If you still need to follow up on this question after closing, please feel free to reopen it. In that case, we will get back to you within 24 hours. We apologize for the inconvenience caused by the closure and thank you so much for your support of PaddlePaddle Group!
