### ISSUE TITLE
docker编译build.sh出错

### ISSUE THREAD

**Issue by jiaozhusos** [PaddlePaddle/Paddle#10084]
使用win7下载docker，安装成功；在docker中使用paddle也显示成功，但是编译build.sh时，报错
（win7，无GPU）使用docker run -it -v $PWD:/paddle -e "WITH_GPU=OFF" -e  docker.paddlepaddlehub.com/paddle:latest-dev bash -x /paddle/paddle/scripts/docker/build.sh命令，显示错误如下：
C:\Program Files\Docker Toolbox\docker.exe: error pulling image configuration: G
et https://dseasb33srnrn.cloudfront.net/registry-v2/docker/registry/v2/blobs/sha
256/59/59507b30b48ad1faa1fa804b635b1fe0d17c60315722d622d1ed89ca1481192b/data?Exp
ires=1524250567&Signature=WXFurMrvl4Y0Wrrl4SmA-y6prVV5e7nyL9BcVFhpeHfcjPIWHyUMKm
llP-AAkYCijfAJeFDZWYbhBaV03j34hN5r8H8TP3My7fKdDrhg0Xcvdy0n5QOyzDtGag1JKYvQBzJq1n
9u7K5hFKsj~MzZaOeGmSdSv9tksIbz2ayF8~c_&Key-Pair-Id=APKAJECH5M7VWIS5YZ6Q: net/htt
p: TLS handshake timeout.
See 'C:\Program Files\Docker Toolbox\docker.exe run --help'.

**Comment by seiriosPlus** [comment]
编译过程中诸多资源需要连接国外网站下载， 请检查网络设置及代理
