### ISSUE TITLE
no-avx 的 paddlepaddle 有没有最新的镜像可以下载

### ISSUE THREAD

**Issue by Zhaoyangzhen** [PaddlePaddle/Paddle#10083]
官网提供的安装方式都试了一遍，还是没能装好。。。装一次要好几个小时，装好了也不能用。。。

官方可以提供最新稳定版的下载吗。。。心态都崩了。。。

**Comment by Zhaoyangzhen** [comment]
pip install paddlepaddle-0.11.0-cp27-cp27mu-linux_x86_64.whl 以后要怎么创建 docker 镜像

**Comment by seiriosPlus** [comment]
如果你以docker镜像的方式使用PaddlePaddle，建议参考http://www.paddlepaddle.org/docs/develop/documentation/fluid/zh/build_and_install/docker_install_cn.html

**Comment by Zhaoyangzhen** [comment]
执行 `docker pull paddlepaddle/paddle` 默认装的是有 avx 指令集的版本，但是我的机器不支持 avx 指令集

执行 `docker pull paddlepaddle/paddle:latest-noavx-openblas` 可以安装没有 noavx 指令集的版本，刚开始测试也是成功的，但是后来这个版本更新了以后又不能用了

**Comment by Zhaoyangzhen** [comment]
想找一个稳定的最新版来用

**Comment by seiriosPlus** [comment]
我们最近也在做一系列的工作来保证更新和升级不影响以前的功能。
“执行 docker pull paddlepaddle/paddle:latest-noavx-openblas 可以安装没有 noavx 指令集的版本，刚开始测试也是成功的，但是后来这个版本更新了以后又不能用了” 具体是出现了什么问题呢

**Comment by seiriosPlus** [comment]
可以考虑不用最新的latest， 用之前的稳定版本.

**Comment by seiriosPlus** [comment]
你贴一下报错信息吧

**Comment by Zhaoyangzhen** [comment]
执行测试程序的 `paddle.init(use_gpu=False, trainer_count=1)` 这一句的时候会报 `illegal instruction`

**Comment by Zhaoyangzhen** [comment]
我看到 latest-noavx-openblas 版本 14 个小时前又更新了，我再去试试。。。您辛苦了。。。

**Comment by Zhaoyangzhen** [comment]
有一个问题就是.whl文件是干啥用的。。怎么用。。。

**Comment by seiriosPlus** [comment]
.whl是Python的模块安装包，可以直接用pip install安装

**Comment by Zhaoyangzhen** [comment]
那 pip install *.whl 之后会有什么效果呢？
如果是在一个 docker 容器中 pip install *.whl  之后这个容器可以 commit 为一个 paddlepaddle 镜像来用吗？

**Comment by seiriosPlus** [comment]
可以的. paddlepaddle 的镜像就是它内部装好了这个whl和环境依赖

**Comment by Zhaoyangzhen** [comment]
谢谢您，我试一下

**Comment by Zhaoyangzhen** [comment]
试了一下最新的 latest-noavx-openblas 只要解决字符集的问题就可以用，谢谢您了！
