### ISSUE TITLE
这样安装0.11有问题吗

### ISSUE THREAD

**Issue by yyhlvdl** [PaddlePaddle/Paddle#10095]
我用docker编译了源码，然后生成了whl文件，然后我pip安装如下：
$pip install paddlepaddle_gpu-0.11.1a2-cp27-cp27mu-linux_x86_64.whl
Processing ./paddlepaddle_gpu-0.11.1a2-cp27-cp27mu-linux_x86_64.whl
Requirement already satisfied: protobuf==3.1 in /usr/local/lib/python2.7/dist-packages (from paddlepaddle-gpu==0.11.1a2) (3.1.0)
Requirement already satisfied: rarfile in /usr/local/lib/python2.7/dist-packages (from paddlepaddle-gpu==0.11.1a2) (3.0)
Requirement already satisfied: requests==2.9.2 in /usr/local/lib/python2.7/dist-packages (from paddlepaddle-gpu==0.11.1a2) (2.9.2)
Requirement already satisfied: recordio>=0.1.0 in /usr/local/lib/python2.7/dist-packages (from paddlepaddle-gpu==0.11.1a2) (0.1.5)
Requirement already satisfied: matplotlib in /usr/local/lib/python2.7/dist-packages (from paddlepaddle-gpu==0.11.1a2) (2.1.1)
Requirement already satisfied: Pillow in /usr/local/lib/python2.7/dist-packages (from paddlepaddle-gpu==0.11.1a2) (4.3.0)
Requirement already satisfied: numpy>=1.12 in /usr/local/lib/python2.7/dist-packages (from paddlepaddle-gpu==0.11.1a2) (1.13.3)
Collecting opencv-python (from paddlepaddle-gpu==0.11.1a2)
  Using cached https://files.pythonhosted.org/packages/57/81/0a678c3f457f880c26ab4bd32c4bdcd3fb6fa5d335e9e8683798d290c9b3/opencv_python-3.4.0.12-cp27-cp27mu-manylinux1_x86_64.whl
Requirement already satisfied: nltk>=3.2.2 in /usr/local/lib/python2.7/dist-packages (from paddlepaddle-gpu==0.11.1a2) (3.2.5)
Collecting scipy>=0.19.0 (from paddlepaddle-gpu==0.11.1a2)
  Using cached https://files.pythonhosted.org/packages/9c/0b/5deb712a9ea5bb0a1de837d04ef7625c5f3ee44efe7ed0765ceda681d7f1/scipy-1.0.1-cp27-cp27mu-manylinux1_x86_64.whl
Requirement already satisfied: graphviz in /usr/local/lib/python2.7/dist-packages (from paddlepaddle-gpu==0.11.1a2) (0.8.1)
Requirement already satisfied: six>=1.9 in /usr/local/lib/python2.7/dist-packages (from protobuf==3.1->paddlepaddle-gpu==0.11.1a2) (1.11.0)
Requirement already satisfied: setuptools in /usr/local/lib/python2.7/dist-packages (from protobuf==3.1->paddlepaddle-gpu==0.11.1a2) (38.2.4)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python2.7/dist-packages (from matplotlib->paddlepaddle-gpu==0.11.1a2) (0.10.0)
Requirement already satisfied: pytz in /usr/local/lib/python2.7/dist-packages (from matplotlib->paddlepaddle-gpu==0.11.1a2) (2017.3)
Requirement already satisfied: subprocess32 in /usr/local/lib/python2.7/dist-packages (from matplotlib->paddlepaddle-gpu==0.11.1a2) (3.2.7)
Requirement already satisfied: python-dateutil>=2.0 in /usr/local/lib/python2.7/dist-packages (from matplotlib->paddlepaddle-gpu==0.11.1a2) (2.6.1)
Requirement already satisfied: backports.functools-lru-cache in /usr/local/lib/python2.7/dist-packages (from matplotlib->paddlepaddle-gpu==0.11.1a2) (1.4)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 in /usr/local/lib/python2.7/dist-packages (from matplotlib->paddlepaddle-gpu==0.11.1a2) (2.2.0)
Requirement already satisfied: olefile in /usr/local/lib/python2.7/dist-packages (from Pillow->paddlepaddle-gpu==0.11.1a2) (0.44)
Installing collected packages: opencv-python, scipy, paddlepaddle-gpu。
可是，最后我使用的时候，出现这样的问题：
$ python train.py yan0net
Traceback (most recent call last):
  File "train.py", line 4, in <module>
    import paddle.v2.dataset.flowers as flowers
ImportError: No module named paddle.v2.dataset.flowers
有人可以帮我看看吗？这是因为什么？

**Comment by xylcbd** [comment]
+1, any solution?

**Comment by xylcbd** [comment]
官网的二进制文件太老，没有该目录。。。
