### ISSUE TITLE
send op speed gradually slows down while distributed training 

### ISSUE THREAD

**Issue by typhoonzero** [PaddlePaddle/Paddle#10100]
Below are some log I picked from the training log

```
Event                            Calls       Total       Min.        Max.        Ave.
thread0::send                    526         65361.4     67.9619     579.561     124.261

Event                            Calls       Total       Min.        Max.        Ave.
thread0::send                    526         68766.4     69.7856     327.23      130.735

Event                            Calls       Total       Min.        Max.        Ave.
thread0::send                    526         91715.7     85.9228     857.418     174.364

Event                            Calls       Total       Min.        Max.        Ave.
thread0::send                    526         99525.2     91.113      1313.42     189.211
```

**Comment by Yancey1989** [comment]
I can also reproduce this problem by [test_dist_train.py](https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/fluid/tests/unittests/test_dist_train.py), it's eariser to reproduce for others.

Edit `test_dist_train.py` to run SendOp multiple times and add `profiler` to do the benchmark

```python
    def init_client(self):
        ...
        for _ in xrange(100):
            with profiler.profiler('CPU', 'total', "profilers.log"):
                for _ in xrange(1000):
                    self.dist_out = exe.run(main, fetch_list=o)  # o is a list
```

Logs abount the performance of SendOp:
```bash
Event             Calls       Total       Min.        Max.        Ave.
thread0::send     10000       10133.3     0.749551    10.3551     1.01333
thread0::send     10000       13750.2     0.953109    8.78552     1.37502
thread0::send     10000       15515.6     1.16483     7.05126     1.55156
thread0::send     10000       18594.9     1.44097     7.06534     1.85949
thread0::send     10000       23103.2     1.1783      12.8077     2.31032
thread0::send     10000       28276.2     2.05772     12.5511     2.82762
thread0::send     10000       29984.4     2.30191     16.7885     2.99844
thread0::send     10000       35027.6     2.5842      12.1836     3.50276
thread0::send     10000       39696.3     2.86429     17.0023     3.96963
thread0::send     10000       43679.9     3.12344     21.3589     4.36799
```

20% drop in performance per 10000 calls to SendOp. I'll follow up this problem.

**Comment by Yancey1989** [comment]
https://github.com/PaddlePaddle/Paddle/blob/d89a30680e2ea4dbc00fab710513c2ca3816cf25/paddle/fluid/operators/detail/variable_response.h#L39-43

We need to create and delete the sub_scope when `use_local_scope=false`,  create&&delete scope frequencly lead to performance  degradation.

**Comment by jacquesqiao** [comment]
Thank you for finding out the reason! Very sorry to introduce this problem by using Scope create&delete. Should improve the performance of scope or use some other way to hold coming variable with the same name.

**Comment by Yancey1989** [comment]
@jacquesqiao yes and I created another issue to fix it. #10125

**Comment by gongweibao** [comment]
Now it improves, but it's not we expected:
![image](https://user-images.githubusercontent.com/10721757/39161629-3b29494a-47a4-11e8-9136-e6d3f2d7e1ba.png)

**Comment by gongweibao** [comment]
https://www.embedded.com/design/mcus-processors-and-socs/4006658/Tackling-memory-allocation-in-multicore-and-multithreaded-applications.
I will fix it.
