### ISSUE TITLE
paddle可以将rnn后的输出转为cnn的输入吗？

### ISSUE THREAD

**Issue by yyhlvdl** [PaddlePaddle/Paddle#10114]
我注意到，cnn的输出经过block_expand可以转化为rnn的输入，那么，有这样的层可以实现rnn的输出转为cnn的输入吗？

**Comment by luotao1** [comment]
> 有这样的层可以实现rnn的输出转为cnn的输入吗？

并不需要特殊的op，只要输入数据的layout是NCHW格式即可。

**Comment by yyhlvdl** [comment]
多谢回复。我可以详细的说明一下吗？我做图像识别，输入数据是3*224*224的，然后我让其经过1*1卷积：
    cov1 = paddle.layer.img_conv(
        name=name + '_1',
        input=input,
        filter_size=1,
        num_channels=channels,
        num_filters=1,
        stride=1,
        padding=0)
其输出应该是1×224×224，然后我将其通过双向GRU,为256个神经元。
然后报错如下：F0424 13:02:26.215569 26153 BaseMatrix.cu:107] Check failed: dimM + offset.bRow_ <= b.height_ (224 vs. 1)

**Comment by yyhlvdl** [comment]
@luotao1目前好像并不支持这样，我把我写的SABGRU layer转换为官网的BGRU也是同样的错误。请问，您有示范的例子吗？就拿图像分类这样的，GRU后面加CNN的。

**Comment by luotao1** [comment]
我们目前没有RNN后接CNN的例子。但使用RNN的话，原始输入需要使用序列格式的数据。

**Comment by luotao1** [comment]
RNN后面能否接个pooling再连CNN呢，这样序列数据就转成非序列数据了。

**Comment by yyhlvdl** [comment]
好的，我试试。多谢。
