### ISSUE TITLE
paddle的Inference接口

### ISSUE THREAD

**Issue by wangbin11** [PaddlePaddle/Paddle#10139]
请教一个问题，假如我的网络是INPUT->Layer1->Layer2->...->LayerN->Output_layer,
在infer的过程中，
inferer = Inference(output_layer=Layer2, parameters=parameters)
inferer.infer(field=field, input=input, feeding=feeding).
那么后面的Layer3 到Output_layer这些网络层还会计算一遍吗

**Comment by Yancey1989** [comment]
不会再算了，只会算到Layer2。

**Comment by wangbin11** [comment]
谢谢 @Yancey1989
