### ISSUE TITLE
iOS编译错误

### ISSUE THREAD

**Issue by Devil-yan** [PaddlePaddle/Paddle#10138]
根据文档 http://www.paddlepaddle.org/docs/develop/mobile/zh//cross_compiling_for_ios_cn.html
cmake -DCMAKE_SYSTEM_NAME=iOS \
      -DIOS_PLATFORM=OS \
      -DIOS_ARCH="armv7;arm64" \
      -DIOS_ENABLE_BITCODE=ON \
      -DIOS_USE_VECLIB_FOR_BLAS=ON \
      -DCMAKE_INSTALL_PREFIX=your/path/to/install \
      -DWITH_C_API=ON \
      -DWITH_TESTING=OFF \
      -DWITH_SWIG_PY=OFF \
      ..
报错信息如下：
/paddle/parameter/Argument.cpp:328:31: error: lambda capture 'stream' is not
      used [-Werror,-Wunused-lambda-capture]
  auto copyStrs = [batchSize, stream](SVectorPtr& dst,

**Comment by Yancey1989** [comment]
可能是XCode或者clang版本太高的原因，之前测试过的版本是XCode9， @Devil-yan 您的编译器版本是多少呢？

**Comment by Devil-yan** [comment]
Version 9.3 (9E145)

**Comment by Devil-yan** [comment]
Version 9.3 (9E145)

**Comment by Yancey1989** [comment]
I reopened this issue and will create a PR to fix this issue.

**Comment by Yancey1989** [comment]
This issue has already been fixed by # 10165, so I close this again.
