### ISSUE TITLE
build.sh编译出错

### ISSUE THREAD

**Issue by jiaozhusos** [PaddlePaddle/Paddle#10131]
win7使用docker安装paddlepaddle，在在最后的build.sh编译中，使用以下代码：
docker run -it -v $PWD:/paddle -e "WITH_GPU=OFF" -e "WITH_AVX=OFF" -e "-DWITH_TESTING=OFF" docker.paddlepaddlehub.com/paddle:latest-dev bash -x /paddle/paddle/scripts/docker/build.sh
进行编译时，报下面的错误：
error: The following untracked working tree files would be overwritten by checko
ut:

Please move or remove them before you can switch branches.
Aborting
CMake Error at /paddle/build/third_party/protobuf/tmp/extern_protobuf-gitclone.c
make:49 (message):
  Failed to checkout tag: '9f75c5aa851cd877fb0d93ccc31b8567a6706546'

CMakeFiles/extern_protobuf.dir/build.make:89: recipe for target 'third_party/pro
tobuf/src/extern_protobuf-stamp/extern_protobuf-download' failed
make[2]: *** [third_party/protobuf/src/extern_protobuf-stamp/extern_protobuf-dow
nload] Error 1
CMakeFiles/Makefile2:576: recipe for target 'CMakeFiles/extern_protobuf.dir/all'
 failed
make[1]: *** [CMakeFiles/extern_protobuf.dir/all] Error 2
Makefile:160: recipe for target 'all' failed
make: *** [all] Error 2

这是由于什么原因呢？需要怎样修改？

**Comment by jiaozhusos** [comment]
你好，看了一下，protobuf大小75MHZ，应该没错啊

**Comment by jiaozhusos** [comment]
主要是：
error: The following untracked working tree files would be overwritten by checko
ut:

Please move or remove them before you can switch branches.
Aborting
CMake Error at /paddle/build/third_party/protobuf/tmp/extern_protobuf-gitclone.c
make:49 (message):
Failed to checkout tag: '9f75c5aa851cd877fb0d93ccc31b8567a6706546'
查了一下，可能和git有关，但是使用命令  git clean -d -fx  就会把build里的大部分文件都强制删除了，再编译还是会报同样的错误

**Comment by jiaozhusos** [comment]
可是.git文件还是有内容的；之前我是把整个paddle文件都删除，重新
git clone https://github.com/PaddlePaddle/Paddle.git
之后 cd Paddle
最后再build的
还是报上面最初始的错误。。。。

**Comment by Yancey1989** [comment]
> error: The following untracked working tree files would be overwritten by checko
ut:

这看起来还是git有冲突无法checkout造成的，可以把protobuf那个目录删掉再试试。
或者也有可能和WIndows下Docker的mount有关系，可以尝试在容器里git clone再build

**Comment by jiaozhusos** [comment]
额，还是解决不了，放弃windows了，准备用centos7试一下。是不是直接用pip安装，再用docker编译（或源码编译）就可以了。因为python2.7是在anaconda下的envs里，不知道会不会受影响~
