### ISSUE TITLE
Memory Leak by malloc by new and free by free

### ISSUE THREAD

**Issue by houqi** [PaddlePaddle/Paddle#10159]
https://github.com/PaddlePaddle/Paddle/blob/d67b9ced051dfc0cca377755f4acba1424ea297f/paddle/api/Matrix.cpp#L280

Memory is freed in numpy with `free` but allocated in Paddle with new.

**Comment by luotao1** [comment]
What's your problem? Can you describe in more details?

**Comment by typhoonzero** [comment]
Closing due to low activity, feel free to reopen.
