### ISSUE TITLE
Check failed: testContext_.numSamples > 0 (0 vs. 0) There is no samples in your test batch. Possibly wrong implementation of DataProvidor.reset()

### ISSUE THREAD

**Issue by SheldonZHANG** [PaddlePaddle/Paddle#10154]
麻烦看一下这个是什么问题。我的paddle/test_data_dir/下面是有数据的，为什么告诉我没有测试数据

任务链接： http://10.89.188.24:8900/fileview.html?path=/home/disk1/normandy/maybach/app-user-20180423151546-41729/

**Comment by luotao1** [comment]
因为LOG比较大，能否直接贴出错误信息

**Comment by SheldonZHANG** [comment]
Log file created at: 2018/04/23 17:25:57
Running on machine: yq01-hpc-lvliang-d0627.yq01.baidu.com
Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
F0423 17:25:57.552273 42134 Tester.cpp:124] Check failed: testContext_.numSamples > 0 (0 vs. 0) There is no samples in your test batch. Possibly wrong implementation of DataProvidor.reset()

**Comment by SheldonZHANG** [comment]
![image](https://user-images.githubusercontent.com/4178111/39162369-c56068b6-47a7-11e8-8728-d973b87f718b.png)

**Comment by luotao1** [comment]
> Possibly wrong implementation of DataProvidor.reset()

请问本地使用测试数据，是否正常？

**Comment by typhoonzero** [comment]
Closing due to low activity, feel free to reopen.
