### ISSUE TITLE
paddle的image_classification是否有其他imagenet已经训练的好的模型

### ISSUE THREAD

**Issue by donote** [PaddlePaddle/Paddle#1015]
网上model zoo提供的imagenet数据利用caffe训练好的其他网络模型，请问是否可以用于paddle，paddle自身是否提供了imagenet数据训练的模型呢，谢谢

**Comment by reyoung** [comment]
@qingqing01 正在开发。近期会上线这个事情。

**Comment by qingqing01** [comment]
@donote  

>  请问是否可以用于paddle
可以用于Paddle， 教程里面提供一些提取特征、预测等使用方式。

关于其他ImageNet训好的模型，私下里有训练，只是并没有开放到官网。如果想转换Caffe模型，https://github.com/PaddlePaddle/Paddle/issues/964  这里转换参考方式。

-  关于ImageNet模型训练

如果准备好数据list，可以根据下面repo来训练ImageNet数据，原理和Image_classification的demo是一样的。 

https://github.com/qingqing01/ImageModel/tree/master/resnet_imagenet_100/paddle

关于数据读取的加速，这里提供了Python多进程加速方式， 注释里面有用法，推荐使用这种方式。

https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/utils/image_multiproc.py#L183

另外，https://github.com/PaddlePaddle/Image  这个repo里也增加C++多线程加速方式，后续后增加更多data argumentation操作。 

后面会整理一篇使用方法，如果您需要其他ImageNet模型，目前可以参考上面方式训练，也可以转换其他模型。
