### ISSUE TITLE
请问，现在gpu训练的cnn，有CPU预测的c++ lib 吗

### ISSUE THREAD

**Issue by yinyunfeng** [PaddlePaddle/Paddle#1016]
请问，现在gpu训练的cnn，有cpu预测的c++lib吗

**Comment by backyes** [comment]
@yinyunfeng 

理论上预测不依赖训练时使用的平台。 

参看下： https://github.com/PaddlePaddle/Paddle/issues/379  

@reyoung @hedaoyuan 也请给点意见。

**Comment by reyoung** [comment]
> 现在gpu训练的cnn，有cpu预测的c++lib吗

目前有Python的library可以做这些。C/C++的lib正在开发。

**Comment by yinyunfeng** [comment]
@reyoung 
这个有排期吗，大概多久能用

**Comment by QiJune** [comment]
目前已支持CAPI的预测模块，请参考https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/capi/examples/model_inference/README.md
