### ISSUE TITLE
Resources for the SRL model 

### ISSUE THREAD

**Issue by belomeriem** [PaddlePaddle/Paddle#10175]
Dear all, I am working with the SRL parser now, trying to retrain it, however, I can't really find the models you mention in the tutorial http://www.paddlepaddle.org/docs/develop/book/07.label_semantic_roles/index.html#permalink-9-train-model
<img width="668" alt="screen shot 2018-04-24 at 1 40 52 pm" src="https://user-images.githubusercontent.com/6345293/39185026-fb922c4e-47c5-11e8-904b-d8cac597700e.png">
Could you please me know if I could get these models somehow? Thanks!

**Comment by luotao1** [comment]
Please refer: https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/v2/dataset/conll05.py

**Comment by belomeriem** [comment]
Super helpful, thanks!
