### ISSUE TITLE
能用paddlepaddle编写自己的激活函数吗？能用paddlepaddle做迁移学习吗？

### ISSUE THREAD

**Issue by kingdsz** [PaddlePaddle/Paddle#10183]
能用paddlepaddle编写自己的激活函数吗？如有例子，请分享。能用paddlepaddle做迁移学习吗？如有例子求分享。

**Comment by typhoonzero** [comment]
您好，建议先阅读[编写新的Operator](http://www.paddlepaddle.org/docs/develop/documentation/fluid/zh/dev/new_op_cn.html)，激活函数本质上也是一个Operator。然后具体写法可以参考https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/fluid/operators/activation_op.h编写激活的c++ kernel，并在`activation_op.cc`中定义激活函数的operator，最后在`python/paddle/fluid/layers/ops.py`中的`__activations__`中增加对应的operator的名字即可。

PaddlePaddle欢迎您的贡献！

**Comment by chengduoZH** [comment]
如果想验证激活函数是否正确，还可以额外的添加单测。

**Comment by kingdsz** [comment]
@typhoonzero @chengduoZH 那用paddlepaddle能做迁移学习吗

**Comment by typhoonzero** [comment]
可以参考：https://github.com/PaddlePaddle/Paddle/issues/6075

**Comment by ktlichkid** [comment]
Closed due to low activity. Please feel free to reopen it if you have further questions.
