### ISSUE TITLE
有两个loss函数，怎么样按照比例叠加loss得到新的loss函数

### ISSUE THREAD

**Issue by chenbblei** [PaddlePaddle/Paddle#10188]
cost_attention = paddle.layer.classification_cost(input=decoder, label=lbl)和
 ctc_loss = paddle.layer.warp_ctc(
        input=fc,
        label=text_data,
        size=dict_size + 1,
        blank=dict_size,
        norm_by_times=True)
以上两个cost函数，怎么样才能返回个loss=0.5*cost_atttention+0.5*ctc_loss这样的loss函数呢，
如何实现呢，请求帮助

**Comment by typhoonzero** [comment]
可以从官方文档：http://www.paddlepaddle.org/docs/develop/api/fluid/en/layers.html 中根据您具体使用的版本找到sum layer的具体使用方法，比如fluid的sum是：http://www.paddlepaddle.org/docs/develop/api/fluid/en/layers.html#sums

**Comment by chenbblei** [comment]
@typhoonzero     
loss = fluid.layers.sums(input=[cost_attention,ctc_loss])
  File "/data/anaconda2/lib/python2.7/site-packages/paddle/fluid/layers/tensor.py", line 169, in sums
    out = helper.create_tmp_variable(dtype=helper.input_dtype())
  File "/data/anaconda2/lib/python2.7/site-packages/paddle/fluid/layer_helper.py", line 97, in input_dtype
    inputs = self.multiple_input(input_param_name)
  File "/data/anaconda2/lib/python2.7/site-packages/paddle/fluid/layer_helper.py", line 59, in multiple_input
    raise type_error
TypeError: Input of sum layer should be Variable or sequence of Variable

报这个错啦

**Comment by typhoonzero** [comment]
额，你之前的代码是v2的吧？如果是得用对应v2的layer

**Comment by chenbblei** [comment]
@typhoonzero 但是v2里面没有看到sum函数，官方文档。。。。。。

**Comment by typhoonzero** [comment]
应该是这个：http://www.paddlepaddle.org/docs/develop/api/en/config/layer.html#linear-comb

**Comment by typhoonzero** [comment]
试下http://www.paddlepaddle.org/docs/develop/api/en/config/layer.html#permalink-98-sum_cost `sum_cost`处理下ctc_loss，然后在用`scaling`求平均，然后再把两个加起来，v2没有试过，https://github.com/PaddlePaddle/Paddle/issues/2913 这里是v1的方法

**Comment by chenbblei** [comment]
@typhoonzero 好的，我试试
