### ISSUE TITLE
推荐模型准确度问题

### ISSUE THREAD

**Issue by zhegeliang2** [PaddlePaddle/Paddle#10194]
请问movielens这个数据集合上的这个深度模型的误差是不是算很大？正常即使我们用lr，fm，或者矩阵分解来预测，误差值比这个要好很多。

**Comment by typhoonzero** [comment]
您好，是否是指：https://github.com/PaddlePaddle/book/tree/develop/05.recommender_system 这个模型。如果是，这个模型只是作为Paddle的教程，并没有严格验证效果，如果寻找fine tuned模型，可以参考：https://github.com/PaddlePaddle/models 下的ltr, ctr, deep_fm等相关模型。

**Comment by typhoonzero** [comment]
Closing due to low activity, feel free to reopen.
