### ISSUE TITLE
PaddlePaddle文档能不能有跟tensorflow一样的类似很方便查询的网站

### ISSUE THREAD

**Issue by chenbblei** [PaddlePaddle/Paddle#10195]
如题，感觉PaddlePaddle架构很好，但是文档太少了，每添加一个新功能，都得找示例找半天，而且很不一定找到

**Comment by typhoonzero** [comment]
请参考官网http://www.paddlepaddle.org/ 是否可以解决您的问题呢。

**Comment by chenbblei** [comment]
@typhoonzero 谢谢你，但这个做得确实不够好，好多函数搜索都无法搜索到，比如搜索classification_cost显示没有匹配的。。。。

**Comment by chenbblei** [comment]
@typhoonzero 好的，多谢，希望尽快解决哈，个人比较喜欢paddlepaddle，希望文档能完善好
