### ISSUE TITLE
PaddlePaddle如何显示的更新权重，比如直接可以调用w=w-梯度*系数，这种写法，而不是直接调用train，有代码实例么？

### ISSUE THREAD

**Issue by chenbblei** [PaddlePaddle/Paddle#10197]
如题

**Comment by typhoonzero** [comment]
Fluid是可以完全自定义计算的，目前还没有类似demo程序，因为现在的模型都是自动生成反向计算的，手动写反向计算是比较困难的。如果感兴趣可以参考[nn.py](https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/fluid/layers/nn.py)中如何向 `ProgramDesc`中增加计算的operators，使用同样的方法可以手动构建计算的流程。

另外，您可以详细描述下具体要做什么事情，达成什么目标，PaddlePaddle可能有更直接的解决方案。

**Comment by chenbblei** [comment]
暂时不需要此种方法
