### ISSUE TITLE
加载参数 load parameter

### ISSUE THREAD

**Issue by shboy** [PaddlePaddle/Paddle#10205]
我的output是这样的 
47      fc_last = paddle.layer.pooling(
 48             input=inputs[0], pooling_type=paddle.pooling.Max())
 49     lstm_last = paddle.layer.pooling(
 50             input=inputs[1], pooling_type=paddle.pooling.Max())
 51     if infer == True:
 52         output = paddle.layer.concat(fc_last,lstm_last)
 53         return output

然后我load了以前的训练parameter

    with open(para_path_2, "r") as f:
        parameters_2 = paddle.parameters.Parameters.from_tar(f)

后面还要加fc层

想把parameter赋给output 怎么办？

**Comment by typhoonzero** [comment]
> 想把parameter赋给output 怎么办？

每理解这句话。如果是load的parameter和模型的定义有区别，可以用`init_from_tar`，会自动加载到parameter name相同的参数中。

**Comment by shboy** [comment]
output_2 = stacked_lstm_net(False, dict_dim, class_dim=class_dim_2, stacked_num=3)
   output_3 = stacked_lstm_net(False, dict_dim, class_dim=class_dim_3, stacked_num=3)

            
    with open(para_path_2, "r") as f:
        parameters_2 = paddle.parameters.Parameters.from_tar(f)
    with open(para_path_3, "r") as f:
        parameters_3 = paddle.parameters.Parameters.from_tar(f)

    input = layer.concat(output_2, out_put3)

    out = layer.fc(input)

**Comment by shboy** [comment]
我的网络的结构大概是这样的

然后我现在不知道怎么把parameter_2、parameter_3分别加载到output_2, out_put3上

**Comment by typhoonzero** [comment]
首先，parameter是不能加载到output上的，parameter是指layer中可训练的参数。看你贴的代码，我理解是有两个预先训练好的lstm的参数，现在希望合并这两个配置中的lstm层生成一个新的模型，并复用之前模型的参数。这样，如果其他层的参数不希望从文件加载，可以先将之前训练的参数`para_path_2 `和`para_path_3 `，解压，然后删除其中其他层的参数只保留lstm层的所有参数。然后用`init_from_tar `加载。

**Comment by typhoonzero** [comment]
Closing due to low activity, feel free to reopen.
