### ISSUE TITLE
Refine argument naming for ParallelExecutor

### ISSUE THREAD

**Issue by pkuyym** [PaddlePaddle/Paddle#10219]
Seems `customize_loss_grad` is not very self-explanatory and there's is no doc for this argument. I propose to change it to a more clear name like `use_default_grad_scale` and the default value is `true`. @reyoung @panyx0718 Need your opinion. Thanks. 

https://github.com/PaddlePaddle/Paddle/blob/bfafcbeefbdddd581608b2a5bd3559a2175503e2/python/paddle/fluid/parallel_executor.py#L33

**Comment by panyx0718** [comment]
sounds good, need some comments to explain.
