### ISSUE TITLE
回归预测的实验运行出错！

### ISSUE THREAD

**Issue by water1981** [PaddlePaddle/Paddle#1021]
输入 是1100*16的稀疏向量，用空格分隔，第一列是label，剩下1100列是特征（特征编号:1），格式如下
1 9:1 29:1 45:1 58:1 70:1 82:1 102:1 116:1 135:1 146:1 162:1 178:1 203:1 211:1 236:1 242:1 267:1 282:1 290:1 306:1 327:1 342:1 354:1 378:1 386:1 411:1 425:1 433:1 455:1 479:1 .....

dataprovider:
```python
@provider(
    input_types=[
                 sparse_binary_vector(1100*16),
                 dense_vector(1)]
         )
def process(settings, file_name):
    with open(file_name, 'r') as f:
        for line_count, line in enumerate(f):
            label= line.strip().split(' ')[0]
            feature_vector =[int(feat.split(':')[0])-1 for feat in line.strip().split(' ')[1:]]
            yield feature_vector,[int(label)]
```

训练配置文件 trainer_config.lr.py：
```python
is_predict = get_config_arg('is_predict', bool, False)
trn = 'data/train.list' if not is_predict else None
tst = 'data/test.list'
process = 'process'



define_py_data_sources2(train_list=trn,
                        test_list=tst,
                        module="dataprovider",
                        obj=process,
                        )

batch_size = 1 if not is_predict else 1
settings(
    batch_size=batch_size,
    learning_rate=2e-3,
    learning_method=AdaDeltaOptimizer(),
)

drop_rate=0.5
default_decay_rate(1e-4 * batch_size)
hidden_dim=512
default_initial_std(1 / math.sqrt(hidden_dim))


data = data_layer(name="feature", size=1100*16)
score = data_layer(name="label",size=1)


layer1 = fc_layer(input=data, size=256,act=LinearActivation(),param_attr=ParameterAttribute(name='_fc1_w_',initial_mean=0,initial_std=1/math.sqrt(256)))
output = fc_layer(input=layer1,size=1,act=LinearActivation(),param_attr=ParameterAttribute(name='_predict_w',initial_mean=0,initial_std=1/math.sqrt(2)))



if not is_predict:
    outputs(regression_cost(input=output,
                            label=score))
else:
    outputs(output)
```

训练脚本 train.sh：

```bash
set -e

cfg=trainer_config.lr.py
/home/img/liushui/bin/paddle train \
  --config=$cfg \
  --save_dir=./output \
  --trainer_count=4 \
  --log_period=20 \
  --num_passes=15 \
  --use_gpu=false \
  --show_parameter_stats_period=1 \
  --dot_period=1 \
  --test_all_data_in_one_period=1 \
  2>&1 | tee 'train.log'
```

运行 nohup bash train.sh & 后，一直停在初始化的提示上面：

```text
I /home/img/baidu/idl/paddle/paddle/utils/Util.cpp:138] commandline: /home/img/liushui/bin/../opt/paddle/bin/paddle_trainer --config=trainer_config.lr.py --save_dir=./output --trainer_count=4 --log_period=20 --num_passes=15 --use_gpu=false --show_parameter_stats_period=1 --dot_period=1 --test_all_data_in_one_period=1
I /home/img/baidu/idl/paddle/paddle/utils/Util.cpp:113] Calling runInitFunctions
I /home/img/baidu/idl/paddle/paddle/utils/Util.cpp:126] Call runInitFunctions done.
[INFO 2016-12-27 16:22:02,662 networks.py:1122] The input order is [feature, label]
[INFO 2016-12-27 16:22:02,662 networks.py:1129] The output order is [__regression_cost_0__]
I /home/img/baidu/idl/paddle/paddle/trainer/Trainer.cpp:169] trainer mode: Normal
I /home/img/baidu/idl/paddle/paddle/gserver/dataproviders/PyDataProvider2.cpp:247] loading dataprovider dataprovider::process
I /home/img/baidu/idl/paddle/paddle/gserver/dataproviders/PyDataProvider2.cpp:247] loading dataprovider dataprovider::process
I /home/img/baidu/idl/paddle/paddle/gserver/gradientmachines/GradientMachine.cpp:134] Initing parameters..
I /home/img/baidu/idl/paddle/paddle/gserver/gradientmachines/GradientMachine.cpp:141] Init parameters done.
```

**Comment by reyoung** [comment]
这块比较慢的话，应该是读取数据的速度比较慢。参考 [FAQ](https://github.com/PaddlePaddle/Paddle/blob/develop/doc/faq/index_cn.rst#id6)

**Comment by water1981** [comment]
是train.conf 里面还是，layer里面？

**Comment by water1981** [comment]
layer1 = fc_layer(input=data, size=256,act=LinearActivation(),param_attr=ParameterAttribute(name='_fc1_w_',sparse_update=True,initial_mean=0,initial_std=1/math.sqrt(256)))

改完以后出core
显示：

 /home/img/.jumbo/lib/python2.7/site-packages/paddle/trainer/config_parser.py : 3159
            trainer_config.lr.py : 83
            /home/img/.jumbo/lib/python2.7/site-packages/paddle/trainer_config_helpers/data_sources.py : 203
            /home/img/.jumbo/lib/python2.7/site-packages/paddle/trainer_config_helpers/data_sources.py : 153
            /home/img/.jumbo/lib/python2.7/site-packages/paddle/trainer_config_helpers/data_sources.py : 94
            /home/img/.jumbo/lib/python2.7/site-packages/paddle/trainer/config_parser.py : 936
            /home/img/.jumbo/lib/python2.7/site-packages/paddle/trainer/config_parser.py : 162
            /home/img/.jumbo/lib/python2.7/site-packages/paddle/trainer/config_parser.py : 3124
Call Object failed.
/home/img/liushui/bin/paddle: line 81: 21327 Aborted                 (core dumped) ${DEBUGGER} $MYDIR/../opt/paddle/bin/paddle_trainer ${@:2}

**Comment by reyoung** [comment]
看起来是改的有问题，请注意一下`trainer_config.lr.py : 83`和`data_sources `相关的部分。

**Comment by water1981** [comment]
能把你修改的部分贴上来吗？多谢，我所有的文件都写在帖子里面了。

**Comment by water1981** [comment]
为了加速，我设置了：
layer1 = fc_layer(input=data, size=512,act=TanhActivation(),param_attr=ParameterAttribute(name='_fc1_w_',initial_mean=0,initial_std=1/math.sqrt(input_size),sparse_update=True))

结果提示：
F /home/img/baidu/idl/paddle/paddle/cuda/src/hl_cuda_device.cc:430] Check failed: (cudaSuccess) == (cudaStat) Cuda Error: an illegal memory access was encountered
/home/img/liushui/bin/paddle: line 81:  4789 Aborted                 (core dumped) ${DEBUGGER} $MYDIR/../opt/paddle/bin/paddle_trainer ${@:2}

**Comment by backyes** [comment]
@water1981 

从你的模型来看， 是可以使用sparse update训练的，但是从你提供的信息无法判定原因所在。

提问请注意： 

*  上下文连贯。 比如最早comments中，你提到『HUNG』注的问题， 至始至终你并没有反馈采纳 @reyoung 建议后的效果。 否则，突然后面又冒出sparse问题，感觉不能get到你的问题重点。

* 提问尽量在简洁和易理解性上折中。 比如， 你贴出的错误，仅仅两行异常，是很难一眼判断出异常的。尽量，能让review问题的人能快速get你的问题。

* 提问要尽量前后一致，不要让人猜测。  
比如， 你开始的命令： 
```
set -e

cfg=trainer_config.lr.py
/home/img/liushui/bin/paddle train \
  --config=$cfg \
  --save_dir=./output \
  --trainer_count=4 \
  --log_period=20 \
  --num_passes=15 \
  --use_gpu=false \
  --show_parameter_stats_period=1 \
  --dot_period=1 \
  --test_all_data_in_one_period=1 \
  2>&1 | tee 'train.log'
```
使用了use_gpu=false, 但是，你下面的错误提示是cuda异常，这也很奇怪， 是否你后面的问题是在使能了gpu下发现的呢？ 
```
Check failed: (cudaSuccess) == (cudaStat) Cuda Error: an illegal memory access was encountered
```

* 另外也建议使用markdown语法， comments 能自动被渲染。 


描述清楚的问题非常重要，否则，来来回回的确认细节，非常影响对问题的判断， :-)

**Comment by water1981** [comment]
后面我在provider设置了缓存模式快多了。

**Comment by water1981** [comment]
成功训练出模型以后，预测的时候出core ：

cfg=trainer_config.lr.py
model="output/pass-00014"

/home/img/liushui/bin/paddle train \
    --config=$cfg \
    --use_gpu=false \
    --job=test \
    --init_model_path=$model \
    --config_args=is_predict=1 \
    --predict_output_dir=. \
    2>&1 | tee 'test.log'

**Comment by water1981** [comment]
I /home/img/baidu/idl/paddle/paddle/utils/Util.cpp:138] commandline: /home/img/liushui/bin/../opt/paddle/bin/paddle_trainer --config=trainer_config.lr.py --use_gpu=false --job=test --init_model_path=output/pass-00014 --config_args=is_predict=1 --predict_output_dir=.
I /home/img/baidu/idl/paddle/paddle/utils/Util.cpp:113] Calling runInitFunctions
I /home/img/baidu/idl/paddle/paddle/utils/Util.cpp:126] Call runInitFunctions done.
[INFO 2016-12-28 19:49:06,343 networks.py:1122] The input order is [feature]
[INFO 2016-12-28 19:49:06,344 networks.py:1129] The output order is [__fc_layer_2__]
I /home/img/baidu/idl/paddle/paddle/trainer/Trainer.cpp:148] trainer: in testing mode
I /home/img/baidu/idl/paddle/paddle/trainer/Trainer.cpp:155] trainer mode: Testing
I /home/img/baidu/idl/paddle/paddle/gserver/dataproviders/PyDataProvider2.cpp:247] loading dataprovider dataprovider::process
I /home/img/baidu/idl/paddle/paddle/gserver/gradientmachines/GradientMachine.cpp:123] Loading parameters from output/pass-00014
F /home/img/baidu/idl/paddle/paddle/gserver/gradientmachines/NeuralNetwork.cpp:232] Check failed: (inArgs.size()) == (dataLayers_.size())
/home/img/liushui/bin/paddle: line 81: 27397 Aborted                 (core dumped) ${DEBUGGER} $MYDIR/../opt/paddle/bin/paddle_trainer ${@:2}

**Comment by backyes** [comment]
```
F /home/img/baidu/idl/paddle/paddle/gserver/gradientmachines/NeuralNetwork.cpp:232] Check failed: (inArgs.size()) == (dataLayers_.size())
```

```
if not is_predict:
    outputs(regression_cost(input=output,
                            label=score))
else:
    outputs(output)

```
应该是预测时的data layer和实际数据不匹配。  预测的时候，需要把label去掉吧 。

**Comment by water1981** [comment]
修改了一下dataprovider ，问题解决了！ 多谢
