### ISSUE TITLE
Check failed: cudaSuccess == cudaStat (0 vs. 39) Cuda Error: uncorrectable ECC error encountered。

### ISSUE THREAD

**Issue by 357589873** [PaddlePaddle/Paddle#10239]
在预测阶段，预测了很长时间出现了这个错误。
`F0426 17:52:54.043815 30811 hl_cuda_device.cc:565] Check failed: cudaSuccess == cudaStat (0 vs. 39) Cuda Error: uncorrectable ECC error encountered
*** Check failure stack trace: ***
    @     0x7f423a77f66d  google::LogMessage::Fail()
    @     0x7f423a78311c  google::LogMessage::SendToLog()
    @     0x7f423a77f193  google::LogMessage::Flush()
    @     0x7f423a78462e  google::LogMessageFatal::~LogMessageFatal()
    @     0x7f423a73a063  hl_stream_synchronize()
    @     0x7f423a7553ef  hl_sequence2batch_copy()
    @     0x7f423a3e1d2b  paddle::LstmLayer::forwardBatch()
    @     0x7f423a3e3462  paddle::LstmLayer::forward()
    @     0x7f423a49c68d  paddle::NeuralNetwork::forward()
    @     0x7f423a2fa9fd  _wrap_GradientMachine_forward
    @     0x7f42b2af1a22  PyEval_EvalFrameEx
    @     0x7f42b2af53bd  PyEval_EvalCodeEx
    @     0x7f42b2af3a92  PyEval_EvalFrameEx
    @     0x7f42b2af53bd  PyEval_EvalCodeEx
    @     0x7f42b2af3a92  PyEval_EvalFrameEx
    @     0x7f42b2a5fda3  gen_iternext
    @     0x7f42b2aed8eb  PyEval_EvalFrameEx
    @     0x7f42b2a5fda3  gen_iternext
    @     0x7f42b2aed8eb  PyEval_EvalFrameEx
    @     0x7f42b2af53bd  PyEval_EvalCodeEx
    @     0x7f42b2af3a92  PyEval_EvalFrameEx
    @     0x7f42b2af53bd  PyEval_EvalCodeEx
    @     0x7f42b2af3a92  PyEval_EvalFrameEx
    @     0x7f42b2af53bd  PyEval_EvalCodeEx
    @     0x7f42b2af54f2  PyEval_EvalCode
    @     0x7f42b2b20062  PyRun_FileExFlags
    @     0x7f42b2b213e9  PyRun_SimpleFileExFlags
    @     0x7f42b2b373bf  Py_Main
    @     0x7f42b2423ec5  __libc_start_main
Thread [139924447762240] Forwarding __lstmemory_0__,
*** Aborted at 1524736374 (unix time) try "date -d @1524736374" if you are using GNU date ***
PC: @                0x0 (unknown)`
我想问一下这个问题是什么造成的，之前查到解决办法是
Try disabling ECC:

sudo nvidia-smi --ecc-config=0
then reboot and retry.
我想问一下如何不重启修改？

**Comment by chengduoZH** [comment]
cudaStat为39表明程序运行过程中出现了不可纠正的ECC错误
> cudaErrorECCUncorrectable = 39
This indicates that an uncorrectable ECC error was detected during execution

而这种错误属于硬件故障，所以可能需要重启一下

这里有相关的解释：https://stackoverflow.com/questions/11839555/cuda-uncorrectable-ecc-error-encountered
