### ISSUE TITLE
make时出现编译错误

### ISSUE THREAD

**Issue by wangchen402** [PaddlePaddle/Paddle#10240]
fatal error: paddle/fluid/framework/framework.pb.h: No such file or directory
compilation terminated.
paddle/fluid/platform/CMakeFiles/device_tracer.dir/build.make:62: recipe for target 'paddle/fluid/platform/CMakeFiles/device_tracer.dir/device_tracer.cc.o' failed
make[2]: *** [paddle/fluid/platform/CMakeFiles/device_tracer.dir/device_tracer.cc.o] Error 1
CMakeFiles/Makefile2:2975: recipe for target 'paddle/fluid/platform/CMakeFiles/device_tracer.dir/all' failed
make[1]: *** [paddle/fluid/platform/CMakeFiles/device_tracer.dir/all] Error 2
Makefile:151: recipe for target 'all' failed
make: *** [all] Error 2

protobuf已经按照教程安装了3.1版本的

**Comment by chengduoZH** [comment]
请问您是在docker里面编译的吗？

**Comment by wangchen402** [comment]
不是在docker里编译的   用cmkae编译后make
