### ISSUE TITLE
使用ConcatenateLayer时，指定拼接的维度

### ISSUE THREAD

**Issue by pkuyym** [PaddlePaddle/Paddle#1024]
> A concatenate layer has multiple input layers. It concatenates rows of each input as one row for the output of this layer and apply activation.

现在想在instance维度拼接多个input也即stacking行，caffe里面可以指定拼接的维度，请问paddle里面如何实现？

**Comment by qingqing01** [comment]
PaddlePaddle里的concatenate_layer不能指定拼接的轴， 每个input当做二维矩阵，例如： 3个input，

input[0]: (H x W0), input[1]: (H x W1), input [2]: (H x W2)

H即是BatchSize， 每个input必须相等，3个input按顺序、按样本拼接，拼接成一个output，形状为：(H x (W0 + W1 + W2))，

**Comment by pkuyym** [comment]
@qingqing01 ，谢谢，我知道concatenate_layer不能指定拼接的轴，但是有没有其他layer可以实现这种拼接呢，或者通过其他方式可以满足我这个issue里面的需求，现在卡在了AUC计算：
https://github.com/PaddlePaddle/Paddle/issues/810

**Comment by hedaoyuan** [comment]
> 但是有没有其他layer可以实现这种拼接呢
可以描述你一下你的数据是几维的，需要怎样拼接？

**Comment by qingqing01** [comment]
仔细看了 #810 ，我理解你的意思是想 按行拼接？ 也就是 PyDataProvider里一次yield产生两个2样本？在计算AUC之前想拼接成两个样本？ 或许可以 先各自 调用 转置层，再拼接，然后再接AUC评估器？  另外就是自己重新基于AucEvalutor重新写个评估器？  不知道我理解是否正确？

**Comment by pkuyym** [comment]
@qingqing01 我试了一下先转置个层，再拼接，再转置，paddle报了错误，具体方案为
> prediction = fc_layer(input = hid_layer2, size = 1, act = SigmoidActivation())
> ## prob for positive sample
> with mixed_layer(size = 1, act = LogActivation()) as logProb:
>     logProb += identity_projection(input = prediction)
> neg_prediction = scaling_layer(input = prediction, weight = sign_weight)
> neg_prediction = addto_layer(input = [neg_prediction, data_layer(name = 'one_weight', size = 1)], act = LinearActivation(), bias_attr = False)
> 
> with mixed_layer(size = 1, act = LogActivation()) as neg_logProb:
>     neg_logProb += identity_projection(input = neg_prediction)
> 
> pos_predict_trans = trans_layer(input = prediction)
> neg_predict_trans = trans_layer(input = neg_prediction)
> concate_predict = concat_layer(input = [pos_predict_trans, neg_predict_trans])
> final_predict = trans_layer(concate_predict)

错误信息：

> F1229 16:13:20.923405 13110 BaseMatrix.cu:1239] Wrong argument  a.width=2 b.width=1000 columnOffset=1000
> *** Check failure stack trace: ***
>     @           0x943414  google::LogMessage::Fail()
>     @           0x94336c  google::LogMessage::SendToLog()
>     @           0x942e01  google::LogMessage::Flush()
>     @           0x945bc2  google::LogMessageFatal::~LogMessageFatal()
>     @           0x778bd5  paddle::BaseMatrixT<>::assignAtOffset()
>     @           0x612009  paddle::ConcatenateLayer::forward()
>     @           0x6ecb40  paddle::NeuralNetwork::forward()
>     @           0x6d58e3  paddle::GradientMachine::forwardBackward()
>     @           0x728be3  paddle::TrainerInternal::forwardBackwardBatch()
>     @           0x729682  paddle::TrainerInternal::trainOneBatch()
>     @           0x726ef6  paddle::Trainer::trainOneDataBatch()
>     @           0x72739d  paddle::Trainer::trainOnePass()
>     @           0x727e15  paddle::Trainer::train()
>     @           0x59cafa  main
>     @     0x7fa44a4f1bd5  __libc_start_main
>     @           0x5a8e75  (unknown)

**Comment by qingqing01** [comment]
这个问题是由于ConcatenateLayer获取output的size的时候是来自config_parse.py填充的。 而TransLayer在config_parse.py里填充的时候，无法获取到Height大小，填充不正确...

**Comment by luotao1** [comment]
Close due to the problem has been solved.
