### ISSUE TITLE
[quick start]的中不采用预处理数据，而是采用原数据处理，当cpu数量为2时，会出现多进程异步阻塞

### ISSUE THREAD

**Issue by beckett1124** [PaddlePaddle/Paddle#1025]
[quick start]的中不采用预处理数据，而是采用原数据处理，当cpu数量为2时，会出现多进程异步阻塞。

![image](https://cloud.githubusercontent.com/assets/12882811/21513223/f5fa4be6-ccf0-11e6-97c3-bc39b10f85ca.png)

![image](https://cloud.githubusercontent.com/assets/12882811/21513225/04a9d4b8-ccf1-11e6-8880-44104d66a0bc.png)

**Comment by hedaoyuan** [comment]
Close this issue, due to the code has been reconstructed.
