### ISSUE TITLE
*** Aborted at 1524797012 (unix time) try "date -d @1524797012" if you are using GNU date *** 是什么原因

### ISSUE THREAD

**Issue by chenbblei** [PaddlePaddle/Paddle#10251]
如题

**Comment by yeyupiaoling** [comment]
@chenbblei 请提供更多的信息

**Comment by chenbblei** [comment]
@yeyupiaoling self.__parameter_updater__.update(each_param)这里面崩溃出现上面的报错，cost定义如下：
decoder = paddle.layer.recurrent_group(
            name=decoder_group_name,
            step=gru_decoder_with_attention,
            input=group_inputs)

    lbl = text_data_next
    pdb.set_trace()
    cost_attention = paddle.layer.warp_ctc(
                                        input=decoder,
                                        label=lbl,
                                        size=dict_size + 1,
                                        blank=dict_size,
                                        norm_by_times=True)

**Comment by chenbblei** [comment]
再补充下：

 self.__parameter_updater__.update(each_param)
(Pdb) p each_param
<py_paddle.swig_paddle.Parameter; proxy of <Swig Object of type 'Parameter *' at 0x7ff1fc764b70> >
(Pdb) s
--Call--
> /data/anaconda2/lib/python2.7/site-packages/py_paddle/swig_paddle.py(1533)update()
-> def update(self, *args):
(Pdb) n
> /data/anaconda2/lib/python2.7/site-packages/py_paddle/swig_paddle.py(1535)update()
-> return _swig_paddle.ParameterUpdater_update(self, *args)
(Pdb) s
*** Aborted at 1524811412 (unix time) try "date -d @1524811412" if you are using GNU date ***
PC: @                0x0 (unknown)
*** SIGFPE (@0x7ff33a0c2ba9) received by PID 13269 (TID 0x7ff39529b740) from PID 973876137; stack trace: ***
    @     0x7ff394a895e0 (unknown)
    @     0x7ff33a0c2ba9 paddle::GpuVectorT<>::getAbsMax()
    @     0x7ff33a3bd7a6 paddle::OptimizerWithGradientClipping::update()
    @     0x7ff33a3b0eb5 paddle::SgdThreadUpdater::updateImpl()
    @     0x7ff33a26df21 ParameterUpdater::update()
    @     0x7ff339e07246 _wrap_ParameterUpdater_update
    @     0x7ff394d93bad PyEval_EvalFrameEx
    @     0x7ff394d94c3e PyEval_EvalCodeEx
    @     0x7ff394d941f7 PyEval_EvalFrameEx
    @     0x7ff394d94c3e PyEval_EvalCodeEx
    @     0x7ff394d941f7 PyEval_EvalFrameEx
    @     0x7ff394d94c3e PyEval_EvalCodeEx
    @     0x7ff394d941f7 PyEval_EvalFrameEx
    @     0x7ff394d94c3e PyEval_EvalCodeEx
    @     0x7ff394d941f7 PyEval_EvalFrameEx
    @     0x7ff394d94c3e PyEval_EvalCodeEx
    @     0x7ff394d941f7 PyEval_EvalFrameEx
    @     0x7ff394d94c3e PyEval_EvalCodeEx
    @     0x7ff394d94d52 PyEval_EvalCode
    @     0x7ff394db5450 PyRun_FileExFlags
    @     0x7ff394db562f PyRun_SimpleFileExFlags
    @     0x7ff394dcafd4 Py_Main
    @     0x7ff393fcfc05 __libc_start_main
    @           0x400729 (unknown)

**Comment by INotWant** [comment]
@chenbblei 请问你解决了吗？

**Comment by chenbblei** [comment]
@INotWant 已解决，需要将学习率调的很小

**Comment by dreamerleague** [comment]
同上，将学习率从e-3调到e-6，问题解决。推测问题处在学习率导致的浮点数溢出。
