### ISSUE TITLE
是否可以支持同时按照CPU和GPU版本的PaddlePaddle

### ISSUE THREAD

**Issue by yeyupiaoling** [PaddlePaddle/Paddle#10255]
有时候使用到的是CPU，但有时候又用到GPU。这个种情况下 ，是不是要安装两个版本的PaddlePaddle？
还是可以直接安装GPU版本的PaddlePaddle，这个同时支持CPU？

**Comment by kuke** [comment]
GPU的paddlepaddle同样也是支持CPU的，所以cmake的时候直接```-DWITH_GPU=ON```

**Comment by yeyupiaoling** [comment]
@kuke 那么为什么不是干脆只安装GPU版本的，这样都支持了？

**Comment by kuke** [comment]
因为不是每个用户的机器都有GPU，所以这个选择要留给用户

**Comment by yeyupiaoling** [comment]
@kuke 没有GPU就无法安装GPU版本的么？我可以安装GPU版本的，但只用CPU

**Comment by kuke** [comment]
@yeyupiaoling 当然是可以安装的，但装GPU版的时候要解决cuda的依赖问题，用户得装上各种不会用到的包，这么做很奇怪。

**Comment by yeyupiaoling** [comment]
@kuke 嗯嗯，明白，谢谢回答。
