### ISSUE TITLE
使用CAPI预测图像时，要怎么处理图像

### ISSUE THREAD

**Issue by yeyupiaoling** [PaddlePaddle/Paddle#10256]
我在这里看到的数据是随机生成的，并不是使用真正的图像：
https://github.com/PaddlePaddle/Paddle/blob/ffda2c414dcf520d2dea0ac9fccd0478dc8e081f/paddle/capi/examples/model_inference/dense/main.c#L70-L74

比如我有一个图像为`image.png`，要模型输入数据为3\*224\*224，这样要怎么处理，是在C++环境下。

**Comment by kuke** [comment]
用真实的图片数据填上这个array就行了，关于多通道怎么处理的，你可以再看看有没有其它的例子。

**Comment by yeyupiaoling** [comment]
@kuke 就是没有例子，Python的就比较多，但是C++就没有了。

**Comment by kuke** [comment]
@yeyupiaoling 这里的`array`是个数据指针，指向`mat`这个高维的tensor的数据存储的首地址。这里tensor的data layout是`NCHW`的，所以只要用NCHW的格式填充`array`就行了

**Comment by kuke** [comment]
无更多的C++代码提供， 注意看上下文，在`mat`定义的可以指定`batch_size`, `height`, `width` ...

**Comment by yeyupiaoling** [comment]
@kuke 能不能提供个代码嘛，我真不知道怎么写。

**Comment by kuke** [comment]
@yeyupiaoling 可以参考这里：

https://github.com/PaddlePaddle/Mobile/blob/849dbd3cd9076102d509ef054b8b3da72ed608a2/Demo/linux/image_io.cpp#L57

**Comment by yeyupiaoling** [comment]
可以将图像数据读取成功字节数组，然后遍历添加到array指针中就好了
