### ISSUE TITLE
batch_normal的参数怎么才能共享

### ISSUE THREAD

**Issue by JayEworld** [PaddlePaddle/Paddle#10257]
将参数名设置成一样就能实现参数共享
Paddle中batch_norm包含mean、variance、scale、offset四个参数，分别对应w1、w2、w0、wbias。
我通过设置param_attr和bias_attr可以实现后两个参数(w0和wbias)共享
那么怎么实现w1和w2的共享呢???

**Comment by kuke** [comment]
@JayEworld mean和variance的共享可以通过这个参数实现

https://github.com/PaddlePaddle/Paddle/blob/76c4ae856f3acc44ca427aeaaf35453a0f8407ae/python/paddle/trainer_config_helpers/layers.py#L3260

**Comment by kuke** [comment]
@JayEworld 应该是集群上paddle环境较老导致的这个错误
