### ISSUE TITLE
cmake error: Target "zlib" of type UTILITY may not be linked into another target.

### ISSUE THREAD

**Issue by githubgsq** [PaddlePaddle/Paddle#10278]
I typed the command:
cmake .. -DWITH_GPU=ON -DWITH_DISTRIBUTE=ON -DWITH_GOLANG=OFF -DCMAKE_INSTALL_PREFIX=$(pwd)/output/ -DPYTHON_INCLUDE_DIR=$(python -c "from distutils.sysconfig import get_python_inc; print(get_python_inc())") -DPYTHON_LIBRARY=$(python -c "import distutils.sysconfig as sysconfig; print(sysconfig.get_config_var('LIBDIR')+'/libpython2.7.so')") -DCUDNN_INCLUDE_DIR=/cuda-8.0/include/ -DCUDNN_LIBRARY=/cuda-8.0/lib64 -DBoost_INCLUDE_DIR=/third/boost/include/
but error occured:

CMake Error at cmake/util.cmake:50 (target_link_libraries):
  Target "zlib" of type UTILITY may not be linked into another target.  One
  may link only to STATIC or SHARED libraries, or to executables with the
  ENABLE_EXPORTS property set.
Call Stack (most recent call first):
  cmake/util.cmake:93 (target_circle_link_libraries)
  paddle/trainer/CMakeLists.txt:50 (link_paddle_exe)
  paddle/trainer/CMakeLists.txt:58 (add_paddle_exe)

CMake Error at cmake/util.cmake:50 (target_link_libraries):
  Target "zlib" of type UTILITY may not be linked into another target.  One
  may link only to STATIC or SHARED libraries, or to executables with the
  ENABLE_EXPORTS property set.
Call Stack (most recent call first):
  cmake/util.cmake:93 (target_circle_link_libraries)
  paddle/trainer/CMakeLists.txt:50 (link_paddle_exe)
  paddle/trainer/CMakeLists.txt:59 (add_paddle_exe)

I set CMAKE_ENABLE_EXPORTS, but it does not help.
how to solve the problem please?
Thanks!

**Comment by pkuyym** [comment]
Which `cmake` version do you use? And please check `build/third_party/zlib` whether exists?

**Comment by githubgsq** [comment]
hi, @pkuyym 
I'm using cmake3.2.2
![image](https://user-images.githubusercontent.com/23164715/39393319-863ae65a-4af6-11e8-8a26-669fb8ea647d.png)
and the directory "build/third_party/zlib" does exist, which contains directory "src" and "tmp"

**Comment by pkuyym** [comment]
@githubgsq Could you please check whether `zlib` compiled successfully? Please execute `ls build/third_party/extern_zlib-stamp` and paste the output.

**Comment by githubgsq** [comment]
hi, @pkuyym , there is no directory named "extern_zlib-stamp" under "./third_party"
but there is a "extern_zlib-stamp" directory here:
./third/zlib/src/zlib-stamp/

ll ./third_party
![image](https://user-images.githubusercontent.com/23164715/39394369-2398a8da-4b04-11e8-982c-41e331a57aad.png)
cd ./third_party/zlib/ && ll
![image](https://user-images.githubusercontent.com/23164715/39394392-492f7542-4b04-11e8-86b6-843453000c3b.png)
cd ./src/zlib-stamp/ && ll
![image](https://user-images.githubusercontent.com/23164715/39394415-6c824a38-4b04-11e8-996d-bef3820e6086.png)

**Comment by githubgsq** [comment]
The problem has been solved! 
I altered cmake/external/zlib.cmake before, but the line "INCLUDE_DIRECTORIES(${THIRD_PARTY_PATH}/install)" was removed by mistake.
If anyone has met the same problem, maybe you can check the zlib.cmake file.
