### ISSUE TITLE
Fluid distributed training TODO

### ISSUE THREAD

**Issue by Yancey1989** [PaddlePaddle/Paddle#10279]
## Fluid Distribute Training Features

- code cleanup and polish 
- implement LARS to improve training performance, #6811
- fault-tolerant
    - checkpointing and recovering parameters on pserver
    - recover reader offset(may need master and etcd)
    - trainer pre-fetch parameters from pserver after the restart
- async training, #9941 
- distributed data reader(should unify with single machine reader)
- calculate global AUC with the distributed table
- initialize trainable parameters from saved parameters on a trainer
- ring-base architecture to improve training performance
- distributed lookup table, https://github.com/PaddlePaddle/Paddle/projects/56
- full overlapping with parallel-executor on dist training
- split send_op into multiple send_vars_op and fetch_vars_op, #9161

## EDL
- implement the master process to schedule task
- etcd operator
- implement CRD to support kubernetes v1.8

## Support different communication library 
- gRPC performance enhancement
- OpenMPI with RDMA and GPU direct
- NCCL2 with multiple nodes
- follow up bRPC

## Experiment
- different distributed training strategy (sync, async etc...) influence on model accuracy/throughput

## CE
- Auto execute benchmark-job on AWS and generate a report

## Future
- differences between multi-machine-single-device and multi-machine-multi-device
- better integration with single-machine training
- think about more flexible user-customized device placement for multi-machine training.
- need to discuss whether we need the remote executor

**Comment by panyx0718** [comment]
Some extra that might worth adding:

1. distributed data reader (should unify with single machine reader)
2. distributed training fault tolerance.
3. evaluate different distributed training strategy (sync, async etc) influence on model accuracy.
4. sort out differences between multi-machine-single-device and multi-machine-multi-device
5. better integration with single-machine training
6. think about more flexible user-customized device placement for multi-machine training.

**Comment by panyx0718** [comment]
fault-tolerance is a basic distributed training feature that probably doesn't belong to EDL only.

**Comment by seiriosPlus** [comment]
```checkpoint``` need to be added to Improve training performance

**Comment by typhoonzero** [comment]
Maybe we should devide `fault-tolerance` to several parts:

* Base features
    * checkpointing and recovering on pserver
    * trainer pull checkpoint from pserver
    * recover reader offset (requires master and etcd)
* Clustering feature
    * autostart failed trainer based on cluster system (Kubernetes etc.)
    * autoscale trainer based on cluster system.

**Comment by Yancey1989** [comment]
Thanks, @panyx0718 @seiriosPlus @typhoonzero, I updated this issue followed by your comments.

**Comment by gongweibao** [comment]
Do we need add abstract interface of communication backend to be compatible with various implementations:
- Sync: nccl, mpi...
- Async: RPC

**Comment by gongweibao** [comment]
I think that it's maybe many things to do and we'd better do them with orders, classification, and priority.

**Comment by typhoonzero** [comment]
Closing this issue, most of the work are done except brpc and EDL related.
