### ISSUE TITLE
A compact data format for serialization or support various different format

### ISSUE THREAD

**Issue by panyx0718** [PaddlePaddle/Paddle#10294]
Currently recordio reader/writer works on raw LodTensor, which are essentially raw floats.
This solution is not compact and might lead to explosion of data size.

An example on flowers image data set:
the original jpg data set is: 347M
After converting to LodTensor and stored as recordio file, the size is increased to 3.5G
It could be a disaster for not so large dataset, such as ImageNet.

We should consider data format that handles raw bytes and only decoding/uncompression
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/example/example.proto

**Comment by reyoung** [comment]
Done, we use uint8 for image now.
