### ISSUE TITLE
Implement NCCL2 distributed GPU training with GPU Direct and RDMA as a contrib module 

### ISSUE THREAD

**Issue by typhoonzero** [PaddlePaddle/Paddle#10290]
NCCL2 provide a better performance over GPU distributed training, I'd like to provide it as a "contrib" module in Fluid, following things need to be done to make this work:

1. Write a new operator: `gen_nccl_id`, which do the following things:
    1. on trainer 0: generate a new unique id, then send it to all other trainers using a gRPC client.
    1. on trainer 1~n: start a gRPC server, when receives the id, then stop execution.
1. Append `gen_nccl_id` to the end of `start_up_program`.
1. Update `nccl.h` to enable initializing `communicator` across ranks of nodes.
1. Update `nccl_all_reduce_op_handle` to use the multi node communicator.

My prototype is at https://github.com/typhoonzero/nccl_rdma_demo

**Comment by seiriosPlus** [comment]
```
1. how to handle data Serialization and Deserialization.
2. how to control the send order of data.
3. how do you know ranks of nodes.
4. Is it support async?
```
I'm sorry for so many questions.

**Comment by typhoonzero** [comment]
@panyx0718 

> Is redis a "must have" to support nccl?

Nope, it's simple to use redis to broadcast the NCCL unique id. But indeed, less dependencies shold be better, will move to use grpc.

**Comment by typhoonzero** [comment]
@seiriosPlus 

1. No need, see `nccl_all_reduce_op_handle.cc`
