### ISSUE TITLE
compile error:expected type-specifier before '::' token

### ISSUE THREAD

**Issue by githubgsq** [PaddlePaddle/Paddle#10305]
An error occured when running "make" command:

In file included from /home/paddle-master/paddle/fluid/operators/detail/grpc_server.h:28:0,
                 from /home/paddle-master/paddle/fluid/operators/detail/grpc_server.cc:15:
/home/paddle-master/paddle/fluid/operators/detail/grpc_service.h: In constructor 'paddle::operators::detail::GrpcService::AsyncService::AsyncService()':
/home/paddle-master/paddle/fluid/operators/detail/grpc_service.h:106:23: error: expected type-specifier before '::' token
         AddMethod(new ::grpc::internal::RpcServiceMethod(
                       ^
make[2]: *** [paddle/fluid/operators/detail/CMakeFiles/sendrecvop_grpc.dir/grpc_server.cc.o] Error 1

I checked the souce code here: 
"https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/fluid/operators/detail/grpc_service.h"
there is no any token before '::'. Then it should be in global namespace.
so what should I do next please? 
Thanks!

**Comment by wanghaoshuang** [comment]
估计是编译器版本原因，可以贴一下你的环境配置么？

**Comment by githubgsq** [comment]
好的，您看下哈～  @wanghaoshuang 
环境配置文件～/.bashrc如下：

# .bashrc
# Source global definitions
if [ -f /etc/bashrc ]; then
        . /etc/bashrc
fi

# User specific aliases and functions
[[ -s "/home/users/gaosiqi/.jumbo/etc/bashrc" ]] && source "/home/users/gaosiqi/.jumbo/etc/bashrc"

export PATH=/home/users/gaosiqi/cmake3.2.2/bin:$PATH
export PATH=/opt/compiler/gcc-4.8.2/bin:$PATH
export PATH=/home/users/gaosiqi/python-gcc482-paddle/bin:$PATH
#export PATH=/home/users/gaosiqi/third/protobuf/bin:$PATH

export PYTHONPATH=/home/users/gaosiqi/python-gcc482-paddle/lib/python2.7/lib-dynload:$PYTHONPATH

export C_INCLUDE_PATH=/usr/local/include:/usr/local/cuda/include:$C_INCLUDE_PATH
export CPLUS_INCLUDE_PATH=/usr/local/include:/usr/local/cuda/include:$CPLUS_INCLUDE_PATH
export C_INCLUDE_PATH=/home/users/gaosiqi/third/nccl2/include:$C_INCLUDE_PATH
export CPLUS_INCLUDE_PATH=/home/users/gaosiqi/third/nccl2/include:$CPLUS_INCLUDE_PATH
export C_INCLUDE_PATH=/home/users/gaosiqi/python-gcc482-paddle/include/python2.7:$C_INCLUDE_PATH
export CPLUS_INCLUDE_PATH=/home/users/gaosiqi/python-gcc482-paddle/include/python2.7:$CPLUS_INCLUDE_PATH

export LD_LIBRARY_PATH=/home/users/gaosiqi/python-gcc482-paddle/lib:$LD_LIBRARY_PATH
export LD_LIBRARY_PATH=/usr/local/lib:$LD_LIBRARY_PATH
export LD_LIBRARY_PATH=/home/users/gaosiqi/third/nccl2/lib:$LD_LIBRARY_PATH

**Comment by githubgsq** [comment]
I deleted the build directory and rebuilt again, the same error still,  do you have any advice please?

![image](https://user-images.githubusercontent.com/23164715/39669547-636cc266-5121-11e8-88bd-1206e71e10e4.png)

**Comment by luotao1** [comment]
Maybe you can set `cmake -DWITH_DISTRIBUTE=OFF ..` if you only want to build Paddle on local machine.
