### ISSUE TITLE
Fluid new API: trainer support distributed training

### ISSUE THREAD

**Issue by helinwang** [PaddlePaddle/Paddle#10312]
The user does not have to change any code to run distributed training.

**Comment by wangkuiyi** [comment]
When users are writing distributed training programs, they should not have to know details like Fluid environment variables. However, currently, they do have to do so. For example:

https://github.com/PaddlePaddle/Paddle/blob/7cfd4e4e865f1989f3705c27c0df6f16159d1d8d/python/paddle/fluid/tests/book/test_fit_a_line.py#L72-L81

@helinwang 's idea is to hide such details in `fluid.Trainer`, which is proposed in the following PR:

https://github.com/PaddlePaddle/Paddle/pull/10313/files#diff-c8d3a5f15220bcd4840f27ed902aea4dR49

**Comment by helinwang** [comment]
PR is at https://github.com/PaddlePaddle/Paddle/pull/10316
