### ISSUE TITLE
Paddle是否有类似word2vec用于基于语义训练word emebding的方式？

### ISSUE THREAD

**Issue by 5idaidai** [PaddlePaddle/Paddle#1033]
仅仅想训练得到基于语义的词语emebding，有没有demo？或者如何将训练好的word emebding作为初始化传给paddle的emebding层用于其他任务？

**Comment by luotao1** [comment]
请参考[中文词向量的使用](https://github.com/PaddlePaddle/Paddle/blob/develop/doc/tutorials/embedding_model/index_cn.md)。

**Comment by 5idaidai** [comment]
谢谢 @luotao1 。
paddle如何加载已训练好的emebding是否有说明？

**Comment by luotao1** [comment]
请仔细阅读该文档。

**Comment by 5idaidai** [comment]
好的，明白了，谢谢！还有一个问题想请教一下，paddle是否支持将一个输入映射成一个matrix？
![63c5cc50-c94f-4817-a95a-27b0ccdb2907](https://cloud.githubusercontent.com/assets/1777746/21547543/bb233de8-ce21-11e6-8ec9-a273a9272238.png)
如上图，将一个user映射为矩阵U_k，将word映射为w_1。

**Comment by Zrachel** [comment]
不太清楚你指的映射具体是什么意思。以word映射为w_1为例，
1. 如果就是指把文本中的一个个word映射成paddle可读矩阵，可参考demo/sentiment/dataprovider.py中的integer_value_sequence实现指定paddle输入类型为index序列（实际就是一个dictionary size大小的one-hot vector），如果不需要序列输入，可以类似地用integer_value类型；

2. 如果映射是指paddle矩阵运算中的矩阵乘法，可以用table_projection/full_matrix_projection/identity_projection，参考python/paddle/trainer_config_helpers/layers.py

**Comment by 5idaidai** [comment]
首先我的问题是想基于user和word来对文本进行分类

我的意思其实是一个词是映射为了一个vector，通常的做法是会乘以一个共享矩阵U，但是我想针对不同的用户乘以不同的参数矩阵U，所以需要将每一个user映射为一个矩阵U，然后与word进行叉乘
