### ISSUE TITLE
训练数据reader是一个怎样的数据格式呢？

### ISSUE THREAD

**Issue by yeyupiaoling** [PaddlePaddle/Paddle#10357]
在每一个训练器中使用的数据都是一个reader，我查阅了官方文档，没有看到reader的数据格式。能简单介绍一下吗？

**Comment by JiayiFeng** [comment]
reader不是送入的数据，它是一个用来产生训练数据的可调用对象。产生的训练数据的具体格式，可以参照：
http://www.paddlepaddle.org/docs/0.11.0/documentation/en/api/v1/data_provider/pydataprovider2_en.html?highlight=dense#input-types

**Comment by yeyupiaoling** [comment]
@JiayiFeng 我看这里https://github.com/PaddlePaddle/models/blob/develop/image_classification/reader.py#L14 是这样格式的，reader这对象是不是里面有这些数据。

**Comment by JiayiFeng** [comment]
reader不持有数据，它只是负责从磁盘读取数据并交给网络做训练。你给的这一行中的img是来自sample的，而sample应该是从磁盘读取的。

**Comment by yeyupiaoling** [comment]
这样子啊？好的，谢谢！

**Comment by yeyupiaoling** [comment]
@JiayiFeng 
为什么要使用这个reader呢？或者说它的工作流程是什么？

**Comment by JiayiFeng** [comment]
简单的来说，reader所做的工作就是从文件中读取数据，并将其转化成符合网络要求输入的numpy对象。每种文件格式都需要实现自己的reader。
同时，reader也可以顺便完成数据shuffle、组成batch之类的数据预处理工作。

**Comment by yeyupiaoling** [comment]
@JiayiFeng 
说到这个`shuffle`接口，我顺便问一下，其参数`buf_size`的作用是什么，当我内存不足是，减小它好像没效果，只能减小`batch_size`才有效

**Comment by JiayiFeng** [comment]
`buf_size`指shuffle缓存的大小，reader每次从文件中读取`buf_size`个样本进行shuffle。

`batch_size`变大会导致网络中各个variable的全面变大，这是占用内存的主要原因。相比之下shuffle的`buf_size`占用的内存可以忽略不计。

**Comment by yeyupiaoling** [comment]
哦哦，感谢回答~
