### ISSUE TITLE
DeepSpeech工程语音识别

### ISSUE THREAD

**Issue by jiaozhusos** [PaddlePaddle/Paddle#10369]
centos6.9虚拟机，使用pip安装的padle。想基于百度已经训练好的模型（aishell）做语音识别，待识别的语音数据是实验室师兄提供的wav数据（一条3-6分钟不等），想问下是基于deploy下的demo_server就可以了吗，还需要再使用demo_client吗？（因为我看到demo_client需要自己录制音频，我的数据已经有了，所以不需要再额外录制）。自己的数据是需要放在speech_save_dir路径下吗，我按照这个进行识别，除了warm_up有显示结果，自己的音频数据没有识别j结果出来，如下：

```
Warming up ...
('Warm-up Test Case %d: %s', 0, u'/home/hwja/.cache/paddle/dataset/speech/Aishell/data_aishell/wav/test/S0913/BAC009S0913W0441.wav')
Response Time: 7.596060, Transcript: 就回家律师事务所律师邱宝昌表示
('Warm-up Test Case %d: %s', 1, u'/home/hwja/.cache/paddle/dataset/speech/Aishell/data_aishell/wav/test/S0912/BAC009S0912W0243.wav')
Response Time: 8.370960, Transcript: 推动环保基础设施和服务向农村延伸
('Warm-up Test Case %d: %s', 2, u'/home/hwja/.cache/paddle/dataset/speech/Aishell/data_aishell/wav/test/S0902/BAC009S0902W0189.wav')
Response Time: 6.425337, Transcript: 农业产业体系更趋完善
-----------------------------------------------------------
ASR Server Started.
```

这是什么原因呢？我需要进行怎样的修改呢？

**Comment by JiayiFeng** [comment]
@pkuyym 能否看一下这个

**Comment by pkuyym** [comment]
@jiaozhusos 需要排查一下音频是否正确传到Server端

**Comment by jiaozhusos** [comment]
这个问题解决了，但是还存在另外两个问题：
1. 关于识别准确率：不管是使用aishell模型还是baidu_cn1.2k模型，准确度都很低，试了一下aishell自带的部分数据，效果也一般。我自己的单条数据比较长（大概3-6min），基本只能识别出几个字（而且并不准），另外就是真的好慢（可能和我电脑的配置有关，所以只能等了。。。）。不知道修改其他的参数是否能提高一下准确度？另外就是增加线程数目（demo_server里的num_threads）会不会提高速度？

**Comment by jiaozhusos** [comment]
我自己的数据好多都一点识别不出来，是因为音频太长吗？

**Comment by jiaozhusos** [comment]
2. 第2个问题就是会出现以下错误：
alpha: 2.5
beam_size: 500
beta: 0.3
cutoff_prob: 0.99
cutoff_top_n: 40
decoding_method: ctc_beam_search
host_ip: localhost
host_port: 8086
lang_model_path: models/lm/zh_giga.no_cna_cmn.prune01244.klm
mean_std_path: models/baidu_cn1.2k_model/mean_std.npz
model_path: models/baidu_cn1.2k_model/params.tar.gz
num_conv_layers: 2
num_rnn_layers: 3
rnn_layer_size: 2048
share_rnn_weights: False
specgram_type: linear
speech_save_dir: my_data
use_gpu: False
use_gru: True
vocab_path: models/baidu_cn1.2k_model/vocab.txt
warmup_manifest: data/aishell/manifest.test
------------------------------------------------
I0508 16:45:57.876515  5865 Util.cpp:166] commandline:  --use_gpu=False --trainer_count=1 
[INFO 2018-05-08 16:45:57,989 layers.py:2689] output for __conv_0__: c = 32, h = 81, w = 54, size = 139968
[INFO 2018-05-08 16:45:57,990 layers.py:3251] output for __batch_norm_0__: c = 32, h = 81, w = 54, size = 139968
[INFO 2018-05-08 16:45:57,991 layers.py:7409] output for __scale_sub_region_0__: c = 32, h = 81, w = 54, size = 139968
[INFO 2018-05-08 16:45:57,992 layers.py:2689] output for __conv_1__: c = 32, h = 41, w = 54, size = 70848
[INFO 2018-05-08 16:45:57,993 layers.py:3251] output for __batch_norm_1__: c = 32, h = 41, w = 54, size = 70848
[INFO 2018-05-08 16:45:57,994 layers.py:7409] output for __scale_sub_region_1__: c = 32, h = 41, w = 54, size = 70848
[INFO 2018-05-08 16:46:21,011 model.py:243] begin to initialize the external scorer for decoding
[INFO 2018-05-08 16:46:33,755 model.py:253] language model: is_character_based = 1, max_order = 5, dict_size = 0
[INFO 2018-05-08 16:46:33,773 model.py:254] end initializing scorer
-----------------------------------------------------------
Warming up ...
('Warm-up Test Case %d: %s', 0, u'/home/hwja/.cache/paddle/dataset/speech/Aishell/data_aishell/wav/test/S0913/BAC009S0913W0441.wav')
Response Time: 47.794737, Transcript: 
('Warm-up Test Case %d: %s', 1, u'/home/hwja/.cache/paddle/dataset/speech/Aishell/data_aishell/wav/test/S0912/BAC009S0912W0243.wav')
Response Time: 39.816912, Transcript: 我
('Warm-up Test Case %d: %s', 2, u'/home/hwja/.cache/paddle/dataset/speech/Aishell/data_aishell/wav/test/S0902/BAC009S0902W0189.wav')
Response Time: 34.964883, Transcript: 我
-----------------------------------------------------------
ASR Server Started.
Received utterance[length=6651648] from 127.0.0.1, saved to my_data/20180508085050_127.0.0.1.wav.
/home/hwja/anaconda3/envs/py2/lib/python2.7/site-packages/resampy/core.py:90: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  if not np.issubdtype(x.dtype, np.float):
F0508 16:50:59.127279  5865 Allocator.h:56] Check failed: posix_memalign(&ptr, 32ul, size) == 0 (12 vs. 0) 
*** Check failure stack trace: ***
    @     0x7f343fa959cd  google::LogMessage::Fail()
    @     0x7f343fa9947c  google::LogMessage::SendToLog()
    @     0x7f343fa954f3  google::LogMessage::Flush()
    @     0x7f343fa9a98e  google::LogMessageFatal::~LogMessageFatal()
    @     0x7f343f9cb305  paddle::CpuAllocator::alloc()
    @     0x7f343f9b275f  paddle::PoolAllocator::alloc()
    @     0x7f343f9b2226  paddle::CpuMemoryHandle::CpuMemoryHandle()
    @     0x7f343f8f1323  paddle::ConvFunctionBase::resizeBuffer<>()
    @     0x7f343f8f2340  paddle::GemmConvFunction<>::calc()
    @     0x7f343f7dd73f  paddle::ExpandConvLayer::forward()
    @     0x7f343f84aefd  paddle::NeuralNetwork::forward()
    @     0x7f343f6f547d  _wrap_GradientMachine_forward
    @     0x7f346e2a79c0  PyEval_EvalFrameEx
    @     0x7f346e2aa519  PyEval_EvalCodeEx
    @     0x7f346e2a74b2  PyEval_EvalFrameEx
    @     0x7f346e2aa519  PyEval_EvalCodeEx
    @     0x7f346e2a74b2  PyEval_EvalFrameEx
    @     0x7f346e2289cb  gen_send_ex.isra.1
    @     0x7f346e2a5486  PyEval_EvalFrameEx
    @     0x7f346e2289cb  gen_send_ex.isra.1
    @     0x7f346e2a5486  PyEval_EvalFrameEx
    @     0x7f346e2aa519  PyEval_EvalCodeEx
    @     0x7f346e2a74b2  PyEval_EvalFrameEx
    @     0x7f346e2aa519  PyEval_EvalCodeEx
    @     0x7f346e2a74b2  PyEval_EvalFrameEx
    @     0x7f346e2aa519  PyEval_EvalCodeEx
    @     0x7f346e2a74b2  PyEval_EvalFrameEx
    @     0x7f346e2a8ddc  PyEval_EvalFrameEx
    @     0x7f346e2aa519  PyEval_EvalCodeEx
    @     0x7f346e23300a  function_call
    @     0x7f346e20e7a3  PyObject_Call
    @     0x7f346e21d53d  instancemethod_call
Aborted


不太清楚是什么原因。此外就是用baiducn1.2k的时候，warm_up不太正常感觉，使用aishell的时候，warm_up是正常的，但是也会出现以上的错误。即使不出错，识别准确度也很差

**Comment by pkuyym** [comment]
我们测过AiShell的模型，在安静环境下，发音清晰的情况下，识别效果还算可以。
```
关于识别准确率：不管是使用aishell模型还是baidu_cn1.2k模型，准确度都很低，试了一下aishell自带的部分数据，效果也一般。我自己的单条数据比较长（大概3-6min），基本只能识别出几个字（而且并不准），另外就是真的好慢（可能和我电脑的配置有关，所以只能等了。。。）。不知道修改其他的参数是否能提高一下准确度？另外就是增加线程数目（demo_server里的num_threads）会不会提高速度？
```

**Comment by jiaozhusos** [comment]
使用aishell模型试听了一下，保存的音频文件有问题（使用aishell自带的音频数据），感觉像是被快进了，基本分辨不出来

**Comment by jiaozhusos** [comment]
我的demo_client.py文件设置：
data_dir='audio_data'
data_path=os.listdir(data_dir)
txt_file_path='txt_result'
for audio_file in data_path:
    print(audio_file)
    # connect server
    (HOST, PORT) = ('localhost', 8086)
    s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    s.connect((HOST, PORT))
    w=wave.open(os.path.join(data_dir,audio_file), 'r')
    n = w.getnframes()
    data = w.readframes(n)
    s.sendall(struct.pack('>i', len(data)) + data)
    received = s.recv(1024)

    txt_name=re.sub('[.wav]','',audio_file)+'.txt'
    with open(os.path.join(txt_file_path,txt_name),'w') as f:
        f.write(received)
    print (received)
    w.close()
    s.close()

因为不需要录音，所以麦克风没有设置。
demo_server文件配置：
parser = argparse.ArgumentParser(description=__doc__)
add_arg = functools.partial(add_arguments, argparser=parser)
# yapf: disable
add_arg('host_port',        int,    8086,    "Server's IP port.")
add_arg('beam_size',        int,    500,    "Beam search width.")
add_arg('num_conv_layers',  int,    2,      "# of convolution layers.")
add_arg('num_rnn_layers',   int,    3,      "# of recurrent layers.")
add_arg('rnn_layer_size',   int,    1024,   "# of recurrent cells per layer.")
add_arg('alpha',            float,  2.5,   "Coef of LM for beam search.")
add_arg('beta',             float,  0.3,   "Coef of WC for beam search.")
add_arg('cutoff_prob',      float,  0.99,    "Cutoff probability for pruning.")
add_arg('cutoff_top_n',     int,    40,     "Cutoff number for pruning.")
add_arg('use_gru',          bool,   True,  "Use GRUs instead of simple RNNs.")
add_arg('use_gpu',          bool,   False,   "Use GPU or not.")
add_arg('share_rnn_weights',bool,   False,   "Share input-hidden weights across "
                                            "bi-directional RNNs. Not for GRU.")
add_arg('host_ip',          str,
        'localhost',
        "Server's IP address.")
add_arg('speech_save_dir',  str,
        'my_data',
        "Directory to save demo audios.")
add_arg('warmup_manifest',  str,
        'data/aishell/manifest.test',
        "Filepath of manifest to warm up.")
add_arg('mean_std_path',    str,
        'models/aishell/mean_std.npz',
        "Filepath of normalizer's mean & std.")
add_arg('vocab_path',       str,
        'models/aishell/vocab.txt',
        "Filepath of vocabulary.")
add_arg('model_path',       str,
        'models/aishell/params.tar.gz',
        "If None, the training starts from scratch, "
        "otherwise, it resumes from the pre-trained model.")
add_arg('lang_model_path',  str,
        'models/lm/zh_giga.no_cna_cmn.prune01244.klm',
        "Filepath for language model.")
add_arg('decoding_method',  str,
        'ctc_beam_search',
        "Decoding method. Options: ctc_beam_search, ctc_greedy",
        choices = ['ctc_beam_search', 'ctc_greedy'])
add_arg('specgram_type',    str,
        'linear',
        "Audio feature type. Options: linear, mfcc.",
        choices=['linear', 'mfcc'])
# yapf: disable
args = parser.parse_args()


class AsrTCPServer(SocketServer.TCPServer):
    """The ASR TCP Server."""

    def __init__(self,
                 server_address,
                 RequestHandlerClass,
                 speech_save_dir,
                 audio_process_handler,
                 bind_and_activate=True):
        self.speech_save_dir = speech_save_dir
        self.audio_process_handler = audio_process_handler
        SocketServer.TCPServer.__init__(
            self, server_address, RequestHandlerClass, bind_and_activate=True)


class AsrRequestHandler(SocketServer.BaseRequestHandler):
    """The ASR request handler."""

    def handle(self):
        # receive data through TCP socket
        chunk = self.request.recv(1024)
        target_len = struct.unpack('>i', chunk[:4])[0]
        data = chunk[4:]
        while len(data) < target_len:
            chunk = self.request.recv(1024)
            data += chunk
        # write to file
        filename = self._write_to_file(data)

        print("Received utterance[length=%d] from %s, saved to %s." %
              (len(data), self.client_address[0], filename))
        start_time = time.time()
        transcript = self.server.audio_process_handler(filename)
        finish_time = time.time()
        print("Response Time: %f, Transcript: %s" %
              (finish_time - start_time, transcript))
        self.request.sendall(transcript.encode('utf-8'))

    def _write_to_file(self, data):
        # prepare save dir and filename
        if not os.path.exists(self.server.speech_save_dir):
            os.mkdir(self.server.speech_save_dir)
        timestamp = strftime("%Y%m%d%H%M%S", gmtime())
        out_filename = os.path.join(
            self.server.speech_save_dir,
            timestamp + "_" + self.client_address[0] + ".wav")
        # write to wav file
        file = wave.open(out_filename, 'wb')
        file.setnchannels(1)
        file.setsampwidth(4)
        file.setframerate(16000)
        file.writeframes(data)
        file.close()
        return out_filename


def warm_up_test(audio_process_handler,
                 manifest_path,
                 num_test_cases,
                 random_seed=0):
    """Warming-up test."""
    manifest = read_manifest(manifest_path)
    rng = random.Random(random_seed)
    samples = rng.sample(manifest, num_test_cases)
    for idx, sample in enumerate(samples):
        print("Warm-up Test Case %d: %s", idx, sample['audio_filepath'])
        start_time = time.time()
        transcript = audio_process_handler(sample['audio_filepath'])
        finish_time = time.time()
        print("Response Time: %f, Transcript: %s" %
              (finish_time - start_time, transcript))


def start_server():
    """Start the ASR server"""
    # prepare data generator
    data_generator = DataGenerator(
        vocab_filepath=args.vocab_path,
        mean_std_filepath=args.mean_std_path,
        augmentation_config='{}',
        specgram_type=args.specgram_type,
        num_threads=1,
        keep_transcription_text=True)
	
    # prepare ASR model
    ds2_model = DeepSpeech2Model(
        vocab_size=data_generator.vocab_size,
        num_conv_layers=args.num_conv_layers,
        num_rnn_layers=args.num_rnn_layers,
        rnn_layer_size=args.rnn_layer_size,
        use_gru=args.use_gru,
        pretrained_model_path=args.model_path,
        share_rnn_weights=args.share_rnn_weights)
	
    vocab_list = [chars.encode("utf-8") for chars in data_generator.vocab_list]

    if args.decoding_method == "ctc_beam_search":
        ds2_model.init_ext_scorer(args.alpha, args.beta, args.lang_model_path,
                                  vocab_list)
    # prepare ASR inference handler
    def file_to_transcript(filename):
        feature = data_generator.process_utterance(filename, "")
        probs_split = ds2_model.infer_batch_probs(
            infer_data=[feature],
            feeding_dict=data_generator.feeding)

        if args.decoding_method == "ctc_greedy":
            result_transcript = ds2_model.decode_batch_greedy(
                probs_split=probs_split,
                vocab_list=vocab_list)
        else:
            result_transcript = ds2_model.decode_batch_beam_search(
                probs_split=probs_split,
                beam_alpha=args.alpha,
                beam_beta=args.beta,
                beam_size=args.beam_size,
                cutoff_prob=args.cutoff_prob,
                cutoff_top_n=args.cutoff_top_n,
                vocab_list=vocab_list,
                num_processes=1)
        return result_transcript[0]

    # warming up with utterrances sampled from Librispeech
    print('-----------------------------------------------------------')
    print('Warming up ...')
    warm_up_test(
        audio_process_handler=file_to_transcript,
        manifest_path=args.warmup_manifest,
        num_test_cases=3)
    print('-----------------------------------------------------------')

    # start the server
	
    server = AsrTCPServer(
        server_address=(args.host_ip, args.host_port),
        RequestHandlerClass=AsrRequestHandler,
        speech_save_dir=args.speech_save_dir,
        audio_process_handler=file_to_transcript)
	
    print("ASR Server Started.")
    server.serve_forever()
	


def main():
    print_arguments(args)
    paddle.init(use_gpu=args.use_gpu, trainer_count=1)
	
    start_server()
	

if __name__ == "__main__":
    main()
除了手动添加模型以外，基本没做任何的修改。
附：自己的音频数据跑aishell的时候是按16000、单声道采样的；跑baidu_cn1.2的时候是按照8000采样的。刚才试听的是aishell自带的几条数据，但是保存的音频格式却不对。

**Comment by jiaozhusos** [comment]
我的demo_client.py文件设置：
data_dir='audio_data'
data_path=os.listdir(data_dir)
txt_file_path='txt_result'
for audio_file in data_path:
    print(audio_file)
    # connect server
    (HOST, PORT) = ('localhost', 8086)
    s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    s.connect((HOST, PORT))
    w=wave.open(os.path.join(data_dir,audio_file), 'r')
    n = w.getnframes()
    data = w.readframes(n)
    s.sendall(struct.pack('>i', len(data)) + data)
    received = s.recv(1024)

    txt_name=re.sub('[.wav]','',audio_file)+'.txt'
    with open(os.path.join(txt_file_path,txt_name),'w') as f:
        f.write(received)
    print (received)
    w.close()
    s.close()

因为不需要录音，所以麦克风没有设置。
demo_server文件配置：
parser = argparse.ArgumentParser(description=__doc__)
add_arg = functools.partial(add_arguments, argparser=parser)
# yapf: disable
add_arg('host_port',        int,    8086,    "Server's IP port.")
add_arg('beam_size',        int,    500,    "Beam search width.")
add_arg('num_conv_layers',  int,    2,      "# of convolution layers.")
add_arg('num_rnn_layers',   int,    3,      "# of recurrent layers.")
add_arg('rnn_layer_size',   int,    1024,   "# of recurrent cells per layer.")
add_arg('alpha',            float,  2.5,   "Coef of LM for beam search.")
add_arg('beta',             float,  0.3,   "Coef of WC for beam search.")
add_arg('cutoff_prob',      float,  0.99,    "Cutoff probability for pruning.")
add_arg('cutoff_top_n',     int,    40,     "Cutoff number for pruning.")
add_arg('use_gru',          bool,   True,  "Use GRUs instead of simple RNNs.")
add_arg('use_gpu',          bool,   False,   "Use GPU or not.")
add_arg('share_rnn_weights',bool,   False,   "Share input-hidden weights across "
                                            "bi-directional RNNs. Not for GRU.")
add_arg('host_ip',          str,
        'localhost',
        "Server's IP address.")
add_arg('speech_save_dir',  str,
        'my_data',
        "Directory to save demo audios.")
add_arg('warmup_manifest',  str,
        'data/aishell/manifest.test',
        "Filepath of manifest to warm up.")
add_arg('mean_std_path',    str,
        'models/aishell/mean_std.npz',
        "Filepath of normalizer's mean & std.")
add_arg('vocab_path',       str,
        'models/aishell/vocab.txt',
        "Filepath of vocabulary.")
add_arg('model_path',       str,
        'models/aishell/params.tar.gz',
        "If None, the training starts from scratch, "
        "otherwise, it resumes from the pre-trained model.")
add_arg('lang_model_path',  str,
        'models/lm/zh_giga.no_cna_cmn.prune01244.klm',
        "Filepath for language model.")
add_arg('decoding_method',  str,
        'ctc_beam_search',
        "Decoding method. Options: ctc_beam_search, ctc_greedy",
        choices = ['ctc_beam_search', 'ctc_greedy'])
add_arg('specgram_type',    str,
        'linear',
        "Audio feature type. Options: linear, mfcc.",
        choices=['linear', 'mfcc'])
# yapf: disable
args = parser.parse_args()


class AsrTCPServer(SocketServer.TCPServer):
    """The ASR TCP Server."""

    def __init__(self,
                 server_address,
                 RequestHandlerClass,
                 speech_save_dir,
                 audio_process_handler,
                 bind_and_activate=True):
        self.speech_save_dir = speech_save_dir
        self.audio_process_handler = audio_process_handler
        SocketServer.TCPServer.__init__(
            self, server_address, RequestHandlerClass, bind_and_activate=True)


class AsrRequestHandler(SocketServer.BaseRequestHandler):
    """The ASR request handler."""

    def handle(self):
        # receive data through TCP socket
        chunk = self.request.recv(1024)
        target_len = struct.unpack('>i', chunk[:4])[0]
        data = chunk[4:]
        while len(data) < target_len:
            chunk = self.request.recv(1024)
            data += chunk
        # write to file
        filename = self._write_to_file(data)

        print("Received utterance[length=%d] from %s, saved to %s." %
              (len(data), self.client_address[0], filename))
        start_time = time.time()
        transcript = self.server.audio_process_handler(filename)
        finish_time = time.time()
        print("Response Time: %f, Transcript: %s" %
              (finish_time - start_time, transcript))
        self.request.sendall(transcript.encode('utf-8'))

    def _write_to_file(self, data):
        # prepare save dir and filename
        if not os.path.exists(self.server.speech_save_dir):
            os.mkdir(self.server.speech_save_dir)
        timestamp = strftime("%Y%m%d%H%M%S", gmtime())
        out_filename = os.path.join(
            self.server.speech_save_dir,
            timestamp + "_" + self.client_address[0] + ".wav")
        # write to wav file
        file = wave.open(out_filename, 'wb')
        file.setnchannels(1)
        file.setsampwidth(4)
        file.setframerate(16000)
        file.writeframes(data)
        file.close()
        return out_filename


def warm_up_test(audio_process_handler,
                 manifest_path,
                 num_test_cases,
                 random_seed=0):
    """Warming-up test."""
    manifest = read_manifest(manifest_path)
    rng = random.Random(random_seed)
    samples = rng.sample(manifest, num_test_cases)
    for idx, sample in enumerate(samples):
        print("Warm-up Test Case %d: %s", idx, sample['audio_filepath'])
        start_time = time.time()
        transcript = audio_process_handler(sample['audio_filepath'])
        finish_time = time.time()
        print("Response Time: %f, Transcript: %s" %
              (finish_time - start_time, transcript))


def start_server():
    """Start the ASR server"""
    # prepare data generator
    data_generator = DataGenerator(
        vocab_filepath=args.vocab_path,
        mean_std_filepath=args.mean_std_path,
        augmentation_config='{}',
        specgram_type=args.specgram_type,
        num_threads=1,
        keep_transcription_text=True)
	
    # prepare ASR model
    ds2_model = DeepSpeech2Model(
        vocab_size=data_generator.vocab_size,
        num_conv_layers=args.num_conv_layers,
        num_rnn_layers=args.num_rnn_layers,
        rnn_layer_size=args.rnn_layer_size,
        use_gru=args.use_gru,
        pretrained_model_path=args.model_path,
        share_rnn_weights=args.share_rnn_weights)
	
    vocab_list = [chars.encode("utf-8") for chars in data_generator.vocab_list]

    if args.decoding_method == "ctc_beam_search":
        ds2_model.init_ext_scorer(args.alpha, args.beta, args.lang_model_path,
                                  vocab_list)
    # prepare ASR inference handler
    def file_to_transcript(filename):
        feature = data_generator.process_utterance(filename, "")
        probs_split = ds2_model.infer_batch_probs(
            infer_data=[feature],
            feeding_dict=data_generator.feeding)

        if args.decoding_method == "ctc_greedy":
            result_transcript = ds2_model.decode_batch_greedy(
                probs_split=probs_split,
                vocab_list=vocab_list)
        else:
            result_transcript = ds2_model.decode_batch_beam_search(
                probs_split=probs_split,
                beam_alpha=args.alpha,
                beam_beta=args.beta,
                beam_size=args.beam_size,
                cutoff_prob=args.cutoff_prob,
                cutoff_top_n=args.cutoff_top_n,
                vocab_list=vocab_list,
                num_processes=1)
        return result_transcript[0]

    # warming up with utterrances sampled from Librispeech
    print('-----------------------------------------------------------')
    print('Warming up ...')
    warm_up_test(
        audio_process_handler=file_to_transcript,
        manifest_path=args.warmup_manifest,
        num_test_cases=3)
    print('-----------------------------------------------------------')

    # start the server
	
    server = AsrTCPServer(
        server_address=(args.host_ip, args.host_port),
        RequestHandlerClass=AsrRequestHandler,
        speech_save_dir=args.speech_save_dir,
        audio_process_handler=file_to_transcript)
	
    print("ASR Server Started.")
    server.serve_forever()
	


def main():
    print_arguments(args)
    paddle.init(use_gpu=args.use_gpu, trainer_count=1)
	
    start_server()
	

if __name__ == "__main__":
    main()
除了手动添加模型以外，基本没做任何的修改。
附：自己的音频数据跑aishell的时候是按16000、单声道采样的；跑baidu_cn1.2的时候是按照8000采样的。刚才试听的是aishell自带的几条数据，但是保存的音频格式却不对。
