### ISSUE TITLE
在加载图像的接口load_image中，它会把其它通道转成HWC通道吗？

### ISSUE THREAD

**Issue by yeyupiaoling** [PaddlePaddle/Paddle#10360]
在读取图像是使用的是这个接口
```
paddle.v2.image.load_image(file, is_color=True)
```
PaddlePaddle使用的通道格式是HWC，那么这个函数是不是把RGB通道的转换成HWC通道的，我观察了源代码，，没看到相应的操作。

**Comment by JiayiFeng** [comment]
RGB和HWC是完全不同的概念。RGB表示图像用红、绿、蓝三个channel表示，而HWC表示图像tensor的第一个维度表示高，第二个维度表示宽，第三个维度表示channel。
一幅RGB的图像可以是HWC的，也可以是CHW的。

**Comment by yeyupiaoling** [comment]
@JiayiFeng 
哦哦，了解，这个接口中https://github.com/PaddlePaddle/models/blob/develop/image_classification/reader.py#L13 的第一个参数的需要的图像是HWC的
文档中有说到：https://github.com/PaddlePaddle/models/blob/develop/image_classification/reader.py#L13
那么不用做特殊处理吗？

**Comment by JiayiFeng** [comment]
这里没有处理是因为这里的从文件中读出来的img本来就是HWC的。

**Comment by yeyupiaoling** [comment]
好的，谢谢回答。
