### ISSUE TITLE
GPU训练的receiver问题：no active receiver found

### ISSUE THREAD

**Issue by qubingxin** [PaddlePaddle/Paddle#1037]
一直用的42的receiver, 下午还正常。晚上无法杀掉任务和提交任务，都报错：no active receiver found
更改端口号后，提交任务出现如下错误：
compressing thirdparty files
finished to pack request
starting to submit to server
None
这是由于新receiver不支持当前的data_provider吗？？

**Comment by qubingxin** [comment]
任何网络相关配置都没改，就跑不了了。

**Comment by backyes** [comment]
下午服务器宕机，已恢复。

**Comment by qubingxin** [comment]
仍然提交不了任务，端口号从9090改到9290，报错如下：
compressing thirdparty files
finished to pack request
starting to submit to server
None
请问现在42系列机器的端口号是多少？
