### ISSUE TITLE
Paddle如何打印模型结构中每层输出的结果

### ISSUE THREAD

**Issue by chenbblei** [PaddlePaddle/Paddle#10397]
如题

**Comment by Superjomn** [comment]
```python
print Topoloty.proto(var)
```

**Comment by chenbblei** [comment]
@Superjomn 我在构建网络的时候，添加这个语句，打印的是网络结构啊,并不是值

**Comment by hf136** [comment]
训练时：http://paddlepaddle.org/docs/develop/documentation/zh/faq/local/index_cn.html#permalink-12-6-layer-output
预测时：http://paddlepaddle.org/docs/develop/documentation/zh/faq/local/index_cn.html#permalink-11-5-infer-layer-

**Comment by chenbblei** [comment]
@hf136 谢谢

**Comment by mrright2019** [comment]
> 训练时：http://paddlepaddle.org/docs/develop/documentation/zh/faq/local/index_cn.html#permalink-12-6-layer-output
> 预测时：http://paddlepaddle.org/docs/develop/documentation/zh/faq/local/index_cn.html#permalink-11-5-infer-layer-

连接不能用了,麻烦再发一遍可行
