### ISSUE TITLE
Can paddle support multi process data loading ?

### ISSUE THREAD

**Issue by youngstu** [PaddlePaddle/Paddle#10396]
现在机器有8个 gpu （Tesla P40），paddle 好像不支持多进程数据加载，现在数据加载成了瓶颈，模型训练速度无法有效提升，请问有什么好的方法么？谢谢！

**Comment by Superjomn** [comment]
有feature还没加入

是否是 reader 写的比较低效？  python reader 那一部分尽量写的高效些。  

比如一些 preprocess 先搞定，压缩载入数据时的计算量。

或者python里面弄一个线程池（IO还好），多线程压到一个 array里， array 处理完毕直接load到paddle。

**Comment by walloollaw** [comment]
可以试试 paddle.reader.decorator.xmap_readers, 这个里面可以用thread并发搞， 不过受限于python的内部机制，并不能利用多核处理；再进一步可以简单修改下 这个xmap_readers的实现，用multiprocess来搞，如果真是计算瓶颈，确实能快不少（我这边实验速度有1倍的提升）
