### ISSUE TITLE
make error: /build/third_party/grpc/src/extern_grpc/libs/opt/libgrpc.so.5.0.0: File format not recognized

### ISSUE THREAD

**Issue by githubgsq** [PaddlePaddle/Paddle#10409]
hi, all
 an error occured when executing "make" command:
![image](https://user-images.githubusercontent.com/23164715/39617812-b5d063ce-4fb3-11e8-9ddb-e1596bb7da91.png)

do you have any advice please?
thanks!

**Comment by jacquesqiao** [comment]
Try to delete the third_part/grpc and rebuild again?
