### ISSUE TITLE
reshape and slice like python

### ISSUE THREAD

**Issue by yttbgf** [PaddlePaddle/Paddle#10413]
1.how to reshape a vector into a tensor with shape more than 2D, such as 3D+(row*col*block*feature) 
2.how to slice tensor with more than 1D slice:such as ( row slice+ col slice )

**Comment by yttbgf** [comment]
in v2 version hiddenlayer

**Comment by Superjomn** [comment]
http://www.paddlepaddle.org/docs/develop/api/fluid/en/layers.html

**Comment by yttbgf** [comment]
I use V2 now, I just found seq_reshape and slice_projection.Is there any other layers which can work?
or can I use fluid and V2 mixed?

**Comment by Superjomn** [comment]
no you can't
