### ISSUE TITLE
how to add L1,L2 with sgd

### ISSUE THREAD

**Issue by PseudoProgrammer** [PaddlePaddle/Paddle#1042]
how to add L1, L2 with sgd

**Comment by backyes** [comment]
@PseudoProgrammer 

Parameter level setting：
http://www.paddlepaddle.org/doc/ui/api/trainer_config_helpers/attrs.html#module-paddle.trainer_config_helpers.attrs 

Global setting：
http://www.paddlepaddle.org/doc/ui/api/trainer_config_helpers/optimizers.html#settings

**Comment by backyes** [comment]
@PseudoProgrammer 

If not sparse update enabled, parameter level L1 regulation is not available, we are working on it.  

Please use some optimizer supporting sparse_update, then L1 and L2 with per-parameter setting are available.

Related issue:
https://github.com/PaddlePaddle/Paddle/issues/273 
https://github.com/PaddlePaddle/Paddle/pull/985

**Comment by Xreki** [comment]
Closed because of inactivity, please feel free to reopen it.
