### ISSUE TITLE
如何用paddle使用lfw数据集

### ISSUE THREAD

**Issue by QinboZhao** [PaddlePaddle/Paddle#10435]
想要复现一个人简单的人脸识别算法,但自己还是个小白，
如何用paddle使用lfw数据集，
有没有相关的教程，
需要实现1：1和1：n验证。
希望前辈们能指点指点。

**Comment by Superjomn** [comment]
可以参考下其他模型的写法或者 paddle book

http://www.paddlepaddle.org/docs/develop/book/01.fit_a_line/index.cn.html

https://github.com/PaddlePaddle/models
