### ISSUE TITLE
有些模型样例里train方法没有指定feeding参数，这种情况下，输入数据是怎么跟输入层对应起来的呢？ hsigmoid、generate_sequence_by_rnn_lm 等均有这个情况

### ISSUE THREAD

**Issue by liaibao120** [PaddlePaddle/Paddle#10446]

**Comment by Yancey1989** [comment]
有default的feeder对应到data layer，可以参考代码：
https://github.com/PaddlePaddle/Paddle/blob/bb3247e33973ca02d900421e7f823214f4b0a067/python/paddle/v2/data_feeder.py#L21-L25
