### ISSUE TITLE
V2 API Documentation

### ISSUE THREAD

**Issue by VictorBebnev** [PaddlePaddle/Paddle#10455]
Hello. 
Do you have documentation about the structure of the saved parameters for V2 API?
Thanks.

**Comment by Yancey1989** [comment]
Sorry, we haven't a document to describe the structure of saved parameter yet, maybe you can take a look at the source code, please feel free to comment this issue if any questions:

https://github.com/PaddlePaddle/Paddle/blob/5b06944857e74f9b1388e081d4502bfd8c002832/paddle/parameter/Parameter.cpp#L292-L306

**Comment by VictorBebnev** [comment]
Can you tell me the difference from V2 API to Fluid API?

**Comment by Yancey1989** [comment]
There are a lot of differences between V2 API and Fluid API, there are some useful links about Fluid API and V2 API:

v2 API:
- document: http://paddlepaddle.org/docs/develop/api/en/overview.html
- demo:  
  - https://github.com/PaddlePaddle/models
  - https://github.com/PaddlePaddle/book

Fluid API 
- document: http://paddlepaddle.org/docs/develop/api/fluid/en/layers.html
- demo: https://github.com/PaddlePaddle/Paddle/tree/develop/python/paddle/fluid/tests/book
