### ISSUE TITLE
Add Double Compile&Unit Test in TravisCI

### ISSUE THREAD

**Issue by reyoung** [PaddlePaddle/Paddle#1045]
Paddle support use double precision as a real type. But it is not tested in TravisCI. We should add a new `JOB` for TravisCI of double precision, even most of us use single precision float version.

Issue comes from @pengli09 .

**Comment by wangkuiyi** [comment]
Good point. Does this mean that we need to make TravisCI build two Paddle binaries -- one 16-bit float and another one 32-bit float?

**Comment by reyoung** [comment]
> Good point. Does this mean that we need to make TravisCI build two Paddle binaries -- one 16-bit float and another one 32-bit float?

One 32-bit float, another one 64-bit float. Currently 16-bit float is not supported by Paddle.

**Comment by reyoung** [comment]
Has been fixed.
