### ISSUE TITLE
测试发现输入数据即使idx out of  【paddle.data_type】的dim也不会报错

### ISSUE THREAD

**Issue by 333caowei** [PaddlePaddle/Paddle#10479]
测试模型的输入层的网络结构如下：
```
query_data = paddle.layer.data(name="query", type=paddle.data_type.integer_value_sequence(5))

title_data = paddle.layer.data(name="title", type=paddle.data_type.integer_value_sequence(5))

if is_infer == False:
    label = paddle.layer.data(name="label", type=paddle.data_type.integer_value(2))

query_emb = paddle.layer.embedding(input=query_data, size=query_emb_dim)
title_emb = paddle.layer.embedding(input=title_data, size=title_emb_dim)

```
在上述输入层定义中，我将query和title的integer_value_sequence维度定义成【维度5】，label维度定义成维度【2】

下面是reader.py的测试返回：
```
yield [2, 6, 7, 14], [12, 22, 8], 15

feeding = {"query": 0, "title": 1, "label": 2}
```
【问题1】：从上面yield的返回可以看见 [2, 6, 7, 14],与[12, 22, 8]的idx已经大于【维度5】，但是程序可以正常执行没有报错提示

【问题2】：label15已经大于维度【2】，但是程序可以正常执行没有报错提示

-------------------------------分界线------------------------------
-------------------------------分界线------------------------------
-------------------------------分界线------------------------------

另外测试了sparse_binary_vector
```
query_data = paddle.layer.data(name="query", type=paddle.data_type.sparse_binary_vector(5))
title_data = paddle.layer.data(name="title", type=paddle.data_type.sparse_binary_vector(5))
if is_infer == False:
    label = paddle.layer.data(name="label", type=paddle.data_type.integer_value(2))
```

这个不会报错
```
yield  [0, 3, 4, 4 ,9],  [2,4,3],  8
```

这个会报错
```
yield  [0, 3, 4, 4 ,4, 3],  [2,4,3], 8
```

【问题3】：我理解type=paddle.data_type.sparse_binary_vector(5)中5的含义是是onehot编码的维度，那么在上述[0, 3, 4, 4 ,6]中，6的idx已经大于5，应该报错，但是实际上没有报错，反而在 [0, 3, 4, 4 ,4, 3]中，因为len( [0, 3, 4, 4 ,4, 3]) >5, 所以报错了。
我理解[0, 3, 4, 4 ,4, 3]代表的onehot编码是[1,0,0,1,1]

**Comment by Xreki** [comment]
【问题1】和【问题2】：
`integer_value_sequence`和`integer_value`类型指定的维度，Paddle实际存的是index，实际有效的value确实应该在维度指定的范围内。Paddle目前没有对value的范围进行检查，需要用户自己保证数据的合法性。

**Comment by 333caowei** [comment]
在sparse_binary_vector中，是否需要要求元素有序呢，比如：
query_data = paddle.layer.data(name="query", type=paddle.data_type.sparse_binary_vector(5)

yield  [0，2，3]
yield  [5, 3, 1]
如果 传入的是后者是否可以

**Comment by shanyi15** [comment]
您好，此issue在近一个月内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题，我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持! 
 Hello, this issue has not been updated in the past month. We will close it today for the sake of other user‘s experience. If you still need to follow up on this question after closing, please feel free to reopen it. In that case, we will get back to you within 24 hours. We apologize for the inconvenience caused by the closure and thank you so much for your support of PaddlePaddle Group!
