### ISSUE TITLE
树莓派

### ISSUE THREAD

**Issue by CHNEG8805** [PaddlePaddle/Paddle#10477]
官方提供的树莓派编译办法总是不成功，会有第三方库报错。而直接在树莓派上安装请问安装哪些环境呢？

**Comment by Xreki** [comment]
请问具体是什么错误呢？

**Comment by CHNEG8805** [comment]
您好
   1.我编译的是releases0.12 目前还不是很清楚您说的v2和fluid版本的区别。
   2.我的期望是可以在树莓派上预测，可以在x86上训练
   3.是的，我实在x86上编译的paddle.我使用的命令是sudo cmake -DCMAKE_SYSTEM_NAME=RPI
并在raspberry_pi.cmake中增加了如下内容，不知道是否可以。
SET(CMAKE_SYSTEM_NAME RPI)
SET(CMAKE_SYSTEM_VERSION 1)
SET(CMAKE_SYSTEM_PROCESSOR arm)

SET(RPI_TOOLCHAIN /home/share/tools-master/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian)
SET(RPI_ARM_NEON ON)
SET(CMAKE_INSTALL_PREFIX /home/share/Paddle/_install)
SET(WITH_GPU OFF)
SET(WITH_C_API ON)
SET(WITH_PYTHON OFF)
SET(WITH_SWIG_PY OFF)
SET(MAKE_BUILD_TYPE MinSizeRel)
SET(CMAKE_BUILD_TYPE Release)

**Comment by CHNEG8805** [comment]
另外，请问在树莓派上使用docker是否可以使用paddlepaddle呢？有没有文档呢？
