### ISSUE TITLE
Two deadlinks in fluid documentation

### ISSUE THREAD

**Issue by weixing02** [PaddlePaddle/Paddle#10484]
Fix most of deadlinks in fluid documentation, but there are still two deadlinks that i can't solve:
---
file:
- https://github.com/PaddlePaddle/Paddle/blob/develop/doc/fluid/design/motivation/api.md

page:
- http://www.paddlepaddle.org/docs/develop/documentation/fluid/en/design/motivation/api.html

deadlinks:
- https://github.com/PaddlePaddle/book/tree/develop/gan

---

file:
- https://github.com/PaddlePaddle/Paddle/blob/develop/doc/fluid/design/multi_devices/operator_kernel_type.md

page:
- http://www.paddlepaddle.org/docs/develop/documentation/fluid/en/design/multi_devices/operator_kernel_type.html

deadlinks:
- http://01org.github.io/mkl-dnn/structmkldnn_1_1memory.html

**Comment by luotao1** [comment]
1. since we don't have `gan` in `book` repo, this link should be removed.
2. http://01org.github.io is moved to http://intel.github.io
