### ISSUE TITLE
paddle v2如何自定义权重W

### ISSUE THREAD

**Issue by guozhizou** [PaddlePaddle/Paddle#10489]
想要实现：`x = MW + b`，其中M是一个m * n的矩阵数据，W（n * 1）、b (m * 1)是自定义的权重（fluid中有对应的paddle.fluid.layers.create_parameter），在paddle v2中如何实现？

**Comment by Xreki** [comment]
这个功能，可以通过定义一个fc layer来实现么？

**Comment by guozhizou** [comment]
fc的输入是vector，矩阵不行的吧

**Comment by Xreki** [comment]
fc的weights是`M x N`，输入是`batch_size x M`，但bias是`1 x N`的，这个可能不满足你的需求。

或许可以尝试使用[mixed layer](http://www.paddlepaddle.org/docs/develop/api/en/config/layer.html#mixed)和[full_matrix_projection](http://www.paddlepaddle.org/docs/develop/api/en/config/layer.html#full-matrix-projection)

**Comment by wanghaoshuang** [comment]
自定义初始化weights, 请参考这里：https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/v2/tests/test_parameters.py#L78

**Comment by Yancey1989** [comment]
由于长时间没有更新的信息，先关闭这个issue了，如有进一步反馈请随时重新打开，多谢！
