### ISSUE TITLE
adam algorithm problem

### ISSUE THREAD

**Issue by PseudoProgrammer** [PaddlePaddle/Paddle#1050]
the tester.INFO has  been pending the parameter of pass 1 for two days, ,with using adam algorithm or adamax algorithm,But the trainer.INFO works well.what's the problem?

tester.INFO
I0101 23:17:25.251305 40352 Trainer.cpp:425] Waiting for parameters of pass 1
I0101 23:18:25.251502 40352 Trainer.cpp:425] Waiting for parameters of pass 1

trainer.INFO
I1231 04:15:08.029392 27685 Trainer.cpp:640]  Pass=2 Batch=1420 samples=1120028 AvgCost=0.318963 Eval: macro-average-precision=0.867963 macro-average-recall=0.867666 macro-average-F1-score=0.867814 micro-average-precision=0.869009 
......
.......
I0101 22:26:46.301242 27685 Trainer.cpp:640]  Pass=18 Batch=1420 samples=1120028 AvgCost=0.156827 Eval: macro-average-precision=0.941429 macro-average-recall=0.940858 macro-average-F1-score=0.941143 micro-average-precision=0.94168

**Comment by qingqing01** [comment]
You start two processes, one for training, another for testing.  I wondered that the command line arguments for testing process are not correct.  Do you set the `--save_dir`  for testing process? And is it the same with the training process?  You could paste more logs, like the command line arguments of testing and training.

**Comment by PseudoProgrammer** [comment]
Either adam  or adamax alrgorithm come to this error, other algorithms don't!

test.INFO
I1230 22:55:50.111060 40352 GradientMachine.cpp:142] Loading parameters from ./output/pass-00000
I1230 23:12:25.299727 40352 ValidationLayer.cpp:119] auc=0.949401
I1230 23:12:25.362432 40352 Trainer.cpp:744]  Pass=0 samples=1502185 AvgCost=0.280517 Eval: macro-average-precision=0.893094 macro-average-recall=0.891227 macro-average-F1-score=0.892159 micro-average-precision=0.893256 
.....
......
I0101 23:17:25.251305 40352 Trainer.cpp:425] Waiting for parameters of pass 1
I0101 23:18:25.251502 40352 Trainer.cpp:425] Waiting for parameters of pass 1

test_arg
test_arg="--port=7164 --ports_num=1 --distribute_test=0 --job=test --test_pass=0 --test_wait=1 --dot_period=1 --log_period=1000 --saving_period=1 --num_passes=500 --start_pserver=0"
train_arg
train_arg="--saving_period=1 --port=7164 --ports_num=1 --local=0 --comment=$comment --dot_period=1000 --log_period=1000 --num_passes=100 --trainer_count=10 --ports_num_for_sparse=1 --use_sparse_updater=1 --use_old_updater=1 --enable_grad_sparse_update=50000000 --grad_sparse_update_max_sparse_rate=0.50"

**Comment by qingqing01** [comment]
看起来你的作业像是用旧的集群提交环境提交的， 这个问题可以在用户群里问，感觉还是有个作业链接可能好查看问题一些，另外建议你可以切换使用新版提交。

**Comment by qingqing01** [comment]
问题已找到，实际运行环境，train_arg和test_arg中的saving_period设置不等导致，如果发起两个进程要设置相同。 因此，关闭改issue。
