### ISSUE TITLE
seq2seq的c-api预测，如何在获得id标签的同时，拿到句子概率

### ISSUE THREAD

**Issue by wangshuohuan** [PaddlePaddle/Paddle#10504]
代码中的prob_matrix可以拿到值，但感觉不是句子的概率(如果是词的概率，如何进行组装，行列各代表什么)，已看过这个issue：https://github.com/PaddlePaddle/Paddle/issues/8293
，未能解决问题，麻烦帮忙看下，谢谢！ 预测代码如下：

    paddle_ivector source_word_paddle_vector = paddle_ivector_create(
        source_word_ids, sizeof(source_word_ids) / sizeof(int), false, false);

    paddle_arguments in_args = paddle_arguments_create_none();
    CHECK(paddle_arguments_resize(in_args, 1));

    CHECK(paddle_arguments_set_ids(in_args, 0, source_word_paddle_vector));

    int seq_pos_array[] = {0, sizeof(source_word_paddle_vector) / sizeof(int)};

    paddle_ivector source_word_pos_paddle_vector = paddle_ivector_create(
        seq_pos_array, sizeof(seq_pos_array) / sizeof(int), false, false);

    CHECK(paddle_arguments_set_sequence_start_pos(in_args, 0, 0, source_word_pos_paddle_vector));

    paddle_arguments out_args = paddle_arguments_create_none();
    CHECK(paddle_gradient_machine_forward(_local_machine,
                                          in_args,
                                          out_args,
                                          /* isTrain */ false));

    paddle_matrix prob_matrix = paddle_matrix_create_none();
    paddle_ivector beam_result_vector = paddle_ivector_create_none();

    paddle_real* prob_array;

    CHECK(paddle_arguments_get_value(out_args, 0, prob_matrix));
    CHECK(paddle_arguments_get_ids(out_args, 0, beam_result_vector));

    uint64_t beam_result_vector_size = 0;
    paddle_ivector_get_size(beam_result_vector, &beam_result_vector_size);

    std::vector<int> target_ids_vector;
    int* beam_result_array;
    paddle_ivector_get(beam_result_vector, &beam_result_array);

    std::cout << beam_result_vector_size << std::endl;
    for (int i = 0; i < beam_result_vector_size; i++) {
        std::cout << beam_result_array[i] << " ";
    }

**Comment by Xreki** [comment]
> CHECK(paddle_arguments_get_value(out_args, 0, prob_matrix));

`prob_matrix`里面存的就是句子的概率吧。可通过如下方式打印`probs_matrix`的值：
https://github.com/PaddlePaddle/Paddle/blob/c7c62e07db317756854a23aff1881541ea3b6966/paddle/capi/examples/model_inference/dense/main.c#L94-L106

**Comment by wangshuohuan** [comment]
我拿到的是width是1，height是解码长度，从头到尾输出来是这样的：
-0.0000  -0.0000  -0.0001  -0.0000  -0.0000  -0.0002  -0.0000  -0.0009  -0.0001  -0.0000  -0.0007  -0.0002  -0.0019  -0.0000  0.0000  -0.0014  -0.0003  -0.0005  0.0000  -0.0003  -0.0001  -0.0002  -0.0016  -0.0000  -0.0000  -0.0101  -0.0000  -0.0018  -0.0001  -0.0012  -0.0032  -0.0000  -0.0000  -0.0032  -0.0010  -0.0000  -0.0008  -0.0002  -0.0001  -0.0001  -0.0002  -0.0001  -0.0000  -0.0021  -0.0001  -0.0000  0.0000  -0.0009  -0.0014  -0.0001  -0.0001  -0.0196  0.0000  -0.0006  -0.0000  -0.0001  -0.0116  -0.0000  -0.0000  -0.0037  -0.0003  -0.0000  -0.0000  -0.0001  -0.0000  -0.0012  -0.0000  -0.0000  -0.0001  -0.0255  -0.0021  -0.0001  -0.0003  -0.0000  -0.0000  -0.0001  0.0000  -0.0000  -0.0005  -0.0027  -0.0008  -0.0012  0.0000  0.0000  -0.0000  -0.0114  -0.0083  -1.0000  -0.0000  -0.0000  -0.0001  -0.0000  -0.0000  -0.0002  -0.0000  -0.0009  -0.0001  -0.0000  -0.0007  -0.0002  -0.0019  -0.0000  0.0000  -0.0014  -0.0003  -0.0005  0.0000  -0.0003  -0.0001  -0.0002  -0.0016  -0.0000  -0.0000  -0.0101  -0.0000  -0.0018  -0.0001  -0.0012  -0.0032  -0.0000  -0.0000  -0.0032  -0.0010  -0.0000  -0.0008  -0.0002  -0.0001  -0.0001  -0.0002  -0.0001  -0.0000  -0.0021  -0.0001  -0.0000  0.0000  -0.0009  -0.0014  -0.0001  -0.0001  -0.0196  0.0000  -0.0006  -0.0000  -0.0001  -0.0116  -0.0000  -0.0000  -0.0037  -0.0003  -0.0000  -0.0000  -0.0001  -0.0000  -0.0012  -0.0000  -0.0000  -0.0001  -3.6812  -0.0001  -0.0019  -0.0000  -0.0000  -0.0001  0.0000  -0.0000  -0.0006  -0.0033  -0.0007  -0.0012  0.0000  0.0000  -0.0000  -0.0108  -0.0085  -1.0000  -0.0000  -0.0000  -0.0001  -0.0000  -0.0000  -0.0002  -0.0000  -0.0009  -0.0001  -0.0000  -0.0007  -0.0002  -0.0019  -0.0000  0.0000  -0.0014  -0.0003  -0.0005  0.0000  -0.0003  -0.0001  -0.0002  -0.0016  -0.0000  -0.0000  -0.0101  -0.0000  -0.0018  -0.0001  -0.0012  -0.0032  -0.0000  -0.0000  -0.0032  -0.0010  -0.0000  -0.0008  -0.0002  -0.0001  -0.0001  -0.0002  -0.0001  -0.0000  -0.0021  -0.0001  -0.0000  0.0000  -0.0009  -0.0014  -0.0001  -0.0001  -4.1362  0.0000  -0.0005  -0.0000  -0.0001  -0.0115  -0.0000  -0.0000  -0.0036  -0.0003  -0.0000  -0.0000  -0.0001  -0.0000  -0.0012  -0.0000  -0.0000  -0.0001  -0.0255  -0.0021  -0.0001  -0.0003  -0.0000  -0.0000  -0.0001  0.0000  -0.0000  -0.0005  -0.0027  -0.0008  -0.0012  0.0000  0.0000  -0.0000  -0.0114  -0.0083  -1.0000

对应的id是：87 4 5 10 4 5 8 4 5 7 4 5 16 47 3 4 6 12 17 3 3 4 5 21 4 6 42 3 3 4 6 11 3 4 5 7 4 4 20 9 4 5 8 4 19 9 3 4 5 23 4 6 31 3 3 4 6 39 3 4 5 24 4 25 27 13 13 3 3 3 3 4 5 18 4 6 14 3 3 3 4 6 14 3 3 3 3 1 -1 86 4 5 10 4 5 8 4 5 7 4 5 16 47 3 4 6 12 17 3 3 4 5 21 4 6 42 3 3 4 6 11 3 4 5 7 4 4 20 9 4 5 8 4 19 9 3 4 5 23 4 6 31 3 3 4 6 39 3 4 5 24 4 25 27 13 13 3 3 3 4 5 18 4 6 14 3 3 3 4 6 14 3 3 3 3 1 -1 87 4 5 10 4 5 8 4 5 7 4 5 16 47 3 4 6 12 17 3 3 4 5 21 4 6 42 3 3 4 6 11 3 4 5 7 4 4 20 9 4 5 8 4 19 9 3 4 5 23 4 6 32 3 3 4 6 39 3 4 5 24 4 25 27 13 13 3 3 3 3 4 5 18 4 6 14 3 3 3 4 6 14 3 3 3 3 1 -1

**Comment by guoshengCS** [comment]
问题已解决，关闭此issue。
