### ISSUE TITLE
can you upload the python install package which version is v0.12.0 to the website?

### ISSUE THREAD

**Issue by xylcbd** [PaddlePaddle/Paddle#10516]
I want to install the lastest paddle on my ubuntu server, but I cannot found the binary package of v0.12.0 on the website: http://www.paddlepaddle.org/docs/develop/documentation/fluid/en/build_and_install/pip_install_en.html

Could you please provide the binary package? thank you.

**Comment by yeyupiaoling** [comment]
It may not be updated in time. You can build from sources. document：http://paddlepaddle.org/docs/develop/documentation/fluid/en/build_and_install/build_from_source_en.html

**Comment by qingqing01** [comment]
In the website http://paddlepaddle.org/docs/develop/documentation/en/build_and_install/pip_install_en.html , the following `whl` packages are based on the latest develop branch.

![image](https://user-images.githubusercontent.com/7845005/39812529-9c96a2c8-53bf-11e8-85c1-37a7cb1ed26a.png)

But, there is some problem with the `whl` package updating. We are repairing them recently.

**Comment by xylcbd** [comment]
ok, thanks!
