### ISSUE TITLE
python mnist_v2.py

### ISSUE THREAD

**Issue by CHNEG8805** [PaddlePaddle/Paddle#10515]
我在centos7.3上install paddlepaddle,然后希望训练模型mnist_v2.py，执行后报错，如下图。请问是什么原因呢？
[root@localhost dense]# python mnist_v2.py 
I0509 05:58:53.570152  8785 Util.cpp:166] commandline:  --use_gpu=False --trainer_count=1 
I0509 05:58:53.576031  8785 GradientMachine.cpp:94] Initing parameters..
I0509 05:58:53.582324  8785 GradientMachine.cpp:101] Init parameters done.
Cache file /root/.cache/paddle/dataset/mnist/train-images-idx3-ubyte.gz not found, downloading http://yann.lecun.com/exdb/mnist/train-images-idx3-ubyte.gz
[==================================================]Cache file /root/.cache/paddle/dataset/mnist/train-labels-idx1-ubyte.gz not found, downloading http://yann.lecun.com/exdb/mnist/train-labels-idx1-ubyte.gz
[==================================================]*** Aborted at 1525845546 (unix time) try "date -d @1525845546" if you are using GNU date ***
PC: @                0x0 (unknown)
*** SIGSEGV (@0x50) received by PID 8785 (TID 0x7f715aa41740) from PID 80; stack trace: ***
    @     0x7f715a2535e0 (unknown)
    @     0x7f715a837aa6 _dl_relocate_object
    @     0x7f715a83fc5c dl_open_worker
    @     0x7f715a83b2d4 _dl_catch_error
    @     0x7f715a83f2cb _dl_open
    @     0x7f71598aba72 do_dlopen
    @     0x7f715a83b2d4 _dl_catch_error
    @     0x7f71598abb32 __GI___libc_dlopen_mode
    @     0x7f71598842a5 init
    @     0x7f715a250e20 __GI___pthread_once
    @     0x7f71598843bc __GI___backtrace
    @     0x7f71502e1643 (unknown)
    @     0x7f71502e1b80 (unknown)
    @     0x7f71502c883b (unknown)
    @     0x7f715a4a789c (unknown)
    @     0x7f715a4a9cba PyNumber_Multiply
    @     0x7f715a5412f0 PyEval_EvalFrameEx
    @     0x7f715a4c61f8 (unknown)
    @     0x7f715a53fb01 PyEval_EvalFrameEx
    @     0x7f715a4c61f8 (unknown)
    @     0x7f715a53fb01 PyEval_EvalFrameEx
    @     0x7f715a4c61f8 (unknown)
    @     0x7f715a4c1c6f (unknown)
    @     0x7f715a53fb01 PyEval_EvalFrameEx
    @     0x7f715a546efd PyEval_EvalCodeEx
    @     0x7f715a5443fc PyEval_EvalFrameEx
    @     0x7f715a546efd PyEval_EvalCodeEx
    @     0x7f715a5443fc PyEval_EvalFrameEx
    @     0x7f715a546efd PyEval_EvalCodeEx
    @     0x7f715a547002 PyEval_EvalCode
    @     0x7f715a56043f (unknown)
    @     0x7f715a5615fe PyRun_FileExFlags

gzip: stdout: Broken pipe
Segmentation fault

**Comment by yeyupiaoling** [comment]
你这个是哪个例子？你有没有修改过代码？

**Comment by CHNEG8805** [comment]
在Paddle-0.12.0/paddle/capi/examples/model_inference/dense/ 下的mnist_v2.py，没有改动过源码。
另外：在book/02.recognize_digits 下执行 python train.py 也报类似的错误，错误如下：
I0509 09:27:49.405292  4396 Util.cpp:166] commandline:  --use_gpu=False --trainer_count=1 
[INFO 2018-05-09 09:27:49,421 layers.py:2689] output for __conv_pool_0___conv: c = 20, h = 24, w = 24, size = 11520
[INFO 2018-05-09 09:27:49,423 layers.py:2829] output for __conv_pool_0___pool: c = 20, h = 12, w = 12, size = 2880
[INFO 2018-05-09 09:27:49,427 layers.py:2689] output for __conv_pool_1___conv: c = 50, h = 8, w = 8, size = 3200
[INFO 2018-05-09 09:27:49,428 layers.py:2829] output for __conv_pool_1___pool: c = 50, h = 4, w = 4, size = 800
I0509 09:27:49.436058  4396 GradientMachine.cpp:94] Initing parameters..
I0509 09:27:49.438542  4396 GradientMachine.cpp:101] Init parameters done.
*** Aborted at 1525858069 (unix time) try "date -d @1525858069" if you are using GNU date ***
PC: @                0x0 (unknown)
*** SIGSEGV (@0x50) received by PID 4396 (TID 0x7fad48c75740) from PID 80; stack trace: ***
    @     0x7fad484875e0 (unknown)
    @     0x7fad48a6baa6 _dl_relocate_object
    @     0x7fad48a73c5c dl_open_worker
    @     0x7fad48a6f2d4 _dl_catch_error
    @     0x7fad48a732cb _dl_open
    @     0x7fad47adfa72 do_dlopen
    @     0x7fad48a6f2d4 _dl_catch_error
    @     0x7fad47adfb32 __GI___libc_dlopen_mode
    @     0x7fad47ab82a5 init
    @     0x7fad48484e20 __GI___pthread_once
    @     0x7fad47ab83bc __GI___backtrace
    @     0x7fad3ef00643 (unknown)
    @     0x7fad3ef00b80 (unknown)
    @     0x7fad3eee783b (unknown)
    @     0x7fad486db89c (unknown)
    @     0x7fad486ddcba PyNumber_Multiply
    @     0x7fad487752f0 PyEval_EvalFrameEx
    @     0x7fad486fa1f8 (unknown)
    @     0x7fad48773b01 PyEval_EvalFrameEx
    @     0x7fad486fa1f8 (unknown)
    @     0x7fad48773b01 PyEval_EvalFrameEx
    @     0x7fad486fa1f8 (unknown)
    @     0x7fad486f5c6f (unknown)
    @     0x7fad48773b01 PyEval_EvalFrameEx
    @     0x7fad4877aefd PyEval_EvalCodeEx
    @     0x7fad487783fc PyEval_EvalFrameEx
    @     0x7fad4877aefd PyEval_EvalCodeEx
    @     0x7fad487783fc PyEval_EvalFrameEx
    @     0x7fad4877aefd PyEval_EvalCodeEx
    @     0x7fad4877b002 PyEval_EvalCode
    @     0x7fad4879443f (unknown)
    @     0x7fad487955fe PyRun_FileExFlags

gzip: stdout: Broken pipe
Segmentation fault

**Comment by qingqing01** [comment]
```
gzip: stdout: Broken pipe
Segmentation fault
```
从错误信息来看，似乎是Python在读取数据/root/.cache/paddle/dataset/mnist/train-images-idx3-ubyte.gz  和 /root/.cache/paddle/dataset/mnist/train-labels-idx1-ubyte.gz时出现了问题。

或许可以单独验证下reader程序部分。

**Comment by CHNEG8805** [comment]
谢谢，我尝试一下
