### ISSUE TITLE
seq_reshape与sub_seq

### ISSUE THREAD

**Issue by yttbgf** [PaddlePaddle/Paddle#10524]
需要对一个序列变形，之后按一定索引截取子序列,无法执行,详细信息在群里提供

**Comment by qingqing01** [comment]
请将错误信息，贴到issue里，谢谢了~

**Comment by yttbgf** [comment]
![data](https://user-images.githubusercontent.com/38252563/39850024-ddf8589c-5441-11e8-8724-0373a24aed59.jpg)
![ex](https://user-images.githubusercontent.com/38252563/39850025-de3dd4da-5441-11e8-821f-b6b100ae537e.jpg)
![ex1](https://user-images.githubusercontent.com/38252563/39850026-de885384-5441-11e8-8ca3-5d1f84bdf08a.jpg)
@qingqing01

**Comment by yttbgf** [comment]
@qingqing01 
![code1_1](https://user-images.githubusercontent.com/38252563/39851735-49a3a674-544b-11e8-85c0-bc3b606cce74.jpg)

![code2_1](https://user-images.githubusercontent.com/38252563/39851713-1928bf20-544b-11e8-9fe5-3abe551ec075.jpg)
![code3_1](https://user-images.githubusercontent.com/38252563/39851746-55b225bc-544b-11e8-84f6-0a0fc85c1f54.jpg)

**Comment by qingqing01** [comment]
从上述SubSequenceLayer.cpp:115行的错误信息来看，是`sub_seq`用的不对。举例来说：

```
第0个输入input:
[
  [0,2,3,4],
  [3,4,4,5],
  [4,5,7,8],  # 第一个样本到这里，共3个time step
  [1,2,5,4],
  [7,4,2,5],
  [4,3,1,8],  
  [5,6,7,2], # 第二个样本到这里，共4个time step
]

第1个输入offset:
[
 0,
 2  
] #2个样本，这里也总共2个。

第2个输入size:
[
 2,
 1
] #2个样本，这里也总共2个。

输出：
[
  [0,2,3,4],
  [3,4,4,5], #  第一个样本取第0，1个time step
  [4,3,1,8],  #  第二个样本取第2个time step
]
```

sub_seq只能类似的这样用，offset和size一个样本只能1个，总共只能和batch size数相等。 请确认你是否想要的这样的操作，以及用是否正确。

另外，请以后贴代码，上面贴图片不是很友好。
