### ISSUE TITLE
提取图片，3d图像的特征可以用paddlepaddle？

### ISSUE THREAD

**Issue by NZQH** [PaddlePaddle/Paddle#10521]
提取图片，3d图像的特征可以用paddlepaddle？行的话一个大概的思路是怎么样的？

**Comment by NZQH** [comment]
抱歉，因为我不专业的问题使得我刚才的表述有问题，我其实要问的是AR（特征检测->图像识别->AR跟踪）的实现过程是否可以和paddlePaddle结合

发送自 Windows 10 版邮件应用

发件人: qingqing01
发送时间: 2018年5月9日 17:21
收件人: PaddlePaddle/Paddle
抄送: NZQH; Author
主题: Re: [PaddlePaddle/Paddle] 提取图片，3d图像的特征可以用paddlepaddle？ (#10521)

3d图像的特征可以用paddlepaddle
不是特别理解意图。能详细描述下吗？是说3D CNN模型？

**Comment by NZQH** [comment]
抱歉，因为我不专业的问题使得我刚才的表述有问题，我其实要问的是AR（特征检测->图像识别->AR跟踪）的实现过程是否可以和paddlePaddle结合 @qingqing01

**Comment by qingqing01** [comment]
特征检测->图像识别->AR跟踪要分析各个步骤的模型Paddle是否支持吧，如果支持，就可以。如果有不支持的，就不行。 要具体分析你用什么检测、识别算法，跟踪方法。关于Paddle支持的模型例子，可以参考 https://github.com/paddlepaddle/models  。
