### ISSUE TITLE
RNN search inference

### ISSUE THREAD

**Issue by sfraczek** [PaddlePaddle/Paddle#10529]
Hi,
We need to benchmark inference for RNN search.
In benchmark/fluid/machine_translation.py I found that there is no **inference_only** path:
```
def infer():
    pass
```
And the **with_test** switch seems to add a test phase but it does not output any accuracy.

Do you plan to add inference?

@dzhwinter, maybe you could help?

**Comment by luotao1** [comment]
@sfraczek We are still working on the inference of RNN search, the beam_search process is not ready now. As soon as we finish the inference, we will tell you.
