### ISSUE TITLE
cluster加载init_model_path报错，但查看hdfs上是有该文件

### ISSUE THREAD

**Issue by qubingxin** [PaddlePaddle/Paddle#1052]
训练AlexNetmodel，几百个pass后错误率不下降。因此使用--init_model_path加载已有模型。
--init_model_path /app/msbu/dpp/qubingxin/paddle/skin_disease/disease_subpic_5/output_20161230112232/model_output/pass-00366

报错如下：
I0103 10:54:17.418300 19798 GradientMachine.cpp:142] Loading parameters from /app/msbu/dpp/qubingxin/paddle/skin_disease/disease_subpic_5/output_20161230112232/model_output/pass-00366
I0103 10:54:17.418331 19798 Parameter.cpp:339] missing parameters [/app/msbu/dpp/qubingxin/paddle/skin_disease/disease_subpic_5/output_20161230112232/model_output/pass-00366/___conv_0__.w0] while loading model.
F0103 10:54:17.418344 19798 Parameter.cpp:345] ___conv_0__.w0 missing, not allowed. 

用hadoop fs -ls 查看该目录下，___conv_0__.w0是存在的，请问怎么解决？

**Comment by qubingxin** [comment]
已解决，closed

**Comment by qubingxin** [comment]
此外，能否提供针对paddle_platform平台的alexnet模型提供pyDataProvider2的demo？ 目前的不是

**Comment by reyoung** [comment]
Hadoop的HDFS上面有不代表同时传递到MPI节点上了，也就是运行那个Paddle进程的机器里面没有这些参数。解决办法是

* 将对应参数和Paddle的二进制一起打包传到MPI上。然后修改`--init_model_path `到MPI下的某个路径。
* 或者，直接修改paddle的训练脚本，在mpi上从HDFS下下载这些参数。

**Comment by qubingxin** [comment]
直接修改paddle的训练脚本，在mpi上从HDFS下下载这些参数。这个方法能否提供一个demo？目前是在cluster_config里添加model_path参数，不起作用

**Comment by qubingxin** [comment]
在cluster_config中添加init_model_path，可解决，之前问题是添加了model_path
