### ISSUE TITLE
Improve Paddle on Kubernetes Tutorial

### ISSUE THREAD

**Issue by wangkuiyi** [PaddlePaddle/Paddle#1053]
1. k8s-aws/README.md refers to k8s/*.{sh,py,yaml}, but doesn't have links.
1. /home/admin/efs ==> /home/core/efs
1. drinkcode/paddle:k8s-job ==> paddle-dev/paddle:k8s
1. /home/jobpath => /efs
1. Don't map container internal ports to host ports, so that multiple Pods can run on the same node.
1. /root in [file](https://github.com/PaddlePaddle/Paddle/blob/develop/doc/howto/usage/cluster/k8s/start.sh#L5) ==> /cache

**Comment by luotao1** [comment]
@typhoonzero @Yancey1989 
Can this issue be closed ?

**Comment by Yancey1989** [comment]
Thanks @luotao1 , we have the repo: https://github.com/PaddlePaddle/cloud to schedule PaddlePaddle job on Kubernetes, if we have any idea, please create issue on the cloud repo.
