### ISSUE TITLE
Show and Tell: A Neural Image Caption Generator

### ISSUE THREAD

**Issue by VamWolf** [PaddlePaddle/Paddle#1056]
[https://github.com/tensorflow/models/blob/master/im2txt/g3doc/show_and_tell_architecture.png](url)

paddle 实现这个结构，是不是
image embeding 一层
word  embeding 一层
两层连接，concat_layer 
然后，作为lstm 的输入，lstm层 得到encoded vector. 
decode ，参考seqToseq 的解码部分就可以了

**Comment by Zrachel** [comment]
有一点不一样，
两层连接，应该用SequenceConcatLayer (concat_layer是指两个拼起来的size是两个相加的size)

**Comment by VamWolf** [comment]
SequenceConcatLayer 在 trainer_config_helpers 里目前没有，./trainer/config_parser.py 里有，应该是可以按照 paddle v1 的方式使用？？？

**Comment by Zrachel** [comment]
是的

**Comment by Yancey1989** [comment]
这issue太久没更新了，如果有更新再打开吧，多谢。
