### ISSUE TITLE
first_seq 

### ISSUE THREAD

**Issue by shboy** [PaddlePaddle/Paddle#10562]
lstm_layer = paddle.layer.lstmemory(input=input_emb_1, reverse=False, param_attr=lstm_para_attr)
    r_lstm_layer = paddle.layer.lstmemory(input=input_emb_2, reverse=True, param_attr=lstm_para_attr)

    elast_layer = paddle.layer.last_seq(input=lstm_layer)
    r_elast_layer = paddle.layer.first_seq(input=r_lstm_layer)
   concat_layer = paddle.layer.concat(input=[elast_layer, r_elast_layer])

reverse = True
是要取first_seq么

**Comment by seiriosPlus** [comment]
没太明白你的意图。
lstmemory 以及 first_seq 和last_seq 中关于正序、逆序的说明可以参考：
https://github.com/PaddlePaddle/Paddle/blob/d02a68c4472d3b85559f82c026896bf2cf563b07/python/paddle/trainer_config_helpers/layers.py#L1815
https://github.com/PaddlePaddle/Paddle/blob/d02a68c4472d3b85559f82c026896bf2cf563b07/python/paddle/trainer_config_helpers/layers.py#L1756

**Comment by shboy** [comment]
我当时第二句用last_seq的时候，显示了这句话
"You are getting the last instance of a sequence that"
                       " is a output of a REVERSED layer. There is no time"
                       " series information at all. Maybe you want to use"
                       " first_seq instead."

**Comment by shboy** [comment]
所以我改的正确吗

**Comment by seiriosPlus** [comment]
看提示是对的

**Comment by shboy** [comment]
好的~
