### ISSUE TITLE
NotImplementedError: Wrong number or type of arguments for overloaded function 'IVector_create'.

### ISSUE THREAD

**Issue by peiss** [PaddlePaddle/Paddle#10570]
我使用的是book/06.understand_sentiment/train.py
想要改造成多文本分类

我的输入数据，已经是数字化了
features包括：
1、分类数据，处理成one-hot，共44列；
2、words的word2vec数据，共100列；

label是0~5，共6个类别；

对train.py的改造：
`    # data
    ## print 'load dictionary...'
    ## word_dict = paddle.dataset.imdb.word_dict()

    # features count
    dict_dim = 144
    class_dim = 6
    train_reader = paddle.batch(
        paddle.reader.shuffle(
            hackathon_disease_utils.train_reader, buf_size=1000),
        batch_size=100)
    test_reader = paddle.batch(
        hackathon_disease_utils.test_reader, batch_size=100)

    feeding = {'word': 0, 'label': 1}
`

我自己的hackathon_disease_utils.train_reader的主要代码为：

`
def read_datas():
    xdata = []
    ydata = []
    for line in open("./model_input_numbers_data.txt.10"):
        line = line[:-1]
        fields = line.split("\t")
        if len(fields) != 2: continue
        features, label = fields
        features_split = [float(x) for x in features.split(",")]
        label = int(float(label))

        print len(features_split), label
        xdata.append(features_split)
        ydata.append(label)
    return xdata, ydata

xdata, ydata = read_datas()
from sklearn.model_selection import train_test_split
import numpy as np

X_train, X_test, y_train, y_test = train_test_split(xdata, ydata, test_size=0.2, random_state=42)

def train_reader():
    for x, y in zip(X_train, y_train):
        yield np.array(x, np.float32), np.array(y, np.int32)

def test_reader():
    for x, y in zip(X_test, y_test):
        yield np.array(x, np.float32), np.array(y, np.int32)
`

其中原始数据长这个样子，其中最后一列是分类的标签：
`0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.05035369468708362,-0.11058226762166856,-0.04626769008885684,-0.05574304173351579,0.03453315805457131,0.010198460353923768,0.11178969553017443,-0.024947830289200848,0.03733541596287476,-0.020355124813343943,0.05546023574926698,-0.15395705042791288,-0.07297490536765164,-0.0412616191656682,-0.09094961783708201,4.439948748642627E-4,0.08310209437281471,-0.038937906015078246,-0.06895857391646132,-0.053934162984409464,0.11769125419809355,-0.009530712256272292,0.08987006533626017,0.05954042228655328,-0.07097658626718902,0.012000049895944137,-0.10276833170591372,0.027582694483310754,0.154955423812398,-0.12002582568359309,-0.008334885704369237,0.1452031820763609,0.061828807618565344,0.033535506800098085,-0.030156932579271156,0.11997460617467054,0.027519867594899803,0.032305058056251786,-0.09902765967879155,-0.012392273998682804,-0.08639632723924447,0.03841115919780789,-0.10587196476990357,-0.16224580381772127,-0.08879026767380278,-0.051423383688008216,-0.06667494091831533,0.026893501762091983,-2.5994363160611225E-4,-0.13750840343408496,-0.12729147219014803,0.0561466093359772,-0.043173990234459655,0.012280527357782784,-0.09493523907189354,0.039277604229122014,-0.06849797709909236,-0.02247113547817772,0.03908506865044383,0.02431180926866765,-0.03732159799005001,-0.003602075402560676,-0.05814249472339349,0.036534004974187,0.11444050486697334,0.002209303479095728,-0.054767017531738585,-0.009210306665346283,0.03622044408163266,-0.03960667211566911,0.062471401889744246,0.1609201731746374,-0.09315723877054928,0.025208703248263818,0.04963106302351787,0.01941258055388783,0.05542753479074173,-0.015436904535002622,0.06262154306851103,-0.0171438038859974,-0.03317034920988151,-0.10868422872314615,0.09739351164346866,-0.048350167642387656,-0.06462607320382036,-0.049236976192332804,0.18659101511805382,0.007606043703131506,-0.09447748639624855,0.05996697946403432,-0.0019816041182413504,-0.012335850114548772,0.01357896166957979,0.0023331985937367224,0.05948535343712388,0.04088002962064287,-0.09049651064661106,-0.08426264521730101,-0.005094437787694664,-0.061239236585418536	0.0
`

train_reader()的数据长这个样子：
(array([ 1.00000000e+00,  0.00000000e+00,  1.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  1.00000000e+00,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00,  1.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        6.40203506e-02,  1.32586937e-02,  1.07684806e-01,  9.72034410e-02,
       -1.14319772e-01, -1.20517118e-02,  4.60293852e-02,  2.68057436e-02,
        1.03367604e-01, -3.89928333e-02,  2.43951473e-02, -2.85483319e-02,
       -1.69568658e-02, -4.10309769e-02,  9.94101763e-02, -5.63507266e-02,
       -6.39652042e-03, -2.96117198e-02,  9.48932096e-02, -6.24678880e-02,
       -3.87909450e-02,  2.01711971e-02,  3.64389494e-02,  1.76385753e-02,
        4.57788967e-02,  4.22310345e-02,  1.68721620e-02,  7.63846142e-03,
       -1.42602548e-01, -5.54708987e-02,  4.64005768e-02, -2.74553392e-02],
      dtype=float32), array(0, dtype=int32))

请问咋办呢，我看了这个问题的其他issue，试着加上了dtype=float32和dtype=int32，可是没有解决

**Comment by seiriosPlus** [comment]
没有太明白~~

**Comment by peiss** [comment]
I0510 19:14:48.341439 2459259776 Util.cpp:166] commandline:  --use_gpu=False 
I0510 19:14:48.361587 2459259776 GradientMachine.cpp:94] Initing parameters..
I0510 19:14:48.368325 2459259776 GradientMachine.cpp:101] Init parameters done.
Traceback (most recent call last):
  File "hackathon_disease_cat.py", line 99, in <module>
    num_passes=20)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/paddle/v2/trainer.py", line 169, in train
    in_args = feeder(data_batch)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/py_paddle/dataprovider_converter.py", line 282, in __call__
    return self.convert(dat, argument)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/paddle/v2/data_feeder.py", line 133, in convert
    return DataProviderConverter.convert(self, reorder_data(dat), argument)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/py_paddle/dataprovider_converter.py", line 277, in convert
    scanner.finish_scan(argument)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/py_paddle/dataprovider_converter.py", line 211, in finish_scan
    ids = swig_paddle.IVector.create(self.__ids__, self.data_in_gpu)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/py_paddle/swig_paddle.py", line 1344, in create
    return _swig_paddle.IVector_create(*args)
NotImplementedError: Wrong number or type of arguments for overloaded function 'IVector_create'.
  Possible C/C++ prototypes are:
    IVector::create(std::vector< int,std::allocator< int > > const &,bool)
    IVector::create(std::vector< int,std::allocator< int > > const &)

**Comment by seiriosPlus** [comment]
看异常是你的输入数据类型不对

**Comment by peiss** [comment]
已解决，了解了sequence的含义

**Comment by GuoLiuFang** [comment]
@peiss 怎么解决的？

> 已解决，了解了sequence的含义
