### ISSUE TITLE
ContextProjection.cpp:108] Check failed: in_->sequenceStartPositions

### ISSUE THREAD

**Issue by peiss** [PaddlePaddle/Paddle#10573]
对情感分类的BOOK的代码修改后，报错：

修改为：

def convolution_net(input_dim, class_dim, emb_dim=128, hid_dim=128):
    data = paddle.layer.data("word",
                             paddle.data_type.dense_vector(input_dim))

    # emb = paddle.layer.embedding(input=data, size=emb_dim)
    conv_3 = paddle.networks.sequence_conv_pool(
        input=data, context_len=3, hidden_size=hid_dim)
    conv_4 = paddle.networks.sequence_conv_pool(
        input=data, context_len=4, hidden_size=hid_dim)

    output = paddle.layer.fc(
        input=[conv_3, conv_4], size=class_dim, act=paddle.activation.Softmax())
    lbl = paddle.layer.data("label", paddle.data_type.integer_value(class_dim))

    cost = paddle.layer.classification_cost(input=output, label=lbl)

    return cost, output

报错为：
I0510 19:27:13.698177 2459259776 Util.cpp:166] commandline:  --use_gpu=False 
I0510 19:27:13.712461 2459259776 GradientMachine.cpp:94] Initing parameters..
I0510 19:27:13.718333 2459259776 GradientMachine.cpp:101] Init parameters done.
F0510 19:27:13.725885 2459259776 ContextProjection.cpp:108] Check failed: in_->sequenceStartPositions 
*** Check failure stack trace: ***
    @        0x10efe1ba5  google::LogMessage::Flush()
    @        0x10efe5cef  google::LogMessageFatal::~LogMessageFatal()
    @        0x10efe2999  google::LogMessageFatal::~LogMessageFatal()
    @        0x10f096f00  paddle::ContextProjection::forward()
    @        0x10f03c671  paddle::MixedLayer::forward()
    @        0x10f0bee9e  paddle::NeuralNetwork::forward()
    @        0x10f0b1c43  paddle::GradientMachine::forwardBackward()
    @        0x10f327b56  GradientMachine::forwardBackward()
    @        0x10efbd7de  _wrap_GradientMachine_forwardBackward()
    @        0x1000c752a  PyEval_EvalFrameEx
    @        0x1000ca193  PyEval_EvalCodeEx
    @        0x1000c6ae5  PyEval_EvalFrameEx
    @        0x1000ca193  PyEval_EvalCodeEx
    @        0x1000c6ae5  PyEval_EvalFrameEx
    @        0x1000ca193  PyEval_EvalCodeEx
    @        0x1000c6ae5  PyEval_EvalFrameEx
    @        0x1000ca193  PyEval_EvalCodeEx
    @        0x1000ca2b6  PyEval_EvalCode
    @        0x1000ef21e  PyRun_FileExFlags
    @        0x1000ef4ba  PyRun_SimpleFileExFlags
    @        0x1001066dd  Py_Main
Abort trap: 6

我的输入数据已经处理成onehot和word2vec的向量了，不用embdding了；
输入数据说明在：https://github.com/PaddlePaddle/Paddle/issues/10570

这俩说不定是一个问题

**Comment by seiriosPlus** [comment]
你的输入数据不是sequence的，但是你用了sequence的网络结构

**Comment by luotao1** [comment]
输入数据必须使用sequence类型的数据 http://www.paddlepaddle.org/docs/develop/documentation/zh/getstarted/concepts/use_concepts_cn.html#id4

请按照表中的sequence数据格式先检查下。

**Comment by peiss** [comment]
看了文档，知道了我的数据属于：
dense_vector：稠密的浮点数向量。
SequenceType.NO_SEQUENCE：不是一条序列

然而我看了很多地方，还是不知道咋改这个代码
paddle.data_type.dense_vector(input_dim)
这个方法，是不是有个参数，可以指定是SequenceType.NO_SEQUENCE？

**Comment by peiss** [comment]
paddle.data_type.dense_vector(input_dim, seq_type = SequenceType.NO_SEQUENCE)

是改成这样对吗，用seq_type这个来指定

**Comment by luotao1** [comment]
如果你的数据是dense_vector，非序列数据。就不能使用sequence_conv_pool，这层是对序列数据操作的。

**Comment by peiss** [comment]
@luotao1 谢谢
