### ISSUE TITLE
paddle线上预测出错

### ISSUE THREAD

**Issue by xusoda** [PaddlePaddle/Paddle#10577]
paddle多线程公用一个模型不可以么？
没有使用multi thread 的方式。
>>>
F0510 22:13:40.048722 15780 SequencePoolLayer.cpp:59] Check failed: starts->getData()[newBatchSize_] == input.getBatchSize() (50 vs. 49)
*** Check failure stack trace: ***
Thread [140616306288384] Forwarding right_utag_pool,
*** Aborted at 1525961620 (unix time) try "date -d @1525961620" if you are using GNU date ***
PC: @                0x0 (unknown)

*** SIGABRT (@0x1f600002226) received by PID 8742 (TID 0x7fe3c8fc6700) from PID 8742; stack trace: ***
    @     0x7fe818049160 (unknown)
    @     0x7fe8150553f7 __GI_raise
    @     0x7fe8150567d8 __GI_abort
已放弃 (core dumped)

**Comment by Yancey1989** [comment]
由于长时间没有更新的信息，先关闭这个issue了，如有进一步反馈请随时重新打开，多谢！
