### ISSUE TITLE
Paddle支持Python3吗？

### ISSUE THREAD

**Issue by Guangzhan** [PaddlePaddle/Paddle#10581]
Paddle是否可以支持Python3？

**Comment by luotao1** [comment]
请参考 https://github.com/PaddlePaddle/Paddle/issues/9174#issuecomment-374092633

**Comment by ktlichkid** [comment]
Same issue with #9174

**Comment by velconia** [comment]
Paddle Fluid 会在 0.15.0 发布python3的试用版, 1.0 发布正式版. 

这个 [issue](https://github.com/PaddlePaddle/Paddle/issues/12040) 记录了我们的工作;
