### ISSUE TITLE
什么就没有selective_fc的使用方法的详细文档，或者详细示例说明呢

### ISSUE THREAD

**Issue by chenbblei** [PaddlePaddle/Paddle#10583]
官网上虽然有一个关于推荐的示例，但关于select只要设置为height为1即可，
但是如果有多个输入同时输入，比如语音 100帧40维，即输入为100*40，那么此时的
select的参数height应该为100，而不是1，所以使用推荐的那个示例就行不通了，但
关于selective_fc的参数介绍，并没有介绍在这种情况下，select该怎么设置了，
感觉文档方面太不详细了，用起来越来越难了

**Comment by lcy-seso** [comment]
我先来解释一下`selective_fc`在计算什么以及一些`height`代表`width`什么，`selective_fc`有训练和预测两个分枝，这两个分枝的行为很不相同，并且`selective_fc`用于训练，目前程序的实现有一些使用上的限制。希望能有所帮助。

`selective_fc`也是完成矩阵乘法运算，但相对于普通的全连接（fc）增加了一个额外的参数`selected rows`，关于`selective_fc`训练时刻的计算过程请看下面这幅图：
<p align="center">
<img src="https://user-images.githubusercontent.com/5842774/39908392-8151571c-5520-11e8-8742-fa0dd88faaf4.png" width=60%>
</p>

- 在上面这幅图中，输入矩阵$x$是一个$3 \times 5$的矩阵，`selective_fc`的可学习参数$W$是一个$5 \times 7$大小的矩阵。
- `selected_rows` （也就是`paddle.layer.selective_fc`的第三个参数：`select`）是： `[2, 4]`
- `selective_fc` 完成输入矩阵与连接矩阵（本层的可学习参数）之间选择性地矩阵乘法运算。针对上面的图：
    - 正常的矩阵乘法是数据矩阵的每一行与连接矩阵的每一列进行点积，得到输出矩阵上的一个元素；
    - 而`selective_fc`只将输入矩阵的每一行与连接矩阵中被选择的列进行点积。
--- 

在上面这幅图的基础上，再来解释一下`selective_fc`接口中几个比较重要的参数的作用

```python
def selective_fc_layer(input,
                       size,
                       select=None,
                       act=None,
                       name=None,
                       pass_generation=False,
                       has_selected_colums=True,
                       mul_ratio=0.02,
                       param_attr=None,
                       bias_attr=None,
                       layer_attr=None)
```

还是以上图为例：

-  size 须设置为 7 而不是 2。`selective_fc` 需要知道本层有多少可学习参数需要学习。
- select 参数需要通过`data_layer`给进来，类型是`binary_sparse_vector`，而`binary_sparse_vector`在定义时同样需要指定宽度，需要设置为 7 。
- 在训练阶段，请注意，**每一条样本都必须选择连接矩阵中同样多的列，不支持选择不同多的列**，最终输出矩阵的宽度是在运行过程中由`select`这个输入到底选择了多少列决定的。

**Comment by lcy-seso** [comment]
这里有一个细节必须说明，在上面的图中，有一个地方画的可能会有些混淆：
图中看上去是选择了矩阵的一列，图注我写了rows。矩阵内部存储是以优先存储，这时候选择一列的时间成本会较高，可以认为`selecitve_fc`的可学习参数是以行优先进行存储的。如果`selective_fc`用在预测中，加载了用fc训练的参数，一定要对fc的参数首先进行转置。

![image](https://user-images.githubusercontent.com/5842774/39908521-10fb726c-5521-11e8-852e-7be503ec11f6.png)

**Comment by lcy-seso** [comment]
一些提示避免使用selective fc层出错。selective fc这个层用于训练是为了实现samped softmax算法而实现，[On Using Very Large Target Vocabulary for Neural Machine Translation](http://www.aclweb.org/anthology/P15-1001)。在sampled softmax 算法里面，selective_fc 会直接接softmax然后接cross entropy，这种情况下cross entropy的类别序号需要重新进行映射。

**Comment by chenbblei** [comment]
@lcy-seso 多谢多谢！我先看看兄弟你写的哈

**Comment by chenbblei** [comment]
@lcy-seso 兄弟，我如何使用binary_sparse_vector生成一个上图中
2 4 
3 5
1 0
的ararry呢，现在总是提示height不一致，我猜测可能就是这个实现的不对

**Comment by lcy-seso** [comment]
能否贴一下具体的报错，方便定位程序走到哪里报错，以确定精确的原因。

p.s ：我不是兄弟。

**Comment by chenbblei** [comment]
@lcy-seso 
具体是这样的，我的fc输出如下：
fc = paddle.layer.fc(
        input=rnn_group_output,
        size=dict_size + 1,
        act=paddle.activation.Linear(),
        bias_attr=True,
        layer_attr=paddle.attr.ExtraLayerAttribute(drop_rate=0.5))
其中dict_size是176*2,
fc.size为176*2+1，fc输出的是一句语音中每一帧的输出的176*2+1个类别值，也就是N帧*（176*2+1）的输出，
然后我调用fc_wav = paddle.layer.selective_fc(input=fc,select=sel_wav_binary,size=dict_size+1,act=paddle.activation.Linear())

其中sel_wav_binary定义如下：
sel_wav_binary = paddle.layer.data(
            name='select_wav_binary',
            type=paddle.data_type.sparse_binary_vector((vocab_size*2+1)))
vocab_size也是176，
其中“select_wav_binary”的输入来自于以下list_wav：
list_wav = []
for i in range(176):
   list_wav.append(i)
list_wav.append(176*2+1)

然后以运行就报错信息如下：
F0510 19:10:41.672122 11590 SelectiveFullyConnectedLayer.cpp:134] Check failed: height == selCols_->getHeight()
*** Check failure stack trace: ***
@ 0x7fa932b942ed google::LogMessage::Fail()
@ 0x7fa932b97d9c google::LogMessage::SendToLog()
@ 0x7fa932b93e13 google::LogMessage::Flush()
@ 0x7fa932b992ae google::LogMessageFatal::~LogMessageFatal()
@ 0x7fa932894fec paddle::SelectiveFullyConnectedLayer::forward()
@ 0x7fa93278ea4d paddle::NeuralNetwork::forward()
@ 0x7fa93276bf54 paddle::TrainerThread::forward()
@ 0x7fa93276d255 paddle::TrainerThread::computeThread()
@ 0x7fa9a9e53870 (unknown)
@ 0x7fa9bb8f8dc5 start_thread
@ 0x7fa9baf1d21d __clone
@ (nil) (unknown)

**Comment by lcy-seso** [comment]
配置中设置的size是正确的，但是给数据是错误的。这个错误在检查selective_fc第一个输入也就是数据输入的batch size和第二个输入也就是selected rows的batch size是一致的。

**Comment by lcy-seso** [comment]
如何传入binary_sparse_vector请参考这篇文档 http://www.paddlepaddle.org/docs/develop/documentation/zh/getstarted/concepts/use_concepts_cn.html 中数据说明的部分：

![image](https://user-images.githubusercontent.com/5842774/39916535-5aaf7ab8-553d-11e8-887a-517de055ac16.png)

**Comment by chenbblei** [comment]
@lcy-seso 谢谢，这两个值height == selCols_->getHeight()我有办法打印出来么？
