### ISSUE TITLE
[Help] PaddlePaddle有没整体架构和细节文档

### ISSUE THREAD

**Issue by zhanglistar** [PaddlePaddle/Paddle#10593]
如题，想深入研究和优化下。

**Comment by shanyi15** [comment]
hi, 您好，请您描述的更详细一些，方便找到对应的老师来回答。
例如：
您指的版本是：v2 or fluid？
细节文档的意思是？

**Comment by qichaotang** [comment]
v2 和 fluid 版本

**Comment by yeyupiaoling** [comment]
@qichaotang PaddlePaddle的官网就有文档：paddlepaddle.org，还有是百度训练营：ai.baidu.com/paddlepaddle

**Comment by Yancey1989** [comment]
这个issue很久没有更新的消息了，我先关闭它了，如仍然有疑问请随时打开它，多谢！
