### ISSUE TITLE
安装paddlepaddle fluid版本后import paddle.fluid error

### ISSUE THREAD

**Issue by buzzf** [PaddlePaddle/Paddle#10607]
本人系统，Ubuntu 16.04，cuda8.0, cudnn 6.0, 安装最新版的paddlepaddle fluid 后，import paddle时问题如下：
在命令行下

` import paddle`
` import paddle.v2`

都没问题，唯独

 `import paddle.fluid`

后报错信息如下：
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/paddle/fluid/__init__.py", line 132, in <module>
    __bootstrap__()
  File "/usr/local/lib/python2.7/dist-packages/paddle/fluid/__init__.py", line 126, in __bootstrap__
    core.init_devices(not in_test)
paddle.fluid.core.EnforceNotMet: CUBLAS: not initialized,  at [/paddle/paddle/fluid/platform/device_context.cc:153]
PaddlePaddle Call Stacks: 
0       0x7f0238da06f6p paddle::platform::EnforceNotMet::EnforceNotMet(std::__exception_ptr::exception_ptr, char const*, int) + 486
1       0x7f0239b1ee54p paddle::platform::CUDADeviceContext::CUDADeviceContext(paddle::platform::CUDAPlace) + 1684
2       0x7f0239b1feb0p paddle::platform::DeviceContextPool::DeviceContextPool(std::vector<boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_>, std::allocator<boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> > > const&) + 752
3       0x7f0238e368bcp paddle::framework::InitDevices(bool, std::vector<int, std::allocator<int> >) + 588
4       0x7f0238e36addp paddle::framework::InitDevices(bool) + 285
5       0x7f0238d865bap
6       0x7f0238db1804p pybind11::cpp_function::dispatcher(_object*, _object*, _object*) + 2596
7             0x4bc3fap PyEval_EvalFrameEx + 1482
8             0x4b9ab6p PyEval_EvalCodeEx + 774
9             0x4c1e6fp PyEval_EvalFrameEx + 24639
10            0x4b9ab6p PyEval_EvalCodeEx + 774
11            0x4b97a6p PyEval_EvalCode + 22
12            0x4b96dfp PyImport_ExecCodeModuleEx + 191
13            0x4b2b06p
14            0x4b402cp
15            0x4a4ae1p
16            0x4a4513p PyImport_ImportModuleLevel + 2259
17            0x4a59e4p
18            0x4a577ep PyObject_Call + 62
19            0x4c5e10p PyEval_CallObjectWithKeywords + 48
20            0x4be6d7p PyEval_EvalFrameEx + 10407
21            0x4b9ab6p PyEval_EvalCodeEx + 774
22            0x4eb30fp
23            0x44a7a2p PyRun_InteractiveOneFlags + 400
24            0x44a56dp PyRun_InteractiveLoopFlags + 186
25            0x43092ep
26            0x493ae2p Py_Main + 1554
27      0x7f026bfa1830p __libc_start_main + 240
28            0x4933e9p _start + 41
为什么只有fluid import出问题呢？

**Comment by typhoonzero** [comment]
请问是从http://www.paddlepaddle.org/docs/develop/documentation/fluid/zh/build_and_install/pip_install_cn.html 下载的最新的包安装的么？

**Comment by buzzf** [comment]
是的，下载的是paddlepaddle_gpu-0.11.0-cp27-cp27mu-linux_x86_64.whl

**Comment by typhoonzero** [comment]
看上去像GPU 和CUDA环境没有正确配置，可以测试`paddle.v2.init(use_gpu=True)`应该也会报错。docker配置使用GPU可以参考：http://www.paddlepaddle.org/docs/develop/documentation/fluid/zh/build_and_install/docker_install_cn.html#dockergpu

**Comment by buzzf** [comment]
感觉不是这个原因，paddle.v2.init(use_gpu=True)可以运行，不报错，
`>>> import paddle.v2
>>> paddle.v2.init(use_gpu=True)
I0513 23:21:04.272110  9466 Util.cpp:166] commandline:  --use_gpu=True`
而且我电脑装了caffe, tensorflow,都可以运行。
所以目前情况就是我不能用paddle fluid的新功能？

**Comment by typhoonzero** [comment]
应该选择和您的系统已经安装的CUDA版本相同的whl包，您的系统是cuda 8.0, cudnn 6 应该使用cuda8.0_cudnn7_avx_mkl才可以适配。

**Comment by buzzf** [comment]
@typhoonzero 谢谢，但是cuda8.0_cudnn7_avx_mkl对应的两个链接都打不开，直接跳转404页面。

**Comment by buzzf** [comment]
解决了，不是下载版本问题，需要给sudo权限。

**Comment by typhoonzero** [comment]
明白了，感谢反馈~

**Comment by baihaojie2011** [comment]
折腾了一天，各种方法都尝试了。最后发现，更新到 0.12.0 就能 import 进来了

**Comment by zhuziying** [comment]
这个问题是怎么回事，我下载的是GPU版本的
>>> import paddle.v2 as paddle
>>> paddle.v2.init(use_gpu=True)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'module' object has no attribute 'v2'
