### ISSUE TITLE
pruning问题

### ISSUE THREAD

**Issue by hyo009** [PaddlePaddle/Paddle#10614]
模型大小为35mb，尝试设置`hk = Hook('pruning', sparsity_ratio=0.9)`，并且在输出层设置
```
output = paddle.layer.fc(input=resize_fc3,
                              size=60,
                              param_attr = ParamAttr(update_hooks=hk),
                              act=paddle.activation.Relu())
```
训练后得到的模型大小并没有减小。

**Comment by kuke** [comment]
@hyo009 这里的设置只对fc层的参数做了稀疏化，而看起来fc的size很小(=60)，所以不会对整体模型大小有太大的影响。你可以找到这个参数对应的模型文件(通常命名为__fc_x.w_x__)，看下改变```sparsity_ratio```对文件大小的影响。

**Comment by kuke** [comment]
纠正一下前一个回答，sparsity只是将某些参数置为零，并不能减小模型尺寸。

**Comment by kuke** [comment]
稀疏化只能让部分参数变为零，所以并不能减小模型的尺寸。要减小模型尺寸，可以用zip压缩模型文件，因为有更多的零值参数，稀疏化后的模型将会有更高的压缩比。
