### ISSUE TITLE
dssm模型本地训练时报错

### ISSUE THREAD

**Issue by liaibao120** [PaddlePaddle/Paddle#10617]
![image](https://user-images.githubusercontent.com/33827992/39978108-30bae216-5771-11e8-80e4-7c293db293c4.png)

**Comment by liaibao120** [comment]
paddle 版本是paddle_0.11， 模型使用的是https://github.com/PaddlePaddle/models/tree/develop/dssm

**Comment by kuke** [comment]
```
python train.py -y 0 --model_arch 0 --class_num 2
```
@liaibao120 我这边可以正常运行没有出bug，看起来你这里像是python环境的问题。有在另外的机器上运行过吗？

**Comment by liaibao120** [comment]
相同的代码，相同的运行环境，扩充了训练数据后出现的这个问题，小数据量的时候，我这也能正常训练。所以帮忙看下，报这种错误，具体是什么原因？

**Comment by kuke** [comment]
这里给的信息太少了，难以定位

**Comment by chengduoZH** [comment]
该issue长时间没有回复，暂且关闭了。如需继续讨论，请再打开。
