### ISSUE TITLE
关于ｐａｄｄｌｅ－ｍｏｂｉｌｅ使用问题

### ISSUE THREAD

**Issue by sky-2016yty** [PaddlePaddle/Paddle#10612]
了解ｐａｄｄｌｅ＿ｍｏｂｉｌｅ使用得到大佬能帮忙看看这两个问题吗？
https://github.com/PaddlePaddle/paddle-mobile/issues/153
https://github.com/PaddlePaddle/paddle-mobile/issues/154

**Comment by chengduoZH** [comment]
@sky-2016yty  关于paddle-mobile问题请到paddle-mobile的Repo下发问
