### ISSUE TITLE
PaddlePaddle安装后不能获取源码

### ISSUE THREAD

**Issue by pearlcurly** [PaddlePaddle/Paddle#10643]
Docker安装了，PaddlePaddle安装了（用的是官网教程里“国内用户加速访问的镜像源”）。但不能获取源码。Paddle book也用不了。 还请指导。谢谢
![Uploading 1.jpg…]()
![Uploading 2.jpg…]()

**Comment by pearlcurly** [comment]
![1](https://user-images.githubusercontent.com/38712162/39999086-a0a0f34c-57ba-11e8-8b1a-54b57a200493.jpg)
![2](https://user-images.githubusercontent.com/38712162/39999095-abdb17d8-57ba-11e8-89b5-57c08665827f.jpg)

**Comment by yeyupiaoling** [comment]
@pearlcurly 安装完成docker就可以使用了，不用在下载源了。可以pull镜像来运行你的paddlepaddle代码
