### ISSUE TITLE
High-level API Trainer constructor cannot be like require both trainer_program and inference_program

### ISSUE THREAD

**Issue by wangkuiyi** [PaddlePaddle/Paddle#10648]
https://github.com/PaddlePaddle/Paddle/blob/a8da5f609f5d273b0752c38ef4fa24f16f601666/python/paddle/fluid/tests/book/high-level-api/word2vec/test_word2vec_new_api.py#L113-L119

**Comment by wangkuiyi** [comment]
Another example is here

https://github.com/PaddlePaddle/Paddle/blob/b7026f79a978218c48302641d10c9d6a907592d7/python/paddle/fluid/tests/book/high-level-api/recognize_digits/test_recognize_digits_mlp.py#L48-L56

**Comment by wangkuiyi** [comment]
But, anyway, we need to make sure that Trainer takes only train_program, but only Inferencer takes infer_program.

**Comment by jacquesqiao** [comment]
Ok, I am working on updating the API.

**Comment by jacquesqiao** [comment]
fixed
