### ISSUE TITLE
对于trainer.test返回result的解释

### ISSUE THREAD

**Issue by peiss** [PaddlePaddle/Paddle#10658]
result = trainer.test(reader=paddle.batch(paddle.dataset.mnist.test(), batch_size=128))

其中result中可以访问两个值：
result.cost
result.metrics['classification_error_evaluator'])

请问这两个有什么区别？

其中classification_error_evaluator应该是指分类的错误率；
可是result.cost代表什么意思？和classification_error_evaluator看起来不一样：

Pass 18, Batch 0, Cost 0.046320, {'classification_error_evaluator': 0.01666666753590107}
...................................................................................................
Pass 18, Batch 100, Cost 0.055098, {'classification_error_evaluator': 0.01666666753590107}
...................................................................................................
Pass 18, Batch 200, Cost 0.109264, {'classification_error_evaluator': 0.05000000074505806}
...................................................................................................
Pass 18, Batch 300, Cost 0.051385, {'classification_error_evaluator': 0.01666666753590107}

麻烦帮忙解释下，或者哪里能看到文档，谢谢

**Comment by pkuyym** [comment]
是的，loss一般指你所使用的loss，比如 cross_entropy_loss等，error的话一般指分类错误率
