### ISSUE TITLE
Paddle 0.11.0 GPU（CUDA8+cudnn7）API 与 Paddle 0.11.0 CPU版本 不兼容

### ISSUE THREAD

**Issue by Yin-MrQ** [PaddlePaddle/Paddle#10654]
使用中发现 Paddle 0.11.0 GPU（CUDA8+cudnn7）版本下  batch, reader, dataset三个API 调用方法与Paddle 0.11.0 文档中的描述不符，这三个API从文档中描述的是在 paddle.v2 调用，但实际应该在paddle中，希望能提供Paddle 0.11.0 GPU（CUDA8+cudnn7）相比 Paddle 0.11.0 API变化的说明文档

**Comment by pkuyym** [comment]
@Yin-MrQ 这块文档确实过时了，dataset库位置被移动了，@shanyi15 帮忙看一下？

**Comment by shanyi15** [comment]
好的，感谢反馈

**Comment by weixing02** [comment]
@Yin-MrQ 能不能贴出具体的使用情况呢，例如paddle的版本和三个API调用时和文档不符的地方

**Comment by shanyi15** [comment]
这里可能是之前whl包的版本号给错了，现在已经修复，安装文档也进行了修改，请您看一下这里
http://www.paddlepaddle.org/docs/develop/documentation/zh/build_and_install/pip_install_cn.html
感谢反馈！
