### ISSUE TITLE
 MemoryHandle.cpp:49] Check failed: size != 0  allocate 0 bytes

### ISSUE THREAD

**Issue by chenbblei** [PaddlePaddle/Paddle#10652]
...........F0515 11:52:24.844298  6662 MemoryHandle.cpp:49] Check failed: size != 0  allocate 0 bytes
*** Check failure stack trace: ***
    @     0x7fa03572c2ed  google::LogMessage::Fail()
    @     0x7fa03572fd9c  google::LogMessage::SendToLog()
    @     0x7fa03572be13  google::LogMessage::Flush()
    @     0x7fa0357312ae  google::LogMessageFatal::~LogMessageFatal()
    @     0x7fa035553579  paddle::CpuMemoryHandle::CpuMemoryHandle()
    @     0x7fa035564f5e  paddle::CpuVectorT<>::CpuVectorT()
    @     0x7fa03556541a  paddle::VectorT<>::create()
    @     0x7fa035715145  IVector::create()
    @     0x7fa0352b6578  _wrap_IVector_create
    @     0x7fa0bff4ebad  PyEval_EvalFrameEx
    @     0x7fa0bff4fc3e  PyEval_EvalCodeEx
    @     0x7fa0bff4f1f7  PyEval_EvalFrameEx
    @     0x7fa0bff4f345  PyEval_EvalFrameEx
    @     0x7fa0bff4f345  PyEval_EvalFrameEx
    @     0x7fa0bff4fc3e  PyEval_EvalCodeEx
    @     0x7fa0bfecaa61  function_call
    @     0x7fa0bfe9ae93  PyObject_Call
    @     0x7fa0bfead64f  instancemethod_call
    @     0x7fa0bfe9ae93  PyObject_Call
    @     0x7fa0bff4d80d  PyEval_EvalFrameEx
    @     0x7fa0bff4fc3e  PyEval_EvalCodeEx
    @     0x7fa0bff4f1f7  PyEval_EvalFrameEx
    @     0x7fa0bff4fc3e  PyEval_EvalCodeEx
    @     0x7fa0bfecaa61  function_call
    @     0x7fa0bfe9ae93  PyObject_Call
    @     0x7fa0bfead64f  instancemethod_call
    @     0x7fa0bfe9ae93  PyObject_Call
    @     0x7fa0bff0b2ac  slot_tp_call
    @     0x7fa0bfe9ae93  PyObject_Call
    @     0x7fa0bff4d80d  PyEval_EvalFrameEx
    @     0x7fa0bff4fc3e  PyEval_EvalCodeEx
    @     0x7fa0bff4f1f7  PyEval_EvalFrameEx

这个错误一般是什么原因导致的？

**Comment by pkuyym** [comment]
```...........F0515 11:52:24.844298 6662 MemoryHandle.cpp:49] Check failed: size != 0 allocate 0 bytes
```
从log看，是分配内存时出了错误，是申请空内存吗？如果是的话，建议检查一下是否存在异常数据。

**Comment by chenbblei** [comment]
数据异常导致
