### ISSUE TITLE
paddle v1 api 保存的模型，无法用 paddle v2 api 加载？

### ISSUE THREAD

**Issue by youngstu** [PaddlePaddle/Paddle#10668]
paddle v1 api 保存的模型，无法用 v2 api `paddle.parameters.Parameters.from_tar(f`)加载。
paddle v2 保存的模型中比v1 api多了 *protobuf 文件。

**Comment by pkuyym** [comment]
@youngstu v2版的模型保存格式有些变化，直接加载会有问题，需要做一下转换

**Comment by youngstu** [comment]
能提供转换的脚本么？

**Comment by pkuyym** [comment]
目前paddle没有从v1到v2的转换脚步

**Comment by youngstu** [comment]
可以提供一些转换的思路？

**Comment by luotao1** [comment]
v1和v2的参数是完全一样的，至于多了的*protobuf文件，可以用v2跑一个同样的模型，只要一个batch后保存下来就行，然后对其中的参数进行替换即可。

**Comment by youngstu** [comment]
Thank you very much. That's a good idea and i will try it later.
