### ISSUE TITLE
求一个训练数据包含多slot的dataprovider例子

### ISSUE THREAD

**Issue by HugoLian** [PaddlePaddle/Paddle#1068]
我希望的训练预料来自不同文件，通过ID关联，或者拼接成一条文本也行。
每份预料对应不同的dict.txt
组成2个以上的slot。
例如：
0;0 1 4 1023;1 4 7 3;2 2 6 511;
1;2 1 5 88 511;

请问有类似的dataprovider可以作为参考么？

**Comment by luotao1** [comment]
没有现成的dataprovider，您可以自己写

**Comment by HugoLian** [comment]
@luotao1 您好，我看了一些dataprovider，输出都是yield出来的，我对PYTHON不熟，如果从2slots到3slots还可以模仿，但是从single slot到多slots，yield的数据连分号都不加，数据好像直接交还给framework来处理了，我们对framework就更不了解了，具体的多slot输出模式，好像自己琢磨有一定难度诶。。。有类似其他参考也好啊。。。

或者直接跳过数据预处理，输入就是生成好格式的文档，这样也行。。

**Comment by backyes** [comment]
@HugoLian 

建议再仔细描述下问题， 我还是没有看明白你的问题。

> 如果从2slots到3slots还可以模仿，但是从single slot到多slots，yield的数据连分号都不加，数据好像直接交还给framework来处理了，我们对framework就更不了解了，具体的多slot输出模式 

训练的dataprovider， 一般至少两个 slot（这个slot的概念，我姑且理解为一个slot 代表一个数据源）， 一般一个input 一个label 就两个slot了。 所以你说的单个slot 具体如何理解？ 

> 例如：
> 0;0 1 4 1023;1 4 7 3;2 2 6 511;
> 1;2 1 5 88 511;

这里的例子，貌似不是很直观，能稍微解释明确一点。 


@reyoung  也可以帮忙给点建议。

**Comment by luotao1** [comment]
可以参考pydataprovider2的[文档](http://www.paddlepaddle.org/doc_cn/ui/data_provider/pydataprovider2.html)

**Comment by HugoLian** [comment]
@backyes 您好。
我的意思是，我目前只有文本文件生成 lable ; slot 0 的例子。我把这个当成单slot了。
我想问问有没有dataprovider生成多个slot的例子：
lable; slot 0 {特征1} ;  slot 1 {特征1} ; 
最好slot0 slot1的特征，来自不同的文件输入，和不同的字典文件（dict.txt）
不知道有没有现成类似的例子可以参考。

**Comment by backyes** [comment]
@HugoLian 


* 在 dataprovider层面， label slot和训练样本slot （这里暂时仍然姑且叫slot， 因为paddlepaddle试图忽略这个slot的老概念）没有区别， 你可以理解label也是一个slot。 所以你再增加一个slot， 就直接添加一个即可。  

* 不同slot来自不同文件。 我理解你只需要在dataprovider实现里打开两个文件，中间按照某种策略从两个文件中产出 slot0， slot1的数据即可。 这个就是普通的python文件处理过程。 只要你dataprovider 最后返回一个迭代器，yield 一个sample即可。 

具体应该可以参考 SRL demo, 它有很多data layer声明，也就是相当于你的多个slot： 
```
https://github.com/PaddlePaddle/Paddle/blob/develop/demo/semantic_role_labeling/db_lstm.py#L9
https://github.com/PaddlePaddle/Paddle/blob/develop/demo/semantic_role_labeling/dataprovider.py#L70
```

不知道我是否解答了你的疑问。

**Comment by backyes** [comment]
@HugoLian 

另外 核心的dataprovider装饰器的实现 ：

```
https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/trainer/PyDataProvider2.py#L225

```

你可以比较清楚的看到内部是如何封装你所说的slot的。

**Comment by backyes** [comment]
@HugoLian 

*  数据格式 请参见 @luotao1  上面给你的文档链接， 相信文档应该说的很清楚。  

```
http://www.paddlepaddle.org/doc/ui/data_provider/pydataprovider2.html
写到：
	NO_SEQUENCE	SEQUENCE	SUB_SEQUENCE
dense_vector	[f, f, ...]	[[f, ...], [f, ...], ...]	[[[f, ...], ...], [[f, ...], ...],...]
sparse_binary_vector	[i, i, ...]	[[i, ...], [i, ...], ...]	[[[i, ...], ...], [[i, ...], ...],...]
sparse_vector	[(i,f), (i,f), ...]	[[(i,f), ...], [(i,f), ...], ...]	[[[(i,f), ...], ...], [[(i,f), ...], ...],...]

```
请优先按照文档来实现你的dataprovider。 

开始阶段，不建议过渡深入PyDataProvider2.py内部代码实现，请先多理解文档和demo。 比如， SparseNonValue 和 SparseValue 都是PyDataProvider2.py内部概念， 对外接口都没有这些概念。

**Comment by luotao1** [comment]
> 在yield的数据中，只要保证最后一个是lable

最后一个不用是label，根据需要自己组织

**Comment by HugoLian** [comment]
请@backyes @luotao1 @reyong 等大侠帮我看一下：
看到了一个多slots的例子：
https://github.com/PaddlePaddle/Paddle/blob/develop/demo/semantic_role_labeling/dataprovider.py#L70
在这个网络结构中：
![image](https://cloud.githubusercontent.com/assets/22980558/21680069/531dff24-d382-11e6-8775-8af1f456e64f.png)
数据层依次输入的slots顺序，和dataprovider.py yield的顺序是100%严格对应的么？
![image](https://cloud.githubusercontent.com/assets/22980558/21680094/794609bc-d382-11e6-9f60-d513e52a7523.png)
也就是说:
1) dataprovider中yield出slots的顺序，会被网络结构的输入依次读取，framemork就是同构这个位置对应的；
2) 在分类中，如果只有一个slot和一个label的文本，对应的设置为：setting.input_types, 对应多slots的文本，对应的设置为：setting.slots (我看其他demo对于yield的数据类型定义，都是input_types和slots两个)
不知道我上面的两个理解对不对啊？

**Comment by luotao1** [comment]
@HugoLian 
1. 第一点的理解是对的，但推荐使用显示调用方式，请参考[image_classification](https://github.com/PaddlePaddle/Paddle/blob/develop/demo/image_classification/image_provider.py#L53)
2. `setting.input_types`和`setting.slots`两者是一样的，都可以用。之前demo用`slots`，但`input_types`更直观，所以后来就改了。这个srl的demo没改过来。

**Comment by backyes** [comment]
@HugoLian 

comments 里可以使用markdown语法引用 shell 、python等语法片段，主要使用 
``` python
#this is python code
```
 包住程序片段即可，这样更加易读，且能被搜索引擎检索，便于后续追踪此issue，:-)

**Comment by HugoLian** [comment]
疑问基本解决，后续自己仿照尝试一下。谢谢大家！
