### ISSUE TITLE
use fluid capi build issue?

### ISSUE THREAD

**Issue by gramce** [PaddlePaddle/Paddle#10680]
The code is 

#include "paddle/fluid/framework/init.h"
#include "paddle/fluid/platform/place.h"
#include "paddle/fluid/framework/executor.h"
#include "paddle/fluid/framework/scope.h"
using namespace std;

int main()
{
    paddle::framework::InitDevices(false);
    auto place    = paddle::platform::CPUPlace();
    auto executor = paddle::framework::Executor(place);
    auto *scope   = new paddle::framework::Scope();
    return(0);
}

error is:
undefined reference to `paddle::framework::Executor::Executor(boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace> const&)'

**Comment by luotao1** [comment]
#10660 fix a similar problem (lack of boost library), maybe you can use the latest develop code.

**Comment by gramce** [comment]
[map@bjyz-map-eta-server00.bjyz.baidu.com build]$ git status
On branch develop
Your branch is up to date with 'origin/develop'.

**Comment by gramce** [comment]
And I had to add CONFIGS("third-64/boost@boost_1-57-0-200_PD_BL") in the bcloud file
otherwise

fail to analyze target: /home/map/gumeichuan_git/bc_out/baidu/eta/route-dnn/src/baidu_eta_route-dnn_route-dnn_app_main.cpp.o, error:
In file included from baidu/eta/route-dnn/paddle/paddle/fluid/platform/place.h:20:0,
                 from baidu/eta/route-dnn/src/main.cpp:4:
baidu/eta/route-dnn/paddle/paddle/fluid/platform/variant.h:28:28: fatal error: boost/config.hpp: No such file or directory
 #include "boost/config.hpp"
                            ^
compilation terminated.
:
/opt/compiler/gcc-4.8.2/bin/g++ -M baidu/eta/route-dnn/src/main.cpp -Ibaidu/eta/route-dnn -Ibaidu/eta/route-dnn/include -Ibc_out/baidu/eta/route-dnn/output/include -Ibaidu/eta/route-dnn/paddle -Ibaidu/eta/route-dnn/paddle/third_party/install/gflags/include -Ibaidu/eta/route-dnn/paddle/third_party/install/glog/include -Ibaidu/eta/route-dnn/paddle/third_party/install/protobuf/include -Ibaidu/eta/route-dnn/paddle/third_party/eigen3 -DBCLOUD -D__const__= -DNDEBUG -w -g -O2 -pipe -fPIC -std=c++11 -w

**Comment by gramce** [comment]
Which branch fix the issue？

**Comment by gongweibao** [comment]
你链接paddle的库了没有？

**Comment by gramce** [comment]
g++ -o bc_out/baidu/eta/route-dnn/output/bin/route-dnn bc_out/baidu/eta/route-dnn/src/baidu_eta_route-dnn_route-dnn_app_main.cpp.o -Xlinker -( -lpthread -lrt -lssl -lcrypto -ldl -lz **-Lbaidu/eta/route-dnn/paddle/paddle/fluid/inference -lpaddle_fluid** bc_out/third-64/boost/output/lib/libboost_atomic.a bc_out/third-64/boost/output/lib/libboost_chrono.a bc_out/third-64/boost/output/lib/libboost_container.a bc_out/third-64/boost/output/lib/libboost_context.a bc_out/third-64/boost/output/lib/libboost_coroutine.a bc_out/third-64/boost/output/lib/libboost_date_time.a bc_out/third-64/boost/output/lib/libboost_exception.a bc_out/third-64/boost/output/lib/libboost_filesystem.a bc_out/third-64/boost/output/lib/libboost_graph.a bc_out/third-64/boost/output/lib/libboost_locale.a bc_out/third-64/boost/output/lib/libboost_log_setup.a bc_out/third-64/boost/output/lib/libboost_math_c99.a bc_out/third-64/boost/output/lib/libboost_math_c99f.a bc_out/third-64/boost/output/lib/libboost_math_c99l.a bc_out/third-64/boost/output/lib/libboost_math_tr1.a bc_out/third-64/boost/output/lib/libboost_math_tr1f.a bc_out/third-64/boost/output/lib/libboost_math_tr1l.a bc_out/third-64/boost/output/lib/libboost_prg_exec_monitor.a bc_out/third-64/boost/output/lib/libboost_program_options.a bc_out/third-64/boost/output/lib/libboost_python.a bc_out/third-64/boost/output/lib/libboost_random.a bc_out/third-64/boost/output/lib/libboost_regex.a bc_out/third-64/boost/output/lib/libboost_serialization.a bc_out/third-64/boost/output/lib/libboost_signals.a bc_out/third-64/boost/output/lib/libboost_system.a bc_out/third-64/boost/output/lib/libboost_test_exec_monitor.a bc_out/third-64/boost/output/lib/libboost_thread.a bc_out/third-64/boost/output/lib/libboost_timer.a bc_out/third-64/boost/output/lib/libboost_unit_test_framework.a bc_out/third-64/boost/output/lib/libboost_wave.a bc_out/third-64/boost/output/lib/libboost_wserialization.a -Xlinker -)

**Comment by gramce** [comment]
链了

**Comment by gramce** [comment]
改用了你们的boost 可以了
