### ISSUE TITLE
Create class GeneralJpegDataProvider failed. 

### ISSUE THREAD

**Issue by yinyunfeng** [PaddlePaddle/Paddle#1072]
I0105 15:17:43.766901 20562 PythonUtil.cpp:83] Python Error: : 
I0105 15:17:43.766921 20562 PythonUtil.cpp:87] Python Callstack: 
I0105 15:17:43.766930 20562 PythonUtil.cpp:92] /home/slurm/job/tmp/job-4574/thirdparty/thirdparty/pyDataProviderImage.py : 132 
F0105 15:17:43.766948 20562 PythonUtil.cpp:108] Create class GeneralJpegDataProvider failed. 

http://yq01-sys-hic-k4004.yq01.baidu.com:8880/look/overview/file?id=4574&file=/job-4574/thirdparty/thirdparty/pyDataProviderImage.py&offset=0

使用的数据是单通道，32*32的图像，pyDataProviderImage.py配置有问题，导致报上面的错，想问一下这个文件里面的参数该怎么配

之前我是32*32、三通道的图像，18类，配置如下，可以跑通
self.mean_file['header'] = dict()
self.mean_file['header']['num_slots'] = 2
self.mean_file['header']['use_sequence_flag'] = 0
self.mean_file['header']['slots'] = [[3, 18], [0, 3072]]

self.total_pixels = 3 * self.inner_pixels

现在是改用单通道的图像训练，上面这五行改怎么改呀，可不可以直接告诉我，
 [[3, 18], [0, 3072]]这里面的3是三通道吗

**Comment by backyes** [comment]
请 @qingqing01 帮忙看看问题。

**Comment by qingqing01** [comment]
> self.mean_file['header']['slots'] = [[3, 18], [0, 3072]]

[3, 18] : 代表第一个slot的信息， 3是： 整数类型， 18是大小，即18类别。
[0, 3072]: 代表第二个slot的信息，0代表：稠密类型， 3072 = 3 * 32 * 32，即数据大小，如果是单通道，改变相应的size，填充即可。

另外，你使用的还是旧的PyDataProvider， 非常你推荐是使用PyDataProvider2， 参考image classification或者mnist这两demo。

**Comment by yinyunfeng** [comment]
self.mean = self.mean_file['data_mean'].reshape(3, self.image_size, self.image_size)[ :, (self.image_size-self.inner_size)/2:((self.image_size-self.inner_size)/2 + self.inner_size) , (self.image_size-self.inner_size)/2:((self.image_size-self.inner_size)/2+self.inner_size)].reshape(1,-1)[0]
那我这一行是不是得改成
self.mean = self.mean_file['data_mean'].reshape(1, self.image_size, self.image_size)[ :, (self.image_size-self.inner_size)/2:((self.image_size-self.inner_size)/2 + self.inner_size) , (self.image_size-self.inner_size)/2:((self.image_size-self.inner_size)/2+self.inner_size)].reshape(1,-1)[0]

**Comment by qingqing01** [comment]
@yinyunfeng  是的~

**Comment by yinyunfeng** [comment]
thanks @qingqing01
