### ISSUE TITLE
单机任务失败，paddle_local: line 109: 20695 Segmentation fault 

### ISSUE THREAD

**Issue by pkuyym** [PaddlePaddle/Paddle#1073]
paddle_local: line 109: 20695 Segmentation fault  ${DEBUGGER} $MYDIR/../opt/paddle/bin/paddle_trainer ${@:2}
请问调试思路？

**Comment by luotao1** [comment]
请贴出完整错误信息

**Comment by pkuyym** [comment]
@luotao1 
这个已经是完整的错误信息了

**Comment by luotao1** [comment]
那你是在集群上跑，还是本地跑，跑什么任务等，都得说一下。`paddle_local:`是什么？本地么

**Comment by luotao1** [comment]
如果生成了core的话，用gdb调试。

**Comment by backyes** [comment]
@pkuyym 

建议从demo开始， 熟悉了系统，你才能更好的找到定位的方法，另外这种异常也没有固定的定位方法， 尤其你根本没有贴出什么具体异常。

**Comment by pkuyym** [comment]
@luotao1  单机跑，GPU任务，paddle_local是本地版本，没有出现详细错误信息，没有core文件，编译工具是一键编译，参数为gpu nonrdma

**Comment by backyes** [comment]
@pkuyym 

请问根据文档，是否能将单机demo跑通？ 建议先卸载老旧的paddle，然后根据最新文档安装单机版paddle，熟悉demo，然后再考虑复杂场景下的异常定位技巧, :-)。

**Comment by hedaoyuan** [comment]
@pkuyym 是自己通过源码编译的paddle程序吗？去掉`paddle/cuda/src/hl_dso_loader.cc`文件中`GetDsoHandleFromDefaultPath`函数里面的VLOG(3)相关代码再编译试试。
@gangliao follow一下这个问题看看，看起来也是像是initMain之前就挂了。

**Comment by pkuyym** [comment]
@hedaoyuan 是的，我是自己编译的paddle，会按照你的建议重新编译下看看，感谢

**Comment by Yancey1989** [comment]
Close the inactive issue.
