### ISSUE TITLE
怎样在pass结束后得到训练集的总错误率

### ISSUE THREAD

**Issue by peiss** [PaddlePaddle/Paddle#10742]
为了绘制出（测试集错误率，训练集错误率）的共同权限，需要在每轮Pass结束后，记录两者的错误率

请问我的代码是否合适：
```python
        if isinstance(event, paddle.event.EndPass):
            with open('./params_pass_%d.tar' % event.pass_id, 'w') as f:
                trainer.save_parameter_to_tar(f)

            result_test = trainer.test(
                reader=paddle.batch(
                    paddle.reader.shuffle(pss_reader_paddle_sequence.test_reader, buf_size=50000),
                    batch_size=120),
                feeding=feeding)
            print "\nTest with Pass %d, %s" % (event.pass_id, result_test.metrics["classification_error_evaluator"])

            result_train = trainer.test(
                reader=paddle.batch(
                    paddle.reader.shuffle(pss_reader_paddle_sequence.train_reader, buf_size=50000),
                    batch_size=120),
                feeding=feeding)
            print "\nTrain with Pass %d, %s" % (event.pass_id, result_train.metrics["classification_error_evaluator"])
```

谢谢

**Comment by guoshengCS** [comment]
训练集错误率无需另行运行test，可以参考这里 https://github.com/PaddlePaddle/models/blob/develop/text_classification/train.py#L125

**Comment by peiss** [comment]
if isinstance(event, paddle.event.EndIteration):
            if event.batch_id % 100 == 0:
                logger.info("Pass %d, Batch %d, Cost %f, %s\n" % (
                    event.pass_id, event.batch_id, event.cost, event.metrics))

你好，我找到了这一段，这看起来是训练集的错误率；

可是这个是每100个batch的错误率，并不能代表整个训练集的错误率吧？

**Comment by guoshengCS** [comment]
可以自行记录下来进行聚合

**Comment by peiss** [comment]
比如打印结果如下：
Pass 0, Batch 0, Cost 1.820907, {'classification_error_evaluator': 0.8700000047683716}
...................................................................................................
Pass 0, Batch 100, Cost 0.478058, {'classification_error_evaluator': 0.1899999976158142}
...................................................................................................
Pass 0, Batch 200, Cost 0.628427, {'classification_error_evaluator': 0.20000000298023224}
...................................................................................................
Pass 0, Batch 300, Cost 0.308915, {'classification_error_evaluator': 0.14000000059604645}
...................................................................................................
Pass 0, Batch 400, Cost 0.271420, {'classification_error_evaluator': 0.14000000059604645}
.......................................................
Test with Pass 0, 0.154414698482

我可以把前面的训练集的错误率取平均对吗

**Comment by guoshengCS** [comment]
一般情况下是可以的，如果这个错误率是以样本来计的话

**Comment by yeyupiaoling** [comment]
@peiss 那个打印是每一batch的训练集错误，我们主要是观察Test的错误率。

**Comment by peiss** [comment]
@yeyupiaoling 我的目的是画出训练集错误和测试集错误曲线，只有测试集数据不行呀

**Comment by yeyupiaoling** [comment]
@peiss 可以参考这个：http://paddlepaddle.org/docs/develop/book/03.image_classification/index.cn.html#permalink-11--
这里可以画出训练和测试的曲线
