### ISSUE TITLE
Do we need to release binaries for each cuda version or document about it?

### ISSUE THREAD

**Issue by typhoonzero** [PaddlePaddle/Paddle#10753]
As mentioned in https://github.com/PaddlePaddle/Paddle/issues/10062#issuecomment-389845257, when we do `pip install paddlepaddle-gpu==0.11.0` the installed package actually only support cuda 7.5 and cudnn 5, which users may not be aware of.

* one possible way is to build several `whl` like `paddlepaddle-gpu-cuda8-cudnn5` and `paddlepaddle-gpu-cuda9-cudnn7`, so that user can choose versions to satisfy their own environment. 
* the other way is to document about what cuda and cudnn version we are using in the `paddlepaddle-gpu`

![image](https://user-images.githubusercontent.com/6836917/40179432-e3c39f22-5a16-11e8-86ac-ea1e78c4a791.png)
If you prefer the first one, please click "UP"; and the second one, please click "smile".

**Comment by panyx0718** [comment]
It seems tensorflow has similar issues:
https://stackoverflow.com/questions/48575900/how-to-install-tensorflow-gpu-with-cuda8-0

**Comment by typhoonzero** [comment]
Seems tensorflow is released based on the latest version of cuda, so it have a version maching like:

* tf 1.4 -- cuda 8
* tf 1.5 -- cuda 9

etc.

**Comment by luotao1** [comment]
I prefer the first one, there are two reasons:
- update cuda version is not an easy job for most users, if they can update paddle version without updating cuda version, they would be more relaxed.
- there are a lot of machine environment in the company, if we can provide different `whl`, they would be more willing to update the paddle version.

**Comment by dzhwinter** [comment]
vote for the first one.

**Comment by wangkuiyi** [comment]
I am afraid that to make sure that a version of PaddlePaddle works several different versions of CUDA and CUDNN would bring too much burden to our CI system.

I would propose that we follow the [TensorFlow way](https://github.com/PaddlePaddle/Paddle/issues/10753#issuecomment-389880900).

**Comment by luotao1** [comment]
> different versions of CUDA and CUDNN would bring too much burden to our CI system

@wangkuiyi Now, our CI system build each one version only once a day, and the building is in the night, so there is not much burden to our daily CI system.

**Comment by ggaaooppeenngg** [comment]
人家还维护了 mac 和 win 的，我觉得 ci 系统要面对的压力是必须面对的，他们定的版本，但是不会这样 break change，所以 1.6 装不上可以装 1.4，1.4 装不上可以装 1.2 总有办法。

**Comment by typhoonzero** [comment]
I've pushed several recent released whl packages to pypi as suggested by @wangkuiyi 

https://pypi.org/project/paddlepaddle-gpu/#history

See https://www.python.org/dev/peps/pep-0440/#post-releases for pypi post-release version.

* v0.12.0 default gpu whl package is built with CUDA 8.0 cuDNN 5
* v0.11.0.post8 is built with CUDA 8.0 cuDNN 5
* v0.11.0.post87 is built with CUDA 8.0 cuDNN 7
* v0.11.0 is built with CUDA 7.5 cuDNN 5

Closing for now.

**Comment by panyx0718** [comment]
@shanyi15 Can we upload the new pip package to http://paddlepaddle.org/docs/develop/documentation/fluid/en/build_and_install/pip_install_en.html and update the page?

**Comment by shanyi15** [comment]
Sure, no problem

**Comment by shanyi15** [comment]
@panyx0718  Done
![image](https://user-images.githubusercontent.com/35982308/40340516-d63c8a78-5db1-11e8-93c5-7affc10fb17b.png)

**Comment by panyx0718** [comment]
thanks!
