### ISSUE TITLE
[Simplified API] When accuracy reaches a threshold, user should be able to terminate the training process

### ISSUE THREAD

**Issue by daming-lu** [PaddlePaddle/Paddle#10754]
Right now in the `event_handler`, even `accuracy` reaches a certain threshold, or` loss` drops under a threshold, the training process still keeps running. Is there a way to let the user terminate training process earlier? 

https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/fluid/tests/book/high-level-api/fit_a_line/test_fit_a_line.py#L72-L75

**Comment by daming-lu** [comment]
I wonder if we can add a returned signal [here](https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/fluid/trainer.py#L302) from event_handler so that it can tell trainer to stop.

**Comment by jacquesqiao** [comment]
yes, I think Trainer can have an interface `Trainer.stop()`, and in event_handle we can use it to stop the training process.
