### ISSUE TITLE
Problem about `use_mkldnn` flag

### ISSUE THREAD

**Issue by luotao1** [PaddlePaddle/Paddle#10765]
This issue is from Intel sides.

The problem we have with `use_mkldnn` flag is that we need to modify all models to enable newly integrated MKL-DNN ops. It would be great, if we can only add an integration and in case when Fluid is run with use mkldnn parameter, all available Ops are used without modification of model scripts, to pass the option.

**Comment by Superjomn** [comment]
I think that makes sense.

**Comment by luotao1** [comment]
How about using `MKLDNNPlace()` to call all available OPs?
```
place=fluid.MKLDNNPlace()
```

**Comment by kbinias** [comment]
It would be great to have global use_mkldnn flag. Now it is very difficult to fallback this flag to some ops, e.g.: elementwise_add, because the python code is auto generate with generate_layer_fn(_OP). Also it would be nice to have another flag not_use_mkldnn on layer level, to switch off MKL-DNN from some layers/ops.

**Comment by mozga-intel** [comment]
Thank you for this issue. 

I will use the sum operator as an example to describe this problem. So, during the implementation this operator I have encountered a few difficulties. The current version of the sum operator of MKLDNN algorithm is using inside other operators. Therefore the use_mkldnn can not be uses in this way. I mean that I have to hardcode this flag in this place . For instance:
[Backward.py](https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/fluid/backward.py#L159)

To this end I agree with @kbinias.

**Comment by Superjomn** [comment]
> it would be nice to have another flag not_use_mkldnn on layer level, to switch off MKL-DNN from some layers/ops.

That makes sense, the user can 

- globally set a default config, ON or OFF
- set MKLDNN config separately for specific operator

For example, such use case (the name of APIs is not important)

```python
set_default_use_mkldnn(True)

v1 = op0(v0) # use mkldnn by default if supported
# ...
v2 = op1(v1, use_mkldnn=False) # turn off MKLDNN for this operator
# ...
```

The above function is better.

**Comment by luotao1** [comment]
We will have a discussion about how to add this global flag function in our framework ASAP.

**Comment by mrysztow** [comment]
@luotao1 Any ETA for this?

**Comment by luotao1** [comment]
@mrysztow Discussed with @Superjomn and @tensor-tang, the newest design is:
- use an environment variable `export FLAGS_use_mkldnn=True` to control it. 
- add `EnableMKLDNN` function (maybe rename it) in `paddle/fluid/platform/mkldnn_helper.h`
https://github.com/PaddlePaddle/Paddle/blob/406c1dd143a66b29e6f40675d0a207648b260e6c/paddle/fluid/inference/tests/test_helper.h#L136-L146
- call `EanbleMKLDNN` function in Executer:Run (`paddle/fluid/framework/executer.cc`) to transpiler the program.

We will finish it ASAP before next meeting.

**Comment by tpatejko** [comment]
@luotao1 What's the reason for using an environment variable? Does it mean that some parameters will be passed as script's arguments and some of them will be passed as environment variables?

**Comment by mrysztow** [comment]
@Superjomn I think it is a good idea, as now we need to change all model scripts to add this option. But will it be consistent with focing usage of other backends, like gpu?

**Comment by luotao1** [comment]
@mrysztow You can use `FLAGS_use_mkldnn=true` to control it now, see #11319 for details.

**Comment by tpatejko** [comment]
@Superjomn My main concern was some sort of consistency and intuition behind passing parameters to the models scripts. I mean, a user will have to set an environment variable if they want to run something on CPU with MKLDNN, which is different from running something on GPU, that requires passing an argument to a model script.

However, it's true what you're saying, this approach is more flexible, as it doesn't require changing scripts with models.

**Comment by Superjomn** [comment]
Yeah, I understand your concern. 

> the MKLDNN might be the first one that has a global switch in runtime.

The environment variable is a low-level API and easy to hide in many ways. 

We can concentrate on the implementation of MKLDNN functions first, and have another discussion about this API after MKLDNN functions are ready and release to users.
