### ISSUE TITLE
resnet 测试输出不一致

### ISSUE THREAD

**Issue by VamWolf** [PaddlePaddle/Paddle#1076]
下载model，跑完predict.sh  ,
[INFO 2017-01-05 17:13:02,893 classify.py:172] Label of example/dog.jpg is: 879
[INFO 2017-01-05 17:13:08,523 classify.py:172] Label of example/cat.jpg is: 879
和官网结果不一致。
http://www.paddlepaddle.org/doc/demo/imagenet_model/resnet_model.html

有一点改动是把use_gpu 改成0 了.  是这个的影响？

**Comment by qingqing01** [comment]
请注意文档里有处Note提示了暂不支持CPU。 目前Release的版本[v0.9.0]( https://github.com/PaddlePaddle/Paddle/releases/tag/v0.9.0)，这个模型还不支持CPU， 但develop分支已支持。 不知道您安装版本是多少？可以更新到develop分支。

**Comment by Yancey1989** [comment]
Close the inactive issue.
