### ISSUE TITLE
 Check failed: newNnz <= newHeight * newWidth (1457 vs. 0) 

### ISSUE THREAD

**Issue by sdwhwxt** [PaddlePaddle/Paddle#1077]
在预测的时候出现：
F0105 18:35:11.668208 27756 CpuSparseMatrix.cpp:59] Check failed: newNnz <= newHeight * newWidth (1457 vs. 0)

**Comment by backyes** [comment]
@sdwhwxt 

请给出复现方法。

**Comment by backyes** [comment]
@sdwhwxt 

请使用 ```paddle github issue newnnz``` 关键词在google里检索下github issue， 有很多类似解答。 如果仍然不能解决你的问题， 请继续反馈。

**Comment by sdwhwxt** [comment]
已解决，
解决方法： 使用paddle提供的python。
