### ISSUE TITLE
新接口对SequenceReshapeLayer的支持

### ISSUE THREAD

**Issue by hiahiahu** [PaddlePaddle/Paddle#1078]
```http://www.paddlepaddle.org/doc/ui/api/trainer_config_helpers/layers.html```
文档中没有找到关于SequenceReshapeLayer 的支持？辛苦！

**Comment by backyes** [comment]
@hiahiahu 

新接口确实没有这个layer实现。请在配置文件里，导入 ```import paddle.trainer.config_parser ``` 暂时使用老接口吧。 

@reyoung  知晓

**Comment by luotao1** [comment]
之前由于这个layer用的人非常少，所以就暂时没有在新接口中加入了。会尽快补上的。

**Comment by luotao1** [comment]
@hiahiahu 已经在helpers中添加了[seq_reshape_layer](https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/trainer_config_helpers/layers.py#L1459)的接口。用法：
```
reshape = seq_reshape_layer(input=layer, reshape_size=4)
```
