### ISSUE TITLE
paddlepaddle v0.12.0 image

### ISSUE THREAD

**Issue by blueskyll** [PaddlePaddle/Paddle#10798]
Do we have docker image based on paddlepaddle v0.12.0? Can't find in docker hub. Or where can I get a template to build the docker image?

**Comment by jacquesqiao** [comment]
Can follow this comment to build a Docker container with the v0.12.0 branch. http://www.paddlepaddle.org/docs/develop/documentation/fluid/zh/build_and_install/build_from_source_cn.html

**Comment by blueskyll** [comment]
我看这个是编译PaddlePaddle的方法？怎么做一个0.12.0的镜像呢？
