### ISSUE TITLE
Should not write file to CMAKE_INSTALL_PREFIX when configuration

### ISSUE THREAD

**Issue by reyoung** [PaddlePaddle/Paddle#10823]
https://github.com/PaddlePaddle/Paddle/blob/d54ad9f1a49fe81d226dc5459ab4e67dbdd06d38/cmake/inference_lib.cmake#L176-L185

This line will write files to CMAKE_INSTALL_PREFIX, which is not the good way to install file. Use `install` command of `cmake`.

This lines will make Paddle failed to compile when the user has no write permission to CMAKE_INSTALL_PREFIX.

**Comment by luotao1** [comment]
Discussed with @reyoung, `CMAKE_INSTALL_PREFIX ` will be changed to `FLUID_INSTALL_DIR`, and the default path of `FLUID_INSTALL_DIR` is `${CMAKE_BINARY_DIR}/fluid_install_dir`.
