### ISSUE TITLE
部分文档链接出错

### ISSUE THREAD

**Issue by BryceLuminary** [PaddlePaddle/Paddle#10820]
http://www.paddlepaddle.org/docs/0.9.0/documentation/doc/build/build_from_source.html#build-and-install
没有内容了

**Comment by velconia** [comment]
请问这个链接是从哪个页面链接进去的

**Comment by shanyi15** [comment]
请您看一下这篇是不是您需要的
http://www.paddlepaddle.org/docs/0.9.0/documentation/zh/build_and_install/cmake/compile_options.html
