### ISSUE TITLE
多个program预测时模型加载问题

### ISSUE THREAD

**Issue by dyning** [PaddlePaddle/Paddle#10824]
在一个Executor中，多个program的网络结构相同，只有权重不同，模型依次加载会出错。

**Comment by dyning** [comment]
startup_program = fluid.Program()
        self.rpn_program = fluid.Program()
        self.frcnn_program = fluid.Program()
        place = fluid.CUDAPlace(0)
        self.exe = fluid.Executor(place)
        self.exe.run(startup_program)

        self.rpn_scope = fluid.core.Scope()
        with fluid.scope_guard(self.rpn_scope):
            with fluid.program_guard(self.rpn_program, startup_program):
                data = fluid.layers.data(name='data', shape=[3, self.size_rpn, self.size_rpn], dtype='float32')
                rois = fluid.layers.data(name='rois', shape=[4], dtype='int64', lod_level=1)    
                fc_cls, fc_loc = gen_fast_rcnn_net(data, rois, 2, True)
                self.rpn_model_path = "./models/trained_ok_models/det_voc/1S1/49/"
                fluid.io.load_persistables(self.exe, self.rpn_model_path, main_program=self.rpn_program)

        self.frcnn_fetch_list = []
        self.frcnn_scope = fluid.core.Scope()
        with fluid.scope_guard(self.frcnn_scope):
            with fluid.program_guard(self.frcnn_program, startup_program):
                data = fluid.layers.data(name='data', shape=[3, self.size_rpn, self.size_rpn], dtype='float32')
                rois = fluid.layers.data(name='rois', shape=[4], dtype='int64', lod_level=1)    
                fc_cls, fc_loc = gen_fast_rcnn_net(data, rois, 21, False)
                self.frcnn_model_path = "./models/trained_ok_models/det_voc/2S1/33/"
                fluid.io.load_persistables(self.exe, self.frcnn_model_path, main_program=self.frcnn_program)

**Comment by jacquesqiao** [comment]
这个问题有两个原因：
1，没有使用unique_name_guard，导致在创建第二个program的时候，var的name是接着之前的名字创建的，就和参数名字对不上了。
2. program_guard里面，startup_program还是用的同一个。

需要补充相关文档： https://github.com/PaddlePaddle/paddle/issues

**Comment by dyning** [comment]
初始化简单示例：
    def __init__(self):
        """__init__"""
        startup_program1 = fluid.Program()
        startup_program2 = fluid.Program()
        self.rpn_program = fluid.Program()
        self.frcnn_program = fluid.Program()
        model_path_dict = {"rpn":"./models/trained_ok_models/det_voc/1S1/49/"\
            , "frcnn":"./models/trained_ok_models/det_voc/2S1/33/"}
        self.size_rpn = 500
        self.mean_value = 148
        self.cand_rois_list = self.get_cand_rois_list()
        #place = fluid.CPUPlace()
        place = fluid.CUDAPlace(0)
        self.exe = fluid.Executor(place)

        self.rpn_fetch_list = []
        self.rpn_scope = fluid.core.Scope()
        with fluid.scope_guard(self.rpn_scope):
            with fluid.unique_name.guard():
                with fluid.program_guard(self.rpn_program, startup_program1):
                    data = fluid.layers.data(name='data', shape=[3, self.size_rpn, self.size_rpn], dtype='float32')
                    rois = fluid.layers.data(name='rois', shape=[4], dtype='int64', lod_level=1)    
                    fc_cls, fc_loc = gen_fast_rcnn_net(data, rois, 2, True)
                    self.rpn_fetch_list.append(fc_cls.name)
                    self.rpn_fetch_list.append(fc_loc.name)
                    self.rpn_feeder = fluid.DataFeeder(place=place, feed_list=[data, rois])
                    self.rpn_model_path = model_path_dict['rpn']
                    fluid.io.load_persistables(self.exe, self.rpn_model_path, main_program=self.rpn_program)

        self.frcnn_fetch_list = []
        self.frcnn_scope = fluid.core.Scope()
        with fluid.scope_guard(self.frcnn_scope):
            with fluid.unique_name.guard():
                with fluid.program_guard(self.frcnn_program, startup_program2):
                    data = fluid.layers.data(name='data', shape=[3, self.size_rpn, self.size_rpn], dtype='float32')
                    rois = fluid.layers.data(name='rois', shape=[4], dtype='int64', lod_level=1)    
                    fc_cls, fc_loc = gen_fast_rcnn_net(data, rois, 21, False)
                    self.frcnn_fetch_list.append(fc_cls.name)
                    self.frcnn_fetch_list.append(fc_loc.name)
                    self.frcnn_feeder = fluid.DataFeeder(place=place, feed_list=[data, rois])
                    self.frcnn_model_path = model_path_dict['frcnn']
                    fluid.io.load_persistables(self.exe, self.frcnn_model_path, main_program=self.frcnn_program)
