### ISSUE TITLE
Refactor the generation process of _swig_paddle.so

### ISSUE THREAD

**Issue by gangliao** [PaddlePaddle/Paddle#1083]
来源：https://cmake.org/cmake/help/v3.2/module/UseSWIG.html

当前Paddle与swig的编译过程时写在[paddle/api/paddle_ld_flags.py](https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/api/paddle_ld_flags.py), [setup.py.in](https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/setup.py.in) 和 [paddle/api/paddle_api_config.py.in](https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/api/paddle_api_config.py.in)里面，跨平台效果并不好，非常不方便进行维护。

具体做法：去掉paddle_api_config.py.in和paddle_ld_flags.py, 简化setup.py。

简单的说，完成这个过程我们只需要在CMake里面调两个函数就行了：
```cmake
SWIG_ADD_MODULE(example python example.i example.cxx)
SWIG_LINK_LIBRARIES(example ${PYTHON_LIBRARIES})
```

官方的说法：

```
CMake knows how to build shared libraries and loadable modules on many different operating systems. This allows easy cross platform SWIG development. It also can generate the custom commands necessary for driving SWIG from IDE's and makefiles. All of this can be done from a single cross platform input file. 
```

```cmake
# This is a CMake example for Python
FIND_PACKAGE(SWIG REQUIRED)
INCLUDE(${SWIG_USE_FILE})

FIND_PACKAGE(PythonLibs)
INCLUDE_DIRECTORIES(${PYTHON_INCLUDE_PATH})

INCLUDE_DIRECTORIES(${CMAKE_CURRENT_SOURCE_DIR})

SET(CMAKE_SWIG_FLAGS "")

SET_SOURCE_FILES_PROPERTIES(example.i PROPERTIES CPLUSPLUS ON)
SET_SOURCE_FILES_PROPERTIES(example.i PROPERTIES SWIG_FLAGS "-includeall")
SWIG_ADD_MODULE(example python example.i example.cxx)
SWIG_LINK_LIBRARIES(example ${PYTHON_LIBRARIES})
```

The above example will generate native build files such as makefiles, nmake files and Visual Studio projects which will invoke SWIG and compile the generated C++ files into _example.so (UNIX) or _example.pyd (Windows). For other target languages on Windows a dll, instead of a .pyd file, is usually generated.

**Comment by backyes** [comment]
@gangliao 

貌似应该也能解决 https://github.com/PaddlePaddle/Paddle/issues/883 问题吧。

**Comment by backyes** [comment]
https://github.com/PaddlePaddle/Paddle/issues/1083

**Comment by reyoung** [comment]
@gangliao 问题不在于build出来那个so，而在于打包成wheel包。

我之前看wheel包似乎只能通过setup.py打包。不太清楚怎么把已经编译好的shared library加到setup.py里面。

**Comment by gangliao** [comment]
@backyes #1017 这个merge之后，就没有问题了。https://github.com/PaddlePaddle/Paddle/pull/1017/files#diff-21ac5135e25d5aca9c7bcb46e118118dR158

**Comment by gangliao** [comment]
@reyoung 

```python
setup(
...
package_data=[`_swig_paddle.so`]
)
```

**Comment by gangliao** [comment]
we already merge this feature into PaddlePaddle. So I closed this PR.
