### ISSUE TITLE
机器翻译示例中，我只想输出beam_search中最佳结果对应的gru_decoder_with_attention的out结果，该怎么获取

### ISSUE THREAD

**Issue by chenbblei** [PaddlePaddle/Paddle#10869]
链接如下：
https://github.com/PaddlePaddle/book/blob/develop/08.machine_translation/train.py
在生成过程中，我不想直接通过beam_search来获取最终的标签id，而是想要的是beam_search得到的最终最佳标签id所对应的gru_decoder_with_attention的输出结果，该如何修改才能获取到

**Comment by kuke** [comment]
@chenbblei out的结果不是很方便拿到，gru_decoder_with_attention是在beam search内部调用的，如果要取其输出，得hack代码

**Comment by chenbblei** [comment]
@kuke paddle能否开发这样的一个接口或者参数来呢

**Comment by chenbblei** [comment]
这个问题希望paddle同事来开发吧，先关闭了，当前没解决方案
