### ISSUE TITLE
Paddle import dump_v2_config报告找不到dump_v2_config错误

### ISSUE THREAD

**Issue by Angus07** [PaddlePaddle/Paddle#10879]
http://staging.paddlepaddle.org/docs/0.12.0/documentation/zh/howto/capi/workflow_of_capi_cn.html 
这里两个代码示例均跑不通，
from paddle.utils.dump_v2_config import dump_v2_config
from mnist_v2 import network

predict = network(is_infer=True)
dump_v2_config(predict, "trainer_config.bin", True)

这个代码提示找不到dump_v2_config
后来我问了同组之前用过的同学，他也遇到过这个坑，才知道他是通过paddle客服人员传输给他的脚本才解决问题。这已经是好几个月之前的事了。同一个坑，让后面的同学不停地踩，我想问一句这是"简单可依赖"吗？
放着一个跑不通的教程，就这么放在页面上，是简单可依赖吗？！第二个段代码更是有低级错误，连拼写都错了。就是不愿意改一改，还堂而皇之地放在那。丢不丢人

**Comment by pkuyym** [comment]
@Angus07 感谢反馈，就这个问题来看，比较怀疑是安装不太正确，paddle的cmake提供了一些可配选项，请确保打开WITH_PYTHON，关闭WITH_FLUID_ONLY。如果您能提供更多的错误信息，可以更好的帮助我们定位问题。谢谢！

**Comment by panyx0718** [comment]
![image](https://user-images.githubusercontent.com/2887803/40427714-1059b544-5ed1-11e8-8753-d2fd53086bd4.png)

**Comment by panyx0718** [comment]
mnist_v2似乎也是可以跑的。
![image](https://user-images.githubusercontent.com/2887803/40427787-42518856-5ed1-11e8-9094-c6383eb32cf1.png)

**Comment by panyx0718** [comment]
bin也生成了
![image](https://user-images.githubusercontent.com/2887803/40427824-5f1adc44-5ed1-11e8-9e95-c6bc568c0e20.png)

**Comment by panyx0718** [comment]
如果信息给得更具体一些，我们可以排查。比如是不是安装包或者编译选项的问题

**Comment by panyx0718** [comment]
![image](https://user-images.githubusercontent.com/2887803/40429471-5b05d204-5ed5-11e8-8447-2df057d27ac4.png)
这个已经安排了修复，多谢汇报
