### ISSUE TITLE
PaddlePaddle 使用高版本 gcc 编译失败的问题

### ISSUE THREAD

**Issue by BryceLuminary** [PaddlePaddle/Paddle#10882]
$ gcc -v
Using built-in specs.
Thread model: posix
gcc version 8.0.1 20180124 (experimental) (GCC)

错误提示：
paddle/fluid/string/tinyformat/tinyformat.h:673:15: error: this statement may fall through [-Werror=implicit-fallthrough=]
       out.setf(std::ios::uppercase);
       ~~~~~~~~^~~~~~~~~~~~~~~~~~~~~

**Comment by Superjomn** [comment]
gcc 8.没有测试过,不能保证不出问题

**Comment by Yancey1989** [comment]
因为这个issue很久没有更新，先关闭它了，如依然有问题请随时打开它，多谢！

**Comment by wanghaoshuang** [comment]
https://stackoverflow.com/questions/55693007/error-this-statement-may-fall-through-werror-implicit-fallthrough

这个问题可能需要修复一下。
