### ISSUE TITLE
训练任务一直挂，换了很多次port也没用，有10个节点可以跑起来的，其他的paddle任务没有大问题，重启几次就好了

### ISSUE THREAD

**Issue by xslguang** [PaddlePaddle/Paddle#10883]
失败任务链接，http://nmg01-hpc-off-mon.dmop.baidu.com:8090/job/i-696659/
10节点任务链接(训练中)，http://nmg01-hpc-off-mon.dmop.baidu.com:8090/job/i-696537/
50节点任务链接(agent lost)，http://nmg01-hpc-off-mon.dmop.baidu.com:8090/job/i-695735/
![pad](https://user-images.githubusercontent.com/22540595/40427183-909f4900-5ecf-11e8-9d5a-616be369e610.png)

**Comment by Yancey1989** [comment]
Hi @xslguang 可以内部联系Inf同学排查下Agent lost的原因。
