### ISSUE TITLE
mnist模型每轮最后一个batch的 cost 增大数十倍

### ISSUE THREAD

**Issue by guochaorong** [PaddlePaddle/Paddle#10897]
CE job地址：
http://18.222.34.7:8080/viewLog.html?tab=buildLog&buildTypeId=Paddle_ContinuousEvaluation&buildId=446

![错误信息](https://user-images.githubusercontent.com/32069604/40460611-304e9c66-5f3a-11e8-8512-4f59d8801675.JPG)

模型代码：
https://github.com/Superjomn/paddle-ce-latest-kpis/blob/master/mnist/model.py

**Comment by dzhwinter** [comment]
It is normal. Just the last batch contains more error instance, what's more, the last minibatch is small than 128.
