### ISSUE TITLE
seqToseq例子用CPU可以，用GPU出错，请指教

### ISSUE THREAD

**Issue by lawup** [PaddlePaddle/Paddle#1091]
环境：
ubuntu14.04.5 
paddle-gpu-0.9.0
cuda-8.0
cudnn-5.1.5

用deb包安装的paddle，下载了同版本源码包，运行seqToseq例子，按照步骤一步步来（用cpu训练成功过，但是真的好慢，于是找了个GTX970），把train.sh中use_gpu=false改成true
运行 ./train.sh 如下报错 （use_gpu=false时可正常训练）

> I0107 21:15:48.867513  8238 Util.cpp:155] commandline: /usr/bin/../opt/paddle/bin/paddle_trainer --config=translation/train.conf --save_dir=translation/model --use_gpu=true --num_passes=16 --show_parameter_stats_period=100 --trainer_count=4 --log_period=10 --dot_period=5 
> *** stack smashing detected ***: /usr/bin/../opt/paddle/bin/paddle_trainer terminated
> *** Aborted at 1483794949 (unix time) try "date -d @1483794949" if you are using GNU date ***
> PC: @     0x7f3f7b5cbc37 (unknown)
> *** SIGABRT (@0x3e80000202e) received by PID 8238 (TID 0x7f3f7d8ce840) from PID 8238; stack trace: ***
>     @     0x7f3f7d1c5330 (unknown)
>     @     0x7f3f7b5cbc37 (unknown)
>     @     0x7f3f7b5cf028 (unknown)
>     @     0x7f3f7b6082a4 (unknown)
>     @     0x7f3f7b69fbbc (unknown)
>     @     0x7f3f7b69fb60 (unknown)
>     @           0x8954ce hl_create_global_resources()
>     @           0x8959f9 hl_specify_devices_start()
>     @           0x895d2d hl_start()
>     @           0x818602 paddle::initMain()
>     @           0x52ac5b main
>     @     0x7f3f7b5b6f45 (unknown)
>     @           0x540c05 (unknown)
>     @                0x0 (unknown)
> /usr/bin/paddle: line 109:  8238 Aborted                 (core dumped) ${DEBUGGER} $MYDIR/../opt/paddle/bin/paddle_trainer ${@:2}
> 

不知什么原因，谢谢

**Comment by lawup** [comment]
运行【图像分类】的例子也是同样的问题：CPU可以，GPU报错：

> *** stack smashing detected ***: /usr/bin/../opt/paddle/bin/paddle_trainer terminated

**Comment by qingqing01** [comment]
使用GPU，需要设置cudnn、cuda等动态库到LD_LIBRARY_PATH，可以参考 http://www.paddlepaddle.org/doc_cn/build_and_install/install/ubuntu_install.html#id1 这里看看。

**Comment by luotao1** [comment]
close due to no update.
