### ISSUE TITLE
ci中不提供最新的cuda的whl包下载

### ISSUE THREAD

**Issue by qq332982511** [PaddlePaddle/Paddle#10911]
paddlepaddle文档中pip安装方法提供都最新的gpu包无法下载
即http://www.paddlepaddle.org/docs/develop/documentation/fluid/zh/build_and_install/pip_install_cn.html
中的cuda8.0_cudnn5_avx_mkl和cuda8.0_cudnn7_avx_mkl的whl包无法下载，ci中也找不到对应的whl。希望修复一下

**Comment by seiriosPlus** [comment]
收到，我查一下CI看是否存在编译的异常

**Comment by seiriosPlus** [comment]
我尝试了全部的包，都能正常下载.
