### ISSUE TITLE
How to initialize a constant matrix in paddlepaddle?

### ISSUE THREAD

**Issue by zczc** [PaddlePaddle/Paddle#10927]
hi all, 
I want to achieve a diag function by paddlepaddle. In other words, given a vector $v$ [x_1, x_2, ... x_n], I want to construct a diagonal matrix $A$ [ [x_1, ...] [0, x_2, ...] ... [0, ..., x_n] ]. I plan to multiply v with a identity matrix to get $A$. Thus I need first initialize a constant identity matrix. I try to directly use a numpy matrix. Undoubtedly, it failed. Then I try to initialize a identity matrix variable in paddlepaddle. But I didn't find the corresponding APIs. So how can I get a constant matrix in paddlepaddle?

**Comment by qingqing01** [comment]
The identity matrix  is:

```
[1, 0, 0, 0, ...,
 0, 1, 0, 0, ...,
 0 ,0, 1, 0, ...,
 ...
 0, 0, 0, ..., 1]
```

Two ways:

1.  make this input as the data layer, pass the identity matrix by data feeder.
2.  If this variable has been created, called it `v`. Set a numpy array identity matrix to this variable.

```
#place = fluid.CUDAPlace(0)
place = fluid.CPUPlace()
t = fluid.global_scope().find_var(v.name).get_tensor()
m = np.eye(n) # n is length of vection
t.set(m, place)
```

**Comment by zczc** [comment]
thx very much.
