### ISSUE TITLE
Could not find a version that satisfies the requirement paddlepaddle

### ISSUE THREAD

**Issue by anxiaoyi** [PaddlePaddle/Paddle#10933]
Looking in indexes: http://mirrors.aliyun.com/pypi/simple/
Collecting paddlepaddle
  Could not find a version that satisfies the requirement paddlepaddle (from versions: )
No matching distribution found for paddlepaddle

Below is my machine:

``` bash
$ uname -a
$ Linux iZ2ze3p7zpoi60ykf5ld7hZ 4.4.0-85-generic #108-Ubuntu SMP Mon Jul 3 17:24:35 UTC 2017 i686 i686 i686 GNU/Linux
```

Pip version:

```bash
$ pip --version
$ pip 10.0.1 from /usr/local/lib/python2.7/dist-packages/pip (python 2.7)
```

**Comment by qingqing01** [comment]
When ` pip search paddlepaddle` on Mac:
```
 pip search paddlepaddle
paddlepaddle (0.12.0)      - Parallel Distributed Deep Learning
  INSTALLED: 0.10.0
  LATEST:    0.12.0
paddlepaddle-gpu (0.12.0)  - Parallel Distributed Deep Learning
```

and `pip install --upgrade paddlepaddle` on Mac:

```
pip install --upgrade paddlepaddle
Collecting paddlepaddle
  Downloading https://files.pythonhosted.org/packages/52/da/5e9d2255bd5c0fb40182546e86a6c915c37a0d40820b4cda428e8fbf8dc5/paddlepaddle-0.11.0-cp27-cp27m-macosx_10_12_x86_64.whl (48.5MB)
    37% |████████████                    | 18.2MB 25.7MB/s eta 0:00:02
```

And there is also no problem on Linux.

What's your system?

**Comment by anxiaoyi** [comment]
AliYun Ubuntu 64

```bash
root@iZ2ze3p7zpoi60ykf5ld7hZ:~# pip search paddlepaddle
paddlepaddle (0.12.0)      - Parallel Distributed Deep Learning
paddlepaddle-gpu (0.12.0)  - Parallel Distributed Deep Learning
```

**Comment by anxiaoyi** [comment]
@qingqing01 单独下载这两个版本的 whl 文件,这两个都无法安装成功,说当前系统不支持,AliYun 有什么限制吗

**Comment by qingqing01** [comment]
paddlepaddle 是CPU版本，
paddlepaddle-gpu是GPU版本。

你 `pip install paddlepaddle`出什么错？

**Comment by anxiaoyi** [comment]
@qingqing01 

![2018_05_25_15_49_33](https://user-images.githubusercontent.com/4382796/40532817-49eb875c-6033-11e8-91fb-30277c5f6b29.png)

**Comment by anxiaoyi** [comment]
@qingqing01  我的操作系统： Ubuntu 16.04 32位

**Comment by qingqing01** [comment]
我们的whl包是64位的~

**Comment by anxiaoyi** [comment]
@qingqing01 那我必须自己编译一个 32 位的,才能继续使用吧,你们支持 32 位编译吗

**Comment by qingqing01** [comment]
出现这个错的原因还有：

http://paddlepaddle.org/docs/develop/documentation/en/faq/build_and_install/index_en.html#paddlepaddle-whl-is-not-a-supported-wheel-on-this-platform

感觉你最好找个64位机器试下。

**Comment by anxiaoyi** [comment]
@qingqing01  OK

**Comment by Nivitus** [comment]
Just follow this cmd
**pip3 install paddlepaddle-gpu**
