### ISSUE TITLE
怎么用paddle实现文本分类的attention？

### ISSUE THREAD

**Issue by leyiwang** [PaddlePaddle/Paddle#10966]
```
def bilstm_with_attention(dict_dim, class_dim=2,  emb_dim=128,  hid_dim=128,  is_infer=False): 
    data = paddle.layer.data("word", paddle.data_type.integer_value_sequence(dict_dim))
    lbl = paddle.layer.data("label", paddle.data_type.integer_value(class_dim))
    emb = paddle.layer.embedding(input=data, size=emb_dim)
    bi_lstm = network.bidirectional_lstm(name='lstm', input=emb, size=hid_dim, return_seq=True)
   
    attention_weight = network.fc_layer(input=bi_lstm, size=1, act=paddle.activation.SequenceSoftmax())
    scaled = network.scaling_layer(input=bi_lstm, weight=attention_weight)
    
    prob = paddle.layer.fc(input=scaled, size=class_dim,act=act.SoftmaxActivation())
    cost = paddle.layer.classification_cost(input=prob, label=lbl)
    return cost, prob, lbl
```
<img width="386" alt="attention" src="https://user-images.githubusercontent.com/10727709/40600232-42671ab2-6283-11e8-9272-040ff1a81fde.png">
我想通过paddle实现带attention的文本分类，其中attention是MLP attention如上图所示。
bi_lstm层输出所有样本的隐层单元序列：[[h_11,h_12,h13...h_1n], [h21,h22,h23...h2m] ...],其中h11为第一个样本的[h_11,h_12,h13...h_1n]，h_11为第一个文本的第一个lstm单元的隐层输出。
想实现图示的attention机制利用每个文本的所有隐层序列编码得到文档的向量，最后对文档向量进行文本分类，应该怎么实现？

**Comment by typhoonzero** [comment]
您好，看您的代码应该是在使用v2 API的，可以餐卡book中的NMT的章节中使用attention部分的代码：

参考：

http://www.paddlepaddle.org/docs/develop/book/08.machine_translation/index.html#permalink-7-attention-mechanism

https://github.com/PaddlePaddle/book/blob/develop/08.machine_translation/train.py

相关API文档：

http://www.paddlepaddle.org/docs/develop/api/en/config/networks.html#permalink-13-simple_attention

**Comment by leyiwang** [comment]
@typhoonzero 你好，我注意到simple_attention接收的参数为两个序列，一个是源语言的隐层状态序列编码，一个是上下文序列，encoded_sequence=enc_seq, encoded_proj=enc_proj。但在文本分类任务中的attention的输入一个是隐层状态序列，另一个是参数向量u，和神经翻译的attention还不太一样。除了aimple_attention, 没有看到paddle里有没有MLP attention的api，有没有什么方法可以实现，辛苦了

**Comment by typhoonzero** [comment]
刚才请教 @guoshengCS ，类似的issue有： https://github.com/PaddlePaddle/Paddle/issues/9362

如果是期望实现类似self-attention的方法，并且包含可学习参数u，可以试试使用`simple_attention`，encoder和decorder都传入lstm的隐层状态。

另一个方法，不包含可学习参数时，可以参考https://github.com/PaddlePaddle/Paddle/issues/9362 中，将lstm的输出自己和自己做`dot_prod`，要不先试试类似的方法？期待您的反馈。

**Comment by leyiwang** [comment]
```
bi_lstm = network.bidirectional_lstm(name='lstm', input=emb, size=hid_dim, return_seq=True)
weighted = simple_attention(bi_lstm, bi_lstm, decoder_state)
```
@typhoonzero 是这样吗？simple_attention方法接收三个参数，这边decoder_state应该怎么设置？

**Comment by guoshengCS** [comment]
你需要的attention机制和目前Paddle封装的`simple_attention `和`dot_product_attention`这两种不太一样，可以试下下面的配置，对应公式的配置给出了注释

```python
def bilstm_with_attention(dict_dim, class_dim=2,  emb_dim=128,  hid_dim=128,  is_infer=False): 
    data = paddle.layer.data("word", paddle.data_type.integer_value_sequence(dict_dim))
    lbl = paddle.layer.data("label", paddle.data_type.integer_value(class_dim))
    emb = paddle.layer.embedding(input=data, size=emb_dim)
    bi_lstm = network.bidirectional_lstm(name='lstm', input=emb, size=hid_dim, return_seq=True)
    # This following line corresponds to the first formula
    u_it = paddle.layer.fc(input=bi_lstm, size= hid_dim, act=paddle.activation.Tanh())
    # This following line corresponds to the second formula
    attention_weight = paddle.layer.fc(input=u_it, size=1, act=paddle.activation.SequenceSoftmax())
    # These following two lines correspond to the third formula
    scaled = network.scaling_layer(input=bi_lstm, weight=attention_weight)
    s_i = paddle.layer.pooling(input= scaled, pooling_type=SumPooling())
    
    prob = paddle.layer.fc(input=s_i, size=class_dim,act=act.SoftmaxActivation())
    cost = paddle.layer.classification_cost(input=prob, label=lbl)
    return cost, prob, lbl
```

**Comment by leyiwang** [comment]
@typhoonzero @guoshengCS 太感谢了，可以了！谢谢两位！

**Comment by typhoonzero** [comment]
感谢 @guoshengCS ~~
