### ISSUE TITLE
seq2seq model sparse update on cpu cluster error

### ISSUE THREAD

**Issue by autoAlien** [PaddlePaddle/Paddle#1096]
seq2seq model, 用CPU集群的sparse update 报错，错误信息截图为：
<img width="1063" alt="428c975e3d1f2f8f88236a76c" src="https://cloud.githubusercontent.com/assets/24998163/21756412/0d8d1a4e-d65c-11e6-93ff-0a805215cada.png">
模型和提交配置：
提交shell带有此参数：--ports_num_for_sparse=1 \
cluster_config带有此参数：use_remote_sparse=True,
setting 的优化算法为：learning_method=AdaGradOptimizer(),
seq2seq_net.py 中，gru_encoder_decoder 函数的embedding_layer 设置有 param_attr=ParamAttr(name='_source_language_embedding', sparse_update=True))

**Comment by qingqing01** [comment]
请不要使用图片，直接粘贴文本吧。这个信息太少，或许可以给个作业链接。

**Comment by autoAlien** [comment]
这个是job链接：http://10.73.221.41:8920/fileview.html?path=/home/normandy/maybach/225298/
错误日志为：
Tue Jan 10 13:13:16 2017[1,0]<stderr>:PC: @           0x702d7a _ZNSt17_Function_handlerIFvPN6paddle9ParameterEEZNS0_15TrainerInternal13trainOneBatchElRKNS0_9DataBatchEPSt6vectorINS0_8ArgumentESaIS9_EEEUlS2_E_E9_M_invokeERKSt9_Any_dataS2_
Tue Jan 10 13:13:16 2017[1,0]<stderr>:*** SIGSEGV (@0x0) received by PID 26948 (TID 0x7ffd27cad780) from PID 0; stack trace: ***
Tue Jan 10 13:13:16 2017[1,0]<stderr>:    @     0x7ffd27887160 (unknown)
Tue Jan 10 13:13:16 2017[1,0]<stderr>:    @           0x702d7a _ZNSt17_Function_handlerIFvPN6paddle9ParameterEEZNS0_15TrainerInternal13trainOneBatchElRKNS0_9DataBatchEPSt6vectorINS0_8ArgumentESaIS9_EEEUlS2_E_E9_M_invokeERKSt9_Any_dataS2_
Tue Jan 10 13:13:16 2017[1,0]<stderr>:    @           0x7040b1 paddle::TrainerInternal::trainOneBatch()
Tue Jan 10 13:13:16 2017[1,0]<stderr>:    @           0x6fe850 paddle::Trainer::trainOneDataBatch()
Tue Jan 10 13:13:16 2017[1,0]<stderr>:    @           0x7015ce paddle::Trainer::trainOnePass()
Tue Jan 10 13:13:16 2017[1,0]<stderr>:    @           0x7028b5 paddle::Trainer::train()
Tue Jan 10 13:13:16 2017[1,0]<stderr>:    @           0x5920aa main
Tue Jan 10 13:13:16 2017[1,0]<stderr>:    @     0x7ffd266acbd5 __libc_start_main
Tue Jan 10 13:13:16 2017[1,0]<stderr>:    @           0x59dcf5 (unknown)
Tue Jan 10 13:13:18 2017[1,0]<stderr>:./train.sh: line 207: 26948 Segmentation fault      PYTHONPATH=./paddle:$PYTHONPATH GLOG_logtostderr=0 GLOG_log_dir="./log" ./paddle_trainer --num_gradient_servers=${OMPI_COMM_WORLD_SIZE} --trainer_id=${OMPI_COMM_WORLD_RANK} --pservers=$ipstring --rdma_tcp=${rdma_tcp} --nics=${nics} ${train_arg} --config=conf/trainer_config.conf --save_dir=./${save_dir} ${extern_arg}

**Comment by kuke** [comment]
Closed because of inactivity
