### ISSUE TITLE
PaddlePaddle-Api文档说明不清楚

### ISSUE THREAD

**Issue by dyning** [PaddlePaddle/Paddle#10972]
http://www.paddlepaddle.org/docs/develop/api/fluid/en/layers.html#permalink-47-dynamic_gru
很多函数说明不清楚，例如：

linear_chain_crf
paddle.fluid.layers.linear_chain_crf(input, label, param_attr=None)

crf_decoding
paddle.fluid.layers.crf_decoding(input, param_attr, label=None)

**Comment by shanyi15** [comment]
感谢您的反馈，正在跟进中

**Comment by dyning** [comment]
赞
