### ISSUE TITLE
运行首页demo报错

### ISSUE THREAD

**Issue by jaegerstar** [PaddlePaddle/Paddle#10989]
> Traceback (most recent call last):
  File "test.py", line 4, in <module>
    paddle.init(use_gpu=False, trainer_count=1)
  File "/home/work/zhangjie/paddle/lib/python2.7/site-packages/paddle/v2/__init__.py", line 128, in init
    import py_paddle.swig_paddle as api
  File "/home/work/zhangjie/paddle/lib/python2.7/site-packages/py_paddle/__init__.py", line 15, in <module>
    from util import DataProviderWrapperConverter
  File "/home/work/zhangjie/paddle/lib/python2.7/site-packages/py_paddle/util.py", line 18, in <module>
    import swig_paddle
  File "/home/work/zhangjie/paddle/lib/python2.7/site-packages/py_paddle/swig_paddle.py", line 28, in <module>
    _swig_paddle = swig_import_helper()
  File "/home/work/zhangjie/paddle/lib/python2.7/site-packages/py_paddle/swig_paddle.py", line 24, in swig_import_helper
    _mod = imp.load_module('_swig_paddle', fp, pathname, description)
ImportError: libmklml_intel.so: cannot open shared object file: No such file or directory

是采用pip安装的方式

**Comment by yeyupiaoling** [comment]
@jaegerstar ` libmklml_intel.so`这个文件不存在，应该是在`/usr/local/lib`下，你找找是不是在这里，如果是的话，复制到`/usr/lib`小

**Comment by jaegerstar** [comment]
@yeyupiaoling 两个文件都没有

**Comment by tensor-tang** [comment]
可以看下是不是在`/lib`下

**Comment by ftry** [comment]
去哪里下载这个文件libmklml_intel.so
？？？？

**Comment by yeyupiaoling** [comment]
![image](https://user-images.githubusercontent.com/26297768/40645631-813a6e70-6359-11e8-9495-b077c14b1023.png)
@jaegerstar

**Comment by yeyupiaoling** [comment]
@jaegerstar 你升级试试，pip install paddlepaddle -U

**Comment by tensor-tang** [comment]
@ftry 下载链接在这个里面 https://github.com/PaddlePaddle/Paddle/blob/develop/cmake/external/mklml.cmake#L33
或者在[这里](https://github.com/intel/mkl-dnn/releases/download/v0.14/mklml_lnx_2018.0.3.20180406.tgz)下载。

**Comment by ftry** [comment]
我是用pip install paddlepaddle 下载的

**Comment by ftry** [comment]
真没有这个文件！！！要不你发我吧

**Comment by yeyupiaoling** [comment]
升级一下吧，pip install paddlepaddle -U @ftry

**Comment by chengduoZH** [comment]
@ftry 你pip install paddlepaddle-gpu试试？看看能否在`/usr/local/lib`里面找到libmkldnn.so.0

**Comment by ftry** [comment]
@chengduoZH 我是通过pycharm建立的虚拟环境，使用pip install paddlepaddle的
用这种方式有问题吗？

**Comment by chengduoZH** [comment]
抱歉  我们没在pycharm建立的虚拟环境中测试过

**Comment by chengduoZH** [comment]
This issue is similar with https://github.com/PaddlePaddle/Paddle/issues/11008.
