### ISSUE TITLE
Fluid版本训练好的模型如何进行合并？

### ISSUE THREAD

**Issue by yeyupiaoling** [PaddlePaddle/Paddle#10990]
在Android设备或者是Linux下，使用的预测模型是合并的模型，在V2版本中，预测模型是一个`.tar.gz`的文件。但是在fluid版本的预测模型不是这样的了。那么如何合并模型呢？

以下是V2的合并模型的代码：
```python
from paddle.utils.merge_model import merge_v2_model

# import your network configuration
from mobilenet import mobile_net

net = mobile_net(3*224*224, 102, 1.0)
param_file = './mobilenet_flowers102.tar.gz'
output_file = './output.paddle'

merge_v2_model(net, param_file, output_file)
```

**Comment by luotao1** [comment]
请参考 http://www.paddlepaddle.org/docs/develop/documentation/fluid/zh/howto/inference/inference_support_in_fluid.html 中的“参数保存到同一个文件”

**Comment by yeyupiaoling** [comment]
@luotao1 
使用这个方式拿到的模型文件，能否像之前那样加载预测模型呢？
https://github.com/PaddlePaddle/Paddle/blob/60783a753adc0429d796c7b77f2f4eeea23a8e15/python/paddle/fluid/tests/book/test_image_classification.py#L216-L217

上面的是Python的，下面C++的是否也是这样使用的？
https://github.com/PaddlePaddle/Paddle/blob/60783a753adc0429d796c7b77f2f4eeea23a8e15/paddle/fluid/inference/tests/book/test_inference_image_classification.cc#L38-L40

最后还有这个`model_filename`是什么意思？
![image](https://user-images.githubusercontent.com/26297768/40694961-9a884e0e-63f1-11e8-9ebc-f42d5f7da2c5.png)

谢谢

**Comment by luotao1** [comment]
> 使用这个方式拿到的模型文件，能否像之前那样加载预测模型

请问，以前那样加载预测模型是指？

> 下面C++的是否也是这样使用的

C++的例子可以参考https://github.com/luotao1/fluid_inference_example/blob/master/example.cc#L43 我们最近会把inference的C++示例放入主干 @tensor-tang 。

> 编译Fluid Inference库 和 链接Fluid Inference库 这两个的区别是什么, 或者说，这些是用来干什么的？

这些是服务器端做预测使用的，你贴的链接是移动端预测用的。编译Fluid Inference库是指编译出libpaddle_fluid.so和相关的头文件，链接Fluid Inference库，是指在服务中怎么使用libpaddle_fluid.so。可以先参考上一条回答中的示例，近期我们会整理进主干。

**Comment by yeyupiaoling** [comment]
@luotao1 
如果`model_filename`和`params_filename`都为None，那么`save_inference_model`的模型参数文件的一个文件夹，里面每个参数变量的文件，可以使用以下的方法加载这些文件，当时使用设置`model_filename`为None、`params_filename`为__params__时，也就是参数保存到同一个文件，下面的方法还可以用吗？
https://github.com/PaddlePaddle/Paddle/blob/60783a753adc0429d796c7b77f2f4eeea23a8e15/python/paddle/fluid/tests/book/test_image_classification.py#L216-L217

因为我看到 **编译Fluid Inference库** 得到的文件跟编译安装所需的Android参不多，所以想问，Fluid版本的是否也可以编译Android的PaddlePaddle库
https://github.com/PaddlePaddle/Paddle/blob/develop/doc/mobile/cross_compiling_for_android_en.md#build-and-install

**Comment by luotao1** [comment]
1. 参考 http://www.paddlepaddle.org/docs/develop/api/fluid/en/io.html#permalink-8-load_inference_model 
    使用`fluid.io.load_inference_model(save_dirname, exe, model_filename=None, params_filename=__params__) `进行加载。
2. Fluid版本暂时无法编译Andorid的PaddlePaddle库。

**Comment by yeyupiaoling** [comment]
@luotao1 收到，谢谢您的回答。
