### ISSUE TITLE
Finetune Fluid模型报错

### ISSUE THREAD

**Issue by chengyuz** [PaddlePaddle/Paddle#10998]
1、将caffe VGG16模型转化为fluid要求的类型，其中模型的加载和存储使用的是(https://github.com/PaddlePaddle/Paddle/issues/8973)中的方法；
2、输入数据类型：`images = fluid.layers.data(name='img', shape=data_shape, dtype='float32')`，data_shape = [3, 300, 300]；
加载模型：`predict = vgg16_raw(images)`，然后run：
`loss = exe.run(
                #fluid.default_main_program(),
                main_program,
                feed={"img": img_data,
                      "label": y_data},
                fetch_list=[avg_cost])`，
报错：
batch_size: 128
data_format: NCHW
data_set: cifar10
device: GPU
iterations: 80
learning_rate: 0.001
pass_num: 50
skip_batch_num: 5
with_test: False
------------------------------------------------
/home/yczhao/anaconda2/lib/python2.7/site-packages/paddle/fluid/average.py:42: Warning: The WeightedAverage is deprecated, please use fluid.metrics.Accuracy instead.
  (self.__class__.__name__), Warning)
Traceback (most recent call last):
  File "vgg16.py", line 301, in <module>
    main()
  File "vgg16.py", line 263, in main
    fetch_list=[avg_cost])
  File "/home/yczhao/anaconda2/lib/python2.7/site-packages/paddle/fluid/executor.py", line 335, in run
    fetch_var_name=fetch_var_name)
  File "/home/yczhao/anaconda2/lib/python2.7/site-packages/paddle/fluid/executor.py", line 234, in _add_feed_fetch_ops
    out = global_block.var(name)
  File "/home/yczhao/anaconda2/lib/python2.7/site-packages/paddle/fluid/framework.py", line 724, in var
    raise ValueError("var %s not in this block" % name)
ValueError: var img not in this block

**Comment by chengduoZH** [comment]
> var img not in this block

错误显示没找到`img`这个var

能否把模型贴一下

**Comment by chengyuz** [comment]
@chengduoZH 
`def vgg16_raw(input):
    def conv(input, k_h, k_w, c_o, s_h, s_w, name, relu=True, padding=None, group=1, biased=True):
        if padding is None:
            padding = [0, 0]
            
        # Get the number of channels in the input
        c_i, h_i, w_i = input.shape[1:]
        
        # Verify that the grouping parameter is valid
        assert c_i % group == 0
        assert c_o % group == 0

        fluid = import_fluid()
        prefix = name + '_'
        output = fluid.layers.conv2d(
            input=input,
            filter_size=[k_h, k_w],
            num_filters=c_o,
            stride=[s_h, s_w],
            padding=padding,
            groups=group,
            param_attr=fluid.ParamAttr(name=prefix + "weights"),
            bias_attr=fluid.ParamAttr(name=prefix + "biases"),
            act="relu" if relu is True else None)
        return output
        
    def pool(pool_type, input, k_h, k_w, s_h, s_w, name, padding):
        # Get the number of channels in the input
        in_hw = input.shape[2:]
        k_hw = [k_h, k_w]
        s_hw = [s_h, s_w]

        fluid = import_fluid()
        output = fluid.layers.pool2d(
            input=input,
            pool_size=k_hw,
            pool_stride=s_hw,
            pool_padding=padding,
            ceil_mode=True,
            pool_type=pool_type)
        return output
        
    def max_pool(input, k_h, k_w, s_h, s_w, name, padding=[0, 0]):
        return pool('max', input, k_h, k_w, s_h, s_w, name, padding)
    
    conv1_1 = conv(input, 3, 3, 64, 1, 1, padding=[1, 1], name='conv1_1')
    conv1_2 = conv(conv1_1, 3, 3, 64, 1, 1, padding=[1, 1], name='conv1_2')
    pool1 = max_pool(conv1_2, 2, 2, 2, 2, name='pool1')
    conv2_1 = conv(pool1, 3, 3, 128, 1, 1, padding=[1, 1], name='conv2_1')
    conv2_2 = conv(conv2_1, 3, 3, 128, 1, 1, padding=[1, 1], name='conv2_2')
    pool2 = max_pool(conv2_2, 2, 2, 2, 2, name='pool2')
    conv3_1 = conv(pool2, 3, 3, 256, 1, 1, padding=[1, 1], name='conv3_1')
    conv3_2 = conv(conv3_1, 3, 3, 256, 1, 1, padding=[1, 1], name='conv3_2')
    conv3_3 = conv(conv3_2, 3, 3, 256, 1, 1, padding=[1, 1], name='conv3_3')
    pool3 = max_pool(conv3_3, 2, 2, 2, 2, name='pool3')
    conv4_1 = conv(pool3, 3, 3, 512, 1, 1, padding=[1, 1], name='conv4_1')
    conv4_2 = conv(conv4_1, 3, 3, 512, 1, 1, padding=[1, 1], name='conv4_2')
    conv4_3 = conv(conv4_2, 3, 3, 512, 1, 1, padding=[1, 1], name='conv4_3')
    pool4 = max_pool(conv4_3, 2, 2, 2, 2, name='pool4')
    conv5_1 = conv(pool4, 3, 3, 512, 1, 1, padding=[1, 1], name='conv5_1')
    conv5_2 = conv(conv5_1, 3, 3, 512, 1, 1, padding=[1, 1], name='conv5_2')
    conv5_3 = conv(conv5_2, 3, 3, 512, 1, 1, padding=[1, 1], name='conv5_3')
    
    #the output feature map of pool5 is 7*7(224*224 input) 
    pool5 = max_pool(conv5_3, 2, 2, 2, 2, name='pool5')
    
    #add extra layers
    fc6 = conv(pool5, 7, 7, 4096, 1, 1, name = 'fc6')
    fc7 = conv(fc6, 1, 1, 4096, 1, 1, name = 'fc7') 
    score_fr = conv(fc7, 1, 1, 21, 1, 1, name = 'score_fr')
    upscore = fluid.layers.conv2d_transpose(input = score_fr, num_filters = 21, output_size = (300, 300))
    return upscore

def main():
    classdim = 21
    data_shape = [3, 300, 300]
    
    vgg16_filename = './models/vgg16_filename'
    vgg16_dirname = './models/vgg16_dirname'
        
    # Initialize executor
    place = core.CPUPlace() if args.device == 'CPU' else core.CUDAPlace(0)
    exe = fluid.Executor(place)
    
    #restore from trained model
    with open(vgg16_filename, "rb") as f:
        program_desc_str = f.read()
    main_program = Program.parse_from_string(program_desc_str)
    load_persistables(exe, vgg16_dirname, main_program)

    # Input data
    images = fluid.layers.data(name='img', shape=data_shape, dtype='float32')
    label = fluid.layers.data(name='label', shape=[300*300], dtype='float32')

    # Train program
    predict = vgg16_raw(images)
    
    cost = crossentropy_seg(predict, label)
    avg_cost = fluid.layers.mean(x=cost)

    # Optimization
    optimizer = fluid.optimizer.Adam(learning_rate=args.learning_rate)
    opts = optimizer.minimize(avg_cost)

    #fluid.memory_optimize(fluid.default_main_program())
    fluid.memory_optimize(main_program)

    # Parameter initialization
    exe.run(fluid.default_startup_program())
    
    data_args = data_provider.Settings(
        data_dir = './data',
        resize_h = cfg.IMG_HEIGHT,
        resize_w = cfg.IMG_WIDTH,
        mean_value = [104, 117, 124])
    
    train_reader = paddle.batch(
        data_provider.train(data_args, './data/train.txt'),
        batch_size = 6)

    iters, num_samples, start_time = 0, 0, time.time()
    accuracy = fluid.average.WeightedAverage()
    for pass_id in range(args.pass_num):
        accuracy.reset()
        train_accs = []
        train_losses = []
        for batch_id, data in enumerate(train_reader()):
            if iters == args.skip_batch_num:
                start_time = time.time()
                num_samples = 0
            if iters == args.iterations:
                break
            img_data = np.array(map(lambda x: x[0].reshape(data_shape), data)).astype("float32")
            y_data = np.array(map(lambda x: x[1], data)).astype("float32")
            #y_data = y_data.reshape([-1, 1])
            #loss, acc, weight = 
            loss = exe.run(
                #fluid.default_main_program(),
                main_program,
                feed={"img": img_data,
                      "label": y_data},
                fetch_list=[avg_cost])`

**Comment by chengyuz** [comment]
@chengduoZH 
模型：
`def vgg16_raw(input):
    def conv(input, k_h, k_w, c_o, s_h, s_w, name, relu=True, padding=None, group=1, biased=True):
        if padding is None:
            padding = [0, 0]
            
        # Get the number of channels in the input
        c_i, h_i, w_i = input.shape[1:]
        
        # Verify that the grouping parameter is valid
        assert c_i % group == 0
        assert c_o % group == 0

        fluid = import_fluid()
        prefix = name + '_'
        output = fluid.layers.conv2d(
            input=input,
            filter_size=[k_h, k_w],
            num_filters=c_o,
            stride=[s_h, s_w],
            padding=padding,
            groups=group,
            param_attr=fluid.ParamAttr(name=prefix + "weights"),
            bias_attr=fluid.ParamAttr(name=prefix + "biases"),
            act="relu" if relu is True else None)
        return output
        
    def pool(pool_type, input, k_h, k_w, s_h, s_w, name, padding):
        # Get the number of channels in the input
        in_hw = input.shape[2:]
        k_hw = [k_h, k_w]
        s_hw = [s_h, s_w]

        fluid = import_fluid()
        output = fluid.layers.pool2d(
            input=input,
            pool_size=k_hw,
            pool_stride=s_hw,
            pool_padding=padding,
            ceil_mode=True,
            pool_type=pool_type)
        return output
        
    def max_pool(input, k_h, k_w, s_h, s_w, name, padding=[0, 0]):
        return pool('max', input, k_h, k_w, s_h, s_w, name, padding)
    
    conv1_1 = conv(input, 3, 3, 64, 1, 1, padding=[1, 1], name='conv1_1')
    conv1_2 = conv(conv1_1, 3, 3, 64, 1, 1, padding=[1, 1], name='conv1_2')
    pool1 = max_pool(conv1_2, 2, 2, 2, 2, name='pool1')
    conv2_1 = conv(pool1, 3, 3, 128, 1, 1, padding=[1, 1], name='conv2_1')
    conv2_2 = conv(conv2_1, 3, 3, 128, 1, 1, padding=[1, 1], name='conv2_2')
    pool2 = max_pool(conv2_2, 2, 2, 2, 2, name='pool2')
    conv3_1 = conv(pool2, 3, 3, 256, 1, 1, padding=[1, 1], name='conv3_1')
    conv3_2 = conv(conv3_1, 3, 3, 256, 1, 1, padding=[1, 1], name='conv3_2')
    conv3_3 = conv(conv3_2, 3, 3, 256, 1, 1, padding=[1, 1], name='conv3_3')
    pool3 = max_pool(conv3_3, 2, 2, 2, 2, name='pool3')
    conv4_1 = conv(pool3, 3, 3, 512, 1, 1, padding=[1, 1], name='conv4_1')
    conv4_2 = conv(conv4_1, 3, 3, 512, 1, 1, padding=[1, 1], name='conv4_2')
    conv4_3 = conv(conv4_2, 3, 3, 512, 1, 1, padding=[1, 1], name='conv4_3')
    pool4 = max_pool(conv4_3, 2, 2, 2, 2, name='pool4')
    conv5_1 = conv(pool4, 3, 3, 512, 1, 1, padding=[1, 1], name='conv5_1')
    conv5_2 = conv(conv5_1, 3, 3, 512, 1, 1, padding=[1, 1], name='conv5_2')
    conv5_3 = conv(conv5_2, 3, 3, 512, 1, 1, padding=[1, 1], name='conv5_3')
    
    #the output feature map of pool5 is 7*7(224*224 input) 
    pool5 = max_pool(conv5_3, 2, 2, 2, 2, name='pool5')
    
    #add extra layers
    fc6 = conv(pool5, 7, 7, 4096, 1, 1, name = 'fc6')
    fc7 = conv(fc6, 1, 1, 4096, 1, 1, name = 'fc7') 
    score_fr = conv(fc7, 1, 1, 21, 1, 1, name = 'score_fr')
    upscore = fluid.layers.conv2d_transpose(input = score_fr, num_filters = 21, output_size = (300, 300))
    return upscore`
训练：
`def main():
    classdim = 21
    data_shape = [3, 300, 300]
    
    vgg16_filename = './models/vgg16_filename'
    vgg16_dirname = './models/vgg16_dirname'
        
    # Initialize executor
    place = core.CPUPlace() if args.device == 'CPU' else core.CUDAPlace(0)
    exe = fluid.Executor(place)
    
    #restore from trained model
    with open(vgg16_filename, "rb") as f:
        program_desc_str = f.read()
    main_program = Program.parse_from_string(program_desc_str)
    load_persistables(exe, vgg16_dirname, main_program)

    # Input data
    images = fluid.layers.data(name='img', shape=data_shape, dtype='float32')
    label = fluid.layers.data(name='label', shape=[300*300], dtype='float32')

    # Train program
    predict = vgg16_raw(images)
    
    cost = crossentropy_seg(predict, label)
    avg_cost = fluid.layers.mean(x=cost)

    # Optimization
    optimizer = fluid.optimizer.Adam(learning_rate=args.learning_rate)
    opts = optimizer.minimize(avg_cost)

    #fluid.memory_optimize(fluid.default_main_program())
    fluid.memory_optimize(main_program)

    # Parameter initialization
    exe.run(fluid.default_startup_program())
    
    data_args = data_provider.Settings(
        data_dir = './data',
        resize_h = cfg.IMG_HEIGHT,
        resize_w = cfg.IMG_WIDTH,
        mean_value = [104, 117, 124])
    
    train_reader = paddle.batch(
        data_provider.train(data_args, './data/train.txt'),
        batch_size = 6)

    iters, num_samples, start_time = 0, 0, time.time()
    accuracy = fluid.average.WeightedAverage()
    for pass_id in range(args.pass_num):
        accuracy.reset()
        train_accs = []
        train_losses = []
        for batch_id, data in enumerate(train_reader()):
            if iters == args.skip_batch_num:
                start_time = time.time()
                num_samples = 0
            if iters == args.iterations:
                break
            img_data = np.array(map(lambda x: x[0].reshape(data_shape), data)).astype("float32")
            y_data = np.array(map(lambda x: x[1], data)).astype("float32")
            #y_data = y_data.reshape([-1, 1])
            #loss, acc, weight = 
            loss = exe.run(
                #fluid.default_main_program(),
                main_program,
                feed={"img": img_data,
                      "label": y_data},
                fetch_list=[avg_cost])`

**Comment by chengduoZH** [comment]
你这种调用方式错的
首先从模型配置讲，既然你在`exe.run`里面调用的是`main_program`，并且`main_program`是从文件从读取的（`main_program = Program.parse_from_string(program_desc_str)`），那么你为什么还在Python端构建`main_program`呢？**因为`main_program`里面有`img`这个var，所以才会报错**

**Comment by chengyuz** [comment]
谢谢回复，我这边是基于加载的模型参数和结构做finetune，对应输入数据是：
`images = fluid.layers.data(name='img', shape=data_shape, dtype='float32')
    label = fluid.layers.data(name='label', shape=[300*300], dtype='float32')

    # Train program
    predict = vgg16_raw(images)`
实验中加载的模型是从caffe模型转化过来的

**Comment by chengduoZH** [comment]
但是你run的时候是调用的从文件中加载的模型结构
```
            loss = exe.run(
                #fluid.default_main_program(),
                main_program,
                feed={"img": img_data,
                      "label": y_data},
                fetch_list=[avg_cost])
```
而不是
```
  # Input data
    images = fluid.layers.data(name='img', shape=data_shape, dtype='float32')
    label = fluid.layers.data(name='label', shape=[300*300], dtype='float32')

    # Train program
    predict = vgg16_raw(images)
    
    cost = crossentropy_seg(predict, label)
    avg_cost = fluid.layers.mean(x=cost)

    # Optimization
    optimizer = fluid.optimizer.Adam(learning_rate=args.learning_rate)
    opts = optimizer.minimize(avg_cost)

    #fluid.memory_optimize(fluid.default_main_program())
```

**Comment by chengduoZH** [comment]
你这样写也是有问题的
建议参考一下图像分类中infer部分是怎么写的
https://github.com/PaddlePaddle/models/blob/86eb2e210c94c7fe5311858a997f9626b7124d47/fluid/image_classification/infer.py#L25-L46

**Comment by chengduoZH** [comment]
你上面的写法是有问题的，你应该参考一下这里个例子： https://github.com/PaddlePaddle/models/blob/86eb2e210c94c7fe5311858a997f9626b7124d47/fluid/image_classification/infer.py#L25-L46

比如fluid.default_main_program()一开始是空的的，但是上面的代码一开始就调用了参数加载操作`fluid.io.load_vars(exe, vgg16_weights, fluid.default_main_program())`,这相当于没有加载任何参数。

**Comment by chengyuz** [comment]
`    predict = vgg16(images)
    
    train_program = fluid.default_main_program().clone(for_test = False)
    
    place = core.CPUPlace() if cfg.DEVICE == 'CPU' else core.CUDAPlace(0)
    exe = fluid.Executor(place)
    
    vgg16_weights = cfg.PRETRAINED_MODEL
    def if_exist(var):
        return os.path.exists(os.path.join(vgg16_weights, var.name)) 
    fluid.io.load_vars(exe, vgg16_weights, predicate=if_exist)

    cost = softmax_with_cross_entropy(predict, label)
    avg_cost = fluid.layers.mean(x=cost)
    optimizer = fluid.optimizer.Adam(learning_rate = cfg.TRAIN.LEARNING_RATE)
    optimizer.minimize(avg_cost)

    fluid.memory_optimize(train_program)
    
    exe.run(fluid.default_startup_program())`
上面是基于image classification修改后的，不过报错：
`Traceback (most recent call last):
  File "train.py", line 106, in <module>
    main()
  File "train.py", line 84, in main
    fetch_list=[avg_cost])
  File "/home/yczhao/anaconda2/lib/python2.7/site-packages/paddle/fluid/executor.py", line 338, in run
    self.executor.run(program.desc, scope, 0, True, True)
paddle.fluid.core.EnforceNotMet: Cannot find fetch variable in scope, fetch_var_name is mean_0.tmp_0 at [/paddle/paddle/fluid/operators/fetch_op.cc:40]`

**Comment by chengduoZH** [comment]
> 还有就是exe.run(fluid.default_startup_program())初始化会不会覆盖load_vars中的初始化

是会覆盖掉的。

你试一下下面这种调用方式
```
predict = vgg16(images)
cost = softmax_with_cross_entropy(predict, label)
avg_cost = fluid.layers.mean(x=cost)
optimizer = fluid.optimizer.Adam(learning_rate = cfg.TRAIN.LEARNING_RATE)
optimizer.minimize(fluid.default_main_program())

place = core.CPUPlace() if cfg.DEVICE == 'CPU' else core.CUDAPlace(0)
exe = fluid.Executor(place)

vgg16_weights = cfg.PRETRAINED_MODEL
def if_exist(var):
    return os.path.exists(os.path.join(vgg16_weights, var.name)) 
fluid.io.load_vars(exe, vgg16_weights, predicate=if_exist)
```

**Comment by chengyuz** [comment]
谢谢！我用的下面的调用模型还是没加载进去，麻烦你看下是否有什么问题：
`data_shape = [cfg.IMG_CHANNEL, cfg.IMG_HEIGHT, cfg.IMG_WIDTH]
    images = fluid.layers.data(name='img', shape=data_shape, dtype='float32')
    label = fluid.layers.data(name='label', shape=[cfg.IMG_HEIGHT, cfg.IMG_WIDTH], dtype='int64')
    predict = vgg16(images)
    
    cost = softmax_with_cross_entropy(predict, label)
    avg_cost = fluid.layers.mean(x=cost)
    optimizer = fluid.optimizer.Adam(learning_rate = cfg.TRAIN.LEARNING_RATE)
    optimizer.minimize(avg_cost)
    
    place = core.CPUPlace() if cfg.DEVICE == 'CPU' else core.CUDAPlace(0)
    exe = fluid.Executor(place)
    
    exe.run(fluid.default_startup_program())
    
    vgg16_weights = cfg.PRETRAINED_MODEL
    def if_exist(var):
        return os.path.exists(os.path.join(vgg16_weights, var.name)) 
    fluid.io.load_vars(exe, vgg16_weights, predicate=if_exist)

    fluid.memory_optimize(fluid.default_main_program())`

这边也准备直接读取预训练模型参数set到现有模型中，使用如下的方式load参数：
`def load_parameter(file_name):
    with open(file_name, 'rb') as f:
        f.read(16)  # skip header.
        return np.fromfile(f, dtype=np.float32)`
然后存在的问题是：
当load vgg16 fc7层weights时，得到的参数大小是4096*4096+3，但实际应该是4096*4096
当load vgg16 fc7层biases时，得到的参数大小是4096+2，但实际应该是4096

**Comment by gongweibao** [comment]
feel free to  reopen it!
