### ISSUE TITLE
是否支持多个使用多个模型进行预测？

### ISSUE THREAD

**Issue by yeyupiaoling** [PaddlePaddle/Paddle#10992]
比如我要做一个车的识别，我既要进行分类车牌的类型，同时也要识别车牌的的信息。
这样我就有两个模型，一个是分类模型，一个是CRNN模型，那么我是否能通过一次预测就可以使用两个模型进行预测。

**Comment by chengduoZH** [comment]
你这个issue里面提到了两个问题：
> 是否支持多个使用多个模型进行预测？

当前paddle是支持在一个进程中进行多模型预测的，可以通过启多个线程实现

> 是否能通过一次预测就可以使用两个模型进行预测。

这个是模型算法层面的问题，而不是paddle技术上的问题

**Comment by yeyupiaoling** [comment]
@chengduoZH 
>当前paddle是支持在一个进程中进行多模型预测的，可以通过启多个线程实现

这个我知道，可以在后端Python服务器中，使用多线程运行这两个加载这两个模型参数，通过调用接口一一识别。但是我现在的需求是要在Android端上同时运行两个模型预测，这里好像多不能用多线程了吧？

>是否能通过一次预测就可以使用两个模型进行预测。

我这句话的意思是，在加载合并模型的时候，同时加载两个模型参数文件，在预测infer的时候，输出两个模型预测的结果。

**Comment by chengduoZH** [comment]
> 在预测infer的时候，输出两个模型预测的结果。

这个问题是不是和这个issus是一个问题 https://github.com/PaddlePaddle/Paddle/issues/10990

**Comment by yeyupiaoling** [comment]
@chengduoZH 不是，那个是把参数文件和神经网络的分类器合并，最后直接加载合并模型就可以进行预测了。
这个是要在一张图像是完成两个识别任务，就是一张车的图片，我要通过分类识别车的类型，同时还要识别车牌号码。如果分开识别，那是很普通的事情，但不知道可不可以一起识别。

**Comment by chengduoZH** [comment]
> 这个是要在一张图像是完成两个识别任务，就是一张车的图片，我要通过分类识别车的类型，同时还要识别车牌号码。如果分开识别，那是很普通的事情，但不知道可不可以一起识别

你说的这个是模型算法层面的，需要用户自己想如何构建这样的模型

**Comment by yeyupiaoling** [comment]
@chengduoZH 
也不用那么复杂吧，比如我现在有一个车型分类的模型参数文件`vgg16.tar.gz`，和一个车牌识别的模型参数文件`crnn,tar.gz`，我只是想把它们一起使用而已。

**Comment by chengduoZH** [comment]
复述一下问题，你是想将图像A经过VGG16模型得到a1，同时将图像A经过CRNN模型得到a2，是吗？

**Comment by yeyupiaoling** [comment]
@chengduoZH 是的是的，有办法吗？

**Comment by yjj19920505** [comment]
有办法的呀，我做层次化分类的时候就把多个分类写在一个模型里边进行预测了

**Comment by yeyupiaoling** [comment]
@yjj19920505 你怎样做到的？

**Comment by yjj19920505** [comment]
比如说，我定义了网络1和网络2，那就分别会有两个cost以及两个output：cost1和cost2，cost_list = [cost1， cost2]，然后用这个cost列表定义参数parameters = paddle.parameters.create(cost_list)。
训练的时候依然是单独训练，可以得到两个网络的参数（每个网络各层定义得有unique标志）。
在预测的时候，首先把这两份参数载入，之后根据key一一对应赋值到parameters 里边，	
接着我们为每个output定义一个inferer，参数都是共享的这个parameter，output_layer则是需要的output，
 inferer = paddle.inference.Inference(
                    output_layer=output_dict[output_key], parameters=parameter)
之后在预测的时候根据需要取对应的inferer进行预测就可以了，这样就可以在一个模型里边进行多个预测。

**Comment by yeyupiaoling** [comment]
@yjj19920505 好像，谢谢您，我好好研究一下。
