### ISSUE TITLE
在场景文字识别中，在训练事件中评估结果没有输出。

### ISSUE THREAD

**Issue by yeyupiaoling** [PaddlePaddle/Paddle#11004]
我使用百度云的深度学习集群跑场景文字识别时，在训练过程中，没有输出评估器的结果：https://github.com/PaddlePaddle/models/blob/36e3fcd578e0e469d91b1257c27d627495c0b06b/scene_text_recognition/train.py#L75-L77

因为服务器没有warp-ctc，使用了百度开源的warp-ctc，地址如下：https://github.com/baidu-research/warp-ctc

输出结果如下：
```
Pass 0, batch 0, Samples 0, Cost 42.609291, Eval {}
...................................................................................................
Pass 0, batch 100, Samples 12800, Cost 0.494285, Eval {}
...................................................................................................
Pass 0, batch 200, Samples 25600, Cost 0.142084, Eval {}
...............
Test 0, Cost 0.105199, Eval {}
```

**Comment by chengduoZH** [comment]
你先检测一下模型的配置，在单机上运行有输出吗？

**Comment by yeyupiaoling** [comment]
@chengduoZH 
因为我本地没有GPU，无法进行测试。

**Comment by yeyupiaoling** [comment]
@chengduoZH 
可能是我使用了百度开源的warp-ctc，有没其他的warp-ctc？
