### ISSUE TITLE
快速入门的例子运行不了[通过pycharm安装的paddle]

### ISSUE THREAD

**Issue by ftry** [PaddlePaddle/Paddle#11008]
我通过pycharm安装了paddle

运行报错ImportError: libmklml_intel.so: cannot open shared object file: No such file or directory

但是我在lib里面找到了这个文件

这是怎么回事！！！

之前用pycharm安装了tensorflow都没有问题？？？

**Comment by chengduoZH** [comment]
抱歉 我们没在pycharm建立的虚拟环境中测试过

**Comment by chengduoZH** [comment]
@ftry 你可以改一下环境变量，LD_LIBRARY_PATH=(ibmklml_intel.so所在的路径):$LD_LIBRARY_PATH

**Comment by ftry** [comment]
@chengduoZH 这个在那里设置环境变量

**Comment by ftry** [comment]
@chengduoZH 谢谢你！我已经解决这个问题了！！！！

**Comment by ftry** [comment]
在pycharm里面安装paddle可能需要在其run/edit里面设置一个环境变量关于LD_LIBRARY_PATH

**Comment by chengduoZH** [comment]
@ftry 好的，多谢

**Comment by Albelt** [comment]
问题同上，我使用pip安装的paddlepaddle,安装成功了但是找不到ibmklml_intel.so这个文件，请问怎么解决？

**Comment by chengduoZH** [comment]
@Albelt 您可以看一下这里 http://www.paddlepaddle.org/docs/develop/documentation/zh/faq/build_and_install/index_cn.html#pippaddlepaddle-import-paddle-fluid-libmkldnn-so-libmklml-intel-so
