### ISSUE TITLE
Quick Start

### ISSUE THREAD

**Issue by harlanc** [PaddlePaddle/Paddle#1101]
In Quick Start->Preprocess data into standardized format
the following commad:
cd demo/quick_start
./data/get_data.sh
./preprocess.sh

the file preprocess.sh cannot be found in folder demo/quick_start??

**Comment by HugoLian** [comment]
We all have this here:
![image](https://cloud.githubusercontent.com/assets/22980558/21805760/d4fff032-d770-11e6-9f11-f01758ecae67.png)

If there is not, update your paddle hopefully works.

**Comment by harlanxu** [comment]
@HugoLian I cannot find it?My git branch is develop branch,and the code is latest.
the all preprocess.sh exist in the following path:

root@ubuntu:~/github/paddle# find . -name preprocess.sh
./third_party/glog/src/glog/src/windows/preprocess.sh
./demo/recommendation/preprocess.sh
./demo/sentiment/preprocess.sh
./demo/image_classification/preprocess.sh

**Comment by harlanxu** [comment]
@gangliao could you give me some advices?

**Comment by gangliao** [comment]
@harlanxu  It looks like you don't require preprocess.sh in develop branch.

If you check the latest get_data.sh https://github.com/PaddlePaddle/Paddle/blob/develop/demo/quick_start/data/proc_from_raw_data/get_data.sh , which already contains preprocess phase.
