### ISSUE TITLE
MKLDNN operator fusion in Fluid

### ISSUE THREAD

**Issue by tpatejko** [PaddlePaddle/Paddle#11015]
MKLDNN supports operator fusion either through special primitives (now deprecated `convolution_relu_forward`), or through special `post_ops` API introduced in MKLDNN v0.12. 

According to MKLDNN release notes, the following fusion scenarios are supported:
* forward convolution with eltwise for inference and training
* convolution with sum for inference
* batch normalization with eltwise for training

Does Fluid implement any fusion passes of existing GPU or CPU operators?

Some graph frameworks implement operator fusion using compiler passes for graph matching and graph rewriting. Does Fluid implement such infrastructure?

We would like to dive a bit deeper into graph compilation in Fluid. Where can we start?

**Comment by Superjomn** [comment]
About the graph frameworks:

In Inference, we are working on a [new graph framework](https://github.com/PaddlePaddle/Paddle/tree/develop/paddle/fluid/inference/analysis) which helps to support third-party engine such as TensorRT, and we plan to integrate some optimization such as op prune or memory reuse in the future.

It is still under development, the first milestone is to support TensorRT engine with sub-graphs.

**Comment by tpatejko** [comment]
@Superjomn thank you for your answer. I will take a look at it.

One more question: will the new graph framework support some form of graph pattern matching and graph rewriting?

**Comment by Superjomn** [comment]
Yes, It is designed to support rewriting the graph with wide optimization logics.

Take TensorRT as an example, this framework will extract a sub-graph that TensorRT supports, delete all the operators related from the original graph, and pass the sub-graph to TensorRT.

That phase rewrites the graph.

**Comment by tpatejko** [comment]
@Superjomn thanks a lot for the clarification!
