### ISSUE TITLE
在Fluid版本中，在预测的时候为什么还有克隆一个预测程序？

### ISSUE THREAD

**Issue by yeyupiaoling** [PaddlePaddle/Paddle#11022]
在以下的例子中，我看到在预测的时候，还克隆了一个预测程序，为什么要这做呢？
https://github.com/PaddlePaddle/Paddle/blob/60783a753adc0429d796c7b77f2f4eeea23a8e15/python/paddle/fluid/tests/book/test_image_classification.py#L225-L227

在此之前就有了一个预测程序，是从参数文件中加载的，如下：
https://github.com/PaddlePaddle/Paddle/blob/60783a753adc0429d796c7b77f2f4eeea23a8e15/python/paddle/fluid/tests/book/test_image_classification.py#L216-L217

同时也不知道它要在这里干什么，应该是比较吧：
https://github.com/PaddlePaddle/Paddle/blob/60783a753adc0429d796c7b77f2f4eeea23a8e15/python/paddle/fluid/tests/book/test_image_classification.py#L241-L242

在预测模型的时候，它为什么又要保存模型呢？
https://github.com/PaddlePaddle/Paddle/blob/60783a753adc0429d796c7b77f2f4eeea23a8e15/python/paddle/fluid/tests/book/test_image_classification.py#L246-L248

**Comment by kuke** [comment]
https://github.com/PaddlePaddle/Paddle/blob/60783a753adc0429d796c7b77f2f4eeea23a8e15/python/paddle/fluid/tests/book/test_image_classification.py#L224

注意这一行的注释，用```inference_transpiler_program```的主要目的是加速计算，后面的比较也是为了验证```inference_transpiler_program```的正确性，最后保存的夜市```inference_transpiler_program```。

**Comment by yeyupiaoling** [comment]
@kuke 都是同一个参数文件加载出来的程序，难道准确性还会不一样的？最后保存的参数文件跟之前的有会优化多少？

**Comment by luotao1** [comment]
@yeyupiaoling 因为两个program都在一个scope里，如果不clone的话，原始program在scope里的一些变量就直接发生了变化，会导致结果出错。更多细节可以看下 https://github.com/PaddlePaddle/Paddle/pull/9792 里的评论。

> 最后保存的参数文件跟之前的有会优化多少？

请问是指速度方面么？the elapsed time on ResNet (test_inference_image_classification) is from 11.2s to 9.3s, about 10% speedup on inference.

**Comment by luotao1** [comment]
因为将batch norm的参数（weight和bias）都融合进conv的参数（weight和bias）中了，所以在预测的时候去掉了batch_norm（如果之前的conv没有bias，会增加一部分bias的计算），速度当然会快。

**Comment by yeyupiaoling** [comment]
好的，了解了，谢谢 @luotao1
