### ISSUE TITLE
在Fluid版本下，使用C++预测图像的一些问题？

### ISSUE THREAD

**Issue by yeyupiaoling** [PaddlePaddle/Paddle#11023]
我在文档中看到这个例子https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/fluid/inference/tests/book/test_inference_image_classification.cc

它是一个图像分类的C++预测程序，但我在里面好像是看到两预测程序，
https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/fluid/inference/tests/book/test_inference_image_classification.cc#L26-L67

https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/fluid/inference/tests/book/test_inference_image_classification.cc#L69-L100

这个不知道是不是分CPU和GPU的进行预测。如果我但是只是使用https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/fluid/inference/tests/book/test_inference_image_classification.cc#L26-L67
是否可以？

如果我想run一下这个dome，该如何做呢？

**Comment by kuke** [comment]
是的，这是单测程序，区分CPU和GPU。编译的时候如果没有用GPU，就只会执行L26-L67，用ctest跑单测就是运行这个测试

**Comment by yeyupiaoling** [comment]
好像的，谢谢@kuke
