### ISSUE TITLE
Update the document for build scripts 

### ISSUE THREAD

**Issue by kuke** [PaddlePaddle/Paddle#11031]
#10721 changed the scripts to build paddle, but does not update the document for them yet. Users are complaining that they fail to build paddle android. Please remember to update the document at the same time whenever the code is changed.

**Comment by wanglei828** [comment]
@kuke Could you point out which documents need to be updated? I think I have fixed build related documents.

**Comment by kuke** [comment]
@wanglei828 It is the problem of building paddle android. Some users were following the [out-of-date document](https://github.com/PaddlePaddle/Paddle/blob/f0548679b3e3f1194591e80af8a4114dc7da10e5/doc/mobile/cross_compiling_for_android_cn.md#编译paddlepaddle-c-api库) and they failed.
