### ISSUE TITLE
paddle op开发编译速度疑问？

### ISSUE THREAD

**Issue by zhxfl** [PaddlePaddle/Paddle#11088]
使用paddle进行op开发，目前知道，如果直接开发op可以使用make opxx进行编译，然后打包成python whl，但是开发的过程中需要再架构中插入日志，去了解架构，编译依赖比较大，编译速度慢，想请教一下paddle的开发者怎么处理这个问题的？

**Comment by zhxfl** [comment]
开多线程编译经常遇到这个问题
<built-in>:0:0: fatal error: when writing output to : No space left on device
但是切换成单线程就正常编译下来了

**Comment by luotao1** [comment]
> 如果直接开发op可以使用make opxx进行编译，然后打包成python whl

这是可以的。开发op的时候不需要每次都打包。请参考 http://www.paddlepaddle.org/documentation/docs/zh/1.0/advanced_usage/development/new_op.html#%E7%BC%96%E8%AF%91
> :0:0: fatal error: when writing output to : No space left on device

这个是你的磁盘空间不够了。

> 编译依赖比较大

第三方依赖编译过一次，后续都不用编译了。

> 编译速度慢

- 请问你的编译命令是什么呢，用docker编译还是本地编译，有使用ccache么？
- 请问是编译fluid版本还是v2版本，cpu还是gpu？

**Comment by zhxfl** [comment]
编译命令是make -j，机器是24核的，版本是fluid v2，本地编译。目前最大的问题还是修改了一些头文件，比如op_desc.h，造成编译很慢，磁盘空间是否的，tmp目录也有几Gb的剩余空间

**Comment by luotao1** [comment]
> 编译命令是make -j

cmake选项是什么？

> 版本是fluid v2

是fluid还是v2？

> 有使用ccache么

请回答。

> 目前最大的问题还是修改了一些头文件，比如op_desc.h，造成编译很慢

第一次编译会稍慢，后面会快。

> cpu还是gpu

请回答。

> 编译很慢

请给出具体时间，和机器配置。

**Comment by zhxfl** [comment]
目前暂时通过避免修改公用的头文件来减少编译依赖，可以节省编译时间，问题不大；多谢~
