### ISSUE TITLE
[paddle v2] softmax层输出和不等于1.

### ISSUE THREAD

**Issue by shiyazhou121** [PaddlePaddle/Paddle#11084]
问题：使用infer接口输出的softmax层结果和不等于1.
以下是我的网络配置等：
![image](https://user-images.githubusercontent.com/15082798/40772934-f65ab912-64f3-11e8-91c1-2633f8ae55c1.png)
我的infer代码：
![image](https://user-images.githubusercontent.com/15082798/40772958-0666a7ee-64f4-11e8-962e-031a7a99f7e8.png)
infer的输出结果：
![image](https://user-images.githubusercontent.com/15082798/40773061-5ad58070-64f4-11e8-9e81-8f28c889cb62.png)

结果分析：
infer中使用的param.tar文件是使用图1的网络配置训练出来的。
从结果中可以很明显看出，softmax层输出和不等于1，请问我的哪个地方出错了？？求助...

**Comment by kuke** [comment]
我算了一下，求和结果还真等于1，如下：
```python
>>> A = [0.0839, 0.0793, 0.0674, 0.0589, 0.0781, 0.0700, 0.0614, 0.0787, 0.0761, 0.0767, 0.0816, 0.0535, 0.0622, 0.0721]
>>> sum(A)
0.9999000000000002
>>>
```

**Comment by shiyazhou121** [comment]
@kuke 谢谢了，辛苦解答，尴尬。。。

**Comment by kuke** [comment]
@shiyazhou121 应该是你估算错了:-)
