### ISSUE TITLE
demo/quick_start/preprocess.sh takes hours on a VM with 1 CPU

### ISSUE THREAD

**Issue by wangkuiyi** [PaddlePaddle/Paddle#111]
I checked with Yi Yang that on his powerful desktop, it takes a few minutes. Anyway, as a _quick start_, is it supposed to be _quick_? :-)

**Comment by reyoung** [comment]
可能的解决办法是。我们选择一个小的数据集，去掉一些预处理内容。

1、小的数据集。 quick start使用的是亚马逊电子产品的数据，但是同样网页中提供了一些更小的数据集。

2、去掉一些预处理内容。去掉英文的分词和标点符号处理(这一块是用perl去做的)。可以直接在python里面repleace一些基础的标点符号，分词等等。不一定需要这么专业。

这个解决方案的问题在于：

小的数据集可能会导致复杂模型的效果不一定比简单模型的效果好。

**Comment by backyes** [comment]
@wangkuiyi @reyoung 这个issue提到的preprocess问题，似乎近期会有解决方案（似乎要提供已经处理好的数据）。

@qingqing01 @luotao1 谁知道的， 麻烦update一下，比如如果有pr，可以关联过来。

**Comment by reyoung** [comment]
@qingqing01 Should this issue be closed or not? Is it resolved?

**Comment by qingqing01** [comment]
https://github.com/PaddlePaddle/Paddle/pull/573   这里PR提供了预处理好的数据，只需要下载数据解压即可。 可以不经过预处理脚本处理，这样可以省去预处理时间。
