### ISSUE TITLE
Fluid模型参数解析和加载

### ISSUE THREAD

**Issue by chengyuz** [PaddlePaddle/Paddle#11103]
这边先使用链接中脚本（https://github.com/PaddlePaddle/models/tree/develop/fluid/image_classification/caffe2fluid）将caffe model转化为fluid模型，然后解析VGG16中模型参数：
`
def load_parameter(file_name):
    with open(file_name, 'rb') as f:
        f.read(16)  # skip header.
        return np.fromfile(f, dtype=np.float32)
`
发现：
当load vgg16 fc7层weights时，得到的参数大小是4096*4096+3，但实际应该是4096 x 4096
当load vgg16 fc7层biases时，得到的参数大小是4096+2，但实际应该是4096

还有个问题：fluid.layers.conv2d中weights和biases支持使用numpy直接进行初始化么？而不是使用框架提供的Xavier等初始化，谢谢！

**Comment by guoshengCS** [comment]
fluid.layers.conv2d中weights和biases是支持使用numpy初始化的，在layer定义时在ParamAttr里设置param name，然后在初始化模型结束或load模型后参照如下方式设置下：
```
        param = fluid.global_scope().find_var(param_name).get_tensor()
        param.set(np_data, place)
```

**Comment by chengyuz** [comment]
谢谢！之前首先将caffe模型转化为对应fluid模型存在问题，直接解析然后加载caffe中模型参数就可以了

**Comment by ktlichkid** [comment]
Seems the issue is already resolved. Please feel free to reopen it if the issue still exists.
