### ISSUE TITLE
物体识别不同尺寸的图片是怎么处理的呢？？？

### ISSUE THREAD

**Issue by jidebingfeng** [PaddlePaddle/Paddle#11110]
物体识别不同尺寸的图片是怎么处理的呢？？？
手写体识别的图片都是同样大小的，如果样本图片的大小不一样应该怎么处理？模型可以兼容还是需要缩放或者是剪切？这个需要预先处理吗？有没有相关的教程或者简单一点的示例？

**Comment by guoshengCS** [comment]
不同尺寸的图片训练的话一般需要裁剪成相同大小的，教程示例的话可以参考这里 https://github.com/PaddlePaddle/models/blob/develop/fluid/object_detection/reader.py#L111 ，包括了数据预处理的内容

**Comment by jidebingfeng** [comment]
好的，谢谢！
