### ISSUE TITLE
MPI提交任务一直失败

### ISSUE THREAD

**Issue by lunanzhao** [PaddlePaddle/Paddle#11125]
跑word2vec 的demo, 提交MPI任务一直失败， 辛苦帮看下什么原因， 谢谢。 

./paddle cluster_train \
  --config thirdparty/train.py \
  --use_gpu cpu \
  --use_remote_sparse 1 \
  --time_limit 00:30:00 \
  --submitter zhaolunan \
  --num_nodes 5 \
  --job_priority normal \
  --trainer_count 1 \
  --num_passes 1 \
  --fs_name afs://xingtian.afs.baidu.com:9902 \
  --fs_ugi ***,***\
  --train_data_path /user/mlarch_rd/zhaolunan/paddle/w2v_demo/data/train \
  --test_data_path  /user/mlarch_rd/zhaolunan/paddle/w2v_demo/data/test \
  --output_path /user/mlarch_rd/zhaolunan/paddle/w2v_demo/output/demo2 \
  --where yq01-hpc-lvliang-cpu-smart2_fcr-10G_cluster \
  --thirdparty ./thirdparty \
  --job_name feed_development_zhaolunan_henghua_w2v 

失败信息：没看到啥有用的信息 

[yq01-hpc-lvliang-i1700.yq01.baidu.com:23053] [[28082,0],2] routed:binomial: Connection to lifeline [[28082,0],0] lost

task_main.log
2018/06/01 16:33:26| Failed to do /usr/bin//matrix_jail -s 1.app-user-20180601155016-23097--feed_development_zhaolunan_henghua_w2v cd /home/disk1/normandy/maybach/app-user-20180601155016-23097 && nice -n 15 /bin/sh -c 'bash script/hang.sh'
|2018/06/01 16:33:26| matrix_jail returns: 137

**Comment by guoshengCS** [comment]
集群问题（除receiver外），还请内网提交JIRA，地址：http://10.100.68.32:8080/browse/MPISUPPORT/
