### ISSUE TITLE
多机训练结束时core掉

### ISSUE THREAD

**Issue by kolinwei** [PaddlePaddle/Paddle#11128]
Pass 0, batch 78, loss [3.1757193 2.9776196 2.5085354 2.6202035 2.7554896 2.7989535 2.605354
 2.9289262]
Pass 0, batch 79, loss [2.6981301 2.8381817 3.1007226 2.9154088 3.0282474 2.8358479 2.740921
 2.5623817]

Total examples: 38400, total time: 59.58084, 644.50253 examples/sed

pure virtual method called
terminate called without an active exception
*** Aborted at 1527853467 (unix time) try "date -d @1527853467" if you are using GNU date ***
PC: @                0x0 (unknown)
*** SIGABRT (@0x1886) received by PID 6278 (TID 0x7fd2f8871700) from PID 6278; stack trace: ***
    @     0x7fd2f844a390 (unknown)
    @     0x7fd2f80a4428 gsignal
    @     0x7fd2f80a602a abort
    @     0x7fd2f0a6c92d __gnu_cxx::__verbose_terminate_handler()
    @     0x7fd2f0a6a996 __cxxabiv1::__terminate()
    @     0x7fd2f0a6a9e1 std::terminate()
    @     0x7fd2f0a6b48f __cxa_pure_virtual
    @     0x7fd2a1951176 grpc::Channel::~Channel()
    @     0x7fd2a1951229 grpc::Channel::~Channel()
    @     0x7fd2a0bb2259 std::_Sp_counted_base<>::_M_release()
    @     0x7fd2a181b2c1 std::_Rb_tree<>::_M_erase()
    @     0x7fd2a181b2af std::_Rb_tree<>::_M_erase()
    @     0x7fd2a191e003 std::unique_ptr<>::~unique_ptr()
    @     0x7fd2f80a8ff8 (unknown)
    @     0x7fd2f80a9045 exit
    @           0x51dc1f Py_Exit
    @           0x51b1b7 (unknown)
    @           0x51aadd PyErr_PrintEx
    @           0x4309d5 (unknown)
    @           0x493ae2 Py_Main
    @     0x7fd2f808f830 __libc_start_main
    @           0x4933e9 _start
    @                0x0 (unknown)
Aborted

**Comment by kolinwei** [comment]
pserver

FLAGS_fraction_of_gpu_memory_to_use=0.0 \
PADDLE_TRAINING_ROLE=PSERVER \
PADDLE_PSERVER_PORT=5002 \
PADDLE_PSERVER_IPS=10.0.0.1,10.0.0.2,10.0.0.3,10.0.0.4 \
PADDLE_TRAINERS=4 \
PADDLE_CURRENT_IP=10.0.0.4 \
PADDLE_TRAINER_ID=3 \
python fluid_benchmark.py --model resnet  --data_set flowers \
--batch_size 512 --device GPU \
--gpus 8 --iterations 11 \
--update_method pserver

train
PADDLE_TRAINING_ROLE=TRAINER \
PADDLE_PSERVER_PORT=5002 \
PADDLE_PSERVER_IPS=10.0.0.1,10.0.0.2,10.0.0.3,10.0.0.4 \
PADDLE_TRAINERS=4 \
PADDLE_CURRENT_IP=10.0.0.4 \
PADDLE_TRAINER_ID=3 \
python fluid_benchmark.py --model resnet  --data_set flowers \
--batch_size 512 --device GPU \
--gpus 8 --iterations 11 \
--use_recordio
--update_method pserver

**Comment by typhoonzero** [comment]
Duplicate: https://github.com/PaddlePaddle/Paddle/issues/11123
