### ISSUE TITLE
tensorflow转paddle遇到的问题

### ISSUE THREAD

**Issue by chenbblei** [PaddlePaddle/Paddle#11138]
tensorflow中有这么一段代码：
embedding = tf.get_variable('char_embedding', shape=(self.output_size, self.emb_size), dtype=tf.float32,
                                initializer=tf.random_uniform_initializer(-0.1, 0.1))
inputs = tf.nn.embedding_lookup(embedding, self.x)

我要改成paddle该怎么修改

**Comment by JiayiFeng** [comment]
我的理解是，你的需求是做一个简单的embedding。
在Fluid中，直接使用layers.embedding即可，embedding的可训练的词表会自动生成：

```python
param_attr = fluid.ParamAttr(name="char_embedding", initializer=fluid.UniformInitializer(low=-0.1, high=0.1))
inputs = fluid.layers.embedding(input=self.x, size=(self.output_size, self.emb_size), 
                                                      param_attr=param_attr)
```

**Comment by chenbblei** [comment]
@JiayiFeng 谢谢
