### ISSUE TITLE
请教一下trainer_count的设置问题

### ISSUE THREAD

**Issue by reddancer** [PaddlePaddle/Paddle#11150]
paddle版本：v2 0.11
服务器cpu配置：num_cores=16, num_processors=32
把batch_size=50 trainer_count=10，模型会一直卡着不动，
如果设置成batch_size=250 trainer_count=10，模型就会正常执行，但感觉好像是在一个cpu上执行的，也就是top时，看到的P那一项，都是同一个数字。
我不太清楚trainer_count的设置规则，还有看paddle的init里面有一个MKL_NUM_THREADS及OMP_NUM_THREADS设置，不明白之间的联系，感谢不吝指教。

**Comment by JiayiFeng** [comment]
trainer_count的数目就是线程数，建议设置成和CPU的物理核数一样。要确认是否是在多个核上执行可以使用`htop`命令看一下各个核的占用情况。
MKL_NUM_THREADS和OMP_NUM_THREADS分别是MKL库的内部线程数和openmp的线程数。V2中不需要管这两个参数，系统会自动进行匹配。

**Comment by luotao1** [comment]
你可以分别试试trainer_count=1，2，4，8。10的话，无法被16整除。

**Comment by reddancer** [comment]
为什么是trainer_count是5可以正常跑，是10就跑不动了呢？，物理cpu是2，cores是16个，proccessors是32个

**Comment by luotao1** [comment]
您好，建议选择能被16整除的trainer count，这样有利于每个core的负载均衡。
