### ISSUE TITLE
Paddle CUDA

### ISSUE THREAD

**Issue by hedaoyuan** [PaddlePaddle/Paddle#1116]
**Refactoring Paddle CUDA**

### paddle/cuda
当前Paddle CUDA中主要包含以下几部分内容：
1. A CUDA engine；
2. 对cublas、cudnn函数的封装；
3. 一些Sparse matrix、CNN、RNN、Tensor Computation相关的CUDA实现；
4. Some utility code;

### About Refactoring
1. Sparse matrix、CNN、RNN Computation相关的code在Paddle Function相关工作中重构，并移入paddle/function目录；
2. Tensor Computation相关的code在Paddle Tensor Computation相关工作中重构；
3. 与CUDA无关的utility code移入paddle/utils目录；
4. paddle/cuda目录下面的代码风格与Paddle中其他代码风格不一致，重构的时候可以参考其他代码风格进行修改；

**Comment by hedaoyuan** [comment]
**Some New Features**

**Comment by gangliao** [comment]
感觉cuda目录也不能叫cuda了

可以叫做： 
kernels
├── cpu
│   ├── avx
│   └── sse
└── gpu

**Comment by hedaoyuan** [comment]
Close the issue, since paddle has been in the reconstruction.
