### ISSUE TITLE
上采样

### ISSUE THREAD

**Issue by Leezhaohui** [PaddlePaddle/Paddle#11179]
请问PaddlePaddle0.12版本有能实现上采样的函数吗，例如反卷积，反池化之类的

**Comment by jacquesqiao** [comment]
你问的是fluid相关的功能么？

**Comment by Leezhaohui** [comment]
v2，不是fluid

**Comment by jacquesqiao** [comment]
有的 http://paddlepaddle.org/docs/0.11.0/api/en/api/v2/config/layer.html#permalink-10-img_conv  
image_conv layer有个参数 trans，如果设置成true，就是反卷积。

**Comment by jacquesqiao** [comment]
https://github.com/PaddlePaddle/Paddle/blob/d02a68c4472d3b85559f82c026896bf2cf563b07/python/paddle/trainer_config_helpers/layers.py#L3021

**Comment by yiakwy** [comment]
@jacquesqiao Hello 现在在fluid 1.5 版本里面怎么实现 “上采样” Upsampling 呢？ 文档里面找不到相关描述。
