### ISSUE TITLE
如何将一个序列化的层转成卷积层

### ISSUE THREAD

**Issue by chenbblei** [PaddlePaddle/Paddle#11178]
如，我有一个(1,28乘以32乘以51)的层，我想把它转化成height = 32, num_filters=28,width=51的卷积层，该怎么写代码

**Comment by jacquesqiao** [comment]
> 我有一个(1,28乘以32乘以51)的层

这是一个什么层？

**Comment by jacquesqiao** [comment]
v2接口还是fluid呀

**Comment by chenbblei** [comment]
@jacquesqiao v2

**Comment by chenbblei** [comment]
@jacquesqiao 人呢

**Comment by chenbblei** [comment]
竟然问着问着就没人回答了，服了

**Comment by jacquesqiao** [comment]
假如FC的weight的shape是M*N， 转成conv之后就是output_channel = M, input_channel =N, filer_h/w = 1
