### ISSUE TITLE
用resnet网络GPU训练model，初始化后出core

### ISSUE THREAD

**Issue by qubingxin** [PaddlePaddle/Paddle#1118]
用model_zoo里的res_net_50训练，参数初始化后出core：

*** Aborted at 1484105923 (unix time) try "date -d @1484105923" if you are using GNU date ***
PC: @ 0x628301 paddle::CudnnConvLayer::forward()
*** SIGSEGV (@0x8) received by PID 19411 (TID 0x7f48cde52700) from PID 8; stack trace: ***
@ 0x7f4904f67160 (unknown)
@ 0x628301 paddle::CudnnConvLayer::forward()
@ 0x701ec1 paddle::NeuralNetwork::forward()
@ 0x6ec951 paddle::GpuSyncThread::forward()
@ 0x6eca6d paddle::GpuSyncThread::computeThread()
@ 0x7f49047fe8a0 execute_native_thread_routine
@ 0x7f4904f5f1c3 start_thread
@ 0x7f490427212d __clone
./train.sh: line 195: 19411 Segmentation fault (core dumped) PYTHONPATH=./paddle:$PYTHONPATH GLOG_logtostderr=0 GLOG_log_dir="./log" ./paddle_trainer --num_gradient_servers=${OMPI_COMM_WORLD_SIZE} --trainer_id=${OMPI_COMM_WORLD_RANK} --pservers=$ipstring --rdma_tcp=${rdma_tcp} --nics=${nics} ${train_arg} --config=conf/trainer_config.conf --save_dir=./${save_dir} ${extern_arg}
+ '[' 139 -ne 0 ']'
+ kill_pserver2_exit
+ ps aux
+ grep paddle_pserver2
+ grep paddle_cluster_job
+ grep -v grep
+ cut -c10-14
+ xargs kill -9
+ log_fatal 'paddle_trainer failed kill paddle_pserver2 and exit'
+ echo '[./common.sh : 394] [kill_pserver2_exit]'
[./common.sh : 394] [kill_pserver2_exit]
+ echo '[FATAL]: paddle_trainer failed kill paddle_pserver2 and exit'
[FATAL]: paddle_trainer failed kill paddle_pserver2 and exit
+ get_stack
+ set +x

*********************Shell Script Stack Trace********************
@: [./log.sh: 35] log_fatal
@: [./common.sh: 394] kill_pserver2_exit
@: [./train.sh: 198] main

+ exit 1
-------------------------------------------------------
Primary job terminated normally, but 1 process returned
a non-zero exit code.. Per user-direction, the job has been aborted.
-------------------------------------------------------
--------------------------------------------------------------------------
mpirun detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

Process name: [[42403,1],0]
Exit code: 1

**Comment by backyes** [comment]
@qubingxin 


* @qubingxin 请先确认单机能否运行，并提供git SHA1版本

* 待 @qubingxin 确认单机能运行，只是集群不work的话，请  @luotao1 能否帮忙确认model zoo是否依赖具体paddle版本。

* 如果依赖具体版本，请 @qubingxin 参照以下操作： 
demo所在的paddle版本git SHA1和集群的paddle的版本的git SHA1保持一致。如果不一致，请参考内部集群文档提供的方法， 比如使用定制方法跑集群。 
另外也可以根据集群默认的paddle版本的git SHA1， 选择下载paddle源码的model zoo。

**Comment by qingqing01** [comment]
mode_zoo里提供的是配置是用于测试、提特征。实际用到训练中，请注意Inputs/Outputs是否正确配置。 一般第一层conv出错的，很大原因是因为Inputs里的顺序和DataProvider配置的顺序不一致问题导致，请仔细检查。

**Comment by qubingxin** [comment]
@backyes @qingqing01 出现如上错误，用的是旧版的receiver和旧版的define_py_data_source，更新到新的receiver和define_py_data_source2, 不再出现该错误，报了另一个错误：http://yq01-sys-hic-k4004.yq01.baidu.com:8880/output/list/4869
F0111 13:00:29.772729 11647 MemoryHandle.cpp:41] Check failed: size != 0 allocate 0 bytesF0111 13:00:29.772905 11643 MemoryHandle.cpp:41] Check failed: size != 0 allocate 0 bytes 
@qingqing01  出现CudnnConvLayer错误时，DataProvider还是GeneralJpegDataProvider(PyDataProviderBase)，跟新的define_py_data_source2不一样

**Comment by qubingxin** [comment]
目前的DataProvider里用的是yield的字典形式，报的错是F0111 13:00:29.772729 11647 MemoryHandle.cpp:41] Check failed: size != 0 allocate 0 bytesF0111 13:00:29.772905 11643 MemoryHandle.cpp:41] Check failed: size != 0 allocate 0 bytes

**Comment by qubingxin** [comment]
目前resnet本地训练一个model的错误是：
I0111 20:23:47.859899 16032 GradientMachine.cpp:135] Initing parameters..
I0111 20:23:49.588367 16032 GradientMachine.cpp:142] Init parameters done.
I0111 20:23:49.718030 16053 ThreadLocal.cpp:38] thread use undeterministic rand seed:16054
Thread [139636794693504] Forwarding conv1_conv, input,
*** Aborted at 1484137431 (unix time) try "date -d @1484137431" if you are using GNU date ***
PC: @           0x6c6d14 paddle::ExpandConvLayer::forward()
*** SIGSEGV (@0x8) received by PID 16032 (TID 0x7effb98b9780) from PID 8; stack trace: ***
    @     0x7effb9493160 (unknown)
    @           0x6c6d14 paddle::ExpandConvLayer::forward()
    @           0x5dc460 paddle::NeuralNetwork::forward()
    @           0x5d7823 paddle::GradientMachine::forwardBackward()
    @           0x719283 paddle::TrainerInternal::forwardBackwardBatch()
    @           0x719d2f paddle::TrainerInternal::trainOneBatch()
    @           0x7173d6 paddle::Trainer::trainOneDataBatch()
    @           0x7178c9 paddle::Trainer::trainOnePass()
    @           0x718495 paddle::Trainer::train()
    @           0x5986aa main
    @     0x7effb82b8bd5 __libc_start_main
    @           0x5a45f5 (unknown)
/home/qubingxin/qbx/source_code/paddle_internal_release_tools/idl/paddle/output/bin/paddle_local: line  16032 Segmentation fault      ${DEBUGGER} $MYDIR/../opt/paddle/bin/paddle_trainer ${@:2}
 与集群上都出现了Thread [140291147298560] Forwarding conv1_conv, input, 目测是均是第一个卷积层出错了。PS. 集群log地址：http://yq01-sys-hic-k4004.yq01.baidu.com:8880/output/list/4869

**Comment by hedaoyuan** [comment]
Close this issue, due to we have fixed the error `Check failed: size != 0 allocate 0 bytes` when trainer_count > 1.
