### ISSUE TITLE
large memory used when infer

### ISSUE THREAD

**Issue by tensor-tang** [PaddlePaddle/Paddle#11185]
This is an issue of NLP online service.

When run inference, the memory usage is always kept as about 6G, which is definitely larger than actually needed.

![image](https://user-images.githubusercontent.com/21351065/40960246-c11c16ec-68d1-11e8-92d2-e7f3d4bb82f3.png)

**Comment by ChinaLiuHao** [comment]
I meet this situation too. In addition, when i use the inference by multi-thread way with "export OPENBLAS_NUM_THREADS=1", the program may end with the "Aborted" error!

**Comment by tensor-tang** [comment]
@ChinaLiuHao 
And as an addition, the "Abort" error is **randomly** encountered, not always appears.

**Comment by luotao1** [comment]
The OCR CRNN_CTC service also has a large memory:
![image](https://user-images.githubusercontent.com/6836917/40968298-d1e0c28c-68e7-11e8-9c91-c66be03617ac.png)

**Comment by tensor-tang** [comment]
After debugging we can found there is a flag to choose how much memory we would like to use at the first time. Default it would use about 3.2%(1/32) of your total memory.

usage:
```
your_app --fraction_of_cpu_memory_to_use=0.1 # it would use 3.2% * 0.1 of total
```

The track back should be like this:

https://github.com/PaddlePaddle/Paddle/blob/666c94e3be10c2290eb143fdff208684e9ee34fe/paddle/fluid/platform/cpu_info.cc#L26-L28

https://github.com/PaddlePaddle/Paddle/blob/666c94e3be10c2290eb143fdff208684e9ee34fe/paddle/fluid/platform/cpu_info.cc#L54-L58

https://github.com/PaddlePaddle/Paddle/blob/666c94e3be10c2290eb143fdff208684e9ee34fe/paddle/fluid/platform/cpu_info.cc#L65-L69

https://github.com/PaddlePaddle/Paddle/blob/666c94e3be10c2290eb143fdff208684e9ee34fe/paddle/fluid/memory/malloc.cc#L32-L36

**Comment by tensor-tang** [comment]
@ChinaLiuHao
The abort issue, we can open another issue to discuss it. Thanks.
