### ISSUE TITLE
paddle  gpu 初始化报错

### ISSUE THREAD

**Issue by jiaozhusos** [PaddlePaddle/Paddle#11195]
如下：
cuda 版本为8.0，cudnn版本为5.1.10，报了以下的错

paddle.init(use_gpu=True, trainer_count=1)
I0605 01:44:45.392531 26917 Util.cpp:166] commandline:  --use_gpu=True --trainer_count=1 
F0605 01:44:46.962916 26917 hl_cuda_cudnn.cc:171] Check failed: (cudnn_cuh_major < 4 && cudnn_dso_major < 4) || (cudnn_cuh_major == cudnn_dso_major) [cudnn init] libcudnn v5 with header v7 unmatched!
PaddlePaddle Requirement: (header v[2-3] with libcudnn v[2-3]) Or (header v4 with libcudnn v4) Or (header v5 with libcudnn v5) Or(header v6 with libcudnn v6).
*** Check failure stack trace: ***
    @     0x7f4f6549ef8d  google::LogMessage::Fail()
    @     0x7f4f654a2a3c  google::LogMessage::SendToLog()
    @     0x7f4f6549eab3  google::LogMessage::Flush()
    @     0x7f4f654a3f4e  google::LogMessageFatal::~LogMessageFatal()
    @     0x7f4f65454eaf  hl_cudnn_init()
    @     0x7f4f6545ced5  hl_create_global_resources()
    @     0x7f4f6545d681  hl_specify_devices_start()
    @     0x7f4f6545da3d  hl_start()
    @     0x7f4f653e7406  paddle::initMain()
    @     0x7f4f65486ac1  initPaddle()
    @     0x7f4f650331f9  _wrap_initPaddle
    @     0x7f4fa4152210  PyEval_EvalFrameEx
    @     0x7f4fa41554e9  PyEval_EvalCodeEx
    @     0x7f4fa41529b8  PyEval_EvalFrameEx
    @     0x7f4fa41554e9  PyEval_EvalCodeEx
    @     0x7f4fa40de28a  function_call
    @     0x7f4fa40b97a3  PyObject_Call
    @     0x7f4fa414e4be  PyEval_EvalFrameEx
    @     0x7f4fa41554e9  PyEval_EvalCodeEx
    @     0x7f4fa41529b8  PyEval_EvalFrameEx
    @     0x7f4fa41554e9  PyEval_EvalCodeEx
    @     0x7f4fa415570a  PyEval_EvalCode
    @     0x7f4fa416e9cd  run_mod
    @     0x7f4fa4170a0e  PyRun_InteractiveOneFlags
    @     0x7f4fa4170baf  PyRun_InteractiveLoopFlags
    @     0x7f4fa41711f0  PyRun_AnyFileExFlags
    @     0x7f4fa4182f8c  Py_Main
    @     0x7f4fa339a830  __libc_start_main
    @     0x55af81fa08bf  (unknown)
Aborted (core dumped)

**Comment by jacquesqiao** [comment]
自己编译的paddle么?

**Comment by jacquesqiao** [comment]
```
libcudnn v5 with header v7 unmatched!
```
从日志可以看出来，编译paddle的时候和运行paddle的时候cudnn版本不一致。

**Comment by jiaozhusos** [comment]
cudnn5和6都试过，都会报同样的不匹配错误，但是同样地,tensorflow就没有问题，也不知道到底是为什么

**Comment by Bigwode** [comment]
遇到同样的问题，运行自带的model的时候显示出错。
I0714 15:32:51.136124  7057 Util.cpp:166] commandline:  --use_gpu=True --trainer_count=1 
F0714 15:32:51.510835  7057 hl_cuda_cudnn.cc:171] Check failed: (cudnn_cuh_major < 4 && cudnn_dso_major < 4) || (cudnn_cuh_major == cudnn_dso_major) [cudnn init] libcudnn v6 with header v7 unmatched!
PaddlePaddle Requirement: (header v[2-3] with libcudnn v[2-3]) Or (header v4 with libcudnn v4) Or (header v5 with libcudnn v5) Or(header v6 with libcudnn v6).
*** Check failure stack trace: ***
    @     0x7f2fe6acc13d  google::LogMessage::Fail()
    @     0x7f2fe6acfbec  google::LogMessage::SendToLog()
    @     0x7f2fe6acbc63  google::LogMessage::Flush()
    @     0x7f2fe6ad10fe  google::LogMessageFatal::~LogMessageFatal()
    @     0x7f2fe6a7e419  hl_cudnn_init()
    @     0x7f2fe6a86cae  hl_create_global_resources()
    @     0x7f2fe6a873a9  hl_specify_devices_start()
    @     0x7f2fe6a877cd  hl_start()
    @     0x7f2fe6a0ff0a  paddle::initMain()
    @     0x7f2fe6ab3b41  initPaddle()
    @     0x7f2fe66250e9  _wrap_initPaddle
    @     0x7f302c6f3bad  PyEval_EvalFrameEx
    @     0x7f302c6f4c3e  PyEval_EvalCodeEx
    @     0x7f302c6f41f7  PyEval_EvalFrameEx
    @     0x7f302c6f4c3e  PyEval_EvalCodeEx
    @     0x7f302c66fa61  function_call
    @     0x7f302c63fe93  PyObject_Call
    @     0x7f302c6f1886  PyEval_EvalFrameEx
    @     0x7f302c6f4c3e  PyEval_EvalCodeEx
    @     0x7f302c6f41f7  PyEval_EvalFrameEx
    @     0x7f302c6f4c3e  PyEval_EvalCodeEx
    @     0x7f302c6f41f7  PyEval_EvalFrameEx
    @     0x7f302c6f4c3e  PyEval_EvalCodeEx
    @     0x7f302c6f4d52  PyEval_EvalCode
    @     0x7f302c715450  PyRun_FileExFlags
    @     0x7f302c71562f  PyRun_SimpleFileExFlags
    @     0x7f302c72afd4  Py_Main
    @     0x7f302b91f830  __libc_start_main
    @           0x400729  (unknown)
已放弃 (核心已转储)

**Comment by luotao1** [comment]
>  [cudnn init] libcudnn v6 with header v7 unmatched!

@Bigwode 从日志看出来，cudnn的lib为v6，但头文件是v7版本。

**Comment by Bigwode** [comment]
@luotao1 谢谢，我尝试修改一下版本

**Comment by jchua127** [comment]
> > [cudnn init] libcudnn v6 with header v7 unmatched!
> 
> @Bigwode 从日志看出来，cudnn的lib为v6，但头文件是v7版本。

你好，请问这个头文件如何升级呢？
