### ISSUE TITLE
[paddle v2] 训练中test接口使用。

### ISSUE THREAD

**Issue by shiyazhou121** [PaddlePaddle/Paddle#11193]
问题：在train中，需要在event函数里写test，目前使用的是trainer.test(reader=reader,feeding=feeding)，但是我看到的例子里的reader都是paddle.batch()。请问如果不想用batch，想测试全部的数据，应该怎么做？

**Comment by jacquesqiao** [comment]
fluid还是v2?

**Comment by shiyazhou121** [comment]
@jacquesqiao V2  0.11

**Comment by jacquesqiao** [comment]
test目前就是会跑全部的数据，他会读取所有数据跑完之后出一个统计结果
