### ISSUE TITLE
编译c-api问题

### ISSUE THREAD

**Issue by wrchow** [PaddlePaddle/Paddle#11239]
编译c-api的demo总是报错：
[ERROR] fail to compile baidu/third-party/paddle-capi/output/bin/sequence_paddle ip:10.103.243.15
 err:/home/opt/gcc-4.8.2.bpkg-r4/gcc-4.8.2.bpkg-r4/sbin/../lib/gcc/x86_64-baidu-linux-gnu/4.8.2/../../../../lib64/crt1.o: In function `_start':
(.text+0x20): undefined reference to `main'
collect2: error: ld returned 1 exit status

**Comment by dzhwinter** [comment]
没写main函数。

**Comment by wrchow** [comment]
跑的demo 
 https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/capi/examples/model_inference/sequence/main.c
