### ISSUE TITLE
another undefined reference ....

### ISSUE THREAD

**Issue by harlanxu** [PaddlePaddle/Paddle#1124]
when issue :
make -j `nproc`

the following error appears:

../../gserver/libpaddle_gserver.a(ProtoDataProvider.cpp.o): In function `paddle::ProtoReader::ProtoReader(std::istream*, bool)':
/root/github/Paddle/paddle/gserver/dataproviders/ProtoReader.h:37: ****undefined reference to `google::protobuf::io::GzipInputStream::GzipInputStream(google::protobuf::io::ZeroCopyInputStream*, google::protobuf::io::GzipInputStream::Format, int)'****
collect2: error: ld returned 1 exit status
paddle/utils/tests/CMakeFiles/test_SpinLock.dir/build.make:114: recipe for target 'paddle/utils/tests/test_SpinLock' failed
make[2]: *** [paddle/utils/tests/test_SpinLock] Error 1
CMakeFiles/Makefile2:491: recipe for target 'paddle/utils/tests/CMakeFiles/test_SpinLock.dir/all' failed
make[1]: *** [paddle/utils/tests/CMakeFiles/test_SpinLock.dir/all] Error 2
Makefile:160: recipe for target 'all' failed
make: *** [all] Error 2

the ubuntu version:

Distributor ID: Ubuntu
Description:    Ubuntu 16.04.1 LTS
Release:        16.04
Codename:       xenial

root@ubuntu:~/github/Paddle/build# dpkg -l *protobuf*
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name                       Version            Architecture       Description
+++-==========================-==================-==================-==========================================================
ii  libmirprotobuf3:amd64      0.21.0+16.04.20160 amd64              Display server for Ubuntu - RPC definitions
ii  libprotobuf-dev:amd64      2.6.1-1.3          amd64              protocol buffers C++ library (development files)
un  libprotobuf-lite9          <none>             <none>             (no description available)
ii  libprotobuf-lite9v5:amd64  2.6.1-1.3          amd64              protocol buffers C++ library (lite version)
un  libprotobuf9               <none>             <none>             (no description available)
ii  libprotobuf9v5:amd64       2.6.1-1.3          amd64              protocol buffers C++ library
ii  protobuf-compiler          2.6.1-1.3          amd64              compiler for protocol buffer definition files
ii  python-protobuf            2.6.1-1.3          amd64              Python bindings for protocol buffers

can you  please give me some advice?thanks.

**Comment by gangliao** [comment]
Do you use the latest Paddle code in develop branch??

**Comment by gangliao** [comment]
The latest code will download, build and install protobuf by itself.
https://github.com/PaddlePaddle/Paddle/blob/develop/cmake/external/protobuf.cmake#L47

**Comment by harlanxu** [comment]
@gangliao  thanks.
