### ISSUE TITLE
fluid_benchmark 运行加入----use_reader_op参数，启动psserver失败

### ISSUE THREAD

**Issue by ccmeteorljh** [PaddlePaddle/Paddle#11259]
测试pr #11121 启动多机训练，启动psserver脚本如下，出错：
export FLAGS_fraction_of_gpu_memory_to_use=0.0 
export PADDLE_TRAINING_ROLE=PSERVER 
export PADDLE_PSERVER_PORT=5002 
export PADDLE_PSERVER_IPS=10.255.123.15,10.255.123.16 
export PADDLE_TRAINERS=2 
export PADDLE_CURRENT_IP=10.255.123.15 
export PADDLE_TRAINER_ID=1
python fluid_benchmark.py --model resnet  \
--data_set flowers --use_reader_op --memory_optimize \
--iterations 20 \
--device GPU --gpus 8 --batch_size 64 \
--pass_num 1 --data_path recordio --no_test \
--update_method pserver
报错如下：
![image](https://user-images.githubusercontent.com/33303691/41076039-250f21d2-6a42-11e8-8e57-d38d7e7000d7.png)

去掉--use_reader_op参数后可以正常启动

**Comment by typhoonzero** [comment]
program中包含reader op然后执行transpile就会报错。需要修复。

**Comment by typhoonzero** [comment]
workaround, pserver启动的进程，不要包含reader相关代码即可。

**Comment by velconia** [comment]
把和 pserver_program op 无关的 input vars 初始化都删去了
