### ISSUE TITLE
请教一下embedding的相关问题

### ISSUE THREAD

**Issue by g7925836** [PaddlePaddle/Paddle#11269]
在paddle学习的中发现了一个问题。
usr_gender_id      = paddle.layer.data(name='gender_id', type=paddle.data_type.integer_value(2))
usr_gender_emb = paddle.layer.embedding(input=usr_gender_id, size=128)
usr_gender_fc     = paddle.layer.fc(input=usr_gender_emb, size=16)
这个代码中gender_id是一个int的整型，通过embidding变成了128维的向量，然后进行全连接变成16维的向量，容易理解。
在实际运用中发现，对不定长的int型如下：
content是一个不定长的int向量
content      = paddle.layer.data("content_1",paddle.data_type.integer_value_sequence(1000))
emb_cont  = paddle.layer.embedding(input=content, size=128)
content_fc = paddle.layer.fc(input=usr_gender_emb, size=128)
这样也能run的痛。但是无法理解。
假设有两个content 分别长度是10和20
embedding后应该变成10 * 128和20 * 128，此时如果进行全联接变成128维的向量，难以理解。因为这样对不定长的content网络结构不同。
请问这种如何解释？

**Comment by Superjomn** [comment]
这段代码来自哪个模型？

**Comment by g7925836** [comment]
我们自己写了一个模型用于预测文本标签，也可以run起来，原始代码如下。
word_dim 和 emd_dim 都是固定值。
title_1是一个不定长向量。
        t_data = paddle.layer.data("title_1",
                             paddle.data_type.integer_value_sequence(word_dim))
        t_emb = paddle.layer.embedding(input=t_data, size=emb_dim)
        self.t_emb = t_emb
        t_in_1 = paddle.layer.fc(input = t_emb, size = emb_dim*2, act=paddle.activation.Linear())
        t_in_2 = paddle.layer.batch_norm(input = t_in_1, act = paddle.activation.Relu())
        t_in_3 = paddle.layer.pooling(input = t_in_2, pooling_type=pl.AvgPooling(),
            agg_level=paddle.layer.AggregateLevel.TO_NO_SEQUENCE)

**Comment by Superjomn** [comment]
你的意思是embedding 的output 也能 fc，比较奇怪是吧。

fc 会把每个 instance 做下fc，不是所有instance合起来做fc

比如，序列长度 3，经过 embedding的output，是 3 个 instance (word vec)

| | |

经过fc是还是 3 个 instance

| | |

两者机制不冲突

**Comment by g7925836** [comment]
可以理解为分别处理是么？

**Comment by g7925836** [comment]
就是title是N维int向量，embedding后变成N个128维向量。在全联接的时候N个128维向量自己进行全联接。结果有N个全联接的产出FC是么？

**Comment by Superjomn** [comment]
对，每个instance单独处理

**Comment by g7925836** [comment]
好的，谢谢解惑
