### ISSUE TITLE
allocator initial cpu memory usage is too large

### ISSUE THREAD

**Issue by tensor-tang** [PaddlePaddle/Paddle#11272]
This is an issue related with #11185 

Even we can use `fraction_of_cpu_memory_to_use` to work around, but it's still tricky and does not make sense that init memory with `max_chunk_size_` which it 3% memory.

`BuddyAllocator::PoolSet::iterator BuddyAllocator::RefillPool() `:
https://github.com/PaddlePaddle/Paddle/blob/6d80dd5a50f32db7c4353e52334bca7e8179d785/paddle/fluid/memory/detail/buddy_allocator.cc#L189-L192

`void* BuddyAllocator::Alloc(size_t unaligned_size)` :
https://github.com/PaddlePaddle/Paddle/blob/6d80dd5a50f32db7c4353e52334bca7e8179d785/paddle/fluid/memory/detail/buddy_allocator.cc#L67-L69

**Comment by Superjomn** [comment]
Maybe an absolute memory usage is better for inference.
