### ISSUE TITLE
dotmul_operator error: different inputs have different size

### ISSUE THREAD

**Issue by April0402** [PaddlePaddle/Paddle#11273]
The error info is :  [CRITICAL 2018-06-07 15:22:18,569 layers.py:856] different inputs have different size: 1024 vs. 256
But I have print size of the two input layers of dotmul_operator layer, their size are both 1024.

This is the code:

    219 def get_p_attention(lstm_layer, p_emb_layer_list, attention_dim, hidden_dim, \
    220          fc_para_attr, lstm_para_attr, default_std):
    221     """
    222     attention:
    223         attention_input = fc(lstm) x fc(p_lstm)
    224         normalized_weight = fc(attention_input, act = SequenceSoftmax)
    225     """
    226
    227     p_emb_mixed_layer = get_hidden_layer(p_emb_layer_list, fc_para_attr, \
    228             hidden_dim, default_std)
    229     p_lstm_layer = paddle.networks.bidirectional_lstm(input=p_emb_mixed_layer, \
    230             size=hidden_dim, return_seq=True)
    231     p_last = paddle.layer.last_seq(input=p_lstm_layer, stride=0)
    232     p_expanded_layer = paddle.layer.expand(input=p_last, expand_as=lstm_layer)
    233     print >> sys.stderr, lstm_layer.size   # 1024
    234     print >> sys.stderr, p_expanded_layer.size   # 1024
    235
    236     with paddle.layer.mixed(size=attention_dim) as combined_input:
    237         combined_input += paddle.layer.dotmul_operator(\
    238                 a=lstm_layer, b=p_expanded_layer)

**Comment by Superjomn** [comment]
lstm_layer 是啥？

**Comment by April0402** [comment]
49     lstm_layer = paddle.networks.bidirectional_lstm(input=emb_mixed_layer, \
     50             size=hidden_dim, return_seq=True)

emb_mixed_layer是一个mixed，输入是一些embedding

**Comment by Superjomn** [comment]
感觉是  `combined_input += ` 这里维度不一致

**Comment by April0402** [comment]
确实是这个问题，把mixed_layer的size改成一致就ok了，感谢感谢！
