### ISSUE TITLE
capi执行convert_protobin提示No module named paddle.utils

### ISSUE THREAD

**Issue by ybbz** [PaddlePaddle/Paddle#11274]
使用的是sequence这个demo（Paddle/paddle/capi/examples/model_inference/sequence）

已经编译成功了，如下所示：
Scanning dependencies of target sequence
[ 50%] Building C object CMakeFiles/sequence.dir/main.c.o
[100%] Linking C executable sequence
[100%] Built target sequence

但是接下来执行sh convert_protobin.sh时，提示：
**/usr/bin/python: No module named paddle.utils**

再执行./sequence，提示：
I0607 16:01:59.184636 94092 Util.cpp:166] commandline:  --use_gpu=False
W0607 16:01:59.184787 94092 CpuId.h:112] PaddlePaddle wasn't compiled to use avx instructions, but these are available on your machine and could speed up CPU computations via CMAKE .. -DWITH_AVX=ON
**[libprotobuf ERROR /paddle/build/third_party/protobuf/src/extern_protobuf/src/google/protobuf/message_lite.cc:119] Can't parse message of type "paddle.ModelConfig" because it is missing required fields: type
Invoke paddle error 3 in paddle_gradient_machine_create_for_inference(&machine, buf, (int)size)**

请问是怎么回事？谢谢！

**Comment by Superjomn** [comment]
是paddle没有安装？ 可以手动找到 paddle.utils 这个 python module 的路径么

**Comment by ybbz** [comment]
paddle不是已经作为lib（libpaddle_capi_shared.so）被编译了吗？还需要怎么安装？就是要在线上使用、无法单机安装paddle、所以才使用capi的

**Comment by Superjomn** [comment]
转proto这步是python的，需要python的paddle

**Comment by ybbz** [comment]
> 转proto这步是python的，需要python的paddle

赞，可以了
