### ISSUE TITLE
Tensor holds the wrong type

### ISSUE THREAD

**Issue by jaegerstar** [PaddlePaddle/Paddle#11285]
> paddle.fluid.core.EnforceNotMet: Tensor holds the wrong type, it holds d at [/paddle/paddle/fluid/framework/tensor_impl.h:84]
PaddlePaddle Call Stacks: 
0       0x7f2e1b207bb2p paddle::platform::EnforceNotMet::EnforceNotMet(std::__exception_ptr::exception_ptr, char const*, int) + 482
1       0x7f2e1b2cb65fp long const* paddle::framework::Tensor::data<long>() const + 255
2       0x7f2e1b4e5a4bp paddle::operators::LookupTableKernel<double>::Compute(paddle::framework::ExecutionContext const&) const + 539
3       0x7f2e1b8a8a52p paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&) const + 1362
4       0x7f2e1b8a6794p paddle::framework::OperatorBase::Run(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&) + 52
5       0x7f2e1b286dbcp paddle::framework::Executor::RunPreparedContext(paddle::framework::ExecutorPrepareContext*, paddle::framework::Scope*, bool, bool) + 364
6       0x7f2e1b2874d9p paddle::framework::Executor::Run(paddle::framework::ProgramDesc const&, paddle::framework::Scope*, int, bool, bool) + 89
7       0x7f2e1b21d641p _ZZN8pybind1112cpp_function10initializeIZNS0_C1IvN6paddle9framework8ExecutorEJRKNS4_11ProgramDescEPNS4_5ScopeEibbEJNS_4nameENS_9is_methodENS_7siblingEEEEMT0_FT_DpT1_EDpRKT2_EUlPS5_S8_SA_ibbE_vJSO_S8_SA_ibbEJSB_SC_SD_EEEvOSF_PFSE_SH_ESN_ENUlRNS_6detail13function_callEE1_4_FUNESV_ + 545
8       0x7f2e1b217902p pybind11::cpp_function::dispatcher(_object*, _object*, _object*) + 2338
9       0x7f2e84cfc3d4p PyEval_EvalFrameEx + 25956
10      0x7f2e84cfd120p PyEval_EvalCodeEx + 2240
11      0x7f2e84cfb491p PyEval_EvalFrameEx + 22049
12      0x7f2e84cfd120p PyEval_EvalCodeEx + 2240
13      0x7f2e84cfb491p PyEval_EvalFrameEx + 22049
14      0x7f2e84cfbc46p PyEval_EvalFrameEx + 24022
15      0x7f2e84cfd120p PyEval_EvalCodeEx + 2240
16      0x7f2e84cfd232p PyEval_EvalCode + 50
17      0x7f2e84d1761cp
18      0x7f2e84d176f0p PyRun_FileExFlags + 144
19      0x7f2e84cf41a3p
20      0x7f2e84cfb639p PyEval_EvalFrameEx + 22473
21      0x7f2e84cfd120p PyEval_EvalCodeEx + 2240
22      0x7f2e84cfb491p PyEval_EvalFrameEx + 22049
23      0x7f2e84cfbc46p PyEval_EvalFrameEx + 24022
24      0x7f2e84cfd120p PyEval_EvalCodeEx + 2240
25      0x7f2e84cfd232p PyEval_EvalCode + 50
26      0x7f2e84d1761cp
27      0x7f2e84d176f0p PyRun_FileExFlags + 144
28      0x7f2e84d18bfcp PyRun_SimpleFileExFlags + 220
29      0x7f2e84d2a4bcp Py_Main + 3164
30        0x318ae1ecddp __libc_start_main + 253
31            0x400659p

想问问问题出在哪？版本是pip安装的0.12.0版，顺便想知道paddle有没有类似tfdebugger那样的debug工具

**Comment by Superjomn** [comment]
没有debug工具。

可以补充多一些信息吗，比如是训练还是预测，大概模型，或者自己能推测出的出问题的代码片段啥的

**Comment by jaegerstar** [comment]
@Superjomn 是用textcnn做文本分类训练的时候，看提示猜是不是Tensor里的数据类型有问题，有一个变量我用了float64，这样写了：
```
data = fluid.layers.data(
        name="words", shape=[1], dtype="float64", lod_level=1)
```
在想是不是不支持float64，找到[supported type](http://www.paddlepaddle.org/doc/ui/data_provider/pydataprovider2.html?highlight=dense_vector#input-types)却链接打不开。

**Comment by jaegerstar** [comment]
`Tensor holds the wrong type, it holds d at [/paddle/paddle/fluid/framework/tensor_impl.h:84]`
看源码貌似里面的d是变量的name？有什么方法可以看到是对应哪个变量吗

**Comment by Superjomn** [comment]
看了下代码，好像这行已经更新了。 应该是data type 的问题，最快的方法可以试试，换成 float32 看逻辑有没有问题。

如果一定要 float64的话，可以再继续查这个问题。

**Comment by jaegerstar** [comment]
@Superjomn 改成了float32了，还是报同样的错，不知道还有什么其他解决思路没，如有必要可以hi上提供代码复现

**Comment by Superjomn** [comment]
可以贴下相关行的配置及其他可以帮助 debug 的信息吗

**Comment by jaegerstar** [comment]
主要训练代码如下：
```
# 数据定义
data = fluid.layers.data(name="words", shape=[1], dtype="float32", lod_level=1)
label = fluid.layers.data(name="label", shape=[1], dtype="int64")

# 生成网络
cost, acc, prediction = network(data, label, len(word_dict))
place = fluid.CUDAPlace(0) if use_cuda else fluid.CPUPlace()
exe = fluid.Executor(place)

# 生成数据feeder
feeder = fluid.DataFeeder(feed_list=[data, label], place=place)
exe.run(fluid.default_startup_program())

# 加载embedding
embedding_name = 'emb_static'
embedding_param = fluid.global_scope().find_var(embedding_name).get_tensor()
embedding_param.set(wordvec, place)

# 训练流程
for epoch_id in xrange(epoch):
	data_size, data_count, total_acc, total_cost = 0, 0, 0.0, 0.0
	for input_data in train_reader():
		avg_cost_np, avg_acc_np = exe.run(fluid.default_main_program(),
										  feed=feeder.feed(input_data),
										  fetch_list=[cost, acc])
		data_size = len(input_data)
		total_acc += data_size * avg_acc_np
		total_cost += data_size * avg_cost_np
		data_count += data_size

	avg_cost = total_cost / data_count
	avg_acc = total_acc / data_count

	print("epoch_id: %d, avg_acc: %f, avg_cost: %f" %
		  (epoch_id, avg_acc, avg_cost))

	epoch_model = save_dirname + "/" + "epoch" + str(epoch_id)
	fluid.io.save_inference_model(epoch_model, ["words", "label"], acc, exe)

```

网络结构代码如下：
```
emb_para_static = ParamAttr(name='emb_static', trainable=False)
parameter_attr = ParamAttr(initializer=MSRA())
def cnn_net(data,
            label,
            dict_dim,
            emb_dim=128,
            hid_dim=128,
            fc_dim=96,
            act='relu',
            win_size=2,
            class_dim=2):
    emb_static = fluid.layers.embedding(input=data, size=[dict_dim, emb_dim], param_attr=emb_para_static)
    conv_set = fluid.nets.sequence_conv_pool(
        input=emb_static,
        num_filters=hid_dim,
        filter_size=win_size,
        act=act,
        pool_type="max")
    # conv_cat = fluid.layers.concat(conv_set, axis=0)
    fc_out = fluid.layers.fc(input=[conv_set],
                             size=fc_dim,
                             param_attr=parameter_attr,
                             bias_attr=parameter_attr)
    prediction = fluid.layers.fc(input=[fc_out], size=class_dim, act="softmax")
    cost = fluid.layers.cross_entropy(input=prediction, label=label)
    avg_cost = fluid.layers.mean(x=cost)
    acc = fluid.layers.accuracy(input=prediction, label=label)
    return avg_cost, acc, prediction
```
@Superjomn

**Comment by Superjomn** [comment]
跑起来之后，完整的错误是啥，能看出来具体哪一个 op 出了那个错吗？

**Comment by jaegerstar** [comment]
完整的错误已经贴在最上面了，没有其他，没法看出哪个op出错，是否需要安装最新版paddle呢

**Comment by Superjomn** [comment]
可以用新版的试试，最近开发确实比较快可能有覆盖那块。

如果还不行那只能完整环境去 debug 了，这边开发比较紧张，周期会更长些。

**Comment by jaegerstar** [comment]
好的，“完整环境去 debug”是什么意思呢 @Superjomn

**Comment by shanyi15** [comment]
您好，此issue在近一个月内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题，我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持! 
 Hello, this issue has not been updated in the past month. We will close it today for the sake of other user‘s experience. If you still need to follow up on this question after closing, please feel free to reopen it. In that case, we will get back to you within 24 hours. We apologize for the inconvenience caused by the closure and thank you so much for your support of PaddlePaddle Group!

**Comment by Albelt** [comment]
我也遇到了同样的问题，我用的0.15.0版本。
发生异常: paddle.fluid.core.EnforceNotMet
Tensor holds the wrong type, it holds l at [/paddle/paddle/fluid/framework/tensor_impl.h:29] PaddlePaddle Call Stacks:  0       0x7ff6f1297d86p paddle::platform::EnforceNotMet::EnforceNotMet(std::__exception_ptr::exception_ptr, char const*, int) + 486 1       0x7ff6f129f710p float const* paddle::framework::Tensor::data<float>() const + 192 2       0x7ff6f14d83cep void paddle::operators::ElementwiseComputeEx<paddle::operators::SubFunctor<float>, paddle::platform::CPUDeviceContext, float, float>(paddle::framework::ExecutionContext const&, paddle::framework::Tensor const*, paddle::framework::Tensor const*, int, paddle::operators::SubFunctor<float>, paddle::framework::Tensor*) + 78 3       0x7ff6f1664d61p paddle::operators::ElementwiseSubKernel<paddle::platform::CPUDeviceContext, float>::Compute(paddle::framework::ExecutionContext const&) const + 321 4       0x7ff6f1664de3p std::_Function_handler<void (paddle::framework::ExecutionContext const&), paddle::framework::OpKernelRegistrarFunctor<paddle::platform::CPUPlace, false, 0ul, paddle::operators::ElementwiseSubKernel<paddle::platform::CPUDeviceContext, float>, paddle::operators::ElementwiseSubKernel<paddle::platform::CPUDeviceContext, double>, paddle::operators::ElementwiseSubKernel<paddle::platform::CPUDeviceContext, int>, paddle::operators::ElementwiseSubKernel<paddle::platform::CPUDeviceContext, long> >::operator()(char const*, char const*) const::{lambda(paddle::framework::ExecutionContext const&)#1}>::_M_invoke(std::_Any_data const&, paddle::framework::ExecutionContext const&) + 35 5       0x7ff6f1c6ac2ep paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&) const + 526 6       0x7ff6f1c6700fp paddle::framework::OperatorBase::Run(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&) + 255 7       0x7ff6f1b01504p 8       0x7ff6f1b010bfp paddle::framework::details::ComputationOpHandle::RunImpl() + 95 9       0x7ff6f1b1e10cp paddle::framework::details::OpHandleBase::Run(bool) + 28 10      0x7ff6f1ae0abap 11      0x7ff6f19e0583p std::_Function_handler<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> (), std::__future_base::_Task_setter<std::unique_ptr<std::__future_base::_Result<void>, std::__future_base::_Result_base::_Deleter>, void> >::_M_invoke(std::_Any_data const&) + 35 12      0x7ff6f13c9487p std::__future_base::_State_base::_M_do_set(std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> ()>&, bool&) + 39 13      0x7ff72cdbea99p 14      0x7ff6f1adf8c2p 15      0x7ff6f13cac64p ThreadPool::ThreadPool(unsigned long)::{lambda()#1}::operator()() const + 404 16      0x7ff7033eb678p 17      0x7ff72cdb76bap 18      0x7ff72c3dd41dp clone + 109 
  File "/home/albelt/test/train1.py", line 201, in train
  File "/home/albelt/test/train1.py", line 305, in <module>

**Comment by Superjomn** [comment]
python 输入数据类型不对，比如需要 flaot ， 你输入了 int

比较常见的情况是， numpy 的 dtype没设对。
@Albelt

**Comment by liushanshan07** [comment]
我也遇到这个问题了。检测数据类型后发现错误传入dtype=int64的数据，已解决。
Tensor holds the wrong type, it holds l 说明传入了Int64，检查下每个数据的类型。

**Comment by Albelt** [comment]
谢谢，已解决。
