### ISSUE TITLE
使用CPU版本出现GPU检测错误

### ISSUE THREAD

**Issue by cdj0311** [PaddlePaddle/Paddle#11301]
安装的CPU版本运行时出现检测CUDA的错误，请问怎么解决？？
F0608 11:16:34.948220 53502 hl_cuda_device.cc:565] Check failed: cudaSuccess == cudaStat (0 vs. 35) Cuda Error: CUDA driver version is insufficient for CUDA runtime version

**Comment by seiriosPlus** [comment]
是V2还是fluid

**Comment by cdj0311** [comment]
@seiriosPlus V2

**Comment by seiriosPlus** [comment]
你有用use_gpu=True这样的参数么~

**Comment by cdj0311** [comment]
@seiriosPlus 用的use_gpu=False

**Comment by seiriosPlus** [comment]
你把之前的版本卸载了重新装一下CPU版本的再尝试一下

**Comment by cdj0311** [comment]
@seiriosPlus 试过了，不行，我用pip安装的

**Comment by seiriosPlus** [comment]
你是什么系统，我尝试一下

**Comment by cdj0311** [comment]
@seiriosPlus Centos7没有GPU

**Comment by seiriosPlus** [comment]
装的是什么版本的paddle

**Comment by seiriosPlus** [comment]
v2你可以装0.10的paddle尝试执行一下

**Comment by cdj0311** [comment]
@seiriosPlus 0.13版
