### ISSUE TITLE
在Paddle中如何给激活函数传入参数？

### ISSUE THREAD

**Issue by zzhzz** [PaddlePaddle/Paddle#11303]
我看到Paddle有Hardshrink以及Softshrink函数，如何在fc层中指定这两个函数的lambda值？例如现在
fc_layer = fluid.fc(input=data, size=100, act='tanh')，如果想要换成hard_shrink函数该如何修改？

**Comment by seiriosPlus** [comment]
目前激活函数只能传 str 类型的，
这种情况你可以 把 fc的act设置成None ，然后加入一层 hard_shrink层
