### ISSUE TITLE
如何使用paddle分析一句话或者一段话的情感色彩(褒贬)

### ISSUE THREAD

**Issue by Hansxsourse** [PaddlePaddle/Paddle#11324]
我们目前再做一个分析评论并分类的东西，想问问怎么使用paddle来做

**Comment by ktlichkid** [comment]
可以参考这里，关于情感分析的入门教程：
http://www.paddlepaddle.org/docs/develop/book/06.understand_sentiment/index.cn.html

**Comment by Hansxsourse** [comment]
谢谢

**Comment by ascotdudu** [comment]
您好，您给的链接，打不开
