### ISSUE TITLE
seqToseq_net输出层的实现与原始论文不一样

### ISSUE THREAD

**Issue by huguanglong** [PaddlePaddle/Paddle#1133]
@luotao1 @lcy-seso 两位，最近对比了下seqToseq_net.py输出层的实现与Bengio原始论文，发现有一些不一样的地方：
1）原始论文《NEURAL MACHINE TRANSLATION BY JOINTLY LEARNING TO ALIGN AND TRANSLATE》中，decoder端gru层的输出si、ci、yi-1合在一起，作为最终输出层的输入，公式如下：
![image](https://cloud.githubusercontent.com/assets/2075596/21880886/2d8ecd88-d8dc-11e6-9c5d-dc2014ea398e.png)
2）seqToseq_net.py中的实现，相当于是直接将decoder端gru层的输出作为最后输出层的输入，代码如下：
![image](https://cloud.githubusercontent.com/assets/2075596/21880912/5d038090-d8dc-11e6-925e-74dfee308f68.png)
请问这种简化实现的考虑是什么？性能方面有与原始论文的实现做对比么？
另外，最近在实现多层时，发现3层以上的性能反而没有2层的好，不知道你们是否有观察到这个现象？会是训练数据不足导致？
谢谢！

**Comment by lcy-seso** [comment]
谢谢你的问题~ 确实是不一样的。

论文中在预测下一个词时：使用了 target embedding，context vector，以及 decoder output ，paddle 的配置中只用到了 decoder output。这些简化在我们的实验中，对生成性能没有影响。只有一层 GRU decoder 时， decoder 的output 已经很好的包含了context vector 和 target embedding 信息，这两个输入也有可能在深层的时候拉浅网络。

同时，论文中用源语言反向最后一个时刻加了一个映射初始化decoder 的状态，这个也是可以省略的。对性能不会有太大影响。

**Comment by huguanglong** [comment]
@lcy-seso 感谢你的回复，我在对比GroundHog（原始论文的实现）和Paddle中的seqToseq_net.py时，发现paddle的效果更好些，这种简化的确没有什么影响。
另外请教下哈：
1）上次所说的华为coverage方案在多层时是否有效，这方面你们有尝试过么？
2）两层比单层的提升很显著，但3层以上似乎没有提升了，这个问题你怎么看呢？

**Comment by lcy-seso** [comment]
1. coverage 我和 RNNSearch 对比过，感觉没啥特别优势，就没有在深层上继续尝试（太费时间啦）。我自己理解是这样，coverage 的思路是对的，但是肯定有更好的实现方式。这个论文里面是试图通过引入 attention 历史来达到对源语言的 coverage ，其实也是比较soft 的coverage，如果是引入 attention 历史，NTM里面提到的的hybird addressing 也有同样的效果。原来跑，效果也会比coverage 更好；所以当时没有一直再去继续这个实验；

2. 深层 RNN一定比浅层好，很可能是没有训练好。

3.  Google NMT 论文里面也提到这个问题。Google 论文里面的数据是裸着迭 4 层，一般没啥问题。再网上需要加一些保证梯度在纵向上顺畅传播的连接。Google 的论文里面加入了 residual connection，还可以加入 Highway。我们之前的实验结果是，在深层 RNN 上面 ，Residual 收敛的快，但最终评估指标 不如 Highway。 

4.  安利一下我们的论文哈~ [Deep Recurrent Models with Fast-Forward Connections for Neural Machine Translation](https://arxiv.org/abs/1606.04199)，里面的 fast-forward connection 也是一种方式~

**Comment by huguanglong** [comment]
@lcy-seso 你们做的很深入啊，赞！
1. 重复翻、漏翻问题，在nmt中似乎很难针对性解决。coverage思路感觉像那么回事，但实际效果并没有文章中说的那么好（可能引入的参数较少，表达不够充分）。期待新的突破性文章！
2. 有可能是没训练好，我现在的训练设置大概是这样的：采用AdamOptimizer，学习率从5e-4开始，每个epoch数据shuf+学习率减半，3轮以上几乎不再收敛。请问这方面有较好的调参经验分享下么？
3. Google NMT目前正在尝试中，4层没有2层的好，估计也是没训练好的原因，需要继续调参观察；highway是类似文献《Recurrent Highway Networks》中的思想么？跟进学习下。
4. 你们的论文也在尝试中，2层对比时，gnmt似乎要好些，目前还在进一步尝试中。
有好的调参经验，还请多多指教哈！

**Comment by lcy-seso** [comment]
3 轮以上就不再收敛，这个挺奇怪的。我们训练的时候还不至于这么差，代价一直会降，是不是学习率砍得过了呢？

Highway 是这个~  有这一篇  [Training Very Deep Networks](https://arxiv.org/pdf/1507.06228.pdf)

**Comment by lcy-seso** [comment]
如果是用paddle 训练的话，有一个参数，--show_parameter_stats_period=N 。设置这个参数，每隔  N 个batch 会输出参数的一些统计信息，比如梯度的平均值，最大值，参数的绝对值的平均值之类的。3 轮就不收敛，这个肯定不应该。可以试试看，是不是什么原因导致梯度太小了？

**Comment by huguanglong** [comment]
@lcy-seso 好的，谢谢你的建议！可能是学习率后面调的过小导致的，我再试试。
还有个问题想咨询下，我用多gpu训练时，速度提升似乎没有预期的快，双卡和单卡训练速度差不多。卡的数量和训练速度之间的关系，有个大概曲线么？

**Comment by lcy-seso** [comment]
多 GPU 双卡和单卡训练速度，差不多这个也是使用 PaddlePaddle 吗？这个现象也不是非常正常。

如果是 GPU 速度的问题，或者可以新提一个issue，提供一些详细的参数信息。请更专业的同学再看看~

**Comment by huguanglong** [comment]
@lcy-seso 嗯，是的，也是使用PaddlePaddle。我的机器上有4张Tesla K80 卡（共8核），做过对比试验：用4张K80和1张K80时，训练速度基本差不多。我的train.sh配置如下：
![image](https://cloud.githubusercontent.com/assets/2075596/22180901/5c272a84-e0b9-11e6-82e0-1c328e3be41f.png)
train.conf配置如下：
![image](https://cloud.githubusercontent.com/assets/2075596/22180907/7ea79328-e0b9-11e6-8f51-3934abb6f41e.png)
这个现象比较奇怪。另外，我在MultiGradientMachine.h中看到这么一段描述：
![image](https://cloud.githubusercontent.com/assets/2075596/22180918/b3a66cde-e0b9-11e6-96cf-f5248ccd86d8.png)
会不会是ring-style方式导致参数传递很耗时？
还是多GPU卡情况下，我的配置参数漏了什么？

**Comment by huguanglong** [comment]
@lcy-seso @reyoung 上述多GPU训练速度无提升的问题，有哪位更专业的同学帮忙看看么？谢谢！

**Comment by WangYQ999** [comment]
您好，请问PaddleSeg中实现的模型与原论文模型性能有进行过测试吗，我想用PaddleSeg中的模型做一些对比实验可行吗？
