### ISSUE TITLE
fluid调用paddle.fluid.layers.resize_bilinear失败

### ISSUE THREAD

**Issue by Leezhaohui** [PaddlePaddle/Paddle#11331]
错误类型：
'module' object has no attribute 'resize_bilinear'

**Comment by qingqing01** [comment]
@Leezhaohui `paddle.fluid.layers.resize_bilinear` 是最近刚加的接口，需要升级你安装的whl包。

**Comment by qingqing01** [comment]
@Leezhaohui 关闭这个issue了，在较新的代码上`paddle.fluid.layers.resize_bilinear`这个测试可用的。
