### ISSUE TITLE
dynamic_lstm和dynamic_gru的reverse问题

### ISSUE THREAD

**Issue by gavin1332** [PaddlePaddle/Paddle#11334]
dynamic_gru和dynamic_lstm的is_reverse参数设为True后得到的结果是reversed还是会恢复为forward序？因为下述样例中85行调用56行的正反向lstm后直接拼接，并没看到reverse操作，所以有这个疑问。
https://github.com/PaddlePaddle/Paddle/blob/635099c1622f28ff5c7cd264180fd0414a1d2d01/benchmark/fluid/models/machine_translation.py

另外，想知道如何reverse一个序列，目前没找到相关op

**Comment by qingqing01** [comment]
@gavin1332 `reverse`代表 计算lstm/gru时，是从最后一个时间步序列往第一个时间步计算，计算后的结果保存为'forward'序列。你的理解没错。

> 想知道如何reverse一个序列，目前没找到相关op

目前没有序列反序的op。

**Comment by Yancey1989** [comment]
Thanks @qingqing01 , `reverse_op` 目前只支持对Tensor的reverse，我加了一个TODO issue来支持LoDTensor #11341
