### ISSUE TITLE
multi label classification 输出差别不大

### ISSUE THREAD

**Issue by DTDXG** [PaddlePaddle/Paddle#11347]
1.主要的网络设置如下
![image](https://user-images.githubusercontent.com/39936716/41213852-8b88298c-6d7a-11e8-887f-cccf1216a22b.png)
![image](https://user-images.githubusercontent.com/39936716/41213898-c0127df6-6d7a-11e8-8354-9c40705a92b4.png)
![image](https://user-images.githubusercontent.com/39936716/41213980-4018f25a-6d7b-11e8-8c44-004590a61398.png)

2.infer之后的结果
![image](https://user-images.githubusercontent.com/39936716/41213953-0f7d0f28-6d7b-11e8-91e3-238e980b6ef1.png)
可以看到所有的测试样本都是第一个label的权重最大，基本等于1，模型训练看loss函数应该拟合，测试样本的区分性比较大，不应该是这样的结果，帮忙解决一下

**Comment by Yancey1989** [comment]
不确定是不是训练数据方面的问题，cost和classification_error_evaluator分别是多少呢？

多分类的模型配置可以参考book里的demo：https://github.com/PaddlePaddle/book/blob/develop/03.image_classification/train.py

**Comment by DTDXG** [comment]
补充一下cost值
[temp.txt](https://github.com/PaddlePaddle/Paddle/files/2089012/temp.txt)
训练数据的label区分性还是比较明显的，贴了一个图，最主要的是训练样本的第一个类别的个数不多，按道理测试集上面的结果不应该这么偏向于第一个类别
![image](https://user-images.githubusercontent.com/39936716/41217935-00c7298a-6d8c-11e8-8cf6-395cf54f4074.png)

**Comment by DTDXG** [comment]
不知道我理解的是否正确，你给我的例子里面是一个multi class 不是multi label

**Comment by dzhwinter** [comment]
How about changing label type from  `sparse_binary_vector` to `dense_vector` ?

**Comment by DTDXG** [comment]
@dzhwinter 谢谢 修改了之后 work了

**Comment by Yancey1989** [comment]
先关闭这个issue了，如果有问题可以再随时打开。

**Comment by DTDXG** [comment]
想问一下关于multi label的配置问题，cost function 为multi_binary_label_cross_entropy_cost，最后一层的全联接的激活函数为softmax，但是程序会提示我"softmax is not a recommended activation for multi_binary_label_cross_entropy, sigmoid is better", 改成sigmoid之后，可以拟合，损失函数降低的不错，但是我觉得最后的结果效果不 好，但是改成softmax的话，感觉模型没有收敛，损失函数没有降低

**Comment by leyiwang** [comment]
@DTDXG @dzhwinter 有个问题想请教一下，在train_reader函数中，样本多标签train_y是否是29维的向量，如[1,0,1,1,0, 0,...,0]？
