### ISSUE TITLE
paddle-gpu版本咨询

### ISSUE THREAD

**Issue by jiaozhusos** [PaddlePaddle/Paddle#11362]
想咨询下paddle-gpu有没有支持如下配置：
cuda-8.0
cudnn-v6
的版本呢？

**Comment by Yancey1989** [comment]
暂时没有，我们有cuda8.0+cudnn5和 cuda8.0+cudnn7的：http://paddlepaddle.org/docs/develop/documentation/en/build_and_install/pip_install_en.html
