### ISSUE TITLE
请问paddle中对于load embeding的oov有设置初始化值的参数吗？

### ISSUE THREAD

**Issue by bbgasj** [PaddlePaddle/Paddle#11361]
load embeding对于nlp任务应该是很常见的操作，一般初始化要么设全0，要么设置一个均值为0的正太分布，但是了解到ParameterAttribute里面的initial_*相关参数只在初始化的时候会用到，load已有词向量的话不生效。
对于nlp任务，这应该是一个比较常见的操作，建议支持一下。

我之前以为下述代码对于OOV会按initial_std随机初始化，咨询后得知不行，所以比较奇怪，来问一下：
        emb_para = paddle.attr.Param(name='emb', initial_std=0., is_static=True)
        emb = paddle.layer.embedding(
            input=input, 
            size=200, 
            param_attr=emb_para)

**Comment by Yancey1989** [comment]
Hi您好
在Paddle v2的embedding layer是一个固定维度的table，对于OOV(out of vocabulary)的情况，可以将统一处理成一个**UNK**的index，参考：https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/dataset/imikolov.py#L72

另外我理解您的需求是需要embedding layer支持动态的table，当输出一个新的ID，动态增加table的大小。此类特性在Fluid中用sparse table还比较好实现。

**Comment by Yancey1989** [comment]
先关闭这个issue了，本地训练支持sparse table的进展请关注 #10868 里的task list。
