### ISSUE TITLE
DNN-Embedding如何实现

### ISSUE THREAD

**Issue by weidong8405347** [PaddlePaddle/Paddle#1137]
对输入one-hot的离散数据先进行embedding转成连续值数据 再扔给dnn去训练，paddle如何支持不同的embedding方法

**Comment by pengli09** [comment]
请参考官方文档quick start中的Word Embedding Model一节。

**Comment by weidong8405347** [comment]
可能没表达清楚，我是想将离散特征比如pv click lr weight fm weight作为embedding传下去，这需要同时train lr fm模型 想问下paddle如何实现
