### ISSUE TITLE
需要在paddle报错信息中增加具有可读性的调试信息

### ISSUE THREAD

**Issue by lgone2000** [PaddlePaddle/Paddle#11371]
paddle使用中很难搞清楚出错信息的含义。  paddle 相当于 把 python 定义的网络 编译成了program， 但没保留任何调试信息。 结果运行时报了指令错误，没有对应到高层的语句和行号。遇到这种错误的时候， 基本靠猜，给出的上下文语义基本没什么线索， 对于不太懂内部原理的人来说。

**Comment by lgone2000** [comment]
能否在运行网络定义代码时.拿到并且保存每个生成的op,变量对应的上层python 的调用堆栈。并序列化成字符串保存到相应program里面。如果运行到哪个op出错，可以返回底层变量或者op的python 对应的变量个代码行号?

**Comment by Yancey1989** [comment]
感谢您的建议！
Debug的确能够提高生产力的工具，Paddle现在使用ProgramDesc描述程序逻辑，Variable来描述变量并存储在Scope中，Executor来保证程序的顺序执行。理论上可以开发出一个工具，在Fluid程序Core掉的时候把Executor中的上下文信息以及Scope中的变量数据打印出来方便调试。

> 如果运行到哪个op出错，可以返回底层变量或者op的python 对应的变量个代码行号?

另外如果需要保存代码行号等信息，可能需要开DEBUG的编译模式，对性能有些影响，线下调试没问题，线上程序可能不会开启此项编译参数。

**Comment by panyx0718** [comment]
> 能否在运行网络定义代码时.拿到并且保存每个生成的op,变量对应的上层python 的调用堆栈。并序列化成字符串保存到相应program里面。如果运行到哪个op出错，可以返回底层变量或者op的python 对应的变量个代码行号?

我记得TF是这么做的，paddle也可以搞一个

**Comment by lgone2000** [comment]
我后续贴一些 错误的报错信息吧，不是paddle开发人员是看不懂的。我们看看能否改善一下。
另外对于出错信息的打印 我认为不会对训练性能有影响， 因为这部分逻辑只有出错时会调用，正常跑都不会影响。

**Comment by typhoonzero** [comment]
这样的debug工具看起来是否更像eager execution或impretive programming的方式，即：debug时，可以enable impretive，运行不需要转换成program就可以直接执行op并可以方便的找到报错的行号并trace stack。程序开发debug完成之后，可以disable impretive，paddle就可以自动生成program(IR)并完成IR的执行优化，kernel fuse等工作，保证online的程序是最高性能执行的。

这个功能感觉我可以找个时间写个原型看下。

**Comment by lgone2000** [comment]
举下面例子看能否产生有意义的错误提示。
```
def testpredict():
    place = fluid.CPUPlace()
    exe = fluid.Executor(place)
    main_program = fluid.default_main_program()
    
    x = fluid.layers.data(name='x', shape=[256], dtype='float32')
    y_predict = fluid.layers.fc(input=x, size=1, act=None)

    batchnum = 5
    batch_data = [[np.random.rand(256)] for a in range(batchnum)]
    
    feeder = fluid.DataFeeder(place=place, feed_list=[x])
    **#exe.run(fluid.default_startup_program())**
    output = exe.run(main_program,
                                  feed=feeder.feed(batch_data),
                                  fetch_list=[y_predict])
    print(output)
```
当#exe.run(fluid.default_startup_program()) 注释关闭时，可以正常运行，当注释打开时，会报下面错误。
希望报错给出 类似 should call fluid.default_startup_program before run main_program

>   File "/home/python-gcc482-paddle/lib/python2.7/site-packages/paddle/fluid/executor.py", line 340, in run
    self.executor.run(program.desc, scope, 0, True, True)
paddle.fluid.core.EnforceNotMet: enforce y_dims.size() > y_num_col_dims failed, 1 <= 1
The input tensor Y's rank of MulOp should be larger than y_num_col_dims. at [/paddle/paddle/fluid/operators/mul_op.cc:52]
PaddlePaddle Call Stacks: 
0       0x7fdc994dfad6p paddle::platform::EnforceNotMet::EnforceNotMet(std::__exception_ptr::exception_ptr, char const*, int) + 486
1       0x7fdc99b23776p paddle::operators::MulOp::InferShape(paddle::framework::InferShapeContext*) const + 2790
2       0x7fdc9a30118bp paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&) const + 91
3       0x7fdc9957af87p paddle::framework::Executor::RunPreparedContext(paddle::framework::ExecutorPrepareContext*, paddle::framework::Scope*, bool, bool) + 263
4       0x7fdc9957c024p paddle::framework::Executor::Run(paddle::framework::ProgramDesc const&, paddle::framework::Scope*, int, bool, bool) + 100
5       0x7fdc994f875bp void pybind11::cpp_function::initialize<pybind11::cpp_function::initialize<void, paddle::framework::Executor, paddle::framework::ProgramDesc const&, paddle::framework::Scope*, int, bool, bool, pybind11::name, pybind11::is_method, pybind11::sibling>(void (paddle::framework::Executor::*)(paddle::framework::ProgramDesc const&, paddle::framework::Scope*, int, bool, bool), pybind11::name const&, pybind11::is_method const&, pybind11::sibling const&)::{lambda(paddle::framework::Executor*, paddle::framework::ProgramDesc const&, paddle::framework::Scope*, int, bool, bool)#1}, void, paddle::framework::Executor*, paddle::framework::ProgramDesc const&, paddle::framework::Scope*, int, bool, bool, pybind11::name, pybind11::is_method, pybind11::sibling>(pybind11::cpp_function::initialize<void, paddle::framework::Executor, paddle::framework::ProgramDesc const&, paddle::framework::Scope*, int, bool, bool, pybind11::name, pybind11::is_method, pybind11::sibling>(void (paddle::framework::Executor::*)(paddle::framework::ProgramDesc const&, paddle::framework::Scope*, int, bool, bool), pybind11::name const&, pybind11::is_method const&, pybind11::sibling const&)::{lambda(paddle::framework::Executor*, paddle::framework::ProgramDesc const&, paddle::framework::Scope*, int, bool, bool)#1}&&, void (*)(paddle::framework::Executor*, paddle::framework::ProgramDesc const&, paddle::framework::Scope*, int, bool, bool), pybind11::name const&, pybind11::is_method const&, pybind11::sibling const&)::{lambda(pybind11::detail::function_call&)#3}::_FUN(pybind11::detail::function_call) + 555
6       0x7fdc994f0e14p pybind11::cpp_function::dispatcher(_object*, _object*, _object*) + 2596
7       0x7fdcd883d55fp PyEval_EvalFrameEx + 29855
8       0x7fdcd883f86dp PyEval_EvalCodeEx + 2061
9       0x7fdcd883c9fcp PyEval_EvalFrameEx + 26940
10      0x7fdcd883f86dp PyEval_EvalCodeEx + 2061
11      0x7fdcd883c9fcp PyEval_EvalFrameEx + 26940
12      0x7fdcd883f86dp PyEval_EvalCodeEx + 2061
13      0x7fdcd883f9a2p PyEval_EvalCode + 50
14      0x7fdcd8868782p PyRun_FileExFlags + 146
15      0x7fdcd8869af9p PyRun_SimpleFileExFlags + 217
16      0x7fdcd887f82dp Py_Main + 3149
17      0x7fdcd7a7cbd5p __libc_start_main + 245
18            0x4007a1p

**Comment by lgone2000** [comment]
另一个示例
```

def testpredict1():
    place = fluid.CPUPlace()
    exe = fluid.Executor(place)
    main_program = fluid.default_main_program()
    
    x = fluid.layers.data(name='x', shape=[256], dtype='float32')
    y_predict = fluid.layers.fc(input=x, size=64, act=None)
    reshaped_y_predict = fluid.layers.reshape(x=y_predict, shape=[-1,128], act= None, inplace=True)
    
    #batchnum = 10
    batchnum = 5
    batch_data = [[np.random.rand(256)] for a in range(batchnum)]
    
    feeder = fluid.DataFeeder(place=place, feed_list=[x])
    exe.run(fluid.default_startup_program())
    output = exe.run(main_program,
                                  feed=feeder.feed(batch_data),
                                  fetch_list=[x, y_predict, reshaped_y_predict])
    for o in output:
        print(o.shape)
```
当batchnum=5 时，报下面错误（batchnum=10可以跑），看错误也是搞不清发生了什么。我是把每行单独注释掉，调试才发现问题的，如果是调试一个比较大的网络，查这种错误会浪费用户大量时间。

>testpredict1()
File "mnist.py", line 271, in testpredict1
    fetch_list=[x, y_predict, reshaped_y_predict])
  File "/home/python-gcc482-paddle/lib/python2.7/site-packages/paddle/fluid/executor.py", line 340, in run
    self.executor.run(program.desc, scope, 0, True, True)
paddle.fluid.core.EnforceNotMet: enforce output_shape[unk_dim_idx] * capacity == -in_size failed, -256 != -320
Invalid shape is given. at [/paddle/paddle/fluid/operators/reshape_op.h:102]
PaddlePaddle Call Stacks: 
0       0x7f145a949ad6p paddle::platform::EnforceNotMet::EnforceNotMet(std::__exception_ptr::exception_ptr, char const*, int) + 486
1       0x7f145af0e968p paddle::operators::ReshapeOp::ValidateShape(std::vector<int, std::allocator<int> >, paddle::framework::DDim const&) + 2728
2       0x7f145af0f1dfp paddle::operators::ReshapeOp::InferShape(paddle::framework::InferShapeContext*) const + 703
3       0x7f145b76b18bp paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPl1
4       0x7f145a9e4f87p paddle::framework::Executor::RunPreparedContext(paddle::framework::ExecutorPrepareContext*, paddle::framework::Scope*, bool, bool) + 263
5       0x7f145a9e6024p paddle::framework::Executor::Run(paddle::framework::ProgramDesc const&, paddle::framework::Scope*, int, bool, bool) + 100
6       0x7f145a96275bp void pybind11::cpp_function::initialize<pybind11::cpp_function::initialize<void, paddle::framework::Executor, paddle::framework::ProgramDesc const&, paddle::framework::Scope*, int, b5
7       0x7f145a95ae14p pybind11::cpp_function::dispatcher(_object*, _object*, _object*) + 2596
8       0x7f1499ca755fp PyEval_EvalFrameEx + 29855
9       0x7f1499ca986dp PyEval_EvalCodeEx + 2061
10      0x7f1499ca69fcp PyEval_EvalFrameEx + 26940
11      0x7f1499ca986dp PyEval_EvalCodeEx + 2061
12      0x7f1499ca69fcp PyEval_EvalFrameEx + 26940
13      0x7f1499ca986dp PyEval_EvalCodeEx + 2061
14      0x7f1499ca99a2p PyEval_EvalCode + 50
15      0x7f1499cd2782p PyRun_FileExFlags + 146
16      0x7f1499cd3af9p PyRun_SimpleFileExFlags + 217
17      0x7f1499ce982dp Py_Main + 3149
18      0x7f1498ee6bd5p __libc_start_main + 245
19            0x4007a1p

**Comment by shanyi15** [comment]
您好，此issue在近一个月内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题，我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持! 
 Hello, this issue has not been updated in the past month. We will close it today for the sake of other user‘s experience. If you still need to follow up on this question after closing, please feel free to reopen it. In that case, we will get back to you within 24 hours. We apologize for the inconvenience caused by the closure and thank you so much for your support of PaddlePaddle Group!

**Comment by wopeizl** [comment]
第一步会将op 信息加入到callstack中，方便出错查看。

**Comment by wopeizl** [comment]
https://github.com/PaddlePaddle/Paddle/pull/15204

**Comment by lgone2000** [comment]
目前paddle加上了模型定义的call stack信息，可以帮助定位一部分。
但是有关shape错误的部分，还是和让人看晕。能否把所有这些关于shape的报错，加上详细的信息？
比如 op的名称，输入的具体shape=[x,x,x,x], 以及为啥 shape不匹配。


Enforce failed. Expected output_shape[unk_dim_idx] * capacity == -in_size, but received output_shape[unk_dim_idx] * capacity:-256 != -in_size:-320.
Invalid shape is given. at [/paddle/paddle/fluid/operators/reshape_op.cc:101]

**Comment by lgone2000** [comment]
下面代码的报错信息也让人读不懂， 希望改进

```
def test_message():
    place = fluid.CPUPlace()
    exe = fluid.Executor(place)
    main_program = fluid.default_main_program()
    x = fluid.layers.data(name='x', shape=[10], dtype='float32')
    feature = fluid.layers.fc(input=x, size=20, act=None)
    loss = fluid.layers.reduce_mean(feature)
    optimizer = fluid.optimizer.SGD(learning_rate=0.1)
    if 1:
        #wrong implement
        exe.run(fluid.default_startup_program())
        opts = optimizer.minimize(loss)
    else:
        #correct
        opts = optimizer.minimize(loss)
        exe.run(fluid.default_startup_program())
        
    batch_data = np.random.rand(6,10).astype(np.float32)
    output = exe.run(main_program,feed={'x': batch_data},fetch_list=[loss])
```    
错误信息
```
Traceback (most recent call last):
  File "debugfluid.py", line 404, in <module>
    func(*sys.argv[2:])
  File "debugfluid.py", line 376, in test_message
    output = exe.run(main_program,feed={'x': batch_data},fetch_list=[loss])
  File "/home/users/liuguoyi01/easy-paddle-run/paddle-release/python-gcc482-paddle/lib/python2.7/site-packages/paddle/fluid/executor.py", line 565, in run
    use_program_cache=use_program_cache)
  File "/home/users/liuguoyi01/easy-paddle-run/paddle-release/python-gcc482-paddle/lib/python2.7/site-packages/paddle/fluid/executor.py", line 642, in _run
    exe.run(program.desc, scope, 0, True, True, fetch_var_name)
paddle.fluid.core.EnforceNotMet: Invoke operator sgd error.
Python Callstacks: 
  File "/home/users/liuguoyi01/easy-paddle-run/paddle-release/python-gcc482-paddle/lib/python2.7/site-packages/paddle/fluid/framework.py", line 1654, in append_op
    attrs=kwargs.get("attrs", None))
  File "/home/users/liuguoyi01/easy-paddle-run/paddle-release/python-gcc482-paddle/lib/python2.7/site-packages/paddle/fluid/optimizer.py", line 547, in _append_optimize_op
    stop_gradient=True)
  File "/home/users/liuguoyi01/easy-paddle-run/paddle-release/python-gcc482-paddle/lib/python2.7/site-packages/paddle/fluid/optimizer.py", line 296, in _create_optimization_pass
    param_and_grad)
  File "/home/users/liuguoyi01/easy-paddle-run/paddle-release/python-gcc482-paddle/lib/python2.7/site-packages/paddle/fluid/optimizer.py", line 441, in apply_gradients
    optimize_ops = self._create_optimization_pass(params_grads)
  File "/home/users/liuguoyi01/easy-paddle-run/paddle-release/python-gcc482-paddle/lib/python2.7/site-packages/paddle/fluid/optimizer.py", line 469, in apply_optimize
    optimize_ops = self.apply_gradients(params_grads)
  File "/home/users/liuguoyi01/easy-paddle-run/paddle-release/python-gcc482-paddle/lib/python2.7/site-packages/paddle/fluid/optimizer.py", line 500, in minimize
    loss, startup_program=startup_program, params_grads=params_grads)
  File "debugfluid.py", line 374, in test_message
    opts = optimizer.minimize(loss)
  File "debugfluid.py", line 404, in <module>
    func(*sys.argv[2:])
C++ Callstacks: 
Enforce failed. Expected framework::product(lr_dims) == 1, but received framework::product(lr_dims):0 != 1:1.
Learning rate should have 1 element at [/paddle/paddle/fluid/operators/optimizers/sgd_op.cc:36]
PaddlePaddle Call Stacks: 
0       0x7fda404f5b68p void paddle::platform::EnforceNotMet::Init<std::string>(std::string, char const*, int) + 360
1       0x7fda404f5eb7p paddle::platform::EnforceNotMet::EnforceNotMet(std::string const&, char const*, int) + 87
2       0x7fda4177d6d4p paddle::operators::SGDOp::InferShape(paddle::framework::InferShapeContext*) const + 1492
3       0x7fda421876a8p paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&, paddle::framework::RuntimeContext*) const + 584
4       0x7fda42187e64p paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&) const + 292
5       0x7fda4218578cp paddle::framework::OperatorBase::Run(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&) + 332
6       0x7fda4066a8bep paddle::framework::Executor::RunPreparedContext(paddle::framework::ExecutorPrepareContext*, paddle::framework::Scope*, bool, bool, bool) + 382
7       0x7fda4066b6ffp paddle::framework::Executor::Run(paddle::framework::ProgramDesc const&, paddle::framework::Scope*, int, bool, bool, std::vector<std::string, std::allocator<std::string> > const&, bool) + 143
8       0x7fda404e535ep
9       0x7fda4052872ep
10      0x7fda8e4f055fp PyEval_EvalFrameEx + 29855
11      0x7fda8e4f286dp PyEval_EvalCodeEx + 2061
12      0x7fda8e4ef9fcp PyEval_EvalFrameEx + 26940
13      0x7fda8e4f286dp PyEval_EvalCodeEx + 2061
14      0x7fda8e4ef9fcp PyEval_EvalFrameEx + 26940
15      0x7fda8e4f286dp PyEval_EvalCodeEx + 2061
16      0x7fda8e468f40p
17      0x7fda8e436f13p PyObject_Call + 67
18      0x7fda8e4ec657p PyEval_EvalFrameEx + 13719
19      0x7fda8e4f286dp PyEval_EvalCodeEx + 2061
20      0x7fda8e4f29a2p PyEval_EvalCode + 50
21      0x7fda8e51b782p PyRun_FileExFlags + 146
22      0x7fda8e51caf9p PyRun_SimpleFileExFlags + 217
23      0x7fda8e53282dp Py_Main + 3149
24      0x7fda8d72fbd5p __libc_start_main + 245
25            0x4007a1p
```

**Comment by lgone2000** [comment]
1.6 版本 跑前面的 testpredict1
增量了下面有关 shape的详细信息，因此testpredict1 解决了
ShapeError: The 'shape' in ReshapeOp is invalid. The input tensor X'size must be divisible by known capacity of 'shape'. But received X's shape = [5, 64], X's size = 320, 'shape' is [-1, 128], known capacity of 'shape' is -128. at [/paddle/paddle/fluid/operators/reshape_op.cc:184]
  [operator < reshape2 > error]


> 另一个示例
> 
> ```
> 
> def testpredict1():
>     place = fluid.CPUPlace()
>     exe = fluid.Executor(place)
>     main_program = fluid.default_main_program()
>     
>     x = fluid.layers.data(name='x', shape=[256], dtype='float32')
>     y_predict = fluid.layers.fc(input=x, size=64, act=None)
>     reshaped_y_predict = fluid.layers.reshape(x=y_predict, shape=[-1,128], act= None, inplace=True)
>     
>     #batchnum = 10
>     batchnum = 5
>     batch_data = [[np.random.rand(256)] for a in range(batchnum)]
>     
>     feeder = fluid.DataFeeder(place=place, feed_list=[x])
>     exe.run(fluid.default_startup_program())
>     output = exe.run(main_program,
>                                   feed=feeder.feed(batch_data),
>                                   fetch_list=[x, y_predict, reshaped_y_predict])
>     for o in output:
>         print(o.shape)
> ```
> 
> 当batchnum=5 时，报下面错误（batchnum=10可以跑），看错误也是搞不清发生了什么。我是把每行单独注释掉，调试才发现问题的，如果是调试一个比较大的网络，查这种错误会浪费用户大量时间。
> 
> > testpredict1()
> > File "mnist.py", line 271, in testpredict1
> > fetch_list=[x, y_predict, reshaped_y_predict])
> > File "/home/python-gcc482-paddle/lib/python2.7/site-packages/paddle/fluid/executor.py", line 340, in run
> > self.executor.run(program.desc, scope, 0, True, True)
> > paddle.fluid.core.EnforceNotMet: enforce output_shape[unk_dim_idx] * capacity == -in_size failed, -256 != -320
> > Invalid shape is given. at [/paddle/paddle/fluid/operators/reshape_op.h:102]
> > PaddlePaddle Call Stacks:
> > 0       0x7f145a949ad6p paddle::platform::EnforceNotMet::EnforceNotMet(std::__exception_ptr::exception_ptr, char const*, int) + 486
> > 1       0x7f145af0e968p paddle::operators::ReshapeOp::ValidateShape(std::vector<int, std::allocator >, paddle::framework::DDim const&) + 2728
> > 2       0x7f145af0f1dfp paddle::operators::ReshapeOp::InferShape(paddle::framework::InferShapeContext*) const + 703
> > 3       0x7f145b76b18bp paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPl1
> > 4       0x7f145a9e4f87p paddle::framework::Executor::RunPreparedContext(paddle::framework::ExecutorPrepareContext*, paddle::framework::Scope*, bool, bool) + 263
> > 5       0x7f145a9e6024p paddle::framework::Executor::Run(paddle::framework::ProgramDesc const&, paddle::framework::Scope*, int, bool, bool) + 100
> > 6       0x7f145a96275bp void pybind11::cpp_function::initialize<pybind11::cpp_function::initialize<void, paddle::framework::Executor, paddle::framework::ProgramDesc const&, paddle::framework::Scope*, int, b5
> > 7       0x7f145a95ae14p pybind11::cpp_function::dispatcher(_object*, _object*, _object*) + 2596
> > 8       0x7f1499ca755fp PyEval_EvalFrameEx + 29855
> > 9       0x7f1499ca986dp PyEval_EvalCodeEx + 2061
> > 10      0x7f1499ca69fcp PyEval_EvalFrameEx + 26940
> > 11      0x7f1499ca986dp PyEval_EvalCodeEx + 2061
> > 12      0x7f1499ca69fcp PyEval_EvalFrameEx + 26940
> > 13      0x7f1499ca986dp PyEval_EvalCodeEx + 2061
> > 14      0x7f1499ca99a2p PyEval_EvalCode + 50
> > 15      0x7f1499cd2782p PyRun_FileExFlags + 146
> > 16      0x7f1499cd3af9p PyRun_SimpleFileExFlags + 217
> > 17      0x7f1499ce982dp Py_Main + 3149
> > 18      0x7f1498ee6bd5p __libc_start_main + 245
> > 19            0x4007a1p

**Comment by lgone2000** [comment]
最新版本1.6 跑test_message ， 发现增加下面调试信息，因此test_message  问题也解决了

Maybe the Input variable LearningRate has not been initialized. You may need to confirm if you put exe.run(startup_program) after optimizer.minimize function. at [/paddle/paddle/fluid/operators/optimizers/sgd_op.cc:39]
  [operator < sgd > error]

> 下面代码的报错信息也让人读不懂， 希望改进
> 
> ```
> def test_message():
>     place = fluid.CPUPlace()
>     exe = fluid.Executor(place)
>     main_program = fluid.default_main_program()
>     x = fluid.layers.data(name='x', shape=[10], dtype='float32')
>     feature = fluid.layers.fc(input=x, size=20, act=None)
>     loss = fluid.layers.reduce_mean(feature)
>     optimizer = fluid.optimizer.SGD(learning_rate=0.1)
>     if 1:
>         #wrong implement
>         exe.run(fluid.default_startup_program())
>         opts = optimizer.minimize(loss)
>     else:
>         #correct
>         opts = optimizer.minimize(loss)
>         exe.run(fluid.default_startup_program())
>         
>     batch_data = np.random.rand(6,10).astype(np.float32)
>     output = exe.run(main_program,feed={'x': batch_data},fetch_list=[loss])
> ```
> 
> 错误信息
> 
> ```
> Traceback (most recent call last):
>   File "debugfluid.py", line 404, in <module>
>     func(*sys.argv[2:])
>   File "debugfluid.py", line 376, in test_message
>     output = exe.run(main_program,feed={'x': batch_data},fetch_list=[loss])
>   File "/home/users/liuguoyi01/easy-paddle-run/paddle-release/python-gcc482-paddle/lib/python2.7/site-packages/paddle/fluid/executor.py", line 565, in run
>     use_program_cache=use_program_cache)
>   File "/home/users/liuguoyi01/easy-paddle-run/paddle-release/python-gcc482-paddle/lib/python2.7/site-packages/paddle/fluid/executor.py", line 642, in _run
>     exe.run(program.desc, scope, 0, True, True, fetch_var_name)
> paddle.fluid.core.EnforceNotMet: Invoke operator sgd error.
> Python Callstacks: 
>   File "/home/users/liuguoyi01/easy-paddle-run/paddle-release/python-gcc482-paddle/lib/python2.7/site-packages/paddle/fluid/framework.py", line 1654, in append_op
>     attrs=kwargs.get("attrs", None))
>   File "/home/users/liuguoyi01/easy-paddle-run/paddle-release/python-gcc482-paddle/lib/python2.7/site-packages/paddle/fluid/optimizer.py", line 547, in _append_optimize_op
>     stop_gradient=True)
>   File "/home/users/liuguoyi01/easy-paddle-run/paddle-release/python-gcc482-paddle/lib/python2.7/site-packages/paddle/fluid/optimizer.py", line 296, in _create_optimization_pass
>     param_and_grad)
>   File "/home/users/liuguoyi01/easy-paddle-run/paddle-release/python-gcc482-paddle/lib/python2.7/site-packages/paddle/fluid/optimizer.py", line 441, in apply_gradients
>     optimize_ops = self._create_optimization_pass(params_grads)
>   File "/home/users/liuguoyi01/easy-paddle-run/paddle-release/python-gcc482-paddle/lib/python2.7/site-packages/paddle/fluid/optimizer.py", line 469, in apply_optimize
>     optimize_ops = self.apply_gradients(params_grads)
>   File "/home/users/liuguoyi01/easy-paddle-run/paddle-release/python-gcc482-paddle/lib/python2.7/site-packages/paddle/fluid/optimizer.py", line 500, in minimize
>     loss, startup_program=startup_program, params_grads=params_grads)
>   File "debugfluid.py", line 374, in test_message
>     opts = optimizer.minimize(loss)
>   File "debugfluid.py", line 404, in <module>
>     func(*sys.argv[2:])
> C++ Callstacks: 
> Enforce failed. Expected framework::product(lr_dims) == 1, but received framework::product(lr_dims):0 != 1:1.
> Learning rate should have 1 element at [/paddle/paddle/fluid/operators/optimizers/sgd_op.cc:36]
> PaddlePaddle Call Stacks: 
> 0       0x7fda404f5b68p void paddle::platform::EnforceNotMet::Init<std::string>(std::string, char const*, int) + 360
> 1       0x7fda404f5eb7p paddle::platform::EnforceNotMet::EnforceNotMet(std::string const&, char const*, int) + 87
> 2       0x7fda4177d6d4p paddle::operators::SGDOp::InferShape(paddle::framework::InferShapeContext*) const + 1492
> 3       0x7fda421876a8p paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&, paddle::framework::RuntimeContext*) const + 584
> 4       0x7fda42187e64p paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&) const + 292
> 5       0x7fda4218578cp paddle::framework::OperatorBase::Run(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&) + 332
> 6       0x7fda4066a8bep paddle::framework::Executor::RunPreparedContext(paddle::framework::ExecutorPrepareContext*, paddle::framework::Scope*, bool, bool, bool) + 382
> 7       0x7fda4066b6ffp paddle::framework::Executor::Run(paddle::framework::ProgramDesc const&, paddle::framework::Scope*, int, bool, bool, std::vector<std::string, std::allocator<std::string> > const&, bool) + 143
> 8       0x7fda404e535ep
> 9       0x7fda4052872ep
> 10      0x7fda8e4f055fp PyEval_EvalFrameEx + 29855
> 11      0x7fda8e4f286dp PyEval_EvalCodeEx + 2061
> 12      0x7fda8e4ef9fcp PyEval_EvalFrameEx + 26940
> 13      0x7fda8e4f286dp PyEval_EvalCodeEx + 2061
> 14      0x7fda8e4ef9fcp PyEval_EvalFrameEx + 26940
> 15      0x7fda8e4f286dp PyEval_EvalCodeEx + 2061
> 16      0x7fda8e468f40p
> 17      0x7fda8e436f13p PyObject_Call + 67
> 18      0x7fda8e4ec657p PyEval_EvalFrameEx + 13719
> 19      0x7fda8e4f286dp PyEval_EvalCodeEx + 2061
> 20      0x7fda8e4f29a2p PyEval_EvalCode + 50
> 21      0x7fda8e51b782p PyRun_FileExFlags + 146
> 22      0x7fda8e51caf9p PyRun_SimpleFileExFlags + 217
> 23      0x7fda8e53282dp Py_Main + 3149
> 24      0x7fda8d72fbd5p __libc_start_main + 245
> 25            0x4007a1p
> ```

**Comment by luotao1** [comment]
总结下：该ISSUE里面报了3个调试信息相关问题， 
- [test_predict](https://github.com/PaddlePaddle/Paddle/issues/11371#issuecomment-397889817): 没有初始化`default_startup_program`。（1.6未解决）#20906 解决
- [testpredict1](https://github.com/PaddlePaddle/Paddle/issues/11371#issuecomment-397891646): reshape_op中Shape报错信息补全。（1.6已解决）
- [test_message](https://github.com/PaddlePaddle/Paddle/issues/11371#issuecomment-492494423)：optimizer.minimize敏感性的问题。（1.6已解决）
