### ISSUE TITLE
cluster_config is not defined

### ISSUE THREAD

**Issue by cbstyle** [PaddlePaddle/Paddle#11389]
paddle集群训练，由原来的reveiver提交方式改成本地提交方式，代码是V1版本；
出现NameError: name 'cluster_config' is not defined错误；

Tue Jun 12 12:19:08 2018[1,7]<stderr>:+ python27-gcc482/bin/python conf/video_mean_conf.py
Tue Jun 12 12:19:08 2018[1,7]<stderr>:Traceback (most recent call last):
Tue Jun 12 12:19:08 2018[1,7]<stderr>:  File "./http_server.py", line 41, in <module>
Tue Jun 12 12:19:08 2018[1,7]<stderr>:    server = ThreadingSimpleServer(('', port), SimpleHTTPRequestHandler)
Tue Jun 12 12:19:08 2018[1,7]<stderr>:  File "/home/disk1/normandy/maybach/app-user-20180612114513-359/workspace/python27-gcc482/lib/python2.7/SocketServer.py", line 420, in __init__
Tue Jun 12 12:19:08 2018[1,7]<stderr>:    self.server_bind()
Tue Jun 12 12:19:08 2018[1,7]<stderr>:  File "/home/disk1/normandy/maybach/app-user-20180612114513-359/workspace/python27-gcc482/lib/python2.7/BaseHTTPServer.py", line 108, in server_bind
Tue Jun 12 12:19:08 2018[1,7]<stderr>:    SocketServer.TCPServer.server_bind(self)
Tue Jun 12 12:19:08 2018[1,7]<stderr>:  File "/home/disk1/normandy/maybach/app-user-20180612114513-359/workspace/python27-gcc482/lib/python2.7/SocketServer.py", line 434, in server_bind
Tue Jun 12 12:19:08 2018[1,7]<stderr>:    self.socket.bind(self.server_address)
Tue Jun 12 12:19:08 2018[1,7]<stderr>:  File "/home/disk1/normandy/maybach/app-user-20180612114513-359/workspace/python27-gcc482/lib/python2.7/socket.py", line 228, in meth
Tue Jun 12 12:19:08 2018[1,7]<stderr>:    return getattr(self._sock,name)(*args)
Tue Jun 12 12:19:08 2018[1,7]<stderr>:socket.error: [Errno 98] Address already in use
Tue Jun 12 12:19:08 2018[1,7]<stderr>:Traceback (most recent call last):
Tue Jun 12 12:19:08 2018[1,7]<stderr>:  File "conf/video_mean_conf.py", line 14, in <module>
Tue Jun 12 12:19:08 2018[1,7]<stderr>:    cluster_config(
Tue Jun 12 12:19:08 2018[1,7]<stderr>:NameError: name 'cluster_config' is not defined

**Comment by Yancey1989** [comment]
Hi 您好，

```python
NameError: name 'cluster_config' is not defined
```

`cluster_config`模块是v1的receiver会将其解析成MPI客户端需要的一些配置参数。由于本地提交只支持V2的API，所以会报这个错，建议使用V2的API或者内网环境的PaddleCloud（支持Fluid）。
