### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by pzz2011** [PaddlePaddle/Paddle#1140]
mkdir build
cd build
cmake ..
```
...................
CMake Error at cmake/external/python.cmake:29 (IF):
  if given arguments:

    "VERSION_LESS" "3.0.0"

  Unknown arguments specified
Call Stack (most recent call first):
  CMakeLists.txt:63 (include)


-- Configuring incomplete, errors occurred!
See also "/home/pzz/workspace/paddle/build/CMakeFiles/CMakeOutput.log".
See also "/home/pzz/workspace/paddle/build/CMakeFiles/CMakeError.log".
pzz@suu:~/workspace/paddle/build$ vim CMakeFiles/CMakeError.log 
pzz@suu:~/workspace/paddle/build$ cat CMakeFiles/CMakeError.log 
Determining if the pthread_create exist failed with the following output:
Change Dir: /home/pzz/workspace/paddle/build/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/make" "cmTC_5f84c/fast"
/usr/bin/make -f CMakeFiles/cmTC_5f84c.dir/build.make CMakeFiles/cmTC_5f84c.dir/build
make[1]: Entering directory '/home/pzz/workspace/paddle/build/CMakeFiles/CMakeTmp'
Building C object CMakeFiles/cmTC_5f84c.dir/CheckSymbolExists.c.o
/usr/bin/cc    -fPIC    -o CMakeFiles/cmTC_5f84c.dir/CheckSymbolExists.c.o   -c /home/pzz/workspace/paddle/build/CMakeFiles/CMakeTmp/CheckSymbolExists.c
Linking C executable cmTC_5f84c
/usr/bin/cmake -E cmake_link_script CMakeFiles/cmTC_5f84c.dir/link.txt --verbose=1
/usr/bin/cc  -fPIC     CMakeFiles/cmTC_5f84c.dir/CheckSymbolExists.c.o  -o cmTC_5f84c -rdynamic 
CMakeFiles/cmTC_5f84c.dir/CheckSymbolExists.c.o: In function `main':
CheckSymbolExists.c:(.text+0x1b): undefined reference to `pthread_create'
collect2: error: ld returned 1 exit status
CMakeFiles/cmTC_5f84c.dir/build.make:97: recipe for target 'cmTC_5f84c' failed
make[1]: *** [cmTC_5f84c] Error 1
make[1]: Leaving directory '/home/pzz/workspace/paddle/build/CMakeFiles/CMakeTmp'
Makefile:126: recipe for target 'cmTC_5f84c/fast' failed
make: *** [cmTC_5f84c/fast] Error 2

File /home/pzz/workspace/paddle/build/CMakeFiles/CMakeTmp/CheckSymbolExists.c:
/* */
#include <pthread.h>

int main(int argc, char** argv)
{
  (void)argv;
#ifndef pthread_create
  return ((int*)(&pthread_create))[argc];
#else
  (void)argc;
  return 0;
#endif
}

Determining if the function pthread_create exists in the pthreads failed with the following output:
Change Dir: /home/pzz/workspace/paddle/build/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/make" "cmTC_2aa2e/fast"
/usr/bin/make -f CMakeFiles/cmTC_2aa2e.dir/build.make CMakeFiles/cmTC_2aa2e.dir/build
make[1]: Entering directory '/home/pzz/workspace/paddle/build/CMakeFiles/CMakeTmp'
Building C object CMakeFiles/cmTC_2aa2e.dir/CheckFunctionExists.c.o
/usr/bin/cc    -fPIC -DCHECK_FUNCTION_EXISTS=pthread_create   -o CMakeFiles/cmTC_2aa2e.dir/CheckFunctionExists.c.o   -c /usr/share/cmake-3.5/Modules/CheckFunctionExists.c
Linking C executable cmTC_2aa2e
/usr/bin/cmake -E cmake_link_script CMakeFiles/cmTC_2aa2e.dir/link.txt --verbose=1
/usr/bin/cc  -fPIC -DCHECK_FUNCTION_EXISTS=pthread_create    CMakeFiles/cmTC_2aa2e.dir/CheckFunctionExists.c.o  -o cmTC_2aa2e -rdynamic -lpthreads 
/usr/bin/ld: cannot find -lpthreads
collect2: error: ld returned 1 exit status
CMakeFiles/cmTC_2aa2e.dir/build.make:97: recipe for target 'cmTC_2aa2e' failed
make[1]: *** [cmTC_2aa2e] Error 1
make[1]: Leaving directory '/home/pzz/workspace/paddle/build/CMakeFiles/CMakeTmp'
Makefile:126: recipe for target 'cmTC_2aa2e/fast' failed
make: *** [cmTC_2aa2e/fast] Error 2

```
the error information reports that cannot find -lpthreads,
while I have double-checked my machine has libpthread.so

so, what's the problem

**Comment by reyoung** [comment]
It seems that cmake cannot find python package `protobuf`. We will check this error and give a definite answer.  @gangliao

**Comment by pzz2011** [comment]
@reyoung  while I have installed it(I have double-checked this trueth)

**Comment by pzz2011** [comment]
I setup environment is:
ubuntu 16.04
python2.7
cmake 3.5.1

**Comment by backyes** [comment]
@gangliao  

```
/usr/bin/cc  -fPIC     CMakeFiles/cmTC_5f84c.dir/CheckSymbolExists.c.o  -o cmTC_5f84c -rdynamic 
CMakeFiles/cmTC_5f84c.dir/CheckSymbolExists.c.o: In function `main':
CheckSymbolExists.c:(.text+0x1b): undefined reference to `pthread_create'
```
直观上，pthread链接阶段少了 ```-lpthread```,  这个可能是线索。

**Comment by gangliao** [comment]
@reyoung @backyes   我处理一下吧  我感觉还是python  protobuf哪里有点问题。pthread我也验证一下  我用ubuntu虚拟机

**Comment by pzz2011** [comment]
The problem is incurred by the cmake/external/python.cmake line29-line31 which is inconsistent to 
the offical document which says that paddle only supports protobuf version <3.0.0

So,please modify the document at least and comment the line29-line31 @reyoung @gangliao

**Comment by gangliao** [comment]
@pzz2011  Sorry for inconsistency about docs and code, all docs already updated at develop branch https://github.com/PaddlePaddle/Paddle/blame/develop/doc/getstarted/build_and_install/build_from_source_en.md#L104

**Comment by harlanxu** [comment]
@pzz2011  may be the problem comes from file privileges,I encount a similar problem,just try to issue

chmod 777  [root folder of paddle]

**Comment by pzz2011** [comment]
Here is another error generated now:
```
gtest.h:1392:11: error: comparison between signed and unsigned integer expressions [-Werror=sign-compare]

```
I have tried to export several flags while It still came to failure.

**Comment by pzz2011** [comment]
@harlanxu It seems it doesn't need 777 to solve this issue. thanks

**Comment by gangliao** [comment]
@pzz2011 Can you post your gcc version

**Comment by pzz2011** [comment]
gcc 5.4.0. 
too higher?

**Comment by gangliao** [comment]
I only test it on gcc 4.8 and AppleClang. I will add higher version of gcc in Travis CI. @pzz2011 Thanks

**Comment by pzz2011** [comment]
so how can I pass this compile process if i don't want to downgrade my gcc version?
@gangliao

**Comment by gangliao** [comment]
```
gtest.h:1392:11: error: comparison between signed and unsigned integer expressions [-Werror=sign-compare]
```

It seems that some code in Paddle use unmatched type to `CHECK_EQ(singed, unsigned)`, you can also help us to fix it via simply convert types into match type, like CHECK_EQ(signed, signed).

**Comment by gangliao** [comment]
@pzz2011 
You can also give me more detail error info:
```
......
.......
gtest.h:1392:11: error: comparison between signed and unsigned integer expressions [-Werror=sign-compare]
....
.....
```

**Comment by pzz2011** [comment]
the error info I reported to you is the only error infomation.....

**Comment by gangliao** [comment]
@pzz2011 Can you give me more context info？Since I don't know where trigger off it.

**Comment by gangliao** [comment]
@pzz2011  You can also use Docker. http://www.paddlepaddle.org/doc/build/docker_install.html

**Comment by pzz2011** [comment]
pzz@suu:~/workspace/Paddle/build/paddle$ make
[ 99%] Built target glog
[ 99%] Built target gtest
[ 99%] Built target gflags
[ 99%] Built target zlib
[ 99%] Built target warpctc
[ 99%] Built target protobuf
[ 99%] Built target paddle_cuda
[ 99%] Built target gen_proto_cpp
[ 99%] Built target paddle_trainer_lib
[ 99%] Built target paddle_proto
[ 99%] Built target paddle_function
[ 99%] Built target paddle_utils
[ 99%] Built target paddle_test_util
[ 99%] Built target paddle_test_main
[ 99%] Built target paddle_math
[ 99%] Built target paddle_parameter
[ 99%] Built target paddle_gserver
[ 99%] Built target paddle_pserver
[ 99%] Built target paddle_network
[ 99%] Building CXX object paddle/function/CMakeFiles/TensorTypeTest.dir/TensorTypeTest.cpp.o
In file included from /home/pzz/workspace/Paddle/paddle/function/TensorTypeTest.cpp:16:0:
/home/pzz/workspace/Paddle/third_party/install/gtest/include/gtest/gtest.h: In instantiation of ‘testing::AssertionResult testing::internal::CmpHelperEQ(const char*, const char*, const T1&, const T2&) [with T1 = long unsigned int; T2 = int]’:
/home/pzz/workspace/Paddle/third_party/install/gtest/include/gtest/gtest.h:1421:23:   required from ‘static testing::AssertionResult testing::internal::EqHelper<lhs_is_null_literal>::Compare(const char*, const char*, const T1&, const T2&) [with T1 = long unsigned int; T2 = int; bool lhs_is_null_literal = false]’
/home/pzz/workspace/Paddle/paddle/function/TensorTypeTest.cpp:22:3:   required from here
/home/pzz/workspace/Paddle/third_party/install/gtest/include/gtest/gtest.h:1392:11: error: comparison between signed and unsigned integer expressions [-Werror=sign-compare]
   if (lhs == rhs) {
           ^
cc1plus: all warnings being treated as errors
paddle/function/CMakeFiles/TensorTypeTest.dir/build.make:62: recipe for target 'paddle/function/CMakeFiles/TensorTypeTest.dir/TensorTypeTest.cpp.o' failed
make[2]: *** [paddle/function/CMakeFiles/TensorTypeTest.dir/TensorTypeTest.cpp.o] Error 1
CMakeFiles/Makefile2:588: recipe for target 'paddle/function/CMakeFiles/TensorTypeTest.dir/all' failed
make[1]: *** [paddle/function/CMakeFiles/TensorTypeTest.dir/all] Error 2
Makefile:160: recipe for target 'all' failed
make: *** [all] Error 2
@gangliao

**Comment by pzz2011** [comment]
```
In file included from /home/pzz/workspace/Paddle/paddle/function/TensorShapeTest.cpp:16:0:
/home/pzz/workspace/Paddle/third_party/install/gtest/include/gtest/gtest.h: In instantiation of ‘testing::AssertionResult testing::internal::CmpHelperEQ(const char*, const char*, const T1&, const T2&) [with T1 = long unsigned int; T2 = int]’:
/home/pzz/workspace/Paddle/third_party/install/gtest/include/gtest/gtest.h:1421:23:   required from ‘static testing::AssertionResult testing::internal::EqHelper<lhs_is_null_literal>::Compare(const char*, const char*, const T1&, const T2&) [with T1 = long unsigned int; T2 = int; bool lhs_is_null_literal = false]’
/home/pzz/workspace/Paddle/paddle/function/TensorShapeTest.cpp:22:3:   required from here
/home/pzz/workspace/Paddle/third_party/install/gtest/include/gtest/gtest.h:1392:11: error: comparison between signed and unsigned integer expressions [-Werror=sign-compare]
   if (lhs == rhs) {
           ^
cc1plus: all warnings being treated as errors
paddle/function/CMakeFiles/TensorShapeTest.dir/build.make:62: recipe for target 'paddle/function/CMakeFiles/TensorShapeTest.dir/TensorShapeTest.cpp.o' failed
make[2]: *** [paddle/function/CMakeFiles/TensorShapeTest.dir/TensorShapeTest.cpp.o] Error 1
CMakeFiles/Makefile2:696: recipe for target 'paddle/function/CMakeFiles/TensorShapeTest.dir/all' failed
make[1]: *** [paddle/function/CMakeFiles/TensorShapeTest.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
In file included from /home/pzz/workspace/Paddle/paddle/function/FunctionTest.cpp:16:0:
/home/pzz/workspace/Paddle/third_party/install/gtest/include/gtest/gtest.h: In instantiation of ‘testing::AssertionResult testing::internal::CmpHelperEQ(const char*, const char*, const T1&, const T2&) [with T1 = long unsigned int; T2 = int]’:
/home/pzz/workspace/Paddle/third_party/install/gtest/include/gtest/gtest.h:1421:23:   required from ‘static testing::AssertionResult testing::internal::EqHelper<lhs_is_null_literal>::Compare(const char*, const char*, const T1&, const T2&) [with T1 = long unsigned int; T2 = int; bool lhs_is_null_literal = false]’
/home/pzz/workspace/Paddle/paddle/function/FunctionTest.cpp:26:3:   required from here
/home/pzz/workspace/Paddle/third_party/install/gtest/include/gtest/gtest.h:1392:11: error: comparison between signed and unsigned integer expressions [-Werror=sign-compare]
   if (lhs == rhs) {
           ^
In file included from /home/pzz/workspace/Paddle/paddle/function/BufferArgTest.cpp:16:0:
/home/pzz/workspace/Paddle/third_party/install/gtest/include/gtest/gtest.h: In instantiation of ‘testing::AssertionResult testing::internal::CmpHelperEQ(const char*, const char*, const T1&, const T2&) [with T1 = long unsigned int; T2 = int]’:
/home/pzz/workspace/Paddle/third_party/install/gtest/include/gtest/gtest.h:1421:23:   required from ‘static testing::AssertionResult testing::internal::EqHelper<lhs_is_null_literal>::Compare(const char*, const char*, const T1&, const T2&) [with T1 = long unsigned int; T2 = int; bool lhs_is_null_literal = false]’
/home/pzz/workspace/Paddle/paddle/function/BufferArgTest.cpp:37:3:   required from here
/home/pzz/workspace/Paddle/third_party/install/gtest/include/gtest/gtest.h:1392:11: error: comparison between signed and unsigned integer expressions [-Werror=sign-compare]
   if (lhs == rhs) {
           ^
In file included from /home/pzz/workspace/Paddle/paddle/function/TensorTypeTest.cpp:16:0:
/home/pzz/workspace/Paddle/third_party/install/gtest/include/gtest/gtest.h: In instantiation of ‘testing::AssertionResult testing::internal::CmpHelperEQ(const char*, const char*, const T1&, const T2&) [with T1 = long unsigned int; T2 = int]’:
/home/pzz/workspace/Paddle/third_party/install/gtest/include/gtest/gtest.h:1421:23:   required from ‘static testing::AssertionResult testing::internal::EqHelper<lhs_is_null_literal>::Compare(const char*, const char*, const T1&, const T2&) [with T1 = long unsigned int; T2 = int; bool lhs_is_null_literal = false]’
/home/pzz/workspace/Paddle/paddle/function/TensorTypeTest.cpp:36:3:   required from here
/home/pzz/workspace/Paddle/third_party/install/gtest/include/gtest/gtest.h:1392:11: error: comparison between signed and unsigned integer expressions [-Werror=sign-compare]
   if (lhs == rhs) {
           ^
cc1plus: all warnings being treated as errors
cc1plus: all warnings being treated as errors
paddle/function/CMakeFiles/TensorTypeTest.dir/build.make:62: recipe for target 'paddle/function/CMakeFiles/TensorTypeTest.dir/TensorTypeTest.cpp.o' failed
make[2]: *** [paddle/function/CMakeFiles/TensorTypeTest.dir/TensorTypeTest.cpp.o] Error 1
CMakeFiles/Makefile2:588: recipe for target 'paddle/function/CMakeFiles/TensorTypeTest.dir/all' failed
make[1]: *** [paddle/function/CMakeFiles/TensorTypeTest.dir/all] Error 2
paddle/function/CMakeFiles/FunctionTest.dir/build.make:62: recipe for target 'paddle/function/CMakeFiles/FunctionTest.dir/FunctionTest.cpp.o' failed
make[2]: *** [paddle/function/CMakeFiles/FunctionTest.dir/FunctionTest.cpp.o] Error 1
CMakeFiles/Makefile2:792: recipe for target 'paddle/function/CMakeFiles/FunctionTest.dir/all' failed
make[1]: *** [paddle/function/CMakeFiles/FunctionTest.dir/all] Error 2
cc1plus: all warnings being treated as errors
paddle/function/CMakeFiles/BufferArgTest.dir/build.make:62: recipe for target 'paddle/function/CMakeFiles/BufferArgTest.dir/BufferArgTest.cpp.o' failed
make[2]: *** [paddle/function/CMakeFiles/BufferArgTest.dir/BufferArgTest.cpp.o] Error 1
CMakeFiles/Makefile2:642: recipe for target 'paddle/function/CMakeFiles/BufferArgTest.dir/all' failed
make[1]: *** [paddle/function/CMakeFiles/BufferArgTest.dir/all] Error 2
Makefile:160: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by Noplz** [comment]
I have the same problem like 
Paddle/third_party/install/gtest/include/gtest/gtest.h:1392:11: error: comparison between signed and unsigned integer expressions [-Werror=sign-compare]
   if (lhs == rhs)

**Comment by pzz2011** [comment]
all these erorr is from the unit test....maybe because the type unmatch?
these function including:
```
xx.getSzie() xx.getElement() xx.....
```
and some unit test don't conform the code style <= 80 which will cause error .
@reyoung 
@gangliao

**Comment by reyoung** [comment]
@pzz2011 Sorry for this error.

You may disable compile unit test to get rid of type mismatch errors, by set CMAKE option `-DWITH_TESTING=OFF`

I will give another Pull Request, add type mismatch checks ASAP.

**Comment by pzz2011** [comment]
@reyoung If I compile Paddle using the flag -DWITH_GPU=ON only, it can pass the compile process.
While I using all flags..... here comes another error.....

**Comment by gangliao** [comment]
@pzz2011  To best of my knowledge,  for CUDA 7.0 and CUDA 7.5, GCC 5.0 and up are not supported. For CUDA 8.0, GCC versions later than 5.3 are not supported.

**Comment by pzz2011** [comment]
my setup environment is CUDA8.0 and gcc 5.4.0....sadly :-(

**Comment by gangliao** [comment]
You'd better install GCC 4.9 which seems more compatible with CUDA.

**Comment by pzz2011** [comment]
@gangliao thanks for your advice.
If I encounter more trouble, I will adopt it.

now

**Comment by alvations** [comment]
This issue from https://github.com/PaddlePaddle/Paddle/issues/1140#issuecomment-272426007 that returns the `make: *** [all] Error 2` still exist in the latest `develop` branch on Ubuntu 16.04 compiling from source 

```
Makefile:160: recipe for target 'all' failed
make: *** [all] Error 2
```

The develop branch I'm compiling from:

```
~/paddle$ git log
commit 0e2acb8ba4bc794b240a28e6fce88ec8d757e90c
Merge: c9d7871 22b5a38
Author: 乔龙飞 <jacquesqiao@users.noreply.github.com>
Date:   Wed Jun 14 07:42:27 2017 +0800

    Merge pull request #2433 from helinwang/pserver_test
    
    Modify pserver client C API, create better test.
```

I had to use the following to successfully compile and install:

```
~/paddle$ mkdir build && cd build
~/paddle/build$ cmake .. -DWITH_TESTING=OFF
```

**Comment by supertonyliu** [comment]
I meet same problem , the error information is following:

Determining if the pthread_create exist failed with the following output:
Change Dir: /paddle/build/CMakeFiles/CMakeTmp
Run Build Command:"/usr/bin/gmake" "cmTC_c6cfa/fast"
/usr/bin/gmake -f CMakeFiles/cmTC_c6cfa.dir/build.make CMakeFiles/cmTC_c6cfa.dir/build
gmake[1]: Entering directory `/paddle/build/CMakeFiles/CMakeTmp'
Building C object CMakeFiles/cmTC_c6cfa.dir/CheckSymbolExists.c.o
/opt/rh/devtoolset-2/root/usr/bin/cc    -fPIC    -o CMakeFiles/cmTC_c6cfa.dir/CheckSymbolExists.c.o   -c /paddle/build/CMakeFiles/CMakeTmp/CheckSymbolExists.c
Linking C executable cmTC_c6cfa
/usr/local/bin/cmake -E cmake_link_script CMakeFiles/cmTC_c6cfa.dir/link.txt --verbose=1
/opt/rh/devtoolset-2/root/usr/bin/cc  -fPIC     CMakeFiles/cmTC_c6cfa.dir/CheckSymbolExists.c.o  -o cmTC_c6cfa -rdynamic
CMakeFiles/cmTC_c6cfa.dir/CheckSymbolExists.c.o: In function `main':
CheckSymbolExists.c:(.text+0x1b): undefined reference to `pthread_create'
collect2: error: ld returned 1 exit status
gmake[1]: *** [cmTC_c6cfa] Error 1
gmake[1]: Leaving directory `/paddle/build/CMakeFiles/CMakeTmp'
gmake: *** [cmTC_c6cfa/fast] Error 2

File /paddle/build/CMakeFiles/CMakeTmp/CheckSymbolExists.c:
/* */
#include <pthread.h>
int main(int argc, char** argv)
{
  (void)argv;
   #ifndef pthread_create
   return ((int*)(&pthread_create))[argc];
   #else
   (void)argc;
   return 0;
   #endif
}

I bulid paddlepaddle as follow document:
http://www.paddlepaddle.org/docs/develop/documentation/zh/getstarted/build_and_install/build_from_source_cn.html
