### ISSUE TITLE
GPU运行seqToseq的Demo一段时间后报错

### ISSUE THREAD

**Issue by lawup** [PaddlePaddle/Paddle#1143]
GPU运行seqToseq的Demo一段时间后报错

> I0113 07:22:56.556532   553 TrainerInternal.cpp:165]  Batch=6990 samples=174750 AvgCost=nan CurrentCost=nan Eval: classification_error_evaluator=0.398381  CurrentEval: classification_error_evaluator=1 
> .Thread [139848543574080] Backwarding decoder_group, __embedding_1__, target_language_word, __mixed_1__, __first_seq_0__, __mixed_0__, __concat_0__, __simple_gru_1__, __simple_gru_1__@__simple_gru_1___recurrent_group, __simple_gru_1__+delay1@__simple_gru_1___recurrent_group, __simple_gru_1___transform@__simple_gru_1___recurrent_group, __simple_gru_1__@__simple_gru_1___recurrent_group, __simple_gru_1__+delay1@__simple_gru_1___recurrent_group, __simple_gru_1___transform@__simple_gru_1___recurrent_group, __simple_gru_1__@__simple_gru_1___recurrent_group, __simple_gru_1__+delay1@__simple_gru_1___recurrent_group, __simple_gru_1___transform@__simple_gru_1___recurrent_group, __simple_gru_1__@__simple_gru_1___recurrent_group, __simple_gru_1__+delay1@__simple_gru_1___recurrent_group, __simple_gru_1___transform@__simple_gru_1___recurrent_group, __simple_gru_1__@__simple_gru_1___recurrent_group, __simple_gru_1__+delay1@__simple_gru_1___recurrent_group, __simple_gru_1___transform@__simple_gru_1___recurrent_group, __simple_gru_1__@__simple_gru_1___recurrent_group, __simple_gru_1__+delay1@__simple_gru_1___recurrent_group, __simple_gru_1___transform@__simple_gru_1___recurrent_group, __simple_gru_1__@__simple_gru_1___recurrent_group, __simple_gru_1__+delay1@__simple_gru_1___recurrent_group, __simple_gru_1___transform@__simple_gru_1___recurrent_group, __simple_gru_1__@__simple_gru_1___recurrent_group, __simple_gru_1__+delay1@__simple_gru_1___recurrent_group, __simple_gru_1___transform@__simple_gru_1___recurrent_group, __simple_gru_1__@__simple_gru_1___recurrent_group, __simple_gru_1__+delay1@__simple_gru_1___recurrent_group, __simple_gru_1___transform@__simple_gru_1___recurrent_group, __simple_gru_1__@__simple_gru_1___recurrent_group, __simple_gru_1__+delay1@__simple_gru_1___recurrent_group, __simple_gru_1___transform@__simple_gru_1___recurrent_group, __simple_gru_1__@__simple_gru_1___recurrent_group, __simple_gru_1__+delay1@__simple_gru_1___recurrent_group, __simple_gru_1___transform@__simple_gru_1___recurrent_group, __simple_gru_1__@__simple_gru_1___recurrent_group, __simple_gru_1__+delay1@__simple_gru_1___recurrent_group, __simple_gru_1___transform@__simple_gru_1___recurrent_group, __simple_gru_1__@__simple_gru_1___recurrent_group, __simple_gru_1__+delay1@__simple_gru_1___recurrent_group, __simple_gru_1___transform@__simple_gru_1___recurrent_group, __simple_gru_1__@__simple_gru_1___recurrent_group, __simple_gru_1__+delay1@__simple_gru_1___recurrent_group, __simple_gru_1___transform@__simple_gru_1___recurrent_group, __simple_gru_1__@__simple_gru_1___recurrent_group, __simple_gru_1__+delay1@__simple_gru_1___recurrent_group, __simple_gru_1___transform@__simple_gru_1___recurrent_group, __simple_gru_1__@__simple_gru_1___recurrent_group, __simple_gru_1__+delay1@__simple_gru_1___recurrent_group, __simple_gru_1___transform@__simple_gru_1___recurrent_group, __simple_gru_1__@__simple_gru_1___recurrent_group, __simple_gru_1__+delay1@__simple_gru_1___recurrent_group, __simple_gru_1___transform@__simple_gru_1___recurrent_group, __simple_gru_1__@__simple_gru_1___recurrent_group, __simple_gru_1__+delay1@__simple_gru_1___recurrent_group, __simple_gru_1___transform@__simple_gru_1___recurrent_group, __simple_gru_1__@__simple_gru_1___recurrent_group, __simple_gru_1__+delay1@__simple_gru_1___recurrent_group, __simple_gru_1___transform@__simple_gru_1___recurrent_group, __simple_gru_1__@__simple_gru_1___recurrent_group, __simple_gru_1__+delay1@__simple_gru_1___recurrent_group, __simple_gru_1___transform@__simple_gru_1___recurrent_group, __simple_gru_1__@__simple_gru_1___recurrent_group, __simple_gru_1__+delay1@__simple_gru_1___recurrent_group, __simple_gru_1___transform@__simple_gru_1___recurrent_group, __simple_gru_1__@__simple_gru_1___recurrent_group, __simple_gru_1__+delay1@__simple_gru_1___recurrent_group, __simple_gru_1___transform@__simple_gru_1___recurrent_group, __simple_gru_1__@__simple_gru_1___recurrent_group, __simple_gru_1__+delay1@__simple_gru_1___recurrent_group, __simple_gru_1___transform@__simple_gru_1___recurrent_group, __simple_gru_1__@__simple_gru_1___recurrent_group, __simple_gru_1__+delay1@__simple_gru_1___recurrent_group, __simple_gru_1___transform@__simple_gru_1___recurrent_group, __simple_gru_1__@__simple_gru_1___recurrent_group, __simple_gru_1__+delay1@__simple_gru_1___recurrent_group, __simple_gru_1___transform@__simple_gru_1___recurrent_group, __simple_gru_1__@__simple_gru_1___recurrent_group, __simple_gru_1__+delay1@__simple_gru_1___recurrent_group, __simple_gru_1___transform@__simple_gru_1___recurrent_group, __simple_gru_1__@__simple_gru_1___recurrent_group, __simple_gru_1__+delay1@__simple_gru_1___recurrent_group, __simple_gru_1___transform@__simple_gru_1___recurrent_group, __simple_gru_1__@__simple_gru_1___recurrent_group, __simple_gru_1__+delay1@__simple_gru_1___recurrent_group, __simple_gru_1___transform@__simple_gru_1___recurrent_group, __simple_gru_1__@__simple_gru_1___recurrent_group, __simple_gru_1__+delay1@__simple_gru_1___recurrent_group, __simple_gru_1___transform@__simple_gru_1___recurrent_group, __simple_gru_1__@__simple_gru_1___recurrent_group, __simple_gru_1__+delay1@__simple_gru_1___recurrent_group, __simple_gru_1___transform@__simple_gru_1___recurrent_group, __simple_gru_1__@__simple_gru_1___recurrent_group, __simple_gru_1__+delay1@__simple_gru_1___recurrent_group, __simple_gru_1___transform@__simple_gru_1___recurrent_group, __simple_gru_1__@__simple_gru_1___recurrent_group, __simple_gru_1__+delay1@__simple_gru_1___recurrent_group, __simple_gru_1___transform@__simple_gru_1___recurrent_group, __simple_gru_1__@__simple_gru_1___recurrent_group, __simple_gru_1__+delay1@__simple_gru_1___recurrent_group, __simple_gru_1___transform@__simple_gru_1___recurrent_group, __simple_gru_1__@__simple_gru_1___recurrent_group, __simple_gru_1__+delay1@__simple_gru_1___recurrent_group, __simple_gru_1___transform@__simple_gru_1___recurrent_group, __simple_gru_1__@__simple_gru_1___recurrent_group, __simple_gru_1__+delay1@__simple_gru_1___recurrent_group, __simple_gru_1___transform@__simple_gru_1___recurrent_group, __simple_gru_1__@__simple_gru_1___recurrent_group, __simple_gru_1__+delay1@__simple_gru_1___recurrent_group, __simple_gru_1___transform@__simple_gru_1___recurrent_group, __simple_gru_1__@__simple_gru_1___recurrent_group, __simple_gru_1__+delay1@__simple_gru_1___recurrent_group, __simple_gru_1___transform@__simple_gru_1___recurrent_group, __simple_gru_1__@__simple_gru_1___recurrent_group, __simple_gru_1__+delay1@__simple_gru_1___recurrent_group, __simple_gru_1___transform@__simple_gru_1___recurrent_group, __simple_gru_1__@__simple_gru_1___recurrent_group, __simple_gru_1__+delay1@__simple_gru_1___recurrent_group, __simple_gru_1___transform@__simple_gru_1___recurrent_group, __simple_gru_1__@__simple_gru_1___recurrent_group, __simple_gru_1__+delay1@__simple_gru_1___recurrent_group, __simple_gru_1___transform@__simple_gru_1___recurrent_group, __simple_gru_1__@__simple_gru_1___recurrent_group, __simple_gru_1__+delay1@__simple_gru_1___recurrent_group, __simple_gru_1___transform@__simple_gru_1___recurrent_group, __simple_gru_1__@__simple_gru_1___recurrent_group, __simple_gru_1__+delay1@__simple_gru_1___recurrent_group, __simple_gru_1___transform@__simple_gru_1___recurrent_group, __simple_gru_1__@__simple_gru_1___recurrent_group, __simple_gru_1__+delay1@__simple_gru_1___recurrent_group, __simple_gru_1___transform@__simple_gru_1___recurrent_group, __simple_gru_1__@__simple_gru_1___recurrent_group, __simple_gru_1__+delay1@__simple_gru_1___recurrent_group, __simple_gru_1___transform@__simple_gru_1___recurrent_group, __simple_gru_1__@__simple_gru_1___recurrent_group, __simple_gru_1__+delay1@__simple_gru_1___recurrent_group, __simple_gru_1___transform@__simple_gru_1___recurrent_group, __simple_gru_1__@__simple_gru_1___recurrent_group, __simple_gru_1__+delay1@__simple_gru_1___recurrent_group, __simple_gru_1___transform@__simple_gru_1___recurrent_group, __simple_gru_1__@__simple_gru_1___recurrent_group, __simple_gru_1__+delay1@__simple_gru_1___recurrent_group, __simple_gru_1___transform@__simple_gru_1___recurrent_group, __simple_gru_1__@__simple_gru_1___recurrent_group, __simple_gru_1__+delay1@__simple_gru_1___recurrent_group, __simple_gru_1___transform@__simple_gru_1___recurrent_group, __simple_gru_1__@__simple_gru_1___recurrent_group, __simple_gru_1__+delay1@__simple_gru_1___recurrent_group, __simple_gru_1___transform@__simple_gru_1___recurrent_group, __simple_gru_1__@__simple_gru_1___recurrent_group, __simple_gru_1__+delay1@__simple_gru_1___recurrent_group, __simple_gru_1___transform@__simple_gru_1___recurrent_group, __simple_gru_1__@__simple_gru_1___recurrent_group, __simple_gru_1__+delay1@__simple_gru_1___recurrent_group, __simple_gru_1___transform@__simple_gru_1___recurrent_group, __simple_gru_1__@__simple_gru_1___recurrent_group, __simple_gru_1__+delay1@__simple_gru_1___recurrent_group, __simple_gru_1___transform@__simple_gru_1___recurrent_group, __simple_gru_1__@__simple_gru_1___recurrent_group, __simple_gru_1__+delay1@__simple_gru_1___recurrent_group, __simple_gru_1___transform@__simple_gru_1___recurrent_group, __simple_gru_1__@__simple_gru_1___recurrent_group, __simple_gru_1__+delay1@__simple_gru_1___recurrent_group, __simple_gru_1___transform@__simple_gru_1___recurrent_group, __simple_gru_1__@__simple_gru_1___recurrent_group, __simple_gru_1__+delay1@__simple_gru_1___recurrent_group, __simple_gru_1___transform@__simple_gru_1___recurrent_group, __simple_gru_1__@__simple_gru_1___recurrent_group, __simple_gru_1__+delay1@__simple_gru_1___recurrent_group, __simple_gru_1___transform@__simple_gru_1___recurrent_group, __simple_gru_1__@__simple_gru_1___recurrent_group, __simple_gru_1__+delay1@__simple_gru_1___recurrent_group, __simple_gru_1___transform@__simple_gru_1___recurrent_group, __simple_gru_1__@__simple_gru_1___recurrent_group, __simple_gru_1__+delay1@__simple_gru_1___recurrent_group, __simple_gru_1___transform@__simple_gru_1___recurrent_group, __simple_gru_1__@__simple_gru_1___recurrent_group, __simple_gru_1__+delay1@__simple_gru_1___recurrent_group, __simple_gru_1___transform@__simple_gru_1___recurrent_group, __simple_gru_1__@__simple_gru_1___recurrent_group, __simple_gru_1__+delay1@__simple_gru_1___recurrent_group, __simple_gru_1___transform@__simple_gru_1___recurrent_group, __simple_gru_1__@__simple_gru_1___recurrent_group, __simple_gru_1__+delay1@__simple_gru_1___recurrent_group, __simple_gru_1___transform@__simple_gru_1___recurrent_group, __simple_gru_1__@__simple_gru_1___recurrent_group, __simple_gru_1__+delay1@__simple_gru_1___recurrent_group, __simple_gru_1___transform@__simple_gru_1___recurrent_group, __simple_gru_1__@__simple_gru_1___recurrent_group, __simple_gru_1__+delay1@__simple_gru_1___recurrent_group, __simple_gru_1___transform@__simple_gru_1___recurrent_group, __simple_gru_1__@__simple_gru_1___recurrent_group, __simple_gru_1__+delay1@__simple_gru_1___recurrent_group, __simple_gru_1___transform@__simple_gru_1___recurrent_group, __simple_gru_1__@__simple_gru_1___recurrent_group, __simple_gru_1__+delay1@__simple_gru_1___recurrent_group, __simple_gru_1___transform@__simple_gru_1___recurrent_group, __simple_gru_1__@__simple_gru_1___recurrent_group, __simple_gru_1__+delay1@__simple_gru_1___recurrent_group, __simple_gru_1___transform@__simple_gru_1___recurrent_group, __simple_gru_1__@__simple_gru_1___recurrent_group, __simple_gru_1__+delay1@__simple_gru_1___recurrent_group, __simple_gru_1___transform@__simple_gru_1___recurrent_group, __simple_gru_1__@__simple_gru_1___recurrent_group, __simple_gru_1__+delay1@__simple_gru_1___recurrent_group, __simple_gru_1___transform@__simple_gru_1___recurrent_group, __simple_gru_1__@__simple_gru_1___recurrent_group, __simple_gru_1__+delay1@__simple_gru_1___recurrent_group, __simple_gru_1___transform@__simple_gru_1___recurrent_group, __simple_gru_1__@__simple_gru_1___recurrent_group, __simple_gru_1__+delay1@__simple_gru_1___recurrent_group, __simple_gru_1___transform@__simple_gru_1___recurrent_group, __simple_gru_1__@__simple_gru_1___recurrent_group, __simple_gru_1__+delay1@__simple_gru_1___recurrent_group, __simple_gru_1___transform@__simple_gru_1___recurrent_group, __simple_gru_1___recurrent_group, __simple_gru_1___transform, __simple_gru_0__, __simple_gru_0__@__simple_gru_0___recurrent_group, __simple_gru_0__+delay1@__simple_gru_0___recurrent_group, __simple_gru_0___transform@__simple_gru_0___recurrent_group, __simple_gru_0__@__simple_gru_0___recurrent_group, __simple_gru_0__+delay1@__simple_gru_0___recurrent_group, __simple_gru_0___transform@__simple_gru_0___recurrent_group, __simple_gru_0__@__simple_gru_0___recurrent_group, __simple_gru_0__+delay1@__simple_gru_0___recurrent_group, __simple_gru_0___transform@__simple_gru_0___recurrent_group, __simple_gru_0__@__simple_gru_0___recurrent_group, __simple_gru_0__+delay1@__simple_gru_0___recurrent_group, __simple_gru_0___transform@__simple_gru_0___recurrent_group, __simple_gru_0__@__simple_gru_0___recurrent_group, __simple_gru_0__+delay1@__simple_gru_0___recurrent_group, __simple_gru_0___transform@__simple_gru_0___recurrent_group, __simple_gru_0__@__simple_gru_0___recurrent_group, __simple_gru_0__+delay1@__simple_gru_0___recurrent_group, __simple_gru_0___transform@__simple_gru_0___recurrent_group, __simple_gru_0__@__simple_gru_0___recurrent_group, __simple_gru_0__+delay1@__simple_gru_0___recurrent_group, __simple_gru_0___transform@__simple_gru_0___recurrent_group, __simple_gru_0__@__simple_gru_0___recurrent_group, __simple_gru_0__+delay1@__simple_gru_0___recurrent_group, __simple_gru_0___transform@__simple_gru_0___recurrent_group, __simple_gru_0__@__simple_gru_0___recurrent_group, __simple_gru_0__+delay1@__simple_gru_0___recurrent_group, __simple_gru_0___transform@__simple_gru_0___recurrent_group, __simple_gru_0__@__simple_gru_0___recurrent_group, __simple_gru_0__+delay1@__simple_gru_0___recurrent_group, __simple_gru_0___transform@__simple_gru_0___recurrent_group, __simple_gru_0__@__simple_gru_0___recurrent_group, __simple_gru_0__+delay1@__simple_gru_0___recurrent_group, __simple_gru_0___transform@__simple_gru_0___recurrent_group, __simple_gru_0__@__simple_gru_0___recurrent_group, __simple_gru_0__+delay1@__simple_gru_0___recurrent_group, __simple_gru_0___transform@__simple_gru_0___recurrent_group, __simple_gru_0__@__simple_gru_0___recurrent_group, __simple_gru_0__+delay1@__simple_gru_0___recurrent_group, __simple_gru_0___transform@__simple_gru_0___recurrent_group, __simple_gru_0__@__simple_gru_0___recurrent_group, __simple_gru_0__+delay1@__simple_gru_0___recurrent_group, __simple_gru_0___transform@__simple_gru_0___recurrent_group, __simple_gru_0__@__simple_gru_0___recurrent_group, __simple_gru_0__+delay1@__simple_gru_0___recurrent_group, __simple_gru_0___transform@__simple_gru_0___recurrent_group, __simple_gru_0__@__simple_gru_0___recurrent_group, __simple_gru_0__+delay1@__simple_gru_0___recurrent_group, __simple_gru_0___transform@__simple_gru_0___recurrent_group, __simple_gru_0__@__simple_gru_0___recurrent_group, __simple_gru_0__+delay1@__simple_gru_0___recurrent_group, __simple_gru_0___transform@__simple_gru_0___recurrent_group, __simple_gru_0__@__simple_gru_0___recurrent_group, __simple_gru_0__+delay1@__simple_gru_0___recurrent_group, __simple_gru_0___transform@__simple_gru_0___recurrent_group, __simple_gru_0__@__simple_gru_0___recurrent_group, __simple_gru_0__+delay1@__simple_gru_0___recurrent_group, __simple_gru_0___transform@__simple_gru_0___recurrent_group, __simple_gru_0__@__simple_gru_0___recurrent_group, __simple_gru_0__+delay1@__simple_gru_0___recurrent_group, __simple_gru_0___transform@__simple_gru_0___recurrent_group, __simple_gru_0__@__simple_gru_0___recurrent_group, __simple_gru_0__+delay1@__simple_gru_0___recurrent_group, __simple_gru_0___transform@__simple_gru_0___recurrent_group, __simple_gru_0__@__simple_gru_0___recurrent_group, __simple_gru_0__+delay1@__simple_gru_0___recurrent_group, __simple_gru_0___transform@__simple_gru_0___recurrent_group, __simple_gru_0__@__simple_gru_0___recurrent_group, __simple_gru_0__+delay1@__simple_gru_0___recurrent_group, __simple_gru_0___transform@__simple_gru_0___recurrent_group, __simple_gru_0__@__simple_gru_0___recurrent_group, __simple_gru_0__+delay1@__simple_gru_0___recurrent_group, __simple_gru_0___transform@__simple_gru_0___recurrent_group, __simple_gru_0__@__simple_gru_0___recurrent_group, __simple_gru_0__+delay1@__simple_gru_0___recurrent_group, __simple_gru_0___transform@__simple_gru_0___recurrent_group, __simple_gru_0__@__simple_gru_0___recurrent_group, __simple_gru_0__+delay1@__simple_gru_0___recurrent_group, __simple_gru_0___transform@__simple_gru_0___recurrent_group, __simple_gru_0__@__simple_gru_0___recurrent_group, __simple_gru_0__+delay1@__simple_gru_0___recurrent_group, __simple_gru_0___transform@__simple_gru_0___recurrent_group, __simple_gru_0__@__simple_gru_0___recurrent_group, __simple_gru_0__+delay1@__simple_gru_0___recurrent_group, __simple_gru_0___transform@__simple_gru_0___recurrent_group, __simple_gru_0__@__simple_gru_0___recurrent_group, __simple_gru_0__+delay1@__simple_gru_0___recurrent_group, __simple_gru_0___transform@__simple_gru_0___recurrent_group, __simple_gru_0__@__simple_gru_0___recurrent_group, __simple_gru_0__+delay1@__simple_gru_0___recurrent_group, __simple_gru_0___transform@__simple_gru_0___recurrent_group, __simple_gru_0__@__simple_gru_0___recurrent_group, __simple_gru_0__+delay1@__simple_gru_0___recurrent_group, __simple_gru_0___transform@__simple_gru_0___recurrent_group, __simple_gru_0__@__simple_gru_0___recurrent_group, __simple_gru_0__+delay1@__simple_gru_0___recurrent_group, __simple_gru_0___transform@__simple_gru_0___recurrent_group, __simple_gru_0__@__simple_gru_0___recurrent_group, __simple_gru_0__+delay1@__simple_gru_0___recurrent_group, __simple_gru_0___transform@__simple_gru_0___recurrent_group, __simple_gru_0__@__simple_gru_0___recurrent_group, __simple_gru_0__+delay1@__simple_gru_0___recurrent_group, __simple_gru_0___transform@__simple_gru_0___recurrent_group, __simple_gru_0__@__simple_gru_0___recurrent_group, __simple_gru_0__+delay1@__simple_gru_0___recurrent_group, __simple_gru_0___transform@__simple_gru_0___recurrent_group, __simple_gru_0__@__simple_gru_0___recurrent_group, __simple_gru_0__+delay1@__simple_gru_0___recurrent_group, __simple_gru_0___transform@__simple_gru_0___recurrent_group, __simple_gru_0__@__simple_gru_0___recurrent_group, __simple_gru_0__+delay1@__simple_gru_0___recurrent_group, __simple_gru_0___transform@__simple_gru_0___recurrent_group, __simple_gru_0__@__simple_gru_0___recurrent_group, __simple_gru_0__+delay1@__simple_gru_0___recurrent_group, __simple_gru_0___transform@__simple_gru_0___recurrent_group, __simple_gru_0__@__simple_gru_0___recurrent_group, __simple_gru_0__+delay1@__simple_gru_0___recurrent_group, __simple_gru_0___transform@__simple_gru_0___recurrent_group, __simple_gru_0__@__simple_gru_0___recurrent_group, __simple_gru_0__+delay1@__simple_gru_0___recurrent_group, __simple_gru_0___transform@__simple_gru_0___recurrent_group, __simple_gru_0__@__simple_gru_0___recurrent_group, __simple_gru_0__+delay1@__simple_gru_0___recurrent_group, __simple_gru_0___transform@__simple_gru_0___recurrent_group, __simple_gru_0__@__simple_gru_0___recurrent_group, __simple_gru_0__+delay1@__simple_gru_0___recurrent_group, __simple_gru_0___transform@__simple_gru_0___recurrent_group, __simple_gru_0__@__simple_gru_0___recurrent_group, __simple_gru_0__+delay1@__simple_gru_0___recurrent_group, __simple_gru_0___transform@__simple_gru_0___recurrent_group, __simple_gru_0__@__simple_gru_0___recurrent_group, __simple_gru_0__+delay1@__simple_gru_0___recurrent_group, __simple_gru_0___transform@__simple_gru_0___recurrent_group, __simple_gru_0__@__simple_gru_0___recurrent_group, __simple_gru_0__+delay1@__simple_gru_0___recurrent_group, __simple_gru_0___transform@__simple_gru_0___recurrent_group, __simple_gru_0__@__simple_gru_0___recurrent_group, __simple_gru_0__+delay1@__simple_gru_0___recurrent_group, __simple_gru_0___transform@__simple_gru_0___recurrent_group, __simple_gru_0__@__simple_gru_0___recurrent_group, __simple_gru_0__+delay1@__simple_gru_0___recurrent_group, __simple_gru_0___transform@__simple_gru_0___recurrent_group, __simple_gru_0__@__simple_gru_0___recurrent_group, __simple_gru_0__+delay1@__simple_gru_0___recurrent_group, __simple_gru_0___transform@__simple_gru_0___recurrent_group, __simple_gru_0__@__simple_gru_0___recurrent_group, __simple_gru_0__+delay1@__simple_gru_0___recurrent_group, __simple_gru_0___transform@__simple_gru_0___recurrent_group, __simple_gru_0__@__simple_gru_0___recurrent_group, __simple_gru_0__+delay1@__simple_gru_0___recurrent_group, __simple_gru_0___transform@__simple_gru_0___recurrent_group, __simple_gru_0__@__simple_gru_0___recurrent_group, __simple_gru_0__+delay1@__simple_gru_0___recurrent_group, __simple_gru_0___transform@__simple_gru_0___recurrent_group, __simple_gru_0__@__simple_gru_0___recurrent_group, __simple_gru_0__+delay1@__simple_gru_0___recurrent_group, __simple_gru_0___transform@__simple_gru_0___recurrent_group, __simple_gru_0__@__simple_gru_0___recurrent_group, __simple_gru_0__+delay1@__simple_gru_0___recurrent_group, __simple_gru_0___transform@__simple_gru_0___recurrent_group, __simple_gru_0__@__simple_gru_0___recurrent_group, __simple_gru_0__+delay1@__simple_gru_0___recurrent_group, __simple_gru_0___transform@__simple_gru_0___recurrent_group, __simple_gru_0__@__simple_gru_0___recurrent_group, __simple_gru_0__+delay1@__simple_gru_0___recurrent_group, __simple_gru_0___transform@__simple_gru_0___recurrent_group, __simple_gru_0__@__simple_gru_0___recurrent_group, __simple_gru_0__+delay1@__simple_gru_0___recurrent_group, __simple_gru_0___transform@__simple_gru_0___recurrent_group, __simple_gru_0__@__simple_gru_0___recurrent_group, __simple_gru_0__+delay1@__simple_gru_0___recurrent_group, __simple_gru_0___transform@__simple_gru_0___recurrent_group, __simple_gru_0__@__simple_gru_0___recurrent_group, __simple_gru_0__+delay1@__simple_gru_0___recurrent_group, __simple_gru_0___transform@__simple_gru_0___recurrent_group, __simple_gru_0__@__simple_gru_0___recurrent_group, __simple_gru_0__+delay1@__simple_gru_0___recurrent_group, __simple_gru_0___transform@__simple_gru_0___recurrent_group, __simple_gru_0__@__simple_gru_0___recurrent_group, __simple_gru_0__+delay1@__simple_gru_0___recurrent_group, __simple_gru_0___transform@__simple_gru_0___recurrent_group, __simple_gru_0__@__simple_gru_0___recurrent_group, __simple_gru_0__+delay1@__simple_gru_0___recurrent_group, __simple_gru_0___transform@__simple_gru_0___recurrent_group, __simple_gru_0__@__simple_gru_0___recurrent_group, __simple_gru_0__+delay1@__simple_gru_0___recurrent_group, __simple_gru_0___transform@__simple_gru_0___recurrent_group, __simple_gru_0__@__simple_gru_0___recurrent_group, __simple_gru_0__+delay1@__simple_gru_0___recurrent_group, __simple_gru_0___transform@__simple_gru_0___recurrent_group, __simple_gru_0__@__simple_gru_0___recurrent_group, __simple_gru_0__+delay1@__simple_gru_0___recurrent_group, __simple_gru_0___transform@__simple_gru_0___recurrent_group, __simple_gru_0__@__simple_gru_0___recurrent_group, __simple_gru_0__+delay1@__simple_gru_0___recurrent_group, __simple_gru_0___transform@__simple_gru_0___recurrent_group, __simple_gru_0__@__simple_gru_0___recurrent_group, __simple_gru_0__+delay1@__simple_gru_0___recurrent_group, __simple_gru_0___transform@__simple_gru_0___recurrent_group, __simple_gru_0__@__simple_gru_0___recurrent_group, __simple_gru_0__+delay1@__simple_gru_0___recurrent_group, __simple_gru_0___transform@__simple_gru_0___recurrent_group, __simple_gru_0__@__simple_gru_0___recurrent_group, __simple_gru_0__+delay1@__simple_gru_0___recurrent_group, __simple_gru_0___transform@__simple_gru_0___recurrent_group, __simple_gru_0__@__simple_gru_0___recurrent_group, __simple_gru_0__+delay1@__simple_gru_0___recurrent_group, __simple_gru_0___transform@__simple_gru_0___recurrent_group, __simple_gru_0__@__simple_gru_0___recurrent_group, __simple_gru_0__+delay1@__simple_gru_0___recurrent_group, __simple_gru_0___transform@__simple_gru_0___recurrent_group, __simple_gru_0__@__simple_gru_0___recurrent_group, __simple_gru_0__+delay1@__simple_gru_0___recurrent_group, __simple_gru_0___transform@__simple_gru_0___recurrent_group, __simple_gru_0___recurrent_group, __simple_gru_0___transform, __embedding_0__, source_language_word, 
> *** Aborted at 1484263378 (unix time) try "date -d @1484263378" if you are using GNU date ***
> PC: @           0x6caa36 paddle::GpuVectorT<>::getAbsMax()
> *** SIGFPE (@0x6caa36) received by PID 553 (TID 0x7f3106c31840) from PID 7121462; stack trace: ***
>     @     0x7f3106528330 (unknown)
>     @           0x6caa36 paddle::GpuVectorT<>::getAbsMax()
>     @           0x6a1b99 _ZNSt17_Function_handlerIFvPN6paddle9ParameterEEZNS0_15TrainerInternal13trainOneBatchElRKNS0_9DataBatchEPSt6vectorINS0_8ArgumentESaIS9_EEEUlS2_E_E9_M_invokeERKSt9_Any_dataS2_
>     @           0x811fd3 paddle::Parameter::incUpdate()
>     @           0x5e775f paddle::RecurrentLayerGroup::backward()
>     @           0x6551e0 paddle::NeuralNetwork::backward()
>     @           0x6a24bc paddle::TrainerInternal::forwardBackwardBatch()
>     @           0x6a28d4 paddle::TrainerInternal::trainOneBatch()
>     @           0x69d9f0 paddle::Trainer::trainOneDataBatch()
>     @           0x6a027f paddle::Trainer::trainOnePass()
>     @           0x6a15d0 paddle::Trainer::train()
>     @           0x52aa07 main
>     @     0x7f3104919f45 (unknown)
>     @           0x53fb25 (unknown)
>     @                0x0 (unknown)
> /usr/bin/paddle: line 109:   553 Floating point exception(core dumped) ${DEBUGGER} $MYDIR/../opt/paddle/bin/paddle_trainer ${@:2}
>

**Comment by backyes** [comment]
请参看

```
paddle github issue Floating point exception
```
 关键词检索出的issue结果。 

例如： 
```
https://github.com/PaddlePaddle/Paddle/issues/563 
https://github.com/PaddlePaddle/Paddle/issues/46 
....
```

**Comment by lcy-seso** [comment]
如果是梯度爆掉的问题，设置 clipping 应该是可以一定程度解决。 但是，一直怀疑代码重构之后， clipping 是不起作用的。  https://github.com/PaddlePaddle/Paddle/issues/775
