### ISSUE TITLE
will it work on Windows OS?

### ISSUE THREAD

**Issue by Sandy4321** [PaddlePaddle/Paddle#11444]
will it work on Windows OS?

**Comment by lucywsq** [comment]
For Windows, only under the environment of  Docker can you start installing. You may download that. For more details, please refer to this instruction :
http://www.paddlepaddle.org/docs/develop/documentation/fluid/en/build_and_install/docker_install_en.html
If you have any questions, just keep contact in this issue~
Hoping you have a nice start : )

**Comment by chengduoZH** [comment]
This issue is inactive for a long time, temporarily close it, if you still have doubts, please feel free to reopen.
