### ISSUE TITLE
fluid.layers.split()不支持int64位吗？

### ISSUE THREAD

**Issue by oyjxer** [PaddlePaddle/Paddle#11443]
max_seq_len = 32
query = fluid.layers.data(name="query", shape=[max_seq_len], lod_level=0)
fluid.layers.split(query, num_or_sections=max_seq_len, dim=1)
在exec.run的时候会core，说op split not support int64

**Comment by chengduoZH** [comment]
是的，现在还不支持` int64`类型。

**Comment by oyjxer** [comment]
@chengduoZH 现在都支持啥类型，什么时候支持int64

**Comment by chengduoZH** [comment]
@oyjxer 昨天把int64加进去了，现在split支持的类型由double, float, int64_t, int.
你可以从这里下载最新的安装包 http://www.paddlepaddle.org/docs/0.13.0/documentation/zh/build_and_install/pip_install_cn.html
