### ISSUE TITLE
希望数据类型DataType支持string类型

### ISSUE THREAD

**Issue by HugoLian** [PaddlePaddle/Paddle#1145]
hi, 现在的DataType只支持这四种格式：
```
class DataType(object):
    Dense = 0
    SparseNonValue = 1
    SparseValue = 2
    Index = 3
```
这样就限制了dataprovider settings.input_types类型。

在做预测的时候，希望连同数据结果，同时输出预测数据的部分信息，比如id， 那么如果这个id是整形的，目前可以通过：integer_value(1)输出（因为预测的batch_size=1因此不用考虑长度）
但如果id超出了整形范围，或者是hex-id，那么现在的paddle就没办法输出这个了。

希望有一天paddle可以支持输出预测文件的部分文件信息。这个对我们还挺重要的。
如：
```
class DataType(object):
    Dense = 0
    SparseNonValue = 1
    SparseValue = 2
    Index = 3
    String = 4
```
这样让settings.input_types里支持```string_value(1)```类型
谢谢。

**Comment by reyoung** [comment]
这个string_value可以加一下，不过目前Paddle Team工作重点可能不在这里。如果对这个功能需求非常紧急，可以说明这个东西怎么加。

类似的就是在PyDataProvider2.cpp里面增加一个新的Scanner，比如StringScanner，然后在IFieldScanner::create中，new出来这个Scanner就好了。

**Comment by qingqing01** [comment]
目前可以使用V2 API, 预测时不做shuffle，写Python程序同时输出数据和预测结果。
