### ISSUE TITLE
数字识别例子出现错误：try "date -d @1528970452" if you are using GNU date ***

### ISSUE THREAD

**Issue by xiaolv3366** [PaddlePaddle/Paddle#11477]
数字识别例子出现错误：
try "date -d @1528970452" if you are using GNU date ***
使用CPU和GPU训练都出现错误。
![image](https://user-images.githubusercontent.com/12287110/41406372-c71f97ec-6ffe-11e8-85ac-b20b7344d696.png)

**Comment by chengduoZH** [comment]
您用的是自己的数据集吗？

**Comment by xiaolv3366** [comment]
不是自己的数据集，是官网下载，程序自动下载的。

**Comment by chengduoZH** [comment]
你跑的是什么模型，安装的是哪个版本的paddle，运行环境是什么?

**Comment by xiaolv3366** [comment]
教程里面数字识别例子，安装最新的paddle，ubuntu 16.04系统。
这个错误频繁出现，很多人提出来，可以复现的。

**Comment by chengduoZH** [comment]
@xiaolv3366 您那边看一下你装的paddle的版本，`pip freeze | grep paddle`
这边用`paddlepaddle==0.13.0`跑手写数字识别是没有问题的。

```
xxx  /paddle/book/02.recognize_digits {develop} python train.py
grep: warning: GREP_OPTIONS is deprecated; please use an alias or script
grep: warning: GREP_OPTIONS is deprecated; please use an alias or script
grep: warning: GREP_OPTIONS is deprecated; please use an alias or script
I0615 02:32:23.214932   711 Util.cpp:166] commandline:  --use_gpu=True --trainer_count=1
W0615 02:32:36.054811   711 CpuId.h:112] PaddlePaddle wasn't compiled to use avx instructions, but these are available on your machine and could speed up CPU computations via CMAKE .. -DWITH_AVX=ON
[INFO 2018-06-15 02:32:36,060 layers.py:2716] output for __conv_pool_0___conv: c = 20, h = 24, w = 24, size = 11520
[INFO 2018-06-15 02:32:36,061 layers.py:2858] output for __conv_pool_0___pool: c = 20, h = 12, w = 12, size = 2880
[INFO 2018-06-15 02:32:36,064 layers.py:2716] output for __conv_pool_1___conv: c = 50, h = 8, w = 8, size = 3200
[INFO 2018-06-15 02:32:36,065 layers.py:2858] output for __conv_pool_1___pool: c = 50, h = 4, w = 4, size = 800
I0615 02:32:36.070379   711 GradientMachine.cpp:94] Initing parameters..
I0615 02:32:36.082705   711 GradientMachine.cpp:101] Init parameters done.
Pass 0, Batch 0, Cost 5.573153, {'classification_error_evaluator': 1.0}
Pass 0, Batch 100, Cost 0.820532, {'classification_error_evaluator': 0.0}
```

**Comment by xiaolv3366** [comment]
@chengduoZH 最新版本，一周前你们编译的版本，应该比paddlepaddle 0.13.0版本还新。
![image](https://user-images.githubusercontent.com/12287110/41448544-abc0c054-708d-11e8-8003-6fe8747043f3.png)

**Comment by chengduoZH** [comment]
您可以换成paddlepaddle 0.13.0试一下吗？

**Comment by yeyupiaoling** [comment]
应该跟这个问题相同：#11480

**Comment by xiaolv3366** [comment]
paddlepaddle 0.11.0 0.12.0 0.13.0 这三个版本我都试了，还是报错。

**Comment by chengduoZH** [comment]
@yeyupiaoling @xiaolv3366 你们在docker里面也会出现这种问题吗？
这里有docker中使用paddle的教程。http://www.paddlepaddle.org/docs/0.13.0/documentation/zh/build_and_install/docker_install_cn.html

另外，你将batch_size调小一点，比如2，试试有没有问题。

**Comment by joodo** [comment]
@chengduoZH 我也复现了问题，改 batch_size 没用

**Comment by cbstyle** [comment]
这个问题最终是啥原因导致的？

**Comment by chengduoZH** [comment]
@joodo @cbstyle 你们在docker里面也会出现这种问题吗？

**Comment by shanyi15** [comment]
您好，此issue在近一个月内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题，我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持! 
 Hello, this issue has not been updated in the past month. We will close it today for the sake of other user‘s experience. If you still need to follow up on this question after closing, please feel free to reopen it. In that case, we will get back to you within 24 hours. We apologize for the inconvenience caused by the closure and thank you so much for your support of PaddlePaddle Group!
