### ISSUE TITLE
集群 No space left on device

### ISSUE THREAD

**Issue by cbstyle** [PaddlePaddle/Paddle#11475]
Thu Jun 14 17:49:26 2018[1,7]<stderr>:get: No space left on device
Thu Jun 14 17:49:26 2018[1,7]<stderr>:
Thu Jun 14 17:49:26 2018[1,7]<stdout>:Java HotSpot(TM) 64-Bit Server VM warning: Insufficient space for shared memory file:
Thu Jun 14 17:49:26 2018[1,7]<stdout>:   /tmp/hsperfdata_normandy/10920
Thu Jun 14 17:49:26 2018[1,7]<stdout>:Try using the -Djava.io.tmpdir= option to select an alternate temp location.
Thu Jun 14 17:49:26 2018[1,7]<stdout>:
Thu Jun 14 17:49:26 2018[1,7]<stderr>:Exception in thread "main" 
Thu Jun 14 17:49:26 2018[1,7]<stderr>:java.lang.NoClassDefFoundError: ___/tmp/hsperfdata_normandy/10935
Thu Jun 14 17:49:26 2018[1,7]<stderr>:
Thu Jun 14 17:49:26 2018[1,7]<stderr>:Caused by: java.lang.ClassNotFoundException: ___.tmp.hsperfdata_normandy.10935
Thu Jun 14 17:49:26 2018[1,7]<stderr>:
Thu Jun 14 17:49:26 2018[1,7]<stderr>:	at java.net.URLClassLoader$1.run(URLClassLoader.java:202)
Thu Jun 14 17:49:26 2018[1,7]<stderr>:
Thu Jun 14 17:49:26 2018[1,7]<stderr>:	at java.security.AccessController.doPrivileged(Native Method)
Thu Jun 14 17:49:26 2018[1,7]<stderr>:	at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
Thu Jun 14 17:49:26 2018[1,7]<stderr>:
Thu Jun 14 17:49:26 2018[1,7]<stderr>:	at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
Thu Jun 14 17:49:26 2018[1,7]<stderr>:	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:301)
Thu Jun 14 17:49:26 2018[1,7]<stderr>:
Thu Jun 14 17:49:26 2018[1,7]<stderr>:	at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
Thu Jun 14 17:49:26 2018[1,7]<stderr>:
Thu Jun 14 17:49:26 2018[1,7]<stderr>:Could not find the main class: ___/tmp/hsperfdata_normandy/10935.  Program will exit.
Thu Jun 14 17:49:26 2018[1,7]<stdout>:/app/mmt-vis/lifu/data/ps_video/feature/train_300w_f16_rgb/attempt_20171215200623_1687558_m000_002823_0.pkl not exit in hdfs
Thu Jun 14 17:49:26 2018[1,7]<stdout>:Java HotSpot(TM) 64-Bit Server VM warning: Insufficient space for shared memory file:
Thu Jun 14 17:49:26 2018[1,7]<stdout>:   /tmp/hsperfdata_normandy/10957
Thu Jun 14 17:49:26 2018[1,7]<stdout>:Try using the -Djava.io.tmpdir= option to select an alternate temp location.
Thu Jun 14 17:49:26 2018[1,7]<stdout>:
Thu Jun 14 17:49:26 2018[1,7]<stderr>:Exception in thread "main" 
Thu Jun 14 17:49:26 2018[1,7]<stderr>:java.lang.NoClassDefFoundError: ___/tmp/hsperfdata_normandy/10971
Thu Jun 14 17:49:26 2018[1,7]<stderr>:
Thu Jun 14 17:49:26 2018[1,7]<stderr>:Caused by: java.lang.ClassNotFoundException: ___.tmp.hsperfdata_normandy.10971
Thu Jun 14 17:49:26 2018[1,7]<stderr>:
Thu Jun 14 17:49:26 2018[1,7]<stderr>:	at java.net.URLClassLoader$1.run(URLClassLoader.java:202)
Thu Jun 14 17:49:26 2018[1,7]<stderr>:
Thu Jun 14 17:49:26 2018[1,7]<stderr>:	at java.security.AccessController.doPrivileged(Native Method)
Thu Jun 14 17:49:26 2018[1,7]<stderr>:	at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
Thu Jun 14 17:49:26 2018[1,7]<stderr>:
Thu Jun 14 17:49:26 2018[1,7]<stderr>:	at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
Thu Jun 14 17:49:26 2018[1,7]<stderr>:	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:301)
Thu Jun 14 17:49:26 2018[1,7]<stderr>:
Thu Jun 14 17:49:26 2018[1,7]<stderr>:	at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
Thu Jun 14 17:49:26 2018[1,7]<stderr>:Could not find the main class: ___/tmp/hsperfdata_normandy/10971.  Program will exit.

**Comment by chengduoZH** [comment]
从log信息上看是您的设备空间不足。

**Comment by cbstyle** [comment]
这个是集群训练的，我是节点数量设置少导致的吗？还是啥其他原因？

**Comment by chengduoZH** [comment]
像是你运行的集群里面某个结点的GPU显存不够，你可以查一下

**Comment by chengduoZH** [comment]
该issue长时间没有回复，暂且关闭了，如需继续讨论可再打开。
