### ISSUE TITLE
定义网络，使用concat op的name属性报错

### ISSUE THREAD

**Issue by jack603047588** [PaddlePaddle/Paddle#11484]
分支：fluid develop
代码：
 j_ctr_embed = fluid.layers.concat(input=[j_h1x], axis=1, name='j_ctr_embed_op')

报以下错误：
![baiduhi_2018-6-14_20-15-25](https://user-images.githubusercontent.com/8231390/41411522-c176b256-700f-11e8-81eb-4b1765abae02.png)

**Comment by jacquesqiao** [comment]
Ok, I will fix this.

**Comment by lgone2000** [comment]
这个之前应该王龙修正过
https://github.com/PaddlePaddle/Paddle/commit/3e177b9d917d657c52244d0adf7e187f5f7731cb#diff-2f61feb27730d0f42a351131c7077ec2

**Comment by jacquesqiao** [comment]
fixed
