### ISSUE TITLE
pip安装失败

### ISSUE THREAD

**Issue by yywangvr** [PaddlePaddle/Paddle#11494]
最近想要使用paddle写代码，可是发现居然无法安装paddle:

Collecting paddlepaddle-gpu
  Could not find a version that satisfies the requirement paddlepaddle-gpu (from versions: )
No matching distribution found for paddlepaddle-gpu

这是什么原因啊？ 我在海外，是找不到源嘛。。。

**Comment by kolinwei** [comment]
pip install paddlepaddle_gpu

**Comment by chengduoZH** [comment]
@Yuyang01  这里有相关的文档 http://www.paddlepaddle.org/docs/0.13.0/documentation/zh/build_and_install/pip_install_cn.html

**Comment by yywangvr** [comment]
你好，我的电脑不带gpu啊，我是mac book pro2015. 也要安装gpu版本吗

**Comment by yywangvr** [comment]
(py36) Yuyang:~ Yuyang$ pip install paddlepaddle_gpu
Collecting paddlepaddle_gpu
  Could not find a version that satisfies the requirement paddlepaddle_gpu (from versions: )
No matching distribution found for paddlepaddle_gpu
(py36) Yuyang:~ Yuyang$ 


依旧不行

**Comment by kolinwei** [comment]
@Yuyang01 你好，现在pip上没有MAC下的whl包，如果想在MAC下试用，可以在docker里面安装
https://hub.docker.com/r/paddlepaddle/paddle/tags/

**Comment by yeyupiaoling** [comment]
@Yuyang01 如果没有GPU，那直接：
```
pip install paddlepaddle
```
pip 版本要大于9.0

**Comment by yywangvr** [comment]
同学你好，谢谢你的回复。我的所有都是最新的，就是不能安装。我目前在欧洲，不知道是不是这个原因？

**Comment by yywangvr** [comment]
你们可以把自己的paddlepaddle卸载了，用pip安装一下，试试能否成功？ ：）

**Comment by yeyupiaoling** [comment]
@Yuyang01 测试过了，没有问题的。不应该受区域影响吧，要不你试试VPN，我觉得全球都能用的。

**Comment by yywangvr** [comment]
你好，谢谢。最后用py2.7版本安装成功了。之前我的配置是py3.6。 多谢各位帮忙

*Yuyang Wang*
Institut image,
Laboratoire d’Ingénierie des Systèmes Physiques et Numériques,
Arts et Métiers ParisTech,

2 rue Thomas Dumorey – 71100 Chalon-sur-Saône, France
E-mail：alwyuyang@ <alwyuyang@163.com>gmail.com, yuyang.wang@
<alwyuyang@163.com>ensam.eu <http://gmail.com/>
Http://github.com/Yuyang01

**Comment by yywangvr** [comment]
希望你们辛苦一些，能不能尽快发布适合py3.0+版本的。

*Yuyang Wang*
Institut image,
Laboratoire d’Ingénierie des Systèmes Physiques et Numériques,
Arts et Métiers ParisTech,

2 rue Thomas Dumorey – 71100 Chalon-sur-Saône, France
E-mail：alwyuyang@ <alwyuyang@163.com>gmail.com, yuyang.wang@
<alwyuyang@163.com>ensam.eu <http://gmail.com/>
Http://github.com/Yuyang01

2018-06-15 23:48 GMT+02:00 Yuyang Wang <alwyuyang@gmail.com>:

> 你好，谢谢。最后用py2.7版本安装成功了。之前我的配置是py3.6。 多谢各位帮忙
>
> *Yuyang Wang*
> Institut image,
> Laboratoire d’Ingénierie des Systèmes Physiques et Numériques,
> Arts et Métiers ParisTech,
>
> 2 rue Thomas Dumorey – 71100 Chalon-sur-Saône, France
> E-mail：alwyuyang@ <alwyuyang@163.com>gmail.com, yuyang.wang@
> <alwyuyang@163.com>ensam.eu <http://gmail.com/>
> Http://github.com/Yuyang01
>

**Comment by chengduoZH** [comment]
@Yuyang01 感谢您的反馈，Paddle这边会尽快支持Python 3.0.
