### ISSUE TITLE
CentOS 7 下编译出错

### ISSUE THREAD

**Issue by EnigmaHuang** [PaddlePaddle/Paddle#1151]
环境：CentOS 7.1 x64， 系统自带 Python 没有安装任何额外包。已编译最新版 OpenBLAS。无 ICC & MKL。使用
```shell
cmake  .. -DWITH_GPU=OFF 
```
进行配置和编译。

前面出现过若干小问题，但都还可以解决。直到此报错：
```cmake
[ 33%] Building CXX object paddle/math/CMakeFiles/paddle_math.dir/BaseMatrix.cu.o
In file included from /home/enigma/Paddle-develop/paddle/math/BaseMatrix.cu:23:0:
/home/enigma/Paddle-develop/paddle/math/MathFunctions.h:30:21: fatal error: lapacke.h: No such file or directory
```

在 [Build from Source](http://www.paddlepaddle.org/doc/build/build_from_source.html) 中并没有提到 Paddle 需要 LAPACK 。此问题应该如何解决？

**Comment by gangliao** [comment]
其实原因是这样，因为你没有设置gfortran编译的openblas，导致openblas没有包含lapack

**Comment by gangliao** [comment]
@EnigmaHuang 

https://github.com/PaddlePaddle/Paddle/pull/1150
这个PR能解决你的问题，你不需要自己编译Openblas了，它会自动帮你下载, 编译，链接Openblas

**Comment by EnigmaHuang** [comment]
好的，因为我之前编译的时候还告诉我说没有 MKL, OpenBLAS 或者 ATLAS 无法继续。个人觉得 OpenBLAS 比 ATLAS 好装好用得多。

另外，指南里好像没有提到如何使用 MKL。我在另外一台有 ICC 2017 的服务器上，加载 ICC 的环境变量以后，cmake 仍然告诉我找到的是 OpenBLAS 而不是 MKL。

**Comment by EnigmaHuang** [comment]
以及 『前面出现过若干的小问题』 里包括一个，在 build 目录下 `cmake ..` 的时候会出现：
```shell
CMake Error at cmake/external/protobuf.cmake:32 (IF):
  if given arguments:

    "STREQUAL" "centos"

  Unknown arguments specified
Call Stack (most recent call first):
  CMakeLists.txt:62 (include)


-- Configuring incomplete, errors occurred!
```
这样的报错。我是注释掉 `cmake/external/protobuf.cmake` 中的第  32 34 35 36 行来临时解决这个问题的。这可能是由于什么引起的？

**Comment by gangliao** [comment]
https://github.com/PaddlePaddle/Paddle/pull/1150/commits/cdf6af64a87c46da070da139925c32cc4064e6d3#diff-d1909544c8c11803d1f2716c16ac9624R68 
使用你预装的MKL, 直接cmake .. -DMKL_ROOT=...

**Comment by gangliao** [comment]
@EnigmaHuang  谢谢反馈，cmake/external/protobuf.cmake 中的第 32 34 35 36 行

这个问题可能在于我写的system.cmake判断操作系统的代码有点问题。

**Comment by EnigmaHuang** [comment]
@gangliao 为 third_party 中的 python 安装一些包的时候会发生类似的问题：
```
[  6%] Performing build step for 'numpy'
CMake Error at /home/enigma/src_packages/Paddle-develop/third_party/python/numpy/src/numpy-stamp/numpy-build-RelWithDebInfo.cmake:16 (message):
  Command failed: 1

   'env' 'PATH=/home/enigma/src_packages/Paddle-develop/third_party/install/python/bin' 'PYTHONHOME=/home/enigma/src_packages/Paddle-develop/third_party/install/python' 'PYTHONPATH=/home/enigma/src_packages/Paddle-develop/third_party/install/python/lib:/home/enigma/src_packages/Paddle-develop/third_party/install/python/lib/python2.7:/home/enigma/src_packages/Paddle-develop/third_party/install/python/lib/python2.7/site-packages' '/home/enigma/src_packages/Paddle-develop/third_party/install/python/bin/python' 'setup.py' 'build'

  See also

    /home/enigma/src_packages/Paddle-develop/third_party/python/numpy/src/numpy-stamp/numpy-build-*.log
```
可能与什么相关，以及应该如何解决？

**Comment by gangliao** [comment]
https://github.com/PaddlePaddle/Paddle/blob/develop/doc/getstarted/build_and_install/build_from_source_en.md
@EnigmaHuang  建议根据文档，直接安装python和python包

**Comment by gangliao** [comment]
@QiJune  我们的centos doc ?

**Comment by EnigmaHuang** [comment]
@gangliao cython & numpy 这些 python 包直接安装到系统自带的 python 中？

**Comment by gangliao** [comment]
我的意思是你直接预先安装python 2.7, 不要走Paddle自动下载编译python那个分支，我们目前还没有在centos 7上面测试过。

**Comment by EnigmaHuang** [comment]
@gangliao CentOS 7 自己带了 Python 2.7.5。也就是说只要我把那几个包全部先装好，编译的时候就不会触发自动下载编译 python 的分支？如果是这样的话，希望可以列一下一共有哪些需要装的包，因为 Cython 不在 Build from Source doc 里但是我看到刚才走分支的时候被安装了；我以前编译安装 NumPy 的时候好像是不需要 Cython的。

**Comment by gangliao** [comment]
你确定有python 2.7?
你cmake ..的时候，看看打印的信息是否真的找到了PythonInterp和PythonLibs

```cmake
INCLUDE(ExternalProject)
INCLUDE(python_module)

FIND_PACKAGE(PythonInterp 2.7)
FIND_PACKAGE(PythonLibs 2.7)

SET(py_env "")

IF(PYTHONLIBS_FOUND AND PYTHONINTERP_FOUND)
如果有的话应该是走这个分支，不会装任何东西
    find_python_module(pip REQUIRED)
    find_python_module(numpy REQUIRED)
    find_python_module(wheel REQUIRED)
    find_python_module(google.protobuf REQUIRED)
    FIND_PACKAGE(NumPy REQUIRED)
    IF(${PY_GOOGLE.PROTOBUF_VERSION} VERSION_LESS "3.0.0")
        MESSAGE(FATAL_ERROR "Found Python Protobuf ${PY_GOOGLE.PROTOBUF_VERSION} < 3.0.0, "
        "please use pip to upgrade protobuf.")
    ENDIF(${PY_GOOGLE.PROTOBUF_VERSION} VERSION_LESS "3.0.0")
ELSE(PYTHONLIBS_FOUND AND PYTHONINTERP_FOUND)
...
这个分支会下载编译一个local python，所有python包都会装在这个local python里面。目前还没有大量测试过，所以不要走这个分支。
ENDIF()
```

**Comment by EnigmaHuang** [comment]
@gangliao 我重新查了一次，没有装任何 Python 包的时候，CentOS 7 core 下的 cmake .. 是这样的输出：
```cmake
-- Found PythonInterp: /usr/bin/python2.7 (found suitable version "2.7.5", minimum required is "2.7") 
-- Could NOT find PythonLibs (missing:  PYTHON_LIBRARIES PYTHON_INCLUDE_DIRS) (Required is at least version "2.7")
[Paddle] Python Executable: /home/enigma/src_packages/Paddle-develop/third_party/install/python/bin/python
[Paddle] Python Include: 
[Paddle] Python Libraries: /home/enigma/src_packages/Paddle-develop/third_party/install/python/lib/libpython2.7.a
```
也就是找到了 PythonInterp 但是没有找到 PythonLibs。用 `yum install python-devel` 以后再 cmake .. ，输出变成了：
```cmake
-- Found PythonInterp: /usr/bin/python2.7 (found suitable version "2.7.5", minimum required is "2.7") 
-- Found PythonLibs: /usr/lib64/libpython2.7.so (found suitable version "2.7.5", minimum required is "2.7") 
-- Could NOT find PY_pip (missing:  PY_PIP) 
CMake Error at cmake/python_module.cmake:27 (message):
  python module pip is not found
Call Stack (most recent call first):
  cmake/external/python.cmake:24 (find_python_module)
  CMakeLists.txt:63 (include)
```
安装 pip 并用 pip install numpy protobuf 以后可以检查通过。

**Comment by liujunyi-sjtu** [comment]
@gangliao 
有两个centos7出现的情况可能需要反应一下
第一个是cmake/external/protobuf.cmake里的ExternalProject_Add中可能需要加上zlib的参数，否则在环境里没有zlib的机器上，自动下载编译的protobuf会找到不到zlib，从而缺少zlib的支持
```
57     -Dprotobuf_BUILD_TESTS=OFF
58     -DZLIB_ROOT:FILEPATH=${ZLIB_ROOT} #或许需要加上这一行
59     -DCMAKE_POSITION_INDEPENDENT_CODE=ON
```

第二个是cmake时，cmake/external/protobuf.cmake里会出现这样的错误
```
CMake Error at cmake/external/protobuf.cmake:32 (IF):
  if given arguments:

    "STREQUAL" "centos"

  Unknown arguments specified
```
在把32行的${HOST_SYSTEM}加上引号以后问题解决，不知道是不是cmake的版本问题
```
32   IF("${HOST_SYSTEM}" STREQUAL "centos")
```

**Comment by EnigmaHuang** [comment]
@liujunyi-sjtu 你的 CMake 版本？

**Comment by gangliao** [comment]
@EnigmaHuang  谢谢您的反馈， 你可以提交一个PR吗，我帮你Review.

**Comment by liujunyi-sjtu** [comment]
@EnigmaHuang 3.7.2 我发现第二个问题是由于我centos7的机子上/etc/issue是空的，这样HOST_SYSTEM就没有正确的值。这或许是centos7自身的bug，我在强行把HOST_SYSTEM设置成"centos"以后就可以了。

**Comment by QiJune** [comment]
@gangliao @EnigmaHuang @liujunyi-sjtu
这个是之前paddle0.8.0版本时的centos编译文档，在centos 7上是没有问题的
https://github.com/QiJune/Paddle/blob/centos_support/doc/build/build_from_source.md#centos
0.9.0的编译过程改动较大，还没有在centos 7上测试过。我后面测试一下这个过程，然后把编译文档放到我个人的分支上吧

**Comment by gangliao** [comment]
Fixed #1155 #1152
