### ISSUE TITLE
加载fluid要7-8秒钟

### ISSUE THREAD

**Issue by lgone2000** [PaddlePaddle/Paddle#11533]
import paddle.fluid as fluid 
这句话执行了很长时间，能否降低这个加载时间呢？
对于调试程序，这个干扰很大。只要import fluid 什么都不做，都要等上一阵子

**Comment by wanghaoshuang** [comment]
@lgone2000  这个耗时主要在初始化device步骤，默认是初始化所有可见device, 你可以通过`export CUDA_VISIBLE_DEVICES=0`减少可见device，来缩减初始化时间。

**Comment by lgone2000** [comment]
it works

**Comment by lgone2000** [comment]
it works
