### ISSUE TITLE
在使用develop分支中提供的dockerfile进行安装Paddle时，安装失败

### ISSUE THREAD

**Issue by wen-bo-yang** [PaddlePaddle/Paddle#1154]
1. 在使用develop分支中提供的dockerfile进行安装Paddle时，安装失败，告知cmake最低版本必须为3.0。
![image](https://cloud.githubusercontent.com/assets/6229206/21968623/85cbd25a-dbd1-11e6-9de4-050521fe209a.png)
由于使用的是develop中提供的Dockerfile.gpu，编译镜像时使用的国内163的Ubuntu镜像进行安装，此时安装cmake的版本为2.8.12.2
![image](https://cloud.githubusercontent.com/assets/6229206/21968694/62447638-dbd2-11e6-87e1-7c724d741cb9.png)

**Comment by gangliao** [comment]
@wen-bo-yang  编译已经和以前不大一样了，docker这块我还没来得及修改，最近会改。

**Comment by gangliao** [comment]
#1169
