### ISSUE TITLE
编译paddlepaddle出错

### ISSUE THREAD

**Issue by hejiajia** [PaddlePaddle/Paddle#11565]
运行环境
内核版本：
Linux version 2.6.32_1-18-0-0  (gcc version 4.4.4 20100726 (Red Hat 4.4.4-13) (GCC) ) #1 SMP Fri Jan 29 18:37:55 CST 2016
paddlepaddle版本：0.13.0
gcc版本：gcc4.8.2

运行步骤
1.获取PaddlePaddle代码, 本模块基于PaddlePaddle v0.13.0实现
$ git clone https://github.com/PaddlePaddle/Paddle.git
$ cd Paddle
$ git checkout v0.13.0
2.本模块及所用的PaddlePaddle Fluid Inference是基于gcc4.8.2编译的，修改CMakeLists.txt文件：
增加一行：SET(CMAKE_CXX_COMPILER "/opt/compiler/gcc-4.8.2/bin/g++")
3.生成Makefile，此步骤需要在build目录内进行
$ mkdir build
$ cd build
$ cmake -DCMAKE_BUILD_TYPE=Release -DWITH_PYTHON=OFF -DWITH_MKL=ON -DWITH_GPU=OFF -DWITH_FLUID_ONLY=ON ..
4.编译PaddlePaddle并部署Fluid Inference, 默认部署到Paddle/build/fluid_install_dir
$ make

报错信息如图
![default](https://user-images.githubusercontent.com/13762927/41582683-db9c1ffe-73d4-11e8-8c1a-c2aa29f28ecf.png)

详细情况可联系hi号：hejiajia_91

**Comment by tensor-tang** [comment]
补充说明下，WITH_MKLDNN=OFF，可以编译过。
