### ISSUE TITLE
ImportError: No module named easydict

### ISSUE THREAD

**Issue by liuliyalei** [PaddlePaddle/Paddle#11589]
在jupyter notebook当中代码如下：
from easydict import EasyDict as edict

报错：
ImportErrorTraceback (most recent call last)
<ipython-input-12-8c181a6ae8b4> in <module>()
----> 1 from easydict import EasyDict as edict
ImportError: No module named easydict

之后我在系统中用pip install easydict --user安装了easydict
在python中测试
from easydict import EasyDict as edict
没有报错

再到在jupyter notebook运行代码如下：
from easydict import EasyDict as edict

依旧报错：
ImportErrorTraceback (most recent call last)
<ipython-input-1-8c181a6ae8b4> in <module>()
----> 1 from easydict import EasyDict as edict
ImportError: No module named easydict

请问是什么问题？

**Comment by JiayiFeng** [comment]
我本人对jupyter notebook不是很了解，但感觉在系统中pip安装包再在jupyter notebook中使用可能是行不通的。如何在jupyter notebook内安装包，我找了一个相关的文章，可供参考:
https://jakevdp.github.io/blog/2017/12/05/installing-python-packages-from-jupyter/

**Comment by zezhou** [comment]
1) 重启 jupyter notebook 了吗?

2) jupyter notebook 和 pip install的是同一个版本的python吗？
比如 jupyter 用的 python3 ,pip 默认是 python 2

3) jupyter notebook 和 pip install的是同一个python env吗？

**Comment by liuliyalei** [comment]
重装了jupyter之后问题解决，谢谢各位
