### ISSUE TITLE
矩阵形式的layer如何定义？

### ISSUE THREAD

**Issue by coollip** [PaddlePaddle/Paddle#1159]
在paddle的文档中看到有trans_layer这种layer
![image](https://cloud.githubusercontent.com/assets/18412946/21973996/1e6edea8-dbff-11e6-85b4-203ee8e0af98.png)
其中x是(MxN)的layer，想问一下，x这种矩阵形式的layer是如何在paddle中定义的？我想定义一个10*50的矩阵layer应该怎么做？

另外，如果可以定义10*50的矩阵layer，如何取出其中第i行(或者第i列)？

**Comment by coollip** [comment]
求指点一二。。

**Comment by reyoung** [comment]
@coollip 不是特别理解，这个矩阵有什么特别的地方么？如果没有的话，为什么不能直接用data_layer送进来？
