### ISSUE TITLE
fluid/platform/float16 cyclically depends on fluid/framework

### ISSUE THREAD

**Issue by wangkuiyi** [PaddlePaddle/Paddle#11611]
Due to the line

https://github.com/PaddlePaddle/Paddle/blob/c413c469158db18bc5f18408e6c1814636ec74e2/paddle/fluid/platform/float16.h#L70

**Comment by kexinzhao** [comment]
This issue has been discussed before in https://github.com/PaddlePaddle/Paddle/pull/10587#pullrequestreview-119572393.

If we want to make the fix pass, we may need to disable the some test in tensor_util_test and risk some util functions have segmentation fault when running.

After discussion with @wangkuiyi,  we close this issue for now.
