### ISSUE TITLE
pip安装paddlepaddle，paddle所使用的protobuf 3.1.0和系统已有的tensorflow使用的protobuf>=3.4.0冲突

### ISSUE THREAD

**Issue by liuliyalei** [PaddlePaddle/Paddle#11613]
tensorflow-gpu 1.8.0 has requirement protobuf>=3.4.0, but you'll have protobuf 3.1.0 which is incompatible.

tensorflow-tensorboard 0.4.0 has requirement protobuf>=3.4.0, but you'll have protobuf 3.1.0 which is incompatible.

tensorboard 1.8.0 has requirement protobuf>=3.4.0, but you'll have protobuf 3.1.0 which is incompatible.

grpcio 1.11.0 has requirement protobuf>=3.5.0.post1, but you'll have protobuf 3.1.0 which is incompatible.

flake8 3.5.0 has requirement pycodestyle<2.4.0,>=2.0.0, but you'll have pycodestyle 2.4.0 which is incompatible.

请问要怎么修改才能同时兼容tensorflow和paddlepaddle

**Comment by vic-93** [comment]
请问是如何解决的呢
