### ISSUE TITLE
selective fc layer mask的维度问题

### ISSUE THREAD

**Issue by shenshuijing** [PaddlePaddle/Paddle#1164]
我的provider如下：
![image](https://cloud.githubusercontent.com/assets/24400858/22009209/71148e7e-dcbc-11e6-9a5b-db519de36492.png)
其中第一个是sparse的feature， 第二个是后续用于selective fc layer的mask的sparse输入， 第三个是label信息
网络结构为：
![image](https://cloud.githubusercontent.com/assets/24400858/22009257/c4c11574-dcbc-11e6-8b32-65053dcb43c7.png)
本地训练后报矩阵相乘出错，错误信息为：
![image](https://cloud.githubusercontent.com/assets/24400858/22009317/42389fd6-dcbd-11e6-93f9-61647d92c767.png)
我的疑问是， 虽然我再provider中第二个输入， 是每个64个数字， 但是是sparse的， 这个64不是维度， 维度应该是256才对， 为什么会有矩阵相乘的时候出现64的dimension呢？

**Comment by reyoung** [comment]
1、请问一下Provider中的SELECT_COLUM_DIM是多少？是256还是64呢？
2、SelectFC似乎用在预测时候提速，训练时候使用这个Layer的情况我不是特别清楚。 @lcy-seso

**Comment by shenshuijing** [comment]
SELECT_COLUM_DIM 这个是256的

**Comment by lcy-seso** [comment]
@shenshuijing 请问想用 selective_fc 实现什么样的功能，是否方便解释一下逻辑呢？因为，selective_fc 的训练流程目前只是为了支持训练 sampled_softmax 而写，不确定是不是和你的需求有出入。

上面这个错误原因是这样的：
1. selective_fc 用于训练有一个限制：选择的列必须始终都是相同的
2. 如果可以保证1的限制，在训练时 selective fc 的输出是一个 dense 矩阵，并不是一个稀疏矩阵
3. 假设如果你可以保证所有的训练样本都只选择 64 列； selective_fc 这一层训练时候输出的宽度是由第二个参数的 nnz / height决定的（也就是 selected colums 那个输入，这是一个系数矩阵）
4. 以上 3 者会导致 selective fc 输出层的size 是 64，而不是 256 。

**Comment by shenshuijing** [comment]
我的需求是有几个自然属性的识别， 年龄，性别，职业等， 我想在底层网络结构进行共享， 中间通过selective_fc 来选择性输出， 比如年龄就选择输出0~64的输出（或者其他设置0）， 
所以我的需求应该1是不满足的

**Comment by lcy-seso** [comment]
那自己构造一个mask，点乘呢？

**Comment by shenshuijing** [comment]
嗯， 我就这样改下， 非常感谢

**Comment by chenbblei** [comment]
@shenshuijing 请问该怎么改呢

我的需求是有几个自然属性的识别， 年龄，性别，职业等， 我想在底层网络结构进行共享， 中间通过selective_fc 来选择性输出， 比如年龄就选择输出0~64的输出（或者其他设置0）
