### ISSUE TITLE
运行if name == "main":报错ImportError: libmklml_intel.so: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by liuliyalei** [PaddlePaddle/Paddle#11645]
pip安装的cpu版本，ubuntu系统，用jupyter notebook运行代码
`...
class TestMNIST:
    def __init__(self):
        # 该模型运行在CUP上，CUP的数量为2
        paddle.init(use_gpu=False, trainer_count=2)

    # *****************获取训练器********************************
    def get_trainer(self):
...
if __name__ == "__main__":
    testMNIST = TestMNIST()
    # 开始训练
    testMNIST.start_trainer()`

报错：
ImportError                               Traceback (most recent call last)
<ipython-input-2-74ea324012ee> in <module>()
     90 
     91 if __name__ == "__main__":
---> 92     testMNIST = TestMNIST()
     93     # 开始训练
     94     testMNIST.start_trainer()

<ipython-input-2-74ea324012ee> in __init__(self)
      9     def __init__(self):
     10         # 该模型运行在CUP上，CUP的数量为2
---> 11         paddle.init(use_gpu=False, trainer_count=2)
     12 
     13     # *****************获取训练器********************************

/home/liul9/.local/lib/python2.7/site-packages/paddle/v2/__init__.pyc in init(**kwargs)
    126 
    127 def init(**kwargs):
--> 128     import py_paddle.swig_paddle as api
    129     args = []
    130     args_dict = {}

/home/liul9/.local/lib/python2.7/site-packages/py_paddle/__init__.py in <module>()
     13 # limitations under the License.
     14 
---> 15 from util import DataProviderWrapperConverter
     16 from dataprovider_converter import DataProviderConverter
     17 

/home/liul9/.local/lib/python2.7/site-packages/py_paddle/util.py in <module>()
     16 """
     17 
---> 18 import swig_paddle
     19 import os
     20 import paddle.trainer.PyDataProviderWrapper

/home/liul9/.local/lib/python2.7/site-packages/py_paddle/swig_paddle.py in <module>()
     26                 fp.close()
     27             return _mod
---> 28     _swig_paddle = swig_import_helper()
     29     del swig_import_helper
     30 else:

/home/liul9/.local/lib/python2.7/site-packages/py_paddle/swig_paddle.py in swig_import_helper()
     22         if fp is not None:
     23             try:
---> 24                 _mod = imp.load_module('_swig_paddle', fp, pathname, description)
     25             finally:
     26                 fp.close()

ImportError: libmklml_intel.so: cannot open shared object file: No such file or directory

**Comment by luotao1** [comment]
请参考 [FAQ](https://github.com/chengduoZH/Paddle/blob/b5daeac86d79400302ab8acd658716f783012346/doc/v2/faq/build_and_install/index_cn.rst#10-%E9%80%9A%E8%BF%87pip%E5%AE%89%E8%A3%85%E7%9A%84paddlepaddle%E5%9C%A8--import-paddlefluid-%E6%8A%A5%E6%89%BE%E4%B8%8D%E5%88%B0-libmkldnnso-%E6%88%96-libmklml_intelso)，看你的路径应该是`export LD_LIBRARY_PATH=/home/liul9/.local/lib:$LD_LIBRARY_PATH`

**Comment by liuliyalei** [comment]
@luotao1 
请问添加这一行代码应该在哪个文件里面？我看的不是很明白

**Comment by liuliyalei** [comment]
在bashrc添加了export LD_LIBRARY_PATH=/home/liul9/.local/lib:$LD_LIBRARY_PATH
在终端中运行source .bashrc
重启jupyter notebook
依旧出错
@luotao1

**Comment by liuliyalei** [comment]
重启系统后已解决谢谢 @luotao1
