### ISSUE TITLE
PaddlePaddle Fluid训练时如何做cross validation验证？

### ISSUE THREAD

**Issue by zzhzz** [PaddlePaddle/Paddle#11643]
我在官方book的image_classification中见到这样一句代码
> test_program = fluid.default_main_program().clone(for_test=True)

链接：https://github.com/PaddlePaddle/Paddle/blob/833a6f36e170124585cd6863619afb1108bf6efc/python/paddle/fluid/tests/book/test_image_classification.py#L125
请问这个test_program是用来做cross validation的program吗？
如果不是请问训练中如何做cross validation?
如果是的话，我在训练中发现该方式会影响模型训练，可能会把用于validation的数据拿去训练，如何解决？

**Comment by dzhwinter** [comment]
可以用来做validation。没有optimizer就不会有参数更新，你观察一下，都是在optimizer之前创建的。

**Comment by zzhzz** [comment]
@dzhwinter 很感谢回答，另外还想请问一下dropout layer里面的is_test参数如何在validation时传入？还是说Paddle会自动处理这个问题

**Comment by dzhwinter** [comment]
"for_test" 就是在处理这个问题。比方说dropout, batch_norm，train和test时候不一致的op，会自动设置attribute
