### ISSUE TITLE
Paddlepaddle pretrained model

### ISSUE THREAD

**Issue by JiahaoYao** [PaddlePaddle/Paddle#11650]
I find the imagenet pretrained models only has three, as shown in [pretrained model](https://github.com/PaddlePaddle/models/blob/develop/image_classification/models/model_download.sh#L28-L38). What is about the others? For example, the googlenet and inception. Is it forgotten to add to the download script?

**Comment by dzhwinter** [comment]
Currently, we only provide these pertained models. There is a caffe2paddle model convert script available, please try it.

**Comment by JiahaoYao** [comment]
Thank you for your reply, @dzhwinter!
