### ISSUE TITLE
训练模型kernel died:The kernel appears to have died. It will restart automatically.

### ISSUE THREAD

**Issue by liuliyalei** [PaddlePaddle/Paddle#11656]
Ubuntu 16.04.4 LTS 64 位
GeForce GTX 1080 Ti/PCIe/SSE2
Intel® Xeon(R) CPU E5-2620 v4 @ 2.10GHz × 16
PaddlePaddle GPU 0.13.0

训练模型的时候总是出现kernel died的情况
The kernel appears to have died. It will restart automatically.
![qq 20180622153624](https://user-images.githubusercontent.com/40382579/41763881-0cdf156c-7632-11e8-87ce-671d5e4a0147.png)

同时系统提示：
应用程序python2.7意外停止

![qq 20180622152808](https://user-images.githubusercontent.com/40382579/41763831-e6c2757c-7631-11e8-84ec-5357df6224dd.png)

**Comment by ktlichkid** [comment]
据 #11678 问题应该已经解决？如果仍未解决欢迎重新打开issue~
