### ISSUE TITLE
executor and parallel executor do not return the same type of fetch_list

### ISSUE THREAD

**Issue by seiriosPlus** [PaddlePaddle/Paddle#11664]
When I run the train with ```executor```, I get the loss:
```
loss: [0.51612484], type: <type 'numpy.ndarray'>
```
But when I run the train with ```parallel executor```, I get the loss:
```
loss: <paddle.fluid.core.LoDTensor object at 0x7f05d6a659f0>, type: <class 'paddle.fluid.core.LoDTensor'>
```

I think we should make the result of ```executor.run()``` are same.

**Comment by jacquesqiao** [comment]
We have a flag in executor.run `as_numpy` to convert returned tensor into numpy.

**Comment by seiriosPlus** [comment]
@jacquesqiao 
We have a flag in ```executor.run``` ```as_numpy``` to convert returned tensor into numpy.

But we do not have ```as_numpy``` in ```ParallelExecutor.run```.
