### ISSUE TITLE
PaddlePaddle wasn't compiled to use avx instructions, but these are available on your machine and could speed up CPU computations via CMAKE .. -DWITH_AVX=ON

### ISSUE THREAD

**Issue by liuliyalei** [PaddlePaddle/Paddle#11675]
ubuntu16.04
pip安装paddlepaddle-0.12.0-cp27-cp27mu-manylinux1_x86_64.wh
python2.7.12

如下：
liul9@ubuntu:~$ python
Python 2.7.12 (default, Dec  4 2017, 14:50:18) 
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import paddle.v2 as paddle
>>> paddle.init(use_gpu=False,trainer_count=1)
I0623 18:08:48.372473  2270 Util.cpp:166] commandline:  --use_gpu=False --trainer_count=1 
W0623 18:08:48.372601  2270 CpuId.h:112] PaddlePaddle wasn't compiled to use avx instructions, but these are available on your machine and could speed up CPU computations via CMAKE .. -DWITH_AVX=ON
>>> 

表示这个问题要怎么解决？？？？求大神呀，被这个问题困扰的没法前进

更新：
ubuntu16.04
PIP安装的paddlepaddle_gpu-0.12.0-cp27-cp27mu-manylinux1_x86_64.whl
python2.7.12

在jupyter notebook中运行代码：
I0625 14:05:03.713416 22055 Util.cpp:166] commandline:  --use_gpu=False --trainer_count=2 
W0625 14:05:03.713452 22055 CpuId.h:112] PaddlePaddle wasn't compiled to use avx instructions, but these are available on your machine and could speed up CPU computations via CMAKE .. -DWITH_AVX=ON

**Comment by seiriosPlus** [comment]
编译的时候加入  -DWITH_AVX=ON 选项。
参考： http://www.paddlepaddle.org/docs/develop/documentation/fluid/zh/build_and_install/build_from_source_cn.html#build-options

**Comment by liuliyalei** [comment]
请问我用pip安装的paddle，还是要走源码编译那一步嘛？ @seiriosPlus

**Comment by seiriosPlus** [comment]
http://www.paddlepaddle.org/docs/develop/documentation/fluid/zh/build_and_install/pip_install_cn.html#id6
可以来这里下载对应的版本

**Comment by liuliyalei** [comment]
问题依然存在，我确认我下了相应的版本 @seiriosPlus

**Comment by seiriosPlus** [comment]
你下载的具体链接是哪一个，我尝试一下

**Comment by liuliyalei** [comment]
paddlepaddle-0.12.0-cp27-cp27mu-manylinux1_x86_64.whl @seiriosPlus

**Comment by seiriosPlus** [comment]
我在Ubuntu 16.04.4 LTS 下安装https://guest@paddleci.ngrok.io/repository/download/Manylinux1_CpuAvxCp27cp27mu/.lastSuccessful/paddlepaddle-latest-cp27-cp27m-linux_x86_64.whl 
没有遇到问题，你试一下这个呢

**Comment by liuliyalei** [comment]
你的连接我一直下载不下来，能不能给个其他下载方式 @seiriosPlus

**Comment by seiriosPlus** [comment]
https://pan.baidu.com/s/1fA75nxTsIxJ8LGenJpPJWA
@liuliyalei 7天失效。

**Comment by liuliyalei** [comment]
问题已经解决，谢谢，请问有GPU 版本的嘛，准备在另外一台带有GPU版本的电脑上跑程序 @seiriosPlus

**Comment by seiriosPlus** [comment]
建议去http://www.paddlepaddle.org/docs/develop/documentation/fluid/zh/build_and_install/pip_install_cn.html下载所需的版本。
网络问题建议自行解决，放网盘不可持续。
