### ISSUE TITLE
如何在训练TextCNN模型时加载预训练的word2vec字典

### ISSUE THREAD

**Issue by jiachengni** [PaddlePaddle/Paddle#11674]
看了下textCnn模型一般都会加embedding层再接卷积层，怎么加载预训练的Wordvec字典做初始化呢？

**Comment by seiriosPlus** [comment]
参考https://github.com/seiriosPlus/fluid_benchmark/blob/master/text_classification/train_low_api.py
这个会预先传入一个词典。

**Comment by jiachengni** [comment]
这个demo我看过，把明文转成id ,输入层的类型是paddle.data_type.integer_value_sequence，如果我通过预训练的word2vec字典，把word_id序列转成矩阵，那 paddle.networks.sequence_conv_pool的input可以是dense_array吗？

**Comment by seiriosPlus** [comment]
我理解应该是可以的，你可以尝试一下。
