### ISSUE TITLE
PaddlePaddle如何导入IDE来阅读代码，因为本身cmakelist，就打算导入clion中，一直未成功，有小伙伴可以指导下吗？ 读源码太麻烦

### ISSUE THREAD

**Issue by shangguanyifeng** [PaddlePaddle/Paddle#11689]
As title

**Comment by ktlichkid** [comment]
请问尝试直接open或者import可以吗？不行的话是什么问题

**Comment by tonyyang-svail** [comment]
@shangguanyifeng 在linux下的话，可以试试在docker里用clion

https://gist.github.com/tonyyang-svail/9904abaef3201d729df47e2357127c88

**Comment by burness** [comment]
@tonyyang-svail  有mac 读源码的解决方案吗 ？ 我这里也遇到如上题目的问题

-----
搞定了 多谢

**Comment by ktlichkid** [comment]
没有follow-up的话这个issue先关闭了。如果有进一步问题欢迎打开~

**Comment by kinghuin** [comment]
需要配置一下CLION的python路径
命令行执行
```bash
which python
```
然后配置CLION：
Clion -- Preferences -- Build, Execution, Deployment -- CMake -- CMake options -- 
填入：
-DPYTHON_EXECUTABLE= 刚刚which python显示的路径
最后
File -- Reload CMake Project
