### ISSUE TITLE
【Question】关于embedding_layer和table_projection的联系与区别，以及LSTM单元的疑问

### ISSUE THREAD

**Issue by pkuyym** [PaddlePaddle/Paddle#1168]
1. embedding_layer和table_projection都可以把离散值转换为稠密实数向量，请问这两个layer有什么不同？
2. 在RNN配置里面的simple_attention样例里面有这样的逻辑：

>  decoder_inputs = mixed_layer(inputs = [full_matrix_projection(context),
>                                            full_matrix_projection(current_word)],
>                                  size = decoder_size * 3)
>   gru_step = gru_step_layer(name='gru_decoder',
>                               input=decoder_inputs,
>                               output_mem=decoder_mem,
>                               size=decoder_size)

  decoder_inputs的size为什么是3倍的decoder_size，同时在simple_lstm里面

>  with mixed_layer(
>             name=fc_name,
>             size=size * 4,
>             act=IdentityActivation(),
>             layer_attr=mixed_layer_attr,
>             bias_attr=False) as m:
>         m += full_matrix_projection(input, param_attr=mat_param_attr)

这个size是4倍的输入的size
请问这里面的逻辑？

**Comment by reyoung** [comment]
1、embedding_layer调用了table_projection。 table_projection是一个projection，而不是layer。Paddle的Projection只可以使用在mixed_layer中。使用Projection，Paddle可以配置类似于其他神经网络框架OP的功能(矩阵乘法, etc)。

2、这个逻辑是因为，Paddle实现的lstm_layer并不是完整的lstm cell，而是将参数的乘法剥离出来。这样做，可以实现非常高的自由度和定制行(gru也一样)。

具体参考这段注释 https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/trainer_config_helpers/layers.py#L1079

**Comment by pkuyym** [comment]
@reyoung 所以说4倍的size，分别指`W_{xi}x_{t}` ,`W_{xf}x_{t}`,`W_{xc}x_t`, `W_{xo}x_{t}`，这些矩阵乘法需要利用fc或者projection自己实现，然后作为input，输入到gru_step_layer或lstmmemory

**Comment by reyoung** [comment]
是的。

**Comment by pkuyym** [comment]
好的，谢谢 @reyoung  的解答，很详细，可以close掉了

**Comment by reyoung** [comment]
客气
