### ISSUE TITLE
fluid卷积层参数用numpy初始化

### ISSUE THREAD

**Issue by Leezhaohui** [PaddlePaddle/Paddle#11703]
比如说：
fluid.layers.conv2d(
        input=input, num_filters=32, filter_size=3, stride=1, padding=1)
如果用numpy对其weight进行初始化,那么numpy的shape应该是什么？

**Comment by qingqing01** [comment]
Fluid conv2d层的参数shape是: [Co, Ci/group, Kh, Kw]
对应你这里例子是：[32, Ci/group, 3, 3]
Co是输出的channel数，Ci是input的channel数，Kh, Kw是filer大小。

也可以参考文档：http://www.paddlepaddle.org/docs/develop/api/fluid/en/layers.html#conv2d

**Comment by Leezhaohui** [comment]
那么我可以提取在v2版本下训练好的VGG16模型的参数，reshape成上述shape，然后给fluid卷积层进行初始化吗？ @qingqing01

**Comment by qingqing01** [comment]
可以的~
