### ISSUE TITLE
Paddle如何实现SRU网络

### ISSUE THREAD

**Issue by chenbblei** [PaddlePaddle/Paddle#11716]
如题，在哪个位置可以新增SRU网络，或者如何写比较方便

**Comment by qingqing01** [comment]
请参考[`fluid.layers.DynamicRNN`文档](http://www.paddlepaddle.org/docs/develop/api/fluid/en/layers.html?highlight=dynamicrnn#dynamicrnn)，这个文档里有个示例代码，是如何写一个最简单的RNN层。 

对于SRU，可以采用`fluid.layers.DynamicRNN`来封装一个吧。后续Paddle也加一个对SRU的支持吧，当前，可以自行先利用基础op和`fluid.layers.DynamicRNN`封装吧。

**Comment by chenbblei** [comment]
@qingqing01 多谢

**Comment by chenbblei** [comment]
@qingqing01 有V2对应的DynamicRNN么

**Comment by qingqing01** [comment]
@chenbblei V2是 [recurrent_group](http://www.paddlepaddle.org/docs/develop/api/en/config/layer.html#permalink-32-recurrent_group)。

**Comment by chenbblei** [comment]
@qingqing01 多谢
