### ISSUE TITLE
paddle.v2.layer.gru_step  跟GRU有什么关系

### ISSUE THREAD

**Issue by chenbblei** [PaddlePaddle/Paddle#11724]
看使用方法就是一个循环迭代的过程，跟GRU有什么关系？

**Comment by qingqing01** [comment]
GRU：是一个完整的、包含所有时间步的计算
gru_step:  只计算一个时间步，一般用于[recurrent-layer-group](  http://www.paddlepaddle.org/docs/develop/api/en/config/layer.html#permalink-30-recurrent-layer-group)中。

**Comment by chenbblei** [comment]
@qingqing01 也就是跟GRU结构没啥关系对吧

**Comment by qingqing01** [comment]
@chenbblei 也不能说完全没关系。 paddle.v2.layer.gru_step是一个时间步的GRU计算。

**Comment by chenbblei** [comment]
@qingqing01 那我不用GRU的话，用FC,我直接改成layer.fc也是可以的吧
