### ISSUE TITLE
piror box layer的实现中存储的bbx顺序不一致，是否能支持对齐？

### ISSUE THREAD

**Issue by tanxchong** [PaddlePaddle/Paddle#11734]
caffe中的priorbox实现是min max s1 s2 ...  1/s1, 1/s2...的顺序，paddle中实现是min s1 1/s1, s2 1/s2... max的顺序，是否可以提供一个参数来调整prior的存储循序和caffe对齐呢？

**Comment by qingqing01** [comment]
@tanxchong  可以的，我们稍后加下~
