### ISSUE TITLE
情感分析的dome，怎么用自定义的训练集和测试集？  

### ISSUE THREAD

**Issue by shangguanyifeng** [PaddlePaddle/Paddle#11732]
demo的例子是用的 imdb 的数据集，我想用自己的数据集。请问怎么把训练集和测试集运用到demo里面

**Comment by qingqing01** [comment]
情感分析的demo也是文本分类，可以参考模型库中文本分类教程中 [使用自定义数据训练 部分](https://github.com/PaddlePaddle/models/tree/develop/text_classification#%E4%BD%BF%E7%94%A8%E8%87%AA%E5%AE%9A%E4%B9%89%E6%95%B0%E6%8D%AE%E8%AE%AD%E7%BB%83%E5%92%8C%E9%A2%84%E6%B5%8B)。

**Comment by qingqing01** [comment]
这个issue关闭了，上面提到的教程，已告诉用户如何操作了，如果有具体问题，欢迎再开issue。
