### ISSUE TITLE
fluid有没有LSTM的教程，我想做decoder部分

### ISSUE THREAD

**Issue by LogicHolmes** [PaddlePaddle/Paddle#11749]
你好，我最近在做image caption，想用fluid做decoder部分，但是fluid这部分资料很少，导致进度很慢！

**Comment by qingqing01** [comment]
Fluid基于encoder-decoder的机器翻译正在开发中，可以参考： 
1. https://github.com/PaddlePaddle/models/pull/954
2. https://github.com/dzhwinter/benchmark/blob/master/fluid/machine_translation.py

**Comment by qingqing01** [comment]
@LogicHolmes 这个issue关闭了。 我们正在做的机器翻译和OCR识别的Attention模型都会包含decoder部分，参数上述资料的同时，如果有具体问题，欢迎再开issue。
