### ISSUE TITLE
protobuf与glog一些引用找不到

### ISSUE THREAD

**Issue by gucasbrg** [PaddlePaddle/Paddle#1174]
按https://github.com/PaddlePaddle/Paddle/blob/develop/doc/getstarted/build_and_install/build_from_source_en.md安装，出现以下错误：
另外CMakeFiles/openblas.dir/build.make 中
/usr/bin/gmake FC=/usr/bin/gfortran CC=/usr/local/bin/gcc HOSTCC=/usr/local/bin/gcc NO_SHARED=1 BINARY=64 U
SE_THREADS=1 NUM_THREADS=8 TARGET=SANDYBRIDGE libs netlib
如果不加另外的参数机器也过不去

Done processing test_FPException.cpp
Total errors found: 0
../../gserver/libpaddle_gserver.a(WarpCTCLayer.cpp.o): In function `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >* google::MakeCheckOpString<unsigned long, unsigned long>(unsigned long const&, unsigned long const&, char const*)':
/home/hotel-revenuetest/ruguo.bu/software/Paddle/third_party/install/glog/include/glog/logging.h:689: undefined reference to `_ZN6google4base21CheckOpMessageBuilder9NewStringB5cxx11Ev'
../../gserver/libpaddle_gserver.a(ValidationLayer.cpp.o): In function `SetNoArena':
/home/hotel-revenuetest/ruguo.bu/software/Paddle/third_party/install/protobuf/include/google/protobuf/arenastring.h:210: undefined reference to `_ZN6google8protobuf8internal26fixed_address_empty_stringB5cxx11E'
/home/hotel-revenuetest/ruguo.bu/software/Paddle/third_party/install/protobuf/include/google/protobuf/arenastring.h:210: undefined reference to `_ZN6google8protobuf8internal26fixed_address_empty_stringB5cxx11E'
../../gserver/libpaddle_gserver.a(TransLayer.cpp.o): In function `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >* google::MakeCheckOpString<int, int>(int const&, int const&, char const*)':
/home/hotel-revenuetest/ruguo.bu/software/Paddle/third_party/install/glog/include/glog/logging.h:689: undefined reference to `_ZN6google4base21CheckOpMessageBuilder9NewStringB5cxx11Ev'
../../gserver/libpaddle_gserver.a(SumToOneNormLayer.cpp.o): In function `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >* google::MakeCheckOpString<unsigned long, unsigned int>(unsigned long const&, unsigned int const&, char const*)':
/home/hotel-revenuetest/ruguo.bu/software/Paddle/third_party/install/glog/include/glog/logging.h:689: undefined reference to `_ZN6google4base21CheckOpMessageBuilder9NewStringB5cxx11Ev'
../../gserver/libpaddle_gserver.a(SumToOneNormLayer.cpp.o): In function `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >* google::MakeCheckOpString<float, double>(float const&, double const&, char const*)':
/home/hotel-revenuetest/ruguo.bu/software/Paddle/third_party/install/glog/include/glog/logging.h:689: undefined reference to `_ZN6google4base21CheckOpMessageBuilder9NewStringB5cxx11Ev'
../../gserver/libpaddle_gserver.a(SubSequenceLayer.cpp.o): In function `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >* google::MakeCheckOpString<bool, bool>(bool const&, bool const&, char const*)':
/home/hotel-revenuetest/ruguo.bu/software/Paddle/third_party/install/glog/include/glog/logging.h:689: undefined reference to `_ZN6google4base21CheckOpMessageBuilder9NewStringB5cxx11Ev'
../../gserver/libpaddle_gserver.a(SubSequenceLayer.cpp.o): In function `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >* google::MakeCheckOpString<unsigned int, unsigned long>(unsigned int const&, unsigned long const&, char const*)':
/home/hotel-revenuetest/ruguo.bu/software/Paddle/third_party/install/glog/include/glog/logging.h:689: undefined reference to `_ZN6google4base21CheckOpMessageBuilder9NewStringB5cxx11Ev'
../../gserver/libpaddle_gserver.a(SubSequenceLayer.cpp.o):/home/hotel-revenuetest/ruguo.bu/software/Paddle/third_party/install/glog/include/glog/logging.h:689: more undefined references to `_ZN6google4base21CheckOpMessageBuilder9NewStringB5cxx11Ev' follow
../../gserver/libpaddle_gserver.a(SpatialPyramidPoolLayer.cpp.o): In function `SetNoArena':
/home/hotel-revenuetest/ruguo.bu/software/Paddle/third_party/install/protobuf/include/google/protobuf/arenastring.h:210: undefined reference to `_ZN6google8protobuf8internal26fixed_address_empty_stringB5cxx11E'
/home/hotel-revenuetest/ruguo.bu/software/Paddle/third_party/install/protobuf/include/google/protobuf/arenastring.h:210: undefined reference to `_ZN6google8protobuf8internal26fixed_address_empty_stringB5cxx11E'
../../gserver/libpaddle_gserver.a(LinearChainCRF.cpp.o): In function `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >* google::MakeCheckOpString<float, int>(float const&, int const&, char const*)':
/home/hotel-revenuetest/ruguo.bu/software/Paddle/third_party/install/glog/include/glog/logging.h:689: undefined reference to `_ZN6google4base21CheckOpMessageBuilder9NewStringB5cxx11Ev'
../../gserver/libpaddle_gserver.a(Layer.cpp.o): In function `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >* google::MakeCheckOpString<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, char [8]>(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, char const (&) [8], char const*)':
/home/hotel-revenuetest/ruguo.bu/software/Paddle/third_party/install/glog/include/glog/logging.h:689: undefined reference to `_ZN6google4base21CheckOpMessageBuilder9NewStringB5cxx11Ev'
../../gserver/libpaddle_gserver.a(GetOutputLayer.cpp.o): In function `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >* google::MakeCheckOpString<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, char [1]>(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, char const (&) [1], char const*)':
/home/hotel-revenuetest/ruguo.bu/software/Paddle/third_party/install/glog/include/glog/logging.h:689: undefined reference to `_ZN6google4base21CheckOpMessageBuilder9NewStringB5cxx11Ev'
../../gserver/libpaddle_gserver.a(ExpandLayer.cpp.o): In function `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >* google::MakeCheckOpString<bool, unsigned long>(bool const&, unsigned long const&, char const*)':
/home/hotel-revenuetest/ruguo.bu/software/Paddle/third_party/install/glog/include/glog/logging.h:689: undefined reference to `_ZN6google4base21CheckOpMessageBuilder9NewStringB5cxx11Ev'
../../gserver/libpaddle_gserver.a(ExpandLayer.cpp.o): In function `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >* google::MakeCheckOpString<long, long>(long const&, long const&, char const*)':
/home/hotel-revenuetest/ruguo.bu/software/Paddle/third_party/install/glog/include/glog/logging.h:689: undefined reference to `_ZN6google4base21CheckOpMessageBuilder9NewStringB5cxx11Ev'
../../gserver/libpaddle_gserver.a(ConvOperator.cpp.o):/home/hotel-revenuetest/ruguo.bu/software/Paddle/third_party/install/glog/include/glog/logging.h:689: more undefined references to `_ZN6google4base21CheckOpMessageBuilder9NewStringB5cxx11Ev' follow
../../gserver/libpaddle_gserver.a(RecurrentGradientMachine.cpp.o): In function `SetNoArena':
/home/hotel-revenuetest/ruguo.bu/software/Paddle/third_party/install/protobuf/include/google/protobuf/arenastring.h:210: undefined reference to `_ZN6google8protobuf8internal26fixed_address_empty_stringB5cxx11E'
../../gserver/libpaddle_gserver.a(RecurrentGradientMachine.cpp.o): In function `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >* google::MakeCheckOpString<long, int>(long const&, int const&, char const*)':
/home/hotel-revenuetest/ruguo.bu/software/Paddle/third_party/install/glog/include/glog/logging.h:689: undefined reference to `_ZN6google4base21CheckOpMessageBuilder9NewStringB5cxx11Ev'
../../gserver/libpaddle_gserver.a(MultiNetwork.cpp.o): In function `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >* google::MakeCheckOpString<char [5], std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >(char const (&) [5], std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, char const*)':
/home/hotel-revenuetest/ruguo.bu/software/Paddle/third_party/install/glog/include/glog/logging.h:689: undefined reference to `_ZN6google4base21CheckOpMessageBuilder9NewStringB5cxx11Ev'
../../gserver/libpaddle_gserver.a(MultiGradientMachine.cpp.o): In function `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >* google::MakeCheckOpString<paddle::enumeration_wrapper::ParameterType, paddle::enumeration_wrapper::ParameterType>(paddle::enumeration_wrapper::ParameterType const&, paddle::enumeration_wrapper::ParameterType const&, char const*)':
/home/hotel-revenuetest/ruguo.bu/software/Paddle/third_party/install/glog/include/glog/logging.h:689: undefined reference to `_ZN6google4base21CheckOpMessageBuilder9NewStringB5cxx11Ev'
../../gserver/libpaddle_gserver.a(GradientMachine.cpp.o): In function `paddle::GradientMachine::create(std::istream&, paddle::TrainerConfig*)':
/home/hotel-revenuetest/ruguo.bu/software/Paddle/paddle/gserver/gradientmachines/GradientMachine.cpp:95: undefined reference to `google::protobuf::MessageLite::ParseFromString(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
../../gserver/libpaddle_gserver.a(PyDataProvider.cpp.o): In function `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >* google::MakeCheckOpString<char*, char const*>(char* const&, char const* const&, char const*)':

**Comment by reyoung** [comment]
看起来这个issue没有问题了。用户自己close掉了。
