### ISSUE TITLE
Move fluid::operators::math::SetNumThreads to fluid::platoform

### ISSUE THREAD

**Issue by wangkuiyi** [PaddlePaddle/Paddle#11754]
The setting of the number of threads is platform dependent operation. It is improper to put it in `fluid/operators/math`:

https://github.com/PaddlePaddle/Paddle/blob/2dae8a46317789fa3ac78cc39ca1b63f8609aef0/paddle/fluid/operators/math/blas.h#L49-L59

Especially that it is called in `fluid/framework/init.cc`:

https://github.com/PaddlePaddle/Paddle/blob/8f266e202236920d1d87ea49bf6b992115928bac/paddle/fluid/framework/init.cc#L118

**Comment by tensor-tang** [comment]
Thanks, I will move it to a proper place.

**Comment by tensor-tang** [comment]
Did not find a proper existing file to place this function. `cpu_info.h` is still not good enough.

So I add new include file named `cpu_helper.h`  .
