### ISSUE TITLE
protobuf与glog一些引用找不到

### ISSUE THREAD

**Issue by gucasbrg** [PaddlePaddle/Paddle#1175]
按 https://github.com/PaddlePaddle/Paddle/blob/develop/doc/getstarted/build_and_install/build_from_source_en.md 安装，出现以下错误：

Done processing test_FPException.cpp
Total errors found: 0
../../gserver/libpaddle_gserver.a(WarpCTCLayer.cpp.o): In function std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >* google::MakeCheckOpString<unsigned long, unsigned long>(unsigned long const&, unsigned long const&, char const*)': /software/Paddle/third_party/install/glog/include/glog/logging.h:689: undefined reference to_ZN6google4base21CheckOpMessageBuilder9NewStringB5cxx11Ev'
../../gserver/libpaddle_gserver.a(ValidationLayer.cpp.o): In function SetNoArena': /software/Paddle/third_party/install/protobuf/include/google/protobuf/arenastring.h:210: undefined reference to_ZN6google8protobuf8internal26fixed_address_empty_stringB5cxx11E'
/software/Paddle/third_party/install/protobuf/include/google/protobuf/arenastring.h:210: undefined reference to _ZN6google8protobuf8internal26fixed_address_empty_stringB5cxx11E' ../../gserver/libpaddle_gserver.a(TransLayer.cpp.o): In functionstd::__cxx11::basic_string<char, std::char_traits, std::allocator >* google::MakeCheckOpString<int, int>(int const&, int const&, char const*)':
/software/Paddle/third_party/install/glog/include/glog/logging.h:689: undefined reference to _ZN6google4base21CheckOpMessageBuilder9NewStringB5cxx11Ev' ../../gserver/libpaddle_gserver.a(SumToOneNormLayer.cpp.o): In functionstd::__cxx11::basic_string<char, std::char_traits, std::allocator >* google::MakeCheckOpString<unsigned long, unsigned int>(unsigned long const&, unsigned int const&, char const*)':
/software/Paddle/third_party/install/glog/include/glog/logging.h:689: undefined reference to _ZN6google4base21CheckOpMessageBuilder9NewStringB5cxx11Ev' ../../gserver/libpaddle_gserver.a(SumToOneNormLayer.cpp.o): In functionstd::__cxx11::basic_string<char, std::char_traits, std::allocator >* google::MakeCheckOpString<float, double>(float const&, double const&, char const*)':
/software/Paddle/third_party/install/glog/include/glog/logging.h:689: undefined reference to _ZN6google4base21CheckOpMessageBuilder9NewStringB5cxx11Ev' ../../gserver/libpaddle_gserver.a(SubSequenceLayer.cpp.o): In functionstd::__cxx11::basic_string<char, std::char_traits, std::allocator >* google::MakeCheckOpString<bool, bool>(bool const&, bool const&, char const*)':
/software/Paddle/third_party/install/glog/include/glog/logging.h:689: undefined reference to _ZN6google4base21CheckOpMessageBuilder9NewStringB5cxx11Ev' ../../gserver/libpaddle_gserver.a(SubSequenceLayer.cpp.o): In functionstd::__cxx11::basic_string<char, std::char_traits, std::allocator >* google::MakeCheckOpString<unsigned int, unsigned long>(unsigned int const&, unsigned long const&, char const*)':
/software/Paddle/third_party/install/glog/include/glog/logging.h:689: undefined reference to _ZN6google4base21CheckOpMessageBuilder9NewStringB5cxx11Ev' ../../gserver/libpaddle_gserver.a(SubSequenceLayer.cpp.o):/software/Paddle/third_party/install/glog/include/glog/logging.h:689: more undefined references to_ZN6google4base21CheckOpMessageBuilder9NewStringB5cxx11Ev' follow
../../gserver/libpaddle_gserver.a(SpatialPyramidPoolLayer.cpp.o): In function SetNoArena': /software/Paddle/third_party/install/protobuf/include/google/protobuf/arenastring.h:210: undefined reference to_ZN6google8protobuf8internal26fixed_address_empty_stringB5cxx11E'
/software/Paddle/third_party/install/protobuf/include/google/protobuf/arenastring.h:210: undefined reference to _ZN6google8protobuf8internal26fixed_address_empty_stringB5cxx11E' ../../gserver/libpaddle_gserver.a(LinearChainCRF.cpp.o): In functionstd::__cxx11::basic_string<char, std::char_traits, std::allocator >* google::MakeCheckOpString<float, int>(float const&, int const&, char const*)':
/software/Paddle/third_party/install/glog/include/glog/logging.h:689: undefined reference to _ZN6google4base21CheckOpMessageBuilder9NewStringB5cxx11Ev' ../../gserver/libpaddle_gserver.a(Layer.cpp.o): In functionstd::__cxx11::basic_string<char, std::char_traits, std::allocator >* google::MakeCheckOpString<std::__cxx11::basic_string<char, std::char_traits, std::allocator >, char [8]>(std::__cxx11::basic_string<char, std::char_traits, std::allocator > const&, char const (&) [8], char const*)':
/software/Paddle/third_party/install/glog/include/glog/logging.h:689: undefined reference to _ZN6google4base21CheckOpMessageBuilder9NewStringB5cxx11Ev' ../../gserver/libpaddle_gserver.a(GetOutputLayer.cpp.o): In functionstd::__cxx11::basic_string<char, std::char_traits, std::allocator >* google::MakeCheckOpString<std::__cxx11::basic_string<char, std::char_traits, std::allocator >, char [1]>(std::__cxx11::basic_string<char, std::char_traits, std::allocator > const&, char const (&) [1], char const*)':
/software/Paddle/third_party/install/glog/include/glog/logging.h:689: undefined reference to _ZN6google4base21CheckOpMessageBuilder9NewStringB5cxx11Ev' ../../gserver/libpaddle_gserver.a(ExpandLayer.cpp.o): In functionstd::__cxx11::basic_string<char, std::char_traits, std::allocator >* google::MakeCheckOpString<bool, unsigned long>(bool const&, unsigned long const&, char const*)':
/software/Paddle/third_party/install/glog/include/glog/logging.h:689: undefined reference to _ZN6google4base21CheckOpMessageBuilder9NewStringB5cxx11Ev' ../../gserver/libpaddle_gserver.a(ExpandLayer.cpp.o): In functionstd::__cxx11::basic_string<char, std::char_traits, std::allocator >* google::MakeCheckOpString<long, long>(long const&, long const&, char const*)':
/software/Paddle/third_party/install/glog/include/glog/logging.h:689: undefined reference to _ZN6google4base21CheckOpMessageBuilder9NewStringB5cxx11Ev' ../../gserver/libpaddle_gserver.a(ConvOperator.cpp.o):/software/Paddle/third_party/install/glog/include/glog/logging.h:689: more undefined references to_ZN6google4base21CheckOpMessageBuilder9NewStringB5cxx11Ev' follow
../../gserver/libpaddle_gserver.a(RecurrentGradientMachine.cpp.o): In function SetNoArena': /software/Paddle/third_party/install/protobuf/include/google/protobuf/arenastring.h:210: undefined reference to_ZN6google8protobuf8internal26fixed_address_empty_stringB5cxx11E'
../../gserver/libpaddle_gserver.a(RecurrentGradientMachine.cpp.o): In function std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >* google::MakeCheckOpString<long, int>(long const&, int const&, char const*)': /software/Paddle/third_party/install/glog/include/glog/logging.h:689: undefined reference to_ZN6google4base21CheckOpMessageBuilder9NewStringB5cxx11Ev'
../../gserver/libpaddle_gserver.a(MultiNetwork.cpp.o): In function std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >* google::MakeCheckOpString<char [5], std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >(char const (&) [5], std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, char const*)': /software/Paddle/third_party/install/glog/include/glog/logging.h:689: undefined reference to_ZN6google4base21CheckOpMessageBuilder9NewStringB5cxx11Ev'
../../gserver/libpaddle_gserver.a(MultiGradientMachine.cpp.o): In function std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >* google::MakeCheckOpString<paddle::enumeration_wrapper::ParameterType, paddle::enumeration_wrapper::ParameterType>(paddle::enumeration_wrapper::ParameterType const&, paddle::enumeration_wrapper::ParameterType const&, char const*)': /software/Paddle/third_party/install/glog/include/glog/logging.h:689: undefined reference to_ZN6google4base21CheckOpMessageBuilder9NewStringB5cxx11Ev'
../../gserver/libpaddle_gserver.a(GradientMachine.cpp.o): In function paddle::GradientMachine::create(std::istream&, paddle::TrainerConfig*)': /software/Paddle/paddle/gserver/gradientmachines/GradientMachine.cpp:95: undefined reference togoogle::protobuf::MessageLite::ParseFromString(std::__cxx11::basic_string<char, std::char_traits, std::allocator > const&)'
../../gserver/libpaddle_gserver.a(PyDataProvider.cpp.o): In function `std::__cxx11::basic_string<char, std::char_traits, std::allocator >* google::MakeCheckOpString<char*, char const*>(char* const&, char const* const&, char const*)':

另外CMakeFiles/openblas.dir/build.make 中
/usr/bin/gmake FC=/usr/bin/gfortran CC=/usr/local/bin/gcc HOSTCC=/usr/local/bin/gcc NO_SHARED=1 BINARY=64 U
SE_THREADS=1 NUM_THREADS=8 TARGET=SANDYBRIDGE libs netlib
如果不加另外的参数，openBLAS貌似也编译不过去

**Comment by gangliao** [comment]
@gucasbrg 请问你用的什么系统, 什么版本

**Comment by gucasbrg** [comment]
CentOS 6.8, gcc5.2

**Comment by gangliao** [comment]
能否帮我确认一下/software/Paddle/third_party/install/glog和/software/Paddle/third_party/install/protobuf是lib还是lib64目录 @gucasbrg

**Comment by gucasbrg** [comment]
@gangliao 
/software/Paddle/third_party/install/glog:lib
/software/Paddle/third_party/install/protobuf:lib64

**Comment by gangliao** [comment]
@gucasbrg  谢谢  我找一个docker centos 6.8试一下

**Comment by reyoung** [comment]
BTW, CentOS 6 为什么是gcc 5.2呢？@gucasbrg 纯粹好奇。。应该还用了repl之类的源吧？

**Comment by gucasbrg** [comment]
@reyoung 因为跑别的框架的缘故，自己重新装的高版本的gcc

**Comment by gucasbrg** [comment]
用scl enable devtoolset-4 -- make DYNAMIC_ARCH=1验证
貌似是版本的问题，caffe也出现过类似的版本不兼容问题
CMakeFiles/test_ThreadBarrier.dir/test_ThreadBarrier.cpp.o：在函数‘std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >* google::MakeCheckOpString<unsigned long, unsigned long>(unsigned long const&, unsigned long const&, char const*)’中：
/home/hotel-revenuetest/ruguo.bu/software/Paddle/third_party/install/glog/include/glog/logging.h:689：对‘google::base::CheckOpMessageBuilder::NewString[abi:cxx11]()’未定义的引用
../../gserver/libpaddle_gserver.a(ValidationLayer.cpp.o)：在函数‘google::protobuf::internal::ArenaStringPtr::SetNoArena(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)’中：
/home/hotel-revenuetest/ruguo.bu/software/Paddle/third_party/install/protobuf/include/google/protobuf/arenastring.h:210：对‘google::protobuf::internal::fixed_address_empty_string[abi:cxx11]’未定义的引用
/home/hotel-revenuetest/ruguo.bu/software/Paddle/third_party/install/protobuf/include/google/protobuf/arenastring.h:210：对‘google::protobuf::internal::fixed_address_empty_string[abi:cxx11]’未定义的引用
../../gserver/libpaddle_gserver.a(TransLayer.cpp.o)：在函数‘std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >* google::MakeCheckOpString<int, int>(int const&, int const&, char const*)’中：
/home/hotel-revenuetest/ruguo.bu/software/Paddle/third_party/install/glog/include/glog/logging.h:689：对‘google::base::CheckOpMessageBuilder::NewString[abi:cxx11]()’未定义的引用
../../gserver/libpaddle_gserver.a(SumToOneNormLayer.cpp.o)：在函数‘std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >* google::MakeCheckOpString<unsigned long, unsigned int>(unsigned long const&, unsigned int const&, char const*)’中：
/home/hotel-revenuetest/ruguo.bu/software/Paddle/third_party/install/glog/include/glog/logging.h:689：对‘google::base::CheckOpMessageBuilder::NewString[abi:cxx11]()’未定义的引用
../../gserver/libpaddle_gserver.a(SumToOneNormLayer.cpp.o)：在函数‘std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >* google::MakeCheckOpString<float, double>(float const&, double const&, char const*)’中：
/home/hotel-revenuetest/ruguo.bu/software/Paddle/third_party/install/glog/include/glog/logging.h:689：对‘google::base::CheckOpMessageBuilder::NewString[abi:cxx11]()’未定义的引用
../../gserver/libpaddle_gserver.a(SubSequenceLayer.cpp.o)：在函数‘std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >* google::MakeCheckOpString<bool, bool>(bool const&, bool const&, char const*)’中：
/home/hotel-revenuetest/ruguo.bu/software/Paddle/third_party/install/glog/include/glog/logging.h:689：对‘google::base::CheckOpMessageBuilder::NewString[abi:cxx11]()’未定义的引用
../../gserver/libpaddle_gserver.a(SubSequenceLayer.cpp.o)：在函数‘std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >* google::MakeCheckOpString<unsigned int, unsigned long>(unsigned int const&, unsigned long const&, char const*)’中：
/home/hotel-revenuetest/ruguo.bu/software/Paddle/third_party/install/glog/include/glog/logging.h:689：对‘google::base::CheckOpMessageBuilder::NewString[abi:cxx11]()’未定义的引用
../../gserver/libpaddle_gserver.a(SubSequenceLayer.cpp.o):/home/hotel-revenuetest/ruguo.bu/software/Paddle/third_party/install/glog/include/glog/logging.h:689: more undefined references to `google::base::CheckOpMessageBuilder::NewString[abi:cxx11]()' follow
../../gserver/libpaddle_gserver.a(SpatialPyramidPoolLayer.cpp.o)：在函数‘google::protobuf::internal::ArenaStringPtr::SetNoArena(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)’中：
/home/hotel-revenuetest/ruguo.bu/software/Paddle/third_party/install/protobuf/include/google/protobuf/arenastring.h:210：对‘google::protobuf::internal::fixed_address_empty_string[abi:cxx11]’未定义的引用
/home/hotel-revenuetest/ruguo.bu/software/Paddle/third_party/install/protobuf/include/google/protobuf/arenastring.h:210：对‘google::protobuf::internal::fixed_address_empty_string[abi:cxx11]’未定义的引用

**Comment by gangliao** [comment]
@gucasbrg 
明白了. 你也可以尝试docker，其支持最新的code

https://github.com/PaddlePaddle/Paddle/blob/develop/doc/getstarted/build_and_install/docker_install_en.rst
