### ISSUE TITLE
cmake download model files for test

### ISSUE THREAD

**Issue by jacquesqiao** [PaddlePaddle/Paddle#11764]
![image](https://user-images.githubusercontent.com/3048612/41960203-bcd79b90-7a21-11e8-828d-93c8cb9616b5.png)

**Comment by Superjomn** [comment]
what's the case?

**Comment by luotao1** [comment]
@Superjomn 应该在单测运行的时候下载这些模型，而不是在编译的时候就下载了。目前python单测，均是在运行的时候下载模型和数据。

**Comment by tensor-tang** [comment]
就是因为这里，在cmake的时候就会执行，下载model。

https://github.com/PaddlePaddle/Paddle/blob/c228977727cfbcd53dbccb4f93153c6102cd7815/paddle/contrib/inference/demo/CMakeLists.txt#L33-L38
