### ISSUE TITLE
Issue while creating EFS

### ISSUE THREAD

**Issue by putcn** [PaddlePaddle/Paddle#1177]
Hi Paddle team, 

great framework first of all! I'm following the k8s aws tutorial these days, but got stuck when try to create EFS. (Setup PaddlePaddle Environment on AWS)
As instructed in the tutorial, we need to associate EFS with the VPC created by k8s. but in my case, EFS is not available in the region created with VPC(us-west-1, NCal), it's only available in us-west-2, Oregon, and some other regions. so it's not possible for me to create EFS associated with k8s VPS. not sure if this is only my account or generally not available to create anymore EFS in NCal.
I tried to migrate k8s cluster to other region where EFS and VPS are both available, however the tutorial mentioned that 
```
Subnets can currently only be created in the following availability zones: us-west-1b, us-west-1a.
```
so migrating seems not possible. 
can anyone help?

thx!

**Comment by helinwang** [comment]
Thank you! This issue is resolved. Please refer to most updated [document](https://github.com/PaddlePaddle/Paddle/blob/develop/doc/howto/usage/k8s/k8s_aws_en.md)
