### ISSUE TITLE
Cls instance has no attribute 'pool_size'

### ISSUE THREAD

**Issue by cbstyle** [PaddlePaddle/Paddle#11775]
TrainData(PyData(
        files="train.list",
        load_data_module="video_mean_provider",
        load_data_object = "processData",
        load_data_args = load_data_args,
        async_load_data = True)
)
 
TestData(PyData(
        files="test.list",
        load_data_module="video_mean_provider",
        load_data_object = "processData",
        load_data_args = load_data_args)
)
数据输入由上面替换为下面，则报错了，啥原因？
define_py_data_sources2(
    train_list = 'train.list',
    test_list = 'test.list',
    module = 'video_mean_provider',
    obj = 'processData')
报错信息：
Cls instance has no attribute 'pool_size'

**Comment by Yancey0623** [comment]
请问在什么环境下，安装的哪个版本的Paddle呢？

**Comment by chengduoZH** [comment]
Close this inactive issue, please feel free to reopen if you need further discuss.
