### ISSUE TITLE
调用paddle_gradient_machine_create_for_inference报错

### ISSUE THREAD

**Issue by Angus07** [PaddlePaddle/Paddle#11774]
C++AIP, 报错信息如下：
```
*** Aborted at 1530081800 (unix time) try "date -d @1530081800" if you are using GNU date ***
PC: @                0x0 (unknown)
*** SIGSEGV (@0xffffffffc7dd2820) received by PID 13001 (TID 0x7f9419c74840) from PID 18446744072767744032; stack trace: ***
    @     0x7f9419852160 (unknown)
    @     0x7f94060f1121 paddle::ModelConfig::MergePartialFromCodedStream()
    @     0x7f94060f80e8 google::protobuf::MessageLite::ParseFromArray()
    @     0x7f9405d667c3 paddle_gradient_machine_create_for_inference
    @           0x710885 du::tagger::TopicTaggerDict::init()
    @           0x634d3e du::tagger::StaticDict::load_topic_tagger_dict()
    @           0x637a8b du::tagger::StaticDict::init_static_dict()
    @           0x63ba6d du::tagger::DocTagger::load_static_resource()
    @           0x6402d2 du::tagger::DocTagger::init_global()
    @           0x61da53 main
    @     0x7f9405156bd5 __libc_start_main
    @           0x6248b9 (unknown)
    @                0x0 (unknown)
```

已经检查过，读入的BIN_FILE的文件是正常的，也读到了。
代码如下：
```
value = options.get_option("l1_bin_file");
    if (value != NULL) {
        string model_bin_file_path = options.get_full_path(*value);
        _paddle_model_buf_l1 = paddle_read_config(
                model_bin_file_path.c_str(), &_paddle_model_size_l1);
        paddle_gradient_machine_create_for_inference(&_classifier_machine_l1,
        _paddle_model_buf_l1, (int) _paddle_model_size_l1);
....
}
```

**Comment by typhoonzero** [comment]
是否可以提供使用的paddle的版本或者github commit id呢？

**Comment by Angus07** [comment]
CONFIGS('baidu/third-party/paddle-capi@paddle-capi-cpu-v0.2@git_tag',NeedOutput())

**Comment by typhoonzero** [comment]
这个版本对应哪个github的commit id呢，这样我可以clone一份代码来debug

**Comment by Angus07** [comment]
你是说我们的代码吗？还是paddle的代码？

**Comment by typhoonzero** [comment]
是说paddle的代码

**Comment by Angus07** [comment]
你是说这个 http://icode.baidu.com/repos/baidu/third-party/paddle-capi/tree/master ?

**Comment by typhoonzero** [comment]
看了下这个项目里是直接link到一个ci上的build id了，并没有记录到底是对应github哪个commit id，所以无法用当时版本的代码复现。

另一个方法是，你可以先下载最新的paddle capi的so，替换项目中thirdparty下的内容，看可否复现，如果仍然可以我可以用最新的代码检查下问题

**Comment by shanyi15** [comment]
您好，此issue在近一个月内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题，我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持! 
 Hello, this issue has not been updated in the past month. We will close it today for the sake of other user‘s experience. If you still need to follow up on this question after closing, please feel free to reopen it. In that case, we will get back to you within 24 hours. We apologize for the inconvenience caused by the closure and thank you so much for your support of PaddlePaddle Group!
