### ISSUE TITLE
paddle.layer.img_conv的padding以及输出的h,w是怎么计算的

### ISSUE THREAD

**Issue by chenbblei** [PaddlePaddle/Paddle#11773]
假设定义一个变量
conv_layer = paddle.layer.img_conv(
        input=input,
        filter_size=(11,41),
        num_channels=1,
        num_filters=16,
        stride=(3,2),
        padding=padding,
        act=paddle.activation.Linear(),
        bias_attr=False)

假设input定义如下：
input= paddle.layer.data(
            name="input",
            type=paddle.data_type.dense_array(300* 161))

那么padding如何计算获得，这个img_conv的输出height和width分别为多少，
自己也计算过，有些疑问，所以问这个问题，请帮忙写下计算过程，好让自己确认自己的理解是否正确，谢谢，假设使用SAME形式

**Comment by Yancey0623** [comment]
Dup with #11148

**Comment by chengduoZH** [comment]
close this duplicate issue.
