### ISSUE TITLE
DNN可以同时运行在GPU和CPU

### ISSUE THREAD

**Issue by liangyz23** [PaddlePaddle/Paddle#11796]
https://github.com/PaddlePaddle/book/issues/281  里面提到整体网络使用GPU的时候，可以部分layer用CPU，但我没找到相应的设置方式，想请教下怎么设置，谢谢！
原话“PaddlePaddle allows a certain layer or some layers runs in CPU while the rest running in GPU”

**Comment by luotao1** [comment]
您好，v2版本未支持这一功能，v1版本是支持的。

**Comment by liangyz23** [comment]
不好意思，怎么区分哪些版本是V1，哪些是V2

**Comment by xiaolv3366** [comment]
为什么v2版本不支持这一功能？这个功能很实用的。

**Comment by luotao1** [comment]
- v1版本是0.9.0的，比较老的，0.10.0开始是v2版本。
- v2版本目前已经不加新的功能，维护为主。
- fluid版本是支持这一功能的，会在run的时候，自动进行CPU/GPU的转换，您可以试下fluid版本。在fluid版本中，如果的有的op没有GPU的kernel 而且该op的输入是在GPU的，  在Op里面会将数据拷贝到CPU端，这个过程不需要用户参与的

**Comment by liangyz23** [comment]
好的，谢谢！
