### ISSUE TITLE
Installing the latest version of Paddle(GPU) is failed

### ISSUE THREAD

**Issue by callmeivy** [PaddlePaddle/Paddle#11798]
downloaded the latest version of paddle wheel(cuda9.0_cudnn7_avx_mkl) from https://guest@paddleci.ngrok.io/repository/download/Manylinux1_Cuda90cudnn7avxMkl/.lastSuccessful/paddlepaddle_gpu-latest-cp27-cp27mu-linux_x86_64.whl

when I install it with "pip install XX.whl", it comes the error of "error: Error -3 while decompressing: invalid code lengths set", pls see the detailed screen shot below:
![default](https://user-images.githubusercontent.com/14139827/42011520-53c37354-7ac6-11e8-954f-f650f4409899.png)

ps. my system is Ubuntu 16.04 LTS with cuda9.0+cudnn7.0

anyone can give any advice, pls?

**Comment by luotao1** [comment]
我们的TeamCity正在重启，等恢复正常后通知您。

**Comment by luotao1** [comment]
@callmeivy TeamCity已经恢复正常，请重新下载即可。

**Comment by callmeivy** [comment]
@luotao1 谢谢。

**Comment by ktlichkid** [comment]
Closed due to low activity. Please feel free to reopen it.
