### ISSUE TITLE
Paddle 自带单元测试挂掉

### ISSUE THREAD

**Issue by BryceLuminary** [PaddlePaddle/Paddle#11795]
您好，我运行 Paddle python 接口的单元测试时，CUDAPlace(0) 有些重要的 op 会挂掉，例如 test_conv2d_op.py。因为卷积层是重要的 op，这个单元测试不能通过会导致几乎所有 CNN 类网络运行失败；改为 CPUPlace 就可以了。运行失败的提示信息如下：

> $ python test_conv2d_op.py
> *** Aborted at 1530115834 (unix time) try "date -d @1530115834" if you are using GNU date ***
> PC: @                0x0 (unknown)
> *** SIGSEGV (@0x0) received by PID 5332 (TID 0x7fda64108700) from PID 0; stack trace: ***
>     @     0x7fda63936520 (unknown)
>     @                0x0 (unknown)
> Segmentation fault (core dumped)`

我的系统环境是两张 P4，两张 K1200 混插在同一台机器上了，所以这个故障怀疑牵扯到单机多卡的 nccl 通信问题。请帮忙定位，谢谢！

**Comment by luotao1** [comment]
您好，运行单测，请按照以下命令：
```
cd build
make test ARGS='-R test_conv2d_op -V'
```
直接运行python文件，会导致一些环境变量没找到。
