### ISSUE TITLE
请看看下面的错误是什么原因？

### ISSUE THREAD

**Issue by Leezhaohui** [PaddlePaddle/Paddle#11820]
![2018-06-29 09-39-33](https://user-images.githubusercontent.com/37324697/42068911-3d40102c-7b81-11e8-8de8-25c7c7a1c0d1.png)

**Comment by typhoonzero** [comment]
应该是显存不够了，请检查是否有别的程序正在占用GPU

**Comment by Leezhaohui** [comment]
![2018-06-29 10-13-30](https://user-images.githubusercontent.com/37324697/42069567-1ecddf62-7b85-11e8-9453-6c09f1331374.png)
@typhoonzero 那这个错误呢？

**Comment by typhoonzero** [comment]
您好，类似这样的错误，Paddle的错误提示应该是准确并充分的，基本上可以通过报错信息和stack定位问题。比如第一个报错"enforce allocating <= available failed"是说内存分配失败。第二个问题 "Broadcast dimension mismatch" 是说两个tensor的dimension不一致，并且是在某个elementwise_op中，这样可以通过进一步的查看stack信息，定位到具体是那个op出错的，并检查模型配置中是否存在shape不一致的问题。

这是一般定位以及解决问题的方法，希望您能掌握通用的方法，这样在后续的模型开发中可以事半功倍。

另外，推荐在提交issue的时候，不要截图，而是将报错的文本用code-block贴起来。这样类似的问题也可以在github issue中或从搜索引擎中搜到，如果有相似的问题，为其他开发者和社区提供帮助。

谢谢！
