### ISSUE TITLE
learning rate calculating use adagrad algorithm

### ISSUE THREAD

**Issue by PseudoProgrammer** [PaddlePaddle/Paddle#1182]
how to calculate the  learning rate in  first pass use adagrad algorithm?In first pass, the penalty item is gt, i ,and the  gradient be gt,i too,so learning rate for all paramters is the same-base learning rate?
Can you tell me?@yuyang

**Comment by PseudoProgrammer** [comment]
Anyone can answer my question?

**Comment by PseudoProgrammer** [comment]
wiki里的adagrad公式是，
![image](https://cloud.githubusercontent.com/assets/9998763/22096559/3ce5c2ca-de57-11e6-9313-a28a6c53cc4d.png)

那么当t=1的时候，Xt+1,i=Xt,i - eta，不论i为何值。所以所有特征的梯度都变成了1？

**Comment by reyoung** [comment]
1、这里一个t不是一个pass，而是一个mini-batch
2、一般实现的时候，会在分母加一个epsilon。所以，一般实现的时候，第一步的修正后的Gradient就会变得特别大。这个没问题。

**Comment by PseudoProgrammer** [comment]
所以在paddle中的pass0，也就是第一轮优化的时候，所有特征的梯度都是1，学习步长就是eta吗？

**Comment by reyoung** [comment]
t不是一个pass，而是一个mini-batch

**Comment by PseudoProgrammer** [comment]
不太清楚paddle的pass和mini-batch的关系，可否给个wiki或者解释下

**Comment by PseudoProgrammer** [comment]
@reyoung 看了下，如果按照下面的参数解释，m个样本，mini-batch是b个样本，简写不考虑epsilon，那么t=1,用的样本是1,...,b，各个特征权重的学习步长都是一样的，eta*1，且都特别大
X2,1=X1,1-eta*1                  
X2,2=X1,2-eta*1
t=2，用的样本是b+1,.....,b+b，各个特征权重的学习步长不一样了
X3,1=X2,1-eta*g2,1/sqrt(g1,1*g1,1+g2,1*g2,1)
X3,2=X2,2-eta*g2,2/sqrt(g1,2*g1,2+g2,2*g2,2)


![image](https://cloud.githubusercontent.com/assets/9998763/22097135/76abd136-de5a-11e6-9786-bb045f8a25dc.png)

**Comment by reyoung** [comment]
> 不太清楚paddle的pass和mini-batch的关系，可否给个wiki或者解释下

Paddle的Pass类似于其他框架里面epoch的概念，即训练完所有数据。mini-batch就和普通的mini-batch思路一样。

如果是想要学习深度学习的基础知识，请关注其他文档，例如 https://github.com/PaddlePaddle/book 。而不是提issue。
