### ISSUE TITLE
用cmake ExternalProject_Add 组织的模块能否在总项目编译节点选择关闭编译，比如warpCTC模块

### ISSUE THREAD

**Issue by backyes** [PaddlePaddle/Paddle#1183]
这次编译机制改动较大，在内部生产环境下编译遇到若干问题，手动排除若干后，最后仍然未能解决。 这里反馈几个细节，以及几个疑问： 

*  当前编译基本要求编译机能连internet，否则编译相对困难很多。（这个问题还好解决）
*  依赖库采用thirdparty方式，其编译过程不受Paddle顶层对编译选项的控制，而是依赖具体子模块的编译。比如出现了 
```
/home/wangyanfei/paddle_internal_release_tools_dev_momentum_tips/idl/paddle/Paddle/third_party/install/protobuf/bin/protoc: /lib64/libc.so.6: version `GLIBC_2.14' not found
```
的编译问题，根本原因是系统默认编译器版本低，且同时使用了安装了高版本编译器，这种非标准方式thirdparty的cmake系统并未处理这种情况。个人觉得，C++这种底层语言对编译环境依赖相对大，因此这种孤立的thirdparty编译方法可能要小心仔细一点，避免出现更多编译未定义问题。

此外，尝试在mac系统上编译，也出现warpCTC要求高版本编译器
```
baidudeMacBook-Pro:build baidu$ make
[  3%] Built target gflags
[  5%] Built target glog
[  8%] Built target gtest
[ 11%] Built target zlib
[ 13%] Built target protobuf
[ 14%] Performing configure step for 'warpctc'
CMake Error at /Users/baidu/work/Paddle/third_party/warpctc/src/warpctc-stamp/warpctc-configure.cmake:16 (message):
  Command failed: 1

   '/usr/local/Cellar/cmake/3.2.3/bin/cmake' '-DCMAKE_CXX_COMPILER=/Library/Developer/CommandLineTools/usr/bin/c++' '-DCMAKE_C_COMPILER=/Library/Developer/CommandLineTools/usr/bin/cc' '-DCMAKE_INSTALL_PREFIX=/Users/baidu/work/Paddle/third_party/install/warpctc' '-DWITH_GPU=OFF' '-DWITH_OMP=OFF' '-DWITH_TORCH=OFF' '-DBUILD_SHARED=ON' '-GUnix Makefiles' '/Users/baidu/work/Paddle/third_party/warpctc/src/warpctc'

  See also

    /Users/baidu/work/Paddle/third_party/warpctc/src/warpctc-stamp/warpctc-configure-*.log


make[2]: *** [../third_party/warpctc/src/warpctc-stamp/warpctc-configure] Error 1
make[1]: *** [CMakeFiles/warpctc.dir/all] Error 2
make: *** [all] Error 2
baidudeMacBook-Pro:build baidu$
```
具体错误： 
```
    1 CMake Error at CMakeLists.txt:2 (cmake_minimum_required):
    2   CMake 3.4 or higher is required.  You are running version 3.2.3

```
一般生产环境可能为了规避风险，不会使用高版本系统发行版，所以默认自带的工具相对低端， 所以此处对cmake高版本的要求，可能也给内部用户带来困扰。 

但是，上述所有问题，在docker发行下，应该都不会踩到这些坑。 此处，仅做mark。

**Comment by backyes** [comment]
另外， 不知道能cmake能否在顶层控制ExternalProject_Add控制的模块的编译，比如关闭warpCTC编译？ @gangliao

**Comment by backyes** [comment]
```
ebaidudeMacBook-Pro:build baidu$ brew uninstall cmake
Uninstalling /usr/local/Cellar/cmake/3.2.3... (1850 files, 32M)
baidudeMacBook-Pro:build baidu$
```
重新编译一个高版本cmake，解决问题。

**Comment by gangliao** [comment]
可以增加一个feature, 默认先检测系统是否存在依赖，有的话，就不需要下载编译。

Paddle会自动下载第三方依赖的源码，然后根据其编译文件，进行configure, build, install.
可以通过传入类似编译器环境变量 CMAKE_ARGS      -DCMAKE_CXX_COMPILER=${CMAKE_CXX_COMPILER} 来控制来解决Protobuf的编译器版本问题。

比如：

```cmake
ExternalProject_Add(
    warpctc
    ${EXTERNAL_PROJECT_LOG_ARGS}
    GIT_REPOSITORY  "https://github.com/gangliao/warp-ctc.git"
    PREFIX          ${WARPCTC_SOURCES_DIR}
    UPDATE_COMMAND  ""
    CMAKE_ARGS      -DCMAKE_CXX_COMPILER=${CMAKE_CXX_COMPILER}
    CMAKE_ARGS      -DCMAKE_C_COMPILER=${CMAKE_C_COMPILER}
    CMAKE_ARGS      -DCMAKE_INSTALL_PREFIX=${WARPCTC_INSTALL_DIR}
    CMAKE_ARGS      -DWITH_GPU=${WITH_GPU}
    CMAKE_ARGS      -DWITH_OMP=${USE_OMP}
    CMAKE_ARGS      -DWITH_TORCH=OFF
    CMAKE_ARGS      -DBUILD_SHARED=ON
```

这种源码级依赖进行编译，存在一个问题是，其编译有自身的限制，比如warpctc要求linux cmake 2.8， mac则需要cmake3.4 (但我们内部不存在这个问题，如果有需要改低，我倒是可以给他们提个PR) @backyes 。

我在内部多台机器上测试过， 目前应该只需要：
```
jumbo install gcc48 设置为默认编译器
jumbo install python27 安装python2.7以及一些python包：numpy, wheel, pip, protobuf >= 3.0
cmake .. && make
```


warpctc目前编译和之前的编译并没有什么区别，只是把submodule换成了cmake自身的externproject_add.

**Comment by backyes** [comment]
```
jumbo install gcc48 设置为默认编译器

```
应该还会有些问题。 这种做法单机可能奏效，但是在集群环境，可能因为运行时环境问题会导致兼容问题。 目前集群和单机统统使用一个特定的编译器，其应该采用了rpath方法来解决线上gcc版本问题。 这个 @reyoung  也很熟悉。

> warpctc目前编译和之前的编译并没有什么区别，只是把submodule换成了cmake自身的externproject_add.
 
嗯。 现在这种方法应该默认都必须编译warpCTC，即便没有使用。

如果全部采用static产出，应该能解决所有问题了，就是不知道会不会有坑，否则最好能兼容现有的模式。

**Comment by backyes** [comment]
> 可以增加一个feature, 默认先检测系统是否存在依赖，有的话，就不需要下载编译。  

我觉得，这种feature外围脚本支持就行了， paddle核心编译系统不必要做这么多的适配，否则可能会增加维护难度。

**Comment by gangliao** [comment]
我也是这么觉得的  目前除了warpctc, 其他应该都是静态库的方式， 之后应该能解决很多问题。

**Comment by backyes** [comment]
@gangliao 

> 其他应该都是静态库的方式， 之后应该能解决很多问题。 

对于某些生产环境整个运行时工具链都非常低的情况下，高版本编译出来的static库会不会存在加载问题，有必要验证一下（如果考虑static部署的话）。
