### ISSUE TITLE
Predicted Housing Price is NEGATIVE

### ISSUE THREAD

**Issue by daming-lu** [PaddlePaddle/Paddle#11856]
After training, when we use real Boston Housing Price to do prediction, Paddle gives negative housing price

https://github.com/daming-lu/Paddle/blob/911567b276844ecc18e5864eaa4c0761af7465c4/python/paddle/fluid/tests/book/high-level-api/fit_a_line/book_fit_a_line.py#L84

The data is here:

https://archive.ics.uci.edu/ml/machine-learning-databases/housing/housing.data

**Comment by luotao1** [comment]
As [`trainer.train`](https://github.com/daming-lu/Paddle/blob/911567b276844ecc18e5864eaa4c0761af7465c4/python/paddle/fluid/tests/book/high-level-api/fit_a_line/book_fit_a_line.py#L66) is V2 inferface, could it be used in fluid demo? Why not use `python/paddle/fluid/tests/book/high-level-api/fit_a_line/test_fit_a_line.py`?

**Comment by luotao1** [comment]
I print the train loss
```
[luotao02@yq01-idl-gpu-jpaas-let01: Paddle] daming-lu-develop -> $ python python/paddle/fluid/tests/book/high-level-api/fit_a_line/book_fit_a_line.py
['275.66712951660156']
['237.9882723490397']
['239.83605448404947']
['235.4544194539388']
['218.99579366048178']
['234.24365997314453']
['201.47886403401694']
['227.6452865600586']
['200.10565948486328']
['195.2815793355306']
['193.22032165527344']
['193.18475850423178']
['207.57064819335938']
['183.79825083414713']
...
['15.914986769358316']
['17.338773886362713']
['18.464251200358074']
['18.860468069712322']
['16.344685395558674']
['14.922477841377258']
['16.406979084014893']
('infer results: ', array([[-459.6747],
       [-401.6311]], dtype=float32))
```
It seems that the train loss is normal, but the infer result is error.
Maybe you can check whether the inference_program is the inference of trainer_program.
