### ISSUE TITLE
Cannot find ctc.h

### ISSUE THREAD

**Issue by lzhao4ever** [PaddlePaddle/Paddle#1186]
when I run make, I got the following message:

```
../paddle/cuda/include/hl_warpctc_wrap.h:18:17: fatal error: ctc.h: No such file or directory
 #include "ctc.h"
```

**Comment by wangkuiyi** [comment]
I think this could be because @gangliao recently removed the Git submodule in https://github.com/PaddlePaddle/Paddle/pull/1093.  Let me confirm.  If so, we just need to re-run `cmake`.

**Comment by gangliao** [comment]
@lzhao4ever Do you build the latest source code from the develop branch?

**Comment by jacquesqiao** [comment]
maybe you should run `git submodule update --recursive`

**Comment by lzhao4ever** [comment]
Yes, I built the latest source code from the develop branch and I ran git submodule update --recursive. I still got the same error. The older version has wrap-ctc, but the new version does not have this directory.

**Comment by gangliao** [comment]
Do you have Paddle/third_party/install/warpctc dir? @lzhao4ever

**Comment by lzhao4ever** [comment]
I have Paddle/third_party/warpctc

**Comment by gangliao** [comment]
If you have Paddle/third_party/install/warpctc/include/ctc.h, it's impossible that `ctc.h` cannot be found

**Comment by lzhao4ever** [comment]
No, I do not have Paddle/third_party/install/warpctc/include/ctc.h. There is only src in Paddle/third_party/warpctc.

**Comment by gangliao** [comment]
Can you simply `rm -rf Paddle/third_party` and `cd build && cmake .. && make`  again?
@lzhao4ever 
Because here already included download, build and install steps for warpctc, `third_party/install/warpctc` should exist. 
https://github.com/PaddlePaddle/Paddle/blob/develop/cmake/external/warpctc.cmake#L46

**Comment by lzhao4ever** [comment]
I clone, build and install warpctc manually. It works now. Thanks.

**Comment by F0REacH** [comment]
I've had same problem. Looks like warp-ctc installs to `${Torch_DIR}` instead of `third_party/install/warpctc` if there is `torch` distro in the system

**Comment by wangkuiyi** [comment]
Thanks for the hints from @F0REacH . @gangliao should we confirm and fix it?

**Comment by F0REacH** [comment]
@wangkuiyi @gangliao I've created PR #1205 to address this issue

**Comment by gangliao** [comment]
@wangkuiyi  @FOREacH wow, Thank you for pointing out the error. I will check it now!
