### ISSUE TITLE
MPI集群版本如何获取中间层输出

### ISSUE THREAD

**Issue by zoopt** [PaddlePaddle/Paddle#11879]
【问题1】本地使用0.12.0版本，使用教程中https://github.com/PaddlePaddle/Paddle/blob/c3162fd7932d508ec2cf1e4d95a9502e29ed7a00/doc/v2/faq/local/index_en.rst#id16 获取中间层输出，如图所示：
![4b86d96edec7150a2b4ecbe5bbd14cf9](https://user-images.githubusercontent.com/4601083/42155289-9255aac2-7e1a-11e8-8855-2a34e967c23a.png)

上到MPI集群版本后，receiver模式，提示出现如下错误：
![d3b8c950f596e823934081c6d1e2d95a](https://user-images.githubusercontent.com/4601083/42155336-b5bb03d6-7e1a-11e8-99fd-b18bfb5558fe.png)

【问题2】我之前也为了适配版本不一致，将损失函数做了更改，如图所示
![image](https://user-images.githubusercontent.com/4601083/42155532-36d271ca-7e1b-11e8-9eb1-fe02cae02c43.png)

【期望回答】
① 辛苦看看问题1如何解决，问题2做法是否正确；
② MPI集群receiver模式 版本有更新计划吗，我怎么知道这个版本和其他版本的diff呢？或者我自己上传客户端

**Comment by gongweibao** [comment]
1. 估计是receiver上的paddle版本太老了。
2. receiver已经不更新了，你可以迁移到paddlecloud.
   有个自己打包上传到receiver的办法。私聊给你。

部署起来有点复杂，你直接迁paddlecloud如何？有一个组的人在维护。
