### ISSUE TITLE
train因Deadline Exceeded连不上ps会core dump，程序应该平稳退出

### ISSUE THREAD

**Issue by kolinwei** [PaddlePaddle/Paddle#11880]
End pass 4, train_loss 2.88446474075, train_acc1 0.378594011068, train_acc5 0.633796095848, test_loss 2.4196540374, test_acc1 0.44827724359, test_acc5 0.70953525641
F0628 11:17:58.649018   220 grpc_client.cc:248] var: name:[batch_norm_22.w_0] ep:[192.168.16.34:5002] grpc error:Deadline Exceeded
*** Check failure stack trace: ***
    @     0x7f1a1031d07d  google::LogMessage::Fail()
    @     0x7f1a10320b2c  google::LogMessage::SendToLog()
    @     0x7f1a1031cba3  google::LogMessage::Flush()
    @     0x7f1a1032203e  google::LogMessageFatal::~LogMessageFatal()
    @     0x7f1a100d0db0  paddle::operators::distributed::GRPCClient::Proceed()
    @     0x7f1a21fafc80  (unknown)
    @     0x7f1a6312f6ba  start_thread
    @     0x7f1a62e6541d  clone
    @              (nil)  (unknown)
Aborted (core dumped)
程序应该平稳退出

**Comment by kolinwei** [comment]
问题还会出现

**Comment by Yancey0623** [comment]
@kolinwei 还是一样的日志么？

**Comment by Yancey0623** [comment]
之前的fix是RPC的超时还会主动报错并退出，但不会有core dump了，也就是不会有
``` text
Aborted (core dumped)
```

这行日志以及程序执行目录下的`core.xxx`文件。
