### ISSUE TITLE
Cmake error on JETSON TX2 WITH CUDA9.0 CUDNN7 for C-API

### ISSUE THREAD

**Issue by zhizunbao-m** [PaddlePaddle/Paddle#11884]
nvcc fatal   : Unknown option 'Wall'
CMake Error at cuda_compile_generated_CropOpGpu.cu.o.cmake:203 (message):
  Error generating
  /home/nvidia/Paddle-develop/release/paddle/function/CMakeFiles/cuda_compile.dir//./cuda_compile_generated_CropOpGpu.cu.o

paddle/function/CMakeFiles/paddle_function.dir/build.make:70: recipe for target 'paddle/function/CMakeFiles/cuda_compile.dir/cuda_compile_generated_CropOpGpu.cu.o' failed
make[2]: *** [paddle/function/CMakeFiles/cuda_compile.dir/cuda_compile_generated_CropOpGpu.cu.o] Error 1
[ 29%] Building CXX object paddle/optimizer/CMakeFiles/paddle_optimizer.dir/adam_optimizer.cc.o
nvcc fatal   : Unknown option 'Wall'
CMake Error at cuda_compile_generated_MulOpGpu.cu.o.cmake:203 (message):
  Error generating
  /home/nvidia/Paddle-develop/release/paddle/function/CMakeFiles/cuda_compile.dir//./cuda_compile_generated_MulOpGpu.cu.o

paddle/function/CMakeFiles/paddle_function.dir/build.make:63: recipe for target 'paddle/function/CMakeFiles/cuda_compile.dir/cuda_compile_generated_MulOpGpu.cu.o' failed
make[2]: *** [paddle/function/CMakeFiles/cuda_compile.dir/cuda_compile_generated_MulOpGpu.cu.o] Error 1
CMakeFiles/Makefile2:1405: recipe for target 'paddle/function/CMakeFiles/paddle_function.dir/all' failed
make[1]: *** [paddle/function/CMakeFiles/paddle_function.dir/all] Error 2
[ 30%] Building CXX object paddle/optimizer/CMakeFiles/paddle_optimizer.dir/optimizer.cc.o
[ 30%] Building CXX object paddle/trainer/CMakeFiles/paddle_trainer_lib.dir/ParameterUpdater.cpp.o
[ 31%] Building CXX object paddle/parameter/CMakeFiles/paddle_parameter.dir/AverageOptimizer.cpp.o
nvcc fatal   : Unknown option 'Wall'
CMake Error at paddle_math_generated_BaseMatrix.cu.o.cmake:203 (message):
  Error generating
  /home/nvidia/Paddle-develop/release/paddle/math/CMakeFiles/paddle_math.dir//./paddle_math_generated_BaseMatrix.cu.o

paddle/math/CMakeFiles/paddle_math.dir/build.make:63: recipe for target 'paddle/math/CMakeFiles/paddle_math.dir/paddle_math_generated_BaseMatrix.cu.o' failed
make[2]: *** [paddle/math/CMakeFiles/paddle_math.dir/paddle_math_generated_BaseMatrix.cu.o] Error 1
CMakeFiles/Makefile2:1535: recipe for target 'paddle/math/CMakeFiles/paddle_math.dir/all' failed
make[1]: *** [paddle/math/CMakeFiles/paddle_math.dir/all] Error 2

**Comment by zhizunbao-m** [comment]
use version release/0.14.0  and gcc-4.8 & g++-4.8 for CAPI

**Comment by panyx0718** [comment]
Supporting TX2 for external users is ongoing.
If you are internal users, can you contact us now?

**Comment by hellodhd** [comment]
same error

**Comment by yxnal** [comment]
> Supporting TX2 for external users is ongoing.
> If you are internal users, can you contact us now?

I am an internal user, how to contact you？
