### ISSUE TITLE
【Exception】预测时，forwardTest出现Check failed: posix_memalign(&ptr, 32ul, size) == 0 (12 vs. 0)

### ISSUE THREAD

**Issue by pkuyym** [PaddlePaddle/Paddle#1188]
通过API预测时，执行到forwardTest，出现异常，详细信息如下：

> F0119 11:17:07.250107 32218 Allocator.h:51] Check failed: posix_memalign(&ptr, 32ul, size) == 0 (12 vs. 0)
> *** Check failure stack trace: ***
>     @     0x7f30b3ef1e34  google::LogMessage::Fail()
>     @     0x7f30b3ef1d8c  google::LogMessage::SendToLog()
>     @     0x7f30b3ef1821  google::LogMessage::Flush()
>     @     0x7f30b3ef45e2  google::LogMessageFatal::~LogMessageFatal()
>     @     0x7f30b3de9b95  paddle::CpuAllocator::alloc()
>     @     0x7f30b3df5def  paddle::PoolAllocator::alloc()
>     @     0x7f30b3db2066  paddle::CpuMemoryHandle::CpuMemoryHandle()
>     @     0x7f30b3dbeb87  paddle::CpuMatrix::CpuMatrix()
>     @     0x7f30b3dbede6  paddle::Matrix::create()
>     @     0x7f30b3dd0011  paddle::Matrix::resizeOrCreate()
>     @     0x7f30b3bc09d7  paddle::Layer::resetSpecifyOutput()
>     @     0x7f30b3bc0b81  paddle::Layer::reserveOutput()
>     @     0x7f30b3c096cb  paddle::FullyConnectedLayer::forward()
>     @     0x7f30b3cddcb0  paddle::NeuralNetwork::forward()
>     @     0x7f30b3b68376  _wrap_GradientMachine_forward
>     @           0x4b4cb9  PyEval_EvalFrameEx
>     @           0x4b6b28  PyEval_EvalCodeEx
>     @           0x4b5d10  PyEval_EvalFrameEx
>     @           0x4b6b28  PyEval_EvalCodeEx
>     @           0x4b5d10  PyEval_EvalFrameEx
>     @           0x4b5fb8  PyEval_EvalFrameEx
>     @           0x4b6b28  PyEval_EvalCodeEx
>     @           0x4b6c52  PyEval_EvalCode
>     @           0x4e1c7d  PyRun_FileExFlags
>     @           0x4e3501  PyRun_SimpleFileExFlags
>     @           0x4159dd  Py_Main
>     @     0x7f30bcdbabd5  __libc_start_main
>     @           0x414b71  (unknown)

**Comment by pkuyym** [comment]
使用API进行预测，好像有问题，那么有没有其他方式呢？
以及cluster版本的，如何进行预测？

**Comment by helinwang** [comment]
@pkuyym log里面的`Check failed: posix_memalign(&ptr, 32ul, size) == 0 (12 vs. 0)`确实表明你说的预测样本过大。因为这里`posix_memalign(...)`的返回值是12，对应着
```
#define ENOMEM          12      /* Out of memory */
```

一般要是碰到申请memory失败，程序直接崩溃是正常的。因为实在没有办法继续下去了。像你说的，只能减少预测样本条数，或者增加电脑的memory。

你提到的`以及cluster版本的，如何进行预测？`，我没有看懂，能否详细解释一下？
