### ISSUE TITLE
from mxnet to paddle and load model error

### ISSUE THREAD

**Issue by nkqiqi** [PaddlePaddle/Paddle#11886]
mxnet转成paddle模型后加载时提示BadCastException错误：what() from PSt3mapI... to St3mapISsS， 请问是什么问题？
![image](https://user-images.githubusercontent.com/34327019/42164351-5cbc0ff0-7e38-11e8-82a4-2bbc20e43af7.png)

**Comment by Superjomn** [comment]
这是啥工具转的？ 官方没有专门的支持吧。
