### ISSUE TITLE
【Question】关于训练和预测的若干问题

### ISSUE THREAD

**Issue by pkuyym** [PaddlePaddle/Paddle#1189]
1. demo里面有单机版通过swig api进行预测的样例，请问cluster版本如何实施预测
2. 运行simple_gru2时，当minibatch的size设置较大时（减小size可以避免出现），出现如下信息，然后程序异常退出

信息如下（训练过程变得非常慢）：
> I0119 10:18:58.880401 27190 Stat.h:221] Stat: [BpBiasTimer] __fc_layer_0__ [Span:22465ms117us] 
> I0119 10:19:16.421510 27190 Stat.h:221] Stat: [BackwardTimer] __fc_layer_0__ [Span:44247ms219us] 

退出时的异常信息如下：
> 
> Thu Jan 19 10:22:40 2017[1,6]<stderr>:    @     0x7f87586fa160 (unknown)
> Thu Jan 19 10:22:40 2017[1,6]<stderr>:    @           0xe45da3 mkl_blas_avx_sgemm_kernel_0
> Thu Jan 19 10:22:41 2017[1,19]<stderr>:./train.sh: line 207: 31795 Floating point exceptionPYTHONPATH=./paddle:$PYTHONPATH GLOG_logtostderr=0 GLOG_log_dir="./log" ./paddle_trainer --num_gradient_servers=${OMPI_COMM_WORLD_SIZE} --trainer_id=${OMPI_COMM_WORLD_RANK} --pservers=$ipstring --rdma_tcp=${rdma_tcp} --nics=${nics} ${train_arg} --config=conf/trainer_config.conf --save_dir=./${save_dir} ${extern_arg}
> Thu Jan 19 10:22:41 2017[1,19]<stderr>:+ '[' 136 -ne 0 ']'

从异常上来看，时浮点数异常，推测应该是过小导致吧，但是minibatch较小时就不出现，难道是根据minibatch做了归一化？导致梯度过小？

**Comment by reyoung** [comment]
1、麻烦将退出时候异常情况截全一点
2、麻烦参考下FAQ

**Comment by pkuyym** [comment]
更详细的信息：

> Thu Jan 19 10:22:39 2017[1,19]<stderr>:Thread [140008687789952] Forwarding __simple_gru2_0___transform, __embedding_0__, label, bidword_seq, 
> Thu Jan 19 10:22:39 2017[1,19]<stderr>:*** Aborted at 1484792559 (unix time) try "date -d @1484792559" if you are using GNU date ***
> Thu Jan 19 10:22:39 2017[1,19]<stderr>:PC: @           0xe45db7 mkl_blas_avx_sgemm_kernel_0
> Thu Jan 19 10:22:39 2017[1,1]<stderr>:Thread [140303555991424] Forwarding __simple_gru2_0___transform, __embedding_0__, label, bidword_seq, 
> Thu Jan 19 10:22:39 2017[1,1]<stderr>:*** Aborted at 1484792559 (unix time) try "date -d @1484792559" if you are using GNU date ***
> Thu Jan 19 10:22:39 2017[1,2]<stderr>:Thread [140571655157632] Forwarding __simple_gru2_0___transform, 
> Thu Jan 19 10:22:39 2017[1,2]<stderr>:__embedding_0__, label, bidword_seq, 
> Thu Jan 19 10:22:39 2017[1,2]<stderr>:*** Aborted at 1484792559 (unix time) try "date -d @1484792559" if you are using GNU date ***
> Thu Jan 19 10:22:39 2017[1,1]<stderr>:PC: @           0xe45da3 mkl_blas_avx_sgemm_kernel_0
> Thu Jan 19 10:22:39 2017[1,11]<stderr>:Thread [139701206407040] Forwarding __simple_gru2_0___transform, __embedding_0__, label, bidword_seq, 
> Thu Jan 19 10:22:39 2017[1,11]<stderr>:*** Aborted at 1484792559 (unix time) try "date -d @1484792559" if you are using GNU date ***
> Thu Jan 19 10:22:39 2017[1,0]<stderr>:Thread [140096278001536] Forwarding __simple_gru2_0___transform, __embedding_0__, label, 
> Thu Jan 19 10:22:39 2017[1,0]<stderr>:bidword_seq, 
> Thu Jan 19 10:22:39 2017[1,19]<stderr>:*** SIGFPE (@0xe45db7) received by PID 31795 (TID 0x7f565019e780) from PID 14966199; stack trace: ***
> Thu Jan 19 10:22:39 2017[1,0]<stderr>:*** Aborted at 1484792559 (unix time) try "date -d @1484792559" if you are using GNU date ***
> Thu Jan 19 10:22:39 2017[1,19]<stderr>:    @     0x7f564fd78160 (unknown)
> Thu Jan 19 10:22:39 2017[1,19]<stderr>:    @           0xe45db7 mkl_blas_avx_sgemm_kernel_0
> Thu Jan 19 10:22:39 2017[1,2]<stderr>:PC: @           0xe45db7 mkl_blas_avx_sgemm_kernel_0
> Thu Jan 19 10:22:39 2017[1,1]<stderr>:*** SIGFPE (@0xe45da3) received by PID 21078 (TID 0x7f9af79d9780) from PID 14966179; stack trace: ***
> Thu Jan 19 10:22:39 2017[1,1]<stderr>:    @     0x7f9af75b3160 (unknown)
> Thu Jan 19 10:22:39 2017[1,1]<stderr>:    @           0xe45da3 mkl_blas_avx_sgemm_kernel_0
> Thu Jan 19 10:22:39 2017[1,11]<stderr>:PC: @           0xe45db7 mkl_blas_avx_sgemm_kernel_0
> Thu Jan 19 10:22:39 2017[1,0]<stderr>:PC: @           0xe45d87 mkl_blas_avx_sgemm_kernel_0
> Thu Jan 19 10:22:39 2017[1,16]<stderr>:Thread [140201746683776] Forwarding __simple_gru2_0___transform, __embedding_0__, label, bidword_seq, 
> Thu Jan 19 10:22:39 2017[1,16]<stderr>:*** Aborted at 1484792559 (unix time) try "date -d @1484792559" if you are using GNU date ***
> Thu Jan 19 10:22:39 2017[1,14]<stderr>:Thread [140114723051392] Forwarding __simple_gru2_0___transform, __embedding_0__, label, bidword_seq, 
> Thu Jan 19 10:22:39 2017[1,14]<stderr>:*** Aborted at 1484792559 (unix time) try "date -d @1484792559" if you are using GNU date ***
> Thu Jan 19 10:22:39 2017[1,17]<stderr>:Thread [140726612678528] Forwarding __simple_gru2_0___transform, __embedding_0__, label, bidword_seq, 
> Thu Jan 19 10:22:39 2017[1,17]<stderr>:*** Aborted at 1484792559 (unix time) try "date -d @1484792559" if you are using GNU date ***
> Thu Jan 19 10:22:39 2017[1,18]<stderr>:Thread [140137521420160] Forwarding __simple_gru2_0___transform, __embedding_0__, label, bidword_seq, 
> Thu Jan 19 10:22:39 2017[1,18]<stderr>:*** Aborted at 1484792559 (unix time) try "date -d @1484792559" if you are using GNU date ***
> Thu Jan 19 10:22:39 2017[1,2]<stderr>:*** SIGFPE (@0xe45db7) received by PID 4826 (TID 0x7fd963923780) from PID 14966199; stack trace: ***
> Thu Jan 19 10:22:39 2017[1,2]<stderr>:    @     0x7fd9634fd160 (unknown)
> Thu Jan 19 10:22:39 2017[1,2]<stderr>:    @           0xe45db7 mkl_blas_avx_sgemm_kernel_0
> Thu Jan 19 10:22:39 2017[1,11]<stderr>:*** SIGFPE (@0xe45db7) received by PID 3758 (TID 0x7f0eb8c85780) from PID 14966199; stack trace: ***
> Thu Jan 19 10:22:39 2017[1,11]<stderr>:    @     0x7f0eb885f160 (unknown)
> Thu Jan 19 10:22:39 2017[1,11]<stderr>:    @           0xe45db7 mkl_blas_avx_sgemm_kernel_0
> Thu Jan 19 10:22:39 2017[1,16]<stderr>:PC: @           0xe45dcf mkl_blas_avx_sgemm_kernel_0
> Thu Jan 19 10:22:39 2017[1,14]<stderr>:PC: @           0xe45da3 mkl_blas_avx_sgemm_kernel_0
> Thu Jan 19 10:22:39 2017[1,18]<stderr>:PC: @           0xe45dc7 mkl_blas_avx_sgemm_kernel_0
> Thu Jan 19 10:22:39 2017[1,17]<stderr>:PC: @           0xe45d87 mkl_blas_avx_sgemm_kernel_0
> Thu Jan 19 10:22:39 2017[1,13]<stderr>:Thread [140467527620480] Forwarding __simple_gru2_0___transform, __embedding_0__, label, bidword_seq, 
> Thu Jan 19 10:22:39 2017[1,13]<stderr>:*** Aborted at 1484792559 (unix time) try "date -d @1484792559" if you are using GNU date ***
> Thu Jan 19 10:22:39 2017[1,14]<stderr>:*** SIGFPE (@0xe45da3) received by PID 11229 (TID 0x7f6f004b9780) from PID 14966179; stack trace: ***
> Thu Jan 19 10:22:39 2017[1,14]<stderr>:    @     0x7f6f00093160 (unknown)
> Thu Jan 19 10:22:39 2017[1,3]<stderr>:Thread [140153097013120] Forwarding __simple_gru2_0___transform, __embedding_0__, label, bidword_seq, 
> Thu Jan 19 10:22:39 2017[1,3]<stderr>:*** Aborted at 1484792559 (unix time) try "date -d @1484792559" if you are using GNU date ***
> Thu Jan 19 10:22:39 2017[1,14]<stderr>:    @           0xe45da3 mkl_blas_avx_sgemm_kernel_0
> Thu Jan 19 10:22:39 2017[1,0]<stderr>:*** SIGFPE (@0xe45d87) received by PID 27190 (TID 0x7f6ab4e27780) from PID 14966151; stack trace: ***
> Thu Jan 19 10:22:39 2017[1,0]<stderr>:    @     0x7f6ab4a01160 (unknown)
> Thu Jan 19 10:22:39 2017[1,0]<stderr>:    @           0xe45d87 mkl_blas_avx_sgemm_kernel_0
> Thu Jan 19 10:22:39 2017[1,13]<stderr>:PC: @           0xe45d87 mkl_blas_avx_sgemm_kernel_0
> Thu Jan 19 10:22:39 2017[1,3]<stderr>:PC: @           0xe45db7 mkl_blas_avx_sgemm_kernel_0
> Thu Jan 19 10:22:39 2017[1,17]<stderr>:*** SIGFPE (@0xe45d87) received by PID 31933 (TID 0x7ffd77c25780) from PID 14966151; stack trace: ***
> Thu Jan 19 10:22:39 2017[1,17]<stderr>:    @     0x7ffd777ff160 (unknown)
> Thu Jan 19 10:22:39 2017[1,18]<stderr>:*** SIGFPE (@0xe45dc7) received by PID 10594 (TID 0x7f744f2f1780) from PID 14966215; stack trace: ***
> Thu Jan 19 10:22:39 2017[1,17]<stderr>:    @           0xe45d87 mkl_blas_avx_sgemm_kernel_0
> Thu Jan 19 10:22:39 2017[1,18]<stderr>:    @     0x7f744eecb160 (unknown)
> Thu Jan 19 10:22:39 2017[1,18]<stderr>:    @           0xe45dc7 mkl_blas_avx_sgemm_kernel_0
> Thu Jan 19 10:22:39 2017[1,16]<stderr>:*** SIGFPE (@0xe45dcf) received by PID 10411 (TID 0x7f83434ed780) from PID 14966223; stack trace: ***
> Thu Jan 19 10:22:39 2017[1,13]<stderr>:*** SIGFPE (@0xe45d87) received by PID 5793 (TID 0x7fc125161780) from PID 14966151; stack trace: ***
> Thu Jan 19 10:22:39 2017[1,16]<stderr>:    @     0x7f83430c7160 (unknown)
> Thu Jan 19 10:22:39 2017[1,13]<stderr>:    @     0x7fc124d3b160 (unknown)
> Thu Jan 19 10:22:39 2017[1,16]<stderr>:    @           0xe45dcf mkl_blas_avx_sgemm_kernel_0
> Thu Jan 19 10:22:39 2017[1,13]<stderr>:    @           0xe45d87 mkl_blas_avx_sgemm_kernel_0
> Thu Jan 19 10:22:39 2017[1,10]<stderr>:Thread [140005277992832] Forwarding __simple_gru2_0___transform, __embedding_0__, label, bidword_seq, 
> Thu Jan 19 10:22:39 2017[1,10]<stderr>:*** Aborted at 1484792559 (unix time) try "date -d @1484792559" if you are using GNU date ***
> Thu Jan 19 10:22:39 2017[1,3]<stderr>:*** SIGFPE (@0xe45db7) received by PID 12770 (TID 0x7f77ef8fc780) from PID 14966199; stack trace: ***
> Thu Jan 19 10:22:39 2017[1,3]<stderr>:    @     0x7f77ef4d6160 (unknown)
> Thu Jan 19 10:22:39 2017[1,3]<stderr>:    @           0xe45db7 mkl_blas_avx_sgemm_kernel_0
> Thu Jan 19 10:22:39 2017[1,10]<stderr>:PC: @           0xe45db7 mkl_blas_avx_sgemm_kernel_0
> Thu Jan 19 10:22:39 2017[1,9]<stderr>:Thread [139777130837888] Forwarding __simple_gru2_0___transform, __embedding_0__, label, bidword_seq, 
> Thu Jan 19 10:22:39 2017[1,9]<stderr>:*** Aborted at 1484792559 (unix time) try "date -d @1484792559" if you are using GNU date ***
> Thu Jan 19 10:22:39 2017[1,10]<stderr>:*** SIGFPE (@0xe45db7) received by PID 18844 (TID 0x7f5584dc8780) from PID 14966199; stack trace: ***
> Thu Jan 19 10:22:39 2017[1,10]<stderr>:    @     0x7f55849a2160 (unknown)
> Thu Jan 19 10:22:39 2017[1,10]<stderr>:    @           0xe45db7 mkl_blas_avx_sgemm_kernel_0
> Thu Jan 19 10:22:39 2017[1,9]<stderr>:PC: @           0xe45dcf mkl_blas_avx_sgemm_kernel_0
> Thu Jan 19 10:22:39 2017[1,9]<stderr>:*** SIGFPE (@0xe45dcf) received by PID 9915 (TID 0x7f20663b3780) from PID 14966223; stack trace: ***
> Thu Jan 19 10:22:39 2017[1,9]<stderr>:    @     0x7f2065f8d160 (unknown)
> Thu Jan 19 10:22:39 2017[1,9]<stderr>:    @           0xe45dcf mkl_blas_avx_sgemm_kernel_0
> Thu Jan 19 10:22:39 2017[1,12]<stderr>:Thread [140589504018304] Forwarding __simple_gru2_0___transform, __embedding_0__, label, bidword_seq, 
> Thu Jan 19 10:22:39 2017[1,12]<stderr>:*** Aborted at 1484792559 (unix time) try "date -d @1484792559" if you are using GNU date ***
> Thu Jan 19 10:22:39 2017[1,12]<stderr>:PC: @           0xe45dc7 mkl_blas_avx_sgemm_kernel_0
> Thu Jan 19 10:22:39 2017[1,12]<stderr>:*** SIGFPE (@0xe45dc7) received by PID 8599 (TID 0x7fdd8b723780) from PID 14966215; stack trace: ***
> Thu Jan 19 10:22:39 2017[1,12]<stderr>:    @     0x7fdd8b2fd160 (unknown)
> Thu Jan 19 10:22:39 2017[1,12]<stderr>:    @           0xe45dc7 mkl_blas_avx_sgemm_kernel_0
> Thu Jan 19 10:22:39 2017[1,5]<stderr>:Thread [139923642955648] Forwarding __simple_gru2_0___transform, __embedding_0__, label, bidword_seq, 
> Thu Jan 19 10:22:39 2017[1,5]<stderr>:*** Aborted at 1484792559 (unix time) try "date -d @1484792559" if you are using GNU date ***
> Thu Jan 19 10:22:39 2017[1,15]<stderr>:Thread [139967555884928] Forwarding __simple_gru2_0___transform, __embedding_0__, label, bidword_seq, 
> Thu Jan 19 10:22:39 2017[1,15]<stderr>:*** Aborted at 1484792559 (unix time) try "date -d @1484792559" if you are using GNU date ***
> Thu Jan 19 10:22:39 2017[1,5]<stderr>:PC: @           0xe45d87 mkl_blas_avx_sgemm_kernel_0
> Thu Jan 19 10:22:40 2017[1,15]<stderr>:PC: @           0xe45d87 mkl_blas_avx_sgemm_kernel_0
> Thu Jan 19 10:22:40 2017[1,5]<stderr>:*** SIGFPE (@0xe45d87) received by PID 31887 (TID 0x7f428308b780) from PID 14966151; stack trace: ***
> Thu Jan 19 10:22:40 2017[1,5]<stderr>:    @     0x7f4282c65160 (unknown)
> Thu Jan 19 10:22:40 2017[1,5]<stderr>:    @           0xe45d87 mkl_blas_avx_sgemm_kernel_0
> Thu Jan 19 10:22:40 2017[1,7]<stderr>:Thread [140408779712384] Forwarding __simple_gru2_0___transform, __embedding_0__, label, bidword_seq, 
> Thu Jan 19 10:22:40 2017[1,7]<stderr>:*** Aborted at 1484792560 (unix time) try "date -d @1484792560" if you are using GNU date ***
> Thu Jan 19 10:22:40 2017[1,15]<stderr>:*** SIGFPE (@0xe45d87) received by PID 29708 (TID 0x7f4cbc72d780) from PID 14966151; stack trace: ***
> Thu Jan 19 10:22:40 2017[1,15]<stderr>:    @     0x7f4cbc307160 (unknown)
> Thu Jan 19 10:22:40 2017[1,15]<stderr>:    @           0xe45d87 mkl_blas_avx_sgemm_kernel_0
> Thu Jan 19 10:22:40 2017[1,7]<stderr>:PC: @           0xe45d95 mkl_blas_avx_sgemm_kernel_0
> Thu Jan 19 10:22:40 2017[1,4]<stderr>:Thread [140132209895296] Forwarding __simple_gru2_0___transform, __embedding_0__, label, bidword_seq,

**Comment by reyoung** [comment]
这个FPE会随着batch size改变而改变的原因，是在这里 https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/trainer_config_helpers/optimizers.py#L375

Paddle在实现SGD的时候，有一个和公式不同的地方。

通常，一般的公式里面解释SGD的时候，都会将这个mini-batch中所有样本产生的Gradient加起来，然后除以样本数，计算出每一个样本的平均梯度，然后再用这个平均的梯度去更新神经网络。

在Paddle里面，并没有计算每条样本的平均梯度，而是使用所有样本的整体梯度去更新网络。

这么做的原因是，

* 如果想要用平均梯度的话，调整learning rate其实也就可以了。
* 现在流行的大部分优化算法都是adaptive的，梯度的大小并不那么重要，而方向却很重要。例如adam，rmsprop
* 如果需要除以样本数的话，多机的情况下，样本数还需要同步一遍。写起来比较麻烦。同时，在每个pass(epoch)结束的那个mini-batch里，样本数也会有一个变化。

正因为这样，在Paddle里面增大batch_size，就会导致Gradient的尺度变得更大，Value减去Gradient的时候减的更狠，所以更容易出现FPE。

**Comment by pkuyym** [comment]
@reyoung 增大batch size，然后相应减小learning rate，应该可以避免FPE吧，但是比较好奇的是，为什么增大batch size后，会明显拖慢速度呢，出现I0119 10:18:58.880401 27190 Stat.h:221] Stat: [BpBiasTimer] fc_layer_0 [Span:22465ms117us]这种性能警报

**Comment by reyoung** [comment]
Batch size变大后，每一个mini-batch要处理的数据就增多了。所以每个mini-batch的速度就会变慢。。

不过整体扫过所有数据的时间，可能会快一点。

**Comment by helinwang** [comment]
问题应该得到解答了，我先关闭这个issue，要是还有问题请把这个issue打开。
