### ISSUE TITLE
The doc of ExecutionStrategy and BuildStrategy is empty.

### ISSUE THREAD

**Issue by chengduoZH** [PaddlePaddle/Paddle#11899]
The doc of ExecutionStrategy and BuildStrategy is empty.

![es_bs](https://user-images.githubusercontent.com/30176695/42196113-c7764d44-7eae-11e8-94db-7b137a435265.png)

**Comment by shanyi15** [comment]
请问这两个api的reference是不需要加了吗，看到pr被驳回了
