### ISSUE TITLE
Type Attribute is not defined in attribute.h but in type_defs.h

### ISSUE THREAD

**Issue by wangkuiyi** [PaddlePaddle/Paddle#11892]
The type Attribute 

https://github.com/PaddlePaddle/Paddle/blob/ebadb4c0916d37a50b66cf33414a28aa0ea01dbe/paddle/fluid/framework/type_defs.h#L35-L39

should be defined in attirubte.h, but not any other file.

It seems that type_defs.h serves as a "hub" where all common types are in there. This would break the software design principle of modulization.

**Comment by reyoung** [comment]
Thanks very much!!!
