### ISSUE TITLE
train启动的时候提示CUDNN_STATUS_NOT_INITIALIZED 

### ISSUE THREAD

**Issue by colin1988** [PaddlePaddle/Paddle#1190]
F0119 13:28:50.834202  2944 hl_cuda_cudnn.cc:186] Check failed: CUDNN_STATUS_SUCCESS == cudnnStat (0 vs. 1) Cudnn Error: CUDNN_STATUS_NOT_INITIALIZED
*** Check failure stack trace: ***
    @          0x147b738  google::LogMessage::Fail()
    @          0x147b690  google::LogMessage::SendToLog()
    @          0x147b125  google::LogMessage::Flush()
    @          0x147dee6  google::LogMessageFatal::~LogMessageFatal()
    @           0x935a3a  hl_cudnn_init()
    @           0x93f791  hl_create_global_resources()
    @           0x93ffa9  hl_specify_devices_start()
    @           0x9403cd  hl_start()
    @           0x8aeb7b  paddle::initMain()
    @           0x5b833f  main
    @     0x7f7fd6775bd5  __libc_start_main
    @           0x5cdfa5  (unknown)
/home/aducz/paddle/paddle_internal_release_tools/idl/paddle/output/bin/paddle_local: line 109:  2944 Aborted                 (core dumped) ${DEBUGGER} $MYDIR/../opt/paddle/bin/paddle_trainer ${@:2}

**Comment by gangliao** [comment]
@colin1988  This error seems that you need to upgrade CUDA Driver. @hedaoyuan

**Comment by helinwang** [comment]
Closing this issue for now. @colin1988 If updating CUDA driver does not solve your problem. Please reopen this issue.
