### ISSUE TITLE
Record stack traceback in python API and throw that stack info when the op fails at runtime for debugging

### ISSUE THREAD

**Issue by typhoonzero** [PaddlePaddle/Paddle#11903]
@panyx0718 said that we can learn from TF's debugging ways to make debug fluid program simpler:

1. record the traceback string when calling `append_op`
1. put the traceback info in the operator as data.
1. when op run fails, can raise the traceback stack for debugging.

**Comment by lucywsq** [comment]
您好，此内部建议记录后将先行关闭，若需要优化的功能开发计划进入排期后，可再重新开启此issue，感谢您的支持！
