### ISSUE TITLE
集群paddlepaddle版本不支持deepFM

### ISSUE THREAD

**Issue by dpwu1994** [PaddlePaddle/Paddle#11905]
如题，集群版本的paddlepaddle版本低于0.11，有没有办法解决。十分感谢。

**Comment by guoshengCS** [comment]
可以参考 http://wiki.baidu.com/pages/viewpage.action?pageId=327596461 中 **更新本地提交package中的paddle二进制** 部分的内容

**Comment by dpwu1994** [comment]
我down不下来最新版的paddlepaddle的whl文件，你那边能提供一份吗，十分感谢

**Comment by guoshengCS** [comment]
CI页面左上角Projects下点击manylinux1选择需要的版本就可以，找到最近编译成功的点击Artifacts选择需要的包

**Comment by dpwu1994** [comment]
paddlepaddle-0.14.0-cp27-cp27mu-linux_x86_64.whl is not a supported wheel on this platform.
这个报错要怎么解决。

**Comment by guoshengCS** [comment]
可以试下重命名为paddlepaddle-0.14.0-cp27-none-linux_x86_64.whl，或者参考FAQ这里 https://github.com/PaddlePaddle/Paddle/blob/develop/doc/v2/faq/build_and_install/index_cn.rst#4-paddlepaddlewhl-is-not-a-supported-wheel-on-this-platform

**Comment by dpwu1994** [comment]
重命名为paddlepaddle-0.14.0-cp27-none-linux_x86_64.whl后可以，十分感谢！

**Comment by dpwu1994** [comment]
server.log里面报错：
./paddle_pserver2: error while loading shared libraries: ./python27-gcc482/lib/libmkldnn.so.0: ELF file OS ABI invalid
[FATAL]: paddle_pserver2 failed
不知道是不是因为昨天的安装0.14.0版本时，替换了paddle_pserver2 所导致
cp bin/paddle_pserver_main ../paddle_pserver2
十分感谢

**Comment by guoshengCS** [comment]
可以还按之前的方法重新下载个不用MKL的whl包试下

**Comment by dpwu1994** [comment]
额，这个要怎么看，我下了一个0.12.0的好像还是要用这个~
十分感谢

**Comment by guoshengCS** [comment]
不带MKL后缀的就是不依赖MKL的
![image](https://user-images.githubusercontent.com/14105589/42270900-8baabdca-7fb4-11e8-96c5-4948ac64b7ed.png)

**Comment by dpwu1994** [comment]
出现新的报错，问题还是在paddle_pserver2，如何解决十分感谢
4 23:33:47 2018[1,0]<stderr>:./paddle_pserver2: /lib64/tls/libc.so.6: version `GLIBC_2.7' not found (required by ./paddle_pserver2)
Wed Jul  4 23:33:47 2018[1,0]<stderr>:./paddle_pserver2: /lib64/tls/libc.so.6: version `GLIBC_2.6' not found (required by ./paddle_pserver2)
Wed Jul  4 23:33:47 2018[1,0]<stderr>:./paddle_pserver2: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.10' not found (required by ./paddle_pserver2)
Wed Jul  4 23:33:47 2018[1,0]<stderr>:./paddle_pserver2: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.9' not found (required by ./paddle_pserver2)
Wed Jul  4 23:33:47 2018[1,0]<stderr>:./paddle_pserver2: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.13' not found (required by ./paddle_pserver2)
Wed Jul  4 23:33:47 2018[1,0]<stderr>:./paddle_pserver2: /usr/lib64/libstdc++.so.6: version `CXXABI_1.3.3' not found (required by ./paddle_pserver2)
Wed Jul  4 23:33:47 2018[1,0]<stderr>:./paddle_pserver2: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.11' not found (required by ./paddle_pserver2)
Wed Jul  4 23:33:47 2018[1,0]<stderr>:./paddle_pserver2: /lib64/tls/libc.so.6: version `GLIBC_2.14' not found (required by ./python27-gcc482/lib/libpython2.7.so.1.0)
Wed Jul  4 23:33:47 2018[1,0]<stderr>:+ check_return 'paddle_pserver2 failed'

**Comment by guoshengCS** [comment]
应该是CI的这个build所用环境和集群机器环境不一样，可能需要自己参照集群环境或者公司开发机编译一个，参照这里 http://wiki.baidu.com/pages/viewpage.action?pageId=327596892 **CentOS 4.3/6.3上编译fluid**部分

**Comment by HugoLian** [comment]
请问这个问题解决了么？我现在遇到了完全一样的问题，楼主遇到的所有问题，我都正在经历。。。。

**Comment by HugoLian** [comment]
@dpwu1994

**Comment by dpwu1994** [comment]
没有解决啊。。后面做其他事情了去了，没继续踩坑了。。

**Comment by luotao1** [comment]
@typhoonzero 觉得是有必要总结一个在大部分集群可以运行的python环境。这个python环境下可以直接pip install paddle 就可以。

**Comment by 333caowei** [comment]
遇到了同样的问题

**Comment by typhoonzero** [comment]
后续集群版本更新可以迁移到paddle cloud，传统手动更新方式容易出错。先关闭此issue了，如果有问题可以reopen，谢谢。
