### ISSUE TITLE
0.11 版本android v7a获取height和width一样，v8a下正常。

### ISSUE THREAD

**Issue by authorfu** [PaddlePaddle/Paddle#11906]
使用paddle_matrix_get_shape(probs, &result.height, &result.width)) 加载armeabi-v7a下so，获取 result.height及result.width， 获得的值都是相等的。
arm-v8a下获得值是符合预期的，result.width一直都是7.
在多台手机及客户的设备上验证。armeabi-v7a下均有此问题。

测试CPU均为 Cortex A53

**Comment by guoshengCS** [comment]
之前有在OCR那边测试过这两个库下的使用应该都是没问题的，麻烦还请确认下使用是否存在问题
