### ISSUE TITLE
【Question】请问paddle支持用RNN+LSTM进行text generation吗？在例子中没有找到。。。

### ISSUE THREAD

**Issue by sillybowen** [PaddlePaddle/Paddle#1191]
假设我有一组电商评论数据，想要训练生成类似的短信息。

在例子中只看到了基于翻译的seqToSeq

Lstm只看到了分类的例子

**Comment by luotao1** [comment]
请问“基于翻译的seqToSeq”和你需要的“RNN+LSTM”差别具体在哪里呢？可以在配置中任意指定需要的layer。

**Comment by sillybowen** [comment]
多谢回复。

我实际是想做一个类似：
http://mxnet.io/tutorials/python/char_lstm.html
的功能，比较一下paddle和mxnet的performance 

SeqToSeq 我的理解是根据输入的Seq选取一个match的Seq。
而我要做的是，输入seq的起始，根据概率生成固定长度的seq。

请问该用哪些layer啊？
或者有没有哪个例子我能借鉴的？

多谢。

**Comment by kuke** [comment]
Closed because of inactivity
