### ISSUE TITLE
capi demo中没有多个data layer的demo

### ISSUE THREAD

**Issue by vincewangnsn** [PaddlePaddle/Paddle#11911]
在进行paddle capi预测改造时，由于模型比较复杂，有多个data layer，如下图所示
![image](https://user-images.githubusercontent.com/40789621/42209610-ac9213cc-7ee1-11e8-9995-e06f807837cd.png)
    请问如何构建Argument，是否依次构建Argument就ok了？是否需要将名字与各个Argument对应？如果可以的话，是否方便给出个多个data layer的demo进行参考，谢谢~

**Comment by guoshengCS** [comment]
可以尝试下参照 https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/legacy/capi/examples/model_inference/dense/main.c 进行以下几处修改
1. `paddle_arguments_resize(in_args, 1)`改为`paddle_arguments_resize(in_args, 10)`
2. 使用`paddle_matrix_create`为输入 i 创建 paddle_matrix_i
3. `paddle_arguments_set_value(in_args, i, paddle_matrix_i)`

**Comment by vincewangnsn** [comment]
@guoshengCS 
```c++
int seq_pos_array[] = {0, 5, 8, 10, 14};
paddle_ivector seq_pos = paddle_ivector_create(
    seq_pos_array, sizeof(seq_pos_array) / sizeof(int), false, false);
// Suppose the network only has one input data layer.
CHECK(paddle_arguments_set_sequence_start_pos(in_args, 0, 0, seq_pos));
```
请问paddle_arguments_set_sequence_start_pos 函数中第三个参数是什么？
![image](https://user-images.githubusercontent.com/40789621/42275016-6410a2c2-7fc1-11e8-8638-59be593549fb.png)

**Comment by guoshengCS** [comment]
这个是双层序列会用到的，表示这是第几层的序列信息

**Comment by vincewangnsn** [comment]
@guoshengCS 
![image](https://user-images.githubusercontent.com/40789621/42275531-3767e9e0-7fc3-11e8-9905-f9d992228042.png)
这是tutorial上面给的例子，也就是我上面copy的代码

**Comment by guoshengCS** [comment]
单层序列用0就可以

**Comment by vincewangnsn** [comment]
@guoshengCS  好的，再麻烦问一下，Python 端数据类型是integer_value_sequence，那么附加的序列信息就是{0}？

**Comment by guoshengCS** [comment]
单层序列第三个参数用0就可以。
数据类型是integer_value_sequence，附加的序列信息是根据每个sequence长度创建的seq_pos，参照你上面贴图里的说明就可以
