### ISSUE TITLE
CosSimLayer 支持单边 static 的问题

### ISSUE THREAD

**Issue by Superjom** [PaddlePaddle/Paddle#1193]
听胡鹏说 CosSimLayer不支持单边 is_static，看了下代码应该很容易改。
可以优先支持下么，在做这块的调研。 

from yanchunwei@baidu.com

**Comment by lcy-seso** [comment]
好像是这个问题，https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/gserver/layers/CosSimLayer.cpp#L62
如果设置了is_static=True, 上面那一行获取梯度的时候会出问题。

最简单的fix，输入的static 参数不要用is_static=True，设置 learning_rate=0。

梯度始终是要回传给前层的，网络中间插入了一层没有梯度，似乎有点奇怪 ？除非这一路都是static 的对吗？如果是后一种，可以先设置learning rate = 0 试试。
