### ISSUE TITLE
Fluid source code declared LAPACK functions but never uses them

### ISSUE THREAD

**Issue by wangkuiyi** [PaddlePaddle/Paddle#11947]
Watch this 

https://github.com/PaddlePaddle/Paddle/search?q=LAPACKE_sgetrf+path%3Apaddle%2Ffluid&unscoped_q=LAPACKE_sgetrf+path%3Apaddle%2Ffluid

**Comment by reyoung** [comment]
It seems that `lapacke` is imported in #3209, but I do not know why. Let the reviewer @dzhwinter  decide should we remove it or not.
