### ISSUE TITLE
Move VisitPlace from fluid::platform to fluid::framework

### ISSUE THREAD

**Issue by wangkuiyi** [PaddlePaddle/Paddle#11948]
From the search result

https://github.com/PaddlePaddle/Paddle/search?q=VisitPlace&unscoped_q=VisitPlace

we see that VisitPlace, which is defined in fluid::platform, is only used in tensor_util.cc, which is in fluid::framework.

For the principal of locality, we should move VisitPlace to where it is used.

**Comment by reyoung** [comment]
Maybe the ultimate solution is #11952. We just change `Place` into plain classes.
