### ISSUE TITLE
NCCL2 distributed training mode parameter initialization is not correct

### ISSUE THREAD

**Issue by typhoonzero** [PaddlePaddle/Paddle#11956]
As mentioned in https://github.com/PaddlePaddle/Paddle/pull/11885#discussion_r199865186, we initialize parameters on each node and broadcasting them to GPUs only on current machine, then parameters could be different on different nodes in the first batch. And this is what exactly @velconia is doing right now for the RPC mode distributed training parameter initialization.

**Comment by velconia** [comment]
The details were described [in this issue](https://github.com/PaddlePaddle/Paddle/issues/11843]

**Comment by typhoonzero** [comment]
Reviewed the code, the initialized parameters will be broadcasted to all nodes when initializing `ParallelExecutor`, this should not be a problem.
