### ISSUE TITLE
PaddlePaddle Fluid EDL

### ISSUE THREAD

**Issue by Yancey0623** [PaddlePaddle/Paddle#11958]
Tasks
- full fault-tolerant training
    - [ ] design doc, https://github.com/PaddlePaddle/Paddle/pull/11625
    - [ ] recoverable trainer process without shutting down the whole job
    - [ ] recoverable pserver process without shutting down the whole job
    - [ ] distributed task queue to manage tasks in etcd
    - [ ] distributed reader to fetch record from task queue
    - [ ] pserver HA
- [ ] support other frameworks like TF using a python API
- [ ] dynamic trainer count in the pserver side so that we will be able to average gradients according to current trainer count.
- [ ] Upgrade EDL controller to CRD so that we can support Kubernetes higher than v1.8
- [ ] a tutorial to run distributed lookup sparse table with EDL
- [ ] update experiment report, https://github.com/PaddlePaddle/cloud/tree/develop/doc/edl/experiment

**Comment by typhoonzero** [comment]
@velconia

**Comment by typhoonzero** [comment]
> pserver HA

Do you mean by implementing parameter server replicas to support online training?

**Comment by Yancey0623** [comment]
> Do you mean by implementing parameter server replicas to support online training?

Yes, but not only supporting online training, for the offline training job that reduces pserver recovery time is necessary.
But maybe we can implement `recoverable pserver process without shutting down the whole job` first.

**Comment by velconia** [comment]
Should we add implement trainer HA too?

**Comment by typhoonzero** [comment]
I added support other frameworks like TF using a python API, design doc is needed.

**Comment by seiriosPlus** [comment]
The HA may take memory twice as much. It is inappropriate to be used in large models.

**Comment by typhoonzero** [comment]
Moving discussions to https://github.com/PaddlePaddle/edl/issues/35

**Comment by typhoonzero** [comment]
Closing.
