### ISSUE TITLE
setup paddle on redhat

### ISSUE THREAD

**Issue by sunshinee24** [PaddlePaddle/Paddle#1196]
Is there anyone setting up paddle on redhat, in cmake/extern/system file, it  seems paddle doesn't support redhat, I am not sure.

**Comment by gangliao** [comment]
This PR can help to pass system detection in CMake.
https://github.com/PaddlePaddle/Paddle/pull/1195

We have yet build Paddle on red hat. But, you can try it on red hat.

**Comment by wangkuiyi** [comment]
Currently, the society supports only two forms of builds -- Docker images and Ubuntu 14.04. It would be great if you are able to build and run Paddle on RedHat/Fedora and would like to maintain it (answering related users's inquiries).  If so, could we have your favor to create a Pull Request adding a https://github.com/PaddlePaddle/Paddle/tree/develop/doc/howto/redhat/README.md file describing the steps to build and run Paddle on RedHat?  Thanks.
