### ISSUE TITLE
多机同步训练时，learning_rate为piecewise_decay时ps启动报错

### ISSUE THREAD

**Issue by kolinwei** [PaddlePaddle/Paddle#11969]
*** SIGSEGV (@0x40000000a) received by PID 14246 (TID 0x7fa3cd7fa700) from PID 10; stack trace: ***
    @     0x7fa5bd812390 (unknown)
    @     0x7fa569adc575 paddle::framework::Executor::RunPreparedContext()
    @     0x7fa56a6ae40a _ZNSt17_Function_handlerIFSt10unique_ptrIN6paddle8platform13EnforceNotMetESt14default_deleteIS3_EEvESt17reference_wrapperISt12_Bind_simpleIFS8_IZNS1_9framework10ThreadPool18RunAndGetExceptionIZNS1_9operatorsL21ParallelExecuteBlocksERKSt6vectorImSaImEEPNSA_8ExecutorERKSE_ISt10shared_ptrINSA_22ExecutorPrepareContextEESaISN_EEPNSA_11ProgramDescEPNSA_5ScopeEEUlvE_EESt6futureIS6_ET_EUlvE_EvEEEE9_M_invokeERKSt9_Any_data
    @     0x7fa56a56892a std::_Function_handler<>::_M_invoke()
    @     0x7fa56a567f47 std::__future_base::_State_base::_M_do_set()
    @     0x7fa5bd80fa99 __pthread_once_slow
    @     0x7fa56a6adad2 _ZNSt13__future_base11_Task_stateIZN6paddle9framework10ThreadPool18RunAndGetExceptionIZNS1_9operatorsL21ParallelExecuteBlocksERKSt6vectorImSaImEEPNS2_8ExecutorERKS6_ISt10shared_ptrINS2_22ExecutorPrepareContextEESaISF_EEPNS2_11ProgramDescEPNS2_5ScopeEEUlvE_EESt6futureISt10unique_ptrINS1_8platform13EnforceNotMetESt14default_deleteISS_EEET_EUlvE_SaIiEFSV_vEE6_M_runEv
    @     0x7fa56a88b6a8 paddle::framework::ThreadPool::TaskLoop()
    @     0x7fa57c688c80 (unknown)
    @     0x7fa5bd8086ba start_thread
    @     0x7fa5bd53e41d clone
    @                0x0 (unknown)
Segmentation fault (core dumped)

**Comment by kolinwei** [comment]
可以用https://github.com/PaddlePaddle/models/tree/develop/fluid/image_classification 下的se-resnext模型浮现

**Comment by typhoonzero** [comment]
需要把这个单测也加到https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/fluid/tests/unittests/test_dist_transpiler.py

**Comment by typhoonzero** [comment]
验证最新的代码已经修复了。对应单测也增加。

**Comment by typhoonzero** [comment]
已经可以复现问题，正在排查。
