### ISSUE TITLE
例行任务最近训练开始卡住

### ISSUE THREAD

**Issue by SheldonZHANG** [PaddlePaddle/Paddle#11975]
使用的是v1.11.0版本，例行任务最近几天开始在训练的时候卡住，具体表现如下图所示；卡住的同时显示http 200的日志，定位发现是paddle/python27-gcc482/lib/python2.7/BaseHTTPServer.py打印的日志，调用该代码的程序可能是train.sh里面的代码，见第二张图
![image](https://user-images.githubusercontent.com/4178111/42279193-994151fe-7fcf-11e8-9683-a742c80e5fc5.png)

![image](https://user-images.githubusercontent.com/4178111/42279406-433119ce-7fd0-11e8-96e8-5aebe1c676a2.png)

**Comment by SheldonZHANG** [comment]
任务链接： http://yq01-hpc-lvliang-mon.dmop.baidu.com:8919/taskinfo.html?appId=app-user-20180704162728-46523&submitTime=2018-07-04%2016:27:28

**Comment by fantine16** [comment]
链接删了吧？

**Comment by lucywsq** [comment]
您好，目前V2版本已不进行维护，此任务在Fluid中可跑通，建议将代码迁移~
此issue在近一个月内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题，
我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持!
