### ISSUE TITLE
集群任务报错

### ISSUE THREAD

**Issue by 201101050424** [PaddlePaddle/Paddle#11974]
部分错误如下：
Wed Jul  4 20:24:41 2018[1,5]<stderr>:F0704 20:24:41.447738 57287 ThreadLocal.h:83] Check failed: pthread_setspecific(threadSpecificKey_, p) == 0 : Success [0]
完整日志：
http://10.74.162.18:8900/filetree?action=cat&path=/home/disk1/normandy/maybach/194916/workspace/log/train.log

**Comment by wanghaoshuang** [comment]
建议联系集群OP协助排查下该错误。

**Comment by ktlichkid** [comment]
Closed due to low activity. Please feel free to reopen it.
