### ISSUE TITLE
Loss with Parallel executor converge slower than MKLDNN

### ISSUE THREAD

**Issue by bingyanghuang** [PaddlePaddle/Paddle#11984]
Hi,

When I did the demo GUI with MKL optimizing on Parallel executor, and with MKLDNN, I found that after 600 iterations, MKL loss value is much slower than MKLDNN loss value. You can see it from figure below.
![image](https://user-images.githubusercontent.com/33643817/42306103-497aeb9e-8060-11e8-868e-ed7c5d6e1698.png)

We can see from the figure that with MKL loss converges slower than MKLDNN.
The demo is a python script which I save in format of txt, you can convert it to python by changing from ".txt "to ".py".   Just run it with `python filename` and click "start" in GUI.  

This is the ResNet50 python script for MKL with Parallel executor:[GUI MKL New.txt](https://github.com/PaddlePaddle/Paddle/files/2165207/GUI.MKL.New.txt)
This is the ResNet50 python script for MKL-DNN:[GUI training for ResNet50 benchmark.txt](https://github.com/PaddlePaddle/Paddle/files/2165208/GUI.training.for.ResNet50.benchmark.txt)

**Comment by luotao1** [comment]
Maybe we should test Parallel executor with MKL and Executor with MKL at first.

**Comment by luotao1** [comment]
@bingyanghuang 
- Could you give us the script without GUI?
- Could you have a test with the same random seed at first?
https://github.com/PaddlePaddle/Paddle/blob/8b80d6da23c3c9813dc2263cba98188bb57a569c/benchmark/fluid/fluid_benchmark.py#L320

**Comment by bingyanghuang** [comment]
@luotao1 
Hi, Luotao
Sorry to respond to you so late, I have been on vacation last week.
* Could you give us the script without GUI?
Here is the ResNet50 python script for MKL with Parallel executor:[train_resnet.txt](https://github.com/PaddlePaddle/Paddle/files/2199886/train_resnet.txt)
I run it with 
`export CPU_NUM=32`
`python train_resnet.py --display_step=1 --warmup=0 --use_gpu=false --number_iteration=20 --skip_first_steps=5 --batch_size_per_trainer=2 --pass_num=1000 --fix_data_in_card=false`
Here is the ResNet50 python script for MKL-DNN:[resnet_mkldnn.txt](https://github.com/PaddlePaddle/Paddle/files/2199906/resnet_mkldnn.txt)
I run it with
`export OMP_NUM_THREADS=36`(On Xeon 6140, Xeon 6148 will be 40)
`export KMP_AFFINITY=granularity=fine,compact,1,0`
`python resnet.py --device=CPU --pass_num=1000 --iterations=40 --batch_size=64 --data_set=flowers --use_mkldnn`
* Could you have a test with the same random seed at first?
  I inserted the random seed (fluid.default_startup_program().random_seed = 1) in both MKL and MKLDNN scripts ,you can check them in the scripts above. Not sure I did it rightly, because I got different loss values each time I run it. After 16 passes with 40 iterations per pass, I got the following results.
### MKL loss results:
pass=16,iter=1, cost=3.8998265, elapse=2.743802, img/sec=839.710716
pass=16,iter=2, cost=4.0034885, elapse=2.529420, img/sec=25.302242
pass=16,iter=3, cost=3.7001367, elapse=2.500464, img/sec=25.595250
pass=16,iter=4, cost=3.6734014, elapse=2.422616, img/sec=26.417724
pass=16,iter=5, cost=3.6091561, elapse=2.439499, img/sec=26.234896
pass=16,iter=6, cost=3.8289914, elapse=2.390324, img/sec=26.774614
pass=16,iter=7, cost=4.206875, elapse=2.425246, img/sec=26.389076
pass=16,iter=8, cost=3.7450442, elapse=2.402758, img/sec=26.636056
pass=16,iter=9, cost=3.6541233, elapse=2.508515, img/sec=25.513104
pass=16,iter=10, cost=4.3115845, elapse=2.477625, img/sec=25.831190
pass=16,iter=11, cost=3.7434502, elapse=2.462387, img/sec=25.991042
pass=16,iter=12, cost=3.5847137, elapse=2.417292, img/sec=26.475906
pass=16,iter=13, cost=3.8390553, elapse=2.452210, img/sec=26.098907
pass=16,iter=14, cost=3.8817425, elapse=2.430587, img/sec=26.331087
pass=16,iter=15, cost=3.7094717, elapse=2.456391, img/sec=26.054483
pass=16,iter=16, cost=3.8221426, elapse=2.479660, img/sec=25.809990
pass=16,iter=17, cost=3.7872772, elapse=2.417982, img/sec=26.468354
pass=16,iter=18, cost=3.6356225, elapse=2.417052, img/sec=26.478536
pass=16,iter=19, cost=3.6081834, elapse=2.475504, img/sec=25.853320
pass=16,iter=20, cost=3.8264966, elapse=2.396983, img/sec=26.700232
pass=16,iter=21, cost=3.7632499, elapse=2.454105, img/sec=26.078752
pass=16,iter=22, cost=3.6129532, elapse=2.379496, img/sec=26.896454
pass=16,iter=23, cost=3.8844528, elapse=2.418326, img/sec=26.464586
pass=16,iter=24, cost=3.8995914, elapse=2.487977, img/sec=25.723713
pass=16,iter=25, cost=3.6648283, elapse=2.410742, img/sec=26.547842
pass=16,iter=26, cost=3.4723861, elapse=2.413311, img/sec=26.519582
pass=16,iter=27, cost=3.6867383, elapse=2.417265, img/sec=26.476204
pass=16,iter=28, cost=3.6850967, elapse=2.404773, img/sec=26.613739
pass=16,iter=29, cost=4.159173, elapse=2.422574, img/sec=26.418181
pass=16,iter=30, cost=3.8440018, elapse=2.423628, img/sec=26.406692
pass=16,iter=31, cost=4.0500917, elapse=2.460153, img/sec=26.014644
pass=16,iter=32, cost=3.6761026, elapse=2.482506, img/sec=25.780401
pass=16,iter=33, cost=4.1401644, elapse=2.413681, img/sec=26.515517
pass=16,iter=34, cost=3.2745652, elapse=2.410656, img/sec=26.548790
pass=16,iter=35, cost=3.5303767, elapse=2.442713, img/sec=26.200376
pass=16,iter=36, cost=3.8183575, elapse=2.419508, img/sec=26.451659
pass=16,iter=37, cost=3.787253, elapse=2.378469, img/sec=26.908066
pass=16,iter=38, cost=3.758924, elapse=2.506734, img/sec=25.531230
pass=16,iter=39, cost=3.9799178, elapse=2.499737, img/sec=25.602693
pass=16,iter=40, cost=3.8034651, elapse=2.482930, img/sec=25.775999
### MKLDNN loss results:
Pass: 16, Iter: 1, Loss: 2.385811, Accuracy: 0.437500, FPS: 32.71241 img/s
Pass: 16, Iter: 2, Loss: 2.561316, Accuracy: 0.359375, FPS: 33.05894 img/s
Pass: 16, Iter: 3, Loss: 2.790822, Accuracy: 0.312500, FPS: 33.40132 img/s
Pass: 16, Iter: 4, Loss: 2.437704, Accuracy: 0.406250, FPS: 33.73789 img/s
Pass: 16, Iter: 5, Loss: 2.203534, Accuracy: 0.375000, FPS: 34.05697 img/s
Pass: 16, Iter: 6, Loss: 2.182505, Accuracy: 0.437500, FPS: 54.21877 img/s
Pass: 16, Iter: 7, Loss: 2.426384, Accuracy: 0.406250, FPS: 51.50700 img/s
Pass: 16, Iter: 8, Loss: 2.520123, Accuracy: 0.328125, FPS: 52.26802 img/s
Pass: 16, Iter: 9, Loss: 2.606726, Accuracy: 0.406250, FPS: 52.48902 img/s
Pass: 16, Iter: 10, Loss: 2.409656, Accuracy: 0.421875, FPS: 52.78261 img/s
Pass: 16, Iter: 11, Loss: 2.828329, Accuracy: 0.296875, FPS: 52.80097 img/s
Pass: 16, Iter: 12, Loss: 2.700110, Accuracy: 0.312500, FPS: 52.68178 img/s
Pass: 16, Iter: 13, Loss: 2.788381, Accuracy: 0.328125, FPS: 52.73723 img/s
Pass: 16, Iter: 14, Loss: 1.786742, Accuracy: 0.515625, FPS: 52.89319 img/s
Pass: 16, Iter: 15, Loss: 2.084830, Accuracy: 0.390625, FPS: 52.95670 img/s
Pass: 16, Iter: 16, Loss: 2.199879, Accuracy: 0.468750, FPS: 53.00152 img/s
Pass: 16, Iter: 17, Loss: 2.115891, Accuracy: 0.375000, FPS: 52.99768 img/s
Pass: 16, Iter: 18, Loss: 2.321513, Accuracy: 0.390625, FPS: 53.08582 img/s
Pass: 16, Iter: 19, Loss: 2.799248, Accuracy: 0.218750, FPS: 53.11047 img/s
Pass: 16, Iter: 20, Loss: 2.243826, Accuracy: 0.437500, FPS: 53.16559 img/s
Pass: 16, Iter: 21, Loss: 2.666715, Accuracy: 0.359375, FPS: 53.20634 img/s
Pass: 16, Iter: 22, Loss: 2.326929, Accuracy: 0.453125, FPS: 53.21169 img/s
Pass: 16, Iter: 23, Loss: 2.980473, Accuracy: 0.281250, FPS: 53.26024 img/s
Pass: 16, Iter: 24, Loss: 2.383747, Accuracy: 0.515625, FPS: 53.31412 img/s
Pass: 16, Iter: 25, Loss: 2.419901, Accuracy: 0.406250, FPS: 53.37037 img/s
Pass: 16, Iter: 26, Loss: 2.183330, Accuracy: 0.437500, FPS: 53.39082 img/s
Pass: 16, Iter: 27, Loss: 2.186817, Accuracy: 0.453125, FPS: 53.41679 img/s
Pass: 16, Iter: 28, Loss: 2.533564, Accuracy: 0.359375, FPS: 53.43456 img/s
Pass: 16, Iter: 29, Loss: 2.292397, Accuracy: 0.406250, FPS: 53.46317 img/s
Pass: 16, Iter: 30, Loss: 2.321457, Accuracy: 0.453125, FPS: 53.23949 img/s
Pass: 16, Iter: 31, Loss: 2.342121, Accuracy: 0.421875, FPS: 53.24486 img/s
Pass: 16, Iter: 32, Loss: 2.595043, Accuracy: 0.359375, FPS: 53.25930 img/s
Pass: 16, Iter: 33, Loss: 2.629114, Accuracy: 0.359375, FPS: 53.26818 img/s
Pass: 16, Iter: 34, Loss: 2.576834, Accuracy: 0.359375, FPS: 53.29205 img/s
Pass: 16, Iter: 35, Loss: 2.614713, Accuracy: 0.281250, FPS: 53.31555 img/s
Pass: 16, Iter: 36, Loss: 2.254075, Accuracy: 0.437500, FPS: 53.33864 img/s
Pass: 16, Iter: 37, Loss: 2.163029, Accuracy: 0.453125, FPS: 53.32685 img/s
Pass: 16, Iter: 38, Loss: 2.349159, Accuracy: 0.406250, FPS: 53.34469 img/s
Pass: 16, Iter: 39, Loss: 2.417690, Accuracy: 0.359375, FPS: 53.35366 img/s
Pass: 16, Iter: 40, Loss: 2.452331, Accuracy: 0.421875, FPS: 53.36753 img/s

we can find that training with mkl after 16 passes, loss value is about 3.8, but with mkldnn after 16 passes, loss value is about 2.5. 
Mkl test is run by paddlepaddle version:commit 4ed0b62476031f668d3797c664731b11b0055344 July 5
MKLDNN test is run by paddlepaddle intel internal branch.

I'm testing with latest paddlepaddle for mkl, will tell you results later. Thanks for your help.

**Comment by tensor-tang** [comment]
Thanks for you great work @bingyanghuang .
Please reopen it as needed.
