### ISSUE TITLE
关于integer_value_sequence的用法

### ISSUE THREAD

**Issue by chaos-dd** [PaddlePaddle/Paddle#11988]
integer_value_sequence会把同一个batch的值concat到一起吗？ 如下代码，我期望emb_idx是[1,2,3]
实际print出来是 [1,2,3,1,2,3,1,2,3]，看起来是把3个batch的concat到一起了。

```python
def train():
    def reader_fn():
        for i in range(0, 10000):
            yield [[1,2,3]]
    feeding = {"emb_idx":0}
    paddle.init(use_gpu=False, trainer_count=1)
    optimizer = paddle.optimizer.Adam(learning_rate=1e-4)
    data = paddle.layer.data(name="emb_idx",
            type=paddle.data_type.integer_value_sequence(10))
    parameters = paddle.parameters.create(data)
    trainer = paddle.trainer.SGD(data, parameters, optimizer)
    def event_handler(event):
        if isinstance(event, paddle.event.EndIteration):
            t=event.gm.getLayerOutputs('emb_idx')['emb_idx']['id']
            print t
    trainer.train(
        reader=paddle.batch(
                reader_fn
                , batch_size=3),
        num_passes=1,
        feeding=feeding,
        event_handler=event_handler)

```

**Comment by chengduoZH** [comment]
@chaos-dd 您设置的batch_size是3，注意到了吗？

**Comment by chaos-dd** [comment]
@chengduoZH  注意到了。我的疑问就是，为什么integer_value_sequence这个类型，会把一个batch的数据concat到一起呢？比如integer_value，应该是产出batch_size * 1的矩阵。integer_value_sequence为什么不是产出batch * emb_size的矩阵呢？   毕竟我理解integer_value_sequence 是一条样本里的一个field的数据是sequence的。

**Comment by chengduoZH** [comment]
> 为什么integer_value_sequence这个类型，会把一个batch的数据concat到一起呢？

这里不是将数据concat起来。
您输入数据的batch是3，所以每次输入的数据是三个[1,2,3]，在Paddle内部会将其表示为[1,2,3,1,2,3,1,2,3]，在处理的时候会将其看做三个样本（每条样本的长度也会在Paddle内部被记录）。

**Comment by chaos-dd** [comment]
@chengduoZH  明白了。我觉得这里表示成 batch*dim的矩阵是不是更清晰呢。。。为什么设计成了一维的呢

**Comment by chengduoZH** [comment]
因为一个batch里面数据的地址连续的。

**Comment by chengduoZH** [comment]
@chaos-dd 关于这个issue还有其他问题吗？

**Comment by ktlichkid** [comment]
Closed due to low activity. Please feel free to reopen it.
