### ISSUE TITLE
some experiment result on async training

### ISSUE THREAD

**Issue by jacquesqiao** [PaddlePaddle/Paddle#11999]
## 初步结论：
异步训练在不加decay的情况下，功能正常，有些情况收敛的比同步更快。

### 1. 文本分类。
测试结果：异步训练比同步训练收敛快，最终收敛准确度高一个百分点(有随机性)
https://github.com/PaddlePaddle/Paddle/issues/10180

### 2. Resnet
测试结果：可以正常收敛，效果和同步差不多

### 3. Ocr
测试结果：调小batch size(64 降到了14)可正常收敛，效果和同步差不多
![image](https://user-images.githubusercontent.com/3048612/42354855-418b2dda-80fc-11e8-8c70-372e6c5fd76b.png)

### 4. transformer
分析：因为transformer使用的learning rate decay的特殊性，启动的时候learning rate 几乎为0，所以用这个机制，在不支持learning rate decay的情况下，异步一直在用接近0的学习率进行优化，不收敛非常正常。
改成SGDOptimizer和固定学习率0.0004，同步和异步都可以收敛，但是相对于使用decay的最佳方案，收敛的都比较慢

下图是学习率曲线
![image](https://user-images.githubusercontent.com/3048612/42354861-4a1544f4-80fc-11e8-8e0c-3f8e17c021de.png)

### 5. language model.
下图是之前QA测试的结果，同步的时候loss先下降，后上升，然后保持不变；异步先下降，后上升，一直上升到比较大的值。

分析：经过分析是因为目前测试的language model已经严重过拟合了。同步模式下，训练到十几个pass之后，学习率被decay到接近0了(lr * 0.5^n,  n = pass_num)，所以loss不再上升，
而异步因为不支持decay，会一直上升，把同步模式的decay去掉，就和异步现象一样了。

![image](https://user-images.githubusercontent.com/3048612/42354865-5244f584-80fc-11e8-8acb-69cad6967d6c.png)

去掉同步的learning rate decay之后，同步的收敛情况，可以看到，先下降，然后逐步上升。
![image](https://user-images.githubusercontent.com/3048612/42355332-25730afc-80ff-11e8-930b-cebf4875e861.png)

语言模型同步和异步训练，loss下降情况。
![image](https://user-images.githubusercontent.com/3048612/42355383-7630d172-80ff-11e8-92ff-8c3818b1ab39.png)

语言模型，同步异步在测试机上的表现，随着训练进行，ppl还会持续上升(过拟合)
![image](https://user-images.githubusercontent.com/3048612/42355396-868645ac-80ff-11e8-8ecc-8a88aa0cf1ad.png)

## 下一步计划：
1. 所有测试和QA确认复现，由QA最终确认。
2. 异步训练支持learning rate decay，目前已有方案，大概需要一周时间实现(实现+测试效果)

**Comment by velconia** [comment]
Cool
