### ISSUE TITLE
将fastText产出的pretrain的word embedding装入首层报错

### ISSUE THREAD

**Issue by github-zj** [PaddlePaddle/Paddle#1199]
“Shared parameter "embeddings" does not have same size: 943400 vs. 1207552”
这是什么错误？
参考了：https://github.com/PaddlePaddle/Paddle/issues/490
写了write_parameter的转换，上述报错

**Comment by qingqing01** [comment]
这个问题看着像是配置中的embeding层的大小和用于初始化的embeding大小不等。 用于初始化的embeding的词典大小  和 配置中的词典大小、embeding维度一致吗？

**Comment by helinwang** [comment]
@github-zj 我先关闭这个issue，要是qingqing的回复没有解答你的问题请再把这个issue打开。
