### ISSUE TITLE
 Could not find a version that satisfies the requirement paddlepaddle

### ISSUE THREAD

**Issue by VictorZhang2014** [PaddlePaddle/Paddle#11993]
I am using Google Cloud Engine,  virtualenv, and installing paddlepaddle by pip, but it threw errors like below.

<img width="660" alt="wx20180705-194942 2x" src="https://user-images.githubusercontent.com/6853884/42321826-d615e226-808c-11e8-8e78-433121568f1b.png">

**Comment by velconia** [comment]
What is the result of this command:

```pip search paddlepaddle```

**Comment by chengduoZH** [comment]
@VictorZhang2014 Have you resolved this error?

**Comment by chengduoZH** [comment]
Closs this inactive issue, feel free to reopen for further discuss.
