### ISSUE TITLE
A probable memory leak bug on ProgramDesc

### ISSUE THREAD

**Issue by gmcather** [PaddlePaddle/Paddle#11991]
As mentioned in the title, there might be a memory leak bug in the Destructor of `ProgramDesc`. 

I can list an example. If you try to load model (load function: https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/fluid/inference/io.cc#L139 ) repeatedly, the memory continues increasing during the running time.  Because memory allocated by creating the ProgramDesc didn't free. 

Here's our temporary solution by freeing the leaked memory manually. More specifically, we clear memory of proto `p->Proto()->Clear();` when destructing the ProgramDesc.
```c
auto t_pdesc = paddle::inference::Load(*_exec, *_root_scope[i],
    program_desc_path, model_path);
    
ProgramDesc* pdesc_ptr = t_pdesc.release();
_program_desc = std::unique_ptr<ProgramDesc, std::function<void(ProgramDesc*)>>(
   pdesc_ptr,
   [](ProgramDesc* p) {
   p->Proto()->Clear();
   delete p;
    });
```

**Comment by chengduoZH** [comment]
@gmcather Thanks for your patience to check the source code. Do you have some experiments to show the memory leak bug on ProgramDesc?

This [line](https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/fluid/inference/io.cc#L139 ) does not produce memory leak. You can refer to the [`unique_ptr`'s usage](http://www.cplusplus.com/reference/memory/unique_ptr/?kw=unique_ptr).


> unique_ptr objects automatically delete the object they manage (using a deleter) as soon as they themselves are destroyed, or as soon as their value changes either by an assignment operation or by an explicit call to unique_ptr::reset.

**Comment by gmcather** [comment]
@chengduoZH Of course, the line you pointed out seems to be correct at the first glance, this is because the real problem is so well hidden. We made the mistake in taking it for granted that Google Protubuf wouldn't bring any memory leak problem. However, it actually did. So we must manually free the memory which comes with the using of google protubuf. This private variable (https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/fluid/framework/program_desc.h#L79) should be explicitly Cleared After the end of life circle of ProgramDesc.

**Comment by gmcather** [comment]
@chengduoZH As my experiment is so huge that it's difficult to be displayed here,  I strongly suggest you reproduce the problem by calling the load function repeatedly, and then you will find there's a memory leak bug.

**Comment by chengduoZH** [comment]
Thank you @gmcather 
But I could not reproduce the memory leak that you described. 
Can you tell me more detail information, such as in which model, how many times of calling `paddle::inference::Load`, how much memory is growing.
