### ISSUE TITLE
Remove the git tag in develop branch

### ISSUE THREAD

**Issue by velconia** [PaddlePaddle/Paddle#12004]
In Paddle repor, if we run

```
git checkout develop
git describe --tags --abbrev=0 --always HEAD
```
it will get ```v0.12.0``` now, because we had serveral tags in ```develop``` branch, this will make our distributed whl package to keep this version forever, I guess we should remove all the tags in ```develop```, like below

```
commit c816121d11f7aed2939c5b859423883ce8bab050 (tag: v0.12.0, origin/release/0.12.0)
Author: baiyf <baiyfbupt@gmail.com>
Date:   Thu Apr 26 19:02:22 2018 +0800

    optimized iou_similarity_op (#10231)

```

**Comment by panyx0718** [comment]
I know why it's on develop now. It's also on release/0.12.0

When I created release/0.12.0, I created a tag. That tag will show up on both develop and release/0.12.0. If no one apply further commits to release/0.12.0 and I don't update the tag,
the tag will keep showing up on develop and release/0.12.0

**Comment by velconia** [comment]
Thanks very much, I will make a special concern on ```develop``` branch later
