### ISSUE TITLE
使用fluid c++ api预测book中训练出来的模型出错

### ISSUE THREAD

**Issue by wuyan08** [PaddlePaddle/Paddle#12007]
通过book/01.fit_a_line/train.py训练出模型，使用fluid c++ api进行预测时，会报找不到__model__的错误。执行train.py后确实没有生成__model__文件，只生成了fc_0.b_0、fc_0.w_0、learning_rate_0、mean_0.tmp_0@GRAD这四个文件。

预测时的错误日志：
terminate called after throwing an instance of 'paddle::platform::EnforceNotMet'
  what():  Cannot open file ./data/model/paddle/fluid/fit_a_line/__model__ at [/home/paddlepaddle/Paddle/paddle/fluid/inference/io.cc:49]
PaddlePaddle Call Stacks: 
0       0x7f0c6ed73edap paddle::platform::EnforceNotMet::EnforceNotMet(std::__exception_ptr::exception_ptr, char const*, int) + 634
1       0x7f0c6ed6efe2p paddle::inference::ReadBinaryFile(std::string const&, std::string*) + 818
2       0x7f0c6ed710e7p paddle::inference::Load(paddle::framework::Executor*, paddle::framework::Scope*, std::string const&) + 215
3       0x7f0c6e43f92bp paddle::NativePaddlePredictor::Init(std::shared_ptr<paddle::framework::Scope>) + 843
4       0x7f0c6e44069ap std::unique_ptr<paddle::PaddlePredictor, std::default_delete<paddle::PaddlePredictor> > paddle::CreatePaddlePredictor<paddle::NativeConfig, (paddle::PaddleEngineKind)0>(paddle::NativeConfig const&) + 1802

**Comment by Superjomn** [comment]
models 里有一些模型的确缺少 `__model__` 这个文件 @qingqing01 @kuke

**Comment by luotao1** [comment]
https://github.com/PaddlePaddle/book/blob/develop/01.fit_a_line/train.py 这个使用的是high-level python api。 @panyx0718 请问这块要梳理下么？

@wuyan08 你先用 https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/fluid/tests/book/test_fit_a_line.py 。

**Comment by wuyan08** [comment]
ok，我先用test下的python脚本生成测试模型。

**Comment by wuyan08** [comment]
book中的例子什么时候可以支持fluid训练？

**Comment by luotao1** [comment]
#12682 已经修复了这个问题，book中的例子 @shippingwang 正在跟进中。

**Comment by shippingwang** [comment]
嗯 我正在做~

**Comment by lucywsq** [comment]
@wuyan08 您好，请问此issue的回复已经解决了您的问题吗？若已解决我们将于三日内关闭。若在关闭后您仍需跟进提问，可重新开启此问题，我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持!
