### ISSUE TITLE
使用develop分支上的docker build时，在用pip安装软件是总是超时，这块有没有什么好的解决办法？

### ISSUE THREAD

**Issue by wen-bo-yang** [PaddlePaddle/Paddle#1200]
总是在pip安装软件时超时，这里有没有什么其他解决办法？
<img width="1658" alt="2017-01-20 12 27 20" src="https://cloud.githubusercontent.com/assets/6229206/22118699/c41a34d6-deb3-11e6-98a6-9e9d8f244547.png">

**Comment by gangliao** [comment]
我没遇到这个问题。@jacquesqiao @wangkuiyi

**Comment by wen-bo-yang** [comment]
我是在家里，用自己的电脑build的，试过连用公司的vpn也会超时。

**Comment by ketra21** [comment]
类似问题可以设置超时时间`--default-timeout=100`解决，如下是例子：
pip install --no-cache-dir -i https://pypi.tuna.tsinghua.edu.cn/simple --default-timeout=100 paddlepaddle-gpu -U
