### ISSUE TITLE
paddle fluid 集群训练模式下异常退出

### ISSUE THREAD

**Issue by spencerlisp** [PaddlePaddle/Paddle#12019]
运行环境：
**paddle docker镜像：**
-    paddlepaddle/paddle:latest-gpu
-    paddlepaddle/paddle:latest-gpu-cuda8.0-cudnn5
尝试了两个都报错，并且通过版本打印，确定paddle版本为0.14.0

**任务调度和分布式训练**
基于k8s调度，起两个pod，每个pod内部先后启动ps_server，trainer.
其中ps_server的时候TRAINING_ROLE为PSERVER, trainer的时候为TRAINER。

**运行任务**
fit-a-line fluid版本
参考：http://paddlecloud.baidu-int.com/paddle/createJob中的demo示例。
并修改：
 t.transpile(
            optimize_ops,
            params_grads,
            trainer_id,
            pservers=pserver_endpoints,
            trainers=trainers)
为
 t.transpile(
            trainer_id,
            pservers=pserver_endpoints,
            trainers=trainers)

相关异常日志如下：

**trainer 1 异常日志：**
pure virtual method called
terminate called without an active exception
*** Aborted at 1530872135 (unix time) try "date -d @1530872135" if you are using GNU date ***
PC: @                0x0 (unknown)
*** SIGABRT (@0x5564ed10) received by PID 66 (TID 0x7f985c8b6700) from PID 1432677648; stack trace: ***
    @     0x7f985c494390 (unknown)
    @     0x7f985c0ee428 gsignal
    @     0x7f985c0f002a abort
    @     0x7f98184a084d __gnu_cxx::__verbose_terminate_handler()
    @     0x7f981849e6b6 (unknown)
    @     0x7f981849e701 std::terminate()
    @     0x7f981849f23f __cxa_pure_virtual
    @     0x7f980007bc46 grpc::Channel::~Channel()
    @     0x7f980007bcf9 grpc::Channel::~Channel()
    @     0x7f97ff243bb9 std::_Sp_counted_base<>::_M_release()
    @     0x7f980003da7e paddle::operators::distributed::GRPCClient::~GRPCClient()
    @     0x7f980003db91 paddle::operators::distributed::GRPCClient::~GRPCClient()
    @     0x7f9800045ada std::unique_ptr<>::~unique_ptr()
    @     0x7f985c0f2ff8 (unknown)
    @     0x7f985c0f3045 exit
    @     0x7f985c0d9837 __libc_start_main
    @           0x4933e9 _start
    @                0x0 (unknown)
Aborted

**trainer 0 异常日志：**
epoF0706 10:15:36.372784   103 grpc_client.cc:299] Get name:[fc_0.b_0], ep:[172.16.75.4:7164] meets grpc error:Socket closed
*** Check failure stack trace: ***
    @     0x7fa7b4739fcd  google::LogMessage::Fail()
    @     0x7fa7b473da7c  google::LogMessage::SendToLog()
    @     0x7fa7b4739af3  google::LogMessage::Flush()
    @     0x7fa7b473ef8e  google::LogMessageFatal::~LogMessageFatal()
    @     0x7fa7b54b2fd7  paddle::operators::distributed::GRPCClient::Proceed()
    @     0x7fa7ccaaec80  (unknown)
    @     0x7fa810a6f6ba  start_thread
    @     0x7fa8107a541d  clone
    @              (nil)  (unknown)

**Comment by typhoonzero** [comment]
这个 https://github.com/PaddlePaddle/Paddle/pull/11994 可以修复此问题。

**Comment by spencerlisp** [comment]
那这个patch什么时候会合入0.14.0？ 或者目前哪个版本能够稳定的支持fluid分布式，谢谢～

**Comment by typhoonzero** [comment]
这个报错目前不影响训练。把FLAGS_rpc_deadline设大点就行， 参考：https://github.com/PaddlePaddle/Paddle/issues/11710

这个报错会在训练完成后报，忽略掉就行。

**Comment by ktlichkid** [comment]
Closed due to low activity. Please feel free to reopen it.
