### ISSUE TITLE
paddle支持python3吗？

### ISSUE THREAD

**Issue by zishuaiz** [PaddlePaddle/Paddle#1201]
看paddle python源码中用的是python2，强烈建议用python3啊

**Comment by reyoung** [comment]
@zishuaiz Paddle写的时候，protobuf还没有3呢。不过Paddle目前链接的protobuf库是3.1

**Comment by wangkuiyi** [comment]
是说 Python 3 和 protobuf 3 有什么关系吗？看上去 Python 3 也可以支持 protobuf 2.x 的样子 https://pypi.python.org/pypi/python3-protobuf

**Comment by reyoung** [comment]
> @zishuaiz Paddle写的时候，protobuf还没有3呢。不过Paddle目前链接的protobuf库是3.1

抱歉，回复的时候看错了。。

python3目前不支持是因为Paddle内嵌了一个python的解释器，用了很多Python的C-API接口。这个会在将Paddle的新的API发布中解决。新的API会直接依赖Paddle的C-API。

**Comment by zishuaiz** [comment]
@reyoung 赞赞赞
度厂加油！

**Comment by jarvisqi** [comment]
Python2.X 都要停止支持了，Paddle还没有支持Python3

**Comment by zishuaiz** [comment]
这个问题貌似迟迟没有解决啊

**Comment by luotao1** [comment]
目前没有支持Python3的计划，暂时也没有排期https://github.com/PaddlePaddle/Paddle/issues/8981#issuecomment-372180743

**Comment by Aoseala** [comment]
不支持python3的话 ，paddle估计要凉了

**Comment by velconia** [comment]
Paddle Fluid 会在 0.15.0 发布python3的试用版, 1.0 发布正式版. 

这个 [issue](https://github.com/PaddlePaddle/Paddle/issues/12040) 记录了我们的工作;
