### ISSUE TITLE
paddle-onnx使用出错：OP[lookup_table] is not supported in the converter!

### ISSUE THREAD

**Issue by xiaolv3366** [PaddlePaddle/Paddle#12018]
如题，使用paddle-onnx转换Paddle Fluid -> ONNX模型，出现如下错误：
OP[lookup_table] is not supported in the converter!

**Comment by JiayiFeng** [comment]
onnx中没有lookup_table对应的op，因此converter不支持转换包含lookup_table_op的模型。

**Comment by xiaolv3366** [comment]
paddle-onnx转换连自家的Paddle Fluid模型都不支持？这不奇怪吗！

**Comment by JiayiFeng** [comment]
onnx不是paddle的项目，是由facebook和微软主导的。onnx本身还不支持任何lookup table的操作，转换器自然也就无法实现这类操作的转换。
onnx目前支持的操作列表：https://github.com/onnx/onnx/blob/master/docs/Operators.md

**Comment by ktlichkid** [comment]
Closed due to low activity. Please feel free to reopen it.
