### ISSUE TITLE
mac下面源码安装出现问题

### ISSUE THREAD

**Issue by gschen** [PaddlePaddle/Paddle#12026]
➜  Paddle git:(develop) pip install build/python/dist/*.whl
paddlepaddle-0.12.0-cp27-cp27mu-linux_x86_64.whl is not a supported wheel on this platform.

编译安装后出现上述问题。

![image](https://user-images.githubusercontent.com/839140/42411162-b5f31812-8229-11e8-9030-ed5c57665491.png)

**Comment by newdimitri** [comment]
macos不能使用pip安装，要编译安装

**Comment by JiabinYang** [comment]
请问您是使用docker进行源码编译的么

**Comment by newdimitri** [comment]
我直接下的docker，用web映射运行的book

**Comment by newdimitri** [comment]
你是哪个部的啊

**Comment by lucywsq** [comment]
您好，此issue在近一个月内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题，我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持!
