### ISSUE TITLE
编译错误：找不到framework.pb.h

### ISSUE THREAD

**Issue by wuyan08** [PaddlePaddle/Paddle#12033]
Git clone出最新的Paddle源码，编译时提示没有framework.pb.h，需要进入到framework.proto所在目录，手动调用下protoc，编译出framework.pb.h后才可继续后面的编译。

Docker环境：docker.paddlepaddlehub.com/paddle:latest-dev
gcc: 5.4.0
编译选项：
cmake -DCMAKE_BUILD_TYPE=Release -DWITH_AVX=OFF -DWITH_MKL=OFF -DWITH_GPU=OFF -DWITH_C_API=OFF -DWITH_FLUID_ONLYON -DWITH_CONTRIB=ON -DWITH_PYTHON=OFF -DWITH_SWIG_PY=OFF -DWITH_DISTRIBUTE=OFF -DWITH_TESTING=ON ..

错误提示：
In file included from /home/paddlepaddle-2/Paddle/paddle/fluid/framework/operator.h:25:0,
                 from /home/paddlepaddle-2/Paddle/paddle/fluid/platform/init.cc:19:
/home/paddlepaddle-2/Paddle/paddle/fluid/framework/attribute.h:23:49: fatal error: paddle/fluid/framework/framework.pb.h: No such file or directory
compilation terminated.
paddle/fluid/platform/CMakeFiles/device_context.dir/build.make:86: recipe for target 'paddle/fluid/platform/CMakeFiles/device_context.dir/init.cc.o' failed
make[2]: *** [paddle/fluid/platform/CMakeFiles/device_context.dir/init.cc.o] Error 1
CMakeFiles/Makefile2:2200: recipe for target 'paddle/fluid/platform/CMakeFiles/device_context.dir/all' failed
make[1]: *** [paddle/fluid/platform/CMakeFiles/device_context.dir/all] Error 2
Makefile:116: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by luotao1** [comment]
请进入build目录编译
```
cd Paddle
mkdir build
cd build
cmake -DCMAKE_BUILD_TYPE=Release ...
```

**Comment by wuyan08** [comment]
是在build目录下编译的.

![cb9ef58d312be1d7d4847ee412ec7cc1](https://user-images.githubusercontent.com/36987150/42448836-1a175906-83b1-11e8-984c-e65bf8e6d9d2.JPG)

**Comment by luotao1** [comment]
1. `git log`看下commitid是什么？

2. https://github.com/PaddlePaddle/Paddle/blob/436bb4500b6c5610025a3c7ee10ef30e34b00d1f/paddle/fluid/platform/CMakeLists.txt#L49 加一个`framework_proto`:
`place framework_proto eigen3 eigen3 stringpiece cpu_helper ${GPU_CTX_DEPS} ${MKLDNN_CTX_DEPS}`

**Comment by wuyan08** [comment]
λ dbc125f6bdd3 /home/paddlepaddle-2/Paddle/build {develop} git log
commit 436bb4500b6c5610025a3c7ee10ef30e34b00d1f
Merge: 11146a0 05ffc13
Author: Tao Luo <luotao02@baidu.com>
Date:   Mon Jul 9 11:19:02 2018 +0800

    Merge pull request #11699 from pzelazko-intel/pzelazko/workaround-for-missing-mklnn-kernels
    
    workaround for no MKLDNN kernel

commit 11146a067a6712095166aff479b577022f562ce5
Merge: 20ecc9f 637acb3
Author: Qiao Longfei <qiaolongfei@baidu.com>
Date:   Mon Jul 9 11:13:40 2018 +0800

    Merge pull request #12001 from jacquesqiao/update-dist-lookup-table-design-doc
    
    Update dist lookup table design doc

**Comment by typhoonzero** [comment]
https://github.com/PaddlePaddle/Paddle/pull/12020 should fix the build

**Comment by JiabinYang** [comment]
您好，此issue在近一个月内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题，我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持!
