### ISSUE TITLE
float division by zero ,testdata exists in my path

### ISSUE THREAD

**Issue by almostlove** [PaddlePaddle/Paddle#12036]
http://10.76.58.21:8900/fileview.html?path=/home/disk1/normandy/maybach/app-user-20180709141052-6693/

路径里有数据的～为什么会down失败然后 division by zero ～～求教

**Comment by Superjomn** [comment]
可以截个图吗，找不到出错的地方

**Comment by Superjomn** [comment]
![image](https://user-images.githubusercontent.com/328693/42437573-16f9e7dc-8390-11e8-88b6-e89720df726d.png)

@typhoonzero 这个你之前碰到过吗

**Comment by typhoonzero** [comment]
应该是trainer.test得到的`num_samples`(test的batch_size)为0，麻烦先检查下test使用的数据是否正确。

**Comment by almostlove** [comment]
已解决，感谢。
