### ISSUE TITLE
多机训练中出现pure virtual method called。

### ISSUE THREAD

**Issue by kolinwei** [PaddlePaddle/Paddle#12038]
End pass 119, train_loss 1.46156001091, train_acc1 0.657408475876, train_acc5 0.855218946934, test_loss 1.24483448955, test_acc1 0.701642628205, test_acc5 0.899799679487
pure virtual method called
terminate called without an active exception
*** Aborted at 1531063311 (unix time) try "date -d @1531063311" if you are using GNU date ***
PC: @                0x0 (unknown)
*** SIGABRT (@0x395e) received by PID 14686 (TID 0x7f7d309e2700) from PID 14686; stack trace: ***
    @     0x7f7d305bd390 (unknown)
    @     0x7f7d30217428 gsignal
    @     0x7f7d3021902a abort
    @     0x7f7cef40a84d __gnu_cxx::__verbose_terminate_handler()
    @     0x7f7cef4086b6 (unknown)
    @     0x7f7cef408701 std::terminate()
    @     0x7f7cef40923f __cxa_pure_virtual
    @     0x7f7cdd58f696 grpc::Channel::~Channel()
    @     0x7f7cdd58f749 grpc::Channel::~Channel()
    @     0x7f7cdc7ef319 std::_Sp_counted_base<>::_M_release()
    @     0x7f7cdd5537ee paddle::operators::distributed::GRPCClient::~GRPCClient()
    @     0x7f7cdd553901 paddle::operators::distributed::GRPCClient::~GRPCClient()
    @     0x7f7cdd55a60a std::unique_ptr<>::~unique_ptr()
    @     0x7f7d3021bff8 (unknown)
    @     0x7f7d3021c045 exit
    @     0x7f7d30202837 __libc_start_main
    @           0x4933e9 _start
    @                0x0 (unknown)

**Comment by typhoonzero** [comment]
@velconia is working on this already.

**Comment by velconia** [comment]
Here is the [pr](https://github.com/PaddlePaddle/Paddle/pull/11994)

**Comment by kolinwei** [comment]
问题还会出现

**Comment by typhoonzero** [comment]
dup: https://github.com/PaddlePaddle/Paddle/issues/11851
