### ISSUE TITLE
Add support for Python 3.x

### ISSUE THREAD

**Issue by velconia** [PaddlePaddle/Paddle#12040]
Currently we only support Python 2.7, but we should support Python 3.

**Comment by velconia** [comment]
According this user survey, we should support python3 now.

![image](https://user-images.githubusercontent.com/1979255/42435376-ea0d27a4-8388-11e8-9a19-b25557ee715b.png)

From Github, I collected these issues reported from users recently:

[PaddlePaddle什么时候支持Python3.x](https://github.com/PaddlePaddle/Paddle/issues/11425)

[呼吁paddle能够尽快支持python3](https://github.com/PaddlePaddle/Paddle/issues/11262)

[python3.6 pip 无法安装](https://github.com/PaddlePaddle/Paddle/issues/11241)

[Paddle支持Python3吗？](https://github.com/PaddlePaddle/Paddle/issues/10581)


From google search engine, you can get these results and feel the urgency need from our users:

[Google result of python3 need for paddle](https://www.google.com.hk/search?q=paddle+python3)

**Comment by velconia** [comment]
@guochaorong @typhoonzero, seems that we need a timeline for this requirement.

Here is the [first issue](https://github.com/tensorflow/tensorflow/issues/1#issuecomment-155371120) for tensorflow supporting python 3.x, we could refer to their working method

**Comment by velconia** [comment]
[Here](http://python3porting.com/strategies.html) is the strategies of porting py2 to py3 and the difference between the ways.

[Here](https://docs.python.org/3.5/howto/pyporting.html) is the recommend way to porting py2 to py3.

**Comment by typhoonzero** [comment]
python3 seems done, closing for now.

**Comment by mirekphd** [comment]
Can you please upload Python 3 wheels to PyPi? Currently there are only Python 2.7 versions...
(see. e.g. https://pypi.org/project/paddlepaddle-gpu/0.15.0.post97/#files )

**Comment by velconia** [comment]
Python3 wheels have been uploaded to PyPi, see: https://pypi.org/project/paddlepaddle/#files

**Comment by clhne** [comment]
@velconia 
Now, only support [python3.5](https://pypi.org/project/paddlepaddle/#files)
But, when to support python3.6 ?

**Comment by velconia** [comment]
@clhne 

Change from python2.7 to python3.5 need a lot of work, so we have spent about 2 months on it. 

Howerver, change from python3.5 to python3.6 and python3.7 will NOT be that tough, so python3.6 and python3.7 will be supported soon.

**Comment by clhne** [comment]
@velconia 
Ok.
But is it supported Python3.6 now?

**Comment by PengboLiu** [comment]
looking forward to supporting py3.6

**Comment by jthestness** [comment]
+1

It doesn't look like there is a pip build for Python 3.6. Would love to have Python 3.6 support, so we can install with our other frameworks! Thanks!

**Comment by velconia** [comment]
We are about to support Python3.6 and Python3.7, so this issue is reopened.

Python3.6 and Python3.7 support is coming soon

**Comment by velconia** [comment]
Python3.x (3.5+) is supported now. You could get all related wheel packages in [here](https://pypi.org/project/paddlepaddle/#files), close this issue.
