### ISSUE TITLE
通过pip安装的PaddlePaddle在 import paddle.fluid 报找不到 libmkldnn.so 或 libmklml_intel.so 

### ISSUE THREAD

**Issue by winter1988** [PaddlePaddle/Paddle#12041]
通过pip安装的PaddlePaddle在 import paddle.fluid 报找不到 libmkldnn.so 或 libmklml_intel.so 
但是
http://www.paddlepaddle.org/docs/develop/documentation/zh/faq/build_and_install/index_cn.html#permalink-15-10-pip-paddlepaddle-import-paddle-fluid-libmkldnn-so-libmklml_intel-so
第十个问题 的新变种
在 /usr/local/lib  下找不到如题的两个
。so 文件
谁能解答一下

**Comment by luotao1** [comment]
如果pip安装在`/usr/local/bin`下，这几个so在`/usr/local/lib`下。因此，可以找一下这几个so安装在哪儿，然后export LD_LIBRARY_PATH即可。

**Comment by sanwushuosi** [comment]
在我用virtualenv安装的paddle环境里面，这个lib在./paddlepaddle0.14/lib这目录里。
我往virtualenv的active添加了
export LD_LIBRARY_PATH="xxxxx/paddlepaddle0.14/lib:$LD_LIBRARY_PATH"
后，就解决了

**Comment by JiabinYang** [comment]
您好，此issue在近一个月内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题，
我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持!
