### ISSUE TITLE
paddle v2进行capi预测时，dense_vector_sequence的定义问题

### ISSUE THREAD

**Issue by vincewangnsn** [PaddlePaddle/Paddle#12045]
![image](https://user-images.githubusercontent.com/40789621/42440419-45275952-8398-11e8-9dfd-146bd35bf433.png)
![image](https://user-images.githubusercontent.com/40789621/42440536-9a5df0ca-8398-11e8-96db-b464f35d8613.png)

￼input是paddle.data_type.dense_vector_sequence的对应C++的是浮点型稠密矩阵，原始数据dense_vector_sequence里存的是n个200维的dense_vector，请问在c++中应该怎么写？￼
我看height是一次预测接受的样本数目，如果是一次输入一条训练样本，那么height=1，width= n*200，还是height = n,width = 200,谢谢~

**Comment by Superjomn** [comment]
应该是 height = n 的情况；或者两种都可以试试。
