### ISSUE TITLE
paddlepaddle是否存在输入一个分布来计算交叉熵的Cost layer？

### ISSUE THREAD

**Issue by wanghainan89** [PaddlePaddle/Paddle#12044]
当前paddlepaddle的交叉熵cost function似乎只能通过输入一个分类标号来完成交叉熵的计算，如softmax输出[0.1, 0.9] label==1,则计算[0.1, 0.9]与[0,1]之间的交叉熵。我想问一下是否能直接输入一个分布而不是一个类标号来完成交叉熵的计算？如softmax输出[0.1, 0.9]，而目标分布是[0.2, 0.8]，现在我想获得[0.1, 0.9]与[0.2, 0.8]之间的交叉熵来作为loss。请问paddlepaddle如何处理这种情况？
谢谢

**Comment by wanghainan89** [comment]
本质上来说，我是想完成一个逻辑回归（并不是用逻辑回归来完成分类），但是在试图获得逻辑回归的cost的时候遇见了这个困难

**Comment by jacquesqiao** [comment]
fluid的cross_entropy可以支持你的需求，只需要设置soft_label为True即可http://paddlepaddle.org/docs/0.14.0/api/fluid/en/layers.html#cross-entropy

**Comment by wanghainan89** [comment]
paddle V2版本现在不能支持哈？

**Comment by jacquesqiao** [comment]
看了下，V2没暴露出这个接口

**Comment by wanghainan89** [comment]
好的，多谢了
