### ISSUE TITLE
Mac系统下编译PaddlePaddle，报错use of undeclared identifier 'openblas_set_num_threads'

### ISSUE THREAD

**Issue by wzzju** [PaddlePaddle/Paddle#12057]
## 关于blas报错
按照PaddlePaddle 0.14.0 release版本的官方文档说明，本人于Mac OS系统进行本机编译PaddlePaddle的0.14.0 release版本。因为官方文档上的编译依赖说明中未写明编译前必须安装openblas或MKL或其他blas库，且明确注明说“其他的依赖软件，会自动在编译时下载”，故而本人编译前没有事先安装一些blas库。在此种场景下，PaddlePaddle也能够编译成功，然而，安装后运行“import paddle.fluid as fluid”会报错，具体如下：
<img width="1193" alt="image" src="https://user-images.githubusercontent.com/17102274/42487492-deb9cab4-8433-11e8-8044-ce53ea02363e.png">
报错显示“To be implemented.”查看blas.h文件代码第60行附近如下：
<img width="599" alt="77a50503e8a674f8b9d3defa8fb1284c" src="https://user-images.githubusercontent.com/17102274/42487618-5db40866-8434-11e8-9d09-e86f66c9d1bd.png">

可以发现此错误是由未使用任何blas库所致，查看cmake命令的输出可知，编译未安装openblas或mkl时使用的是cblas。

## 安装openblas
在Mac上安装openblas后，重新编译，依旧出现编译错误，报错信息如下：
![52fc29e8a6c0e37a0de084dc096c2494](https://user-images.githubusercontent.com/17102274/42487728-d72441ac-8434-11e8-942d-6e4682fcee7c.png)
本人怀疑要么是PaddlePaddle对编译所依赖的openblas版本有具体要求，要么就是openblas在linux和mac下的接口定义是不同的？毕竟openblas_set_num_threads是个函数，但是为什么会报错为未定义的标志符呢？

<img width="557" alt="1b508c6d19d515bfdbe227a72ad54e72" src="https://user-images.githubusercontent.com/17102274/42487816-47d4f86a-8435-11e8-8be7-4fdbecea7fb8.png">

**Comment by tensor-tang** [comment]
>查看cmake命令的输出可知，编译未安装openblas或mkl时使用的是cblas。

可以先贴一下你的cmake option 以及log信息。

如果系统不带Openblas，paddle是会自动下载并编译的。

**Comment by jacquesqiao** [comment]
这个问题是因为默认找到系统自带的cblas.h 而这个cblas.h是不对的，需要显示设置
```
-DOPENBLAS_INC_DIR=/usr/local/Cellar/openblas/0.2.19_1/include/
```

编译流程需要优化一下，做一下check

**Comment by tensor-tang** [comment]
如果是Openblas找的不对，可以尝试用环境变量解决下

https://github.com/PaddlePaddle/Paddle/blob/938920c894ac853ebfa0e374df4db8955e8c0a31/cmake/cblas.cmake#L29

另外这个路径是哪里看到的？
/usr/local/Cellar/openblas/0.2.19_1/include/

**Comment by wzzju** [comment]
@tensor-tang @jacquesqiao 谢谢两位老师，问题已经解决，使用cmake命令时加上编译选项`-DOPENBLAS_INC_DIR=/usr/local/Cellar/openblas/[电脑上安装的openblas版本号]/include/`即可消除该报错信息。

**Comment by chasingegg** [comment]
Anyone knows if we use system's default blas implementation, how to set num_threads?
