### ISSUE TITLE
paddle python3支持排期

### ISSUE THREAD

**Issue by guochaorong** [PaddlePaddle/Paddle#12050]
考虑到用户对python3的期待，https://github.com/PaddlePaddle/Paddle/issues/12040
同时对python2的依赖，采用兼容python2和python3的方案
 
 
**具体实施步骤**
1.	搭建python3 ci job， 使用manylinux 的docker镜像，部署安装python3 环境， 比如python3.5。 设置python 3.5 环境变量 以及 python 和pip 默认指向python3 和pip3， 执行单测。
 
2.	分别对python中的这些模块及单测进行 to3 兼容（调用2to3 工具等 ， 对代码进行兼容性修改）
          'paddle.utils',
          'paddle.dataset',
          'paddle.reader',
          'paddle.fluid',
          'paddle.fluid.layers',
           'paddle.fluid.proto',
          'paddle.fluid.proto.profiler',
          'paddle.fluid.transpiler',
          'paddle.fluid.transpiler.details
 
    如果还需要支持v2版本：
    packages+=['paddle.proto',
               'paddle.trainer',
               'paddle.trainer_config_helpers',
               'paddle.v2',
               'paddle.v2.master',
               'paddle.v2.plot',
               'paddle.v2.reader',
               'paddle.v2.dataset',
               'py_paddle']
        
3.	调试上面失败的环节， 依赖包的变更， 单测fail等。并对新进的代码兼容， 直到整个python3 ci job流程通过。

4.	后续开发需要兼容python2 和python3 （ci保障）

**实施排期**

7月18号，ci job搭建完毕 （wuyi、 chaorong）
8月20， 脚本兼容完毕 （qiyang、 chaorong）， python3 ci job告警打开。
8月30，ci job 整体通过（qiyang、chaorong），
9月15，python3 whl包发布

**Comment by velconia** [comment]
感谢, 辛苦超容老师

**Comment by guochaorong** [comment]
太客气了~
 这个按照你的建议列的时间排期， 可以根据目前的问题和进展更新下~

**Comment by panyx0718** [comment]
1. 需要厂内的环境和镜像支持python3，paddle RD可以使用厂内环境调试python3。
2. 新增了python3的CI，相关的新增机器需求是否有考虑到？感觉是要加倍？（上次讨论机器好像忘记考虑这个问题了）

**Comment by guochaorong** [comment]
嗯嗯，  ci job 总时间变长了。 
专门拿几台来做python3的， 可能需要增加好几台。如果4卡机器，python2 和 python3 的docker镜像能并行跑， 似乎可以少加点机器？ 

厂内这个等我们这边镜像 ready ，给他们个模板，让他们搞一下。。他们这段时间都在弄整个公司虚拟化的事情， 也可以先自己弄个镜像放到镜像仓库， 我们v100的cuda9 镜像也是自己搞的。

**Comment by guochaorong** [comment]
1虚4 ， 阡陌那边不建议做， 这周交了我2台4卡的。 我先试试
如果真能1虚4， 似乎也不需要几个8卡机器啦~

**Comment by yeyupiaoling** [comment]
@guochaorong 
看来PaddlePaddle支持Python3指日可待了。

**Comment by velconia** [comment]
[We have supported Python3 installation](https://github.com/PaddlePaddle/Paddle/issues/12040) now. PaddlePaddle for Python3 could be installed via ```pip3 install paddlepaddle``` or ```pip3 install paddlepaddle-gpu```. 

Seems this issue could be closed.
