### ISSUE TITLE
 MemoryHandle.cpp:52] Check failed: size != 0  allocate 0

### ISSUE THREAD

**Issue by Emma-Ding** [PaddlePaddle/Paddle#12064]
报错如下，请帮忙排查，线下能跑通，线上就无法跑通

Tue Jul 10 15:37:25 2018[1,0]<stderr>:[WARNING 2018-07-10 15:37:25,823 networks.py:1438] `outputs` routine try to calculate network's inputs and outputs order. It might not work well.Please see follow log carefully.
Tue Jul 10 15:37:25 2018[1,0]<stderr>:[INFO 2018-07-10 15:37:25,824 networks.py:1466] The input order is [AgeId, GenderId, MultiPreqIds, QueryProfile, WordProfile, TitleProfile, TotalProfile, CmatchProfile, MtIdProfile, Cmatch, Ua, MtId, Title, Brand, Word, label, qleft]
Tue Jul 10 15:37:25 2018[1,0]<stderr>:[INFO 2018-07-10 15:37:25,824 networks.py:1472] The output order is [__cost_0__, __cost_1__, __regression_cost_0__]
Tue Jul 10 15:37:27 2018[1,0]<stderr>:[INFO 2018-07-10 15:37:27,095 dataprovider.py:27] hook
Tue Jul 10 15:37:27 2018[1,0]<stderr>:[INFO 2018-07-10 15:37:27,145 dataprovider.py:46] dict_size is 21198
Tue Jul 10 15:37:27 2018[1,0]<stderr>:[INFO 2018-07-10 15:37:27,145 dataprovider.py:47] schema_pos_size is 552
Tue Jul 10 15:37:27 2018[1,0]<stderr>:[INFO 2018-07-10 15:37:27,145 dataprovider.py:48] schema_output_size is 58
Tue Jul 10 15:37:27 2018[1,0]<stderr>:[INFO 2018-07-10 15:37:27,145 dataprovider.py:49] lda_ad_size is 127
Tue Jul 10 15:37:27 2018[1,0]<stderr>:[INFO 2018-07-10 15:37:27,145 dataprovider.py:50] lda_news_size is 127
Tue Jul 10 15:37:27 2018[1,0]<stderr>:[INFO 2018-07-10 15:37:27,146 dataprovider.py:27] hook
Tue Jul 10 15:37:27 2018[1,0]<stderr>:[INFO 2018-07-10 15:37:27,195 dataprovider.py:46] dict_size is 21198
Tue Jul 10 15:37:27 2018[1,0]<stderr>:[INFO 2018-07-10 15:37:27,195 dataprovider.py:47] schema_pos_size is 552
Tue Jul 10 15:37:27 2018[1,0]<stderr>:[INFO 2018-07-10 15:37:27,195 dataprovider.py:48] schema_output_size is 58
Tue Jul 10 15:37:27 2018[1,0]<stderr>:[INFO 2018-07-10 15:37:27,195 dataprovider.py:49] lda_ad_size is 127
Tue Jul 10 15:37:27 2018[1,0]<stderr>:[INFO 2018-07-10 15:37:27,195 dataprovider.py:50] lda_news_size is 127
Tue Jul 10 15:37:32 2018[1,1]<stderr>:F0710 15:37:32.315852  7698 MemoryHandle.cpp:52] Check failed: size != 0  allocate 0 bytes
Tue Jul 10 15:37:32 2018[1,0]<stderr>:F0710 15:37:32.322885  4834 MemoryHandle.cpp:52] Check failed: size != 0  allocate 0 bytes
Tue Jul 10 15:37:32 2018[1,0]<stderr>:*** Check failure stack trace: ***
Tue Jul 10 15:37:32 2018[1,0]<stderr>:F0710 15:37:32.323173  4807 MemoryHandle.cpp:52] Check failed: size != 0  allocate 0 bytesF0710 15:37:32.323606  4815 MemoryHandle.cpp:52]

**Comment by seiriosPlus** [comment]
是fluid的还是v2的代码

**Comment by seiriosPlus** [comment]
检查一下输入数据， 怀疑传入了空值或者长度为0的数据， 导致在申请内存的时候出现错误。

**Comment by seiriosPlus** [comment]
调小trainer_count
