### ISSUE TITLE
官方Demo: Image Classification，用CPU训练，这是不收敛吗？

### ISSUE THREAD

**Issue by hwcn** [PaddlePaddle/Paddle#1207]
基本环境：
Server：IBM system X server CPU（32 cores）
OS: CentOS 7 
Python 2.7
PaddlePaddle   v 0.9.0  release (Compile CPU only version from source code)
CBLAS:     OpenBlas

train.sh稍微改了一下：
set -e
config=vgg_16_cifar.py
output=./cifar_vgg_model
log=train.log

paddle train \
--config=$config \
--dot_period=10 \
--log_period=100 \
--test_all_data_in_one_period=1 \
--use_gpu=0 \
--trainer_count=32 \
--num_passes=300 \
--save_dir=$output \
2>&1 | tee $log

训练结果是这样的：
这是不收敛吗？该怎么调？只取了一部分日志，谢谢各位了。
.........I0120 09:40:38.375778 42576 TrainerInternal.cpp:182]  Pass=0 Batch=391 samples=50000 AvgCost=2.28196 Eval: classification_error_evaluator=0.84386 
.........I0120 09:58:33.392508 42576 TrainerInternal.cpp:182]  Pass=1 Batch=391 samples=50000 AvgCost=2.02242 Eval: classification_error_evaluator=0.78108 
.........I0120 10:16:25.745831 42576 TrainerInternal.cpp:182]  Pass=2 Batch=391 samples=50000 AvgCost=2.02981 Eval: classification_error_evaluator=0.78592 
.........I0120 10:34:05.210327 42576 TrainerInternal.cpp:182]  Pass=3 Batch=391 samples=50000 AvgCost=1.96686 Eval: classification_error_evaluator=0.7667 
.........I0120 10:51:51.905078 42576 TrainerInternal.cpp:182]  Pass=4 Batch=391 samples=50000 AvgCost=1.93706 Eval: classification_error_evaluator=0.7503 
.........I0120 11:09:37.912906 42576 TrainerInternal.cpp:182]  Pass=5 Batch=391 samples=50000 AvgCost=1.89019 Eval: classification_error_evaluator=0.72914 
.........I0120 11:27:45.914955 42576 TrainerInternal.cpp:182]  Pass=6 Batch=391 samples=50000 AvgCost=1.85504 Eval: classification_error_evaluator=0.69998 
.........I0120 11:45:52.886119 42576 TrainerInternal.cpp:182]  Pass=7 Batch=391 samples=50000 AvgCost=1.79014 Eval: classification_error_evaluator=0.66748 
.........I0120 12:03:44.760459 42576 TrainerInternal.cpp:182]  Pass=8 Batch=391 samples=50000 AvgCost=1.72443 Eval: classification_error_evaluator=0.63188 
.........I0120 12:21:42.505465 42576 TrainerInternal.cpp:182]  Pass=9 Batch=391 samples=50000 AvgCost=1.67007 Eval: classification_error_evaluator=0.6008
.........I0120 12:57:40.879541 42576 TrainerInternal.cpp:182]  Pass=11 Batch=391 samples=50000 AvgCost=1.60237 Eval: classification_error_evaluator=0.56378 
.........I0120 16:01:24.059942 42576 TrainerInternal.cpp:182]  Pass=21 Batch=391 samples=50000 AvgCost=1.46927 Eval: classification_error_evaluator=0.4902 
.........I0120 19:05:08.228250 42576 TrainerInternal.cpp:182]  Pass=31 Batch=391 samples=50000 AvgCost=1.51718 Eval: classification_error_evaluator=0.50558 
.........I0120 22:09:29.269179 42576 TrainerInternal.cpp:182]  Pass=41 Batch=391 samples=50000 AvgCost=1.57499 Eval: classification_error_evaluator=0.5246 
.........I0121 01:12:34.591846 42576 TrainerInternal.cpp:182]  Pass=51 Batch=391 samples=50000 AvgCost=1.57144 Eval: classification_error_evaluator=0.52724 
.........I0121 04:16:31.359561 42576 TrainerInternal.cpp:182]  Pass=61 Batch=391 samples=50000 AvgCost=1.68175 Eval: classification_error_evaluator=0.57412 
.........I0121 07:19:46.639513 42576 TrainerInternal.cpp:182]  Pass=71 Batch=391 samples=50000 AvgCost=1.80195 Eval: classification_error_evaluator=0.63002 
.........I0121 10:28:13.282104 42576 TrainerInternal.cpp:182]  Pass=81 Batch=391 samples=50000 AvgCost=1.84321 Eval: classification_error_evaluator=0.64668

**Comment by qingqing01** [comment]
下面是是曾经CPU训练的部分log，使用4个线程，Pass=2时，训练集错误率已达到37.372%。

```
I1230 10:08:25.090476 21249 Util.cpp:154] commandline: /home/xxx/paddle/bin/../opt/paddle/bin/paddle_trainer --config=vgg_16_cifar.py --dot_period=10 --log_period=100 --use_gpu=0 --trainer_count=4 --num_passes=300 --save_dir=./cifar_vgg_model
...

.........I1230 11:32:06.467403 21249 TrainerInternal.cpp:181]  Pass=2 Batch=391 samples=50000 AvgCost=1.07486 Eval: classification_error_evaluator=0.37672
I1230 11:40:02.065742 21249 Tester.cpp:115]  Test samples=50000 cost=0.944215 Eval: classification_error_evaluator=0.32084
```

看您的log里面使用了`trainer_count=32`个线程，`batch_size = 128` 时，每个线程只分到了4个样本。而这个模型本身用了BatchNorm，我觉得可能和这个有关系。您可以减少trainer_count个数试下。

**Comment by hwcn** [comment]
换成4个线程了，好像有效果，等我再多训练几次再贴结果。谢谢！

**Comment by helinwang** [comment]
看起来是解决问题了，我先关闭这个issue，@hwcn要是有问题请再把这个issue打开。
