### ISSUE TITLE
训练模型时候显示初始化化参数后，返回了一个killed是什么原因？

### ISSUE THREAD

**Issue by zxprog** [PaddlePaddle/Paddle#12072]
![qq](https://user-images.githubusercontent.com/23354372/42505955-00059006-8473-11e8-91b9-01c2c862a0ea.png)

**Comment by yuanxiangxie** [comment]
同遇到这个问题，求问楼主解决了吗？

**Comment by zxprog** [comment]
这是由于内存溢出导致的，我是在虚拟机里运行的，一开始给的1G，后来给了2G就好了

**Comment by yuanxiangxie** [comment]
嗯，感谢楼主
