### ISSUE TITLE
Mac OS系统下直接本机编译PaddlePaddle“踩坑”记录

### ISSUE THREAD

**Issue by wzzju** [PaddlePaddle/Paddle#12078]
# <center>Mac OS系统下直接本机编译PaddlePaddle“踩坑”记录</center>

> 文档声明：编译过程参照官网文档（Fluid 0.14.0）。硬件环境为MacBook Pro，操作系统版本为10.13.5 (17F77)。

## 问题1

基于Docker容器编译PaddlePaddle与本机上直接编译PaddlePaddle，所使用的编译执行命令是不一样的，但是官网仅仅给出了基于Docker容器编译PaddlePaddle所执行的命令。

##### 建议文档对应处修改为如下类似内容：

基于Docker容器编译PaddlePaddle，需要执行：

```bash

# 1. 获取源码

git clone https://github.com/PaddlePaddle/Paddle.git

cd Paddle

# 2. 可选步骤：源码中构建用于编译PaddlePaddle的Docker镜像

docker build -t paddle:dev .

# 3. 执行下面的命令编译CPU-Only的二进制

docker run -it -v $PWD:/paddle -e "WITH_GPU=OFF" -e "WITH_TESTING=OFF" paddlepaddle/paddle_manylinux_devel:cuda8.0_cudnn5 bash -x /paddle/paddle/scripts/paddle_build.sh build

# 4. 或者也可以使用为上述可选步骤构建的镜像（必须先执行第2步）

docker run -it -v $PWD:/paddle -e "WITH_GPU=OFF" -e "WITH_TESTING=OFF" paddle:dev

```

直接在本机上编译PaddlePaddle，需要执行：

```bash

# 1. 使用virtualenvwrapper创建python虚环境并将工作空间切换到虚环境

mkvirtualenv paddle-venv

workon paddle-venv

# 2. 获取源码

git clone https://github.com/PaddlePaddle/Paddle.git

cd Paddle

# 3. 执行下面的命令编译CPU-Only的二进制

mkdir build && cd build

cmake .. -DWITH_GPU=OFF -DWITH_TESTING=OFF

make -j$(nproc)

```

## 问题2
![image](https://user-images.githubusercontent.com/17102274/42515239-e24be824-848d-11e8-9f3d-3baf156dcea8.png)
![image](https://user-images.githubusercontent.com/17102274/42515246-e6f7c2d0-848d-11e8-853a-7d7401e4650f.png)

##### 解决方法：
```bash
pip install wheel
brew install protobuf@3.1
pip install protobuf==3.1.0
```
##### 执行`pip install protobuf==3.1.0`时报错：

![image](https://user-images.githubusercontent.com/17102274/42515286-fb7a7b76-848d-11e8-931a-a7f61bd6374b.png)

##### 解决方法：
```bash
easy_install -U six 
pip install protobuf==3.1.0
```
## 问题3
![image](https://user-images.githubusercontent.com/17102274/42515304-0bd7012e-848e-11e8-966f-946361ac7a56.png)

##### 解决方法：
```bash
brew install wget
```
## 问题4
![image](https://user-images.githubusercontent.com/17102274/42515324-1bd9c020-848e-11e8-8934-d7da5fc1f090.png)

##### 解决方法：
修改CMake编译命令，打开`WITH_FLUID_ONLY`编译选项，修改后编译命令如下：
```bash
cmake .. -DWITH_FLUID_ONLY=ON -DWITH_GPU=OFF -DWITH_TESTING=OFF
```
## 问题5
![image](https://user-images.githubusercontent.com/17102274/42515350-28c055ce-848e-11e8-9b90-c294b375d8a4.png)

##### 解决方法一：
修改`paddle/fluid/platform/CMakeFiles/profiler_py_proto.dir/build.make`内容的第60行~第62行内容，原内容如下(划线部分为需要修改的地方)：
![image](https://user-images.githubusercontent.com/17102274/42673761-6a70defe-869f-11e8-9377-0b7854b62ee6.png)

修改后如下(划线部分为需要修改的地方)：
![image](https://user-images.githubusercontent.com/17102274/42673808-a8fd128c-869f-11e8-8206-464a63211c20.png)

##### 解决方法二：
将CMake版本降级到3.4及以下，故而最终的CMake版本控制范围为：`3.2=<CMake<=3.4`。目前，官网文档上只写了CMake版本需要大于等于3.2，还应该强调不能使用CMake太新的版本，即可将CMake使用版本范围声明为：`3.2=<CMake<=3.4`。
## 问题6

![image](https://user-images.githubusercontent.com/17102274/42515402-453cc0d4-848e-11e8-9a03-a579ea8e4d2d.png)
##### 解决方法：
```bash
# 上面编译的是develop分支，此时Generating build/.timestamp这一步涉及的代码还在修改中。
```
接下来通过执行如下命令将分支切换到`0.14.0`进行编译:
```bash
cd Paddle
git checkout -b 0.14.0 origin/release/0.14.0
cd build &&  rm -rf *
cmake .. -DWITH_FLUID_ONLY=ON -DWITH_GPU=OFF -DWITH_TESTING=OFF
make -j4
```
## 编译成功后结果如下：
![image](https://user-images.githubusercontent.com/17102274/42515418-4fb71e56-848e-11e8-81c6-da2a5553a27a.png)

## 问题7——运行PaddlePaddle出错
使用`pip install build/python/dist/*.whl`命令安装PaddlePaddle后，
测试运行PaddlePaddle时出错，错误信息如下：

![image](https://user-images.githubusercontent.com/17102274/42515444-5a9e9a42-848e-11e8-8e07-6caa10a99fd9.png)
##### 解决方法：
卸载paddlepaddle，安装openblas，重新编译安装。
```bash
pip uninstall paddlepaddle
cd Paddle/build && rm -rf *
brew install openblas
cmake .. -DWITH_FLUID_ONLY=ON -DWITH_GPU=OFF -DWITH_TESTING=OFF
make -j4
```

## 问题8——重新编译时报错

![image](https://user-images.githubusercontent.com/17102274/42515461-64f36c34-848e-11e8-86df-2aa0aea8e530.png)

##### 解决方法：
执行cmake命令时加上编译选项`-DOPENBLAS_INC_DIR=/usr/local/Cellar/openblas/0.3.1/include/`，具体如下：
```bash
cd Paddle/build && rm -rf *
cmake .. -DWITH_FLUID_ONLY=ON -DWITH_GPU=OFF -DWITH_TESTING=ON -DOPENBLAS_INC_DIR=/usr/local/Cellar/openblas/0.3.1/include/
time make -j4
```
## 最终编译结果
![image](https://user-images.githubusercontent.com/17102274/42515484-6f9bdb26-848e-11e8-9d3a-72f3179f9284.png)

##### 安装PaddlePaddle并运行`test_fit_a_line.py` 程序:
```bash
pip install build/python/dist/*.whl
python python/paddle/fluid/tests/book/test_fit_a_line.py
```
## 运行结果
![image](https://user-images.githubusercontent.com/17102274/42515501-7831d02e-848e-11e8-8192-1e14bf7645ab.png)
## 总结
Mac OS系统下编译PaddlePaddle需要事先安装好`wheel`、`protobuf`、`wget`、`openblas`等软件，而一个全新等Mac OS系统上这些软件可能均未安装，因此在官方文档中应该明确指出Mac OS系统下编译PaddlePaddle依赖`wheel`、`protobuf`、`wget`、`openblas`等软件，且要指出这些软件在Mac OS下不会自动安装，需要使用者手动安装。对于CMake等要求，目前官网文档上只写了CMake版本需要大于等于3.2，还应该强调不能使用CMake太新的版本，即可将CMake使用版本范围声明为：`3.2=<CMake<=3.4`。

## 参考资料
* [PaddlePaddle使用文档](http://www.paddlepaddle.org/docs/0.14.0/documentation/fluid/zh/new_docs/beginners_guide/install/install_doc.html#permalink-4--macos-paddlepaddle)

* [paddle源码编译（osx）报各种module找不到的问题 #280](https://github.com/PaddlePaddle/Paddle/issues/280)

* [Mac 编译Paddle报错*** target pattern contains no `%'. Stop.](https://github.com/PaddlePaddle/Paddle/issues/6197)

**Comment by northeast250** [comment]
非常有用啊！我跟你踩得坑一样啊！中途更新了cmake，然后重新安装了openblas，而且还是用的手机流量。

**Comment by wzzju** [comment]
@northeast250 谢谢支持，在Mac系统下编译遇到的“坑”也欢迎在这个issue下补充哈～

**Comment by DDDivano** [comment]
怒赞！

**Comment by taoziliu** [comment]
想让更多人看到！

**Comment by wangtao169447** [comment]
训练api_train_v2.py的时候提示ImportError: No module named v2

**Comment by JiabinYang** [comment]
感谢 @wzzju 的记录，这里的问题我们已经在新版本中基本解决，欢迎大家使用[最新版本](http://paddlepaddle.org)的paddlepaddle
