### ISSUE TITLE
 LightNetwork.cpp:379] Check failed: connect(sockfd, (sockaddr *)&serv_addr, sizeof(serv_addr)) >= 0 ERROR connecting

### ISSUE THREAD

**Issue by Emma-Ding** [PaddlePaddle/Paddle#12082]
与https://github.com/PaddlePaddle/Paddle/issues/2495  遇到了同样的问题，看了之后对集群配置做了如下更改，
<img width="865" alt="2018-07-11 9 55 30" src="https://user-images.githubusercontent.com/22070158/42546746-4a1d9c14-84f1-11e8-919e-ea0d428db800.png">

结果还是报错同样的错误F0711 09:43:56.800041  5309 LightNetwork.cpp:379] Check failed: connect(sockfd, (sockaddr *)&serv_addr, sizeof(serv_addr)) >= 0 ERROR connecting to 10.87.139.37: Connection refused [111]

**Comment by ktlichkid** [comment]
#2955 #6499 可以先试试这里的几个方法。另外麻烦提供更详细的训练log. 此类问题最好还是联系JIRA处理。

**Comment by kuke** [comment]
Closed due to inactivity.
