### ISSUE TITLE
使用docker编译paddlepaddle book时报错

### ISSUE THREAD

**Issue by wzzju** [PaddlePaddle/Paddle#12089]
根据[如何贡献文档](http://www.paddlepaddle.org/docs/develop/documentation/fluid/zh/dev/write_docs_cn.html)介绍的使用docker构建book指南，在执行完`docker run -it -p 8000:8000 -v `pwd`:/var/content paddlepaddle/paddlepaddle.org:latest`命令后，访问`http://localhost:8000`并点击`book`选项卡报错，报错信息如下：
<img width="740" alt="image" src="https://user-images.githubusercontent.com/17102274/42556543-81f8adea-851e-11e8-96a3-b9e949193cd2.png">

<img width="816" alt="image" src="https://user-images.githubusercontent.com/17102274/42556617-c14fd3e2-851e-11e8-9ef6-74f5da7b947d.png">

**Comment by newdimitri** [comment]
在新的仓库中重新拉一下docker镜像

**Comment by wzzju** [comment]
好的,谢谢. @newdimitri
