### ISSUE TITLE
Port current fluid code and pybind11 to python3

### ISSUE THREAD

**Issue by velconia** [PaddlePaddle/Paddle#12094]
This is the first job of [Add py3 support](https://github.com/PaddlePaddle/Paddle/issues/12040)

**Comment by velconia** [comment]
Accroding to this [issue](https://github.com/linkchecker/linkchecker/pull/40), PaddlePaddle Python part depends on the LinkChecker, but LinkChecker doesn't support Python3 yet, we should replace it in our repo

**Comment by luotao1** [comment]
@velconia If documents are not generated from Paddle repo, we could remove LinkChecker. @shanyi15 Are documents not generated from Paddle repo now?
