### ISSUE TITLE
ParallelExecutor CPU 单机和多机精度验证

### ISSUE THREAD

**Issue by seiriosPlus** [PaddlePaddle/Paddle#12096]
## ParallelExecutor CPU 单机和多机精度验证
验证模型： text_classification
验证代码： https://github.com/seiriosPlus/fluid_benchmark/blob/master/text_classification/train_high_api.py

### 单机: 
CPU_NUM = 4
OPTIMIZER = SGD
BatchSzie = 160
PARALLEL_EXECUTOR = False
Epoch: 0, Step: 0, Time: 0.691313028336, Loss: 0.758364140987, Accuracy: 0.0
Epoch: 0, Step: 1, Time: 0.669323921204, Loss: 0.755404293537, Accuracy: 0.0
Epoch: 0, Step: 2, Time: 0.492468118668, Loss: 0.75151693821, Accuracy: 0.0
Epoch: 0, Step: 3, Time: 0.634160995483, Loss: 0.74986153841, Accuracy: 0.0
Epoch: 0, Step: 4, Time: 0.559371948242, Loss: 0.746825933456, Accuracy: 0.0
Epoch: 0, Step: 5, Time: 0.65730381012, Loss: 0.744488358498, Accuracy: 0.0
Epoch: 0, Step: 6, Time: 0.57714009285, Loss: 0.740698099136, Accuracy: 0.0
Epoch: 0, Step: 7, Time: 0.565196990967, Loss: 0.737674236298, Accuracy: 0.0
Epoch: 0, Step: 8, Time: 0.670403957367, Loss: 0.735484838486, Accuracy: 0.0
Epoch: 0, Step: 9, Time: 0.60733795166, Loss: 0.732566833496, Accuracy: 0.0
Epoch: 0, Step: 10, Time: 0.618324041367, Loss: 0.72943675518, Accuracy: 0.0
Epoch: 0, Step: 11, Time: 0.654896020889, Loss: 0.726955294609, Accuracy: 0.0
Epoch: 0, Step: 12, Time: 0.606182098389, Loss: 0.724970698357, Accuracy: 0.0
Epoch: 0, Step: 13, Time: 0.535058021545, Loss: 0.720089435577, Accuracy: 0.0
Epoch: 0, Step: 14, Time: 0.530606985092, Loss: 0.717955291271, Accuracy: 0.0
Epoch: 0, Step: 15, Time: 0.55975317955, Loss: 0.716057658195, Accuracy: 0.0
Epoch: 0, Step: 16, Time: 0.57083106041, Loss: 0.713347136974, Accuracy: 0.0
Epoch: 0, Step: 17, Time: 0.583375930786, Loss: 0.710104584694, Accuracy: 0.0
Epoch: 0, Step: 18, Time: 0.625988960266, Loss: 0.70750695467, Accuracy: 0.0
Epoch: 0, Step: 19, Time: 0.561584949493, Loss: 0.705342590809, Accuracy: 0.00625000009313

- - - - - 
CPU_NUM = 4
OPTIMIZER = SGD
BatchSzie = 40 (相当于每个线程是40的BatchSize)
PARALLEL_EXECUTOR = True
Epoch: 0, Step: 0, Time: 0.363101959229, Loss: 0.758364200592, Accuracy: 0.0
Epoch: 0, Step: 1, Time: 0.276148080826, Loss: 0.755404353142, Accuracy: 0.0
Epoch: 0, Step: 2, Time: 0.26346206665, Loss: 0.751516878605, Accuracy: 0.0
Epoch: 0, Step: 3, Time: 0.298815965652, Loss: 0.74986153841, Accuracy: 0.0
Epoch: 0, Step: 4, Time: 0.269979953766, Loss: 0.746825933456, Accuracy: 0.0
Epoch: 0, Step: 5, Time: 0.294218063354, Loss: 0.744488418102, Accuracy: 0.0
Epoch: 0, Step: 6, Time: 0.295897960663, Loss: 0.740698099136, Accuracy: 0.0
Epoch: 0, Step: 7, Time: 0.291954994202, Loss: 0.737674236298, Accuracy: 0.0
Epoch: 0, Step: 8, Time: 0.388696908951, Loss: 0.735484838486, Accuracy: 0.0
Epoch: 0, Step: 9, Time: 0.277570962906, Loss: 0.732566773891, Accuracy: 0.0
Epoch: 0, Step: 10, Time: 0.279649972916, Loss: 0.729436695576, Accuracy: 0.0
Epoch: 0, Step: 11, Time: 0.276800870895, Loss: 0.7269551754, Accuracy: 0.0
Epoch: 0, Step: 12, Time: 0.282086849213, Loss: 0.724970698357, Accuracy: 0.0
Epoch: 0, Step: 13, Time: 0.264585971832, Loss: 0.720089375973, Accuracy: 0.0
Epoch: 0, Step: 14, Time: 0.255345106125, Loss: 0.717955350876, Accuracy: 0.0
Epoch: 0, Step: 15, Time: 0.262812137604, Loss: 0.716057658195, Accuracy: 0.0
Epoch: 0, Step: 16, Time: 0.294218063354, Loss: 0.713347196579, Accuracy: 0.0
Epoch: 0, Step: 17, Time: 0.286861896515, Loss: 0.710104644299, Accuracy: 0.0
Epoch: 0, Step: 18, Time: 0.310491085052, Loss: 0.707507014275, Accuracy: 0.0
Epoch: 0, Step: 19, Time: 0.30881690979, Loss: 0.705342590809, Accuracy: 0.00625000009313

>  多机：
CPU_NUM = 4 
Trainer*Pserver = 1*1
BatchSize = 40 (相当于每个线程是40的BatchSize)

数据详情：
Epoch: 0, Step: 0, Time: 0.645524024963, Loss: 0.758364200592, Accuracy: 0.0
Epoch: 0, Step: 1, Time: 0.452592849731, Loss: 0.716291725636, Accuracy: 0.0
Epoch: 0, Step: 2, Time: 0.413733005524, Loss: 0.688405871391, Accuracy: 0.75
Epoch: 0, Step: 3, Time: 0.470826148987, Loss: 0.663906574249, Accuracy: 0.75
Epoch: 0, Step: 4, Time: 0.439845085144, Loss: 0.643519043922, Accuracy: 0.75
Epoch: 0, Step: 5, Time: 0.439889907837, Loss: 0.622890949249, Accuracy: 0.75
Epoch: 0, Step: 6, Time: 0.444410085678, Loss: 0.604803562164, Accuracy: 0.75
Epoch: 0, Step: 7, Time: 0.403778076172, Loss: 0.588454723358, Accuracy: 0.75
Epoch: 0, Step: 8, Time: 0.483130931854, Loss: 0.567219376564, Accuracy: 0.75
Epoch: 0, Step: 9, Time: 0.452316999435, Loss: 0.553434789181, Accuracy: 0.75
Epoch: 0, Step: 10, Time: 0.46025800705, Loss: 0.534703552723, Accuracy: 0.75
Epoch: 0, Step: 11, Time: 0.422217130661, Loss: 0.514850497246, Accuracy: 0.75
Epoch: 0, Step: 12, Time: 0.421497106552, Loss: 0.499343156815, Accuracy: 0.75
Epoch: 0, Step: 13, Time: 0.402488946915, Loss: 0.487519323826, Accuracy: 0.75
Epoch: 0, Step: 14, Time: 0.384223937988, Loss: 0.476423442364, Accuracy: 0.75
Epoch: 0, Step: 15, Time: 0.41647195816, Loss: 0.457093030214, Accuracy: 0.75
Epoch: 0, Step: 16, Time: 0.443618059158, Loss: 0.445936471224, Accuracy: 0.75
Epoch: 0, Step: 17, Time: 0.42789888382, Loss: 0.433399736881, Accuracy: 0.75
Epoch: 0, Step: 18, Time: 0.473331212997, Loss: 0.420853078365, Accuracy: 0.75
Epoch: 0, Step: 19, Time: 0.466829061508, Loss: 0.409123629332, Accuracy: 0.75

目前1x1的精度无法对齐，原因正在查找中。

**Comment by luotao1** [comment]
related #11984

**Comment by chengduoZH** [comment]
@seiriosPlus 做的这组实验显示用CPU多线程ParallelExecutor和Executor得到的loss基本是对齐。
因为high level API里面对reader加了一个decorator，导致每个线程的batch size就是reader这只的batch size。
https://github.com/PaddlePaddle/Paddle/blob/e568acbee2f90a296054f54f71cbdc31e9cc1fdb/python/paddle/fluid/trainer.py#L532-L538

**Comment by seiriosPlus** [comment]
验证了 @Yancey1989 的 #12120 ，结果如下：
多机：
CPU_NUM = 4
Trainer * Pserver = 1 * 1
BatchSize = 40 (相当于每个线程是40的BatchSize)

Epoch: 0, Step: 0, Time: 35.2061178684, Loss: 0.758364200592, Accuracy: 0.0, Test Loss: 0.694377968788, Test Accuracy: 0.5
Epoch: 0, Step: 1, Time: 35.0572519302, Loss: 0.755404353142, Accuracy: 0.0, Test Loss: 0.694211413193, Test Accuracy: 0.5
Epoch: 0, Step: 2, Time: 35.3907709122, Loss: 0.751516878605, Accuracy: 0.0, Test Loss: 0.694053212261, Test Accuracy: 0.5
Epoch: 0, Step: 3, Time: 36.1886260509, Loss: 0.74986153841, Accuracy: 0.0, Test Loss: 0.693902818203, Test Accuracy: 0.5
Epoch: 0, Step: 4, Time: 36.4673368931, Loss: 0.746825933456, Accuracy: 0.0, Test Loss: 0.69376071291, Test Accuracy: 0.5
Epoch: 0, Step: 5, Time: 35.9189600945, Loss: 0.744488418102, Accuracy: 0.0, Test Loss: 0.693626162529, Test Accuracy: 0.5
Epoch: 0, Step: 6, Time: 36.5941262245, Loss: 0.740698099136, Accuracy: 0.0, Test Loss: 0.693499660492, Test Accuracy: 0.5
Epoch: 0, Step: 7, Time: 36.600135088, Loss: 0.737674236298, Accuracy: 0.0, Test Loss: 0.693381149292, Test Accuracy: 0.5
Epoch: 0, Step: 8, Time: 36.6638920307, Loss: 0.735484838486, Accuracy: 0.0, Test Loss: 0.693270359993, Test Accuracy: 0.5
Epoch: 0, Step: 9, Time: 36.9587979317, Loss: 0.732566773891, Accuracy: 0.0, Test Loss: 0.693167249107, Test Accuracy: 0.5
Epoch: 0, Step: 10, Time: 36.7882978916, Loss: 0.729436695576, Accuracy: 0.0, Test Loss: 0.693071754742, Test Accuracy: 0.5
Epoch: 0, Step: 11, Time: 36.6152598858, Loss: 0.7269551754, Accuracy: 0.0, Test Loss: 0.692983698273, Test Accuracy: 0.5
Epoch: 0, Step: 12, Time: 36.2591760159, Loss: 0.724970698357, Accuracy: 0.0, Test Loss: 0.692903227425, Test Accuracy: 0.499920000076
Epoch: 0, Step: 13, Time: 36.6880331039, Loss: 0.720089375973, Accuracy: 0.0, Test Loss: 0.692830232239, Test Accuracy: 0.499920000115
Epoch: 0, Step: 14, Time: 36.3916630745, Loss: 0.717955350876, Accuracy: 0.0, Test Loss: 0.692764881516, Test Accuracy: 0.499960000116
Epoch: 0, Step: 15, Time: 36.5529630184, Loss: 0.716057658195, Accuracy: 0.0, Test Loss: 0.692706660748, Test Accuracy: 0.500120000118
Epoch: 0, Step: 16, Time: 36.3077409267, Loss: 0.713347196579, Accuracy: 0.0, Test Loss: 0.692655705929, Test Accuracy: 0.50048000024
Epoch: 0, Step: 17, Time: 36.7172749043, Loss: 0.710104644299, Accuracy: 0.0, Test Loss: 0.692611847401, Test Accuracy: 0.500840001136
Epoch: 0, Step: 18, Time: 36.6404490471, Loss: 0.707507014275, Accuracy: 0.0, Test Loss: 0.692575182629, Test Accuracy: 0.502760002381
Epoch: 0, Step: 19, Time: 36.4271299839, Loss: 0.705342590809, Accuracy: 0.00625000009313, Test Loss: 0.692545964527, Test Accuracy: 0.507560003638

目前 1x1 跟单机的ParallelExecutorn能够保持一致， 后续会进行多个节点的验证。

**Comment by seiriosPlus** [comment]
目前验证了多机1X1的情况，还有4x2的情况在验证中.

**Comment by seiriosPlus** [comment]
多机：
CPU_NUM = 4
Trainer * Pserver = 4 * 2
BatchSize = 10 (相当于每个线程是10的BatchSize)

取Trainer_id = 0 的数据如下：
Epoch: 0, Step: 0, Time: 46.4841001034, Loss: 0.759456932545, Accuracy: 0.0, Test Loss: 0.694622479868, Test Accuracy: 0.5
Epoch: 0, Step: 1, Time: 44.0505151749, Loss: 0.749677538872, Accuracy: 0.0, Test Loss: 0.694474376512, Test Accuracy: 0.5
Epoch: 0, Step: 2, Time: 45.2129030228, Loss: 0.74602663517, Accuracy: 0.0, Test Loss: 0.694334262252, Test Accuracy: 0.5
Epoch: 0, Step: 3, Time: 44.5908379555, Loss: 0.744451284409, Accuracy: 0.0, Test Loss: 0.694201724672, Test Accuracy: 0.5
Epoch: 0, Step: 4, Time: 43.5845909119, Loss: 0.741384029388, Accuracy: 0.0, Test Loss: 0.69407733171, Test Accuracy: 0.5
Epoch: 0, Step: 5, Time: 44.3482508659, Loss: 0.739122390747, Accuracy: 0.0, Test Loss: 0.693960511041, Test Accuracy: 0.5
Epoch: 0, Step: 6, Time: 43.9955949783, Loss: 0.735454916954, Accuracy: 0.0, Test Loss: 0.693851473188, Test Accuracy: 0.5
Epoch: 0, Step: 7, Time: 43.9169800282, Loss: 0.73179346323, Accuracy: 0.0, Test Loss: 0.693750136423, Test Accuracy: 0.5
Epoch: 0, Step: 8, Time: 44.2999920845, Loss: 0.729355037212, Accuracy: 0.0, Test Loss: 0.693656350255, Test Accuracy: 0.5
Epoch: 0, Step: 9, Time: 43.4975268841, Loss: 0.727340459824, Accuracy: 0.0, Test Loss: 0.693569982958, Test Accuracy: 0.5
Epoch: 0, Step: 10, Time: 43.4207708836, Loss: 0.722418069839, Accuracy: 0.0, Test Loss: 0.693491055584, Test Accuracy: 0.49995999999
Epoch: 0, Step: 11, Time: 45.0141952038, Loss: 0.721349358559, Accuracy: 0.0, Test Loss: 0.693419311595, Test Accuracy: 0.49995999999
Epoch: 0, Step: 12, Time: 43.5045480728, Loss: 0.719966053963, Accuracy: 0.0, Test Loss: 0.693355010986, Test Accuracy: 0.499919999981
Epoch: 0, Step: 13, Time: 44.5677270889, Loss: 0.714942574501, Accuracy: 0.0, Test Loss: 0.693297820592, Test Accuracy: 0.499879999971
Epoch: 0, Step: 14, Time: 44.878330946, Loss: 0.712553679943, Accuracy: 0.0, Test Loss: 0.693248114538, Test Accuracy: 0.499959999955
Epoch: 0, Step: 15, Time: 44.6381950378, Loss: 0.711360991001, Accuracy: 0.0, Test Loss: 0.693205334997, Test Accuracy: 0.499919999933
Epoch: 0, Step: 16, Time: 43.9651148319, Loss: 0.708251714706, Accuracy: 0.0, Test Loss: 0.693169727111, Test Accuracy: 0.500239999768
Epoch: 0, Step: 17, Time: 43.3345329762, Loss: 0.706681966782, Accuracy: 0.0, Test Loss: 0.693140937448, Test Accuracy: 0.501119999257
Epoch: 0, Step: 18, Time: 44.4996461868, Loss: 0.702792704105, Accuracy: 0.0, Test Loss: 0.693119056106, Test Accuracy: 0.502279997766
Epoch: 0, Step: 19, Time: 45.0364561081, Loss: 0.700524628162, Accuracy: 0.0500000007451, Test Loss: 0.693104332709, Test Accuracy: 0.506759998915

测试结果和单机的parallel_executor对比误差在 万分之10 以内， 结果符合预期。

**Comment by Yancey0623** [comment]
@seiriosPlus Can we close this issue?

**Comment by seiriosPlus** [comment]
We can not close it at present, I am doing more experiments to verify the ```loss``` and ```accuracy```.

**Comment by seiriosPlus** [comment]
目前测试，多机和单机在parallel_executor运行上测试 ```accuracy ``` 符合预期， 但是训练的 ```loss``` 误差在 千分之2左右， ```accuracy ``` 误差较大， 正在排查。

**Comment by seiriosPlus** [comment]
多机：
CPU_NUM = 4
Trainer * Pserver = 4 * 1
BatchSize = 10 (相当于每个线程是10的BatchSize)
单机的BatchSize = 40

训练精度数据：
ITEA: 0_0, STANDALONE: 0.0, CLUSER MEAN: 0.0, ERROR: 0.0
ITEA: 0_1, STANDALONE: 0.0, CLUSER MEAN: 0.0, ERROR: 0.0
ITEA: 0_2, STANDALONE: 0.0, CLUSER MEAN: 0.0, ERROR: 0.0
ITEA: 0_3, STANDALONE: 0.0, CLUSER MEAN: 0.0, ERROR: 0.0
ITEA: 0_4, STANDALONE: 0.0, CLUSER MEAN: 0.0, ERROR: 0.0
ITEA: 0_5, STANDALONE: 0.0, CLUSER MEAN: 0.0, ERROR: 0.0
ITEA: 0_6, STANDALONE: 0.0, CLUSER MEAN: 0.0, ERROR: 0.0
ITEA: 0_7, STANDALONE: 0.0, CLUSER MEAN: 0.0, ERROR: 0.0
ITEA: 0_8, STANDALONE: 0.0, CLUSER MEAN: 0.0, ERROR: 0.0
ITEA: 0_9, STANDALONE: 0.0, CLUSER MEAN: 0.0, ERROR: 0.0
ITEA: 0_10, STANDALONE: 0.0, CLUSER MEAN: 0.0, ERROR: 0.0
ITEA: 0_11, STANDALONE: 0.0, CLUSER MEAN: 0.0, ERROR: 0.0
ITEA: 0_12, STANDALONE: 0.0, CLUSER MEAN: 0.0, ERROR: 0.0
ITEA: 0_13, STANDALONE: 0.0, CLUSER MEAN: 0.0, ERROR: 0.0
ITEA: 0_14, STANDALONE: 0.0, CLUSER MEAN: 0.0, ERROR: 0.0
ITEA: 0_15, STANDALONE: 0.0, CLUSER MEAN: 0.0, ERROR: 0.0
ITEA: 0_16, STANDALONE: 0.0, CLUSER MEAN: 0.0, ERROR: 0.0
ITEA: 0_17, STANDALONE: 0.0, CLUSER MEAN: 0.0, ERROR: 0.0
ITEA: 0_18, STANDALONE: 0.0, CLUSER MEAN: 0.0, ERROR: 0.0
ITEA: 0_19, STANDALONE: 0.00625000009313, CLUSER MEAN: 0.00625000009313, ERROR: 4.99947305777e-15
ITEA: 0_20, STANDALONE: 0.0500000007451, CLUSER MEAN: 0.0500000012107, ERROR: 4.65625003832e-10
ITEA: 0_21, STANDALONE: 0.0562499985099, CLUSER MEAN: 0.0562500017694, ERROR: 3.25947499547e-09
ITEA: 0_22, STANDALONE: 0.28125, CLUSER MEAN: 0.28125, ERROR: 0.0
ITEA: 0_23, STANDALONE: 0.41249999404, CLUSER MEAN: 0.41250000149, ERROR: 7.45000000579e-09
ITEA: 0_24, STANDALONE: 0.612500011921, CLUSER MEAN: 0.612500026822, ERROR: 1.49012500117e-08
ITEA: 0_25, STANDALONE: 0.793749988079, CLUSER MEAN: 0.793749973178, ERROR: 1.49012500117e-08
ITEA: 0_26, STANDALONE: 0.925000011921, CLUSER MEAN: 0.924999982118, ERROR: 2.98025000234e-08
ITEA: 0_27, STANDALONE: 0.975000023842, CLUSER MEAN: 0.975000008941, ERROR: 1.49012500117e-08

训练LOSS数据：
ITEA: 0_0, STANDALONE: 0.758364200592, CLUSER MEAN: 0.758364215493, ERROR: 1.49012500117e-08
ITEA: 0_1, STANDALONE: 0.755404353142, CLUSER MEAN: 0.755404293537, ERROR: 5.96047500245e-08
ITEA: 0_2, STANDALONE: 0.751516878605, CLUSER MEAN: 0.751516908407, ERROR: 2.98022498901e-08
ITEA: 0_3, STANDALONE: 0.74986153841, CLUSER MEAN: 0.749861553311, ERROR: 1.49014999229e-08
ITEA: 0_4, STANDALONE: 0.746825933456, CLUSER MEAN: 0.746825903654, ERROR: 2.98017500677e-08
ITEA: 0_5, STANDALONE: 0.744488418102, CLUSER MEAN: 0.744488343596, ERROR: 7.4505750014e-08
ITEA: 0_6, STANDALONE: 0.740698099136, CLUSER MEAN: 0.740698143839, ERROR: 4.47034999018e-08
ITEA: 0_7, STANDALONE: 0.737674236298, CLUSER MEAN: 0.737674221397, ERROR: 1.49014999229e-08
ITEA: 0_8, STANDALONE: 0.735484838486, CLUSER MEAN: 0.735484823585, ERROR: 1.49012500117e-08
ITEA: 0_9, STANDALONE: 0.732566773891, CLUSER MEAN: 0.732566803694, ERROR: 2.98027499346e-08
ITEA: 0_10, STANDALONE: 0.729436695576, CLUSER MEAN: 0.729436695576, ERROR: 2.49911202843e-13
ITEA: 0_11, STANDALONE: 0.7269551754, CLUSER MEAN: 0.726955235004, ERROR: 5.96045000023e-08
ITEA: 0_12, STANDALONE: 0.724970698357, CLUSER MEAN: 0.724970713258, ERROR: 1.49007499672e-08
ITEA: 0_13, STANDALONE: 0.720089375973, CLUSER MEAN: 0.720089405775, ERROR: 2.98019998679e-08
ITEA: 0_14, STANDALONE: 0.717955350876, CLUSER MEAN: 0.717955321074, ERROR: 2.98022501122e-08
ITEA: 0_15, STANDALONE: 0.716057658195, CLUSER MEAN: 0.716057628393, ERROR: 2.98019999789e-08
ITEA: 0_16, STANDALONE: 0.713347196579, CLUSER MEAN: 0.713347196579, ERROR: 2.50022225146e-13
ITEA: 0_17, STANDALONE: 0.710104644299, CLUSER MEAN: 0.710104584694, ERROR: 5.96049999357e-08
ITEA: 0_18, STANDALONE: 0.707507014275, CLUSER MEAN: 0.707506969571, ERROR: 4.47042499685e-08
ITEA: 0_19, STANDALONE: 0.705342590809, CLUSER MEAN: 0.705342590809, ERROR: 1.11022302463e-16
ITEA: 0_20, STANDALONE: 0.701672017574, CLUSER MEAN: 0.701671987772, ERROR: 2.98019999789e-08
ITEA: 0_21, STANDALONE: 0.700769424438, CLUSER MEAN: 0.700769379735, ERROR: 4.47029999684e-08
ITEA: 0_22, STANDALONE: 0.696260929108, CLUSER MEAN: 0.696260944009, ERROR: 1.49007499672e-08
ITEA: 0_23, STANDALONE: 0.694629311562, CLUSER MEAN: 0.694629266858, ERROR: 4.47042499685e-08
ITEA: 0_24, STANDALONE: 0.691340565681, CLUSER MEAN: 0.691340610385, ERROR: 4.47037500351e-08
ITEA: 0_25, STANDALONE: 0.689275801182, CLUSER MEAN: 0.689275816083, ERROR: 1.49009998784e-08
ITEA: 0_26, STANDALONE: 0.686127662659, CLUSER MEAN: 0.68612767756, ERROR: 1.49007499672e-08
ITEA: 0_27, STANDALONE: 0.683331012726, CLUSER MEAN: 0.683330997825, ERROR: 1.49012500117e-08

**Comment by seiriosPlus** [comment]
多机：
CPU_NUM = 4
Trainer * Pserver = 4 * 1
BatchSize = 10 (相当于每个线程是10的BatchSize)
单机的BatchSize = 80

训练精度数据：
ITEA: 0_0, STANDALONE: 0.0, CLUSER MEAN: 0.0, ERROR: 0.0
ITEA: 0_1, STANDALONE: 0.0, CLUSER MEAN: 0.0, ERROR: 0.0
ITEA: 0_2, STANDALONE: 0.0, CLUSER MEAN: 0.0, ERROR: 0.0
ITEA: 0_3, STANDALONE: 0.0, CLUSER MEAN: 0.0, ERROR: 0.0
ITEA: 0_4, STANDALONE: 0.0, CLUSER MEAN: 0.0, ERROR: 0.0
ITEA: 0_5, STANDALONE: 0.0, CLUSER MEAN: 0.0, ERROR: 0.0
ITEA: 0_6, STANDALONE: 0.0, CLUSER MEAN: 0.0, ERROR: 0.0
ITEA: 0_7, STANDALONE: 0.0, CLUSER MEAN: 0.0, ERROR: 0.0
ITEA: 0_8, STANDALONE: 0.0, CLUSER MEAN: 0.0, ERROR: 0.0
ITEA: 0_9, STANDALONE: 0.0, CLUSER MEAN: 0.0, ERROR: 0.0
ITEA: 0_10, STANDALONE: 0.0, CLUSER MEAN: 0.0, ERROR: 0.0
ITEA: 0_11, STANDALONE: 0.0, CLUSER MEAN: 0.0, ERROR: 0.0
ITEA: 0_12, STANDALONE: 0.0, CLUSER MEAN: 0.0, ERROR: 0.0
ITEA: 0_13, STANDALONE: 0.0, CLUSER MEAN: 0.0, ERROR: 0.0
ITEA: 0_14, STANDALONE: 0.00312500004657, CLUSER MEAN: 0.00312500004656, ERROR: 7.50007694839e-15
ITEA: 0_15, STANDALONE: 0.0, CLUSER MEAN: 0.0, ERROR: 0.0
ITEA: 0_16, STANDALONE: 0.0, CLUSER MEAN: 0.0, ERROR: 0.0
ITEA: 0_17, STANDALONE: 0.0, CLUSER MEAN: 0.0, ERROR: 0.0
ITEA: 0_18, STANDALONE: 0.00937500037253, CLUSER MEAN: 0.00937500013969, ERROR: 2.32842498754e-10
ITEA: 0_19, STANDALONE: 0.0125000001863, CLUSER MEAN: 0.0125000001863, ERROR: 4.99999347481e-14
ITEA: 0_20, STANDALONE: 0.0218749996275, CLUSER MEAN: 0.0218750000931, ERROR: 4.65625000362e-10
ITEA: 0_21, STANDALONE: 0.09375, CLUSER MEAN: 0.0937500009313, ERROR: 9.31312499342e-10
ITEA: 0_22, STANDALONE: 0.23125000298, CLUSER MEAN: 0.231250003911, ERROR: 9.31499988255e-10
ITEA: 0_23, STANDALONE: 0.375, CLUSER MEAN: 0.375000003725, ERROR: 3.72524999737e-09
ITEA: 0_24, STANDALONE: 0.568749964237, CLUSER MEAN: 0.56875000149, ERROR: 3.72531250292e-08
ITEA: 0_25, STANDALONE: 0.78125, CLUSER MEAN: 0.78125, ERROR: 0.0
ITEA: 0_26, STANDALONE: 0.921875, CLUSER MEAN: 0.921875007451, ERROR: 7.45062500584e-09
ITEA: 0_27, STANDALONE: 0.96875, CLUSER MEAN: 0.968750014901, ERROR: 1.49012500117e-08
ITEA: 0_28, STANDALONE: 0.993749976158, CLUSER MEAN: 0.993750005961, ERROR: 2.98025000234e-08
ITEA: 0_29, STANDALONE: 1.0, CLUSER MEAN: 1.0, ERROR: 0.0
ITEA: 0_30, STANDALONE: 1.0, CLUSER MEAN: 1.0, ERROR: 0.0
ITEA: 0_31, STANDALONE: 1.0, CLUSER MEAN: 1.0, ERROR: 0.0
ITEA: 0_32, STANDALONE: 1.0, CLUSER MEAN: 1.0, ERROR: 0.0
ITEA: 0_33, STANDALONE: 1.0, CLUSER MEAN: 1.0, ERROR: 0.0
ITEA: 0_34, STANDALONE: 1.0, CLUSER MEAN: 1.0, ERROR: 0.0
ITEA: 0_35, STANDALONE: 1.0, CLUSER MEAN: 1.0, ERROR: 0.0
ITEA: 0_36, STANDALONE: 1.0, CLUSER MEAN: 1.0, ERROR: 0.0
ITEA: 0_37, STANDALONE: 1.0, CLUSER MEAN: 1.0, ERROR: 0.0

训练LOSS数据：
ITEA: 0_0, STANDALONE: 0.758363842964, CLUSER MEAN: 0.758363865316, ERROR: 2.23517501174e-08
ITEA: 0_1, STANDALONE: 0.755093574524, CLUSER MEAN: 0.755093619227, ERROR: 4.47033748907e-08
ITEA: 0_2, STANDALONE: 0.752945899963, CLUSER MEAN: 0.752945870161, ERROR: 2.980212499e-08
ITEA: 0_3, STANDALONE: 0.749299228191, CLUSER MEAN: 0.749299228191, ERROR: 3.75033337718e-13
ITEA: 0_4, STANDALONE: 0.746930003166, CLUSER MEAN: 0.746929988265, ERROR: 1.49009999895e-08
ITEA: 0_5, STANDALONE: 0.743838429451, CLUSER MEAN: 0.74383841455, ERROR: 1.49011250006e-08
ITEA: 0_6, STANDALONE: 0.740871071815, CLUSER MEAN: 0.740871027112, ERROR: 4.47031249795e-08
ITEA: 0_7, STANDALONE: 0.737979650497, CLUSER MEAN: 0.737979687751, ERROR: 3.72535000626e-08
ITEA: 0_8, STANDALONE: 0.735308527946, CLUSER MEAN: 0.735308498144, ERROR: 2.98018750788e-08
ITEA: 0_9, STANDALONE: 0.732561290264, CLUSER MEAN: 0.732561253011, ERROR: 3.72527499959e-08
ITEA: 0_10, STANDALONE: 0.72989988327, CLUSER MEAN: 0.729899853468, ERROR: 2.980200009e-08
ITEA: 0_11, STANDALONE: 0.72657930851, CLUSER MEAN: 0.72657931596, ERROR: 7.45037509464e-09
ITEA: 0_12, STANDALONE: 0.72386932373, CLUSER MEAN: 0.723869398236, ERROR: 7.45060000362e-08
ITEA: 0_13, STANDALONE: 0.720677316189, CLUSER MEAN: 0.720677293837, ERROR: 2.23519999176e-08
ITEA: 0_14, STANDALONE: 0.718268573284, CLUSER MEAN: 0.718268603086, ERROR: 2.98023750123e-08
ITEA: 0_15, STANDALONE: 0.715328395367, CLUSER MEAN: 0.715328425169, ERROR: 2.980212499e-08
ITEA: 0_16, STANDALONE: 0.713032543659, CLUSER MEAN: 0.713032618165, ERROR: 7.45061249363e-08
ITEA: 0_17, STANDALONE: 0.711152017117, CLUSER MEAN: 0.711152009666, ERROR: 7.45087502807e-09
ITEA: 0_18, STANDALONE: 0.707172393799, CLUSER MEAN: 0.707172401249, ERROR: 7.45037498362e-09
ITEA: 0_19, STANDALONE: 0.704988598824, CLUSER MEAN: 0.704988673329, ERROR: 7.45053749807e-08
ITEA: 0_20, STANDALONE: 0.702762305737, CLUSER MEAN: 0.702762335539, ERROR: 2.98017499567e-08
ITEA: 0_21, STANDALONE: 0.700175046921, CLUSER MEAN: 0.700175076723, ERROR: 2.98018749678e-08
ITEA: 0_22, STANDALONE: 0.696775913239, CLUSER MEAN: 0.69677592814, ERROR: 1.49006249561e-08
ITEA: 0_23, STANDALONE: 0.695110559464, CLUSER MEAN: 0.695110596717, ERROR: 3.72525000847e-08
ITEA: 0_24, STANDALONE: 0.692278027534, CLUSER MEAN: 0.692278079689, ERROR: 5.21547499632e-08
ITEA: 0_25, STANDALONE: 0.689247846603, CLUSER MEAN: 0.689247854054, ERROR: 7.4511250503e-09
ITEA: 0_26, STANDALONE: 0.686113357544, CLUSER MEAN: 0.686113402247, ERROR: 4.47033750017e-08
