### ISSUE TITLE
Fluid一个函数可以构建多个不同网络进行训练么

### ISSUE THREAD

**Issue by chengyuz** [PaddlePaddle/Paddle#12108]
当训练第一个网络时，若显存沾满，那么加载第二个模型时显存不够，有方法可以显式释放显存么；

**Comment by qingqing01** [comment]
可以构建多个不同的网络进行训练，Fluid的程序执行有两个入口：

-   单卡/单线程Executor： 默认会释放除过Parameter之外的非persistable的variable。
-   多卡/多线程ParallelExecutor： 不会释放除过Parameter之外的variable，构造函数有个`share_vars_from`，可以共享不同ParallelExecutor之间的同名的variable，但也得多个网络可被复用的variable同名。

这确实是个可以增强的点。

**Comment by chengyuz** [comment]
谢谢回复！那当使用单卡时，在第一个网络训练完成后是继续新建executor，使用fluid.default_main_program()继续训练么

**Comment by qingqing01** [comment]
对于单卡： 

1. 多个program可以用同一个 executor运行，比如我们很多models里fluid示例，同一个executor可以运行fluid.default_main_program()和fluid.default_startup_program()两个program。

2. 你多个网络，应该是需要构造多个ProgramDesc吧，可以参考： https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/fluid/tests/demo/fc_gan.py

**Comment by chengyuz** [comment]
好的，多谢

**Comment by maydaygmail** [comment]
> 可以构建多个不同的网络进行训练，Fluid的程序执行有两个入口：
> 
> * 单卡/单线程Executor： 默认会释放除过Parameter之外的非persistable的variable。
> * 多卡/多线程ParallelExecutor： 不会释放除过Parameter之外的variable，构造函数有个`share_vars_from`，可以共享不同ParallelExecutor之间的同名的variable，但也得多个网络可被复用的variable同名。
> 
> 这确实是个可以增强的点。

多卡使用ParallelExecutor训练，遇到一个问题：有三个Program, 其中第三个program的参数有分别与第一个和第二个共享，但是share_vars_from应该只能指定一个，这个问题该怎么解决？
