### ISSUE TITLE
seqToseq单机多卡下训练速度几乎无提升

### ISSUE THREAD

**Issue by huguanglong** [PaddlePaddle/Paddle#1211]
@lcy-seso @reyoung 我的一台机器上有4张Tesla K80 卡（共8核），运行seqToseq.py实验时，用4张K80和1张K80时，训练速度基本差不多。

**Comment by qingqing01** [comment]
可否详细贴出时间信息?  卡数增加时，可以成倍的增加batch_size再测下时间~

**Comment by backyes** [comment]
@huguanglong 

建议： 
*  如果对源码编译比较熟悉，建议打开TIMER选项，有个WITH_TIMER选项，最终它会output量化性能分析，会比较客观。 

* 依据量化结果分析： 
  卡数增多耗时几乎不变的情况，最大的怀疑对象是数据读取可能是瓶颈。 如果读数据问题，总归是有办法解决的。

* 我印象中咱么默认的DoubleBuffer的buffer size是1， 这个也会影响缓冲效果。@qingqing01

**Comment by huguanglong** [comment]
@qingqing01  @详细时间信息是指 @backyes 所说的打开TIMER选项么？单卡和4卡的batch_size我都是设成80了。成倍的增加batch_size会不会导致训练性能有下降呢？
下面是我单机上的GPU信息：
![image](https://cloud.githubusercontent.com/assets/2075596/22189404/5acfc4cc-e157-11e6-939b-ff567779ce9e.png)

**Comment by qingqing01** [comment]
> 详细时间信息是指 @backyes 所说的打开TIMER选项么？
这样观察时间可以，就是比较详细的debug了看各部分耗时了。简单的方法就是过相同数量样本对比时间吧。

> 单卡和4卡的batch_size我都是设成80了。成倍的增加batch_size会不会导致训练性能有下降呢？
不一定的，batch_size和最终收敛程度视任务而定吧。

**Comment by huguanglong** [comment]
@qingqing01 @backyes 我打开了TIMER选项，在单卡和4卡下分别运行了1个batch日志，batch_size都等于80. 详细耗时如下：
1）单卡：
[train_1gpu_1batch.txt](https://github.com/PaddlePaddle/Paddle/files/722560/train_1gpu_1batch.txt)
2）4卡：
[train_4gpu_1batch.txt](https://github.com/PaddlePaddle/Paddle/files/722564/train_4gpu_1batch.txt)
麻烦两位看看，谢谢！
另外，你们在用单卡和多卡训练时，参数设置上会有什么变化么？（除了batch_size成倍增加外）还是说多卡下的提速是靠batch_size成倍增加实现的？

**Comment by backyes** [comment]
@huguanglong 

* 设置log_period = N, N 至少大于10吧
* 另外不要只跑一个batch，误差太大 

总之， 时间不要太短

**Comment by huguanglong** [comment]
@backyes 好，我分别跑1个小时，傍晚再贴上来。

**Comment by backyes** [comment]
@huguanglong 

不用那么久， 跑三五个log_period的日志看看。

**Comment by backyes** [comment]
@huguanglong 

你有follow @qingqing01 意见 将setting(batch_size=N, ...) 的N 设置成 batch_size = batch_size（单卡） * trainer_count 么？  也可以出一组这样的数据。 

现在至少看来性能问题跟dataprovider没有什么关系了。

**Comment by backyes** [comment]
等你数据完备了，@hedaoyuan 道远也可以review下。

**Comment by huguanglong** [comment]
@backyes 好，我再跑一组 batch_size = batch_size（单卡） * trainer_count 的实验。
不知道你们对多卡情况下的训练，建议参数设置是怎样的？还是多卡下就是通过 batch_size = batch_size（单卡） * trainer_count 的设置来达到加速目的的？

**Comment by backyes** [comment]
@huguanglong 

 > 不知道你们对多卡情况下的训练，建议参数设置是怎样的 

这个要综合算法收敛性、系统效率等因素来确定batch size，没有固定的方法。 上面给你的增加batch size的建议，主要先看看系统效率有没有提升，方便分析问题。

等你综合好数据，我们再分析吧。

**Comment by qingqing01** [comment]
@huguanglong   卡数增多时，增加batch size是为了增大计算量，尽可能充分利用GPU资源，并不是说为了达到加速目的。

**Comment by huguanglong** [comment]
@backyes @qingqing01 
刚做了三组实验，分别跑了6个log_period：
1）1 gpu，batch_size=80，平均 44 句/秒：
[train_1gpu_bs80_6logperiod.txt](https://github.com/PaddlePaddle/Paddle/files/722763/train_1gpu_bs80_6logperiod.txt)
2）4 gpu，batch_size=80，平均 41 句/秒：
[train_4gpu_bs80_6logperiod.txt](https://github.com/PaddlePaddle/Paddle/files/722764/train_4gpu_bs80_6logperiod.txt)
3）4 gpu，batch_size=320，平均 135 句/秒：
[train_4gpu_bs320_6logperiod.txt](https://github.com/PaddlePaddle/Paddle/files/722766/train_4gpu_bs320_6logperiod.txt)
总的来看，4卡时，batch_size扩大4倍，能获得3倍左右的加速。细节麻烦两位看看日志，谢谢！

**Comment by qingqing01** [comment]
>  1）1 gpu，batch_size=80，平均 44 句/秒：
>  train_1gpu_bs80_6logperiod.txt

这个你其实测的不是1卡的时间，命令行参数里 `--trainer_count=2`，所以你这个是2个卡的时间。

对比 `train_1gpu_bs80_6logperiod.txt` 和  `train_4gpu_bs80_6logperiod.txt` 来看：
- 计算时间确实少了， 可以比较 `FwMulTimer`,  'BpMulTimer',  `GruStepFwTime`, `GruStepBwTime`,  `ForwardTimer`, `BackwardTimer` 等。但不是成倍的减少，RNN相关的任务本身GPU资源也没有充分利用吧。
- 其他一些多机间操作的时间增加。

一般使用多卡，都会增加batch_size吧，建议你也可这样使用。

**Comment by huguanglong** [comment]
@qingqing01 我的是k80，1张卡上相当于有2个核，所以跑1张卡时，trainer_count设成了2。
也就是说，在用多卡时，要想获得提速，是靠增加batch_size来实现是么？batch_size不变的情况下，单卡和多卡速度就差不多了？

**Comment by qingqing01** [comment]
@huguanglong  多谢你提醒。

>  在用多卡时，要想获得提速，是靠增加batch_size来实现是么？batch_size不变的情况下，单卡和多卡速度就差不多了？

在这个任务中，看你测的时间确实是这样。另外我自己在K40的机器上验证了下，同样的batch size，2个卡相对1张卡还是加速的(由于shuffle、序列长度不等等因素，并没有很准确的对比)。

**Comment by huguanglong** [comment]
@qingqing01 感谢你抽时间做了实验验证。
那基本结论可以归结为：
1）batch_size相同的情况下，多卡的计算时间少了，但多卡间的操作时间也增加了，导致整体训练时间没有什么提升；
2）多卡情况下，batch_size相应地倍增（或考虑其他因素综合选择），能带来提速，此时可能需要多增加些迭代次数来达到单卡类似的收敛程度，不过整体上还是提速的。
