### ISSUE TITLE
grpc "os_error":"Protocol not available"

### ISSUE THREAD

**Issue by jacquesqiao** [PaddlePaddle/Paddle#12111]
E0712 09:59:00.210762273   41229 tcp_server_posix.cc:64]     check for SO_REUSEPORT: {"created":"@1531360740.210739831","description":"OS Error","errno":92,"file":"src/core/lib/iomgr/socket_utils_common_posix.cc","file_line":169,"os_error":"Protocol not available","syscall":"setsockopt(SO_REUSEPORT)"}
Thu Jul 12 09:59:00 2018[1,4]<stderr>:

**Comment by Yancey0623** [comment]
Seems the kernel version is too old that don't support `REUSE PORT`
reference links:
- https://github.com/tensorflow/tensorflow/issues/9377 
- https://stackoverflow.com/questions/3261965/so-reuseport-on-linux
