### ISSUE TITLE
fuild 0.14.0什么时候可以支持rank_cost ?

### ISSUE THREAD

**Issue by xum2008** [PaddlePaddle/Paddle#12117]

**Comment by xum2008** [comment]
fuild 0.14.0什么时候可以支持rank_cost ?

**Comment by qingqing01** [comment]
@xum2008 rank_cost的op已经实现: https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/fluid/operators/rank_loss_op.cc ，需要在Python API里封装下，我们尽快封装下。
