### ISSUE TITLE
Do we need support Eigen with MKL

### ISSUE THREAD

**Issue by tensor-tang** [PaddlePaddle/Paddle#12122]
根据 eigen [文档](https://eigen.tuxfamily.org/dox/TopicUsingIntelMKL.html)，我们只需要加宏来实现`EIGEN_USE_MKL_ALL` 和link MKL的library来enable这个功能。

但是，根据文档中所描述的加入了MKL影响的面很小，也就是基本的MKL BLAS (?GEMM, ?GEMV, ?TRSM, ?AXPY and ?DOT) and LAPACK (LU, Cholesky and QR)等，这些函数在paddle里面好像并没有使用eigen调用吧？我看用到这些的时候一般都会切到`math::CBLAS`。

我实际增加了这个宏定义之后，没有任何速度提升。

@jacquesqiao @luotao1 @Superjomn 你们怎么看？

PS: paddle里面的`USE_EIGEN_FOR_BLAS`貌似只是V2的功能。

**Comment by Superjomn** [comment]
意思是，现在很多 OP 在有 MKL 之后已经自动用了 MKL？

**Comment by tensor-tang** [comment]
我的理解是op使用eigen时，好像并没有太多用BLAS，用到BLAS会切到调用`math:GetBlas`这些会使用到MKL，类似这样
https://github.com/PaddlePaddle/Paddle/blob/10737ed9cec68530bc64e610238187c5b12607ed/paddle/fluid/operators/matmul_op.cc#L57-L63

**Comment by luotao1** [comment]
https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/fluid/operators/math/blas.h
把需要大量用blas库函数的都调用了，包括GEMM，GEMV，AXPY等，fluid都进行调用了。所以不需要eigen额外调用了。

**Comment by tensor-tang** [comment]
reopen it as needed
