### ISSUE TITLE
paddle CNN能否支持对不同size的图像进行预测

### ISSUE THREAD

**Issue by shateng** [PaddlePaddle/Paddle#1212]
原理上CNN是与输入图像大小无关的，在固定size训练好网络后，能否支持对其他size的图像进行预测？需要做哪些调整？

**Comment by qingqing01** [comment]
如果是全卷积网络，支持对其他size的图像进行预测，但是目前得预测期间的size保持不变。

**Comment by shateng** [comment]
Python api，貌似没问题
