### ISSUE TITLE
paddlepaddle编译错误

### ISSUE THREAD

**Issue by wuzhibin69** [PaddlePaddle/Paddle#12126]
编译paddle时出现如下错误：
paddlepaddle/paddle/paddle/legacy/gserver/dataproviders/PyDataProvider2.cpp:693:53: error: ‘PyArray_DTYPE’ was not declared in this scope
       auto dtype = PyArray_DTYPE((PyArrayObject*)obj);

在paddlepaddle下搜索PyArray_DTYPE,只能找到该处使用，并没找到其定义，请问要如何解决？
![paddleerror](https://user-images.githubusercontent.com/41161432/42641735-cb128cb2-8627-11e8-8eda-98c674f97854.png)

**Comment by Yancey0623** [comment]
编译时用的Python是什么版本的呢？另外这部分应该是Paddle v1的代码，如果只是想编译Fluid可以在cmake时加上`-DWITH_FLUID_ONLY=ON`

**Comment by wuzhibin69** [comment]
的python 是2.7.3
![default](https://user-images.githubusercontent.com/41161432/42694926-7e428bb6-86e6-11e8-8309-7ef3f0143d92.PNG)

**Comment by velconia** [comment]
试一下先 ```pip install numpy```, 然后再编译;

```PyArray_DTYPE``` 是 ```numpy``` 里的CAPI, 可能是因为你的 python 环境没有安装 ```numpy```

**Comment by wuzhibin69** [comment]
![default](https://user-images.githubusercontent.com/41161432/42696113-d44408ca-86e9-11e8-8670-620c12e87eac.PNG)
应该是已经安装了，我还尝试了下 sudo pip install numpy --upgrade 也成功了：
![2](https://user-images.githubusercontent.com/41161432/42696492-d3e831ac-86ea-11e8-9939-d4644369ddff.PNG)

再次回到paddle/build下
cmake ..
make
还是会出现上述错误

**Comment by velconia** [comment]
贴下你的```CMAKE```结果, 可能是```CMAKE```使用的```python```版本不太对

**Comment by wuzhibin69** [comment]
![2](https://user-images.githubusercontent.com/41161432/42696901-2eccd07c-86ec-11e8-90f9-d165b1968812.PNG)

**Comment by wuzhibin69** [comment]
![3](https://user-images.githubusercontent.com/41161432/42697303-4fd1b606-86ed-11e8-9b9a-53904868758c.PNG)

通过
grep -inr PyArray_DTYPE /usr/lib/python2.7
grep -inr PyArray_DTYPE /usr/include
都找不到PyArray_DTYPE

**Comment by wuzhibin69** [comment]
你们的环境中 PyArray_DTYPE 这个所在的头文件是放在哪个目录的呢？

**Comment by Yancey0623** [comment]
试下Python2.7.12呢？另外可以尽量使用我们的开发环境镜像来编译，避免环境的问题：
```paddlepaddle/paddle:latest-dev```

**Comment by gongweibao** [comment]
Feel free to reopen it!
