### ISSUE TITLE
v2版本上如何在加载模型后改变embedding的shape

### ISSUE THREAD

**Issue by jaegerstar** [PaddlePaddle/Paddle#12137]
旧模型是根据原有词典训的，但是OOV问题比较严重，现在想要加载旧模型后，用词汇量更大的词典，相应的embedding也备好了。但是运行时候显示embedding的shape不匹配。请问有无相关demo可以解决？

**Comment by Yancey0623** [comment]
v2现在没有这个功能，在Fluid可能会比较容易实现，可以关注相关的issue：#10868

**Comment by lucywsq** [comment]
您好，此issue在近一个月内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题，我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持!
