### ISSUE TITLE
BaseSGDOptimizer没有实现？

### ISSUE THREAD

**Issue by huguanglong** [PaddlePaddle/Paddle#1213]
有的论文中先用Adam做快速优化，之后再用SGD做优化，效果比单独使用Adam或SGD要好。参见GNMT论文8.3小节：
![image](https://cloud.githubusercontent.com/assets/2075596/22181922/636b5248-e0d2-11e6-8ab6-6fb3ac370ee7.png)

Paddle中似乎取消了SGD的实现：
![image](https://cloud.githubusercontent.com/assets/2075596/22181904/cda21738-e0d1-11e6-86ec-72c43fb599c7.png)
请问这种未实现的考虑是怎样的？或者有替代的其他方案么？

**Comment by qingqing01** [comment]
SGD实现了，即MomentumOptimizer：

http://www.paddlepaddle.org/doc/ui/api/trainer_config_helpers/optimizers.html#momentumoptimizer

**Comment by huguanglong** [comment]
@qingqing01 Paddle文档中MomentumOptimizer的公式如下：
![image](https://cloud.githubusercontent.com/assets/2075596/22189827/0a4ef952-e15a-11e6-815b-edfaf2254db3.png)
这个公式与原始MomentumOptimizer公式似乎不一样：
![image](https://cloud.githubusercontent.com/assets/2075596/22189816/f67af78c-e159-11e6-8039-298818775ec0.png)
是做了改进么？
按照原始Momentum公式，γ=0就退化成SGD了。在Paddle中如何设置参数，将Momentum退化成SGD呢？

**Comment by qingqing01** [comment]
如果不需要设置正则，下面这样设置就好了：

```
settings(
    batch_size=xxx,
    learning_method = MomentumOptimizer(), #默认就是0
    learning_rate = xxx,
)
```

**Comment by huguanglong** [comment]
@qingqing01 好的，谢谢！
另外，Paddle文档中几种Optimizer的公式似乎不太完整，比如Adam最后一个公式少了均值项，建议Review下，谢谢。
