### ISSUE TITLE
Problem about begin_pass and end_pass.

### ISSUE THREAD

**Issue by gongweibao** [PaddlePaddle/Paddle#12139]
I think `begin_pass` and `end_pass` should be operators just like `SendBarrierOp` operators and `FetchBarrierOp`.

And then the BeginPass() should not use 
```
void GRPCClient::SendBeginPass() {
  for (auto& it : channels_) {
    VLOG(3) << "send begin pass to: " << it.first;
    this->AsyncSendBeginPass(it.first);
  }
  this->Wait();
}

void GRPCClient::SendEndPass() {
  for (auto& it : channels_) {
    VLOG(3) << "send end pass to " << it.first;
    this->AsyncSendEndPass(it.first);
  }
  this->Wait();
}
```

since we may connect to anything includes pserver. 

I think this functions should implement in `BeginPass` operator and `EndPass` operator.

**Comment by Yancey0623** [comment]
> I think begin_pass and end_pass should be operators just like SendBarrierOp operators and FetchBarrierOp.

Yes, but it's hard to implement for the current `ProgramDesc`, we can only know the pass barrier in Python code bacause of the `for loop` was not in `ProgramDesc`.


> since we may connect to anything includes pserver.

Agree with that.

**Comment by Yancey0623** [comment]
Close this inactive issue.
