### ISSUE TITLE
Installing paddle wheel meets problem

### ISSUE THREAD

**Issue by BigFishMaster** [PaddlePaddle/Paddle#12134]
I install "refs/heads/develop \#297" wheel from paddle [url](https://paddleci.ngrok.io/project.html?projectId=Manylinux1), and get the following problem:

```python
paddle/fluid/../libs/libmklml_intel.so: symbol __kmpc_omp_task_with_deps, version VERSION not defined in file libiomp5.so with link time reference
```

**Comment by luotao1** [comment]
请问你装的是哪个版本的？

**Comment by BigFishMaster** [comment]
cuda8.0_cudnn5_avx_mkl,
refs/heads/develop #297
paddlepaddle_gpu-latest-cp27-cp27mu-linux_x86_64.whl (90.71 MB)

**Comment by luotao1** [comment]
https://paddleci.ngrok.io/repository/download/Manylinux1_Cuda80cudnn5cp27cp27mu/1730:id/paddlepaddle_gpu-latest-cp27-cp27mu-linux_x86_64.whl
我下载了这个whl包，在docker环境（paddlepaddle/paddle:latest-dev）里安装，import paddle.fluid是正常的。
![image](https://user-images.githubusercontent.com/6836917/42678024-346b4522-86b0-11e8-923e-fe82bc528e01.png)

**Comment by lgone2000** [comment]
我自己编译，也遇到同样问题

**Comment by Yancey0623** [comment]
麻烦提供下操作系统和kernel的版本？

**Comment by lgone2000** [comment]
@qingqing01  之前确认过这个问题，她说在修复

> 党青青 2018-07-13 15:46:23
自己编译的话，把thirdparty/instal里 mkldnn mklml的lib设置到LD_LIBRARY_PATH里
刘国翌 2018-07-13 15:47:43
以前咋没这个问题呢？
党青青 2018-07-13 15:48:18
最近对mkl的path有些修改，我们自己发现了，在fix

**Comment by lgone2000** [comment]
另外在paddlecloud 好像不能设置自己的LD_LIBRARY_PATH，希望给一个不用改LD_LIBRARY_PATH 的修复方案

**Comment by luotao1** [comment]
在 @lgone2000 的机器上复现问题了。该机器使用了`python-gcc482-paddle`：
```
ldd /home/liuguoyi01/work/paddletest/easy-paddle-run/paddle-release/python-gcc482-paddle/lib/python2.7/site-packages/paddle/fluid/core.so
	linux-vdso.so.1 (0x00007ffef3956000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f7ccbc58000)
	libpython2.7.so.1.0 => not found
	librt.so.1 => /lib64/librt.so.1 (0x00007f7ccba4f000)
	libiomp5.so => /home/liuguoyi01/work/paddletest/easy-paddle-run/paddle-release/python-gcc482-paddle/lib/python2.7/site-packages/paddle/fluid/../libs/libiomp5.so (0x00007f7ccb6ab000)
	libmkldnn.so.0 => /home/liuguoyi01/work/paddletest/easy-paddle-run/paddle-release/python-gcc482-paddle/lib/python2.7/site-packages/paddle/fluid/../libs/libmkldnn.so.0 (0x00007f7ccae4d000)
	libdl.so.2 => /lib64/libdl.so.2 (0x00007f7ccac49000)
	libstdc++.so.6 => /usr/lib64/libstdc++.so.6 (0x00007f7cca943000)
	libm.so.6 => /lib64/libm.so.6 (0x00007f7cca640000)
	libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007f7cca42a000)
	libc.so.6 => /lib64/libc.so.6 (0x00007f7cca069000)
	/opt/compiler/gcc-4.8.2/lib64/ld-linux-x86-64.so.2 (0x00007f7cd5cb4000)
	libmklml_intel.so => /home/liuguoyi01/work/paddletest/easy-paddle-run/paddle-release/python-gcc482-paddle/lib/python2.7/site-packages/paddle/fluid/../libs/libmklml_intel.so (0x00007f7cc0f97000)
```
异常现象：使用dlopen后，不应该出现最后一行的`libmklml_intel.so => XXX`了。

目前的临时解决方案：
```
paddle_lib=/home/liuguoyi01/work/paddletest/easy-paddle-run/paddle-release/python-gcc482-paddle/lib/python2.7/site-packages/paddle/libs
## paddle_lib必须放在LD_LIBRARY_PATH前才能生效
export LD_LIBRARY_PATH=$paddle_lib:$LD_LIBRARY_PATH
```

猜测：iomp5的问题。 @tensor-tang

**Comment by luotao1** [comment]
@lgone2000 发现他的LD_LIBRAYR_PATH 里面有一个其他版本的libiomp5.so，删掉后 ，就可以正常跑了。 目前看不是paddle的问题。
