### ISSUE TITLE
百度AI控烟项目

### ISSUE THREAD

**Issue by liuyu666-thu** [PaddlePaddle/Paddle#12146]
本人对百度前些时候完成的吸烟人群识别项目跟感兴趣，想请教几个问题：

1）识别是基于视频连续帧的动态识别，还是基于单帧图像的静态识别？
2）数据集是如何获取和标注的呢？能否开源数据集？
3）主要用到了什么方法呢？是直接拿数据集去fine tune了SSD吗？

谢谢。

**Comment by captainwoon** [comment]
您好，谢谢对paddlepaddle的关注，针对您的问题有以下回复：
1.由于受限计算资源，使用的是静态识别
2.数据集是为了完成此项目自主采集的，使用标注工具（http://jl.shenjian.io/ ），数据集由于项目还有后续工作，暂时不考虑开放
3.是直接用数据去fine tune ssd

**Comment by liuyu666-thu** [comment]
@captainwoon 

非常感谢您的回答，很好地解决了我的疑问。

我还有最后一个问题，烦请告知：
在标注数据集的时候，针对吸烟者是如何标注的？ 单单标注香烟的形状，还是人脸，还是全身？

万分感激。

**Comment by captainwoon** [comment]
全身标注
模型最终判断的是一个人是否有吸烟动作

**Comment by jzyztzn** [comment]
@captainwoon @quinnliu4real   您好，我也对吸烟人群识别项目很感兴趣，也有一个问题需要请教一下，使用全身标注的话，一般会设置多少类别呢？还是只有吸烟的人这一个类别？只要目标手中拿着香烟，却没有放在嘴边，是不是也算吸烟。
谢谢
