### ISSUE TITLE
paddle v1 mixed_layer报错

### ISSUE THREAD

**Issue by Emma-Ding** [PaddlePaddle/Paddle#12148]
mixed_layer一用就报错，删除就可以train，code如下
`fc2 = mixed_layer(size=256, input=[full_matrix_projection(input=fc1),
                                        identity_projection(input=fc1)])`
报错如下，

Python Error: <type 'exceptions.Exception'> :
Python Callstack:
            /home/dingweiyue/baidu/nad-model/deepfeed/feedbsq_paddle/paddle/python27-gcc482/lib/python2.7/site-packages/paddle/trainer/config_parser.py : 3406
            /home/dingweiyue/baidu/nad-model/deepfeed/feedbsq_paddle/paddle/python27-gcc482/lib/python2.7/site-packages/paddle/trainer/config_parser.py : 3382
            conf/trainer_config.conf : 209
            conf/trainer_config.conf : 177
            /home/dingweiyue/baidu/nad-model/deepfeed/feedbsq_paddle/paddle/python27-gcc482/lib/python2.7/site-packages/paddle/trainer_config_helpers/default_decorators.py : 53
            /home/dingweiyue/baidu/nad-model/deepfeed/feedbsq_paddle/paddle/python27-gcc482/lib/python2.7/site-packages/paddle/trainer_config_helpers/default_decorators.py : 53
            /home/dingweiyue/baidu/nad-model/deepfeed/feedbsq_paddle/paddle/python27-gcc482/lib/python2.7/site-packages/paddle/trainer_config_helpers/default_decorators.py : 53
            /home/dingweiyue/baidu/nad-model/deepfeed/feedbsq_paddle/paddle/python27-gcc482/lib/python2.7/site-packages/paddle/trainer_config_helpers/layers.py : 300
            /home/dingweiyue/baidu/nad-model/deepfeed/feedbsq_paddle/paddle/python27-gcc482/lib/python2.7/site-packages/paddle/trainer_config_helpers/layers.py : 762
            /home/dingweiyue/baidu/nad-model/deepfeed/feedbsq_paddle/paddle/python27-gcc482/lib/python2.7/site-packages/paddle/trainer_config_helpers/layers.py : 693
            /home/dingweiyue/baidu/nad-model/deepfeed/feedbsq_paddle/paddle/python27-gcc482/lib/python2.7/site-packages/paddle/trainer/config_parser.py : 2677
            /home/dingweiyue/baidu/nad-model/deepfeed/feedbsq_paddle/paddle/python27-gcc482/lib/python2.7/site-packages/paddle/trainer/config_parser.py : 156
            /home/dingweiyue/baidu/nad-model/deepfeed/feedbsq_paddle/paddle/python27-gcc482/lib/python2.7/site-packages/paddle/trainer/config_parser.py : 3346
Call Object failed.
*** Check failure stack trace: ***
    @          0x13c3398  google::LogMessage::Fail()
    @          0x13c32f0  google::LogMessage::SendToLog()
    @          0x13c2d85  google::LogMessage::Flush()
    @          0x13c5b46  google::LogMessageFatal::~LogMessageFatal()
    @           0x81e19d  paddle::callPythonFuncRetPyObj()
    @           0x81e3a1  paddle::callPythonFunc()
    @           0x71baa6  paddle::TrainerConfigHelper::TrainerConfigHelper()
    @           0x71c11d  paddle::TrainerConfigHelper::createFromFlags()
    @           0x5923d4  main
    @     0x7f4a0f1e0bd5  __libc_start_main
    @           0x59e195  (unknown)

**Comment by Emma-Ding** [comment]
P.S.：mixed_layer是不是如下意思，mixed_layer(a=layer1, b=layer2) 即  output[i] = a[i]+ b[i]， 那这里最后对output加上激活函数activation function吗

**Comment by luotao1** [comment]
1. 可以尝试下
```
with mixed_layer(size=256) as fc2:
           fc2 += full_matrix_projection(input=fc1)
           fc2 += identity_projection(input=fc1)
```
2. mixed_layer默认使用LinearActivation，可以用act参数自定义激活函数
https://github.com/PaddlePaddle/Paddle/blob/0042ba93c8caec99289d08cee8f98989632a4f24/python/paddle/trainer_config_helpers/layers.py#L865-L874

> mixed_layer是不是如下意思，mixed_layer(a=layer1, b=layer2) 即 output[i] = a[i]+ b[i]

是的。

**Comment by reyoung** [comment]
Closed due to no response for a long time.
