### ISSUE TITLE
It's seems wrong to modify var dependency after memory_optimize_transpiler

### ISSUE THREAD

**Issue by panyx0718** [PaddlePaddle/Paddle#12140]
memory_optimizer decides a var can be overridden if it is no longer "live" in the future.

For example, var1 can be reused after ```op1```
```
var3 can use var1's memory.
var1->op1->var2->op2->var3
```

However, in the builders of ParallelExecutor, many nodes can be inserted into the graph, adding various new var dependency. This cause the decision made by the memory_optimizer previously wrong.

For example, the graph can be later changed to:
```
op3 is inserted and depends on both var1 and var3
var1->op1->var2->op2->var3->op3 -> var4
     ->------------------------->
```
var3 using var1's memory becomes wrong!

Hence
memory_optimizer should be applied after graph dependency modifications.

**Comment by dzhwinter** [comment]
Let's make it clear, the parallel executor will insert what kind of ops at which stage?
In my mind, only the broadcast ops and reduce ops is inserted.  

For the broadcast ops, parameters will not be reused, so the broadcast is not affected by the memory optimizer. So inserted them anywhere will be fine.  

For the reduce/allreduce ops, it has two kind of inputs: the weights(parameter) and the gradients. 
The gradient is depended by the optimize op, so its will be live and will not be reused by any other ops.
