### ISSUE TITLE
AttributeError: 'module' object has no attribute 'Trainer' 

### ISSUE THREAD

**Issue by 930083287** [PaddlePaddle/Paddle#12155]
运行这个代码时，trainer = fluid.Trainer(train_func=train_program, place=place, optimizer_func=optimizer_program)报上述错误，已经import这个了import paddle.v2.fluid as fluid

**Comment by seiriosPlus** [comment]
请安装新版的paddlepaddle， import 使用 ```import paddle.fluid as fluid```

**Comment by upwindflys** [comment]
> 请安装新版的paddlepaddle， import 使用 `import paddle.fluid as fluid`

你好，安装paddlepaddle-gpu 1.2.0且使用 `import paddle.fluid as fluid` ，运行models/fluid/PaddleCV/HiNAS_models时仍然报此错误
