### ISSUE TITLE
paddle使用问题：想获取paddlepaddle全连接层（激活函数不为softmax）输出,转为一个普通向量。

### ISSUE THREAD

**Issue by xiaocc612** [PaddlePaddle/Paddle#12174]
我想利用paddle来实现siamese网络，需要计算两个CNN提取出的特征向量。我发现paddle网络层返回的是：paddle.trainer_config_helpers.layers.LayerOutput，不知道如何转成list。且我是在科赛网的K-lab平台上使用paddlepaddle,该平台只支持0.11.0版本的paddle，而这个版本的源码在GitHub上已经没有了。麻烦各位了

**Comment by kuke** [comment]
[0.11.0](https://github.com/PaddlePaddle/Paddle/tree/release/0.11.0)作为PaddlePaddle Fluid的一个release版本，会一直在github上。

可以将CNN的feature map作为网络的输出，infer之后就可以得到ndarray形式的普通数据格式了

https://github.com/PaddlePaddle/models/blob/bb59b41a701cee3c7420e9e1d692aeb44b30bc15/fluid/image_classification/infer.py#L71

**Comment by WangTaoSpace** [comment]
您好，针对 0.11.0版本paddlepaddle给下具体的操作？out_anchor = paddle.layer.fc(
        input=net_anchor, size=128, act= None)  , out_anchor 就是我想要向量
