### ISSUE TITLE
paddle损失函数问题，官方提供的损失函数没有对比损失函数（contrastive loss function）。自己实现的话应该怎么做

### ISSUE THREAD

**Issue by xiaocc612** [PaddlePaddle/Paddle#12186]
问题如题所示。使用paddle训练器时，要求传过去的损失函数类型为：paddle.v2.config_base.Layer
自己实现对比损失函数的话，怎么将计算的结果转为paddle.v2.config_base.Layer类型。谢谢。
  
![image](https://user-images.githubusercontent.com/36946952/42809317-ee81d1a8-89e7-11e8-860c-a8f6a2d1b6e1.png)

**Comment by kuke** [comment]
@xiaocc612 http://www.paddlepaddle.org/docs/0.14.0/documentation/zh/dev/new_layer_cn.html 这里有个文档，说明了如何在V2中实现新的层

**Comment by lucywsq** [comment]
您好，此issue在近一个月内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题，
我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持!
