### ISSUE TITLE
What is the difference between arguments `ports_num` and `ports_num_for_sparse `

### ISSUE THREAD

**Issue by helinwang** [PaddlePaddle/Paddle#1219]
According to https://github.com/PaddlePaddle/Paddle/blob/6aed264f0a4f8e045e5fc44fd7144fc727098070/paddle/utils/Flags.cpp#L38

> DEFINE_int32(ports_num,
>              1,
>              "The ports number for parameter send,"
>              " increment based on default port number");
> DEFINE_int32(ports_num_for_sparse,
>              0,
>              "The ports number for parameter send,"
>              " increment based on default (port + ports_num)");

Feels like it's hard to understand the difference.

**Comment by emailweixu** [comment]
If remote sparse update is used, there are two types of parameter servedrs. One for dense update, one for sparse update. ports_num is for dense parameter server, ports_num_for_sparse is for sparse parameter server.
