### ISSUE TITLE
fc layer with mkl and without mkl performance analyse

### ISSUE THREAD

**Issue by jacquesqiao** [PaddlePaddle/Paddle#12203]
CPU配置如下：
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                12
On-line CPU(s) list:   0-11
Thread(s) per core:    1
Core(s) per socket:    1
Socket(s):             12
NUMA node(s):          1
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 44
Model name:            Intel(R) Xeon(R) CPU           E5645  @ 2.40GHz
Stepping:              2
CPU MHz:               2400.082
BogoMIPS:              4800.16
Hypervisor vendor:     KVM
Virtualization type:   full
L1d cache:             32K
L1i cache:             32K
L2 cache:              4096K
NUMA node0 CPU(s):     0-11
 
内存配置：
MemTotal:       49288900 kB
MemFree:         2094440 kB
MemAvailable:   46980392 kB
Buffers:          437212 kB
Cached:         43032928 kB
SwapCached:          716 kB
Active:         17141468 kB
Inactive:       27298956 kB
Active(anon):     330000 kB
Inactive(anon):  1186068 kB
Active(file):   16811468 kB
Inactive(file): 26112888 kB
Unevictable:           0 kB
Mlocked:               0 kB
SwapTotal:      50331644 kB
SwapFree:       50304148 kB
Dirty:               316 kB
Writeback:             0 kB
AnonPages:        969620 kB
Mapped:           107948 kB
Shmem:            545784 kB
Slab:            2266136 kB
SReclaimable:    2193664 kB
SUnreclaim:        72472 kB
KernelStack:       11808 kB
PageTables:        15068 kB
NFS_Unstable:          0 kB
Bounce:                0 kB
WritebackTmp:          0 kB
CommitLimit:    74976092 kB
Committed_AS:    7869472 kB
VmallocTotal:   34359738367 kB
VmallocUsed:      121304 kB
VmallocChunk:   34359543279 kB
HardwareCorrupted:     0 kB
HugePages_Total:       0
HugePages_Free:        0
HugePages_Rsvd:        0
HugePages_Surp:        0
Hugepagesize:       2048 kB
DirectMap4k:       65404 kB
DirectMap2M:     3080192 kB
DirectMap1G:    49283072 kB

**Comment by jacquesqiao** [comment]
## batch_size=2 

## with_mkl
![image](https://user-images.githubusercontent.com/3048612/42855992-bdbb16c2-8a75-11e8-8f46-824bf9f6eea1.png)

## without_mkl
![image](https://user-images.githubusercontent.com/3048612/42856110-442cd66e-8a76-11e8-941e-6038ef542c45.png)

## 效果

op | without_mkl| with_mkl | with_mkl/without_mkl
---- | --- | --- | ---
mul |8398.83 |3249.81  |0.387
mul_grad |17069.3 |10266.5| 0.6015

**Comment by jacquesqiao** [comment]
## batch_size=64

## with_mkl
![image](https://user-images.githubusercontent.com/3048612/42856548-4322fe68-8a78-11e8-8d74-d2d33a810a2b.png)

## without_mkl
![image](https://user-images.githubusercontent.com/3048612/42856571-5defa1d8-8a78-11e8-98ae-6c90e1cd8732.png)

## 效果

op | without_mkl| with_mkl |  with_mkl/without_mkl
---- | --- | --- | ---
mul |16000 |15427  |0.9641875
mul_grad |31139 |33427| 1.073

**Comment by tensor-tang** [comment]
附上E5-2699v3，AVX2的机器 测试结果。

单核测试：

batchsize | openblas(ms) | mkl(ms) | mkl/openblas | openblas-ms
-- | -- | -- | -- | --
2 | 5.35 | 3.17 | 0.592523364 | 2.18
4 | 5.37 | 3.07 | 0.5716946 | 2.3
8 | 6.43 | 3.56 | 0.553654743 | 2.87
16 | 7.22 | 4.47 | 0.619113573 | 2.75
32 | 9.11 | 6.55 | 0.718990121 | 2.56
64 | 12.62 | 10.12 | 0.801901743 | 2.5

多核测试


bs              | MKL                     | MKL    | MKL    | MKL    | MKL    | OpenBLAS
--------------- | ----------------------- | ------ | ------ | ------ | ------ | --------
OMP_NUM_THREADS | 36                      | 18     | 10     | 4      | 1      | 1
Batch size=64   | time per iter(100iters) | 3.05ms | 3.13ms | 3.65ms | 4.97ms | 10.12ms  | 13.19ms
Batch size=2    | time per iter(100iters) | 1.76ms | 1.77ms | 1.87ms | 2.11ms | 3.17ms   | 5.35ms

**Comment by jacquesqiao** [comment]
在新型号的CPU上，batch_size为64时也能有30%以上的加速效果
