### ISSUE TITLE
CRNN-CTC train error

### ISSUE THREAD

**Issue by pmajchrzak** [PaddlePaddle/Paddle#12212]
# CRNN-CTC train error
During training crnn model (ocr_recognition) an errors occurs which most probably is placed in the paddle source.

> Traceback (most recent call last):
>   File "/root/models/paddle_models/fluid/ocr_recognition/ctc_train.py", line 193, in <module>
>     main()
>   File "/root/models/paddle_models/fluid/ocr_recognition/ctc_train.py", line 190, in main
>     train(args, data_reader=ctc_reader)
>   File "/root/models/paddle_models/fluid/ocr_recognition/ctc_train.py", line 51, in train
>     images, label, args, num_classes)
>   File "/root/models/paddle_models/fluid/ocr_recognition/crnn_ctc_model.py", line 186, in ctc_train_net
>     max_average_window=args.max_average_window)
>   File "/usr/local/lib/python2.7/dist-packages/paddle/fluid/optimizer.py", line 1174, in __init__
>     self._add_average_apply_op(block, param_grad)
>   File "/usr/local/lib/python2.7/dist-packages/paddle/fluid/optimizer.py", line 1183, in _add_average_apply_op
>     param = block.clone_variable(param_grad[0])
> AttributeError: '**Block' object has no attribute 'clone_variable'**

**Comment by luotao1** [comment]
This is due to https://github.com/PaddlePaddle/Paddle/pull/12107 change `clone_variable` to `_clone_variable`. But in `optimizer.py`, it still uses `clone_variable`.
https://github.com/PaddlePaddle/Paddle/blob/97b774dfe512b12e4916ee0e72c1cec8985fc06a/python/paddle/fluid/optimizer.py#L1182-L1190

We will fix it ASAP.

**Comment by pmajchrzak** [comment]
Super! Thx!
