### ISSUE TITLE
Fluid运行在GPU模式下，NCE不支持

### ISSUE THREAD

**Issue by liangyz23** [PaddlePaddle/Paddle#12255]
https://github.com/PaddlePaddle/Paddle/issues/11796 中提到如果运行在GPU模式下，某些不支持GPU的OP，可以自行运行在CPU上，复制过程不需要用户干预，但我在运行的时候，用到NCE，会报paddle.fluid.core.EnforceNotMet: op nce does not have kernel for data_type[float]:data_layout[ANY_LAYOUT]:place[CUDAPlace(1)]:library_type[PLAIN] at [/paddle/paddle/fluid/framework/operator.cc:640]
如果把GPU换成CPU就不会报错，所以觉得应该还是不支持GPU所致。
请教下怎么设置能让不支持GPU的layer单独在CPU模式下运行，其他的layer在GPU上呢？

**Comment by jacquesqiao** [comment]
nce_op有个地方需要修改一下，告诉框架这个op只支持cpu kernel。我们update一下
https://github.com/PaddlePaddle/Paddle/blob/6c981e7d3c80bbffd5064d1db35271e1e2a6cddd/paddle/fluid/operators/nce_op.cc#L173-L177

**Comment by liangyz23** [comment]
那我这边需要重新安装paddle吗？

**Comment by jacquesqiao** [comment]
fixed by https://github.com/PaddlePaddle/Paddle/pull/14385
