### ISSUE TITLE
soft relu就是leky relu吗

### ISSUE THREAD

**Issue by Emma-Ding** [PaddlePaddle/Paddle#12257]
请问一下soft relu就是leky relu吗？
![8f74d2bdf14810c119594fc6346255db](https://user-images.githubusercontent.com/22070158/42931734-0780fd14-8b73-11e8-8028-f66990a8e208.png)

**Comment by guoshengCS** [comment]
Paddle中softRelu的计算是`f(x) = log(1+exp(x))`，查了下leakyRelu的是`f(x)=alpha * x for x < 0, f(x) = x for x>=0`，这个Paddle好像还没有

**Comment by ktlichkid** [comment]
The issue seems to have already resolved. Please feel free to reopen it if you had further questions.
