### ISSUE TITLE
pipenv install paddlepaddle fail

### ISSUE THREAD

**Issue by smilefufu** [PaddlePaddle/Paddle#12267]
![image](https://user-images.githubusercontent.com/4025427/42981768-7ee13dea-8c10-11e8-832c-e26baed8672d.png)
Install fail on my macbook-pro. pip version 10.0.1, python version 2.7.14.
Seems like paddlepaddle don't support pip 10?

**Comment by yeyupiaoling** [comment]
@smilefufu Mac要在编译哦，http://www.paddlepaddle.org/docs/0.14.0/documentation/fluid/zh/new_docs/beginners_guide/install/install_doc.html#macospaddlepaddle
