### ISSUE TITLE
Anakin 预测问题

### ISSUE THREAD

**Issue by mzchtx** [PaddlePaddle/Paddle#12268]
### Anakin 预测问题
1. 当前 Anakin 已 release 版本为 [0.1.0](https://github.com/Shixiaowei02/Anakin/releases/download/v0.1.0/v_0_1_0.tar.bz2)，而 Paddle 当前使用为临时的 [2.0.1](https://github.com/pangge/Anakin/releases/download/3.0/anakin_release_simple.tar.gz) 版本。
2. 当前依赖的 Anakin 为动态库和头问题，而不是联编。
3. 使用 Anakin 预测的结果会变，为 CUDA 同步问题，在预测[这里](https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/fluid/inference/api/api_anakin_engine.cc#L60)前后加上全局同步问题问题可修复，当然也许有更好的方式：
    ```
    cudaDeviceSynchronize();
    executor_.prediction();
    cudaDeviceSynchronize();
    ```
    验证方式：使用同一幅图多次调用预测对比 diff 即可复现。
4. 在预测前的将数据从 PaddleTensor 拷贝到 Anakin input tensor 时未检查 PaddleTensor 的 shape 与 Anakin input tensor 的 shape：
    + 如果 PaddleTensor 的 shape 小于 Anakin input tensor 的 shape，需要对 Anakin input tensor 进行 reshape，否则拷贝会越界，出现 coredump，如 ocr 的默认。
	    ```
	    auto d_tensor_in_p = executor_.get_in(input.name);
	    anakin::saber::Shape img_shape;
	    for (auto s : input.shape) {
	        img_shape.push_back(s);
	    }
	    d_tensor_in_p->reshape(img_shape);
	    ```
    + 如果 PaddleTensor 的 shape 大于 Anakin input tensor 的 shape，需要对 Anakin Graph 进行 reshape，并且重新创建 Anakin Net，此时会涉及显存的再分配。
5. 预测后输出的 shape 应该是 Anakin output tensor 的 valid_shape()，而不是 shape()，[这里](https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/fluid/inference/api/api_anakin_engine.cc#L68)
6. 调用预测接口时指定的 output layer name 不对时会 core dump，不太友好，可能的解决方式：
    + Anakin 预测库返回错误码，而不是直接抛异常
    + 使用 Anakin 的接口获取 output，并 check 是否匹配
        ```
        Graph<NV, AK_FLOAT, Precision::FP32> graph;
        auto graph_outs = graph.get_outs();
        auto d_tensor_out_p = net_executer_p->get_out(graph_outs[0]);
        ```
7. 部分模型调用预测接口输入数据的 batch-size < max-batch-size 时会 core dump，测试模型为多输出的 ResNeXt50 模型。

**Comment by Superjomn** [comment]
@pangge 可以帮看看这个问题
