### ISSUE TITLE
Paddle如何实现L1正则化

### ISSUE THREAD

**Issue by xiaolv3366** [PaddlePaddle/Paddle#12263]
Paddle实现L2正则化：
optimizer = paddle.optimizer.AdaGrad(
        learning_rate=1e-1,
        regularization=paddle.optimizer.L2Regularization(rate=1e-3))
如何实现L1正则化？

**Comment by wanghaoshuang** [comment]
请参考这里： https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/fluid/regularizer.py#L170

**Comment by xiaolv3366** [comment]
PaddlePaddle V2版本实现L1正则化吗？@wanghaoshuang
