### ISSUE TITLE
Paddle 预测 API页面死链接

### ISSUE THREAD

**Issue by wanghaoshuang** [PaddlePaddle/Paddle#12277]
这个页面里的‘详细代码参考’章节给的两个例子都是死链接：
http://www.paddlepaddle.org/docs/0.14.0/documentation/fluid/zh/new_docs/user_guides/howto/inference/native_infer.html#permalink-4--

**Comment by shanyi15** [comment]
请@luotao1 和@ Superjomn 提供一下这两处最新的链接
![image](https://user-images.githubusercontent.com/35982308/42992814-41ad1666-8c3c-11e8-964a-8a4407467929.png)

**Comment by luotao1** [comment]
#12229 修复了develop版本，未修复0.14.0版本。
