### ISSUE TITLE
官方文档下载文件页面需添加md5校验

### ISSUE THREAD

**Issue by wanghaoshuang** [PaddlePaddle/Paddle#12278]
建议为这个页面提供下载的tar文件添加md5验证，以便用户检验下载是否正确。
http://www.paddlepaddle.org/docs/0.14.0/documentation/fluid/zh/new_docs/user_guides/howto/inference/build_and_install_lib_cn.html#permalink-1--

**Comment by shanyi15** [comment]
请文档作者 @Superjomn 看一下
