### ISSUE TITLE
定义的paddle.data_type.dense_array怎么feed

### ISSUE THREAD

**Issue by chenbblei** [PaddlePaddle/Paddle#12276]
audio_data = paddle.layer.data(
            name="test",
            type=paddle.data_type.dense_array(162,1))

怎么feed这个变量，有没有示例

**Comment by yeyupiaoling** [comment]
@chenbblei 如果是图片，那么name为image，type就是他的图片大小，

**Comment by wanghaoshuang** [comment]
`dense_array` 本质上和 `dense_vector`一样： https://github.com/PaddlePaddle/Paddle/blob/43d69818c0a962973e2035827a0fa1422c363dde/python/paddle/trainer/PyDataProvider2.py#L183

所以你可以参考`dense_vector`相关的例子: https://github.com/PaddlePaddle/models/search?q=dense_vector&unscoped_q=dense_vector
