### ISSUE TITLE
官网CAPI文档版本不明确

### ISSUE THREAD

**Issue by wanghaoshuang** [PaddlePaddle/Paddle#12280]
官网CAPI文档版本不明确
从当前页面，只能看出这是0.14.0版本的文档，但是无法直观分辨是fluid API还是V2 API.
http://www.paddlepaddle.org/docs/0.14.0/documentation/zh/howto/capi/workflow_of_capi_cn.html

**Comment by shanyi15** [comment]
目前官网的文档，fluid的文档在路径里会带**fluid**
http://www.paddlepaddle.org/docs/0.14.0/documentation/fluid/zh/new_docs/user_guides/howto/inference/native_infer.html
而v2文档则不带
http://www.paddlepaddle.org/docs/0.14.0/documentation/zh/howto/capi/index_cn.html
可以把v2的文档改成路径里带v2，辛苦@jetfuel看一下可行性
