### ISSUE TITLE
pip提供的包版本跟文档的不一样

### ISSUE THREAD

**Issue by yeyupiaoling** [PaddlePaddle/Paddle#12284]
在文档http://www.paddlepaddle.org/docs/0.14.0/documentation/fluid/zh/new_docs/beginners_guide/install/install_doc.html#linuxpaddlepaddle 的文档是说默认的是cuda9.0，cudnn7.0的
![image](https://user-images.githubusercontent.com/26297768/42994901-fe3d0c3c-8c41-11e8-9b53-27c02845357f.png)

但是实际我看到的不是这样的
https://mirrors.aliyun.com/pypi/simple/paddlepaddle-gpu/
![image](https://user-images.githubusercontent.com/26297768/42994971-303dc4f6-8c42-11e8-98d2-dea239d8b88d.png)

**Comment by typhoonzero** [comment]
`==0.14.0` 对应cuda9
`==0.14.0.post87` 对应cuda8 cudnn7
`==0.14.0.post85` 对应cuda8 cudnn5

是这样的，您遇到什么问题了呢

**Comment by yeyupiaoling** [comment]
@typhoonzero 你骗人！我在训练的时候遇到了这个问题，#12285

**Comment by typhoonzero** [comment]
没有版本号是`post97`，0.14默认是基于cuda9的，需要指定安装版本为`pip install paddlepaddle-gpu==0.14.0` pip 自动选择的版本会根据上传时间决定。

**Comment by yeyupiaoling** [comment]
@typhoonzero 打扰了打扰了，应该是正常的，可能是我机器的问题。

**Comment by yogurfrul** [comment]
@typhoonzero  我也遇到了 [一样的问题](https://github.com/PaddlePaddle/Paddle/issues/12711#issuecomment-413434415)
意思是版本选择是pip根据上传时间选择最近的？
不能根据环境来选择版本吗？
即使下错版本，安装前不能做下check下？check不满足打印给用户说要指定某某版本按照也好撒

**Comment by typhoonzero** [comment]
pip无法检测系统中的cuda, cudnn版本，pip本身机制无法满足。安装指定具体版本就行。

**Comment by procr** [comment]
> `==0.14.0` 对应cuda9
> `==0.14.0.post87` 对应cuda8 cudnn7
> `==0.14.0.post85` 对应cuda8 cudnn5
> 
> 是这样的，您遇到什么问题了呢

请问有cuda9的docker dev环境么？  我找了一圈都只有runtime环境。
