### ISSUE TITLE
flowers那个数据接口的训练集和测试集分别是多少数据？

### ISSUE THREAD

**Issue by yeyupiaoling** [PaddlePaddle/Paddle#12282]
在一个优化方法中，需要知道训练集有多张图片，我使用的是这个接口，flowers这个数据一共有8189张，这个接口在生存reader的时候是安装什么比例分成训练集和测试集的？

https://github.com/PaddlePaddle/Paddle/blob/b42ced8edab119b2a7b97cc7e235ed38dd26c6bc/python/paddle/v2/dataset/flowers.py#L134-L160

**Comment by oraoto** [comment]
数据集已经分成了在训练集`paddle.dataset.flowers.train`、测试集`paddle.dataset.flowers.test`、验证集`paddle.dataset.flowers.valid`。

可以这样看一个reader有多数据：

```
reduce(lambda x,y: x + 1, paddle.dataset.flowers.test()(), 0) # 1020
reduce(lambda x,y: x + 1, paddle.dataset.flowers.train()(), 0) # 6149
reduce(lambda x,y: x + 1, paddle.dataset.flowers.valid()(), 0) # 1020
```

**Comment by yeyupiaoling** [comment]
@oraoto 好的，谢谢，你是怎们看出来的，我怎么没看出来。

**Comment by oraoto** [comment]
[文档](http://paddlepaddle.org/docs/0.14.0/api/en/data/dataset.html)里有其他数据集，数据集接口基本都是这样设计的，自动补全一下就看到了。

**Comment by yeyupiaoling** [comment]
@oraoto 好的，谢谢您。
