### ISSUE TITLE
PaddlePaddle的control_flow问题

### ISSUE THREAD

**Issue by jayxio** [PaddlePaddle/Paddle#12296]
请问`array should be tensor array vairable`是什么错误？
```
import paddle.fluid as fluid
import numpy as np

exe = fluid.executor.Executor(fluid.CPUPlace())
exe.run(fluid.default_startup_program())

tmp = fluid.layers.zeros(shape=[10], dtype='int32')
#table = fluid.layers.lod_rank_table(tmp, level=0)
#array = fluid.layers.lod_tensor_to_array(tmp,table)
i = fluid.layers.fill_constant(shape=[1], dtype='int64', value=10)
arr = fluid.layers.array_read(tmp, i=i)

exe.run(fluid.default_main_program(), feed={'tmp':np.ones(shape=[10])}, fetch_list=[arr])
`````
报错：
TypeErrorTraceback (most recent call last)
<ipython-input-4-a7124c9a750e> in <module>()
      3 #array = fluid.layers.lod_tensor_to_array(tmp,table)
      4 i = fluid.layers.fill_constant(shape=[1], dtype='int64', value=10)
----> 5 arr = fluid.layers.array_read(tmp, i=i)

/usr/local/lib/python2.7/dist-packages/paddle/fluid/layers/control_flow.pyc in array_read(array, i)
   1100             array,
   1101             Variable) or array.type != core.VarDesc.VarType.LOD_TENSOR_ARRAY:
-> 1102         raise TypeError("array should be tensor array vairable")
   1103     out = helper.create_tmp_variable(dtype=array.dtype)
   1104     helper.append_op(

TypeError: array should be tensor array vairable

**Comment by jacquesqiao** [comment]
array_read的输入应该是一个lod_tensor_array，你现在创建的是一个普通的lod_tensor
