### ISSUE TITLE
在图片分类中，Fluid版本会输出两个准确率，我该相信那个呢？

### ISSUE THREAD

**Issue by yeyupiaoling** [PaddlePaddle/Paddle#12294]
比如下面是一个训练的过程
```
loss, acc1, acc5 = exe.run(test_program,
                                   fetch_list=fetch_list,
                                   feed=feeder.feed(data))
```
输出的有两个准确率，分别是`acc1`和`acc5`，他们的差距还是有点大的，那我使用哪个来判断这个模型训练的效果呢？
```
Pass 98, trainbatch 180, loss 1.43729066849, acc1 0.75, acc5 0.90625 time 0.11 sec
```

**Comment by oraoto** [comment]
这要看你的fetch_list里有哪些变量，还有它们的定义是什么吧？

**Comment by yeyupiaoling** [comment]
@oraoto 
在这里，有什么区别吗？
https://github.com/PaddlePaddle/models/blob/develop/fluid/image_classification/train.py#L162
```
fetch_list = [avg_cost.name, acc_top1.name, acc_top5.name]
```

**Comment by oraoto** [comment]
Top k Accuracy是指取模型最可能的k分类作为预测结果，只要k个中有一个是正确的就算分类正确，例如ImageNet的比赛就通常用Top 1和Top 5。

**Comment by yeyupiaoling** [comment]
@oraoto 哦哦，有点明白了，目前好像更多人是说Top 5的吧。谢谢您的解答。
