### ISSUE TITLE
多个loss，如何设置权重，如何在训练时查看各个loss的收敛情况

### ISSUE THREAD

**Issue by Emma-Ding** [PaddlePaddle/Paddle#12293]
多个loss， 在traner_config.conf里面的配置如下
```python
output2 = fc_layer(name="output2", input=sim, size=class_dim, act=SoftmaxActivation()) 
output3 = fc_layer(name="output3", input=concat_layer(input=revise_vec), size=class_dim, act=SoftmaxActivation())
    output1 = fc_layer(name="output", input=fc5, size=class_dim, act=SoftmaxActivation())
outputs([classification_cost(input=output1, label=lbl), classification_cost(input=output2, label=lbl), classification_cost(input=output3, label=lbl)])
```

请问如何设置每个loss的权重，以及如何查看训练时各个loss的收敛情况?

**Comment by JiayiFeng** [comment]
我可以给一些建议，但因为v1接口太过久远我自己也没有用过……所以可能使用上还是会有一些问题

1. 如何添加多个loss？ 在V2 api中，loss可以是一个list，将所有要做优化的lost都加到这个list里去就可以了。因为v1和v2使用的是同一个内核，应该是类似的方法。

2. 如何为各个loss设置不同的权重？ 很多cost layer有个`coeff`参数来表示自身在反向传播中的权重，这是一个float值，默认为1.0

3. 如何查看？  是否可以将他们直接打印出来呢？


如果可能的话，还请尽量迁移至最新的Fluid版本，我们未来的支持方向都会在这上面，V1 V2可能会逐渐减少~

**Comment by freekoy** [comment]
在fluid的cost layer中看到coeff的参数
但是 我需要的loss函数，在官方中没有，怎么自定义一个loss函数，并设置权重

**Comment by JiayiFeng** [comment]
Fluid的模型表示和V2是完全不同的，v2是layer by layer, Fluid是计算图。所以，在Fluid中只要把多个损失按照你想要的比例加起来，然后把和作为新的loss送入Optimizer去优化就行了。

事实上，在Fluid中，loss就是一个普通的variable，和其他的variable没有什么不同。你可以自己用数学计算组装出想要的loss，送给Optimizer去优化。
