### ISSUE TITLE
paddle/fluid/inference/api/api.cc中new delete语句不匹配

### ISSUE THREAD

**Issue by deerlu** [PaddlePaddle/Paddle#12308]
data_变量使用的new和delete语句不匹配。
https://github.com/PaddlePaddle/Paddle/blob/9c0fad4764b5834e8f03d511a8752d23c3311400/paddle/fluid/inference/api/api.cc#L56
https://github.com/PaddlePaddle/Paddle/blob/9c0fad4764b5834e8f03d511a8752d23c3311400/paddle/fluid/inference/api/api.cc#L71

**Comment by Superjomn** [comment]
这个好像不是问题。
