### ISSUE TITLE
请问是否对mobilenet模型进行测试过？ 能否提供一个可供测试的mobilenet模型？

### ISSUE THREAD

**Issue by xiebaiyuan** [PaddlePaddle/Paddle#12303]
请问是否对mobilenet模型进行测试过？ 能否提供一个可供测试的mobilenet模型？

**Comment by NHZlX** [comment]
模型配置参考这里：
https://github.com/PaddlePaddle/models/blob/develop/fluid/image_classification/models/mobilenet.py

**Comment by xiebaiyuan** [comment]
好的。多谢！
我试试
