### ISSUE TITLE
paddlepaddle-latest-cp27-cp27m-macosx_10_12_x86_64.whl can not install on mac

### ISSUE THREAD

**Issue by jacquesqiao** [PaddlePaddle/Paddle#12314]
invalid package name

**Comment by velconia** [comment]
@panyx0718, seems that ```latest``` is a invalid name for pip, we should follow [PEP 440](https://www.python.org/dev/peps/pep-0440/) to give it a ```version```, so maybe i'll change the version of ```develop``` branch back to v0.12.0 later

**Comment by panyx0718** [comment]
Perhaps 0.0.0 is better than 0.12.0? 0.0.0 means it's not quite stable

**Comment by velconia** [comment]
OK, I will put 0.0.0 to it
