### ISSUE TITLE
Fluid版本应该如何使用多个CPU

### ISSUE THREAD

**Issue by yeyupiaoling** [PaddlePaddle/Paddle#12329]
在V2版本中，如果我要设置多个CPU一起训练的话，我只要在初始化的时候指定就行，当然我是有多大指定多大的。
```python
paddle.init(use_gpu=False, trainer_count=2)
```

那么在Fluid版本中应该如何指定使用CPU的数量呢，我想全部使用机器的CPU。

**Comment by oraoto** [comment]
可以用ParallelExecutor：

```python
exe = fluid.parallel_executor.ParallelExecutor(use_cuda=False, num_trainers=2)
```

**Comment by yeyupiaoling** [comment]
@oraoto 我找到一个类似的接口http://paddlepaddle.org/docs/0.14.0/api/fluid/en/fluid.html#parallelexecutor
`num_trainers`好像是分布式的是的节点数吧，不是使用本地的线程数量吧？

**Comment by oraoto** [comment]
@yeyupiaoling 嗯，num_trainers分布式的。

ParallelExecutor默认会用全部的CPU:

https://github.com/PaddlePaddle/Paddle/blob/db67d60e31302065632a11b074f6f5dd83d6c5d5/python/paddle/fluid/parallel_executor.py#L116-L124

**Comment by yeyupiaoling** [comment]
@oraoto 好的，那太好了，不用我们自己设置了。
