### ISSUE TITLE
多目标任务，其中一个目标未被标记怎么处理

### ISSUE THREAD

**Issue by Yukizzz** [PaddlePaddle/Paddle#12334]
现在想实现一个多目标的任务，像这个issue中提到的
https://github.com/PaddlePaddle/Paddle/issues/4191
但是比如数据中存在两个目标中一个目标没有标注的情况，此时应该是按照被标注目标的cost计算的，请问怎样在网络配置中处理某个label并不存在的情况？或者说怎么给一条数据加一个标记，然后选择性的走某些层？

**Comment by dzhwinter** [comment]
按你写的例子
```python
loss2 = paddle.layer.cross_entropy_cost(
            input=out2, label=lbl, coeff=0.3)
paddle.evaluator.classification_error(input=out2, label=lbl)
extra_layers = [loss1, loss2]
```
加上ifelseop是不是可以满足需求呢?  根据该条数据中是否包含label，决定是否走true_block, false_block。 https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/fluid/tests/test_if_else_op.py

**Comment by Yukizzz** [comment]
@dzhwinter 
例子中的true和false使用的cond都是一个，这种写法两个block都会走，结果是最后false那一个block的对吧？

![6563c403-c472-4979-baeb-ae33db3cc27a](https://user-images.githubusercontent.com/9652571/43238710-e7613284-90c1-11e8-82dc-f9a156ce471d.JPG)

另外我想根据数据中cmatch_new这个字段决定走哪个层（给embedding和cnn层命名不同的名字），但是训练结束只有cmatch_label=2走的那个层才有参数保存下来，数据中cmatch_new这个字段值为1和2都有，请问是不是写法有问题，如何才能将两种层的参数都保存下来呀？word_emb和text_cnn函数是给各个层根据cmatch_label命名。
![e2f105fa-d110-4d62-96d5-38d1eee579af](https://user-images.githubusercontent.com/9652571/43240897-576ad0ea-90cb-11e8-9741-326a2292068f.JPG)

**Comment by dzhwinter** [comment]
在hi上已解决，给出的例子可以实现该功能。
