### ISSUE TITLE
帮忙看看是否文档有问题

### ISSUE THREAD

**Issue by jeff41404** [PaddlePaddle/Paddle#12338]
参考文档运行demo，发现出错：
File "./fluid_cifar.py", line 248, in main
    place=place)
  File "/usr/local/lib/python2.7/site-packages/paddle/fluid/trainer.py", line 109, in __init__
    raise TypeError("The optimizer should be an instance of Optimizer")
出错位置为：
trainer = fluid.Trainer(
    train_func=train_program,
    optimizer_func=optimizer_program,
    place=place)

查看fluid/trainer.py源码，修改为如下代码可以运行，帮忙看看是否文档有问题
trainer = fluid.Trainer(
    train_func=train_program,
    optimizer=optimizer_program(),
    place=place)

涉及文档：
http://www.paddlepaddle.org/docs/develop/book/01.fit_a_line/index.cn.html
http://www.paddlepaddle.org/docs/develop/book/02.recognize_digits/index.cn.html
http://www.paddlepaddle.org/docs/develop/book/03.image_classification/index.cn.html

**Comment by chenwhql** [comment]
你好，谢谢你提出的建议！
但我们并没有复现你的问题，是否可以提供更详细的操作过程描述以及错误信息？
此外，你修改之后的代码在语法上好像有些问题
![image](https://user-images.githubusercontent.com/22561442/43134744-a13a40e0-8f75-11e8-827c-9b56b3fc19a8.png)
首先，代码里的参数名是optimizer_func，所以修改成optimizer理论上是错误的
![image](https://user-images.githubusercontent.com/22561442/43134801-d721294e-8f75-11e8-8b4f-c959aeb7d86b.png)
其次，python函数作为参数传递的时候，是不加括号的，所以正确写法就是
```
optimizer_func=optimizer_program
```

**Comment by jeff41404** [comment]
我是用docker方式使用Paddle
版本：paddle-fluid-v0.13
镜像地址：registry.baidu.com/paddlecloud/paddlecloud-runenv-centos6u3-online:paddlecloud-v0.13.0-gcc482-cuda8.0_cudnn5
镜像介绍：http://paddlecloud.baidu-int.com/paddle/paddleVersion

另外查看了如上镜像中的fluid/trainer.py中__init__，好像和上面的截图也不一样，是不同版本的接口不一样？
![trainer init](https://user-images.githubusercontent.com/8555991/43621541-b6eeef7a-970a-11e8-857e-b126138a9b0d.JPG)

**Comment by jeff41404** [comment]
同时，试了一下，对于http://www.paddlepaddle.org/docs/develop/book/下的所有例子，在这个镜像中都要修改为 optimizer=optimizer_program() 才能正常运行

**Comment by lucywsq** [comment]
您好，此问题应该是和代码书写格式相关，建议您用值班同学的解决方案再次尝试~
此issue在近一个月内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题，我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持!
