### ISSUE TITLE
训练时全图读入（大小不一），使用batchsize=1，如何实现？

### ISSUE THREAD

**Issue by Naruto-Sasuke** [PaddlePaddle/Paddle#12333]
在官网的教程中，全部是固定大小的，例如（N*3*224*224)，那么我要进行全图输入（不进行任何resize和crop）。我输出的是也是一个图片。不过网络中有pool，所以这个输出的图片大小也是变化的。如何实现？

**Comment by oraoto** [comment]
一个实现的方法是为不同大小的输入都定义一个Program/网络，网络间共享全部的参数。

```python
# 网络，参数指定名字实现共享
def network(inp):
    y = fluid.layers.conv2d(
        input=inp, 
        filter_size=3,
        num_filters=3, 
        param_attr="conv1/w", 
        bias_attr="conv1/b")
    y = fluid.layers.pool2d(y, pool_size=2)
    y = fluid.layers.conv2d(
        input=y, 
        filter_size=3,
        num_filters=3, 
        param_attr="conv2/w", 
        bias_attr="conv2/b")
    y = fluid.layers.pool2d(y, pool_size=y.shape[2:]) # 输入FC层前要转层一样大小
    y = fluid.layers.fc(y, size=2, param_attr="fc/w", bias_attr="fc/b")
    return y

# 两个main program，一个共享的startup program
main_1 = fluid.Program()
main_2 = fluid.Program()
startup = fluid.Program()

# 第一个Program
with fluid.program_guard(main_1, startup):
    image1 = fluid.layers.data('image1', [3, 24, 24])
    y1 = network(image1)

# 第二个Program
with fluid.program_guard(main_2, startup):
    image2 = fluid.layers.data('image2', [3, 48, 48])
    y2 = network(image2)

# 初始化一次
exe = fluid.executor.Executor(fluid.CPUPlace())
exe.run(startup)
```

训练的时候根据输入大小选择对应的输入输出变量和Program即可。

比较麻烦:(，希望有更好的方法。

**Comment by dzhwinter** [comment]
@oraoto 感谢提供解答，不过您的办法不work。

图像大小是否固定是由网络性质决定的，例如fully convolutional network就可以适应不同大小的图像，对于大小不同的图像生成一个点或一个矩阵，但是对于alexnet就不可以。原因是有一些层并不是尺度不变的，以fc为例，网络中包含fc，那么固定位置的权重代表了对输入图像某个位置上的假设（改变图像大小会打破这个假设），因此一般选择将图像放缩到相同尺度，图像特征受到影响不大，而且实践证明这样损失很小。

1. 用类似fcn这样的模型，可以应用不同尺寸图像。 https://people.eecs.berkeley.edu/~jonlong/long_shelhamer_fcn.pdf

2. 不同图像都resize到同一尺度，crop只是为了增加训练样本的，做不做都可以。

**Comment by oraoto** [comment]
@dzhwinter  也注意到了这点，所以在FC层之前用pool转成了一样大小，的确是有局限性。

**Comment by Naruto-Sasuke** [comment]
@dzhwinter 不是。有些任务其实全图会更好一些。比如对于人流统计任务，我发现，如果用固定size进行训练，则效果会差一些。如果全图输入（size不断变化）则效果会好一些。最近百度之星的比赛，要求用paddle，所以也许有一个这样的教程会好一些。
