### ISSUE TITLE
Fluid版本该如何处理数据，为什么预测的结果都是一样的

### ISSUE THREAD

**Issue by yeyupiaoling** [PaddlePaddle/Paddle#12346]
我在做图片预测的时候，这样处理图片是能正常预测的，但是预测的结果不对，不管是什么图片，输出的都是同一个类别，我训练的是102flowers的图片，接口是`paddle.v2.dataset.flowers`

```python
    with fluid.scope_guard(inference_scope):
        # 加载模型
        [inference_program, feed_target_names, fetch_targets] = fluid.io.load_inference_model(model_path, exe)

        # 获取预测数据
        test_data = np.array(paddle.image.load_and_transform(image_file, 256, 224, False)).astype("float32")
        test_data = test_data[np.newaxis, :] / 255
        # 开始预测
        results = exe.run(inference_program,
                          feed={feed_target_names[0]: test_data},
                          fetch_list=fetch_targets)

        results = np.argsort(-results[0])
        # 打印预测结果
        print("The infer results label is: ", results[0][0])
```

**Comment by NHZlX** [comment]
你加载的模型是什么模型呢？ 是自己训练的flower102 分类模型么

**Comment by yeyupiaoling** [comment]
@NHZlX 是的。是不是我在预测的时候数据处理错了？训练的时候是正常的，准确率挺的

**Comment by yeyupiaoling** [comment]
@NHZlX 下面就是要预测的程序，包括了图片和模型
[infer100.zip](https://github.com/PaddlePaddle/Paddle/files/2226127/infer100.zip)

**Comment by yeyupiaoling** [comment]
@NHZlX 
我处理数据改成下面这个了，结果是有变化的，但是预测结果就是不正确（全部）
```python
# 获取预测数据
test_data = np.array(
paddle.image.load_and_transform(os.path.join(root_path, image_path), 256, 224, False)).astype("float32")
test_datas = [test_data]
test_data = np.array(test_datas)
```

**Comment by NHZlX** [comment]
训练脚本给我看一下，你先确保预测同训练数据的预处理是一样的

**Comment by yeyupiaoling** [comment]
@NHZlX 是一样的，数据我都是在测试集里面那出来的，附件中就是预测的代码。训练代码我是使用models下fluid的图片分类的，只是修改数据集而已，使用的是102flowers数据集，直接调用接口的。
https://github.com/PaddlePaddle/models/tree/develop/fluid/image_classification

[infer100.zip](https://github.com/PaddlePaddle/Paddle/files/2230407/infer100.zip)

我还是一块发训练代码吧，
[image_classification.zip](https://github.com/PaddlePaddle/Paddle/files/2230397/image_classification.zip)

**Comment by yeyupiaoling** [comment]
@NHZlX 
我修改了一个地方，就是把保存模型的接口改成下面这个方式：
```
fluid.io.save_inference_model(model_path, ['image'], [out0], exe)
```

原来的是这个
```
fluid.io.save_persistables(exe, model_path)
```

保存模型到底用哪个exe，这程序中有2个哦：
https://github.com/PaddlePaddle/models/blob/develop/fluid/image_classification/train.py#L141
https://github.com/PaddlePaddle/models/blob/develop/fluid/image_classification/train.py#L160

**Comment by NHZlX** [comment]
flowers 102 的图片的预处理, 要经过resize到224，将图像转成 CHW format， 减去均值[103.94, 116.78, 123.68] 过程。具体的可以看 paddle/python/paddle/v2/dataset/flowers.py

**Comment by yeyupiaoling** [comment]
@NHZlX 
我修改成下面这，准确率集好多了，我之前也是加上这个mean的，不知道这次为什么突然好那么多了。
```python
# 获取预测数据
test_data = np.array(
paddle.image.load_and_transform(image_path, 256, 224, False, mean=[103.94, 116.78, 123.68])).astype("float32")
test_datas = [test_data]
test_data = np.array(test_datas)
```

但是准确率还是不是高，我在训练的是acc1有0.8左右，acc5有0.95左右，我同样使用测试集作为预测数据统计了一下，只有0.78

>将图像转成 CHW format

这个上面代码有没有处理了？谢谢。

**Comment by NHZlX** [comment]
这个接口有对 `将图像转成 CHW format`处理，试一下`paddle.image.load_and_transform(root_path, image_path, 224, 224, False, mean=[103.94, 116.78, 123.68])).astype("float32")`

**Comment by yeyupiaoling** [comment]
@NHZlX 
但是数据集接口在训练的时候是这样的
https://github.com/PaddlePaddle/Paddle/blob/ec4c6e1f7cf627940b6a1e443421b35090aa70b7/python/paddle/v2/dataset/flowers.py#L64-L65

我修改成这样错误就低了一些0.772549

**Comment by NHZlX** [comment]
>> `我在训练的是acc1有0.8左右，acc5有0.95左右，我同样使用测试集作为预测数据统计了一下，只有0.786275` 

请确保你用的模型是0.8 acc1 的模型（因为随着训练，acc是存在波动的，存储的模型的acc也是波动的）。

**Comment by yeyupiaoling** [comment]
@NHZlX 应该是吧。主要的问题解决了，谢谢您。
