### ISSUE TITLE
fluid的sequence_conv_pool没有bias_attr参数吗？

### ISSUE THREAD

**Issue by Yukizzz** [PaddlePaddle/Paddle#12359]
sequence_conv_pool函数中没有bias_attr这个参数
![baiduhi_2018-7-25_16-41-53](https://user-images.githubusercontent.com/9652571/43189708-c9b852dc-9029-11e8-8ef0-760ecade1d0a.png)
但是调用的sequence_conv是有bias_attr参数的，
![baiduhi_2018-7-25_16-47-5](https://user-images.githubusercontent.com/9652571/43189928-679370e0-902a-11e8-9560-6bfbd88e9910.png)
![baiduhi_2018-7-25_16-51-10](https://user-images.githubusercontent.com/9652571/43190282-405b08ac-902b-11e8-81ae-49a77880ea47.png)

如果要配置sequence_conv_pool的bias_attr的话只能直接调用sequence_conv + sequence_pool？
可否麻烦直接在sequence_conv_pool中加一下呢？

**Comment by Superjomn** [comment]
可以帮看看么 @qingqing01
