### ISSUE TITLE
用自己的数据训练SSD样例时出错

### ISSUE THREAD

**Issue by zhengzhe97** [PaddlePaddle/Paddle#12351]
An error ocurred while starting the kernel
I0722 13:27:58.929406 5872 Util.cpp:166] commandline: ‑‑use_gpu=True ‑‑trainer_count=2 
I0722 13:28:02.449893 5872 MultiGradientMachine.cpp:99] numLogicalDevices=1 numThreads=2 numDevices=1
F0722 13:28:02.449947 5872 MultiGradientMachine.cpp:104] trainer_count * num_devices_in_model (2*1)=2 exceeds number of GPU devices(1)
*** Check failure stack trace: ***
@ 0x7f1aefadc13d google::LogMessage::Fail()
@ 0x7f1aefadfbec google::LogMessage::SendToLog()
@ 0x7f1aefadbc63 google::LogMessage::Flush()
@ 0x7f1aefae10fe google::LogMessageFatal::~LogMessageFatal()
@ 0x7f1aef8051a6 paddle::MultiGradientMachine::MultiGradientMachine()
@ 0x7f1aef808b9f paddle::GradientMachine::create()
@ 0x7f1aefab8a25 GradientMachine::createFromPaddleModelPtr()
@ 0x7f1aefab8c0f GradientMachine::createByConfigProtoStr()
@ 0x7f1aef65fc67 _wrap_GradientMachine_createByConfigProtoStr
@ 0x7f1b79d94210 PyEval_EvalFrameEx
@ 0x7f1b79d974e9 PyEval_EvalCodeEx
@ 0x7f1b79d949b8 PyEval_EvalFrameEx
@ 0x7f1b79d974e9 PyEval_EvalCodeEx
@ 0x7f1b79d949b8 PyEval_EvalFrameEx
@ 0x7f1b79d974e9 PyEval_EvalCodeEx
@ 0x7f1b79d20377 function_call
@ 0x7f1b79cfb7a3 PyObject_Call
@ 0x7f1b79d0a63d instancemethod_call
@ 0x7f1b79cfb7a3 PyObject_Call
@ 0x7f1b79d54584 slot_tp_init
@ 0x7f1b79d50e3b type_call
@ 0x7f1b79cfb7a3 PyObject_Call
@ 0x7f1b79d91b69 PyEval_EvalFrameEx
@ 0x7f1b79d974e9 PyEval_EvalCodeEx
@ 0x7f1b79d949b8 PyEval_EvalFrameEx
@ 0x7f1b79d974e9 PyEval_EvalCodeEx
@ 0x7f1b79d9770a PyEval_EvalCode
@ 0x7f1b79db09cd run_mod
@ 0x7f1b79db1b48 PyRun_FileExFlags
@ 0x7f1b79d8b247 builtin_execfile
@ 0x7f1b79d94210 PyEval_EvalFrameEx
@ 0x7f1b79d974e9 PyEval_EvalCodeEx

**Comment by qingqing01** [comment]
>  trainer_count * num_devices_in_model (2*1)=2 exceeds number of GPU devices(1)

看样子你的机器上只有一个GPU，而你配置了`‑‑trainer_count=2` 使用2个卡训练。
