### ISSUE TITLE
fluid里面是否有v1 的tensor_layer类似的op

### ISSUE THREAD

**Issue by Emma-Ding** [PaddlePaddle/Paddle#12363]
之前使用的v1版本，model还用了tensor_layer，使用如下，现在迁到fluid上，想问问如何实现类似的操作

`user_emb1 = fc_layer(name="user_emb1", input=concat_layer(input=user_emb_vec), size=256, act=ReluActivation())
    user_emb2 = fc_layer(name="user_emb2", input=user_emb1, size=128, act=ReluActivation())
    user_emb3 = fc_layer(name="user_emb3", input=user_emb2, size=64, act=ReluActivation())
    user_emb4 = fc_layer(name="user_emb4", input=user_emb3, size=32)
    user_emb5 = fc_layer(name="user_emb5", input=user_emb4, size=16)

    user_cross1 = fc_layer(name="user_cross1", input=concat_layer(input=user_emb_vec), size=128, act=LinearActivation())
    user_cross2_raw = tensor_layer(name="user_cross2_raw", a=user_cross1, b=user_cross1, size=128, act=LinearActivation())
    user_cross2 = user_cross2_raw + user_cross1

    user_cross3_raw = tensor_layer(name="user_cross3_raw", a=user_cross2, b=user_cross1, size=128, act=LinearActivation())
    user_cross3 = user_cross3_raw + user_cross2`

**Comment by Superjomn** [comment]
有对应的代码片段吗，可以描述详细些

**Comment by Emma-Ding** [comment]
@Superjomn 
```
user_emb1 = fc_layer(name="user_emb1", input=concat_layer(input=user_emb_vec), size=256, act=ReluActivation())
    user_emb2 = fc_layer(name="user_emb2", input=user_emb1, size=128, act=ReluActivation())
    user_emb3 = fc_layer(name="user_emb3", input=user_emb2, size=64, act=ReluActivation())
    user_emb4 = fc_layer(name="user_emb4", input=user_emb3, size=32)
    user_emb5 = fc_layer(name="user_emb5", input=user_emb4, size=16)

    user_cross1 = fc_layer(name="user_cross1", input=concat_layer(input=user_emb_vec), size=128, act=LinearActivation())
    user_cross2_raw = tensor_layer(name="user_cross2_raw", a=user_cross1, b=user_cross1, size=128, act=LinearActivation())
    user_cross2 = user_cross2_raw + user_cross1

    user_cross3_raw = tensor_layer(name="user_cross3_raw", a=user_cross2, b=user_cross1, size=128, act=LinearActivation())
    user_cross3 = user_cross3_raw + user_cross2
```

**Comment by Superjomn** [comment]
`tensor_layer` 的操作是

```
y_{i} = a * W_{i} * {b^\mathrm{T}}
```

参考 https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/trainer_config_helpers/layers.py#L5127

目前好像没有这个 op，@kuke 帮看看能不能 slice 拼出来吧

**Comment by kuke** [comment]
到目前为止没有这样的layer，应该可以用fc和乘法拼出来
