### ISSUE TITLE
向量相乘后生成的矩阵，再加上原始向量怎么实现？

### ISSUE THREAD

**Issue by Emma-Ding** [PaddlePaddle/Paddle#12362]
问题描述：有两个向量，x，x0，想实现如下操作，请问要怎么怎样实现，w是优化要求得的参数

<img width="139" alt="2018-07-25 5 04 03" src="https://user-images.githubusercontent.com/22070158/43191591-0978e054-902e-11e8-987f-ffe95cb6abf1.png">
<img width="369" alt="2018-07-25 5 04 11" src="https://user-images.githubusercontent.com/22070158/43191606-1078bcbc-902e-11e8-90d2-d2a768d12558.png">

个人理解： x, x0的的向量相乘可以通过fluid.layers.matmul实现，但是对于每一行权值共享w，又不做filter，这个好像没有看到解决办法，目前的思路是做fc全连接，输出维度的【1，64】然后加上维度是【-1，64】的x，但是生成的数据维度变为了【1，64】，代码如下

```python
user_cross0 = fluid.layers.fc(name="user_cross_0", input=user_fc0, size=64)
    user_cross_raw1 = fluid.layers.matmul(name="user_cross_raw1", x=user_cross0, y=user_cross0, transpose_x=True, transpose_y=False)
    user_cross_raw2 = fluid.layers.reshape(name="user_cross_raw2", x=user_cross_raw1, shape= [1, 64 * 64])
    #print user_cross_raw2.shape
    user_cross_scale_1 = fluid.layers.fc(input=user_cross_raw2, size=64)
    user_cross_1 = user_cross_scale_1 + user_cross0

```

问题是：（1）是否可以有对一个matrix的每一行都采用一个w做权值共享的操作
               （2）按照我的理解做的相加操作是否可行

**Comment by Superjomn** [comment]
> w做权值共享

这个意思是每行 vector 加一个 scalar？

**Comment by Emma-Ding** [comment]
就是矩阵乘法，但是因为w是待求参数，所以想问问有没有方法操作

**Comment by Superjomn** [comment]
现在是卡在 

> 加上原始向量

了么

看了下好像操作应该都是标准的，op好像都支持了。

**Comment by ktlichkid** [comment]
有个elementwise_add的layer您可以试一下~
如果shape有差异也可以用sequence_expand等

**Comment by kuke** [comment]
Closed due to be resolved
