### ISSUE TITLE
本地和集群跑程序，使用sparse报错。

### ISSUE THREAD

**Issue by shiyazhou121** [PaddlePaddle/Paddle#12377]
本地报错
![image](https://user-images.githubusercontent.com/15082798/43239926-b7e85f00-90c6-11e8-8444-f922e172ef27.png)
集群报错
![image](https://user-images.githubusercontent.com/15082798/43239945-d24e5bba-90c6-11e8-855e-d890b1474e78.png)
网络配置
![image](https://user-images.githubusercontent.com/15082798/43239952-def3465a-90c6-11e8-9f76-eeacadd23f28.png)

**Comment by seiriosPlus** [comment]
sparse的能在CPU下进行验证么，sparse的在V2版本下不支持GPU

**Comment by shiyazhou121** [comment]
@seiriosPlus 单机情况下，使用CPU是可以训练的。但是怎么改成GPU呢？是更新版本吗？
还有集群训练是用的CPU，还是报错，求看看啥情况。。http://10.73.47.34:8900/fileview.html?path=/home/disk1/normandy/maybach/app-user-20180726102002-11632/

**Comment by shiyazhou121** [comment]
@seiriosPlus 貌似问题是我在网络配置中的sparse data layer 和 fc层之间加了dropout。现在的v2不支持这样用吗？
![image](https://user-images.githubusercontent.com/15082798/43242890-14ba0eae-90d6-11e8-9e15-0634761c28e8.png)
![image](https://user-images.githubusercontent.com/15082798/43242898-1b712e6c-90d6-11e8-8816-5cb2379ff6dd.png)

**Comment by seiriosPlus** [comment]
目前V2不支持这么用， 可以考虑迁移到Fluid。
