### ISSUE TITLE
Detction MAP 一直很低，接近于0？

### ISSUE THREAD

**Issue by youngstu** [PaddlePaddle/Paddle#12372]
![selection_001](https://user-images.githubusercontent.com/26452514/43238039-fddbaf10-90be-11e8-883c-92ff3b9c68c0.png)

```
paddle.evaluator.detection_map(
                input=detection_out,
                label=bbox,
                overlap_threshold=0.5,
                background_id=0,
                evaluate_difficult=False,
                ap_type='11point',
                name='detection_evaluator')
```

**Comment by youngstu** [comment]
[ar@yq01-gpu-255-100-26-00 v10_4_1]$ paddle version
PaddlePaddle 0.11.0, compiled with
    with_avx: ON
    with_gpu: ON
    with_mkl: ON
    with_mkldnn: ON
    with_double: OFF
    with_python: ON
    with_rdma: OFF
    with_timer: OFF

**Comment by qingqing01** [comment]
看样子你用的是Paddle V2的检测， 请问使用预训练模型了吗？

**Comment by youngstu** [comment]
有使用预训练模型

**Comment by seiriosPlus** [comment]
这个暂时先使用v1的API吧，后续可以考虑迁移到 Fluid @youngstu

**Comment by lucywsq** [comment]
您好，此issue在近一个月内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题， 我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持!
