### ISSUE TITLE
paddlepaddle install problem

### ISSUE THREAD

**Issue by yyHaker** [PaddlePaddle/Paddle#12386]
I use pip install the paddlepaddle on my ubuntu system, but when I run the "import paddle", it gives the errors below:
"'"
ImportError: libmkldnn.so.0: cannot open shared object file: No such file or directory
""
what is wrong with it?

**Comment by seiriosPlus** [comment]
reference:
https://github.com/PaddlePaddle/Paddle/blob/develop/doc/fluid/new_docs/faq/faq.rst

**Comment by yyHaker** [comment]
3q
