### ISSUE TITLE
关于序列数据输入后打印tensor dim的问题

### ISSUE THREAD

**Issue by 333caowei** [PaddlePaddle/Paddle#12380]
我有一个id list输入给模型，每个id代表一个词，例如[9,8,3,4,5]
```
query_data = fluid.layers.data(
         name="query",
         shape=[1],
         dtype='int64',
         lod_level=1)

query_emb = fluid.layers.embedding(
             input=query_data,
             size=[VOCAB_DICT_SIZE, 128],
             is_sparse=IS_SPARSE)
print query_emb

```
可是print query_emb信息如下：
```
type {
  type: LOD_TENSOR
  lod_tensor {
    tensor {
      data_type: FP32
      dims: -1
      dims: 128
    }
    lod_level: 1
  }
}
persistable: false
```
为什么query_emb的dim是2维的呢，第一维-1表示batchsize，第二维128表示向量dim，应该还有第三维表示序列长度才对

**Comment by qingqing01** [comment]
@333caowei embedding层的输出确实是2维的，data层设置了`lod_level=1`，表示是个序列，
你上面的配置，在Fluid里确实是2维矩阵：[-1, 128]， -1这维度有个LoD表示样本的序列长度，同时也能得到batch size。

例如输入2个样本，第一个样本2个时间步、第二样本3个时间步，embedding的输出会是：

 tensor.shape: [5, 128],
 lod: [0, 2, 5]，# 存储了每个样本的偏移 [0, 1]是第一个样本，[2,3,4]是第二个样本。

通过lod即能得到batch size，也能得到每个样本的时间步长度。
