### ISSUE TITLE
Temporally disable rpc_server_test 

### ISSUE THREAD

**Issue by chengduoZH** [PaddlePaddle/Paddle#12381]
`rpc_server_test ` prevents this PR(#12369), so I temporally disable it. @Yancey1989 will help to enable it later.

**Comment by Yancey0623** [comment]
Will do that after it merged.

**Comment by Yancey0623** [comment]
Already fixed by https://github.com/PaddlePaddle/Paddle/pull/12369/commits/47ab0792d88615b5553daf47a0140784d6189b76 , will close this issue.
