### ISSUE TITLE
paddle v2版本中，如果要对一个网络进行多尺度预测(输入的图像大小不一样），怎样定义网络？

### ISSUE THREAD

**Issue by YongtaoGE** [PaddlePaddle/Paddle#12388]
```
def network(img_h,img_w):
   img = paddle.layer.data(name='image', 
                   type=paddle.data_type.dense_vector(3*img_h*img_w),height=img_h,width=img_w)
   conv1_out_h = img_h - 2
   conv1_out_w = img_w - 2
   prelu1 = paddle.layer.prelu(name='prelu1',input=conv1,partial_sum=conv1_out_h*conv1_out_w) 
   ...
   return layer_out
```
假如定义一个全卷积的网络，每次输入的图像尺寸不一样，怎样定义网络，我使用以下代码，会报错：
```
paddle.init(use_gpu=False)
layer_out = network(img_h1,img_w1)
layer_out = network(img_h2,img_w2)
```

**Comment by seiriosPlus** [comment]
是否能在输入输入数据前加入预处理？

**Comment by YongtaoGE** [comment]
你好，我是想实现人脸检测的网络MTCNN的PNet,这个全卷积网络的作用相当于一个固定大小的滑动窗口在不同尺度的图片上扫一遍(比如图片大小是h,w,会把图片进行降采样，所以输入的图片大小是不相同的），不知道有没有比较好的解决办法。

**Comment by YongtaoGE** [comment]
我觉得主要问题是第一次调用network（）函数之后网络已经被初始化一遍了，但我没有找到清除网络参数的办法，再次调用network（）函数输入不同大小的数据就会报错。

**Comment by qingqing01** [comment]
对于Paddle V2，可以参考：

https://github.com/PaddlePaddle/DeepSpeech/blob/422f55a5d3f04f8b57d6859d7c7a7505c034c9da/model_utils/model.py#L409-L414

        # paddle.data_type.dense_array is used for variable batch input.
        # The size 161 * 161 is only an placeholder value and the real shape
        # of input batch data will be induced during training.
        audio_data = paddle.layer.data(
            name="audio_spectrogram",
            type=paddle.data_type.dense_array(161 * 161))

支持训练的变长图片输入，reader里返回numpy array即可。

V2 FAQ: http://paddlepaddle.org/docs/0.14.0/documentation/zh/faq/model/index_cn.html#paddlepaddle

但Fluid更灵活吧，也欢迎使用Fluid。

**Comment by YongtaoGE** [comment]
因为这个网络有一个prelu层，这一层依赖于第一次卷积得到的feature map的尺寸，所以不只是数据的输入维度是变化的，prelu的`partial_sum`参数也需要动态调整，请问有解决方案吗？

按照以下代码依然在第二次调用`network()`函数的数据输入层就报错：
```
def network(img_h,img_w):
   img = paddle.layer.data(name='image', 
                   type=paddle.data_type.dense_vector(3*img_h*img_w),height=img_h,width=img_w)
   conv1_out_h = img_h - 2
   conv1_out_w = img_w - 2
   prelu1 = paddle.layer.prelu(name='prelu1',input=conv1,partial_sum=conv1_out_h*conv1_out_w) 
   .
   return layer_out

paddle.init(use_gpu=False)
layer_out = network(img_h1,img_w1)
layer_out = network(img_h2,img_w2)
```
不知是否可以调用paddle中计算某个层输出feature map尺寸的函数，赋值给`prelu`层的`partial_sum`参数。
但我没有找到这样的函数。

**Comment by qingqing01** [comment]
@yongtaoge Paddle V2的prelu不支持这样操作。

**Comment by YongtaoGE** [comment]
@qingqing01 好的，谢谢啦。看来只能做单尺度的预测了。还有一个问题就是paddle v2的prelu接受的层必须是包含channel,height和width的张量。我发现全连接层fc的输出只有size这个参数，channel，height和width的值均为零。fc的输出送给prelu层可以得到正确的结果吗？

**Comment by qingqing01** [comment]
fc的输出可以作为prelu的输入。Paddle V2的`prelu_layer`比较僵硬。 设置：

```
channel_shared=None
partial_sum=1 # 或fc的hidden size
num_channels= fc_size # fc的hidden size
```

@yongtaoge  感谢使用，Fluid会比Paddle V2好很多。

**Comment by YongtaoGE** [comment]
再次感谢！
