### ISSUE TITLE
请问有没有各个网络的ImageNet训练好的模型Cffe转Fluid 的

### ISSUE THREAD

**Issue by yeyupiaoling** [PaddlePaddle/Paddle#12396]
我在这里https://github.com/PaddlePaddle/models/tree/develop/fluid/image_classification/caffe2fluid 看到有caffe装FLuid教程，但是没有找到训练好的ImagesNet的模型。特别是MobileNet，ResNet，Inception。

**Comment by qingqing01** [comment]
https://github.com/PaddlePaddle/models/tree/develop/fluid/image_classification#supported-models-and-performances

图像分类的教程里发布了Fluid框架训练的ImageNet模型，包括ResNet, SE-ResNeXt, AlexNet。 Inception等还没发布，后续可能会发布。

**Comment by yeyupiaoling** [comment]
@qingqing01 嗯嗯，我有看到呢，就是太少了。那有没有Caffe的模型呢，我转换一下，我在网上兜里一圈，没找到全面一些的caffe模型。

**Comment by yeyupiaoling** [comment]
@qingqing01 [这些模型](https://github.com/PaddlePaddle/models/tree/develop/fluid/image_classification/caffe2fluid#tested-models)是训练ImageNet的吗？有没有Caffe的MobileNetV1，MobileNetV2，InceptionV3的模型下载呢？能否介绍一下，谢谢。

**Comment by qingqing01** [comment]
@yeyupiaoling  Caffe的模型需要去Caffe官网或网上搜索去找。

**Comment by yeyupiaoling** [comment]
@qingqing01 哈哈，我找到了TensorFlow的，caffe的目前还没找到，但是这个TensorFlow的很详细的，您看https://github.com/tensorflow/models/tree/master/research/slim#pre-trained-models

我看到V2版本有TensorFlow转换的工具https://github.com/PaddlePaddle/models/tree/develop/image_classification/tf2paddle ，Fluid版本有吗？转换成预测模型的。
