### ISSUE TITLE
tensor_layer的源码

### ISSUE THREAD

**Issue by Emma-Ding** [PaddlePaddle/Paddle#12394]
能否贴一个tensor_layer的底层源码?

**Comment by seiriosPlus** [comment]
可以看
https://github.com/PaddlePaddle/Paddle/blob/71b1c397d7d7cf7cc02c274fb2d69aaf7f794933/paddle/legacy/gserver/layers/TensorLayer.h
https://github.com/PaddlePaddle/Paddle/blob/71b1c397d7d7cf7cc02c274fb2d69aaf7f794933/paddle/legacy/gserver/layers/TensorLayer.cpp

**Comment by lucywsq** [comment]
您好，此issue在近一个月内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题， 我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持!
