### ISSUE TITLE
有关fluid ifelse写法的问题

### ISSUE THREAD

**Issue by Yukizzz** [PaddlePaddle/Paddle#12395]
我希望数据根据cmatch_new这个特征值的不同走不同的层，因此引入ifelse~
具体操作在两个block中分别传入dim不同的layer，然后用block返回的dim作为cmatch_label（很蠢的做法，求指导），希望这个cmatch_label不同的数据走不同的层。
![392483762d58a1537061a946a33fc9cb](https://user-images.githubusercontent.com/9652571/43266541-3d7ccb7c-911e-11e8-995b-8bc8100cb9da.JPG)

但是我的数据中cmatch_new都为2，并不符合cond，按理应该走false的层？但是产出的层都是true对应的。
把判断条件换反之后还是只有true对应的参数…请问这个是啥原因呀？求帮忙看下我的写法有问题不~？

**Comment by jacquesqiao** [comment]
`产出的层都是true对应的` 这个是怎么判断的？

**Comment by Yukizzz** [comment]
true的input是age，age的shape[1]是1，我理解ifelse返回的layer的shape[1]也是1，对应的cmatch_label是1。
false的input是total_profile_fea的shape[1]=2，对应的cmatch_label是2。
最后产出的模型参数cmatch_label都是1。

**Comment by Yukizzz** [comment]
![baiduhi_2018-7-26_22-16-29](https://user-images.githubusercontent.com/9652571/43299404-a306416c-918c-11e8-8fe1-b61e5838f10b.png)
更新了一个代码的图片，其中word_emb和text_cnn函数是给各个层根据cmatch_label重命名。

**Comment by lucywsq** [comment]
您好，此issue在近一个月内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题， 我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持!
