### ISSUE TITLE
是否可以将需要的配置，定义到配置文件？

### ISSUE THREAD

**Issue by yangjingyuan** [PaddlePaddle/Paddle#12405]
编译PaddleFluid 遇到了不少问题，其实整体逻辑还是比较清晰的，如果要是能将一些配置通过配置文件的形式，显式的定义出来会不会更好

**Comment by yangjingyuan** [comment]
再就是有些库如果用户配置，有的话，可能就不需要下载了

**Comment by luotao1** [comment]
@yangjingyuan 碰到的问题：
1. nccl.h 报错找不到，但发现该源文件是存在的
![image](https://user-images.githubusercontent.com/6836917/43305497-96b09ad4-91aa-11e8-8a52-7a97b79d95a9.png)
   - 原因：用户并不清楚是nccl库的nccl.h找不到，以为是fluid中的nccl.h找不到，报错机制并不完善。同时用户发现已经安装了nccl，但不清楚是要加入LD_LIBRARY_PATH还是哪里设置下？
   - 解决方案：临时解决的话，可以把安装的那个nccl.h 手动cp到$builddir/third_party/install/warpctc/include/。
2. cp过去后，发现新错误
![image](https://user-images.githubusercontent.com/6836917/43305646-244d7a92-91ab-11e8-8fe0-d85fb467564d.png)
   - 原因：用户装的是nccl，并不是nccl2。用户不知道要装nccl2，无报错信息。
   - 解决方案：让用户重新安装nccl2，用户提议能否直接做到thirdparty里下载，不需要安装。
3. 新问题，cmake版本不一致
![image](https://user-images.githubusercontent.com/6836917/43305747-6f61ef0e-91ab-11e8-9b1b-3795ffb20d64.png)
![image](https://user-images.githubusercontent.com/6836917/43305801-9873bac6-91ab-11e8-8950-0e85167d08a2.png)

   - 原因：用户使用的cmake版本太高了，是3.12。但用户不知道cmake要用哪个版本。
   - 解决方案：让用户使用3.4-3.6中的某一个版本。

@JiabinYang

**Comment by lucywsq** [comment]
您好，此issue在近一个月内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题， 我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持!
