### ISSUE TITLE
mac使用docker镜像安装cpu-only的paddle报错未下载patchelf

### ISSUE THREAD

**Issue by topxxuki** [PaddlePaddle/Paddle#12407]

**Comment by topxxuki** [comment]
报错信息如下：
CMake Error at python/CMakeLists.txt:103 (message):
  patchelf not found, please install it.

  For Ubuntu, the command is: apt-get install -y patchelf.


-- Configuring incomplete, errors occurred!

在docker尝试使用apt-get install -y patchelf解决报错如下：.
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package patchelf.
E: Couldn't find any package by glob 'patchelf.'
E: Couldn't find any package by regex 'patchelf.'

在docker外使用brew install patchelf 下载了patchelf 0.9 重启doker依旧显示未安装patchelf

**Comment by luotao1** [comment]
请问您使用的是最新develop分支的代码么？

**Comment by topxxuki** [comment]
如何确认是否用的是develop分支的代码呢？

**Comment by luotao1** [comment]
git log 看下

**Comment by topxxuki** [comment]
的确在develop分支下

**Comment by ktlichkid** [comment]
我也试了下，目前docker里面应该是装了patchelf，并且用apt-get安装也能正常装，复现不了这个问题。
您是用的哪个docker镜像？是latest-dev吗？

**Comment by topxxuki** [comment]
是这个镜像

**Comment by topxxuki** [comment]
是这个镜像

**Comment by topxxuki** [comment]
使用docker可以检索到一个patchelf
<docker search patchelf
NAME                DESCRIPTION         STARS               OFFICIAL            AUTOMATED
onedata/patchelf                        0
>
需要下载这个吗

**Comment by topxxuki** [comment]
手动编译后解决了这个问题
