### ISSUE TITLE
mpi训练模型之后无法保存到指定HDFS路径

### ISSUE THREAD

**Issue by yuanxiangxie** [PaddlePaddle/Paddle#12410]
经过查看日志信息，发现代码没有执行 『将目录移到output』这段代码。具体如图
![image](https://user-images.githubusercontent.com/9253455/43315484-a9a64a94-91c8-11e8-9887-133f1346cd76.png)
![image](https://user-images.githubusercontent.com/9253455/43315553-e3df265e-91c8-11e8-885f-0b82e6872fca.png)

**Comment by typhoonzero** [comment]
是v2 API的话，把那个move放到`event_handler`的PassEnd里。

**Comment by yuanxiangxie** [comment]
嗯，感谢。经过测试发现可用~

**Comment by lucywsq** [comment]
您好，此issue在近一个月内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题， 我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持!
