### ISSUE TITLE
Why the GRU layer does not include weighing of the input?

### ISSUE THREAD

**Issue by wojtuss** [PaddlePaddle/Paddle#12413]
The dynamic GRU algorithm described in the documentation (http://paddlepaddle.org/docs/0.14.0/api/fluid/en/layers.html#dynamic-gru) includes multiplication of the input x<sub>t</sub> by weight matrices W<sub>x</sub>, but the PaddlePaddle's implementation of the operator does not include this operation.

Here are my questions:
1. Why is that?
2. Could the usual FC layer (actually the MUL operator) preceding the dynamic GRU op be incorporated into GRU in nn.py?
3. Could the combination of two FC layers with two GRUs for the two opposite directions (like in the CRNN-CTC model) be joined in nn.py into a single bidirectional variant of the GRU op?

Changes proposed in 2. and 3. would allow for significant optimization using a single MKL-DNN's GRU operator.

**Comment by guoshengCS** [comment]
Thanks for the proposal. The purpose of that is to be consistent with the original implement, see 
https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/trainer_config_helpers/layers.py#L1605. For changes proposed 2. and 3., maybe other python wrappers can be added temporarily 
to be compatible with some current OCR and NLP models in the Production Line use.

**Comment by wojtuss** [comment]
@guoshengCS , thanks for the answer!
Maybe you could give us some advice on the following:
When training a model with GRU layer on GPU, the weights for the FC and GRU layers are stored separately, right?
To be able to do inference with MKL-DNN GRU op the weights have to be loaded as one tensor.
Is there any (considerably simple) way to achieve this?

**Comment by guoshengCS** [comment]
As you rightly say, the weights for the FC and GRU layers are stored separately. Furthermore, the weights in GRU may also different with MKL-DNN GRU op: For the weight tensor with shape `size * 3 * size` in GRU, weights of update gate and reset gate reside in the first `size * 2 * size` and are concatenated(to do matrix multiplication simultaneously), the remaining `size * size` elements are the weights of candidate. 
If training with current GRU while inference with MKL-DNN's GRU maybe we should assemble a new weight tensor externally first, or insert some operators such as concat, split in the python wrapper of MKL-DNN's GRU to assemble a new weight tensor.

**Comment by wojtuss** [comment]
@guoshengCS, thanks for your help!
