### ISSUE TITLE
关于输入大小不一的图像的问题，官方文档说只要设置比输入数据维数大的值占位即可，但报错

### ISSUE THREAD

**Issue by freekoy** [PaddlePaddle/Paddle#12429]
PaddlePaddle提供的 paddle.data_type.dense_array 支持维数可变的数据输入。在使用时，将对应数据层的维数设置成一个大于输入数据维数的值用于占位即可。
http://www.paddlepaddle.org/docs/0.14.0/documentation/zh/faq/model/index_cn.html
报错如下

Input layer pixel: Incorrect input image size 88 * 89 for input image pixels 7840
Traceback (most recent call last):
  File "train.py", line 94, in <module>
    testMNIST.start_trainer()
  File "train.py", line 53, in start_trainer
    trainer = self.get_trainer()
  File "train.py", line 17, in get_trainer
    out = convolutional_neural_network()
....
File "/usr/lib64/python2.7/site-packages/paddle/trainer/config_parser.py", line 4341, in my_fatal
    raise Exception()
Exception

"The data size must be equal to it in data layer.")
ValueError: The data size must be equal to it in data layer.

**Comment by qingqing01** [comment]
@freekoy 除了这样设置之外，reader里要求返回numpy array，如果是彩色图，即CHW的3D numpy array。

**Comment by freekoy** [comment]
已返回numpy array亦是不对

**Comment by lucywsq** [comment]
您好，建议您将返回numpy array后报错信息再行贴出，以便精准定位问题，谢谢~
此issue在近一个月内暂无更新，我们将于三天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题，我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持!
