### ISSUE TITLE
加载部分预训练模型参数

### ISSUE THREAD

**Issue by libaikai** [PaddlePaddle/Paddle#12428]
有时候会想用预训练模型，比如VGG，但是不需要全部的参数；
如何加载部分pre-trained parameters到自己的model里面，为了做迁移学习。
有没有比较好的示例或者好用的函数（像Pytorch里state_dict()这样的）

**Comment by oraoto** [comment]
`paddle.fluid.io.load_params`和`paddle.fluid.io.load_vars`都有`main_program`参数，即只加载`main_program`里的变量和参数。

例如这个[SE_ResNeXt50的例子](https://github.com/oraoto/learn_ml/blob/master/paddle/pretrained.ipynb)，构建了一个只有前几层的program，然后只加载这部分参数。

**Comment by libaikai** [comment]
大大的感谢：）

**Comment by lucywsq** [comment]
您好，此issue在近一个月内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题， 我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持!
