### ISSUE TITLE
Unkown setting: momentum

### ISSUE THREAD

**Issue by shateng** [PaddlePaddle/Paddle#1242]
按books里的setting设置learning_method=MomentumOptimizer(0.9)，报错：
[CRITICAL 2017-01-30 11:27:20,067 optimizers.py:388] Unkown setting: momentum

是什么原因呢？版本应该不低，是momentum没实现？

**Comment by helinwang** [comment]
请问你的paddle是什么版本的？
我按照[教程](https://github.com/PaddlePaddle/Paddle/blob/develop/doc/tutorials/image_classification/index_cn.md)试了一下，是可以用的。
我的paddle版本：
```
$ paddle version
PaddlePaddle 0.9.0a0, compiled with
    with_avx: ON
    with_gpu: OFF
    with_double: OFF
    with_python: ON
    with_rdma: OFF
    with_glog: ON
    with_gflags: ON
    with_metric_learning: 
    with_timer: OFF
    with_predict_sdk:
```
我们有打包好的paddle demo docker image，详见[这里](https://github.com/PaddlePaddle/Paddle/blob/develop/doc/getstarted/build_and_install/docker_install_cn.rst)。要是你懂得怎么用docker的话，可以试试。因为docker打包好的版本是肯定可以用的。
我运行的docker指令是
```
docker run -it paddledev/paddle:cpu-demo-latest
```
