### ISSUE TITLE
tensor_layer参数相关

### ISSUE THREAD

**Issue by Emma-Ding** [PaddlePaddle/Paddle#12435]
想问问这个里tesor_layer的i的维度是不是由size决定的?
![0dfa82472bf554423fe5dd474c189a8b](https://user-images.githubusercontent.com/22070158/43375390-5004965a-93e7-11e8-8c52-40c09e03d6d8.png)

**Comment by luotao1** [comment]
是的，这里K就是输出y的维度，即这个layer的size。
