### ISSUE TITLE
安装出错，Built target paddle_fluid_api

### ISSUE THREAD

**Issue by tangzhiyi11** [PaddlePaddle/Paddle#12436]
[ 55%] Built target paddle_inference_api_shared
[ 55%] Built target paddle_inference_api
make[2]: *** INTERNAL: readdir: Input/output error.  Stop.
CMakeFiles/Makefile2:4867: recipe for target 'paddle/fluid/framework/details/CMakeFiles/ssa_graph_checker.dir/all' failed
make[1]: *** [paddle/fluid/framework/details/CMakeFiles/ssa_graph_checker.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 55%] Building CXX object paddle/fluid/inference/CMakeFiles/paddle_fluid_api.dir/io.cc.o
[ 55%] Linking CXX static library libpaddle_fluid_api.a
[ 55%] Built target paddle_fluid_api
Makefile:149: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by luotao1** [comment]
请问 `git log`的commitid号是多少，是否为最新代码？#12416 修复过一次编译问题。

**Comment by tangzhiyi11** [comment]
85c4912755b783dd7554a9d6b9dae4a7e40371bc

**Comment by luotao1** [comment]
请更新到最新代码，再试一下

**Comment by lucywsq** [comment]
您好，此issue在近一个月内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题，我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持!
