### ISSUE TITLE
look_up_table_op在bp阶段对padding idx的处理问题

### ISSUE THREAD

**Issue by gavin1332** [PaddlePaddle/Paddle#12442]
https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/fluid/operators/lookup_table_op.h
look_up_table op 在bp阶段没有对padding idx的梯度做特殊处理？
forward运算里是有的padding idx的处理，但backward没有保持一致

**Comment by guoshengCS** [comment]
backward的时候不用做特殊处理应该就行，不管训练过程中backward如何处理paddding_idx的embedding，forward时都会输出0

**Comment by gavin1332** [comment]
3KS
