### ISSUE TITLE
Paddle训练GPU不支持CRF条件随机场

### ISSUE THREAD

**Issue by xiaolv3366** [PaddlePaddle/Paddle#12470]
Paddle使用GPU训练CRF条件随机场报错！这是为什么？这么重要的CRF层GPU训练都不支持，CPU训练实在太慢了！没法用GPU训练根本跑不动。
![image](https://user-images.githubusercontent.com/12287110/43451344-4ce62f82-94e7-11e8-8dee-3bd5dc92fb0b.png)

**Comment by typhoonzero** [comment]
Paddle 的CRF现在暂时还没有GPU版本的实现。

CPU训练速度慢，可以尝试修改`trainer_count=n`用多线程执行或者使用分布式训练提升速度。

**Comment by xiaolv3366** [comment]
CRF条件随机场都不支持GPU训练？这个应该要支持的。

**Comment by lucywsq** [comment]
您好，感谢您的建议，我们已经收到并记录此方面需求，若在未来有相关动态后您可再reopen此issue
感谢您对PaddlePaddle的支持和关注！
