### ISSUE TITLE
为什么模型文件中参数数量，和网络结构不一致呢？

### ISSUE THREAD

**Issue by HugoLian** [PaddlePaddle/Paddle#12474]
在我的网络结构中，有22个embedding层，但是解压gz模型文件后，发现只有21个embedding层的变量（0-20），这是为什么呢？
![image](https://user-images.githubusercontent.com/22980558/43458373-a2cf6476-94fc-11e8-98e9-748d5ab44233.png)

查看下对应的embedding_20, 模型文件大小是48，而对应我的第21层网络是：
4 ×２×４＋１６＝４８是可以对上的

![image](https://user-images.githubusercontent.com/22980558/43458454-ec1da0fc-94fc-11e8-9315-49af273131de.png)

然而第22个embedding得参数去哪儿了呢？

**Comment by typhoonzero** [comment]
可以直接给embedding layer设置一个名字( `name=xxx` )，然后再save下正常是都会save的，可能是顺序问题？

**Comment by HugoLian** [comment]
@typhoonzero 多谢大神~~ 最后还是我网络结构写错了，有两个FC接的是同一个input，这样embedding21实际上没有向后传递，大意了。。。。。

**Comment by typhoonzero** [comment]
明白了，感谢反馈~
