### ISSUE TITLE
Model average Optimizer 【使用】

### ISSUE THREAD

**Issue by CNevd** [PaddlePaddle/Paddle#12471]
看到龙飞在ppt里讲到 训练中通过窗口累计历史的parameter，预测时使用average后的parameter，整体提高预测的精度
想问一下这部分的实现逻辑是在哪个文件呢？

**Comment by jacquesqiao** [comment]
https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/fluid/optimizer.py#L1111  在这里

**Comment by CNevd** [comment]
好的谢谢，这个特性是训练过程中server每次回复worker端pull操作的都是average的parameter？
