### ISSUE TITLE
安装出错 Linking libpaddle_pybind.so 失败

### ISSUE THREAD

**Issue by leahic** [PaddlePaddle/Paddle#12483]
[ 39%] Building CXX object paddle/fluid/pybind/CMakeFiles/paddle_pybind.dir/recordio.cc.o
[ 40%] Linking CXX shared library libpaddle_pybind.so
collect2: fatal error: ld terminated with signal 9 [Killed]
compilation terminated.
paddle/fluid/inference/CMakeFiles/paddle_fluid_shared.dir/build.make:742: recipe for target 'paddle/fluid/inference/libpaddle_fluid.so' failed
make[2]: *** [paddle/fluid/inference/libpaddle_fluid.so] Error 1
make[2]: *** Deleting file 'paddle/fluid/inference/libpaddle_fluid.so'
CMakeFiles/Makefile2:26266: recipe for target 'paddle/fluid/inference/CMakeFiles/paddle_fluid_shared.dir/all' failed
make[1]: *** [paddle/fluid/inference/CMakeFiles/paddle_fluid_shared.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 40%] Built target paddle_pybind
Makefile:149: recipe for target 'all' failed
make: *** [all] Error 2

Mac版 docker 17.06.2-ce
CPU-Only版本的PaddlePaddle

git log >>
commit f372f27e3f724a55ed221f18d3c30b18b4cde8cf
Author: *****
Date:   Mon Jul 30 15:36:15 2018 +0800
    Hidden APIs for While, StaticRNN, ParallelDo. (#12332)
    * Hidden APIs for While, StaticRNN, ParallelDo.

**Comment by chengduoZH** [comment]
您改用最新的commti试一下可以吗

**Comment by lucywsq** [comment]
您好，此issue在近一个月内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题， 我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持!
