### ISSUE TITLE
random fail unittest

### ISSUE THREAD

**Issue by guochaorong** [PaddlePaddle/Paddle#12481]
1.  test_dist_se_resnext
2. test_parallel_executor_mnist

第一个单测在厂内的4个agent上， 有80%的概率会失败
失败原因：
![fail1](https://user-images.githubusercontent.com/32069604/43471048-a2fcc70c-951c-11e8-878c-a262a1348a8f.JPG)
请武毅老师帮忙调查更正

第二个单测，在所有agent上，有较小的概率失败
![fail2](https://user-images.githubusercontent.com/32069604/43471131-d136af98-951c-11e8-9bdf-513d60958885.JPG)
请chenduo老师评估是否真的需要disable该单测

**Comment by typhoonzero** [comment]
Related: https://github.com/PaddlePaddle/Paddle/issues/12487

Can only reproduce on some virtual machines, test with bare metal seems fine.

**Comment by panyx0718** [comment]
Raised the delta. But we should investigate why.
