### ISSUE TITLE
分布式的参数该怎么初始化？

### ISSUE THREAD

**Issue by gongweibao** [PaddlePaddle/Paddle#12488]
### 背景
之前的实现中，分布式的每一个节点都是自己初始化参数的。这种情况下
1. 训练的第一个batch trainer使用的是自己的参数，然后
2. pserver收到了非自己参数获得的梯度然后进行优化，相当于乱走了一步。
3. 第二个batch开始，trainer使用pserver的参数来继续训练

这样，第一个batch的训练是没有用处的。

### 方案
1. 各个pserver自己初始化参数，trainer去pserver获取参数
     问题：由于我们支持切分variable，每个pserver上可能只会存储一个参数的一部分，每个部分用不同的初始化种子初始化的。当然，参数够大的情况下，他们的数据分布应该是相同的。
2. trainer0初始化参数，broadcast到各个节点(pserver和trainer)
    问题：需要各个trainer拥有自己的端口，端口目前是核心资源。
3. trainer0初始化参数，发送到pserver，然后各个trainer节点从pserver更新参数。

### 个人倾向于第三种：
1. 可以和本地做到完全一致，非常易于对比精度和调试。
2. 避免1的可能的问题。

**Comment by gongweibao** [comment]
之前的讨论在：https://github.com/PaddlePaddle/Paddle/pull/12047

**Comment by velconia** [comment]
> 每个部分用不同的初始化种子初始化

这会带来什么问题么..., 如果我们固定了seed, 那么所有pserver还是一致的, 如果我们不固定, 那么各个pserver的seed本来就是0,一个var分散成两个部分, 在两个pserver上进行随机初始化应该也没啥问题;

**Comment by seiriosPlus** [comment]
1.trainer0初始化参数的前提是 trainer0上有全部的参数， 如果trainer0上不存在的参数该如何初始化
2.```trainer0初始化参数，broadcast到各个节点(pserver和trainer)```， 这个网络是不是搞复杂了.

**Comment by gongweibao** [comment]
感谢曹博：
![image](https://user-images.githubusercontent.com/10721757/43507708-731235de-95a0-11e8-8076-b2d4054c92a5.png)

**Comment by typhoonzero** [comment]
我自己觉得，分到不同pserver初始化，可能反而会更好：

1. 初始化是一个随机过程，初始化的结果满足需要的分布即可，否则在local trian中，多次不同从头训练，收敛结果会有区别。多个pserver初始化，用不同的自动生成的seed，初始化的结果同样满足使用的intializer的分布。
1. 由于随机数是伪随机，而不同的server由于硬件的微小差异（比如时钟频率的微小差异）有可能提高整体的随机性，猜测可能更好？

**Comment by gongweibao** [comment]
曹博帮忙的回复（感谢曹博）：
```
种子确实不一样，理论上高斯分布是有均值和方差决定的，
随机种子是技术上为了保证随机性引入的，并不是高斯分布本质的刻画因素。
对其他的分布来说，只要初始化都是”从一个分布采样N个数“这种模式，应该是一个道理。
```

**Comment by panyx0718** [comment]
从抽象上看，这些方法是对用户定义的program的不同部署方式，在program中插入合适的split/concat/send/recv，然后部署在多个机器上，并且通过一定的驱动方法启动执行这些program。

无论是1，还是3，都是可以通过不同的transform pass进行program->IR转换实现的。通过组装不同的pass，可以灵活的实现不同program执行方式。

这些转换不仅包含主要训练部分，还包含startup/save/load。以后有些模型会有不通的分布式的方法，需要考虑到将来的扩展性问题。
现在讨论的是pserver的，那基于ring的可能又会不一样
