### ISSUE TITLE
Links on the installation part of official website is not available 

### ISSUE THREAD

**Issue by JiabinYang** [PaddlePaddle/Paddle#12486]
Links shown in the pic on the official website is not available, plz help to fix it:
http://paddlepaddle.org/docs/0.14.0/documentation/fluid/zh/new_docs/beginners_guide/index.html
![2018-08-01 1 12 32](https://user-images.githubusercontent.com/22361972/43504877-83864f6c-9597-11e8-9ae5-9ca083b07546.png)

**Comment by luotao1** [comment]
http://paddlepaddle.org/documentation/docs/zh/0.14.0/new_docs/beginners_guide/install/install_doc.html#permalink-2-ubuntu-paddlepaddle 这个链接里面都可以下载，但下载的不是0.14.0，而是develop @JiabinYang @shanyi15
