### ISSUE TITLE
0.11.0 实现facenet，如何一次传入多个图片

### ISSUE THREAD

**Issue by WangTaoSpace** [PaddlePaddle/Paddle#12496]
我要实现facenet的网络结构，需要实现一个triplet_loss 函数，需要3张图片。我如何传入训练数据时，一次传入3张图片，传统方法一般是传入一张图片

**Comment by chengduoZH** [comment]
您可以设定batch为3的整数被，即要传入的三张图像为一组，在triplet_loss中一次处理为一组的图像。

**Comment by lucywsq** [comment]
您好，此issue在近一个月内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题，我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持!
