### ISSUE TITLE
如何使用大规模离散特征训练模型

### ISSUE THREAD

**Issue by Damcy** [PaddlePaddle/Paddle#12499]
在paddle的教程里面没有找到相关教程，现在想用uint64_t编码的作为特征id进行训练，应该使用哪些api

**Comment by chengduoZH** [comment]
您使用fluid还是V2？

**Comment by Damcy** [comment]
用的是fluid版本

**Comment by Damcy** [comment]
@chengduoZH 用的是fluid版本

**Comment by chengduoZH** [comment]
目前Fluid还不支持这样类型的特征，以后会对这个做支持的。
您可以试着将uint64_t转成int64_t试试。

**Comment by jacquesqiao** [comment]
目前暂时使用的是int64来表示大表的id，目前大表功能在大规模测试中，还有一些小问题，最近应该会有一个稳定的版本和教程放出来，尽请期待~

**Comment by Damcy** [comment]
@jacquesqiao @chengduoZH 使用int64有对应的教程吗？在手册中看到了distribute lookup table的介绍

**Comment by jacquesqiao** [comment]
已支持。请参考文档 
http://paddlepaddle.org/documentation/docs/zh/1.1/user_guides/howto/training/cluster_howto.html

http://paddlepaddle.org/documentation/docs/zh/1.1/user_guides/howto/training/cluster_howto.html#embedding 
和模型
https://github.com/PaddlePaddle/models/tree/develop/fluid/PaddleRec/ctr

**Comment by Damcy** [comment]
@jacquesqiao 好赞，马上试用一波

**Comment by lucywsq** [comment]
您好，如您的问题已经解决，我们将在今天内关闭。如您后续有其他问题，可重新开启此issue。感谢您对PaddlePaddle的支持！

**Comment by lovetimil** [comment]
大规模稀疏id只能embedding吗，有支持sparse LR处理方式吗？不过把emb当成LR的W也能曲线救国。
