### ISSUE TITLE
MNIST CNN training doesn't work on Cuda 8.0 + Cudnn 5.1

### ISSUE THREAD

**Issue by zchen0211** [PaddlePaddle/Paddle#1249]
My paddle demo training on mnist is good on cpu but doesn't converge on GPU. I used latest release of Ubuntu 16.04, cuda and cudnn. The codes are in the ./demo, with standard setup. The same codes run perfectly on the old version cuda 7.5 + cudnn 5.

After many iterations, the test error is still high. The error rate is still 30%+, which should be around 1% in previous releases.

**Comment by gangliao** [comment]
Which Paddle version you installed? Do you build the source code from the develop branch?

Here are some suggestions may help you figure out the problem:  https://github.com/PaddlePaddle/Paddle/issues/1207

**Comment by gangliao** [comment]
I will verify this demo using cuda 8.0 + cudnn 5.1

**Comment by zchen0211** [comment]
Hello, I'm using the latest version: paddle 0.9.0. I built it from source.
Yeah, should be, I strongly agree. The same code runs great on my cpu and others with cuda 7.5+ cudnn 5: performance strong and 2 pass error only 2%; the same code on my gpu cuda 8.0 + cudnn 5, many passes still 50% error. I'm pretty sure that something is wrong... 
Thanks :)

**Comment by zchen0211** [comment]
Hi, I rerun it and it is fixed. I think we can closed this :)
