### ISSUE TITLE
load_inference_model接口所需要的模型只能是save_inference_model保存的模型吗 ？

### ISSUE THREAD

**Issue by yeyupiaoling** [PaddlePaddle/Paddle#12495]
使用`load_inference_model`加载模型需要`__model__`文件，这个文件只有`save_inference_model`保存的时候才有，其他保存模型的好像没有，比如[图片分类的例子](https://github.com/PaddlePaddle/models/blob/1ae49ef4cbabff4f977fcc15f0981f359d1eb5a3/fluid/image_classification/train.py#L227)使用的是`save_persistables`保存的模型，我想使用它预测都不行，我指定的是以下的预测方式：
```python
[inference_program, feed_target_names, fetch_targets] = fluid.io.load_inference_model(model_path, exe)
```
这个方式预测很简单的

**Comment by chengduoZH** [comment]
> load_inference_model接口所需要的模型只能是save_inference_model保存的模型吗 ？

是的
图片分类的例子使用的是save_persistables保存的是参数。

**Comment by yeyupiaoling** [comment]
@chengduoZH 
使用`save_persistables`这样就像V2那样，在预测的时候还要网络的Python文件呢。

**Comment by chengduoZH** [comment]
是的

**Comment by yeyupiaoling** [comment]
@chengduoZH 
使用`save_persistables`保存的模型有没有可能转换成`save_inference_model`保存模型的样子？

**Comment by chengduoZH** [comment]
`save_persistables `中保存的是参数，没有网络结构，所以不能。

**Comment by yeyupiaoling** [comment]
@chengduoZH 好的，谢谢。
