### ISSUE TITLE
tensor_layser bias的维度 

### ISSUE THREAD

**Issue by Emma-Ding** [PaddlePaddle/Paddle#12494]
tensor_layer里面bias的维度是不是跟y一样，也就是做完了下图的矩阵乘法后再加的bias?
<img width="348" alt="2018-08-01 4 50 20" src="https://user-images.githubusercontent.com/22070158/43511474-116de0de-95ab-11e8-9a55-af3a380b9ee6.png">

http://paddlepaddle.org/docs/0.9.0/documentation/en/ui/api/trainer_config_helpers/layers.html#permalink-61-tensor_layer

**Comment by chengduoZH** [comment]
不一定，只要bias可以broadcast成y的shape就可以

**Comment by lucywsq** [comment]
您好，此issue在近一个月内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题， 我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持!
