### ISSUE TITLE
 Executer::run() interface in paddle/fluid/framework/executor.h changed

### ISSUE THREAD

**Issue by wangguibao** [PaddlePaddle/Paddle#12516]
The 3rd and 4th arguments had changed. Now it has the signature 
```
void Executor::Run(const ProgramDesc& program, Scope* scope,
                   std::map<std::string, const LoDTensor*>* feed_targets,
                   std::map<std::string, LoDTensor*>* fetch_targets,
                   bool create_vars, const std::string& feed_holder_name,
                   const std::string& fetch_holder_name);
```
Caller in Paddle/paddle/fluid/inference/tests/test_multi_thread_helper.h shall be updated accordingly (3rd and 4th parameter shall be pointers now, instead of references).

```
  // 6. Run the inference program
  executor->Run(*copy_program, scope, feed_targets, fetch_targets, true,
                feed_holder_name, fetch_holder_name);
```

**Comment by gongweibao** [comment]
What's wrong with it?

**Comment by Superjomn** [comment]
Reference http://www.paddlepaddle.org/docs/0.14.0/documentation/fluid/zh/new_docs/user_guides/howto/inference/native_infer.html

The `Load` APIs are the underlying APIs, and we will discard them later.

The high-level API is a more general, and officially backward compatible.

https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/fluid/inference/api/paddle_inference_api.h

**Comment by wangguibao** [comment]
For now I see paddle/fluid/inference/api/ on develop branch but not on 0.14.0 release.
Will try inference API once it is released in the future
