### ISSUE TITLE
paddle::inference::Load() interface has changed

### ISSUE THREAD

**Issue by wangguibao** [PaddlePaddle/Paddle#12517]
First parameter has changed to framework::Executor* executor. Now it has signature:
```
std::unique_ptr<framework::ProgramDesc> Load(framework::Executor* executor,
                                             framework::Scope* scope,
                                             const std::string& dirname);

std::unique_ptr<framework::ProgramDesc> Load(framework::Executor* executor,
                                             framework::Scope* scope,
                                             const std::string& prog_filename,
                                             const std::string& param_filename);
```
Callers in paddle/fluid/inference/tests/test_multi_thread_helper.h shall be updated accordingly.

```
  // 2. Initialize the inference_program and load parameters
  std::unique_ptr<paddle::framework::ProgramDesc> inference_program =
      paddle::inference::Load(executor, *scope, dirname);
```

**Comment by Superjomn** [comment]
Reference http://www.paddlepaddle.org/docs/0.14.0/documentation/fluid/zh/new_docs/user_guides/howto/inference/native_infer.html

The `Load` APIs are the underlying APIs, and we will discard them later.

The high-level API is a more general, and officially backward compatible.

https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/fluid/inference/api/paddle_inference_api.h

**Comment by wangguibao** [comment]
For now I see paddle/fluid/inference/api/ on develop branch but not on 0.14.0 release.
Will try inference API once it is released in the future
