### ISSUE TITLE
pserver2端口问题

### ISSUE THREAD

**Issue by LoveGarden** [PaddlePaddle/Paddle#12510]
Log file created at: 2018/08/02 16:09:21
Running on machine: yq01-ecom-nova0843.yq01.baidu.com
Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
I0802 16:09:21.459648  3819 Util.cpp:155] commandline: ./paddle_pserver2 --num_gradient_servers=2 --nics=xgbe0 --port=13211 --ports_num=1 --ports_num_for_sparse=1 --rdma_tcp=tcp --comment=paddle_cluster_job 
I0802 16:09:21.460024  3819 Util.cpp:130] Calling runInitFunctions
I0802 16:09:21.460352  3819 Util.cpp:143] Call runInitFunctions done.
I0802 16:09:21.460467  3819 ParameterServer2Main.cpp:66] pserver started : xgbe0:13211
I0802 16:09:21.460554  3819 ParameterServer2Main.cpp:66] pserver started : xgbe0:13212
I0802 16:09:21.460561  3820 LightNetwork.cpp:265] tcp server start 
I0802 16:09:21.460649  3821 LightNetwork.cpp:265] tcp server start 
F0802 16:09:21.460726  3821 LightNetwork.cpp:186] Check failed: bind(socket_, (struct sockaddr *)&serv_addr, sizeof(serv_addr)) >= 0 ERROR on binding 10.182.19.12: Address already in use [98]

pserver2更换端口为13211后，第一次mpi任务能跑，第二次时报端口占用，例行任务如何先择端口？

**Comment by gongweibao** [comment]
现在MPI应该还没有做到根据端口进行任务schedule。要不你直接问一下HPC管MPI的同学？

**Comment by lucywsq** [comment]
您好，此issue在近一个月内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题，我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持!
