### ISSUE TITLE
c-api make后git clone 下载不了

### ISSUE THREAD

**Issue by Kevinlsy** [PaddlePaddle/Paddle#12519]
Scanning dependencies of target extern_mklml
[  1%] Completed 'extern_mklml'
[  2%] Built target extern_mklml
Scanning dependencies of target extern_mkldnn
[  3%] Performing download step (git clone) for 'extern_mkldnn'
Cloning into 'extern_mkldnn'...
error: RPC failed; curl 56 GnuTLS recv error (-54): Error in the pull function.
fatal: The remote end hung up unexpectedly
fatal: early EOF
fatal: index-pack failed
Cloning into 'extern_mkldnn'...
error: RPC failed; curl 56 GnuTLS recv error (-54): Error in the pull function.
fatal: The remote end hung up unexpectedly
fatal: early EOF
fatal: index-pack failed
Cloning into 'extern_mkldnn'...
error: RPC failed; curl 56 GnuTLS recv error (-54): Error in the pull function.
fatal: The remote end hung up unexpectedly
fatal: early EOF
fatal: index-pack failed
-- Had to git clone more than once:
          3 times.
CMake Error at /mnt/tf/lsy/paddle_c_api/Paddle/third_party/mkldnn/tmp/extern_mkldnn-gitclone.cmake:40 (message):
  Failed to clone repository: 'https://github.com/01org/mkl-dnn.git'

**Comment by Kevinlsy** [comment]
服务器把github.com墙了，有直接安装的版本吗

**Comment by Kevinlsy** [comment]
http://www.paddlepaddle.org/docs/0.14.0/documentation/zh/howto/capi/compile_paddle_lib_cn.html   
   直接下载安装包为空了，make编译后git clone下载不了相关包

**Comment by luotao1** [comment]
> 直接下载安装包为空了

会尽快修复

> make编译后git clone下载不了相关包

从错误看，是网络链接出错，请确保机器有外网权限，即可下载相关包。

**Comment by jtyoui** [comment]
> > 直接下载安装包为空了
> 
> 会尽快修复
> 
> > make编译后git clone下载不了相关包
> 
> 从错误看，是网络链接出错，请确保机器有外网权限，即可下载相关包。

修复了吗？我也遇到了相同的情况，现在是2020年了

**Comment by ZhangYuef** [comment]
2022年12月 打卡
