### ISSUE TITLE
在图像分类中出现梯度爆炸改如何解决呢？

### ISSUE THREAD

**Issue by yeyupiaoling** [PaddlePaddle/Paddle#12529]
@guochaorong 
我一开始是使用这个优化方法的，但收敛的不是很好。
```python
        optimizer = paddle.optimizer.Momentum(
            momentum=0.9,
            regularization=paddle.optimizer.L2Regularization(rate=0.0005 * batch_size),
            learning_rate=0.00001 / batch_size,
            learning_rate_decay_a=0.1,
            learning_rate_decay_b=128000 * 35,
            learning_rate_schedule="discexp", )
```

然后我就使用这个优化方法，吴恩达老师说Adam要比Momentum要好，但是使用这个会出现梯度爆炸
```python
        optimizer = paddle.optimizer.Adam(
            learning_rate=1e-3,
            learning_rate_schedule="manual",
            learning_rate_args="1000:1.0,2000:0.9,3000:0.8")
```

![image](https://user-images.githubusercontent.com/26297768/43631732-a14fa282-9736-11e8-8015-b7637c2a7021.png)

**Comment by kuke** [comment]
Adam出现不收敛的问题应该是初始学习率太大(`1e^-3`)的原因，可以将这里的学习率也设置成`0.00001 / batch_size`。

**Comment by yeyupiaoling** [comment]
@kuke  好的，我先试试。

**Comment by yeyupiaoling** [comment]
@kuke 减小了学习率，就没办法收敛了，如下：
![default](https://user-images.githubusercontent.com/26297768/43954568-8c8c1d6e-9ccf-11e8-8012-4afdf566bead.png)

**Comment by yeyupiaoling** [comment]
模型本身有问题，要修改模型
