### ISSUE TITLE
paddle 正在进入下个阶段

### ISSUE THREAD

**Issue by nashannashui** [PaddlePaddle/Paddle#12524]
我看你们现在连周会都不开了

**Comment by xiaolv3366** [comment]
江山代有才人出，各领风骚数百年。大神走了，百度又会出现新的大神！
Paddle深度学习框架，目前发展的不错，一定要坚持发展下去，这是百度令人值得敬畏的产品。

**Comment by yeyupiaoling** [comment]
@nashannashui 
paddlepaddle现在已基本稳定了，接下来的工作就是推广。另外百度的大神多得很呢。

**Comment by nashannashui** [comment]
@xiaolv3366  别扯了 我也是从百度出来的 当时连内部没开源我就用过paddle了 像徐伟这种工程和学术皆世界顶级的人 百度历史上没有 未来估计也不会有 就算有这种人 估计也不会再来百度了

**Comment by nashannashui** [comment]
@yeyupiaoling  paddle本身技术已经演化了三代了 可想而知 未来肯定还会继续演化 你说的稳定只是相对当前这段时间 如果没有大牛掌舵 后面可能会跟不上节奏 最终被淘汰 另外 别把那种只会发论文灌水 连像样的c++程序都写不出来的人叫大神 那是对这个行业的侮辱

**Comment by lucywsq** [comment]
我也是PaddlePaddle的用户，合作还比价深入，感觉最近框架越来越稳定了，文档也越来越完善了，官网最近更新频率也很高，一个框架越来越好用，肯定不会凉了的。而且和PaddlePaddle合作时，也了解到他们有专门的团队开发框架，不是一个人单独开发的框架。再厉害的英雄也不可能一个人搞定一件事，任何的成功都必定是团队的。不支持由“个人英雄主义”引发的唱衰，还是比较看好未来的走势的。

**Comment by nashannashui** [comment]
@lucywsq 真跟唱衰没关系 有可能就直接衰了 估计你都不是it领域的 跟不用说ai领域 有的东西说了估计你也不明白 技术和工程难度的大项目 需要大牛时刻把握方向 其他人都只是在他的指点和带领下干活 没了这个人 或者换了技术很烂的人来掌舵 直接就会带歪了 甚至下面的人全跑了 

百度的徐伟就类似google 的jeff dean，如果你明白我在说什么的话，google很多nb的大项目都是jeff dean掌舵，当然徐伟跟他还是比不了

**Comment by coding-forever** [comment]
我也在用paddle，最近体验下来感觉挺好用的，正准备用paddle实验一下新的想法~与其关注这种所谓的人事变动，不如多关心框架是不是更好用来的实在吧~
