### ISSUE TITLE
V2的多个data layer在infer时的问题

### ISSUE THREAD

**Issue by shiyazhou121** [PaddlePaddle/Paddle#12525]
我有两个输入分别是dense和sparse类型的，模型训练好了，不知道怎么infer。求问python版的infer和capi版的infer 应该怎么构造。以下是我的网络结构。
![image](https://user-images.githubusercontent.com/15082798/43619695-b6f6ddba-9701-11e8-9dfd-1a44f761c713.png)
python版的infer
![image](https://user-images.githubusercontent.com/15082798/43619708-c639f168-9701-11e8-9d0f-9b49eb0f936e.png)
报错
![image](https://user-images.githubusercontent.com/15082798/43619723-d742d7f4-9701-11e8-81c1-18582b36714b.png)

**Comment by gongweibao** [comment]
这里有一个多线程的例子你看看？
https://github.com/PaddlePaddle/Paddle/tree/develop/paddle/legacy/capi/examples/model_inference/multi_thread

**Comment by lucywsq** [comment]
您好，V2版本后续将不作维护，建议您后续将代码迁移至Fluid~
此issue在近一个月内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题，
我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持!
