### ISSUE TITLE
请问fluid版本中，sparse vector应该如何输入？

### ISSUE THREAD

**Issue by HugoLian** [PaddlePaddle/Paddle#12532]
在v2版本中，
sparse_binary_vector : [ 2,  3,  23,  124] 这样的输入是：
input = paddle.layer.data(name='input_data', type=paddle.data_type.sparse_binary_vector(162))
sparse_float_vector : [ (2, 0.12), (321, 0.06)] 这样的输入是：
input = paddle.layer.data(name='input_data', type=paddle.data_type.sparse_float_vector(562))

请问这两种输入用paddle.fluid.layers.data（）分别应该怎么设置shape和type呢？

**Comment by reyoung** [comment]
Fluid目前不支持Sparse输入。

**Comment by HugoLian** [comment]
那如果用户兴趣、文章关键词这样的 一次输入有多个ID（词典大小几万到几十万），中间没有顺序关机的tensor，再fluid中大家一般怎么处理呢？ @reyoung

**Comment by nicky2015** [comment]
是否意味着fluid暂不支持将训练好的词向量（gensim.models.Word2Vec.load()）作输入？

**Comment by Yancey0623** [comment]
> 是否意味着fluid暂不支持将训练好的词向量（gensim.models.Word2Vec.load()）作输入？

支持的， 参考：https://github.com/PaddlePaddle/models/blob/develop/fluid/PaddleNLP/deep_attention_matching_net/model.py#L87

``` python
    def set_word_embedding(self, word_emb, place):
        word_emb_param = fluid.global_scope().find_var(
            self.word_emb_name).get_tensor()
        word_emb_param.set(word_emb, place)

```

并且在模型中指定 embedding table 的名字:

``` python
response_emb = fluid.layers.embedding(
            input=self.response,
            size=[self._vocab_size + 1, self._emb_size],
            is_sparse=self.use_sparse_embedding,
            param_attr=fluid.ParamAttr(
                name=self.word_emb_name,
                initializer=fluid.initializer.Normal(scale=0.1)))

```

> 那如果用户兴趣、文章关键词这样的 一次输入有多个ID（词典大小几万到几十万），中间没有顺序关机的tensor，再fluid中大家一般怎么处理呢？

我理解这种需要支持 sparse 的 input data type 才行，Fluid 中暂时不支持，但也请 @reyoung 帮确认一下？

**Comment by Yancey0623** [comment]
由于长此issue长时间未更新，我先关掉了，如有问题可以随时打开：）
