### ISSUE TITLE
Paddle多机分布式训练出错

### ISSUE THREAD

**Issue by coding-forever** [PaddlePaddle/Paddle#12537]
大家好！

       这两天在尝试使用PaddlePaddle平台。之前按照操作说明单机训练可以有结果，但是进行多机训练时出错。

       按照 http://www.paddlepaddle.org/docs/0.14.0/documentation/fluid/zh/new_docs/user_guides/howto/training/cluster_quick_start.html 这个文档进行的操作。

      报错信息如下：

root@3374a3140ee5:/app/ap/recognize_digits# PADDLE_TRAINING_ROLE=TRAINER PADDLE_PSERVER_IPS=ps0.paddlepaddle.com,ps1.paddlepaddle.com PADDLE_TRAINERS=2 PADDLE_TRAINER_ID=1 PADDLE_PSERVER_PORT=6174 python fluid_dist.py
F0720 09:45:08.417428   591 grpc_client.cc:276] Send name:[fc_0.b_0@GRAD.trainer_1], ep:[ps1.paddlepaddle.com:6174] meets grpc error:Deadline Exceeded
*** Check failure stack trace: ***
    @     0x7f69cdad679d  google::LogMessage::Fail()
    @     0x7f69cdada24c  google::LogMessage::SendToLog()
    @     0x7f69cdad62c3  google::LogMessage::Flush()
    @     0x7f69cdadb75e  google::LogMessageFatal::~LogMessageFatal()
    @     0x7f69ce2e16ef  paddle::operators::distributed::GRPCClient::Proceed()
    @     0x7f69d8856c80  (unknown)
    @     0x7f6a198526ba  start_thread
    @     0x7f6a1958841d  clone
    @              (nil)  (unknown)
Aborted (core dumped)

     我是在docker里面进行操作的。  启用了4个docker实例，模拟4个主机。

     /etc/hosts 里面配置如下：

172.17.0.9 ps0.paddlepaddle.com
172.17.0.10 ps1.paddlepaddle.com
172.17.0.11 trainer0.paddlepaddle.com
172.17.0.12 trainer1.paddlepaddle.com

      4个docker实例可以互相访问，端口都打开着。

      大家在多机训练时是怎么做的。有人遇到过类似的问题吗？希望得到高手指点，在此先谢过了！

**Comment by lucywsq** [comment]
下载最新版本PaddlePaddle进行编译，能够解决问题。再补充一个参考内容https://github.com/PaddlePaddle/Paddle/issues/11851

**Comment by jacquesqiao** [comment]
看日志是rpc超时了，可以打开日志看看
```
export GLOG_v=4
export GLOG_logtostderr=1
```
