### ISSUE TITLE
怎么使我的训练错误率收敛

### ISSUE THREAD

**Issue by lianqingsong** [PaddlePaddle/Paddle#12547]
我有一套手写数字的数据集，我按照官网上的识别数字来训练我自己的数据集。但它就是不收敛，尝试了减小学习率和对图片进行灰度处理缩小等，还是那样不收敛。错误率特别高。而且最终训练出来的模型，测试，不管什么图片，用这个模型测试出来的都显示1.。。。这是什么情况，请问我应该怎么去改

**Comment by yeyupiaoling** [comment]
@Qsongl 你的数据量是多少呢？学习率你设置了多少呢？

**Comment by lianqingsong** [comment]
@yeyupiaoling  数据量大概有8000千多张图
学习率learning_rate=0.0001 / 128.0。。往大往小都调试了，没有用。cost一直在2点多

**Comment by yeyupiaoling** [comment]
@Qsongl  训练了多少个pass，错误率是多少呢？cost不一定很小的。还有你预测的，图片的预处理和和训练的是的预处理是否一样？

**Comment by lianqingsong** [comment]
@yeyupiaoling 100pass.错误率在70到90。是一样的。而且训练出来的模型，预测图片都是一样的结果

**Comment by yeyupiaoling** [comment]
@Qsongl 关于自定义数据集的话，可以看看这个教程https://blog.csdn.net/qq_33200967/article/details/79095265

**Comment by lianqingsong** [comment]
@yeyupiaoling 哪里的教程

**Comment by yeyupiaoling** [comment]
@Qsongl 更新了

**Comment by lianqingsong** [comment]
@yueyupiaoling 好的，我去看看 Thanks♪(･ω･)ﾉ

**Comment by lianqingsong** [comment]
@yeyupiaoling  好的，我去看看 Thanks♪(･ω･)ﾉ

**Comment by lianqingsong** [comment]
@yeyupiaoling 不行，用这个还是一样 不收敛 还要怎么调

**Comment by lianqingsong** [comment]
@yeyupiaoling 不行，用这个还是一样 不收敛 还要怎么调

**Comment by yeyupiaoling** [comment]
@Qsongl 那要考虑你的数据集问题了，方便把你的程序给我看看不？

**Comment by lianqingsong** [comment]
@yeyupiaoling 可以 这个上面怎么给你看

**Comment by yeyupiaoling** [comment]
打包压缩成zip，在这里上传
![image](https://user-images.githubusercontent.com/26297768/43758344-65dbdc32-9a4e-11e8-820e-e3ea568d489e.png)

**Comment by lianqingsong** [comment]
[shuzi.zip](https://github.com/PaddlePaddle/Paddle/files/2265294/shuzi.zip)
@yeyupiaoling 您看看

**Comment by yeyupiaoling** [comment]
好

**Comment by lianqingsong** [comment]
@yeyupiaoling 麻烦了

**Comment by yeyupiaoling** [comment]
@Qsongl 我测试了一下，不行呢，调了各种参数也不行，建议换一个数据集试试。

**Comment by lianqingsong** [comment]
@yeyupiaoling 
哇  我们老师说清华的可以做到准确率98以上
-.-

**Comment by yeyupiaoling** [comment]
@Qsongl 那你继续琢磨琢磨，

**Comment by lianqingsong** [comment]
@yeyupiaoling 23333，好

**Comment by yeyupiaoling** [comment]
@Qsongl 有其他问题再交流。

**Comment by lianqingsong** [comment]
好的 @yeyupiaoling

**Comment by lianqingsong** [comment]
@yeyupiaoling 您那有没有封装的手写体数据集吗，想换个试试

**Comment by yeyupiaoling** [comment]
@Qsongl 没有呢

**Comment by lianqingsong** [comment]
@yeyupiaoling 好的吧
