### ISSUE TITLE
paddle正则化，设置l1的时候，报错

### ISSUE THREAD

**Issue by mufasalab** [PaddlePaddle/Paddle#1255]
paddle 支持不同正则化，情形是这样的，左侧网络为离散dnn输入，设置为spare_binary_vector，想通过l1来进行正则化，报如下错误，烦请看下。

<img width="1011" alt="2017-02-04 10 58 14" src="https://cloud.githubusercontent.com/assets/22140712/22615469/42631420-ead0-11e6-95d1-caa1ebb7ac9d.png">

配置如下：

![2017-02-04 11 53 03](https://cloud.githubusercontent.com/assets/22140712/22615501/84b76baa-ead0-11e6-98a6-14fda1b7e759.png)

**Comment by gangliao** [comment]
@mufasalab 最新的develop分支已经fix调这个问题了，可以尝试更新。

**Comment by reyoung** [comment]
这个问题我们在最新的版本里面已经修复了。。会在下一次release的时候，去掉这个限制。

之前限制是参数的宽度必须是4或者8的倍数(具体值我忘了，可以尝试一下)。。

也就是最后的fc_layer的size必须是4或者8。。。虽然这么做可能会稍微影响训练效果，不过估计影响不大。
