### ISSUE TITLE
v2 版本 refine已有模型，怎么控制各层的学习率和是否学习？

### ISSUE THREAD

**Issue by yttbgf** [PaddlePaddle/Paddle#12551]
如题，能否直接访问到定义好的模型结构，加载预训练参数后，再用层名（get_layer(name)）并设置
learning_rate参数。不然要重新将网络结构构造的代码改造成按层的学习率，预训练和refine时给不同参数。

fc_para_attr = paddle.attr.Param(learning_rate=1e-3)
fc1 = paddle.layer.fc(
            input=inputs,
            size=hid_dim,
            act=linear,
            param_attr=fc_para_attr,
            )

**Comment by wanghaoshuang** [comment]
paddle v2 应该是不支持你说的动态设置学习率的，必须重新将网络结构构造的代码改造成按层的学习率。

**Comment by lucywsq** [comment]
您好，此issue在近一个月内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题， 我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持!
