### ISSUE TITLE
Failed to download wmt14 dataset

### ISSUE THREAD

**Issue by kexinzhao** [PaddlePaddle/Paddle#12559]
When trying the machine translation book example, it failed to download the following link:
```
RuntimeError: Cannot download http://paddlepaddle.cdn.bcebos.com/demo/wmt_shrinked_data/wmt14.tgz within retry limit 3
```

It seems that the download request is denied because the account is bill overdue:
```
{"code":"AccountOverdue","message":"Your request is denied because there is an overdue bill of your account.","requestId":"088e42d0-c79e-4626-bfaa-8f866ec8a97c"}
```

**Comment by luotao1** [comment]
We move it to http://paddlemodels.bj.bcebos.com/wmt/wmt14.tgz instead. I will fix the URL ASAP.

**Comment by mcyhx** [comment]
Hi,luotao1,It seems the example is still using the link of  http://paddlepaddle.cdn.bcebos.com/demo/wmt_shrinked_data/wmt14.tgz and it does not work.

**Comment by luotao1** [comment]
@mcyhx Which example do you use? Could you give the code URL?
