### ISSUE TITLE
通过reveiver提交训练任务，任务run了一个小时，没有从hdfs下载训练数据，workspace下也没有train_data_dir路径

### ISSUE THREAD

**Issue by wangyingfan** [PaddlePaddle/Paddle#12566]
通过reveiver提交训练任务，任务run了一个小时，没有从hdfs下载训练数据，workspace下也没有train_data_dir路径，log中只有assigned_ip.log，没有train.log，是什么问题？

**Comment by JiayiFeng** [comment]
关于内网receiver的问题不太适合在github上解答，容易暴露内网地址，要是方便的话请在用户群里提问并附上链接。这个先关了。
