### ISSUE TITLE
tensor_layer的bias加在哪儿的

### ISSUE THREAD

**Issue by Emma-Ding** [PaddlePaddle/Paddle#12564]
采用tensor_layer训练的时候，有bias参数文件，试了试，并不是加在公式最后的，想问问这个bias是加在下面的公式的哪儿的
![2018-08-07 2 53 25](https://user-images.githubusercontent.com/22070158/43759399-b16e413c-9a51-11e8-9001-41f447d968c6.png)

**Comment by JiayiFeng** [comment]
从代码上看，应该是加在最后的。是做了什么样的实验发现不是加在最后的呢？

**Comment by Emma-Ding** [comment]
size的维度跟bias的维度不一定是一样的，所以很奇怪这个要加在哪儿

**Comment by JiayiFeng** [comment]
这两个维度本身就不需要一致，其中一方会自动做broadcast。

**Comment by Emma-Ding** [comment]
请问broadcast具体是什么意思呀?有文档或者源码可以参考吗?

**Comment by JiayiFeng** [comment]
broadcast就是说，shape小的那一方会自动复制自身让两边shape一样，比如，a = [1,2,3,4], b = [2], 那么b就会broadcast自己变成[2,2,2,2]。更高维度下也同理。

**Comment by Emma-Ding** [comment]
好的，谢谢，也就是说bias的维度应该是大于等于y的，可以这样理解吗？

**Comment by JiayiFeng** [comment]
不一定，也可以y比较大bias比较小，这样bias会被broadcast

**Comment by lucywsq** [comment]
您好，此issue在近一个月内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题， 我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持!
