### ISSUE TITLE
有没有TensorFlow转Fluid版本的模型工具

### ISSUE THREAD

**Issue by yeyupiaoling** [PaddlePaddle/Paddle#12576]
我在tensorflow看到了比较完善的训练好的模型：https://github.com/tensorflow/models/tree/master/research/slim#pre-trained-models
我想把他们转换成fluid版本的预测库，是类似这个接口保存得到的模型：http://www.paddlepaddle.org/docs/0.14.0/api/fluid/en/io.html#save-inference-model
```
save_inference_model
```
因为PaddleMobile需要这个格式的模型

有这个工具吗？

**Comment by zhangyang0701** [comment]
我们也有这个刚性需求，有办法解决吗？

**Comment by lucywsq** [comment]
您好，您的建议已经被记录，当前此方面暂未进入代发计划，后续若进入开发可重启此issue
感谢您对PaddlePaddle的支持！

**Comment by yeyupiaoling** [comment]
@lucywsq 好的。

**Comment by ckarying** [comment]
请问，现在有相关的工具或者api么？tensorflow to fluid
