### ISSUE TITLE
删除demo目录下和book中重复的例子

### ISSUE THREAD

**Issue by luotao1** [PaddlePaddle/Paddle#1257]
demo目录下和book中重复的例子是否可以删除了？ @wangkuiyi  @Zrachel 
目前demo目录如下，其中6个带*的demo，和book中完全重复。
```
├── gan
├── image_classification *
├── introduction
├── mnist *
├── model_zoo
├── quick_start
├── recommendation *
├── semantic_role_labeling *
├── sentiment *
├── seqToseq *
├── sequence_tagging
└── traffic_prediction
```

**Comment by reyoung** [comment]
@wangkuiyi @luotao1 @Zrachel 

1、我感觉Paddle的用户不一定知道Book这个项目。我们能不能使用submodule来引用Book项目，这样也比较方便用户来查找这个项目？

```bash
git submodule add https://github.com/PaddlePaddle/Book demo
```

2、目前Paddle文档中还有demo的介绍，我们是不是应该先将那个介绍指向Book之后，再去删除demo中的代码？

**Comment by luotao1** [comment]
1. 同意使用submodule的方式。
2. Paddle文档中的demo介绍在doc/tutorials目录下面（如下），除了gan外，其他都有中英文。目前book只有中文，是等统一翻译完后再将介绍链接指向Book，然后删除demo中的代码么？
```
├── embedding_model
├── gan
├── image_classification
├── imagenet_model
├── quick_start
├── rec
├── semantic_role_labeling
├── sentiment_analysis
└── text_generation
```

**Comment by Zrachel** [comment]
我也同意submodule方式，但是现在如果想替换paddle repo里的document主要还两个问题：

1） tutorial里的文档没有英文翻译，替换过去导致paddle主页里demo的中英文不对应；
2） paddle repo里还有两个demo代码没有配tutorial，不知道放哪；

益哥的建议呢？
