### ISSUE TITLE
tensor_layer实现相关问题

### ISSUE THREAD

**Issue by Emma-Ding** [PaddlePaddle/Paddle#12571]
实现的代码跟公式好像有点出入，不知道能不能帮忙看一下，同时帮忙找到一下tmpMat->mul的源码，谢谢
![c3b08cf4fe126cbbba38e5e3a47b25c3](https://user-images.githubusercontent.com/22070158/43774538-ff515d42-9a7b-11e8-9388-d7f023840ab6.png)
![2018-08-07 2 53 25](https://user-images.githubusercontent.com/22070158/43774539-01db68e6-9a7c-11e8-9c76-cd59916e1a41.png)
https://github.com/PaddlePaddle/Paddle/blob/71b1c397d7d7cf7cc02c274fb2d69aaf7f794933/paddle/legacy/gserver/layers/TensorLayer.cpp

**Comment by JiayiFeng** [comment]
mul的实现在这个文件中：https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/legacy/math/Matrix.cpp

根据Matrix类型的不同（CPU，GPU，稠密，稀疏等），有很多个版本的`mul`。

**Comment by Emma-Ding** [comment]
谢谢，看了看源码跟我的实现是一样的，但是最后算下来结果上还是有差别，那想再问问代码里面的outV->rowDotMul这个函数的源码在哪儿可以看到呢? 谢谢

**Comment by JiayiFeng** [comment]
这里：
https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/legacy/math/BaseMatrix.cu#L1398

**Comment by Emma-Ding** [comment]
想再问问，这个weight的存储结构是拉长了放在一个vector里吗，那在做矩阵运算的时候这个是行主序还是列主序的啊，谢谢

**Comment by JiayiFeng** [comment]
Fluid是行主续的，老的V1/V2我也不太清楚。存储结构肯定不会用std::vector，一般都是一个指针加一个长度的原始数组形式。

**Comment by lucywsq** [comment]
您好，此issue在近一个月内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题， 我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持!
