### ISSUE TITLE
使用cpu训练model下面的image_classification时报错

### ISSUE THREAD

**Issue by kolinwei** [PaddlePaddle/Paddle#12589]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/work/weike/svn/baidu/paddle/test/cts_test/test_image_classification_train_cpu.py", line 101, in test_train_single_cpu
    self.train_exe = fluid.ParallelExecutor(use_cuda=self.use_gpu, loss_name=self.avg_cost.name)
  File "/usr/local/lib/python2.7/dist-packages/paddle/fluid/parallel_executor.py", line 160, in __init__
    build_strategy, num_trainers, trainer_id)
EnforceNotMet: optimize operations cannot be depended by forward or backward node momentum -> conditional_block at [/paddle/paddle/fluid/framework/details/multi_devices_graph_builder.cc:221]
PaddlePaddle Call Stacks:
0       0x7ff1079b8fa6p paddle::platform::EnforceNotMet::EnforceNotMet(std::__exception_ptr::exception_ptr, char const*, int) + 486
1       0x7ff10873a425p paddle::framework::details::SortOpsAndDelayOptimizeOp(paddle::framework::ir::Graph const&) + 2053
2       0x7ff1087407e0p paddle::framework::details::MultiDevSSAGraphBuilder::ApplyImpl(std::unique_ptr<paddle::framework::ir::Graph, std::default_delete<paddle::framework::ir::Graph> >) const + 80

**Comment by jacquesqiao** [comment]
模型怎么配置的？

**Comment by lucywsq** [comment]
您好，此issue在近一个月内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题， 我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持!
