### ISSUE TITLE
paddlepaddle.bj.bcebos.com 域名已欠费，数据需要放到百度云paddlepaddle账户

### ISSUE THREAD

**Issue by guochaorong** [PaddlePaddle/Paddle#12580]
paddlepaddle.bj.bcebos.com 域名已经欠费，

```sh
curl http://paddlepaddle.bj.bcebos.com/demo/srl_dict_and_embedding/wordDict.txt
{"code":"AccountOverdue","message":"Your request is denied because there is an overdue bill of your account.","requestId":"ea92441c-c52a-447c-9527-f62745500009"}
```

后续这个链接下的数据都统一存放到百度云paddlepaddle账户。

登录paddlepaddle账户， 将原来在paddlepaddle.bj.bcebos.com 域名下的数据集，上传到bucket：
选择文件最后边， 更多操作， 设置属性为公共权限

如

![22](https://user-images.githubusercontent.com/32069604/43814400-c3f23cae-9afc-11e8-8f7b-38b9e4b421e6.png)

目前已经将paddle 单测中用到的conll05st 和 wmt数据集放到了百度云paddlepaddle账户下
点击获取链接
http://paddlemodels.bj.bcebos.com/conll05st%2FwordDict.txt
http://paddlemodels.bj.bcebos.com/wmt%2Fwmt14.tgz

**Comment by velconia** [comment]
> http://paddlemodels.bj.bcebos.com/conll05st%2FwordDict.txt
http://paddlemodels.bj.bcebos.com/wmt%2Fwmt14.tgz

这两个是指: 
```
http://paddlemodels.bj.bcebos.com/conll05st/wordDict.txt
http://paddlemodels.bj.bcebos.com/wmt/wmt14.tgz
```

这两个吗?

**Comment by xingyuezhiyun** [comment]
文档麻烦更新下!!!
