### ISSUE TITLE
paddle v2和fluid版本的模型预测capi是否无区别?

### ISSUE THREAD

**Issue by flyhighzy** [PaddlePaddle/Paddle#12581]
如题，是否预测capi底层的依赖库也是相同的呢？谢谢

**Comment by luotao1** [comment]
v2和fluid两个版本的预测库区别比较大，详细请看文档：
- v2预测库：http://www.paddlepaddle.org/docs/0.14.0/documentation/zh/howto/capi/index_cn.html
- fluid预测库：http://www.paddlepaddle.org/docs/0.14.0/documentation/fluid/zh/new_docs/user_guides/howto/inference/index.html

> 是否预测capi底层的依赖库也是相同的呢

不太一样。具体可以根据上面文档，下载paddle.tgz（v2版本）和fluid.tgz，查看所依赖的第三方库。

**Comment by flyhighzy** [comment]
多谢回答，貌似这两个文档链接都404了，麻烦更新一下~
