### ISSUE TITLE
sigmoid_cross_entropy_with_logits 跑不起来

### ISSUE THREAD

**Issue by Angus07** [PaddlePaddle/Paddle#12585]
prob = fluid.layers.fc(
        input=prediction, size=class_dim,act='sigmoid')
    cost = fluid.layers.cross_entropy(input=prob, label=label, soft_label= True)
    cost = fluid.layers.mean(x=cost) 
和 
cost = fluid.layers.sigmoid_cross_entropy_with_logits(input=prob, label=label)
是否等价呢？
同样的输入都是ND的矩阵，上面就跑通，下面就报错。
BOOK中找不到sigmoid_cross_entropy_with_logits的使用例子。

**Comment by Angus07** [comment]
``` bash
Traceback (most recent call last):
  File "l1_train_5.py", line 138, in <module>
    main(args)
  File "l1_train_5.py", line 129, in main
    model_save_dir=args.model_save_dir)
  File "l1_train_5.py", line 62, in train
    cost, prob, pred = topology(data1,data2,data3, label, dict_dim,class_num)
  File "/home/ssd5/du/niuguocheng/topic_l1/code_v14_cly/network_conf_short5.py", line 78, in convolution_net
    cost = fluid.layers.sigmoid_cross_entropy_with_logits(input=prob, label=label, soft_label= True)
  File "/home/du/chenliangyu/python27-gcc482/lib/python2.7/site-packages/paddle/fluid/layers/layer_function_generator.py", line 174, in func
    dtype = infer_and_check_dtype(op_proto, *args, **kwargs)
  File "/home/du/chenliangyu/python27-gcc482/lib/python2.7/site-packages/paddle/fluid/layers/layer_function_generator.py", line 154, in infer_and_check_dtype
    val = [args[0]]
IndexError: tuple index out of range
```

这是用sigmoid_cross_entropy_with_logits 的报错信息。其中Label的格式是[0,1,0,0,1.....,0,1]这样的NXD的矩阵。N为Batch_size。

**Comment by luotao1** [comment]
sigmoid_cross_entropy_with_logits说明：
http://www.paddlepaddle.org/documentation/api/zh/0.14.0/layers.html#permalink-120-sigmoid_cross_entropy_with_logits 要求是二维的。

> 其中Label的格式是[0,1,0,0,1.....,0,1] 

这是一维的。可以参考下我们的单侧
https://github.com/PaddlePaddle/Paddle/blob/95ea54fd7938b59483e81a57b69262e7efa410cd/python/paddle/fluid/tests/unittests/test_sigmoid_cross_entropy_with_logits_op.py#L22-L36

https://github.com/PaddlePaddle/Paddle/blob/29fac3c0923b964dd357b7e2d1afaa2eec4a9666/python/paddle/fluid/tests/unittests/test_dyn_rnn.py#L124-L125

**Comment by Angus07** [comment]
我这个也是二维的啊，[0,1,0,0,1.....,0,1]是一个Instance，加上Batch就是二维了啊。
打印结构是这样

name: "label"
type {
  type: LOD_TENSOR
  lod_tensor {
    tensor {
      data_type: FP32
      dims: -1
      dims: 27
    }
    lod_level: 0
  }
}
persistable: false

**Comment by Angus07** [comment]
fluid.layers.cross_entropy(input=prob, label=label, soft_label= True) 这个函数中，soft_label=true也要求是二维的label，我用这个就可以跑通的。

**Comment by luotao1** [comment]
从参数接口看，只有两个参数
`cost = fluid.layers.sigmoid_cross_entropy_with_logits(input=prob, label=label)`

**Comment by Angus07** [comment]
我就写了两个参数啊？我什么时候写了三个参数？

**Comment by luotao1** [comment]
从上面的报错信息看，你是写了三个参数的。请仔细检查。
```
File "/home/ssd5/du/niuguocheng/topic_l1/code_v14_cly/network_conf_short5.py", line 78, in convolution_net
cost = fluid.layers.sigmoid_cross_entropy_with_logits(input=prob, label=label, soft_label= True)
```

**Comment by Angus07** [comment]
``` bash
Traceback (most recent call last):
  File "l1_train_5.py", line 138, in <module>
    main(args)
  File "l1_train_5.py", line 129, in main
    model_save_dir=args.model_save_dir)
  File "l1_train_5.py", line 62, in train
    cost, prob, pred = topology(data1,data2,data3, label, dict_dim,class_num)
  File "/home/ssd5/du/niuguocheng/topic_l1/code_v14_cly/network_conf_short5.py", line 81, in convolution_net
    cost = fluid.layers.sigmoid_cross_entropy_with_logits(input=prob, label=label)
  File "/home/du/chenliangyu/python27-gcc482/lib/python2.7/site-packages/paddle/fluid/layers/layer_function_generator.py", line 174, in func
    dtype = infer_and_check_dtype(op_proto, *args, **kwargs)
  File "/home/du/chenliangyu/python27-gcc482/lib/python2.7/site-packages/paddle/fluid/layers/layer_function_generator.py", line 154, in infer_and_check_dtype
    val = [args[0]]
IndexError: tuple index out of range
```

**Comment by Angus07** [comment]
不是这个问题啊，我5天前就试过好多遍了，两个也是这个错。这个是刚才我为了贴错误临时改了一下，写错了。

**Comment by luotao1** [comment]
请问是使用最新版本的paddle么？请给出一个完整可复现的配置和脚本。

**Comment by luotao1** [comment]
> File "/home/du/chenliangyu/python27-gcc482/lib/python2.7/site-packages/paddle/fluid/layers/layer_function_generator.py", line 154, in infer_and_check_dtype
val = [args[0]]
IndexError: tuple index out of range

可以在154行这里，把args打印出来看看。

**Comment by Angus07** [comment]
![image](https://user-images.githubusercontent.com/4252318/44024558-33b0a914-9f20-11e8-936c-0d08b59c95da.png)
![image](https://user-images.githubusercontent.com/4252318/44024565-38fc6b06-9f20-11e8-8ed8-6fb7170471bf.png)
几个相关变量及打印结果

**Comment by Angus07** [comment]
![image](https://user-images.githubusercontent.com/4252318/44024672-88ef7afe-9f20-11e8-8b91-7b47cce21144.png)
![image](https://user-images.githubusercontent.com/4252318/44024687-94b91674-9f20-11e8-928e-bf3ddb336dd9.png)
相关打印结果

**Comment by Angus07** [comment]
![image](https://user-images.githubusercontent.com/4252318/44024734-c31825f0-9f20-11e8-92c9-2111178d428d.png)

**Comment by Yancey0623** [comment]
把参数`input`改成`x`呢？
``` python
cost = fluid.layers.sigmoid_cross_entropy_with_logits(x=prob, label=label)
```

**Comment by Angus07** [comment]
把参数input改成x可以了。

**Comment by lucywsq** [comment]
您好，此issue在近一个月内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题， 我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持!
