### ISSUE TITLE
capi,cpu预测模型是没问题的，设置成gpu=True之后报错。

### ISSUE THREAD

**Issue by Kevinlsy** [PaddlePaddle/Paddle#12594]
I0808 21:26:19.011968 10332 Util.cpp:166] commandline:  --use_gpu=True 
I0808 21:26:37.443864 10332 GradientMachine.cpp:83] Loading parameters from ./model/ssd_model
*** Aborted at 1533734798 (unix time) try "date -d @1533734798" if you are using GNU date ***
PC: @                0x0 (unknown)
*** SIGSEGV (@0x108426ec000) received by PID 10332 (TID 0x7f529dabc840) from PID 1114554368; stack trace: ***
    @     0x7f5298d064b0 (unknown)
    @           0x40e433 getImageData()
    @           0x40e7a0 prepare()
    @           0x40e7dd main
    @     0x7f5298cf1830 __libc_start_main
    @           0x40a1a9 _start
    @                0x0 (unknown)
Segmentation fault (core dumped)

我想问问是不是我用opencv处理后的图片存储在cpu上，不能将数据直接赋值给paddle的gpu中。

**Comment by jacquesqiao** [comment]
需要拷贝到GPU显存中
