### ISSUE TITLE
旧版paddle里的initial_smart  在新版的trainer_config 里怎么写对应的配置 ？

### ISSUE THREAD

**Issue by buptzzl** [PaddlePaddle/Paddle#1260]
旧版paddle里的initial_smart  在新版的trainer_config 里怎么写对应的配置 ？

**Comment by reyoung** [comment]
ParamAttr的默认值就是initial_smart的。

即 attr = ParameterAttribute()即可。

**Comment by buptzzl** [comment]
@reyang 谢谢解答。
