### ISSUE TITLE
fail了，看不出为什么fail

### ISSUE THREAD

**Issue by zhengyandan** [PaddlePaddle/Paddle#12601]
![image](https://user-images.githubusercontent.com/42170878/43876895-a1256b38-9bc9-11e8-9895-1d8134978d6d.png)
![Uploading image.png…]()

**Comment by dzhwinter** [comment]
你好，可以贴一下栈顶吗？报错信息没截全。

**Comment by zhengyandan** [comment]
这个应该不是函数层的问题，我把没用的那个函数去掉了，还是报错
![image](https://user-images.githubusercontent.com/42170878/43958742-0e542b84-9cdf-11e8-93b8-b2b82b5c93f3.png)

**Comment by lucywsq** [comment]
C中为new/delete函数，C++语言的标准内存分配函数：malloc，calloc，realloc，free等，malloc和calloc的区别是1块与n块的区别，realloc调用形式为(类型*)realloc(*ptr，size)：将ptr内存大小增大到size，可以重新修改一下。
您好，此issue在近一个月内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题，我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持!
