### ISSUE TITLE
prune把最后inplace的op剪掉了

### ISSUE THREAD

**Issue by oraoto** [PaddlePaddle/Paddle#12609]
```python
import paddle.fluid as fluid
import paddle
from paddle.fluid.debugger import draw_block_graphviz

x = fluid.layers.data(name='x', shape=[1], dtype='float32', lod_level=1)
y = fluid.layers.fc(x, size=2, bias_attr=False, act='relu')
y = fluid.layers.fc(y, size=3, bias_attr=False, act='relu')

draw_block_graphviz(fluid.default_main_program().block(0), path="m.pdf")

pruned = fluid.default_main_program().prune(y)

draw_block_graphviz(pruned.block(0), path="g.pdf")

```

剪枝前：

![before](https://user-images.githubusercontent.com/24709398/43885241-e1b4220e-9bea-11e8-9edd-de36c75c988f.PNG)

剪枝后，最后一个relu没了：

![after](https://user-images.githubusercontent.com/24709398/43885251-e7ecae20-9bea-11e8-8f9c-c16ca97225e6.png)

**Comment by dzhwinter** [comment]
Thanks for the reporting. Seems it's a bug.

**Comment by dzhwinter** [comment]
@Superjomn @luotao1 对于同名的var，prune看起来会出问题

**Comment by lucywsq** [comment]
感谢您的建议，此issue已经被记录~鉴于此issue在近一个月内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题，我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持!
