### ISSUE TITLE
Ubuntu18.04 下CUDA9.2，Cudnn7安装gpu版本paddle报错

### ISSUE THREAD

**Issue by JiabinYang** [PaddlePaddle/Paddle#12610]
环境：
ubuntu 18.40
nvidia-docker启动
cmake 3.4.3
gcc 4.8.5 
CUDA 9.2
Cudnn 7(使用CUDA官方docker镜像）

编译正常，安装后出现以下报错，pip install paddlepaddle-gpu也会出现同样的报错：

*** Aborted at 1533782423 (unix time) try "date -d @1533782423" if you are using GNU date ***
PC: @                0x0 (unknown)
*** SIGSEGV (@0x50) received by PID 58 (TID 0x7f6d32a06740) from PID 80; stack trace: ***
    @     0x7f6d32439f20 (unknown)
    @     0x7f6d327f8ac8 (unknown)
    @     0x7f6d328010bd (unknown)
    @     0x7f6d325622df _dl_catch_exception
    @     0x7f6d328007ca (unknown)
    @     0x7f6d325613ad (unknown)
    @     0x7f6d325622df _dl_catch_exception
    @     0x7f6d3256236f _dl_catch_error
    @     0x7f6d325614d9 __libc_dlopen_mode
    @     0x7f6d3252c075 (unknown)
    @     0x7f6d321eb827 __pthread_once_slow
    @     0x7f6d3252c14f backtrace
    @     0x7f6c8d214436 paddle::platform::EnforceNotMet::EnforceNotMet()
    @     0x7f6c8dfed666 paddle::platform::GetCUDADeviceCount()
    @     0x7f6c8d2b93b6 paddle::framework::InitDevices()
    @     0x7f6c8d1f7dfa _ZZN8pybind1112cpp_function10initializeIZN6paddle6pybindL13pybind11_initEvEUlbE62_vIbEINS_4nameENS_5scopeENS_7siblingEEEEvOT_PFT0_DpT1_EDpRKT2_ENUlRNS_6detail13function_callEE1_4_FUNESL_
    @     0x7f6c8d229b1a pybind11::cpp_function::dispatcher()
    @     0x55990598201a (unknown)
    @     0x55990597f8ca (unknown)
    @     0x5599059877d3 (unknown)
    @     0x55990597f8ca (unknown)
    @     0x55990597f1e9 (unknown)
    @     0x55990597f125 (unknown)
    @     0x559905978493 (unknown)
    @     0x559905979889 (unknown)
    @     0x55990596a623 (unknown)
    @     0x55990596a014 (unknown)
    @     0x55990596b5a8 (unknown)
    @     0x55990596b33e (unknown)
    @     0x55990598b360 (unknown)
    @     0x55990598414c (unknown)
    @     0x55990597f8ca (unknown)
Segmentation fault

**Comment by yeyupiaoling** [comment]
@JiabinYang  请按照这个版本安装：
![image](https://user-images.githubusercontent.com/26297768/44134293-ce6816c8-a096-11e8-9f23-b71426002376.png)

**Comment by JiabinYang** [comment]
我是自己编译之后的包安装出现的问题，同样的问题也出现在CentOS7 CUDA8 cuDNN7下

**Comment by JiabinYang** [comment]
由于显卡驱动和CUDA版本不匹配

**Comment by procr** [comment]
请问显卡驱动和CUDA版本应该要怎么匹配？
