### ISSUE TITLE
pip install paddlepaddle安装失败

### ISSUE THREAD

**Issue by duanxian** [PaddlePaddle/Paddle#12621]
报错：
 Could not find a version that satisfies the requirement opencv-python (from paddlepaddle) (from versions: )
No matching distribution found for opencv-python (from paddlepaddle)
操作系统为：
CentOS release 4.3 (Final)
Kernel \r on an \m

**Comment by dzhwinter** [comment]
厂内jumbo pip缺少opencv-python，这个pip源处于无人维护状态。只能按wiki流程绕一下
