### ISSUE TITLE
paddle v2 MPI集群运行异常

### ISSUE THREAD

**Issue by guozhizou** [PaddlePaddle/Paddle#12623]
paddle(v0.14)本地提交集群任务，MPI上可以成功跑几分钟后，报错：
```
./paddle_pserver2: error while loading shared libraries: ./python27-gcc482/lib/libmkldnn.so.0: ELF file OS ABI invalid
```
一周多前任务是完全正常的，请问这个如何解决？

**Comment by HugoLian** [comment]
这两个issue是一个问题，里面提到的所有方法都试过，和楼主一样不能解决问题，最后留言是重新编译paddle版本，但是这个对于小白用户来说感觉成本太高了。。。 用本地机器的padder_trainer和paddler_pserver_main替换后，就是那个so.0文件版本不对应， 这个问题感觉会大面积遇到，希望有一个统一的解决方案 https://github.com/PaddlePaddle/Paddle/issues/11905

**Comment by Superjomn** [comment]
感觉这是集群环境发生变化了， 或者增加了不支持 mkldnn 的旧机型。
