### ISSUE TITLE
Fluid 模型参数解析 header 内容？

### ISSUE THREAD

**Issue by mzchtx** [PaddlePaddle/Paddle#12627]
[使用指南](http://www.paddlepaddle.org/docs/0.14.0/documentation/zh/faq/parameter/index_cn.html?highlight=learning#permalink-6-6-) 说参数的格式为前 16 个字节为 header，之后的数据为实际的参数数据，而实际上 header 的信息是变长的。

例如：一个 fc layer，weight 的 shape 为 512 * 1024，bias 的 shape 为 512，保存后:
+ weight 文件 size 为 512 * 1024 * 4 + 28 = 2097152 + 28 = 2097180
+ bias 文件 size 为 512 * 4 + 25 = 2073

查看源码[SerializeToStream](https://github.com/PaddlePaddle/Paddle/blob/b06309381babc8dca0ada2b6931ced417dd3f901/paddle/fluid/framework/lod_tensor.cc#L249)后发现保存时是包含 Lod 信息的，请确认文档中是否有问题？

**Comment by mzchtx** [comment]
看了下代码，参数的实际结构为：
1.  LoDTensor verison
    + uint32_t version
2. LoD information
    + uint64_t lod_level
    + lod data
    ```
        for (each : lod)
            uint64_t each.size
            each.data
    ```
3. tensor information
    + uint32_t version
    + proto::VarType::TensorDesc desc
          + int32_t size
          + buf
    + tensor data
   
参考：
[SerializeToStream](https://github.com/PaddlePaddle/Paddle/blob/release/0.14.0/paddle/fluid/framework/lod_tensor.cc#L243-L268)
[TensorToStream](https://github.com/PaddlePaddle/Paddle/blob/release/0.14.0/paddle/fluid/framework/tensor_util.cc#L228-L295)
[TensorDesc](https://github.com/PaddlePaddle/Paddle/blob/0d4b376fc0862e404dc47e0d3eaaa68001ef3f59/paddle/fluid/framework/framework.proto#L131-L135)

**Comment by luotao1** [comment]
您看的使用指南链接是V2版本的。V2和fluid的存储格式是不一样的。 @shanyi15 能否在官网更加显示说明下呢？

**Comment by shanyi15** [comment]
您看的应该是v2的文档
![default](https://user-images.githubusercontent.com/35982308/44016599-28ce412c-9f08-11e8-92ad-29c6f207d862.png)
查看Fluid的文档，请确定文档版本那里选择的是fluid，例如0.14.0
![default](https://user-images.githubusercontent.com/35982308/44016631-3e1439ec-9f08-11e8-827b-159530d49755.png)

**Comment by shanyi15** [comment]
Fluid FAQ请参考 http://www.paddlepaddle.org/documentation/docs/zh/0.14.0/new_docs/faq/index_cn.html

**Comment by mzchtx** [comment]
回溯了一下，发现之前 0.12.0 的文档在链接中也会带上 0.14.0 的字样，anyway，现在应该是没问题了，希望能完善下 Fluid FAQ。

**Comment by shanyi15** [comment]
好的，我们会逐步完善，也非常欢迎您为我们贡献FAQ文档~

**Comment by lucywsq** [comment]
您好，此issue在近一个月内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题， 我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持!
