### ISSUE TITLE
MPI集群跑机器翻译模型demo，中途报错Forwarding __bidirectional_gru_0___fw

### ISSUE THREAD

**Issue by Bodhi-Tree** [PaddlePaddle/Paddle#12654]
Sat Aug 11 15:35:27 2018[1,1]<stdout>:
Sat Aug 11 15:35:27 2018[1,1]<stdout>:Pass 0, Batch 368, Cost 50.880733, {'classification_error_evaluator': 0.7685352563858032}
Sat Aug 11 15:35:27 2018[1,2]<stdout>:
Sat Aug 11 15:35:27 2018[1,2]<stdout>:Pass 0, Batch 368, Cost 53.013538, {'classification_error_evaluator': 0.7777777910232544}
Sat Aug 11 15:35:42 2018[1,19]<stderr>:Thread [139910583289600] Forwarding __bidirectional_gru_0___fw, 
Sat Aug 11 15:35:42 2018[1,19]<stderr>:*** Aborted at 1533972942 (unix time) try "date -d @1533972942" if you are using GNU date ***
Sat Aug 11 15:35:42 2018[1,13]<stderr>:Thread [140696326326016] Forwarding __bidirectional_gru_0___fw, 
Sat Aug 11 15:35:42 2018[1,13]<stderr>:*** Aborted at 1533972942 (unix time) try "date -d @1533972942" if you are using GNU date ***
Sat Aug 11 15:35:42 2018[1,19]<stderr>:PC: @                0x0 (unknown)
Sat Aug 11 15:35:42 2018[1,13]<stderr>:
Sat Aug 11 15:35:42 2018[1,13]<stderr>:PC: @                0x0 (unknown)
Sat Aug 11 15:35:42 2018[1,20]<stderr>:Thread [140598679189248] Forwarding __bidirectional_gru_0___fw, 
Sat Aug 11 15:35:42 2018[1,20]<stderr>:*** Aborted at 1533972942 (unix time) try "date -d @1533972942" if you are using GNU date ***
Sat Aug 11 15:35:42 2018[1,24]<stderr>:Thread [139964018677504] Forwarding __bidirectional_gru_0___fw, 
Sat Aug 11 15:35:42 2018[1,24]<stderr>:*** Aborted at 1533972942 (unix time) try "date -d @1533972942" if you are using GNU date ***
Sat Aug 11 15:35:42 2018[1,11]<stderr>:Thread [140135036057344] Forwarding __bidirectional_gru_0___fw, 
Sat Aug 11 15:35:42 2018[1,11]<stderr>:*** Aborted at 1533972942 (unix time) try "date -d @1533972942" if you are using GNU date ***
Sat Aug 11 15:35:42 2018[1,10]<stderr>:Thread [139842902214400] Forwarding __bidirectional_gru_0___fw, 
Sat Aug 11 15:35:42 2018[1,10]<stderr>:*** Aborted at 1533972942 (unix time) try "date -d @1533972942" if you are using GNU date ***
Sat Aug 11 15:35:42 2018[1,20]<stderr>:
Sat Aug 11 15:35:42 2018[1,20]<stderr>:PC: @                0x0 (unknown)
Sat Aug 11 15:35:42 2018[1,24]<stderr>:
Sat Aug 11 15:35:42 2018[1,24]<stderr>:PC: @                0x0 (unknown)
Sat Aug 11 15:35:42 2018[1,11]<stderr>:
Sat Aug 11 15:35:42 2018[1,11]<stderr>:PC: @                0x0 (unknown)
Sat Aug 11 15:35:42 2018[1,10]<stderr>:
Sat Aug 11 15:35:42 2018[1,10]<stderr>:PC: @                0x0 (unknown)
Sat Aug 11 15:35:42 2018[1,18]<stderr>:Thread [139962781460224] Forwarding __bidirectional_gru_0___fw, 
Sat Aug 11 15:35:42 2018[1,18]<stderr>:*** Aborted at 1533972942 (unix time) try "date -d @1533972942" if you are using GNU date ***
Sat Aug 11 15:35:42 2018[1,24]<stderr>:
Sat Aug 11 15:35:42 2018[1,24]<stderr>:*** SIGFPE (@0x7f4d8904b460) received by PID 5470 (TID 0x7f4be99d5700) from PID 18446744071713371232; stack trace: ***
Sat Aug 11 15:35:42 2018[1,20]<stderr>:
Sat Aug 11 15:35:42 2018[1,20]<stderr>:*** SIGFPE (@0x7fdfff589460) received by PID 20103 (TID 0x7fdfae543700) from PID 18446744073698579552; stack trace: ***
Sat Aug 11 15:35:42 2018[1,24]<stderr>:
Sat Aug 11 15:35:42 2018[1,24]<stderr>:    @     0x7f4d8eb9f160 (unknown)
Sat Aug 11 15:35:42 2018[1,20]<stderr>:
Sat Aug 11 15:35:42 2018[1,20]<stderr>:    @     0x7fe0050dd160 (unknown)
Sat Aug 11 15:35:42 2018[1,13]<stderr>:
Sat Aug 11 15:35:42 2018[1,13]<stderr>:*** SIGFPE (@0x7ff6b4518460) received by PID 48799 (TID 0x7ff66a8d4700) from PID 18446744072439825504; stack trace: ***
Sat Aug 11 15:35:42 2018[1,11]<stderr>:
Sat Aug 11 15:35:42 2018[1,11]<stderr>:*** SIGFPE (@0x7f73f16fc460) received by PID 27779 (TID 0x7f73bb0b7700) from PID 18446744073465218144; stack trace: ***
Sat Aug 11 15:35:42 2018[1,13]<stderr>:
Sat Aug 11 15:35:42 2018[1,13]<stderr>:    @     0x7ff6ba06c160 (unknown)
Sat Aug 11 15:35:42 2018[1,3]<stderr>:Thread [140542075557632] Forwarding __bidirectional_gru_0___fw, 
Sat Aug 11 15:35:42 2018[1,3]<stderr>:*** Aborted at 1533972942 (unix time) try "date -d @1533972942" if you are using GNU date ***
Sat Aug 11 15:35:42 2018[1,19]<stderr>:*** SIGFPE (@0x7f3fb9a26460) received by PID 51743 (TID 0x7f3f789e0700) from PID 18446744072529011808; stack trace: ***
Sat Aug 11 15:35:42 2018[1,3]<stderr>:PC: @                0x0 (unknown)
Sat Aug 11 15:35:42 2018[1,19]<stderr>:    @     0x7f3fbf57a160 (unknown)
Sat Aug 11 15:35:42 2018[1,21]<stderr>:Thread [140391670904576] Forwarding __bidirectional_gru_0___fw, 
Sat Aug 11 15:35:42 2018[1,21]<stderr>:*** Aborted at 1533972942 (unix time) try "date -d @1533972942" if you are using GNU date ***
Sat Aug 11 15:35:42 2018[1,17]<stderr>:Thread [140468229388032] Forwarding __bidirectional_gru_0___fw, 
Sat Aug 11 15:35:42 2018[1,17]<stderr>:*** Aborted at 1533972942 (unix time) try "date -d @1533972942" if you are using GNU date ***
Sat Aug 11 15:35:42 2018[1,11]<stderr>:
Sat Aug 11 15:35:42 2018[1,11]<stderr>:    @     0x7f73f7250160 (unknown)
Sat Aug 11 15:35:42 2018[1,10]<stderr>:
Sat Aug 11 15:35:42 2018[1,10]<stderr>:*** SIGFPE (@0x7f3156ea8460) received by PID 35278 (TID 0x7f2fb682c700) from PID 1458209888; stack trace: ***
Sat Aug 11 15:35:42 2018[1,10]<stderr>:
Sat Aug 11 15:35:42 2018[1,10]<stderr>:    @     0x7f315c9fc160 (unknown)
Sat Aug 11 15:35:42 2018[1,18]<stderr>:
Sat Aug 11 15:35:42 2018[1,18]<stderr>:PC: @                0x0 (unknown)
Sat Aug 11 15:35:42 2018[1,20]<stderr>:
Sat Aug 11 15:35:42 2018[1,20]<stderr>:    @     0x7fdfff589460 (unknown)
Sat Aug 11 15:35:42 2018[1,20]<stderr>:
Sat Aug 11 15:35:42 2018[1,20]<stderr>:    @     0x7fdfff2fc20b hl_cpu_gru_forward<>()
Sat Aug 11 15:35:42 2018[1,12]<stderr>:Thread [140489601419008] Forwarding __bidirectional_gru_0___fw, 
Sat Aug 11 15:35:42 2018[1,12]<stderr>:*** Aborted at 1533972942 (unix time) try "date -d @1533972942" if you are using GNU date ***
Sat Aug 11 15:35:42 2018[1,20]<stderr>:
Sat Aug 11 15:35:42 2018[1,20]<stderr>:    @     0x7fdfff2fbce7 paddle::GruCompute::forward<>()
Sat Aug 11 15:35:42 2018[1,21]<stderr>:
Sat Aug 11 15:35:42 2018[1,21]<stderr>:PC: @                0x0 (unknown)
Sat Aug 11 15:35:42 2018[1,24]<stderr>:
Sat Aug 11 15:35:42 2018[1,24]<stderr>:    @     0x7f4d8904b460 (unknown)
Sat Aug 11 15:35:42 2018[1,19]<stderr>:
Sat Aug 11 15:35:42 2018[1,19]<stderr>:    @     0x7f3fb9a26460 (unknown)
Sat Aug 11 15:35:42 2018[1,12]<stderr>:
Sat Aug 11 15:35:42 2018[1,12]<stderr>:PC: @                0x0 (unknown)
Sat Aug 11 15:35:42 2018[1,20]<stderr>:
Sat Aug 11 15:35:42 2018[1,20]<stderr>:    @     0x7fdfff2ff9ae paddle::GatedRecurrentLayer::forwardBatch()
Sat Aug 11 15:35:42 2018[1,24]<stderr>:
Sat Aug 11 15:35:42 2018[1,24]<stderr>:    @     0x7f4d88dbe20b hl_cpu_gru_forward<>()
Sat Aug 11 15:35:42 2018[1,19]<stderr>:
Sat Aug 11 15:35:42 2018[1,19]<stderr>:    @     0x7f3fb979920b hl_cpu_gru_forward<>()
......

如题，我用集群跑paddle给的机器翻译的demo，刚开始跑得好好的，后来不知怎的就报上面这个错，不知是什么原因，还请老师帮忙看一下

**Comment by luotao1** [comment]
从报错信息中看到了`SIGFPE `，属于浮点数异常。请参考 http://www.paddlepaddle.org/documentation/docs/zh/0.12.0/faq/local/index_cn.html#permalink-10-4-floating-point-exception-

**Comment by lucywsq** [comment]
您好，此issue在近一个月内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题， 我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持!
