### ISSUE TITLE
paddle.fluid.core.EnforceNotMet: enforce allocating <= available failed, 14802874401 > 12088311552

### ISSUE THREAD

**Issue by chenbblei** [PaddlePaddle/Paddle#12652]
请问该如何解决，10几G的显卡怎么不够呢，应该怎么修改可以解决这个问题，我这边每个卡只有10几G的显卡可用

**Comment by chenbblei** [comment]
10几G的显卡怎么会不够呢。。。。

**Comment by luotao1** [comment]
请参考：https://github.com/PaddlePaddle/models/issues/1084 ，使用`export FLAGS_fraction_of_gpu_memory_to_use=0.1`(用户自定义)

**Comment by chenbblei** [comment]
@luotao1 多谢

**Comment by chenbblei** [comment]
@luotao1 但训练过程中又出现The default exception handler is LOG(FATAL).enforce allocating <= available failed, 1609008087 > 814022400

**Comment by JiayiFeng** [comment]
1. 确保卡上没有其他任务在运行
2. 减小batch size

**Comment by chenbblei** [comment]
@JiayiFeng 但卡上肯定不可能只跑一个任务啊

**Comment by luotao1** [comment]
可以分出一个专门的卡来单独跑paddle程序么？

**Comment by chenbblei** [comment]
@luotao1 好吧

**Comment by lianqingsong** [comment]
@chenbblei  请问你解决这个问题了吗，我也出现这个问题了
