### ISSUE TITLE
'module' object has no attribute 'get_places'

### ISSUE THREAD

**Issue by chenbblei** [PaddlePaddle/Paddle#12651]
fluid/DeepASR/model_utils/model.py, line 91, in stacked_lstmp_model
    places = fluid.layers.get_places()
AttributeError: 'module' object has no attribute 'get_places'

请问怎么解决

**Comment by luotao1** [comment]
请问你使用的是什么版本的paddle？
因为 https://github.com/PaddlePaddle/Paddle/commit/6c83dcd622000756d470202ff957907861920f26 (7月10日) 对get_places做了隐藏，所以如果使用最新版本的paddle，需要做如下修改：
```
## 增加import语句
from paddle.fluid.layers.device import get_places
## 91行需要改成
places = get_places()
```
您可以先自行修改，我们会尽快修复。

**Comment by chenbblei** [comment]
@luotao1 多谢
