### ISSUE TITLE
AttributeError: 'paddle.fluid.core.LoDTensor' object has no attribute 'get_dims'

### ISSUE THREAD

**Issue by chenbblei** [PaddlePaddle/Paddle#12653]
dims = lod_tensor.get_dims()
AttributeError: 'paddle.fluid.core.LoDTensor' object has no attribute 'get_dims'

求教解决

**Comment by luotao1** [comment]
https://github.com/PaddlePaddle/Paddle/commit/b83ffda4aa8aaa085e7447b21d09528480ae5b21 （7月11日）将`get_dims`改成`_get_dims`，您可以先自行改一下。

我们会尽快将develop分支下相关示例接口都更新。

**Comment by chenbblei** [comment]
@luotao1好吧。。
