### ISSUE TITLE
paddle.v2中cos_sim layer forward出错 Thread [139713573971712] Forwarding __cos_sim_0__

### ISSUE THREAD

**Issue by wangyingfan** [PaddlePaddle/Paddle#12678]
报错如下：
![_20180814104944](https://user-images.githubusercontent.com/42171054/44069074-c8d16f62-9faf-11e8-8397-6910d5399213.png)

![image](https://user-images.githubusercontent.com/42171054/44069096-dadfd9a0-9faf-11e8-87b5-175b5f0895ff.png)

相应代码如下：

![_20180814105625](https://user-images.githubusercontent.com/42171054/44069317-b762ac90-9fb0-11e8-847f-c3681a15f01a.png)

hidden_dim = 256

求问CosSimOp.cpp这个文件在哪里可以看到？

**Comment by Yancey0623** [comment]
源码在： https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/legacy/function/CosSimOp.cpp

看起来就是dim的问题，可以用下面方法把layers打出来看下：

```python
from paddle.v2.layer import parse_network
print(parse_network(output_left))
```

**Comment by lucywsq** [comment]
您好，此issue在近一个月内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题， 我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持!
