### ISSUE TITLE
请问训练开始前的rand seed怎么理解？

### ISSUE THREAD

**Issue by HugoLian** [PaddlePaddle/Paddle#1267]
thread use undeterministic rand seed:12296 这个seed有什么用？不是所有样本都会被用于训练过程么？
batch_size * batch数，也等于训练样本数

![image](https://cloud.githubusercontent.com/assets/22980558/22637992/55aba2f2-ec80-11e6-93fb-539a424dd71d.png)

**Comment by hedaoyuan** [comment]
`thread use undeterministic rand seed:12296` 里面的seed是用于随机初始化paddle里面用的一些数据（比如如果训练用到dropout，一开始的drop out mask是随机初始化的）。
`不过所有样本都会被用于训练过程么？` 是的（实际上不是很理解这个问题）。

**Comment by HugoLian** [comment]
@hedaoyuan PADDLE默认会做dropout处理么？我并没有任何相关dropout的设置啊？

**Comment by hedaoyuan** [comment]
上边只是一个会打印出这个rand seed的举例。paddle默认是不会调用dropout的，需要每个layer显示的配置drop_rate；不过paddle的有些demo里面是配置了drop_rate的。

**Comment by HugoLian** [comment]
@hedaoyuan 哦，我发现在用到rank_cost和lambda_cost的时候，出现过这个rand seed，分类的时候貌似没见过，所以应该是rank lambda层里面本身的一些设置吧？

**Comment by hedaoyuan** [comment]
看了一下，rank cost和lambda cost[代码](https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/gserver/layers/CostLayer.cpp#L198)本身并没有用到rand的地方，估计还是配置上有差别吧。
`分类的时候貌似没见过` 你的意思是仅仅将分类的cost换成这两个cost就会有这个rand出现？

**Comment by HugoLian** [comment]
@hedaoyuan 我最早些的是分类的cost，每注意有这个，最近用的lambda_cost，是肯定出现这个了。配置好像没有什么特别的东西。。基础的也就这些东西：
![image](https://cloud.githubusercontent.com/assets/22980558/22639228/e93efad0-ec87-11e6-8205-d55e9054f14c.png)
然后fc_layer的时候配置了个l2_rate

**Comment by hedaoyuan** [comment]
看一下dataprovider里面的`should_shuffle`是否配置了true，这个也会调用[rand](https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/gserver/dataproviders/PyDataProvider2.cpp#L556)。

**Comment by HugoLian** [comment]
@hedaoyuan 也没有配置这个参数。。

**Comment by hedaoyuan** [comment]
呃，这个log信息中缺少了产生rand seed的上下文，也不是很好猜是什么地方引起的。如果有gdb环境的话，你可以试一下，断点到[getSeed](https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/utils/ThreadLocal.cpp#L40)这里，看一下调用栈。

**Comment by jacquesqiao** [comment]
too old to debug, feel free to reopen it if needed.
