### ISSUE TITLE
相同模型在不同机器上预测报错core dump，paddle版本相同

### ISSUE THREAD

**Issue by snowsteper** [PaddlePaddle/Paddle#12674]
模型在训练机器上可以正常预测，在另一台机器上预测报错，均是用cpu预测（--use_gpu=False --trainer_count=1）
paddle版本都是PaddlePaddle 0.14.0.post85

报错信息：
Thread [140259229722368] Forwarding __bidirectional_gru_0___fw, 
*** Aborted at 1534163416 (unix time) try "date -d @1534163416" if you are using GNU date ***
PC: @                0x0 (unknown)
*** SIGABRT (@0x1f800000ddf) received by PID 3551 (TID 0x7f90a5906700) from PID 3551; stack trace: ***
    @     0x7f90a50bd160 (unknown)
    @     0x7f90a462b3f7 __GI_raise
    @     0x7f90a462c7d8 __GI_abort
    @     0x7f90a01921e5 tcmalloc::Log()
    @     0x7f90a018d00c (anonymous namespace)::InvalidFree()
    @     0x7f90a038f5ce operator delete()
    @     0x7f909f25b9a0 std::basic_ostringstream<>::~basic_ostringstream()
    @     0x7f8ff8128b67 google::MakeCheckOpString<>()
    @     0x7f8ff837108c hl_stream_synchronize()
    @     0x7f8ff80a3b2e paddle::GatedRecurrentLayer::forwardBatch()
    @     0x7f8ff80a4c02 paddle::GatedRecurrentLayer::forward()
    @     0x7f8ff7f91e1d paddle::NeuralNetwork::forward()
    @     0x7f8ff7f3057d _wrap_GradientMachine_forward
    @     0x7f90a53d660f PyEval_EvalFrameEx
    @     0x7f90a53d9f3d PyEval_EvalCodeEx
    @     0x7f90a53d71b5 PyEval_EvalFrameEx
    @     0x7f90a53d9f3d PyEval_EvalCodeEx
    @     0x7f90a53d71b5 PyEval_EvalFrameEx
    @     0x7f90a53456c3 gen_iternext
    @     0x7f90a53d32fc PyEval_EvalFrameEx
    @     0x7f90a53456c3 gen_iternext
    @     0x7f90a53d32fc PyEval_EvalFrameEx
    @     0x7f90a53d9f3d PyEval_EvalCodeEx
    @     0x7f90a53d71b5 PyEval_EvalFrameEx
    @     0x7f90a53d72d0 PyEval_EvalFrameEx
    @     0x7f90a53d72d0 PyEval_EvalFrameEx
    @     0x7f90a53d9f3d PyEval_EvalCodeEx
    @     0x7f90a53da072 PyEval_EvalCode
    @     0x7f90a5402e32 PyRun_FileExFlags
    @     0x7f90a54041c9 PyRun_SimpleFileExFlags
    @     0x7f90a541a09d Py_Main
    @     0x7f90a4617bd5 __libc_start_main
已放弃 (core dumped)

**Comment by qingqing01** [comment]
如果是CPU预测，要注释机器是否支持avx，可以通过：

grep avx /proc/cpuinfo

查看。
