### ISSUE TITLE
soft_binary_class_cross_entropy如何使用

### ISSUE THREAD

**Issue by zhangyong15** [PaddlePaddle/Paddle#1268]
label为dense_vector, cost函数使用soft_binary_class_cross_entropy，这个如何配置啊？

**Comment by HugoLian** [comment]
按这个顺序写行不 cross_entropy(input, label, name=None, coeff=1.0, layer_attr=None)
基础的配置input label就好了

**Comment by mufasalab** [comment]
并不行，我贴下配置
![2017-02-06 4 09 50](https://cloud.githubusercontent.com/assets/22140712/22638994/be3b9632-ec86-11e6-8455-8d731654d4fd.png)

**Comment by mufasalab** [comment]
报错如下:
![2017-02-06 4 10 50](https://cloud.githubusercontent.com/assets/22140712/22639022/dd9d61a4-ec86-11e6-8026-a587d69f9dd6.png)

还有个问题cross_entropy就是以前的soft_binary_class_cross_entropy ?

**Comment by reyoung** [comment]
这个cost没有到配置解析里面，我加一下。

**Comment by mufasalab** [comment]
label是否支持dense vecotr ？

**Comment by lcy-seso** [comment]
I close this issue due to inactivity, please feel free to reopen it.
