### ISSUE TITLE
Book希望Paddle提供的功能

### ISSUE THREAD

**Issue by luotao1** [PaddlePaddle/Paddle#1269]
机器翻译
 - attention weight的heap map如下图。该功能有现成的evaluator可以直接调用。
![default](https://cloud.githubusercontent.com/assets/6836917/22639763/8d4f1270-ec8a-11e6-9325-741a360d3377.PNG)
 - beam search希望得到每个词的概率，用于自定义剪枝 #1135 。该功能需要改c++代码，但工作量不大。
 - decoding每一步解码都能展示。该功能实现工作量很大，同时展示时beam size得小，且选择短句子。

**Comment by reyoung** [comment]
1、线性回归
	* 在训练过程中，展示训练进度
		* 实时显示cost值
		* 实时显示每一个特征的权重。
			* 在这个例子里，特征的权重是有物理意义的。权重越大，就说明这个特征越重要。越接近于0，说明这个特征不重要
	* 如果加上L1正则，可能能够看出来哪些特征是非常没用的。
2、手写识别
	* 既然同时对比了Softmax回归，MLP和CNN的网络，那么网络训练效果也可以对比一下。
		* 三个网络，跑过同样数据误差下降的曲线，识别率上升曲线
		* 三个网络参数大小的对比
	* 什么是卷积？什么是卷积核？
		这里可以给出引用(https://en.wikipedia.org/wiki/Kernel_(image_processing)) 卷积神经网络就是学习卷积核的神经网络
* 可视化的显示经过卷积后的图像

3、图像分类
	既然和手写识别类似，是不是卷积，池化的介绍不需要再写一遍了？

**Comment by helinwang** [comment]
Closed due to inactivity.
