### ISSUE TITLE
Paddle Fluid 中的array是否等价于C语言中的数组？

### ISSUE THREAD

**Issue by zzhzz** [PaddlePaddle/Paddle#12699]
因为某些原因，需要使用Paddle开发一个模型，而这个模型中有递归构建的过程。考虑到Paddle目前似乎暂未支持递归，故打算使用栈+循环的过程来完成模型的递归构建。请问使用Paddle Fluid能够完成吗？我知道的是如果fluid中的array等价于C语言中的数组，那么可以用Whileop和array来完成这一任务

**Comment by reyoung** [comment]
目前应该不太支持『递归』功能。虽然我们用Array和WhileOp可以模拟递归的前向，但是反向传播需要特殊支持一下。目前Paddle/Fluid不支持这一功能。
