### ISSUE TITLE
paddle CAPI中多data_layer输入的实现方法

### ISSUE THREAD

**Issue by snowsteper** [PaddlePaddle/Paddle#12708]
当前使用一个有三个数据层的输入的模型做预测，模型的输入部分如下：
![image](https://user-images.githubusercontent.com/16777018/44128896-084c4b9e-a078-11e8-8d6b-0431e5ba5c70.png)

问题是，这样的模型想用CAPI实现预测，in_args变量应该怎么设置，当前我采用的方式是
把3个输入拼成一个paddle_ivector，然后通过seq_pos设置paddle_arguments_set_sequence_start_pos(in_args, 0, 0, seq_pos)，把ivector切分成三段，请问这样是否可行？

**Comment by qingqing01** [comment]
@snowsteper 请参考文档：http://paddlepaddle.org/documentation/docs/zh/0.12.0/howto/capi/organization_of_the_inputs_cn.html#permalink-4--

也可以参考issue：https://github.com/PaddlePaddle/Paddle/issues/11911

三个data layer不能拼接，in_args里有3个，各自设置，伪代码如下：


```c++
paddle_arguments in_args = paddle_arguments_create_none();
CHECK(paddle_arguments_resize(in_args, 3));

CHECK(paddle_arguments_set_ids(in_args, 0, data_char));
CHECK(paddle_arguments_set_sequence_start_pos(in_args, 0, 0, char_seq_pos));

CHECK(paddle_arguments_set_ids(in_args, 1, data_word));
CHECK(paddle_arguments_set_sequence_start_pos(in_args, 1, 0, word_seq_pos));

CHECK(paddle_arguments_set_ids(in_args, 2, data_phrase));
CHECK(paddle_arguments_set_sequence_start_pos(in_args, 2, 0, phrase_seq_pos));
```
