### ISSUE TITLE
I want to use both sequence features and BOW feature in a single model.

### ISSUE THREAD

**Issue by xdsoul** [PaddlePaddle/Paddle#1270]
How can i config the network?
E.g., using text CNN to model seq and then feed to a fully-connected layer
great thx.
![demo](https://cloud.githubusercontent.com/assets/4352866/22640949/cef0adce-ec8f-11e6-8a5f-fda0b10078bf.png)
 plus BOW features.

**Comment by kuke** [comment]
Closed because of inactivity
