### ISSUE TITLE
关于开发operator的事情

### ISSUE THREAD

**Issue by zzhzz** [PaddlePaddle/Paddle#12704]
我打算开发一个自己定制的卷积操作。我使用的开发环境是CLion，在创建.cc与.cu文件时CLion让我选择将文件并入哪些Makefile，请问开发operator创建的文件应该放在哪些Makefile中？

**Comment by Yancey0623** [comment]
您好，加新的Op可以参考这篇文档： https://github.com/PaddlePaddle/Paddle/blob/develop/doc/fluid/dev/new_op_cn.md

源码编译的方法可以参考：http://paddlepaddle.org/documentation/docs/zh/0.14.0/new_docs/beginners_guide/install/install_doc.html#others

推荐使用Docker环境进行源码编译，可以避免大部分的环境依赖问题。

> 我使用的开发环境是CLion，在创建.cc与.cu文件时CLion让我选择将文件并入哪些Makefile，

不熟悉CLion，其实可以直接在命令行用cmake来编译。

**Comment by zzhzz** [comment]
就是我只需要直接创建operator就可以，而不需要管Makefile之类的事情吗 @Yancey1989
