### ISSUE TITLE
有关Paddle优化器中的L2 regularization接口问题

### ISSUE THREAD

**Issue by usafchn** [PaddlePaddle/Paddle#12718]
如果给paddle的优化器配置l2 decay，比如：
```
            optimizer = fluid.optimizer.Momentum(
                learning_rate=xxxx,
                momentum=FLAGS.momentum,
                use_nesterov=True,
                regularization=fluid.regularizer.L2DecayRegularizer(FLAGS.weight_decay)
            )
```

实现上paddle会给所有variable加上正则，包括每一层的bias，如果要关掉bias上的正则，还需要给每一层：
fluid.layers.conv2d(xxx……,  bias_attr=False, xxxx……)
手动关掉bias的正则，比较麻烦。

我个人觉得很少有模型会给bias加正则，当optimizer配置全局正则的时候，应该默认就跳过bias，这样的设计会比较好点？

**Comment by qingqing01** [comment]
我感觉在优化器里配置regularization，作用于所有的参数是合理的，对于优化器来说weight和bias都是参数，理论上不会区别对待。  

为了使用方便，是可以提供把所有Parameter统一拿出来，判断如果是bias，for循环设置正则是0，而不是到每个layer里设置。同样learning等其他超参数也支持类似的设置方式。

**Comment by lucywsq** [comment]
您好，此issue在近一个月内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题， 我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持!
