### ISSUE TITLE
能运行VGGNet 模型在PaddlePadle里么?

### ISSUE THREAD

**Issue by gaoshan2006** [PaddlePaddle/Paddle#1271]
能在Paddle 中使用,  VGGNet,/AlextNet/GoogleNet  这些用 prototxt 文件定义的标准模型吗 ?  我没有在Paddle 的demo 中找到使用的例子.  如果想用 Paddle 做类似 ImageNet 这样的事情可以吗? 谢谢

**Comment by qingqing01** [comment]
用于PaddlePaddle的AlexNet、GoogleNet的网络配置可参考 https://github.com/PaddlePaddle/Paddle/tree/develop/benchmark/paddle/image 
VGG、ResNet可参考https://github.com/PaddlePaddle/book/tree/develop/image_classification/models

基于ImageNet训练完全可以，可参考图像分类的教程。

**Comment by luotao1** [comment]
Too old to close.
