### ISSUE TITLE
function_attributes(): after cudaFuncGetAttributes: invalid device function

### ISSUE THREAD

**Issue by yogurfrul** [PaddlePaddle/Paddle#12711]
我在ubuntu16自己docker里 安装了cuda9.0+cudnn7.0.5 硬件是Tesla V100
然后安装了pip2 instal paddlepaddle-gpu
也打印了 Successfully installed paddlepaddle-gpu-0.14.0.post87

但我是在跑 MLperf [Seq-CNN例子](https://github.com/mlperf/reference/tree/master/sentiment_analysis)时报错
```
Traceback (most recent call last):
  File "train.py", line 214, in <module>
    save_dirname="understand_sentiment_conv.inference.model")
  File "train.py", line 188, in main
    save_dirname=save_dirname)
  File "train.py", line 173, in train
    train_loop(fluid.default_main_program())
  File "train.py", line 137, in train_loop
    exe.run(fluid.default_startup_program())
  File "/usr/local/lib/python2.7/dist-packages/paddle/fluid/executor.py", line 443, in run
    self.executor.run(program.desc, scope, 0, True, True)
RuntimeError: function_attributes(): after cudaFuncGetAttributes: invalid device function

```

**Comment by qingqing01** [comment]
@yogurfrul 请问你使用的docker还是nvidia-docker？

**Comment by yogurfrul** [comment]
nvidia-docker

**Comment by yogurfrul** [comment]
我这样安装 就可以了 
pip2 instal paddlepaddle-gpu==0.14.0

我明明装的cuda9.0 cudnn7 不知道你们为啥不指定版本号就给我安装paddlepaddle-gpu-0.14.0.post87

**Comment by shanyi15** [comment]
您好，请您参考这个issue https://github.com/PaddlePaddle/Paddle/issues/12284#event-1744545535，也请 @typhoonzero @JiabinYang 看一下

**Comment by lucywsq** [comment]
您好，此issue在近一个月内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题， 我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持!
