### ISSUE TITLE
 `F0815 03:23:10.625906 20323 threaded_ssa_graph_executor.cc:206] Unknown exception catched

### ISSUE THREAD

**Issue by lijing1996** [PaddlePaddle/Paddle#12712]
程序在单卡上能跑，切到多卡上时碰到下面的问题么请问这是什么问题呢？

> F0815 03:23:10.625906 20323 threaded_ssa_graph_executor.cc:206] Unknown exception catched
*** Check failure stack trace: ***
F0815 03:23:10.625910 20314 threaded_ssa_graph_executor.cc:206] Unknown exception catched
*** Check failure stack trace: ***
    @     0x7f868fb2643d  google::LogMessage::Fail()
    @     0x7f868fb2643d  google::LogMessage::Fail()
    @     0x7f868fb29eec  google::LogMessage::SendToLog()
    @     0x7f868fb29eec  google::LogMessage::SendToLog()
    @     0x7f868fb25f63  google::LogMessage::Flush()
    @     0x7f868fb25f63  google::LogMessage::Flush()
    @     0x7f868fb2b3fe  google::LogMessageFatal::~LogMessageFatal()
    @     0x7f868fb2b3fe  google::LogMessageFatal::~LogMessageFatal()
    @     0x7f868f81d0dd  _ZZN6paddle9framework7details24ThreadedSSAGraphExecutor5RunOpEPNS0_13BlockingQueueIPNS1_13VarHandleBaseEEEPNS1_12OpHandleBaseEENKUlvE_clEv
    @     0x7f868f81d0dd  _ZZN6paddle9framework7details24ThreadedSSAGraphExecutor5RunOpEPNS0_13BlockingQueueIPNS1_13VarHandleBaseEEEPNS1_12OpHandleBaseEENKUlvE_clEv
    @     0x7f868f6997a3  std::_Function_handler<>::_M_invoke()
    @     0x7f868f6997a3  std::_Function_handler<>::_M_invoke()
    @     0x7f868f699f37  std::__future_base::_State_base::_M_do_set()
    @     0x7f868f699f37  std::__future_base::_State_base::_M_do_set()
    @     0x7f86e761ea99  __pthread_once_slow
    @     0x7f86e761ea99  __pthread_once_slow
    @     0x7f868f81b982  _ZNSt13__future_base11_Task_stateISt5_BindIFZN6paddle9framework7details24ThreadedSSAGraphExecutor5RunOpEPNS3_13BlockingQueueIPNS4_13VarHandleBaseEEEPNS4_12OpHandleBaseEEUlvE_vEESaIiEFvvEE6_M_runEv
    @     0x7f868f81b982  _ZNSt13__future_base11_Task_stateISt5_BindIFZN6paddle9framework7details24ThreadedSSAGraphExecutor5RunOpEPNS3_13BlockingQueueIPNS4_13VarHandleBaseEEEPNS4_12OpHandleBaseEEUlvE_vEESaIiEFvvEE6_M_runEv
    @     0x7f868f81ff94  _ZZN10ThreadPoolC1EmENKUlvE_clEv
    @     0x7f868f81ff94  _ZZN10ThreadPoolC1EmENKUlvE_clEv
    @     0x7f86a2b4ac5c  execute_native_thread_routine_compat
    @     0x7f86a2b4ac5c  execute_native_thread_routine_compat
    @     0x7f86e76176ba  start_thread
    @     0x7f86e76176ba  start_thread
    @     0x7f86e6c3d41d  clone
    @     0x7f86e6c3d41d  clone
    @              (nil)  (unknown)
Aborted (core dumped)

**Comment by qingqing01** [comment]
@lijing1996 从这个log没看出具体问题，请问你使用的是哪个版本？可否跑个paddle提供的多卡示例验证下？

**Comment by lucywsq** [comment]
您好，此issue在近一个月内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题，我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持!
