### ISSUE TITLE
fluid下scatter操作对输入参数要求有问题

### ISSUE THREAD

**Issue by luameows** [PaddlePaddle/Paddle#12725]
a，labels，diff的dtype分别为float32, int64, float32
调用fluid下`layers.scatter(x=a,ids=labels,updates=diff)`，提示错误`operator scatter must input same dtype. VarType.FP32 vs VarType.INT64`

后来跟进代码里面，发现按照这个check逻辑，scatter的三个输入的dtype必须要求一致才行。
![image](https://user-images.githubusercontent.com/30432086/44147240-cec7560e-a0c5-11e8-9a7f-5fafb451017f.png)

按照scatter的用法说明，ids为对应索引index，不应该是float类型吧？请问下这是什么原因呢？

**Comment by qingqing01** [comment]
@luameows 看了下是个op Python API封装的原因，内部实现的原因，Python API需要手动封装下，我们稍后修复下下吧，抱歉。

如果着急使用，可以仿照 https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/fluid/layers/nn.py 里自行先封装~

**Comment by luameows** [comment]
@qingqing01 谢谢您的答复。由于我是在科赛平台上使用的paddlepaddle，似乎没法对源码进行修改。烦请您在修正该bug后给我一个反馈吧，我好重新下载。

**Comment by ktlichkid** [comment]
新加了scatter op的python API，麻烦您试试可以用不能

**Comment by luameows** [comment]
@ktlichkid 实在不好意思再打扰下，我如果要更新paddle版本，是不是只能通过下载源码编译的方式来更新，而无法通过pip install获取。
另外，看了下您对scatter部分的修改，似乎将out=Out[id]+update修改成了out[id]=update。

**Comment by luameows** [comment]
@ktlichkid @qingqing01 @luotao1 
我安装了最新版本的whl包，调用scatter，还是有些问题。
其中label.shape=(-1,1)，label_reshape.shape=(-1,)。features是我的网络输出层，shape=(-1,512)
```
label=fluid.layers.data(name='label',shape=[1],dtype='int64')
label_reshape=fluid.layers.reshape(x=label,shape=[-1],name='label_reshape')
centers_global=fluid.layers.scatter(input=centers_global,index=label_reshape,updates=diff)
test=fluid.layers.scatter(input=features,index=label_reshape,updates=features)
```
错误信息如下
```
--> 386     test=fluid.layers.scatter(input=features,index=label_reshape,updates=features)


/usr/local/lib/python2.7/dist-packages/paddle/fluid/layers/layer_function_generator.pyc in func(*args, **kwargs)
    172         helper = LayerHelper(op_type, **kwargs)
    173 
--> 174         dtype = infer_and_check_dtype(op_proto, *args, **kwargs)
    175 
    176         inputs = dict()

/usr/local/lib/python2.7/dist-packages/paddle/fluid/layers/layer_function_generator.pyc in infer_and_check_dtype(op_proto, *args, **kwargs)
    152                 val = [val]
    153             if len(val) == 0:
--> 154                 val = [args[0]]
    155                 args = args[1:]
    156 

IndexError: tuple index out of range
```
