### ISSUE TITLE
paddle运行image_classification这个demo时，执行sh train.sh，出现下面的问题：

### ISSUE THREAD

**Issue by leanna62** [PaddlePaddle/Paddle#1272]
Python Error: <type 'exceptions.IndexError'> : too many indices for array
Python Callstack: 
            /home/work/paddle/bin_install/output/python27-gcc482/lib/python2.7/site-packages/paddle/trainer/PyDataProvider2.py : 132
            /home/work/paddle/bin_install/book-develop/image_classification/dataprovider.py : 41
Calling iterator next error
*** Check failure stack trace: ***
    @          0x13b4438  google::LogMessage::Fail()
    @          0x13b4390  google::LogMessage::SendToLog()
    @          0x13b3e25  google::LogMessage::Flush()
    @          0x13b6be6  google::LogMessageFatal::~LogMessageFatal()
    @           0x5bd702  paddle::PyDataProvider2::loadThread()
    @     0x7f1020dd08a0  execute_native_thread_routine
    @     0x7f102164e1c3  start_thread
    @     0x7f102054112d  __clone

**Comment by qingqing01** [comment]
Thanks! I will fix it soon.

**Comment by qingqing01** [comment]
@leanna62  请参考修改 https://github.com/PaddlePaddle/book/pull/60

**Comment by leanna62** [comment]
谢谢哈，已解决～
