### ISSUE TITLE
测试operator只能通过python接口吗

### ISSUE THREAD

**Issue by zzhzz** [PaddlePaddle/Paddle#12731]
我实现完成一个operator之后想通过C++代码来对operator本身做测试，请问只能通过Optest（使用Python接口）的方式吗？我可以不可以自己创建一个单独的测试代码？如果可以的话，怎样启动测试过程？需要将整个paddle重新编译一次吗？我看到一个C++测试的例子：https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/fluid/operators/math/im2col_test.cc ，请问怎么启动类似这样的测试呢？

**Comment by typhoonzero** [comment]
新Op编写方法请参考文档：
http://www.paddlepaddle.org/documentation/docs/zh/0.14.0/new_docs/advanced_usage/development/new_op.html

通常使用Python编写op单测，便于用标准实现（比如numpy或naive实现）检测计算正确性。特殊op可以考虑使用c++编写单测，可以参考`test_send_nccl_id.cc`，`im2col_test.cc`是针对通用计算的functor的单测，如果有这样的实现也可以独立实现。
