### ISSUE TITLE
使用dict显式指定input_types后，加载数据的中途抛 Check failed: PySequence_Check(seq_)

### ISSUE THREAD

**Issue by buptzzl** [PaddlePaddle/Paddle#1273]
我使用 0.90版本。而且是加载了一部分数据后中途抛出这个错误（下面的错误日志中的[debug] ins keys... 部分即process()函数中自己在yield 之前加的debug 内容）：
# this is shell 
$ paddle version
PaddlePaddle 0.9.0a0, compiled with
    with_avx: ON
    with_gpu: OFF
    with_double: OFF
    with_python: ON
    with_rdma: OFF
    with_glog: ON
    with_gflags: ON
    with_metric_learning: 
    with_timer: OFF
    with_predict_sdk: 
# this is shell
$ sh train.sh 
Paddle release a new version 0.9.0, you can get the install package in http://www.paddlepaddle.org
I0207 10:50:41.679668 34506 Util.cpp:155] commandline: /home/zhouliaoming01/libs/paddle_neibu_bin/local/output/bin/../opt/paddle/bin/paddle_trainer --config=trainer_config.base.py --save_dir=./output --trainer_count=10 --log_period=100 --num_passes=5 --use_gpu=false --show_parameter_stats_period=100 --test_all_data_in_one_period=1-
I0207 10:50:41.679867 34506 Util.cpp:130] Calling runInitFunctions
I0207 10:50:41.680160 34506 Util.cpp:143] Call runInitFunctions done.
[debug] trainer_config.conf
[INFO 2017-02-07 10:50:41,814 networks.py:1466] The input order is [input0, input1, input2, input3, input4, input5, input6, input7, input8, input9, input10, label]
[INFO 2017-02-07 10:50:41,814 networks.py:1472] The output order is [__cost_0__]
I0207 10:50:41.816539 34506 Trainer.cpp:122] ignore sparse_remote_update=true due to  --local=true
I0207 10:50:41.816560 34506 Trainer.cpp:167] trainer mode: SgdSparseCpuTraining
I0207 10:50:41.871948 34506 PyDataProvider2.cpp:257] loading dataprovider dataprovider::process
I0207 10:50:41.873567 34506 PyDataProvider2.cpp:257] loading dataprovider dataprovider::process
I0207 10:50:41.873749 34506 GradientMachine.cpp:134] Initing parameters..
I0207 10:50:41.899520 34506 GradientMachine.cpp:141] Init parameters done.
[info] process() begin. used_slots: ['input0', 'input1', 'input10', 'input2', 'input3', 'input4', 'input5', 'input6', 'input7', 'input8', 'input9', 'label']
[debug] ins keys: ['input2', 'input3', 'input0', 'input6', 'input7', 'input4', 'input5', 'input8', 'input9', 'label', 'input10']
[debug] ins keys: ['input2', 'input3', 'input0', 'input6', 'input7', 'input4', 'input5', 'input8', 'input9', 'label', 'input10']
I0207 10:51:08.878790 34848 ThreadLocal.cpp:37] thread use undeterministic rand seed:34849
F0207 10:51:08.878875 34848 PythonUtil.h:215] Check failed: PySequence_Check(seq_)-
*** Check failure stack trace: ***
    @          0x13b4438  google::LogMessage::Fail()
    @          0x13b4390  google::LogMessage::SendToLog()
    @          0x13b3e25  google::LogMessage::Flush()
    @          0x13b6be6  google::LogMessageFatal::~LogMessageFatal()
    @           0x5ba23e  paddle::SparseNonValueScanner::prepare()
    @           0x5bfda5  paddle::PyDataProvider2::getNextBatchInternal()
    @           0x5a0c12  paddle::DoubleBuffer::asyncLoadBatch()
    @     0x7ff4c2d7e8a0  execute_native_thread_routine
    @     0x7ff4c35fc1c3  start_thread
    @     0x7ff4c24ef12d  __clone
/home/zhouliaoming01/libs/paddle_neibu_bin/local/output/bin/paddle_local: line 109: 34506 已放弃               ${DEBUGGER} $MYDIR/../opt/paddle/bin/paddle_trainer ${@:2}

**Comment by zhangyong15** [comment]
@buptzzl 这个问题您解决了么？我也遇到同样的问题
