### ISSUE TITLE
Segmentation fault(core dumped) 是什么原因？

### ISSUE THREAD

**Issue by hxk11111** [PaddlePaddle/Paddle#12769]
跑相同的代码，有的时候一运行就崩溃，有的时候是能够迭代几次再崩溃，并且无详细报错原因。
下面这段是在迭代了四轮之后报的错：
*** Aborted at 1534493112 (unix time) try "date -d @1534493112" if you are using GNU date ***
PC: @                0x0 (unknown)
*** SIGSEGV (@0x7f9800000002) received by PID 6873 (TID 0x7f98f132a700) from PID 2; stack trace: ***
    @     0x7f98f0f0c390 (unknown)
    @           0x4bc296 PyEval_EvalFrameEx
    @           0x4b9ab6 PyEval_EvalCodeEx
    @           0x4c1e6f PyEval_EvalFrameEx
    @           0x4b9ab6 PyEval_EvalCodeEx
    @           0x4c1e6f PyEval_EvalFrameEx
    @           0x4b9ab6 PyEval_EvalCodeEx
    @           0x4c1e6f PyEval_EvalFrameEx
    @           0x4b9ab6 PyEval_EvalCodeEx
    @           0x4c1e6f PyEval_EvalFrameEx
    @           0x4c136f PyEval_EvalFrameEx
    @           0x4b9ab6 PyEval_EvalCodeEx
    @           0x4eb30f (unknown)
    @           0x4e5422 PyRun_FileExFlags
    @           0x4e3cd6 PyRun_SimpleFileExFlags
    @           0x493ae2 Py_Main
    @     0x7f98f0b51830 __libc_start_main
    @           0x4933e9 _start
    @                0x0 (unknown)
Segmentation fault (core dumped)

下面这段是运行之后一轮还未迭代完就报的错：
*** Aborted at 1534492217 (unix time) try "date -d @1534492217" if you are using GNU date ***
PC: @                0x0 (unknown)
*** SIGSEGV (@0x7f0300000002) received by PID 6836 (TID 0x7f0362c02700) from PID 2; stack trace: ***
    @     0x7f03627e4390 (unknown)
    @     0x7f0300000002 (unknown)
Segmentation fault (core dumped)

请问下是什么原因？？

**Comment by chengduoZH** [comment]
@hxk11111 从报错信息上看你的输入的数据可能有异常，您输入的数据是否做了shuffle?
另外，您用的是Fluid还是V2，请说明。

**Comment by hxk11111** [comment]
@chengduoZH 我用的Fluid，已经对数据做了shuffle，之前用相同数据跑通过，还有可能其他原因吗。谢谢

**Comment by hxk11111** [comment]
@chengduoZH 如果是数据有问题的话，不应该第一轮迭代就会报错吗，有的时候是迭代了几轮之后才报的错，下面是我跑相同代码，迭代了两轮之后，第三轮报错了。

[Train] precision:0.95636802412, recall:0.962871439716, f1:0.959608713383
[Validation] precision:0.977395283485, recall:0.976412678541, f1:0.976903733928
************************************************************************************************
Best F1 Score, Saving model at Iteration 0
pass_id:1, time_cost:162.314188004s
[Train] precision:0.980808946981, recall:0.982174436103, f1:0.981491216612
[Validation] precision:0.981641970973, recall:0.979828318047, f1:0.980734306022
************************************************************************************************
Best F1 Score, Saving model at Iteration 1
*** Aborted at 1534575811 (unix time) try "date -d @1534575811" if you are using GNU date ***
PC: @                0x0 (unknown)
*** SIGSEGV (@0x2) received by PID 11487 (TID 0x7f02cbaea700) from PID 2; stack trace: ***
    @     0x7f02cb6cc390 (unknown)
    @     0x7f02add2e328 std::string::string()
    @     0x7f0295fb695b std::__detail::_Map_base<>::operator[]()
    @     0x7f0295fb4267 paddle::framework::Scope::VarInternal()
    @     0x7f0295fb43ae paddle::framework::Scope::Var()
    @     0x7f0295f3a843 paddle::framework::details::ScopeBufferedSSAGraphExecutor::Run()
    @     0x7f029583927c paddle::framework::ParallelExecutor::Run()
    @     0x7f02957bfc56 _ZZN8pybind1112cpp_function10initializeIZNS0_C1IvN6paddle9framework16ParallelExecutorEIRKSt6vectorISsSaISsEERKSsEINS_4nameENS_9is_methodENS_7siblingEEEEMT0_FT_DpT1_EDpRKT2_EUlPS5_SA_SC_E_vISQ_SA_SC_EISD_SE_SF_EEEvOSH_PFSG_SJ_ESP_ENUlRNS_6detail13function_callEE1_4_FUNESX_
    @     0x7f029579b46c pybind11::cpp_function::dispatcher()
    @           0x4c37ed PyEval_EvalFrameEx
    @           0x4b9ab6 PyEval_EvalCodeEx
    @           0x4c16e7 PyEval_EvalFrameEx
    @           0x4c136f PyEval_EvalFrameEx
    @           0x4b9ab6 PyEval_EvalCodeEx
    @           0x4eb30f (unknown)
    @           0x4e5422 PyRun_FileExFlags
    @           0x4e3cd6 PyRun_SimpleFileExFlags
    @           0x493ae2 Py_Main
    @     0x7f02cb311830 __libc_start_main
    @           0x4933e9 _start
    @                0x0 (unknown)
Segmentation fault (core dumped)

**Comment by chengduoZH** [comment]
@hxk11111 Can you display your training model and configuration here? I plan to reproduce this error in my evn.
