### ISSUE TITLE
利用bcloud编译完成后，运行出错！

### ISSUE THREAD

**Issue by Kevinlsy** [PaddlePaddle/Paddle#12763]
$ ./objectdetect 
I0817 14:18:27.279603  7532 Util.cpp:166] commandline:  --use_gpu=True 
*** Aborted at 1534486707 (unix time) try "date -d @1534486707" if you are using GNU date ***
PC: @                0x0 (unknown)
*** SIGSEGV (@0x7f8b11112e40) received by PID 7532 (TID 0x7f8b11107940) from PID 286338624; stack trace: ***
    @     0x7f8afc3fe160 (unknown)
    @     0x7f8b10ef7fd4 open_path
    @     0x7f8b10efa0ab _dl_map_object
    @     0x7f8b10f04805 dl_open_worker
    @     0x7f8b10f00694 _dl_catch_error
    @     0x7f8b10f0421b _dl_open
    @     0x7f8b1049501b dlopen_doit
    @     0x7f8b10f00694 _dl_catch_error
    @     0x7f8b104955cd _dlerror_run
    @     0x7f8b104950b1 __dlopen_check
    @     0x7f8b0f4d9036 cudart::globalState::loadDriverInternal()
    @     0x7f8b0f4da223 cudart::__loadDriverInternalUtil()
    @     0x7f8afc3fb973 __GI___pthread_once
    @     0x7f8b0f509629 cudart::cuosOnce()
    @     0x7f8b0f4da82e cudart::globalState::initializeDriver()
    @     0x7f8b0f4f040a cudaGetDeviceCount
    @     0x7f8b0f3f6b4f hl_specify_devices_start()
    @     0x7f8b0f3f71dd hl_start()
    @     0x7f8b0f3786aa paddle::initMain()
    @     0x7f8b0efd49f0 paddle_init
    @           0x4032f7 main
    @     0x7f8afc062bd5 __libc_start_main
    @           0x4034d1 (unknown)
    @                0x0 (unknown)
Segmentation fault

我用cmake编译是可以正常运行的（但是这台机器不能连内网，所以没法使用bcloud编译），换了台机器，利用bcloud编译，就出现以上错误。

**Comment by chengduoZH** [comment]
@Kevinlsy 从报错信息上看，程序在获取GPU个数的时候报错，所以请检查一下您编译的时候是否选择了`WITH_GPU=ON`

```
@ 0x7f8b0f4f040a cudaGetDeviceCount
@ 0x7f8b0f3f6b4f hl_specify_devices_start()
@ 0x7f8b0f3f71dd hl_start()
@ 0x7f8b0f3786aa paddle::initMain()
@ 0x7f8b0efd49f0 paddle_init
@ 0x4032f7 main
@ 0x7f8afc062bd5 __libc_start_main
```

**Comment by Kevinlsy** [comment]
@chengduoZH 有两个问题
1.想问下，我想用Bcloud云端编译，但是在icode上没有找到paddle合适的依赖库，内部有相关的依赖库吗？
2.现在依赖的是http://icode.baidu.com/repos/baidu/third-party/paddle-capi/tree/paddle-capi-v0.2 这个paddle支持的是cuda7.5的,有cuda8.0的依赖库在icode上吗？
现在报错GPU训练 
Check failed: cudaSuccess == err (0 vs. 8) [hl_gpu_apply_unary_op failed] CUDA error: invalid device function
是不是因为我引用icode上这个paddle支持cuda7.5而我的cuda版本8.0不匹配才导致的。
