### ISSUE TITLE
label为dense vector， cost为soft_binary_class_cross_entropy 网络配置

### ISSUE THREAD

**Issue by zhangyong15** [PaddlePaddle/Paddle#1277]
我简要描述下我的网络结构：
1. 二分类问题
2. 输入的label为dense vector = [a, b] (a + b =1)，a和b均为float
3.最后一层为sofmax，2个节点
4.cost函数选择soft_binary_class_cross_entropy

附上网络配置，疑问点用红框做标注了：
1. 关于label的维度填写，dense vector的size是填写为1还是2
关于dataprovider.py部分
<img width="490" alt="3b02a7083f18c0460abfecfad78eeb25" src="https://cloud.githubusercontent.com/assets/22140712/22679935/6cb06fe4-ed40-11e6-833d-94d7e8188dba.png">

<img width="651" alt="8b021f2f80536c6d64706da1129793ad" src="https://cloud.githubusercontent.com/assets/22140712/22679994/c36cabe0-ed40-11e6-903c-00afafb8ae64.png">

2. 关于网络配置
由于soft_binary_class_cross_entropy新接口还未添加，故沿用老配置方式：
前一个issue中提到bug， last_layer需要设置为8的倍数，这个值会对配置产生影响，导致check无法通过。

<img width="976" alt="ad858533a33f3ba05fa079409aade89f" src="https://cloud.githubusercontent.com/assets/22140712/22680145/7f7b3702-ed41-11e6-93e4-cc9be9aca00f.png">

上述部分疑问比较多，烦请帮忙下，谢谢！

**Comment by mufasalab** [comment]
在现有master版本之下，该如何解决

**Comment by reyoung** [comment]
> 关于label的维度填写，dense vector的size是填写为1还是2

为8。

返回的label_vec = [0.1, 0.9, 0.0, ...]

Label那个data_layer的size，也设置成8

**Comment by mufasalab** [comment]
升级到最新版本的code，可以解决最后一个label需要为8的倍数这个问题；网络设置上，label 的size均设置为1。

 谢谢@reyoung 的耐心帮助。
