### ISSUE TITLE
Mac环境编译错误

### ISSUE THREAD

**Issue by zzhzz** [PaddlePaddle/Paddle#12784]
错误信息如下：
Paddle/paddle/fluid/framework/ir/graph_pattern_detecter.cc:100:40:
error: implicit instantiation of undefined template 'std::__1::array<std::__1::vector<paddle::framework::ir::HitGroup, std::__1::allocator<paddle::framework::ir::HitGroup> >, 2>'
  std::array<std::vector<HitGroup>, 2> bi_records;

**Comment by kuke** [comment]
@zzhzz 可以在docker中编译试试
