### ISSUE TITLE
Hello guys！ Do you know how to compute arctanh in paddlepaddle?

### ISSUE THREAD

**Issue by jayxio** [PaddlePaddle/Paddle#12794]
大家好！

There is a `fluid.layers.tanh()` for us to compute `tanh`. What about `arctanh`? Is there an API for this? Or if there is any other way?

Best,
Jay

**Comment by guoshengCS** [comment]
There isn't  such API currently, and may you can implement `arctanh` by combining some other operators according to the formula temporarily.

**Comment by jayxio** [comment]
Thank you!
