### ISSUE TITLE
请问mpi集群上怎么看回归模型的评估指标

### ISSUE THREAD

**Issue by almostlove** [PaddlePaddle/Paddle#12797]
问下回归模型在mpi集群训练完成后怎么用一些评估指标类似mse的看结果啊  paddle.evaluator有提供么

**Comment by guoshengCS** [comment]
可以使用square_error_cost，参考链接见
V2：
http://www.paddlepaddle.org/documentation/api/zh/0.12.0/config/layer.html#square-error-cost
Fluid：http://www.paddlepaddle.org/documentation/api/zh/0.14.0/layers.html#square-error-cost

**Comment by almostlove** [comment]
您好 不是训练时的cost 是验证时候用来看的评估指标  例如查看测试集上的auc。  paddle.evaluator.auc(name = 'out_label', input = label, label = lbl_click)  这种打印出来的。

**Comment by guoshengCS** [comment]
回归问题的话，目前没有相应的evaluator，不过可以自定义evaluator，可以参照这里 
https://github.com/PaddlePaddle/models/tree/develop/ltr#%E8%AE%AD%E7%BB%83%E8%BF%87%E7%A8%8B%E4%B8%AD%E8%BE%93%E5%87%BA%E8%87%AA%E5%AE%9A%E4%B9%89%E8%AF%84%E4%BC%B0%E6%8C%87%E6%A0%87

**Comment by almostlove** [comment]
好的感谢。
