### ISSUE TITLE
对C++中的Tensor的一些问题

### ISSUE THREAD

**Issue by zzhzz** [PaddlePaddle/Paddle#12799]
在C++代码中，如果我给一个Tensor的DDim设置为(3, 15)，我是否可以通过tensor[2][11]这样的方式来获取元素？换句话说，C++的Tensor是否重载了[]运算？如果没有的话我该如何取值呢？是需要将Tensor看做一个一维数组来取值吗？

**Comment by guoshengCS** [comment]
C++中目前没有重载[]运算，需要将Tensor看做一个一维数组来取值

**Comment by zzhzz** [comment]
在给Tensor赋值过程中，因为一些原因无法直接计算出来某个Tensor最终的大小，请问Tensor内部会自动完成内存分配吗？换句话问，Tensor可不可以使用类似std::vector<T>的push_back之类的方式来赋值？

**Comment by guoshengCS** [comment]
Fluid的OP内会进行infer shape，直接调用tensor的mutable_data就可以完成内存分配，不过没有类似push_back的赋值方式，需要使用offset赋值
