### ISSUE TITLE
Fill Constant op only for float?

### ISSUE THREAD

**Issue by xingyuanbu** [PaddlePaddle/Paddle#12792]
https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/fluid/operators/fill_constant_op.cc#L68

How can I fill int, double etc. to Tensor

**Comment by guoshengCS** [comment]
You can fill int or double by setting the argument  `dtype="int32"` or `dtype="float64"`, please refer to this: 
http://www.paddlepaddle.org/documentation/api/zh/0.14.0/layers.html#fill-constant

**Comment by xingyuanbu** [comment]
solved, thx
