### ISSUE TITLE
利用static pre-trained词向量训练文本分类模型

### ISSUE THREAD

**Issue by zjgtan** [PaddlePaddle/Paddle#12801]
1、预处理阶段：将文本切词后转化为word embedding序列
2、模型结构：
![image](https://user-images.githubusercontent.com/4132906/44320411-863b6080-a474-11e8-8ec1-303d7db9c91f.png)
3、问题：模型无法收敛
![image](https://user-images.githubusercontent.com/4132906/44320455-a4a15c00-a474-11e8-9169-b7649d97c6a6.png)

**Comment by guoshengCS** [comment]
请问是希望验证是否正确加载了static pre-trained的词向量么

**Comment by zjgtan** [comment]
恩，我没有通过embedding层加载词向量参数，而是在预处理阶段，通过请求nlpc_wordemb_v2服务，把文本转换为了词向量序列，如“北京 百度” ==> [vev1, vec2]

**Comment by guoshengCS** [comment]
应该是可以的，另外有一种方法可以把这个词向量拿出来对照下看是否正确，具体参考 http://www.paddlepaddle.org/documentation/docs/zh/0.12.0/faq/local/index_cn.html#layeroutput 中**6. 如何在训练过程中获得某一个layer的output**部分的内容

**Comment by lucywsq** [comment]
您好，此issue在近一个月内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题，我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持!
