### ISSUE TITLE
python/paddle/dataset/flowers.py wrong md5

### ISSUE THREAD

**Issue by pmajchrzak** [PaddlePaddle/Paddle#12827]
The dataset "flowers" is downloaded each time when training is run, even if it was downloaded under earlier iteration

Proposed solution:
change md5 information in file `python/paddle/dataset/flowers.py`
```
from: 33bfc11892f1e405ca193ae9a9f2a118
  to: 52808999861908f626f3c1f4e79d11fa
```

**Comment by pmajchrzak** [comment]
There is:
![image](https://user-images.githubusercontent.com/10847947/44383277-82f9b080-a518-11e8-9cc4-7e8605c1a689.png)

and then
![image](https://user-images.githubusercontent.com/10847947/44383360-cf44f080-a518-11e8-93fe-6258f6b412c3.png)

**Comment by luotao1** [comment]
@pmajchrzak Could you submit a PR to fix it? You should update both `python/paddle/dataset/flowers.py` and `python/v2/paddle/dataset/flowers.py`.
