### ISSUE TITLE
有pytorch 转 fluid 的转换工具？

### ISSUE THREAD

**Issue by youngstu** [PaddlePaddle/Paddle#12820]
你好，能帮忙提供一下 pytorch 转 fluid 的转换工具么？

**Comment by wanghaoshuang** [comment]
你好，我们暂时无法提供这种转换工具，会考虑将其列入后续工作计划中。多谢反馈。

**Comment by lucywsq** [comment]
您好，此issue在近一个月内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题， 我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持!
