### ISSUE TITLE
用老版本paddle训练的模型用 v2版本dump bin 失败

### ISSUE THREAD

**Issue by sugarfreesang** [PaddlePaddle/Paddle#12839]
有一个已有的用老版本paddle训练的模型，现在想用在线上，需要用v2的capi线上加载model。原有模型配置为：
![image](https://user-images.githubusercontent.com/17564152/44395583-e7465f80-a56c-11e8-943f-8e192a5794b5.png)

原来dump出来的模型目录结构如下：
![image](https://user-images.githubusercontent.com/17564152/44395362-3b9d0f80-a56c-11e8-9a25-a9ba96c85299.png)

预估是直接用network = swig_paddle.GradientMachine.createFromConfigProto(conf.model_config)

想请教下如何把网络结构拓扑传给 dump_v2_config 函数？

**Comment by wanghaoshuang** [comment]
你试试这个： https://github.com/PaddlePaddle/Paddle/blob/da158c2279008010996687d32b88c76e4e8ec1b7/paddle/legacy/capi/examples/model_inference/dense/convert_protobin.sh

**Comment by sugarfreesang** [comment]
嗯，可以用～谢谢haoshuang
