### ISSUE TITLE
Caffe模型转fluid模型是不是会存在精度损失的情况？

### ISSUE THREAD

**Issue by yeyupiaoling** [PaddlePaddle/Paddle#12832]
我使用这里的转换工具：https://github.com/PaddlePaddle/models/tree/develop/fluid/image_classification/caffe2fluid
转换之后，我发现准确率低了2个百分点，这是正常的吗？

如果存在，这是什么原理呢？

**Comment by wanghaoshuang** [comment]
可能的原因：
1. 初始化方式不严格相同
2. 某些op的计算不一致

建议print下各层output，debug下具体哪里导致的不一致。

**Comment by yeyupiaoling** [comment]
@wanghaoshuang 嗯嗯，您说的print，是在预测的是，加载模型的时候`print(inference_program)`吗，还是怎样？
