### ISSUE TITLE
源码开发机安装develop  问题

### ISSUE THREAD

**Issue by VamWolf** [PaddlePaddle/Paddle#1283]
之前源码安装很快就搞定了.  这次安装，问题不少
 The Fortran compiler "/usr/bin/g77" is not able to compile a simple test 

是还得升级个 Fortran compiler？

**Comment by gangliao** [comment]
https://github.com/PaddlePaddle/Paddle/blob/develop/doc/getstarted/build_and_install/build_from_source_en.md

**Comment by VamWolf** [comment]
就是按照这个安装的，各种失败.  上面是一个错误. 
之前安装老版本和0.8 的时候，都没有出现这么多问题.

**Comment by gangliao** [comment]
请问你用的是什么系统? 是内部还是外部用户

**Comment by mufasalab** [comment]
希望能出一个内部的更新最新版本的工具，顶！

**Comment by VamWolf** [comment]
内部用用户，开发机. Linux version 2.6.32_1-14-0-0

**Comment by gangliao** [comment]
@VamWolf  @mufasalab  已经搞定，等会更新

**Comment by gangliao** [comment]
@VamWolf @zhangyong15  尝试一下这个 [链接](http://icode.baidu.com/repo/baidu%2Fidl%2Fpaddle_internal_release_tools/files/master/tree/)

**Comment by gangliao** [comment]
#1280

**Comment by VamWolf** [comment]
没权限. 求开新权限.

**Comment by gangliao** [comment]
@VamWolf  icode上面，没有设置权限

**Comment by gangliao** [comment]
Fix #1294

via 

icode: 

baidu/idl/paddle_internal_release_tools

or

baidu/gangliao/paddle_internal_release_tools
