### ISSUE TITLE
There is bug in fluid.InferenceTranspiler for VGG model.

### ISSUE THREAD

**Issue by qingqing01** [PaddlePaddle/Paddle#12840]
去掉BatchNorm里的in-place操作后，单测test_image_classification.py里VGG模型的Batch Norm fuse的单测挂了。

**Comment by panyx0718** [comment]
https://github.com/PaddlePaddle/Paddle/pull/12736/files

**Comment by luotao1** [comment]
close due to `inference_transpiler` is replaced by `PASS`, and would not be maintained later.
