### ISSUE TITLE
Question on fluid.layers.dynamic_lstm

### ISSUE THREAD

**Issue by jczaja** [PaddlePaddle/Paddle#12845]
Hi,

I have question of returned values of fluid.layers.dynamic_lstm. According to : 
http://paddlepaddle.org/documentation/api/en/0.14.0/layers.html#dynamic-lstm

dynamic_lstm does return hidden state as well as **cell state**. My questions are:
1) what is the intention of returning **cell state** by dynamic_lstm?
2)  In what situation it can be useful for a model to have an access to **cell state** when using dynamic_lstm?
3) Can you point me fluid model that is actively(not ignoring) using **cell state**  as returned by dynamic_lstm ?

Best Regards,

**Comment by luotao1** [comment]
Discussed with @qingqing01 : 

> what is the intention of returning cell state by dynamic_lstm

- Desired by the tensorflow API, we return cell state as well.
https://github.com/PaddlePaddle/Paddle/blob/decda738b0bf1dbba5ff4b0b035d2630ab0b7919/benchmark/tensorflow/rnn/rnn.py#L63

- Backward of lstm use `cell` as well.
https://github.com/PaddlePaddle/Paddle/blob/decda738b0bf1dbba5ff4b0b035d2630ab0b7919/paddle/fluid/operators/lstmp_op.h#L240

> 2. In what situation it can be useful for a model to have an access to cell state when using dynamic_lstm? 
> 3. Can you point me fluid model that is actively(not ignoring) using cell state as returned by dynamic_lstm?

There is no fluid model using cell state now.

**Comment by jczaja** [comment]
Thanks @luotao1,

Meantime I found an additional argument after having cell state returned via python interface which is
that if sequence is to long to have it processed at once via dynamic_lstm then it could be split into multiple execution of dynamic_lstm's and returning cell_state as well as providing input c0 will allow this scenario to happen.
