### ISSUE TITLE
the movie rating demo in the site

### ISSUE THREAD

**Issue by pianoman4873** [PaddlePaddle/Paddle#1284]
could you please give more specific details in the algorithm you use ?
Usually in recommendation systems collaborative filtering is used , but you seem to be using a neural network ? Could you give more details about the architecture , is is supervised learning , what's the cost function etc. Thanks, 

Shimon

**Comment by luotao1** [comment]
可以参考 http://book.paddlepaddle.org/recommender_system/ ，我们使用regression_cost。

**Comment by luotao1** [comment]
Too old to close.
