### ISSUE TITLE
本地代码编译后单测报错

### ISSUE THREAD

**Issue by zzhzz** [PaddlePaddle/Paddle#12879]
按照本地代码编译的步骤编译完成。
在build目录下使用指令 `ctest -R test_mul_op`对mul_op进行单元测试得到如下结果：

Test project /Users/baidu/Documents/Paddle/build
    Start 197: test_mul_op
    1/1 Test #197: test_mul_op ......................***Exception: Child aborted  1.24 sec

0% tests passed, 1 tests failed out of 1

Total Test time (real) =   1.27 sec

The following tests FAILED:
	197 - test_mul_op (Child aborted)
Errors while running CTest

请问如何解决？

**Comment by JiayiFeng** [comment]
可以用`ctest -V -R test_mul_op`来看到更详细的报错信息。

对于op的单测，推荐在`Paddle/python/paddle/fluid/tests/unittests`目录下执行： `python -m unittest test_mul_op`。在一些机器上（比如mac），ctest调用python单测可能产生一些问题。
