### ISSUE TITLE
Floating point exception异常

### ISSUE THREAD

**Issue by almostlove** [PaddlePaddle/Paddle#12882]
模型今天增量训练过程中突然出现异常，请教下什么问题
![image](https://user-images.githubusercontent.com/15178274/44504172-e4628080-a6cc-11e8-8aeb-845ae963bb77.png)

**Comment by JiayiFeng** [comment]
这个是训练过程中出现了float point exception。通常可以试着调小学习率，但如果说以往训练没有问题现在突然出现的话，一般是训练数据有问题，可以先尝试在本地跑一下这批数据看能否复现。

**Comment by lucywsq** [comment]
您好，此issue在近一个月内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题， 我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持!
