### ISSUE TITLE
内部上线，依赖库相关问题

### ISSUE THREAD

**Issue by Kevinlsy** [PaddlePaddle/Paddle#12881]
有两个问题
1.想问下，我想用Bcloud云端编译上线，但是在icode上没有找到paddle-capi(cuda 8.0)合适的依赖库，内部icode上有相关的依赖库吗？
2.之前我依赖的是http://icode.baidu.com/repos/baidu/third-party/paddle-capi/tree/paddle-capi-v0.2 
报错：
Check failed: cudaSuccess == err (0 vs. 8) [hl_gpu_apply_unary_op failed] CUDA error: invalid device function
我查看了下这个icode的依赖库paddle支持的是cuda7.5而我的cuda版本8.0，我查看可其他的issues，想确认是不是因为cuda版本不匹配才导致的上面的报错。

**Comment by JiayiFeng** [comment]
你好，能否提供下你的hi用户名？我们hi上直接与您联系

**Comment by Kevinlsy** [comment]
@JiayiFeng 用户名：蒙奇_D_加内特。 谢谢
