### ISSUE TITLE
开发operator时遇到的问题

### ISSUE THREAD

**Issue by zzhzz** [PaddlePaddle/Paddle#12888]
我按照教程完成了operator的前向计算过程，打算通过python接口来完成前向计算的单元测试。但是启动单元测试时得到如下结果：
terminate called after throwing an instance of 'paddle::platform::EnforceNotMet'
  what():  Fail to initialize tree_conv's OpProto, because (cannot determine missing fields for lite message) is not initialized at [/Users/baidu/Documents/Paddle/paddle/fluid/framework/details/op_registry.h:104]
PaddlePaddle Call Stacks: 
0          0x10e964ba2p paddle::platform::EnforceNotMet::EnforceNotMet(std::__exception_ptr::exception_ptr, char const*, int) + 338
1          0x10f263479p paddle::framework::OperatorRegistrar<paddle::operators::TreeConvOp, paddle::operators::TreeConvOpMaker, paddle::framework::DefaultGradOpDescMaker<true> >::OperatorRegistrar(char const*) + 1769
2          0x11367712dp _GLOBAL__sub_I_tree_conv_op.cc + 61
请问这个问题是什么原因造成的呢？

**Comment by velconia** [comment]
请问编译时是否清理了build目录中的cache呢

**Comment by zzhzz** [comment]
清空了

**Comment by JiayiFeng** [comment]
看上去是有op要求的attribute或者input和output没有在python中被正确设置，请检查下是否所有在OpMaker类中定义的东西都在python单测里设置了

**Comment by zzhzz** [comment]
实际上我是刚写完operator，尚未编写python单测。我通过 `python -m unittest test_mul_op`打算验证一下框架单测功能可以使用。那意思是所有operator的单测都需要编写完才可以运行单测吗? @JiayiFeng

**Comment by JiayiFeng** [comment]
那应该因为还没有为op注册反向计算的内容，导致Op的protobuf信息不全报错。反向暂时还没写的话，可以先给它注册一个空的反向计算，例如：
https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/fluid/operators/fill_constant_op.cc#L92
