### ISSUE TITLE
ResNet的GPU和CPU预测结果有差异

### ISSUE THREAD

**Issue by qubingxin** [PaddlePaddle/Paddle#1288]
问题描述：
1. 用GPU集群，训练了一个50层的resnet分类模型，把对应pass的model下载下来，在本地用CPU版进行预测，发现测试集在本地CPU的测试和在GPU集群上log的准确率有差异，相差在10%左右
2. 图片中预处理和预测时都进行了swap
请问是否是ResNet的实现细节中存在某些层的CPU和GPU的不一致？

**Comment by qingqing01** [comment]
参考 https://github.com/PaddlePaddle/Paddle/issues/417 ，请确保集群和本地使用的版本是修正过的。

**Comment by qubingxin** [comment]
@qingqing01  是修正过的，之前跑5层CNN时遇到该问题已修正过。

**Comment by Canpio** [comment]
Close this inactivate issue, please feel free to reopen.
