### ISSUE TITLE
预测器如何加入新的一层（新层使用训练程序的一层参数）

### ISSUE THREAD

**Issue by ws441572091** [PaddlePaddle/Paddle#12880]
训练程序中有一层crf（name=‘crfw’）
预测程序想加入一层crf_decode(name='crfw'),
ValueError: var crfw not in this block

**Comment by JiayiFeng** [comment]
参数共享请使用layer的`param_attr`参数，例如：

```python
crf_decode = layers.crf_decoding(input=hidden, param_attr=ParamAttr(name="crfw"))
```

其中`crfw`是已经存在的参数的名称。在该参数的训练层上也需要用`param_attr`参数用相同的方法来指定名字。

**Comment by ws441572091** [comment]
已经使用了param_attr，但是crfw参数封装在训练program的block里，现在预测程序想新建一个program直接使用crfw，报错crfw不在这个block里，要怎样才能调用呢

**Comment by JiayiFeng** [comment]
解决的方法可能比较hack。

1. 打印一下训练program里的crfw参数，看一下它有哪些参数，各自的值是多少
2. 调用预测program的block 0的create_var接口，创造一个和crfw所有参数完全一致的Variable

这样应该就可以调用了

**Comment by ws441572091** [comment]
好的，请问如何查看crfw参数到各个参数和值呢

**Comment by lucywsq** [comment]
您好，此issue在近一个月内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题，我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持!

**Comment by panda1681** [comment]
@JiayiFeng 

也遇到了类似的问题，RNN+LSTM模型，根据https://github.com/PaddlePaddle/Paddle/issues/17127的提示，在预测的时候去掉含有label的layer，将 crf_cost = fluid.layers.linear_chain_crf( input=emission, label=target,param_attr=fluid.ParamAttr(name='crfw')) 这行代码去掉。只保留crf_decode = layers.crf_decoding(input=hidden, param_attr=ParamAttr(name="crfw"))，报ValueError: var crfw not in this block的错误。加上linear_chain_crf层就没问题，但是这样导致在预测的时候必须构造一个假的label标签作为feed。请问怎么解决这个问题。

**Comment by jianengli** [comment]
> @JiayiFeng
> 
> 也遇到了类似的问题，RNN+LSTM模型，根据[https://github.com/PaddlePaddle/Paddle/issues/17127的提示，在预测的时候去掉含有label的layer，将](https://github.com/PaddlePaddle/Paddle/issues/17127%E7%9A%84%E6%8F%90%E7%A4%BA%EF%BC%8C%E5%9C%A8%E9%A2%84%E6%B5%8B%E7%9A%84%E6%97%B6%E5%80%99%E5%8E%BB%E6%8E%89%E5%90%AB%E6%9C%89label%E7%9A%84layer%EF%BC%8C%E5%B0%86) crf_cost = fluid.layers.linear_chain_crf( input=emission, label=target,param_attr=fluid.ParamAttr(name='crfw')) 这行代码去掉。只保留crf_decode = layers.crf_decoding(input=hidden, param_attr=ParamAttr(name="crfw"))，报ValueError: var crfw not in this block的错误。加上linear_chain_crf层就没问题，但是这样导致在预测的时候必须构造一个假的label标签作为feed。请问怎么解决这个问题。

请问你解决了这个问题吗？
