### ISSUE TITLE
sampling_id op doesn't return id

### ISSUE THREAD

**Issue by zenghsh3** [PaddlePaddle/Paddle#12890]
sampling_id op is returning the value now instead of id, PR #12556 
https://github.com/seiriosPlus/Paddle/blob/822496f6268c70fc53e50a1a15fb7a3f0a3fe49e/paddle/fluid/operators/sampling_id_op.h#L66
the code above should be: 
```c++
ids[i] = ins_vector[idx];
```

**Comment by JiayiFeng** [comment]
Thank you for your feedback! We have informed this op's owner about this issue.

**Comment by TomorrowIsAnOtherDay** [comment]
@seiriosPlus Could you fix it?

**Comment by seiriosPlus** [comment]
I will fix it right now.
