### ISSUE TITLE
LambdaCost计算反向传播导数时公式有误

### ISSUE THREAD

**Issue by fanan** [PaddlePaddle/Paddle#1289]
https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/gserver/layers/CostLayer.cpp#L413

这里的公式是不是写错了?感觉应该是
(std::pow(2,score_i) - std::pow(2,score_j)) * (1/std::log(i+2)-1/std::log(j+2))

**Comment by lutaojian** [comment]
@gongweibao 想问一下这个问题什么时候可以修复？

**Comment by luotao1** [comment]
@lutaojian 因为CostLayer.cpp更新过很多次了，目前的L413行指向的不是这个公式，能再贴下下具体的行数，和对应的代码么？

**Comment by lutaojian** [comment]
https://github.com/PaddlePaddle/Paddle/blob/bb81baa19b311e2d4eb994b8fe4fdfe1d17c9cac/paddle/gserver/layers/CostLayer.cpp#L465
@luotao1 是这行代码里面计算的dcgDif。

https://papers.nips.cc/paper/2971-learning-to-rank-with-nonsmooth-cost-functions.pdf

**Comment by cxysteven** [comment]
看起来是写错了，如果你要急用，改动很小，可以先原代码修改一下。

**Comment by lutaojian** [comment]
@cxysteven 下个正式版本能改好这个bug吗？大概什么时候在正式版修复？

**Comment by cxysteven** [comment]
你好，写layer的同学已经离职，我现在来改一下。

**Comment by cxysteven** [comment]
@lutaojian 你好，现在这个layer的同学已经离职了， 我来改一下。
