### ISSUE TITLE
多分类问题在预测时如何跟label的明文关联上

### ISSUE THREAD

**Issue by wfeagle** [PaddlePaddle/Paddle#12901]
用fluid训练了多分类(比如十类)的模型，输出层softmax应该各个结点有个概率，把top 3 的概率找到后（比如是1，7，9结点），想把这1，7，9 对应的label的明文也找到，请问怎么处理？

**Comment by JiayiFeng** [comment]
label与明文之间的映射规则应该是用户自己预先的就定义好的，训练时候送入模型的label就是已经映射后的0-9数字，预测时候反向映射回去就是了

**Comment by wfeagle** [comment]
主要是不清楚输出格式什么？我把prediction的打印出来，是一个二维数组，然后0维和1维都是label的个数，请问为什么输出会有两维呢？分别代表什么含义呢？我说是下面的val[0]和val[1]都是label个数的维度，这val是pred的一个元素
`pred = exe.run(inference_program,
                feed=utils.data2pred(data, place),
                fetch_list=fetch_targets,
                return_numpy=True)
   for val in pred:
         print(val.ndim)
         print(val[0])
         print(val[0].ndim)
         print(val[0].size)
         print(val[1])
          print(val[1].ndim)
          print(val[1].size)
          break`

**Comment by jacquesqiao** [comment]
0维应该是batch_size 而不是label的个数

**Comment by jacquesqiao** [comment]
而且你可以把预测值打出来，看最大的概率的index，然后就能知道对应的label是什么了

**Comment by wfeagle** [comment]
但是我看你们给的一些models的例子，打印的都是第0维的概率，而第1维的就忽略了，
https://github.com/PaddlePaddle/models/blob/c34bb5f162b7d9b0b61db4632a277095af2e64b8/fluid/text_classification/clouds/scdb_parallel_executor.py  第367行

刚刚上面那个问题，我没有说清楚，我说是下面的val[0]和val[1]都是label个数的维度，val是pred的一个元素
我是想说我该取val[0]还是val[1]呢？？
pred = exe.run(inference_program, feed=utils.data2pred(data, place), fetch_list=fetch_targets, return_numpy=True) 
for val in pred: 
      print(val.ndim) 
      print(val[0]) 
      print(val[0].ndim) 
      print(val[0].size)  //label个数
      print(val[1]) 
      print(val[1].ndim) 
      print(val[1].size)  //label个数
 break
