### ISSUE TITLE
关于last-column-auc Evaluator 部分情形下受限

### ISSUE THREAD

**Issue by hiahiahu** [PaddlePaddle/Paddle#1291]
似乎这个auc专门为softmax-classification设计的？实际情况中以下两种情况都没法直接用：
1、做回归训练，验证集的label其实是denseSlot,没法直接用(预测、训练分别设置slot可绕过)
2、predict是负数的时候这个不能用(可以通过额外加一层 无bias,identity(input)的mixlayer绕过)

是否可以拓展成真正的last-column-auc，业务方同学一不小心就踩坑了。。。。

**Comment by typhoonzero** [comment]
related: https://github.com/PaddlePaddle/Paddle/issues/5124
