### ISSUE TITLE
fluid.Trainer api下如何获取到指定名字的参数

### ISSUE THREAD

**Issue by leochen86** [PaddlePaddle/Paddle#12919]
<img width="571" alt="639f932bac2eaf9e54232d6a9c11292d" src="https://user-images.githubusercontent.com/34496954/44572900-c6257f00-a7b7-11e8-9ee7-ac2189f93a5d.png">
<img width="566" alt="68e2e98b7484c09e9ac31c56aaacc49b" src="https://user-images.githubusercontent.com/34496954/44572907-caea3300-a7b7-11e8-941c-0d7c60b5ffa7.png">
<img width="326" alt="6728a87df476e46c928a44f8c59ee455" src="https://user-images.githubusercontent.com/34496954/44572915-cde52380-a7b7-11e8-848c-d1ed7b17f522.png">

**Comment by leochen86** [comment]
<img width="357" alt="cf4121a295c71f58dc4019203ce86faa" src="https://user-images.githubusercontent.com/34496954/44572992-04bb3980-a7b8-11e8-9575-fe67b87a5e2f.png">
<img width="466" alt="0b50bbe6b679bfa87b9d80f89b7fea16" src="https://user-images.githubusercontent.com/34496954/44572998-07b62a00-a7b8-11e8-891e-a2df703aa73d.png">

**Comment by jacquesqiao** [comment]
在event_handle里面，参考：
https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/fluid/tests/unittests/test_sgd_op.py#L58
```
param = scope.var('Param').get_tensor()
result_array = np.array(param)
```
可以把参数拿出来

**Comment by leochen86** [comment]
你好，按照说明，放入代码后，运行报异常，按照之前的经验应该是参数格式错误，请问正确的传参格式应该是怎样的？
<img width="494" alt="78a7b4dab5a8ea2d9c7a5471bbc25418" src="https://user-images.githubusercontent.com/34496954/44573584-9a0afd80-a7b9-11e8-9f73-7f5c5aaea843.png">
<img width="755" alt="af565f3d3a2c973aae89894aca6a324b" src="https://user-images.githubusercontent.com/34496954/44573588-9d9e8480-a7b9-11e8-8096-316f90b22bf4.png">

**Comment by leochen86** [comment]
我代码是这样写的，是不是哪里不对
<img width="639" alt="29a6fdc0a7402eca78f7dc4ac841851a" src="https://user-images.githubusercontent.com/34496954/44573930-8b711600-a7ba-11e8-8e2a-5284ab610c22.png">

**Comment by jacquesqiao** [comment]
fluid.global_scope().find_var()

**Comment by leochen86** [comment]
你好，最后使用trainer.scope.find_var()成功拿到参数了，如图网络结构，最后参数的确应该时6个，但是最后在使用visualdl add_record时报了运行时错误
<img width="740" alt="eec110a235ce6843fdfacc4064401dcc" src="https://user-images.githubusercontent.com/34496954/44574652-99c03180-a7bc-11e8-980b-cc758054c3c9.png">
<img width="747" alt="424582c4c60f27d8bb60c08ea6794866" src="https://user-images.githubusercontent.com/34496954/44574656-9d53b880-a7bc-11e8-9d0a-17d077db5ee5.png">

**Comment by leochen86** [comment]
<img width="392" alt="d24314ded64019229dffdac98f7b71dc" src="https://user-images.githubusercontent.com/34496954/44574708-bf4d3b00-a7bc-11e8-9605-5c12e89d3274.png">

**Comment by leochen86** [comment]
我知道了，histogram("param1",6)就可以了，需要和参数数量一致
