### ISSUE TITLE
本地训练好的模型，集群如何使用呢？

### ISSUE THREAD

**Issue by wfeagle** [PaddlePaddle/Paddle#12915]
用fluid训练好一个多分类模型，然后大数据需要放到集群队列预测使用，该怎么操作呢？ 
如果要放到线上使用的话，有什么API吗？

**Comment by jacquesqiao** [comment]
http://paddlepaddle.org/documentation/docs/zh/0.14.0/new_docs/user_guides/howto/inference/index.html 部署相关的文档

**Comment by wfeagle** [comment]
还有一个疑问，如果放到集群使用的话，含有paddle的python包该怎么打包上传呢？
