### ISSUE TITLE
fluid.io.save_params时出错

### ISSUE THREAD

**Issue by kolinwei** [PaddlePaddle/Paddle#12911]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/work/weike/svn/baidu/paddle/test/cts_test/test_mnist_train_bak.py", line 146, in test_train_mnist_simple_fc_multi_gpu
    train_info1 = check_network()
  File "/work/weike/svn/baidu/paddle/test/cts_test/test_mnist_train_bak.py", line 108, in check_network
    fluid.io.save_params(executor=exe, dirname="./test", main_program=main)
  File "/usr/local/lib/python2.7/dist-packages/paddle/fluid/io.py", line 249, in save_params
    filename=filename)
  File "/usr/local/lib/python2.7/dist-packages/paddle/fluid/io.py", line 170, in save_vars
    filename=filename)
  File "/usr/local/lib/python2.7/dist-packages/paddle/fluid/io.py", line 201, in save_vars
    executor.run(save_program)
  File "/usr/local/lib/python2.7/dist-packages/paddle/fluid/parallel_executor.py", line 276, in run
    self.executor.run(fetch_list, fetch_var_name)
TypeError: run(): incompatible function arguments. The following argument types are supported:
    1. (self: paddle.fluid.core.ParallelExecutor, arg0: List[unicode], arg1: unicode) -> None

**Comment by jacquesqiao** [comment]
看起来是函数的参数填错了

**Comment by kolinwei** [comment]
import os
import numpy as np
import time
import sys
import paddle
import paddle.fluid as fluid
from nose import tools


def cnn_model(data, is_simple = False):
    """
    返回模型,is_simple为True时，只返回全连接层的模型
    """
    conv_pool_1 = fluid.nets.simple_img_conv_pool(
        input=data,
        filter_size=5,
        num_filters=20,
        pool_size=2,
        pool_stride=2,
        act="relu")
    conv_pool_2 = fluid.nets.simple_img_conv_pool(
        input=conv_pool_1,
        filter_size=5,
        num_filters=50,
        pool_size=2,
        pool_stride=2,
        act="relu")

    SIZE = 10
    input_shape = conv_pool_2.shape
    param_shape = [reduce(lambda a, b: a * b, input_shape[1:], 1)] + [SIZE]
    scale = (2.0 / (param_shape[0]**2 * SIZE))**0.5

    predict = fluid.layers.fc(
        input=data if is_simple else conv_pool_2,
        size=SIZE,
        act="softmax",
        param_attr=fluid.param_attr.ParamAttr(
            initializer=fluid.initializer.NormalInitializer(
                loc=0.0, scale=scale)))
    return predict


def check_network(net_type=True, use_gpu=True,
                batch_size=32,
                batch_num=5,
                image_shape='1,28,28',
                use_parallel_executor=True,
                use_reduce=False):
    """
    执行部分函数
    """
    main = fluid.Program()
    startup = fluid.Program()
    startup.random_seed = 1
    main.random_seed = 1
    with fluid.program_guard(main, startup):
        image_shape = [int(m) for m in image_shape.split(",")]
        image = fluid.layers.data(name='image', shape=image_shape, dtype='float32')
        label = fluid.layers.data(name='label', shape=[1], dtype='int64')
        predict = cnn_model(image, net_type)
        cost = fluid.layers.cross_entropy(input=predict, label=label)
        avg_cost = fluid.layers.mean(x=cost)
        opt = fluid.optimizer.AdamOptimizer(
            learning_rate=0.001, beta1=0.9, beta2=0.999)
        opt.minimize(avg_cost)
        place = fluid.CUDAPlace(0) if use_gpu else fluid.CPUPlace()
        startup_exe = fluid.Executor(place)
        startup_exe.run(startup)
        build_strategy = fluid.BuildStrategy()
        build_strategy.reduce_strategy = fluid.BuildStrategy.ReduceStrategy.Reduce \
            if use_reduce else fluid.BuildStrategy.ReduceStrategy.AllReduce
        if use_parallel_executor:
            exe = fluid.ParallelExecutor(
                    use_cuda=use_gpu,
                    loss_name = avg_cost.name,
                    build_strategy=build_strategy)
        else:
            exe = fluid.Executor(place=place)
        train_reader = paddle.batch(paddle.dataset.mnist.test(), batch_size=batch_size)
        feeder = fluid.DataFeeder(place=place, feed_list=[image, label])
        fetch_list = [avg_cost.name]
        train_info = []
        for batch_id, data in enumerate(train_reader()):
            loss,  = exe.run(
                            fetch_list = fetch_list,
                            feed = feeder.feed(data))
            #print loss
            loss = np.mean(np.array(loss))
            train_info.append(loss)
            if batch_id == batch_num:
                break
        fluid.io.save_params(executor=startup_exe, dirname="./test", main_program=main)
        return train_info


class TestMnistTrain():
    """
    mnist model train
    """
    def __init__(self):
        self.batch_size = 32
        self.use_gpu = True
        self.image_shape = "1,28,28"
        self.model_name = 'mnist'
        self.num_epochs = 5

    def test_train_mnist_simple_fc_multi_gpu(self):
        """
        验证简化模型下，多GPU训练
        """
        train_info1 = check_network()

**Comment by kolinwei** [comment]
```python
main = fluid.Program()
    startup = fluid.Program()
    startup.random_seed = 1
    main.random_seed = 1
    with fluid.program_guard(main, startup):
        image_shape = [int(m) for m in image_shape.split(",")]
        image = fluid.layers.data(name='image', shape=image_shape, dtype='float32')
        label = fluid.layers.data(name='label', shape=[1], dtype='int64')
        predict = cnn_model(image, net_type)
        cost = fluid.layers.cross_entropy(input=predict, label=label)
        avg_cost = fluid.layers.mean(x=cost)
        opt = fluid.optimizer.AdamOptimizer(
            learning_rate=0.001, beta1=0.9, beta2=0.999)
        opt.minimize(avg_cost)
        place = fluid.CUDAPlace(0) if use_gpu else fluid.CPUPlace()
        startup_exe = fluid.Executor(place)
        startup_exe.run(startup)
        build_strategy = fluid.BuildStrategy()
        build_strategy.reduce_strategy = fluid.BuildStrategy.ReduceStrategy.Reduce \
            if use_reduce else fluid.BuildStrategy.ReduceStrategy.AllReduce
        if use_parallel_executor:
            exe = fluid.ParallelExecutor(
                    use_cuda=use_gpu,
                    loss_name = avg_cost.name,
                    build_strategy=build_strategy)
        else:
            exe = fluid.Executor(place=place)
        train_reader = paddle.batch(paddle.dataset.mnist.test(), batch_size=batch_size)
        feeder = fluid.DataFeeder(place=place, feed_list=[image, label])
        fetch_list = [avg_cost.name]
        train_info = []
        for batch_id, data in enumerate(train_reader()):
            loss,  = exe.run(
                            fetch_list = fetch_list,
                            feed = feeder.feed(data))
            #print loss
            loss = np.mean(np.array(loss))
            train_info.append(loss)
            if batch_id == batch_num:
                break
        fluid.io.save_params(executor=exe, dirname="./test", main_program=main)
```

**Comment by kolinwei** [comment]
代码片段如上，请帮看下

**Comment by velconia** [comment]
辛苦提供下更全面的 Traceback, python 的 Traceback 下面应该还有一句比较关键的语句

**Comment by velconia** [comment]
```
fluid.io.save_params(executor=exe, dirname="./test", main_program=main)
```
我看了下, 和python3无关, 你传入的exe是ParallelExecutor, save_params不支持ParallelExecutor, 只支持 Executor, 可以参考方法的 doc: 

```
 Args:                                                                                                                                                 
         executor(Executor): The executor to run for saving parameters.
```
