### ISSUE TITLE
预测问题

### ISSUE THREAD

**Issue by 1145520074** [PaddlePaddle/Paddle#1292]
我在使用minst Demo进行预测时，出现了这样的情况，请问是怎么回事
![90935dcf1171a2f2185de34b6](https://cloud.githubusercontent.com/assets/12948853/22728354/61b2456c-ee18-11e6-8bfb-e883acf5d688.png)
另外，我想问一下，在GPU机器上训练好模型后，如何发布到别的CPU机器上进行预测？

**Comment by luotao1** [comment]
请问是在book/recognize_digits还是paddle/demo/mnist呢？

**Comment by 1145520074** [comment]
是在paddle/demo/mnist

**Comment by luotao1** [comment]
按如下修改predict.py文件：
![image](https://cloud.githubusercontent.com/assets/6836917/22730434/f27bf6c0-ee21-11e6-8263-61026852319a.png)
即把./data/raw_data/ 改成 DATA

**Comment by 1145520074** [comment]
这样改没用啊，改注释怎么会有用呢？

**Comment by dayhaha** [comment]
有用的，这个是python docopt的注释，就是从注释里面获取参数。

**Comment by 1145520074** [comment]
我改了后还是一样的呢？
[tuku@bjyz-tuku-gpu1.bjyz.baidu.com mnist]$ python predict.py -c vgg_16_mnist.py -d ./data/raw_data/ -m mnist_vgg_model/pass-00037
Usage: predict.py -c CONF -d DATA  -m MODEL
Arguments:
    CONF        train conf
    DATA        MNIST Data
    MODEL       Model
Options:
    -h      --help
    -c      conf
    -d      data
    -m      model

**Comment by luotao1** [comment]
能否贴一下predict.py的代码，最新paddle下面已经没有这个文件了

**Comment by 1145520074** [comment]
好的
"""
Usage: predict.py -c CONF -d DATA  -m MODEL
Arguments:
    CONF        train conf
    DATA        MNIST Data
    MODEL       Model
Options:
    -h      --help
    -c      conf
    -d      data
    -m      model
"""

import os
import sys
from docopt import docopt
#import matplotlib.pyplot as plt
import numpy as np

from py_paddle import swig_paddle, DataProviderConverter
from paddle.trainer.PyDataProvider2 import dense_vector
from paddle.trainer.config_parser import parse_config

from load_data import read_data


class Prediction():
    def __init__(self, train_conf, data_dir, model_dir):

        conf = parse_config(train_conf, 'is_predict=1')
        self.network = swig_paddle.GradientMachine.createFromConfigProto(
            conf.model_config)
        self.network.loadParameters(model_dir)

        self.images, self.labels = read_data(data_dir, "t10k")

        slots = [dense_vector(28 * 28)]
        self.converter = DataProviderConverter(slots)

    def predict(self, index):
        input = self.converter([[self.images[index].flatten().tolist()]])
        output = self.network.forwardTest(input)
        prob = output[0]["value"]
        predict = np.argsort(-prob)
        print "Predicted probability of each digit:"
        print prob
        print "Predict Number: %d" % predict[0][0]
        print "Actual Number: %d" % self.labels[index]


def main():
    print "hh"
    arguments = docopt(__doc__)
    train_conf = arguments['CONF']
    data_dir = arguments['DATA']
    print data_dir
    model_dir = arguments['MODEL']
    swig_paddle.initPaddle("--use_gpu=0")
    predictor = Prediction(train_conf, data_dir, model_dir)
    while True:
        index = int(raw_input("Input image_id [0~9999]: "))
        predictor.predict(index)


if __name__ == '__main__':
    main()

**Comment by luotao1** [comment]
你的错误信息是 #1293 中列出来的呢？还是下面的
```
Usage: predict.py -c CONF -d DATA -m MODEL
Arguments:
CONF train conf
DATA MNIST Data
MODEL Model
Options:
-h --help
-c conf
-d data
-m model
```

**Comment by 1145520074** [comment]
两个是不一样的问题，这里我吧matplot屏蔽了，但是还是出错了，预测时只打印了下面的信息，没有预测
Usage: predict.py -c CONF -d DATA -m MODEL
Arguments:
CONF train conf
DATA MNIST Data
MODEL Model
Options:
-h --help
-c conf
-d data
-m model

**Comment by luotao1** [comment]
我看代码里加了打印信息“print "hh"和“print data_dir”，没有打印出么？

**Comment by dayhaha** [comment]
明白了，还是docopt格式的问题。
你把
Usage: predict.py -c CONF -d DATA -m MODEL
Arguments:
CONF train conf
DATA MNIST Data
MODEL Model
Options:
-h --help
-c conf
-d data
-m model
改成
"""Usage: predict.py -c CONF -d DATA -m MODEL

 Arguments:
     CONF        train conf
     DATA        MNIST Data
     MODEL       Model

 Options:
     -h      --help
     -c      conf
     -d      data
     -m      model
 """
中间空行试一下呢？  我刚刚试了，中间不空行不行。

**Comment by 1145520074** [comment]
嗯，是的，大神啊。真的可以了。
但是出了新的问题，不管我输入数字是多少，Predict Number都是9,而Actual Number会变。
然后就是怎么把训练好的模型移植到普通的CPU机器上跑呢

**Comment by dayhaha** [comment]
@@ -46,6 +46,7 @@ class Prediction():
         self.network.loadParameters(model_dir)

         self.images, self.labels = read_data(data_dir, "t10k")
+        self.images = self.images / 255.0 * 2.0 - 1.0  # normalized to [-1,1]

         slots = [dense_vector(28 * 28)]
         self.converter = DataProviderConverter(slots)


对于Predict Number不会变的问题，抱歉，这地方少了一个归一的步骤  self.images = self.images / 255.0 * 2.0 - 1.0  # normalized to [-1,1]
加上去之后预测就是正常的了。

GPU训练好的模型，直接放在CPU上面，这个api应该默认就是用CPU进行预测的？ @luotao1

**Comment by 1145520074** [comment]
class Prediction():
    def __init__(self, train_conf, data_dir, model_dir):

        conf = parse_config(train_conf, 'is_predict=1')
        self.network = swig_paddle.GradientMachine.createFromConfigProto(
            conf.model_config)
        self.network.loadParameters(model_dir)

        self.images, self.labels = read_data(data_dir, "t10k")
        self.images = self.images / 255.0 * 2.0 - 1.0 # normalized to [-1,1]
        slots = [dense_vector(28 * 28)]
        self.converter = DataProviderConverter(slots)
这样改了后，预测结果依然是9，不变。

GPU训练好的模型，直接放在CPU上面，这个api应该默认就是用CPU进行预测的
我的意识是拿到别的机器上跑，需要加上哪些依赖？

**Comment by luotao1** [comment]
默认是cpu，main函数里的这行代码写了。如果要用gpu，就把0改成1。
```
swig_paddle.initPaddle("--use_gpu=0")
```

**Comment by 1145520074** [comment]
class Prediction():
def init(self, train_conf, data_dir, model_dir):

    conf = parse_config(train_conf, 'is_predict=1')
    self.network = swig_paddle.GradientMachine.createFromConfigProto(
        conf.model_config)
    self.network.loadParameters(model_dir)

    self.images, self.labels = read_data(data_dir, "t10k")
    self.images = self.images / 255.0 * 2.0 - 1.0 # normalized to [-1,1]
    slots = [dense_vector(28 * 28)]
    self.converter = DataProviderConverter(slots)

这样改了后，预测结果依然是9，不变。

GPU训练好的模型，拿到别的机器上跑，需要加上哪些依赖？
@luotao1  @dayhaha

**Comment by dayhaha** [comment]
我在CPU上训练和预测没有问题，这个问题可能是在GPU上训练然后再CPU上预测出现的问题。
好像之前有一些issue有类似的问题 #1288  #417  #379。  这个问题好像是在develop上面修复了。
你用的是什么版本的paddle呢？

具体的可能得由 @luotao1 来解答。

**Comment by luotao1** [comment]
@dayhaha 这个问题已经在develop分支上面修复了。 @1145520074 请问您是用什么版本的paddle，可以试下develop分支。

**Comment by 1145520074** [comment]
怎么看分支呢？
@luotao1

**Comment by 1145520074** [comment]
嗯，试了下develop版本的，图像分类没有问题，多谢
