### ISSUE TITLE
如何使用numpy数组对Variable赋值？

### ISSUE THREAD

**Issue by molly00ecla** [PaddlePaddle/Paddle#12930]
您好
我使用fluid构造了一个网络模型，如：
conv1 = fluid.layers.conv2d(X, 64, 9,act='relu', name='conv1' , 
                                param_attr= fluid.ParamAttr(name='conv1_w'))
然后获取variable:
conv1_w = fluid.get_var('conv1_w')
我希望使用numpy数组对这个参数进行赋值，要如何做呢？

我查到资料说，可以使用 paddle.parameters.Parameters.set 进行赋值。但是我使用fluid.get_var获取到的对象不是paddle.parameters.Parameters类型的，没有set方法……

多谢！

**Comment by jacquesqiao** [comment]
请参考
https://github.com/PaddlePaddle/Paddle/blob/038e2817f0208f8de3761854700ff01fc5c28362/python/paddle/fluid/tests/book/test_label_semantic_roles.py#L178-L182
