### ISSUE TITLE
paddle源码编译遇到问题

### ISSUE THREAD

**Issue by leanna62** [PaddlePaddle/Paddle#1294]
内部用户，使用提供的build.sh进行编译，提示
fatal error: TrainerConfig.pb.h: No such file or directory，编译失败，下载的是最新的开发分支，请问是什么问题呢

**Comment by gangliao** [comment]
你好，之前维护的一键编译并不支持Paddle的最新代码，可以考虑使用最新的一键编译脚本编译Paddle最新代码.
@leanna62 
脚本在icode上面, 具体地址请参考 #1283

**Comment by leanna62** [comment]
用的就是icode上面的这个脚本，编译的github上的最新分支出现的这个问题 @gangliao

**Comment by gangliao** [comment]
@leanna62  你提供的信息好少，重新 rm -rf Paddle, 重新 sh build.sh试一试， 请贴一下错误详情。

**Comment by leanna62** [comment]
好的，详细信息如下：
`make[2]: *** [paddle/function/CMakeFiles/paddle_function.dir/ContextProjectionOp.cpp.o] Error 1
In file included from /home/work/paddle_new/paddle_internal_release_tools/idl/paddle/Paddle/paddle/utils/ThreadLocal.h:25:0,
                 from /home/work/paddle_new/paddle_internal_release_tools/idl/paddle/Paddle/paddle/math/Matrix.h:22,
                 from /home/work/paddle_new/paddle_internal_release_tools/idl/paddle/Paddle/paddle/function/TensorType.h:17,
                 from /home/work/paddle_new/paddle_internal_release_tools/idl/paddle/Paddle/paddle/function/BufferArg.h:20,
                 from /home/work/paddle_new/paddle_internal_release_tools/idl/paddle/Paddle/paddle/function/Function.h:19,
                 from /home/work/paddle_new/paddle_internal_release_tools/idl/paddle/Paddle/paddle/function/CrossMapNormalOp.h:17,
                 from /home/work/paddle_new/paddle_internal_release_tools/idl/paddle/Paddle/paddle/function/CrossMapNormalOp.cpp:15:
/home/work/paddle_new/paddle_internal_release_tools/idl/paddle/Paddle/paddle/utils/Util.h:31:30: fatal error: TrainerConfig.pb.h: No such file or directory
 #include "TrainerConfig.pb.h"
                              ^
compilation terminated.
make[2]: *** [paddle/function/CMakeFiles/paddle_function.dir/CrossMapNormalOp.cpp.o] Error 1
In file included from /home/work/paddle_new/paddle_internal_release_tools/idl/paddle/Paddle/paddle/utils/ThreadLocal.h:25:0,
                 from /home/work/paddle_new/paddle_internal_release_tools/idl/paddle/Paddle/paddle/math/Matrix.h:22,
                 from /home/work/paddle_new/paddle_internal_release_tools/idl/paddle/Paddle/paddle/function/TensorType.h:17,
                 from /home/work/paddle_new/paddle_internal_release_tools/idl/paddle/Paddle/paddle/function/BufferArg.h:20,
                 from /home/work/paddle_new/paddle_internal_release_tools/idl/paddle/Paddle/paddle/function/Function.h:19,
                 from /home/work/paddle_new/paddle_internal_release_tools/idl/paddle/Paddle/paddle/function/Function.cpp:15:
/home/work/paddle_new/paddle_internal_release_tools/idl/paddle/Paddle/paddle/utils/Util.h:31:30: fatal error: TrainerConfig.pb.h: No such file or directory
 #include "TrainerConfig.pb.h"
                              ^
compilation terminated.
make[2]: *** [paddle/function/CMakeFiles/paddle_function.dir/Function.cpp.o] Error 1
make[1]: *** [paddle/function/CMakeFiles/paddle_function.dir/all] Error 2`

**Comment by gangliao** [comment]
能否hi下我

**Comment by leanna62** [comment]
好的

**Comment by leanna62** [comment]
感谢 @gangliao  提供最新的工具，已经解决编译问题了～
