### ISSUE TITLE
简易集群模式下，是否支持多个cluster job并行？

### ISSUE THREAD

**Issue by sarawon** [PaddlePaddle/Paddle#1295]
利用cluster_train下面提供的脚本进行多级训练，是否支持多个cluster job并行？测试发现每次启动一个新的cluster job,会有一个Kill操作，把现有的paddle_process都kill掉

**Comment by reyoung** [comment]
如果是[这里的代码](https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/scripts/cluster_train/paddle.py#L191)的话，可能确实有这个bug。我会近期看一下。

不过我们应该会提供基于kubernetes的集群调度模式，可以参考[这里](https://github.com/PaddlePaddle/Paddle/tree/develop/doc/howto/usage/k8s)

那个简易方法使用的是fabric，fabric本质上就是ssh封装，所以，其实也可以直接登录到那个机器上启动paddle训练。

**Comment by sarawon** [comment]
好的，理论上是应该支持多个不同的cluster job并行在跑的是吧？kubernetes支持吗？直接登录到机器启动的方法是指ssh到每台机器启动具体的pserver和train进程吗？

**Comment by jacquesqiao** [comment]
kubernetes can support multi cluster job, this issue is two old to debug, close it , feel free to reopened it if needed.
