### ISSUE TITLE
Timing模块和RDMA模块 使用文档支持求助

### ISSUE THREAD

**Issue by dingjie1234** [PaddlePaddle/Paddle#1296]
在编译paddle时加了with timing 和 with RDMA选项，但是不太清楚这两个参数具体怎么控制，请问有相关的使用文档吗？

**Comment by gangliao** [comment]
@dingjie1234  Timing 模块这里有介绍 https://github.com/PaddlePaddle/Paddle/blob/develop/doc/howto/optimization/gpu_profiling_cn.rst

RDMA模块 目前应该没有介绍 @reyoung

**Comment by Xreki** [comment]
暂时关闭，如有需要再重新打开。
