### ISSUE TITLE
跑gpu版本的时候，提示 Check failed

### ISSUE THREAD

**Issue by xianming90** [PaddlePaddle/Paddle#12965]
Check failed: (cudnn_cuh_major < 4 && cudnn_dso_major < 4) || (cudnn_cuh_major == cudnn_dso_major) [cudnn init] libcudnn v5 with header v7 unmatched!
PaddlePaddle Requirement: (header v[2-3] with libcudnn v[2-3]) Or (header v4 with libcudnn v4) Or (header v5 with libcudnn v5) Or(header v6 with libcudnn v6).

**Comment by seiriosPlus** [comment]
PaddlePaddle要求的CUDNN版本和你宿主机环境的CUDNN版本不一致

**Comment by lucywsq** [comment]
您好，此issue在近一个月内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题， 我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持!
