### ISSUE TITLE
v2 capi模型前传api调用时间有跳变

### ISSUE THREAD

**Issue by lpx1233** [PaddlePaddle/Paddle#12975]
厂内线上c++模块接入paddle模型的时候, 模型前传api调用时间跳变, 请问有优化方法吗? 
现在接入后模型前传api (paddle_gradient_machine_forward) 一般值在0.3ms, 偶尔会跳2,30ms甚至100ms, 非常影响性能
用的v2的c-api (非fluid), 模型也比较简单, embedding + seq_conv + fc

**Comment by luotao1** [comment]
> 模型前传api调用时间

请问是单纯的预测时间，还是包括初始化时间呢？独占机器么？

**Comment by lpx1233** [comment]
> 请问是单纯的预测时间，还是包括初始化时间呢？独占机器么？

是单纯的预测时间, 单纯调用一条paddle_gradient_machine_forward所占用的时间, 是独占机器

**Comment by luotao1** [comment]
- 请问是CPU预测（MKL还是OpenBlas）还是GPU预测？
- 请问和样本有关系么，某些样本特别耗时？看配置应该是序列模型，是不是有些样本特别长，导致预测时间暴增。

**Comment by lpx1233** [comment]
> 请问是CPU预测（MKL还是OpenBlas）还是GPU预测？

CPU预测, 用的mkl版本

> 请问和样本有关系么，某些样本特别耗时？看配置应该是序列模型，是不是有些样本特别长，导致预测时间暴增。

据我测试与样本长度无关, 经常出现同一长度样本预测时间相差100倍(0.3ms vs 30ms)的情况

**Comment by luotao1** [comment]
可以试试`export MKL_NUM_THRADS=1`

**Comment by lpx1233** [comment]
`export MKL_NUM_THREADS=1`之后就正常了, 预测时间不再有跳变
谢谢同学, 辛苦解答了~
