### ISSUE TITLE
载入模型后，在预测过程中，打印出指定层的结果。

### ISSUE THREAD

**Issue by Renwb1991** [PaddlePaddle/Paddle#12986]
使用 fluid.io.load_inference_model 方法对文件 model 和 params 载入模型时，获得的 program 是否已经确定了需要输出的 fetch_list ？ 我看见了[executor.py](https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/fluid/evaluator.py)中的 has_fetch_operators 方法， 这里已经指出了每层 op 的desc.type() 了。

我们的需求是：使用 fluid.io.load_inference_model 方法对文件 model 和 params 载入模型后，打印出指定层的结果。

**Comment by seiriosPlus** [comment]
var = np.array(fluid.global_scope().find_var('map_eval_0_1_accum_true_pos').get_tensor())

**Comment by Renwb1991** [comment]
map_eval_0_1_accum_true_pos 指定是我希望打印的层？

**Comment by seiriosPlus** [comment]
指定你希望打印出来的变量。
如：
```
q_fc = fluid.layers.fc(input=q_ss,
    size=hid_dim,
    param_attr=fluid.ParamAttr(name="__q_fc__", learning_rate=base_lr))
```

可以打印__q_fc__.

**Comment by Renwb1991** [comment]
模型是别人给定的，我们只是进行 infer，并拿到指定层的中间结果。
使用 ```var = np.array(fluid.global_scope().find_var('map_eval_0_1_accum_true_pos').get_tensor())``` 的过程中， ```fluid.global_scope().find_var('XXX')``` 返回的类型可能为````None``.

现在遇到的问题好像是：
1. 对参数层是 ```fluid.global_scope().find_var('XXX')``` 都返回 ```Variable```,   能够打印。例如: 
 -  ```resnet_v1_50_block1_unit_1_bottleneck_v1_shortcut_BatchNorm_FusedBatchNorm_variance```
 -  ```resnet_v1_50_block1_unit_1_bottleneck_v1_shortcut_BatchNorm_FusedBatchNorm_variance```.
2. 对中间结果层是 ```fluid.global_scope().find_var('XXX')``` 都返回 ``None```,   不能够打印。例如: 
 - ```resnet_v1_50_block1_unit_2_bottleneck_v1_conv3_BatchNorm_FusedBatchNorm.batch_norm.output.1.tmp_0``` 
 - ```resnet_v1_50_block2_unit_2_bottleneck_v1_conv1_BatchNorm_FusedBatchNorm.batch_norm.output.1.tmp_0```

**Comment by Renwb1991** [comment]
重新说下需求，**在保存完一份模型后（包含参数和graph结构），期望能够：**
1. 在预测的过程中，能够输出最终的结果。
2. 在预测的过程中，能够输出指定层（可以不在 fetch_list 中）的中间结果。
3. 能够将参数载入到模型中，从而进行 finetuning 训练。**[非必需，做到做好]**

**Comment by lucywsq** [comment]
您好，感谢您的建议，鉴于此issue在近一个月内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题，我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持!

**Comment by NHZlX** [comment]
为模型添加新的fetch list
```
import paddle.fluid as fluid
#from infer_model4 import net
import numpy as np

exe = fluid.Executor(fluid.CPUPlace())

tensor_img = np.zeros([1, 21, 108, 108], dtype=np.float32)
tensor_img[0, 0, 0, 0] = 1.0

[inference_program, feed_target_names, fetch_targets] = \
    fluid.io.load_inference_model(dirname='./test_model', executor=exe, model_filename='model', params_filename='params')


print fetch_targets
with fluid.program_guard(inference_program):
    block0 = inference_program.blocks[0]

    all_vars = block0.vars
    fetch_targets.append(all_vars['concat.concat.output.1.tmp_0'])
    fluid.io.save_inference_model(
                    'test1', feed_target_names,
                    fetch_targets,
                    exe,
                    main_program=None,
                    model_filename="model",
                    params_filename="params")

```

预测：
```
import paddle.fluid as fluid
import numpy as np

exe = fluid.Executor(fluid.CPUPlace())

tensor_img = np.zeros([1, 21, 108, 108], dtype=np.float32)
tensor_img[0, 0, 0, 0] = 1.0

[inference_program, feed_target_names, fetch_targets] = \
    fluid.io.load_inference_model(dirname='./test1', executor=exe, model_filename='model', params_filename='params')


results = exe.run(inference_program,
                        feed={feed_target_names[0]: tensor_img},
                                            fetch_list=fetch_targets)

print results[1]

```

**Comment by christianahui** [comment]
您好，@NHZlX ，我按照上面这种方法，想打印中间层的输出，但是报错，请问是什么问题？
`     place = fluid.CUDAPlace(0) if use_cuda else fluid.CPUPlace()

      exe = fluid.Executor(place)  
      inference_scope = fluid.core.Scope()
      with fluid.scope_guard(inference_scope):
          [inference_program, feed_target_names,
           fetch_targets] = fluid.io.load_inference_model(model_path, exe)
          print fetch_targets
          with fluid.program_guard(inference_program):
              block0 = inference_program.blocks[0]
              all_vars = block0.vars
              fetch_targets.append(all_vars['matmul_2.tmp_0'])
              fluid.io.save_inference_model(
                      'test1', feed_target_names,
                      fetch_targets,
                      exe)
`
预测：

`     place = fluid.CUDAPlace(0) if use_cuda else fluid.CPUPlace()

      exe = fluid.Executor(place)
      inference_scope = fluid.core.Scope()
      with fluid.scope_guard(inference_scope):
          [inference_program, feed_target_names,
           fetch_targets] = fluid.io.load_inference_model(model_path, exe)
          print fetch_targets
          print feed_target_names

         for data in test_reader():
             cost1,acc,prediction, content_attention_weight, sent_attention_weight = exe.run(inference_program,
                           feed=utils_bak.data2tensor(data, place),
                           fetch_list=fetch_targets,
                           return_numpy=False)
`
报错说：
```
` Traceback (most recent call last):

  File "infer_vis2.py", line 114, in <module>
    infer(test_reader, word_reverse_dict, use_cuda=False, model_path=epoch_path)
  File "infer_vis2.py", line 48, in infer
    return_numpy=False)
  File "/home/spider/xingzhihui/book/08.machine_translation/paddle_release_home/python/lib/python2.7/site-packages/paddle/fluid/executor.py", line 467, in run
    fetch_var_name=fetch_var_name)
  File "/home/spider/xingzhihui/book/08.machine_translation/paddle_release_home/python/lib/python2.7/site-packages/paddle/fluid/executor.py", line 313, in _add_feed_fetch_ops
    if not has_feed_operators(global_block, feed, feed_var_name):
  File "/home/spider/xingzhihui/book/08.machine_translation/paddle_release_home/python/lib/python2.7/site-packages/paddle/fluid/executor.py", line 130, in has_feed_operators
    "Feed operators in program desc do not match 'feed_targets'")
Exception: Feed operators in program desc do not match 'feed_targets'
```
辛苦解答，多谢~

**Comment by NHZlX** [comment]
```
for data in test_reader():
         cost1,acc,prediction, content_attention_weight, sent_attention_weight = exe.run(inference_program,
                       feed=utils_bak.data2tensor(data, place),
                       fetch_list=fetch_targets,
                       return_numpy=False)
```

根据log看起来， 你的feed = utils_bak.data2tensor(data, place) 和program desc 中的feed targets 不匹配。

**Comment by qnqinan** [comment]
![image](https://user-images.githubusercontent.com/25759045/50827058-6f8c9c00-1378-11e9-930e-e0dbef7706db.png)
，请问这个问题解决了没有，我们也有这个需求
