### ISSUE TITLE
Benchmark工程求助

### ISSUE THREAD

**Issue by shijieheping** [PaddlePaddle/Paddle#1298]
在0.9.0 dev版本https://github.com/PaddlePaddle/Paddle/tree/develop/benchmark/paddle/image目录下，没有提供数据下载和预处理的脚本。
运行过程中input.list的内容是空的，看上去好像没有正确运行。

按照README.md 里的信息，我下载好了那几个小规模的数据包bvlc_alexnet.caffemodel、bvlc_googlenet.caffemodel和cifar-10-python.tar.gz，应该怎么输入到平台里处理呢？

这个benchmark工程，能不能输出每秒钟训练多少example这种信息？
当前我计时只能看一眼10batch时间，在看一眼100batch时间，之后相减除以90。

能否提供详细一些的benchmark操作文档？感谢

**Comment by qingqing01** [comment]
@shijieheping 图像CNN的benchmark采用随机生成的数据，不读取真实数据。在dataprovider文件里，即 https://github.com/PaddlePaddle/Paddle/blob/develop/benchmark/paddle/image/provider.py，不需要提供模型和数据，只需要模型配置文件即可。

` paddle train --job=time `会打印出多少Batch的时间，每秒训练多少样本，可以自己根据batch size换算。
