### ISSUE TITLE
Python单测check_grad出问题

### ISSUE THREAD

**Issue by zzhzz** [PaddlePaddle/Paddle#12994]
自己写了一个operator，完成了反向计算过程
在单测的check_grad中发生如下错误，没有找到修改的头绪
Traceback (most recent call last):
287:   File "/Users/baidu/Documents/Paddle/build/python/paddle/fluid/tests/unittests/test_tree_conv_op.py", line 92, in test_check_grad
287:     self.check_grad(['NodesVector', 'Filter'], 'Out')
287:   File "/Users/baidu/Documents/Paddle/build/python/paddle/fluid/tests/unittests/op_test.py", line 405, in check_grad
287:     user_defined_grads)
287:   File "/Users/baidu/Documents/Paddle/build/python/paddle/fluid/tests/unittests/op_test.py", line 441, in check_grad_with_place
287:     output_names, no_grad_set)
287:   File "/Users/baidu/Documents/Paddle/build/python/paddle/fluid/tests/unittests/op_test.py", line 519, in _get_gradient
287:     executor.run(prog, feed_dict, fetch_list, return_numpy=False)))
287:   File "/Users/baidu/Documents/Paddle/build/python/paddle/fluid/executor.py", line 470, in run
287:     self.executor.run(program.desc, scope, 0, True, True)
287: ValueError: Invalid index

**Comment by seiriosPlus** [comment]
加入log相关ENV先定位一下错误的地点。
    export GLOG_v=4
    export GLOG_logtostderr=1
