### ISSUE TITLE
mac 安装错误

### ISSUE THREAD

**Issue by VamWolf** [PaddlePaddle/Paddle#1299]
[Paddle] Python Executable: /usr/bin/python2.7
[Paddle] Python Include: /usr/include/python2.7
[Paddle] Python Libraries: /usr/lib/libpython2.7.dylib
CMake Error at cmake/external/openblas.cmake:36 (MESSAGE):
  To build lapack in libopenblas, you need to set gfortran compiler: cmake ..
  -DCMAKE_Fortran_COMPILER=...
Call Stack (most recent call first):
  CMakeLists.txt:64 (include)

需要自主安装一个？还是配置错了.

**Comment by gangliao** [comment]
@VamWolf 
有两种方法解决这个问题：
第一种方法：brew install openblas
第二种方法：brew install gcc

**Comment by gangliao** [comment]
@VamWolf  any update？

**Comment by VamWolf** [comment]
blas 的问题搞定了。
新问题是
CMake Error at cmake/configure.cmake:48 (message):
  Paddle need cudnn to compile
Call Stack (most recent call first):
  CMakeLists.txt:78 (include)

**Comment by VamWolf** [comment]
求解决方案

**Comment by VamWolf** [comment]
这个库我下载下来安装了

**Comment by gangliao** [comment]
```
cmake -DCUDNN_ROOT ..
```
@VamWolf 

你Mac有gpu?

**Comment by gangliao** [comment]
@VamWolf misunderstand his Mac OS X equipped with GPU when compiling paddle.

I closed this issue.
