### ISSUE TITLE
Failed to interpret file './cifar-10-batches-py/data_batch_1' as a pickle

### ISSUE THREAD

**Issue by axsauze** [PaddlePaddle/Paddle#1301]
# Minor issue in Image Classification Tutorial

When running the "process_cifar.py" file /demos/image_classification/data on Python 3.4, I get the error:

``` bash
OSError: Failed to interpret file './cifar-10-batches-py/data_batch_1' as a pickle
```

This error appears when np.load tries to open the data_batch_1 file.

I was able to walk around this issue by using cPickle directly as follows:

``` python
def get_data(batch_path):
    f = open(batch_path, 'rb')
    d = cPickle.load(f, encoding='bytes')
    d_decoded = {}
    for k, v in d.items():
        d_decoded[k.decode('utf8')] = v
    d = d_decoded
    f.close()
    data = d['data']
    labels = d['labels']
    filenames = [b.decode("utf-8") for b in d['filenames']]

    return data, labels, filenames
```

I'm not sure if this is due to a python versioning problem, but more users might experience this issue. 

Thank you.

**Comment by axsauze** [comment]
Nevermind, I have realised that the docker container use Python 2.7 and the code that is provided is suitable for Python 2.7

Thank you anyways!

**Comment by helinwang** [comment]
Thank you for reporting! This issue will be useful for people with similar python version problem. Since it's resolved for you. I am closing this issue.
