### ISSUE TITLE
paddle V2的capi的多输入如何写？

### ISSUE THREAD

**Issue by shiyazhou121** [PaddlePaddle/Paddle#13011]
我的网络结构如下：
![image](https://user-images.githubusercontent.com/15082798/44698667-81e5f780-aab3-11e8-8397-3efa0586875c.png)

猜测的代码应该是下边这样的，想问下是这样写的吗？另外想问下mat1 mat2 如何对应到x1 x2。是按顺序排列就行了？
paddle_arguments in_args = paddle_arguments_create_none();
CHECK(paddle_arguments_resize(in_args, 2));

paddle_matrix mat1 = paddle_matrix_create(1, 800, false);
CHECK(paddle_arguments_set_value(in_args, 0, mat1));

paddle_matrix mat2 = paddle_matrix_create(1, 384, false);
CHECK(paddle_arguments_set_value(in_args, 1, mat2));

**Comment by luotao1** [comment]
- 上面的代码是正确的。
- 按照C++的input顺序排列。

**Comment by shiyazhou121** [comment]
@luotao1 是按照python里定义的顺序吗？ 比如上面的python里x1，x2调换位置，变成x2, x1 ，在c++中就要改成下面的吗？
paddle_arguments in_args = paddle_arguments_create_none();
CHECK(paddle_arguments_resize(in_args, 2));

paddle_matrix mat1 = paddle_matrix_create(1, 384, false);
CHECK(paddle_arguments_set_value(in_args, 0, mat1));

paddle_matrix mat2 = paddle_matrix_create(1, 800, false);
CHECK(paddle_arguments_set_value(in_args, 1, mat2));

**Comment by luotao1** [comment]
按照C++的input顺序，大部分情况下和python定义的顺序是一样的。

**Comment by shiyazhou121** [comment]
@luotao1 还是有些疑惑，1.C++的input顺序是指(paddle_arguments_set_value(in_args, xxxxx, mat2)中的xxxxx吗？ 2.大部分情况和python顺序是一样的，，感觉很玄学啊。。有没有类似feeding来保证输入的连接？？

**Comment by luotao1** [comment]
可以参考类似问题 https://github.com/PaddlePaddle/Paddle/issues/12014#issuecomment-403453631
v2的CAPI目前没有feeding来保证输入的链接。

**Comment by shiyazhou121** [comment]
@luotao1 看了你发的其他人的问题和答案。
找到保存的模型目录下inputs的protobuf文件
用工具把protobuf的内容打印出来查看inputs的先后顺序
对应调整 c++里的input 的先后顺序

我的保存模型是merge_v2_model保存的，可以用上面说的工具吗？还有上面说的工具在哪里可以找到

**Comment by luotao1** [comment]
@shiyazhou121 C++中的顺序和python中的是一样的。不一样的情况，是由于python中调整了顺序，但没有重新使用merge_v2_model来保存。所以，如果您调整python顺序后，要重新用merge_v2_model来保存一下，再调整C++顺序即可。

**Comment by lucywsq** [comment]
您好，此issue已经解决，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题，
我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持!

**Comment by ckarying** [comment]
请问一下，现在capi的paddle_ivector可以指定batchsize么 @luotao1
