### ISSUE TITLE
PIL dependencies not installed in Docker file

### ISSUE THREAD

**Issue by axsauze** [PaddlePaddle/Paddle#1302]
It seems that the dependencies for PIL.Image python are not installed in the docker image.

I am aware that the tutorials that it's necessary to install it, but I think it might be something useful to have if offering it to people. 

Also other basic python libraries would be useful such as virtualenv, together with the requirements.txt file so users can avoid having to install everything manually.

**Comment by helinwang** [comment]
@axsauze Thanks for reporting!
From my understanding, PIL is the pillow package in pip. I do find it in the [docker file](https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/scripts/docker/Dockerfile#L18)

Good point in the requirements.txt, this is something we would like to improve. Contribution welcome!

**Comment by Xreki** [comment]
It is already met in current Dockerfile, so closed.
