### ISSUE TITLE
怎样打印 loDTensor 内容？

### ISSUE THREAD

**Issue by youngstu** [PaddlePaddle/Paddle#13029]
('====result: ', <paddle.fluid.core.LoDTensor object at 0x7f8aa8056300>)

怎样打印 loDTensor 内容，或者把loDTensor 转换为其他类型如numpy, loDTensor 有哪些属性和方法？

**Comment by youngstu** [comment]
why fluid does not have such as torch.from_numpy() 和 tensor.numpy() 类似轻便的方法。

**Comment by ktlichkid** [comment]
有两种方法，一种是用layers.Print直接Print
另一种是把lod tensor作为网络的输出fetch出来，然后 numpy.array(lod_tensor), 就能转成numpy array

这确实是很常用的操作，但我们在文档中没能很好地讲解这些方法，导致了不必要的误解。我们会在今后的版本中强化这一块的文档，让用户可以更加清晰地使用这些操作。

**Comment by gtvforever** [comment]
@ktlichkid 能否就后一种方法 举出更详细的例子？ 不是很清楚如何fetch 没找到fetch的详细接口定义。谢谢

**Comment by ktlichkid** [comment]
所谓fetch就是获取网络的输出值。例如下面的code, fetch_outs获取之后就可以numpy.array(fetch_outs[0])转成numpy array

```Python
        fetch_outs = exe.run(framework.default_main_program(),
                             feed={
                                 feeding_list[0]: src_seq,
                                 feeding_list[1]: init_ids,
                                 feeding_list[2]: init_scores
                             },
                             fetch_list=[translation_ids, translation_scores],
                             return_numpy=False)
```

**Comment by ktlichkid** [comment]
没有其他问题的话，这个issue我先close了。如果还有问题欢迎再打开~
