### ISSUE TITLE
存Batch Norm时，无法只计算forward-backward，但不更新参数

### ISSUE THREAD

**Issue by Tristan-Hao** [PaddlePaddle/Paddle#13038]
当model中存在Batch Norm时，希望只计算forward-backward，但不更新参数,只计算input的梯度。
      param_grads = fluid.backward.append_backward(
          loss, parameter_list=[self._input_name])
      self._gradient = filter(lambda p: p[0].name == self._input_name,
                              param_grads)[0][1]

现在的现像是，非is_test模式下，可以计算梯度，但参数都被更新，相当于正常训练模式。
is_test模式下，参数不会被更新，但无法计算梯度，只能预测。
请确认和支持该能力。谢谢

**Comment by velconia** [comment]
请问为什么会有这样的需求呢? 是为了debug吗? 如果是为了打印参数, 建议使用```print_op```, 如果不更新参数做法会比较Hack

**Comment by Tristan-Hao** [comment]
是的，我们是在做adversarial example相关，使用tensorflow可以独立计算梯度，在paddle下要使用append_backward，在简单模型（无BN无dropout）下没有问题，如果存在BN就不行，参数全被更新，除非再进行反复load参数操作.....是否能对BN进行调整，或支持仅供计算梯度的API。

**Comment by velconia** [comment]
你定义Optimizer了吗? 如果未定义Optimizer就不会更新参数的

**Comment by lucywsq** [comment]
您好，此issue在近一个月内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题，我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持!
