### ISSUE TITLE
如何发布训练好的模型？

### ISSUE THREAD

**Issue by 1145520074** [PaddlePaddle/Paddle#1303]
想问下我训练好一个模型后，如何发布程序到hadoop或者别的没有安装paddle程序的机器上运行预测程序，需要添加哪些依赖？多谢

**Comment by 1145520074** [comment]
顶一下，没人会么？

**Comment by reyoung** [comment]
* Paddle推荐使用Docker来多机分布式执行。hadoop如果可以执行docker run的话，这事情就比较简单了。
* 如果目标机器不可以执行docker，可以讲docker container export成一个rootfs，然后使用[proot](https://github.com/proot-me/PRoot/blob/master/doc/proot/manual.txt)来做。这样避免手动安装依赖。

**Comment by 1145520074** [comment]
好的，多谢
