### ISSUE TITLE
每个batch 用指定的数据update指定层的参数

### ISSUE THREAD

**Issue by rulai-huiyingl** [PaddlePaddle/Paddle#13034]
两个数据不同的task共享网络的底层参数，但是有不同的上层和损失函数.
能否做到，在每一个batch,sample一个task，用这个task的batch数据update底层共享和上层独有的参数. 
也就是每一个batch的训练数据，loss和要update的参数都可能是不一样的．
谢谢！

**Comment by rulai-huiyingl** [comment]
请问在v2上能不能实现，谢谢！

**Comment by velconia** [comment]
请问方便提供下代码吗? 建议使用```Fluid```来做这件事, 会更灵活一些

**Comment by rulai-huiyingl** [comment]
@velconia 谢谢回复！因为版本限制暂时只能用v2.
没有代码呢，因为用v2不知道实现这个怎么下手，trainer只有cost这个kwarg可以接受一个或者多个loss,没有看见其他可以变动的东西，我至少希望可以每个batch的loss函数不一样
是否可能在event_handler enditeration里面做一些操作达到效果？

**Comment by velconia** [comment]
你好，我理解你这个是一个两个网络共享参数 + IfElseOp的需求，这个在v2里是不支持的

**Comment by lucywsq** [comment]
您好，后续V2版本将不进行维护，建议您迁移至Fluid。
此issue在近一个月内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题，
我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持!
