### ISSUE TITLE
如何获取CUDA上的Tensor中的值？

### ISSUE THREAD

**Issue by zzhzz** [PaddlePaddle/Paddle#13031]
我使用类似CPU的手段：
```c++
const T* data = tensor.data<T>();
T v = data[10];
```
类似这样的手段，但是运行时报了SEGFAULT。我不是太会使用CUDA，请问这个该怎么办呢

**Comment by ktlichkid** [comment]
如果tensor在GPU上，那最好是在GPU kernel里面处理这个data。比如你可以看看lstm_unit.cu这个文件

**Comment by dzhwinter** [comment]
需要先调用TensorCopy，拷贝到CPU上，然后wait一下。参考lod_tensor_test，里面有所有的测试用例

**Comment by zzhzz** [comment]
CUDA上面的Tensor可以在GPU kernel中使用mutable_data吗 @ktlichkid

**Comment by zzhzz** [comment]
比如我临时创建了一个Tensor，期望GPU将计算结果放在这个Tensor里面。如果是CPU的话需要使用mutable_data获取一个可分配的空间，GPU上也是这么做吗？在CPU上直接使用mutable_data然后将数据指针传送到GPU kernel中可以吗？

**Comment by zzhzz** [comment]
还有一个问题：如果我想在GPU kernel中使用BLAS的Matmul函数，是否可以直接调用？有没有可供参考的例子

**Comment by velconia** [comment]
可以参考 operators/math/blas_impl.h

**Comment by ktlichkid** [comment]
> 在CPU上直接使用mutable_data然后将数据指针传送到GPU kernel中可以吗？

基本上你只有两种选择：
1. 单独为你的op写一个GPU kernel，可以参考operator路径下的诸多.cu文件
2. 用TensorCopy将tensor拷贝到CPU上处理

**Comment by zzhzz** [comment]
我知道了
