### ISSUE TITLE
多机训练image_classification时，如果打开内存优化报错

### ISSUE THREAD

**Issue by kolinwei** [PaddlePaddle/Paddle#13042]
Traceback (most recent call last):
  File "dist_image_classification.py", line 139, in <module>
    runtime_main(TestDistImageClassification)
  File "/work/weike/svn/baidu/paddle/test/cts_test/dist_base.py", line 243, in runtime_main
    model.run_trainer(endpoints, trainer_id, trainers, run_params)
  File "/work/weike/svn/baidu/paddle/test/cts_test/dist_base.py", line 176, in run_trainer
    build_strategy=build_strategy)
  File "/usr/local/lib/python2.7/dist-packages/paddle/fluid/parallel_executor.py", line 165, in __init__
    build_strategy, num_trainers, trainer_id)
paddle.fluid.core.EnforceNotMet: can not find right place for distributed op: conv2d_grad at [/paddle/paddle/fluid/framework/details/multi_devices_graph_pass.cc:754]
PaddlePaddle Call Stacks:
0       0x7f8c84172e86p paddle::platform::EnforceNotMet::EnforceNotMet(std::__exception_ptr::exception_ptr, char const*, int) + 486
1       0x7f8c84f91fe9p paddle::framework::details::MultiDevSSAGraphBuilder::CreateDistTrainOp(paddle::framework::ir::Graph*, paddle::framework::ir::Node*) const + 2345
2       0x7f8c84f95469p paddle::framework::details::MultiDevSSAGraphBuilder::ApplyImpl(std::unique_ptr<paddle::framework::ir::Graph, std::default_delete<paddle::framework::ir::Graph> >) const + 2025

**Comment by kolinwei** [comment]
Traceback (most recent call last):
  File "dist_image_classification.py", line 139, in <module>
    runtime_main(TestDistImageClassification)
  File "/work/weike/svn/baidu/paddle/test/cts_test/dist_base.py", line 262, in runtime_main
    model.run_trainer(endpoints, trainer_id, trainers, run_params)
  File "/work/weike/svn/baidu/paddle/test/cts_test/dist_base.py", line 178, in run_trainer
    build_strategy=build_strategy)
  File "/usr/local/lib/python2.7/dist-packages/paddle/fluid/parallel_executor.py", line 165, in __init__
    build_strategy, num_trainers, trainer_id)
paddle.fluid.core.EnforceNotMet: the distribute training related op should be in [split_byref, concat]. at [/work/weike/paddle15/paddle/fluid/framework/details/multi_devices_graph_pass.cc:741]
PaddlePaddle Call Stacks:
0       0x7f7c4290cfe6p paddle::platform::EnforceNotMet::EnforceNotMet(std::__exception_ptr::exception_ptr, char const*, int) + 486
1       0x7f7c4373b122p paddle::framework::details::MultiDevSSAGraphBuilder::CreateDistTrainOp(paddle::framework::ir::Graph*, paddle::framework::ir::Node*) const + 2114
2       0x7f7c4373eb49p paddle::framework::details::MultiDevSSAGraphBuilder::ApplyImpl(std::unique_ptr<paddle::framework::ir::Graph, std::default_delete<paddle::framework::ir::Graph> >) const + 2025

**Comment by typhoonzero** [comment]
Will find a general way and fix this in next release.

**Comment by typhoonzero** [comment]
对内存优化和分布式训练共同使用的情况，现在决定规定，必须先调用memory_optimize，然后调用distribute_transpiler。

如果先调用distribute_transpiler，然后对生成的trainer端的program执行内存优化，会导致send的variable会被rename，导致trainer和pserver的variable name有区别，导致程序出错。所以，需要修改distribute transpiler可以同步兼容内存优化输出的program，另外在每个模型上增加单测。

**Comment by panyx0718** [comment]
内存优化这块志宏已经开始在IR里做了。将来还是会在dist_transpiler之后进行。所以内存优化可能会需要判断分布式相关op，避免一些问题。
