### ISSUE TITLE
pip2能安装paddle，pip3安装不了？

### ISSUE THREAD

**Issue by hdjsjyl** [PaddlePaddle/Paddle#13061]
pip2 install paddlepaddle-gpu and一切正常；pip3 install …… 显示无法找到要求的包，这是什么原因？

**Comment by hdjsjyl** [comment]
找到回答了, 确实还不支持!

**Comment by yangperasd** [comment]
paddlepaddle目前不支持python3，只支持python2.
所以不能使用pip3安装。

**Comment by lucywsq** [comment]
您好，此issue在近一个月内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题， 我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持!
