### ISSUE TITLE
求问有木有googlenet的模型配置文件?

### ISSUE THREAD

**Issue by 1145520074** [PaddlePaddle/Paddle#1306]
我看vgg和resenet的都有，googlenet有木有呢？

**Comment by qingqing01** [comment]
GoogleNet-V1可以参考这个:

https://github.com/PaddlePaddle/Paddle/blob/develop/benchmark/paddle/image/googlenet.py

**Comment by 1145520074** [comment]
# @qingqing01 好的多谢
