### ISSUE TITLE
使用命令"pip install paddlepaddle-gpu" for CUDA9, 但是自动安装的版本是paddlepaddle-gpu-0.14.0.post87, 这个是cuda8的版本, 怎么办?

### ISSUE THREAD

**Issue by hdjsjyl** [PaddlePaddle/Paddle#13062]
使用命令"pip install paddlepaddle-gpu" for CUDA9, 但是自动安装的版本是paddlepaddle-gpu-0.14.0.post87, 这个是cuda8的版本, 怎么办?

**Comment by xuezhong** [comment]
试下指定安装版本 pip install  paddlepaddle-gpu==0.14.0 更多参考http://www.paddlepaddle.org/documentation/docs/zh/0.14.0/new_docs/beginners_guide/install/install_doc.html

**Comment by hdjsjyl** [comment]
@xuezhong  这个版本也试了, 还是不work

**Comment by hdjsjyl** [comment]
@xuezhong  用docker就可以

**Comment by lucywsq** [comment]
您好，此issue在近一个月内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题， 我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持!
