### ISSUE TITLE
编译错误

### ISSUE THREAD

**Issue by RayLiu2015** [PaddlePaddle/Paddle#13086]
在只有CPU 的 ubuntu 16.04 机器上使用文档中的命令通过源码编译:
![image](https://user-images.githubusercontent.com/13360993/44856864-182b4080-aca1-11e8-80d5-c7de1d5352ca.png)

尝试编译了很多次, 依旧报错, 最终的报错信息为:
![image](https://user-images.githubusercontent.com/13360993/44856915-35600f00-aca1-11e8-8aba-dee9306f7c5c.png)
哪位同学帮忙看下怎么解决呀 ?

**Comment by sneaxiy** [comment]
麻烦提供完整的编译安装环境，如gcc版本，cmake版本，protobuf版本等

**Comment by JiabinYang** [comment]
请使用gcc5.4，cmake3.4进行make 和cmake

**Comment by RayLiu2015** [comment]
好的, thx
