### ISSUE TITLE
关于fc_layer默认激活函数的疑问

### ISSUE THREAD

**Issue by HugoLian** [PaddlePaddle/Paddle#1309]
利用paddle做回归，最后一层的输出，demo上都是不带激活函数的。
但是我用模型最predict，最后的输出值域在（0,1）
在fc_layer的定义中：
```
def fc_layer(input,
             size,
             act=None,
             name=None,
             param_attr=None,
             bias_attr=None,
             layer_attr=None):
```
如果不设置act,那么程序对于act的定义是个None,
这样在该方法下面的配置中：
```
Layer(
        inputs=[
            Input(ipt.name, **attr.attr) for ipt, attr in zip(input, param_attr)
        ],
        name=name,
        type=LayerType.FC_LAYER,
        size=size,
        bias=ParamAttr.to_bias(bias_attr),
        active_type=act.name,
        **ExtraLayerAttribute.to_kwargs(layer_attr))
```
那么对于active_type=act.name，对一个None的对象取name, python不是会直接报错么？
为什么程序可以顺利运行呢？
另外fc_layer的说明中，说默认的激活函数是tanh，但是tanh是(-1 , 1)的，那么究竟如果不设置act，fc层是个什么机制输出啊？

**Comment by qingqing01** [comment]
> 那么对于active_type=act.name，对一个None的对象取name, python不是会直接报错么？为什么程序可以顺利运行呢？

[fc_layer 的这里](https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/trainer_config_helpers/layers.py#L846 ) 有个装饰器可以设置[默认的act](https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/trainer_config_helpers/default_decorators.py#L153)， 所以实际不是None。

> 另外fc_layer的说明中，说默认的激活函数是tanh，但是tanh是(-1 , 1)的，那么究竟如果不设置act，fc 层是个什么机制输出啊？

不设置就是默认的, 可以参考手册，或者转换为protostr的形式，看该层的act实际是什么。

```
python -m paddle.utils.dump_config  config.py > test.protostr
```

**Comment by HugoLian** [comment]
非常感谢！！
