### ISSUE TITLE
请问使用fluid.Trainer构建网络如何加载预训练数据

### ISSUE THREAD

**Issue by ws441572091** [PaddlePaddle/Paddle#13103]
查看教程文档加载预训练emb用这种方式
    def train_loop(main_program):
        exe.run(fluid.default_startup_program())
        embedding_param = fluid.global_scope().find_var(
            embedding_name).get_tensor()
        embedding_param.set(
            load_parameter(conll05.get_embedding(), word_dict_len, word_dim),
            place)
我使用的Trainer构建网络
![image](https://user-images.githubusercontent.com/35720887/44895459-0ee4b700-ad27-11e8-8935-7d4708618e70.png)
![image](https://user-images.githubusercontent.com/35720887/44895475-17d58880-ad27-11e8-85db-f9fb5738bd02.png)
这样不能直接加载预训练的emb到网络层
  File "glove_emb_drop.py", line 302, in main
    train(use_cuda,train_program, params_dirname)
  File "glove_emb_drop.py", line 166, in train
    embedding_name).get_tensor()
AttributeError: 'NoneType' object has no attribute 'get_tensor'
请问如何加载

**Comment by sneaxiy** [comment]
从log上看应该是`embedding_name`不对，建议检查下保存的模型里的`embedding_name`是否与load时一致。

**Comment by sneaxiy** [comment]
`scope.find_var()`在变量不存在时会返回`None`。可改用`scope.var()`，这个API在变量不存在的时候会创建之。

**Comment by MangoLiu** [comment]
本来加载预训练embedding是个很通用的点。
但文档偏偏让参考语义角色标注中的一段代码。
难道抽象一下，写到通用文档里，不好吗？
