### ISSUE TITLE
训练CTR模型，发生错误：Matrix.cpp:653] Not supported

### ISSUE THREAD

**Issue by xiaolv3366** [PaddlePaddle/Paddle#13105]
使用GPU训练CTR模型，发生错误：Matrix.cpp:653] Not supported。
使用CPU训练没有问题，CTR模型用CPU训练很慢，用GPU训练有没有解决办法？
![image](https://user-images.githubusercontent.com/12287110/44896949-8ec15000-ad2c-11e8-8b20-59f250780f6c.png)

**Comment by xiaolv3366** [comment]
PaddlePaddle一定要支持GPU训练CTR模型，有没办法解决？

**Comment by sneaxiy** [comment]
我看代码里面是因为transpose的矩阵乘法在GPU上不支持，您可以先将矩阵transponse后再进行矩阵乘法计算。

**Comment by lucywsq** [comment]
您好，此issue在近一个月内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题， 我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持!
