### ISSUE TITLE
Propose to re-define Layer/Network description proto messages

### ISSUE THREAD

**Issue by wangkuiyi** [PaddlePaddle/Paddle#1310]
Currently the definition in https://github.com/PaddlePaddle/Paddle/blob/develop/proto/ModelConfig.proto doesn't follow the usually way we use protobuf and is over-complicated.

I propose an alternative as follows, in hope of a clean and concise description.  Your comments are welcome!

```
package paddle.proto.layer

# Usage would be proto.Layer.Layer/FC/Data, which differs from paddle.layer.Layer/FC/Data
message Layer {
	required string name = 1;
	repeated uint32 inputs = 2;  // indices into Network.layers
	repeated uint32 outputs = 3; // indices into Network.layers

	enum Type {
	     FC,
	     Data,
             Softmax,
	}
	required Type type = 10;
	optional Data data = 11; // According to type, if it's a data layer, fill this field.
	optional FC fc = 12;     // or, if it's a FC layer, fill this field.
        optional Softmax = 13;
}

message Network {
	repeated Layer layers = 1;
}
```

An example for your convenience.  The following network

```
  /-> int1 -\
in           -> out
  \-> int2 -/
```

can be expressed as

```
Network {
  layers = {
     Layer { name="in", type=Data, inputs=[], outputs=[1,2] },
     Layer { name="int1", type=FC, inputs=[0], outputs=[3] },
     Layer { name="int2", type=FC, inputs=[0], outputs=[3] },
     Layer { name="out", type=Softmax, inputs=[1,2], outputs=[] }
  }
}
```

**Comment by wangkuiyi** [comment]
As suggested by @emailweixu , I am reading [Tensorflow's implementation](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/framework/graph.proto) as a survey.

**Comment by reyoung** [comment]
我感觉重构protobuf对于目前重构Paddle API并不是非常关键的。不过，如果要重构protobuf message的话，可能之前的一些教训需要考虑一下。

每一种类型的Layer都有每一种类型Layer的特有参数。如果对于每一种Layer都定义一个field的话，那这个Layer message会很快的有如下几个问题:

* 变得非常大和难以维护。因为每个Layer都会往里增删参数。
* 无法shared同样行为的参数。比如，对于很多layer都会有一个drop_out的参数，来配置这个层的drop_out率。如果我们对每一个layer都有独立的field的话，那么一些common的参数就很难传递。

   ```protobuf
   message FC {
   ...
   optional float drop_out_rate = 10;
   ...
   }
   message LSTM {
   ...
   option float drop_out_rate = 10;
   ...
   }
   message Layer {
   ...
   optional FC fc = 10;
   ...
   optional LSTM lstm = 100;
   }
   ```
* Layer变成了必须写在Paddle主线代码里的东西，用户除非修改这个protobuf message，否则没有办法自定义一个Layer了。

之前也考虑过这个事情，这个事情在最新的protobuf library里面，可以通过`map`来解决。我们定义一个通用的Attribute类，类似于 `boost::any`。然后每种Layer独有的参数，都通过map传入，不同的Layer可以使用不同的key的prefix。整体定义类似于

```protobuf
syntax = "proto2";  // using protobuf 2 syntax
message Attribute {
    enum AttributeType {
        AT_INT,
        AT_BOOL,
        AT_FLOAT,
        ...
    }
    required AttributeType type = 1;
    optional int int_value = 2;
    optional bool bool_value = 3;
    optional float float_value = 4;
}

message Layer {
    required string name = 1;
    repeated string inputs = 2;
    required int size = 3;
    ...
    map<string, Attribute> other_attrs = 100;
}
```

参考连接:

https://developers.google.com/protocol-buffers/docs/proto#maps

**Comment by Canpio** [comment]
Close this inactivate issue, please feel free to reopen.
