### ISSUE TITLE
magic numbers

### ISSUE THREAD

**Issue by wojtuss** [PaddlePaddle/Paddle#13110]
What these numbers mean? There is no comment on that:

https://github.com/PaddlePaddle/Paddle/blob/c709a04ae22cd848f50a11737bdb3af24eabbe1e/paddle/fluid/framework/ir/fc_lstm_fuse_pass.cc#L27

**Comment by luotao1** [comment]
These numbers mean the node ID in the ditu-rnn demo. We will remove these hard-coding ASAP.

**Comment by luotao1** [comment]
#13158 has already removed these hard-coding numbers.
