### ISSUE TITLE
an high performance issue in prelu_op.h#L44

### ISSUE THREAD

**Issue by xiebaiyuan** [PaddlePaddle/Paddle#13123]
https://github.com/PaddlePaddle/Paddle/blob/c108376506faa8c51f489a4c1e658a446424453a/paddle/fluid/operators/prelu_op.h#L44

this expression that on L44 of prelu_op.h :
(temp = numel / (dim[0] * dim[1]);）  
can be moved out of for loop  to  improve performance

**Comment by tensor-tang** [comment]
Thanks, good catch!
