### ISSUE TITLE
如何在train的时候输出每个layer传到下一个layer的数据

### ISSUE THREAD

**Issue by lcxaiw** [PaddlePaddle/Paddle#1314]
您好：
       最近我在用Paddle写网络的时候总会遇到layer之间传递的数据类型不对称的问题，大部分是因为手误，但却要花费大量时间进行调试，请问Paddle有相关的API可以输出这些数据嘛？用outputs()只能输出最后classufication_cost的数据，但输出其他的会报错或者不输出。
        查阅文档没有找到相关的API
        谢谢

**Comment by wangkuiyi** [comment]
谢谢提醒。我理解我们目前还没有这样的便利的调试方法。我记得之前 @reyoung 提到够过增加这样的检查。

**Comment by lcxaiw** [comment]
@reyoung 您好，请问现在这个功能已经添加进来了嘛？如果有，还望指教，谢谢

**Comment by reyoung** [comment]
如果想在每次训练的时候，输出某一层的值，可以使用`print_layer`。具体配置方法类似于

```python
data = data_layer(...)
...
middle = fc_layer(...)

print_layer(input=middle)
```

这样，会将middle的输出输出在log里。

**Comment by lcxaiw** [comment]
@reyoung  多谢
