### ISSUE TITLE
Broken links in README.md

### ISSUE THREAD

**Issue by Haichao-Zhang** [PaddlePaddle/Paddle#13152]
All the links in the Installation and Documentation sections are broken:
![image](https://user-images.githubusercontent.com/21375027/44952615-9f5eec80-ae38-11e8-8071-ecc970b04c91.png)

![image](https://user-images.githubusercontent.com/21375027/44952619-b7cf0700-ae38-11e8-96d0-4f6ec71800ec.png)

**Comment by shanyi15** [comment]
请您提供这个页面的链接
![image](https://user-images.githubusercontent.com/35982308/44963975-9a955800-af60-11e8-873b-b91665580e3d.png)

**Comment by qingqing01** [comment]
@shanyi15 是Paddle Repo主页： https://github.com/PaddlePaddle/Paddle#installation

**Comment by shanyi15** [comment]
Thanks @Haichao-Zhang for the valuable reminding
Thanks @qingqing01 for providing link
