### ISSUE TITLE
如何创建lstm模型预测一个回归值？有大神的麻烦写一下代码。

### ISSUE THREAD

**Issue by 1727536969** [PaddlePaddle/Paddle#13157]

**Comment by qingqing01** [comment]
LSTM使用代码可以参考： https://github.com/PaddlePaddle/models/blob/develop/fluid/text_classification/nets.py#L62

做预测回归，大致可以是， 输入一个时间序列，用lstm网络提取特征， 使用mse之类的loss(当然loss也可以是其他的)。
