### ISSUE TITLE
se-resnext多机同步下，有trainer在多个pass下后，loss值突增

### ISSUE THREAD

**Issue by ccmeteorljh** [PaddlePaddle/Paddle#13163]
paddle version：0.15
模型：se-resnext
paddlecloud job:
http://paddlecloud.baidu-int.com:8088/paddle/jobRunInfo?jobId=job-e6c5b7d5391e215f&flag=jobs&groupName=k8s_gpu_demo&groupId=c0a1f165-6279-5320-b9e7-e0218c7a87f5&currentPage=1&currentKey=1

**Comment by luameows** [comment]
@ccmeteorljh 您是如何安装0.15版本的呢

**Comment by ccmeteorljh** [comment]
直接在cloud上用编译好的whl包替换paddle

**Comment by Yancey0623** [comment]
已能够在小范围内复现，job链接：http://paddlecloud.baidu-int.com:8088/paddle/jobRunInfo?jobId=job-e6c5b8f3e3895c4f&flag=jobs&groupName=k8s_gpu_demo&groupId=c0a1f165-6279-5320-b9e7-e0218c7a87f5&currentPage=1&currentKey=1

现象：当trainer节点分配的batch不相同时，其中某些节点会提前结束训练并调用`exe.close()`，剩余继续训练的节点会出现loss升高的情况。
可能的原因：同步训练时，pserver会根据任务启动时配置的trainer数量对w@GRAD求平均:`sum(w@GRAD.trainer$i)/trainers`, 当部分节点结束训练时，trainers并没有动态调整，导致优化时候的grad变小，是否和loss升高有直接原因还需要进一步定位。
