### ISSUE TITLE
能够获取 sequenceStartPositions 信息, 并将保存的sequenceStartPositions 赋值给某个序列

### ISSUE THREAD

**Issue by JinmingZhao** [PaddlePaddle/Paddle#13166]
**版本信息: paddle.v2**
事情是这样的, 比如一个bacth 10句话, 每句话长度不等, 所有单词用 batch_words 表示, 每个单词的维度用 word_dim 来表示, 那么paddle的保存格式为: (batch_words, word_dim)].
假设这个batch经过resize操作原先的 sequenceStartPositions 信息丢失了, 我下面再接一个 lstm的时候就会报错 
F0903 04:46:41.062814 16210 LstmLayer.cpp:155] Check failed: input.sequenceStartPositions
那么这种这种情况下如何解决这个问题?
比较直观的想是在变换之前保存操作之前的 sequenceStartPositions 信息, 然后变换之后再将这个信息赋值.

**Comment by Yancey0623** [comment]
Hi您好，在v2的版本中暂时没有这个功能，但可以在Fluid中通过 [lod_reset](http://paddlepaddle.org/documentation/api/zh/0.14.0/layers.html#lod-reset) 来实现

**Comment by JinmingZhao** [comment]
Hi, 您好, 谢谢回复.
我现在有两个shape为[94, 500] 的矩阵(其中94为lstm的输出, 表示一个batch内的所有words, 具有batch内的每个句子的起始点信息) 分别为A和B, 现在其中 500 是 5个100维的向量拼接而成, 那么计算  [94, 5, 100]  与 [94, 5, 100]   对应元素(元素表示100维度的vector) 的余弦距离, 最后得到一个 (94, 5)的矩阵.
并且 得到的(94, 5)的矩阵还要做的序列送入下一个lstm, 如上面提到的问题, 不能进行resize成(94*5, 100)操作, 否则会打乱原有序列信息.

那么这种情况, 我应该怎么做呢?
比较直观的是 (94, 500) 进行 切片, 每次取 (94, 100 ), 在paddle中怎么实现这种切片? 用select_fc 吗?

**Comment by JinmingZhao** [comment]
@Yancey1989 
提供一个解决思路:
用 seq_reshape 可以保留 seqence 的 起始点信息, 而直接resize 则会丢失 起始点信息.
B = paddle.layer.seq_reshape(A, reshape_size=100)
C = paddle.layer.seq_reshape(A, reshape_size=5)
