### ISSUE TITLE
paddle version is 0.0.0

### ISSUE THREAD

**Issue by qnqinan** [PaddlePaddle/Paddle#13174]
在执行编译cmake .. -DWITH_FLUID_ONLY=ON -DWITH_GPU=OFF -DWITH_TESTING=OFF后，会在最后打印如下信息：
-- Paddle version is 0.0.0
-- Configuring done
-- Generating done
-- Build files have been written to: /home/ubuntu1604-02/project/paddle/build
为什么提示paddle的版本是0.0.0？？看之前的有人遇到，说需要执行git fetch upstream, 我这边执行会报如下错误：
fatal: 'upstream' does not appear to be a git repository
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
所以我这边尝试执行的是git fetch origin，不会报错，
然后执行cmake .. -DWITH_FLUID_ONLY=ON -DWITH_GPU=OFF -DWITH_TESTING=OFF，还是会打印以上信息，提示paddle版本是0.0.0

**Comment by Yancey0623** [comment]
Hi 您好

这个版本的提示信息不影响正常的编译，paddle的cmake是根据当前git所在分支来判断版本的，例如想编译0.14.0版本的paddle可以先切换到`v0.14.0`这个tag再编译：

``` bash
> git checkout v0.14.0
```

**Comment by qnqinan** [comment]
@Yancey1989 
ok, tks
