### ISSUE TITLE
ctr 异步训练内存泄露

### ISSUE THREAD

**Issue by ccmeteorljh** [PaddlePaddle/Paddle#13173]
job地址：
http://paddlecloud.baidu-int.com:8088/paddle/jobRunInfo?jobId=job-e6c5b88ed1a5c0e6&flag=jobs&groupName=paddle&groupId=2b984db1-5c29-5951-b4ee-11da61ccb0a5&currentPage=1&currentKey=1

与龙飞一起看过内存一直在增长，直到挂掉

**Comment by jacquesqiao** [comment]
### 当前状态
测试了很多场景，没能复现问题。

### 50节点异步

http://paddlecloud.baidu-int.com:8088/paddle/jobRunInfo?jobId=job-e6c5ba8b1d2d8c2d&flag=jobs&groupName=paddle&groupId=2b984db1-5c29-5951-b4ee-11da61ccb0a5&currentPage=1&currentKey=1

![image](https://user-images.githubusercontent.com/3048612/45987783-fc4f6a80-c0a5-11e8-8e1b-847c350b496d.png)

### 30节点异步

http://paddlecloud.baidu-int.com:8088/paddle/jobRunInfo?jobId=job-e6c5ba864818f1ac&flag=jobs&groupName=paddle&groupId=2b984db1-5c29-5951-b4ee-11da61ccb0a5&currentPage=1&currentKey=1

![image](https://user-images.githubusercontent.com/3048612/45987924-9c0cf880-c0a6-11e8-8d67-eacd6db6cb0f.png)

### 分析
可能是版本太老，需要更新一下代码重新测试
