### ISSUE TITLE
咨询下docker的lastest-gpu 下的fluid版本问题

### ISSUE THREAD

**Issue by TomorrowIsAnOtherDay** [PaddlePaddle/Paddle#13183]
我们通过docker 拉了最新版本fluid，但是发现里面的fluid不是对应最新代码的，咨询下docker：lastest-gpu里面fluid是对应哪部分代码的呢？

**Comment by TomorrowIsAnOtherDay** [comment]
update:
paddle.version.show() 可以看到版本信息，release的版本会显示版本号，develop分支的会显示commit id。

目前来看应该是每间隔一天同步一次：）

**Comment by Yancey0623** [comment]
是的，docker image是每天会更新一次。

**Comment by TomorrowIsAnOtherDay** [comment]
好的，谢谢解答

**Comment by TomorrowIsAnOtherDay** [comment]
经过3天之后，通过docker pull更新了最新的镜像，发现最新的版本仍是3天前的，请更新下docker的版本：）
![image](https://user-images.githubusercontent.com/25046619/45074855-a2e3c380-b117-11e8-8f3f-b644615bea93.png)
由于我们的仓库unittest依赖于最新的镜像，烦请跟进下

**Comment by typhoonzero** [comment]
https://hub.docker.com/r/paddlepaddle/paddle/tags/ 目前看`latest-gpu`是一小时前更新的了

**Comment by TomorrowIsAnOtherDay** [comment]
嗯呐，我刚才pull的时候确实更新了，但是登进去之后发现版本还是3天前的呢，这个有办法申请刷新吗？

**Comment by TomorrowIsAnOtherDay** [comment]
噢，看错了，load了错误的image，没有问题：）谢谢wuyi的解答
