### ISSUE TITLE
咨询paddle v2 infer多结果输出对应的field值选取规则

### ISSUE THREAD

**Issue by LiuZheng-Z** [PaddlePaddle/Paddle#13188]
https://github.com/PaddlePaddle/Paddle/blob/release/0.12.0/python/paddle/v2/inference.py

有提到`infer(output_layer, parameters, input, feeding=None, field='value')`中的field需要为[value,id,prob]的子集，也可为list。想问下在infer多结果输出时，是否可以选择任意两者的组合，比如value,prob或者value,prob，亦或者可以同时指定为value,prob,id。在选择field的时候对模型有什么要求吗？
![image](https://user-images.githubusercontent.com/13477849/44986148-508a9180-afb5-11e8-9837-e375a48baaf8.png)

**Comment by Yancey0623** [comment]
根据文档提示是可以任意组合的，只是`prob`需要output layer是beamsearch或者max_id，如果使用时遇到问题可以在这里提出来。

**Comment by LiuZheng-Z** [comment]
@Yancey1989 ok，谢谢了

**Comment by lucywsq** [comment]
您好，此issue在近一个月内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题， 我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持!
