### ISSUE TITLE
pip install paddlepaddle-gpu==0.14.0.post87 安装 fluid 版本报错

### ISSUE THREAD

**Issue by qichaotang** [PaddlePaddle/Paddle#13222]
pip install paddlepaddle-gpu==0.14.0.post87 
公司内部开发GPU机器，
系统信息：
![image](https://user-images.githubusercontent.com/12878507/45028894-606ba980-b079-11e8-98e7-6e80f1c3f386.png)
CUDA信息
![image](https://user-images.githubusercontent.com/12878507/45028950-8c872a80-b079-11e8-82f2-ca6591203eb1.png)
按照官网安装：pip install paddlepaddle-gpu==0.14.0.post87
执行 import paddle.fluid as fluid 失败
![image](https://user-images.githubusercontent.com/12878507/45028976-a0329100-b079-11e8-84a7-07253eafb3cb.png)
奇怪的是，同样的环境下，上周运行成功，这周确运行失败，求解答

**Comment by luotao1** [comment]
可以查看下是否GPU显存不够了。

**Comment by qichaotang** [comment]
执行 nvidia-smi ，显示是够的
![image](https://user-images.githubusercontent.com/12878507/45072174-5fd02300-b10c-11e8-9f16-7337a5e22082.png)
![image](https://user-images.githubusercontent.com/12878507/45072186-6c547b80-b10c-11e8-94df-578e8e8ad7d6.png)

**Comment by qichaotang** [comment]
刚才重新安装又好了。。。可能是昨天显存不够吧！Thanks！
