### ISSUE TITLE
Inference CI unittests can NOT pass under manylinux envs

### ISSUE THREAD

**Issue by velconia** [PaddlePaddle/Paddle#13221]
The tests below can NOT pass the CI tests in manylinux envs:

```
test_fake_quantize_op
test_analyzer_ner
test_analyzer_lac
```

Hope for your fix @Superjomn @luotao1 @qingqing01

**Comment by velconia** [comment]
Now ```test_fake_quantize_op``` has been fixed, thanks for @qingqing01 's work

**Comment by luotao1** [comment]
I test the latest code in `paddlepaddle/paddle_manylinux_devel:cuda8.0_cudnn5` and `python35` environment, above two unit tests are successful.

**Comment by velconia** [comment]
Thanks very much for @luotao1 's work, I have validated these tests in [here](http://ci.paddlepaddle.org/viewLog.html?buildId=17690&buildTypeId=Paddle_PrCiPython35&tab=buildLog), and this issue could be closed.
