### ISSUE TITLE
predict 本地运行错误，已设置sparse_update=Flase

### ISSUE THREAD

**Issue by zhangyong15** [PaddlePaddle/Paddle#1323]
模型已训练好，涉及sparse_update, 参照相关issue #364，训练时sparse_update=True,  预测时sparse_update=False，

测试样本共有100w+，本地cpu模式，predict运行到16w左右，就退出了。报错如下
![2017-02-13 2 20 08](https://cloud.githubusercontent.com/assets/22140712/22873019/206461b0-f1f8-11e6-92cd-4b774f6b73d0.png)

 
每次运行，退出的条数都不大相同，有的一条ins都无法predict，有的可以达到10w多才退出。

**Comment by qingqing01** [comment]
如果是测试，请关闭数据的shuffle，首先检查数据是否有问题~

**Comment by zhangyong15** [comment]
数据并无shuffle，训练集和测试集完全一致。

**Comment by NHZlX** [comment]
I'll close the inactivate issue, and feel free to reopen it.
