### ISSUE TITLE
fetch_var接口失效了吗？

### ISSUE THREAD

**Issue by zzhzz** [PaddlePaddle/Paddle#13248]
我编译当前版本的paddle，发现使用fetch_var接口报错 
> AttributeError: 'module' object has no attribute 'fetch_var'
请问目前想要从神经网络中获取一个Tensor的Numpy数组值该怎么办呢？

**Comment by typhoonzero** [comment]
`fetch_var`接口在新版中已经隐藏，请使用在`exe.run(fetch_list=[vars to fetch])`在`exe.run`中增加需要fetch的variable
