### ISSUE TITLE
使用nce训练失败

### ISSUE THREAD

**Issue by bhan1111** [PaddlePaddle/Paddle#13242]
fluid 0.15.0版本
任务local模式可以跑通
使用paddlecloud提交后，任务链接http://10.182.22.147:8900/fileview.html?path=/home/disk1/normandy/maybach/app-user-20180905155251-6051/
会报
<img width="1225" alt="default" src="https://user-images.githubusercontent.com/29255596/45079619-9cf4df00-b125-11e8-9c98-20ff73d53c3e.png">
这样的错误，不知原因

**Comment by typhoonzero** [comment]
错误：`Tensor nce_0.tmp_0 contains Inf` 如果是同步集群batch size是单机的n倍，单机能收敛的情况集群不一定，可以适当调整参数重新训练，或者如果本地内存较大可以先在本地测试大batch size的情况

**Comment by bhan1111** [comment]
但是我只用了一个节点训练啊 batch size设置为100

**Comment by bhan1111** [comment]
INF表示无穷大还是无穷小呢？

**Comment by typhoonzero** [comment]
是无穷大。这个问题得具体看下，如果是单pserver，单trainer，是和local模式训练是完全一致的才对。可以加一些print layer看具体是哪些层会有INF

**Comment by typhoonzero** [comment]
和用户沟通，在local跑的时候，loss也会为INF，只不过不会挂，此为版本问题。有INF也没必要继续run下去了

**Comment by lucywsq** [comment]
您好，此issue在近一个月内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题， 我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持!
