### ISSUE TITLE
怎么把训练好的一个模型封装

### ISSUE THREAD

**Issue by lianqingsong** [PaddlePaddle/Paddle#13245]
请问，自己训练好的一个模型，怎么样才能把这个模型放在一个没有paddlepaddle框架的平台，直接调用

**Comment by typhoonzero** [comment]
不确定是否是你需要的： https://github.com/PaddlePaddle/book/tree/develop/serve

**Comment by lianqingsong** [comment]
@typhoonzero 谢谢(･ω･)ﾉ，好像不是呢。我需要的是把自己训练好的模型，封装好，比如说图片分类的模型吧，把这个模型训练出来了。封装好模型，给别人用。别人输入一张图片进去，这个模型就反馈出分类结果。

**Comment by typhoonzero** [comment]
上面的例子就是用http方式封装了一个服务，同样也可以类似的封装一个API，SDK或者其他形式。吧inference的代码包装一下就行

**Comment by lianqingsong** [comment]
@typhoonzero  哇，不好意思，上面的例子看着不是很懂，不明白，您能详细的说一下嘛_(:з」∠)_

**Comment by typhoonzero** [comment]
可以看link里的README已经有详细说明了。如果是封装inference，请参考：https://github.com/PaddlePaddle/book/blob/develop/02.recognize_digits/train.py#L128

**Comment by lianqingsong** [comment]
@typhoonzero  好的  谢谢了

**Comment by lucywsq** [comment]
您好，此issue在近一个月内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题， 我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持!
