### ISSUE TITLE
clang: error: no such file or directory: 'Paddle_wrap.cxx'

### ISSUE THREAD

**Issue by wangke-tech** [PaddlePaddle/Paddle#1327]
Hi there,

When I try to install paddle using setup.py, bugs ocurr as following. Where is "Paddle_wrap.cxx" that is mentioned in setup.py at 62nd Line.

What should I do?

Looking Forward to ur reply!

thx.

> Leon-2:paddle Michael$ sudo python setup.py install
running install
Checking .pth file support in /Library/Python/2.7/site-packages/
/usr/bin/python -E -c pass
TEST PASSED: /Library/Python/2.7/site-packages/ appears to support .pth files
running bdist_egg
running egg_info
writing requirements to py_paddle.egg-info/requires.txt
writing py_paddle.egg-info/PKG-INFO
writing top-level names to py_paddle.egg-info/top_level.txt
writing dependency_links to py_paddle.egg-info/dependency_links.txt
reading manifest file 'py_paddle.egg-info/SOURCES.txt'
writing manifest file 'py_paddle.egg-info/SOURCES.txt'
installing library code to build/bdist.macosx-10.11-intel/egg
running install_lib
running build_py
running build_ext
building 'py_paddle._swig_paddle' extension
cc -fno-strict-aliasing -fno-common -dynamic -g -Os -pipe -fno-common -fno-strict-aliasing -fwrapv -DENABLE_DTRACE -DMACOSX -DNDEBUG -Wall -Wstrict-prototypes -Wshorten-64-to-32 -DNDEBUG -g -fwrapv -Os -Wall -Wstrict-prototypes -DENABLE_DTRACE -pipe -arch x86_64 -I/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/numpy/core/include -I../ -I/System/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7 -I/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/numpy/core/include -I../ -I/System/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7 -c Paddle_wrap.cxx -o build/temp.macosx-10.11-intel-2.7/Paddle_wrap.o
clang: error: no such file or directory: 'Paddle_wrap.cxx'
clang: error: no input files
error: command 'cc' failed with exit status 1

**Comment by gangliao** [comment]
Do you follow the docs to compile the code firstly?
https://github.com/PaddlePaddle/Paddle/blob/develop/doc/getstarted/build_and_install/build_from_source_en.md

Basically, you need to compile the source code via cmake, it will invoke SWIG to generate the corresponding python wrapper 'Paddle_wrap.cxx' and packaging all python code and shared libraries in wheel package.

Finally, you can install it via `pip install xxx.whl`

@wangke-tech

**Comment by gangliao** [comment]
no update, I closed this issue. New comments are welcome.
