### ISSUE TITLE
Pyramidbox 有官方训练的模型可以使用吗

### ISSUE THREAD

**Issue by zhengzhe97** [PaddlePaddle/Paddle#13274]

**Comment by qingqing01** [comment]
@zhengzhe97 感谢关注，我们最近会release模型，预计下周内吧。多谢~  
另外，您也可以尝试训练： https://github.com/PaddlePaddle/models/tree/develop/fluid/face_detection

**Comment by zhengzhe97** [comment]
@qingqing01 好的谢谢

**Comment by zhengzhe97** [comment]
@qingqing01 请问具体周几能发布模型吗，我的1080 batch只能设置成1，在训练有几张图时就会出现梯度爆炸的情况，很艰难= =，

**Comment by qingqing01** [comment]
@zhengzhe97 昨天已经模型整理好，今天可以发布。 另外，我们文档里提供了VGG的初始化模型链接吧。

**Comment by zhengzhe97** [comment]
@qingqing01 我使用了提供的vgg初始化模型，训练时误差平均在5-12之间，但是可能是batch为1的缘故，在部分图片上误差较大，导致出现梯度爆炸的情况。（我认为是这样= =，）
![image](https://user-images.githubusercontent.com/26462054/45333660-f471cf80-b5a9-11e8-93ea-69405c24dfe0.png)

**Comment by qingqing01** [comment]
@zhengzhe97 

PyramidBox模型链接： http://paddlemodels.bj.bcebos.com/PyramidBox_WiderFace.tar.gz

**Comment by lucywsq** [comment]
您好，此issue在近一个月内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题， 我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持!
