### ISSUE TITLE
fluid 现在支持 focal_loss 么？

### ISSUE THREAD

**Issue by youngstu** [PaddlePaddle/Paddle#13289]
fluid 现在能否支持 focal_loss ? 如果没有，能否写一个python 扩展，类似pytorch ?

**Comment by kuke** [comment]
暂时不支持 但是可以用现有的layers或ops拼出来

**Comment by lucywsq** [comment]
您好，此issue在近一个月内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题， 我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持!
