### ISSUE TITLE
单机多GPU 训练怎样设置？

### ISSUE THREAD

**Issue by youngstu** [PaddlePaddle/Paddle#13297]
单击多GPU 训练模型怎样设置， 需要设置CUDA_VISIBLE_DEVICES 和 CUDAPlace 么？

CUDAPlace(0) 有接口文档说明么，官网上没有介绍。和paddle v2 API不一样。

**Comment by kolinwei** [comment]
你好，设置CUDA_VISIBLE_DEVICES 即可，比如有8张GPU卡，
可以设置CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7

**Comment by youngstu** [comment]
是否还需要设置CUDAPlace 等参数呢， pytorch 还需要设置 `self.model = torch.nn.DataParallel(self.model, [0,1,2,3])`

CUDA_VISIBLE_DEVICES=CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 我尝试过会出错，但是只设置CUDA_VISIBLE_DEVICES=7 没有问题，可以正常运行。

**Comment by kolinwei** [comment]
你好，你的机器有几张gpu卡呢，能贴下nvidia-smi执行的结果吗

**Comment by youngstu** [comment]
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 384.81                 Driver Version: 384.81                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla P40           On   | 00000000:00:0A.0 Off |                    0 |
| N/A   23C    P8    10W / 250W |     10MiB / 22912MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   1  Tesla P40           On   | 00000000:00:0B.0 Off |                    0 |
| N/A   25C    P8    10W / 250W |     10MiB / 22912MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   2  Tesla P40           On   | 00000000:00:0C.0 Off |                    0 |
| N/A   22C    P8     9W / 250W |     10MiB / 22912MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   3  Tesla P40           On   | 00000000:00:0D.0 Off |                    0 |
| N/A   22C    P8     9W / 250W |     10MiB / 22912MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   4  Tesla P40           On   | 00000000:00:0E.0 Off |                    0 |
| N/A   42C    P0    51W / 250W |    943MiB / 22912MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   5  Tesla P40           On   | 00000000:00:0F.0 Off |                    0 |
| N/A   37C    P0    51W / 250W |    933MiB / 22912MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   6  Tesla P40           On   | 00000000:00:10.0 Off |                    0 |
| N/A   39C    P0    51W / 250W |    933MiB / 22912MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   7  Tesla P40           On   | 00000000:00:11.0 Off |                    0 |
| N/A   25C    P0    49W / 250W |    175MiB / 22912MiB |      0%      Default |

**Comment by youngstu** [comment]
```
    if parallel:
        train_exe = fluid.ParallelExecutor(
            use_cuda=use_gpu, loss_name=loss.name)
```
```
if not parallel:
        cost, acc, prediction = network(data, label, len(word_dict))
    else:
        places = fluid.layers.device.get_places(device_count=2)
        pd = fluid.layers.ParallelDo(places)
        with pd.do():
            cost, acc, prediction = network(
                pd.read_input(data), pd.read_input(label), len(word_dict))

            pd.write_output(cost)
            pd.write_output(acc)

        cost, acc = pd()
        cost = fluid.layers.mean(cost)
        acc = fluid.layers.mean(acc)
```

以上两种多卡运行的方式有什么区别？

**Comment by kolinwei** [comment]
新的版本不推荐使用ParallelDo，统一用ParallelExecutor吧

**Comment by youngstu** [comment]
使用PallelExecutor 无法使用多卡，当设置CUDA_VISIBLE_DEVICES 为多个时报错

**Comment by youngstu** [comment]
```
*** Aborted at 1536731055 (unix time) try "date -d @1536731055" if you are using GNU date ***
PC: @                0x0 (unknown)
*** SIGSEGV (@0x0) received by PID 16155 (TID 0x7f557a4a3740) from PID 0; stack trace: ***
    @       0x38c040f130 (unknown)
    @                0x0 (unknown)
```

**Comment by youngstu** [comment]
没与任何有效信息，都不知道哪里有问题

**Comment by youngstu** [comment]
我跑的模型是 models/fluid/object_detection/mobilenet_ssd

**Comment by kolinwei** [comment]
你好，我跑是可以的，能贴下完整的错误吗

**Comment by youngstu** [comment]
```
(paddle_v014) [xx@xxxxxxxxxxxx v11_fluid_mobilenet_ssd]$ tailf -n 50 train.log
-----------  Configuration Arguments -----------
ap_version: 11point
apply_distort: True
apply_expand: True
batch_size: 12
dataset: coco2017
is_toy: 0
learning_rate: 0.001
mean_value_B: 103.94
mean_value_G: 116.78
mean_value_R: 123.68
model_save_dir: model
nms_threshold: 0.45
num_passes: 120
parallel: 1
pretrained_model: 
resize_h: 300
resize_w: 300
use_gpu: True
------------------------------------------------
-----------------------begin
/ssd2/xxx/envs/vrts/paddle_v014/lib/python2.7/site-packages/paddle/fluid/evaluator.py:69: Warning: The DetectionMAP is deprecated, because maintain a modified program inside evaluator cause bug easily, please use fluid.metrics.DetectionMAP instead.
  % (self.__class__.__name__, self.__class__.__name__), Warning)
-----------------------dataset
-----------------------optimizer
-----------------------run
-----------------------model
*** Aborted at 1536731055 (unix time) try "date -d @1536731055" if you are using GNU date ***
PC: @                0x0 (unknown)
*** SIGSEGV (@0x0) received by PID 16155 (TID 0x7f557a4a3740) from PID 0; stack trace: ***
    @       0x38c040f130 (unknown)
    @                0x0 (unknown)
^C
[1]+  Exit 139                nohup sh train.sh
```

**Comment by youngstu** [comment]
```
#!/bin/bash

#env CUDA_VISIBLE_DEVICES=0,1,2,3 FLAGS_fraction_of_gpu_memory_to_use=1.0 python -u train.py \
env CUDA_VISIBLE_DEVICES=0,1,2,3 python -u train.py \
--parallel=True \
--dataset='coco2017' \
--pretrained_model='' \
>& train.log
```
这是我的train.sh，当设置单卡时可以正常运行，当设置多卡报错如上

**Comment by kolinwei** [comment]
GLOG_v=3 python -u train.py
这样运行 我看下完整的错误

**Comment by youngstu** [comment]
```
(paddle_v014) [xxx@xxxxxxxxxxxxxxx v11_fluid_mobilenet_ssd]$ tailf -n 50 train.log
WARNING: Logging before InitGoogleLogging() is written to STDERR
I0912 19:29:30.210608 27225 init.cc:44] Init commandline: dummy train.py --tryfromenv=use_pinned_memory,check_nan_inf,benchmark,warpctc_dir,eager_delete_scope,use_mkldnn,initial_cpu_memory_in_mb,fraction_of_gpu_memory_to_use,cudnn_deterministic 
-----------  Configuration Arguments -----------
ap_version: 11point
apply_distort: True
apply_expand: True
batch_size: 12
dataset: coco2017
is_toy: 0
learning_rate: 0.001
mean_value_B: 103.94
mean_value_G: 116.78
mean_value_R: 123.68
model_save_dir: model
nms_threshold: 0.45
num_passes: 120
parallel: 1
pretrained_model: 
resize_h: 300
resize_w: 300
use_gpu: True
------------------------------------------------
-----------------------begin
/ssd2/xxxx/envs/vrts/paddle_v014/lib/python2.7/site-packages/paddle/fluid/evaluator.py:69: Warning: The DetectionMAP is deprecated, because maintain a modified program inside evaluator cause bug easily, please use fluid.metrics.DetectionMAP instead.
  % (self.__class__.__name__, self.__class__.__name__), Warning)
-----------------------dataset
-----------------------optimizer
-----------------------run
-----------------------model
*** Aborted at 1536751779 (unix time) try "date -d @1536751779" if you are using GNU date ***
PC: @                0x0 (unknown)
*** SIGSEGV (@0x0) received by PID 27225 (TID 0x7fcc4aedb740) from PID 0; stack trace: ***
    @       0x38c040f130 (unknown)
    @                0x0 (unknown)
^C
[1]+  Exit 139                nohup sh train.sh
```
并没有打印出完整的更多错误系信息

**Comment by kolinwei** [comment]
这样沟通效率太低，加我hi吧，kolinwei

**Comment by lucywsq** [comment]
您好，鉴于此问题已解决，我们将于今天内先行关闭，若后续有更新追问您随时reopen，感谢您对PaddlePaddle的支持！

**Comment by molly00ecla** [comment]
您好！是怎样解决的呢？遇到同样的问题。

**Comment by Ezra-Yu** [comment]
怎么解决啊？这里没说清楚啊

**Comment by haileewu** [comment]
同问。。为什么不说清楚呢。。
