### ISSUE TITLE
如何基于ImageNet数据训练

### ISSUE THREAD

**Issue by gaoshan2006** [PaddlePaddle/Paddle#1329]
我想使用ImageNet 的数据训练VGGNet 模型, 请问改如何去做?
我现在的操作如下: 
1)下载并解压 ILSVRC2012_img_train 的数据,, 将训练数据放在/data/ILSVRC2012_img_train_paddle/train 目录下,   
2) 修改 demo/image_classification/preprocess.sh 脚本的路径,, 改为如下

data_dir=/data/ILSVRC2012_img_train_paddle
python preprocess.py -i $data_dir -s 32 -c 1
echo "/data/ILSVRC2012_img_train_paddle/batches/train.txt" > train.list
echo "/data/ILSVRC2012_img_train_paddle/batches/test.txt" > test.list
3) 然后运行 demo/image_classification/preprocess.sh  想仿照原来的脚本做预处理 生成相关list file, 结果就看到如下错误

Traceback (most recent call last):
  File "preprocess.py", line 54, in <module>
    data_creator.create_batches()
  File "/usr/lib/python2.7/site-packages/paddle/utils/preprocess_util.py", line 352, in create_batches
    self.keys.index(self.permutate_key), self.num_per_batch)
  File "/usr/lib/python2.7/site-packages/paddle/utils/preprocess_util.py", line 147, in permute
    self.permute_by_key(key_id, num_per_batch)
  File "/usr/lib/python2.7/site-packages/paddle/utils/preprocess_util.py", line 172, in permute_by_key
    math.ceil(num_per_batch / float(len(keyvalue_indices.keys())))
ZeroDivisionError: float division by zero

请问我想使用ImageNet 的数据训练VGGNet 模型, 我该如何做? 有个文挡或具体步骤吗?  谢谢

**Comment by qingqing01** [comment]
@gaoshan2006  demo/image_classification/preprocess.sh 这个demo处理数据时实际对数据格式有一定的要求。  我比较建议你，先理解PaddlePaddle的DataProvider提供数据的使用方法，理解了之后，其实可以不参考这个demo处理数据。 最简单的使用方法是：
1.  将train数据准备成一个数据list，形式类似：

```
n01440764/n01440764_10026.JPEG 0  # 即图片路径 label
n01440764/n01440764_10027.JPEG 0  
...
```

2. 在dataprovider中依据这个list，使用PIL读取图片，可以参考这个dataprovider的写法即可
https://github.com/qingqing01/ImageModel/blob/master/resnet_imagenet_100/paddle/provider.py

训练完整可以过程可以参考下面链接
https://github.com/qingqing01/ImageModel/tree/master/resnet_imagenet_100/paddle

ps: 然后如果对读数据的速度有进一步的要求，可以再继续优化dataprovider，可以使用Python多进程加速 https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/utils/image_multiproc.py， 或者 https://github.com/PaddlePaddle/Image 一个C++的库都可以。  如果你已经对dataprovider用法熟悉了，对速度有要求，可以考虑这部分加速， 有问题我们可以再讨论。

**Comment by gaoshan2006** [comment]
谢谢. 按照您的这个方法, 我现在先生成了list,  按照这里的代码, 运行, https://github.com/qingqing01/ImageModel/tree/master/resnet_imagenet_100/paddle
但是出现错误 
Python Error: <type 'exceptions.IndexError'> : too many indices for array
Python Callstack: 
            /export/Paddle_image_classfication/ImageModel/resnet_imagenet_100/paddle/provider.py : 62

我看下代码 , 是**img = img[[2,1,0],:,:]** 这行,  请问需要怎么解决? 谢谢
def processPIL(settings, file_list):
    with open(file_list, 'r') as fdata:
        lines = [line.strip() for line in fdata]
        random.shuffle(lines)
        for line in lines:
            img_path, lab = line.strip().split('\t')
            img = Image.open(img_path)
            img.load()
            img = image_util.resize_image2(img, settings.resize_size)
            img = np.array(img)
            if len(img.shape) == 3:
                img = np.swapaxes(img, 1, 2)
                img = np.swapaxes(img, 1, 0)
            **img = img[[2,1,0],:,:]**
            img_feat= image_util.preprocessImg(settings, img)
            yield int(lab.strip()), img_feat.astype('float32')

**Comment by qingqing01** [comment]
@gangliao  先调试一下在这行之前的数据是否有读取成功，就是Image.open()是否有成功，一步步看下~

**Comment by gaoshan2006** [comment]
贴上全部错误信息
....................................
[INFO 2017-02-15 05:09:40,556 provider.py:43] Image resize size: 256
[INFO 2017-02-15 05:09:40,557 provider.py:44] Crop size: 224
[INFO 2017-02-15 05:09:40,557 provider.py:45] DataProvider Initialization finished
I0215 05:09:40.558902 29964 PyDataProvider2.cpp:257] loading dataprovider provider::processPIL
[INFO 2017-02-15 05:09:40,559 provider.py:43] Image resize size: 256
[INFO 2017-02-15 05:09:40,559 provider.py:44] Crop size: 224
[INFO 2017-02-15 05:09:40,559 provider.py:45] DataProvider Initialization finished
I0215 05:09:40.560099 29964 GradientMachine.cpp:134] Initing parameters..
I0215 05:09:44.022426 29964 GradientMachine.cpp:141] Init parameters done.
F0215 05:09:46.908895 30032 PythonUtil.h:345] Check failed: (data) != nullptr Current PYTHONPATH: ['/opt/paddle-bin/opt/paddle/bin', '/usr/lib64/python2.7/site-packages/numpy-1.11.0-py2.7-linux-ppc64le.egg', '/usr/lib64/python2.7/site-packages/mxnet-0.9.3-py2.7-linux-ppc64le.egg', '/usr/lib/python2.7/site-packages/protobuf-3.1.0-py2.7.egg', '/usr/lib/python2.7/site-packages/six-1.10.0-py2.7.egg', '/export/Paddle_image_classfication/ImageModel/resnet_imagenet_100/paddle', '/usr/lib64/python27.zip', '/usr/lib64/python2.7', '/usr/lib64/python2.7/plat-linux2', '/usr/lib64/python2.7/lib-tk', '/usr/lib64/python2.7/lib-old', '/usr/lib64/python2.7/lib-dynload', '/usr/lib64/python2.7/site-packages', '/usr/lib64/python2.7/site-packages/gtk-2.0', '/usr/lib/python2.7/site-packages']
Python Error: <type 'exceptions.IndexError'> : too many indices for array
Python Callstack: 
            /export/Paddle_image_classfication/ImageModel/resnet_imagenet_100/paddle/provider.py : 62
Calling iterator next error
*** Check failure stack trace: ***
    @     0x3fff9c36d2ac  google::LogMessage::Fail()
    @     0x3fff9c36fdec  google::LogMessage::SendToLog()
    @     0x3fff9c36cc9c  google::LogMessage::Flush()
    @     0x3fff9c3709d4  google::LogMessageFatal::~LogMessageFatal()
    @         0x102ba0f8  paddle::PyDataProvider2::loadThread()
    @         0x102ba4ec  _ZNSt6thread5_ImplISt12_Bind_simpleIFZN6paddle15PyDataProvider29resetImplEbEUlvE_vEEE6_M_runEv
    @     0x3fff9c28c174  (unknown)
    @     0x3fff9d828728  start_thread
    @     0x3fff9bf9d210  __clone
/opt/paddle-bin/bin/paddle: line 109: 29964 Aborted                 (core dumped) ${DEBUGGER} $MYDIR/../opt/paddle/bin/paddle_trainer ${@:2}

**Comment by gaoshan2006** [comment]
我search 到一个类似的错误, https://github.com/PaddlePaddle/Paddle/issues/1272  不知道是否他们相关.
另外如果是同样的问题, 那个错误是在 dataprovider.py里面,  现在这个是在provider.py里面, 不知道修改是否一样?  谢谢

**Comment by qingqing01** [comment]
这两个没有关系，我觉得还是你数据没有组织好， 

https://github.com/qingqing01/ImageModel/tree/master/resnet_imagenet_100/paddle  这个里面数据组织方式，不知道你有没有注意到：

train.list:
```
./data/train.txt
```
train.txt 里才是图片路径和label，并且 \t分割。 不知道你是否这样组织？

provider.py文件是可以调试的，你可以多打印些信息，看看下面两行是否正确。

```
 img_path, lab = line.strip().split('\t')
 img = Image.open(img_path)
```

**Comment by gaoshan2006** [comment]
我的就是在train.txt 中,  把文件和label 使用 \t 分割的.   
我打印 log 了,  发现有一些文件已经被处理过了,  但运行一会儿就出错了,  而且每次错误还不在同一个文件上,

**Comment by qingqing01** [comment]
是这张图片Image.open()就没有被正确打开？

**Comment by gaoshan2006** [comment]
不是open().  出错的时候,  已经得到图片的大小尺寸  已经可以输出图片的大小尺寸了

**Comment by qingqing01** [comment]
```
            img = np.array(img)   # 将PIL读取的Image转换为numpy array
            if len(img.shape) == 3:   # 如果是RGB 3通道图，PIL读取的图片是 H W C的顺序， 下面将其转换为C H W的顺序
                img = np.swapaxes(img, 1, 2)
                img = np.swapaxes(img, 1, 0)
            img = img[[2,1,0],:,:]   # RGB -> BGR转换， 依然是C H W通道， 这步可以没有的
            # 上面这些都是基于彩色图的
```
如果是  img = img[[2,1,0],:,:]  这行不对，你可以针对你的数据更改呀~

**Comment by gaoshan2006** [comment]
可是我使用的数据集合就是 imagenent ILSVRC-2012, 他就是RGB 啊

**Comment by tensor-tang** [comment]
@gaoshan2006 我之前碰到过类似问题，我发现的其实是，imagedata里面有些图片虽然看的时候是RGB的，但是实际用py去读的时候，有的shape不为3，估计跟图片格式或者py的library有关，anyway， 我用最笨的做法：把所有的图片用这种方式读一遍，丢掉shape不为3的图片，其实没有很多张，然后用复合要求的list train就没问题了

**Comment by gaoshan2006** [comment]
@tensor-tang 谢谢。我回头按照 你的办法试一下，多谢多谢！
