### ISSUE TITLE
Output of int type cannot be handled by Paddle inference API

### ISSUE THREAD

**Issue by wojtuss** [PaddlePaddle/Paddle#13298]
https://github.com/PaddlePaddle/Paddle/blob/f76f42c2e021ff81113beb4c1e46e6892a40944f/paddle/fluid/inference/api/paddle_inference_api.h#L31
https://github.com/PaddlePaddle/Paddle/blob/f76f42c2e021ff81113beb4c1e46e6892a40944f/paddle/fluid/inference/api/api_impl.cc#L272

Current version of Paddle inference API does not allow to handle the output of `int` type, for example from `ResNet50` model.

**Comment by luotao1** [comment]
We can support INT64 output type.
https://github.com/PaddlePaddle/Paddle/blob/f76f42c2e021ff81113beb4c1e46e6892a40944f/paddle/fluid/inference/api/api_impl.cc#L286-L289
This is the example of INT64 output type.
https://github.com/PaddlePaddle/Paddle/blob/f980b29e6259b8e51f4ee04260e3a84233f337df/paddle/fluid/inference/analysis/analyzer_ner_tester.cc#L164

**Comment by wojtuss** [comment]
@luotao1 , true, but when the model output type is `int`, and not `int64_t`, one gets the following error:
```
E0910 11:42:46.542758 47709 api_impl.cc:290] unknown type, only support float32 and int64 now.
```

**Comment by wojtuss** [comment]
@luotao1, what do you think? I still consider it a flaw.

**Comment by luotao1** [comment]
why do you need it?  Currently, the inference output of our model is either `int64_t` or `float32`.

**Comment by wojtuss** [comment]
I was using an older version of a python script for ResNet50 inference and one of the otputs was `int`. Now I have updated the script to the current public version and everything is fine.
Thanks!
