### ISSUE TITLE
comment says there is no FC operator

### ISSUE THREAD

**Issue by sfraczek** [PaddlePaddle/Paddle#13302]
https://github.com/PaddlePaddle/Paddle/blob/f980b29e6259b8e51f4ee04260e3a84233f337df/paddle/fluid/framework/ir/fc_fuse_pass.cc#L49

What do you mean there is no FC available? There is `fc_op` AFAIK.

**Comment by sfraczek** [comment]
Does this mean this pass doesn't actually work?

**Comment by Superjomn** [comment]
I am working on a PR, that will remove this out-dated comment.

Currently, we have FC fuse works on the real models.

**Comment by sfraczek** [comment]
Thanks.  👍
