### ISSUE TITLE
paddle V2， mpi训练，trainer_count=1速度比trainer_count大于1要快

### ISSUE THREAD

**Issue by 333caowei** [PaddlePaddle/Paddle#13300]
版本如下：
PaddlePaddle 0.14.0, compiled with
    with_avx: ON
    with_gpu: OFF
    with_mkl: ON
    with_mkldnn: ON
    with_double: OFF
    with_python: ON
    with_rdma: OFF
    with_timer: OFF

使用20个mpi节点，通过下述代码打印环境变量：
`
print(
    "PADDLE_TRAINER_COUNT %s" % os.getenv("PADDLE_TRAINER_COUNT", "1"),
    "PADDLE_PORT: %s" % os.getenv("PADDLE_PORT", "7164"),
    "PADDLE_PORTS_NUM: %s" % os.getenv("PADDLE_PORTS_NUM", "1"),
    "PADDLE_PORTS_NUM_FOR_SPARSE: %s" % os.getenv("PADDLE_PORTS_NUM_FOR_SPARSE", "1"),
    "PADDLE_NUM_GRADIENT_SERVERS: %s" % os.getenv("PADDLE_NUM_GRADIENT_SERVERS", "1"),
    "PADDLE_TRAINER_ID: %s" % os.getenv("PADDLE_TRAINER_ID", "0"),
    "PADDLE_PSERVERS : %s" % os.getenv("PADDLE_PSERVERS", "127.0.0.1")
)
`

PADDLE_TRAINER_COUNT=1
PADDLE_PORT=1
PADDLE_PORTS_NUM=1
PADDLE_PORTS_NUM_FOR_SPARSE=1
PADDLE_NUM_GRADIENT_SERVERS=20
PADDLE_PSERVERS：有20个ip地址

通过结合训练速度以及cpu idel观察发现：
当trainer_count=1，idle约85，这时候训练速度最快
当trainer_count=28时候（机器有28个物理核），idle约70，这时候训练速度不及上面trainer_count=1
当trainer_count=56时候（机器有28个物理核），idle约50，这时候训练速度不及上面trainer_count=28

从网卡流量观察也可发现：
trainer_count=1的流量>trainer_count=28的流量>trainer_count=56的流量

**Comment by lucywsq** [comment]
感谢您的建议~我们已经记录并关注。同时建议您将代码迁移至Fluid，未来V2版本将不进行后续维护。
此issue在近一个月内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题，
我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持!
