### ISSUE TITLE
如何从GradientMachine中获取每一层的输出？

### ISSUE THREAD

**Issue by reyoung** [PaddlePaddle/Paddle#1330]
Paddle的GradientMachine包含了多个Neural Network。之所以包含多个NeuralNetwork的原因是:

* Paddle在单机运行时，实际上是多设备数据并行的方式做训练。所以，对不同的设备，都会有一个NeuralNetwork
* Paddle在RNN实现时，实际上对于RNN每一个时间步，都是一个子NeuralNetwork。

所以，如果要获得某一个Layer的输出(Activation)。那么就需要遍历一个GradientMachine中包含的所有Neural Network。再从其中获得这个层的输出。

所以我们是不是应该给GradientMachine添加一个遍历所有子NeuralNetwork的接口？

例如:

```cpp
class GradientMachine {
public:
    void accessSubGradientMachine(const std::function<void(const GradientMachine&)>& callback);
}
```

### 术语表

* GradientMachine: Paddle用来计算forward和backward的统一接口。可以处理单机多GPU，多CPU的数据并行问题
* NeuralNetwork: Paddle在某个设备上实际的执行计算任务的对象。

**Comment by hedaoyuan** [comment]
Paddle的数据并行，除了每个`TrainerThread`有一个`NeuralNetwork`外，`MultiGradientMachine`也有一个[`NeuralNetwork`](https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/gserver/gradientmachines/MultiGradientMachine.cpp#L92)。

>所以，如果要获得某一个Layer的输出(Activation)。那么就需要遍历一个GradientMachine中包含的所有Neural Network。再从其中获得这个层的输出。
> 所以我们是不是应该给GradientMachine添加一个遍历所有子NeuralNetwork的接口？

并不需要对外暴露遍历每个子`NeuralNetwork`的接口，比如需要获取每个Layer的output，可以在`MultiGradientMachine`里面将多个部分的输出merge到`MultiGradientMachine`的`NeuralNetwork`上，这样外面用起来感觉还是一个`NeuralNetwork`。

**Comment by luotao1** [comment]
@hedaoyuan 
> 可以在MultiGradientMachine里面将多个部分的输出

这里你说的输出，是指`MultiGradientMachine::getOutArgs`这个[函数](https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/gserver/gradientmachines/MultiGradientMachine.cpp#L341)么?

**Comment by gangliao** [comment]
看了这一部分的代码，我想主要逻辑应该是：

GradientMachine在trainer_count > 1, 调用multiGradientMachine, multiGradientMachine内部通过有trainerThread(其数量thread_num_ = trainer_count),  执行单机多卡数据并行。

trainerThread之间采用GPU环形通信，进行更新。

看样子Paddle里面有类似的实现
```c++
void MultiGradientMachine::getOutArgs(std::vector<Argument>* outArgs,
                                      PassType passType) {
  for (auto& thread : threads_) {
    REGISTER_TIMER("waitOutArgs");
    thread->waitOutArgsReady();
  }
  outArgs_.resize(threads_[0]->getOutArgs().size());

  REGISTER_TIMER("copyOutArgs");
  for (size_t i = 0; i < outArgs_.size(); ++i) {
    std::vector<Argument> args;
    args.reserve(threads_.size());
    for (auto& thread : threads_) {
      args.push_back(thread->getOutArgs()[i]);
    }
    outArgs_[i].concat(args, useGpu_, outArgStream_, passType);
  }

  if (useGpu_) {
    hl_stream_synchronize(outArgStream_);
  }

  *outArgs = outArgs_;
}
```

**Comment by luotao1** [comment]
> 看样子Paddle里面有类似的实现，但不确定能不能具体到某一层layer.

在GradientMachine的一个子类NeuralNetwork（使用于单线程，即trainer_count=1）中，是可以到具体的某一层的。
```
MatrixPtr NeuralNetwork::getLayerOutput(const std::string& layerName) {
  auto it = layerMap_.find(layerName);
  CHECK(it != layerMap_.end()) << "Cannot find layer: " << layerName;
  return it->second->getOutputValue();
}
```

所以在MultiGradientMachine中，可以也实现一个getlayerOutput函数。

**Comment by gangliao** [comment]
通过聚合多个train_thread的某个layer的输出，应该就行了

```
out = trainer_thread_[i]->NeuralNetwork-> getLayerOutput(layername)
```
