### ISSUE TITLE
关于[book]个性化推荐网络结构的一些疑问

### ISSUE THREAD

**Issue by HugoLian** [PaddlePaddle/Paddle#1331]
来源：
http://book.paddlepaddle.org/recommender_system/
在看完这个网络结构后，有三个问题想请教：

1）比如gender只有男女两个值，但是在网络结构中，还是把它映射成了256维的向量，这么做的意义是什么呢？
```
embsize = 256
gender_emb = embedding_layer(input=gender, size=embsize)
gender_hidden = fc_layer(input=gender_emb, size=embsize)
```

2）我不是很熟悉embedding_layer，可以理解成embedding_layer的作用，基本都是把一个维度很大离散的输入，映射程固定长度的词向量，且词向量之间的距离可以表示原始输入的相似度？

3）模型输出是cos（向量a, 向量b），这个值是[-1, 1]那为什么最后会输出4.25的分数？
![image](https://cloud.githubusercontent.com/assets/22980558/22918279/889f7de2-f2c4-11e6-8b33-93d9077b2fe7.png)
如果是做了映射，我看用原始[-2, 2]的rating，和cos[-1, 1]之间做 regression_cost效果好么？为什么不把原始rating得分直接映射到[-1, 1]之间？
![image](https://cloud.githubusercontent.com/assets/22980558/22918330/d03a5898-f2c4-11e6-9807-254e8cb9d8c9.png)

**Comment by lcy-seso** [comment]
谢谢你的问题~

（1） 和 （2）这两个问题，可以合并起来一起回答。

+ 词向量更多的解释，和如何在实际问题中使用，我们在 PaddleBook 中有 “[词向量](http://book.paddlepaddle.org/word2vec/)” 这一章，可以参考；
+ paddle 中的 embedding_layer 会学习一个实数矩阵，这个矩阵是一个大的词表，矩阵的每一列是为字典中每一个词语学习到的一个 dense 表示，通常大家会提到 distribute representation 这个概念（如果感兴趣，可以以此为关键字搜索到很多资料）。 
+ distribute representation 核心大体上有两个作用：（1）对抗维数灾难，假如我们只使用 0，1 这样简单的离散变量，一个离散的二维向量只能编码4种信息，但是如果我们使用二维连续的实向量，却能够编码理论上无穷种信息 ，也就是说实向量空间的表达能力是远远大于离散向量空间，使得我们可以用更低的维度，编码更多的信息，来缓解计算的压力；（2）学习好的词向量，是高维实向量空间中的一个点，于是我们可以通过实向量空间的数学特性，或者其实定义的一些数学操作，来刻画语言在语义层面的一些复杂性。比如大家常用的例子，通过距离运算度量词义的相似性（也就是你的第二个问题）。

（3）这个问题，paddle 的cos 有一个scale，默认是5（你可以确认一下），scale .* [-1, +1]来改变cos 本身的scale。

**Comment by lcy-seso** [comment]
（1）里面提到 gender 属性只有2个值，但是却为这两个值分别学习了 embedding。说说我的理解。

这个是一种较为少用的非典型情况，embedding 在这种情况下，作用可能不太大，embedding_layer 的引入，多了参数，相当于对原始的离散输入特征做了一个新的特征表示转化，而这个表示是网络自己学习到的。

如果是从拟合数据的角度，用BOW特征， 多增加几个 fc layer，应该也是可以拟合地住（这个实验我没有做过）。

**Comment by HugoLian** [comment]
@lcy-seso 感谢解答，继续请教一下：
关于问题2：
```
user_id_emb = embedding_layer(input=user_id, size=embsize)
user_id_hidden = fc_layer(input=user_id_emb, size=embsize)
```
我看网络结构中，每一个embedding_layer都会接一个同等长度的fc_layer，这么做的好处是什么呢？如果我们获得一个one-hot representation的distribute representation形式，那么应该是对应上面的embedding_layer层输出，还是fc_layer输出？

另外关于问题1：
性别不只有男，女么？一个一维的0,1表示或者2维的枚举表示不就足够了么？为什么还要映射到一个256维的词向量上呢？

**Comment by lcy-seso** [comment]
distribute representation 是 embeding_layer 的输出。

这种 2个离散特征的情况，不是最典型的场景， 算是一种 model design choice，并不是只能这么做，也并不是说么做总是最优的。 对于离散特征，BOW 接若干个fc，应该也能拟合住。

不过性别这个，应该算是一个特征有两个取值，如果不转化成 embedding，直接给下一层，就变成了简单的乘以一个系数，相当于我们对 “男”和“女”天生有一个权值，不如为 “男” 和 “女” 学习一个特征表示，把这个表示给下一层这种设计更好。

其它特征，接 embedding 也没啥坏处，相当于为原始输入重新学习一个表示。

**Comment by HugoLian** [comment]
@lcy-seso 继续请教一下：现在就是对于一个embedding层的输出，后面接一个fc，然后用fc层作为下一层的输入，这个考虑或者好处是什么呢？ 还是说现在一般的网络结构，通常会有这样一种配置的组合，经验上是比较理想的？

**Comment by lcy-seso** [comment]
先说我的结论：
1. fc + embedding 也不是什么非常特殊的设计，需要的是找到复杂度恰好的那个模型。
2. 这个模型cnn 处理电影名那里算是一个常规的序列模型。

以下是一些说明：
- 在推荐系统这个例子中，性别，以及其它一些离散特征，永远都只会取到其中一个值，是一个one-hot 表示，这时候过embedding layer 和 one-hot 直接接一个fc 是没啥区别的，计算上完全一样。
- 如果你觉得不是非常好理解， 这和接了两个 fc ，第一个fc 没有引入非线性是一样的。
- embedding + fc 这种配置，本身也不算是“固定的”，或者说“通用的”就一定需要这样配的配置方法。机器学习模型设计，通常还是首先考虑尽可能地拟合住数据，在这个过程中，控制模型的复杂度。先从简单的模型开始尝试，果拟合准确率已经非常高了，够用的话，在数据没有扩大的情况下，通常可以不再考虑更复杂的模型。提高复杂度就是一个layer，一个layer 网上叠加。
- 推荐系统这个例子中的模型已经是复杂度较低的一个模型，你可以试试去掉fc层，训练集的拟合精度会不会降；然后再加一个fc 层，看见训练集的拟合精度会不会提升，拟合速率会不会有变化，同时，在变化的过程中，测试集上的精度会不会有所改变。

**Comment by HugoLian** [comment]
非常细致深入！
非常感谢！！@lcy-seso
