### ISSUE TITLE
如何feed lod_level > 1的数据

### ISSUE THREAD

**Issue by fseasy** [PaddlePaddle/Paddle#13312]
看 http://paddlepaddle.org/documentation/docs/zh/0.15.0/new_docs/user_guides/howto/prepare_data/feeding_data.html#permalink-4-- ，里面是用的 
`create_lod_tensor`这个函数来feed sequence数据的。

但是这个函数目前的签名与例子不相同了…… 
另外，按照上面的链接里的`训练数据 sentence 包含三个样本`，这个feed进去时一个batch的数据？ 也就是说，lod-level = 1，表示多个变长的句子，每个句子是一个输入；那么 lod-level=2, 可以表示多个变长的句子集合，每个句子集合是一个输入？ 
感觉把batch和tensor的维度这两个混在一起了，感觉有些不易理解了。
最好多给几个正确的例子吧。

**Comment by wanghaoshuang** [comment]
关于LoD的概念，可以参考这里的设计文档：https://github.com/PaddlePaddle/Paddle/blob/e26f51ce74e998c4119fc2c3145aa7c1224c2170/doc/fluid/design/concepts/lod_tensor.md

还有一个非常详细的讨论：https://github.com/PaddlePaddle/Paddle/issues/10855

**Comment by fseasy** [comment]
啊，看完大概理解了…… 总结了一下https://github.com/PaddlePaddle/Paddle/issues/10855#issuecomment-419777303

**Comment by fseasy** [comment]
哎呀，这个api感觉还是不清楚啊，望多给点例子。
这种example不应该是写单测的时候都要写的吗，为什么不直接贴出来呢？ issue的内容也麻烦尽快总结到doc里吧。issue里搜索可能漏掉，放到doc里就好多啦。
真的很浪费大家时间啊……

**Comment by wanghaoshuang** [comment]
@memeda 感谢反馈和建议，你说的很有道理，我们确实需要细化下对重要的概念的解释文档。

**Comment by luotao1** [comment]
> 我们确实需要细化下对重要的概念的解释文档

@shanyi15 请统一规划一下。

**Comment by shanyi15** [comment]
收到@luotao1

**Comment by lucywsq** [comment]
您好，此issue在近一个月内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题，我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持!
