### ISSUE TITLE
请问可以把batch里每个序列数据划分为两部分，第一部分是第一条，第二部分是剩下的所有

### ISSUE THREAD

**Issue by fseasy** [PaddlePaddle/Paddle#13324]
## 背景

篇章级别，分别有title和多个句子组成的正文；想要算title与每个句子的相似度。
title和句子的表示方式相同，所以我想把title和正文内的所有句子一起输入进去做表示处理；
处理完后，需要把这个表示拆出来，也就是分为title和正文的句子集合；然后去算title和每个句子的相似度。

## 问题

可以完成拆分操作吗？
我看到有 fluid.layers.sequence_first_step 可以取第一个batch sequence 的第一个句子（也就是title），但是剩余部分可以取出来吗？
我看到有`fluid.layers.gather`, 但是似乎是针对一个tensor的？

**Comment by wanghaoshuang** [comment]
抱歉，我们没有类似的例子，但是你可以尝试一下dynamic_rnn: https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/fluid/layers/control_flow.py#L1542
理论上是可以实现你提出的需求的，需要你探索一下。

**Comment by fseasy** [comment]
😂 似乎是可以根据dynamic_rnn 改一个是吗 = =
刚刚试了下 sequencce_first_step + slice, 发现第一个会报错`paddle.fluid.core.EnforceNotMet: Enforce failed. Expected lod.size() == 1UL, but received lod.size():2 != 1UL:1.`,
 第二个出来看起来是按照data做的slice，而不是lod_tensor
——————
我想是不是还是作为独立的输入弄进去，或者尝试写一下……

**Comment by fseasy** [comment]
哎呀，搞不定…… 对lod_tensor_to_array等的内部机制不太懂；单纯从打印来看，step_input拿到的按长度排序后的句子？ 这样我就不能把原来的第一个句子单独拿出来了？ 对内部不太懂，还是不折腾了……
