### ISSUE TITLE
编译遇到/lib64/tls/libc.so.6: version `GLIBC_2.14' not found的问题

### ISSUE THREAD

**Issue by wuhabi** [PaddlePaddle/Paddle#1333]
根据 http://deeplearning.baidu.com/doc/local_compile.html 编译paddle，但遇到了/lib64/tls/libc.so.6: version `GLIBC_2.14' not found
<img width="1280" alt="screen shot 2017-02-14 at 5 26 42 pm" src="https://cloud.githubusercontent.com/assets/7334845/22923025/cbf74816-f2da-11e6-8d0f-912f45c948ca.png">

**Comment by gangliao** [comment]
内部用户： @wuhabi 
```bash
jumbo install gcc48
cmake   ..  -DCMAKE_C_COMPILER=$HOME/.jumbo/opt/gcc48/bin/gcc -DCMAKE_CXX_COMPILER=$HOME/.jumbo/opt/gcc48/bin/g++ 
```

**Comment by gangliao** [comment]
或者直接使用icode下面的一键安装脚本：icode: baidu/gangliao/paddle_internal_release_tools
