### ISSUE TITLE
Fluid咨询

### ISSUE THREAD

**Issue by shangguanyifeng** [PaddlePaddle/Paddle#13333]
使用fluid怎么获取中间层的特征图信息，需要使用什么api具体使用什么api，直接在定义网络的时候print并不能得到任何关于shape的信息

**Comment by reyoung** [comment]
可以在executor.run或者parallel_executor.run中fetch，将对应的输出过来。

http://paddlepaddle.org/documentation/docs/zh/0.15.0/new_docs/user_guides/howto/training/single_node.html#id6
