### ISSUE TITLE
mac 安装问题

### ISSUE THREAD

**Issue by gucasbrg** [PaddlePaddle/Paddle#1334]
1. mac操作系统10.11.3
2. git 最新的develop分支

编译：
```
cmake .. -DWITH_GPU=OFF -DCMAKE_INSTALL_PREFIX=/Users/user/git/deeplearning
make -j `nproc` && make install
```

error or warning:

gcc -fno-strict-aliasing -I/Users/user/anaconda/include -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -arch x86_64 -I/Users/user/anaconda/lib/python2.7/site-packages/numpy/core/include -I../ -I/Users/user/anaconda/include/python2.7 -I/Users/user/anaconda/lib/python2.7/site-packages/numpy/core/include -I../ -I/Users/user/anaconda/include/python2.7 -c Paddle_wrap.cxx -o build/temp.```macosx-10.6-x86_64-2.7```/Paddle_wrap.o -std=c++11 
cc1plus: warning: command line option '-Wstrict-prototypes' is valid for C/ObjC but not for C++

ld: warning: object file (/Users/user/git/paddle/build/paddle/gserver/libpaddle_gserver.a(WarpCTCLayer.cpp.o)) was built for newer OSX version (10.11) than being linked (10.6)
ld: warning: object file (/Users/user/git/paddle/build/paddle/gserver/libpaddle_gserver.a(ValidationLayer.cpp.o)) was built for newer OSX version (10.11) than being linked (10.6)

 ld: targeted OS version does not support use of thread local variables in google::protobuf::Arena::Init()   for architecture x86_64

**Comment by gucasbrg** [comment]
安装之前export MACOSX_DEPLOYMENT_TARGET=10.11 成功，是不是脚本里面获取一下系统版本

**Comment by gangliao** [comment]
有道理 #1336
