### ISSUE TITLE
Overriden or added method in AnalysisPredictor?

### ISSUE THREAD

**Issue by wojtuss** [PaddlePaddle/Paddle#13353]
https://github.com/PaddlePaddle/Paddle/blob/620392ef7d011239c417c5ec79d242f217868c19/paddle/fluid/inference/api/analysis_predictor.h#L36

Was the `Init()` method from the `AnalysisPredictor` intentionally made not overriding the `Init()` method from the base `NativePaddlePredictor` class? IMHO it looks like by mistake.

**Comment by Superjomn** [comment]
No, it doesn't override. 

In the latest code, the AnalysisPredictor doesn't inherit NativePredictor.
