### ISSUE TITLE
missing expand op 

### ISSUE THREAD

**Issue by hedlmote** [PaddlePaddle/Paddle#13357]
I found that expand op has been implemented: https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/fluid/operators/expand_op.cc

However, i cannot find its corresponding api.

**Comment by lucywsq** [comment]
We have received your question and we would reply relative methods to you as soon as possible : )

**Comment by dzhwinter** [comment]
it can be included in paddle/fluid/layers/nn.py. Which is automatically generated in python implicitly.
