### ISSUE TITLE
mpi训练使用batch_norm出现  bool(int(g_command_config_args.get("use_gpu", 0))).  ValueError: invalid literal for int() with base 10: 'False'

### ISSUE THREAD

**Issue by 333caowei** [PaddlePaddle/Paddle#13371]
mpi训练，加入batch_norm层后，出现如下错误：
`
Wed Sep 12 22:07:21 2018[1,73]<stderr>:  File "/home/disk1/normandy/maybach/app-user-20180912220136-9231/workspace/python27-gcc482/lib/python2.7/site-packages/paddle/trainer/config_parser.py", line 2501, in __init__
Wed Sep 12 22:07:21 2018[1,73]<stderr>:    use_gpu = bool(int(g_command_config_args.get("use_gpu", 0)))
Wed Sep 12 22:07:21 2018[1,73]<stderr>:ValueError: invalid literal for int() with base 10: 'False'
`

本地运行就没有这个问题

**Comment by dzhwinter** [comment]
设置错误，use_gpu=0.不能是False

**Comment by 333caowei** [comment]
不知g_command_config_args.get("use_gpu", 0)是在哪里设置的，
我代码里面使用的是：use_gpu_flag = os.getenv("PADDLE_USE_GPU", "0")
@dzhwinter

**Comment by Superjomn** [comment]
use_gpu_flag = os.getenv("PADDLE_USE_GPU", "0")

直接设置0试试？ 不要从环境变量取了

**Comment by 333caowei** [comment]
经过测试把use_gpu_flag = os.getenv("PADDLE_USE_GPU", "0")直接写死成use_gpu_flag = 0解决了，谢谢 @Superjomn
