### ISSUE TITLE
caffe2fluid 加载转换之后的模型fine-tune出错(holder_ should not be null)

### ISSUE THREAD

**Issue by Wkyao** [PaddlePaddle/Paddle#13388]
![image](https://user-images.githubusercontent.com/24263632/45489483-eb922100-b796-11e8-861c-1fe2fc49de58.png)

**原因是：转换之后BN函数里面一个参数'is_test=True'，改为False就可以正常训练了**
![image](https://user-images.githubusercontent.com/24263632/45489613-475caa00-b797-11e8-832b-667229cdd98e.png)

**Comment by velconia** [comment]
```is_test```是为validation program设置的一个参数, 训练时建议设置为True, 请问您参考的是哪篇文档呢?
