### ISSUE TITLE
paddle capi 预测问题

### ISSUE THREAD

**Issue by wfeagle** [PaddlePaddle/Paddle#13398]
把训好的模型改成C++预测，照着这个例子写的，
https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/legacy/capi/examples/model_inference/sequence/main.c

现在编译通过了，但是预测报错，如下：
$ head -10 z | ./output/bin/main
I0914 15:47:04.985348  3788 Util.cpp:166] commandline:  --use_gpu=False
I0914 15:47:04.992543  3788 GradientMachine.cpp:94] Initing parameters..
I0914 15:47:05.080584  3788 GradientMachine.cpp:101] Init parameters done.
I0914 15:47:05.080603  3788 GradientMachine.cpp:83] Loading parameters from /home/disk1/wangfang20/baidu/medical-topic/inference/models/
F0914 15:47:05.081784  3788 NeuralNetwork.cpp:250] Check failed: inArgs.size() == dataLayers_.size() (1 vs. 0)
*** Check failure stack trace: ***
    @     0x7f6ab9d5307d  google::LogMessage::Fail()
    @     0x7f6ab9d56b2c  google::LogMessage::SendToLog()
    @     0x7f6ab9d52ba3  google::LogMessage::Flush()
    @     0x7f6ab9d5803e  google::LogMessageFatal::~LogMessageFatal()
    @     0x7f6ab9ecb132  paddle::NeuralNetwork::forward()
    @     0x7f6ab9d4e0f6  paddle_gradient_machine_forward
    @           0x43e4be  medical_topic::paddle::predictor::MedicalTopicPredictor::predict_topic()
    @           0x43d131  main
    @     0x7f6ab913ebd5  __libc_start_main
    @           0x43d559  (unknown)
    @              (nil)  (unknown)
Aborted

**Comment by Superjomn** [comment]
> F0914 15:47:05.081784 3788 NeuralNetwork.cpp:250] Check failed: inArgs.size() == dataLayers_.size() (1 vs. 0)

这是模型没有传输入，一个输入对应一个 data layer，现在是0个data layer。

Data layer 是模型的输入的处理op。

**Comment by wfeagle** [comment]
是说我的输入数据没有传进去吗？ 这里的val 是得到bidword的切词索引，这样传不对吗？还是其他的地方有问题？

```c++
bool create_sequence_feature(
        paddle_arguments& in_args,
        vector<int>& val,
        vector<paddle_ivector>& out_ivector) {
    paddle_ivector sentence = paddle_ivector_create(
            &val[0], val.size(), false, false);
    CHECK(paddle_arguments_set_ids(in_args, 0, sentence));

    int seq_pos_array[] = {0, static_cast<int>(val.size())};
    paddle_ivector seq_pos = paddle_ivector_create(
            seq_pos_array, sizeof(seq_pos_array) / sizeof(int), false, false);
    CHECK(paddle_arguments_set_sequence_start_pos(in_args, 0, 0, seq_pos));

    out_ivector.push_back(sentence);
    out_ivector.push_back(seq_pos);
    return true;
}
```

**Comment by Superjomn** [comment]
这个是处理数据？ 跟这个好像没关系，是预测接口传的inputs是空的应该

**Comment by wfeagle** [comment]
上面的就是把val(bidword索引)放进in_args, 然后in_args放入paddle的forward函数，所以是说这里的in_args从这个函数出来后就没有得到data 是吗？下面第二行是上面的函数，后面一行就是预测了

    vector<paddle_ivector> new_ivector;
    create_sequence_feature(in_args, val, new_ivector);
    paddle_arguments out_args = paddle_arguments_create_none();
    CHECK(paddle_gradient_machine_forward(_machine, in_args, out_args, false));

**Comment by Superjomn** [comment]
可以把 `in_args` 的size 输出来，从出错看，这里是空的

**Comment by Superjomn** [comment]
这是v1 还是 v2?

**Comment by wfeagle** [comment]
v2

**Comment by Superjomn** [comment]
dataLayers.size() =0，感觉是
![image](https://user-images.githubusercontent.com/328693/45540113-2a2ee680-b83e-11e8-936c-7374b5fa8e25.png)

没有data layer ?  输入的确不是空的，是1

**Comment by wfeagle** [comment]
输入就是这个，照着这个教程http://www.paddlepaddle.org/documentation/docs/zh/0.12.0/howto/capi/workflow_of_capi_cn.html  把神经网络预测dump成train_config.bin的，模型参数在另外一个文件夹

data = paddle.layer.data(name="words",
                        type=paddle.data_type.integer_value_sequence(dict_dim))

**Comment by Superjomn** [comment]
![image](https://user-images.githubusercontent.com/328693/45541095-ab877880-b840-11e8-955b-52313d9080da.png)

这个步骤是不是把data layer也删了

**Comment by wfeagle** [comment]
```
import paddle.v2 as paddle
from paddle.v2.layer import full_matrix_projection, identity_projection

dict_dim=4492
class_dim=6610
emb_dim=64
hid_dim=64
emb_lr=1e-2
dropout_rate=0.5

# word seq data
data = paddle.layer.data(name="words",
                        type=paddle.data_type.integer_value_sequence(dict_dim))
# embedding layer
emb = paddle.layer.embedding(input=data,
                            size=emb_dim,
                            param_attr=paddle.attr.Param(
                                name="embedding",
                                learning_rate=emb_lr))
# Lstm layer
hidden = paddle.layer.mixed(
        size=hid_dim * 4,
        input=[full_matrix_projection(input=emb)])
lstm_h = paddle.layer.lstmemory(
        input=hidden,
        reverse=False)
dropout = paddle.layer.mixed(
        input=[identity_projection(input=lstm_h)],
        layer_attr=paddle.attr.Extra(drop_rate=dropout_rate))

rhidden = paddle.layer.mixed(
        size=hid_dim * 4,
        input=[full_matrix_projection(input=emb)])
rlstm_h = paddle.layer.lstmemory(
        input=rhidden,
        reverse=True)
rdropout = paddle.layer.mixed(
        input=[identity_projection(input=rlstm_h)],
        layer_attr=paddle.attr.Extra(drop_rate=dropout_rate))

# concat layer
lstm_concat = paddle.layer.concat(input=[dropout, rdropout])

# attention
att_vec = paddle.layer.mixed(
        size=hid_dim*4 // 2,
        input=[full_matrix_projection(input=lstm_concat)],
        act=paddle.activation.Tanh())

att_weight = paddle.layer.mixed(
        size=1,
        input=[full_matrix_projection(input=att_vec)],
        act=paddle.activation.SequenceSoftmax())

scaled = paddle.layer.scaling(input=lstm_concat, weight=att_weight)

context = paddle.layer.pooling(input=scaled, pooling_type=paddle.pooling.Sum())

# softmax layer
prediction = paddle.layer.fc(
        size=class_dim,
        input=context,
        act=paddle.activation.Softmax(),
        bias_attr=False)
```

**Comment by wfeagle** [comment]
就是把上面的单独写在一个py文件，然后再dump成bin

**Comment by Superjomn** [comment]
@qingqing01 @jacquesqiao 有遇到过这种情况吗

感觉是python 里，对应 v1 的 inputs(xxx) 没设
