### ISSUE TITLE
LSTM的数据格式如何传入

### ISSUE THREAD

**Issue by 1727536969** [PaddlePaddle/Paddle#13415]
我在用LSTM做一个预测，现在已经有了模型，但就是数据集不知道以什么样的格式传给X，能被接收。

**Comment by velconia** [comment]
请问方便贴出代码吗? 数据集传入可以参考 http://www.paddlepaddle.org/documentation/api/en/develop/data_feeder.html 这个文档

**Comment by velconia** [comment]
你好, 请问还有别的问题吗?
