### ISSUE TITLE
集群训练问题，paddle.py和conf.py导致No module named trainer.config_parser

### ISSUE THREAD

**Issue by shijieheping** [PaddlePaddle/Paddle#1342]
重现方法如下：

/root/pp/git/paddle/benchmark/paddle/image下，执行
    paddle train --job=time --config=alexnet.py --use_gpu=True --trainer_count=2 --log_period=10 --test_period=100 --config_args=batch_size=64
顺利运行

复制集群训练配置文件到该目录，
cp /data/PaddlePaddle/git/paddle/paddle/scripts/cluster_train/paddle.py ./
cp /data/PaddlePaddle/git/paddle/paddle/scripts/cluster_train/conf.py ./
再执行
    paddle train --job=time --config=alexnet.py --use_gpu=True --trainer_count=2 --log_period=10 --test_period=100 --config_args=batch_size=64
会报错
[root@g1 image]# paddle train --job=time --config=alexnet.py --use_gpu=True --trainer_count=2 --log_period=10 --test_period=100 --config_args=batch_size=64
Paddle release a new version 0.9.0, you can get the install package in http://www.paddlepaddle.org
I0215 11:06:19.916949 38513 Util.cpp:160] commandline: /usr/local/bin/../opt/paddle/bin/paddle_trainer --job=time --config=alexnet.py --use_gpu=True --trainer_count=2 --log_period=10 --test_period=100 --config_args=batch_size=64 
F0215 11:06:22.954466 38513 PythonUtil.cpp:186] Check failed: (module) != nullptr Current PYTHONPATH: ['/usr/local/opt/paddle/bin', '/root/pp/git/paddle/benchmark/paddle/image', '/data/PaddlePaddle/git/paddle/benchmark/paddle/image', '/usr/lib64/python27.zip', '/usr/lib64/python2.7', '/usr/lib64/python2.7/plat-linux2', '/usr/lib64/python2.7/lib-tk', '/usr/lib64/python2.7/lib-old', '/usr/lib64/python2.7/lib-dynload', '/root/.local/lib/python2.7/site-packages', '/usr/lib64/python2.7/site-packages', '/usr/lib/python2.7/site-packages']
Python Error: <type 'exceptions.ImportError'> : No module named trainer.config_parser
Python Callstack: 
Import paddle.trainer.config_parserError
*** Check failure stack trace: ***
    @           0x93ab68  google::LogMessage::Fail()
    @           0x93aac4  google::LogMessage::SendToLog()
    @           0x93a448  google::LogMessage::Flush()
    @           0x93d4ef  google::LogMessageFatal::~LogMessageFatal()
    @           0x87c4bb  paddle::py::import()
    @           0x87c52e  paddle::callPythonFuncRetPyObj()
    @           0x87c8fc  paddle::callPythonFunc()
    @           0x75fc0b  paddle::TrainerConfigHelper::TrainerConfigHelper()
    @           0x760244  paddle::TrainerConfigHelper::createFromFlags()
    @           0x5b5b42  main
    @     0x7f6eef23db35  __libc_start_main
    @           0x5cc7f2  (unknown)
    @              (nil)  (unknown)
/usr/local/bin/paddle: line 109: 38513 Aborted                 ${DEBUGGER} $MYDIR/../opt/paddle/bin/paddle_trainer ${@:2}

检查了一下python环境，是有这个包的
/root/miniconda2/lib/python2.7/site-packages/paddle/trainer/config_parser.py
/root/miniconda2/lib/python2.7/site-packages/paddle/trainer/config_parser.pyc
/usr/lib/python2.7/site-packages/paddle/trainer/config_parser.py
/usr/lib/python2.7/site-packages/paddle/trainer/config_parser.pyc

这是什么原理？运行目录下的paddle.py文件会覆盖配置？为什么会说No module named trainer.config_parser呢

操作系统CentOS7.3，paddle版本0.9.0a

**Comment by shijieheping** [comment]
提这个问题是因为，我想要在集群里训练。
结果配置之后，集群训练运行不起来。
从最小环境开始检查，发现只要有paddle.py，连单机都运行不了了。
和conf.py没关系，我把那行注释掉还是会有这个问题。

我刚才从ftp上更新过CentOS7.3的pyparsing，感觉不会是这个影响到的。它又不import paddle
yum install ftp://mirror.switch.ch/pool/4/mirror/centos/7.3.1611/cloud/x86_64/openstack-kilo/common/pyparsing-2.0.3-1.el7.noarch.rpm

**Comment by shijieheping** [comment]
@qingqing01 今天上午试过了用yum python重新编译，装到yum pip里。
还是不行，和paddle.trainer .config_parser #6现象一致，但是换python和pip环境重新编译安装，没能解决


[root@g1 image]# cat logs/alexnet-1gpu-64.log 
Paddle release a new version 0.9.0, you can get the install package in http://www.paddlepaddle.org
I0216 01:23:09.348279 40403 Util.cpp:160] commandline: /usr/local/bin/../opt/paddle/bin/paddle_trainer --job=time --config=alexnet.py --use_gpu=True --trainer_count=1 --log_period=10 --test_period=100 --config_args=batch_size=64 
F0216 01:23:12.380504 40403 PythonUtil.cpp:186] Check failed: (module) != nullptr Current PYTHONPATH: ['/usr/local/opt/paddle/bin', '/root/pp/git/paddle/benchmark/paddle/image', '/data/PaddlePaddle/git/paddle/benchmark/paddle/image', '/usr/lib64/python27.zip', '/usr/lib64/python2.7', '/usr/lib64/python2.7/plat-linux2', '/usr/lib64/python2.7/lib-tk', '/usr/lib64/python2.7/lib-old', '/usr/lib64/python2.7/lib-dynload', '/root/.local/lib/python2.7/site-packages', '/usr/lib64/python2.7/site-packages', '/usr/lib/python2.7/site-packages']
Python Error: <type 'exceptions.ImportError'> : No module named trainer.config_parser
Python Callstack: 
Import paddle.trainer.config_parserError
*** Check failure stack trace: ***
    @           0x940380  google::LogMessage::Fail()
    @           0x9402dc  google::LogMessage::SendToLog()
    @           0x93fc60  google::LogMessage::Flush()
    @           0x942d07  google::LogMessageFatal::~LogMessageFatal()
    @           0x888f7b  paddle::py::import()
    @           0x888fee  paddle::callPythonFuncRetPyObj()
    @           0x8893bc  paddle::callPythonFunc()
    @           0x767943  paddle::TrainerConfigHelper::TrainerConfigHelper()
    @           0x767f84  paddle::TrainerConfigHelper::createFromFlags()
    @           0x5b6c82  main
    @     0x7f805516db35  __libc_start_main
    @           0x5cdbf2  (unknown)
    @              (nil)  (unknown)
/usr/local/bin/paddle: line 109: 40403 Aborted                 ${DEBUGGER} $MYDIR/../opt/paddle/bin/paddle_trainer ${@:2}

**Comment by shijieheping** [comment]
这会重现更容易了，只要有paddle.py*在目录下，python就不知道怎么import parser包了。
下面这个过程应该挺清晰的

[root@g1 paddle]# ls
image  rnn
[root@g1 paddle]# python
Python 2.7.5 (default, Nov  6 2016, 00:28:07) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-11)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import paddle.trainer.config_parser
>>> 

[root@g1 paddle]# cd -
/root/pp/git/paddle/benchmark/paddle/image
[root@g1 image]# ls
alexnet.py  googlenet.py  paddle.py   provider.py  smallnet_mnist_cifar.py  train.list
conf.py     logs          paddle.pyc  run.sh       tmp
[root@g1 image]# python
Python 2.7.5 (default, Nov  6 2016, 00:28:07) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-11)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import paddle.trainer.config_parser
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named trainer.config_parser
>>> 

[root@g1 image]# mv paddle.py* tmp/
[root@g1 image]# python
Python 2.7.5 (default, Nov  6 2016, 00:28:07) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-11)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import paddle.trainer.config_parser
>>> 
[root@g1 image]#

**Comment by shijieheping** [comment]
@qingqing01 
最新进展，我发现这个和paddle.py的内容都没关系，只要在目录下有paddle.py文件，单机训练就运行不起来。
我touch了一个空paddle.py文件，和上面的log一样。
不贴log了，需要的话我再复制一下上面的那堆。

**Comment by qingqing01** [comment]
>  只要在目录下有paddle.py文件，单机训练就运行不起来。

是因为这时候 import paddle.trainer.config_parser 是从当前目录的paddle.py文件里import trainer.config_parser就会导致有问题， 所以不应该在同一个目录下。
