### ISSUE TITLE
fluid版本定义常量和张量问题

### ISSUE THREAD

**Issue by yeyupiaoling** [PaddlePaddle/Paddle#13437]
比如这个接口：http://www.paddlepaddle.org/documentation/api/zh/0.15.0/layers.html#permalink-183-fill_constant

比如我想定义一个shape为`[2,2]`的，值为`[[1,2].[3,4]]`，但是赋值能是一个数字，如下：
```python
data = fluid.layers.fill_constant(shape=[2,2], value=0, dtype='int64')
```

类型的问题还有这个接口：http://www.paddlepaddle.org/documentation/api/zh/0.15.0/layers.html#permalink-177-create_global_var

**Comment by velconia** [comment]
你好，fill_constant不支持为tensor赋予不同的值，你可以使用assign进行赋值操作

**Comment by yeyupiaoling** [comment]
@velconia 好的，明白了，谢谢您们。发布1.0之后，您们总算有时间回答issue了
