### ISSUE TITLE
paddle.fluid.core.Variable 和 paddle.fluid.framework.Variable 两种类型有何区别?

### ISSUE THREAD

**Issue by gtvforever** [PaddlePaddle/Paddle#13448]
RT。 另外像请教下初始化 paddle.fluid.framework.Variable 的问题， 可否通过传递一个已经初始化好的ndarray来初始化 paddle.fluid.framework.Variable？

**Comment by xuezhong** [comment]
paddle.fluid.core.Variable  是C++的接口，不对外使用的 paddle.fluid.framework.Variable 是python的接口 是对外使用的，两者接口也不相同，因此不能替换。
初始化参数的方法如下，以embedding的参数为例：
 input_embedding = layers.embedding(
            input=input_ids,
            size=[vocab.size(), vocab.embed_dim],
            dtype='float32',
            param_attr=fluid.ParamAttr(
                name = 'embedding_para'))
    embedding_para = fluid.global_scope().find_var(
            'embedding_para').get_tensor()
    embedding_para.set(vocab.embeddings.astype(np.float32), place)

**Comment by lucywsq** [comment]
您好，此issue在近一个月内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题，我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持!
