### ISSUE TITLE
关于paddle提供向量函数疑问

### ISSUE THREAD

**Issue by DanChristas** [PaddlePaddle/Paddle#13452]
能问一下，pad是否提供相邻向量之间Point-wise Mutual Info和Branch Entropy的计算函数？

**Comment by xuezhong** [comment]
您好，没太看明白你的需求，能具体说明下吗
另外可以参考api中提供的方法
http://www.paddlepaddle.org/documentation/api/zh/0.15.0/layers.html

**Comment by lucywsq** [comment]
您好，此issue在近一个月内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题，我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持!
