### ISSUE TITLE
paddle.fluid.layers.scale bug

### ISSUE THREAD

**Issue by lgone2000** [PaddlePaddle/Paddle#13462]
复现代码如下。虽然和qingqing沟通可以绕过，但还是希望这个要当作bug解决。
```
def testscale():
    x = fluid.layers.data(name='x', shape=[1], dtype='float32')
    y = x * 2
    z = paddle.fluid.layers.scale(x, 2)
    place = fluid.CPUPlace()
    exe = fluid.Executor(place)
    exe.run(fluid.default_startup_program())
    inputdata = np.array([1],np.float32)
    output = exe.run(
                fluid.default_main_program(),
                feed={'x': inputdata},
                fetch_list=[x.name, y.name, z.name]
            )
    #should output 1,2,2 ; but it output 1,2,1
    print output
```

**Comment by qingqing01** [comment]
1. 解决办法：
    >   z = paddle.fluid.layers.scale(x, 2)

    改成以下就行：

    ```python
    z = paddle.fluid.layers.scale(x=x, scale=2.)
    ```
2. 原因：
   scale这个API是 https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/fluid/layers/ops.py 自动生成，自动生成这类Python API可能都存在该问题，文档也不是很友好：

    http://paddlepaddle.org/documentation/api/zh/0.15.0/layers.html#permalink-109-scale

    ```python
    paddle.fluid.layers.scale(*args, **kwargs)
    ```
    也没明确告诉用户必需在接口里加key，或者正确的用法。
   
又回到之前的老问题~    @shanyi15 @panyx0718 @reyoung

**Comment by lgone2000** [comment]
参数设计这块，根据大多数python的用法，函数入口没有强制要求一定要用key传入的。

**Comment by lucywsq** [comment]
您好，此issue在近一个月内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题，我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持!

**Comment by qingqing01** [comment]
此类API都已修复，都已重新封装，例如`fluid.layers.scale`, 见 https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/fluid/layers/nn.py#L8317 文件：

```python
@templatedoc()
def scale(x, scale=1.0, bias=0.0, bias_after_scale=True, act=None, name=None):
```

不在要求用户必需给key。

**Comment by lgone2000** [comment]
验证了一下，确实修正了
