### ISSUE TITLE
训练过程中部分结点训练完成，部分结点出core

### ISSUE THREAD

**Issue by sinoautom** [PaddlePaddle/Paddle#13478]
日志链接：http://10.182.19.22:8900/fileview.html?path=/home/disk1/normandy/maybach/app-user-20180918181435-16523/

任务链接：http://paddlecloud.baidu-int.com:8088/paddle/jobRunInfo?jobId=job-e6c5ba0cfe33515a&flag=jobs&groupName=feed_ads&groupId=f323a7cf-d135-4e45-9d71-12dcf823ed6e&currentPage=1&currentKey=1

**Comment by lucywsq** [comment]
您好，想麻烦问一下您使用的V2版本还是Fluid？如果是V2建议您后续迁移至Fluid
此问题我们已经收到，将尽快回复您解决办法~

**Comment by typhoonzero** [comment]
@sinoautom 抱歉回复晚了，才看到，请问现在还有能复现的场景么？

**Comment by lucywsq** [comment]
您好，此issue在近一个月内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题，我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持!
