### ISSUE TITLE
Semaphore Lock 内存泄漏

### ISSUE THREAD

**Issue by viennadd** [PaddlePaddle/Paddle#1347]
在 [Locks.cpp#L25](https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/utils/arch/linux/Locks.cpp#L25) 中，Semaphore 构造时 new 了 SemaphorePrivate， 但析构时没有调用 delete，

构造
` Semaphore::Semaphore(int initValue) : m(new SemaphorePrivate()) {`

析构
`Semaphore::~Semaphore() { sem_destroy(&m->sem); }`

**Comment by reyoung** [comment]
Has been fixed.
