### ISSUE TITLE
评价指标问题

### ISSUE THREAD

**Issue by mengyiliu22** [PaddlePaddle/Paddle#13471]
你好，我在使用nce做多分类损失函数时，想在训练过程中打印出训练集和验证集的P值或AUC等评价指标。
我的做法是取出nce层的参数，然后得到输出向量，用该向量和label做evaluator的参数。
问题是在训练过程中，event.metrics都是空的，请问这是什么原因呢？

**Comment by seiriosPlus** [comment]
你好，您用的是trainer.py来训练的么？

**Comment by mengyiliu22** [comment]
> 你好，您用的是trainer.py来训练的么？

是的，用trainer.train()来训练的。

**Comment by lucywsq** [comment]
您好，请您截图详细的报错代码，以便定位和解决问题~
此issue若已经解决，我们将于三天内关闭。若在关闭后您仍需跟进 提问，可重新开启此问题，
我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持!
