### ISSUE TITLE
Does PaddlePaddle support CentOS 6.x ?

### ISSUE THREAD

**Issue by 17Skye17** [PaddlePaddle/Paddle#1349]
I've tried build PaddlePaddle on CentOS 6.8,however,it seems that some of the requirements are just available for CentOS 7.x.
Have anyone built it on CentOS 6.x successfully?

**Comment by gangliao** [comment]
You can post the error info in here when build paddle on CenOS 6.8. @17Skye17

**Comment by 17Skye17** [comment]
On CentOS6.8,glibc version is 2.12,it seems paddle requires for glibc version 2.14?

**Comment by reyoung** [comment]
Paddle should be compiled on any Linux, but in develop branch, we do not ensure that all commits are well tested.

To install Paddle on CentOS 6.+, please try to use master branch of Paddle.

Also, the Glibc 2.14 dependency is introduced by `protobuf 3.1` we used in Paddle. We will try our best to fix it. The solution may be:

* Downgrade the protobuf to 3.0.
* Or try to hack protobuf source code for this dependency.

It should be fixed after several commits.

**Comment by Canpio** [comment]
Close this inactivate issue, please feel free to reopen.
