### ISSUE TITLE
请问如何调整GPU显存分配策略？

### ISSUE THREAD

**Issue by zzhzz** [PaddlePaddle/Paddle#13497]
在训练过程中，我发现PaddlePaddle默认的显存分配策略是分配尽可能多的显存（比如当前GPU上没有其他程序运行的话，训练程序会分配全部显存）。如何调整显存策略为动态增长呢？

**Comment by tensor-tang** [comment]
默认情况下初始拿显存的92%，这个是可以通过flag调整。
https://github.com/PaddlePaddle/Paddle/blob/87086b1386083a2f7479585b966f3ca82d7a9012/paddle/fluid/platform/gpu_info.cc#L22-L25

**Comment by zzhzz** [comment]
@tensor-tang 这个怎么调整，通过系统环境变量吗？

**Comment by tensor-tang** [comment]
在python跑的时候，`--fraction_of_gpu_memory_to_use=0.4`

**Comment by xixiaoyao** [comment]
请问如何实现显存的动态增长呢？
