### ISSUE TITLE
The last dimension of the 'Ids' tensor must be 1

### ISSUE THREAD

**Issue by zhoukunsheng** [PaddlePaddle/Paddle#13502]
environment information:
- paddlepaddle version 0.15.0, fluid API
- use CPU

My batch of data is like a batch of sentences, for example: [ [ 1, 2, 2], [3, 2, 1, 2] ] is a batch with 2 examples, first one is with length 3, second one with length 4. So I declare a data layers with shape [1] and lod_level = 1, and feed a LoDTensor with data [[1], [2], [2], [3], [2], [1], [2]], lod [0, 3, 7].  And then I created the model like the language-model example did. 

The error info that came up to me is like :
paddle.fluid.core.EnforceNotMet: Enforce failed. Expected ids_dims[ids_rank - 1] == 1, but received ids_dims[ids_rank - 1]:0 != 1:1.
The last dimension of the 'Ids' tensor must be 1. at [/paddle/paddle/fluid/operators/lookup_table_op.cc:39]
PaddlePaddle Call Stacks:
0       0x7f6652156d86p paddle::platform::EnforceNotMet::EnforceNotMet(std::__exception_ptr::exception_ptr, char const*, int) + 486
1       0x7f665232663ep paddle::operators::LookupTableOp::InferShape(paddle::framework::InferShapeContext*) const + 1470
2       0x7f6652b29a69p paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&) const + 73
3       0x7f6652b2600fp paddle::framework::OperatorBase::Run(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&) + 255
4       0x7f66529c0504p
5       0x7f66529c00bfp paddle::framework::details::ComputationOpHandle::RunImpl() + 95
6       0x7f66529dd10cp paddle::framework::details::OpHandleBase::Run(bool) + 28
7       0x7f665299fabap
8       0x7f665289f583p std::_Function_handler<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> (), std::__future_base::_Task_setter<std::unique_ptr<std::__future_base::_Result<void>, std::__future_base::_Result_base::_Deleter>, void> >::_M_invoke(std::_Any_data const&) + 35
9       0x7f6652288487p std::__future_base::_State_base::_M_do_set(std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> ()>&, bool&) + 39
10      0x7f66b4c70b23p pthread_once + 83
11      0x7f665299e8c2p
12      0x7f6652289c64p ThreadPool::ThreadPool(unsigned long)::{lambda()#1}::operator()() const + 404
13      0x7f6697d27c5cp
14      0x7f66b4c6b851p
15      0x7f66b432e67dp clone + 109

Any help is useful. Thanks!

**Comment by tensor-tang** [comment]
could you show us the test script

**Comment by zhoukunsheng** [comment]
![image](https://user-images.githubusercontent.com/29747927/45799050-c2194e00-bcde-11e8-8ac4-e37dc42aa79c.png)

![image](https://user-images.githubusercontent.com/29747927/45799083-dbba9580-bcde-11e8-893d-071ea46bed55.png)

![image](https://user-images.githubusercontent.com/29747927/45799123-fab92780-bcde-11e8-994f-9fe52e4fe71f.png)

**Comment by tensor-tang** [comment]
问题已复现

**Comment by luotao1** [comment]
可以参考 #13312 关于feed lod的说明。 @shanyi15 这部分文档比较着急，请优先考虑。

**Comment by tensor-tang** [comment]
分析了下发现shape的定义什么的都没有问题，但是dataset是自定义，在code中打出来的dim[0]为-1，应该是自定义dataset处理的问题。

建议参考下https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/dataset/imikolov.py#L83 的实现
