### ISSUE TITLE
训练成功完成后hang住时间太长被kill

### ISSUE THREAD

**Issue by sinoautom** [PaddlePaddle/Paddle#13519]
日志链接：
http://10.182.6.161:8900/fileview.html?path=/home/disk1/normandy/maybach/app-user-20180920120410-18991/

任务训练完成后一直hang住，直到被kill，训练返回＝0；

**Comment by typhoonzero** [comment]
您好，请参考最新文档：https://github.com/PaddlePaddle/FluidDoc/blob/develop/doc/fluid/user_guides/howto/training/cluster_quick_start.rst

需要在训练完成后加`exe.close()`调用。

PS: 该文档会在最近发布到官方文档：http://www.paddlepaddle.org/documentation/docs/zh/0.15.0/user_guides/howto/training/cluster_quick_start.html

**Comment by lucywsq** [comment]
您好，此issue在近一个月内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题，我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持!
