### ISSUE TITLE
Mac OS docker build from source error

### ISSUE THREAD

**Issue by MaybeShewill-CV** [PaddlePaddle/Paddle#13529]
Mac OS version:10.13.6
docker version:18.06.1-ce
paddle fluid version: 0.15.0
cmake command: cmake .. -DWITH_FLUID_ONLY=ON -DWITH_GPU=OFF -DWITH_TESTING=OFF
docker command: docker run --name paddle-test -v $PWD:/paddle --network=host -it hub.baidubce.com/paddlepaddle/paddle:latest-dev /bin/bash
make error terminal: 
![make_err_log](https://user-images.githubusercontent.com/15725187/45867548-45f23980-bdb6-11e8-9f79-a9db32bfb331.jpg)

**Comment by JiabinYang** [comment]
能发一下完整的log么

**Comment by JiabinYang** [comment]
看起来是运行时内存不足造成的

**Comment by MaybeShewill-CV** [comment]
@JiabinYang 编译的时候没有记录log 明天重新编译一下记录完发上来,整个编译过程一直都没有什么报错信息，就是到link paddle_python.so的时候被kill了==！

**Comment by MaybeShewill-CV** [comment]
@JiabinYang I completely removed the docker image and recompiled paddle fluid 0.15.0 again and the compile process still got stuck.
<img width="730" alt="machi 2018-10-09 15-29-48" src="https://user-images.githubusercontent.com/15725187/46653459-aff14800-cbd8-11e8-92f1-d8238ecbf472.png">
<img width="730" alt="machi 2018-10-09 15-31-07" src="https://user-images.githubusercontent.com/15725187/46653467-b7185600-cbd8-11e8-8265-b5cef696c076.png">
Could you please provider some instructions here? Thanks :)

**Comment by MaybeShewill-CV** [comment]
@JiabinYang CMake flag is just the same as the install instruction here http://paddlepaddle.org/documentation/docs/zh/0.15.0/beginners_guide/install/install_doc.html

**Comment by JiabinYang** [comment]
您需要在docker下分配至少30G的磁盘空间来保证编译：
![2018-11-05 3 21 49](https://user-images.githubusercontent.com/22361972/47983518-8a3f5c00-e10e-11e8-9cd4-5f299ec78570.png)

**Comment by MaybeShewill-CV** [comment]
@JiabinYang I have successfully compiled the new paddle fluid release 1.0:) Thanks a lot~
