### ISSUE TITLE
Need to pass trainer's endpoints to executor.close()

### ISSUE THREAD

**Issue by gongweibao** [PaddlePaddle/Paddle#13526]
https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/fluid/framework/executor.cc#L52

Need to pass trainer's endpoints to it!

https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/fluid/operators/distributed/grpc_client.cc#L42

It's a potential bug.

**Comment by typhoonzero** [comment]
Need a real scenario.
