### ISSUE TITLE
paddle训练cpu dnn网络，每次到固定位置出现Floating point exception错误

### ISSUE THREAD

**Issue by zds9204** [PaddlePaddle/Paddle#13547]
在使用paddle训练cpu dnn网络时，设置batch size=512时，训练到第3420个batch时，出现如下错误：
Thread [140327239198464] Forwarding __fc_layer_10__, 
*** Aborted at 1537716648 (unix time) try "date -d @1537716648" if you are using GNU date ***
PC: @                0x0 (unknown)
*** SIGFPE (@0x7fa060dd4827) received by PID 855 (TID 0x7fa07b3ea700) from PID 1625114663; stack trace: ***
    @     0x7fa097242500 (unknown)
    @     0x7fa060dd4827 paddle::vTanh<>()
    @     0x7fa060da59b3 paddle::CpuMatrix::tanh()
    @     0x7fa060c6773c paddle::tanhActivation::forward()
    @     0x7fa060b911c9 paddle::Layer::forwardActivation()
    @     0x7fa060b61870 paddle::FullyConnectedLayer::forward()
    @     0x7fa060c715dd paddle::NeuralNetwork::forward()
    @     0x7fa060c7c3b4 paddle::TrainerThread::forward()
    @     0x7fa060c7d615 paddle::TrainerThread::computeThread()
    @     0x7fa06ed0d470 (unknown)
    @     0x7fa09723a851 start_thread
    @     0x7fa0968fd90d clone
    @                0x0 (unknown)
/root/paddlejob/run.sh: line 240:   855 Floating point exception(core dumped) python train.py

如果将batch size改为1024，会在1710个batch出现同样的错误

开始怀疑为梯度爆炸，但是在网络中加入bn层后，错误仍然出现在同样位置。而后根据 [paddle文档](http://www.paddlepaddle.org/documentation/docs/zh/0.12.0/faq/local/index_cn.html#floating-point-exception) 中提到的方法，加入gradient_clipping_threshold=10.0 参数，进行梯度截断，而后错误位置不变，但是内容变为：

*** Aborted at 1537719996 (unix time) try "date -d @1537719996" if you are using GNU date ***
PC: @                0x0 (unknown)
*** SIGSEGV (@0x8) received by PID 840 (TID 0x7f2e5704c700) from PID 8; stack trace: ***
    @     0x7f2e98947500 (unknown)
    @     0x7f2e623e5d62 paddle::ProtoClient::recv()
    @     0x7f2e6267c704 paddle::ParameterClient2::sendParallel()
    @     0x7f2e624eaaac _ZNSt6thread5_ImplISt12_Bind_simpleIFZN6paddle14SyncThreadPool5startEvEUliE_mEEE6_M_runEv
    @     0x7f2e70412470 (unknown)
    @     0x7f2e9893f851 start_thread
    @     0x7f2e9800290d clone
    @                0x0 (unknown)
/root/paddlejob/run.sh: line 240:   840 Segmentation fault      (core dumped) python train.py
*********************error messages********************
[/root/paddlejob/run.sh : 243] [start_trainer]
[ERROR]: execute user cmd failed, Mon Sep 24 00:26:38 CST 2018

希望开发者能给出这种错误的原因和修正方法

**Comment by zds9204** [comment]
每次出现错误的batch数不变

**Comment by typhoonzero** [comment]
可以跳过当前batch的数据再看下，是否仍然存在，排除异常数据的影响。

**Comment by zds9204** [comment]
跳过batch有效。已排查出问题，为输入的原始数据中有NaN导致
