### ISSUE TITLE
关于Argument.h中的参数问题

### ISSUE THREAD

**Issue by IBITM** [PaddlePaddle/Paddle#1354]
在结构体Argument，其参数ids起什么作用，并且其值由什么决定？

**Comment by wangkuiyi** [comment]
Argument类型是PaddlePaddle里每个Layer的输入类型和输出类型。

因为不同的layer的输入和输出类型不同，所以Argument里包括了各种类型的数据：

```
Argument {
   MatrixPtr value;
   IVectorPtr ids;
   IVectorPtr sequenceStartPosition;
   ...
}
```

举个例子可能可以解释得更清楚一些。假设我们要训练一个DNN做图像识别。可以想象这个网络的输入层（一个layer.data对象）接收的是一幅图片；这个网络的cost层需要接收一个label。为了表示一幅图像，我们会生成一个Argument对象，并且用图像数据填充其中的`value` field。为了表示一个label，我们会生成另一个Argument对象，并且填充用label填充其中的`ids` field。

类似的，·sequenceStartPosition`是Argument作为RNN的输入时需要填充的。

逻辑上，Argument其实应该是一个union类型，而不是一个struct或者class类型。而且最好其中每个field对应一种data layer type。不过之前的工程工作里，我们没有注意好这些方面。欢迎大家来帮助我们把这块代码的逻辑修正得更清楚一些。
