### ISSUE TITLE
集群训练与本地不一致 check failed: simd:vec_check(width) 1

### ISSUE THREAD

**Issue by zhangyong15** [PaddlePaddle/Paddle#1355]
本地启动paddle可以正常运行，迁移至集群进行训练，报下述问题，是否由于集群和本地版本不一致所导致的？望解答。

![1](https://cloud.githubusercontent.com/assets/22140712/23050749/250021dc-f4ff-11e6-90e0-afdf095e5733.png)

本地使用master版本，集群paddle版本如下：
<img width="333" alt="027edf4c54249723ee4f8fed825548b5" src="https://cloud.githubusercontent.com/assets/22140712/23050699/ed81ea10-f4fe-11e6-9a2e-493b6404f03a.png">

**Comment by gangliao** [comment]
除了版本可能不一致以外，也有可能是数据本身的长度问题。

但是最新develop分支是没有这个问题的。

@zhangyong15

**Comment by qingqing01** [comment]
可以看下集群是否支持AVX~

**Comment by gangliao** [comment]
@qingqing01  不是AVX的问题，是之前sparse对长度有限制

**Comment by zhangyong15** [comment]
@gangliao @qingqing01 已经确认过了，集群数据与本地的paddle版本使用的数据并无差别，我还是不理解这个问题的原因，麻烦看一下啊。

**Comment by zhangyong15** [comment]
更新集群版本得到解决
