### ISSUE TITLE
Question on test_text_classification

### ISSUE THREAD

**Issue by jczaja** [PaddlePaddle/Paddle#13551]
How can I run Test_text_classification with diffrent batch size than 1 eg. 32 ?

There is an enforce to have batch_size = 1 :
https://github.com/PaddlePaddle/Paddle/blob/d6358541f9597aeac05ce7ca3d3d72053daf92fe/paddle/fluid/inference/tests/api/analyzer_text_classification_tester.cc#L25

I need that to test BatchCompute path of fusion_lstm_op 

Please advice ,

**Comment by luotao1** [comment]
We will update this unit-test ASAP.

**Comment by jczaja** [comment]
Ok, thanks
