### ISSUE TITLE
PythonUtil 可疑内存泄漏

### ISSUE THREAD

**Issue by viennadd** [PaddlePaddle/Paddle#1356]
我们扫描到一处可疑的内存泄漏，在 [PythonUtil.cpp.in#L78](https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/utils/PythonUtil.cpp.in#L78) 里的`printPyErrorStack ` 函数，strdup 需要和 free 通常成对使用，但这里可能缺少了free，希望查询一下

```c
...
    os << "Current PYTHONPATH: " << py::repr(PySys_GetObject(strdup("path")));
....
```

**Comment by reyoung** [comment]
这里确实有一个内存泄露，不过当时考虑因为这个函数调用实际在程序coredump之前(程序出错退出时打印的log)，所以，即使有内存泄露也无所谓了。

不过，也可以改成static的。麻烦 @gangliao  和 #1357 一并修改了吧。THX

**Comment by Canpio** [comment]
Close the issue for the bug has been fixed. Please feel free to reopen.
