### ISSUE TITLE
Picture is invalid on doc of 0.13.0

### ISSUE THREAD

**Issue by JiabinYang** [PaddlePaddle/Paddle#13565]
http://paddlepaddle.org/documentation/docs/zh/0.13.0/design/motivation/refactorization.html

<img width="934" alt="2018-09-25 3 55 14" src="https://user-images.githubusercontent.com/22361972/46001181-43a51d80-c0dd-11e8-9518-089ec2008393.png">

**Comment by shanyi15** [comment]
感谢反馈，正在排查。
