### ISSUE TITLE
CAPI CRNN-CTC application

### ISSUE THREAD

**Issue by tpatejko** [PaddlePaddle/Paddle#13574]
Is `analyzer_vis_tester.cc` an implementation of CRNN-CTC in CAPI? If yes, where can I find trained model and data for inference for that model.

**Comment by luotao1** [comment]
Sorry, `analyzer_vis_tester.cc` is not an implementation of CRNN-CTC in CAPI.
For CRNN-CTC:
- dataset: http://paddle-ocr-data.bj.bcebos.com/data.tar.gz
- readme of dataset: https://github.com/PaddlePaddle/models/tree/develop/fluid/ocr_recognition#%E6%95%B0%E6%8D%AE
- params: http://paddle-ocr-data.bj.bcebos.com/crnn_ctc_params.tar.gz
- program_desc: you can save the program_desc from python side at first.

**Comment by tpatejko** [comment]
Thank! Do you have any CAPI CRNN-CTC application?

**Comment by tpatejko** [comment]
@luotao1 What is the difference between `analyzer_vis_tester` and CRNN-CTC model? If I understand correctly both are OCR models?

**Comment by luotao1** [comment]
Their layers are different. The layer in `analyzer_vis_tester` is:
```
feed
conv2d
elementwise_add
relu
conv2d
elementwise_add
relu
conv2d
elementwise_add
relu
conv2d
elementwise_add
relu
conv2d
elementwise_add
relu
pool2d
conv2d
elementwise_add
relu
conv2d
elementwise_add
relu
conv2d
elementwise_add
relu
conv2d
elementwise_add
relu
conv2d
elementwise_add
relu
pool2d
conv2d
elementwise_add
relu
conv2d
elementwise_add
relu
conv2d
elementwise_add
relu
conv2d
elementwise_add
relu
conv2d
elementwise_add
relu
pool2d
conv2d
elementwise_add
relu
conv2d
elementwise_add
relu
conv2d
elementwise_add
relu
conv2d
elementwise_add
relu
conv2d
elementwise_add
relu
im2sequence
mul
elementwise_add
mul
elementwise_add
gru
gru
mul
mul
sum
elementwise_add
softmax
fetch
```

**Comment by tpatejko** [comment]
If I remember correctly, CRNN-CTC in Baidu's model repository also has convolution part, im2sequence layer and two GRU operators with forward and backward directions. 

Is the difference that CRNN-CTC uses CTC for classification and `analyzer_vis_tester` uses softmax?

**Comment by luotao1** [comment]
The layers in CRNN-CTC:
```
feed
conv2d
elementwise_add
relu
conv2d
elementwise_add
relu
pool2d
conv2d
elementwise_add
relu
conv2d
elementwise_add
relu
pool2d
conv2d
elementwise_add
relu
conv2d
elementwise_add
relu
pool2d
conv2d
elementwise_add
relu
conv2d
elementwise_add
relu
im2sequence
mul
elementwise_add
mul
elementwise_add
gru
gru
mul
mul
sum
elementwise_add
softmax
top_k
ctc_align
cast
fetch
fetch
```
> Is the difference that CRNN-CTC uses CTC for classification and analyzer_vis_tester uses softmax

Yes, but there are some other difference. You can diff these two layers.

**Comment by tpatejko** [comment]
Thanks a lot for the information!

**Comment by tpatejko** [comment]
@luotao1 Are you working on any CAPI CRNN-CTC application?
Are you planning to deploy any of the models mentioned above (CRNN-CTC and vis model), and if so, which one?

**Comment by luotao1** [comment]
I close this issue since we are not working on any CRNN-CTC application recently. @tpatejko If you have further questions, please feel free to reopen it.
