### ISSUE TITLE
paddle local运行

### ISSUE THREAD

**Issue by wuhabi** [PaddlePaddle/Paddle#1358]
按照http://deeplearning.baidu.com/doc/local_binary.html 的说明进行了单机二进制安装。试图跑一个最简单的程序，于是将 https://github.com/PaddlePaddle/Paddle/tree/develop/demo/ 中的introduction目录下载下来，运行命令sh train.sh，得到如下错误：/home/users/wuhaibing/paddle/output/bin/paddle_local: line 81: 18521 Illegal instruction     (core dumped) ${DEBUGGER} $MYDIR/../opt/paddle/bin/paddle_trainer ${@:2}

**Comment by gangliao** [comment]
这个原因可能是因为 提供的二进制需要本机支持AVX指令。而你的机器上不支持AVX指令。

解决方案：使用icode里面的baidu/gangliao/paddle_internal_release_tools 一键编译脚本

@wuhabi

**Comment by Yancey1989** [comment]
现在可以使用Paddle的Docker image: `paddlepaddle/paddle:0.10.0rc3-noavx`, 先关闭这个issue，如果有问题再开发吧：）
