### ISSUE TITLE
Adding Python 3 wheels to PyPi

### ISSUE THREAD

**Issue by mirekphd** [PaddlePaddle/Paddle#13604]
Currently there are only Python 2.7 versions there...
(see. e.g. https://pypi.org/project/paddlepaddle-gpu/0.15.0.post97/#files )

_Originally posted by @mirekphd in https://github.com/PaddlePaddle/Paddle/issues/12040#issuecomment-424287180_

**Comment by kuke** [comment]
We will add the py3 version for the release 0.15 later.

**Comment by velconia** [comment]
After abundant test in Python3 we will release it in 0.15.0, so it will be later than the release time of Python2.

And the release time of Python3 in 1.0.0 will be the same as Python2 in 1.0.0

**Comment by velconia** [comment]
[We have supported Python3 installation](https://github.com/PaddlePaddle/Paddle/issues/12040) now. PaddlePaddle for Python3 could be installed via ```pip3 install paddlepaddle``` or ```pip3 install paddlepaddle-gpu```. 

This question will be closed. If you still need to follow up on this question after closing, please feel free to reopen it.Thank you so much for your support of PaddlePaddle Group!
