### ISSUE TITLE
get_app_port_bin failed

### ISSUE THREAD

**Issue by sinoautom** [PaddlePaddle/Paddle#13612]
上午运行成功的任务，今天提交报错 get_app_port_bin failed
日志地址：http://10.182.13.147:8900/fileview.html?path=/home/disk1/normandy/maybach/app-user-20180926200628-479/

**Comment by gongweibao** [comment]
get_app_port_bin 这个程序应该是HPC的同学提供的。不是paddle提供的。要不你问一下HPC的同学？

**Comment by lucywsq** [comment]
您好，此issue在近一个月内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题，我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持!
