### ISSUE TITLE
ResNet50 pre-trained weight inference error in python

### ISSUE THREAD

**Issue by sfraczek** [PaddlePaddle/Paddle#13617]
Hi,
Resnet50 eval result is wierd on pre-trained weights from https://github.com/PaddlePaddle/models/tree/develop/fluid/image_classification. I have downloaded **develop branch for both Paddle and models** 

When I try eval:
```
CPU_NUM=1 FLAGS_use_mkldnn=0 python eval.py \                
--use_gpu False \
--batch_size 32 \
--model ResNet50 \
--pretrained_model models/resnet_50/115
```
I get
```
Testbatch 0,loss 17.3628101349, acc1 0.03125,acc5 0.03125,time 11.99 sec
Testbatch 10,loss 16.5818500519, acc1 0.0,acc5 0.0,time 10.16 sec
Testbatch 20,loss 16.7979774475, acc1 0.0,acc5 0.0,time 10.11 sec
```

**Comment by luotao1** [comment]
You can refer to https://github.com/PaddlePaddle/models/issues/1223

**Comment by sfraczek** [comment]
Thank you very much for pointing me to this @luotao1. It seems we have some work to do on improving our internal communication.
