### ISSUE TITLE
Trainer和save_inference_model的疑问

### ISSUE THREAD

**Issue by SnailTowardThesun** [PaddlePaddle/Paddle#13611]
使用fluid.Trainer进行训练，训练完成后，只能调用fluid.Trainer.save_params()进行保存，而没函数与fluid.io.save_inference_model对应。想请教下，该如何操作，才能生成__model__文件，供C++接口使用？

**Comment by kuke** [comment]
建议用通用API，这个high level api用的是save_persistables(), 没法保存inference model

**Comment by luotao1** [comment]
两种API的区别可以参考 [High/Low-level API简介](https://github.com/PaddlePaddle/FluidDoc/blob/develop/doc/fluid/api_guides/high_low_level_api.md)

**Comment by SnailTowardThesun** [comment]
已经了解了，换为基础API去做
