### ISSUE TITLE
Assign placement on operator

### ISSUE THREAD

**Issue by Yancey0623** [PaddlePaddle/Paddle#13648]
tasks:
- [ ] design doc: https://github.com/PaddlePaddle/FluidDoc/pull/107
- [ ] Python API to assign place on operator: #13649 
- [ ] refine startup_program so that initializing the var on the valid place.
- [ ] Using a pass to insert the communicator (memcpy, send, listen_and_serv) at the boundary between ops which on the different place.

**Comment by panyx0718** [comment]
`place="/role:worker/gpu:0-7"`
Is there a formal format definition for the placement string?

Which model do you want to use it for? Can you give an example why it's required and how will it be realized?

**Comment by Yancey0623** [comment]
> Is there a formal format definition for the placement string?
> Which model do you want to use it for? Can you give an example why it's required and how will it be realized?

Thanks for review!
It updated them in the design doc: https://github.com/PaddlePaddle/FluidDoc/pull/107, and 
the op placement can be used on the model parallelism feature, for example: the models in face recognize model, there is a very larege sofmax layer which can not be place on GPU memory.

**Comment by panyx0718** [comment]
The solution is very similar to tensorflow. How does other framework handle model parallelism?
