### ISSUE TITLE
transformer 加上内存优化后的loss值与不加相差较大

### ISSUE THREAD

**Issue by kolinwei** [PaddlePaddle/Paddle#13669]
之前0.15版本的transformer。
不加内存优化前6个batch的loss值:
[9.574362, 9.552914, 9.515497, 9.539991, 9.502448, 9.493856]
加上后变为:
61298.586, 61925.836, 62752.34, 62703.094, 62897.477, 62393.04]

**Comment by reyoung** [comment]
确定loss.persistable = True么？

**Comment by dzhwinter** [comment]
https://github.com/PaddlePaddle/models/tree/develop/fluid/neural_machine_translation/transformer
使用官方的transformer加memory_optimize没有问题，@kolinwei 同样复现了该结果。issue中描述的问题是test case只用了官网例子的transformer中的一部分，模型配置有diff。
