### ISSUE TITLE
如何获取提供模型的形状、各层的名字等信息

### ISSUE THREAD

**Issue by lance6716** [PaddlePaddle/Paddle#13665]
文档里完全没有找到，fluid.io只能把它加载给executor，然而我都不知道形状和输入层的名字，该怎么让executor跑起来。

**Comment by wanghaoshuang** [comment]
通过fluid.io load模型之后，可以通过通过以下方式遍历parameters:
```
for param in fluid.default_main_program().global_block().all_parameters():
    print param.shape
    print param.name
```

或者打印网络中每个op的详细信息：
```
print  fluid.default_main_program()
```

**Comment by lucywsq** [comment]
您好，此issue若已经解决，我们将于三天内关闭。若在关闭后您仍需跟进 提问，可重新开启此问题，
我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持!
