### ISSUE TITLE
关于expand_layer类的功能的疑惑

### ISSUE THREAD

**Issue by lcxaiw** [PaddlePaddle/Paddle#1367]
expand_layer类在文档中的解释为 A layer for “Expand Dense data or (sequence data where the length of each sequence is one) to sequence data.”
由于没有数学表达，不太明白这句话的意思
他是说 可以把一个稠密向量或者一个长度为1的序列数据转换为一个序列数据嘛？
那么找了很久，也没找到paddle中将序列拼接的类是哪一个？不是concat那种
seq1 = [vec1_1,vec1_2]
seq2 = [vec2_1,vec2_2]
seq = layer(seq1,seq2) = [vec1_1,vec1_2,vec2_1.vec2_2]
paddle中有关于这个功能的实现嘛？
望解答，谢谢

**Comment by luotao1** [comment]
expand_layer的意思：input1是稠密向量，input是序列数据。那么output的序列形式和input2的一样，序列中的每一个数据和input1的一样。

Paddle中有SequenceConcatLayer，不过实现的是：
seq1 = [vec1_1,vec1_2]
seq2 = [vec2_1,vec2_2]
seq = layer(seq1,seq2) = [vec1_1,vec2_1,vec1_2.vec2_2]

**Comment by lcxaiw** [comment]
@luotao1 谢谢，我查找到了这个类，但发现在官方文档里这些类只有接口和函数实现的说明，并没有说怎么去调用它们，请问有相应的方法可以知道它们的调用方式嘛？

**Comment by luotao1** [comment]
sequenceConcatLayer这个类没有最新的调用接口，会尽快补上的。

**Comment by lcxaiw** [comment]
@luotao1 是内部已经实现好了，没有文档，还是还没实现好？如果实现好了只是没有文档的话，望周知

**Comment by luotao1** [comment]
[layers.py](https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/trainer_config_helpers/layers.py)中还没有这个接口。尽快补上，补上后通知您。

**Comment by lcxaiw** [comment]
@luotao1 好的，谢谢

**Comment by luotao1** [comment]
@lcxaiw 已经加了接口，见[layers.py](https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/trainer_config_helpers/layers.py#L2579)。用法如下：
```
concat = seq_concat_layer(a=layer1, b=layer2)
```

**Comment by lcxaiw** [comment]
@luotao1 谢谢，辛苦了

**Comment by HynUx** [comment]
补充下, V2里这个似乎已经变成了seq_concat
paddle.v2.layer.seq_concat
