### ISSUE TITLE
internal error in RPCClient

### ISSUE THREAD

**Issue by jeff41404** [PaddlePaddle/Paddle#13676]
paddle version 0.15
模型：https://github.com/PaddlePaddle/models/tree/develop/fluid/DeepASR
作业运行配置：2个pserver，5个trainer，每个trainer 1卡
作业运行在Paddle cloud上，作业ID：job-e6c5badca934519f，在第1个pass所有batch运行完的时候报错
在 单机 或 Paddle cloud多机小数据量跑则训练正常

![rpc error](https://user-images.githubusercontent.com/8555991/46239899-24a2d600-c3d2-11e8-94cf-602b3420510f.JPG)

其它类似的issue：
https://github.com/PaddlePaddle/Paddle/issues/12679

**Comment by seiriosPlus** [comment]
在作业配置里面加入：
FLAGS_rpc_deadline=30000000

**Comment by lucywsq** [comment]
您好，此issue若已经解决，我们将于三天内关闭。若在关闭后您仍需跟进 提问，可重新开启此问题，
我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持!
