### ISSUE TITLE
多线程下RecordIO的reader进行reset操作后无法读取数据

### ISSUE THREAD

**Issue by xiaoyao4573** [PaddlePaddle/Paddle#13680]
train_exe = fluid.ParallelExecutor(
            use_cuda=False,
            loss_name=train_avg_loss.name,
            main_program=train_program)
    test_exe = fluid.ParallelExecutor(
            use_cuda=False,
            main_program=test_program,
            share_vars_from=train_exe)

    for epoch in xrange(100):
        try:
            while True:
                train_loss_v = train_exe.run(return_numpy=False, fetch_list=[train_loss.name])
        except fluid.core.EOFException:
            # 触发了EOFException以后似乎还有线程没有完成训练。
            train_reader.reset() #这里reset后在下一个epoch没有读入任何数据。

        try:
            while True:
                test_loss_v = test_exe.run(return_numpy=False, fetch_list=[test_loss.name])
        except paddle.fluid.core.EOFException:
            test_reader.reset()

**Comment by sneaxiy** [comment]
建议您使用fluid的py_reader进行数据读取，recordio相关的接口后期可能不再维护了。
py_reader的使用方式请参考：https://github.com/PaddlePaddle/FluidDoc/blob/develop/doc/fluid/user_guides/howto/prepare_data/use_py_reader.rst

**Comment by lucywsq** [comment]
您好，此issue若已经解决，我们将于三天内关闭。若在关闭后您仍需跟进 提问，可重新开启此问题，
我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持!
