### ISSUE TITLE
paddle编译成功，但运行时Python Error: <type 'exceptions.ImportError'> : /lib64/tls/libc.so.6: version `GLIBC_2.14' not found

### ISSUE THREAD

**Issue by wuhabi** [PaddlePaddle/Paddle#1369]
编译成功。但运行时遇到问题Python Error: <type 'exceptions.ImportError'> : /lib64/tls/libc.so.6: version `GLIBC_2.14' not found
<img width="1256" alt="screen shot 2017-02-19 at 11 31 27 am" src="https://cloud.githubusercontent.com/assets/7334845/23098996/433cd296-f697-11e6-90a0-3e2f4bee4539.png">

**Comment by 17Skye17** [comment]
I am facing the same issue #1349

**Comment by reyoung** [comment]
Duplicated with #1349. We will fix this problem in #1349.
