### ISSUE TITLE
fluid多卡训练报错

### ISSUE THREAD

**Issue by jeff41404** [PaddlePaddle/Paddle#13716]
使用 fluid.Executor 单卡训练没有问题，改为 fluid.ParallelExecutor 多卡训练报错
帮忙看看是什么问题
paddle.fluid.core.EnforceNotMet: Enforce failed. Expected 1 == framework::product(ctx->GetInputDim("X")), but received 1:1 != framework::product(ctx->GetInputDim("X")):0.

![ctx error](https://user-images.githubusercontent.com/8555991/46256454-db3fad00-c4dd-11e8-90ac-3ce676e1cd58.JPG)

**Comment by lucywsq** [comment]
您好，问题已经收到，我们将尽快反馈~

**Comment by lucywsq** [comment]
您好，此issue在近一个月内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题，我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持!
