### ISSUE TITLE
pip install error ,Is there a plan to support python3?

### ISSUE THREAD

**Issue by SantiagoFan** [PaddlePaddle/Paddle#13728]
OS:CentOS7
pip install Error:

Could not find a version that satisfies the requirement paddlepaddle (from versions: )
No matching distribution found for paddlepaddle

**Comment by velconia** [comment]
[We have supported Python3 installation](https://github.com/PaddlePaddle/Paddle/issues/12040) now. PaddlePaddle for Python3 could be installed via ```pip3 install paddlepaddle``` or ```pip3 install paddlepaddle-gpu```. 

This question will be closed. If you still need to follow up on this question after closing, please feel free to reopen it.Thank you so much for your support of PaddlePaddle Group!
