### ISSUE TITLE
在gpu服务器上训练的目标检测模型挪到普通服务器报错

### ISSUE THREAD

**Issue by Luis-zhang** [PaddlePaddle/Paddle#13729]
两边都用的paddlepaddle0.15.0
下面是报错信息：
开始初始化！
I1003 17:13:25.759611 95924 Util.cpp:166] commandline:  --use_gpu=False --trainer_count=2 
初始化完成
开始预测
[INFO 2018-10-03 17:13:25,765 layers.py:2716] output for conv1_1: c = 64, h = 300, w = 300, size = 5760000
[INFO 2018-10-03 17:13:25,766 layers.py:2716] output for conv1_2: c = 64, h = 300, w = 300, size = 5760000
[INFO 2018-10-03 17:13:25,767 layers.py:2858] output for pool1: c = 64, h = 150, w = 150, size = 1440000
[INFO 2018-10-03 17:13:25,768 layers.py:2716] output for conv2_1: c = 128, h = 150, w = 150, size = 2880000
[INFO 2018-10-03 17:13:25,771 layers.py:2716] output for conv2_2: c = 128, h = 150, w = 150, size = 2880000
[INFO 2018-10-03 17:13:25,771 layers.py:2858] output for pool2: c = 128, h = 75, w = 75, size = 720000
[INFO 2018-10-03 17:13:25,773 layers.py:2716] output for conv3_1: c = 256, h = 75, w = 75, size = 1440000
[INFO 2018-10-03 17:13:25,774 layers.py:2716] output for conv3_2: c = 256, h = 75, w = 75, size = 1440000
[INFO 2018-10-03 17:13:25,775 layers.py:2716] output for conv3_3: c = 256, h = 75, w = 75, size = 1440000
[INFO 2018-10-03 17:13:25,776 layers.py:2858] output for __pool_0__: c = 256, h = 38, w = 38, size = 369664
[INFO 2018-10-03 17:13:25,777 layers.py:2716] output for conv4_1: c = 512, h = 38, w = 38, size = 739328
[INFO 2018-10-03 17:13:25,777 layers.py:2716] output for conv4_2: c = 512, h = 38, w = 38, size = 739328
[INFO 2018-10-03 17:13:25,778 layers.py:2716] output for conv4_3: c = 512, h = 38, w = 38, size = 739328
[INFO 2018-10-03 17:13:25,779 layers.py:2858] output for __pool_1__: c = 512, h = 19, w = 19, size = 184832
[INFO 2018-10-03 17:13:25,781 layers.py:2716] output for conv4_3_norm_mbox_loc: c = 12, h = 38, w = 38, size = 17328
[INFO 2018-10-03 17:13:25,781 layers.py:2716] output for conv4_3_norm_mbox_conf: c = 6, h = 38, w = 38, size = 8664
[INFO 2018-10-03 17:13:25,782 layers.py:2716] output for conv5_1: c = 512, h = 19, w = 19, size = 184832
[INFO 2018-10-03 17:13:25,783 layers.py:2716] output for conv5_2: c = 512, h = 19, w = 19, size = 184832
[INFO 2018-10-03 17:13:25,784 layers.py:2716] output for conv5_3: c = 512, h = 19, w = 19, size = 184832
[INFO 2018-10-03 17:13:25,785 layers.py:2858] output for __pool_2__: c = 512, h = 19, w = 19, size = 184832
[INFO 2018-10-03 17:13:25,786 layers.py:2716] output for fc6: c = 1024, h = 19, w = 19, size = 369664
[INFO 2018-10-03 17:13:25,786 layers.py:2716] output for fc7: c = 1024, h = 19, w = 19, size = 369664
[INFO 2018-10-03 17:13:25,787 layers.py:2716] output for fc7_mbox_loc: c = 24, h = 19, w = 19, size = 8664
[INFO 2018-10-03 17:13:25,788 layers.py:2716] output for fc7_mbox_conf: c = 12, h = 19, w = 19, size = 4332
[INFO 2018-10-03 17:13:25,789 layers.py:2716] output for conv6_1: c = 256, h = 19, w = 19, size = 92416
[INFO 2018-10-03 17:13:25,790 layers.py:2716] output for conv6_2: c = 512, h = 10, w = 10, size = 51200
[INFO 2018-10-03 17:13:25,791 layers.py:2716] output for conv6_2_mbox_loc: c = 24, h = 10, w = 10, size = 2400
[INFO 2018-10-03 17:13:25,791 layers.py:2716] output for conv6_2_mbox_conf: c = 12, h = 10, w = 10, size = 1200
[INFO 2018-10-03 17:13:25,792 layers.py:2716] output for conv7_1: c = 128, h = 10, w = 10, size = 12800
[INFO 2018-10-03 17:13:25,793 layers.py:2716] output for conv7_2: c = 256, h = 5, w = 5, size = 6400
[INFO 2018-10-03 17:13:25,794 layers.py:2716] output for conv7_2_mbox_loc: c = 24, h = 5, w = 5, size = 600
[INFO 2018-10-03 17:13:25,795 layers.py:2716] output for conv7_2_mbox_conf: c = 12, h = 5, w = 5, size = 300
[INFO 2018-10-03 17:13:25,796 layers.py:2716] output for conv8_1: c = 128, h = 5, w = 5, size = 3200
[INFO 2018-10-03 17:13:25,797 layers.py:2716] output for conv8_2: c = 256, h = 3, w = 3, size = 2304
[INFO 2018-10-03 17:13:25,797 layers.py:2716] output for conv8_2_mbox_loc: c = 24, h = 3, w = 3, size = 216
[INFO 2018-10-03 17:13:25,798 layers.py:2716] output for conv8_2_mbox_conf: c = 12, h = 3, w = 3, size = 108
[INFO 2018-10-03 17:13:25,799 layers.py:2858] output for pool6: c = 256, h = 1, w = 1, size = 256
[INFO 2018-10-03 17:13:25,800 layers.py:2716] output for pool6_mbox_loc: c = 24, h = 1, w = 1, size = 24
[INFO 2018-10-03 17:13:25,800 layers.py:2716] output for pool6_mbox_conf: c = 12, h = 1, w = 1, size = 12
<generator object reader at 0x7f07924bb5f0>
Traceback (most recent call last):
  File "infer.py", line 146, in <module>
    threshold=0.3)
  File "infer.py", line 104, in infer
    for img in reader():
  File "/home/cloud/code/data_provider.py", line 93, in reader
    img = Image.open(img_path)
  File "/usr/local/lib/python2.7/dist-packages/PIL/Image.py", line 2657, in open
    % (filename if filename else fp))
IOError: cannot identify image file '../images/infer.txt'

**Comment by Luis-zhang** [comment]
```python
infer.py函数
# coding=utf-8
import gzip
import os

import numpy as np
import paddle.v2 as paddle
from PIL import Image
from pascal_voc_conf import cfg

import data_provider
import vgg_ssd_net


def _infer(inferer, infer_data, threshold):
    '''
    预测并返回预测结果
    :param inferer: 预测器
    :param infer_data: 要预测的数据
    :param threshold: 置信度阈值
    :return:
    '''
    ret = []
    # 获取预测原始结果
    infer_res = inferer.infer(input=infer_data)
    # 筛选预测结果
    keep_inds = np.where(infer_res[:, 2] >= threshold)[0]
    for idx in keep_inds:
        ret.append([
            infer_res[idx][0], infer_res[idx][1] - 1, infer_res[idx][2],
            infer_res[idx][3], infer_res[idx][4], infer_res[idx][5],
            infer_res[idx][6]
        ])
    return ret


def save_batch_res(ret_res, img_w, img_h, fname_list, fout):
    '''
    保存预测结果
    :param ret_res: 所有的预测结果
    :param img_w: 图像的宽
    :param img_h: 图像的高
    :param fname_list: 图像路径的list
    :param fout: 保存预测结果的文件
    :return:
    '''
    for det_res in ret_res:
        # 获取图像的idx
        img_idx = int(det_res[0])
        # 获取图像的label
        label = int(det_res[1])
        # 获取预测的得分
        conf_score = det_res[2]
        # 获取目标的框
        xmin = det_res[3] * img_w[img_idx]
        ymin = det_res[4] * img_h[img_idx]
        xmax = det_res[5] * img_w[img_idx]
        ymax = det_res[6] * img_h[img_idx]
        # 将预测结果写入到文件中
        fout.write(fname_list[img_idx] + '\t' + str(label) + '\t' + str(
            conf_score) + '\t' + str(xmin) + ' ' + str(ymin) + ' ' + str(xmax) +
                   ' ' + str(ymax))
        fout.write('\n')


def infer(eval_file_list, save_path, data_args, batch_size, model_path,threshold):
    '''
    预测图像
    :param eval_file_list: 指定图像路径列表
    :param save_path: 指定预测结果保存路径
    :param data_args: 配置数据预处理所需参数
    :param batch_size: 为每多少样本预测一次
    :param model_path: 指模型的位置
    :param threshold: 置信度阈值
    :return:
    '''
    # 通过网络模型获取输出层
    detect_out = vgg_ssd_net.net_conf(mode='infer')
    # 检查模型路径是否正确
    assert os.path.isfile(model_path), 'Invalid model.'
    # 加载训练好的参数
    parameters = paddle.parameters.Parameters.from_tar(gzip.open(model_path))
    # 或预测器
    inferer = paddle.inference.Inference(
        output_layer=detect_out, parameters=parameters)
    # 获取预测数据
    reader = data_provider.infer(data_args, eval_file_list)
    all_fname_list = [line.strip() for line in open(eval_file_list).readlines()]

    # 预测的数据
    test_data = []
    # 预测的图像路径list
    fname_list = []
    # 图像的宽
    img_w = []
    # 图像的高
    img_h = []
    # 图像的idx
    idx = 0
    '''按批处理推理，
    bbox的坐标将根据图像大小进行缩放
    '''
    with open(save_path, 'w') as fout:
        print(reader())
        for img in reader():
            test_data.append([img])
            fname_list.append(all_fname_list[idx])
            w, h = Image.open(os.path.join('../images', fname_list[-1])).size
            img_w.append(w)
            img_h.append(h)
            # 当数据达到一个batch后，就开始预测
            if len(test_data) == batch_size:
                ret_res = _infer(inferer, test_data, threshold)
                save_batch_res(ret_res, img_w, img_h, fname_list, fout)
                # 预测后要清空之前的数据
                test_data = []
                fname_list = []
                img_w = []
                img_h = []
            idx += 1

        # 剩下没有达到一个batch的在在最后也要预测
        if len(test_data) > 0:
            ret_res = _infer(inferer, test_data, threshold)
            save_batch_res(ret_res, img_w, img_h, fname_list, fout)


if __name__ == "__main__":
    print("开始初始化！")
    paddle.init(use_gpu=False, trainer_count=2)
    print("初始化完成")
    # 设置数据参数
    data_args = data_provider.Settings(
        data_dir='../images',
        label_file='../data/label_list',
        resize_h=cfg.IMG_HEIGHT,
        resize_w=cfg.IMG_WIDTH,
        mean_value=[104, 117, 124])
    print("开始预测")
    # 开始预测,batch_size只能设置为1，否则会数据丢失
    infer(
        eval_file_list='../images/infer.txt',
        save_path='../images/infer.res',
        data_args=data_args,
        batch_size=1,
        model_path='../models/params_pass.tar.gz',
        threshold=0.3)
```

**Comment by Superjomn** [comment]
```
File "/usr/local/lib/python2.7/dist-packages/PIL/Image.py", line 2657, in open
% (filename if filename else fp))
IOError: cannot identify image file '../images/infer.txt'
```

这是 Python PIL 库的报错，应该是你的文件路径没设对

**Comment by lucywsq** [comment]
您好，此issue在近一个月内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题，我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持!
