### ISSUE TITLE
edit_distance 文档中给的示例跑不了，能否提供一个能用的示例？

### ISSUE THREAD

**Issue by lgone2000** [PaddlePaddle/Paddle#13734]
![image](https://user-images.githubusercontent.com/11441133/46570583-e04aa380-c998-11e8-9d01-f8d7d4d27e8a.png)

```
def testeditdistance():
    x = fluid.layers.data(name='x', shape=[8], dtype='float32')
    y = fluid.layers.data(name='y', shape=[7], dtype='float32')
    cost = fluid.layers.edit_distance(input=x,label=y)
```
报错
paddle.fluid.core.EnforceNotMet: Input(Hyps) must be a 2-D LoDTensor with the 2nd dimension equal to 1. at [/sharefolder/Paddle/paddle/fluid/operators/edit_distance_op.cc:34]
PaddlePaddle Call Stacks: 
0       0x7fb194c2c646p paddle::platform::EnforceNotMet::EnforceNotMet(std::__exception_ptr::exception_ptr, char const*, int) + 486
1       0x7fb194f94303p paddle::operators::EditDistanceOp::InferShape(paddle::framework::InferShapeContext*) const + 1011
2       0x7fb194ce0d66p paddle::framework::OpDesc::InferShape(paddle::framework::BlockDesc const&) const + 902
3       0x7fb194c8d1e5p void pybind11::cpp_function::initialize<pybind11::cpp_function::initialize<void, paddle::framework::OpDesc, paddle::framework::BlockDesc const&, pybind11::name, pybind11::is_method, 3
4       0x7fb194c41af4p pybind11::cpp_function::dispatcher(_object*, _object*, _object*) + 2596

**Comment by velconia** [comment]
```
def testeditdistance():
    x = fluid.layers.data(name='x', shape=[1], dtype='float32')
    y = fluid.layers.data(name='y', shape=[1], dtype='float32')
    cost = fluid.layers.edit_distance(input=x,label=y)
```

这应该是正确的写法，文档不够严谨，没有根据代码及时更新

@wanghaoshuang 辛苦更新下对应文档
