### ISSUE TITLE
Very slow reading data for large batch sizes in C-API inference

### ISSUE THREAD

**Issue by wojtuss** [PaddlePaddle/Paddle#13731]
Reading data in C-API inference (via `PaddlePredictor::Run()` method) is very slow and appears to be a bottleneck for inference performance.
Is the following piece of code required? If yes, can we optimize it somehow?
https://github.com/PaddlePaddle/Paddle/blob/8cd17c04c1d0eadebb96c2a9dc887c8411e7e6c8/paddle/fluid/inference/api/api_impl.cc#L197
Can we optimize reading data also in any other way?

**Comment by luotao1** [comment]
> appears to be a bottleneck for inference performance

We test the inference performance exclude reading data now. We will read all the test data before inference.

> Is the following piece of code required? If yes, can we optimize it somehow?

This piece of code is required. But you can optimize it.

> Can we optimize reading data also in any other way?

Could you describe the way that how to optimize reading data?

**Comment by ghost** [comment]
According to @Superjomn , we can modify our CAPI model by using "zero copy" (see RNN1 model: https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/fluid/inference/tests/api/analyzer_rnn1_tester.cc#L324)

**Comment by wojtuss** [comment]
It turned out that reading data was not the performance bottleneck, but the "zero copy" approach could also help. Thanks!
