### ISSUE TITLE
cgan使用paddle最新版本跑出来的效果不如develop好。

### ISSUE THREAD

**Issue by helen88** [PaddlePaddle/Paddle#13744]
Thank you for contributing to PaddlePaddle. Submitting an issue is a great help for us.
Both Chinese and English issues are welcome.

It's hard to solve a problem when important details are missing.
Before submitting the issue, look over the following criteria before handing your request in.

- [ ] Was there a similar issue submitted or resolved before ? You could search issue in the github.
- [ ] Did you retrieve your issue from widespread search engines ?
- [ ] Is my description of the issue clear enough to reproduce this problem?
   * If some errors occurred, we need details about `how do you run your code?`, `what system do you use?`, `Are you using GPU or not?`, etc.
   * If you use an recording [asciinema](https://asciinema.org/) to show what you are doing to make it happen, that's awesome! We could help you solve the problem more quickly.
- [ ] Is my description of the issue use the github markdown correctly?
   * Please use the proper markdown syntaxes for styling all forms of writing, e.g, source code, error information, etc.
   * Check out [this page](https://guides.github.com/features/mastering-markdown/) to find out much more about markdown.

**Comment by helen88** [comment]
![image](https://user-images.githubusercontent.com/4593091/46590869-4fcfa880-cae9-11e8-973a-a4382056a4c1.png)

develop版本：
![image](https://user-images.githubusercontent.com/4593091/46590878-59591080-cae9-11e8-9722-bbef07b3f95a.png)

**Comment by sneaxiy** [comment]
您好，请问您用的是哪个Paddle版本，麻烦您提供完整的问题描述，如网络配置、GPU还是CPU等，以便我们帮助解决。
另外，您可以升级至paddle 1.0，这个问题可能是数值稳定性引起的，近期代码里可能修复了一些数值稳定性的bug。
