### ISSUE TITLE
Paddle在集群上训练，网络结构构建好后，似乎在初始化过程中，一直报这种错误。

### ISSUE THREAD

**Issue by CruiseSun** [PaddlePaddle/Paddle#13745]
Mon Oct  8 11:12:55 2018[1,20]<stderr>:./train.sh: line 239: 62525 Segmentation fault      (core dumped) python27-gcc482/bin/python conf/trainer_config.conf
Mon Oct  8 11:12:55 2018[1,20]<stderr>:+ '[' 139 -ne 0 ']'
Mon Oct  8 11:12:55 2018[1,20]<stderr>:+ kill_pserver2_exit
Mon Oct  8 11:12:55 2018[1,20]<stderr>:+ ps aux
Mon Oct  8 11:12:55 2018[1,20]<stderr>:+ grep paddle_pserver2
Mon Oct  8 11:12:55 2018[1,20]<stderr>:+ grep paddle_cluster_job
Mon Oct  8 11:12:55 2018[1,20]<stderr>:+ grep -v grep
Mon Oct  8 11:12:55 2018[1,20]<stderr>:+ cut -c10-14
Mon Oct  8 11:12:55 2018[1,20]<stderr>:+ xargs kill -9
Mon Oct  8 11:12:55 2018[1,20]<stderr>:usage: kill [ -s signal | -p ] [ -a ] pid ...
Mon Oct  8 11:12:55 2018[1,20]<stderr>:       kill -l [ signal ]
Mon Oct  8 11:12:55 2018[1,20]<stderr>:+ log_fatal 'paddle_trainer failed kill paddle_pserver2 and exit'
Mon Oct  8 11:12:55 2018[1,20]<stderr>:+ echo '[./common.sh : 399] [kill_pserver2_exit]'
Mon Oct  8 11:12:55 2018[1,20]<stderr>:[./common.sh : 399] [kill_pserver2_exit]
Mon Oct  8 11:12:55 2018[1,20]<stderr>:+ echo '[FATAL]: paddle_trainer failed kill paddle_pserver2 and exit'
Mon Oct  8 11:12:55 2018[1,20]<stderr>:[FATAL]: paddle_trainer failed kill paddle_pserver2 and exit
Mon Oct  8 11:12:55 2018[1,20]<stderr>:+ get_stack
Mon Oct  8 11:12:55 2018[1,20]<stderr>:+ set +x
Mon Oct  8 11:12:55 2018[1,20]<stderr>:
Mon Oct  8 11:12:55 2018[1,20]<stderr>:*********************Shell Script Stack Trace********************
Mon Oct  8 11:12:55 2018[1,20]<stderr>: @: [./log.sh: 41] log_fatal
Mon Oct  8 11:12:55 2018[1,20]<stderr>: @: [./common.sh: 399] kill_pserver2_exit
Mon Oct  8 11:12:55 2018[1,20]<stderr>: @: [./train.sh: 242] main
Mon Oct  8 11:12:55 2018[1,20]<stderr>:
Mon Oct  8 11:12:55 2018[1,20]<stderr>:+ exit 1

**Comment by CruiseSun** [comment]
我的任务地址如下，麻烦帮忙看下train.log。http://10.73.71.14:8900/fileview.html?path=/home/disk1/normandy/maybach/app-user-20181008103547-24309/

**Comment by typhoonzero** [comment]
Dup: https://github.com/PaddlePaddle/Paddle/issues/13762

**Comment by lucywsq** [comment]
您好，此issue在近一个月内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题，我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持!
