### ISSUE TITLE
fluid.layers.l2_normalize层输入正常，输出全为nan

### ISSUE THREAD

**Issue by hedlmote** [PaddlePaddle/Paddle#13743]
网络中有如下两层，
rgb_att1 = attention_pool([input_rgb,rgb_weight1], shift_multi=-0.72, shift_bias=0.16)
rgb_att1_out = fluid.layers.l2_normalize(x=rgb_att1,axis=1, epsilon=1e-6)
其中attention_pool是一个模块，输出rgb_att1打印出来是正常的：
[[-0.18813121 -0.21344894 -0.1914207  ... -0.22382796 -0.2166537 -0.20107862]]

经过l2_normalize之后输出的rgb_att1_out全是nan
[[nan nan nan ... nan nan nan]]

**Comment by qingqing01** [comment]
@hedlmote 请问使用的是Paddle哪个版本？

**Comment by hedlmote** [comment]
It is the problem of old fluid version, the latest version of fluid works fine with l2_normalize
