### ISSUE TITLE
mpi训练过程中，突然会出现卡住不动的情况

### ISSUE THREAD

**Issue by 333caowei** [PaddlePaddle/Paddle#13753]
已经训练了多轮，然后突然会卡住日志不再滚动：
train.log如下（已过去一个多小时，日志依然保持在下图样子）：
<img width="1280" alt="image" src="https://user-images.githubusercontent.com/4569055/46596007-83bcc500-cb0d-11e8-85fb-eacc43264ebb.png">

paddle_pserver2.INFO如下：
<img width="758" alt="image" src="https://user-images.githubusercontent.com/4569055/46596039-9afbb280-cb0d-11e8-904a-ee41e0dc3dc9.png">

作业链接可以私hi：caowei07

**Comment by typhoonzero** [comment]
是否是在跑test呢还是一直卡着，可以多打一些日志看下？

**Comment by 333caowei** [comment]
不是跑test，之前几轮都是好的，卡了6个小时后已手工kill

**Comment by typhoonzero** [comment]
看job页面是否有故障节点呢

**Comment by 333caowei** [comment]
看过了节点应该是正常的，后面重新跑了一下程序又没有卡住的现象了.......
