### ISSUE TITLE
用C-API执行paddle_gradient_machine_create_for_inference时报错

### ISSUE THREAD

**Issue by clztmclztm** [PaddlePaddle/Paddle#13758]
用c-api调用函数paddle_gradient_machine_create_for_inference时，出core，同时报错：
WARNING: Logging before InitGoogleLogging() is written to STDERR
F1008 17:11:31.869549 28953 ClassRegistrar.h:65] Check failed: mapGet(type, creatorMap_, &creator) Unknown class type: data
*** Check failure stack trace: ***
Aborted (core dumped)
gcc版本：4.8.2
动态链接库：LIBS('./third-party/dnn_tools/paddle_sdk/lib/libmkldnn.so.0', './third-party/dnn_tools/paddle_sdk/lib/libpaddle_capi_shared.so')
链接参数：LDFLAGS('-lpthread -lrt -lssl -lcrypto -ldl -lz')
代码：
int PairWiseModel::_init_predict_machines(const char* bin_path, const char* model_path) {
    int err_code = 0;
    // read config_bin
    long buf_sz;
    void* buf = _read_config(bin_path, &buf_sz);
    if (buf == NULL) {
        std::free(buf);
        return -1;
    }
    // UB_LOG_TRACE("DXS DEBUG: BUF SIZE [%ld]", buf_:/sz);
    // init THE machine
    err_code = paddle_gradient_machine_create_for_inference(&_init_machine, buf, (int)buf_sz);
    if (err_code != kPD_NO_ERROR) {
        std::free(buf);
        return -2;
    }
    err_code = paddle_gradient_machine_load_parameter_from_disk(_init_machine, model_path);
    if (err_code != kPD_NO_ERROR) {
        std::free(buf);
        return -3;
    }
    // init other machines sharing params with THE machine
    for (int i = 0; i < _machine_nums; ++i) {
        paddle_gradient_machine local_machine;
        err_code =
            paddle_gradient_machine_create_shared_param(_init_machine, buf, buf_sz, &local_machine);
        if (err_code != kPD_NO_ERROR) {
            std::free(buf);
            return -4;
        }
        _predict_machines.push_back(local_machine);
    }
    // init mutices
    std::vector<std::mutex> tmp_mutex_list(_machine_nums);
    _predict_mutexes.swap(tmp_mutex_list);
    std::free(buf);
    return 0;
}

**Comment by clztmclztm** [comment]
用c-api调用函数paddle_gradient_machine_create_for_inference时，出core，同时报错：
WARNING: Logging before InitGoogleLogging() is written to STDERR
F1008 17:11:31.869549 28953 ClassRegistrar.h:65] Check failed: mapGet(type, creatorMap_, &creator) Unknown class type: data
*** Check failure stack trace: ***
Aborted (core dumped)
gcc版本：4.8.2
动态链接库：LIBS('./third-party/dnn_tools/paddle_sdk/lib/libmkldnn.so.0', './third-party/dnn_tools/paddle_sdk/lib/libpaddle_capi_shared.so')
链接参数：LDFLAGS('-lpthread -lrt -lssl -lcrypto -ldl -lz')

**Comment by shibing624** [comment]
@clztmclztm 请问怎么解决的该问题的？我也遇到了
