### ISSUE TITLE
网络预测时出现错误“First matrix's width must be equal with second matrix's height”

### ISSUE THREAD

**Issue by zds9204** [PaddlePaddle/Paddle#13769]
仿照demo设计ctr网络，训练时正常，预测时出现如下错误：
_Traceback (most recent call last):
  File "push_ctr_net_fluid_infer.py", line 55, in <module>
    infer(test_reader, use_cuda=False, model_path=model_path)
  File "push_ctr_net_fluid_infer.py", line 36, in infer
    return_numpy=False)
  File "/home/users/zhangtai01/paddle_release_home/python/lib/python2.7/site-packages/paddle/fluid/executor.py", line 449, in run
    self.executor.run(program.desc, scope, 0, True, True)
paddle.fluid.core.EnforceNotMet: enforce x_mat_dims[1] == y_mat_dims[0] failed, 1 != 5
First matrix's width must be equal with second matrix's height. at [/paddle/paddle/fluid/operators/mul_op.cc:59]
PaddlePaddle Call Stacks:
0       0x7fe68e270816p paddle::platform::EnforceNotMet::EnforceNotMet(std::__exception_ptr::exception_ptr, char const*, int) + 486
1       0x7fe68e8f7e1ep paddle::operators::MulOp::InferShape(paddle::framework::InferShapeContext*) const + 2494
2       0x7fe68eb0f8f8p paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&) const + 88
3       0x7fe68eb0cdc0p paddle::framework::OperatorBase::Run(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&) + 208
4       0x7fe68e32e05fp paddle::framework::Executor::RunPreparedContext(paddle::framework::ExecutorPrepareContext*, paddle::framework::Scope*, bool, bool, bool) + 255
5       0x7fe68e32f0b0p paddle::framework::Executor::Run(paddle::framework::ProgramDesc const&, paddle::framework::Scope*, int, bool, bool) + 128
6       0x7fe68e2586fdp
7       0x7fe68e281224p pybind11::cpp_function::dispatcher(_object*, _object*, _object*) + 2596
8       0x7fe6b762ebb8p PyEval_EvalFrameEx + 25016
9       0x7fe6b76320bdp PyEval_EvalCodeEx + 2061
10      0x7fe6b762f345p PyEval_EvalFrameEx + 26949
11      0x7fe6b76320bdp PyEval_EvalCodeEx + 2061
12      0x7fe6b762f345p PyEval_EvalFrameEx + 26949
13      0x7fe6b76320bdp PyEval_EvalCodeEx + 2061
14      0x7fe6b76321f2p PyEval_EvalCode + 50
15      0x7fe6b765af42p PyRun_FileExFlags + 146
16      0x7fe6b765c2d9p PyRun_SimpleFileExFlags + 217
17      0x7fe6b767200dp Py_Main + 3149
18      0x7fe6b686fbd5p __libc_start_main + 245
19            0x4007a1p_

无论如何修改输入，均产生这种错误。甚至，将输入的lod_tensor故意写成错误的长度，依然出现这种错误。

**Comment by zds9204** [comment]
_Traceback (most recent call last):
  File "push_ctr_net_fluid_infer.py", line 55, in <module>
    infer(test_reader, use_cuda=False, model_path=model_path)
  File "push_ctr_net_fluid_infer.py", line 36, in infer
    return_numpy=False)
  File "/home/users/zhangtai01/paddle_release_home/python/lib/python2.7/site-packages/paddle/fluid/executor.py", line 449, in run
    self.executor.run(program.desc, scope, 0, True, True)
paddle.fluid.core.EnforceNotMet: enforce x_mat_dims[1] == y_mat_dims[0] failed, 1 != 5
First matrix's width must be equal with second matrix's height. at [/paddle/paddle/fluid/operators/mul_op.cc:59]
PaddlePaddle Call Stacks:
0       0x7fe68e270816p paddle::platform::EnforceNotMet::EnforceNotMet(std::__exception_ptr::exception_ptr, char const*, int) + 486
1       0x7fe68e8f7e1ep paddle::operators::MulOp::InferShape(paddle::framework::InferShapeContext*) const + 2494
2       0x7fe68eb0f8f8p paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&) const + 88
3       0x7fe68eb0cdc0p paddle::framework::OperatorBase::Run(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&) + 208
4       0x7fe68e32e05fp paddle::framework::Executor::RunPreparedContext(paddle::framework::ExecutorPrepareContext*, paddle::framework::Scope*, bool, bool, bool) + 255
5       0x7fe68e32f0b0p paddle::framework::Executor::Run(paddle::framework::ProgramDesc const&, paddle::framework::Scope*, int, bool, bool) + 128
6       0x7fe68e2586fdp
7       0x7fe68e281224p pybind11::cpp_function::dispatcher(_object*, _object*, _object*) + 2596
8       0x7fe6b762ebb8p PyEval_EvalFrameEx + 25016
9       0x7fe6b76320bdp PyEval_EvalCodeEx + 2061
10      0x7fe6b762f345p PyEval_EvalFrameEx + 26949
11      0x7fe6b76320bdp PyEval_EvalCodeEx + 2061
12      0x7fe6b762f345p PyEval_EvalFrameEx + 26949
13      0x7fe6b76320bdp PyEval_EvalCodeEx + 2061
14      0x7fe6b76321f2p PyEval_EvalCode + 50
15      0x7fe6b765af42p PyRun_FileExFlags + 146
16      0x7fe6b765c2d9p PyRun_SimpleFileExFlags + 217
17      0x7fe6b767200dp Py_Main + 3149
18      0x7fe6b686fbd5p __libc_start_main + 245
19            0x4007a1p_

**Comment by zds9204** [comment]
搜索相关的问题，多是由于循环神经网络得到的结果长度不固定造成的。但是本网络中没有用到循环结构

**Comment by tensor-tang** [comment]
建议先添加环境变量`export GLOG_v=3` 打印日志，定位下是哪层fc出的问题

**Comment by tensor-tang** [comment]
线下沟通后发现是由于`create_lod_tensor`这个接口只支持`int64`的data
https://github.com/PaddlePaddle/Paddle/blob/cc36bab184b83210e5e925f43db9dfc3ff0c1da7/python/paddle/fluid/lod_tensor.py#L77

用户采用了`float32`的导致出现的其他错误。

这一部分用户表示我们并没有文档明确说明只支持int64，很容易导致用户的误用。@shanyi15 @panyx0718

**Comment by shanyi15** [comment]
收到，感谢反馈，请@tink2123 在写lod文档时关注～辛苦

**Comment by zds9204** [comment]
总结一下：预测时使用create_lod_tensor api将输入数据转化成张量，但是这个api目前只支持int64，不能正确处理输入的float32变量，造成的上述错误。正确写法如下

_# user_travel_pref = fluid.create_lod_tensor(
        #     [[0.08085073, 0.6272741, 0.28248206, 0.009154413, 0.00023870559]], [[5]], place)
        user_travel_pref = fluid.core.LoDTensor()
        lod = [[0, 1]]
        data = np.array([[0.08085073, 0.6272741, 0.28248206, 0.009154413, 0.00023870559]],
                        dtype='float32')
        user_travel_pref.set(data, place)
        user_travel_pref.set_lod(lod)_

注释掉的是错误写法，下面是正确的代码

**Comment by panyx0718** [comment]
> 线下沟通后发现是由于`create_lod_tensor`这个接口只支持`int64`的data
> [Paddle/python/paddle/fluid/lod_tensor.py](https://github.com/PaddlePaddle/Paddle/blob/cc36bab184b83210e5e925f43db9dfc3ff0c1da7/python/paddle/fluid/lod_tensor.py#L77)
> 
> Line 77 in [cc36bab](/PaddlePaddle/Paddle/commit/cc36bab184b83210e5e925f43db9dfc3ff0c1da7)
> 
>  flattened_data = np.concatenate(data, axis=0).astype("int64") 
> 用户采用了`float32`的导致出现的其他错误。
> 
> 这一部分用户表示我们并没有文档明确说明只支持int64，很容易导致用户的误用。@shanyi15 @panyx0718

create_lod_tensor应该检查一下输入的type然后报个可读的错误？比如 “does not support float32" @tensor-tang

**Comment by tensor-tang** [comment]
发现更准确的说法是，在输入为list的时候，只支持int64。

确实可以加点check。
