### ISSUE TITLE
GradientPrinter Evaluator do not need to print sequence position

### ISSUE THREAD

**Issue by reyoung** [PaddlePaddle/Paddle#1376]
There are several printer evaluators for debugging Paddle network. The GradientPrinter is one of them. It will print input layers' gradient and sequence start position now. I think the GradientPrinter should only print gradient, nothing more. The reasons are:

* The sequence information in GradientPrinter is NOT COMPLETE. If GradientPrinter print sequence positions, how about the nested(sub) sequence positions? Should we add the nested(sub) sequence position?
* If a user wants to print sequence information in the evaluator, we could provide a `SequenceInfoPrinter`.  `SequenceInfoPrinter` is not provided now, but `ValuePrinter` print the argument value(a.k.a Neural Network Activations) and sequence information now. Users can use `ValuePrinter` to print sequence information now.

**Comment by qingqing01** [comment]
Thanks for your explanation.  Good!
