### ISSUE TITLE
在MPI集群上训练paddle报如下错误：

### ISSUE THREAD

**Issue by CruiseSun** [PaddlePaddle/Paddle#13762]
Mon Oct  8 17:00:17 2018[1,4]<stderr>:F1008 17:00:17.361272  7286 LightNetwork.cpp:395] connection refused by pserver, maybe pserver failed!
Mon Oct  8 17:00:17 2018[1,4]<stderr>:*** Check failure stack trace: ***
Mon Oct  8 17:00:17 2018[1,4]<stderr>:    @     0x7f4c5091c27d  google::LogMessage::Fail()
Mon Oct  8 17:00:17 2018[1,4]<stderr>:    @     0x7f4c5091fd2c  google::LogMessage::SendToLog()
Mon Oct  8 17:00:17 2018[1,4]<stderr>:    @     0x7f4c5091bda3  google::LogMessage::Flush()
Mon Oct  8 17:00:17 2018[1,4]<stderr>:    @     0x7f4c5092123e  google::LogMessageFatal::~LogMessageFatal()
Mon Oct  8 17:00:17 2018[1,4]<stderr>:    @     0x7f4c507793c1  paddle::SocketClient::TcpClient()
Mon Oct  8 17:00:17 2018[1,4]<stderr>:    @     0x7f4c507795a1  paddle::SocketClient::SocketClient()
Mon Oct  8 17:00:17 2018[1,4]<stderr>:    @     0x7f4c513fc9b0  paddle::ParameterClient2::init()
Mon Oct  8 17:00:17 2018[1,4]<stderr>:    @     0x7f4c50f8909d  paddle::RemoteParameterUpdater::init()
Mon Oct  8 17:00:17 2018[1,4]<stderr>:    @     0x7f4c508fc1ea  ParameterUpdater::init()
Mon Oct  8 17:00:17 2018[1,4]<stderr>:    @     0x7f4c505a5f7b  _wrap_ParameterUpdater_init
Mon Oct  8 17:00:17 2018[1,4]<stderr>:    @           0x4b4cb9  PyEval_EvalFrameEx
Mon Oct  8 17:00:17 2018[1,4]<stderr>:    @           0x4b6b28  PyEval_EvalCodeEx
Mon Oct  8 17:00:17 2018[1,4]<stderr>:    @           0x4b5d10  PyEval_EvalFrameEx
Mon Oct  8 17:00:17 2018[1,4]<stderr>:    @           0x4b6b28  PyEval_EvalCodeEx
Mon Oct  8 17:00:17 2018[1,4]<stderr>:    @           0x4b5d10  PyEval_EvalFrameEx
Mon Oct  8 17:00:17 2018[1,4]<stderr>:    @           0x4b5fb8  PyEval_EvalFrameEx
Mon Oct  8 17:00:17 2018[1,4]<stderr>:    @           0x4b6b28  PyEval_EvalCodeEx
Mon Oct  8 17:00:17 2018[1,4]<stderr>:    @           0x4b6c52  PyEval_EvalCode
Mon Oct  8 17:00:17 2018[1,4]<stderr>:    @           0x4e1c7d  PyRun_FileExFlags
Mon Oct  8 17:00:17 2018[1,4]<stderr>:    @           0x4e3501  PyRun_SimpleFileExFlags
Mon Oct  8 17:00:17 2018[1,4]<stderr>:    @           0x4159dd  Py_Main
Mon Oct  8 17:00:17 2018[1,4]<stderr>:    @     0x7f4c538f7bd5  __libc_start_main
Mon Oct  8 17:00:17 2018[1,4]<stderr>:    @           0x414b71  (unknown)
Mon Oct  8 17:00:17 2018[1,4]<stderr>:    @              (nil)  (unknown)

**Comment by CruiseSun** [comment]
log地址 http://10.73.71.25:8900/fileview.html?path=/home/disk1/normandy/maybach/app-user-20181008114417-24348/

**Comment by typhoonzero** [comment]
可能是端口冲突之类的问题，请参考：http://www.paddlepaddle.org/documentation/docs/zh/0.12.0/faq/cluster/index_cn.html 排查

**Comment by lucywsq** [comment]
您好，此issue在近一个月内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题，我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持!
