### ISSUE TITLE
训练过程报错“paddle.fluid.core.EnforceNotMet: Enforce failed. Expected ids[i] < row_number, but received ids[i]:11 >= row_number:10.  at [/paddle/paddle/fluid/operators/lookup_table_op.h:59]”

### ISSUE THREAD

**Issue by fengshuting** [PaddlePaddle/Paddle#13777]
Traceback (most recent call last):
  File "/tmp/pycharm_project_707/train.py", line 286, in <module>
    main(USE_GPU)
  File "/tmp/pycharm_project_707/train.py", line 279, in main
    params_dirname=params_dirname)
  File "/tmp/pycharm_project_707/train.py", line 223, in train
    feed_order=feed_order)
  File "/usr/local/lib/python2.7/dist-packages/paddle/fluid/trainer.py", line 405, in train
    feed_order)
  File "/usr/local/lib/python2.7/dist-packages/paddle/fluid/trainer.py", line 461, in _train_by_executor
    self._train_by_any_executor(event_handler, exe, num_epochs, reader)
  File "/usr/local/lib/python2.7/dist-packages/paddle/fluid/trainer.py", line 490, in _train_by_any_executor
    for var in self.train_func_outputs
  File "/usr/local/lib/python2.7/dist-packages/paddle/fluid/executor.py", line 470, in run
    self.executor.run(program.desc, scope, 0, True, True)
paddle.fluid.core.EnforceNotMet: Enforce failed. Expected ids[i] < row_number, but received ids[i]:11 >= row_number:10.
 at [/paddle/paddle/fluid/operators/lookup_table_op.h:59]
PaddlePaddle Call Stacks: 
0       0x7fb252ddad86p paddle::platform::EnforceNotMet::EnforceNotMet(std::__exception_ptr::exception_ptr, char const*, int) + 486
1       0x7fb252faf448p paddle::operators::LookupTableKernel<float>::Compute(paddle::framework::ExecutionContext const&) const + 1608
2       0x7fb252faf7e3p std::_Function_handler<void (paddle::framework::ExecutionContext const&), paddle::framework::OpKernelRegistrarFunctor<paddle::platform::CPUPlace, false, 0ul, paddle::operators::LookupTableKernel<float>, paddle::operators::LookupTableKernel<double> >::operator()(char const*, char const*) const::{lambda(paddle::framework::ExecutionContext const&)#1}>::_M_invoke(std::_Any_data const&, paddle::framework::ExecutionContext const&) + 35
3       0x7fb2537adc2ep paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&) const + 526
4       0x7fb2537aa00fp paddle::framework::OperatorBase::Run(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&) + 255
5       0x7fb252e989d9p paddle::framework::Executor::RunPreparedContext(paddle::framework::ExecutorPrepareContext*, paddle::framework::Scope*, bool, bool, bool) + 393
6       0x7fb252e995d0p paddle::framework::Executor::Run(paddle::framework::ProgramDesc const&, paddle::framework::Scope*, int, bool, bool) + 128
7       0x7fb252dc265dp
8       0x7fb252e0d034p pybind11::cpp_function::dispatcher(_object*, _object*, _object*) + 2596
9             0x4c37edp PyEval_EvalFrameEx + 31165
10            0x4b9ab6p PyEval_EvalCodeEx + 774
11            0x4c16e7p PyEval_EvalFrameEx + 22711
12            0x4b9ab6p PyEval_EvalCodeEx + 774
13            0x4c1e6fp PyEval_EvalFrameEx + 24639
14            0x4b9ab6p PyEval_EvalCodeEx + 774
15            0x4c1e6fp PyEval_EvalFrameEx + 24639
16            0x4b9ab6p PyEval_EvalCodeEx + 774
17            0x4c16e7p PyEval_EvalFrameEx + 22711
18            0x4b9ab6p PyEval_EvalCodeEx + 774
19            0x4c1e6fp PyEval_EvalFrameEx + 24639
20            0x4b9ab6p PyEval_EvalCodeEx + 774
21            0x4c1e6fp PyEval_EvalFrameEx + 24639
22            0x4b9ab6p PyEval_EvalCodeEx + 774
23            0x4eb30fp
24            0x4e5422p PyRun_FileExFlags + 130
25            0x4e3cd6p PyRun_SimpleFileExFlags + 390
26            0x493ae2p Py_Main + 1554
27      0x7fb271093830p __libc_start_main + 240
28            0x4933e9p _start + 41

**Comment by fengshuting** [comment]
def fc_net(case, class_dim, hid_dim):

    # 第一个全连接层，激活函数为ReLU
    hidden = fluid.layers.fc(input=case, size=hid_dim, act='relu')
    # 第二个全连接层，激活函数为ReLU
    hidden = fluid.layers.fc(input=hidden, size=hid_dim, act='relu')
    prediction = fluid.layers.fc(input=hidden, size=class_dim, act='softmax')
    return prediction

**Comment by tensor-tang** [comment]
出错在lookup_table_op.h，应该是有embedding层，建议检查下前后的dim size。报错的信息是为了检查idx不越界的。
https://github.com/PaddlePaddle/Paddle/blob/cc36bab184b83210e5e925f43db9dfc3ff0c1da7/paddle/fluid/operators/lookup_table_op.h#L59

**Comment by fengshuting** [comment]
input的case是embedding后的数据，经过文本卷积处理，这里重新进入全链接层还需要embedding吗？

**Comment by tensor-tang** [comment]
看embedding的出错信息应该是检查下他的输入层，跟后面接fc应该没有什么关系。
