### ISSUE TITLE
c-api调用预测接口paddle_gradient_machine_forward出错时，没有打印出stack信息

### ISSUE THREAD

**Issue by clztmclztm** [PaddlePaddle/Paddle#13782]
调用c-api的预测接口paddle_gradient_machine_forward时，报错，但是没有打印出日志，不知道该怎么debug，请问如何打印出报错日志？
报错信息如下：
Thread [140639771183232] Forwarding concat,
*** Aborted at 1539074835 (unix time) try "date -d @1539074835" if you are using GNU date ***
PC: @                0x0 (unknown)
*** SIGSEGV (@0x10) received by PID 11245 (TID 0x7fe93f9a4880) from PID 16; stack trace: ***
    @     0x7fe93f580160 (unknown)

**Comment by tensor-tang** [comment]
可以手动编译debug 版的library 用gdb调试吗

**Comment by tensor-tang** [comment]
另外可以在docker里面调试，一般是有stack信息的。 源码编译安装的相关文档在这里：http://paddlepaddle.org/documentation/docs/zh/0.15.0/beginners_guide/install/install_doc.html#ubt_docker

**Comment by tensor-tang** [comment]
please reopen it if necessary
