### ISSUE TITLE
[API分类] 优化目前官网API类别的问题

### ISSUE THREAD

**Issue by tink2123** [PaddlePaddle/Paddle#13789]
**背景：** 
目前官网部分API类别稍显粗糙，期望优化分类以减轻用户的阅读负担。

**简单说明：** 
对比Tensoflow 1.0版本的API，在release/0.15.0的基础上将Fluid的API初步分成如下大类。

*此版本仅是初版，期待老师们提出宝贵的修改意见。*

将API按按首字母排序：

| API | type | note |
| -- | -- | -- |
| fluid | |
| fluid.average| |
|fluid.backward| |
| fluid.bitwise  | 新增 | fluid.layers.logical_or / fluid.layers.logical_and/... |
| fluid.clip | |
| fluid.contrib| |
| fluid.data| 新增 | fluid.dataset |
| fluid.data_feeder|
|fluid.initializer|
|fluid.io|
|fluid.layers|
|fluid.layers.control_flow|
|fluid.layers.detection|
|fluid.layers.io| 合并| 与fluid.io合并 |
|fluid.layers.learning_rate_schedule|
|fluid.losses|新增| 从fluid.layers中分离|
|fluid.metrics|合并| 与fluid.metric_op合并|
|fluid.net|合并| 与fluid.layers.nn合并 |
|fluid.layers.tensor|
|fluid.layers.ops|  拆分（仍需讨论） | 拆分成：elementwise、math、Activation Function、clip（与fluid.clip合并？）|
|fluid.optimizer|
|fluid.param_attr|
|fluid.profiler|
|fluid.recordio_writer|
|fluid.regularizer|
|fluid.transpiler|
|flud.save_model|新增| fluid.io.save_inference 等 |
|fluid.test|新增| not found |
|fluid.train|新增| fluid.trainer ? |

**Comment by shanyi15** [comment]
辛苦 @luotao1 @qingqing01 review，期望在周四10月11日之内定稿～谢谢！

**Comment by luotao1** [comment]
- 注意：`fluid.bitwise`虽然可以分类在一块，但不会新增这样一个api。
- 目前的分类较乱，先把一级大类（中文）分出来，对应填入api。可以结合API Guide一起做。
- 等一级大类确定后，再逐步往下分小类，每次分类时，完成对应类别的API Guide。

**Comment by luotao1** [comment]
因为是对API目录分类，将移到FluidDoc repo下讨论，先关闭此issue。
