### ISSUE TITLE
Duplicated ValuePrinter/PrintLayer logic.

### ISSUE THREAD

**Issue by reyoung** [PaddlePaddle/Paddle#1378]
In paddle, there are two ways to print paddle input layer output. They are 

* ValuePrinter Evaluator
* PrintLayer Layer

They have slightly different behaviors. PrintLayer is a layer, and it will print layer output in every Paddle forward method.  ValuePrinter is an evaluator, and it will only print layer output when evaluating Network.

However, the print logic is same, and current implementation almost copy-and-paste twice in ValuePrinter and PrintLayer.

We should unify the implementation. And the print logic should belong to Argument.

**Comment by luotao1** [comment]
> the print logic should belong to Argument

Agree.
