### ISSUE TITLE
官网 c++ 部署库版本的疑问

### ISSUE THREAD

**Issue by BryceLuminary** [PaddlePaddle/Paddle#13781]
您好，官网 0.15.0 的文档“模型预测部署”的 cuda8.0_cudnn7_avx_mkl 附带的 github commit 号源码 git reset 不能成功，显示错误：
`Could not parse object 'bfd2ba99f06ea8e781734df4bf1708b0187a1536'.`

附：链接
http://www.paddlepaddle.org/documentation/docs/zh/0.15.0/user_guides/howto/inference/build_and_install_lib_cn.html#id1
https://guest@paddleci.ngrok.io/repository/download/Manylinux1_Cuda8cudnn7cp27cp27mu/.lastSuccessful/fluid.tgz/?branch=0.15.0

我发现已经有 0.1.0 正式版本发布，请问能否及时更新库文件，谢谢！

**Comment by tensor-tang** [comment]
> 源码 git reset 不能成功

直接下载最新的develop code，可以找到 bfd2ba99f06ea8e781734df4bf1708b0187a1536

>我发现已经有 0.1.0 正式版本发布，请问能否及时更新库文件

这句不是很明白

**Comment by tensor-tang** [comment]
reopen it if needed.
