### ISSUE TITLE
mpi任务Address already in use，求如何独占运行

### ISSUE THREAD

**Issue by lyp2github** [PaddlePaddle/Paddle#13798]
Wed Oct 10 01:40:44 2018[1,31]<stderr>:Traceback (most recent call last):
Wed Oct 10 01:40:44 2018[1,31]<stderr>:  File "./http_server.py", line 41, in <module>
Wed Oct 10 01:40:44 2018[1,31]<stderr>:    server = ThreadingSimpleServer(('', port), SimpleHTTPRequestHandler)
Wed Oct 10 01:40:44 2018[1,31]<stderr>:  File "/home/disk1/normandy/maybach/787768/workspace/python27-gcc482/lib/python2.7/SocketServer.py", line 420, in __init__
Wed Oct 10 01:40:44 2018[1,31]<stderr>:    self.server_bind()
Wed Oct 10 01:40:44 2018[1,31]<stderr>:  File "/home/disk1/normandy/maybach/787768/workspace/python27-gcc482/lib/python2.7/BaseHTTPServer.py", line 108, in server_bind
Wed Oct 10 01:40:44 2018[1,31]<stderr>:    SocketServer.TCPServer.server_bind(self)
Wed Oct 10 01:40:44 2018[1,31]<stderr>:  File "/home/disk1/normandy/maybach/787768/workspace/python27-gcc482/lib/python2.7/SocketServer.py", line 434, in server_bind
Wed Oct 10 01:40:44 2018[1,31]<stderr>:    self.socket.bind(self.server_address)
Wed Oct 10 01:40:44 2018[1,31]<stderr>:  File "/home/disk1/normandy/maybach/787768/workspace/python27-gcc482/lib/python2.7/socket.py", line 228, in meth
Wed Oct 10 01:40:44 2018[1,31]<stderr>:    return getattr(self._sock,name)(*args)
Wed Oct 10 01:40:44 2018[1,31]<stderr>:socket.error: [Errno 98] Address already in use

任务集群mng-off链接/job/i-787768/

**Comment by Yancey0623** [comment]
> Wed Oct 10 01:40:44 2018[1,31]:socket.error: [Errno 98] Address already in use

报错在这里，端口被占用了，换个端口吧。

**Comment by lyp2github** [comment]
换了个端口还是失败
Wed Oct 10 16:32:32 2018[1,17]<stderr>:F1010 16:32:32.301614 30125 LightNetwork.cpp:395] connection refused by pserver, maybe pserver failed!
Wed Oct 10 16:32:32 2018[1,17]<stderr>:*** Check failure stack trace: ***
Wed Oct 10 16:32:32 2018[1,17]<stderr>:    @     0x7fa7173e527d  google::LogMessage::Fail()
Wed Oct 10 16:32:32 2018[1,17]<stderr>:    @     0x7fa7173e8d2c  google::LogMessage::SendToLog()
Wed Oct 10 16:32:32 2018[1,17]<stderr>:    @     0x7fa7173e4da3  google::LogMessage::Flush()
任务集群mng-off链接/job/i-787946/

**Comment by Yancey0623** [comment]
可以先按 http://www.paddlepaddle.org/documentation/docs/zh/0.12.0/faq/cluster/index_cn.html 排查一下。

**Comment by lyp2github** [comment]
I1010 18:29:46.309986 23009 ParameterClient2.cpp:113] pserver 0 127.0.0.1:20134
W1010 18:29:46.310145 23009 LightNetwork.cpp:397] connection refused by pserver, try again!
W1010 18:29:47.310341 23009 LightNetwork.cpp:397] connection refused by pserver, try again!
W1010 18:29:48.310495 23009 LightNetwork.cpp:397] connection refused by pserver, try again!
W1010 18:29:49.310645 23009 LightNetwork.cpp:397] connection refused by pserver, try again!
W1010 18:29:50.310788 23009 LightNetwork.cpp:397] connection refused by pserver, try again!
W1010 18:29:51.310941 23009 LightNetwork.cpp:397] connection refused by pserver, try again!
W1010 18:29:52.311098 23009 LightNetwork.cpp:397] connection refused by pserver, try again!
W1010 18:29:53.311275 23009 LightNetwork.cpp:397] connection refused by pserver, try again!
F1010 18:29:53.311308 23009 LightNetwork.cpp:399] connection refused by pserver, maybe pserver failed!
*** Check failure stack trace: ***
    @     0x7f616ee67f5d  google::LogMessage::Fail()
    @     0x7f616ee6ba0c  google::LogMessage::SendToLog()
    @     0x7f616ee67a83  google::LogMessage::Flush()
使用paddlecloud也失败：app-user-20181010180117-25882

**Comment by lyp2github** [comment]
http://10.75.70.27:8900/fileview.html?path=/home/disk1/normandy/maybach/791044/
Mon Oct 15 05:20:43 2018[1,29]<stderr>:+ ./paddle_pserver2 --num_gradient_servers=30 --nics=xgbe0 --port=23462 --ports_num=1 --ports_num_for_sparse=1 --rdma_tcp=tcp --comment=paddle_cluster_job
Mon Oct 15 05:20:43 2018[1,10]<stderr>:*** Check failure stack trace: ***
Mon Oct 15 05:20:43 2018[1,10]<stderr>:    @           0x8d19fd  google::LogMessage::Fail()
Mon Oct 15 05:20:43 2018[1,10]<stderr>:    @           0x8d54ac  google::LogMessage::SendToLog()
Mon Oct 15 05:20:43 2018[1,10]<stderr>:    @           0x8d1523  google::LogMessage::Flush()
Mon Oct 15 05:20:43 2018[1,10]<stderr>:    @           0x8d1729  google::LogMessage::~LogMessage()
Mon Oct 15 05:20:43 2018[1,10]<stderr>:    @           0x8d49d7  google::ErrnoLogMessage::~ErrnoLogMessage()
Mon Oct 15 05:20:43 2018[1,10]<stderr>:    @           0x72a855  paddle::SocketServer::tcpServer()
Mon Oct 15 05:20:43 2018[1,10]<stderr>:    @           0x72aabc  paddle::SocketServer::run()
Mon Oct 15 05:20:43 2018[1,14]<stderr>:F1015 05:20:43.501972 40984 LightNetwork.cpp:190] Check failed: bind(socket_, (struct sockaddr *)&serv_addr, sizeof(serv_addr)) >= 0 ERROR on binding 10.73.91.40: Address already in use [98]
Mon Oct 15 05:20:43 2018[1,10]<stderr>:    @     0x7f62e70728a0  execute_native_thread_routine
Mon Oct 15 05:20:43 2018[1,10]<stderr>:    @     0x7f62e7d4a1c3  start_thread
Mon Oct 15 05:20:43 2018[1,10]<stderr>:    @     0x7f62e67e312d  __clone
Mon Oct 15 05:20:43 2018[1,10]<stderr>:    @              (nil)  (unknown)
Mon Oct 15 05:20:43 2018[1,10]<stderr>:./start_server.sh: line 33: 29116 Abor

**Comment by lyp2github** [comment]
http://10.75.70.27:8900/fileview.html?path=/home/disk1/normandy/maybach/790974/
Mon Oct 15 01:16:26 2018[1,20]<stderr>:+ ./paddle_pserver2 --num_gradient_servers=30 --nics=xgbe0 --port=57196 --ports_num=1 --ports_num_for_sparse=1 --rdma_tcp=tcp --comment=paddle_cluster_job
Mon Oct 15 01:16:26 2018[1,11]<stderr>:F1015 01:16:26.424638 12933 LightNetwork.cpp:190] Check failed: bind(socket_, (struct sockaddr *)&serv_addr, sizeof(serv_addr)) >= 0 ERROR on binding 10.75.72.30: Address already in use [98]
Mon Oct 15 01:16:26 2018[1,11]<stderr>:*** Check failure stack trace: ***
Mon Oct 15 01:16:26 2018[1,11]<stderr>:    @           0x8d19fd  google::LogMessage::Fail()
Mon Oct 15 01:16:26 2018[1,11]<stderr>:    @           0x8d54ac  google::LogMessage::SendToLog()
Mon Oct 15 01:16:26 2018[1,11]<stderr>:    @           0x8d1523  google::LogMessage::Flush()
Mon Oct 15 01:16:26 2018[1,25]<stderr>:F1015 01:16:26.455083 23250 LightNetwork.cpp:190] Check failed: bind(socket_, (struct sockaddr *)&serv_addr, sizeof(serv_addr)) >= 0 ERROR on binding 10.75.70.33: Address already in use [98]
Mon Oct 15 01:16:26 2018[1,11]<stderr>:    @           0x8d1729  google::LogMessage::~LogMessage()
Mon Oct 15 01:16:26 2018[1,11]<stderr>:    @           0x8d49d7  google::ErrnoLogMessage::~ErrnoLogMessage()
Mon Oct 15 01:16:26 2018[1,11]<stderr>:    @           0x72a855  paddle::SocketServer::tcpServer()
Mon Oct 15 01:16:26 2018[1,11]<stderr>:    @           0x72aabc  paddle::SocketServer::run()
Mon Oct 15 01:16:26 2018[1,25]<stderr>:*** Check failure stack trace: ***
Mon Oct 15 01:16:26 2018[1,11]<stderr>:    @     0x7fb226b3f8a0  execute_native_thread_routine
Mon Oct 15 01:16:26 2018[1,11]<stderr>:    @     0x7fb2278171c3  start_thread
Mon Oct 15 01:16:26 2018[1,11]<stderr>:    @     0x7fb2262b012d  __clone
Mon Oct 15 01:16:26 2018[1,11]<stderr>:    @              (nil)  (unknown)

**Comment by NHZlX** [comment]
请问这个问题解决了么 @lyp2github

**Comment by Yancey0623** [comment]
如果是使用 `qsub_f` 提交任务需要在提交时设置参数
``` text
qsub_f -l resource=full
```

如果是 paddlecloud 提交，请在 paddlecloud 群里联系管理员，其他方式可以在内网先联系 yanxu05 具体看下，先关闭这个 issue了。
