### ISSUE TITLE
Questions about the data reader design doc

### ISSUE THREAD

**Issue by wangkuiyi** [PaddlePaddle/Paddle#1380]
I have some questions about [this example](https://github.com/PaddlePaddle/Paddle/blame/develop/doc/design/reader/README.md#L110):

1. It seems that the function `image_reader` should be named `image_reader_creator? I ask because a Python function calling `yield` is actually a *reader creator*, as an invocation to this function returns an iterable (i.e., a reader closure).

1. There is no`l.close` in this example. Should we add it?

1. This example literally real two data streams -- images and labels. Could/should we change this example to be something like 

   ```python
   paddle.reader.shuffle(
     paddle.reader.compose(
       paddle.reader.creator.image("image_file.npy"),
       paddle.reader.creator.text("labels.txt")))
   ```

1. This [line](https://github.com/PaddlePaddle/Paddle/blame/develop/doc/design/reader/README.md#L121) is actually a lazy evaluation -- don't call `image_reader` when Pythons evaluate parameters of `train`; instead, evaluate `image_reader` in the body of `train`.  It seems that this lazy evaluation is required because we do passes as a nested loop in `train` and in each execution of this nested loop we need the lazy evaluation to create a new reader.  I am wondering should we make the reader returns an *end_of_pass* flag in addition to the minibatch?  It seems that this could remove the requirement of lazy evaluation?

**Comment by qingqing01** [comment]
I agree with 1, 2 and 3.  And for 3rd point, we may need `make_shuffle` and `make_minibatch` interface in the reader.   Maybe need an example to show how to use #1364 in the read demo.

**Comment by wangkuiyi** [comment]
@qingqing01 I also agree with 1, 2, and 3. They are clear.  I know 4. is not clear. Actually, it might be wrong.

Nevertheless, I wrote the following example, which doesn't rely on `lambda` for lazy evaluation; instead, it pass the function name of a reader creator and the corresponding parameters into a reader decorator as parameters, and the decorator calls Python's `apply` to create the reader.

```python
import random

def text(filename):
    f = open(filename, "r")
    for l in f:
        yield l.split()
    yield None
    f.close()

def compose(reader_creators, args):
    i = 0
    rs = list()
    for rc in reader_creators:
        r = apply(rc, args[i])
        rs.append(r)
        i = i + 1

    while True:
        l = list()
        for r in rs:
            t = r.next()
            if t == None:
                yield None
                return
            else:
                l.append(t)
        yield l

def shuffle(reader_creator, arg, buffer_size):
    r = apply(reader_creator, arg)
    buf = list()
                
    for l in r:
        if l == None or len(buf) >= buffer_size:
            random.shuffle(buf)
            for t in buf:
                yield t
            buf = list()
        buf.append(l)

    random.shuffle(buf)
    for t in buf:
        yield t
        
def multipass(reader_creator, arg, passes):
    for p in xrange(passes):
        r = apply(reader_creator, arg)
        for l in r:
            yield l

def train(reader):
    cur_pass = 0
    for l in reader:
        if l == None:
            cur_pass = cur_pass + 1
        else:
            print "Pass %d: updating model using instance %s ..." % (cur_pass, l)

train(
    multipass(
        shuffle,
        [compose,
         [[text, text], [["hello.txt"], ["world.txt"]]],
         2],
        3))       
```

This program works as long as we create a `hello.txt` which contains something like

```
Hello 1
Hello 2
```

and a `world.txt` which contains something like

```
World 1
World 2
```

**Comment by helinwang** [comment]
@wangkuiyi Agree with 2, thanks for pointing out. Here is the PR to fix it: https://github.com/PaddlePaddle/Paddle/pull/1391

**Comment by helinwang** [comment]
I think it's a good idea to illustrate `paddle.reader.compose`, but I don't think here is a good place to do so.

If we do so, `paddle.reader.creator.image_from_numpy` will be:
```
def paddle.reader.creator.image_from_numpy(path, n, w, h, channel):
  f = open(path)
  images = numpy.fromfile(
    f, 'ubyte', count=n * 28 * 28).reshape((n, 28 * 28)).astype('float32')
  images = images / 255.0 * 2.0 - 1.0
  for i in range(n):
    yield images[i]
  f.close()
```
In my opinion, code to read from image from numpy is already simple enough (just 2 line, or 4 lines if we count open and close file). I am not seeing the benefit of re-wrapping such simple thing in paddle.

Besides, the line `images = images / 255.0 * 2.0 - 1.0` is a preprocessing step, not everyone reading image from numpy want to do the exact same thing, maybe someone want to do `images = images / 255.0` instead.

I think reading image from numpy is just one of many ways to read image. It by itself is already simple enough. If we create such a reader for every simple way of reading images, we are not simplifying things, but actually complicating things.

**Comment by helinwang** [comment]
For 1, I am ok either way. `data_reader_creator` is more precise (`data_iterator_creator` may be even more precise 😄 ).
On the other hand, I don't see much problem on defining `data_reader` as `a function that returns a iterable for one pass of training data`.

**Comment by helinwang** [comment]
For 4, I like the idea of doing everything in one iteration.
Mixing `None` with real data could cause some problem:
- In `shuffle`, should be shuffle `None` around? If we do, we are changing the boundary of different passes. If not, more code is required to handle it.
- In `compose`, we need to return `None` rather than `(None, None)` if two readers both return `None`. Extra code to handle it.

I think make a function call and create a new iterable is easier to understand.
```python
r = reader()
for item in r:
  #...
```

**Comment by wangkuiyi** [comment]
@helinwang I think the semantic of `shuffle` and `compose` could be clear.

1. `shuffle`: Because None indicates the end of a stream, so shuffling shouldn't work on None, but should work on the stream before None.

1. `compose`: We'd anyway check the value read from each stream because we need to make sure that these streams are aligned, i.e., their sizes are the same.   When we do the check that if any of these stream returns None, all rest streams are also returning None, we can convert all these Nones into one None.

**Comment by helinwang** [comment]
During meeting we decided:
for 1:
use name `image_reader_creator` since it's more clear.
for 3:
We can write this creator from mnist in mnist dataset. Not necessary to be a public helper function, since this data reading format is very specific for mnist.
For 4:
Decided to use single iterator format. Return None to indicate pass finish. And provide helper to create shuffle compose decorator.

**Comment by wangkuiyi** [comment]
Helin and I had some discussions and decided to do the following

### Reader creators returns closures instead of iterables:

```python
def text(filename):
    def reader():
        f = open(filename, "r")
        for l in f:
            yield l.split()
        f.close()
    return reader
```

### Reader decorators accept reader creators and returns closures

```python
def shuffle(reader, buf_size):
    def reader():
       ...
    return reader
```

### Multi-pass scanning of the data is implemeted in `paddle.train`

```python
