### ISSUE TITLE
Paddle V2在MPI集群上跑任务，AUC全部输出为0

### ISSUE THREAD

**Issue by CruiseSun** [PaddlePaddle/Paddle#13805]
查过其他人的issue，发现问题在Paddle evaluator auc要求使用二维离散值作为输入，但是我的网络out为一个一维数值y，想要把它变成二维[1-y, y]，我该怎么做？因为是对layer层做操作，不知道Paddle支持怎么做。

**Comment by CruiseSun** [comment]
我的网络输出是这样的
out = paddle.layer.addto(name='out',
                             input=dot_prod,
                             act=paddle.activation.Sigmoid(),
                             bias_attr=False)

**Comment by NHZlX** [comment]
这个是分类模型么

**Comment by NHZlX** [comment]
我查了相关的v2 api 没有找到合适的layer来解决这个问题。

**Comment by CruiseSun** [comment]
> 这个是分类模型么

是的，用来做二分类的

**Comment by NHZlX** [comment]
二分类的话可以将网络设计成2个output的结构

**Comment by HugoLian** [comment]
我之前遇到过这个问题，当然我是回归问题用的AUC不是分类问题。paddle的同学说回归问题不能计算AUC，不过我用0.14版本做单机训练的时候，如果把输出控制在0-1之间，是可以输出AUC的，但是放在集群上就变成0了。

我当时这个问题是集群paddle用的是0.09版本（也是paddle wiki上当时给出的V2版本），归回问题的AUC计算就都是0，后来换到0.10版本的集群paddle后（来自paddle cloud），AUC就可以显示了。

**Comment by NHZlX** [comment]
因为v2已经停止开发，建议大家使用fluid， 那样遇到问题都可以得到快速的解决。先关闭此issue，如果有问题可以重新打开。
