### ISSUE TITLE
paddlecloud提交任务失败

### ISSUE THREAD

**Issue by lyp2github** [PaddlePaddle/Paddle#13810]
详细日志：Submit job to cluster failed: [FATAL] qsub_f: Submit job failed, submit failed, info: submit request refused, permission denied. ACROSS_CLUSTER_CHECK is on, across cluster job from HOST:nmg01-hpc-10g.dmop.baidu.com to HDFS:hdfs://nmg01-mulan-hdfs.dmop.baidu.com:54310 is not allowed [FATAL]: submit failed
原因：
解决方法：

**Comment by oshixiaoxiliu** [comment]
官网申请一下队列权限
