### ISSUE TITLE
使用load_inference_model读入数据

### ISSUE THREAD

**Issue by 333caowei** [PaddlePaddle/Paddle#13826]
input数据如下：一个是id、一个是id list
```
query = fluid.layers.data(
                    name="query",
                    shape=[1],
                    dtype='int64')

query_char = fluid.layers.data(
                    name="query_char",
                    shape=[1],
                    dtype='int64',
                    lod_level=1)
```
然后使用下面的save_inference_model保存模型
```
fluid.io.save_inference_model(epoch_model, ["query", "query_char"], predict, exe)
```

载入模型：
```
[inference_program, feed_target_names, fetch_targets] = fluid.io.load_inference_model(model_path, exe)
```

 预测时候遇到问题：
```
score = exe.run(inference_program,
                feed=data2tensor({"query": 4, "query_char": [3,2,5]}, place),
                fetch_list=fetch_targets,
                return_numpy=True)

def data2tensor(data, place):
    res = dict()
    res["query"] = to_lodtensor(data["query"], place)
    res["query_char"] = to_lodtensor(data["query_char"], place)
    return res

def to_lodtensor(data, place):
    res = fluid.LoDTensor()
    res.set(data, place)
    return res
```

在预测时候，data2tensor函数调用to_lodtensor将数据转化后给到模型,报如下错误：
paddle.fluid.core.EnforceNotMet: enforce ids_dims.size() == 2 failed, 0 != 2
 at [/paddle/paddle/fluid/operators/lookup_table_op.cc:43]
PaddlePaddle Call Stacks:

**Comment by Superjomn** [comment]
![image](https://user-images.githubusercontent.com/328693/46795696-69891e00-cd7d-11e8-8866-ab8c89efbaf2.png)

这里应该是二维的 numpy.array 才行，不然没有shape

**Comment by Superjomn** [comment]
刚说的有问题。

试下

{"query": [4], ...

得有个list

详细的可以参考 https://github.com/PaddlePaddle/models/blob/develop/fluid/language_model/infer.py#L28

**Comment by 333caowei** [comment]
现在错误现在变成了
RuntimeError: Some of your fetched tensors hold LoD information.             They can not be completely cast to Python ndarray.             Please set the parameter 'return_numpy' as 'False'
看上去需要把return_numpy=False
但是这样得到的预测结果分数不是numpy的

**Comment by 333caowei** [comment]
已解决，print np.array(output[0])即可
