### ISSUE TITLE
paddle计算cost和auc的原理

### ISSUE THREAD

**Issue by zds9204** [PaddlePaddle/Paddle#13824]
请教，paddle如何计算cost和auc？我的训练输出如下：cost在跳跃，auc却绝大部份时候都在稳定上升。是和auc的计算方式有关系吗？这个值可信吗？还有就是每次做完测试，下面的训练步骤中，auc会稍稍降低一点
>Pass 1, batch 1909, cost 0.19247454, auc 0.6434270107163857
Pass 1, batch 1919, cost 0.22812182, auc 0.6434267787963717
Pass 1, batch 1929, cost 0.24577512, auc 0.6434510845627743
Pass 1, batch 1939, cost 0.20186093, auc 0.643460327533481
Pass 1, batch 1949, cost 0.22698459, auc 0.6435032802800212
Pass 1, batch 1959, cost 0.19867998, auc 0.6435776448961714
Pass 1, batch 1969, cost 0.16872633, auc 0.6435772155782321
Pass 1, batch 1979, cost 0.22229147, auc 0.6436030926709777
Pass 1, batch 1989, cost 0.22751878, auc 0.6436795211141892
Pass 1, batch 1999, cost 0.16602051, auc 0.643698203486087
Test with Pass 1, batch 1999, cost 0.16868488, auc 0.6425449517748172
Pass 1, batch 2009, cost 0.17661315, auc 0.641565554032737
Pass 1, batch 2019, cost 0.19275923, auc 0.6415964804081982
Pass 1, batch 2029, cost 0.18021822, auc 0.641636031573152
Pass 1, batch 2039, cost 0.18022606, auc 0.641631451746716

我的计算代码如下：
```
predict = layers.fc(input=combined, size=2, act="softmax")

label = layers.data(name='label', shape=[1], dtype='int64')
auc_var, cur_auc_var = fluid.layers.auc(
input=predict, label=label, num_thresholds=2 ** 12)

cost = layers.cross_entropy(input=predict, label=label)

avg_cost = layers.mean(cost)

return predict, avg_cost, auc_var
```

**Comment by seiriosPlus** [comment]
```
auc_var, cur_auc_var = fluid.layers.auc(input=predict, label=label, num_thresholds=2 ** 12)
```

auc_var 是一个全局累加值，因此波动较小
cur_auc_var 是没有配置 ```step_slices``` 的话是计算当前batch对应的auc的值， 跟当前batch有关

**Comment by HugoLian** [comment]
我们这边用过几个模型，
LR  GBDT  DNN, 其中DNN是paddle，前两个不是paddle训练的。
三种模型的AUC都能再0.72-0.74 但从线上效果来看，LR GBDT在0.74的AUC都有比较稳定的表现，但是PADDLE出来的0.73-0.74效果就比那两个差非常多，所以同问PADDLE的AUC计算是否可信？

**Comment by zds9204** [comment]
> ```
> auc_var, cur_auc_var = fluid.layers.auc(input=predict, label=label, num_thresholds=2 ** 12)
> ```
> auc_var 是一个全局累加值，因此波动较小
> cur_auc_var 是没有配置 `step_slices` 的话是计算当前batch对应的auc的值， 跟当前batch有关


全局累加的话是取平均吗？为什么像我给出了例子里，每次test之后auc都会下降一段时间？
一般训练的时候观察哪个指标比较合理呢？

**Comment by seiriosPlus** [comment]
1. 如果是用的load_inference_model计算test，需要把auc相关的值先置0.
2. 全局累加的话是取所有auc平均

**Comment by CruiseSun** [comment]
我刚好也遇到了相似的问题，请问：
1. global auc是全局累计取平均值？那是不是等同于我记录每个batch auc，然后将它们求和平均呢？
2. 用load_inference_model计算test的auc，如何把global auc给先置0呢？

**Comment by seiriosPlus** [comment]
1. global auc是全局累计取平均值？那是不是等同于我记录每个batch auc，然后将它们求和平均呢?
     答： 不是，AUC是累加值进行计算的，不是求平均
2. 用load_inference_model计算test的auc，如何把global auc给先置0呢？
在调用auc layers的时候，会返回三个值 第一个是 全局auc的var, 第二个是 batch auc的var, 第三个是auc相关的状态记录的var。 参见https://github.com/PaddlePaddle/Paddle/blob/c4c5f0b8ca79fdb35397f0e96ce1050a4a8961dc/python/paddle/fluid/layers/metric_op.py#L190。
如何把global auc给置0， 可以参考代码， 其中的auc_states为auc相关的状态记录的var：
        def set_zero(var_name):
            param = inference_scope.var(var_name).get_tensor()
            param_array = np.zeros(param._get_dims()).astype("int64")
            param.set(param_array, place)

        for auc_state in auc_states:
            set_zero(auc_state.name)

**Comment by CruiseSun** [comment]
我现在想在固定步数的batch后进行一次test，可是如果这样吧auc的状态给置0了，感觉会影响到train auc的累加吧？不知道该怎么解决好，是重新定义一个auc layer还是有什么更好的办法？

**Comment by lighthearts** [comment]
> 我现在想在固定步数的batch后进行一次test，可是如果这样吧auc的状态给置0了，感觉会影响到train auc的累加吧？不知道该怎么解决好，是重新定义一个auc layer还是有什么更好的办法？

有同样的疑问，关注

**Comment by bluemandora** [comment]
>        如何把global auc给置0， 可以参考代码， 其中的auc_states为auc相关的状态记录的var：
>        def set_zero(var_name):
>        param = inference_scope.var(var_name).get_tensor()
>        param_array = np.zeros(param._get_dims()).astype("int64")
>        param.set(param_array, place)
>        ```
>         for auc_state in auc_states:
>             set_zero(auc_state.name)
>        ```
这里的inference_scope是怎么获取的？

**Comment by gzu-hmjiang** [comment]
param = inference_scope.var(var_name).get_tensor()这个inference_scope是什么呢？
