### ISSUE TITLE
在sentiment demo里面,predict.sh 输入不认识的单词就报错？

### ISSUE THREAD

**Issue by Bonsen** [PaddlePaddle/Paddle#1383]
比如输入"lstm"，出现
MemoryHandle.cpp:52 Check failed: size != 0 allocate 0 bytes
*** Check failure stack trace: ***
....
.....
请问如何debug并进行修改？？

**Comment by qingqing01** [comment]
感谢你的反馈。 实际如果输入样本的所有word不在词典之中，应该丢弃该样本，稍后我会在https://github.com/PaddlePaddle/Paddle/blob/develop/demo/sentiment/predict.py 中添加判断。

**Comment by Bonsen** [comment]
@qingqing01 改完说一声哈，谢谢

**Comment by Bonsen** [comment]
@qingqing01 
我在main函数内140 line 改为：
batch = []
ifcan = []
for line in sys.stdin:
    ifcan = predict.get_index(line)
    if not ifcan:
        print("The word does not exist .")
        break
    else:
        batch.append(ifcan)
