### ISSUE TITLE
在编译带有mkldnn的库中，预测多线程性能降低问题

### ISSUE THREAD

**Issue by tensor-tang** [PaddlePaddle/Paddle#13845]
## BUG复现步骤：

编译带有mkldnn版本的预测库。

跑单侧test_analyzer_rnn1.profile, bs100, threads=10

## 期望结果：

 线程数为10的时候，每个线程所用时间，与单线程时基本不变。

## 实际结果：

多线程时，每个线程耗时是单线程时的10倍左右。

## 问题原因
在编译带有mkldnn的版本时，默认是不设置线程数为1的，因为mkldnn训练时是需要多线程加速。

解决办法，在预测init的时候添加默认值，保证在含有mkldnn的情况下预测默认也可以用paddle_num_threads控制线程数。

**Comment by luotao1** [comment]
未修复前的版本，可以通过使用`export OMP_NUM_THREADS=1`和`export MKL_NUM_THREADS=1`来保证速度。

**Comment by HugoLian** [comment]
@luotao1 我们也遇到了相似的问题，不过这个问题描述不知道和我们的是否一样。我们capi版本是：cpu_avx_mkl 0.14那个版本
预测的时候发现随着网络结构的复杂，多线程的性能降低的很厉害。尤其是在ORCP本身多线程的服务中，每个线程再开若干个paddle_gradient_machine的多线程预测，耗时就会严重增长。

这和楼主是一个问题么？除了减少paddle线程，有什么办法可以优化么？
