### ISSUE TITLE
关于embedding稀疏更新（is_sparse参数）原理的解释

### ISSUE THREAD

**Issue by 333caowei** [PaddlePaddle/Paddle#13842]
fluid 稀疏更新：http://www.paddlepaddle.org/documentation/api/zh/0.14.0/layers.html#permalink-48-embedding
v2 稀疏更新：http://www.paddlepaddle.org/documentation/api/zh/0.12.0/config/attr.html

在embedding的size特别大的情况下，embedding层是否开启is_sparse训练速度差别很大，请教下述问题：
1、请教稀疏更新的原理是啥，为什么能够加速训练？
2、开启和不开启稀疏更新训练出来的模型对于预测结果是否有差别？如果没有区别为什么要专门加一个is_sparse的参数？
3、之前在v2版本使用embedding稀疏更新+adagrad发现loss下降的很慢（v2不支持Adam的稀疏更新）。后来切换到fluid以后，使用稀疏更新+adam发现loss能很快下降，不知是何原因。

**Comment by jacquesqiao** [comment]
1 稀疏更新的时候，梯度会比较小，这样对于网络通信和计算来说都会更快，当embedding特别大的时候，效果会非常明显
2. 没有差别，但并不是所有场景都是打开is_sparse比较好，embedding很小的时候就不需要打开
3. 不清楚，需要具体分析
