### ISSUE TITLE
Some Unit Tests fail due to TinyFormat assertion

### ISSUE THREAD

**Issue by Sand3r-** [PaddlePaddle/Paddle#13860]
Since one of the recent commits, I have started receiving the following errors thrown by many different tests, especially those from `test_analyzer_*` family.

```
test_analyzer_resnet50: /home/sand3r/Repos/Paddle/paddle/fluid/string/tinyformat/tinyformat.h:563: const char* paddle::string::tinyformat::detail::streamStateFromFormat(std::ostream&, bool&, int&, const char*, const paddle::string::tinyformat::detail::FormatArg*, int&, int): Assertion `0 && "tinyformat: Not enough conversion specifiers in format string"' failed.
```

@luotao1, could you please assist me with solving this issue?

**Comment by luotao1** [comment]
We don't encounter this error both in TeamCity and the local server. Could you give more details to reproduce this issue?
- What's your development environment, docker image?
- What's your cmake command? 
- Do you use the latest develop code?

You can `rm -rf build` to rebuild and test at first.

**Comment by Sand3r-** [comment]
Thank you for the response @luotao1.
- I do not use docker image, but paddle built from source. Has any new library been recently added to docker image? By recently I mean last ~2 weeks.
- `cmake -DCMAKE_BUILD_TYPE=Debug -DWITH_GPU=OFF -DWITH_MKLDNN=ON -DWITH_TESTING=ON -DWITH_PROFILER=ON -DWITH_STYLE_CHECK=OFF -DWITH_INFERENCE=ON -DWITH_INFERENCE_API_TEST=ON -DINFERENCE_DEMO_INSTALL_DIR=/home/mgallus/.cache/inference_demo ..`
- I use the latest develop code indeed.

I've tried removing build as well a few times.

Also, this issue is related to #13894.

**Comment by luotao1** [comment]
@Sand3r- We reproduce this issue, the reason is `cmake -DCMAKE_BUILD_TYPE=Debug`. If you are in `cmake -DCMAKE_BUILD_TYPE=Release` mode, there is no error.
And #13850 fix this issue, you can merge with the latest code.

**Comment by yiakwy** [comment]
@luotao1 @Sand3r-  The error can be reproduced in released 2.0 when `-DCMAKE_BUILD_TYPE=Debug`. It is apparently straight forward that the source code of the tinyformat was not used correctly.

I have recently compiled released 2.0 with gcc-8.4 in release mode[of course I have fixed many bugs including the old trainer/demo, and many errors in Documentation]. 

And now I am trying to compile in gcc-8.2 in debug mode to avoid frequently regenerated dynamic content [it seems that the code generation in cmake was not written correctly with cmake dependency system. Of course you can let cmake to know whether the dependencies of dynamic generated content is changed by specifying dependencies in `add_custom_command`].


```
[ 99%] Built target paddle_inference_c
copy_if_different /home/yiak/WorkSpace/Github/Paddle/paddle/fluid/pybind/op_function_impl.h
op_function_generator: /home/yiak/WorkSpace/Github/Paddle/paddle/fluid/string/tinyformat/tinyformat.h:782: void paddle::string::tinyformat::detail::formatImpl(std::ostream&, const char*, const paddle::string::tinyformat::detail::FormatArg*, int): Assertion `0 && "tinyformat: Too many conversion specifiers in format string"' failed.
Child aborted
paddle/fluid/pybind/CMakeFiles/op_function_generator.dir/build.make:673: recipe for target 'paddle/fluid/pybind/op_function_generator' failed
make[2]: *** [paddle/fluid/pybind/op_function_generator] Error 1
make[2]: *** Deleting file 'paddle/fluid/pybind/op_function_generator'
CMakeFiles/Makefile2:85748: recipe for target 'paddle/fluid/pybind/CMakeFiles/op_function_generator.dir/all' failed
make[1]: *** [paddle/fluid/pybind/CMakeFiles/op_function_generator.dir/all] Error 2

```

The #13850 is not the cure to the problem.

Please check whether the correct version of the tinyformat source is used.

I will post a new article on how to compile paddle and use it in a cmake project in a rgiht way:
complie it with gcc - 8.4 (WorkStation 1, 32 cores, 1 GPU card):
![paddled_installed](https://user-images.githubusercontent.com/8510840/110333054-19047080-805c-11eb-8bcf-9b885e16631f.png)
![paddle_gcc-8 4](https://user-images.githubusercontent.com/8510840/110333067-1e61bb00-805c-11eb-9b9e-0579f27d2437.png)

compile it with gcc - 8.2 (WorkStation 2, 8 cores, 2 GPU cards) :
![paddle-gcc_8 2](https://user-images.githubusercontent.com/8510840/110333084-24579c00-805c-11eb-815d-0c602b9cc70e.png)

**Comment by luotao1** [comment]
@swtkiwi Please see how to process the build problem under Debug mode.

**Comment by yiakwy** [comment]
@luotao1 @Sand3r- @swtkiwi  I have resolved the problem:

Quick Solution
===========

Open Paddle/fluid/string/tinyformat/tinyformat.h, move your cursor to detail::formatImpl and line 779

replace the codes
```
  fmt = printFormatStringLiteral(out, fmt);
  if (*fmt != '\0')
    TINYFORMAT_ERROR(
        "tinyformat: Too many conversion specifiers in format string");
```
to 

```
  fmt = printFormatStringLiteral(out, fmt);
  if (fmt != nullptr && *fmt != '\0' && *fmt != 0)
    TINYFORMAT_ERROR(
        "tinyformat: Too many conversion specifiers in format string");
```

Reason
======

When set CMAKE_BUILD_TYPE to Debug, the fluid/operators/controlflow/compare_op.cc is involved 

```
    AddInput("X", string::Sprintf("the left hand operand of %s operator",
                                  comment.type));
```

The safe printer actually passes a C style string pointer **without adding `\0` to the end**!
