### ISSUE TITLE
在paddleapddle v11.0版本中，用LSTM模型，如何预测数据

### ISSUE THREAD

**Issue by 1727536969** [PaddlePaddle/Paddle#13877]
在paddle.v2在LSTM中，得到了一个模型，现在遇到的问题是如何传入X的值，
代码如下，
rsult=paddle.infer(
正中间的代码怎么写？，
)

**Comment by Superjomn** [comment]
可以增加一些描述或者代码，不太能理解问题

**Comment by 1727536969** [comment]
是这样的，在LSTM中 paddle是paddle.v2 as paddle 。想要预测结果
result=paddle.infer(
input=x,
parameters=parameters,
output_layer=output,
feeding={'x':0}
)
我想问的是数据x的结构是什么类型的数据。才能传入。目前我把x制成了二维矩阵。运行不了

**Comment by Superjomn** [comment]
你是paddle v2，目前已经停止开发了?  建议迁移到 paddle fluid， 跟tf 使用方法类似。
