### ISSUE TITLE
【question】hsigmoid层的原理及用法

### ISSUE THREAD

**Issue by pkuyym** [PaddlePaddle/Paddle#1387]
文档上给出的解释是：

> Organize the classes into a binary tree. At each node, a sigmoid function is used to calculate the probability of belonging to the right branch
> cost = hsigmoid(input=[layer1, layer2],
>                 label=data_layer,
>                 num_classes=3)

问题1:
word2vec里面是建立一个哈夫曼树，来最小化总开销，这里面并没有类别的频次信息，所以应该不是构建哈夫曼树，请问binary tree如何建立

问题2:
这个输出是一个cost，在训练时没有问题，请问在predict时，如何获取每个类别的概率？

问题3:
有没有经验，这样做会多大程度上影响模型的收敛？

**Comment by luotao1** [comment]
第一个问题可以参考[HierarchicalSigmoidLayer.h](https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/gserver/layers/HierarchicalSigmoidLayer.h#L22)中的注释。

**Comment by pkuyym** [comment]
@luotao1 谢谢，理解了，这里应该有优化空间，构建哈夫曼树，可以大幅减少总开销

**Comment by luotao1** [comment]
不客气，不过NCE_Layer目前不支持GPU上的计算，请知晓。
