### ISSUE TITLE
CRNN-CTC SOTA Accuracy and Error Understanding

### ISSUE THREAD

**Issue by hshen14** [PaddlePaddle/Paddle#13878]
I followed the comments in https://github.com/PaddlePaddle/Paddle/issues/13574#issuecomment-424587581 to reproduce the accuracy of CRNN-CTC after a minor fixing below:

diff --git a/fluid/ocr_recognition/eval.py b/fluid/ocr_recognition/eval.py
index 666803d..87f4f9c 100644
--- a/fluid/ocr_recognition/eval.py
+++ b/fluid/ocr_recognition/eval.py
@@ -31,7 +31,7 @@ def evaluate(args):
     num_classes = data_reader.num_classes()
     data_shape = data_reader.data_shape()
     # define network
-    evaluator, cost = eval(data_shape, num_classes)
+    evaluator, cost = eval(data_shape, num_classes, True if args.use_gpu else False)

I got the below metrics:
Read 2000 samples; avg_distance: [0.08513155]; avg_seq_error: [0.2255]

Can we understand the output is SOTA accuracy? How can I understand the meaning of the avg_distance and avg_seq_error? Is there any formula behind? Thanks.

**Comment by wanghaoshuang** [comment]
`avg_distance` means average edit distance.
`avg_seq_error` is the rate of samples whose edit distance is not zero. So accuracy should be (1 - avg_seq_error).
(1-0.2255) is the SOTA accuracy on the dataset introduced [here](https://github.com/PaddlePaddle/models/blob/develop/fluid/ocr_recognition/README.md).

**Comment by hshen14** [comment]
Thanks. I know edit distance by the wiki introduction. Could you please help translate 0.08513155? The numerator should be total edit distance, the denominator is the total length of all tested words? For example, saying a word "abc", if predicted result is acc, the avg_distance should be 1 / 3?

Is 77.45% SOTA accuracy same as yours? I would like to confirm that since we will use it as the reference accuracy for INT8 inference. @wanghaoshuang

**Comment by hshen14** [comment]
@wanghaoshuang

**Comment by wanghaoshuang** [comment]
>For example, saying a word "abc", if predicted result is acc, the avg_distance should be 1 / 3?

Yes. You are right. The edit distance will be [normalized]([https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/fluid/layers/nn.py#L3729]) by the length of sequence.

>Is 77.45% SOTA accuracy same as yours? I would like to confirm that since we will use it as the reference accuracy for INT8 inference.

Actually the best `avg_seq_error` was 21.11%. But it's hard to reproduce the SOTA accuracy because of random factors.

**Comment by hshen14** [comment]
@wanghaoshuang Is it possible to share the parameter that can reach 21.11% error?

**Comment by wanghaoshuang** [comment]
@hshen14 Sorry. I was confused by chinese dataset and english dataset.  21.11% error is the SOTA of Chinese dataset which is not published. And 22.0% error is the SOTA of english dataset introduced in readme.   I have only the parameters that can reach 22.3% error.

**Comment by hshen14** [comment]
22.3% is for English dataset? Could you please share the link? I think mine is 22.55%.

**Comment by hshen14** [comment]
I also found the data shape is a little confusing in CRNN-CTC:
* In data_reader.py, DATA_SHAPE = [1, 48, 512]
* In eval.py, the image size is 48 x 384

Shall we change DATA_SHAPE here? @wangguibao @tpatejko @luotao1

**Comment by wojtuss** [comment]
Closed, due to INT8v1 having been removed.
