### ISSUE TITLE
CUDA driver version is insufficient for CUDA runtime version

### ISSUE THREAD

**Issue by shippingwang** [PaddlePaddle/Paddle#13882]
用GPU跑Book的例子，报错CUDA driver version is insufficient for CUDA runtime version，
重新docker安装与显卡驱动匹配的latest-gpu-cuda8.0-cudnn7镜像，仍然报错。

**Comment by lucywsq** [comment]
您好，方便的话请您贴出详细报错代码，以便后续复现~
