### ISSUE TITLE
对Python API注释的建议：cos_sim layer

### ISSUE THREAD

**Issue by mapingshuo** [PaddlePaddle/Paddle#13886]
我最近在根据fluid0.15.0版本的中文文档学习fluid， 我发现一个fluid layer 叫做 cos_sim 的layer, 她计算两个向量的cosine相似度：http://paddlepaddle.org/documentation/api/zh/0.15.0/layers.html#permalink-40-cos_sim

**Comment by mapingshuo** [comment]
然而我发现文档的公式中使用大写的X和Y来表示向量，我觉得不妥，一般大写表示矩阵。另外我觉得文档应该对用户输入矩阵时对矩阵的预处理解释一下，比如说：如果输入是矩阵，矩阵会首先被拉伸为一个向量，然后按照向量的cosine相似度来计算。

**Comment by shanyi15** [comment]
查了下发现1.0文档有一样的问题 http://paddlepaddle.org/documentation/api/zh/1.0.0/layers.html#cos-sim

**Comment by shanyi15** [comment]
@mapingshuo 请参看这里 https://en.wikipedia.org/wiki/Cosine_similarity 这里用的是大写

**Comment by mapingshuo** [comment]
用户可能需要被明示公式中的X和Y表示的是矩阵还是向量：当用户输入的Tensor的shape为[batch_size, N]时，不存在误解，一切都很好；当用户输入的向量shape为 X: [batch_size, M, N], Y: [batch_size, M, N]时，他会开始疑惑：X^T * Y 是什么操作呢？是矩阵乘法还是向量乘法呢？如果是向量乘法，矩阵怎么转换为向量呢？

**Comment by shanyi15** [comment]
辛苦 @typhoonzero  看一下是否需要改python 注释里的说明，感谢

**Comment by typhoonzero** [comment]
需要完善下，这样会清晰一点。我会更新下这个文档。

**Comment by lucywsq** [comment]
您好，此issue在近一个月内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题，我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持!
