### ISSUE TITLE
训练过程报错paddle.fluid.core.EnforceNotMet: Cannot open file recommender_case.inference.model1/case_table for load op at [/paddle/paddle/fluid/operators/load_op.cc:39]

### ISSUE THREAD

**Issue by fengshuting** [PaddlePaddle/Paddle#13898]
Traceback (most recent call last):
  File "/tmp/pycharm_project_707/train.py", line 289, in <module>
    main(USE_GPU)
  File "/tmp/pycharm_project_707/train.py", line 286, in main
    params_dirname=params_dirname)
  File "/tmp/pycharm_project_707/train.py", line 234, in infer
    inference_program, param_path=params_dirname, place=place)
  File "/usr/local/lib/python2.7/dist-packages/paddle/fluid/inferencer.py", line 68, in __init__
    io.load_params(executor.Executor(self.place), param_path)
  File "/usr/local/lib/python2.7/dist-packages/paddle/fluid/io.py", line 454, in load_params
    filename=filename)
  File "/usr/local/lib/python2.7/dist-packages/paddle/fluid/io.py", line 376, in load_vars
    filename=filename)
  File "/usr/local/lib/python2.7/dist-packages/paddle/fluid/io.py", line 407, in load_vars
    executor.run(load_prog)
  File "/usr/local/lib/python2.7/dist-packages/paddle/fluid/executor.py", line 470, in run
    self.executor.run(program.desc, scope, 0, True, True)
paddle.fluid.core.EnforceNotMet: Cannot open file recommender_case.inference.model1/case_table for load op at [/paddle/paddle/fluid/operators/load_op.cc:39]
PaddlePaddle Call Stacks: 
0       0x7fd508116d86p paddle::platform::EnforceNotMet::EnforceNotMet(std::__exception_ptr::exception_ptr, char const*, int) + 486
1       0x7fd50881c818p paddle::operators::LoadOp::RunImpl(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&) const + 1864
2       0x7fd508ae600fp paddle::framework::OperatorBase::Run(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&) + 255
3       0x7fd5081d49d9p paddle::framework::Executor::RunPreparedContext(paddle::framework::ExecutorPrepareContext*, paddle::framework::Scope*, bool, bool, bool) + 393
4       0x7fd5081d55d0p paddle::framework::Executor::Run(paddle::framework::ProgramDesc const&, paddle::framework::Scope*, int, bool, bool) + 128
5       0x7fd5080fe65dp
6       0x7fd508149034p pybind11::cpp_function::dispatcher(_object*, _object*, _object*) + 2596
7             0x4c37edp PyEval_EvalFrameEx + 31165
8             0x4b9ab6p PyEval_EvalCodeEx + 774
9             0x4c16e7p PyEval_EvalFrameEx + 22711
10            0x4b9ab6p PyEval_EvalCodeEx + 774
11            0x4c16e7p PyEval_EvalFrameEx + 22711
12            0x4b9ab6p PyEval_EvalCodeEx + 774
13            0x4c16e7p PyEval_EvalFrameEx + 22711
14            0x4b9ab6p PyEval_EvalCodeEx + 774
15            0x4c16e7p PyEval_EvalFrameEx + 22711
16            0x4b9ab6p PyEval_EvalCodeEx + 774
17            0x4d55f3p
18            0x4eebeep
19            0x4ee7f6p
20            0x4aa9abp
21            0x4c15bfp PyEval_EvalFrameEx + 22415
22            0x4b9ab6p PyEval_EvalCodeEx + 774
23            0x4c1e6fp PyEval_EvalFrameEx + 24639
24            0x4b9ab6p PyEval_EvalCodeEx + 774
25            0x4c1e6fp PyEval_EvalFrameEx + 24639
26            0x4b9ab6p PyEval_EvalCodeEx + 774
27            0x4eb30fp
28            0x4e5422p PyRun_FileExFlags + 130
29            0x4e3cd6p PyRun_SimpleFileExFlags + 390
30            0x493ae2p Py_Main + 1554
31      0x7fd5263cf830p __libc_start_main + 240
32            0x4933e9p _start + 41

**Comment by lucywsq** [comment]
您好，此issue在近一个月内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题，我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持!
