### ISSUE TITLE
Not enough conversion specifiers in format string

### ISSUE THREAD

**Issue by wojtuss** [PaddlePaddle/Paddle#13894]
In the following call to `Sprintf()` function the format string does not contain enough conversion specifiers. This causes an assertion fail.

https://github.com/PaddlePaddle/Paddle/blob/2c9839c847fa3382e4e2165aa8b66413ad92ab98/paddle/fluid/operators/isfinite_op.cc#L62-L73

**Comment by luotao1** [comment]
fixed by #13850
