### ISSUE TITLE
It seems Python API memory_optimization will hang in some model.

### ISSUE THREAD

**Issue by qingqing01** [PaddlePaddle/Paddle#13892]
1.  I found https://github.com/PaddlePaddle/models/tree/develop/fluid/deeplabv3%2B will hang in memory_optimization calling on V100 by the latest Paddle develop branch code without docker.
     But it is ok on P40 with the save version with docker image.
2. Someone  also found memory_optimization will hang in [other model](https://github.com/PaddlePaddle/models/tree/develop/fluid/face_detection) on P40 by v1.0.1 version without docker.
     But there is no problem serveral weeks ago when I train this model with docker env.

 Both these two models are deep.

**Comment by dzhwinter** [comment]
Update. I had tested on @qingqing01 's machine, I turn off the io buffer of python "python -u train.py".  This issue cannot reproduce inside docker and out of docker.
