### ISSUE TITLE
v2-12 capi预测库cpu_avx_mkl版本出core："Program terminated with signal 4, Illegal instruction" 

### ISSUE THREAD

**Issue by CtfGo** [PaddlePaddle/Paddle#13902]
paddle v2-12 capi预测库的cpu_avx_mkl版本出core，提示Program terminated with signal 4, Illegal instruction，栈信息如下：
#0  0x00007f34659b307b in paddle::CpuMatrix::addBias () from /home/work/feedvideorank_4ae8ba872924afd993288210fb2a0f48/bin/libpaddle_capi_shared.so
#1  0x0000000000000001 in ?? ()
#2  0x00007f33f8bf7fa0 in ?? ()
#3  0x00007f345b3b0538 in ?? () from /opt/compiler/gcc-4.8.2/lib/libstdc++.so.6
#4  0x0000000000000000 in ?? ()

内核版本：2.6.32_1-15-0-0  x86_64
看了下出core的机器都是core-avx-i的，相同服务部署在core-avx2机器上没发现问题，请问是什么原因？有什么解决方案吗？

**Comment by frankwhzhang** [comment]
暂时关闭此issue 如有问题可以重开
