### ISSUE TITLE
Some of your fetched tensors hold LoD information

### ISSUE THREAD

**Issue by qshi95** [PaddlePaddle/Paddle#13903]
Some of your fetched tensors hold LoD information.             They can not be completely cast to Python ndarray.             Please set the parameter 'return_numpy' as 'False' to             return LoDTensor itself directly.

请问LoD tensor 转化为Tensor该怎么操作呢 谢谢

**Comment by Derekglk** [comment]
Hi qshi95,

这个问题解决了么？我加载一个__model__和__params__过后，想dump某个op出来的结果看看，就会报上边您说的这个错误。
谢谢。
