### ISSUE TITLE
关于capi的paddle_gradient_machine_create_for_inference_with_parameters在模型预测时出错

### ISSUE THREAD

**Issue by shibing624** [PaddlePaddle/Paddle#13911]
https://user-images.githubusercontent.com/10249622/46992060-04e21080-d13b-11e8-8ee1-57d1bce12c2e.png
python 调用C++生成的.so时，如上图出错，请问怎么解决？

**Comment by wangguibao** [comment]
@shibing624 请问能帖一下您调用时的代码吗？如果可以，请把截图里文字也拷贝一下帖一下，方便我们跟进，谢谢

**Comment by shibing624** [comment]
内存问题导致的，已经解决了，谢谢。
