### ISSUE TITLE
[编译安装] nvidia-docker运行镜像latest-gpu-cuda8.0-cudnn7: SIGILL

### ISSUE THREAD

**Issue by shippingwang** [PaddlePaddle/Paddle#13920]
sudo nvidia-docker run --name Paddle -it -v $PWD:/work hub.baidubce.com/paddlepaddle/paddle:latest-gpu-cuda8.0-cudnn7 /bin/bash

>>> import paddle.fluid
*** Aborted at 1539682149 (unix time) try "date -d @1539682149" if you are using GNU date ***
PC: @                0x0 (unknown)
*** SIGILL (@0x7f6ac6ea9436) received by PID 16 (TID 0x7f6b07bc7700) from PID 18446744072751846454; stack trace: ***

**Comment by wangguibao** [comment]
Hi, 请参考https://github.com/PaddlePaddle/Paddle/issues/13925 ，确认一下是否是指令集不支持

**Comment by wangguibao** [comment]
@shippingwang 辛苦看一下是否是CPU指令集不支持；如果是的话，我们已经在跟进类似的case

**Comment by shippingwang** [comment]
> @shippingwang 辛苦看一下是否是CPU指令集不支持；如果是的话，我们已经在跟进类似的case

更改为latest-gpu版本运行了：）
