### ISSUE TITLE
paddle.fluid.core.EnforceNotMet: Failed to find dynamic library: libwarpctc.so ( dlopen: cannot load any more object with static TLS ) 

### ISSUE THREAD

**Issue by liushanshan07** [PaddlePaddle/Paddle#13935]
训练时出现如下错误信息
File "train.py", line 157, in <module>
    main()
  File "train.py", line 153, in main
    train(args, data_reader=ctc_reader)
  File "train.py", line 120, in train
    results = train_one_batch(data)
  File "train.py", line 89, in train_one_batch
    feed=get_feeder_data(data, place))
  File "/usr/local/lib/python2.7/site-packages/paddle/fluid/parallel_executor.py", line 276, in run
    self.executor.run(fetch_list, fetch_var_name)
paddle.fluid.core.EnforceNotMet: Failed to find dynamic library: libwarpctc.so ( dlopen: cannot load any more object with static TLS ) 
 Please specify its path correctly using following ways: 
 Method. set environment variable LD_LIBRARY_PATH on Linux or DYLD_LIBRARY_PATH on Mac OS. 
 For instance, issue command: export LD_LIBRARY_PATH=... 
 Note: After Mac OS 10.11, using the DYLD_LIBRARY_PATH is impossible unless System Integrity Protection (SIP) is disabled. at [/paddle/paddle/fluid/platform/dynload/dynamic_loader.cc:138]
PaddlePaddle Call Stacks: 
0       0x7fef0ff4de86p paddle::platform::EnforceNotMet::EnforceNotMet(std::__exception_ptr::exception_ptr, char const*, int) + 486
1       0x7fef110c2822p paddle::platform::dynload::GetWarpCTCDsoHandle() + 1618
2       0x7fef10bebb19p _ZSt16__once_call_implISt12_Bind_simpleIFZN6paddle8platform7dynload28DynLoad__get_warpctc_versionclIIEEEDTcl19get_warpctc_versionspfp_EEDpT_EUlvE_vEEEvv + 9
3       0x7fef79261b23p pthread_once + 83
4       0x7fef10bf35a8p paddle::operators::WarpCTCFunctor<paddle::platform::CUDADeviceContext>::operator()(paddle::framework::ExecutionContext const&, float const*, float*, int const*, int const*, int const*, unsigned long, unsigned long, unsigned long, float*) + 136
5       0x7fef10bf4f11p paddle::operators::WarpCTCKernel<paddle::platform::CUDADeviceContext, float>::Compute(paddle::framework::ExecutionContext const&) const + 1921
6       0x7fef10bf5883p _ZNSt17_Function_handlerIFvRKN6paddle9framework16ExecutionContextEEZNKS1_24OpKernelRegistrarFunctorINS0_8platform9CUDAPlaceELb0ELm0EJNS0_9operators13WarpCTCKernelINS7_17CUDADeviceContextEfEEEEclEPKcSF_EUlS4_E_E9_M_invokeERKSt9_Any_dataS4_ + 35
7       0x7fef10f385bep paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&) const + 526
8       0x7fef10f3564cp paddle::framework::OperatorBase::Run(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&) + 252
9       0x7fef10d7a7a7p
10      0x7fef10d98930p
11      0x7fef10d98195p paddle::framework::details::OpHandleBase::RunAndRecordEvent(std::function<void ()()> const&) + 805
12      0x7fef10d7a27fp paddle::framework::details::ComputationOpHandle::RunImpl() + 95
13      0x7fef10d99235p paddle::framework::details::OpHandleBase::Run(bool) + 117
14      0x7fef10d58cbap
15      0x7fef10bd56a3p std::_Function_handler<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> ()(), std::__future_base::_Task_setter<std::unique_ptr<std::__future_base::_Result<void>, std::__future_base::_Result_base::_Deleter>, void> >::_M_invoke(std::_Any_data const&) + 35
16      0x7fef100a35d7p std::__future_base::_State_base::_M_do_set(std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> ()()>&, bool&) + 39
17      0x7fef79261b23p pthread_once + 83
18      0x7fef10d57ac2p
19      0x7fef100a5114p _ZZN10ThreadPoolC1EmENKUlvE_clEv + 404
20      0x7fef26d60470p
21      0x7fef7925c851p
22      0x7fef7891f90dp clone + 109

**Comment by luotao1** [comment]
可以看下`/usr/local/lib/python2.7/site-packages/paddle/libs`有没有

**Comment by liushanshan07** [comment]
嗯。有的。谢谢帮忙。请问这个so应该在训练时export进去吗还是应该咋弄，解决上面的问题呢？

**Comment by luotao1** [comment]
`export LD_LIBRARY_PATH=/usr/local/lib/python2.7/site-packages/paddle/libs` 即可

**Comment by liushanshan07** [comment]
> `export LD_LIBRARY_PATH=/usr/local/lib/python2.7/site-packages/paddle/libs` 即可

无奈再次遇到类似问题。请问如果再次报这个错，上面的python路径下又找不到libwarpctc.so，应该咋处理呢？

**Comment by luotao1** [comment]
可以从报错信息，推断libwarpctc.so在哪个路径下。
```
File "/usr/local/lib/python2.7/site-packages/paddle/fluid/parallel_executor.py", line 276, in run
self.executor.run(fetch_list, fetch_var_name)
```

**Comment by liushanshan07** [comment]
> 可以从报错信息，推断libwarpctc.so在哪个路径下。
> 
> ```
> File "/usr/local/lib/python2.7/site-packages/paddle/fluid/parallel_executor.py", line 276, in run
> self.executor.run(fetch_list, fetch_var_name)
> ```

![default](https://user-images.githubusercontent.com/31281000/47982237-f9668180-e109-11e8-8277-fbb038d68130.png)
已经export你之前给的建议。还是报这个错误。

**Comment by luotao1** [comment]
> 上面的python路径下又找不到libwarpctc.so

是不是该so不小心被删了？可以拷贝一个到相同的位置即可。

**Comment by liushanshan07** [comment]
> > 上面的python路径下又找不到libwarpctc.so
> 
> 是不是该so不小心被删了？可以拷贝一个到相同的位置即可。

拷贝到指定目录还是报相同错误。/usr/local/lib/python2.7/site-packages/paddle路径下只有libs这个目录，是不是镜像的问题呢？

**Comment by luotao1** [comment]
能重新安装一份么？我的paddle路径下有
```
/home/luotao/.jumbo/lib/python2.7/site-packages/paddle/
├── batch.py
├── compat.py
├── dataset
├── fluid
├── __init__.py
├── libs
├── reader
├── utils
└── version.py
```

**Comment by liushanshan07** [comment]
好的。我重新编译一个，在安装下。建议安装release的哪个版本呢。在v100上运行。

**Comment by luotao1** [comment]
http://www.paddlepaddle.org/documentation/docs/zh/1.1/beginners_guide/install/Tables.html/#whls 可以安装1.1版本了

**Comment by lucywsq** [comment]
您好，此issue若已经解决，我们将于三天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题，我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持!
