### ISSUE TITLE
文档链接失效：如何写新的Operator一文中，关于在PaddlePaddle中如何使用Eigen库的使用文档

### ISSUE THREAD

**Issue by barrierye** [PaddlePaddle/Paddle#13939]
我最近在根据fluid1.0版本的中文文档学习写新的Op：http://paddlepaddle.org/documentation/docs/zh/1.0/advanced_usage/development/new_op.html ，然而我发现在”关于在PaddlePaddle中如何使用Eigen库，请参考使用文档“这句话中，”使用文档“的链接已经失效了。

**Comment by shanyi15** [comment]
感谢您反馈，我们将尽快修复，请先在这里阅读 https://github.com/PaddlePaddle/FluidDoc/blob/release/1.0/doc/fluid/dev/use_eigen_cn.md

**Comment by shanyi15** [comment]
辛苦修复@tink2123

**Comment by shanyi15** [comment]
您好，文档中链接已修复http://paddlepaddle.org/documentation/docs/zh/1.0/advanced_usage/development/new_op.html
