### ISSUE TITLE
README.md里中英文档的badge链接失效

### ISSUE THREAD

**Issue by endyul** [PaddlePaddle/Paddle#13936]

**Comment by shanyi15** [comment]
感谢您反馈，正在跟进

**Comment by endyul** [comment]
<img width="187" alt="image" src="https://user-images.githubusercontent.com/1056031/47131474-6805ab80-d2d1-11e8-8c97-a5eca8d7667f.png">
@shanyi15  您好，badge图标的文档链接也需要更新，如图
