### ISSUE TITLE
在virtualenv安装的python环境下装paddlepaddle，运行时提示Fatal Python error: PyThreadState_Get: no current thread

### ISSUE THREAD

**Issue by zhangxiaoleigit** [PaddlePaddle/Paddle#13943]
Fatal Python error: PyThreadState_Get: no current thread

Process finished with exit code 134 (interrupted by signal 6: SIGABRT)

**Comment by wangguibao** [comment]
This had been resolved last night by @typhoonzero .

I asked user to elaborate detailed procedures dealing with this issue so that everyone can get help. Now waiting user feedback before closing it.

**Comment by zhangxiaoleigit** [comment]
mac版本：10.12.6
paddlepaddle版本： 1.0.1
操作步骤：
1、创建python env  ：paddleEnv
2、激活环境
3、安装paddlepaddle =>  pip install paddlepaddle
4、运行paddlepaddle 报错Fatal Python error: PyThreadState_Get: no current thread

解决方法：
    1、删除  paddleEnv/lib/python2.7/site-packages/paddle/.dylibs/  目录下的Python   文件，其中paddleEnv是用virtualenv创建的环境
    2、 增加环境变量
    export LD_LIBRARY_PATH=/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7
export DYLD_LIBRARY_PATH=/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7

需要根据自己电脑修改对应的路径，指向当前python安装路径下包含mac动态链接库"Python"文件的路径

**Comment by velconia** [comment]
This problem has been fixed in paddle 1.1 version
