### ISSUE TITLE
迫切需求支持focal loss

### ISSUE THREAD

**Issue by JFTong** [PaddlePaddle/Paddle#13947]
在样本分布不均的场景下，focal loss能够很好的解决模型过拟合到较多样本上。希望fluid能够添加下对focal loss的支持。相关paper见：https://arxiv.org/abs/1708.02002

**Comment by qingqing01** [comment]
可以使用子op拼接：
```python
def focal_loss(fc, labels, num_classes, gama):
    labels = fluid.layers.one_hot(labels, depth=num_classes)
    fc = fluid.layers.clip(x=fc, min=1e-7, max=1. - 1e-7)
    #######cross_entropy
    # loss = -1 * fluid.layers.log(fc) * labels
    # loss = fluid.layers.reduce_sum(loss, dim=1)
    #######focal loss
    loss = -1 * fluid.layers.pow(1 - fc, gama) * fluid.layers.log(fc) * labels
    loss = fluid.layers.reduce_sum(loss, dim=1)
    return loss
```

**Comment by shiyazhou121** [comment]
@qingqing01 hi，我用你给的例子时报错了。这个应该怎么改下？
Traceback (most recent call last):
  File "train.py", line 404, in <module>
    main()
  File "train.py", line 401, in main
    save_dirname=save_dirname)
  File "train.py", line 246, in train
    loss1_ce = own_loss(pred, label, CLASS_DIM, gama)
  File "train.py", line 209, in own_loss
    loss = -1 * fluid.layers.pow(1 - fc, gama) * fluid.layers.log(fc) * labels
  File "/home/disk1/normandy/maybach/app-user-20181113165234-10978/workspace/python27-gcc482/lib/python2.7/site-packages/paddle/fluid/layers/nn.py", line 5983, in pow
    attrs={'factor': factor})
  File "/home/disk1/normandy/maybach/app-user-20181113165234-10978/workspace/python27-gcc482/lib/python2.7/site-packages/paddle/fluid/layer_helper.py", line 50, in append_op
    return self.main_program.current_block().append_op(*args, **kwargs)
  File "/home/disk1/normandy/maybach/app-user-20181113165234-10978/workspace/python27-gcc482/lib/python2.7/site-packages/paddle/fluid/framework.py", line 1207, in append_op
    op = Operator(block=self, desc=op_desc, *args, **kwargs)
  File "/home/disk1/normandy/maybach/app-user-20181113165234-10978/workspace/python27-gcc482/lib/python2.7/site-packages/paddle/fluid/framework.py", line 653, in __init__
    self.desc.check_attrs()
paddle.fluid.core.EnforceNotMet: Cannot get attribute factor by type float, its type is int at [/paddle/paddle/fluid/framework/attribute.h:132]
PaddlePaddle Call Stacks: 
0       0x7f840637c176p paddle::platform::EnforceNotMet::EnforceNotMet(std::__exception_ptr::exception_ptr, char const*, int) + 486
1       0x7f84064609b0p paddle::framework::ExtractAttribute<float>::operator()(boost::variant<boost::blank, int, float, std::string, std::vector<int, std::allocator<int> >, std::vector<float, std::allocator<float> >, std::vector<std::string, std::allocator<std::string> >, bool, std::vector<bool, std::allocator<bool> >, paddle::framework::BlockDesc*, long, std::vector<paddle::framework::BlockDesc*, std::allocator<paddle::framework::BlockDesc*> >, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_>&) const + 432
2       0x7f8406461f38p std::_Function_handler<void (std::unordered_map<std::string, boost::variant<boost::blank, int, float, std::string, std::vector<int, std::allocator<int> >, std::vector<float, std::allocator<float> >, std::vector<std::string, std::allocator<std::string> >, bool, std::vector<bool, std::allocator<bool> >, paddle::framework::BlockDesc*, long, std::vector<paddle::framework::BlockDesc*, std::allocator<paddle::framework::BlockDesc*> >, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_>, std::hash<std::string>, std::equal_to<std::string>, std::allocator<std::pair<std::string const, boost::variant<boost::blank, int, float, std::string, std::vector<int, std::allocator<int> >, std::vector<float, std::allocator<float> >, std::vector<std::string, std::allocator<std::string> >, bool, std::vector<bool, std::allocator<bool> >, paddle::framework::BlockDesc*, long, std::vector<paddle::framework::BlockDesc*, std::allocator<paddle::framework::BlockDesc*> >, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> > > >&), paddle::framework::TypedAttrChecker<float> >::_M_invoke(std::_Any_data const&, std::unordered_map<std::string, boost::variant<boost::blank, int, float, std::string, std::vector<int, std::allocator<int> >, std::vector<float, std::allocator<float> >, std::vector<std::string, std::allocator<std::string> >, bool, std::vector<bool, std::allocator<bool> >, paddle::framework::BlockDesc*, long, std::vector<paddle::framework::BlockDesc*, std::allocator<paddle::framework::BlockDesc*> >, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_>, std::hash<std::string>, std::equal_to<std::string>, std::allocator<std::pair<std::string const, boost::variant<boost::blank, int, float, std::string, std::vector<int, std::allocator<int> >, std::vector<float, std::allocator<float> >, std::vector<std::string, std::allocator<std::string> >, bool, std::vector<bool, std::allocator<bool> >, paddle::framework::BlockDesc*, long, std::vector<paddle::framework::BlockDesc*, std::allocator<paddle::framework::BlockDesc*> >, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> > > >&) + 168
3       0x7f8406422940p paddle::framework::OpDesc::CheckAttrs() + 160
4       0x7f84063cfd85p void pybind11::cpp_function::initialize<pybind11::cpp_function::initialize<void, paddle::framework::OpDesc, , pybind11::name, pybind11::is_method, pybind11::sibling>(void (paddle::framework::OpDesc::*)(), pybind11::name const&, pybind11::is_method const&, pybind11::sibling const&)::{lambda(paddle::framework::OpDesc*)#1}, void, paddle::framework::OpDesc*, pybind11::name, pybind11::is_method, pybind11::sibling>(pybind11::cpp_function::initialize<void, paddle::framework::OpDesc, , pybind11::name, pybind11::is_method, pybind11::sibling>(void (paddle::framework::OpDesc::*)(), pybind11::name const&, pybind11::is_method const&, pybind11::sibling const&)::{lambda(paddle::framework::OpDesc*)#1}&&, void (*)(paddle::framework::OpDesc*), pybind11::name const&, pybind11::is_method const&, pybind11::sibling const&)::{lambda(pybind11::detail::function_call&)#3}::_FUN(pybind11::detail::function_call) + 117
5       0x7f84063ae30cp pybind11::cpp_function::dispatcher(_object*, _object*, _object*) + 2540
6       0x7f84708d5010p PyEval_EvalFrameEx + 16384
7       0x7f84708d6b80p PyEval_EvalCodeEx + 2128
8       0x7f8470867a5dp
9       0x7f84708443c3p PyObject_Call + 67
10      0x7f8470852a0dp
11      0x7f84708443c3p PyObject_Call + 67
12      0x7f84708968d7p
13      0x7f84708961efp
14      0x7f84708443c3p PyObject_Call + 67
15      0x7f84708d1ec8p PyEval_EvalFrameEx + 3768
16      0x7f84708d6b80p PyEval_EvalCodeEx + 2128
17      0x7f8470867a5dp
18      0x7f84708443c3p PyObject_Call + 67
19      0x7f84708d1ec8p PyEval_EvalFrameEx + 3768
20      0x7f84708d6b80p PyEval_EvalCodeEx + 2128
21      0x7f84708d508ep PyEval_EvalFrameEx + 16510
22      0x7f84708d6b80p PyEval_EvalCodeEx + 2128
23      0x7f84708d508ep PyEval_EvalFrameEx + 16510
24      0x7f84708d5132p PyEval_EvalFrameEx + 16674
25      0x7f84708d6b80p PyEval_EvalCodeEx + 2128
26      0x7f84708d508ep PyEval_EvalFrameEx + 16510
27      0x7f84708d5132p PyEval_EvalFrameEx + 16674
28      0x7f84708d6b80p PyEval_EvalCodeEx + 2128
29      0x7f84708d6c82p PyEval_EvalCode + 50
30      0x7f84708ef60fp
31      0x7f84708f067ep PyRun_FileExFlags + 126
32      0x7f84708f17d7p PyRun_SimpleFileExFlags + 199
33      0x7f8470901d9dp Py_Main + 3133
34      0x7f846fb47bd5p __libc_start_main + 245
35            0x4007c1p

**Comment by zzhzz** [comment]
改成1.0-fc试试？
