### ISSUE TITLE
请问Paddle源码编译如何打开调试选项？

### ISSUE THREAD

**Issue by zzhzz** [PaddlePaddle/Paddle#13959]
在训练过程中遇到一些问题，需要通过gdb来分析定位出错代码。请问Paddle编译会默认打开gcc -g选项吗？如果没有打开的话，怎样打开呢

**Comment by gavin1332** [comment]
具体是什么问题？是为了调试你自己贡献的代码吗？

**Comment by zzhzz** [comment]
@gavin1332 不是，是ParallelExectuor运行出了一些问题，想定位问题

**Comment by luotao1** [comment]
`cmake .. -DCMAKE_BUILD_TYPE=Debug`可以开启debug模式。
