### ISSUE TITLE
PaddlePaddle读文件

### ISSUE THREAD

**Issue by studyPaddle** [PaddlePaddle/Paddle#1396]
我发现PaddlePaddle每训练完一轮都会重新读一遍文件，重新调用DataProvider中的process函数，重新预处理一边数据，特别耗时，请问有没有办法让他在整个训练过程中只预处理一遍数据

**Comment by helinwang** [comment]
因为如果要不重新调用一遍的话，内存里不一定能够存下process之后的数据。
所以要是process耗时，可以考虑把文件处理一遍，存起来。以后就直接用处理好的数据。

**Comment by Z-TAO** [comment]
@studyPaddle http://www.paddlepaddle.org/doc/ui/data_provider/pydataprovider2.html#cache
你可以设置CacheType.CACHE_PASS_IN_MEM , which means the first pass reads data by the user implemented python module, and the rest passes will directly read data from memory.
但是担心内存爆掉的问题。

**Comment by studyPaddle** [comment]
就是设置的CacheType.CACHE_PASS_IN_MEM，依然前几轮会重新读，后面几轮就不读了
