### ISSUE TITLE
训练过程中报：x_mat_dims[1]:160 != y_mat_dims[0]:128 in mul_op.cc

### ISSUE THREAD

**Issue by yanyunxinyu** [PaddlePaddle/Paddle#13963]
Traceback (most recent call last):
  File "train.py", line 289, in <module>
    main(USE_GPU)
  File "train.py", line 286, in main
    params_dirname=params_dirname)
  File "train.py", line 268, in infer
    return_numpy=False)
  File "/usr/local/lib/python2.7/dist-packages/paddle/fluid/inferencer.py", line 104, in infer
    return_numpy=return_numpy)
  File "/usr/local/lib/python2.7/dist-packages/paddle/fluid/executor.py", line 470, in run
    self.executor.run(program.desc, scope, 0, True, True)
paddle.fluid.core.EnforceNotMet: Enforce failed. Expected x_mat_dims[1] == y_mat_dims[0], but received x_mat_dims[1]:160 != y_mat_dims[0]:128.
First matrix's width must be equal with second matrix's height. at [/paddle/paddle/fluid/operators/mul_op.cc:59]
PaddlePaddle Call Stacks: 
0       0x7fb3a6d94d86p paddle::platform::EnforceNotMet::EnforceNotMet(std::__exception_ptr::exception_ptr, char const*, int) + 486
1       0x7fb3a71f1be9p paddle::operators::MulOp::InferShape(paddle::framework::InferShapeContext*) const + 2569
2       0x7fb3a7767a69p paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&) const + 73
3       0x7fb3a776400fp paddle::framework::OperatorBase::Run(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&) + 255
4       0x7fb3a6e529d9p paddle::framework::Executor::RunPreparedContext(paddle::framework::ExecutorPrepareContext*, paddle::framework::Scope*, bool, bool, bool) + 393
5       0x7fb3a6e535d0p paddle::framework::Executor::Run(paddle::framework::ProgramDesc const&, paddle::framework::Scope*, int, bool, bool) + 128
6       0x7fb3a6d7c65dp
7       0x7fb3a6dc7034p pybind11::cpp_function::dispatcher(_object*, _object*, _object*) + 2596
8             0x4c37edp PyEval_EvalFrameEx + 31165
9             0x4b9ab6p PyEval_EvalCodeEx + 774
10            0x4c16e7p PyEval_EvalFrameEx + 22711
11            0x4b9ab6p PyEval_EvalCodeEx + 774
12            0x4c16e7p PyEval_EvalFrameEx + 22711
13            0x4b9ab6p PyEval_EvalCodeEx + 774
14            0x4c1e6fp PyEval_EvalFrameEx + 24639
15            0x4b9ab6p PyEval_EvalCodeEx + 774
16            0x4c1e6fp PyEval_EvalFrameEx + 24639
17            0x4b9ab6p PyEval_EvalCodeEx + 774
18            0x4eb30fp
19            0x4e5422p PyRun_FileExFlags + 130
20            0x4e3cd6p PyRun_SimpleFileExFlags + 390
21            0x493ae2p Py_Main + 1554
22      0x7fb3c4c46830p __libc_start_main + 240
23            0x4933e9p _start + 41

**Comment by qingqing01** [comment]
```
paddle.fluid.core.EnforceNotMet: Enforce failed. Expected x_mat_dims[1] == y_mat_dims[0], but received x_mat_dims[1]:160 != y_mat_dims[0]:128.
```
看这个是mul(或fc)输入shape不一致，可以分析下mul/fc相关输入shape是否正确。

**Comment by fengshuting** [comment]
(-1L, 32L)
(-1L, 16L)
(-1L, 16L)
(-1L, 32L)
(-1L, 32L)
(-1L, 32L)
concat:
(-1L, 200L)
code：
CLASS_DIM = 2
EMB_DIM = 128
HID_DIM = 200
def fc_net(case, class_dim, hid_dim):
    # 第一个全连接层，激活函数为ReLU
    hidden = fluid.layers.fc(input=case, size=hid_dim, act='relu')
    # 第二个全连接层，激活函数为ReLU
    hidden = fluid.layers.fc(input=hidden, size=hid_dim, act='relu')
    prediction = fluid.layers.fc(input=hidden, size=class_dim, act='softmax')
    return prediction


感觉shape没有什么问题，没有设置过160这样的参数呢

**Comment by qingqing01** [comment]
在程序运行时可以通过fluid.layers.Print()来辅助定位，在可能出现128的fc附近，打印运行时的shape信息，比如：

```
fluid.layers.Print(case)
hidden = fluid.layers.fc(input=case, size=hid_dim, act='relu')
```

**Comment by lucywsq** [comment]
您好，此问题在一个月内未更新，将于今天内关闭~如有问题您可随时开启，感谢您对PaddlePaddle的支持！
