### ISSUE TITLE
ParallelExecutor 如何回收资源？

### ISSUE THREAD

**Issue by mzchtx** [PaddlePaddle/Paddle#13970]
Executor 中有 close() 方法可以回收资源，而 ParallelExecutor 中并没有，ParallelExecutor 的资源如何回收？

**Comment by lucywsq** [comment]
您好，请您将遇到的问题的报错代码贴出，以便快速定位问题~

**Comment by lucywsq** [comment]
您好，此issue在近一个月内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题，我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持!

**Comment by chengduoZH** [comment]
@mzchtx Executor中有 close() 是用于分布式训练中释放PServers资源的操作，ParallelExecutor目前不需这种操作
