### ISSUE TITLE
使用国内的Pypi源没办法pip安装PaddlePaddle

### ISSUE THREAD

**Issue by JiabinYang** [PaddlePaddle/Paddle#13972]
这是由于国内的Pypi源没有和Pypi官方的源同步造成的，这种情况下可以从[Pypi官方源](https://pypi.org/user/paddle-dev/)下载对应whl包，然后pip install [下载的whl包所在的路径]安装

**Comment by yeyupiaoling** [comment]
我也奇怪，为什么不同步呢？这样很麻烦，百度云服务器使用的是国内镜像源，所以安装比较麻烦。没有办法同步吗？

**Comment by yeyupiaoling** [comment]
目前已经知道阿里镜像源已经更新了。
