### ISSUE TITLE
paddle V1 如何获得数据的数值

### ISSUE THREAD

**Issue by Emma-Ding** [PaddlePaddle/Paddle#13980]
想要获得的label具体数值，如何获得? 如下，通过代码
https://github.com/PaddlePaddle/Paddle/blob/e26f51ce74e998c4119fc2c3145aa7c1224c2170/python/paddle/trainer_config_helpers/layers.py
找到了可以获得size信息，想问怎么获得具体的数值?
![2018-10-18 8 23 16](https://user-images.githubusercontent.com/22070158/47153996-afad2700-d313-11e8-86e3-ebfb1e34bbd3.png)

**Comment by qingqing01** [comment]
看您使用的Paddle v2 API， 因为数据是从Python端输入，可以在Python的reader里打印label具体的值，另外，推荐使用Paddle Fluid.
