### ISSUE TITLE
Remove unnecessary null pointer checks

### ISSUE THREAD

**Issue by elfring** [PaddlePaddle/Paddle#14]
[An extra null pointer check is not needed in functions](https://isocpp.org/wiki/faq/freestore-mgmt#delete-handles-null) like the following.
- [ParameterOptimizer](https://github.com/baidu/Paddle/blob/4fe7d833cf0dd952bfa8af8d5d7772bbcd552c58/paddle/api/ParameterOptimizer.cpp#L55)
- [StorageEngine](https://github.com/baidu/Paddle/blob/4fe7d833cf0dd952bfa8af8d5d7772bbcd552c58/paddle/math/Storage.cpp#L34)
- [Vector](https://github.com/baidu/Paddle/blob/4fe7d833cf0dd952bfa8af8d5d7772bbcd552c58/paddle/api/Vector.cpp#L160)

**Comment by reyoung** [comment]
OK， we will check and fix them
