### ISSUE TITLE
sequence_argmax op needed

### ISSUE THREAD

**Issue by LihangLiu** [PaddlePaddle/Paddle#14004]
普通的tensor可以通过layers.argmax来得到最大值的下标，但是找了下文档，貌似对于lod tensor并没有类似于sequence_argmax的操作？

**Comment by luotao1** [comment]
参考：http://paddlepaddle.org/documentation/api/zh/1.0/layers.html#sequence-pool 
`fluid.layers.sequence_pool(input=x, pool_type='max')`

**Comment by luotao1** [comment]
参考 http://paddlepaddle.org/documentation/api/zh/1.0/layers.html#sequence-pool
`fluid.layers.sequence_pool(input=x, pool_type='max')`

**Comment by LihangLiu** [comment]
sequence_pool(input=x, pool_type='max') 得到的是最大的值，但是我想得到的是最大值的**下标**。也就是想得到argmax，而不是max。

**Comment by luotao1** [comment]
@kagome112 请看下这个新需求

**Comment by lucywsq** [comment]
您好，此建议已被记录，衷心感谢您对PaddlePaddle的贡献~我们将努力优化，提供更好的使用体验

**Comment by HuangLK** [comment]
2020年了
