### ISSUE TITLE
运行单测报错

### ISSUE THREAD

**Issue by zzhzz** [PaddlePaddle/Paddle#14001]
Test project /mnt/paddle/Paddle/build
    Start 369: test_mul_op
1/1 Test #369: test_mul_op ......................***Exception: Other  1.27 sec

0% tests passed, 1 tests failed out of 1

Total Test time (real) =   1.31 sec

The following tests FAILED:
        369 - test_mul_op (OTHER_FAULT)
Errors while running CTest

**Comment by zzhzz** [comment]
UpdateCTestConfiguration  from :/mnt/paddle/Paddle/build/DartConfiguration.tcl
UpdateCTestConfiguration  from :/mnt/paddle/Paddle/build/DartConfiguration.tcl
Test project /mnt/paddle/Paddle/build
Constructing a list of tests
Done constructing a list of tests
Checking test dependency graph...
Checking test dependency graph end
test 369
    Start 369: test_mul_op

369: Test command: /usr/bin/env "PYTHONPATH=/mnt/paddle/Paddle/build/python" "/opt/python/cp27-cp27mu/bin/python2.7" "/mnt/paddle/Paddle/tools/test_runner.py" "test_mul_op"
369: Test timeout computed to be: 9.99988e+06
369: python2.7: /mnt/paddle/Paddle/paddle/fluid/string/tinyformat/tinyformat.h:563: const char* paddle::string::tinyformat::detail::streamStateFromFormat(std::ostream&, bool&, int&, const char*, const paddle::string::tinyformat::detail::FormatArg*, int&, int): Assertion `0 && "tinyformat: Not enough conversion specifiers in format string"' failed.
1/1 Test #369: test_mul_op ......................***Exception: Other  1.59 sec

0% tests passed, 1 tests failed out of 1

Total Test time (real) =   1.63 sec

The following tests FAILED:
        369 - test_mul_op (OTHER_FAULT)
Errors while running CTest

**Comment by Yancey0623** [comment]
请问paddle版本以及编译和运行的环境是什么呢？另外可以把错误栈以及运行日志打出来看一下：

``` python
GLOG_v=6 GLOG_logtostderr=1 \
PYTHONPATH=/mnt/paddle/Paddle/build/python \
/opt/python/cp27-cp27mu/bin/python2.7 /mnt/paddle/Paddle/build/python/paddle/fluid/tests/unittests/test_mul_op.py
```

**Comment by zzhzz** [comment]
@Yancey1989 paddle是1.0.1版本，运行环境是centos 6.9

**Comment by zzhzz** [comment]
@Yancey1989 运行你的命令的结果
``` text
python2.7: /mnt/paddle/Paddle/paddle/fluid/string/tinyformat/tinyformat.h:563: const char* paddle::string::tinyformat::detail::streamStateFromFormat(std::ostream&, bool&, int&, const char*, const paddle::string::tinyformat::detail::FormatArg*, int&, int): Assertion `0 && "tinyformat: Not enough conversion specifiers in format string"' failed.
```
