### ISSUE TITLE
softmax_with_cross_entropy soft_label=False, loss=10^20

### ISSUE THREAD

**Issue by phlrain** [PaddlePaddle/Paddle#14006]
我写一个语言模型的网络，
当 softmax_with_cross_entropy，soft_label=False的时候，有些情况下 loss 等于10^20，导致训练出现inf
如果我手动把label做成one hot的形式，同样用这个函数，soft_label=True的情况下，loss就会表现得正常

**Comment by chengduoZH** [comment]
This PR https://github.com/PaddlePaddle/Paddle/pull/14087 has fixed it.
