### ISSUE TITLE
How do you measure the ResNet50 inference accuracy in C-API?

### ISSUE THREAD

**Issue by wojtuss** [PaddlePaddle/Paddle#14016]
The `test_anlyzer_resnet50` test uses fake data and a model without accuracy layer. When developing fuse passes we need to verify the accuracy. How do you measure the accuracy of the ResNet50 model?

**Comment by luotao1** [comment]
We compare the inference result by
https://github.com/PaddlePaddle/Paddle/blob/5d6783f8ca9ee8205057d75b659e25f3b09a5281/paddle/fluid/inference/tests/api/analyzer_resnet50_tester.cc#L101-L104

**Comment by wojtuss** [comment]
@luotao1 , thank you!
