### ISSUE TITLE
fluid gpu 安装问题 undefined symbol: mkldnn_softmax_backward_desc_init

### ISSUE THREAD

**Issue by shiyazhou121** [PaddlePaddle/Paddle#14010]
在安装fluid 1.0.1时报错。paddlepaddle_gpu-1.0.1.post85-cp27-cp27mu-manylinux1_x86_64.whl
![image](https://user-images.githubusercontent.com/15082798/47278000-fe024480-d5f7-11e8-8874-702a212b61ed.png)
安装fluid 0.15也报错。paddlepaddle_gpu-0.15.0.post85-cp27-cp27mu-manylinux1_x86_64.whl
![image](https://user-images.githubusercontent.com/15082798/47278010-12464180-d5f8-11e8-8412-13f04f42b5ac.png)
安装fluid 0.14就没问题。paddlepaddle_gpu-0.14.0.post85-cp27-cp27mu-manylinux1_x86_64.whl

请问，为啥0.14没事，其他高版本就会报mkldnn的错误？0.14与其他版本之间有什么不一样的？

**Comment by typhoonzero** [comment]
可以先看下`core.so`是否能正确链接到mkl，在我的环境下：

```bash
ldd /opt/python/cp27-cp27mu/lib/python2.7/site-packages/paddle/fluid/core.so
	linux-vdso.so.1 =>  (0x00007ffdb9f30000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f102d723000)
	libpython2.7.so.1.0 => /opt/python/cp27-cp27mu/lib/libpython2.7.so.1.0 (0x00007f102d315000)
	librt.so.1 => /lib64/librt.so.1 (0x00007f102d10d000)
	libiomp5.so => /opt/python/cp27-cp27mu/lib/python2.7/site-packages/paddle/fluid/../libs/libiomp5.so (0x00007f102cd69000)
	libmkldnn.so.0 => /opt/python/cp27-cp27mu/lib/python2.7/site-packages/paddle/fluid/../libs/libmkldnn.so.0 (0x00007f102c52a000)
	libdl.so.2 => /lib64/libdl.so.2 (0x00007f102c326000)
	libstdc++.so.6 => /usr/lib64/libstdc++.so.6 (0x00007f102c020000)
	libm.so.6 => /lib64/libm.so.6 (0x00007f102bd9b000)
	libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007f102bb85000)
	libc.so.6 => /lib64/libc.so.6 (0x00007f102b7f1000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f10380cd000)
	libutil.so.1 => /lib64/libutil.so.1 (0x00007f102b5ed000)
	libmklml_intel.so => /opt/python/cp27-cp27mu/lib/python2.7/site-packages/paddle/fluid/../libs/libmklml_intel.so (0x00007f102251c000)
```

**Comment by shiyazhou121** [comment]
@typhoonzero 请问，怎么确定mkl是正确的。。
![image](https://user-images.githubusercontent.com/15082798/47286608-02435780-d622-11e8-90be-f3d45a7a0e5f.png)

**Comment by typhoonzero** [comment]
是否安装了多个版本的paddle，是否单独安装过mkl，看下`paddle安装路径/libs`下是否也存在mkl.so？

**Comment by lucywsq** [comment]
您好，此issue在近一个月内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题，我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持!
