### ISSUE TITLE
implement more layers in v2 API

### ISSUE THREAD

**Issue by luotao1** [PaddlePaddle/Paddle#1402]
- [ ]   "full_matrix_projection",
- [ ]    "identity_projection",
- [ ]    "dotmul_projection",
- [ ]    "dotmul_operator",
- [ ]    "repeat_layer",
- [ ]    "table_projection",
- [ ]    "mixed_layer",
- [x]    "data_layer",
- [ ]    "embedding_layer",
- [x]    "fc_layer",
- [ ]    "grumemory",
- [ ]    "pooling_layer",
- [ ]    "lstmemory",
- [ ]    "last_seq",
- [ ]    "first_seq",
- [ ]    "cos_sim",
- [ ]    "hsigmoid",
- [ ]    "conv_projection",
- [x]    "regression_cost",
- [x]    'classification_cost',
- [ ]    'img_conv_layer',
- [ ]    'img_pool_layer',
- [ ]    'batch_norm_layer',
- [ ]    'img_cmrnorm_layer',
- [ ]    'addto_layer',
- [ ]    'concat_layer',
- [ ]    'seq_concat_layer',
- [ ]    'lstm_step_layer',
- [ ]    'recurrent_group',
- [ ]    'memory',
- [ ]    'StaticInput',
- [ ]    'expand_layer',
- [ ]    'scaling_layer',
- [ ]    'scaling_projection',
- [ ]    'power_layer',
- [ ]    'interpolation_layer',
- [ ]    'bilinear_interp_layer',
- [ ]    'trans_layer',
- [ ]    'rotate_layer',
- [ ]    'sum_to_one_norm_layer',
- [ ]    'get_output_layer',
- [ ]    'context_projection',
- [ ]    'beam_search',
- [x]    'maxid_layer',
- [ ]    'GeneratedInput',
- [ ]    'SubsequenceInput',
- [ ]    'gru_step_layer',
- [ ]    'recurrent_layer',
- [ ]    'BaseGeneratedInput',
- [ ]    'conv_operator',
- [ ]    'conv_shift_layer',
- [ ]    'tensor_layer',
- [ ]    'selective_fc_layer',
- [ ]    'sampling_id_layer',
- [ ]    'slope_intercept_layer',
- [ ]    'trans_full_matrix_projection',
- [ ]    'linear_comb_layer',
- [ ]    'convex_comb_layer',
- [ ]    'ctc_layer',
- [ ]    'warp_ctc_layer',
- [ ]    'crf_layer',
- [ ]    'crf_decoding_layer',
- [ ]    'nce_layer',
- [x]    'cross_entropy_with_selfnorm',
- [x]    'cross_entropy',
- [x]    'multi_binary_label_cross_entropy',
- [x]    'sum_cost',
- [x]    'rank_cost',
- [x]    'lambda_cost',
- [x]    'huber_cost',
- [ ]    'block_expand_layer',
- [ ]    'maxout_layer',
- [ ]    'out_prod_layer',
- [ ]    'print_layer',
- [ ]    'priorbox_layer',
- [ ]    'spp_layer',
- [ ]    'pad_layer',

**Comment by reyoung** [comment]
@luotao1 @jacquesqiao The most of them could be implemented well by `__convert_to_v2__` function. But the layer group related layers (`recurrent_group`, etc)are difficult to implement.  Please notice that, and figure how to implement it asap.

**Comment by jacquesqiao** [comment]
带xx_layer的一般都可以直接转。
可能有风险的layer。

- [ ]   "recurrent_group",

**Comment by jacquesqiao** [comment]
#1452 implement more layers in v2  @luotao1 
#1453 convert mixed layer, projection and operator @qingqing01 
#1441 support rnn @jacquesqiao
#1400 add Topology to handle actions on network @jacquesqiao
