### ISSUE TITLE
GPU下，预测阶段出错，Check failed: cudaSuccess == err (0 vs. 9)

### ISSUE THREAD

**Issue by 930083287** [PaddlePaddle/Paddle#14039]
训练时，类别分为3类，图片尺寸为256*256＊2；
预测阶段，图片尺寸为128的话，不会报错，但是仅仅分为一类；当图片尺寸为256时，出错。
F1024 09:13:15.036841 100191 hl_gpu_matrix_kernel.cuh:181] Check failed: cudaSuccess == err (0 vs. 9) [hl_gpu_apply_unary_op failed] CUDA error: invalid configuration argument
*** Check failure stack trace: ***
    @     0x7f6922255bcd  google::LogMessage::Fail()
    @     0x7f692225967c  google::LogMessage::SendToLog()
    @     0x7f69222556f3  google::LogMessage::Flush()
    @     0x7f692225ab8e  google::LogMessageFatal::~LogMessageFatal()
    @     0x7f69220cc44b  hl_gpu_apply_unary_op<>()
    @     0x7f69220cc7bd  paddle::BaseMatrixT<>::applyUnary<>()
    @     0x7f69220cca03  paddle::BaseMatrixT<>::zero()
    @     0x7f692205a645  paddle::GpuMatrix::zeroMem()
    @     0x7f6921f3a4bb  paddle::Layer::resetSpecifyOutput()
    @     0x7f6921f3a6a4  paddle::Layer::resetOutput()
    @     0x7f6921e77859  paddle::CudnnConvBaseLayer::forward()
    @     0x7f6921f5ba4d  paddle::NeuralNetwork::forward()
    @     0x7f6921dd098d  _wrap_GradientMachine_forward
    @     0x7f697575d990  PyEval_EvalFrameEx
    @     0x7f69757604e9  PyEval_EvalCodeEx
    @     0x7f697575d482  PyEval_EvalFrameEx
    @     0x7f69757604e9  PyEval_EvalCodeEx
    @     0x7f697575d482  PyEval_EvalFrameEx
    @     0x7f69756de99b  gen_send_ex.isra.1
    @     0x7f697575b456  PyEval_EvalFrameEx
    @     0x7f69756de99b  gen_send_ex.isra.1
    @     0x7f697575b456  PyEval_EvalFrameEx
    @     0x7f69757604e9  PyEval_EvalCodeEx
    @     0x7f697575d482  PyEval_EvalFrameEx
    @     0x7f69757604e9  PyEval_EvalCodeEx
    @     0x7f697575d482  PyEval_EvalFrameEx
    @     0x7f69757604e9  PyEval_EvalCodeEx
    @     0x7f697575d482  PyEval_EvalFrameEx
    @     0x7f69757604e9  PyEval_EvalCodeEx
    @     0x7f697576070a  PyEval_EvalCode
    @     0x7f697577993d  run_mod
    @     0x7f697577aab8  PyRun_FileExFlags
Aborted (core dumped)

**Comment by kuke** [comment]
See https://github.com/PaddlePaddle/Paddle/issues/4439

**Comment by kuke** [comment]
Closed due to inactivity
