### ISSUE TITLE
Inference model, cudnn 7 is ok, but cudnn 6 doesn't work

### ISSUE THREAD

**Issue by TheodoreG** [PaddlePaddle/Paddle#14035]
I saved a inference model using resnet50 from paddle model. But when I run following inference code:
```
model_path = "./resnet50_infer_mode   
place = fluid.CUDAPlace(0)
exe = fluid.Executor(place)
img_np_array = np.random.random(size=(1, 3, 224, 224)).astype('float32')
[inference_program, feed_target_names, fetch_targets] = fluid.io.load_inference_model(model_path, exe)
results = exe.run(inference_program,feed={feed_target_names[0]: img_np_array},fetch_list=fetch_targets)
print(results)
```
but I find that when LD_LIBRARY_PATH include only cudnn v6 library, it shows 
```
*** Aborted at 1540288996 (unix time) try "date -d @1540288996" if you are using GNU date ***
PC: @                0x0 (unknown)
*** SIGSEGV (@0x0) received by PID 1274 (TID 0x7fcb0da1c700) from PID 0; stack trace: ***
    @     0x7fcb0d1eb160 (unknown)
    @                0x0 (unknown)
Segmentation fault
```
When LD_LIBRARY_PATH  include cudnn v7, it acts normal.
Could anyone explain that to me?

**Comment by chengduoZH** [comment]
Can you display the version of the paddle that you use?

**Comment by TheodoreG** [comment]
> Can you display the version of the paddle that you use?

paddlepaddle-gpu                   1.0.1.post97

**Comment by chengduoZH** [comment]
@TheodoreG Do you have resolved this question?

**Comment by TheodoreG** [comment]
Now I use  paddlepaddle/paddle:1.1.0-gpu-cuda9.0-cudnn7, and it seems this bug doesn't happen any more. Thanks a lot.

**Comment by chengduoZH** [comment]
Sorry, I can't reproduce this error. It is a strange error, because `infer_mode` doesn't store any cudnn info about the version, so there should be no error.

**Comment by chengduoZH** [comment]
Close this PR, because of it is inactive for a long time.
