### ISSUE TITLE
meets grpc error:OS Error

### ISSUE THREAD

**Issue by LoveGarden** [PaddlePaddle/Paddle#14030]
mpi上fluid 0.15在训练过程报错如下
Tue Oct 23 11:15:31 2018[1,132]<stdout>:INFO[2018-10-23 11:15:31][train.py][441] -  pass_id=0 batch_id=140 cost=1009.5504 auc=[0.64529329] py_reader.queue.size: 100 acc=0.9277344 read_data_time=9.53674316406e-07 train_batch_time=10.4956641197 sample_per_second=390.256390951
Tue Oct 23 11:18:40 2018[1,128]<stdout>:F1023 11:18:40.494853  9754 grpc_client.cc:295] Get name:[fc_0.w_0.block2], ep:[10.182.9.15:8000] meets grpc error:OS Error
Tue Oct 23 11:18:40 2018[1,128]<stdout>:*** Check failure stack trace: ***
Tue Oct 23 11:18:40 2018[1,128]<stdout>:    @     0x7f6fff50cebd  google::LogMessage::Fail()
Tue Oct 23 11:18:40 2018[1,128]<stdout>:    @     0x7f6fff51096c  google::LogMessage::SendToLog()
Tue Oct 23 11:18:40 2018[1,128]<stdout>:    @     0x7f6fff50c9e3  google::LogMessage::Flush()
Tue Oct 23 11:18:40 2018[1,128]<stdout>:    @     0x7f6fff511e7e  google::LogMessageFatal::~LogMessageFatal()
Tue Oct 23 11:18:40 2018[1,128]<stdout>:    @     0x7f6fffd6e1d0  paddle::operators::distributed::GRPCClient::Proceed()
Tue Oct 23 11:18:40 2018[1,128]<stdout>:    @     0x7f700a3978a0  execute_native_thread_routine
Tue Oct 23 11:18:40 2018[1,128]<stdout>:    @     0x7f70a7a1f1c3  start_thread
Tue Oct 23 11:18:40 2018[1,128]<stdout>:    @     0x7f70a704712d  __clone
Tue Oct 23 11:18:40 2018[1,128]<stdout>:    @              (nil)  (unknown)
Tue Oct 23 11:18:44 2018[1,128]<stdout>:.//paddle/start_trainer.sh: line 89: 49394 Aborted                 /home/disk1/normandy/maybach/app-user-20181023101155-15287/workspace/python27-gcc482//bin/python -u mpi_train.py --use_parallel_exe 1 --batch_size 4096 --cpu_num=1 --train_data_dir train_data --test_data_dir test_data
Tue Oct 23 11:18:44 2018[1,128]<stderr>:+ trainer_ret=134
Tue Oct 23 11:18:44 2018[1,128]<stderr>:+ popd
Tue Oct 23 11:18:44 2018[1,128]<stdout>:/home/disk1/nor

**Comment by jacquesqiao** [comment]
1. 建议先用少量节点测试看能否复现
2. 看能不能拿到core文件，方便我们分析。

**Comment by typhoonzero** [comment]
补充：用户pserver的error 日志：

```
7843 Tue Oct 23 12:52:29 2018[1,14]<stdout>:*** Aborted at 1540270349 (unix time) try "date -d @1540270349" if you are using GNU date ***
7844 Tue Oct 23 12:52:29 2018[1,132]<stdout>:*** Error in `/home/disk1/normandy/maybach/app-user-20181023101155-15287/workspace/python27-gcc482/bi     n/python': double free or corruption (!prev): 0x0000000004920a10 ***
7845 Tue Oct 23 12:52:29 2018[1,56]<stdout>:*** Error in `/home/disk1/normandy/maybach/app-user-20181023101155-15287/workspace/python27-gcc482/bin     /python': double free or corruption (!prev): 0x00000000046abba0 ***
7846 Tue Oct 23 12:52:30 2018[1,24]<stdout>:*** Error in `/home/disk1/normandy/maybach/app-user-20181023101155-15287/workspace/python27-gcc482/bin     /python': double free or corruption (!prev): 0x0000000003ebc9c0 ***
7847 Tue Oct 23 12:52:30 2018[1,24]<stdout>:*** Aborted at 1540270350 (unix time) try "date -d @1540270350" if you are using GNU date ***
7848 Tue Oct 23 12:52:30 2018[1,97]<stdout>:*** Aborted at 1540270350 (unix time) try "date -d @1540270350" if you are using GNU date ***
7849 Tue Oct 23 12:52:30 2018[1,0]<stdout>:*** Error in `/home/disk1/normandy/maybach/app-user-20181023101155-15287/workspace/python27-gcc482/bin/     python': double free or corruption (!prev): 0x000000000526b910 ***
7850 Tue Oct 23 12:52:30 2018[1,0]<stdout>:*** Error in `/home/disk1/normandy/maybach/app-user-20181023101155-15287/workspace/python27-gcc482/bin/     python': double free or corruption (!prev): 0x000000000523e770 ***
7851 Tue Oct 23 12:52:30 2018[1,0]<stdout>:*** Aborted at 1540270350 (unix time) try "date -d @1540270350" if you are using GNU date ***
7852 Tue Oct 23 12:52:30 2018[1,0]<stdout>:*** Error in `/home/disk1/normandy/maybach/app-user-20181023101155-15287/workspace/python27-gcc482/bin/     python': double free or corruption (!prev): 0x0000000004d62d90 ***
7853 Tue Oct 23 12:52:30 2018[1,0]<stdout>:*** Error in `/home/disk1/normandy/maybach/app-user-20181023101155-15287/workspace/python27-gcc482/bin/     python': double free or corruption (fasttop): 0x00000000048b06e0 ***
7854 mpirun: killing job...
```

**Comment by LoveGarden** [comment]
> 1. 建议先用少量节点测试看能否复现
在10个结点上跑小量数据是能跑成功的
> 2. 看能不能拿到core文件，方便我们分析。
mpi结点上core文件暂时还不知道获取方法

**Comment by chengduoZH** [comment]
@LoveGarden 请问现在问题解决了吗
