### ISSUE TITLE
AVX512f 判断错误

### ISSUE THREAD

**Issue by tensor-tang** [PaddlePaddle/Paddle#14040]
https://github.com/PaddlePaddle/Paddle/blob/8837669782c73742e0eaba769342f76fa81f3160/cmake/simd.cmake#L90-L94

这段验证在5117的机器上并不能通过，应该是需要avx512的其他指令支持的。

所以在CI上目前没有一台机器验证了avx512的正确性。

查了下这个机器是5117的支持avx512f，如下的log是gcc54编译，但是判断的avx512f flag是failed。
http://ci.paddlepaddle.org/viewLog.html?buildId=24130&buildTypeId=Paddle_PrCi&tab=buildLog

http://ci.paddlepaddle.org/viewLog.html?buildId=24130&buildTypeId=Paddle_PrCi&tab=buildLog

http://ci.paddlepaddle.org/viewLog.html?tab=buildLog&logTab=tree&filter=debug&expand=all&buildId=24130&_focus=519

**Comment by tensor-tang** [comment]
现在改为正确的avx512判断之后(#14041)，发现有很有单元测试精度是对不齐的，具体可以查看 #14041 的[log1](http://ci.paddlepaddle.org/viewLog.html?buildId=24340&buildTypeId=Paddle_PrCi&tab=buildLog)，[log2](http://ci.paddlepaddle.org/viewLog.html?buildId=24220&buildTypeId=Paddle_PrCi&tab=buildLog) 

其中包括如下等：
```
test_analyzer_resnet50
test_activation_mkldnn_op
test_hsigmoid_op
...
test_adadelta_op
```

**Comment by tensor-tang** [comment]
另外一个问题，[intrinsic guide](https://software.intel.com/sites/landingpage/IntrinsicsGuide/#text=_mm512_undefined_epi32&expand=5949)上写的他是AVX512F的指令为什么在5117和6148上check是失败的？
```
Synopsis
__m512i _mm512_undefined_epi32 ()
#include <immintrin.h>
CPUID Flags: AVX512F
Description
Return vector of type __m512i with undefined elements.
```

**Comment by yihuaxu** [comment]
上次修改好了，还没有合进去。 下面是改好的链接。https://github.com/PaddlePaddle/Paddle/commit/d8502b36cb4f12a84bd04975ae8cbeecdda17322
intrinsic function不是严格意义上的汇编指令，_mm512_undefined_epi32的具体实现没用到AVX512F的指令。

**Comment by tensor-tang** [comment]
你修改的还是flag的问题，这个已经在 #14041 解决了，目前问题是正确 enable AVX512之后单测不过的问题。
