### ISSUE TITLE
关于sparse update和test问题

### ISSUE THREAD

**Issue by fishfly3384** [PaddlePaddle/Paddle#1404]
有两个问题有些不解：
1. 看之前的issue提到sparse update和test不能共存。将define_by_data_sources2()中的test_list设置成none即可。现在有没有更好的解决方案？

2. 如果train和test分离，那如何提交一个只有test的任务给集群？ 比如加载几个指定PASS的model，在测试集上做evaluation？

**Comment by Yancey1989** [comment]
Close this inactivate issue, please reopen it for free.
