### ISSUE TITLE
找不到对应的文档

### ISSUE THREAD

**Issue by gongweibao** [PaddlePaddle/Paddle#14058]
```
save_checkpint load_checkpoint
```

**Comment by shanyi15** [comment]
hi 这两个api，由于是high-level-api，放在了contrib目录下，目前应该是还没有正式暴露给用户（除了在book的前几章有出现过），需要暴露给用户吗？
http://paddlepaddle.org/documentation/docs/zh/1.0/api_guides/high_low_level_api.html
