### ISSUE TITLE
在v100的机器上，用docker编译成功，但执行出现“invalid device function”

### ISSUE THREAD

**Issue by procr** [PaddlePaddle/Paddle#14077]
Thank you for contributing to PaddlePaddle. Submitting an issue is a great help for us.
Both Chinese and English issues are welcome.

It's hard to solve a problem when important details are missing.
Before submitting the issue, look over the following criteria before handing your request in.

- [ ] Was there a similar issue submitted or resolved before ? You could search issue in the github.
- [ ] Did you retrieve your issue from widespread search engines ?
- [ ] Is my description of the issue clear enough to reproduce this problem?
   * If some errors occurred, we need details about `how do you run your code?`, `what system do you use?`, `Are you using GPU or not?`, etc.
   * If you use an recording [asciinema](https://asciinema.org/) to show what you are doing to make it happen, that's awesome! We could help you solve the problem more quickly.
- [ ] Is my description of the issue use the github markdown correctly?
   * Please use the proper markdown syntaxes for styling all forms of writing, e.g, source code, error information, etc.
   * Check out [this page](https://guides.github.com/features/mastering-markdown/) to find out much more about markdown.

**Comment by procr** [comment]
使用的docker镜像是：
hub.baidubce.com/paddlepaddle/paddle：latest-dev

**Comment by procr** [comment]
跑resnet50，出现

λ 6dbb0ffcf63b /paddle {master} python resnet50.py
----------- resnet Configuration Arguments -----------
batch_size: 32
data_format: NCHW
data_set: flowers
device: GPU
infer_only: False
iterations: 80
model: resnet_imagenet
pass_num: 100
skip_batch_num: 5
use_cprof: False
use_fake_data: False
use_nvprof: False
with_test: False
------------------------------------------------
Traceback (most recent call last):
  File "resnet50.py", line 299, in <module>
    run_benchmark(model_map[args.model], args)
  File "resnet50.py", line 228, in run_benchmark
    exe.run(fluid.default_startup_program())
  File "/usr/local/lib/python2.7/dist-packages/paddle/fluid/executor.py", line 340, in run
    self.executor.run(program.desc, scope, 0, True, True)
RuntimeError: function_attributes(): after cudaFuncGetAttributes: invalid device function

**Comment by procr** [comment]
安装的产出是：
pip install Paddle/build/python/dist/paddlepaddle_gpu-0.13.0-cp27-cp27mu-linux_x86_64.whl

**Comment by gongweibao** [comment]
这个是cuda驱动没有绑定到docker中。

**Comment by gongweibao** [comment]
https://github.com/gongweibao/paddlepaddleutils/tree/develop/build#%E5%90%AF%E5%8A%A8%E9%95%9C%E5%83%8F

**Comment by lucywsq** [comment]
您好，此issue在近三周内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题，我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持!
