### ISSUE TITLE
Request for MobileNet model and weights for image classification

### ISSUE THREAD

**Issue by wojtuss** [PaddlePaddle/Paddle#14074]
Could you please provide us with a trained model and weights for MobileNet (image classification)? That would help us proceed faster with model optimizations.

**Comment by luotao1** [comment]
Following script can download the MobileNet (both model and weight)
https://github.com/PaddlePaddle/Paddle/blob/aa6b2bda2c4e11db847cabbded5fbf227e03a81a/paddle/fluid/inference/api/demo_ci/run.sh#L46-L49
You can `wget http://paddlemodels.cdn.bcebos.com/inference-vis-demos%2F/mobilenet.tar.gz`

**Comment by wojtuss** [comment]
@luotao1 , the model you gave us a link to seems to be MobileNet-SSD model, it contains `prior_box` primitives:
![image](https://user-images.githubusercontent.com/19307410/47647265-bc811480-db76-11e8-8c7d-b40542d4deaa.png)
Do you have a MobileNet-v1 (for image classification) model and weights?

**Comment by luotao1** [comment]
@wojtuss You can try :

Random initialized one:
`wget http://paddle-inference-dist.bj.bcebos.com/tensorrt_test/mobilenet.tar.gz`

**Comment by NHZlX** [comment]
The model offered by @luotao1 is Initialized of random parameters, i will offer an `imagenet trained` one.

Imagenet trained one:
`http://paddle-inference-dist.cdn.bcebos.com/mobilenet_imagenet_pretrained.tar.gz`

**Comment by wojtuss** [comment]
@luotao1, @NHZlX, thank you! Do you have also a pretrained model with `top_k`, `cross_entropy` and `accuracy` layers?

**Comment by wojtuss** [comment]
@luotao1 , @NHZlX , or is there a way to add those layers to your model?

**Comment by luotao1** [comment]
CRNN-CTC https://github.com/PaddlePaddle/Paddle/issues/13574#issuecomment-424652591 has the `top-k` layer.  But `cross_entropy` and `accuracy` are not in any inference models, `save_inference_model` will clip these layers since they are not used in inference.

**Comment by wojtuss** [comment]
@luotao1 , is there a way to add `cross_entropy` and `accuracy` layers to a model saved using `save_inference_model`?

**Comment by luotao1** [comment]
You can try to insert these two layer like
https://github.com/PaddlePaddle/Paddle/blob/90d9e5aee891c3ebf576ceb58cde459799cfa13d/python/paddle/fluid/transpiler/inference_transpiler.py#L347-L353

**Comment by wojtuss** [comment]
@luotao1 , thanks for the idea, though I'm not sure how to apply it yet.
@NHZlX , the model you shared does not contain the `top-k` layer, do you have a model that contains the `top-k`?
I'm looking for a trained model we could use to verify the accuracy.

**Comment by bingyanghuang** [comment]
@wojtuss  if I do understand correctly, this request is for the following INT8 work, right?

**Comment by luotao1** [comment]
@wojtuss Please contact @hshen14 at first. We send some models to him.

**Comment by hshen14** [comment]
You may try this one: http://paddle-inference-dist.cdn.bcebos.com/mobilenet_imagenet_pretrained.tar.gz

I used the one shared by internal channel, but I believe they are the same.

**Comment by hshen14** [comment]
BTW, I used the below command "FLAGS_use_mkldnn=true OMP_NUM_THREADS=28 KMP_AFFINITY=compact,granularity=fine taskset -c 0-27 numactl -l python eval.py  --model=MobileNet  --batch_size=50  --class_dim=1000  --image_shape=3,224,224  --with_mem_opt=True  --use_gpu=False --pretrained_model=fluid_mobilenet_v1". Latest public Paddle and models.

**Comment by wojtuss** [comment]
@hshen14 , thank you for the model you have shared by internal channel! It works great! And it is different from the one you shared above.

**Comment by wojtuss** [comment]
@luotao1 , using the model from @hshen14 we get top1 accuracy 70.43 % (with and without optimizations) on the full validation ImageNet dataset. Is it acceptable for Baidu?

**Comment by sfraczek** [comment]
@hshen14 and @NHZIX do I see right that the model you referenced http://paddle-inference-dist.cdn.bcebos.com/mobilenet_imagenet_pretrained.tar.gz has no depthwise_conv layers but conv layers instead?

**Comment by sfraczek** [comment]
While this one http://paddle-inference-dist.bj.bcebos.com/tensorrt_test/mobilenet.tar.gz has weights in separate files (not in one params file) and I can't load it in my test_analyzer_mobilenet.

**Comment by luotao1** [comment]
@sfraczek To combine separate files into one param file, you can:
```python
[program, feed_target_names, fetch_targets] = 
    fluid.io.load_inference_model(src_model, exe)
fluid.io.save_inference_model(dst_model, feed_target_names, fetch_targets, 
    exe, model_filename="model", params_filename="param")
```

**Comment by sfraczek** [comment]
I'm sorry, I see I didn't mention this, but I need to do this in CAPI, not python, specifically in the test `test_analyzer_mobilenet`. Is there api for that?

**Comment by luotao1** [comment]
@sfraczek You can combine separate files into one param file by python at first, and then use the one param file for CAPI.

**Comment by sfraczek** [comment]
Ok, then I should send it to you for uploading?

**Comment by luotao1** [comment]
Yes, you can send to me. The new model:
- has `model` and `params` file
- has `depthwise_conv` op

**Comment by sfraczek** [comment]
I'm trying to do it how you showed but I can't get it to work.
```python
# load model
142     [infer_program, feed_dict, fetch_targets] = fluid.io.load_inference_model(
143         args.infer_model_path, exe)
144
145     # Save model
146     if not os.path.isdir(args.save_model_path):
147         os.makedirs(args.save_model_path)
148
149     fluid.io.save_inference_model(
150         args.save_model_path, feed_dict,
151         fetch_targets,
152         exe,
153         model_filename="model",
154         params_filename="params")
```
The error is:
```python
Traceback (most recent call last):
  File "infer_image_classification.py", line 279, in <module>
    infer(args)
  File "infer_image_classification.py", line 154, in infer
    params_filename="params")
  File "/home/sfraczek/source/pr/Paddle/build/python/paddle/fluid/io.py", line 654, in save_inference_model
    main_program = main_program._prune(targets=target_vars)
  File "/home/sfraczek/source/pr/Paddle/build/python/paddle/fluid/framework.py", line 1739, in _prune
    "The target variable must have an "
ValueError: The target variable must have an associated operator that generates it.
```

**Comment by luotao1** [comment]
This is my script, you can refer to it. It can merge several parameters into one, and for `__model__`, just rename it. @sfraczek 
```python
import paddle.fluid as fluid
import os
import sys

def main(src_model, dst_model):
    if not os.path.isdir(dst_model):
        os.makedirs(dst_model)

    place = fluid.CPUPlace()
    exe = fluid.Executor(place)
    inference_scope = fluid.core.Scope()

    with fluid.scope_guard(inference_scope):
        [inference_program, feed_target_names,
         fetch_targets] = fluid.io.load_inference_model(src_model, exe)

        fluid.io.save_persistables(exe, dst_model, inference_program, 'params')

if __name__ == '__main__':
    src_model = sys.argv[1]
    dst_model = sys.argv[2]
    main(src_model, dst_model)
```

**Comment by sfraczek** [comment]
Please upload the model from this link: https://www.dropbox.com/s/boqe6v7l1ygosim/mobilenet_model.tar.gz?dl=0
(change dl=0 to dl=1 if you want to download it right away)
I converted it from:
http://paddle-inference-dist.bj.bcebos.com/tensorrt_test/mobilenet.tar.gz

**Comment by sfraczek** [comment]
Also, thank you for the script. It helped a lot.

**Comment by luotao1** [comment]
@sfraczek I upload, and the url is http://paddle-inference-dist.bj.bcebos.com/mobilenet_model.tar.gz
