### ISSUE TITLE
embeding后concat跟没有concat网络结构的区别

### ISSUE THREAD

**Issue by zhanliqing** [PaddlePaddle/Paddle#14083]
请教一下，我有3个特征,a,b,c ，分别做了embeding，一种是我把3个embeding后的值放到一个list, [a,b,c] ，还有一种是我把这3个embeding后的值做concat,
分别接fc，请问这两个网络结构是一样的吗，不过不一样，有什么区别

**Comment by guoshengCS** [comment]
这两种效果是一样的

**Comment by zhanliqing** [comment]
感觉不一样，实例代码如下

input_a = paddle.layer.data('input_a', paddle.data_type.integer_value_sequence(10000))
emb_a = paddle.layer.embedding('emb_a', input=input_a , size = 16, param_attr = paddle.attr.Param(initial_max = 1.0, initial_min = -1.0))

input_b = paddle.layer.data('input_b', paddle.data_type.integer_value_sequence(10000))
emb_b = paddle.layer.embedding('emb_b', input=input_b , size = 16, param_attr = paddle.attr.Param(initial_max = 1.0, initial_min = -1.0))


input_c = paddle.layer.data('input_c', paddle.data_type.integer_value_sequence(10000))
emb_c = paddle.layer.embedding('emb_c', input=input_c , size = 16, param_attr = paddle.attr.Param(initial_max = 1.0, initial_min = -1.0))

lst = list()
lst.append(emb_a)
lst.append(emb_b)
lst.append(emb_c)

fc_1 = paddle.layer.fc(name='fc_1', input=lst, size=256, act=paddle.activation.Linear())

训练好后，我infer  fc_1的输出，用
fc_1 = paddle.layer.fc(name='fc_1', input=lst, size=256, act=paddle.activation.Linear())
跟
emb_concat = paddle.layer.concat(lst)
fc_1 = paddle.layer.fc(name='fc_1', input=emb_concat, size=256, act=paddle.activation.Linear())

打印输出fc_1的值不一样

**Comment by guoshengCS** [comment]
这里可能是由于随机初始化引入的差异，可以试下在程序最开始（定义网络结构之前）设置下`paddle.fluid.default_startup_program().seed`和`paddle.fluid.default_startup_program().seed`固定下随机性

**Comment by lucywsq** [comment]
您好，此issue若已经解决，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题，我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持!
