### ISSUE TITLE
why does depthwise convolution has condition num_filters % num_channels instead of ==?

### ISSUE THREAD

**Issue by sfraczek** [PaddlePaddle/Paddle#14092]
Hi,

Regarding this:
https://github.com/PaddlePaddle/Paddle/blob/a3efba176c65fed4553cdccdb1b0d9f57f9b97ab/python/paddle/fluid/layers/nn.py#L1594
I would like to know why is this condition not `num_filters == num_channels`?

**Comment by luotao1** [comment]
@NHZlX Could you help answer this question, since this condition is added by you in https://github.com/PaddlePaddle/Paddle/commit/6e17babe49a7fdeb4f345c83d347f217d05e7e77?

**Comment by NHZlX** [comment]
@sfraczek <del>`num_channels` here represents the num of the input channels. `num_filters ` represents the num of the output channels. There are two type depthwise conv in mobilenet. 1). The input shape equals output shape, the depthwise_separable  contains a 1 * 1 conv and 3 *3 conv(kernel size: 3, stride: 1), the output channels num equals to the input channels num.  2) The size of the output is approximately 1/2 of the input size, the depthwise_separable  contains a 1 * 1 conv and 3 *3 conv(kernel size: 3, stride: 2), The number of output channels is two times that of input channel.</del>

**Comment by sfraczek** [comment]
Thank you for replying!

Are you sure? I can't find the **2)** case. Is it in other mobilenet architectures?
In this mobilenet paper: https://arxiv.org/abs/1704.04861 I found this table:
![image](https://user-images.githubusercontent.com/17185347/47644749-504ee280-db6f-11e8-91cd-01606bb96891.png)
And there seems to be always (for depthwise conv) `num_filters == num_channels`.

Looking at PaddlePaddle I found that always `groups == num_channels` https://github.com/PaddlePaddle/models/blob/develop/fluid/PaddleCV/image_classification/models/mobilenet.py#L42. 
I see `num_filters` doubled in some cases of the **pointwise convolution only** but they have `groups=1`. I don't see the case where `num_filters != num_channels` in this mobilenet architecture.

**Comment by NHZlX** [comment]
Sorry about the last reply. It seems that i have forgotten the structure of mobilenet. `num_filters % num_channels == 0 ` might  for flexibility.  Tensorflow use `channel_multiplier` to control this, which can be infer from [here](https://www.tensorflow.org/api_docs/python/tf/nn/separable_conv2d?hl=zh-cn).

**Comment by sfraczek** [comment]
Thank you for answers! I had to know if there is something I need to worry about. So I think I don't have to worry about this. MKL-DNN should handle both cases (= and %) even if mkl-dnn developers say that depthwise conv is the case where they are all equal.
