### ISSUE TITLE
modprobe: ERROR: ../libkmod/libkmod.c:556 kmod_search_moddep() could not open moddep file '/lib/modules/2.6.32-573.el6.x86_64/modules.dep.bin'

### ISSUE THREAD

**Issue by Ayle3125** [PaddlePaddle/Paddle#1410]
root@b81a5d1d4262:/home/code/traffic_prediction# sh train.sh
I0221 23:49:55.158325    34 Util.cpp:155] commandline: /usr/local/bin/../opt/paddle/bin/paddle_trainer --config=trainer_config.py --save_dir=./output --trainer_count=4 --log_period=1000 --dot_period=10 --num_passes=10 --use_gpu=true --show_parameter_stats_period=3000 
modprobe: ERROR: ../libkmod/libkmod.c:556 kmod_search_moddep() could not open moddep file '/lib/modules/2.6.32-573.el6.x86_64/modules.dep.bin'
F0221 23:49:59.081681    34 hl_cuda_device.cc:526] Check failed: cudaSuccess == cudaStat (0 vs. 30) Cuda Error: unknown error
*** Check failure stack trace: ***
    @     0x7f47aff0fdaa  (unknown)
    @     0x7f47aff0fce4  (unknown)
    @     0x7f47aff0f6e6  (unknown)
    @     0x7f47aff12687  (unknown)
    @           0x895560  hl_specify_devices_start()
    @           0x89576d  hl_start()
    @           0x80f402  paddle::initMain()
    @           0x52ac5b  main
    @     0x7f47af11bf45  (unknown)
    @           0x540c05  (unknown)
    @              (nil)  (unknown)
/usr/local/bin/paddle: line 109:    34 Aborted                 (core dumped) ${DEBUGGER} $MYDIR/../opt/paddle/bin/paddle_trainer ${@:2}

plz

**Comment by Ayle3125** [comment]
I change the "LD_LIBRARY_PATH"
"export LD_LIBRARY_PATH=/usr/lib64:$LD_LIBRARY_PATH"

Maybe I need reboot the container? But when I exit and restart the container the "LD_LIBRARY_PATH" would not be saved.

What can I do?

**Comment by hedaoyuan** [comment]
Write `export LD_LIBRARY_PATH=/usr/lib64:$LD_LIBRARY_PATH` into `~/.bashrc` file.

**Comment by Ayle3125** [comment]
I have changed the  library_path, however, the problem still exists...

:<

**Comment by Ayle3125** [comment]
I reflect the host file to docker system....but a new "modprobe: ERROR" problem appeares:
modprobe error could not insert 'nvidia_uvm': Operation not permitted.

Is there something wrong with my cuda driver? 

Please help me T.T

**Comment by gangliao** [comment]
please follow this: https://github.com/PaddlePaddle/Paddle/blob/develop/doc/getstarted/build_and_install/docker_install_en.rst

**Comment by Ayle3125** [comment]
Thank you very much.
@gangliao 
I download and run the docker images "gpu-latest", following [](http://www.paddlepaddle.org/doc/build/docker_install.html).
So, the solution to the error is building a new image from source code?

**Comment by gangliao** [comment]
You can also pull docker image.

**Comment by gangliao** [comment]
Please read the latest docs carefully.
https://github.com/PaddlePaddle/Paddle/blob/develop/doc/getstarted/build_and_install/docker_install_en.rst

For instance,
 
just please don't forget to install CUDA driver and let Docker knows about it:
```
export CUDA_SO="$(\ls /usr/lib64/libcuda* | xargs -I{} echo '-v {}:{}') $(\ls /usr/lib64/libnvidia* | xargs -I{} echo '-v {}:{}')"
export DEVICES=$(\ls /dev/nvidia* | xargs -I{} echo '--device {}:{}')
docker run ${CUDA_SO} ${DEVICES} -it paddledev/paddle:gpu-latest
```

**Comment by Ayle3125** [comment]
I do pull the image and set the environment variables following the tutorial ....
and "export LD_LIBRARY_PATH=/usr/lib64:$LD_LIBRARY_PATH"
and set "/lib/modules"
...

What could I do?
I am also desperate T.T

@gangliao Save me please.

**Comment by gangliao** [comment]
Actually, Paddle Docker Image is no problem. The problem is from your GPU driver. https://devtalk.nvidia.com/default/topic/744881/cuda-in-debian-linux-doesn-t-work-/

**Comment by Yancey1989** [comment]
Close the inactivate issue, reopen it for free please.
