### ISSUE TITLE
nccl2 多机多卡下出错

### ISSUE THREAD

**Issue by ccmeteorljh** [PaddlePaddle/Paddle#14109]
模型：resnet
paddle_version: 1.0.2.post85
**多机单卡下运行正常**
运行命令：
```bash
python -u fluid_benchmark.py --model resnet --gpus 8 --update_method nccl2 --iterations -1 --pass_num 200 --use_reader_op --learning_rate 0.025 --memory_optimize
```
报错如下:
```bash
yq01-jpaas-ai00-let0034:890:890 [0] misc/ibvwrap.cu:60 WARN Failed to open libibverbs.so[.1]
yq01-jpaas-ai00-let0034:890:890 [0] INFO Using internal Network Socket
yq01-jpaas-ai00-let0034:890:890 [0] INFO Using NCCL Low-latency algorithm for sizes below 16384
yq01-jpaas-ai00-let0034:890:1081 [0] INFO NET : Using interface eth0:10.255.121.17<0>
yq01-jpaas-ai00-let0034:890:1081 [0] INFO NET : Using interface matrix0:172.27.0.1<0>
yq01-jpaas-ai00-let0034:890:1081 [0] INFO NET : Using interface matrixdummy0:fe80::f800:ff:fe00:0%matrixdummy0<0>
yq01-jpaas-ai00-let0034:890:1081 [0] INFO NET/Socket : 3 interfaces found
yq01-jpaas-ai00-let0034:890:1081 [0] INFO 7 -> 8 via NET/Socket/0
yq01-jpaas-ai00-let0034:890:1083 [2] INFO Ring 00 : 10[2] -> 11[3] via P2P/direct pointer
yq01-jpaas-ai00-let0034:890:1086 [5] INFO Ring 00 : 13[5] -> 14[6] via P2P/direct pointer
yq01-jpaas-ai00-let0034:890:1084 [3] INFO Ring 00 : 11[3] -> 12[4] via P2P/direct pointer
yq01-jpaas-ai00-let0034:890:1082 [1] INFO Ring 00 : 9[1] -> 10[2] via P2P/direct pointer
yq01-jpaas-ai00-let0034:890:1085 [4] INFO Ring 00 : 12[4] -> 13[5] via P2P/direct pointer
yq01-jpaas-ai00-let0034:890:1087 [6] INFO Ring 00 : 14[6] -> 15[7] via P2P/direct pointer
yq01-jpaas-ai00-let0034:890:1081 [0] INFO Ring 00 : 8[0] -> 9[1] via P2P/direct pointer
yq01-jpaas-ai00-let0034:890:1081 [0] INFO 7 -> 8 via NET/Socket/1
yq01-jpaas-ai00-let0034:890:1082 [1] INFO Ring 01 : 9[1] -> 10[2] via P2P/direct pointer
yq01-jpaas-ai00-let0034:890:1083 [2] INFO Ring 01 : 10[2] -> 11[3] via P2P/direct pointer
yq01-jpaas-ai00-let0034:890:1084 [3] INFO Ring 01 : 11[3] -> 12[4] via P2P/direct pointer
yq01-jpaas-ai00-let0034:890:1081 [0] INFO Ring 01 : 8[0] -> 9[1] via P2P/direct pointer
yq01-jpaas-ai00-let0034:890:1086 [5] INFO Ring 01 : 13[5] -> 14[6] via P2P/direct pointer
yq01-jpaas-ai00-let0034:890:1087 [6] INFO Ring 01 : 14[6] -> 15[7] via P2P/direct pointer
yq01-jpaas-ai00-let0034:890:1085 [4] INFO Ring 01 : 12[4] -> 13[5] via P2P/direct pointer

yq01-jpaas-ai00-let0034:890:1088 [7] include/socket.h:185 WARN Call to connect failed : Connection refused
yq01-jpaas-ai00-let0034:890:1088 [7] INFO transport/net_socket.cu:101 -> 2
yq01-jpaas-ai00-let0034:890:1088 [7] INFO include/net.h:28 -> 2 [Net]
yq01-jpaas-ai00-let0034:890:1088 [7] INFO transport/net.cu:271 -> 2
yq01-jpaas-ai00-let0034:890:1088 [7] INFO init.cu:484 -> 2
yq01-jpaas-ai00-let0034:890:1088 [7] INFO init.cu:542 -> 2
yq01-jpaas-ai00-let0034:890:1088 [7] INFO misc/group.cu:70 -> 2 [Async thread]
F1028 10:18:47.714808   890 nccl_helper.h:62] Check failed: dynload::ncclGroupEnd() == ncclSuccess (2 vs. 0) 
*** Check failure stack trace: ***
    @     0x7f42a72a57dd  google::LogMessage::Fail()
    @     0x7f42a72a928c  google::LogMessage::SendToLog()
yq01-jpaas-ai00-let0034:890:1082 [1] INFO Ring 02 : 9[1] -> 10[2] via P2P/direct pointer
    @     0x7f42a72a5303  google::LogMessage::Flush()
    @     0x7f42a72aa79e  google::LogMessageFatal::~LogMessageFatal()
    @     0x7f42a72fddef  paddle::platform::NCCLGroupGuard::~NCCLGroupGuard()
    @     0x7f42a7300a8d  paddle::platform::NCCLContextMap::NCCLContextMap()
yq01-jpaas-ai00-let0034:890:1087 [6] INFO Ring 02 : 14[6] -> 15[7] via P2P/direct pointer
yq01-jpaas-ai00-let0034:890:1085 [4] INFO Ring 02 : 12[4] -> 13[5] via P2P/direct pointer
    @     0x7f42a72fac95  paddle::framework::ParallelExecutor::ParallelExecutor()
yq01-jpaas-ai00-let0034:890:1084 [3] INFO Ring 02 : 11[3] -> 12[4] via P2P/direct pointer
yq01-jpaas-ai00-let0034:890:1086 [5] INFO Ring 02 : 13[5] -> 14[6] via P2P/direct pointer
yq01-jpaas-ai00-let0034:890:1083 [2] INFO Ring 02 : 10[2] -> 11[3] via P2P/direct pointer
    @     0x7f42a7271095  _ZZN8pybind1112cpp_function10initializeIZNS_6detail4initIIRKSt6vectorIN5boost7variantIN6paddle8platform9CUDAPlaceENS8_8CPUPlaceENS8_15CUDAPinnedPlaceENS5_6detail7variant5void_ESE_SE_SE_SE_SE_SE_SE_SE_SE_SE_SE_SE_SE_SE_SE_SE_EESaISF_EERKSt13unordered_setISsSt4hashISsESt8equal_toISsESaISsEESS_RKNS7_9framework11ProgramDescERKSsPNST_5ScopeERS4_IS10_SaIS10_EERKNST_7details17ExecutionStrategyERKNS14_13BuildStrategyEmmEE7executeINS_6class_INST_16ParallelExecutorEIEEEIELi0EEEvRT_DpRKT0_EUlPS1E_SJ_SS_SS_SW_SY_S10_S13_S17_S1A_mmE_vIS1M_SJ_SS_SS_SW_SY_S10_S13_S17_S1A_mmEINS_4nameENS_9is_methodENS_7siblingEEEEvOT_PFT0_DpT1_EDpRKT2_ENKUlRNS2_13function_callEE1_clES23_
    @     0x7f42a72711ee  _ZZN8pybind1112cpp_function10initializeIZNS_6detail4initIIRKSt6vectorIN5boost7variantIN6paddle8platform9CUDAPlaceENS8_8CPUPlaceENS8_15CUDAPinnedPlaceENS5_6detail7variant5void_ESE_SE_SE_SE_SE_SE_SE_SE_SE_SE_SE_SE_SE_SE_SE_SE_EESaISF_EERKSt13unordered_setISsSt4hashISsESt8equal_toISsESaISsEESS_RKNS7_9framework11ProgramDescERKSsPNST_5ScopeERS4_IS10_SaIS10_EERKNST_7details17ExecutionStrategyERKNS14_13BuildStrategyEmmEE7executeINS_6class_INST_16ParallelExecutorEIEEEIELi0EEEvRT_DpRKT0_EUlPS1E_SJ_SS_SS_SW_SY_S10_S13_S17_S1A_mmE_vIS1M_SJ_SS_SS_SW_SY_S10_S13_S17_S1A_mmEINS_4nameENS_9is_methodENS_7siblingEEEEvOT_PFT0_DpT1_EDpRKT2_ENUlRNS2_13function_callEE1_4_FUNES23_
    @     0x7f42a722f824  pybind11::cpp_function::dispatcher()
    @     0x7f4306896323  PyObject_Call
    @     0x7f43068a7dec  instancemethod_call
    @     0x7f4306896323  PyObject_Call
    @     0x7f4306903e3d  slot_tp_init
    @     0x7f430690276f  type_call
    @     0x7f4306896323  PyObject_Call
    @     0x7f430694c442  PyEval_EvalFrameEx
    @     0x7f430694f48c  PyEval_EvalCodeEx
    @     0x7f43068c8455  function_call
    @     0x7f4306896323  PyObject_Call
    @     0x7f43068a7dec  instancemethod_call
    @     0x7f4306896323  PyObject_Call
    @     0x7f4306903e3d  slot_tp_init
    @     0x7f430690276f  type_call
    @     0x7f4306896323  PyObject_Call
    @     0x7f430694c442  PyEval_EvalFrameEx
    @     0x7f430694f48c  PyEval_EvalCodeEx
    @     0x7f43068c836c  function_call
    @     0x7f4306896323  PyObject_Call
    @     0x7f430694ad97  PyEval_EvalFrameEx
    @     0x7f430694e3ac  PyEval_EvalFrameEx
    @     0x7f430694f48c  PyEval_EvalCodeEx
```

**Comment by ccmeteorljh** [comment]
#13599

**Comment by typhoonzero** [comment]
此问题原因和 #13599 应该是一样的，大概率是环境原因

**Comment by LihangLiu** [comment]
我也碰到了Check failed: dynload::ncclGroupEnd() == ncclSuccess (1 vs. 0) 的问题，因为按照[#13599](https://github.com/PaddlePaddle/Paddle/issues/13599) 将num_thread=1。

    F1122 12:57:04.196161 22202 nccl_helper.h:62] Check failed: dynload::ncclGroupEnd() == ncclSuccess (1 vs. 0) 
    *** Check failure stack trace: ***
        @     0x7fd3677641ed  google::LogMessage::Fail()
        @     0x7fd367767c9c  google::LogMessage::SendToLog()
        @     0x7fd367763d13  google::LogMessage::Flush()
        @     0x7fd3677691ae  google::LogMessageFatal::~LogMessageFatal()
        @     0x7fd3677bb0f6  paddle::platform::NCCLGroupGuard::~NCCLGroupGuard()
        @     0x7fd3677bda0c  paddle::platform::NCCLContextMap::NCCLContextMap()
        @     0x7fd3677b9210  paddle::framework::ParallelExecutor::ParallelExecutor()
        @     0x7fd367733058  _ZZN8pybind1112cpp_function10initializeIZNS_6detail4initIIRKSt6vectorIN5boost7variantIN6paddle8platform9CUDAPlaceENS8_8CPUPlaceENS8_15CUDAPinnedPlaceENS5_6detail7variant5void_ESE_SE_SE_SE_SE_SE_SE_SE_SE_SE_SE_SE_SE_SE_SE_SE_EESaISF_EERKSt13unordered_setISsSt4hashISsESt8equal_toISsESaISsEESS_RKNS7_9framework11ProgramDescERKSsPNST_5ScopeERS4_IS10_SaIS10_EERKNST_7details17ExecutionStrategyERKNS14_13BuildStrategyEmmEE7executeINS_6class_INST_16ParallelExecutorEIEEEIELi0EEEvRT_DpRKT0_EUlPS1E_SJ_SS_SS_SW_SY_S10_S13_S17_S1A_mmE_vIS1M_SJ_SS_SS_SW_SY_S10_S13_S17_S1A_mmEINS_4nameENS_9is_methodENS_7siblingEEEEvOT_PFT0_DpT1_EDpRKT2_ENKUlRNS2_13function_callEE1_clES23_
        @     0x7fd36773318e  _ZZN8pybind1112cpp_function10initializeIZNS_6detail4initIIRKSt6vectorIN5boost7variantIN6paddle8platform9CUDAPlaceENS8_8CPUPlaceENS8_15CUDAPinnedPlaceENS5_6detail7variant5void_ESE_SE_SE_SE_SE_SE_SE_SE_SE_SE_SE_SE_SE_SE_SE_SE_EESaISF_EERKSt13unordered_setISsSt4hashISsESt8equal_toISsESaISsEESS_RKNS7_9framework11ProgramDescERKSsPNST_5ScopeERS4_IS10_SaIS10_EERKNST_7details17ExecutionStrategyERKNS14_13BuildStrategyEmmEE7executeINS_6class_INST_16ParallelExecutorEIEEEIELi0EEEvRT_DpRKT0_EUlPS1E_SJ_SS_SS_SW_SY_S10_S13_S17_S1A_mmE_vIS1M_SJ_SS_SS_SW_SY_S10_S13_S17_S1A_mmEINS_4nameENS_9is_methodENS_7siblingEEEEvOT_PFT0_DpT1_EDpRKT2_ENUlRNS2_13function_callEE1_4_FUNES23_
        @     0x7fd3676fa2a2  pybind11::cpp_function::dispatcher()
        @     0x7fd3b0d7d973  PyObject_Call
        @     0x7fd3b0d8c80d  instancemethod_call
        @     0x7fd3b0d7d973  PyObject_Call
        @     0x7fd3b0dd6764  slot_tp_init
        @     0x7fd3b0dd301b  type_call
        @     0x7fd3b0d7d973  PyObject_Call
        @     0x7fd3b0e13d49  PyEval_EvalFrameEx
        @     0x7fd3b0e196c9  PyEval_EvalCodeEx
        @     0x7fd3b0da2567  function_call
        @     0x7fd3b0d7d973  PyObject_Call
        @     0x7fd3b0d8c80d  instancemethod_call
        @     0x7fd3b0d7d973  PyObject_Call
        @     0x7fd3b0dd6764  slot_tp_init
        @     0x7fd3b0dd301b  type_call
        @     0x7fd3b0d7d973  PyObject_Call
        @     0x7fd3b0e13d49  PyEval_EvalFrameEx
        @     0x7fd3b0e1817e  PyEval_EvalFrameEx
        @     0x7fd3b0e196c9  PyEval_EvalCodeEx
        @     0x7fd3b0e198ea  PyEval_EvalCode
        @     0x7fd3b0e32bad  run_mod
        @     0x7fd3b0e33d28  PyRun_FileExFlags
        @     0x7fd3b0e34f48  PyRun_SimpleFileExFlags
    Aborted

**Comment by typhoonzero** [comment]
Hi, https://github.com/PaddlePaddle/Paddle/pull/14586 已经修复此类问题， 请尝试用最新版本

**Comment by lucywsq** [comment]
您好，此问题已经解决，我们将于今天内关闭，如果有问题您可随时开启，感谢您对PaddlePaddle的支持！
