### ISSUE TITLE
fluid 1.0的paddle.fluid.metrics.CompositeMetric报错

### ISSUE THREAD

**Issue by shiyazhou121** [PaddlePaddle/Paddle#14105]
在训练里加入compsite，准备得到准召率。
![image](https://user-images.githubusercontent.com/15082798/47626071-2c39d400-db64-11e8-8c15-16df74f16e1b.png)
然后报错，
![image](https://user-images.githubusercontent.com/15082798/47626085-3cea4a00-db64-11e8-85c4-2d7b2dd45ead.png)
求解决下。。程序是在mpi-paddle集群跑的。

**Comment by shiyazhou121** [comment]
@dzhwinter 问下，修复了吗。。

**Comment by dzhwinter** [comment]
It has been fixed in #14104
