### ISSUE TITLE
cpu训练报错：CUDA driver version is insufficient for CUDA runtime

### ISSUE THREAD

**Issue by lyp2github** [PaddlePaddle/Paddle#14111]
平台：使用paddlecloud训练
cpu版本的模型训练出现以上错误，paddlecloud反馈
“我们排查后认为比较可能是由paddle v2代码中产生的问题。因为你使用的是cpu集群运行的任务，应该不存在cuda版本不对的问题……”
模型开放模型:dssm https://github.com/PaddlePaddle/models/tree/8bca0e4311b444a61024c2a5dd755a22b47487da/legacy/dssm
并已指定CPU运行use_gpu=False
    "--use_gpu",
    type=distutils.util.strtobool,
    default=False,

**Comment by jacquesqiao** [comment]
找一个纯CPU版本的paddle试试？

**Comment by jacquesqiao** [comment]
看起来这个问题需要paddle cloud的人跟进一下，确认下环境

**Comment by jacquesqiao** [comment]
cloud环境中安装了一个带cuda的paddle版本，需要cloud同学解决。
