### ISSUE TITLE
训练网络和预测网络略有不同 如何加载模型

### ISSUE THREAD

**Issue by frankwhzhang** [PaddlePaddle/Paddle#14113]
训练网络是有正例tag和负例tag ，训练过程中利用两者相减 求得loss， 但是在预测网络中，只有无属性的tag。主要的网络结构是相同的 ，如何利用训练好的模型参数进行预测 。有没有相关的样例。

**Comment by jacquesqiao** [comment]
save_inference_model保存的时候，只保存你需要的target，会自动裁剪网络

**Comment by frankwhzhang** [comment]
是不是我可以把预测的网络也写到训练网络中，不feed ,预测的时候再feed数据
