### ISSUE TITLE
任务运行失败，Check failed: len > 0  

### ISSUE THREAD

**Issue by lyp2github** [PaddlePaddle/Paddle#14120]
平台：paddlecloud 
jobid= job-e6c5bd6b88eb7964
历史类似问题说是因为超时被kill, 但任务明显没有超时
作业提交时间：2018-10-29 15:37:03
作业开始时间：2018-10-29 15:37:40
作业结束时间：2018-10-29 17:12:46
已经执行的时间：01 hour 35 min 01 sec

报错信息：
F1029 17:07:19.030912 20059 SocketChannel.cpp:101] Check failed: len > 0  peer=10.75.68.23 curIov=23 iovCnt=117 iovs[curIov].base=0x7f5a0ec8a99d iovs[curIov].iov_len=34467
*** Check failure stack trace: ***
    @     0x7f5a43a8af5d  google::LogMessage::Fail()
    @     0x7f5a43a8ea0c  google::LogMessage::SendToLog()
    @     0x7f5a43a8aa83  google::LogMessage::Flush()
    @     0x7f5a43a8ff1e  google::LogMessageFatal::~LogMessageFatal()
    @     0x7f5a43866bd1  paddle::readwritev<>()
    @     0x7f5a438677e4  paddle::MsgReader::readBlocks()
    @     0x7f5a4566459a  paddle::ParameterClient2::sendParallel()
    @     0x7f5a439d43cc  _ZNSt6thread5_ImplISt12_Bind_simpleIFZN6paddle14SyncThreadPool5startEvEUliE_mEEE6_M_runEv
    @     0x7f5a9793e8a0  execute_native_thread_routine
    @     0x7f5aa88a21c3  start_thread
    @     0x7f5aa7eca12d  __clone

**Comment by typhoonzero** [comment]
您好，v2版本可以先参考http://www.paddlepaddle.org/documentation/docs/zh/0.12.0/faq/cluster/index_cn.html 找到最早报错日志排查。如果最早日志均为网络通信错误，请检查是否存在端口混用，端口冲突等问题。

**Comment by lucywsq** [comment]
您好，此issue在近一月内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题，我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持!
