### ISSUE TITLE
SIGSEGV (@0x50) received by PID 105250 (TID 0x7f22ef08b700) from PID 80; stack trace

### ISSUE THREAD

**Issue by JingY0604** [PaddlePaddle/Paddle#14132]
paddle训练的时候报如下异常：
*** Aborted at 1540824797 (unix time) try "date -d @1540824797" if you are using GNU date ***
PC: @                0x0 (unknown)
*** SIGSEGV (@0x50) received by PID 105250 (TID 0x7f22ef08b700) from PID 80; stack trace: ***
    @     0x7f22ee85d7e0 (unknown)
    @     0x7f1feb010e13 (unknown)
    @     0x7f1feb014aed ncclCommInitAll
    @     0x7f228c9da0be paddle::platform::NCCLContextMap::NCCLContextMap()
    @     0x7f228c9d5608 paddle::framework::ParallelExecutor::ParallelExecutor()
    @     0x7f228c94a225                                                                                                                                      _ZZN8pybind1112cpp_function10initializeIZNS_6detail4initIIRKSt6vectorIN5boost7variantIN6paddle8platform9CUDAPlaceENS8_8CPUPlaceENS8_15CUDAPinnedPlaceENS5_6detail7variant5void_ESE_SE_SE_SE_SE_SE_SE_SE_SE_SE_SE_SE_SE_SE_SE_SE_EESaISF_EERKSt13unordered_setISsSt4hashISsESt8equal_toISsESaISsEESS_RKNS7_9framework11ProgramDescERKSsPNST_5ScopeERS4_IS10_SaIS10_EERKNST_7details17ExecutionStrategyERKNS14_13BuildStrategyEmmEE7executeINS_6class_INST_16ParallelExecutorEIEEEIELi0EEEvRT_DpRKT0_EUlPS1E_SJ_SS_SS_SW_SY_S10_S13_S17_S1A_mmE_vIS1M_SJ_SS_SS_SW_SY_S10_S13_S17_S1A_mmEINS_4nameENS_9is_methodENS_7siblingEEEEvOT_PFT0_DpT1_EDpRKT2_ENKUlRNS2_13function_callEE1_clES23_
    @     0x7f228c94a37e                                                                                                                                      _ZZN8pybind1112cpp_function10initializeIZNS_6detail4initIIRKSt6vectorIN5boost7variantIN6paddle8platform9CUDAPlaceENS8_8CPUPlaceENS8_15CUDAPinnedPlaceENS5_6detail7variant5void_ESE_SE_SE_SE_SE_SE_SE_SE_SE_SE_SE_SE_SE_SE_SE_SE_EESaISF_EERKSt13unordered_setISsSt4hashISsESt8equal_toISsESaISsEESS_RKNS7_9framework11ProgramDescERKSsPNST_5ScopeERS4_IS10_SaIS10_EERKNST_7details17ExecutionStrategyERKNS14_13BuildStrategyEmmEE7executeINS_6class_INST_16ParallelExecutorEIEEEIELi0EEEvRT_DpRKT0_EUlPS1E_SJ_SS_SS_SW_SY_S10_S13_S17_S1A_mmE_vIS1M_SJ_SS_SS_SW_SY_S10_S13_S17_S1A_mmEINS_4nameENS_9is_methodENS_7siblingEEEEvOT_PFT0_DpT1_EDpRKT2_ENUlRNS2_13function_callEE1_4_FUNES23_
    @     0x7f228c90c944 pybind11::cpp_function::dispatcher()
    @     0x7f22eeabed33 PyObject_Call
    @     0x7f22eeacd74d (unknown)
    @     0x7f22eeabed33 PyObject_Call
    @     0x7f22eeb2a36f (unknown)
    @     0x7f22eeb28eff (unknown)
    @     0x7f22eeabed33 PyObject_Call

**Comment by guru4elephant** [comment]
export LD_LIBRARY_PATH=nccl2的路径看看

**Comment by dzhwinter** [comment]
+1

**Comment by JingY0604** [comment]
> export LD_LIBRARY_PATH=nccl2的路径看看

加这个也没有用，它本来就会找本地的.so吧

**Comment by dzhwinter** [comment]
1. 需要指定nccl2的路径。
2. 确认一下cuda版本和nccl2能对上吗

**Comment by JingY0604** [comment]
> 1. 需要指定nccl2的路径。
> 2. 确认一下cuda版本和nccl2能对上吗

指定了我本地的nccl2路径， cuda8.0

**Comment by dzhwinter** [comment]
那打开VLOG = 10 检查一下是否load进去正确的nccl包。

**Comment by JingY0604** [comment]
> 那打开VLOG = 10 检查一下是否load进去正确的nccl包。
我开始可以训练，中间报的这个异常，应该跟nccl没有关系吧

**Comment by dzhwinter** [comment]
这个是跑完了初始化就挂掉了，位置是NcclInitCommon，这个是去初始化各个gpu卡，并创建一个context的。所以是nccl包的问题。

**Comment by dzhwinter** [comment]
如果能正常load进相同版本的nccl后，仍然会出这个问题。那看下单测是否能跑起来？ https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/fluid/tests/unittests/test_parallel_executor_mnist.py

**Comment by dzhwinter** [comment]
这个问题是nccl初始化的问题，注意检查nccl load的log过程。
closed.
