### ISSUE TITLE
用Paddle V2进行预测生成图像向量时，如何加快图像处理的速度？如开启多线程等等。

### ISSUE THREAD

**Issue by CruiseSun** [PaddlePaddle/Paddle#14138]
paddle.image.load_and_transform('./images/' + path, 256, 224, False).flatten().astype('float32')
            vec = paddle.infer(output_layer=fc12, parameters=parameters,
                               input=[(paddle.image.load_and_transform('./images/'+path, 256, 224, False).flatten().astype('float32'), )])

**Comment by CruiseSun** [comment]
用的是paddle.v2.infer这个函数测试每张图像生成向量

**Comment by CruiseSun** [comment]
是不是需要把图像搞成batch批量，然后在init时增加trainer.count的数量可以实现？

**Comment by dzhwinter** [comment]
infer直接一次预测多个样本可以吗？ 搞成batch 批量预测也是支持的。

**Comment by dzhwinter** [comment]
单个线程支持一个batch内有多个样本

**Comment by CruiseSun** [comment]
请问增大trainer_count是否可以加快infer的速度呢？

**Comment by CruiseSun** [comment]
还是只能采用多线程的方式呢？

**Comment by dzhwinter** [comment]
增大trainer_count就是多线程

**Comment by lucywsq** [comment]
您好，此问题已经超过一个月未更新，我们将于今天内关闭，如您遇到问题可随时开启，感谢您对PaddlePaddle的支持！
