### ISSUE TITLE
paddle init Fatal Python error: PyThreadState_Get: no current thread

### ISSUE THREAD

**Issue by ZEllison** [PaddlePaddle/Paddle#14133]
mac预装的python是2.7.10
mac系统版本是10.13.2
下载了Python 2.7.15后安装paddle成功，但是运行时执行paddle.init时报错，已经定位到出错行。

报错命令和输出如下：
import py_paddle.swig_paddle as api
Fatal Python error: PyThreadState_Get: no current thread
Abort trap: 6

按照https://github.com/PaddlePaddle/Paddle/issues/5401 的方法尝试了，但是并未解决

**Comment by dzhwinter** [comment]
https://github.com/PaddlePaddle/Paddle/issues/5401#issuecomment-352370732
用评论中的方法验证替换后的Python会链接到哪里

另外，mac推荐用fluid。

**Comment by lucywsq** [comment]
您好，此issue在近三周内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题，我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持!
