### ISSUE TITLE
中文分词的实验卡住

### ISSUE THREAD

**Issue by lucywsq** [PaddlePaddle/Paddle#14146]
您好！我最近准备上那个baidu AI中的中文分词的实验，可是原来能运行的项目，我什么都没改动现在却不能运行了，问题是卡在第一步
#请先运行此代码块获得代码
!DATA_PATH=data/data840/ && NEW_NAME=$(find -name *[0-9].ipynb) && NEW_NAME=${NEW_NAME%.*} && NEW_NAME=${NEW_NAME#./} && unzip -o ${DATA_PATH}中文分词fluid.zip  && cp -rf 中文分词fluid/. . && mv jieba_practice_complete.ipynb ${NEW_NAME}"_complete.ipynb"
单击运行后一直是运行中的状态[*],请帮忙分析是什么原因导致的？谢谢了

**Comment by dzhwinter** [comment]
看起来和paddle没关系，检查一下自己的code？
