### ISSUE TITLE
error in sequence_pad op example

### ISSUE THREAD

**Issue by gmcather** [PaddlePaddle/Paddle#14150]
errors happened as following:
```python
pad_value = fluid.layers.assign(input=np.array([0]))
  File "/home/ssd6/online/fluid_release_home/python/lib/python2.7/site-packages/paddle/fluid/layers/tensor.py", line 269, in assign
    raise ValueError("Unsupported dtype %s", input.dtype)
ValueError: ('Unsupported dtype %s', dtype('int64'))
```
the example in https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/fluid/layers/nn.py#L3019
should be changed to
`fluid.layers.assign(input=numpy.array([0.0], dtype=numpy.float32))`

**Comment by dzhwinter** [comment]
thanks for the reporting. will fixed.
