### ISSUE TITLE
fluid1.0 sequence_pad cpu和cuda版本的结果不一致

### ISSUE THREAD

**Issue by LihangLiu** [PaddlePaddle/Paddle#14164]
以下是我在fluid1.0上跑sequence_pad的结果，cpu和cuda跑出来的output不一样，如下
case1: 一致

    Input: 
    x is 1-level lod tensor
    x.lod = [[0, 8,]]
    x.dims = [8, 1]

    Output:
    CPU version: y.dims = [1, 8, 1]
    CUDA version: y.dims = [8, 1]
case2: 不一致

    Input: 
    x is 1-level lod tensor
    x.lod = [[0, 8, 12]]
    x.dims = [12, 1]

    Output:
    CPU version: y.dims = [2, 8, 1]
    CUDA version: y.dims = [2, 8, 1]

当x有多个sequence的时候，结果是一样的。当x实际只有一个sequence的时候，结果是不一样的。

**Comment by kuke** [comment]
这可能是个bug，我修复一下，然后加个单测

**Comment by lucywsq** [comment]
您好，此bug正在修复中，为了保证用户体验，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题，我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持!

**Comment by kuke** [comment]
https://github.com/PaddlePaddle/Paddle/pull/15103

增加了一个单测case，从单测来看，这个issue应该没问题

**Comment by Ashleychen** [comment]
我遇到了相同的问题，gpu模式下当我batch_size设成1，本来应该返回shape：(batch_size, seq_len, 1），实际返回(seq_len，1)，batch_size这一维被吃掉了。看来这个bug还没有修复？
