### ISSUE TITLE
macOs 怎么安装paddlepaddle 0.15.0?

### ISSUE THREAD

**Issue by aturbofly** [PaddlePaddle/Paddle#14179]
![image](https://user-images.githubusercontent.com/16451716/47786225-13891400-dd46-11e8-885f-64713fc2aed3.png)

**Comment by JiabinYang** [comment]
mac下我们不支持0.15.0版本paddlepaddle的pip安装，具体安装方式请参见：http://paddlepaddle.org/documentation/docs/zh/0.15.0/beginners_guide/install/install_doc.html#paddlepaddle     
您可以pip安装0.15.0以上版本，推荐使用最新版本的paddlepaddle
