### ISSUE TITLE
DynamicRNN输出多个变量时出错

### ISSUE THREAD

**Issue by beacandler** [PaddlePaddle/Paddle#14170]
![image](https://user-images.githubusercontent.com/33446789/47770381-28e84900-dd1a-11e8-8dc9-e019db06796f.png)
如图，我想在每个step输出两个变量，(h, output)，但是在调用方会出现如下错误：

![image](https://user-images.githubusercontent.com/33446789/47770513-a318cd80-dd1a-11e8-9932-875207c453fe.png)

**Comment by guoshengCS** [comment]
麻烦贴下完整的代码，输出一个变量的时候是可以的吗

**Comment by beacandler** [comment]
一个变量可以打印出来，两个也可以打印出来，就是报错

**Comment by kuke** [comment]
@beacandler 请问这个问题最后是否解决，如果还有问题的话还请贴一下完整代码

**Comment by lucywsq** [comment]
您好，此issue在近一个月内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题，我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持!
