### ISSUE TITLE
train.sh 多卡并行报错

### ISSUE THREAD

**Issue by gjtjx** [PaddlePaddle/Paddle#1417]
你好！采用提供的resnet_imagenet_100/paddle
train.sh中开启并行--parallel_nn=1报错
File "/usr/local/lib/python2.7/dist-packages/paddle/trainer/config_parser.py", line 1909, in init
((not parallel_nn) or self.config.device > -1) and 
AttributeError: 'BatchNormLayer' object has no attribute 'config'
这个问题如何解决？

**Comment by qingqing01** [comment]
@gjtjx 多卡并行，实际只需要设置--trainer_count个数，就可以是数据并行，不需要设置parallel_nn。parallel_nn解释和用法可以参考 http://www.paddlepaddle.org/doc/ui/cmd_argument/use_case.html#parallel-nn 。

关于你的报错确实有些问题，我fix下，也多谢提出。

**Comment by qingqing01** [comment]
另外其实 resnet_imagenet_100/paddle 这个不是Paddle官网提供的，issue的标题也不够准确 :)

**Comment by gjtjx** [comment]
文档之前已经看过,我其实是想要模型并行，然后采用这个parallel_nn

**Comment by gjtjx** [comment]
文档之前已经看过,我其实是想要模型并行，然后采用这个parallel_nn

**Comment by gjtjx** [comment]
这个问题fix 了吗？

**Comment by gjtjx** [comment]
我手动去掉((not parallel_nn) or self.config.device > -1) ，训练可以跑起来，但很快报了如下错误：
/usr/local/bin/paddle: line 109: 27759 Aborted                 ${DEBUGGER} $MYDIR/../opt/paddle/bin/paddle_trainer ${@:2}
模型并行功能能否正常，还请大神关注
@ganglian

**Comment by gjtjx** [comment]
/mnt/data1/Vehicle_Train_Rcnn/back/954_1F0224 12:39:13.409380  8446 hl_cuda_device.cc:566] Check failed: cudaSuccess == cudaStat (0 vs. 77) Cuda Error: an illegal memory access was encountered
*** Check failure stack trace: ***
    @           0x93d98c  google::LogMessage::Fail()
    @           0x93d8d3  google::LogMessage::SendToLog()
    @           0x93d248  google::LogMessage::Flush()
    @           0x94043d  google::LogMessageFatal::~LogMessageFatal()
    @           0x90f047  hl_stream_synchronize()
    @           0x9133df  hl_matrix_classification_error()
    @           0x781c9c  paddle::GpuMatrix::classificationError()
    @           0x6ce2a5  paddle::ClassificationErrorEvaluator::calcError()
    @           0x6ce81b  paddle::ClassificationErrorEvaluator::evalImp()
    @           0x6c84d5  paddle::Evaluator::eval()
    @           0x6b5718  paddle::CombinedEvaluator::eval()
    @           0x75b7c4  paddle::TrainerInternal::trainOneBatch()
    @           0x756510  paddle::Trainer::trainOneDataBatch()
    @           0x758cef  paddle::Trainer::trainOnePass()
    @           0x75a100  paddle::Trainer::train()
    @           0x5b4c13  main
    @     0x7f171d4edf45  __libc_start_main
    @           0x5cc5f2  (unknown)
    @              (nil)  (unknown)
4

**Comment by qingqing01** [comment]
@gjtjx 

> cudaSuccess == cudaStat (0 vs. 77) Cuda Error: an illegal memory access was encountered

看下label或者其他数据有没有越界的，或者size不对的呢？

**Comment by gjtjx** [comment]
@qingqing01
/mnt/data1/Vehicle_Train_Rcnn/back/954_1F0224 13:04:18.586678 12570 Matrix.cpp:798] Check failed: output_ptr && label_ptr Invalid argument pointer
*** Check failure stack trace: ***
    @           0x93d98c  google::LogMessage::Fail()
    @           0x93d8d3  google::LogMessage::SendToLog()
    @           0x93d248  google::LogMessage::Flush()
    @           0x94043d  google::LogMessageFatal::~LogMessageFatal()
    @           0x781c7a  paddle::GpuMatrix::classificationError()
    @           0x6ce2a5  paddle::ClassificationErrorEvaluator::calcError()
    @           0x6ce81b  paddle::ClassificationErrorEvaluator::evalImp()
    @           0x6c84d5  paddle::Evaluator::eval()
    @           0x6b5718  paddle::CombinedEvaluator::eval()
    @           0x75b7c4  paddle::TrainerInternal::trainOneBatch()
    @           0x756510  paddle::Trainer::trainOneDataBatch()
    @           0x758cef  paddle::Trainer::trainOnePass()
    @           0x75a100  paddle::Trainer::train()
    @           0x5b4c13  main
    @     0x7f00b0489f45  __libc_start_main
    @           0x5cc5f2  (unknown)
    @              (nil)  (unknown)
在次将provider中的数据生成这块改成yield img_feat.astype('float32'),int(lab.strip) ,然后就报这个指针错误了。

**Comment by gjtjx** [comment]
@qingqing01
paddlepaddle模型并行这个功能有测试过吗？

**Comment by qingqing01** [comment]
@gjtjx  device设置的修复：https://github.com/PaddlePaddle/Paddle/pull/1454

> /mnt/data1/Vehicle_Train_Rcnn/back/954_1F0224 13:04:18.586678 12570 Matrix.cpp:798] Check failed: output_ptr && label_ptr Invalid argument pointer

> paddlepaddle模型并行这个功能有测试过吗？

可能是网络配置或者数据哪里不太对，这个得具体调试吧，不然只有信息看不出来哪里有问题。

**Comment by gjtjx** [comment]
模型并行不行，数据并行是可以的

**Comment by Yancey1989** [comment]
Close the inactive issue, reopen it if any updating.
