### ISSUE TITLE
训练 Check failed: PySequence_Check(seq_)

### ISSUE THREAD

**Issue by zhangyong15** [PaddlePaddle/Paddle#1418]
报如下问题：Check failed: PySequence_Check(seq_)
<img width="645" alt="2017-02-22 2 45 43" src="https://cloud.githubusercontent.com/assets/22140712/23201096/e3e58562-f912-11e6-854b-d67b6ed93a29.png">

已确认过input_types，输入数据顺序，值均没有问题。
参考过issue：#1273，#1114，#1125

**Comment by dreamingcp** [comment]
How do you fix it ?
