### ISSUE TITLE
dropout的使用问题

### ISSUE THREAD

**Issue by Angus07** [PaddlePaddle/Paddle#14180]
在训练中设置dropout，在dev数据集和test数据集上测试的时候，应该是不dropout的。请问
1.如何在dev 数据集上evaluate的时候设置dropout为0呢？
2.保存的模型是否默认会去掉dropout层呢？

**Comment by Superjomn** [comment]
保存模型不会默认去掉dropout，dropout应该有test模式

详细文档： http://www.paddlepaddle.org/documentation/api/zh/1.0/layers.html#dropout

**Comment by Angus07** [comment]
1.不明白，这个网络在初始化都定型了，只能传feed_dict进去，怎么把is_test这个参数传进去？
2.如果不是默认去掉，那么读取模型预测预测的时候还会有dropout的操作？为什么要这么设计？难道还有人在预测的时候保留dropout吗？

**Comment by Superjomn** [comment]
@dzhwinter @qingqing01 可以帮回答下吗

**Comment by seiriosPlus** [comment]
你保存模型的时候指定一下test=true试试呢，
比如 ```inference_program = fluid.default_main_program().clone(for_test=True)```

**Comment by qingqing01** [comment]
@Angus07  如 @seiriosPlus 所说
```
inference_program = fluid.default_main_program().clone(for_test=True)
```
这个操作中`for_test=True`会将dropout接口参数is_test设置True，做预测时该op存在，但内部实现在is_test=True时的操作和训练不同：

```c++
      if (dropout_implementation == "upscale_in_train") {
        Y.device(place) = X;
      } else {
        Y.device(place) = X * static_cast<T>(1.0f - dropout_prob);
     }
```

https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/fluid/operators/dropout_op.h#L72-L

**Comment by dzhwinter** [comment]
用clone接口，可以实现自动转换

**Comment by lucywsq** [comment]
好，此issue在近一个月内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题，我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持!
