### ISSUE TITLE
关于官方文档的问题

### ISSUE THREAD

**Issue by aturbofly** [PaddlePaddle/Paddle#14187]
提两个关于文档的问题：
  1.版本选择0.14.0的时候。点击模型库，显示页面不存在。
￼       
![image](https://user-images.githubusercontent.com/16451716/47828723-44595f80-ddbf-11e8-9fd3-a199ab08ad66.png)

如果只从0.15.0开始才有，也应该处理下。
2.版本选择0.14.0，英文版下面有models，中文版没有。 比如我要找Learning to rank / 排序学习。我中文版里完全找不到入口。 但实际是提供了[中文版](http://www.paddlepaddle.org/documentation/models/en/0.14.0/ltr/README.html)的。并且英文版中models下面的learning to rank 很简单。此外。点击选择了Learning to rank ，然后再点击又上角的
![image](https://user-images.githubusercontent.com/16451716/47828738-4de2c780-ddbf-11e8-8f16-006c86c18641.png)
￼，就这样了。。。：
![image](https://user-images.githubusercontent.com/16451716/47828742-5509d580-ddbf-11e8-8262-eac7b0e3760c.png)

**Comment by shanyi15** [comment]
please check this problem @jetfuel @varunarora ,thanks

**Comment by shanyi15** [comment]
版本选择0.14.0，英文版下面有models，中文版没有。 比如我要找Learning to rank / 排序学习。我中文版里完全找不到入口。 但实际是提供了中文版的。并且英文版中models下面的learning to rank 很简单。此外。点击选择了Learning to rank ，然后再点击又上角的

-----------
您好，@aturbofly 0.14.0的英文版文档的结构和中文版的不一致，中文版的models是有的，只是位置调整到了“使用指南”中，请见：
http://paddlepaddle.org/documentation/docs/zh/0.14.0/new_docs/user_guides/models/index.html
![image](https://user-images.githubusercontent.com/35982308/47833993-8773fc80-ddd8-11e8-9550-55ccc9a50da7.png)

**Comment by aturbofly** [comment]
> 版本选择0.14.0，英文版下面有models，中文版没有。 比如我要找Learning to rank / 排序学习。我中文版里完全找不到入口。 但实际是提供了中文版的。并且英文版中models下面的learning to rank 很简单。此外。点击选择了Learning to rank ，然后再点击又上角的
> 
> 您好，@aturbofly 0.14.0的英文版文档的结构和中文版的不一致，中文版的models是有的，只是位置调整到了“使用指南”中，请见：
> http://paddlepaddle.org/documentation/docs/zh/0.14.0/new_docs/user_guides/models/index.html
> ![image](https://user-images.githubusercontent.com/35982308/47833993-8773fc80-ddd8-11e8-9550-55ccc9a50da7.png)

但这个下面还是找不到排序学习的入口：http://www.paddlepaddle.org/documentation/models/en/0.14.0/ltr/README.html

**Comment by jetfuel** [comment]
@aturbofly 感謝你的回饋，我們會下一個更新中，把0.14.0 之前版本的導覽行中，把`模型库`隱藏起來。好避免混淆。

**Comment by shanyi15** [comment]
@jetfuel 整理了一下，用户困惑的原因在于：能搜索到0.14.0“排序学习”这篇文档，但在左侧导航栏找不到相应的入口。
    这是因为，对于0.13.0及其以前版本的模型文档，采取了把“模型库”单独成块，例如，在这一页，http://paddlepaddle.org/documentation/models/zh/0.13.0/README.html 点击每一个模型，跳到每个模型的详情页，例如http://paddlepaddle.org/documentation/models/zh/0.13.0/hsigmoid/README.html 。这可能是沿用了之前“模型库”是独立模块的做法，但左侧导航栏并没有展示每一篇文档，用户难免困惑。 
    由于这个逻辑其实依然作用于0.14.0及其以后的版本（只是0.14.0及其以后的左侧导航栏中不再展示单独成块的“模型库”），所以其实0.14.0及其以后的版本中，仍然可以通过搜索引擎，或改链接路径等方式找到这些模型文档，但其实我们并不考虑把这些文档在官网暴露给用户。
    希望能够在0.14.0及其以后的文档中，彻底去掉0.13.0及其以前“模型库”的逻辑，只保留“Fluid”模型库这一入口，并且对于每个模型，点击直接跳转到Github；对于0.13.0及其以前的“模型库”，期望只展示一篇文档，且点击每个模型，跳出官网，链接至Github
    考虑到models repo路径有时会做调整，而Readme的位置是相对稳定的，上述也是一种比较好维护的做法

**Comment by lucywsq** [comment]
您好，鉴于此问题已经解决，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题，我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持!
