### ISSUE TITLE
implement Dataset Reader in Paddle Book

### ISSUE THREAD

**Issue by reyoung** [PaddlePaddle/Paddle#1419]
This issue is a part of #1392.

There are eight books in the current [Paddle Book](https://github.com/paddlepaddle/book). We need to write eight reader creators for each dataset.  There are\:

* 新手入门
* 识别数字
   * http://scikit-learn.org/stable/datasets/ sklearn.dataset
* 图像分类
   * cifar https://www.cs.toronto.edu/~kriz/cifar-10-python.tar.gz
* 词向量
   * By @wangkuiyi 
   * It seems we could use `nltk.corpus.treebank` to fetch the exactly dataset used in Book.
* 情感分析
   * By @wen-bo-yang 
   * The IMDB dataset is not included in `nltk.corpus`, but the Amazon reviews is included. So could we change the dataset used in Book?
* 语义角色标注
   * By @reyoung
   * The book uses CONLL 2005 dataset. The `nltk.corpus` contains `CONLL 2000`, `CONLL 2002`, `CONLL 2007` dataset. Could we changed the dataset into `CONLL 2007`?
* 机器翻译
   * `nltk.corpus` contains `WMT` dataset.
* 个性化推荐

**Comment by wangkuiyi** [comment]
data cache 目录 `/usr/local/paddle/dataset`

**Comment by reyoung** [comment]
> /usr/local/paddle/dataset

这个目录，用户没有root权限就没法写

**Comment by wen-bo-yang** [comment]
我在nltk.corpus中找到了影评资源，内容和IMDB的组织形式差不都，我想是否可以使用这个文本数据做情感分类的数据
```
/nltk_data/corpora/movie_reviews/neg# ls
cv000_29416.txt  cv143_21158.txt .....
/nltk_data/corpora/movie_reviews/pos# ls
cv000_29590.txt  cv143_19666.txt .....
```
