### ISSUE TITLE
hsigmoid预测问题

### ISSUE THREAD

**Issue by wfeagle** [PaddlePaddle/Paddle#14192]
我用hsigmoid作为cost function训练了一个模型(query-->主题)，输出层label是6600个主题，我想将这6600个主题对应的概率**降序排列**取top5对应的主题明文，现在遇到的问题是所有输入query的输出概率都完全一样的，我的方法有什么不对吗？请问应该怎么取?
hsigmoid的结果是：后面是top5的概率完全一样
从万州到深圳的飞机票  0.999997735023	0.999997735023	0.999997735023	0.999997735023	0.999997735023
国家 采购师 0.999997735023	0.999997735023	0.999997735023	0.999997735023	0.999997735023
养森瘦瘦包怎么用 0.999997735023	0.999997735023	0.999997735023	0.999997735023	0.999997735023
治疗女性妇科炎症 0.999997735023	0.999997735023	0.999997735023	0.999997735023	0.999997735023
余姚工作服 0.999997735023	0.999997735023	0.999997735023	0.999997735023	0.999997735023
正常的softmax结果是：
从万州到深圳的飞机票 0.99999320507	1.13317628347e-06	1.04318235117e-06	6.67322581194e-07	4.06154896382e-07
国家 采购师 0.99997651577	9.45519332163e-06	1.61620971539e-06	1.14728959488e-06	7.41304916119e-07
养森瘦瘦包怎么用 0.999954342842	1.66152603924e-05	1.16899636851e-05	7.4703593782e-06	3.92522633774e-06
治疗女性妇科炎症 0.660032451153	0.330115199089	0.0050456430763	0.00182093610056	0.00090728799114
余姚工作服 0.995840251446	0.00190833827946	0.000685566861648	0.000165651319548	0.000122168872622
预测的代码如下：
```python
  if is_infer:
        # hsigmoid
        prediction = paddle.layer.mixed(
                size=class_dim,
                input=paddle.layer.trans_full_matrix_projection(
                    context, param_attr=paddle.attr.Param(name="sigmoid_w")),
                act=paddle.activation.Sigmoid(),
                bias_attr=paddle.attr.Param(name="sigmoid_b"))
        return prediction
    else:
        # label data
        label = paddle.layer.data(name="label",
                                type=paddle.data_type.integer_value(class_dim))

        cost = paddle.layer.hsigmoid(input=context,
                label=label,
                num_classes=class_dim,
                param_attr=paddle.attr.Param(name="sigmoid_w"),
                bias_attr=paddle.attr.Param(name="sigmoid_b"))
        return cost, label
```

取值的代码如下：
```python
def _infer_a_batch(inferer, test_batch, label_reverse_dict, topk):
        result = inferer.infer(input=test_batch, field=["value"])
        assert len(result) == len(test_batch)
        for word, prob in zip(test_batch, result):
            line = word[-1].strip()
            query = line.split(u"\t")[0]
            top_probs_idx = prob.argsort()[-topk:][::-1]
            probs = prob[top_probs_idx].tolist()
```

**Comment by JiabinYang** [comment]
请问您使用的是paddle v2么

**Comment by wfeagle** [comment]
> 请问您使用的是paddle v2么

是的，paddle0.11.0 版本

**Comment by JiabinYang** [comment]
不好意思，因为paddle.v2现在已经没有在维护了，所以请迁移到paddle fluid

**Comment by lucywsq** [comment]
您好，此问题已经超过三周未更新，我们将于今天内关闭，如您遇到问题可随时开启，感谢您对PaddlePaddle的支持！
