### ISSUE TITLE
paddle.fluid.core.EnforceNotMet: Enforce failed. Expected ids_dims[ids_rank - 1] == 1,

### ISSUE THREAD

**Issue by lyp2github** [PaddlePaddle/Paddle#14198]
from utils import logger
import paddle.fluid as fluid
from paddle.fluid.initializer import NormalInitializer
import math

main = fluid.Program()
startup = fluid.Program()
with fluid.program_guard(main, startup):
    left = fluid.layers.data(
         name="left",
         shape=[1],
         dtype='int32',  lod_level=1)
    fc_left = fluid.layers.embedding(input=left, size=[10, 1])
place = fluid.CPUPlace()
exe = fluid.Executor(place)
exe.run(startup)
feeder = fluid.DataFeeder(feed_list=[left], place=place)
score_list = exe.run(main,
                feed=feeder.feed([[[5, 3]],[[2, 6]]]),
                fetch_list=[fc_left],
                return_numpy = False,
          )
print dir(score_list[0])
print score_list[0].lod()
print score_list[0].shape()

**Comment by seiriosPlus** [comment]
embedding加一个is_sparse=False的参数看看？

**Comment by lyp2github** [comment]
解决了，left = fluid.layers.data(
name="left",
shape=[1],
dtype='int64', lod_level=1)

**Comment by panyx0718** [comment]
type改成int64就行了? @seiriosPlus 这个报错信息看看能不能改的更直观一些？

**Comment by panyx0718** [comment]
比如embedding的python入口check一下类型

**Comment by seiriosPlus** [comment]
@panyx0718 可以的，这块我优化一下.
