### ISSUE TITLE
train的时候，cuda比cpu还慢

### ISSUE THREAD

**Issue by LihangLiu** [PaddlePaddle/Paddle#14207]
fluid1.0，模型**inference的时候gpu比cpu快很多**，但是模型**train的时候gpu反而比cpu慢很多**。不知道是什么原因，怎么查？
几个可能有用的信息：
1. 我的fluid1.0是用paddlepaddle/paddle_manylinux_devel:cuda8.0_cudnn5 加上source code成wheel在用pip安装的。
2. inference和train的差别在于train多了back propagation。
3. 跑gpu的时候，nvidia-smi确实打满了。

**Comment by phlrain** [comment]
某些op 在用adam更新的时候 速度特别慢，我们定位下问题

**Comment by phlrain** [comment]
目前在某些特殊的op的时候 adam 比 sgd 慢5倍
![image](https://user-images.githubusercontent.com/43953930/47902316-c8ddd800-debc-11e8-9a43-1da1d246e2ca.png)

**Comment by phlrain** [comment]
post85 会出现这个问题，cuda9，cudnn7 表现正常

**Comment by 333caowei** [comment]
遇到同样的问题
