### ISSUE TITLE
sequence model reshape error.

### ISSUE THREAD

**Issue by chizhizhen** [PaddlePaddle/Paddle#14200]
I read sequence data with "lod_level", where the model_input is a sequence: [frame_nums, feat_dim].
For example, input feature dims are fixed [300, 20], when I send inputs to the model file, the feature dims are changed to [-1, 20].
If I want to reshape model_input to [1, 600], how can I operate on it, since input dims are[-1, 20].

**Comment by seiriosPlus** [comment]
这里的-1是根据batch_size动态调整的

**Comment by chizhizhen** [comment]
> 这里的-1是根据batch_size动态调整的

那我想reshape到固定尺寸，就像上面说的，这个怎么操作呢？

**Comment by seiriosPlus** [comment]
可以去PaddlePaddle Models的REPO里面看一下其他人的模型：
https://github.com/PaddlePaddle/models/search?q=reshape&unscoped_q=reshape
