### ISSUE TITLE
关于paddlepaddle 的rank_loss 

### ISSUE THREAD

**Issue by aturbofly** [PaddlePaddle/Paddle#14204]
请问下：
![image](https://user-images.githubusercontent.com/16451716/47847716-0f70fb00-de07-11e8-8ce4-d2c06ad390d5.png)
![image](https://user-images.githubusercontent.com/16451716/47847731-1992f980-de07-11e8-803c-146850080598.png)
训练一段时间后，我打印出来的avg_loss_value有很多负值：
![image](https://user-images.githubusercontent.com/16451716/47847751-2d3e6000-de07-11e8-91ef-070d53d81788.png)
我想请问下，我的这种情况可能会是什么原因呢？

**Comment by seiriosPlus** [comment]
在打印时候，把输入给rank_loss的left, right, label的值都打印出来吧。

**Comment by aturbofly** [comment]
> 在打印时候，把输入给rank_loss的left, right, label的值都打印出来吧。

我先对loss 求mean。然后增加更多样本后，训练好像正常了。谢谢。
