### ISSUE TITLE
fluid 集群训练报错  meets grpc error:OS Error

### ISSUE THREAD

**Issue by oshixiaoxiliu** [PaddlePaddle/Paddle#14218]
Fri Nov  2 15:37:12 2018[1,133]<stdout>:F1102 15:37:12.763226 49369 grpc_client.cc:295] Get name:[embedding_5.w_0.block70], ep:[10.182.108.31:8000] meets grpc error:OS Error
Fri Nov  2 15:37:12 2018[1,133]<stdout>:*** Check failure stack trace: ***
Fri Nov  2 15:37:12 2018[1,133]<stdout>:    @     0x7f2e104e1bed  google::LogMessage::Fail()
Fri Nov  2 15:37:12 2018[1,133]<stdout>:    @     0x7f2e104e569c  google::LogMessage::SendToLog()
Fri Nov  2 15:37:12 2018[1,133]<stdout>:    @     0x7f2e104e1713  google::LogMessage::Flush()
Fri Nov  2 15:37:12 2018[1,133]<stdout>:    @     0x7f2e104e6bae  google::LogMessageFatal::~LogMessageFatal()
Fri Nov  2 15:37:12 2018[1,133]<stdout>:    @     0x7f2e10d42250  paddle::operators::distributed::GRPCClient::Proceed()
Fri Nov  2 15:37:12 2018[1,133]<stdout>:    @     0x7f2e1d5a28a0  execute_native_thread_routine
Fri Nov  2 15:37:12 2018[1,133]<stdout>:    @     0x7f2ebab691c3  start_thread
Fri Nov  2 15:37:12 2018[1,133]<stdout>:    @     0x7f2eba19112d  __clone
Fri Nov  2 15:37:12 2018[1,133]<stdout>:    @              (nil)  (unknown)

http://10.182.17.162:8900/fileview.html?path=/home/disk1/normandy/maybach/app-user-20181102141927-1728/

对应的机器上找不到报错信息。
经常碰到这个问题，偶尔才能训练成功

**Comment by oshixiaoxiliu** [comment]
集群训练还有这个问题，第一次碰到
http://10.182.80.31:8900/filetree?action=cat&path=/home/disk1/normandy/maybach/app-user-20181102225539-144/workspace/log/user/trainer.log


F1103 03:19:01.741590 43142 grpc_client.cc:348] FetchBarrierRPC name:[FETCH_BARRIER@RECV], ep:[10.182.8.32:8000], status:[-1] meets grpc error, error_code:14 error_message:OS Error error_details:
*** Check failure stack trace: ***
    @     0x7f08ba3b46fd  google::LogMessage::Fail()
    @     0x7f08ba3b81ac  google::LogMessage::SendToLog()
    @     0x7f08ba3b4223  google::LogMessage::Flush()
    @     0x7f08ba3b96be  google::LogMessageFatal::~LogMessageFatal()
    @     0x7f08baeffa41  paddle::operators::distributed::GRPCClient::Proceed()
    @     0x7f08c5fcc8a0  execute_native_thread_routine
    @     0x7f096379a1c3  start_thread
    @     0x7f0962dc212d  __clone
    @              (nil)  (unknown)
.//paddle/start_trainer.sh: line 100: 39389 Aborted

**Comment by oshixiaoxiliu** [comment]
http://10.182.94.156:8900/filetree?action=cat&path=/home/disk1/normandy/maybach/app-user-20181106110625-5091/workspace/log/user/trainer.log

1.1.0 版本 还是grpc的问题

F1106 11:21:26.066817 45262 grpc_client.cc:348] GetRPC name:[sequence_conv_1.w_0.block1], ep:[10.182.85.30:8074], status:[-1] meets grpc error, error_code:14 error_message:OS Error error_details:
*** Check failure stack trace: ***
    @     0x7fb7f206b6fd  google::LogMessage::Fail()
    @     0x7fb7f206f1ac  google::LogMessage::SendToLog()
    @     0x7fb7f206b223  google::LogMessage::Flush()
    @     0x7fb7f20706be  google::LogMessageFatal::~LogMessageFatal()
    @     0x7fb7f2bb6a41  paddle::operators::distributed::GRPCClient::Proceed()
    @     0x7fb7fc26b8a0  execute_native_thread_routine
    @     0x7fb899a391c3  start_thread
    @     0x7fb89906112d  __clone
    @              (nil)  (unknown)

**Comment by jacquesqiao** [comment]
碰到这种问题一般是看节点0 app目录下的汇总的日志，可以看到最早报错的地方，上述日志都不是问题所在地。

**Comment by oshixiaoxiliu** [comment]
http://10.182.5.31:8900/filetree?action=cat&path=/home/disk1/normandy/maybach/app-user-20181109101754-1530/workspace/log/user/trainer.log
http://10.182.5.31:8900/filetree?action=cat&path=/home/disk1/normandy/maybach/app-user-20181109101754-1530/workspace/log/app/train.log

**Comment by oshixiaoxiliu** [comment]
http://10.182.85.161:8900/filetree?action=cat&path=/home/disk1/normandy/maybach/app-user-20181112112801-8267/workspace/log/user/trainer.log

**Comment by jacquesqiao** [comment]
![image](https://user-images.githubusercontent.com/3048612/48549832-da3ad180-e90b-11e8-9ead-f3af9aada219.png)

端口冲突了，这个问题找paddlecloud的同学定位下。

http://10.182.5.31:8900/filetree?action=cat&path=/home/disk1/normandy/maybach/app-user-20181109101754-1530/workspace/log/app/pserver.log

**Comment by panpanli521** [comment]
> 集群训练还有这个问题，第一次碰到
> http://10.182.80.31:8900/filetree?action=cat&path=/home/disk1/normandy/maybach/app-user-20181102225539-144/workspace/log/user/trainer.log
> 
> F1103 03:19:01.741590 43142 grpc_client.cc:348] FetchBarrierRPC name:[FETCH_BARRIER@RECV], ep:[10.182.8.32:8000], status:[-1] meets grpc error, error_code:14 error_message:OS Error error_details:
> *** Check failure stack trace: ***
> @ 0x7f08ba3b46fd google::LogMessage::Fail()
> @ 0x7f08ba3b81ac google::LogMessage::SendToLog()
> @ 0x7f08ba3b4223 google::LogMessage::Flush()
> @ 0x7f08ba3b96be google::LogMessageFatal::~LogMessageFatal()
> @ 0x7f08baeffa41 paddle::operators::distributed::GRPCClient::Proceed()
> @ 0x7f08c5fcc8a0 execute_native_thread_routine
> @ 0x7f096379a1c3 start_thread
> @ 0x7f0962dc212d __clone
> @ (nil) (unknown)
> .//paddle/start_trainer.sh: line 100: 39389 Aborted

@oshixiaoxiliu   请问这个问题解决了吗？
