### ISSUE TITLE
SSD模型训练不能后台执行

### ISSUE THREAD

**Issue by 930083287** [PaddlePaddle/Paddle#14213]
利用paddlepaddle开源的v2版SSD模型，直接利用python train.py正常执行，如果利用nohup python train.py置于后台,就不再运行了，不知道为什么？

**Comment by 930083287** [comment]
1、查看nvidia-smi是否运行；
2、如果正在运行，可以采用python -u train.py

**Comment by phlrain** [comment]
python 有些log是有缓存的，如果用nohup 不会立马打印出来，可以用python -u 启动程序，禁用缓存
