### ISSUE TITLE
求看这个是什么问题

### ISSUE THREAD

**Issue by zhengyandan** [PaddlePaddle/Paddle#14219]
Fri Nov  2 12:34:28 2018[1,0]<stdout>:Node 0, Pass 0, Batch 91600, Train Cost 0.121742330492, {'__auc_evaluator_0__': 0.8770161271095276}
mpirun: killing job...

[yq01-ecom-nova0980-2b0da.yq01.baidu.com:47830] getpeername() failed: Transport endpoint is not connected (107)
[yq01-ecom-nova0980-2b0da.yq01.baidu.com:47830] [[10189,0],0]-[[10189,0],78] mca_oob_tcp_msg_recv: readv from (null) failed: Transport endpoint is not connected (107)
[yq01-ecom-nova0980-2b0da.yq01.baidu.com:47830] oob_tcp_msg.c:392 FATAL

**Comment by jacquesqiao** [comment]
看起来像网络出问题了
