### ISSUE TITLE
raspberry编译paddlepaddle，出现错误fatal error: cpuid.h: No such file or directory

### ISSUE THREAD

**Issue by maxy0524** [PaddlePaddle/Paddle#14229]
有点搞不懂ARM处理器的机器怎么编译paddlepaddle。并最终生成whl的python安装文件。
具体错误如下：
[  6%] Building CXX object paddle/fluid/platform/CMakeFiles/cpu_info.dir/cpu_info.cc.o
In file included from /home/pi/ma/Paddle/paddle/fluid/platform/cpu_info.cc:19:0:
/home/pi/ma/Paddle/build/third_party/install/xbyak/include/xbyak/xbyak_util.h:39:21: fatal error: cpuid.h: No such file or directory
   #include <cpuid.h>
                     ^
compilation terminated.
paddle/fluid/platform/CMakeFiles/cpu_info.dir/build.make:62: recipe for target 'paddle/fluid/platform/CMakeFiles/cpu_info.dir/cpu_info.cc.o' failed
make[2]: *** [paddle/fluid/platform/CMakeFiles/cpu_info.dir/cpu_info.cc.o] Error 1
CMakeFiles/Makefile2:3102: recipe for target 'paddle/fluid/platform/CMakeFiles/cpu_info.dir/all' failed
make[1]: *** [paddle/fluid/platform/CMakeFiles/cpu_info.dir/all] Error 2
Makefile:149: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by velconia** [comment]
https://github.com/PaddlePaddle/paddle-mobile 树莓派上编译可以使用这个 repo 的代码；

**Comment by velconia** [comment]
@allonli 请问关于在树莓派上编译Paddle Fluid, 你可以提供更多的信息吗？

**Comment by xiebaiyuan** [comment]
[paddlemobile树莓派的编译文档](https://github.com/PaddlePaddle/paddle-mobile/blob/develop/doc/development_arm_linux.md)

**Comment by velconia** [comment]
请问还有别的问题吗？

**Comment by velconia** [comment]
请问还有别的问题吗？

**Comment by lucywsq** [comment]
您好，此issue在近一个月内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题，我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持!
