### ISSUE TITLE
Paddle多机作业的端口问题

### ISSUE THREAD

**Issue by yxfGrace** [PaddlePaddle/Paddle#14247]
在paddle的多机作业中，遇到过端口相关的两类报错，麻烦paddle同学帮忙看看分别是什么原因
1. check for SO_REUSEPORT报错
![1](https://user-images.githubusercontent.com/29363426/47994290-d4373a80-e12c-11e8-9c78-8e8db677ac75.jpg)

2. 端口占用问题 
![2](https://user-images.githubusercontent.com/29363426/47994321-e31ded00-e12c-11e8-842c-d20ee685b0ba.jpg)
对于这种端口占用问题，能否后续在日志中打印一下冲突的端口，方便问题排查呢？

**Comment by typhoonzero** [comment]
@yxfGrace 您好，应该线下聊过了，1: `SO_REUSEPORT`为linux内核并不支持端口复用，但并不影响pserver启动。此问题会在最近的版本增加开关，后续版本用户可以指定默认关闭端口复用。2: 冲突的端口可以从日志中的环境变量查看，用户也可以从python程序中打印os.environ查看

**Comment by lucywsq** [comment]
您好，若此issue已经解决，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题，
我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持!
