### ISSUE TITLE
fluid网络训练最后一层nce，CAPI预测的时候，怎么取出nce前面一层输出

### ISSUE THREAD

**Issue by ShadowSkyLiu** [PaddlePaddle/Paddle#14245]
```python
def network():

   fc_1 = fluid.layers.fc(
            name="Relu1",
            input=vec, #[lstm_last, uid_emb, city_emb, phone_emb, max_emb_cats, max_emb_tags],
            size=256,
            act='relu')
    fc = fluid.layers.fc(
            name="Relu2",
            input=fc_1,
            size=31,
            act='relu')
    w_param = fluid.default_main_program().global_block().create_parameter(
        shape=[nid_dict_size, 31], dtype='float32', name='nce_w')
    b_param = fluid.default_main_program().global_block().create_parameter(
        shape=[nid_dict_size, 1], dtype='float32', name='nce_b')
    if is_train:
        cost = fluid.layers.nce(
            input=fc,
            label=next_id,
            num_total_classes=nid_dict_size,
            param_attr=fluid.ParamAttr(name="nce_w"),
            bias_attr=fluid.ParamAttr(name="nce_b"),
            num_neg_samples=5)
        return cost
    else:  
        fc_3_trans = fluid.layers.transpose(
            fluid.layers.matmul(x=fc, y=w_param, transpose_y=True), perm=[1, 0]) + b_param
        prediction = fluid.layers.softmax(
            fluid.layers.transpose(fc_3_trans, perm=[1, 0]))
        return prediction
```

——————————————————————-
请问使用CAPI预测的时候，怎样能取出 fc 的输出

**Comment by luotao1** [comment]
使用`fluid.io.save_inference_model`来保存模型，会裁剪掉cost。请参考[预测引擎](http://www.paddlepaddle.org/documentation/api/zh/1.1/api_guides/low_level/inference.html)文档。

**Comment by ShadowSkyLiu** [comment]
1. save_inference_model会裁剪掉cost，但是我最后nce那层的参数(nce_w、nce_b)是需要的？所以不能使用save_inference_model？
2.问一下CAPI怎么加载模型，并取出fc那一层的输出呢？

**Comment by luotao1** [comment]
> 但是我最后nce那层的参数(nce_w、nce_b)是需要的

看配置，是在`is_train=True`的时候才需要。预测的时候本身就没走这步，为什么还需要呢？

> 问一下CAPI怎么加载模型，并取出fc那一层的输出呢

用`save_inference_model`保存后，参考http://www.paddlepaddle.org/documentation/docs/zh/1.1/user_guides/howto/inference/native_infer.html

**Comment by ShadowSkyLiu** [comment]
is_train=True的时候会训练nce_w，线上预测的时候：1. 首先会离线取出nce_w和nce_b当成输入数据的高维编码，这里的nce参数是有含义的；2. 然后线上输入预测的数据，得到fc这一层的输出，再跟nce_w和nce_b做内积，取出nce_w对应内积较大的列

**Comment by luotao1** [comment]
是否可以：
1. 用save_inference_model存下来的模型，可以在C++预测的时候得到fc输出
2. 把fc输出，和离线存下来的nce_w/b再做内积。

**Comment by ShadowSkyLiu** [comment]
save_inference_model不是只能到fc这一层么？怎么能保存nce_w/b呢

**Comment by luotao1** [comment]
nce_w/b是python端离线存下来的，用`fluid.io.save_params`:http://www.paddlepaddle.org/documentation/api/zh/1.1/api_guides/low_level/model_save_reader.html

**Comment by ShadowSkyLiu** [comment]
也就是我既要save_inference_model，又有save_params?

**Comment by luotao1** [comment]
是的。因为nce_w/b是你额外要计算的一步。

**Comment by ShadowSkyLiu** [comment]
这不算额外的计算吧，save_params的时候已经把所有的params保存下来了，为什么不能按照网络重新走一遍得到fc呢？

**Comment by luotao1** [comment]
预测模型里是没有cost的，因此只能获得fc的值。所以fc和nce的计算是额外的一步。

**Comment by ShadowSkyLiu** [comment]
那我如果做pre_train，要固定上面fc1那一层呢？只训练fc和nce后面两层呢，需要保存三次？

**Comment by Xreki** [comment]
@ShadowSkyLiu 

> save_inference_model不是只能到fc这一层么？怎么能保存nce_w/b呢

`save_inference_model`并不是只能到`fc`这一层，`target_vars`可以设定为`nce`的输出，也可以同时将`fc`和`nce`的输出都设置为`target_vars`。只是你使用`save_inference_model`保存下来的模型时，明确地知道这个模型的配置。

https://github.com/PaddlePaddle/Paddle/blob/1f4a4343022c97fa813dc051f53298912bda520a/python/paddle/fluid/io.py#L544-L551

**Comment by lucywsq** [comment]
您好，鉴于此问题已经解决，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题，我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持
