### ISSUE TITLE
fluid infer

### ISSUE THREAD

**Issue by shiyazhou121** [PaddlePaddle/Paddle#14246]
求问：fluid的python预测，data是序列数据，结果报错。
![image](https://user-images.githubusercontent.com/15082798/47991217-86b6cf80-e124-11e8-8685-c86bb1846379.png)
![image](https://user-images.githubusercontent.com/15082798/47991268-a3530780-e124-11e8-94aa-108a9b004c86.png)

**Comment by sneaxiy** [comment]
embedding参数保存错误，建议检查下embedding table是否保存成功

**Comment by shiyazhou121** [comment]
@sneaxiy 这个写法有问题吗。。因为我用c++库预测没有报类似的问题，所以我觉得可能是我的代码有问题。。

**Comment by sneaxiy** [comment]
@shiyazhou121 是scope未指定的问题。您加载inference_model时用的是一个新建的scope，在run的时候也需要指定该scope。

**Comment by shiyazhou121** [comment]
@sneaxiy 确实是这个原因，谢谢了。另外想问下，如果我想定义一个全局的scope，应该怎么在函数里获得，比如下面的场景，应该怎么让scope一致?
exe = fluid.Executor(place)
with fluid.scope_guard(inference_scope):
    [inference_program, feed_target_names, fetch_targets] = fluid.io.load_inference_model(save_dirname, exe)

def a():
    results = exe.run(inference_program,
            feed={feed_target_names[0]: x},
            fetch_list=fetch_targets,
            return_numpy=True)

**Comment by sneaxiy** [comment]
将inference_scope记录下来，在调用`exe.run()`时加上`with fluid.scope_guard(inference_scope):`。即：

```
inference_scope = fluid.core.Scope()

with fluid.scope_guard(inference_scope):
    [inference_program, feed_target_names, fetch_targets] = fluid.io.load_inference_model(save_dirname, exe)

......

def a():
    with fluid.scope_guard(inference_scope):
        results = exe.run(inference_program, feed={feed_target_names[0]: x}, fetch_list=fetch_targets, return_numpy=True)
```

**Comment by shiyazhou121** [comment]
@sneaxiy 多谢解答
