### ISSUE TITLE
MobileNet-v1 accuracy on ImageNet

### ISSUE THREAD

**Issue by wojtuss** [PaddlePaddle/Paddle#14249]
@luotao1 , using the model from @hshen14 (https://github.com/PaddlePaddle/Paddle/issues/14074) we get top1 accuracy 70.43 % (on CPU, batchsize 50, without optimizations as well as with MKL-DNN and optimizations) on the full validation ImageNet dataset. Is it acceptable for Baidu?

**Comment by hshen14** [comment]
looks good，mine are 70.87% with transpiler fusion enabled，batchsize 50

**Comment by wojtuss** [comment]
@hshen14 , thanks!
