### ISSUE TITLE
单机单卡可以使用ParallelExecutor加速训练吗 

### ISSUE THREAD

**Issue by zzhzz** [PaddlePaddle/Paddle#14253]
在GPU环境下，只有单机单卡的话可以使用ParallelExecutor加速训练模型吗？例如设置num_trainers = 4之类的

**Comment by chengduoZH** [comment]
> 只有单机单卡的话可以使用ParallelExecutor加速训练模型吗？

相比于Executor，ParallelExecutor在执行策略上做一些改动，比如operator是乱序执行，即如果多个Op的输入互不依赖，这些op在ParallelExecutor里面可以并发执行，所以单机单卡下ParallelExecutor是否能够加速模型训练与模型的结构相关。

ParallelExecutor是为多卡设计的，所以如果只有一个卡，那么num_trainers就只能是1.

**Comment by 333caowei** [comment]
```ParallelExecutor是为多卡设计的```
请问如果是mpi cpu训练的的话，ParallelExecutor有意义吗？
@chengduoZH

**Comment by chengduoZH** [comment]
@333caowei 目前分布式用ParallelExecutor执行时，通过MPI进行通信的情况还没有正式测试，后续会有相关测试和发布。
