### ISSUE TITLE
fluid c++预测与python api预测结果不一样。

### ISSUE THREAD

**Issue by shiyazhou121** [PaddlePaddle/Paddle#14266]
模型是文本的一维序列数据，但两个预测结果不一样，不确定是哪个有问题。
以下是python的配置
![image](https://user-images.githubusercontent.com/15082798/48045502-8c1b2500-e1cb-11e8-862d-bd37d4fdf4e1.png)
以下是c++的预测配置
![image](https://user-images.githubusercontent.com/15082798/48045530-a81ec680-e1cb-11e8-8de9-df785d1df11a.png)
输入数据均是1, 2, 3, 4
python预测结果
![image](https://user-images.githubusercontent.com/15082798/48045668-40b54680-e1cc-11e8-8379-76a78c024191.png)
C++预测结果
![image](https://user-images.githubusercontent.com/15082798/48045590-eae09e80-e1cb-11e8-9c4c-c9cadee3b61f.png)

**Comment by tensor-tang** [comment]
首先感谢您做了如此细致的对比。
几个小问题：
1. 可否在适当的位置在打印出输入数据，以保证输入确实一样。
2. C++预测端可以尝试用`TensorAssignData`试下。可以参考

https://github.com/PaddlePaddle/Paddle/blob/8fc05e0373bb481e36b53c650f2dc00acf1b32a5/paddle/fluid/inference/tests/api/analyzer_lac_tester.cc#L99-L106

**Comment by shiyazhou121** [comment]
@tensor-tang 确实是输入数据的问题，在C++预测时，我使用\t切分数据，，应该用空格切分，改变后输出就一致了，谢谢了。
