### ISSUE TITLE
v2版SSD模型在CPU时预测报错

### ISSUE THREAD

**Issue by 930083287** [PaddlePaddle/Paddle#14261]
报错信息：Check failed: useGpu_ CudnnPoolLayer only support gpu

**Comment by tensor-tang** [comment]
从报错信息上看，你是走到了Cudnn的Pool实现，但是由于这个是只支持gpu的，在cpu上应该是没开启GPU。如果是纯CPU跑，那么应该是哪里配置错误导致进入了CudnnPool这个layer。

**Comment by 930083287** [comment]
paddle.inference.Inference() 经查是这个函数出错的，我应该如何去更改不进入CudnnPool的layer？

**Comment by tensor-tang** [comment]
可否提供完整的log信息，以及相应的配置。
在这个paddle.inference.Inference() 函数出错，不一定是这个函数里面有问题，也有可能是使用不当。
或者您可以参考下使用流程 http://paddlepaddle.org/documentation/docs/zh/0.12.0/howto/capi/workflow_of_capi_cn.html

**Comment by tensor-tang** [comment]
在这个paddle.inference.Inference() 函数出错，不一定是这个函数里面有问题，也有可能是使用不当

**Comment by tensor-tang** [comment]
经过线下沟通发现是 https://github.com/PaddlePaddle/models/blob/develop/legacy/ssd/vgg_ssd_net.py#L65 这里显示指定使用cudnnlayer，所以在cpu上跑会出错。

**Comment by tensor-tang** [comment]
@qingqing01 请问下我们SSD这个模型在v2上支持CPU only上跑吗

**Comment by tensor-tang** [comment]
经过沟通，去掉pool_type即可解决问题。

建议迁移到新版本Fluid。
