### ISSUE TITLE
fluid 1.1.0 的unifrom_random op存在异常

### ISSUE THREAD

**Issue by zenghsh3** [PaddlePaddle/Paddle#14279]
fluid.layers.uniform_random(shape=[1])执行抛出异常：

for name in locals_var:
RuntimeError: dictionary changed size during iteration

**Comment by tensor-tang** [comment]
麻烦您提供稍微详细点的log吧。

抛出异常肯定是有原因的。

我本地试了下 `y=fluid.layers.uniform_random(shape=[1])` 这样是可以的

**Comment by zenghsh3** [comment]
修改源码paddle/fluid/layers/ops.py中67行代码为下面即可：
for name in list(locals_var):

**Comment by tensor-tang** [comment]
我在1.1.0上面也试了下：
![image](https://user-images.githubusercontent.com/21351065/48063796-0ca84880-e201-11e8-82e7-5b6820423f69.png)

**Comment by zenghsh3** [comment]
不过我是在python3.5环境下的fluid，有可能是python3版本的有问题？

**Comment by tensor-tang** [comment]
哦，有可能，我是在Python27下。
