### ISSUE TITLE
本地编译Paddle  1.0.0失败

### ISSUE THREAD

**Issue by 352174109** [PaddlePaddle/Paddle#14272]
报错为
[  8%] Built target memory Scanning dependencies of target profiler_py_proto_init
[  8%] Built target profiler_py_proto_init paddle/fluid/platform/CMakeFiles/profiler_py_proto.dir/build.make:60: *** target attern contains no `%'.  Stop.
make[1]: *** [paddle/fluid/platform/CMakeFiles/profiler_py_proto.dir/all] Error

**Comment by tensor-tang** [comment]
请问您的cmake 选项是什么，gcc， cmake 等版本是什么，能否提供稍微完整的出错信息。

或者您可以参考编译文档 http://paddlepaddle.org/documentation/docs/zh/1.1/beginners_guide/install/compile/fromsource.html 

推荐在docker下编译，可以保证环境配置的一致性。

**Comment by 352174109** [comment]
cmake -DCMAKE_BUILD_TYPE=Release -DWITH_MKLDNN=OFF -DWITH_GPU=OFF -DWITH_FLUID_ONLY=ON ..
cmake版本3.13.0
gcc版本4.8.5
docker下也编译不过去
操作系统centos7.5

**Comment by 352174109** [comment]
> cmake -DCMAKE_BUILD_TYPE=Release -DWITH_MKLDNN=OFF -DWITH_GPU=OFF -DWITH_FLUID_ONLY=ON ..
> cmake版本3.13.0
> gcc版本4.8.5
> docker下也编译不过去
> 操作系统centos7.5

[nohup.txt](https://github.com/PaddlePaddle/Paddle/files/2555853/nohup.txt)

**Comment by tensor-tang** [comment]
您可以在最新的develop编译吗，我们没法复现您的问题。但是猜测还是环境问题。

您用的是paddlepaddle/paddle:latest-dev这个docker镜像吗。

**Comment by 352174109** [comment]
好吧 我试试这个镜像

**Comment by 352174109** [comment]
多谢 使用这个docker镜像编译通过了

**Comment by tensor-tang** [comment]
好的，那我close了

**Comment by tensor-tang** [comment]
@352174109 我在mac上源码编译复现你的问题了，原因是protobuf的版本问题，需要换为3.1。

**Comment by 352174109** [comment]
好的 多谢
