### ISSUE TITLE
paddle由0.15.0升级为1.1.0后，同一脚本在本地训练读取数据报core

### ISSUE THREAD

**Issue by LoveGarden** [PaddlePaddle/Paddle#14275]
错误信息：
INFO:get the reader function obj
INFO:read data from [/home/users/luojianhui/paddle/script/data.0]
INFO:start train
*** Aborted at 1541491850 (unix time) try "date -d @1541491850" if you are using GNU date ***
PC: @                0x0 (unknown)
*** SIGILL (@0x7fcde3d374e9) received by PID 23768 (TID 0x7fce09f16700) from PID 18446744073236870377; stack trace: ***
INFO:read data from [/home/users/luojianhui/paddle/script/data.1]
    @     0x7fce096cd160 (unknown)
    @     0x7fcde3d374e9 paddle::operators::reader::BufferedReader::BufferedReader()
    @     0x7fcde3437f26 paddle::operators::reader::CreateDoubleBufferReaderOp::RunImpl()
    @     0x7fcde3f2ab58 paddle::framework::OperatorBase::Run()
    @     0x7fcde33790fb paddle::framework::Executor::RunPreparedContext()
    @     0x7fcde3379ee0 paddle::framework::Executor::Run()
    @     0x7fcde329a8bd _ZZN8pybind1112cpp_function10initializeIZN6paddle6pybindL13pybind11_initEvEUlRNS2_9framework8ExecutorERKNS4_11ProgramDescEPNS4_5ScopeEibbE63_vIS6_S9_SB_ibbEINS_4nameENS_9is_methodENS_7siblingEEEEvOT_PFT0_DpT1_EDpRKT2_ENUlRNS_6detail13function_callEE1_4_FUNEST_
    @     0x7fcde32eacb4 pybind11::cpp_function::dispatcher()
    @     0x7fce099e6bb8 PyEval_EvalFrameEx
    @     0x7fce099ea0bd PyEval_EvalCodeEx
    @     0x7fce099e7345 PyEval_EvalFrameEx
    @     0x7fce099e7460 PyEval_EvalFrameEx
    @     0x7fce099e7460 PyEval_EvalFrameEx
    @     0x7fce099ea0bd PyEval_EvalCodeEx
    @     0x7fce099ea1f2 PyEval_EvalCode
    @     0x7fce09a12f42 PyRun_FileExFlags
    @     0x7fce09a142d9 PyRun_SimpleFileExFlags
    @     0x7fce09a2a00d Py_Main
    @     0x7fce08c27bd5 __libc_start_main
    @           0x4007a1 (unknown)
    @                0x0 (unknown)
Illegal instruction (core dumped)

**Comment by tensor-tang** [comment]
这是因为您的机器不支持AVX2导致的，在最新的develop当中已经解决该问题，但是发版还有段时间。

目前的解决办法是在您本地的机器上源码编译paddle并安装即可。

给你造成了不便深表歉意。

 [这里](http://paddlepaddle.org/documentation/docs/zh/1.1/beginners_guide/install/compile/compile_Ubuntu.html)有源码编译的doc。
