### ISSUE TITLE
paddle should cache the kill signal it recived and log it out for debugging

### ISSUE THREAD

**Issue by jacquesqiao** [PaddlePaddle/Paddle#14288]
最近出现一些集群上任务挂掉，日志里边只能看到double free的问题，费了很多时间定位paddle自己是不是有问题，后来定位到是被集群的优先级管理系统给kill掉了，所以paddle 如果被外部kill 应该抛个日志抱怨一下，方便定位问题。

**Comment by typhoonzero** [comment]
如果能复现pserver 被kill的时候报double free，可以处理下这个signal，使其graceful shutdown，并记录收到了这个signal的日志，减少用户的费解
