### ISSUE TITLE
Which method in paddle is similar to SubpixelConv2d in tensorlayer?

### ISSUE THREAD

**Issue by toddwyl** [PaddlePaddle/Paddle#14282]
When I reimplement SRGAN, I want a method like SubpixelConv2d?
Can the BilinearInitializer help? 
Or what can help me to implement this layers?
[tensorlayer]https://tensorlayer.readthedocs.io/en/stable/_modules/tensorlayer/layers/convolution/super_resolution.html#SubpixelConv2d

**Comment by NHZlX** [comment]
@wanghaoshuang Does paddle support the SubpixelConv2d op?

**Comment by wanghaoshuang** [comment]
`SubpixelConv2d` is not supported in paddle currently.

**Comment by lucywsq** [comment]
您好，此功能已经被记录，我们将努力早日完善。此问题已经超过1个月未更新，我们将于今天内关闭，如您有问题可随时开启，感谢您对PaddlePaddle的支持。
