### ISSUE TITLE
How to set a 2-dimensional vector to input_types?

### ISSUE THREAD

**Issue by 17Skye17** [PaddlePaddle/Paddle#1430]
I want to input a 30*50 matrix to data_layer like [[......],[......],[......],......] , but after I set settings.input_type as below , there occurs an error.

`
settings.input_types = [dense_vector(30,seq_type=SequenceType.SEQUENCE),dense_vector(50,seq_type=SequenceType.SEQUENCE)]`

I'd be very grateful if anyone can help.

**Comment by Canpio** [comment]
Close this issue due to inactivity. please feel free to reopen it if more information is available
