### ISSUE TITLE
Any example code related to distributed training using ParallelExecutor()? 

### ISSUE THREAD

**Issue by TheodoreG** [PaddlePaddle/Paddle#14318]
Is there any example code related to distributed training using ParallelExecutor()? 
I found an example using normal exe in  http://www.paddlepaddle.org/documentation/docs/zh/1.0/user_guides/howto/training/cluster_quick_start.html

**Comment by JiabinYang** [comment]
请参见：https://github.com/PaddlePaddle/models/blob/develop/fluid/PaddleCV/image_classification/dist_train/dist_train.py
