### ISSUE TITLE
paddle 1.1版本docker镜像没有python3

### ISSUE THREAD

**Issue by flyhighzy** [PaddlePaddle/Paddle#14311]
使用镜像：paddlepaddle/paddle:1.10-gpu-cuda8.0-cudnn7
镜像中未发现python3可执行文件和相关依赖包，希望能添加一下

**Comment by JiabinYang** [comment]
感谢反馈，请在下个版本中添加相关解决方案 @velconia

**Comment by velconia** [comment]
这是生产环境的镜像，不是开发环境的镜像，我们会为生产环境单独 generate 出一套新的镜像
