### ISSUE TITLE
paddle.fluid.core.EnforceNotMet: internal error in RPCClient at [/paddle/paddle/fluid/operators/send_barrier_op.cc:47

### ISSUE THREAD

**Issue by lyp2github** [PaddlePaddle/Paddle#14319]
cloud平台提交：job-e6c5be28ea3cce79&flag=jobs&groupName=off_smart
paddle-fluid-v1.0.0版本
E1108 02:44:05.118659 25384 grpc_client.cc:280] Send name:[fc_1.b_0@GRAD.trainer_0], ep:[10.75.68.37:8000], status:[-1] meets grpc error:Deadline Exceeded
E1108 02:44:05.119359 25384 grpc_client.cc:280] Send name:[fc_1.w_0@GRAD.block1.trainer_0], ep:[10.73.91.52:8000], status:[-1] meets grpc error:Deadline Exceeded
E1108 02:44:05.119462 25384 grpc_client.cc:280] Send name:[fc_1.w_0@GRAD.block2.trainer_0], ep:[10.73.98.13:8000], status:[-1] meets grpc error:Deadline Exceeded
E1108 02:44:05.119549 25384 grpc_client.cc:280] Send name:[fc_1.w_0@GRAD.block0.trainer_0], ep:[10.73.91.44:8000], status:[-1] meets grpc error:Deadline Exceeded
E1108 02:44:05.119633 25384 grpc_client.cc:280] Send name:[fc_1.w_0@GRAD.block3.trainer_0], ep:[10.73.34.25:8000], status:[-1] meets grpc error:Deadline Exceeded
E1108 02:44:05.146458 25384 grpc_client.cc:280] Send name:[fc_0.b_0@GRAD.trainer_0], ep:[10.75.68.45:8000], status:[-1] meets grpc error:Deadline Exceeded
E1108 02:44:05.170817 25384 grpc_client.cc:280] Send name:[fc_0.w_0@GRAD.block2.trainer_0], ep:[10.73.34.18:8000], status:[-1] meets grpc error:Deadline Exceeded
E1108 02:44:05.179358 25384 grpc_client.cc:280] Send name:[fc_0.w_0@GRAD.block0.trainer_0], ep:[10.75.68.38:8000], status:[-1] meets grpc error:Deadline Exceeded
E1108 02:44:05.183396 25384 grpc_client.cc:280] Send name:[fc_0.w_0@GRAD.block1.trainer_0], ep:[10.75.68.36:8000], status:[-1] meets grpc error:Deadline Exceeded
E1108 02:44:05.183454 25384 grpc_client.cc:280] Send name:[fc_0.w_0@GRAD.block3.trainer_0], ep:[10.73.91.36:8000], status:[-1] meets grpc error:Deadline Exceeded
E1108 02:44:05.183503 25384 grpc_client.cc:280] Send name:[fc_0.w_0@GRAD.block4.trainer_0], ep:[10.73.91.50:8000], status:[-1] meets grpc error:Deadline Exceeded
E1108 02:44:05.183550 25384 grpc_client.cc:280] Send name:[fc_0.w_0@GRAD.block5.trainer_0], ep:[10.73.83.16:8000], status:[-1] meets grpc error:Deadline Exceeded
E1108 02:44:05.196419 25384 grpc_client.cc:280] Send name:[fc_img.b_0@GRAD.trainer_0], ep:[10.73.91.38:8000], status:[-1] meets grpc error:Deadline Exceeded
E1108 02:44:05.201006 25384 grpc_client.cc:280] Send name:[fc_img.w_0@GRAD.block1.trainer_0], ep:[10.73.91.47:8000], status:[-1] meets grpc error:Deadline Exceeded
E1108 02:44:05.206399 25384 grpc_client.cc:280] Send name:[fc_img.w_0@GRAD.block3.trainer_0], ep:[10.75.68.23:8000], status:[-1] meets grpc error:Deadline Exceeded
E1108 02:44:05.221465 25384 grpc_client.cc:280] Send name:[fc_img.w_0@GRAD.block2.trainer_0], ep:[10.73.98.14:8000], status:[-1] meets grpc error:Deadline Exceeded
E1108 02:44:05.221554 25384 grpc_client.cc:280] Send name:[fc_img.w_0@GRAD.block0.trainer_0], ep:[10.73.34.14:8000], status:[-1] meets grpc error:Deadline Exceeded
Traceback (most recent call last):
  File "train.py", line 212, in <module>
    train(is_local=False)
  File "train.py", line 208, in train
    train_loop(t.get_trainer_program())
  File "train.py", line 131, in train_loop
    feed=feeder.feed(data)
  File "/home/disk1/normandy/maybach/app-user-20181107150817-6162/workspace/python27-gcc482/lib/python2.7/site-packages/paddle/fluid/executor.py", line 470, in run
    self.executor.run(program.desc, scope, 0, True, True)
paddle.fluid.core.EnforceNotMet: internal error in RPCClient at [/paddle/paddle/fluid/operators/send_barrier_op.cc:47]
PaddlePaddle Call Stacks:

**Comment by frankwhzhang** [comment]
我也遇到了同样的错误, 提交版本是fluid1.1

**Comment by typhoonzero** [comment]
trainer端超时，可能是server挂了，看下server端的日志呢

**Comment by lucywsq** [comment]
您好，此issue在近三周内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题，我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持
