### ISSUE TITLE
paddle有已经训练好的VGG19模型吗？

### ISSUE THREAD

**Issue by toddwyl** [PaddlePaddle/Paddle#14329]
paddle有已经训练好的VGG19模型吗？
找了一下并没有发现有VGG的

**Comment by JiabinYang** [comment]
您好，PaddlePaddle目前没有提供训练好的VGG19的模型，[这里](https://github.com/PaddlePaddle/models/blob/develop/fluid/PaddleCV/image_classification/models/vgg.py)有VGG的模型实现代码，您可以根据自己的需求训练

**Comment by toddwyl** [comment]
> 您好，PaddlePaddle目前没有提供训练好的VGG19的模型，[这里](https://github.com/PaddlePaddle/models/blob/develop/fluid/PaddleCV/image_classification/models/vgg.py)有VGG的模型实现代码，您可以根据自己的需求训练

那可以从caffe的预训练模型转成fluid吗？这样可行吗？

**Comment by JiabinYang** [comment]
您可以参考这个使用https://github.com/PaddlePaddle/models/tree/develop/fluid/PaddleCV/image_classification/caffe2fluid

**Comment by toddwyl** [comment]
> 您可以参考这个使用https://github.com/PaddlePaddle/models/tree/develop/fluid/PaddleCV/image_classification/caffe2fluid

OK，已经成功转换过来了，在此处放下链接
https://github.com/strawsuper/vgg19_paddlepaddle
方便以后的同学直接使用！:+1:

**Comment by JiabinYang** [comment]
非常感谢！
