### ISSUE TITLE
Failed to download conll05 dataset

### ISSUE THREAD

**Issue by xuzhenglei1991** [PaddlePaddle/Paddle#14322]
Failed to download conll05 dataset. After checking paddle source code, I find that the url given in the source codes are failed to open. The detail source codes are as follows：

dir：/usr/local/lib/python2.7/dist-packages/paddle/dataset/conll05.py

DATA_URL = 'http://www.cs.upc.edu/~srlconll/conll05st-tests.tar.gz'
DATA_MD5 = '387719152ae52d60422c016e92a742fc'
WORDDICT_URL = 'http://paddlepaddle.bj.bcebos.com/demo/srl_dict_and_embedding/wordDict.txt'
WORDDICT_MD5 = 'ea7fb7d4c75cc6254716f0177a506baa'
VERBDICT_URL = 'http://paddlepaddle.bj.bcebos.com/demo/srl_dict_and_embedding/verbDict.txt'
VERBDICT_MD5 = '0d2977293bbb6cbefab5b0f97db1e77c'
TRGDICT_URL = 'http://paddlepaddle.bj.bcebos.com/demo/srl_dict_and_embedding/targetDict.txt'
TRGDICT_MD5 = 'd8c7f03ceb5fc2e5a0fa7503a4353751'
EMB_URL = 'http://paddlepaddle.bj.bcebos.com/demo/srl_dict_and_embedding/emb'
EMB_MD5 = 'bf436eb0faa1f6f9103017f8be57cdb7'

**Comment by JiabinYang** [comment]
我看了下，0.14.0的这个dataset的link确实失效了，请使用最新版本的paddlepaddle，最新版本中的地址在[这里](https://github.com/PaddlePaddle/Paddle/blob/release/1.1/python/paddle/dataset/conll05.py)
