### ISSUE TITLE
paddle单机训练报错Aborted (core dumped)

### ISSUE THREAD

**Issue by mengyiliu22** [PaddlePaddle/Paddle#14347]
F1109 12:18:23.650521  4435 Vector.h:131] Check failed: start < src.size_ (48 vs. 48)
*** Check failure stack trace: ***
    @     0x7f0cdb721f2d  google::LogMessage::Fail()
    @     0x7f0cdb7259dc  google::LogMessage::SendToLog()
    @     0x7f0cdb721a53  google::LogMessage::Flush()
    @     0x7f0cdb726eee  google::LogMessageFatal::~LogMessageFatal()
F1109 12:18:23.652926  4434 Vector.h:131] Check failed: start < src.size_ (12288 vs. 7936) F*** Check failure stack trace: ***
F1109 12:18:23.652926  4434 Vector.h:131] Check failed: start < src.size_ (12288 vs. 7936) F1109 12:18:23.652927  4431 Vector.h:131] Check failed: start + size <= src.size_ (8192 vs. 7936) F1109 12:18:23.652927  4433 Vector.h:131] Check failed: start < src.size_ (10240 vs. 7936)
*** Check failure stack trace: ***
F1109 12:18:23.652926  4434 Vector.h:131] Check failed: start < src.size_ (12288 vs. 7936) F1109 12:18:23.652927  4431 Vector.h:131] Check failed: start + size <= src.size_ (8192 vs. 7936) F1109 12:18:23.652927  4433 Vector.h:131] Check failed: start < src.size_ (10240 vs. 7936)
*** Check failure stack trace: ***
F1109 12:18:23.652926  4434 Vector.h:131] Check failed: start < src.size_ (12288 vs. 7936) F1109 12:18:23.652927  4431 Vector.h:131] Check failed: start + size <= src.size_ (8192 vs. 7936) F1109 12:18:23.652927  4433 Vector.h:131] Check failed: start < src.size_ (10240 vs. 7936) F1109 12:18:23.653033  4432 Vector.h:131] Check failed: start < src.size_ (8192 vs. 7936)
*** Check failure stack trace: ***
    @     0x7f0cdb7f47cb  paddle::SgdThreadUpdater::threadUpdateDense()
    @     0x7f0cdb721f2d  google::LogMessage::Fail()
    @     0x7f0cdb721f2d  google::LogMessage::Fail()
    @     0x7f0cdb721f2d  google::LogMessage::Fail()
    @     0x7f0cdb721f2d  google::LogMessage::Fail()
    @     0x7f0cdb7f585f  _ZNSt17_Function_handlerIFvimEZN6paddle16SgdThreadUpdater11finishBatchEfEUlimE_E9_M_invokeERKSt9_Any_dataim
    @     0x7f0cdb7259dc  google::LogMessage::SendToLog()
    @     0x7f0cdb7259dc  google::LogMessage::SendToLog()
    @     0x7f0cdb7259dc  google::LogMessage::SendToLog()
    @     0x7f0cdb7259dc  google::LogMessage::SendToLog()
    @     0x7f0cdb68e59c  _ZNSt6thread5_ImplISt12_Bind_simpleIFZN6paddle14SyncThreadPool5startEvEUliE_mEEE6_M_runEv
    @       0x318eab6470  (unknown)
    @       0x318b207851  (unknown)
    @       0x318aee767d  (unknown)
    @     0x7f0cdb721a53  google::LogMessage::Flush()
    @     0x7f0cdb721a53  google::LogMessage::Flush()
    @     0x7f0cdb721a53  google::LogMessage::Flush()
    @     0x7f0cdb721a53  google::LogMessage::Flush()
    @     0x7f0cdb726eee  google::LogMessageFatal::~LogMessageFatal()
    @     0x7f0cdb726eee  google::LogMessageFatal::~LogMessageFatal()
    @     0x7f0cdb726eee  google::LogMessageFatal::~LogMessageFatal()
    @     0x7f0cdb726eee  google::LogMessageFatal::~LogMessageFatal()
    @              (nil)  (unknown)

**Comment by wzzju** [comment]
您好！Label要从0开始，比如10分类，label是 0-9。

**Comment by mengyiliu22** [comment]
> 您好！Label要从0开始，比如10分类，label是 0-9。

字典编码我检查了一下，是从0开始的。

**Comment by wzzju** [comment]
用户本打算重新训练，字典都是新的，与加载的老模型字典没有对上，现在问题已经解决。
