### ISSUE TITLE
主模块PB版本与paddlepaddle的PB版本冲突问题

### ISSUE THREAD

**Issue by chenguoliang1990** [PaddlePaddle/Paddle#14343]
1.主模块需要依赖CONFIGS('third-64/protobuf@protobuf_3-2-0-6274_PD_BL') 版本
2.主模块依赖了CONFIGS('baidu/paddlepaddle/paddle@release_prebuilt_cpu_avx_mkl@git_branch') 
3.主模块编译的时候报了PB相关的错误：
  framework.pb.cc:(.text+0x1d0c): undefined reference to `google::protobuf::io::CodedOutputStream::VarintSize32Fallback(unsigned int)'
framework.pb.cc:(.text+0x1d21): undefined reference to `google::protobuf::io::CodedOutputStream::VarintSize32Fallback(unsigned int)'
baidu/paddlepaddle/paddle/paddle/lib/libpaddle_fluid.a(framework.pb.cc.o): In function `paddle::framework::proto::VarType_ReaderDesc::ByteSizeLong() const':
framework.pb.cc:(.text+0x1d7b): undefined reference to `google::protobuf::io::CodedOutputStream::VarintSize32Fallback(unsigned int)'
baidu/paddlepaddle/paddle/paddle/lib/libpaddle_fluid.a(framework.pb.cc.o): In function `paddle::framework::proto::VarType_LoDTensorArrayDesc::ByteSizeLong() const':
framework.pb.cc:(.text+0x1e2c): undefined reference to `google::protobuf::io::CodedOutputStream::VarintSize32Fallback(unsigned int)'
baidu/paddlepaddle/paddle/paddle/lib/libpaddle_fluid.a(framework.pb.cc.o):framework.pb.cc:(.text+0x1e41): more undefined references to `google::protobuf::io::CodedOutputStre
am::VarintSize32Fallback(unsigned int)' follow
baidu/paddlepaddle/paddle/paddle/lib/libpaddle_fluid.a(framework.pb.cc.o): In function `paddle::framework::proto::OpDesc_Attr::ByteSizeLong() const':
framework.pb.cc:(.text+0x36c4): undefined reference to `google::protobuf::io::CodedOutputStream::VarintSize64(unsigned long)'
framework.pb.cc:(.text+0x3753): undefined reference to `google::protobuf::io::CodedOutputStream::VarintSize32Fallback(unsigned int)'
framework.pb.cc:(.text+0x3768): undefined reference to `google::protobuf::io::CodedOutputStream::VarintSize64(unsigned long)'
framework.pb.cc:(.text+0x3781): undefined reference to `google::protobuf::io::CodedOutputStream::VarintSize32Fallback(unsigned int)'
framework.pb.cc:(.text+0x3791): undefined reference to `google::protobuf::io::CodedOutputStream::VarintSize32Fallback(unsigned int)'
framework.pb.cc:(.text+0x37ba): undefined reference to `google::protobuf::io::CodedOutputStream::VarintSize32Fallback(unsigned int)'
framework.pb.cc:(.text+0x37c8): undefined reference to `google::protobuf::io::CodedOutputStream::VarintSize32Fallback(unsigned int)'
baidu/paddlepaddle/paddle/paddle/lib/libpaddle_fluid.a(framework.pb.cc.o): In function `paddle::framework::proto::OpDesc::ByteSizeLong() const':
framework.pb.cc:(.text+0x3864): undefined reference to `google::protobuf::io::CodedOutputStream::VarintSize32Fallback(unsigned int)'
baidu/paddlepaddle/paddle/paddle/lib/libpaddle_fluid.a(framework.pb.cc.o):framework.pb.cc:(.text+0x38b4): more undefined references to `google::protobuf::io::CodedOutputStre
am::VarintSize32Fallback(unsigned int)' follow
baidu/paddlepaddle/paddle/paddle/lib/libpaddle_fluid.a(framework.pb.cc.o): In function `paddle::framework::proto::(anonymous namespace)::MergeFromFail(int)':
framework.pb.cc:(.text.unlikely+0xe): undefined reference to `google::protobuf::internal::MergeFromFail(char const*, int)'

**Comment by wzzju** [comment]
您好！请问您主机安装的protobuf的版本是3.1吗？请在主机安装3.1版本的protobuf。

**Comment by JiabinYang** [comment]
现在paddle只能支持protobuf 3.1.0，请问您在单独安装编译paddle的时候会有这个问题么

**Comment by wzzju** [comment]
用户将`libpaddle_fluid.a`换成`libpaddle_fluid.so`后可以集成到自己的主模块中。特此记录。

**Comment by wzzju** [comment]
用户将`libpaddle_fluid.a`换成`libpaddle_fluid.so`后可以集成到自己到主模块中。特此记录。
