### ISSUE TITLE
Has fluid-recordio supported varied image-size and sequence-label？

### ISSUE THREAD

**Issue by linan142857** [PaddlePaddle/Paddle#14357]

**Comment by reyoung** [comment]
The image size and sequence label must be the same in one training batch/iteration. However, it can be varied in whole epoch/pass.
RecordIO files just store `vector<Tensor>` and the input shape does not check in runtime

**Comment by reyoung** [comment]
However, RecordIO is not recommended during it is hard to use. Please consider using `PyReader` instead. The `PyReader` is fully cached in memory and GPU. If the time consumption of reading one mini-batch is less than training one mini-batch, the data-reading part should not be the bottleneck of the system.

**Comment by frankwhzhang** [comment]
This problem has solved  and close this issue .
