### ISSUE TITLE
libpaddle_capi_shared.so不维护了吗？https://paddleci.ngrok.io/overview.html不能下载了？

### ISSUE THREAD

**Issue by likeqinqin** [PaddlePaddle/Paddle#14363]
在线业务使用的libpaddle_capi_shared.so，依赖的cudnn v5，希望能下载个依赖cudnn v7的。非常感谢！

**Comment by Superjomn** [comment]
v2 已经停止维护，相关的lib我找人问下

**Comment by luotao1** [comment]
@likeqinqin http://www.paddlepaddle.org/documentation/docs/zh/0.12.0/howto/capi/compile_paddle_lib_cn.html 可以下载cuda8.0_cudnn7_avx_mkl版本
