### ISSUE TITLE
有单机多GPU任务的demo吗

### ISSUE THREAD

**Issue by wchange** [PaddlePaddle/Paddle#14369]
看fluid的api文档里面有feed_parallel、decorate_reader等接口，但是还是不知道具体应该怎么用，另外官网所述的版本似乎找不到
`pip install paddlepaddle-gpu==1.1.0.post85`

> Looking in indexes: http://pip.baidu.com/root/baidu/+simple/
> Collecting paddlepaddle-gpu==1.1.0.post85
>   Could not find a version that satisfies the requirement paddlepaddle-gpu==1.1.0.post85 (from versions: 0.10.1, 0.10.5, 0.10.7, 0.11.0, 0.11.0.post8, 0.11.0.post87, 0.12.0, 0.12.0.post97, 0.13.0, 0.14.0, 0.14.0.post85, 0.14.0.post87)
> No matching distribution found for paddlepaddle-gpu==1.1.0.post85

**Comment by frankwhzhang** [comment]
https://github.com/PaddlePaddle/models/blob/75594b98b27cfb793832064f2b43be4086311a41/fluid/PaddleRec/gru4rec/train.py#L115 
单机多卡的情况 可以参考

**Comment by frankwhzhang** [comment]
http://paddlepaddle.org/documentation/docs/zh/1.1/beginners_guide/install/Start.html
最新的gpu版本可以从这个网页查找

**Comment by wchange** [comment]
> https://github.com/PaddlePaddle/models/blob/75594b98b27cfb793832064f2b43be4086311a41/fluid/PaddleRec/gru4rec/train.py#L115
> 单机多卡的情况 可以参考

这个例子里面用了Executor，但看book 03.image classification里面用的是Trainer，不知道是怎么对应的啊
