### ISSUE TITLE
执行demo报错

### ISSUE THREAD

**Issue by MellonGuan** [PaddlePaddle/Paddle#14373]
系统ubuntu16.04
python3.5
已安装的是paddleGPU

paddle 官方安装：http://www.paddlepaddle.org/documentation/docs/zh/1.1/beginners_guide/install/install_Ubuntu.html
paddle model官方文档：https://github.com/PaddlePaddle/models/blob/develop/fluid/PaddleCV/object_detection/README_cn.md

`python -u train.py --batch_size=64 --dataset='pascalvoc' --pretrained_model='pretrained/ssd_mobilenet_v1_coco/'`

![default](https://user-images.githubusercontent.com/19337606/48351944-812e2c00-e6c6-11e8-9a45-9597eaa5361a.PNG)
![0](https://user-images.githubusercontent.com/19337606/48351946-825f5900-e6c6-11e8-90a1-deb3a89cca20.PNG)

**Comment by wangguibao** [comment]
看报错像是GPU memory不足，能否贴一下系统配置，例如显卡型号、显存大小等等

**Comment by MellonGuan** [comment]
> 看报错像是GPU memory不足，能否贴一下系统配置，例如显卡型号、显存大小等等
今天试了一下，把batch_size调小了，但还是不行。
显卡: geforce gtx 1070
CPU: i7-7700k
CPU核心数: 8
硬盘: 50 G
内存: 32 G
带宽: 100 M
显存: 8 G
显存带宽: 256 GB/s
运行情况如下：
[screencapture-fw-trinicloud-cn-52566-terminals-1-2018-11-13-15_20_35.pdf](https://github.com/PaddlePaddle/Paddle/files/2575015/screencapture-fw-trinicloud-cn-52566-terminals-1-2018-11-13-15_20_35.pdf)

**Comment by MellonGuan** [comment]
> 看报错像是GPU memory不足，能否贴一下系统配置，例如显卡型号、显存大小等等

另一个情况是 python2 环境下的安装和执行同上。运行还可以，自己勉强能应对
情况如下：
![screencapture-fw-trinicloud-cn-57106-terminals-5-2018-11-13-15_45_13](https://user-images.githubusercontent.com/19337606/48398283-4f1ad980-e75b-11e8-9772-ee007b49761c.png)

**Comment by MellonGuan** [comment]
> 系统ubuntu16.04
> python3.5
> 已安装的是paddleGPU
> 
> paddle 官方安装：http://www.paddlepaddle.org/documentation/docs/zh/1.1/beginners_guide/install/install_Ubuntu.html
> paddle model官方文档：https://github.com/PaddlePaddle/models/blob/develop/fluid/PaddleCV/object_detection/README_cn.md
> 
> `python -u train.py --batch_size=64 --dataset='pascalvoc' --pretrained_model='pretrained/ssd_mobilenet_v1_coco/'`
> 
> ![default](https://user-images.githubusercontent.com/19337606/48351944-812e2c00-e6c6-11e8-9a45-9597eaa5361a.PNG)
> ![0](https://user-images.githubusercontent.com/19337606/48351946-825f5900-e6c6-11e8-90a1-deb3a89cca20.PNG)
