### ISSUE TITLE
确定DecayRegularizer 用于 SelectedRow数据的实际效果？

### ISSUE THREAD

**Issue by colin1988** [PaddlePaddle/Paddle#14370]
将L1DecayRegularizer用于大规模稀疏表，是否能自动去掉作用较小的id特征，更确切的说是在id对应embedding的每个维度做L1正则还是在整个id对应的embedding向量上作分组L1正则？

另外，求简要介绍大规模稀疏表的正则化实现策略。

**Comment by chengduoZH** [comment]
> 是否能自动去掉作用较小的id特征

目前Paddle是不支持在L1中指定id的。

您是要做分布式吗？

**Comment by colin1988** [comment]
@chengduoZH 对。大规模稀疏特征的embedding，期望能通过正则化过滤掉某些低频id特征对应的整个embedding。或者说对pserver支持weight decay。develop分支两天前对SelectedRow是有特化的，刚刚去掉吧

        if grad.type == core.VarDesc.VarType.SELECTED_ROWS:
            idx = block.create_var(
                dtype="int64",
                shape=param.shape,
                type=core.VarDesc.VarType.LOD_TENSOR)
            decay = block.create_var(
                dtype="float32",
                shape=param.shape,
                type=core.VarDesc.VarType.LOD_TENSOR)
            block.append_op(
                type='extract_rows', inputs={'X': grad}, outputs={'Out': idx})
            block.append_op(
                type='lookup_table',
                inputs={'W': param,
                        'Ids': idx},
                outputs={'Out': decay},
                attrs={'is_sparse': True})
            param = decay
python/paddle/fluid/regularizer.py

**Comment by chengduoZH** [comment]
> develop分支两天前对SelectedRow是有特化的，刚刚去掉吧

是的，之前的实现方式是有问题的，~~正确的正则化方法应该是对整个参数，这是符合数学表达的。~~ 根据正则化的数学公式，正确的正则化方法应该是对整个参数做正则。

**Comment by colin1988** [comment]
@chengduoZH 最新的develop分支里正则化针对pserver是什么效果啊？另外，"正确的正则化方法"预计什么时候可用啊

**Comment by chengduoZH** [comment]
> "正确的正则化方法"预计什么时候可用 

根据数学公式，正确的正则化方法应该是对整个参数，现在的develop分支就是这么做的。

**Comment by wangguibao** [comment]
先关闭了。后续相关需求可以随时重新打开
