### ISSUE TITLE
训练RNN在K80上为什么还没有CPU跑得快？

### ISSUE THREAD

**Issue by lcxaiw** [PaddlePaddle/Paddle#1437]
我的机器CPU配置是24核，cpu型号是 Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GH 
最近在用paddle写rnn的应用，本来在K80上做，以为是本身计算慢
但偶然间发现，在CPU上直接运行反而更快
运行是k80上显存一直在200M，但内存的利用率却很高，系统是centos-7.2
而我在我的另一台服务器用的GTX1070表现的却比较正常，显存也可以达到2GB左右的占用，而那个系统是ubuntu16.04的
所以是在centos上用的源码安装，而paddle源码安装只支持ubuntu的系统差异造成的？
还是GPU的原因？
又或者是我没加什么运行或者编译的参数造成的？
但我记得GTX1070的GFLOPS没有K80的高
望解答
@reyoung @luotao1

**Comment by ZhangXinNan** [comment]
同问？

**Comment by bringtree** [comment]
同问？
