### ISSUE TITLE
fluid GPU模式下使用 nce报错

### ISSUE THREAD

**Issue by colwater123** [PaddlePaddle/Paddle#14378]
word2vec在gpu模式下，使用nce报错：
paddle.fluid.core.EnforceNotMet: op nce does not have kernel for data_type[float]:data_layout[ANY_LAYOUT]:place[CUDAPlace(1)]:library_type[PLAIN] at [/paddle/paddle/fluid/framework/operator.cc:678]
使用cpu是可以成功执行。
我看到 #12255 也提到了这个问题，请问现在有修正后的版本了么？

**Comment by jacquesqiao** [comment]
fixed by https://github.com/PaddlePaddle/Paddle/pull/14385

**Comment by wangguibao** [comment]
@colwater123 代码已修复，请用主干代码重新跑一下试试

**Comment by wangguibao** [comment]
代码已修复，issue回复和内部分别通知用户去用最新版本复现。用户一周无回复，issue先关闭了。
