### ISSUE TITLE
paddle.fluid.core.EnforceNotMet: Enforce failed. Expected x_dims.size() > x_num_col_dims, but received x_dims.size():1 <= x_num_col_dims:1. The input tensor X's rank of MulOp should be larger than x_num_col_dims. at [/paddle/paddle/fluid/operators/mul_op.cc:48]

### ISSUE THREAD

**Issue by sonofaeolus** [PaddlePaddle/Paddle#14391]
Thank you for contributing to PaddlePaddle. Submitting an issue is a great help for us.
Both Chinese and English issues are welcome.

It's hard to solve a problem when important details are missing.
Before submitting the issue, look over the following criteria before handing your request in.

- [ ] Was there a similar issue submitted or resolved before ? You could search issue in the github.
- [ ] Did you retrieve your issue from widespread search engines ?
- [ ] Is my description of the issue clear enough to reproduce this problem?
   * If some errors occurred, we need details about `how do you run your code?`, `what system do you use?`, `Are you using GPU or not?`, etc.
   * If you use an recording [asciinema](https://asciinema.org/) to show what you are doing to make it happen, that's awesome! We could help you solve the problem more quickly.
- [ ] Is my description of the issue use the github markdown correctly?
   * Please use the proper markdown syntaxes for styling all forms of writing, e.g, source code, error information, etc.
   * Check out [this page](https://guides.github.com/features/mastering-markdown/) to find out much more about markdown.

**Comment by wangguibao** [comment]
用户提供的日志和代码截图：
![9dd3a93f12e4104059320ab480947056](https://user-images.githubusercontent.com/1445888/48419233-5f9a7680-e792-11e8-8182-7a2fb3278fc9.JPG)
![797d2726dba3d5418dc0fa9b55140a16](https://user-images.githubusercontent.com/1445888/48419234-5f9a7680-e792-11e8-9da9-5fdabb9aceeb.JPG)

**Comment by wangguibao** [comment]
出错是因为fc里头有有个mul，(input x w)；如果input多于2维，会把它先压平成2维；现在发现input的dim只有1

已建议用户检查input

**Comment by wangguibao** [comment]
用户代码：[ptr_multi.zip](https://github.com/PaddlePaddle/Paddle/files/2584067/ptr_multi.zip)

@chengduoZH 帮看了一下用户的代码，定位原因如下：
用户用了Trainer这个高层API，在Trainer内部会用program_guard创建一个新的program；而程序开头的一些layer是定义在default_main_program里的；这样在train_loss函数里，实际是看不到gru_last_proj这些变量的

已经给用户解释，等待反馈

**Comment by sonofaeolus** [comment]
是这个愿意
