### ISSUE TITLE
How can I feed data into a  middle layer?

### ISSUE THREAD

**Issue by TheodoreG** [PaddlePaddle/Paddle#14407]
Hi, everyone I have a question about feed data. 
1. Is the fluid.layers.data() only way for feeding data? Can I feed data into any tensor in the program?
2. I want to train a ResNet model from a middle layer like 'pool6', and I want to feed this 2048-dim feature into the network, how can I achieve this?

**Comment by colourful-tree** [comment]
已在hi群里回答，可以参考 https://github.com/PaddlePaddle/Paddle/issues/11030

**Comment by TheodoreG** [comment]
I check this program but I can't see how the lib rllab is related to paddle? I download the rllab but still can't figure out how this code works.
Is there any code about variables copying between programs using pure paddle lib?

**Comment by gavin1332** [comment]
没太明白这样做的目的，如果你直接把数据灌入pool6，那pool6还有其他输入吗？

**Comment by TheodoreG** [comment]
> 没太明白这样做的目的，如果你直接把数据灌入pool6，那pool6还有其他输入吗？

现在这条路已经放弃了，选用了将两个program参数copy的策略，见 https://github.com/PaddlePaddle/Paddle/issues/14443
