### ISSUE TITLE
Which kind of 'input_types' should a mixed vector be?

### ISSUE THREAD

**Issue by 17Skye17** [PaddlePaddle/Paddle#1440]
Can dense_vector be used to represent vector like [0.0,0.0,0.0,0.0,......]？
Assume there be a mixed vector like [[1.0,2.0,5.0,9.0],[0.0,0.0,0.0,0.0]] , what should its input_type be?dense_vector ? sparse_vector?or neither of them?

**Comment by 17Skye17** [comment]
I wonder if this error is caused by input_types.Could anyone offer me a hand?

![image](https://cloud.githubusercontent.com/assets/16254832/23265925/3d1df768-fa21-11e6-938c-0bee6fa479ba.png)

**Comment by lcy-seso** [comment]
I close this issue for its inactivity for quite a long time. Please feel free to reopen it. Thank you.
