### ISSUE TITLE
SSD训练阶段加载初始model失败

### ISSUE THREAD

**Issue by 930083287** [PaddlePaddle/Paddle#14419]
![image](https://user-images.githubusercontent.com/15224527/48528074-64f9dd00-e8c8-11e8-9149-408e0300885d.png)

Traceback (most recent call last):
  File "train_add.py", line 87, in <module>
    init_model_path=model_path)
  File "train_add.py", line 25, in train
    parameters.init_from_tar(gzip.open(init_model_path))
  File "/home/users/zhaohui15/miniconda2/lib/python2.7/site-packages/paddle/v2/parameters.py", line 402, in init_from_tar
    self.set(pname, tar_param.get(pname))
  File "/home/users/zhaohui15/miniconda2/lib/python2.7/site-packages/paddle/v2/parameters.py", line 270, in set
    self.__setitem__(key=parameter_name, value=value)
  File "/home/users/zhaohui15/miniconda2/lib/python2.7/site-packages/paddle/v2/parameters.py", line 223, in __setitem__
    (shape, value.shape))
ValueError: Value shape mismatch, expect (1, 525312), should (1, 290304)

当我修改config中的__C.CLASS_NUM参数由21改为其他值时，出现上述错误，paddle平台使用的是v2

**Comment by gavin1332** [comment]
网络配置能贴一下吗

**Comment by 930083287** [comment]
from easydict import EasyDict as edict
import numpy as np

__C = edict()
cfg = __C

__C.TRAIN = edict()

__C.IMG_WIDTH = 300
__C.IMG_HEIGHT = 300
__C.IMG_CHANNEL = 3
__C.CLASS_NUM = 38
__C.BACKGROUND_ID = 0

# training settings
__C.TRAIN.LEARNING_RATE = 0.001 / 4
__C.TRAIN.MOMENTUM = 0.9
__C.TRAIN.BATCH_SIZE = 64
__C.TRAIN.NUM_PASS = 200
__C.TRAIN.L2REGULARIZATION = 0.0005 * 4
__C.TRAIN.LEARNING_RATE_DECAY_A = 0.1
__C.TRAIN.LEARNING_RATE_DECAY_B = 16551 * 80
__C.TRAIN.LEARNING_RATE_SCHEDULE = 'discexp'

__C.NET = edict()

# configuration for multibox_loss_layer
__C.NET.MBLOSS = edict()
__C.NET.MBLOSS.OVERLAP_THRESHOLD = 0.5
__C.NET.MBLOSS.NEG_POS_RATIO = 3.0
__C.NET.MBLOSS.NEG_OVERLAP = 0.5

# configuration for detection_map
__C.NET.DETMAP = edict()
__C.NET.DETMAP.OVERLAP_THRESHOLD = 0.5
__C.NET.DETMAP.EVAL_DIFFICULT = False
__C.NET.DETMAP.AP_TYPE = "11point"

# configuration for detection_output_layer
__C.NET.DETOUT = edict()
__C.NET.DETOUT.CONFIDENCE_THRESHOLD = 0.01
__C.NET.DETOUT.NMS_THRESHOLD = 0.45
__C.NET.DETOUT.NMS_TOP_K = 400
__C.NET.DETOUT.KEEP_TOP_K = 200

# configuration for priorbox_layer from conv4_3
__C.NET.CONV4 = edict()
__C.NET.CONV4.PB = edict()
__C.NET.CONV4.PB.MIN_SIZE = [30]
__C.NET.CONV4.PB.MAX_SIZE = []
__C.NET.CONV4.PB.ASPECT_RATIO = [2.]
__C.NET.CONV4.PB.VARIANCE = [0.1, 0.1, 0.2, 0.2]

# configuration for priorbox_layer from fc7
__C.NET.FC7 = edict()
__C.NET.FC7.PB = edict()
__C.NET.FC7.PB.MIN_SIZE = [60]
__C.NET.FC7.PB.MAX_SIZE = [114]
__C.NET.FC7.PB.ASPECT_RATIO = [2., 3.]
__C.NET.FC7.PB.VARIANCE = [0.1, 0.1, 0.2, 0.2]

# configuration for priorbox_layer from conv6_2
__C.NET.CONV6 = edict()
__C.NET.CONV6.PB = edict()
__C.NET.CONV6.PB.MIN_SIZE = [114]
__C.NET.CONV6.PB.MAX_SIZE = [168]
__C.NET.CONV6.PB.ASPECT_RATIO = [2., 3.]
__C.NET.CONV6.PB.VARIANCE = [0.1, 0.1, 0.2, 0.2]

# configuration for priorbox_layer from conv7_2
__C.NET.CONV7 = edict()
__C.NET.CONV7.PB = edict()
__C.NET.CONV7.PB.MIN_SIZE = [168]
__C.NET.CONV7.PB.MAX_SIZE = [222]
__C.NET.CONV7.PB.ASPECT_RATIO = [2., 3.]
__C.NET.CONV7.PB.VARIANCE = [0.1, 0.1, 0.2, 0.2]

# configuration for priorbox_layer from conv8_2
__C.NET.CONV8 = edict()
__C.NET.CONV8.PB = edict()
__C.NET.CONV8.PB.MIN_SIZE = [222]
__C.NET.CONV8.PB.MAX_SIZE = [276]
__C.NET.CONV8.PB.ASPECT_RATIO = [2., 3.]
__C.NET.CONV8.PB.VARIANCE = [0.1, 0.1, 0.2, 0.2]

# configuration for priorbox_layer from pool6
__C.NET.POOL6 = edict()
__C.NET.POOL6.PB = edict()
__C.NET.POOL6.PB.MIN_SIZE = [276]
__C.NET.POOL6.PB.MAX_SIZE = [330]
__C.NET.POOL6.PB.ASPECT_RATIO = [2., 3.]
__C.NET.POOL6.PB.VARIANCE = [0.1, 0.1, 0.2, 0.2]

是这个吧？其中当__C.CLASS_NUM＝21时，就不出现上述问题，不知道具体原因了

**Comment by gavin1332** [comment]
建议使用fluid版本SSD，里边给出了包括训练和预测在内的工具套件，且有专人持续维护：
https://github.com/PaddlePaddle/models/tree/develop/fluid/PaddleCV/object_detection

**Comment by gavin1332** [comment]
关于v2 SSD模型问题，我assign给 @qingqing01  帮忙解答一下

**Comment by qingqing01** [comment]
@930083287 请问您加在的初始化模型是什么？CLASS_NUM改变后，计算conf、loc的conv的num_filter数会改变，这几层是不需要初始化的。看错误是加载的参数shape不匹配，确保初始化模型是没用错吧。

**Comment by 930083287** [comment]
初始会模型使用的是vgg_model.tar.gz,这个没有问题，与修改CLASS_NUM之前一致，请问ssd模型，修改CLASS_NUM非21时，是否还有对应的其他参数需要改？应该怎么改？ @qingqing01

**Comment by gavin1332** [comment]
初始model应该是指定了具体类别数的，你更改了类别数，新的网络跟模型对不上，必然没法成功加载。

**Comment by gavin1332** [comment]
要么冷启动训练，要么跟初始model保持类别数一致。
先关闭此issue，如有疑问可重新开启。

**Comment by 930083287** [comment]
@gavin1332 我尝试采用冷启动的方式，出现float异常，
![image](https://user-images.githubusercontent.com/15224527/48591552-60443000-e97f-11e8-96ab-0aa57295f8a3.png)

**Comment by 930083287** [comment]
修改初始化模型与类别相关的部分，
![image](https://user-images.githubusercontent.com/15224527/48592022-7521c300-e981-11e8-8810-afaf193f9095.png)
参考：https://github.com/PaddlePaddle/Paddle/issues/8530
