### ISSUE TITLE
Paddle fluid版本如何构建fm layer？

### ISSUE THREAD

**Issue by CruiseSun** [PaddlePaddle/Paddle#14418]
参考DeepFM的配置文档：http://www.paddlepaddle.org/documentation/models/zh/1.1/legacy/deep_fm/README.html
在Paddle V2里面，是通过如下方式构建fm layer的：
def fm_layer(input, factor_size):
    first_order = paddle.layer.fc(input=input, size=1, act=paddle.activation.Linear())
    second_order = paddle.layer.factorization_machine(input=input, factor_size=factor_size)
    fm = paddle.layer.addto(input=[first_order, second_order],
                            act=paddle.activation.Linear(),
                            bias_attr=False)
    return fm
请问在fluid版本里我该怎么配置呢？

**Comment by gavin1332** [comment]
当前fluid还不支持fm模型。

**Comment by gavin1332** [comment]
想了解一下你使用fm目的是为了复现实验，还是做技术调研？
如果是后者的话，建议使用效果更好的DNN模型

**Comment by CruiseSun** [comment]
主要是为了做技术调研，改进DNN网络结构，提高模型特征抽取能力，考虑到deepFM可以自动结合低阶和高阶的特征，应该会有更好的效果。

**Comment by gavin1332** [comment]
之前我们有（使用其他工具）做过fm，deepfm，DNN模型的调研，发现从性能和效果综合表现看，DNN模型明显占优。
原因在于DNN本身有高阶建模特性，且matmul计算易于加速。而fm的交叉内积运算很难加速，性能较差，效果也不理想。
更优的模型可以考虑DCN

**Comment by CruiseSun** [comment]
好的。请问DCN网络Paddle是否有支持的模型配置供参考呢？

**Comment by jacquesqiao** [comment]
fm和dcn目前都能配出来，但是还没暴露出接口和提供样例，我们后续会逐步补充道models下，请关注
https://github.com/PaddlePaddle/models/tree/develop/fluid/PaddleRec/ctr

**Comment by gavin1332** [comment]
fm和dcn应该都放在PaddleRec目录下吧？

**Comment by gavin1332** [comment]
Rec模型大都是ctr预估任务

**Comment by CruiseSun** [comment]
> fm和dcn应该都放在PaddleRec目录下吧？

没有找到呢，现在fm和dcn是不是都还没有呢？

**Comment by gavin1332** [comment]
@CruiseSun Sorry，我的意思是未来示例建设好以后应该放在该目录下。

**Comment by CruiseSun** [comment]
> fm和dcn目前都能配出来，但是还没暴露出接口和提供样例，我们后续会逐步补充道models下，请关注
> https://github.com/PaddlePaddle/models/tree/develop/fluid/PaddleRec/ctr

请问 @jacquesqiao fm和dcn要什么时候才能在fluid使用上呢？

**Comment by CruiseSun** [comment]
@gavin1332 欧欧~
