### ISSUE TITLE
Paddle V2在做电影评分预测时，scale_infer的范围是不是[-5, 5]？可是label是[0,5]

### ISSUE THREAD

**Issue by CruiseSun** [PaddlePaddle/Paddle#14428]
http://www.paddlepaddle.org/documentation/docs/zh/1.1/beginners_guide/basics/recommender_system/index.html

**Comment by CruiseSun** [comment]
![image](https://user-images.githubusercontent.com/20597775/48541614-f765a500-e8f7-11e8-804f-7ce912fd396c.png)

**Comment by gavin1332** [comment]
此处确认有误，应该是 2.5*(inference+1)，稍后更新一下wiki

**Comment by CruiseSun** [comment]
可以对layer对象，直接操作+或者*的运算么？

**Comment by gavin1332** [comment]
目前不支持，不过乘法和加法运算可以直接通过elementwise_xxx方法操作，功能一样，只是写起来麻烦点儿。
另外，全1向量可以通过layers.ones生成

**Comment by CruiseSun** [comment]
我有一个需要是，要计算二分类的auc，不过Paddle V2好像只支持二维向量，而sigmoid只会输出一个值y，我就需要组合出一个[y, 1-y]这种形式的输出，我该怎么做呢？

**Comment by cszhou** [comment]
> 此处确认有误，应该是 2.5*(inference+1)，稍后更新一下wiki
@gavin1332 
https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/dataset/movielens.py
```rating = float(rating) * 2 - 5.0```
所以wiki没错。

**Comment by gavin1332** [comment]
@cszhou 多谢解答，这个细节被隐藏起来了，wiki上缺乏相关说明

**Comment by gavin1332** [comment]
@CruiseSun 可以用log_loss，不过这个问题已经与此topic无关了。
暂时close了，如有需要，可新开issue解答。
