### ISSUE TITLE
跑NCCL demo时，programDesc中没有reduce和broadcast的op

### ISSUE THREAD

**Issue by dashulu** [PaddlePaddle/Paddle#14421]
我打算尝试通过nccl进行paddle的多机多卡训练，程序执行后打印出main_program时，并不像文档所说的有broadcast和reduce的op，只在startup_program中看到gen_nccl_id。
![image](https://user-images.githubusercontent.com/4484303/48528817-83150c80-e8cb-11e8-8d8f-ee0acdcbcc58.png)
这个是为什么？

**Comment by typhoonzero** [comment]
感谢您的反馈。

allreduce相关的op目前是作为`ParallelExecutor`内部的ophandle使用，在program中还看不到，如果需要看到实际执行的graph，可以用下面方法，生成执行graph的图：

```python
build_st = fluid.BuildStrategy()
build_st.debug_graphviz_path = "./mygraph"
exe = fluid.ParallelExecutor(
        True,
        avg_loss.name,
        build_strategy=build_st)
...
```
获得到`mygraph`之后，执行：`dot -Tpnt -o mygraph.png mygraph` 即可生成包含allreduce的执行graph。注意如果模型很大，这个图片生成的也回很大，建议用简单的模型debug。

**Comment by dashulu** [comment]
我看文档中all-reduce是用reduce（grad） + broadcast(para)来实现的，这边我看profile的结果是直接用了all-reduce。这个为什么？reduce + broadcast应该会比all-reduce少传输数据吧。

**Comment by typhoonzero** [comment]
默认是AllReduce，文档图中Reduce是统称 Reduce类OP

**Comment by typhoonzero** [comment]
但文档的确可以完善一下
