### ISSUE TITLE
CRF Decoding fails on AVX machine

### ISSUE THREAD

**Issue by luotao1** [PaddlePaddle/Paddle#14425]
![image](https://user-images.githubusercontent.com/6836917/48533154-4acaf980-e8de-11e8-9825-5d145c9f263d.png)
TAG: Paddle v1.1.0
AVX machine
- Sucess: 
   - Intel(R) Xeon(R) CPU E5-2650 v4 @ 2.20GHz （AVX+AVX2）
   - Intel Core Processor (Haswell) （ONLY has AVX）
```
vendor_id : GenuineIntel
cpu family : 6
model : 60
model name : Intel Core Processor (Haswell)
stepping : 1
cpu MHz : 2394.454
cache size : 4096 KB
fpu : yes
fpu_exception : yes
cpuid level : 13
wp : yes
flags : fpu vme de pse tsc msr pae mce cx8 apic mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon rep_good unfair_spinlock pni pclmulqdq ssse3 fma cx16 sse4_1 sse4_2 x2apic movbe popcnt aes xsave avx f16c rdrand hypervisor lahf_lm abm xsaveopt fsgsbase bmi1 smep erms
bogomips : 4788.90
clflush size : 64
cache_alignment : 64
address sizes : 40 bits physical, 48 bits virtual
power management:
processor : 1
vendor_id : GenuineIntel
cpu family : 6
model : 60
```
- Fail:
   - Intel(R) Xeon(R) CPU E5-2620 0 @ 2.00GHz （ONLY has AVX）
```
model name : Intel(R) Xeon(R) CPU E5-2620 0 @ 2.00GHz
stepping : 7
cpu MHz : 2001.000
cache size : 15360 KB
physical id : 1
siblings : 6
core id : 0
cpu cores : 6
apicid : 32
initial apicid : 32
fpu : yes
fpu_exception : yes
cpuid level : 13
wp : yes
flags : fpu vme de pse tsc msr pae mce cx8 apic mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good xtopology nonstop_tsc aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 cx16 xtpr pdcm dca sse4_1 sse4_2 x2apic popcnt aes xsave avx lahf_lm ida arat epb xsaveopt pln pts dts tpr_shadow vnmi flexpriority ept vpid
bogomips : 3999.44
clflush size : 64
cache_alignment : 64
address sizes : 46 bits physical, 48 bits virtual
power management:
processor : 7
vendor_id : GenuineIntel
cpu family : 6
```

**Comment by luotao1** [comment]
@yihuaxu Could you help to solve this problem?

**Comment by tensor-tang** [comment]
>  flags : fpu vme de pse tsc msr pae mce cx8 apic mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good xtopology nonstop_tsc aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 cx16 xtpr pdcm dca sse4_1 sse4_2 x2apic popcnt aes xsave avx lahf_lm ida arat epb xsaveopt pln pts dts tpr_shadow vnmi flexpriority ept vpid


在 failed的机器flag里面我没有看到 fma， crf里面有没有用fma的相关指令 @yihuaxu

**Comment by ghost** [comment]
@tensor-tang @luotao1 我们这边可能一下子找不到类似的老机器来复现。可以用gdb确认一下是否是跑到AVX的对应jit kernel后crash的么？https://github.com/PaddlePaddle/Paddle/blob/2354409601c9878f076461042ed915a7e3bed85d/paddle/fluid/operators/math/jit_kernel_crf_decode.cc#L38

**Comment by tensor-tang** [comment]
我看到出错的指令是：

```
=> 0x7ee2cf:	add    %ch,0x375ba(%rsi)
   0x7ee2d5:	add    %al,(%rax)
   0x7ee2d7:	add    %dl,(%rbx)
   0x7ee2d9:	add    %al,(%rax)
   0x7ee2db:	add    %al,(%rax)
   0x7ee2dd:	add    %al,(%rax)
   0x7ee2df:	add    %dl,%bl
   0x7ee2e1:	jns    0x7ee32e
   0x7ee2e3:	add    (%rdx),%ah
   0x7ee2e5:	add    %cl,(%rsi)
   0x7ee2e7:	add    %ah,%al
   0x7ee2e9:	adc    %al,(%rax,%rax,1)
   0x7ee2ed:	add    %al,(%rax)
   0x7ee2ef:	add    %ch,(%rdx)
   0x7ee2f1:	add    %al,(%rax)
```

**Comment by ghost** [comment]
@tensor-tang 这句出错不太合理啊。上面log显示的是"Illegal Instruction"。这是add, 顶多是寻址异常，应该不可能是"Illegal Instruction"

**Comment by tensor-tang** [comment]
是的我也觉得比较奇怪，但是core文件看到的就是这句，报的错也是Illegal Instruction。

感觉应该更像是越界什么的。

**Comment by ghost** [comment]
![image](https://user-images.githubusercontent.com/35804429/48601561-3e60a280-e9ab-11e8-8be8-2b9a18a3e3b0.png)
Crash地址：07ee2cf

反汇编lac二进制文件后，该地址对应的汇编指令为：vpand
![image](https://user-images.githubusercontent.com/35804429/48601670-91d2f080-e9ab-11e8-975c-03dcda6e56e6.png)

而使用vpand指令的唯一intrinsic function是__m256i _mm256_and_si256 (__m256i a, __m256i b)。
见这个链接（https://software.intel.com/sites/landingpage/IntrinsicsGuide/#techs=AVX,AVX2）。
vpand指令是对两个256bit位宽的寄存器组进行AND操作。这个指令是AVX2的。这可能是造成Illegal Instruction的原因。

回到源代码，_mm256_and_si256唯一被调用的地方是在AVX2的JIT kernel里，如下：
https://github.com/PaddlePaddle/Paddle/blob/d971d5b875e793c44e3f3b37565a91145b000a97/paddle/fluid/operators/math/jit_kernel_crf_decode.cc#L194

所以现在看，问题是：为什么在只有AVX的该机器上，会走到AVX2的jit kernel

**Comment by tensor-tang** [comment]
赞，思路非常清楚。

`_mm256_and_si256((__m256i)mask, _mm256_set1_epi32(i))); ` 这个函数被使用的地方是在AVX2的宏下，所以还是说明在编译的时候打开的avx2

https://github.com/PaddlePaddle/Paddle/blob/d971d5b875e793c44e3f3b37565a91145b000a97/paddle/fluid/operators/math/jit_kernel_crf_decode.cc#L272-L276
