### ISSUE TITLE
GPU版本包跑CPU训练

### ISSUE THREAD

**Issue by sarawon** [PaddlePaddle/Paddle#1442]
1.如果安装了GPU版本的deb包，但是跑的是CPU训练可以吗？这个跟直接安装CPU的包有什么区别吗？
2.我用GPU训练出来的和CPU训练出来mnist模型在准确度上有点差别，这个是在实现上有什么差别吗？符合预期的吗？

**Comment by hedaoyuan** [comment]
1. 没有什么区别；
2. GPU版本和CPU版本在一些算法实现上会有浮点精度差异，这个差异不会很大，一般不会影响模型预测精度。你说的`模型在准确度上有点差别`是多大的差别？

**Comment by sarawon** [comment]
@hedaoyuan 可能跑的次数不够多哈 比如num_passes=10
GPU第10轮的classification_error_evaluator=0.0129
CPU的第10轮是classification_error_evaluator=0.0088
这个是预期范围内的吧

**Comment by hedaoyuan** [comment]
多跑几个pass吧，另外并不一定是最后一个pass最好的（GPU和CPU也不一定是在同一个pass中达到最好）。

**Comment by sarawon** [comment]
OK 好的 中间轮确实也有小的值
