### ISSUE TITLE
expand op 文档示例有误

### ISSUE THREAD

**Issue by frankwhzhang** [PaddlePaddle/Paddle#14429]
http://paddlepaddle.org/documentation/api/zh/1.1/layers.html#permalink-62-expand
官方文档api中的expand 给出的样例如下
x = fluid.layers.data(name='x', shape=[10], dtype='float32')
out = fluid.layers.expand(x=x, expand_times=[1, 2, 2])

但是x其实是[batchsize,10] dims是2 ，不能与[1,2,2] dims=3 扩展

会出现报错信息
x_dims.size()) == expand_times.size(), but received static_cast<size_t>(x_dims.size()):2 != expand_times.size():3.

**Comment by shanyi15** [comment]
find https://github.com/PaddlePaddle/Paddle/blame/develop/python/paddle/fluid/layers/nn.py#L7198 please have a look, thanks @wanghaoshuang
