### ISSUE TITLE
没有给定program情况下，如何通过param_attr的name在global_scope中找到该parameter variable

### ISSUE THREAD

**Issue by zenghsh3** [PaddlePaddle/Paddle#14422]
global_scope().find_var(name)目前返回的是core.Variable，有类似接口可以返回framewark.Variable吗？（需求是：可以通过param_attr名字在global_scope中找到该参数varialbe，在不指定program情况下)

**Comment by velconia** [comment]
为什么需要获取 ```framework.Variable``` 而不是 ```core.Variable``` 呢？至于framework.Variable可以通过在Program里面通过查找名字找到；

**Comment by zenghsh3** [comment]
在做variable之间的参数同步时（强化学习算法很多需要周期性地将一个model参数同步到另一个model（target model）中），assign op目前只支持framework.Variable

如果是通过np.array(core.Variable().get_tensor())这种方法的话需要将参数从GPU中拷贝到CUP中，再拷贝回GPU，效率会低点，所以想通过assign op放在program里run

**Comment by TomorrowIsAnOtherDay** [comment]
> 为什么需要获取 framework.Variable 而不是 core.Variable 呢？

直觉上看哈
我觉得返回C++ 的core.Variable 给python API的用户其实有点怪.返回python端的`framework.Variable`这个看着合理点

**Comment by velconia** [comment]
> assign op目前只支持framework.Variable

这是因为 framework.Variable 和 assign op 是compile time时的方法和变量，只有 dim 和 desc 这些东西；
而 core.Variable 是真正具体数值的 runtime 变量；

所以你从scope里获取到的只能是包含真正runtime数值的core.Variable；

而且经过了Pass之后也。。。不一定能和framework.Variable对应起来。。。

**Comment by velconia** [comment]
我还是没能完全理解这个需求，如果方便的话可以电话我，

但是如果真的要找到 ```framework.Variable``` 的话，建议直接用param_attr里传入的name查找就好，因为这是个compile time的静态变量

**Comment by zenghsh3** [comment]
> 我还是没能完全理解这个需求，如果方便的话可以电话我，
> 
> 但是如果真的要找到 `framework.Variable` 的话，建议直接用param_attr里传入的name查找就好，因为这是个compile time的静态变量

https://github.com/PaddlePaddle/Paddle/blob/2354409601c9878f076461042ed915a7e3bed85d/python/paddle/fluid/framework.py#L2173
类似于上面的_get_var方法，能在不给定program的情况下去查找吗？（我们需要在所有的program中去查找，不仅仅是default_main_program）

**Comment by zenghsh3** [comment]
经讨论，目前在不同program之间同步参数(src_variable->target_variable)的方法：
  - 需要给定src_variable和target_variable分别所在的program，通过_get_var(name, program=None)找到对应的variable，然后构建新的program进行assign（不需要将数据从GPU拷贝到CPU）
  - 通过create_parameter的形式来创建src_variable和target_variable分别对应的两个参数重用的variable，然后构建新的program进行assign（不需要将数据从GPU拷贝到CPU）
  -  通过np.array(global_scope().find_var(name))得到src_variable的数据，然后直接set到target_variable（需要将数据从GPU拷贝到CPU）
