### ISSUE TITLE
Traceback (most recent call last):   File "ptr_multi.py", line 91, in <module>     loss_val = exe.run(main_program, feed = feeder.feed(data), fetch_list=[all_loss.name])   File "/home/wangxiaoyu/python27_fluid/lib/python2.7/site-packages/paddle/fluid/executor.py", line 470, in run     self.executor.run(program.desc, scope, 0, True, True) IndexError: vector::_M_range_check

### ISSUE THREAD

**Issue by sonofaeolus** [PaddlePaddle/Paddle#14433]
Thank you for contributing to PaddlePaddle. Submitting an issue is a great help for us.
Both Chinese and English issues are welcome.

It's hard to solve a problem when important details are missing.
Before submitting the issue, look over the following criteria before handing your request in.

- [ ] Was there a similar issue submitted or resolved before ? You could search issue in the github.
- [ ] Did you retrieve your issue from widespread search engines ?
- [ ] Is my description of the issue clear enough to reproduce this problem?
   * If some errors occurred, we need details about `how do you run your code?`, `what system do you use?`, `Are you using GPU or not?`, etc.
   * If you use an recording [asciinema](https://asciinema.org/) to show what you are doing to make it happen, that's awesome! We could help you solve the problem more quickly.
- [ ] Is my description of the issue use the github markdown correctly?
   * Please use the proper markdown syntaxes for styling all forms of writing, e.g, source code, error information, etc.
   * Check out [this page](https://guides.github.com/features/mastering-markdown/) to find out much more about markdown.

**Comment by gavin1332** [comment]
可以把组网发一下吗？

**Comment by sonofaeolus** [comment]
可以

**Comment by sonofaeolus** [comment]
#-*-coding:utf8-*-
import paddle
import paddle.fluid as fluid
import gen_train_vec
from paddle.fluid.contrib.trainer import *
import paddle.fluid.framework as framework

#超参数定义
dict_size = 30000
emb_size = 64
hidden_size = 128
batch_size = 10
dict_size = 30000

#word input
src_word_id = fluid.layers.data(name = 'src_word_id', shape = [1], dtype = 'int64', lod_level = 1)
biz_label = fluid.layers.data(name = 'biz_label', shape = [1], dtype = 'int64', lod_level = 1)
ctr_label = fluid.layers.data(name = 'ctr_label', shape = [1], dtype = 'int64', lod_level = 1)
biz_word_id = fluid.layers.data(name = 'biz_word_id', shape = [1], dtype = 'int64', lod_level = 1)
ctr_word_id = fluid.layers.data(name = 'ctr_word_id', shape = [1], dtype = 'int64', lod_level = 1)

#源词嵌入
emb_param = fluid.param_attr.ParamAttr(name = "word_emb")
src_emb = fluid.layers.embedding(input = src_word_id, size = [dict_size, emb_size], is_sparse = True, param_attr = emb_param)

#Encoder
gru_input = fluid.layers.fc(input = src_emb, size = hidden_size * 3)
gru_layer = fluid.layers.dynamic_gru(input = gru_input, size = hidden_size)

#Decoder
def train_decoder(gru_layer = gru_layer, name = "ctr"):
    gru_layer_proj = fluid.layers.fc(input = gru_layer, size = hidden_size, bias_attr = False)
    last_seq = fluid.layers.sequence_last_step(input = gru_layer)
    gru_last_proj = fluid.layers.fc(input = last_seq, size = hidden_size, bias_attr = False)
    if name == "biz":
        tgt_emb = fluid.layers.embedding(input = biz_word_id, size = [dict_size, emb_size], is_sparse = True, param_attr = emb_param)
    elif name == "ctr":
        tgt_emb = fluid.layers.embedding(input = ctr_word_id, size = [dict_size, emb_size], is_sparse = True, param_attr = emb_param)
    drnn = fluid.layers.DynamicRNN(name = name)
    with drnn.block():
        word = drnn.step_input(tgt_emb)
        prev = drnn.memory(init = gru_last_proj)
        state_word = fluid.layers.fc(input = word, size = hidden_size, bias_attr = False)
        state_prev = fluid.layers.fc(input = prev, size = hidden_size, bias_attr = False)
        state_now = fluid.layers.relu(state_word + state_prev)
        state_fc_expand = fluid.layers.sequence_expand(x = prev, y = gru_layer_proj)
        mix_layer = state_fc_expand + gru_layer_proj
        att_layer = fluid.layers.fc(input = mix_layer, size = dict_size)
        print att_layer.shape
        sum_layer = fluid.layers.sequence_pool(input = att_layer, pool_type = 'sum')
        print sum_layer.shape
        att_weight = fluid.layers.softmax(sum_layer)
        drnn.update_memory(prev, state_now)
        drnn.output(att_weight)
    return drnn()
        
#定义损失函数
def train_loss():
    decoder_biz = train_decoder(name = 'biz', gru_layer = gru_layer)
    decoder_ctr = train_decoder(name = 'ctr', gru_layer = gru_layer)
    print biz_label.shape
    biz_loss = fluid.layers.reduce_sum(fluid.layers.cross_entropy(input = decoder_biz, label = biz_label))
    ctr_loss = fluid.layers.reduce_sum(fluid.layers.cross_entropy(input = decoder_ctr, label = ctr_label))
    biz_maxpool = fluid.layers.sequence_pool(input = decoder_biz, pool_type = 'max')
    ctr_maxpool = fluid.layers.sequence_pool(input = decoder_ctr, pool_type = 'max')
    print biz_maxpool.shape, ctr_maxpool.shape
    sim_loss = fluid.layers.reduce_sum(fluid.layers.elementwise_mul(biz_maxpool, fluid.layers.log(fluid.layers.elementwise_div(x = biz_maxpool, y = ctr_maxpool))))
    print sim_loss.shape, ctr_loss.shape, sim_loss.shape
    all_loss = biz_loss + ctr_loss + sim_loss
    return biz_loss

#定义优化器
optimizer = fluid.optimizer.Adam(learning_rate = 0.0002)

#读取训练数据
train_reader = paddle.batch(paddle.reader.shuffle(gen_train_vec.train(dict_size), buf_size = 500), batch_size = batch_size)
feed_order = [src_word_id, ctr_word_id, ctr_label, biz_word_id, biz_label]

#Train proc
place = fluid.CPUPlace()
#trainer = Trainer(train_func = train_loss, place = place, optimizer_func = optimizer)
#trainer.train(reader = train_reader, num_epochs = 100, event_handler = event_handler, feed_order = feed_order)
all_loss = train_loss()
optimizer.minimize(all_loss)
exe = fluid.Executor(place)
exe.run(fluid.default_startup_program())
feeder = fluid.DataFeeder(feed_list = feed_order, place=place)
main_program = fluid.default_main_program()
for batch_id, data in enumerate(train_reader()):
    print len(data[0]), batch_id
    print feeder.feed(data)
    loss_val = exe.run(main_program, feed = feeder.feed(data), fetch_list=[all_loss])
    print "batch %d loss: %f" % (batchid, loss_val[0])

**Comment by sonofaeolus** [comment]
Traceback (most recent call last):
  File "ptr_multi.py", line 92, in <module>
    loss_val = exe.run(main_program, feed = feeder.feed(data), fetch_list=[all_loss])
  File "/home/wangxiaoyu/python27_fluid/lib/python2.7/site-packages/paddle/fluid/executor.py", line 470, in run
    self.executor.run(program.desc, scope, 0, True, True)
paddle.fluid.core.EnforceNotMet: Enforce failed. Expected lod.size() == 1UL, but received lod.size():0 != 1UL:1.
Only support one level sequence now. at [/paddle/paddle/fluid/operators/sequence_pool_op.h:43]现在错误

**Comment by sonofaeolus** [comment]
> 
> 
> 可以把组网发一下吗？

已发 https://github.com/PaddlePaddle/Paddle/issues/14433

**Comment by gavin1332** [comment]
模型比较复杂，我裸眼看的话初步定为在下边的代码：
sum_layer = fluid.layers.sequence_pool(input = att_layer, pool_type = 'sum')
att_layer需要是个sequence而非vector，跟错误信息一值：
Expected lod.size() == 1UL, but received lod.size():0 != 1UL:1.
建议跟踪打印lod信息再debug一下

**Comment by gavin1332** [comment]
暂时close此问题，如有异议，可重新打开。

**Comment by sonofaeolus** [comment]
> 
> 
> 暂时close此问题，如有异议，可重新打开。

att_layer的shape是(-1,30000) 并且接收的输入是一个gru的output
