### ISSUE TITLE
conv_elementwise_add_mkldnn_fuse_pass Segment Fault

### ISSUE THREAD

**Issue by luotao1** [PaddlePaddle/Paddle#14446]
https://github.com/PaddlePaddle/Paddle/issues/14174#issuecomment-434648082 say that there is a bug in `conv_elementwise_add_mkldnn_fuse_pass`. Is this bug solved now?

We encounter `Segment Fault` with this pass in another model. And if we remove this pass, predictor runs successfully. 
The log is [feature.log](https://github.com/PaddlePaddle/Paddle/files/2587935/feature.log)

**Comment by tpatejko** [comment]
@luotao1 I'm working on this issue.

If you want, I can share my branch with you, so you can test whether the new version on the pass works with your models.

**Comment by luotao1** [comment]
> I can share my branch with you

@tpatejko OK, or you can create a PR for us.

**Comment by tpatejko** [comment]
@luotao1 I created a PR with the implementation:
https://github.com/PaddlePaddle/Paddle/pull/14458

Please take into account that this is still work in progress. I need to add unit tests for projection connection, and probably refactor the code. However, I think you could try to use it and check whether it solves your problem.

I checked it with Resnet50 and with SE-Resnext. I also checked it with CAPI tests for Resnet and Mobilenet. They all should work.
