### ISSUE TITLE
本地部署Paddle后使用报错

### ISSUE THREAD

**Issue by lucywsq** [PaddlePaddle/Paddle#14444]
项目为HousePredict0

运行环境：
1.	Python解释器：
 
![image](https://user-images.githubusercontent.com/38712162/48595649-9f2eb180-e990-11e8-9377-c1fb1ff9efe2.png)

2.	系统
Mac Os high Sierra version 10.13.6
其他：本机同时装有python2和python3，如图解释器已经调整为python2。当运行house_price_predict.py时，出现如下报错：
 
![image](https://user-images.githubusercontent.com/38712162/48595709-db621200-e990-11e8-983e-4d14403d8177.png)

已经参考网上系列博客，依然无法解决。
https://blog.csdn.net/Eclipsesy/article/details/79703834

**Comment by Xreki** [comment]
系统环境太复杂，建议使用docker。
