### ISSUE TITLE
fluid.io.get_inference_program 接口报错

### ISSUE THREAD

**Issue by xuzhenglei1991** [PaddlePaddle/Paddle#14448]
当前版本为v1.1.0.
使用如https://github.com/baidu/lac中的步骤安装paddle、python 编译fluid、拉取lac代码，编译LAC，最后执行train.py的时候fluid.io.get_inference_program 接口报错

**Comment by xuzhenglei1991** [comment]
python/paddle/fluid/io.py 文件中也没有对该函数的定义

**Comment by Xreki** [comment]
`get_inference_program`这个接口在develop分支上已经删掉了。建议用户直接用api定义自己的inference program。

**Comment by yma-admin** [comment]
建议@kuke 看看，用户按照LAC的安装文档跑，跑不通。需要优化文档。

**Comment by kuke** [comment]
好的 我给NLP的同学反馈下

**Comment by jshower** [comment]
已对train.py进行了修改，可以在paddlev.1.1版本下运行。
