### ISSUE TITLE
Overhead of weight variable creation during inference

### ISSUE THREAD

**Issue by hshen14** [PaddlePaddle/Paddle#14466]
In current implementation, each iteration for inference will re-create weight variables. I ran the CAPI on ResNet-50 with BS=1 and found the overhead of variable creation is 2% (most are malloc).

Could you please explain whether it is a known issue or there are some usage issues at my side? Thanks. @luotao1 @Superjomn @panyx0718 

Variable* Scope::VarInternal(const std::string& name) {
  auto* v = FindVarLocally(name);
  if (v != nullptr) return v;

  v = new Variable();
  vars_[name].reset(v);
  VLOG(30) << "Create variable " << name;
  v->name_ = &(vars_.find(name)->first);
  return v;
}

**Comment by Superjomn** [comment]
The CAPI should not malloc memory each time. All the weights and temporary variable will be reused each batch, so are their memory.

The python API will delete the temporary variables each batch, so it has more overhead due to malloc.

**Comment by hshen14** [comment]
Thanks. We will follow up to verify whether CAPI solved the issue and get update with you.

**Comment by hshen14** [comment]
After rerun with GLOG_v=6 GLOG_logtostderr=1, seems there are twice variable creation for weight variables:
log:16324:I1207 17:00:47.815078 142972 scope.cc:165] Create variable conv_bn_fuse/eltwise_y_in/52
log:28926:I1207 17:00:48.164046 142972 scope.cc:165] Create variable conv_bn_fuse/eltwise_y_in/52

Sorry, I did not fully understand why there are twice here. Could you please explain?

**Comment by Superjomn** [comment]
What's the model?

**Comment by hshen14** [comment]
ResNet-50 FP32, download from the link Luotao provided before.

**Comment by Superjomn** [comment]
Can you provide the C++ code? Maybe some usage problem.

**Comment by hshen14** [comment]
[infer_image_classification.txt](https://github.com/PaddlePaddle/Paddle/files/2661649/infer_image_classification.txt)

Command: GLOG_v=6 GLOG_logtostderr=1 FLAGS_use_mkldnn=true FLAGS_paddle_num_threads=28 KMP_AFFINITY=compact,granularity=fine taskset -c 0-27 numactl -l  ./build/infer_image_classification \
        --infer_model=../resnet50_model \
        --batch_size=1 \
        --profile \
        --skip_batch_num=10 \
        --iterations=100  \
        --data_list=/home/chuanqiw/paddle/intelpaddle-models/fluid/image_classification/data/ILSVRC2012/val_list.txt \
        --data_dir=/home/chuanqiw/paddle/intelpaddle-models/fluid/image_classification/data/ILSVRC2012/ \
        --use_mkldnn \
        --paddle_num_threads=28  \
        --use_fake_data=true  2>&1 | tee log

+@chuanqi129

**Comment by hshen14** [comment]
Seems the variable creation is necessary, because: 1) the first time compile time (IR pass); and 2) the second time during runtime. Will close it.
