### ISSUE TITLE
paddle可以自定义损失函数吗？

### ISSUE THREAD

**Issue by xiaolv3366** [PaddlePaddle/Paddle#14462]
paddle 自定义损失函数

Keras可以自定义损失函数，其他框架也是可以的，paddle可以自定义损失函数吗？

着急。

**Comment by mapingshuo** [comment]
你好，我觉得直接使用其他layer组出来一个loss即可，但我也没有实践过 :) 你的loss是什么公式？

**Comment by lucywsq** [comment]
您好，此issue在近一个月内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题，我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持!
