### ISSUE TITLE
Dataprovider

### ISSUE THREAD

**Issue by studyPaddle** [PaddlePaddle/Paddle#1448]
请问PaddlePaddle在在输入二维数组时，init_hook中的input_type应该怎么设置？？？？data_Layer中的size应该怎么写？？

**Comment by reyoung** [comment]
@studyPaddle 有一个基本的问题，为什么输入数据是二维的呢？是图像么？如果是图像的话，请参考Paddle的图像识别demo。

Paddle对图像的处理，是将二维数据变成一维数据，然后在卷积层里面处理图像的长和宽的。

如果是其他需求，请说明输入数据是什么。

**Comment by pwllr** [comment]
文档中：
PaddlePaddle的数据包括四种主要类型，和三种序列模式。其中，四种数据类型是
dense_vector 表示稠密的浮点数向量。
sparse_binary_vector 表示稀疏的零一向量，即大部分值为0，有值的位置只能取1
sparse_vector 表示稀疏的向量，即大部分值为0，有值的部分可以是任何浮点数
integer 表示整数标签。
而三种序列模式为

SequenceType.NO_SEQUENCE 即不是一条序列
SequenceType.SEQUENCE 即是一条时间序列
SequenceType.SUB_SEQUENCE 即是一条时间序列，且序列的每一个元素还是一个时间序列。
不同的数据类型和序列模式返回的格式不同，列表如下

 	NO_SEQUENCE	SEQUENCE	SUB_SEQUENCE
dense_vector	[f, f, ...]	[[f, ...], [f, ...], ...]	[[[f, ...], ...], [[f, ...], ...],...]
sparse_binary_vector	[i, i, ...]	[[i, ...], [i, ...], ...]	[[[i, ...], ...], [[i, ...], ...],...]
sparse_vector	[(i,f), (i,f), ...]	[[(i,f), ...], [(i,f), ...], ...]	[[[(i,f), ...], ...], [[(i,f), ...], ...],...]
integer_value	i	[i, i, ...]	[[i, ...], [i, ...], ...]
其中，f代表一个浮点数，i代表一个整数。


其中	SEQUENC和SUB_SEQUENCE两种数据类型，输入时如何配置？？都要转换成1维数组吗？我如果需要保留二维的信息怎么办？？

**Comment by pwllr** [comment]
@reyoung

**Comment by lcy-seso** [comment]
读取数据格式相关的信息，可以在Paddle的文档区查找信息。
由于长时间没有信息更新，我先close掉此issue。如果有进一步的信息，可以reopen后继续交流。
