### ISSUE TITLE
请问这里为什么要加一个fc层？

### ISSUE THREAD

**Issue by CruiseSun** [PaddlePaddle/Paddle#14482]
https://github.com/PaddlePaddle/models/blob/7852d0604d9c4d82778ef1c705dbcfd904eecadf/fluid/PaddleRec/gru4rec/train.py#L47

**Comment by frankwhzhang** [comment]
http://paddlepaddle.org/documentation/api/zh/1.0/layers.html#permalink-34-dynamic_gru
这是dynamic_gru的文档说明，根据这个op的设计 需要在dynamic_gru op之前加一层fc ，可以理解为一个逻辑单步分成了两步实现的

**Comment by frankwhzhang** [comment]
经与用户沟通，问题已解决，先关闭这个issue，如有问题可以重开。
