### ISSUE TITLE
[feature request] support for python 3.6+

### ISSUE THREAD

**Issue by TomorrowIsAnOtherDay** [PaddlePaddle/Paddle#14498]
Fluid support currently python2.7 and python3.5, but some benchmarks in RL request python3.6,
I tried to install fluid with python3.6 in `pip`, but it showed `no package found`.

Could developers provide package for python3.6 in `pip` so that it could be installed in python3.6 environment.

**Comment by velconia** [comment]
```Python3.6``` is supporting now. But what's the ddl for python3.6 support, we are going to support it in 12.6, you could see the works we are doing in the end of this [issue](https://github.com/PaddlePaddle/Paddle/issues/12040)

**Comment by TomorrowIsAnOtherDay** [comment]
We plan to publish model and PARL in NeurIPS workshop(12.07) and many participants will be cloning the PARL and  launch the prediction to check its performance.
So it would be nice it is ready at the moment. Besides, will you support `pip install` ?

**Comment by velconia** [comment]
Yes, but they should use ```pip3.6``` or ```pip3.7``` to install the python3.6 or python3.7 paddle wheel package

**Comment by velconia** [comment]
Python3.6 is supported now. Close this issue
