### ISSUE TITLE
sequence_pool出错

### ISSUE THREAD

**Issue by sonofaeolus** [PaddlePaddle/Paddle#14495]
Thank you for contributing to PaddlePaddle. Submitting an issue is a great help for us.
Both Chinese and English issues are welcome.

It's hard to solve a problem when important details are missing.
Before submitting the issue, look over the following criteria before handing your request in.

- [ ] Was there a similar issue submitted or resolved before ? You could search issue in the github.
- [ ] Did you retrieve your issue from widespread search engines ?
- [ ] Is my description of the issue clear enough to reproduce this problem?
   * If some errors occurred, we need details about `how do you run your code?`, `what system do you use?`, `Are you using GPU or not?`, etc.
   * If you use an recording [asciinema](https://asciinema.org/) to show what you are doing to make it happen, that's awesome! We could help you solve the problem more quickly.
- [ ] Is my description of the issue use the github markdown correctly?
   * Please use the proper markdown syntaxes for styling all forms of writing, e.g, source code, error information, etc.
   * Check out [this page](https://guides.github.com/features/mastering-markdown/) to find out much more about markdown.

**Comment by sonofaeolus** [comment]
1 import paddle.fluid as fluid
  2 import paddle
  3 import numpy as np
  4 
  5 data = fluid.layers.data(name = 'X', shape = [1], dtype = 'float32', lod_level = 1)
  6 data_tmp = fluid.layers.data(name = 'Y', shape = [10,10], dtype = 'float32', lod_level = 1)
  7 #hidden = fluid.layers.fc(input=data, size=10, act = 'softmax')
  8 #out = fluid.layers.sequence_expand(x = data, y = data_tmp)
  9 sum = fluid.layers.sequence_pool(data, pool_type = 'sum')
 10 
 11 cpu = fluid.CPUPlace()
 12 exe = fluid.Executor(cpu)
 13 exe.run(fluid.default_startup_program())
 14 
 15 x = np.random.random(size = (1, 10)).astype('float32')
 16 print x
 17 y = np.random.random(size = (7,10)).astype('float32')
 18 outs = exe.run(feed={'X': x, 'Y' : y}, fetch_list=[sum])
 19 print outs[0]

**Comment by sonofaeolus** [comment]
Traceback (most recent call last):
  File "test.py", line 18, in <module>
    outs = exe.run(feed={'X': x, 'Y' : y}, fetch_list=[sum])
  File "/home/wangxiaoyu/python27_fluid/lib/python2.7/site-packages/paddle/fluid/executor.py", line 470, in run
    self.executor.run(program.desc, scope, 0, True, True)
paddle.fluid.core.EnforceNotMet: Enforce failed. Expected lod.size() == 1UL, but received lod.size():0 != 1UL:1.
Only support one level sequence now. at [/paddle/paddle/fluid/operators/sequence_pool_op.h:43]
PaddlePaddle Call Stacks: 
0       0x7f9eeefc1ab6p paddle::platform::EnforceNotMet::EnforceNotMet(std::__exception_ptr::exception_ptr, char const*, int) + 486
1       0x7f9eef9434bcp paddle::operators::SequencePoolKernel<paddle::platform::CPUDeviceContext, float>::Compute(paddle::framework::ExecutionContext const&) const + 2236
2       0x7f9eef943af3p std::_Function_handler<void (paddle::framework::ExecutionContext const&), paddle::framework::OpKernelRegistrarFunctor<paddle::platform::CPUPlace, false, 0ul, paddle::operators::SequencePoolKernel<paddle::platform::CPUDeviceContext, float> >::operator()(char const*, char const*) const::{lambda(paddle::framework::ExecutionContext const&)#1}>::_M_invoke(std::_Any_data const&, paddle::framework::ExecutionContext const&) + 35
3       0x7f9eefc3a81ep paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&) const + 526
4       0x7f9eefc36b58p paddle::framework::OperatorBase::Run(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&) + 232
5       0x7f9eef0850fbp paddle::framework::Executor::RunPreparedContext(paddle::framework::ExecutorPrepareContext*, paddle::framework::Scope*, bool, bool, bool) + 219
6       0x7f9eef085ee0p paddle::framework::Executor::Run(paddle::framework::ProgramDesc const&, paddle::framework::Scope*, int, bool, bool) + 128
7       0x7f9eeefa68bdp
8       0x7f9eeeff6cb4p pybind11::cpp_function::dispatcher(_object*, _object*, _object*) + 2596
9             0x4b8ba7p PyEval_EvalFrameEx + 30279
10            0x4baac8p PyEval_EvalCodeEx + 2040
11            0x4b8328p PyEval_EvalFrameEx + 28104
12            0x4baac8p PyEval_EvalCodeEx + 2040
13            0x4babf2p PyEval_EvalCode + 50
14            0x4e8addp PyRun_FileExFlags + 285
15            0x4ea361p PyRun_SimpleFileExFlags + 209
16            0x415c5dp Py_Main + 2925
17      0x7f9f12e97bd5p __libc_start_main + 245
18            0x414df1p

**Comment by seiriosPlus** [comment]
data do not have```LoD```,  refer: http://paddlepaddle.org/documentation/docs/zh/1.1/user_guides/howto/prepare_data/lod_tensor.html

**Comment by mapingshuo** [comment]
@sonofaeolus I recommend using the fluid.DataFeeder, it will convert a numpy tensor to lod tensor automatically：

```python
import paddle.fluid as fluid
import paddle
import numpy as np

data = fluid.layers.data(name = 'X', shape = [1], dtype = 'float32', lod_level = 1)
sum = fluid.layers.sequence_pool(data, pool_type = 'sum')

cpu = fluid.CPUPlace()
exe = fluid.Executor(cpu)
exe.run(fluid.default_startup_program())

feeder = fluid.DataFeeder(feed_list=[data], place=cpu)

batch_size = 2
batch_data = [[np.random.random(size=(3, 1)).astype('float32')] for i in range(batch_size)]

# batch_data in shape [batch_size, input_num, sequence_len, feature_dim]
# that is [2, 1, 3, 1]
print batch_data

outs = exe.run(feed=feeder.feed(batch_data), fetch_list=[sum])
print outs[0]
```

**Comment by sonofaeolus** [comment]
> 
> 
> @sonofaeolus I recommend using the fluid.DataFeeder, it will convert a numpy tensor to lod tensor automatically：
> 
> ```python
> import paddle.fluid as fluid
> import paddle
> import numpy as np
> 
> data = fluid.layers.data(name = 'X', shape = [1], dtype = 'float32', lod_level = 1)
> sum = fluid.layers.sequence_pool(data, pool_type = 'sum')
> 
> cpu = fluid.CPUPlace()
> exe = fluid.Executor(cpu)
> exe.run(fluid.default_startup_program())
> 
> feeder = fluid.DataFeeder(feed_list=[data], place=cpu)
> 
> batch_size = 2
> batch_data = [[np.random.random(size=(3, 1)).astype('float32')] for i in range(batch_size)]
> 
> # batch_data in shape [batch_size, input_num, sequence_len, feature_dim]
> # that is [2, 1, 3, 1]
> print batch_data
> 
> outs = exe.run(feed=feeder.feed(batch_data), fetch_list=[sum])
> print outs[0]
> ```

thank u

**Comment by sonofaeolus** [comment]
> 
> 
> > @sonofaeolus I recommend using the fluid.DataFeeder, it will convert a numpy tensor to lod tensor automatically：
> > ```python
> > import paddle.fluid as fluid
> > import paddle
> > import numpy as np
> > 
> > data = fluid.layers.data(name = 'X', shape = [1], dtype = 'float32', lod_level = 1)
> > sum = fluid.layers.sequence_pool(data, pool_type = 'sum')
> > 
> > cpu = fluid.CPUPlace()
> > exe = fluid.Executor(cpu)
> > exe.run(fluid.default_startup_program())
> > 
> > feeder = fluid.DataFeeder(feed_list=[data], place=cpu)
> > 
> > batch_size = 2
> > batch_data = [[np.random.random(size=(3, 1)).astype('float32')] for i in range(batch_size)]
> > 
> > # batch_data in shape [batch_size, input_num, sequence_len, feature_dim]
> > # that is [2, 1, 3, 1]
> > print batch_data
> > 
> > outs = exe.run(feed=feeder.feed(batch_data), fetch_list=[sum])
> > print outs[0]
> > ```
> 
> thank u
