### ISSUE TITLE
paddlecloud执行训练任务卡住

### ISSUE THREAD

**Issue by yuanzfy** [PaddlePaddle/Paddle#14496]
使用paddlecloud提交任务，任务会出现假死状态，有某一个或多个训练节点CPU利用率很高，但是看不到任何日志，已经找paddlecloud同学排查过，没有发现异常日志，求关注下：
任务链接：http://paddlecloud.baidu-int.com/paddle/jobRunInfo?jobId=job-e6c5bf2a1c5c1e30&flag=jobs&groupName=k8s_cpu_demo&groupId=4dddb21c-8b8b-4b61-a8a3-b184d17887d&currentPage=1&currentKey=1
异常节点：￼
![de5c5cd57ee8407d9347e5bed](https://user-images.githubusercontent.com/4515954/48747885-f5149980-ecaf-11e8-9d71-fe5ac190fc93.png)
用pstack看下堆栈：
![1dbb176301053b554d3accd98](https://user-images.githubusercontent.com/4515954/48747925-0e1d4a80-ecb0-11e8-99f2-1b52874baed5.png)

**Comment by reyoung** [comment]
如果CPU占用率很高的话，那其实并没有死锁，说明还在计算。

**Comment by seiriosPlus** [comment]
还有问题后续可以通过HI进行沟通。
