### ISSUE TITLE
使用reduce_sum作为loss的时候，parallel_exe不能对loss 除以CPU_NUM

### ISSUE THREAD

**Issue by jacquesqiao** [PaddlePaddle/Paddle#14505]
目前parallel_executor多cpu_num的模式下，默认对每一个loss都除以CPU_NUM，这个做法在使用reduce_mean作为loss layer的时候是没问题的:
例如，如果batch_size = 6，每个cpu分到的batch_size = 2,
如果只有一个cpu，那么loss为  loss / 6， 当 CPU_NUM = 3的时候，三个loss都为  loss1 / 2, loss2/ 2, loss3/ 2, 这时候如果想和CPU_NUM = 1等价，应该对每个loss再除以3，

但是当使用reduce_sum作为loss的时候，直接把loss加起来就行了，不需要除以CPU_NUM!

### 临时方案
可以在reduce_sum得到的loss scale一下cpu_num

**Comment by reyoung** [comment]
在Python端设置ParallelExecutor的BuildStrategy。
https://github.com/PaddlePaddle/Paddle/blob/50a698525d6baf898db43ab552fd599acc3351b2/paddle/fluid/framework/details/build_strategy.h#L64-L65

将，`gradient_scale_` 改成 `kOne` 似乎可以解决问题？
