### ISSUE TITLE
Vgg预测多进程超时

### ISSUE THREAD

**Issue by 930083287** [PaddlePaddle/Paddle#14504]
问题描述：
内存中有两个进程，当A进程初始化paddle，并使其常驻内存；用B进程初始化paddle，当才用vgg网络预测阶段出现hold的情况，请帮忙解决？

**Comment by seiriosPlus** [comment]
A进程在做什么工作呢，是B进程进行VGG网络预测的时候出现HOLD？

**Comment by 930083287** [comment]
我们采用uwsgi的方式，生成多个进程任务，比如A和B两个进程，首先利用A进程初始化paddle，并完成预测操作，但是A进程保持长驻进程；然后利用B进程初始化Paddle，并预测分类操作，在预测阶段会hold住，很长时间没有结果

**Comment by seiriosPlus** [comment]
能不能开一下日志级别， 看看进程B hold在了哪里

**Comment by seiriosPlus** [comment]
export GLOG_v=4
    export GLOG_logtostderr=1

**Comment by 930083287** [comment]
因为我们要考虑多进程并发，reset_parser()这个函数不是很明白，简单尝试下，好像并不能解决我的问题

**Comment by seiriosPlus** [comment]
还有问题后续可以通过HI进行沟通。
