### ISSUE TITLE
mpi cluster训练出错

### ISSUE THREAD

**Issue by wangsouc** [PaddlePaddle/Paddle#1451]
使用mpi cluster训练，迭代完一轮pass，第二轮pass迭代到一半数据报错：
该问题已经多次出现，求指导一下，谢谢！

Fri Feb 24 15:19:45 2017[1,21]<stderr>:*** Aborted at 1487920785 (unix time) try "date -d @1487920785" if you are using GNU date ***
Fri Feb 24 15:19:45 2017[1,35]<stderr>:
Fri Feb 24 15:19:45 2017[1,35]<stderr>:*** Aborted at 1487920785 (unix time) try "date -d @1487920785" if you are using GNU date ***
Fri Feb 24 15:19:45 2017[1,21]<stderr>:
Fri Feb 24 15:19:45 2017[1,21]<stderr>:PC: @           0x7203e2 paddle::ProtoClient::recv()
Fri Feb 24 15:19:45 2017[1,42]<stderr>:
Fri Feb 24 15:19:45 2017[1,42]<stderr>:*** Aborted at 1487920785 (unix time) try "date -d @1487920785" if you are using GNU date ***
Fri Feb 24 15:19:45 2017[1,42]<stderr>:F0224 15:19:45.211447 29510 SocketChannel.cpp:99] Check failed: len > 0  peer=10.73.71.49 curIov=0 iovCnt=4 iovs[curIov].base=0x7f9bb35fdca0 iovs[curIov].iov_len=16: Broken pipe [32]
Fri Feb 24 15:19:45 2017[1,17]<stderr>:
Fri Feb 24 15:19:45 2017[1,21]<stderr>:F0224 15:19:45.198148 13925 SocketChannel.cpp:99] Check failed: len > 0  peer=10.73.71.49 curIov=0 iovCnt=4 iovs[curIov].base=0x7eff217faca0 iovs[curIov].iov_len=16: Broken pipe [32]

**Comment by reyoung** [comment]
集群出错请给出所有的log。

下载打包log的脚本为: https://gist.github.com/reyoung/1d27ad45b86f868095e0c571b86ae0bb

经分析log，发现40号节点的PServer进程被kill掉了。初步怀疑内存泄露。

![image](https://cloud.githubusercontent.com/assets/728699/23297864/29d73da0-fab6-11e6-9635-73e01809fa36.png)

打包的log为
[paddle.log.tar.gz](https://github.com/PaddlePaddle/Paddle/files/798803/paddle.log.tar.gz)

初步来看，应该并非多机特有的错误，故先close掉。如果确认内存泄露，或者被同集群其他任务误杀，请开新的issue记录。
