### ISSUE TITLE
询问几个模型接口问题，谢谢

### ISSUE THREAD

**Issue by Kayven** [PaddlePaddle/Paddle#14516]
1、paddle中如何生成一个随机初始化的embedding（用来自学习一个中间向量）

2、mpi集群上paddle.v2 layer和networks中都没有dot_prod（本地测试有），请问有什么替代接口吗
https://github.com/PaddlePaddle/Paddle/issues/9362 （前面有人问过，说是networks有，但仍然没有
）

3、paddle layer接口中看到有seqreshape，但是执行中提示没有
https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/trainer_config_helpers/layers.py#L1865 （本地机器源码中也有这个接口）

**Comment by guoshengCS** [comment]
V2中随机初始化可以通过param_att设置，可以参考这里 https://github.com/PaddlePaddle/models/blob/develop/legacy/sequence_tagging_for_ner/network_conf.py#L19
dot_prod和seqreshape应该都是由于集群中Paddle版本的问题，替代的接口应该还没有

推荐使用Fluid版本，v2支持的模型Fluid中应该都能够更方便的支持

**Comment by Kayven** [comment]
多谢 @guoshengCS 
第一个问题，我其实是想实现类似tensorflow这样的
u_omega = tf.Variable(tf.random_normal([atten_size], stddev=0.1, dtype=tf.float32))

但是paddle里需要指定input，我并没有input；我只需要一个随机向量，而且这个向量可以训练，需要与另外一个embedding做运算
word = paddle.layer.data(
        name="word",
        type=paddle.data_type.integer_value_sequence(word_dict_len))
    word_embedding = paddle.layer.embedding(
        input=word,
        size=word_dim,
        param_attr=paddle.attr.Param(
            name="emb", initial_std=math.sqrt(1. / word_dim), is_static=True))

**Comment by guoshengCS** [comment]
V2中貌似没有暴露创建可训练参数的接口，可训练的参数好像都是在layer内部创建的，可能没办法实现，Fluid是支持的

**Comment by lucywsq** [comment]
您好，此issue若已解决，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题，我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持!
