### ISSUE TITLE
What is the best way to read Program desc?

### ISSUE THREAD

**Issue by TheodoreG** [PaddlePaddle/Paddle#14521]
Now I know that a Program in Fluid has a description file which contains information about the whole network structure. But when I print this Program  I got the description on screen which is too long to be read.  I'm not pointing to the model file such as __model__ because this is the serialized string format. What is the easiest way to make this file into human readable format?

**Comment by gongweibao** [comment]
https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/fluid/tests/unittests/test_program_code.py
