### ISSUE TITLE
使用强化学习训练小车游戏分数一直上不去

### ISSUE THREAD

**Issue by yeyupiaoling** [PaddlePaddle/Paddle#14531]
我使用强化学习训练一个小游戏，如下：
![image](https://user-images.githubusercontent.com/26297768/48878268-b6aee400-ee41-11e8-82dd-79d01a305cf7.png)

jupyter代码：https://github.com/yeyupiaoling/LearnPaddle2/blob/master/note7/DQNetwork.ipynb

训练时，分数一直上不去。使用同样的tensorflow代码，可以有400多分，而且分数相对稳定一些。
请问老师，这是什么原因呢？

**Comment by kuke** [comment]
@yeyupiaoling  没有在你的配置里面看出什么问题，这个网络相对简单，可以把初始化设置为tensorflow完全一样，然后对比一下中间结果

**Comment by yeyupiaoling** [comment]
@kuke 都不一样。请问我的网络是否正确？我根据tensorflow和PaddlePaddle下的models下的强化学习修改的，不支持整个网络是否正确，比如损坏函数那一块。

**Comment by kuke** [comment]
比如你可以只比较前向，将fc的参数都初始化为某个常数，损失函数也可以换成一样的

**Comment by yeyupiaoling** [comment]
@kuke 
>比较前向

这是什么意思？

损失函数我按照tensorflow的，这是在求平均损失时，我使用的是`fluid.layers.reduce_mean(cost)`
以前在其他任务上，我使用的是`fluid.layers.mean(cost)`
这有影响吗？我看PaddlePaddle的demo是使用`fluid.layers.reduce_mean(cost)`的

**Comment by yeyupiaoling** [comment]
@kuke 关于在这个任务上，有比较好的处理方法了，可以稳定训练结果，还提高训练分数。

**Comment by kuke** [comment]
比较前向指的是网络forward逐层的计算结果

可用print layer

https://github.com/PaddlePaddle/Paddle/blob/8965cee89f83f2d2d4d403e0908232a2810e3149/python/paddle/fluid/tests/unittests/test_print_op.py#L38

cost的计算方式是正确的

**Comment by yeyupiaoling** [comment]
@kuke 除了加深网络深度和增加每个全连接层的单元数量，还有其他什么办法提高网络的性能吗？

**Comment by kuke** [comment]
学习率，优化方法等等，都可以试试

**Comment by yeyupiaoling** [comment]
@kuke 好的，谢谢老师耐心解答。
