### ISSUE TITLE
holder_ should not be null

### ISSUE THREAD

**Issue by sonofaeolus** [PaddlePaddle/Paddle#14544]
Thank you for contributing to PaddlePaddle. Submitting an issue is a great help for us.
Both Chinese and English issues are welcome.

It's hard to solve a problem when important details are missing.
Before submitting the issue, look over the following criteria before handing your request in.

- [ ] Was there a similar issue submitted or resolved before ? You could search issue in the github.
- [ ] Did you retrieve your issue from widespread search engines ?
- [ ] Is my description of the issue clear enough to reproduce this problem?
   * If some errors occurred, we need details about `how do you run your code?`, `what system do you use?`, `Are you using GPU or not?`, etc.
   * If you use an recording [asciinema](https://asciinema.org/) to show what you are doing to make it happen, that's awesome! We could help you solve the problem more quickly.
- [ ] Is my description of the issue use the github markdown correctly?
   * Please use the proper markdown syntaxes for styling all forms of writing, e.g, source code, error information, etc.
   * Check out [this page](https://guides.github.com/features/mastering-markdown/) to find out much more about markdown.

**Comment by sonofaeolus** [comment]
Traceback (most recent call last):
  File "0.ptr_multi.py", line 114, in <module>
    loss_val = exe.run(main_program, feed = feeder.feed(data), fetch_list = [all_loss])
  File "/home/wangxiaoyu/python27_fluid/lib/python2.7/site-packages/paddle/fluid/executor.py", line 470, in run
    self.executor.run(program.desc, scope, 0, True, True)
paddle.fluid.core.EnforceNotMet: holder_ should not be null
Tensor holds no memory. Call Tensor::mutable_data first. at [/paddle/paddle/fluid/framework/tensor.cc:22]
PaddlePaddle Call Stacks: 
0       0x7f8b6acb5ab6p paddle::platform::EnforceNotMet::EnforceNotMet(std::__exception_ptr::exception_ptr, char const*, int) + 486
1       0x7f8b6b9914e4p paddle::framework::Tensor::check_memory_size() const + 228
2       0x7f8b6ae75361p paddle::framework::EigenVector<float, 1, long>::Flatten(paddle::framework::Tensor const&) + 81
3       0x7f8b6afed059p paddle::operators::ActivationGradKernel<paddle::platform::CPUDeviceContext, paddle::operators::ReluGradFunctor<float> >::Compute(paddle::framework::ExecutionContext const&) const + 329
4       0x7f8b6afed383p std::_Function_handler<void (paddle::framework::ExecutionContext const&), paddle::framework::OpKernelRegistrarFunctor<paddle::platform::CPUPlace, false, 0ul, paddle::operators::ActivationGradKernel<paddle::platform::CPUDeviceContext, paddle::operators::ReluGradFunctor<float> >, paddle::operators::ActivationGradKernel<paddle::platform::CPUDeviceContext, paddle::operators::ReluGradFunctor<double> > >::operator()(char const*, char const*) const::{lambda(paddle::framework::ExecutionContext const&)#1}>::_M_invoke(std::_Any_data const&, paddle::framework::ExecutionContext const&) + 35
5       0x7f8b6b92e81ep paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&) const + 526
6       0x7f8b6b92ab58p paddle::framework::OperatorBase::Run(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&) + 232
7       0x7f8b6ad790fbp paddle::framework::Executor::RunPreparedContext(paddle::framework::ExecutorPrepareContext*, paddle::framework::Scope*, bool, bool, bool) + 219
8       0x7f8b6b3eb1edp paddle::operators::WhileGradOp::RunImpl(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&) const + 1741
9       0x7f8b6b92ab58p paddle::framework::OperatorBase::Run(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&) + 232
10      0x7f8b6ad790fbp paddle::framework::Executor::RunPreparedContext(paddle::framework::ExecutorPrepareContext*, paddle::framework::Scope*, bool, bool, bool) + 219
11      0x7f8b6ad79ee0p paddle::framework::Executor::Run(paddle::framework::ProgramDesc const&, paddle::framework::Scope*, int, bool, bool) + 128
12      0x7f8b6ac9a8bdp
13      0x7f8b6aceacb4p pybind11::cpp_function::dispatcher(_object*, _object*, _object*) + 2596
14            0x4b8ba7p PyEval_EvalFrameEx + 30279
15            0x4baac8p PyEval_EvalCodeEx + 2040
16            0x4b8328p PyEval_EvalFrameEx + 28104
17            0x4baac8p PyEval_EvalCodeEx + 2040
18            0x4babf2p PyEval_EvalCode + 50
19            0x4e8addp PyRun_FileExFlags + 285
20            0x4ea361p PyRun_SimpleFileExFlags + 209
21            0x415c5dp Py_Main + 2925
22      0x7f8b8eb8bbd5p __libc_start_main + 245
23            0x414df1p

**Comment by sonofaeolus** [comment]
前向计算 使用fluid.layers.Print 可以完成 但是之后报这个bug

**Comment by kuke** [comment]
可以把你的配置贴一个么

**Comment by sonofaeolus** [comment]
> 
> 
> 可以把你的配置贴一个么

好的 稍等下

**Comment by sonofaeolus** [comment]
```
#-*-coding:utf8-*-
import paddle
import paddle.fluid as fluid
#import gen_train_vec_ptr as gen_train_vec
import gen_train_vec
from paddle.fluid.contrib.trainer import *
import paddle.fluid.framework as framework

#超参数定义
dict_size = 30000
emb_size = 64
hidden_size = 128
batch_size = 10

#word input
src_word_id = fluid.layers.data(name = 'src_word_id', shape = [1], dtype = 'int64', lod_level = 1)
biz_label = fluid.layers.data(name = 'biz_label', shape = [1], dtype = 'int64', lod_level = 1)
ctr_label = fluid.layers.data(name = 'ctr_label', shape = [1], dtype = 'int64', lod_level = 1)
biz_word_id = fluid.layers.data(name = 'biz_word_id', shape = [1], dtype = 'int64', lod_level = 1)
ctr_word_id = fluid.layers.data(name = 'ctr_word_id', shape = [1], dtype = 'int64', lod_level = 1)
#fluid.layers.Print(src_word_id)

#源词嵌入
emb_param = fluid.param_attr.ParamAttr(name = "word_emb")
src_emb = fluid.layers.embedding(input = src_word_id, size = [dict_size, emb_size], is_sparse = True, param_attr = emb_param)
#fluid.layers.Print(src_emb)

#Encoder
gru_input = fluid.layers.fc(input = src_emb, size = hidden_size * 3)
#fluid.layers.Print(gru_input)

gru_layer = fluid.layers.dynamic_gru(input = gru_input, size = hidden_size)
#fluid.layers.Print(gru_layer)

#Decoder
def train_decoder(gru_layer = gru_layer, name = "ctr"):
    gru_layer_proj = fluid.layers.fc(input = gru_layer, size = hidden_size, bias_attr = False)
    #fluid.layers.Print(gru_layer_proj)
    last_seq = fluid.layers.sequence_last_step(input = gru_layer)
    #fluid.layers.Print(last_seq)
    gru_last_proj = fluid.layers.fc(input = last_seq, size = hidden_size, bias_attr = False)
    if name == "biz":
        tgt_emb = fluid.layers.embedding(input = biz_word_id, size = [dict_size, emb_size], is_sparse = True, param_attr = emb_param)
    elif name == "ctr":
        tgt_emb = fluid.layers.embedding(input = ctr_word_id, size = [dict_size, emb_size], is_sparse = True, param_attr = emb_param)
    print tgt_emb.shape
    drnn = fluid.layers.DynamicRNN(name = name)
    with drnn.block():
        word = drnn.step_input(tgt_emb)
        print word.shape
        prev = drnn.memory(init = gru_last_proj)
        state_word = fluid.layers.fc(input = word, size = hidden_size, bias_attr = False)
        state_prev = fluid.layers.fc(input = prev, size = hidden_size, bias_attr = False)
        state_now = fluid.layers.relu(state_word + state_prev)
        state_fc_expand = fluid.layers.sequence_expand_as(x = prev, y = gru_layer_proj)
        #fluid.layers.Print(state_fc_expand)
        mix_layer = state_fc_expand + gru_layer_proj
        mix_act = fluid.layers.tanh(mix_layer)
        print mix_layer.shape
        att_layer = fluid.layers.fc(input = mix_act, size = dict_size)
        print att_layer.shape
        #sum_layer = fluid.layers.sum(x = att_layer)
        sum_layer = fluid.layers.sequence_pool(input = att_layer, pool_type = 'sum')
        #sum_layer = fluid.layers.reduce_sum(att_layer, dim = 0, keep_dim = True)
        #fluid.layers.Print(sum_layer)
        print sum_layer.shape
        att_weight = fluid.layers.softmax(sum_layer)
        drnn.update_memory(prev, state_now)
        drnn.output(att_weight)
    return drnn()
        
#定义损失函数
def train_loss():
    decoder_biz = train_decoder(name = 'biz', gru_layer = gru_layer)
    #fluid.layers.Print(decoder_biz)
    decoder_ctr = train_decoder(name = 'ctr', gru_layer = gru_layer)
    #fluid.layers.Print(decoder_ctr)
    print biz_label.shape
    biz_loss = fluid.layers.reduce_sum(fluid.layers.cross_entropy(input = decoder_biz, label = biz_label))
    #fluid.layers.Print(biz_loss)
    ctr_loss = fluid.layers.reduce_sum(fluid.layers.cross_entropy(input = decoder_ctr, label = ctr_label))
    biz_maxpool = fluid.layers.sequence_pool(input = decoder_biz, pool_type = 'max')
    #fluid.layers.Print(biz_maxpool)
    ctr_maxpool = fluid.layers.sequence_pool(input = decoder_ctr, pool_type = 'max')
    print biz_maxpool.shape, ctr_maxpool.shape
    #fluid.layers.Print(ctr_maxpool/ctr_maxpool)
    sim_loss = fluid.layers.reduce_sum(biz_maxpool - ctr_maxpool)
    print sim_loss.shape, ctr_loss.shape, sim_loss.shape
    #fluid.layers.Print(sim_loss)
    all_loss = biz_loss + ctr_loss + sim_loss
    fluid.layers.Print(sim_loss)
    return sim_loss

#定义优化器
optimizer = fluid.optimizer.Adam(learning_rate = 0.0002)

#读取训练数据

#Train proc
place = fluid.CPUPlace()
train_reader = paddle.batch(paddle.reader.shuffle(gen_train_vec.train(dict_size), buf_size = 100), batch_size = 1)
#trainer = Trainer(train_func = train_loss, place = place, optimizer_func = optimizer)
#trainer.train(reader = train_reader, num_epochs = 100, event_handler = event_handler, feed_order = feed_order)
all_loss = train_loss()
optimizer.minimize(all_loss)
exe = fluid.Executor(place)
exe.run(fluid.default_startup_program())
feed_order = [src_word_id, ctr_word_id, ctr_label, biz_word_id, biz_label]
feeder = fluid.DataFeeder(feed_list = feed_order, place=place)
main_program = fluid.default_main_program()
for batch_id, data in enumerate(train_reader()):
    print len(data)
    print feeder.feed(data)
    loss_val = exe.run(main_program, feed = feeder.feed(data), fetch_list = [all_loss])
    print "batch %d loss: %f" % (batchid, loss_val[0])
```

**Comment by sonofaeolus** [comment]
> 
> 
> > 可以把你的配置贴一个么
> 
> 好的 稍等下

已经贴了

**Comment by kuke** [comment]
@sonofaeolus 可能的原因是在RNN里面`state_now`没有接输出，导致最后一个时间步`state_now`悬空了，不能传回梯度，导致ReLU的反向出错。

有个办法可能可以绕过这个问题，即在RNN里面只计算`state_now`并作为输出，`att_weight`可以放在RNN外面计算

**Comment by lucywsq** [comment]
您好，此issue在近一个月内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题，我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持
