### ISSUE TITLE
请问Paddle如何添加fusion的op

### ISSUE THREAD

**Issue by shijiaxin** [PaddlePaddle/Paddle#14554]
现在我们在Paddle里新增一种Place，实现了相应的Kernel。
现在希望能提高inference时候的性能，比如将conv和bn的kernel做kernel fusion，用一个kernel实现。
请问paddle是否支持？如果支持的话，需要如何新增代码？

**Comment by chengduoZH** [comment]
> 现在我们在Paddle里新增一种Place，实现了相应的Kernel。

为什么要新增Place呢？ 在Fluid的设计中，Place和内存地址有关，所以对于GPU和CPU分别有CPUPlace和GPUPlace，您新加的这个Place是什么含义呢？

> 比如将conv和bn的kernel做kernel fusion

将这两个Op融合之后就变成了新的Op，而不是新的Op Kernel

**Comment by luotao1** [comment]
> 现在希望能提高inference时候的性能，比如将conv和bn的kernel做kernel fusion，用一个kernel实现

conv+bn的fuse，现在已经实现了，请参考https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/fluid/framework/ir/conv_bn_fuse_pass.cc

**Comment by shijiaxin** [comment]
> > 现在我们在Paddle里新增一种Place，实现了相应的Kernel。
> 
> 为什么要新增Place呢？ 在Fluid的设计中，Place和内存地址有关，所以对于GPU和CPU分别有CPUPlace和GPUPlace，您新加的这个Place是什么含义呢？
> 
> > 比如将conv和bn的kernel做kernel fusion
> 
> 将这两个Op融合之后就变成了新的Op，而不是新的Op Kernel

新的Place是对应新的设备，区别与GPU和CPU的某种特殊硬件。
是的，我们就想要有个新的Op。

**Comment by shijiaxin** [comment]
> > 现在希望能提高inference时候的性能，比如将conv和bn的kernel做kernel fusion，用一个kernel实现
> 
> conv+bn的fuse，现在已经实现了，请参考https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/fluid/framework/ir/conv_bn_fuse_pass.cc

好的谢谢。这个是如何实现的，那假如我想要试着跑跑看这个已经实现的版本，该如何修改python脚本呢？能大致说一下吗？以Resnet50为例：https://github.com/dzhwinter/benchmark/blob/master/fluid/resnet50.py

**Comment by luotao1** [comment]
这个是用于C++预测。
python预测请见`inference_transpiler.py`（该接口已不再维护，后续会重新发布）：https://github.com/PaddlePaddle/Paddle/blob/dd6fd4c747df9ad5ffdf0f6eef8ef3683df871cb/python/paddle/fluid/transpiler/inference_transpiler.py#L300

使用方式见：
https://github.com/PaddlePaddle/Paddle/blob/dd6fd4c747df9ad5ffdf0f6eef8ef3683df871cb/python/paddle/fluid/tests/book/test_image_classification.py#L224-L227

**Comment by qingqing01** [comment]
@shijiaxin

一般分2步： 

1. 写fusion的op及kernel:

例如： conv+bias+act的fusion: https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/fluid/operators/conv_fusion_op.cc
例如： 其他op的fusion:  https://github.com/PaddlePaddle/Paddle/tree/develop/paddle/fluid/operators/fused

2. 写IR Pass做自动融合：

https://github.com/PaddlePaddle/Paddle/tree/develop/paddle/fluid/framework/ir

**Comment by dzhwinter** [comment]
Place代表地址空间，如果新硬件有这种特性，可以定义一个新的Place

**Comment by lucywsq** [comment]
您好，鉴于您的问题已经解决，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题，我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持
