### ISSUE TITLE
Is there any way to make paddle fluid does not initialize with gpu memory occupation?

### ISSUE THREAD

**Issue by TheodoreG** [PaddlePaddle/Paddle#14559]
Hi guys, I found that with "import paddle.fluid as fluid" all capable gpus will be initialized with a mall portion of gpu memories, about 313 MB. However for some training role like "pserver" they do not need gpu memories. Making pserver occupying gpus is a kind of waste.
Is there any way to restrain such gpu occupation?
Thanks a lot.

**Comment by chengduoZH** [comment]
You can use `export CUDA_VISIBLE_DEVICES=X,X`.
