### ISSUE TITLE
 op auc does not have kernel for data_type[float]

### ISSUE THREAD

**Issue by 333caowei** [PaddlePaddle/Paddle#14566]
本地cpu训练正常，gpu训练提示 op auc does not have kernel for data_type[float]
涉及代码如下：
```
binary_prediction = fluid.layers.concat(input=[1.0 - prediction, prediction], axis=1)
int_label = fluid.layers.cast(x=self.label, dtype='int64')
auc = fluid.layers.auc(input=binary_prediction, label=int_label)

```

<img width="1280" alt="image" src="https://user-images.githubusercontent.com/4569055/48938472-4d67c780-ef4c-11e8-9641-8b0d1b5b809a.png">

**Comment by chengduoZH** [comment]
您好，最新develop分支已经修复了这个问题，请pull最新的代码编译使用。
