### ISSUE TITLE
Fluid报错：AttributeError: 'tuple' object has no attribute 'name'

### ISSUE THREAD

**Issue by CruiseSun** [PaddlePaddle/Paddle#14567]
报错如下：
Traceback (most recent call last):
  File "train.py", line 808, in <module>
    main(USE_GPU)
  File "train.py", line 804, in main
    params_dirname=params_dir)
  File "train.py", line 794, in train
    feed_order=feed_order)
  File "/home/work/.jumbo/lib/python2.7/site-packages/paddle/fluid/contrib/trainer.py", line 405, in train
    feed_order)
  File "/home/work/.jumbo/lib/python2.7/site-packages/paddle/fluid/contrib/trainer.py", line 483, in _train_by_executor
    self._train_by_any_executor(event_handler, exe, num_epochs, reader)
  File "/home/work/.jumbo/lib/python2.7/site-packages/paddle/fluid/contrib/trainer.py", line 512, in _train_by_any_executor
    for var in self.train_func_outputs
AttributeError: 'tuple' object has no attribute 'name'

**Comment by CruiseSun** [comment]
部分代码如下：
def train(use_cuda, train_program, params_dirname):
    place = fluid.CUDAPlace(0) if use_cuda else fluid.CPUPlace()
    trainer = Trainer(
        train_func=train_program, place=place, optimizer_func=optimizer_func)

    feed_order = [
        'scene_type', 'app_id', 'd_item_type', 'd_cluster_id', 'd_category_id', 'd_tags', 'd_quality_level',
        'd_source_domain', 'd_item_type_crss_d_category_id', 'd_item_type_crss_d_tags',
        'd_item_type_crss_d_quality_level', 'hour', 'item_type', 'cluster_id', 'category_id', 'tags', 'quality_level',
        'source_name', 'source_domain', 'title_segs', 'feeds_type', 'diff_time', 'duration_halfminut',
        'image_count_dscr', 'item_type_crss_category_id', 'item_type_crss_tags', 'item_type_crss_quality_level',
        'item_type_crss_diff_time', 'category_id_crss_source_name', 'category_id_crss_title_segs',
        'category_id_crss_tags', 'category_id_crss_quality_level', 'category_id_crss_diff_time', 'user', 'city',
        'session_click_num_dscr', 'session_exposure_num_dscr', 'session_click_items', 'session_exposure_items',
        'session_click_terms', 'session_exposure_terms', 'session_click_categories', 'session_exposure_categories',
        'session_click_tags', 'session_exposure_tags', 'session_click_category_level',
        'session_exposure_category_level', 'history_click_num_dscr', 'history_exposure_num_dscr',
        'history_click_items', 'history_exposure_items', 'history_click_terms', 'history_exposure_terms',
        'history_click_categories', 'history_exposure_categories', 'history_click_tags', 'history_exposure_tags',
        'history_click_category_level', 'history_exposure_category_level', 'label'
    ]

    train_reader = paddle.v2.batch(
        paddle.v2.reader.shuffle(
            reader.train_reader(train_path='./train'),
            buf_size=10),
        batch_size=BATCH_SIZE)

    test_reader = paddle.v2.batch(
        reader.test_reader(test_path='./test'),
        batch_size=BATCH_SIZE)

    def event_handler(event):
        if isinstance(event, EndStepEvent):
            if event.step % 10 == 0:
                print("\nPass %d, Batch %d, Cost %f, Auc %f" %
                      (event.epoch, event.step, event.metrics[0],
                       event.metrics[1]))
            else:
                sys.stdout.write('.')
                sys.stdout.flush()

        if isinstance(event, EndEpochEvent):
            avg_cost, auc = trainer.test(
                reader=test_reader, feed_order=feed_order)

            print('\nTest with Pass {0}, Loss {1:2.2}, Auc {2:2.2}'.format(
                event.epoch, avg_cost, auc))
            if params_dirname is not None:
                trainer.save_params(params_dirname)

    trainer.train(
        num_epochs=1,
        event_handler=event_handler,
        reader=train_reader,
        feed_order=feed_order)

**Comment by chengduoZH** [comment]
你可以贴一下`train_program`的函数实现吗？错误显示您这个函数的输出有问题
```
File "/home/work/.jumbo/lib/python2.7/site-packages/paddle/fluid/contrib/trainer.py", line 512, in _train_by_any_executor
for var in self.train_func_outputs
AttributeError: 'tuple' object has no attribute 'name'
```

**Comment by CruiseSun** [comment]
`def train_program():

    predict, binary_predict = inference_program()

    label = fluid.layers.data(name='label', shape=[1], dtype='int64')
    print(predict)
    print(binary_predict)
    print(label)
    cost = fluid.layers.cross_entropy(input=predict, label=label)
    avg_cost = fluid.layers.mean(x=cost)

    auc = fluid.layers.auc(input=binary_predict, label=label)

    return [avg_cost, auc]`

**Comment by chengduoZH** [comment]
I see, this is because the return of `auc` have multi-values, but `Trainer` thinks the `train_func_outputs` should be a list of variable. For hot fix, you can make the return of `train_program` be a list of variable.

https://github.com/PaddlePaddle/Paddle/blob/e52d90a35e19301bbd8db354b17c3890c069cf9c/python/paddle/fluid/layers/metric_op.py#L190-L192

--- 

The high-level API is not yet stable, I recommend that you do not use the high-level API. If you insist on using it, please refer to the source code.
https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/fluid/contrib/trainer.py#L169
