### ISSUE TITLE
v2 api parameters.get not returning value of parameters.set

### ISSUE THREAD

**Issue by helinwang** [PaddlePaddle/Paddle#1457]
```python
    for param_name in parameters.keys():
        array = parameters.get(param_name)
        array = numpy.random.uniform(low=-1.0, high=1.0, size=array.shape)
        print array # 1st time
        parameters.set(parameter_name=param_name, value=array)

    for param_name in parameters.keys():
        array = parameters.get(param_name)
        print array # 2nd time
```
The array being printed second time is still a non-initialized array.
I think it's because https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/v2/parameters.py#L126
```python
if len(self.__gradient_machines__) == 0:
            # create new parameter in python numpy.
            return np.ndarray(shape=shape, dtype=np.float32)
```
parameters will always return a non-initialized array even after parameter has being set.

From users' standpoint, I think get should return the array being set regardless parameters is attached to gradient machine or not.

**Comment by Yancey1989** [comment]
Close the inactive issue, please reopen it for free.
