### ISSUE TITLE
目前只有SSD模型可以用于目标检测，建议添加模型支持训练目标追踪

### ISSUE THREAD

**Issue by HoustonDuane** [PaddlePaddle/Paddle#14576]

**Comment by wanghaoshuang** [comment]
感谢反馈，我们会考虑将该提议纳入规划。

**Comment by lucywsq** [comment]
您好，您的建议已经被记录，鉴于此issue在近一个月内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题，我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持!
