### ISSUE TITLE
根本就不支持pip 安装

### ISSUE THREAD

**Issue by zhouhao-learning** [PaddlePaddle/Paddle#14572]
你们官网说支持pip方式安装，可是，当我执行pip install paddlepaddle时，却是如下结果:
```
Collecting paddlepaddle==1.1.0
Cache entry deserialization failed, entry ignored
Could not find a version that satisfies the requirement paddlepaddle==1.1.0 (from versions: )
No matching distribution found for paddlepaddle==1.1.0
You are using pip version 9.0.1, however version 18.1 is available.
```
我的系统是ubuntu16.04

**Comment by shanyi15** [comment]
hi @zhouhao-learning，请问您的pip源是否更改过呢，请您尝试以下命令能否解决您的问题：
`pip install paddlepaddle==1.1.0 -i  https://pypi.doubanio.com/simple/  --trusted-host pypi.doubanio.com`

**Comment by zhouhao-learning** [comment]
@shanyi15 
您提供的方法没有用，还是一样的错误

**Comment by shanyi15** [comment]
您好，由于不清楚您的环境，我们无法复现您的问题，根据您的报错信息，请问您是否用了anaconda？请看[这里](https://blog.csdn.net/shanpenghui/article/details/80564268)

**Comment by zhouhao-learning** [comment]
@shanyi15 
你好，你提供的方法虽然能正确安装，但是我安装失败的原因不是因为我使用了anaconda,根本原因是你们的paddlepaddle不支持python3.6,仅仅支持python3.5和python2.7

**Comment by lucywsq** [comment]
@zhouhao-learning 您好，目前PaddlePaddle支持Python版本是3.5和2.7。Python3.6及Python3.7版本都在PaddlePaddle的支持计划中。其中Python3.6支持已经进入研发阶段，预计在未来的2个月会完成稳定支持。您可以根据自己的使用需要来进行选择~

**Comment by MOONSky1996** [comment]
ERROR: Could not find a version that satisfies the requirement paddlepaddle==1.6.1 (from versions: 1.8.5, 2.0.0rc0, 2.0.0rc1, 2.0.0, 2.0.1, 2.0.2, 2.1.0, 2.1.1, 2.1.2, 2.1.3, 2.2.0rc0, 2.2.0, 2.2.1, 2.2.2)
ERROR: No matching distribution found for paddlepaddle==1.6.1
旧版本现在不提供了，用pip3 install paddlepaddle -i https://pypi.doubanio.com/simple/ --trusted-host pypi.doubanio.com不限制版本亲测可行

**Comment by shuangxi2006** [comment]
ERROR: Could not install packages due to an OSError: [Errno 2] No such file or directory: 'C:\\Users\\~~~\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\paddle\\include\\paddle\\phi\\kernels\\fusion\\cutlass\\memory_efficient_attention\\iterators\\epilogue_predicated_tile_iterator.h'

用上面的办法安装会出现头文件丢失的情况。


> ERROR: Could not find a version that satisfies the requirement paddlepaddle==1.6.1 (from versions: 1.8.5, 2.0.0rc0, 2.0.0rc1, 2.0.0, 2.0.1, 2.0.2, 2.1.0, 2.1.1, 2.1.2, 2.1.3, 2.2.0rc0, 2.2.0, 2.2.1, 2.2.2) ERROR: No matching distribution found for paddlepaddle==1.6.1 旧版本现在不提供了，用pip3 install paddlepaddle -i https://pypi.doubanio.com/simple/ --trusted-host pypi.doubanio.com不限制版本亲测可行
