### ISSUE TITLE
fluid c++预测时报内存相关错误

### ISSUE THREAD

**Issue by shindou** [PaddlePaddle/Paddle#14598]
- 版本、环境信息：
    1）PaddlePaddle版本：离线训练版本 v0.14.0
    2）GPU：false
    3）系统环境：CentOS 6.3

- 预测信息
    1）预测库来源：官网下载（v1.1页面提供的cpu_avx_mkl下载链接）
    2）安装包版本信息
           a) GIT COMMIT ID: 05c15a08674bc7a1b08bda32eb6bf4194f3423e9
           b) WITH_MKL: OFF
           c) WITH_MKLDNN: OFF
           d) WITH_GPU: OFF

- 问题描述： 在并发预测情况下出现几种不同的内存报错

1. 使用官网提供的情感分类模型Senta进行离线训练， 预测，均正常（https://github.com/baidu/Senta/blob/master/README.md）
2. 线上c++预测时出现多种报错交替出现,  在NativeConfig情况下会出现以下几种报错
有一种是 malloc(): smallbin double linked list corrupted
![b15851c5697d4283fdb0830bba32916e](https://user-images.githubusercontent.com/1444854/49011577-c9167e00-f1b1-11e8-8d43-bab9d8adf480.jpg)
其他几种是paddle::AnalysisPredictor::Run()下的报错：
![image](https://user-images.githubusercontent.com/1444854/49011791-50fc8800-f1b2-11e8-8076-8210dcb90826.png)
![image](https://user-images.githubusercontent.com/1444854/49011809-61146780-f1b2-11e8-8cfa-8a7870f7d9f5.png)
![image](https://user-images.githubusercontent.com/1444854/49011835-78535500-f1b2-11e8-81bb-17437d789a7e.png)

4.  如果使用AnalysisConfig预测， 固定好相同的输入，反复调用infer函数，会有一定概率出现预测值与应该输出的预测值不一致的情况。 最后以malloc(): smallbin double linked list corrupted报错结束

3.  代码如下:
```
remove
```

**Comment by shindou** [comment]
补充一下：
4.  如果使用AnalysisConfig预测， 固定好相同的输入，反复调用infer函数，会有一定概率出现预测值与应该输出的预测值不一致的情况。 最后以malloc(): smallbin double linked list corrupted报错结束

**Comment by Superjomn** [comment]
线下已经沟通，有后续问题可以 reopen
