### ISSUE TITLE
fluid版本Embeding参数初始化问题

### ISSUE THREAD

**Issue by urnotdfs** [PaddlePaddle/Paddle#14596]
我想对embedding的参数做初始化，在相关文档中看到了v2的写法
<img width="482" alt="e0305cea9c088cea92bed381307eccb1" src="https://user-images.githubusercontent.com/30000786/49010411-23addb00-f1ae-11e8-96c0-713549e78cd4.png">
但在fluid中没有initial_std，我换成了fluid.initializer.Normal:
embed_param = fluid.ParamAttr(name="shared_w", initializer=fluid.initializer.Normal(loc=1, scale=1))但是加上fluid.initializer.Normal的时候会报错
![ad38eeec72a5268bf464fcb88f8663bb](https://user-images.githubusercontent.com/30000786/49010435-36281480-f1ae-11e8-9f50-e3e144f0cf62.png)

报错信息：
![178aa14a17d730fe301620c1b0dd6bad](https://user-images.githubusercontent.com/30000786/49010806-4a204600-f1af-11e8-9f8a-b5515838f90b.png)

辛苦相关同学帮忙看下问题出在哪，谢谢

**Comment by jacquesqiao** [comment]
```python
embed_param = fluid.ParamAttr(name="shared_w", initializer=fluid.initializer.Normal(loc=1.0, scale=1.0))
```
这么写，把整数换成浮点数

**Comment by urnotdfs** [comment]
解决了，谢谢~

**Comment by lucywsq** [comment]
您好，鉴于此问题已经解决，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题，
我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持!
