### ISSUE TITLE
The way the multithread mode is enabled has changed?

### ISSUE THREAD

**Issue by wojtuss** [PaddlePaddle/Paddle#14594]
A few days ago, when I was running a C-API inference application for MobileNet-SSD or any other model on CPU with a flag `FLAGS_paddle_num_threads` set to > 1, the inference run on multiple threads. With the current version of PaddlePaddle it does not work any more, i.e. the app runs only on a single thread.
How should I set the number of cores to use in the C-API app now?

**Comment by luotao1** [comment]
#14543 fix this problem, you can use the latest code to try again.

**Comment by kbinias** [comment]
It also doesn't work on the latest version of code:
commit 6224e61fd94e6ad87f18c2808a76256b516fa3f3
Author: qingqing01 <dangqingqing@baidu.com>
Date:   Mon Nov 26 15:54:39 2018 +0800

**Comment by luotao1** [comment]
You can use the command
```
./paddle/fluid/inference/tests/api/test_analyzer_resnet50 --infer_model=third_party/inference_demo/resnet50/model/ --gtest_filter=Analyzer_resnet50.profile_mkldnn --paddle_num_threads=2 --repeat=100 --batch_size=1 --num_threads=2
```

**Comment by wojtuss** [comment]
@luotao1, @kbinias, I confirm it works after adding
```
config.SetCpuMathLibraryNumThreads(14);
```
to my `AnalysisConfig`.

**Comment by wojtuss** [comment]
@luotao1, do we also have to use `analysis_predictor->SetMKLDNNThreadId()` in our standalone application when running with MKL-DNN?

**Comment by kbinias** [comment]
Thanks, so problem was on our side (our C-API application).

**Comment by luotao1** [comment]
@wojtuss Yes, `analysis_predictor->SetMKLDNNThreadId()` is added by your sides https://github.com/PaddlePaddle/Paddle/pull/14543/files#diff-de28fd15f9d03473704e18c205add315L218 , we only encapsulation it.

**Comment by wojtuss** [comment]
@luotao1 , thank you!
