### ISSUE TITLE
运行SSD物体检测中train.py报错NoneType is not iterable

### ISSUE THREAD

**Issue by xiaochunWu** [PaddlePaddle/Paddle#14601]
PaddlePaddle版本为1.1.0
CPU为i7-6700K
GPU为1080
系统为ubuntu16.04
在跑https://github.com/PaddlePaddle/models/blob/develop/fluid/PaddleCV/object_detection/train.py这个代码时报错如下：
/home/aeta/anaconda3/lib/python3.5/site-packages/paddle/fluid/evaluator.py:71: Warning: The DetectionMAP is deprecated, because maintain a modified program inside evaluator cause bug easily, please use fluid.metrics.DetectionMAP instead.
  % (self.__class__.__name__, self.__class__.__name__), Warning)
loading annotations into memory...
Done (t=12.81s)
creating index...
index created!
train on coco2017 with 118287 images
loading annotations into memory...
Done (t=0.44s)
creating index...
index created!
test on coco2017 with 5000 images
*** Aborted at 1543233201 (unix time) try "date -d @1543233201" if you are using GNU date ***
PC: @                0x0 (unknown)
*** SIGTERM (@0x3e8000029f5) received by PID 10852 (TID 0x7f9580afd700) from PID 10741; stack trace: ***
    @     0x7f9659ade390 (unknown)
    @     0x7f9659d9a65a insertdict
    @     0x7f9659d9b198 _PyObjectDict_SetItem
    @     0x7f9659da9a24 _PyObject_GenericSetAttrWithDict
    @     0x7f9659da9e0a PyObject_SetAttr
    @     0x7f9659e2a081 PyEval_EvalFrameEx
    @     0x7f9659e2eb49 _PyEval_EvalCodeWithName
    @     0x7f9659e2ddf5 PyEval_EvalFrameEx
    @     0x7f9659e2e166 PyEval_EvalFrameEx
    @     0x7f9659e2e166 PyEval_EvalFrameEx
    @     0x7f9659e2eb49 _PyEval_EvalCodeWithName
    @     0x7f9659e2ecd8 PyEval_EvalCodeEx
    @     0x7f9659d84542 function_call
    @     0x7f9659d51236 PyObject_Call
    @     0x7f9659d52d65 callmethod
    @     0x7f9659d54560 _PyObject_CallMethodId
    @     0x7f9659e24606 PyEval_ReInitThreads
    @     0x7f9659e743ad PyOS_AfterFork
    @     0x7f9659e79596 os_fork
    @     0x7f9659e2d5f9 PyEval_EvalFrameEx
    @     0x7f9659e2e166 PyEval_EvalFrameEx
    @     0x7f9659e2eb49 _PyEval_EvalCodeWithName
    @     0x7f9659e2ecd8 PyEval_EvalCodeEx
    @     0x7f9659d84542 function_call
    @     0x7f9659d51236 PyObject_Call
    @     0x7f9659d6d77c method_call
    @     0x7f9659d51236 PyObject_Call
    @     0x7f9659dc24c3 slot_tp_init
    @     0x7f9659db8daf type_call
    @     0x7f9659d51236 PyObject_Call
    @     0x7f9659e2b314 PyEval_EvalFrameEx
    @     0x7f9659e2e166 PyEval_EvalFrameEx
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/home/aeta/anaconda3/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/home/aeta/anaconda3/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/home/aeta/anaconda3/lib/python3.5/site-packages/paddle/fluid/layers/io.py", line 659, in __provider_thread__
    for tensors in func():
  File "/home/aeta/anaconda3/lib/python3.5/site-packages/paddle/fluid/layers/io.py", line 702, in __tensor_provider__
    for slots in paddle_reader():
  File "/home/aeta/anaconda3/lib/python3.5/site-packages/paddle/fluid/data_feeder.py", line 277, in __reader_creator__
    yield self.feed(item)
  File "/home/aeta/anaconda3/lib/python3.5/site-packages/paddle/fluid/data_feeder.py", line 188, in feed
    for each_sample in iterable:
TypeError: 'NoneType' object is not iterable

初步筛选为数据读取问题，但是因为没有报错点所以没办法进一步定位问题。求帮助，多谢~

**Comment by qingqing01** [comment]
@Renewing 可以参考 https://github.com/PaddlePaddle/Paddle/issues/14476 .

**Comment by xiaochunWu** [comment]
@qingqing01 我看到这个issue了，但是没有理解里面的修改尺寸是什么意思，是修改缩放之前的图片尺寸吗？这样的话是不是可以归类为显存太小？多谢~

**Comment by xiaochunWu** [comment]
@qingqing01 我把batch_size改为1之后还是报同样的错，好像不是显存的问题

**Comment by qingqing01** [comment]
@Renewing  你这个问题不是显存问题，是reader数据有误。 参考 https://github.com/PaddlePaddle/Paddle/issues/14476#issuecomment-439750551 这里给的可能调试地方，打印看下吧

**Comment by xiaochunWu** [comment]
@qingqing01 谢谢大佬，这个bug解决了。但是现在在跑的时候又遇到segmentation fault的错误，具体如下：
*** Aborted at 1543245429 (unix time) try "date -d @1543245429" if you are using GNU date ***
PC: @                0x0 (unknown)
*** SIGSEGV (@0x0) received by PID 30554 (TID 0x7fdfd6b97700) from PID 0; stack trace: ***
    @     0x7fdfd629f390 (unknown)
    @                0x0 (unknown)
Segmentation fault (core dumped)
麻烦大佬

**Comment by qingqing01** [comment]
请去掉 ‘大佬’  :)

1. 可以补充下怎么解决的  `TypeError: 'NoneType' object is not iterable` 问题吗？ 可以帮助其他遇到类似问题的人。
2. segmentation fault 错误信息有点少，看不出来问题，麻烦多提供一些信息。

**Comment by xiaochunWu** [comment]
@qingqing01 哈哈，问题已经解决，是自己读取图片的时候路径出了问题，至于segmentation fault也解决了，是因为paddlepaddle的版本和cudnn版本不协调，更换版本后问题解决，多谢大佬~

**Comment by Renewing** [comment]
@qingqing01 问题已经解决。'NoneType' object is not iterable是因为数据读取的时候路径有问题，修改后问题解决；segmentation fault是因为paddlepaddle的版本和cudnn的版本不协调，卸载重装后问题解决，多谢大佬哈~
