### ISSUE TITLE
【Question】关于LSTM网络使用问题

### ISSUE THREAD

**Issue by LoganZhou** [PaddlePaddle/Paddle#1461]
想使用LSTM网络来进行训练，参考`trainer_config.lstm.py`文件对`trainer_config.py`进行修改，但训练报错
```
I0225 17:12:06.709349 17327 Trainer.cpp:175] trainer mode: Normal
I0225 17:12:06.770145 17327 PyDataProvider2.cpp:243] loading dataprovider dataprovider::process
I0225 17:12:06.784571 17327 PyDataProvider2.cpp:243] loading dataprovider dataprovider::process
I0225 17:12:06.786155 17327 GradientMachine.cpp:135] Initing parameters..
I0225 17:12:06.796674 17327 GradientMachine.cpp:142] Init parameters done.
F0225 17:12:58.758431 17327 LstmLayer.cpp:155] Check failed: input.sequenceStartPositions 
*** Check failure stack trace: ***
    @           0x93ca56  google::LogMessage::Fail()
    @           0x93c9a2  google::LogMessage::SendToLog()
    @           0x93c326  google::LogMessage::Flush()
    @           0x93f3c5  google::LogMessageFatal::~LogMessageFatal()
    @           0x640b87  paddle::LstmLayer::forward()
    @           0x6c9e60  paddle::NeuralNetwork::forward()
    @           0x6bc453  paddle::GradientMachine::forwardBackward()
    @           0x75786d  paddle::TrainerInternal::forwardBackwardBatch()
    @           0x757dec  paddle::TrainerInternal::trainOneBatch()
    @           0x752cf0  paddle::Trainer::trainOneDataBatch()
    @           0x7554ef  paddle::Trainer::trainOnePass()
    @           0x756900  paddle::Trainer::train()
    @           0x5c6913  main
    @     0x2b87548e9d1d  __libc_start_main
    @           0x5dcb41  (unknown)
/usr/local/Paddle-GPU/bin/paddle: line 109: 17327 Aborted                 (core dumped) ${DEBUGGER} $MYDIR/../opt/paddle/bin/paddle_trainer ${@:2}
```
LSTM构建部分如下：
```py
output_label = []
link_encode = data_layer(name='link_encode', size=TERM_NUM)
for i in xrange(FORECASTING_NUM):
    link_param = ParamAttr(
        name='_link_vec.w', initial_max=1.0, initial_min=-1.0)
    link_vec = fc_layer(input=link_encode, size=emb_size, param_attr=link_param)
    lstm = simple_lstm(
        input=link_vec, size=emb_size, lstm_cell_attr=ExtraAttr(drop_rate=0.25))
    score = fc_layer(input=lstm, size=4, act=SoftmaxActivation())
    if is_predict:
        maxid = maxid_layer(score)
        output_label.append(maxid)
    else:
        label = data_layer(name='label_%dmin' % ((i + 1) * 5), size=4)
        cls = classification_cost(
            input=score, name="cost_%dmin" % ((i + 1) * 5), label=label)
        output_label.append(cls)
outputs(output_label)
```

之前也参考文档使用`mixed_layer`来进行搭建LSTM，但也是报错
想知道这样构建错在哪里，望解答，谢谢！

**Comment by luotao1** [comment]
请提供对应的dataprovider.py文件

**Comment by LoganZhou** [comment]
```py
from paddle.trainer.PyDataProvider2 import *
import sys
import numpy as np
TERM_NUM = 24
FORECASTING_NUM = 24
LABEL_VALUE_NUM = 4

def initHook(settings, file_list, **kwargs):
    """
    Init hook is invoked before process data. It will set obj.slots and store data meta.

    :param settings: global object. It will passed to process routine.
    :type obj: object
    :param file_list: the meta file object, which passed from trainer_config.py,but unused in this function.
    :param kwargs: unused other arguments.
    """
    del kwargs  #unused 

    settings.pool_size = sys.maxint
    #Use a time seires of the past as feature.
    #Dense_vector's expression form is [float,float,...,float]
    settings.input_types = [dense_vector(TERM_NUM)]
    #There are next FORECASTING_NUM fragments you need predict.
    #Every predicted condition at time point has four states.
    for i in range(FORECASTING_NUM):
        settings.input_types.append(integer_value(LABEL_VALUE_NUM))

@provider(
    init_hook=initHook, cache=CacheType.CACHE_PASS_IN_MEM, should_shuffle=True)
def process(settings, file_name):
    with open(file_name) as f:
        #abandon fields name
        f.next()
        for row_num, line in enumerate(f):
            speeds = map(int, line.rstrip('\r\n').split(",")[1:])
            # Get the max index.
            end_time = len(speeds)
            # Scanning and generating samples
            for i in range(TERM_NUM, end_time - FORECASTING_NUM):
                # For dense slot
                pre_spd = map(float, speeds[i - TERM_NUM:i])

                # Integer value need predicting, values start from 0, so every one minus 1.
                fol_spd = [j - 1 for j in speeds[i:i + FORECASTING_NUM]]

                # Predicting label is missing, abandon the sample.
                if -1 in fol_spd:
                    continue
                yield [pre_spd] + fol_spd

def predict_initHook(settings, file_list, **kwargs):
    settings.pool_size = sys.maxint
    settings.input_types = [dense_vector(TERM_NUM)]


@provider(init_hook=predict_initHook, should_shuffle=False)
def process_predict(settings, file_name):
    with open(file_name) as f:
        #abandon fields name
        f.next()
        for row_num, line in enumerate(f):
            speeds = map(int, line.rstrip('\r\n').split(","))
            end_time = len(speeds)
            pre_spd = map(float, speeds[end_time - TERM_NUM:end_time])
            yield pre_spd

```

以上是dataprovider.py文件，传送格式是[[向量1]向量2]

**Comment by luotao1** [comment]
可参考语义角色标注的[dataprovider.py](https://github.com/PaddlePaddle/book/blob/develop/label_semantic_roles/dataprovider.py)

使用`integer_value_sequence`和`dense_vector_sequence`来表示序列数据。

**Comment by pwllr** [comment]
@luotao1 请问如果dataprovider.py文件，传送格式是[[向量1，[向量2]，[向量3]]，向量2]，这样的，如何指定dense_vector_sequence（）后面括号中传入的参数呢？？

**Comment by 7633** [comment]
Guys, please, speak english. It's english-speaking forum.
@luotao1 Could you explain why we need to change to `integer_value_sequence` and `dense_vector_sequence`? In _initHook_ we define, that input is dense_vector_sequence. It's OK, but when we define output:
   ```
 for i in range(FORECASTING_NUM):
        settings.input_types.append(integer_value(LABEL_VALUE_NUM))
```
why we need to change `integer_value` to `integer_value_sequence` if we only classify sequence to one of this values [1,2,3,4]?

**Comment by LoganZhou** [comment]
Thank you !
I've solved this problem. In _initHook_ I define input like this:
```py
settings.input_types = {
        'data': integer_value_sequence(TERM_NUM),
        'label': integer_value_sequence(1)
    }
```

**Comment by luotao1** [comment]
@7633 
> Every predicted condition at time point has four states

"time point" means that the output is a sequence data too.

**Comment by luotao1** [comment]
@pwllr 

> [[向量1，[向量2]，[向量3]]，向量2]

the dense_vector_sequence is [[f, ...], [f, ...], ..., [f, ...]], it not fit your style.

**Comment by From00** [comment]
@luotao1 
We define input:
`settings.input_types = [dense_vector_sequence(TERM_NUM)]
    for i in range(FORECASTING_NUM):
	 settings.input_types.append(integer_value_sequence(1))`

and provide data like this: 
`                # For dense slot
                pre_spd = map(float, speeds[i - TERM_NUM:i])

                 # Integer value need predicting, values start from 0, so every one minus 1.
                fol_spd = [j - 1 for j in speeds[i:i + FORECASTING_NUM]]

                # Predicting label is missing, abandon the sample.
                if -1 in fol_spd:
                     continue

                yield [pre_spd] + fol_spd`
 
But it dose not work:
`I0228 14:57:51.075773 20818 GradientMachine.cpp:141] Init parameters done.
I0228 14:58:33.608119 20826 ThreadLocal.cpp:37] thread use undeterministic rand seed:20827
F0228 14:58:33.608639 20826 PythonUtil.h:215] Check failed: PySequence_Check(seq_) 
*** Check failure stack trace: ***
    @     0x7f1d0db8edaa  (unknown)
    @     0x7f1d0db8ece4  (unknown)
    @     0x7f1d0db8e6e6  (unknown)
    @     0x7f1d0db91687  (unknown)
    @           0x549546  paddle::py::SequenceHelper::SequenceHelper()
    @           0x549661  paddle::SequenceScanner::prepare()
    @           0x54f61c  paddle::PyDataProvider2::getNextBatchInternal()
    @           0x55467e  paddle::DoubleBuffer::asyncLoadBatch()
    @     0x7f1d0d70ba60  (unknown)
    @     0x7f1d0e9a1184  start_thread
    @     0x7f1d0ce7337d  (unknown)
    @              (nil)  (unknown)
/usr/bin/paddle: line 109: 20818 Aborted                 (core dumped) ${DEBUGGER} $MYDIR/../opt/paddle/bin/paddle_trainer ${@:2}
` 

Could you tell us how to provide data correctly?

**Comment by luotao1** [comment]
you can print and check the yield. It should has FORECASTING_NUM+1 input.
```
yield dense_input_1, dense_input_2, ..., dense_input_FORECASTING_NUM, integer_input
```

**Comment by 7633** [comment]
@luotao1 Thank you for explanation!
But what could this error means?
`F0228 16:24:54.667619 19048 Matrix.cpp:3167] Check failed: (size_t)lbl[i] < dim (4 vs. 4)`
My network architecture is quite similar:
```
link_encode = data_layer(name='data', size=TERM_NUM)
lstm = simple_lstm(input=link_encode, size=emb_size)
score = fc_layer(input=lstm, size=4, act=SoftmaxActivation())
if is_predict:
    maxid = maxid_layer(score)
    outputs([maxid, score])
else:
    # Multi-task training.
    label = data_layer(name='label', size=4)
    cls = classification_cost(input=score, label=label)
    outputs(cls)
```
So, part of _initHook_ in dataprovider:
```
settings.input_types = [
        dense_vector_sequence(TERM_NUM),
        integer_value(4)
    ]
```
And _process_ return this `yield [input_data], int(speeds[i])`

I didn't understand why and where it occurs, because dimension of output label layer is 4, dimension of  score layer the same.

**Comment by guoshengCS** [comment]
Close since no update. Please reopen it if necessary.
