### ISSUE TITLE
paddlecloud模型训练出错： CUDA driver version is insufficient for CUDA runtime version

### ISSUE THREAD

**Issue by pankiki** [PaddlePaddle/Paddle#14625]
CPU
paddlecloud将trainer_count改成10出错
具体错误：
Tue Nov 27 13:49:06 2018[1,10]<stdout>:F1127 13:49:06.743296 17418 hl_cuda_device.cc:565] Check failed: cudaSuccess == cudaStat (0 vs. 35) Cuda Error: CUDA driver version is insufficient for CUDA runtime version
Tue Nov 27 13:49:06 2018[1,10]<stdout>:*** Check failure stack trace: ***

**Comment by jacquesqiao** [comment]
目前初步结论是当用户选择cpu集群的时候，不应该安装带cuda支持的paddle版本。

**Comment by lucywsq** [comment]
您好，此issue在近三周内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题，我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持
