### ISSUE TITLE
Machine Translation Documentation - 08.machine_translation

### ISSUE THREAD

**Issue by n00blet** [PaddlePaddle/Paddle#14633]
Hello,
I was trying to run machine translation, and was looking at the documentation and the example to run a basic NMT model. And in your documentation, the link to download the subset of dataset is not available.
Link: http://paddlepaddle.bj.bcebos.com/demo/wmt_shrinked_data/wmt14.tgz.

And in the documentation, how do I create source and target dictionary for my files. Do I have to use a different library, and what will be the format of dictionary files.

Also, is there a way to preprocess  without having to merge my source and target files every time. 
For example, OpenNMT-PY has its own pre-process. It would be nice if I could run the sample machine translation using Paddle.

**Comment by n00blet** [comment]
I am currently using Google colab to test the Machine Translation and after pip install of **paddlepaddle-gpu** , I tried to run the following command **paddle train --help**  and I ended up with the following error. Is there a way around this problem ?.

_/usr/local/bin/paddle_trainer: error while loading shared libraries: libmklml_intel.so: cannot open shared object file: No such file or directory_

Thanks,
Rakshith

**Comment by dzhwinter** [comment]
设置 LD_LIBRARY_PATH=/usr/local/lib:$LD_LIBRARY_PATH

**Comment by jacquesqiao** [comment]
Which machine translation model are you using? Can you paste a link to the model repo?

**Comment by n00blet** [comment]
> Which machine translation model are you using? Can you paste a link to the model repo?

Hello, I am following the guidelines from one of your documentation.
https://github.com/PaddlePaddle/book/blob/develop/08.machine_translation/README.md
and
http://paddlepaddle.org/documentation/book/en/1.1/08.machine_translation/index.html#permalink-9-data-preprocessing.

I am trying to run the basic example that is written in the documentation using Google Colab as it has good GPU. 

Also the demo dataset offered by paddle is not available for download.

**Comment by jacquesqiao** [comment]
文档问题请 @shanyi15 跟进一下，训练时缺乏lib的问题请 @JiabinYang 跟进一下
