### ISSUE TITLE
fluid V1.1 报错paddle.fluid.core.EnforceNotMet: Enforce failed. Expected table_dims.size() == 2, but received table_dims.size():1 != 2:2.

### ISSUE THREAD

**Issue by shiyazhou121** [PaddlePaddle/Paddle#14650]
具体报错如下：
![image](https://user-images.githubusercontent.com/15082798/49149277-a2d51780-f344-11e8-8204-9e5365064ce7.png)
其中data为
![image](https://user-images.githubusercontent.com/15082798/49149338-c7c98a80-f344-11e8-8962-c6210805b081.png)
网络结构为
![image](https://user-images.githubusercontent.com/15082798/49149360-d6b03d00-f344-11e8-84f1-a2a1642271af.png)
![image](https://user-images.githubusercontent.com/15082798/49149368-dc0d8780-f344-11e8-97f6-4a3af494dc19.png)

**Comment by dzhwinter** [comment]
你的table写错了，嵌套的list中多包含了一层，看起来像没有parse到二维矩阵，而是当做一个tuple处理了。

**Comment by shiyazhou121** [comment]
@dzhwinter 我理解是batch是一个list，每条数据是一个tuple，tuple中有两个list，对应feeder里的word, target，这个应该怎么改
下面是dataReader函数
![image](https://user-images.githubusercontent.com/15082798/49194268-672a6400-f3bd-11e8-95f4-13867f8381d5.png)
