### ISSUE TITLE
关于data接口的shape参数的问题

### ISSUE THREAD

**Issue by yeyupiaoling** [PaddlePaddle/Paddle#14655]
# 环境：
 - paddlepaddle 1.1.0
 - Python 3.5
 - Ubuntu 16.04
 - CPU 4个

# 问题：
我的label值是一个长度为60的一维数组，我的data定义如下：
```
y = fluid.layers.data(name='y', shape=[1], dtype='float32')
```
或者
```
y = fluid.layers.data(name='y', shape=[60], dtype='float32')
```

**那么问题就来了，`shape`参数是至数据的维度还是长度？**

同样我定义data时
```
x = fluid.layers.data(name='x', shape=[121, 6], dtype='float32')
```
或者
```
x = fluid.layers.data(name='x', shape=[726], dtype='float32')
```

这两种都可以正常训练，但哪个才是标准的使用方式呢？

**Comment by Superjomn** [comment]
标准方式是，shape是数据的维度。 比如，你的label是一维数组，60长，应该就是 [60]，行优先

**Comment by yeyupiaoling** [comment]
@Superjomn 像下面定义`y`时，`shape=[121, 6]`和`shape=[726]`都可以，是不是底层已经把他们相乘了？

**Comment by NHZlX** [comment]
shape表示输入的维度信息 ，data后的第一个op可能不需要data的shape，因此不会有影响。有的 op像conv， 会依赖输入的shape来计算output的shape，因此需要准确输入shape的。

**Comment by yeyupiaoling** [comment]
好的，谢谢您的回答。
