### ISSUE TITLE
Ubuntu 下本地源码安装cmake 时报错

### ISSUE THREAD

**Issue by Mcliuyi** [PaddlePaddle/Paddle#14675]
控制台的报错信息
CMake Error at /usr/share/cmake-3.10/Modules/FindCUDA.cmake:682 (message):
  Specify CUDA_TOOLKIT_ROOT_DIR
Call Stack (most recent call first):
  cmake/configure.cmake:90 (FIND_PACKAGE)
  CMakeLists.txt:245 (include)

CMakeError.log文件的报错信息
make[1]: Entering directory '/home/python/Paddle/build/CMakeFiles/CMakeTmp'
139 Building CXX object CMakeFiles/cmTC_7ba69.dir/src.cxx.o
140 /usr/bin/c++    -std=c++11 -fPIC -fno-omit-frame-pointer -Werror -Wall -Wext    ra -Wnon-virtual-dtor -Wdelete-non-virtual-dtor -Wno-unused-parameter -Wno-u    nused-function -Wno-error=literal-suffix -Wno-error=sign-compare -Wno-error=    unused-local-typedefs -DCXX_COMPILER_SUPPORT_FLAG__Wno_error_parentheses_equ    ality   -Wno-error=parentheses-equality -o CMakeFiles/cmTC_7ba69.dir/src.cxx    .o -c /home/python/Paddle/build/CMakeFiles/CMakeTmp/src.cxx
141 cc1plus: error: -Werror=parentheses-equality: no option -Wparentheses-equali    ty
142 CMakeFiles/cmTC_7ba69.dir/build.make:65: recipe for target 'CMakeFiles/cmTC_    7ba69.dir/src.cxx.o' failed
143 make[1]: *** [CMakeFiles/cmTC_7ba69.dir/src.cxx.o] Error 1
144 make[1]: Leaving directory '/home/python/Paddle/build/CMakeFiles/CMakeTmp'
145 Makefile:126: recipe for target 'cmTC_7ba69/fast' failed
146 make: *** [cmTC_7ba69/fast] Error 2

**Comment by JiabinYang** [comment]
请问您是编译的哪一个分支的代码

**Comment by Mcliuyi** [comment]
默认分支，因为我切换分支时失败了

**Comment by JiabinYang** [comment]
您cmake的时候使用`-DWITH_GPU=OFF`试下看看能不能编过
