### ISSUE TITLE
fluid v1.1 crf_decoding输出查看方法

### ISSUE THREAD

**Issue by shiyazhou121** [PaddlePaddle/Paddle#14678]
想在训练时查看下crf_decode输出的序列，在使用exe.run时报错，所以想问下正确的方法
![image](https://user-images.githubusercontent.com/15082798/49266743-46800e00-f492-11e8-8501-b2de8bb15f2c.png)
![image](https://user-images.githubusercontent.com/15082798/49266747-497afe80-f492-11e8-87ef-3c92271b7f81.png)

**Comment by seiriosPlus** [comment]
1. 设置```return_numpy=False```
2. 参考 https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/fluid/tests/test_lod_tensor.py
3. 取Tensor， 可以用get_tensor的方法，取出tensor。
4. 然后用 np.array(取出的tensor)， 可以转换成numpy的array
