### ISSUE TITLE
运行book第一个实验中生成一个core文件，使用gdb调试出现问号，不知道哪报错

### ISSUE THREAD

**Issue by zhuziying** [PaddlePaddle/Paddle#14684]
镜像使用的这里地址的 docker.paddlepaddlehub.com/book:latest-gpu
显示core.x文件的内容有问号

**Comment by xuezhong** [comment]
可以贴下复现信息

**Comment by zhuziying** [comment]
root@aa0e7351db67:/book/01.fit_a_line# ls
README.cn.ipynb  README.cn.md  README.ipynb  README.md  core.497  fit_a_line.tar  image  index.cn.html  index.html  infer.py  train.py
root@aa0e7351db67:/book/01.fit_a_line# python train.py 
Illegal instruction (core dumped)
root@aa0e7351db67:/book/01.fit_a_line# gdb core core.497 
GNU gdb (Ubuntu 7.11.1-0ubuntu1~16.5) 7.11.1
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
core: No such file or directory.
[New LWP 497]
Core was generated by `python train.py'.
Program terminated with signal SIGILL, Illegal instruction.
#0  0x00007f6b91926c38 in ?? ()

**Comment by xuezhong** [comment]
可以先用pdb 调试下Python代码，看python代码能运行到哪一句。

从 "Illegal instruction" 来看还是环境安装的有些问题，请贴下安装paddle的命令

**Comment by zhuziying** [comment]
好的，我安装pdb试一下，安装paddle我就是用github上paddle/book下面官方的链接docker pull docker.paddlepaddlehub.com/book:latest-gpu，下载后的镜像是

docker.paddlepaddlehub.com/book         latest-gpu          7a82298ca2b3        8 months ago        3.91 GB
docker.paddlepaddlehub.com/book         latest-gpu          7a82298ca2b3        8 months ago        3.91 GB



在 2018-12-05 15:03:20，"xuezhong" <notifications@github.com> 写道：


可以先用pdb 调试下Python代码，看python代码能运行到哪一句。

从 "Illegal instruction" 来看还是环境安装的有些问题，请贴下安装paddle的命令

**Comment by zhuziying** [comment]
使用pdb调试 with_gpu是False，我的cuda是10.0，cunn也是10.0 是不是版本问题




在 2018-12-05 15:03:20，"xuezhong" <notifications@github.com> 写道：


可以先用pdb 调试下Python代码，看python代码能运行到哪一句。

从 "Illegal instruction" 来看还是环境安装的有些问题，请贴下安装paddle的命令

**Comment by luotao1** [comment]
@zhuziying `cat /proc/cpuinfo`看下机器是否有avx指令集。

@junjun315 @JiabinYang 应该属于avx的问题，`docker.paddlepaddlehub.com/book:latest-gpu` 很久没有更新了。

**Comment by zhuziying** [comment]
processor       : 0
vendor_id       : GenuineIntel
cpu family      : 6
model           : 23








model name      : Intel(R) Celeron(R) CPU        E3400  @ 2.60GHz
stepping        : 10
microcode       : 0xa0b
cpu MHz         : 1203.000
cache size      : 1024 KB
physical id     : 0
siblings        : 2
core id         : 0
cpu cores       : 2
apicid          : 0
initial apicid  : 0
fpu             : yes
fpu_exception   : yes
cpuid level     : 13
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx lm constant_tsc arch_perfmon pebs bts rep_good nopl aperfmperf pni dtes64 monitor ds_cpl vmx est tm2 ssse3 cx16 xtpr pdcm xsave lahf_lm tpr_shadow vnmi flexpriority dtherm
bogomips        : 5201.84
clflush size    : 64
cache_alignment : 64
address sizes   : 36 bits physical, 48 bits virtual
power management:
以上是cat /proc/cpuinfo的结果，flags是指令集吗？好像没有avx

**Comment by luotao1** [comment]
> flags是指令集吗？好像没有avx

对的，确实没有avx

**Comment by zhuziying** [comment]
我需要换有avx指令集的cpu是这个意思吗？

**Comment by junjun315** [comment]
我们预计12月10日那周内更新包含noavx版本的paddle包，并且更新book的镜像。更新完成后我也会在这个issue里再回复您，请期待，谢谢您的关注和使用～

**Comment by junjun315** [comment]
请先换用新的镜像吧: hub.baidubce.com/paddlepaddle/book. 这个镜像是CPU环境，包含noavx版本的paddlepaddle。如果是因为处理器不包含avx指令集而导致运行有问题的话，新的镜像应该不复现问题。
