### ISSUE TITLE
paddle v2 capi 是否存在内存泄露问题（valgrind报告存在大量possibly lost）？

### ISSUE THREAD

**Issue by fseasy** [PaddlePaddle/Paddle#14680]
- 版本、环境信息：
    1）PaddlePaddle版本：V2
    2）CPU：Intel(R) Xeon(R) CPU E5-2650 v4 @ 2.20GHz，OpenBlas
    3）GPU：NONE
    4）系统环境：CentOS4.3
-预测信息
    1）C++预测：v2 noavx
    2）CMake包含路径的完整命令: 无，预编译
    3）API信息：
    4）预测库来源：特殊环境 (内部预编译仓库)

- 问题描述：

目前使用v2的capi预测，线上环境内存持续增加。目前还没有定位到具体问题。
不过通过valgrind检测，发现大量paddle命名空间下的protobuf possibly lost.
一个片段如下：
![image](https://user-images.githubusercontent.com/5585818/49269102-31a97780-f49e-11e8-96aa-0b46a5537c66.png)

使用的protobuf是 protobuf_2-4-1-1100_PD_BL

麻烦问下paddle V2之前是否遇到过类似的问题，这个possibly lost是否真的是内存泄露呢？ 我看网上说，出现这个问题，似乎是少调用了protobuf::ShutdownProtobufLibrary() ？

上面只是一个疑问，因为内存是持续增长的，不知道这个会不会带来持续增长。

**Comment by Superjomn** [comment]
之前没有见过类似问题。 v2上线的服务比较多，应该不太可能出现这样的普遍的内存泄漏问题。
你们模型或者使用版本是有啥特殊的地方吗

**Comment by fseasy** [comment]
嗯，我跑数据看了一下哈； 的确不算泄露； 因为是hierarchical输入，也就是句子列表；但是长度截断却是直接按总长度截的，导致有的输入句子个数特别多，因此paddle forward内存大规模增加。
我想知道paddle的内存管理，就是类似vector那样的吧
