### ISSUE TITLE
paddle v2 多卡训练速度不如单卡快

### ISSUE THREAD

**Issue by zhaoshiyu** [PaddlePaddle/Paddle#14690]
PaddlePaddle 0.11.0(v2)，P40卡，训练时单卡比8卡快是什么原因？
8卡时大部分时间卡处于闲置状态。
GPU：P40
驱动：CUDA 8.0和cuDNN 7

**Comment by guru4elephant** [comment]
v2没有使用nccl2，多卡同步的效率并不高，推荐使用fluid版本@zhaoshiyu
