### ISSUE TITLE
提供的模型是否可以提供多个接口的模型？

### ISSUE THREAD

**Issue by yeyupiaoling** [PaddlePaddle/Paddle#14705]
保存模型的方式有很多种，文档：http://www.paddlepaddle.org/documentation/api/zh/1.0/io.html
但是官方一般是提供：https://github.com/PaddlePaddle/models/blob/a8dc7ed3d95cf83d7ae0f7988628e6910f018a49/fluid/PaddleCV/image_classification/train.py#L257

我的建议是4个接口保存模型的方式都提供，比如paddle-mobile使用但是`save_inference_model`接口保存的模型，但官网提供的模型也不是这个接口的，以后提供训练好的模型是否可以提供全部的模型。
![image](https://user-images.githubusercontent.com/26297768/49350212-167e7800-f6e9-11e8-813c-8af173c45900.png)

**Comment by xuezhong** [comment]
谢谢您的建议，的确现在提供的模型中主要是checkpoint的方式保存。但是save_inference_model也有大量的模型用到，比如https://github.com/PaddlePaddle/models/blob/25fd8885fe8a1bf848bd6e7d44128c40d882f03d/fluid/PaddleRec/ctr/train.py#L138。你可以直接在repo中搜索就可以获得。

以后提供训练好的模型是否可以提供全部的模型
这个一般依据需求确定，由于实际需求变化比较大，因此具体模型具体分析。如果实际运用中遇到问题，也可以通过issue获得帮助。谢谢~

**Comment by yeyupiaoling** [comment]
>如果实际运用中遇到问题，也可以通过issue获得帮助。谢谢~

我的确是在实际的运用上使用到，我在使用paddle-mobile做目标检测时，需要用到`save_inference_model`保存的模型。而且我看看tensorflow提供模型，也是提供全部的模型并打包好的。
