### ISSUE TITLE
请问fluid中lstm出序列向量的接口是什么

### ISSUE THREAD

**Issue by Kayven** [PaddlePaddle/Paddle#14708]
对于输入【batch_size, seq_len, emb_len】
只能先fc成二维的【batch_size, hid_dim】，然后调用lstm？
emb=fluid.layers.fc(input=emb, size=hid_dim * 4)
fluid.layers.dynamic_lstm(input=emb, size=hid_dim*4, is_reverse=False)

希望lstm输出【batch_size, seq_len, hid_dim】，fluid该怎么实现呢？
tensorflow里就是这样的，tf.nn.bidirectional_dynamic_rnn
paddle里原来v2有个networks.bidirectional_lstm(..., return_seq=True)也可以实现，fluid不兼容

**Comment by xuezhong** [comment]
fluid中有两类数据 1是 lodtensor 2是tensor，两类数据的lstm调用方法不一样的。这是最重要的。

其中lodtensor调用dynamic_lstm 或者DynamicRNN+lstm_step, 好处是输入不用padding和mask。[例子](https://github.com/PaddlePaddle/models/blob/develop/fluid/PaddleNLP/language_model/gru/train.py#L50) 

其中tensor调用的是StaticRNN，[例子](https://github.com/PaddlePaddle/models/blob/develop/fluid/PaddleNLP/language_model/lstm/lm_model.py#L261)，好处是和tensorflow差不多的逻辑

tensorflow的实现对应fluid tensor的实现

具体选用哪一种，根据实际需要

**Comment by Kayven** [comment]
多谢@xuezhong  对于dynamic_lstm有点疑问
输入lodtensor
x.lod[[2, 1, 3]]   3条样本3个句子，每个词数不同
x.data [a1,a2,b1,b1,b2,b3]  每个元素是一个词向量

由于需要先fc再dynamic_lstm
emb=fluid.layers.fc(input=emb, size=hid_dim * 4)
此后每条样本就是一个向量了？ 序列丢失了？（成了3个样本，每个是hid_dim * 4的向量）
fluid.layers.dynamic_lstm(input=emb, size=hid_dim*4, is_reverse=False)

**Comment by xuezhong** [comment]
lod描述了不同的sequence的长度信息，因此从shape看，就没有batch_size这个维度。

在dynamic_lstm内部，会对lod描述的整个长序列，切分成各个sequence 长度，然后做lstm运算。不存在 "序列丢失"。你可以通过Print op将所有的lodtensor打印出来，这样一目了然
