### ISSUE TITLE
Fluid版本的image工具在哪里？

### ISSUE THREAD

**Issue by yeyupiaoling** [PaddlePaddle/Paddle#14724]
## 环境：
 - PaddlePaddle 1.1.0
 - Python 3.5
 - Ubuntu 16.04

## 问题：
在PaddlePaddle 1.1.0版本的默认安装，是没有V2版本的库的，我要使用：https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/v2/image.py 这个工具，好像在fluid下找不到，还请老师指点一下，这些工具迁移到哪里了？

**Comment by sneaxiy** [comment]
你好，`v2/image.py`的工具在`paddle/dataset/image.py`里面。
