### ISSUE TITLE
新版本paddle与v2的兼容问题

### ISSUE THREAD

**Issue by Angus07** [PaddlePaddle/Paddle#14729]
原来的老版本的paddle v2预测代码在fluid最新版本的框架更新后无法正常运行，现场是在预测阶段卡住不动，一直在运行中，不报任何错误。

**Comment by Superjomn** [comment]
是静态链接还是动态链接。

另外，可能是mkl版本不一致，可以切换成openblas试试。

**Comment by Angus07** [comment]
python 的预测，不是c++的

**Comment by Angus07** [comment]
1.self.inferer = paddle.inference.Inference(output_layer=prob_layer, parameters=parameters)

2.probs = self.inferer.infer(input=test_batch, field=["value"])
在2这里卡住了

**Comment by luotao1** [comment]
和用户沟通后，设置`export MKL_NUM_THREADS=1`和`export OMP_NUM_THREADS=1`，就能跑通了。
