### ISSUE TITLE
在MPI集群上训练，报错信息很短不知道是哪里出问题了（Fluid版本）

### ISSUE THREAD

**Issue by CruiseSun** [PaddlePaddle/Paddle#14739]
Tue Dec  4 23:03:36 2018[1,8]<stdout>:PassID 0, BatchID 0001, Test Loss 0.59, Auc 0.58, Bat-Auc 0.64
Tue Dec  4 23:03:36 2018[1,8]<stdout>:Exception in thread Thread-35 (most likely raised during interpreter shutdown):
Tue Dec  4 23:03:38 2018[1,8]<stderr>:+ trainer_ret=0
Tue Dec  4 23:03:38 2018[1,8]<stderr>:+ popd
Tue Dec  4 23:03:38 2018[1,8]<stdout>:/home/disk1/normandy/maybach/app-user-20181204210532-6338/workspace
Tue Dec  4 23:03:38 2018[1,8]<stderr>:+ exit 0

**Comment by typhoonzero** [comment]
沟通后怀疑是train_loop中判断auc > 0.1就return了，可能是这个原因，正在验证

**Comment by CruiseSun** [comment]
验证成功~
