### ISSUE TITLE
paddlepaddle_gpu-1.1.0.post97-cp27-cp27mu-manylinux1_x86_64.whl 是对应cuda9.0 cudnn7.0吗

### ISSUE THREAD

**Issue by 994374821** [PaddlePaddle/Paddle#14759]
建立issue时，为快速解决问题，请您根据使用情况给出如下信息：
- 标题：请包含关键词“安装错误”/“编译错误”，例如“Mac编译错误”
- 版本、环境信息：
    1）PaddlePaddle版本：paddlepaddle_gpu-1.1.0.post97-cp27-cp27mu-manylinux1_x86_64.whl
    2）CPU：请提供CPU型号，MKL/OpenBlas/MKLDNN/等数学库的使用情况
    3）GPU：cuda9.0 CUDNN7.0
    4）系统环境：ubuntu16.04 python2.7
- 安装方式信息：
1）pip安装/docker安装 
pip install paddlepaddle_gpu-1.1.0.post97-cp27-cp27mu-manylinux1_x86_64.whl

- 问题描述：请详细描述您的问题，同步贴出报错信息、日志/代码关键片段
import paddle.fluid
报错 all CUDA-capable devices are busy or unavailable at [/paddle/paddle/fluid/platform/device_context.cc:251]

**Comment by NHZlX** [comment]
对的。

**Comment by NHZlX** [comment]
sorry，由于疏忽，没有看清您的问题描述，请问问题解决了么
