### ISSUE TITLE
如何实现z(0) i;j = [xiT ; yjT ]T？

### ISSUE THREAD

**Issue by sonofaeolus** [PaddlePaddle/Paddle#14766]
为使您的问题得到快速解决，在建立Issues前，请您先通过如下方式搜索是否有相似问题:【搜索issue关键字】【使用labels筛选】【官方文档】

如果您没有查询到相似问题，为快速解决您的提问，建立issue时请提供如下细节信息：
- 标题：简洁、精准概括您的问题
- 版本、环境信息：
    1）PaddlePaddle版本：请提供您的PaddlePaddle版本号，例如1.1或CommitID
    2）CPU/GPU：如果您使用GPU训练，请提供GPU驱动版本、CUDA和cuDNN版本号
    3）系统环境：请您描述系统类型、版本，例如Mac OS 10.14
    4）Python版本号
    5）显存信息
- 复现信息：如为报错，请给出复现环境、复现步骤
- 问题描述：请详细描述您的问题，同步贴出报错信息、日志/代码关键片段

Thank you for contributing to PaddlePaddle.
Before submitting the issue, you could search issue in the github in case that there was a similar issue submitted or resolved before.
If there is no solution,please provide us with the following details :
**System information**
-PaddlePaddle version （eg.1.1）or CommitID
-CPU: including CPUMKL/OpenBlas/MKLDNN version
-GPU: including CUDA/cuDNN version
-OS Platform and Distribution(eg.Mac OS 10.14)
-Python version 
**To Reproduce**
Steps to reproduce the behavior
**Describe your current behavior**
**Code to reproduce the issue**
**Other info / logs**

**Comment by sonofaeolus** [comment]
>>> a = [[1,2,3],[4,5,6]]  
>>> b = [[7,8,9],[10,11,12]]
>>> print c
[[1, 2, 3, 7, 8, 9], [1, 2, 3, 10, 11, 12], [4, 5, 6, 7, 8, 9], [4, 5, 6, 10, 11, 12]]

**Comment by sonofaeolus** [comment]
> 
> 
> > > > a = [[1,2,3],[4,5,6]]
> > > > b = [[7,8,9],[10,11,12]]
> > > > print c
> > > > [[1, 2, 3, 7, 8, 9], [1, 2, 3, 10, 11, 12], [4, 5, 6, 7, 8, 9], [4, 5, 6, 10, 11, 12]]
x y 是 ab，z是c

**Comment by NHZlX** [comment]
这个op目前不支持。

**Comment by sonofaeolus** [comment]
使用while op能不能实现这个操作 两个while op嵌套

**Comment by NHZlX** [comment]
这个应该是矩阵的一种操作，你的应用场景是什么，或者说paper，这边可以衡量一下是否可以对其进行支持。

**Comment by sonofaeolus** [comment]
我这边先用其他方式试下 不行再说 谢谢了
