### ISSUE TITLE
nccl训练是否支持只使用机器上的部分GPU卡

### ISSUE THREAD

**Issue by dashulu** [PaddlePaddle/Paddle#14769]
nccl进行分布式训练时，如果每个节点有8张卡，能否只使用其中的4张卡进行训练？需要什么特殊配置吗？

**Comment by typhoonzero** [comment]
单机情况，指定`export CUDA_VISIBLE_DEVICES=0,1,2,3`用其中4个卡就行。多机情况不需要特殊配置
