### ISSUE TITLE
tensorflow 模型转换

### ISSUE THREAD

**Issue by HUSTLX** [PaddlePaddle/Paddle#14779]
原来的tf代码是这样的:
![image](https://user-images.githubusercontent.com/12711390/49585758-4011fa80-f99a-11e8-9b91-2507532572f7.png)
usr和job分别是Batch\*100,和Batch\*1000的tensor，通过embedding_lookup成Batch\*100\*embed_dim,和Batch\*1000\*embed_dim维度，但是我改成下面的paddle fluid代码就报错

![image](https://user-images.githubusercontent.com/12711390/49586105-31781300-f99b-11e8-8bcb-44d6ede3c46f.png)

![image](https://user-images.githubusercontent.com/12711390/49586147-48b70080-f99b-11e8-9f53-a243302393ec.png)

**Comment by NHZlX** [comment]
emb的输入应该是N*D 的数据，其中N是batchsize， D的大小为1

**Comment by HUSTLX** [comment]
> emb的输入应该是N*D 的数据，其中N是batchsize， D的大小为1

但是tf里面这样输入是可以的，我发现我改成这样就可以了

![image](https://user-images.githubusercontent.com/12711390/49590791-b36e3900-f9a7-11e8-926d-298cb0a4e841.png)

**Comment by NHZlX** [comment]
保证最后一个维度是1就可以。根据你的问题来看，你可以让usr的输入是` [-1, 100, 1]`
job的shape为 `[-1, 1000, 1]`
