### ISSUE TITLE
Fluid在MPI上训练几个batch过后总是报这个GetRPC error，稳定复现问题

### ISSUE THREAD

**Issue by CruiseSun** [PaddlePaddle/Paddle#14776]
E1206 18:26:28.056375 21482 grpc_client.cc:342] GetRPC name:[category_id_crss_diff_time_table], ep:[10.75.76.39:8000], status:[-1] meets grpc error, error_code:4 error_message:Deadline Exceeded error_details:
E1206 18:26:28.056991 21482 grpc_client.cc:342] GetRPC name:[app_id_table], ep:[10.75.76.42:8000], status:[-1] meets grpc error, error_code:4 error_message:Deadline Exceeded error_details:
E1206 18:26:28.058243 21482 grpc_client.cc:342] GetRPC name:[fc_7.b_0], ep:[10.75.76.44:8000], status:[-1] meets grpc error, error_code:4 error_message:Deadline Exceeded error_details:
E1206 18:26:28.058390 21482 grpc_client.cc:342] GetRPC name:[fc_11.w_0.block5], ep:[10.75.76.36:8000], status:[-1] meets grpc error, error_code:4 error_message:Deadline Exceeded error_details:
E1206 18:26:28.058503 21482 grpc_client.cc:342] GetRPC name:[category_id_crss_source_name_table.block0], ep:[10.75.76.48:8000], status:[-1] meets grpc error, error_code:4 error_message:Deadline Exceeded error_details:
E1206 18:26:28.058542 21482 grpc_client.cc:342] GetRPC name:[category_id_crss_title_segs_table.block9], ep:[10.75.76.36:8000], status:[-1] meets grpc error, error_code:4 error_message:Deadline Exceeded error_details:
E1206 18:26:28.058573 21482 grpc_client.cc:342] GetRPC name:[cluster_id_table.block7], ep:[10.75.76.36:8000], status:[-1] meets grpc error, error_code:4 error_message:Deadline Exceeded error_details:
E1206 18:26:28.058634 21482 grpc_client.cc:342] GetRPC name:[category_id_table], ep:[10.75.76.48:8000], status:[-1] meets grpc error, error_code:4 error_message:Deadline Exceeded error_details:
E1206 18:26:28.058670 21482 grpc_client.cc:342] GetRPC name:[cluster_id_table.block8], ep:[10.75.76.48:8000], status:[-1] meets grpc error, error_code:4 error_message:Deadline Exceeded error_details:
E1206 18:26:28.058702 21482 grpc_client.cc:342] GetRPC name:[category_id_crss_title_segs_table.block0], ep:[10.75.76.48:8000], status:[-1] meets grpc error, error_code:4 error_message:Deadline Exceeded error_details:
E1206 18:26:28.058733 21482 grpc_client.cc:342] GetRPC name:[category_id_crss_tags_table.block9], ep:[10.75.76.36:8000], status:[-1] meets grpc error, error_code:4 error_message:Deadline Exceeded error_details:
E1206 18:26:28.058789 21482 grpc_client.cc:342] GetRPC name:[category_id_crss_tags_table.block0], ep:[10.75.76.48:8000], status:[-1] meets grpc error, error_code:4 error_message:Deadline Exceeded error_details:
E1206 18:26:28.058825 21482 grpc_client.cc:342] GetRPC name:[category_id_crss_quality_level_table], ep:[10.75.76.36:8000], status:[-1] meets grpc error, error_code:4 error_message:Deadline Exceeded error_details:
E1206 18:26:28.058858 21482 grpc_client.cc:342] GetRPC name:[category_id_crss_source_name_table.block9], ep:[10.75.76.36:8000], status:[-1] meets grpc error, error_code:4 error_message:Deadline Exceeded error_details:
E1206 18:26:28.058902 21482 grpc_client.cc:342] GetRPC name:[category_id_crss_source_name_table.block1], ep:[10.75.74.37:8000], status:[-1] meets grpc error, error_code:4 error_message:Deadline Exceeded error_details:
E1206 18:26:28.058936 21482 grpc_client.cc:342] GetRPC name:[city_table], ep:[10.75.74.37:8000], stat

**Comment by CruiseSun** [comment]
任务地址：http://10.75.76.42:8900/fileview.html?path=/home/disk1/normandy/maybach/app-user-20181206175918-1204/

**Comment by CruiseSun** [comment]
发现该问题经常发生在两个data的shuffle buf size之间。

**Comment by typhoonzero** [comment]
可以把deadline 设置长一点，在paddlecloud提交配置中增加： `FLAGS_rpc_deadline=6000000`，另外也需要考虑优化shuffle的性能。

**Comment by CruiseSun** [comment]
好的。刚增加了deadline新提交个任务试一下。关于优化shuffle的性能请问该怎么做呢？我现在用的是paddle.v2.reader.shuffle()

**Comment by typhoonzero** [comment]
那shuffle应该还好，可能是fill buf的时间比较长，优化reader性能会减小fill buf的时间。但先看加了`FLAGS_rpc_deadline`是否有效果

**Comment by CruiseSun** [comment]
好的，效果验证中

**Comment by CruiseSun** [comment]
增加了FLAGS_rpc_deadline，目前看比之前好些，可以稳定运行，当前batch size设置为16。batch size为256的任务4个小时过去了，目前还没有trainer.log输出，所以还看不到效果。

**Comment by CruiseSun** [comment]
batch size为500的一个任务，再次出现同样的问题挂掉了，已经训练5个多小时了。任务地址：http://10.75.66.45:8900/fileview.html?path=/home/disk1/normandy/maybach/app-user-20181207101732-1988/

**Comment by typhoonzero** [comment]
这个看起来没有日志输出。batch_size变大和小batch理论上是一样的，所以可能是程序在batch size变大之后是否存在无限等待数据之类的情况，可以在reader等多处地方增加日志debug，等任务fail时间太长了，debug周期太慢。

**Comment by CruiseSun** [comment]
这个问题解决了，原来是我的reader逻辑问题，导致延迟太高。谢谢！

**Comment by typhoonzero** [comment]
好的感谢反馈。先关闭了～
