### ISSUE TITLE
Cannot build Debug build with WITH_GPU=ON due to file truncation

### ISSUE THREAD

**Issue by Sand3r-** [PaddlePaddle/Paddle#14775]
**System information**
-PaddlePaddle version  29d9fb53fcb2ca3d64ac7209d80bb40b974f3a9a
-CPU: including MKLDNN version 0.17
-GPU: including CUDA 8.0/CUDNN 7 version
-OS Platform Ubuntu 16.04
-Python version 2.7.12
- Install method: build from source(without docker)

**To Reproduce**
Run cmake:
```
cmake -DCMAKE_BUILD_TYPE=Debug -DWITH_GPU=ON -DWITH_MKLDNN=ON -DWITH_TESTING=ON -DWITH_PROFILER=ON -DWITH_STYLE_CHECK=OFF -DWITH_INFERENCE=ON -DWITH_INFERENCE_API_TEST=ON .. 
```
and build with `make -j`
**Describe your current behavior**
When GPU build is ran with Debug build type, a linking error occurs:
```
/usr/bin/ar: /home/mgallus/src/Sander/Paddle/build_gpu_deb/paddle/fluid/inference/libpaddle_fluid.a: File truncated
paddle/fluid/inference/CMakeFiles/paddle_fluid.dir/build.make:4981: recipe for target 'paddle/fluid/inference/libpaddle_fluid.a' failed
make[2]: *** [paddle/fluid/inference/libpaddle_fluid.a] Error 1
make[2]: *** Deleting file 'paddle/fluid/inference/libpaddle_fluid.a'
CMakeFiles/Makefile2:58681: recipe for target 'paddle/fluid/inference/CMakeFiles/paddle_fluid.dir/all' failed
make[1]: *** [paddle/fluid/inference/CMakeFiles/paddle_fluid.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
/usr/bin/ar: /home/mgallus/src/Sander/Paddle/build_gpu_deb/paddle/fluid/inference/libpaddle_fluid_origin.a: File truncated
paddle/fluid/inference/CMakeFiles/paddle_fluid_origin.dir/build.make:4909: recipe for target 'paddle/fluid/inference/libpaddle_fluid_origin.a' failed
make[2]: *** [paddle/fluid/inference/libpaddle_fluid_origin.a] Error 1
make[2]: *** Deleting file 'paddle/fluid/inference/libpaddle_fluid_origin.a'
CMakeFiles/Makefile2:59135: recipe for target 'paddle/fluid/inference/CMakeFiles/paddle_fluid_origin.dir/all' failed
make[1]: *** [paddle/fluid/inference/CMakeFiles/paddle_fluid_origin.dir/all] Error 2

```

**Comment by luotao1** [comment]
There need some times to fix this compile bug.
And if you only want to fix the `test_concat_mkldnn_op` (which fails the TC build), you can remove following lines, which will not compile inference code:
https://github.com/PaddlePaddle/Paddle/blob/c83d5b7a16563df85cfb61adbe9d18592b3b5d52/paddle/fluid/CMakeLists.txt#L11

**Comment by Sand3r-** [comment]
@luotao1 Thank you for the tip, I'll definitely try that 👍

**Comment by luotao1** [comment]
solved by #15109

**Comment by kbinias** [comment]
System information:
- PaddlePaddle version c49e604
- CPU: SKX 8180, MKLDNN version 0.18
- GPU: including CUDA 8.0, cuDNN v7
- OS Platform Ubuntu 16.04
- Python version 2.7.12

Reproduce:
- `cmake .. -DWITH_GPU=ON -DWITH_PROFILER=ON -DWITH_STYLE_CHECK=OFF -DWITH_MKLDNN=ON -DWITH_TESTING=ON`
- `make -j`

Result

[ 74%] Linking CXX static library libpaddle_fluid_origin.a
/usr/bin/ar: /home/kbinias/dev/paddle/build/paddle/fluid/inference/libpaddle_fluid_origin.a: File truncated
paddle/fluid/inference/CMakeFiles/paddle_fluid_origin.dir/build.make:5701: recipe for target 'paddle/fluid/inference/libpaddle_fluid_origin.a' failed
make[2]: *** [paddle/fluid/inference/libpaddle_fluid_origin.a] Error 1
make[2]: *** Deleting file 'paddle/fluid/inference/libpaddle_fluid_origin.a'
CMakeFiles/Makefile2:64213: recipe for target 'paddle/fluid/inference/CMakeFiles/paddle_fluid_origin.dir/all' failed
make[1]: *** [paddle/fluid/inference/CMakeFiles/paddle_fluid_origin.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....

**Comment by luotao1** [comment]
@kbinias Please use the latest image `paddlepaddle/paddle:latest-dev`, or you can solve it by #15109.

**Comment by lidanqing-vv** [comment]
Building with the same command still reports the same error: file truncation. 
Removing the inference and training doesn't work. 
PaddlePaddle commit: [81b4fad8b94d85a473875ae0efe634fe46697314](https://github.com/PaddlePaddle/Paddle/commit/81b4fad8b94d85a473875ae0efe634fe46697314)

![image](https://user-images.githubusercontent.com/47151829/54450358-7ce74d80-4750-11e9-89ef-f310aa939abb.png)

Related to [#15615](https://github.com/PaddlePaddle/Paddle/issues/15615), we can not reproduce the same results as yours. Thanks

**Comment by luotao1** [comment]
@lidanqing-intel please see https://github.com/PaddlePaddle/Paddle/issues/14775#issuecomment-473301707

**Comment by lidanqing-vv** [comment]
If this would be searched again, consider update binutils to 2.28.0 or higher version.
To check: `ar --version`
