### ISSUE TITLE
split op出错in_axis_dim % num == 0 failed

### ISSUE THREAD

**Issue by nizihan** [PaddlePaddle/Paddle#14787]
ids_r 的信息如下：
shape: [160,]
dtype: f
希望将ids_r 分成32个子tensor：
slice_lbl = fluid.layers.split(ids_r, num_or_sections=32, dim=0)
报错：
paddle.fluid.core.EnforceNotMet: enforce in_axis_dim % num == 0 failed, 31 != 0
tensor split does not result in an equal division at [/paddle/paddle/fluid/operators/split_op.cc:44]

**Comment by JiabinYang** [comment]
请问下ids_r是从哪儿来的呢，有完整的代码可以贴一下么

**Comment by nizihan** [comment]
代码如下：
tmp_clas_fc, tmp_bbox_fc, tmp_heatmap_out = Net(num_classes, image, image_shape)
boxes, ids = fluid.layers.split(tmp_bbox_fc, num_or_sections=[4, 1], dim=2)# 32 5 5 ---> 32 5 4   32 5 1
ids_r = fluid.layers.reshape(x=ids, shape=[-1])# 32 5 1 ---> 160
slice_lbl = fluid.layers.split(ids_r, num_or_sections=32, dim=0)

**Comment by JiabinYang** [comment]
能麻烦打印一下ids的dims么

**Comment by JiabinYang** [comment]
<img width="754" alt="2018-12-07 4 47 17" src="https://user-images.githubusercontent.com/22361972/49637265-d9dfb300-fa3f-11e8-9085-f866397bdefc.png">
您在使用`layer.data`的时候把`append_batch_size`这个参数设置为`False`然后在您代码中`-1`替代`batch_size`的地方吧32的`batch_size`填入

**Comment by JiabinYang** [comment]
https://github.com/PaddlePaddle/Paddle/blob/c83d5b7a16563df85cfb61adbe9d18592b3b5d52/python/paddle/fluid/data_feeder.py
您可以修改您paddle文件中的这个文件里，注释掉L159-L161行即可解决reader检查batch size维度的问题

**Comment by nizihan** [comment]
好的，非常感谢
