### ISSUE TITLE
关于加载训练模型进行预测的接口问题

### ISSUE THREAD

**Issue by yeyupiaoling** [PaddlePaddle/Paddle#14788]
# 环境：
 - PaddlePaddle 1.1.0
 - Python 3.5
 - Ubuntu 16.04

# 问题：
 - 如果使用load_inference_model接口报错模型，那么在预测的时候使用save_inference_model加载模型，进行预测流程非常简单，而且不用加载网络的定义。这个没问题
 - 但是，我在图像分类的[预测代码上](https://github.com/PaddlePaddle/models/blob/5c9deb5e2474a64890a1c2282bb9b29c3bfdef14/fluid/PaddleCV/image_classification/infer.py#L67)看到加载模型是使用load_vars，问题是在[训练的时候](https://github.com/PaddlePaddle/models/blob/5c9deb5e2474a64890a1c2282bb9b29c3bfdef14/fluid/PaddleCV/image_classification/train.py#L352)使用的是这个save_persistables接口来保存模型，这就很奇怪了。加载模型和保存模型不应该是一一对应的吗？
 - 有些例子又是对应的，比如机器翻译这个例子，[训练](https://github.com/PaddlePaddle/models/blob/5c9deb5e2474a64890a1c2282bb9b29c3bfdef14/fluid/PaddleNLP/neural_machine_translation/rnn_search/train.py#L163-L166)使用的是save_persistables，[预测](https://github.com/PaddlePaddle/models/blob/5c9deb5e2474a64890a1c2282bb9b29c3bfdef14/fluid/PaddleNLP/neural_machine_translation/rnn_search/infer.py#L73-L76)的是使用load_persistables
 - 还有save_params和load_params是否也可以跟上面一样，还有save_vars和load_vars。
 - 它们到底有什么区别

**Comment by JiabinYang** [comment]
1. 使用save_persistables保存的模型可以使用load_persistable来load模型.       
2.   save/load param 是专门保存python中parameter的
3. save vars是保存所有的var，或者您指定的var，不论是不是persistable

具体的区别您可以参考api[文档](http://paddlepaddle.org/documentation/docs/zh/1.1/api/io.html)

**Comment by yeyupiaoling** [comment]
>使用save_persistables保存的模型可以使用load_persistable来load模型.

我想表达的是，通过load_vars接口可以加载 persistables 和 params 模型作为预测吗？

>save/load param 是专门保存python中parameter的

这句话我不是很懂，难道还有其他的参数？

ps：就是因为文档说的不清楚，我才来问的。

**Comment by JiabinYang** [comment]
1. 可以的    
2. 我们在python中有一个parameter类，save/load param是用来存取它的，一般来说，因为vars包含persistable包含parameter，因此load和save的使用也可以借鉴这个关系来使用
3. 相关的文档我们会尽快完善，感谢您的反馈

**Comment by yeyupiaoling** [comment]
@JiabinYang vars、infer_model、params、persistable这四个模型都可以作为预测模型，那还有一些问，
 1. vars包含了params和persistable，infer_model是为了更方便预测。那么为什么要区分params和persistable呢？

**Comment by JiabinYang** [comment]
因为有一些`vars`是用户可以自行设置为`persistable`的但这些`vars`可以不是`param`,例如在使用`memrory optimize`的时候为了防止内存被复用，需要把`loss`设置为`persistable`，但是它不是`param`

**Comment by yeyupiaoling** [comment]
哦哦，明白。谢谢了。
