### ISSUE TITLE
from paddle.utils.merge_model import merge_v2_model 提示ImportError: No module named merge_model 但是自行安装不成功

### ISSUE THREAD

**Issue by duanyuzhuo** [PaddlePaddle/Paddle#14785]
如题
from paddle.utils.merge_model import merge_v2_model 
提示ImportError: No module named merge_model

自行安装merge_model模块，提示以下错误信息
Collecting merge_model
  Could not find a version that satisfies the requirement merge_model (from versions: )
No matching distribution found for merge_model

本人使用python 2.7.10 GCC 4.8.2
paddle版本为v2

小白求解答，非常感谢！

**Comment by JiabinYang** [comment]
merge_model的code在[这里](https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/utils/merge_model.py) ， 您可以直接使用

**Comment by duanyuzhuo** [comment]
好的，已解决，非常感谢！
