### ISSUE TITLE
在训练前加载预训练模型的接口问题

### ISSUE THREAD

**Issue by yeyupiaoling** [PaddlePaddle/Paddle#14790]
# 环境：
 - PaddlePaddle 1.1.0
 - Python 3.5
 - Ubuntu 16.04

# 问题：
 - 在图像分类的模型中，加载与训练模型居然同时使用两个，一个是[load_persistables](https://github.com/PaddlePaddle/models/blob/5c9deb5e2474a64890a1c2282bb9b29c3bfdef14/fluid/PaddleCV/image_classification/train.py#L228-L229)，另一个是[load_vars](https://github.com/PaddlePaddle/models/blob/5c9deb5e2474a64890a1c2282bb9b29c3bfdef14/fluid/PaddleCV/image_classification/train.py#L236-L237)，这是什么情况，在加载预训模型到底用那个接口？
 - 是否也可以使用load_params加载与训练模型？

**Comment by shippingwang** [comment]
> # 环境：
> * PaddlePaddle 1.1.0
> * Python 3.5
> * Ubuntu 16.04
> 
> # 问题：
> * 在图像分类的模型中，加载与训练模型居然同时使用两个，一个是[load_persistables](https://github.com/PaddlePaddle/models/blob/5c9deb5e2474a64890a1c2282bb9b29c3bfdef14/fluid/PaddleCV/image_classification/train.py#L228-L229)，另一个是[load_vars](https://github.com/PaddlePaddle/models/blob/5c9deb5e2474a64890a1c2282bb9b29c3bfdef14/fluid/PaddleCV/image_classification/train.py#L236-L237)，这是什么情况，在加载预训模型到底用那个接口？
> * 是否也可以使用load_params加载与训练模型？

1. vars可以看作是包含params和persistables的。
2. checkpoint 用persistables，比如训练一半程序挂了，要继续训练。
3. 用params加载预训练模型可以啊
具体您可以再参考一下[load](http://paddlepaddle.org/documentation/api/zh/1.1/io.html#load-params)

**Comment by yeyupiaoling** [comment]
@shippingwang 
 - 也就是说vars、params、persistables这个三个都可以保存模型，之后可以这个这些模型作为预训练模型加载进去？
 - 那么加载预训练模型的时候，调用的接口要对应之前保存模型的接口一样吗？还是说load_vars可以加载所有的模型作为预训练？

**Comment by shippingwang** [comment]
> @shippingwang
> 
> * 也就是说vars、params、persistables这个三个都可以保存模型，之后可以这个这些模型作为预训练模型加载进去？
> * 那么加载预训练模型的时候，调用的接口要对应之前保存模型的接口一样吗？还是说load_vars可以加载所有的模型作为预训练？

用```save_persistsbles```保存持久化参数 用```load_vars```加载模型。
不能 params和persistables相互对应的 保存和加载。

**Comment by yeyupiaoling** [comment]
@shippingwang 我不太明白您的表述。我的意思是，是不是可以在训练之前使用load_vars加载vars、params、persistables这三个模型作为预训练？

**Comment by shippingwang** [comment]
> @shippingwang 我不太明白您的表述。我的意思是，是不是可以在训练之前使用load_vars加载vars、params、persistables这三个模型作为预训练？

可以，当然可以。具体你可以参照[模型保存与加载](http://paddlepaddle.org/documentation/docs/zh/1.2/api_cn/api_guides/low_level/model_save_reader.html#api-guide-model-save-reader)

**Comment by yeyupiaoling** [comment]
好的，谢谢您的回答。
