### ISSUE TITLE
The WarpCTCKernel does not accept INT64 label input

### ISSUE THREAD

**Issue by wojtuss** [PaddlePaddle/Paddle#14794]
When running CRNN-CTC inference using C-API and `AnalysisPredictor`, I have to declare the network inputs (`pixel` and `label`) as `PaddleTensor`s of type either `PaddleDType::FLOAT` or `PaddleDType::INT64`. So I declare the labels as `INT64`. However, when the execution comes to the `warpctc` operator
https://github.com/PaddlePaddle/Paddle/blob/add98c9e7de55c72e9cf79300ba65e50934e6178/paddle/fluid/operators/warpctc_op.h#L202
and then to the check
https://github.com/PaddlePaddle/Paddle/blob/add98c9e7de55c72e9cf79300ba65e50934e6178/paddle/fluid/framework/tensor_impl.h#L41
it fails, as it expects `int` and not `long int` (`INT64`).

Can I do anything to avoid this problem or it requires a fix to the `warpctc` operator?

**Comment by luotao1** [comment]
Why inference need `warpctc_op`?

**Comment by wojtuss** [comment]
Actually, it is for evaluation and accuracy check. This is how python scripts execute the CRNN-CTC evaluation.

**Comment by wojtuss** [comment]
@luotao1 , I have just found out that I really do not need the `warpctc` operator.
Thanks!
