### ISSUE TITLE
gru4rec 启动报错

### ISSUE THREAD

**Issue by jackyhawk** [PaddlePaddle/Paddle#14815]
E1210 10:11:24.682713  1501 grpc_client.cc:338] SendRPC name:[fc_1.w_0@GRAD.block0.trainer_1], ep:[127.0.0.1:6000], status:[-1] meets grpc error, error_code:4 error_message:Deadline Exceeded error_details:
E1210 10:11:24.683696  1501 grpc_client.cc:338] SendRPC name:[embedding_0.w_0@GRAD.block0.trainer_1], ep:[127.0.0.1:6000], status:[-1] meets grpc error, error_code:4 error_message:Deadline Exceeded error_details:
E1210 10:11:24.683753  1501 grpc_client.cc:338] SendRPC name:[fc_0.w_0@GRAD.block1.trainer_1], ep:[127.0.0.1:6000], status:[-1] meets grpc error, error_code:4 error_message:Deadline Exceeded error_details:
E1210 10:11:24.683784  1501 grpc_client.cc:338] SendRPC name:[fc_0.b_0@GRAD.trainer_1], ep:[127.0.0.1:6000], status:[-1] meets grpc error, error_code:4 error_message:Deadline Exceeded error_details:
E1210 10:11:24.683814  1501 grpc_client.cc:338] SendRPC name:[gru_0.w_0@GRAD.block1.trainer_1], ep:[127.0.0.1:6000], status:[-1] meets grpc error, error_code:4 error_message:Deadline Exceeded error_details:
E1210 10:11:24.683840  1501 grpc_client.cc:338] SendRPC name:[gru_0.b_0@GRAD.trainer_1], ep:[127.0.0.1:6000], status:[-1] meets grpc error, error_code:4 error_message:Deadline Exceeded error_details:
('use_cuda:', False)
start constuct word dict
run distribute training
run trainer
epoch_1 start
Traceback (most recent call last):
  File "cluster_train.py", line 140, in <module>
    train()
  File "cluster_train.py", line 137, in train
    train_loop(t.get_trainer_program())
  File "cluster_train.py", line 102, in train_loop
    fetch_list=fetch_list)
  File "/data0/home/jy7/python_installed/lib/python2.7/site-packages/paddle/fluid/executor.py", line 470, in run
    self.executor.run(program.desc, scope, 0, True, True)
paddle.fluid.core.EnforceNotMet: internal error in RPCClient at [/paddle/paddle/fluid/operators/send_barrier_op.cc:47]
PaddlePaddle Call Stacks: 
0       0x7fde36e8fab6p paddle::platform::EnforceNotMet::EnforceNotMet(std::__exception_ptr::exception_ptr, char const*, int) + 486
1       0x7fde37890794p paddle::operators::SendBarrierOp::RunImpl(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&) const + 788
2       0x7fde37b04b58p paddle::framework::OperatorBase::Run(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&) + 232
3       0x7fde36f530fbp paddle::framework::Executor::RunPreparedContext(paddle::framework::ExecutorPrepareContext*, paddle::framework::Scope*, bool, bool, bool) + 219
4       0x7fde36f53ee0p paddle::framework::Executor::Run(paddle::framework::ProgramDesc const&, paddle::framework::Scope*, int, bool, bool) + 128
5       0x7fde36e748bdp
6       0x7fde36ec4cb4p pybind11::cpp_function::dispatcher(_object*, _object*, _object*) + 2596
7       0x7fde6c34a45ap PyEval_EvalFrameEx + 34762
8       0x7fde6c34b868p PyEval_EvalCodeEx + 1976
9       0x7fde6c3481d1p PyEval_EvalFrameEx + 25921
10      0x7fde6c34b868p PyEval_EvalCodeEx + 1976
11      0x7fde6c3481d1p PyEval_EvalFrameEx + 25921
12      0x7fde6c34b868p PyEval_EvalCodeEx + 1976
13      0x7fde6c3481d1p PyEval_EvalFrameEx + 25921
14      0x7fde6c34b868p PyEval_EvalCodeEx + 1976
15      0x7fde6c34ba79p PyEval_EvalCode + 25
16      0x7fde6c36e02ap PyRun_FileExFlags + 138
17      0x7fde6c36fe23p PyRun_SimpleFileExFlags + 211
18      0x7fde6c388c4ep Py_Main + 2830
19      0x7fde6b577b35p __libc_start_main + 245
20            0x40071ep

**Comment by jackyhawk** [comment]
大伙有谁遇到过吗？

**Comment by frankwhzhang** [comment]
在哪里实现的？是paddlecloud 还是本地

**Comment by frankwhzhang** [comment]
本地跑的话 需要关闭代理

**Comment by jackyhawk** [comment]
多谢 @frankwhzhang .

我是在自己的服务器上跑的，关闭的是哪个代理（或者怎样关闭代理），非常感谢

**Comment by jackyhawk** [comment]
貌似 --is_local 1  这样设置就ok了

**Comment by frankwhzhang** [comment]
echo http_proxy和https_proxy ，unset http_proxy 关闭代理，但一般得是进入shell前就要关闭才有效

**Comment by BiaoPeng** [comment]
同样问题 周六在pddle cloud 上没问题 今天就出问题了

**Comment by frankwhzhang** [comment]
> 同样问题 周六在pddle cloud 上没问题 今天就出问题了

这个是稳定复现的问题吗

**Comment by BiaoPeng** [comment]
> > 同样问题 周六在pddle cloud 上没问题 今天就出问题了
> 
> 这个是稳定复现的问题吗

今天 起了 好几次任务 就是同样的错误 
E1210 18:54:18.154878  9260 grpc_client.cc:342] SendRPC name:[emb.w@GRAD.block3.trainer_0], ep:[10.156.85.34:8000], status:[-1] meets grpc error, error_code:4 error_message:Deadline Exceeded error_details:
Traceback (most recent call last):
  File "train.py", line 300, in <module>
    train()
  File "train.py", line 289, in train
    train_reader, place, avg_cost)
  File "train.py", line 173, in train_parallel
    avg_loss_value = parallel_exe.run([avg_cost.name])
  File "/home/disk1/normandy/maybach/app-user-20181210181746-3770/workspace/python27-gcc482/lib/python2.7/site-packages/paddle/fluid/parallel_executor.py", line 277, in run
    self.executor.run(fetch_list, fetch_var_name)
paddle.fluid.core.EnforceNotMet: internal error in RPCClient at [/paddle/paddle/fluid/operators/send_barrier_op.cc:48]
PaddlePaddle Call Stacks: 
0       0x7f90ef8b0c26p paddle::platform::EnforceNotMet::EnforceNotMet(std::__exception_ptr::exception_ptr, char const*, int) + 486
1       0x7f90f02a4c30p paddle::operators::SendBarrierOp::RunImpl(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&) const + 864

**Comment by frankwhzhang** [comment]
> > > 同样问题 周六在pddle cloud 上没问题 今天就出问题了
> > 
> > 
> > 这个是稳定复现的问题吗
> 
> 今天 起了 好几次任务 就是同样的错误
> E1210 18:54:18.154878 9260 grpc_client.cc:342] SendRPC name:[emb.w@GRAD.block3.trainer_0], ep:[10.156.85.34:8000], status:[-1] meets grpc error, error_code:4 error_message:Deadline Exceeded error_details:
> Traceback (most recent call last):
> File "train.py", line 300, in 
> train()
> File "train.py", line 289, in train
> train_reader, place, avg_cost)
> File "train.py", line 173, in train_parallel
> avg_loss_value = parallel_exe.run([avg_cost.name])
> File "/home/disk1/normandy/maybach/app-user-20181210181746-3770/workspace/python27-gcc482/lib/python2.7/site-packages/paddle/fluid/parallel_executor.py", line 277, in run
> self.executor.run(fetch_list, fetch_var_name)
> paddle.fluid.core.EnforceNotMet: internal error in RPCClient at [/paddle/paddle/fluid/operators/send_barrier_op.cc:48]
> PaddlePaddle Call Stacks:
> 0 0x7f90ef8b0c26p paddle::platform::EnforceNotMet::EnforceNotMet(std::__exception_ptr::exception_ptr, char const*, int) + 486 1 0x7f90f02a4c30p paddle::operators::SendBarrierOp::RunImpl(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&) const + 864

如果之前可以跑通 今天不行的话 可以联系paddlecloud那边的同学，有可能是网络问题

**Comment by frankwhzhang** [comment]
经与用户沟通，问题已解决，暂时关闭此issue
