### ISSUE TITLE
paddlepaddle 在tensor中通过boolean值索引矩阵

### ISSUE THREAD

**Issue by GuangyanZhang** [PaddlePaddle/Paddle#14816]
我想用paddlepaddle做一个tensor的boolean值索引矩阵，在tensorflow中是这个函数tf.boolean_mask,我想知道paddlepaddle有没有这样功能的函数。。（我自己在官方文档找了好久都没有找到），请大佬帮我解答下，谢谢。。。。

**Comment by frankwhzhang** [comment]
目前没有这个op 您可以自己开发一个或者使用已有的op组合

**Comment by GuangyanZhang** [comment]
@frankwhzhang 我用numpy实现了，但是网络模型涉及的是tensor，所以不好对tensor操作，能不能教下怎么用已有的op组合吗？

**Comment by frankwhzhang** [comment]
这个不确定可以实现 一般是自己实现op是最好的

**Comment by frankwhzhang** [comment]
用户未回应，暂时关闭此issue。
