### ISSUE TITLE
在Windows在图像分类训练报错

### ISSUE THREAD

**Issue by yeyupiaoling** [PaddlePaddle/Paddle#14810]
# 环境：
 - PaddlePaddle 1.2.0
 - Windows 10 专业版
 - Python 3.5

# 问题：
在训练图像分类的时候，报错。是不是MNIST数据集接口出了问题？

```
Traceback (most recent call last):
  File "D:/ubuntu/paddlepaddle/pycharm/PycharmProjects/LearnPaddle2/note4/test.py", line 86, in <module>
    for batch_id, data in enumerate(train_reader()):
  File "C:\Python35\lib\site-packages\paddle\batch.py", line 35, in batch_reader
    for instance in r:
  File "C:\Python35\lib\site-packages\paddle\dataset\mnist.py", line 49, in reader
    raise NotImplementedError()
NotImplementedError

```

不知道是不是这个问题。

https://github.com/PaddlePaddle/Paddle/blob/943ad4781f5c96573e9615668c1cc73dcb378356/python/paddle/dataset/mnist.py#L43-L49

**Comment by junjun315** [comment]
获取数据中使用了命令行指令，当前没有对windows环境进行兼容考虑。后面会修改掉这个数据集获取实现

**Comment by yeyupiaoling** [comment]
哦哦，明白。

**Comment by yeyupiaoling** [comment]
@junjun315 突然想到，你说的修改掉，是删除Windows下这个数据集，还是完善它，让mnist数据集支持Windows下调用？

**Comment by qianledan** [comment]
应该是将mnist的数据重新用windows的打包工具打包。让windows系统也能查看，格式应该由.gz修改为其它windows支持的格式。

**Comment by junjun315** [comment]
我们重写了这个数据集的reader，然后兼容linux和window环境下读取。
可以参考这个pr: https://github.com/PaddlePaddle/Paddle/pull/15273

**Comment by junjun315** [comment]
@yeyupiaoling 我们完善了它。
 @qianledan 也想过这样做，但为了保持代码统一以及前后版本的兼容，我们用了通用的gz读取办法。如果有好的建议也可以提给我们哈~
