### ISSUE TITLE
example for lmdb reader

### ISSUE THREAD

**Issue by imistyrain** [PaddlePaddle/Paddle#14822]
[#4695](https://github.com/PaddlePaddle/Paddle/issues/4695)里面有人问道是否有lmdb的reader，但是并没有给出使用的示例,是否需要自己实现这个reader,有没有计划支持，如果有的话什么时候能完成?

**Comment by frankwhzhang** [comment]
https://github.com/PaddlePaddle/Paddle/blob/f90c7865f0ababccd89332604e7e181c85cf9b60/benchmark/fluid/models/stacked_dynamic_lstm.py

**Comment by frankwhzhang** [comment]
暂时没有这个计划

**Comment by frankwhzhang** [comment]
经与用户沟通，先关闭这个issue

**Comment by frankwhzhang** [comment]
帮助用户联系了相关老师，下载了ILSVRC2012的数据
