### ISSUE TITLE
如何知晓import paddle的版本

### ISSUE THREAD

**Issue by topxxuki** [PaddlePaddle/Paddle#14835]
安装版本：v1.2 /v0.14
python 2.7.13
系统环境 centos7

有没有类似于sys.version_info知道python版本的方法查看paddle版本？

**Comment by topxxuki** [comment]
0.14的安装链接：https://files.pythonhosted.org/packages/e0/34/e953e61c6024e32383d8053c12c88c2e7270af406a38e960cff55de6b07a/paddlepaddle-0.14.0-cp27-cp27mu-manylinux1_x86_64.whl

采用
import paddle
print paddle.__version__ 
输出版本好0.0.0

**Comment by JiabinYang** [comment]
您可以直接在命令行输入`paddle version`

**Comment by topxxuki** [comment]
> 您可以直接在命令行输入`paddle version`

![image](https://user-images.githubusercontent.com/18697846/49775326-c9c31e80-fd32-11e8-9fc7-671a62991a92.png)

**Comment by JiabinYang** [comment]
或者在python使用`print(paddle.__version__)`

**Comment by frankwhzhang** [comment]
经与用户沟通 ，用户把所有的paddle_release_home都删除，重新下载用.whl安装了
