### ISSUE TITLE
models/fluid/PaddleNLP/chinese_ner 无法正常跑模型

### ISSUE THREAD

**Issue by ylxsyf** [PaddlePaddle/Paddle#14833]
train.py中34行把默认的GPU换成了CPU

pass_id:0, time_cost:2.85610508919s
[Train] precision:0.00207385603425, recall:0.0168753402286, f1:0.00369377420316
Traceback (most recent call last):
  File "train.py", line 356, in <module>
    main(args)
  File "train.py", line 344, in main
    [num_infer_chunks, num_label_chunks, num_correct_chunks])
  File "train.py", line 231, in test2
    fetch_list=cur_fetch_list)
  File "/root/.jumbo/lib/python2.7/site-packages/paddle/fluid/executor.py", line 470, in run
    self.executor.run(program.desc, scope, 0, True, True)
paddle.fluid.core.EnforceNotMet: Cannot find fetch variable in scope, fetch_var_name is chunk_eval_0.tmp_3 at [/paddle/paddle/fluid/operators/fetch_op.cc:37]
PaddlePaddle Call Stacks:
0       0x7fa84f0fdd86p paddle::platform::EnforceNotMet::EnforceNotMet(std::__exception_ptr::exception_ptr, char const*, int) + 486
1       0x7fa84f4818f9p paddle::operators::FetchOp::RunImpl(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&) const + 1689
2       0x7fa84facd00fp paddle::framework::OperatorBase::Run(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&) + 255
3       0x7fa84f1bb9d9p paddle::framework::Executor::RunPreparedContext(paddle::framework::ExecutorPrepareContext*, paddle::framework::Scope*, bool, bool, bool) + 393
4       0x7fa84f1bc5d0p paddle::framework::Executor::Run(paddle::framework::ProgramDesc const&, paddle::framework::Scope*, int, bool, bool) + 128
5       0x7fa84f0e565dp
6       0x7fa84f130034p pybind11::cpp_function::dispatcher(_object*, _object*, _object*) + 2596
7       0x7fa8740343d4p PyEval_EvalFrameEx + 25956
8       0x7fa874035120p PyEval_EvalCodeEx + 2240
9       0x7fa874033491p PyEval_EvalFrameEx + 22049
10      0x7fa874033c46p PyEval_EvalFrameEx + 24022

**Comment by frankwhzhang** [comment]
根据用户需求，建议用户使用seq_ner模型，经与用户沟通，先关闭此Issue
