### ISSUE TITLE
The `fc_gru_fuse_pass` breaks accuracy in C-API CRNN-CTC inference.

### ISSUE THREAD

**Issue by wojtuss** [PaddlePaddle/Paddle#14837]
The `fc_gru_fuse_pass` breaks accuracy when running CRNN-CTC inference using the C-API.

The application
https://github.com/wojtuss/models/tree/wojtuss/capi-ocr-recognition/fluid/PaddleCV/ocr_recognition/capi
runs inference using the CRNN-CTC trained model
https://github.com/wojtuss/models/blob/wojtuss/capi-ocr-recognition/fluid/PaddleCV/ocr_recognition/models/CRNN-CTC_model.tar.gz
 (with weights from Baidu, with EditDistance evaluator added) on the standard dataset.

With the `fc_gru_fuse_pass` disabled in `infer_ocr_recognition.cc:233` the accuracy we get from the app is equal to the accuracy we get using python `eval.py` script: avg distance = 0.09206844, avg seq error = 0.2425.
With the `fc_gru_fuse_pass` enabled, the accuracy gets lost: avg seq error = 1.0000.

The script
https://github.com/wojtuss/models/blob/wojtuss/capi-ocr-recognition/fluid/PaddleCV/ocr_recognition/capi/infer_ocr_with_accuracy.sh
provides an example of how to run the application.

**Comment by luotao1** [comment]
Yes, we already find that `fc_gru_fuse_pass` breaks accuracy in CRNN-CTC, but we don't have a priority to fix it. You can remove this pass in CRNN-CTC at first:
```
config.pass_builder()->DeletePass("fc_gru_fuse_pass");
```

**Comment by wojtuss** [comment]
OK, thanks!

**Comment by wojtuss** [comment]
@frankwhzhang , was this issue fixed?

**Comment by luotao1** [comment]
@wojtuss It hasn't fixed now.

**Comment by Sand3r-** [comment]
Is it known whether the problem lies within the kernel or within the pass? Or perhaps both?

**Comment by luotao1** [comment]
Sorry, we don't confirm it so far. @Sand3r-

**Comment by luotao1** [comment]
@bingyanghuang
