### ISSUE TITLE
Duplicate symbol in op_library (operator/reader, operator/detection)

### ISSUE THREAD

**Issue by carlushuang** [PaddlePaddle/Paddle#14841]
https://github.com/PaddlePaddle/Paddle/pull/14413

@typhoonzero @luotao1

I found out an symbol duplication issue in ob_library cmake system due to above PR.
All operators are registered in OP_LIBRARY value in cmake, and when you call op_library() function, it will automatically insert to OP_LIBRARY list as defined in [cmake/operators.cmake](https://github.com/PaddlePaddle/Paddle/blob/develop/cmake/operators.cmake#L93). 
```
function(op_library TARGET)
...
    set(OP_LIBRARY ${TARGET} ${OP_LIBRARY} CACHE INTERNAL "op libs")
...
endfunction()
```

However, in [operators/reader/CMakeLists.txt](https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/fluid/operators/reader/CMakeLists.txt#L43) and [operators/detection/CMakeLists.txt](https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/fluid/operators/detection/CMakeLists.txt#L45), they all do a manually register in OP_LIBRARY

```
# in operators/detection/CMakeLists.txt
foreach(src ${LOCAL_DETECTION_LIBS})
    set(OP_LIBRARY ${src} ${OP_LIBRARY} CACHE INTERNAL "op libs")
endforeach()
```

Hence, operators in reader and detection may registered twice in OP_LIBRARY list, and result in link twice the static library.

Maybe the manual register in operators/detection/CMakeLists.txt and operators/reader/CMakeLists.txt may removed?

**Comment by luotao1** [comment]
> Maybe the manual register in operators/detection/CMakeLists.txt and operators/reader/CMakeLists.txt may removed?

When `merge_static_library`, we have already removed the duplicated libs.
https://github.com/PaddlePaddle/Paddle/blob/3243b45bb2fb5aed5fc710515fc3cb5fbf269835/cmake/generic.cmake#L127-L129

**Comment by carlushuang** [comment]
Hi @luotao1 

It seems that merge_static_libs() function may still not able to remove duplicate libraries like libpaddle_pybind.so to remove duplicate static lib.

merge_static_libs() is currently used in [cc_library()](https://github.com/PaddlePaddle/Paddle/blob/3243b45bb2fb5aed5fc710515fc3cb5fbf269835/cmake/generic.cmake#L286), [nv_library()](https://github.com/PaddlePaddle/Paddle/blob/3243b45bb2fb5aed5fc710515fc3cb5fbf269835/cmake/generic.cmake#L405), [hip_library()](https://github.com/PaddlePaddle/Paddle/blob/3243b45bb2fb5aed5fc710515fc3cb5fbf269835/cmake/generic.cmake#L484), and it will be called only if there is no SRCS parsed to cc_library()
```
  else(cc_library_SRCS)  # here it check cc_library() parsed in SRC
    if(cc_library_DEPS)
      merge_static_libs(${TARGET_NAME} ${cc_library_DEPS})
    else()
      message(FATAL "Please specify source file or library in cc_library.")
    endif()
  endif(cc_library_SRCS)
endfunction(cc_library)
```

and for libpaddle_pybind.so senario:

```
# in function(op_library TARGET)
set(OP_LIBRARY ${TARGET} ${OP_LIBRARY} CACHE INTERNAL "op libs")

# then in paddle/fluid/operators/CMakeLists.txt
set(GLOB_OP_LIB ${OP_LIBRARY} CACHE INTERNAL "Global OP library")

# finally in  paddle/fluid/pybind/CMakeLists.txt
    cc_library(paddle_pybind SHARED
      SRCS ${PYBIND_SRCS}  # SRCS parsed in
      DEPS ${PYBIND_DEPS}
      ${GLOB_OP_LIB} ${GLOB_OPERATOR_DEPS})
    if(NOT APPLE AND NOT ANDROID AND NOT WIN32
```
so the ops will result in link to **libpaddle_pybind.so** twice

Maybe merge_static_libs() need be called without the cc_library_DEPS check?

**Comment by luotao1** [comment]
Could you tell me what's the problem (compiler error or any other else) do you encount?

**Comment by carlushuang** [comment]
Runtime error with AMDGPU backend.
For it use [ARCHIEVE_START/END](https://github.com/PaddlePaddle/Paddle/blob/3243b45bb2fb5aed5fc710515fc3cb5fbf269835/paddle/fluid/pybind/CMakeLists.txt#L8) in paddle_pybind target link stage.
This will result the duplicated op static lib linked in libpaddle_pybind.so, and op registed by REGISTER_OPERATOR() may call constructor twice, hence crash.

I know remove ARCHIEVE_START/END can resolve the issue, but still want to know if all the libs is designed to remove duplication or not.
