### ISSUE TITLE
单机多卡训练时，使用的是pserver方式还是nccl方式进行训练？

### ISSUE THREAD

**Issue by dashulu** [PaddlePaddle/Paddle#14840]
paddle进行单机多卡训练时，是使用pserver还是nccl方式同步参数的？两种方式都支持吗？有没有每种方式的例子？

**Comment by typhoonzero** [comment]
单机多卡训练可以参考文档：http://www.paddlepaddle.org/documentation/docs/zh/1.2/user_guides/howto/training/single_node.html#permalink-6--

**Comment by typhoonzero** [comment]
单机多卡训练，参考文档：http://www.paddlepaddle.org/documentation/docs/zh/1.2/user_guides/howto/training/single_node.html#permalink-6--

参考的例子：https://github.com/PaddlePaddle/models/tree/develop/fluid/PaddleCV/image_classification

单机训练，可以不用考虑是否使用pserver还是nccl2方式，默认都是使用nccl2完成多卡训练，一般只有多节点才会考虑使用pserver或跨节点nccl2通信。但单机也可以模拟多个节点的方式训练，但效率不高并不是默认的使用方式
