### ISSUE TITLE
如何提高Paddle在X86的CPU的预测性能

### ISSUE THREAD

**Issue by Ouyangtengfang** [PaddlePaddle/Paddle#14856]
你好！ 我在Intel的J1800赛扬CPU，2G内存的Ubutun14.04的工控机，调用Paddle的SSD物件检测模型，预测一张图片的时间大约是0.5秒左右，但是这个速度不能满足我们应用的需求（我们需要把预测时间减少到到0.04秒），请问在不提高硬件性能的前提下，如何才能提高Paddle的检测速度，我们只需要在机器做预测，不需要做训练，训练在服务器进行，谢谢！

**Comment by colourful-tree** [comment]
指令集的优化可以参考
http://paddlepaddle.org/documentation/docs/zh/1.0/user_guides/howto/inference/build_and_install_lib_cn.html#id1

**Comment by Ouyangtengfang** [comment]
你好！ 首先，非常感谢你的回复！ 但是由于我用的Python，你上面介绍的指令集优化是基于C++，所以，请问如果我用Python有其他的优化方法吗？ 谢谢！

**Comment by colourful-tree** [comment]
python只是一个前端，实际的运行是基于c++完成的，所以如果想做优化的话，肯定是要对c++进行优化。

**Comment by Ouyangtengfang** [comment]
好的，我先试试你的方法，如果有问题，再向你请教，谢谢！

**Comment by Ouyangtengfang** [comment]
你好！这几天我换了一台性能好很多的电脑（英特尔ｉ７　８５６５），１６Ｇ内存的手提电脑，执行ＳＳＤ模型的示例代码（https://github.com/PaddlePaddle/models/blob/develop/fluid/PaddleCV/object_detection/README_cn.md），但是我执行预测：python infer.py --dataset='pascalvoc' --nms_threshold=0.45 --model_dir='./model/best_model' --image_path='/usr/tengfang/Python/object_detection/data/pascalvoc/plate_number/images/000300.jpg'，执行时间是０．１秒左右，但依然不能满足我们的需求，请问有什么参数可以优化ｉｎｆｅｒ的速度吗？谢谢！

**Comment by luotao1** [comment]
1. 建议使用C++部署，C++预测上做了很多Python端并没有的优化。可参考[服务器部署文档](http://www.paddlepaddle.org/documentation/docs/zh/1.2/advanced_usage/deploy/inference/index_cn.html)
2. 如果使用Python预测，有以下几个方法可以提速：
   - 检查安装的paddle包`paddle version`，是否为MKL版本。如果是OpenBlas版本，建议升级到MKL版本。`pip install paddlepaddle==1.2.0`
   - `i7 8565`有4个核，使用top命令看下预测时，是否4个核都跑满了。如果没有，可以采用以下三个方法任一（三个方法独立互斥，不能同时使用）
       - 使用环境变量：`export MKL_NUM_THREADS=4`和`export OMP_NUM_THREADS=4`
       - 使用`ParallelExecutor`代替Executor，https://github.com/PaddlePaddle/models/blob/develop/fluid/PaddleCV/object_detection/infer.py#L71-L75 改为：
          ```
          test_program = fluid.default_main_program().clone(for_test=True)
          test_exe = fluid.ParallelExecutor(use_cuda=False, main_program=test_program)
          nmsed_out_v, = test_exe.run(feed=feeder.feed([[data]]), fetch_list=[nmsed_out])
          ```
       - 使用MKLDNN库（因为i7 8565支持avx2指令集），命令为`FLAGS_use_mkldnn=true python infer.py --dataset='pascalvoc' --nms_threshold=0.45 --model_dir='./model/best_model' --image_path='/usr/tengfang/Python/object_detection/data/pascalvoc/plate_number/images/000300.jpg'`

**Comment by lucywsq** [comment]
您好，鉴于此问题已经解决，我们将于今天内关闭，如果您若在关闭后您仍需跟进提问，可重新开启此问题，我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持
