### ISSUE TITLE
较早版本中的fluid.layers.get_places去哪里了？

### ISSUE THREAD

**Issue by molly00ecla** [PaddlePaddle/Paddle#14859]
单机多卡训练
之前的demo使用的是 places = fluid.layers.get_places() 之类的，这个接口只在0.X版本有。更新到1.1之后就没有了……
demo来源：
https://mp.weixin.qq.com/s/6xU0cmg1biH4c-mmwbkjNg
或者单机多卡是否有其它的实现方式？

补充：
参考https://github.com/PaddlePaddle/models/blob/75594b98b27cfb793832064f2b43be4086311a41/fluid/PaddleRec/gru4rec/train.py#L115
对代码进行修改，会报错：

![image](https://user-images.githubusercontent.com/22423844/49846100-96e95b00-fe04-11e8-87f8-d8695f9e0961.png)
但是单GPU情况下就没有问题

**Comment by colourful-tree** [comment]
executor 获取place可以参考http://paddlepaddle.org/documentation/docs/zh/1.2/api_cn/fluid_cn.html#executor

**Comment by molly00ecla** [comment]
> executor 获取place可以参考http://paddlepaddle.org/documentation/docs/zh/1.2/api_cn/fluid_cn.html#executor

这个只能使用CUDAPlace()，且具体使用方法也没有说明。fluid.layers.get_places()可以获取当前所有可使用的显卡。Returns a list of places based on flags. The list will be used for parallel execution.

**Comment by colourful-tree** [comment]
看一下ParallelExecutor
http://paddlepaddle.org/documentation/docs/zh/1.2/api_cn/fluid_cn.html#parallelexecutor

**Comment by molly00ecla** [comment]
> 看一下ParallelExecutor
> http://paddlepaddle.org/documentation/docs/zh/1.2/api_cn/fluid_cn.html#parallelexecutor

嗯，我使用ParallelExecutor会报错，就是一开始题图里面那个……Orz

**Comment by chengduoZH** [comment]
> 之前的demo使用的是 places = fluid.layers.get_places() 之类的

这个API已经删除了，因为这个API最初是为配合ParallelDo使用的，但是ParallelDo存在性能问题，所以目前转向使用ParallelExecutor。ParallelExecutor是一个数据并行执行引擎，相关内容可以参考：http://paddlepaddle.org/documentation/docs/zh/1.2/api_cn/api_guides/low_level/parallel_executor.html

您可以把ParallelExecutor运行报错的模型贴一下吗？@molly00ecla

**Comment by molly00ecla** [comment]
> > 之前的demo使用的是 places = fluid.layers.get_places() 之类的
> 
> 这个API已经删除了，因为这个API最初是为配合ParallelDo使用的，但是ParallelDo存在性能问题，所以目前转向使用ParallelExecutor。ParallelExecutor是一个数据并行执行引擎，相关内容可以参考：http://paddlepaddle.org/documentation/docs/zh/1.2/api_cn/api_guides/low_level/parallel_executor.html
> 
> 您可以把ParallelExecutor运行报错的模型贴一下吗？@molly00ecla

感谢回答，明白啦。
报错那个我单独开了个问题~
