### ISSUE TITLE
Paddle Tensor RT 的测试是否有使用类似Python前端的profiler工具？

### ISSUE THREAD

**Issue by procr** [PaddlePaddle/Paddle#14852]
跑的例子仿照下面链接：
http://www.paddlepaddle.org/documentation/docs/zh/develop/user_guides/howto/inference/paddle_tensorrt_infer.html

**Comment by procr** [comment]
想要得到相关的性能数据，例如跑完一次inference的总体耗时，应该怎么统计？

**Comment by wangguibao** [comment]
如果是总体耗时，每个batch的inference的总体耗时，在Run()前后计时就可以了吧

还是说我没有理解到您的需求呢
