### ISSUE TITLE
 optimize operations cannot be depended by forward or backward node sgd -> elementwise_add_grad 

### ISSUE THREAD

**Issue by molly00ecla** [PaddlePaddle/Paddle#14860]
使用ParallelExecutor后报错
![image](https://user-images.githubusercontent.com/22423844/49850207-9a3a1200-fe17-11e8-84be-c50d2f45ba6d.png)

![image](https://user-images.githubusercontent.com/22423844/49850189-8a223280-fe17-11e8-9407-4e73fea2ad22.png)

**Comment by chengduoZH** [comment]
@molly00ecla 你的模型是怎样的，可以贴一下吗

**Comment by chengduoZH** [comment]
Similar with https://github.com/PaddlePaddle/Paddle/issues/14859

**Comment by molly00ecla** [comment]
> @molly00ecla 你的模型是怎样的，可以贴一下吗

http://aistudio.baidu.com/#/projectdetail/29882
这个工程里面有数据集，所以可能会耗时十几分钟打开……
element_add 这个操作在In[9]中（ResNet的ShortCut）和In[11]处。
代码使用单GPU或者CPU可以正常进行优化。
感谢！❤

**Comment by chengduoZH** [comment]
为什么你这里对一个Program会有这么多的optimizer呢？
```
    if SOLVE_STATUS == 'PCB':
        #ptimizer = fluid.optimizer.MomentumOptimizer(lr_schedule,0.001)
        #optimizer2 = fluid.optimizer.MomentumOptimizer(0.1*lr_schedule, 0.001)
        optimizer = fluid.optimizer.AdamOptimizer(0.01, regularization=fluid.regularizer.L2DecayRegularizer(regularization_coeff=0.0001))
        optimizer2 = fluid.optimizer.AdamOptimizer(0.001, regularization=fluid.regularizer.L2DecayRegularizer(regularization_coeff=0.0001))
        opts = optimizer.minimize(avg_cost, parameter_list=remain_param)
        opts_net = optimizer2.minimize(avg_cost, parameter_list=pretrained_param)
    elif SOLVE_STATUS == 'PCB+RPP':
        optimizer3 = fluid.optimizer.SGDOptimizer(0.1*lr_schedule)
        opts = optimizer3.minimize(avg_cost, parameter_list=RPP_param)
    else:
        optimizer = fluid.optimizer.SGDOptimizer(0.1*lr_schedule)
        optimizer2 = fluid.optimizer.SGDOptimizer(0.1*lr_schedule)
        optimizer3 = fluid.optimizer.SGDOptimizer(0.1*lr_schedule)
        opts = optimizer.minimize(avg_cost, parameter_list=remain_param)
        opts_net = optimizer2.minimize(avg_cost, parameter_list=pretrained_param)
        opts_RPP = optimizer3.minimize(avg_cost, parameter_list=RPP_param)
       
```

**Comment by molly00ecla** [comment]
> 为什么你这里对一个Program会有这么多的optimizer呢？
> 
> ```
>     if SOLVE_STATUS == 'PCB':
>         #ptimizer = fluid.optimizer.MomentumOptimizer(lr_schedule,0.001)
>         #optimizer2 = fluid.optimizer.MomentumOptimizer(0.1*lr_schedule, 0.001)
>         optimizer = fluid.optimizer.AdamOptimizer(0.01, regularization=fluid.regularizer.L2DecayRegularizer(regularization_coeff=0.0001))
>         optimizer2 = fluid.optimizer.AdamOptimizer(0.001, regularization=fluid.regularizer.L2DecayRegularizer(regularization_coeff=0.0001))
>         opts = optimizer.minimize(avg_cost, parameter_list=remain_param)
>         opts_net = optimizer2.minimize(avg_cost, parameter_list=pretrained_param)
>     elif SOLVE_STATUS == 'PCB+RPP':
>         optimizer3 = fluid.optimizer.SGDOptimizer(0.1*lr_schedule)
>         opts = optimizer3.minimize(avg_cost, parameter_list=RPP_param)
>     else:
>         optimizer = fluid.optimizer.SGDOptimizer(0.1*lr_schedule)
>         optimizer2 = fluid.optimizer.SGDOptimizer(0.1*lr_schedule)
>         optimizer3 = fluid.optimizer.SGDOptimizer(0.1*lr_schedule)
>         opts = optimizer.minimize(avg_cost, parameter_list=remain_param)
>         opts_net = optimizer2.minimize(avg_cost, parameter_list=pretrained_param)
>         opts_RPP = optimizer3.minimize(avg_cost, parameter_list=RPP_param)
>        
> ```

各种优化策略。其实只有两三个opt，看起来多而已……
然后这是一篇paper的复现，原文如此。大致就是有时候需要固定一部分参数，有时候需要对不同的参数使用不同的lr……

**Comment by molly00ecla** [comment]
> 为什么你这里对一个Program会有这么多的optimizer呢？
> 
> ```
>     if SOLVE_STATUS == 'PCB':
>         #ptimizer = fluid.optimizer.MomentumOptimizer(lr_schedule,0.001)
>         #optimizer2 = fluid.optimizer.MomentumOptimizer(0.1*lr_schedule, 0.001)
>         optimizer = fluid.optimizer.AdamOptimizer(0.01, regularization=fluid.regularizer.L2DecayRegularizer(regularization_coeff=0.0001))
>         optimizer2 = fluid.optimizer.AdamOptimizer(0.001, regularization=fluid.regularizer.L2DecayRegularizer(regularization_coeff=0.0001))
>         opts = optimizer.minimize(avg_cost, parameter_list=remain_param)
>         opts_net = optimizer2.minimize(avg_cost, parameter_list=pretrained_param)
>     elif SOLVE_STATUS == 'PCB+RPP':
>         optimizer3 = fluid.optimizer.SGDOptimizer(0.1*lr_schedule)
>         opts = optimizer3.minimize(avg_cost, parameter_list=RPP_param)
>     else:
>         optimizer = fluid.optimizer.SGDOptimizer(0.1*lr_schedule)
>         optimizer2 = fluid.optimizer.SGDOptimizer(0.1*lr_schedule)
>         optimizer3 = fluid.optimizer.SGDOptimizer(0.1*lr_schedule)
>         opts = optimizer.minimize(avg_cost, parameter_list=remain_param)
>         opts_net = optimizer2.minimize(avg_cost, parameter_list=pretrained_param)
>         opts_RPP = optimizer3.minimize(avg_cost, parameter_list=RPP_param)
>        
> ```

update： 好像真的是多个opt导致的问题。我只使用一个opt的时候，就没有这个问题了……我改到用ParamAttr控制应该就可以了。
❤非常感谢！！！ ^3^
