### ISSUE TITLE
如何固定模型部分参数只训练另一部分参数

### ISSUE THREAD

**Issue by dubhex** [PaddlePaddle/Paddle#14870]
模型由主干分支和次分支构成，次分支是在主干分支上后接出来的。现在主干分支已经训练好并将相关参数保存为params。在新的训练中，希望先加载主干部分参数并固定，只训练次分支的参数。
已经尝试过两种方法：
（1）对于主干分支的层，设置paddle.fluid.ParamAttr中trainable=False;
（2）对于主干分支的层，设置paddle.fluid.ParamAttr中learning_rate=0;
但是测试表明主干分支的参数被改变了，上述两种方法都不成功。
有两个问题：
（1）使用上述两种方法时是否需要其它的设置？
（2）是否有方法能够实现我的目的？

**Comment by gavin1332** [comment]
能确认主干分支的参数在次分支上正确加载吗？比如加载后不训练直接保存，确认主干分支部分参数一致

**Comment by dubhex** [comment]
> 能确认主干分支的参数在次分支上正确加载吗？比如加载后不训练直接保存，确认主干分支部分参数一致

已经确定能正确加载，加载后主干分支输出测试结果也是正常的。

**Comment by gavin1332** [comment]
RMSOptimizer貌似不ParamAttr的trainbale=false和learning_rate控制
SGDOptimizer验证无误

**Comment by lucywsq** [comment]
您好，此问题超过48小时未有进一步回复，我们将于今天内关闭，如果您若在关闭后您仍需跟进提问，可重新开启此问题，我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持
