### ISSUE TITLE
paddle训练速度慢，主要是数据传输慢，怎么解决？

### ISSUE THREAD

**Issue by yuyy0823** [PaddlePaddle/Paddle#14876]
PaddlePaddle 0.14 GPU版本
单机2个GPU跑二分类，特征7k维，batch_size=1024，网络结构是一个2层的CNN，参数维数比较低。
使用profiler分析发现耗时应该主要是数据从cpu到gpu拷贝比较慢，以下分别是按照cputime和gputime逆序排列的结果。看起来paddle内部的操作耗时都不多，主要是io耗时高，请问该如何优化这一部分？
method  gputime  cputime
memcpyHtoD 1.824 19204.238
memcpyHtoD 3.808 12522.656
memcpyHtoD 1.728 10132.713
memcpyHtoD 1.408 9395.499
memcpyHtoD 1.440 7006.348
memcpyHtoD 1.632 6175.062
memcpyHtoD 5.824 5356.806
memcpyHtoD 1.440 4094.026

memcpyDtoH 6.464 2733.988
memcpyDtoH 6.176 2711.298
memcpyDtoH 8.480 2578.788
memcpyDtoH 17.088 2418.215
memcpyDtoH 4.128 2269.545
memcpyDtoH 3.264 2194.679
memcpyHtoD 10.848 2169.339
memcpyHtoD 3.168 2131.716
memcpyDtoH 1.856 2019.804
memcpyDtoH 4.000 1983.331
memcpyHtoD 121.824 1846.201

尝试使用paddle.reader.xmap_readers，但感觉并没有用

**Comment by colourful-tree** [comment]
建议尝试一下pyreader

**Comment by yuyy0823** [comment]
用的是pyreader呢，目前的网络结构如下图
![image](https://user-images.githubusercontent.com/28800753/49983416-959f6600-ff9d-11e8-9db2-c655f9b1a60b.png)

训练50w的数据，跑10个epoch需要大概6个小时，时间太长了
![image](https://user-images.githubusercontent.com/28800753/49983390-6c7ed580-ff9d-11e8-8278-157ad1ba83d6.png)

**Comment by Yancey0623** [comment]
您好，模型计算量比较小时，IO占比确实会相对增加，请问现在的模式是单卡还是多卡呢？另外可以再详细 profile 一下，确定瓶颈和理想值

1. 目前吞吐: images / sec
1. 单独测试 reader 的吞吐: images / sec
1. pyreader 有 test_mode 模式, 可以屏蔽掉python预处理的性能损耗（仍然会有copy），启动时候使用环境变量: `FLAGS_reader_queue_speed_test_mode=1`: images /sec
1. 尝试增大batch_size

> method gputime cputime
memcpyHtoD 1.824 19204.238
memcpyHtoD 3.808 12522.656
memcpyHtoD 1.728 10132.713

请问这里的gputime和cputime分别是如何统计的呢？

**Comment by yuyy0823** [comment]
现在的是单机2卡，batch_size现在是1024，增大后GPU利用率好像并没有改善，现在基本是0%。下面是profile的详细信息，应该主要还是read比较耗时。gputime和cputime是通过cuda_profiler获得的
![Uploading image.png…]()

**Comment by yuyy0823** [comment]
现在的是单机2卡，batch_size现在是1024，增大后GPU利用率好像并没有改善，现在基本是0%。下面是profile的详细信息，应该主要还是read比较耗时。gputime和cputime是通过cuda_profiler获得的
![profile](https://user-images.githubusercontent.com/28800753/50055697-1bcdcf00-018d-11e9-9df0-61da4c35a1a8.jpg)

images / sec 这个是什么呢？，FLAGS_reader_queue_speed_test_mode=1 设置后profile的结果好像没有太大区别，下面是设置后的结果
![profile2](https://user-images.githubusercontent.com/28800753/50055739-de1d7600-018d-11e9-9c72-cf66128022f0.jpg)

**Comment by Yancey0623** [comment]
> images / sec 这个是什么呢？

吞吐量，就是每秒的样本数，非图片的就是 samples / sec,

> 单独测试 reader 的吞吐: images / sec

可以测下Python预处理的性能，然后和整体训练性能对比一下确定瓶颈是不是在Python预处理这里。

**Comment by yuyy0823** [comment]
1、用python测试reader中数据读取操作的性能，不经过py_reader和模型训练相关过程时，samples / sec=1105
2、只是去掉网络训练过程，其他操作都保留时（如下图），samples / sec=300
![image](https://user-images.githubusercontent.com/28800753/50151058-c9aabc00-02fa-11e9-881a-182dc74dbf7b.png)

3、正常训练时，samples / sec=334
测试时，机器上跑的任务很多，导致cpu占用率很高，可能影响结果，正常第三种应该比第二种吞吐量高的，但应该是数据读取上比较耗时，请问什么优化方法吗？

我的reader没做很复杂的操作
![image](https://user-images.githubusercontent.com/28800753/50146403-99f5b700-02ee-11e9-9aaa-095454f96d94.png)

另外，想问下，我的gpu利用率基本为0，这个可能是哪里有问题呢？

**Comment by Yancey0623** [comment]
> 另外，想问下，我的gpu利用率基本为0，这个可能是哪里有问题呢？

这个基本上就是训练数据比较大，但计算太小了，导致大部分时间都在向GPU拷数据，所以利用率为0.

看你模型也比较简单，用CPU训试试呢？或者多用几块卡，IO时间占太多用GPU训就不太划算了。

**Comment by yuyy0823** [comment]
那模型比较复杂，gpu利用率也很高时，也只是加快训练的速度，数据拷贝到GPU这一步还是会很慢吧，那训练时间还是很长啊

**Comment by Yancey0623** [comment]
是的，CPU到GPU到数据拷贝是一定会存在的，Paddle中`pyreader`使用的是双buffer的策略是通过尽量减少python预处理所占用的时间，但还无法做到数据拷贝和GPU计算overlap。


> 那模型比较复杂，gpu利用率也很高时，也只是加快训练的速度，数据拷贝到GPU这一步还是会很慢吧，那训练时间还是很长啊

GPU利用率很高说明数据拷贝但占比已经很低了（数据拷贝时GPU利用率为0）。

**Comment by imistyrain** [comment]
看源码发现是paddle等一个batch的所有数据都到齐后才进行前传，能不能来个数据就算，不要等都到齐了再算呀,不然这GPU利用率也太惨不忍睹了.
