### ISSUE TITLE
fluid

### ISSUE THREAD

**Issue by zzulike** [PaddlePaddle/Paddle#14881]
用ner模型遇到个问题：
用这个模型在预测的时候发现，给预测数据随意标记的label会影响到最终的预测结果；当把数据减少一些(比如10w)后，这个问题就没有了，数据比较大的时候term的预测结果就会往这个随意标记的类别大量倾斜。。

定义的term的label只有0和1，在预测数据里定义label=2，发现数据量大的时候，预测结果很多都是2。。

出现问题：
![image](https://user-images.githubusercontent.com/19464821/49931200-515e8800-ff01-11e8-8cc2-0487955e1dc3.png)

数据量较小正常：
![image](https://user-images.githubusercontent.com/19464821/49931306-89fe6180-ff01-11e8-9a3f-6ca33a1f3830.png)

**Comment by gavin1332** [comment]
参见 https://github.com/PaddlePaddle/models/issues/1534
