### ISSUE TITLE
Add development tools in Dockerfile

### ISSUE THREAD

**Issue by wangkuiyi** [PaddlePaddle/Paddle#1488]
As we decided to [use Docker container as our development environement](https://github.com/PaddlePaddle/Paddle/issues/1236), we need to add some tools into Dockerfile:

- bash/git auto-completion: https://raw.githubusercontent.com/git/git/master/contrib/completion/git-completion.bash
- remember git password: http://stackoverflow.com/a/5343146/724872
- git-aware bash prompt: https://github.com/jimeh/git-aware-prompt
- pre-commit and clang-format:
   ```
   apt-get install -y clang-format-3.8
   ln -s /usr/bin/clang-format-3.8 /usr/bin/clang-format
   pip install -U pre-commit
   ```

**Comment by gangliao** [comment]
![44bb076a-0dbb-4386-b010-450625ef83c0](https://cloud.githubusercontent.com/assets/3071933/23461433/ddb5dde2-fec4-11e6-9e29-c87d56199f32.png)
