### ISSUE TITLE
训练没有报错，但是output模型没有输出

### ISSUE THREAD

**Issue by huoyuming** [PaddlePaddle/Paddle#14895]
模型训练快一天，日志已经打印pass0 的auc，但是输出目录里并没有输出模型，这个是怎么回事

**Comment by shippingwang** [comment]
> 模型训练快一天，日志已经打印pass0 的auc，但是输出目录里并没有输出模型，这个是怎么回事

1. model_path = os.path.join(model_save_dir + '/' + model_name, str(pass_id))设置路径。
2. fluid.io.save_persistables(exe, model_path, main_program=train_prog) 保存模型。
3. 跑完一个epoch 查看是否有模型输出。

**Comment by lucywsq** [comment]
您好，此问题超过48小时未有进一步回复，我们将于今天内关闭，如果您若在关闭后您仍需跟进提问，可重新开启此问题，我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持
