### ISSUE TITLE
illegal hardware instruction when import paddle.fluid as fluid

### ISSUE THREAD

**Issue by QingGo** [PaddlePaddle/Paddle#14902]
- 版本、环境信息：
    1）PaddlePaddle版本：1.0.0，CPU版，使用‘pip install paddlepaddle==1.0.0 ’安装
    2）CPU：AMD双核P320
    3）GPU：ATI HD5650
    4）系统环境：Ubuntu 17.10，Python版本为3.5.3，用virtualenv建立虚拟环境
- 训练信息
    1）单机
- 复现信息：python进入解释器环境，输入import paddle.fluid as fluid

```
(senta_env_python35) ➜  tools python
Python 3.5.3 (default, Jan 19 2017, 14:11:04) 
[GCC 6.3.0 20170118] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import paddle.fluid as fluid
[1]    22037 illegal hardware instruction (core dumped)  python
```

- 问题描述：在我的Ubuntu 17.10系统里用virtualenv建立python3.5.3虚拟环境，安装paddlepaddle1.0.0的cpu版本后，可以import paddle ，然而import paddle.fluid as fluid就会报错
”[1]    22037 illegal hardware instruction (core dumped)  python”
我的CPU不是Intel的而是AMD，难道是需要自行编译吗？求助。

我目前只能看到这么一行错误信息，如果需要更多的错误信息，请告诉我如何收集这些信息；或者如果需要更详细的运行环境信息的话，也请告诉我。我会把这些信息贴上来。

**Comment by shippingwang** [comment]
> * 版本、环境信息：
>      1）PaddlePaddle版本：1.0.0，CPU版，使用‘pip install paddlepaddle==1.0.0 ’安装
>      2）CPU：AMD双核P320
>      3）GPU：ATI HD5650
>      4）系统环境：Ubuntu 17.10，Python版本为3.5.3，用virtualenv建立虚拟环境
> * 训练信息
>      1）单机
> * 复现信息：python进入解释器环境，输入import paddle.fluid as fluid
> 
> ```
> (senta_env_python35) ➜  tools python
> Python 3.5.3 (default, Jan 19 2017, 14:11:04) 
> [GCC 6.3.0 20170118] on linux
> Type "help", "copyright", "credits" or "license" for more information.
> >>> import paddle.fluid as fluid
> [1]    22037 illegal hardware instruction (core dumped)  python
> ```
> * 问题描述：在我的Ubuntu 17.10系统里用virtualenv建立python3.5.3虚拟环境，安装paddlepaddle1.0.0的cpu版本后，可以import paddle ，然而import paddle.fluid as fluid就会报错
>   ”[1]    22037 illegal hardware instruction (core dumped)  python”
>   我的CPU不是Intel的而是AMD，难道是需要自行编译吗？求助。
> 
> 我目前只能看到这么一行错误信息，如果需要更多的错误信息，请告诉我如何收集这些信息；或者如果需要更详细的运行环境信息的话，也请告诉我。我会把这些信息贴上来。

您安装最新的1.2版本试一下。

**Comment by shippingwang** [comment]
@QingGo 您安装最新的1.2版本试一下

**Comment by QingGo** [comment]
@shippingwang 多谢回复
这次我没开虚拟环境，在系统默认的Python3.6.2下使用‘pip install paddlepaddle==1.2.0 ’安装了paddlepaddle的CPU版，在解释器下或.py文件中执行‘ import paddle.fluid as fluid’时，也仍然会报错“illegal hardware instruction (core dumped) ”。

```
➜  ~ pip list | grep paddle
paddlepaddle                       1.2.0      
➜  ~ python
Python 3.6.2 |Anaconda custom (64-bit)| (default, Jul 20 2017, 13:51:32) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import paddle.fluid as fluid
[2]    26266 illegal hardware instruction (core dumped)  python

```

**Comment by JiabinYang** [comment]
您可以参考官网指南看一线您的机器是否支持avx指令集

**Comment by QingGo** [comment]
@JiabinYang 我的电脑CPU似乎并不支持AVX指令集，请问还有办法在这台电脑上运行paddlepaddle吗，以下是我的CPU的相关信息：
```
➜  桌面 cat /proc/cpuinfo           
processor	: 0
vendor_id	: AuthenticAMD
cpu family	: 16
model		: 6
model name	: AMD Athlon(tm) II P320 Dual-Core Processor
stepping	: 3
microcode	: 0x10000c8
cpu MHz		: 800.000
cache size	: 512 KB
physical id	: 0
siblings	: 2
core id		: 0
cpu cores	: 2
apicid		: 0
initial apicid	: 0
fpu		: yes
fpu_exception	: yes
cpuid level	: 5
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm 3dnowext 3dnow constant_tsc rep_good nopl nonstop_tsc cpuid extd_apicid pni monitor cx16 popcnt lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a 3dnowprefetch osvw ibs skinit wdt nodeid_msr hw_pstate vmmcall npt lbrv svm_lock nrip_save
bugs		: tlb_mmatch apic_c1e fxsave_leak sysret_ss_attrs null_seg amd_e400 spectre_v1 spectre_v2
bogomips	: 4189.44
TLB size	: 1024 4K pages
clflush size	: 64
cache_alignment	: 64
address sizes	: 48 bits physical, 48 bits virtual
power management: ts ttp tm stc 100mhzsteps hwpstate

processor	: 1
vendor_id	: AuthenticAMD
cpu family	: 16
model		: 6
model name	: AMD Athlon(tm) II P320 Dual-Core Processor
stepping	: 3
microcode	: 0x10000c8
cpu MHz		: 800.000
cache size	: 512 KB
physical id	: 0
siblings	: 2
core id		: 1
cpu cores	: 2
apicid		: 1
initial apicid	: 1
fpu		: yes
fpu_exception	: yes
cpuid level	: 5
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm 3dnowext 3dnow constant_tsc rep_good nopl nonstop_tsc cpuid extd_apicid pni monitor cx16 popcnt lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a 3dnowprefetch osvw ibs skinit wdt nodeid_msr hw_pstate vmmcall npt lbrv svm_lock nrip_save
bugs		: tlb_mmatch apic_c1e fxsave_leak sysret_ss_attrs null_seg amd_e400 spectre_v1 spectre_v2
bogomips	: 4189.44
TLB size	: 1024 4K pages
clflush size	: 64
cache_alignment	: 64
address sizes	: 48 bits physical, 48 bits virtual
power management: ts ttp tm stc 100mhzsteps hwpstate

```

**Comment by JiabinYang** [comment]
看起来是的，您可以参见官网[安装文档](http://paddlepaddle.org/documentation/docs/zh/1.2/beginners_guide/install/Tables.html#permalink-5--whl-release)，安装`no-avx`版本的PaddlePaddle，

**Comment by QingGo** [comment]
@JiabinYang 多谢回复
安装了noaux版本的paddlepaddle后，现在已经可以成功导入包运行程序了
