### ISSUE TITLE
fluid报错paddle::framework::GetFetchVariable()

### ISSUE THREAD

**Issue by huashaosmile** [PaddlePaddle/Paddle#14926]
*** Aborted at 1545050659 (unix time) try "date -d @1545050659" if you are using GNU date ***
PC: @                0x0 (unknown)
*** SIGSEGV (@0x0) received by PID 76722 (TID 0x1132de5c0) stack trace: ***
    @     0x7fff7cb97b3d _sigtramp
    @       0x1a1524bc43 paddle::framework::GetFetchVariable()
    @       0x1a151a9116 _ZZN8pybind1112cpp_function10initializeIRPFRN6paddle9framework9LoDTensorERKNS3_5ScopeERKNSt3__112basic_stringIcNS9_11char_traitsIcEENS9_9allocatorIcEEEEmES5_JS8_SH_mEJNS_4nameENS_5scopeENS_7siblingEEEEvOT_PFT0_DpT1_EDpRKT2_ENKUlRNS_6detail13function_callEE_clES11_
    @       0x1a1517e2ea pybind11::cpp_function::dispatcher()
    @        0x107f894e4 PyEval_EvalFrameEx
    @        0x107f838c4 PyEval_EvalCodeEx
    @        0x107f8dc0d fast_function
    @        0x107f88f89 PyEval_EvalFrameEx
    @        0x107f838c4 PyEval_EvalCodeEx
    @        0x107f8dc0d fast_function
    @        0x107f88f89 PyEval_EvalFrameEx
    @        0x107f838c4 PyEval_EvalCodeEx
    @        0x107f8dc0d fast_function
    @        0x107f88f89 PyEval_EvalFrameEx
    @        0x107f838c4 PyEval_EvalCodeEx
    @        0x107f8dc0d fast_function
    @        0x107f88f89 PyEval_EvalFrameEx
    @        0x107f838c4 PyEval_EvalCodeEx
    @        0x107f8dc0d fast_function
    @        0x107f88f89 PyEval_EvalFrameEx
    @        0x107f838c4 PyEval_EvalCodeEx
    @        0x107f83042 PyEval_EvalCode
    @        0x107fb0a7d PyRun_FileExFlags
    @        0x107fb05c0 PyRun_SimpleFileExFlags
    @        0x107fc7452 Py_Main

**Comment by huashaosmile** [comment]
uap_cost = network_conf.UapDnn(
        layer_dims,
        neg_size,
        dataset.feature_dict,
        dataset.label_freq,
        dataset.feature_info_list,
        True
    ).build_dnn_model()
cost = exe.run(main_program, feed=feeder.feed(data), fetch_list=[uap_cost])

**Comment by hjchen2** [comment]
这个看不出来是什么问题，请问一下你跑的是自己的模型么？方便把network_conf.UapDnn的代码发出来看一下么

**Comment by huashaosmile** [comment]
self.executor.run(program.desc, scope, 0, True, True)
paddle.fluid.core.EnforceNotMet: Enforce failed. Expected out_dims[j] == ins[i][j], but received out_dims[j]:3 != ins[i][j]:15.
Input tensors should have the same elements except the specify axis. at [/Users/python2/yangjiabin/PR/Paddle/paddle/fluid/operators/concat_op.cc:52]
PaddlePaddle Call Stacks: 
0         0x1a0e3af9a8p paddle::platform::EnforceNotMet::EnforceNotMet(std::exception_ptr, char const*, int) + 760
1         0x1a0ee17e6ap paddle::operators::ConcatOp::InferShape(paddle::framework::InferShapeContext*) const + 3226
2         0x1a0f1d7dd8p paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&) const + 88
3         0x1a0f1d3f31p paddle::framework::OperatorBase::Run(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&) + 577
4         0x1a0e47d196p paddle::framework::Executor::RunPreparedContext(paddle::framework::ExecutorPrepareContext*, paddle::framework::Scope*, bool, bool, bool) + 390
5         0x1a0e47cbc3p paddle::framework::Executor::Run(paddle::framework::ProgramDesc const&, paddle::framework::Scope*, int, bool, bool) + 163
6         0x1a0e3e3837p void pybind11::cpp_function::initialize<paddle::pybind::pybind11_init()::$_64, void, paddle::framework::Executor&, paddle::framework::ProgramDesc const&, paddle::framework::Scope*, int, bool, bool, pybind11::name, pybind11::is_method, pybind11::sibling>(paddle::pybind::pybind11_init()::$_64&&, void (*)(paddle::framework::Executor&, paddle::framework::ProgramDesc const&, paddle::framework::Scope*, int, bool, bool), pybind11::name const&, pybind11::is_method const&, pybind11::sibling const&)::'lambda'(pybind11::detail::function_call&)::__invoke(pybind11::detail::function_call&) + 135
7         0x1a0e3ba2eap pybind11::cpp_function::dispatcher(_object*, _object*, _object*) + 5690
8          0x1011dc297p PyEval_EvalFrameEx + 22391
9          0x1011d68c4p PyEval_EvalCodeEx + 2164
10         0x1011e0c0dp fast_function + 109
11         0x1011dbf89p PyEval_EvalFrameEx + 21609
12         0x1011d68c4p PyEval_EvalCodeEx + 2164
13         0x1011e0c0dp fast_function + 109
14         0x1011dbf89p PyEval_EvalFrameEx + 21609
15         0x1011d68c4p PyEval_EvalCodeEx + 2164
16         0x1011e0c0dp fast_function + 109
17         0x1011dbf89p PyEval_EvalFrameEx + 21609
18         0x1011d68c4p PyEval_EvalCodeEx + 2164
19         0x1011e0c0dp fast_function + 109
20         0x1011dbf89p PyEval_EvalFrameEx + 21609
21         0x1011d68c4p PyEval_EvalCodeEx + 2164
22         0x1011d6042p PyEval_EvalCode + 34
23         0x101203a7dp PyRun_FileExFlags + 157
24         0x1012035c0p PyRun_SimpleFileExFlags + 816
25         0x10121a452p Py_Main + 3506
26      0x7fff7c9ae085p start + 1
