### ISSUE TITLE
PaddlePaddle会支持Windows下使用GPU吗？

### ISSUE THREAD

**Issue by yeyupiaoling** [PaddlePaddle/Paddle#14939]
目前PaddlePaddle已经支持了Windows的CPU版本，这是令人非常兴奋的一件事。 人的欲望是无止境的，所以我还希望PaddlePaddle能够支持在我Windows上使用GPU，是否有这个计划呢？

**Comment by yeyupiaoling** [comment]
@chengduoZH 这个问题很久了，能答一下？

**Comment by wopeizl** [comment]
@yeyupiaoling 感谢对paddlepaddle的支持，windows的GPU版本预期会在paddlepaddle1.3发布，时间大概在19年2月份某个时间点。

**Comment by yeyupiaoling** [comment]
@wopeizl 好的，感谢回答。

**Comment by yeyupiaoling** [comment]
@wopeizl 会不会支持CUDA 10呢？我的显卡2070只能用CUDA 10。我使用Ubuntu编译CUDA 10的PaddlePaddle能成功。
