### ISSUE TITLE
img_conv 中的filter_size、padding、stride的size

### ISSUE THREAD

**Issue by gaoyiyeah** [PaddlePaddle/Paddle#14938]
img_conv 中的filter_size、padding、stride的size是（H，W）还是（W，H）？

**Comment by yeyupiaoling** [comment]
@gaoyiyeah 
我的理解如下：
1. `filter_size`卷积核的大小
2. `padding`边缘填充大小
3. `stride`卷积的步长

**Comment by gaoyiyeah** [comment]
谢谢，我知道各个参数的含义，但是这些参数是H在前，还是W在前，输入的feature是(H，W)的顺序话，我以为这些参数也是（H，W）的顺序，但感觉又不太对，所以想确认一下顺序？
