### ISSUE TITLE
fluid.io.save_inference_model怎么设置不剪枝呢

### ISSUE THREAD

**Issue by Kayven** [PaddlePaddle/Paddle#14946]
由于fluid.io.save_inference_model默认会剪枝掉没用到的op或var导致报错，试验的时候需要把无用的去掉很麻烦，怎么能设置不裁剪优化呢？

**Comment by Yancey0623** [comment]
这个有具体的场景么？和 #14947 是同一个事情？

**Comment by Yancey0623** [comment]
由于长时间未有更新的消息，先关闭这个issue了，如有更新可随时重新打开。
