### ISSUE TITLE
embedding shape指定：Expected ids_dims[ids_rank - 1] == 1, but received ids_dims[ids_rank - 1]:100 != 1:1

### ISSUE THREAD

**Issue by lvxiaxia** [PaddlePaddle/Paddle#14951]
输入数据格式 
[[1,2,4,0,0,0,....][5,7,9,12,0,0,0,...][0]]   
[ [###100维###] [###1000维###] [##1维##] ]

代码：
![image](https://user-images.githubusercontent.com/18480850/50196766-69aa2900-037f-11e9-8559-b62b6651f7c8.png)

错误：
![image](https://user-images.githubusercontent.com/18480850/50197019-682d3080-0380-11e9-89d6-9a34a3b92320.png)

为啥 fluid.layers.data 的数据的shape直接写成 [100] , [1000] 不行呢，改成[100,1]  [1000,1]就可以pao qi lai跑起来模型，由于需要上线，输入数据shape指定加个1的话 和线上其他模型的输入格式不一致，有什么解决方法？还是只能这样子。。

**Comment by Yancey0623** [comment]
reader的yield部分 还有feed的部分代码也贴下呢？

**Comment by jacquesqiao** [comment]
输入是一个sequence数据么

**Comment by jacquesqiao** [comment]
```python
data(name="left", shape=[1], lod_level=1, dtype='int64')
data(name="right", shape=[1], lod_level=1, dtype='int64')
```
这样试试

**Comment by Yancey0623** [comment]
线下和 @jacquesqiao  @lvxiaxia 沟通了一下，写一下结论：

对于 embedding layer来说，目前支持两种输入：
1. 固定长度的 1维定长的 ids, API类似：
    ```layers.data(name="ids", shape=[1], lod_level=0, dtype="int64")```
1. 变长sequence类 ids, API 类似:
    ```layers.data(name="ids", shape=[1], lod_level=1, dtype="int64")```
    此种方法会将输入的ids转换成一个lod_tensor,支持变长的输入序列（转lodtensor会对性能有些影响 -- from @jacquesqiao ）

@lvxiaxia 这种场景输入定长的高维 Ids, 理论上应该使用方法2， 但由于是定长，所以方法一也可以 work：

``` python
layers.data(name="ids", shape=[100, 1], lod_level=0, dtype="int64")
layers.data(name="ids", shape=[1], lod_level=1, dtype="int64")
```

shape需要是 `[100,1]` 而不是 `[100]` 是因为目前代码中check了最后一维必须为1，和 @jacquesqiao  讨论了一下，高维定长定输入后续会有一个明确定使用方法。

**Comment by lvxiaxia** [comment]
谢谢～
