### ISSUE TITLE
Rename reader_dict

### ISSUE THREAD

**Issue by wangkuiyi** [PaddlePaddle/Paddle#1495]
https://github.com/PaddlePaddle/Paddle/pull/1465/files#diff-84822b81237e20194a78620b1f9e6bd1R143

This concept means a Python dict that maps columns returned by readers to data layers.  But it needs a better name.

**Comment by qingqing01** [comment]
想到的一些：
- feeder_dict
- feeder_map

**Comment by reyoung** [comment]
@qingqing01 @wangkuiyi 这里有一个comments，叫feeding

https://github.com/PaddlePaddle/Paddle/pull/1501#discussion_r104039588
