### ISSUE TITLE
optimizer.minimize(loss)出错

### ISSUE THREAD

**Issue by JinYue2015** [PaddlePaddle/Paddle#14955]
- 版本、环境信息：
    1）PaddlePaddle版本：1.2.0
    2）python：3.5  
    3）ai studio  /  win10
- 训练信息
    1）单机  ps：我在本地运行和在ai studio单机上运行出现的错误是一样的。

- 复现信息：我修改了paddleCV/deeplabv3+/train.py 用作其他数据集的训练，但在定义
```
loss = loss(logit_ret,binary_label,instance_label)
lr = fluid.layers.polynomial_decay(base_lr, total_step, end_learning_rate = 0,power=0.9)
opt = fluid.optimizer.Momentum(lr,momentum=0.9,
                                regularization=fluid.regularizer.L2DecayRegularizer(
                                    regularization_coeff=weight_decay))
opt.minimize(loss)
```
`opt.minimize(loss)`这句话报错。
- 问题描述：
报错信息如下：

> EnforceNotMet                             Traceback (most recent call last)
> <ipython-input-48-ce969b174dc5> in <module>
>     122                                    regularization=fluid.regularizer.L2DecayRegularizer(
>     123                                        regularization_coeff=weight_decay))
> --> 124     _,retv = opt.minimize(loss=loss,startup_program=sp,)
>     125 
>     126 fluid.memory_optimize(
> 
> /opt/conda/envs/py35-paddle1.0.0/lib/python3.5/site-packages/paddle/fluid/optimizer.py in minimize(self, loss, startup_program, parameter_list, no_grad_set)
>     253         """
>     254         params_grads = append_backward(loss, parameter_list, no_grad_set,
> --> 255                                        [error_clip_callback])
>     256 
>     257         params_grads = sorted(params_grads, key=lambda x: x[0].name)
> 
> /opt/conda/envs/py35-paddle1.0.0/lib/python3.5/site-packages/paddle/fluid/backward.py in append_backward(loss, parameter_list, no_grad_set, callbacks)
>     588     _rename_grad_(root_block, fwd_op_num, grad_to_var, {})
>     589 
> --> 590     _append_backward_vars_(root_block, fwd_op_num, grad_to_var, grad_info_map)
>     591 
>     592     program.current_block_idx = current_block_idx
> 
> /opt/conda/envs/py35-paddle1.0.0/lib/python3.5/site-packages/paddle/fluid/backward.py in _append_backward_vars_(block, start_op_idx, grad_to_var, grad_info_map)
>     424         # infer_shape and infer_type
>     425         op_desc.infer_var_type(block.desc)
> --> 426         op_desc.infer_shape(block.desc)
>     427         # ncclInit dones't need to set data_type
>     428         if op_desc.type() == 'ncclInit':
> 
> EnforceNotMet: The input of cast op must be set at [/paddle/paddle/fluid/operators/cast_op.cc:42]
> PaddlePaddle Call Stacks: 
> 0       0x7f1bf9e45426p paddle::platform::EnforceNotMet::EnforceNotMet(std::__exception_ptr::exception_ptr, char const*, int) + 486
> 1       0x7f1bfa5ecb16p paddle::operators::CastOpInferShape::operator()(paddle::framework::InferShapeContext*) const + 566
> 2       0x7f1bfa5ecd63p std::_Function_handler<void (paddle::framework::InferShapeContext*), paddle::framework::details::OpInfoFiller<paddle::operators::CastOpInferShape, (paddle::framework::details::OpInfoFillType)4>::operator()(char const*, paddle::framework::OpInfo*) const::{lambda(paddle::framework::InferShapeContext*)#1}>::_M_invoke(std::_Any_data const&, paddle::framework::InferShapeContext*) + 35
> 3       0x7f1bf9eedd86p paddle::framework::OpDesc::InferShape(paddle::framework::BlockDesc const&) const + 902
> 4       0x7f1bf9e9a755p void pybind11::cpp_function::initialize<pybind11::cpp_function::initialize<void, paddle::framework::OpDesc, paddle::framework::BlockDesc const&, pybind11::name, pybind11::is_method, pybind11::sibling>(void (paddle::framework::OpDesc::*)(paddle::framework::BlockDesc const&) const, pybind11::name const&, pybind11::is_method const&, pybind11::sibling const&)::{lambda(paddle::framework::OpDesc const*, paddle::framework::BlockDesc const&)#1}, void, paddle::framework::OpDesc const*, paddle::framework::BlockDesc const&, pybind11::name, pybind11::is_method, pybind11::sibling>(pybind11::cpp_function::initialize<void, paddle::framework::OpDesc, paddle::framework::BlockDesc const&, pybind11::name, pybind11::is_method, pybind11::sibling>(void (paddle::framework::OpDesc::*)(paddle::framework::BlockDesc const&) const, pybind11::name const&, pybind11::is_method const&, pybind11::sibling const&)::{lambda(paddle::framework::OpDesc const*, paddle::framework::BlockDesc const&)#1}&&, void (*)(paddle::framework::OpDesc const*, paddle::framework::BlockDesc const&), pybind11::name const&, pybind11::is_method const&, pybind11::sibling const&)::{lambda(pybind11::detail::function_call&)#3}::_FUN(pybind11::detail::function_call) + 213
> 5       0x7f1bf9e77be4p pybind11::cpp_function::dispatcher(_object*, _object*, _object*) + 2596
> 6       0x7f1c3aa57199p PyCFunction_Call + 233
> 7       0x7f1c3aaf23f9p PyEval_EvalFrameEx + 33545
> 8       0x7f1c3aaf21d0p PyEval_EvalFrameEx + 32992
> 9       0x7f1c3aaf44b6p
> 10      0x7f1c3aaf15b5p PyEval_EvalFrameEx + 29893
> 11      0x7f1c3aaf44b6p
> 12      0x7f1c3aaf15b5p PyEval_EvalFrameEx + 29893
> 13      0x7f1c3aaf44b6p
> 14      0x7f1c3aaf45a8p PyEval_EvalCodeEx + 72
> 15      0x7f1c3aaf45ebp PyEval_EvalCode + 59
> 16      0x7f1c3aae7c5dp
> 17      0x7f1c3aa57179p PyCFunction_Call + 201
> 18      0x7f1c3aaf1dbep PyEval_EvalFrameEx + 31950
> 19      0x7f1c3aa2b410p _PyGen_Send + 128
> 20      0x7f1c3aaf0953p PyEval_EvalFrameEx + 26723
> 21      0x7f1c3aa2b410p _PyGen_Send + 128
> 22      0x7f1c3aaf0953p PyEval_EvalFrameEx + 26723
> 23      0x7f1c3aa2b410p _PyGen_Send + 128
> 24      0x7f1c3aaf1d60p PyEval_EvalFrameEx + 31856
> 25      0x7f1c3aaf21d0p PyEval_EvalFrameEx + 32992
> 26      0x7f1c3aaf21d0p PyEval_EvalFrameEx + 32992
> 27      0x7f1c3aaf44b6p
> 28      0x7f1c3aaf45a8p PyEval_EvalCodeEx + 72
> 29      0x7f1c3aa33c33p
> 30      0x7f1c3aa0233ap PyObject_Call + 106
> 31      0x7f1c3aaec6eep PyEval_EvalFrameEx + 9726
> 32      0x7f1c3aaf44b6p
> 33      0x7f1c3aaf15b5p PyEval_EvalFrameEx + 29893
> 34      0x7f1c3aa2a6bap
> 35      0x7f1c3aae5af6p
> 36      0x7f1c3aa57179p PyCFunction_Call + 201
> 37      0x7f1c3aaf1dbep PyEval_EvalFrameEx + 31950
> 38      0x7f1c3aaf44b6p
> 39      0x7f1c3aaf15b5p PyEval_EvalFrameEx + 29893
> 40      0x7f1c3aa2a6bap
> 41      0x7f1c3aae5af6p
> 42      0x7f1c3aa57179p PyCFunction_Call + 201
> 43      0x7f1c3aaf1dbep PyEval_EvalFrameEx + 31950
> 44      0x7f1c3aaf44b6p
> 45      0x7f1c3aaf15b5p PyEval_EvalFrameEx + 29893
> 46      0x7f1c3aa2a6bap
> 47      0x7f1c3aae5af6p
> 48      0x7f1c3aa57179p PyCFunction_Call + 201
> 49      0x7f1c3aaf1dbep PyEval_EvalFrameEx + 31950
> 50      0x7f1c3aaf44b6p
> 51      0x7f1c3aaf45a8p PyEval_EvalCodeEx + 72
> 52      0x7f1c3aa33b56p
> 53      0x7f1c3aa0233ap PyObject_Call + 106
> 54      0x7f1c3aaec6eep PyEval_EvalFrameEx + 9726
> 55      0x7f1c3aa2b410p _PyGen_Send + 128
> 56      0x7f1c3aaf1d60p PyEval_EvalFrameEx + 31856
> 57      0x7f1c3aaf21d0p PyEval_EvalFrameEx + 32992
> 58      0x7f1c3aaf44b6p
> 59      0x7f1c3aaf45a8p PyEval_EvalCodeEx + 72
> 60      0x7f1c3aa33c33p
> 61      0x7f1c3aa0233ap PyObject_Call + 106
> 62      0x7f1c3aaec6eep PyEval_EvalFrameEx + 9726
> 63      0x7f1c3aaf44b6p
> 64      0x7f1c3aaf45a8p PyEval_EvalCodeEx + 72
> 65      0x7f1c3aa33b56p
> 66      0x7f1c3aa0233ap PyObject_Call + 106
> 67      0x7f1c3ab67ccap
> 68      0x7f1c3aa0233ap PyObject_Call + 106
> 69      0x7f1c3aaee4c5p PyEval_EvalFrameEx + 17365
> 70      0x7f1c3aaf44b6p
> 71      0x7f1c3aaf45a8p PyEval_EvalCodeEx + 72
> 72      0x7f1c3aa33b56p
> 73      0x7f1c3aa0233ap PyObject_Call + 106
> 74      0x7f1c3aaec6eep PyEval_EvalFrameEx + 9726
> 75      0x7f1c3aaf21d0p PyEval_EvalFrameEx + 32992
> 76      0x7f1c3aaf21d0p PyEval_EvalFrameEx + 32992
> 77      0x7f1c3aaf21d0p PyEval_EvalFrameEx + 32992
> 78      0x7f1c3aaf21d0p PyEval_EvalFrameEx + 32992
> 79      0x7f1c3aaf21d0p PyEval_EvalFrameEx + 32992
> 80      0x7f1c3aaf44b6p
> 81      0x7f1c3aaf15b5p PyEval_EvalFrameEx + 29893
> 82      0x7f1c3aaf44b6p
> 83      0x7f1c3aaf45a8p PyEval_EvalCodeEx + 72
> 84      0x7f1c3aaf45ebp PyEval_EvalCode + 59
> 85      0x7f1c3aae7c5dp
> 86      0x7f1c3aa57179p PyCFunction_Call + 201
> 87      0x7f1c3aaf1dbep PyEval_EvalFrameEx + 31950
> 88      0x7f1c3aaf44b6p
> 89      0x7f1c3aaf15b5p PyEval_EvalFrameEx + 29893
> 90      0x7f1c3aaf44b6p
> 91      0x7f1c3aaf45a8p PyEval_EvalCodeEx + 72
> 92      0x7f1c3aa33b56p
> 93      0x7f1c3aa0233ap PyObject_Call + 106
> 94      0x7f1c3ab40ba1p
> 95      0x7f1c3ab414a5p Py_Main + 1493
> 96            0x400b54p main + 356
> 97      0x7f1c39ab5830p __libc_start_main + 240
> 98            0x400c01p

**Comment by WangTaoSpace** [comment]
> * 版本、环境信息：
>      1）PaddlePaddle版本：1.2.0
>      2）python：3.5
>   3）ai studio  /  win10
> * 训练信息
>      1）单机  ps：我在本地运行和在ai studio单机上运行出现的错误是一样的。
> * 复现信息：我修改了paddleCV/deeplabv3+/train.py 用作其他数据集的训练，但在定义
> 
> ```
> loss = loss(logit_ret,binary_label,instance_label)
> lr = fluid.layers.polynomial_decay(base_lr, total_step, end_learning_rate = 0,power=0.9)
> opt = fluid.optimizer.Momentum(lr,momentum=0.9,
>                                 regularization=fluid.regularizer.L2DecayRegularizer(
>                                     regularization_coeff=weight_decay))
> opt.minimize(loss)
> ```
> 
> `opt.minimize(loss)`这句话报错。
> 
> * 问题描述：
>   报错信息如下：
> 
> > EnforceNotMet                             Traceback (most recent call last)
> >  in 
> > 122                                    regularization=fluid.regularizer.L2DecayRegularizer(
> > 123                                        regularization_coeff=weight_decay))
> > --> 124     _,retv = opt.minimize(loss=loss,startup_program=sp,)
> > 125
> > 126 fluid.memory_optimize(
> > /opt/conda/envs/py35-paddle1.0.0/lib/python3.5/site-packages/paddle/fluid/optimizer.py in minimize(self, loss, startup_program, parameter_list, no_grad_set)
> > 253         """
> > 254         params_grads = append_backward(loss, parameter_list, no_grad_set,
> > --> 255                                        [error_clip_callback])
> > 256
> > 257         params_grads = sorted(params_grads, key=lambda x: x[0].name)
> > /opt/conda/envs/py35-paddle1.0.0/lib/python3.5/site-packages/paddle/fluid/backward.py in append_backward(loss, parameter_list, no_grad_set, callbacks)
> > 588     _rename_grad_(root_block, fwd_op_num, grad_to_var, {})
> > 589
> > --> 590     _append_backward_vars_(root_block, fwd_op_num, grad_to_var, grad_info_map)
> > 591
> > 592     program.current_block_idx = current_block_idx
> > /opt/conda/envs/py35-paddle1.0.0/lib/python3.5/site-packages/paddle/fluid/backward.py in _append_backward_vars_(block, start_op_idx, grad_to_var, grad_info_map)
> > 424         # infer_shape and infer_type
> > 425         op_desc.infer_var_type(block.desc)
> > --> 426         op_desc.infer_shape(block.desc)
> > 427         # ncclInit dones't need to set data_type
> > 428         if op_desc.type() == 'ncclInit':
> > EnforceNotMet: The input of cast op must be set at [/paddle/paddle/fluid/operators/cast_op.cc:42]
> > PaddlePaddle Call Stacks:
> > 0       0x7f1bf9e45426p paddle::platform::EnforceNotMet::EnforceNotMet(std::__exception_ptr::exception_ptr, char const*, int) + 486
> > 1       0x7f1bfa5ecb16p paddle::operators::CastOpInferShape::operator()(paddle::framework::InferShapeContext*) const + 566
> > 2       0x7f1bfa5ecd63p std::_Function_handler<void (paddle::framework::InferShapeContext*), paddle::framework::details::OpInfoFiller<paddle::operators::CastOpInferShape, (paddle::framework::details::OpInfoFillType)4>::operator()(char const*, paddle::framework::OpInfo*) const::{lambda(paddle::framework::InferShapeContext*)#1}>::_M_invoke(std::_Any_data const&, paddle::framework::InferShapeContext*) + 35
> > 3       0x7f1bf9eedd86p paddle::framework::OpDesc::InferShape(paddle::framework::BlockDesc const&) const + 902
> > 4       0x7f1bf9e9a755p void pybind11::cpp_function::initialize<pybind11::cpp_function::initialize<void, paddle::framework::OpDesc, paddle::framework::BlockDesc const&, pybind11::name, pybind11::is_method, pybind11::sibling>(void (paddle::framework::OpDesc::_)(paddle::framework::BlockDesc const&) const, pybind11::name const&, pybind11::is_method const&, pybind11::sibling const&)::{lambda(paddle::framework::OpDesc const_, paddle::framework::BlockDesc const&)#1}, void, paddle::framework::OpDesc const*, paddle::framework::BlockDesc const&, pybind11::name, pybind11::is_method, pybind11::sibling>(pybind11::cpp_function::initialize<void, paddle::framework::OpDesc, paddle::framework::BlockDesc const&, pybind11::name, pybind11::is_method, pybind11::sibling>(void (paddle::framework::OpDesc::_)(paddle::framework::BlockDesc const&) const, pybind11::name const&, pybind11::is_method const&, pybind11::sibling const&)::{lambda(paddle::framework::OpDesc const_, paddle::framework::BlockDesc const&)#1}&&, void (_)(paddle::framework::OpDesc const_, paddle::framework::BlockDesc const&), pybind11::name const&, pybind11::is_method const&, pybind11::sibling const&)::{lambda(pybind11::detail::function_call&)#3}::_FUN(pybind11::detail::function_call) + 213
> > 5       0x7f1bf9e77be4p pybind11::cpp_function::dispatcher(_object*, _object*, _object*) + 2596
> > 6       0x7f1c3aa57199p PyCFunction_Call + 233
> > 7       0x7f1c3aaf23f9p PyEval_EvalFrameEx + 33545
> > 8       0x7f1c3aaf21d0p PyEval_EvalFrameEx + 32992
> > 9       0x7f1c3aaf44b6p
> > 10      0x7f1c3aaf15b5p PyEval_EvalFrameEx + 29893
> > 11      0x7f1c3aaf44b6p
> > 12      0x7f1c3aaf15b5p PyEval_EvalFrameEx + 29893
> > 13      0x7f1c3aaf44b6p
> > 14      0x7f1c3aaf45a8p PyEval_EvalCodeEx + 72
> > 15      0x7f1c3aaf45ebp PyEval_EvalCode + 59
> > 16      0x7f1c3aae7c5dp
> > 17      0x7f1c3aa57179p PyCFunction_Call + 201
> > 18      0x7f1c3aaf1dbep PyEval_EvalFrameEx + 31950
> > 19      0x7f1c3aa2b410p _PyGen_Send + 128
> > 20      0x7f1c3aaf0953p PyEval_EvalFrameEx + 26723
> > 21      0x7f1c3aa2b410p _PyGen_Send + 128
> > 22      0x7f1c3aaf0953p PyEval_EvalFrameEx + 26723
> > 23      0x7f1c3aa2b410p _PyGen_Send + 128
> > 24      0x7f1c3aaf1d60p PyEval_EvalFrameEx + 31856
> > 25      0x7f1c3aaf21d0p PyEval_EvalFrameEx + 32992
> > 26      0x7f1c3aaf21d0p PyEval_EvalFrameEx + 32992
> > 27      0x7f1c3aaf44b6p
> > 28      0x7f1c3aaf45a8p PyEval_EvalCodeEx + 72
> > 29      0x7f1c3aa33c33p
> > 30      0x7f1c3aa0233ap PyObject_Call + 106
> > 31      0x7f1c3aaec6eep PyEval_EvalFrameEx + 9726
> > 32      0x7f1c3aaf44b6p
> > 33      0x7f1c3aaf15b5p PyEval_EvalFrameEx + 29893
> > 34      0x7f1c3aa2a6bap
> > 35      0x7f1c3aae5af6p
> > 36      0x7f1c3aa57179p PyCFunction_Call + 201
> > 37      0x7f1c3aaf1dbep PyEval_EvalFrameEx + 31950
> > 38      0x7f1c3aaf44b6p
> > 39      0x7f1c3aaf15b5p PyEval_EvalFrameEx + 29893
> > 40      0x7f1c3aa2a6bap
> > 41      0x7f1c3aae5af6p
> > 42      0x7f1c3aa57179p PyCFunction_Call + 201
> > 43      0x7f1c3aaf1dbep PyEval_EvalFrameEx + 31950
> > 44      0x7f1c3aaf44b6p
> > 45      0x7f1c3aaf15b5p PyEval_EvalFrameEx + 29893
> > 46      0x7f1c3aa2a6bap
> > 47      0x7f1c3aae5af6p
> > 48      0x7f1c3aa57179p PyCFunction_Call + 201
> > 49      0x7f1c3aaf1dbep PyEval_EvalFrameEx + 31950
> > 50      0x7f1c3aaf44b6p
> > 51      0x7f1c3aaf45a8p PyEval_EvalCodeEx + 72
> > 52      0x7f1c3aa33b56p
> > 53      0x7f1c3aa0233ap PyObject_Call + 106
> > 54      0x7f1c3aaec6eep PyEval_EvalFrameEx + 9726
> > 55      0x7f1c3aa2b410p _PyGen_Send + 128
> > 56      0x7f1c3aaf1d60p PyEval_EvalFrameEx + 31856
> > 57      0x7f1c3aaf21d0p PyEval_EvalFrameEx + 32992
> > 58      0x7f1c3aaf44b6p
> > 59      0x7f1c3aaf45a8p PyEval_EvalCodeEx + 72
> > 60      0x7f1c3aa33c33p
> > 61      0x7f1c3aa0233ap PyObject_Call + 106
> > 62      0x7f1c3aaec6eep PyEval_EvalFrameEx + 9726
> > 63      0x7f1c3aaf44b6p
> > 64      0x7f1c3aaf45a8p PyEval_EvalCodeEx + 72
> > 65      0x7f1c3aa33b56p
> > 66      0x7f1c3aa0233ap PyObject_Call + 106
> > 67      0x7f1c3ab67ccap
> > 68      0x7f1c3aa0233ap PyObject_Call + 106
> > 69      0x7f1c3aaee4c5p PyEval_EvalFrameEx + 17365
> > 70      0x7f1c3aaf44b6p
> > 71      0x7f1c3aaf45a8p PyEval_EvalCodeEx + 72
> > 72      0x7f1c3aa33b56p
> > 73      0x7f1c3aa0233ap PyObject_Call + 106
> > 74      0x7f1c3aaec6eep PyEval_EvalFrameEx + 9726
> > 75      0x7f1c3aaf21d0p PyEval_EvalFrameEx + 32992
> > 76      0x7f1c3aaf21d0p PyEval_EvalFrameEx + 32992
> > 77      0x7f1c3aaf21d0p PyEval_EvalFrameEx + 32992
> > 78      0x7f1c3aaf21d0p PyEval_EvalFrameEx + 32992
> > 79      0x7f1c3aaf21d0p PyEval_EvalFrameEx + 32992
> > 80      0x7f1c3aaf44b6p
> > 81      0x7f1c3aaf15b5p PyEval_EvalFrameEx + 29893
> > 82      0x7f1c3aaf44b6p
> > 83      0x7f1c3aaf45a8p PyEval_EvalCodeEx + 72
> > 84      0x7f1c3aaf45ebp PyEval_EvalCode + 59
> > 85      0x7f1c3aae7c5dp
> > 86      0x7f1c3aa57179p PyCFunction_Call + 201
> > 87      0x7f1c3aaf1dbep PyEval_EvalFrameEx + 31950
> > 88      0x7f1c3aaf44b6p
> > 89      0x7f1c3aaf15b5p PyEval_EvalFrameEx + 29893
> > 90      0x7f1c3aaf44b6p
> > 91      0x7f1c3aaf45a8p PyEval_EvalCodeEx + 72
> > 92      0x7f1c3aa33b56p
> > 93      0x7f1c3aa0233ap PyObject_Call + 106
> > 94      0x7f1c3ab40ba1p
> > 95      0x7f1c3ab414a5p Py_Main + 1493
> > 96            0x400b54p main + 356
> > 97      0x7f1c39ab5830p __libc_start_main + 240
> > 98            0x400c01p

我也遇到一样的错误，但是我本地GPU能跑，ai_studio不能跑，老哥最后如何解决的？
