### ISSUE TITLE
运行官网房价模型报错

### ISSUE THREAD

**Issue by lucywsq** [PaddlePaddle/Paddle#14965]
具体报错信息如下，显示不能连接到proxy，已经排除是官网的数据集网址问题，想麻烦看下是哪里出了问题
如下是报错截图
![2118abc9b80375561efa7e1625a1b332](https://user-images.githubusercontent.com/38712162/50219282-b1ee3900-03c9-11e9-9b53-0ba44577f4e7.JPG)
如下是具体配置信息
![fb12fad335672f7956489721f14b642b](https://user-images.githubusercontent.com/38712162/50219318-cdf1da80-03c9-11e9-8f4e-52b295de9f3f.JPG)

**Comment by wopeizl** [comment]
看起来像是proxy的问题，可以这样查一下
echo $http_proxy
echo $https_proxy

**Comment by Yancey0623** [comment]
代理工作是否正常呢, 可以试下：```curl http://172.19.57.45:3128```

**Comment by yeyupiaoling** [comment]
@lucywsq 这个是Windows下的docker通病，应该是Windows虚拟机网络设置有问题。我建议之间在Windows下安装paddlepaddle，这样会方便很多。

**Comment by Yancey0623** [comment]
感谢 @yeyupiaoling , 先关闭这个issue了，问题若有更新可随时打开。
