### ISSUE TITLE
cuDNN6支持使用fluid1.2吗

### ISSUE THREAD

**Issue by zhengzhe97** [PaddlePaddle/Paddle#14967]

**Comment by Yancey0623** [comment]
需要自己从源码编译一下，目前paddle发布的版本是 cuda8.0+cudnn5, cuda8+cudnn7, cuda9+cudnn7.

源码编译的方法可以参考：http://paddlepaddle.org/documentation/docs/zh/1.2/beginners_guide/install/compile/compile_Ubuntu.html

**Comment by zhengzhe97** [comment]
@Yancey1989 
![l rtrt 3eaua e2 6x gwp](https://user-images.githubusercontent.com/26462054/50258995-329a4d00-043d-11e9-98c6-eb3f81bcf578.png)
我使用pip安装的paddlepaddle，在运行以上代码是没有出错，是不是意味着我安装是成功的？

**Comment by Yancey0623** [comment]
如果`use_gpu=True`能够正常运行，说明安装是没问题的。
