### ISSUE TITLE
fluid 中是否存在类似tf.shape来获取dynamic shape 的api

### ISSUE THREAD

**Issue by zhouksh** [PaddlePaddle/Paddle#14976]
譬如如何获取batch中的最长序列长度用来定义网络？

**Comment by luotao1** [comment]
shape接口请参考 http://www.paddlepaddle.org/documentation/docs/zh/1.2/api_cn/layers_cn.html#shape

**Comment by guoshengCS** [comment]
用户希望使用batch中的最长序列长度进行position encoding，已和用户沟通解决。
如果希望获取LoDTensor里的序列长度，可以先行加一个额外的data layer记录每个序列的长度，作为输入feed进去。只考虑position encoding的话也可以不用管batch中的最长序列长度，参考Transformer中的做法定义一个embedding layer，大小为最大可能的序列长度，然后使用python代码计算好position encoding后作为embedding 的参数初始值设置进去。
https://github.com/PaddlePaddle/models/blob/develop/fluid/PaddleNLP/neural_machine_translation/transformer/model.py#L228
 https://github.com/PaddlePaddle/models/blob/develop/fluid/PaddleNLP/neural_machine_translation/transformer/model.py#L10
