### ISSUE TITLE
deeplabv3 我使用cpu运行代码时没问题，在使用GPU出错

### ISSUE THREAD

**Issue by zhengzhe97** [PaddlePaddle/Paddle#14981]
train.py:35: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  a = a[slices]
*** Aborted at 1545288441 (unix time) try "date -d @1545288441" if you are using GNU date ***
PC: @                0x0 (unknown)
*** SIGSEGV (@0x0) received by PID 12022 (TID 0x7f6e9b7fe700) from PID 0; stack trace: ***
    @     0x7f72f426f330 (unknown)
    @                0x0 (unknown)
Segmentation fault (core dumped)

对于所给的报错不是很理解

**Comment by luotao1** [comment]
请给出更详细一点的信息，包括网络结构，使用paddle版本等。

**Comment by zhengzhe97** [comment]
@luotao1 paddlepaddle1.2  模型库里的deeplabv3+

*** Aborted at 1545288441 (unix time) try "date -d @1545288441" if you are using GNU date ***
PC: @ 0x0 (unknown)
*** SIGSEGV (@0x0) received by PID 12022 (TID 0x7f6e9b7fe700) from PID 0; stack trace: ***
@ 0x7f72f426f330 (unknown)
@ 0x0 (unknown)
Segmentation fault (core dumped

前面的warning可以理解，但是后面的错误不是很懂

**Comment by luotao1** [comment]
@cjld 能帮忙看一下么？

**Comment by qingqing01** [comment]
GPU的错误信息有点少，可以运行以下命令，看看有没有更详细的错误信息，提供下、同时提供下GPU的信息、环境信息。

```
export GLOG_v=3
export GLOG_logtostderr=1
```

**Comment by liyingying05** [comment]
<img width="1274" alt="image" src="https://user-images.githubusercontent.com/39268034/52028678-d1d95680-254a-11e9-8a03-8a26760d9515.png">
我也遇到类似这样的错误  在k40的机器上跑没有问题 在p40的机器上单卡跑也没有问题 但是开多卡的话就报错这个错误 麻烦看一下这个信息能反映出什么吗？ @qingqing01
