### ISSUE TITLE
clone的使用，及模型库里train.py中test_prog = test_prog.clone(for_test=True)的解释

### ISSUE THREAD

**Issue by ghost** [PaddlePaddle/Paddle#14984]
![p1](https://user-images.githubusercontent.com/29684008/50285516-60ac7b00-0497-11e9-9158-86cdfadac285.png)
![p2](https://user-images.githubusercontent.com/29684008/50285517-64400200-0497-11e9-839d-cc4f45e58905.png)
问题一：上两图是API中fluid.Program下Clone方法的代码示例，第一张图好理解，把train_program的参数给test_program共享，第二张图没法理解，请问test_program是怎么拿到train_program的参数的呢？而且“#不使用测试阶段的startup_program”是不是想表达“#不使用训练阶段的startup_program”？
![p3](https://user-images.githubusercontent.com/29684008/50285712-0b249e00-0498-11e9-860a-5bbbda44d7d6.png)
问题二：这段代码是模型库（https://github.com/PaddlePaddle/models/tree/develop/fluid/PaddleCV/image_classification）中train.py文件的内容，请问test_prog = test_prog.clone(for_test=True)是什么意思？我在快速入门中看到的都是克隆main_program，不是克隆自己，再赋值给自己。

感谢。

**Comment by luotao1** [comment]
- 问题1:
> 第二张图没法理解，请问test_program是怎么拿到train_program的参数的呢

`train_program`, `test_program`都是`fluid.Program()`，因此都在一个`program_desc`里面。

> “#不使用测试阶段的startup_program”是不是想表达“#不使用训练阶段的startup_program”？

不是的。如果使用测试阶段自己的startup_program, 就无法共享`fluid.Program()`了。

- 问题2:
> test_prog = test_prog.clone(for_test=True)是什么意思？我在快速入门中看到的都是克隆main_program，不是克隆自己，再赋值给自己

`build_program`里的`is_train=False`，并没有将program_desc里op的`is_test`属性改成false。它只是不加一些训练需要的参数。
https://github.com/PaddlePaddle/models/blob/develop/fluid/PaddleCV/image_classification/train.py#L178-L187

因此，必须使用`clone(for_test=True)`来将program_desc里op的`is_test`属性改成false。

**Comment by ghost** [comment]
对于问题一，我觉得可能是你们的勘误：
![p4](https://user-images.githubusercontent.com/29684008/50333206-842b0080-053f-11e9-9afd-3eb9b65116f3.png)
标注的地方我认为是startup_program，而不应该是fluid.Program()。
这就是为什么问题二中train_prog和test_prog在build的时候传的是同一个初始化，即startup_prog，这样才能参数共享。

**Comment by luotao1** [comment]
能否告知下问题一的代码来源，可以贴下url么？

**Comment by ghost** [comment]
http://www.paddlepaddle.org/documentation/docs/zh/1.2/api_cn/fluid_cn.html#permalink-23-program

fluid.Program类下的clone方法

**Comment by luotao1** [comment]
> 标注的地方我认为是startup_program，而不应该是fluid.Program()

`start_program=fluid.Program()`, 两者是一致的。

startup_program存放是参数初始化的操作。main_program存放的是模型网络结构。测试和训练这里是共享参数的，所以需要用训练阶段的startup_program,不能用测试阶段自己的startup_program。
