### ISSUE TITLE
C-API 加在python训练的模型后出core

### ISSUE THREAD

**Issue by haoshengxuan** [PaddlePaddle/Paddle#14985]
python 训练后save的代码如下：
![bcea20ecd7db20a27505a5b5665bfa30](https://user-images.githubusercontent.com/8426999/50286492-7c655080-049a-11e9-9c6b-e83151d69c58.PNG)

C++ 调用paddle_inference_api的代码如下：
![image](https://user-images.githubusercontent.com/8426999/50286139-6acf7900-0499-11e9-92d5-85eaf6c07781.png)

出core的gdb调试信息如下：
![image](https://user-images.githubusercontent.com/8426999/50286165-8044a300-0499-11e9-8db5-8047e4b574db.png)

-预测信息
1）C++预测：请您提供预测库安装包的版本信息，及其中的version.txt文件
GIT COMMIT ID: a9aebfa7cff3ca645eaebf3c79dcd06898accaa8
WITH_MKL: ON
WITH_MKLDNN: ON
WITH_GPU: OFF

预测库来源：官网下载

**Comment by luotao1** [comment]
python存储的预测文件是`__model__`和`__params__`吧？
这样C++代码里需要
```
model_dir.prog_file =  "xxx/__model__";
model_dir.param_file = "xxx/__params__";
```

**Comment by haoshengxuan** [comment]
> python存储的预测文件是`__model__`和`__params__`吧？
> 这样C++代码里需要
> 
> ```
> model_dir.prog_file =  "xxx/__model__";
> model_dir.param_file = "xxx/__params__";
> ```

问题已解决。非常感谢。
