### ISSUE TITLE
paddle 是否有提供 python3 环境的 docker 镜像？

### ISSUE THREAD

**Issue by Yancey0623** [PaddlePaddle/Paddle#14990]
问题来自用户群
解答：暂时没有，但有提供python3的wheel包，可以直接在python3但环境下使用pip install 进行安装。

**Comment by Yancey1989** [comment]
暂时没有，但有提供python3的wheel包，可以直接在python3但环境下使用`pip install` 进行安装。

**Comment by JiabinYang** [comment]
已经有了latest-dev的镜像是有的`docker run --name paddle-test -v $PWD:/paddle --network=host -it hub.baidubce.com/paddlepaddle/paddle:latest-dev /bin/bash`
