### ISSUE TITLE
paddle 1.2版本rank_loss文档错误

### ISSUE THREAD

**Issue by 333caowei** [PaddlePaddle/Paddle#14999]
http://www.paddlepaddle.org/documentation/docs/zh/1.2/api_cn/layers_cn.html
rank_loss的代码示例是错的，fluid.layers.affine_grid不是这个api的代码示例

**Comment by chengduoZH** [comment]
收到，非常感谢，已通过相关同学修正。
英文文档是正常的。

**Comment by tink2123** [comment]
@333caowei 收到反馈，中文文档已经修复，非常感谢您的关注和使用。
