### ISSUE TITLE
Capi与python API预测结果不一致

### ISSUE THREAD

**Issue by haoshengxuan** [PaddlePaddle/Paddle#14995]
python 训练后save的代码如下：
![bcea20ecd7db20a27505a5b5665bfa30](https://user-images.githubusercontent.com/8426999/50332455-20073d00-053d-11e9-8393-84f90ade1e33.PNG)

python 调用API的代码如下：
![bec43a3a449df7a4045da830a5b8682c](https://user-images.githubusercontent.com/8426999/50332423-09f97c80-053d-11e9-9055-bb071a35d4bf.PNG)

C++ 调用paddle_inference_api的代码如下：
![image](https://user-images.githubusercontent.com/8426999/50332506-47f6a080-053d-11e9-8f98-94f7947605e5.png)
![image](https://user-images.githubusercontent.com/8426999/50332537-5ba20700-053d-11e9-9419-db805a66c86b.png)

观察结果看预测结果明显不一致。

预测信息
1）C++预测：请您提供预测库安装包的版本信息，及其中的version.txt文件
GIT COMMIT ID: a9aebfa7cff3ca645eaebf3c79dcd06898accaa8
WITH_MKL: ON
WITH_MKLDNN: ON
WITH_GPU: OFF

python 版本是0.14.0的。

**Comment by Superjomn** [comment]
你预测output是activation的输出么，比如 softmax 或者 tanh 等，如果是，中间有个bug：

- 尝试在 output 后面加个 scale op，把scale的输出作为新的output 获取

**Comment by haoshengxuan** [comment]
> 你预测output是activation的输出么，比如 softmax 或者 tanh 等，如果是，中间有个bug：
> 
> * 尝试在 output 后面加个 scale op，把scale的输出作为新的output 获取

output是softmax activation的输出。 scale op这块我没有找到相关的API。请问具体应该如何操作呢。或者相关的API文档或者样例链接能否提供下。

**Comment by Superjomn** [comment]
```python
output1 = layers.scale(old_output, 1.)
save_inference_model(xxx, fetch_list=[output1])
```

很抱歉，这个bug我们在修，需要重构修改量比较大，所以晚一些发版放出来

**Comment by haoshengxuan** [comment]
> ```python
> output1 = layers.scale(old_output, 1)
> save_inference_model(xxx, fetch_list=[output1])
> ```
> 
> 很抱歉，这个bug我们在修，需要重构修改量比较大，所以晚一些发版放出来

![aaa](https://user-images.githubusercontent.com/8426999/50340786-4f2aa800-0557-11e9-994f-61e0cde5bb72.png)
output按scale处理后再save依然不一致，python api预测结果是两个0~1的浮点数。而capi预测结果都是0或1，且与python按照0.5上下取整的结果完全不一样。

**Comment by Superjomn** [comment]
这个问题解决了吗？
