### ISSUE TITLE
eval.py代码有误

### ISSUE THREAD

**Issue by ghost** [PaddlePaddle/Paddle#15005]
![error](https://user-images.githubusercontent.com/29684008/50381667-b6676a00-06c7-11e9-9014-dabca22ec300.png)

https://github.com/PaddlePaddle/models/blob/develop/fluid/PaddleCV/image_classification/eval.py

应该是reader.val()，不传“”空字符串进去。

**Comment by shippingwang** [comment]
@skjasonz  没错，这里是val_list的路径。已修复，感谢。
