### ISSUE TITLE
关于使用paddle进行车牌识别的问题

### ISSUE THREAD

**Issue by Ouyangtengfang** [PaddlePaddle/Paddle#15002]
你好！我打算用ｐａｄｄｌｅ做车牌识别，我不知道是该使用ＳＳＤ还是ＯＣＲ？　如果是使用ＯＣＲ，我参考过你们的例子：https://github.com/PaddlePaddle/models/tree/develop/fluid/PaddleCV/ocr_recognition，里面只有英文字母的训练数据，中国的车牌除了英文，还有中文和数字，请问哪里可以下载到相应的数据集用来训练？　谢谢！

**Comment by chengduoZH** [comment]
@Ouyangtengfang 目前Paddle这边没有提供，您可以在网上找一下，应该是还设有的。

**Comment by wanghaoshuang** [comment]
车牌识别建议使用OCR, 因版权问题暂时无法对外开放中文数据，需要您从其他渠道收集数据。

**Comment by Ouyangtengfang** [comment]
好的，我用ＯＣＲ模型试试，非常感谢你们的及时回复，谢谢！
