### ISSUE TITLE
求问为什么Paddle tensorrt 性能比原生支持caffe模型的差？

### ISSUE THREAD

**Issue by procr** [PaddlePaddle/Paddle#15016]
在V100的机器实测。
我先用caffe的模型用原生trt接口测试，再用caffe2fluid工具转换成paddle模型用paddle trt测试。
精度都是float
[1, 3, 224, 224], 一次inference。
ResNet50，paddle trt:  2.959ms，caffe trt: 2.146
VGG19, 3.1ms vs 2.8ms
AlexNet, 1.3ms vs 0.9ms
MobileNetV2, 1.7ms vs 1.0ms

**Comment by Superjomn** [comment]
两者机制不一样，paddle是用子图的方式，中间需要一个映射过程，目前一些经典模型上需要的映射都包含了，但肯定有模型没包含，需要按模型来看。

**Comment by procr** [comment]
上面列举的几个模型，都能在Tensorrt执行。
“有模型没有包含”，是指有些子图的op没有办法被tensorrts所优化么？

**Comment by procr** [comment]
顺便请问一下，是否现在有哪个模型能够使paddle trt的性能和原生的trt性能相一致么？

**Comment by Superjomn** [comment]
http://www.paddlepaddle.org/documentation/docs/zh/1.2/advanced_usage/deploy/inference/paddle_gpu_benchmark.html

这些模型都有。

fluid op(s) -> tensorrt op(s) 的映射过程是需要手写rule 的，rule包含的能映射过去，不包含的不能映射过去，目前我们重点看了上面列表里的模型，现在的rule理论上能覆盖大部分图像模型，但无法保证所有模型。

**Comment by procr** [comment]
目前再看的就是ResNet50这个模型，根据你上面买的链接，这个模型应该是被paddle tensorrt所支持的。

不过我们测下来，
在V100，paddle trt: 2.959ms，caffe trt: 2.146ms
在T4，paddle trt: 6.949ms，caffe trt: 2.800ms
差别有一点大。
请问这个是什么原因？

**Comment by Superjomn** [comment]
我们对比的方式是，找到 caffe模型，测试 tensorrt原生；将 caffe模型转成fluid格式，用paddle-trt 测试；两者时间是对齐的。 

不确定你们的测试模型结构是否相同。

部分测试结果：

![image](https://user-images.githubusercontent.com/328693/50766247-72718900-12b3-11e9-91d2-885654ac6ab2.png)

**Comment by procr** [comment]
先确定一下，这个模型是在T4上测试的对么？
用caffe原生的模型测试tensorrt float性能。
然后使用该工具：https://github.com/PaddlePaddle/models/tree/develop/fluid/PaddleCV/caffe2fluid
将caffe模型转换成fluid模型。
再将fluid模型在paddle tensorrt以及paddle里面分别测试。

![image](https://user-images.githubusercontent.com/5010880/50806893-8d83dd80-1333-11e9-88f4-baf54ef5e425.png)
上表列出了ResNet50测试的结果，我们测的和你们测的似乎相差比较大。（包括vgg19和googlenet差别也很大）
能否分享你们测试用的上述三个模型（resnet50 vgg19 googlenet）的caffe prototxt文件以方便复现你们的实验，感谢：）

**Comment by Superjomn** [comment]
caffe 和 paddle 对应的model有么，有的话可以提供下 @NHZlX

**Comment by NHZlX** [comment]
@procr  我们是在p4上测试的结果。TensorRT原生你是用的` IProfiler`来测试的执行时间么, 或者说用的是TensorRT-4.0.1.6/samples/sampleGoogleNet/sampleGoogleNet.cpp 来进行的测试？

**Comment by procr** [comment]
@NHZlX 我用的是tensorrt:18.11-py3，TensorRT原生的docker镜像。
里面有一个默认的指令giexec（参考：https://docs.nvidia.com/deeplearning/sdk/tensorrt-archived/tensorrt_210/tensorrt-user-guide/index.html）
测试指令如下
giexec --deploy=ResNet50.prototxt --output=prob --workspace=1024 --batch=1

**Comment by NHZlX** [comment]
@procr 
看了一下 TensorRT-4.0.1.6/samples/trtexec/trtexec.cpp 的profiler实现，这个和paddle-trt的统计的区别在于，paddle-trt会多出一次cpu->gpu 的输入copy，以及一次gpu->cpu 的输出copy。在V100 下的时间看起来还是合理的。在T4下的结果感觉有点意外。

**Comment by NHZlX** [comment]
@procr 目前手里没有T4机器，最近看看能不能申请到，然后测试一下。

**Comment by procr** [comment]
嗨~@NHZlX 这个后来有结果了么？
