### ISSUE TITLE
fluid pairwise使用rank_loss训练，loss在input数据buf切换时候会上升

### ISSUE THREAD

**Issue by 333caowei** [PaddlePaddle/Paddle#15036]
训练pairwise网络，loss function使用的是rank_loss，最后画图loss变化趋势发现loss会定期上升，如下图：
<img width="765" alt="image" src="https://user-images.githubusercontent.com/4569055/50414613-8fd53a80-0851-11e9-9a10-8cd7f5e6a2af.png">
经过排查，发现每一个loss的上升的时间点都是input数据buff切换的时候，即：
```
 train_reader = paddle.batch(
         paddle.reader.shuffle(
             reader.train_reader(
                 train_data_dir,
                 ), buf_size=BATCH_SIZE*500),
         batch_size=BATCH_SIZE)
```
例如上述buf_size=BATCH_SIZE*500，即在batch为500的倍数时候，loss就会上升：
![image](https://user-images.githubusercontent.com/4569055/50414695-f35f6800-0851-11e9-8b3c-d2765a8f1b62.png)

通过调整buf_size的大小，loss上升的点也会随之变化，请问这是什么原因？fluid1.1版本

**Comment by 333caowei** [comment]
已解决

**Comment by cheradam** [comment]
@333caowei 求解决办法

**Comment by 333caowei** [comment]
数据shuffle问题，input数据是hadoop产出的都是按照key进行排序，导致paddle每次读入的数据有偏

**Comment by guoshengCS** [comment]
已解决，这里先行close，如有需要可以reopen
