### ISSUE TITLE
fluid启动pserver时卡住

### ISSUE THREAD

**Issue by flyhighzy** [PaddlePaddle/Paddle#15038]
使用环境：自建k8s, 使用paddle镜像：1.0.1-gpu-cuda8.0-cudnn7
启动pserver相关代码 ：

```
    if training_role == "PSERVER":
        place = fluid.CPUPlace()
    exe = fluid.Executor(place)
    if is_local:
        train_loop(fluid.default_main_program())
    else:
        eplist = []
        for ip in pserver_ips.split(","):
            eplist.append(':'.join([ip, port]))
        pserver_endpoints = ",".join(eplist)  # ip:port,ip:port...
        print(pserver_endpoints)
        print(trainers)
        print(trainer_id)
        t = fluid.DistributeTranspiler()
        t.transpile(
            trainer_id,
            pservers=pserver_endpoints,
            trainers=trainers)

        if training_role == "PSERVER":
            print("pserver")
            print("current_endpoint: %s" % current_endpoint)
            pserver_prog = t.get_pserver_program(current_endpoint)
            pserver_startup = t.get_startup_program(current_endpoint,
                                                    pserver_prog)
            print("start pserver...")
            exe.run(pserver_startup)
            print("pserver start up ok: %s" % pserver_startup)
            exe.run(pserver_prog)
            print("pserver ended")
        elif training_role == "TRAINER":
            print("trainer")
            train_loop(t.get_trainer_program())
```

输出日志中发现输出了start pserver...之后再无新日志输出，而trainer也一直在等待pserver启动成功, 不停的输出“pserver not ready, wait 3 sec to retry...”，一段时间后trainer也失败退出。
感觉pserver启动过程中在exe.run(pserver_startup)时卡住了，请问是什么原因可能导致这种情况？

**Comment by guoshengCS** [comment]
搜了下报“pserver not ready, wait 3 sec to retry...”这个错的代码，貌似是通信问题，还没有进入Paddle Fluid的执行逻辑，https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/fluid/transpiler/details/checkport.py#L48, 会被这里调用 https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/fluid/transpiler/distribute_transpiler.py#L563 ，可以试下单独执行下wait_server_ready这段代码看看是否有网络通信问题

**Comment by flyhighzy** [comment]
是的，trainer确实还没开始工作，在等待pserver，现在就是在启动pserver过程中表现为在执行`exe.run(pserver_startup)`时卡住了，导致pserver没成功启动。麻烦看下这个原因

**Comment by guoshengCS** [comment]
可以试下加下这两个环境变量输出更多日志看下，贴出来方便debug
```
export GLOG_v=3
export GLOG_logtostderr=1
```

**Comment by gongweibao** [comment]
你的代码贴全一点？或者把日志打开，日志多打一点？
```
export GLOG_v=10
export GLOG_logtostderr=1
```

**Comment by flyhighzy** [comment]
具体代码和pserver日志见附件 
[code&log.zip](https://github.com/PaddlePaddle/Paddle/files/2708370/code.log.zip)

**Comment by flyhighzy** [comment]
请问有看出问题吗~

**Comment by gongweibao** [comment]
pserver应该用parallelexecutor 启动。
给你一个例子，你可以看一下：
https://github.com/PaddlePaddle/models/blob/develop/fluid/PaddleCV/image_classification/dist_train/dist_train.py#L326
