### ISSUE TITLE
Potential issue after loading model twice

### ISSUE THREAD

**Issue by hshen14** [PaddlePaddle/Paddle#15055]
Here is the usage scenario in our case: 
* A single python unit test
* Load INT8 model, do the inference
* Load FP32 model, do the inference (will crash due to current key reuse mechanism)
* INT8 model is transformed from FP32 model, so all the shape and variable name are same

Here is the sample code for reference:

[int8_infer_program, feed_dict, fetch_targets] = fluid.io.load_inference_model(int8_model, exe)
with fluid.program_guard(main_program=int8_infer_program):
    # do the int8 inference

[fp32_infer_program, feed_dict, fetch_targets] = fluid.io.load_inference_model(fp32_model, exe)
with fluid.program_guard(main_program=fp32_infer_program):
    # do the fp32 inference

The crash shows "paddle.fluid.core.EnforceNotMet: Enforce failed. Expected requested_size >= size, but received requested_size:10035200 < size:40140800". We probably can fix the issue at key reuse side, however, the issue seems general (e.g, run FP16 model first and then FP32), and we would like to raise it for discussion and figure out a better solution.

Is it possible to have the mechanism to reset devicecontext/place/scope in Python API (e.g., p_blobmap in MKLDNNDeviceContext)? Any suggestions? Thanks.

@panyx0718 @Superjomn

**Comment by panyx0718** [comment]
Can you search "program_scope_guard" and do something similar? Let me know the result.

**Comment by hshen14** [comment]
Thanks. I found some sample code:

    @contextlib.contextmanager
    def program_scope_guard(self):
        prog = fluid.Program()
        startup_prog = fluid.Program()
        scope = fluid.core.Scope()
        with fluid.scope_guard(scope):
            with fluid.program_guard(prog, startup_prog):
                yield

A basic question: shall we follow the similar @contextlib.contextmanager here? Below is my simplified case for your review; however, with the scope guard, even FP32 single run does not work.

    [fp32_infer_program, feed_dict, fetch_targets] = fluid.io.load_inference_model(fp32_model, exe)
    t = fluid.transpiler.InferenceTranspiler()
    t.transpile(fp32_infer_program, place)

    scope = fluid.core.Scope()
    with fluid.scope_guard(scope):
        with fluid.program_guard(main_program=fp32_infer_program):
            # do fp32 inference

**Comment by panyx0718** [comment]
you need to put the guard before load

**Comment by hshen14** [comment]
with fluid.scope_guard(fluid.core.Scope()):
    with fluid.program_guard(fluid.Program(), fluid.Program()):
        [int8_infer_program, feed_dict, fetch_targets] = fluid.io.load_inference_model(int8_model, exe)
        t = fluid.transpiler.InferenceTranspiler()
        t.transpile(int8_infer_program, place)
        # do int8 inference # OK

with fluid.scope_guard(fluid.core.Scope()):
    with fluid.program_guard(fluid.Program(), fluid.Program()):
        [fp32_infer_program, feed_dict, fetch_targets] = fluid.io.load_inference_model(fp32_model, exe)
        t = fluid.transpiler.InferenceTranspiler()
        t.transpile(fp32_infer_program, place)
        # do fp32 inference # Crash

It shows the same error: "paddle.fluid.core.EnforceNotMet: Enforce failed. Expected requested_size >= size, but received requested_size:10035200 < size:40140800".

**Comment by panyx0718** [comment]
Does it work with fp32 alone?

What `exe` are you using? Can you create new Executor for each case?

**Comment by wojtuss** [comment]
Closed, due to INT8v1 having been removed.
