### ISSUE TITLE
How/Where could i upload the calibration tool doc for integrating

### ISSUE THREAD

**Issue by guomingz** [PaddlePaddle/Paddle#15063]
We've implemented the calibration tool for int8 inference.
i have some questions on the location of this tool document, what's the suitable way to upload it?
relate #15062

**Comment by luotao1** [comment]
I think the tool usage document https://github.com/PaddlePaddle/Paddle/pull/15062#issue-240915833 can be put in `python/paddle/fluid/contrib/int8_inference/` at first.
