### ISSUE TITLE
paddle现在支持bert模型吗？有官方提供的model不？

### ISSUE THREAD

**Issue by dashulu** [PaddlePaddle/Paddle#15067]
paddle支持bert吗？如果支持需要什么版本能跑起来？paddle提供官方的model吗？

**Comment by wanghaoshuang** [comment]
已经有同事在做了，但是还没有正式发布bert。

**Comment by wanghaoshuang** [comment]
更多进展与详情，可以和 @kuke 沟通下。

**Comment by kuke** [comment]
@dashulu BERT将会在近期开源，敬请关注

**Comment by wanghaoshuang** [comment]
关于BERT可以关注https://github.com/PaddlePaddle/models, 后续不在该issue中讨论。

**Comment by kuke** [comment]
BERT on Paddle 的实现开源在这里，敬请关注 https://github.com/PaddlePaddle/models/tree/develop/PaddleNLP/PaddleLARK/BERT
