### ISSUE TITLE
怎么获取PaddlePaddle3.0版本，试用autodl功能

### ISSUE THREAD

**Issue by upwindflys** [PaddlePaddle/Paddle#15072]
看到发布的paddlepaddle3.0支持automl,请问对应版本是哪个呢？

**Comment by wanghaoshuang** [comment]
您好，请问您是从什么渠道获知paddlepaddle3.0版本相关消息的呢？

**Comment by upwindflys** [comment]
> 您好，请问您是从什么渠道获知paddlepaddle3.0版本相关消息的呢？

https://www.infoq.cn/article/2018%2F07%2Fbaidu-ai-con 提到了PaddlePaddle3.0 包括完整的核心框架，以及 AI Studio、AutoDL、EasyDL 等可以让开发者平等便捷获取顶尖 AI 能力的平台。

**Comment by wanghaoshuang** [comment]
您说的内容不仅是Paddle基础框架的内容，关于AI Studio、AutoDL、EasyDL 可以参考：ai.baidu.com

**Comment by wanghaoshuang** [comment]
该issue已给出回复，但长期未收到反馈，暂时将其关闭。如果需要，请随时reopen. 谢谢。
