### ISSUE TITLE
paddlepaddle是否有参数绑定机制

### ISSUE THREAD

**Issue by GuangyanZhang** [PaddlePaddle/Paddle#15078]
我想多层卷积使用同一个卷积核？了解到要param_name命名为一样的，但是没有找到这个机制。。。

**Comment by wanghaoshuang** [comment]
您好，将conv2d的name设置为一样即可。https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/fluid/layers/nn.py#L1750

**Comment by wanghaoshuang** [comment]
该issue长期未收到反馈，暂时将其关闭，如果需要，请随时reopen.谢谢。
