### ISSUE TITLE
concat代码报错。

### ISSUE THREAD

**Issue by procr** [PaddlePaddle/Paddle#15091]
https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/fluid/operators/strided_memcpy.h#L68

此行代码是否应该改为
`for (int64_t i = 0; i < dst_stride_numel.size(); ++i) {`

**Comment by cuicheng01** [comment]
你用的concat是报错还是精度对不上？另外是paddle的哪个版本呢？

**Comment by procr** [comment]
上面的代码链接也是直接到你们最新的版本。
这里只是代码写的不对，不过在实际运行的过程应该并不会报错。“src and dst should have the same elements，except the specified axis.”  那么遍历的长度就应该是concat的tensort维度[0, dim.size())，而不是[0, axis)
