### ISSUE TITLE
Check failed: in_->ids

### ISSUE THREAD

**Issue by dreamingcp** [PaddlePaddle/Paddle#1509]
I0301 17:46:06.359429   185 GradientMachine.cpp:141] Init parameters done.
I0301 17:47:19.549320   191 ThreadLocal.cpp:37] thread use undeterministic rand seed:192
F0301 17:47:19.646843   186 TableProjection.cpp:39] Check failed: in_->ids F0301 17:0:7:47:19..646875   189 TableProjection.cpp::3939] Check failed: in_->ids 

F0301 17:47:19.646843   187 TableProjection.cpp:39] Check failed: in_->ids 
*** Check failure stack trace: ***
/usr/local/bin/paddle: line 109:   185 Aborted                 (core dumped) ${DEBUGGER} $MYDIR/../opt/paddle/bin/paddle_trainer ${@:2}

用cpu版的docker跑的，demo可以跑，对其加了2层网络之后就出现上面的情况。请问大概是什么原因？网络配置的问题吗？

**Comment by qingqing01** [comment]
> F0301 17:47:19.646843 186 TableProjection.cpp:39] Check failed: in_->ids F0301 17:0:7:47:19..646875 189 TableProjection.cpp::3939] Check failed: in_->ids

这个通常发生在embedding层，可能原因是由于数据和配置原因导致，可以贴出网络配置和dataprovider代码来分析下~
