### ISSUE TITLE
DataType of Paddle Op reduce_sum_grad must be the same.

### ISSUE THREAD

**Issue by zhouksh** [PaddlePaddle/Paddle#15115]
inference 过程正常，可以打印loss，但是假如optimizer 进行训练时报错：

Traceback (most recent call last):
  File "ref/train.py", line 111, in <module>
    train(args)
  File "ref/train.py", line 79, in train
    result = exe.run(fluid.default_main_program(), feed=feed, fetch_list=fetch_list, return_numpy=True)
  File "/home/work/software/paddle_release_home/python/lib/python2.7/site-packages/paddle/fluid/executor.py", line 470, in run
    self.executor.run(program.desc, scope, 0, True, True)
paddle.fluid.core.EnforceNotMet: DataType of Paddle Op reduce_sum_grad must be the same. Get reduce_sum_1.tmp_0(5) != reduce_sum_1.tmp_0@GRAD(3) at [/paddle/paddle/fluid/framework/operator.cc:860]
PaddlePaddle Call Stacks:
0       0x7fe6a5a19246p paddle::platform::EnforceNotMet::EnforceNotMet(std::__exception_ptr::exception_ptr, char const*, int) + 486
1       0x7fe6a711855cp paddle::framework::OperatorWithKernel::IndicateDataType(paddle::framework::ExecutionContext const&) const + 956
2       0x7fe6a71188dfp paddle::framework::OperatorWithKernel::GetExpectedKernelType(paddle::framework::ExecutionContext const&) const + 47
3       0x7fe6a711993dp paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::voi
4       0x7fe6a7115c5fp paddle::framework::OperatorBase::Run(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost:
5       0x7fe6a5ae6debp paddle::framework::Executor::RunPreparedContext(paddle::framework::ExecutorPrepareContext*, paddle::framework::Scope*, bool, bool, bool) + 219
6       0x7fe6a5ae7a40p paddle::framework::Executor::Run(paddle::framework::ProgramDesc const&, paddle::framework::Scope*, int, bool, bool) + 128
7       0x7fe6a59fb23dp
8       0x7fe6a5a2f0d4p pybind11::cpp_function::dispatcher(_object*, _object*, _object*) + 2596
9       0x7fe6eb2e8bb8p PyEval_EvalFrameEx + 25016
10      0x7fe6eb2ec0bdp PyEval_EvalCodeEx + 2061
11      0x7fe6eb2e9345p PyEval_EvalFrameEx + 26949
12      0x7fe6eb2e9460p PyEval_EvalFrameEx + 27232
13      0x7fe6eb2ec0bdp PyEval_EvalCodeEx + 2061
14      0x7fe6eb2ec1f2p PyEval_EvalCode + 50
15      0x7fe6eb314f42p PyRun_FileExFlags + 146
16      0x7fe6eb3162d9p PyRun_SimpleFileExFlags + 217
17      0x7fe6eb32c00dp Py_Main + 3149
18      0x7fe6ea529bd5p __libc_start_main + 245
19            0x4007a1p

**Comment by dzhwinter** [comment]
报错为
reduce_sum_1.tmp_0(5) != reduce_sum_1.tmp_0@GRAD(3)， 
是说输出的loss是int，而需要的grad是float，类型匹配错误，你的输出是做过转换吗？

**Comment by zhouksh** [comment]
使用的loss 是layers.softmax_with_cross_entropy，打印出来的loss 结果是float 类型的

**Comment by dzhwinter** [comment]
datatype问题，检测一下reduce_sum op之后一层的类型

**Comment by dzhwinter** [comment]
this issue has been not active one month. Please feel free to reopen it.
