### ISSUE TITLE
paddle模型是否支持上采样或者反池化层，如果支持如何实现？

### ISSUE THREAD

**Issue by nqluowei** [PaddlePaddle/Paddle#15118]

**Comment by dzhwinter** [comment]
支持，参考https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/fluid/tests/unittests/test_unpool_op.py
提issue前请搜索文档。

**Comment by dzhwinter** [comment]
This issue is solved. closed. Please feel free to reopen it.
