### ISSUE TITLE
Paddle doesn't built in the configuration for the GPU (CUDA)

### ISSUE THREAD

**Issue by pmajchrzak** [PaddlePaddle/Paddle#15110]
Build sequence under ubuntu-16.04:
```
cd /repos/paddle_paddle
mkdir buil
cd build
cmake .. -DWITH_GPU=ON -DWITH_MKLDNN=OFF -DWITH_TESTING=OFF -DWITH_PROFILER=ON -DWITH_STYLE_CHECK=ON -DWITH_FLUID_ONLY=ON
```
(…)
```
make
```
not finished.
Error occurs:
```
 Linking CXX static library libpaddle_fluid.a
../libpaddle_fluid_api.a(io.cc.o): In function `__static_initialization_and_destruction_0':
/repos/paddle_paddle/build/paddle/fluid/pybind/pybind.h:251: undefined reference to `TouchOpKernelRegistrar_conv2d_fusion_CUDA_DEFAULT_TYPE()'
collect2: error: ld returned 1 exit status
paddle/fluid/inference/utils/CMakeFiles/visualizer.dir/build.make:492: recipe for target 'paddle/fluid/inference/utils/visualizer' failed
make[2]: *** [paddle/fluid/inference/utils/visualizer] Error 1
CMakeFiles/Makefile2:51149: recipe for target 'paddle/fluid/inference/utils/CMakeFiles/visualizer.dir/all' failed
make[1]: *** [paddle/fluid/inference/utils/CMakeFiles/visualizer.dir/all] Error 2
```

**Comment by luotao1** [comment]
How about build in Release Mode? `-DCMAKE_BUILD_TYPE=Release`

**Comment by pmajchrzak** [comment]
The release doesn't build too:
```
cmake .. -DWITH_GPU=ON -DWITH_MKLDNN=OFF -DWITH_TESTING=OFF -DWITH_PROFILER=ON -DWITH_STYLE_CHECK=ON -DWITH_FLUID_ONLY=ON -DCMAKE_BUILD_TYPE=Release
```
Error:
```
Linking CXX static library libpaddle_fluid_origin.a
../libpaddle_fluid_api.a(io.cc.o): In function `_GLOBAL__sub_I_io.cc':
io.cc:(.text.startup+0xbbd): undefined reference to `TouchOpKernelRegistrar_conv2d_fusion_CUDA_DEFAULT_TYPE()'
collect2: error: ld returned 1 exit status
```

**Comment by wopeizl** [comment]
是个bug 我有一个pr 15122 可以参考
This is a bug, please refer to #15122 

发自我的 iPhone

在 2018年12月31日，下午7:31，pmajchrzak <notifications@github.com<mailto:notifications@github.com>> 写道：


The release doesn't build too:

cmake .. -DWITH_GPU=ON -DWITH_MKLDNN=OFF -DWITH_TESTING=OFF -DWITH_PROFILER=ON -DWITH_STYLE_CHECK=ON -DWITH_FLUID_ONLY=ON -DCMAKE_BUILD_TYPE=Release


Error:

Linking CXX static library libpaddle_fluid_origin.a
../libpaddle_fluid_api.a(io.cc.o): In function `_GLOBAL__sub_I_io.cc':
io.cc<http://io.cc>:(.text.startup+0xbbd): undefined reference to `TouchOpKernelRegistrar_conv2d_fusion_CUDA_DEFAULT_TYPE()'
collect2: error: ld returned 1 exit status

**Comment by luotao1** [comment]
http://ci.paddlepaddle.org/viewLog.html?buildId=43816&buildTypeId=Manylinux1_Cuda80cudnn5cp27cp27mu&tab=buildLog&_focus=9173
