### ISSUE TITLE
paddle fluid 1.2 nce和paddle v2版本的nce计算loss上有什么区别吗，同样的网络结构，loss差别很大

### ISSUE THREAD

**Issue by huashaosmile** [PaddlePaddle/Paddle#15119]
v2版本的nce使用
self.nce_layer = paddle.layer.nce(
                input=self.norm_fc_2,
                label=self._label_layer,
                num_classes=label_dim,
                param_attr=paddle.attr.Param(name='nce_w', initial_mean=0.0, initial_std=1.0),
                bias_attr=paddle.attr.Param(name='nce_b', initial_mean=0.0, initial_std=1.0),
                num_neg_samples=self._num_neg_samples,
                neg_distribution=self._label_freq
            )

fluid版本的nce使用
w_param = fluid.default_main_program().global_block().create_parameter(shape=[label_dim, hidden2_dim],
                                                                               dtype='float32', name='nce_w', default_initializer=fluid.initializer.Normal())
        b_param = fluid.default_main_program().global_block().create_parameter(shape=[label_dim, 1], dtype='float32',
                                                                               name='nce_b', default_initializer=fluid.initializer.Normal())

        # 配置NCE层
        if not self._is_infer:
            self.nce_layer = fluid.layers.nce(
                input=self.norm_fc_2,
                sampler='custom_dist',
                custom_dist=self._dist,
                label=self._label_layer,
                num_total_classes=label_dim,
                param_attr=fluid.ParamAttr(name='nce_w'),
                bias_attr=fluid.ParamAttr(name='nce_b'),
                num_neg_samples=self._num_neg_samples
            )

另外实际使用时，当网络结构数据一样的情况下发现fluid训练比v2慢3倍左右

**Comment by dzhwinter** [comment]
感谢反馈。我们看一下这个问题。

**Comment by dzhwinter** [comment]
@seiriosPlus 请看一下这个实现是否和v2有差异

**Comment by huashaosmile** [comment]
有进展了吗？ @seiriosPlus @dzhwinter

**Comment by wanghaoshuang** [comment]
fluid比V2多了这一步操作：https://github.com/wanghaoshuang/Paddle/blob/develop/python/paddle/fluid/layers/nn.py#L2984

**Comment by huashaosmile** [comment]
从v2迁移到fluid模型出现不收敛的情况，模型结构一样，能帮忙看看是什么问题吗
v2版本的模型：
class UapDnn(object):

    def __init__(self, layer_dims, num_neg_samples, feature_dict,
                 label_freq, feature_info_list, is_infer=False):
        """
        构造函数

        :param layer_dims:   数组，每一层网络的维度
        :param is_infer:    是否预测
        """

        self._layer_dims = layer_dims
        self._feature_dict = feature_dict
        self._label_freq = label_freq
        self._feature_info_list = feature_info_list

        self._is_infer = is_infer

        self._num_neg_samples = num_neg_samples
        self._build_input_layer()
        self._build_embedding_layer()
        self.model_cost = self._build_dnn_model()

    def _build_input_layer(self):
        """
        build input layer
        """

        # 配置输入层

        self._input_layer_dic = {}
        self.feature_names = [feature_info[0] for feature_info in self._feature_info_list]
        self.is_sequence = [feature_info[1] for feature_info in self._feature_info_list]
        self.embed_dim = [int(feature_info[2]) for feature_info in self._feature_info_list]
        self.data_range = [int(feature_info[3]) for feature_info in self._feature_info_list]
        self.data_layer_names = ['_' + name for name in self.feature_names]

        for i in range(len(self.data_layer_names)):
            if self.is_sequence[i] == '0':
                self._input_layer_dic[self.data_layer_names[i]] = \
                    paddle.layer.data(
                        name=self.feature_names[i], type=paddle.data_type.integer_value(
                            len(self._feature_dict[self.feature_names[i]])))
            else:
                self._input_layer_dic[self.data_layer_names[i]] = \
                    paddle.layer.data(
                        name=self.feature_names[i], type=paddle.data_type.integer_value_sequence(
                            len(self._feature_dict[self.feature_names[i]])))

        # 配置label层

        self._label_layer = paddle.layer.data(
            name='label',
            type=paddle.data_type.integer_value(len(self._label_freq)))
        self._hot_layer = paddle.layer.data(
            name='hot',
            type=paddle.data_type.dense_vector(1))    

    def _create_emb_attr(self, name):
        """
        create embedding parameter
        """
        return paddle.attr.Param(
            name=name,
            initial_std=1.0,
            initial_mean=0.0,
            learning_rate=1,
            l2_rate=0,
            sparse_update=False)

    def _build_embedding_layer(self):
        """
        build embedding layer
        """
        self._embed_layer_dic = {}
        self.embed_layer_names = [data_layer + '_emb' for data_layer in self.data_layer_names]
        param_names = ['_proj' + data_layer for data_layer in self.data_layer_names]

        for i in range(len(self.embed_layer_names)):
            self._embed_layer_dic[self.embed_layer_names[i]] = \
                paddle.layer.embedding(
                    input=self._input_layer_dic[self.data_layer_names[i]],
                    size=self.embed_dim[i],
                    param_attr=self._create_emb_attr(param_names[i]))

    def _build_dnn_model(self):
        """
        build dnn model
        """
        self._concat_layer_dic = {}
        concat_layer_names = [embed_layer + '_con' for embed_layer in self.embed_layer_names]
        for i in range(len(concat_layer_names)):
            if self.is_sequence[i] == '2':
                conv_1 = paddle.networks.sequence_conv_pool(
                    input=self._embed_layer_dic[self.embed_layer_names[i]], context_len=3, hidden_size=256)
                conv_2 = paddle.networks.sequence_conv_pool(
                    input=self._embed_layer_dic[self.embed_layer_names[i]], context_len=4, hidden_size=256)
                # self._concat_layer_dic[concat_layer_names[i]] = paddle.layer.concat([conv_1, conv_2])

                _rnn_cell = paddle.networks.simple_lstm(
                    input=self._embed_layer_dic[self.embed_layer_names[i]], size=256)

                _lstm_last = paddle.layer.last_seq(input=_rnn_cell)

                self._concat_layer_dic[concat_layer_names[i]] = paddle.layer.concat([conv_1, conv_2, _lstm_last])

            elif self.is_sequence[i] == '1':
                # avg_emb = fluid.layers.sequence_pool(
                #    input=self._embed_layer_dic[self.embed_layer_names[i]], pool_type='average')
                avg_emb = paddle.layer.pooling(
                    input=self._embed_layer_dic[self.embed_layer_names[i]],
                    pooling_type=paddle.pooling.Avg())
                self._concat_layer_dic[concat_layer_names[i]] = avg_emb

            else:
                self._concat_layer_dic[concat_layer_names[i]] = self._embed_layer_dic[self.embed_layer_names[i]]

        hidden0_dim = self._layer_dims[0]
        hidden1_dim = self._layer_dims[1]
        hidden2_dim = self._layer_dims[2]
        label_dim = self._layer_dims[3]

        self._fc_0 = paddle.layer.fc(
            name="Relu0",
            input=paddle.layer.batch_norm(paddle.layer.concat(self._concat_layer_dic.values())),
            param_attr=paddle.attr.Param(name='fc_0_w', initial_mean=0.0, initial_std=1.0),
            size=hidden0_dim,
            act=paddle.activation.Linear(),
            bias_attr=False)

        self.norm_fc_0 = paddle.layer.batch_norm(input=self._fc_0, act=paddle.activation.Relu())

        self._fc_1 = paddle.layer.fc(
            name="Relu1",
            input=self.norm_fc_0,
            param_attr=paddle.attr.Param(name='fc_1_w', initial_mean=0.0, initial_std=1.0),
            size=hidden1_dim,
            act=paddle.activation.Linear(),
            bias_attr=False
        )
        self.norm_fc_1 = paddle.layer.batch_norm(input=self._fc_1, act=paddle.activation.Relu())

        self._fc_2 = paddle.layer.fc(
            name="Relu2",
            input=self.norm_fc_1,
            param_attr=paddle.attr.Param(name='fc_2_w', initial_mean=0.0, initial_std=1.0),
            size=hidden2_dim,
            act=paddle.activation.Linear(),
            bias_attr=False
        )
        self.norm_fc_2 = paddle.layer.batch_norm(input=self._fc_2, act=paddle.activation.Relu())

        # 配置NCE层

        if not self._is_infer:
            self.nce_layer = paddle.layer.nce(
                input=self.norm_fc_2,
                label=self._label_layer,
                num_classes=label_dim,
                param_attr=paddle.attr.Param(name='nce_w', initial_mean=0.0, initial_std=1.0),
                bias_attr=paddle.attr.Param(name='nce_b', initial_mean=0.0, initial_std=1.0),
                num_neg_samples=self._num_neg_samples,
                neg_distribution=self._label_freq
            )
            return (self.nce_layer + self._hot_layer)


        else:
            self.predict_layer = paddle.layer.mixed(
                size=label_dim,
                input=paddle.layer.trans_full_matrix_projection(
                    self.norm_fc_2,
                    param_attr=paddle.attr.Param(name='nce_w')
                ),
                act=paddle.activation.Softmax(),
                bias_attr=paddle.attr.Param(name="nce_b")
            )
            return self.predict_layer

fluid版本模型：
# -*- coding:utf-8 -*-

import os
import numpy as np
import paddle.fluid as fluid


class UapDnn(object):
    """
            paddle uap dnn network configure
    """

    def __init__(self, layer_dims, neg_size, feature_dict,
                 label_freq, feature_info_list, is_infer=False):
        """
        构造函数

        :param layer_dims:   数组，每一层网络的维度
        :param is_infer:    是否预测
        """

        self._layer_dims = layer_dims
        self._feature_dict = feature_dict
        self._label_freq = label_freq
        self._feature_info_list = feature_info_list

        self._is_infer = is_infer
        self._dist = np.array(label_freq).astype('float32')
        self._num_neg_samples = neg_size
        self._build_input_layer()
        self._build_embedding_layer()
        self.model_cost = self.build_dnn_model()

    def _build_input_layer(self):
        """
        build input layer
        """
        # 配置输入层

        self._input_layer_dic = {}
        self.feature_names = [feature_info[0] for feature_info in self._feature_info_list]
        self.is_sequence = [feature_info[1] for feature_info in self._feature_info_list]
        self.embed_dim = [int(feature_info[2]) for feature_info in self._feature_info_list]
        # self.data_range = [int(feature_info[3]) for feature_info in self._feature_info_list]
        self.data_layer_names = ['_' + name for name in self.feature_names]

        for i in range(len(self.data_layer_names)):
            if self.is_sequence[i] == '0':
                self._input_layer_dic[self.data_layer_names[i]] = fluid.layers.data(name=self.feature_names[i],
                                                                                    shape=[1], dtype="int64")
            else:
                self._input_layer_dic[self.data_layer_names[i]] = \
                    fluid.layers.data(name=self.feature_names[i], shape=[1], dtype="int64", lod_level=1)
        # 配置label层

        self._label_layer = fluid.layers.data(name='label', dtype="int64", shape=[1])
        self._hot_layer = fluid.layers.data(name='hot', dtype='int64', shape=[1])

    def _create_emb_attr(self, name):
        """
        create embedding parameter
        """
        return fluid.param_attr.ParamAttr(name=name, initializer=fluid.initializer.Normal(), learning_rate=1.0,
                                          trainable=True)

    def _build_embedding_layer(self):
        """
        build embedding layer
        """
        self._embed_layer_dic = {}
        self.embed_layer_names = [data_layer + '_emb' for data_layer in self.data_layer_names]
        param_names = ['_proj' + data_layer for data_layer in self.data_layer_names]

        for i in range(len(self.embed_layer_names)):
            self._embed_layer_dic[self.embed_layer_names[i]] = \
                fluid.layers.embedding(
                    input=self._input_layer_dic[self.data_layer_names[i]],
                    size=[len(self._feature_dict[self.feature_names[i]]), self.embed_dim[i]],
                    param_attr=self._create_emb_attr(param_names[i]), is_sparse=True)

    def build_dnn_model(self):
        """
        build dnn model
        """

        self._concat_layer_dic = {}
        concat_layer_names = [embed_layer + '_con' for embed_layer in self.embed_layer_names]

        for i in range(len(concat_layer_names)):
            if self.is_sequence[i] == '2':
                conv_1 = fluid.nets.sequence_conv_pool(input=self._embed_layer_dic[self.embed_layer_names[i]], filter_size=3, num_filters=256)
                conv_2 = fluid.nets.sequence_conv_pool(input=self._embed_layer_dic[self.embed_layer_names[i]], filter_size=4, num_filters=256)
                # self._concat_layer_dic[concat_layer_names[i]] = paddle.layer.concat([conv_1, conv_2])

                _lstm_hidden0, _ = fluid.layers.dynamic_lstm(input=self._embed_layer_dic[self.embed_layer_names[i]], size=256)
                #_lstm_last = fluid.layers.sequence_pool(input=_lstm_hidden0, pool_type='max')
                _lstm_last = fluid.layers.sequence_last_step(input=_lstm_hidden0)

                self._concat_layer_dic[concat_layer_names[i]] = fluid.layers.concat([conv_1, conv_2, _lstm_last], axis=1)
            elif self.is_sequence[i] == '1':
                avg_emb = fluid.layers.sequence_pool(
                    input=self._embed_layer_dic[self.embed_layer_names[i]],
                    pool_type='average')
                self._concat_layer_dic[concat_layer_names[i]] = avg_emb

            else:
                self._concat_layer_dic[concat_layer_names[i]] = self._embed_layer_dic[self.embed_layer_names[i]]

        hidden0_dim = self._layer_dims[0]
        hidden1_dim = self._layer_dims[1]
        hidden2_dim = self._layer_dims[2]
        label_dim = self._layer_dims[3]

        self._fc_0 = fluid.layers.fc(
            name="Relu0",
            input=fluid.layers.batch_norm(fluid.layers.concat(self._concat_layer_dic.values(), axis=1)),
            param_attr=fluid.param_attr.ParamAttr(name='fc_0_w', initializer=fluid.initializer.Xavier()),
            size=hidden0_dim
        )

        self.norm_fc_0 = fluid.layers.batch_norm(input=self._fc_0, act='relu')

        self._fc_1 = fluid.layers.fc(
            name="Relu1",
            input=self.norm_fc_0,
            param_attr=fluid.param_attr.ParamAttr(name='fc_1_w', initializer=fluid.initializer.Xavier()),
            size=hidden1_dim
        )
        self.norm_fc_1 = fluid.layers.batch_norm(input=self._fc_1, act='relu')

        self._fc_2 = fluid.layers.fc(
            name="Relu2",
            input=self.norm_fc_1,
            param_attr=fluid.param_attr.ParamAttr(name='fc_2_w', initializer=fluid.initializer.Xavier()),
            size=hidden2_dim
        )
        self.norm_fc_2 = fluid.layers.batch_norm(input=self._fc_2, act='relu')

        w_param = fluid.default_main_program().global_block().create_parameter(shape=[label_dim, hidden2_dim],
                                                                               dtype='float32', name='nce_w')
        b_param = fluid.default_main_program().global_block().create_parameter(shape=[label_dim, 1], dtype='float32',
                                                                               name='nce_b')

        # 配置NCE层
        if not self._is_infer:
            os.environ['PADDLE_ENABLE_REMOTE_PREFETCH'] = "1"
            self.nce_layer = fluid.layers.nce(
                input=self.norm_fc_2,
                sampler='custom_dist',
                custom_dist=self._dist,
                label=self._label_layer,
                num_total_classes=label_dim,
                param_attr=fluid.ParamAttr(name='nce_w'),
                bias_attr=fluid.ParamAttr(name='nce_b'),
                num_neg_samples=self._num_neg_samples,
                is_sparse=True
            )
            del os.environ['PADDLE_ENABLE_REMOTE_PREFETCH']
            return (self.nce_layer+self._hot_layer)

        else:
            norm_fc = fluid.layers.transpose(fluid.layers.matmul(x=self.norm_fc_2, y=w_param, transpose_y=True),
                                             perm=[1, 0]) + b_param
            predict_layer = fluid.layers.softmax(fluid.layers.transpose(norm_fc, perm=[1, 0]))
            pred_topvalue, pred_topindices = fluid.layers.topk(predict_layer, k=100)
            return pred_topvalue, pred_topindices

**Comment by xuezhong** [comment]
由于V2多了cost / (num_neg_samples + 1)  你可以考虑，loss/(num_neg_samples + 1) 修正，先对上loss

**Comment by huashaosmile** [comment]
> 由于V2多了cost / (num_neg_samples + 1) 你可以考虑，loss/(num_neg_samples + 1) 修正，先对上loss

loss从训练的结果上能够对的上，不过在mpi上训练的时候由于目前的fluid1.2在nn.py的4730行的assign未定义，导致在mpi上训练无法使用nce的custom_dist模型，这个bug还麻烦一下你们这边修复一下。
可以使用fluid1.2 nce的示例代码发现bug， 目前示例代码无法运行
import numpy as np
import paddle.fluid as fluid
import paddle.fluid.layers as layers

window_size = 5
words = []
for i in xrange(window_size):
    words.append(layers.data(
        name='word_{0}'.format(i), shape=[1], dtype='int64'))

dict_size = 10000
label_word = int(window_size / 2) + 1

embs = []
for i in xrange(window_size):
    if i == label_word:
        continue

    emb = layers.embedding(input=words[i], size=[dict_size, 32],
                           # param_attr='emb.w',
                           is_sparse=True)
    embs.append(emb)

embs = layers.concat(input=embs, axis=1)

# 使用custom distribution
# dist = fluid.layers.assign(input=np.array([0.05, 0.5, 0.1, 0.3, 0.05]).astype("float32"))
dist = np.array([0.05, 0.5, 0.1, 0.3, 0.05]).astype("float32")
loss = layers.nce(input=embs, label=words[label_word],
                  num_total_classes=5,
                  # param_attr='nce.w',
                  # bias_attr='nce.b',
                  num_neg_samples=3,
                  sampler="custom_dist",
                  custom_dist=dist)
print(loss)

**Comment by huashaosmile** [comment]
我这边做了几个实验，网络结构，样本都一样的情况下，分别对于nce采用custom_dist采样方式，采用均匀采样方式，模型都不能收敛，弃用nce，采用softmax，同样的batch_size，最终采用softmax的模型达到了和v2差不多的收敛效果。你们这边看看是不是fluid 1.2版本的nce相比v2的nce除了损失函数最后除了个（neg_num +1）不同外，是不是nce具体实现逻辑有区别

**Comment by seiriosPlus** [comment]
fluid的nce的实现逻辑是参考V2的，有业务线使用了nce达到了v2的效果。 Fliud本身的实现和V2有一些区别，包括初始化、部分layer的实现。 可以把fluid的网络和v2的做一个完全对齐， 可以考虑使用最新的develop编译出来的包， 修复了nce中按频率采样的一个bug。

**Comment by xuezhong** [comment]
> mpi上训练的时候由于目前的fluid1.2在nn.py的4730行的assign未定义，导致在mpi上训练无法使用nce的custom_dist模型，这个bug还麻烦一下你们这边修复一下。
> 可以使用fluid1.2 nce的示例代码发现bug，

这个bug已经在develop上修复，预计1.3发布。
精度对不齐的问题，我们再看下

**Comment by huashaosmile** [comment]
OK，问一下1.3大概是什么时间发布呢

**Comment by seiriosPlus** [comment]
应该是月底左右，如果是paddle cloud上运行的可以根据Wiki自行build， 或者单hi我发给你一个包

**Comment by huashaosmile** [comment]
> 有业务线使用了nce达到了v2的效果

这个应该是在没有使用频次采样模式下的，因为上述bug是出现在频次采样模式。我这边使用的是频次采样模式发现不收敛情况，所以还麻烦您看看频次采样模式是否还存在bug

**Comment by seiriosPlus** [comment]
> > 有业务线使用了nce达到了v2的效果
> 
> 这个应该是在没有使用频次采样模式下的，因为上述bug是出现在频次采样模式。我这边使用的是频次采样模式发现不收敛情况，所以还麻烦您看看频次采样模式是否还存在bug

是使用的按频率采样的， 给他们用的版本是我修复了该问题的。
