### ISSUE TITLE
sequence_tagging_for_ner 模型替换训练数据后效果不收敛

### ISSUE THREAD

**Issue by ylxsyf** [PaddlePaddle/Paddle#15123]
https://github.com/PaddlePaddle/models/tree/develop/legacy/sequence_tagging_for_ner
将模型中的特征进行替换label进行替换后，训练1000轮以上，效果不收敛。
precsion和recall都不足10%
不论怎么替换特征，都无法收敛
想确认下怎么看下模型是不是生效了。

备注：原始数据能够收敛，1000轮以上，训练集可以达到100%准确率

**Comment by dzhwinter** [comment]
原始数据能收敛，说明模型配置是没有问题的。检查一下label和特征替换是否正确吧？

**Comment by ylxsyf** [comment]
> 原始数据能收敛，说明模型配置是没有问题的。检查一下label和特征替换是否正确吧？

是正确的，看了。

**Comment by dzhwinter** [comment]
那就是你的数据样本问题了，欠拟合

**Comment by dzhwinter** [comment]
close since it has been solved. please feel free to reopen it.
