### ISSUE TITLE
希望paddle尽快支持mixup操作，毕竟这个操作对分类，检测，分割都会有显著的提高！

### ISSUE THREAD

**Issue by cuicheng01** [PaddlePaddle/Paddle#15126]

**Comment by dzhwinter** [comment]
你好，mixup的操作是指什么呢？ 混合精度的训练？

**Comment by cuicheng01** [comment]
> 你好，mixup的操作是指什么呢？ 混合精度的训练？

是的，可以看一下那篇论文https://arxiv.org/abs/1710.09412

**Comment by cuicheng01** [comment]
@dzhwinter mixup主要是对两张图和label做mix操作，原理也很简单，但是怎么把他们和reader结合起来，不是很会写

**Comment by dzhwinter** [comment]
可以读入一个batch内数据，对batch内的数据做mixed_up。
我看了下论文，只是前后样本的一个线性累加？

**Comment by dzhwinter** [comment]
你可以参考一下这个case，定制一个reader完成前后的变换就可以了
https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/fluid/tests/unittests/test_py_reader_using_executor.py#L132

使用py_reader，是否能满足你的需求？

**Comment by dzhwinter** [comment]
is there any active?
