### ISSUE TITLE
transformer paddle.fluid.core.EnforceNotMet: holder_ should not be null 

### ISSUE THREAD

**Issue by shashlik007** [PaddlePaddle/Paddle#15136]
W0102 12:50:41.764370 28848 grpc_server.cc:416] completion queue:RequestSend recv no regular event context:RequestSend name:[], ep:[] Process using req_id:0 
W0102 12:50:41.764364 28847 grpc_server.cc:416] completion queue:RequestSend recv no regular event context:RequestSend name:[], ep:[] Process using req_id:99 
W0102 12:50:41.764354 28845 grpc_server.cc:416] completion queue:RequestSend recv no regular event context:RequestSend name:[], ep:[] Process using req_id:95 
W0102 12:50:41.764375 28849 grpc_server.cc:416] completion queue:RequestSend recv no regular event context:RequestSend name:[], ep:[] Process using req_id:1 
Traceback (most recent call last): 
File "train.py", line 747, in 
train(args) 
File "train.py", line 689, in train 
trainer_id) 
File "train.py", line 521, in train_loop 
feed=feed_dict_list) 
File "/home/slurm/job/tmp/job-72767/python/lib/python2.7/site-packages/paddle/fluid/parallel_executor.py", line 272, in run 
self.executor.run(fetch_list, fetch_var_name) 
paddle.fluid.core.EnforceNotMet: holder_ should not be null 
Tensor not initialized yet when Tensor::type() is called. at [/paddle/paddle/fluid/framework/tensor.h:143] 
PaddlePaddle Call Stacks: 
0 0x7fa1eef15e86p paddle::platform::EnforceNotMet::EnforceNotMet(std::__exception_ptr::exception_ptr, char const*, int) + 486 
1 0x7fa1eef18569p paddle::framework::Tensor::type() const + 137 
2 0x7fa1f071a3b0p paddle::framework::GetDataTypeOfVar(paddle::framework::Variable const*) + 272 
3 0x7fa1f0224839p paddle::operators::ElementwiseOp::GetExpectedKernelType(paddle::framework::ExecutionContext const&) const + 137 
4 0x7fa1f071c9edp paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, boost::variant const&) const + 237 
5 0x7fa1f0718c2fp paddle::framework::OperatorBase::Run(paddle::framework::Scope const&, boost::variant const&) + 463 
6 0x7fa1f06d9a37p 
7 0x7fa1f06f63f0p 
8 0x7fa1f06f5c55p paddle::framework::details::OpHandleBase::RunAndRecordEvent(std::function const&) + 805 
9 0x7fa1f06d9530p paddle::framework::details::ComputationOpHandle::RunImpl() + 128 
10 0x7fa1f06f6cf5p paddle::framework::details::OpHandleBase::Run(bool) + 117 
11 0x7fa1f06badaap 
12 0x7fa1eeff0233p std::_Function_handler (), std::__future_base::_Task_setter, std::__future_base::_Result_base::_Deleter>, void> >::_M_invoke(std::_Any_data const&) + 35 
13 0x7fa1eefefa37p std::__future_base::_State_base::_M_do_set(std::function ()>&, bool&) + 39 
14 0x7fa250b31973p pthread_once + 83 
15 0x7fa1f06ba072p 
16 0x7fa1eeff1d84p ThreadPool::ThreadPool(unsigned long)::{lambda()#1}::operator()() const + 404 
17 0x7fa23ec178a0p 
18 0x7fa250b2c1c3p 
19 0x7fa25015412dp clone + 109

**Comment by velconia** [comment]
请提供一下 paddle 的版本，代码，以及环境信息

**Comment by shashlik007** [comment]
> 代码

https://github.com/PaddlePaddle/models/blob/develop/fluid/PaddleNLP/neural_machine_translation/transformer/train.py

版本：fluid 1.2, paddlepaddle_gpu-1.2.0-cp27-cp27mu-linux_x86_64.whl
环境：内网p40集群

**Comment by shashlik007** [comment]
现在上述问题没了，出现了以下问题：
yq01-sys-hic-p40-0075:17362:21438 [0] NCCL INFO NET/IB : GPU Direct RDMA Disabled for GPU 0 / HCA mlx5_0 (not supported by GPU) 
yq01-sys-hic-p40-0075:17362:21439 [1] NCCL INFO Ring 00 : 1[1] -> 2[2] via P2P/direct pointer 
yq01-sys-hic-p40-0075:17362:21441 [2] NCCL INFO Ring 00 : 2[2] -> 3[3] via P2P/direct pointer 
yq01-sys-hic-p40-0075:17362:21447 [4] NCCL INFO Ring 00 : 4[4] -> 5[5] via P2P/direct pointer 
yq01-sys-hic-p40-0075:17362:21438 [0] NCCL INFO Ring 00 : 15 -> 0 via NET/IB/0 
yq01-sys-hic-p40-0075:17362:21442 [3] NCCL INFO Ring 00 : 3[3] -> 4[4] via P2P/direct pointer 
yq01-sys-hic-p40-0075:17362:21490 [5] NCCL INFO Ring 00 : 5[5] -> 6[6] via P2P/direct pointer 
yq01-sys-hic-p40-0075:17362:21574 [6] NCCL INFO Ring 00 : 6[6] -> 7[7] via P2P/direct pointer 
yq01-sys-hic-p40-0075:17362:21438 [0] NCCL INFO Ring 00 : 0[0] -> 1[1] via P2P/direct pointer 
yq01-sys-hic-p40-0075:17362:21705 [7] NCCL INFO NCCL_IB_GID_INDEX set by environment to 3. 
yq01-sys-hic-p40-0075:17362:21705 [7] NCCL INFO NET/IB: Dev 0 Port 1 qpn 202 mtu 3 GID 3 (0/1044FF0AFFFF0000) 
yq01-sys-hic-p40-0075:17362:17362 [0] NCCL INFO Launch mode Group/CGMD/Stream 

yq01-sys-hic-p40-0075:17362:32659 [7] transport/net_ib.cu:829 NCCL WARN NET/IB : Got completion with error 12, opcode 1, len 0, vendor err 129 
yq01-sys-hic-p40-0075:17362:32659 [7] NCCL INFO include/net.h:30 -> 2 
yq01-sys-hic-p40-0075:17362:32659 [7] NCCL INFO transport/net.cu:404 -> 2 

yq01-sys-hic-p40-0075:17362:32659 [7] transport.cu:153 NCCL WARN transport.cu:153 -> 2 [Proxy thread error]

**Comment by velconia** [comment]
问题转移到了Wiki, 在Wiki中继续跟进，这个issue先close了
