### ISSUE TITLE
网络的共享参数除了param_attr设置同名以外，bias_attr是否也要同名呢

### ISSUE THREAD

**Issue by 333caowei** [PaddlePaddle/Paddle#15143]
查阅文档显示paddle的网络参数共享只需要设置param_attr同名即可，但是bias_attr不需要设置同名吗？例如在pairwise网络中，需要保持左右两个网络的参数共享，但是在paddle官方demo中我看只设置了param_attr同名，并没有设置bias_attr，这是为什么呢？

官方demo fluid paipairwise全连接网络：
https://github.com/PaddlePaddle/models/blob/develop/fluid/PaddleRec/multiview_simnet/nets.py
<img width="523" alt="image" src="https://user-images.githubusercontent.com/4569055/50597792-8ef07880-0ee3-11e9-86fe-fdb19993de60.png">

官方demo v2 paipairwise全连接网络：
https://github.com/PaddlePaddle/models/blob/develop/legacy/ltr/ranknet.py
<img width="582" alt="image" src="https://user-images.githubusercontent.com/4569055/50597876-e1ca3000-0ee3-11e9-8ed1-1a211a972929.png">

我理解应该：
![image](https://user-images.githubusercontent.com/4569055/50597852-ca8b4280-0ee3-11e9-9d64-b7c6a7e48345.png)
只有w和b都设置一个固定name以后，网络才是真正的参数共享

**Comment by velconia** [comment]
Good advice, 不过建议提到models repo中，这应该是models的编写者没有注意，已经反馈给模型同学修改了

**Comment by velconia** [comment]
这里simnet的例子中，其实应该设置```bias_attr=False```，去掉FC中的bias参数；

**Comment by velconia** [comment]
请问还有别的问题吗？

**Comment by 333caowei** [comment]
再请教一下，ltr pairwise模型是否也需要设置bias_attr=False呢？

**Comment by frankwhzhang** [comment]
您好，我是multiview_simnet的owner，这是个很好的问题，我会尽快修复这个问题，修复的方式是添加bias_attr=xxx . 另外legacy目录下的代码由于版本问题我们基本都迁移到fluid目录下，不再维护了。

**Comment by frankwhzhang** [comment]
代码已经修复，除了fc之外，gru/cnn也有类似的bias参数问题。https://github.com/PaddlePaddle/models/pull/1593

**Comment by velconia** [comment]
> ltr pairwise模型是否也需要设置bias_attr=False呢？

方便给一下 models 地址吗？

**Comment by 333caowei** [comment]
hi上联系把，caowei07

**Comment by velconia** [comment]
OK, close this issue first
