### ISSUE TITLE
c++里怎样解析beam_search layer的结果

### ISSUE THREAD

**Issue by shateng** [PaddlePaddle/Paddle#15141]
从paddle_arguments_get_value(_out_args, 0, prob));里得到的beam_search layer的输出是一个一维浮点数组，那么怎么解析出来beam_search对应的prob和ids列表呢？

**Comment by velconia** [comment]
@shateng 请问方便切换到 Fluid 版本吗？

**Comment by velconia** [comment]
https://github.com/PaddlePaddle/models/blob/c3ae83966538c58f06ba71087503558121f6e327/legacy/nmt_without_attention/generate.py#L11 

这个是v2 beam_search的infer方法，里面应该能满足你的需求

**Comment by shateng** [comment]
> https://github.com/PaddlePaddle/models/blob/c3ae83966538c58f06ba71087503558121f6e327/legacy/nmt_without_attention/generate.py#L11
> 
> 这个是v2 beam_search的infer方法，里面应该能满足你的需求

这是python的infer，c++里怎么得到beam search的搜索结果呢？

**Comment by luotao1** [comment]
试试`paddle_arguments_get_ids(_out_args, 0, id))`?
请参考#8293

**Comment by shateng** [comment]
> 试试`paddle_arguments_get_value(_out_args, 0, id))`?

这和现在用的 paddle_arguments_get_value(_out_args, 0, prob)) 有啥区别吗？把prob的浮点数组改成id的int数组？

**Comment by velconia** [comment]
Thanks for @luotao1 providing this issue https://github.com/PaddlePaddle/Paddle/issues/8293 and the code https://github.com/PaddlePaddle/Paddle/blob/da158c2279008010996687d32b88c76e4e8ec1b7/paddle/legacy/capi/examples/model_inference/sequence/main.c

**Comment by velconia** [comment]
Close this issue
