### ISSUE TITLE
如何使用Numpy指定与读取fc层的weight和bias的值

### ISSUE THREAD

**Issue by kelvict** [PaddlePaddle/Paddle#15149]
如何使用Numpy指定与读取fc层的weight和bias的值

**Comment by xuezhong** [comment]
参考这个例子，通过name索引参数，让后进行设置。
https://github.com/PaddlePaddle/models/blob/develop/fluid/PaddleNLP/machine_reading_comprehension/run.py#L390

**Comment by kelvict** [comment]
所以是先对fc的param_attr与bias_attr赋个对象指定名字。再根据这个名字用fluid.global_scope()，找出名字，进行变量值读取与赋值是么？

**Comment by xuezhong** [comment]
是的
