### ISSUE TITLE
如何在V2中查看layer的output shape？

### ISSUE THREAD

**Issue by jianxiangm** [PaddlePaddle/Paddle#15159]
比如在deepspeech2中，想查看某一层的输出shape，要怎么做呢？谢谢。
conv_layer = paddle.layer.img_conv(
        input=input,
        filter_size=filter_size,
        num_channels=num_channels_in,
        num_filters=num_channels_out,
        stride=stride,
        padding=padding,
        act=paddle.activation.Linear(),
        bias_attr=False)

**Comment by xuezhong** [comment]
可以查看v2相关文档，由于不维护了，我们自己先找下，再回复您

**Comment by jianxiangm** [comment]
@xuezhong 谢谢。
我查看了V2相关文档，但是貌似没找到。
由于在用deepspeech2，只有V2版本的。

**Comment by xuezhong** [comment]
组网编译的时候，可以通过.size看到shape相关信息
运行的时候，可以通过接口获得实际变量的值
https://github.com/PaddlePaddle/DeepSpeech/blob/a76fc692123e97e5f183c3a00e30b7f2e2d3f07c/model_utils/model.py#L171
parameters的获取
https://github.com/PaddlePaddle/DeepSpeech/blob/develop/model_utils/model.py#L401
