### ISSUE TITLE
resize_bilinear输出的shape问题

### ISSUE THREAD

**Issue by littletomatodonkey** [PaddlePaddle/Paddle#15158]
在使用resize_bilinear的时候，下面的代码输出的shape是(50,1,40,40)，但是我看官网说明是以actual_shape为准的，所以不知道是不是自己写的有问题。
我在训练的时候，如果将数据喂进去之后，再去实时查看shape的话，输出的shape又是以actual_shape为准，所以对这一块有疑惑，不知道是否是resize_bilinear在build model的时候有问题呢？

```
import paddle
import paddle.fluid as fluid
a = fluid.layers.fill_constant(shape=[50,1,20,20], value=0, dtype='int64')
shape_a = fluid.layers.shape( a )
shape_nc, shape_hw = fluid.layers.split(shape_a,  num_or_sections=[2,2])

output = fluid.layers.resize_bilinear(a, scale=2.0, actual_shape=shape_hw)
print( output.shape )
```

**Comment by typhoonzero** [comment]
您好，并不会的。paddle fluid有“编译时” 和 “运行时”两个概念，上面的代码是对应“编译时”，当开始feed数据并执行`exe.run()`时为运行时。运行时一般第一维是batch size会根据当前feed的数据的实际batch size决定，每个layer都是能处理batch size变化的情况的。

**Comment by littletomatodonkey** [comment]
哦哦这样，谢谢您。

**Comment by xuezhong** [comment]
没有进一步问题的话 我就关闭了
