### ISSUE TITLE
memory_optimize接口的input_program参数值是什么

### ISSUE THREAD

**Issue by yeyupiaoling** [PaddlePaddle/Paddle#15152]
# 环境
 - PaddlePaddle 1.2.0
 - Python 3.5
 - Ubuntu 16.04

# 问题
`paddle.fluid.transpiler.memory_optimize`接口中参数input_program类型是str，我传递`fluid.default_main_program()`可以吗？

**Comment by xuezhong** [comment]
fluid.default_main_program()  这个可以的

**Comment by yeyupiaoling** [comment]
好的，明白。谢谢
