### ISSUE TITLE
新训练得到得模型会覆盖上一次保存的模型吗？

### ISSUE THREAD

**Issue by yeyupiaoling** [PaddlePaddle/Paddle#15150]
# 环境
 - PaddlePaddle 1.2.0
 - Python 3.5
 - Ubuntu 16.04

# 问题
我只想保存一个pass的模型，如果之后的模型准确率要高于之前的，就按照原路径保存。
这里我一个问题，这些是否能直接覆盖之前的模型呢？会不会有什么问题？

**Comment by xuezhong** [comment]
这个判定最好用户程序实现，因为save的操作是用户调用的

**Comment by yeyupiaoling** [comment]
@xuezhong 你是说，应该要把之前删除再保存吗？

**Comment by xuezhong** [comment]
嗯 文件操作最好都由用户操作

**Comment by yeyupiaoling** [comment]
@xuezhong 好的，明白。谢谢了。
