### ISSUE TITLE
batch_norm层可以设置不使用CUDNN吗？

### ISSUE THREAD

**Issue by yeyupiaoling** [PaddlePaddle/Paddle#15151]
# 环境
 - PaddlePaddle 1.2.0
 - Python 3.5
 - Ubuntu 16.04

# 问题
我使用MobileNet V1和MobileNet V2 训练一个图像分类的模型，这两个模型都用到`fluid.layers.batch_norm`，但是我电脑用不了cudnn，原因是：#15140

我想都不使用cudnn训练，其中`fluid.layers.conv2d`和`fluid.layers.pool2d`都可以通过参数`use_cudnn=False`设置不使用cudnn。但是`fluid.layers.batch_norm`没有这个参数，但它的确使用了cudnn，这个要怎么处理？

**Comment by xuezhong** [comment]
这块内部的确只支持CuDNN，因此建议还是先安装Cuda 9.0版本试下

**Comment by yeyupiaoling** [comment]
@xuezhong 我安装的真的是cuda 9.0，但是不知道为什么用`nvidia-smi`查看有cuda 10，但是用`nvcc -V`看到的是cuda 9.0.
这里有我的详细讨论过程：https://github.com/PaddlePaddle/Paddle/issues/15140
麻烦一起解答下。

**Comment by yeyupiaoling** [comment]
@xuezhong 那batch_norm能单独指定使用CPU吗？

**Comment by yeyupiaoling** [comment]
因为显卡RTX2070 只能使用CUDA 10以上，所以之前的错误就是这个原因。
我通过自己基于CUDA 10 和 CUDNN 7.4 编译得到的PaddlePaddle，能够正常使用。
