### ISSUE TITLE
可以使用load_persistables加载模型做评估

### ISSUE THREAD

**Issue by yeyupiaoling** [PaddlePaddle/Paddle#15153]
# 环境
 - PaddlePaddle 1.2.0
 - Python 3.5
 - Ubuntu 16.04

# 问题
我在这里：https://github.com/PaddlePaddle/models/blob/develop/fluid/PaddleCV/image_classification/eval.py 看到了模型评估的方式。
但它加载模型的方式是：https://github.com/PaddlePaddle/models/blob/022c0899a325107821eff6754702ea0f5fb82ed2/fluid/PaddleCV/image_classification/eval.py#L81-L86

我加载模型的方式是：
```python
fluid.io.load_persistables(executor=exe, dirname='model/')
```

我这样加载模型是否合理，程序是能够正常运行的。

**Comment by xuezhong** [comment]
load_persistables加载变量都会加载模型参数，因此对于预测来说都是可以的

**Comment by yeyupiaoling** [comment]
@xuezhong `load_params`就不行，是吧？在已经使用`save_params`保存模型的情况下。

**Comment by xuezhong** [comment]
应该也是可以的

**Comment by yeyupiaoling** [comment]
@xuezhong 好的，谢谢回答。
