### ISSUE TITLE
在使用GPU训练的时候，也会使用CPU参与训练吗？

### ISSUE THREAD

**Issue by yeyupiaoling** [PaddlePaddle/Paddle#15157]
# 环境
 - PaddlePaddle 1.2.0 GPU版本
 - Python 3.5
 - Ubuntu 16.04

# 问题
在使用GPU训练的时候，也会使用CPU参与训练吗？我看CPU的使用率也很高
![2019-01-03 16-28-43](https://user-images.githubusercontent.com/26297768/50629594-2a332d80-0f78-11e9-9d15-ea4d23f5ae4b.png)
![2019-01-03 16-28-54](https://user-images.githubusercontent.com/26297768/50629595-2a332d80-0f78-11e9-967a-99762f2dd44d.png)

**Comment by xuezhong** [comment]
有的op是只会CPU上运行，比如while op，同时一些调度工作也会在CPU上，因此CPU有占用，也是正常的

**Comment by yeyupiaoling** [comment]
@xuezhong 好的，明白，谢谢。
