### ISSUE TITLE
seq_unpad 限制x与length必须要有相同的dimension 0

### ISSUE THREAD

**Issue by zhoukunsheng** [PaddlePaddle/Paddle#15166]
从seq_unpad 的实现意图上理解没有问题，但当使用reshape之后该dimension 的限制就显得不灵活。
譬如下面代码中删除reshape行的注释，则代码报EnforceNotMet 的错误

`
import numpy as np
import paddle.fluid as fluid
import paddle.fluid.layers as layers
import op_utils
np.random.seed(0)
batch=2
length = layers.data(name='length', shape=[1], dtype='int64')
rep = layers.data(name='rep', shape=[5,3], dtype='float32')

#rep = layers.reshape(rep, (-1, 3))

ret = layers.sequence_unpad(rep, length)
length_d = np.array([[2],[3]], dtype=np.int64)
rep_d = np.random.rand(2,5,3).astype('float32')

prog = fluid.default_main_program()
exe = fluid.Executor(fluid.CPUPlace())
exe.run(fluid.default_startup_program())

result, = exe.run(prog, feed={'length':length_d, 'rep':rep_d}, fetch_list=[ret], return_numpy=False)
print(np.array(result))

print(rep_d)
`

**Comment by sneaxiy** [comment]
您好，reshape后batch_size维和其他维度就混合在一起了，导致sequence_unpad的输入是[10, 3]（未reshape前是[2, 5, 3]），但length是[[2], [3]]，所以运行时出错。sequence_unpad要求输入数据的维度应该是batch_size * seq_len * other_dims。如果您确实需要reshape，您可以考虑改变length的输入，比如设置为[[4], [6]]。

**Comment by sneaxiy** [comment]
seq_unpad的输入要求第0维的含义是batch_size，因此要求length的第0维也必须是batch_size。在上述例子中reshape操作使rep的batch_size和其他维护混在一起了，所以报错。建议您不要reshape或用其他方式实现类似功能。
