### ISSUE TITLE
RMSProp训练loss不降，Momentum没有问题

### ISSUE THREAD

**Issue by cuicheng01** [PaddlePaddle/Paddle#15162]
paddle版本：0.15
遇到的问题：
在用paddle复现InceptionV4的时候，需要RMSProp优化器来训练，但是用该优化器loss完全不降，acc完全不涨，改成Momentum优化器就没有问题了，但是Momentum优化器最终的收敛精度会稍微差一点，论文也是这么说。
补充1:初始学习率是0.045，单机训练，centered = False 与True都试过了。
补充2：之前在复现MobileNet的时候也遇到了这个问题，但是最终用Momentum优化器对上了精度就没有再提issue

**Comment by cuicheng01** [comment]
RMSProp各种参数都试过了，搞不定，完全训练不动。

**Comment by shippingwang** [comment]
In progress
