### ISSUE TITLE
pserver模式下，使用py_reader报elementwise_op dimension mismatch的错误

### ISSUE THREAD

**Issue by LihangLiu** [PaddlePaddle/Paddle#15163]
我在用pserver模式训练的时候，
       如果用pyreader来读数据，会出现elementwise_op dimension mismatch的错误。
       如果用data feed的形式读数据就不会有。
请问是什么原因呢？
fluid版本为git上最新版。

**Comment by LihangLiu** [comment]
并不是一定会报错，是有一定概率的出错。

**Comment by sneaxiy** [comment]
能把详细的log放出来吗？另外，单机是否会出现同样的问题？

**Comment by LihangLiu** [comment]
log如下。单机模式和pserver+data feed的模式都不会报错。

    Enforce failed. Expected x_dims[i + axis] == y_dims[i], but received x_dims[i + axis]:4389 != y_dims[i]:766. 
    Broadcast dimension mismatch. at [/paddle/paddle/fluid/operators/elementwise/elementwise_op_function.h:63] 
    PaddlePaddle Call Stacks: 
    0 0x7f3c0a4ffd9dp void paddle::platform::EnforceNotMet::Init(std::string, char const*, int) + 365 
    1 0x7f3c0a500c50p paddle::platform::EnforceNotMet::EnforceNotMet(char const*, int, char const*, char const*, char const*, char const*, std::string, char const*, std::string, std::string) + 144
    2 0x7f3c0a74cb0cp paddle::operators::get_mid_dims(paddle::framework::DDim const&, paddle::framework::DDim const&, int, int*, int*, int*) + 444 
    3 0x7f3c0b80dd21p void paddle::operators::ElementwiseComputeEx, paddle::platform::CUDADeviceContext, float, float>(paddle::framework::ExecutionContext const&, paddle::framework::Tensor const*, paddle::framework::Tensor const*, int, paddle::operators::AddFunctor, paddle::framework::Tensor*) + 497 
    4 0x7f3c0b80e403p void paddle::operators::default_elementwise_add(paddle::framework::ExecutionContext const&, paddle::framework::Tensor const*, paddle::framework::Tensor const*, paddle::framework::Tensor*) + 115 
    5 0x7f3c0b80e6a0p paddle::operators::ElementwiseAddKernel::Compute(paddle::framework::ExecutionContext const&) const + 608 
    6 0x7f3c0b80e8e3p std::_Function_handler, paddle::operators::ElementwiseAddKernel, paddle::operators::ElementwiseAddKernel, paddle::operators::ElementwiseAddKernel, paddle::operators::ElementwiseAddKernel >::operator()(char const*, char const*, int) const::{lambda(paddle::framework::ExecutionContext const&)#1}>::_M_invoke(std::_Any_data const&, paddle::framework::ExecutionContext const&) + 35 
    7 0x7f3c0bcff48ap paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, boost::variant const&) const + 666 
    8 0x7f3c0bcfad2fp paddle::framework::OperatorBase::Run(paddle::framework::Scope const&, boost::variant const&) + 479 
    9 0x7f3c0bc8bb27p 
    10 0x7f3c0bca8d90p 
    11 0x7f3c0bca85f5p paddle::framework::details::OpHandleBase::RunAndRecordEvent(std::function const&) + 805 
    12 0x7f3c0bc8b620p paddle::framework::details::ComputationOpHandle::RunImpl() + 128 
    13 0x7f3c0bca9515p paddle::framework::details::OpHandleBase::Run(bool) + 117 
    14 0x7f3c0bc1a22dp 
    15 0x7f3c0bc1ac2dp paddle::framework::details::ThreadedSSAGraphExecutor::RunOp(std::shared_ptr > const&, paddle::framework::details::OpHandleBase*) + 1309 
    16 0x7f3c0bc1c944p paddle::framework::details::ThreadedSSAGraphExecutor::Run(std::vector > const&) + 2324 
    17 0x7f3c0bc217e4p paddle::framework::details::ScopeBufferedSSAGraphExecutor::Run(std::vector > const&) + 628 
    18 0x7f3c0a5f8f22p paddle::framework::ParallelExecutor::Run(std::vector > const&, std::string const&) + 562 
    19 0x7f3c0a4efd3ep 
    20 0x7f3c0a52585ep 
    21 0x7f3ceb10f1a7p PyEval_EvalFrameEx + 28695 
    22 0x7f3ceb1116c9p PyEval_EvalCodeEx + 2025 
    23 0x7f3ceb10eb98p PyEval_EvalFrameEx + 27144 
    24 0x7f3ceb1116c9p PyEval_EvalCodeEx + 2025 
    25 0x7f3ceb10eb98p PyEval_EvalFrameEx + 27144 
    26 0x7f3ceb1116c9p PyEval_EvalCodeEx + 2025 
    27 0x7f3ceb10eb98p PyEval_EvalFrameEx + 27144 
    28 0x7f3ceb1116c9p PyEval_EvalCodeEx + 2025 
    29 0x7f3ceb10eb98p PyEval_EvalFrameEx + 27144 
    30 0x7f3ceb1116c9p PyEval_EvalCodeEx + 2025 
    31 0x7f3ceb1118eap PyEval_EvalCode + 26 
    32 0x7f3ceb12abadp 
    33 0x7f3ceb12bd28p PyRun_FileExFlags + 120 
    34 0x7f3ceb12cf48p PyRun_SimpleFileExFlags + 232 
    35 0x7f3ceb13f16cp Py_Main + 2988 
    36 0x7f3cea374bd5p __libc_start_main + 245 
    37 0x7f3ceb20c07fp

**Comment by sneaxiy** [comment]
能否把您使用py_reader和data_feeder的代码贴出来？可能是配置的维度不正确导致。

**Comment by LihangLiu** [comment]
不好意思，订正下，单机模型的py_reader也会有概率报错。

**Comment by LihangLiu** [comment]
py_reader和data_feeder的代码如下：

    def _all_data_layers_with_property(self, mode):
        res_dict = copy.deepcopy(self._data_layers_with_property)
        # add extra
        res_dict.update({
            'num_items': {
                    'shape':[-1, 1], 'dtype':'int64', 'lod_level':1},
            'pos': {
                    'shape':[-1, 1], 'dtype':'int64', 'lod_level':1},
            'recent_mask': {
                    'shape':[-1, -1, -1], 'dtype':'float32', 'lod_level':0},
            'recent_pos': {
                    'shape':[-1, 1], 'dtype':'int64', 'lod_level':1},
        })
        for block_id in range(self._num_blocks):
            for atten_id in range(self._num_attens):
                name = 'mask-%d-%d' % (block_id, atten_id)
                res_dict[name] = {
                    'shape':[-1, -1, -1], 'dtype':'float32', 'lod_level':0}
        if self._recent_encode_type == 'Transformer':
            res_dict.update({
                'num_recents': {
                    'shape':[-1, 1], 'dtype':'int64', 'lod_level':1},
                'recent_encode_mask': {
                    'shape':[-1, -1, -1], 'dtype':'float32', 'lod_level':0},
            })
        res_dict['label'] = {
                    'shape':[-1], 'dtype':'int64', 'lod_level':1}
        return res_dict

    def create_inputs(self, mode):
        all_data_layers_with_property = self._all_data_layers_with_property(mode)
        inputs = {}
        for key, proper in all_data_layers_with_property.items():
            inputs[key] = layers.data(name=key, shape=proper['shape'], 
                                    dtype=proper['dtype'], lod_level=proper['lod_level'])
        return inputs

    def create_reader(self, mode):
        all_data_layers_with_property = self._all_data_layers_with_property(mode)
        # 
        sorted_names = sorted(all_data_layers_with_property.keys())
        reader = fluid.layers.py_reader(capacity=128,
                                        shapes=[all_data_layers_with_property[name]['shape'] for name in sorted_names],
                                        dtypes=[all_data_layers_with_property[name]['dtype'] for name in sorted_names],
                                        lod_levels=[all_data_layers_with_property[name]['lod_level'] for name in sorted_names],
                                        name="%s_reader" % mode,
                                        use_double_buffer=False)
        list_var = fluid.layers.read_file(reader)
        inputs = {name:var for name, var in zip(sorted_names, list_var)}
        return inputs, sorted_names, reader

create_inputs得到data_feeder的输入，create_reader得到py_reader的输入。两者都是调用了_all_data_layers_with_property这个函数（定义了所有的维度），所以应该不是写错的缘故。

**Comment by sneaxiy** [comment]
看目前贴出来的code应该没啥问题。能否方便把你的完整code贴出来？

**Comment by LihangLiu** [comment]
我这边自己实现了一个多线程的data feeder版本，发现如果提前准备多个batch的feed data（从numpy array变成lod tensor），就会出跟py reader同样的问题，请问从这个现象可以看出问题所在么？

**Comment by sneaxiy** [comment]
建议您检查下每次组成的lod_tensor维度是否是正确的。出现这种问题可能是某次feed的数据维度不对。
