### ISSUE TITLE
How to set `offset` and `length` for `sequence_slice` when the `input.lod` is unknown?

### ISSUE THREAD

**Issue by lijiancheng0614** [PaddlePaddle/Paddle#15160]
Hi,

I tried several times to use [`paddle.fluid.layers.sequence_slice`](http://www.paddlepaddle.org/documentation/docs/zh/1.2/api_cn/layers_cn.html#permalink-146-sequence_slice).

It works when I know the input (e.g. the example in the doc), but I don't know how to set the `offset` and `length` when the `input.lod` is unknown.

For example, the input is a `LOD_TENSOR_ARRAY` with shape `(-1L, 6L)` and I just want to get the last four elements for every sequence. (In numpy, we can use `input[:, 2:]` to get the result.) I tried to use `with while_op.block()` but also failed.

Any advices? Thanks!

**Comment by xuezhong** [comment]
you can try to reverse the sequence and slice it, finally reverse the result. Pls refer to http://www.paddlepaddle.org/documentation/docs/zh/1.2/api_cn/layers_cn.html#sequence-reverse

**Comment by lijiancheng0614** [comment]
Hi, I mean the length of the offset and length is unknown because the input.lod is unknown (the first value of the shape is -1 instead of a const if the length of the sequence is not fixed.)
If I do the reverse op, then how to do the sequence_slice for input[:, :4]?

**Comment by xuezhong** [comment]
获得batch_size的代码如下：
batch_ones = fluid.layers.fill_constant_batch_size_like(
        input=start_logits, dtype='int64', shape=[1], value=1)
    num_seqs = fluid.layers.reduce_sum(input=batch_ones)

**Comment by lijiancheng0614** [comment]
Finally use [`slice`](http://www.paddlepaddle.org/documentation/docs/zh/1.2/api_cn/layers_cn.html#slice) and [`lod-reset`](http://www.paddlepaddle.org/documentation/docs/zh/1.2/api_cn/layers_cn.html#lod-reset) to solve the problem.

Thanks!
