### ISSUE TITLE
同一台机器中，存在其他fluid任务的时候，import paddle.fluid as fluid会报错。

### ISSUE THREAD

**Issue by kelvict** [PaddlePaddle/Paddle#15168]
1、程序运行在16卡的K40机器上，看起来是仅import paddle.fluid的进程在16张卡中均占了100M显存，然后我再起了Python import fluid就报这个错。
`terminate called after throwing an instance of 'paddle::platform::EnforceNotMet'
  what():  out of memory at [/paddle/paddle/fluid/platform/device_context.cc:251]
PaddlePaddle Call Stacks:
0       0x7f212d2cbd06p paddle::platform::EnforceNotMet::EnforceNotMet(std::__exception_ptr::exception_ptr, char const*, int) + 486
1       0x7f212e8e73fap paddle::platform::CUDADeviceContext::Wait() const + 474
2       0x7f212e8e7b46p paddle::platform::CUDADeviceContext::~CUDADeviceContext() + 54
3       0x7f212e8e8131p paddle::platform::CUDADeviceContext::~CUDADeviceContext() + 17
4       0x7f212e5a6b92p std::_Rb_tree<boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_>, std::pair<boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const, std::unique_ptr<paddle::platform::DeviceContext, std::default_delete<paddle::platform::DeviceContext> > >, std::_Select1st<std::pair<boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const, std::unique_ptr<paddle::platform::DeviceContext, std::default_delete<paddle::platform::DeviceContext> > > >, std::less<boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> >, std::allocator<std::pair<boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const, std::unique_ptr<paddle::platform::DeviceContext, std::default_delete<paddle::platform::DeviceContext> > > > >::_M_erase(std::_Rb_tree_node<std::pair<boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const, std::unique_ptr<paddle::platform::DeviceContext, std::default_delete<paddle::platform::DeviceContext> > > >*) + 66
5       0x7f212e5a6b7fp std::_Rb_tree<boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_>, std::pair<boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const, std::unique_ptr<paddle::platform::DeviceContext, std::default_delete<paddle::platform::DeviceContext> > >, std::_Select1st<std::pair<boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const, std::unique_ptr<paddle::platform::DeviceContext, std::default_delete<paddle::platform::DeviceContext> > > >, std::less<boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> >, std::allocator<std::pair<boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const, std::unique_ptr<paddle::platform::DeviceContext, std::default_delete<paddle::platform::DeviceContext> > > > >::_M_erase(std::_Rb_tree_node<std::pair<boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const, std::unique_ptr<paddle::platform::DeviceContext, std::default_delete<paddle::platform::DeviceContext> > > >*) + 47
6       0x7f212e8e9b6ap paddle::platform::DeviceContextPool::DeviceContextPool(std::vector<boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_>, std::allocator<boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> > > const&) + 906
7       0x7f212e8ec2d8p paddle::framework::InitDevices(bool, std::vector<int, std::allocator<int> >) + 696
8       0x7f212e8ec50dp paddle::framework::InitDevices(bool) + 285
9       0x7f212d2aaa0ap
10      0x7f212d2e2414p pybind11::cpp_function::dispatcher(_object*, _object*, _object*) + 2596
11      0x7f217cce7039p PyEval_EvalFrameEx + 28537
12      0x7f217cce986dp PyEval_EvalCodeEx + 2061
13      0x7f217cce69fcp PyEval_EvalFrameEx + 26940
14      0x7f217cce986dp PyEval_EvalCodeEx + 2061
15      0x7f217cce99a2p PyEval_EvalCode + 50
16      0x7f217ccfe6bcp PyImport_ExecCodeModuleEx + 140
17      0x7f217ccfea1ep
18      0x7f217ccffe69p
19      0x7f217ccff919p
20      0x7f217cd0064ap PyImport_ImportModuleLevel + 682
21      0x7f217ccde0afp
22      0x7f217cc2df13p PyObject_Call + 67
23      0x7f217ccdfac7p PyEval_CallObjectWithKeywords + 71
24      0x7f217cce3f90p PyEval_EvalFrameEx + 16080
25      0x7f217cce986dp PyEval_EvalCodeEx + 2061
26      0x7f217cce99a2p PyEval_EvalCode + 50
27      0x7f217cd13777p PyRun_InteractiveOneFlags + 343
28      0x7f217cd1397ep PyRun_InteractiveLoopFlags + 78
29      0x7f217cd1417ep PyRun_AnyFileExFlags + 62
30      0x7f217cd2982dp Py_Main + 3149
31      0x7f217bf26bd5p __libc_start_main + 245
32            0x4007a1p

*** Aborted at 1546584543 (unix time) try "date -d @1546584543" if you are using GNU date ***
PC: @                0x0 (unknown)
*** SIGABRT (@0x20100004024) received by PID 16420 (TID 0x7f217d216700) from PID 16420; stack trace: ***
    @     0x7f217c9cc160 (unknown)
    @     0x7f217bf3a3f7 __GI_raise
    @     0x7f217bf3b7d8 __GI_abort
    @     0x7f2150179c65 __gnu_cxx::__verbose_terminate_handler()
    @     0x7f2150177e06 __cxxabiv1::__terminate()
    @     0x7f2150176ec9 __cxa_call_terminate
    @     0x7f2150177a7a __gxx_personality_v0
    @     0x7f215064c853 _Unwind_RaiseException_Phase2
    @     0x7f215064cd87 _Unwind_Resume
    @     0x7f212e8e7460 paddle::platform::CUDADeviceContext::Wait()
    @     0x7f212e8e7b46 paddle::platform::CUDADeviceContext::~CUDADeviceContext()
    @     0x7f212e8e8131 paddle::platform::CUDADeviceContext::~CUDADeviceContext()
    @     0x7f212e5a6b92 std::_Rb_tree<>::_M_erase()
    @     0x7f212e5a6b7f std::_Rb_tree<>::_M_erase()
    @     0x7f212e8e9b6a paddle::platform::DeviceContextPool::DeviceContextPool()
    @     0x7f212e8ec2d8 paddle::framework::InitDevices()
    @     0x7f212e8ec50d paddle::framework::InitDevices()
    @     0x7f212d2aaa0a _ZZN8pybind1112cpp_function10initializeIZN6paddle6pybindL13pybind11_initEvEUlbE65_vIbEINS_4nameENS_5scopeENS_7siblingEEEEvOT_PFT0_DpT1_EDpRKT2_ENUlRNS_6detail13function_callEE1_4_FUNESL_
    @     0x7f212d2e2414 pybind11::cpp_function::dispatcher()
    @     0x7f217cce7039 PyEval_EvalFrameEx
    @     0x7f217cce986d PyEval_EvalCodeEx
    @     0x7f217cce69fc PyEval_EvalFrameEx
    @     0x7f217cce986d PyEval_EvalCodeEx
    @     0x7f217cce99a2 PyEval_EvalCode
    @     0x7f217ccfe6bc PyImport_ExecCodeModuleEx
    @     0x7f217ccfea1e load_source_module
    @     0x7f217ccffe69 load_package
    @     0x7f217ccff919 import_submodule
    @     0x7f217cd0064a PyImport_ImportModuleLevel
    @     0x7f217ccde0af builtin___import__
    @     0x7f217cc2df13 PyObject_Call
    @     0x7f217ccdfac7 PyEval_CallObjectWithKeywords
Aborted`

2、
paddle.fluid.core.EnforceNotMet: CUDNN_STATUS_INTERNAL_ERROR at [/paddle/paddle/fluid/platform/device_context.cc:162]
`Python 2.7.14 (default, Apr 20 2018, 13:08:19)
[GCC 4.8.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import paddle.fluid as fluid
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/yuechu/python27-fluid/lib/python2.7/site-packages/paddle/fluid/__init__.py", line 142, in <module>
    __bootstrap__()
  File "/home/yuechu/python27-fluid/lib/python2.7/site-packages/paddle/fluid/__init__.py", line 136, in __bootstrap__
    core.init_devices(not in_test)
paddle.fluid.core.EnforceNotMet: CUDNN_STATUS_INTERNAL_ERROR at [/paddle/paddle/fluid/platform/device_context.cc:162]
PaddlePaddle Call Stacks:
0       0x7fd7b7aa7d06p paddle::platform::EnforceNotMet::EnforceNotMet(std::__exception_ptr::exception_ptr, char const*, int) + 486
1       0x7fd7b90c703bp paddle::platform::CudnnHolder::CudnnHolder(CUstream_st* const*, paddle::platform::CUDAPlace const&) + 699
2       0x7fd7b90c4412p paddle::platform::CUDADeviceContext::CUDADeviceContext(paddle::platform::CUDAPlace) + 722
3       0x7fd7b90c5a08p paddle::platform::DeviceContextPool::DeviceContextPool(std::vector<boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_>, std::allocator<boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> > > const&) + 552
4       0x7fd7b90c82d8p paddle::framework::InitDevices(bool, std::vector<int, std::allocator<int> >) + 696
5       0x7fd7b90c850dp paddle::framework::InitDevices(bool) + 285
6       0x7fd7b7a86a0ap
7       0x7fd7b7abe414p pybind11::cpp_function::dispatcher(_object*, _object*, _object*) + 2596
8       0x7fd8074c3039p PyEval_EvalFrameEx + 28537
9       0x7fd8074c586dp PyEval_EvalCodeEx + 2061
10      0x7fd8074c29fcp PyEval_EvalFrameEx + 26940
11      0x7fd8074c586dp PyEval_EvalCodeEx + 2061
12      0x7fd8074c59a2p PyEval_EvalCode + 50
13      0x7fd8074da6bcp PyImport_ExecCodeModuleEx + 140
14      0x7fd8074daa1ep
15      0x7fd8074dbe69p
16      0x7fd8074db919p
17      0x7fd8074dc64ap PyImport_ImportModuleLevel + 682
18      0x7fd8074ba0afp
19      0x7fd807409f13p PyObject_Call + 67
20      0x7fd8074bbac7p PyEval_CallObjectWithKeywords + 71
21      0x7fd8074bff90p PyEval_EvalFrameEx + 16080
22      0x7fd8074c586dp PyEval_EvalCodeEx + 2061
23      0x7fd8074c59a2p PyEval_EvalCode + 50
24      0x7fd8074ef777p PyRun_InteractiveOneFlags + 343
25      0x7fd8074ef97ep PyRun_InteractiveLoopFlags + 78
26      0x7fd8074f017ep PyRun_AnyFileExFlags + 62
27      0x7fd80750582dp Py_Main + 3149
28      0x7fd806702bd5p __libc_start_main + 245
29            0x4007a1p`

**Comment by sneaxiy** [comment]
经沟通，目前fluid尚不支持不通过设置CUDA_VISIBLE_DEVICES的方式达到完全不占用其他GPU显存的目的。CUDNN出错是因为还有机器上还有残留的paddle进程，导致CUDA分配资源报错。
