### ISSUE TITLE
Investigate Dockerfile CPU and GPU

### ISSUE THREAD

**Issue by gangliao** [PaddlePaddle/Paddle#1517]
Dockerfile和Dockerfile.gpu两个文件基本完全冗余，设法只保留一份，减小开发维护开销。

**Comment by typhoonzero** [comment]
找到cuda docker镜像的Dockerfile: https://hub.docker.com/r/nvidia/cuda/ 

可以合并一个From ubuntu14.04 的Dockerfile生成一个paddle的基础镜像，然后gpu版本的FROM这个paddle的基础镜像再安装cuda？

会不会有点hacky

**Comment by gangliao** [comment]
From Yancey1989
> @gangliao @typhoonzero 可以基于ubuntu做一个base的image，这样几个版本的Dockerfile可以减少冗余。

**Comment by typhoonzero** [comment]
@gangliao 的确。如果cuda的Dockerfile更新就不能自动更新到paddle的Dockerfile了

**Comment by typhoonzero** [comment]
目前Docker并不支持引用别的Dockerfile的方法

看上去https://hub.docker.com/r/nvidia/cuda/ cuda的Dockerfile也是使用不同的FROM会创建不同的Dockerfile。虽然可以使用一个程序来自动生成Dockerfile，但这样会变的不可读

**Comment by gangliao** [comment]
@typhoonzero  明白了

**Comment by Yancey1989** [comment]
```bash
yanxu@Yancey-MBP: docker diff Dockerfile Dockerfile.gpu
1c1
< FROM ubuntu:14.04
---
> FROM nvidia/cuda:7.5-cudnn5-devel-ubuntu14.04
17c17
< ENV WITH_GPU=OFF
---
> ENV WITH_GPU=ON
```
既然两个Dockerfile只有基础镜像和`WITH_GPU`参数不同，那么CPU和GPU版本都使用`nvidia/cuda:7.5-cudnn5-devel-ubuntu14.04`作为基础镜像是不是就可以了？
在docker build时，通过[--build-arg](https://docs.docker.com/engine/reference/commandline/build/#usage)来指定制作CPU或者GPU版本的Image：
```
docker build -t mypaddle:cpu-devel-latest --build-arg=WITH_GPU=OFF ./
```
