### ISSUE TITLE
使用SequenceUnpad op 出core

### ISSUE THREAD

**Issue by zhoukunsheng** [PaddlePaddle/Paddle#15174]
bp 时sequence_unpad 这个op 出core

![image](https://user-images.githubusercontent.com/29747927/50686563-e5cb8e80-1058-11e9-8133-d38deb377374.png)

**Comment by sneaxiy** [comment]
感谢您的反馈。经排查，原因是crf op的bug，crf的反向时未将emission的lod传递下去，导致后续的sequence_unpad op运行出错。我们会尽快修复此bug。
