### ISSUE TITLE
gru_unit的初始化方式

### ISSUE THREAD

**Issue by nizihan** [PaddlePaddle/Paddle#15177]
请问如果没有指定initializer的话，gru_unit的初始化方式是Xavier吗？相比于使用默认值，我显示的指定initializer为Xavier的时候，实验效果会有提升。请问这是什么原因？
使用默认值：
`clip = fluid.clip.GradientClipByNorm(clip_norm=2.0) `
`clip_attr = fluid.ParamAttr(gradient_clip=clip)`
`h, _, _ = fluid.layers.gru_unit(
                    input=decoder_inputs,
                    hidden = hidden_mem,
                    param_attr = clip_attr,
                    bias_attr = clip_attr,
                    size=args.decoder_size * 3)`

显示的指定initializer为Xavier：
`gru_clip = fluid.clip.GradientClipByNorm(clip_norm=2.0)`
        `gru_attr = fluid.ParamAttr(
                      gradient_clip = gru_clip,
                      initializer = fluid.initializer.Xavier())`
       ` h, _, _ = fluid.layers.gru_unit(
                    input=decoder_inputs,
                    hidden = hidden_mem,
                    param_attr = gru_attr,
                    bias_attr = clip_attr,
                    size=args.decoder_size * 3)`

**Comment by kuke** [comment]
参数的默认初始化器是Xavier没问题

https://github.com/PaddlePaddle/Paddle/blob/6d04a9cf4779a63123c5c1254450dbf881961b1f/python/paddle/fluid/param_attr.py#L106

有种办法可以看两种初始化方式的结果是否一致，可以将startup program的种子设置成一样，然后将初始化之后的参数拿出来做比较，请参考

https://github.com/PaddlePaddle/models/blob/2e86916fe32378f47ed89670125c5d814b97f4c4/fluid/PaddleNLP/deep_attention_matching_net/train_and_evaluate.py#L197
和

https://github.com/PaddlePaddle/models/blob/c19f7ac1841713de6afa10f0461495b36e169807/fluid/PaddleNLP/language_model/lstm/train.py#L56

**Comment by nizihan** [comment]
> 参数的默认初始化器是Xavier没问题
> 
> [Paddle/python/paddle/fluid/param_attr.py](https://github.com/PaddlePaddle/Paddle/blob/6d04a9cf4779a63123c5c1254450dbf881961b1f/python/paddle/fluid/param_attr.py#L106)
> 
> Line 106 in [6d04a9c](/PaddlePaddle/Paddle/commit/6d04a9cf4779a63123c5c1254450dbf881961b1f)
> 
>  self._set_default_initializer(Xavier()) 
> 有种办法可以看两种初始化方式的结果是否一致，可以将startup program的种子设置成一样，然后将初始化之后的参数拿出来做比较，请参考
> 
> https://github.com/PaddlePaddle/models/blob/2e86916fe32378f47ed89670125c5d814b97f4c4/fluid/PaddleNLP/deep_attention_matching_net/train_and_evaluate.py#L197
> 和
> 
> https://github.com/PaddlePaddle/models/blob/c19f7ac1841713de6afa10f0461495b36e169807/fluid/PaddleNLP/language_model/lstm/train.py#L56

好的，我试一下，谢谢哈
