### ISSUE TITLE
paddle保存模型有好几种方式，里面分别保存了什么东西，怎么相互转换?

### ISSUE THREAD

**Issue by imistyrain** [PaddlePaddle/Paddle#15176]
如题，在[image_classification](https://github.com/PaddlePaddle/models/blob/develop/fluid/PaddleCV/image_classification/train.py)中使用的是fluid.io.save_persistables()
在[object_detection](https://github.com/PaddlePaddle/models/blob/develop/fluid/PaddleCV/object_detection/train.py)中使用的是fluid.io.save_inference_model()
在[保存与载入模型变量](http://paddlepaddle.org/documentation/docs/zh/1.1/user_guides/howto/training/save_load_variables.html#id2)中还提到了fluid.io.save_params()和fluid.io.save_checkpoint()

**Comment by yeyupiaoling** [comment]
@imistyrain 可以参考这个两个issue：#14790  和   #14788

**Comment by NHZlX** [comment]
对于这样的接口，我比较喜欢直接去看py文件中的注释。

1.  save_persistables()
https://github.com/PaddlePaddle/Paddle/blob/88bd7e1a6194a123237129ee4e9cc5c70516946c/python/paddle/fluid/io.py#L439 
这个存储到磁盘中只是参数。和save_params类似，看到文档中有这么一个notice 
```
NOTICE: Some variables are not Parameter while they are necessary for
    training. So you can NOT save and continue your training just by
    `save_params()` and `load_params()`. Please use `save_persistables()`
    and `load_persistables()` instead.
```
那我建议，如果只想把参数存储到磁盘，用这个接口就可以，无论预测和训练fine-tune加载参数都ok。
**我也并不是很清楚，为啥将同样的功能用两个接口来实现？可能是历史遗留问题..**

2. save_inference_model

https://github.com/PaddlePaddle/Paddle/blob/88bd7e1a6194a123237129ee4e9cc5c70516946c/python/paddle/fluid/io.py#L857

这个接口，存储的模型是专门用来做预测的。有时候，我们不仅需要将模型参数存储，而且需要将模型的结构进行存储，以便用于端上预测。 所以这个接口即存储模型结构，又存储模型参数。

3. save_params
https://github.com/PaddlePaddle/Paddle/blob/88bd7e1a6194a123237129ee4e9cc5c70516946c/python/paddle/fluid/io.py#L211

这个接口功能同1类似。

4.  save_checkpoint
https://github.com/PaddlePaddle/Paddle/blob/88bd7e1a6194a123237129ee4e9cc5c70516946c/python/paddle/fluid/contrib/trainer.py#L663

这个接口看注释是用在分布式端模型参数的存储。
