### ISSUE TITLE
在使用VisualDL保存的histogram图，如何分析呢？

### ISSUE THREAD

**Issue by yeyupiaoling** [PaddlePaddle/Paddle#15178]
学生使用定义参数
```python
param_name = fluid.default_startup_program().global_block().all_parameters()[0].name
```
然后使用获取参数
```python
param = exe.run(program=fluid.default_main_program(),
                            feed=feeder.feed(data),
                            fetch_list=[param_name])
```
最后使用以下方式保存参数
```python
histogram.add_record(train_step, param.flatten())
```

最后经过训练得到的图像是：
![image](https://user-images.githubusercontent.com/26297768/50744436-2f38fb00-125e-11e9-9186-066fbe91afa7.png)

得到这个图像之后，我应该如何分析呢？能从这个图像中知道什么的？当图像出现那些情况对于的又是那种情况呢？

**Comment by JiabinYang** [comment]
横坐标是参数值分布，纵坐标是step数，每一条水平方向的先代表在该step下的参数分布情况，具体的问题您可以直接在[VisualDL](https://github.com/PaddlePaddle/VisualDL)下提问，

**Comment by yeyupiaoling** [comment]
@JiabinYang 这些我知道，我就是不知道如何使用这个图来分析什么，就那我这个图来说，当前训练的模型，是好，还是不好，依据是什么等等

**Comment by JiabinYang** [comment]
关于进一步的VisualDL的使用麻烦您在[VisualDL](https://github.com/PaddlePaddle/VisualDL/issues)的repo下提问，会有专门的同学为您解答

**Comment by yeyupiaoling** [comment]
@JiabinYang 好的，谢谢。
