### ISSUE TITLE
使用add_position_encoding在GPU上训练报错

### ISSUE THREAD

**Issue by xprincehf** [PaddlePaddle/Paddle#15205]
使用fluid.layers.add_position_encoding的时候，在CPU上可以正常训练，但是用GPU会报错
op add_position_encoding does not have kernel for data_type[float]
![image](https://user-images.githubusercontent.com/9077041/50807732-68449e80-1336-11e9-9d42-96ba80c80e39.png)

类似问题的issue有这些，该问题是否是同样bug
#14378  #12255 #14566

**Comment by wzzju** [comment]
您好！我看了下`add_position_encoding`代码中并没有有关GPU的实现。
![image](https://user-images.githubusercontent.com/17102274/50808800-397cf700-133b-11e9-91d9-dc6190907e0a.png)
代码中没有以.cu为后缀的文件。`add_position_encoding`的逻辑您可以在数据预处理时完成。

**Comment by xprincehf** [comment]
> 您好！我看了下`add_position_encoding`代码中并没有有关GPU的实现。
> ![image](https://user-images.githubusercontent.com/17102274/50808800-397cf700-133b-11e9-91d9-dc6190907e0a.png)
> 代码中没有以.cu为后缀的文件。`add_position_encoding`的逻辑您可以在数据预处理时完成。

在预处理的时候完成是什么意思？目前我是在embedding之后使用了add_position_encoding层
代码如下：

```

def db_lstm(data_reader, word, distance, **ignored):
    hidden_dim = int(global_param.get_param('hidden_dim'))
    depth = int(global_param.get_param('depth'))
    label_dict_len = int(data_reader.get_dict_size('label_dict'))
    word_emb_fixed = True if global_param.get_param('word_emb_fixed') == 'True' else False
    # 2 features
    word_param = fluid.ParamAttr(name=global_param.get_param('emb_name'),
                                 trainable=(not word_emb_fixed))
    word_embedding = fluid.layers.embedding(
        input=word,
        size=[data_reader.get_dict_size('wordemb_dict'),
              int(global_param.get_param('word_dim'))],
        dtype='float32',
        param_attr=word_param)

    distance_embedding = fluid.layers.fc(
        input=distance,
        size=int(global_param.get_param('dist_dim')),
        param_attr='distance')

    # embedding
    emb_layers = []
    for layer in [word_embedding, distance_embedding]:
        position_encoding = fluid.layers.add_position_encoding(layer, 1.0, 1.0)
        emb_layers.append(position_encoding)

    # input hidden
    hidden_0_layers = [
        fluid.layers.fc(input=emb, size=hidden_dim, act='tanh')
        for emb in emb_layers
    ]

```

**Comment by xprincehf** [comment]
> > 您好！我看了下`add_position_encoding`代码中并没有有关GPU的实现。
> > ![image](https://user-images.githubusercontent.com/17102274/50808800-397cf700-133b-11e9-91d9-dc6190907e0a.png)
> > 代码中没有以.cu为后缀的文件。`add_position_encoding`的逻辑您可以在数据预处理时完成。
> 
> 在预处理的时候完成是什么意思？目前我是在embedding之后使用了add_position_encoding层
> 代码如下：
> 
> ```
> 
> def db_lstm(data_reader, word, distance, **ignored):
>     hidden_dim = int(global_param.get_param('hidden_dim'))
>     depth = int(global_param.get_param('depth'))
>     label_dict_len = int(data_reader.get_dict_size('label_dict'))
>     word_emb_fixed = True if global_param.get_param('word_emb_fixed') == 'True' else False
>     # 2 features
>     word_param = fluid.ParamAttr(name=global_param.get_param('emb_name'),
>                                  trainable=(not word_emb_fixed))
>     word_embedding = fluid.layers.embedding(
>         input=word,
>         size=[data_reader.get_dict_size('wordemb_dict'),
>               int(global_param.get_param('word_dim'))],
>         dtype='float32',
>         param_attr=word_param)
> 
>     distance_embedding = fluid.layers.fc(
>         input=distance,
>         size=int(global_param.get_param('dist_dim')),
>         param_attr='distance')
> 
>     # embedding
>     emb_layers = []
>     for layer in [word_embedding, distance_embedding]:
>         position_encoding = fluid.layers.add_position_encoding(layer, 1.0, 1.0)
>         emb_layers.append(position_encoding)
> 
>     # input hidden
>     hidden_0_layers = [
>         fluid.layers.fc(input=emb, size=hidden_dim, act='tanh')
>         for emb in emb_layers
>     ]
> ```

错误信息如下
```
Traceback (most recent call last):
  File "paddle_model.py", line 334, in <module>
    main(sys.argv[2], use_cuda=use_gpu, is_local=in_local)
  File "paddle_model.py", line 319, in main
    train(data_generator, use_cuda=use_cuda, is_local=is_local)
  File "paddle_model.py", line 198, in train
    train_loop(fluid.default_main_program())
  File "paddle_model.py", line 166, in train_loop
    cost = exe.run(main_program, feed=feeder.feed(data), fetch_list=[avg_cost])
  File "/usr/local/lib/python2.7/site-packages/paddle/fluid/executor.py", line 472, in run
    self.executor.run(program.desc, scope, 0, True, True)
paddle.fluid.core.EnforceNotMet: op add_position_encoding does not have kernel for data_type[float]:data_layout[ANY_LAYOUT]:place[CUDAPlace(0)]:library_type[PLAIN] at [/script/paddle/paddle/fluid/framework/operator.cc:739]
PaddlePaddle Call Stacks: 
0       0x7f4a400e6826p paddle::platform::EnforceNotMet::EnforceNotMet(std::__exception_ptr::exception_ptr, char const*, int) + 486
1       0x7f4a4199f7b8p paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&) const + 1752
2       0x7f4a4199b45fp paddle::framework::OperatorBase::Run(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&) + 463
3       0x7f4a401bd410p paddle::framework::Executor::RunPreparedContext(paddle::framework::ExecutorPrepareContext*, paddle::framework::Scope*, bool, bool, bool) + 224
4       0x7f4a401bda10p paddle::framework::Executor::Run(paddle::framework::ProgramDesc const&, paddle::framework::Scope*, int, bool, bool) + 128
5       0x7f4a400d272bp
6       0x7f4a4010e44ep
7       0x7f4ae4f48631p PyEval_EvalFrameEx + 24497
8       0x7f4ae4f49bcep PyEval_EvalCodeEx + 2190
9       0x7f4ae4f4820ap PyEval_EvalFrameEx + 23434
10      0x7f4ae4f49bcep PyEval_EvalCodeEx + 2190
11      0x7f4ae4f4820ap PyEval_EvalFrameEx + 23434
12      0x7f4ae4f49bcep PyEval_EvalCodeEx + 2190
13      0x7f4ae4f4820ap PyEval_EvalFrameEx + 23434
14      0x7f4ae4f49bcep PyEval_EvalCodeEx + 2190
15      0x7f4ae4f4820ap PyEval_EvalFrameEx + 23434
16      0x7f4ae4f49bcep PyEval_EvalCodeEx + 2190
17      0x7f4ae4f49ce2p PyEval_EvalCode + 50
18      0x7f4ae4f699e0p PyRun_FileExFlags + 176
19      0x7f4ae4f69bbfp PyRun_SimpleFileExFlags + 239
20      0x7f4ae4f7f454p Py_Main + 3188
21      0x7f4ae4233cddp __libc_start_main + 253
22            0x400649p

*********************error messages********************
```

**Comment by xprincehf** [comment]
> 您好！我看了下`add_position_encoding`代码中并没有有关GPU的实现。
> ![image](https://user-images.githubusercontent.com/17102274/50808800-397cf700-133b-11e9-91d9-dc6190907e0a.png)
> 代码中没有以.cu为后缀的文件。`add_position_encoding`的逻辑您可以在数据预处理时完成。

是否因为该算子不支持GPU模式，所以在使用GPU进行训练的时候导致了异常？可以设置部分算子单独使用CPU进行训练吗？

**Comment by wzzju** [comment]
> > 您好！我看了下`add_position_encoding`代码中并没有有关GPU的实现。
> > ![image](https://user-images.githubusercontent.com/17102274/50808800-397cf700-133b-11e9-91d9-dc6190907e0a.png)
> > 代码中没有以.cu为后缀的文件。`add_position_encoding`的逻辑您可以在数据预处理时完成。
> 
> 在预处理的时候完成是什么意思？目前我是在embedding之后使用了add_position_encoding层
> 代码如下：
> 
> ```
> 
> def db_lstm(data_reader, word, distance, **ignored):
>     hidden_dim = int(global_param.get_param('hidden_dim'))
>     depth = int(global_param.get_param('depth'))
>     label_dict_len = int(data_reader.get_dict_size('label_dict'))
>     word_emb_fixed = True if global_param.get_param('word_emb_fixed') == 'True' else False
>     # 2 features
>     word_param = fluid.ParamAttr(name=global_param.get_param('emb_name'),
>                                  trainable=(not word_emb_fixed))
>     word_embedding = fluid.layers.embedding(
>         input=word,
>         size=[data_reader.get_dict_size('wordemb_dict'),
>               int(global_param.get_param('word_dim'))],
>         dtype='float32',
>         param_attr=word_param)
> 
>     distance_embedding = fluid.layers.fc(
>         input=distance,
>         size=int(global_param.get_param('dist_dim')),
>         param_attr='distance')
> 
>     # embedding
>     emb_layers = []
>     for layer in [word_embedding, distance_embedding]:
>         position_encoding = fluid.layers.add_position_encoding(layer, 1.0, 1.0)
>         emb_layers.append(position_encoding)
> 
>     # input hidden
>     hidden_0_layers = [
>         fluid.layers.fc(input=emb, size=hidden_dim, act='tanh')
>         for emb in emb_layers
>     ]
> ```

您好！add_position_encoding的操作就是对输入数据做了一些简单的变换，我的意思是您可以选择在预处理时对数据做下这些变换。

**Comment by wzzju** [comment]
> > 您好！我看了下`add_position_encoding`代码中并没有有关GPU的实现。
> > ![image](https://user-images.githubusercontent.com/17102274/50808800-397cf700-133b-11e9-91d9-dc6190907e0a.png)
> > 代码中没有以.cu为后缀的文件。`add_position_encoding`的逻辑您可以在数据预处理时完成。
> 
> 是否因为该算子不支持GPU模式，所以在使用GPU进行训练的时候导致了异常？可以设置部分算子单独使用CPU进行训练吗？

该OP确实不支持在GPU上运行，但是这个op的编写者当初没有设计好，所以有些bug。我们框架的设计是这样的，如果某个op在GPU上没有实现的话，该op会自动选择在CPU上运行。您可以按照下面方式修改一下即可运行：
![image](https://user-images.githubusercontent.com/17102274/50814829-f4b28980-1355-11e9-981a-d08602d90ed7.png)
