### ISSUE TITLE
IfElse使用出错，ConditionalBlockGradInferShape

### ISSUE THREAD

**Issue by forpure** [PaddlePaddle/Paddle#15225]
<img width="670" alt="image" src="https://user-images.githubusercontent.com/11329225/50831039-94870c00-1384-11e9-9dc5-35b006d4f36e.png">
按照API方式使用IfElse，对输入数据分开算loss，最后执行时报如下错误：
<img width="1320" alt="image" src="https://user-images.githubusercontent.com/11329225/50831139-e92a8700-1384-11e9-8897-7bc5764ee79f.png">
请问下可能是哪里有问题呢？

**Comment by jerrywgz** [comment]
请问你if else的使用逻辑是什么样的？方便贴下部分代码吗

**Comment by forpure** [comment]
> 请问你if else的使用逻辑是什么样的？方便贴下部分代码吗

方便发下你的hi吗，我私发给你

**Comment by jerrywgz** [comment]
wangguanzhong

**Comment by oshixiaoxiliu** [comment]
请问这个问题解决了么？

**Comment by irukawang** [comment]
请问这个问题解决了么
