### ISSUE TITLE
paddle.fluid.LoDTensor数据可以转为numba.cuda.cudadrv.devicearray.DeviceNDArray数据结构吗

### ISSUE THREAD

**Issue by yxnal** [PaddlePaddle/Paddle#15221]
paddle.fluid.LoDTensor数据可以转为numba.cuda.cudadrv.devicearray.DeviceNDArray数据结构吗？

**Comment by wzzju** [comment]
您好！您可以先将paddle.fluid.LoDTensor转成numpy数组，然后再通过numpy数组转成您想要的格式。paddle.fluid.LoDTensor支持向numpy数组的转换。

**Comment by yxnal** [comment]
感谢你的回答！我理解您提供的方法是在cpu内存中的操作吧？如果我通过如下方式创建在gpu内存中的LoDTensor数据tensor：
place = fluid.CUDAPlace(0)
tensor = fluid.LoDTensor()
tensor.set([[1]], place)
tensor.set_recursive_sequence_lengths([[1]])

然后，想要获取tensor首元素的gpu地址,请问有获取的方法吗？
例如在torch中的获取方法：
torch_tensor = torch.cuda.FloatTensor(5, 5)     #torch_tensor在gpu内存中创建的torch的tensor数据结构
ptr = torch_tensor.data_ptr()          #ptr为torch_tensor首元素的gpu内存地址。

获取tensor首元素的gpu地址的目的是为了进行如下操作：
ctx = numba.cuda.current_context()

memptr = numba.cuda.cudadrv.driver.MemoryPointer(ctx, ctypes.c_uint64(ptr), tensor.numel() * tensor.element_size())   # memory pointer object for tensor data

arr = numba.cuda.devicearray.DeviceNDArray(shape=(5, 5), strides=tuple(4*x for x in tensor.stride()), dtype=np.dtype(np.float32), gpu_data=memptr)  # ndarray representation of our tensor 

最终的诉求是想了解，paddle是否支持 numba cuda array_interface

**Comment by wzzju** [comment]
您可以使用`fluid.global_scope().find_var(var_name).get_tensor()`来获取tensor首元素的gpu地址，但是这只针对于网络的参数变量可以这样使用，对于中间结果变量不能这样使用。对于“paddle是否支持 numba cuda array_interface？”这个问题，回答应该是“不支持的”，至少之前还没有见过这样使用的。

**Comment by yxnal** [comment]
感谢解答！您提供的fluid.global_scope().find_var(var_name).get_tensor()方法是否支持，通过paddle的create_tensor、create_parameter、create_global_var这三种方法创建的数据结构？
还有这个方法只支持网络参数变量吗，支持训练数据吗？

**Comment by wzzju** [comment]
> 感谢解答！您提供的fluid.global_scope().find_var(var_name).get_tensor()方法是否支持，通过paddle的create_tensor、create_parameter、create_global_var这三种方法创建的数据结构？
> 还有这个方法只支持网络参数变量吗，支持训练数据吗？

您好！`fluid.global_scope().find_var(var_name).get_tensor()`只支持paddle中persistable的Variable。暂不支持 numba cuda array_interface。
