### ISSUE TITLE
如何在本地运行所有的Operator的单元测试？

### ISSUE THREAD

**Issue by zzhzz** [PaddlePaddle/Paddle#15233]
我提交了 PR#15217 但是PR_CI_python35运行单测时在一个与我提交代码无关的位置出错了。我希望在本地复现错误，确定错误的问题。请问有什么办法可以在编译完成后直接启动所有的单测？

**Comment by jerrywgz** [comment]
如果是与代码无关的位置出错我们这边相关的负责人会进行处理，启动所有单测可以用ctest -R
