### ISSUE TITLE
提交集群任务失败

### ISSUE THREAD

**Issue by AWSWXY** [PaddlePaddle/Paddle#15234]
提交集群任务返回None

**Comment by jerrywgz** [comment]
麻烦贴出些log吧

**Comment by AWSWXY** [comment]
connect to receiver:  yq01-idl-gpu-offline14.yq01.baidu.com:9296
compressing thirdparty files
finished to pack request
starting to submit to server
None

**Comment by AWSWXY** [comment]
![image](https://user-images.githubusercontent.com/18156360/50875712-97c1dc80-1404-11e9-8647-ccf656e12a74.png)

**Comment by typhoonzero** [comment]
v2 job用8090, 8091端口
