### ISSUE TITLE
Check failed: outG && outV && inV1 && inV2 && inG1 && inG2

### ISSUE THREAD

**Issue by EchoCX** [PaddlePaddle/Paddle#15243]
I0109 17:02:55.147073 18162 Util.cpp:166] commandline: --use_gpu=False --trainer_count=1
(1000002, 128)
[INFO 2019-01-09 17:04:00,371 train.py:73] create a sequence_conv_pool whose context width is 3.
[INFO 2019-01-09 17:04:00,374 train.py:73] create a sequence_conv_pool whose context width is 3.
I0109 17:04:05.276542 18162 GradientMachine.cpp:94] Initing parameters..
I0109 17:04:45.933693 18162 GradientMachine.cpp:101] Init parameters done.
F0109 17:04:49.682454 18162 CosSimLayer.cpp:79] Check failed: outG && outV && inV1 && inV2 && inG1 && inG2
*** Check failure stack trace: ***
@ 0x7fedb7ecf9ad google::LogMessage::Fail()
@ 0x7fedb7ed345c google::LogMessage::SendToLog()
@ 0x7fedb7ecf4d3 google::LogMessage::Flush()
@ 0x7fedb7ed496e google::LogMessageFatal::~LogMessageFatal()
@ 0x7fedb7c4fa38 paddle::CosSimLayer::backward()
@ 0x7fedb7c85522 paddle::NeuralNetwork::backward()
@ 0x7fedb7eab994 GradientMachine::forwardBackward()
@ 0x7fedb7b29c99 _wrap_GradientMachine_forwardBackward
@ 0x7fee1c9f2426 PyEval_EvalFrameEx
@ 0x7fee1c9f321d PyEval_EvalCodeEx
@ 0x7fee1c9f14f1 PyEval_EvalFrameEx
@ 0x7fee1c9f321d PyEval_EvalCodeEx
@ 0x7fee1c9f14f1 PyEval_EvalFrameEx
@ 0x7fee1c9f321d PyEval_EvalCodeEx
@ 0x7fee1c9f14f1 PyEval_EvalFrameEx
@ 0x7fee1c9f321d PyEval_EvalCodeEx
@ 0x7fee1c9f14f1 PyEval_EvalFrameEx
@ 0x7fee1c9f321d PyEval_EvalCodeEx
@ 0x7fee1c9f3352 PyEval_EvalCode
@ 0x7fee1ca1df22 PyRun_FileExFlags
@ 0x7fee1ca1f459 PyRun_SimpleFileExFlags
@ 0x7fee1ca34e9d Py_Main
@ 0x7fee1bc36bd5 __libc_start_main
@ 0x4007a1 (unknown)
@ (nil) (unknown)
Aborted (core dumped)

**Comment by EchoCX** [comment]
# input layer
    unit_emb = paddle.layer.data(name='unit', type=paddle.data_type.dense_vector(emb_size))
    pos_title = paddle.layer.data(name='pos_title', type=paddle.data_type.integer_value_sequence(vocab_size))
    neg_title = paddle.layer.data(name='neg_title', type=paddle.data_type.integer_value_sequence(vocab_size))
    label = paddle.layer.data(name='label', type=paddle.data_type.integer_value(1))

    # embedding layer
    #emb_para = paddle.attr.Param(name='emb', initial_std=0.0, is_static=emb_done)
    pos_title_emb = paddle.layer.embedding(input=pos_title, size=256, param_attr=ParamAttr(name="pos_emb.w"))
    neg_title_emb = paddle.layer.embedding(input=neg_title, size=256, param_attr=ParamAttr(name="neg_emb.w"))

    # cnn layer
    #unit_cnn = create_cnn(unit_emb, "unit")
    pos_title_cnn = create_cnn(pos_title_emb, "pos")
    neg_title_cnn = create_cnn(neg_title_emb, "neg")

    # cosine
    left_score = paddle.layer.cos_sim(unit_emb, pos_title_cnn)
    right_score = paddle.layer.cos_sim(unit_emb, neg_title_cnn)
    cost = paddle.layer.rank_cost(left_score, right_score, label=label)

**Comment by jerrywgz** [comment]
请问您使用的是v2版本吗

**Comment by EchoCX** [comment]
def create_cnn(emb, prefix):
    def create_conv(context_len, hidden_size, prefix):
        key = "%s_%d_%d" % (prefix, context_len, hidden_size)
        conv = paddle.networks.sequence_conv_pool(
            input=emb,
            context_len=context_len,
            hidden_size=hidden_size,
            # set parameter attr for parameter sharing
            context_proj_param_attr=ParamAttr(name=key + "_contex_proj.w"),
            fc_param_attr=ParamAttr(name=key + "_fc.w"),
            fc_bias_attr=ParamAttr(name=key + "_fc.b"),
            pool_bias_attr=ParamAttr(name=key + "_pool.b"))
        return conv
    
    logger.info("create a sequence_conv_pool whose context width is 3.")
    conv_3 = create_conv(3, 128, prefix+"_cnn")
    return conv_3

**Comment by EchoCX** [comment]
> 请问您使用的是v2版本吗

是的

**Comment by jerrywgz** [comment]
能否转为fluid，现在v2版本我们已经不再维护了

**Comment by EchoCX** [comment]
> 能否转为fluid，现在v2版本我们已经不再维护了

这里的报错是转了fluid就可以解决么？

**Comment by jerrywgz** [comment]
大部分问题在fluid下是可以解决的，如果还有问题也会有相应负责人处理

**Comment by EchoCX** [comment]
> 大部分问题在fluid下是可以解决的，如果还有问题也会有相应负责人处理

fluid的API求一下连接

**Comment by jerrywgz** [comment]
http://www.paddlepaddle.org/documentation/docs/zh/1.2/api_cn/layers_cn.html

**Comment by wanghaoshuang** [comment]
该issue长期未回复，且问题有替换方案，暂时将该issue关闭。如果需要，请随时reopen. 谢谢。
