### ISSUE TITLE
关于模型初始化顺序

### ISSUE THREAD

**Issue by zhangyong15** [PaddlePaddle/Paddle#1525]
1.  用已经训练好的模型进行初始化
<img width="992" alt="0bb31d98b851c9b867757905ed26f2e3" src="https://cloud.githubusercontent.com/assets/22140712/23505101/33990cbc-ff7d-11e6-9c4c-637e77596d20.png">
2. 每一层又可以选择初始化方式。
<img width="1039" alt="d700c3316db609b25cbd8660ea36db9c" src="https://cloud.githubusercontent.com/assets/22140712/23505168/6c0c5680-ff7d-11e6-82eb-63dd102cbf59.png">

如果我**只想初始化一部分**网络参数，比如layer1用已训练好的模型，layer2用随机值进行初始化，是否只需要设置init_model_path, 然后再layer2网络配置中写好初始化方式，这样能够得到预期么？

**Comment by hiahiahu** [comment]
init_model_path里面只提供layer1的参数，其他layer参数缺损，命令行设置--load_missing_parameter_strategy='rand' 就行了
