### ISSUE TITLE
embedding使用is_distributed=True出错

### ISSUE THREAD

**Issue by forpure** [PaddlePaddle/Paddle#15263]
def sparse_embedding_layer(input):
            """
            sparse_embedding_layer
            """
            emb = fluid.layers.embedding(
                input=input, dtype='float32', size=[SPARSE_FEATURE_DIM, EMBEDDING_DIM],
                param_attr=sparse_emb_param, is_sparse=True, is_distributed=True)
            return fluid.layers.sequence_pool(input=emb, pool_type='average')

如上加上is_distributed=True参数后，出现如下错误：
File "train.py", line 135, in train_parallel
    avg_loss_value = parallel_exe.run([avg_cost.name])
  File "/home/disk1/normandy/maybach/app-user-20190110150158-28408/workspace/python27-gcc482/lib/python2.7/site-packages/paddle/fluid/parallel_executor.py", line 272, in run
    self.executor.run(fetch_list, fetch_var_name)
paddle.fluid.core.EnforceNotMet: holder_ should not be null
Tensor holds no memory. Call Tensor::mutable_data first. at [/script/paddle/paddle/fluid/framework/tensor.cc:22]
PaddlePaddle Call Stacks: 
0       0x7fcbf5a233c6p paddle::platform::EnforceNotMet::EnforceNotMet(std::__exception_ptr::exception_ptr, char const*, int) + 486
1       0x7fcbf6833fbbp paddle::framework::Tensor::check_memory_size() const + 219
2       0x7fcbf5b3a159p long const* paddle::framework::Tensor::data<long>() const + 25
3       0x7fcbf6142e24p paddle::operators::SplitIdsOpKernel<paddle::platform::CPUPlace, long>::Compute(paddle::framework::ExecutionContext const&) const + 628
4       0x7fcbf6144163p std::_Function_handler<void (paddle::framework::ExecutionContext const&), paddle::framework::OpKernelRegistrarFunctor<paddle::platform::CPUPlace, false, 0ul, paddle::operators::SplitIdsOpKernel<paddle::platform::CPUPlace, long>, paddle::operators::SplitIdsOpKernel<paddle::platform::CPUPlace, float> >::operator()(char const*, char const*) const::{lambda(paddle::framework::ExecutionContext const&)#1}>::_M_invoke(std::_Any_data const&, paddle::framework::ExecutionContext const&) + 35
5       0x7fcbf6801503p paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&) const + 531
6       0x7fcbf67fd698p paddle::framework::OperatorBase::Run(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&) + 232
7       0x7fcbf67c9cb4p
8       0x7fcbf67c97c0p paddle::framework::details::ComputationOpHandle::RunImpl() + 128
9       0x7fcbf67cbbfcp paddle::framework::details::OpHandleBase::Run(bool) + 28
10      0x7fcbf673d59dp
11      0x7fcbf61222b3p std::_Function_handler<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> (), std::__future_base::_Task_setter<std::unique_ptr<std::__future_base::_Result<void>, std::__future_base::_Result_base::_Deleter>, void> >::_M_invoke(std::_Any_data const&) + 35
12      0x7fcbf60f1937p std::__future_base::_State_base::_M_do_set(std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> ()>&, bool&) + 39
13      0x7fcc9f4f5973p pthread_once + 83
14      0x7fcbf673c282p
15      0x7fcbf60f2df4p ThreadPool::ThreadPool(unsigned long)::{lambda()#1}::operator()() const + 404
16      0x7fcc01c5f8a0p
17      0x7fcc9f4f01c3p
18      0x7fcc9eb1812dp clone + 109

**Comment by jacquesqiao** [comment]
看起来是因为输入数据为空，现在是什么情况？

**Comment by appleappleorange** [comment]
因为长时间未回复，此issue现在暂时关闭，如有需要可以重新open
