### ISSUE TITLE
输入等于输出的mlp的模型save问题

### ISSUE THREAD

**Issue by wangty163** [PaddlePaddle/Paddle#15270]
Thank you for contributing to PaddlePaddle. Submitting an issue is a great help for us.
Both Chinese and English issues are welcome.

It's hard to solve a problem when important details are missing.
Before submitting the issue, look over the following criteria before handing your request in.

- [x] Was there a similar issue submitted or resolved before ? You could search issue in the github.
- [x] Did you retrieve your issue from widespread search engines ?
- [x] Is my description of the issue clear enough to reproduce this problem?
   * If some errors occurred, we need details about `how do you run your code?`, `what system do you use?`, `Are you using GPU or not?`, etc.
   * If you use an recording [asciinema](https://asciinema.org/) to show what you are doing to make it happen, that's awesome! We could help you solve the problem more quickly.
- [x] Is my description of the issue use the github markdown correctly?
   * Please use the proper markdown syntaxes for styling all forms of writing, e.g, source code, error information, etc.
   * Check out [this page](https://guides.github.com/features/mastering-markdown/) to find out much more about markdown.

**Comment by wangty163** [comment]
```
# 输入tensor
x = fluid.layers.data(name="x", shape=[10], dtype='float32')
# 模型的输出等于输入
y = x

# 模型保存逻辑
fluid.io.save_inference_model(
    feeded_var_names=[x.name],
    target_vars=[y],
    .....
)

# 模型保存时报错
ValueError: The target variable must have an associated operator that generates it.
```





这样的模型我需要怎么保存？

**Comment by wangguibao** [comment]
可以像这样用一个assign layer

```
x = fluid.layers.data(name="x", shape=[10], dtype='float32')
y = fluid.layers.create_tensor(dtype='float32')
fluid.layers.assign(x, y)

place = fluid.CPUPlace()
executor = fluid.Executor(place)

fluid.io.save_inference_model('model/', [x.name], [y], executor)
```
