### ISSUE TITLE
paddle inference库多线程预估结果错误

### ISSUE THREAD

**Issue by dhx1989** [PaddlePaddle/Paddle#15274]
版本： v1.1.0， cpu openblas ， c++预测

多线程预估版本实现参考demo实现

1. 单线程版本输入n个tensor，输出n个不同结果
2. 多线程版本输入和单线程一样tensor，输出结果与单线程结果不同， 概率发生

可以稳定复现此问题

**Comment by wangguibao** [comment]
跟用户线下在看
