### ISSUE TITLE
高维embedding，小数据集上训练成功，大数据集上出错

### ISSUE THREAD

**Issue by forpure** [PaddlePaddle/Paddle#15272]
网络中embedding层dim约530w*16，在小数据集上用户一个节点测试跑执行成功，但换到大数据集50个节点跑执行失败，错误信息：
++ /home/disk1/normandy/maybach/app-user-20190110210313-61/workspace/python27-gcc482/bin/python train.py
get_pserver_program() is deprecated, call get_pserver_programs() to get pserver main and startup in a single call.get_startup_program() is deprecated, call get_pserver_programs() to get pserver main and startup in a single call.passing pserver_program to get_startup_program() is deprecated, you can use new API get_pserver_programs() to get both pserver main program and startup program.E0110 21:13:27.756530765   13541 tcp_server_posix.cc:64]     check for SO_REUSEPORT: {"created":"@1547126007.756506863","description":"OS Error","errno":92,"file":"src/core/lib/iomgr/socket_utils_common_posix.cc","file_line":169,"os_error":"Protocol not available","syscall":"setsockopt(SO_REUSEPORT)"}
I0110 21:13:27.759591 13541 grpc_server.cc:290] Server listening on 10.90.121.23:62004 selected port: 62004
F0110 21:31:50.565829 32254 listen_and_serv_op.cc:73] run sub program:3 error holder_ should not be null
Tensor holds no memory. Call Tensor::mutable_data first. at [/script/paddle/paddle/fluid/framework/tensor.cc:22]
PaddlePaddle Call Stacks: 
0       0x7f16364083c6p paddle::platform::EnforceNotMet::EnforceNotMet(std::__exception_ptr::exception_ptr, char const*, int) + 486
1       0x7f1637218fbbp paddle::framework::Tensor::check_memory_size() const + 219
2       0x7f16367605abp paddle::operators::ClipKernel<paddle::platform::CPUDeviceContext, float>::Compute(paddle::framework::ExecutionContext const&) const + 1307
3       0x7f1636760e63p std::_Function_handler<void (paddle::framework::ExecutionContext const&), paddle::framework::OpKernelRegistrarFunctor<paddle::platform::CPUPlace, false, 0ul, paddle::operators::ClipKernel<paddle::platform::CPUDeviceContext, float> >::operator()(char const*, char const*) const::{lambda(paddle::framework::ExecutionContext const&)#1}>::_M_invoke(std::_Any_data const&, paddle::framework::ExecutionContext const&) + 35
4       0x7f16371e6503p paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&) const + 531
5       0x7f16371e2698p paddle::framework::OperatorBase::Run(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&) + 232
6       0x7f16364d5460p paddle::framework::Executor::RunPreparedContext(paddle::framework::ExecutorPrepareContext*, paddle::framework::Scope*, bool, bool, bool) + 224
7       0x7f1636b01182p
8       0x7f1636b083cap std::_Function_handler<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> (), std::__future_base::_Task_setter<std::unique_ptr<std::__future_base::_Result<std::unique_ptr<paddle::platform::EnforceNotMet, std::default_delete<paddle::platform::EnforceNotMet> > >, std::__future_base::_Result_base::_Deleter>, std::unique_ptr<paddle::platform::EnforceNotMet, std::default_delete<paddle::platform::EnforceNotMet> > > >::_M_invoke(std::_Any_data const&) + 42
9       0x7f1636ad6937p std::__future_base::_State_base::_M_do_set(std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> ()>&, bool&) + 39
10      0x7f16b5e07973p pthread_once + 83
11      0x7f1636b003d2p
12      0x7f1637213639p paddle::framework::ThreadPool::TaskLoop() + 1689
13      0x7f16426448a0p
14      0x7f16b5e021c3p
15      0x7f16b542a12dp clone + 109
*** Check failure stack trace: ***
F0110 21:31:50.565945 32265 listen_and_serv_op.cc:73] run sub program:13 error holder_ should not be null
Tensor holds no memory. Call Tensor::mutable_data first. at [/script/paddle/paddle/fluid/framework/tensor.cc:22]
PaddlePaddle Call Stacks: 
0       0x7f16364083c6p paddle::platform::EnforceNotMet::EnforceNotMet(std::__exception_ptr::exception_ptr, char const*, int) + 486
1       0x7f1637218fbbp paddle::framework::Tensor::check_memory_size() const + 219
2       0x7f16367605abp paddle::operators::ClipKernel<paddle::platform::CPUDeviceContext, float>::Compute(paddle::framework::ExecutionContext const&) const + 1307
3       0x7f1636760e63p std::_Function_handler<void (paddle::framework::ExecutionContext const&), paddle::framework::OpKernelRegistrarFunctor<paddle::platform::CPUPlace, false, 0ul, paddle::operators::ClipKernel<paddle::platform::CPUDeviceContext, float> >::operator()(char const*, char const*) const::{lambda(paddle::framework::ExecutionContext const&)#1}>::_M_invoke(std::_Any_data const&, paddle::framework::ExecutionContext const&) + 35
4       0x7f16371e6503p paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&) const + 531
5       0x7f16371e2698p paddle::framework::OperatorBase::Run(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&) + 232
6       0x7f16364d5460p paddle::framework::Executor::RunPreparedContext(paddle::framework::ExecutorPrepareContext*, paddle::framework::Scope*, bool, bool, bool) + 224
7       0x7f1636b01182p
8       0x7f1636b083cap std::_Function_handler<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> (), std::__future_base::_Task_setter<std::unique_ptr<std::__future_base::_Result<std::unique_ptr<paddle::platform::EnforceNotMet, std::default_delete<paddle::platform::EnforceNotMet> > >, std::__future_base::_Result_base::_Deleter>, std::unique_ptr<paddle::platform::EnforceNotMet, std::default_delete<paddle::platform::EnforceNotMet> > > >::_M_invoke(std::_Any_data const&) + 42
9       0x7f1636ad6937p std::__future_base::_State_base::_M_do_set(std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> ()>&, bool&) + 39
10      0x7f16b5e07973p pthread_once + 83
11      0x7f1636b003d2p
12      0x7f1637213639p paddle::framework::ThreadPool::TaskLoop() + 1689
13      0x7f16426448a0p
14      0x7f16b5e021c3p
15      0x7f16b542a12dp clone + 109
*** Check failure stack trace: ***
    @     0x7f163648fcdd  google::LogMessage::Fail()
    @     0x7f163648fcdd  google::LogMessage::Fail()
    @     0x7f163649378c  google::LogMessage::SendToLog()
    @     0x7f163649378c  google::LogMessage::SendToLog()
    @     0x7f163648f803  google::LogMessage::Flush()
    @     0x7f163648f803  google::LogMessage::Flush()
    @     0x7f1636494c9e  google::LogMessageFatal::~LogMessageFatal()
    @     0x7f1636494c9e  google::LogMessageFatal::~LogMessageFatal()
    @     0x7f1636b01220  _ZNSt17_Function_handlerIFSt10unique_ptrIN6paddle8platform13EnforceNotMetESt14default_deleteIS3_EEvESt17reference_wrapperISt12_Bind_simpleIFS8_IZNS1_9framework10ThreadPool18RunAndGetExceptionIZNS1_9operatorsL21ParallelExecuteBlocksERKSt6vectorImSaImEEPNSA_8ExecutorERKSE_ISt10shared_ptrINSA_22ExecutorPrepareContextEESaISN_EEPNSA_11ProgramDescEPNSA_5ScopeEEUlvE_EESt6futureIS6_ET_EUlvE_EvEEEE9_M_invokeERKSt9_Any_data
    @     0x7f1636b01220  _ZNSt17_Function_handlerIFSt10unique_ptrIN6paddle8platform13EnforceNotMetESt14default_deleteIS3_EEvESt17reference_wrapperISt12_Bind_simpleIFS8_IZNS1_9framework10ThreadPool18RunAndGetExceptionIZNS1_9operatorsL21ParallelExecuteBlocksERKSt6vectorImSaImEEPNSA_8ExecutorERKSE_ISt10shared_ptrINSA_22ExecutorPrepareContextEESaISN_EEPNSA_11ProgramDescEPNSA_5ScopeEEUlvE_EESt6futureIS6_ET_EUlvE_EvEEEE9_M_invokeERKSt9_Any_data
    @     0x7f1636b083ca  std::_Function_handler<>::_M_invoke()
    @     0x7f1636b083ca  std::_Function_handler<>::_M_invoke()
    @     0x7f1636ad6937  std::__future_base::_State_base::_M_do_set()
    @     0x7f1636ad6937  std::__future_base::_State_base::_M_do_set()
    @     0x7f16b5e07973  __GI___pthread_once
    @     0x7f16b5e07973  __GI___pthread_once
    @     0x7f1636b003d2  _ZNSt13__future_base11_Task_stateIZN6paddle9framework10ThreadPool18RunAndGetExceptionIZNS1_9operatorsL21ParallelExecuteBlocksERKSt6vectorImSaImEEPNS2_8ExecutorERKS6_ISt10shared_ptrINS2_22ExecutorPrepareContextEESaISF_EEPNS2_11ProgramDescEPNS2_5ScopeEEUlvE_EESt6futureISt10unique_ptrINS1_8platform13EnforceNotMetESt14default_deleteISS_EEET_EUlvE_SaIiEFSV_vEE6_M_runEv
    @     0x7f1636b003d2  _ZNSt13__future_base11_Task_stateIZN6paddle9framework10ThreadPool18RunAndGetExceptionIZNS1_9operatorsL21ParallelExecuteBlocksERKSt6vectorImSaImEEPNS2_8ExecutorERKS6_ISt10shared_ptrINS2_22ExecutorPrepareContextEESaISF_EEPNS2_11ProgramDescEPNS2_5ScopeEEUlvE_EESt6futureISt10unique_ptrINS1_8platform13EnforceNotMetESt14default_deleteISS_EEET_EUlvE_SaIiEFSV_vEE6_M_runEv
    @     0x7f1637213639  paddle::framework::ThreadPool::TaskLoop()
    @     0x7f1637213639  paddle::framework::ThreadPool::TaskLoop()
    @     0x7f16426448a0  execute_native_thread_routine
    @     0x7f16426448a0  execute_native_thread_routine
    @     0x7f16b5e021c3  start_thread
    @     0x7f16b5e021c3  start_thread
    @     0x7f16b542a12d  __clone
    @     0x7f16b542a12d  __clone
    @              (nil)  (unknown)

**Comment by wangguibao** [comment]
请 @jacquesqiao 在帮忙看
