### ISSUE TITLE
resize_nearest与tensorflow.image.resize_nearest_neighbor差异

### ISSUE THREAD

**Issue by jiangjiajun** [PaddlePaddle/Paddle#15276]
两个接口的定义分别为
```
paddle.fluid.layers.resize_nearest(input, out_shape=None, scale=None, name=None, actual_shape=None)
```

```
tensorflow.image.resize_nearest_neighbor( images, size, align_corners=False, name=None)
```
测试中发现，同样的输入，只有在tensorflow接口里align_corners=True的前提下，输出才无diff

请问是否有方法，在align_corners=False的情况下，使PaddlePaddle和Tensorflow得到同样的输出结果呢

**Comment by heavengate** [comment]
对比了下tensorflow的代码，align_corners为True时是对下标值取round，为False时是对下标值取floor，当前实现是按取round的方式，目前还不支持取floor这种方式，当前版本暂时不能支持align_corners=False的情况了，我们会尽快增加这个模式，预计可能要到下一个版本生效了。
