### ISSUE TITLE
训练出core

### ISSUE THREAD

**Issue by EchoCX** [PaddlePaddle/Paddle#15285]
*** Aborted at 1547189448 (unix time) try "date -d @1547189448" if you are using GNU date ***
PC: @                0x0 (unknown)
*** SIGILL (@0x7f4cf288a002) received by PID 14906 (TID 0x7f4d13b58700) from PID 18446744073483624450; stack trace: ***
    @       0x318b20f500 (unknown)
    @     0x7f4cf288a002 paddle::framework::VisitDataType<>()
    @     0x7f4cf28722ff paddle::operators::math::set_constant_with_place<>()
    @     0x7f4cf1e3d99b paddle::operators::FillConstantOp::RunImpl()
    @     0x7f4cf2825b58 paddle::framework::OperatorBase::Run()
    @     0x7f4cf1c740fb paddle::framework::Executor::RunPreparedContext()
    @     0x7f4cf1c74ee0 paddle::framework::Executor::Run()
    @     0x7f4cf1b958bd _ZZN8pybind1112cpp_function10initializeIZN6paddle6pybindL13pybind11_initEvEUlRNS2_9framework8ExecutorERKNS4_11ProgramDescEPNS4_5ScopeEibbE63_vIS6_S9_SB_ibbEINS_4nameENS_9is_methodENS_7siblingEEEEvOT_PFT0_DpT1_EDpRKT2_ENUlRNS_6detail13function_callEE1_4_FUNEST_
    @     0x7f4cf1be5cb4 pybind11::cpp_function::dispatcher()
    @     0x7f4d13c4f3e4 PyEval_EvalFrameEx
    @     0x7f4d13c50130 PyEval_EvalCodeEx
    @     0x7f4d13c4e4a1 PyEval_EvalFrameEx
    @     0x7f4d13c50130 PyEval_EvalCodeEx
    @     0x7f4d13c4e4a1 PyEval_EvalFrameEx
    @     0x7f4d13c50130 PyEval_EvalCodeEx
    @     0x7f4d13c4e4a1 PyEval_EvalFrameEx
    @     0x7f4d13c50130 PyEval_EvalCodeEx
    @     0x7f4d13c4e4a1 PyEval_EvalFrameEx
    @     0x7f4d13c50130 PyEval_EvalCodeEx
    @     0x7f4d13c50242 PyEval_EvalCode
    @     0x7f4d13c6a62c run_mod
    @     0x7f4d13c6a700 PyRun_FileExFlags
    @     0x7f4d13c6bc0c PyRun_SimpleFileExFlags
    @     0x7f4d13c7d4cc Py_Main
    @       0x318ae1ecdd (unknown)

**Comment by EchoCX** [comment]
unit = fluid.layers.data(name='unit_emb', shape=[128], dtype='float32')
    pos = fluid.layers.data(name='pos_ids', shape=[1], dtype='int64', lod_level=1)
    neg = fluid.layers.data(name='neg_ids', shape=[1], dtype='int64', lod_level=1)
    label = fluid.layers.data(name='label', shape=[1], dtype='int64')
    
    pos_emb = fluid.layers.embedding(input=pos, size=[dict_dim, 128], is_sparse=True)
    neg_emb = fluid.layers.embedding(input=neg, size=[dict_dim, 128], is_sparse=True)

    pos_pool = fluid.layers.sequence_pool(input=pos_emb, pool_type='sum')
    neg_pool = fluid.layers.sequence_pool(input=neg_emb, pool_type='sum')

    pos_fc = fluid.layers.fc(input=pos_pool, size=128)
    neg_fc = fluid.layers.fc(input=neg_pool, size=128)

    left_score = fluid.layers.cos_sim(unit, pos_fc)
    right_score = fluid.layers.cos_sim(unit, neg_fc)
    avg_cost = get_loss(left_score, right_score)

**Comment by wangguibao** [comment]
怀疑指令集不兼容，请用户提供机器和运行环境看下现场，截至目前未收到回复。

**Comment by wangguibao** [comment]
截至今天用户未反馈。先关闭了，如有需要可随时重新打开
