### ISSUE TITLE
rnn接embeding时出错 paddle.fluid.core.EnforceNotMet: Enforce failed. Expected ids_dims[ids_rank - 1] == 1, but received ids_dims[ids_rank - 1]:-1 != 1:1.

### ISSUE THREAD

**Issue by sonofaeolus** [PaddlePaddle/Paddle#15289]
为使您的问题得到快速解决，在建立Issue前，请您先通过如下方式搜索是否有相似问题:【搜索issue关键字】【使用labels筛选】【官方文档】

建立issue时，为快速解决问题，请您根据使用情况给出如下信息：
- 标题：简洁、精准描述您的问题，例如“ssd 模型前置lstm报错  ”
- 版本、环境信息：
    1）PaddlePaddle版本：请提供PaddlePaddle版本号，例如1.1或CommitID
    2）CPU：请提供CPU型号，MKL/OpenBlas/MKLDNN/等数学库的使用情况
    3）GPU：请提供GPU型号，CUDA和CUDNN版本号
    4）系统环境：请说明系统类型、版本（例如Mac OS 10.14），Python版本
- 模型信息
    1）模型名称 2）使用数据集名称 3）使用算法名称 4）模型链接
- 复现信息：如为报错，请给出复现环境、复现步骤
- 问题描述：请详细描述您的问题，同步贴出报错信息、日志/代码关键片段

Thank you for contributing to PaddlePaddle.
Before submitting the issue, you could search issue in the github.Probably there was a similar issue submitted or resolved before.
If there is no solution,please make sure that this is a issue of models including the following details:
**System information**
-PaddlePaddle version （eg.1.1）or CommitID
-CPU: including CPUMKL/OpenBlas/MKLDNN version
-GPU: including CUDA/CUDNN version
-OS Platform (eg.Mac OS 10.14)
-Python version
-Name of Models&Dataset/details of operator
**To Reproduce**
Steps to reproduce the behavior
**Describe your current behavior**
**Code to reproduce the issue**
**Other info / logs**

**Comment by sonofaeolus** [comment]
关键部分代码（G_net是个seq2seq网络）：
words_prob = G_net(src_word_id, ctr_word_id, ctr_label)
words_id = fluid.layers.argmax(words_prob, axis = 1)
emb_layer = fluid.layers.embedding(input = word_id, size = [dict_size, emb_size], is_sparse = True)

**Comment by Xreki** [comment]
`embedding`输入的size必须是`[x, x, ..., 1]`这样的，也就是说最后一个维度必须是1，先确认一下`words_id`的shape是多少？可以调用`fluid.layers.reshape`先将`word_id` reshape一下。

**Comment by sonofaeolus** [comment]
reshape可以 但是我发现argmax结果不是一个lodtensor了 有没有类似的argmax的op输出是lodtensor的 或者一个tensor怎么转换为一个lodtensor

**Comment by Xreki** [comment]
可以使用`lod_reset`，http://www.paddlepaddle.org/documentation/docs/zh/1.2/api_cn/layers_cn.html#lod-reset

例如：

```python
current_state_with_lod = fluid.layers.lod_reset(x=current_state, y=pre_score)
```

**Comment by ccluqh** [comment]
请问您最后是怎么解决的哪？是只reshape了嘛？还是加了lod_reset？

**Comment by sonofaeolus** [comment]
最后解决方式是先reshape 然后lod_reset

**Comment by ccluqh** [comment]
> 最后解决方式是先reshape 然后lod_reset
words_id  reshape成[...,1]后，lod_reset(x=words_id_reshaped, y=?), y的输入是什么哪？
