### ISSUE TITLE
WITH_MKLDNN=ON 导致模型变慢

### ISSUE THREAD

**Issue by velconia** [PaddlePaddle/Paddle#15282]
排查发现，WITH_MKL=ON时，FLAGS_initial_cpu_memory_in_mb会被设置为 5000 

所以**所有使用 py_reader double_buffer 的模型在训练时，都会初始化 5G 的内存**，用于set tensor;

消耗过大，而且由于allocator性能的原因，这也会导致速度降低；

workaround:
1. 手动改小 FLAGS_initial_cpu_memory_in_mb 值，提升性能；

带 fix 问题：
1. 提升allocator性能，MaxSize变大时也能保证性能；
2. WITH_MKL=ON时，不应该设置更大的FLAGS_initial_cpu_memory_in_mb; 浪费内存

**Comment by luotao1** [comment]
@velconia The more accurate reason is `WITH_MKLDNN=ON`. Related codes:
https://github.com/PaddlePaddle/Paddle/blob/869f3a9dde1f533ca7ad3cb5a2daedde2044deb6/paddle/fluid/platform/cpu_info.cc#L39-L50

**Comment by luotao1** [comment]
I translate https://github.com/PaddlePaddle/Paddle/issues/15282#issue-398137989 into English.

When `WITH_MKL=ON`, FLAGS_initial_cpu_memory_in_mb=5000.
Thus, all models using `py_reader double_buffer` will allocate 5G memory for setting tensor.
It cause a lot of time and memory, and make the models run slower.

Workaround:
- `FLAGS_initial_cpu_memory_in_mb=500` manually.

TODO：
- refine allocator to ensure the speed when MaxSize grows bigger.
- `FLAGS_initial_cpu_memory_in_mb` should be 500M when `WITH_MKL=ON`

**Comment by luotao1** [comment]
Supplementary information of this issue：
- `WITH_MKL=ON` runs 30% slower than `WITH_MKL=OFF`
- This model runs on GPU.
- This model is small, only has 100 FC ops.

The default release whls (like `pip install paddlepaddle-gpu==1.0.1` ) have `WITH_MKLDNN=ON`. If `FLAGS_initial_cpu_memory_in_mb` could not be `500M` in default, we will remove mkldnn-related codes in such whls.

**Comment by wojtuss** [comment]
@luotao1 , the 500MB is enough now. PR with changes is submitted: https://github.com/PaddlePaddle/Paddle/pull/15291

**Comment by hshen14** [comment]
@wojtuss May I know the reason why 500MB is enough now?

**Comment by velconia** [comment]
Thanks for @luotao1 's help
