### ISSUE TITLE
安装错误_win10专业版_fluid1.2_pip安装_“image找不到”

### ISSUE THREAD

**Issue by baihaojie2011** [PaddlePaddle/Paddle#15297]
你好，我的笔记本电脑是 win10专业版，anaconda2，python 3.6，pip version 18.1
命令： pip install paddlepaddle
> 参考资料：http://www.paddlepaddle.org/documentation/docs/zh/1.2/beginners_guide/install/install_Windows.html

安装成功
但是，运行失败，效果如图
![500](https://user-images.githubusercontent.com/27996442/51074016-463f7900-16b4-11e9-9969-5190f2649d0c.png)

尝试过两次，都是失败了，请您看一下什么问题，谢谢

**Comment by colourful-tree** [comment]
看报错好像是anaconda2 自带的 pillow 版本不对？可以先尝试重新安装 pillow 试试？

**Comment by JiabinYang** [comment]
please reply this @wopeizl

**Comment by wopeizl** [comment]
看起来是依赖包pil有问题 可以尝试先pip uninstall pillow 再安装paddle试试

**Comment by wopeizl** [comment]
paddle1.3也已经发布 推荐使用新版本
