### ISSUE TITLE
layers怎么获取指定位置的元素

### ISSUE THREAD

**Issue by littletomatodonkey** [PaddlePaddle/Paddle#15299]
使用argsort对layers进行操作之后，想取出其中的前若干个元素，但是会爆
'''
'Variable' object has no attribute '__getitem__'
'''
的问题，我想问一下怎么获取layer中特定位置的元素，谢谢

**Comment by littletomatodonkey** [comment]
还有，想问一下paddle的detection中会考虑实现FPN中类似于的caffe2的CollectAndDistributeFpnRpnProposalsOp的op吗？

**Comment by gavin1332** [comment]
先讨论第一个问题。请详细描述一下需求，以及你是怎么取的？

**Comment by gavin1332** [comment]
http://www.paddlepaddle.org/documentation/docs/zh/1.2/api_cn/layers_cn.html#topk
step1. fluid.layers.topk得到前K个索引
step2. fluid.layers.one_hot将topk改为one hot表示
step3. fluid.layers.elementwise_mul完成select
