### ISSUE TITLE
Bug in is_test pass

### ISSUE THREAD

**Issue by hshen14** [PaddlePaddle/Paddle#15305]
In is_test pass, the code will check the whether op has attribute or op defines is_test first and then whether op exists in the specified op_list.

```
 for (const Node* n : graph->Nodes()) {
    if (n->IsOp()) {
      auto* op = n->Op();
      if (op->HasAttr("is_test") || op->HasProtoAttr("is_test")) {
        op->SetAttr("is_test", true);
      } else if (std::find(begin(op_list), end(op_list), op->Type()) !=
                 end(op_list)) {
        op->MutableAttrMap()->insert(
            std::pair<std::string, Attribute>("is_test", true));
      }
}
```
The right logic should check op first and then the op attribute. Please consider to fix it. @kbinias

**Comment by luotao1** [comment]
The logic is right since `op_list` is incomplete.

**Comment by hshen14** [comment]
I think we could make the implementation simple and error-proneless by making the op_list complete. Then, we don't need to understand whether op has such attribute. Probably it is a feature request.

**Comment by luotao1** [comment]
I think the implementation could be simplified like:
```
if (n->IsOp()) {
      auto* op = n->Op();
      if (op->HasAttr("is_test") || op->HasProtoAttr("is_test")) {
        op->SetAttr("is_test", true);
      } 
}
```
`op->HasProtoAttr("is_test")` contains the situation `op_list`, and we should not manully update `op_list`.
