### ISSUE TITLE
Inferencer re-design

### ISSUE THREAD

**Issue by wangkuiyi** [PaddlePaddle/Paddle#1531]
- As shown in https://github.com/PaddlePaddle/Paddle/pull/1501#discussion_r104040135, please re-consider if `paddle.infer` should take a reader parameter, or literal data.

- As explained in https://github.com/PaddlePaddle/Paddle/issues/1514, `python/paddle/v2/inferencer.py` should be renamed `inference.py`.

- The class `Inferencer` should not be exposed in `inferener.py` via `__all__`.

**Comment by helinwang** [comment]
>- python/paddle/v2/inferencer.py should be renamed inference.py.
>- The class Inferencer should not be exposed in inferener.py.

Fixed by https://github.com/PaddlePaddle/Paddle/pull/1532

**Comment by jacquesqiao** [comment]
fixed
