### ISSUE TITLE
预测阶段报错segmentation fault

### ISSUE THREAD

**Issue by LordAaron** [PaddlePaddle/Paddle#15324]
用的是paddle.fluid 0.14.0, gpu是4卡的p4
训好的网络想用来做预测
定位是python脚本的这里出的问题：out_bbx = self.exe.run(self.program, feed=self.feeder.feed(img), fetch_list=[self.nmsed_out], return_numpy=False)

报出的错误不太懂：
```
*** Aborted at 1547469391 (unix time) try "date -d @1547469391" if you are using GNU date ***
PC: @                0x0 (unknown)
*** SIGSEGV (@0x0) received by PID 20254 (TID 0x7f77e00b4700) from PID 0; stack trace: ***
    @       0x318b20f500 (unknown)
    @                0x0 (unknown)
[1]    20254 segmentation fault (core dumped)  python visualize.py
```

**Comment by Xreki** [comment]
`SIGSEGV (@0x0)` 这个错误应该是访问了非法地址`0x0`。是不是feed的数据为空？建议先检查一下，或者提供下详细的代码。

**Comment by LordAaron** [comment]
> `SIGSEGV (@0x0)` 这个错误应该是访问了非法地址`0x0`。是不是feed的数据为空？建议先检查一下，或者提供下详细的代码。

代码是没问题，我在k40的机器（cuda8.0，cudnn_v7.1）上面跑通了，没有任何问题，应该还是环境的问题，p4的环境有什么要求吗？

**Comment by Xreki** [comment]
请问预测用的单卡还是4卡呢？

**Comment by LordAaron** [comment]
> 请问预测用的单卡还是4卡呢？

4卡都会占用，但跑的是单卡
