### ISSUE TITLE
请问， 谁能给一个paddle c++预测的例子？

### ISSUE THREAD

**Issue by lavizhao** [PaddlePaddle/Paddle#15338]
在文档上找不到一个完整例子， 并且。。。。文档和github对不上， 目测文档已经不更新了。 

只能看github， 但是github里面例子一个是隐藏的很深， 另外一个确实一点注释不写， 本人菜鸡， 也看不懂。 

希望paddle 的同学能好好维护一下吧， 谢谢，  用起来真的很遭罪！

**Comment by shippingwang** [comment]
@lavizhao 麻烦贴一下 您看到的文档地址

**Comment by lavizhao** [comment]
http://www.paddlepaddle.org/documentation/docs/zh/1.2/advanced_usage/deploy/inference/build_and_install_lib_cn.html 

上面写的是 lib
│       ├── libpaddle_fluid.a
│       └── libpaddle_fluid.so

这个应该是错的吧？ 还有include， 貌似也不对。。。。。

**Comment by lavizhao** [comment]
还有就是book 里面好多例子都不更新， 都不知道对不对（希望不用我举例子了）。 

还有就是C++ 的编译选项希望能介绍的再全一点， 比如可不可以不用blas， 不用性能下降多少之类的。

**Comment by lavizhao** [comment]
而且讲道理， C++ 接口都这么不重视， 大家用paddle 说心底话， 基本没有啥搞科研的需求， 那既然这样， 还不如用别的了。

**Comment by shanyi15** [comment]
@lavizhao 
尊敬的用户您好，很抱歉我们的产品为您带来不好的体验，将您的反馈总结为以下几点：
- 在文档上找不到一个完整例子，存在于github里面例子位置深、不容易找、不写注释
- 未更新book 里面的例子
- C++ 的编译选项希望能介绍的再全一点， 比如可不可以不用blas， 不用性能下降多少之类
- 不重视C++ 接口

非常感谢您对我们的反馈，我们将充分考虑您的建议，为了让我们更具体地了解您的需求，请您针对以上几点分别补充以下信息：

- 请您提供“未更新book 里面的例子”的链接，因为看到book中的文档近期还在持续更新：

![image](https://user-images.githubusercontent.com/35982308/51176750-b3435080-18f8-11e9-9b38-fc0e2e6c89c0.png)

- 不重视C++ 接口

请您补充具体希望我们优化的点

谢谢！

**Comment by luotao1** [comment]
> 上面写的是 lib
│ ├── libpaddle_fluid.a
│ └── libpaddle_fluid.so
这个应该是错的吧？ 还有include， 貌似也不对

请问为什么认为是错的？

**Comment by lavizhao** [comment]
@lutao1 因为， 我用你们 v1.2 编出来的不一样啊， 你们编出来的和github 上是一致的， 但是docs 上就不是叫这个名啊。。。。 

@shanyi15 我嘴瓢了，不好意思， 应该是models下面的模型， 详细的我有难言之隐不能说， 你们得自己看了。 。。。。。

**Comment by lavizhao** [comment]
C++ 接口好歹也要给个例子啊， docs 上的 明显是旧版的， models 和book 里面明显没有c++的例子， 然后就只能看github 上的， 我发现的资料有这些：
1. https://github.com/PaddlePaddle/Paddle/tree/develop/paddle/legacy/capi/examples/model_inference ， 这个算是我认为可以参考的， 。。。但是比如seq目录下就啥介绍都没有， 我连这个具体是干啥的都不清楚。 

2. 还有一个藏的也很深， 我翻了块一天才找到的。

**Comment by luotao1** [comment]
> C++ 接口好歹也要给个例子啊

请仔细看我们的官网文档
http://www.paddlepaddle.org/documentation/docs/zh/1.2/advanced_usage/deploy/inference/native_infer.html#permalink-8--
![image](https://user-images.githubusercontent.com/6836917/51178587-f6ec8900-18fd-11e9-92db-5617ac509481.png)

**Comment by luotao1** [comment]
> 我用你们 v1.2 编出来的不一样啊， 你们编出来的和github 上是一致的

请问是否按照完全我们的编译步骤？如果仍然有错，请贴出详细的编译步骤。

**Comment by lavizhao** [comment]
楼上的大爷， 你用没用过啊， 你看贵司的文档：
https://github.com/PaddlePaddle/Paddle/blob/develop/doc/v2/howto/capi/compile_paddle_lib_cn.md

编出来的是 
lib
│   ├── libpaddle_capi_engine.a
│   ├── libpaddle_capi_layers.a
│   ├── libpaddle_capi_shared.so
│   └── libpaddle_capi_whole.a

但是你司文档遍出来的是 
库文件libpaddle_fluid.so 或 libpaddle_fluid.a

我就问你， 哪个对？ 你弄没弄明白， 现在是贵司文档用户别人看不懂的问题？

**Comment by lavizhao** [comment]
还有， 有一句话我一直想说， 你们这头文件静态库变了我看少说两三次了， 你们在大搜也敢这么玩？ 还是你们拿了压根没在厂内试用过的东西就给我们用了？ 我点到为止。。。。

**Comment by lavizhao** [comment]
还有， 贵司给的预测库的下载文档链接都失效了好吗， 我给你举个例子， 

这页的

https://github.com/PaddlePaddle/Paddle/blob/develop/doc/v2/howto/capi/compile_paddle_lib_cn.md

这个

https://guest@paddleci.ngrok.io/repository/download/Manylinux1_CpuAvxCp27cp27mu/.lastSuccessful/paddle.tgz

**Comment by luotao1** [comment]
请选择正确的版本号，选择最新的版本号：
![image](https://user-images.githubusercontent.com/6836917/51222165-7a968c00-1977-11e9-96a2-b6accbd39529.png)
> 库文件libpaddle_fluid.so 或 libpaddle_fluid.a

这是最新的v1.2版本的预测库。

> https://github.com/PaddlePaddle/Paddle/blob/develop/doc/v2/howto/capi/compile_paddle_lib_cn.md

这是v0.12.0的老版本库。（这个库现在已经不维护了，不建议下载和使用）

**Comment by shangguanyifeng** [comment]
v0.12.0的老版本库。（这个库现在已经不维护了，不建议下载和使用）

**Comment by shangguanyifeng** [comment]
同学你好，看到了您反馈的上述问题。

目前您遇到的问题可能是因为版本过旧官方不再维护库造成的。建议您尝试更新到最新的fluid版本，解决当前问题。同时我们已经着手在文档中增加版本提示，避免后续使用文档的同学遇到类似情况。

如果可以，希望能获取您的联系方式，和您进一步沟通，帮您解决遇到的问题。
