### ISSUE TITLE
请教一下，怎么根据自己的需要更新网络的参数

### ISSUE THREAD

**Issue by wudeshi** [PaddlePaddle/Paddle#15336]
tensorflow中可以先求gradient，进行一些处理，然后用apply函数更新参数。paddlepaddle有这样子的api吗

**Comment by phlrain** [comment]
![image](https://user-images.githubusercontent.com/43953930/51182401-07563100-1909-11e9-94c6-9eb52d870e7d.png)
目前 paddle中只实现了一个minimize 接口，包含了类似于tf的compute gradient，然后处理，最后apply gradient，后续我们会升级相应的接口，如果你着急使用，minimize中的 self._create_optimization_pass 就是做了 apply gradient的工作，你可以修改python的 site-packages/paddle 中的optimizer.py 暴露两个接口来使用

**Comment by wudeshi** [comment]
好的，谢谢，还有一个问题，我打印出一个卷积核的形状是[1, 参数大小]，怎么知道高度，宽度，输出channel啊

**Comment by shippingwang** [comment]
@wudeshi  input.shape ?
