### ISSUE TITLE
是否能增加一个接口输出GPU内存池中实际使用的显存。

### ISSUE THREAD

**Issue by lgone2000** [PaddlePaddle/Paddle#15332]
目前paddle内存池采用预分配，用nvidia-smi 查看不了显存使用情况。
主要需要用于查看 跟进显存使用情况，来设定训练batch大小。也可以用于查找显存或者内存泄露

**Comment by shippingwang** [comment]
请您看下 [GPU profile](http://www.paddlepaddle.org/documentation/docs/zh/1.2/advanced_usage/development/profiling/gpu_profiling_cn.html#gpu) 是否满足需求。

**Comment by lgone2000** [comment]
这个使用还需要重新设置WITH_PROFILER  编译吗，使用门槛有点高。
其实能提供一个简单的命令行nvidia-smi 这样的命令查看使用情况就行。

**Comment by zzchust** [comment]
这个目前进展如何呢？ 急需。目前使用paddle训练简单的分类问题，设定训练的batchsize较为困难

**Comment by lgone2000** [comment]
如果只是为了测试batch大小， 可以训练前设置
export FLAGS_fraction_of_gpu_memory_to_use=0.2
这样初始时不会分配全部显存，而是随使用临时申请
