### ISSUE TITLE
怎么打印出数据经过某些层后输出的东西是什么

### ISSUE THREAD

**Issue by wudeshi** [PaddlePaddle/Paddle#15334]
现在需要知道一个test 数据经过一些神经网络之后输出的数据对不对

**Comment by shippingwang** [comment]
请参照 #12986 
比如要打印 out=fluid.layers.fc(...)
out.persistable=True

fc = np.array(fluid.global_scope().find_var(**layer name**).get_tensor())
print(fc)
或参照 [print op](http://www.paddlepaddle.org/documentation/docs/zh/1.2/api_cn/layers_cn.html#print)
谢谢

**Comment by OleNet** [comment]
> layer name

这里面的layer name是什么呢？
'out' 还是 fluid.layers.fc的某个指定参数?
