### ISSUE TITLE
如何让全连接层输出的结果都是正数呢？

### ISSUE THREAD

**Issue by yeyupiaoling** [PaddlePaddle/Paddle#15340]
# 环境
 - PaddlePaddle 1.2.0
 - Python 3.5
 - Windows 10

# 问题
使用的损失函数是`square_error_cost`，我想网络输出的是都是正数以上，不要输出负数，怎么处理呢？
```python
fc1 = fliud.layers.fc(input=ipt, size=100, act='relu')
fc1 = fliud.layers.fc(input=ipt, size=2)
```

**Comment by shippingwang** [comment]
@yeyupiaoling  
第一行 加了relu后输出都是大于等于0的吧
第二行 输出结果可能是正也可能是负
第一行是满足的

**Comment by yeyupiaoling** [comment]
@shippingwang 好的，谢谢回答。
