### ISSUE TITLE
关于paddle输入数据的格式的问题

### ISSUE THREAD

**Issue by wowBC** [PaddlePaddle/Paddle#15349]
请问一下，paddle如下的jni接口，参数buf是否支持（r,g,b,x,y......r,g,b,x,y）这种数据格式;其中x表示像素点的x坐标，y表示y坐标；
JNIEXPORT jfloatArray JNICALL Java_com_baidu_paddle_PML_predictImage(
    JNIEnv *env, jclass thiz, jfloatArray buf, jintArray ddims)
如果支持的话，输入的ddims应该是什么格式呢？谢谢～

**Comment by heavengate** [comment]
请问你使用的是paddle-mobile么，还是paddle的哪个版本？

**Comment by wowBC** [comment]
是的，paddle mobile，thx

**Comment by wowBC** [comment]
是的，paddle mobile，paddle mobile和paddle支持的数据格式应该是一样的吧

**Comment by hjchen2** [comment]
@wowBC 你好，我理解你想问的是Paddle Mobile是否支持 [n, h, w, c]的图片格式，并且c=5（r, g, b, x, y）。
Paddle Mobile的predictImage jni接口只是透传数据，本身支持你说的这种格式，输入的dims是[1, h, w, 5]，不过由于Paddle Mobile的op只支持[n, c, h, w]的格式，因此在预测时可能导致错误的结果。你需要将模型转换成[n, c, h, w]对应的格式，才能得到正确的结果。

**Comment by wowBC** [comment]
@hjchen2 是的，我需要输入的buf参数就是是（r, g, b, x, y, ..., r, g, b, x, y ）。谢谢。

**Comment by wowBC** [comment]
@hjchen2 好的，感谢
