### ISSUE TITLE
Travis CI frequent fail because of TCP port problem

### ISSUE THREAD

**Issue by helinwang** [PaddlePaddle/Paddle#1535]
Following error log is often found in failed CI test:
> I0302 22:32:02.964061 14115 Util.cpp:160] commandline: /home/travis/build/PaddlePaddle/Paddle/build/paddle/pserver/test/test_ProtoServer --port=22618 
> I0302 22:32:02.966806 14117 LightNetwork.cpp:269] tcp server start 
> [==========] Running 2 tests from 1 test case.
> [----------] Global test environment set-up.
> [----------] 2 tests from ProtoServer
> [ RUN      ] ProtoServer.regular
> I0302 22:32:02.976634 14118 LightNetwork.cpp:322] worker started, peer = 127.0.0.1
> [       OK ] ProtoServer.regular (2 ms)
> [ RUN      ] ProtoServer.extended
> [       OK ] ProtoServer.extended (0 ms)
> [----------] 2 tests from ProtoServer (2 ms total)
> [----------] Global test environment tear-down
> [==========] 2 tests from 1 test case ran. (2 ms total)
> [  PASSED  ] 2 tests.
> I0302 22:32:02.977071 14115 SocketChannel.cpp:42] destory connection in socket channel, peer = 127.0.0.1
> I0302 22:32:02.977301 14117 LightNetwork.cpp:215] pserver accept thread finish, addr=127.0.0.1 port=22618
> I0302 22:32:02.977375 14115 SocketChannel.cpp:42] destory connection in socket channel, peer = 127.0.0.1
> *** Aborted at 1488493922 (unix time) try "date -d @1488493922" if you are using GNU date ***
> PC: @                0x0 (unknown)
> *** SIGABRT (@0x3e800003723) received by PID 14115 (TID 0x2ba794d5f700) from PID 14115; stack trace: ***
>     @     0x2ba790baa330 (unknown)
>     @     0x2ba791d76c37 gsignal
>     @     0x2ba791d7a028 abort
>     @          0x11ed3fd glog_internal_namespace_::Mutex::Lock()
>     @          0x11ed49e glog_internal_namespace_::MutexLock::MutexLock()
>     @          0x11e8efd google::LogMessage::Flush()
>     @          0x11e8d87 google::LogMessage::~LogMessage()
>     @           0xd41ee2 paddle::SocketWorker::run()
>     @           0x96a935 _ZZN6paddle6Thread5startEvENKUlvE_clEv
>     @           0x982894 _ZNSt12_Bind_simpleIFZN6paddle6Thread5startEvEUlvE_vEE9_M_invokeIJEEEvSt12_Index_tupleIJXspT_EEE
>     @           0x9826f7 _ZNSt12_Bind_simpleIFZN6paddle6Thread5startEvEUlvE_vEEclEv
>     @           0x9824e0 _ZNSt6thread5_ImplISt12_Bind_simpleIFZN6paddle6Thread5startEvEUlvE_vEEE6_M_runEv
>     @     0x2ba7915d1a60 (unknown)
>     @     0x2ba790ba2184 start_thread
>     @     0x2ba791e3a37d clone
>     @                0x0 (unknown)
> /home/travis/build/PaddlePaddle/Paddle/build/paddle/pserver/test/test_ProtoServer run wrong
> /home/travis/build/PaddlePaddle/Paddle/paddle/.common_test_util.sh: line 72: 14115 Aborted                 (core dumped) $cmd --$port_type=$port

**Comment by gangliao** [comment]
#1541 Disable test_protoserver on Travis CI to avoid blocking. (no problem on local machine)
#1542 Simplify Travis CI outputs.
