### ISSUE TITLE
训练过程中embedding更新方式

### ISSUE THREAD

**Issue by LihangLiu** [PaddlePaddle/Paddle#15354]
想咨询一下paddle在更新embedding的参数的时候，是取gradients的mean么（相当于sum(grads) / batch_size）？

**Comment by LihangLiu** [comment]
fluid.layers.embedding函数

**Comment by heavengate** [comment]
![image](https://user-images.githubusercontent.com/12605721/51232493-e68dea00-19a1-11e9-9242-4c21d123cf35.png)
不是平均，而是直接加和，相当于sum，不除以sample数
