### ISSUE TITLE
当我使用DynamicRNN创建自定义rnn的时候，我怎样可以获得每个step输出的状态，而不是最后一步的状态呢？

### ISSUE THREAD

**Issue by dianhuasici** [PaddlePaddle/Paddle#15364]

**Comment by dianhuasici** [comment]
![image](https://user-images.githubusercontent.com/28981936/51235636-007ffa80-19ab-11e9-8b93-9d68f9be3367.png)
像图中这样，我不想按照文档上面使用"sequence_last_step 可获取 DynamicRNN 最后一个时间步的输出"

**Comment by heavengate** [comment]
是指获得gate0，gate1，gate2这些参数么

**Comment by dianhuasici** [comment]
不是，是获得代码中的hidden，因为到最后return的时候好像还是最后一个step的输出，但是我现在想获得每一步中间状态的输出

**Comment by heavengate** [comment]
你可以试下在block里面更新hidden之前hidden.persistable=True, 并把hidden打印出来，打印出来你会知道hidden的名字，然后在每次exe.run 之后通过numpy.array(fluid.global_scope().find_var("hidden_name").gen_tensor()) 获取

**Comment by dianhuasici** [comment]
好的，十分感谢，我还想多问一下，在我构建这个rnn得时候有没有api能直接让我获得结果呢，就像使用dynamic_gru一样，我直接使用return的值就可以获得，在这个DynamicRNN里面有什么接口呢，因为我在获得结果之后还会进一步有一些操作，不能直接就exe.run() @heavengate

**Comment by heavengate** [comment]
需要做什么处理，在更新block处可以获取到每一步的hidden，我理解可以在with语句上面初始化一个数组，with里面把每个hidden append进去，这样在外面能获取到

**Comment by dianhuasici** [comment]
@heavengate 好的，谢谢~
