### ISSUE TITLE
PaddlePaddle中是否有对应Tensorflow中的一些rnn api实现？

### ISSUE THREAD

**Issue by jjjkaixin** [PaddlePaddle/Paddle#15369]
主要是下面四个api
tf.contrib.rnn.BasicLSTMCell
tf.contrib.rnn.DropoutWrapper
tf.contrib.rnn.MultiRNNCell
tf.nn.static_bidirectional_rnn

**Comment by heavengate** [comment]
没有上面这些直接对应的接口，lstm与tf的rnn_cell/LSTMCell一致，不知道与你要求是否一致
