### ISSUE TITLE
运行book示例报core

### ISSUE THREAD

**Issue by kjfren1985** [PaddlePaddle/Paddle#15366]
- 版本、环境信息：
    1）PaddlePaddle版本：1.2.0（内网一键安装paddlepaddle-1.2.0-cp27-cp27mu-linux_x86_64.whl）
    2）CPU：有avx
    3）系统环境：CentOS release 4.3 (Final)
- 训练信息
    1）单机
- 复现信息：01.fit_a_line下运行fluid train.py
- 问题描述：
运行book示例报core（可提供core文件）：

*** Aborted at 1547628350 (unix time) try "date -d @1547628350" if you are using GNU date ***
PC: @                0x0 (unknown)
*** SIGSEGV (@0x10) received by PID 15644 (TID 0x7f3623a3a740) from PID 16; stack trace: ***
    @     0x7f3622cdb160 (unknown)
    @     0x7f3622cd7d2c __pthread_cond_broadcast
段错误 (core dumped)

**Comment by heavengate** [comment]
这个centos版本比较低，应该是whl报和linux不兼容，建议通过docker安装运行 docker pull hub.baidubce.com/paddlepaddle/paddle:latest-dev

**Comment by kjfren1985** [comment]
> 这个centos版本比较低，应该是whl报和linux不兼容，建议通过docker安装运行 docker pull hub.baidubce.com/paddlepaddle/paddle:latest-dev

多谢~那我之前通过厂内一键安装的paddlepaddle需要先清除吗？现在目前在调研阶段，通过docker安装的可以满足后续的开发、启动集群任务的需求吗？

**Comment by heavengate** [comment]
docker开发是我们目前的常用开发模式，开发需求基本都能满足的，不需要清楚本地，docker是一个独立的环境容器，至于说集群任务部署，一般使用paddlecloud等，能在docker里跑的在paddlecloud里面肯定是可行的
