### ISSUE TITLE
把cnn层的filter参数打印出来，形状是[1, 参数个数]，我知道filter形状，和channel也不能把卷积还原出来

### ISSUE THREAD

**Issue by wudeshi** [PaddlePaddle/Paddle#15362]

**Comment by heavengate** [comment]
请贴一下代码并详细描述一下问题，谢谢 @wudeshi

**Comment by wudeshi** [comment]
> 请贴一下代码并详细描述一下问题，谢谢 @wudeshi

paddle.layer.img_conv的参数是
![image](https://user-images.githubusercontent.com/18420038/51235141-ba766700-19a9-11e9-8ec8-1a1dc1b137e0.png)都是我不知道[1, 参数个数]是怎么跟1✖️32✖️11乘41对应起来的

**Comment by heavengate** [comment]
你使用的是paddle的那个版本，打印的是哪个参数的shape，不太理解你的filer的shape是[1, 参数个数], 是指filter_size么

**Comment by wudeshi** [comment]
> 你使用的是paddle的那个版本，打印的是哪个参数的shape，不太理解你的filer的shape是[1, 参数个数], 是指filter_size么

0.10版本，打印的卷积核的参数，但是只能得到二维的，不是4维的

**Comment by heavengate** [comment]
你是使用哪个接口打印的卷积核参数

**Comment by hjchen2** [comment]
> > 你使用的是paddle的那个版本，打印的是哪个参数的shape，不太理解你的filer的shape是[1, 参数个数], 是指filter_size么
> 
> 0.10版本，打印的卷积核的参数，但是只能得到二维的，不是4维的

是不是打印的是Conv bias的shape，而不是filter的shape
