### ISSUE TITLE
reverse函数出现一些问题

### ISSUE THREAD

**Issue by dianhuasici** [PaddlePaddle/Paddle#15379]
![image](https://user-images.githubusercontent.com/28981936/51293170-99188800-1a48-11e9-9d22-e8a2bf5f7e5a.png)
我按照文档上给的方法，先随便创建了一个全0的Variable，紧接着使用reverse（axis=1）报错

**Comment by hjchen2** [comment]
@dianhuasici 你好，我这边使用你提供的命令复现了这个问题，这个应该是fluid python接口的一个bug。临时解决方案是：将paddle/fluid/layers/tensor.py中reverse函数中的，
```python
        inputs={'Input': x},
```
改成
```python
      inputs={'X': x},
```
我们这边后续会尽快修复，谢谢！

**Comment by junjun315** [comment]
@dianhuasici 新版本的代码中已经修复了这个问题，请使用develop的代码重新编译或者待release1.3发布
