### ISSUE TITLE
编译1.2版本的paddle，产出whl包版本是0.0.0

### ISSUE THREAD

**Issue by hjchen2** [PaddlePaddle/Paddle#15380]
请问一下，我在 compile paddle 1.2 版本时，执行 /paddle/paddle/scripts/paddle_build.sh build
脚本时，编译的时候也没有报错，但是编译出来的 whl 包名为：paddlepaddle_gpu-0.0.0-cp27-cp27mu-linux_x86_64.whl。安装后，打印 paddle version 也是 ￼0.0.0

**Comment by hjchen2** [comment]
这个是paddle检测version的一个bug，在release/1.2的分支下，需要将cmake/version.cmake中的set(TAG_VERSION_REGEX "[0-9]+\\.[0-9]+\\.[0-9]+(\\.(a|b|rc)\\.[0-9]+)?")这一行改成set(TAG_VERSION_REGEX "[0-9]+\\.[0-9]+(\\.(a|b|rc)\\.[0-9]+)?")。后续我们会安排修复一下，谢谢。

**Comment by jiaqianjing** [comment]
好的，：）

**Comment by jiaqianjing** [comment]
另外，提个小意见，这个 branch 的名字， release/number 能否和 paddle version 保持一致 ，比如 release/1.2.0

**Comment by jiaqianjing** [comment]
> 请问一下，我在 compile paddle 1.2 版本时，执行 /paddle/paddle/scripts/paddle_build.sh build
> 脚本时，编译的时候也没有报错，但是编译出来的 whl 包名为：paddlepaddle_gpu-0.0.0-cp27-cp27mu-linux_x86_64.whl。安装后，打印 paddle version 也是 ￼0.0.0

也可以通过修改编译的 环境变量修复：export PADDLE_VERSION=1.2.0

**Comment by Yancey0623** [comment]
Will close this issue, fixed by #15551
