### ISSUE TITLE
开发一个图像识别的，在paddle可以支持不同的初始化方式上一直纠结，不知道这个有没有差异？采用不同的方式会不会影响开发。

### ISSUE THREAD

**Issue by appleappleorange** [PaddlePaddle/Paddle#15393]
开发一个图像识别的，在paddle可以支持不同的初始化方式上一直纠结，不知道这个有没有差异？采用不同的方式会不会影响开发。

**Comment by hjchen2** [comment]
@appleappleorange 请问一下你是从零开始训一个模型，还是从checkpoint继续训练，还是finetune？从零开始训练的话，参数初始化方式对收敛的效果是有影响的，这个需要用户不断的去尝试，但图像识别的模型参数初始化方式一般也就选择xavier和MSRA吧。断点训练或finetune可以使用对应的load接口初始化参数，具体可以参考 http://paddlepaddle.org/documentation/docs/zh/1.2/user_guides/howto/training/single_node.html#id4
