### ISSUE TITLE
API V2目前需要完成的工作。

### ISSUE THREAD

**Issue by reyoung** [PaddlePaddle/Paddle#1539]
1. 机器翻译调通   ---- 龙飞

2. Demo的Markdown
    * Fit A Line需要帮助  --- 王益

3. 数据集
    * [x] Sentimental 数据集   --- 文博，于洋
    * [ ] Fit A Line 数据集 Approved & Need Merged  --- 党青青
    * [ ] WMT 14 需要加一下 --- 于洋、王鹤麟
        * [ ] 于洋负责把文件扔到CDN
        * [x] 于洋issue 一个说明，WMT 14的预处理过程是怎样的。
        * [ ] 王鹤麟 负责实现reader
    * [ ] 词向量 Fix Need Merge  --- 王鹤麟

4. 重画Book中，中文图例  --- 刘勇峰

5. Release New API 文档  --- 于洋
    * [x] Python __doc__ + Sphinx
    * [x] http://www.paddlepaddle.org/v0.10.0.rc/doc

6. BUG --- 何道远
    * [x] MultiGradientMachine TrainerCount>1 预测 样本 == 1 有bug

**Comment by jacquesqiao** [comment]
fixed
