### ISSUE TITLE
What is settings' data structure

### ISSUE THREAD

**Issue by dreamingcp** [PaddlePaddle/Paddle#1540]
1.In dataprovider.py, there usually is settings.input_types, but in semantic_role_labeling, there is only a settings.slots . What is the difference between input_types and slots? 
2.Can someone give me the whole data structure of 'settings' and the description of the data structure?

Thanks a lot!

**Comment by reyoung** [comment]
Sorry for lacking documentation of this data structure.

> 1.In dataprovider.py, there usually is settings.input_types, but in semantic_role_labeling, there is only a settings.slots . What is the difference between input_types and slots?

`settings.slots` and `settings.input_types` are same object.  We used to name each feature of a neural network as `slot`.  Before we open source Paddle, we think `slot` is confusing. We changed `slot` to `input_types`.  For backward compatibility, we didn't remove `slot` object in `settings`.

> 2.Can someone give me the whole data structure of 'settings' and the description of the data structure?

Related [Documentation](http://www.paddlepaddle.org/doc/ui/data_provider/pydataprovider2.html#provider).

`settings` object is a global context, which shared between `init_hook` and `process` function. User can store some context, such as `word dictionary`, to`settings` object in `init_hook`, and use them in `process`.

The settings object is actually [`DataProvider`](https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/trainer/PyDataProvider2.py#L316) object itself. There are many fields in it, but they are mostly used by Paddle Core code.
