### ISSUE TITLE
Is there any error in sequence_expand_op's doc?

### ISSUE THREAD

**Issue by Xreki** [PaddlePaddle/Paddle#15406]
See [here](http://www.paddlepaddle.org/documentation/docs/zh/1.2/api_cn/layers_cn.html#sequence-expand), the second case:

```python
x is a Tensor:
    x.data = [[a], [b], [c]]
    x.dims = [3, 1]

y is a LoDTensor:
    y.lod = [[2, 0, 3]]

ref_level: -1

then output is a Tensor:
    out.data = [[a], [a], [c], [c], [c]]
    out.dims = [5, 1]
```

`y.lod` should be `[[0, 2, 2, 5]]`?

**Comment by qingqing01** [comment]
@Xreki  Now LoD in Python is lenght-based, i.e,  users only need to give length-based LoD. So there is no error.

**Comment by Xreki** [comment]
I see. Thanks.
