### ISSUE TITLE
reshape_op can not match size

### ISSUE THREAD

**Issue by liyingying05** [PaddlePaddle/Paddle#15400]
预测的时候发现input_shape改变会在reshape层导致size不匹配的问题
问题应该是reshape_op中的output_shape[unk_dim_idx] 没有取float所导致，具体表现为：
in_dim=[-1, 260, 35, 63]
shape = [-1, 2, 1820, 14]
Capacity = -1*2*1820*14 = - 35840
in_size=-1*260*35*63=-573300
不取float
output_shape[unk_dim_idx] = -in_size / capacity = 15
output_shape[unk_dim_idx] * capacity = 15*35840 = 537600 != in_size 
取float
output_shape[unk_dim_idx] = -in_size / capacity = 15.9960938
output_shape[unk_dim_idx] * capacity = 15.9960938*35840 = 573300 == in_size

**Comment by hjchen2** [comment]
@liyingying05 output_shape只能是取整数，因此in_size必须是capacity的整数倍，否则reshape前后的数据大小就不一样了。请看看是不是输入数据的shape本身有问题呢？
