### ISSUE TITLE
关于fluid版本和以前的v2版本

### ISSUE THREAD

**Issue by stoiczzz** [PaddlePaddle/Paddle#15414]
fluid版本为什么找不到激活函数linear，而且以前v2的版本的paddle.v2.layer.addto请问对应的是现在哪个，直接可以使用+吗 elementwise_add？。

**Comment by qingqing01** [comment]
1. linear激活即y=x，不用配置即是linear。举例下面两种方式都是linear激活。

```python
    data = fluid.layers.data(name="data", shape=[32, 32], dtype="float32")
    fc = fluid.layers.fc(input=data, size=128, act=None)
    # or
    #  fc = fluid.layers.fc(input=data, size=128)
```

2. paddle.v2.layer.addto对应 fluid.layers.elementwise_add，使用如下，也支持x和y的shape不同，支持broadcast，参考文档：http://www.paddlepaddle.org/documentation/docs/zh/1.2/api_cn/layers_cn.html#elementwise-add

```
x = fluid.layers.data(name='x', shape=[10], dtype='float32')
y = fluid.layers.data(name='y', shape=[10], dtype='float32')
z = x + y
# z = fluid.layers.elementwise_add(x,y)
```
