### ISSUE TITLE
PaddlePaddle的开发感觉在配置上有些不清楚，希望提供模型配置文件教程确认

### ISSUE THREAD

**Issue by appleappleorange** [PaddlePaddle/Paddle#15416]
PaddlePaddle的开发感觉在配置上有些不清楚，希望提供模型配置文件教程确认，能有详细的说明吗，提供一下地址

**Comment by qingqing01** [comment]
能麻烦具体说下是什么模型的配置吗？ 

另外：
1. 模型库：https://github.com/PaddlePaddle/models/tree/develop/fluid 这里的模型都是我们验证过、对齐的，可以参考。
2. 模型配置相关API文档：http://www.paddlepaddle.org/documentation/docs/zh/1.2/api_cn/index_cn.html
