### ISSUE TITLE
paddle 的grumemory的源码在哪里啊，都查不到

### ISSUE THREAD

**Issue by wudeshi** [PaddlePaddle/Paddle#15412]

**Comment by qingqing01** [comment]
@wudeshi grumemory是Paddle V2里的代码，等价于fluid.layers.dynamic-gru实现，推荐使用Fluid。

 Fluid文档：http://www.paddlepaddle.org/documentation/docs/zh/1.2/api_cn/layers_cn.html#dynamic-gru
Python接口代码: https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/fluid/layers/nn.py#L861
C++源码: https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/fluid/operators/gru_op.cc
