### ISSUE TITLE
1.PaddlePaddle在安装过程中，采用什么类型的开发环境会好点

### ISSUE THREAD

**Issue by appleappleorange** [PaddlePaddle/Paddle#15415]
PaddlePaddle在安装过程中，采用什么类型的开发环境会好点，例如linux，windows，或者unix等，开发环境对运行性能有差异吗？

**Comment by qingqing01** [comment]
Paddle支持的环境包括：Ubuntu, CentOS, MacOS, Windows7，详细参考 http://www.paddlepaddle.org/documentation/docs/zh/1.2/beginners_guide/install/index_cn.html 。 建议Linux开发环境，目前发型版本只有Linux支持GPU。 性能差异取决于硬件。
