### ISSUE TITLE
模型压缩

### ISSUE THREAD

**Issue by xueshang-liulp** [PaddlePaddle/Paddle#15422]
使用paddlepaddle训练的模型怎么进行模型压缩

**Comment by qingqing01** [comment]
@llp123 感谢关注，我们正在做模型压缩系列工作，请问您具体需要那种压缩方法？

**Comment by xueshang-liulp** [comment]
@qingqing01 现在遇到的问题就是模型过大，推理耗费时间长，进行例如降低精度，模型裁剪等方面的压缩方法，另外DeepBench不知道能否应用上？

**Comment by qingqing01** [comment]
请问您是什么模型？是在端上预测还是Server上预测？是CPU预测还是GPU预测？推理较耗时，也需要依据您的模型和C++预测API的使用情况。

关于Paddle对于模型压缩的情况： 
1. 8bit预测，如果是端上，Paddle-Mobile支持若干CNN模型的预测，Paddle CPU正在支持8bit的预测。 GPU可以使用TensorRT的8bit加速CNN模型。 需要知道您的具体模型和硬件。8bit预测Paddle也正在优化支持。
2. 其他裁剪模型、蒸馏等方法属于算法级别，这些后续会支持，但需要知道您的模型类型。

DeepBench我理解是来针对不同操作、硬件、模型做benchmark，评估性能，不是用来加速的。
