### ISSUE TITLE
Windows下pip安装成功但import paddle.fluid验证安装失败

### ISSUE THREAD

**Issue by HaozhengLi** [PaddlePaddle/Paddle#15423]
- 版本、环境信息：
    1）PaddlePaddle版本：1.2.1
    2）CPU：Intel(R) Core(TM) i5-7500
    3）操作系统：Windows 7 专业版 + Python 3.5.1

- 安装方式信息：
    pip安装：pip3 install paddlepaddle

- 复现信息：Windows下pip安装成功但import paddle.fluid验证安装失败
- 问题描述：
```
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\paddle\fluid\framework.py", line 27, in <module>
    from . import core
ImportError: DLL load failed: 找不到指定的程序。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:/Output/Python_output/PARL/PARL-kog/main.py", line 1, in <module>
    import paddle.fluid
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\paddle\fluid\__init__.py", line 18, in <module>
    from . import framework
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\paddle\fluid\framework.py", line 33, in <module>
    directory. The original error is: \n""" + cpt.get_exception_message(e))
ImportError: NOTE: You may need to run "export LD_LIBRARY_PATH=/usr/local/lib:$LD_LIBRARY_PATH"
    if you encounters "libmkldnn.so not found" errors. If you have python
    installed in other directory, replace "/usr/local/lib" with your own
    directory. The original error is: 
DLL load failed: 找不到指定的程序。
```

**Comment by wopeizl** [comment]
一般情况下是因为python35.dll不在path环境变量里面，可以尝试手工加到path环境变量中再试一下

**Comment by HaozhengLi** [comment]
> 一般情况下是因为python35.dll不在path环境变量里面，可以尝试手工加到path环境变量中再试一下

您好，您的意思是指系统环境变量中 “用户变量” 或 “系统变量” 中的path吗，我已经将<python35.dll>所在的路径<C:\Users\Administrator\AppData\Local\Programs\Python\Python35>加入到path中了，仍然报一样的错误。

请问还有别的解决方法吗，谢谢。

**Comment by wopeizl** [comment]
可以这样 1. 用Administrator账号权限运行一下。
2. 如果这样还不行，可以试验一下用virtualenv，具体步骤是
a.  pip install virtualenv
b. virtualenv test
c. cd test
d. scripts\activate
e. pip install paddlepaddle
再看看能否使用paddle

**Comment by HaozhengLi** [comment]
> 可以这样 1. 用Administrator账号权限运行一下。
> 2. 如果这样还不行，可以试验一下用virtualenv，具体步骤是
> a. pip install virtualenv
> b. virtualenv test
> c. cd test
> d. scripts\activate
> e. pip install paddlepaddle
> 再看看能否使用paddle

您好，这两种方法都尝试过了，仍然报一样的错误。

请问还有别的解决方法吗，谢谢。

**Comment by wopeizl** [comment]
目前看起来感觉是python安装可能有点问题，可以尝试重新安装一下，安装的时候勾选“add python3 to path"选项 ，并最好安装到自定义目录方便查看
![image](https://user-images.githubusercontent.com/23548796/51579251-3bc68000-1efb-11e9-87df-14224609b0b4.png)

**Comment by HaozhengLi** [comment]
> 目前看起来感觉是python安装可能有点问题，可以尝试重新安装一下，安装的时候勾选“add python3 to path"选项 ，并最好安装到自定义目录方便查看
> ![image](https://user-images.githubusercontent.com/23548796/51579251-3bc68000-1efb-11e9-87df-14224609b0b4.png)

看来是python版本的原因，我将Python版本换成3.6.3即可跑通。

感谢您的帮助，谢谢！

**Comment by benjaminxz** [comment]
我也遇到了类似的问题，解决方法和上面类似，卸载已经安装的python ，重新安装3.6版本，再重新安装paddle就可以跑通。

**Comment by benjaminxz** [comment]
我也遇到了类似的问题，解决方法和上面类似，卸载已经安装的python ，重新安装3.6版本，再重新安装paddle就可以跑通。

**Comment by Tianhuo007** [comment]
我用的是anconda安装的python3.7，遇到了同样的问题，是core.pyd反编译出了问题吗？

**Comment by benjaminxz** [comment]
其实我也遇到了相同的问题，不过我的解决方法比较粗暴：删除电脑中所有版本的python，然后再安装某一个需要的版本，添加环境变量。问题解决。

**Comment by benjaminxz** [comment]
其实我也遇到了相同的问题，不过我的解决方法比较粗暴：删除电脑中所有版本的python，然后再安装某一个需要的版本，添加环境变量。问题解决。

**Comment by lluck42** [comment]
Python 3.6.8
import paddle 没啥问题
import paddle.fluid
DLL load failed: 找不到指定的模块。
必须是3.6.3版本的么?

**Comment by wopeizl** [comment]
机器cpu是什么型号的 可以尝试一下noavx的版本

**Comment by luotao1** [comment]
@wopeizl http://www.cpu-world.com/CPUs/Core_i5/Intel-Core%20i5%20i5-7500.html
Intel(R) Core(TM) i5-7500是支持avx的。

**Comment by luotao1** [comment]
```
Traceback (most recent call last):
  File "E:/Output/Python_output/PARL/PARL-kog/main.py", line 1, in <module>
    import paddle.fluid
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\paddle\fluid\__init__.py", line 18, in <module>
    from . import framework
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\paddle\fluid\framework.py", line 33, in <module>
    directory. The original error is: \n""" + cpt.get_exception_message(e))
ImportError: NOTE: You may need to run "export LD_LIBRARY_PATH=/usr/local/lib:$LD_LIBRARY_PATH"
    if you encounters "libmkldnn.so not found" errors. If you have python
    installed in other directory, replace "/usr/local/lib" with your own
    directory. The original error is: 
DLL load failed: 找不到指定的程序。
```
从错误信息看，是没做绑定。 @wopeizl @junjun315

**Comment by lluck42** [comment]
noavx 版本可以

在 2019-04-12 12:04:40，"wopeizl" <notifications@github.com> 写道：


机器cpu是什么型号的 可以尝试一下noavx的版本

**Comment by ChenShaomin** [comment]
我遇到同样的问题，刚开始可以通过修改Python.exe权限和安装openblas版本的安装包解决。后来发现paddle默认需要mkl库，重新创建的环境里没有mkl，安装paddle的时候也没有自动安装mkl，手动执行pip install mkl后问题解决。

**Comment by wopeizl** [comment]
1.5fix这个问题

**Comment by sidneyz139** [comment]
我也是import paddle正常，paddle.fluid失败，avx报错，找不到DLL。
CPU Intel i7 3720QM, 有avx, 没有avx2. 有Intel HD graphics 4000, 和NVIDIA NVS 5400M，CUDA 10.0/10.2, cudnn 7.6.5
我现在安装的paddle已经是1.7.0了，安装了mkl.
上文中提到的绑定是什么意思？
我明明安装的是paddlepaddle-gpu的版本，怎么fluid会去试图调用 AVX?
另外，我把paddlepaddle CPU版和GPU版同时安装了，这个问题还是存在。
上文中提到的NOAVX版本，应该怎么获得和安装？

**Comment by sidneyz139** [comment]
@wopeizl @lluck42 @luotao1 
openblas 需要安装什么吗？

**Comment by sidneyz139** [comment]
已经解决了，重新安装了一个干净的Python3.7.
