### ISSUE TITLE
What's the real meaning of FLAGS_fraction_of_gpu_memory_to_use?

### ISSUE THREAD

**Issue by imistyrain** [PaddlePaddle/Paddle#15426]
P40单卡显存24445MiB，paddle-gpu 1.2，且没有其他任务占用显存.
使用models模型里的image calssification训练alexnet
运行的命令为:
```
python train.py \
     --model=AlexNet \
     --batch_size=64 \
     --total_images=1281167 \
     --class_dim=1000 \
     --image_shape=3,224,224 \
     --model_save_dir=output/ \
     --with_mem_opt=False \
     --lr_strategy=piecewise_decay \
     --num_epochs=120 \
     --lr=0.01 \
```
当设置FLAGS_fraction_of_gpu_memory_to_use=0.01时，占用显存1773MiB
当设置FLAGS_fraction_of_gpu_memory_to_use=0.1时，占用显存2693MiB
当设置FLAGS_fraction_of_gpu_memory_to_use=0.2时，占用显存5015MiB
更特别的
当设置为FLAGS_fraction_of_gpu_memory_to_use=0时，占用显存在1019MB到1635MB之间波动
有点迷惑了，这个标志的真正含义到底是啥呢？从字面意思是预先申请占用的百分比，但实际结果好像并不是.

**Comment by shippingwang** [comment]
显存使用的比例。@imistyrain 设置with_men_opt=True 当出现提示 调整更小的值。

**Comment by imistyrain** [comment]
但是看上面测出的结果，占用的比例好像不对哦，不知有什么计算公式没？

**Comment by qingqing01** [comment]
@imistyrain 

在Paddle底层有memory管理的Allocator。简单来说分为：SystemAllocator(普通的CPU Allocator和GPU Allocator)和[BuddyAllocator](https://en.wikipedia.org/wiki/Buddy_memory_allocation)，BuddyAllocator是一种内存管理算法，简单来说是每次分配一大块连续内存，称作max_chunk大小，后续再分配内存块时，基于已分配的、空闲的块重分配内存，也可merge释放的内存。如果再次分配内存时，池子没有适合的块来分类，会再次重新分配一大块(max_chunk大小)，重复前面管理。 目的是统一管理内存、加速动态分配的速度。

`FLAGS_fraction_of_gpu_memory_to_use`的作用是确定max_chunk大小，这个大小是:[(总的内存大小-小部分预留内存) *   FLAGS_fraction_of_gpu_memory_to_use](https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/fluid/platform/gpu_info.cc#L194)。 如果是0，BuddyAllocator算法中则调用普通的SystemAllocator；或者分配的大小超过max_chunk大小时，会回退为调用普通的SystemAllocator。否则，则在BuddyAllocator的池子里找，BuddyAllocator来管理内存。

所以您设置不同的`FLAGS_fraction_of_gpu_memory_to_use`大小，看到了不同的显存占用。

**Comment by zzchust** [comment]
怎么通过设置FLAGS_fraction_of_gpu_memory_to_use知道单卡我可以设置的最大batchsize呢？

**Comment by gavin1332** [comment]
> 怎么通过设置FLAGS_fraction_of_gpu_memory_to_use知道单卡我可以设置的最大batchsize呢？

在独占显存情况下，建议将FLAGS_fraction_of_gpu_memory_to_use设置为0.99，这样可以配置尽可能大的batch size

**Comment by gavin1332** [comment]
> 怎么通过设置FLAGS_fraction_of_gpu_memory_to_use知道单卡我可以设置的最大batchsize呢？

在独占显存情况下，建议将FLAGS_fraction_of_gpu_memory_to_use设置为0.99，这样可以配置尽可能大的batch size

**Comment by zzchust** [comment]
已解决。

将FLAGS_fraction_of_gpu_memory_to_use设0，然后watch -n1 nvidia-smi，找到当前batch size对应的最大值，然后计算支持的最大batch size， 再将FLAGS_fraction_of_gpu_memory_to_use设为0.99
