### ISSUE TITLE
Paddle支持低精度训练吗？比如fp16，int16等

### ISSUE THREAD

**Issue by dashulu** [PaddlePaddle/Paddle#15437]
Paddle支持低精度训练吗？有什么教程吗？

**Comment by typhoonzero** [comment]
目前可以支持部分模型在GPU上的FP16训练，参考：https://github.com/PaddlePaddle/models/tree/develop/fluid/PaddleCV/image_classification#using-mixed-precision-training

**Comment by dashulu** [comment]
那paddle现在有工具可以看一个模型训练过程中，需要多少内存、多少计算量吗？

**Comment by dashulu** [comment]
> 目前可以支持部分模型在GPU上的FP16训练

@typhoonzero 
为了支持其他模型低精度训练，需要为模型用到的op都提供一个低精度的kernel实现，对吗？

**Comment by typhoonzero** [comment]
> 为了支持其他模型低精度训练，需要为模型用到的op都提供一个低精度的kernel实现，对吗？

目前大部分kernel已经支持，不支持的的确需要增加对应的kernel实现

**Comment by typhoonzero** [comment]
> 那paddle现在有工具可以看一个模型训练过程中，需要多少内存、多少计算量吗？

这个可以使用`fluid.contrib.memory_usage(program, batch_size)`估计： https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/fluid/contrib/memory_usage_calc.py#L46

**Comment by dashulu** [comment]
> > 为了支持其他模型低精度训练，需要为模型用到的op都提供一个低精度的kernel实现，对吗？
> 
> 目前大部分kernel已经支持，不支持的的确需要增加对应的kernel实现

这边梯度也是用低精度计算的吗，还是float？

**Comment by typhoonzero** [comment]
梯度计算是用fp16，梯度更新会转成fp32防止精度太差

**Comment by freekoy** [comment]
@typhoonzero 
[https://github.com/PaddlePaddle/models/tree/develop/fluid/PaddleCV/image_classification#using-mixed-precision-training](url)
fp16示例报错，使用版本是paddlepaddle fluid1.2.0
运行代码如下
```
python train.py --model=VGG11 --batch_size=32 --total_images=3 --class_dim=1000 --image_shape=3,224,224 --model_save_dir=output/ --with_mem_opt=False --lr_strategy=piecewise_decay --lr=0.1 --fp16=True
```
错误如下
```
Traceback (most recent call last):
  File "train.py", line 426, in <module>
    main()
  File "train.py", line 422, in main
    train(args)
  File "train.py", line 240, in train
    args=args)
  File "train.py", line 205, in build_program
    params_grads = optimizer.backward(avg_cost)
AttributeError: 'MomentumOptimizer' object has no attribute 'backward'
```

**Comment by typhoonzero** [comment]
需要使用develop版本或者等1.3最近发布
