### ISSUE TITLE
预测模型中的问题

### ISSUE THREAD

**Issue by stoiczzz** [PaddlePaddle/Paddle#15430]
v2版本中的paddle.inference.Inference我要加载池化层，则output是pool层，在那fluid版本中模型加载load可以调参数吗?默认调用__model__吗。
此外，dense_vector是获取向量的维度吗?在fliud中有对应函数吗。

因为初学，同时觉得官方文档在v2和fliud中变动较大，网络资料很多是以v2写的，所以想请教一下新版的问题。希望不要嫌弃，嘿嘿。

**Comment by Yancey0623** [comment]
> 在那fluid版本中模型加载load可以调参数吗?默认调用__model__吗。

是说指定models的目录吗？可以参考API：[paddle.fluid.io.load_inference_model](http://paddlepaddle.org/documentation/docs/zh/1.2/api_cn/io_cn.html#load-inference-model)

> dense_vector是获取向量的维度吗?在fliud中有对应函数吗。

dense_vector是data layer的输入类型为稠密向量，在Fluid中可以用 [paddle.fluid.layers.data](http://paddlepaddle.org/documentation/docs/zh/1.2/api_cn/layers_cn.html#data) 即可。

**Comment by stoiczzz** [comment]
> > 在那fluid版本中模型加载load可以调参数吗?默认调用__model__吗。
> 
> 是说指定models的目录吗？可以参考API：[paddle.fluid.io.load_inference_model](http://paddlepaddle.org/documentation/docs/zh/1.2/api_cn/io_cn.html#load-inference-model)
> 
> > dense_vector是获取向量的维度吗?在fliud中有对应函数吗。
> 
> dense_vector是data layer的输入类型为稠密向量，在Fluid中可以用 [paddle.fluid.layers.data](http://paddlepaddle.org/documentation/docs/zh/1.2/api_cn/layers_cn.html#data) 即可。

不，我的意思是在v2中。例如预测程序中可以指定某个神经网络层的数据。例如我不想要最后一层的全连接层预测，可以指定倒数第二层的池化层。
在fliud是要保存两个模型（pool层和fc层）才可以实现吗？fliud也找不到以前的paddle.infer了。就统一exe.run吗？

再补充一个问题，在fliud中我使用plot想要绘图，但报错缺参。无法使用，请问有实例吗

**Comment by Yancey0623** [comment]
> 不，我的意思是在v2中。例如预测程序中可以指定某个神经网络层的数据。例如我不想要最后一层的全连接层预测，可以指定倒数第二层的池化层。
在fliud是要保存两个模型（pool层和fc层）才可以实现吗？

要获取 pooling和fc层的输出么？这个可以通过 Executor 的 fetch_list 参数实现，例如：
``` python
pre = fluid.layers.fc(input=x,size=10)
loss = fluid.layers.cross_entropy(input=pre, label=label)
exe.run(fluid.default_main_program(), feed=feeder.feed(data), fetch_list=[pre, loss])
```

> 再补充一个问题，在fliud中我使用plot想要绘图，但报错缺参。无法使用，请问有实例吗

plot是属于第三方库，fliud中没有默认安装，可以在自己的环境上安装一个。

**Comment by stoiczzz** [comment]
> > 不，我的意思是在v2中。例如预测程序中可以指定某个神经网络层的数据。例如我不想要最后一层的全连接层预测，可以指定倒数第二层的池化层。
> > 在fliud是要保存两个模型（pool层和fc层）才可以实现吗？
> 
> 要获取 pooling和fc层的输出么？这个可以通过 Executor 的 fetch_list 参数实现，例如：
> 
> ```python
> pre = fluid.layers.fc(input=x,size=10)
> loss = fluid.layers.cross_entropy(input=pre, label=label)
> exe.run(fluid.default_main_program(), feed=feeder.feed(data), fetch_list=[pre, loss])
> ```
> 
> > 再补充一个问题，在fliud中我使用plot想要绘图，但报错缺参。无法使用，请问有实例吗
> 
> plot是属于第三方库，fliud中没有默认安装，可以在自己的环境上安装一个。

那我需要保存2个模型吗？还是只需要保存一个模型，之后可以根据参数选择加载pool层或fc层吗？

下面这个问题，谢谢，jupyter上貌似可以。

**Comment by Yancey0623** [comment]
> 之后可以根据参数选择加载pool层或fc层吗？

你说的加载pool和fc是指啥呢？Executr.run里的fetch_list参数只能获取某一层的输出，如果是模型不同，那可能需要保存成不同的模型了。

**Comment by stoiczzz** [comment]
> > 之后可以根据参数选择加载pool层或fc层吗？
> 
> 你说的加载pool和fc是指啥呢？Executr.run里的fetch_list参数只能获取某一层的输出，如果是模型不同，那可能需要保存成不同的模型了。

我的意思是一个模型在返回2个数据，分别是倒数第二层的池化层和最后一层的全连接层（分类器）。然后在加载预测模型时load_inference_model，可以指定获取的是哪个层的输出吗，还是就是对应save_inference_model的时候中指定target_vars为pool层，加载预测模型也只能获取到池化层的数据

pool, net = top3_CNN(image)
.................
fluid.io.save_inference_model(dirname=fc_model, feeded_var_names=['image'], target_vars=[net],executor=exe)
fluid.io.save_inference_model(dirname=pool_model, feeded_var_names=['image'], target_vars=[pool],executor=exe)

需要这样吗。

[infer_program,feeded_var_names,target_vars]=fluid.io.load_inference_model(dirname=fc_model,executor=exe)
[infer_program1,feeded_var_names1,target_vars1]=fluid.io.load_inference_model(dirname=pool_model,executor=exe)

**Comment by Yancey0623** [comment]
只保存一个模型就可以了：
```fluid.io.save_inference_model(dirname=fc_model, feeded_var_names=['image'], target_vars=[net,pool],executor=exe)```

**Comment by stoiczzz** [comment]
> 只保存一个模型就可以了：
> `fluid.io.save_inference_model(dirname=fc_model, feeded_var_names=['image'], target_vars=[net,pool],executor=exe)`

谢谢你！

**Comment by mask0918** [comment]
> 只保存一个模型就可以了：
> `fluid.io.save_inference_model(dirname=fc_model, feeded_var_names=['image'], target_vars=[net,pool],executor=exe)`

那在加载预测模型时，只要调整params_filename的参数就可以了，指定net或者Pool
