### ISSUE TITLE
group normalization使用

### ISSUE THREAD

**Issue by littletomatodonkey** [PaddlePaddle/Paddle#15435]
我在使用GN的时候，会报出以下的错误

> mean_out = helper.create_tmp_variable(dtype=dtype, stop_gradient=True)
> AttributeError: 'LayerHelper' object has no attribute 'create_tmp_variable'

调用的代码如下
```
out = fluid.layers.group_norm(conv, groups=32,
                                      param_attr=ParamAttr(name=gn_name + '_gamma'),
                                      bias_attr=ParamAttr(name=gn_name + '_beta'),
                                      act=act)
```
想问一下GN的正确使用方式，谢谢啦

**Comment by luotao1** [comment]
@littletomatodonkey 请问这是哪个fluid版本？
@cjld 请问能帮忙看下么？

**Comment by littletomatodonkey** [comment]
1.2.0 ，我在安装好的paddle包里的nn.py里面搜索，看到conv2d、layer norm等函数都是使用的create_variable_for_type_inference创建variable，在group norm里面使用的是create_tmp_variable，我把create_tmp_variable修改为create_variable_for_type_inference，就可以正常运行了，但是不知道为什么原始的gn会报错

**Comment by qingqing01** [comment]
@littletomatodonkey 多谢反馈，这个问题在develop分支已经修复。

**Comment by littletomatodonkey** [comment]
恩恩好的
