### ISSUE TITLE
编译安装失败

### ISSUE THREAD

**Issue by shippingwang** [PaddlePaddle/Paddle#15439]
编译安装失败 make出现error
docker image:  hub.baidubce.com/paddlepaddle/paddle:latest-dev

![image](https://user-images.githubusercontent.com/13645332/51455131-1e6ea600-1d83-11e9-9047-d094e453df3b.png)

**Comment by luotao1** [comment]
fixed by #15109, 请重新pull latest-dev镜像
`docker pull paddlepaddle/paddle:latest-dev`

**Comment by shippingwang** [comment]
rm -rf 
make clean尝试多次 
cmake .. -DWITH_GPU=ON -DWITH_TESTING=ON -DCMAKE_BUILD_TYPE=Release 
重新编译安装，成功
