### ISSUE TITLE
[fluid 1.2] gpu训练时，显存问题报错

### ISSUE THREAD

**Issue by shiyazhou121** [PaddlePaddle/Paddle#15458]
这个报错是需要的显存大于可利用的吗？我应该怎么优化这个问题？尝试过FLAGS_fraction_of_gpu_memory_to_use = 0.8，没有效果。
试了fluid.memory_optimize，没有效果。
![image](https://user-images.githubusercontent.com/15082798/51510770-6e0fa900-1e39-11e9-866d-9d32d7d540e6.png)

paddle.fluid.core.EnforceNotMet: Enforce failed. Expected allocating <= available, but received allocating:20998686233 > available:19587333888.
Insufficient GPU memory to allocation. at [/paddle/paddle/fluid/platform/gpu_info.cc:170]
PaddlePaddle Call Stacks:
0       0x7f22456da6a6p paddle::platform::EnforceNotMet::EnforceNotMet(std::__exception_ptr::exception_ptr, char const*, int) + 486
1       0x7f224707162ep paddle::platform::GpuMaxChunkSize() + 782
2       0x7f224706adaap
3       0x7f2280848a90p pthread_once + 80
4       0x7f224706a21dp paddle::memory::legacy::GetGPUBuddyAllocator(int) + 93
5       0x7f224706a505p void* paddle::memory::legacy::Alloc<paddle::platform::CUDAPlace>(paddle::platform::CUDAPlace const&, unsigned long) + 37
6       0x7f224706abb5p paddle::memory::allocation::LegacyAllocator::AllocateImpl(unsigned long, paddle::memory::allocation::Allocator::Attr) + 389
7       0x7f224706cafbp paddle::memory::allocation::Allocator::Allocate(unsigned long, paddle::memory::allocation::Allocator::Attr) + 27

**Comment by chengduoZH** [comment]
@shiyazhou121 这是由于batch太大以至于GPU的显存不够导致的，有两种方案
- 将FLAGS_fraction_of_gpu_memory_to_use调小一点，比如0.4或这个0.1，但是这样会导致程序运行变慢
- 减少batch_size

**Comment by shiyazhou121** [comment]
@chengduoZH 我尝试了这两种方法，均没有效果，报错没有任何改变，不知道是不是我用法的问题。
![image](https://user-images.githubusercontent.com/15082798/51514209-bc2ca880-1e49-11e9-826c-03eb52f4edb8.png)

batch_size 从256改成20，也没有效果

**Comment by chengduoZH** [comment]
@shiyazhou121 你不要在Python里面设置FLAGS_fraction_of_gpu_memory_to_use，应该在环境变量里面添加，即：`export FLAGS_fraction_of_gpu_memory_to_use=0.1`.
另外，batch_size 从256改成20之后，GPU显存占用应该会变少的，不清楚您的模型配置是否有问题。

**Comment by shiyazhou121** [comment]
@chengduoZH 确实设置环境变量后，可以训练了，batch_size的问题，我再排查下，谢谢啦

**Comment by MrTuo** [comment]
题外话，想问问为什么要用FLAGS_fraction_of_gpu_memory_to_use这种机制去预分配内存呢？这样岂不是自己在每次训练之前还要看这块卡上还剩多少内存，然后手动去算这个百分比，然后再去手动设置，是不是有点蠢呢。。。

**Comment by MrTuo** [comment]
> @shiyazhou121 你不要在Python里面设置FLAGS_fraction_of_gpu_memory_to_use，应该在环境变量里面添加，即：`export FLAGS_fraction_of_gpu_memory_to_use=0.1`.
> 另外，batch_size 从256改成20之后，GPU显存占用应该会变少的，不清楚您的模型配置是否有问题。

题外话，想问问为什么要用FLAGS_fraction_of_gpu_memory_to_use这种机制去预分配内存呢？这样岂不是自己在每次训练之前还要看这块卡上还剩多少内存，然后手动去算这个百分比，然后再去手动设置，是不是有点蠢呢。。。
