### ISSUE TITLE
Bug for layers.create_parameter

### ISSUE THREAD

**Issue by jiangjiajun** [PaddlePaddle/Paddle#15456]
```
import paddle.fluid as fluid
inputs = fluid.layers.create_parameter(shape=[2, 4], dtype='int32', name='xxxx')
exe = fluid.Executor(fluid.CPUPlace())
exe.run(fluid.default_startup_program())
```
当dtype为int32时，上述代码运行出core，问题可复现
当dtype改为float32时，代码运行无问题

**Comment by typhoonzero** [comment]
默认的parameter的初始化op (uniform_random) 没有int32类型的kernel，random类的op一般会生成0~1之间的分布，如果是int32可以使用：`create_parameter(...., default_initializer=fluid.initializer.Constant(100))`

我会在这个API中增加一些check，抛出比较友好的warning。
