### ISSUE TITLE
ProgramDesc输出的格式是什么格式？用什么工具解析？

### ISSUE THREAD

**Issue by dashulu** [PaddlePaddle/Paddle#15467]
programDesc的格式如下：
blocks {
  idx: 4
  parent_idx: 0
  ops {
    inputs {
      parameter: "X"
      arguments: "fill_constant_6.tmp_0"
    }
    outputs {
      parameter: "Out"
      arguments: "learning_rate"
    }
    type: "assign"
    attrs {
      name: "op_role_var"
      type: STRINGS
    }
    attrs {
      name: "op_namescope"
      type: STRING
      s: "/"
    }
    attrs {
      name: "op_role"
      type: INT
      i: 16
    }
  }
}
这个是什么格式？用什么工具解析？

**Comment by chengduoZH** [comment]
你是想借用工具将programDesc可视化出来吗？

**Comment by dashulu** [comment]
> 你是想借用工具将programDesc可视化出来吗？

@chengduoZH 我想通过ProgramDesc获取整个模型的op，以及每个op的参数规模、计算量、内存使用量等信息，包括op的依赖关系。

**Comment by chengduoZH** [comment]
@dashulu 你可以参考一下这个： https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/fluid/contrib/memory_usage_calc.py

**Comment by dashulu** [comment]
这个我看过，但是只是内存相关的东西，无法知道每个op的计算量

**Comment by chengduoZH** [comment]
Op的计算量与OpKernel的实现有关，目前这部分内容目前无法在programDesc中显现

**Comment by chengduoZH** [comment]
你可以用这样的方式保存和加载Program
```
import paddle.fluid as fluid
def simple_fc_net():
    img = fluid.layers.data(name='image', shape=[784], dtype='float32')
    label = fluid.layers.data(name='label', shape=[1], dtype='int64')
    hidden = img
    for _ in range(4):
        hidden = fluid.layers.fc(
            hidden,
            size=200,
            act='tanh',
            bias_attr=fluid.ParamAttr(
                initializer=fluid.initializer.Constant(value=1.0)))
    prediction = fluid.layers.fc(hidden, size=10, act='softmax')
    loss = fluid.layers.cross_entropy(input=prediction, label=label)
    loss = fluid.layers.mean(loss)
    return loss

main_program = fluid.Program()
startup_program = fluid.Program()
with fluid.program_guard(main_program, startup_program):
    loss = simple_fc_net()
    #...
# Save Program to disk
with open('program_bin.txt', "wb") as f:
    f.write(main_program.desc.serialize_to_string())
```
从文件中加载Program：
```
# Load Program from disk
with open('program_bin.txt', 'rb') as f:
    program_desc_str = f.read()

program = fluid.Program.parse_from_string(program_desc_str)
```
