### ISSUE TITLE
conv2d_transpose与tf中conv2d_transpose的差异

### ISSUE THREAD

**Issue by jiangjiajun** [PaddlePaddle/Paddle#15477]
tensorflow里面的conv2d_transpose，output_shape计算是Padding为Same的情况下为input_height * stride, Valid的情况下则为(input_height-1)*stride + kernel_height 

因此在tf中，输入的height和width为[14, 28],  padding='SAME', stride=[2, 2], kernel_size=[3, 3]时，得到的output_shape为[28, 56]
 
而Paddle中，根据文档[conv2d_transpose](http://www.paddlepaddle.org/documentation/docs/zh/1.2/api_cn/layers_cn.html#permalink-43-conv2d_transpose) 中所述，同样的输入，同样的kernel_size，无法得到与tf相同大小的输出。

请问一下paddlepaddle如何能够实现tensorflow中的conv2d_transpose呢？

**Comment by chengduoZH** [comment]
Paddle中关于[conv2d_transpose](http://www.paddlepaddle.org/documentation/docs/en/1.2/api/layers.html#conv2d-transpose)是没有类似于TF中的`SAME`和`VALID`模式的。
关于conv2d_tranpose中输出大小的计算公式如下：
<img width="711" alt="wx20190123-101600 2x" src="https://user-images.githubusercontent.com/30176695/51578353-416e9680-1ef8-11e9-855a-8fac3be87d2a.png">

**Comment by jiangjiajun** [comment]
> Paddle中关于[conv2d_transpose](http://www.paddlepaddle.org/documentation/docs/en/1.2/api/layers.html#conv2d-transpose)是没有类似于TF中的`SAME`和`VALID`模式的。
> 关于conv2d_tranpose中输出大小的计算公式如下：
> <img alt="wx20190123-101600 2x" width="711" src="https://user-images.githubusercontent.com/30176695/51578353-416e9680-1ef8-11e9-855a-8fac3be87d2a.png">

我这边看了下tensorflow的conv2d_transpose，相对比paddle的conv2d_transpose，在padding=SAME的情况下，tensorflow的conv2d_transpose会在最后结果做一个裁剪步骤

因此在同样参数调用下，Paddle的输出是[29, 57]，而tensorflow的输出是[28, 56]

所以要实现与Tensorflow一致，padding为SAME的情况下，paddle需要再调用layers.crop进行处理

**Comment by chengduoZH** [comment]
@jiangjiajun 你可以通过加pad的方式得到与tf输出size一致的结果，这里有例子，你可以看一下：
https://github.com/PaddlePaddle/models/blob/58e9bc20305ea453d50eb924bc94a5f702109888/fluid/PaddleCV/gan/cycle_gan/model.py#L15-L17
