### ISSUE TITLE
关于安装时pip3和pip的区别

### ISSUE THREAD

**Issue by LittleFatHero** [PaddlePaddle/Paddle#15475]
系统：Windows 10专业版
paddlepaddle 版本：fluid

看到官网说在Windows 下的安装命令是pip install paddlepaddle或者是pip3 install paddlepaddle.
我想问的是，使用pip install paddlepaddle安装的paddlepaddle是不是只支持python 2.7而使用
pip3 install paddlepaddle命令安装的paddlepaddle是不是只支持python 3.x？
还是说两个命令安装的paddlepaddle没有区别，是同时支持python 2.7和python 3.x的？

还有想问一下，paddlepaddle大概什么时候可以支持在Windows下进行GPU训练？

paddlepaddle下一个大版本更新是什么时候？

**Comment by chengduoZH** [comment]
> 使用pip install paddlepaddle安装的paddlepaddle是不是只支持python 2.7而使用
pip3 install paddlepaddle命令安装的paddlepaddle是不是只支持python 3.x

是的，如果您是使用Python3.x做开发，需要用pip3安装

> paddlepaddle大概什么时候可以支持在Windows下进行GPU训练？

预计是在1.3版本支持。

> paddlepaddle下一个大版本更新是什么时候？

大概是2月下旬。

**Comment by LittleFatHero** [comment]
你好，如果使用python 3.x做开发，需要使用pip3安装的话，那么能不能在官方的安装文档里说明一下，因为这个很容易引起误解。一般很多新手都直接使用pip来安装，结果使用python3.x来开发，导致一系列问题

**Comment by wopeizl** [comment]
谢谢指出，安装文档里面有说明，http://paddlepaddle.org/documentation/docs/zh/1.2/beginners_guide/install/install_Windows.html

**Comment by LittleFatHero** [comment]
还有一个问题。我的电脑上**只安装了**python 3.6，好像只能使用pip，没有pip3命令。这时候，我使用pip install paddlepaddle命令安装的paddlepaddle是不是和使用pip3安装的paddlepaddle一样的，都只支持python 3.x？因为我电脑上只有一个python版本

**Comment by LittleFatHero** [comment]
PS：安装文档我看过了，就是因为安装文档里没有明确说明才导致了这一系列疑问的

**Comment by GT-ZhangAcer** [comment]
至于pip和pip3的问题，应该是常识，但也希望文档可以标注这一点

**Comment by LittleFatHero** [comment]
还有就是新官网的选环境安装cuda，cuda只有9和8，其实9.x和8.x也是支持的，但是官网没有说，我建议他们把8和9改成8.x和9.x，还是没有改，笑哭

**Comment by joodo** [comment]
您好，感谢反馈，官网现在已经更新了文案，希望您继续关注 PaddlePaddle，谢谢！
