### ISSUE TITLE
内部用户，编译develop版本  `GLIBCXX_3.4.11' not found

### ISSUE THREAD

**Issue by dylanliuli** [PaddlePaddle/Paddle#1548]
idl/paddle/Paddle/third_party/install/protobuf/bin/protoc: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.11' not found
idl/paddle/Paddle/third_party/install/protobuf/bin/protoc: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.10' not found
idl/paddle/Paddle/third_party/install/protobuf/bin/protoc: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.9' not found

没有sudo权限，有不安装glib的方式解决吗？谢谢

**Comment by gangliao** [comment]
Duplicate Issue.

You can find solution from https://github.com/PaddlePaddle/Paddle/pull/1523

**Comment by dylanliuli** [comment]
看上去jumbo下安装成功了，但build依然会调Paddle下的bin：idl/paddle/Paddle/third_party/install/protobuf/bin/protoc

如何配置指定调用jumbo下的版本？

**Comment by gangliao** [comment]
1. rm -rf idl/paddle/Paddle/third_party/
2. cd build && rm -rf *
3. cmake again

记得清理之前的环境啊。。。。。 @dylanliuli

**Comment by dylanliuli** [comment]
是使用paddle_internal_release_tools一键安装，自己替换了devlop版本。
清理了环境，用build.sh还是会调用Paddle下的protoc...
用上面手动方式，会报很多其他编译错误。。
make64[5]: *** [googlemock/gtest/CMakeFiles/gtest.dir/src/gtest-all.cc.o] 错误 1
make64[4]: *** [googlemock/gtest/CMakeFiles/gtest.dir/all] 错误 2

**Comment by gangliao** [comment]
那个已经没人维护了。。可以直接编译啊

**Comment by gangliao** [comment]
@dylanliuli  或者可以尝试这样一个脚本

https://github.com/gangliao/Paddle_Internal_build/blob/master/build.sh

**Comment by dylanliuli** [comment]
是参考了 #1283， 使用的是
icode: baidu/idl/paddle_internal_release_tools

**Comment by gangliao** [comment]
手动配置的方式，不需要一键编译。。。

**Comment by dylanliuli** [comment]
是说用docker安装吗？没有sudo权限，内部用户安装devlop版有stepbystep说明么，环境问题困惑了好久。。。
初衷是为了cpu使用已发布的resnet model，除了使用devlop版本，还有其他途径吗？
其他tag版本的安装用一键安装都很方便。

btw，感谢周末还在帮忙解决问题

**Comment by gangliao** [comment]
https://github.com/gangliao/Paddle_Internal_build/blob/master/build.sh 试一试。。

**Comment by dylanliuli** [comment]
试了下，还是有很多编译问题。
make64[5]: *** [googlemock/gtest/CMakeFiles/gtest.dir/src/gtest-all.cc.o] 错误 1

make64[5]: *** [googlemock/CMakeFiles/gmock_main.dir/src/gmock-all.cc.o] 错误 1
make64[5]: *** [googlemock/CMakeFiles/gmock_main.dir/src/gmock_main.cc.o] 错误 1
make64[4]: *** [googlemock/CMakeFiles/gmock_main.dir/all] 错误 2

**Comment by gangliao** [comment]
好吧  回头hi下我  我帮你看看

**Comment by dylanliuli** [comment]
cc1plus: error: unrecognized command line option "-Wno-missing-field-initializers"

看了下是gcc冲突，有一个低版本（3.4.5）。但已通过cmake .. -DCMAKE_C_COMPILER=xxx -DCMAKE_CXX_COMPILER=xxx  指定高版本（4.8.3），还是会出现上面错误。

**Comment by gangliao** [comment]
记得已经通过下线解决。 所以关闭这个issue
