### ISSUE TITLE
使用ParallelExecutor 进行单机多卡训练时出core

### ISSUE THREAD

**Issue by zhoukunsheng** [PaddlePaddle/Paddle#15481]
paddle 版本：源码编译dev 版

单卡使用Executor 时运行正常，修改成ParallelExecutor 之后运行出错。
![image](https://user-images.githubusercontent.com/29747927/51579766-1c305700-1efd-11e9-8bfc-327395f3cfe3.png)

![image](https://user-images.githubusercontent.com/29747927/51579639-adeb9480-1efc-11e9-938f-93c70aa4c53e.png)

**Comment by kuke** [comment]
可以把配置贴全否，应该是输入有点问题

**Comment by zhoukunsheng** [comment]
![image](https://user-images.githubusercontent.com/29747927/51584337-cd3fed00-1f0f-11e9-885c-ce74e66b5d8d.png)
![image](https://user-images.githubusercontent.com/29747927/51584355-e0eb5380-1f0f-11e9-8ec3-37baea21d0b6.png)

**Comment by kuke** [comment]
@zhoukunsheng dataset.train_reader()出来的数据格式是什么
