### ISSUE TITLE
paddle.dataset.imdb.word_dict() 报错，连接超时

### ISSUE THREAD

**Issue by gninrom** [PaddlePaddle/Paddle#15483]
![image](https://user-images.githubusercontent.com/13362142/51582417-e85a2f00-1f06-11e9-99a2-f3f7bda1d9dc.png)
加载paddle自带的数据集时，显示连接失败，这个该怎么解决？

**Comment by kuke** [comment]
刚尝试过直接wget http://ai.stanford.edu/%7Eamaas/data/sentiment/aclImdb_v1.tar.gz 没有问题，请检查一下网络连接

**Comment by ChenjieXu** [comment]
使用AIstudio时没有网络连接, 如何加载本地数据集?
