### ISSUE TITLE
ValueError: setting an array element with a sequence.

### ISSUE THREAD

**Issue by liushanshan07** [PaddlePaddle/Paddle#15495]
使用pyreader实现识别ctc训练任务，报错为ValueError: setting an array element with a sequence.现象是训练任务挂起，没有显存占用。求问是啥原因（调试发现数据lod对不上，但不会改。不确定本质原因是啥）

1. 原来的数据类型如下，有个python自定义train_reader
`images = fluid.layers.data(name='pixel', shape=data_shape, dtype='float32')`
`label = fluid.layers.data(name='label', shape=[1], dtype='int32', lod_level=1)`

2. 改用py_reader实现如下，decorate_paddle_reader设置reader
`py_reader = fluid.layers.py_reader(
                    capacity=queue_capacity,
                    shapes=[[-1] + image_shape, [-1, 1]],
                    lod_levels=[0, 1],
                    dtypes=["float32", "int32"],
                    use_double_buffer=True)`
` images, label = fluid.layers.read_file(py_reader)`
`train_py_reader.decorate_paddle_reader(train_reader)`

**Comment by kuke** [comment]
@liushanshan07 这里是numpy的报错，应该是用一个形状不对的list去初始化了ndarray，例如
```
>>> A = np.array([1,2,3,[4,5]])
```
会给出一样的报错。猜测是初始化lodtensor的list没有做展开的缘故

**Comment by liushanshan07** [comment]
> @liushanshan07 这里是numpy的报错，应该是用一个形状不对的list去初始化了ndarray，例如
> 
> ```
> >>> A = np.array([1,2,3,[4,5]])
> ```
> 
> 会给出一样的报错。猜测是初始化lodtensor的list没有做展开的缘故

谢谢帮助。求问上述py_reader中哪个位置用到了list初始化np.array？我把python 的train_reader yield类型写在下面。
`img = Image.open(items[2]).convert('L')`
` label = [int(c) + 2 for c in items[-1].split(',')]`
`result = [img, label]`
`yield result`

**Comment by wanghaoshuang** [comment]
images, label = fluid.layers.read_file(py_reader)

在这行之后fluid.layers.Print(label), 看一下label的lod是不是正确？
