### ISSUE TITLE
线上如何使用api进行预估服务

### ISSUE THREAD

**Issue by wangsouc** [PaddlePaddle/Paddle#1550]
线上使用C++进行多线程实时预估，请问使用哪个api可以实现？是线程安全的么？

**Comment by reyoung** [comment]
Related issue #1543

**Comment by csdnlzh** [comment]
求可用CAPI

**Comment by jacquesqiao** [comment]
c-api is provieded https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/capi/examples/model_inference/README.md
