### ISSUE TITLE
fluid.layers.data里面指定的shape与实际输出不符合预期

### ISSUE THREAD

**Issue by hutuxian** [PaddlePaddle/Paddle#15519]
举例来说，输入层指定的shape是[5,1]：
`fluid.layers.data(name="", shape=[5, 1], dtype="int64")`
实际运行时Print出来变成了[1,5]（batch_size为2)。输出如下：
        shape: [2,1,5,]
        dtype: l
        data: 3737,19450,100000,100000,100000,6855,3805,100000,100000,100000,

请问该怎么理解layers.data里面的shape？

**Comment by hutuxian** [comment]
现在问题基本知道出在哪里：shape是以实际数据的shape为准没有与fluid.layers.data()里面定义的shape做相同强制检查。
那么接下来的一个不重要的问题就是有什么场景是没法判断fluid.layers.data()的shape和实际数据的shape的吗？

**Comment by guoshengCS** [comment]
`fluid.layers.data`会在shape的最前面加上一个-1作为batch size，可以参考这里 https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/fluid/layers/io.py#L88

可以认为Fluid中定义网络结构时的shape都是placeholder，实际运行时使用的都是实际数据的shape，如这里的 [2,1,5,]

**Comment by hutuxian** [comment]
谢谢回答。那么placeholder里面的shape的作用是什么呢？只是为了帮助用户编程的时候在编译时提前发现错误吗？
在另一个issue里面看到了类似的问题，[https://github.com/PaddlePaddle/Paddle/issues/13917](https://github.com/PaddlePaddle/Paddle/issues/13917)。不知道后面有什么计划没？

**Comment by guoshengCS** [comment]
Fluid中定义网络结构时的shape能够帮助在编译时提前发现错误，不过一些情况下需要借助于placeholder而不能强制shape固定，如NLP任务中很多时候会是变长的数据，不同batch的数据的shape会是不同的，这时候需要实际的shape可变且和网络定义时的shape不同
