### ISSUE TITLE
demo:recommendation,evaluate error

### ISSUE THREAD

**Issue by Ayle3125** [PaddlePaddle/Paddle#1552]
Here is the tutorial from https://github.com/PaddlePaddle/Paddle/blob/develop/doc/tutorials/rec/ml_regression_cn.rst:

> 在训练了几个轮次以后，你可以对模型进行评估，得到最好轮次下的模型。运行下面命令即可：
> 
> ./evaluate.sh
> 你将看到如下的信息：
> 
> Best pass is 00009,  error is 3.06949, which means predict get error as 0.875998002281
> evaluating from pass output/pass-00009
> 然后，你可以预测任何用户对于任何一部电影的评价，运行下面命令即可：
> 
> python prediction.py 'output/pass-00009/'
> 

In my computer, it looks like:

> 
> $ ./evaluate.sh 
>   File "\<string\>", line 1, in <module>
> ValueError: could not convert string to float: 
> Best pass is ,  error is , which means predict get error as 
> evaluating from pass output/pass-

Could someone help me, please?

**Comment by kuke** [comment]
Closed because of inactivity
