### ISSUE TITLE
对齐tensorflow的保存模型中的max_to_keep和keep_checkpoint_every_n_hours

### ISSUE THREAD

**Issue by imistyrain** [PaddlePaddle/Paddle#15526]
在tensorflow的保存模型的Saver中有两个非常好用的参数max_to_keep和keep_checkpoint_every_n_hours其中
1.max_to_keep：最多保留的检查点数。
2.keep_checkpoint_every_n_hours：保存检查点的时间间隔
目前我暂没有看到paddlepaddle里有类似的参数，只能通过自己实现的逻辑来进行控制，但这是很有用且公共的需求，如果能集成到库里实现就能大大减少不必要的编码.
不知这块有没有进行支持的打算？

**Comment by appleappleorange** [comment]
已经转达框架方向同学进行跟进
