### ISSUE TITLE
编译paddle v1.2版本出错

### ISSUE THREAD

**Issue by dashulu** [PaddlePaddle/Paddle#15544]
编译v1.2版本时，出现如下错误：
/paddle/paddle/fluid/pybind/pybind.cc:90:16: error: expected constructor, destructor, or type conversion before ‘(’ token
 PYBIND11_MODULE(core, m) {
                ^
/paddle/paddle/fluid/pybind/pybind.cc:939:1: error: expected ‘}’ at end of input
 }  // namespace paddle
 ^
/paddle/paddle/fluid/pybind/pybind.cc:939:1: error: expected ‘}’ at end of input

**Comment by dzhwinter** [comment]
需要升级一下pybind。清空一下build环境重新编译就好了。
