### ISSUE TITLE
errors when compile paddle from source code under ubuntu.

### ISSUE THREAD

**Issue by zigennlp** [PaddlePaddle/Paddle#15543]
after git clone source code of paddle 

first
build$ 

> cmake  ---with-extra-cflags --with-extra-cxxflags  -DCMAKE_BUILD_TYPE=Release -DWITH_MKLDNN=OFF -DWITH_GPU=OFF -DWITH_FLUID_ONLY=ON ..

> cd build
> build$ make  CFLAGS='-Wno-implicit-fallthrough'  CXXFLAGS='-Wno-implicit-fallthrough'  

the error message as below：

> [ 14%] Built target profiler_py_proto_init
> paddle/fluid/platform/CMakeFiles/profiler_py_proto.dir/build.make:60: *** target pattern contains no '%'.  Stop.
> CMakeFiles/Makefile2:1811: recipe for target 'paddle/fluid/platform/CMakeFiles/profiler_py_proto.dir/all' failed
> make[1]: *** [paddle/fluid/platform/CMakeFiles/profiler_py_proto.dir/all] Error 2
> Makefile:151: recipe for target 'all' failed
> make: *** [all] Error 2

it seem that not the c or c++ code error ,   I lost at here .

thanks in advance .

**Comment by jacquesqiao** [comment]
This is because the protoc version is not 3.1, please check in you env.

**Comment by zigennlp** [comment]
I check my env of protoc , 

>$ protoc --version
>libprotoc 3.1.0

Maybe there are others issue cause this error.

**Comment by jacquesqiao** [comment]
@JiabinYang please take a look.

**Comment by JiabinYang** [comment]
您是编译的那一个版本的paddle

**Comment by zigennlp** [comment]
@JiabinYang 

我现在配合LAC使用Paddle， LAC 建议:

>$ git checkout v0.14.0

我现在使用的Paddle是： v0.14.0 版本。


https://github.com/baidu/lac/issues/26

上面的链接里有我出错的详细信息， 应该是和protoc有关系！

但是又无从下手。

多谢支持。

**Comment by zigennlp** [comment]
问题已经找到，并且解决了。

一个路径错误，是我对PaddlePaddle的工具链不熟悉造成的。

多谢支持。我关闭这个issue了。
