### ISSUE TITLE
transformer里data层的疑问

### ISSUE THREAD

**Issue by shiyazhou121** [PaddlePaddle/Paddle#15579]
tranformer的fluid实现是参考https://github.com/PaddlePaddle/models/tree/develop/fluid/PaddleNLP/neural_machine_translation/transformer

其中src_word数据层定义是"src_word": [(batch_size, seq_len, 1), "int64", 2], 对应的是data的shape, dtype, lod_level。

以上是tranformer的实现，我在用到自己模型中时，参考上边的配置，结果报错了。
我的数据是将一个句子转变成的序列vector，比如 [[1], [2], [3], [5]]
另外有个疑惑，既然已经做了padding，可以当定长处理，为什么tranformer里用的lod_level = 2.

![image](https://user-images.githubusercontent.com/15082798/51892905-4478f380-23de-11e9-99fe-aebdb4293a9a.png)
![image](https://user-images.githubusercontent.com/15082798/51892911-4a6ed480-23de-11e9-8e13-cf6236156c51.png)

![image](https://user-images.githubusercontent.com/15082798/51892873-31feba00-23de-11e9-8ae2-5add162151b9.png)

**Comment by Superjomn** [comment]
辛苦transformer 的作者答下哈 @kuke

**Comment by kuke** [comment]
已在hi上解答
