### ISSUE TITLE
fluid.layers.grid_sample 梯度计算异常

### ISSUE THREAD

**Issue by kebinC** [PaddlePaddle/Paddle#15583]
测试代码：
stn.py
```
import paddle
import paddle.fluid as fluid
import numpy as np

__all__ = ["STN"]


class STN():
    def __init__(self, ):
        pass

    def net(self, input):
        x = self.localization(input)
        theta = self.fc_loc(x)
        grid = fluid.layers.affine_grid(theta, out_shape=input.shape)
        out = fluid.layers.grid_sampler(input, grid=grid)
        return out

    def localization(self, input):
        x = self.conv_pool_layer(input, 8, 7, 2, 'conv_loc_0')
        x = self.conv_pool_layer(x, 16, 3, 2, 'conv_loc_1')
        out = self.conv_pool_layer(x, 24, 3, 2, 'conv_loc_2')
        return out

    def fc_loc(self, input):
        np_array = np.asarray([1, 0, 0, 0, 1, 0], dtype=np.float32)
        x = fluid.layers.fc(input=input, size=32, act='relu',
                param_attr=fluid.initializer.Constant(value=0),
                bias_attr=fluid.initializer.Constant(value=0),
                name='fc_loc_0')
        x = fluid.layers.fc(input=x, size=6, act=None,
                param_attr=fluid.initializer.Constant(value=0),
                bias_attr=fluid.initializer.NumpyArrayInitializer(np_array),
                name='fc_loc_1')
        out = fluid.layers.reshape(x, shape=[-1, 2, 3])
        return out

    def conv_pool_layer(self,
                      input,
                      num_filters,
                      filter_size,
                      stride,
                      name):
        conv = fluid.layers.conv2d(
            input=input,
            num_filters=num_filters,
            filter_size=filter_size,
            stride=stride,
            act=None,
            name=name)
        pool = fluid.layers.pool2d(
            input=conv,
            pool_size=2,
            pool_stride=2,
            pool_type='max')
        relu = fluid.layers.relu(pool)
        return relu
```

test.py
```
import paddle
import paddle.fluid as fluid
import numpy as np
from stn import STN


def test():

    input_np = np.random.randn(2, 3, 224, 224).astype(np.float32)
    input = fluid.layers.create_global_var(
                shape=[2, 3, 224, 224], value=0, dtype='float32', persistable=True)
    fluid.layers.assign(input_np, input)

    label_np = np.random.randn(2, 3, 224, 224).astype(np.float32)
    label = fluid.layers.create_global_var(
                shape=[2, 3, 224, 224], value=0, dtype='float32', persistable=True)
    fluid.layers.assign(label_np, label)

    stn = STN()
    output = stn.net(input)
    loss = output - label
    avg_loss = fluid.layers.mean(x=loss)

    optimizer = fluid.optimizer.SGD(learning_rate=0.001)
    optimizer.minimize(avg_loss)

    place = fluid.CUDAPlace(0)
    exe = fluid.Executor(place)
    exe.run(fluid.default_startup_program())

    train_exe = fluid.ParallelExecutor(use_cuda=True, loss_name=avg_loss.name)

    fetch_list_train = [avg_loss.name]
    fluid.memory_optimize(fluid.default_main_program(), skip_opt_set=set(fetch_list_train))

    for _ in xrange(10):
        loss = train_exe.run(fetch_list_train)
        print(loss)

test()
```

错误信息：
W0129 16:18:19.649785 91562 device_context.cc:263] Please NOTE: device: 0, CUDA Capability: 35, Driver API Version: 9.0, Runtime API Version: 8.0
W0129 16:18:19.649894 91562 device_context.cc:271] device: 0, cuDNN Version: 5.0.
W0129 16:18:19.649914 91562 device_context.cc:295] WARNING: device: 0. The installed Paddle is compiled with CUDNN 5.1, but CUDNN version in your machine is 5.0, which may cause serious incompatible bug. Please recompile or reinstall Paddle with compatible CUDNN version.
*** Aborted at 1548749905 (unix time) try "date -d @1548749905" if you are using GNU date ***
PC: @                0x0 (unknown)
*** SIGSEGV (@0x60) received by PID 91562 (TID 0x7faa7a079700) from PID 96; stack trace: ***
    @     0x7fab4f967160 (unknown)
    @     0x7fab0945f87b paddle::framework::Tensor::Resize()
    @     0x7fab0839813b paddle::operators::CUDNNGridSampleGradOpKernel<>::Compute()
    @     0x7fab083987c3 _ZNSt17_Function_handlerIFvRKN6paddle9framework16ExecutionContextEEZNKS1_24OpKernelRegistrarFunctorINS0_8platform9CUDAPlaceELb0ELm0EJNS0_9operators27CUDNNGridSampleGradOpKernelIfEENSA_IdEEEEclEPKcSF_iEUlS4_E_E9_M_invokeERKSt9_Any_dataS4_
    @     0x7fab093d1573 paddle::framework::OperatorWithKernel::RunImpl()
    @     0x7fab093ced65 paddle::framework::OperatorBase::Run()
    @     0x7fab0927baca paddle::framework::details::ComputationOpHandle::RunImpl()
    @     0x7fab092930e6 paddle::framework::details::OpHandleBase::Run()
    @     0x7fab09218ccd _ZZN6paddle9framework7details24ThreadedSSAGraphExecutor5RunOpERKSt10shared_ptrINS0_13BlockingQueueIPNS1_13VarHandleBaseEEEEPNS1_12OpHandleBaseEENKUlvE_clEv
    @     0x7fab08bb8ad3 std::_Function_handler<>::_M_invoke()
    @     0x7fab086e82e7 std::__future_base::_State_base::_M_do_set()
    @     0x7fab4f964973 __GI___pthread_once
    @     0x7fab092179b2 _ZNSt13__future_base11_Task_stateISt5_BindIFZN6paddle9framework7details24ThreadedSSAGraphExecutor5RunOpERKSt10shared_ptrINS3_13BlockingQueueIPNS4_13VarHandleBaseEEEEPNS4_12OpHandleBaseEEUlvE_vEESaIiEFvvEE6_M_runEv
    @     0x7fab086e9574 _ZZN10ThreadPoolC1EmENKUlvE_clEv
    @     0x7fab241ee8a0 execute_native_thread_routine
    @     0x7fab4f95f1c3 start_thread
    @     0x7fab4ef8712d __clone
    @                0x0 (unknown)
Segmentation fault

**Comment by Superjomn** [comment]
![image](https://user-images.githubusercontent.com/328693/51894190-11386380-23e2-11e9-98e3-9ca6bf19f044.png)
![image](https://user-images.githubusercontent.com/328693/51894199-1695ae00-23e2-11e9-8daa-da09b3bdeb5f.png)

**Comment by kebinC** [comment]
> 测试代码：
> stn.py
> 
> ```
> import paddle
> import paddle.fluid as fluid
> import numpy as np
> 
> __all__ = ["STN"]
> 
> 
> class STN():
>     def __init__(self, ):
>         pass
> 
>     def net(self, input):
>         x = self.localization(input)
>         theta = self.fc_loc(x)
>         grid = fluid.layers.affine_grid(theta, out_shape=input.shape)
>         out = fluid.layers.grid_sampler(input, grid=grid)
>         return out
> 
>     def localization(self, input):
>         x = self.conv_pool_layer(input, 8, 7, 2, 'conv_loc_0')
>         x = self.conv_pool_layer(x, 16, 3, 2, 'conv_loc_1')
>         out = self.conv_pool_layer(x, 24, 3, 2, 'conv_loc_2')
>         return out
> 
>     def fc_loc(self, input):
>         np_array = np.asarray([1, 0, 0, 0, 1, 0], dtype=np.float32)
>         x = fluid.layers.fc(input=input, size=32, act='relu',
>                 param_attr=fluid.initializer.Constant(value=0),
>                 bias_attr=fluid.initializer.Constant(value=0),
>                 name='fc_loc_0')
>         x = fluid.layers.fc(input=x, size=6, act=None,
>                 param_attr=fluid.initializer.Constant(value=0),
>                 bias_attr=fluid.initializer.NumpyArrayInitializer(np_array),
>                 name='fc_loc_1')
>         out = fluid.layers.reshape(x, shape=[-1, 2, 3])
>         return out
> 
>     def conv_pool_layer(self,
>                       input,
>                       num_filters,
>                       filter_size,
>                       stride,
>                       name):
>         conv = fluid.layers.conv2d(
>             input=input,
>             num_filters=num_filters,
>             filter_size=filter_size,
>             stride=stride,
>             act=None,
>             name=name)
>         pool = fluid.layers.pool2d(
>             input=conv,
>             pool_size=2,
>             pool_stride=2,
>             pool_type='max')
>         relu = fluid.layers.relu(pool)
>         return relu
> ```
> test.py
> 
> ```
> import paddle
> import paddle.fluid as fluid
> import numpy as np
> from stn import STN
> 
> 
> def test():
> 
>     input_np = np.random.randn(2, 3, 224, 224).astype(np.float32)
>     input = fluid.layers.create_global_var(
>                 shape=[2, 3, 224, 224], value=0, dtype='float32', persistable=True)
>     fluid.layers.assign(input_np, input)
> 
>     label_np = np.random.randn(2, 3, 224, 224).astype(np.float32)
>     label = fluid.layers.create_global_var(
>                 shape=[2, 3, 224, 224], value=0, dtype='float32', persistable=True)
>     fluid.layers.assign(label_np, label)
> 
>     stn = STN()
>     output = stn.net(input)
>     loss = output - label
>     avg_loss = fluid.layers.mean(x=loss)
> 
>     optimizer = fluid.optimizer.SGD(learning_rate=0.001)
>     optimizer.minimize(avg_loss)
> 
>     place = fluid.CUDAPlace(0)
>     exe = fluid.Executor(place)
>     exe.run(fluid.default_startup_program())
> 
>     train_exe = fluid.ParallelExecutor(use_cuda=True, loss_name=avg_loss.name)
> 
>     fetch_list_train = [avg_loss.name]
>     fluid.memory_optimize(fluid.default_main_program(), skip_opt_set=set(fetch_list_train))
> 
>     for _ in xrange(10):
>         loss = train_exe.run(fetch_list_train)
>         print(loss)
> 
> test()
> ```
> 错误信息：
> W0129 16:18:19.649785 91562 device_context.cc:263] Please NOTE: device: 0, CUDA Capability: 35, Driver API Version: 9.0, Runtime API Version: 8.0
> W0129 16:18:19.649894 91562 device_context.cc:271] device: 0, cuDNN Version: 5.0.
> W0129 16:18:19.649914 91562 device_context.cc:295] WARNING: device: 0. The installed Paddle is compiled with CUDNN 5.1, but CUDNN version in your machine is 5.0, which may cause serious incompatible bug. Please recompile or reinstall Paddle with compatible CUDNN version.
> *** Aborted at 1548749905 (unix time) try "date -d @1548749905" if you are using GNU date ***
> PC: @ 0x0 (unknown)
> *** SIGSEGV (@0x60) received by PID 91562 (TID 0x7faa7a079700) from PID 96; stack trace: ***
> @ 0x7fab4f967160 (unknown)
> @ 0x7fab0945f87b paddle::framework::Tensor::Resize()
> @ 0x7fab0839813b paddle::operators::CUDNNGridSampleGradOpKernel<>::Compute()
> @ 0x7fab083987c3 _ZNSt17_Function_handlerIFvRKN6paddle9framework16ExecutionContextEEZNKS1_24OpKernelRegistrarFunctorINS0_8platform9CUDAPlaceELb0ELm0EJNS0_9operators27CUDNNGridSampleGradOpKernelIfEENSA_IdEEEEclEPKcSF_iEUlS4_E_E9_M_invokeERKSt9_Any_dataS4_
> @ 0x7fab093d1573 paddle::framework::OperatorWithKernel::RunImpl()
> @ 0x7fab093ced65 paddle::framework::OperatorBase::Run()
> @ 0x7fab0927baca paddle::framework::details::ComputationOpHandle::RunImpl()
> @ 0x7fab092930e6 paddle::framework::details::OpHandleBase::Run()
> @ 0x7fab09218ccd _ZZN6paddle9framework7details24ThreadedSSAGraphExecutor5RunOpERKSt10shared_ptrINS0_13BlockingQueueIPNS1_13VarHandleBaseEEEEPNS1_12OpHandleBaseEENKUlvE_clEv
> @ 0x7fab08bb8ad3 std::_Function_handler<>::_M_invoke()
> @ 0x7fab086e82e7 std::__future_base::_State_base::_M_do_set()
> @ 0x7fab4f964973 __GI___pthread_once
> @ 0x7fab092179b2 _ZNSt13__future_base11_Task_stateISt5_BindIFZN6paddle9framework7details24ThreadedSSAGraphExecutor5RunOpERKSt10shared_ptrINS3_13BlockingQueueIPNS4_13VarHandleBaseEEEEPNS4_12OpHandleBaseEEUlvE_vEESaIiEFvvEE6_M_runEv
> @ 0x7fab086e9574 _ZZN10ThreadPoolC1EmENKUlvE_clEv
> @ 0x7fab241ee8a0 execute_native_thread_routine
> @ 0x7fab4f95f1c3 start_thread
> @ 0x7fab4ef8712d __clone
> @ 0x0 (unknown)
> Segmentation fault

没有加fluid.layers.grid_sample也会出现cudnn版本不一致的警告，但不影响运行

**Comment by chengduoZH** [comment]
@kebinC 你那边可以先将cudnn更新成5.1试试 可以吗？

**Comment by kebinC** [comment]
> @kebinC 你那边可以先将cudnn更新成5.1试试 可以吗？

换成cudnn5.1后，就没有WARNING了，但还是有梯度的问题

W0129 17:06:26.513718 70165 device_context.cc:263] Please NOTE: device: 0, CUDA Capability: 35, Driver API Version: 9.0, Runtime API Version: 8.0
W0129 17:06:26.513835 70165 device_context.cc:271] device: 0, cuDNN Version: 5.1.
*** Aborted at 1548752793 (unix time) try "date -d @1548752793" if you are using GNU date ***
PC: @                0x0 (unknown)
*** SIGSEGV (@0x60) received by PID 70165 (TID 0x7fbc71745700) from PID 96; stack trace: ***
    @     0x7fbd502c4160 (unknown)
    @     0x7fbd0ac4d87b paddle::framework::Tensor::Resize()
    @     0x7fbd09b8613b paddle::operators::CUDNNGridSampleGradOpKernel<>::Compute()
    @     0x7fbd09b867c3 _ZNSt17_Function_handlerIFvRKN6paddle9framework16ExecutionContextEEZNKS1_24OpKernelRegistrarFunctorINS0_8platform9CUDAPlaceELb0ELm0EJNS0_9o$erators27CUDNNGridSampleGradOpKernelIfEENSA_IdEEEEclEPKcSF_iEUlS4_E_E9_M_invokeERKSt9_Any_dataS4_
    @     0x7fbd0abbf573 paddle::framework::OperatorWithKernel::RunImpl()
    @     0x7fbd0abbcd65 paddle::framework::OperatorBase::Run()
    @     0x7fbd0aa69aca paddle::framework::details::ComputationOpHandle::RunImpl()
    @     0x7fbd0aa810e6 paddle::framework::details::OpHandleBase::Run()

**Comment by heavengate** [comment]
> W0129 19:27:45.514364 131197 device_context.cc:203] Please NOTE: device: 0, CUDA Capability: 70, Driver Version: 9.2, Runtime Version: 9.2
W0129 19:27:45.514426 131197 device_context.cc:210] device: 0, cuDNN Version: 7.0.
[array([0.01646649], dtype=float32)]
[array([0.01338135], dtype=float32)]
[array([0.01144676], dtype=float32)]
[array([0.00995981], dtype=float32)]
[array([0.00882449], dtype=float32)]
[array([0.00791433], dtype=float32)]
[array([0.00822456], dtype=float32)]
[array([0.00796479], dtype=float32)]
[array([0.00762382], dtype=float32)]
[array([0.00814216], dtype=float32)]

CUDNN7 上非复现出这个问题，请问你那边能换高一点的CUDNN版本么，我也找找CUDNN5或者CUDNN6的版本测一下

**Comment by kebinC** [comment]
我换了cudnn7，还是报上面的错误
换成cudnn7.1, 报了新的问题：

Traceback (most recent call last):
  File "test_stn2.py", line 40, in <module>
    test()
  File "test_stn2.py", line 29, in test
    exe.run(fluid.default_startup_program())
  File "/home/users/chenkaibing/env/paddle-release-cudnn7/python-gcc482-paddle/lib/python2.7/site-packages/paddle/fluid/executor.py", line 525, in run
    use_program_cache=use_program_cache)
  File "/home/users/chenkaibing/env/paddle-release-cudnn7/python-gcc482-paddle/lib/python2.7/site-packages/paddle/fluid/executor.py", line 591, in _run
    exe.run(program.desc, scope, 0, True, True)
paddle.fluid.core.EnforceNotMet: Invoke operator fill_constant error.
Python Callstacks:
  File "/home/users/chenkaibing/env/paddle-release-cudnn7/python-gcc482-paddle/lib/python2.7/site-packages/paddle/fluid/framework.py", line 1373, in _prepend_op
    attrs=kwargs.get("attrs", None))
  File "/home/users/chenkaibing/env/paddle-release-cudnn7/python-gcc482-paddle/lib/python2.7/site-packages/paddle/fluid/initializer.py", line 167, in __call__
    stop_gradient=True)
  File "/home/users/chenkaibing/env/paddle-release-cudnn7/python-gcc482-paddle/lib/python2.7/site-packages/paddle/fluid/framework.py", line 1192, in create_var
    kwargs['initializer'](var, self)
  File "/home/users/chenkaibing/env/paddle-release-cudnn7/python-gcc482-paddle/lib/python2.7/site-packages/paddle/fluid/layer_helper.py", line 390, in set_variable_$
nitializer
    initializer=initializer)
  File "/home/users/chenkaibing/env/paddle-release-cudnn7/python-gcc482-paddle/lib/python2.7/site-packages/paddle/fluid/layers/tensor.py", line 137, in create_globa$
_var
    value=float(value), force_cpu=force_cpu))
  File "/home/users/chenkaibing/env/paddle-release-cudnn7/python-gcc482-paddle/lib/python2.7/site-packages/paddle/fluid/optimizer.py", line 92, in _create_global_le$
rning_rate
    persistable=True)
  File "/home/users/chenkaibing/env/paddle-release-cudnn7/python-gcc482-paddle/lib/python2.7/site-packages/paddle/fluid/optimizer.py", line 224, in _create_optimiza$
ion_pass
    self._create_global_learning_rate()
  File "/home/users/chenkaibing/env/paddle-release-cudnn7/python-gcc482-paddle/lib/python2.7/site-packages/paddle/fluid/optimizer.py", line 350, in apply_gradients
    optimize_ops = self._create_optimization_pass(params_grads)
  File "/home/users/chenkaibing/env/paddle-release-cudnn7/python-gcc482-paddle/lib/python2.7/site-packages/paddle/fluid/optimizer.py", line 405, in minimize
    optimize_ops = self.apply_gradients(params_grads)
  File "test_stn2.py", line 25, in test

**Comment by heavengate** [comment]
> W0129 20:47:54.938205 213486 device_context.cc:213] Please NOTE: device: 0, CUDA Capability: 70, Driver Version: 9.2, Runtime Version: 9.2
W0129 20:47:54.938258 213486 device_context.cc:220] device: 0, cuDNN Version: 5.1.
[array([-0.00814993], dtype=float32)]
[array([-0.00021479], dtype=float32)]
[array([-0.00416845], dtype=float32)]
[array([-0.00395859], dtype=float32)]
[array([-0.00456897], dtype=float32)]
[array([-0.00368273], dtype=float32)]
[array([-0.00547487], dtype=float32)]
[array([-0.0044285], dtype=float32)]
[array([-0.00413001], dtype=float32)]
[array([-0.00506805], dtype=float32)]

编了下5.1的版本也没有报这个错，请问一下你的paddle是如何安装的

**Comment by kebinC** [comment]
> > W0129 20:47:54.938205 213486 device_context.cc:213] Please NOTE: device: 0, CUDA Capability: 70, Driver Version: 9.2, Runtime Version: 9.2
> > W0129 20:47:54.938258 213486 device_context.cc:220] device: 0, cuDNN Version: 5.1.
> > [array([-0.00814993], dtype=float32)]
> > [array([-0.00021479], dtype=float32)]
> > [array([-0.00416845], dtype=float32)]
> > [array([-0.00395859], dtype=float32)]
> > [array([-0.00456897], dtype=float32)]
> > [array([-0.00368273], dtype=float32)]
> > [array([-0.00547487], dtype=float32)]
> > [array([-0.0044285], dtype=float32)]
> > [array([-0.00413001], dtype=float32)]
> > [array([-0.00506805], dtype=float32)]
> 
> 编了下5.1的版本也没有报这个错，请问一下你的paddle是如何安装的

@heavengate 我从官方网站下载的paddle whl包也会报这个问题，请问你的测试环境是什么？我这边是
k40机器 + cuda8.0 + cudnn5.1

**Comment by kebinC** [comment]
@heavengate 看下这个测试代码可以跑过吗？
```
import paddle
import paddle.fluid as fluid
import numpy as np
from stn import STN


def test():

    input = fluid.layers.data(name='input', shape=[3, 224, 224], dtype='float32')
    label = fluid.layers.data(name='label', shape=[3, 224, 224], dtype='float32')

    stn = STN()
    output = stn.net(input)
    loss = output - label
    avg_loss = fluid.layers.mean(x=loss)

    optimizer = fluid.optimizer.SGD(learning_rate=0.001)
    optimizer.minimize(avg_loss)

    place = fluid.CUDAPlace(0)
    exe = fluid.Executor(place)
    exe.run(fluid.default_startup_program())

    train_exe = fluid.ParallelExecutor(use_cuda=True, loss_name=avg_loss.name)

    fetch_list_train = [avg_loss.name]
    fluid.memory_optimize(fluid.default_main_program(), skip_opt_set=set(fetch_list_train))

    for _ in xrange(10):
        input_np = np.random.randn(8, 3, 224, 224).astype(np.float32)
        label_np = np.random.randn(8, 3, 224, 224).astype(np.float32)
        loss = train_exe.run(fetch_list_train, feed={'input': input_np, 'label': label_np})
        print(loss)

test()
```

**Comment by heavengate** [comment]
该问题触发原因如下：
由于grid_sampler的输入input为网络输入，即layers.data，layers.data默认的stop_gradient=True，故在grid_sampler里面关于input的grad无法注册，而cudnn的api需要计算关于input的梯度（grid_sampler也可能输入时featuremap）, 故报错。
解决方法：
将input的stop_gradient置为False，如下
input = fluid.layers.data(name='input', shape=[3, 224, 224], dtype='float32', stop_gradient=False)
