### ISSUE TITLE
文档

### ISSUE THREAD

**Issue by shippingwang** [PaddlePaddle/Paddle#15580]
我们的文档 现在更新的频率很快，文档越来越好，是不是可以飘个new之类的，比如说前几天我看[py_reader](http://paddlepaddle.org/documentation/docs/zh/1.2/user_guides/howto/prepare_data/use_py_reader.html)
 文档不全，现在已经改善了，这种“惊喜”感，是不是可以放出来说一下。

比如：XX文档有更新，或者标志一下XX文档的最后更新的时间。

**Comment by shanyi15** [comment]
感谢建议。
另，目前文档已迁移到[FluidDoc](https://github.com/PaddlePaddle/FluidDoc)作统一管理，后续如有建议也欢迎在该Repo建立Issue，谢谢！
