### ISSUE TITLE
请问PaddlePaddle区分LoDTensor是不是偏移表示，是不是根据提lod-Tensor第一个值是否为0来界定的？

### ISSUE THREAD

**Issue by newdimitri** [PaddlePaddle/Paddle#15581]
如题，
还有一个问题LoDTensor适用于大规模稀疏数据吗？

**Comment by Superjomn** [comment]
LoDTensor 的话，本身就是基于相对偏移的

http://www.paddlepaddle.org/documentation/docs/zh/1.2/api_cn/fluid_cn.html#paddle.fluid.LoDTensor

另外，LoDTensor 暂不支持稀疏矩阵。


但如果是分布式embedding的话，那可能是另外一回事了。
