### ISSUE TITLE
fluid API如何从文件读取离散稀疏特征

### ISSUE THREAD

**Issue by kjfren1985** [PaddlePaddle/Paddle#15595]
数据格式类似：
LineNum  \t  Label  \t  Feas

Feas类似：1 32 64 512 1023;  共1024维

paddle版本：paddlepaddle_gpu-1.2.0.post87-cp27-cp27mu-linux_x86_64.whl

**Comment by seiriosPlus** [comment]
去paddle models下看看ctr的模型配置和数据读取配置， 原理是一样的。

**Comment by kjfren1985** [comment]
> 去paddle models下看看ctr的模型配置和数据读取配置， 原理是一样的。

看了下这个例子，这个例子里面是30维左右的离散特征，我的实际生成环境是特征10万维左右，会不会有性能问题？

**Comment by seiriosPlus** [comment]
> > 去paddle models下看看ctr的模型配置和数据读取配置， 原理是一样的。
> 
> 看了下这个例子，这个例子里面是30维左右的离散特征，我的实际生成环境是特征10万维左右，会不会有性能问题？

10万维的话可能会有性能问题，用法是一样的，你可以试一下，先看一下功能和用法能否满足，性能可以优化

**Comment by kjfren1985** [comment]
`sparse_embed_seq = list(map(embedding_layer, words[1:-1]))`

`concated = fluid.layers.concat(sparse_embed_seq + words[0:1], axis=1)`

`fc1 = fluid.layers.fc(input=concated, size=400, act='relu',
                          param_attr=fluid.ParamAttr(initializer=fluid.initializer.Normal(
                              scale=1 / math.sqrt(concated.shape[1]))))
`

在network_conf.py中，网络配置处把输入离散特征进行了embedding，可以不embedding直接输入吗（因为我们业务上embedding之后模型效果会变差）？维度如何指定？

**Comment by qingqing01** [comment]
@kjfren1985 

了解到直接使用sparse数据输入，使用sparse fc来计算。可以使用embedding + sequence_pool来等价次方式，前提是输入的sparse输入数据没有权重。numpy的模拟代码验证没问题:

```python
import numpy as np
from scipy.sparse import csr_matrix

emb = np.random.random((10, 8)).astype("float32")
index = [[0, 4], [1, 3, 7]]

o1 = []
for d in index:
  o1.append(np.sum(emb[d], axis=0))
o1 = np.array(o1)
print('embedding + pool: ', o1)


data = [1, 1, 1, 1, 1] # sparse binary数据，每个位置上都是1，没有权重。
row = np.array([0, 0, 1, 1, 1])
col = np.array([0, 4, 1, 3, 7]) 
st = csr_matrix((data, (row, col)), shape=(2, 10)).toarray()
o2 = np.matmul(st,emb)
print('sparse_gemm: ', o2)
```

sequence_pool文档: http://paddlepaddle.org/documentation/docs/zh/1.2/api_cn/layers_cn.html#sequence-pool

**Comment by kjfren1985** [comment]
再问下，ctr示例中其实是13个连续特征，27个离散特征，相当于还是定长的；
我的特征如下：
Feas类似：1 32 64 512 10232; 共10万维
可能长度不同，并且比较稀疏，弄成10万个值的矩阵显然不太合理，怎么读入比较合理？
