### ISSUE TITLE
seqToseq 找不到src.dict??

### ISSUE THREAD

**Issue by VamWolf** [PaddlePaddle/Paddle#1559]
Sun Mar  5 14:56:36 2017[1,5]<stderr>:    for line_count, line in enumerate(open(src_lang_dict, "r")):
Sun Mar  5 14:56:36 2017[1,5]<stderr>:IOError: [Errno 2] No such file or directory: './src.dict'
Sun Mar  5 14:56:36 2017[1,5]<stderr>:F0305 14:56:36.558559 30540 PythonUtil.cpp:134] Check failed: (ret) != nullptr Current PYTHONPATH: ['/home/disk1/normandy/maybach/451174/workspace', '/home/disk1/normandy/maybach/451174/workspace/python27-gcc482/lib/python2.7/site-packages/setuptools-18.2-py2.7.egg', '/home/disk1/normandy/maybach/451174/workspace/paddle', '/home/disk1/normandy/maybach/451174/workspace', '/home/disk1/normandy/maybach/451174/workspace/thirdparty/thirdparty', '/home/disk1/normandy/maybach/451174/workspace/python27-gcc482/lib/python27.zip', '/home/disk1/normandy/maybach/451174/workspace/python27-gcc482/lib/python2.7', '/home/disk1/normandy/maybach/451174/workspace/python27-gcc482/lib/python2.7/plat-linux2', '/home/disk1/normandy/maybach/451174/workspace/python27-gcc482/lib/python2.7/lib-tk', '/home/disk1/normandy/maybach/451174/workspace/python27-gcc482/lib/python2.7/lib-old', '/home/disk1/normandy/maybach/451174/workspace/python27-gcc482/lib/python2.7/lib-dynload', '/home/disk1/normandy/maybach/451174/workspace/python27-gcc482/lib/python2.7/site-packages', '..']
Sun Mar  5 14:56:36 2017[1,5]<stderr>:Python Error: <type 'exceptions.IOError'> : [Errno 2] No such file or directory: './src.dict'
Sun Mar  5 14:56:36 2017[1,5]<stderr>:Python Callstack: 

已经传上去了啊，为啥找不到？

**Comment by jacquesqiao** [comment]
这个问题看起来主要还是因为用户配置有问题，但是时间太长，无法追踪了，如有类似问题，请重新提交issue
