### ISSUE TITLE
Add JIT CRF_decoding and Layer_norm unit-test

### ISSUE THREAD

**Issue by luotao1** [PaddlePaddle/Paddle#15616]
To improve the code (line+function) coverage, please add JIT CRF_decoding and Layer_norm unit-tests:
http://ce.paddlepaddle.org:8080/viewLog.html?buildId=21110&buildTypeId=PaddlePaddleFramework_TestCoverage_TestCoverage&tab=report_project15_C___Coverage
![image](https://user-images.githubusercontent.com/6836917/52031672-a52c3b80-2558-11e9-9444-4f8663af7d4c.png)
https://github.com/PaddlePaddle/Paddle/blob/c4b9eac11af34d340db876fae54d93aee427e5d6/paddle/fluid/operators/jit/test.cc#L760
@yihuaxu Could you add unit-tests for these two ops?

**Comment by yihuaxu** [comment]
Just pushed one PR ([PR#15699](https://github.com/PaddlePaddle/Paddle/pull/15699)) for this issue.
