### ISSUE TITLE
Ngraph op fails on code coverage

### ISSUE THREAD

**Issue by luotao1** [PaddlePaddle/Paddle#15617]
http://ce.paddlepaddle.org:8080/viewLog.html?buildId=21110&buildTypeId=PaddlePaddleFramework_TestCoverage_TestCoverage&tab=report_project15_C___Coverage
![image](https://user-images.githubusercontent.com/6836917/52031945-d22d1e00-2559-11e9-81d0-530540441c37.png)
In build log, it seems that ngraph ops are not build successfully, please check it. 
http://ce.paddlepaddle.org:8080/viewLog.html?buildId=21110&buildTypeId=PaddlePaddleFramework_TestCoverage_TestCoverage&tab=buildLog&_focus=63#_state=63
The image is `paddlepaddle/paddle:latest-dev`, and the detail cmake options are in build log, mainly is `-DWITH_COVERAGE=ON`.

**Comment by baojun-nervana** [comment]
It seems the build has WITH_DISTRIBUTE=ON, while executor is not compiled with ngraph when WITH_DISTRIBUTE=ON. 

https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/fluid/framework/CMakeLists.txt#L161

**Comment by luotao1** [comment]
CI also has `WITH_DISTRIBUTE=ON`, but it has `test_xxx_ngraph_op`
