### ISSUE TITLE
Performance regression of box_coder op

### ISSUE THREAD

**Issue by hshen14** [PaddlePaddle/Paddle#15618]
Recently, we used PaddlePaddle new commit (1a252f4be6598d46af82acdad14ac3f096baf6e1 in 1/30) and ran SSD-MobileNet. Seems there is performance regression in box_coder op.

Before the upgrading, the profile is:
```
Event                      Calls       Total       Min.        Max.        Ave.        Ratio.      
thread0::conv2d            2350        37918.7     0.091484    50.9656     16.1356     0.906646    
thread0::multiclass_nms    50          1262.89     24.996      26.1822     25.2578     0.0301961   
thread0::prior_box         300         980.794     0.144806    11.5341     3.26931     0.023451    
thread0::reshape2          1200        906.852     0.004585    8.57195     0.75571     0.0216831   
thread0::transpose2        650         277.378     0.027228    2.43797     0.426735    0.00663217  
thread0::softmax           50          221.55      4.39363     4.63009     4.43099     0.00529731  
thread0::concat            200         156.415     0.071128    2.49121     0.782075    0.00373992  
thread0::box_coder         50          68.9811     1.3714      1.39247     1.37962     0.00164936  
thread0::flatten2          600         12.1264     0.012349    0.059559    0.0202107   0.000289946 
thread0::fetch             50          11.177      0.216979    0.23537     0.22354     0.000267245 
thread0::assign_value      600         5.6246      0.004578    0.02607     0.00937434  0.000134486 
thread0::feed              50          0.559388    0.01022     0.012291    0.0111878   1.33751e-05 
```
After the upgrading, the profile is 
```
Event                      Calls       Total       Min.        Max.        Ave.        Ratio.      
thread0::conv2d            2350        37742.3     0.086507    50.8266     16.0605     0.861045    
thread0::box_coder         50          2216.7      44.2231     44.5352     44.334      0.0505714   
thread0::multiclass_nms    50          1311.86     26.0629     27.1475     26.2373     0.0299286   
thread0::prior_box         300         979.043     0.126828    11.6266     3.26348     0.0223357   
thread0::reshape2          1200        911.08      0.005721    8.56092     0.759234    0.0207852   
thread0::transpose2        650         255.189     0.025399    2.42074     0.392599    0.00582184  
thread0::softmax           50          226.04      4.399       4.72333     4.52081     0.00515685  
thread0::concat            200         159.471     0.073097    2.49975     0.797355    0.00363814  
thread0::flatten2          600         14.4118     0.015236    0.057221    0.0240196   0.000328788 
thread0::fetch             50          10.9862     0.209115    0.238141    0.219724    0.000250637 
thread0::assign_value      600         5.58148     0.004008    0.036771    0.00930247  0.000127335 
thread0::feed              50          0.447534    0.007618    0.019401    0.00895068  1.021e-05 
```

We observed the recent commit for box coder by @jerrywgz. Could you please take a look and double confirmed the issue? You may use the script eval.py under fluid/PaddleCV/object_detection and enable the profiler to dump the performance profiling information. Thanks.

Add @luotao1.

**Comment by jerrywgz** [comment]
this is the performance of evaluation in object_detection and seems that box coder is not time consuming:
![image](https://user-images.githubusercontent.com/22989727/52041083-57bdc780-2574-11e9-9576-77ce0ff95885.png)

**Comment by hshen14** [comment]
> this is the performance of evaluation in object_detection and seems that box coder is not time consuming:
> ![image](https://user-images.githubusercontent.com/22989727/52041083-57bdc780-2574-11e9-9576-77ce0ff95885.png)

May I know the batch size you used here? We used big batch size 256/512.

**Comment by jerrywgz** [comment]
Use 1 GPU and batch_size is 32, and 256/512 is also for 1 GPU?

**Comment by hshen14** [comment]
Sorry, we used CPU and big batch size and measured on SKX. Could you please also have a try on CPU?

**Comment by jerrywgz** [comment]
Sure, box coder is slower than before and it may caused by ifelse branch in for loop. We will refine it asap.

**Comment by hshen14** [comment]
> Sure, box coder is slower than before and it may caused by ifelse branch in for loop. We will refine it asap.

Thanks for confirmation. Please let me know when the fixing happened.

**Comment by jerrywgz** [comment]
In my test, the performance of box coder after last commit isn't much worse than before. In #15637, I move many if-else branches out of the for loop and it improves 10%. You can test on your model.

**Comment by hshen14** [comment]
> In my test, the performance of box coder after last commit isn't much worse than before. In #15637, I move many if-else branches out of the for loop and it improves 10%. You can test on your model.

Great! The patch looks good to me. We will verify the performance soon, but most likely after CNY, due to the lack of machine resources now.

**Comment by hshen14** [comment]
The performance is back at our side. Sorry for the late response.

**Comment by hshen14** [comment]
@jerrywgz Could you please tell us the HW and SW command to get the performance result in #15637? We found different batch size still leads to the performance downgrade and we want to confirm with you. Thanks. 
Copy @luotao1 I reopened it and need further confirmation. Thanks.
Copy @chuanqi129 as well.

**Comment by hshen14** [comment]
Hi @jerrywgz @luotao1,
We verified the performance of box_coder OP using fake data on SKX6148 (to align HW at your side) and got the below result (unit is ms):

bs | cores | 16cb3ebd68d639a0a3a851caea08ae3b83eb5d0a | 0936097c1e07ed8798e23596e7a1d73ec59ba4f9
--|--|--|--
32 | 20 | 0.13 | 6.38
64 | 20 | 0.24 | 19.29
128 | 20 | 0.46 | 27.34
256 | 20 | 0.9 | 53.63
512 | 20 | 1.76 | 105.95
512 | 1 | 0.46 | 27.34

Could you please double check at your side? 

Our command is: `FLAGS_use_mkldnn=true OMP_NUM_THREADS=20 taskset -c 0-19 python eval_tp_fake_data.py --model_dir xxx --iterations 10 --skip_batch_num 5 --batch_size xx`. Please note that `OMP_NUM_THREADS=20 taskset -c 0-19` is to specify using the first 20 cores to run the inference. Chuanqi, please share the script `eval_tp_fake_data.py` with @jerrywgz and help reproduce the performance. Thanks.

**Comment by chuanqi129** [comment]
Our full command is: `FLAGS_use_mkldnn=true OMP_NUM_THREADS=20 taskset -c 0-19 python eval_tp_fake_data.py --model_dir xxx --iterations 10 --skip_batch_num 5 --batch_size xx` , 
`eval_tp_fake_data.py` as follow, @jerrywgz FYI.
```
import os
import time
import numpy as np
import argparse
import functools
import math

import paddle
import paddle.fluid as fluid
import paddle.fluid.profiler as profiler
import reader
from mobilenet_ssd import mobile_net
from utility import add_arguments, print_arguments

parser = argparse.ArgumentParser(description=__doc__)
add_arg = functools.partial(add_arguments, argparser=parser)
# yapf: disable
add_arg('batch_size',       int,   32,          "Minibatch size.")
add_arg('use_gpu',          bool,  False,       "Whether use GPU.")
add_arg('model_dir',        str,   '',          "The model path.")
add_arg('use_transpiler',   bool,  True,        "Whether to use transpiler.")
add_arg('profiler',         bool,  False,       "If true, do profiling.")
add_arg('use_fake_data',    bool,  True,        "If set, use fake data instead of real data.")
add_arg('skip_batch_num',   int,   0,           "Skip batch num.")
add_arg('iterations',       int,   100,         "iterations num.")
# yapf: enable

def user_data_reader(data):
    '''
    Creates a data reader for user data.
    '''

    def data_reader():
        while True:
            for b in data:
                yield b

    return data_reader


def eval(args, batch_size, model_dir=None):
    test_prog = fluid.Program()
    test_prog = test_prog.clone(for_test=True)
    place = fluid.CUDAPlace(0) if args.use_gpu else fluid.CPUPlace()
    exe = fluid.Executor(place)

    def if_exist(var):
        return os.path.exists(os.path.join(model_dir, var.name))

    [test_prog, feed_dict,
        fetch_targets] = fluid.io.load_inference_model(model_dir, exe)

    if args.use_transpiler:
        t = fluid.transpiler.InferenceTranspiler()
        t.transpile(test_prog, place)

    image_shape = [3, 300, 300]

    cnt = 0
    periods = []
    fake_data = [(
        np.random.rand(image_shape[0] * image_shape[1] * image_shape[2]).astype(np.float32),
        np.random.randint(1, 20)) for _ in range(1)]

    val_reader = paddle.batch(user_data_reader(fake_data), batch_size=batch_size)

    if args.skip_batch_num > args.iterations:
        print("Please ensure the skip_batch_num less than iterations.")
        sys.exit(0)

    for batch_id, data in enumerate(val_reader()):
        image = np.array(map(lambda x: x[0].reshape(image_shape), data)).astype(
            "float32")

        t1 = time.time()
        detection_out = exe.run(test_prog,feed={feed_dict[0]: image}, fetch_list=fetch_targets, return_numpy=False)
        period = time.time() - t1
        periods.append(period)
        cnt += len(data)
        print("Batch_id {0}, time {1}".format(batch_id, period))
        if batch_id == args.iterations - 1:
            break
    throughput = cnt / np.sum(periods[args.skip_batch_num:])
    latency = np.average(periods[args.skip_batch_num:])
    print("Throughput {0}, latency {1}.".format(throughput, latency))


if __name__ == '__main__':
    args = parser.parse_args()
    print_arguments(args)


    if not os.path.exists(args.model_dir):
        raise ValueError("The model path [%s] does not exist." %
                         (args.model_dir))

    if args.profiler:
        if args.use_gpu:
            with profiler.cuda_profiler("cuda_profiler.txt", 'csv') as nvprof:
                eval(
                    args,
                    batch_size=args.batch_size,
                    model_dir=args.model_dir)
        else:
            with profiler.profiler("CPU", sorted_key='total') as cpuprof:
                eval(
                    args,
                    batch_size=args.batch_size,
                    model_dir=args.model_dir)
    else:
        eval(
            args,
            batch_size=args.batch_size,
            model_dir=args.model_dir)

```

**Comment by jerrywgz** [comment]
I have tried to reproduce the performance but the results between two versions are relatively same.

bs | cores | before https://github.com/PaddlePaddle/Paddle/pull/15398 | latest dev
--|--|--|--
32 | 20 | 0.33 | 0.32
64 | 20 | 0.62 | 0.63
128 | 20 | 2.17 | 2.07
256 | 20 | 8.18| 8.47

Time is latency from the code you provided

**Comment by chuanqi129** [comment]
Hi @jerrywgz , Please use `--profiler`  to compare time of `thread0::box_coder`.

**Comment by jerrywgz** [comment]
Yes, box coder is time-consuming indeed and I got 8.5ms in bs=32. I try to remove the change from https://github.com/PaddlePaddle/Paddle/pull/14671 then I got 2.8ms in same config. In term of https://github.com/PaddlePaddle/Paddle/pull/15398, I added some ifelse branch in for loop and I wonder if this change causes bad performance.

**Comment by hshen14** [comment]
@jerrywgz It should be. Parallel for may not work well if there is a couple of if conditions inside. Is it possible for you to revert such changes to make performance on-par as before or shall we submit the PR to revert the change? Thanks.

**Comment by luotao1** [comment]
> Is it possible for you to revert such changes

@hshen14 Which PR do you want to revert? Do you mean #15398? I think it's impossible to revert #15398 since it adds a new feature. You could refine the performance of box_coder op.
