### ISSUE TITLE
paddle::operators::jit::gen::SeqPoolJitCode needs an aligned allocator

### ISSUE THREAD

**Issue by GBuella** [PaddlePaddle/Paddle#15622]
The standard new operator is used with an overaligned type:
```
paddle/fluid/operators/jit/gen/seqpool.cc:74:60:   required from here
paddle/fluid/operators/jit/registry.h:33:29: error: ‘new’ of type ‘paddle::operators::jit::gen::SeqPoolJitCode’ with extended alignment 32 [-Werror=aligned-new=]
   return std::unique_ptr<T>(new T(std::forward<Args>(args)...));
                             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

```
Obviously this can result in runtime errors when using certain AVX instructions, if the allocated SeqPoolJitCode instance is misaligned.

**Comment by tensor-tang** [comment]
Thanks for reporting issues. 

But could you give some more reproduce infos, it seems some compile issue?

**Comment by tensor-tang** [comment]
maybe your gcc version? we only tried below gcc5.4.

> Obviously this can result in runtime errors when using certain AVX instructions

BTW, this jitcode instance is only an instance that generate code, the code buffer would be allocated by xbyak with alignment, so I did not get your point about the runtime error if I understand right.

**Comment by GBuella** [comment]
This issue is independent of compilers. The warning comes from GCC 7.3 BTW.
The offending allocation is at:
https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/fluid/operators/jit/gen/seqpool.h#L196

The 32 char aligned data member was added in this commit:
https://github.com/PaddlePaddle/Paddle/commit/123b98f417d064e780412f316f4ca43988f4d0d2

As I look at it now, it is only a single float variable that is "aligned", so that seems rather pointless.
I think it would make sense to just remove those ALIGN32* macros from `seqpool.h`.

**Comment by tensor-tang** [comment]
OK, thanks, now I understand your issue.

Firstly, this new operator in this `SeqPoolJitCode` instance itself would not result in runtime error using AVX. 

Secondly, since I used new operator, then this ALIGEN code would cause high level GCC e.g. GCC 7.3 (which warning check more strictly with `-Werror=aligned-new`) failed.
https://github.com/PaddlePaddle/Paddle/blob/546eefae6fdf6b9848b91c8246b17a0fa72cc982/paddle/fluid/operators/jit/gen/seqpool.h#L196


Maybe you could replace here 

https://github.com/PaddlePaddle/Paddle/blob/546eefae6fdf6b9848b91c8246b17a0fa72cc982/paddle/fluid/operators/jit/registry.h#L33

as 

```
void* ptr = aligned_alloc(32, sizeof(A));
A* a = new(ptr) A;
```

**Comment by GBuella** [comment]
```
Firstly, this new operator in this SeqPoolJitCode instance itself would not result in runtime error using AVX.
```
No, the runtime issue has nothing to do with the `new` operator -- the issue is, a compiler assumes each instance of that class to be 32 char aligned - thus it is allowed to use certain AVX instructions anytime anywhere on instances of such a class.
When
 1) one tells the compiler that it can assume some data to be 32 char aligned
 2) that data is not 32 char aligned at runtime

That means the code is clearly broken.
BTW, what is the point of that alignment specification?
As I see, that float only seems to be used in a vbroadcastss, which has no requirement for it's single float operand to overaligned.
I really suspect that those macros should just be removed.

**Comment by GBuella** [comment]
Yes, using `alinged_alloc` could help here, but probably it should not be needed. Unless I'm missing something, the original author could perhaps explain the reason.

**Comment by tensor-tang** [comment]
> the issue is, a compiler assumes each instance of that class to be 32 char aligned - thus it is allowed to use certain AVX instructions anytime anywhere on instances of such a class.

Yes, Thanks for pointer out that.

As for this seqpool file, this `fp_h_` is just use to compute avg and sqrt.

#15625 would just help solve your problem, but it can not solve this kind issue in case somewhere else use ALIGED here.

**Comment by GBuella** [comment]
"would just help solve your problem, but it can not solve this kind issue in case somewhere else use ALINGED here"
That is true. If a warning points out another similar case, then an alignment aware allocator might be needed.

In that case by the way, it is a better genral solution, to the appropriate member methods `operator new` and `operator delete` to such classes.
