### ISSUE TITLE
用多标签分类fluid.layers.sigmoid_cross_entropy_with_logits，预测每个类别结果异常

### ISSUE THREAD

**Issue by hweidream** [PaddlePaddle/Paddle#15623]
预测代码：
![image](https://user-images.githubusercontent.com/17971652/52098651-d5341700-260a-11e9-831a-ee8b9b1d29bf.png)

预测时直接输出结果如下图：
![image](https://user-images.githubusercontent.com/17971652/52055890-a03cab80-259b-11e9-9046-3278d98edb01.png)

sigmoid_cross_entropy_with_logits用的的激活函数是sigmoid，预测结果不应该映射到0～1之间吗，为何会输出负数？

**Comment by velconia** [comment]
可以参考下 ```sigmoid_cross_entropy_with_logits``` 的公式 , 我理解X很大的话也是可能这样的

http://www.paddlepaddle.org/documentation/docs/zh/1.2/api_cn/layers_cn.html#paddle.fluid.layers.sigmoid_cross_entropy_with_logits

```loss=max(X,0)−X∗Labels+log(1+exp(−|X|)```

**Comment by hweidream** [comment]
那如何根据预测结果来判断label
