### ISSUE TITLE
multi_binary_label_cross_entropy with GPU training

### ISSUE THREAD

**Issue by CrossLee1** [PaddlePaddle/Paddle#1563]
In my network configuration, the _**multi_binary_label_cross_entropy**_ cost is used for multi-label problem. When I use CPU for training ,everything is OK. But if I use GPU, error occurs, following is the detailed information.
It seems the _**multi_binary_label_cross_entropy**_ cost for GPU calculation is not implemented.
Is there a plan to implement this operation in the coming days?

Thanks~

I0306 14:30:24.197165  9426 GradientMachine.cpp:134] Initing parameters..
I0306 14:30:29.967819  9426 GradientMachine.cpp:141] Init parameters done.
I0306 14:30:30.027035  9426 DataProvider.h:328] the double-buffer is starting ...
F0306 14:30:52.430397  9476 Matrix.h:889] Not implemented
*** Check failure stack trace: ***
    @           0x9bd9cc  google::LogMessage::Fail()
    @           0x9bd924  google::LogMessage::SendToLog()
    @           0x9bd3b9  google::LogMessage::Flush()
    @           0x9c017a  google::LogMessageFatal::~LogMessageFatal()
F0306 14:30:52.436619  9484 Matrix.h:889] Not implemented
*** Check failure stack trace: ***
    @           0x9bd9cc  google::LogMessage::Fail()
    @           0x9bd924  google::LogMessage::SendToLog()
    @           0x9bd3b9  google::LogMessage::Flush()
    @           0x646e30  paddle::Matrix::multiBinaryLabelCrossEntropy()
    @           0x9c017a  google::LogMessageFatal::~LogMessageFatal()
    @           0x646e30  paddle::Matrix::multiBinaryLabelCrossEntropy()
F0306 14:30:52.436619  9484 Matrix.h:889] Not implementedF0306 14:30:52.441058  9472 Matrix.h:889] Not implemented
*** Check failure stack trace: ***
F0306 14:30:52.436619  9484 Matrix.h:889] Not implementedF0306 14:30:52.441058  9472 Matrix.h:889] Not implementedF0306 14:30:52.441334  9480 Matrix.h:889] Not implemented
*** Check failure stack trace: ***
    @           0x9bd9cc  google::LogMessage::Fail()
    @           0x9bd9cc  google::LogMessage::Fail()
    @           0x9bd924  google::LogMessage::SendToLog()
    @           0x9bd924  google::LogMessage::SendToLog()
    @           0x9bd3b9  google::LogMessage::Flush()
    @           0x9bd3b9  google::LogMessage::Flush()
    @           0x863185  paddle::CostLayer::forward()
    @           0x863185  paddle::CostLayer::forward()
    @           0x9c017a  google::LogMessageFatal::~LogMessageFatal()
    @           0x9c017a  google::LogMessageFatal::~LogMessageFatal()
    @           0x646e30  paddle::Matrix::multiBinaryLabelCrossEntropy()
    @           0x646e30  paddle::Matrix::multiBinaryLabelCrossEntropy()
    @           0x863185  paddle::CostLayer::forward()
    @           0x863185  paddle::CostLayer::forward()
    @           0x9103ac  paddle::NeuralNetwork::forward()
    @           0x9103ac  paddle::NeuralNetwork::forward()
    @           0x9103ac  paddle::NeuralNetwork::forward()
    @           0x9103ac  paddle::NeuralNetwork::forward()
    @           0x90162f  paddle::TrainerThread::forward()
    @           0x90162f  paddle::TrainerThread::forward()
    @           0x90162f  paddle::TrainerThread::forward()
    @           0x90162f  paddle::TrainerThread::forward()
    @           0x902835  paddle::TrainerThread::computeThread()
    @           0x902835  paddle::TrainerThread::computeThread()
    @           0x902835  paddle::TrainerThread::computeThread()
    @           0x902835  paddle::TrainerThread::computeThread()
    @     0x7fa16f4958a0  execute_native_thread_routine
    @     0x7fa16f4958a0  execute_native_thread_routine
    @     0x7fa16f4958a0  execute_native_thread_routine
    @     0x7fa16f4958a0  execute_native_thread_routine
    @     0x7fa16fbf61c3  start_thread
    @     0x7fa16fbf61c3  start_thread
    @     0x7fa16fbf61c3  start_thread
    @     0x7fa16fbf61c3  start_thread
    @     0x7fa16ef0912d  __clone
    @     0x7fa16ef0912d  __clone

**Comment by luotao1** [comment]
最新的develop分支中，有对应的gpu实现。可更新代码。

**Comment by CrossLee1** [comment]
我使用最新的develop分支中的gpu实现，但是运行一小段时间后又报错，请问这是什么原因呢：

..F0308 21:35:12.979095 10444 hl_cuda_device.cc:643] Check failed: cudaSuccess == cudaStat (0 vs. 77) Cuda Error: an illegal memory access was encountered
*** Check failure stack trace: ***
    @     0x7faa212e546d  google::LogMessage::Fail()
    @     0x7faa212e72ef  google::LogMessage::SendToLog()
    @     0x7faa212e5003  google::LogMessage::Flush()
    @     0x7faa212e7c0e  google::LogMessageFatal::~LogMessageFatal()
    @           0x8821db  hl_stream_synchronize()
    @           0x887c37  hl_matrix_multi_binary_cross_entropy()
    @           0x6f5808  paddle::GpuMatrix::multiBinaryLabelCrossEntropy()
    @           0x600bc5  paddle::MultiBinaryLabelCrossEntropy::forwardImp()
    @           0x600845  paddle::CostLayer::forward()
    @           0x64df20  paddle::NeuralNetwork::forward()
    @           0x655eb7  paddle::TrainerThread::forward()
    @           0x6581cc  paddle::TrainerThread::computeThread()
    @     0x7faa1cda98a0  execute_native_thread_routine
    @     0x7faa20ea31c3  start_thread
    @     0x7faa1c51a12d  __clone

**Comment by luotao1** [comment]
gpubox环境，麻烦 @hedaoyuan 看下

**Comment by hedaoyuan** [comment]
I will check the implementation of `hl_matrix_multi_binary_cross_entropy`.

@CrossLee1 用单个卡跑呢，这个问题也是必现吗？是在固定某个batch的数据计算时出core吗？
> 我使用最新的develop分支中的gpu实现，但是运行一小段时间后又报错，请问这是什么原因呢。
> 环境：单机运行，GPUBOX，16卡K40

**Comment by CrossLee1** [comment]
@hedaoyuan 
单卡跑了一个Pass，暂时没出现问题，但是后续会不会出问题还需要观察。
不是固定某个batch的数据计算时出core

**Comment by hedaoyuan** [comment]
closed by #1900
