### ISSUE TITLE
Paddle can't  use the most of memory now

### ISSUE THREAD

**Issue by gongweibao** [PaddlePaddle/Paddle#15644]
![image](https://user-images.githubusercontent.com/10721757/52159366-658f5c00-26de-11e9-8c8f-c2e0f6554c7c.png)

Cant it alloc only the left memory if it can't alloc the `fraction` memory？

**Comment by panyx0718** [comment]
open an internal issue for 内部提出？

**Comment by gongweibao** [comment]
?
![image](https://user-images.githubusercontent.com/10721757/52829961-b3a65580-3109-11e9-8c9b-73e8c4ad406c.png)

**Comment by gongweibao** [comment]
![image](https://user-images.githubusercontent.com/10721757/55371544-2ab87180-5531-11e9-8d45-9052dc2effde.png)

**Comment by sneaxiy** [comment]
You can set `FLAGS_fraction_of_gpu_memory_to_use=1` to fix temporarily.
