### ISSUE TITLE
paddlepaddle有冻结网络部分层，进行训练的api吗

### ISSUE THREAD

**Issue by freekoy** [PaddlePaddle/Paddle#15641]
类似keras可以冻结部分层，进行训练

**Comment by shiyazhou121** [comment]
是fine-tune吗？
![image](https://user-images.githubusercontent.com/15082798/52158342-573b4300-26d2-11e9-83b6-b56553f268a3.png)

**Comment by velconia** [comment]
@shiyazhou121，GJ 👍 , 在参数的 ParamAttr 里设置 trainable=False 就可以冻结这个参数的训练

**Comment by freekoy** [comment]
@shiyazhou121 
就是要这个，但怎么动态调整网络的可训练性？
比如想先预训练前三层，再整体训练？

**Comment by velconia** [comment]
@freekoy 可以搭建两个Program，一个用于预训练，一个用于整体训练，两个Program保持参数名字相同，即可共享参数训练结果；伪代码如下:
```
pro1 = fluid.Program()
with program_guard(pro1):
  f1 = fluid.layers.fc(10, param_attr=ParamAttr(name='W1‘, trainable=False)

pro2 = fluid.Program()
with program_guard(pro2):
  f2 = fluid.layers.fc(10, param_attr=ParamAttr(name='W1‘, trainable=True)

exe = fluid.Executor()
exe.run(pro1)
exe.run(pro2)
```

**Comment by freekoy** [comment]
好的，谢谢

**Comment by XiaoheYou** [comment]
你好，请问你的freeze怎么实现的？我把trainable=False后，没有变化。
