### ISSUE TITLE
模型的int8量化训练

### ISSUE THREAD

**Issue by dubhex** [PaddlePaddle/Paddle#15646]
请问如何使用paddle进行模型的int8量化训练？

**Comment by xuezhong** [comment]
支持CNN 8bit量化训练。  量化预测TensorRT支持，但还没正式release， cpu的8bit预测也还没正式release。  量化预测1.3才会release一部分能力。

**Comment by qingqing01** [comment]
@guo-hanqi 可以参考示例 https://github.com/PaddlePaddle/models/blob/develop/fluid/PaddleCV/object_detection/README_quant.md
