### ISSUE TITLE
How to handle int32 input in C-API inference app for Transformer?

### ISSUE THREAD

**Issue by wojtuss** [PaddlePaddle/Paddle#15658]
In the Transformer model's config, there is a new input named `init_idx`, which is of `int32` type. In order to run C-API inference for this model all the inputs have to be either of `PaddleDType::FLOAT32` or `PaddleDType::INT64`. How should we define the `init_idx` input in C-API?

**Comment by luotao1** [comment]
We will add `int32` type later.

**Comment by wojtuss** [comment]
@luotao1 , You mean adding support for INT32 in C-API, right? What is the time perspective for that? It is quite important for our work on Transformer.
Thank you!

**Comment by luotao1** [comment]
Yes, adding support for INT32 in C-API maybe works after Chinese New Year. How about adding support yourself if you are convenient?

**Comment by wojtuss** [comment]
Done. Thank you.
