### ISSUE TITLE
多GPU出core

### ISSUE THREAD

**Issue by molly00ecla** [PaddlePaddle/Paddle#15651]
Paddle版本：paddlepaddle-gpu (1.1.0.post85)
代码如下：
![image](https://user-images.githubusercontent.com/22423844/52162743-7ad2ad80-2713-11e9-8f23-57c1c2f4fcae.png)
如果不用parallelExe，是可以正常训练的。用的话在构造对象时候就会报错
![image](https://user-images.githubusercontent.com/22423844/52162765-a9e91f00-2713-11e9-9cbe-28fcc8b5593b.png)
最神奇的是，如果指定1个显卡的话，就没问题……
CUDA_VISIBLE_DEVICES=0 python 0202.py   这样就不会报错
CUDA_VISIBLE_DEVICES=0,1 python 0202.py 这样就会报上面那个错

NCCL也安装了呀
![image](https://user-images.githubusercontent.com/22423844/52162774-b8cfd180-2713-11e9-85c5-205e5c209895.png)

**Comment by xuezhong** [comment]
可以贴下整个的代码吗，另外如果不用parallelExe的代码又是怎么样的？
