### ISSUE TITLE
NotImplementedError when using drop rate in pooling_layer

### ISSUE THREAD

**Issue by cactiball** [PaddlePaddle/Paddle#1567]
When I do:

hidden = pooling_layer(
  input=ipt,
  pooling_type=AvgPooling(),
  layer_attr=ExtraAttr(drop_rate=0.1),
)

I get:
Python Error: <type 'exceptions.NotImplementedError'> : Layer pooling_layer cannot support drop_rate

Is this because I am using an old version code base?

Thanks much!

**Comment by luotao1** [comment]
This is already fixed by #1027 , and will be merged ASAP.

**Comment by cactiball** [comment]
Thanks

**Comment by luotao1** [comment]
@cactiball #1027 has been merged now. You can have a try.
