### ISSUE TITLE
fc_mkldnn_op.cc has IDENTICAL_BRANCHES

### ISSUE THREAD

**Issue by luotao1** [PaddlePaddle/Paddle#15675]
https://github.com/PaddlePaddle/Paddle/blob/1ccbc51218c4cbc7273c3bb38cfd395be3b3a6dc/paddle/fluid/operators/mkldnn/fc_mkldnn_op.cc#L281-L285
CID 47193 (#1 of 1): Identical code for different branches (IDENTICAL_BRANCHES)identical_branches: Ternary expression on condition with_bias has identical then and else expressions: mkldnn::inner_product_backward_weights::desc(src, diff_weights, bias, diff_dst). Should one of the expressions be modified, or the entire ternary expression replaced?

**Comment by mozga-intel** [comment]
@Sand3r Could you please look at this issue.

**Comment by Sand3r-** [comment]
The second `mkldnn::inner_product_backward_weights::desc(src, diff_weights, bias, diff_dst);` should be changed to `mkldnn::inner_product_backward_weights::desc(src, diff_weights, diff_dst);`
