### ISSUE TITLE
开启显存优化后，优化效果提升不大

### ISSUE THREAD

**Issue by DDDivano** [PaddlePaddle/Paddle#15683]
transformer模型，
开启优化
![image](https://user-images.githubusercontent.com/10734244/52636350-4d51e500-2f07-11e9-8675-97ae9fe39775.png)
未开启优化
![image](https://user-images.githubusercontent.com/10734244/52636362-58a51080-2f07-11e9-9f17-3e85ebcaf48a.png)

rcnn模型也有相同问题

**Comment by dzhwinter** [comment]
fix 了默认配置。本地测试结果(Batchsize都采用了较小的32，显存的单位为MB)


Resnet50 | 显存
-- | --
Python端的memory optimize | 4298
memory_optimize, inplace,   fast_deletion_mode | 3647
  |  
faster_rcnn |  
Python端的memory optimize | 6961
memory_optimize, inplace,   fast_deletion_mode | 3102

**Comment by dzhwinter** [comment]
修复的PR在 https://github.com/PaddlePaddle/Paddle/pull/15696
