### ISSUE TITLE
模型训练约10个小时后fail

### ISSUE THREAD

**Issue by AWSWXY** [PaddlePaddle/Paddle#15689]
日志中没有报错。
任务链接
http://yq01-hpc-lvliang-mon.dmop.baidu.com:8919/taskinfo.html?appId=app-user-20190212204641-2604&submitTime=2019-02-12%2020:46:41

**Comment by Xreki** [comment]
您好，我在任务链接的首页看到这样的信息：

```
Stage Trace 
Epilogue Finish
Epilogue Start
Usermain Fail usermain timeout
Usermain Start
Prologue Finish
Prologue Start
Preparing Finish
Preparing Start
```

这里有`timeout`字样，除此之外也没看到别的错误信息，是否是网络超时？重跑该任务，问题会复现吗？

**Comment by Xreki** [comment]
PaddleCloud训练任务默认设置时间为10个小时，这个应该是因为时间到了，所以退出了。

**Comment by sunflowerlyb** [comment]
> ，

hi，麻烦请教请下这个时间是在哪里设置的呢？我的模型训练过程中会自动断掉，我以为是learningrate设置的太大了，我设置的是e-3，但是改成e-4之后还是会自动退出，没有报错信息
