### ISSUE TITLE
内部用户，sequence tagging   local改写集群版问题

### ISSUE THREAD

**Issue by hxhlwf** [PaddlePaddle/Paddle#1569]
sequence tagging 单机改集群版
错误信息：
F0310 10:50:26.130656 14511 SocketChannel.cpp:99] Check failed: len > 0  peer=10.73.29.40 curIov=0 iovCnt=4 iovs[curIov].base=0x7f8aecdf9ca0 iovs[curIov].iov_len=16F0310 10:50:26.130676 14521 SocketChannel.cpp:99] Check failed: len > 0  peer=10.73.30.51 curIov=0 iovCnt=4 iovs[curIov].base=0x7f8ab61fbca0 iovs[curIov].iov_len=16F0310 10:50:26.130682 14507 SocketChannel.cpp:99] Check failed: len > 0  peer=10.73.29.31 curIov=0 iovCnt=4 iovs[curIov].base=0x7f8aef5fdca0 iovs[curIov].iov_len=16: BrBroken pipe [ [32]32]: Broken pipe [32]
Fri Mar 10 10:50:26 2017[1,89]<stderr>:+ ps aux
Fri Mar 10 10:50:26 2017[1,61]<stderr>:*** Check failure stack trace: ***
Fri Mar 10 10:50:26 2017[1,89]<stderr>:+ grep paddle_pserver2
Fri Mar 10 10:50:26 2017[1,44]<stderr>:./train.sh: line 207:  2666 Floating point exceptionPYTHONPATH=./paddle:$PYTHONPATH GLOG_logtostderr=0 GLOG_log_dir="./log" ./paddle_trainer --num_gradient_servers=${OMPI_COMM_WORLD_SIZE} --trainer_id=${OMPI_COMM_WORLD_RANK} --pservers=$ipstring --rdma_tcp=${rdma_tcp} --nics=${nics} ${train_arg} --config=conf/trainer_config.conf --save_dir=./${save_dir} ${extern_arg}
Fri Mar 10 10:50:26 2017[1,61]<stderr>:F0310 10:50:26.130650 14509 SocketChannel.cpp:99] Check failed: len > 0  peer=10.73.29.39 curIov=0 iovCnt=4 iovs[curIov].base=0x7f8aee1fbca0 iovs[curIov].iov_len=16: Broken pipe [32]
Fri Mar 10 10:50:26 2017[1,44]<stderr>:+ '[' 136 -ne 0 ']'

改集群版出现了上面这个问题，不知道是哪儿的问题

**Comment by Yancey1989** [comment]
Close the inactive issue, please reopen it if any update.
