### ISSUE TITLE
paddle memory leak when using deepspeech

### ISSUE THREAD

**Issue by nemo9903** [PaddlePaddle/Paddle#15690]
I remember the deepspeech worked before. But why it doesn't work now?
As the training going on, the used memory increase along. At last, the system halt.
I tried both pip and docker installation method. On top of ubuntu 14.04,16.04,18.04. And I also tried cpu /gpu versions paddle of 0.10,0.14,0.15,1.2.0,1.2.1.  I also tried to modifiy the training parameters, for example, gru/layer size/batch size.
 I tried all of the configurations,but no use.

At last, the packages listed below. Is one of the configurations I tested.

Package                       Version
----------------------------- --------
adium-theme-ubuntu            0.3.4
backports.functools-lru-cache 1.5
cffi                          1.11.5
cycler                        0.10.0
Cython                        0.29.5
enum34                        1.1.6
funcsigs                      1.0.2
graphviz                      0.10.1
kiwisolver                    1.0.1
LinkChecker                   9.3
llvmlite                      0.27.0
matplotlib                    2.2.3
nltk                          3.4
numba                         0.42.0
numpy                         1.16.1
opencv-python                 4.0.0.21
paddlepaddle                  1.2.1
Pillow                        5.4.1
pip                           19.0.2
protobuf                      3.1.0
pycparser                     2.19
pyparsing                     2.3.1
python-dateutil               2.8.0
python-speech-features        0.6
pytz                          2018.9
rarfile                       3.0
recordio                      0.1.5
requests                      2.9.2
resampy                       0.2.1
scipy                         1.2.1
setuptools                    20.7.0
singledispatch                3.4.0.3
six                           1.12.0
SoundFile                     0.10.2
subprocess32                  3.5.3
swig-decoders                 1.1
unity-lens-photos             1.0
wheel                         0.29.0

**Comment by Xreki** [comment]
The [DeepSpeech](https://github.com/PaddlePaddle/DeepSpeech) remains not changed since 9 months ago. Do you have any change in your environment?

**Comment by nemo9903** [comment]
Last year, It's OK. Recently, I reinstalled the Ubuntu16.04, And the memory leak happened. I don't know what is changed. I still follow the README.md.  The deepspeech code is not changed. But the paddlepaddle or the depended pip packages are changed. Could you please give me a list of the version of the qualified packages?

**Comment by nemo9903** [comment]
@Xreki 
I believe, If you install again, it also leaks.
