### ISSUE TITLE
Add ngraph related unit-tests

### ISSUE THREAD

**Issue by luotao1** [PaddlePaddle/Paddle#15708]
To improve the code (line+function) coverage, please **add ngraph related unit-tests**:
http://ce.paddlepaddle.org:8080/viewLog.html?buildId=25255&buildTypeId=PaddlePaddleFramework_TestCoverage_TestCoverage&tab=report_project15_C___Coverage
- operators/ngraph/ops
![image](https://user-images.githubusercontent.com/6836917/52716182-324fa580-2fd9-11e9-9a42-4ca09643aad3.png)
![image](https://user-images.githubusercontent.com/6836917/52716213-40052b00-2fd9-11e9-89b9-9f03e68ae6e6.png)
![image](https://user-images.githubusercontent.com/6836917/52716235-4d221a00-2fd9-11e9-917b-3462289968a5.png)

**Comment by mozga-intel** [comment]
@luotao1 I will have a look at this, thank you.
