### ISSUE TITLE
不理解log每行的含义

### ISSUE THREAD

**Issue by chenbai1002** [PaddlePaddle/Paddle#1572]
在paddle上训练了一个简化的vgg，num_pass=50，但是每一轮的AvgCost都没有下降，想看下log，发现不太懂，哪位同学能帮忙解释下？
（curve是样本y值的变量名，是浮点数）
不太理解的是，1. mean值是对什么数据计算的均值？
2. curve的mean值是怎么计算的？
3. 为什么curve的mean值输出后，下一行是__conv_4__的数据？

日志：
I0307 15:03:02.039155 23169 Layer.cpp:322] The output state of __conv_3__: mean=217.806, std=1.07076e+07, min=-22505.9, max=20308.8
I0307 15:03:02.049365 23166 Layer.cpp:322] The output state of __batch_norm_3__: mean=0.529093, std=0.792352, min=0, max=9.71457
I0307 15:03:02.133126 23169 Layer.cpp:322] The output state of __batch_norm_3__: mean=0.802943, std=2.31592, min=0, max=22.3154
I0307 15:03:02.157477 23165 Layer.cpp:322] The output state of __fc_layer_0__: mean=-59.4017, std=601253, min=-4554.63, max=5402.61
I0307 15:03:02.158000 23165 Layer.cpp:322] The output state of __batch_norm_5__: mean=0.139144, std=0.121383, min=0, max=4.03563
I0307 15:03:02.160650 23165 Layer.cpp:322] The output state of __fc_layer_1__: mean=2.79507, std=14837.1, min=-377.746, max=421.116
I0307 15:03:02.160818 23165 Layer.cpp:322] The output state of __fc_layer_2__: mean=4.24835e-18, std=0, min=4.24835e-18, max=4.24835e-18
**I0307 15:03:02.160897 23165 Layer.cpp:322] The output state of curve: mean=-0.000655183, std=1.12623e-06, min=-0.00306697, max=0.00104117
I0307 15:03:02.373538 23167 Layer.cpp:322] The output state of __conv_4__: mean=-30.7068, std=156569, min=-3716.34, max=3878.18**
I0307 15:03:02.447966 23167 Layer.cpp:322] The output state of __batch_norm_4__: mean=0.46306, std=0.645961, min=0, max=11.0901
I0307 15:03:02.460011 23167 Layer.cpp:322] The output state of __dropout_0__: mean=0.277384, std=0.20836, min=0, max=5.54504
I0307 15:03:02.543288 23167 Layer.cpp:322] The output state of __fc_layer_0__: mean=-87.8653, std=1.40964e+06, min=-8038.86, max=9601.44
I0307 15:03:02.543723 23167 Layer.cpp:322] The output state of __batch_norm_5__: mean=0.18127, std=0.196429, min=0, max=4.31139
I0307 15:03:02.545486 23167 Layer.cpp:322] The output state of __fc_layer_1__: mean=4.85983, std=46964, min=-847.111, max=945.122
I0307 15:03:02.545569 23167 Layer.cpp:322] The output state of __fc_layer_2__: mean=4.24835e-18, std=0, min=4.24835e-18, max=4.24835e-18
I0307 15:03:02.545611 23167 Layer.cpp:322] The output state of curve: mean=0.00118923, std=2.72458e-05, min=-0.0081565, max=0.0119824

**Comment by qingqing01** [comment]
> 训练了一个简化的vgg，num_pass=50，但是每一轮的AvgCost都没有下降

这个可能需要看下简化后配置，才能具体看下问题~

> 不太理解的是，1. mean值是对什么数据计算的均值？
> 2. curve的mean值是怎么计算的？

需要看下你使用的命令行参数，你使用了 `--show_layer_stat`吗？ 打印的是一个minibatch的每一层output的统计信息，fc,conv层即对输出的特征统计，data层对该层的数据统计。

> 3. 为什么curve的mean值输出后，下一行是__conv_4__的数据？

顺序问题，和调用该层的顺序有关系(也和配置文件层的顺序可能有关系)，`curve` 是data_layer吧，这个顺序并不影响啥。

**Comment by chenbai1002** [comment]
感谢回复！
我看log里面curve的均值是随着迭代次数逐渐接近于真实值的，这好像说明了模型是有效的，但是AvgCost没有下降且数值特别大我不太理解，附件是我的模型配置文件，请你帮忙看下是我在使用regression_cost时有错误吗，还是其它的配置有问题?

[trainer.txt](https://github.com/PaddlePaddle/Paddle/files/835626/trainer.txt)

**Comment by chenbai1002** [comment]
感谢回复！
我看log里面curve的均值是随着迭代次数逐渐接近于真实值的，这好像说明了模型是有效的，但是AvgCost没有下降且数值特别大我不太理解，附件是我的模型配置文件，请你帮忙看下是我在使用regression_cost时有错误吗，我没找到regression_cost的说明文档，还是其它的配置有问题?
[trainer.txt](https://github.com/PaddlePaddle/Paddle/files/835661/trainer.txt)
