### ISSUE TITLE
paddlepaddle.org的文档页访问慢

### ISSUE THREAD

**Issue by yebie** [PaddlePaddle/Paddle#1574]
**repro step:**
1. 清理浏览器缓存（此步骤可选，不过清理之后更容易重现）
2. 访问官网文档页面，如[这里](http://www.paddlepaddle.org/doc/index.html)
3. 此时页面长期处于loading状态（国内可能超过1分钟），并且在loading过程中，页面不显示内容。
4. 在loading过程中如果取消网页加载，可显示出页面。

用浏览器调试工具可以看到，主要是mathjax.js文件加载时间长：
  ` <script type="text/javascript" src="https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML"></script>`

因为这个js文件加载放在网页的<head>部分，浏览器的策略通常都是要下载完这个文件才开始渲染页面，导致这一个访问缓慢时会block整个页面的显示。

尤其是新用户第一次访问时，这个js文件会导致整个文档系统的访问缓慢，体验不佳。

**建议：**
1. 是否还在文档中写公式？如果没有了，建议从模板中移除这个js文件；
2. 如果还需要这个js文件，是否可以在paddlepaddle.org的本地拷贝一份，而不是访问cdn.mathjax.org；
3. 如果需要这个js文件但不方便在网站服务器上存储，是否可以将这行`<script>...</script>` 挪到 `<div class="footer" role="contentinfo">...</div>`之后、`</body>`之前？这样会让浏览器先渲染页面内容再后台加载mathjax.js，不影响页面显示。

**Comment by hedaoyuan** [comment]
非常感谢~
@llxxxll 勇峰帮忙看一下。

**Comment by reyoung** [comment]
![image](https://cloud.githubusercontent.com/assets/728699/25084626/3edc94d6-2390-11e7-96af-fab222d8220a.png)
目前已经换成了cloudflared的CDN，但愿能快一点。
