### ISSUE TITLE
模型保存正常，发生如下错误。

### ISSUE THREAD

**Issue by stoiczzz** [PaddlePaddle/Paddle#15740]
想保存模型后，加载之前的模型继续进行训练。
在load过程中发生如下错误，之前的一个模型是好的，这次新的出现如下问题，请问是什么导致的？

paddle.fluid.core.EnforceNotMet: Cannot open file ./model_0215/1/fc_1.b_0 for load op at [/paddle/paddle/fluid/operators/load_op.cc:39]

**Comment by stoiczzz** [comment]
model_path = os.path.join(model_save_dir, str(pass_id))
    if not os.path.exists(model_save_dir):
        os.makedirs(model_save_dir)
    print('save as%s' % (model_path))
    fluid.io.save_inference_model(model_path, ['image'], net, exe)

**Comment by hjchen2** [comment]
请先确认一下./model_0215/1/fc_1.b_0文件是否存在，看起来可能是load的模型路径没设对

**Comment by mask0918** [comment]
> 请先确认一下./model_0215/1/fc_1.b_0文件是否存在，看起来可能是load的模型路径没设对

就是缺少这个，但是我不知道为什么
