### ISSUE TITLE
parallel的训练模式下，cpu模式并没有利用多个cpu核。

### ISSUE THREAD

**Issue by LihangLiu** [PaddlePaddle/Paddle#15758]
parallel的训练模式下，GPU模式可以实现多个GPU同时执行。但是CPU模式还是单个CPU在执行，并没有利用多CPU进行加速，请问是什么原因呢？

**Comment by LihangLiu** [comment]
2019年1月份拉的develop版本，系统为centos。

**Comment by junjun315** [comment]
http://www.paddlepaddle.org/documentation/docs/zh/1.2/api_cn/fluid_cn.html#permalink-21-parallelexecutor
参考这里的描述，您可以试试看添加环境变量 CPU_NUM 来设置CPU设备的个数。
从环境描述看，用的是镜像？

**Comment by LihangLiu** [comment]
代码中设置了

    strategy = fluid.ExecutionStrategy()
    strategy.num_threads = 1
导致速度被限制，现已解决。
