### ISSUE TITLE
paddle.utils.plot在python3.7下运行出错

### ISSUE THREAD

**Issue by junjun315** [PaddlePaddle/Paddle#15761]
- 版本、环境信息：
    1）PaddlePaddle版本：1.2.1
    2）CPU/GPU：all
    3）系统环境：win
    4）Python版本号：3.7
- 复现信息：
   http://ai.baidu.com/forum/topic/show/942279
   参考这里的代码。
   `from paddle.utils.plot import Ploter
    train_prompt = "Train cost"
    test_prompt = "Test cost"
    plot_cost = Ploter(test_prompt,train_prompt)`
   
   只要append 就出错
- 问题描述：
   File "C:\Users\11856\AppData\Roaming\Python\Python37\site-packages\paddle\utils\plot.py", line 75, in append
assert isinstance(title, basestring)
NameError: name 'basestring' is not defined

**Comment by henrystrident** [comment]
你好，我想问下paddlepaddle在python3.7版本下能用 pip install paddlepaddle安装吗？ 我用这个命令后会出现No matching distribution found for paddlepaddle 这样的错误，我pip版本号是10.0.1

**Comment by junjun315** [comment]
你好，出现这样的问题的原因可能不是因为pip版本。
1. 检查pip源是否有过改动，比如自己定义了pip.conf。部分源可能没有paddle
2. 可以看看本机pip3.7支持的whl包的版本。
  `from pip import pep425tags`
   `print(pep425tags.get_supported()) `
  来查看支持的whl包版本。paddle当前只支持64位的, 可能安装的pip以及python是32位的

**Comment by henrystrident** [comment]
这个问题我已经解决了，的确是因为python安装的是32位的版本，谢谢你的回复
