### ISSUE TITLE
fluid中没有plot

### ISSUE THREAD

**Issue by appleappleorange** [PaddlePaddle/Paddle#15766]
在手写数中，有用到paddle.v2.plot，但是最新的fluid中没有plot，有没有替代品？
手写数的这段代码”for step_id, data in enumerate(train_reader()):“产生了一段bug，在mnist中def reader(): if platform.system() == 'Darwin': zcat_cmd = 'gzcat' elif platform.system() == 'Linux': zcat_cmd = 'zcat' else: raise NotImplementedError()总之没有准备好面对

**Comment by junjun315** [comment]
你好，这里应该有两个问题：
1. paddle.v2.plot 已经替换成 paddle.utils.plot
2. 如果是在win的环境下，repo：book中“手写数字识别”在V1.2.1及以前版本有一个已知问题，数据集中使用了一个环境不友好的处理，在即将发布的新版本中会解决。 可以参考当前paddle develop分支中：/python/paddle/dataset/mnist.py 代码的解决方案。
