### ISSUE TITLE
resnet example extract_fea_c++.sh会挂掉，extract_fea_py.sh 正常

### ISSUE THREAD

**Issue by dylanliuli** [PaddlePaddle/Paddle#1577]
dev版本
运行extract_fea_c++.sh会挂掉，但extract_fea_py.sh 正常，
[libprotobuf ERROR google/protobuf/message_lite.cc:119] Can't parse message of type "paddle.TrainerConfig" because it is missing required fields: opt_config.learning_rate
F0308 16:13:54.406886  8318 TrainerConfigHelper.cpp:57] Check failed: m->conf.ParseFromString(configProtoStr)
*** Check failure stack trace: ***
    @           0x876630  google::LogMessage::Fail()
    @           0x87658c  google::LogMessage::SendToLog()
    @           0x875f10  google::LogMessage::Flush()
    @           0x878fb7  google::LogMessageFatal::~LogMessageFatal()
    @           0x6ff379  paddle::TrainerConfigHelper::TrainerConfigHelper()
    @           0x6ff744  paddle::TrainerConfigHelper::createFromFlags()
    @           0x56d5c2  main
    @     0x7fc6f1c47bd5  __libc_start_main
    @           0x579ff9  (unknown)
    @              (nil)  (unknown)
xxxx/bin/paddle: line 109:  8318 Aborted                 ${DEBUGGER} $MYDIR/../opt/paddle/bin/paddle_trainer ${@:2}

看了下和py版本的网络配置都是resnet.py，里面已配learning_rate

**Comment by qingqing01** [comment]
`extract_fea_py.sh` 调用了 swig paddle， 这个问题应该是python问题，编译py_paddle用的python和实际运行时使用的python不是同一个。 @gangliao

**Comment by gangliao** [comment]
楼上说的没错

**Comment by dylanliuli** [comment]
没明白，是说 extract_fea_py.sh -> swig_paddle-> py_paddle 有问题？

**Comment by dylanliuli** [comment]
extract_fea_py.sh 结果正确，是extract_fea_c++.sh会挂掉

**Comment by dylanliuli** [comment]
ok了，谢谢 @gangliao 

btw，解决方法：指定 -DPYTHON_LIBRARY=xxx/libpython2.7.a 重新编译
