### ISSUE TITLE
paddlepaddle打算什么时候支持使用conda安装和支持MKL？

### ISSUE THREAD

**Issue by LittleFatHero** [PaddlePaddle/Paddle#15845]
以前在安装tensorflow的时候，发现tensorflow支持使用conda安装，超级方便。无论是windows还是Linux，只需要一个命令：
conda install tensorflow-gpu
便可以在Windows，Linux上安装好GPU版本的tensorflow。更关键在于，执行完上述命令后，会自动安装相应的cuda和cudnn，用户再也不用愁怎么安装cuda和cudnn（配置过程超级痛苦）。安装的cuda和cudnn会被隔离在conda创建的虚拟环境中，与其它conda虚拟环境中的cuda和cudnn互不干扰。这样可以很方便测试不同cuda版本之间的性能差距。conda安装的tensorflow还可以支持老版本的系统，比如tensorflow官方的安装命令pip install tensorflow是不支持在Ubuntu 16.04以下版本上安装的，但是使用conda install tensorflow确可以在Ubuntu 14.04上安装。超级nice的，兼容性超级强。

安装支持MKL的CPU版本的tensorflow也超级简单，也是一个命令，在Linux下：
conda install tensorflow
windows下：
conda install tensorflow-mkl
只需一条命令便可以安装完成支持MKL库的tensorflow，安装前并不需要事先安装MKL库。超级方便，完全实现了傻瓜式安装。对于新手超级友好。

**paddlepaddle什么时候才能提供这样的安装方式呀？
超级期待！！！！**

**Comment by luotao1** [comment]
> 只需一条命令便可以安装完成支持MKL库的tensorflow，安装前并不需要事先安装MKL库

`pip install paddlepaddle`能完成支持MKL库的安装，且事先不需要安装MKL库。

**Comment by LittleFatHero** [comment]
你逗我呢，你逗我呢，你逗我呢？？？？？？？？自己打开官网看，，，，
[http://www.paddlepaddle.org/documentation/docs/zh/1.2/beginners_guide/install/install_Windows.html#permalink-3--pip-](url)

**Comment by LittleFatHero** [comment]
@luotao1

**Comment by LittleFatHero** [comment]
官方都说不支持MKL洛，，，，，， @luotao1

**Comment by luotao1** [comment]
即将发布的release1.3版本支持windows MKL功能。linux一直支持MKL功能。

**Comment by JiabinYang** [comment]
> 你逗我呢，你逗我呢，你逗我呢？？？？？？？？自己打开官网看，，，，
> [http://www.paddlepaddle.org/documentation/docs/zh/1.2/beginners_guide/install/install_Windows.html#permalink-3--pip-](url)

**Comment by JiabinYang** [comment]
很抱歉我们目前还没有支持conda，但是我们会尽快列入计划，感谢您对PaddlePaddle的支持

**Comment by LittleFatHero** [comment]
> 即将发布的release1.3版本支持windows MKL功能。linux一直支持MKL功能。

谢谢，非常感谢 @luotao1

**Comment by LittleFatHero** [comment]
感谢 @JiabinYang

**Comment by yeyupiaoling** [comment]
我不知道为什么有人那么喜欢用conda，我基本上不使用conda，需要什么环境都可以通过命令安装。这样自己清晰。

**Comment by LittleFatHero** [comment]
@yeyupiaoling 一时conda一时爽，一直conda一直爽，真的，你试试就知道了。用miniconda就行（50MB才）。anaconda自带很多用不到的库

**Comment by yeyupiaoling** [comment]
@BigBigWolf-AI 
我用过，究竟还是pip习惯。除非万不得已

**Comment by JiaoZiLang** [comment]
同样期待conda版本，conda安装tf和pytorch都很方便啊
