### ISSUE TITLE
load_vars应该返回bool值以便判断模型加载是否成功

### ISSUE THREAD

**Issue by imistyrain** [PaddlePaddle/Paddle#15859]
目前所有的加载模型的函数比如load_vars、load_params和load_persistables都没有返回bool型的量以便判断模型加载是否成功，这种静默执行的方式隐藏了很多问题，等调试好长时间才发现是模型并没有加载成功导致的，比如路径名拼错了等.

**Comment by qingqing01** [comment]
感谢提议，很好的建议，我们可以考虑实现下。
