### ISSUE TITLE
clip操作导致分布式训练失败

### ISSUE THREAD

**Issue by hutuxian** [PaddlePaddle/Paddle#15852]
在使用fluid.DistributeTranspiler配置的分布式场景下,添加如下梯度clip：
`fluid.clip.set_gradient_clip(clip=fluid.clip.GradientClipByGlobalNorm(clip_norm=5.0))`
会导致训练失败。
其中ps端报错：
![910705e33efc4c3accc1d3e76d9360a9](https://user-images.githubusercontent.com/11195205/53163410-f6d05f00-3608-11e9-9e90-2cf3c6ea1bf1.jpg)
trainer端报错：
GetRPC name:[atten_fc1.b_0], ep:[127.0.0.1:6000], status:[-1] meets grpc error, error_code:14 error_message:Socket closed error_details:

**Comment by jacquesqiao** [comment]
给个复现的例子

**Comment by hutuxian** [comment]
模型还未发布，后面会提供一个最小可复现的例子
