### ISSUE TITLE
“Fluid编程指南”页面上有个链接可能需要修改

### ISSUE THREAD

**Issue by houj04** [PaddlePaddle/Paddle#15878]
首页是
http://www.paddlepaddle.org/
点里面的“官方中文文档”，进入到
http://www.paddlepaddle.org/documentation/docs/zh/1.2/beginners_guide/index.html
然后点左边的“Fluid编程指南”，进入到
http://www.paddlepaddle.org/documentation/docs/zh/1.2/beginners_guide/programming_guide/programming_guide.html
这个页面上有一个“可以参考阅读Fluid设计思想”，进入到
http://www.paddlepaddle.org/documentation/docs/zh/1.2/user_guides/design_idea/fluid_design_idea.html
然后发现这个页面上的图挂了。
推测的原因和fix：设计思想的正确的链接，应该是这个：
http://www.paddlepaddle.org/documentation/docs/zh/1.2/advanced_usage/design_idea/fluid_design_idea.html

**Comment by shanyi15** [comment]
感谢反馈，正在修复ing
