### ISSUE TITLE
[Fluid 1.2]infer时报错Tensor holds no memory.

### ISSUE THREAD

**Issue by shiyazhou121** [PaddlePaddle/Paddle#15879]
paddle版本：fluid 1.2
情况是训练没有报错，模型也收敛了。但是python的infer和C++的infer都报错Tensor holds no memory. Call Tensor::mutable_data first. at [/paddle/paddle/fluid/framework/tensor.cc:22]
python infer报错如下：
![image](https://user-images.githubusercontent.com/15082798/53227910-a285b780-36ba-11e9-8f8c-61a8d3efab2a.png)
C++ infer报错如下：
![image](https://user-images.githubusercontent.com/15082798/53228697-ebd70680-36bc-11e9-986f-ec207aeae543.png)

部分网络结构如下：
feature传入的数据格式是一维序列，比如 [1 2 3 4]
![image](https://user-images.githubusercontent.com/15082798/53228110-2b045800-36bb-11e9-9f43-9eb750b870c2.png)
![image](https://user-images.githubusercontent.com/15082798/53228189-643cc800-36bb-11e9-92be-7267d49abb0c.png)

**Comment by Yancey0623** [comment]
infer之前是否有执行 startup_program 呢？

**Comment by shiyazhou121** [comment]
@Yancey1989 没有，但是模型文件替换成lstm的可以正常出结果
![image](https://user-images.githubusercontent.com/15082798/53228746-11641000-36bd-11e9-8d86-749155e3f9bc.png)

**Comment by Yancey0623** [comment]
hi @shiyazhou121 麻烦贴一下 paddle的版本以及 infer program 的 feed_target_names

**Comment by shiyazhou121** [comment]
@Yancey1989 hi，感谢帮忙排查问题，最后发现是lod_reset时用了label标签，infer时没有数据传入导致的报错。
