### ISSUE TITLE
保存权重到一个文件后，加载有问题

### ISSUE THREAD

**Issue by AIFollowers** [PaddlePaddle/Paddle#15885]
![7a880e5b3282ddc7fcff6fff05403bd4](https://user-images.githubusercontent.com/42403163/53238654-ca821480-36d4-11e9-93a1-f23ccb6c18ca.png)
<img width="791" alt="4af8b6681f9603b4b3b802d5b09336ff" src="https://user-images.githubusercontent.com/42403163/53238661-d1a92280-36d4-11e9-8e93-539f16fd4cdb.png">

Paddle1.2版本
GPU K40 4块显卡

**Comment by yeyupiaoling** [comment]
@AIFollowers 文件名有没有对呢？

**Comment by AIFollowers** [comment]
@yeyupiaoling 这个没有问题
