### ISSUE TITLE
paddlepaddle到底支持cuda哪个版本？

### ISSUE THREAD

**Issue by LittleFatHero** [PaddlePaddle/Paddle#15896]
很高兴看到paddlepaddle官网终于实现了类似于pytorch的选择环境然后生成安装命令的快速安装模式，但是，其中也有歧义的，在cuda那一栏，有9和8两个数字可以选，这个是什么意思呢？
比如选9，是只支持cuda 9.0还是支持cuda 9+，比如cuda 9.2。如果只支持 CUDA 9.0，那么建议像pytorch官网那样，把 9改成 9.0， 8改成8.0。

**Comment by yeyupiaoling** [comment]
@BigBigWolf-AI 我的理解是9是支持9+，因为我觉得它归根到底还是9版本

**Comment by joodo** [comment]
您好，我们兼容小版本，比如 CUDA 9，是支持 9.x 的
