### ISSUE TITLE
paddlepaddle什么时候能实现一条命令就能安装好paddle和CUDA和CUDNN？

### ISSUE THREAD

**Issue by LittleFatHero** [PaddlePaddle/Paddle#15895]
对于新人来说，安装CUDA和CUDNN是非常痛苦的，因为要配置各种环境变量，设置path。最可怕的是，百度一下，你会发现安装CUDA和CUDNN的方法有一亿种这么多，根本不知道相信谁。
tensorflow就很贴心地解决了这个问题，在安装好显卡驱动（这个安装起来超简单）的前提下只需下面一条命令：
conda create -n tensorflow_gpuenv tensorflow-gpu
就能将tensorflow以及CUDA and CUDNN都安装好，对于新人简直不能太友好了。
如果paddlepaddle能够实现这样的安装，那么估计用的人会越来越多。
上面的命令会根据不同的操作系统自动解决各种依赖包的安装，简直不能再棒了。
详情请参考（估计你们也不会看，但是还是列出来吧）：
[https://www.anaconda.com/tensorflow-in-anaconda/](url)

**Comment by wopeizl** [comment]
很好的建议，paddle目前有提供快速安装的脚本但是不提供一键安装cuda和cudnn的能力，我们会认真考虑您的建议


在 2019年2月24日，下午5:54，BigBigWolf-AI <notifications@github.com<mailto:notifications@github.com>> 写道：


对于新人来说，安装CUDA和CUDNN是非常痛苦的，因为要配置各种环境变量，设置path。最可怕的是，百度一下，你会发现安装CUDA和CUDNN的方法有一亿种这么多，根本不知道相信谁。
tensorflow就很贴心地解决了这个问题，在安装好显卡驱动（这个安装起来超简单）的前提下只需下面一条命令：
conda create -n tensorflow_gpuenv tensorflow-gpu
就能将tensorflow以及CUDA and CUDNN都安装好，对于新人简直不能太友好了。
如果paddlepaddle能够实现这样的安装，那么估计用的人会越来越多。
上面的命令会根据不同的操作系统自动解决各种依赖包的安装，简直不能再棒了。
详情请参考（估计你们也不会看，但是还是列出来吧）：
https://www.anaconda.com/tensorflow-in-anaconda/<url>

**Comment by yeyupiaoling** [comment]
@BigBigWolf-AI 这样可以写一个脚本，一条命令是不可能的吧，毕竟CUDA和CUDNN又不是PaddlePaddle的。

**Comment by LittleFatHero** [comment]
可以一条命令来安装的，通过conda来解决（pytorch，tensorflow都可以通过conda来安装，不需要安装cudnn和cuda，只需要驱动，非常简单）。为什么要这样呢？因为这样有很多好处，conda创建不同的虚拟环境中，可以安装不同的cuda版本。如果你用pip，那么只能使用系统安装的cuda。而且，更为关键的是，conda解决依赖的能力是真的强，tensorflow官方不支持Ubuntu 14.04，但是conda安装的tensorflow可以支持。感觉conda真的有点容器的概念，非常好的。这就是当今最流行的深度学习框架pytorch官方直接推荐使用conda安装的原因。

**Comment by yeyupiaoling** [comment]
支不支持是一回事，有人喜欢这样用，那肯定要支持的。只是我个人喜欢用pip，安装的东西我都可以掌控。
