### ISSUE TITLE
根据0-1向量取tensor value

### ISSUE THREAD

**Issue by littletomatodonkey** [PaddlePaddle/Paddle#15903]
我现在有一个[0,1,0,0,1]的tensor A，有一个[5,4,3,2,1]的tensor B，我想根据这个0,1矩阵取出B中特定的行，即希望结果是[4,1]。我想问一下这个操作在paddle里怎么实现呢？gather里面好像只能根据index取出特定的行。

**Comment by chengduoZH** [comment]
目前没有直接的方法可以实现这个操作。你可以将A转化为index形式。

**Comment by littletomatodonkey** [comment]
那怎么将A转化为index形式呢？

**Comment by chengduoZH** [comment]
首先明确一下，您的issue题目中写的是one-hot，但是您给的例子中的A并不是one-hot。您可以再准确的描述一下您的需求吗

**Comment by littletomatodonkey** [comment]
您好， 我修改了issue的题目，我希望根据这个0-1的向量取出B对应的行，谢谢您。

**Comment by chengduoZH** [comment]
tensor A 是模型中间计算结果，还是模型的输入？

**Comment by littletomatodonkey** [comment]
tensor A是模型中间计算的结果

**Comment by chengduoZH** [comment]
如果是求tensor中的最大元素用argmax，如果是找==1的目前还没有这样的layer
