### ISSUE TITLE
self-attention性能优化问题

### ISSUE THREAD

**Issue by shiyazhou121** [PaddlePaddle/Paddle#15918]
版本：Fluid 1.2
问题：自己实现self-attention + CRF的模型，但性能比BiLstm+CRF低很多。哪些地方可以做优化？我发现一维序列的长度对性能影响特别大，是因为scale_dot_product时矩阵相乘耗时吗？怎么优化这部分。。

**Comment by chengduoZH** [comment]
你可以用profiler工具分析一下 http://paddlepaddle.org/documentation/docs/zh/1.2/advanced_usage/development/profiling/timeline_cn.html

**Comment by shiyazhou121** [comment]
@chengduoZH 用profiler分析了下infer。
![image](https://user-images.githubusercontent.com/15082798/53381509-1ae6c400-39ac-11e9-9c02-f7fb340d751e.png)
占性能的是softmax和matmul，对应网络中的scale_dot_product_att。

```
def scaled_dot_product_attention(q, k, v):
     product = fluid.layers.matmul(x=q, y=k, transpose_y=True, alpha=FC_DIM**-0.5)
     weights = fluid.layers.softmax(product)
     att = fluid.layers.matmul(weights, v)
     return att
```
请问有什么方法可以优化吗？

**Comment by shiyazhou121** [comment]
感谢paddle同学帮忙

**Comment by lancer94** [comment]
hello，请问下这个问题解决了吗
