### ISSUE TITLE
face_detection 模型 program 描述中有一部分 var 的 dim 为非 -1 的负数

### ISSUE THREAD

**Issue by Karbit** [PaddlePaddle/Paddle#15927]
[环境]
PaddlePaddle 1.2.1, compiled with
    with_avx: ON
    with_gpu: OFF
    with_mkl: OFF
    with_mkldnn: OFF
    with_double: OFF
    with_python: ON
    with_rdma: OFF
    with_timer: OFF
[模型] face_detection https://github.com/PaddlePaddle/models/tree/develop/fluid/PaddleCV/face_detection
[问题] 
在 train.py 中 140 行增加如下打印指令：
print(train_prog.to_string(False))
发现打印出来的 program 描述中有一部分 var 的 dim 为负数（如下所示），且不为 -1，不知道是否符合预期：
  vars {
    name: "tmp_12"
    type {
      type: LOD_TENSOR
      lod_tensor {
        tensor {
          data_type: FP32
          dims: -34125
          dims: 1
        }
        lod_level: 0
      }
    }
  }

**Comment by qingqing01** [comment]
@Karbit 在构建Program/网络图时，batch size维度是-1，其他维度可能是正数，在经过reshape(等) op时，-1参与维度的计算，就会导致在构建的Program里出现非-1的负数。 实际在运行时(executor run时)是每个tensor的shape是不存在负数的。 如果想查看运行时的真实shape，也可以通过fluid.layers.Print()接口在看。

**Comment by Karbit** [comment]
理解了，多谢解答！
