### ISSUE TITLE
models/legacy/ctr 下 执行文档中的命令后报错

### ISSUE THREAD

**Issue by Yve-Neal** [PaddlePaddle/Paddle#15920]
按照这个文档https://github.com/PaddlePaddle/models/tree/develop/legacy/ctr一次运行完：
一： mkdir -p output; python avazu_data_processer.py --data_path train.txt --output_dir output --num_lines_to_detect 1000 --test_set_size 100 
二：python train.py --train_data_path ./output/train.txt --test_data_path ./output/test.txt --data_meta_file ./output/data.meta.txt --model_type=0
后报如下错：
I0225 20:16:28.711913 15929 Util.cpp:166] commandline:  --use_gpu=False --trainer_count=1 
INFO:paddle:dnn input dim: 61
INFO:paddle:lr input dim: 10040001
I0225 20:16:28.911039 15929 GradientMachine.cpp:94] Initing parameters..
I0225 20:16:29.801417 15929 GradientMachine.cpp:101] Init parameters done.
INFO:paddle:load trainset from ./output/train.txt
WARNING:paddle:Pass 0, Samples 0, Cost 0.686135, {}
INFO:paddle:load testset from ./output/test.txt
Traceback (most recent call last):
  File "train.py", line 112, in <module>
    train()
  File "train.py", line 108, in train
    num_passes=args.num_passes)
  File "/home/anaconda2/lib/python2.7/site-packages/paddle/v2/trainer.py", line 206, in train
    gm=self.__gradient_machine__))
  File "train.py", line 90, in __event_handler__
    feeding=reader.feeding_index)
  File "/home/opt/anaconda2/lib/python2.7/site-packages/paddle/v2/trainer.py", line 247, in test
    evaluator=evaluator, cost=total_cost / num_samples)
ZeroDivisionError: float division by zero

**Comment by chengduoZH** [comment]
> ZeroDivisionError: float division by zero

是python端抛出来的错
