### ISSUE TITLE
paddle v1.3.0  多节点运行时模型保存不完整

### ISSUE THREAD

**Issue by yxfGrace** [PaddlePaddle/Paddle#15932]
2个节点的cpu作业，pserver模式，用的是https://github.com/PaddlePaddle/Paddle/blob/v1.3.0/python/paddle/fluid/tests/book/notest_understand_sentiment.py  这个demo
保存模型后，两个节点中保存的模型不一致，其中一个节点的模型不完整，导致在load模型时报错
![image](https://user-images.githubusercontent.com/29363426/53393225-c0169200-39d6-11e9-89a6-a7b357d81805.png)
在输出中确实没有这个模型
同样的demo用paddle-v1.2.0是可以成功运行的
新版paddle的模型保存接口是否有变化呢？

**Comment by kuke** [comment]
模型保存接口没有任何变化，可能是保存模型的时候其中一个节点被异常中断了，你可以再跑一次试试

**Comment by yxfGrace** [comment]
> 模型保存接口没有任何变化，可能是保存模型的时候其中一个节点被异常中断了，你可以再跑一次试试

可以稳定复现的呢
而且每次缺的模型都是相同的  所以应该不是随机问题

**Comment by seiriosPlus** [comment]
是做增量还是做预测？
贴一下多机save/load的用法

**Comment by yxfGrace** [comment]
> 是做增量还是做预测？
> 贴一下多机save/load的用法
用的就是官网上的这个demo https://github.com/PaddlePaddle/Paddle/blob/v1.3.0/python/paddle/fluid/tests/book/notest_understand_sentiment.py
只是改成了多机运行的模式
save:
```
def train_loop(main_program):
        exe.run(fluid.default_startup_program())

        for pass_id in range(PASS_NUM):
            for data in train_data():
                cost_val, acc_val = exe.run(main_program,
                                            feed=feeder.feed(data),
                                            fetch_list=[cost, acc_out])
                print("cost=" + str(cost_val) + " acc=" + str(acc_val))
                if cost_val < 0.4 and acc_val > 0.8:
                    if save_dirname is not None:
                        fluid.io.save_inference_model(save_dirname, ["words"],
                                                      prediction, exe)
                    exe.close()
                    return
                if math.isnan(float(cost_val)):
                    sys.exit("got NaN loss, training failed.")
        raise AssertionError("Cost is too large for {0}".format(
            net_method.__name__))
```
load:
```
def infer(word_dict_len, use_cuda, save_dirname=None):
    if save_dirname is None:
        return

    place = fluid.CUDAPlace(0) if use_cuda else fluid.CPUPlace()
    exe = fluid.Executor(place)

    inference_scope = fluid.core.Scope()
    with fluid.scope_guard(inference_scope):
        # Use fluid.io.load_inference_model to obtain the inference program desc,
        # the feed_target_names (the names of variables that will be feeded
        # data using feed operators), and the fetch_targets (variables that
        # we want to obtain data from using fetch operators).
        [inference_program, feed_target_names,
         fetch_targets] = fluid.io.load_inference_model(save_dirname, exe)
```

**Comment by seiriosPlus** [comment]
贴一下多机运行模式的写法， 1.3是有一点变化，我得确认一下你是怎么写的

**Comment by yxfGrace** [comment]
> 贴一下多机运行模式的写法， 1.3是有一点变化，我得确认一下你是怎么写的

#!/bin/env python
# -*- encoding:utf-8 -*-
"""
understand sentiment demo
Authors: yangjintao
refer to:
https://github.com/PaddlePaddle/Paddle/blob/v1.3.0/python/paddle/fluid/tests/book/notest_understand_sentiment.py
"""

from __future__ import print_function

from paddle.fluid.layers.device import get_places
import unittest
import paddle.fluid as fluid
import paddle
import contextlib
import math
import numpy as np
import sys
import os
import pickle

def convolution_net(data, label, input_dim, class_dim=2, emb_dim=32,
                    hid_dim=32):

    emb = fluid.layers.embedding(
        input=data, size=[input_dim, emb_dim], is_sparse=True)
    conv_3 = fluid.nets.sequence_conv_pool(
        input=emb,
        num_filters=hid_dim,
        filter_size=3,
        act="tanh",
        pool_type="sqrt")
    conv_4 = fluid.nets.sequence_conv_pool(
        input=emb,
        num_filters=hid_dim,
        filter_size=4,
        act="tanh",
        pool_type="sqrt")
    prediction = fluid.layers.fc(input=[conv_3, conv_4],
                                 size=class_dim,
                                 act="softmax")
    cost = fluid.layers.cross_entropy(input=prediction, label=label)
    avg_cost = fluid.layers.mean(cost)
    accuracy = fluid.layers.accuracy(input=prediction, label=label)
    return avg_cost, accuracy, prediction


def dyn_rnn_lstm(data, label, input_dim, class_dim=2, emb_dim=32,
                 lstm_size=128):

    emb = fluid.layers.embedding(
        input=data, size=[input_dim, emb_dim], is_sparse=True)
    sentence = fluid.layers.fc(input=emb, size=lstm_size, act='tanh')

    rnn = fluid.layers.DynamicRNN()
    with rnn.block():
        word = rnn.step_input(sentence)
        prev_hidden = rnn.memory(value=0.0, shape=[lstm_size])
        prev_cell = rnn.memory(value=0.0, shape=[lstm_size])

        def gate_common(ipt, hidden, size):

            gate0 = fluid.layers.fc(input=ipt, size=size, bias_attr=True)
            gate1 = fluid.layers.fc(input=hidden, size=size, bias_attr=False)
            return gate0 + gate1

        forget_gate = fluid.layers.sigmoid(x=gate_common(word, prev_hidden,
                                                         lstm_size))
        input_gate = fluid.layers.sigmoid(x=gate_common(word, prev_hidden,
                                                        lstm_size))
        output_gate = fluid.layers.sigmoid(x=gate_common(word, prev_hidden,
                                                         lstm_size))
        cell_gate = fluid.layers.sigmoid(x=gate_common(word, prev_hidden,
                                                       lstm_size))

        cell = forget_gate * prev_cell + input_gate * cell_gate
        hidden = output_gate * fluid.layers.tanh(x=cell)
        rnn.update_memory(prev_cell, cell)
        rnn.update_memory(prev_hidden, hidden)
        rnn.output(hidden)

    last = fluid.layers.sequence_last_step(rnn())
    prediction = fluid.layers.fc(input=last, size=class_dim, act="softmax")
    cost = fluid.layers.cross_entropy(input=prediction, label=label)
    avg_cost = fluid.layers.mean(cost)
    accuracy = fluid.layers.accuracy(input=prediction, label=label)
    return avg_cost, accuracy, prediction


def stacked_lstm_net(data,
                     label,
                     input_dim,
                     class_dim=2,
                     emb_dim=128,
                     hid_dim=512,
                     stacked_num=3):

    assert stacked_num % 2 == 1

    emb = fluid.layers.embedding(
        input=data, size=[input_dim, emb_dim], is_sparse=True)
    # add bias attr

    # TODO(qijun) linear act
    fc1 = fluid.layers.fc(input=emb, size=hid_dim)
    lstm1, cell1 = fluid.layers.dynamic_lstm(input=fc1, size=hid_dim)

    inputs = [fc1, lstm1]

    for i in range(2, stacked_num + 1):
        fc = fluid.layers.fc(input=inputs, size=hid_dim)
        lstm, cell = fluid.layers.dynamic_lstm(
            input=fc, size=hid_dim, is_reverse=(i % 2) == 0)
        inputs = [fc, lstm]

    fc_last = fluid.layers.sequence_pool(input=inputs[0], pool_type='max')
    lstm_last = fluid.layers.sequence_pool(input=inputs[1], pool_type='max')

    prediction = fluid.layers.fc(input=[fc_last, lstm_last],
                                 size=class_dim,
                                 act='softmax')
    cost = fluid.layers.cross_entropy(input=prediction, label=label)
    avg_cost = fluid.layers.mean(cost)
    accuracy = fluid.layers.accuracy(input=prediction, label=label)
    return avg_cost, accuracy, prediction


def train(dict_dim,
          net_method,
          use_cuda,
          parallel=False,
          save_dirname=None,
          is_local=True):
    BATCH_SIZE = 128
    PASS_NUM = 5
    class_dim = 2

    data = fluid.layers.data(
        name="words", shape=[1], dtype="int64", lod_level=1)
    label = fluid.layers.data(name="label", shape=[1], dtype="int64")

    if not parallel:
        cost, acc_out, prediction = net_method(
            data, label, input_dim=dict_dim, class_dim=class_dim)
    else:
        raise NotImplementedError()

    adagrad = fluid.optimizer.Adagrad(learning_rate=0.002)
    adagrad.minimize(cost)

    train_data = paddle.batch(
        paddle.reader.shuffle(
            paddle.dataset.imdb.train(word_dict), buf_size=1000),
        batch_size=BATCH_SIZE)
    place = fluid.CUDAPlace(0) if use_cuda else fluid.CPUPlace()
    exe = fluid.Executor(place)
    feeder = fluid.DataFeeder(feed_list=[data, label], place=place)

    def train_loop(main_program):

        exe.run(fluid.default_startup_program())

        for pass_id in range(PASS_NUM):
            for data in train_data():
                cost_val, acc_val = exe.run(main_program,
                                            feed=feeder.feed(data),
                                            fetch_list=[cost, acc_out])
                print("cost=" + str(cost_val) + " acc=" + str(acc_val))
                if cost_val < 0.4 and acc_val > 0.8:
                    if save_dirname is not None:
                        fluid.io.save_inference_model(save_dirname, ["words"],
                                                      prediction, exe)
                    exe.close()
                    return
                if math.isnan(float(cost_val)):
                    sys.exit("got NaN loss, training failed.")
        raise AssertionError("Cost is too large for {0}".format(
            net_method.__name__))

    if is_local:
        train_loop(fluid.default_main_program())
    else:
        port = os.getenv("PADDLE_PSERVER_PORT", "6174")
        pserver_ips = os.getenv("PADDLE_PSERVER_IPS")  # ip,ip...
        eplist = []
        for ip in pserver_ips.split(","):
            eplist.append(':'.join([ip, port]))
        pserver_endpoints = ",".join(eplist)  # ip:port,ip:port...
        trainers = int(os.getenv("PADDLE_TRAINERS"))
        current_endpoint = os.getenv("POD_IP") + ":" + port
        trainer_id = int(os.getenv("PADDLE_TRAINER_ID"))
        training_role = os.getenv("PADDLE_TRAINING_ROLE", "TRAINER")
        t = fluid.DistributeTranspiler()
        t.transpile(trainer_id, pservers=pserver_endpoints, trainers=trainers)
        if training_role == "PSERVER":
            pserver_prog = t.get_pserver_program(current_endpoint)
            pserver_startup = t.get_startup_program(current_endpoint,
                                                    pserver_prog)
            exe.run(pserver_startup)
            exe.run(pserver_prog)
        elif training_role == "TRAINER":
            train_loop(t.get_trainer_program())


def infer(word_dict_len, use_cuda, save_dirname=None):

    if save_dirname is None:
        return

    place = fluid.CUDAPlace(0) if use_cuda else fluid.CPUPlace()
    exe = fluid.Executor(place)

    inference_scope = fluid.core.Scope()
    with fluid.scope_guard(inference_scope):
        # Use fluid.io.load_inference_model to obtain the inference program desc,
        # the feed_target_names (the names of variables that will be feeded
        # data using feed operators), and the fetch_targets (variables that
        # we want to obtain data from using fetch operators).
        [inference_program, feed_target_names,
         fetch_targets] = fluid.io.load_inference_model(save_dirname, exe)

        # Setup input by creating LoDTensor to represent sequence of words.
        # Here each word is the basic element of the LoDTensor and the shape of
        # each word (base_shape) should be [1] since it is simply an index to
        # look up for the corresponding word vector.
        # Suppose the recursive_sequence_lengths info is set to [[3, 4, 2]],
        # which has only one level of detail. Then the created LoDTensor will have only
        # one higher level structure (sequence of words, or sentence) than the basic
        # element (word). Hence the LoDTensor will hold data for three sentences of
        # length 3, 4 and 2, respectively.
        # Note that recursive_sequence_lengths should be a list of lists.
        recursive_seq_lens = [[3, 4, 2]]
        base_shape = [1]
        # The range of random integers is [low, high]
        tensor_words = fluid.create_random_int_lodtensor(
            recursive_seq_lens,
            base_shape,
            place,
            low=0,
            high=word_dict_len - 1)

        # Construct feed as a dictionary of {feed_target_name: feed_target_data}
        # and results will contain a list of data corresponding to fetch_targets.
        assert feed_target_names[0] == "words"
        results = exe.run(inference_program,
                          feed={feed_target_names[0]: tensor_words},
                          fetch_list=fetch_targets,
                          return_numpy=False)
        print(results[0].recursive_sequence_lengths())
        np_data = np.array(results[0])
        print("Inference Shape: ", np_data.shape)
        print("Inference results: ", np_data)


def main(use_cuda, is_local):

    if use_cuda and not fluid.core.is_compiled_with_cuda():
        return
    with open("./word_dict.pkl", 'r') as fp:
        word_dict = pickle.load(fp)
    dict_dim = len(word_dict)
    save_dirname = "./model/"
    if not os.path.isdir(save_dirname):
        os.makedirs(save_dirname)
    train(
        dict_dim=dict_dim,
        net_method=convolution_net,
        use_cuda=use_cuda,
        parallel=False,
        save_dirname=save_dirname,
        is_local=is_local)
    infer(dict_dim, use_cuda, save_dirname)

if __name__ == '__main__':
    use_cuda = False
    is_local = False
    main(use_cuda, is_local)

**Comment by seiriosPlus** [comment]
调用```fluid.io.save_inference_model``` 的时候把 训练的```main_program```传进去看看呢？

**Comment by yxfGrace** [comment]
> 调用`fluid.io.save_inference_model` 的时候把 训练的`main_program`传进去看看呢？

还是一样的报错呢

**Comment by seiriosPlus** [comment]
能把main_program的proto贴一下么， 把 load报错也贴一下

**Comment by yxfGrace** [comment]
> 能把main_program的proto贴一下么， 把 load报错也贴一下
```
def train_loop(main_program):
        exe.run(fluid.default_startup_program())

        for pass_id in range(PASS_NUM):
            for data in train_data():
                cost_val, acc_val = exe.run(main_program,
                                            feed=feeder.feed(data),
                                            fetch_list=[cost, acc_out])
                print("cost=" + str(cost_val) + " acc=" + str(acc_val))
                if cost_val < 0.4 and acc_val > 0.8:
                    if save_dirname is not None:
                        fluid.io.save_inference_model(save_dirname, ["words"],
                                                      prediction, exe,  main_program=main_program)
                    exe.close()
                    return
                if math.isnan(float(cost_val)):
                    sys.exit("got NaN loss, training failed.")
        raise AssertionError("Cost is too large for {0}".format(
            net_method.__name__))
```
报错：
![image](https://user-images.githubusercontent.com/29363426/53465574-70dd6980-3a89-11e9-97f2-8d642aba49a8.png)

**Comment by seiriosPlus** [comment]
proto这样打印:
```
        with open("xxx.proto", "w") as f:
            f.write(str(main_program))
```

**Comment by yxfGrace** [comment]
> proto这样打印:
> 
> ```
>         with open("xxx.proto", "w") as f:
>             f.write(str(main_program))
> ```

```
blocks {
  idx: 0
  parent_idx: -1
  vars {
    name: "__control_var@0.119813869578"
    type {
      type: LOD_TENSOR
    }
  }
  vars {
    name: "sequence_conv_1.w_0@GRAD.trainer_1"
    type {
      type: LOD_TENSOR
      lod_tensor {
        tensor {
          data_type: FP32
          dims: 128
          dims: 32
        }
      }
    }
  }
  vars {
    name: "sequence_conv_0.w_0@GRAD.trainer_1"
    type {
      type: LOD_TENSOR
      lod_tensor {
        tensor {
          data_type: FP32
          dims: 96
          dims: 32
        }
      }
    }
  }
  vars {
    name: "fc_0.w_1@GRAD.trainer_1"
    type {
      type: LOD_TENSOR
      lod_tensor {
        tensor {
          data_type: FP32
          dims: 32
          dims: 2
        }
      }
    }
  }
  vars {
    name: "embedding_0.w_0@GRAD.block1.trainer_1"
    type {
      type: SELECTED_ROWS
      selected_rows {
        data_type: FP32
        dims: 2573
        dims: 32
      }
    }
    persistable: false
  }
  vars {
    name: "__control_var@0.334408286034"
    type {
      type: LOD_TENSOR
    }
  }
  vars {
    name: "moment_6"
    type {
      type: LOD_TENSOR
      lod_tensor {
        tensor {
          data_type: FP32
          dims: 32
        }
      }
    }
    persistable: true
  }
  vars {
    name: "__control_var@0.753401413363"
    type {
      type: LOD_TENSOR
    }
  }
  vars {
    name: "moment_5"
    type {
      type: LOD_TENSOR
      lod_tensor {
        tensor {
          data_type: FP32
          dims: 96
          dims: 32
        }
      }
    }
    persistable: true
  }
  vars {
    name: "moment_4"
    type {
      type: LOD_TENSOR
      lod_tensor {
        tensor {
          data_type: FP32
          dims: 32
        }
      }
    }
    persistable: true
  }
  vars {
    name: "__control_var@0.445538270747"
    type {
      type: LOD_TENSOR
    }
  }
  vars {
    name: "__control_var@0.869797579123"
    type {
      type: LOD_TENSOR
    }
  }
  vars {
    name: "sequence_conv_0.b_0@GRAD.trainer_1"
    type {
      type: LOD_TENSOR
      lod_tensor {
        tensor {
          data_type: FP32
          dims: 32
        }
        lod_level: 0
      }
    }
  }
  vars {
    name: "moment_3"
    type {
      type: LOD_TENSOR
      lod_tensor {
        tensor {
          data_type: FP32
          dims: 32
          dims: 2
        }
      }
    }
    persistable: true
  }
  vars {
    name: "moment_2"
    type {
      type: LOD_TENSOR
      lod_tensor {
        tensor {
          data_type: FP32
          dims: 32
          dims: 2
        }
      }
    }
    persistable: true
  }
  vars {
    name: "embedding_0.tmp_0@GRAD"
    type {
      type: LOD_TENSOR
      lod_tensor {
        tensor {
          data_type: FP32
          dims: -1
          dims: 32
        }
        lod_level: 1
      }
    }
  }
  vars {
    name: "moment_7"
    type {
      type: LOD_TENSOR
      lod_tensor {
        tensor {
          data_type: FP32
          dims: 128
          dims: 32
        }
      }
    }
    persistable: true
  }
  vars {
    name: "sequence_conv_0.tmp_1@GRAD"
    type {
      type: LOD_TENSOR
      lod_tensor {
        tensor {
          data_type: FP32
          dims: -1
          dims: 32
        }
        lod_level: 1
      }
    }
  }
  vars {
    name: "fc_0.b_0"
    type {
      type: LOD_TENSOR
      lod_tensor {
        tensor {
          data_type: FP32
          dims: 2
        }
      }
    }
    persistable: true
  }
  vars {
    name: "sequence_conv_0.w_0"
    type {
      type: LOD_TENSOR
      lod_tensor {
        tensor {
          data_type: FP32
          dims: 96
          dims: 32
        }
      }
    }
    persistable: true
  }
  vars {
    name: "sequence_pool_0.tmp_0@GRAD"
    type {
      type: LOD_TENSOR
      lod_tensor {
        tensor {
          data_type: FP32
          dims: -1
          dims: 32
        }
      }
    }
  }
  vars {
    name: "embedding_0.w_0@GRAD.block0.trainer_1"
    type {
      type: SELECTED_ROWS
      selected_rows {
        data_type: FP32
        dims: 2574
        dims: 32
      }
    }
    persistable: false
  }
  vars {
    name: "fc_0.tmp_4@GRAD"
    type {
      type: LOD_TENSOR
      lod_tensor {
        tensor {
          data_type: FP32
          dims: -1
          dims: 2
        }
        lod_level: 0
      }
    }
  }
  vars {
    name: "fc_0.b_0@GRAD.trainer_1"
    type {
      type: LOD_TENSOR
      lod_tensor {
        tensor {
          data_type: FP32
          dims: 2
        }
        lod_level: 0
      }
    }
  }
  vars {
    name: "fc_0.tmp_1@GRAD"
    type {
      type: LOD_TENSOR
      lod_tensor {
        tensor {
          data_type: FP32
          dims: -1
          dims: 2
        }
        lod_level: 0
      }
    }
  }
  vars {
    name: "fc_0.tmp_0"
    type {
      type: LOD_TENSOR
      lod_tensor {
        tensor {
          data_type: FP32
          dims: -1
          dims: 2
        }
        lod_level: 0
      }
    }
    persistable: false
  }
  vars {
    name: "fc_0.tmp_3"
    type {
      type: LOD_TENSOR
      lod_tensor {
        tensor {
          data_type: FP32
          dims: -1
          dims: 2
        }
        lod_level: 0
      }
    }
    persistable: false
  }
  vars {
    name: "moment_1"
    type {
      type: LOD_TENSOR
      lod_tensor {
        tensor {
          data_type: FP32
          dims: 2
        }
      }
    }
    persistable: true
  }
  vars {
    name: "fc_0.w_0"
    type {
      type: LOD_TENSOR
      lod_tensor {
        tensor {
          data_type: FP32
          dims: 32
          dims: 2
        }
      }
    }
    persistable: true
  }
  vars {
    name: "sequence_pool_1.tmp_1"
    type {
      type: LOD_TENSOR
      lod_tensor {
        tensor {
          data_type: FP32
        }
      }
    }
    persistable: false
  }
  vars {
    name: "sequence_conv_1.tmp_1"
    type {
      type: LOD_TENSOR
      lod_tensor {
        tensor {
          data_type: FP32
          dims: -1
          dims: 32
        }
        lod_level: 1
      }
    }
    persistable: false
  }
  vars {
    name: "mean_0.tmp_0@GRAD"
    type {
      type: LOD_TENSOR
      lod_tensor {
        tensor {
          data_type: FP32
          dims: 1
        }
      }
    }
  }
  vars {
    name: "fc_0.tmp_1"
    type {
      type: LOD_TENSOR
      lod_tensor {
        tensor {
          data_type: FP32
          dims: -1
          dims: 2
        }
        lod_level: 0
      }
    }
    persistable: false
  }
  vars {
    name: "learning_rate_0"
    type {
      type: LOD_TENSOR
      lod_tensor {
        tensor {
          data_type: FP32
          dims: 1
        }
      }
    }
    persistable: true
  }
  vars {
    name: "sequence_pool_0.tmp_0"
    type {
      type: LOD_TENSOR
      lod_tensor {
        tensor {
          data_type: FP32
          dims: -1
          dims: 32
        }
      }
    }
    persistable: false
  }
  vars {
    name: "__control_var@0.423767983778"
    type {
      type: LOD_TENSOR
    }
  }
  vars {
    name: "__control_var@0.581755186727"
    type {
      type: LOD_TENSOR
    }
  }
  vars {
    name: "fc_0.tmp_3@GRAD"
    type {
      type: LOD_TENSOR
      lod_tensor {
        tensor {
          data_type: FP32
          dims: -1
          dims: 2
        }
      }
    }
  }
  vars {
    name: "sequence_pool_1.tmp_0@GRAD"
    type {
      type: LOD_TENSOR
      lod_tensor {
        tensor {
          data_type: FP32
          dims: -1
          dims: 32
        }
      }
    }
  }
  vars {
    name: "words"
    type {
      type: LOD_TENSOR
      lod_tensor {
        tensor {
          data_type: INT64
          dims: -1
          dims: 1
        }
        lod_level: 1
      }
    }
    persistable: false
  }
  vars {
    name: "__control_var@0.230084648915"
    type {
      type: LOD_TENSOR
    }
  }
  vars {
    name: "label"
    type {
      type: LOD_TENSOR
      lod_tensor {
        tensor {
          data_type: INT64
          dims: -1
          dims: 1
        }
        lod_level: 0
      }
    }
    persistable: false
  }
  vars {
    name: "top_k_0.tmp_1"
    type {
      type: LOD_TENSOR
      lod_tensor {
        tensor {
          data_type: INT64
          dims: -1
          dims: 1
        }
        lod_level: 0
      }
    }
    persistable: false
  }
  vars {
    name: "sequence_conv_1.tmp_0"
    type {
      type: LOD_TENSOR
      lod_tensor {
        tensor {
          data_type: FP32
          dims: -1
          dims: 32
        }
        lod_level: 1
      }
    }
    persistable: false
  }
  vars {
    name: "sequence_conv_0.tmp_0"
    type {
      type: LOD_TENSOR
      lod_tensor {
        tensor {
          data_type: FP32
          dims: -1
          dims: 32
        }
        lod_level: 1
      }
    }
    persistable: false
  }
  vars {
    name: "sequence_pool_0.tmp_1"
    type {
      type: LOD_TENSOR
      lod_tensor {
        tensor {
          data_type: FP32
        }
      }
    }
    persistable: false
  }
  vars {
    name: "moment_0"
    type {
      type: LOD_TENSOR
      lod_tensor {
        tensor {
          data_type: FP32
          dims: 5147
          dims: 32
        }
      }
    }
    persistable: true
  }
  vars {
    name: "cross_entropy_0.tmp_0"
    type {
      type: LOD_TENSOR
      lod_tensor {
        tensor {
          data_type: FP32
          dims: -1
          dims: 1
        }
        lod_level: 0
      }
    }
    persistable: false
  }
  vars {
    name: "sequence_conv_0.tmp_0@GRAD"
    type {
      type: LOD_TENSOR
      lod_tensor {
        tensor {
          data_type: FP32
          dims: -1
          dims: 32
        }
        lod_level: 1
      }
    }
  }
  vars {
    name: "sequence_pool_1.tmp_0"
    type {
      type: LOD_TENSOR
      lod_tensor {
        tensor {
          data_type: FP32
          dims: -1
          dims: 32
        }
      }
    }
    persistable: false
  }
  vars {
    name: "sequence_conv_0.tmp_1"
    type {
      type: LOD_TENSOR
      lod_tensor {
        tensor {
          data_type: FP32
          dims: -1
          dims: 32
        }
        lod_level: 1
      }
    }
    persistable: false
  }
  vars {
    name: "embedding_0.w_0.block0"
    type {
      type: LOD_TENSOR
      lod_tensor {
        tensor {
          data_type: FP32
          dims: 2574
          dims: 32
        }
      }
    }
    persistable: false
  }
  vars {
    name: "fc_0.tmp_4"
    type {
      type: LOD_TENSOR
      lod_tensor {
        tensor {
          data_type: FP32
          dims: -1
          dims: 2
        }
        lod_level: 0
      }
    }
    persistable: false
  }
  vars {
    name: "sequence_conv_1.b_0@GRAD.trainer_1"
    type {
      type: LOD_TENSOR
      lod_tensor {
        tensor {
          data_type: FP32
          dims: 32
        }
        lod_level: 0
      }
    }
  }
  vars {
    name: "W"
    type {
      type: LOD_TENSOR
    }
  }
  vars {
    name: "mean_0.tmp_0"
    type {
      type: LOD_TENSOR
      lod_tensor {
        tensor {
          data_type: FP32
          dims: 1
        }
      }
    }
    persistable: false
  }
  vars {
    name: "fc_0.tmp_0@GRAD"
    type {
      type: LOD_TENSOR
      lod_tensor {
        tensor {
          data_type: FP32
          dims: -1
          dims: 2
        }
        lod_level: 0
      }
    }
  }
  vars {
    name: "embedding_0.tmp_0@GRAD@RENAME@1"
    type {
      type: LOD_TENSOR
      lod_tensor {
        tensor {
          data_type: FP32
          dims: -1
          dims: 32
        }
        lod_level: 1
      }
    }
  }
  vars {
    name: "top_k_0.tmp_0"
    type {
      type: LOD_TENSOR
      lod_tensor {
        tensor {
          data_type: FP32
          dims: -1
          dims: 1
        }
        lod_level: 0
      }
    }
    persistable: false
  }
  vars {
    name: "embedding_0.tmp_0@GRAD@RENAME@0"
    type {
      type: LOD_TENSOR
      lod_tensor {
        tensor {
          data_type: FP32
          dims: -1
          dims: 32
        }
        lod_level: 1
      }
    }
  }
  vars {
    name: "sequence_conv_1.w_0"
    type {
      type: LOD_TENSOR
      lod_tensor {
        tensor {
          data_type: FP32
          dims: 128
          dims: 32
        }
      }
    }
    persistable: true
  }
  vars {
    name: "accuracy_0.tmp_0"
    type {
      type: LOD_TENSOR
      lod_tensor {
        tensor {
          data_type: FP32
          dims: 1
        }
        lod_level: 0
      }
    }
    persistable: false
  }
  vars {
    name: "fc_0.tmp_2@GRAD"
    type {
      type: LOD_TENSOR
      lod_tensor {
        tensor {
          data_type: FP32
          dims: -1
          dims: 2
        }
        lod_level: 0
      }
    }
  }
  vars {
    name: "fc_0.w_0@GRAD.trainer_1"
    type {
      type: LOD_TENSOR
      lod_tensor {
        tensor {
          data_type: FP32
          dims: 32
          dims: 2
        }
      }
    }
  }
  vars {
    name: "sequence_conv_1.b_0"
    type {
      type: LOD_TENSOR
      lod_tensor {
        tensor {
          data_type: FP32
          dims: 32
        }
      }
    }
    persistable: true
  }
  vars {
    name: "embedding_0.w_0"
    type {
      type: LOD_TENSOR
      lod_tensor {
        tensor {
          data_type: FP32
          dims: 5147
          dims: 32
        }
      }
    }
    persistable: true
  }
  vars {
    name: "sequence_conv_0.b_0"
    type {
      type: LOD_TENSOR
      lod_tensor {
        tensor {
          data_type: FP32
          dims: 32
        }
      }
    }
    persistable: true
  }
  vars {
    name: "accuracy_0.tmp_1"
    type {
      type: LOD_TENSOR
      lod_tensor {
        tensor {
          data_type: INT64
          dims: 1
        }
      }
    }
    persistable: false
  }
  vars {
    name: "embedding_0.w_0@GRAD"
    type {
      type: SELECTED_ROWS
      selected_rows {
        data_type: FP32
        dims: 5147
        dims: 32
      }
    }
  }
  vars {
    name: "accuracy_0.tmp_2"
    type {
      type: LOD_TENSOR
      lod_tensor {
        tensor {
          data_type: INT64
          dims: 1
        }
      }
    }
    persistable: false
  }
  vars {
    name: "cross_entropy_0.tmp_0@GRAD"
    type {
      type: LOD_TENSOR
      lod_tensor {
        tensor {
          data_type: FP32
          dims: -1
          dims: 1
        }
        lod_level: 0
      }
    }
  }
  vars {
    name: "fc_0.tmp_2"
    type {
      type: LOD_TENSOR
      lod_tensor {
        tensor {
          data_type: FP32
          dims: -1
          dims: 2
        }
        lod_level: 0
      }
    }
    persistable: false
  }
  vars {
    name: "__control_var@0.450809802685"
    type {
      type: LOD_TENSOR
    }
  }
  vars {
    name: "embedding_0.tmp_0"
    type {
      type: LOD_TENSOR
      lod_tensor {
        tensor {
          data_type: FP32
          dims: -1
          dims: 32
        }
        lod_level: 1
      }
    }
    persistable: false
  }
  vars {
    name: "sequence_conv_1.tmp_1@GRAD"
    type {
      type: LOD_TENSOR
      lod_tensor {
        tensor {
          data_type: FP32
          dims: -1
          dims: 32
        }
        lod_level: 1
      }
    }
  }
  vars {
    name: "fc_0.w_1"
    type {
      type: LOD_TENSOR
      lod_tensor {
        tensor {
          data_type: FP32
          dims: 32
          dims: 2
        }
      }
    }
    persistable: true
  }
  vars {
    name: "sequence_conv_1.tmp_0@GRAD"
    type {
      type: LOD_TENSOR
      lod_tensor {
        tensor {
          data_type: FP32
          dims: -1
          dims: 32
        }
        lod_level: 1
      }
    }
  }
  vars {
    name: "embedding_0.w_0.block1"
    type {
      type: LOD_TENSOR
      lod_tensor {
        tensor {
          data_type: FP32
          dims: 2573
          dims: 32
        }
      }
    }
    persistable: false
  }
  ops {
    inputs {
      parameter: "Ids"
      arguments: "words"
    }
    inputs {
      parameter: "W"
      arguments: "embedding_0.w_0"
    }
    outputs {
      parameter: "Out"
      arguments: "embedding_0.tmp_0"
    }
    type: "lookup_table"
    attrs {
      name: "op_role_var"
      type: STRINGS
    }
    attrs {
      name: "is_sparse"
      type: BOOLEAN
      b: true
    }
    attrs {
      name: "epmap"
      type: STRINGS
      strings: "10.73.182.42:62004"
```
