### ISSUE TITLE
paddlepaddle是否支持增量更新一个模型

### ISSUE THREAD

**Issue by xiuechen** [PaddlePaddle/Paddle#15954]
在一些场景中，比如类似推荐系统当中，我们往往需要用到最新的一些用户行为数据，这种时候就需要支持对模型进行增量训练和更新，那么这种情况能否支持。另外部署的时候，如何能支持这种流式更新的模型能快速部署到线上，谢谢

**Comment by seiriosPlus** [comment]
1. paddlepaddle支持增量更新<具体可以看文档>
2. paddlepaddle能够在增量更新的过程中产生新模型， 更新的模型能快速部署到线上我理解需要您所在的工程团队打通这条 模型 -> 部署上线的流程。
3. PaddlePaddle目前也在开发这种流式的全流程的框架，暂时还未公开。
