### ISSUE TITLE
paddle v2 训练报错：Check failed: binIdx <= kBinNum_ bin index [4294958922] out of range, predict value[-0.000499178]

### ISSUE THREAD

**Issue by lizhiqings** [PaddlePaddle/Paddle#15967]
F0228 10:11:26.789562 2317116224 Evaluator.cpp:460] Check failed: binIdx <= kBinNum_ bin index [4294958922] out of range, predict value[-0.000499178]
*** Check failure stack trace: ***
    @        0x116bf6b1f  google::LogMessageFatal::~LogMessageFatal()
    @        0x116bf3509  google::LogMessageFatal::~LogMessageFatal()
    @        0x116c1790b  paddle::AucEvaluator::evalImp()
    @        0x116c16a9a  paddle::Evaluator::eval()
    @        0x116c5f83c  paddle::CombinedEvaluator::eval()
    @        0x116bd0373  _wrap_GradientMachine_eval()
    @        0x10a136ebe  PyEval_EvalFrameEx
    @        0x10a13be82  fast_function
    @        0x10a136ab4  PyEval_EvalFrameEx
    @        0x10a12f5b2  PyEval_EvalCodeEx
    @        0x10a13bde5  fast_function
    @        0x10a136ab4  PyEval_EvalFrameEx
    @        0x10a12f5b2  PyEval_EvalCodeEx
    @        0x10a13bde5  fast_function
    @        0x10a136ab4  PyEval_EvalFrameEx
    @        0x10a12f5b2  PyEval_EvalCodeEx
    @        0x10a13bde5  fast_function
    @        0x10a136ab4  PyEval_EvalFrameEx
    @        0x10a13be82  fast_function
    @        0x10a136ab4  PyEval_EvalFrameEx
    @        0x10a12f5b2  PyEval_EvalCodeEx
    @        0x10a12efa6  PyEval_EvalCode
    @        0x10a15de24  PyRun_FileExFlags
    @        0x10a15d9a1  PyRun_SimpleFileExFlags
    @        0x10a1735e8  Py_Main

**Comment by guoshengCS** [comment]
报错对应这行代码 https://github.com/PaddlePaddle/Paddle/blob/release/1.2/paddle/legacy/gserver/evaluators/Evaluator.cpp#L460 ，是在AUC计算时，预测结果为负数`predict value[-0.000499178]`导致非负数的索引变量`unint32_t binIdx`值错误，超过了bin的大小，可以确认下预测结果是否为非负的概率值

**Comment by lizhiqings** [comment]
是说 这个输出值 必须为正数么，我用的是 square_error_cost 损失函数 ，应该对 输出值没有 限制吧

发件人: Guo Sheng <notifications@github.com>
答复: PaddlePaddle/Paddle <reply@reply.github.com>
日期: 2019年2月28日 星期四 上午10:48
收件人: PaddlePaddle/Paddle <Paddle@noreply.github.com>
抄送: "Li,Zhiqing" <lizhiqing@baidu.com>, Author <author@noreply.github.com>
主题: Re: [PaddlePaddle/Paddle] paddle v2 训练报错：Check failed: binIdx <= kBinNum_ bin index [4294958922] out of range, predict value[-0.000499178] (#15967)

负

**Comment by guoshengCS** [comment]
是要求输出值 必须为正数 的，一般只在分类时使用，要求非负的预测概率值

**Comment by lizhiqings** [comment]
哦 ，了解

发件人: Guo Sheng <notifications@github.com>
答复: PaddlePaddle/Paddle <reply@reply.github.com>
日期: 2019年2月28日 星期四 上午10:55
收件人: PaddlePaddle/Paddle <Paddle@noreply.github.com>
抄送: "Li,Zhiqing" <lizhiqing@baidu.com>, Author <author@noreply.github.com>
主题: Re: [PaddlePaddle/Paddle] paddle v2 训练报错：Check failed: binIdx <= kBinNum_ bin index [4294958922] out of range, predict value[-0.000499178] (#15967)

的

**Comment by guoshengCS** [comment]
先行close，如有需要还请reopen
