### ISSUE TITLE
paddle目前有带权采样的功能嘛

### ISSUE THREAD

**Issue by frankwhzhang** [PaddlePaddle/Paddle#15974]
类似于tf的 tf.nn.fixed_unigram_candidate_sampler

**Comment by guoshengCS** [comment]
可以看下这个 [sampling_id](http://paddlepaddle.org/documentation/docs/zh/1.3/api_cn/layers_cn.html#paddle.fluid.layers.sampling_id)是否满足需求 ，另外目前支持python写OP可以试下，如果是需要大规模分类的采样加速的话目前有[nce OP](https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/fluid/layers/nn.py#L5140) 和 [sampled_softmax_with_cross_entropy OP](https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/fluid/layers/nn.py#L5862)
