### ISSUE TITLE
请问Fluid 1.2 如何设置全局随机数种子， 实现模型稳定复现

### ISSUE THREAD

**Issue by aprilvkuo** [PaddlePaddle/Paddle#15975]
1）PaddlePaddle版本：Fluid 1.2 
    2）CPU：多线程

我目前是设置是这样，每个ephco跑出来结果是有diff的。

fluid.default_main_program().random_seed = 7
fluid.default_startup_program().random_seed = 7

￼

**Comment by guoshengCS** [comment]
需要在定义网络结构前设置下网络所用program的random_seed，可以参考这里 https://github.com/PaddlePaddle/models/blob/release/1.6/PaddleNLP/PaddleMT/transformer/train.py#L167  ，如果有用dropout的话需要再设置下dropout的seed

注意 program.random_seed 的设置要在网络定义开始前

**Comment by guoshengCS** [comment]
链接失效，更新如下： 
一方面需要在定义网络结构前设置下网络所用program的random_seed用于固定初始化中的随机性，可以参考这里  https://github.com/PaddlePaddle/models/blob/release/1.6/PaddleNLP/PaddleMT/transformer/train.py#L167 ；
另一方面网络中如用到存在随机性的OP，如dropout、sampling_id，可以再设置下相应的seed。
