### ISSUE TITLE
如何建立一个人脸识别模型？

### ISSUE THREAD

**Issue by yeyupiaoling** [PaddlePaddle/Paddle#15988]
我想通过使用深度学习模型建立一个人脸识别模型，但是我不是很了解人脸识别的流程，我大概猜想是这样子的：

首先训练目标检测模型，如SSD，来检测人脸的位置，用于之后的人脸提取。

然后再训练一个人脸分类的模型，如VGG，把每个人的人脸作为一个类别，然后使用VGG来训练一个分类模型

最后在结合这里两个模型组成一个人脸识别系统，通过使用人脸检测模型把一张人脸图片检测并裁剪出来，然后使用已经裁剪的人使用第二步训练得到的模型进行预测，但是分类模型输出的不是最后一层softmax的输出，而且其上一层的特征输出，再使用输出图像特征数据和之前同样方法输出的特征数据进行对角余弦值比较，判断它们的相似度。

我这样设想不知道对不对，就算正确，还是存在一个很大的问题，这个人脸识别模型需要分两个模型来完成。这是不是在实际应用下是行不通，比如一些深度学习框架一般只能加载一个模型，不能过同时加载两个模型，所以说这应该是合并成一个模型才可以的，那么该如何来合并这两个呢？

问题的知乎链接：[如何建立一个人脸识别模型？](https://www.zhihu.com/question/313838104)

**Comment by wanghaoshuang** [comment]
非常抱歉，无力详细的回答 ‘如何建立一个人脸识别模型？’， 但是可以建议您参考下paddle/models下的[face detection](https://github.com/PaddlePaddle/models/tree/develop/fluid/PaddleCV/face_detection)。

>我这样设想不知道对不对，就算正确，还是存在一个很大的问题，这个人脸识别模型需要分两个模型来完成。这是不是在实际应用下是行不通，比如一些深度学习框架一般只能加载一个模型，不能过同时加载两个模型，所以说这应该是合并成一个模型才可以的，那么该如何来合并这两个呢？

paddle是可以加载两个模型的，在OCR领域，也有把检测和识别放在一起训练的端到端训练。

**Comment by yeyupiaoling** [comment]
@wanghaoshuang 非常感谢您的回答，关于人脸检测，和人脸对比我都可以实现。
但是在真实场景中，是应该通过目标检测获取人脸，然后再对人脸进行对比，完成人脸识别。
这是两个过程，我需要一个过程完成它。

**Comment by yeyupiaoling** [comment]
@wanghaoshuang 在训练人脸对比模型的时候，已经对图片进行裁剪和人脸进行居中了，所以得到的预测模型，所需的预测图片也应该是经过裁剪，人脸居中的。
但是真实场景中一张图片不可能只有一个人脸，而且是居中的，所以这个时候就要对人脸进行检测，然后裁剪，对人脸进行居中该，最后再使用人脸对比模型完成人脸识别。
这个是两个过程。

**Comment by yeyupiaoling** [comment]
@wanghaoshuang 

>paddle是可以加载两个模型的，在OCR领域，也有把检测和识别放在一起训练的端到端训练。

官方提供的OCR项目中，已经去掉了检测部分了。https://github.com/PaddlePaddle/models/tree/develop/fluid/PaddleCV/ocr_recognition

**Comment by yeyupiaoling** [comment]
@wanghaoshuang 

>paddle是可以加载两个模型的

这个有例子吗？我感觉是直接输出结果，而不是分步使用模型识别。
比如使同时加载两个模型，在预测图片的时候直接输出两个模型的结果，而不是有第一个模型预测人脸位置，然后裁剪图片，然后再使用第二个模型预测。
