### ISSUE TITLE
paddle支持 tf.ones_like 这样的功能吗

### ISSUE THREAD

**Issue by frankwhzhang** [PaddlePaddle/Paddle#15984]
根据一个tensor的形状，生成形状大小相同的值为1或者0的tensor

**Comment by guoshengCS** [comment]
这个目前还没有，如果形状固定的话可以使用[fill_const](http://paddlepaddle.org/documentation/docs/zh/1.3/api_cn/layers_cn.html#paddle.fluid.layers.fill_constant)，如果只有batch_size一维变化的话可以使用[fill_const_batch_size_like](http://paddlepaddle.org/documentation/docs/zh/1.3/api_cn/layers_cn.html#paddle.fluid.layers.fill_constant_batch_size_like)，或者可以作为input给feed进来

**Comment by frankwhzhang** [comment]
好的 使用了
fill_const_batch_size_like 解决了这个问题，但是似乎需要补充一下这种op
