### ISSUE TITLE
单机多卡训练报错: Cannot find fetched variable

### ISSUE THREAD

**Issue by dubhex** [PaddlePaddle/Paddle#15989]
程序在单机单卡下能正常训练，但是在使用
`train_exe = fluid.ParallelExecutor(use_cuda = True, 
            loss_name = avg_cost.name, main_program = fluid.default_main_program())`

进行多卡训练时报下述错误

> File "run_train.py", line 199, in <module>
    main(args)
  File "run_train.py", line 140, in main
    feed = feeder.feed(data))
  File "/opt/python/cp27-cp27mu/lib/python2.7/site-packages/paddle/fluid/executor.py", line 472, in run
    self.executor.run(program.desc, scope, 0, True, True)
KeyboardInterrupt
[root@272c5daea05d face_align_150pts]# python run_train.py
Hi, Program begin
W0301 02:37:43.430696  1892 device_context.cc:213] Please NOTE: device: 0, CUDA Capability: 35, Driver Version: 9.0, Runtime Version: 8.0
W0301 02:37:43.430814  1892 device_context.cc:220] device: 0, cuDNN Version: 5.1.
Data reader is ready
Training begin
Traceback (most recent call last):
  File "run_train.py", line 199, in <module>
    main(args)
  File "run_train.py", line 140, in main
    feed = feeder.feed(data))
  File "/opt/python/cp27-cp27mu/lib/python2.7/site-packages/paddle/fluid/parallel_executor.py", line 287, in run
    self.executor.run(fetch_list, fetch_var_name)
paddle.fluid.core.EnforceNotMet: Cannot find fetched variable.(Perhaps the main_program is not set to ParallelExecutor) at [/paddle/paddle/fluid/framework/details/threaded_ssa_graph_executor.cc:166]
PaddlePaddle Call Stacks: 
0       0x7f20c96d5406p paddle::platform::EnforceNotMet::EnforceNotMet(std::__exception_ptr::exception_ptr, char const*, int) + 486
1       0x7f20caf4c658p paddle::framework::details::ThreadedSSAGraphExecutor::InsertFetchOps(std::vector<std::string, std::allocator<std::string> > const&, std::vector<paddle::framework::details::FetchOpHandle*, std::allocator<paddle::framework::details::FetchOpHandle*> >*, std::unordered_set<paddle::framework::details::VarHandleBase*, std::hash<paddle::framework::details::VarHandleBase*>, std::equal_to<paddle::framework::details::VarHandleBase*>, std::allocator<paddle::framework::details::VarHandleBase*> >*, std::unordered_map<paddle::framework::details::OpHandleBase*, unsigned long, std::hash<paddle::framework::details::OpHandleBase*>, std::equal_to<paddle::framework::details::OpHandleBase*>, std::allocator<std::pair<paddle::framework::details::OpHandleBase* const, unsigned long> > >*, std::unordered_set<paddle::framework::details::VarHandleBase*, std::hash<paddle::framework::details::VarHandleBase*>, std::equal_to<paddle::framework::details::VarHandleBase*>, std::allocator<paddle::framework::details::VarHandleBase*> >*, paddle::framework::BlockingQueue<paddle::framework::details::VarHandleBase*>*, std::vector<paddle::framework::LoDTensor, std::allocator<paddle::framework::LoDTensor> >*) + 3208
2       0x7f20caf4cdd8p paddle::framework::details::ThreadedSSAGraphExecutor::Run(std::vector<std::string, std::allocator<std::string> > const&) + 1768
3       0x7f20caf51707p paddle::framework::details::ScopeBufferedSSAGraphExecutor::Run(std::vector<std::string, std::allocator<std::string> > const&) + 391
4       0x7f20c97cebb9p paddle::framework::ParallelExecutor::Run(std::vector<std::string, std::allocator<std::string> > const&, std::string const&) + 489
5       0x7f20c96ca2dep
6       0x7f20c96fd78ep
7       0x7f210a90cce8p PyEval_EvalFrameEx + 28264
8       0x7f210a90f37dp PyEval_EvalCodeEx + 2061
9       0x7f210a90cd70p PyEval_EvalFrameEx + 28400
10      0x7f210a90ce9ep PyEval_EvalFrameEx + 28702
11      0x7f210a90f37dp PyEval_EvalCodeEx + 2061
12      0x7f210a90f4b2p PyEval_EvalCode + 50
13      0x7f210a9391c2p PyRun_FileExFlags + 146
14      0x7f210a93a559p PyRun_SimpleFileExFlags + 217
15      0x7f210a9501ddp Py_Main + 3149
16      0x7f2109be3d1dp __libc_start_main + 253
17            0x4006b1p

请问有什么方法解决？

**Comment by wanghaoshuang** [comment]
麻烦把exe.run()相关的代码也贴出来？

**Comment by wanghaoshuang** [comment]
构造ParallelExecutor的时候，会将主卡上的数据分发到其它卡上，可能某些variable没有被正确分发，需要更多代码确认下具体原因。

**Comment by XipengY** [comment]
@wanghaoshuang  我是这么写的exe.run  out_loss, feas, l = exe_train.run(fetch_list=[loss.name, out.name, label.name], feed=feeder.feed(data))
出现同样的错误，去掉label.name就好了。这个是什么问题呢？前面也在layer里面加了label这一层。

**Comment by wanghaoshuang** [comment]
可以尝试设置label.persistable=True

**Comment by XipengY** [comment]
@wanghaoshuang 您好，这个是在哪里设置呢？我在lable定义后紧接着就设置了，
label = fluid.layers.data(name='label', shape=[1], dtype='int64')
label.persistable=True
还是同样的错误。
paddle.fluid.core.EnforceNotMet: Cannot find fetched variable.

**Comment by wanghaoshuang** [comment]
```
 for batch_id, data in enumerate(train_reader()):
146             batch_start_time = time.time()
147 #            r1,r2,r3,r4,r5 = train_exe.run(
148 #                fetch_list = [lr.name, avg_cost.name, outputs.name, main_pts.name, M.name],
149 #                feed = feeder.feed(data))
150             r = train_exe.run(fetch_list = [lr.name],
151                 feed = feeder.feed(data))[0]
152
153             d = np.array(fluid.executor.global_scope().find_var(outputs.name).get_tensor())
154             print "name: %s; shape: %s" % (outputs.name, d.name)
155
156             d = np.array(fluid.executor.global_scope().find_var(lr.name).get_tensor())
157             print "d: %s" % d
158             d = np.array(fluid.executor.global_scope().find_var(main_pts.name).get_tensor()).shape
159             print "main_pts.name: %s" % (d,)
160             d = np.array(fluid.executor.global_scope().find_var(M.name).get_tensor())
161             print "M.name: %s" % d
162             d = np.array(fluid.executor.global_scope().find_var(avg_cost.name).get_tensor())
163             print "avg_cost: %s" % d
```

可以暂时通过这种方式获取要fetch的variable @XipengY

**Comment by chengduoZH** [comment]
@guo-hanqi 这所因为`main_pts`变量在模型中没有用到，所以计算图中没有该变量的信息。
