### ISSUE TITLE
官网fluid编程指南代码实例的疑问

### ISSUE THREAD

**Issue by DDDivano** [PaddlePaddle/Paddle#16001]
![image](https://user-images.githubusercontent.com/10734244/53628548-48e73500-3c46-11e9-92a6-9144d119c0a6.png)
这里我将`y_predict = fluid.layers.fc(input=x,size=1,act=None)`中的size改成2，4 。。。。也能正常跑结果
size改成2
![image](https://user-images.githubusercontent.com/10734244/53628700-b2ffda00-3c46-11e9-9d80-7f8f1d0ea028.png)

si'ze改成4
![image](https://user-images.githubusercontent.com/10734244/53628676-a67b8180-3c46-11e9-8af9-e3b1f7416993.png)

之后我将y的数据和对应的shape改成2 `y = fluid.layers.data(name="y",shape=[2],dtype='float32')`，指定size=2
结果
![image](https://user-images.githubusercontent.com/10734244/53628759-d9257a00-3c46-11e9-9bd6-24a7304be4d0.png)

size改成4
![image](https://user-images.githubusercontent.com/10734244/53628780-e93d5980-3c46-11e9-802f-8a6efbd9ad9c.png)
这个报错我能理解，但是之前不报错是怎么回事？

**Comment by wanghaoshuang** [comment]
>这里我将y_predict = fluid.layers.fc(input=x,size=1,act=None)中的size改成2，4 。。。。也能正常跑结果

square_error_cost由elementwise_sub op和square op组成，而elementwise_sub op会自动对input做broadcast操作，所以您的第一种情况没有报错。

**Comment by DDDivano** [comment]
> > 这里我将y_predict = fluid.layers.fc(input=x,size=1,act=None)中的size改成2，4 。。。。也能正常跑结果
> 
> square_error_cost由elementwise_sub op和square op组成，而elementwise_sub op会自动对input做broadcast操作，所以您的第一种情况没有报错。

明白了，多谢豪爽
