### ISSUE TITLE
enable providing gradient from user

### ISSUE THREAD

**Issue by lzhao4ever** [PaddlePaddle/Paddle#1600]
希望能够从任意一个layer做back propagation。layer.backward(gradient)，因为有时候python里面算gradient比较灵活方便，自己写个layer做cost太麻烦。 使用场景是unsupervised learning里面没有label来算cost以及gradient，gradient的计算python实现起来方便灵活。

**Comment by jacquesqiao** [comment]
从任意layer算gradient，fluid理论上是支持的，目前还没有暴露比较好的接口，但是不会实现在Python上。
