### ISSUE TITLE
关于Paddle.fluid的一个疑惑

### ISSUE THREAD

**Issue by Samhandsome** [PaddlePaddle/Paddle#16038]
在Paddle.fluid中的fluid.Program()的文档中，没有看的太明白，请问有相关的具体讲解或者实例分享一下嘛？谢谢

**Comment by yeyupiaoling** [comment]
@Samhandsome 这里倒是有一个应用案例：https://github.com/PaddlePaddle/models/blob/8c3d3801cd6490f72c59759b296a843635aa34dd/fluid/PaddleCV/object_detection/train.py#L146-L148

**Comment by Samhandsome** [comment]
@yeyupiaoling 谢谢

**Comment by jiayouff** [comment]
@yeyupiaoling 👍🏻

**Comment by shanyi15** [comment]
您好，请问具体不明白的地方是？我们可以优化一下API文档 @Samhandsome
