### ISSUE TITLE
Doc-reader部分写的几个typo还有一些建议

### ISSUE THREAD

**Issue by OleNet** [PaddlePaddle/Paddle#16031]
以下的建议都是关于这个[页面](http://paddlepaddle.org/documentation/docs/zh/1.3/user_guides/howto/prepare_data/reader_cn.html)的：

1. ...为什么需要一个batch raeder ... -> ...为什么需要一个batch **reader** ... 
2. 文档里面有一段代码：
``` 很容易将reader转换成batch reader：
mnist_train = paddle.dataset.mnist.train()
mnist_train_batch_reader = paddle.batch(mnist_train, 128)
```
这里的paddle.dataset.mnist.train() 出现的很突然，大概paddle.dataset.mnist.train()是一个reader的意思? 是否可以在出现这个函数的时候，解释一下这个函数想要代表的意义？

3. doc 可不可以考虑升级成ipynb组织的doc， 可以让人下载下来，很快的过一遍代码，更快的理解？

4. 另外还有一个不太确定的地方：《**使用**》这一节，确认是paddle.layer.data而不是fluid.layers.data对吧？

**Comment by shanyi15** [comment]
收到，感谢您的反馈，相关问题正在跟进

**Comment by shanyi15** [comment]
您好，针对您的问题，解答如下：
1. 问题1是笔误

2. mnist.train如问题说的，是返回一个reader。相关api说明，请参考：
http://paddlepaddle.org/documentation/docs/en/1.3/api/data/dataset.html#mnist
对应中文翻译即将新增

3. 技术上可行，已加入需求list

4. 这里的paddle都应该改成fluid

===
由于本文档近期未在维护，导致以上问题，感谢您反馈，我们将高优修复
文档问题欢迎您反馈至：https://github.com/PaddlePaddle/FluidDoc

**Comment by OleNet** [comment]
恩恩 辛苦辛苦
