### ISSUE TITLE
bert Fine-tuning 过程中loss存在不稳定

### ISSUE THREAD

**Issue by pkuzjq** [PaddlePaddle/Paddle#16040]
- 标题：bert Fine-tuning 过程中loss存在不稳定
- 版本、环境信息：
    1）PaddlePaddle版本：fluid1.2
    2）CPU：无
    3）GPU：26:00.0 VGA compatible controller [0300]: ASPEED Technology, Inc. ASPEED Graphics Family [1a03:2000] (rev 30) (prog-if 00 [VGA controller])
CUDA：CUDA Version 9.0.176
CUDNN：缺
    4）系统环境：Linux version 3.10.0_3-0-0-7 

- 训练信息
    1）单机，单卡
    2）显存信息
use_cuda: True
use_fast_executor: False
use_fp16: False
validation_steps: 100
verbose: False
vocab_path: chinese_L-12_H-768_A-12/vocab.txt
warmup_proportion: 0.1
weight_decay: 0.01
------------------------------------------------
attention_probs_dropout_prob: 0.1
directionality: bidi
hidden_act: gelu
hidden_dropout_prob: 0.1
hidden_size: 768
initializer_range: 0.02
intermediate_size: 3072
max_position_embeddings: 512
num_attention_heads: 12
num_hidden_layers: 12
pooler_fc_size: 768
pooler_num_attention_heads: 12
pooler_num_fc_layers: 3
pooler_size_per_head: 128
pooler_type: first_token_transform
type_vocab_size: 2
vocab_size: 21128
    3）Operator信息 
- 复现信息：
 diff log11 log11_1
< W0304 14:47:54.619240 16591 device_context.cc:203] Please NOTE: device: 0, CUDA Capability: 35, Driver Version: 9.2, Runtime Version: 8.0
< W0304 14:47:54.619304 16591 device_context.cc:210] device: 0, cuDNN Version: 5.0.
---
> W0304 14:50:13.588771 46163 device_context.cc:203] Please NOTE: device: 0, CUDA Capability: 35, Driver Version: 9.2, Runtime Version: 8.0
> W0304 14:50:13.588835 46163 device_context.cc:210] device: 0, cuDNN Version: 5.0.
56,57c56,57
< [nan] [128]
< epoch: 1, progress: 1000/1000, step: 10, ave loss: nan, ave acc: 0.210938, speed: 0.430254 steps/s
---
> [1.1014073] [128]
> epoch: 1, progress: 1000/1000, step: 10, ave loss: 1.101407, ave acc: 0.695312, speed: 0.432922 steps/s

- 问题描述：addle bert模型的使用在Fine-tuning 过程中使用小train集时，发现不稳定情况，loss 在正常和 nan之间随机转换。这个问题可以找哪位帮忙看下。两次完全一样的代码和环境，一次出现nan，一次不出现nan

**Comment by Superjomn** [comment]
辛苦帮看看哈 @kuke

**Comment by kuke** [comment]
是PaddlePaddle版本的问题，安装 1.3 之后解决
