### ISSUE TITLE
Should we expose paddle.batch

### ISSUE THREAD

**Issue by wangkuiyi** [PaddlePaddle/Paddle#1605]
`paddle.batch` in our new API is for grouping data instances into *mini-batches*, a concept in DL training.  More than that, not all training algorithms need minibatch.

Given that we provide `paddle.train` for high-level (highly abstracted) API, it seems that we shouldn't expose the concept minibatch.

However, it is exposed currently. I remember the reason is that we'd thought in a discussion that `paddle.infer` would also need mini-batches.   Now I doubt it.

In all our chapter example programs, e.g.,https://github.com/PaddlePaddle/book/blame/develop/machine_translation/README.en.md#L231, our new API requires users to call `paddle.batch` explicitly.  This seems an extra burden.

I'd propose:

1. Do not expose `paddle.batch`, but move it into the package of training as a private function.
1. `paddle.trainer.XXX.train` and `paddle.train` calls `paddle.batch` internally.
1. Expose a `paddle.reader.consume` function, which reads and returns some instances from a reader, e.g., `paddle.dataset.mnist.test()`, so to feed `paddle.infer`.

**Comment by wangkuiyi** [comment]
Few more cents:

In a previous discussion, @reyoung reminded that in some NLP applications, users need to be able to control minibatch sizes.  This led to the introduction of the concept *batched reader* in https://github.com/PaddlePaddle/Paddle/tree/develop/doc/design/reader#why-do-we-need-batch-reader-isnt-train-take-reader-and-batch_size-as-arguments-sufficient

But this seems a specific case that doesn't have to be covered by the high-level API `paddle.train`?

Should we make `paddle.trainer.SGD.train(...)` accepts a batched reader, but leave `paddle.train` to accept a reader?  In so, we would write 

```python
paddle.train(
    cost_layer,
    paddle.trainer.SGD(...), 
    paddle.dataset.mnist.train(), ...)
```

and the implementation of `paddle.train` calls:

```python
def train(cost_layer, trainer, reader, ...):
    trainer.train(
        cost_layer,
        paddle.trainer.batch(reader),
        ...)
```

**Comment by reyoung** [comment]
> Should we make `paddle.trainer.SGD.train(...)` accepts a batched reader, but leave paddle.train to accept a reader?

有道理。

**Comment by helinwang** [comment]
Before I thought the high level api `paddle.train` is just an alias to `paddle.trainer.SDG.train`. Seems it's a misunderstanding.

Could you please elaborate more on what is the role of `paddle.train`?

**Comment by Xreki** [comment]
It is related to the design of v2 api. Since v2 api has already been implemented, so closed.
