### ISSUE TITLE
模型重存储问题

### ISSUE THREAD

**Issue by jeanglewang** [PaddlePaddle/Paddle#16053]
有个训练好双塔模型，想infer的时候只有单支。我做的操作是先加载模型，然后只保存一支，得到新模型。但结果和双支有diff。  重存储代码如下
`program, feed_var_names, fetch_targets = fluid.io.load_inference_model(model_path, executor)
feed_var_names = [feed_var_names[0]]
fetch_targets = [fetch_targets[0]]
fluid.io.save_inference_model(new_model_path, feed_var_names, fetch_targets, executor, program)
`

查看case似乎是最后的relu层没起作用，所以我又做了如下操作
`
program, feed_var_names, fetch_targets = fluid.io.load_inference_model(model_path, executor)
feed_var_names = [feed_var_names[0]]
scale_out = fluid.layers.scale(x=fetch_targets[0], scale=1.0, bias=0.0, bias_after_scale=True)
fetch_targets = [scale_out]
fluid.io.save_inference_model(new_model_path, feed_var_names, fetch_targets, executor, program)
`

但scale语句报错，报错语句如下
`Traceback (most recent call last):
  File "infer_online.py", line 30, in <module>
    scale_out = fluid.layers.scale(x=fetch_targets[0], scale=1.0, bias=0.0, bias_after_scale=True)
  File "/home/wangjianguo/.jumbo/lib/python2.7/site-packages/paddle/fluid/layers/nn.py", line 8100, in scale
    'bias_after_scale': bias_after_scale
  File "/home/wangjianguo/.jumbo/lib/python2.7/site-packages/paddle/fluid/layer_helper.py", line 50, in append_op
    return self.main_program.current_block().append_op(*args, **kwargs)
  File "/home/wangjianguo/.jumbo/lib/python2.7/site-packages/paddle/fluid/framework.py", line 1207, in append_op
    op = Operator(block=self, desc=op_desc, *args, **kwargs)
  File "/home/wangjianguo/.jumbo/lib/python2.7/site-packages/paddle/fluid/framework.py", line 655, in __init__
    self.desc.infer_var_type(self.block.desc)
paddle.fluid.core.EnforceNotMet:  at [/home/wangjianguo/paddle/Paddle/paddle/fluid/operators/detail/safe_ref.h:28]
PaddlePaddle Call Stacks: 
0       0x7f120a7ec176p paddle::platform::EnforceNotMet::EnforceNotMet(std::__exception_ptr::exception_ptr, char const*, int) + 486
1       0x7f120a9307a3p paddle::operators::ScaleOpVarTypeInference::operator()(paddle::framework::OpDesc const&, paddle::framework::BlockDesc*) const + 435
2       0x7f120a9308a3p std::_Function_handler<void (paddle::framework::OpDesc const&, paddle::framework::BlockDesc*), paddle::framework::details::OpInfoFiller<paddle::operators::ScaleOpVarTypeInference, (paddle::framework::details::OpInfoFillType)3>::operator()(char const*, paddle::framework::OpInfo*) const::{lambda(paddle::framework::OpDesc const&, paddle::framework::BlockDesc*)#1}>::_M_invoke(std::_Any_data const&, paddle::framework::OpDesc const&, paddle::framework::BlockDesc*) + 35
3       0x7f120a89e1e2p paddle::framework::OpDesc::InferVarType(paddle::framework::BlockDesc*) const + 98
4       0x7f120a855363p
5       0x7f120a825f97p
6       0x7f123ae273e4p PyEval_EvalFrameEx + 25956
7       0x7f123ae28130p PyEval_EvalCodeEx + 2240
8       0x7f123adb427dp
9       0x7f123ad8c0f3p PyObject_Call + 83
10      0x7f123ad9ef7fp
11      0x7f123ad8c0f3p PyObject_Call + 83
12      0x7f123ade280ep
13      0x7f123ade1478p
14      0x7f123ad8c0f3p PyObject_Call + 83
15      0x7f123ae24de7p PyEval_EvalFrameEx + 16231
16      0x7f123ae28130p PyEval_EvalCodeEx + 2240
17      0x7f123adb427dp
18      0x7f123ad8c0f3p PyObject_Call + 83
19      0x7f123ae24de7p PyEval_EvalFrameEx + 16231
20      0x7f123ae28130p PyEval_EvalCodeEx + 2240
21      0x7f123ae264a1p PyEval_EvalFrameEx + 22049
22      0x7f123ae28130p PyEval_EvalCodeEx + 2240
23      0x7f123ae264a1p PyEval_EvalFrameEx + 22049
24      0x7f123ae28130p PyEval_EvalCodeEx + 2240
25      0x7f123ae28242p PyEval_EvalCode + 50
26      0x7f123ae4262cp
27      0x7f123ae42700p PyRun_FileExFlags + 144
28      0x7f123ae43c0cp PyRun_SimpleFileExFlags + 220
29      0x7f123ae554ccp Py_Main + 3164
30        0x318ae1ecddp __libc_start_main + 253
31            0x400669p
`

**Comment by seiriosPlus** [comment]
scale 的layer这么写呢？
```
scale = fluid.layers.scale(x=sim, scale=1.0)
```

**Comment by jeanglewang** [comment]
> scale 的layer这么写呢？
> 
> ```
> scale = fluid.layers.scale(x=sim, scale=1.0)
> ```

fluid.layers.scale(x=fetch_targets[0], scale=1.0, bias=0.0, bias_after_scale=True)
这样写的

**Comment by seiriosPlus** [comment]
把这行加到你网络里面
