### ISSUE TITLE
通过slurm提交训练任务报错

### ISSUE THREAD

**Issue by buffontus** [PaddlePaddle/Paddle#16055]
问题：
通过slurm提交训练任务报错，麻烦看下，谢谢！
W0305 03:02:28.340292  3825 init.cc:127] AVX is available, Please re-compile on local machine
Traceback (most recent call last):
  File "sentiment_classify.py", line 298, in <module>
    main(args) 
  File "sentiment_classify.py", line 267, in main
    args.num_passes)
  File "sentiment_classify.py", line 142, in train_net
    exe.run(fluid.default_startup_program())
  File "/home/slurm/job/tmp/job-84301/python/lib/python2.7/site-packages/paddle/fluid/executor.py", line 472, in run
    self.executor.run(program.desc, scope, 0, True, True)
paddle.fluid.core.EnforceNotMet: Cannot run operator on place CUDAPlace(0) at [/paddle/paddle/fluid/framework/operator.cc:145]
PaddlePaddle Call Stacks: 
0       0x7fcf71344ed2p paddle::platform::EnforceNotMet::EnforceNotMet(std::__exception_ptr::exception_ptr, char const*, int) + 482
1       0x7fcf720aff94p paddle::framework::OperatorBase::Run(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&) + 644
2       0x7fcf71408e9ap paddle::framework::Executor::RunPreparedContext(paddle::framework::ExecutorPrepareContext*, paddle::framework::Scope*, bool, bool, bool) + 234
3       0x7fcf71409525p paddle::framework::Executor::Run(paddle::framework::ProgramDesc const&, paddle::framework::Scope*, int, bool, bool) + 117
4       0x7fcf71334fe2p
5       0x7fcf7137b4f5p
6       0x7fcfc7c14bb8p PyEval_EvalFrameEx + 25016
7       0x7fcfc7c180bdp PyEval_EvalCodeEx + 2061
8       0x7fcfc7c15345p PyEval_EvalFrameEx + 26949
9       0x7fcfc7c180bdp PyEval_EvalCodeEx + 2061
10      0x7fcfc7c15345p PyEval_EvalFrameEx + 26949
11      0x7fcfc7c15460p PyEval_EvalFrameEx + 27232
12      0x7fcfc7c180bdp PyEval_EvalCodeEx + 2061
13      0x7fcfc7c181f2p PyEval_EvalCode + 50
14      0x7fcfc7c40f42p PyRun_FileExFlags + 146
15      0x7fcfc7c422d9p PyRun_SimpleFileExFlags + 217
16      0x7fcfc7c5800dp Py_Main + 3149
17      0x7fcfc6e55bd5p __libc_start_main + 245
18            0x4007a1p

**Comment by gongweibao** [comment]
编译的时候需要用WITH_GPU=ON
或者使用带了GPU功能的whl包
`pip install paddlepaddle-gpu`
