### ISSUE TITLE
分布式图像分类时ps报如下错误

### ISSUE THREAD

**Issue by kolinwei** [PaddlePaddle/Paddle#16075]
get_pserver_program() is deprecated, call get_pserver_programs() to get pserver main and startup in a single call.
I0306 11:30:49.197628  1910 grpc_server.cc:430] Server listening on 10.255.106.25:30016 selected port: 30016
F0306 11:32:40.549396  2578 listen_and_serv_op.cc:74] run sub program:96 error Enforce failed. Expected in_dim == x_dim, but received in_dim:256, 1024, 1, 1 != x_dim:1024, 256, 1, 1.
Input tensors must have same shape at [/workspace/paddle/fluid/operators/sum_op.cc:67]
PaddlePaddle Call Stacks: 
0       0x7fd92eb6ebeap void paddle::platform::EnforceNotMet::Init<std::string>(std::string, char const*, int) + 362
1       0x7fd92eb6ef42p paddle::platform::EnforceNotMet::EnforceNotMet(std::string const&, char const*, int) + 82
2       0x7fd92f6239e7p paddle::operators::SumOp::InferShape(paddle::framework::InferShapeContext*) const + 1303
3       0x7fd93046afb2p paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&) const + 658
4       0x7fd93046942cp paddle::framework::OperatorBase::Run(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&) + 300
5       0x7fd92ec84706p paddle::framework::Executor::RunPreparedContext(paddle::framework::ExecutorPrepareContext*, paddle::framework::Scope*, bool, bool, bool) + 246
6       0x7fd92f6d9202p
7       0x7fd92f6dfd87p std::_Function_handler<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> ()(), std::__future_base::_Task_setter<std::unique_ptr<std::__future_base::_Result<std::unique_ptr<paddle::platform::EnforceNotMet, std::default_delete<paddle::platform::EnforceNotMet> > >, std::__future_base::_Result_base::_Deleter>, std::unique_ptr<paddle::platform::EnforceNotMet, std::default_delete<paddle::platform::EnforceNotMet> > > >::_M_invoke(std::_Any_data const&) + 39
8       0x7fd92f69a5e4p std::__future_base::_State_base::_M_do_set(std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> ()()>&, bool&) + 36
9       0x7fd996fdab23p pthread_once + 83
10      0x7fd92f6d8384p
11      0x7fd9304c1139p paddle::framework::ThreadPool::TaskLoop() + 1609
12      0x7fd98c29d470p
13      0x7fd996fd5851p
14      0x7fd99669890dp clone + 109

**Comment by typhoonzero** [comment]
经过复现，目前现象总结如下：

- 使用Ubuntu16.04 base image编译(gcc 4.8)，开启`-O3`，运行以上case可以复现
- 使用Ubuntu16.04 base image编译(gcc 4.8)，开启`-O2`，可以复现
- 使用Ubuntu16.04 base image编译(gcc 4.8)，开启`-O2`，在ubuntu16.04运行时镜像执行，可以复现
- 使用CentOS6编译(gcc 4.8)，开启`-O3`，无法复现

**Comment by typhoonzero** [comment]
目前可以确定是集群硬件环境的问题，下掉一台故障机器后，目前无法复现此问题，暂时关闭。
