### ISSUE TITLE
py_reader能在训练减少多少时间？

### ISSUE THREAD

**Issue by yeyupiaoling** [PaddlePaddle/Paddle#16079]
# 环境
 - PaddlePaddle 1.3 GPU
 - Ubuntu 16.04 64位
 - Python 3.5

 # 问题
[paddle.fluid.layers.py_reader](http://paddlepaddle.org/documentation/docs/zh/1.3/api_cn/layers_cn.html#py-reader)数据读取接口能加快训练整体时间的多少，因为使用了这个代码结构变得复杂很多，我想问使用`py_reader`是否值得？

**Comment by yeyupiaoling** [comment]
我发现我在跑目标检测的时候:https://github.com/PaddlePaddle/models/tree/develop/fluid/PaddleCV/object_detection
使用`paddle.fluid.layers.py_reader`速度反而会更慢

使用的数据是：pascalvoc
1. ` for batch_id, data in enumerate(train_reader()):`一个Pass时间为：534.448076 s
2. `paddle.fluid.layers.py_reader`一个Pass时间为：597.962765 s

**Comment by velconia** [comment]
PyReader的核心功能是**异步数据读取**，目的是将读取数据的IO时间和训练的CPU时间重叠起来，加速训练；

但如果数据读取的速度较慢，训练速度较快，会导致训练一直在等待数据读取，性能不会提升；
针对GPU模型，需要设置double_buffer=True来提升性能；

@sneaxiy 是这方面专家，欢迎补充更多观点

**Comment by yeyupiaoling** [comment]
@velconia 理论上是PyReader更快一些吧，但是实际并非如此哦。

**Comment by sneaxiy** [comment]
你是CPU训练还是GPU训练？

**Comment by yeyupiaoling** [comment]
我使用的是GPU呢、

**Comment by velconia** [comment]
double_buffer 设置了吗？ 另外使用非 py_reader 的代码部分方便贴下吗？

**Comment by yeyupiaoling** [comment]
@velconia 设置了
```python
 py_reader = fluid.layers.py_reader(
            capacity=64,
            shapes=[[-1] + image_shape, [-1, 4], [-1, 1]],
            lod_levels=[0, 1, 1],
            dtypes=["float32", "float32", "int32"],
            use_double_buffer=True)
```

**Comment by imistyrain** [comment]
paddlepaddle设计时错误的把batch_size当成反传的基本单位，必须等所有数据都到齐后才进行一个批次的训练，GPU大部分浪费在等数据上了.

**Comment by yeyupiaoling** [comment]
@imistyrain 那就是说是PaddlePaddle本身的Bug咯？

**Comment by sneaxiy** [comment]
@yeyupiaoling 您是几个GPU卡训练？

**Comment by yeyupiaoling** [comment]
@sneaxiy  一个GPU呢。

**Comment by yeyupiaoling** [comment]
@velconia 建议出个性能对照表，对照Python Reader和Py_reader的性能。
