### ISSUE TITLE
Feature Request: Sequence Pooling with Stride

### ISSUE THREAD

**Issue by lcy-seso** [PaddlePaddle/Paddle#1608]
Problem:

- Currently, sequence [Pooling](http://www.paddlepaddle.org/doc/ui/api/trainer_config_helpers/poolings.html) in PaddlePaddle is performed sequence-wise. After pooling, a sequence is transformed into a non-sequence.
- This is not enough  in building a deep one-dimensional convolution model, such as models for NLP or speech tasks, in which pooling layer may be followed by a new convolution layer. 
- According to current design, such a model is impossible, because output of pooling is no longer a sequence, that cannot be input to a new convolution layer.

**It will be helpful if the sequence Pooling layer provides a stride parameter, which controls  the scope of pooling operation**. 

It may work like this:
- If stride is set -1, it equals to sequence-wise pooling as it does now, otherwise, pooling is performed upon a small local area.
- After pooling with stride n (n is smaller than sequence length), a long sequence will be shorten.

**Comment by luotao1** [comment]
和 @lcy-seso 讨论后，目前会优先支持AverageLayer、MaxLayer和SequenceLastInstanceLayer，这三个单层的功能。
