### ISSUE TITLE
make show assert error

### ISSUE THREAD

**Issue by yizhiheying** [PaddlePaddle/Paddle#16081]
[100%] Built target warpctc
Install the project...
-- Install configuration: "Release"
-- Installing: /home/eason/main/source/ai/alg/Paddle/Paddle/build/third_party/install/warpctc/lib/libwarpctc.so
-- Installing: /home/eason/main/source/ai/alg/Paddle/Paddle/build/third_party/install/warpctc/include/ctc.h
[  5%] Completed 'extern_warpctc'
[  5%] Built target extern_warpctc
Scanning dependencies of target extern_gzstream
[  5%] Creating directories for 'extern_gzstream'
[  5%] Performing download step (git clone) for 'extern_gzstream'
Cloning into 'extern_gzstream'...
Already on 'master'
Your branch is up to date with 'origin/master'.
[  5%] No patch step for 'extern_gzstream'
[  5%] No update step for 'extern_gzstream'
[  5%] No configure step for 'extern_gzstream'
[  5%] Performing build step for 'extern_gzstream'
CPPFLAGS: "-I/home/eason/main/source/ai/alg/Paddle/Paddle/build/third_party/install/zlib/include" -I. -fPIC -O
LDFLAGS: "-L/home/eason/main/source/ai/alg/Paddle/Paddle/build/third_party/install/zlib/lib" -L. -lgzstream -lz
[  5%] Performing install step for 'extern_gzstream'
[  5%] Completed 'extern_gzstream'
[  5%] Built target extern_gzstream
Scanning dependencies of target place
[  5%] Building CXX object paddle/fluid/platform/CMakeFiles/place.dir/place.cc.o
In file included from /home/eason/main/source/ai/alg/Paddle/Paddle/build/third_party/boost/src/extern_boost/boost/mpl/aux_/na_assert.hpp:23,
                 from /home/eason/main/source/ai/alg/Paddle/Paddle/build/third_party/boost/src/extern_boost/boost/mpl/arg.hpp:25,
                 from /home/eason/main/source/ai/alg/Paddle/Paddle/build/third_party/boost/src/extern_boost/boost/variant/variant_fwd.hpp:19,
                 from /home/eason/main/source/ai/alg/Paddle/Paddle/build/third_party/boost/src/extern_boost/boost/variant/variant.hpp:27,
                 from /home/eason/main/source/ai/alg/Paddle/Paddle/build/third_party/boost/src/extern_boost/boost/variant.hpp:17,
                 from /home/eason/main/source/ai/alg/Paddle/Paddle/paddle/fluid/platform/variant.h:45,
                 from /home/eason/main/source/ai/alg/Paddle/Paddle/paddle/fluid/platform/place.h:21,
                 from /home/eason/main/source/ai/alg/Paddle/Paddle/paddle/fluid/platform/place.cc:15:
/home/eason/main/source/ai/alg/Paddle/Paddle/build/third_party/boost/src/extern_boost/boost/mpl/assert.hpp:154:21: error: unnecessary parentheses in declaration of ‘assert_arg’ [-Werror=parentheses]
 failed ************ (Pred::************
                     ^
/home/eason/main/source/ai/alg/Paddle/Paddle/build/third_party/boost/src/extern_boost/boost/mpl/assert.hpp:159:21: error: unnecessary parentheses in declaration of ‘assert_not_arg’ [-Werror=parentheses]
 failed ************ (boost::mpl::not_<Pred>::************
                     ^
cc1plus: all warnings being treated as errors
make[2]: *** [paddle/fluid/platform/CMakeFiles/place.dir/build.make:63: paddle/fluid/platform/CMakeFiles/place.dir/place.cc.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:2670: paddle/fluid/platform/CMakeFiles/place.dir/all] Error 2
make: *** [Makefile:152: all] Error 2

Python: python3.6 
linux: ubuntu18.10
paddlepaddle: cpu

just refer to http://paddlepaddle.org/documentation/docs/zh/1.3/beginners_guide/install/compile/compile_Ubuntu.html/#ubt_source 
when run make cmd,show above error msg.
anyone can help?

**Comment by JiabinYang** [comment]
what is your gcc version, this error is looks like #16083
