### ISSUE TITLE
ubuntu18.10 cpu版本python3.6编译错误

### ISSUE THREAD

**Issue by yizhiheying** [PaddlePaddle/Paddle#16083]
- 版本、环境信息：
    1）PaddlePaddle版本：github develop版本
    2）CPU：vmware14
    3）GPU：非gpu
    4）系统环境：ubuntu18.10 64位 python3.6 
- 安装方式信息：

本地编译：http://paddlepaddle.org/documentation/docs/zh/1.3/beginners_guide/install/compile/compile_Ubuntu.html/#ubt_source 中本机编译第十步make 命令

错误信息如下：

[100%] Built target warpctc
Install the project...
-- Install configuration: "Release"
-- Installing: /home/eason/main/source/ai/alg/Paddle/Paddle/build/third_party/install/warpctc/lib/libwarpctc.so
-- Installing: /home/eason/main/source/ai/alg/Paddle/Paddle/build/third_party/install/warpctc/include/ctc.h
[  5%] Completed 'extern_warpctc'
[  5%] Built target extern_warpctc
Scanning dependencies of target extern_gzstream
[  5%] Creating directories for 'extern_gzstream'
[  5%] Performing download step (git clone) for 'extern_gzstream'
Cloning into 'extern_gzstream'...
Already on 'master'
Your branch is up to date with 'origin/master'.
[  5%] No patch step for 'extern_gzstream'
[  5%] No update step for 'extern_gzstream'
[  5%] No configure step for 'extern_gzstream'
[  5%] Performing build step for 'extern_gzstream'
CPPFLAGS: "-I/home/eason/main/source/ai/alg/Paddle/Paddle/build/third_party/install/zlib/include" -I. -fPIC -O
LDFLAGS: "-L/home/eason/main/source/ai/alg/Paddle/Paddle/build/third_party/install/zlib/lib" -L. -lgzstream -lz
[  5%] Performing install step for 'extern_gzstream'
[  5%] Completed 'extern_gzstream'
[  5%] Built target extern_gzstream
Scanning dependencies of target place
[  5%] Building CXX object paddle/fluid/platform/CMakeFiles/place.dir/place.cc.o
In file included from /home/eason/main/source/ai/alg/Paddle/Paddle/build/third_party/boost/src/extern_boost/boost/mpl/aux_/na_assert.hpp:23,
                 from /home/eason/main/source/ai/alg/Paddle/Paddle/build/third_party/boost/src/extern_boost/boost/mpl/arg.hpp:25,
                 from /home/eason/main/source/ai/alg/Paddle/Paddle/build/third_party/boost/src/extern_boost/boost/variant/variant_fwd.hpp:19,
                 from /home/eason/main/source/ai/alg/Paddle/Paddle/build/third_party/boost/src/extern_boost/boost/variant/variant.hpp:27,
                 from /home/eason/main/source/ai/alg/Paddle/Paddle/build/third_party/boost/src/extern_boost/boost/variant.hpp:17,
                 from /home/eason/main/source/ai/alg/Paddle/Paddle/paddle/fluid/platform/variant.h:45,
                 from /home/eason/main/source/ai/alg/Paddle/Paddle/paddle/fluid/platform/place.h:21,
                 from /home/eason/main/source/ai/alg/Paddle/Paddle/paddle/fluid/platform/place.cc:15:
/home/eason/main/source/ai/alg/Paddle/Paddle/build/third_party/boost/src/extern_boost/boost/mpl/assert.hpp:154:21: error: unnecessary parentheses in declaration of ‘assert_arg’ [-Werror=parentheses]
 failed ************ (Pred::************
                     ^
/home/eason/main/source/ai/alg/Paddle/Paddle/build/third_party/boost/src/extern_boost/boost/mpl/assert.hpp:159:21: error: unnecessary parentheses in declaration of ‘assert_not_arg’ [-Werror=parentheses]
 failed ************ (boost::mpl::not_<Pred>::************
                     ^
cc1plus: all warnings being treated as errors
make[2]: *** [paddle/fluid/platform/CMakeFiles/place.dir/build.make:63: paddle/fluid/platform/CMakeFiles/place.dir/place.cc.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:2670: paddle/fluid/platform/CMakeFiles/place.dir/all] Error 2
make: *** [Makefile:152: all] Error 2

**Comment by JiabinYang** [comment]
请问下您的gcc版本和cmake版本是多少呢

**Comment by yizhiheying** [comment]
gcc version 8.2.0 
cmake version 3.12.1

**Comment by yizhiheying** [comment]
PaddlePaddle V1.3.0

**Comment by JiabinYang** [comment]
> gcc version 8.2.0
> cmake version 3.12.1

请使用gcc 5.4或gcc 4.8，这个问题是boost库在gcc 8下的一个[问题](https://github.com/CauldronDevelopmentLLC/cbang/issues/26)导致的
