### ISSUE TITLE
elementwise_pow的GradOp没注册以及没有mod操作

### ISSUE THREAD

**Issue by superwj1990** [PaddlePaddle/Paddle#16097]
elementwise_pow这个Op没有实现反向
paddle.fluid.core.EnforceNotMet: grad_op_maker_ should not be null
Operator GradOpMaker has not been registered. at [/paddle/paddle/fluid/framework/op_info.h:61]

**Comment by velconia** [comment]
已Assign给对应同学修复

**Comment by gongweibao** [comment]
收到
跟随1.4发布吧。

**Comment by YingjingLu** [comment]
请问这个问题解决了吗，我在Paddle 1.5 Ubuntu Cuda 9 CUDNN 7.3上面依然有这个问题
