### ISSUE TITLE
activation with cudnn cause NaN in Faster RCNN

### ISSUE THREAD

**Issue by jerrywgz** [PaddlePaddle/Paddle#16096]
CUDA8，cudnn7，P40
https://github.com/PaddlePaddle/Paddle/pull/15164 会导致models(develop)中faster rcnn在训练至11个iter左右的时候出NaN
尝试注释activation_op.cc中的部分代码，如下图红圈内所示，重新训练即正常
![image](https://user-images.githubusercontent.com/22989727/53928889-ce476b00-40c6-11e9-9a18-de848ad8469e.png)
能否在api端添加是否使用cudnn的选项，或者有其他更加合理的处理方式

**Comment by velconia** [comment]
可能是 cudnn7 有某个参数改变导致的问题，这个在 BN 里也遇到了
