### ISSUE TITLE
尝试将fit.a.line改用py_reader出错

### ISSUE THREAD

**Issue by gogogo45** [PaddlePaddle/Paddle#16094]
学习py_reader的用法，尝试将example中的fit.a.line改为py_reader模式，报以下错误
![image](https://user-images.githubusercontent.com/4569437/53895221-7da32400-406c-11e9-8c2e-e536423af803.png)

代码的修改处如下：
![image](https://user-images.githubusercontent.com/4569437/53895291-adeac280-406c-11e9-8060-f6b220ef000e.png)

请帮忙指出问题，谢谢

[train.py.zip](https://github.com/PaddlePaddle/Paddle/files/2939558/train.py.zip)

**Comment by velconia** [comment]
方便提供下Paddle的版本吗？

**Comment by velconia** [comment]
你注释掉的这个写法应该才是对的，这是 1.3 版本的写法示例：
http://paddlepaddle.org/documentation/docs/zh/1.3/user_guides/howto/prepare_data/use_py_reader.html

**Comment by gogogo45** [comment]
> 你注释掉的这个写法应该才是对的，这是 1.3 版本的写法示例：
> http://paddlepaddle.org/documentation/docs/zh/1.3/user_guides/howto/prepare_data/use_py_reader.html

注释掉的写法也试过，同样的异常。

**Comment by gogogo45** [comment]
> 方便提供下Paddle的版本吗？

现在使用的是1.2.0

**Comment by velconia** [comment]
总结一下，网络有两处问题：
1. PyReader的open_file会得到x_val和y_val, 这两个值相当于原来的 fluid.layers.data()，所以应该传入 fluid.layers.fc 和 square_error_cost;
2. Test依旧可以使用DataFeeder的形式进行；所以如果eval_exe不准备使用py_reader, 也可以不注释掉
