### ISSUE TITLE
gru4rec 预测部署

### ISSUE THREAD

**Issue by lingdu0001** [PaddlePaddle/Paddle#16103]
我看了gru4rec的代码，但是infer.py里面只有计算召回率的方法。
但是我要真实预测应该如何向某个用户推荐哪些商品的话应该如何写呢？请问方便提供demo么？
谢谢！
需要输入的数据是什么呢？fetch_list部分应该如何写呢？

**Comment by velconia** [comment]
辛苦模型负责人 @frankwhzhang 老师解答下~

**Comment by frankwhzhang** [comment]
有两种方案：
1. 在训练的网络中添加topk op, k=1,可以返回最高的indice(具体参考topk 做法)，需要在train.py中的fetch_list中添加对应返回的值，类似acc. 然后再infer.py 取回来后通过np.array(topk_value),就可以取到对应的下标
2. 参考infer_sample_neg.py 中的做法，训练阶段只保存参数(save_params这个方式保存)，预测阶段重新构建网络，直接在预测网络中添加topk op

**Comment by velconia** [comment]
@lingdu0001 请问还有别的问题吗？

**Comment by lingdu0001** [comment]
我试试哈 谢谢！
