### ISSUE TITLE
Windows环境模型预测 (c++)教程无法走通  生成失败

### ISSUE THREAD

**Issue by benjaminxz** [PaddlePaddle/Paddle#16102]
PaddlePaddle版本为1.3  win10 cpu
在走Windows环境模型预测这个教程的时候遇到了错误，在vs2015中生成解决方案失败，错误信息为：

1>------ 已启动生成: 项目: simple_on_word2vec, 配置: Release x64 ------
1>  simple_on_word2vec.cc
1>C:\Paddle-develop\fluid_inference\third_party\install\gflags\include\gflags/gflags.h(288): error C2065: “unused”: 未声明的标识符
1>C:\Paddle-develop\fluid_inference\third_party\install\glog\include\glog/logging.h(47): fatal error C1083: 无法打开包括文件: “unistd.h”: No such file or directory
========== 生成: 成功 0 个，失败 1 个，最新 1 个，跳过 0 个 ==========

预测库(1.3版本) 来自官网下载的 cpu_avx_mkl 版本

实践上与官网唯一有改动的地方在cmake命令上
cmake .. -G "Visual Studio 14 2015 Win64" -DWITH_GPU=OFF -DWITH_MKL=OFF -DWITH_STATIC_LIB=ON -DCMAKE_BUILD_TYPE=Release -DDEMO_NAME=simple_on_word2vec -DPADDLE_LIB=C:\Paddle-develop\fluid_inference
最后的路径指向了解压后的预测库根目录。

我之前未接触过c++，自己找了很多办法均未奏效，请指教一下如何走通这个教程。

**Comment by velconia** [comment]
请问方便提供下教程的链接吗？

**Comment by benjaminxz** [comment]
@velconia  好的  其实也就是官方最新版本的文档
http://paddlepaddle.org/documentation/docs/zh/1.3/advanced_usage/deploy/inference/build_and_install_lib_cn.html
http://paddlepaddle.org/documentation/docs/zh/1.3/advanced_usage/deploy/inference/windows_cpp_inference.html

**Comment by velconia** [comment]
好的，我们本地复现后答复您哈

**Comment by wopeizl** [comment]
看起来是你的glog库有问题，请问你的glog编译是通过paddle做的还是直接拷贝过来的？

**Comment by benjaminxz** [comment]
@wopeizl 你好，库文件是直接拷贝过来的
文件来自于http://paddlepaddle.org/documentation/docs/zh/1.3/advanced_usage/deploy/inference/build_and_install_lib_cn.html
中的第一个下载链接，下载下来的文件是fluid_inference.tgz 

上面遇到的2个错误
1>C:\Paddle-develop\fluid_inference\third_party\install\gflags\include\gflags/gflags.h(288): error C2065: “unused”: 未声明的标识符
1>C:\Paddle-develop\fluid_inference\third_party\install\glog\include\glog/logging.h(47): fatal error C1083: 无法打开包括文件: “unistd.h”: No such file or directory

经过你的提示 ，刚才我在github找glog到源码并编译，添加到项目中后这2个错误没有再提示了，不过又遇到了很多新的错误。

在(编译simple_on_word2vec项目) 试图修复这个编译错误的时候发现  vs会提示
 无法打开文件“libglog.lib”  无法打开文件“***.lib”  这种错误
而fluid_inference.tgz 这个压缩包内 的静态库 有很多是 .a 文件类型

以下是我的猜测，
http://paddlepaddle.org/documentation/docs/zh/1.3/advanced_usage/deploy/inference/windows_cpp_inference.html
页面中的  Paddle/paddle/fluid/inference/api/demo_ci   项目是不是还没有来得及更新呢

另外页面中第一步中的
”解压Paddle，Release，fluid_install_dir压缩包。“
3个压缩包在哪里呢 ，我在github和官网上找了很久……

**Comment by wopeizl** [comment]
官网上的inference包默认是linux下的，所以win下的需要自己去编译，依照这个文档，http://paddlepaddle.org/documentation/docs/zh/1.3/beginners_guide/install/compile/compile_Windows.html 编译， 完成后在build的目录下就有fluid_inference_install_dir目录

**Comment by benjaminxz** [comment]
@wopeizl 好的，谢谢，我这几天去试一试

**Comment by benjaminxz** [comment]
http://paddlepaddle.org/documentation/docs/zh/1.3/beginners_guide/install/compile/compile_Windows.html
这几天我一直在尝试，但是这个教程在我的电脑上并不能全部编译通过，编译环境是一台还原系统后的win10 x64  ，python3.5  cmake-3.14.0-win64-x64  vs2015 update3
步骤严格按照网站上的执行，执行cmake这一步选择了For Python3: cpu版本
执行完第7步，结果几小时的编译后，vs显示  生成有10多个失败  3个跳过 其他成功 

Release，fluid_install_dir 文件夹中 并没有相应的lib文件。

**Comment by wopeizl** [comment]
paddle编译失败了吗？先编译third_party，后编译的paddle？把错误提示麻烦发一下
