### ISSUE TITLE
fluid.layers 官方文档有一些小问题

### ISSUE THREAD

**Issue by OliverLPH** [PaddlePaddle/Paddle#16119]
发现了官方文档有一些小问题

[fluid.layers的使用说明](http://paddlepaddle.org/documentation/docs/zh/1.3/api_cn/layers_cn.html#cn-api-fluid-layers-array-read) 里面的 array_read和array_write两个板块。

![42697fb8c58287d075ab20ecce9bb01b](https://user-images.githubusercontent.com/14963836/54016487-1c8b6580-41be-11e9-8423-a3467d75fe2f.png)
应该是 
```python
arr = fluid.layers.array_read(tmp,i=i)
```

![25cfdb18215c164a1121653db09f226d](https://user-images.githubusercontent.com/14963836/54016621-7a1fb200-41be-11e9-8354-e76f224c217a.png)
```python
arr = fluid.layers.array_write(tmp, i=i)
```

**Comment by shanyi15** [comment]
hi，您好，非常感谢您的反馈，我们将尽快更新
