### ISSUE TITLE
内部用户， Floating point exception when trainning with GPU

### ISSUE THREAD

**Issue by fsfszongming256** [PaddlePaddle/Paddle#1611]
日志：:
I0313 19:00:05.295281  8472 Stat.cpp:140] ======= BarrierStatSet status ======
I0313 19:00:05.295287  8472 Stat.cpp:153] --------------------------------------------------
Thread [139773011044416] Backwarding __lstm_1__, lstm_transform___lstm_1__, __embedding_1__, __seq_pooling_0__, __lstm_0__, lstm_trans
form___lstm_0__, __embedding_0__, t_word, q_word, 
*** Aborted at 1489402805 (unix time) try "date -d @1489402805" if you are using GNU date ***
PC: @           0x7b3859 paddle::GpuVectorT<>::getAbsMax()
*** SIGFPE (@0x7b3859) received by PID 8472 (TID 0x7f1f70ac2840) from PID 8075353; stack trace: ***
    @     0x7f1f7069d160 (unknown)
    @           0x7b3859 paddle::GpuVectorT<>::getAbsMax()
    @           0x74c2ef _ZNSt17_Function_handlerIFvPN6paddle9ParameterEEZNS0_15TrainerInternal13trainOneBatchElRKNS0_9DataBatchEPSt6v
ectorINS0_8ArgumentESaIS9_EEEUlS2_E_E9_M_invokeERKSt9_Any_dataS2_
    @           0x8da203 paddle::Parameter::incUpdate()
    @           0x5f808c paddle::LstmLayer::backward()
    @           0x6add1f paddle::NeuralNetwork::backward()
    @           0x74c3e3 paddle::TrainerInternal::forwardBackwardBatch()
    @           0x74d2ed paddle::TrainerInternal::trainOneBatch()
    @           0x74ac06 paddle::Trainer::trainOneDataBatch()
    @           0x74b0f9 paddle::Trainer::trainOnePass()
    @           0x74bcc5 paddle::Trainer::train()
    @           0x5b90ca main
    @     0x7f1f6f2babd5 __libc_start_main
    @           0x5ce555 (unknown)
/home/img/zongming/paddle_env/paddle_internal_release_tools/idl/paddle/output/bin/paddle_local: line 109:  8472 Floating point excepti
on(core dumped) ${DEBUGGER} $MYDIR/../opt/paddle/bin/paddle_trainer ${@:2}

**Comment by reyoung** [comment]
@fsfszongming256 请参考这个解答 https://github.com/PaddlePaddle/Paddle/pull/1617/files

这个问题会加到FAQ里面。

**Comment by yinyunfeng** [comment]
Thu Aug 17 12:26:40 2017[1,86]<stderr>:Thread [140053943498496] Forwarding hidden-2, hidden-1, input_merge, cate_5974_emb, cate_5974, cate_5975_emb
Thu Aug 17 12:26:40 2017[1,70]<stderr>:./train.sh: line 207:  4153 Floating point exceptionPYTHONPATH=./paddle:$PYTHONPATH GLOG_logtostderr=0 GLOG_log_dir="./log" ./paddle_trainer --num_gradient_servers=${OMPI_COMM_WORLD_SIZE} --trainer_id=${OMPI_COMM_WORLD_RANK} --pservers=$ipstring --rdma_tcp=${rdma_tcp} --nics=${nics} ${train_arg} --config=conf/trainer_config.conf --save_dir=./${save_dir} ${extern_arg}
Thu Aug 17 12:26:40 2017[1,86]<stderr>:, cate_5975, cate_5910_emb, cate_5910, cate_5916_emb, cate_5916, cate_5917_emb, cate_5917, cate_5914_emb, cate_5914, cate_5915_emb, cate_5915, cate_5937_emb, cate_5937, cate_4645_emb, cate_4645, cate_4644_emb, cate_4644, cate_4646_emb, cate_4646, cate_4641_emb, cate_4641, cate_4642_emb, cate_4642, id_5957, cate_4648_emb, cate_4648, cate_5123_emb, cate_5123, cate_5121_emb, cate_5121, cate_5127_emb, cate_5127, cate_5125_emb, cate_5125, id_4609, cate_4626_emb, cate_4626, id_5129, cate_5670_emb, cate_5670, cate_4193_emb, cate_4193, cate_4192_emb, cate_4192, cate_22785_emb, cate_22785, cate_22784_emb, cate_22784, cate_5944_emb, cate_5944, cate_4145_emb, cate_4145, cate_5941_emb, cate_5941, cate_5940_emb, cate_5940, cate_5943_emb, cate_5943, cate_5942_emb, cate_5942, cate_5945_emb, cate_5945, cate_4129_emb, cate_4129, cate_5946_emb, cate_5946, cate_5131_emb, cate_5131, cate_5644_emb, cate_5644, id_5889, cate_5667_emb, cate_5667, cate_4625_emb, cate_4625, 
Thu Aug 17 12:26:40 2017[1,70]<stderr>:+ '[' 136 -ne 0 ']'
Thu Aug 17 12:26:40 2017[1,86]<stderr>:label, 
Thu Aug 17 12:26:40 2017[1,86]<stderr>:*** Aborted at 1502944000 (unix time) try "date -d @1502944000" if you are using GNU date ***
Thu Aug 17 12:26:40 2017[1,70]<stderr>:+ kill_pserver2_exit
Thu Aug 17 12:26:40 2017[1,70]<stderr>:+ ps aux
Thu Aug 17 12:26:40 2017[1,70]<stderr>:+ grep paddle_pserver2
Thu Aug 17 12:26:40 2017[1,70]<stderr>:+ grep paddle_cluster_job
Thu Aug 17 12:26:40 2017[1,70]<stderr>:+ grep -v grep
Thu Aug 17 12:26:40 2017[1,86]<stderr>:
Thu Aug 17 12:26:40 2017[1,86]<stderr>:PC: @                0x0 (unknown)
Thu Aug 17 12:26:40 2017[1,70]<stderr>:+ cut -c10-14
Thu Aug 17 12:26:40 2017[1,86]<stderr>:
Thu Aug 17 12:26:40 2017[1,86]<stderr>:*** SIGFPE (@0xd994b7) received by PID 2728 (TID 0x7f60d98d3700) from PID 14259383; stack trace: ***
Thu Aug 17 12:26:40 2017[1,70]<stderr>:+ xargs kill -9
Thu Aug 17 12:26:40 2017[1,86]<stderr>:
Thu Aug 17 12:26:40 2017[1,86]<stderr>:    @     0x7f61f6316160 (unknown)
Thu Aug 17 12:26:40 2017[1,86]<stderr>:
Thu Aug 17 12:26:40 2017[1,86]<stderr>:    @           0xd994b7 mkl_blas_avx_sgemm_kernel_0

**Comment by qingqing01** [comment]
@yinyunfeng 除过上述多数据做归一化、调小学习率之外，还可以尝试加gradient clipping 或者error clipping，可以参考这个[例子](https://github.com/PaddlePaddle/models/blob/develop/nmt_without_attention/train.py#L35).
