### ISSUE TITLE
使用py_reader读取数据，如何在save_inference_model存储feed变量

### ISSUE THREAD

**Issue by gogogo45** [PaddlePaddle/Paddle#16113]
简单的fit_a_line
- 版本、环境信息：
    1）PaddlePaddle版本：Fluid-1.2
    2）系统环境：Python 2.7
- 训练信息
    1）单机
- 问题描述：
使用py_reader进行模型训练和测试，训练完成后存储预测模型。再load模型进行预测，遇到如下问题。
1. save_inference_model的时候，feeded_var_names无法赋值，写入[]可保存成功。如果写入参数['x']，执行报错。那么应该如何带参数保存model？
![image](https://user-images.githubusercontent.com/4569437/53972587-0936b680-413a-11e9-8ac4-b95627e112e0.png)

2.写入[]保存inference_model后，加载预测模型的时候用py_reader读取，feeded_var_names为空也无法通过feed输入了。py_reader此刻应该如何声明？理论上是不能读取label了。尝试新建pyreader提供数据报错。代码如下：
![image](https://user-images.githubusercontent.com/4569437/53972795-70546b00-413a-11e9-8afb-491fe816547f.png)
报错如下：
![image](https://user-images.githubusercontent.com/4569437/53972863-937f1a80-413a-11e9-9e69-3b5fba3d8177.png)

附上代码，由fit_a_line demo改造而来。其中paddle库里的uci_housing.py，增加了一个小函数
def infer_reader():
    global UCI_TEST_DATA
    load_data(paddle.dataset.common.download(URL, 'uci_housing', MD5))
    def reader():
        for d in UCI_TEST_DATA:
            yield (d[:-1])
    return reader

[train.py.zip](https://github.com/PaddlePaddle/Paddle/files/2942315/train.py.zip)

谢谢

**Comment by sneaxiy** [comment]
调用save_inference_model接口时，feeded_var_names参数传入`fluid.layers.read_file`的返回值即可。目前load_inference_model加载进行的模型还不支持py_reader输入，抱歉。

**Comment by gogogo45** [comment]
> 调用save_inference_model接口时，feeded_var_names参数传入`fluid.layers.read_file`的返回值即可。目前load_inference_model加载进行的模型还不支持py_reader输入，抱歉。

这个我有尝试过，并没有成功。因为我把网络结构封装在一个network函数里调用，read_file也在函数里面，似乎在存储的时候获取不到变量了。详见我附上的代码

**Comment by xuezhong** [comment]
> 我把网络结构封装在一个network函数里调用，read_file也在函数里面，似乎在存储的时候获取不到变量了

你可以把x,y 都从network返回过来，save的时候再用上

**Comment by gogogo45** [comment]
> > 我把网络结构封装在一个network函数里调用，read_file也在函数里面，似乎在存储的时候获取不到变量了
> 
> 你可以把x,y 都从network返回过来，save的时候再用上

尝试过，但是仍然报错
![image](https://user-images.githubusercontent.com/4569437/54067747-f5e13380-427e-11e9-90e5-70151205c4a5.png)
![image](https://user-images.githubusercontent.com/4569437/54067751-02fe2280-427f-11e9-9850-f46a88656193.png)
![image](https://user-images.githubusercontent.com/4569437/54067754-10b3a800-427f-11e9-8e43-cddf2962bfc2.png)
还是报var x is not in this block

**Comment by xuezhong** [comment]
试下feed_var_names=[x.name]
