### ISSUE TITLE
关于core的问题

### ISSUE THREAD

**Issue by Samhandsome** [PaddlePaddle/Paddle#16132]
paddle.fluid.core.EnforceNotMet 请问这个api在文档的具体位置是哪里呢 我一直没有找到 谢谢

**Comment by sneaxiy** [comment]
这个是Paddle内部错误时抛出的异常，现未有public的API。请问您是需要来做什么用呢？一般情况您不用在意这个，因为出现这个异常一般都是程序出错了。

**Comment by Samhandsome** [comment]
@sneaxiy 是这样子的 我今天在训练的时候 看到命令行里面抛出一个关于这个paddle.fluid.core.EnforceNotMet  我在API文档里面没有找到 所以想询问下

**Comment by xuezhong** [comment]
还有其他问题吗
