### ISSUE TITLE
关于文档索引的问题

### ISSUE THREAD

**Issue by Samhandsome** [PaddlePaddle/Paddle#16131]
请问，是否可以提供一份常用报错的索引，要不然出现报错还得一个个翻阅文档，有点麻烦~谢谢

**Comment by shanyi15** [comment]
Need to amplify FAQ doc
cc to @kagome112

**Comment by shanyi15** [comment]
@Samhandsome 尊敬的用户您好，请问您指的“索引”是指在终端里输某个命令，展示全部的报错信息及对应的解释，还是指希望增加这方面的文档呢？谢谢

**Comment by Samhandsome** [comment]
@shanyi15 您好 我是希望增加这方面的文档
