### ISSUE TITLE
Invoke operator fill_constant error.

### ISSUE THREAD

**Issue by AaronWhite95** [PaddlePaddle/Paddle#16136]
运行代码出现如下错误
`W0309 22:57:00.700938 37327 device_context.cc:263] Please NOTE: device: 0, CUDA Capability: 61, Driver API Version: 9.0, Runtime API Version: 9.0 W0309 22:57:00.701022 37327 device_context.cc:271] device: 0, cuDNN Version: 5.0. W0309 22:57:00.701028 37327 device_context.cc:295] WARNING: device: 0. The installed Paddle is compiled with CUDNN 7.3, but CUDNN version in your machine is 5.1, which may cause serious incompatible bug. Please recompile or reinstall Paddle with compatible CUDNN version. Traceback (most recent call last): File "bin/p_classification/p_train.py", line 149, in <module> main(conf_dict, use_cuda=use_gpu) File "bin/p_classification/p_train.py", line 137, in main train(conf_dict, data_generator, use_cuda=use_cuda) File "bin/p_classification/p_train.py", line 122, in train train_loop(fluid.default_main_program()) File "bin/p_classification/p_train.py", line 79, in train_loop exe.run(fluid.default_startup_program()) File "/home/xfbai/anaconda3/envs/py2/lib/python2.7/site-packages/paddle/fluid/executor.py", line 525, in run use_program_cache=use_program_cache) File "/home/xfbai/anaconda3/envs/py2/lib/python2.7/site-packages/paddle/fluid/executor.py", line 591, in _run exe.run(program.desc, scope, 0, True, True) paddle.fluid.core.EnforceNotMet: Invoke operator fill_constant error. Python Callstacks: File "/home/xfbai/anaconda3/envs/py2/lib/python2.7/site-packages/paddle/fluid/framework.py", line 1382, in _prepend_op attrs=kwargs.get("attrs", None)) File "/home/xfbai/anaconda3/envs/py2/lib/python2.7/site-packages/paddle/fluid/initializer.py", line 167, in __call__ stop_gradient=True) File "/home/xfbai/anaconda3/envs/py2/lib/python2.7/site-packages/paddle/fluid/framework.py", line 1198, in create_var kwargs['initializer'](var, self) File "/home/xfbai/anaconda3/envs/py2/lib/python2.7/site-packages/paddle/fluid/layer_helper.py", line 402, in set_variable_initializer initializer=initializer) File "/home/xfbai/anaconda3/envs/py2/lib/python2.7/site-packages/paddle/fluid/layers/tensor.py", line 137, in create_global_var value=float(value), force_cpu=force_cpu)) File "/home/xfbai/anaconda3/envs/py2/lib/python2.7/site-packages/paddle/fluid/optimizer.py", line 92, in _create_global_learning_rate persistable=True) File "/home/xfbai/anaconda3/envs/py2/lib/python2.7/site-packages/paddle/fluid/optimizer.py", line 224, in _create_optimization_pass self._create_global_learning_rate() File "/home/xfbai/anaconda3/envs/py2/lib/python2.7/site-packages/paddle/fluid/optimizer.py", line 350, in apply_gradients optimize_ops = self._create_optimization_pass(params_grads) File "/home/xfbai/anaconda3/envs/py2/lib/python2.7/site-packages/paddle/fluid/optimizer.py", line 405, in minimize optimize_ops = self.apply_gradients(params_grads) File "bin/p_classification/p_train.py", line 65, in train sgd_optimizer.minimize(avg_cost) File "bin/p_classification/p_train.py", line 137, in main train(conf_dict, data_generator, use_cuda=use_cuda) File "bin/p_classification/p_train.py", line 149, in <module> main(conf_dict, use_cuda=use_gpu)`
请问是什么问题呢

**Comment by xuezhong** [comment]
fill_constant 是网络初始化的时候调用的，这个一般不太出错，在这个环境下，其他demo能运行吗？compiled with CUDNN 7.3, but CUDNN version in your machine is 5.1 另外这个问题也需要关注下

**Comment by AaronWhite95** [comment]
简单的demo可以运行
![image](https://user-images.githubusercontent.com/19512779/54095799-07901b80-43e4-11e9-82b8-27f7c0e4e1b1.png)

**Comment by xuezhong** [comment]
你把出错的代码贴下吧

**Comment by renhui19931001** [comment]
同问，用mmap内存映射加上py_reader的时候报的错误，请问解决了么

**Comment by xuehui0725** [comment]
同出现这个问题，相同的环境，相同的代码，别人的数据集正常，自己的数据跑时就会出现上面的错误Invoke operator fill_constant error。数据集格式没有问题。@HWZX 请问你找到原因了吗？

**Comment by corgi66** [comment]
你重新登陆一下服务器 重新训练一下就好啦 我的原因是内存不够 显示这个问题的
