### ISSUE TITLE
关于本地分布式训练的问题

### ISSUE THREAD

**Issue by superwj1990** [PaddlePaddle/Paddle#16138]
在ps模式的分布式训练中，我设置了
export PADDLE_PSERVER_ENDPOINTS="10.98.149.31:7160,10.98.151.31:7161"
...
PADDLE_TRAINING_ROLE="TRAINER" \
PADDLE_CURRENT_ENDPOINT="10.98.151.31:7161" \
PADDLE_TRAINER_ID="0" \
CUDA_VISIBLE_DEVICES="0,1,2,3,4,5,6,7" \
fluid -u train_classifier_distributed_version.py
可是，实际运行中，当PADDLE_TRAINING_ROLE="TRAINER"时，仍在10.98.149.31机器上运行，而不是10.98.151.31。这个该怎么设置？
有没有本地机器自己搭建分布式训练的教程，看到官网都是集群分布式训练的教程，或者一台机器不同端口来模拟多台机器的教程。

**Comment by jacquesqiao** [comment]
两个trainer的PADDLE_TRAINER_ID 设置成0或者1

**Comment by superwj1990** [comment]
问题解决了，本地多台机器的分布式运算，不同trainer的代码要在实际机器上运行，并且保证每台机器的代码是完全一致的。
