### ISSUE TITLE
make error, Segmentation fault, No space left on device.

### ISSUE THREAD

**Issue by shippingwang** [PaddlePaddle/Paddle#16143]
![image](https://user-images.githubusercontent.com/13645332/54098667-74a9ae00-43f0-11e9-915f-ed1d57e4b28a.png)
It seems like my /tmp folder is already full, and would raise a make error, I link the /tmp to ~ /tmp.
mkdir ~ /tmp
export TMPDIR=~/tmp
It doesn't work.

**Comment by NHZlX** [comment]
I met the same problem before. The default docker container's  capacity is 10G. When you compile with multithreading, like `make -j  N`,  when N is big,  the generated tmp files take up a lot of space. Try `make -j 10 ` or lift docker container space.
