### ISSUE TITLE
训练在cross_entropy出报错 

### ISSUE THREAD

**Issue by dubhex** [PaddlePaddle/Paddle#16142]
使用cross_entropy 时报错：
相关部分代码：
`
def net_config(image, label, model, args):
    _, score_out = model(image)
    cost = fluid.layers.cross_entropy(score_out, label)
    avg_cost = fluid.layers.mean(cost)
    return avg_cost, score_out, label
`

运行时报错：

> Traceback (most recent call last):
  File "run_fast_train_score.py", line 334, in <module>
    train(args)
  File "run_fast_train_score.py", line 227, in train
    loss_tr_np, score_out_tr_np, label_tr, lr_tr_np = train_exe.run(fetch_list = train_fetch_list)
  File "/opt/python/cp27-cp27mu/lib/python2.7/site-packages/paddle/fluid/parallel_executor.py", line 303, in run
    self.executor.run(fetch_list, fetch_var_name)
paddle.fluid.core.EnforceNotMet: Invoke operator cross_entropy error.
Python Callstacks: 
  File "/opt/python/cp27-cp27mu/lib/python2.7/site-packages/paddle/fluid/framework.py", line 1317, in append_op
    attrs=kwargs.get("attrs", None))
  File "/opt/python/cp27-cp27mu/lib/python2.7/site-packages/paddle/fluid/layer_helper.py", line 56, in append_op
    return self.main_program.current_block().append_op(*args, **kwargs)
  File "/opt/python/cp27-cp27mu/lib/python2.7/site-packages/paddle/fluid/layers/nn.py", line 1409, in cross_entropy
    "ignore_index": ignore_index})
  File "run_fast_train_score.py", line 105, in net_config
    cost = fluid.layers.cross_entropy(score_out, label)
  File "run_fast_train_score.py", line 125, in build_program
    avg_cost, score_out, label = net_config(image, label, model, args)
  File "run_fast_train_score.py", line 158, in train
    is_train = True, main_prog = train_prog, startup_prog = startup_prog, args = args)
  File "run_fast_train_score.py", line 334, in <module>
    train(args)
C++ Callstacks: 
Tensor holds the wrong type, it holds int at [/paddle/paddle/fluid/framework/tensor_impl.h:29]
PaddlePaddle Call Stacks: 
0       0x7fb172ccdf15p void paddle::platform::EnforceNotMet::Init<char const*>(char const*, char const*, int) + 357
1       0x7fb172cce299p paddle::platform::EnforceNotMet::EnforceNotMet(std::__exception_ptr::exception_ptr, char const*, int) + 137
2       0x7fb174540187p paddle::operators::math::CrossEntropyFunctor<paddle::platform::CUDADeviceContext, float>::operator()(paddle::platform::CUDADeviceContext const&, paddle::framework::Tensor*, paddle::framework::Tensor const*, paddle::framework::Tensor const*, bool, int) + 1687
3       0x7fb1731f8895p paddle::operators::CrossEntropyOpKernel<paddle::platform::CUDADeviceContext, float>::Compute(paddle::framework::ExecutionContext const&) const + 469
4       0x7fb1731f89f3p _ZNSt17_Function_handlerIFvRKN6paddle9framework16ExecutionContextEEZNKS1_24OpKernelRegistrarFunctorINS0_8platform9CUDAPlaceELb0ELm0EJNS0_9operators20CrossEntropyOpKernelINS7_17CUDADeviceContextEfEENSA_ISB_dEENSA_ISB_NS7_7float16EEEEEclEPKcSI_iEUlS4_E_E9_M_invokeERKSt9_Any_dataS4_ + 35
5       0x7fb1747c1d43p paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&) const + 659
6       0x7fb1747bf5b5p paddle::framework::OperatorBase::Run(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&) + 341
7       0x7fb17463592ap paddle::framework::details::ComputationOpHandle::RunImpl() + 250
8       0x7fb17462f006p paddle::framework::details::OpHandleBase::Run(bool) + 118
9       0x7fb1745c721dp
10      0x7fb1738e4643p std::_Function_handler<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> ()(), std::__future_base::_Task_setter<std::unique_ptr<std::__future_base::_Result<void>, std::__future_base::_Result_base::_Deleter>, void> >::_M_invoke(std::_Any_data const&) + 35
11      0x7fb1738a7967p std::__future_base::_State_base::_M_do_set(std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> ()()>&, bool&) + 39
12      0x7fb1b4485e03p pthread_once + 83
13      0x7fb1745c5f02p
14      0x7fb1738a8d94p _ZZN10ThreadPoolC1EmENKUlvE_clEv + 404
15      0x7fb1ab607470p
16      0x7fb1b4480aa1p
17      0x7fb1b3b42bcdp clone + 109

请问这是怎么回事，如何解决？

**Comment by tensor-tang** [comment]
> C++ Callstacks:
Tensor holds the wrong type, it holds int at [/paddle/paddle/fluid/framework/tensor_impl.h:29]
PaddlePaddle Call Stacks:

根据error信息，请检查下数据格式

**Comment by dubhex** [comment]
查到问题是使用cross_entrop时如果是hard label，label数据类型应该是int64，更正后原来的问题小时，但是又出现了新的问题：

> terminate called after throwing an instance of 'paddle::platform::EnforceNotMet'
  what():  an illegal memory access was encountered at [/paddle/paddle/fluid/framework/details/op_handle_base.cc:37]
PaddlePaddle Call Stacks: 
0       0x7fcad6582f15p void paddle::platform::EnforceNotMet::Init<char const*>(char const*, char const*, int) + 357
1       0x7fcad6583299p paddle::platform::EnforceNotMet::EnforceNotMet(std::__exception_ptr::exception_ptr, char const*, int) + 137
2       0x7fcad7ee3f41p paddle::framework::details::OpHandleBase::~OpHandleBase() + 337
3       0x7fcad7ed1df1p paddle::framework::details::FetchOpHandle::~FetchOpHandle() + 17
4       0x7fcad6633fd9p paddle::framework::ir::Node::~Node() + 73
5       0x7fcad6634181p paddle::framework::ir::Node::~Node() + 17
6       0x7fcad7ed392bp paddle::framework::details::ClearFetchOp(paddle::framework::ir::Graph*, std::vector<paddle::framework::details::FetchOpHandle*, std::allocator<paddle::framework::details::FetchOpHandle*> >*) + 1995
7       0x7fcad7e7f1b4p paddle::framework::details::ThreadedSSAGraphExecutor::Run(std::vector<std::string, std::allocator<std::string> > const&) + 4660
8       0x7fcad7e7591ap paddle::framework::details::ScopeBufferedSSAGraphExecutor::Run(std::vector<std::string, std::allocator<std::string> > const&) + 394
9       0x7fcad66c12e2p paddle::framework::ParallelExecutor::Run(std::vector<std::string, std::allocator<std::string> > const&, std::string const&) + 562
10      0x7fcad65738fep
11      0x7fcad65ae84ep
12      0x7fcb1801fce8p PyEval_EvalFrameEx + 28264
13      0x7fcb1802237dp PyEval_EvalCodeEx + 2061
14      0x7fcb1801fd70p PyEval_EvalFrameEx + 28400
15      0x7fcb1802237dp PyEval_EvalCodeEx + 2061
16      0x7fcb1801fd70p PyEval_EvalFrameEx + 28400
17      0x7fcb1802237dp PyEval_EvalCodeEx + 2061
18      0x7fcb180224b2p PyEval_EvalCode + 50
19      0x7fcb1804c1c2p PyRun_FileExFlags + 146
20      0x7fcb1804d559p PyRun_SimpleFileExFlags + 217
21      0x7fcb180631ddp Py_Main + 3149
22      0x7fcb172f6d1dp __libc_start_main + 253
23            0x4006b1p

*** Aborted at 1552219730 (unix time) try "date -d @1552219730" if you are using GNU date ***
PC: @                0x0 (unknown)
*** SIGABRT (@0x7d7) received by PID 2007 (TID 0x7fcb18534700) from PID 2007; stack trace: ***
    @     0x7fcb17d067e0 (unknown)
    @     0x7fcb1730a495 __GI_raise
    @     0x7fcb1730bc75 __GI_abort
    @     0x7fcb0d0a5a8d __gnu_cxx::__verbose_terminate_handler()
    @     0x7fcb0d0a3be6 (unknown)
    @     0x7fcb0d0a2b69 (unknown)
    @     0x7fcb0d0a35c1 __gxx_personality_v0
    @     0x7fcb0d51d383 (unknown)
    @     0x7fcb0d51d70d _Unwind_RaiseException
    @     0x7fcb0d0a3d25 __cxa_throw
    @     0x7fcad7ee3f5f paddle::framework::details::OpHandleBase::~OpHandleBase()
    @     0x7fcad7ed1df1 paddle::framework::details::FetchOpHandle::~FetchOpHandle()
    @     0x7fcad6633fd9 paddle::framework::ir::Node::~Node()
    @     0x7fcad6634181 paddle::framework::ir::Node::~Node()
    @     0x7fcad7ed392b paddle::framework::details::ClearFetchOp()
    @     0x7fcad7e7f1b4 paddle::framework::details::ThreadedSSAGraphExecutor::Run()
    @     0x7fcad7e7591a paddle::framework::details::ScopeBufferedSSAGraphExecutor::Run()
    @     0x7fcad66c12e2 paddle::framework::ParallelExecutor::Run()
    @     0x7fcad65738fe _ZZN8pybind1112cpp_function10initializeIZN6paddle6pybindL18pybind11_init_coreERNS_6moduleEEUlRNS2_9framework16ParallelExecutorERKSt6vectorISsSaISsEERKSsE152_vIS8_SD_SF_EINS_4nameENS_9is_methodENS_7siblingEEEEvOT_PFT0_DpT1_EDpRKT2_ENUlRNS_6detail13function_callEE1_4_FUNESX_
    @     0x7fcad65ae84e pybind11::cpp_function::dispatcher()
    @     0x7fcb1801fce8 PyEval_EvalFrameEx
    @     0x7fcb1802237d PyEval_EvalCodeEx
    @     0x7fcb1801fd70 PyEval_EvalFrameEx
    @     0x7fcb1802237d PyEval_EvalCodeEx
    @     0x7fcb1801fd70 PyEval_EvalFrameEx
    @     0x7fcb1802237d PyEval_EvalCodeEx
    @     0x7fcb180224b2 PyEval_EvalCode
    @     0x7fcb1804c1c2 PyRun_FileExFlags
    @     0x7fcb1804d559 PyRun_SimpleFileExFlags
    @     0x7fcb180631dd Py_Main
    @     0x7fcb172f6d1d __libc_start_main
    @           0x4006b1 (unknown)
Aborted

请问是什么情况？

**Comment by tensor-tang** [comment]
> C++ Callstacks:
Tensor holds the wrong type, it holds int at [/paddle/paddle/fluid/framework/tensor_impl.h:29]
PaddlePaddle Call Stacks: 
6 0x7fcad7ed392bp paddle::framework::details::ClearFetchOp(paddle::framework::ir::Graph*, std::vector<paddle::framework::details::FetchOpHandle*, 

应该是某些数据访问越界了，或者内存没申请？

**Comment by dubhex** [comment]
> > C++ Callstacks:
> > Tensor holds the wrong type, it holds int at [/paddle/paddle/fluid/framework/tensor_impl.h:29]
> > PaddlePaddle Call Stacks:
> > 6 0x7fcad7ed392bp paddle::framework::details::ClearFetchOp(paddle::framework::ir::Graph*, std::vector<paddle::framework::details::FetchOpHandle*,
> 
> 应该是某些数据访问越界了，或者内存没申请？

问题找到了，有的数据没找到，感谢帮助！

**Comment by tensor-tang** [comment]
不用客气哈
