### ISSUE TITLE
Fluid的StaticRNN op文档不完善

### ISSUE THREAD

**Issue by zenghsh3** [PaddlePaddle/Paddle#16141]
Fluid的StaticRNN op的文档不完善：

http://paddlepaddle.org/documentation/docs/zh/1.1/api_cn/layers.html#staticrnn

例如缺少用法说明：StaticRNN处理序列问题时，对于Batch_size * Timestep的传统输入，如果需要对每个时间步处理，需要先转置成Timestep * Batch_size，因为StaticRNN是沿着第0维进行遍历。

感觉目前的文档没有提供相关使用说明和例子。

**Comment by tensor-tang** [comment]
多谢反馈，我们会完善相关文档

**Comment by shanyi15** [comment]
please take a look, thanks @zhaoyuchen2018

**Comment by shanyi15** [comment]
FIXED by https://github.com/PaddlePaddle/Paddle/pull/16707
