### ISSUE TITLE
mkldnn related irpasses are added triple times when mkldnn is enabled in AnaylsisPredictor

### ISSUE THREAD

**Issue by LeoZhao-BJ** [PaddlePaddle/Paddle#16174]
**System information**
-PaddlePaddle version: develop
-CPU: including CPUMKL/OpenBlas/MKLDNN version
-OS Platform : Linux

**To Reproduce**
use test in paddle/fluid/inference/tests/api/ and observe how many mkldnn related irpasses are processed.

**Describe your current behavior**
The rootcause is CpuPassStrategy uses copy constructor to re-initialize PassStrategy, the passes in previous instance is still kept, so mkldnn related irpasses are added multiple times.  

**Code to reproduce the issue**
**Other info / logs**

**Comment by luotao1** [comment]
@LeoZhao-Intel Thanks for your issue! I can reproduce it:
- command:
```
./paddle/fluid/inference/tests/api/test_analyzer_resnet50 --infer_model=third_party/inference_demo/resnet50/model/ --gtest_filter=Analyzer_resnet50.profile_mkldnn --paddle_num_threads=1 --repeat=1 --batch_size=1
```
- result: There are three `mkldnn_placement_pass`.
```
I0313 03:04:25.902946 12478 analysis_predictor.cc:377] MKLDNN is enabled
--- Running analysis [ir_graph_build_pass]
--- Running analysis [ir_analysis_pass]
--- Running IR pass [mkldnn_placement_pass]
--- Running IR pass [mkldnn_placement_pass]
--- Running IR pass [mkldnn_placement_pass]
--- Running IR pass [infer_clean_graph_pass]
--- Running IR pass [attention_lstm_fuse_pass]
--- Running IR pass [seqpool_concat_fuse_pass]
--- Running IR pass [seqconv_eltadd_relu_fuse_pass]
```
@kbinias Do you know why?

**Comment by LeoZhao-BJ** [comment]
https://github.com/PaddlePaddle/Paddle/pull/16175, this is patch for the fix. 

The rootcause is CpuPassStrategy uses copy constructor to re-initialize PassStrategy by update() function, the passes in previous instance is still kept, so mkldnn related irpasses are added multiple times.

**Comment by luotao1** [comment]
close due to #16606
