### ISSUE TITLE
在目标检测中，图片的每个通道不需要减去均值也可以的吧？

### ISSUE THREAD

**Issue by yeyupiaoling** [PaddlePaddle/Paddle#16182]
# 环境
 - PaddlePaddle 1.2
 - Ubuntu 16.04
 - Python 3.5

# 问题

在目标检测中，例如使用VOC数据集的时候，会对每个通道都减去一个均值：https://github.com/PaddlePaddle/models/blob/9e76aa14796e04ef24c10c1080edcabf38341caf/fluid/PaddleCV/object_detection/reader.py#L160

我换成了我的数据集，我不知道这个均值应该设置多少，这个可以忽略的吗？

**Comment by wzzju** [comment]
您好！可以继续使用原来的均值。

**Comment by yeyupiaoling** [comment]
好的，谢谢。
