### ISSUE TITLE
api文档中warpctc的实例是错的

### ISSUE THREAD

**Issue by kolinwei** [PaddlePaddle/Paddle#16184]
label = fluid.layers.data(shape=[11, 8], dtype='float32', lod_level=1)
predict = fluid.layers.data(shape=[11, 1], dtype='float32')
直接运行会出错， fluid.layers.data需要传入name的参数。应该为如下:
label = fluid.layers.data(name="label", shape=[11, 8], dtype='float32', lod_level=1)
predict = fluid.layers.data(name="predict", shape=[11, 1], dtype='float32')

**Comment by wanghaoshuang** [comment]
已修复：https://github.com/PaddlePaddle/Paddle/blob/release/1.5/python/paddle/fluid/layers/nn.py#L5492-L5495
