### ISSUE TITLE
paddle fluid如何读文件训练

### ISSUE THREAD

**Issue by zhaocaibei123** [PaddlePaddle/Paddle#16180]
咨询一下如何读文件，看文档有些迷糊，咨询几个问题：
1. Python Reader同步方式 和 py_reader接口异步方式 具体是什么样的？同步是指先读完数据 都load到内存里，再开始训练；异步是指一边读数据一边训练吗，会有单独的线程读数据？
2. Python Reader方式 读文件
http://www.paddlepaddle.org/documentation/docs/en/develop/user_guides/howto/prepare_data/reader.html
def image_reader_creator(image_path, label_path, n):
   def reader():
        f = open(image_path)
        l = open(label_path)
        images = numpy.fromfile(
            f, 'ubyte', count=n * 28 * 28).reshape((n, 28 * 28)).astype('float32')
        images = images / 255.0 * 2.0 - 1.0
        labels = numpy.fromfile(l, 'ubyte', count=n).astype("int")
        for i in xrange(n):
            yield images[i, :], labels[i] # a single entry of data is created each time
        f.close()
        l.close()
    return reader
reader = image_reader_creator("/path/to/image_file", "/path/to/label_file", 1024)
paddle.train(paddle.batch(reader, 128), {"image":0, "label":1}, ...)
文档中定义好reader之后，只能调 paddle.train() 函数 来用吗，train函数里 do_forward_backward 是在哪里定义的呢
def train(batch_reader, mapping, batch_size, total_pass):
    for pass_idx in range(total_pass):
        for mini_batch in batch_reader(): # this loop will never end in online learning.
            do_forward_backward(mini_batch, mapping)
另外看到有用DataFeed来读数据的方式，可以给个示例吗
3. Python Reader方式 中 prefetch_data 是在什么时候预取数据的呢，跟同步异步方式有联系吗？
4. py_reader接口异步方式是怎么实现的能简单介绍下吗
5. 最后，能否给个完整的读文件+训练的实例，本地小数据 同步方式 就可以

**Comment by yeyupiaoling** [comment]
@zhaocaibei123 我这个例子就是用同步的方式读取本地图片文件的：https://blog.csdn.net/qq_33200967/article/details/87895105

**Comment by sneaxiy** [comment]
1. 同步是指一个batch的数据load到内存里，再开始训练；异步是指有个单独的线程准备数据，训练和数据加载是并行执行的。
2. paddle.train在官网里的例子有误，近期我们已经进行修改，您可浏览最近官网上的中文文档。
3. Python Reader里的prefetch data也是开线程预读，但存在Python GIL和CPU到GPU数据的同步拷贝等因素，因此使用py_reader会更快些。
4. py_reader异步方式内部是开启线程，同时释放Python GIL锁，且完成了CPU到GPU的异步拷贝。
5. 请参阅：http://www.paddlepaddle.org/documentation/docs/zh/develop/user_guides/howto/prepare_data/use_py_reader.html

**Comment by zhaocaibei123** [comment]
好的，谢谢两位

**Comment by zhaocaibei123** [comment]
`import numpy as np
import paddle
import paddle.fluid as fluid

def my_train_reader(train_file_path):
    def reader():
        with open(train_file_path, 'r') as f:
            lines = f.readlines()
            np.random.shuffle(lines)
            for line in lines:
                line = line.strip().split(' ')
                line = [int(l) for l in line]
                label = line[0]
                data = line[1:]
                yield data, label
    return reader()


def network(look_up_size):
    data = fluid.layers.data(name='ids', shape=[-1, 1], dtype='int32', append_batch_size=False, lod_level=1)
    label_data = fluid.layers.data(name='label', shape=[-1, 1], dtype='int32')
    embed = fluid.layers.embedding(input=data, size=[look_up_size, 8], padding_idx=None, is_sparse=True)
    #sum_embed_square = fluid.layers.reduce_sum(embed, dim=1)
    sum_embed_square = fluid.layers.sequence_pool(input=embed, pool_type="sum")
    sum_embed_square = fluid.layers.square(sum_embed_square)
    embed_square_sum = fluid.layers.sequence_pool(fluid.layers.square(embed), pool_type="sum")
    fm = fluid.layers.reduce_sum(0.5 * fluid.layers.elementwise_sub(sum_embed_square, embed_square_sum), dim=1, keep_dim=True)

    fm = fluid.layers.sigmoid(fm)
    cost = fluid.layers.cross_entropy(input=fm,label=label_data)
    avg_cost = fluid.layers.mean(x=cost)

    sgd_optimizer = fluid.optimizer.SGD(learning_rate=0.001)
    opt = sgd_optimizer.minimize(avg_cost)

    place = fluid.CPUPlace()
    exe = fluid.Executor(place)
    exe.run(fluid.default_startup_program())

    train_reader = paddle.batch(reader=my_train_reader('test.data'), batch_size=1)
    
    feeder = fluid.DataFeeder(place=place, feed_list=[data, label_data])

    for pass_id in range(100):
        for batch_id, data in enumerate(train_reader()):
            train_cost = exe.run(program=fluid.default_main_program(),
                    feed=feeder.feed(data),
                    fetch_list=[avg_cost])
            if batch_id % 100 == 0:
                print 'pass:%d, batch:%d, cost:%0.5f' % (pass_id, batch_id, train_cost)
    

if __name__ == '__main__':
    network(32)`

**Comment by zhaocaibei123** [comment]
import numpy as np
import paddle
import paddle.fluid as fluid

def my_train_reader(train_file_path):
    def reader():
        with open(train_file_path, 'r') as f:
            lines = f.readlines()
            np.random.shuffle(lines)
            for line in lines:
                line = line.strip().split(' ')
                line = [int(l) for l in line]
                label = line[0]
                data = line[1:]
                yield data, label
    return reader()


def network(look_up_size):
    data = fluid.layers.data(name='ids', shape=[-1, 1], dtype='int32', append_batch_size=False, lod_level=1)
    label_data = fluid.layers.data(name='label', shape=[-1, 1], dtype='int32')
    embed = fluid.layers.embedding(input=data, size=[look_up_size, 8], padding_idx=None, is_sparse=True)
    #sum_embed_square = fluid.layers.reduce_sum(embed, dim=1)
    sum_embed_square = fluid.layers.sequence_pool(input=embed, pool_type="sum")
    sum_embed_square = fluid.layers.square(sum_embed_square)
    embed_square_sum = fluid.layers.sequence_pool(fluid.layers.square(embed), pool_type="sum")
    fm = fluid.layers.reduce_sum(0.5 * fluid.layers.elementwise_sub(sum_embed_square, embed_square_sum), dim=1, keep_dim=True)

    fm = fluid.layers.sigmoid(fm)
    cost = fluid.layers.cross_entropy(input=fm,label=label_data)
    avg_cost = fluid.layers.mean(x=cost)

    sgd_optimizer = fluid.optimizer.SGD(learning_rate=0.001)
    opt = sgd_optimizer.minimize(avg_cost)

    place = fluid.CPUPlace()
    exe = fluid.Executor(place)
    exe.run(fluid.default_startup_program())

    train_reader = paddle.batch(reader=my_train_reader('test.data'), batch_size=1)
    
    feeder = fluid.DataFeeder(place=place, feed_list=[data, label_data])

    for pass_id in range(100):
        for batch_id, data in enumerate(train_reader()):
            train_cost = exe.run(program=fluid.default_main_program(),
                    feed=feeder.feed(data),
                    fetch_list=[avg_cost])
            if batch_id % 100 == 0:
                print 'pass:%d, batch:%d, cost:%0.5f' % (pass_id, batch_id, train_cost)
    

if __name__ == '__main__':
    network(32)

**Comment by zhaocaibei123** [comment]
想实现一个fm模型，从本地文件读数据训练，数据格式如下（sparse feature）
label1 feature_id11 feature_id12 ...
label2 feature_id21 feature_id22 ...
下面代码读数据会报错，请问怎么改正
`
import numpy as np
import paddle
import paddle.fluid as fluid

def my_train_reader(train_file_path):
    def reader():
        with open(train_file_path, 'r') as f:
            lines = f.readlines()
            np.random.shuffle(lines)
            for line in lines:
                line = line.strip().split(' ')
                line = [int(l) for l in line]
                label = line[0]
                data = line[1:]
                yield data, label
    return reader()


def network(look_up_size):
    data = fluid.layers.data(name='ids', shape=[-1, 1], dtype='int32', append_batch_size=False, lod_level=1)
    label_data = fluid.layers.data(name='label', shape=[-1, 1], dtype='int32')
    embed = fluid.layers.embedding(input=data, size=[look_up_size, 8], padding_idx=None, is_sparse=True)
    #sum_embed_square = fluid.layers.reduce_sum(embed, dim=1)
    sum_embed_square = fluid.layers.sequence_pool(input=embed, pool_type="sum")
    sum_embed_square = fluid.layers.square(sum_embed_square)
    embed_square_sum = fluid.layers.sequence_pool(fluid.layers.square(embed), pool_type="sum")
    fm = fluid.layers.reduce_sum(0.5 * fluid.layers.elementwise_sub(sum_embed_square, embed_square_sum), dim=1, keep_dim=True)

    fm = fluid.layers.sigmoid(fm)
    cost = fluid.layers.cross_entropy(input=fm,label=label_data)
    avg_cost = fluid.layers.mean(x=cost)

    sgd_optimizer = fluid.optimizer.SGD(learning_rate=0.001)
    opt = sgd_optimizer.minimize(avg_cost)

    place = fluid.CPUPlace()
    exe = fluid.Executor(place)
    exe.run(fluid.default_startup_program())

    train_reader = paddle.batch(reader=my_train_reader('test.data'), batch_size=1)
    
    feeder = fluid.DataFeeder(place=place, feed_list=[data, label_data])

    for pass_id in range(100):
        for batch_id, data in enumerate(train_reader()):
            train_cost = exe.run(program=fluid.default_main_program(),
                    feed=feeder.feed(data),
                    fetch_list=[avg_cost])
            if batch_id % 100 == 0:
                print 'pass:%d, batch:%d, cost:%0.5f' % (pass_id, batch_id, train_cost)
    

if __name__ == '__main__':
    network(32)
`
报错信息：
Traceback (most recent call last):
  File "net.py", line 54, in <module>
    network(32)
  File "net.py", line 45, in network
    for batch_id, data in enumerate(train_reader()):
  File "XXX/python/lib/python2.7/site-packages/paddle/batch.py", line 33, in batch_reader
    r = reader()
TypeError: 'generator' object is not callable

**Comment by SunGaofeng** [comment]
下面代码里面的，return reader()换成 return reader
line = [int(l) for l in line]
label = line[0]
data = line[1:]
yield data, label
return reader()
