### ISSUE TITLE
PaddlePaddle有复现MTCNN模型吗？

### ISSUE THREAD

**Issue by yeyupiaoling** [PaddlePaddle/Paddle#16200]
最近想使用这个模型，请问有复现这个模型吗？models下是没有的。

**Comment by jerrywgz** [comment]
目前还没有复现这个模型

**Comment by yeyupiaoling** [comment]
有没有其他朋友复现的呢？

**Comment by jerrywgz** [comment]
现在paddle还没有将复现这个模型列入计划，您这边可以尝试开发，我们这边会提供协助，或是提个需求我们进行排期

**Comment by yeyupiaoling** [comment]
@jerrywgz 我有先您们的公众号提了需要复现的模型，但是估计没那么快吧。我还是先自己尝试自己复现吧，公司不会等那么久的。我遇到问题再向您们提问。
