### ISSUE TITLE
python paddle 如何流式预测

### ISSUE THREAD

**Issue by snowsteper** [PaddlePaddle/Paddle#16209]
如题

当前通过fluid.io.load_inference_model的方式加载模型的时候，模型加载和实际的exe.run预测都需要在with fluid.scope_guard(inference_scope)结构下面，这导致流式预测的时候，每次都要加载一次模型
有没有可以把加载模型和实际预测操作分离的方式完成预测？

**Comment by NHZlX** [comment]
```
import paddle.fluid as fluid
#from infer_model4 import net
import numpy as np

exe = fluid.Executor(fluid.CPUPlace())

tensor_img = np.zeros([1, 3, 3, 3], dtype=np.float32)
tensor_img[0, 0, 0, 0] = 1.0

[inference_program, feed_target_names, fetch_targets] = \
            fluid.io.load_inference_model(dirname='./conv_test3', executor=exe, model_filename='model', params_filename='params')
            #fluid.io.load_inference_model(dirname='./checkouts4', executor=exe)
#with fluid.program_guard(inference_program):
results = exe.run(inference_program,
	feed={feed_target_names[0]: tensor_img},
	    fetch_list=fetch_targets)

result = results[0].flatten()
   
print result
```

fluid.io.load_inference_model 已经做了加载模型的工作，之后用exe.run 预测就可以，可以不用每次都load model。

**Comment by snowsteper** [comment]
跑通了，感谢。
另外，问下，如果不加with fluid.scope_guard(inference_scope)就可以进行所有的操作，那声明Scope以及使用这个with结构的意义是什么呢，看book里面的预测里面都采用了这个结构

**Comment by NHZlX** [comment]
请问一下，加上这个scope ，你这边有哪些操作进行不了

**Comment by snowsteper** [comment]
就是题目里提的，使用with scope这个结构，所有的操作都必须在with这个结构里面，就导致模型的加载和预测没法分离，流式预测的时候每条数据都要加载模型
现在来看，不用scope这个结构，就能完成加载和预测所有的操作，所以这边想问一下用Scope的意义是什么

**Comment by NHZlX** [comment]
scope可以认为保护 inference_program。应用场景的话，我估计是多个模型同时用python加载的时候，会用到

**Comment by junjun315** [comment]
http://paddlepaddle.org/documentation/docs/zh/1.3/advanced_usage/design_idea/fluid_design_idea.html#permalink-5-blockdesc-and-programdesc
可以参考这里的文档，查看with的含义
