### ISSUE TITLE
源码编译错误：编译新增功能的分支版本，cuda9.0-cudnnv7出现Exception: patch core..so failed

### ISSUE THREAD

**Issue by liushanshan07** [PaddlePaddle/Paddle#16215]
辛苦帮忙看看编译问题：
- 版本、环境信息：
    1）PaddlePaddle版本：分支版本
    2）GPU：请提供GPU型号，CUDA9.0和CUDNNv7版本号
- 安装方式信息：
1）docker编译：
提供docker镜像: docker pull registry.baidu.com/paddlecloud/paddlecloud-runenv-centos6u3-online:paddlecloud-v1.3.0-gcc540-cuda9.0_cudnn7
编译命令：bash -x paddle/scripts/paddle_build.sh build
2)编译出现问题

> [ 96%] Generating paddle_fluid.dir/unsqueeze_op.objlist
[ 96%] Generating paddle_fluid.dir/fill_zeros_like_op.objlist
[ 96%] Generating paddle_fluid.dir/gaussian_random_op.objlist
Traceback (most recent call last):
  File "setup.py", line 230, in <module>
    raise Exception("patch core.%s failed, command: %s" % (ext_name, command))
Exception: patch core..so failed, command: /usr/bin/patchelf --set-rpath '$ORIGIN/../libs/' /root/cuda90_cudnnv7/Paddle/build/python/paddle/fluid/core.so
[ 96%] Generating paddle_fluid.dir/sign_op.objlist
make[2]: *** [python/build/.timestamp] Error 1
make[1]: *** [python/CMakeFiles/paddle_python.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 96%] Generating paddle_fluid.dir/huber_loss_op.objlist
[ 96%] Generating paddle_fluid.dir/load_combine_op.objlist
[ 96%] Generating paddle_fluid.dir/affine_channel_op.objlist
[ 96%] Linking CXX executable test_analyzer_rnn2
[ 96%] Linking CXX executable test_analyzer_mobilenet_depthwise_conv
[ 96%] Generating paddle_fluid.dir/clip_by_norm_op.objlist

**Comment by JiabinYang** [comment]
那这个问题您可以去paddle cloud的群里提问下，看起来是/usr/bin/patchelf --set-rpath '$ORIGIN/../libs/这个指令没有执行成功
