### ISSUE TITLE
How to save model for inference in C-API?

### ISSUE THREAD

**Issue by wojtuss** [PaddlePaddle/Paddle#16229]
@luotao1 
Is there any way to save an optimized and quantized model for inference in C-API?
If not, is there any simple way to implement it?

**Comment by luotao1** [comment]
There is no save model interface in C-API.
Maybe you could refer to `AnalysisPredictor::LoadParameters()` and `AnalysisPredictor::LoadProgramDesc()` to implement a `SaveParameters()` and `SaveProgramDesc()`.

**Comment by luotao1** [comment]
related #16441

**Comment by luotao1** [comment]
Close due to #16441 is merged.
