### ISSUE TITLE
离线安装方案

### ISSUE THREAD

**Issue by wangvince** [PaddlePaddle/Paddle#1622]
我想在离线的环境下安装paddle，但是在下载了paddle后，执行安装脚本时还是需要访问github下载另外几个库。

如果我想完全离线安装，需要怎么操作呢

**Comment by helinwang** [comment]
Docker安装方式可以说是完全离线安装的，只需要下载对应的docker image，就可以立刻跑了，不需要再做其他的工作：https://github.com/PaddlePaddle/Paddle/blob/develop/doc/getstarted/build_and_install/docker_install_cn.rst
