### ISSUE TITLE
希望加入类似tf.gradients的算子用于计算梯度，以支持WGAN

### ISSUE THREAD

**Issue by neverrop** [PaddlePaddle/Paddle#16244]
wgan里需要拿到预测标签对原始输入图像的梯度做为一个惩罚，使网络收敛更快，效果更好，这里要用到类似tf.gradients的算子，希望能尽快支持。

**Comment by gavin1332** [comment]
收到您的建议，我们及时反馈

**Comment by gavin1332** [comment]
python前端目前有获取并应用梯度的一些方法：
https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/fluid/optimizer.py#L404
不知能否解决你的问题？

**Comment by qingqing01** [comment]
这个问题属于backward of backward问题，我们跟下这个需求~

**Comment by qingqing01** [comment]
已完成，关闭~
