### ISSUE TITLE
安装paddlepaddle报错

### ISSUE THREAD

**Issue by echoKangYL** [PaddlePaddle/Paddle#16241]
windows10操作系统下，按照官方文档中的流程执行命令：
docker pull docker.paddlepaddlehub.com/paddle:0.14.0-centos7-cpu时报错如下：
Error response from daemon: Get https://docker.paddlepaddlehub.com/v2/: EOF
请问大家如何解决呀~
谢谢~

**Comment by gavin1332** [comment]
如果没有历史版本依赖的话，建议使用最新的版本1.3
