### ISSUE TITLE
PaddlePaddle有没有关于图片颜色抖动的API

### ISSUE THREAD

**Issue by yeyupiaoling** [PaddlePaddle/Paddle#16252]
# 环境
 - PaddlePaddle 1.2
 - Ubuntu 16.04
 - Python 3.5

# 问题
有人使用tensorflow编写了以下的一个函数，我猜是针对输入图片进行颜色抖动，从而增强数据的吧。那么PaddlePaddle有没有类似这个的操作呢？
```python
def image_color_distort(inputs):
    inputs = tf.image.random_contrast(inputs, lower=0.5, upper=1.5)
    inputs = tf.image.random_brightness(inputs, max_delta=0.2)
    inputs = tf.image.random_hue(inputs, max_delta=0.2)
    inputs = tf.image.random_saturation(inputs, lower=0.5, upper=1.5)

    return inputs
```

**Comment by qingqing01** [comment]
@yeyupiaoling  PaddlePaddle框架未提供这些，我们一般在Python里做这些扰动操作，可以参考 https://github.com/PaddlePaddle/models/blob/develop/fluid/PaddleCV/image_classification/reader.py#L76  。

**Comment by yeyupiaoling** [comment]
@qingqing01 好的，明白，谢谢青青姐。
