### ISSUE TITLE
PaddlePaddle有没有regularization_losses

### ISSUE THREAD

**Issue by yeyupiaoling** [PaddlePaddle/Paddle#16253]
# 环境
 - PaddlePaddle
 - Ubuntu 16.04
 - Python 3.5

# 问题
在tensorflow中有以下和损失函数，PaddlePaddle是如何获取的呢？
```python
tf.add_n(slim.losses.get_regularization_losses())
```

**Comment by gavin1332** [comment]
暂时没有列举某系列函数的方法，我们会考虑未来提供相关功能支持

**Comment by gavin1332** [comment]
不过参数正则化的方法可以在文档中找到：
http://paddlepaddle.org/documentation/docs/zh/1.3/api_cn/fluid_cn.html#paramattr
regularizer (WeightDecayRegularizer) – 正则因子. 默认为None

**Comment by yeyupiaoling** [comment]
@gavin1332 我说我怎么没找到这个issue，原来是你偷偷关闭了，我连邮件都没收到。

我主要是想复现tensorflow的这个损失函数，其中就需要到这个L2_loss，
```python
L2_loss_op = tf.add_n(slim.losses.get_regularization_losses())

total_loss_op = radio_cls_loss * cls_loss_op + radio_bbox_loss * bbox_loss_op + radio_landmark_loss * landmark_loss_op + L2_loss_op
```

函数的公式：

![image](https://user-images.githubusercontent.com/26297768/54651577-74936780-4aee-11e9-8ee4-8d916069ddff.png)
