### ISSUE TITLE
fluid.layers.space_to_depth问题

### ISSUE THREAD

**Issue by jiangjiajun** [PaddlePaddle/Paddle#16267]
首先, 是给定的文档里面的例子并不能在paddle 1.3版本下运行成功，在搭建网络时就会提示出错
http://paddlepaddle.org/documentation/docs/zh/1.3/api_cn/layers_cn.html#paddle.fluid.layers.space_to_depth
下面是错误提示
```
paddle.fluid.core.EnforceNotMet: Enforce failed. Expected x_dims.size() == 4, but received x_dims.size():5 != 4:4.
input should be a 4D tensor at [/paddle/paddle/fluid/operators/space_to_depth_op.cc:33]
```

其次, 同样的例子，在tensorflow下，用如下代码可以
```
# 输入shape: [-1, 20, 20, 3]
# 输出shape: [-1, 4, 4, 75]
inputs = tf.placeholder(dtype=tf.float32, shape=[None, 20, 20, 3])
result = tf.nn.space_to_depth(inputs, block_size=5)
```
而在PaddlePaddle GPU 1.3版本下，理论上如下代码与上面代码功能一致，但实际上在搭建网络时会出错
```
inputs = fluid.layers.data(dtype='float32', shape=[3, 20, 20], name='inputs')
result = fluid.layers.space_to_depth(inputs, blocksize=5)
```

**Comment by JiabinYang** [comment]
您好，这个文档已经提交修复了 #16293 ，文档中例子出现的问题是因为paddle的data_layer会在第一不是-1的时候append一个-1的维度作为batch_size，而第二个例子不能正常执行是因为paddle的space_to_depth只支持`[batch, channel, height, width]`的layout, 而且channel需要能被block_size的平方整除
