### ISSUE TITLE
About regression_cost

### ISSUE THREAD

**Issue by cactiball** [PaddlePaddle/Paddle#1626]
I have a question about the regression_cost, I did not find enough information about it in the document.

So I have a dataset with 0-1 labels. 1 represent the same, 0 represent different. If I build the network like this:
```
output = tensor_layer(
    a=input1,
    b=input2,
    size=1,
    act=SigmoidActivation(),
)

cost = regression_cost(
        input=output,
        label=lbl,
)
outputs(cost)
```
Is the "output" here represent the probability of "input1 and input2 are the same"?

Thanks!

**Comment by qingqing01** [comment]
@lcy-seso could you help to reply this question?

**Comment by lcy-seso** [comment]
- regression_cost in PaddlePaddle is just mean square error.  regressio_cost = $(t - y)^2$, where $t$ is the true label, and $y$ is the predicted label. 
- output of sigmoid activation is on the interval of [0, 1], but it is not a probability distribution function.
- sigmoid is a cumulative distribution function of logistic distribution.

**Comment by cactiball** [comment]
Thanks!
