### ISSUE TITLE
Total CPU Cores are 50% only utilized

### ISSUE THREAD

**Issue by rajkumard** [PaddlePaddle/Paddle#16279]
Environment : PaddlePaddle Docker Image, nvidia docker. Python 2.7

CPU: 
processor       : 39
vendor_id       : GenuineIntel
cpu family      : 6
model           : 79
model name      : Intel(R) Xeon(R) CPU E5-2630 v4 @ 2.20GHz

Version:
xyz@testdomain:/usr/local/lib/python2.7/dist-packages/paddle/v2# paddle version
PaddlePaddle latest, compiled with
    with_avx: ON
    with_gpu: OFF
    with_mkl: ON
    with_mkldnn: ON
    with_double: OFF
    with_python: ON
    with_rdma: OFF
    with_timer: OFF

Problem: We are able to use only 50% of total logical cpu cores. 
My Investigations:
File we have checked : /usr/local/lib/python2.7/dist-packages/paddle/v2/__init__.py
Function in the above file : "set_env_vars(trainer_count)"
Problem : The logic to set number of threads returns only 50% of the total logical cores.

Please explain whether to use only 50% of the CPU is intentional or it is a bug. If it is intentional please explain the reason behind it.

**Comment by tensor-tang** [comment]
Please print the `paddle.__version__` 
And do you use fluid? or v2?  or could you show us how you write your script. 

The default `executor` only use 1 core. You should use [ParallelExecutor](http://paddlepaddle.org/documentation/docs/zh/1.3/api_cn/fluid_cn.html#parallelexecutor) to run with multi-threads.
