### ISSUE TITLE
关于fluid.unique_name.guard()

### ISSUE THREAD

**Issue by Samhandsome** [PaddlePaddle/Paddle#16271]
我在api文档中没有找到关于这个api的详细介绍，请问可以分享下关于fluid.unique_name.guard()的文档吗？

**Comment by Samhandsome** [comment]
不好意思，我已经找到了相关的文档了。https://blog.csdn.net/qq_41427568/article/details/87375107

**Comment by Xreki** [comment]
您好，我们目前缺乏这个API的文档，感谢您的指出，我们会尽快补上。

**Comment by Samhandsome** [comment]
@Xreki 好的，请补上之后通知我一下，谢谢

**Comment by logicgogh** [comment]
目前最新文档中还是没有unique_name 的相关文档
