### ISSUE TITLE
关于reshape的一些问题？

### ISSUE THREAD

**Issue by yeyupiaoling** [PaddlePaddle/Paddle#16281]
# 环境
 - PaddlePaddle
 - Ubuntu 16.04
 - Python 3.5

# 问题

Tensorflow的

```python
    num_cls_prob = tf.size(cls_prob)
    cls_prob_reshpae = tf.reshape(cls_prob, [num_cls_prob, -1])
    label_int = tf.cast(label_filter_invalid, tf.int32)
```

Paddlepaddle这样两个是否等效？
```python
    num_cls_prob = sum(cls_prob.shape)
    cls_prob_reshpae = fluid.layers.reshape(cls_prob, [-1, num_cls_prob])
    label_int = fluid.layers.cast(label_filter_invalid, dtype='int32')
```

**Comment by Xreki** [comment]
您好，可以将相应var的shape打印出来进行确认。

**Comment by yeyupiaoling** [comment]
@Xreki  打印出来有点区别，因为tensorflow的batch是真实值，PaddlePaddle的是-1

**Comment by Xreki** [comment]
`cls_prob_reshpae`数据实际的shape，应该是`cls_prob数据实际的长度 / num_cls_prob`。可将`cls_prob_reshpae`设置为`Executor.run()`的`fetch_targets`，这样可以打印出实际数据的长度。

或者使用`print` op打印，`print` op API文档：http://paddlepaddle.org/documentation/docs/zh/1.3/api_cn/layers_cn.html#print

**Comment by yeyupiaoling** [comment]
好的，谢谢。
