### ISSUE TITLE
如何进行Variable和numpy数据结构相互转换

### ISSUE THREAD

**Issue by yuanyc06** [PaddlePaddle/Paddle#16285]
请问如何进行paddle.fluid.framework.Variable和numpy数组之间的相互转换？目前网上搜不到任何可行的方法

**Comment by Xreki** [comment]
经线下讨论，用户的实际需求是focal loss，@qingqing01 在https://github.com/PaddlePaddle/Paddle/issues/13947 中给出了用已有op组合的方法。

Paddle 1.3新增了[py_func op](http://paddlepaddle.org/documentation/docs/zh/1.3/api_cn/layers_cn.html#py-func) ，使得用户可以使用 py_func 在Python端注册operator。用户将尝试使用`py_func`解决该问题，参考示例https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/fluid/tests/unittests/test_py_func_op.py

**Comment by LinXiyao** [comment]
但是没有一个可用的便捷方法吗？由Variable得到np.array应该是一个比较通用的需求啊

**Comment by Cauchyzhou** [comment]
+1
还有ndarray转parameters,相比tensorflow这操作太麻烦了，文档也不好找，体验很差
