### ISSUE TITLE
TrainerConfigHelpers会停止支持吗

### ISSUE THREAD

**Issue by wondervictor** [PaddlePaddle/Paddle#1629]
API V2推出后，trainer_config_helpers还会继续支持吗？

**Comment by wondervictor** [comment]
API V2推出后，trainer_config_helpers还会继续支持吗？

**Comment by reyoung** [comment]
@wondervictor 会的。

这两个API在网络配置上形式基本一直，用的也是一套代码。

事实上，我们下周、下下周的工作之一，是将二者完全依赖同一套代码。这样，我们就可以同步更新两套API了。

**Comment by jacquesqiao** [comment]
question answered
