### ISSUE TITLE
LoDTensor创建

### ISSUE THREAD

**Issue by littletomatodonkey** [PaddlePaddle/Paddle#16299]
我在做检测任务时，box_coder的op的一个输入的tensor打印出来如下
![image](https://user-images.githubusercontent.com/14270174/54614585-a0373300-4a97-11e9-84ce-0a8301e7f695.png)

我现在有一个tensor，信息如下
![image](https://user-images.githubusercontent.com/14270174/54614386-46cf0400-4a97-11e9-8008-88f9c67bf415.png)

我想问一下怎么使用下面的tensor生成上面的图中所示的tensor呢（第一个维度是不确定的，不影响，希望下面的变量也具有Lod的属性）？

**Comment by Xreki** [comment]
可以使用`set_recursive_sequence_lengths`设置，例如：

https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/fluid/tests/unittests/test_tensor.py#L95

```
def test_int_lod_tensor(self):
        place = core.CPUPlace()
        scope = core.Scope()
        var_lod = scope.var("test_lod_tensor")
        lod_tensor = var_lod.get_tensor()

        lod_tensor._set_dims([4, 4, 6])
        lod_tensor._alloc_int(place)
        array = numpy.array(lod_tensor)
        array[0, 0, 0] = 3
        array[3, 3, 5] = 10
        lod_tensor.set(array, place)
        lod_tensor.set_recursive_sequence_lengths([[2, 2]])

        lod_v = numpy.array(lod_tensor)
        self.assertTrue(numpy.alltrue(array == lod_v))

        lod = lod_tensor.recursive_sequence_lengths()
        self.assertEqual(2, lod[0][0])
        self.assertEqual(2, lod[0][1])
```

具体请看LoDTensor的文档：http://paddlepaddle.org/documentation/docs/zh/1.3/api_cn/fluid_cn.html#lodtensor
