### ISSUE TITLE
infer时，当先后加载检测和分类两个网络时，分类网络的参数未被load进去

### ISSUE THREAD

**Issue by celineJiang** [PaddlePaddle/Paddle#16291]
- 版本、环境信息：
    1）PaddlePaddle版本：1.3
    2）系统环境：Ubuntu16.04，Python 3.5
- 问题描述：
    由于工程需要，需要先使用ssd256进行检测，再将检测框处的图片裁剪出来输入MobileNet中进行识别。前期二者的训练与验证均为分开进行，若且单独进行infer阶段，均能获得很好的结果。但若将二者串行运行，则MobileNet的模型参数将无法被加载，导致其网络参数随机初始化，使得识别结果出错，由于只有两类，会出现全为1或0的情况。请问这种情况应该如何解决？感谢！
    错误分类的结果输出：
Test-0-score: 0.8182742595672607, class 1
Test-1-score: 0.7910793423652649, class 1
Test-2-score: 0.7845519781112671, class 1
Test-3-score: 0.8314852118492126, class 1
Test-4-score: 0.8375226259231567, class 1
Test-5-score: 0.8246129751205444, class 1
- 重要部分代码：

def infer(data_args, image_path, model_dir): # 检测

    image_shape = [3, 256, 256]
    use_gpu = True

    image = fluid.layers.data(name='detec_image', shape=image_shape, dtype='float32')
    locs, confs, box, box_var = mobile_net(image)
    nmsed_out = fluid.layers.detection_output(
        locs, confs, box, box_var, nms_threshold=cfg.NET.DETOUT.NMS_THRESHOLD)

    place = fluid.CUDAPlace(0) if use_gpu else fluid.CPUPlace()
    exe = fluid.Executor(place)

    if model_dir:
        def if_exist(var):
            return os.path.exists(os.path.join(model_dir, var.name))
        fluid.io.load_vars(exe, model_dir, predicate=if_exist)

    infer_reader = data_provider.infer(data_args, image_path)
    feeder = fluid.DataFeeder(place=place, feed_list=[image])

    data = infer_reader()
    test_program = fluid.default_main_program().clone(for_test=True)
    nmsed_out_v, = exe.run(test_program,
                           feed=feeder.feed([[data]]),
                           fetch_list=[nmsed_out],
                           return_numpy=False)
    nmsed_out_v = np.array(nmsed_out_v)
    draw_bounding_box_on_image(image_path, nmsed_out_v, 0.3, data_args.label_list)

def infer(img_path): # 分类

    class_dim = 2
    use_gpu = True
    pretrained_model = './checkpoints_256/MobileNet_224_1.0/19_0.9617'
    image_shape = [3, 224, 224]

    main_program = fluid.Program()
    startup_program = fluid.Program()
    with fluid.program_guard(main_program=main_program, startup_program=startup_program):
        image = fluid.layers.data(name='classify_image', shape=image_shape, dtype='float32')
        out = MobileNet.net(input=image, class_dim=class_dim)
        fetch_list = [out.name]

        place = fluid.CUDAPlace(0) if use_gpu else fluid.CPUPlace()
        exe = fluid.Executor(place)
        exe.run(fluid.default_startup_program())

        if pretrained_model:
            def if_exist(var):
                return os.path.exists(os.path.join(pretrained_model, var.name))
            fluid.io.load_vars(exe, pretrained_model, main_program=main_program, predicate=if_exist)

        test_batch_size = 1
        test_reader = paddle.batch(reader.test(img_path), batch_size=test_batch_size)
        feeder = fluid.DataFeeder(place=place, feed_list=[image])

        test_program = main_program.clone(for_test=True)

        TOPK = 1
        pred_label = []
        for batch_id, data in enumerate(test_reader()):
            result = exe.run(test_program,
                             fetch_list=fetch_list,
                             feed=feeder.feed(data))
            result = result[0][0]
            pred_label.append(np.argsort(result)[::-1][:TOPK][0])
            print("Test-{0}-score: {1}, class {2}"
                  .format(batch_id, result[pred_label[batch_id]], pred_label[batch_id]))
            sys.stdout.flush()
        return pred_label

**Comment by Xreki** [comment]
> 但若将二者串行运行，则MobileNet的模型参数将无法被加载，导致其网络参数随机初始化，使得识别结果出错，由于只有两类，会出现全为1或0的情况。

你确定是分类模型参数不对吗？你的代码里应该都使用的是默认的scope吧，如果先load ssd，再load mobilenet，很有可能是mobilenet的一些参数覆盖了ssd的参数，导致ssd结果不对，从而mobilenet的结果也就不对了吧？

可尝试先后两次infer在不同的scope里面进行。

https://github.com/PaddlePaddle/Paddle/blob/d3acf680445a7cadd05949a7cc7bbb95a0c82641/python/paddle/fluid/tests/book/test_image_classification.py#L210-L211

**Comment by celineJiang** [comment]
> > 但若将二者串行运行，则MobileNet的模型参数将无法被加载，导致其网络参数随机初始化，使得识别结果出错，由于只有两类，会出现全为1或0的情况。
> 
> 你确定是分类模型参数不对吗？你的代码里应该都使用的是默认的scope吧，如果先load ssd，再load mobilenet，很有可能是mobilenet的一些参数覆盖了ssd的参数，导致ssd结果不对，从而mobilenet的结果也就不对了吧？
> 
> 可尝试先后两次infer在不同的scope里面进行。
> 
> [Paddle/python/paddle/fluid/tests/book/test_image_classification.py](https://github.com/PaddlePaddle/Paddle/blob/d3acf680445a7cadd05949a7cc7bbb95a0c82641/python/paddle/fluid/tests/book/test_image_classification.py#L210-L211)
> 
> Lines 210 to 211 in [d3acf68](/PaddlePaddle/Paddle/commit/d3acf680445a7cadd05949a7cc7bbb95a0c82641)
>  inference_scope = fluid.core.Scope() 
>  with fluid.scope_guard(inference_scope):

因为是检测部分的infer结束后才加载的分类模型，所以我认为是分类的参数有问题。
我尝试了先后使用不同scope的方法，但是结果并没有好转。请问是否使用scope后，只能通过load_inference_model来获取需要run的program？

**Comment by Xreki** [comment]
只需在这里加2行，其他的不用修改：
```python
mobilenet_scope = fluid.core.Scope() 
with fluid.scope_guard(mobilenet_scope):
    with fluid.program_guard(main_program=main_program, startup_program=startup_program):
```

建议先把mobilenet的infer简化一下，可以尝试拿一个确定的测试样本来测试下。

**Comment by celineJiang** [comment]
> 建议先把mobilenet的infer简化一下，可以尝试拿一个确定的测试样本来测试下。

您好，这个错误已经得到解决，方法是在您的基础上增加了一行：
```python
with fluid.program_guard(main_program=main_program, startup_program=startup_program):
    with fluid.unique_name.guard():
```
感谢您的回答与帮忙！
