### ISSUE TITLE
请问gpu版本和dev版本有什么区别吗？为什么AnyQ的README中要求安装的是dev?

### ISSUE THREAD

**Issue by xiaobaiying** [PaddlePaddle/Paddle#16300]
谢谢解答！

**Comment by Xreki** [comment]
PaddlePaddle有多个docker镜像，完整的列表见：
https://hub.docker.com/r/paddlepaddle/paddle/tags

其中`-dev`结尾的为开发镜像，用来从源码编译Paddle，且其中没有预装Paddle。其他镜像皆为产品镜像，其中预装了不同版本不同配置的Paddle，用户可根据需求自取。

请看文档：http://paddlepaddle.org/documentation/docs/zh/1.3/beginners_guide/install/install_Docker.html

AnyQ的`README`最新更新时间为8个月之前，文档内容只能说明，他们当初用的是`-dev`镜像从源码编译的，Paddle在近8个月只能有很多更新，你可以拉取时间最接近的产品镜像使用。
