### ISSUE TITLE
elementwise_add，sum，sums的区别是什么?

### ISSUE THREAD

**Issue by yeyupiaoling** [PaddlePaddle/Paddle#16305]
同样是求和，这三个接口有什么区别呢？还请赐教。

**Comment by shippingwang** [comment]
- elementwise_add 是逐元素相加 输入的是两个tensor

- sum是相加操作 接受一个参数，list中的tensor需要纬度一致

output = layers.sum([input,input2])

![image](https://user-images.githubusercontent.com/13645332/54663408-2432fe80-4b1c-11e9-8617-ce8ca5bfb842.png)

现在sum的doc 容易让人误解的
[sum op](https://github.com/PaddlePaddle/Paddle/blob/release/1.3/python/paddle/fluid/layers/nn.py#L8717)
这种写法并不会有实质操作发生

- sums和sum是一样的 也是相加操作 接受1个参数
![image](https://user-images.githubusercontent.com/13645332/54663465-4b89cb80-4b1c-11e9-9534-ed56a7f287f2.png)
现在接受N个参数但是没有实质操作，可能是bug

- reduce_sum 为常用的求和接口

**Comment by yeyupiaoling** [comment]
@shippingwang 有没有一个广播的操作，如`[[1,2], [3,4]]` 乘一个`[2]`

**Comment by shippingwang** [comment]
elementwise_mul ?

**Comment by yeyupiaoling** [comment]
@shippingwang 应该是，谢谢回答。
