### ISSUE TITLE
centos Paddle tensorRT编译错误

### ISSUE THREAD

**Issue by OliverLPH** [PaddlePaddle/Paddle#16311]
- 版本、环境信息：
    1）PaddlePaddle版本：1.3
    2）CPU：
    3）GPU：无
    4）系统环境：CentOS release 6.3 (Final)
- 编译信息：
     1）本地编译tensor RT
流程根据：https://github.com/PaddlePaddle/FluidDoc/blob/08cb0128b0a0bd0b83e0858d7a3a959e3c98e96d/doc/fluid/advanced_usage/deploy/inference/paddle_tensorrt_infer.md

因为没有GPU，所以执行了
```shell
docker run --name paddle_trt -v $PWD/Paddle:/Paddle -it hub.baidubce.com/paddlepaddle/paddle:latest-dev /bin/bash
```
拉取镜像并在容器中编译。

然后在build文件夹中进行
```shell
# 编译    
make -j
```

遇到了问题，log如下
<img width="1015" alt="9b6a032e2f1d6078d06ba5eb250cdef8" src="https://user-images.githubusercontent.com/14963836/54658347-ee841a80-4b07-11e9-910b-9c69450d96b9.png">

**Comment by OliverLPH** [comment]
报错之后，会自动关闭docker容器和docker服务。

随后重新启动docker，然后运行指令
```
# 生成预测库
make inference_lib_dist -j
```
编译一段时间，随后也会自动关闭docker容器和docker服务

**Comment by NHZlX** [comment]
Hello， TRT是gpu 推理加速引擎，必须在有gpu的环境机器上编译运行。

**Comment by OliverLPH** [comment]
> Hello， TRT是gpu 推理加速引擎，必须在有gpu的机器上编译。

噢噢好滴，我自己没搞清楚。谢谢哈
