### ISSUE TITLE
排序学习(Learning To Rank) 文档失效

### ISSUE THREAD

**Issue by clmtulip** [PaddlePaddle/Paddle#16310]
排序学习(Learning To Rank) http://www.paddlepaddle.org/documentation/models/en/0.14.0/ltr/README.html

该文档中的实现方法和代码链接均失效，希望示例更新到最新fluid版本，谢谢。

**Comment by shanyi15** [comment]
hi，相关文档和代码请在这里查看https://github.com/PaddlePaddle/models/tree/develop/legacy/ltr
旧文档已经不再维护了，未来我们将在官网文档页面中给出”不再维护“的提示~
