### ISSUE TITLE
如何计算给定输入输出下gradient数值并返回

### ISSUE THREAD

**Issue by dubhex** [PaddlePaddle/Paddle#16328]
请问paddle中是否有类似于pytorch中autograd.grad的操作，就是给定输入输出，计算gradient返回。

**Comment by shippingwang** [comment]
没有

**Comment by shippingwang** [comment]
From @qingqing01 :
目前只能通过 https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/fluid/backward.py#L394  append_backward 或者 minimize() 函数给program里添加反向op， 通过Exeuctor执行，得到梯度值

**Comment by dubhex** [comment]
> From @qingqing01 :
> 目前只能通过 https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/fluid/backward.py#L394 append_backward 或者 minimize() 函数给program里添加反向op， 通过Exeuctor执行，得到梯度值

这样计算得到梯度值得同时对网络参数也会有改变吧。现在希望计算得到梯度后和常规的loss一起组成新的loss 反向传播回去更新网络参数。这种需求现在有方法可以满足吗？

**Comment by hjchen2** [comment]
请问是将梯度加到loss里面进行反向计算么？基于静态graph的执行方式貌似很难做到这种用法

**Comment by dubhex** [comment]
> 请问是将梯度加到loss里面进行反向计算么？基于静态graph的执行方式貌似很难做到这种用法

是的，将梯度降到loss里反向计算。在一些cv方面的工作中就需要这样的操作。比如我现在正在复现的AttrGAN，不加入这部分梯度loss，结果还达不到原文的情况。这种操作对很多模型训练还是很重要的，所以希望paddle能够在这方面给与支持，这样paddle也能得到更广泛的应用。

**Comment by qingqing01** [comment]
@dubhex  PaddleGAN已提供AttrGAN模型，请参考，v1.5也提供了fluid.gradients接口，故关闭该Issue。
