### ISSUE TITLE
fluid.layers.hash 报错paddle::operators::HashKerel<>::Compute()

### ISSUE THREAD

**Issue by gongxijun** [PaddlePaddle/Paddle#16321]
比如允许如下代码，会出现 stack trace: ***异常.
eg:
import paddle
import paddle.fluid as fluid
import paddle.fluid.layers as layers
import paddle.fluid.nets as nets
import numpy as np

place = fluid.core.CPUPlace()
titles = fluid.layers.data(name='titles', shape=[1], dtype='int32', lod_level=1)
hash_r = fluid.layers.hash(name='hash_x', input=titles, num_hash=1, hash_size=1000)

exece = fluid.Executor(place)
exece.run(fluid.default_startup_program())  # 网络参数初始化

out = exece.run(feed={'titles': np.array([[4],[7],[5]])}, fetch_list=[hash_r])

print(out)

异常信息：
Aborted at 1553067291 (unix time) try "date -d @1553067291" if you are using GNU date ***
PC: @                0x0 (unknown)
*** SIGSEGV (@0x8) received by PID 95339 (TID 0x10ec645c0) stack trace: ***
    @     0x7fff5ae44b3d _sigtramp
    @        0x1256e1bc2 paddle::operators::HashKerel<>::Compute()
    @        0x1256e1860 _ZNSt3__110__function6__funcIZNK6paddle9framework24OpKernelRegistrarFunctorINS2_8platform8CPUPlaceELb0ELm1EJNS2_9operators9HashKerelIiEENS8_IxEEEEclEPKcSD_iEUlRKNS3_16ExecutionContextEE_NS_9allocatorISH_EEFvSG_EEclESG_
    @        0x1262b6936 paddle::framework::OperatorWithKernel::RunImpl()
    @        0x1262b23b8 paddle::framework::OperatorBase::Run()
    @        0x1252c2380 paddle::framework::Executor::RunPreparedContext()
    @        0x1252c1d68 paddle::framework::Executor::Run()
    @        0x1251df3b4 _ZZN8pybind1112cpp_function10initializeIZN6paddle6pybindL18pybind11_init_coreERNS_6moduleEE4$_90vJRNS2_9framework8ExecutorERKNS7_11ProgramDescEPNS7_5ScopeEibbEJNS_4nameENS_9is_methodENS_7siblingEEEEvOT_PFT0_DpT1_EDpRKT2_ENUlRNS_6detail13function_callEE_8__invokeESV_
    @        0x12519d447 pybind11::cpp_function::dispatcher()
    @        0x105db3297 PyEval_EvalFrameEx
    @        0x105dad8c4 PyEval_EvalCodeEx
    @        0x105db7c0d fast_function
    @        0x105db2f89 PyEval_EvalFrameEx
    @        0x105dad8c4 PyEval_EvalCodeEx
    @        0x105db7c0d fast_function
    @        0x105db2f89 PyEval_EvalFrameEx
    @        0x105dad8c4 PyEval_EvalCodeEx
    @        0x105dad042 PyEval_EvalCode
    @        0x105ddaa7d PyRun_FileExFlags
    @        0x105dda5c0 PyRun_SimpleFileExFlags
    @        0x105df1452 Py_Main

**Comment by velconia** [comment]
这是因为 hash 的输入是带 lod 的，但你没有设置，这里是正确的 demo

```
import paddle
import paddle.fluid as fluid
import paddle.fluid.core as core
import paddle.fluid.layers as layers
import paddle.fluid.nets as nets
import numpy as np

place = fluid.core.CPUPlace()

titles = fluid.layers.data(name='titles', shape=[1], dtype='int32', lod_level=1)
hash_r = fluid.layers.hash(name='hash_x', input=titles, num_hash=1, hash_size=1000)

exece = fluid.Executor(place)
exece.run(fluid.default_startup_program()) 

tensor = core.LoDTensor() 
## 初始化 Tensor
tensor.set(np.random.randint(0, 10, (3, 1)).astype("int32"), place)
## 设置LoD信息
tensor.set_recursive_sequence_lengths([[1, 1, 1]])

out = exece.run(feed={'titles': tensor}, fetch_list=[hash_r], return_numpy=False)

print(np.array(out[0]))
```
