### ISSUE TITLE
c++调用paddlepaddle多线程出core

### ISSUE THREAD

**Issue by yuyy0823** [PaddlePaddle/Paddle#16335]
c++调用paddlepaddle进行预测时，qps设为1是正常的，超过1就会出core。
c++调用的paddlepaddle版本信息为：
![image](https://user-images.githubusercontent.com/28800753/54730442-f30e0900-4bc3-11e9-8a57-7765a8c9e3d3.png)

core信息显示错误在调用paddlepaddle的run方法：
![image](https://user-images.githubusercontent.com/28800753/54730853-0de17d00-4bc6-11e9-9f0f-f0e9762b16f8.png)

c++调用paddlepaddle代码如下：
![image](https://user-images.githubusercontent.com/28800753/54730716-63695a00-4bc5-11e9-9222-e8683aba9b04.png)

帮忙看看这是什么问题呢，怎么解决？

**Comment by heavengate** [comment]
export MKL_NUM_THREADS=1
export OMP_NUM_THREADS=1
试试加下这两个环境变量

**Comment by yuyy0823** [comment]
> export MKL_NUM_THREADS=1
> export OMP_NUM_THREADS=1
> 试试加下这两个环境变量

试了，还是会出core

**Comment by heavengate** [comment]
Paddle predict 库里没有多线程的实现，当上游服务并发时，需要用户起多个预测服务，参考http://paddlepaddle.org/documentation/docs/zh/1.3/advanced_usage/deploy/inference/native_infer.html
