### ISSUE TITLE
rank_loss 返回值是空

### ISSUE THREAD

**Issue by clmtulip** [PaddlePaddle/Paddle#16343]
建立issue时，为快速解决问题，请您根据使用情况给出如下信息：
- 传入rank_loss的参数都正常，但是rank_loss的结果为空

![image](https://user-images.githubusercontent.com/1183026/54736220-11d0c780-4be5-11e9-8761-fb214b02a6f5.png)
![image](https://user-images.githubusercontent.com/1183026/54736227-2319d400-4be5-11e9-9165-b9d4a3c811e4.png)
![Uploading image.png…]()

**Comment by heavengate** [comment]
看你Print出来的信息，lefts_score里面没有数据，right_score里面有[16, 1]的数据，麻烦确认一下是不是前面网络输出有问题

**Comment by clmtulip** [comment]
![image](https://user-images.githubusercontent.com/1183026/54737998-52344380-4bed-11e9-8869-3b5ccaf8fc90.png)

**Comment by heavengate** [comment]
代码没看出什么问题，可以确认一下image_left, image_right feed进来的数据格式是否正确

**Comment by heavengate** [comment]
定位为，train.py后续代码有误，程序异常退出，Print还没输出出来

**Comment by clmtulip** [comment]
果然是数据的问题，我的训练数据太少了，batch_size 设的8，数据也是8；py_reader会缓存，在跑第一个iter的时候后面几个iter的数据都已经读进来了，这个时候没数据就会有EOFexception
