### ISSUE TITLE
int8模型预测失败

### ISSUE THREAD

**Issue by Hub-er** [PaddlePaddle/Paddle#16345]
- 版本、环境信息：

1）PaddlePaddle版本：请提供您的PaddlePaddle版本号（如1.1）或CommitID
$ pip list |grep paddle
paddlepaddle (1.2.1)

2）CPU：
processor       : 0
vendor_id       : GenuineIntel
cpu family      : 6
model           : 63
model name      : Intel(R) Xeon(R) CPU E5-2620 v3 @ 2.40GH

3）系统环境：
 cat /etc/redhat-release
CentOS release 6.3 (Final)

-预测信息

1）预测库来源：pip 安装
2）错误栈信息：
Traceback (most recent call last):
  File "infer_batch.py", line 224, in <module>
    infer()
  File "infer_batch.py", line 159, in infer
    infer_method_1(bin_data, outFile[0])
  File "infer_batch.py", line 115, in infer_method_1
    fetch_list=fetch_targets, return_numpy=False)
  File "/home/wangwei/.jumbo/lib/python2.7/site-packages/paddle/fluid/executor.py", line 472, in run
    self.executor.run(program.desc, scope, 0, True, True)
paddle.fluid.core.EnforceNotMet: Enforce failed. Expected input_data_type == filter_data_type, but received input_data_type:5 != filter_data_type:21.
input and filter data type should be consistent at [/paddle/paddle/fluid/operators/conv_op.cc:98]
PaddlePaddle Call Stacks: 
0       0x7f0b89942852p paddle::platform::EnforceNotMet::EnforceNotMet(std::__exception_ptr::exception_ptr, char const*, int) + 482
1       0x7f0b89cfa3c5p paddle::operators::ConvOp::GetExpectedKernelType(paddle::framework::ExecutionContext const&) const + 1045
2       0x7f0b8a680ccfp paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&) const + 239
3       0x7f0b8a67ce90p paddle::framework::OperatorBase::Run(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&) + 224
4       0x7f0b89a05c77p paddle::framework::Executor::RunPreparedContext(paddle::framework::ExecutorPrepareContext*, paddle::framework::Scope*, bool, bool, bool) + 247
5       0x7f0b89a066e5p paddle::framework::Executor::Run(paddle::framework::ProgramDesc const&, paddle::framework::Scope*, int, bool, bool) + 117
6       0x7f0b89931682p
7       0x7f0b89978ae5p
8       0x7f0ba6a1d414p PyEval_EvalFrameEx + 25956
9       0x7f0ba6a1e160p PyEval_EvalCodeEx + 2240
10      0x7f0ba6a1c4d1p PyEval_EvalFrameEx + 22049
11      0x7f0ba6a1cc86p PyEval_EvalFrameEx + 24022
12      0x7f0ba6a1cc86p PyEval_EvalFrameEx + 24022
13      0x7f0ba6a1e160p PyEval_EvalCodeEx + 2240
14      0x7f0ba6a1e272p PyEval_EvalCode + 50
15      0x7f0ba6a3865cp
16      0x7f0ba6a38730p PyRun_FileExFlags + 144
17      0x7f0ba6a39c3cp PyRun_SimpleFileExFlags + 220
18      0x7f0ba6a4b4fcp Py_Main + 3164
19      0x7f0ba5c8892dp __libc_start_main + 253
20            0x400699p

- 问题描述：请详细描述您的问题，同步贴出报错信息、日志/代码关键片段

def infer(input, save_dirname=None):
    place = fluid.CPUPlace()
    exe = fluid.Executor(place)
    inference_scope = fluid.core.Scope()

    # 从模型中获取预测程序、输入数据名称列表、分类器
    [inference_program, feed_target_names, fetch_targets] = \
                fluid.io.load_inference_model(save_dirname, exe)
 
    results = exe.run(inference_program,
            feed={feed_target_names[0]: input},
            fetch_list=fetch_targets, return_numpy=False)

**Comment by heavengate** [comment]
报错原因是网络定义和实际数据输入一个int8类型，一个是float32类型，类型不匹配，请修改输入和网络配置的数据类型一致

**Comment by Hub-er** [comment]
问题已解决：
paddle定点工具输出float，int8，mobile三种不同场景的模型，实际情况是paddle应该加载float中的模型，而我给它加载的是int8模型，所以导致错误！

**Comment by WangTaoSpace** [comment]
> 问题已解决：
> paddle定点工具输出float，int8，mobile三种不同场景的模型，实际情况是paddle应该加载float中的模型，而我给它加载的是int8模型，所以导致错误！

您好，我在windows上float，int8，mobile中输出的模型是俩个文件，model和weights，无法加载。是我的执行错误了吗？
