### ISSUE TITLE
线上热加载模型时候出现如图错误

### ISSUE THREAD

**Issue by HaoMoney** [PaddlePaddle/Paddle#16349]
- 版本、环境信息：
    1）PaddlePaddle版本：0.10.0
    4）系统环境：Mac OS 10.13.6
![image](https://user-images.githubusercontent.com/23650773/54738459-5d886e80-4bef-11e9-855b-996c72339cbc.png)
图片中duration-data/model中主要是模型解压后的参数。

**Comment by heavengate** [comment]
麻烦贴一下代码

**Comment by HaoMoney** [comment]
> 麻烦贴一下代码

具体什么代码，是模型结构代码，还是线上预测加载模型的吗

**Comment by heavengate** [comment]
Paddle 0.10.0 已经不维护了，建议在官网下载最新版本Paddle, http://paddlepaddle.org/documentation/docs/zh/1.3/beginners_guide/install/index_cn.html
