### ISSUE TITLE
关于fluid.layers.anchor_generator中stride的问题

### ISSUE THREAD

**Issue by SunAhong1993** [PaddlePaddle/Paddle#16358]
```
import paddle.fluid as fluid
conv1 = fluid.layers.data(dtype='float32', shape=[3,256,256], name='conv1')
anchor_var = fluid.layers.anchor_generator(
input=conv1,
anchor_sizes=[64, 128, 256, 512],
aspect_ratios=[0.5, 1.0, 2.0],
variance=[0.1, 0.1, 0.2, 0.2],
stride=[2.0, 2.0],
offset=0.5)
import numpy as np
data = np.random.rand(10,3,256,256).astype('float32')
exe = fluid.Executor(fluid.CPUPlace())
exe.run(fluid.default_startup_program())
res = exe.run(fluid.default_main_program(), feed={'conv1':data}, fetch_list=anchor_var)
print(res[1].shape)
```
当使用上述代码，因为步长设置为2了，输出的shape不应该是[128,128,12,4]吗？但是输出为[256,256,12,4]。同时发现不管stride设置为什么值，其输出结果不变。

**Comment by heavengate** [comment]
anchor_generator中input shape为[N, C, H, W]时，输出shape为[H, W, X, 4]，每个feature map点生成X个anchor，stride并不是指像素点的stride，而是指anchor中心点在H和W方向上的stride，例如sitrde=[8, 16], 假设像素点[0, 0]处生成的anchor中心点在[0, 0]，则像素点[0, 1]处生成的anchor中心点在[0, 16], 像素点[1, 1]处生成的anchor中心点在[8, 16]
![MacHi 2019-03-21 19-27-52](https://user-images.githubusercontent.com/12605721/54749508-bc5de000-4c0f-11e9-918c-bed4b77b56b2.png)
