### ISSUE TITLE
Tensor.set 输入值和输出值有diff

### ISSUE THREAD

**Issue by jerrywgz** [PaddlePaddle/Paddle#16355]
![image](https://user-images.githubusercontent.com/22989727/54742794-4e102200-4bfd-11e9-9297-d8b304024bd2.png)
通过加载pytorch权重初始化paddle权重的过程中，发现加载的pytorch权重和set到paddle中的权重不一致，place使用cpu，gpu都有这种情况
![image](https://user-images.githubusercontent.com/22989727/54742931-afd08c00-4bfd-11e9-8c57-23a0ee652887.png)

**Comment by junjun315** [comment]
应该是在读入数据时有精度转换。需要在写入来源数据之前指定相同数据类型，读取时指定数据类型再进行set操作
