### ISSUE TITLE
不训练的情况下保存模型报错

### ISSUE THREAD

**Issue by snowsteper** [PaddlePaddle/Paddle#16363]
RT，希望在不训练的情况下存储模型，遇到报错
paddle.fluid.core.EnforceNotMet: holder_ should not be null
Tensor not initialized yet when Tensor::type() is called. at [/paddle/paddle/fluid/framework/tensor.h:141]

代码如下：
```
score = network(char_dict_dim=char_dict_num, word_dict_dim=word_dict_num, class_dim=class_num)
score.persistable = True

# Program
main_program = fluid.default_main_program()
start_program = fluid.default_startup_program()

# Executor
exe = fluid.Executor(place)
exe.run(start_program)

# model_name = model_name_prefix + "_pass_%04d" % pass_num
# model_path = os.path.join(model_dir, model_name)
# fluid.io.load_params(exe, model_path, main_program=main_program, filename=None)

feeded_var_names = ["query_char_data", "query_basic_data", "query_phrase_data",
                    "title_char_data", "title_basic_data", "title_phrase_data"]

target_vars = [score]
fluid.io.save_inference_model(dirname=save_model_dir,
                              model_filename=save_model_name,
                              feeded_var_names=feeded_var_names,
                              target_vars=target_vars,
                              executor=exe,
                              main_program=main_program)
```

更新一下：
我的实际需求是这样，
有一个训好的网络A，结构是 data_layer -> nets_A
我想加一路数据输入，但是对于两路输入中间nets的参数是共享的，都用训好网络A的参数，也就是网络B的结构是：
data_layer_1 -> nets_A(用网络A的参数)
data_layer_2 -> nets_A(用网络A的参数)
也就是说，除了输入以外，中间计算的所有需要训练的参数都复用A的参数

最终，我想通过先加载再保存的方式得到model.conf以及对应的正确的参数

**Comment by heavengate** [comment]
是因为你权重还没有初始化就要保存，所以报这个，确实需求这种场景的话可以使用save_params和load_params这组API试下

**Comment by imistyrain** [comment]
你应该加载预训练的参数，特别的，现在的加载并不会给你返回加载失败的信息，所以务必确认预训练目录存在且能正常加载
```
    place = fluid.CUDAPlace(0) if args.use_gpu else fluid.CPUPlace()
    exe = fluid.Executor(place)
    model_dir=args.pretrained_model_dir
    def if_exist(var):
        return os.path.exists(os.path.join(model_dir, var.name))
    test_prog = fluid.default_main_program().clone(for_test=True)
    fluid.io.load_vars(
        exe, model_dir, main_program=test_prog, predicate=if_exist)
    fluid.io.save_inference_model(model_dir+"-fluid",[image.name],[outop_name],exe,test_prog,
            model_filename=None,params_filename="params")
```

**Comment by snowsteper** [comment]
> 是因为你权重还没有初始化就要保存，所以报这个，确实需求这种场景的话可以使用save_params和load_params这组API试下

如果先load_params，然后直接运行save_params，同样会报
paddle.fluid.core.EnforceNotMet: holder_ should not be null
Tensor not initialized yet when Tensor::type() is called. at [/paddle/paddle/fluid/framework/tensor.h:141]

然后用这种方式保存的模型是没有model.conf的，有点不符合需求

不知道理解的对不对
```
exe = fluid.Executor(place)
exe.run(start_program)
```
之后就应该已经初始化参数了

**Comment by snowsteper** [comment]
> 你应该加载预训练的参数，特别的，现在的加载并不会给你返回加载失败的信息，所以务必确认预训练目录存在且能正常加载
> 
> ```
>     place = fluid.CUDAPlace(0) if args.use_gpu else fluid.CPUPlace()
>     exe = fluid.Executor(place)
>     model_dir=args.pretrained_model_dir
>     def if_exist(var):
>         return os.path.exists(os.path.join(model_dir, var.name))
>     test_prog = fluid.default_main_program().clone(for_test=True)
>     fluid.io.load_vars(
>         exe, model_dir, main_program=test_prog, predicate=if_exist)
>     fluid.io.save_inference_model(model_dir+"-fluid",[image.name],[outop_name],exe,test_prog,
>             model_filename=None,params_filename="params")
> ```

我的实际需求是这样，
有一个训好的网络A，结构是 data_layer -> nets_A
我想加一路数据输入，但是对于两路输入中间nets的参数是共享的，都用训好网络A的参数，也就是网络B的结构是：
data_layer_1 -> nets_A(用网络A的参数)
data_layer_2 -> nets_A(用网络A的参数)
也就是说，除了输入以外，中间计算的所有需要训练的参数都复用A的参数
最终，我想通过先加载再保存的方式得到model.conf以及对应的正确的参数

利用fluid.io.load_vars方法加载参数，会提示输入层的名称与原来网络不一致

**Comment by hjchen2** [comment]
`score.persistable = True`
请问为什么要将score设置为persistable var？另外可以尝试在load_vars接口中指定需要load的variables

**Comment by snowsteper** [comment]
> `score.persistable = True`
> 请问为什么要将score设置为persistable var？另外可以尝试在load_vars接口中指定需要load的variables

load_var这个接口加载部分变量还是会报错，
paddle.fluid.core.EnforceNotMet: holder_ should not be null
Tensor not initialized yet when Tensor::type() is called. at [/paddle/paddle/fluid/framework/tensor.h:141]

实现方法是：
```
var_list = ['_emb_', '_conv_char_2', '_conv_char_3', '_conv_basic_2', '_conv_basic_3', '_conv_phrase_2', '_conv_phrase_3', 'fc_0.w_0', 'fc_0.b_0', 'fc_0.tmp_2',]
def var_name_to_load(var):
    res = var.name in var_list
    return res 
fluid.io.load_vars(exe, model_path, main_program=main_program, vars=None, predicate=var_name_to_load, filename=None)
```
