### ISSUE TITLE
Investigate Solution for Docker Images‘ Pull Operations Very Slowly from China

### ISSUE THREAD

**Issue by gangliao** [PaddlePaddle/Paddle#1636]
目前，国内用户或者开发者想要从docker官方docker hub上docker pull Paddle镜像，会频繁失去连接或者网速过慢等问题。

欢迎大家发挥想象力，提供各种可行的解决方案。

**Comment by gangliao** [comment]
目前，已确定内部其他部门没有提供此类服务，解决不了这个问题。

**Comment by gongweibao** [comment]
# Goals
加速国内的docker image pull的速度  
例如：  
```
docker pull ubuntu
```  
等待时间很长，或者直接拉取不下来

# 方式
1. 推动阡陌云或者百度云开放加速服务：  
百度还没有dockerhub的加速服务，或者对国内用户的docker image 托管的服务。阡陌云只对公司内部。  
  
1. 使用第三方：  **加速效果还没有测试**
第三方的mirror加速服务有:[网易](c.163.com)，阿里云, [daocloud](https://www.daocloud.io/)等，其中网易的加速服务在[这里](https://c.163.com/wiki/index.php？title=DockerHub%E9%95%9C%E5%83%8F%E5%8A%A0%E9%80%9F)  。百度号称有云服务，docker image的加速用第三方、而且在获取方式中明确指出来加速源，这个可能不好看。   


1. 自己搭建和维护：  
可以预见，流量和安全问题将会比较耗费精力，而且不是我们的核心。

**Comment by typhoonzero** [comment]
1. 建立paddle自己的docker registry，用户可以直接`docker pull paddlepaddle.org/paddle:latest`快速的获取到镜像，paddle的docker registry也可以提供docker hub的镜像服务加速其他镜像的访问，比如nginx：
  1. 备案，并部署在国内的服务器上：国内访问速度最快，但可能影响国外开发者
  1. 不备案，部署在阿里云 香港服务器上： 速度相对dockerhub会快不少，网络连接稳定（阿里的机器），网络延迟带宽没有方案1好
1. 使用中转服务器做代理，加速docker hub的访问速度，比如在香港有一台服务器做为HTTP proxy转发请求。
