### ISSUE TITLE
模型训练完多个pass，未见模型保存

### ISSUE THREAD

**Issue by wangsouc** [PaddlePaddle/Paddle#1637]
【内网环境】在mpi多机场景下训练模型，第1个pass保存了模型，2-4个pass没有保存模型。是配置有错嘛？模型小流量实验中，急求更新，求指导！

提交的配置如下：
paddle cluster_train \
  --config=job_config.py \
  --use_gpu=cpu \
  --num_nodes=140 \
  --num_passes=10 \
  --log_period=100 \
  --trainer_count=4 \
  --saving_period=10 \
  --thirdparty=./thirdparty \
  --job_name=xxx \
  --time_limit=99:29:00 \
  --submitter=wangsijiang01 \
  --where=xxx \
  --config_args=is_local=0 \
  --show_parameter_stats_period=10

【日志 pass-0000】：
I0317 17:25:11.942836  4302 TrainerInternal.cpp:207] _output.wbias        avg_abs_val=0.233802    max_val=0.233811    avg_abs_grad=2.58522     max_grad=2.58522    
I0317 17:26:12.388079  4302 TrainerInternal.cpp:182]  Pass=0 Batch=9322 samples=19090609 AvgCost=0.13207 Eval: __auc_evaluator_0__=0.67317 classification_error_evaluator=0.0311735 
I0317 17:26:57.727107  4302 Tester.cpp:127]  Test samples=189060 cost=0.119063 Eval: __auc_evaluator_0__=0.690291 classification_error_evaluator=0.027605 
I0317 17:26:57.827801  4302 GradientMachine.cpp:112] Saving parameters to ./output/pass-00000
I0317 17:26:57.870573  4302 Util.cpp:230] copy conf/trainer_config.conf to ./output/pass-00000
I0317 17:27:46.176511  4302 TrainerInternal.cpp:207] ___embedding_0__.w0  avg_abs_val=0.0724354   max_val=0.825412    avg_abs_grad=0.00269223  max_grad=0.370669

【日志pass-00001】:
I0317 22:29:13.901273  4302 TrainerInternal.cpp:207] _output.wbias        avg_abs_val=0.470885    max_val=0.470908    avg_abs_grad=1.44517     max_grad=1.44517    
I0317 22:30:10.752303  4302 TrainerInternal.cpp:182]  Pass=1 Batch=9322 samples=19090609 AvgCost=0.131351 Eval: __auc_evaluator_0__=0.680867 classification_error_evaluator=0.0311343 
I0317 22:30:58.895789  4302 Tester.cpp:127]  Test samples=189060 cost=0.119017 Eval: __auc_evaluator_0__=0.690198 classification_error_evaluator=0.027605 
I0317 22:31:59.908869  4302 TrainerInternal.cpp:207] ___embedding_0__.w0  avg_abs_val=0.0734578   max_val=1.01699     avg_abs_grad=0.00248179  max_grad=0.459645

**Comment by jacquesqiao** [comment]
saving_period 改成1 试试
