### ISSUE TITLE
Installation of paddlepaddle-gpu does not work on NVIDIA RTX 2080TI

### ISSUE THREAD

**Issue by AmitRozner** [PaddlePaddle/Paddle#16370]
- PaddlePaddle version 1.3.1
- GPU: Nvidia RTX 2080TI
- OS Platform Ubuntu MATE 1.12.1
- Python version 3.5.2
- Install method: pip install paddlepaddle-gpu
- CUDA 9.0 cuDNN 7.3.1

**nvcc -V**
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2017 NVIDIA Corporation
Built on Fri_Sep__1_21:08:03_CDT_2017
Cuda compilation tools, release 9.0, V9.0.176

**nvidia-smi**
Thu Mar 21 10:06:22 2019       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 410.78       Driver Version: 410.78       CUDA Version: 10.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce RTX 208...  Off  | 00000000:01:00.0  On |                  N/A |
| 35%   29C    P8    14W / 260W |    143MiB / 10986MiB |      1%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0      1073      G   /usr/lib/xorg/Xorg                           118MiB |
|    0     11958      G   /opt/teamviewer/tv_bin/TeamViewer             23MiB |
+-----------------------------------------------------------------------------+

**When I load inference model and try to infer I get the following error:**
`C++ Callstacks: 
CUDNN_STATUS_EXECUTION_FAILED at [/paddle/paddle/fluid/operators/conv_cudnn_op.cu.cc:244]
PaddlePaddle Call Stacks: 
0       0x7fe91743c8bdp void paddle::platform::EnforceNotMet::Init<std::string>(std::string, char const*, int) + 365
1       0x7fe91743cc07p paddle::platform::EnforceNotMet::EnforceNotMet(std::string const&, char const*, int) + 87
2       0x7fe917b11d61p paddle::operators::CUDNNConvOpKernel<float>::Compute(paddle::framework::ExecutionContext const&) const + 5169
3       0x7fe917b12473p std::_Function_handler<void (paddle::framework::ExecutionContext const&), paddle::framework::OpKernelRegistrarFunctor<paddle::platform::CUDAPlace, false, 0ul, paddle::operators::CUDNNConvOpKernel<float>, paddle::operators::CUDNNConvOpKernel<double>, paddle::operators::CUDNNConvOpKernel<paddle::platform::float16> >::operator()(char const*, char const*, int) const::{lambda(paddle::framework::ExecutionContext const&)#1}>::_M_invoke(std::_Any_data const&, paddle::framework::ExecutionContext const&) + 35
4       0x7fe918e50e53p paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&) const + 659
5       0x7fe918e4e6c5p paddle::framework::OperatorBase::Run(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&) + 341
6       0x7fe917558e4ap paddle::framework::Executor::RunPreparedContext(paddle::framework::ExecutorPrepareContext*, paddle::framework::Scope*, bool, bool, bool) + 218
7       0x7fe91755ae45p paddle::framework::Executor::Run(paddle::framework::ProgramDesc const&, paddle::framework::Scope*, int, bool, bool) + 261
8       0x7fe917420a2bp
9       0x7fe91746774ep
10            0x4ea137p PyCFunction_Call + 119
11            0x53c176p PyEval_EvalFrameEx + 23030
12            0x53fc97p
13            0x53bc93p PyEval_EvalFrameEx + 21779
14            0x53fc97p
15            0x53b83fp PyEval_EvalFrameEx + 20671
16            0x53b294p PyEval_EvalFrameEx + 19220
17            0x53b294p PyEval_EvalFrameEx + 19220
18            0x53b294p PyEval_EvalFrameEx + 19220
19            0x53b294p PyEval_EvalFrameEx + 19220
20            0x53b294p PyEval_EvalFrameEx + 19220
21            0x53fc97p
22            0x5409bfp PyEval_EvalCode + 31
23            0x60cb42p
24            0x60efeap PyRun_FileExFlags + 154
25            0x60f7dcp PyRun_SimpleFileExFlags + 444
26            0x640256p Py_Main + 1110
27            0x4d0001p main + 225
28      0x7fe9db667830p __libc_start_main + 240
29            0x5d6999p _start + 41
`

I also tried to install paddlepaddle from source but also could not.

**Comment by heavengate** [comment]
1. you can try pip install paddlepaddle-gpu==1.3.1.post97 for CUDA9 and CUDNN7
2.  install paddlepaddle from source: did you specified CUDA and CUDNN path

**Comment by AmitRozner** [comment]
1. This is what I did and it still does not work.
2. I did not specify the paths

**Comment by AmitRozner** [comment]
Build from source:
**Tried to specify the CUDA path using:**
`cmake .. -DPY_VERSION=3.5 -DWITH_FLUID_ONLY=ON -DWITH_GPU=ON -DWITH_TESTING=OFF -DCMAKE_BUILD_TYPE=Release -DCUDA_TOOLKIT_ROOT_DIR=/usr/local/cuda`

**Still getting the same error:**
```
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

HEAD is now at 9a42ec1... changed typedef to using
[  3%] No patch step for 'extern_threadpool'
[  3%] No update step for 'extern_threadpool'
[  4%] No configure step for 'extern_threadpool'
[  4%] No build step for 'extern_threadpool'
[  4%] No install step for 'extern_threadpool'
[  4%] No test step for 'extern_threadpool'
[  4%] Completed 'extern_threadpool'
[  4%] Built target extern_threadpool
Scanning dependencies of target enforce
[  4%] Building CXX object paddle/fluid/platform/CMakeFiles/enforce.dir/enforce.cc.o
In file included from ..../Paddle/paddle/fluid/platform/enforce.h:46:0,
                 from ..../Paddle/paddle/fluid/platform/enforce.cc:15:
..../Paddle/paddle/fluid/platform/dynload/nccl.h:16:18: fatal error: nccl.h: No such file or directory
compilation terminated.
paddle/fluid/platform/CMakeFiles/enforce.dir/build.make:62: recipe for target 'paddle/fluid/platform/CMakeFiles/enforce.dir/enforce.cc.o' failed
make[2]: *** [paddle/fluid/platform/CMakeFiles/enforce.dir/enforce.cc.o] Error 1
CMakeFiles/Makefile2:3217: recipe for target 'paddle/fluid/platform/CMakeFiles/enforce.dir/all' failed
make[1]: *** [paddle/fluid/platform/CMakeFiles/enforce.dir/all] Error 2
Makefile:149: recipe for target 'all' failed
make: *** [all] Error 2
```

The file nccl.h exists and the user has full permissions to it. I still get **No such file or directory** error.

**Comment by JiabinYang** [comment]
looks like you haven't installed nccl2, plz install nccl2 before trying to compile paddle

**Comment by yeyupiaoling** [comment]
@AmitRozner Hi， I think you must use CUDA 10. Because RTX 2080 only can run no CUDA.

**Comment by AmitRozner** [comment]
@JiabinYang I Installed nccl2 again and it is now stuck at a later stage but still cannot compile:
`[ 83%] Generating paddle_fluid.dir/smooth_l1_loss_op.objdir
[ 83%] Generating paddle_fluid.dir/paddle_fluid_api.objdir
[ 83%] Generating paddle_fluid.dir/analysis_predictor.objdir
[ 83%] Building C object paddle/fluid/inference/CMakeFiles/paddle_fluid.dir/paddle_fluid_dummy.c.o
[ 83%] Linking CXX static library libpaddle_fluid.a
[100%] Built target paddle_fluid
[100%] Linking CXX shared library libpaddle_pybind.so
[100%] Built target paddle_pybind
Makefile:149: recipe for target 'all' failed
make: *** [all] Error 2
`
@yeyupiaoling Tensorflow and Pytorch seem to work fine with the CUDA 9.0 on 2080TI. Are you sure I have to upgrade the CUDA?

**Comment by AmitRozner** [comment]
**This is the full error when running j1:**
`
[ 43%] Linking CXX shared library libpaddle_fluid.so
/usr/bin/ld: cannot find ../platform/libcpu_info.a: Too many open files
/usr/bin/ld: cannot find ../memory/allocation/libcuda_allocator.a: Too many open files
/usr/bin/ld: cannot find ../memory/allocation/libretry_allocator.a: Too many open files
/usr/bin/ld: cannot find ../memory/allocation/libpinned_allocator.a: Too many open files
/usr/bin/ld: cannot find ../memory/allocation/libaligned_allocator.a: Too many open files
/usr/bin/ld: cannot find ../memory/allocation/libauto_increment_allocator.a: Too many open files
/usr/bin/ld: cannot find ../memory/allocation/libzero_size_allocator.a: Too many open files
/usr/bin/ld: cannot find ../memory/allocation/libconditional_allocator.a: Too many open files
/usr/bin/ld: cannot find ../memory/allocation/liballocator.a: Too many open files
/usr/bin/ld: cannot find ../memory/allocation/liballocator_strategy.a: Too many open files
/usr/bin/ld: cannot find ../platform/libcuda_device_guard.a: Too many open files
/usr/bin/ld: cannot find ../platform/libgpu_info.a: Too many open files
/usr/bin/ld: cannot find ../platform/libplace.a: Too many open files
/usr/bin/ld: cannot find ../platform/libenforce.a: Too many open files
/usr/bin/ld: cannot find /usr/local/cuda/lib64/libcudart_static.a: Too many open files
/usr/bin/ld: cannot find -ldl
/usr/bin/ld: cannot find -lrt
/usr/bin/ld: cannot find ../../../libboost.a: Too many open files
/usr/bin/ld: cannot find ../framework/libversion.a: Too many open files
/usr/bin/ld: cannot find ../recordio/librecordio.a: Too many open files
/usr/bin/ld: cannot find ../recordio/libchunk.a: Too many open files
/usr/bin/ld: cannot find ../recordio/libheader.a: Too many open files
/usr/bin/ld: cannot find ../../../third_party/install/zlib/lib/libz.a: Too many open files
/usr/bin/ld: cannot find ../../../third_party/install/snappy_stream/lib/libsnappystream.a: Too many open files
/usr/bin/ld: cannot find ../../../third_party/install/snappy/lib/libsnappy.a: Too many open files
/usr/bin/ld: cannot find ../../../third_party/install/glog/lib/libglog.a: Too many open files
/usr/bin/ld: cannot find ../../../third_party/install/gflags/lib/libgflags.a: Too many open files
/usr/bin/ld: cannot find -lpthread
/usr/bin/ld: cannot find -lstdc++
/usr/bin/ld: cannot find -lm
/usr/bin/ld: cannot find -lgcc_s
/usr/bin/ld: cannot find -lc
/usr/bin/ld: cannot find -lgcc_s
/usr/bin/ld: cannot find /usr/lib/gcc/x86_64-linux-gnu/5/crtendS.o: Too many open files
/usr/bin/ld: cannot find /usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/crtn.o: Too many open files
collect2: error: ld returned 1 exit status
paddle/fluid/inference/CMakeFiles/paddle_fluid_shared.dir/build.make:1117: recipe for target 'paddle/fluid/inference/libpaddle_fluid.so' failed
make[2]: *** [paddle/fluid/inference/libpaddle_fluid.so] Error 1
CMakeFiles/Makefile2:51230: recipe for target 'paddle/fluid/inference/CMakeFiles/paddle_fluid_shared.dir/all' failed
make[1]: *** [paddle/fluid/inference/CMakeFiles/paddle_fluid_shared.dir/all] Error 2
Makefile:149: recipe for target 'all' failed
make: *** [all] Error 2
`

**Comment by yeyupiaoling** [comment]
@AmitRozner 
>Tensorflow and Pytorch seem to work fine with the CUDA 9.0 on 2080TI. Are you sure I have to upgrade the CUDA?

Yes, I sure. My GPU is 2070. I think they ara the same. 

When I use CUDA 9.0, PaddlePaddle will report errors: CUDNN_STATUS_EXECUTION_FAILED.

>I Installed nccl2 again and it is now stuck at a later stage but still cannot compile:

You can try using docker : https://blog.csdn.net/qq_33200967/article/details/83052060#UbuntuDocker_233

**Comment by AmitRozner** [comment]
@yeyupiaoling The pip install works with CUDA 10.0. Thanks for the tips.
