### ISSUE TITLE
使用DistributeTranspiler将Program转成分布式执行后，整个program无法执行

### ISSUE THREAD

**Issue by hjchen2** [PaddlePaddle/Paddle#16381]
请教下，原有的Program在本地可以边训练边test，使用了DistributeTranspiler将Program转成分布式执行后，整个program无法执行，这是正常的吗？

**Comment by jacquesqiao** [comment]
> 整个program无法执行

是指？

**Comment by gogogo45** [comment]
fluid1.3版本，大致代码如下，
![image](https://user-images.githubusercontent.com/4569437/54804832-e961cf80-4caf-11e9-8e7b-9020d69141d1.png)
启动方式为在本地启动两个pserver，启动两个trainer
实际执行状况是pserver正常启动，trainer启动后卡住，长时间等待后，报错退出
![image](https://user-images.githubusercontent.com/4569437/54805091-d0a5e980-4cb0-11e9-8955-d26a1b11c6e1.png)

把test_program相关内容全部注释掉后可正常运行

**Comment by jacquesqiao** [comment]
代码不完整，请提供完整代码

**Comment by gogogo45** [comment]
需要全部的可运行代码吗？

**Comment by hjchen2** [comment]
> 需要全部的可运行代码吗？

从你截图的代码中我们看不出具体的问题，如果可以的话，麻烦简化出一个我们这边能复现的完整代码，谢谢。
