### ISSUE TITLE
centos下源码编译安装失败

### ISSUE THREAD

**Issue by JiaXiao243** [PaddlePaddle/Paddle#16429]
- 版本、环境信息：
    1）PaddlePaddle版本：develop分支
    2）CPU：Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz
    3）GPU：cuda9_cudnn7
    4）系统环境：centos6.1、版本、Python版本：python3.5
- 安装方式信息：
1）docker安装
2）docker编译：请提供docker镜像，编译命令            
复现步骤：
1. 下载docker images，sudo docker pull paddlepaddle/paddle_manylinux_devel:cuda9.0_cudnn7 
2. 创建docker 容器，sudo nvidia-docker run --name centos --network host  -v $PWD:/paddle -it  paddlepaddle/paddle_manylinux_devel:cuda9.0_cudnn7  /bin/bash
3. cd /home
export http_proxy=http://172.19.61.250:3128
export https_proxy=http://172.19.61.250:3128
export LD_LIBRARY_PATH=/opt/_internal/cpython-3.5.1/lib/:${LD_LIBRARY_PATH}
export PATH=/opt/_internal/cpython-3.5.1/bin/:${PATH}
export PYTHON_FLAGS="-DPYTHON_EXECUTABLE:FILEPATH=/opt/_internal/cpython-3.5.1/bin/python3.5 -DPYTHON_INCLUDE_DIR:PATH=/opt/_internal/cpython-3.5.1/include/python3.5m -DPYTHON_LIBRARIES:FILEPATH=/opt/_internal/cpython-3.5.1/lib/libpython3.5.so"
export PYTHON_ABI="cp35-cp35m"
export PY_VERSION=3.5
export WITH_FLUID_ONLY=ON
export WITH_GPU=ON
export WITH_INFERENCE=OFF
export WITH_INFERENCE_API_TEST=OFF 
yum -y install python-devel
pip3 install numpy==1.14.0 protobuf==3.1.0 wheel

git clone https://github.com/PaddlePaddle/Paddle.git
cd Paddle
mkdir build 
cd build
cmake .. -DPYTHON_EXECUTABLE:FILEPATH=/opt/_internal/cpython-3.5.1/bin/python3.5 -DPYTHON_INCLUDE_DIR:PATH=/opt/_internal/cpython-3.5.1/include/python3.5m -DPYTHON_LIBRARIES:FILEPATH=/opt/_internal/cpython-3.5.1/lib/libpython3.5.so -DWITH_FLUID_ONLY=ON -DWITH_GPU=ON -DWITH_TESTING=OFF -DCMAKE_BUILD_TYPE=Release
make -j$(nproc)
报错信息如下：
<img width="669" alt="ea604fbda7fea1fd63b1758a8f24bb8d" src="https://user-images.githubusercontent.com/37854899/54902031-2b3e8000-4f13-11e9-8f9a-9881f97af3d4.png">
PS:之前编译安装是成功的，这次开始报错...

**Comment by wopeizl** [comment]
今天的cdn出了问题，厂内访问会出错，所以导致编译错误

**Comment by JiaXiao243** [comment]
请问大概什么时候可以使用源码编译安装呢？

**Comment by wopeizl** [comment]
现在已经修复，请下载最新代码，再build就可以

**Comment by JiaXiao243** [comment]
嗯 可以啦
