### ISSUE TITLE
fluid 使用nce定制custom_dist 负采样概率报错

### ISSUE THREAD

**Issue by PengheLiu** [PaddlePaddle/Paddle#16430]
paddle: 1.3.1   on mac cpu version
直接运行的这个例子。
http://paddlepaddle.org/documentation/docs/zh/1.3/api_cn/layers_cn.html#permalink-110-nce
```
import paddle as paddle
import paddle.fluid as fluid
from paddle.fluid import layers

import numpy as np

window_size = 5
words = []
for i in xrange(window_size):
        words.append(layers.data(
                name='word_{0}'.format(i), shape=[1], dtype='int64'))

dict_size = 10000
label_word = int(window_size / 2) + 1

embs = []
for i in xrange(window_size):
        if i == label_word:
                continue

        emb = layers.embedding(input=words[i], size=[dict_size, 32],
                                                   param_attr='emb.w', is_sparse=True)
        embs.append(emb)

embs = layers.concat(input=embs, axis=1)

#使用custom distribution
dist = fluid.layers.assign(input=np.array([0.05,0.5,0.1,0.3,0.05]).astype("float32"))
loss = layers.nce(input=embs, label=words[label_word],
                          num_total_classes=5, param_attr='nce.w',
                          bias_attr='nce.b',
                          num_neg_samples=3,
                          sampler="custom_dist",
                          custom_dist=dist)
```
![image](https://user-images.githubusercontent.com/7145732/54902639-f3d0d300-4f14-11e9-84fe-6d1eb026aad1.png)

**Comment by seiriosPlus** [comment]
```
dist = fluid.layers.assign(input=np.array([0.05,0.5,0.1,0.3,0.05]).astype("float32"))
```
这行需要更改一下， 现在传一个概率的数组就可以了，如：```[0.05,0.5,0.1,0.3,0.05]```

**Comment by PengheLiu** [comment]
OK，好的，刚实验了下，没有问题，谢谢。
另外想多问一下，如果使用paddlecolud在mpi上训练的话这样是否有问题？

**Comment by seiriosPlus** [comment]
> OK，好的，刚实验了下，没有问题，谢谢。
> 另外想多问一下，如果使用paddlecolud在mpi上训练的话这样是否有问题？

没有问题

**Comment by PengheLiu** [comment]
今天我使用了大的数据集，发现自定义概率数组太大时会报错，我的词表大概是千万到亿级别，我试了下使用1000万的自定义概率集合，nce就会报错，辛苦看下这个该如何解决？

```
dict_size = 10000000
#使用custom distribution
dist = np.random.random(dict_size).astype("float32")
loss = layers.nce(input=embs, label=words[label_word],
                          num_total_classes=dict_size, param_attr='nce.w',
                          bias_attr='nce.b',
                          num_neg_samples=3,
                          sampler="custom_dist",
                          custom_dist=dist)
```
报错信息如下：
  File "test.py", line 44, in <module>
    custom_dist=dist)
  File "/usr/local/anaconda2/lib/python2.7/site-packages/paddle/fluid/layers/nn.py", line 5281, in nce
    np.array(custom_dist).astype('float32'))
  File "/usr/local/anaconda2/lib/python2.7/site-packages/paddle/fluid/layers/nn.py", line 5276, in _init_by_numpy_array
    default_initializer=NumpyArrayInitializer(numpy_array))
  File "/usr/local/anaconda2/lib/python2.7/site-packages/paddle/fluid/layer_helper.py", line 339, in create_parameter
    **attr._to_kwargs(with_initializer=True))
  File "/usr/local/anaconda2/lib/python2.7/site-packages/paddle/fluid/framework.py", line 1300, in create_parameter
    initializer(param, self)
  File "/usr/local/anaconda2/lib/python2.7/site-packages/paddle/fluid/initializer.py", line 753, in __call__
    raise ValueError("The size of input is too big. Please consider "
ValueError: The size of input is too big. Please consider saving it to file and 'load_op' to load it

**Comment by seiriosPlus** [comment]
看了下代码， 现在支持 1024 * 1024 * 5 以下的大小， 试一下这个大小下可不可以？

**Comment by PengheLiu** [comment]
这个大小看起来是可以的，也就是说如果想要使用更大数组的话，目前是没有办法支持的是么? 
看起来现阶段我只能取top 1024*1024*5 作为采样的概率。

**Comment by PengheLiu** [comment]
看起来nce这个定制采样概率没有办法在大数据集上使用了，那训练skip-gram模型的话如果使用nce的这个定制采样概率功能只能允许不同单词个数最大为1024*1024*5么？感觉这样太鸡肋了。

我本来觉得我可以只采样高频的单词，从而让概率数组小一点，但是会报概率数组大小与类别个数不一致的错误。

![image](https://user-images.githubusercontent.com/7145732/54970922-20d9c000-4fbf-11e9-8251-3f548a9f2aa6.png)

**Comment by seiriosPlus** [comment]
我优化一下这个吧
