### ISSUE TITLE
Paddle文档相关疑问

### ISSUE THREAD

**Issue by dayhaha** [PaddlePaddle/Paddle#1643]
Paddle新的文档感觉好像基本上已经完成了，我有以下几个疑问：
1. http://www.paddlepaddle.org/ 官网中点击文档跳转的还是以前的老文档，这个目前的链接不用更新么？还是说新文档还有很多没有完成？
2. 新文档 http://www.paddlepaddle.org/develop/doc/getstarted/index_en.html 最上面一排（Home\Get Started\Documentation)的链接好像还没有加上
3. 加载新文档的时候，cdn.mathjax.org这个模块一直很慢，这个是不是可以放百度的cdn上面，来提高相应速度呢？

**Comment by luotao1** [comment]
1. 官网是根据master分支生成的文档，由于master分支一直没更新，所以官网文档也一直没更新。预计在下次发版本的时候更新。
2. 链接是没加上，原因是：中英文页面的最上面一排都是英文， 之前和 @llxxxll 讨论的是，如果中文页面 http://www.paddlepaddle.org/develop/doc_cn/ 最上面一排也改成中文的话，会有两套设计模板，FE当时没空改。
3. 请 @reyoung 看看是否可行。
