### ISSUE TITLE
集群训练 出现Check failed: 0 == gethostbyname_r 这样的错误，如图所示。

### ISSUE THREAD

**Issue by csdnlzh** [PaddlePaddle/Paddle#1644]
<img width="1246" alt="machi 2017-03-20 12-04-49" src="https://cloud.githubusercontent.com/assets/1267886/24088449/70603d0a-0d65-11e7-8920-17633ef03c1e.png">

**Comment by typhoonzero** [comment]
Sorry for the late reply! Can you please post which version you are using and the command line options?

**Comment by NHZlX** [comment]
I'll close the inactivate issue, and feel free to reopen it.
