### ISSUE TITLE
如何对定长的sequence做完embedding后接Conv2D操作

### ISSUE THREAD

**Issue by phonism** [PaddlePaddle/Paddle#16444]
希望的操作是：embedding后shape是(batch_size, padded_sentence_size, embedding_size)，然后unsqueeze(input, [2])，得到(batch_size, 1, padding_sentence_size, embedding_size)，就可以进行Conv2D了。

但是embedding后是lod_tensor，lod_tensor将batch_size和padded_sentence_size合在同一维了，请问如何对embedding后的lod_tensor，转成普通的3维tensor。

**Comment by phonism** [comment]
embedding输入用shape[padded_sentence_size, 1]，解决

**Comment by wopeizl** [comment]
能否贴一下使用的例子，我们看看怎么可以优化一下

**Comment by phonism** [comment]
@wopeizl 模型结构大概是这样
```
left_emb = self.emb(left)
right_emb = self.emb(right)

cross = fluid.layers.matmul(left_emb, right_emb, False, True)

cross_img = fluid.layers.unsqueeze(cross, [1])

cross_conv = fluid.layers.conv2d(
                cross_img,
                num_filters=32,
                filter_size=[3, 3],
                padding=[1, 1],
                act="relu")
```
输入是统一padding了一下，没有使用lod_tensor
```
left = data(name="left", shape=[30, 1], dtype="int64", lod_level=0)
right = data(name="left", shape=[50, 1], dtype="int64", lod_level=0)
```
