### ISSUE TITLE
以字符为单元做LSTM

### ISSUE THREAD

**Issue by hweidream** [PaddlePaddle/Paddle#16458]
想请问在以字符为单元进行RNN得到每个词的词表示时训练出core
`
char = fluid.layers.data(
     name='char_data', shape=[-1, 1], dtype='int64', lod_level=2)
char_fc = fluid.layers.fc(input=char_embedding, size=hidden_dim, act='tanh')
clstm_0, _ = fluid.layers.dynamic_lstm(input=char_fc, \
size=hidden_dim,
        candidate_activation='relu',
        gate_activation='sigmoid',
        cell_activation='sigmoid',
        is_reverse=False)
clstm_1, _ = fluid.layers.dynamic_lstm(input=char_fc, \
        size=hidden_dim,
        candidate_activation='relu',
        gate_activation='sigmoid',
        cell_activation='sigmoid',
        is_reverse=True)
char_lstm = fluid.layers.sequence_last_step(input=clstm_0)
char_lstm_reverse = fluid.layers.sequence_last_step(input=clstm_1)
`
报错信息如下：
`
    cost = exe.run(main_program, feed=feeder.feed(data), fetch_list=[avg_cost])
  File "/home/tools/paddle_fluid/paddle_release_home/python/lib/python2.7/site-packages/paddle/fluid/executor.py", line 472, in run
    self.executor.run(program.desc, scope, 0, True, True)
paddle.fluid.core.EnforceNotMet: Enforce failed. Expected lods.size() == 1UL, but received lods.size():2 != 1UL:1.
Only support one level sequence now. at [/paddle/paddle/fluid/operators/math/sequence2batch.h:79]
`

**Comment by SunGaofeng** [comment]
从报错信息来看，是因为sequence2batch只支持lod level =1的情形，您的输入数据的lod level是2。
这里的输入数据具体是什么形式的？

**Comment by hweidream** [comment]
char的输入类似于下面的，整个序列表示一个句子，其中[1148, 1905]表示句子中第一个词中包含了两个字符，其中1148和1905是字符对应的id
[[1148, 1905], [232], [415], [182, 2414],...]

**Comment by SunGaofeng** [comment]
这个输入数据确实是lod level = 2的，那sequence2batch 里面会出错。从上面的模型结构来看，lstm里面是不是只用了lod level 0 的信息，是否可以将 输入数据改成 lod level = 1的形式？

**Comment by xuezhong** [comment]
lstm 得输入是id的序列，每一个id都必须明确前一个id是啥，比如[1148, 1905], [232], [415], [182, 2414],...]中232的前一个id是啥？

**Comment by xuezhong** [comment]
针对lod_level=2的情形，一般还是先将数据转换成lod_level=1的数据再做rnn处理。
其中一种方法可参考https://github.com/PaddlePaddle/models/blob/develop/fluid/PaddleNLP/machine_reading_comprehension/rc_model.py#L284

**Comment by hweidream** [comment]
那如果词中只包含了一个字符，前一个id是需要指定为什么？

**Comment by hweidream** [comment]
改了之后又报错如下：
![image](https://user-images.githubusercontent.com/17971652/55065013-01718e80-50b6-11e9-85fd-2ceb618e0432.png)

**Comment by hweidream** [comment]
改了之后又报下面的错误
![image](https://user-images.githubusercontent.com/17971652/55065069-20702080-50b6-11e9-8b50-f1f68fcdf638.png)

**Comment by xuezhong** [comment]
先贴下出错的代码把
