### ISSUE TITLE
在recommender_system中如何从数据集中获取用户性别。

### ISSUE THREAD

**Issue by zmhuihuihui** [PaddlePaddle/Paddle#16451]
paddle.dataset.movielens.user_info()[1].gender为什么不能获取用户性别？

**Comment by SunGaofeng** [comment]
可以使用paddle.dataset.movielens.user_info()[1].value()获取用户信息，
其中value()函数的返回值是：
         [self.index, 0 if self.is_male else 1, self.age, self.job_id]，
第二项即是gender信息
具体请参考https://github.com/PaddlePaddle/Paddle/blob/0fff666f149af9c1254440cd1f3b8d9d4aa7887e/python/paddle/dataset/movielens.py#L86
