### ISSUE TITLE
请问PaddlePaddle如何使用reshape方法？

### ISSUE THREAD

**Issue by yeyupiaoling** [PaddlePaddle/Paddle#16469]
# 环境
 - PaddlePaddle （develop）
 - Ubuntu 16.04
 - Python

# 问题
我想复现tensorflow的以下代码
```python
    num_cls_prob = tf.size(cls_prob)
    cls_prob_reshpae = tf.reshape(cls_prob, [num_cls_prob, -1])

    print(num_cls_prob)
    print(cls_prob_reshpae)
```
输出的结果：
```
Tensor("PNet/Size:0", shape=(), dtype=int32)
Tensor("PNet/Reshape:0", shape=(64, 1), dtype=float32)

```

但是PaddlePaddle没有`size`接口，所以我使用以下的方法的，但是是有错误的，得到的维度不是期望得到的维度，
```python
    # 类别size[2*batch]
    def my_size(x):
        num_cls_prob = np.size(x)
        cls_prob_reshpae = np.reshape(x, [num_cls_prob, -1])
        return cls_prob_reshpae

    cls_prob_reshpae = create_tmp_var(name='cls_prob_reshpae', dtype=cls_prob.dtype, shape=cls_prob.shape)
    cls_prob_reshpae = fluid.layers.py_func(func=my_size, x=cls_prob, out=cls_prob_reshpae)

    print(cls_prob)
    print(cls_prob_reshpae)
```

输出的情况：
```
name: "cls_prob.tmp_0"
type {
  type: LOD_TENSOR
  lod_tensor {
    tensor {
      data_type: FP32
      dims: -1
      dims: 2
    }
    lod_level: 0
  }
}
persistable: false

name: "cls_prob_reshpae"
type {
  type: LOD_TENSOR
  lod_tensor {
    tensor {
      data_type: FP32
      dims: -1
      dims: 2
    }
  }
}
```

**Comment by qingqing01** [comment]
- reshape接口请参考: http://www.paddlepaddle.org/documentation/docs/zh/1.3/api/layers.html#reshape
  - 可通过静态的shape来设置， 其中-1会推断，0是会直接拷贝对应维度。
  - 也可以通过actual_shape一个Variable来设置
- 获取某个Variable的的shape可以参考fluid.layers.shape  http://www.paddlepaddle.org/documentation/docs/zh/1.3/api/layers.html#shape
-  如何对shape总的大小，可以用fluid.layers.reduce_prod() 

不知道这些可否解决你的问题？

**Comment by yeyupiaoling** [comment]
@qingqing01  我使用了`fluid.layers.reduce_prod()`代替自定义的py_func代码也不可用
报错信息：
```
Traceback (most recent call last):
  File "/media/test/5C283BCA283BA1C6/yeyupiaoling/PyCharm/TestMTCNN/train/train_PNet.py", line 14, in <module>
    image, label, bbox_target, landmark_target, label_cost, bbox_loss, landmark_loss, accuracy, conv4_1, conv4_2, conv4_3 = P_Net()
  File "/media/test/5C283BCA283BA1C6/yeyupiaoling/PyCharm/TestMTCNN/train/model.py", line 75, in P_Net
    label_cost = cls_ohem(cls_prob=cls_prob, label=label)
  File "/media/test/5C283BCA283BA1C6/yeyupiaoling/PyCharm/TestMTCNN/train/model.py", line 121, in cls_ohem
    cls_prob_reshpae = fluid.layers.reshape(cls_prob, [num_cls_prob, -1])
  File "/home/test/PaddlePaddle_Python3.5/lib/python3.5/site-packages/paddle/fluid/layers/nn.py", line 6339, in reshape
    "Only one dimension in shape can be unknown.")
AssertionError: Only one dimension in shape can be unknown.
```


这个我的项目，不知道您有没有时间看一看呢，直接运行`train_PNet`即可。
[TestMTCNN.zip](https://github.com/PaddlePaddle/Paddle/files/3011805/TestMTCNN.zip)

**Comment by qingqing01** [comment]
> AssertionError: Only one dimension in shape can be unknown.

 这个错误说明在 `cls_prob_reshpae = fluid.layers.reshape(cls_prob, [num_cls_prob, -1])` 这个里面，静态的shape出现了2个-1，无法正确推断。 要么合理考虑使用-1和0，要么reshape接口里使用actual_shape，接受一个Variable作为shape。

**Comment by qingqing01** [comment]
> AssertionError: Only one dimension in shape can be unknown.

 这个错误说明在 `cls_prob_reshpae = fluid.layers.reshape(cls_prob, [num_cls_prob, -1])` 这个里面，静态的shape出现了2个-1，无法正确推断。 要么合理考虑使用-1和0，要么reshape接口里使用actual_shape，接受一个Variable作为shape。

**Comment by yeyupiaoling** [comment]
@qingqing01 
>要么合理考虑使用-1和0

这个没办法实现我的需求呢。

> 要么reshape接口里使用actual_shape，接受一个Variable作为shape。

这是具体要怎么操作呢？

**Comment by qingqing01** [comment]
首先，你要reshape成啥样呢? 就是需要构造出来一个Variable表示的目标shape，假如是s0，再假如静态的shape是s1=[1024， 4](这是个举例，您可以依据实际的shape设置)。

```
cls_prob_reshpae = fluid.layers.reshape(cls_prob,  shape=s1,  actual_shape=s0)
```

- 这里静态的shape用于构建网络时输出shape推断，使用这个原因，actual_shape是个Variable，在构建图时还无法预先知道里面的值。
- actual_shape是Variable，网络实际运行时可以得到真实的值，actual_shape的优先级高于shape。

**Comment by yeyupiaoling** [comment]
@qingqing01 我要reshape的结果是这样的，比如batch为32，那么`cls_prob`的`shape`就是`[32, 2]`，然后是经过`reshape`得到的是`[64, 1]`。
可能actual_shape能够实现，不知道，还需要实验一下。我发给的文件中是MTCNN中的PNet网络，能够独立运行的。

**Comment by qingqing01** [comment]
那您可以直接如下吗：

```python
    cls_prob_reshpae = fluid.layers.reshape(cls_prob, [-1, 1])
```

您发给我的代码可以运行，但是不清楚上下文，无法知道目标shape到底是啥样的。

**Comment by yeyupiaoling** [comment]
@qingqing01 如果修改成这样，这一步是能够通过的
```python
    num_cls_prob = fluid.layers.reduce_prod(cls_prob)
    cls_prob_reshpae = fluid.layers.reshape(cls_prob, [-1, 1])
```

对比tensorflow的代码，上面的操作虽然得到与实际的结果维度一样，但是也不是最准确的。根据tensorflow来看，实际上是应该是把`cls_prob`的batch维度修改成所有维度总和的大小，然后第二个维度的大小为自动推断。
```python
    # 类别size[2*batch]
    num_cls_prob = tf.size(cls_prob)
    cls_prob_reshpae = tf.reshape(cls_prob, [num_cls_prob, -1])
```

## 补充
我主要是为了实现MTCNN的交叉熵损失函数，参考tensorflow的代码
```python
def cls_ohem(cls_prob, label):
    '''计算类别损失
    参数：
      cls_prob：预测类别，是否有人
      label：真实值
    返回值：
      损失
    '''
    zeros = tf.zeros_like(label)

    # 只把pos的label设定为1,其余都为0
    label_filter_invalid = tf.where(tf.less(label, 0), zeros, label)

    # 类别size[2*batch]
    num_cls_prob = tf.size(cls_prob)
    cls_prob_reshpae = tf.reshape(cls_prob, [num_cls_prob, -1])

    label_int = tf.cast(label_filter_invalid, tf.int32)

    # 获取batch数
    num_row = tf.to_int32(cls_prob.get_shape()[0])

    # 对应某一batch而言，batch*2为非人类别概率，batch*2+1为人概率类别,indices为对应 cls_prob_reshpae
    # 应该的真实值，后续用交叉熵计算损失
    row = tf.range(num_row) * 2
    indices_ = row + label_int

    # 真实标签对应的概率
    label_prob = tf.squeeze(tf.gather(cls_prob_reshpae, indices_))
    loss = -tf.log(label_prob + 1e-10)

    zeros = tf.zeros_like(label_prob, dtype=tf.float32)
    ones = tf.ones_like(label_prob, dtype=tf.float32)

    # 统计neg和pos的数量
    valid_inds = tf.where(label < zeros, zeros, ones)
    num_valid = tf.reduce_sum(valid_inds)

    print(num_valid)
    print(valid_inds)

    # 选取70%的数据
    keep_num = tf.cast(num_valid * num_keep_radio, dtype=tf.int32)

    # 只选取neg，pos的70%损失
    loss = loss * valid_inds
    loss, _ = tf.nn.top_k(loss, k=keep_num)
    return tf.reduce_mean(loss)
```

其公式为：
![image](https://user-images.githubusercontent.com/26297768/55123940-73da8100-513f-11e9-9270-a53646bf4d5e.png)


我根据tensorflow修改成PaddlePaddle的代码为：
https://github.com/yeyupiaoling/TestMTCNN/blob/b99771f9cc40c7d026150c216abecb23ffa9ba26/train/model.py#L95-L165

**Comment by qingqing01** [comment]
>      num_cls_prob = fluid.layers.reduce_prod(cls_prob)
这个得到是一个Variable，不是一个scaler的数值，无法作为[num_cls_prob，-1]传到reshape里。

除非你再将-1构造Variable，和num_cls_prob的Variable拼接。
或者num_cls_prob要是确定的数字，直接用即可，不用推断。
或者通过Variable之间变化构造出想要的目标shape。

**Comment by yeyupiaoling** [comment]
@qingqing01 嗯嗯，我还是直接指定reshape的数字吧，这样做可能会简单一些。谢谢您的回答。
是否也能帮我解答这个问题：#16507
