### ISSUE TITLE
PR 16295导致 加上FLAGS_fraction_of_gpu_memory_to_use=0.0训练时，速度降为原来1/3 

### ISSUE THREAD

**Issue by kolinwei** [PaddlePaddle/Paddle#16464]
https://github.com/PaddlePaddle/Paddle/pull/16295

**Comment by zhhsplendid** [comment]
目前在我用的K40机器上，用PR前后的commit运行训练脚本
https://github.com/PaddlePaddle/paddle-ce-latest-kpis/blob/master/lstm/run.xsh
都不能复现，将继续跟进修理这个问题。

**Comment by zhhsplendid** [comment]
已经查出原因，ce测试在跑这个PR（以及附近几个PR时）有其他人在调试机器，导致训练变慢。并非代码问题。现在ce测试最新的commit里训练速度已经恢复了。
