### ISSUE TITLE
fine-tune重置优化器参数

### ISSUE THREAD

**Issue by ws441572091** [PaddlePaddle/Paddle#16478]
![fb5c215c5f0d0780b91c722ba2bb70b3](https://user-images.githubusercontent.com/35720887/55054904-53a5b600-509c-11e9-8b7d-f217dd9584a9.png)
询问paddle值班同学 @dangqingiqng 之后，load_persistable会加载初始化模型的lr，请问是否将我第一行设置的lr覆盖
那么请问如何重置lr，以及decay_step这些参数

**Comment by qingqing01** [comment]
@ws441572091  是会覆盖，你可以将保存路径里的LR参数删掉，或者通过  [“paddle.fluid.io.load_vars”](http://paddlepaddle.org/documentation/docs/zh/1.3/api/io.html#permalink-4-load_vars)加载，通过设置predicate来过滤不想加载的。

**Comment by ws441572091** [comment]
尝试了一下第一种方法
![image](https://user-images.githubusercontent.com/35720887/55059274-7db1a500-50a9-11e9-8748-dc84e4d7a4e7.png)
请问是否时删掉LR_DECAY_COUNTER这个文件，删掉之后报错
![image](https://user-images.githubusercontent.com/35720887/55059234-6a9ed500-50a9-11e9-9b1c-42b8fa4ff40f.png)

**Comment by ws441572091** [comment]
尝试了一下第二种方法，请问可以直接从persistable路径下使用load_vars吗，目前使用load_vars报错
代码：
![image](https://user-images.githubusercontent.com/35720887/55060080-99b64600-50ab-11e9-8313-0929a8f36e78.png)
错误：
![image](https://user-images.githubusercontent.com/35720887/55060111-ad61ac80-50ab-11e9-9512-c30c2dd142af.png)

**Comment by qingqing01** [comment]
可以load，可以先删除对应变量，再用load_vars 过滤不存在的， 参考： https://github.com/PaddlePaddle/models/blob/develop/fluid/PaddleCV/image_classification/train.py#L267  这里面是针对保存的variable是单个文件的。

**Comment by ws441572091** [comment]
好的，那么其实就是一个方法，删掉不想加载的单个文件，再用load_vars的predicate过滤
![image](https://user-images.githubusercontent.com/35720887/55067253-5ca58000-50ba-11e9-8768-fa9aa588a764.png)
目前这样修改在前几轮效果上打平了tensorflow，后续实验效果待观察
