### ISSUE TITLE
Train speed on bert

### ISSUE THREAD

**Issue by gongweibao** [PaddlePaddle/Paddle#16485]
### 速度问题
5节点，每节点8卡：
使用 experimental_executor，num_threads = 8     速度：2.0 * 8 steps/s
使用 experimental_executor，num_threads = 2     速度：2.9 * 8 steps/s
使用并行图，速度：2.4 * 8 steps/s

### 使用并行图性能波动明显：
![image](https://user-images.githubusercontent.com/10721757/55061481-d59eda80-50ae-11e9-91f2-7abc21ea95f7.png)

experimental_executor很稳定：
![image](https://user-images.githubusercontent.com/10721757/55061501-dfc0d900-50ae-11e9-976b-b4ed620e8ce0.png)

**Comment by Yancey0623** [comment]
PG的num_threads 是多少？

**Comment by gongweibao** [comment]
没设置，默认

**Comment by Yancey0623** [comment]
把PG的num_threads设置成8或者16呢，这样可以让每个graph一个线程，默认应该是device_nun*4， 8卡的话就是32线程，每个graph4个。

**Comment by chengduoZH** [comment]
有这个结果的复现环境吗？
