### ISSUE TITLE
Name of scale op conflict when saving inference model

### ISSUE THREAD

**Issue by wanghaoshuang** [PaddlePaddle/Paddle#16483]
[save_inference_model](https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/fluid/io.py#L865)中，会在target variables之后加一个[scale op](https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/fluid/io.py#L956), 然后将scale op的output做为target对网络进行回溯剪枝。

问题是：如果这里添加的scale op的output variable（name: scale_0.tmp_0）和网络中其它variable重名的话，会导致剪枝结果错误。

解决办法：
1. 在目标网络的name scope下添加scale op。 （无法保障，不好实现）
2. 添加scale op的时候给output一个唯一命名

以下一个scale output命名冲突的网络示例：
![image](https://user-images.githubusercontent.com/7534971/55058549-4215db80-50a7-11e9-92ac-8842adfab51c.png)

**Comment by Superjomn** [comment]
用最新develop或者 v1.3.1
