### ISSUE TITLE
windows安装完paddle，import时报错

### ISSUE THREAD

**Issue by hjchen2** [PaddlePaddle/Paddle#16511]
如下图：
![WechatIMG17](https://user-images.githubusercontent.com/13991173/55127504-54495580-514b-11e9-99fd-3399cae5754c.png)

**Comment by Yancey0623** [comment]
请问是哪个版本，如何安装的呢？

**Comment by yeyupiaoling** [comment]
@hjchen2 我的也是#15944 我已经放弃了。

**Comment by wopeizl** [comment]
有用户反馈重装anaconda后，重启解决

**Comment by yeyupiaoling** [comment]
@wopeizl 我试过，不行。

**Comment by wopeizl** [comment]
试一下2.7看看，经常有各种环境问题，我们本地无法复现也很难查

**Comment by yeyupiaoling** [comment]
@wopeizl 好的，谢谢。

**Comment by junjun315** [comment]
看了一下报错，报错里有说需要把C:\Users\Administrator\Miniconda3\envs\test路径加入到path环境变量中。pip安装时，paddle需要找到lib目录来放置编译的库文件，miniconda这类环境关联lib时可能关联不好

**Comment by junjun315** [comment]
安装一下不带avx的包试试看 
win_cpu_noavx_openblas
http://paddlepaddle.org/documentation/docs/zh/1.3/beginners_guide/install/Tables.html

**Comment by yeyupiaoling** [comment]
@junjun315 试过了。
