### ISSUE TITLE
使用fluid.io.load_inference_model模型预测报错

### ISSUE THREAD

**Issue by luluxing3** [PaddlePaddle/Paddle#16516]
RuntimeError: Some of your feed data hold LoD information. They can not be completely cast from a list of Python ndarray to LoDTensor. Please convert data to LoDTensor directly before feeding the data.

debug information如下：
debug feed_target_names: [u'context_wordseq', u'response_wordseq', u'label']
debug fetch_vars: [name: "scale_45.tmp_0"
type {
  type: LOD_TENSOR
  lod_tensor {
    tensor {
      data_type: FP32
      dims: 1
    }
    lod_level: 0
  }
}
persistable: false
]
debug batch----------------
(<paddle.fluid.core.LoDTensor object at 0x5e38ce0>, <paddle.fluid.core.LoDTensor object at 0x5e38d50>, [[1], [0], [0], [0], [0], [0], [0], [0], [0], [0], [1], [0], [0], [0], [0], [0], [0], [0], [0], [0], [1], [0], [0], [0], [0], [0], [0], [0], [0], [0], [1], [0]])
debug batch----------------

**Comment by Yancey0623** [comment]
是要feed一个带LoD带数据吗？

**Comment by luluxing3** [comment]
是的 'context_wordseq', 'response_wordseq' 是lod_tensor

**Comment by Yancey0623** [comment]
是如何feed的呢？看起来是需要先转下LoDTensor才行, 参考下训练的feeder。

**Comment by yeyupiaoling** [comment]
@luluxing3 可以参考一下这里：https://github.com/yeyupiaoling/LearnPaddle2/blob/c2ed0cea1634159b1f005a0d2d954ce44b51b739/note12/infer.py#L32-L43

**Comment by luluxing3** [comment]
之前预测时feed_target_names: [u'context_wordseq', u'response_wordseq', u'label']，其中u'context_wordseq', u'response_wordseq'是lod_tensor,u'label'是tensor
删除u'label'（预测其实不需要）就没问题了
