### ISSUE TITLE
是否可以提供一下where 的op呢？

### ISSUE THREAD

**Issue by yeyupiaoling** [PaddlePaddle/Paddle#16535]
使用py_func()接口固然能够实现这个功能，但是使用起来还是有点复杂的，希望能够直接提供：where函数接口。

**Comment by luotao1** [comment]
感谢您的建议，我们会加入需求池中，进行统一规划！

**Comment by yeyupiaoling** [comment]
好的。

**Comment by luotao1** [comment]
@zhoukunsheng is developing where op now.
