### ISSUE TITLE
最新版paddle，python3兼容性问题

### ISSUE THREAD

**Issue by wsjz** [PaddlePaddle/Paddle#16533]
最新版paddle

python3

报错信息
~\Develop\anaconda\lib\site-packages\paddle\utils\plot.py in append(self, title, step, value)
     73                 plot_curve.append(title="Curve 1",step=1,value=1)
     74 	"""
---> 75         assert isinstance(title, basestring)
     76         assert self.__plot_data__.has_key(title)
     77         data = self.__plot_data__[title]

NameError: name 'basestring' is not defined

**Comment by wsjz** [comment]
目前plot.py这个文件仍然是Python2的语法

比如python3没有的has_key:
'dict' object has no attribute 'has_key'

**Comment by luotao1** [comment]
您好，这个问题已经在develop版本中合入了，1.4正式版会解决这个问题，感谢您的建议！

**Comment by wsjz** [comment]
> 您好，这个问题已经在develop版本中合入了，1.4正式版会解决这个问题，感谢您的建议！

只是这个文件的问题吗。。。想求一份新的plot.py文件

**Comment by luotao1** [comment]
修复PR在#15906，从develop分支上下载plot.py就可以了。
https://github.com/PaddlePaddle/Paddle/tree/develop/python/paddle/utils

**Comment by wsjz** [comment]
> 修复PR在#15906，从develop分支上下载plot.py就可以了。
> https://github.com/PaddlePaddle/Paddle/tree/develop/python/paddle/utils

解决了，谢谢
