### ISSUE TITLE
README.md里边quick start连接死链

### ISSUE THREAD

**Issue by gongweibao** [PaddlePaddle/Paddle#1654]
README.md里边quick start连接死链
>paddle/README.md 是不是需要跟新一下，有些link都死了，比如Quick Start

**Comment by wangkuiyi** [comment]
还有其他一些链接，比如指向 document 的链接。我记得 @reyoung @llxxxll 在 paddlepaddle.org 上创建了一个目录，里面是对应 develop branch 的文档的？

**Comment by luotao1** [comment]
paddlepaddle.org里面document的链接，是对应master branch的文档

**Comment by reyoung** [comment]
这个issue是不是已经fix了？我们能不能close掉了？ @gongweibao
