### ISSUE TITLE
Issues with building in Docker

### ISSUE THREAD

**Issue by wangkuiyi** [PaddlePaddle/Paddle#1655]
I noticed that our [Dockerfile](https://github.com/PaddlePaddle/Paddle/blob/develop/Dockerfile) for the development image refers to the [`build.sh`](https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/scripts/docker/build.sh).  But this script doesn't match the design doc.  For example, I cannot build PaddlePaddle using the single command listed in the [design doc](https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/scripts/docker/README.md#build-paddlepaddle-from-source-code).

**Comment by wangkuiyi** [comment]
- I don't think that build.sh need to give the generated production image Dockerfile a suffix name `${DOCKER_SUFFIX}` [here](https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/scripts/docker/build.sh#L109).  It could be just named `Dockerfile`.

- I don't understand why we need environment variable `${BUILD_AND_INSTALL` [here](https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/scripts/docker/build.sh#L39).  It looks to me that build.sh just builds, whatever the value of this variable.

- I don't think that we need `${DELETE_BUILD_CACHE}` [here](https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/scripts/docker/build.sh#L47).  Developers can clear the cache by running `rm -rf paddle/build/*` on their host machine.

- I don't think that we need to derive `${DEB_PATH}` [here](https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/scripts/docker/build.sh#L20) nor to rename the generated .deb file into `${DEB_PATH}` [here](https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/scripts/docker/build.sh#L65).  In the future, we might have more or less production image variants.  We'd better leave the flexibility to developers to rename their .deb file into whatever they want.

- I don't think we need `${DOCKER_BUILD}` [here](https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/scripts/docker/build.sh#L95).  I don't know what is actually doing here.

- I don't think the generated production image Dockerfile should have `ARG WITH_AVX` etc [here](https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/scripts/docker/build.sh#L114).  These should have been specified when developers run `docker run -v $PWD:/paddle paddle:dev -e "WITH_AVX=ON"`.  We should just need `ENV`s, but not `ARG`s.

**Comment by helinwang** [comment]
Thanks! I am working on it.

**Comment by typhoonzero** [comment]
https://github.com/PaddlePaddle/Paddle/pull/1642 already fixed :

> I don't think that build.sh need to give the generated production image Dockerfile a suffix name ${DOCKER_SUFFIX} here. It could be just named Dockerfile.

**Comment by typhoonzero** [comment]
> I don't think that we need ${DELETE_BUILD_CACHE} here. Developers can clear the cache by running rm -rf paddle/build/* on their host machine.

In fact there are 3 places that stores cache: `build/`, `third_party`, `paddle/dist` currently. If we need a "clean build"(eg. update to the latest third parte libraries or re-generate Makefiles), we need to clean them all. And we don't need to confuse developers to tell them those 3 folders to be cleaned.
