### ISSUE TITLE
Do we really need numpy?

### ISSUE THREAD

**Issue by wangkuiyi** [PaddlePaddle/Paddle#1656]
I noticed that in our [Dockerfile template](https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/scripts/docker/build.sh#L134), we install `numpy` in the production Docker image.

Is numpy really necessary?

To my understand, numpy is needed because some Python programs convert loaded data into numpy matrices, whose memory layout *happens* to be the same as our C++ code's, so that our C++ code can re-use the numpy matrices' memory space.

Compared with this three-step conversion `native Python type -- numpy matrices -- C++ data`,  a more sound and efficient alternative is `native Python type -- C++ data`?

Also, I am afraid that there are some fragile assumptions there letting C++ code re-use Python data.

Please review my concerns. Thanks!

**Comment by jacquesqiao** [comment]
这个问题的起源是一开始觉得image size比较大，想起来numpy比较占地方，其中有部分test文件可以删掉，后来实际测试了下，目前image中的numpy大小为74M，最占地方的是paddle的几个二进制，一些调查结果见 https://github.com/PaddlePaddle/Paddle/issues/1659。

经过和@wangkuiyi 老师讨论，认为如果numpy只有74M大小，那么这个事情优先级就可以降低，所以这个issue暂时先关闭，后续可以进一步优化。
