### ISSUE TITLE
c++调用paddlepaddle出core

### ISSUE THREAD

**Issue by yuyy0823** [PaddlePaddle/Paddle#16578]
之前提出过paddlepaddle调用多线程出core的问题，后来封装了多线程后问题解决（https://github.com/PaddlePaddle/Paddle/issues/16335）。
最近又出现两次core，core信息如下：

![image](https://user-images.githubusercontent.com/28800753/55299371-5110db00-5465-11e9-8625-2ec7829ece5e.png)

paddlepaddle显示的core信息如下：
![image](https://user-images.githubusercontent.com/28800753/55299443-992ffd80-5465-11e9-9be3-5eac600c7929.png)

出错的代码位置如下：
![image](https://user-images.githubusercontent.com/28800753/55299481-ba90e980-5465-11e9-8fc5-3fca1e62b74d.png)

希望帮忙定位下是什么错误导致的呢？

**Comment by yuyy0823** [comment]
补充一下，上次修复多线程问题后，c++调用的paddlepaddle升级为release/1.3版本了

**Comment by Superjomn** [comment]
可以贴下调用代码，特别是多线程那部分

另外，建议用最新的高层API，不要用老的API
