### ISSUE TITLE
CPU/GPU 混合训练的问题

### ISSUE THREAD

**Issue by Rivensa** [PaddlePaddle/Paddle#16582]
旧版本的paddlepaddle里可以设置parallel_nn来混合使用GPU和CPU计算网络层的参数，更新成fluid版本之后没有了，是不支持混合使用CPU/GPU了，还是使用方法变了

旧版本的使用链接：
http://www.paddlepaddle.org/documentation/docs/zh/0.12.0/howto/cmd_parameter/use_case_cn.html#permalink-9--gpu-cpu-

**Comment by kuke** [comment]
Fluid已经不支持混合使用CPU/GPU了，这种功能较少用到，在后续版本的设计中就去掉了
