### ISSUE TITLE
请问当模型有多个损失函数的时候要怎么处理？

### ISSUE THREAD

**Issue by yeyupiaoling** [PaddlePaddle/Paddle#16588]
# 环境
 - PaddlePaddle （develop）
 - Ubuntu 16.04
 - Python 3.5

# 问题
比如在MTCNN这个模型中，有三个损失函数，分别对应的是：是否人脸的交叉熵损失函数，人脸box的平方差损失函数，关键点平方差损失函数。
那么三个损坏函数如何合成一个损失值呢？

tensorflow的例子中是把它们乘上各自的比例，再相加，最后还加一个`L2_loss `。我也不知道这`L2_loss`是个什么鬼。
```
L2_loss = tf.add_n(slim.losses.get_regularization_losses())

total_loss_op = radio_cls_loss * cls_loss_op + radio_bbox_loss * bbox_loss_op + radio_landmark_loss * landmark_loss_op + L2_loss
```

**Comment by kuke** [comment]
训练模型的时候，每个模型的优化器在同一时刻只能有一个优化对象，所以这些loss应该是要求加权和的。这里的l2 loss应该是经过正则之后的均方误差损失。

**Comment by yeyupiaoling** [comment]
@kuke 如果是PaddlePaddle应当如何实现这个`L2_loss`呢？

**Comment by kuke** [comment]
https://github.com/PaddlePaddle/Paddle/blob/73c4f2b7b619b1bcb250c81686bc2220876faa36/python/paddle/fluid/contrib/slim/distillation/distiller.py#L174

可以参考这个写法

**Comment by yeyupiaoling** [comment]
@kuke 好的，谢谢您。

**Comment by yeyupiaoling** [comment]
@kuke 我不太懂例子中的用法，例如在我的项目中应当如何使用呢：https://github.com/yeyupiaoling/PaddlePaddle-MTCNN/blob/ed9f29ecff2e8f3333f742ba8117ef567aa1d966/train/model.py#L74-L84

**Comment by kuke** [comment]
https://github.com/PaddlePaddle/models/blob/f001d4b8ba61b5771ed96fa2f0ef71dc7d93bca7/fluid/PaddleNLP/machine_reading_comprehension/run.py#L321 

如果手写l2_loss可以参考这个例子

或者，在optimizer里面用l2正则

https://github.com/PaddlePaddle/Paddle/blob/582011ba76baab02dcc9fbaf3536d781ba59dc3b/python/paddle/fluid/tests/unittests/test_regularizer.py#L185

**Comment by yeyupiaoling** [comment]
@kuke 在tensorflow复现的MTCNN模型中，是在把各个的损失值相加的时候加上`L2_loss`，上面的做法可以么？
```python
total_loss_op = radio_cls_loss * cls_loss_op + radio_bbox_loss * bbox_loss_op + radio_landmark_loss * landmark_loss_op + L2_loss
```

**Comment by kuke** [comment]
@yeyupiaoling 可以的
