### ISSUE TITLE
Paddle 编译结果大小分析

### ISSUE THREAD

**Issue by jacquesqiao** [PaddlePaddle/Paddle#1659]
目前 paddlepaddle编译结果中，主要有以下几个二进制/动态库：
1. paddle_trainer: `124M`
  trainer主进程

2. paddle_pserver_main: `114M`
  parameter_server主进程

3. paddle_merge_model:  `120M`

4. _swig_paddle.so: `129M`
py_paddle的主要部分，paddle的python封装通过load并调用此动态库中的代码执行paddle核心逻辑。

因为paddle采用静态链接的方式编译，所以上述二进制size都比较大，而且都包含了大量重复的代码，这也是为了方便他们在分布式环境中执行。

造成的结果是paddle docker image size看起来比较大，有1G+，不过docker image传输过程中采用zip压缩，而zip压缩对重复内容很有效果，做了一下测试，上述四个文件用zip压缩之后的size为`167M`，实际在docker image中的压缩效果，还需进一步测试。

**Comment by jacquesqiao** [comment]
refs: [整理paddlepaddle编译过程](https://github.com/PaddlePaddle/Paddle/issues/1641)

**Comment by lcy-seso** [comment]
paddle_merge_model 这个工具普通用户用到的机会比较少，可以考虑不打包。线上发布为了可维护性，会把模型中的所有文件和配置merge进一个二进制文件中，维护和替换方便，普通用户应该都没有这个需要。

**Comment by jacquesqiao** [comment]
> paddle_merge_model 这个工具普通用户用到的机会比较少，可以考虑不打包。线上发布为了可维护性，会把模型中的所有文件和配置merge进一个二进制文件中，维护和替换方便，普通用户应该都没有这个需要。

@lcy-seso 赞，好的，可以减小docker image的size

**Comment by gangliao** [comment]
#1663 CMAKE第三方库添加动态库选项

**Comment by jacquesqiao** [comment]
done
