### ISSUE TITLE
求复现MTCNN模型

### ISSUE THREAD

**Issue by yeyupiaoling** [PaddlePaddle/Paddle#16593]
我几乎完全复现了：https://github.com/yeyupiaoling/PaddlePaddle-MTCNN
就差几步，但是这几步我实在是走不下去了，太难了。我放弃！！！！

我复现了PNet、RNet、ONet网络，这三个都能正常训练，但是，
在训练的过程中，损失值突然为nan，分类模型的准确率上不去，还下降了。
随着训练的进行，分类模型的第一个标签（非人脸）无限接近1，第二个（人脸）无限接近0，已真实的label不拟合。

反正就是不行。求PaddlePaddle工程师能够帮忙调试，成功后我愿意把代码贡献到`model`项目下。如需训练数据集，可以联系我。

**Comment by kuke** [comment]
已加了一个内部需求，然而短时间内不一定有排期

**Comment by yeyupiaoling** [comment]
@kuke 我基本写好了，只是有一些问题而已，是否能够帮我解决呢？

**Comment by kuke** [comment]
https://github.com/yeyupiaoling/PaddlePaddle-MTCNN/blob/ed9f29ecff2e8f3333f742ba8117ef567aa1d966/train/model.py#L56 将use_cudnn设置成False试试？

**Comment by yeyupiaoling** [comment]
@kuke 不行啊，没有效果。

**Comment by kuke** [comment]
@yeyupiaoling 看来不是这个问题

**Comment by yeyupiaoling** [comment]
@kuke 那是什么问题呢？是损失函数的问题？还是网络的问题？还是优化方法的问题？

**Comment by kuke** [comment]
这得实际跑一下才能知道了，直接看不易发现问题

**Comment by yeyupiaoling** [comment]
@kuke 需要完整的数据集么？我给您。

**Comment by lgone2000** [comment]
@yeyupiaoling 请问你是百度的吗，我目前负责paddle-vision模型这块，如果有兴趣复现开源检测模型，可以直接贡献到paddlecv模型库中.

**Comment by yeyupiaoling** [comment]
@lgone2000 不是呢，如果是的话，也不会那么凄凉在这里艰难地复现这模型了。

**Comment by lgone2000** [comment]
我帮你看看代码吧， 你装一个百度hi，加我一下，lgone2000@163.com，有问题可以交流，如果能复现出论文指标，我也可以帮忙推动加到 paddle模型库PaddleCV下面。
