### ISSUE TITLE
请问如何查看PaddlePaddle源码定义的op？

### ISSUE THREAD

**Issue by yeyupiaoling** [PaddlePaddle/Paddle#16590]
# 环境
 - PaddlePaddle 1.3
 - Ubuntu 16.04
 - Python 3.5

# 问题
我想查看某一个op的定义方式，应当如果查看呢？

例如我想PaddlePaddle的prelu，是否与下面tensorflow的定义一样。

```python
def prelu(inputs):
    '''prelu函数定义'''
    alphas = tf.get_variable('alphas', shape=inputs.get_shape()[-1], dtype=tf.float32,
                             initializer=tf.constant_initializer(0.25))
    pos = tf.nn.relu(inputs)
    neg = alphas * (inputs - abs(inputs)) * 0.5
    return pos + neg
```

**Comment by kuke** [comment]
https://github.com/PaddlePaddle/Paddle/tree/develop/paddle/fluid/operators 

PaddlePaddle定义的op，都在这个目录下。一般来讲，每个op的实现包括三个文件：接口定义文件*.cc, cpu计算逻辑实现*.h，和gpu计算逻辑实现*.cu

例如这是prelu的cc文件
https://github.com/PaddlePaddle/Paddle/blob/3628d894f2c5077832fa78f76caa75f979b42a08/paddle/fluid/operators/prelu_op.cc

**Comment by yeyupiaoling** [comment]
好的，谢谢。
