### ISSUE TITLE
fluid.incubate.fleet分布式训练必须有filelist吗？mpi训练读取hdfs数据有使用demo吗？

### ISSUE THREAD

**Issue by DukeFun** [PaddlePaddle/Paddle#16594]
版本：paddle develop版本
问题描述：fluid.incubate.fleet分布式训练必须有filelist文件列表吗？针对纯dense网络，mpi分布式训练从hdfs读取数据有使用demo吗？
thx~

**Comment by colourful-tree** [comment]
如hi沟通~
