### ISSUE TITLE
使用分布式训练出现 11889 Segmentation fault

### ISSUE THREAD

**Issue by PengheLiu** [PaddlePaddle/Paddle#16619]
*fluid1.3版本，cpu版本，mpi集群分布式训练出现以下错误*
++ /home/disk1/normandy/maybach/app-user-20190402103653-6089/workspace/python27-gcc482//bin/python train.py --train_dir ./train_data --dict_size 48295147 --model_dir ./output/model --is_local 0 --embed_size 64 --pass_num 50 --window_size 8
*** Aborted at 1554173334 (unix time) try "date -d @1554173334" if you are using GNU date ***
PC: @                0x0 (unknown)
*** SIGSEGV (@0x7fc639d53c30) received by PID 11889 (TID 0x7fd433d72700) from PID 970275888; stack trace: ***
    @     0x7fd43358d150 (unknown)
    @     0x7fd432bfebdc __memmove_ssse3_back
    @     0x7fd3d408da77 paddle::operators::math::ConcatFunctor<>::operator()()
    @     0x7fd3d39dc119 paddle::operators::ConcatKernel<>::Compute()
    @     0x7fd3d39dc363 _ZNSt17_Function_handlerIFvRKN6paddle9framework16ExecutionContextEEZNKS1_24OpKernelRegistrarFunctorINS0_8platform8CPUPlaceELb0ELm1EJNS0_9operators12ConcatKernelINS7_16CPUDeviceContextEdEENSA_ISB_fEENSA_ISB_lEENSA_ISB_iEEEEclEPKcSI_iEUlS4_E_E9_M_invokeERKSt9_Any_dataS4_
    @     0x7fd3d42cbc93 paddle::framework::OperatorWithKernel::RunImpl()
    @     0x7fd3d42ca7bb paddle::framework::OperatorBase::Run()
    @     0x7fd3d341c042 paddle::framework::Executor::RunPreparedContext()
    @     0x7fd3d341d105 paddle::framework::Executor::Run()
    @     0x7fd3d32ec70b _ZZN8pybind1112cpp_function10initializeIZN6paddle6pybindL18pybind11_init_coreERNS_6moduleEEUlRNS2_9framework8ExecutorERKNS6_11ProgramDescEPNS6_5ScopeEibbE90_vIS8_SB_SD_ibbEINS_4nameENS_9is_methodENS_7siblingEEEEvOT_PFT0_DpT1_EDpRKT2_ENUlRNS_6detail13function_callEE1_4_FUNESV_
    @     0x7fd3d332df6e pybind11::cpp_function::dispatcher()
    @     0x7fd433875010 PyEval_EvalFrameEx
    @     0x7fd433876b80 PyEval_EvalCodeEx
    @     0x7fd43387508e PyEval_EvalFrameEx
    @     0x7fd433876b80 PyEval_EvalCodeEx
    @     0x7fd43387508e PyEval_EvalFrameEx
    @     0x7fd433876b80 PyEval_EvalCodeEx
    @     0x7fd43387508e PyEval_EvalFrameEx
    @     0x7fd433876b80 PyEval_EvalCodeEx
    @     0x7fd43387508e PyEval_EvalFrameEx
    @     0x7fd433876b80 PyEval_EvalCodeEx
    @     0x7fd433876c82 PyEval_EvalCode
    @     0x7fd43388f60f run_mod
    @     0x7fd43389067e PyRun_FileExFlags
    @     0x7fd4338917d7 PyRun_SimpleFileExFlags
    @     0x7fd4338a1d9d Py_Main
    @     0x7fd432ae7bd5 __libc_start_main
    @           0x4007c1 (unknown)
    @                0x0 (unknown)
.//paddle/start_trainer.sh: line 105: 11889 Segmentation fault      (core dumped) /home/disk1/normandy/maybach/app-user-20190402103653-6089/workspace/python27-gcc482//bin/python train.py --train_dir ./train_data --dict_size 48295147 --model_dir ./output/model --is_local 0 --embed_size 64 --pass_num 50 --window_size 8

mpi训练任务链接：http://nmg-hpc-hlan-mon.dmop.baidu.com:8919/taskinfo.html?appId=app-user-20190402103653-6089

**Comment by seiriosPlus** [comment]
在配置里面加一下日志的FLAG吧
GLOG_v=4 
GLOG_logtostderr=1
