### ISSUE TITLE
Training hangs when training resnet101 on P40 * 4 GPUs

### ISSUE THREAD

**Issue by Kontinuation** [PaddlePaddle/Paddle#16616]
I submitted multiple training jobs to paddlecloud with same configuration, they all hang after several iterations (50 - 700):
* Paddle version: fluid v1.3
* GPU: P40 * 4 on a single host, CUDA Version: 9.0, CUDNN Version: 7.0
* Model: ResNet 101, batch size: 240

I reproduced this problem with logging enabled (`GLOG_vmodule=threaded_ssa_graph_executor=10,operator=4`), and produced this [training log](https://drive.google.com/file/d/1U5e8nAdRVcOby-UHBc2ZWnCxT8hBpXGX/view?usp=sharing).

Explicitly setting the `num_threads` property of ParallelExecutor's execution strategy make the problem unable to reproduce.
<img width="729" alt="f802267fe0f3dba63862a1622a6dcaf8" src="https://user-images.githubusercontent.com/5501374/55378114-382e2580-554a-11e9-886a-94585a9ad996.png">

**Comment by walloollaw** [comment]
补充下， 这个任务在2卡 P40和 4卡K40 上都是好的，只在4卡 P40上会夯住

**Comment by chengduoZH** [comment]
@walloollaw 您在本地能够复现吗？

**Comment by Kontinuation** [comment]
> @walloollaw 您在本地能够复现吗？

我们这边没有本地的P40环境，所以没有在本地试过

**Comment by chengduoZH** [comment]
@Kontinuation  最好能够在本地试一下，如果只是在cloud上有问题，可能就比较难查了。

**Comment by chengduoZH** [comment]
最新版本（V1.4.1）已经没有这个问题了
