### ISSUE TITLE
mnist示例代码optimizer报错

### ISSUE THREAD

**Issue by okboy32** [PaddlePaddle/Paddle#16613]
mnist示例代码optimizer报错
- 版本、环境信息：
    1）PaddlePaddle版本：1.3.1 Numpy: 1.14.2
    2）CPU：2.2 GHz Intel Core i7
    4）系统环境：例如Mac OS 10.14.4，Python Anaconda 3.6 [https://pan.baidu.com/s/1TAZ3AxeW_SLW_ySoj0qc2A](url)
提取码: hvgc

**Comment by gongweibao** [comment]
能否先跑一下我们model的例子那？

**Comment by junjun315** [comment]
这个报错应该是我们util里的一个方法有问题。不支持py3，主要是paddle.util.plots。可以切换python2.7版本。在下个版本里我们会修正这个错误
