### ISSUE TITLE
关于视频预测

### ISSUE THREAD

**Issue by Samhandsome** [PaddlePaddle/Paddle#16615]
请问训练好的视频模型，怎么和视频流结合起来呢？Paddle有和Opencv的接口吗？或者有什么办法读取视频吗？

**Comment by gongweibao** [comment]
这个还没有。。。

**Comment by Samhandsome** [comment]
@gongweibao 那现在有什么解决办法吗？

**Comment by gongweibao** [comment]
@qingqing01 知道吗？

**Comment by qingqing01** [comment]
@Samhandsome  PaddlePaddle框架本身没有提供对视频读取接口，一般在用户预测程序里处理。
1. 如果您是Python预测，可以通过python-cv2(或其他python库)处理视频，再使用Paddle Python预测。
2. 如果您是C++里做预处理，将Paddle预测库(lib) 和 OpenCV库或其他读取视频库联编，处理视频数据，将处理过的数据作为预测lib的输入。 如何使用Paddle C++预测库可以详细参考官网文档。
