### ISSUE TITLE
Paddle python包编译过程及优化计划

### ISSUE THREAD

**Issue by jacquesqiao** [PaddlePaddle/Paddle#1662]
refs: [整理paddlepaddle编译过程](https://github.com/PaddlePaddle/Paddle/issues/1641)

## python包编译过程

目前paddle编译过程中会生成两个python包，例如：
###  paddle-`0.10.0rc0`-py2-none-any.whl
这个包目前包含paddle python封装代码，包含以下几个目录：
  - `proto`:  paddle中定义的proto对应的python封装，DataConfig、ModelConfig等。
  - `trainer`:最初的config_parser那一套代码等。
  - `trainer_config_helpers`:对config_parser的初步封装。
  - `utils`: 一些工具函数
  - `v2`: 最新重构的api封装。

这个包是由paddle/python/setup.py.in配置生成，paddle/python/CMakeLists.txt先将setup.py.in存储为setup.py并修改其中定义的变量，然后执行：
```shell
python setup.py bdist_wheel
```
生成whl包。

### py_paddle-`0.10.0rc0`-cp27-cp27m-macosx_10_10_x86_64.whl
这个包主要对应的是paddle的swig封装，最主要的部分是`_swig_paddle.so`和`swig_paddle.py`。提供了python调用paddle核心cpp框架的入口，上述`paddle`中的api封装对象主要就是swig_paddle.py。
`paddle/api/CMakeLists.txt`中：

1. `python_swig_sources`

	这个target会调用swig命令:
	```
	swig -python -c++ -outcurrentdir -I../ api/Paddle.swig
	```

	生成`Paddle_wrap.cxx`, `Paddle_wrap.h`和`swig_paddle.py`三个文件。

	`paddle_api_config.py.in`被修改为:

	`setup.py.in`依赖`paddle_ld_flags.py`依赖`paddle_api_config.py.in`

	`paddle_api_config.py`里面都是一些flag

	`api/paddle_ld_flags.py`这个文件用来生成对应的ld_flags

2. `add_custom_command`

	```shell
	# 打包
	python setup.py bdist_wheel
	```
这个过程会利用swig命令生成的头文件和cxx文件，编译生成swig依赖的动态库`_swig_paddle.so`

**Comment by jacquesqiao** [comment]
## 优化计划
从上述编译过程来看，目前编译过程会生成两个python包，其实都是paddle的python binding，其实完全可以放到同一个python包中，所以初步计划统一成一个python包。

**Comment by gangliao** [comment]
最好还是移除 api/paddle_ld_flags.py以及setup.py.in的方式获取CMAKE编译参数和选项

**Comment by luotao1** [comment]
以后python包安装的时候，能否自动覆盖老的版本么？这样不用先pip uninstall paddle，再重新安装一份。

**Comment by jacquesqiao** [comment]
> 以后python包安装的时候，能否自动覆盖老的版本么？这样不用先pip uninstall paddle，再重新安装一份。

@luotao1 这个可以通过  `pip install --upgrade xxx.whl`来实现
