### ISSUE TITLE
pserver模式执行出core，本地模式没问题。

### ISSUE THREAD

**Issue by sshilei** [PaddlePaddle/Paddle#16627]
paddlecluode jobid : job-0bb5ca2d76873f0d

![image](https://user-images.githubusercontent.com/18701471/55379820-c907ff80-5550-11e9-99f0-9cd14a6809f3.png)

**Comment by gongweibao** [comment]
这个不是最开始的错误。你看一下是不是有节点没有启动起来或者死掉了？
这个错误的意思是说对方节点迟迟没有回应。

**Comment by LeLiu** [comment]
> 这个不是最开始的错误。你看一下是不是有节点没有启动起来或者死掉了？
> 这个错误的意思是说对方节点迟迟没有回应。

@gongweibao 您好，我也遇到了类似的问题。我的情况是训练节点在训练过程中有用dev节点跑测试的情况，在跑完测试后，所有的训练节点再尝试与PSERVER连接就会失败。是因为不能长时间与PSERVER不通信吗？要怎么处理？
