### ISSUE TITLE
多卡训练提示找不到"libnccl.so*"

### ISSUE THREAD

**Issue by xyq019971** [PaddlePaddle/Paddle#16630]
EnforceNotMet: Failed to find dynamic library: libnccl.so ( libnccl.so: cannot open shared object file: No such file or directory ) Please specify its path correctly using following ways: Method. set environment variable LD_LIBRARY_PATH on Linux or DYLD_LIBRARY_PATH on Mac OS. For instance, issue command: export LD_LIBRARY_PATH=... Note: After Mac OS 10.11, using the DYLD_LIBRARY_PATH is impossible unless System Integrity Protection (SIP) is disabled. at [/paddle/paddle/fluid/platform/dynload/dynamic_loader.cc:157] PaddlePaddle Call Stacks:

**Comment by gongweibao** [comment]
find 一下libnccl.so在哪里，然后把LD_LIBRARY_PATH添加一下。nccl的没有。

**Comment by xyq019971** [comment]
> find 一下libnccl.so在哪里，然后把LD_LIBRARY_PATH添加一下。nccl的没有。

找不到  libnccl.so

**Comment by gongweibao** [comment]
那得装一个呀。
