### ISSUE TITLE
exe.run(fetch_list=[loss.name]) 获取参数报错

### ISSUE THREAD

**Issue by AWSWXY** [PaddlePaddle/Paddle#16637]

**Comment by AWSWXY** [comment]
![image](https://user-images.githubusercontent.com/18156360/55399492-cec80a00-557d-11e9-8963-3fee20977c98.png)

**Comment by seiriosPlus** [comment]
看上去是reader的问题，贴一下reader相关的定义代码？

**Comment by gongweibao** [comment]
Hi上已经解决了。
