### ISSUE TITLE
Generate External Shared Libraries for Docker Image to Reduce Size

### ISSUE THREAD

**Issue by gangliao** [PaddlePaddle/Paddle#1663]
增加cmake参数，支持所有第三方依赖以动态库的方式存在，缩小image size.

improve https://github.com/PaddlePaddle/Paddle/issues/1641

**Comment by jacquesqiao** [comment]
对于目前的mpi来说，是不是还是需要静态编译，如果未来分布式环境只支持docker的话，就没有这个问题啦。

**Comment by gangliao** [comment]
我们应该是指提供一个cmake变量控制，既可以满足动态编译也可以满足静态编译场景。

**Comment by gangliao** [comment]
I will close this issue.
