### ISSUE TITLE
fluid.layers.mean 不支持name参数

### ISSUE THREAD

**Issue by lgone2000** [PaddlePaddle/Paddle#16646]
fluid的layers 大部分都支持name参数，为啥有个别的不支持？

**Comment by lgone2000** [comment]
softmax_with_cross_entropy 也不支持

**Comment by guoshengCS** [comment]
layer的name参数会用来对layer中包含的参数和输出进行命名，确实有些layer没有留出来这个参数，默认会使用layer的type加上个idx作为name进行命名，可以参考这里fc的name处理
https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/fluid/layers/nn.py#L301
https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/fluid/layer_helper.py#L36
