### ISSUE TITLE
关于运行时优化的问题咨询

### ISSUE THREAD

**Issue by a6802739** [PaddlePaddle/Paddle#16641]
请教下, IR目录下有很多pass是关于运行时优化的，请教下有每种pass主要是做哪方面的优化。

**Comment by gongweibao** [comment]
比较多。后续我们加入文档。

**Comment by a6802739** [comment]
能不能先给一些参考链接。@gongweibao

**Comment by gongweibao** [comment]
这个好像还没有文档。。。现在主要是公司内开发人员用。。。

**Comment by gongweibao** [comment]
您是？

**Comment by a6802739** [comment]
嗯嗯，多谢您了。应该有一些文档开发的时候作为参考吧？

gongweibao <notifications@github.com> 于 2019年4月3日周三 下午6:16写道：
