### ISSUE TITLE
group_norm op计算出 nan, 计算结果中方差存在负数

### ISSUE THREAD

**Issue by MyPandaShaoxiang** [PaddlePaddle/Paddle#16654]
PaddlePaddle版本：develop分支 commit:ed61d67c737590ebf2819ca9770a9a6d4e294880 
   cpu5117，centos6u3, python版本
   跑deeplabv3模型，在第一个groupnorm输出结果中出现nan, 查看group_norm参数scale和bias,输入均无nan,输入数据正常， 经查看发现group_norm输出的var存在负数，可能导致开方后出nan

模型输入是全1数据，op输入为1*32*513*1025, group=32，输出中前后部分有数据，中间部分为nan

**Comment by Shixiaowei02** [comment]
@MyPandaShaoxiang 请帮忙使用正式版 v1.3 验证一下问题是否也存在，谢谢！
