### ISSUE TITLE
在一个迁移paddle的项目中，确认paddle的api是否能满足需求

### ISSUE THREAD

**Issue by liujian07** [PaddlePaddle/Paddle#16665]
在一个模型训练任务迁移到paddle的过程中，想知道所需功能，PaddlePaddle的api是否能支持（之前跟闫旭交流过，这里的很多功能，paddlepaddle正在开发中。）如果能支持的话，请告诉我api的用法，或者wiki网址。

功能列表如下：
1、各卡上数组求最大值   reduce max
2、将GPU卡上某个数据复制到GPU0或者CPU内存里   as_in_context
3、各卡上数组减去某个数   element sub
4、各卡上数组求指数   element exp
5、各卡上数组的求和   reduce sum
6、各卡上数组元素除以某个数   element div
7、卡上的某个数据单元减去一个数 sub
8、在自定义loss是否能执行以上的操作？

谢谢！

**Comment by Yancey0623** [comment]
> 1、各卡上数组求最大值 reduce max

[reduce_max op](http://paddlepaddle.org/documentation/docs/zh/1.3/api/layers.html#reduce-max)

2、将GPU卡上某个数据复制到GPU0或者CPU内存里 as_in_context
这个暂时不支持，但支持 collective op，这个具体是啥场景呢？

3、各卡上数组减去某个数 element sub/sum/dev/exp(power)

可以在官网搜一下 关键字：**elementwise** ：http://paddlepaddle.org/searchdoc?q=elementwise&language=zh&version=1.3


7、卡上的某个数据单元减去一个数 sub

没太明白，是说tensor中某个维度的值减去一个scalar？

8、在自定义loss是否能执行以上的操作？

能够用paddle op 拼出来的自定义 loss 都可以执行。

**Comment by liujian07** [comment]
>>2、将GPU卡上某个数据复制到GPU0或者CPU内存里 as_in_context
>>这个暂时不支持，但支持 collective op，这个具体是啥场景呢？

这个具体场景很容易理解。我为了计算一个数组（这个数组分散于所有卡上）的最大值，具体的计算方法是先把这个数组在每个卡上的最大值求出来，然后把这些最大值复制到cpu上，再在cpu上求这些局部最大值的最大值，得到整个数组的最大值。
这个 collective op怎么做呢？

**Comment by Yancey0623** [comment]
这个场景看起来不需要复制到CPU也可以实现？

``` python
y = fluid.layers.reduce_max(x)
y = fluid.layers.collective._allreduce(y,reduce_type="max")
```

reduce_max 参考：http://paddlepaddle.org/documentation/docs/zh/1.3/api/layers.html#reduce-max
collective ops 目前还没有正式发布，用法可以参考单测代码：https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/fluid/tests/unittests/dist_allreduce_op.py
