### ISSUE TITLE
embedding 的具体实现方式和 pytorch实现的差别

### ISSUE THREAD

**Issue by randomtutu** [PaddlePaddle/Paddle#16674]
_ 标题：简洁、精准描述您的问题，例如“ssd 模型前置lstm报错  ”
- 版本、环境信息：
    1）PaddlePaddle版本：1.3
    2）CPU：E5
    3）GPU：tesla p10
    4）系统环境：redhat /python3.6
- 模型信息
    1）模型名称: ernie 2）自由数据集 3）模型链接 https://github.com/PaddlePaddle/LARK
- 复现信息：
   模型转换为pytorch的ckpt并加载之后，同样的id 进行embedding的结果不同
- 问题描述：请详细描述您的问题，同步贴出报错信息、日志/代码关键片段

因为paddle文档比较少，因此想要把转换成pytorch。

我使用 https://github.com/PaddlePaddle/LARK/issues/37 上的脚本，将paddle的ckpt转换为dict,再通过简单的名字对应和tensor的转换，将对应权重加载到pytorch中。

我将两个框架的模型跑同一数据的前向传播，将每一步的数据进行对比。结果发现，两个框架上同样的embedding权重（weight），对相同id的embedding居然不同。

我猜测要么是两个框架的embedding实现方法有差别

请问一下是否有差别呢？

**Comment by guoshengCS** [comment]
这个不是特别清楚，Paddle的话embedding层是一个查表操作，参数是一个dict_size*embed_dim的矩阵

**Comment by InsaneLife** [comment]
> _ 标题：简洁、精准描述您的问题，例如“ssd 模型前置lstm报错  ”
> 
> * 版本、环境信息：
>      1）PaddlePaddle版本：1.3
>      2）CPU：E5
>      3）GPU：tesla p10
>      4）系统环境：redhat /python3.6
> * 模型信息
>      1）模型名称: ernie 2）自由数据集 3）模型链接 https://github.com/PaddlePaddle/LARK
> * 复现信息：
>   模型转换为pytorch的ckpt并加载之后，同样的id 进行embedding的结果不同
> * 问题描述：请详细描述您的问题，同步贴出报错信息、日志/代码关键片段
> 
> 因为paddle文档比较少，因此想要把转换成pytorch。
> 
> 我使用 [PaddlePaddle/LARK#37](https://github.com/PaddlePaddle/LARK/issues/37) 上的脚本，将paddle的ckpt转换为dict,再通过简单的名字对应和tensor的转换，将对应权重加载到pytorch中。
> 
> 我将两个框架的模型跑同一数据的前向传播，将每一步的数据进行对比。结果发现，两个框架上同样的embedding权重（weight），对相同id的embedding居然不同。
> 
> 我猜测要么是两个框架的embedding实现方法有差别
> 
> 请问一下是否有差别呢？

请问你是怎么加载到pytorch中的呢，脚本能否分享下
