### ISSUE TITLE
CNN网络C++预测输入问题

### ISSUE THREAD

**Issue by snowsteper** [PaddlePaddle/Paddle#16670]
任务：文本分类任务
模型网络：Input(int64) -> embedding -> cnn -> predict_label

网络的输入是变长的sequence，假设每个数据输入是[1,N]，N是seqence的长度，写代码时创建输入Tensor会遇到如下问题：
1. Tensor.shape = {N, 1}  不报错，模型输出相当于只输入了tensor的第一个id

2. Tensor.shape = {1, N}  报错， 提示embedding维度最后一维必须是1
Enforce failed. Expected ids_dims[ids_rank - 1] == 1, but received ids_dims[ids_rank - 1]:12 != 1:1.
The last dimension of the 'Ids' tensor must be 1. at [/Paddle/paddle/fluid/operators/lookup_table_op.cc:39]

3. Tensor.shape = {1, N, 1} 报错，提示cnn的输入必须是2D tensor
terminate called after throwing an instance of 'paddleplatform::EnforceNotMet'
  what():  Input(X, Filter) should be 2-D tensor. at [/Paddle/paddle/fluid/operators/sequence_conv_op.cc:43]

目前已经确认切词，转id，模型加载均无问题，基本可以定位到输入维度的问题

请问，CNN网络中输入tensor该如何设置，有没有成功的例子可以参考

c++代码：
```
int predict(const std::string input_str) {
        // 将输入字符串切词，得到id vec
	std::vector<std::vector<int64_t>> id_vecs = gen_in_vec(input_str);

        // 创建输入tensor
	const std::string name_base[] = { "char_data", "basic_data", "phrase_data" };
	std::vector<paddle::PaddleTensor> in_tensors;
	for (int i = 0; i < 3; ++i) {
		paddle::PaddleTensor in_tensor;
		in_tensor.name = name_base[i];
		in_tensor.dtype = paddle::PaddleDType::INT64;
		in_tensor.lod.emplace_back(std::vector<size_t>({ 0, 1 }));

		in_tensor.data.Resize(id_vecs[i].size() * sizeof(int64_t));
		std::cout << i << " in_tensor:\t";
		memcpy(in_tensor.data.data(), id_vecs[i].data(), id_vecs[i].size() * sizeof(int64_t));
		int64_t *tensor_data = static_cast<int64_t *> (in_tensor.data.data());
		for (size_t j = 0; j < id_vecs[i].size(); j++) {
			std::cout << tensor_data[j] << " ";
		}
		std::cout << std::endl;
		in_tensor.shape.push_back(id_vecs[i].size());
		 in_tensor.shape.push_back(1);

		in_tensors.emplace_back(in_tensor);
	}

	std::vector<paddle::PaddleTensor> input_slots;
	input_slots.assign({ in_tensors[0], in_tensors[1], in_tensors[2] });

	std::vector<paddle::PaddleTensor> output_slots;
	predictor->Run(input_slots, &output_slots);
    std::cout << "output size: " << output_slots.size() << std::endl;

	return 0;
}
```

**Comment by guoshengCS** [comment]
设置lod的这一行 `in_tensor.lod.emplace_back(std::vector<size_t>({ 0, 1 }));` 可能有些问题，lod需要是batch中每一个sequence的起始位置的list，如batch中包含length为5和6的两个sequence，则lod要是[0,5,11]，batch中包含length为5的一个sequence则lod要是[0,5]

**Comment by snowsteper** [comment]
> 设置lod的这一行 `in_tensor.lod.emplace_back(std::vector<size_t>({ 0, 1 }));` 可能有些问题，lod需要是batch中每一个sequence的起始位置的list，如batch中包含length为5和6的两个sequence，则lod要是[0,5,11]，batch中包含length为5的一个sequence则lod要是[0,5]

确实，lod维度的问题，已经解决，感谢！
