### ISSUE TITLE
节点hang住之后失败

### ISSUE THREAD

**Issue by AWSWXY** [PaddlePaddle/Paddle#16692]
http://10.87.138.44:8900/fileview.html?path=/home/disk1/normandy/maybach/app-user-20190405140253-12479/

**Comment by AWSWXY** [comment]
http://10.87.138.44:8900/fileview.html?path=/home/disk1/normandy/maybach/app-user-20190405140253-12479/

**Comment by wanghaoshuang** [comment]
抱歉，根据您提供的日志链接，暂未定位到任务hang住的原因。
