### ISSUE TITLE
Need to document the releasing steps

### ISSUE THREAD

**Issue by typhoonzero** [PaddlePaddle/Paddle#1670]
We need to document the exact releasing steps, including:

1. Use tag or branch for each release 
1. How to manage multiple release candidates
1. Build binaries on travis-ci or other tool?
1. How to release docker images, which image tag should use
1. How to release the latest/versioned docs

**Comment by reyoung** [comment]
> Use tag or branch for each release

我们使用master分支作为release分支，在master分支的每一个版本都是稳定的release。而develop分支是当前的开发分支。

在release分支，我们会打上release版本 tag，我们所有的版本号，遵循[Semantic Versioning 2.0.0](http://semver.org/)标准。这个版本的版本号格式是`Major.Minor.Patch`

> How to manage multiple release candidates

Paddle每次要release一个新版本，会新建一个Releasing分支，这个分支会增加Minor版本的数值。这个分支会打若干个tag，来标注这个分支内的各个版本。

分支版本包括下述可能性 `alpha`, `beta`和`release candidate`，版本号格式为`0.9.0a0`, `0.9.0b1`, `0.9.0rc0`等。其中`alpha`为内测版本,`beta`是公测版本，`rc`为发行候选版本。每一个版本都可以将QA同事拉入进来，做全量的功能测试。

> Build binaries on travis-ci or other tool?

目前二进制使用Docker部署，在开发机上手工编译。

> How to release docker images, which image tag should use

To be defined

> How to release the latest/versioned docs

Paddle的文档是自动编译部署的，master分支文档部署到 `www.paddlepaddle.org/doc/`上，而develop分支文档部署到`www.paddlepaddle.org/develop/doc/`上。

**Comment by typhoonzero** [comment]
感谢评论！

感觉有必要把Comment的内容，和一个完整的做Releasing的步骤写到`doc/howto/releasing`的一个文档下。这样任意一个开发者都可以依据这个步骤完成发版。
