### ISSUE TITLE
本地多台服务器构建CPU集群

### ISSUE THREAD

**Issue by Rivensa** [PaddlePaddle/Paddle#16714]
本地有多台服务器，想要构建PaddlePaddle的CPU集群，请问有相关的教程吗？
目前在文档中找不到详细的教程。只需要服务器之间可以互相ssh登录，再各自装上CPU版的paddlepaddle就可以了吗？需不需要其他环境或者软件

**Comment by velconia** [comment]
您说的是CPU的Pserver + Trainer的集群吧？

分布式训练可以参考 http://paddlepaddle.org/documentation/docs/zh/1.3/user_guides/howto/training/cluster_quick_start.html 这个教程搭建
