### ISSUE TITLE
rnn search with attation模型下，单GPU训练报错

### ISSUE THREAD

**Issue by DDDivano** [PaddlePaddle/Paddle#16719]
EnforceNotMet: Variable must be type St6vectorIN6paddle9framework9LoDTensorESaIS2_EE, the holding type is N6paddle9framework9LoDTensorE at [/paddle/paddle/fluid/framework/variable.h:51]
![image](https://user-images.githubusercontent.com/10734244/55771706-b8f5a000-5abb-11e9-8307-166d79b51a1b.png)

**Comment by velconia** [comment]
请问代码方便贴一下吗？

**Comment by DDDivano** [comment]
显存优化在c++端的bug，已经修复 。 https://github.com/PaddlePaddle/Paddle/pull/16748/files
