### ISSUE TITLE
machine_reading_comprehension训练报错

### ISSUE THREAD

**Issue by DDDivano** [PaddlePaddle/Paddle#16730]
EnforceNotMet: Invoke operator shrink_rnn_memory error.
![image](https://user-images.githubusercontent.com/10734244/55782198-58c42580-5ade-11e9-87b3-46602df6d9c5.png)
C++ Callstacks: 
holder_ should not be null
Tensor not initialized yet when Tensor::type() is called. at [/paddle/paddle/fluid/framework/tensor.h:146]
![image](https://user-images.githubusercontent.com/10734244/55782229-68436e80-5ade-11e9-84b3-d7528fbbd1b1.png)

**Comment by xuezhong** [comment]
沟通是打开显存优化后出现的问题
