### ISSUE TITLE
Paddle docker build readme need to illustrate how to test paddle. Current implementation of test is not correct.

### ISSUE THREAD

**Issue by helinwang** [PaddlePaddle/Paddle#1674]
Currently readme only mentioned "test" in this command
```
docker run -v $PWD:/paddle -e "GPU=OFF" -e "AVX=ON" -e "TEST=ON" paddle:dev
```
But there is no explanation about how will the test be performed. E.g., will the test run during building docker image `paddle:dev`, or later when paddle is building the final output image.

Current implementation is paddle will run test inside `paddle:dev` image, which is incorrect. Since the environment maybe different from the final image. Actually I encountered this problem: the test fails in `paddle:dev` since the numpy version for `paddle:dev` is too old, but the numpy version is good in the final produced image.

**Comment by typhoonzero** [comment]
Well currently it's the only way to run tests in `paddle:dev`. Or else we need to package all the test binaries into production image, and write a test script instead of running `make test` or `make coverall`. I'll fix this by updating the `paddle:dev` environment.

**Comment by typhoonzero** [comment]
Encounterd a strange issue when running build and test in `paddle:dev`: `/bin/sh: 1: eval: /usr/local/bin/cmake: Argument list too long`
```
58/60 Test #18: test_Allocator ......................   Passed    0.20 sec
59/60 Test #19: test_Tensor .........................   Passed   82.51 sec
60/60 Test #47: test_CompareTwoNets .................   Passed   98.26 sec

100% tests passed, 0 tests failed out of 60

Total Test time (real) =  98.27 sec
/bin/sh: 1: eval: /usr/local/bin/cmake: Argument list too long
make[3]: *** [CMakeFiles/coveralls_generate] Error 2
make[2]: *** [CMakeFiles/coveralls_generate.dir/all] Error 2
make[1]: *** [CMakeFiles/coveralls.dir/rule] Error 2
make: *** [coveralls] Error 2
```

**Comment by helinwang** [comment]
@gangliao ^^ could you please check above comment?

**Comment by helinwang** [comment]
@typhoonzero I think @gangliao is familiar with cmake as well, maybe he can give some suggestions.

**Comment by typhoonzero** [comment]
@helinwang I've talked with @gangliao . we'll try to figure out a solution later.

**Comment by helinwang** [comment]
I tried to use production image for test, after ctest binary available in the production image (the test programs are generated to `paddle/build`, which gets mounted into the production image), I can run unit test. However, some tests failed due to binary not found:
```text
      Start  1: test_Thread
Could not find executable test_Thread
Looked in the following places:
test_Thread
test_Thread
Release/test_Thread
Release/test_Thread
Debug/test_Thread
Debug/test_Thread
MinSizeRel/test_Thread
MinSizeRel/test_Thread
RelWithDebInfo/test_Thread
RelWithDebInfo/test_Thread
Deployment/test_Thread
Deployment/test_Thread
Development/test_Thread
Development/test_Thread
Unable to find executable: test_Thread
...
```
Maybe this can be a direction to solve the problem: copy everything unit test need into `paddle/build` and use production image to test it.

**Comment by gongweibao** [comment]
Feel free to reopen it.
