### ISSUE TITLE
目标检测（比如SSD、faster-rcnn）训练若干次之后，程序卡住，也不报错，无法继续训练

### ISSUE THREAD

**Issue by wuxiaodong1014** [PaddlePaddle/Paddle#16755]
大家好！我遇到一个问题：我在运行目标检测程序时，比如用SSD、faster-rcnn，训练若干次之后，程序卡住，也不报错，无法继续训练，这是什么原因呢？有没有解决办法呢？谢谢大家

**Comment by qingqing01** [comment]
请问您使用是哪个Paddle版本，以及什么机器？卡住的现象是什么？GPU里利用率和显存占用如何？

**Comment by wuxiaodong1014** [comment]
我用的paddle版本是1.3,python 3.6。当我把参数parallel设为True时（也就是用多卡GPU并行训练时，我有两块GPU）会出现卡住情况，当我把parallel设为False时，不会出现卡住现象。卡住的现象是：屏幕不再打印输出loss值，但是GPU还是满满的，程序也不报错。

**Comment by qivigor** [comment]
我也遇到同样的情况：屏幕不再打印输出loss值，但是GPU还是满满的，程序也不报错。不过我是用caffe训练另一个网络时遇到的，然后等了一会，屏幕就继续打印了，训练也没中断。
