### ISSUE TITLE
test_calibration 扩充ssd mobilenet case相关问题？

### ISSUE THREAD

**Issue by guomingz** [PaddlePaddle/Paddle#16754]
hi @luotao1，

我们现在这边准备扩充下test_calibration case对ssd mobilenet的支持， 但如同之前enable resnet50/mobilenet 两个模型时遇到的问题一样， 需要复用一些数据准备的代码， 比如models/fluid/PaddleCV/object_detection/image_util.py 和models/fluid/PaddleCV/object_detection/reader.py 这2个文件。
能否将他们直接复制到test_calibration 同级目录呢？ 我查了下 paddlepaddle目录下没有重复代码引用。

谢谢

**Comment by guomingz** [comment]
hi， is there any update on this issue?

**Comment by luotao1** [comment]
https://github.com/PaddlePaddle/Paddle/blob/0c277ac6e997ff0704a65cf450bf35761203f998/python/paddle/fluid/transpiler/inference_transpiler.py#L54-L56
InferenceTranspiler is deprecated
如果要扩充test_calibration case对ssd mobilenet的支持，请扩充C++ Pass @guomingz @hshen14

**Comment by hshen14** [comment]
这个是用v1的calibration tool支持新的模型，和infer_transpiler应该没关

**Comment by luotao1** [comment]
因为升级到V2了，后续都走C++ pass的统一接口，test_calibration不再进行扩充。

**Comment by hshen14** [comment]
了解

**Comment by wojtuss** [comment]
Closed, due to INT8v1 having been removed.
