### ISSUE TITLE
cpu版本finetune bert内存优化

### ISSUE THREAD

**Issue by daiwk** [PaddlePaddle/Paddle#16752]
使用 https://github.com/PaddlePaddle/LARK/tree/develop/BERT 中的run_classifier进行finetune，发现batchsize=1，max_seq_len=8的时候，使用cpu版本的paddle，如果机器的cpu是56核的，内存会占用114g…如果机器cpu是12核，会占用25g内存；想问问cpu下，是否有类似gpu的只使用几个卡的类似的设置方式呢：
```
export CUDA_VISIBLE_DEVICES=0,1,2,3,4
```

**Comment by xuezhong** [comment]
export CPU_NUM=x x就是希望的核数

**Comment by daiwk** [comment]
@xuezhong 已解决 谢谢
