### ISSUE TITLE
paddle embedding查找表是怎么训练出来的？不同业务自产的ID序列是否需要特殊处理

### ISSUE THREAD

**Issue by sshilei** [PaddlePaddle/Paddle#16768]
如果样本中某些ID有特殊含义，比如1是分隔符，2是无效ID之类的，是否需要特殊的设置。对于我样本中的无效ID查找表如何进行特殊处理？

**Comment by xuezhong** [comment]
不同业务自产的ID序列是否需要特殊处理？
特殊含义字符的一般也不用做特殊处理，放到一块训练。深度学习的好处就是不用特征工程
paddle embedding查找表是怎么训练出来的？
可以参考https://github.com/PaddlePaddle/book/blob/develop/04.word2vec/README.cn.md这个教程，最简单的w2v模型训练, 将onehot形式的id转化为低纬度空间中的向量

**Comment by guru4elephant** [comment]
@sshilei 可以在reader中把这些无效ID去掉，这样即使你的无效ID有对应的embedding参数，但训练过程中不学习，不影响效果。
