### ISSUE TITLE
1.3.1-gpu-cuda9.0-cudnn7 这个tag的Dockerfile在哪里呀？

### ISSUE THREAD

**Issue by tingweiwu** [PaddlePaddle/Paddle#16767]
Dockerhub上这个tag 1.3.1-gpu-cuda9.0-cudnn7镜像的Dockerfile在哪里呢？

https://github.com/PaddlePaddle/Paddle/blob/v1.3.1/Dockerfile  这里的是基于cuda8.0的呢

另外，Dockerhub上的镜像都是python2.7版本的吗？是否有python3+的？
检查了 1.3.1-gpu-cuda9.0-cudnn7  和 1.3.2-gpu-cuda9.0-cudnn7 都是py2.7的

**Comment by xuezhong** [comment]
目前支持得还不太全，一个办法是可以在镜像里面安装paddle 自己做个需要的镜像  可以参考首页http://paddlepaddle.org/
