### ISSUE TITLE
Compilation error on Nvidia Jetson TX2

### ISSUE THREAD

**Issue by susu3621** [PaddlePaddle/Paddle#16786]
I'm using the following command to do compilation.

cmake .. -DPY_VERSION=3.5 -DWITH_FLUID_ONLY=ON -DWITH_GPU=ON -DWITH_TESTING=OFF -DCMAKE_BUILD_TYPE=Release -DWITH_AVX=OFF -DWITH_MKL=OFF

There are 2 issues are found so far:
1. third_party/dgc is combined with WITH_GPU option.
But in we just want to do inference with single GPU, nccl is not necessary, and Jetson serials don't support nccl.

2. unrecognized command line option ‘-m64’
Seems we are not handling arch except x86 platform.

[  4%] Building CXX object paddle/fluid/platform/CMakeFiles/enforce.dir/enforce.cc.o
c++: error: unrecognized command line option ‘-m64’
paddle/fluid/platform/CMakeFiles/enforce.dir/build.make:62: recipe for target 'paddle/fluid/platform/CMakeFiles/enforce.dir/enforce.cc.o' failed
make[2]: *** [paddle/fluid/platform/CMakeFiles/enforce.dir/enforce.cc.o] Error 1
CMakeFiles/Makefile2:2538: recipe for target 'paddle/fluid/platform/CMakeFiles/enforce.dir/all' failed
make[1]: *** [paddle/fluid/platform/CMakeFiles/enforce.dir/all] Error 2
Makefile:149: recipe for target 'all' failed
make: *** [all] Error 2

If we can make make nccl support with anther build option, maybe we can help with  the arm platform build issue.

**Comment by susu3621** [comment]
BTW: the above result is based on branch origin/release/1.4

**Comment by sneaxiy** [comment]
Thanks for your question. Nccl and -m64 are needed in this repo. If you want to use Paddle in arm platform, please refer to https://github.com/PaddlePaddle/paddle-mobile.

**Comment by susu3621** [comment]
Hi @sneaxiy ，yes, we can compile and use paddle-mobile on this platform. But saddly mobile is not supporting GPU. Since arm device is also running Ubuntu 18.04, and have cuda10 and tensorRT 5, we believe it's more suitable to use the Paddle project.
