### ISSUE TITLE
C++预测模块，paddletensor如何处理二维lod_tensor

### ISSUE THREAD

**Issue by ws441572091** [PaddlePaddle/Paddle#16795]
例如一维的lod_tensor，当 batch = 2时，a和b分别为两个batch的输入
 格式为[[a1,a2,a3],[b1,b2]] 

C++输入：[a1,a2,a3,b1,b2], length = [3,2], batch =2 
C++转换：转换为paddletensor中的 tensor.lod = [[0,3]], tensor.shape = [5,1]

那么二维的lod_tensor,  当batch= 2时
格式为[[[a11],[a21,a22],[a31]],[[b11,b12,b13],[b21]]]

是否仍然以偏移量表示
C++转换：转换为paddletensor中的 tensor.lod = [[[0,1,3],[0,3]]]吗？
另外tensor.shape时多少，是[8,1]吗？

**Comment by Superjomn** [comment]
> C++输入：[a1,a2,a3,b1,b2], length = [3,2], batch =2
> C++转换：转换为paddletensor中的 tensor.lod = [[0,3]], tensor.shape = [5,1]

这个有问题， tensor.lod 应该是 `[[0, 3, 5]]`

> 那么二维的lod_tensor, 当batch= 2时
> 格式为[[[a11],[a21,a22],[a31]],[[b11,b12,b13],[b21]]]

Lod 每一层都是相对 offset
最底层lod :  `[0, 1, 3, 4, 7, 8]`
上一层： `[0, 3, 5]`
总的 lod 是： `[[0,3,5], [0,1,3,4,7,8]]`

shape 是 `num elements` ，跟 lod 没有关系，所以是 `[8,1]`


lod 格式比较复杂，下个版本我们会加个 helper 来自动转换。
