### ISSUE TITLE
Can paddlepaddle support  MPI based distributed training in multiple CPUs?

### ISSUE THREAD

**Issue by moting9** [PaddlePaddle/Paddle#1680]
Want to enable paddlepaddle distributed training in HPC environment with multiple CPUs which is MPI dominated.
Can paddlepaddle support MPI based distributed training in multiple CPUs？
Any suggestion is appreciated. 
Thanks.

**Comment by helinwang** [comment]
Sorry for late reply! We do support MPI, probably @Yancey1989, @typhoonzero or @reyoung  are more familiar, can you guys make some comment?

**Comment by moting9** [comment]
Thanks for the reply. look forward to more feedback.
In public paddlepaddle code,  only tcp socket and rdma socket communication is supported.  curious how to add mpi communication in such pserver/ptrainer topology. 
we expect paddlepaddle distributed training to run on mpi  for the following reason:

MPI is dominant in HPC domain,  and mpi performance on tcp layer is much worse than mpi on other layers such as PSM2.  so we expect paddlepaddle can directly run on mpi interface for distributed training to take advantage of the mpi performance on non-tcp layer.  Thanks.

**Comment by typhoonzero** [comment]
I've worked out a simple sample of running paddle v1 API distributed trainning on openmpi: https://github.com/typhoonzero/paddle-openmpi .

It's the simplest way so that you have to do training data split and copy to eatch node. We'll work on a solution to enable this on v2 API and with simpler way to use it.

**Comment by moting9** [comment]
Thanks!  The sample can be launched with MPIrun. But the pserver /ptrainer is communicated via socket over tcp/ip. Is it possible to have parameter exchange between pserver/ptrainer via mpi interface such as mpi_allreduce?

![mpi](https://cloud.githubusercontent.com/assets/24264611/24993605/af1cefb4-2059-11e7-9e27-546b12d62c8c.png)

**Comment by reyoung** [comment]
We do not have plan to use `mpi_allreduce` or other `mpi` interfaces in Paddle because `mpi` is not suitable for sparse data communication.

**Comment by moting9** [comment]
Thanks for the confirm. close it
