### ISSUE TITLE
Shall we need a cache API for every dataset module?

### ISSUE THREAD

**Issue by Yancey1989** [PaddlePaddle/Paddle#1684]
## 背景：
在做book的Docker Image时需要提前将dataset的数据缓存起来，尝试过以下方法：
- 用API直接下载的方式，类似
```
# Cache conll05
dataset.common.download(dataset.conll05.WORDDICT_URL, 'conll05st', \
                        dataset.conll05.WORDDICT_MD5)
```

缺点是每次增加一个dataset时，需要修改代码

- 反射moudle调用里面的test函数，类似:

```
for name filter(lambda x: not x.startswith("__"), dir(paddle.v2.dataset)):
    mod = importlib.import_module("paddle.v2.dataset.%s"%name)
    for method in filter(lambda x: x.startswith("test"), dir(mod)):
        getattr(mod, "test")()
```
但有存在`test`函数名字不一致，或者需要参数等情况。

## 建议

考虑在每个module加一个`cache_to_local()`的API来完成缓存的操作,这样缓存的操作会长成以下这样：
```

for name filter(lambda x: not x.startswith("__"), dir(paddle.v2.dataset)):
    getattr(importlib.import_module("paddle.v2.dataset.%s"%name), "cache_to_local")()

```

**Comment by reyoung** [comment]
`cache_to_local ` =>`fetch`/`download` 也许更好？

**Comment by gongweibao** [comment]
用户是否会觉得应该给download一个参数？@reyoung

**Comment by gongweibao** [comment]
哦。是不是download_to_cache()，可以打消用户填写参数的欲望。

**Comment by typhoonzero** [comment]
加一个base class，提供一个download接口，每个dataset实现这个接口？在demo执行的时候也可以直接调用这个接口。这样只需要对每个模块执行一次download方法即可

**Comment by Yancey1989** [comment]
这里 https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/v2/dataset/cifar.py 这里会下载两个gz包，所以加参数好像也不是很靠谱

**Comment by qingqing01** [comment]
是将数据也打包在Docker Image里吗？ 这样随着book的增多，Image的size会不会较大？

**Comment by Yancey1989** [comment]
@qingqing01 是的，考虑到用户的网络环境不同，让用户在运行Docker Image时下载数据会有下载失败的情况，对用户体验会有影响。

**Comment by Yancey1989** [comment]
@reyoung 
>`cache_to_local ` =>`fetch`/`download` 也许更好？

`download` +1
