### ISSUE TITLE
单独预测报错

### ISSUE THREAD

**Issue by ws441572091** [PaddlePaddle/Paddle#16869]
同一个预测函数，在每一轮训练之后进行预测没有问题，但是单独加载模型预测报错
<img width="1136" alt="image" src="https://user-images.githubusercontent.com/35720887/56120758-64619180-5fa1-11e9-9525-1c306a889e04.png">
预测函数：
![image](https://user-images.githubusercontent.com/35720887/56120832-8c50f500-5fa1-11e9-9c53-6fe4791c780b.png)
训练时使用：
![image](https://user-images.githubusercontent.com/35720887/56120855-9bd03e00-5fa1-11e9-90b0-3eab945d5e47.png)
单独使用：
![image](https://user-images.githubusercontent.com/35720887/56120877-a7bc0000-5fa1-11e9-9d3a-9978e33f73ae.png)

**Comment by wzzju** [comment]
请将227行改成`feeder = fluid.DataFeeder(feed_list=feed_targer_names, place=place, program=inference_program)`。额，你代码中`feed_targer_names`是不是拼写错误了，`feed_target_names`?

**Comment by ws441572091** [comment]
好的，已解决
