### ISSUE TITLE
test_softmax_with_cross_entropy_ngraph random fail

### ISSUE THREAD

**Issue by tensor-tang** [PaddlePaddle/Paddle#16870]
test_softmax_with_cross_entropy_ngraph_op
http://ci.paddlepaddle.org/viewLog.html?tab=buildLog&buildTypeId=Paddle_PrCi&buildId=84655

report from @tianshuo78520a 

Maybe related with test_softmax_with_cross_entropy_op
http://ci.paddlepaddle.org/viewLog.html?tab=buildLog&buildTypeId=Paddle_PrCi&buildId=84655

**Comment by baojun-nervana** [comment]
Is this fail related to the particular PR https://github.com/PaddlePaddle/Paddle/pull/16806 ? If so, it is easy to fix. I see heavengate already updated the unittest to make it pass. I can follow up after the PR is merged. I see the cross_entroy op and softmax_with_cross_entropy op are redefined.

**Comment by tensor-tang** [comment]
@tianshuo78520a This random fail seems not the problem based on develop branch.

**Comment by luotao1** [comment]
close due to #16806 merged
