### ISSUE TITLE
新版的paddle如何使用ranknet排序模型？

### ISSUE THREAD

**Issue by lvjianxin** [PaddlePaddle/Paddle#16886]
有没有example？老版的都找不到啦
http://www.paddlepaddle.org/documentation/models/zh/0.13.0/ltr/README.html
这个网页的demo找不到了

**Comment by jerrywgz** [comment]
https://github.com/PaddlePaddle/models/tree/develop/legacy/ltr
现在的模型放到这个目录下了，这个模型使用的是paddle v2版本

**Comment by lvjianxin** [comment]
no model named paddle.v2，请问有没有v2版本的安装说明，github上的安装文档链接报404


 
---原始邮件---
发件人: "jerrywgz"<notifications@github.com>
发送时间: 2019年4月16日(星期二) 中午11:31
收件人: "PaddlePaddle/Paddle"<Paddle@noreply.github.com>;
抄送: "Bruce Lv"<279141909@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [PaddlePaddle/Paddle] 新版的paddle如何使用ranknet排序模型？ (#16886)



https://github.com/PaddlePaddle/models/tree/develop/legacy/ltr
 现在的模型放到这个目录下了，这个模型使用的是paddle v2版本

**Comment by jerrywgz** [comment]
我们现在已经不再维护v2的代码了，安装fluid 1.0之前的版本会自带v2

**Comment by lvjianxin** [comment]
请问如何安装fluid 1.0之前版本呢，想测试一下排序效果


 
---原始邮件---
发件人: "jerrywgz"<notifications@github.com>
发送时间: 2019年4月16日(星期二) 下午3:47
收件人: "PaddlePaddle/Paddle"<Paddle@noreply.github.com>;
抄送: "Bruce Lv"<279141909@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [PaddlePaddle/Paddle] 新版的paddle如何使用ranknet排序模型？ (#16886)



我们现在已经不再维护v2的代码了，安装fluid 1.0之前的版本会自带v2

**Comment by jerrywgz** [comment]
请问你的cuda cudnn python版本分别是多少？

**Comment by jerrywgz** [comment]
http://www.paddlepaddle.org/documentation/docs/zh/1.0/beginners_guide/install/Start.html
可以参考这个文档

**Comment by lvjianxin** [comment]
centos7.3-python3.6.4-cuda8-cudnn6-tensorflow1.4.1-keras2.1.0-pytorch0.3.0


 
---原始邮件---
发件人: "jerrywgz"<notifications@github.com>
发送时间: 2019年4月16日(星期二) 下午4:14
收件人: "PaddlePaddle/Paddle"<Paddle@noreply.github.com>;
抄送: "Bruce Lv"<279141909@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [PaddlePaddle/Paddle] 新版的paddle如何使用ranknet排序模型？ (#16886)



请问你的cuda cudnn python版本分别是多少？

**Comment by jerrywgz** [comment]
我们目前还没有cudnn6可以直接pip安装的版本，需要进行源码编译，还是可以参考上面这个文档

**Comment by lvjianxin** [comment]
fluid1.0版本 Windows单机能跑吗


 
---原始邮件---
发件人: "jerrywgz"<notifications@github.com>
发送时间: 2019年4月16日(星期二) 下午5:59
收件人: "PaddlePaddle/Paddle"<Paddle@noreply.github.com>;
抄送: "Bruce Lv"<279141909@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [PaddlePaddle/Paddle] 新版的paddle如何使用ranknet排序模型？ (#16886)



我们目前还没有cudnn6可以直接pip安装的版本，需要进行源码编译，还是可以参考上面这个文档

**Comment by jerrywgz** [comment]
可以的，http://www.paddlepaddle.org/documentation/docs/zh/1.0/beginners_guide/install/install_Windows.html
