### ISSUE TITLE
paddle版本transformer的C++预测（GPU），开启config.SwitchIrOptim(),每个线程都只出同样的一个结果

### ISSUE THREAD

**Issue by Lizhengo** [PaddlePaddle/Paddle#16893]
paddle版本transformer的C++预测（GPU），开启config.SwitchIrOptim(),每个线程都只出同样的一个结果，无论是单卡单线程还是多卡多线程都是这样
关闭config.SwitchIrOptim()才预测正常

**Comment by NHZlX** [comment]
您好，请问使用的是哪个版本的代码，是最新的develop还是？
另外，方便贴一下预测的代码么
