### ISSUE TITLE
预测遇到报错

### ISSUE THREAD

**Issue by ws441572091** [PaddlePaddle/Paddle#16894]
1. 

保存模型时，feed的list中包含输入和labels
fluid.io.save_inference_model(tmp_params_dirname,['words','labels'],[crf_decode],exe)
预测的reader为 yield words，labels
数据例子：[42, 14, 127, 47, 6, 17, 79, 13, 60, 236, 16, 1111, 624, 3], [12, 6, 6, 0, 0, 0, 8, 5, 5, 5, 0, 7, 1, 0]
预测的代码如下，运行没有问题
![image](https://user-images.githubusercontent.com/35720887/56178814-295d6d80-6036-11e9-997a-fef65eba30cc.png)

2.

现在希望保存模型时，feed的list中只包含输入

fluid.io.save_inference_model(tmp_params_dirname,['words'],[crf_decode],exe)
预测的reader修为yield words
数据例子：[42, 14, 127, 47, 6, 17, 79, 13, 60, 236, 16, 1111, 624, 3]
报错：The number of fields in data (14) does not match len(feed_list) (1)

在外面加了一层list之后，数据例子：[[42, 14, 127, 47, 6, 17, 79, 13, 60, 236, 16, 1111, 624, 3]]
报错：The Input(Label) should be a 2-D tensor with the 2nd dimensions fixed to 1.

**Comment by jerrywgz** [comment]
这里的报错像是没有label数据导致的，可以检查下你在第二种情况下的模型里是否包含label

**Comment by ws441572091** [comment]
训练的时候在计算loss时会使用label,但是预测只需要用crf_decode就好，不需要label啊
![image](https://user-images.githubusercontent.com/35720887/56186224-58350d00-6051-11e9-9860-805c4777fd2e.png)

**Comment by ws441572091** [comment]
![image](https://user-images.githubusercontent.com/35720887/56186809-46546980-6053-11e9-8979-dbff9293b5d9.png)
确实报错的是86行没有label，但是crf_cost只是为了计算训练时的loss，在保存的模型中已经指出了需要的预测结果是crf_decode,为什么预测时不能跳过crf_cost,直接进行crf_decode

**Comment by ws441572091** [comment]
通过观察发现model里面的__model__会有save_inference_model的报错信息，但是没有看懂具体的错误是什么，初步怀疑是save_inference_model的时候报错，导致save_inference_model直接保存了这个模型图而不只是预测图，所以在运行load_inference_model中报错显示需要label信息

__model__文件，还包括许多其他报错信息：
[__model__.txt](https://github.com/PaddlePaddle/Paddle/files/3088511/__model__.txt)

**Comment by ws441572091** [comment]
保存训练模型代码
<img width="1003" alt="image" src="https://user-images.githubusercontent.com/35720887/56271789-e4b3fe00-612b-11e9-91c1-090da367524e.png">
