### ISSUE TITLE
fluid.layers.elementwise_div的值不符合预期

### ISSUE THREAD

**Issue by sshilei** [PaddlePaddle/Paddle#16912]
![image](https://user-images.githubusercontent.com/18701471/56194911-748f7480-6066-11e9-989a-dc4556ea4196.png)

![image](https://user-images.githubusercontent.com/18701471/56194942-86711780-6066-11e9-9c39-de3c3df571ff.png)

![image](https://user-images.githubusercontent.com/18701471/56194976-9688f700-6066-11e9-8bcb-5be30107c5f7.png)

**Comment by jerrywgz** [comment]
已通过设置persistable=True解决
