### ISSUE TITLE
After training, how to use the model trained by PaddlePaddle?

### ISSUE THREAD

**Issue by superzhangmch** [PaddlePaddle/Paddle#1692]
I am a new guy to PaddlePaddle.  I have sucessfully trained a model with a pretty good behavior on the testing data. But I don't know how to use it in online environment.  Even for offline, do I cannot find a way.

**Comment by riceCao** [comment]
I have the same question. Can anyone help us work out?
I knew someone made the prediction happen by running _python predict.py -c vgg_16_mnist.py -d ./data/raw_data/ -m mnist_vgg_model/pass-00037_ ,however, i did not find this related-predict file.
referenced link https://github.com/PaddlePaddle/Paddle/issues/1292

**Comment by helinwang** [comment]
@superzhangmch @riceCao Thanks guys for posting the question. Sorry for the late reply!
Please refer to https://github.com/PaddlePaddle/Paddle/blob/develop/demo/mnist/api_train_v2.py#L98 for saving model. And https://github.com/PaddlePaddle/Paddle/blob/develop/demo/mnist/api_train_v2.py#L76 for loading model.
At last, please see here for using PaddlePaddle docker image: https://github.com/PaddlePaddle/Paddle/blob/develop/doc/getstarted/build_and_install/docker_install_en.rst

**Comment by jekin000** [comment]
@helinwang , Thanks a lot!
