### ISSUE TITLE
exe.run返回fetch_list结果时，怎么获取到py_reader喂入的对应数据

### ISSUE THREAD

**Issue by tsaizehua** [PaddlePaddle/Paddle#16934]
transformer example在自己的数据上预测时，发现source的数目跟predict的数目不一致，想着能把source跟predict同时打印出来看看具体情况；但是不知如何才能在exe.run返回的结果中获取到py_reader对应的数据。

**Comment by guoshengCS** [comment]
这个可能是因为有一些长的句子被过滤掉了，可以试下在infer.py里加下这些内容，并在运行的时候重新设置下max_length和max_out_len

<img width="446" alt="dc174f498739eb63f55cc04a3880b7a7" src="https://user-images.githubusercontent.com/14105589/56288599-ae897500-6151-11e9-9d92-ae7dae61e6b9.png">


    for pos_enc_param_name in pos_enc_param_names:
        pos_enc_param = fluid.global_scope().find_var(
            pos_enc_param_name).get_tensor()

        pos_enc_param.set(
            position_encoding_init(ModelHyperParams.max_length + 1,
                                   ModelHyperParams.d_model), place)
