### ISSUE TITLE
fluid版本的预测，有多线层共享同一个模型来减少内存开销的功能吗

### ISSUE THREAD

**Issue by JayEworld** [PaddlePaddle/Paddle#16936]
v2版本有paddle_gradient_machine_create_shared_param接口，与其它gradient machine的共享已经加载的预测模型。这种情况多出现在使用多线程预测时，通过多个线程共享同一个模型来减少内存开销。可参考此示例。

**请问fluid版本有类似功能吗？现在都是通过clone模型来完成，但是内存消耗会比较大**

**Comment by Superjomn** [comment]
fluid 1.3 里面支持 clone，也就是多线程共享一套模型参数。

更进一步的优化是预测的 memory optimize，这个还没 ready，后续版本会 release。

**Comment by JayEworld** [comment]
> fluid 1.3 里面支持 clone，也就是多线程共享一套模型参数。

意思是现在的clone函数已经共享参数了是么？但是我设置不同的predictor个数，内存会变化非常大

这个代码看下有没有问题呢
![image](https://user-images.githubusercontent.com/16730384/56259513-e79bf800-6105-11e9-8bc0-58c98b6b5da4.png)

**Comment by Superjomn** [comment]
`CreatePaddlePredictor<paddle::AnalysisConfig>(config)`

这个试试，应该好很多

NativeConfig 优化不多，里面的 Clone 是 copy 的逻辑； AnalysisConfig 是我们一直优化的。
