### ISSUE TITLE
Why test compare sparse is turned off on travis CI

### ISSUE THREAD

**Issue by helinwang** [PaddlePaddle/Paddle#1694]
Today on @wangyang59 's local build, compare sparse is failing. So we were wondering how does it pass on travis CI. Then turns out that this test is turned off on travis CI (https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/trainer/tests/CMakeLists.txt#L50)

So we are wondering why this test is turned off on travis CI?

**Comment by typhoonzero** [comment]
Some of the tests need to start some local pservers to finish, and travis-ci seems does not support it.

I've also noticed that the build script on travis-ci and under docker are quite different, shall we merge them into one build procedure and pass different arguments when build on different environment?

**Comment by luotao1** [comment]
@helinwang sometimes test_compareSparse is ok, and sometimes fails. In my local build, this test is ok.

**Comment by helinwang** [comment]
@typhoonzero Sorry for the late reply! Yes I think travis-ci should run code for building similar to our docker release build procedure. Would be awesome if travis-ci could automatically push new image to dockerhub and China mirror if new tag is created.

**Comment by typhoonzero** [comment]
I've done some test of using travis-ci to release our docker images. Seems travis-ci only run each job for 50 minutes, but build all of the images spends too much time that travis-ci will eventually kill it.

I'll fire a PR once it is finished

**Comment by helinwang** [comment]
Teamcity CI is testing this:
```text
[22:14:57] :	 [Step 1/1] 59/73 Test #59: test_CompareSparse ..................   Passed  207.19 sec
```
http://19196ef4.ngrok.io/viewLog.html?buildId=1144&buildTypeId=Paddle_GpuUnittest&tab=buildLog
