### ISSUE TITLE
c++调用模型进行预测时出core

### ISSUE THREAD

**Issue by sunflowerlyb** [PaddlePaddle/Paddle#16947]
c++调用模型进行预测时出core
使用工具输入数据进行预测时：
![1](https://user-images.githubusercontent.com/15072355/56276753-b0ddd600-6135-11e9-86f9-63bc87f2d215.png)

 core信息：
![2](https://user-images.githubusercontent.com/15072355/56277088-3f525780-6136-11e9-9cac-df71ef827abc.png)
![3](https://user-images.githubusercontent.com/15072355/56277109-49745600-6136-11e9-939e-f23ebe1f56ee.png)

希望帮忙定位下是什么错误导致的呢？

**Comment by sunflowerlyb** [comment]
paddlepaddle的报错信息
![5](https://user-images.githubusercontent.com/15072355/56277431-ec2cd480-6136-11e9-8b31-6df421fd4458.png)

**Comment by Superjomn** [comment]
![image](https://user-images.githubusercontent.com/328693/56278146-52febd80-6138-11e9-970a-c77b701de859.png)

训练的版本是那个？  1.3 还是  1.3.1 ?

**Comment by sunflowerlyb** [comment]
训练的版本是1.3的

**Comment by sunflowerlyb** [comment]
> ![image](https://user-images.githubusercontent.com/328693/56278146-52febd80-6138-11e9-970a-c77b701de859.png)
> 
> 训练的版本是那个？ 1.3 还是 1.3.1 ?

训练的版本是1.3的

**Comment by Superjomn** [comment]
我们线下对下吧
