### ISSUE TITLE
多机训练如何clone一个用于测试的Program？

### ISSUE THREAD

**Issue by LeLiu** [PaddlePaddle/Paddle#16955]
> clone(for_test=False)
> 创建一个新的、相同的Program。
> 
> 有些operator，在训练和测试之间的行为是不同的，比如batch_norm。它们有一个属性is_test来控制行为。当for_test=True时，此方法将把它们的is_test属性更改为True。
> 
> 克隆Program，该Program用于训练时，将 for_test 设置为False。
> 克隆Program，该Program用于测试时，将 for_test 设置为True。
> 注意:此API不会删除任何操作符。请在backward和optimization之前使用clone(for_test=True)。
> 
> 代码示例
> 
> ```
> test_program = fluid.default_main_program().clone(for_test=True)
> optimizer = fluid.optimizer.Momentum(learning_rate=0.01, momentum=0.9)
> optimizer.minimize()
> ```

以上是官方文档关于clone的说明，在program中增加optimizer操作前不能克隆。但是在多机训练的时候，是要增加optimizer操作后才能transpile，根据这个逻辑transpile后我就不能克隆一个用于测试的Program了。我的理解正确吗？这种需求正常该如何操作？

transpile函数中的triner_id参数在角色为PSERVER的机器上代表什么意思？
http://paddlepaddle.org/documentation/docs/zh/1.3/api/transpiler.html#distributetranspiler

> Examples
> 
> ```
> # for pserver mode
> pserver_endpoints = "192.168.0.1:6174,192.168.0.2:6174"
> trainer_endpoints = "192.168.0.1:6174,192.168.0.2:6174"
> current_endpoint = "192.168.0.1:6174"
> trainer_id = 0
> trainers = 4
> role = os.getenv("PADDLE_TRAINING_ROLE")
> t = fluid.DistributeTranspiler()
> t.transpile(
>      trainer_id, pservers=pserver_endpoints, trainers=trainers)
> if role == "PSERVER":
>      pserver_program = t.get_pserver_program(current_endpoint)
>      pserver_startup_program = t.get_startup_program(current_endpoint,
>                                                     pserver_program)
> elif role == "TRAINER":
>      trainer_program = t.get_trainer_program()
> ...
> ```

官方文档中的例子中，trainer都指定了端口，而实际使用过程中trainer作为客户端口是随机分配的，而且我理解是不需要显示的设置trainer的IP，所以这样理解正确吗？还是说在NCCL模式下有特别的用处？

**Comment by wangguibao** [comment]
请问能了解一下为什么要clone一个transpile之后的program吗，transpile是为了分布式训练才把program重新排布一下，但是为了test的话，应该不需要transpile？

**Comment by LeLiu** [comment]
> 请问能了解一下为什么要clone一个transpile之后的program吗，transpile是为了分布式训练才把program重新排布一下，但是为了test的话，应该不需要transpile？

感谢您的回复。

我想在训练的时候在dev集合上测试，看下在train和dev上的gap和变化趋势来调整超参，并且在我认为较差的时候提前退出本轮以节省时间。我如何在多机训练的时候在dev上测试？

**Comment by jacquesqiao** [comment]
听起来不需要transpiler之后再clone，可以这样试试：
```python
def net():
   # train_network

with unique_name_guard():
    with program_gurad():
        with scope_guard():
           net()
           test_program = fluid.default_main_program.clone(for_test)
           exe.run(test_program)
```

**Comment by wangguibao** [comment]
另外 @LeLiu 这个地方是不是理解反了
```
以上是官方文档关于clone的说明，在program中增加optimizer操作前不能克隆
```
program.clone()本来就应该是在optimize之前做的

**Comment by LeLiu** [comment]
@jacquesqiao 我试了，这样是可以的。貌似就是要使用original_program来clone。

@wangguibao 在哪个位置clone我和您理解的一样，就是不清楚应该用哪个program来clone。现在已经清楚了。

对clone这块的一点小建议：
既然已经填了for_test=True，那么就应给内部把和test无关的optimize op给去掉，只在文档里写个注意，还是很容易被误用。在transpile之前和之后进行test的clone效果应该是一样的，因为对于测试来说，多机和单机应该保持一致，接口的语义也应该和实际相同。

**Comment by wangguibao** [comment]
用户提到的program.clone(for_test=True)应该自动把预测无关的optimize op去掉这个建议，我们会反馈给内部团队

**Comment by shuoyin** [comment]
> 听起来不需要transpiler之后再clone，可以这样试试：
> 
> ```python
> def net():
>    # train_network
> 
> with unique_name_guard():
>     with program_gurad():
>         with scope_guard():
>            net()
>            test_program = fluid.default_main_program.clone(for_test)
>            exe.run(test_program)
> ```

hi,你好。我现在模型里有一个分布式的embedding词表（DistributedLookupTable）,采用了您提供的方法，然后在validation的时候报错了，我的代码大概是这样的
```python
with fluid.program_guard(train_program, startup_program):
        with fluid.unique_name.guard():
            net()
            test_program = train_program.clone(for_test=True)

    with fluid.program_guard(train_program, startup_program):
        with fluid.unique_name.guard():
            sgd = fluid.optimizer.SGD(learning_rate=args.lr)
            sgd.minimize(model_loss)
```
报的错误主要是paddle.fluid.core_avx.EnforceNotMet: Invoke operator lookup_table error.
C++ Callstacks: 
holder_ should not be null
Tensor not initialized yet when Tensor::type() is called. at [/paddle/paddle/fluid/framework/tensor.h:139]

**Comment by wangguibao** [comment]
@shuoyin 只看这几行代码看不出来，您还是需要把代码和报错信息尽量多的贴一些，谢谢
