### ISSUE TITLE
Paddle如何进行CPU多线程训练，有demo吗？

### ISSUE THREAD

**Issue by dashulu** [PaddlePaddle/Paddle#16953]
Paddle CPU如何进行单机多线程训练？有demo吗？
另外，训练的过程中，多个线程是否共享同一个模型数据？多线程之间的梯度是每个线程都维护一份？如何进行梯度更新的？还是说单机多线程使用parameter server的方式进行参数更新？

**Comment by frankwhzhang** [comment]
https://github.com/PaddlePaddle/models/tree/develop/PaddleRec/word2vec 这个是我实现的模型，用的是cpu多线程 可以参考一下
