### ISSUE TITLE
docker build on CUDA 8

### ISSUE THREAD

**Issue by helinwang** [PaddlePaddle/Paddle#1695]
CUDA 7.5 images can not run on new generation Pascal architectures. A lot of GPUs are now pascal: GTX 1060, GTX 1070, GTX 1080, Pascal Titan X.

I think we need to switch to CUDA 8.0 for our docker images.

I tried to compile CUDA 8 by switch dev build dockerfile and production image dockerfile based on cuda-8. But it does not work:
When running paddle from built image, I got:
```text
ImportError: libcudart.so.7.5: cannot open shared object file: No such file or director
```
Maybe @gangliao understands more about the build process.

**Comment by hedaoyuan** [comment]
用ldd检查一下编译出来paddle_trainer是链接的那个cuda，这个错误信息看起来是链接的libcudart.so.7.5。
