### ISSUE TITLE
fluid.layers.Print 没有输出

### ISSUE THREAD

**Issue by sshilei** [PaddlePaddle/Paddle#16963]
![image](https://user-images.githubusercontent.com/18701471/56336466-18962e80-61d3-11e9-8983-00e2a68f8619.png)

程序会在169行报错，我在153行和167行加了Print调试一下，但是没有任何输出。 如果把169行改正确的话，Print就可以输出

**Comment by wangguibao** [comment]
试试这个
https://stackoverflow.com/a/37463806

**Comment by wangguibao** [comment]
fluid.layers.Print()是在program里增加一个print_op，print_op在运行时才起作用。

用户程序169行是在python端报错，还未开始训练，Print()还不能打印

已向用户解释。
