### ISSUE TITLE
多label图像分类

### ISSUE THREAD

**Issue by zhkfu** [PaddlePaddle/Paddle#16962]
做多分类的时候，程序执行到loss,lr =train_exe.run(train_prog, fetch_list=train_fetch_list) ，报错TypeError: run() got multiple values for keyword argument 'fetch_list'
程序代码 train_fetch_list =[train_cost.name,global_lr.name]
loss,lr =train_exe.run(train_prog, fetch_list=train_fetch_list)

**Comment by wangguibao** [comment]
用户用的ParallelExecutor，ParallelExecutor的run方法不带main_program参数

**Comment by Melonzhou** [comment]
我也遇到了这个问题，使用的是ParallelExecutor， 请问有什么解决办法吗？
![image](https://user-images.githubusercontent.com/5926307/56708482-61a82e80-674f-11e9-9bf1-2125667dc394.png)
![image](https://user-images.githubusercontent.com/5926307/56708493-708ee100-674f-11e9-9cdd-e8fe9d2f19f3.png)

**Comment by wangguibao** [comment]
@Melonzhou train_exe.run()方法不带program参数，这一行**要去掉compiled_prog参数**：
```
ret_avg_cost = train_exe.run(compiled_prog, feed={...}, fetch_list={...})
```

**Comment by Melonzhou** [comment]
> @Melonzhou train_exe.run()方法不带program参数，这一行**要去掉compiled_prog参数**：
> 
> ```
> ret_avg_cost = train_exe.run(compiled_prog, feed={...}, fetch_list={...})
> ```

去掉的话那不就是意味着不能用CompiledProgram了？

**Comment by wangguibao** [comment]
如果要用CompiledProgram接口，我看CompiledProgram例子是这样写的：
```
place = fluid.CUDAPlace(0) if use_cuda else fluid.CPUPlace()
        exe = fluid.Executor(place)
        exe.run(startup)
        compiled_prog = compiler.CompiledProgram(main).with_data_parallel(
            loss_name=loss.name)
        for i in range(5):
            test_loss, = exe.run(compiled_prog,
                                 feed=feed_dict,
                                 fetch_list=[loss.name])
```

这样`fluid.Executor`内部其实会用到ParallelExecutor去run

**Comment by Melonzhou** [comment]
> 如果要用CompiledProgram接口，我看CompiledProgram例子是这样写的：
> 
> ```
> place = fluid.CUDAPlace(0) if use_cuda else fluid.CPUPlace()
>         exe = fluid.Executor(place)
>         exe.run(startup)
>         compiled_prog = compiler.CompiledProgram(main).with_data_parallel(
>             loss_name=loss.name)
>         for i in range(5):
>             test_loss, = exe.run(compiled_prog,
>                                  feed=feed_dict,
>                                  fetch_list=[loss.name])
> ```
> 这样`fluid.Executor`内部其实会用到ParallelExecutor去run

哦哦，明白了，谢谢啦 ~
