### ISSUE TITLE
sequence_concat 出core

### ISSUE THREAD

**Issue by sshilei** [PaddlePaddle/Paddle#16960]
![image](https://user-images.githubusercontent.com/18701471/56330750-0eb50100-61bc-11e9-8e0d-ec11ba2a37c1.png)

sequnce_concat的输入都是 shape[1] 的序列， concat出错。

**Comment by sshilei** [comment]
![image](https://user-images.githubusercontent.com/18701471/56332290-49219c80-61c2-11e9-8aec-2f6b1da1ce02.png)

**Comment by wangguibao** [comment]
根据场景，用户换成layers.concat()了。更换layer以后也没有出core
