### ISSUE TITLE
Docker build fail with DYNAMIC_ARCH=1 for openblas

### ISSUE THREAD

**Issue by helinwang** [PaddlePaddle/Paddle#1697]
The related PR is https://github.com/PaddlePaddle/Paddle/pull/1691/files

I think normal build (the on travis uses) works, but docker build fails:

<img width="827" alt="981a8ffa279e937c5451c45bb" src="https://cloud.githubusercontent.com/assets/1724178/24232998/5549bd82-0f4c-11e7-889a-68e0d1483b73.png">

**Comment by gangliao** [comment]
Maybe we need to build cblas https://github.com/xianyi/OpenBLAS/issues/1134

**Comment by helinwang** [comment]
This issue is resolved after `rm -rf third_party build`. I think it's would be easier if `third_party` folder is located in `./build/`
