### ISSUE TITLE
centos保存模型错误，mac与centos 模型结构保存行为不一致，

### ISSUE THREAD

**Issue by oshixiaoxiliu** [PaddlePaddle/Paddle#16979]
使用以下代码保存模型结构，在centos、macos上行为不一致，centos上保存的结构错误

`
import os
import math
import paddle
import paddle.fluid as fluid
import sys
import time
use_cuda = False

def fake_model():
    fc_input = fluid.layers.data(name="fc_input", shape=[-1, 950], dtype='float32')
    fc0 = fluid.layers.fc(input=fc_input, size=256, act="tanh")
    fc1 = fluid.layers.fc(input=fc0, size=128, act="tanh")
    return fc_input, fc1

def fake_train():
    model_dir = "./fake_train__model"
    fc_input, fc1 = fake_model()
    place = fluid.CPUPlace()
    exe = fluid.Executor(place)
    exe.run(fluid.default_startup_program())
    fluid.io.save_inference_model(model_dir, [fc_input.name], [fc1], exe)
    
if __name__ == '__main__':
    fake_train()
`

centos上的保存出的结构如下，缺少了一个tanh激活函数，**期望是有一个tanh激活函数的**
![image](https://user-images.githubusercontent.com/4152372/56413146-14dcd780-62b9-11e9-9f3e-8265a82b26d1.png)

mac上保存出的结构如下，有tanh
![image](https://user-images.githubusercontent.com/4152372/56413214-4fdf0b00-62b9-11e9-99fa-b633e8233f83.png)

环境如下
paddle版本 1.3.2 
python版本 mac上为 Python 2.7.10 centos为Python 2.7.10

**Comment by Superjomn** [comment]
centos 上是1.3以上？

**Comment by oshixiaoxiliu** [comment]
> centos 上是1.3以上？

centos上paddle的版本和mac上的都是1.3.2
centos版本为CentOS release 6.3 (Final)
