### ISSUE TITLE
C++预测结果

### ISSUE THREAD

**Issue by ws441572091** [PaddlePaddle/Paddle#16971]
python中保存了预测模型，在python中使用预测模型进行预测，输出正常
![image](https://user-images.githubusercontent.com/35720887/56362896-836c5780-621d-11e9-9846-618856951a99.png)
使用此模型用C++进行预测
每个数字后面多了个0，
<img width="241" alt="image" src="https://user-images.githubusercontent.com/35720887/56362955-a0a12600-621d-11e9-9387-cbb6f2696091.png">
下面是我的C++预测代码，请问是哪里出了问题
![image](https://user-images.githubusercontent.com/35720887/56363045-de05b380-621d-11e9-93c2-c0a126365581.png)
其中在102行改成size*2才能看到这些结果，正确的话不应该每个数字后面多0，size就应该是正确结果

**Comment by wangguibao** [comment]
请确认一下fetch的数据类型是不是int？

**Comment by wangguibao** [comment]
和用户确认后，fetch variable类型应该是long int，在服务器上验证long int是8字节，而int是4字节。

用户改用long int解析output，已经符合预期。
