### ISSUE TITLE
建议修改test_conv2d_op.py中一个非测试case的名称

### ISSUE THREAD

**Issue by guomingz** [PaddlePaddle/Paddle#16987]
[testcuda](https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/fluid/tests/unittests/test_conv2d_op.py#L120) 是否可以修改为has_cuda(self)? 这里使用test开头，会被unittest认为是一个test case，尽管这不是。

**Comment by guomingz** [comment]
@luotao1  we can provide a simple PR for this suggestion if needed.

**Comment by luotao1** [comment]
请问这是会对int8单测造成影响么？

**Comment by guomingz** [comment]
> 请问这是会对int8单测造成影响么？

local 测试显示更改无影响 反而会加快ut，因为减少了不必要的测试(testcuda)。
