### ISSUE TITLE
如何获取训练过程中的所有梯度？

### ISSUE THREAD

**Issue by dashulu** [PaddlePaddle/Paddle#16980]
如何获取训练中的所有梯度，并且像模型一样保存下来？

**Comment by colourful-tree** [comment]
np.array(fluid.global_scope().find_var('embedding_name').get_tensor())

**Comment by dashulu** [comment]
@colourful-tree 有批量的接口吗？就像save model一样？

**Comment by colourful-tree** [comment]
好像没有哈

**Comment by dashulu** [comment]
按照np.array(fluid.global_scope().find_var('embedding_name').get_tensor())****方法，梯度无法获取，显示
![image](https://user-images.githubusercontent.com/4484303/56485721-c2452a80-6507-11e9-873d-d67b41498250.png)
请问是否有其他方式？

**Comment by heavengate** [comment]
fluid.default_main_program().list_vars()可以或者所有的Variable，其中name带@GRAD的都是梯度

**Comment by dashulu** [comment]
@heavengate  通过list_vars()是可以看到user.w@GRAD这个变量的，但是find_var时就是找不到
![image](https://user-images.githubusercontent.com/4484303/56486549-8c557580-650a-11e9-8303-cc2a224eab42.png)

**Comment by heavengate** [comment]
> @heavengate 通过list_vars()是可以看到user.w@GRAD这个变量的，但是find_var时就是找不到
> ![image](https://user-images.githubusercontent.com/4484303/56486549-8c557580-650a-11e9-8303-cc2a224eab42.png)

list_vars()的时候把var.persistable 打出来看下这个梯度是不是persistable的

**Comment by heavengate** [comment]
可以将 user.w@GRAD 加到fetch_list中，通过exe.run fetch出来
