### ISSUE TITLE
使用py_reader异步训练，save_inference_model报错

### ISSUE THREAD

**Issue by hexmiao** [PaddlePaddle/Paddle#16989]
环境信息：PaddlePaddle-1.4.0， CPU单机训练， Mac OS 10.10  Python 3.5
当训练完一个轮次，调用 fluid.io.save_inference_model 方法时，报以下错误：

 File "/Users/hex/paddle/lib/python3.5/site-packages/paddle/fluid/io.py", line 1000, in save_inference_model
    prepend_feed_ops(main_program, feeded_var_names)
  File "/Users/hex/paddle/lib/python3.5/site-packages/paddle/fluid/io.py", line 840, in prepend_feed_ops
    out = global_block.var(name)
  File "/Users/hex/paddle/lib/python3.5/site-packages/paddle/fluid/framework.py", line 1448, in var
    raise ValueError("var %s not in this block" % name)
ValueError: var input not in this block

**Comment by colourful-tree** [comment]
可以参照这样的写法：
fluid.io.save_inference_model(epoch_model, ["words"], [prediction], exe)

**Comment by hexmiao** [comment]
写法没有问题，同步训练的方式保存是正常，只是切换成py_reader的方式来训练就不行了！
fluid.io.save_inference_model 该方法里面，经过以下代码处理后，发现input 变量在global_block 已被移除，导致var input not in this block 错误
          
        main_program = main_program._prune(targets=target_vars)  

        main_program = main_program._inference_optimize(prune_read_op=True)
        fetch_var_names = [v.name for v in target_vars]
        
        #出错代码行
        prepend_feed_ops(main_program, feeded_var_names)

**Comment by paulpaul91** [comment]
input 变量在global_block 已被移除，导致var input not in this block 错误, 请问这个问题怎么解决
