### ISSUE TITLE
用SSD训练pascalvoc数据集时，训练了200个epoch，但Best test map一直在65%，一直上不去

### ISSUE THREAD

**Issue by wuxiaodong1014** [PaddlePaddle/Paddle#16992]
老师们好！我在运行咱们paddle官网上“目标检测”：https://github.com/PaddlePaddle/models/blob/develop/PaddleCV/object_detection/README_cn.md时，按照说明一步步来操作，能够正常训练。但是从第4个epoch开始 ，Best test map 的值，一直是0.652660250664，未变。训练到了200个epoch依然是0.652660250664。且best_model这个文件夹也一直没有更新。请问这可能是什么原因呢？不知道别的小伙伴有没有遇到这种情况。

**Comment by heavengate** [comment]
方便贴一下paddle版本，models版本，代码，训练命令，日志等相关信息么

**Comment by yeyupiaoling** [comment]
@wuxiaodong1014 你使用的是哪个预训练模型？如果使用的是ImageNet预训练模型，这个应该是差不多了吧。

**Comment by qingqing01** [comment]
@wuxiaodong1014  73.32%结果需要用`download_coco.sh`下载初始化模型，我们最近也验证了下
https://github.com/PaddlePaddle/models/pull/2143  是可以到的。 你可以更新到develop最新代码再试下。
