### ISSUE TITLE
模型训练过程中自动退出

### ISSUE THREAD

**Issue by sunflowerlyb** [PaddlePaddle/Paddle#17006]
你好，模型在训练过程中会自动退出，日志中无报错信息，cost值正常下降，请教一下是什么原因呢？
代码：
"""
This file is used to train the model.
"""
import os
import sys
import math
import time
import random
import argparse

import numpy as np
import paddle
import paddle.fluid as fluid

#import reader
from network import lex_net

def file_reader(file_dir,
                word2id_dict,
                label2id_dict,
                word_replace_dict,
                filename_feature=""):
    """
    define the reader to read files in file_dir
    """
    word_dict_len = max(map(int, word2id_dict.values())) + 1
    label_dict_len = max(map(int, label2id_dict.values())) + 1
    def reader():
        """
        the data generator
        """
        index = 0
        for root, dirs, files in os.walk(file_dir):
            for filename in files:
                if not filename.startswith(filename_feature):
                    continue
                cnt_org = 0
                cnt_res = 0
                for line in open(os.path.join(root, filename), 'r'):
                    cnt_org = cnt_org + 1
                    index += 1
                    bad_line = False
                    line = line.strip("\n")
                    if len(line) == 0:
                        continue
                    seg_tag = line.rfind("\t")
                    word_part = line[0:seg_tag]
                    label_part = line[seg_tag + 1:]
                    word_idx = []
		    seperator = chr(1)
                    words = word_part.split(seperator)
                    for word_tmp in words:
			word = word_tmp.decode('utf-8')
                        #if word in word_replace_dict:
                        #    word = word_replace_dict[word]
                        if word in word2id_dict:
                            word_idx.append(int(word2id_dict[word]))
                        else:
                            word_idx.append(int(word2id_dict["OOV"]))
                    target_idx = []
                    labels = label_part.strip().split(" ")
                    for label in labels:
                        if label in label2id_dict:
                            target_idx.append(int(label2id_dict[label]))
                        else:
                            target_idx.append(int(label2id_dict["O"]))
		    word_idx = word_idx[0:len(word_idx) - 1]
                    if len(word_idx) != len(target_idx):
                        continue             
		#    label_final = 0
		#    for i in range(len(word_idx) - 1, 0, -1):
		#        if (target_idx[i] != 0):
		#	    label_final = i
		#	    break
                    yield word_idx, target_idx
                    cnt_res = cnt_res + 1
                print file_dir, cnt_res, cnt_org
    return reader

def load_dict(dict_path):
    """
    Load a dict. The first column is the key and the second column is the value.
    """
    result_dict = {}
    for line in open(dict_path, "r"):
        terms = line.strip("\n").split("\t")
        if len(terms) != 2:
            continue
        result_dict[terms[0].decode("utf-8")] = terms[1].decode("utf-8")
    return result_dict

def load_reverse_dict(dict_path):
    """
    Load a dict. The first column is the value and the second column is the key.
    """
    result_dict = {}
    for line in open(dict_path, "r"):
        terms = line.strip("\n").split("\t")
        if len(terms) != 2:
            continue
        result_dict[terms[1].decode("utf-8")] = terms[0].decode("utf-8")
    return result_dict

def parse_args():
    """
    Parsing the input parameters.
    """
    parser = argparse.ArgumentParser("Training for lexical analyzer.")
    parser.add_argument(
        "--traindata_dir",
        type=str,
        default="./conf/train_data",
        #default="./data/train_data",
        help="The folder where the training data is located.")
    parser.add_argument(
        "--testdata_dir",
        type=str,
        default="./conf/test_data",
        help="The folder where the training data is located.")
    parser.add_argument(
        "--model_save_dir",
        type=str,
        default="./models",
        help="The model will be saved in this path.")
    parser.add_argument(
        "--save_model_per_batchs",
        type=int,
        default=5,
        help="Save the model once per xxxx batch of training")
    parser.add_argument(
        "--eval_window",
        type=int,
        default=20,
        help="Training will be suspended when the evaluation indicators on the validation set" \
             " no longer increase. The eval_window specifies the scope of the evaluation.")
    parser.add_argument(
        "--batch_size",
        type=int,
        default=40,
        help="The number of sequences contained in a mini-batch, or the maximum" \
             "number of tokens (include paddings) contained in a mini-batch.")
    parser.add_argument(
        "--corpus_type_list",
        type=str,
        #default=["human", "feed", "query", "title", "news"],
        default=["train_data"],
        nargs='+',
        help="The pattern list of different types of corpus used in training.")
    parser.add_argument(
        "--corpus_proportion_list",
        type=float,
        #default=[0.2, 0.2, 0.2, 0.2, 0.2],
        default=[1],
        nargs='+',
        help="The proportion list of different types of corpus used in training.")
    parser.add_argument(
        "--use_gpu",
        type=int,
        default=False,
        help="Whether or not to use GPU. 0-->CPU 1-->GPU")
    parser.add_argument(
        "--traindata_shuffle_buffer",
        type=int,
        default=200000,
        help="The buffer size used in shuffle the training data.")
    parser.add_argument(
        "--word_emb_dim",
        type=int,
        default=128,
        help="The dimension in which a word is embedded.")
    parser.add_argument(
        "--grnn_hidden_dim",
        type=int,
        default=256,
        help="The number of hidden nodes in the GRNN layer.")
    parser.add_argument(
        "--bigru_num",
        type=int,
        default=2,
        help="The number of bi_gru layers in the network.")
    parser.add_argument(
        "--base_learning_rate",
        type=float,
        default=(1e-3)/10,
        help="The basic learning rate that affects the entire network.")
    parser.add_argument(
        "--emb_learning_rate",
        type=float,
        default=5,
        help="The real learning rate of the embedding layer will be" \
        " (emb_learning_rate * base_learning_rate)."
    )
    parser.add_argument(
        "--crf_learning_rate",
        type=float,
        default=0.2,
        help="The real learning rate of the embedding layer will be" \
             " (crf_learning_rate * base_learning_rate)."
    )
    parser.add_argument(
        "--word_dict_path",
        type=str,
        default="./conf/word.txt",
        #default="./conf/word.dic",
        help="The path of the word dictionary."
    )
    parser.add_argument(
        "--label_dict_path",
        type=str,
        #default="./conf/tag.dic",
        default="./conf/label.txt",
        help="The path of the label dictionary."
    )
    parser.add_argument(
        "--word_rep_dict_path",
        type=str,
        default="./conf/q2b.dic",
        help="The path of the word replacement Dictionary."
    )
    parser.add_argument(
        "--num_iterations",
        type=int,
        default=0,
        help="The maximum number of iterations. If set to 0 (default), do not limit the number."
    )
    args = parser.parse_args()
    if len(args.corpus_proportion_list) != len(args.corpus_type_list):
        sys.stderr.write(
            "The length of corpus_proportion_list should be equal to the length of corpus_type_list.\n"
        )
        exit(-1)
    return args

def print_arguments(args):
    print('-----------  Configuration Arguments -----------')
    for arg, value in sorted(vars(args).iteritems()):
        print('%s: %s' % (arg, value))
    print('------------------------------------------------')

def to_lodtensor(data, place):
    """
    Convert data in list into lodtensor.
    """
    seq_lens = [len(seq) for seq in data]
    cur_len = 0
    lod = [cur_len]
    for l in seq_lens:
        cur_len += l
        lod.append(cur_len)
    flattened_data = np.concatenate(data, axis=0).astype("int64")
    flattened_data = flattened_data.reshape([len(flattened_data), 1])
    res = fluid.LoDTensor()
    res.set(flattened_data, place)
    res.set_lod([lod])
    return res

def test(exe, chunk_evaluator, inference_program, test_data, place,
         cur_fetch_list):
    """
    Test the network in training.
    """
    chunk_evaluator.reset()
    for data in test_data():
        word = to_lodtensor(map(lambda x: x[0], data), place)
        target = to_lodtensor(map(lambda x: x[1], data), place)
        result_list = exe.run(
            inference_program,
            feed={
                "word": word,
                "target": target
            },
            fetch_list=cur_fetch_list)
        number_infer = np.array(result_list[0])
        number_label = np.array(result_list[1])
        number_correct = np.array(result_list[2])
        chunk_evaluator.update(number_infer[0], number_label[0],
                               number_correct[0])
    return chunk_evaluator.eval()

def train(args):
    """
    Train the network.
    """
    if not os.path.exists(args.model_save_dir):
        os.mkdir(args.model_save_dir)

    word2id_dict = load_reverse_dict(args.word_dict_path)
    label2id_dict = load_reverse_dict(args.label_dict_path)
    word_rep_dict = load_dict(args.word_rep_dict_path)
    word_dict_len = max(map(int, word2id_dict.values())) + 1                
    label_dict_len = max(map(int, label2id_dict.values())) + 1 
    
    avg_cost, crf_decode, word, target= lex_net(args, word_dict_len, label_dict_len)
    sgd_optimizer = fluid.optimizer.SGD(learning_rate=args.base_learning_rate)
    sgd_optimizer.minimize(avg_cost)

    (precision, recall, f1_score, num_infer_chunks, num_label_chunks,
     num_correct_chunks) = fluid.layers.chunk_eval(
         input=crf_decode,
         label=target,
         chunk_scheme="IOB",
         num_chunk_types=int(math.ceil((label_dict_len - 1) / 2.0)))
    chunk_evaluator = fluid.metrics.ChunkEvaluator()
    chunk_evaluator.reset()
    inference_program = fluid.default_main_program().clone()
    with fluid.program_guard(inference_program):
    	inference_program = fluid.default_main_program().clone(for_test=True)
    train_reader_list = []
    corpus_num = len(args.corpus_type_list)
    for i in xrange(corpus_num):
        train_reader = paddle.batch(
            paddle.reader.shuffle(
                file_reader(args.traindata_dir,
                                            word2id_dict,
                                            label2id_dict,
                                            word_rep_dict,
                                            args.corpus_type_list[i]),
                buf_size=args.traindata_shuffle_buffer),
            batch_size=int(args.batch_size * args.corpus_proportion_list[i]))
        train_reader_list.append(train_reader)
    test_reader = paddle.batch(
        file_reader(args.testdata_dir, word2id_dict, label2id_dict, word_rep_dict),
        batch_size=args.batch_size)
    train_reader_itr_list = []
    for train_reader in train_reader_list:
        cur_reader_itr = train_reader()
        train_reader_itr_list.append(cur_reader_itr)

    place = fluid.CUDAPlace(0) if args.use_gpu else fluid.CPUPlace()
    feeder = fluid.DataFeeder(feed_list=[word, target], place=place)
    exe = fluid.Executor(place)
    exe.run(fluid.default_startup_program())
    batch_id = 0
    start_time = time.time()
    eval_list = []
    iter = 0
    while iter <= 30002:
        full_batch = []
        cur_batch = []
        for i in xrange(corpus_num):
            reader_itr = train_reader_itr_list[i]
            try:
                cur_batch = next(reader_itr)
            except StopIteration:
                print(args.corpus_type_list[i] +
                      " corpus finish a pass of training")
                new_reader = train_reader_list[i]
                train_reader_itr_list[i] = new_reader()
                cur_batch = next(train_reader_itr_list[i])
            full_batch += cur_batch
        random.shuffle(full_batch)

        cost_var, nums_infer, nums_label, nums_correct = exe.run(
            fluid.default_main_program(),
            fetch_list=[
                avg_cost, num_infer_chunks, num_label_chunks,
                num_correct_chunks
            ],
            feed=feeder.feed(full_batch))
        print("batch_id:" + str(batch_id) + ", avg_cost:" + str(cost_var[0]))
        chunk_evaluator.update(nums_infer, nums_label, nums_correct)
        batch_id += 1

        if (batch_id % args.save_model_per_batchs == 1):
            save_exe = fluid.Executor(place)
            save_dirname = os.path.join(args.model_save_dir,
                                        "params_batch_%d" % batch_id)
            fluid.io.save_inference_model(save_dirname, ['word'], [crf_decode],
                                          save_exe, main_program=inference_program)
            precision, recall, f1_score = chunk_evaluator.eval()
            print("[train] batch_id:" + str(batch_id) + ", precision:" +
                  str(precision) + ", recall:" + str(recall) + ", f1:" +
                  str(f1_score))
            chunk_evaluator.reset()
            p, r, f1 = test(
                exe, chunk_evaluator, inference_program, test_reader, place,
                [num_infer_chunks, num_label_chunks, num_correct_chunks])
            print("[test] batch_id:" + str(batch_id) + ", precision:" +
                  str(p) + ", recall:" + str(r) + ", f1:" + str(f1))
            end_time = time.time()
            print("cur_batch_id:" + str(batch_id) + ", last " +
                  str(args.save_model_per_batchs) + " batchs, time_cost:" +
                  str(end_time - start_time))
            start_time = time.time()

            if len(eval_list) < 2 * args.eval_window:
                eval_list.append(f1)
            else:
                eval_list.pop(0)
                eval_list.append(f1)
                last_avg_f1 = sum(
                    eval_list[0:args.eval_window]) / args.eval_window
                cur_avg_f1 = sum(eval_list[
                    args.eval_window:2 * args.eval_window]) / args.eval_window
                if cur_avg_f1 <= last_avg_f1:
                    return
                else:
                    print "keep training!"
        iter += 1
        if (iter == args.num_iterations):
            return

if __name__ == "__main__":
    args = parse_args()
    print_arguments(args)
    train(args)

日志：
-----------  Configuration Arguments -----------
base_learning_rate: 0.0001
batch_size: 40
bigru_num: 2
corpus_proportion_list: [1]
corpus_type_list: ['train_data']
crf_learning_rate: 0.2
emb_learning_rate: 5
eval_window: 20
grnn_hidden_dim: 256
label_dict_path: ./conf/label.txt
model_save_dir: ./models
num_iterations: 0
save_model_per_batchs: 5
testdata_dir: ./conf/test_data
traindata_dir: ./conf/train_data
traindata_shuffle_buffer: 200000
use_gpu: False
word_dict_path: ./conf/word.txt
word_emb_dim: 128
word_rep_dict_path: ./conf/q2b.dic
------------------------------------------------
./conf/train_data 1242 1242
batch_id:0, avg_cost:2179.0352
[train] batch_id:1, precision:[0.06589983], recall:[0.05200061], f1:[0.05813093]
./conf/test_data 241 241
[test] batch_id:1, precision:[0.95488913], recall:[0.97344898], f1:[0.96407974]
cur_batch_id:1, last 5 batchs, time_cost:55.996997118
batch_id:1, avg_cost:201.397
batch_id:2, avg_cost:195.12589
batch_id:3, avg_cost:197.31886
batch_id:4, avg_cost:198.17867
batch_id:5, avg_cost:216.80196
[train] batch_id:6, precision:[0.95453569], recall:[0.97335283], f1:[0.96385243]
./conf/test_data 241 241
[test] batch_id:6, precision:[0.95519874], recall:[0.97376461], f1:[0.96439233]
cur_batch_id:6, last 5 batchs, time_cost:76.8644471169
batch_id:6, avg_cost:188.77359
batch_id:7, avg_cost:190.17339
batch_id:8, avg_cost:185.80566
batch_id:9, avg_cost:207.06792
batch_id:10, avg_cost:172.13199
[train] batch_id:11, precision:[0.95519412], recall:[0.97394589], f1:[0.96447887]
./conf/test_data 241 241
[test] batch_id:11, precision:[0.95519874], recall:[0.97376461], f1:[0.96439233]
cur_batch_id:11, last 5 batchs, time_cost:76.8603959084
batch_id:11, avg_cost:186.4683
batch_id:12, avg_cost:190.73444
batch_id:13, avg_cost:197.28282
batch_id:14, avg_cost:198.26308
batch_id:15, avg_cost:201.36722
[train] batch_id:16, precision:[0.95534972], recall:[0.97375577], f1:[0.96446494]
./conf/test_data 241 241
[test] batch_id:16, precision:[0.95519874], recall:[0.97376461], f1:[0.96439233]
cur_batch_id:16, last 5 batchs, time_cost:79.713285923
batch_id:16, avg_cost:188.21878
batch_id:17, avg_cost:184.6235
batch_id:18, avg_cost:187.36221
batch_id:19, avg_cost:182.611
batch_id:20, avg_cost:182.33086
[train] batch_id:21, precision:[0.95621947], recall:[0.97425053], f1:[0.96515079]
./conf/test_data 241 241
[test] batch_id:21, precision:[0.95519874], recall:[0.97376461], f1:[0.96439233]
cur_batch_id:21, last 5 batchs, time_cost:78.9919850826
batch_id:21, avg_cost:180.34085
batch_id:22, avg_cost:186.19136
batch_id:23, avg_cost:190.14204
batch_id:24, avg_cost:186.67085
batch_id:25, avg_cost:194.69307
[train] batch_id:26, precision:[0.9557176], recall:[0.97416147], f1:[0.9648514]
./conf/test_data 241 241
[test] batch_id:26, precision:[0.95519874], recall:[0.97376461], f1:[0.96439233]
cur_batch_id:26, last 5 batchs, time_cost:78.3991529942
batch_id:26, avg_cost:168.20438
batch_id:27, avg_cost:227.61435
batch_id:28, avg_cost:171.51877
batch_id:29, avg_cost:183.67896
batch_id:30, avg_cost:186.93619
[train] batch_id:31, precision:[0.95509761], recall:[0.97412466], f1:[0.96451731]
./conf/test_data 241 241
[test] batch_id:31, precision:[0.95519874], recall:[0.97376461], f1:[0.96439233]
cur_batch_id:31, last 5 batchs, time_cost:77.8607211113
batch_id:31, avg_cost:218.96307
train_data corpus finish a pass of training
./conf/train_data 1242 1242
batch_id:32, avg_cost:186.4036
batch_id:33, avg_cost:181.5275
batch_id:34, avg_cost:189.85948
batch_id:35, avg_cost:163.7574
[train] batch_id:36, precision:[0.95596534], recall:[0.97431541], f1:[0.96505315]
./conf/test_data 241 241
[test] batch_id:36, precision:[0.95519874], recall:[0.97376461], f1:[0.96439233]
cur_batch_id:36, last 5 batchs, time_cost:75.3044800758
batch_id:36, avg_cost:155.23145
batch_id:37, avg_cost:183.1269
batch_id:38, avg_cost:194.3497
batch_id:39, avg_cost:179.31912
batch_id:40, avg_cost:173.75755
[train] batch_id:41, precision:[0.9559961], recall:[0.97421182], f1:[0.965018]
./conf/test_data 241 241
[test] batch_id:41, precision:[0.95519874], recall:[0.97376461], f1:[0.96439233]
cur_batch_id:41, last 5 batchs, time_cost:77.9997930527
batch_id:41, avg_cost:186.6453
batch_id:42, avg_cost:187.02847
batch_id:43, avg_cost:217.85957
batch_id:44, avg_cost:178.25395
batch_id:45, avg_cost:174.27505
[train] batch_id:46, precision:[0.95500105], recall:[0.97387386], f1:[0.96434512]
./conf/test_data 241 241
[test] batch_id:46, precision:[0.95519874], recall:[0.97376461], f1:[0.96439233]
cur_batch_id:46, last 5 batchs, time_cost:79.3493487835
batch_id:46, avg_cost:160.21164
batch_id:47, avg_cost:176.35843
batch_id:48, avg_cost:182.56248
batch_id:49, avg_cost:163.10474
batch_id:50, avg_cost:170.9408
[train] batch_id:51, precision:[0.95473414], recall:[0.97344922], f1:[0.96400086]
./conf/test_data 241 241
[test] batch_id:51, precision:[0.95519874], recall:[0.97376461], f1:[0.96439233]
cur_batch_id:51, last 5 batchs, time_cost:76.2578139305
batch_id:51, avg_cost:182.39621
batch_id:52, avg_cost:182.11084
batch_id:53, avg_cost:177.75412
batch_id:54, avg_cost:179.0194
batch_id:55, avg_cost:177.36002
[train] batch_id:56, precision:[0.95553686], recall:[0.97426191], f1:[0.96480854]
./conf/test_data 241 241
[test] batch_id:56, precision:[0.95519874], recall:[0.97376461], f1:[0.96439233]
cur_batch_id:56, last 5 batchs, time_cost:78.7749528885
batch_id:56, avg_cost:180.67923
batch_id:57, avg_cost:173.29
batch_id:58, avg_cost:181.93362
batch_id:59, avg_cost:167.58086
batch_id:60, avg_cost:176.13493
[train] batch_id:61, precision:[0.95527977], recall:[0.97407298], f1:[0.96458484]
./conf/test_data 241 241
[test] batch_id:61, precision:[0.95519874], recall:[0.97376461], f1:[0.96439233]
cur_batch_id:61, last 5 batchs, time_cost:78.1325769424
batch_id:61, avg_cost:165.13687
batch_id:62, avg_cost:173.32434
batch_id:63, avg_cost:177.95973
train_data corpus finish a pass of training
./conf/train_data 1242 1242
batch_id:64, avg_cost:169.67526
batch_id:65, avg_cost:183.35628
[train] batch_id:66, precision:[0.95419526], recall:[0.97343109], f1:[0.9637172]
./conf/test_data 241 241
[test] batch_id:66, precision:[0.95519874], recall:[0.97376461], f1:[0.96439233]
cur_batch_id:66, last 5 batchs, time_cost:72.8406820297
batch_id:66, avg_cost:170.41626
batch_id:67, avg_cost:166.57967
batch_id:68, avg_cost:165.3492
batch_id:69, avg_cost:166.82597
batch_id:70, avg_cost:170.34686
[train] batch_id:71, precision:[0.95778908], recall:[0.9750578], f1:[0.9663463]
./conf/test_data 241 241
[test] batch_id:71, precision:[0.95519874], recall:[0.97376461], f1:[0.96439233]
cur_batch_id:71, last 5 batchs, time_cost:80.418161869
batch_id:71, avg_cost:168.9687
batch_id:72, avg_cost:174.90625
batch_id:73, avg_cost:157.20847
batch_id:74, avg_cost:181.2568
batch_id:75, avg_cost:179.32904
[train] batch_id:76, precision:[0.95466047], recall:[0.97341772], f1:[0.96394785]
./conf/test_data 241 241
[test] batch_id:76, precision:[0.95519874], recall:[0.97376461], f1:[0.96439233]
cur_batch_id:76, last 5 batchs, time_cost:77.7075719833
batch_id:76, avg_cost:164.75253
batch_id:77, avg_cost:227.56743
batch_id:78, avg_cost:160.5148
batch_id:79, avg_cost:170.28079
batch_id:80, avg_cost:168.76785
[train] batch_id:81, precision:[0.95407752], recall:[0.97406515], f1:[0.96396774]
./conf/test_data 241 241
[test] batch_id:81, precision:[0.95519874], recall:[0.97376461], f1:[0.96439233]
cur_batch_id:81, last 5 batchs, time_cost:77.5919241905
batch_id:81, avg_cost:172.05551
batch_id:82, avg_cost:178.33621
batch_id:83, avg_cost:159.76016
batch_id:84, avg_cost:166.02124
batch_id:85, avg_cost:166.30484
[train] batch_id:86, precision:[0.95440647], recall:[0.97304384], f1:[0.96363505]
./conf/test_data 241 241
[test] batch_id:86, precision:[0.95519874], recall:[0.97376461], f1:[0.96439233]
cur_batch_id:86, last 5 batchs, time_cost:76.5915839672
batch_id:86, avg_cost:173.95786
batch_id:87, avg_cost:166.06761
batch_id:88, avg_cost:163.67905
batch_id:89, avg_cost:157.8635
batch_id:90, avg_cost:162.6392
[train] batch_id:91, precision:[0.95585817], recall:[0.97416795], f1:[0.96492621]
./conf/test_data 241 241
[test] batch_id:91, precision:[0.95519874], recall:[0.97376461], f1:[0.96439233]
cur_batch_id:91, last 5 batchs, time_cost:77.8657550812
batch_id:91, avg_cost:169.31091
batch_id:92, avg_cost:165.60446
batch_id:93, avg_cost:156.25443
batch_id:94, avg_cost:169.82889
batch_id:95, avg_cost:178.62819
[train] batch_id:96, precision:[0.95629451], recall:[0.97455497], f1:[0.9653384]
./conf/test_data 241 241
[test] batch_id:96, precision:[0.95519874], recall:[0.97376461], f1:[0.96439233]
cur_batch_id:96, last 5 batchs, time_cost:73.2651381493
train_data corpus finish a pass of training
./conf/train_data 1242 1242
batch_id:96, avg_cost:167.0712
batch_id:97, avg_cost:159.52267
batch_id:98, avg_cost:166.1258
batch_id:99, avg_cost:158.76329
batch_id:100, avg_cost:211.40762
[train] batch_id:101, precision:[0.95401242], recall:[0.97376442], f1:[0.96378723]
./conf/test_data 241 241
[test] batch_id:101, precision:[0.95519874], recall:[0.97376461], f1:[0.96439233]
cur_batch_id:101, last 5 batchs, time_cost:80.2748761177
batch_id:101, avg_cost:172.75159
batch_id:102, avg_cost:173.66623
batch_id:103, avg_cost:151.89725
batch_id:104, avg_cost:176.98523
batch_id:105, avg_cost:164.71585
[train] batch_id:106, precision:[0.95537799], recall:[0.97412489], f1:[0.96466037]
./conf/test_data 241 241
[test] batch_id:106, precision:[0.95519874], recall:[0.97376461], f1:[0.96439233]
cur_batch_id:106, last 5 batchs, time_cost:79.7745821476
batch_id:106, avg_cost:152.98386
batch_id:107, avg_cost:156.57333
batch_id:108, avg_cost:146.73149
batch_id:109, avg_cost:158.79655
batch_id:110, avg_cost:164.07103
[train] batch_id:111, precision:[0.95645627], recall:[0.97436807], f1:[0.96532909]
./conf/test_data 241 241
[test] batch_id:111, precision:[0.95519874], recall:[0.97376461], f1:[0.96439233]
cur_batch_id:111, last 5 batchs, time_cost:78.0702381134
batch_id:111, avg_cost:178.70955
batch_id:112, avg_cost:157.70956
batch_id:113, avg_cost:159.3383
batch_id:114, avg_cost:160.22583
batch_id:115, avg_cost:173.31291
[train] batch_id:116, precision:[0.95477524], recall:[0.97330863], f1:[0.96395286]
./conf/test_data 241 241
[test] batch_id:116, precision:[0.95519874], recall:[0.97376461], f1:[0.96439233]
cur_batch_id:116, last 5 batchs, time_cost:77.4131309986
batch_id:116, avg_cost:146.02261
batch_id:117, avg_cost:153.55276
batch_id:118, avg_cost:166.80077
batch_id:119, avg_cost:167.61752
batch_id:120, avg_cost:156.18916
[train] batch_id:121, precision:[0.95603595], recall:[0.97438214], f1:[0.96512186]
./conf/test_data 241 241
[test] batch_id:121, precision:[0.95519874], recall:[0.97376461], f1:[0.96439233]
cur_batch_id:121, last 5 batchs, time_cost:77.7746288776
batch_id:121, avg_cost:163.29385
batch_id:122, avg_cost:153.79953
batch_id:123, avg_cost:161.43678
batch_id:124, avg_cost:157.08916
batch_id:125, avg_cost:164.05002
[train] batch_id:126, precision:[0.95528321], recall:[0.97392973], f1:[0.96451636]
./conf/test_data 241 241
[test] batch_id:126, precision:[0.95519874], recall:[0.97376461], f1:[0.96439233]
cur_batch_id:126, last 5 batchs, time_cost:77.9396109581
batch_id:126, avg_cost:166.70036
batch_id:127, avg_cost:175.86777
train_data corpus finish a pass of training
./conf/train_data 1242 1242
batch_id:128, avg_cost:164.3735
batch_id:129, avg_cost:178.63455
batch_id:130, avg_cost:146.60262
[train] batch_id:131, precision:[0.95611381], recall:[0.97432123], f1:[0.96513166]
./conf/test_data 241 241
[test] batch_id:131, precision:[0.95519874], recall:[0.97376461], f1:[0.96439233]
cur_batch_id:131, last 5 batchs, time_cost:75.8542599678
batch_id:131, avg_cost:155.58679
batch_id:132, avg_cost:155.22531
batch_id:133, avg_cost:172.01651
batch_id:134, avg_cost:146.1984
batch_id:135, avg_cost:155.3292
[train] batch_id:136, precision:[0.95587602], recall:[0.97436192], f1:[0.96503045]
./conf/test_data 241 241
[test] batch_id:136, precision:[0.95519061], recall:[0.97371411], f1:[0.96436342]
cur_batch_id:136, last 5 batchs, time_cost:78.1983568668
batch_id:136, avg_cost:146.99606
batch_id:137, avg_cost:165.26291
batch_id:138, avg_cost:144.24207
batch_id:139, avg_cost:160.52567
batch_id:140, avg_cost:168.32672
[train] batch_id:141, precision:[0.95343275], recall:[0.97262369], f1:[0.96293261]
./conf/test_data 241 241
[test] batch_id:141, precision:[0.95520752], recall:[0.97369517], f1:[0.96436275]
cur_batch_id:141, last 5 batchs, time_cost:75.7425649166
batch_id:141, avg_cost:159.14854
batch_id:142, avg_cost:158.43042
batch_id:143, avg_cost:158.26663
batch_id:144, avg_cost:161.0039
batch_id:145, avg_cost:144.9355
[train] batch_id:146, precision:[0.95584289], recall:[0.97422911], f1:[0.96494843]
./conf/test_data 241 241
[test] batch_id:146, precision:[0.95520724], recall:[0.97368886], f1:[0.96435951]
cur_batch_id:146, last 5 batchs, time_cost:77.9459729195
batch_id:146, avg_cost:158.93105
batch_id:147, avg_cost:157.02377
batch_id:148, avg_cost:156.05531
batch_id:149, avg_cost:210.89087
batch_id:150, avg_cost:149.53195
[train] batch_id:151, precision:[0.95495303], recall:[0.97409425], f1:[0.96442868]
./conf/test_data 241 241
[test] batch_id:151, precision:[0.9552188], recall:[0.97368255], f1:[0.9643623]
cur_batch_id:151, last 5 batchs, time_cost:78.7867388725
batch_id:151, avg_cost:168.06015
batch_id:152, avg_cost:156.14238
batch_id:153, avg_cost:144.63618
batch_id:154, avg_cost:150.55669
batch_id:155, avg_cost:161.41411
[train] batch_id:156, precision:[0.95576108], recall:[0.97394585], f1:[0.96476778]
./conf/test_data 241 241
[test] batch_id:156, precision:[0.95522444], recall:[0.97367624], f1:[0.96436208]
cur_batch_id:156, last 5 batchs, time_cost:78.3030798435
batch_id:156, avg_cost:151.37659
batch_id:157, avg_cost:159.3527
batch_id:158, avg_cost:160.64645
batch_id:159, avg_cost:148.15167
train_data corpus finish a pass of training
./conf/train_data 1242 1242
batch_id:160, avg_cost:138.69118
[train] batch_id:161, precision:[0.95599991], recall:[0.97434015], f1:[0.96508291]
./conf/test_data 241 241
[test] batch_id:161, precision:[0.95523007], recall:[0.97366992], f1:[0.96436186]
cur_batch_id:161, last 5 batchs, time_cost:74.2825829983
batch_id:161, avg_cost:154.76208
batch_id:162, avg_cost:156.24988
batch_id:163, avg_cost:146.94304
batch_id:164, avg_cost:147.8795
batch_id:165, avg_cost:153.18503
[train] batch_id:166, precision:[0.95609516], recall:[0.97436201], f1:[0.96514216]
./conf/test_data 241 241
[test] batch_id:166, precision:[0.95523007], recall:[0.97366992], f1:[0.96436186]
cur_batch_id:166, last 5 batchs, time_cost:78.6564657688
batch_id:166, avg_cost:157.35341
batch_id:167, avg_cost:155.8477
batch_id:168, avg_cost:208.97722
batch_id:169, avg_cost:140.5709
batch_id:170, avg_cost:152.89584
[train] batch_id:171, precision:[0.95410393], recall:[0.97336313], f1:[0.96363732]
./conf/test_data 241 241
[test] batch_id:171, precision:[0.95525975], recall:[0.97353736], f1:[0.96431195]
cur_batch_id:171, last 5 batchs, time_cost:77.7744920254
batch_id:171, avg_cost:151.23085
batch_id:172, avg_cost:148.61942
batch_id:173, avg_cost:148.31181
batch_id:174, avg_cost:169.72078
batch_id:175, avg_cost:154.34772
[train] batch_id:176, precision:[0.95651953], recall:[0.97446233], f1:[0.96540757]
./conf/test_data 241 241
[test] batch_id:176, precision:[0.95522277], recall:[0.97363836], f1:[0.96434266]
cur_batch_id:176, last 5 batchs, time_cost:78.7199699879
batch_id:176, avg_cost:150.18999
batch_id:177, avg_cost:134.99252
batch_id:178, avg_cost:165.77875
batch_id:179, avg_cost:168.09982
batch_id:180, avg_cost:161.54416
[train] batch_id:181, precision:[0.95607227], recall:[0.97404752], f1:[0.9649762]
./conf/test_data 241 241
[test] batch_id:181, precision:[0.95523322], recall:[0.9736068], f1:[0.9643325]
cur_batch_id:181, last 5 batchs, time_cost:78.8202359676
batch_id:181, avg_cost:147.13618
batch_id:182, avg_cost:148.2308
batch_id:183, avg_cost:145.45749
batch_id:184, avg_cost:171.4704
batch_id:185, avg_cost:150.38826
[train] batch_id:186, precision:[0.95523988], recall:[0.97382153], f1:[0.96444121]
./conf/test_data 241 241
[test] batch_id:186, precision:[0.95533114], recall:[0.97341111], f1:[0.96428638]
cur_batch_id:186, last 5 batchs, time_cost:78.1423590183
batch_id:186, avg_cost:145.85135
batch_id:187, avg_cost:167.66414
batch_id:188, avg_cost:147.87837
batch_id:189, avg_cost:167.60172
batch_id:190, avg_cost:156.22656
[train] batch_id:191, precision:[0.95462191], recall:[0.97302303], f1:[0.96373464]
./conf/test_data 241 241
[test] batch_id:191, precision:[0.95533391], recall:[0.97347423], f1:[0.96431877]
cur_batch_id:191, last 5 batchs, time_cost:77.6048898697
batch_id:191, avg_cost:116.07391
train_data corpus finish a pass of training
./conf/train_data 1242 1242
batch_id:192, avg_cost:140.9844
batch_id:193, avg_cost:148.16249
batch_id:194, avg_cost:141.87637
batch_id:195, avg_cost:161.75247
[train] batch_id:196, precision:[0.95537511], recall:[0.97384361], f1:[0.96452096]
./conf/test_data 241 241
[test] batch_id:196, precision:[0.95536666], recall:[0.97341111], f1:[0.96430448]
cur_batch_id:196, last 5 batchs, time_cost:73.8427150249
batch_id:196, avg_cost:143.80501
batch_id:197, avg_cost:163.95894
batch_id:198, avg_cost:155.58122
batch_id:199, avg_cost:161.55777
batch_id:200, avg_cost:138.35738
[train] batch_id:201, precision:[0.95583561], recall:[0.97383089], f1:[0.96474934]
./conf/test_data 241 241
[test] batch_id:201, precision:[0.95538895], recall:[0.97337954], f1:[0.96430034]
cur_batch_id:201, last 5 batchs, time_cost:78.4884371758

辛苦帮忙看下什么原因吧？

**Comment by sunflowerlyb** [comment]
paddle版本1.2.0

**Comment by heavengate** [comment]
file_reader中遍历完一次数据后即返回，train函数中也只对reader调用过一次初始化，数据读完之后reader就没有数据yield出来，导致程序中止

**Comment by heavengate** [comment]
![image](https://user-images.githubusercontent.com/12605721/56482623-a5a0f680-64f7-11e9-89c9-bcbadc0ce5b3.png)
代码中主动退出

**Comment by sunflowerlyb** [comment]
多谢了
