### ISSUE TITLE
交通流预测训练时报F0323 13:21:31.180212 14883 Weight.cpp:28] Check failed: param->getSize() == width * height (64 vs. 0)

### ISSUE THREAD

**Issue by jeromeJT** [PaddlePaddle/Paddle#1700]
如题，并不出core，hang住不再继续运行

最初怀疑provider有问题，但是本地小数据集训练可以顺利进行，求帮助

- paddle_trainer.FATAL完整错误信息：

Log file created at: 2017/03/23 13:21:31
Running on machine: 
Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
F0323 13:21:31.180212 14883 Weight.cpp:28] Check failed: param->getSize() == width * height (64 vs. 0) 

- paddle_trainer.INFO信息：

Log file created at: 2017/03/23 13:21:26
Running on machine: nmg01-*
Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
I0323 13:21:26.771327 14883 Util.cpp:155] commandline: ./paddle_trainer --num_gradient_servers=75 --trainer_id=0 --pservers=10.73.* --rdma_tcp=tcp --nics=xgbe0 --port=7164 --ports_num=1 --load_missing_parameter_strategy=rand --saving_period_by_batches=4000 --config_args=is_cluster=1 --test_wait=1 --show_parameter_stats_period=100 --log_period=100 --trainer_count=11 --num_passes=30 --local=0 --config=conf/trainer_config.conf --save_dir=./output --use_gpu=0 
I0323 13:21:26.772786 14883 Util.cpp:130] Calling runInitFunctions
I0323 13:21:26.773114 14883 Util.cpp:143] Call runInitFunctions done.
I0323 13:21:30.094532 14883 Trainer.cpp:170] trainer mode: Normal
F0323 13:21:31.180212 14883 Weight.cpp:28] Check failed: param->getSize() == width * height (64 vs. 0) 

- 网络配置：

[trainer_config.conf.mult.indx.linkid.upload.txt](https://github.com/PaddlePaddle/Paddle/files/867387/trainer_config.conf.mult.indx.linkid.upload.txt)

**Comment by reyoung** [comment]
请将错误日志尽量截全。

**Comment by jeromeJT** [comment]
hi@reyoung，错误日志就只有这么多

**Comment by lcy-seso** [comment]
看不出来明显的错误，如果本地可以复现可以调试一下。

这个问题的一些线索如下，或可以供进一步排查/调试
1. 上面的错误是在网络初始化创建参数时发生的，和读取数据无关。
2. param->getSize()返回的是配置中计算出来的参数大小，网络中size = 64 的只有embeding layer的bias，因此可以初步推断是创建 bias 时遇到的问题
3. 从出错信息看 width * height = 0 ，对bias 参数，前者固定是1，后者是从配置中获取的 bias_size，配置解析结果我检查过，没有发现错误；

缺乏更多信息，暂无法确定原因。

**Comment by reyoung** [comment]
这个bug似乎是由 @qingqing01 的 #218 引入。

**Comment by qingqing01** [comment]
> 但是本地小数据集训练可以顺利进行，求帮助

本地可以运行，集群有问题，也就是本地和集群的版本不一致，本地是哪个版本呢？可以提供一个复现的环境的吗？

**Comment by Xreki** [comment]
暂时关闭，如有需要请重新打开。
