### ISSUE TITLE
save_inference_model的结果如何使用capi预测？

### ISSUE THREAD

**Issue by LokiLiu** [PaddlePaddle/Paddle#17002]
- 版本、环境信息：
    1）PaddlePaddle版本：0.12.0(v2)
    2）CPU：Intel(R) Xeon(R) CPU E5-2620 v2 @ 2.10GHz
    3）GPU：
    4）系统环境：Linux version 3.10.0_3-0-0-17

**Comment by heavengate** [comment]
请参考 http://www.paddlepaddle.org/documentation/docs/zh/1.4/advanced_usage/deploy/inference/native_infer.html
