### ISSUE TITLE
all pass can only apply to OPs in block 0

### ISSUE THREAD

**Issue by yihuaxu** [PaddlePaddle/Paddle#17003]
When using to apply the fuse passes into transformer model, we found that all pass can only apply to OPs in block 0.

details :
**System information**
-PaddlePaddle version 1.4
-CPU: all version

**Comment by luotao1** [comment]
related #15023. You can update #15023 which only fails on 
```
210 - test_pass_builder (Failed)
```

**Comment by sfraczek** [comment]
Why was it discontinued? I can see if I can finish that.

**Comment by luotao1** [comment]
@sfraczek 
> Why was it discontinued?

@Superjomn has some other high-priority works now.

>  I can see if I can finish that.

Hope your work!

**Comment by sfraczek** [comment]
Regarding that PR:
>This PR just support drawing graph.

**Comment by sfraczek** [comment]
I'm sorry I need to go back to optimizing current priority models. 
The graph drawing worked nicely after merging with latest develop. Unfortunately I didn't figure out any way how to iterate over ops in while_op chaning use_mkldnn attribute permanently so the problem remains. 
For someone who will pick this up, here is the approach that didn't work: https://github.com/sfraczek/Paddle/tree/set-mkldnn-inside-while

**Comment by luotao1** [comment]
> how to iterate over ops in while_op changing use_mkldnn attribute permanently so the problem remains.

Do you mean that if don't use `use_mkldnn` attribute, the problem could be solved?

**Comment by sfraczek** [comment]
Unfortunately no. I was just using `mkldnn_placement_pass` (which sets use_mkldnn=true) as an example. For the tests. It is a conceptually simple pass that should iterate over all operators include those in subgraph. I couldn't make it work.

**Comment by bingyanghuang** [comment]
@luotao1 Did we have any updates for this issue from your side?

**Comment by luotao1** [comment]
Our side doesn't have any update now. @bingyanghuang

**Comment by bingyanghuang** [comment]
This issue exists long time no solved. If there is any new tasks related to this issue, will open an new issue to track this.
