### ISSUE TITLE
paddle是否支持cuda10 v100的训练

### ISSUE THREAD

**Issue by alexqdh** [PaddlePaddle/Paddle#17016]
想问下paddle是否支持cuda10 v100的训练, dockerhub上没有找到对应的镜像
https://hub.docker.com/r/paddlepaddle/paddle/tags

**Comment by heavengate** [comment]
我们官方提供cuda9的镜像，如果是cuda10的话需要自己编译Paddle

**Comment by chyj4747** [comment]
> 我们官方提供cuda9的镜像，如果是cuda10的话需要自己编译Paddle

请问用VS2017能否编译？

**Comment by heavengate** [comment]
建议参考 http://paddlepaddle.org/documentation/docs/zh/1.4/beginners_guide/install/compile/fromsource.html 编译
