### ISSUE TITLE
模型在测试时正常，使用c++调用时预测失败

### ISSUE THREAD

**Issue by sunflowerlyb** [PaddlePaddle/Paddle#17025]
你好，模型训练paddle版本1.2.0，c++调用paddle版本1.3.0
问题：
同一个mcpack包，我在模型训练的时候，调用模型进行测试时，对特征标注正确，使用c++调用模型标注失败（未识别）

详细的输入序列及预测如下：
1、调用模型进行测试时，对特征标注正确，格式：输入tag    输入index    模型预测标注结果
![image](https://user-images.githubusercontent.com/15072355/56490262-28857980-6517-11e9-9ca6-8b6c63194c0b.png)
2、使用c++调用时预测失败，格式：输入tag    输入index    模型预测标注结果（未转化为标签名，不影响查看）
![image](https://user-images.githubusercontent.com/15072355/56490285-4226c100-6517-11e9-8798-647af6efca31.png)
从截图的输入序列上看差异并不大，只有空格有diff，其他基本是一样的，本模型共标注了12个字段，只有“avator”标注有问题，其他字段和测试时的准召都是一致的
辛苦帮忙看下是什么原因吧。

**Comment by heavengate** [comment]
请粘贴一下相关代码，谢谢

**Comment by heavengate** [comment]
C++输入数据空格未对齐，请对齐空格确认

**Comment by sunflowerlyb** [comment]
去掉空格后ok，多谢了
