### ISSUE TITLE
paddle.fluid.core.EnforceNotMet: Enforce failed. Expected x_mat_dims[1] == y_mat_dims[0]

### ISSUE THREAD

**Issue by wzgwzg** [PaddlePaddle/Paddle#17023]
**paddle version: 1.2.0**

**error information:**
Traceback (most recent call last):
  File "random_erasing_train.py", line 399, in <module>
    main()
  File "random_erasing_train.py", line 395, in main 
    train(args)
  File "random_erasing_train.py", line 345, in train
    fetch_list=train_fetch_list)
  File "/home/ssd1/vis/wangzhigang05/paddle_release_home/python/lib/python2.7/site-packages/paddle/fluid/parallel_executor.py", line 272, in run
    self.executor.run(fetch_list, fetch_var_name)
paddle.fluid.core.EnforceNotMet: Enforce failed. Expected x_mat_dims[1] == y_mat_dims[0], but received x_mat_dims[1]:30 != y_mat_dims[0]:512.
First matrix's width must be equal with second matrix's height. 30, 512 at [/paddle/paddle/fluid/operators/mul_op.cc:60]
PaddlePaddle Call Stacks: 
0       0x7fec4901ee86p paddle::platform::EnforceNotMet::EnforceNotMet(std::__exception_ptr::exception_ptr, char const*, int) + 486
1       0x7fec496aec89p paddle::operators::MulOp::InferShape(paddle::framework::InferShapeContext*) const + 2873 
2       0x7fec4a82594dp paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&) const + 77
3       0x7fec4a821c2fp paddle::framework::OperatorBase::Run(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&) + 463
4       0x7fec4a7e2a37p
5       0x7fec4a7ff3f0p
6       0x7fec4a7fec55p paddle::framework::details::OpHandleBase::RunAndRecordEvent(std::function<void ()> const&) + 805
7       0x7fec4a7e2530p paddle::framework::details::ComputationOpHandle::RunImpl() + 128
8       0x7fec4a7ffcf5p paddle::framework::details::OpHandleBase::Run(bool) + 117
9       0x7fec4a7645ddp
10      0x7fec490f9233p std::_Function_handler<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> (), std::__future_base::_Task_setter<std::unique_ptr<std::__future_base::_Result<void>, std::__future_base::_Result_base::_Deleter>, void> >::_M_invoke(std::_Any_data const&) + 35
11      0x7fec490f8a37p std::__future_base::_State_base::_M_do_set(std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> ()>&, bool&) + 39 
12      0x7fecaa10f973p pthread_once + 83 
13      0x7fec4a763622p
14      0x7fec490fad84p ThreadPool::ThreadPool(unsigned long)::{lambda()#1}::operator()() const + 404
15      0x7fec9a76b8a0p
16      0x7fecaa10a1c3p
17      0x7feca973212dp clone + 109

**code:**

class PCB_ResNet():

    def __init__(self, layers=50, num_classes=751, num_features=30, num_parts=6, is_train=True):
        self.params = train_parameters
        self.base = ResNet(layers)
        self.num_classes = num_classes
        self.num_features = num_features
        self.num_parts = num_parts
        self.is_train = is_train

    def part_pooling(self, x):
        part_height = int(x.shape[2] / self.num_parts)
        width = int(x.shape[3])
        print('part height: ', part_height)
        x = fluid.layers.pool2d(
                input=x, pool_size=(part_height, width), pool_type='avg',
                pool_stride=(part_height, width))
        return x

    def net(self, input):
        x_base = self.base.net(input, self.num_classes)
        print('base shape: ', x_base.shape)
        x_pp = self.part_pooling(x_base)
        print('part pooling shape: ', x_pp.shape)
        # if test, set is_test=True for dropout
        if self.is_train:
            x_pp = fluid.layers.dropout(x_pp, dropout_prob=0.5)
        else:
            x_pp = fluid.layers.dropout(x_pp, dropout_prob=0.5, is_test=True)
        if self.is_train:
            w_param_attrs = fluid.ParamAttr(learning_rate=10)
            x_red = fluid.layers.conv2d(
                    input=x_pp,
                    num_filters=self.num_features,
                    filter_size=1,
                    bias_attr=False,
                    param_attr=w_param_attrs,
                    name='red_conv')
            print('red conv shape: ', x_red.shape)
            x_red = fluid.layers.batch_norm(input=x_red, name='red_bn')
            x_red = fluid.layers.relu(x_red, name='red_relu')
            x_parts = fluid.layers.split(x_red, num_or_sections=6, dim=2)
            print('x parts shape: ', x_parts[0].shape, x_parts[5].shape)
            for part_idx in range(self.num_parts):
                part_name = 'fc_' + str(part_idx)
                x_parts[part_idx] = fluid.layers.fc(
                        input=x_parts[part_idx],
                        size=self.num_classes,
                        param_attr=fluid.ParamAttr(learning_rate=10,
                                  initializer=fluid.initializer.Normal(0.0,0.001)),
                        name=part_name)
            return x_parts
        else:
            x = fluid.layers.conv2d(
                    input=x,
                    num_filters=self.num_features,
                    filter_size=1,
                    bias_attr=False,
                    name='red_conv')
            x = fluid.layers.reshape(x, [x.shape[0], self.num_features * self.num_parts])
            x = fluid.layers.l2_normalize(x=x, axis=1)

        return x

**print information:**
base shape:  (-1L, 512L, 12L, 6L)
part height:  2
part pooling shape:  (-1L, 512L, 6L, 1L)
red conv shape:  (-1L, 30L, 6L, 1L)
x parts shape:  (-1L, 30L, 1L, 1L) (-1L, 30L, 1L, 1L)

**Comment by heavengate** [comment]
是train的时候报错还是test时候报错

**Comment by wzgwzg** [comment]
> 是train的时候报错还是test时候报错

train的时候

**Comment by heavengate** [comment]
有加载ResNet预训练权重么， ResNet(layers)里面有队ResNet结构做修改么

**Comment by wzgwzg** [comment]
> 有加载ResNet预训练权重么， ResNet(layers)里面有队ResNet结构做修改么

有加载权重，resnet就是把最后的stride改了，2改到1

**Comment by heavengate** [comment]
paddle中如何对模型进行剪裁？
  + 解答：加载预训练权重的时候误加载fc层
