### ISSUE TITLE
paddle中如何对模型进行剪裁？

### ISSUE THREAD

**Issue by dubhex** [PaddlePaddle/Paddle#17021]
想请问paddle中如何对模型进行剪裁？
具体为：
模型1的最后一层用全连接层输出100个值，模型已训练完成并使用io.save_inference或io.save_params保存了inference/params文件。
现需要一个输出50个值（与模型1前50值相同）的模型2，模型2除了输出全连接层输出数量与模型1不同外，其它均相同，也就是如何对模型1进行剪裁。
换个一角度，两个模型定义的.py文件，除了输出fc的数量不同，其与相同，如何进行对应赋值完成模型剪裁。
请问paddle中如何操作能达到上述目的？

**Comment by heavengate** [comment]
这种需要导入的时候对该层做特殊处理，参考https://github.com/PaddlePaddle/models/blob/f89fab5b0ada13558b902d30712562f97428aeb4/PaddleCV/video/models/stnet/stnet.py#L136

**Comment by dubhex** [comment]
> 这种需要导入的时候对该层做特殊处理，参考https://github.com/PaddlePaddle/models/blob/f89fab5b0ada13558b902d30712562f97428aeb4/PaddleCV/video/models/stnet/stnet.py#L136

这个导入是选择某些层的参数不导入吧？比如例子中，整个fc层的参数没导入，现在的情况是需要可以有选择的导入部分fc层的参数，有这种例子吗？

**Comment by heavengate** [comment]
建议搭网络的时候搭两个最后的fc层，一层100，一层50，先把权重导到100的那个fc中，然后参考  https://github.com/PaddlePaddle/models/blob/f89fab5b0ada13558b902d30712562f97428aeb4/PaddleCV/video/models/stnet/stnet.py#L136
中get和set的方法把裁剪的权重set到50的fc中，实际网络输出用50的fc的输出

**Comment by dubhex** [comment]
> 建议搭网络的时候搭两个最后的fc层，一层100，一层50，先把权重导到100的那个fc中，然后参考 https://github.com/PaddlePaddle/models/blob/f89fab5b0ada13558b902d30712562f97428aeb4/PaddleCV/video/models/stnet/stnet.py#L136
> 中get和set的方法把裁剪的权重set到50的fc中，实际网络输出用50的fc的输出

有两个fc层，这样最后使用io.save_inference保存网络的时候也会包输出100个值得那个fc给保存下来吧？现在的目的就是想通过剪裁fc保留特定输出，减小参数量，这样做应该不能达到这个目的？

**Comment by heavengate** [comment]
> > 建议搭网络的时候搭两个最后的fc层，一层100，一层50，先把权重导到100的那个fc中，然后参考 https://github.com/PaddlePaddle/models/blob/f89fab5b0ada13558b902d30712562f97428aeb4/PaddleCV/video/models/stnet/stnet.py#L136
> > 中get和set的方法把裁剪的权重set到50的fc中，实际网络输出用50的fc的输出
> 
> 有两个fc层，这样最后使用io.save_inference保存网络的时候也会包输出100个值得那个fc给保存下来吧？现在的目的就是想通过剪裁fc保留特定输出，减小参数量，这样做应该不能达到这个目的？

先写带100和50的fc为中间版本，转换权重后保存，然后删掉fc100的，重新load再save_inference

**Comment by mapingshuo** [comment]
> > 建议搭网络的时候搭两个最后的fc层，一层100，一层50，先把权重导到100的那个fc中，然后参考 https://github.com/PaddlePaddle/models/blob/f89fab5b0ada13558b902d30712562f97428aeb4/PaddleCV/video/models/stnet/stnet.py#L136
> > 中get和set的方法把裁剪的权重set到50的fc中，实际网络输出用50的fc的输出
> 
> 有两个fc层，这样最后使用io.save_inference保存网络的时候也会包输出100个值得那个fc给保存下来吧？现在的目的就是想通过剪裁fc保留特定输出，减小参数量，这样做应该不能达到这个目的？

你好，我正在做模型裁剪的工作：https://github.com/PaddlePaddle/Paddle/issues/19362。
