### ISSUE TITLE
如何指定在训练网络时指定参数偏移量名字？

### ISSUE THREAD

**Issue by zds9204** [PaddlePaddle/Paddle#17032]
训练中，代码如下：
content_subtitle_conv = nets.sequence_conv_pool(
        input=content_subtitle_emb,
        num_filters=32,
        filter_size=3,
        act="relu",
        pool_type="average",
        param_attr='content_subtitle_conv')

用这种方式指定层的名字，只能指定一部分参数。 还会出现sequence_conv_0.b_0。请问这个参数如何指定名字？

**Comment by heavengate** [comment]
<img width="355" alt="conv_pool" src="https://user-images.githubusercontent.com/12605721/56501939-47016a00-6543-11e9-9f0e-57f80200c136.png">
sequence_conv_pool有param_attr和bias_attr参数，分别制定w和b的attr，可通过类似https://github.com/PaddlePaddle/models/blob/18d7c658648056c81962c96442f0fa2b15b4c95d/PaddleCV/yolov3/models/darknet.py#L44   的方式制定两个Variable的名字

**Comment by zds9204** [comment]
有用。多谢了
