### ISSUE TITLE
Run small_vgg wrong

### ISSUE THREAD

**Issue by heiyexingchen** [PaddlePaddle/Paddle#1704]
1. I convert a 15 * 15 matrix into a 1 * 225 one-dimensional vector as input data for small_vgg. In the training can output layers of information, but the following error:
**
I0325 02:12:46.702256    86 Trainer.cpp:170] trainer mode: Normal
F0325 02:12:46.944080    86 ThreadLocal.h:55] Check failed: pthread_key_create(&threadSpecificKey_, dataDestructor) == 0 : No such file or directory [2]
*** Check failure stack trace: ***
    @     0x7fd597707daa  (unknown)
    @     0x7fd597707ce4  (unknown)
    @     0x7fd5977076e6  (unknown)
    @     0x7fd5977074fb  (unknown)
    @     0x7fd597708477  (unknown)
    @           0x779e27  paddle::ThreadLocal<>::ThreadLocal()
    @           0x7786ef  paddle::Parameter::setMat()
    @           0x53acfe  paddle::Parameter::enableType()
    @           0x543b9d  _ZNSt17_Function_handlerIFviPN6paddle9ParameterEEZNS0_20MultiGradientMachineC1ERKNS0_11ModelConfigEbEUliS2_E_E9_M_invokeERKSt9_Any_dataiS2_
    @           0x539923  paddle::NeuralNetwork::init()
    @           0x5479d2  paddle::MultiGradientMachine::MultiGradientMachine()
    @           0x53efde  paddle::GradientMachine::create()
    @           0x67bc98  paddle::TrainerInternal::init()
    @           0x6783ee  paddle::Trainer::init()
    @           0x5132a9  main
    @     0x7fd596913f45  (unknown)
    @           0x51f2a5  (unknown)
    @              (nil)  (unknown)
/usr/local/bin/paddle: line 109:    86 Aborted                 ${DEBUGGER} $MYDIR/../opt/paddle/bin/paddle_trainer ${@:2}
**

2.In the classification problem, such as digital recognition, a total of only 10 categories, in the definition of input data, integer_value (num) in the num is 10 or 1?
settings.slots = [dense_vector(settings.data_size), integer_value(10)]？
settings.slots = [dense_vector(settings.data_size), integer_value(1)]？

**Comment by heiyexingchen** [comment]
1、我将15 * 15矩阵转换为1 * 225一维向量作为small_vgg的输入数据。 在训练中可以输出层次的信息，但是出现以下错误：
**
I0325 02:12:46.702256 86 Trainer.cpp:170] trainer mode: Normal
F0325 02:12:46.944080 86 ThreadLocal.h:55] Check failed: pthread_key_create(&threadSpecificKey_, dataDestructor) == 0 : No such file or directory [2]
*** Check failure stack trace: ***

2、在分类问题中，如数字识别，总共只有10个类别，在定义输入数据时，num_value（num）中的num为10或1？
settings.slots = [dense_vector（settings.data_size），integer_value（10）]？
settings.slots = [dense_vector（settings.data_size），integer_value（1）]？

**Comment by qingqing01** [comment]
@heiyexingchen 第1个问题，你使用的是什么paddle版本信息是啥呢？ `paddle version` 可以查看。

第2个问题： settings.slots = [dense_vector（settings.data_size），integer_value（10）]？ 这种吧~

**Comment by heiyexingchen** [comment]
@qingqing01 很感谢你的回答，给你看一下我的paddle信息，不知道有什么关系
PaddlePaddle 0.9.0a0, compiled with
    with_avx: ON
    with_gpu: OFF
    with_double: OFF
    with_python: ON
    with_rdma: OFF
    with_glog: ON
    with_gflags: ON
    with_metric_learning: 
    with_timer: OFF
    with_predict_sdk:

**Comment by qingqing01** [comment]
我看你的输入是 15 * 15 的图片，网络解析部分输出的 c,h,w信息有没有出现为0的？

**Comment by heiyexingchen** [comment]
@qingqing01 你说的这几个参数我没有看到，不知道你指的是什么参数？不过经你提醒，我将train.sh中的trainer_count改为1，就不再报错了，但是我的这个程序好吃内存啊，电脑根本hold不住。源程序有这么两条语句：
for i in xrange(FORECASTING_NUM):
    predict = samll_vgg(traffic_data_layer)

不知道把这个small_vgg放到for循环外面会有多大影响，但是放到外面确实准确度降低了一点，我做了测试的

**Comment by qingqing01** [comment]
> pthread_key_create(&threadSpecificKey_, dataDestructor) == 0 : No such file or directory [2]
*** Check failure stack trace: *** 

这个错误输出 `No such file or directory` 和 这行代码看着不太符合：https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/utils/ThreadLocal.h#L54  

small_vgg放在for循环里外和网络连接有关吧，你贴的代码: `predict = samll_vgg(traffic_data_layer)` 这个 和 for循环看着没啥关系吧？ small_vgg这个确实比较好内存一些，看你的输入数据貌似不大，15*15，你也可以减小模型吧。

**Comment by heiyexingchen** [comment]
@qingqing01   我已经更换模型了
