### ISSUE TITLE
v2 训练的model，该如何利用fluid预测

### ISSUE THREAD

**Issue by 930083287** [PaddlePaddle/Paddle#17056]
虽然https://github.com/PaddlePaddle/Paddle/issues/12819 这个issue有相关解释，但是并没有完全解决，目前我们可以转换了参数，但是后面如何load模型？烦请解析一下

**Comment by xiaohuanghuasyy** [comment]
```
import sys
import numpy
import paddle.fluid as fluid
from PIL import Image
import numpy as np
import ast

def load_parameter_old(file_name):
    with open(file_name, 'rb') as f:
        f.read(16)  # skip header.
        return np.fromfile(f, dtype=np.float32)

def load_param(name_map_file, old_param_dir):
    result = {}
    name_map = {}
    shape_map = {}
    with open(name_map_file, 'r') as map_file:
        for param in map_file:
            old_name, new_name, shape = param.strip().split('=')
            name_map[new_name] = old_name
            shape_map[new_name] = ast.literal_eval(shape)

    for new_name in name_map:
        #print(new_name)
        #print(shape_map[new_name])
        #print(load_parameter_old("/".join([old_param_dir, name_map[new_name]])).shape)
        
        try:
            result[new_name] = load_parameter_old("/".join(
                    [old_param_dir, name_map[new_name]])).reshape(shape_map[new_name])
            #print(new_name)
        except Exception:
            print "new_name",new_name,shape_map[new_name],load_parameter_old("/".join([old_param_dir, name_map[new_name]])).shape

    return result


def load_parameter(place):
    params = load_param('./trans.map', './model/')
    for name in params:
        # 造个tensor
        data = params[name]
        print data.shape
        input=fluid.layers.create_tensor(dtype='float32', persistable=True, name=name)
        fluid.layers.assign(input=data, output=input)
        t = fluid.global_scope().find_var(input).get_tensor()
        t.set(params[name], place)

def trans(use_cuda,model_path):
    """
    """
    # 是否使用GPU
    place = fluid.CUDAPlace(0) if use_cuda else fluid.CPUPlace()
    # 生成调试器
    exe = fluid.Executor(place)
    exe.run(fluid.default_startup_program())
    load_parameter(place)
    #fluid.io.load_vars(exe, pretrained_model, main_program=train_prog, predicate=if_exist)
    # 保存预测的模型
    #fluid.io.save_inference_model(model_path, ['image'], [predict], exe)


if __name__ == '__main__':
    image_file = './1.jpg'
    #model_path = sys.argv[1]
    model_path = "./new_model/__model__"
    trans(False, model_path)

```

**Comment by shippingwang** [comment]
1. 首先搭建好fluid实现的VGG16，详细参考 https://github.com/PaddlePaddle/models/blob/develop/PaddleCV/image_classification/models/vgg.py
2. 

```
def load_parameter(place):
    params = load_param('map文件', 'V2文件')
    for name in params:
        t = fluid.global_scope().find_var(name).get_tensor()
        t.set(params[name], place)
```
3. tensor set后 网络中已经load好params ，不用写load_vars了

**Comment by xiaohuanghuasyy** [comment]
模型转换完成后我保存了准换后的模型，用于预测时会报错。求帮助，感谢～
再如上代码基础上增加如下保存代码：
```
   # 如果保存路径不存在就创建
    if not os.path.exists(model_path):
        os.makedirs(model_path)
    # 保存预测的模型
    fluid.io.save_inference_model(model_path, ['image'], [model], exe)
预测代码：
import numpy
import paddle.fluid as fluid
import paddle
from PIL import Image
import numpy as np

def infer(image_file, use_cuda, model_path):
    # 是否使用GPU
    place = fluid.CUDAPlace(0) if use_cuda else fluid.CPUPlace()
    # 生成调试器
    exe = fluid.Executor(place)

    inference_scope = fluid.core.Scope()
    with fluid.scope_guard(inference_scope):
        # 加载模型
        [inference_program, feed_target_names, fetch_targets] = fluid.io.load_inference_model(model_path, exe)
        # 获取预测数据
        img = Image.open(image_file)
        img = img.resize((256, 256), Image.ANTIALIAS)
        test_data = np.array(img).astype("float32")
        test_data = np.transpose(test_data, (2, 0, 1))
        test_data = test_data[np.newaxis, :] / 255.0
        print test_data.shape
        # 开始预测
        results = exe.run(inference_program,
                          feed={feed_target_names[0]: test_data},
                          fetch_list=fetch_targets)

        results = np.argsort(-results[0])
        # 打印预测结果
        print "The images/horse4.png infer results label is: ", results[0][0]


if __name__ == '__main__':
    image_file = './business_license_train/business_license_rrr_1000_0.jpg'
    #model_path = '../models/0/'
    model_path = './new_model/'
    infer(image_file, False, model_path)
```
报错信息：
Traceback (most recent call last):
  File "infer.py", line 51, in <module>
    infer(image_file, False, model_path)
  File "infer.py", line 40, in infer
    fetch_list=fetch_targets)
  File "/home/users/huangxueyuan01/local/python2.7.16/lib/python2.7/site-packages/paddle/fluid/executor.py", line 525, in run
    use_program_cache=use_program_cache)
  File "/home/users/huangxueyuan01/local/python2.7.16/lib/python2.7/site-packages/paddle/fluid/executor.py", line 591, in _run
    exe.run(program.desc, scope, 0, True, True)
paddle.fluid.core.EnforceNotMet: Invoke operator batch_norm error.
Python Callstacks: 
  File "/home/users/huangxueyuan01/local/python2.7.16/lib/python2.7/site-packages/paddle/fluid/framework.py", line 1317, in append_op
    attrs=kwargs.get("attrs", None))
  File "/home/users/huangxueyuan01/local/python2.7.16/lib/python2.7/site-packages/paddle/fluid/layer_helper.py", line 56, in append_op
    return self.main_program.current_block().append_op(*args, **kwargs)
  File "/home/users/huangxueyuan01/local/python2.7.16/lib/python2.7/site-packages/paddle/fluid/layers/nn.py", line 2936, in batch_norm
    "use_global_stats": use_global_stats
  File "/home/users/huangxueyuan01/local/python2.7.16/lib/python2.7/site-packages/paddle/fluid/nets.py", line 234, in img_conv_group
    tmp = layers.batch_norm(input=tmp, act=conv_act, in_place=True)
  File "/home/users/huangxueyuan01/code_version/cxmodel_clone_0412/baidu/cop-chengxin/cxmodel/app/auto_classification/src/fluid_train/vgg.py", line 30, in conv_block
    pool_type='max')
  File "/home/users/huangxueyuan01/code_version/cxmodel_clone_0412/baidu/cop-chengxin/cxmodel/app/auto_classification/src/fluid_train/vgg.py", line 32, in vgg16_bn_drop
    conv1 = conv_block(input, 64, 2, [0.3, 0])
  File "trans.py", line 94, in trans
    model= vgg16_bn_drop(image, class_dim)
  File "trans.py", line 116, in <module>
    trans(False, model_path)
C++ Callstacks: 
Enforce failed. Expected ctx->GetInputDim("Scale")[0] == C, but received ctx->GetInputDim("Scale")[0]:512 != C:64.
 at [/paddle/paddle/fluid/operators/batch_norm_op.cc:60]
PaddlePaddle Call Stacks: 
0       0x7eff4600659dp void paddle::platform::EnforceNotMet::Init<std::string>(std::string, char const*, int) + 365
1       0x7eff460068e7p paddle::platform::EnforceNotMet::EnforceNotMet(std::string const&, char const*, int) + 87
2       0x7eff465ee818p paddle::operators::BatchNormOp::InferShape(paddle::framework::InferShapeContext*) const + 8120
3       0x7eff46fcac5bp paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&) const + 603
4       0x7eff46fc97bbp paddle::framework::OperatorBase::Run(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&) + 267
5       0x7eff4611b042p paddle::framework::Executor::RunPreparedContext(paddle::framework::ExecutorPrepareContext*, paddle::framework::Scope*, bool, bool, bool) + 226
6       0x7eff4611c105p paddle::framework::Executor::Run(paddle::framework::ProgramDesc const&, paddle::framework::Scope*, int, bool, bool) + 261
7       0x7eff45feb70bp
8       0x7eff4602cf6ep
9             0x4aa69ap PyEval_EvalFrameEx + 32874
10            0x4aba27p PyEval_EvalCodeEx + 2167
11            0x4aa424p PyEval_EvalFrameEx + 32244
12            0x4aba27p PyEval_EvalCodeEx + 2167
13            0x4aa424p PyEval_EvalFrameEx + 32244
14            0x4aa6acp PyEval_EvalFrameEx + 32892
15            0x4aba27p PyEval_EvalCodeEx + 2167
16            0x4abb32p PyEval_EvalCode + 50
17            0x4ccdaep PyRun_FileExFlags + 318
18            0x4ccfd7p PyRun_SimpleFileExFlags + 231
19            0x4151c2p Py_Main + 2850
20        0x318ae1ecddp __libc_start_main + 253
21            0x4142a9p

**Comment by shippingwang** [comment]
> 模型转换完成后我保存了准换后的模型，用于预测时会报错

这是啥意思？save_inference么？

预测的话 你跑一下infer就行了 
```
if pretrained_model:
    load一下参数
```
建议参考 image classification的 [infer.py](https://github.com/PaddlePaddle/models/blob/develop/PaddleCV/image_classification/infer.py#L67)

**Comment by wanghaoshuang** [comment]
>Enforce failed. Expected ctx->GetInputDim("Scale")[0] == C, but received ctx->GetInputDim("Scale")

这个错误是因为你load进来的parameter的shape和当前网络里parameter的shape不一致。

你可以在load parameters时，检查下shape, 如下：

```
def load_parameter(place):
    params = load_param('map文件', 'V2文件')
    for name in params:
        t = fluid.global_scope().find_var(name).get_tensor()
        print("t shape: {}; param shape: {}".format(t.shape, params[name].shape))
        t.set(params[name], place)
```
