### ISSUE TITLE
开发者峰会开完了 什么时候出3.0

### ISSUE THREAD

**Issue by 1Shaun** [PaddlePaddle/Paddle#17052]
开发者峰会开完了 什么时候出3.0

**Comment by shippingwang** [comment]
您好，目前最新的Paddle release版本是1.4.1
具体没有3.0的计划
现在paddlepaddle不按照v1 v2...发布版本
而是按照fluid +版本号进行更新，
感谢您对paddlepaddle的期待，谢谢
