### ISSUE TITLE
官方数字识别实例EnforceNotMet: Invoke operator batch_norm_grad error.

### ISSUE THREAD

**Issue by doraemonlei** [PaddlePaddle/Paddle#17059]
1）docker ubuntu16.04
2）pp最新版
3）gpu：k80双卡 cuda9+cudnn7
```
EnforceNotMet: Invoke operator batch_norm_grad error.
Python Callstacks: 
  File "/root/.pyenv/versions/3.6.6/lib/python3.6/site-packages/paddle/fluid/framework.py", line 1654, in append_op
    attrs=kwargs.get("attrs", None))
  File "/root/.pyenv/versions/3.6.6/lib/python3.6/site-packages/paddle/fluid/layer_helper.py", line 43, in append_op
    return self.main_program.current_block().append_op(*args, **kwargs)
  File "/root/.pyenv/versions/3.6.6/lib/python3.6/site-packages/paddle/fluid/layers/nn.py", line 3096, in batch_norm
    "use_global_stats": use_global_stats
  File "<ipython-input-5-b3a356b35a35>", line 20, in convolutional_neural_network
    conv_pool_1 = fluid.layers.batch_norm(conv_pool_1)
  File "<ipython-input-6-582e7deafdc1>", line 16, in train_program
    predict = convolutional_neural_network() # 取消注释将使用 LeNet5卷积神经网络
  File "<ipython-input-11-3a29fcf74292>", line 6, in <module>
    prediction, [avg_loss, acc] = train_program()
  File "/root/.pyenv/versions/3.6.6/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 3291, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "/root/.pyenv/versions/3.6.6/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 3209, in run_ast_nodes
    if (yield from self.run_code(code, result)):
  File "/root/.pyenv/versions/3.6.6/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 3044, in run_cell_async
    interactivity=interactivity, compiler=compiler, result=result)
  File "/root/.pyenv/versions/3.6.6/lib/python3.6/site-packages/IPython/core/async_helpers.py", line 67, in _pseudo_sync_runner
    coro.send(None)
  File "/root/.pyenv/versions/3.6.6/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 2869, in _run_cell
    return runner(coro)
  File "/root/.pyenv/versions/3.6.6/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 2843, in run_cell
    raw_cell, store_history, silent, shell_futures)
  File "/root/.pyenv/versions/3.6.6/lib/python3.6/site-packages/ipykernel/zmqshell.py", line 536, in run_cell
    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)
  File "/root/.pyenv/versions/3.6.6/lib/python3.6/site-packages/ipykernel/ipkernel.py", line 294, in do_execute
    res = shell.run_cell(code, store_history=store_history, silent=silent)
  File "/root/.pyenv/versions/3.6.6/lib/python3.6/site-packages/tornado/gen.py", line 209, in wrapper
    yielded = next(result)
  File "/root/.pyenv/versions/3.6.6/lib/python3.6/site-packages/ipykernel/kernelbase.py", line 534, in execute_request
    user_expressions, allow_stdin,
  File "/root/.pyenv/versions/3.6.6/lib/python3.6/site-packages/tornado/gen.py", line 209, in wrapper
    yielded = next(result)
  File "/root/.pyenv/versions/3.6.6/lib/python3.6/site-packages/ipykernel/kernelbase.py", line 267, in dispatch_shell
    yield gen.maybe_future(handler(stream, idents, msg))
  File "/root/.pyenv/versions/3.6.6/lib/python3.6/site-packages/tornado/gen.py", line 209, in wrapper
    yielded = next(result)
  File "/root/.pyenv/versions/3.6.6/lib/python3.6/site-packages/ipykernel/kernelbase.py", line 357, in process_one
    yield gen.maybe_future(dispatch(*args))
  File "/root/.pyenv/versions/3.6.6/lib/python3.6/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.send(value)
  File "/root/.pyenv/versions/3.6.6/lib/python3.6/site-packages/tornado/gen.py", line 781, in inner
    self.run()
  File "/root/.pyenv/versions/3.6.6/lib/python3.6/site-packages/tornado/ioloop.py", line 743, in _run_callback
    ret = callback()
  File "/root/.pyenv/versions/3.6.6/lib/python3.6/site-packages/tornado/ioloop.py", line 690, in <lambda>
    lambda f: self._run_callback(functools.partial(callback, future))
  File "/root/.pyenv/versions/3.6.6/lib/python3.6/asyncio/events.py", line 145, in _run
    self._callback(*self._args)
  File "/root/.pyenv/versions/3.6.6/lib/python3.6/asyncio/base_events.py", line 1434, in _run_once
    handle._run()
  File "/root/.pyenv/versions/3.6.6/lib/python3.6/asyncio/base_events.py", line 422, in run_forever
    self._run_once()
  File "/root/.pyenv/versions/3.6.6/lib/python3.6/site-packages/tornado/platform/asyncio.py", line 148, in start
    self.asyncio_loop.run_forever()
  File "/root/.pyenv/versions/3.6.6/lib/python3.6/site-packages/ipykernel/kernelapp.py", line 505, in start
    self.io_loop.start()
  File "/root/.pyenv/versions/3.6.6/lib/python3.6/site-packages/traitlets/config/application.py", line 658, in launch_instance
    app.start()
  File "/root/.pyenv/versions/3.6.6/lib/python3.6/site-packages/ipykernel_launcher.py", line 16, in <module>
    app.launch_new_instance()
  File "/root/.pyenv/versions/3.6.6/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/root/.pyenv/versions/3.6.6/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
C++ Callstacks: 
holder_ should not be null
Tensor holds no memory. Call Tensor::mutable_data first. at [/paddle/paddle/fluid/framework/tensor.cc:23]
PaddlePaddle Call Stacks: 
0       0x7fce80df9228p void paddle::platform::EnforceNotMet::Init<std::string>(std::string, char const*, int) + 360
1       0x7fce80df9577p paddle::platform::EnforceNotMet::EnforceNotMet(std::string const&, char const*, int) + 87
2       0x7fce82adc179p paddle::framework::Tensor::check_memory_size() const + 185
3       0x7fce80e005e9p float const* paddle::framework::Tensor::data<float>() const + 25
4       0x7fce8162f21ap paddle::operators::BatchNormGradKernel<paddle::platform::CUDADeviceContext, float>::Compute(paddle::framework::ExecutionContext const&) const + 1882
5       0x7fce81630d93p std::_Function_handler<void (paddle::framework::ExecutionContext const&), paddle::framework::OpKernelRegistrarFunctor<paddle::platform::CUDAPlace, false, 0ul, paddle::operators::BatchNormGradKernel<paddle::platform::CUDADeviceContext, float>, paddle::operators::BatchNormGradKernel<paddle::platform::CUDADeviceContext, double>, paddle::operators::BatchNormGradKernel<paddle::platform::CUDADeviceContext, paddle::platform::float16> >::operator()(char const*, char const*, int) const::{lambda(paddle::framework::ExecutionContext const&)#1}>::_M_invoke(std::_Any_data const&, paddle::framework::ExecutionContext const&) + 35
6       0x7fce82a88376p paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&, paddle::framework::RuntimeContext*) const + 662
7       0x7fce82a88ae4p paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&) const + 292
8       0x7fce82a8640cp paddle::framework::OperatorBase::Run(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&) + 332
9       0x7fce80f6b3fep paddle::framework::Executor::RunPreparedContext(paddle::framework::ExecutorPrepareContext*, paddle::framework::Scope*, bool, bool, bool) + 382
10      0x7fce80f6c23fp paddle::framework::Executor::Run(paddle::framework::ProgramDesc const&, paddle::framework::Scope*, int, bool, bool, std::vector<std::string, std::allocator<std::string> > const&, bool) + 143
11      0x7fce80de88dep
12      0x7fce80e2b7cep
13            0x4afa4cp _PyCFunction_FastCallKeywords + 428
14            0x540808p
15            0x542abdp _PyEval_EvalFrameDefault + 4141
16            0x5406a5p
17            0x540957p
18            0x54272bp _PyEval_EvalFrameDefault + 3227
19            0x5406a5p
20            0x540957p
21            0x54272bp _PyEval_EvalFrameDefault + 3227
22            0x5406a5p
23            0x540957p
24            0x54272bp _PyEval_EvalFrameDefault + 3227
25            0x5406a5p
26            0x541533p PyEval_EvalCode + 35
27            0x53e81ep
28            0x4afb19p _PyCFunction_FastCallKeywords + 633
29            0x540a3ep
30            0x542abdp _PyEval_EvalFrameDefault + 4141
31            0x47aa2ep _PyGen_Send + 142
32            0x5475dep _PyEval_EvalFrameDefault + 23374
33            0x47aa2ep _PyGen_Send + 142
34            0x5475dep _PyEval_EvalFrameDefault + 23374
35            0x47aa2ep _PyGen_Send + 142
36            0x4afafep _PyCFunction_FastCallKeywords + 606
37            0x540a3ep
38            0x542abdp _PyEval_EvalFrameDefault + 4141
39            0x53fd01p
40            0x540bb1p
41            0x542abdp _PyEval_EvalFrameDefault + 4141
42            0x53fd01p
43            0x540bb1p
44            0x542abdp _PyEval_EvalFrameDefault + 4141
45            0x5406a5p
46            0x54964ap _PyFunction_FastCallDict + 298
47            0x453f70p _PyObject_FastCallDict + 480
48            0x45406ap _PyObject_Call_Prepend + 202
49            0x453c4cp PyObject_Call + 92
50            0x5447bap _PyEval_EvalFrameDefault + 11562
51            0x5406a5p
52            0x540957p
53            0x54272bp _PyEval_EvalFrameDefault + 3227
54            0x479456p
55            0x53c661p
56            0x4afb19p _PyCFunction_FastCallKeywords + 633
57            0x540a3ep
58            0x542abdp _PyEval_EvalFrameDefault + 4141
59            0x5406a5p
60            0x540957p
61            0x542abdp _PyEval_EvalFrameDefault + 4141
62            0x479456p
63            0x53c661p
64            0x4afb19p _PyCFunction_FastCallKeywords + 633
65            0x540a3ep
66            0x542abdp _PyEval_EvalFrameDefault + 4141
67            0x5406a5p
68            0x540957p
69            0x542abdp _PyEval_EvalFrameDefault + 4141
70            0x479456p
71            0x53c661p
72            0x4afb19p _PyCFunction_FastCallKeywords + 633
73            0x540a3ep
74            0x542abdp _PyEval_EvalFrameDefault + 4141
75            0x5406a5p
76            0x5496f6p _PyFunction_FastCallDict + 470
77            0x453f70p _PyObject_FastCallDict + 480
78            0x45406ap _PyObject_Call_Prepend + 202
79            0x453c4cp PyObject_Call + 92
80            0x5447bap _PyEval_EvalFrameDefault + 11562
81            0x47aa2ep _PyGen_Send + 142
82            0x4afafep _PyCFunction_FastCallKeywords + 606
83            0x540a3ep
84            0x542abdp _PyEval_EvalFrameDefault + 4141
85            0x53fd01p
86            0x540bb1p
87            0x542abdp _PyEval_EvalFrameDefault + 4141
88            0x5406a5p
89            0x5496f6p _PyFunction_FastCallDict + 470
90            0x453f70p _PyObject_FastCallDict + 480
91            0x59d790p
92            0x453e32p _PyObject_FastCallDict + 162
93            0x540808p
94            0x542abdp _PyEval_EvalFrameDefault + 4141
95            0x53fd01p
96            0x540bb1p
97            0x542abdp _PyEval_EvalFrameDefault + 4141
98            0x5406a5p
99            0x5415bep PyEval_EvalCodeEx + 62
```

**Comment by hjchen2** [comment]
我这边测试没问题，请问一下你有更改训练脚本么

**Comment by doraemonlei** [comment]
> 我这边测试没问题，请问一下你有更改训练脚本么

没有更改，我用cpu训练是正常的

**Comment by yeyupiaoling** [comment]
@doraemonlei 会不会是你的电脑不支持avx指令集。你使用的系统是？

**Comment by doraemonlei** [comment]
> @doraemonlei 会不会是你的电脑不支持avx指令集。你使用的系统是？

1）docker ubuntu16.04
2）pp最新版
3）gpu：k80双卡 cuda9+cudnn7

**Comment by hjchen2** [comment]
paddlepaddle最新版本是哪个版本，要不你执行一下pip install paddlepaddle-gpu --upgrade试试？
另外可否先试试python2.7的环境

**Comment by hjchen2** [comment]
@doraemonlei 我这边验证了一下fluid 1.3和1.4，以及python2.7和3.6，cpu和gpu都没有问题。如果升级paddle还有问题的话，麻烦请贴一下具体的代码

**Comment by doraemonlei** [comment]
> @doraemonlei 我这边验证了一下fluid 1.3和1.4，以及python2.7和3.6，cpu和gpu都没有问题。如果升级paddle还有问题的话，麻烦请贴一下具体的代码

pp:1.4.1.post97
python：3.6.6
训练到第1000step的时候出错的

代码和官方的一样，就是
`use_cuda = True # 如想使用GPU，请设置为 True`这个重新设置了一下，是不是pp在docker里使用gpu出现的问题。我用tf和keras都正常。

**Comment by hjchen2** [comment]
把训练日志贴一下吧。另外你git status看看有哪些文件修改过，把修改过的文件发给我。最后下载最新的book repo再试一下。

**Comment by hohdiy** [comment]
我也遇到了同样的问题，使用的是MNIST例子，报告同样的错误。
请问这个问题没有后续了么？
每次跑到900时报错：
![image](https://user-images.githubusercontent.com/20314800/57193076-06a1e300-6f6a-11e9-87a1-71b90f266f3a.png)
EnforceNotMet: Invoke operator batch_norm_grad error.
Python Callstacks: 
  File "/opt/conda/envs/py27-paddle/lib/python2.7/site-packages/paddle/fluid/framework.py", line 1654, in append_op
    attrs=kwargs.get("attrs", None))
  File "/opt/conda/envs/py27-paddle/lib/python2.7/site-packages/paddle/fluid/layer_helper.py", line 43, in append_op
    return self.main_program.current_block().append_op(*args, **kwargs)
  File "/opt/conda/envs/py27-paddle/lib/python2.7/site-packages/paddle/fluid/layers/nn.py", line 3096, in batch_norm
    "use_global_stats": use_global_stats
  File "<ipython-input-7-c575d22723e6>", line 20, in convolutional_neural_network
    conv_pool_1 = fluid.layers.batch_norm(conv_pool_1)
  File "<ipython-input-8-582e7deafdc1>", line 16, in train_program
    predict = convolutional_neural_network() # 取消注释将使用 LeNet5卷积神经网络
  File "<ipython-input-12-f795befbe277>", line 6, in <module>
    prediction, [avg_loss, acc] = train_program()
  File "/opt/conda/envs/python-2.7/lib/python2.7/site-packages/IPython/core/interactiveshell.py", line 2878, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "/opt/conda/envs/python-2.7/lib/python2.7/site-packages/IPython/core/interactiveshell.py", line 2818, in run_ast_nodes
    if self.run_code(code, result):
  File "/opt/conda/envs/python-2.7/lib/python2.7/site-packages/IPython/core/interactiveshell.py", line 2714, in run_cell
    interactivity=interactivity, compiler=compiler, result=result)
  File "/opt/conda/envs/python-2.7/lib/python2.7/site-packages/ipykernel/zmqshell.py", line 537, in run_cell
    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)
  File "/opt/conda/envs/python-2.7/lib/python2.7/site-packages/ipykernel/ipkernel.py", line 208, in do_execute
    res = shell.run_cell(code, store_history=store_history, silent=silent)
  File "/opt/conda/envs/python-2.7/lib/python2.7/site-packages/ipykernel/kernelbase.py", line 399, in execute_request
    user_expressions, allow_stdin)
  File "/opt/conda/envs/python-2.7/lib/python2.7/site-packages/ipykernel/kernelbase.py", line 233, in dispatch_shell
    handler(stream, idents, msg)
  File "/opt/conda/envs/python-2.7/lib/python2.7/site-packages/ipykernel/kernelbase.py", line 283, in dispatcher
    return self.dispatch_shell(stream, msg)
  File "/opt/conda/envs/python-2.7/lib/python2.7/site-packages/tornado/stack_context.py", line 300, in null_wrapper
    return fn(*args, **kwargs)
  File "/opt/conda/envs/python-2.7/lib/python2.7/site-packages/zmq/eventloop/zmqstream.py", line 438, in _run_callback
    callback(*args, **kwargs)
  File "/opt/conda/envs/python-2.7/lib/python2.7/site-packages/zmq/eventloop/zmqstream.py", line 486, in _handle_recv
    self._run_callback(callback, msg)
  File "/opt/conda/envs/python-2.7/lib/python2.7/site-packages/zmq/eventloop/zmqstream.py", line 456, in _handle_events
    self._handle_recv()
  File "/opt/conda/envs/python-2.7/lib/python2.7/site-packages/tornado/stack_context.py", line 300, in null_wrapper
    return fn(*args, **kwargs)
  File "/opt/conda/envs/python-2.7/lib/python2.7/site-packages/tornado/ioloop.py", line 1073, in start
    handler_func(fd_obj, events)
  File "/opt/conda/envs/python-2.7/lib/python2.7/site-packages/ipykernel/kernelapp.py", line 499, in start
    self.io_loop.start()
  File "/opt/conda/envs/python-2.7/lib/python2.7/site-packages/traitlets/config/application.py", line 658, in launch_instance
    app.start()
  File "/usr/local/cuda-9.2/conda/envs/python-2.7/lib/python2.7/site-packages/ipykernel_launcher.py", line 16, in <module>
    app.launch_new_instance()
  File "/opt/conda/envs/py27-paddle/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/opt/conda/envs/py27-paddle/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
C++ Callstacks: 
holder_ should not be null
Tensor holds no memory. Call Tensor::mutable_data first. at [/paddle/paddle/fluid/framework/tensor.cc:23]
PaddlePaddle Call Stacks: 
0       0x7f561e239338p void paddle::platform::EnforceNotMet::Init<std::string>(std::string, char const*, int) + 360
1       0x7f561e239687p paddle::platform::EnforceNotMet::EnforceNotMet(std::string const&, char const*, int) + 87
2       0x7f561ff16f79p paddle::framework::Tensor::check_memory_size() const + 185
3       0x7f561e2406e9p float const* paddle::framework::Tensor::data<float>() const + 25
4       0x7f561ea6d91ap paddle::operators::BatchNormGradKernel<paddle::platform::CUDADeviceContext, float>::Compute(paddle::framework::ExecutionContext const&) const + 1882
5       0x7f561ea6f493p std::_Function_handler<void (paddle::framework::ExecutionContext const&), paddle::framework::OpKernelRegistrarFunctor<paddle::platform::CUDAPlace, false, 0ul, paddle::operators::BatchNormGradKernel<paddle::platform::CUDADeviceContext, float>, paddle::operators::BatchNormGradKernel<paddle::platform::CUDADeviceContext, double>, paddle::operators::BatchNormGradKernel<paddle::platform::CUDADeviceContext, paddle::platform::float16> >::operator()(char const*, char const*, int) const::{lambda(paddle::framework::ExecutionContext const&)#1}>::_M_invoke(std::_Any_data const&, paddle::framework::ExecutionContext const&) + 35
6       0x7f561fec3176p paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&, paddle::framework::RuntimeContext*) const + 662
7       0x7f561fec38e4p paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&) const + 292
8       0x7f561fec120cp paddle::framework::OperatorBase::Run(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&) + 332
9       0x7f561e3ad0eep paddle::framework::Executor::RunPreparedContext(paddle::framework::ExecutorPrepareContext*, paddle::framework::Scope*, bool, bool, bool) + 382
10      0x7f561e3adf2fp paddle::framework::Executor::Run(paddle::framework::ProgramDesc const&, paddle::framework::Scope*, int, bool, bool, std::vector<std::string, std::allocator<std::string> > const&, bool) + 143
11      0x7f561e228b5ep
12      0x7f561e26bf0ep
13      0x7f569888c1a7p PyEval_EvalFrameEx + 28695
14      0x7f569888e6c9p PyEval_EvalCodeEx + 2025
15      0x7f569888bb98p PyEval_EvalFrameEx + 27144
16      0x7f569888e6c9p PyEval_EvalCodeEx + 2025
17      0x7f569888bb98p PyEval_EvalFrameEx + 27144
18      0x7f569888e6c9p PyEval_EvalCodeEx + 2025
19      0x7f569888bb98p PyEval_EvalFrameEx + 27144
20      0x7f569888e6c9p PyEval_EvalCodeEx + 2025
21      0x7f569888e8eap PyEval_EvalCode + 26
22      0x7f569888acc0p PyEval_EvalFrameEx + 23344
23      0x7f569888e6c9p PyEval_EvalCodeEx + 2025
24      0x7f569888bb98p PyEval_EvalFrameEx + 27144
25      0x7f569888e6c9p PyEval_EvalCodeEx + 2025
26      0x7f569888bb98p PyEval_EvalFrameEx + 27144
27      0x7f569888e6c9p PyEval_EvalCodeEx + 2025
28      0x7f5698817567p
29      0x7f56987f2973p PyObject_Call + 67
30      0x7f569888769ep PyEval_EvalFrameEx + 9486
31      0x7f569888e6c9p PyEval_EvalCodeEx + 2025
32      0x7f569888bb98p PyEval_EvalFrameEx + 27144
33      0x7f569888e6c9p PyEval_EvalCodeEx + 2025
34      0x7f569888bb98p PyEval_EvalFrameEx + 27144
35      0x7f569888e6c9p PyEval_EvalCodeEx + 2025
36      0x7f569888bb98p PyEval_EvalFrameEx + 27144
37      0x7f569888e6c9p PyEval_EvalCodeEx + 2025
38      0x7f569888bb98p PyEval_EvalFrameEx + 27144
39      0x7f569888e6c9p PyEval_EvalCodeEx + 2025
40      0x7f5698817567p
41      0x7f56987f2973p PyObject_Call + 67
42      0x7f569888769ep PyEval_EvalFrameEx + 9486
43      0x7f569888e6c9p PyEval_EvalCodeEx + 2025
44      0x7f5698817567p
45      0x7f56987f2973p PyObject_Call + 67
46      0x7f569888769ep PyEval_EvalFrameEx + 9486
47      0x7f569888e6c9p PyEval_EvalCodeEx + 2025
48      0x7f569888bb98p PyEval_EvalFrameEx + 27144
49      0x7f569888e6c9p PyEval_EvalCodeEx + 2025
50      0x7f569888bb98p PyEval_EvalFrameEx + 27144
51      0x7f569888e6c9p PyEval_EvalCodeEx + 2025
52      0x7f5698817567p
53      0x7f56987f2973p PyObject_Call + 67
54      0x7f569888769ep PyEval_EvalFrameEx + 9486
55      0x7f569888e6c9p PyEval_EvalCodeEx + 2025
56      0x7f569888bb98p PyEval_EvalFrameEx + 27144
57      0x7f569888e6c9p PyEval_EvalCodeEx + 2025
58      0x7f569888bb98p PyEval_EvalFrameEx + 27144
59      0x7f569888e6c9p PyEval_EvalCodeEx + 2025
60      0x7f569888bb98p PyEval_EvalFrameEx + 27144
61      0x7f569888e6c9p PyEval_EvalCodeEx + 2025
62      0x7f569888bb98p PyEval_EvalFrameEx + 27144
63      0x7f569888e6c9p PyEval_EvalCodeEx + 2025
64      0x7f569888e8eap PyEval_EvalCode + 26
65      0x7f569888acc0p PyEval_EvalFrameEx + 23344
66      0x7f569888e6c9p PyEval_EvalCodeEx + 2025
67      0x7f569888bb98p PyEval_EvalFrameEx + 27144
68      0x7f569888e6c9p PyEval_EvalCodeEx + 2025
69      0x7f569881747ap
70      0x7f56987f2973p PyObject_Call + 67
71      0x7f56988bb320p
72      0x7f56988bb9dep Py_Main + 1374
73      0x7f5697a8c830p __libc_start_main + 240
74      0x555d9a5ac07fp

**Comment by hohdiy** [comment]
![image](https://user-images.githubusercontent.com/20314800/57193118-6d270100-6f6a-11e9-9a4b-86c8f1dbacc3.png)
使用cpu没有问题，使用gpu报错，cuda9.2 + cudnn7，显卡是taitanX

**Comment by hohdiy** [comment]
发现训练过程没有问题，是这句报的错:
![image](https://user-images.githubusercontent.com/20314800/57193262-b88ddf00-6f6b-11e9-8a78-89e113cf4935.png)

**Comment by chengduoZH** [comment]
你的test_program应该是`optimizer.minimize(avg_loss)`之前构建。
请参考：https://github.com/PaddlePaddle/book/blob/develop/02.recognize_digits/train.py#L84

另外，代码里面如果没有特别指定program，所有的操作都会放到`fluid.default_main_program()`，如果在jupiter中运行两次，就会出现在`fluid.default_main_program()`中插入两次Op。
如何指定Program的相关文档： http://paddlepaddle.org/documentation/docs/zh/1.4/api_cn/fluid_cn.html#program-guard
