### ISSUE TITLE
RDMA编译问题：   c++: error: ./librdma: No such file or directory, when Linking CXX shared module _swig_paddle.so

### ISSUE THREAD

**Issue by shijieheping** [PaddlePaddle/Paddle#1705]
这个问题之前没有，今天晚上刚出现。

make过程如下：
cmake .. -DRDMA_ROOT=/root/pp/sxi_for_mlnx -DMKL_ROOT=/opt/intel17/compilers_and_libraries_2017.0.098/linux/mkl -DWITH_DOC=ON -DWITH_GPU=ON -DWITH_AVX=ON -DWITH_RDMA=ON -DWITH_PROFILER=ON
make install

崩在：
[ 95%] Building CXX object paddle/trainer/tests/CMakeFiles/test_recurrent_machine_generation.dir/test_recurrent_machine_generation.cpp.o
Linking CXX executable test_recurrent_machine_generation
Done processing test_recurrent_machine_generation.cpp
Total errors found: 0
[ 95%] Built target test_recurrent_machine_generation
[ 98%] Built target paddle_api
[ 98%] Swig source
Scanning dependencies of target _swig_paddle
[ 98%] Swig source
[ 98%] Building CXX object paddle/api/CMakeFiles/_swig_paddle.dir/PaddlePYTHON_wrap.cxx.o
Linking CXX shared module _swig_paddle.so
c++: error: ./librdma: No such file or directory
make[2]: *** [paddle/api/_swig_paddle.so] Error 1
make[1]: *** [paddle/api/CMakeFiles/_swig_paddle.dir/all] Error 2
make: *** [all] Error 2
[root@g2 build]# 

简单检查一下librdma：
[root@g4 function]# ll /root/pp/git/paddle/build/paddle/function/librdma/
total 0
lrwxrwxrwx 1 root root 30 Mar 26 11:22 libibverbs.so -> /usr/lib64/libibverbs.so.1.0.0
lrwxrwxrwx 1 root root 30 Mar 26 11:22 libibverbs.so.1 -> /usr/lib64/libibverbs.so.1.0.0
lrwxrwxrwx 1 root root 29 Mar 26 11:22 librdmacm.so -> /usr/lib64/librdmacm.so.1.0.0
lrwxrwxrwx 1 root root 29 Mar 26 11:22 librdmacm.so.1 -> /usr/lib64/librdmacm.so.1.0.0
能看到有librdma

这时候，就不知道linker说的那个c++: error: ./librdma: No such file or directory指的是什么了，也不知道怎么找原因。

版本：
[root@g4 build]# git show
commit 929090ed2290b25a1d08959e15a3d6e7a05e1862
Merge: 5961b52 df9993f
Author: QI JUN <qijun1994@hotmail.com>
Date:   Fri Mar 24 18:12:30 2017 +0800

    Merge pull request #1702 from gangliao/python_remove
    
    Fix NOT WITH_PYTHON

另外请教一下，看版本是不是git show   git log？

**Comment by gangliao** [comment]
直接make VERBOSE=1 ,贴一下编译最后的详细信息

**Comment by shijieheping** [comment]
@gangliao 我刚才用0.9.0a编译了一下，那个版本里确实没有这个问题
我现在再切换到这个929090e重现一下

[root@g4 pp]# paddle version
Paddle release a new version 0.9.0, you can get the install package in http://www.paddlepaddle.org
PaddlePaddle 0.9.0a0, compiled with
    with_avx: ON
    with_gpu: ON
    with_double: OFF
    with_python: ON
    with_rdma: ON
    with_glog: ON
    with_gflags: ON
    with_metric_learning: 
    with_timer: OFF
    with_predict_sdk:

**Comment by gangliao** [comment]
具体原因我已经知道了。https://github.com/jacquesqiao/Paddle/blob/6f745ba0261e609dcffcd0d3d1969ae5c245bed4/paddle/api/CMakeLists.txt#L79 注释掉这两行就行了。

**Comment by gangliao** [comment]
swig里面之前是不会连接rdma的。

**Comment by shijieheping** [comment]
@gangliao OK，多谢gaoliao

我现在在使用RDMA库，感觉升级到1.0会引入更多问题，就不去验证了。用0.9.0a会更安全一些
更新这个注释之后，如果没有其他人反映，我猜就是solve了    :)
