### ISSUE TITLE
paddle1.4.0版本动态图预测问题

### ISSUE THREAD

**Issue by DDDivano** [PaddlePaddle/Paddle#17068]
对mnist模型进行训练和预测中，在训练后直接进行预测，预测结果是正确的。但在训练后保存网络权重参数，加载到新生成mnist模型对象后，预测结果错误。预测结果数组有diff，如图。

![image](https://user-images.githubusercontent.com/10734244/56636618-ee91b000-669b-11e9-8612-b0f84292f1e4.png)

**Comment by junjun315** [comment]
由于FC Layer是在build_once时创建参数，导致load_persistable时网络中还没有该参数，而无法进行更新。查看pr 16983 https://github.com/PaddlePaddle/Paddle/pull/16983
