### ISSUE TITLE
显存优化策略打开后，显存占用多次结果不同

### ISSUE THREAD

**Issue by ccmeteorljh** [PaddlePaddle/Paddle#17069]
paddle comitid：63d9fe336217303e1178e20ee66a7a10055387dc
复现脚本：
https://github.com/PaddlePaddle/benchmark/blob/master/NeuralMachineTranslation/Transformer/fluid/train/run.sh
测试结果：
每0.1s采样显存占用，取最大值
测试3次，分别结果是：
7924,6940,7924

**Comment by sneaxiy** [comment]
可能是机器环境问题，后续未有出现类似现象。
