### ISSUE TITLE
GRU层如何传入mask

### ISSUE THREAD

**Issue by laoliukan** [PaddlePaddle/Paddle#17073]

**Comment by laoliukan** [comment]
我要实现一个网络：gru的输出和bert的输出进行拼接，由于paddle bert现在输入都是padding好的，所以gru层输入也是padding的，gru层应该如何传入mask呢？

**Comment by junjun315** [comment]
可以在输入gru之前，进行一次 `paddle.fluid.layers.sequence_unpad`操作，再输出到gru中
