### ISSUE TITLE
请教PaddlePaddle使用动态图的方法。

### ISSUE THREAD

**Issue by yeyupiaoling** [PaddlePaddle/Paddle#17078]
# 环境
 - PaddlePaddle 1.4
 - Ubuntu 16.04
 - Python 3.5

# 问题
首先感叹一下，PaddlePaddle终于支持了动态图，终于不需要用别人剩下的技术了。之前还被吐槽，连TensorFlow都开始抛弃静态图，把动态图作为首选。而我们的PaddlePaddle还在为实现静态图而努力，为何不直接支持动态图。好了，说得有点多了，回答问题。

关于PaddlePaddle使用动态图，资料有点少，有没有更多的demo？

**Comment by hjchen2** [comment]
https://github.com/PaddlePaddle/models/tree/develop/dygraph 这里面有几个模型的例子，可以参考一下
