### ISSUE TITLE
1.4版本还不支持CUDA 10？

### ISSUE THREAD

**Issue by yeyupiaoling** [PaddlePaddle/Paddle#17072]
# 环境
 - PaddlePaddle 1.4
 - Ubuntu 16.04
 - Python 3.5

# 问题
都 1.4 版本了，还不支持CUDA 10，虽然我自行编译可以支持CUDA 10，但是每次都要编译其实很麻烦的。

对于1.4版本的发布，值得高兴的是，paddlePaddle终于支持动态图了。

**Comment by hjchen2** [comment]
@yeyupiaoling 确实目前还没提供cuda 10的预编译二进制包

**Comment by yeyupiaoling** [comment]
@hjchen2 这我就不懂了，明明是可以在cuda 10正常编译得到的。为什么不顺便提供呢？
