### ISSUE TITLE
MobileNet-SSD使用自己的数据训练出错

### ISSUE THREAD

**Issue by MHloulis** [PaddlePaddle/Paddle#17083]
重要的报错信息为
 val_file_list=val_file_list)
best_map, mean_map = test(epoc_id, best_map)
test_map, = exe.run(test_prog, fetch_list=[accum_map])
Invoke operator multiclass_nms error.

Enforce failed. Expected box_dims[1] == score_dims[2], but received box_dims[1]:1917 != score_dims[2]:13419.
The 2nd dimension of Input(BBoxes) must be equal to last dimension of Input(Scores), which represents the predicted bboxes. at [/paddle/paddle/fluid/operators/detection/multiclass_nms_op.cc:60]

- 版本、环境信息：
    1）PaddlePaddle版本：1.41，cpu版本
    2）系统环境：Ubuntu18.04 python3.6
- 训练信息
    1）单机
制作了数据集，运行了create_list.py，修改了label_list和train.py里面的class_num，然后就这样报错了。

(Ps：经常出现MemoryError怎么解决，python版本为64位)
感谢解答

**Comment by yeyupiaoling** [comment]
@MHloulis 网络的输出输入不一致，你的类别是多少，你的label_list是什么？

MemoryError这是是不是内存溢出？如果是就减小batch size

**Comment by MHloulis** [comment]
class_num为3，label_list为
![image](https://user-images.githubusercontent.com/22653034/56724045-cf1e8400-677c-11e9-8390-cdd8be967bda.png)，输入输出不一致吗，我看看。
减小batch_size，我试试吧
谢谢解答
