### ISSUE TITLE
paddle新发布的docker镜像，run没反应

### ISSUE THREAD

**Issue by leanna62** [PaddlePaddle/Paddle#1709]
执行docker run后只出现以下信息，但启动不起来，是发布版本有问题吗？同样方式运行book镜像是可行的。
PaddlePaddle 0.10.0rc2, compiled with
    with_avx: ON
    with_gpu: OFF
    with_double: OFF
    with_python: ON
    with_rdma: OFF
    with_metric_learning: 
    with_timer: OFF
    with_predict_sdk:

**Comment by gangliao** [comment]
请粘贴你使用的命令

**Comment by leanna62** [comment]
docker run -p 8880:8880 docker.paddlepaddle.org/paddle:0.10.0rc2

**Comment by gangliao** [comment]
https://github.com/PaddlePaddle/Paddle/blob/develop/doc/getstarted/build_and_install/docker_install_cn.rst

**Comment by leanna62** [comment]
docker run -d -p 2202:22 -p 8888:8888 paddledev/paddle:0.10.0rc1-cpu
找不到镜像。。。。

**Comment by CodeSuperman** [comment]
sudo docker images 
看下已有镜像列表

**Comment by leanna62** [comment]
而且按照这个进程操作会出现connect to host XXXX port 2202: Connection refused的问题

**Comment by leanna62** [comment]
恩，主要是这个链接上的内容不是最新的

**Comment by gangliao** [comment]
sorry，我们最近docker迭代的太快，文档还在review中https://github.com/PaddlePaddle/Paddle/pull/1685/files

**Comment by leanna62** [comment]
ssh root@localhost -p 2202的时候出现connect to host XXXX port 2202: Connection refused这样的问题是什么原因呢？

**Comment by typhoonzero** [comment]
@leanna62 可以在 https://hub.docker.com/r/paddledev/paddle/tags/ 找到最新的paddle docker images，目前最新的是：`0.10.0rc2`。rc2对应的使用方法可以参考：http://mp.weixin.qq.com/s/weRobXZsZyN7qyiXEkL_IQ 。 文档会尽快更新在doc目录下。

`Connection refused` 问题，请先检查paddle 的docker容器是否已经正确启动：`docker ps`查看容器是否是`Running`状态。另外如果是使用`docker-machine`等工具，需要先查看`docker-machine`的IP，然后链接到其IP，而不是localhost。使用`docker-machine env`可以找到对应的IP。

**Comment by typhoonzero** [comment]
补充说明：rc1镜像中包含了sshd，但在rc2中只有dev镜像才有sshd，这里需要注意。

**Comment by leanna62** [comment]
应该是正常启动的状态
50c495a85b96        docker.paddlepaddle.org/paddle:0.10.0rc2   "/bin/bash"            9 minutes ago       Up 9 minutes                                 romantic_lalande
另外我想问下，怎么能在docker环境下方便看demo和使用Demo呢？

**Comment by Yancey1989** [comment]
@leanna62 如果要进入生产环境镜像可以通过`docker exec -it <containerid> /bin/bash`来完成

更方便的做法是将你的工程目录mount到container上：
`docker run -it -v $<your workspace>:/work paddlepaddle/paddle:0.10.0rc2 python xxx.py`

另外，没有在生产环境镜像中启动sshd服务是因为我们期望能够减少镜像的体积，能描述下使用场景么？

**Comment by leanna62** [comment]
哦，我看到推荐使用sshd，所以选择了这种方式。
$<your workspace>:/work 这里的work指的用户名？ @Yancey1989

**Comment by typhoonzero** [comment]
@leanna62 可以参考 http://mp.weixin.qq.com/s/weRobXZsZyN7qyiXEkL_IQ 提到的如何使用书籍镜像部分。

**Comment by leanna62** [comment]
书籍部分是可以直接使用的，我也能直接使用，但是我想知道一些细节部分，目前的book并不能提供api_train.py这样直接执行的功能吧，所以我没办法运行demo啊；只能到本地环境下运行

**Comment by Yancey1989** [comment]
> 哦，我看到推荐使用sshd，所以选择了这种方式。
$<your workspace>:/work 这里的work指的用户名？

@leanna62 这里work是mount到容器内的目录，对应到你本机的工程目录，具体可参考[Volume](https://docs.docker.com/engine/reference/run/#volume-shared-filesystems)。

**Comment by leanna62** [comment]
好的 @Yancey1989

**Comment by typhoonzero** [comment]
> 书籍部分是可以直接使用的，我也能直接使用，但是我想知道一些细节部分，目前的book并不能提供api_train.py这样直接执行的功能吧，所以我没办法运行demo啊；只能到本地环境下运行 @typhoonzero

书籍镜像启动jupyter notebook后，可以直接在页面上运行，修改`api_train.py`这样的程序的。在浏览器上选择你想要使用的demo，鼠标点选代码段，然后在点击工具栏中的“运行”按钮。

如果希望使用命令行执行，也可以使用`docker run -it paddlepaddle/book:0.10.0rc2 /bin/bash`进入书籍容器中执行对应操作。

**Comment by leanna62** [comment]
好的 @typhoonzero 
多谢各位～～
