### ISSUE TITLE
基本数学操作缺失

### ISSUE THREAD

**Issue by Yelrose** [PaddlePaddle/Paddle#17093]
paddlepaddle 1.4

+、-、*、/ 主要是重载elementwise的操作。目前用起来有一些不方便，如假设 a是一个(batch_size,  hidden_size)的Tensor。

1 - a 是不合法的
-a 不存在 unary操作

**Comment by junjun315** [comment]
很好的建议，谢谢！`1-a`是不合法的，主要是基于shape的推导考虑，当前我们考虑第一个位置的tensor，以它为基础进行shape推导。这个示例中1*1的tensor就不符合推导结果。取负的不存在 unary操作这个应该改进。

**Comment by SidHard** [comment]
那么，一个tensor如何取负呢，找了半天，一脸懵逼

**Comment by Yelrose** [comment]
> 那么，一个tensor如何取负呢，找了半天，一脸懵逼

目前的办法是 neg_a = neg_a * -1
