### ISSUE TITLE
Paddle pip安装 指定依赖包的版本

### ISSUE THREAD

**Issue by bfjia1** [PaddlePaddle/Paddle#17092]
作为Paddlepaddle的用户 很不理解 pip 安装的 requirement package 为什么指定固定版本号的依赖包，而不是允许一个版本兼容范围，导致经常由于强制指定固定版本的依赖包带来其他python包的冲突，建议更改这一点，并能即使升级依赖包的版本

**Comment by yeyupiaoling** [comment]
@jiabinfeng 因为依赖的包是要版本要求的，可能有些依赖包的版本是不支持的，所以要指定依赖包的版本，保证PaddlePaddle正常使用。

我们一般是使用Python的虚拟环境进行开发的，所以环境直接是相互独立的，各不影响。

**Comment by fc500110** [comment]
建议使用[virtualenv](https://docs.python.org/3/library/venv.html)

**Comment by linkinbird** [comment]
这样用的人多了，可能会遇到很多问题啊
