### ISSUE TITLE
动态图机制-DyGraph保持的模型有问题

### ISSUE THREAD

**Issue by yeyupiaoling** [PaddlePaddle/Paddle#17098]
# 环境
 - PaddlePaddle 1.4.1
 - Ubuntu 16.04
 - Python 3.5

# 问题
动态图机制-DyGraph保持的模型是有问题的，GPU训练得到的模型必须要使用GPU加载预测，如果使用的是CPU，预测就不准确了。
以这个代码为例：https://github.com/PaddlePaddle/models/tree/develop/dygraph/mnist

**Comment by junjun315** [comment]
当前在跟踪这个问题，感谢提出。

**Comment by yeyupiaoling** [comment]
OK
