### ISSUE TITLE
【mac首次运行】安装成功后，首次运行demo失败

### ISSUE THREAD

**Issue by JiaoZiLang** [PaddlePaddle/Paddle#17107]
情况如下所示，mac中运行首页安装的demo，提示这个错误
```
 ~ python
Python 2.7.10 (default, Feb 22 2019, 21:17:52)
[GCC 4.2.1 Compatible Apple LLVM 10.0.1 (clang-1001.0.37.14)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import paddle.fluid as fluid
>>> fluid.install_check.run_check()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'module' object has no attribute 'install_check'
```

**Comment by junjun315** [comment]
您好，请问是否是使用了mac中自带的python安装？ mac自带的python设置上有些不太一样的地方。可以尝试新安装一个python以及pip之后，再用pip安装一次。

**Comment by JiaoZiLang** [comment]
> 您好，请问是否是使用了mac中自带的python安装？ mac自带的python设置上有些不太一样的地方。可以尝试新安装一个python以及pip之后，再用pip安装一次。

hi,我用的是conda3下面的python3，这个也不能支持？

**Comment by junjun315** [comment]
我看输出里显示的是 `Python 2.7.10 (default, Feb 22 2019, 21:17:52)` 是不是没有切换对应的环境？

**Comment by junjun315** [comment]
我复现了这个问题，谢谢您的反馈。请继续关注这个issue，如果有消息我会更新

**Comment by JiaoZiLang** [comment]
好的，麻烦你那边跟进一下

**Comment by junjun315** [comment]
您好，请检查一下paddle的版本：
```
import paddle 
print(paddle.__version__)
```
如果paddle的版本低于1.4，建议升级到最新版本。 可以使用 pip uninstall paddlepaddle卸载后再执行 pip install paddlepaddle安装

**Comment by JiaoZiLang** [comment]
done

**Comment by JiaoZiLang** [comment]
是更新了pip的源？
