### ISSUE TITLE
docker 预装软件以方便使用

### ISSUE THREAD

**Issue by xionghang** [PaddlePaddle/Paddle#1711]
前几天下载了cpu-noavx-devel-latest版本的docker， 运行了quick_start，总体比较顺利，有两个小建议：
1. 希望docker预装些必要软件，至少保证quick_start能直接运行：如 wget zip (dev最好还有vim catgs等）
同时sh指向bash 而非默认dash.
2. quick_start/api_train.sh 最终的模型产出在output/modle/下， 因此predict.sh的默认配置无法直接读取（默认是output/）。建议api_train.py 新增默认参数parser.add_argument("--save_dir", default="./output",type=str, help="modle output dir")，并生效该config。

**Comment by helinwang** [comment]
谢谢提出很好的建议。关于第一个问题，您说得对，确实应该保证demo能够直接使用。quick_start那个demo属于旧版本api的demo，我们准备删掉了（详见这个issue：https://github.com/PaddlePaddle/Paddle/issues/1725）。
现在新版api把模型保存在哪里是自己定义的。详情请见：https://github.com/PaddlePaddle/Paddle/blob/develop/demo/mnist/api_train_v2.py#L98

最后我们更新了最新的使用docker运行PaddlePaddle的方法，欢迎阅读以及提建议！
https://github.com/PaddlePaddle/Paddle/blob/develop/doc/getstarted/build_and_install/docker_install_en.rst

**Comment by wanghaisheng** [comment]
@helinwang  能否提供docker 镜像的离线安装包  从docker hub上下载实在是太慢且容易连接不上

**Comment by typhoonzero** [comment]
@wanghaisheng 可以使用paddle的docker registry，在国内可以获得较快的访问速度:
```bash
docker pull docker.paddlepaddle.org/paddle:0.10.0rc2-noavx
```
