### ISSUE TITLE
请教paddle embedding层中is_sparse的原理

### ISSUE THREAD

**Issue by bhan1111** [PaddlePaddle/Paddle#17119]
文档没具体说明，请教该参数的原理以及何时打开比较合适，发现当需要embed的节点数很大时，开不开对内存以及训练速度都有很大的影响

**Comment by seiriosPlus** [comment]
针对于embedding, 目前sparse和dense的区别，主要在于梯度的存储格式上。

1. 采用sparse的embedding的参数，对应的梯度采用SelectedRows格式来存储，只会保存当前batch中对应ID所需要的数据， 存储空间和batch大小相关。
2. 采用dense的embedding的参数，对应的梯度采用LodTensor格式来存储，存储空间和embedding的参数大小相关。

当embedding的参数很大时， 
内存占用上， 采用sparse的embedding比采用dense的占用内存小。
训练速度上， 采用SGD的情况下速度会有大幅提升， 采用常规ADAM的情况速度提升不明显， 采用lazy_mode的ADAM 速度会明显提升。

多机情况下，还有优化， 后续再讲.

**Comment by Yelrose** [comment]
> 针对于embedding, 目前sparse和dense的区别，主要在于梯度的存储格式上。
> 
> 1. 采用sparse的embedding的参数，对应的梯度采用SelectedRows格式来存储，只会保存当前batch中对应ID所需要的数据， 存储空间和batch大小相关。
> 2. 采用dense的embedding的参数，对应的梯度采用LodTensor格式来存储，存储空间和embedding的参数大小相关。
> 
> 当embedding的参数很大时，
> 内存占用上， 采用sparse的embedding比采用dense的占用内存小。
> 训练速度上， 采用SGD的情况下速度会有大幅提升， 采用常规ADAM的情况速度提升不明显， 采用lazy_mode的ADAM 速度会明显提升。
> 
> 多机情况下，还有优化， 后续再讲.

请问一下，这里说的速度包括GPU速度的提升吗？还是lazy_adam目前只实现了CPU版

**Comment by seiriosPlus** [comment]
lazy_adam目前只有CPU实现

**Comment by Yelrose** [comment]
> lazy_adam目前只有CPU实现

这部分的GPU实现能否支持吗？大Embedding GPU训练对比SGD速度差的太多了，但是收敛速度比SGD要快很多。
