### ISSUE TITLE
OSError: [Errno 13] Permission denied

### ISSUE THREAD

**Issue by 930083287** [PaddlePaddle/Paddle#17120]
利用paddlepaddle安装成功后，在import paddle时，出现上述错误。
![image](https://user-images.githubusercontent.com/15224527/56795117-54b83780-6842-11e9-8c00-8feda1c0cf6d.png)

**Comment by yeyupiaoling** [comment]
@930083287 你试试使用root权限。你的Python路径是自己修改的？试试模型Python的路径试试。

**Comment by junjun315** [comment]
重装rar命令后好了，谢谢@yeyupiaoling 的回复。 问题的原因是 import paddle依赖的rarfile包，而init rarfile时会执行一个检查cmd rar命令是否允许执行。 而用户的环境里当前用户权限不允许执行该命令，导致报错 。
