### ISSUE TITLE
请问Fluid有没有只克隆预测程序的？

### ISSUE THREAD

**Issue by yeyupiaoling** [PaddlePaddle/Paddle#17127]
# 环境 
 - PaddlePaddle 1.4.1
 - Ubuntu 16.05 / windows 10
 - Python 3.5

# 问题
在Fluid版本中有克隆测试程序的操作，可以用来预测，但是数据的数据必须同时有训练数据和label，拿图片识别来说，就需要image和label。
```
test_program = fluid.default_main_program().clone(for_test=True)
```

但是我想在训练过程中，只是预测数据，不需要报错模型的方式，而且数据的数据只要image，不输入label，这样方式如何实现。重复，不使用保存和加载模型的方式。

**Comment by qingqing01** [comment]
@yeyupiaoling 在网络定义部分，不定义label相关的layers.data、以及评估指标相关的即可。 也就是和label相关layer都去掉。

**Comment by yeyupiaoling** [comment]
@qingqing01 例如这样
```python
model = convolutional_neural_network(image)

infer_program = fluid.default_main_program().clone(for_test=True)

# 获取损失函数和准确率函数
cost = fluid.layers.cross_entropy(input=model, label=label)
avg_cost = fluid.layers.mean(cost)
acc = fluid.layers.accuracy(input=model, label=label)
```
谢谢解答。
