### ISSUE TITLE
关于动态图机制API一致的建议？

### ISSUE THREAD

**Issue by yeyupiaoling** [PaddlePaddle/Paddle#17128]
# 环境
 - PaddlePaddle 1.4.1

# 建议
能否统一API，例如神经网络居然有2套，拿二维卷积操作来说，就有
```
fluid.dygraph.nn.Pool2D()
```
和
```
fluid.dygraph.Pool2D
```

能不能只保留一个，不要让我们在开发的时候，考虑他们是否是同一个API，可否？

**Comment by junjun315** [comment]
实际上这两个api指向了同一个。 只是 fluid.dygraph.nn.Pool2D() 是实际的位置，fluid.dygraph.Pool2D 是短位置。 之后我们考虑屏蔽较长的位置。 当前dygraph的api没有正式公布，我们可能会对调整接口位置和调用方式继续调整

**Comment by yeyupiaoling** [comment]
@junjun315 好的，不管你们有没有公开，反正我已经开始使用了。
