### ISSUE TITLE
反反复复出现的grpc错误

### ISSUE THREAD

**Issue by SheldonZHANG** [PaddlePaddle/Paddle#17139]
提交的大部分任务都被grpc错误给停掉了模型训练，链接如下
http://yq01-hpc-lvliang01-mon.dmop.baidu.com:8919/taskinfo.html?appId=app-user-20190425184558-89
http://yq01-hpc-lvliang01-mon.dmop.baidu.com:8919/taskinfo.html?appId=app-user-20190428081629-1663
http://yq01-hpc-lvliang01-mon.dmop.baidu.com:8919/taskinfo.html?appId=app-user-20190427225547-1395
http://yq01-hpc-lvliang01-mon.dmop.baidu.com:8919/taskinfo.html?appId=app-user-20190428081858-1666

**Comment by seiriosPlus** [comment]
在hi沟通中， 会同步结果及解决方案。
