### ISSUE TITLE
dynamic_gru 是否可以使用普通的Tensor作为输入, 而不是用LoD Tensor? 如果可以该怎么用?

### ISSUE THREAD

**Issue by Robets2020** [PaddlePaddle/Paddle#17144]
dynamic_gru 是否可以使用普通的Tensor作为输入, 而不是用LoD Tensor? 如果可以该怎么用?

**Comment by qingqing01** [comment]
@roberts-sh  

dynamic_gru的输入限制了是LoDTensor，最好在输入层就带有序列长度信息，通过LoDTensor作为输入。 当然也可以通过`lod_reset`来给Tensor设置LoD信息，再输入给`dynamic_gru`。

**Comment by Robets2020** [comment]
@qingqing01 谢谢, 按照你的方法已经满足需要. 但想问一下, 有没有和dynamic_gru相对应的方法, 是使用普通的Tensor作为输入的?

**Comment by qingqing01** [comment]
@roberts-sh 

1. 可以通过DynamicRNN:   http://paddlepaddle.org/documentation/docs/zh/1.4/api_cn/layers_cn.html#dynamicrnn 来组合。

2. Paddle的PR中有个cudnn实现的GRU，支持Tensor作为输入，后续会合入。
