### ISSUE TITLE
编译问题

### ISSUE THREAD

**Issue by ws441572091** [PaddlePaddle/Paddle#17154]
目前本地编译BCLOUD是通过的，其中需要依赖libmkldnn.so.0
<img width="1238" alt="image" src="https://user-images.githubusercontent.com/35720887/56878070-c253a600-6a84-11e9-95da-8623ab4b26d3.png">

希望改成云编译
这个是参考wiki使用云编译的BCLOUD
![5690cf413f66bdb9103ef415f3179a01](https://user-images.githubusercontent.com/35720887/56878016-6f79ee80-6a84-11e9-8a8b-8376313041bf.png)

那么参照这个wiki，我应该如何修改BCLOUD加入依赖的libmkldnn.so.0

【第一次修改为这个，但好像是libmkldnn.so】
![image](https://user-images.githubusercontent.com/35720887/56878104-e4e5bf00-6a84-11e9-9df0-4af770317fbd.png)

**Comment by hutuxian** [comment]
经沟通，问题已解决，先关闭此issue
