### ISSUE TITLE
PR_CI(PADDLE) is not stable.

### ISSUE THREAD

**Issue by guomingz** [PaddlePaddle/Paddle#17150]
Hi,

i found my PR [17130](https://github.com/PaddlePaddle/Paddle/pull/17130) met the PRE_CI(PADDLE) [fail](http://ci.paddlepaddle.org/viewLog.html?buildId=90893&buildTypeId=Paddle_PrCi) issue.
After i checked the [log](http://ci.paddlepaddle.org/downloadBuildLog.html?buildId=90893&plain=true), i found the error was not raised by code but the insufficient gpu memory. e.g `[20:00:56] :	 [Step 1/1] unknown file: Failure
[20:00:56] :	 [Step 1/1] C++ exception with description "cudaMemGetInfo failed in paddle::platform::GetMemoryUsage: out of memory at [/paddle/paddle/fluid/platform/gpu_info.cc:198]`

But i got the [pass](http://ci.paddlepaddle.org/viewLog.html?buildId=90846&buildTypeId=Paddle_PrCi) after rerun testing.

Besides that, the PRE_CI(PADDLE) will rerun automatically, even the previous testing was passed.

Would you please give me some hints on this issue?
@luotao1

**Comment by guomingz** [comment]
From this [summary link](http://ci.paddlepaddle.org/viewType.html?buildTypeId=Paddle_PrCi&branch_Paddle=pull%2F17130&tab=buildTypeStatusDiv), it looks the host yq01-sys-hic-p40-0089.yq01 has the issue on the PR_CI(PADDLE) testing,  you may refer to [this](http://ci.paddlepaddle.org/agentDetails.html?id=120&tab=agentHistory&buildTypeId=Paddle_PrCi)

**Comment by luotao1** [comment]
yq01-sys-hic-p40-0089.yq01 is not stable, and @tianshuo78520a is fixing now.

> the PRE_CI(PADDLE) will rerun automatically, even the previous testing was passed.

The reason is that this PR is rerun several times. Maybe this PR is rerun by others, please notify the waiting lists to check it.

**Comment by wojtuss** [comment]
Closed, due to INT8v1 having been removed.
