### ISSUE TITLE
16.04/GPU/Cmake 出错

### ISSUE THREAD

**Issue by outlookerr** [PaddlePaddle/Paddle#17151]
我是根据这个博客来进行安装的 https://blog.csdn.net/qq_33200967/article/details/83052060
在执行下述命令时报错
cmake .. -DPY_VERSION=3.5 -DWITH_FLUID_ONLY=ON -DWITH_GPU=ON -DWITH_TESTING=OFF -DCMAKE_BUILD_TYPE=Release
日志为
Determining if the pthread_create exist failed with the following output:
Change Dir: /home/lfz/software/Paddle/build/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/make" "cmTC_d8b10/fast"
/usr/bin/make -f CMakeFiles/cmTC_d8b10.dir/build.make CMakeFiles/cmTC_d8b10.dir/build
make[1]: Entering directory '/home/lfz/software/Paddle/build/CMakeFiles/CMakeTmp'
Building C object CMakeFiles/cmTC_d8b10.dir/CheckSymbolExists.c.o
/usr/bin/cc    -fPIC    -o CMakeFiles/cmTC_d8b10.dir/CheckSymbolExists.c.o   -c /home/lfz/software/Paddle/build/CMakeFiles/CMakeTmp/CheckSymbolExists.c
Linking C executable cmTC_d8b10
/usr/bin/cmake -E cmake_link_script CMakeFiles/cmTC_d8b10.dir/link.txt --verbose=1
/usr/bin/cc  -fPIC     CMakeFiles/cmTC_d8b10.dir/CheckSymbolExists.c.o  -o cmTC_d8b10 -rdynamic 
CMakeFiles/cmTC_d8b10.dir/CheckSymbolExists.c.o：在函数‘main’中：
CheckSymbolExists.c:(.text+0x1b)：对‘pthread_create’未定义的引用
collect2: error: ld returned 1 exit status
CMakeFiles/cmTC_d8b10.dir/build.make:97: recipe for target 'cmTC_d8b10' failed
make[1]: *** [cmTC_d8b10] Error 1
make[1]: Leaving directory '/home/lfz/software/Paddle/build/CMakeFiles/CMakeTmp'
Makefile:126: recipe for target 'cmTC_d8b10/fast' failed
make: *** [cmTC_d8b10/fast] Error 2

File /home/lfz/software/Paddle/build/CMakeFiles/CMakeTmp/CheckSymbolExists.c:
/* */
#include <pthread.h>

int main(int argc, char** argv)
{
  (void)argv;
#ifndef pthread_create
  return ((int*)(&pthread_create))[argc];
#else
  (void)argc;
  return 0;
#endif
}

Determining if the function pthread_create exists in the pthreads failed with the following output:
Change Dir: /home/lfz/software/Paddle/build/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/make" "cmTC_c213a/fast"
/usr/bin/make -f CMakeFiles/cmTC_c213a.dir/build.make CMakeFiles/cmTC_c213a.dir/build
make[1]: Entering directory '/home/lfz/software/Paddle/build/CMakeFiles/CMakeTmp'
Building C object CMakeFiles/cmTC_c213a.dir/CheckFunctionExists.c.o
/usr/bin/cc    -fPIC -DCHECK_FUNCTION_EXISTS=pthread_create   -o CMakeFiles/cmTC_c213a.dir/CheckFunctionExists.c.o   -c /usr/share/cmake-3.5/Modules/CheckFunctionExists.c
Linking C executable cmTC_c213a
/usr/bin/cmake -E cmake_link_script CMakeFiles/cmTC_c213a.dir/link.txt --verbose=1
/usr/bin/cc  -fPIC -DCHECK_FUNCTION_EXISTS=pthread_create    CMakeFiles/cmTC_c213a.dir/CheckFunctionExists.c.o  -o cmTC_c213a -rdynamic -lpthreads 
/usr/bin/ld: 找不到 -lpthreads
collect2: error: ld returned 1 exit status
CMakeFiles/cmTC_c213a.dir/build.make:97: recipe for target 'cmTC_c213a' failed
make[1]: *** [cmTC_c213a] Error 1
make[1]: Leaving directory '/home/lfz/software/Paddle/build/CMakeFiles/CMakeTmp'
Makefile:126: recipe for target 'cmTC_c213a/fast' failed
make: *** [cmTC_c213a/fast] Error 2

Performing C++ SOURCE FILE Test AVX512F_FOUND failed with the following output:
Change Dir: /home/lfz/software/Paddle/build/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/make" "cmTC_13f0b/fast"
/usr/bin/make -f CMakeFiles/cmTC_13f0b.dir/build.make CMakeFiles/cmTC_13f0b.dir/build
make[1]: Entering directory '/home/lfz/software/Paddle/build/CMakeFiles/CMakeTmp'
Building CXX object CMakeFiles/cmTC_13f0b.dir/src.cxx.o
/usr/bin/c++     -DAVX512F_FOUND -mavx512f   -o CMakeFiles/cmTC_13f0b.dir/src.cxx.o -c /home/lfz/software/Paddle/build/CMakeFiles/CMakeTmp/src.cxx
Linking CXX executable cmTC_13f0b
/usr/bin/cmake -E cmake_link_script CMakeFiles/cmTC_13f0b.dir/link.txt --verbose=1
/usr/bin/c++    -DAVX512F_FOUND -mavx512f    CMakeFiles/cmTC_13f0b.dir/src.cxx.o  -o cmTC_13f0b -rdynamic 
make[1]: Leaving directory '/home/lfz/software/Paddle/build/CMakeFiles/CMakeTmp'

Return value: FAILED_TO_RUN
Source file was:

#include <immintrin.h>
int main()
{
    __m512i a = _mm512_set_epi32 (-1, 2, -3, 4, -1, 2, -3, 4,
                                  13, -5, 6, -7, 9, 2, -6, 3);
    __m512i result = _mm512_abs_epi32 (a);
    return 0;
}

**Comment by hutuxian** [comment]
请根据我们的源码编译文档进行编译：http://paddlepaddle.org/documentation/docs/zh/1.4/beginners_guide/install/compile/fromsource.html
