### ISSUE TITLE
调用预测库报core dump

### ISSUE THREAD

**Issue by jjlucus** [PaddlePaddle/Paddle#17168]
为使您的问题得到快速解决，在建立Issue前，请您先通过如下方式搜索是否有相似问题:【搜索issue关键字】【使用labels筛选】【官方文档】

如果您没有查询到相似问题，为快速解决您的提问，建立issue时请提供如下细节信息：
- 标题：简洁、精准描述您的问题，例如“最新预测库的API文档在哪儿 ”
- 版本、环境信息：
    1）PaddlePaddle版本：1.3.0
    2）CPU：Intel(R) Xeon(R) CPU  E5645  @ 2.40GHz，MKL/OpenBlas/MKLDNN使用情况未知，但启动时会报mkl和mkldnn动态库找不到的错误，需设置LD_LIBRARY_PATH添加这两个库的路径；
    4）系统环境：CentOS release 6.3，Python 2.7.10
-预测信息
    1）C++预测：cpu_noavx_openblas，1.4版本
    2）预测库来源：官网下载
- 复现信息：如为报错，请给出复现环境、复现步骤
- 问题描述：请详细描述您的问题，同步贴出报错信息、日志/代码关键片段

启动后马上报core dump，gdb调试信息如下
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007fa81473b4c5 in _dl_map_object () from /opt/compiler/gcc-4.8.2/lib64/ld-linux-x86-64.so.2
[Current thread is 1 (LWP 29665)]
warning: File "/home/opt/gcc-4.8.2.bpkg-r4/gcc-4.8.2.bpkg-r4/lib64/libstdc++.so.6.0.19-gdb.py" auto-loading has been declined by your `auto-load safe-path' set to "$debugdir:$datadir/auto-load".
(gdb) bt
#0  0x00007fa81473b4c5 in _dl_map_object () from /opt/compiler/gcc-4.8.2/lib64/ld-linux-x86-64.so.2
#1  0x00007fa814745805 in dl_open_worker () from /opt/compiler/gcc-4.8.2/lib64/ld-linux-x86-64.so.2
#2  0x00007fa814741694 in _dl_catch_error () from /opt/compiler/gcc-4.8.2/lib64/ld-linux-x86-64.so.2
#3  0x00007fa81474521b in _dl_open () from /opt/compiler/gcc-4.8.2/lib64/ld-linux-x86-64.so.2
#4  0x00007fa8138a001b in dlopen_doit () from /opt/compiler/gcc-4.8.2/lib/libdl.so.2
#5  0x00007fa814741694 in _dl_catch_error () from /opt/compiler/gcc-4.8.2/lib64/ld-linux-x86-64.so.2
#6  0x00007fa8138a05cd in _dlerror_run () from /opt/compiler/gcc-4.8.2/lib/libdl.so.2
#7  0x00007fa8138a00b1 in dlopen@@GLIBC_2.2.5 () from /opt/compiler/gcc-4.8.2/lib/libdl.so.2
#8  0x00007fa809e5ad63 in mkl_serv_inspector_suppress () from /home/syz/work/baidu/paddle-serving/inferencer-fluid-cpu/lib/libmklml_intel.so
#9  0x00007fa809e5acbd in mkl_serv_lock () from /home/syz/work/baidu/paddle-serving/inferencer-fluid-cpu/lib/libmklml_intel.so
#10 0x00007fa809e56739 in mkl_serv_finalize () from /home/syz/work/baidu/paddle-serving/inferencer-fluid-cpu/lib/libmklml_intel.so
#11 0x00007fa814741e38 in _dl_fini () from /opt/compiler/gcc-4.8.2/lib64/ld-linux-x86-64.so.2
#12 0x00007fa806edceb9 in __run_exit_handlers () from /opt/compiler/gcc-4.8.2/lib/libc.so.6
#13 0x00007fa806edcf05 in exit () from /opt/compiler/gcc-4.8.2/lib/libc.so.6
#14 0x00007fa806ec6bdc in __libc_start_main () from /opt/compiler/gcc-4.8.2/lib/libc.so.6
#15 0x00000000005241ed in _start ()

Thank you for contributing to PaddlePaddle.
Before submitting the issue, you could search issue in the github in case that th
If there is no solution,please make sure that this is an inference issue including the following details :
**System information**
-PaddlePaddle version （eg.1.1）or CommitID
-CPU: including CPUMKL/OpenBlas/MKLDNN version
-GPU: including CUDA/CUDNN version
-OS Platform (eg.Mac OS 10.14)
-Python version
-Cmake orders
-C++version.txt
-API information
**To Reproduce**
Steps to reproduce the behavior
**Describe your current behavior**
**Code to reproduce the issue**
**Other info / logs**

**Comment by sandyhouse** [comment]
![屏幕快照 2019-04-30 上午9 53 42](https://user-images.githubusercontent.com/6737864/56937174-ed460480-6b2d-11e9-9778-aa439a7ebb23.png)
从报错信息看，dlopen错误，设置LD_LIBRARY_PATH是否可以解决？

**Comment by sandyhouse** [comment]
I closed this issue. If you have any question, feel free to reopen it.
