### ISSUE TITLE
load_vars后模型正常运行，想要再进行save_inference_model时报错

### ISSUE THREAD

**Issue by CYang828** [PaddlePaddle/Paddle#17160]
- 版本、环境信息：
    1）PaddlePaddle版本：1.4
    2）GPU： NVIDIA Corporation GP102 [GeForce GTX 1080 Ti] 
                      CUDA Version 9.0.176
    3）系统环境：centos 7 + python3.6.8
-预测信息
![image](https://user-images.githubusercontent.com/6592136/56889101-250a6900-6aa8-11e9-8500-e6542e07da55.png)

- 复现信息：如为报错，请给出复现环境、复现步骤
![image](https://user-images.githubusercontent.com/6592136/56889175-4bc89f80-6aa8-11e9-9060-4e6d10cae771.png)

- 问题描述：我想把官方的lac模型加载finetune参数后，用save_inference_model保存起来，怎样做比较好？如果这样操作不正确，应该如何操作，感谢~

**Comment by D-DanielYang** [comment]
+1同问

**Comment by hutuxian** [comment]
请先参考下列相关issue初步排查原因：https://github.com/PaddlePaddle/Paddle/issues/15270 https://github.com/PaddlePaddle/Paddle/issues/16098

**Comment by CYang828** [comment]
已解决，save_inference_model的feeded_var_names和target_vars的选择问题
`fluid.io.save_inference_model('lac-inference-model/',
                              feeded_var_names=[ernie_inputs['src_ids'].name,
                                                ernie_inputs['sent_ids'].name,
                                                ernie_inputs['pos_ids'].name,
                                                ernie_inputs['input_mask'].name,
                                                ernie_inputs['seq_lens'].name],
                              target_vars=[infer_ret['words'], infer_ret['crf_decode']],
                              executor=exe,
                              main_program=infer_program)`
