### ISSUE TITLE
用GPU训练deeplab_v3p网络时，总是提示无法分配内存

### ISSUE THREAD

**Issue by namemzy** [PaddlePaddle/Paddle#17171]
W0429 20:27:09.415925 29126 device_context.cc:203] Please NOTE: device: 0, CUDA Capability: 61, Driver Version: 9.0, Runtime Version: 9.0
W0429 20:27:09.415963 29126 device_context.cc:210] device: 0, cuDNN Version: 7.0.
load succeed
W0429 20:27:11.855363 29126 system_allocator.cc:122] Cannot malloc 7087.16 MB GPU memory. Please shrink FLAGS_fraction_of_gpu_memory_to_use environment variable to a lower value. Current value is 0.92
W0429 20:27:11.855510 29126 legacy_allocator.cc:161] Cannot allocate 36.000000MB in GPU 0, available 342.625000MB
W0429 20:27:11.855520 29126 legacy_allocator.cc:164] total 8502771712
W0429 20:27:11.855527 29126 legacy_allocator.cc:165] GpuMinChunkSize 256.000000B
W0429 20:27:11.855535 29126 legacy_allocator.cc:168] GpuMaxChunkSize 6.921052GB
W0429 20:27:11.855543 29126 legacy_allocator.cc:171] GPU memory used: 6.874296GB
Traceback (most recent call last):
  File "train.py", line 227, in <module>
    train(model)
  File "train.py", line 218, in train
    trainLoop()
  File "train.py", line 182, in trainLoop
    fetch_list=[loss,predict,iou])
  File "/home/xgs/anaconda3/lib/python3.6/site-packages/paddle/fluid/executor.py", line 472, in run
    self.executor.run(program.desc, scope, 0, True, True)
paddle.fluid.core.EnforceNotMet: cudaMemcpy failed in paddle::platform::GpuMemcpySync: invalid argument at [/paddle/paddle/fluid/platform/gpu_info.cc:184]
PaddlePaddle Call Stacks: 
0       0x7fcd33138ea6p paddle::platform::EnforceNotMet::EnforceNotMet(std::__exception_ptr::exception_ptr, char const*, int) + 486
1       0x7fcd349d895ap paddle::platform::GpuMemcpySync(void*, void const*, unsigned long, cudaMemcpyKind) + 234
2       0x7fcd34982cc3p paddle::framework::TensorCopySync(paddle::framework::Tensor const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&, paddle::framework::Tensor*) + 1107
3       0x7fcd33c13207p paddle::operators::ReshapeKernel::operator()(paddle::framework::ExecutionContext const&) const + 1015
4       0x7fcd3493db3cp paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&) const + 492
5       0x7fcd34939c7fp paddle::framework::OperatorBase::Run(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&) + 463
6       0x7fcd3320dba3p paddle::framework::Executor::RunPreparedContext(paddle::framework::ExecutorPrepareContext*, paddle::framework::Scope*, bool, bool, bool) + 227
7       0x7fcd3320e5d0p paddle::framework::Executor::Run(paddle::framework::ProgramDesc const&, paddle::framework::Scope*, int, bool, bool) + 128
8       0x7fcd33124c4bp
9       0x7fcd3316082ep
10      0x564da37b7b94p _PyCFunction_FastCallDict + 340
11      0x564da38477cep
12      0x564da3869cbap _PyEval_EvalFrameDefault + 762
13      0x564da3840a94p
14      0x564da3841941p
15      0x564da3847755p
16      0x564da386aa7ap _PyEval_EvalFrameDefault + 4282
17      0x564da3840daep
18      0x564da3841941p
19      0x564da3847755p
20      0x564da3869cbap _PyEval_EvalFrameDefault + 762
21      0x564da3840daep
22      0x564da3841941p
23      0x564da3847755p
24      0x564da3869cbap _PyEval_EvalFrameDefault + 762
25      0x564da3842459p PyEval_EvalCodeEx + 809
26      0x564da38431ecp PyEval_EvalCode + 28
27      0x564da38bd9a4p
28      0x564da38bdda1p PyRun_FileExFlags + 161
29      0x564da38bdfa4p PyRun_SimpleFileExFlags + 452
30      0x564da38c1a9ep Py_Main + 1598
31      0x564da37894bep main + 238
32      0x7fcd846ba830p __libc_start_main + 240
33      0x564da3870773p

*** Aborted at 1556540832 (unix time) try "date -d @1556540832" if you are using GNU date ***
PC: @                0x0 (unknown)
*** SIGSEGV (@0x10) received by PID 29126 (TID 0x7fcd850ec740) from PID 16; stack trace: ***
    @     0x7fcd84a75390 (unknown)
    @     0x7fcd349d6a50 paddle::memory::detail::MetadataCache::load()
    @     0x7fcd349d6204 paddle::memory::detail::MemoryBlock::type()
    @     0x7fcd349d5575 paddle::memory::detail::BuddyAllocator::Free()
    @     0x7fcd349d18f5 paddle::memory::allocation::LegacyAllocator::Free()
    @     0x7fcd3313c969 std::_Sp_counted_base<>::_M_release()
    @     0x7fcd3313dd1d paddle::framework::Variable::PlaceholderImpl<>::~PlaceholderImpl()
    @     0x7fcd349739ed paddle::framework::Scope::~Scope()
    @     0x7fcd349738f1 paddle::framework::Scope::DropKids()
    @     0x7fcd3497397d paddle::framework::Scope::~Scope()
    @     0x7fcd3313685a _ZN8pybind116class_IN6paddle9framework5ScopeEJEE7deallocERNS_6detail16value_and_holderE
    @     0x7fcd33163dba pybind11::detail::clear_instance()
    @     0x7fcd33163f3f pybind11_object_dealloc
    @     0x564da37de890 PyDict_SetItem
    @     0x564da37fc49b _PyModule_ClearDict
    @     0x564da3852e28 PyImport_Cleanup
    @     0x564da38b7411 Py_FinalizeEx
    @     0x564da38c17d6 Py_Main
    @     0x564da37894be main
    @     0x7fcd846ba830 __libc_start_main
    @     0x564da3870773 (unknown)
段错误

我的GPU是gtx1080,。已经尝试多次修改FLAGS_fraction_of_gpu_memory_to_use，还是会出现同样的问题，请问这种情况如何解决？

**Comment by hutuxian** [comment]
应该是显存大小不够的问题。请确保运行的时候GPU卡没有被其他进程占用，并且可以尝试诸如调小batch_size等方法来缩小显存占用量。
