### ISSUE TITLE
执行paddle.fluid.install_check.run_check()出错

### ISSUE THREAD

**Issue by outlookerr** [PaddlePaddle/Paddle#17177]
报错信息如下
Running Verify Fluid Program ... 
W0430 10:57:48.789304 26099 device_context.cc:261] Please NOTE: device: 0, CUDA Capability: 50, Driver API Version: 9.0, Runtime API Version: 8.0
W0430 10:57:48.790666 26099 device_context.cc:269] device: 0, cuDNN Version: 5.1.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.5/dist-packages/paddle/fluid/install_check.py", line 63, in run_check
    exe.run(default_startup_program())
  File "/usr/local/lib/python3.5/dist-packages/paddle/fluid/executor.py", line 534, in run
    use_program_cache=use_program_cache)
  File "/usr/local/lib/python3.5/dist-packages/paddle/fluid/executor.py", line 606, in _run
    exe.run(program.desc, scope, 0, True, True, fetch_var_name)
paddle.fluid.core.EnforceNotMet: Invoke operator fill_constant error.
Python Callstacks: 
  File "/usr/local/lib/python3.5/dist-packages/paddle/fluid/framework.py", line 1725, in _prepend_op
    attrs=kwargs.get("attrs", None))
  File "/usr/local/lib/python3.5/dist-packages/paddle/fluid/initializer.py", line 167, in __call__
    stop_gradient=True)
  File "/usr/local/lib/python3.5/dist-packages/paddle/fluid/framework.py", line 1619, in create_parameter
    initializer(param, self)
  File "/usr/local/lib/python3.5/dist-packages/paddle/fluid/layer_helper_base.py", line 316, in create_parameter
    **attr._to_kwargs(with_initializer=True))
  File "/usr/local/lib/python3.5/dist-packages/paddle/fluid/dygraph/layers.py", line 88, in create_parameter
    default_initializer)
  File "/usr/local/lib/python3.5/dist-packages/paddle/fluid/dygraph/nn.py", line 904, in build_once
    attr=self._bias_attr, shape=size, dtype=self._dtype, is_bias=True)
  File "/usr/local/lib/python3.5/dist-packages/paddle/fluid/dygraph/layers.py", line 155, in __call__
    self.build_once(*inputs)
  File "/usr/local/lib/python3.5/dist-packages/paddle/fluid/install_check.py", line 37, in forward
    x = self._fc1(inputs)
  File "/usr/local/lib/python3.5/dist-packages/paddle/fluid/dygraph/layers.py", line 157, in __call__
    outputs = self.forward(*inputs)
  File "/usr/local/lib/python3.5/dist-packages/paddle/fluid/install_check.py", line 58, in run_check
    out = simple_layer(inp)
  File "<stdin>", line 1, in <module>
C++ Callstacks: 
Enforce failed. Expected allocating <= available, but received allocating:1835602970 > available:1791426304.
Insufficient GPU memory to allocation. at [/paddle/paddle/fluid/platform/gpu_info.cc:262]
PaddlePaddle Call Stacks: 
0       0x7f1c46264cf8p void paddle::platform::EnforceNotMet::Init<std::string>(std::string, char const*, int) + 360
1       0x7f1c46265047p paddle::platform::EnforceNotMet::EnforceNotMet(std::string const&, char const*, int) + 87
2       0x7f1c480d74c6p paddle::platform::GpuMaxChunkSize() + 630
3       0x7f1c480ab722p
4       0x7f1c83ecca99p
5       0x7f1c480aadcdp paddle::memory::legacy::GetGPUBuddyAllocator(int) + 109
6       0x7f1c480abbf3p void* paddle::memory::legacy::Alloc<paddle::platform::CUDAPlace>(paddle::platform::CUDAPlace const&, unsigned long) + 35
7       0x7f1c480ac035p paddle::memory::allocation::LegacyAllocator::AllocateImpl(unsigned long, paddle::memory::allocation::Allocator::Attr) + 389
8       0x7f1c480d13dbp paddle::memory::allocation::Allocator::Allocate(unsigned long, paddle::memory::allocation::Allocator::Attr) + 27
9       0x7f1c4809fc33p paddle::memory::allocation::AllocatorFacade::Alloc(boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&, unsigned long, paddle::memory::allocation::Allocator::Attr) + 435
10      0x7f1c4809fd51p paddle::memory::allocation::AllocatorFacade::AllocShared(boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&, unsigned long, paddle::memory::allocation::Allocator::Attr) + 33
11      0x7f1c47ca90d0p paddle::memory::AllocShared(boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&, unsigned long, paddle::memory::allocation::Allocator::Attr) + 48
12      0x7f1c4807297ap paddle::framework::Tensor::mutable_data(boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_>, paddle::framework::proto::VarType_Type, paddle::memory::allocation::Allocator::Attr, unsigned long) + 154
13      0x7f1c46f682b1p paddle::operators::FillConstantKernel<float>::Compute(paddle::framework::ExecutionContext const&) const + 497
14      0x7f1c46f6b453p std::_Function_handler<void (paddle::framework::ExecutionContext const&), paddle::framework::OpKernelRegistrarFunctor<paddle::platform::CUDAPlace, false, 0ul, paddle::operators::FillConstantKernel<float>, paddle::operators::FillConstantKernel<double>, paddle::operators::FillConstantKernel<long>, paddle::operators::FillConstantKernel<int>, paddle::operators::FillConstantKernel<paddle::platform::float16> >::operator()(char const*, char const*, int) const::{lambda(paddle::framework::ExecutionContext const&)#1}>::_M_invoke(std::_Any_data const&, paddle::framework::ExecutionContext const&) + 35
15      0x7f1c47fe5e26p paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&, paddle::framework::RuntimeContext*) const + 662
16      0x7f1c47fe6594p paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&) const + 292
17      0x7f1c47fe3ebcp paddle::framework::OperatorBase::Run(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&) + 332
18      0x7f1c463d5faep paddle::framework::Executor::RunPreparedContext(paddle::framework::ExecutorPrepareContext*, paddle::framework::Scope*, bool, bool, bool) + 382
19      0x7f1c463d6defp paddle::framework::Executor::Run(paddle::framework::ProgramDesc const&, paddle::framework::Scope*, int, bool, bool, std::vector<std::string, std::allocator<std::string> > const&, bool) + 143
20      0x7f1c462543aep
21      0x7f1c4629728ep
22            0x4ea137p PyCFunction_Call + 119
23            0x53c176p PyEval_EvalFrameEx + 23030
24            0x53fc97p
25            0x53bc93p PyEval_EvalFrameEx + 21779
26            0x53fc97p
27            0x53b83fp PyEval_EvalFrameEx + 20671
28            0x53b294p PyEval_EvalFrameEx + 19220
29            0x53fc97p
30            0x5409bfp PyEval_EvalCode + 31
31            0x60cb42p
32            0x46b7ffp PyRun_InteractiveOneObject + 689
33            0x46b9a8p PyRun_InteractiveLoopFlags + 232
34            0x46cf00p
35            0x4cf412p
36            0x4d0001p main + 225
37      0x7f1c83b14830p __libc_start_main + 240
38            0x5d6999p _start + 41
谢谢你的任何建议和指导

**Comment by sandyhouse** [comment]
“Enforce failed. Expected allocating <= available, but received allocating:1835602970 > available:1791426304”, 从错误信息看，是请求分配内存过大。可以试试将FLAGS_fraction_of_gpu_memory_to_use设置成较小的值。

**Comment by outlookerr** [comment]
@sandyhouse 我是通过pip安装的，这种方式能修改CMakelist吗

**Comment by sandyhouse** [comment]
不需要修改CMakelist，例如：
export FLAGS_fraction_of_gpu_memory_to_use=0.34

**Comment by outlookerr** [comment]
@sandyhouse  谢谢你的建议，但是好像问题不出在这，错误仍然存在

**Comment by sandyhouse** [comment]
排查一下GPU是否被占用（nvidia-smi的输出是什么）？能否提供一个可复现的环境？谢谢。

**Comment by outlookerr** [comment]
GPU应该是没有被占用的
 NVIDIA-SMI 384.130                Driver Version: 384.130                   |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 850M    Off  | 00000000:01:00.0 Off |                  N/A |
| N/A   42C    P8    N/A /  N/A |    246MiB /  2002MiB |      0%      Default |
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0      1251      G   /usr/lib/xorg/Xorg                           136MiB |
|    0      2250      G   compiz                                        58MiB |
|    0      2493      G   fcitx-qimpanel                                 8MiB |
|    0     12830      G   /usr/lib/firefox/firefox                       1MiB |
|    0     30616      G   ...quest-channel-token=7115493144571559904    38MiB |
+-----------------------------------------------------------------------------+
@sandyhouse

**Comment by sandyhouse** [comment]
从您这个输出结果来看，GPU是有进程在使用的：
| N/A 42C P8 N/A / N/A | 246MiB / 2002MiB |
并且
| 0 1251 G /usr/lib/xorg/Xorg 136MiB |
| 0 2250 G compiz 58MiB |
| 0 2493 G fcitx-qimpanel 8MiB |
| 0 12830 G /usr/lib/firefox/firefox 1MiB |
| 0 30616 G ...quest-channel-token=7115493144571559904 38MiB |

**Comment by outlookerr** [comment]
@sandyhouse  我又重新安装了一下，结果import 的时候出现了问题，您看一下
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/lfz/.local/lib/python3.5/site-packages/paddle/__init__.py", line 25, in <module>
    import paddle.dataset
  File "/home/lfz/.local/lib/python3.5/site-packages/paddle/dataset/__init__.py", line 28, in <module>
    import paddle.dataset.mq2007
  File "/home/lfz/.local/lib/python3.5/site-packages/paddle/dataset/mq2007.py", line 30, in <module>
    import rarfile
  File "/home/lfz/.local/lib/python3.5/site-packages/rarfile.py", line 109, in <module>
    from cryptography.hazmat.primitives.ciphers import algorithms, modes, Cipher
  File "/usr/lib/python3/dist-packages/cryptography/hazmat/primitives/ciphers/__init__.py", line 7, in <module>
    from cryptography.hazmat.primitives.ciphers.base import (
  File "/usr/lib/python3/dist-packages/cryptography/hazmat/primitives/ciphers/base.py", line 16, in <module>
    from cryptography.hazmat.backends.interfaces import CipherBackend
  File "/usr/lib/python3/dist-packages/cryptography/hazmat/backends/__init__.py", line 7, in <module>
    import pkg_resources
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2927, in <module>
    @_call_aside
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2913, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2952, in _initialize_master_working_set
    add_activation_listener(lambda dist: dist.activate())
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 956, in subscribe
    callback(dist)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2952, in <lambda>
    add_activation_listener(lambda dist: dist.activate())
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2515, in activate
    declare_namespace(pkg)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2097, in declare_namespace
    _handle_ns(packageName, path_item)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2047, in _handle_ns
    _rebuild_mod_path(path, packageName, module)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2066, in _rebuild_mod_path
    orig_path.sort(key=position_in_sys_path)
AttributeError: '_NamespacePath' object has no attribute 'sort'

**Comment by sandyhouse** [comment]
参考下以下链接：https://stackoverflow.com/questions/47955397/pip3-error-namespacepath-object-has-no-attribute-sort 
https://github.com/googleapis/google-cloud-python/issues/2990

**Comment by outlookerr** [comment]
@sandyhouse 您好，我在进行run_check的时候找不到cudnn的库，但是我确实复制进入cuda/lib64中，并在～/.bashrc中export LD_LIBRARY_PATH=/usr/local/cuda/lib64:$LD_LIBRARY_PATH并生效。仍然还是报错
>>> paddle.fluid.install_check.run_check()
Running Verify Fluid Program ... 
W0506 14:56:06.782366 32108 device_context.cc:261] Please NOTE: device: 0, CUDA Capability: 50, Driver API Version: 9.0, Runtime API Version: 8.0
W0506 14:56:06.782572 32108 dynamic_loader.cc:107] Can not find library: libcudnn.so. Please try to add the lib path to LD_LIBRARY_PATH.
W0506 14:56:06.782603 32108 dynamic_loader.cc:165] Failed to find dynamic library: libcudnn.so ( libcudnn.so: cannot open shared object file: No such file or directory ) 
 Please specify its path correctly using following ways: 
 Method. set environment variable LD_LIBRARY_PATH on Linux or DYLD_LIBRARY_PATH on Mac OS. 
 For instance, issue command: export LD_LIBRARY_PATH=... 
 Note: After Mac OS 10.11, using the DYLD_LIBRARY_PATH is impossible unless System Integrity Protection (SIP) is disabled.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/lfz/.local/lib/python3.5/site-packages/paddle/fluid/install_check.py", line 63, in run_check
    exe.run(default_startup_program())
  File "/home/lfz/.local/lib/python3.5/site-packages/paddle/fluid/executor.py", line 534, in run
    use_program_cache=use_program_cache)
  File "/home/lfz/.local/lib/python3.5/site-packages/paddle/fluid/executor.py", line 606, in _run
    exe.run(program.desc, scope, 0, True, True, fetch_var_name)
paddle.fluid.core.EnforceNotMet: Invoke operator fill_constant error.
Python Callstacks: 
  File "/home/lfz/.local/lib/python3.5/site-packages/paddle/fluid/framework.py", line 1725, in _prepend_op
    attrs=kwargs.get("attrs", None))
  File "/home/lfz/.local/lib/python3.5/site-packages/paddle/fluid/initializer.py", line 167, in __call__
    stop_gradient=True)
  File "/home/lfz/.local/lib/python3.5/site-packages/paddle/fluid/framework.py", line 1619, in create_parameter
    initializer(param, self)
  File "/home/lfz/.local/lib/python3.5/site-packages/paddle/fluid/layer_helper_base.py", line 316, in create_parameter
    **attr._to_kwargs(with_initializer=True))
  File "/home/lfz/.local/lib/python3.5/site-packages/paddle/fluid/dygraph/layers.py", line 88, in create_parameter
    default_initializer)
  File "/home/lfz/.local/lib/python3.5/site-packages/paddle/fluid/dygraph/nn.py", line 904, in build_once
    attr=self._bias_attr, shape=size, dtype=self._dtype, is_bias=True)
  File "/home/lfz/.local/lib/python3.5/site-packages/paddle/fluid/dygraph/layers.py", line 155, in __call__
    self.build_once(*inputs)
  File "/home/lfz/.local/lib/python3.5/site-packages/paddle/fluid/install_check.py", line 37, in forward
    x = self._fc1(inputs)
  File "/home/lfz/.local/lib/python3.5/site-packages/paddle/fluid/dygraph/layers.py", line 157, in __call__
    outputs = self.forward(*inputs)
  File "/home/lfz/.local/lib/python3.5/site-packages/paddle/fluid/install_check.py", line 58, in run_check
    out = simple_layer(inp)
  File "<stdin>", line 1, in <module>
C++ Callstacks: 
Cannot load cudnn shared library. Cannot invoke method cudnnGetVersion at [/paddle/paddle/fluid/platform/dynload/cudnn.cc:59]
PaddlePaddle Call Stacks: 
0       0x7f9d107e87d0p void paddle::platform::EnforceNotMet::Init<char const*>(char const*, char const*, int) + 352
1       0x7f9d107e8b49p paddle::platform::EnforceNotMet::EnforceNotMet(std::__exception_ptr::exception_ptr, char const*, int) + 137
2       0x7f9d1263a248p paddle::platform::dynload::EnforceCUDNNLoaded(char const*) + 200
3       0x7f9d12616a15p paddle::platform::CUDADeviceContext::CUDADeviceContext(paddle::platform::CUDAPlace) + 741
4       0x7f9d1261b6e8p std::_Function_handler<std::unique_ptr<paddle::platform::DeviceContext, std::default_delete<paddle::platform::DeviceContext> > (), std::reference_wrapper<std::_Bind_simple<void paddle::platform::EmplaceDeviceContext<paddle::platform::CUDADeviceContext, paddle::platform::CUDAPlace>(std::map<boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_>, std::shared_future<std::unique_ptr<paddle::platform::DeviceContext, std::default_delete<paddle::platform::DeviceContext> > >, std::less<boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> >, std::allocator<std::pair<boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const, std::shared_future<std::unique_ptr<paddle::platform::DeviceContext, std::default_delete<paddle::platform::DeviceContext> > > > > >*, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_>)::{lambda()#1} ()> > >::_M_invoke(std::_Any_data const&) + 104
5       0x7f9d12619ccap std::_Function_handler<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> (), std::__future_base::_Task_setter<std::unique_ptr<std::__future_base::_Result<std::unique_ptr<paddle::platform::DeviceContext, std::default_delete<paddle::platform::DeviceContext> > >, std::__future_base::_Result_base::_Deleter>, std::unique_ptr<paddle::platform::DeviceContext, std::default_delete<paddle::platform::DeviceContext> > > >::_M_invoke(std::_Any_data const&) + 42
6       0x7f9d108b4e57p std::__future_base::_State_base::_M_do_set(std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> ()>&, bool&) + 39
7       0x7f9d463f1a99p
8       0x7f9d1261cfbcp std::__future_base::_Deferred_state<std::_Bind_simple<void paddle::platform::EmplaceDeviceContext<paddle::platform::CUDADeviceContext, paddle::platform::CUDAPlace>(std::map<boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_>, std::shared_future<std::unique_ptr<paddle::platform::DeviceContext, std::default_delete<paddle::platform::DeviceContext> > >, std::less<boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> >, std::allocator<std::pair<boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const, std::shared_future<std::unique_ptr<paddle::platform::DeviceContext, std::default_delete<paddle::platform::DeviceContext> > > > > >*, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_>)::{lambda()#1} ()>, std::unique_ptr<paddle::platform::DeviceContext, std::default_delete<paddle::platform::DeviceContext> > >::_M_run_deferred() + 220
9       0x7f9d126174e9p paddle::platform::DeviceContextPool::Get(boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&) + 137
10      0x7f9d12569bd8p paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&, paddle::framework::RuntimeContext*) const + 72
11      0x7f9d1256a594p paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&) const + 292
12      0x7f9d12567ebcp paddle::framework::OperatorBase::Run(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&) + 332
13      0x7f9d10959faep paddle::framework::Executor::RunPreparedContext(paddle::framework::ExecutorPrepareContext*, paddle::framework::Scope*, bool, bool, bool) + 382
14      0x7f9d1095adefp paddle::framework::Executor::Run(paddle::framework::ProgramDesc const&, paddle::framework::Scope*, int, bool, bool, std::vector<std::string, std::allocator<std::string> > const&, bool) + 143
15      0x7f9d107d83aep
16      0x7f9d1081b28ep
17            0x4ea137p PyCFunction_Call + 119
18            0x53c176p PyEval_EvalFrameEx + 23030
19            0x53fc97p
20            0x53bc93p PyEval_EvalFrameEx + 21779
21            0x53fc97p
22            0x53b83fp PyEval_EvalFrameEx + 20671
23            0x53b294p PyEval_EvalFrameEx + 19220
24            0x53fc97p
25            0x5409bfp PyEval_EvalCode + 31
26            0x60cb42p
27            0x46b7ffp PyRun_InteractiveOneObject + 689
28            0x46b9a8p PyRun_InteractiveLoopFlags + 232
29            0x46cf00p
30            0x4cf412p
31            0x4d0001p main + 225
32      0x7f9d46039830p __libc_start_main + 240
33            0x5d6999p _start + 41

**Comment by sandyhouse** [comment]
你是直接拷贝的libcudnn.so吗，一般来说libcudnn.so都是软链接。你也可以直接吧cudnn的库目录添加到LD_LIBRARY_PATH中 @outlookerr

**Comment by outlookerr** [comment]
@sandyhouse 我是直接cp过去的，按照文件大小的话应该不是软链接，另外把cudnn的库目录添加到LD_LIBRARY_PATH中是什么意思，我不太理解

**Comment by sandyhouse** [comment]
@outlookerr 例如，安装完cudnn后，我的cudnn的目录是cudnn7.1, 可以设置直接设置LD_LIBRARY_PATH=cudnn7.1/lib64:$LD_LIBRARY_PATH。libcudnn.so找不到的问题大都是环境问题，我这边没发复现这个问题，可以在仔细检查一下。如果有更多信息，我们可以继续讨论。

**Comment by outlookerr** [comment]
感谢支持！问题已经全部解决了！ @sandyhouse
