### ISSUE TITLE
pip 安装CPU版本 使用提示No module named 'proto'

### ISSUE THREAD

**Issue by Yaque** [PaddlePaddle/Paddle#17188]
为使您的问题得到快速解决，在建立Issue前，请您先通过如下方式搜索是否有相似问题:【搜索issue关键字】【使用labels筛选】【官方文档】

建立issue时，为快速解决问题，请您根据使用情况给出如下信息：
- 标题：请包含关键词“安装错误”/“编译错误”，例如“Mac编译错误”
- 版本、环境信息：
    1）PaddlePaddle版本：1.4.1
    2）CPU：i7-8u
    3）GPU：150max
    4）系统环境：ubuntu 18.04 python3.6
- 安装方式信息：
1）pip 在线安装 使用的清华源， 没办法，在寝室移动的网太慢了。刚刚装的机器没有装proxy(有没有简单的Ubuntu代理方式（基于ss的），求帮助)

` File "/usr/local/lib/python3.6/dist-packages/paddle/fluid/executor.py", line 847, in train_from_dataset
    print_period=print_period)
  File "/usr/local/lib/python3.6/dist-packages/paddle/fluid/executor.py", line 676, in _prepare_trainer
    trainer = TrainerFactory()._create_trainer(program._fleet_opt)
  File "/usr/local/lib/python3.6/dist-packages/paddle/fluid/trainer_factory.py", line 30, in _create_trainer
    trainer = MultiTrainer()
  File "/usr/local/lib/python3.6/dist-packages/paddle/fluid/trainer_desc.py", line 71, in __init__
    super(MultiTrainer, self).__init__()
  File "/usr/local/lib/python3.6/dist-packages/paddle/fluid/trainer_desc.py", line 26, in __init__
    from proto import trainer_desc_pb2
ModuleNotFoundError: No module named 'proto'
`
我在issu里查了一下，有说需要make gen_proto_py
add:
but i find that
![image](https://user-images.githubusercontent.com/23148165/57137329-227a7d00-6de2-11e9-92a8-afc61caf65a2.png)
但是他依旧不好使
解决中。。。

我还没有去尝试
但是理论上我使用pip安装应该是全的吧。也没有哪提示说我还需要去编译他啊。
求科普，今天刚刚接触这个东西。由于电脑cuda是用的10.0所以没有装gpu版本

**Comment by Yaque** [comment]
没找到原因，但是我找了个笨办法，如下：
`import sys
sys.path.append("/usr/local/lib/python3.6/dist-packages/paddle/fluid")
sys.path.append("/usr/local/lib/python3.6/dist-packages/paddle/fluid/proto")`
我猜可能是我自己安装的时候有问题，我的是直接的系统自带的py36环境。

**Comment by Yaque** [comment]
有人能说一下原因吗？

**Comment by AlessandroVol23** [comment]
Hi I've got the same problem when trying to execute the code in https://github.com/yaoxuefeng6/Paddle_baseline_KDD2019. 

I am using a conda environment and added it to the base environment and tried to add the following lines:

```python
import sys
sys.path.append("~/anaconda3/lib/python3.7/site-packages/paddle/fluid/")
sys.path.append("~/anaconda3/lib/python3.7/site-packages/paddle/fluid/proto/")
```

Unfortunately I still have the same error:

```python
In [6]: import proto
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-6-ae163c4dffa4> in <module>
----> 1 import proto

ModuleNotFoundError: No module named 'proto'
```

I tried to install it via 

```bash 
pip install protobuf
pip install google
pip install google-cloud 
```

But it didn't help.

Any ideas how to solve it?

**Comment by Yaque** [comment]
Sorry, maybe you can see here
![image](https://user-images.githubusercontent.com/23148165/57696228-43cb3c80-761e-11e9-8265-a4228f0944f8.png)
there is some file.
i can't remenber others

**Comment by ylyhlh** [comment]
some dirty change...:

in file paddle/fluid/trainer_desc.py
`from proto import trainer_desc_pb2`
change this to `from .proto import trainer_desc_pb2`

in file 
paddle/fluid/proto/trainer_desc_pb2.py
`import data_feed_pb2 as data__feed__pb2`
change this to `from . import data_feed_pb2 as data__feed__pb2`

**Comment by AlessandroVol23** [comment]
That worked thanks! :)

**Comment by lzha106** [comment]
same issue when runing https://github.com/yaoxuefeng6/Paddle_baseline_KDD2019 with pip installed paddlepaddle  1.4.1.

After modify paddle/fluid/trainer_desc.py and paddle/fluid/trainer_desc.py, it has below issue:

2019-05-23 13:32:37,337-INFO: run local training
ready to epochs
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
  File "map_reader.py", line 17, in <module>
  File "map_reader.py", line 17, in <module>
  File "map_reader.py", line 17, in <module>
        import paddle.fluid.incubate.data_generator as dg
import paddle.fluid.incubate.data_generator as dg
ImportError:     No module named paddle.fluid.incubate.data_generator
import paddle.fluid.incubate.data_generator as dg
ImportErrorImportError: No module named paddle.fluid.incubate.data_generator:
No module named paddle.fluid.incubate.data_generator
Traceback (most recent call last):
  File "map_reader.py", line 17, in <module>
    import paddle.fluid.incubate.data_generator as dg
