### ISSUE TITLE
paddle在分布式上如何实现训练和验证在一起呢，主要想实现early stop

### ISSUE THREAD

**Issue by irukawang** [PaddlePaddle/Paddle#17183]
```python
    fluid.DistributeTranspiler() # 只会返回一个program （train_program）不是太清楚test_program \
如何得到。 测试如果不使用fluid.DistributeTranspiler() 是跑在0号节点嘛。跟trainer0在一起嘛。
```

**Comment by sandyhouse** [comment]
可以参考fast imagenet的实现代码，里面包括train、test和early stop。
https://github.com/PaddlePaddle/models/tree/develop/PaddleCV/image_classification/fast_imagenet

**Comment by sandyhouse** [comment]
I closed this issue. Feel free to reopen it if you have any question.

**Comment by sandyhouse** [comment]
I closed this issue. Feel free to reopen it if you have any question.
