### ISSUE TITLE
关于离线量化中calibration代码的一些疑惑

### ISSUE THREAD

**Issue by wzzju** [PaddlePaddle/Paddle#17184]
1. 关于P_sum的计算
![image](https://user-images.githubusercontent.com/17102274/56962436-22cc0b80-6b89-11e9-8f2d-bf4afa6cb6f2.png)
![image](https://user-images.githubusercontent.com/17102274/56962450-2b244680-6b89-11e9-8222-ebca2901ccc3.png)
![image](https://user-images.githubusercontent.com/17102274/56962456-30819100-6b89-11e9-91e3-0bf5c9c40ba3.png)
![image](https://user-images.githubusercontent.com/17102274/56962473-38413580-6b89-11e9-8794-3a16c206f767.png)
从上述代码来看，P_sum的值其实是预测采样时进行迭代的次数。实际上应该为activation_blob中元素的总个数，此处代码应为`P_sum = len(activation_blob.flatten())`。
2. 
下述链接处代码的一些疑惑：https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/fluid/contrib/int8_inference/utility.py#L674

![image](https://user-images.githubusercontent.com/17102274/56962854-12686080-6b8a-11e9-9227-ad7636d5f0b5.png)
根据674行代码的上下文可知min_kl_index必然大于等于starting_iter，若min_kl_index=0，则必然是因为starting_iter等于0，那么while循环条件就不会成立，最后min_kl_index=starting_iter=0。即这段if语句就算成立也是什么都没有做，请问这段代码是否是冗余的呢？

**Comment by guomingz** [comment]
i'll have a look on this issue。

**Comment by guomingz** [comment]
> 下述链接处代码的一些疑惑：https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/fluid/contrib/int8_inference/utility.py#L674
> 
> ![image](https://user-images.githubusercontent.com/17102274/56962854-12686080-6b8a-11e9-9227-ad7636d5f0b5.png)
> 根据674行代码的上下文可知min_kl_index必然大于等于starting_iter，若min_kl_index=0，则必然是因为starting_iter等于0，那么while循环条件就不会成立，最后min_kl_index=starting_iter=0。即这段if语句就算成立也是什么都没有做，请问这段代码是否是冗余的呢？



hi @wzzju 关于这段代码，  我理解是考虑[L673 pass](https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/fluid/contrib/int8_inference/utility.py#L673) case， 此时min_kl_index的确等于0，但是starting_iteration 不一定也是0， 即min_kl_index必然大于等于starting_iter并非一直成立。

**Comment by guomingz** [comment]
> 1. 关于P_sum的计算
>    ![image](https://user-images.githubusercontent.com/17102274/56962436-22cc0b80-6b89-11e9-8f2d-bf4afa6cb6f2.png)
>    ![image](https://user-images.githubusercontent.com/17102274/56962450-2b244680-6b89-11e9-8222-ebca2901ccc3.png)
>    ![image](https://user-images.githubusercontent.com/17102274/56962456-30819100-6b89-11e9-91e3-0bf5c9c40ba3.png)
>    ![image](https://user-images.githubusercontent.com/17102274/56962473-38413580-6b89-11e9-8794-3a16c206f767.png)
>    从上述代码来看，P_sum的值其实是预测采样时进行迭代的次数。实际上应该为activation_blob中元素的总个数，此处代码应为`P_sum = len(activation_blob.flatten())`。
> 
的确，这里是存在问题的，我们会提一个pr修复。

**Comment by wzzju** [comment]
> > 下述链接处代码的一些疑惑：https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/fluid/contrib/int8_inference/utility.py#L674
> > ![image](https://user-images.githubusercontent.com/17102274/56962854-12686080-6b8a-11e9-9227-ad7636d5f0b5.png)
> > 根据674行代码的上下文可知min_kl_index必然大于等于starting_iter，若min_kl_index=0，则必然是因为starting_iter等于0，那么while循环条件就不会成立，最后min_kl_index=starting_iter=0。即这段if语句就算成立也是什么都没有做，请问这段代码是否是冗余的呢？
> 
> hi @wzzju 关于这段代码， 我理解是考虑[L673 pass](https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/fluid/contrib/int8_inference/utility.py#L673) case， 此时min_kl_index的确等于0，但是starting_iteration 不一定也是0， 即min_kl_index必然大于等于starting_iter并非一直成立。

`kl_inited `在进入for循环前设为了False，所以第一个if条件在第一次执行循环体时必然成立，故min_kl_index必然在第一次执行循环体时被赋值为starting_iter。之后就算一直执行的分支为`else: pass`，那么min_kl_index也为starting_iter。其他情况下min_kl_index必然大于starting_iter。
