### ISSUE TITLE
Default CUDA driver version or configurable driver version

### ISSUE THREAD

**Issue by typhoonzero** [PaddlePaddle/Paddle#1718]
We updated cuda driver version to the latest "8.0" at : https://github.com/PaddlePaddle/Paddle/pull/1699 . Do we need to make cuda driver version configurable when building paddle binaries? Since users may need to use a previous version of cuda?

**Comment by helinwang** [comment]
I think @wangkuiyi mentioned in yesterday's IDL-US meeting that we plan to only support CUDA 8.0 (unless there is a compelling reason to support 7.5).
Actually CUDA 8.0 just need to have sufficient version GPU driver and GPU architecture. (more detail here: https://github.com/NVIDIA/nvidia-docker/wiki/CUDA)
The driver version and architecture does not seem too strict.

**Comment by helinwang** [comment]
Maybe we can keep only CUDA 8.0 for now until there is a compelling use case for supporting 7.5.
