### ISSUE TITLE
faster-rcnn自己的数据集，loss值会出现NAN

### ISSUE THREAD

**Issue by wuxiaodong1014** [PaddlePaddle/Paddle#17203]
大家好，我在运行faster-rcnn目标检测自己的数据集时，当运行到一定次数，loss值会出现NAN情况，不知道是什么原因，

- 版本、环境信息：
    1）PaddlePaddle版本：1.3
    2）GPU：    CUDA：9.0和CUDNN： 7
    4）python 3.6
现象如下所示：
2019-05-05 09:39:54.880255, iter: 1283, lr: 0.00100, 'loss': nan, 'loss_cls': nan, 'loss_bbox': 0.097, 'loss_rpn_cls': 0.004, 'loss_rpn_bbox': 0.015, time: 0.627
/usr/local/lib/python3.6/dist-packages/numpy/lib/function_base.py:3405: RuntimeWarning: Invalid value encountered in median
  r = func(a, **kwargs)
2019-05-05 09:39:55.511381, iter: 1284, lr: 0.00100, 'loss': nan, 'loss_cls': nan, 'loss_bbox': 0.097, 'loss_rpn_cls': 0.004, 'loss_rpn_bbox': 0.015, time: 0.615
2019-05-05 09:39:56.129382, iter: 1285, lr: 0.00100, 'loss': nan, 'loss_cls': nan, 'loss_bbox': 0.106, 'loss_rpn_cls': 0.004, 'loss_rpn_bbox': 0.015, time: 0.631

**Comment by jerrywgz** [comment]
请问你是用八卡训练的吗

**Comment by edencfc** [comment]
我也遇到同样的情况，调低初始学习率就正常了

**Comment by jerrywgz** [comment]
请问你是八卡训练吗，https://github.com/PaddlePaddle/models/blob/develop/PaddleCV/PaddleDetection/docs/GETTING_STARTED_cn.md#faq 如果不是八卡的话需要相应调整学习率，可以参考这里

**Comment by wchange** [comment]
> 请问你是八卡训练吗，https://github.com/PaddlePaddle/models/blob/develop/PaddleCV/PaddleDetection/docs/GETTING_STARTED_cn.md#faq 如果不是八卡的话需要相应调整学习率，可以参考这里

我是8卡训练，同样遇到nan的情况，学习率设置为0.001，在72543轮的时候出现nan，使用的数据集是https://challenge.xviewdataset.org/data-explore

**Comment by jerrywgz** [comment]
nan是稳定复现的吗，可以尝试将warmup factor调至0.1，steps调到1000或2000

**Comment by jerrywgz** [comment]
另外学习率是0.01的话很快就会nan吗？

**Comment by wchange** [comment]
> nan是稳定复现的吗，可以尝试将warmup factor调至0.1，steps调到1000或2000

> 另外学习率是0.01的话很快就会nan吗？

稳定复现，0.01的话15000+轮就出现nan，我试下这俩参数，需要从头训练吗，还是可以load最近的checkpoint

**Comment by jerrywgz** [comment]
最好从头训练，另外可以把每轮的数据保存下，看下是不是非法数据导致的

**Comment by wchange** [comment]
> 另外可以把每轮的数据保存下，看下是不是非法数据导致的

这个具体如何操作？不是说每轮都保存一次模型吧？

**Comment by jerrywgz** [comment]
https://github.com/PaddlePaddle/PaddleDetection/blob/master/ppdet/modeling/architectures/faster_rcnn.py#L138 可以在这里加入{‘gt_box’: feed_vars['gt_box']}这样，然后在train.py中每次exe.run得到的结果中就有gt_box的值了

**Comment by wchange** [comment]
我用的是https://github.com/PaddlePaddle/models/tree/develop/PaddleCV/rcnn这份代码，能麻烦告知一下对应修改的地方吗

**Comment by jerrywgz** [comment]
可以在https://github.com/PaddlePaddle/models/blob/develop/PaddleCV/rcnn/models/model_builder.py#L65 这里返回self.gt_box 然后https://github.com/PaddlePaddle/models/blob/develop/PaddleCV/rcnn/train.py#L103 这里将返回值加入fetch_list中。 https://github.com/PaddlePaddle/models/blob/develop/PaddleCV/rcnn/train.py#L189 每次out[-1]即为gt_box的值，另外190行打印log时还需要将outs[:-1] 改为outs[:-2]以保证原始log不变

**Comment by wchange** [comment]
十分感谢，我试一下

**Comment by wchange** [comment]
还有个问题请教一下，这份代码里面没有看到steps这个参数，只有一个lr_steps，不知道是否对应steps参数？

**Comment by jerrywgz** [comment]
https://github.com/PaddlePaddle/models/blob/develop/PaddleCV/rcnn/train.py#L96 是这两个参数

**Comment by wchange** [comment]
好的，多谢

**Comment by wchange** [comment]
https://github.com/PaddlePaddle/models/blob/develop/PaddleCV/rcnn/models/model_builder.py#L65，这里改成了：
`return rloss, rkeys, self.gt_box`
https://github.com/PaddlePaddle/models/blob/develop/PaddleCV/rcnn/train.py#L83，这里改成了：
`losses, keys, gt_box = model.loss()`
https://github.com/PaddlePaddle/models/blob/develop/PaddleCV/rcnn/train.py#L103，这里改成了：
`fetch_list = fetch_list + [lr, gt_box]`
然后在https://github.com/PaddlePaddle/models/blob/develop/PaddleCV/rcnn/train.py#L189，这里报错：
RuntimeError: Some of your fetched tensors hold LoD information.             They can not be completely cast to Python ndarray.             Please set the parameter 'return_numpy' as 'False' to             return LoDTensor itself directly.
麻烦再看一下怎么修改~

**Comment by jerrywgz** [comment]
就按报错信息改，run里面加return_numpy=False

**Comment by wchange** [comment]
正常运行了，多谢
gt_box应该是ground truth的bounding box数据？那是不是构造数据的时候就可以检查是否有非法数据了？
而且我看打印出来的数据应该是把一张图里面的所有bounding bbox拼成一个1维数组了？我用的这个数据集是卫星图像的目标检测数据集，一张图比较大，而且包含目标较多，这样打在日志里面检查数据也挺费劲的。。

**Comment by jerrywgz** [comment]
那你这边可以手动过滤一遍数据吗？1. 过滤没有框的样本 2. 过滤有框，但是所有的框is_crowd都为True的样本 
之所以想这样看gt_box，是检查是不是每次挂的时候都是同一张图片导致的，如果数量多，可以打印im_id

**Comment by wchange** [comment]
了解了，我手动check一下是否存在上述情况

**Comment by wchange** [comment]
check完可以确认所有train image都含有至少1个框，is_crowd是构造数据的时候就全设为0了，所以上述1，2两种情况应该是都没有。。

**Comment by jerrywgz** [comment]
那就再check下是不是每次出nan的时候对应的im_id是相同的，另外学习率可以再做下修改训练尝试下

**Comment by wchange** [comment]
跑了2遍，报nan的轮次不一致了，而且报错轮次里面没有出现相同im_id的图片，麻烦问下还有其他的排查手段吗

**Comment by jerrywgz** [comment]
可以将log_window设置为1，然后观察loss为nan前的变化，是逐渐变nan还是突然nan，如果是突然nan的话可以排查下是那个地方最先开始出现异常的，可以将中间层的输出fetch出来观察下。如果是逐渐nan的话可能和模型训练参数有关，首先看还可以调整哪些超参，还可以尝试使用我们训练好的模型做finetune

**Comment by wchange** [comment]
按照https://github.com/PaddlePaddle/models/blob/develop/PaddleCV/rcnn/train.py#L186 的写法，log_window这个参数生效了吗？我设置成1以后感觉和之前的日志也没有什么太大的变化，应该都是每轮都打印的吧
之前的实验结果都是上一轮无异常，下一轮loss_bbox, loss, loss_cls都为nan了

**Comment by jerrywgz** [comment]
log_window决定了显示loss的平滑程度，设置为1相当于不做平滑
想问下你的数据集类别数是多少呢，你所设置的类别数包含背景类了吗

**Comment by wchange** [comment]
类别数62，没包含背景类，需要设置成63吗

**Comment by jerrywgz** [comment]
是的，需要包含背景类

**Comment by wchange** [comment]
赞，跑了一个周末没有出现nan问题，应该是解决了，多谢
