### ISSUE TITLE
有其他进程占用部分gpu显存时，预测时显示显存不足导致无法预测

### ISSUE THREAD

**Issue by littlepan0413** [PaddlePaddle/Paddle#17208]
1、仅前向推导过程，模型大小大概是2.4G
2、空卡上使用FLAGS_fraction_of_gpu_memory_to_use=0.3可训练
3、gpu单卡显存11.4GB，已使用进程5787MB，剩余大约50%，使用FLAGS_fraction_of_gpu_memory_to_use=0.33无法训练，报错exception caught, parallel_for failed: out of memory

**显卡信息**
+-------------------------------+----------------------+----------------------+
|   3   xxx          On   | 00000000:00:0A.0 Off |                    0 |
| N/A   47C    P0    70W / 235W |   5800MiB / 11439MiB |     47%      Default |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    3     26175      C   python                                      5787MiB |
+-----------------------------------------------------------------------------+

**运行报错信息**
CUDA_VISIBLE_DEVICES=3 FLAGS_fraction_of_gpu_memory_to_use=0.3 python xxx.py
------------------------------------------------
W0505 19:15:12.944301 21279 device_context.cc:263] Please NOTE: device: 0, CUDA Capability: 35, Driver API Version: 9.0, Runtime API Version: 9.0
W0505 19:15:12.944494 21279 device_context.cc:271] device: 0, cuDNN Version: 7.0.
W0505 19:15:12.944511 21279 device_context.cc:295] WARNING: device: 0. The installed Paddle is compiled with CUDNN 7.3, but CUDNN version in your machine is 7.0, which may cause serious incompatible bug. Please recompile or reinstall Paddle with compatible CUDNN version.
Load pretraining parameters from xxxx
W0505 19:15:18.893642 21711 system_allocator.cc:122] Cannot malloc 3260.36 MB GPU memory. Please shrink FLAGS_fraction_of_gpu_memory_to_use environment variable to a lower value. Current value is 0.3
W0505 19:15:18.894001 21711 legacy_allocator.cc:191] Cannot allocate 10.253906MB in GPU 0, available 2.153076GB
W0505 19:15:18.894024 21711 legacy_allocator.cc:194] total 11995578368
W0505 19:15:18.894040 21711 legacy_allocator.cc:195] GpuMinChunkSize 256.000000B
W0505 19:15:18.894058 21711 legacy_allocator.cc:198] GpuMaxChunkSize 3.183950GB
W0505 19:15:18.894074 21711 legacy_allocator.cc:201] GPU memory used: 3.176743GB
W0505 19:15:19.322134 21710 system_allocator.cc:122] Cannot malloc 3260.36 MB GPU memory. Please shrink FLAGS_fraction_of_gpu_memory_to_use environment variable to a lower value. Current value is 0.3
W0505 19:15:19.322496 21710 legacy_allocator.cc:191] Cannot allocate 41.015625MB in GPU 0, available 2.153076GB
W0505 19:15:19.322520 21710 legacy_allocator.cc:194] total 11995578368
W0505 19:15:19.322536 21710 legacy_allocator.cc:195] GpuMinChunkSize 256.000000B
W0505 19:15:19.322549 21710 legacy_allocator.cc:198] GpuMaxChunkSize 3.183950GB
W0505 19:15:19.322567 21710 legacy_allocator.cc:201] GPU memory used: 3.176783GB
W0505 19:15:19.352350 21709 system_allocator.cc:122] Cannot malloc 3260.36 MB GPU memory. Please shrink FLAGS_fraction_of_gpu_memory_to_use environment variable to a lower value. Current value is 0.3
W0505 19:15:19.352682 21709 legacy_allocator.cc:191] Cannot allocate 41.015625MB in GPU 0, available 2.153076GB
W0505 19:15:19.352705 21709 legacy_allocator.cc:194] total 11995578368
W0505 19:15:19.352721 21709 legacy_allocator.cc:195] GpuMinChunkSize 256.000000B
W0505 19:15:19.352735 21709 legacy_allocator.cc:198] GpuMaxChunkSize 3.183950GB
W0505 19:15:19.352751 21709 legacy_allocator.cc:201] GPU memory used: 3.176783GB
F0505 19:15:19.356230 21709 exception_holder.h:34] std::exception caught, parallel_for failed: out of memory
*** Check failure stack trace: ***
    @     0x7ffa5e29331d  google::LogMessage::Fail()
    @     0x7ffa5e296dcc  google::LogMessage::SendToLog()
    @     0x7ffa5e292e43  google::LogMessage::Flush()
    @     0x7ffa5e2982de  google::LogMessageFatal::~LogMessageFatal()
    @     0x7ffa5f9cc67c  paddle::framework::details::ExceptionHolder::Catch()
    @     0x7ffa5f9cf46d  _ZZN6paddle9framework7details24ThreadedSSAGraphExecutor5RunOpERKSt10shared_ptrINS0_13BlockingQueueIPNS1_13VarHandleBaseEEEEPNS1_12OpHandleBaseEENKUlvE_clEv
    @     0x7ffa5ed8f283  std::_Function_handler<>::_M_invoke()
    @     0x7ffa5ed525a7  std::__future_base::_State_base::_M_do_set()
    @     0x7ffaaf5d3be0  __GI___pthread_once
    @     0x7ffa5f9cdd72  _ZNSt13__future_base11_Task_stateISt5_BindIFZN6paddle9framework7details24ThreadedSSAGraphExecutor5RunOpERKSt10shared_ptrINS3_13BlockingQueueIPNS4_13VarHandleBaseEEEEPNS4_12OpHandleBaseEEUlvE_vEESaIiEFvvEE6_M_runEv
    @     0x7ffa5ed539d4  _ZZN10ThreadPoolC1EmENKUlvE_clEv
    @     0x7ffa86c52678  execute_native_thread_routine_compat
    @     0x7ffaaf5cedf3  start_thread
    @     0x7ffaaebf32cd  __clone
    @              (nil)  (unknown)
已放弃

**Comment by SunGaofeng** [comment]
FLAGS_fraction_of_gpu_memory_to_use设置成0.3，是说每次需要显存的时候就分30%的显存空间，不是说最多只要用到30%的显存。如果一开始分了30%的显存，随着计算的进行，有更多变量需要空间，发现不够用了，会再分配30%的显存。
