### ISSUE TITLE
执行paddle.fluid.install_check.run_check()出错

### ISSUE THREAD

**Issue by narrowview** [PaddlePaddle/Paddle#17217]
>>> import paddle.fluid
>>> paddle.fluid.install_check.run_check()
Running Verify Fluid Program ... 
W0506 01:30:57.022621  3174 device_context.cc:261] Please NOTE: device: 0, CUDA Capability: 75, Driver API Version: 10.1, Runtime API Version: 9.0
W0506 01:30:57.024513  3174 device_context.cc:269] device: 0, cuDNN Version: 7.0.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/wenwu/.local/lib/python2.7/site-packages/paddle/fluid/install_check.py", line 65, in run_check
    fetch_list=[out.name, param_grads[1].name])
  File "/home/wenwu/.local/lib/python2.7/site-packages/paddle/fluid/executor.py", line 565, in run
    use_program_cache=use_program_cache)
  File "/home/wenwu/.local/lib/python2.7/site-packages/paddle/fluid/executor.py", line 642, in _run
    exe.run(program.desc, scope, 0, True, True, fetch_var_name)
paddle.fluid.core.EnforceNotMet: Invoke operator mul error.
Python Callstacks: 
  File "/home/wenwu/.local/lib/python2.7/site-packages/paddle/fluid/framework.py", line 1654, in append_op
    attrs=kwargs.get("attrs", None))
  File "/home/wenwu/.local/lib/python2.7/site-packages/paddle/fluid/dygraph/layer_object_helper.py", line 52, in append_op
    stop_gradient=stop_gradient)
  File "/home/wenwu/.local/lib/python2.7/site-packages/paddle/fluid/dygraph/nn.py", line 919, in forward
    "y_num_col_dims": 1
  File "/home/wenwu/.local/lib/python2.7/site-packages/paddle/fluid/dygraph/layers.py", line 158, in __call__
    outputs = self.forward(*inputs)
  File "/home/wenwu/.local/lib/python2.7/site-packages/paddle/fluid/install_check.py", line 37, in forward
    x = self._fc1(inputs)
  File "/home/wenwu/.local/lib/python2.7/site-packages/paddle/fluid/dygraph/layers.py", line 158, in __call__
    outputs = self.forward(*inputs)
  File "/home/wenwu/.local/lib/python2.7/site-packages/paddle/fluid/install_check.py", line 58, in run_check
    out = simple_layer(inp)
  File "<stdin>", line 1, in <module>
C++ Callstacks: 
CUBLAS: execution failed,  at [/paddle/paddle/fluid/operators/math/blas_impl.cu.h:34]
PaddlePaddle Call Stacks: 
0       0x7fb2f0aa1640p void paddle::platform::EnforceNotMet::Init<char const*>(char const*, char const*, int) + 352
1       0x7fb2f0aa19b9p paddle::platform::EnforceNotMet::EnforceNotMet(std::__exception_ptr::exception_ptr, char const*, int) + 137
2       0x7fb2f0d0f467p void paddle::operators::math::Blas<paddle::platform::CUDADeviceContext>::GEMM<float>(CBLAS_TRANSPOSE, CBLAS_TRANSPOSE, int, int, int, float, float const*, float const*, float, float*) const + 1815
3       0x7fb2f1189e3cp void paddle::operators::math::Blas<paddle::platform::CUDADeviceContext>::MatMul<float>(paddle::framework::Tensor const&, bool, paddle::framework::Tensor const&, bool, float, paddle::framework::Tensor*, float) const + 844
4       0x7fb2f118a276p paddle::operators::MulKernel<paddle::platform::CUDADeviceContext, float>::Compute(paddle::framework::ExecutionContext const&) const + 662
5       0x7fb2f118a463p std::_Function_handler<void (paddle::framework::ExecutionContext const&), paddle::framework::OpKernelRegistrarFunctor<paddle::platform::CUDAPlace, false, 0ul, paddle::operators::MulKernel<paddle::platform::CUDADeviceContext, float>, paddle::operators::MulKernel<paddle::platform::CUDADeviceContext, double>, paddle::operators::MulKernel<paddle::platform::CUDADeviceContext, paddle::platform::float16> >::operator()(char const*, char const*, int) const::{lambda(paddle::framework::ExecutionContext const&)#1}>::_M_invoke(std::_Any_data const&, paddle::framework::ExecutionContext const&) + 35
6       0x7fb2f27336f6p paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&, paddle::framework::RuntimeContext*) const + 662
7       0x7fb2f2733e64p paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&) const + 292
8       0x7fb2f273178cp paddle::framework::OperatorBase::Run(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&) + 332
9       0x7fb2f0c168bep paddle::framework::Executor::RunPreparedContext(paddle::framework::ExecutorPrepareContext*, paddle::framework::Scope*, bool, bool, bool) + 382
10      0x7fb2f0c176ffp paddle::framework::Executor::Run(paddle::framework::ProgramDesc const&, paddle::framework::Scope*, int, bool, bool, std::vector<std::string, std::allocator<std::string> > const&, bool) + 143
11      0x7fb2f0a9135ep
12      0x7fb2f0ad472ep
13            0x4c5326p PyEval_EvalFrameEx + 37958
14            0x4b9b66p PyEval_EvalCodeEx + 774
15            0x4c1f56p PyEval_EvalFrameEx + 24694
16            0x4b9b66p PyEval_EvalCodeEx + 774
17            0x4c17c6p PyEval_EvalFrameEx + 22758
18            0x4c141fp PyEval_EvalFrameEx + 21823
19            0x4b9b66p PyEval_EvalCodeEx + 774
20            0x4eb69fp
21            0x44a7c2p PyRun_InteractiveOneFlags + 400
22            0x44a58dp PyRun_InteractiveLoopFlags + 186
23            0x430b76p
24            0x4938cep Py_Main + 1358
25      0x7fb32e0d7830p __libc_start_main + 240
26            0x493299p _start + 41

>>>

**Comment by chengduoZH** [comment]
@narrowview 你装的是什么版本的Paddle?

**Comment by narrowview** [comment]
> @narrowview 你装的是什么版本的Paddle?

用pip install paddlepaddle-gpu装的， ubuntu下python2.7  cuda 9.0 cudnn 7.0

**Comment by chengduoZH** [comment]
@narrowview 
你可以换一台机器试一下吗？我这边没能复现你的问题
```
In [1]: import paddle.fluid

In [2]: paddle.fluid.install_check.run_check()
Running Verify Fluid Program ...
W0511 23:02:20.682183 24883 device_context.cc:261] Please NOTE: device: 0, CUDA Capability: 70, Driver API Version: 10.0, Runtime API Version: 9.0
W0511 23:02:20.692134 24883 device_context.cc:269] device: 0, cuDNN Version: 7.0.
W0511 23:02:20.692178 24883 device_context.cc:293] WARNING: device: 0. The installed Paddle is compiled with CUDNN 7.3, but CUDNN version in your machine is 7.1, which may cause serious incompatible bug. Please recompile or reinstall Paddle with compatible CUDNN version.
Your Paddle Fluid is installed successfully! Let's start deep Learning with Paddle Fluid now

In [3]: paddle.__version__
Out[3]: '1.4.1'
```

**Comment by MrRace** [comment]
同样遇到这个问题。Ubuntu环境，Python3.5,Cuda=9,CuDNN=7。`pip3 install paddlepaddle-gpu`方式安装。
```
import paddle.fluid
paddle.fluid.install_check.run_check()`
```
报错：
```
Running Verify Fluid Program ... 
W0515 14:12:12.377182  6682 device_context.cc:261] Please NOTE: device: 0, CUDA Capability: 75, Driver API Version: 10.0, Runtime API Version: 9.0
W0515 14:12:12.379117  6682 device_context.cc:269] device: 0, cuDNN Version: 7.0.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/lab/liujiepeng/KGProject/information-extraction/info_extrac_env_py35/lib/python3.5/site-packages/paddle/fluid/install_check.py", line 65, in run_check
    fetch_list=[out.name, param_grads[1].name])
  File "/home/lab/liujiepeng/KGProject/information-extraction/info_extrac_env_py35/lib/python3.5/site-packages/paddle/fluid/executor.py", line 565, in run
    use_program_cache=use_program_cache)
  File "/home/lab/liujiepeng/KGProject/information-extraction/info_extrac_env_py35/lib/python3.5/site-packages/paddle/fluid/executor.py", line 642, in _run
    exe.run(program.desc, scope, 0, True, True, fetch_var_name)
paddle.fluid.core.EnforceNotMet: Invoke operator mul error.
```

**Comment by chengduoZH** [comment]
@MrRace 完整的报错信息是什么？

**Comment by MrRace** [comment]
> @MrRace 完整的报错信息是什么？

Running Verify Fluid Program ... 
W0515 14:12:12.377182  6682 device_context.cc:261] Please NOTE: device: 0, CUDA Capability: 75, Driver API Version: 10.0, Runtime API Version: 9.0
W0515 14:12:12.379117  6682 device_context.cc:269] device: 0, cuDNN Version: 7.0.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/lab/liujiepeng/KGProject/information-extraction/info_extrac_env_py35/lib/python3.5/site-packages/paddle/fluid/install_check.py", line 65, in run_check
    fetch_list=[out.name, param_grads[1].name])
  File "/home/lab/liujiepeng/KGProject/information-extraction/info_extrac_env_py35/lib/python3.5/site-packages/paddle/fluid/executor.py", line 565, in run
    use_program_cache=use_program_cache)
  File "/home/lab/liujiepeng/KGProject/information-extraction/info_extrac_env_py35/lib/python3.5/site-packages/paddle/fluid/executor.py", line 642, in _run
    exe.run(program.desc, scope, 0, True, True, fetch_var_name)
paddle.fluid.core.EnforceNotMet: Invoke operator mul error.

**Comment by Knightsll** [comment]
我出现的问题也是这个，请问找到了解决方法吗，我的显卡是RTX2080Ti
