### ISSUE TITLE
在paddlecloud上跑模型预测报grpc error

### ISSUE THREAD

**Issue by MaxLingwei** [PaddlePaddle/Paddle#17219]
PaddlePaddle版本：v1.3.0, fluid
在mpi集群上测试了单机和多机（50个节点）均出现同样的错误，代码在本地开发机可以正常运行。

**Comment by jiaqianjing** [comment]
++ /home/disk1/task_data/history/20190506/0.app-user-20190506101929-9084--train_text_cnn_lilingwei_paddlecloud/logs/workspace/python27-gcc482//bin/python validate_text_cnn.py
F0506 10:26:01.296134 15850 grpc_client.cc:418] PrefetchRPC name:[embedding_0.tmp_0@10.74.195.26:62004], ep:[10.74.195.26:62004], status:[-1] meets grpc error, error_code:14 error_message:OS Error error_details:
*** Check failure stack trace: ***
    @     0x7fef5b5f0c0d  google::LogMessage::Fail()
    @     0x7fef5b5f46bc  google::LogMessage::SendToLog()
    @     0x7fef5b5f0733  google::LogMessage::Flush()
    @     0x7fef5b5f5bce  google::LogMessageFatal::~LogMessageFatal()
    @     0x7fef5c0f830a  paddle::operators::distributed::GRPCClient::Proceed()
    @     0x7fef674c6560  execute_native_thread_routine
    @     0x7fefc5d3a1c1  start_thread
    @     0x7fefc53620ad  __clone
    @              (nil)  (unknown)
load model successfully
batch 0
.//paddle/start_trainer.sh: line 109: 15808 Aborted                 (core dumped) /home/disk1/task_data/history/20190506/0.app-user-20190506101929-9084--train_text_cnn_lilingwei_paddlecloud/logs/workspace/python27-gcc482//bin/python validate_text_cnn.py

**Comment by seiriosPlus** [comment]
Hi上联系， 后续我会把问题和结论贴出

**Comment by seiriosPlus** [comment]
same as #15224
