### ISSUE TITLE
ERNIE fine-tuning后做预测时, 配置文件ernie_config是不是应该和 fine-tuning训练时的不同?

### ISSUE THREAD

**Issue by Robets2020** [PaddlePaddle/Paddle#17220]
ERNIE的fine-tuning做预测时, 使用了和训练时相同的ernie_config, 会导致attention_probs_dropout_prob": 0.1,和"hidden_dropout_prob": 0.1. 
所以测试时应该使用单独的配置, 将attention_probs_dropout_prob和hidden_dropout_prob设置为0.
不知到我的理解对不对?

**Comment by chengduoZH** [comment]
@kuke 毅冰老师可以帮忙看一下吗？

**Comment by kuke** [comment]
https://github.com/PaddlePaddle/LARK/blob/1b54d1444bfde000efa3e71ddf04396c89fd7186/ERNIE/train.py#L198

paddle的inference/test program的声明方式已经考虑到了这个问题，`for_test=True` 会将dropout这种区分train/test的op的执行模式改成test，所以config保持不变即可。

**Comment by kuke** [comment]
https://github.com/PaddlePaddle/Paddle/blob/16922e00937525005829caef87993ed50ad071de/python/paddle/fluid/layers/nn.py#L1366-L1381

另即便是预测，也不能随意改drop_prob，可能导致错误的结果，请参考`downgrade_in_infer`这种dropout模式

**Comment by Robets2020** [comment]
@kuke 谢谢. 文档里好像没见这方面的说明( "for_test=True 会将dropout这种区分train/test的op的执行模式改成test"), 建议可以加一下说明.

**Comment by Robets2020** [comment]
@kuke 
test_prog = test_prog.clone(for_test=True) 可以理解为等同于将dropout的is_test设置为True吗?
dropout_implementation="upscale_in_train" 是不是(除了dropout_prob和keep_prob的差别)等同与tensorflow中的dropout?

**Comment by kuke** [comment]
@roberts-sh 对的，文档我们会完善一下
