### ISSUE TITLE
Paddle训练报错

### ISSUE THREAD

**Issue by shejay2017** [PaddlePaddle/Paddle#1722]
root@9363fa112004:/home/code/demo/semantic_role_labeling# bash ./train.sh
I0329 07:03:13.008100    75 Util.cpp:155] commandline: /usr/local/bin/../opt/paddle/bin/paddle_trainer --config=./db_lstm.py --use_gpu=false --log_period=5000 --trainer_count=1 --show_parameter_stats_period=5000 --save_dir=./output --num_passes=10000 --average_test_period=10000000 --init_model_path=./data --load_missing_parameter_strategy=rand --test_all_data_in_one_period=1 
I0329 07:03:13.008280    75 Util.cpp:130] Calling runInitFunctions
I0329 07:03:13.008620    75 Util.cpp:143] Call runInitFunctions done.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/paddle/trainer/config_parser.py", line 3406, in parse_config_and_serialize
    config = parse_config(config_file, config_arg_str)
  File "/usr/local/lib/python2.7/dist-packages/paddle/trainer/config_parser.py", line 3382, in parse_config
    execfile(config_file, make_config_environment(config_file, config_args))
  File "./db_lstm.py", line 90, in <module>
    average_window=0.5, max_average_window=10000), )
  File "/usr/local/lib/python2.7/dist-packages/paddle/trainer_config_helpers/default_decorators.py", line 53, in __wrapper__
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/paddle/trainer_config_helpers/default_decorators.py", line 53, in __wrapper__
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/paddle/trainer_config_helpers/optimizers.py", line 441, in settings
    kwargs = __extends__(kwargs, each.to_setting_kwargs())
  File "/usr/local/lib/python2.7/dist-packages/paddle/trainer_config_helpers/optimizers.py", line 349, in __extends__
    assert key not in dict1
AssertionError
F0329 07:03:13.136715    75 PythonUtil.cpp:134] Check failed: (ret) != nullptr Current PYTHONPATH: ['/usr/local/opt/paddle/bin', '/home/code/demo/semantic_role_labeling', '/usr/lib/python2.7', '/usr/lib/python2.7/plat-x86_64-linux-gnu', '/usr/lib/python2.7/lib-tk', '/usr/lib/python2.7/lib-old', '/usr/lib/python2.7/lib-dynload', '/usr/local/lib/python2.7/dist-packages', '/usr/lib/python2.7/dist-packages']
Python Error: <type 'exceptions.AssertionError'> : 
Python Callstack: 
            /usr/local/lib/python2.7/dist-packages/paddle/trainer/config_parser.py : 3406
            /usr/local/lib/python2.7/dist-packages/paddle/trainer/config_parser.py : 3382
            ./db_lstm.py : 90
            /usr/local/lib/python2.7/dist-packages/paddle/trainer_config_helpers/default_decorators.py : 53
            /usr/local/lib/python2.7/dist-packages/paddle/trainer_config_helpers/default_decorators.py : 53
            /usr/local/lib/python2.7/dist-packages/paddle/trainer_config_helpers/optimizers.py : 441
            /usr/local/lib/python2.7/dist-packages/paddle/trainer_config_helpers/optimizers.py : 349
Call Object failed.
*** Check failure stack trace: ***
    @     0x7f79eb5a4daa  (unknown)
    @     0x7f79eb5a4ce4  (unknown)
    @     0x7f79eb5a46e6  (unknown)
    @     0x7f79eb5a7687  (unknown)
    @           0x76814a  paddle::callPythonFuncRetPyObj()
    @           0x76832c  paddle::callPythonFunc()
    @           0x684ef3  paddle::TrainerConfigHelper::TrainerConfigHelper()
    @           0x685534  paddle::TrainerConfigHelper::createFromFlags()
    @           0x513207  main
    @     0x7f79ea7b0f45  (unknown)
    @           0x51f2a5  (unknown)
    @              (nil)  (unknown)
/usr/local/bin/paddle: line 109:    75 Aborted                 (core dumped) ${DEBUGGER} $MYDIR/../opt/paddle/bin/paddle_trainer ${@:2}

**Comment by helinwang** [comment]
请问您用的是哪个一个branch？如果是develop的话，请尝试直接运行这个https://github.com/PaddlePaddle/Paddle/blob/develop/demo/semantic_role_labeling/api_train_v2.py (`python api_train_v2.py`)

您运行的`train.sh`属于旧版api的示例程序。

**Comment by shejay2017** [comment]
已经解决了的，谢谢
