### ISSUE TITLE
TITAN V显卡 hl_gpu_apply_unary_op failed. CUDA error: no kernel image is available for execution on the device

### ISSUE THREAD

**Issue by simpv** [PaddlePaddle/Paddle#17222]
cuda 版本： 9.2  
显卡类型： TITAN V 
手动编译的paddle 0.10.0版本，安装也成功了
在GTX1080显卡的机器上（cuda10）可以运行
但是在TITAN V显卡的机器上，CPU可以运行。使用GPU运行的时候就报错了
错误信息如下：

I0506 03:23:19.720924   156 Util.cpp:166] commandline:  --use_gpu=True --trainer_count=1 
[INFO 2019-05-06 03:23:21,325 networks.py:1482] The input order is [x, y]
[INFO 2019-05-06 03:23:21,326 networks.py:1488] The output order is [__mse_cost_0__]
[INFO 2019-05-06 03:23:21,327 networks.py:1482] The input order is [x, y]
[INFO 2019-05-06 03:23:21,327 networks.py:1488] The output order is [__mse_cost_0__]
F0506 03:23:21.328544   156 hl_gpu_matrix_kernel.cuh:181] Check failed: cudaSuccess == err (0 vs. 48) [hl_gpu_apply_unary_op failed] CUDA error: no kernel image is available for execution on the device
*** Check failure stack trace: ***
    @     0x7f2191b1d19d  google::LogMessage::Fail()
    @     0x7f2191b1f7b4  google::LogMessage::SendToLog()
    @     0x7f2191b1cc1b  google::LogMessage::Flush()
    @     0x7f2191b2053e  google::LogMessageFatal::~LogMessageFatal()
    @     0x7f2191962f32  hl_gpu_apply_unary_op<>()
    @     0x7f219196342f  paddle::BaseMatrixT<>::applyUnary<>()
    @     0x7f21919636f8  paddle::BaseMatrixT<>::zero()
    @     0x7f2191700db8  paddle::Parameter::enableType()
    @     0x7f21916f9f61  paddle::parameterInitNN()
    @     0x7f21916fd4cb  paddle::NeuralNetwork::init()
    @     0x7f21916f85c1  paddle::GradientMachine::create()
    @     0x7f2191af2624  GradientMachine::createFromPaddleModelPtr()
    @     0x7f2191af3199  GradientMachine::createByConfigProtoStr()
    @     0x7f21916bb24d  _wrap_GradientMachine_createByConfigProtoStr
    @           0x4c2e1e  PyEval_EvalFrameEx
    @           0x4b9b66  PyEval_EvalCodeEx
    @           0x4c1f56  PyEval_EvalFrameEx
    @           0x4b9b66  PyEval_EvalCodeEx
    @           0x4c17c6  PyEval_EvalFrameEx
    @           0x4b9b66  PyEval_EvalCodeEx
    @           0x4d57a3  (unknown)
    @           0x4eef5e  (unknown)
    @           0x4eeb66  (unknown)
    @           0x4aaafb  (unknown)
    @           0x4c166d  PyEval_EvalFrameEx
    @           0x4b9b66  PyEval_EvalCodeEx
    @           0x4c1f56  PyEval_EvalFrameEx
    @           0x4b9b66  PyEval_EvalCodeEx
    @           0x4eb69f  (unknown)
    @           0x4e58f2  PyRun_FileExFlags
    @           0x4e41a6  PyRun_SimpleFileExFlags
    @           0x4938ce  Py_Main
Aborted (core dumped)

请问这是什么问题呢

**Comment by chengduoZH** [comment]
@simpv 从错误上看可能是您在编译的时候指定的CUDA_ARCH有问题.
另外，看到您使用是较早之前的Paddle的，这个版本的Paddle已经停止维护，建议您使用PaddleFluid.

**Comment by simpv** [comment]
@chengduoZH 嗯，我在flags.make中加了sm70就可以了。谢谢
不同显卡,要使用不同的ARCH参数，详见http://arnon.dk/matching-sm-architectures-arch-and-gencode-for-various-nvidia-cards/
早期的paddle版本，一些新显卡没有默认添加这些架构参数。不过好像是可以通过cmake 时传入 -DCUDA_ARCH_NAME=Auto 参数自动识别

**Comment by chengduoZH** [comment]
> 不过好像是可以通过cmake 时传入 -DCUDA_ARCH_NAME=Auto 参数自动识别

是的

**Comment by YeFeiyangx** [comment]
> @chengduoZH 嗯，我在flags.make中加了sm70就可以了。谢谢
> 不同显卡,要使用不同的ARCH参数，详见http://arnon.dk/matching-sm-architectures-arch-and-gencode-for-various-nvidia-cards/
> 早期的paddle版本，一些新显卡没有默认添加这些架构参数。不过好像是可以通过cmake 时传入 -DCUDA_ARCH_NAME=Auto 参数自动识别

请问如何在 flags.make中加参数，我目前用的是3080但是cuda版本是9
