### ISSUE TITLE
请判断下 持久化未训练的模型的方式是否无任何问题

### ISSUE THREAD

**Issue by ifkite** [PaddlePaddle/Paddle#17238]
麻烦 同学判断下  
1. 我用于 保存未训练的模型的方式（调用 save_inference_model） 是否是正确的？ 
2. 是否兼容 paddle v1.2.0 和 v1.3.0，关于第2个问题，如果你这边也不确定的话我去试就好。

- 版本、环境信息：
    1）PaddlePaddle版本：1.4.1
    2）CPU：请提供CPU型号，Intel Core i5
    3）GPU：无
    4）系统环境：例如Mac OS 10.13.6 ，Python2.7
- 模型信息
    1）模型名称 ，无 2）使用数据集，无 3）使用算法名称，无 4）模型链接，无
- 复现信息：
执行问题描述的代码
- 问题描述：

完整代码见 http://wiki.baidu.com/download/attachments/746290827/paddle_save_model.py?version=1&modificationDate=1557132545225&api=v2
```python
data = fluid.layers.data(name="words", shape=[1], dtype="int64", lod_level=1)
label = fluid.layers.data(name="label", shape=[1], dtype="int64")  
_, _, model = convolution_net(data, label, 100)  

save_path = 'infer_model'  
name = 'input_name'  

place = fluid.CPUPlace()  
exe = fluid.Executor(place)  
exe.run(fluid.default_startup_program())  

fluid.io.save_inference_model(save_path, feeded_var_names=[data.name], target_vars=[model], executor=exe)  
```

**Comment by chengduoZH** [comment]
@ifkite 你是又遇到什么问题吗？

**Comment by ifkite** [comment]
没遇到问题，想请同学确认下 我保存未训练模型的方式 是正确的。

**Comment by chengduoZH** [comment]
看这个是没有问题的，这里有相关的文档：http://paddlepaddle.org/documentation/docs/zh/1.4/api_cn/io_cn.html#save-inference-model
