### ISSUE TITLE
image_resize 执行报错

### ISSUE THREAD

**Issue by drmfsls** [PaddlePaddle/Paddle#17248]
warnings未定义，报错信息如下： 
 File "/usr/local/lib/python2.7/dist-packages/paddle/fluid/layers/nn.py", line 7202, in image_resize
    warnings.warn("out_shape as Variable type is deprecated, \
NameError: global name 'warnings' is not defined

**Comment by luotao1** [comment]
请问是执行什么代码出错了呢？

**Comment by drmfsls** [comment]
![image](https://user-images.githubusercontent.com/8296333/57272252-81cbdc00-70c5-11e9-8ac7-6c7ebed08279.png)
应该是走到这个分支了，然后nn.py里面warnings未定义

**Comment by luotao1** [comment]
可以先在nn.py开头加一个`import warnings`，我们会进行修复。感谢！
