### ISSUE TITLE
Remove old api demo

### ISSUE THREAD

**Issue by helinwang** [PaddlePaddle/Paddle#1725]
Since we are only going to support new API moving forward. The old API demo may no longer work or cause confusion.
For example I think this issue is caused by old API demo still in the repo: https://github.com/PaddlePaddle/Paddle/issues/1722

**Comment by luotao1** [comment]
因为新版api还未能实现所有旧版api的功能，比如beam search等，所以能否先把www.paddlepaddle.org/develop上的文档删了，demo保留一段时间以做对比。或者demo挪到其他位置？
