### ISSUE TITLE
Transpose2 (fwd+bwd) need be further optimized for CPU training

### ISSUE THREAD

**Issue by ghost** [PaddlePaddle/Paddle#17269]
Need optimize Transpose2 OP (fwd+bwd) for CPU training

**Comment by luotao1** [comment]
Close due to `mkldnn_transpose_op` have nice performance in our application.

|Op time (s) | mkl | mkldnn |
|---|---|---|
|transpose2 | 11058 | 699.797 |
|transpose2_grad | 10981.3 | 640.842 |
