### ISSUE TITLE
seqtext_printer_evaluator如何指定输出格式

### ISSUE THREAD

**Issue by pkuyym** [PaddlePaddle/Paddle#1726]
文档里面写到seqtext_printer_evaluator可以支持三种输出格式：

>  1. sequence without sub-sequence, and there is probability.
> 
>     .. code-block:: python
> 
>          id \t prob space_seperated_tokens_from_dictionary_according_to_seq
> 
>     2. sequence without sub-sequence, and there is not probability.
> 
>     .. code-block:: python
> 
>          id \t space_seperated_tokens_from_dictionary_according_to_seq
> 
>     3. sequence with sub-sequence, and there is not probability.
> 
>     .. code-block:: python
> 
>          id \t space_seperated_tokens_from_dictionary_according_to_sub_seq
>          \t \t space_seperated_tokens_from_dictionary_according_to_sub_seq
>          ...
请问如何指定输出格式，输出sub-sequence以及对应的probability？

**Comment by luotao1** [comment]
不需要指定输出格式，seqtext_printer_evaluator对双层序列和单层序列的使用是一样。

**Comment by pkuyym** [comment]
@luotao1 也就是说输出格式是自动确定的？比如说能不能强制输出概率？

**Comment by luotao1** [comment]
如果是beam search就会输出概率（即beam size>1的情况），但one-way search就不会输出概率。

**Comment by pkuyym** [comment]
好的，非常感谢
