### ISSUE TITLE
BCLOUD编译依赖后，编译报错

### ISSUE THREAD

**Issue by sshilei** [PaddlePaddle/Paddle#17290]
BCLOUD只添加了一行paddle1.41版本依赖，就会出现编译错误。 去掉这行paddle依赖就可以编译成功。

CONFIGS('baidu/paddlepaddle/paddle@v1.4.1@git_branch')

![image](https://user-images.githubusercontent.com/18701471/57371398-3a2c7980-71c5-11e9-980a-a428dfb4f35e.png)

**Comment by sshilei** [comment]
另外，有没有BCLOUD编译相关的wiki和注意事项，辛苦提供一下。

**Comment by kuke** [comment]
已内部解答
