### ISSUE TITLE
C API 预测接口怎么指定 feed_list

### ISSUE THREAD

**Issue by sshilei** [PaddlePaddle/Paddle#17299]
因为我在线执行模型仅仅是训练的一部分，我在线只需要针对1个tensor进行运算，而训练的输入是16个tensor。  有没有类似于 Executor.run 中feed参数，可以预测时指定feed。

**Comment by fc500110** [comment]
可以参考[C++预测部署API](http://paddlepaddle.org/documentation/docs/zh/1.4/advanced_usage/deploy/inference/index_cn.html)
