### ISSUE TITLE
Some question about accuracy.

### ISSUE THREAD

**Issue by Ayle3125** [PaddlePaddle/Paddle#1729]
Is there any different influence to accuracy between GPU and CPU?
How about Distributed Training?

Thanks

**Comment by hedaoyuan** [comment]
CPU and GPU hardware on the calculation accuracy is no difference.
But the CPU and GPU implementation of the same algorithm may be different, resulting in differences in the results of the calculation.
One common implementation difference is that multiple floating point numbers are summed in a different way. Such as: `sum_cpu` and `sum_gpu` may be a bit different.
```
sum_cpu = ((f1 + f2)  + f3) + f4;
sum_gpu = (f1 + f2) + (f3 + f4); 
```
Distributed computing also this problem.
