### ISSUE TITLE
AttributeError: 'module' object has no attribute 'flatten'

### ISSUE THREAD

**Issue by hyo009** [PaddlePaddle/Paddle#17307]
配置模型时，报错如下：
`Traceback (most recent call last):
  File "keras_2_fluid_all_part_map_diff_direction2_fix_multi_sum_output2.py", line 132, in <module>
    flatten1 = fluid.layers.flatten(input=fc1, axis=0, name='flatten')
AttributeError: 'module' object has no attribute 'flatten'`

文件中已import相关库：
import paddle
import paddle.fluid as fluid
import paddle.fluid.core as core
import paddle.fluid.framework as framework
from paddle.fluid.executor import Executor

**Comment by gongweibao** [comment]
版本是？

**Comment by hyo009** [comment]
paddle.__version__
'0.11.0'

**Comment by hyo009** [comment]
这个版本有flatten吗？

**Comment by gongweibao** [comment]
立即转fluid 1.4吧。
