### ISSUE TITLE
Standardize Python's import statements

### ISSUE THREAD

**Issue by wangkuiyi** [PaddlePaddle/Paddle#1730]
If we standardize import form as

```python
import paddle.v2.layer as layer
```

then we will be able to run the following scripts to present the
import-relationship between Python files in `python/paddle/v2`:

```bash
echo "digraph A {"
for i in *py; do
	for j in $(grep '^import paddle.v2' $i | sed 's/import paddle.v2.* as //'); do
		echo $j '->' $(echo $i | sed 's/\.py//') ';';
	done;
done
echo "}"
```

**Comment by typhoonzero** [comment]
Close due to low activity, please feel free to reopen it.
