### ISSUE TITLE
C API 链接失败  undefined reference to paddle::CreatePaddlePredictor

### ISSUE THREAD

**Issue by sshilei** [PaddlePaddle/Paddle#17303]
![image](https://user-images.githubusercontent.com/18701471/57432997-e45ddd00-7269-11e9-9a9f-3100774b25ff.png)

![image](https://user-images.githubusercontent.com/18701471/57433011-efb10880-7269-11e9-9d34-b32ef276e686.png)

![image](https://user-images.githubusercontent.com/18701471/57433039-03f50580-726a-11e9-8968-509836d3aade.png)

**Comment by wangguibao** [comment]
让用户改用预编译的libpaddle_fluid.so
原理：#3636

用户反馈已编译通过
