### ISSUE TITLE
模型训练正常， 预测的时候报错

### ISSUE THREAD

**Issue by sshilei** [PaddlePaddle/Paddle#17305]
我训练用的是最新的incubator版本。

预测用 incubator的infer_from_dataset()  和 fluid 1.4 的 Executor.run() 都会报错。

fluid1.4 Executor.run报错如下
![image](https://user-images.githubusercontent.com/18701471/57434845-7b2c9880-726e-11e9-8c2f-aa29026c0fb8.png)

incubator版本： infer_from_dataset报错如下：
![image](https://user-images.githubusercontent.com/18701471/57434804-62bc7e00-726e-11e9-9ded-077f5c81d068.png)

代码：
fluid 1.4版本
![image](https://user-images.githubusercontent.com/18701471/57435040-f3935980-726e-11e9-8d6b-719d183bd627.png)

incubator版本
![image](https://user-images.githubusercontent.com/18701471/57434951-b9c25300-726e-11e9-88dc-2422a304548d.png)

**Comment by xjqbest** [comment]
Executor.run报错是组网的问题，可以检查一下网络。
infer_from_dataset报错，看着你用的whl包是旧的，目前fleet有改动，这周新合入了代码，你跑的这个版本可能是fleet之前的bug。
