### ISSUE TITLE
ValueError: Parameter shape should not be related with batch-size

### ISSUE THREAD

**Issue by hyo009** [PaddlePaddle/Paddle#17311]
paddlepaddle版本：paddlepaddle-latest-cp27-cp27mu-linux_x86_64.whl
环境： centos6u4,    python2.7
报错信息如下：
`Traceback (most recent call last):
  File "keras_2_fluid_all_part_map_diff_direction2_fix_multi_sum_output2.py", line 136, in <module>
    fc2 = fluid.layers.fc(name='relu_fc2',input=concat2,size=10,act='relu',bias_attr=True)
  File "/home/map01/.jumbo/lib/python2.7/site-packages/paddle/fluid/layers/nn.py", line 318, in fc
    attr=param_attr, shape=param_shape, dtype=dtype, is_bias=False)
  File "/home/map01/.jumbo/lib/python2.7/site-packages/paddle/fluid/layer_helper_base.py", line 316, in create_parameter
    **attr._to_kwargs(with_initializer=True))
  File "/home/map01/.jumbo/lib/python2.7/site-packages/paddle/fluid/framework.py", line 1603, in create_parameter
    param = Parameter(global_block, *args, **kwargs)
  File "/home/map01/.jumbo/lib/python2.7/site-packages/paddle/fluid/framework.py", line 3344, in __init__
    raise ValueError("Parameter shape should not be related with "
ValueError: Parameter shape should not be related with batch-size`

模型报错部分结构：
MEAN_sum = fluid.layers.data(name='mean_sum', shape=[1], dtype='float32')
MEDIAN_sum = fluid.layers.data(name='median_sum', shape=[1], dtype='float32')

fc1 = fluid.layers.fc(name='relu_fc1',input=attention_output,size=30,act='relu',bias_attr=True)
flatten1 = fluid.layers.flatten(x=fc1, axis=0, name='flatten1')
concat2 = fluid.layers.concat([flatten1,MEAN_sum,MEDIAN_sum],axis=0,name='concat2')
**fc2 = fluid.layers.fc(name='relu_fc2',input=concat2,size=10,act='relu',bias_attr=True)**
final_output2 = fluid.layers.fc(name='final_output2',input=fc2,
                size=1,act=None,bias_attr=True)

在加粗部分出错，之前的结构，attention_output是变长的序列输出，通过fc1后平铺，concat两个一维特征后放入fc2。

**Comment by guoshengCS** [comment]
我这边自己试了下
```python
import paddle.fluid as fluid
MEAN_sum = fluid.layers.data(name='mean_sum', shape=[1], dtype='float32')
MEDIAN_sum = fluid.layers.data(name='median_sum', shape=[1], dtype='float32')

#fc1 = fluid.layers.fc(name='relu_fc1',input=attention_output,size=30,act='relu',bias_attr=True)
fc1 = fluid.layers.fc(name='relu_fc1',input=MEAN_sum,size=30,act='relu',bias_attr=True)
print fc1.shape
flatten1 = fluid.layers.flatten(x=fc1, axis=0, name='flatten1')
print flatten1.shape
concat2 = fluid.layers.concat([flatten1,MEAN_sum,MEDIAN_sum],axis=0,name='concat2')
print concat2.shape
fc2 = fluid.layers.fc(name='relu_fc2',input=concat2,size=10,act='relu',bias_attr=True)
final_output2 = fluid.layers.fc(name='final_output2',input=fc2,
size=1,act=None,bias_attr=True)
```
有如下输出
```text
(-1L, 30L)
(1L, -30L)
(-1L, -30L)
Traceback (most recent call last):
  File "test.py", line 12, in <module>
    fc2 = fluid.layers.fc(name='relu_fc2',input=concat2,size=10,act='relu',bias_attr=True)
  File "/home/paddle/liuyibing/python27-gcc482/lib/python2.7/site-packages/paddle/fluid/layers/nn.py", line 318, in fc
    attr=param_attr, shape=param_shape, dtype=dtype, is_bias=False)
  File "/home/paddle/liuyibing/python27-gcc482/lib/python2.7/site-packages/paddle/fluid/layer_helper_base.py", line 316, in create_parameter
    **attr._to_kwargs(with_initializer=True))
  File "/home/paddle/liuyibing/python27-gcc482/lib/python2.7/site-packages/paddle/fluid/framework.py", line 1598, in create_parameter
    param = Parameter(global_block, *args, **kwargs)
  File "/home/paddle/liuyibing/python27-gcc482/lib/python2.7/site-packages/paddle/fluid/framework.py", line 3339, in __init__
    raise ValueError("Parameter shape should not be related with "
ValueError: Parameter shape should not be related with batch-size
```
fc1.shape是(-1L, 30L)，flatten1.shape是(1L, -30L)，concat2.shape是(-1L, -30L)，然后`fc2 = fluid.layers.fc(name='relu_fc2',input=concat2,size=10,act='relu',bias_attr=True)
`的时候就会要用concat2.shape来构建weight的shape，负数（用来表示batch-size）就会报这个错。
感觉应该是这个flatten的问题，这里这个flatten1.shape是(1L, -30L)导致出现了后面的问题，这个(1L, -30L)通常表示batch_size为1，特征维度为-30，可以试下调整下fluid.layers.flatten中的axis

**Comment by guoshengCS** [comment]
试了下将flatten换成reshape后可以跑通
```python
import paddle.fluid as fluid
MEAN_sum = fluid.layers.data(name='mean_sum', shape=[1], dtype='float32')
MEDIAN_sum = fluid.layers.data(name='median_sum', shape=[1], dtype='float32')

#fc1 = fluid.layers.fc(name='relu_fc1',input=attention_output,size=30,act='relu',bias_attr=True)
fc1 = fluid.layers.fc(name='relu_fc1',input=MEAN_sum,size=30,act='relu',bias_attr=True)
print fc1.shape
#flatten1 = fluid.layers.flatten(x=fc1, axis=1, name='flatten1')
flatten1 = fluid.layers.reshape(fc1, shape=[-1,1], name='flatten1')
print flatten1.shape
concat2 = fluid.layers.concat([flatten1,MEAN_sum,MEDIAN_sum],axis=0,name='concat2')
print concat2.shape
fc2 = fluid.layers.fc(name='relu_fc2',input=concat2,size=10,act='relu',bias_attr=True)
final_output2 = fluid.layers.fc(name='final_output2',input=fc2,
size=1,act=None,bias_attr=True)
```

shape输出如下：
```txt
(-1L, 30L)
(-1L, 1L)
(-1L, 1L)
```
