### ISSUE TITLE
beam search 使用时error paddle.fluid.core.EnforceNotMet: Enforce failed. Expected in_dim == x_dim, but received in_dim:2, 3072 != x_dim:4, 3072.

### ISSUE THREAD

**Issue by sonofaeolus** [PaddlePaddle/Paddle#17328]
为使您的问题得到快速解决，在建立Issue前，请您先通过如下方式搜索是否有相似问题:【搜索issue关键字】【使用labels筛选】【官方文档】

如果您没有查询到相似问题，为快速解决您的提问，建立issue时请提供如下细节信息：
- 标题：简洁、精准描述您的问题，例如“最新预测库的API文档在哪儿 ”
- 版本、环境信息：
    1）PaddlePaddle版本：请提供您的PaddlePaddle版本号（如1.1）或CommitID
    2）CPU：预测若用CPU，请提供CPU型号，MKL/OpenBlas/MKLDNN/等数学库使用情况
    3）GPU：预测若用GPU，请提供GPU型号、CUDA和CUDNN版本号
    4）系统环境：请您描述系统类型、版本（如Mac OS 10.14），Python版本
-预测信息
    1）C++预测：请您提供预测库安装包的版本信息，及其中的version.txt文件
    2）CMake包含路径的完整命令
    3）API信息（如调用请提供）
    4）预测库来源：官网下载/特殊环境（如BCLOUD编译）
- 复现信息：如为报错，请给出复现环境、复现步骤
- 问题描述：请详细描述您的问题，同步贴出报错信息、日志/代码关键片段

Thank you for contributing to PaddlePaddle.
Before submitting the issue, you could search issue in the github in case that th
If there is no solution,please make sure that this is an inference issue including the following details :
**System information**
-PaddlePaddle version （eg.1.1）or CommitID
-CPU: including CPUMKL/OpenBlas/MKLDNN version
-GPU: including CUDA/CUDNN version
-OS Platform (eg.Mac OS 10.14)
-Python version
-Cmake orders
-C++version.txt
-API information
**To Reproduce**
Steps to reproduce the behavior
**Describe your current behavior**
**Code to reproduce the issue**
**Other info / logs**

**Comment by sonofaeolus** [comment]
问题部分代码
    cond = pd.less_than(x=counter, y=array_len)

    while_op = pd.While(cond=cond)
    with while_op.block():
        pre_ids = pd.array_read(array=ids_array, i=counter)
        pre_state = pd.array_read(array=state_array, i=counter)
        pre_score = pd.array_read(array=scores_array, i=counter)
        pre_ids_emb = pd.embedding(input=pre_ids, size=[dict_size, emb_size], dtype='float32', is_sparse=is_sparse)
        prev_proj = fluid.layers.fc(input = pre_state, size = hidden_size, bias_attr = False)
        prev_expand = fluid.layers.sequence_expand_as(x = prev_proj, y = gru_layer_proj)
        mix_prev_encoder = prev_expand + gru_layer_proj
        mix_fc = fluid.layers.fc(input = mix_prev_encoder, size = 1, bias_attr = False)
        att_weight = fluid.layers.sequence_softmax(input = mix_fc)
        weights_reshape = fluid.layers.reshape(x = att_weight, shape=[-1])
        scale_layer = fluid.layers.elementwise_mul(x = gru_layer, y = weights_reshape, axis = 0)
        contex = fluid.layers.sequence_pool(input = scale_layer, pool_type = "sum")
        pd.Print(pre_ids_emb)
        pd.Print(contex)
        #contex = pd.lod_reset(x = contex, y = pre_ids_emb)
        word_proj = fluid.layers.fc(input = [contex, pre_ids_emb], size = hidden_size * 3)
        hidden_val, r_h_val, gate_val= fluid.layers.gru_unit(input = word_proj, hidden = pre_state, size = hidden_size * 3)
        #output = fluid.layers.fc(input = hidden_val, act = "softmax", size = dict_size, bias_attr = True)
        

        # expand the recursive_sequence_lengths of pre_state to be the same with pre_score
        #pre_state_expanded = pd.sequence_expand(pre_proj, pre_score)

        current_state = hidden_val
        current_state_with_lod = pd.lod_reset(x=current_state, y=pre_score)
        # use score to do beam search
        current_score = fluid.layers.fc(input = current_state_with_lod, act = "softmax", size = dict_size, bias_attr = True)
        topk_scores, topk_indices = pd.topk(current_score, k=beam_size)
        # calculate accumulated scores after topk to reduce computation cost
        accu_scores = pd.elementwise_add(
            x=pd.log(topk_scores), y=pd.reshape(
                pre_score, shape=[-1]), axis=0)
        pd.Print(pre_score)
        pd.Print(pre_ids) 
        pd.Print(topk_indices)
        pd.Print(accu_scores)
        selected_ids, selected_scores = pd.beam_search(
            pre_ids,
            pre_score,
            topk_indices,
            accu_scores,
            beam_size,
            end_id=10,
            level= 0)

        pd.increment(x=counter, value=1, in_place=True)
        pd.Print(selected_ids)

        # update the memories
        pd.array_write(current_state, array=state_array, i=counter)
        pd.array_write(selected_ids, array=ids_array, i=counter)
        pd.array_write(selected_scores, array=scores_array, i=counter)

        # update the break condition: up to the max length or all candidates of
        # source sentences have ended.
        length_cond = pd.less_than(x=counter, y=array_len)
        finish_cond = pd.logical_not(pd.is_empty(x=selected_ids))
        pd.logical_and(x=length_cond, y=finish_cond, out=cond)

    translation_ids, translation_scores = pd.beam_search_decode(
        ids=ids_array, scores=scores_array, beam_size=beam_size, end_id=10)

    # return init_ids, init_scores

    return translation_ids, translation_scores

**Comment by sonofaeolus** [comment]
word_proj = fluid.layers.fc(input = [contex, pre_ids_emb], size = hidden_size * 3) 应该是这边 contex跟pre_ids_emb shape不同导致，但是contex 与 pre_ids_emb的lod信息不同无法使用 sequence_expand，使用lod_reset报错求问这个该怎么解决

**Comment by guoshengCS** [comment]
请问这个训练能跑通吗，看代码感觉contex是attention的结果应该是单步的，pre_ids_emb应该也是单步的，为什么shape不同呢

**Comment by sonofaeolus** [comment]
训练的时候没有beam_search 可以跑通 infer的时候不行

**Comment by guoshengCS** [comment]
请问打印出来的这两个的shape是什么样的呢
```
    pd.Print(pre_ids_emb)
    pd.Print(contex)
```

**Comment by sonofaeolus** [comment]
初始化的时候 pre_ids_emb ：2 512； contex：2 1024
第一次beam_search之后 pre_ids_emb ：4 512； contex：2 1024

**Comment by guoshengCS** [comment]
这个是说4和2不一样是吧，这个一样就能对上了是吗

**Comment by sonofaeolus** [comment]
对

**Comment by guoshengCS** [comment]
是否是`prev_expand = fluid.layers.sequence_expand_as(x = prev_proj, y = gru_layer_proj)`这个反了呢，可以试下打印下prev_proj和gru_layer_proj，将其中2的expand成4的

**Comment by sonofaeolus** [comment]
应该不是这边 prev_proj是rnn最后一步的结果+proj 而gru_layer_proj是之前rnn每一步的结果+proj 我感觉这个应该是在beam_search的时候把维度改了 我设置的beam_size = 2，batch_size = 2刚好是现在的shape

**Comment by sonofaeolus** [comment]
我这个是一个seq2seq + att

**Comment by sonofaeolus** [comment]
我这个是一个seq2seq + att

**Comment by guoshengCS** [comment]
`这个应该是在beam_search的时候把维度改了`这个是这样的，第一步到时候将batch_size根据beam_size进行了扩展，下一步的时候需要将任何用到的state（第一维会是batch_size=2）都根据pre_ids（第一维是batch_size*beam_size=4）  expand下
