### ISSUE TITLE
int8训出来的模型 测试了一下。评价基本都为0了，但是在量化训练的时候会跑验证阶段这时候的loss是正常的。

### ISSUE THREAD

**Issue by KeyKy** [PaddlePaddle/Paddle#17327]
问题是：int8量化训出来的模型 测试了一下。评价基本都为0了，但是在量化训练的时候会跑验证阶段这时候的loss是正常的。评价指标计算正确，我测了我其他的模型是正常的。
    1）PaddlePaddle版本：1.4.1
    3）GPU：CUDA9 CUDNN7.0
    4）系统环境：Centos python2.7

**Comment by WangTaoSpace** [comment]
> 问题是：int8量化训出来的模型 测试了一下。评价基本都为0了，但是在量化训练的时候会跑验证阶段这时候的loss是正常的。评价指标计算正确，我测了我其他的模型是正常的。
>    1）PaddlePaddle版本：1.4.1
>    3）GPU：CUDA9 CUDNN7.0
>    4）系统环境：Centos python2.7

请问下如何加载的量化出来的模型，我量化出来的模型是两个文件，无法加载
