### ISSUE TITLE
fluid C++预测出core

### ISSUE THREAD

**Issue by jjlucus** [PaddlePaddle/Paddle#17325]
为使您的问题得到快速解决，在建立Issue前，请您先通过如下方式搜索是否有相似问题:【搜索issue关键字】【使用labels筛选】【官方文档】

如果您没有查询到相似问题，为快速解决您的提问，建立issue时请提供如下细节信息：
- 标题：简洁、精准描述您的问题，例如“最新预测库的API文档在哪儿 ”
- 版本、环境信息：
    1）PaddlePaddle版本：fluid 1.4
    2）CPU：Intel(R) Xeon(R) CPU    E5645  @ 2.40GHz
    3）GPU：预测若用GPU，请提供GPU型号、CUDA和CUDNN版本号
    4）系统环境：CentOS release 6.3，Python2.7.10
-预测信息
    1）C++预测：fluid 1.4
    2）CMake包含路径的完整命令
    3）API信息  predictor->Run(in_data, &out_data)
    4）预测库来源：BCLOUD编译
- 复现信息：如为报错，请给出复现环境、复现步骤
- 问题描述：请详细描述您的问题，同步贴出报错信息、日志/代码关键片段

![image](https://user-images.githubusercontent.com/36889237/57498914-55f06680-7310-11e9-8267-76b7ccfa9943.png)

Thank you for contributing to PaddlePaddle.
Before submitting the issue, you could search issue in the github in case that th
If there is no solution,please make sure that this is an inference issue including the following details :
**System information**
-PaddlePaddle version （eg.1.1）or CommitID
-CPU: including CPUMKL/OpenBlas/MKLDNN version
-GPU: including CUDA/CUDNN version
-OS Platform (eg.Mac OS 10.14)
-Python version
-Cmake orders
-C++version.txt
-API information
**To Reproduce**
Steps to reproduce the behavior
**Describe your current behavior**
**Code to reproduce the issue**
**Other info / logs**

**Comment by guoshengCS** [comment]
看这个贴图里的报错应该对应了这里 https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/fluid/framework/feed_fetch_method.cc#L49
```C++
  Variable* g_fetch_value = scope.FindVar(var_name);
  PADDLE_ENFORCE_NOT_NULL(g_fetch_value, "%s is not found.", var_name);
  PADDLE_ENFORCE(g_fetch_value->IsType<FeedFetchList>(),
                 "Only %s can be invoked by GetFetchVariable",
                 typeid(FeedFetchList).name());
```
这个报错貌似是因为fetch获取的类型不正确，麻烦确认下保存的模型是否正确，可以试下python里load_inference_model是否能正确运行来判断模型是否正确
