### ISSUE TITLE
paddle.fluid.core.EnforceNotMet: Cannot get attribute height_sections by type

### ISSUE THREAD

**Issue by kangzhangqi** [PaddlePaddle/Paddle#17339]
- 问题描述：
预测程序中导入模型后运行报错。反复核对了模型文件和输入输出，找不到原因。
**重点是：模型在GPU上训练，完成训练之后拷贝到CPU机器上预测。**
预测程序很简单，如下:
![image](https://user-images.githubusercontent.com/23546538/57514450-273fb380-7343-11e9-8f55-728d899645b6.png)
- 报错日志截图：
![image](https://user-images.githubusercontent.com/23546538/57514538-4f2f1700-7343-11e9-851e-392115c16b3c.png)
- 报错日志如下
Traceback (most recent call last):
  File "predict.py", line 65, in <module>
    infer(test_reader, model_path=epoch_path)
  File "predict.py", line 44, in infer
    return_numpy = True)
  File "/home/map/kangzhangqi/paddle/paddle_release_home/python/lib/python2.7/site-packages/paddle/fluid/executor.py", line 565, in run
    use_program_cache=use_program_cache)
  File "/home/map/kangzhangqi/paddle/paddle_release_home/python/lib/python2.7/site-packages/paddle/fluid/executor.py", line 642, in _run
    exe.run(program.desc, scope, 0, True, True, fetch_var_name)
paddle.fluid.core.EnforceNotMet: Cannot get attribute height_sections by type std::vector<int, std::allocator<int> >, its type is std::vector<long, std::allocator<long> > at [/paddle/paddle/fluid/framework/attribute.h:42]
PaddlePaddle Call Stacks: 
0       0x7fed4bdb1728p void paddle::platform::EnforceNotMet::Init<std::string>(std::string, char const*, int) + 360
1       0x7fed4bdb1a77p paddle::platform::EnforceNotMet::EnforceNotMet(std::string const&, char const*, int) + 87
2       0x7fed4bfd8eb5p paddle::framework::ExtractAttribute<std::vector<int, std::allocator<int> > >::operator()(boost::variant<boost::blank, int, float, std::string, std::vector<int, std::allocator<int> >, std::vector<float, std::allocator<float> >, std::vector<std::string, std::allocator<std::string> >, bool, std::vector<bool, std::allocator<bool> >, paddle::framework::BlockDesc*, long, std::vector<paddle::framework::BlockDesc*, std::allocator<paddle::framework::BlockDesc*> >, std::vector<long, std::allocator<long> >, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_>&) const + 677
3       0x7fed4bfdd541p std::_Function_handler<void (std::unordered_map<std::string, boost::variant<boost::blank, int, float, std::string, std::vector<int, std::allocator<int> >, std::vector<float, std::allocator<float> >, std::vector<std::string, std::allocator<std::string> >, bool, std::vector<bool, std::allocator<bool> >, paddle::framework::BlockDesc*, long, std::vector<paddle::framework::BlockDesc*, std::allocator<paddle::framework::BlockDesc*> >, std::vector<long, std::allocator<long> >, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_>, std::hash<std::string>, std::equal_to<std::string>, std::allocator<std::pair<std::string const, boost::variant<boost::blank, int, float, std::string, std::vector<int, std::allocator<int> >, std::vector<float, std::allocator<float> >, std::vector<std::string, std::allocator<std::string> >, bool, std::vector<bool, std::allocator<bool> >, paddle::framework::BlockDesc*, long, std::vector<paddle::framework::BlockDesc*, std::allocator<paddle::framework::BlockDesc*> >, std::vector<long, std::allocator<long> >, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> > > >*), paddle::framework::TypedAttrChecker<std::vector<int, std::allocator<int> > > >::_M_invoke(std::_Any_data const&, std::unordered_map<std::string, boost::variant<boost::blank, int, float, std::string, std::vector<int, std::allocator<int> >, std::vector<float, std::allocator<float> >, std::vector<std::string, std::allocator<std::string> >, bool, std::vector<bool, std::allocator<bool> >, paddle::framework::BlockDesc*, long, std::vector<paddle::framework::BlockDesc*, std::allocator<paddle::framework::BlockDesc*> >, std::vector<long, std::allocator<long> >, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_>, std::hash<std::string>, std::equal_to<std::string>, std::allocator<std::pair<std::string const, boost::variant<boost::blank, int, float, std::string, std::vector<int, std::allocator<int> >, std::vector<float, std::allocator<float> >, std::vector<std::string, std::allocator<std::string> >, bool, std::vector<bool, std::allocator<bool> >, paddle::framework::BlockDesc*, long, std::vector<paddle::framework::BlockDesc*, std::allocator<paddle::framework::BlockDesc*> >, std::vector<long, std::allocator<long> >, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> > > >*) + 289
4       0x7fed4cf467f1p paddle::framework::OpRegistry::CreateOp(std::string const&, std::map<std::string, std::vector<std::string, std::allocator<std::string> >, std::less<std::string>, std::allocator<std::pair<std::string const, std::vector<std::string, std::allocator<std::string> > > > > const&, std::map<std::string, std::vector<std::string, std::allocator<std::string> >, std::less<std::string>, std::allocator<std::pair<std::string const, std::vector<std::string, std::allocator<std::string> > > > > const&, std::unordered_map<std::string, boost::variant<boost::blank, int, float, std::string, std::vector<int, std::allocator<int> >, std::vector<float, std::allocator<float> >, std::vector<std::string, std::allocator<std::string> >, bool, std::vector<bool, std::allocator<bool> >, paddle::framework::BlockDesc*, long, std::vector<paddle::framework::BlockDesc*, std::allocator<paddle::framework::BlockDesc*> >, std::vector<long, std::allocator<long> >, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_>, std::hash<std::string>, std::equal_to<std::string>, std::allocator<std::pair<std::string const, boost::variant<boost::blank, int, float, std::string, std::vector<int, std::allocator<int> >, std::vector<float, std::allocator<float> >, std::vector<std::string, std::allocator<std::string> >, bool, std::vector<bool, std::allocator<bool> >, paddle::framework::BlockDesc*, long, std::vector<paddle::framework::BlockDesc*, std::allocator<paddle::framework::BlockDesc*> >, std::vector<long, std::allocator<long> >, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> > > >) + 385
5       0x7fed4cf46956p paddle::framework::OpRegistry::CreateOp(paddle::framework::OpDesc const&) + 102
6       0x7fed4bf1b6b3p paddle::framework::Executor::Prepare(paddle::framework::ProgramDesc const&, int, std::vector<std::string, std::allocator<std::string> > const&, bool) + 227
7       0x7fed4bf1bb40p paddle::framework::Executor::Run(paddle::framework::ProgramDesc const&, paddle::framework::Scope*, int, bool, bool, std::vector<std::string, std::allocator<std::string> > const&, bool) + 112
8       0x7fed4bda1faep
9       0x7fed4bde0fcep
10      0x7fee265ddbb8p PyEval_EvalFrameEx + 25016
11      0x7fee265e10bdp PyEval_EvalCodeEx + 2061
12      0x7fee265de345p PyEval_EvalFrameEx + 26949
13      0x7fee265e10bdp PyEval_EvalCodeEx + 2061
14      0x7fee265de345p PyEval_EvalFrameEx + 26949
15      0x7fee265e10bdp PyEval_EvalCodeEx + 2061
16      0x7fee265de345p PyEval_EvalFrameEx + 26949
17      0x7fee265e10bdp PyEval_EvalCodeEx + 2061
18      0x7fee265e11f2p PyEval_EvalCode + 50
19      0x7fee26609f42p PyRun_FileExFlags + 146
20      0x7fee2660b2d9p PyRun_SimpleFileExFlags + 217
21      0x7fee2662100dp Py_Main + 3149
22      0x7fee2581ebd5p __libc_start_main + 245
23            0x4007a1p

**Comment by luotao1** [comment]
`height_sections`是分布式Op里的属性，存为预测模型后不应该有这个属性。
@kangzhangqi 可以先试下：用save_persistable来保存参数， 然后自己重新定义网络保存下来一个包含你feed和fetch_target的网络
@seiriosPlus 可以帮忙看下么？

**Comment by kangzhangqi** [comment]
> `height_sections`是分布式Op里的属性，存为预测模型后不应该有这个属性。
> @kangzhangqi 可以先试下：用save_persistable来保存参数， 然后自己重新定义网络保存下来一个包含你feed和fetch_target的网络
> @seiriosPlus 可以帮忙看下么？

对的。我是在cpu机器上训练的模型导入就没问题，我用GPU训练同样的模型导入报这个错误。也不像是paddle版本的问题。我现在在训练脚本里面是用的save_inference_model保存的模型。我先试试save_persistables。

**Comment by kangzhangqi** [comment]
@seiriosPlus 有空帮我看看这个问题，很棘手。不然以后就得抛弃GPU，在CPU重新训练。

**Comment by kangzhangqi** [comment]
这个问题是由于训练机器使用的GPU的paddle和预测机器使用CPU的paddle版本不一致导致的。已经解决。
