### ISSUE TITLE
如何实现tf.gather_nd?

### ISSUE THREAD

**Issue by luluxing3** [PaddlePaddle/Paddle#17332]
有一个输入tensor，shape= [batch, seq_len, dim] 和记录position的tensor，shape=[batch];按照position取具体seq_len的某一个时刻(切片[batch，1，dim]),最终得到输出tensor，shape=[batch, dim]
请问如何在paddle中实现？

**Comment by luluxing3** [comment]
step1: reshape input tensor,  [batch, seq_len, dim] --> [batch * seq_len, dim]
step2: change position offset, postion[i] += i*seq_len+position[i]
step3: paddle.fluid.gather(input_tensor, position)

具体代码可参考：
x = fluid.layers.range(0, batch_size, 1, 'int64') * max_seq_len
index = positions + x
index = fluid.layers.cast(index, dtype='int32')
index.stop_gradient = True
input_reshape = fluid.layers.reshape(input_tensor, shape=[-1, dim])
gather_result = fluid.layers.gather(input_reshape, index)

**Comment by banma12956** [comment]
You can also try layers.onehot in paddlepaddle. Here is a demo:

onehot = layers.one_hot(positions, dim)
onehot = layers.cast(onehot, dtype='float32')
gather_result = layers.reduce_sum(layers.elementwise_mul(onehot, input_tensor), dim=1)
