### ISSUE TITLE
INT8 mul MKLDNN kernel need be created

### ISSUE THREAD

**Issue by ghost** [PaddlePaddle/Paddle#17336]
Need create INT8 mul MKLDNN kernel.

**Comment by yihuaxu** [comment]
I will check this issue and try to implement it.

**Comment by Minghui-Intel** [comment]
This issue will be solved by PR #17834

**Comment by bingyanghuang** [comment]
@jianhang-liu PR #17834 has been merged. I think we can close this milestone.
