### ISSUE TITLE
doc_cn/build_and_install/index.html 国内间歇性无法访问

### ISSUE THREAD

**Issue by llxxxll** [PaddlePaddle/Paddle#1733]
瓶颈在 https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML  这个mathjax.js

当cdn.mathjax.org无法在国内访问时，http://www.paddlepaddle.org/doc_cn/build_and_install/index.html
无法打开。

**Comment by livc** [comment]
可以使用 mathjax.js 的国内镜像，比如 http://www.bootcdn.cn/mathjax/

**Comment by helinwang** [comment]
@livc 请问能不能发一个PR修改一下：）doc_cn用国内的镜像。

**Comment by livc** [comment]
@helinwang 好的，没问题！
