### ISSUE TITLE
How to debug shape error?

### ISSUE THREAD

**Issue by TheodoreG** [PaddlePaddle/Paddle#17340]
When I run mobilenet ssd, I got such wrong

![image](https://user-images.githubusercontent.com/13977118/57516082-94a11380-7346-11e9-97a9-238d77384905.png)

How do I debug such reshape wrong? Cause I don't know even know which variable got such error.

**Comment by tensor-tang** [comment]
Can you print the shape after each layers, or `export GLOG_v=3` to see the shape flow.

**Comment by TheodoreG** [comment]
I set export GLOG_v=3 before my running script, but nothing different happened

**Comment by tensor-tang** [comment]
Please make sure  `export GLOG_logtostderr=1 ` added

**Comment by guoshengCS** [comment]
Maybe you can use  layers.Print to print and see the shape of output of each layer.
