### ISSUE TITLE
训练好的模型，Python预测没有问题，C-API加载时CreatePaddlePredictor出core，无法加载成功

### ISSUE THREAD

**Issue by sshilei** [PaddlePaddle/Paddle#17345]
![image](https://user-images.githubusercontent.com/18701471/57570633-cd201a80-7436-11e9-8835-5ef82519d926.png)

**Comment by Superjomn** [comment]
![image](https://user-images.githubusercontent.com/328693/57571544-4f620c00-7442-11e9-9754-4c5a00dd6b64.png)

信息不足，可以提供下：

1. 错误日志。  enforce 挂了会输出对应的错误信息以及代码行号
2. 版本号
3. 看起来是在预测库外层做了封装，建议先用单测测试相应的封装接口，之后再连到服务里

**Comment by sshilei** [comment]
1. 错误日志：
2. 版本号 ：   CONFIGS("baidu/paddlepaddle/paddle@paddle_prebuilt_cpu-1-0-0-1_PD_BL@git_tag")
3. 没有进行外层封装，我是主模块直接调用的预测库API。主模块就是在init启动过程中加载模型就core，还没有设计到主模块的运行逻辑。

**Comment by Superjomn** [comment]
有错误日志吗， enforce 失败会打日志

**Comment by sshilei** [comment]
--- Running analysis [ir_graph_build_pass]
--- Running analysis [ir_analysis_pass]
--- Running IR pass [infer_clean_graph_pass]
--- Running IR pass [runtime_context_cache_pass]
--- Running IR pass [attention_lstm_fuse_pass]
--- Running IR pass [seqpool_concat_fuse_pass]
--- Running IR pass [seqconv_eltadd_relu_fuse_pass]
--- Running IR pass [fc_lstm_fuse_pass]
--- Running IR pass [mul_lstm_fuse_pass]
--- Running IR pass [fc_gru_fuse_pass]
--- Running IR pass [mul_gru_fuse_pass]
--- Running IR pass [seq_concat_fc_fuse_pass]
--- Running IR pass [fc_fuse_pass]
---  detected 1 subgraphs
--- Running IR pass [repeated_fc_relu_fuse_pass]
--- Running IR pass [squared_mat_sub_fuse_pass]
--- Running IR pass [conv_bn_fuse_pass]
--- Running IR pass [conv_eltwiseadd_bn_fuse_pass]
--- Running IR pass [is_test_pass]
--- Running analysis [ir_params_sync_among_devices_pass]
--- Running analysis [ir_graph_to_program_pass]
WARNING: Logging before InitGoogleLogging() is written to STDERR
I0513 09:37:18.611336 24287 analysis_predictor.cc:433] == optimize end ==
terminate called after throwing an instance of 'paddle::platform::EnforceNotMet'
  what():  Cannot get attribute height_sections by type std::vector<int, std::allocator<int> >, its type is std::vector<long, std::allocator<long> > at [/paddle/paddle/fluid/framework/attribute.h:42]
PaddlePaddle Call Stacks:
0             0xcf81a8p
1             0xcf88b7p
2             0xe4cfa2p
3             0xe56ee3p std::_Function_handler<void (std::unordered_map<std::string, boost::variant<boost::blank, int, float, std::string, std::vector<int, std::allocator<int> >, std::vector<float, std::allocator<float> >, std::vector<std::string, std::allocator<std::string> >, bool, std::vector<bool, std::allocator<bool> >, paddle::framework::BlockDesc*, long, std::vector<paddle::framework::BlockDesc*, std::allocator<paddle::framework::BlockDesc*> >, std::vector<long, std::allocator<long> >, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_>, std::hash<std::string>, std::equal_to<std::string>, std::allocator<std::pair<std::string const, boost::variant<boost::blank, int, float, std::string, std::vector<int, std::allocator<int> >, std::vector<float, std::allocator<float> >, std::vector<std::string, std::allocator<std::string> >, bool, std::vector<bool, std::allocator<bool> >, paddle::framework::BlockDesc*, long, std::vector<paddle::framework::BlockDesc*, std::allocator<paddle::framework::BlockDesc*> >, std::vector<long, std::allocator<long> >, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> > > >*), paddle::framework::TypedAttrChecker<std::vector<int, std::allocator<int> > > >::_M_invoke(std::_Any_data const&, std::unordered_map<std::string, boost::variant<boost::blank, int, float, std::string, std::vector<int, std::allocator<int> >, std::vector<float, std::allocator<float> >, std::vector<std::string, std::allocator<std::string> >, bool, std::vector<bool, std::allocator<bool> >, paddle::framework::BlockDesc*, long, std::vector<paddle::framework::BlockDesc*, std::allocator<paddle::framework::BlockDesc*> >, std::vector<long, std::allocator<long> >, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_>, std::hash<std::string>, std::equal_to<std::string>, std::allocator<std::pair<std::string const, boost::variant<boost::blank, int, float, std::string, std::vector<int, std::allocator<int> >, std::vector<float, std::allocator<float> >, std::vector<std::string, std::allocator<std::string> >, bool, std::vector<bool, std::allocator<bool> >, paddle::framework::BlockDesc*, long, std::vector<paddle::framework::BlockDesc*, std::allocator<paddle::framework::BlockDesc*> >, std::vector<long, std::allocator<long> >, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> > > >*) + 227
4             0xe1c371p
5             0xe1c4d6p
6             0xd0b07ep
7             0xd0b9cbp
8             0xcedc3ap
9             0xcf4fe5p
10            0xcf5457p
11            0xcf6071p
12            0x746410p
13            0x73dd9ep
14            0x87b4f7p
15      0x7f05d1ee0bd5p __libc_start_main + 245
16            0x71fd19p

**Comment by Superjomn** [comment]
你模型里面有 nce_op 吗

https://github.com/PaddlePaddle/Paddle/commit/74040cb4aad1c8390fcc080c32f0c12bee46a05b#diff-1a32c2da5e543db6809ddd612601cc32L137

发现这个 attribute  `height_sections` 的确改了格式，导致训练(版本) 和 预测库版本不一致时，训练存储的模型不兼容

确认下是有有用 NCE

**Comment by sshilei** [comment]
看了你给的链接， 没有发现有nce_op,  我补充一下模型代码如下：
现有加载失败的模型操作主要有：
（1） embedding
```
 74     output = fluid.layers.embedding(
 75         input=_input,
 76         size=[dict_dim, emb_dim],
 77         param_attr=param_config(
 78             name=layer_name,
 79             learning_rate=emb_lr),
 80         is_sparse=True)
 81     return output
```
(2) bow 
```
141     output  = pooling(input=_input, pool_type='sum')
142     output = fluid.layers.softsign(output)
```
(3)  fc
(4)  求cos_sim
```
359         cos_q_pt = fluid.layers.cos_sim(q_encode, pt_encode[0])
360         cos_q_nt = fluid.layers.cos_sim(q_encode, nt_encode[0])
```
(5) 计算loss
```
391     margin_var = const_var(input=cos_q_pt,
392                            shape=[-1, 1],
393                            value=hparams['margin'],
394                            dtype='float32')
395
396     margin_minus_qt = elem_sub(margin_var, cos_q_pt)
397     margin_minus_nt = elem_add(margin_minus_qt, cos_q_nt)
398
399     zero_var = const_var(input=margin_minus_nt,
400                          shape=[-1, 1],
401                          value=0.0,
402                          dtype='float32')
403
404     loss = fluid.layers.elementwise_max(
405         zero_var, margin_minus_nt)
406
407     avg_cost = fluid.layers.mean(loss)
408     #pnum, nnum, pn = get_global_pn(cos_
```


除此之后，还有一个模型是CNN，可以通过C-API加载成功， 唯一的区别是在（2）步
CNN用的是
146         output = fluid.nets.sequence_conv_pool(
147                     input=_input,
148                     num_filters=hparams['hidden_dim'],
149                     filter_size=hparams['cnn_window_size'],
150                     param_attr = param_config(
151                         name=layer_name + "_cnn__",
152                     ),
153                     act=hparams['activate'],
154                     pool_type=hparams['pooling_type'],
155                     bias_attr = param_config(
156                         name = layer_name + "_cnn_bias__",
157                     ))

**Comment by Superjomn** [comment]
或者给一个__model__ 文件，我这边解析一下，大概率是op的attr 把int改成int64_t了，导致不同版本的训练存储下来和另外一个版本的预测库里，对这个attr解析的格式不一样

**Comment by sshilei** [comment]
通过hi提供模型文件

**Comment by Superjomn** [comment]
应该弄清楚了，的确是1月份改了代码导致不兼容；

建议使用版本一致的，但预测库是1版本的，可能比较老

@fc500110 我们最新的 1.4 的 pre-built 可以提供过来

类似这样的Op的attr定义内部不允许随意改，不然影响不同版本的兼容性，我们内部也会case study下。
