### ISSUE TITLE
adversarial training 中我需要使用输入的embeding的梯度信息，有没有接口

### ISSUE THREAD

**Issue by paulpaul91** [PaddlePaddle/Paddle#17358]
adversarial training 中我需要使用输入的embeding的梯度信息，有没有接口？
例如tensorflow中的tf.gradients 和pytorch 中的grad接口

**Comment by qingqing01** [comment]
@paulpaul91 得到输入的embeding的梯度信息之后会放入loss里，做梯度惩罚吗？

**Comment by qingqing01** [comment]
@paulpaul91 

Paddle目前的接口有一个没有对用户开放的接口，可以获取任意dy/dx的梯度，参考：  https://github.com/PaddlePaddle/Paddle/pull/16862 里的第4点描述，建议不要当做正式接口用。 我们目前正在开发可以将梯度加入loss，做梯度惩罚的。下个版本会有类似tf.gradients正式接口。

**Comment by paulpaul91** [comment]
> @paulpaul91 得到输入的embeding的梯度信息之后会放入loss里，做梯度惩罚吗？

不是，拿到grdient和embedding相加，再次送进网络计算loss

**Comment by qyccc** [comment]
> @paulpaul91 得到输入的embeding的梯度信息之后会放入loss里，做梯度惩罚吗？

你好，现在有什么做梯度惩罚的方式吗？我尝试用py_func自定义了前向后向函数，但是在后向函数里面用fluid.gradients 计算会报错
>  AttributeError: 'paddle.fluid.core_avx.LoDTensor' object has no attribute 'block' 
有什么解决方法吗
