### ISSUE TITLE
实现focal loss遇到的运行错误

### ISSUE THREAD

**Issue by rlistengr** [PaddlePaddle/Paddle#17350]
环境：百度AI studio
问题：

```
    labels = fluid.layers.data(name='labels', shape=[1], dtype='int64', lod_level=0)
    indexs = fluid.layers.data(name='indexs', shape=[1], dtype='int64', lod_level=0)

    。。。。
   #logits的大小是batch_size * 2
    predict = fluid.layers.softmax(input=logits)
    softmax = fluid.layers.reshape(logits, [-1])
    indexs1 = indexs + labels
    prob = fluid.layers.gather(softmax, indexs1)
    weight_ones = fluid.layers.ones(shape=[100], dtype="float")
    weight1 = weight_ones - prob
    weight = fluid.layers.pow(weight1, 2.0)
    ce_loss = weight * fluid.layers.log(prob)
```

现在运行时发生错误：

```
Traceback (most recent call last):
  File "train.py", line 348, in <module>
    main(args)
  File "train.py", line 223, in main
    fetch_list=[loss.name, accuracy.name, num_seqs.name, predict.name, labels.name])
  File "/usr/local/lib/python2.7/dist-packages/paddle/fluid/parallel_executor.py", line 303, in run
    self.executor.run(fetch_list, fetch_var_name)
paddle.fluid.core.EnforceNotMet: Invoke operator gather error.
Python Callstacks: 
  File "/usr/local/lib/python2.7/dist-packages/paddle/fluid/framework.py", line 1317, in append_op
    attrs=kwargs.get("attrs", None))
  File "/usr/local/lib/python2.7/dist-packages/paddle/fluid/layer_helper.py", line 56, in append_op
    return self.main_program.current_block().append_op(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/paddle/fluid/layers/nn.py", line 7165, in gather
    outputs={"Out": out})
  File "train.py", line 115, in create_model
    prob = fluid.layers.gather(softmax, indexs1)
  File "train.py", line 174, in main
    is_prediction=False)
  File "train.py", line 348, in <module>
    main(args)
C++ Callstacks: 
Tensor holds the wrong type, it holds int64_t at [/paddle/paddle/fluid/framework/tensor_impl.h:29]
PaddlePaddle Call Stacks: 
0       0x7f60519881a5p void paddle::platform::EnforceNotMet::Init<char const*>(char const*, char const*, int) + 357
1       0x7f6051988529p paddle::platform::EnforceNotMet::EnforceNotMet(std::__exception_ptr::exception_ptr, char const*, int) + 137
```

意思是gather操作的下标类型错误，麻烦帮忙看下

**Comment by Superjomn** [comment]
https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/fluid/operators/gather.h#L48

看起来 index 得是 int 格式的，不是 int64 的 

试下

 indexs = fluid.layers.data(name='indexs', shape=[1], dtype='int', lod_level=0)

**Comment by rlistengr** [comment]
我昨晚上试了，现在修改成了下面这个版本
    labels = fluid.layers.data(name='labels', shape=[1], dtype='int', lod_level=0)
    indexs = fluid.layers.data(name='indexs', shape=[1], dtype='int', lod_level=0)
下面是最后一个全连接层
    logits = fluid.layers.fc(
        input=logits2,
        size=num_labels,
        param_attr=fluid.ParamAttr(
            name="cls_out_w",
            initializer=fluid.initializer.TruncatedNormal(scale=0.2)),
        bias_attr=fluid.ParamAttr(
            name="cls_out_b", initializer=fluid.initializer.Constant(0.)))

    #ce_loss, predict = fluid.layers.softmax_with_cross_entropy(
    #    logits=logits, label=labels, return_softmax=True)
    #mul = labels * 0.7
    #labels1_loss = ce_loss * mul
    #ce_loss1 = ce_loss + labels1_loss
    
    predict = fluid.layers.softmax(input=logits)
    softmax = fluid.layers.reshape(logits, [-1])
    indexs1 = indexs + labels
    indexs2 = fluid.layers.reshape(indexs1, [-1])
   问题出错行就是下面这行，还是不行，明明已经是int了
    prob = fluid.layers.gather(softmax, indexs2)
    weight_ones = fluid.layers.ones(shape=[100], dtype="float")
    weight1 = weight_ones - prob
    weight = fluid.layers.pow(weight1, 2.0)
    ce_loss = weight * fluid.layers.log(prob)
    mul = fluid.layers.reshape(labels * 1, [-1])
    labels1_loss = ce_loss * mul
    ce_loss1 = ce_loss + labels1_loss

错误信息
Traceback (most recent call last):
  File "train.py", line 354, in <module>
    main(args)
  File "train.py", line 229, in main
    fetch_list=[loss.name, accuracy.name, num_seqs.name, predict.name, labels.name])
  File "/usr/local/lib/python2.7/dist-packages/paddle/fluid/parallel_executor.py", line 303, in run
    self.executor.run(fetch_list, fetch_var_name)
paddle.fluid.core.EnforceNotMet: Invoke operator gather error.
Python Callstacks: 
  File "/usr/local/lib/python2.7/dist-packages/paddle/fluid/framework.py", line 1317, in append_op
    attrs=kwargs.get("attrs", None))
  File "/usr/local/lib/python2.7/dist-packages/paddle/fluid/layer_helper.py", line 56, in append_op
    return self.main_program.current_block().append_op(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/paddle/fluid/layers/nn.py", line 7165, in gather
    outputs={"Out": out})
  File "train.py", line 118, in create_model
    prob = fluid.layers.gather(softmax, indexs2)
  File "train.py", line 180, in main
    is_prediction=False)
  File "train.py", line 354, in <module>
    main(args)
C++ Callstacks: 
Tensor holds the wrong type, it holds int64_t at [/paddle/paddle/fluid/framework/tensor_impl.h:29]
PaddlePaddle Call Stacks: 
0       0x7ff0859251a5p void paddle::platform::EnforceNotMet::Init<char const*>(char const*, char const*, int) + 357
1       0x7ff085925529p paddle::platform::EnforceNotMet::EnforceNotMet(std::__exception_ptr::exception_ptr, char const*, int) + 137
2       0x7ff08592ee62p int const* paddle::framework::Tensor::data<int>() const + 194
3       0x7ff0862208e0p void paddle::operators::GPUGather<float>(paddle::platform::DeviceContext const&, paddle::framework::Tensor const&, paddle::framework::Tensor const&, paddle::framework::Tensor*) + 272
4       0x7ff086220c3ap paddle::operators::GatherOpCUDAKernel<float>::Compute(paddle::framework::ExecutionContext const&) const + 314
5       0x7ff086220d73p std::_Function_handler<void (paddle::framework::ExecutionContext const&), paddle::framework::OpKernelRegistrarFunctor<paddle::platform::CUDAPlace, false, 0ul, paddle::operators::GatherOpCUDAKernel<float>, paddle::operators::GatherOpCUDAKernel<double>, paddle::operators::GatherOpCUDAKernel<long>, paddle::operators::GatherOpCUDAKernel<int>, paddle::operators::GatherOpCUDAKernel<paddle::platform::float16> >::operator()(char const*, char const*, int) const::{lambda(paddle::framework::ExecutionContext const&)#1}>::_M_invoke(std::_Any_data const&, paddle::framework::ExecutionContext const&) + 35
6       0x7ff08750b483p paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&) const + 659
7       0x7ff087508cf5p paddle::framework::OperatorBase::Run(paddle::framework::Scope const&, boost::variant<paddle::platfo

**Comment by Superjomn** [comment]
labels 还是 int64, index 是 int，不是两个都改

**Comment by rlistengr** [comment]
还是一样的结果，我本地有个类似的测试程序就没问题，

Traceback (most recent call last):
  File "train.py", line 354, in <module>
    main(args)
  File "train.py", line 229, in main
    fetch_list=[loss.name, accuracy.name, num_seqs.name, predict.name, labels.name])
  File "/usr/local/lib/python2.7/dist-packages/paddle/fluid/parallel_executor.py", line 303, in run
    self.executor.run(fetch_list, fetch_var_name)
paddle.fluid.core.EnforceNotMet: Invoke operator gather error.
Python Callstacks: 
  File "/usr/local/lib/python2.7/dist-packages/paddle/fluid/framework.py", line 1317, in append_op
    attrs=kwargs.get("attrs", None))
  File "/usr/local/lib/python2.7/dist-packages/paddle/fluid/layer_helper.py", line 56, in append_op
    return self.main_program.current_block().append_op(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/paddle/fluid/layers/nn.py", line 7165, in gather
    outputs={"Out": out})
  File "train.py", line 118, in create_model
    prob = fluid.layers.gather(softmax, indexs2)
  File "train.py", line 180, in main
    is_prediction=False)
  File "train.py", line 354, in <module>
    main(args)
C++ Callstacks: 
Tensor holds the wrong type, it holds int64_t at [/paddle/paddle/fluid/framework/tensor_impl.h:29]

**Comment by Superjomn** [comment]
![image](https://user-images.githubusercontent.com/328693/57695531-15cb1400-7681-11e9-8b3a-ef4a9849fc07.png)

这里应该会cast 成 int64，传到 gather 里还是 int64，不是 int，这里有问题

**Comment by rlistengr** [comment]
你意思是indexs1 = indexs+labels会被cast成int64？
我之前试过加完之后再加一步强转，强转成int，还是提示这个错误，感觉是gather这个接口问题了呢

**Comment by rlistengr** [comment]
softmax = fluid.layers.reshape(logits, [-1])
    indexs1 = indexs + labels
    indexs2 = fluid.layers.cast(indexs1, dtype='int')
    prob = fluid.layers.gather(softmax, indexs2)
当时是这样，
然后错误还是
Traceback (most recent call last):
  File "train.py", line 354, in <module>
    main(args)
  File "train.py", line 229, in main
    fetch_list=[loss.name, accuracy.name, num_seqs.name, predict.name, labels.name])
  File "/usr/local/lib/python2.7/dist-packages/paddle/fluid/parallel_executor.py", line 303, in run
    self.executor.run(fetch_list, fetch_var_name)
paddle.fluid.core.EnforceNotMet: Invoke operator gather error.
Python Callstacks: 
  File "/usr/local/lib/python2.7/dist-packages/paddle/fluid/framework.py", line 1317, in append_op
    attrs=kwargs.get("attrs", None))
  File "/usr/local/lib/python2.7/dist-packages/paddle/fluid/layer_helper.py", line 56, in append_op
    return self.main_program.current_block().append_op(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/paddle/fluid/layers/nn.py", line 7165, in gather
    outputs={"Out": out})
  File "train.py", line 118, in create_model
    prob = fluid.layers.gather(softmax, indexs2)
  File "train.py", line 180, in main
    is_prediction=False)
  File "train.py", line 354, in <module>
    main(args)
C++ Callstacks: 
Tensor holds the wrong type, it holds int64_t at [/paddle/paddle/fluid/framework/tensor_impl.h:29]

**Comment by rlistengr** [comment]
大神或者有没有其他方式可以实现我的这个需求，这是个二分类，每个样本有两个概率，只要取出每个样本所属分类的概率就行，还有什么layers的接口可以搞定这个事

**Comment by phlrain** [comment]
indexs2 = fluid.layers.cast(indexs1, dtype='int')
改成
indexs2 = fluid.layers.cast(indexs1, dtype='int32')

**Comment by rlistengr** [comment]
int32今天早上也试过了，也不行，而且错误提示还不一样了
Traceback (most recent call last):
  File "train.py", line 354, in <module>
    main(args)
  File "train.py", line 229, in main
    fetch_list=[loss.name, accuracy.name, num_seqs.name, predict.name, labels.name])
  File "/usr/local/lib/python2.7/dist-packages/paddle/fluid/parallel_executor.py", line 303, in run
    self.executor.run(fetch_list, fetch_var_name)
paddle.fluid.core.EnforceNotMet: Input X(0)is not initialized at [/paddle/paddle/fluid/framework/operator.cc:1093]
PaddlePaddle Call Stacks: 
0       0x7f400156e1a5p void paddle::platform::EnforceNotMet::Init<char const*>(char const*, char const*, int) + 357
1       0x7f400156e529p paddle::platform::EnforceNotMet::EnforceNotMet(std::__exception_ptr::exception_ptr, char const*, int) + 137
2       0x7f4003153499p paddle::framework::OperatorWithKernel::IndicateDataType(paddle::framework::ExecutionContext const&) const + 1385
3       0x7f40031536bfp paddle::framework::OperatorWithKernel::GetExpectedKernelType(paddle::framework::ExecutionContext const&) const + 47
4       0x7f4001fc5448p paddle::operators::CastOp::GetExpectedKernelType(paddle::framework::ExecutionContext const&) const + 40
5       0x7f40031542e0p paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&) const + 240
6       0x7f4003151cf5p paddle::framework::OperatorBase::Run(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&) + 341
7       0x7f4002fc7efap paddle::framework::details::ComputationOpHandle::RunImpl() + 250
8       0x7f4002fc15d6p paddle::framework::details::OpHandleBase::Run(bool) + 118
9       0x7f4002f597edp
10      0x7f4002f5a1edp paddle::framework::details::ThreadedSSAGraphExecutor::RunOp(std::shared_ptr<paddle::framework::BlockingQueue<paddle::framework::details::VarHandleBase*> > const&, paddle::framework::details::OpHandleBase*) + 1309
11      0x7f4002f5be64p paddle::framework::details::ThreadedSSAGraphExecutor::Run(std::vector<std::string, std::allocator<std::string> > const&) + 2324
12      0x7f4002f52eeap paddle::framework::details::ScopeBufferedSSAGraphExecutor::Run(std::vector<std::string, std::allocator<std::string> > const&) + 394
13      0x7f40016ac452p paddle::framework::ParallelExecutor::Run(std::vector<std::string, std::allocator<std::string> > const&, std::string const&) + 562
14      0x7f400155e47ep
15      0x7f4001599acep
16            0x4c5326p PyEval_EvalFrameEx + 37958
17            0x4b9b66p PyEval_EvalCodeEx + 774
18            0x4c17c6p PyEval_EvalFrameEx + 22758
19            0x4c141fp PyEval_EvalFrameEx + 21823
20            0x4b9b66p PyEval_EvalCodeEx + 774
21            0x4eb69fp
22            0x4e58f2p PyRun_FileExFlags + 130
23            0x4e41a6p PyRun_SimpleFileExFlags + 390
24            0x4938cep Py_Main + 1358
25      0x7f40606bd830p __libc_start_main + 240
26            0x493299p _start + 41

[/root/paddlejob/run.sh : 263] [start_trainer]
[FATAL]: execute user cmd failed

**Comment by Superjomn** [comment]
你是公司内的吗，我们可以线下对下，我 hi 是 yanchunwei

**Comment by luotao1** [comment]
@rlistengr 请问你是用什么版本的paddle呢？1.5版本已经修复这个问题了，可以传入int64类型。https://github.com/PaddlePaddle/Paddle/pull/17610
