### ISSUE TITLE
Request for trained models with program descriptors

### ISSUE THREAD

**Issue by wojtuss** [PaddlePaddle/Paddle#17365]
We are working on INT8v2 quantization of the models: GoogleNet, ResNet101, MobileNetV2, VGG16, VGG19, ShuffleNetV2. Their trained parameters are available at https://github.com/PaddlePaddle/models/tree/develop/PaddleCV/image_classification#supported-models-and-performances.
In order to enable the models in the unit tests, we need the full models (parameters and program descriptors) to be uploaded to the http://paddle-inference-dist.bj.bcebos.com server.
Could you please upload your full models there?

Internally we use program descriptors saved using python scripts from the `PaddlePaddle/models` repository. However, the FP32 accuracy values we get using them differ a little bit from the values reported on the above page with links to the parameters. We do care about getting the right accuracy and it would be very supportive if you could share your full models.

**Comment by luotao1** [comment]
> However, the FP32 accuracy values we get using them differ a little bit from the values reported on the above page with links to the parameters

Could you paste the difference here?

**Comment by wojtuss** [comment]
Sure. The differences in accuracy look like this:

Models | Baidu FP32 (cv2) | Our FP32
----|----|----
ResNet101 | 77.56% | 77.26%
VGG16 | 71.65% | 71.75%
VGG19 | 72.32% | 72.33%
GoogleNet | 70.27% | 69.92%
MobileNetV2 | 71.53% | 71.68%
ShuffleNetV2 | 69.48% | 69.34%

**Comment by luotao1** [comment]
Is the difference between CPU and GPU?
I see ResNet-50 and MobileNet-V1 have difference as well.
https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/fluid/inference/tests/api/int8_mkldnn_quantization.md

Models | Baidu FP32 (cv2) | Our FP32
----|----|----
ResNet50 | 76.22% | 76.63%
MobileNetV1 | 70.51% | 70.78%

**Comment by wojtuss** [comment]
Our values are from CPU (Intel i9, 1 socket, 14 cores), Baidu values are taken from the referenced page (https://github.com/PaddlePaddle/models/tree/develop/PaddleCV/image_classification#supported-models-and-performances).

**Comment by luotao1** [comment]
Baidu values are taken from the GPU.

**Comment by wojtuss** [comment]
I see, thank you.
Could you please upload the full models to the server http://paddle-inference-dist.bj.bcebos.com ? We can prepare them with our program descriptors if you like.

**Comment by luotao1** [comment]
I have uploaded all the models, please check it!

**Comment by wojtuss** [comment]
@luotao1 , thank you!
