### ISSUE TITLE
pyreader如果先调用了reset， 再调用decorate_tensor_provider，就会丢2个batch的数据

### ISSUE THREAD

**Issue by OleNet** [PaddlePaddle/Paddle#17377]
GPU p40/v100 
centos
单机/多卡

丢数据：
![bb3b05af7e704bb66d119af4f191a3af](https://user-images.githubusercontent.com/3206718/57622090-772aae80-75bf-11e9-8055-d40733f848e4.png)

正确：
![6efaaaf911193b4db41cef14e489a24e](https://user-images.githubusercontent.com/3206718/57622208-af31f180-75bf-11e9-9562-36a5ee562fa6.png)

**Comment by sneaxiy** [comment]
`py_reader.reset`必须在捕获`EOFException`时调用，不能在其他地方调用。

**Comment by OleNet** [comment]
感觉这个限制好隐晦，可以在doc里面说明吗。或者加入某种assert机制，防止用户再次出现这种错误。
