### ISSUE TITLE
请问有CompiledProgram结合pyreader的使用例子吗？

### ISSUE THREAD

**Issue by luluxing3** [PaddlePaddle/Paddle#17376]
http://paddlepaddle.org/documentation/docs/zh/1.4/api_guides/low_level/compiled_program.html 关于CompiledProgram只找到了这个介绍，这里只有feed_dict的数据传输方式。

**Comment by sneaxiy** [comment]
与原来使用Program相比，使用CompiledProgram时py_reader的使用方式不变。请您参考py_reader文档http://paddlepaddle.org/documentation/docs/zh/1.4/user_guides/howto/prepare_data/use_py_reader.html
