### ISSUE TITLE
fluid 有什么layer可以让变长序列变成定长的输出？

### ISSUE THREAD

**Issue by hyo009** [PaddlePaddle/Paddle#17385]
paddle版本： fluid 1.4 latest

如题，我的模型输出是定长的一维输出，但之前的结构是一个变长的序列，希望找出能过连接变长序列和定长输出的layer。

**Comment by seiriosPlus** [comment]
可以参考API文档中Sequece相关的API， http://paddlepaddle.org/documentation/docs/zh/1.4/api_cn/layers_cn.html#sequence-pool
