### ISSUE TITLE
如何save CompiledProgram？

### ISSUE THREAD

**Issue by luluxing3** [PaddlePaddle/Paddle#17384]
使用CompiledProgram 多卡训练，save 模型报错
![image](https://user-images.githubusercontent.com/23072928/57670112-5f473f00-7640-11e9-8f73-b928662def11.png)

**Comment by seiriosPlus** [comment]
1. 确认是多机多卡的训练(GPU)还是多机训练(CPU)
2. 尝试CompiledProgram的训练换成ParallelExecutor的训练

**Comment by luluxing3** [comment]
1. 单机多卡（GPU）
2. ParallelExecutor is deprecated? 代码需要定义多个program，定义多个ParallelExecutor 会有问题吗？

**Comment by chengduoZH** [comment]
目前只能保存Porgram，不能保存CompiledProgram。

**Comment by luluxing3** [comment]
请问保存CompiledProgram有计划开发吗？大概什么时候可以实现保存CompiledProgram？谢谢。

**Comment by chengduoZH** [comment]
@luluxing3 目前没有保存CompiledProgram的计划。
