### ISSUE TITLE
谁那里有paddledev/paddle:gpu-demo-latest导出的镜像，麻烦给个链接，感激不尽！

### ISSUE THREAD

**Issue by heiyexingchen** [PaddlePaddle/Paddle#1739]
谁那里有paddledev/paddle:gpu-demo-latest导出的镜像，麻烦给个链接，感激不尽！

我下载的时候，要么提示找不到文件，要么提示IP已经更换，要么就是连接超时，可能和我这边的网有关，但是已经快半个月了，都没有下下来！

**Comment by livc** [comment]
我帮你下了下来，你可以参考[这个](http://stackoverflow.com/questions/23935141/how-to-copy-docker-images-from-one-host-to-another-without-via-repository)导入。

https://transfer.sh/wBCwN/paddle.7z

**Comment by helinwang** [comment]
@heiyexingchen 国内请使用`docker pull docker.paddlepaddle.org/paddle:0.10.0rc2`
国外：`docker pull paddlepaddle/paddle:0.10.0rc2`
如何使用请参考这里：https://github.com/PaddlePaddle/Paddle/blob/develop/doc/getstarted/build_and_install/docker_install_en.rst

**Comment by helinwang** [comment]
Closing this issue for now due to no response. If you have any question, feel free to re-open it.
