### ISSUE TITLE
训练api_train_v2.py的时候提示ImportError: No module named v2

### ISSUE THREAD

**Issue by shenjiayi1993** [PaddlePaddle/Paddle#1740]
运行docker后运行源码下的demo/semantic_role_labeling/api_train_v2.py后提示No module named v2，请问可能是什么原因？

Traceback (most recent call last):
  File "api_train_v2.py", line 4, in <module>
    import paddle.v2 as paddle
ImportError: No module named v2

**Comment by livc** [comment]
您可以使用这个：https://github.com/PaddlePaddle/book

**Comment by helinwang** [comment]
请问您参考的是哪个使用说明？
可以参考这个使用说明：https://github.com/PaddlePaddle/Paddle/blob/develop/doc/getstarted/build_and_install/docker_install_en.rst

**Comment by Yancey1989** [comment]
看起来像镜像版本的问题? @shenjiayi1993 请问用的是哪个image？

**Comment by shenjiayi1993** [comment]
@Yancey1989 您好 我使用的是cpu-latest版本 安装在mac上的docker

**Comment by helinwang** [comment]
@shenjiayi1993 能否按照https://github.com/PaddlePaddle/Paddle/blob/develop/doc/getstarted/build_and_install/docker_install_en.rst，尝试一下这个image?: `paddlepaddle/paddle:0.10.0rc2`（或者国内的话`docker.paddlepaddle.org/paddle:0.10.0rc2`快一些）

**Comment by shenjiayi1993** [comment]
@helinwang 可以了！谢谢你~不过我想问一下为什么有些docker版本不行呢？

**Comment by helinwang** [comment]
@shenjiayi1993 v2 api还在release candidate阶段，没有正式发布，所以需要特别的版本号（0.10.0rc2)

**Comment by helinwang** [comment]
The problem seems to be fixed. Closing this issue for now. If you have any question, feel free to re-open it.
