### ISSUE TITLE
Releasing PaddlePaddle docker images and doc

### ISSUE THREAD

**Issue by Yancey1989** [PaddlePaddle/Paddle#1742]
# 背景
目前PaddlePaddle项目迭代很快，需要频繁的更新PaddlePaddle Docker Image或是Book Image，现阶段都是人为的手工build然后push到registry，效率很低

# 改进
我们需要一个能够自动发布的工具，这涉及到：
- 编译并push镜像
    - 自动编译并push PaddlePaddle 开发环境镜像以及生产环境镜像（四个版本）
    - 自动编译并push PaddlePaddle book镜像

- 同步镜像    
    将dockerhub上的镜像同步至香港的docker registry

- 更新文档  
    同步更新book.paddlepaddle.org网站上的内容

- 更新docker image
    - 对于develop分支的代码，每次更新都会触发一次重新build，push的流程，并更新tag为latest的docker image
    - 对于每产生一个tag，也会触发一次重新build，push的流程，并更新对应tag的docker image

- 状态显示    
    最好能够在主页上显示最近一次发布的状态：成功或者失败

- 编译工具&&环境
之前从 @typhoonzero  那里了解到目前用的travis ci工具每个job限制了最长执行时间为40分钟，而我们每次build的时间肯定会超过这个限制，或许我们可以考虑使用一台虚拟机定时执行这样的一个任务。

**Comment by helinwang** [comment]
之前@reyoung和我一起写了个CI系统（https://github.com/wangkuiyi/ci），可以考虑用它来做。

关于更新周期，感觉我们只需要每个tag产生的时候更新就好了。

**Comment by Yancey1989** [comment]
多谢 @helinwang 
> 关于更新周期，感觉我们只需要每个tag产生的时候更新就好了。

目前确实有用dev分之的代码更新某个docker images tag的情况，造成了github上的tag的代码和docker images是不一致的，看起来还需要用dev的代码来生成latest这个tag的docker image？

**Comment by helinwang** [comment]
@Yancey1989 是说develop可能引入新的build dependency，导致最新的develop和最新的tag编译环境不一致，所以需要latest-dev来对应最新的develop吗？有道理。
因为dev image是从docker file直接生成的，所以docker build感觉大部分时候都会用cache，所以估计build速度不会很慢。可以考虑先试试每次都push，如果有问题再做进一步打算。

**Comment by Yancey1989** [comment]
@helinwang build dev image 大部分时候会用到cache，但product image需要重新编译代码，我在阿里云 （1CPU，2G RAW）的机器上编译时，build每个product image需要至少20分钟左右的时间。可以先考虑每次都push：）

**Comment by helinwang** [comment]
@Yancey1989 dev image如果一直有最新的很方便开发者开发，product image不知道需不需要一直更新最新的？

**Comment by Yancey1989** [comment]
@helinwang 使用一致的tag就可以吧，比如dev是latest的，product image最好也使用latest的。

**Comment by gongweibao** [comment]
productimage应该按照版本更新吧？否则api更新了会造成用户需要改动自己的程序。

**Comment by typhoonzero** [comment]
之前写过一些用travis-ci自动push镜像的，受限于其限制了build时间还没完成，我来看下使用 https://github.com/wangkuiyi/ci 来实现的方法吧～

**Comment by typhoonzero** [comment]
另外：可能和这个issue关联：https://github.com/PaddlePaddle/Paddle/issues/1670

**Comment by helinwang** [comment]
Using the CI could fix this issue as well: https://github.com/PaddlePaddle/Paddle/issues/1783
