### ISSUE TITLE
core.pyd in paddle\fluid cannot be loaded on Windows 7

### ISSUE THREAD

**Issue by Bonum** [PaddlePaddle/Paddle#17431]
core.pyd in paddle\fluid cannot be loaded for neither of versions since vers. 1.2.0 on Windows 7

The last working version is vers. 1.2.0 , but the new functionality is missing.

**System information**::
-PaddlePaddle version （1.4.1. 1.4.0 and all versions since (except) 1.2.0)
-CPU: Intel i7-2600  Memory 10GB
-GPU: No
-OS Platform Windows 7, 64 bit
Environment:  Python 3.6.3 |Anaconda custom (64-bit)|) [MSC v.1900 64 bit (AMD64)] on win32
- Install method: pip install

Environment: Windows 7, Python 3.6.3 |Anaconda custom (64-bit)| (default, Nov 8 2017, 15:10:56) [MSC v.1900 64 bit (AMD64)] on win32
paddlepaddle 1.4.1 (and other older versions, except vers. 1.2.0 )

Bug Reproduce:

python
>import paddle.fluid as fluid

Traceback (most recent call last):
File "Q:\Anaconda\lib\site-packages\paddle\fluid\framework.py", line 41, in 
from . import core
ImportError: DLL load failed: The specified procedure could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "", line 1, in 
File "Q:\Anaconda\lib\site-packages\paddle\fluid_init_.py", line 18, in 
from . import framework
File "Q:\Anaconda\lib\site-packages\paddle\fluid\framework.py", line 50, in 
(executable_path, executable_path, cpt.get_exception_message(e)))
ImportError: NOTE: You may need to run "set PATH=Q:\Anaconda;%PATH%"
if you encounters "DLL load failed" errors. If you have python
installed in other directory, replace "Q:\Anaconda" with your own
directory. The original error is:
DLL load failed: The specified procedure could not be found.

**Comment by velconia** [comment]
@wopeizl would you like to take a look at this?

**Comment by wopeizl** [comment]
It can be due to msvcr120.dll missing, you can fix it by install vc2015 runtime.

**Comment by Bonum** [comment]
Thank you for your investigation, but
unfortunately msvcr120.dll doesn't cause the the problem.

 I do have Microsoft Visual C++ [2005,2008,2010,2012,2013,2015,2017] Redistributables and
 msvcr[71,80,90,100,110,120].dll versions in Windows\System32\ and in PATH directory.
 I even put msvcr120.dll in <Anaconda>\Lib\site-packages\paddle\fluid but the problem persists.
 
core.pyd in paddle\fluid can be loaded only for version version 1.2.0

 May be you should check what has changed in core.pyd since vers. 1.2.0
