### ISSUE TITLE
支持numpy中的repeat操作

### ISSUE THREAD

**Issue by qxin** [PaddlePaddle/Paddle#17438]
您好, 发现paddle没有支持numpy的repeat操作. 
因为有时候需要用到上采样, 但是上采样的方法每个人实现的经常有轻微diff. 为了保持一致.使用了repeat来模拟 nearest upsample.

**Comment by velconia** [comment]
@qingqing01 辛苦判断下这个是否是正确需求呢？

**Comment by qingqing01** [comment]
1. paddle实现的线性插值上采样，考虑到不同框架的实现差异，实际支持了多种mode：
http://paddlepaddle.org/documentation/docs/zh/1.4/api_cn/layers_cn.html#resize-bilinear
可以参考文档设置align_corners，align_mode。

2. 您说的repeat，Paddle确实没有提供这个API，提供了expand，不知道可否满足要求 http://paddlepaddle.org/documentation/docs/zh/1.4/api_cn/layers_cn.html#expand

**Comment by qxin** [comment]
expand的计算不一致(对应的是numpy中的tile,)

> 1. paddle实现的线性插值上采样，考虑到不同框架的实现差异，实际支持了多种mode：
>    http://paddlepaddle.org/documentation/docs/zh/1.4/api_cn/layers_cn.html#resize-bilinear
>    可以参考文档设置align_corners，align_mode。
> 2. 您说的repeat，Paddle确实没有提供这个API，提供了expand，不知道可否满足要求 http://paddlepaddle.org/documentation/docs/zh/1.4/api_cn/layers_cn.html#expand

**Comment by parap1uie-s** [comment]
+1，希望实现类似np.repeat的API

**Comment by Topdu** [comment]
可以如下实现

x = torch.randn(1, 3,5)
print(x,x.shape)
x = x.repeat(1, repeat_num,1)
print(x,x.shape)

x = paddle.randn([1, 3,5])
print(x.shape)
print(x)
x = paddle.concat([x for i in range(repeat_num)],axis=repeat_dim)
print(x)
