### ISSUE TITLE
Kubernetes cluster distributed training error

### ISSUE THREAD

**Issue by TheodoreG** [PaddlePaddle/Paddle#17439]
Hi, I am using paddle distributed training in "NCCL2" mode within a kubernetes cluster.
Here I have two workers in one namespace and can ping each other successfully:

![image](https://user-images.githubusercontent.com/13977118/57825116-1a521280-77d0-11e9-84d9-998ac22b08d0.png)

But when I start training it get errors:

![image](https://user-images.githubusercontent.com/13977118/57825135-2b028880-77d0-11e9-892a-325653a645be.png)

Such wrong only happens when two pods are assigned to different nodes. When those two pods are assigned to the same node, which equals multi-GPUs training there's no such error. How to solve it ?

**Comment by velconia** [comment]
@gongweibao would you like to take this question?

**Comment by gongweibao** [comment]
1. Check if there is http_proxy https_proxy
2. Which paddleversion do you use？
3. Do you use it in baidu cluster?
