### ISSUE TITLE
提供数组的原地index或select

### ISSUE THREAD

**Issue by qxin** [PaddlePaddle/Paddle#17444]
有时需要对数组的某一个维度进行原地操作,如exp或sigmoid等.  发现应该是不支持. 只能slice数组之后再concat完成. 但是这个slice操作应该是复制array的,  预期会比原地index或select的效率低. 希望能添加个新的op 支持这种操作.

**Comment by velconia** [comment]
![image](https://user-images.githubusercontent.com/1979255/57996792-1e49a180-7afc-11e9-8e66-a0ce363b5f0f.png)
slice操作是不会复制array的，效率应该不会低

**Comment by qxin** [comment]
好的, 多谢多谢
