### ISSUE TITLE
模型训练输入与预测输入转换问题

### ISSUE THREAD

**Issue by ylxsyf** [PaddlePaddle/Paddle#17441]
1）模型训练输入：
![image](https://user-images.githubusercontent.com/5714337/57826789-5f2d7780-77d7-11e9-9d62-4bcf3054ebd1.png)
2) 模型测试输入：
![image](https://user-images.githubusercontent.com/5714337/57826842-8f751600-77d7-11e9-8a18-8bedd53f90e2.png)
3）对应reader的输入：
yield word_idx, layer_idx, class_idx

问题描述：
因为reader里面的word_idx, layer_idx都是N*1维度的，但是class_idx是N*10维的（可以认为N是batch_size），报错：
    class_attr = to_lodtensor([x[2] for x in data], place)
  File "/home/disk5/nlp/paddle/sequence_tagging_for_ner/utils_extend.py", line 24, in to_lodtensor
    flattened_data = flattened_data.reshape([len(flattened_data), 1])
ValueError: cannot reshape array of size 12400 into shape (620,1)

**Comment by velconia** [comment]
用户在class_attr的输入转化为 [x, 20, 1] 的正确维度之后问题解决，issue暂时关闭

Please feel free to reopen this. :)
