### ISSUE TITLE
预测库链接失效

### ISSUE THREAD

**Issue by gavin1332** [PaddlePaddle/Paddle#17455]
http://paddlepaddle.org/documentation/docs/zh/1.4/advanced_usage/deploy/inference/build_and_install_lib_cn.html
![image](https://user-images.githubusercontent.com/1552048/57899634-63699b80-7890-11e9-99cc-180e35d2da94.png)

**Comment by sneaxiy** [comment]
已修复，请您再次尝试下载预测库。
