### ISSUE TITLE
训练过程中使用save_persistables保存参数的时候出core

### ISSUE THREAD

**Issue by Melonzhou** [PaddlePaddle/Paddle#17463]
训练过程中使用save_persistables保存参数的时候出core
    1）PaddlePaddle版本：1.3.0.post97
    2）GPU：V100,16G显存，CUDA-9.0和CUDNN-V7
    3）系统环境：python2.7
- 训练信息
    1）单机单卡
    2）显存信息
    3）Operator信息
-代码
![image](https://user-images.githubusercontent.com/5926307/57910397-cb7fa800-78b7-11e9-80ea-783fe7743ab6.png)
![image](https://user-images.githubusercontent.com/5926307/57910600-43e66900-78b8-11e9-9a32-6f968fba00e7.png)
![image](https://user-images.githubusercontent.com/5926307/57910612-4ba60d80-78b8-11e9-84f7-04ec807e7bb9.png)
![image](https://user-images.githubusercontent.com/5926307/57910622-51035800-78b8-11e9-99be-5bad7cc4aaac.png)
![image](https://user-images.githubusercontent.com/5926307/57910628-582a6600-78b8-11e9-81f8-b6cb7eace543.png)
![image](https://user-images.githubusercontent.com/5926307/57910660-61b3ce00-78b8-11e9-8a23-e8fd4dda558b.png)
![image](https://user-images.githubusercontent.com/5926307/57910692-7bedac00-78b8-11e9-8c10-66d466fa29c9.png)
![image](https://user-images.githubusercontent.com/5926307/57910795-afc8d180-78b8-11e9-883e-1951c08f27ea.png)
![image](https://user-images.githubusercontent.com/5926307/57910910-f74f5d80-78b8-11e9-89a0-f909234d1933.png)
报错信息：
![image](https://user-images.githubusercontent.com/5926307/57910933-08986a00-78b9-11e9-92f1-0b6df4258c58.png)

**Comment by sneaxiy** [comment]
能否贴下文本的代码，方便我复现？

**Comment by Melonzhou** [comment]
> 能否贴下文本的代码，方便我复现？

代码比较分散，我发你文件吧？怎么发呢？

**Comment by Melonzhou** [comment]
找到问题原因了，出错代码是这部分
![image](https://user-images.githubusercontent.com/5926307/57967197-4dda9b80-798e-11e9-8c5b-30e775037cd7.png)
其实num_seqs这个layer是没有连接到网络里面去的，参数里面是找不到对应的数据的，所以在保存的时候就出错了。

**Comment by Melonzhou** [comment]
> 找到问题原因了，出错代码是这部分
> ![image](https://user-images.githubusercontent.com/5926307/57967197-4dda9b80-798e-11e9-8c5b-30e775037cd7.png)
> 其实num_seqs这个layer是没有连接到网络里面去的，参数里面是找不到对应的数据的，所以在保存的时候就出错了。
补充一下，出错的时候是红框中的代码是没有被注释的，注释之后就能正常保存参数了。
