### ISSUE TITLE
Connecting Tensorboard to Paddle for inspecting training ? 

### ISSUE THREAD

**Issue by pengwangucla** [PaddlePaddle/Paddle#1746]
Tensorboard is a powerful tool for inspecting the training process ( checking parameters, intermedia results, accuracy  and learning loss) This is especially  useful when there is multiple loss and compare different model results. When training on server, we can view the process through webpages.

Currently, it is already supported for MXNet to combine tensorboard [here](https://github.com/dmlc/tensorboard). I think it could be also very useful for paddle, and it may not require much effort since both are dependent on Protobuf. 

I wonder whether paddle is able to develop an api for it.

Thanks
Peng Wang

**Comment by dzhwinter** [comment]
TensorBoard has a copyright that we can not use it directly, we will deliver a totally new tool to meet our needs. Now we have a VisualDL project  https://github.com/PaddlePaddle/VisualDL.  It will do the similar thing. And the Production team will also deliver a PaddleBoard tool nearly.

**Comment by 978326187** [comment]
where is PaddleBoard ？

**Comment by core-burner** [comment]
They said that they would do VisualDL then pulled everything to the cloud under wandb or something.
No visually observable training with paddlepaddle anymore.
