### ISSUE TITLE
concat出core

### ISSUE THREAD

**Issue by Hhairu** [PaddlePaddle/Paddle#17471]
fluid.layers.concat层，concat四个向量，当维度为64，128时都运行成功，改到2048维时报段错误，是否fluid不支持这么高的维度？
![image](https://user-images.githubusercontent.com/50739413/57925337-77d28600-78da-11e9-92da-0b4290339a54.png)
报错log:
![image](https://user-images.githubusercontent.com/50739413/57924609-1e695780-78d8-11e9-83d6-329eb2860571.png)

**Comment by sneaxiy** [comment]
能否把您的完整代码贴出来？我这边无法复现此bug。concat是支持这么高维度的。

**Comment by chengduoZH** [comment]
@Hhairu 请不要贴截图，贴截图会导致在issue里面搜不到内容。

**Comment by JiaXiao243** [comment]
请问这个问题解决了吗？@Hhairu
