### ISSUE TITLE
conda下面安装遇到的 requests包版本冲突问题

### ISSUE THREAD

**Issue by linkinbird** [PaddlePaddle/Paddle#17485]
MAC电脑下面通过pip安装CPU版本
Python 3.6.1 :: Anaconda 4.4.0 (x86_64)

pip3 install paddlepaddle 时报错

......
conda 4.6.14 requires ruamel_yaml>=0.11.14, which is not installed.
conda 4.6.14 has requirement requests>=2.12.4, but you'll have requests 2.9.2 which is incompatible.
Installing collected packages: requests, recordio, funcsigs, opencv-python, kiwisolver, matplotlib, graphviz, paddlepaddle
Found existing installation: requests 2.21.0
Uninstalling requests-2.21.0:
Could not install packages due to an EnvironmentError: [Errno 13] Permission denied: '/Users/bird/anaconda/lib/python3.6/site-packages/requests-2.21.0.dist-info/INSTALLER'
Consider using the --user option or check the permissions.

好像conda不允许你替换到他的requests版本哦，你这个2.9.2版本可以升到2.12吗

**Comment by JiabinYang** [comment]
可以试试，但不建议，最好不要使用conda的python安装，因为conda的python依赖和python官方的会有不同，目前我们还没有支持conda安装，请参考http://paddlepaddle.org/documentation/docs/zh/1.4/beginners_guide/install/install_MacOS.html，使用python.org或者brew下载的python来安装，
