### ISSUE TITLE
获取模型参数返回None

### ISSUE THREAD

**Issue by mengyiliu22** [PaddlePaddle/Paddle#17493]
使用save_persistables将模型保存在一个目录下，想加载模型并取出模型指定参数，输出None

<img width="489" alt="image" src="https://user-images.githubusercontent.com/15141419/58004339-9a041800-7b15-11e9-9700-6a0734162f1c.png">

**Comment by JiabinYang** [comment]
其他的parameters可以读取得到么

**Comment by mengyiliu22** [comment]
> 其他的parameters可以读取得到么

读不到，而且把path改为一个不存在的路径，返回也是None，不会报错

**Comment by JiabinYang** [comment]
> > 其他的parameters可以读取得到么
> 
> 读不到，而且把path改为一个不存在的路径，返回也是None，不会报错

是不是文件路径不对呢

**Comment by junjun315** [comment]
请问是什么版本？

**Comment by mengyiliu22** [comment]
> 请问是什么版本？

fluid 1.4

**Comment by mengyiliu22** [comment]
> > > 其他的parameters可以读取得到么
> > 
> > 
> > 读不到，而且把path改为一个不存在的路径，返回也是None，不会报错
> 
> 是不是文件路径不对呢

fluid.io.load_persistables(exe, path, prog)   给一个不存在的路径这里应该会报错啊。。。确认了下，路径没有问题

**Comment by junjun315** [comment]
对应保存的目录下，有形如fc_0.b_0文件名的文件么？

**Comment by mengyiliu22** [comment]
> 对应保存的目录下，有形如fc_0.b_0文件名的文件么？

<img width="1236" alt="image" src="https://user-images.githubusercontent.com/15141419/58008443-ffa8d200-7b1e-11e9-9b7e-b8ab460a3db7.png">
保存的模型文件很正常，加载模型做infer没有问题。

**Comment by junjun315** [comment]
我看了一下代码，prog是一个空的program吧？fluid下load_persisbale需要根据program来获取保存的var list，再进行恢复。如果没有program，请使用[load_vars](http://www.paddlepaddle.org/documentation/docs/zh/1.4/api_cn/io_cn.html#load-vars)，并构建vars 参数的参数列表来获取指定的var。

**Comment by mengyiliu22** [comment]
> 我看了一下代码，prog是一个空的program吧？fluid下load_persisbale需要根据program来获取保存的var list，再进行恢复。如果没有program，请使用[load_vars](http://www.paddlepaddle.org/documentation/docs/zh/1.4/api_cn/io_cn.html#load-vars)，并构建vars 参数的参数列表来获取指定的var。

尝试了load_vars，报错如下
assert isinstance(each_var, Variable)
AssertionError

尝试了load_params，报错如下
C++ Callstacks:
Enforce failed. Expected static_cast<int>(out_var_names.size()) > 0, but received static_cast<int>(out_var_names.size()):0 <= 0:0.
The number of output variables should be greater than 0. at [/paddle/paddle/fluid/operators/load_combine_op.h:40]

**Comment by mengyiliu22** [comment]
> 我看了一下代码，prog是一个空的program吧？fluid下load_persisbale需要根据program来获取保存的var list，再进行恢复。如果没有program，请使用[load_vars](http://www.paddlepaddle.org/documentation/docs/zh/1.4/api_cn/io_cn.html#load-vars)，并构建vars 参数的参数列表来获取指定的var。

我要取的参数其实在定义的时候是一个ParamAttr，load_vars时参数列表应该怎么构建呢，我感觉是我构建的有问题

**Comment by junjun315** [comment]
load_params的报错是因为把新输入的参数当作了文件名filename这个取值。

load_vars 是 vars  参数要求输入的是一个variable类型。 

从需求看，您可以用 load_inference_model ，也就是您用来预测时读取的方式构建恢复program和读取参数。 然后再用 find_var从恢复了的program中获取到对应的var 就可以了

**Comment by mengyiliu22** [comment]
> load_params的报错是因为把新输入的参数当作了文件名filename这个取值。
> 
> load_vars 是 vars 参数要求输入的是一个variable类型。
> 
> 从需求看，您可以用 load_inference_model ，也就是您用来预测时读取的方式构建恢复program和读取参数。 然后再用 find_var从恢复了的program中获取到对应的var 就可以了

可以把ParamAttr转为Variable吗

**Comment by mengyiliu22** [comment]
> load_params的报错是因为把新输入的参数当作了文件名filename这个取值。
> 
> load_vars 是 vars 参数要求输入的是一个variable类型。
> 
> 从需求看，您可以用 load_inference_model ，也就是您用来预测时读取的方式构建恢复program和读取参数。 然后再用 find_var从恢复了的program中获取到对应的var 就可以了

使用save_persistables保存的模型可以用于预测吗，使用load_inference_model缺少__model__文件

**Comment by junjun315** [comment]
如果只是调用了save_persistables ，是不会保存模型结构文件，所以不能用load_inference_model。
但是load_inference_model本身也包含一次 load_persistables操作，同理save的时候也是包含save_persistables.

如果使用ParamAttr转为Variable，则是有些麻烦了。

您可以从另外一个保存了模型文件的目录进行load_inference_model恢复program, 再用这个program，从你需要的参数目录来load_persistables。

**Comment by mengyiliu22** [comment]
> 如果只是调用了save_persistables ，是不会保存模型结构文件，所以不能用load_inference_model。
> 但是load_inference_model本身也包含一次 load_persistables操作，同理save的时候也是包含save_persistables.
> 
> 如果使用ParamAttr转为Variable，则是有些麻烦了。
> 
> 您可以从另外一个保存了模型文件的目录进行load_inference_model恢复program, 再用这个program，从你需要的参数目录来load_persistables。

可以理解为，在没有模型结构的情况下，load_persistables没办法根据模型目录和参数名取出参数/

**Comment by mengyiliu22** [comment]
> 如果只是调用了save_persistables ，是不会保存模型结构文件，所以不能用load_inference_model。
> 但是load_inference_model本身也包含一次 load_persistables操作，同理save的时候也是包含save_persistables.
> 
> 如果使用ParamAttr转为Variable，则是有些麻烦了。
> 
> 您可以从另外一个保存了模型文件的目录进行load_inference_model恢复program, 再用这个program，从你需要的参数目录来load_persistables。

试出了一种折中的办法，保存模型还是用save_persistables，加载模型取参数的时侯再定义一下网络结构，使用load_persistables可以取出参数

**Comment by junjun315** [comment]
> > 如果只是调用了save_persistables ，是不会保存模型结构文件，所以不能用load_inference_model。
> > 但是load_inference_model本身也包含一次 load_persistables操作，同理save的时候也是包含save_persistables.
> > 如果使用ParamAttr转为Variable，则是有些麻烦了。
> > 您可以从另外一个保存了模型文件的目录进行load_inference_model恢复program, 再用这个program，从你需要的参数目录来load_persistables。
> 
> 可以理解为，在没有模型结构的情况下，load_persistables没办法根据模型目录和参数名取出参数/

这个理解是正确的
