### ISSUE TITLE
PaddlePaddle1.4.0版本nccl出错

### ISSUE THREAD

**Issue by JiabinYang** [PaddlePaddle/Paddle#17507]
使用paddlepaddle/paddle:latest-dev和paddlepaddle/paddle:1.4.1-gpu-cuda9.0-cudnn7镜像，运行models/PaddleCV/image_classification/train.py --model=SE_ResNeXt50_32x4d --enable_ce=True，出现如下图问题：
<img width="1436" alt="MacHi 2019-05-20 21-34-57" src="https://user-images.githubusercontent.com/22361972/58025734-ae610880-7b47-11e9-8938-ba87e6fb1356.png">
<img width="1431" alt="MacHi 2019-05-20 21-35-12" src="https://user-images.githubusercontent.com/22361972/58025736-b02acc00-7b47-11e9-80c4-21396762cd45.png">
退回1.3.0版本可以正常运行

**Comment by JiaXiao243** [comment]
会不会是机子的问题呢？我使用相同的docker images运行是没有问题的。之前我的一台机器运行某几个模型总是报错，报错信息跟你的挺像了，附一下当时的截图。是机器p2p 的问题。
<img width="1033" alt="1" src="https://user-images.githubusercontent.com/37854899/58095643-137b3380-7c06-11e9-851a-6a89ec782e91.png">
可以看一下这个issue: [#1754](https://github.com/PaddlePaddle/models/issues/1754)
请问是同一台机器, paddle回退到1.3.0版本可以正常运行的吗？
