### ISSUE TITLE
PaddleRec里的gnn算法内存超了

### ISSUE THREAD

**Issue by xugang02** [PaddlePaddle/Paddle#17508]
- 标题：推荐广告使用PaddleRec里的gnn算法，报内存不够
- 版本、环境信息：
    1）PaddlePaddle版本：1.4.1
    2）CPU：
    3）GPU：CUDA9
    4）系统环境：python 2.7.3
- 训练信息
    1）单机，多卡
    2）Tesla K40m
    3）Operator信息
- 复现信息：
CUDA_VISIBLE_DEVICES=13,10,7,8,9,11,12,14 fluid -u train.py --use_cuda 1 >log1.txt 2>&1 &
- 问题描述：
2019-05-20 21:34:35,698-INFO: load data complete
W0520 21:34:36.788852 22316 device_context.cc:261] Please NOTE: device: 0, CUDA Capability: 35, Driver API Version: 9.0, Runtime API Version: 8.0
W0520 21:34:36.790452 22316 device_context.cc:269] device: 0, cuDNN Version: 5.1.
ParallelExecutor is deprecated. Please use CompiledProgram and Executor. CompiledProgram is a central place for optimization and Executor is the unified executor. Example can be found in compiler.py.
W0520 21:34:44.330098 22316 graph.h:204] WARN: After a series of passes, the current graph can be quite different from OriginProgram. So, please avoid using the `OriginProgram()` method!
2019-05-20 21:34:44,330-WARNING:
     You can try our memory optimize feature to save your memory usage:
         # create a build_strategy variable to set memory optimize option
         build_strategy = compiler.BuildStrategy()
         build_strategy.enable_inplace = True
         build_strategy.memory_optimize = True

         # pass the build_strategy to with_data_parallel API
         compiled_prog = compiler.CompiledProgram(main).with_data_parallel(
             loss_name=loss.name, build_strategy=build_strategy)

     !!! Memory optimize is our experimental feature !!!
         some variables may be removed/reused internal to save memory usage,
         in order to fetch the right value of the fetch_list, please set the
         persistable property to true for each variable in fetch_list

         # Sample
         conv1 = fluid.layers.conv2d(data, 4, 5, 1, act=None)
         # if you need to fetch conv1, then:
         conv1.persistable = True

I0520 21:34:48.196982 22316 build_strategy.cc:285] SeqOnlyAllReduceOps:0, num_trainers:1
2019-05-20 21:34:48,223-INFO: begin train
W0520 21:36:58.166503 22316 system_allocator.cc:125] Cannot malloc 7348.37 MB GPU memory. Please shrink FLAGS_fraction_of_gpu_memory_to_use or FLAGS_initial_gpu_memory_in_mb or
FLAGS_reallocate_gpu_memory_in_mbenvironment variable to a lower value. Current FLAGS_fraction_of_gpu_memory_to_use value is 0. Current FLAGS_initial_gpu_memory_in_mb value is 0. Current
FLAGS_reallocate_gpu_memory_in_mb value is 0
F0520 21:36:58.169145 22316 legacy_allocator.cc:200] Cannot allocate 7.176146GB in GPU 0, available 3.448120GBtotal 11995578368GpuMinChunkSize 256.000000BGpuMaxChunkSize 0.000000BGPU memory used: 0.
000000B

**Comment by JiabinYang** [comment]
可能是显存不足造成的，可以开启gc来优化显存试试，FLAGS_eager_delete_tensor_gb=0.0
