### ISSUE TITLE
py_reader相关问题

### ISSUE THREAD

**Issue by mengyiliu22** [PaddlePaddle/Paddle#17502]
![image](https://user-images.githubusercontent.com/15141419/58019570-65558800-7b38-11e9-91dd-63635e6d00f2.png)
使用py_reader读取数据，我理解每个循环读了一个batch数据，请问有什么方法可以把当前batch的数据打印出来吗？

**Comment by JiabinYang** [comment]
您可以模仿这个例子里，使用`read_file`然后，fetch`read_file`的内容：
    
    reader = fluid.layers.py_reader(capacity=64,
                                         shapes=[(-1, 1, 28, 28), (-1, 1)],
                                         dtypes=['float32', 'int64'])
         reader.decorate_paddle_reader(
             paddle.reader.shuffle(paddle.batch(mnist.train(), batch_size=5),
                                   buf_size=1000))

         img, label = fluid.layers.read_file(reader)
         loss = network(img, label)
         exe = fluid.ParallelExecutor(use_cuda=True)
         for epoch_id in range(10):
             reader.start()
                 try:
                     while True:
                         exe.run(fetch_list=[image, label])

**Comment by mengyiliu22** [comment]
> 您可以模仿这个例子里，使用`read_file`然后，fetch`read_file`的内容：
> 
> ```
> reader = fluid.layers.py_reader(capacity=64,
>                                      shapes=[(-1, 1, 28, 28), (-1, 1)],
>                                      dtypes=['float32', 'int64'])
>      reader.decorate_paddle_reader(
>          paddle.reader.shuffle(paddle.batch(mnist.train(), batch_size=5),
>                                buf_size=1000))
> 
>      img, label = fluid.layers.read_file(reader)
>      loss = network(img, label)
>      exe = fluid.ParallelExecutor(use_cuda=True)
>      for epoch_id in range(10):
>          reader.start()
>              try:
>                  while True:
>                      exe.run(fetch_list=[image, label])
> ```

我想取出来的是一个lod_level为1的序列，这样取报错如下：
RuntimeError: Some of your fetched tensors hold LoD information.             They can not be completely cast to Python ndarray.             Please set the parameter 'return_numpy' as 'False' to                 return LoDTensor itself directly.

**Comment by mengyiliu22** [comment]
> 您可以模仿这个例子里，使用`read_file`然后，fetch`read_file`的内容：
> 
> ```
> reader = fluid.layers.py_reader(capacity=64,
>                                      shapes=[(-1, 1, 28, 28), (-1, 1)],
>                                      dtypes=['float32', 'int64'])
>      reader.decorate_paddle_reader(
>          paddle.reader.shuffle(paddle.batch(mnist.train(), batch_size=5),
>                                buf_size=1000))
> 
>      img, label = fluid.layers.read_file(reader)
>      loss = network(img, label)
>      exe = fluid.ParallelExecutor(use_cuda=True)
>      for epoch_id in range(10):
>          reader.start()
>              try:
>                  while True:
>                      exe.run(fetch_list=[image, label])
> ```

设置exe.run()里面return_numpy=False， 然后np.array()取出lod，发现只有只有一维，而数据是一个序列，这是什么情况呢？

**Comment by JiabinYang** [comment]
> > 您可以模仿这个例子里，使用`read_file`然后，fetch`read_file`的内容：
> > ```
> > reader = fluid.layers.py_reader(capacity=64,
> >                                      shapes=[(-1, 1, 28, 28), (-1, 1)],
> >                                      dtypes=['float32', 'int64'])
> >      reader.decorate_paddle_reader(
> >          paddle.reader.shuffle(paddle.batch(mnist.train(), batch_size=5),
> >                                buf_size=1000))
> > 
> >      img, label = fluid.layers.read_file(reader)
> >      loss = network(img, label)
> >      exe = fluid.ParallelExecutor(use_cuda=True)
> >      for epoch_id in range(10):
> >          reader.start()
> >              try:
> >                  while True:
> >                      exe.run(fetch_list=[image, label])
> > ```
> 
> 设置exe.run()里面return_numpy=False， 然后np.array()取出lod，发现只有只有一维，而数据是一个序列，这是什么情况呢？

有lod的tensor不能用numpy返回，想看lod信息就需要使用tensor.lod(), 如果需要看数据的话就直接，np.array(Your_lod_tensor)

**Comment by mengyiliu22** [comment]
> > > 您可以模仿这个例子里，使用`read_file`然后，fetch`read_file`的内容：
> > > ```
> > > reader = fluid.layers.py_reader(capacity=64,
> > >                                      shapes=[(-1, 1, 28, 28), (-1, 1)],
> > >                                      dtypes=['float32', 'int64'])
> > >      reader.decorate_paddle_reader(
> > >          paddle.reader.shuffle(paddle.batch(mnist.train(), batch_size=5),
> > >                                buf_size=1000))
> > > 
> > >      img, label = fluid.layers.read_file(reader)
> > >      loss = network(img, label)
> > >      exe = fluid.ParallelExecutor(use_cuda=True)
> > >      for epoch_id in range(10):
> > >          reader.start()
> > >              try:
> > >                  while True:
> > >                      exe.run(fetch_list=[image, label])
> > > ```
> > 
> > 
> > 设置exe.run()里面return_numpy=False， 然后np.array()取出lod，发现只有只有一维，而数据是一个序列，这是什么情况呢？
> 
> 有lod的tensor不能用numpy返回，想看lod信息就需要使用tensor.lod(), 如果需要看数据的话就直接，np.array(Your_lod_tensor)

results = exe.run(infer_program, fetch_list=[predict, data[3], data[-1]], return_numpy=False)
logger.info(np.array(results[1]))

目前代码是这样的，data[3]是个序列，但是打印出来的数据都是单值的，和实际数据不一样

**Comment by JiabinYang** [comment]
> > > > 您可以模仿这个例子里，使用`read_file`然后，fetch`read_file`的内容：
> > > > ```
> > > > reader = fluid.layers.py_reader(capacity=64,
> > > >                                      shapes=[(-1, 1, 28, 28), (-1, 1)],
> > > >                                      dtypes=['float32', 'int64'])
> > > >      reader.decorate_paddle_reader(
> > > >          paddle.reader.shuffle(paddle.batch(mnist.train(), batch_size=5),
> > > >                                buf_size=1000))
> > > > 
> > > >      img, label = fluid.layers.read_file(reader)
> > > >      loss = network(img, label)
> > > >      exe = fluid.ParallelExecutor(use_cuda=True)
> > > >      for epoch_id in range(10):
> > > >          reader.start()
> > > >              try:
> > > >                  while True:
> > > >                      exe.run(fetch_list=[image, label])
> > > > ```
> > > 
> > > 
> > > 设置exe.run()里面return_numpy=False， 然后np.array()取出lod，发现只有只有一维，而数据是一个序列，这是什么情况呢？
> > 
> > 
> > 有lod的tensor不能用numpy返回，想看lod信息就需要使用tensor.lod(), 如果需要看数据的话就直接，np.array(Your_lod_tensor)
> 
> results = exe.run(infer_program, fetch_list=[predict, data[3], data[-1]], return_numpy=False)
> logger.info(np.array(results[1]))
> 
> 目前代码是这样的，data[3]是个序列，但是打印出来的数据都是单值的，和实际数据不一样

有使用`memory_optimize`么

**Comment by mengyiliu22** [comment]
> memory_optimize

没有使用

**Comment by JiabinYang** [comment]
你可以提供一下具体的代码么

**Comment by mengyiliu22** [comment]
> 你可以提供一下具体的代码么

这个问题已经绕过去了，使用了别的方法打印数据

**Comment by leiyahui** [comment]
> > 你可以提供一下具体的代码么
> 
> 这个问题已经绕过去了，使用了别的方法打印数据

有了什么方法呢，求教
