### ISSUE TITLE
请问有fluid版本的LTR模型示例吗？

### ISSUE THREAD

**Issue by ybbz** [PaddlePaddle/Paddle#17519]
请问有fluid版本的LTR模型示例吗？（类似v2版本的ranknet和lambdarank）
如果想用fluid来做排序学习（比如pairwise），该怎么做呢？

**Comment by wzzju** [comment]
pairwise训练和普通pointwise训练的区别在于：（1）用两个相同的网络，一个叫left，一个叫right，共享所有参数（2）每次输入进去的是query+left_title+right_title+label，label用来指示“是left好还是right好”（3）顶上的cost用rank_loss
然后rank_loss在paddle中是有现成的
http://www.paddlepaddle.org/documentation/docs/zh/1.4/api_cn/layers_cn.html#rank-loss
剩下的组网您可以组两个一样的网然后连一起。
上述大致给您提供一个思路吧。LTR模型示例我没有找到，抱歉。

**Comment by ybbz** [comment]
好的，非常感谢 @wzzju
