### ISSUE TITLE
yolov3 开放代码库调用报错

### ISSUE THREAD

**Issue by 930083287** [PaddlePaddle/Paddle#17520]
paddlepaddle:1.4.0
对于部署代码并数据及预训练模型之后，执行python train.py --model_save_dir=output/ --pretrain=weights/darknet53/ --data_dir=data/coco/coco17/  出现报错
![image](https://user-images.githubusercontent.com/15224527/58073427-17db2880-7bd5-11e9-8aba-fb4d0898d4ca.png)
![image](https://user-images.githubusercontent.com/15224527/58073674-d26b2b00-7bd5-11e9-8573-9cacdda66f48.png)

**Comment by heavengate** [comment]
输入读入为None，下载的coco数据集部分图片缺失，如下图，请重新下载coco数据集尝试
![2566cec6c4e2c923d010813088d7676c](https://user-images.githubusercontent.com/12605721/58075611-b1590900-7bda-11e9-98aa-22309267b2a9.png)
