### ISSUE TITLE
uniform_random在python3环境下运行出错

### ISSUE THREAD

**Issue by wzzju** [PaddlePaddle/Paddle#17538]
![image](https://user-images.githubusercontent.com/17102274/58091654-c21a7680-7bfc-11e9-93c2-d0c1438cdb42.png)
![image](https://user-images.githubusercontent.com/17102274/58091662-c8a8ee00-7bfc-11e9-9be7-9fdd0acc5c36.png)
uniform_random在python3环境下运行出错，在python2下可以运行正常。

**Comment by hong19860320** [comment]
It's recently fixed by @Lfc1993  and @sneaxiy, plz merge PR #17086 and #17492.
https://github.com/PaddlePaddle/Paddle/pull/17086
https://github.com/PaddlePaddle/Paddle/pull/17492

**Comment by paulpaul91** [comment]
> It's recently fixed by @Lfc1993 and @sneaxiy, plz merge PR #17086 and #17492.
> #17086
> #17492
针对这个问题 pip 安装的版本什么时候更新

**Comment by hong19860320** [comment]
paddepaddle1.4.1
