### ISSUE TITLE
安装1.4.1版本后跑预测出现找不到libnccl.so问题

### ISSUE THREAD

**Issue by littlepan0413** [PaddlePaddle/Paddle#17532]
之前安装了1.3.0.post97版本，预测没有问题，但是这个版本有bug导致功能无法使用，卸载之后重新安装1.4.1.post97版本，然后运行报错

**Failed to find dynamic library: libnccl.so ( libnccl.so: cannot open shared object file: No such file or directory )**

完整报错信息
W0521 17:05:35.625020 21264 dynamic_loader.cc:107] Can not find library: libnccl.so. Please try to add the lib path to LD_LIBRARY_PATH.
terminate called after throwing an instance of 'paddle::platform::EnforceNotMet'
  what():  Failed to find dynamic library: libnccl.so ( libnccl.so: cannot open shared object file: No such file or directory )
 Please specify its path correctly using following ways:
 Method. set environment variable LD_LIBRARY_PATH on Linux or DYLD_LIBRARY_PATH on Mac OS.
 For instance, issue command: export LD_LIBRARY_PATH=...
 Note: After Mac OS 10.11, using the DYLD_LIBRARY_PATH is impossible unless System Integrity Protection (SIP) is disabled. at [/paddle/paddle/fluid/platform/dynload/dynamic_loader.cc:163]
PaddlePaddle Call Stacks:
0       0x7f9925d177f0p void paddle::platform::EnforceNotMet::Init<char const*>(char const*, char const*, int) + 352
1       0x7f9925d17b69p paddle::platform::EnforceNotMet::EnforceNotMet(std::__exception_ptr::exception_ptr, char const*, int) + 137
2       0x7f9927a46a25p paddle::platform::dynload::GetNCCLDsoHandle() + 1813
3       0x7f99276019a9p void std::__once_call_impl<std::_Bind_simple<paddle::platform::dynload::DynLoad__ncclCommDestroy::operator()<ncclComm*>(ncclComm*)::{lambda()#1} ()> >() + 9
4       0x7f997948fbe0p pthread_once + 80
5       0x7f9927a21463p paddle::platform::CUDADeviceContext::~CUDADeviceContext() + 259
6       0x7f9927a216b1p paddle::platform::CUDADeviceContext::~CUDADeviceContext() + 17
7       0x7f9925ec8c45p std::_Hashtable<int, std::pair<int const, paddle::platform::NCCLContext>, std::allocator<std::pair<int const, paddle::platform::NCCLContext> >, std::__detail::_Select1st, std::equal_to<int>, std::hash<int>, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<false, false, true> >::clear() + 53
8       0x7f9925eca3b9p paddle::platform::NCCLContextMap::NCCLContextMap(std::vector<boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_>, std::allocator<boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> > > const&, ncclUniqueId*, unsigned long, unsigned long) + 2441
9       0x7f9925ec6090p paddle::framework::ParallelExecutor::ParallelExecutor(std::vector<boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_>, std::allocator<boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> > > const&, std::vector<std::string, std::allocator<std::string> > const&, std::string const&, paddle::framework::Scope*, std::vector<paddle::framework::Scope*, std::allocator<paddle::framework::Scope*> > const&, paddle::framework::details::ExecutionStrategy const&, paddle::framework::details::BuildStrategy const&, paddle::framework::ir::Graph*) + 2816
10      0x7f9925dae7e8p
11      0x7f9925d4a8dep
12      0x7f9979729973p PyObject_Call + 67
13      0x7f997973880dp
14      0x7f9979729973p PyObject_Call + 67
15      0x7f9979782764p
16      0x7f997977f01bp
17      0x7f9979729973p PyObject_Call + 67
18      0x7f99797bfd49p PyEval_EvalFrameEx + 15289
19      0x7f99797c56c9p PyEval_EvalCodeEx + 2025
20      0x7f99797c2b98p PyEval_EvalFrameEx + 27144
21      0x7f99797c56c9p PyEval_EvalCodeEx + 2025
22      0x7f99797c2b98p PyEval_EvalFrameEx + 27144
23      0x7f99797c56c9p PyEval_EvalCodeEx + 2025
24      0x7f997974e567p
25      0x7f9979729973p PyObject_Call + 67
26      0x7f997973880dp
27      0x7f9979729973p PyObject_Call + 67
28      0x7f9979782764p
29      0x7f997977f01bp
30      0x7f9979729973p PyObject_Call + 67
31      0x7f99797bfd49p PyEval_EvalFrameEx + 15289
32      0x7f99797c56c9p PyEval_EvalCodeEx + 2025
33      0x7f99797c2b98p PyEval_EvalFrameEx + 27144
34      0x7f99797c56c9p PyEval_EvalCodeEx + 2025
35      0x7f99797c58eap PyEval_EvalCode + 26
36      0x7f99797debadp
37      0x7f99797dfd28p PyRun_FileExFlags + 120
38      0x7f99797e0f48p PyRun_SimpleFileExFlags + 232
39      0x7f99797f316cp Py_Main + 2988
40      0x7f99789dab45p __libc_start_main + 245
41      0x7f99798c307fp

*** Aborted at 1558429535 (unix time) try "date -d @1558429535" if you are using GNU date ***
PC: @                0x0 (unknown)
*** SIGABRT (@0x1f400005310) received by PID 21264 (TID 0x7f99796c5740) from PID 21264; stack trace: ***
    @     0x7f9979492130 (unknown)
    @     0x7f99789ee9d9 __GI_raise
    @     0x7f99789f00e8 __GI_abort
    @     0x7f9948af43df __gnu_cxx::__verbose_terminate_handler()
    @     0x7f9948af2b16 __cxxabiv1::__terminate()
    @     0x7f9948af1f91 __cxa_call_terminate
    @     0x7f9948af279d __gxx_personality_v0
    @     0x7f9970a48f56 _Unwind_RaiseException_Phase2
    @     0x7f9970a493e9 _Unwind_Resume
    @     0x7f997948fc26 clear_once_control
    @     0x7f9927a21463 paddle::platform::CUDADeviceContext::~CUDADeviceContext()
    @     0x7f9927a216b1 paddle::platform::CUDADeviceContext::~CUDADeviceContext()
    @     0x7f9925ec8c45 std::_Hashtable<>::clear()
    @     0x7f9925eca3b9 paddle::platform::NCCLContextMap::NCCLContextMap()
    @     0x7f9925ec6090 paddle::framework::ParallelExecutor::ParallelExecutor()
    @     0x7f9925dae7e8 _ZZN8pybind1112cpp_function10initializeIZNS_6detail8initimpl11constructorIJRKSt6vectorIN5boost7variantIN6paddle8platform9CUDAPlaceENS9_8CPUPlaceENS9_15CUDAPinnedPlaceENS6_6detail7variant5void_ESF_SF_SF_SF_SF_SF_SF_SF_SF_SF_SF_SF_SF_SF_SF_SF_EESaISG_EERKS5_ISsSaISsEERKSsPNS8_9framework5ScopeERS5_IST_SaIST_EERKNSR_7details17ExecutionStrategyERKNSX_13BuildStrategyEPNSR_2ir5GraphEEE7executeINS_6class_INSR_16ParallelExecutorEJEEEJELi0EEEvRT_DpRKT0_EUlRNS2_16value_and_holderESK_SO_SQ_ST_SW_S10_S13_S16_E_vJS1J_SK_SO_SQ_ST_SW_S10_S13_S16_EJNS_4nameENS_9is_methodENS_7siblingENS2_24is_new_style_constructorEEEEvOT_PFT0_DpT1_EDpRKT2_ENUlRNS2_13function_callEE1_4_FUNES21_
    @     0x7f9925d4a8de pybind11::cpp_function::dispatcher()
    @     0x7f9979729973 PyObject_Call
    @     0x7f997973880d instancemethod_call
    @     0x7f9979729973 PyObject_Call
    @     0x7f9979782764 slot_tp_init
    @     0x7f997977f01b type_call
    @     0x7f9979729973 PyObject_Call
    @     0x7f99797bfd49 PyEval_EvalFrameEx
    @     0x7f99797c56c9 PyEval_EvalCodeEx
    @     0x7f99797c2b98 PyEval_EvalFrameEx
    @     0x7f99797c56c9 PyEval_EvalCodeEx
    @     0x7f99797c2b98 PyEval_EvalFrameEx
    @     0x7f99797c56c9 PyEval_EvalCodeEx
    @     0x7f997974e567 function_call
    @     0x7f9979729973 PyObject_Call
    @     0x7f997973880d instancemethod_call
test_inference.sh: line 19: 21264 已放弃               python -u predict_classifier.py --task_name ${TASK_NAME} --use_cuda true --batch_size 50 --data_dir ${DATA_PATH} --vocab_path ${BERT_BASE_PATH}/vocab.txt --init_checkpoint ${INIT_CKPT_PATH} --do_lower_case true --max_seq_len 128 --bert_config_path ${BERT_BASE_PATH}/bert_config.json --do_predict true --save_inference_model_path ${INIT_CKPT_PATH}/xnli

**Comment by wzzju** [comment]
这个问题主要是因为您所在的机器上没有安装nccl，请您安装一下nccl。
