### ISSUE TITLE
PaddlePaddle Fluid 编译Paddle-TRT预测库时的docker问题

### ISSUE THREAD

**Issue by 986088924** [PaddlePaddle/Paddle#17531]
系统环境：win10系统
docker编译：
在获取docker镜像时，因为提示没有nvidia-docker，所以先去下载   。
在下载的过程中执行下载命令 dpkg -i nvidia-docker_1.0.1-1_amd64.deb
提示”dpkg不是内部或外部命令，也不是可运行的程序”
了解之后发现只有dpkg是在Linux系统中用的？现在不知道如何才能成功获取docker镜像。

**Comment by NHZlX** [comment]
貌似nvidia-docker 没有windows版本，建议在linux下测试。另外，trt4不支持windows。
