### ISSUE TITLE
自己编译的paddle集群环境训练报glibc.2.14 not found

### ISSUE THREAD

**Issue by phoenares** [PaddlePaddle/Paddle#17558]
在本地离线服务器用gcc4.8.2编译的paddle，在本地可以运行。推到集群训练时报错，错误如下：
Traceback (most recent call last):
  File "train.py", line 9, in <module>
    import paddle.fluid as fluid
  File "/home/slurm/job/tmp/job-36306/env/env/lib/python2.7/site-packages/paddle/fluid/__init__.py", line 18, in <module>
    from . import framework
  File "/home/slurm/job/tmp/job-36306/env/env/lib/python2.7/site-packages/paddle/fluid/framework.py", line 56, in <module>
    directory. The original error is: \n""" + cpt.get_exception_message(e))
ImportError: NOTE: You may need to run "export LD_LIBRARY_PATH=/usr/local/lib:$LD_LIBRARY_PATH"
        if you encounters "libmkldnn.so not found" errors. If you have python
        installed in other directory, replace "/usr/local/lib" with your own
        directory. The original error is: 
/lib64/libc.so.6: version `GLIBC_2.14' not found (required by /home/slurm/job/tmp/job-36306/env/env/lib/python2.7/site-packages/paddle/fluid/core.so)

**Comment by phoenares** [comment]
按照https://github.com/PaddlePaddle/Paddle/issues/10054，
加入LD_LIBRARY_PATH=/opt/compiler/gcc-4.8.2/lib64:$LD_LIBRARY_PATH，
然后会报如下错误：
/var/slurm/slurmd/job36910/slurm_script: line 32: 82485 Segmentation fault      $HERE/env/env/bin/python train.py

一个集群同事说只有在glibc低版本的机器上编译，集群的/lib64/glibc.so.6是2.12版本的，我本地是2.17版本的，但是也不知到为啥编译出来的是2.14版本的。。。是有什么参数设置吗，谢谢

**Comment by JiabinYang** [comment]
应该是集群的的glibc太老了，最好是在低版本的机器上编译，glibc的依赖是取决编译的机器，没有参数设置
