### ISSUE TITLE
Paddle inference_demo中rnn1模型，python加载报维度错误

### ISSUE THREAD

**Issue by OliverLPH** [PaddlePaddle/Paddle#17563]
- 标题：Paddle inference_demo中rnn1模型，python加载报维度错误
- 版本、环境信息：
    1）PaddlePaddle版本：1.4
    2）CPU：预测若用CPU，请提供CPU型号，MKL/OpenBlas/MKLDNN/等数学库使用情况
    3）GPU：Nvidia p4, cuda8, cudnn7
    4）系统环境：centos6.1, python3.5
  
- 复现信息：

```python
place = fluid.CPUPlace()
exe = fluid.Executor(place)
model_dir = "/Paddle/build/third_party/inference_demo/rnn1/"
params_dirname = model_dir + "model"
with fluid.scope_guard(fluid.core.Scope()):
    [program, feed, fetch] = fluid.io.load_inference_model(
        params_dirname,
        exe,
        model_filename='__model__',
        params_filename='__params__')
    
    prog_file = "{}/__model__".format(model_dir + "model")
    params_file = "{}/__params__".format(model_dir + "model")
    config = fluid.core.AnalysisConfig(prog_file, params_file)
    config.disable_gpu()

    program = fluid.compiler.CompiledProgram(program)
    program.with_inference_optimize(config)
    outputs = exe.run(program, feed=input_value)
```
报错如下
![image](https://user-images.githubusercontent.com/14963836/58157735-88ed0f80-7cab-11e9-95f5-1847c08b6975.png)

- 问题描述：

输入模型的数据确认是正确的，包括数据的 lod，shape信息（与/paddle/fluid/inference/tests/api/analyzer_rnn1_tester.cc的输入数据比对过）。

目前就是感到很困惑，输入数据正确，但并不能成功加载数据。

**Comment by Superjomn** [comment]
我们持续集成系统里会每天测试 rnn1 的c++ 模型，应该还是 python 哪儿用错了。
