### ISSUE TITLE
fasterrcnn 训练时出错

### ISSUE THREAD

**Issue by 930083287** [PaddlePaddle/Paddle#17564]
![image](https://user-images.githubusercontent.com/15224527/58159723-b1770880-7caf-11e9-9537-9beba5a4f786.png)
paddle：1.4.0 
执行命令：python train.py --help 
python安装在/mnt/huangxueyuan01/local/python2.7/bin//python，并非默认目录

**Comment by jerrywgz** [comment]
请问你的paddle是如何安装的呢？版本是？

**Comment by 930083287** [comment]
pip install *.whl paddle.14.1
