### ISSUE TITLE
在ai studio上用cpu不报错，改成算力卡用gpu报错：EnforceNotMet: Invoke operator batch_norm_grad error. 

### ISSUE THREAD

**Issue by 315536712** [PaddlePaddle/Paddle#17566]
![微信截图_20190522164421](https://user-images.githubusercontent.com/13358316/58160887-dff5e300-7cb1-11e9-895c-61413b4349e2.png)
![微信截图_20190522164332](https://user-images.githubusercontent.com/13358316/58160902-e5ebc400-7cb1-11e9-88d3-2875360fe78d.png)
![微信截图_20190522164239](https://user-images.githubusercontent.com/13358316/58160908-e84e1e00-7cb1-11e9-9e5a-9e4fd07da3da.png)

**Comment by 315536712** [comment]
aistudio链接：https://aistudio.baidu.com/aistudio/projectdetail/58618

**Comment by jerrywgz** [comment]
请问是在运行过程中挂的吗

**Comment by 315536712** [comment]
> 请问是在运行过程中挂的吗

是的

**Comment by jerrywgz** [comment]
从报错信息看是产生了空输出导致之后的op计算时报错，可以先确认下是否为数据问题，也可以通过Print op打印下各层的输出是否异常

**Comment by 315536712** [comment]
> 从报错信息看是产生了空输出导致之后的op计算时报错，可以先确认下是否为数据问题，也可以通过Print op打印下各层的输出是否异常

哦哦哦，这和使用GPU有关系吗？如果没关系，那使用CPU应该也产生空输出的话才对啊？

**Comment by jerrywgz** [comment]
有可能是在GPU kernel下计算导致的这个问题，另外可以先关闭显存优化来缩小范围

**Comment by 315536712** [comment]
> 有可能是在GPU kernel下计算导致的这个问题，另外可以先关闭显存优化来缩小范围

怎么关闭显存？有具体的代码吗？

**Comment by jerrywgz** [comment]
你这边有使用memory optimize吗，如果有可以先去掉；另外你这边使用的paddle版本是？

**Comment by jerrywgz** [comment]
另外就是你这边使用GPU的是单卡吗
