### ISSUE TITLE
动态图切换eval模式导致显存增加

### ISSUE THREAD

**Issue by DDDivano** [PaddlePaddle/Paddle#17568]
加上这段代码显存会一直增长，第二个图是显存增长
![image](https://user-images.githubusercontent.com/10734244/58163455-a4114c80-7cb6-11e9-9e88-3a4b2178bc9f.png)
![image](https://user-images.githubusercontent.com/10734244/58163787-2ac62980-7cb7-11e9-9dbf-ae28df8d6015.png)

**Comment by phlrain** [comment]
这个问题我们已经修复了，你可以尝试编译下最新的develop代码
