### ISSUE TITLE
reader部分报错，cudaMemcpy failed

### ISSUE THREAD

**Issue by thomas010** [PaddlePaddle/Paddle#17569]
【问题描述】
原网络正常运行，在此之上添加如下代码（只修改网络内部结构，输入输出接口不变），reader部分却报错，请问可能什么原因

【添加代码】
![image](https://user-images.githubusercontent.com/7474360/58393317-d2a17580-8070-11e9-9c8d-6232ba175155.png)

【报错信息】
提示 cudaMemcpy failed

**Comment by jerrywgz** [comment]
这个任务是在多卡上吗？看起来像是多卡数据拷贝的问题

**Comment by thomas010** [comment]
已解决。用dynamic_gru op替换lstm op可以运行，需要先把输入input通过sequence_unpad转换成序列输入，代码如下：

![image](https://user-images.githubusercontent.com/7474360/58393366-fb296f80-8070-11e9-905c-b0641644379c.png)

**Comment by thomas010** [comment]
训练到第3个epoch，sequence_unpad op出错，错误信息如下：
paddle.fluid.core.EnforceNotMet: Invoke operator sequence_unpad error.
C++ Callstacks:
Enforce failed. Expected numel() * SizeOfType(type()) <= memory_size(), but received numel() * SizeOfType(type()):71860247984660480 > memory_size():393216.
Tensor's dims_ is out of bound. Call Tensor::mutable_data first to re-allocate memory.
or maybe the required data-type mismatches the data already stored. at [/paddle/paddle/fluid/framework/tensor.cc:28]

补充paddle堆栈信息：
![image](https://user-images.githubusercontent.com/7474360/58449034-63915300-813c-11e9-9999-9ba35ff2ff3a.png)

**Comment by heavengate** [comment]
这个问题和该issue没有关联，麻烦重新提一个issue，便于问题记录和其他遇到该问题的开发者检索，谢谢
