### ISSUE TITLE
PaddleSlim是否支持object detection模型ssd mobilenet的压缩？

### ISSUE THREAD

**Issue by sherrysfu** [PaddlePaddle/Paddle#17579]
**System information**
-PaddlePaddle version （eg.1.4.1）
-CPU: including CPUMKL/OpenBlas/MKLDNN version
-GPU: including CUDA/CUDNN version
-OS Platform (eg.Mac OS 10.14)
-Python version： 3.7
-Name of Models&Dataset/details of operator：PaddleSlim

尝试修改PaddleSlim/compress.py, 将ssd mobilenet在pasalvoc上进行压缩， 结果运行出错。
**To Reproduce** 请问是否支持object detection模型的压缩。

**Comment by wanghaoshuang** [comment]
理论上是支持的，但是官方没做过实验验证，没有release相关数据。

**Comment by wanghaoshuang** [comment]
方便把code和错误日志贴一下么

**Comment by sherrysfu** [comment]
<img width="718" alt="Capture" src="https://user-images.githubusercontent.com/30885303/58294476-26654380-7d7f-11e9-8b0e-27d2344916d6.PNG">

[compress0.txt](https://github.com/PaddlePaddle/Paddle/files/3214572/compress0.txt)

**Comment by sherrysfu** [comment]
谢谢，我感觉train和eval的program我没写好，请帮忙看看。

**Comment by sherrysfu** [comment]
你好，现在已经没有error，但是感觉求解有问题，可以帮忙看下code吗？谢谢
<img width="633" alt="Capture" src="https://user-images.githubusercontent.com/30885303/58349169-67109b80-7e17-11e9-9a96-b4feb5bab7f9.PNG">

[compress0.docx](https://github.com/PaddlePaddle/Paddle/files/3218182/compress0.docx)
