### ISSUE TITLE
使用动态图后，在网络init时报 got multiple values for keyword argument错误

### ISSUE THREAD

**Issue by wzgwzg** [PaddlePaddle/Paddle#17572]
paddle版本1.4.1

网络定义的__init__()函数如下：
14 class ResNet(fluid.dygraph.Layer):
 15     def __init__(self, name_scope, layers=50):
 16         super(ResNet, self).__init__(name_scope)
 17         self.layers = layers

Coatt_ResNet会将上面的ResNet作为自己的backbone

138 class Coatt_ResNet(fluid.dygraph.Layer):
139     def __init__(self, name_scope, layers=50, num_classes=751, num_features=1024, num_instances=4, is_train=True):
140         super(Coatt_ResNet, self).__init__(name_scope)
141         self.base = ResNet(self.full_name())
142         self.num_classes = num_classes
143         self.num_features = num_features
144         assert num_instances > 1
145         self.num_instances = num_instances
146         self.is_train = is_train

训练时，build_program过程会报错
def build_program(is_train, main_prog, startup_prog, args):
    image_shape = [int(m) for m in args.image_shape.split(",")]
    model_name = args.model
    model_list = [m for m in dir(models) if "__" not in m]
    assert model_name in model_list, "{} is not in lists: {}".format(args.model, model_list)
    model = models.__dict__[model_name]('co_att', layers=args.layers, num_classes=args.class_dim, num_features=args.num_features, num_instances=args.num_instances, is_train=True)
就是这里的最后一句

**Comment by phlrain** [comment]
错误的完整log 能否粘贴一下

**Comment by wzgwzg** [comment]
> 错误的完整log 能否粘贴一下

整个log就这么多，这还是开了GLOG_vmodule=operator=4 的debug模式

24 Traceback (most recent call last):
 25   File "train.py", line 318, in <module>
 26     main()
 27   File "train.py", line 314, in main
 28     train(args)
 29   File "train.py", line 192, in train
 30     q_acc, att_acc, global_lr = build_program(is_train=True, main_prog=train_prog, startup_prog=startup_prog, args=args)
 31   File "train.py", line 128, in build_program
 32     model = models.__dict__[model_name]('co_att', layers=args.layers, num_classes=args.class_dim, num_features=args.num_features, num_instances=args.num_instances    , is_train=True)
 33 TypeError: Coatt_ResNet50() got multiple values for keyword argument 'layers'

**Comment by phlrain** [comment]
我感觉是你的  args.layers 给的是多个值（list, 或者tuple)，不是单个值

**Comment by wzgwzg** [comment]
> 我感觉是你的 args.layers 给的是多个值（list, 或者tuple)，不是单个值

27 add_arg('batch_size',       int,   16,                   "Minibatch size.")
28 add_arg('layers',           int,   50,                   "resnet layers")
29 add_arg('class_dim',        int,   751,                  "Class number.")
给的值是确实是单个啊，我开始还怀疑是不是开了多卡有什么影响，结果把并行关了还是同样的错误

**Comment by phlrain** [comment]
能否提供下环境，我们复现下

**Comment by wzgwzg** [comment]
> 能否提供下环境，我们复现下

ok，我怎么联系你，可否提供一下hi账号
