### ISSUE TITLE
build error uint64_t undefined in alloc_continuous_space_for_grad_pass.h

### ISSUE THREAD

**Issue by jnorwood** [PaddlePaddle/Paddle#17584]
为使您的问题得到快速解决，在建立Issues前，请您先通过如下方式搜索是否有相似问题:【搜索issue关键字】【使用labels筛选】【官方文档】

如果您没有查询到相似问题，为快速解决您的提问，建立issue时请提供如下细节信息：
- 标题：简洁、精准概括您的问题
- 版本、环境信息：
    1）PaddlePaddle版本：请提供您的PaddlePaddle版本号，例如1.1或CommitID
    2）CPU/GPU：如果您使用GPU训练，请提供GPU驱动版本、CUDA和cuDNN版本号
    3）系统环境：请您描述系统类型、版本，例如Mac OS 10.14
    4）Python版本号
    5）显存信息
- 复现信息：如为报错，请给出复现环境、复现步骤
- 问题描述：请详细描述您的问题，同步贴出报错信息、日志/代码关键片段

Thank you for contributing to PaddlePaddle.
Before submitting the issue, you could search issue in the github in case that there was a similar issue submitted or resolved before.
If there is no solution,please provide us with the following details :
**System information**
-PaddlePaddle version （eg.1.1）or CommitID
-CPU: including CPUMKL/OpenBlas/MKLDNN version
-GPU: including CUDA/cuDNN version
-OS Platform and Distribution(eg.Mac OS 10.14)
-Python version 
**To Reproduce**
Steps to reproduce the behavior
**Describe your current behavior**
**Code to reproduce the issue**
**Other info / logs**

**Comment by jnorwood** [comment]
latest build from source, using ubuntu 18.04, gcc7.4.0
`
git clone https://github.com/PaddlePaddle/Paddle.git

mkdir Paddledbg

cd Paddledbg

```
cmake -DFLUID_INFERENCE_INSTALL_DIR=/home/jay/PaddleInst \
      -DCMAKE_BUILD_TYPE=RELWITHDEBINFO \
      -DWITH_PYTHON=OFF \
      -DWITH_MKL=OFF \
	  -DWITH_TESTING=ON \
      -DWITH_GPU=OFF  \
      -DON_INFER=ON \
      ../Paddle

````
`
home/jay/Paddle/paddle/fluid/framework/ir/alloc_continuous_space_for_grad_pass.h:25:1: error: ‘uint64_t’ does not name a type; did you mean ‘u_int64_t’?
 uint64_t GetFuseParameterMemorySize();
`

Fixed my own buld by including boost::cstdint, as done in other files:
`
#include <boost/cstdint.hpp>
`
`
void SetFuseParameterMemorySize(boost::uint64_t memory_size);

boost::uint64_t GetFuseParameterMemorySize();
 `

**Comment by JiabinYang** [comment]
Looks like you are using a wrong version of gcc to compile paddle, plz using gcc 4.8 or 5.4 as your complier because there is some compiler diff will cause problem

**Comment by jnorwood** [comment]
while the build completed, several tests failed.  I haven't debugged to see if it is related.

`88% tests passed, 12 tests failed out of 103

Label Time Summary:
RUN_TYPE=DIST         =   0.26 sec*proc (11 tests)
RUN_TYPE=EXCLUSIVE    =   0.32 sec*proc (1 test)

Total Test time (real) =  25.82 sec

The following tests FAILED:
	 37 - test_naive_executor (Failed)
	 92 - test_api_impl (Failed)
	 94 - test_inference_image_classification_vgg (Failed)
	 95 - test_inference_image_classification_resnet (Failed)
	 96 - test_inference_label_semantic_roles (Failed)
	 97 - test_inference_recognize_digits_mlp (Failed)
	 98 - test_inference_recognize_digits_conv (Failed)
	 99 - test_inference_recommender_system (Failed)
	100 - test_inference_word2vec (Failed)
	101 - test_inference_nlp (Failed)
	102 - test_train_recognize_digits_mlp (Failed)
	103 - test_train_recognize_digits_conv (Failed)
Errors while running CTest
`

**Comment by JiabinYang** [comment]
Could u plz post the complete test error log?

**Comment by jnorwood** [comment]
[paddle_logs.zip](https://github.com/PaddlePaddle/Paddle/files/3212440/paddle_logs.zip)
I'm attaching the zip archive that  contains the ctest --verbose log and the original build log, which contained the uint64_t error.  I didn't save the build log after adding the boost:cstdint include, but it built and linked all the tests without error.  There are a number of compiler warnings in the  build log which I didn't try to correct, though.

The ctest log shows all errors except one are trying to access something under a python subdirectory in the build path.  However, I built with -DWITH_PYTHON=OFF, as suggested by the documentation instructions.  Maybe these tests just need to be disabled in the cmake config if WITH_PYTHON==OFF.

There is one other failure which is not doing a python subdirectory access, but I haven't tried to examine it further.

**Comment by jnorwood** [comment]
[paddle_log2.zip](https://github.com/PaddlePaddle/Paddle/files/3213030/paddle_log2.zip)

I'm attaching a build log after adding the fix.  It shows the completed build, with the test cases linking successfully. 

I pushed my change into an onnxtst branch in my fork of Paddle
` https://github.com/jnorwood/Paddle/commit/37a60f464e35bfa9a9b4d289c506fca5164d5b9b `

**Comment by JiabinYang** [comment]
Thx for ur support for Paddle!
