### ISSUE TITLE
请问用 train_pyreader.decorate_tensor_provider，怎么指定输入变量lod_levels=1和对应的lod呢？

### ISSUE THREAD

**Issue by laoliukan** [PaddlePaddle/Paddle#17595]

**Comment by frankwhzhang** [comment]
详细描述一下问题

**Comment by laoliukan** [comment]
paddle bert中feed数据是使用的train_pyreader.decorate_tensor_provider
train_pyreader.decorate_tensor_provider(train_data_generator)
模型中具体的定义是：
pyreader = fluid.layers.py_reader(
        capacity=50,
        shapes=[[-1, args.max_seq_len, 1], [-1, args.max_seq_len, 1],
                [-1, args.max_seq_len, 1], [-1, args.max_seq_len, 1], [-1, 1]],
        dtypes=['int64', 'int64', 'int64', 'float32', 'int64'],
        lod_levels=[0, 0, 0, 0, 0],
        name=pyreader_name,
        use_double_buffer=True)

现在我想再传一个slot_label，lod_level想设为1，并且设定lod值，请问应该怎么feed数据呢？

**Comment by laoliukan** [comment]
> 详细描述一下问题

paddle bert中feed数据是使用的train_pyreader.decorate_tensor_provider
train_pyreader.decorate_tensor_provider(train_data_generator)
模型中具体的定义是：
pyreader = fluid.layers.py_reader(
capacity=50,
shapes=[[-1, args.max_seq_len, 1], [-1, args.max_seq_len, 1],
[-1, args.max_seq_len, 1], [-1, args.max_seq_len, 1], [-1, 1]],
dtypes=['int64', 'int64', 'int64', 'float32', 'int64'],
lod_levels=[0, 0, 0, 0, 0],
name=pyreader_name,
use_double_buffer=True)

现在我想再传一个slot_label，lod_level想设为1，并且设定lod值，请问应该怎么feed数据呢？

**Comment by frankwhzhang** [comment]
https://github.com/PaddlePaddle/Paddle/blob/0d4cbdad91777320c35e7454833792268d97f1f3/python/paddle/fluid/lod_tensor.py#L23
