### ISSUE TITLE
Paddle V2 API 文档的英文注释需要完善

### ISSUE THREAD

**Issue by lcy-seso** [PaddlePaddle/Paddle#1759]
[Paddle V2 API 文档](http://www.paddlepaddle.org/develop/doc/api/v2/model_configs.html) 的注释中有非常多基础的英文语法错误，很多写得令人费解，影响普通用户的理解。

最好可以逐渐地修改，最基本的，至少保证不要有太低级的语法错误。

**Comment by helinwang** [comment]
赞！可以考虑用grammerly.com检查语法错。

**Comment by lcy-seso** [comment]
大家持续对python 用户接口中的英文注释做了一些完善，我先close 掉这个issue。
