### ISSUE TITLE
save_inference_model保存时program没有clone(is_test=True)的影响

### ISSUE THREAD

**Issue by xiangyubo** [PaddlePaddle/Paddle#17591]
请教个问题，save_inference_model 这个函数里的 program，如果没有设置用 program.clone(for_test=True)，会有什么影响吗？网络里没用 bn，用了 dropout

**Comment by frankwhzhang** [comment]
我的理解是 如果训练和预测是同时进行的 ，program.clone(for_test=True) 是为了去掉反向和优化，直接复用Program. 如果训练和预测是两个程序，预测阶段只需要Load_inference_model就可以。 参考https://github.com/PaddlePaddle/models/tree/develop/PaddleRec/gru4rec 里面的train.py 和infer.py

**Comment by xiangyubo** [comment]
@frankwhzhang 谢谢解答哈，没太懂，其实我就想问，有不有必要把 is_test 的设置为 True。会不会对精度有影响

**Comment by frankwhzhang** [comment]
不会
