### ISSUE TITLE
import paddle.fluid as fluid成功，但是执行fluid.install_check.run_check()报错

### ISSUE THREAD

**Issue by ghost** [PaddlePaddle/Paddle#17597]
- 版本、环境信息：
    1）PaddlePaddle版本：paddlepaddle-gpu-1.4.1.post97
    2）CPU：i5-8300h
    3）GPU：1050ti，cuda_9.0.176_384.81_linux， cudnn-9.0-linux-x64-v7.5.1.10
    4）系统环境：Ubuntu18.04 python3.6.7
- 安装方式信息：
1）pip3安装

报错信息如下：
`Python 3.6.7 (default, Oct 22 2018, 11:32:17) 
[GCC 8.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import paddle.fluid as fluid
>>> fluid.install_check.run_check()
Running Verify Fluid Program ... 
W0523 18:16:51.931136  2125 device_context.cc:261] Please NOTE: device: 0, CUDA Capability: 61, Driver API Version: 9.1, Runtime API Version: 9.0
W0523 18:16:52.534754  2125 device_context.cc:269] device: 0, cuDNN Version: 7.0.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/dist-packages/paddle/fluid/install_check.py", line 63, in run_check
    exe.run(default_startup_program())
  File "/usr/local/lib/python3.6/dist-packages/paddle/fluid/executor.py", line 565, in run
    use_program_cache=use_program_cache)
  File "/usr/local/lib/python3.6/dist-packages/paddle/fluid/executor.py", line 642, in _run
    exe.run(program.desc, scope, 0, True, True, fetch_var_name)
paddle.fluid.core.EnforceNotMet: Invoke operator fill_constant error.
Python Callstacks: 
  File "/usr/local/lib/python3.6/dist-packages/paddle/fluid/framework.py", line 1725, in _prepend_op
    attrs=kwargs.get("attrs", None))
  File "/usr/local/lib/python3.6/dist-packages/paddle/fluid/initializer.py", line 167, in __call__
    stop_gradient=True)
  File "/usr/local/lib/python3.6/dist-packages/paddle/fluid/framework.py", line 1619, in create_parameter
    initializer(param, self)
  File "/usr/local/lib/python3.6/dist-packages/paddle/fluid/layer_helper_base.py", line 316, in create_parameter
    **attr._to_kwargs(with_initializer=True))
  File "/usr/local/lib/python3.6/dist-packages/paddle/fluid/dygraph/layers.py", line 89, in create_parameter
    default_initializer)
  File "/usr/local/lib/python3.6/dist-packages/paddle/fluid/dygraph/nn.py", line 904, in build_once
    attr=self._bias_attr, shape=size, dtype=self._dtype, is_bias=True)
  File "/usr/local/lib/python3.6/dist-packages/paddle/fluid/dygraph/layers.py", line 156, in __call__
    self.build_once(*inputs)
  File "/usr/local/lib/python3.6/dist-packages/paddle/fluid/install_check.py", line 37, in forward
    x = self._fc1(inputs)
  File "/usr/local/lib/python3.6/dist-packages/paddle/fluid/dygraph/layers.py", line 158, in __call__
    outputs = self.forward(*inputs)
  File "/usr/local/lib/python3.6/dist-packages/paddle/fluid/install_check.py", line 58, in run_check
    out = simple_layer(inp)
  File "<stdin>", line 1, in <module>
C++ Callstacks: 
Enforce failed. Expected allocating <= available, but received allocating:3702537255 > available:3547332352.
Insufficient GPU memory to allocation. at [/paddle/paddle/fluid/platform/gpu_info.cc:262]
PaddlePaddle Call Stacks: 
0       0x7f9754264228p void paddle::platform::EnforceNotMet::Init<std::string>(std::string, char const*, int) + 360
1       0x7f9754264577p paddle::platform::EnforceNotMet::EnforceNotMet(std::string const&, char const*, int) + 87
2       0x7f9755fac706p paddle::platform::GpuMaxChunkSize() + 630
3       0x7f9755f810a2p
4       0x7f97a2f4c827p
5       0x7f9755f8074dp paddle::memory::legacy::GetGPUBuddyAllocator(int) + 109
6       0x7f9755f81573p void* paddle::memory::legacy::Alloc<paddle::platform::CUDAPlace>(paddle::platform::CUDAPlace const&, unsigned long) + 35
7       0x7f9755f819b5p paddle::memory::allocation::LegacyAllocator::AllocateImpl(unsigned long, paddle::memory::allocation::Allocator::Attr) + 389
8       0x7f9755fa6c6bp paddle::memory::allocation::Allocator::Allocate(unsigned long, paddle::memory::allocation::Allocator::Attr) + 27
9       0x7f9755f755b3p paddle::memory::allocation::AllocatorFacade::Alloc(boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&, unsigned long, paddle::memory::allocation::Allocator::Attr) + 435
10      0x7f9755f756d1p paddle::memory::allocation::AllocatorFacade::AllocShared(boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&, unsigned long, paddle::memory::allocation::Allocator::Attr) + 33
11      0x7f9755bb35a0p paddle::memory::AllocShared(boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&, unsigned long, paddle::memory::allocation::Allocator::Attr) + 48
12      0x7f9755f4796ap paddle::framework::Tensor::mutable_data(boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_>, paddle::framework::proto::VarType_Type, paddle::memory::allocation::Allocator::Attr, unsigned long) + 154
13      0x7f9754f200d1p paddle::operators::FillConstantKernel<float>::Compute(paddle::framework::ExecutionContext const&) const + 497
14      0x7f9754f23273p std::_Function_handler<void (paddle::framework::ExecutionContext const&), paddle::framework::OpKernelRegistrarFunctor<paddle::platform::CUDAPlace, false, 0ul, paddle::operators::FillConstantKernel<float>, paddle::operators::FillConstantKernel<double>, paddle::operators::FillConstantKernel<long>, paddle::operators::FillConstantKernel<int>, paddle::operators::FillConstantKernel<paddle::platform::float16> >::operator()(char const*, char const*, int) const::{lambda(paddle::framework::ExecutionContext const&)#1}>::_M_invoke(std::_Any_data const&, paddle::framework::ExecutionContext const&) + 35
15      0x7f9755ef3376p paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&, paddle::framework::RuntimeContext*) const + 662
16      0x7f9755ef3ae4p paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&) const + 292
17      0x7f9755ef140cp paddle::framework::OperatorBase::Run(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&) + 332
18      0x7f97543d63fep paddle::framework::Executor::RunPreparedContext(paddle::framework::ExecutorPrepareContext*, paddle::framework::Scope*, bool, bool, bool) + 382
19      0x7f97543d723fp paddle::framework::Executor::Run(paddle::framework::ProgramDesc const&, paddle::framework::Scope*, int, bool, bool, std::vector<std::string, std::allocator<std::string> > const&, bool) + 143
20      0x7f97542538dep
21      0x7f97542967cep
22            0x565d5cp _PyCFunction_FastCallDict + 860
23            0x503073p
24            0x506859p _PyEval_EvalFrameDefault + 1097
25            0x504c28p
26            0x502540p
27            0x502f3dp
28            0x507641p _PyEval_EvalFrameDefault + 4657
29            0x504c28p
30            0x502540p
31            0x502f3dp
32            0x506859p _PyEval_EvalFrameDefault + 1097
33            0x502209p
34            0x502f3dp
35            0x506859p _PyEval_EvalFrameDefault + 1097
36            0x504c28p
37            0x506393p PyEval_EvalCode + 35
38            0x634d52p
39            0x4a38c5p
40            0x4a5cd5p PyRun_InteractiveLoopFlags + 212
41            0x6387b3p PyRun_AnyFileExFlags + 83
42            0x63915ap Py_Main + 1402
43            0x4a6f10p main + 224
44      0x7f97a317db97p __libc_start_main + 231
45            0x5afa0ap _start + 42
`

**Comment by frankwhzhang** [comment]
有详细的代码吗 以及任务是什么

**Comment by ghost** [comment]
> 有详细的代码吗 以及任务是什么

就是导入paddle.fluid，然后测试是否安装成功，
`
fluid.install_check.run_check()
`

**Comment by frankwhzhang** [comment]
http://www.paddlepaddle.org/documentation/docs/zh/1.4/beginners_guide/install/index_cn.html
应该是没有安装成功吧 这里有个文档

**Comment by ghost** [comment]
> http://www.paddlepaddle.org/documentation/docs/zh/1.4/beginners_guide/install/index_cn.html
> 应该是没有安装成功吧 这里有个文档

我也觉得是安装不成功，但是没有找到原因，因为paddle.fluid可以正常导入，然后执行fluid.install_check.run_check()报错不知道是为什么，官方文档中也没找到具体该如何处理

**Comment by frankwhzhang** [comment]
您是百度内部用户 还是外部用户

**Comment by JiabinYang** [comment]
看报错是显存不足

**Comment by ghost** [comment]
> 看报错是显存不足

请问您知道如何解决吗

**Comment by ghost** [comment]
> 您是百度内部用户 还是外部用户

c4人工智能创意赛的参赛选手

**Comment by JiabinYang** [comment]
> > 看报错是显存不足
> 
> 请问您知道如何解决吗

这个需要您看一下是不是您的显卡有占用，如果有的话，杀掉占用显卡的进程再运行
