### ISSUE TITLE
做为中国本土的深度学习，为什么自然语言处理没有支持中文的

### ISSUE THREAD

**Issue by bournes** [PaddlePaddle/Paddle#176]
百度的李大大，请问做为中国本土的深度学习，为什么自然语言处理没有支持中文

**Comment by backyes** [comment]
Thanks your attention, we may provide more easy full demos about Chinese word, but currently you can check related DOC here:

Chinese Word Embedding Model Tutorial 
http://www.paddlepaddle.org/doc/demo/embedding_model/index.html

In PaddlePaddle, Chinese word is also treated as 'ID' value, almost same as English language with train mode.
