### ISSUE TITLE
grpc error, error_code:8

### ISSUE THREAD

**Issue by AWSWXY** [PaddlePaddle/Paddle#17604]
Thu May 23 17:05:57 2019[1,10]<stdout>:F0523 17:05:57.958317 59461 grpc_client.cc:357] GetRPC name:[fc_1.w_0], ep:[10.197.70.28:62004], status:[-1] meets grpc error, error_code:8 error_message:Sent message larger than max (2857176090 vs. 2147483647) error_details:
Thu May 23 17:05:58 2019[1,10]<stdout>:*** Check failure stack trace: ***
Thu May 23 17:05:58 2019[1,10]<stdout>:    @     0x7f86466afcdd  google::LogMessage::Fail()
Thu May 23 17:05:58 2019[1,10]<stdout>:    @     0x7f86466b378c  google::LogMessage::SendToLog()
Thu May 23 17:05:58 2019[1,10]<stdout>:    @     0x7f86466af803  google::LogMessage::Flush()
Thu May 23 17:05:58 2019[1,10]<stdout>:    @     0x7f86466b4c9e  google::LogMessageFatal::~LogMessageFatal()
Thu May 23 17:05:58 2019[1,10]<stdout>:    @     0x7f8647104994  paddle::operators::distributed::GRPCClient::Proceed()
Thu May 23 17:05:58 2019[1,10]<stdout>:    @     0x7f86ef36b8a0  execute_native_thread_routine
Thu May 23 17:05:58 2019[1,10]<stdout>:    @     0x7f86f8d1c1c3  start_thread
Thu May 23 17:05:58 2019[1,10]<stdout>:    @     0x7f86f834412d  __clone
Thu May 23 17:05:58 2019[1,10]<stdout>:    @              (nil)  (unknown)

**Comment by frankwhzhang** [comment]
有没有详细一点的code和信息

**Comment by frankwhzhang** [comment]
参数超限了

**Comment by frankwhzhang** [comment]
问题已解决
