### ISSUE TITLE
py_func使用问题

### ISSUE THREAD

**Issue by xiangyubo** [PaddlePaddle/Paddle#17608]
paddle 1.3.2 版本，GPU 环境
我照着 py_func 的例子使用，就是一个简单的打印输入变量，但什么都没打印出来，不知道是哪里的问题
以下是我的代码片段

`
    def print_func(var):
        print("in py func type: {0}".format(type(var)))

	....
    # 定义输入数据的占位符 
    img = fluid.layers.data(name='img', shape=train_parameters['input_size'], dtype='float32') 
    label = fluid.layers.data(name='label', shape=[1], dtype='int64') 
    feeder = fluid.DataFeeder(feed_list=[img, label], place=place) 
 
    # 选取不同的网络 
    logger.info("build newwork") 
    model = AlexNet() 
    out = model.net(input=img, class_dim=train_parameters['class_dim'])
    new_out = create_tmp_var(name='new_out', dtype=out.dtype, shape=out.shape)
    fluid.layers.py_func(func=print_func, x=out, out=None)
    cost = fluid.layers.cross_entropy(new_out, label) 
    avg_cost = fluid.layers.mean(x=cost) 
    acc_top1 = fluid.layers.accuracy(input=out, label=label, k=1) 
    # 选取不同的优化器 
    optimizer = optimizer_rms_setting() 
`

**Comment by wangguibao** [comment]
这里有个打印tensor的例子

```
import paddle
import paddle.fluid as fluid
import numpy as np

def my_func(var):
    print var.lod()
    print var._dtype()
    print np.array(var)

word = fluid.layers.data(name='input', shape=[1], dtype='float32')

fluid.layers.Print(input=word)

fluid.layers.py_func(func=my_func, x=word, out=None)

place = fluid.CPUPlace()
exe = fluid.Executor(place)
exe.run(fluid.default_startup_program())
exe.run(fluid.default_main_program(), feed={"input": {1}})
```

**Comment by xiangyubo** [comment]
找到问题了，是我自己写的有问题，谢谢大家
