### ISSUE TITLE
import fluid提示找不到libcudart.so.9.0

### ISSUE THREAD

**Issue by zeyu-liu** [PaddlePaddle/Paddle#17603]
运行release版paddle，报错：
![image](https://user-images.githubusercontent.com/16282731/58251834-40ab1b80-7d97-11e9-8a07-656008bc745b.png)
已安装cuda-9.0，同时添加了环境变量:
`export LD_LIBRARY_PATH=/home/work/cuda-9.0/lib64/:/home/work/cudnn/cudnn_v7/cuda/lib64/:${PWD}/nccl_2.3.7-1+cuda9.0_x86_64/lib:$LD_LIBRARY_PATH`
仍报错

**Comment by zeyu-liu** [comment]
已解决，环境变量设置有误

**Comment by chensusu11** [comment]
Hi，请问您这个是怎么设置动态链接的哇？谢谢了
