### ISSUE TITLE
SE_ResNext_50_32x4d在训练的时候test_loss收敛不起来，test_acc1精度低

### ISSUE THREAD

**Issue by XiaoheYou** [PaddlePaddle/Paddle#17613]
SE_ResNext_50_32x4d在训练的时候训练集可以收敛，train_acc可以达到一个很高的值，但是test_loss收敛不起来，test_acc1精度低。将训练集和测试集设置成一样，依然存在这样的问题。 
同时用1.4代码评估了你们提供的预训练模型，结果Test_loss 7.03461, test_acc1 0.00076, test_acc5 0.00488。
测试环境：paddle:1.4.0-gpu-cuda9.0-cudnn7。

**Comment by qingqing01** [comment]
请问您使用验证集的label list来自哪里？

**Comment by XiaoheYou** [comment]
ImageNet下载的list

**Comment by qingqing01** [comment]
@XiaoheYou 之前有同学遇到过label list和我们 https://github.com/PaddlePaddle/models/blob/develop/PaddleCV/image_classification/data/ILSVRC2012/download_imagenet2012.sh 提供的不一样，您按照这个脚本提供的链接下载再试下吧:

```
wget http://paddle-imagenet-models.bj.bcebos.com/ImageNet_label.tgz

```

**Comment by XiaoheYou** [comment]
你提供的链接失效了。404 not found

**Comment by XiaoheYou** [comment]
使用了你们的label文件，eval的效果依旧几乎0

**Comment by shippingwang** [comment]
paddle 1.4.1
最新的models代码
1. 100类数据train
SeResNeXt50 train ImageNet**100**类

End pass 1, train_loss 2.87303, train_acc1 0.28167, train_acc5 0.58539, test_loss 2.50966, test_acc1 0.35064, test_acc5 0.66573

2. 1000类数据eval
eval 
![image](https://user-images.githubusercontent.com/13645332/58531228-2b5d4380-8214-11e9-8e9c-93971705290a.png)
![image](https://user-images.githubusercontent.com/13645332/58531243-3f08aa00-8214-11e9-8670-12b86d35420e.png)

麻烦检查下数据/预训练模型是否加载的进来什么的吧

**Comment by XiaoheYou** [comment]
问题已自己解决。
reader.py里process_image有段代码要修改：
![image](https://user-images.githubusercontent.com/28619328/58531585-69a73280-8215-11e9-95e5-0d0bea378b3d.png)
需要先对输入图片做resize再做crop，否则当输入图片宽高小于DATA_DIM的时候，train的数据会被padding而test的数据小于256也会被padding否则不会，这样会造成训练数据和测试数据不一致，因此testloss不收敛且test_acc值很低。而且不建议用resize_short短边resize。

**Comment by XiaoheYou** [comment]
已自己解决。
