### ISSUE TITLE
使用固定的CPU核数问题

### ISSUE THREAD

**Issue by ljayx** [PaddlePaddle/Paddle#17615]
- 版本、环境信息：
    1） PaddlePaddle版本：1.4.1
    2）CPU：96  Intel(R) Xeon(R) Gold 6271 CPU @ 2.60GHz
    3）系统环境：Docker Ubuntu 16.04.6 LTS (Host: centos6u3)
    4)   Python版本：3.6.7

- 问题描述：用 fluid python api 预测模型时，通过设置环境变量 `export MKL_NUM_THREADS=1` 和 `export OMP_NUM_THREADS=1`设置为单核预测，但是当我跑多进程时发现使用的CPU核数并非一个，而是使用了和进程数基本相同的数量。
如下图是`export MKL_NUM_THREADS=1` ， `export OMP_NUM_THREADS=1` 24进程时的top信息：
![image](https://user-images.githubusercontent.com/29032384/58299164-d46cfe00-7e10-11e9-809a-a3e8ec7ecda3.png)
IDLE=75, 这意思应该还是用了24核而非如环境变量所设置的单核。

请问这种通过环境变量设置固定核数的方法是否正确？
如何才能使用固定的核数？比如当我跑**单核24进程**时，24进程都跑在单核上，IDLE的值理论上应该接近99才对，而不是75。

谢谢！

**Comment by wangguibao** [comment]
搜了一下，https://stackoverflow.com/questions/30791550/limit-number-of-threads-in-numpy

In regards to doing this from within a python script as opposed to at the bash prompt, per this thread you can do the following (same commands as the answer above):

import os
os.environ["MKL_NUM_THREADS"] = "1" 
os.environ["NUMEXPR_NUM_THREADS"] = "1" 
os.environ["OMP_NUM_THREADS"] = "1" 
but you have to put that before you do import numpy. Apparently numpy only checks for this at import.

**Comment by wangguibao** [comment]
同时你top命令观察时可以按一下'1'，看一下CPU实际占用情况

**Comment by ljayx** [comment]
>import os
os.environ["MKL_NUM_THREADS"] = "1"
os.environ["NUMEXPR_NUM_THREADS"] = "1"
os.environ["OMP_NUM_THREADS"] = "1"

谢谢回复，这样的方式是可以的。如果都设置为1，单进程情况下，只占用一个核，多进程会各自独立占用每个核。

谢谢~
