### ISSUE TITLE
Why can't I “Have some google symbols”  

### ISSUE THREAD

**Issue by procr** [PaddlePaddle/Paddle#17621]
请问一下在编译paddle的v1.2.1这个版本
然后自己加了一个OP，报了这个错
![image](https://user-images.githubusercontent.com/5010880/58304707-f6be4600-7e27-11e9-9987-2e07ebb52679.png)

请问一下这个检查的目的是什么？

![image](https://user-images.githubusercontent.com/5010880/58304716-fcb42700-7e27-11e9-88ac-175bbea334b2.png)

**Comment by luotao1** [comment]
> Why can't I “Have some google symbols”

为了避免线上业务时，与其他版本中google symbols起冲突。

如果方便的话，可以贴OP出来看看。

**Comment by procr** [comment]
为了做GoogleNet的fusion，所以代码里面有google的字样。
除了把新增的OP当中的google字样替换掉之外，可以暂时把该check_symbol 脚本注释掉么？

**Comment by luotao1** [comment]
> 除了把新增的OP当中的google字样替换掉之外，

这个方法比较好。

> 可以暂时把该check_symbol 脚本注释掉么？

如果你只是自己本地用，也是可以的。
