### ISSUE TITLE
MPI训练打开Embedding层参数更新，训练报GRPC错误

### ISSUE THREAD

**Issue by lonelywinter340** [PaddlePaddle/Paddle#17628]
PaddleCloud Fluid 1.3.0

关掉embedding参数更新没有问题，打开embeding参数更新报下面的错误。
Fri May 24 14:58:03 2019[1,6]<stdout>:F0524 14:58:03.763126  6355 grpc_client.cc:418] GetRPC name:[emb_title.block2], ep:[10.90.102.22:62004], status:[-1] meets grpc error, error_code:14 error_message:Socket closed error_details:

**Comment by wangguibao** [comment]
已转内部多机issue跟进

**Comment by wangguibao** [comment]
多机issue，内部已修复。
