### ISSUE TITLE
Expected in_axis_dim % num == 0, but received in_axis_dim % num:1 != 0:0.

### ISSUE THREAD

**Issue by lizhiqings** [PaddlePaddle/Paddle#17620]
![wer](https://user-images.githubusercontent.com/47736115/58304266-22403100-7e26-11e9-8f63-02b00b8a7bd6.png)

输入batch 是四个 样本 每个 长度不一  但是进过 sequence_pool 应该变成 4x5 的 矩阵了吧 这样 还是不能 split 么

**Comment by wangguibao** [comment]
是compile time InferShape()失败了，原因是此时pool1的dim是[-1, 5]，按第一维切分会出现截图中提示的“除不尽”的问题

但是split一般不在第1维（batch那一维）做

跟用户解释后，用户接受并表示理解。
