### ISSUE TITLE
如何把一个二维矩阵转成tensor 或者lod tensor

### ISSUE THREAD

**Issue by yuanzfy** [PaddlePaddle/Paddle#17633]
目前在用fluid1.3，在模型中有一步操作是【模型的中间输出和一个单位矩阵进行逻辑运算】，单位矩阵的大小为batch_size*batch_size，现在不清楚该怎么生成这样一个等价于单位矩阵的tensor或者lodtendor。自己尝试使用create_lod_tensor后报类型错误。
单位矩阵lodtansor定义：
![image](https://user-images.githubusercontent.com/4515954/58318493-76f5a300-7e4a-11e9-8be8-a88ac8009dc5.png)
逻辑运算：
![image](https://user-images.githubusercontent.com/4515954/58318555-92f94480-7e4a-11e9-8c8a-90e305800be9.png)
逻辑运算报错：
![image](https://user-images.githubusercontent.com/4515954/58318571-9987bc00-7e4a-11e9-8829-f21bfa04a177.png)

之所以这么复杂，归根结底还是paddle对numpy运算的支持不够，很多numpy的api都没有，后续也希望能够继续增加这块的支持。

**Comment by yuanzfy** [comment]
POS_MASK = np.logical_not(np.identity(BATCH_SIZE))
pos_mask = fluid.create_lod_tensor(POS_MASK, recursive_seq_lens=[[batch_size]], place=fluid.CPUPlace())

p_valid_mask = fluid.layers.logical_and(p_valid_mask, pos_mask)

**Comment by yuanzfy** [comment]
刚才那个问题搞定了，用create_tensor + layers.assign就行，但是，新的问题来了，我自己生成的tensor，类型是3*3，而模型计算出来的向量，类型是-1*3，进行逻辑运算会报错dim不匹配
![image](https://user-images.githubusercontent.com/4515954/58323347-487dc500-7e56-11e9-81b8-ed7740452d86.png)
求帮忙看看！

**Comment by wangguibao** [comment]
我是这么写的

```
import paddle
import paddle.fluid as fluid
import numpy as np

BATCH_SIZE = 10

POS_MASK = np.logical_not(np.identity(BATCH_SIZE))

pos_mask = fluid.layers.data(name="POS_MASK", shape=[1], dtype='int')
neg_mask = fluid.layers.data(name="NEG_MASK", shape=[1], dtype='int')

fluid.layers.logical_and(x=pos_mask, y=neg_mask)

exe = fluid.executor.Executor(fluid.CPUPlace())
exe.run(fluid.default_startup_program())

left=fluid.create_lod_tensor(np.ndarray([4, 4], dtype=np.bool_), [[1, 1, 1, 1]], place=fluid.CPUPlace())
right=fluid.create_lod_tensor(np.ndarray([4, 4], dtype=np.bool_), [[1, 1, 1, 1]], place=fluid.CPUPlace())

exe.run(fluid.default_main_program(), feed={"POS_MASK": left, "NEG_MASK": right})

```

**Comment by yuanzfy** [comment]
我使用feed传入的方法也可以，我在测试的时候是这样写的，但是在生产环境下，使用py reader不知道该怎么传入，而且会有batch shuffle的操作，变换后就无法保证传入的矩阵是对角阵了
感觉paddle在【编译期】做的dim检查有点严，一个-1*3的和3*3的矩阵，是有可能能够匹配的

**Comment by yuanzfy** [comment]
举个具体的例子来说明下我的需求
假设现在batch_size = 3
通过qp_dot_product = fluid.layers.matmul(q_emb, p_emb, transpose_y=True)，能够得到一个3*3的矩阵，这时候我想把对角线的值全部置为0

**Comment by wangguibao** [comment]
经过了解，py reader场景下确实还不支持，建议暂时用同步feed接口。

用户表示理解。
