### ISSUE TITLE
paddle fluid 1.4的im2sequence op传入的padding参数错误，导致padding无法生效

### ISSUE THREAD

**Issue by beacandler** [PaddlePaddle/Paddle#17649]
1. paddlepaddle版本号：
          pip install paddlepaddle-gpu==1.4.0.post87
2. 出现的问题：
          
![image](https://user-images.githubusercontent.com/33446789/58363788-5a09b000-7edc-11e9-9ebf-8f915d7669d7.png)
如图，无论padding的参数设置成多少，均不起作用，导致后续的网络无法训练

3. 问题排查：
     1. paddle官方代码：
![image](https://user-images.githubusercontent.com/33446789/58363805-91785c80-7edc-11e9-881c-242b7fcc6842.png)
地址：https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/fluid/operators/im2sequence_op.h#L50
发现后台确实将paddings参数读入进去。

       2. paddle python warper代码

![image](https://user-images.githubusercontent.com/33446789/58363818-be2c7400-7edc-11e9-87af-5d90bb3f8636.png)
地址：~/lib/python2.7/site-packages/paddle/fluid/layers/nn.py
         发现问题，传入的是padding，而不是paddings，所以导致后台无法辨认，修复上述问题后，im2seq的padding参数可以正常使用

**Comment by beacandler** [comment]
请paddle同学尽快确认上述bug，并且修正，因为需要在集群上运行

**Comment by gavin1332** [comment]
> 请paddle同学尽快确认上述bug，并且修正，因为需要在集群上运行

感谢宝贵意见，已反馈。
临时解决方案可以将本地编译的whl包上传hdfs thirdparty路径，然后在before_hook.sh里执行安装操作
