### ISSUE TITLE
Fix gather op grad calc bug when has same index#17662 

### ISSUE THREAD

**Issue by wawltor** [PaddlePaddle/Paddle#17663]
The gather op has indices input，when the indices has same index, calculate the grad has a bug，just use overwrite mode to calculate the same index grad,  fix this bug using the accumulate mode to calculate the same index grad. At the same time, using the lib of open-blas and eigen  to optimize the time cost in accumulate mode

**Comment by shippingwang** [comment]
pls write this good comments in the #17662 or cite it
