### ISSUE TITLE
为什么设置变量的属性为persitable会影响训练的结果？

### ISSUE THREAD

**Issue by dashulu** [PaddlePaddle/Paddle#17670]
两次训练，一次把变量全部设为persistable， 另外一个部分设为persistable， 训练数据和模型都一样，数据也没有shuffle， 为什么结果会不一样。

**Comment by dashulu** [comment]
另外，训练到第n个batch之后，把参数保存下来，然后训练第n+1个batch，为什么结果与加载保存下来的参数，训练第n+1个batch的结果不一样？

**Comment by shippingwang** [comment]
> 两次训练，一次把变量全部设为persistable， 另外一个部分设为persistable， 训练数据和模型都一样，数据也没有shuffle， 为什么结果会不一样。

应该是显存复用影响了，对于不想被显存复用的变量设置persistable=True

> 另外，训练到第n个batch之后，把参数保存下来，然后训练第n+1个batch，为什么结果与加载保存下来的参数，训练第n+1个batch的结果不一样？

用的是什么save? resume 再训练 用save_persistable和load_persistable

**Comment by dashulu** [comment]
> 该是显存复用影响了，对于不想被显存复用的变量设置persistable=True

为什么显存复用会影响训练结果？
