### ISSUE TITLE
ernie训练之后预测时报错 Enforce failed. Expected numel() * SizeOfType(type()) <= memory_size(), but received numel() * SizeOfType(type()):57492480 > memory_size():17915904.

### ISSUE THREAD

**Issue by baiyanan-kate** [PaddlePaddle/Paddle#17676]
![image](https://user-images.githubusercontent.com/23547727/58423656-30ad7780-80c8-11e9-8f83-2c52c6d41c6e.png)
![image](https://user-images.githubusercontent.com/23547727/58424276-aa923080-80c9-11e9-9e44-8a132e9fd6e1.png)

![image](https://user-images.githubusercontent.com/23547727/58446953-4e64f600-8135-11e9-8157-d08177adc28b.png)
![image](https://user-images.githubusercontent.com/23547727/58446961-50c75000-8135-11e9-8614-8a84b504758d.png)
http://yq01-sys-hic-v100-box-a225-0062.yq01.baidu.com:8388/v1/slurmjobs/38589/joblog

**Comment by kuke** [comment]
Closed because it is fixed in release 1.5
