### ISSUE TITLE
sequence_unpad 在训练过程中内存报错

### ISSUE THREAD

**Issue by thomas010** [PaddlePaddle/Paddle#17685]
问题描述：sequence_unpad 在训练过程中内存报错

版本、环境信息：
    1）Paddle1.4
    2）GPU：p40，cuda8.0, cudnn7

复现信息：
1. 使用sequence_unpad将固定shape的tensor转成sequence类型
2. 然后输入到dynamic_lstm进行处理

相关代码
`    # input shape [-1, lenth, feature_size]
    seq_lenth = fluid.layers.fill_constant_batch_size_like(input, shape=[-1,1], value=input.shape[1], dtype='int64')
    seq_input = fluid.layers.sequence_unpad(x=input, length=seq_lenth)

    fc0 = fluid.layers.fc(
            input=seq_input, 
            size=hidden_size * 3,
            param_attr=fluid.ParamAttr(name=name+"_fc0.w"), 
            bias_attr=False
            )
    gru_h = fluid.layers.dynamic_gru(
            input=fc0, 
            size=hidden_size, 
            is_reverse=False, 
            param_attr=fluid.ParamAttr(name=name+"_gru.w"), 
            bias_attr=fluid.ParamAttr(name=name+"_gru.b")
            )
    rgru_h = fluid.layers.dynamic_gru(
            input=fc0, 
            size=hidden_size, 
            is_reverse=True, 
            param_attr=fluid.ParamAttr(name=name+"_rgru.w"), 
            bias_attr=fluid.ParamAttr(name=name+"_rgru.b")
            )

    hidden_states = fluid.layers.concat(input=[gru_h, rgru_h], axis=1)
    pool_rep = fluid.layers.sequence_pool(input=hidden_states, pool_type=pool_type)
    pool_rep = fluid.layers.fc(
            input=pool_rep, 
            size=output_fize,
            param_attr=fluid.ParamAttr(name=name+"_fc_pool.w"), 
            bias_attr=fluid.ParamAttr(name=name+"_fc_pool.b")
            )`
错误情况：运行过程中（第二个epoch）内存报错，错误信息如下：
![image](https://user-images.githubusercontent.com/7474360/58449510-655c1600-813e-11e9-961a-ac36f2cccb93.png)

**Comment by heavengate** [comment]
看报错是sequence_unpad里申请新tensor的shape太大，sequence_unpad op中只申请了一个out的tensor，该tensor的shape是[x_shape[0] * x_shape[1], x_shape[2], x_shape[3] ....]， 麻烦确认一下是不是sequence_unpad的input shape太大的原因

**Comment by thomas010** [comment]
sequence_unpad的input shape都是固定的[16 ， 3， 2048]，训练过程中间报错，需要内存跟input shape也不match，感觉不会是input shape问题
Enforce failed. Expected numel() * SizeOfType(type()) <= memory_size(), but received numel() * SizeOfType(type()):72712219978063872 > memory_size():393216

**Comment by heavengate** [comment]
input shape没问题的话，可能是dtype的问题，reader里面读入的数据在yield之前请调用一下`astype('float32')`指定dtype，确保训练过程中dtype一致，有可能是训练过程中reader读入的dtype不一致的问题

**Comment by thomas010** [comment]
reader里面已经用astype('float32')做了类型转化的

**Comment by heavengate** [comment]
imgs 做-= /= 操作的dtype有可能会变的，可以在return的时候astype试下

**Comment by thomas010** [comment]
reader部分return的时候都做了astype转换，依旧报同样错误，可以排除dtype问题

**Comment by heavengate** [comment]
1.4版本sequence unpad有问题，在定位中，可以使用1.3版本试一下

**Comment by thomas010** [comment]
试了下1.3版本（1.2-1.4都试过），仍出现同样错误

**Comment by kuke** [comment]
Fixed by https://github.com/PaddlePaddle/Paddle/pull/17984

**Comment by tianxin1860** [comment]
使用 paddle-latest 版本训练，出现了同样的报错，报错详情如下:
![image](https://user-images.githubusercontent.com/6829601/59678996-54b03480-9200-11e9-8606-57b1ceb8f73d.png)
