### ISSUE TITLE
cmake 如何指定-O2

### ISSUE THREAD

**Issue by xjqbest** [PaddlePaddle/Paddle#17686]
cmake 如何指定-O2

目前我是这样编译的
```
cmake -DCMAKE_INSTALL_PREFIX=./output/ -DCMAKE_BUILD_TYPE=Release -DWITH_PYTHON=ON -DWITH_MKL=OFF -DWITH_GPU=OFF -DWITH_FLUID_ONLY=ON -DPYTHON_INCLUDE_DIR=$PYTHONROOT/include/python2.7/ -DPYTHON_LIBRARY=$PYTHONROOT/lib/libpython2.7.so -DPYTHON_EXECUTABLE=$PYTHONROOT/bin/python2.7 -DWITH_PSLIB=ON   ..
```

**Comment by heavengate** [comment]
可以修改一下cmake file
https://github.com/PaddlePaddle/Paddle/blob/962eed6f827090c84ac92f0ee28fa612aa836f70/cmake/coveralls.cmake#L66

**Comment by xjqbest** [comment]
> 可以修改一下cmake file
> https://github.com/PaddlePaddle/Paddle/blob/962eed6f827090c84ac92f0ee28fa612aa836f70/cmake/coveralls.cmake#L66

请问需要把paddle/cmake/目录下的所有文件都这样改一下么

**Comment by heavengate** [comment]
> > 可以修改一下cmake file
> > https://github.com/PaddlePaddle/Paddle/blob/962eed6f827090c84ac92f0ee28fa612aa836f70/cmake/coveralls.cmake#L66
> 
> 请问需要把paddle/cmake/目录下的所有文件都这样改一下么

修改CMakeList.txt中即可
https://github.com/PaddlePaddle/Paddle/blob/962eed6f827090c84ac92f0ee28fa612aa836f70/CMakeLists.txt#L246
