### ISSUE TITLE
使用fluid.ParallelExecutor内存报错

### ISSUE THREAD

**Issue by zhouxc** [PaddlePaddle/Paddle#17684]
![image](https://user-images.githubusercontent.com/1280621/58449495-55443680-813e-11e9-9f70-1f639bb8c79f.png)
![image](https://user-images.githubusercontent.com/1280621/58449503-5e350800-813e-11e9-92a2-17dd6bdb0434.png)

**Comment by heavengate** [comment]
麻烦把报错信息截全一些，看一下调用栈在哪个op，应该是哪个op里面没有满足posix_memalign(&p, 4096ul, size) == 0的检验

**Comment by zhouxc** [comment]
![image](https://user-images.githubusercontent.com/1280621/58449787-ca177080-813e-11e9-9b23-e479476049a8.png)
![image](https://user-images.githubusercontent.com/1280621/58449814-e1eef480-813e-11e9-9cce-1dc51247309e.png)
![image](https://user-images.githubusercontent.com/1280621/58449840-eadfc600-813e-11e9-8e57-4490e4a707a7.png)

**Comment by heavengate** [comment]
cross_enttropy 有内存泄漏的bug于20天前修复，请使用Paddle develop编译版本或使用latest whl包
https://github.com/PaddlePaddle/Paddle/issues/17232

**Comment by zhouxc** [comment]
模型太大 已解决
