### ISSUE TITLE
稀疏特征 fulid版本api

### ISSUE THREAD

**Issue by AWSWXY** [PaddlePaddle/Paddle#17683]
稀疏矩阵fluid版本api

**Comment by AWSWXY** [comment]
输入形式为：1 32 64 512 10232
程度不固定，如何读入数据

**Comment by heavengate** [comment]
参考 https://github.com/PaddlePaddle/models/blob/061b58e27c5fd4f7dba36444f68b68725432ff2b/PaddleRec/ctr/reader.py#L5
