### ISSUE TITLE
预测c++实现时出现core

### ISSUE THREAD

**Issue by ylxsyf** [PaddlePaddle/Paddle#17699]
c++实现预测模型（CNN）出现core：
1)单线程正常运行
2)多线程出core，core的信息如下：
![image](https://user-images.githubusercontent.com/5714337/58481485-0c689e00-818f-11e9-82bc-d6fb6bd9f3cc.png)
实现方式：predictor全局变量，多线程调用predictor->run()函数

**Comment by heavengate** [comment]
多线程实现不能共用predictor，每个线程创建自己堵路的predictor，参考http://paddlepaddle.org/documentation/docs/zh/1.4/advanced_usage/deploy/inference/native_infer.html 数据并行的服务

**Comment by ylxsyf** [comment]
> 多线程实现不能共用predictor，每个线程创建自己堵路的predictor，参考http://paddlepaddle.org/documentation/docs/zh/1.4/advanced_usage/deploy/inference/native_infer.html 数据并行的服务

线程之间的predictor是安全的吗？

**Comment by heavengate** [comment]
> > 多线程实现不能共用predictor，每个线程创建自己堵路的predictor，参考http://paddlepaddle.org/documentation/docs/zh/1.4/advanced_usage/deploy/inference/native_infer.html 数据并行的服务
> 
> 线程之间的predictor是安全的吗？

线程之间的predictor不在一个线程里，是安全的
