### ISSUE TITLE
使用fluid.metrics.Precision()，调用update的时候报错，ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

### ISSUE THREAD

**Issue by Melonzhou** [PaddlePaddle/Paddle#17693]
为使您的问题得到快速解决，在建立Issues前，请您先通过如下方式搜索是否有相似问题:【搜索issue关键字】【使用labels筛选】【官方文档】

如果您没有查询到相似问题，为快速解决您的提问，建立issue时请提供如下细节信息：
- 标题：简洁、精准概括您的问题，例如“Insufficient Memory xxx" ”
- 版本、环境信息：
    1）PaddlePaddle版本：1.3.0.post97
    2）GPU：K40,10G显存，CUDA-8.0和CUDNN-V6
    3）系统环境：python2.7
- 训练信息
    1）单机单卡
-报错信息
 使用fluid.metrics.Precision()，调用update的时候报错。
![image](https://user-images.githubusercontent.com/5926307/58463347-3a85b800-8166-11e9-99c8-a921cbadfbba.png)
对应的，site-packages/paddle/fluid/metrics.py中的代码为下图
![image](https://user-images.githubusercontent.com/5926307/58463402-58ebb380-8166-11e9-9f7d-61d1a3971e9a.png)
使用代码
![image](https://user-images.githubusercontent.com/5926307/58463428-699c2980-8166-11e9-9d96-523846faaf70.png)

**Comment by heavengate** [comment]
pred应该是和label相同shape，是一个[N, 1]的array，只需要保留预测为True的概率就可以了，可以按照你的代码逻辑选取pred其中一列传入

**Comment by Melonzhou** [comment]
只保留预测为ture的概率之后，不会报错了，但是计算出来的值有点奇怪啊，precision不是0就是1，我用sk-learn计算出来的值看着就挺正常。
![image](https://user-images.githubusercontent.com/5926307/58464927-2db69380-8169-11e9-8506-5208171cbe97.png)

**Comment by heavengate** [comment]
确认了下precision代码，麻烦做如下修改尝试：
1. 输入的shape [N, 1] reshape成[N]
2. label 调用一下astype('int32')

**Comment by Melonzhou** [comment]
辛苦再看下，绿框中的是我的修改，结果和之前一样，不是0就是1
![image](https://user-images.githubusercontent.com/5926307/58466584-83d90600-816c-11e9-8866-9ceb46c1be51.png)
![image](https://user-images.githubusercontent.com/5926307/58466618-92bfb880-816c-11e9-8f4d-a9b71b14a1db.png)
