### ISSUE TITLE
预测c++实现时出现core

### ISSUE THREAD

**Issue by ylxsyf** [PaddlePaddle/Paddle#17698]
c++实现预测（CNN）
单线程正确
多线程出core，core的信息如下：
![image](https://user-images.githubusercontent.com/5714337/58481384-d7f4e200-818e-11e9-8690-b05c60a9f290.png)
实现方法：predictor全局变量，多线程调用predictor->run()函数

**Comment by heavengate** [comment]
重复issue，在https://github.com/PaddlePaddle/Paddle/issues/17699 中跟进
