### ISSUE TITLE
c++预测测试出内存泄露

### ISSUE THREAD

**Issue by ylxsyf** [PaddlePaddle/Paddle#17704]
c++实现模型预测（CNN）：
利用valgrind进行测试，发现paddle的内部代码有爆出内存泄露，具体如下：
![image](https://user-images.githubusercontent.com/5714337/58485852-64a39e00-8197-11e9-9498-2881bad83691.png)

**Comment by fc500110** [comment]
用的哪个版本？

**Comment by ylxsyf** [comment]
> 用的哪个版本？

我用paddle@v1.3.0_pb32@git_branch 和paddle@v1.2.0_pb32@git_branch 都出现这个问题了。

**Comment by Superjomn** [comment]
可以忽略，里面有个误报。
