### ISSUE TITLE
SSD训练自定义样本集报错

### ISSUE THREAD

**Issue by dreamonezero** [PaddlePaddle/Paddle#17728]
1）PaddlePaddle版本：1.4.1
    3）NVIDIA GT730  CUDA9.0+CUDNN7.0
    4）系统环境：win10专业版 python3.7
- 训练信息
    1）单机，单卡

devices_num: 1
batch_size: 2 epoc_num: 120 batch_size_per_device: 2
class_num: 2
class_num: 2
W0529 19:28:03.713282 23548 device_context.cc:261] Please NOTE: device: 0, CUDA Capability: 35, Driver API Version: 9.1, Runtime API Version: 8.0
W0529 19:28:03.720264 23548 device_context.cc:269] device: 0, cuDNN Version: 7.0.
Epoc 0, batch 0, loss 30.892044, time 0.00100
Epoc 0, batch 10, loss 14.349803, time 0.39893
Epoc 0, batch 20, loss 17.970669, time 0.38397
Batch 0, map [0.]
Batch 10, map [0.]
Batch 20, map [0.]
Batch 30, map [0.]
Batch 40, map [0.]
Epoc 0, test map 0.0
Best test map 0.0
save models to model\0
Epoc 1, batch 0, loss 15.596876, time 0.00000
Epoc 1, batch 10, loss 13.237637, time 0.40193
Epoc 1, batch 20, loss 11.892453, time 0.38597
Epoc 2, batch 0, loss 18.011284, time 0.00100
Epoc 2, batch 10, loss 6.392341, time 0.46875
Epoc 2, batch 20, loss 11.551768, time 0.38697
Epoc 3, batch 0, loss 8.948514, time 0.00100
Epoc 3, batch 10, loss 7.487110, time 0.39395
Epoc 3, batch 20, loss 10.909262, time 0.45678
Epoc 4, batch 0, loss 6.537111, time 0.00000
Epoc 4, batch 10, loss 6.392653, time 0.38597
Epoc 4, batch 20, loss 12.555858, time 0.38397
Epoc 5, batch 0, loss 8.214245, time 0.00100
Epoc 5, batch 10, loss 3.444009, time 0.39893
Epoc 5, batch 20, loss 3.268178, time 0.38397
Epoc 6, batch 0, loss 8.844184, time 0.00100
Epoc 6, batch 10, loss 5.565411, time 0.38896
Epoc 6, batch 20, loss 5.621006, time 0.38796
Epoc 7, batch 0, loss 8.129871, time 0.00000
Epoc 7, batch 10, loss 5.115551, time 0.47074
Epoc 7, batch 20, loss 10.151852, time 0.38697
Epoc 8, batch 0, loss 2.773974, time 0.00100
Epoc 8, batch 10, loss 17.428673, time 0.40990
Epoc 8, batch 20, loss 11.854261, time 0.37998
Epoc 9, batch 0, loss 9.003402, time 0.00000
Epoc 9, batch 10, loss 5.343739, time 0.38697
Epoc 9, batch 20, loss 7.956851, time 0.38497
Epoc 10, batch 0, loss 4.034008, time 0.00000
Epoc 10, batch 10, loss 7.442851, time 0.41689
Epoc 10, batch 20, loss 5.388234, time 0.45578
Batch 0, map [0.]
Traceback (most recent call last):
  File "train.py", line 352, in <module>
    main()
  File "train.py", line 348, in main
    val_file_list=val_file_list)
  File "train.py", line 285, in train
    best_map, mean_map = test(epoc_id, best_map)
  File "train.py", line 233, in test
    test_map, = exe.run(test_prog, fetch_list=[accum_map])
  File "D:\work\PaddlePaddle\venv\lib\site-packages\paddle\fluid\executor.py", line 565, in run
    use_program_cache=use_program_cache)
  File "D:\work\PaddlePaddle\venv\lib\site-packages\paddle\fluid\executor.py", line 642, in _run
    exe.run(program.desc, scope, 0, True, True, fetch_var_name)
paddle.fluid.core.EnforceNotMet: Invoke operator detection_map error.
Python Callstacks:
  File "D:\work\PaddlePaddle\venv\lib\site-packages\paddle\fluid\framework.py", line 1654, in append_op
    attrs=kwargs.get("attrs", None))
  File "D:\work\PaddlePaddle\venv\lib\site-packages\paddle\fluid\layer_helper.py", line 43, in append_op
    return self.main_program.current_block().append_op(*args, **kwargs)
  File "D:\work\PaddlePaddle\venv\lib\site-packages\paddle\fluid\layers\detection.py", line 797, in detection_map
    'class_num': class_num,
  File "D:\work\PaddlePaddle\venv\lib\site-packages\paddle\fluid\metrics.py", line 655, in __init__
    ap_version=ap_version)
  File "train.py", line 130, in build_program
    ap_version=ap_version)
  File "train.py", line 186, in train
    is_train=False)
  File "train.py", line 348, in main
    val_file_list=val_file_list)
  File "train.py", line 352, in <module>
    main()
C++ Callstacks:
Enforce failed. Expected det_dims[1] == 6UL, but received det_dims[1]:1 != 6UL:6.
The shape is of Input(DetectRes) [N, 6]. at [D:\1.4.1\paddle\paddle\fluid\operators\detection_map_op.cc:49]
PaddlePaddle Call Stacks:
Windows not support stack backtrace yet.

**Comment by fc500110** [comment]
输入数据shape有问题吧？

**Comment by dreamonezero** [comment]
数据是灰度图，请问下有灰度图应如何处理才能用，预训练模型是ssd_mobilenet_v1_coco，数据集是自定义数据集，按照pascalvoc格式来的

**Comment by dreamonezero** [comment]
im = Image.open(image_path)
            if im.mode == 'L':
               im = im.convert('RGB')

代码中有转换，输入shape是3

**Comment by yeyupiaoling** [comment]
@dreamonezero 写一个脚步清除错误的图片吧。可能是这个问题呢

**Comment by dreamonezero** [comment]
是label_list的问题，background需要是0，要和detection_output中background_label=0一致
