### ISSUE TITLE
externals/any repo失效

### ISSUE THREAD

**Issue by dancingpipi** [PaddlePaddle/Paddle#17721]
使用1.2版本，在docker环境下进行源码编译：
https://github.com/PaddlePaddle/any.git 
这个repo已经失效，请提供一个新的repo

**Comment by junjun315** [comment]
您好，我看这个repo是可以使用的，只是变成只读了。请问为什么还需要这个版本呢？

**Comment by fc500110** [comment]
建议参考修改一下编译选项
https://github.com/PaddlePaddle/Paddle/pull/15813/commits/c797a1f050a8f1a7c75de58aba5d387c803d678f

**Comment by luotao1** [comment]
@z13974509906 这个repo在今天上午已经恢复了，请重新试下，谢谢！
