### ISSUE TITLE
Tensor holds the wrong type, it holds float at [/home/teamcity/work/ef54dc8a5b211854/paddle/fluid/framework/tensor_impl.h:29]

### ISSUE THREAD

**Issue by Melonzhou** [PaddlePaddle/Paddle#17723]
为使您的问题得到快速解决，在建立Issues前，请您先通过如下方式搜索是否有相似问题:【搜索issue关键字】【使用labels筛选】【官方文档】

如果您没有查询到相似问题，为快速解决您的提问，建立issue时请提供如下细节信息：
- 标题：简洁、精准概括您的问题，例如“Insufficient Memory xxx" ”
- 版本、环境信息：
    1）PaddlePaddle版本：请提供您的PaddlePaddle版本号，例如1.1或CommitID
    2）CPU：预测若用CPU，请提供CPU型号，MKL/OpenBlas/MKLDNN/等数学库使用情况
    3）GPU：预测若用GPU，请提供GPU型号、CUDA和CUDNN版本号
    4）系统环境：请您描述系统类型、版本，例如Mac OS 10.14，Python版本
- 训练信息
    1）单机/多机，单卡/多卡
    2）显存信息
    3）Operator信息
- 复现信息：如为报错，请给出复现环境、复现步骤
- 问题描述：请详细描述您的问题，同步贴出报错信息、日志、可复现的代码片段

Thank you for contributing to PaddlePaddle.
Before submitting the issue, you could search issue in the github in case that there was a similar issue submitted or resolved before.
If there is no solution,please make sure that this is a training issue including the following details:
**System information**
-PaddlePaddle version （eg.1.1）or CommitID
-CPU: including CPUMKL/OpenBlas/MKLDNN version
-GPU: including CUDA/CUDNN version
-OS Platform (eg.Mac OS 10.14)
-Other imformation: Distriuted training/informantion of operator/
Graphics card storage
**To Reproduce**
Steps to reproduce the behavior
**Describe your current behavior**
**Code to reproduce the issue**
**Other info / logs**
`def create_model(pyreader_name):
    print('create model in run_custom.py')
    py_reader, list = custom_encoder_tensor(cfg, pyreader_name)
    data = list[0]
    label = list[1]
    data_mask = list[2]
    data_lens = list[3]

    # demo code
    # config = Config()
    dict_dim = 3823
    emb_dim = 128
    hid_dim = 20
    hid_dim2 = 20
    class_dim = cfg.class_dim
    win_size = 3

    unpad_data = fluid.layers.sequence_unpad(data, length=data_lens)
    print("data.shape = ", data.shape)
    print("label.shape = ", label)
    print("unpad.shape = ", unpad_data.shape)

    emb = fluid.layers.embedding(input=unpad_data, size=[dict_dim, emb_dim])

    conv = fluid.nets.sequence_conv_pool(
        input=emb,
        num_filters=hid_dim,
        filter_size=win_size,
        act="tanh",
        pool_type="max")

    # full connect layer
    fc_1 = fluid.layers.fc(input=[conv], size=hid_dim2)

    # softmax layer
    prediction = fluid.layers.fc(input=[fc_1], size=class_dim, act="softmax")
    fluid.layers.Print(prediction)

    cost = fluid.layers.cross_entropy(input=prediction, label=label)
    avg_cost = fluid.layers.mean(x=cost)
    num_seqs = fluid.layers.create_tensor(dtype='int64')
    acc = fluid.layers.accuracy(input=prediction, label=label, total=num_seqs)

`
prediction打印出来的数据如下L：
`2019-05-29 17:47:42,978-DEBUG: file being processed:./train_data/custom/adv_train_id
1559123262              Tensor[fc_1.tmp_2]
        shape: [2,2,]
        dtype: f
        data: 0.502986,0.497014,0.515373,0.484627,
1559123263              Tensor[fc_1.tmp_2]
        shape: [2,2,]
        dtype: f
        data: 0.511956,0.488044,0.503456,0.496544,
1559123263              Tensor[fc_1.tmp_2]
        shape: [2,2,]
        dtype: f
        data: 0.522002,0.477998,0.518964,0.481036,
1559123263              Tensor[fc_1.tmp_2]
        shape: [2,2,]
        dtype: f
        data: 0.503166,0.496834,0.526349,0.473651,`

**Comment by Melonzhou** [comment]
补充一下环境信息和错误日志
* 版本、环境信息：    1）PaddlePaddle版本：1.3.0.post97    2）GPU：K40,10G显存，CUDA-8.0和CUDNN-V6    3）系统环境：python2.7
* 训练信息    1）单机单卡 
错误日志：
Traceback (most recent call last):
  File "run_custom.py", line 108, in <module>
    model.train()
  File "/Users/baidu/workspace/kkk/baidu/nlpc/nlpt-strategy/strategy/model/base_model.py", line 287, in train
    self.train_exe.run(fetch_list=[])
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/paddle/fluid/parallel_executor.py", line 205, in run
    return_numpy=return_numpy)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/paddle/fluid/executor.py", line 580, in run
    return_numpy=return_numpy)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/paddle/fluid/executor.py", line 446, in _run_parallel
    exe.run(fetch_var_names, fetch_var_name)
paddle.fluid.core.EnforceNotMet: Invoke operator cross_entropy2 error.
Python Callstacks: 
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/paddle/fluid/framework.py", line 1654, in append_op
    attrs=kwargs.get("attrs", None))
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/paddle/fluid/layer_helper.py", line 43, in append_op
    return self.main_program.current_block().append_op(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/paddle/fluid/layers/nn.py", line 1497, in cross_entropy2
    attrs={'ignore_index': ignore_index})
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/paddle/fluid/layers/nn.py", line 1472, in cross_entropy
    return cross_entropy2(input, label, ignore_index)
  File "run_custom.py", line 80, in create_model
    cost = fluid.layers.cross_entropy(input=prediction, label=label)
  File "/Users/baidu/workspace/kkk/baidu/nlpc/nlpt-strategy/strategy/model/base_model.py", line 84, in wrapper
    pyreader, graph_vars = create_net(*config, **kwconfig)
  File "/Users/baidu/workspace/kkk/baidu/nlpc/nlpt-strategy/strategy/model/base_model.py", line 166, in define_train_program
    self.train_pyreader, self.graph_vars = create_net(pyreader_name="train_reader")
  File "/Users/baidu/workspace/kkk/baidu/nlpc/nlpt-strategy/strategy/model/base_model.py", line 124, in build_program
    self.define_train_program()
  File "/Users/baidu/workspace/kkk/baidu/nlpc/nlpt-strategy/strategy/model/base_model.py", line 62, in __init__
    self.build_program()
  File "run_custom.py", line 107, in <module>
    model = CustomModel(cfg, create_model)
C++ Callstacks: 
Tensor holds the wrong type, it holds float at [/home/teamcity/work/ef54dc8a5b211854/paddle/fluid/framework/tensor_impl.h:29]
PaddlePaddle Call Stacks: 
0          0x11e1c93dcp void paddle::platform::EnforceNotMet::Init<char const*>(char const*, char const*, int) + 636
1          0x11e1c910bp paddle::platform::EnforceNotMet::EnforceNotMet(std::exception_ptr, char const*, int) + 139
2          0x11e213857p long long const* paddle::framework::Tensor::data<long long>() const + 247
3          0x11e73861cp paddle::operators::CrossEntropyOpKernel2<paddle::platform::CPUDeviceContext, float>::Compute(paddle::framework::ExecutionContext const&) const + 348
4          0x11e738480p std::__1::__function::__func<paddle::framework::OpKernelRegistrarFunctor<paddle::platform::CPUPlace, false, 0ul, paddle::operators::CrossEntropyOpKernel2<paddle::platform::CPUDeviceContext, float>, paddle::operators::CrossEntropyOpKernel2<paddle::platform::CPUDeviceContext, double> >::operator()(char const*, char const*, int) const::'lambda'(paddle::framework::ExecutionContext const&), std::__1::allocator<paddle::framework::OpKernelRegistrarFunctor<paddle::platform::CPUPlace, false, 0ul, paddle::operators::CrossEntropyOpKernel2<paddle::platform::CPUDeviceContext, float>, paddle::operators::CrossEntropyOpKernel2<paddle::platform::CPUDeviceContext, double> >::operator()(char const*, char const*, int) const::'lambda'(paddle::framework::ExecutionContext const&)>, void (paddle::framework::ExecutionContext const&)>::operator()(paddle::framework::ExecutionContext const&) + 32
5          0x11f3bad41p paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&, paddle::framework::RuntimeContext*) const + 865
6          0x11f3ba95cp paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&) const + 300
7          0x11f3b6b25p paddle::framework::OperatorBase::Run(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&) + 357
8          0x11f23df7fp std::__1::__function::__func<paddle::framework::details::ComputationOpHandle::RunImpl()::$_0, std::__1::allocator<paddle::framework::details::ComputationOpHandle::RunImpl()::$_0>, void ()>::operator()() + 111
9          0x11f23d9f3p paddle::framework::details::ComputationOpHandle::RunImpl() + 195
10         0x11f1a3248p paddle::framework::details::ThreadedSSAGraphExecutor::RunOp(std::__1::shared_ptr<paddle::framework::BlockingQueue<paddle::framework::details::VarHandleBase*> > const&, paddle::framework::details::OpHandleBase*)::$_2::operator()() const + 408
11         0x11f1a6fc9p std::__1::packaged_task<void ()>::operator()() + 73
12         0x11e29e21ap ThreadPool::ThreadPool(unsigned long)::'lambda'()::operator()() const + 522
13         0x11e29df9dp std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, ThreadPool::ThreadPool(unsigned long)::'lambda'()> >(void*, void*) + 45
14      0x7fffc07fd93bp _pthread_body + 180
15      0x7fffc07fd887p _pthread_body + 0
16      0x7fffc07fd08dp thread_start + 13

**Comment by Melonzhou** [comment]
我的label和predict对应的类型和shape如下：
![image](https://user-images.githubusercontent.com/5926307/58607622-f06e1500-82d2-11e9-9d1d-d4c04430ebf4.png)
![image](https://user-images.githubusercontent.com/5926307/58607626-f532c900-82d2-11e9-97ab-d8be55e62a68.png)

**Comment by JiaXiao243** [comment]
有个类似的issue [#17462](https://github.com/PaddlePaddle/Paddle/issues/17462)，numpy在win下是用int类型，在linux下用的是int64。请问是windows环境吗？float可能是同样的问题。

**Comment by Melonzhou** [comment]
linux环境下的

**Comment by Melonzhou** [comment]
感谢paddle同学，原因查到了，label的数据类型应该是int64才对，但是在组batch的时候不小心给转成字符了。
![image](https://user-images.githubusercontent.com/5926307/58620358-7a30d900-82f9-11e9-8e5f-dd220ae8cdfb.png)
变成下面这样就好了
![image](https://user-images.githubusercontent.com/5926307/58620420-9f254c00-82f9-11e9-9541-5ce027434517.png)

**Comment by junjun315** [comment]
fluid.layers.cross_entropy(input=prediction, label=label)
这个op强制要求label输入类型为int64
