### ISSUE TITLE
fleet role maker isinstance check does not work with py2.7

### ISSUE THREAD

**Issue by lzha106** [PaddlePaddle/Paddle#17735]
- 版本、环境信息：
    1）PaddlePaddle版本：PaddlePaddle Docker latest （0529 日）
    2）CPU：是
    3）GPU：否
    4）系统环境：ubuntu 16.04，Python 2.7.12,   enum-0.4.7
- 训练信息
    1）单机/多机：单机分布式
    2）代码：https://github.com/PaddlePaddle/Paddle/tree/develop/python/paddle/fluid/incubate/fleet/tests
- 复现信息：在以上容器环境下运行 fleet tests
- 问题描述：
      File "/usr/local/lib/python2.7/dist-packages/paddle/fluid/incubate/fleet/base/role_maker.py", line 316, in __init__
    raise TypeError("role must be as Role")
TypeError: role must be as Role

**Comment by seiriosPlus** [comment]
fix #17736

**Comment by lzha106** [comment]
#17736  can't fix the issue, as in py27, Enum is not a instance, and line 316 will always fail on  isinstance(role, Role) check. 

No idea if a good way to make the 'isinstance' check work with Enum on py27.

**Comment by lzha106** [comment]
最新版本中已 fix，此 issue 可以关闭了
