### ISSUE TITLE
参数超过维度限制

### ISSUE THREAD

**Issue by AWSWXY** [PaddlePaddle/Paddle#17741]
grpc_client.cc:357] GetRPC name:[embedding_0.w_0], ep:[10.182.163.149:62004], status:[-1] meets grpc error, error_code:8 error_message:Sent message larger than max (2560000033 vs. 2147483647) error_details:
Wed May 29 21:55:12 2019[1,2]<stdout>:*** Check failure stack trace: ***
Wed May 29 21:55:12 2019[1,2]<stdout>:    @     0x7f56dcb13cdd  google::LogMessage::Fail()
Wed May 29 21:55:12 2019[1,2]<stdout>:    @     0x7f56dcb1778c  google::LogMessage::SendToLog()
Wed May 29 21:55:12 2019[1,2]<stdout>:    @     0x7f56dcb13803  google::LogMessage::Flush()
Wed May 29 21:55:12 2019[1,2]<stdout>:    @     0x7f56dcb18c9e  google::LogMessageFatal::~LogMessageFatal()
Wed May 29 21:55:12 2019[1,2]<stdout>:    @     0x7f56dd568994  paddle::operators::distributed::GRPCClient::Proceed()
Wed May 29 21:55:12 2019[1,2]<stdout>:    @     0x7f5766fe18a0  execute_native_thread_routine
Wed May 29 21:55:12 2019[1,2]<stdout>:    @     0x7f57709921c3  start_thread
Wed May 29 21:55:12 2019[1,2]<stdout>:    @     0x7f576ffba12d  __clone
Wed May 29 21:55:12 2019[1,2]<stdout>:    @              (nil)  (unknown)
Wed May 29 21:55:12 2019[1,2]<stdout>:thon2.7/site-packages/cv2 
Wed May 29 21:55:12 2019[1,2]<stdout>:

**Comment by junjun315** [comment]
组网时参数对应的数据大小超过了多机grpc设置的限制，导致传输时报错。可以调大server上的grpc包限制大小的值

**Comment by junjun315** [comment]
另外，可以通过fluid.DistributeTranspiler设置 config.slice_var_up= True 也可以解决。通过设置该参数，将把稀疏参数根据pserver的个数进行拆分，达到减少参数大小的目的。

**Comment by AWSWXY** [comment]
调整该参数后 config.slice_var_up= True 问题解决。
