### ISSUE TITLE
Error occurs when use paddle version 0.10 to train

### ISSUE THREAD

**Issue by 17Skye17** [PaddlePaddle/Paddle#1776]
Hello, I tried to use paddle version 0.10 code style to write the train script, but there always exists the error below:

F0413 06:01:49.267854 25689 Matrix.cpp:3255] Check failed: dynamic_cast<CpuIVector*>(&label) F0413 06:01:49.267868 25691 Matrix.cpp:3255] Check failed: dynamic_cast<CpuIVector*>(&label) F0413 06:01:49.268756 25687 Matrix.cpp:3255] Check failed: dynamic_cast<CpuIVector*>(&label) F0413 06:01:49.268764 25686 Matrix.cpp:3255] Check failed: dynamic_cast<CpuIVector*>(&label) F0413 06:01:49.268790 25688 Matrix.cpp:3255] Check failed: dynamic_cast<CpuIVector*>(&label) F0413 06:01:49.268812 25685 Matrix.cpp:3255] Check failed: dynamic_cast<CpuIVector*>(&label) F0413 06:01:49.268832 25695 Matrix.cpp:3255] Check failed: dynamic_cast<CpuIVector*>(&label) F0413 06:01:49.268844 25696 Matrix.cpp:3255] Check failed: dynamic_cast<CpuIVector*>(&label) FF0413 06:01:49.267854 25689 Matrix.cpp:3255] Check failed: dynamic_cast<CpuIVector*>(&label) F0413 06:01:49.267868 25691 Matrix.cpp:3255] Check failed: dynamic_cast<CpuIVector*>(&label) F0413 06:01:49.268756 25687 Matrix.cpp:3255] Check failed: dynamic_cast<CpuIVector*>(&label) F0413 06:01:49.268764 25686 Matrix.cpp:3255] Check failed: dynamic_cast<CpuIVector*>(&label) F0413 06:01:49.268790 25688 Matrix.cpp:3255] Check failed: dynamic_cast<CpuIVector*>(&label) F0413 06:01:49.268812 25685 Matrix.cpp:3255] Check failed: dynamic_cast<CpuIVector*>(&label) F0413 06:01:49.268832 25695 Matrix.cpp:3255] Check failed: dynamic_cast<CpuIVector*>(&label) F0413 06:01:49.268844 25696 Matrix.cpp:3255] Check failed: dynamic_cast<CpuIVector*>(&label) F0413 06:01:49.268842 25692 Matrix.cpp:3255] Check failed: dynamic_cast<CpuIVector*>(&label) F0413 06:01:49.268857 25690 Matrix.cpp:3255] Check failed: dynamic_cast<CpuIVector*>(&label) 
*** Check failure stack trace: ***
*** Check failure stack trace: ***
*** Check failure stack trace: ***

Can anyone give me a favor?

**Comment by 17Skye17** [comment]
@reyoung

**Comment by lcy-seso** [comment]
请参考此 issue https://github.com/PaddlePaddle/Paddle/issues/3716
