### ISSUE TITLE
论文参考文献怎么引用paddle的开发文档

### ISSUE THREAD

**Issue by Sparrow0817** [PaddlePaddle/Paddle#17774]

**Comment by SunGaofeng** [comment]
引用paddle网站(http://www.paddlepaddle.org/) 的文档，还是github上的说明文档？

**Comment by Sparrow0817** [comment]
> 引用paddle网站(http://www.paddlepaddle.org/) 的文档，还是github上的说明文档？

github上的doc

**Comment by raindrops2sea** [comment]
@Sparrow0817 具体是对应哪部分开文档内容呢？如果是使用了PaddlePaddle的话，建议可以直接引用“https://github.com/PaddlePaddle/Paddle”。

**Comment by Sparrow0817** [comment]
> @Sparrow0817 具体是对应哪部分开文档内容呢？如果是使用了PaddlePaddle的话，建议可以直接引用“[https://github.com/PaddlePaddle/Paddle”。](https://github.com/PaddlePaddle/Paddle%E2%80%9D%E3%80%82)

好的，感谢
