### ISSUE TITLE
pserver 启动失败

### ISSUE THREAD

**Issue by jiaqianjing** [PaddlePaddle/Paddle#17771]
为使您的问题得到快速解决，在建立Issues前，请您先通过如下方式搜索是否有相似问题:【搜索issue关键字】【使用labels筛选】【官方文档】

如果您没有查询到相似问题，为快速解决您的提问，建立issue时请提供如下细节信息：
- 标题：简洁、精准概括您的问题
- 版本、环境信息：
    1）PaddlePaddle版本：1.2.0
    2）CPU/GPU：cpu
    3）系统环境：centos
    4）Python版本号 2.7
    5）显存信息
- 复现信息：如为报错，请给出复现环境、复现步骤
- 问题描述：
Fri May 31 18:03:54 2019[1,0]<stdout>:Traceback (most recent call last):
Fri May 31 18:03:54 2019[1,0]<stdout>:  File "train.py", line 353, in <module>
Fri May 31 18:03:54 2019[1,0]<stdout>:    train_main(use_cuda=use_cuda, is_sparse=True, is_distributed=True, is_local=is_local, args=args)
Fri May 31 18:03:54 2019[1,0]<stdout>:  File "train.py", line 338, in train_main
Fri May 31 18:03:54 2019[1,0]<stdout>:    trainers=trainers)
Fri May 31 18:03:54 2019[1,0]<stdout>:  File "/home/disk1/normandy/maybach/app-user-20190531180117-3040/workspace/python27-gcc482/lib/python2.7/site-packages/paddle/fluid/transpiler/distribute_transpiler.py", line 519, in transpile
Fri May 31 18:03:54 2019[1,0]<stdout>:    pserver_endpoints)
Fri May 31 18:03:54 2019[1,0]<stdout>:  File "/home/disk1/normandy/maybach/app-user-20190531180117-3040/workspace/python27-gcc482/lib/python2.7/site-packages/paddle/fluid/transpiler/distribute_transpiler.py", line 1187, in _replace_lookup_table_op_with_prefetch
Fri May 31 18:03:54 2019[1,0]<stdout>:    outputs={"Out": self.all_prefetch_input_vars})
Fri May 31 18:03:54 2019[1,0]<stdout>:  File "/home/disk1/normandy/maybach/app-user-20190531180117-3040/workspace/python27-gcc482/lib/python2.7/site-packages/paddle/fluid/framework.py", line 1224, in _insert_op
Fri May 31 18:03:54 2019[1,0]<stdout>:    op = Operator(block=self, desc=op_desc, *args, **kwargs)
Fri May 31 18:03:54 2019[1,0]<stdout>:  File "/home/disk1/normandy/maybach/app-user-20190531180117-3040/workspace/python27-gcc482/lib/python2.7/site-packages/paddle/fluid/framework.py", line 657, in __init__
Fri May 31 18:03:54 2019[1,0]<stdout>:    self.desc.infer_shape(self.block.desc)
Fri May 31 18:03:54 2019[1,0]<stdout>:paddle.fluid.core.EnforceNotMet: Enforce failed. Expected ids_dims[0].size() == 2, but received ids_dims[0].size():3 != 2:2.
Fri May 31 18:03:54 2019[1,0]<stdout>: at [/script/paddle/paddle/fluid/operators/distributed_ops/split_ids_op.cc:59]
Fri May 31 18:03:54 2019[1,0]<stdout>:PaddlePaddle Call Stacks: 
Fri May 31 18:03:54 2019[1,0]<stdout>:0       0x7f6f8cf1c3c6p paddle::platform::EnforceNotMet::EnforceNotMet(std::__exception_ptr::exception_ptr, char const*, int) + 486
Fri May 31 18:03:54 2019[1,0]<stdout>:1       0x7f6f8d638ca0p paddle::operators::SplitIdsOp::InferShape(paddle::framework::InferShapeContext*) const + 976
Fri May 31 18:03:54 2019[1,0]<stdout>:2       0x7f6f8cfd08e6p paddle::framework::OpDesc::InferShape(paddle::framework::BlockDesc const&) const + 886
Fri May 31 18:03:54 2019[1,0]<stdout>:3       0x7f6f8cf84a7cp
Fri May 31 18:03:54 2019[1,0]<stdout>:4       0x7f6f8cf55e80p
Fri May 31 18:03:54 2019[1,0]<stdout>:5       0x7f6fa8616010p PyEval_EvalFrameEx + 16384
Fri May 31 18:03:54 2019[1,0]<stdout>:6       0x7f6fa8617b80p PyEval_EvalCodeEx + 2128
Fri May 31 18:03:54 2019[1,0]<stdout>:7       0x7f6fa85a8a5dp
Fri May 31 18:03:54 2019[1,0]<stdout>:8       0x7f6fa85853c3p PyObject_Call + 67
Fri May 31 18:03:54 2019[1,0]<stdout>:9       0x7f6fa8593a0dp
Fri May 31 18:03:54 2019[1,0]<stdout>:10      0x7f6fa85853c3p PyObject_Call + 67
Fri May 31 18:03:54 2019[1,0]<stdout>:11      0x7f6fa85d78d7p
Fri May 31 18:03:54 2019[1,0]<stdout>:12      0x7f6fa85d71efp
Fri May 31 18:03:54 2019[1,0]<stdout>:13      0x7f6fa85853c3p PyObject_Call + 67
Fri May 31 18:03:54 2019[1,0]<stdout>:14      0x7f6fa8612ec8p PyEval_EvalFrameEx + 3768
Fri May 31 18:03:54 2019[1,0]<stdout>:15      0x7f6fa8617b80p PyEval_EvalCodeEx + 2128
Fri May 31 18:03:54 2019[1,0]<stdout>:16      0x7f6fa861608ep PyEval_EvalFrameEx + 16510
Fri May 31 18:03:54 2019[1,0]<stdout>:17      0x7f6fa8617b80p PyEval_EvalCodeEx + 2128
Fri May 31 18:03:54 2019[1,0]<stdout>:18      0x7f6fa861608ep PyEval_EvalFrameEx + 16510
Fri May 31 18:03:54 2019[1,0]<stdout>:19      0x7f6fa8617b80p PyEval_EvalCodeEx + 2128
Fri May 31 18:03:54 2019[1,0]<stdout>:20      0x7f6fa861608ep PyEval_EvalFrameEx + 16510
Fri May 31 18:03:54 2019[1,0]<stdout>:21      0x7f6fa8617b80p PyEval_EvalCodeEx + 2128
Fri May 31 18:03:54 2019[1,0]<stdout>:22      0x7f6fa861608ep PyEval_EvalFrameEx + 16510
Fri May 31 18:03:54 2019[1,0]<stdout>:23      0x7f6fa8617b80p PyEval_EvalCodeEx + 2128
Fri May 31 18:03:54 2019[1,0]<stdout>:24      0x7f6fa8617c82p PyEval_EvalCode + 50
Fri May 31 18:03:54 2019[1,0]<stdout>:25      0x7f6fa863060fp
Fri May 31 18:03:54 2019[1,0]<stdout>:26      0x7f6fa863167ep PyRun_FileExFlags + 126
Fri May 31 18:03:54 2019[1,0]<stdout>:27      0x7f6fa86327d7p PyRun_SimpleFileExFlags + 199
Fri May 31 18:03:54 2019[1,0]<stdout>:28      0x7f6fa8642d9dp Py_Main + 3133
Fri May 31 18:03:54 2019[1,0]<stdout>:29      0x7f6fa7888bd5p __libc_start_main + 245
Fri May 31 18:03:54 2019[1,0]<stdout>:30            0x4007c1p

**Comment by SunGaofeng** [comment]
paddle.fluid.core.EnforceNotMet: Enforce failed. Expected ids_dims[0].size() == 2, but received ids_dims[0].size():3 != 2:2.

从这个报错信息来看，像是输入的shape不一致导致的，能否检查下数据输入？

**Comment by bhan1111** [comment]
训练样本应该没有问题啊，单机可以跑通

**Comment by bhan1111** [comment]
我把is_distributed设置为False
http://10.182.7.13:8900/fileview.html?path=/home/disk1/normandy/maybach/app-user-20190604142501-7246/
<img width="509" alt="图片" src="https://user-images.githubusercontent.com/29255596/58858662-a2924c00-86da-11e9-8ac4-5837e87a1c50.png">
总是提示pserver not ready

**Comment by jacquesqiao** [comment]
这个任务的trianer和pserver没有区分，都是启动的trainer
