### ISSUE TITLE
paddlepaddle如何支持cuda10训练

### ISSUE THREAD

**Issue by sicily** [PaddlePaddle/Paddle#17784]
是否支持cuda10训练？如何才能支持？目前看官网只提供了cuda8和cuda9

**Comment by hutuxian** [comment]
Thanks for your attention to PaddlePaddle.
For now you can use cuda10 by compiling the source code.

**Comment by hutuxian** [comment]
What's more, we plan to support cuda10 in the new fluid version(1.5) at the end of June.

**Comment by carychai** [comment]
Look forward to.My display card is RTX2060,can not use with CUDA8.0.
