### ISSUE TITLE
如何对loss分元素加权

### ISSUE THREAD

**Issue by dubhex** [PaddlePaddle/Paddle#17780]
模型输出为100个值，标签对应100个值，计算输出与标签的smooth_l1_loss，需要对其中的第10个至第20个值smooth_l1_loss进行加权。 
paddle.fluid.layers.smooth_l1可以用来计算smooth_l1 loss并进行加权，问题是参数outside_weight应该以什么形式、如何传入？

**Comment by SunGaofeng** [comment]
outside_weight可以用input data的形式传进来，或者用create_parameter的形式
1、input data 形式：
          outside_weight = fluid.layers.data(name='outside_weight', shape=[100], dtype='float32')
2、create_parameter形式：
         outside_weight_array = Your_Array.astype('float32')   # define your numpy array for outside weight
         outside_weight = fluid.layers.create_parameter(
                               shape=outside_weight_array.shape, dtype='float32',
                               default_initializer = fluid.initializer.NumpyArrayInitializer(outside_weight_array))
