### ISSUE TITLE
本地编译release/1.4分支失败

### ISSUE THREAD

**Issue by sicily** [PaddlePaddle/Paddle#17789]
本地编译，遇到以下问题，ubuntu16.04
```
paddle/fluid/platform/CMakeFiles/device_tracer.dir/build.make:62: recipe for target 'paddle/fluid/platform/CMakeFiles/device_tracer.dir/device_tracer.cc.o' failed
make[2]: *** [paddle/fluid/platform/CMakeFiles/device_tracer.dir/device_tracer.cc.o] Error 1
CMakeFiles/Makefile2:3335: recipe for target 'paddle/fluid/platform/CMakeFiles/device_tracer.dir/all' failed
make[1]: *** [paddle/fluid/platform/CMakeFiles/device_tracer.dir/all] Error 2

```

**Comment by sicily** [comment]
没有人回答问题吗？

**Comment by wopeizl** [comment]
可以把log再贴一点吗？目前这个看不太出来，还有编译过程是怎么做的？

**Comment by sicily** [comment]
![image](https://user-images.githubusercontent.com/3928685/58796080-d6179c80-862e-11e9-8b04-b049a4256999.png)
![image](https://user-images.githubusercontent.com/3928685/58796099-ef204d80-862e-11e9-8b6f-27cb63242a82.png)


我编译环境是：
ubuntu16.04，cuda10，gcc4.8，cmake3.5，python3.6
cmake命令：
```
cmake .. -DPY_VERSION=3.6 -DWITH_GPU=ON -DWITH_MKL=OFF -DWITH_TESTING=OFF -DCMAKE_BUILD_TYPE=Release
```

麻烦帮我看下这个是什么错误，谢谢

**Comment by sicily** [comment]
> 可以把log再贴一点吗？目前这个看不太出来，还有编译过程是怎么做的？

**Comment by wopeizl** [comment]
paddlepaddle当前没有正式支持cuda10，下个版本将开始支持，另外编译的时候可以采用官方提供的docker镜像，这样编译的时候能省去不少环境配置的环节。
http://paddlepaddle.org/documentation/docs/zh/1.4/beginners_guide/install/compile/compile_Ubuntu.html
