### ISSUE TITLE
作业开始训练后hang住

### ISSUE THREAD

**Issue by yxfGrace** [PaddlePaddle/Paddle#17798]
集群：MPI
paddle版本：paddle-fluid-v1.2.0
问题描述：
![image](https://user-images.githubusercontent.com/29363426/58774230-f88bc480-85f2-11e9-8789-d4f6646822bd.png)
作业开始训练后，hang住不动

**Comment by sandyhouse** [comment]
请提供具体的作业配置信息。

**Comment by sandyhouse** [comment]
https://github.com/PaddlePaddle/Paddle/issues/14930 https://github.com/PaddlePaddle/Paddle/issues/17362  https://github.com/PaddlePaddle/Paddle/issues/14776 https://github.com/PaddlePaddle/Paddle/issues/14447看一下这几个issue是否包含您的问题？

**Comment by sandyhouse** [comment]
问题原因是由于pserver节点宕机，已解决。

**Comment by sandyhouse** [comment]
Closing this issue. Reopen it if you have any further question.

**Comment by sandyhouse** [comment]
Closing this issue. Reopen it if you have any further question.

**Comment by sandyhouse** [comment]
Closing this issue. Reopen it if you have any further question.
