### ISSUE TITLE
TensorFlow 和 PaddlePaddle 的有无联系

### ISSUE THREAD

**Issue by yanwb** [PaddlePaddle/Paddle#17793]
TensorFlow的代码是否可以和PaddlePaddle框架下的代码相互迁移？是的话，具体如何操作呢？ 否的话，为甚麼？

**Comment by junjun315** [comment]
您好，paddlepaddle是一个独立的、完整的框架，与tensorflow在设计和实现上均有不同。如果需要把tensorflow下的代码迁移到paddlepaddle，可以参考我们这个项目：https://github.com/PaddlePaddle/X2Paddle  。如果使用过程中有问题欢迎随时跟我们联系。

**Comment by sandyhouse** [comment]
Closing this issue. Reopen it if you have any further question.
