### ISSUE TITLE
ocr训练找不到libwarpctc.so

### ISSUE THREAD

**Issue by peixuanshi** [PaddlePaddle/Paddle#17792]
d
- 版本、环境信息：
    1）PaddlePaddle::fluid_87
    3）GPU：CUDA8.0和CUD7版本号
    4）系统环境：centOS ，Python36,使用anaconda的虚拟环境
         
- 问题描述：
  使用modles自带的ocr_recognition的数据训练模型，出现： Can not find library: libwarpctc.so. Please try to add the lib path to LD_LIBRARY_PATH。但是按照的paddle已经自带了  libwarpctc.so。另外自己安装warpctc，并指定环境变量也是出现通用的错误

**Comment by luotao1** [comment]
请先检查下是否有多个python环境导致装错了，排查方法：
```
ldd python2.7/site-packages/paddle/fluid/core.so
```
看一下链接的库中，是否有链接到其他python环境下。即确保paddle装在你想装的python环境下。

**Comment by wanghaoshuang** [comment]
#17162

**Comment by wanghaoshuang** [comment]
该问题已解决：https://github.com/PaddlePaddle/models/issues/1360
