### ISSUE TITLE
The requirement version of requests incompatible with spacy, docker, and allennlp

### ISSUE THREAD

**Issue by lcctju** [PaddlePaddle/Paddle#17815]
**System information**
-PaddlePaddle version : 1.4.1
-CPU: Intel(R) Xeon(R) CPU E5-2680 v4 @ 2.40GHz
-GPU: GeForce GTX 1080 Ti  CUDA: 10.1  CUDNN: 7.0
-OS Platform: Ubuntu
-Python version: python3.6
- Install method: build from source(without docker)

**To Reproduce**

Requirement already satisfied: paddlepaddle-gpu==0.0.0 from file:///mnt/lun2/home/lcc/Paddle/build/python/dist/paddlepaddle_gpu-0.0.0-cp36-cp36m-linux_x86_64.whl in /usr/local/lib/python3.6/dist-packages (0.0.0)
Requirement already satisfied: nltk>=3.2.2 in /usr/local/lib/python3.6/dist-packages (from paddlepaddle-gpu==0.0.0) (3.4)
Requirement already satisfied: funcsigs in /usr/local/lib/python3.6/dist-packages (from paddlepaddle-gpu==0.0.0) (1.0.2)
Requirement already satisfied: numpy>=1.12 in /usr/local/lib/python3.6/dist-packages (from paddlepaddle-gpu==0.0.0) (1.15.4)
Requirement already satisfied: graphviz in /usr/local/lib/python3.6/dist-packages (from paddlepaddle-gpu==0.0.0) (0.10.1)
Requirement already satisfied: prettytable in /usr/local/lib/python3.6/dist-packages (from paddlepaddle-gpu==0.0.0) (0.7.2)
Requirement already satisfied: decorator in /usr/local/lib/python3.6/dist-packages (from paddlepaddle-gpu==0.0.0) (4.3.0)
Requirement already satisfied: scipy>=0.19.0 in /usr/local/lib/python3.6/dist-packages (from paddlepaddle-gpu==0.0.0) (1.2.0)
Requirement already satisfied: matplotlib==2.2.3 in /usr/local/lib/python3.6/dist-packages (from paddlepaddle-gpu==0.0.0) (2.2.3)
Requirement already satisfied: rarfile in /usr/local/lib/python3.6/dist-packages (from paddlepaddle-gpu==0.0.0) (3.0)
Requirement already satisfied: opencv-python in /usr/local/lib/python3.6/dist-packages (from paddlepaddle-gpu==0.0.0) (4.1.0.25)
Requirement already satisfied: six in /usr/local/lib/python3.6/dist-packages (from paddlepaddle-gpu==0.0.0) (1.12.0)
Requirement already satisfied: Pillow in /usr/lib/python3/dist-packages (from paddlepaddle-gpu==0.0.0) (5.1.0)
Collecting requests==2.9.2 (from paddlepaddle-gpu==0.0.0)
  Downloading https://files.pythonhosted.org/packages/8b/e7/229a428b8eb9a7f925ef16ff09ab25856efe789410d661f10157919f2ae2/requests-2.9.2-py2.py3-none-any.whl (502kB)
     |████████████████████████████████| 512kB 142kB/s 
Requirement already satisfied: pyyaml in /usr/lib/python3/dist-packages (from paddlepaddle-gpu==0.0.0) (3.12)
Requirement already satisfied: protobuf>=3.1.0 in /usr/local/lib/python3.6/dist-packages (from paddlepaddle-gpu==0.0.0) (3.7.1)
Requirement already satisfied: recordio>=0.1.0 in /usr/local/lib/python3.6/dist-packages (from paddlepaddle-gpu==0.0.0) (0.1.7)
Requirement already satisfied: singledispatch in /usr/local/lib/python3.6/dist-packages (from nltk>=3.2.2->paddlepaddle-gpu==0.0.0) (3.4.0.3)
Requirement already satisfied: pytz in /usr/local/lib/python3.6/dist-packages (from matplotlib==2.2.3->paddlepaddle-gpu==0.0.0) (2017.3)
Requirement already satisfied: kiwisolver>=1.0.1 in /usr/local/lib/python3.6/dist-packages (from matplotlib==2.2.3->paddlepaddle-gpu==0.0.0) (1.0.1)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 in /usr/local/lib/python3.6/dist-packages (from matplotlib==2.2.3->paddlepaddle-gpu==0.0.0) (2.3.0)
Requirement already satisfied: python-dateutil>=2.1 in /usr/local/lib/python3.6/dist-packages (from matplotlib==2.2.3->paddlepaddle-gpu==0.0.0) (2.7.5)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.6/dist-packages (from matplotlib==2.2.3->paddlepaddle-gpu==0.0.0) (0.10.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.6/dist-packages (from protobuf>=3.1.0->paddlepaddle-gpu==0.0.0) (40.6.3)
ERROR: spacy 2.0.18 has requirement requests<3.0.0,>=2.13.0, but you'll have requests 2.9.2 which is incompatible.
ERROR: docker 4.0.1 has requirement requests!=2.18.0,>=2.14.2, but you'll have requests 2.9.2 which is incompatible.
ERROR: allennlp 0.8.4 has requirement requests>=2.18, but you'll have requests 2.9.2 which is incompatible.

**Comment by ceci3** [comment]
requests这个包要求是大于2.13.0， 小于3.0.0，但是你本机安装的是2.9.2，需要先卸载掉2.9.2的requests，安装满足条件的requests包

**Comment by lcctju** [comment]
> requests这个包要求是大于2.13.0， 小于3.0.0，但是你本机安装的是2.9.2，需要先卸载掉2.9.2的requests，安装满足条件的requests包

paddle的依赖文件requirements.txt里面设置的requests==2.9.2

**Comment by ceci3** [comment]
> > requests这个包要求是大于2.13.0， 小于3.0.0，但是你本机安装的是2.9.2，需要先卸载掉2.9.2的requests，安装满足条件的requests包
> 
> paddle的依赖文件requirements.txt里面设置的requests==2.9.2

看了一下你的环境，paddle 1.4.1目前没有正式支持cuda10，会在下个版本开始支持

**Comment by lcctju** [comment]
> > > requests这个包要求是大于2.13.0， 小于3.0.0，但是你本机安装的是2.9.2，需要先卸载掉2.9.2的requests，安装满足条件的requests包
> > 
> > 
> > paddle的依赖文件requirements.txt里面设置的requests==2.9.2
> 
> 看了一下你的环境，paddle 1.4.1目前没有正式支持cuda10，会在下个版本开始支持

我使用源码编译，跟cuda版本貌似没有关系吧，paddle的依赖文件requirements.txt里面设置的requests==2.9.2，这个问题吧
