### ISSUE TITLE
cpu gru op进行训练时出错

### ISSUE THREAD

**Issue by dashulu** [PaddlePaddle/Paddle#17820]
用cpu训练一个包含gru op的模型，出现了如下错误， 请问是什么原因：
Traceback (most recent call last):                                                                              
  File "thirdparty/train.py", line 203, in <module>                                                             
    train_net()                                                                                                 
  File "thirdparty/train.py", line 199, in train_net                                                            
    init_high_bound=0.1)                                                                                        
  File "thirdparty/train.py", line 138, in train                                                                
    fetch_list=fetch_list)                                                                                      
  File "/usr/local/lib/python2.7/site-packages/paddle/fluid/executor.py", line 472, in run                      
    self.executor.run(program.desc, scope, 0, True, True)                                                       
paddle.fluid.core.EnforceNotMet:  at [/paddle/paddle/fluid/framework/operator.h:273]                            
PaddlePaddle Call Stacks:                                                                                       
0       0x7f35f95bc906p paddle::platform::EnforceNotMet::EnforceNotMet(std::__exception_ptr::exception_ptr, char
 const*, int) + 486                                                                                             
1       0x7f35f98de8f1p paddle::framework::ExecutionContext::cuda_device_context() const + 161                  
2       0x7f35f9e5660dp paddle::operators::GRUGradKernel<paddle::platform::CPUDeviceContext, float>::BatchComput
e(paddle::framework::ExecutionContext const&) const + 3133                                                      
3       0x7f35f9e5782ep _ZNSt17_Function_handlerIFvRKN6paddle9framework16ExecutionContextEEZNKS1_24OpKernelRegis
trarFunctorINS0_8platform8CPUPlaceELb0ELm0EJNS0_9operators13GRUGradKernelINS7_16CPUDeviceContextEfEENSA_ISB_dEEE
EclEPKcSG_EUlS4_E_E9_M_invokeERKSt9_Any_dataS4_ + 62          ，

**Comment by ceci3** [comment]
您好，方便贴一下训练脚本吗？

**Comment by dashulu** [comment]
> 您好，方便贴一下训练脚本吗？

    args = parse_args()                                                                                         
    # random seed must set before configuring the network.                                                      
    fluid.default_startup_program().random_seed = SEED                                                          
    fluid.default_main_program().random_seed = SEED                                                             
    vocab_size = len(vocab)                                                                                     
                                                                                                                
    #Input data                                                                                                 
    src_wordseq = fluid.layers.data(                                                                            
        name="src_wordseq", shape=[1], dtype="int64", lod_level=1)                                              
    dst_wordseq = fluid.layers.data(                                                                            
        name="dst_wordseq", shape=[1], dtype="int64", lod_level=1)                                              
                                                                                                                
    # Train program                                                                                             
    avg_cost = None                                                                                             
    cost = network(src_wordseq, dst_wordseq, vocab_size, hid_size,                                              
                   init_low_bound, init_high_bound)                                                             
    avg_cost = fluid.layers.mean(x=cost)                                                                        
                                                                                                                
    # Optimization to minimize lost                                                                             
    sgd_optimizer = fluid.optimizer.SGD(                                                                        
        learning_rate=fluid.layers.exponential_decay(                                                           
            learning_rate=base_lr,                                                                              
            decay_steps=2100 * 4,                                                                               
            decay_rate=0.5,                                                                                     
            staircase=True))                                                                                    
    sgd_optimizer.minimize(avg_cost) 
    sgd_optimizer.minimize(avg_cost)                                                                            
                                                                                                                
    # Initialize executor                                                                                       
    place = fluid.CUDAPlace(0) if use_cuda else fluid.CPUPlace()                                                
    exe = fluid.Executor(place)                                                                                 
    exe.run(fluid.default_startup_program())                                                                    
                                                                                                                                            
    train_exe = fluid.Executor(place)                                                                           
                                                                                                                
    total_time = 0.0                                                                                            
    fetch_list = [avg_cost.name]                                                                                
    for pass_idx in six.moves.xrange(pass_num):                                                                 
        epoch_idx = pass_idx + 1                                                                                
        print("epoch_%d start" % epoch_idx)                                                                     
                                                                                                                
        t0 = time.time()                                                                                        
        i = 0                                                                                                   
        newest_ppl = 0                                                                                          
        for data in train_reader():                                                                             
            i += 1                                                                                              
            lod_src_wordseq = utils.to_lodtensor([dat[0] for dat in data],                                      
                                                 place)                                                         
            lod_dst_wordseq = utils.to_lodtensor([dat[1] for dat in data],                                      
                                                 place)                                                         
            ret_avg_cost = train_exe.run(feed={                                                                 
                "src_wordseq": lod_src_wordseq, 
                "src_wordseq": lod_src_wordseq,                                                                 
                "dst_wordseq": lod_dst_wordseq                                                                  
            },                                                                                                  
                                         fetch_list=fetch_list)                                                 
            avg_ppl = np.exp(ret_avg_cost[0])                                                                   
            newest_ppl = np.mean(avg_ppl)                                                                       
            if i % 100 == 0:                                                                                    
                print("step:%d ppl:%.3f" % (i, newest_ppl))                                                     
                                                                                                                
        t1 = time.time()                                                                                        
        total_time += t1 - t0                                                                                   
        print("epoch:%d num_steps:%d time_cost(s):%f" %                                                         
              (epoch_idx, i, total_time / epoch_idx))

**Comment by ceci3** [comment]
用户使用GPU训练没有报错，我本地使用paddlepaddle 1.4运行代码也没有报错
