### ISSUE TITLE
使用c++（paddle-tensorrt）如何给lstm序列喂入输入？

### ISSUE THREAD

**Issue by dancingpipi** [PaddlePaddle/Paddle#17843]
1）PaddlePaddle版本：1.4
    2）CPU：None
    3）GPU：P4
    4）系统环境：ubuntu16.04
-预测信息
    1）C++预测：GIT COMMIT ID: bfcc97d9245e21aa06053755033679de6e3a537a
                            WITH_MKL: OFF
                            WITH_MKLDNN: OFF
                            WITH_GPU: ON
                            CUDA version: 8.0
                            CUDNN version: v7
    2）CMake包含路径的完整命令
                            cmake .. \
                                  -DWITH_FLUID_ONLY=ON \
                                  -DWITH_MKL=OFF \
                                  -DWITH_MKLDNN=OFF \
                                  -DCMAKE_BUILD_TYPE=Release \
                                  -DWITH_PYTHON=OFF   \
                                  -DTENSORRT_ROOT=/usr \
                                  -DON_INFER=ON
    3）API信息（如调用请提供）             
```c++
        auto predictor = CreatePaddlePredictor(config);
        predictor->Run(paddle_tensor_feeds, &outputs, batch_size);
```
    4）预测库来源：官网下载
- 复现信息：
- 问题描述：
 1、核心问题：使用paddle-tensorRT时，如何给lstm喂输入。
![image](https://user-images.githubusercontent.com/20511825/58885148-43e9c400-8714-11e9-822b-a44975324183.png)

 2、模型介绍：我有一个场景分类模型，这个模型有两个输入，一个输出。两个输入分别是视频所有帧的图像特征（1024维）和音频信息（128维），视频帧的长度不定。在python代码中使用：
```python
fluid.layers.data(shape=[1024], lod_level=1, dtype='float32', name=name1)
fluid.layers.data(shape=[128], lod_level=1, dtype='float32', name=name2)
```
作为输入层，使用
```python
infer_feeder = fluid.DataFeeder(place=place, feed_list=infer_feeds)
infer_outs = exe.run(fetch_list=fetch_list,
                             feed=infer_feeder.feed(data_feed_in))
```
来喂入数据，使用
```python
fluid.io.save_inference_model(dirname="./infer_model",
                                  feeded_var_names=infer_feeds_name,
                                  target_vars=[infer_outputs[0]], executor = exe)
```
来保存模型。

3、参考了官方的教程：[paddle-tensorrt](http://paddlepaddle.org/documentation/docs/zh/1.4/advanced_usage/deploy/inference/paddle_tensorrt_infer.html)
但是教程说到lod的时候又跳到python了，所以还是没有搞明白应该如何用c++喂序列类型的数据。
这里贴一下我用的代码：
```c++
AnalysisConfig config(model_dirname);
  // config->SetModel(model_dirname + "/model",                                                                                             
  //                     model_dirname + "/params");

  config.EnableUseGpu(100, 0 /*gpu_id*/);
  config.EnableTensorRtEngine(1 << 20 /*work_space_size*/, batch_size /*max_batch_size*/);

  // 2. 根据config 创建predictor
  std::cout << "create_predictor!"<< std::endl;
  auto predictor = CreatePaddlePredictor(config);
  std::cout << "finish create_predictor!"<< std::endl;
  // 3. 创建输入 tensor 
  float input_data1[batch_size * 185 * 1024] = {0};
  float input_data2[batch_size * 185 * 128] = {0};

  PaddleTensor tensor1;
  tensor1.shape = std::vector<int>({batch_size, 185 * 1024});
  tensor1.data = PaddleBuf(static_cast<void *>(input_data1),
                          sizeof(float) * (185 * 1024));
  tensor1.dtype = PaddleDType::FLOAT32;

  PaddleTensor tensor2;
  tensor2.shape = std::vector<int>({batch_size, 185 * 128});
  tensor2.data = PaddleBuf(static_cast<void *>(input_data2),
                          sizeof(float) * (185 * 128));
```

希望得到解答，或者能给一个详尽点的教程~

**Comment by NHZlX** [comment]
paddle-trt暂时还不支持.
config配置参照https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/fluid/inference/tests/api/analyzer_rnn2_tester.cc#L107-#L112


lstm输入应该需要设置lod信息，具体参照：
https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/fluid/inference/tests/api/analyzer_rnn2_tester.cc#L91-#L104


关于这块，文档确实存在不详尽的情况，近期会进行完善
