### ISSUE TITLE
加载模型失败

### ISSUE THREAD

**Issue by AWSWXY** [PaddlePaddle/Paddle#17849]
![image](https://user-images.githubusercontent.com/18156360/58927019-aa57fc00-877f-11e9-8959-7cb643e46194.png)

**Comment by AIFollowers** [comment]
请再详细描述下问题@AWSWXY

**Comment by yeyupiaoling** [comment]
@AWSWXY 你是否使用了正确的模型加载接口？或者是加载的模型是否正确。
你会不会加载了预测的模型？
