### ISSUE TITLE
#强烈建议支持multi-hot编码

### ISSUE THREAD

**Issue by tz28** [PaddlePaddle/Paddle#17840]
欢迎您对PaddlePaddle提出建议，非常感谢您对PaddlePaddle的贡献！
在留下您的建议时，辛苦您同步提供如下信息：
- 版本、环境信息
1）PaddlePaddle版本：fluid1.4
2）CPU/GPU：cpu
3）系统环境：Mac OS 10.14
- 复现信息：如为报错，请给出复现环境、复现步骤
- 建议描述：希望增加multi-hot编码的支持。对于单值离散特征，fluid中已经封装了one-hot编码，但是在ctr预估中经常有多值离散特征，即一条样本的某个特征会取多个值，如用户兴趣。这样就需要multi-hot，得到的编码形如：[0,1,1,0,1,0,0,1,0]等。目前paddle中还不支持。可参考embedding实现，传入多个索引可以得到多个embedding向量。
Thank you for contributing to PaddlePaddle.
Before submitting the issue, you could search issue in the github in case that there was a similar issue submitted or resolved before.
Please make sure that this is a feature request. 
**System information**
-PaddlePaddle version （eg.1.1）or CommitID
-CPU: including CPUMKL/OpenBlas/MKLDNN version
-GPU: including CUDA/CUDNN version
-OS Platform (eg.Mac OS 10.14)
**To Reproduce**
Steps to reproduce the behavior
**Describe the feature and the current behavior/state.**
**Any Other info.**

**Comment by ceci3** [comment]
您好，现在还不支持

**Comment by guru4elephant** [comment]
@tz28 可以直接用embedding将多个离散特征放到一个slot里面进行查找，embedding layer可以看做multi-hot的一个超集，当embedding dim为1时，并且参数都为1.0，那么就是multi-hot
