### ISSUE TITLE
两台机器使用相同环境，一台正常运行，另一台CUDNN_STATUS_NOT_INITIALIZED

### ISSUE THREAD

**Issue by miraclebiu** [PaddlePaddle/Paddle#17842]
为使您的问题得到快速解决，在建立Issues前，请您先通过如下方式搜索是否有相似问题:【搜索issue关键字】【使用labels筛选】【官方文档】

如果您没有查询到相似问题，为快速解决您的提问，建立issue时请提供如下细节信息：
- 标题：简洁、精准概括您的问题，例如“Insufficient Memory xxx" ”
- 版本、环境信息：
    1）PaddlePaddle版本：1.4.1
    2）CPU：预测若用CPU，请提供CPU型号，MKL/OpenBlas/MKLDNN/等数学库使用情况
    3）GPU：k40
    4）系统环境：cuda8 cudnn7.1
    1）单机/多机，多卡

Traceback (most recent call last):
  File "ft_car_rec_v7_paddle.py", line 257, in <module>
    ret = train(args, weight_file, data_path, train_img_path, train_label_filename, test_img_path, test_label_filename)
  File "ft_car_rec_v7_paddle.py", line 221, in train
    loss_value, softmax_value = exe.run(program=train_parallel_prog, fetch_list=[loss_list[1].name,pred_list[0].name], feed=feeder.feed(data))
  File "/home/vis/jiangminyue/dependency/minyue/lib/python2.7/site-packages/paddle/fluid/executor.py", line 580, in run
    return_numpy=return_numpy)
  File "/home/vis/jiangminyue/dependency/minyue/lib/python2.7/site-packages/paddle/fluid/executor.py", line 446, in _run_parallel
    exe.run(fetch_var_names, fetch_var_name)
paddle.fluid.core.EnforceNotMet: Invoke operator conv2d error.
Python Callstacks: 
  File "/home/vis/jiangminyue/dependency/minyue/lib/python2.7/site-packages/paddle/fluid/framework.py", line 1654, in append_op
    attrs=kwargs.get("attrs", None))
  File "/home/vis/jiangminyue/dependency/minyue/lib/python2.7/site-packages/paddle/fluid/layer_helper.py", line 43, in append_op
    return self.main_program.current_block().append_op(*args, **kwargs)
  File "/home/vis/jiangminyue/dependency/minyue/lib/python2.7/site-packages/paddle/fluid/layers/nn.py", line 2073, in conv2d
    'fuse_relu_before_depthwise_conv': False
  File "/home/vis/jiangminyue/paddle_ft_rec_cluster/recv7_multi_output_node.py", line 207, in conv
    act=act)
  File "/home/vis/jiangminyue/paddle_ft_rec_cluster/recv7_multi_output_node.py", line 30, in layer_decorated
    layer_output = op(self, layer_input, *args, **kwargs)
  File "/home/vis/jiangminyue/paddle_ft_rec_cluster/recv7_multi_output_node.py", line 666, in setup
    self.conv(7, 7, 16, 1, 1, padding=[3, 3], biased=False, relu=False, name='eariest_unit1_conv1')
  File "/home/vis/jiangminyue/paddle_ft_rec_cluster/recv7_multi_output_node.py", line 62, in __init__
    self.setup()
  File "ft_car_rec_v7_paddle.py", line 56, in build_model
    net = Deep_agg_60({input_name: images})
  File "ft_car_rec_v7_paddle.py", line 86, in load_model
    net, input_map, images = build_model()
  File "ft_car_rec_v7_paddle.py", line 164, in train
    ret = load_model(net_weight)
  File "ft_car_rec_v7_paddle.py", line 257, in <module>
    ret = train(args, weight_file, data_path, train_img_path, train_label_filename, test_img_path, test_label_filename)
C++ Callstacks: 
CUDNN_STATUS_NOT_INITIALIZED at [/paddle/paddle/fluid/platform/device_context.cc:218]
PaddlePaddle Call Stacks: 
0       0x7fe9d4ee2f90p void paddle::platform::EnforceNotMet::Init<char const*>(char const*, char const*, int) + 352
1       0x7fe9d4ee3309p paddle::platform::EnforceNotMet::EnforceNotMet(std::__exception_ptr::exception_ptr, char const*, int) + 137
2       0x7fe9d6d36008p paddle::platform::CudnnHolder::CudnnHolder(CUstream_st* const*, paddle::platform::CUDAPlace const&) + 1000
3       0x7fe9d6d362d0p
4         0x38c040cbe0p pthread_once + 80
5       0x7fe9d6d3552bp paddle::platform::CUDADeviceContext::cudnn_holder() const + 91
6       0x7fe9d6d35559p paddle::platform::CUDADeviceContext::cudnn_handle() const + 9
7       0x7fe9d52ab520p paddle::operators::ConvOp::GetExpectedKernelType(paddle::framework::ExecutionContext const&) const + 400
8       0x7fe9d6c898f3p paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&, paddle::framework::RuntimeContext*) const + 243
9       0x7fe9d6c8a204p paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&) const + 292
10      0x7fe9d6c87b2cp paddle::framework::OperatorBase::Run(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&) + 332
11      0x7fe9d6a963cap paddle::framework::details::ComputationOpHandle::RunImpl() + 250
12      0x7fe9d6a89480p paddle::framework::details::OpHandleBase::Run(bool) + 160
13      0x7fe9d69f0b4dp
14      0x7fe9d5caa043p std::_Function_handler<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> (), std::__future_base::_Task_setter<std::unique_ptr<std::__future_base::_Result<void>, std::__future_base::_Result_base::_Deleter>, void> >::_M_invoke(std::_Any_data const&) + 35
15      0x7fe9d4fb15e7p std::__future_base::_State_base::_M_do_set(std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> ()>&, bool&) + 39
16        0x38c040cbe0p pthread_once + 80
17      0x7fe9d69f06e2p
18      0x7fe9d4fb2924p ThreadPool::ThreadPool(unsigned long)::{lambda()#1}::operator()() const + 404
19      0x7fea0f2c9678p
20        0x38c0407df3p
21        0x38bfcf62cdp clone + 109

**Comment by ceci3** [comment]
相同的环境是指cuda版本驱动和cudnn版本相同吗

**Comment by AIFollowers** [comment]
CUDA与cuDNN版本不一致，找相应版本的paddle进行pip安装，或者手动编译安装

**Comment by miraclebiu** [comment]
> CUDA与cuDNN版本不一致，找相应版本的paddle进行pip安装，或者手动编译安装

这两个机器的cuda和cudnn是一样的

**Comment by yeyupiaoling** [comment]
@miraclebiu 这个我遇到过，就是显卡不支持CUDA的问题，例如我的是2070，我安装了CUDA9也是这个错误，只有使用CUDA 10才行。
