### ISSUE TITLE
no CUDA-capable is detected

### ISSUE THREAD

**Issue by manzhengrui** [PaddlePaddle/Paddle#17857]
程序运行的时候，提示：
no CUDA-capable is detected

**Comment by Austendeng** [comment]
错误截图如下
![image](https://user-images.githubusercontent.com/16330293/58937881-41d04580-87a6-11e9-82a0-df0d12c24947.png)

**Comment by AIFollowers** [comment]
CUDA_VISIBLE_DEVICES变量设置问题

**Comment by manzhengrui** [comment]
先看下需要安装的paddle的版本所需要的cuda版本，以及对应的 cudnn版本，和驱动版本
然后先安装 驱动，在安装 cuda cudnn 还有几个库，
最后安装paddle，安装后，export 库
如果是单机单卡，那GPU编号是0开始。对单机多卡的设置也要修改下

这个问题主要是 GPU的编号没有指定对，需要指定 CUDA_VISIBLE_DEVICES
