### ISSUE TITLE
训练中报错，原因不明

### ISSUE THREAD

**Issue by bhan1111** [PaddlePaddle/Paddle#17855]
1）PaddlePaddle版本：1.2.0
   2）CPU/GPU：cpu
   3）系统环境：centos
   4）Python版本号 2.7
   5）显存信息

mpi 地址：
http://10.182.15.20:8900/fileview.html?path=/home/disk1/normandy/maybach/app-user-20190605112054-8214/

pserver 报错：
<img width="1229" alt="图片" src="https://user-images.githubusercontent.com/29255596/58935805-d20b8c00-87a0-11e9-838c-8137b6c9ebbc.png">
无法定位问题，请求支援

**Comment by jacquesqiao** [comment]
distribute_transpiler_config.slice_var_up=True

**Comment by jacquesqiao** [comment]
https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/fluid/transpiler/distribute_transpiler.py#L156
