### ISSUE TITLE
train_from_dataset 接口如何打印训练速度信息？

### ISSUE THREAD

**Issue by lzha106** [PaddlePaddle/Paddle#17850]
- 版本、环境信息：
    1）PaddlePaddle版本：1.4.1
    2）CPU：Xeon
    3）GPU： no GPU
    4）系统环境：Ubuntu 16.04， python 2.7
- 训练信息
    1）单机
    2）显存信息
    3）Operator信息
- 复现信息：使用 train_from_dataset 进行训练，例如 https://github.com/PaddlePaddle/models/blob/develop/PaddleRec/ctr/Paddle_baseline_KDD2019/local_train.py
- 问题描述：
使用 train_from_dataset 如何打印训练速度？例如 batches/second。 目前看到的接口，print_period  只能打印 fetch_info 的变量，但是没有时间戳，无法计算 batches/second。 另外是否接口内部可以直接打出训练速度？

**Comment by yeyupiaoling** [comment]
@lzha106 我一般是自己统计的，PaddlePaddle好像没有这个操作。

**Comment by guru4elephant** [comment]
train_from_dataset接口参数设置debug=True，会打印单个线程每秒处理的样本数，我们后面会增加独立的python线程进行数据fetch的接口

**Comment by guru4elephant** [comment]
此外，训练的线程数和dataset使用的线程数以及文件个数有关，推荐文件个数尽量多，dataset线程数打满cpu core

**Comment by lzha106** [comment]
> @lzha106 我一般是自己统计的，PaddlePaddle好像没有这个操作。

多谢 @yeyupiaoling 回复，请问基于 train_from_dataset 您是怎么来统计的呢？这个接口只有完成一次 epoch 的训练才可以自己加时间统计，对于大的数据集太久了。根据 print_period 输出的日志，没有时间戳也不太方便统计。

**Comment by lzha106** [comment]
> train_from_dataset接口参数设置debug=True，会打印单个线程每秒处理的样本数，我们后面会增加独立的python线程进行数据fetch的接口

@guru4elephant ，打开 debug 是否会影响训练速度？

**Comment by guru4elephant** [comment]
> > train_from_dataset接口参数设置debug=True，会打印单个线程每秒处理的样本数，我们后面会增加独立的python线程进行数据fetch的接口
> 
> @guru4elephant ，打开 debug 是否会影响训练速度？

不会，你可以做对比测试看看，我之前自己测试过几乎没区别。@lzha106

**Comment by lzha106** [comment]
debug 开关打开可以看到单 thread 的处理样本数，但是依旧包含了许多不关心的内容，例如 ops 的时间，log 会很多，还是希望未来可以通过 fetch_list 的打印同时打出训练速度。

**Comment by lzha106** [comment]
@guru4elephant 再请问下 train_from_dataset 接口怎么能间隔 step 获取到 auc ，loss 的数值？如果要使用 visual dl 显示训练过程 loss 下降，是只能从日志获取么？有没有接口可以在运行时获取

**Comment by guru4elephant** [comment]
@lzha106 train_from_dataset内部是异步执行，获取的数值可能会不准，但我们未来会增加一个python的call back接口，允许用户获取scope中的变量值
