### ISSUE TITLE
Error while running  demo/semantic_role_labeling/train.sh

### ISSUE THREAD

**Issue by sanjaymeena** [PaddlePaddle/Paddle#1785]
Hello all, I am using paddle for the first time. I am using docker image paddlepaddle/paddle:0.10.0rc2 . When i run paddle/demo/semantic_role_labeling/train.sh , it give me following error : 

![image](https://cloud.githubusercontent.com/assets/5145685/25033506/0387064a-2111-11e7-86e1-4a35ad5339dd.png)

Please help!  I can run api_train_v2.py . It does not have code to save model or do predictions yet.

**Comment by typhoonzero** [comment]
Sorry, this is a bug of the docker image `paddlepaddle/paddle:0.10.0rc2`. You need to specify `PYTHONHOME` to `/usr/local` in order to run: 
```
export PYTHONHOME=/usr/local
./train.sh
```

**Comment by sanjaymeena** [comment]
thank you :) this solves my problem. Waiting for the patch.

**Comment by sanjaymeena** [comment]
Hello, in the same demo program there is another problem with predict.sh script . It gives a core dump

build : paddlepaddle/paddle:0.10.0rc2
file : paddle/demo/semantic_role_labeling/predict.sh 


![image](https://cloud.githubusercontent.com/assets/5145685/25036594/3fdfc864-2127-11e7-8ffa-0b43b6ae916a.png)

**Comment by reyoung** [comment]
It seems we provide a new version training script but do not provide the prediction code at the same time.

Please try to use master branch for stable release. This issue will be fixed soon.

**Comment by luotao1** [comment]
@sanjaymeena please use the [latest v0.10.0](https://github.com/PaddlePaddle/Paddle/releases/tag/v0.10.0) and [book/label_semantic_roles](https://github.com/PaddlePaddle/book/tree/develop/07.label_semantic_roles) instead. We will not maintain the `demo/semantic_role_labeling` in the future.
