### ISSUE TITLE
安装错误_k1200卡安装paddle

### ISSUE THREAD

**Issue by manzhengrui** [PaddlePaddle/Paddle#17852]
k1200的卡上安装paddle，安装错误

**Comment by AIFollowers** [comment]
没有安装相应的显卡驱动；

**Comment by manzhengrui** [comment]
先看下需要安装的paddle的版本所需要的cuda版本，以及对应的 cudnn版本，和驱动版本
然后先安装 驱动，在安装 cuda cudnn 还有几个库，
最后安装paddle，安装后，export 库
如果是单机单卡，那GPU编号是0开始。对单机多卡的设置也要修改下
