### ISSUE TITLE
paddlepaddle 安装检查报错

### ISSUE THREAD

**Issue by carychai** [PaddlePaddle/Paddle#17863]
- 版本、环境信息：
    1）PaddlePaddle版本：
    2）CPU：i5-8400
    3）GPU：Geforce RTX2060，CUDA:8.0 和CUDNN:V7.1
    4）系统环境：windows 10. python: 3.7.3

- 安装方式信息：
1）pip安装:pip3 install paddlepaddle-gpu    

- 问题描述：请详细描述您的问题，同步贴出报错信息、日志/代码关键片段
C:\Users\Administrator>python
Python 3.7.3 (v3.7.3:ef4ec6ed12, Mar 25 2019, 22:22:05) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import paddle.fluid
>>> paddle.fluid.install_check.run_check()
Running Verify Fluid Program ...
W0605 16:46:12.933351 11216 device_context.cc:261] Please NOTE: device: 0, CUDA Capability: 75, Driver API Version: 10.1, Runtime API Version: 8.0
W0605 16:46:12.988390 11216 device_context.cc:269] device: 0, cuDNN Version: 7.0.
F0605 16:46:13.126737 11216 device_context.cc:337] cudaGetLastError  invalid device function errno:8
*** Check failure stack trace: ***

随后弹出python环境异常，退出python
![error](https://user-images.githubusercontent.com/26074835/58943627-b3ae8c00-87b2-11e9-9272-7e8184606490.png)

**Comment by carychai** [comment]
<img width="464" alt="微信图片_20190606085418" src="https://user-images.githubusercontent.com/26074835/58999562-d6838380-8838-11e9-8f9b-643cb773ddbf.png">
安装CUDA8.0提示

**Comment by yeyupiaoling** [comment]
你的CUDA是安装成功的吗？

**Comment by carychai** [comment]
CUDA 8.0安装过程。今天帮显卡驱动，cuda全部卸载，重新装，还是一样的问题，cuda显示安装完成。
帮忙看一下

**Comment by yeyupiaoling** [comment]
@carychai 你的显卡是什么？

**Comment by carychai** [comment]
Nvidia Geforce RTX2060

**Comment by yeyupiaoling** [comment]
你检查一下显卡驱动是否安装成功，使用命令：nvidia-smi 查看一下。如果是没有问题的，我怀疑是你的显卡不支持CUDA 8

**Comment by carychai** [comment]
nvidia-smi正确显示驱动的版本，GPU型号，所以显卡驱动正确安装了.
如果显卡不支持CUDA8,paddle在windows下只有CUDA8选择，哪些显卡能支持呢？
我这个显卡也是大几千一张呢

**Comment by yeyupiaoling** [comment]
@carychai 你在Ubuntu上使用CUDA 9 ，再安装PaddlePaddle。
这个不是钱的问题，是版本的问题。
我的是 2070，也不支持CUDA 8 ，CUDA9。只支持CUDA10

**Comment by carychai** [comment]
我的意思是想知道哪些显卡能支持windows下CUDA8.0，不然买了不能用，浪费钱。

**Comment by yeyupiaoling** [comment]
@carychai 这我也太了解，例如1080这些应该都支持吧。

**Comment by carychai** [comment]
请教你在用哪个显卡呢？

**Comment by yeyupiaoling** [comment]
我公司给我买了个2070，这样让我很头疼，因为他只支持CUDA 10，基本上用不了，支持在Ubuntu 上自己编译支持CUDA 10的PaddlePaddle才能用

**Comment by carychai** [comment]
OK，我准备安装Ubuntu了。

**Comment by yeyupiaoling** [comment]
嗯嗯。你可以看看这个教程：https://yeyupiaoling.blog.csdn.net/article/details/80689543

**Comment by carychai** [comment]
谢谢
