### ISSUE TITLE
请问Fluid版本如何在训练过程中获取batch size？

### ISSUE THREAD

**Issue by yeyupiaoling** [PaddlePaddle/Paddle#17874]
# 环境
 - PaddlePaddle 1.4.1
 - Ubuntu 16.04
 - Python 3.5

# 问题
请问Fluid版本如何在训练过程中获取batch size？

**Comment by zhaoyuchen2018** [comment]
batch size是自己设置的，不太清楚要获取什么batch size

**Comment by yeyupiaoling** [comment]
@zhaoyuchen2018 因为在训练过程中，batch size是有可能变化的。

**Comment by yeyupiaoling** [comment]
@zhaoyuchen2018 我记得之前有同学说是可以使用什么切片的方式获取的，我不记得了。

**Comment by yeyupiaoling** [comment]
@zhaoyuchen2018 tensorflow是这样获取batch size的
```
# 获取batch数
num_row = tf.to_int32(label.get_shape()[0])
```

**Comment by yeyupiaoling** [comment]
可以通过`fluid.layers.py_func`这个接口获取。
