### ISSUE TITLE
server not ready，一直等待

### ISSUE THREAD

**Issue by MaxLingwei** [PaddlePaddle/Paddle#17888]
在GPU集群进行训练，商品一直在等待
![image](https://user-images.githubusercontent.com/14048056/59014340-f766cb80-886e-11e9-8240-821f95edc404.png)
也尝试过其他端口，会出现同样的问题。
训练代码参考了这个demo
https://github.com/PaddlePaddle/Paddle/tree/v1.1.0/benchmark/fluid

**Comment by zhaoyuchen2018** [comment]
这个请分布式的同学帮忙看看

**Comment by ccmeteorljh** [comment]
麻烦检查下是否开了代理

**Comment by kjkttt** [comment]
尝试设置wait_port为False
`config = fluid.DistributeTranspilerConfig()  
config.wait_port = False
`
