### ISSUE TITLE
Semantic Role Labeling Demo only provide v2 trainer, but not provide model inference code.

### ISSUE THREAD

**Issue by reyoung** [PaddlePaddle/Paddle#1788]
Related issue #1785.

The paddle [srl demo](https://github.com/PaddlePaddle/Paddle/tree/develop/demo/semantic_role_labeling) only provide v2 API trainer, which is `api_train_v2.py`. The `predict.py` is not related to this trainer, and the `train.sh`, `data` cannot be used due to missing files.

**Comment by lcy-seso** [comment]
qingqing has fixed this in this [pr](https://github.com/PaddlePaddle/book/pull/273/files).  I will merge it into demo later.

**Comment by sanjaymeena** [comment]
Hi, i tried the latest build . Seems the fixes has not been updated yet. Please help to make the inference script run. Many thanks!
