### ISSUE TITLE
Ubuntu编译报错

### ISSUE THREAD

**Issue by lcctju** [PaddlePaddle/Paddle#17899]
- 版本、环境信息：
    1）PaddlePaddle版本：e2c1b7c354c9ca6720228f1b55bfc4c6a6f82292
    2）CPU：Intel(R) Xeon(R) CPU E5-2680 v4 @ 2.40GHz
    3）GPU：GTX 1080 Ti，CUDA 10.1 CUDNN 7
    4）系统环境：Ubuntu 18.04、Python3.6
- 安装方式信息：本地编译：
- cmake命令: cmake .. -DPY_VERSION=3.6 -DWITH_FLUID_ONLY=ON -DWITH_GPU=ON -DWITH_TESTING=OFF -DCMAKE_BUILD_TYPE=Release

- 问题描述：
[ 14%] Building CXX object paddle/fluid/framework/ir/CMakeFiles/alloc_continuous_space_for_grad_pass.dir/alloc_continuous_space_for_grad_pass.cc.o
In file included from /home/lcc/mypaddle/Paddle/paddle/fluid/framework/ir/alloc_continuous_space_for_grad_pass.cc:15:0:
/home/lcc/mypaddle/Paddle/paddle/fluid/framework/ir/alloc_continuous_space_for_grad_pass.h:24:33: error: variable or field ‘SetFuseParameterMemorySize’ declared void
 void SetFuseParameterMemorySize(uint64_t memory_size);
                                 ^~~~~~~~
/home/lcc/mypaddle/Paddle/paddle/fluid/framework/ir/alloc_continuous_space_for_grad_pass.h:24:33: error: ‘uint64_t’ was not declared in this scope
/home/lcc/mypaddle/Paddle/paddle/fluid/framework/ir/alloc_continuous_space_for_grad_pass.h:24:33: note: suggested alternative: ‘u_int64_t’
 void SetFuseParameterMemorySize(uint64_t memory_size);
                                 ^~~~~~~~
                                 u_int64_t
/home/lcc/mypaddle/Paddle/paddle/fluid/framework/ir/alloc_continuous_space_for_grad_pass.h:25:1: error: ‘uint64_t’ does not name a type; did you mean ‘u_int64_t’?
 uint64_t GetFuseParameterMemorySize();
 ^~~~~~~~
 u_int64_t
In file included from /home/lcc/mypaddle/Paddle/paddle/fluid/framework/attribute.h:25:0,
                 from /home/lcc/mypaddle/Paddle/paddle/fluid/framework/op_desc.h:20,
                 from /home/lcc/mypaddle/Paddle/paddle/fluid/framework/ir/node.h:22,
                 from /home/lcc/mypaddle/Paddle/paddle/fluid/framework/ir/graph.h:23,
                 from /home/lcc/mypaddle/Paddle/paddle/fluid/framework/ir/pass.h:23,
                 from /home/lcc/mypaddle/Paddle/paddle/fluid/framework/ir/pass_builder.h:19,
                 from /home/lcc/mypaddle/Paddle/paddle/fluid/framework/details/build_strategy.h:22,
                 from /home/lcc/mypaddle/Paddle/paddle/fluid/framework/ir/alloc_continuous_space_for_grad_pass.cc:21:
/home/lcc/mypaddle/Paddle/paddle/fluid/platform/cuda_helper.h: In destructor ‘paddle::platform::CublasHandleHolder::~CublasHandleHolder()’:
/home/lcc/mypaddle/Paddle/paddle/fluid/platform/enforce.h:254:67: warning: throw will always call terminate() [-Wterminate]

**Comment by luotao1** [comment]
@lcctju #17924 change `SetFuseParameterMemorySize(uint64_t memory_size)` to `SetFuseParameterMemorySize(double memory_size)`. Could you test the develop branch in your environment?

**Comment by lcctju** [comment]
> @lcctju #17924 change `SetFuseParameterMemorySize(uint64_t memory_size)` to `SetFuseParameterMemorySize(double memory_size)`. Could you test the develop branch in your environment?

I can build successfully.
