### ISSUE TITLE
训练使用机器越多，cost下降越慢

### ISSUE THREAD

**Issue by AWSWXY** [PaddlePaddle/Paddle#17894]
相同的代码
使用40个节点cost缓慢下降
使用80个节点 cost不下降

**Comment by AWSWXY** [comment]
相同的代码和数据
使用40个节点cost缓慢下降
使用80个节点 cost不下降
http://10.87.108.38:8900/fileview.html?path=/home/disk1/normandy/maybach/app-user-20190606023619-1949/   40个节点日志
http://10.197.72.150:8900/fileview.html?path=/home/disk1/normandy/maybach/app-user-20190606023517-8974/     80个节点日志

**Comment by zhaoyuchen2018** [comment]
麻烦提供下完整的代码和数据，日志里面没有太多信息
