### ISSUE TITLE
SetNumThreads(1) breaks slim multi-threading

### ISSUE THREAD

**Issue by sfraczek** [PaddlePaddle/Paddle#17903]
Hi,

https://github.com/PaddlePaddle/Paddle/blob/e2c1b7c354c9ca6720228f1b55bfc4c6a6f82292/paddle/fluid/inference/api/analysis_predictor.cc#L240

this change breaks int8 slim tests. Multi-threading works until int8 warm-up phase and after that, everything runs on 1 thread only.
The test series such as test_analyzer_int8_resnet50 are not affected.

Is this change necessary?
Any suggestions how we can fix it?

**Comment by luotao1** [comment]
> Is this change necessary

Yes, we only want to use multi-thread inside `AnalysisPredictor::ZeroCopyRun()` and `AnalysisPredictor::Run()`. You can see the reason in #17801.

> this change breaks int8 slim tests, Multi-threading works until int8 warm-up phase and after that, everything runs on 1 thread only.

How about making `mkldnn_quantizer_config` support `cpu_math_library_num_threads`?

**Comment by sfraczek** [comment]
Should we set number of threads from python before and after calling exe->Run?

**Comment by sfraczek** [comment]
We never hit that `  paddle::platform::SetNumThreads(config_.cpu_math_library_num_threads());` line again from python after it was set to 1 at the end of call. It seems python is calling different method later.

**Comment by luotao1** [comment]
> It seems python is calling different method later

If python is calling a different method, #17801 will not affect it. Could you find the method python called at first?

> Should we set number of threads from python before and after calling exe->Run

Could you give `git diff` of your change?

**Comment by sfraczek** [comment]
I don't have a diff - I mean here (edit ~https://github.com/PaddlePaddle/Paddle/pull/17814/files#diff-79b68fb950ff79f6c979a5b3774ca8f7R199~ https://github.com/PaddlePaddle/Paddle/pull/17634/files?file-filters%5B%5D=.cc&file-filters%5B%5D=.h&file-filters%5B%5D=.py&owned-by%5B%5D=#diff-c06e05c8a775f42a2c811269a7d9e88fR140) this calls Executor and it runs on 1 thread.

I see two options here:
1. surround with pybind calls to setnumthreads like you did here: https://github.com/PaddlePaddle/Paddle/pull/17801/files#diff-859bde2f1a0236fbd9b5ac0c67026fb7R590
2. move the setnumthreads calls to inside executor->run somehow

**Comment by luotao1** [comment]
C++ `AnalysisPredictor::ZeroCopyRun()` and `AnalysisPredictor::Run()` don't change `exe.run` python executor. Thus, `exe.run` python executor should use one-thread in default.

Maybe you can use `FLAGS_OMP_NUM_THREADS=xxx` for the whole script like before.

**Comment by sfraczek** [comment]
We've been using FLAGS_OMP_NUM_THREADS. That python script first runs calibration somewhere which goes through AnalysisPredictor::Run and it sets threads to 1 at the end and this is why later exe.run works on 1 thread. If not for that line, exe.run was running on as many threads as was set by FLAGS_OMP_NUM_THREADS

**Comment by sfraczek** [comment]
I mistook the file. I meant this one I think. I cannot access my dev machine today to double check everything. sorry for this.
https://github.com/PaddlePaddle/Paddle/pull/17634/files?file-filters%5B%5D=.cc&file-filters%5B%5D=.h&file-filters%5B%5D=.py&owned-by%5B%5D=#diff-c06e05c8a775f42a2c811269a7d9e88fR140

**Comment by luotao1** [comment]
Got it. Thus, how about trigger `FLAGS_OMP_NUM_THREADS` again before later `exe.run`?

**Comment by sfraczek** [comment]
> Got it. Thus, how about trigger `FLAGS_OMP_NUM_THREADS` again before later `exe.run`?

What do you mean?

**Comment by luotao1** [comment]
https://github.com/PaddlePaddle/Paddle/blob/209a3f4e095c6a3ca2d7684e667da15d8bffe00f/python/paddle/fluid/contrib/slim/tests/test_mkldnn_int8_quantization_strategy.py#L140-L144
`export OMP_NUM_THREADS=xxx` again before above codes?

**Comment by sfraczek** [comment]
The value of OMP_NUM_THREADS doesn't change throughout the execution
