### ISSUE TITLE
batch size 已经调到很小了，但是还是报错显存申请失败

### ISSUE THREAD

**Issue by xiangyubo** [PaddlePaddle/Paddle#17917]
如果您没有查询到相似问题，为快速解决您的提问，建立issue时请提供如下细节信息：
- 标题：简洁、精准概括您的问题，例如“Insufficient Memory xxx" ”
- 版本、环境信息：
    1）PaddlePaddle版本：1.4.1
    3）GPU：v100，显存16G
    4）系统环境：
- 训练信息
    1）单机单卡

训练 YOLOv3的时候，一开始我的 batch_size 是128，会报错说申请不到足够的显存；我逐步调小都12，依然不行。我配合着调小 FLAGS_fraction_of_gpu_memory_to_use 也没有作用，最后的时候这个环境变量是0.72， batch size：12

一直报错
W0608 14:36:02.768568   897 system_allocator.cc:125] Cannot malloc 11053.8 MB GPU memory. Please shrink FLAGS_fraction_of_gpu_memory_to_use or FLAGS_initial_gpu_memory_in_mb or FLAGS_reallocate_gpu_memory_in_mbenvironment variable to a lower value. Current FLAGS_fraction_of_gpu_memory_to_use value is 0.72. Current FLAGS_initial_gpu_memory_in_mb value is 0. Current FLAGS_reallocate_gpu_memory_in_mb value is 0

**Comment by heavengate** [comment]
YOLOv3的--batch_size是指单卡上的batch size，默认是8，使用8卡，总batch size是64，看你batch size=128应该是总batch size，这个batch size要除以卡数来设置，另外YOLOv3目前在22G显存上单卡最大batch size=14，大于这个值会显存不足，请参考设置

**Comment by xiangyubo** [comment]
> YOLOv3的--batch_size是指单卡上的batch size，默认是8，使用8卡，总batch size是64，看你batch size=128应该是总batch size，这个batch size要除以卡数来设置，另外YOLOv3目前在22G显存上单卡最大batch size=14，大于这个值会显存不足，请参考设置

好的，谢谢官方说明，我自己调到4才可以。没想到这个网络这么吃显存

**Comment by heavengate** [comment]
> > YOLOv3的--batch_size是指单卡上的batch size，默认是8，使用8卡，总batch size是64，看你batch size=128应该是总batch size，这个batch size要除以卡数来设置，另外YOLOv3目前在22G显存上单卡最大batch size=14，大于这个值会显存不足，请参考设置
> 
> 好的，谢谢官方说明，我自己调到4才可以。没想到这个网络这么吃显存

如果对batch size需求较大的话可以关闭train.py里面的memory_optimize然后开启如下Flag：
export FLAGS_fast_eager_deletion_mode=1
export FLAGS_eager_delete_tensor_gb=0.0
export FLAGS_fraction_of_gpu_memory_to_use=0.98
