### ISSUE TITLE
使用grid_sampler api后 前向传播预测正常，开启反向传播优化后报错

### ISSUE THREAD

**Issue by fatwolf** [PaddlePaddle/Paddle#17919]
- 版本、环境信息：
    1）PaddlePaddle版本：1.4
- 训练信息
    1）单机单卡
    2）GPU CPU同样错误
    3）Operator信息：
- 复现信息：在模型训练过程中 如果开启优化 并且反向传播路径包含
   i1_pred = paddle.fluid.layers.grid_sampler(i0, grid)
则会报以下错误
memory_optimize is deprecated. Use CompiledProgram and Executor
W0608 16:45:27.233000 59468 device_context.cc:261] Please NOTE: device: 0, CUDA Capability: 61, Driver API Version: 9.2, Runtime API Version: 9.0
W0608 16:45:27.235400 59468 device_context.cc:269] device: 0, cuDNN Version: 7.0.
total number 1
*** Aborted at 1559983528 (unix time) try "date -d @1559983528" if you are using GNU date ***
PC: @                0x0 (unknown)
*** SIGSEGV (@0x68) received by PID 59468 (TID 0x7f55c128d740) from PID 104; stack trace: ***
    @     0x7f55c0eab890 (unknown)
    @     0x7f5583899e63 paddle::framework::Tensor::Resize()
    @     0x7f55825df397 paddle::operators::CUDNNGridSampleGradOpKernel<>::Compute()
    @     0x7f55825dfa73 _ZNSt17_Function_handlerIFvRKN6paddle9framework16ExecutionContextEEZNKS1_24OpKernelRegistrarFunctorINS0_8platform9CUDAPlaceELb0ELm0EINS0_9operators27CUDNNGridSampleGradOpKernelIfEENSA_IdEEEEclEPKcSF_iEUlS4_E_E9_M_invokeERKSt9_Any_dataS4_
    @     0x7f5583846326 paddle::framework::OperatorWithKernel::RunImpl()
    @     0x7f5583846a94 paddle::framework::OperatorWithKernel::RunImpl()
    @     0x7f55838443bc paddle::framework::OperatorBase::Run()
    @     0x7f5581d293ae paddle::framework::Executor::RunPreparedContext()
    @     0x7f5581d2a1ef paddle::framework::Executor::Run()
    @     0x7f5581ba689e _ZZN8pybind1112cpp_function10initializeIZN6paddle6pybindL18pybind11_init_coreERNS_6moduleEEUlRNS2_9framework8ExecutorERKNS6_11ProgramDescEPNS6_5ScopeEibbRKSt6vectorISsSaISsEEE97_vIS8_SB_SD_ibbSI_EINS_4nameENS_9is_methodENS_7siblingEEEEvOT_PFT0_DpT1_EDpRKT2_ENUlRNS_6detail13function_callEE1_4_FUNES10_
    @     0x7f5581be977e pybind11::cpp_function::dispatcher()
    @     0x555f84a8a2d8 PyCFunction_Call
    @     0x555f84ae5dd6 PyEval_EvalFrameEx
    @     0x555f84ae5351 PyEval_EvalFrameEx
    @     0x555f84ae5351 PyEval_EvalFrameEx
    @     0x555f84aeb2ad PyEval_EvalCodeEx
    @     0x555f84aec1fc PyEval_EvalCode
    @     0x555f84b498d4 run_mod
    @     0x555f84b4af41 PyRun_FileExFlags
    @     0x555f84b4b15e PyRun_SimpleFileExFlags
    @     0x555f84b4b80d Py_Main
    @     0x555f84a15571 main
    @     0x7f55c0ac9b97 __libc_start_main
    @     0x555f84aedf38 (unknown)
Segmentation fault (core dumped)

若反向传播不包含该API 或仅运行前向传播 关闭optimizer 则代码可正常运行

**Comment by heavengate** [comment]
如果grid_sampler的第一个参数是fluid.layers.data指定的输入的话，在data里设置stop_gradient=False 参考https://github.com/PaddlePaddle/Paddle/issues/15583

**Comment by fatwolf** [comment]
> 
> 
> 如果grid_sampler的第一个参数是fluid.layers.data指定的输入的话，在data里设置stop_gradient=False 参考#15583

感谢 问题解决
