### ISSUE TITLE
使用1.4.1的编译好的so预测库， 预测时显存占用量比 python 版本的paddle 1.4.1 大很多。

### ISSUE THREAD

**Issue by xhuanlc** [PaddlePaddle/Paddle#17916]
使用1.4.1的预测库，来自BCLOUD编译，p40GPU。
预测时显存占用量比 python 版本的paddle 1.4.1 大很多。
模型的输入输出均为图片，用到了2d conv ， transposed 2d conv， cat等op。
1280*720的图片在python 的paddle下 4G显存足够，  用编译好的so预测，22G显存会爆掉。
尝试开启enable_ir_optim: 1，报如下错误：
![image](https://user-images.githubusercontent.com/11305017/59141811-1b005200-89e6-11e9-8b87-e8075812fda9.png)

**Comment by Superjomn** [comment]
![image](https://user-images.githubusercontent.com/328693/59148653-46169000-8a3e-11e9-85c0-0fef1434ade2.png)

这个是打开了 TensorRT 子图？ 如果不需要的话可以不要打开。

另外，显存有开关控制， 可能memory pool 设置的比例太高

NativeConfig 是 https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/fluid/inference/api/paddle_api.h#L291

**Comment by NHZlX** [comment]
https://github.com/PaddlePaddle/Paddle/pull/17925
