### ISSUE TITLE
希望增加从checkpoint文件直接解析参数的api

### ISSUE THREAD

**Issue by yangapku** [PaddlePaddle/Paddle#17914]
如题，如果我拿到了一份checkpoint文件（自己训的或者从别人手中拿到），想不搭图就直接从checkpoint里面解析参数，用于了解checkpoint有哪些参数、检查checkpoint参数的值、以及进一步可能转换成其他格式，目前paddle似乎没有这样的api。唯一的办法是在代码里面先搭一个图，在图里面定义出checkpoint的所有参数，之后用`paddle.fluid.io.load_persistables`读取checkpoint，最后再分别用`numpy.array(fluid.global_scope().find_var(param_name).get_tensor())`来看，过于麻烦。而且从直觉上，checkpoint二进制文件本身应该包含了完整的参数名和参数值信息，我按道理就没有必要搭这个图，为什么没有一个直接解析二进制文件参数的api？
对比其他框架，torch的pt文件可以直接pickle读取，框架也提供了`torch.load()`。Tensorflow里面也有`pywrap_tensorflow.NewCheckpointReader()`都是可以直接读取的，我觉得paddle也有实现这样api的必要。

**Comment by junjun315** [comment]
你好。 paddle一般的checkpoint文件通常是通过使用save_vars 或者save_persistables接口来保存的，只包含参数的文件。确实没有图建构的保存。
如果需要存的话，一般可以通过save_inference_models 来保存结构。 只是这个接口当前是面向做预测的，会对图有一些操作。
确实可以如您所说对接口进行优化。我们已经纳入了修改计划里，请保持关注后续版本！

**Comment by yangapku** [comment]
您好，我的意思和图建构的保存与否无关，就是从只包含参数的二进制文件里面，不搭图直接从checkpoint里面解析出参数（主要是persistables）的名字和值。这个是为了了解checkpoint有哪些参数、检查checkpoint参数的值、以及进一步可能转换成其他格式，和`torch.load()`以及`pywrap_tensorflow.NewCheckpointReader()`达到相似的目的。

**Comment by junjun315** [comment]
当前如果你拿到的是save_vars一类的接口保存的文件是不包含参数对象信息的，只有数据值。只能从所在文件目录结构里推断出参数名字。确实不是一个好的设计，我们后面有新的接口计划。 

torch.load() 是从一个pickle保存的对象中恢复的参数结构；而tf相应的接口则是有自己的参数结构文件格式。

**Comment by sparrowhole** [comment]
请问现在这个API开发进度如何呢，我也遇到此需求了！
