### ISSUE TITLE
Cannot find variable fc_0.tmp_1 at [/paddle/paddle/fluid/framework/op_desc.cc:193]

### ISSUE THREAD

**Issue by superwj1990** [PaddlePaddle/Paddle#17932]
我在用fluid.layers.concat函数concat两个模型的fc输出时，报了paddle.fluid.core.EnforceNotMet: Cannot find variable fc_0.tmp_1 at [/paddle/paddle/fluid/framework/op_desc.cc:193]这个错。

**Comment by qingqing01** [comment]
报错信息，找不到一个fc的输出，请给出可复现的代码片段

**Comment by qingqing01** [comment]
已Hi上沟通，concat的内容不在一个program里，需要放到一个program里才行。
