### ISSUE TITLE
C++预测模块无输出

### ISSUE THREAD

**Issue by fabregasguo** [PaddlePaddle/Paddle#17956]
1）PaddlePaddle版本：fluid v1.3
    2）CPU：预测若用CPU，请提供CPU型号，MKL/OpenBlas/MKLDNN/等数学库使用情况
    3）GPU：无
    4）系统环境：请您描述系统类型、版本（如Mac OS 10.14），Python版本
-预测信息
    1）C++预测：请您提供预测库安装包的版本信息，及其中的version.txt文件
    2）CMake包含路径的完整命令
    3）API信息（如调用请提供）
    4）预测库来源：BCLOUD编译
- 复现信息：如为报错，请给出复现环境、复现步骤
- 问题描述：预测无输出

     std::vector<paddle::PaddleTensor>  outputs;
    LOG(FATAL) << "id_list size guojun " << id_list.size();
    predictor->Run(input_slots, &outputs, id_list.size());
    LOG(FATAL) << "guojun shape size is " << outputs.size() ;
输出为空

**Comment by Shixiaowei02** [comment]
如 hi 沟通，Paddle 这边没能复现问题，测试输出结果是正常的。请您准备一个单测简化问题，继续调试。谢谢！
