### ISSUE TITLE
paddle v2 与v1 不兼容吗？我安装好v2版本以后，运行v1版本程序报错Python Error: <type 'exceptions.ImportError'> : No module named paddle.trainer.config_parser Python Callstack:  Import paddle.trainer.config_parserError

### ISSUE THREAD

**Issue by pwllr** [PaddlePaddle/Paddle#1795]

**Comment by typhoonzero** [comment]
请问您是以什么方式安装的呢，是否是使用Docker？

如果问题和 https://github.com/PaddlePaddle/Paddle/issues/1785 相同，Docker的镜像会尽快更新，可以先使用`export PYTHONHOME=/usr/local` 解决。

**Comment by Yancey1989** [comment]
Close the inactive issue, if the latest Docker image has the same problem, please reopen this issue.
