### ISSUE TITLE
paddle op比较多，建议增加一个教程，把numpy的常用操作与paddle op对应起来，方便大家入门学习

### ISSUE THREAD

**Issue by lgone2000** [PaddlePaddle/Paddle#17963]
比如numpy常见的一些操作
ones, zeros , where,  index,  astype,  argsort  

也可以举一些高级点的示例，说明一些损失或者功能如何实现。
比如怎么实现下面功能
a[a<0] = -100
a[3:5, -1] *= 2
如果能做到和numpy操作等效的话，差不多所有的复杂op都可以从简单op组合实现。比如NMS, linear-interplation等

**Comment by qingqing01** [comment]
多谢建议~
