### ISSUE TITLE
PaddlePaddle的单机多GPU调用，直接修改trainer_count参数即可？还是需要修改demo的算法？

### ISSUE THREAD

**Issue by ssdyue** [PaddlePaddle/Paddle#1796]

**Comment by luotao1** [comment]
直接改traincer_count参数即可

**Comment by ssdyue** [comment]
电脑有2个GPU，修改参数trainer_count=2，于是train，迭代结束后，出现如下错误：

F0417 02:21:10.778404   278 PyDataProvider2.cpp:572] Check failed: poolPtr != nullptr 
*** Check failure stack trace: ***
    @     0x7fe46100bdaa  (unknown)
    @     0x7fe46100bce4  (unknown)
    @     0x7fe46100b6e6  (unknown)
    @     0x7fe46100e687  (unknown)
    @           0x591a9a  paddle::PyDataProvider2::getNextBatchInternal()
    @           0x59604e  paddle::DoubleBuffer::asyncLoadBatch()
    @     0x7fe460b88a60  (unknown)
    @     0x7fe461e1e184  start_thread
    @     0x7fe4602f037d  (unknown)
    @              (nil)  (unknown)
/usr/local/bin/paddle: line 109:   261 Aborted                 (core dumped) ${DEBUGGER} $MYDIR/../opt/paddle/bin/paddle_trainer ${@:2}

**Comment by reyoung** [comment]
@ssdyue  该问题已经在最新的paddle里面修复了，请使用develop分支下的Paddle。

**Comment by ssdyue** [comment]
@reyoung 谢谢您的回答！使用了develop分支下的Paddle，在image_classification demo中train，但是还是有以上问题，不知道这个会不会影响训练的模型。另外，无论在单GPU还是多GPU上predict，都会出现错误：
I0417 14:07:48.356452    84 GradientMachine.cpp:123] Loading parameters from cifar_vgg_model/pass-00002/
Traceback (most recent call last):
  File "prediction.py", line 159, in <module>
    obj.predict(image, output_layer)
  File "prediction.py", line 135, in predict
    prob = self.forward(data, output_layer)
  File "prediction.py", line 129, in forward
    return output[output_layer]['value'].mean(0)
ValueError: field named value not found

我安装的是PaddlePaddle-docker image，有些demo能run，但有些不行，很是疑惑！
