### ISSUE TITLE
ubuntu 16.04 RTX2080Ti 安装完GPU版本后，检测安装是否完好时出错

### ISSUE THREAD

**Issue by Knightsll** [PaddlePaddle/Paddle#17977]
pip 安装GPU版本1.4.1，但运行install_check.run_check()时出错
cuda9.1  cudnn 7.1.3  RTX2080Ti

execution failed at [/paddle/paddle/fluid/operator/math/blas_impl.cu.h:34]
![image](https://user-images.githubusercontent.com/6836917/59248921-4d17eb00-8c56-11e9-8308-18e0206a7dd8.png)

**Comment by luotao1** [comment]
same issue with #17496

**Comment by kolinwei** [comment]
能贴下完整的错误log吗

**Comment by Knightsll** [comment]
Running Verify Fluid Program ... 
W0520 16:52:06.161931 27216 device_context.cc:261] Please NOTE: device: 0, CUDA Capability: 75, Driver API Version: 10.0, Runtime API Version: 9.0
W0520 16:52:06.187935 27216 device_context.cc:269] device: 0, cuDNN Version: 7.0.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/lab/liujiepeng/MachineComprehension/DuReader/paddle_py35_even/lib/python3.5/site-packages/paddle/fluid/install_check.py", line 65, in run_check
    fetch_list=[out.name, param_grads[1].name])
  File "/home/lab/liujiepeng/MachineComprehension/DuReader/paddle_py35_even/lib/python3.5/site-packages/paddle/fluid/executor.py", line 565, in run
    use_program_cache=use_program_cache)
  File "/home/lab/liujiepeng/MachineComprehension/DuReader/paddle_py35_even/lib/python3.5/site-packages/paddle/fluid/executor.py", line 642, in _run
    exe.run(program.desc, scope, 0, True, True, fetch_var_name)
paddle.fluid.core.EnforceNotMet: Invoke operator mul error.
Python Callstacks: 
  File "/home/lab/liujiepeng/MachineComprehension/DuReader/paddle_py35_even/lib/python3.5/site-packages/paddle/fluid/framework.py", line 1654, in append_op
    attrs=kwargs.get("attrs", None))
  File "/home/lab/liujiepeng/MachineComprehension/DuReader/paddle_py35_even/lib/python3.5/site-packages/paddle/fluid/dygraph/layer_object_helper.py", line 52, in append_op
    stop_gradient=stop_gradient)
  File "/home/lab/liujiepeng/MachineComprehension/DuReader/paddle_py35_even/lib/python3.5/site-packages/paddle/fluid/dygraph/nn.py", line 919, in forward
    "y_num_col_dims": 1
  File "/home/lab/liujiepeng/MachineComprehension/DuReader/paddle_py35_even/lib/python3.5/site-packages/paddle/fluid/dygraph/layers.py", line 158, in __call__
    outputs = self.forward(*inputs)
  File "/home/lab/liujiepeng/MachineComprehension/DuReader/paddle_py35_even/lib/python3.5/site-packages/paddle/fluid/install_check.py", line 37, in forward
    x = self._fc1(inputs)
  File "/home/lab/liujiepeng/MachineComprehension/DuReader/paddle_py35_even/lib/python3.5/site-packages/paddle/fluid/dygraph/layers.py", line 158, in __call__
    outputs = self.forward(*inputs)
  File "/home/lab/liujiepeng/MachineComprehension/DuReader/paddle_py35_even/lib/python3.5/site-packages/paddle/fluid/install_check.py", line 58, in run_check
    out = simple_layer(inp)
  File "<stdin>", line 1, in <module>
C++ Callstacks: 
CUBLAS: execution failed,  at [/paddle/paddle/fluid/operators/math/blas_impl.cu.h:34]
PaddlePaddle Call Stacks: 
0       0x7fb372fe4c90p void paddle::platform::EnforceNotMet::Init<char const*>(char const*, char const*, int) + 352
1       0x7fb372fe5009p paddle::platform::EnforceNotMet::EnforceNotMet(std::__exception_ptr::exception_ptr, char const*, int) + 137
2       0x7fb373250097p void paddle::operators::math::Blas<paddle::platform::CUDADeviceContext>::GEMM<float>(CBLAS_TRANSPOSE, CBLAS_TRANSPOSE, int, int, int, float, float const*, float const*, float, float*) const + 1815
3       0x7fb3736caa6cp void paddle::operators::math::Blas<paddle::platform::CUDADeviceContext>::MatMul<float>(paddle::framework::Tensor const&, bool, paddle::framework::Tensor const&, bool, float, paddle::framework::Tensor*, float) const + 844
4       0x7fb3736caea6p paddle::operators::MulKernel<paddle::platform::CUDADeviceContext, float>::Compute(paddle::framework::ExecutionContext const&) const + 662
5       0x7fb3736cb093p std::_Function_handler<void (paddle::framework::ExecutionContext const&), paddle::framework::OpKernelRegistrarFunctor<paddle::platform::CUDAPlace, false, 0ul, paddle::operators::MulKernel<paddle::platform::CUDADeviceContext, float>, paddle::operators::MulKernel<paddle::platform::CUDADeviceContext, double>, paddle::operators::MulKernel<paddle::platform::CUDADeviceContext, paddle::platform::float16> >::operator()(char const*, char const*, int) const::{lambda(paddle::framework::ExecutionContext const&)#1}>::_M_invoke(std::_Any_data const&, paddle::framework::ExecutionContext const&) + 35
6       0x7fb374c74326p paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&, paddle::framework::RuntimeContext*) const + 662
7       0x7fb374c74a94p paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&) const + 292
8       0x7fb374c723bcp paddle::framework::OperatorBase::Run(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&) + 332
9       0x7fb3731573aep paddle::framework::Executor::RunPreparedContext(paddle::framework::ExecutorPrepareContext*, paddle::framework::Scope*, bool, bool, bool) + 382
10      0x7fb3731581efp paddle::framework::Executor::Run(paddle::framework::ProgramDesc const&, paddle::framework::Scope*, int, bool, bool, std::vector<std::string, std::allocator<std::string> > const&, bool) + 143
11      0x7fb372fd489ep
12      0x7fb37301777ep
13      0x55c1828a34e8p PyCFunction_Call + 120
14      0x55c1828ffec4p PyEval_EvalFrameEx + 23284
15      0x55c1828ff490p PyEval_EvalFrameEx + 20672
16      0x55c1828ff490p PyEval_EvalFrameEx + 20672
17      0x55c1828fae90p PyEval_EvalFrameEx + 2752
18      0x55c18290503dp PyEval_EvalCodeEx + 525
19      0x55c182905f5cp PyEval_EvalCode + 28
20      0x55c182962454p
21      0x55c18282eb5ep PyRun_InteractiveOneObject + 709
22      0x55c18282ed01p PyRun_InteractiveLoopFlags + 239
23      0x55c18282ed62p
24      0x55c18282f080p
25      0x55c18282f871p main + 225
26      0x7fb3b31d2830p __libc_start_main + 240
27      0x55c182907808p


显卡是2080Ti, 运行tensorflow-gpu没有问题

**Comment by Knightsll** [comment]
Running Verify Fluid Program ... 
W0613 08:19:27.455412 26630 device_context.cc:261] Please NOTE: device: 0, CUDA Capability: 75, Driver API Version: 10.1, Runtime API Version: 9.0
W0613 08:19:27.867404 26630 device_context.cc:269] device: 0, cuDNN Version: 7.0.
W0613 08:19:27.867480 26630 device_context.cc:293] WARNING: device: 0. The installed Paddle is compiled with CUDNN 7.3, but CUDNN version in your machine is 7.1, which may cause serious incompatible bug. Please recompile or reinstall Paddle with compatible CUDNN version.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/yjb/miniconda3/envs/paddle/lib/python3.7/site-packages/paddle/fluid/install_check.py", line 65, in run_check
    fetch_list=[out.name, param_grads[1].name])
  File "/home/yjb/miniconda3/envs/paddle/lib/python3.7/site-packages/paddle/fluid/executor.py", line 565, in run
    use_program_cache=use_program_cache)
  File "/home/yjb/miniconda3/envs/paddle/lib/python3.7/site-packages/paddle/fluid/executor.py", line 642, in _run
    exe.run(program.desc, scope, 0, True, True, fetch_var_name)
paddle.fluid.core.EnforceNotMet: Invoke operator mul error.
Python Callstacks: 
  File "/home/yjb/miniconda3/envs/paddle/lib/python3.7/site-packages/paddle/fluid/framework.py", line 1654, in append_op
    attrs=kwargs.get("attrs", None))
  File "/home/yjb/miniconda3/envs/paddle/lib/python3.7/site-packages/paddle/fluid/dygraph/layer_object_helper.py", line 52, in append_op
    stop_gradient=stop_gradient)
  File "/home/yjb/miniconda3/envs/paddle/lib/python3.7/site-packages/paddle/fluid/dygraph/nn.py", line 919, in forward
    "y_num_col_dims": 1
  File "/home/yjb/miniconda3/envs/paddle/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 158, in __call__
    outputs = self.forward(*inputs)
  File "/home/yjb/miniconda3/envs/paddle/lib/python3.7/site-packages/paddle/fluid/install_check.py", line 37, in forward
    x = self._fc1(inputs)
  File "/home/yjb/miniconda3/envs/paddle/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 158, in __call__
    outputs = self.forward(*inputs)
  File "/home/yjb/miniconda3/envs/paddle/lib/python3.7/site-packages/paddle/fluid/install_check.py", line 58, in run_check
    out = simple_layer(inp)
  File "<stdin>", line 1, in <module>
C++ Callstacks: 
CUBLAS: execution failed,  at [/paddle/paddle/fluid/operators/math/blas_impl.cu.h:34]
PaddlePaddle Call Stacks: 
0       0x7f9823064d60p void paddle::platform::EnforceNotMet::Init<char const*>(char const*, char const*, int) + 352
1       0x7f98230650d9p paddle::platform::EnforceNotMet::EnforceNotMet(std::__exception_ptr::exception_ptr, char const*, int) + 137
2       0x7f98232d01b7p void paddle::operators::math::Blas<paddle::platform::CUDADeviceContext>::GEMM<float>(CBLAS_TRANSPOSE, CBLAS_TRANSPOSE, int, int, int, float, float const*, float const*, float, float*) const + 1815
3       0x7f982374ab8cp void paddle::operators::math::Blas<paddle::platform::CUDADeviceContext>::MatMul<float>(paddle::framework::Tensor const&, bool, paddle::framework::Tensor const&, bool, float, paddle::framework::Tensor*, float) const + 844
4       0x7f982374afc6p paddle::operators::MulKernel<paddle::platform::CUDADeviceContext, float>::Compute(paddle::framework::ExecutionContext const&) const + 662
5       0x7f982374b1b3p std::_Function_handler<void (paddle::framework::ExecutionContext const&), paddle::framework::OpKernelRegistrarFunctor<paddle::platform::CUDAPlace, false, 0ul, paddle::operators::MulKernel<paddle::platform::CUDADeviceContext, float>, paddle::operators::MulKernel<paddle::platform::CUDADeviceContext, double>, paddle::operators::MulKernel<paddle::platform::CUDADeviceContext, paddle::platform::float16> >::operator()(char const*, char const*, int) const::{lambda(paddle::framework::ExecutionContext const&)#1}>::_M_invoke(std::_Any_data const&, paddle::framework::ExecutionContext const&) + 35
6       0x7f9824cf4446p paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&, paddle::framework::RuntimeContext*) const + 662
7       0x7f9824cf4bb4p paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&) const + 292
8       0x7f9824cf24dcp paddle::framework::OperatorBase::Run(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&) + 332
9       0x7f98231d74bep paddle::framework::Executor::RunPreparedContext(paddle::framework::ExecutorPrepareContext*, paddle::framework::Scope*, bool, bool, bool) + 382
10      0x7f98231d82ffp paddle::framework::Executor::Run(paddle::framework::ProgramDesc const&, paddle::framework::Scope*, int, bool, bool, std::vector<std::string, std::allocator<std::string> > const&, bool) + 143
11      0x7f982305496ep
12      0x7f982309776ep
13      0x560fb244f6e4p _PyMethodDef_RawFastCallKeywords + 612
14      0x560fb244f801p _PyCFunction_FastCallKeywords + 33
15      0x560fb24ab7aep _PyEval_EvalFrameDefault + 21374
16      0x560fb23ec4f9p _PyEval_EvalCodeWithName + 761
17      0x560fb244ea27p _PyFunction_FastCallKeywords + 903
18      0x560fb24a78fep _PyEval_EvalFrameDefault + 5326
19      0x560fb23ec4f9p _PyEval_EvalCodeWithName + 761
20      0x560fb244ea27p _PyFunction_FastCallKeywords + 903
21      0x560fb24a78fep _PyEval_EvalFrameDefault + 5326
22      0x560fb244e79bp _PyFunction_FastCallKeywords + 251
23      0x560fb24aaed9p _PyEval_EvalFrameDefault + 19113
24      0x560fb23ec4f9p _PyEval_EvalCodeWithName + 761
25      0x560fb23ed3c4p PyEval_EvalCodeEx + 68
26      0x560fb23ed3ecp PyEval_EvalCode + 28
27      0x560fb2505874p
28      0x560fb23cbda8p
29      0x560fb23cbf5ep PyRun_InteractiveLoopFlags + 243
30      0x560fb23cbffep
31      0x560fb23cca88p
32      0x560fb2510f7cp _Py_UnixMain + 60
33      0x7f984fc9f830p __libc_start_main + 240
34      0x560fb24b6122p
@kolinwei  请问是哪里出了问题， CPU版本能运行

**Comment by jasonlbx13** [comment]
出现了同样的错误,已解决
目前paddlepaddle尚不支持在conda自环境中进行安装
需要在base环境下使用pip3安装paddlepaddle,并安装cudnn(cudnn要从网上下载安装包,不能使用conda安装)
之后在基础环境下进行测试即可发现check不再报错

**Comment by bruce1408** [comment]
> 出现了同样的错误,已解决
> 目前paddlepaddle尚不支持在conda自环境中进行安装
> 需要在base环境下使用pip3安装paddlepaddle,并安装cudnn(cudnn要从网上下载安装包,不能使用conda安装)
> 之后在基础环境下进行测试即可发现check不再报错

我在base 环境中安装依然出现错误,如下:
>>> import paddle.fluid
>>> paddle.fluid.install_check.run_check()
Running Verify Fluid Program ... 
W0819 16:56:44.087344 19839 device_context.cc:259] Please NOTE: device: 0, CUDA Capability: 75, Driver API Version: 10.1, Runtime API Version: 10.0
W0819 16:56:44.088443 19839 device_context.cc:267] device: 0, cuDNN Version: 7.0.
W0819 16:56:44.088451 19839 device_context.cc:293] WARNING: device: 0. The installed Paddle is compiled with CUDNN 7.4, but CUDNN version in your machine is 7.0, which may cause serious incompatible bug. Please recompile or reinstall Paddle with compatible CUDNN version.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/bruce/anaconda3/lib/python3.6/site-packages/paddle/fluid/install_check.py", line 123, in run_check
    test_simple_exe()
  File "/home/bruce/anaconda3/lib/python3.6/site-packages/paddle/fluid/install_check.py", line 121, in test_simple_exe
    fetch_list=[out0.name, param_grads[1].name])
  File "/home/bruce/anaconda3/lib/python3.6/site-packages/paddle/fluid/executor.py", line 651, in run
    use_program_cache=use_program_cache)
  File "/home/bruce/anaconda3/lib/python3.6/site-packages/paddle/fluid/executor.py", line 749, in _run
    exe.run(program.desc, scope, 0, True, True, fetch_var_name)
paddle.fluid.core_avx.EnforceNotMet: Invoke operator mul error.
Python Callstacks: 
  File "/home/bruce/anaconda3/lib/python3.6/site-packages/paddle/fluid/framework.py", line 1771, in append_op
    attrs=kwargs.get("attrs", None))
  File "/home/bruce/anaconda3/lib/python3.6/site-packages/paddle/fluid/dygraph/layer_object_helper.py", line 52, in append_op
    stop_gradient=stop_gradient)
  File "/home/bruce/anaconda3/lib/python3.6/site-packages/paddle/fluid/dygraph/nn.py", line 945, in forward
    "y_num_col_dims": 1
  File "/home/bruce/anaconda3/lib/python3.6/site-packages/paddle/fluid/dygraph/layers.py", line 162, in __call__
    outputs = self.forward(*inputs)
  File "/home/bruce/anaconda3/lib/python3.6/site-packages/paddle/fluid/install_check.py", line 40, in forward
    x = self._fc1(inputs)
  File "/home/bruce/anaconda3/lib/python3.6/site-packages/paddle/fluid/dygraph/layers.py", line 162, in __call__
    outputs = self.forward(*inputs)
  File "/home/bruce/anaconda3/lib/python3.6/site-packages/paddle/fluid/install_check.py", line 113, in test_simple_exe
    out0 = simple_layer0(inp0)
  File "/home/bruce/anaconda3/lib/python3.6/site-packages/paddle/fluid/install_check.py", line 123, in run_check
    test_simple_exe()
  File "<stdin>", line 1, in <module>
C++ Callstacks: 
CUBLAS: execution failed,  at [/paddle/paddle/fluid/operators/math/blas_impl.cu.h:34]
PaddlePaddle Call Stacks: 
0       0x7f26cb439890p void paddle::platform::EnforceNotMet::Init<char const*>(char const*, char const*, int) + 352
1       0x7f26cb439c09p paddle::platform::EnforceNotMet::EnforceNotMet(std::__exception_ptr::exception_ptr, char const*, int) + 137
2       0x7f26cb68ae67p void paddle::operators::math::Blas<paddle::platform::CUDADeviceContext>::GEMM<float>(CBLAS_TRANSPOSE, CBLAS_TRANSPOSE, int, int, int, float, float const*, float const*, float, float*) const + 1815
3       0x7f26cbbf546cp void paddle::operators::math::Blas<paddle::platform::CUDADeviceContext>::MatMul<float>(paddle::framework::Tensor const&, bool, paddle::framework::Tensor const&, bool, float, paddle::framework::Tensor*, float) const + 860
4       0x7f26cbbf5913p paddle::operators::MulKernel<paddle::platform::CUDADeviceContext, float>::Compute(paddle::framework::ExecutionContext const&) const + 659
5       0x7f26cbbf5b03p std::_Function_handler<void (paddle::framework::ExecutionContext const&), paddle::framework::OpKernelRegistrarFunctor<paddle::platform::CUDAPlace, false, 0ul, paddle::operators::MulKernel<paddle::platform::CUDADeviceContext, float>, paddle::operators::MulKernel<paddle::platform::CUDADeviceContext, double>, paddle::operators::MulKernel<paddle::platform::CUDADeviceContext, paddle::platform::float16> >::operator()(char const*, char const*, int) const::{lambda(paddle::framework::ExecutionContext const&)#1}>::_M_invoke(std::_Any_data const&, paddle::framework::ExecutionContext const&) + 35
6       0x7f26cd4c7f67p paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&, paddle::framework::RuntimeContext*) const + 375
7       0x7f26cd4c8341p paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&) const + 529
8       0x7f26cd4c593cp paddle::framework::OperatorBase::Run(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&) + 332
9       0x7f26cb5c468ep paddle::framework::Executor::RunPreparedContext(paddle::framework::ExecutorPrepareContext*, paddle::framework::Scope*, bool, bool, bool) + 382
10      0x7f26cb5c772fp paddle::framework::Executor::Run(paddle::framework::ProgramDesc const&, paddle::framework::Scope*, int, bool, bool, std::vector<std::string, std::allocator<std::string> > const&, bool) + 143
11      0x7f26cb42af1dp
12      0x7f26cb46c1a6p
13      0x563b1a17ab94p _PyCFunction_FastCallDict + 340
14      0x563b1a20a7cep
15      0x563b1a22ccbap _PyEval_EvalFrameDefault + 762
16      0x563b1a203a94p
17      0x563b1a204941p
18      0x563b1a20a755p
19      0x563b1a22da7ap _PyEval_EvalFrameDefault + 4282
20      0x563b1a203a94p
21      0x563b1a204941p
22      0x563b1a20a755p
23      0x563b1a22da7ap _PyEval_EvalFrameDefault + 4282
24      0x563b1a203c26p
25      0x563b1a204941p
26      0x563b1a20a755p
27      0x563b1a22ccbap _PyEval_EvalFrameDefault + 762
28      0x563b1a203daep
29      0x563b1a204941p
30      0x563b1a20a755p
31      0x563b1a22ccbap _PyEval_EvalFrameDefault + 762
32      0x563b1a205459p PyEval_EvalCodeEx + 809
33      0x563b1a2061ecp PyEval_EvalCode + 28
34      0x563b1a2809a4p
35      0x563b1a14760cp
36      0x563b1a1477c2p PyRun_InteractiveLoopFlags + 243
37      0x563b1a147862p
38      0x563b1a149a57p
39      0x563b1a14c4bep main + 238
40      0x7f2726443830p __libc_start_main + 240
41      0x563b1a233773p

>>>
