### ISSUE TITLE
save_inference_model 参数有的是var，有的是var.name, 易用性较差

### ISSUE THREAD

**Issue by ccmeteorljh** [PaddlePaddle/Paddle#17989]
paddle.fluid.io.save_inference_model(dirname, feeded_var_names, target_vars, executor, main_program=None, model_filename=None, params_filename=None, export_for_deployment=True)

**Comment by AIpioneer** [comment]
Thanks for your feedback. Now we are reconstructing save/load APIs and it will be released soon.
