### ISSUE TITLE
rpc启动报错： error_message:Sent message larger than max

### ISSUE THREAD

**Issue by zhouxc** [PaddlePaddle/Paddle#18002]
欢迎您对PaddlePaddle提出建议，非常感谢您对PaddlePaddle的贡献！
在留下您的建议时，辛苦您同步提供如下信息：
- 版本、环境信息
1）PaddlePaddle版本：请提供您的PaddlePaddle版本号，例如1.1
2）CPU/GPU：您是否使用GPU进行训练，如是，请提供您的CUDA和cuDNN版本号
3）系统环境：请您描述系统类型、版本，例如Mac OS 10.14
- 复现信息：如为报错，请给出复现环境、复现步骤
- 建议描述：请您详细描述，您认为需优化的功能

Thank you for contributing to PaddlePaddle.
Before submitting the issue, you could search issue in the github in case that there was a similar issue submitted or resolved before.
Please make sure that this is a feature request. 
**System information**
-PaddlePaddle version （eg.1.1）or CommitID
-CPU: including CPUMKL/OpenBlas/MKLDNN version
-GPU: including CUDA/CUDNN version
-OS Platform (eg.Mac OS 10.14)
**To Reproduce**
Steps to reproduce the behavior
**Describe the feature and the current behavior/state.**
**Any Other info.**

**Comment by zhouxc** [comment]
http://10.89.167.39:8900/fileview.html?path=/home/disk1/normandy/maybach/app-user-20190611190754-15212/
![image](https://user-images.githubusercontent.com/1280621/59268374-228e5800-8c7f-11e9-82bc-b459fbfd5913.png)
![image](https://user-images.githubusercontent.com/1280621/59268392-2ae69300-8c7f-11e9-8904-edef03762b23.png)

**Comment by luotao1** [comment]
请问该模型在本地单机能否跑通呢？
