### ISSUE TITLE
How to set multi-core training in Docker?Malloc too much memory?

### ISSUE THREAD

**Issue by 17Skye17** [PaddlePaddle/Paddle#1801]
Hello, I am using docker image and I set trainer_count to 20 in train.sh, but only 2 cores are used.
And I noticed that if trainer_count >=3, then errror occurs:
`       BLAS : malloc too much memory `

Does anyone know why this happens?Maybe some parameters of docker need to configure?
 : )

**Comment by dzhwinter** [comment]
Please open docker client setting, and assign more memory managed to docker. Besides, the trainer_count  far greater than core numbers, it may not speed up training.
Please feel free to reopen it if there is any new activity.
