### ISSUE TITLE
auc以及损失函数计算的问题

### ISSUE THREAD

**Issue by AWSWXY** [PaddlePaddle/Paddle#18017]
看到ctr demo里面是这么使用auc和处理损失函数的。

![image](https://user-images.githubusercontent.com/18156360/59321203-bace2080-8d03-11e9-8db7-993bf00dadfe.png)
avg_cost = fluid.layers.reduce_sum(cost)
![image](https://user-images.githubusercontent.com/18156360/59321239-e8b36500-8d03-11e9-85f3-08a263ce9dec.png)
1、想问下这么做的原因是什么。
2、auc里这个参数可以解释下吗
![image](https://user-images.githubusercontent.com/18156360/59321278-11d3f580-8d04-11e9-95d3-8d16a62b7069.png)

**Comment by chengduoZH** [comment]
@AWSWXY 可以发一下这个demo的链接吗

**Comment by AWSWXY** [comment]
https://github.com/PaddlePaddle/models/blob/develop/PaddleRec/ctr/train.py

**Comment by jacquesqiao** [comment]
问题是什么？

**Comment by AWSWXY** [comment]
1、采用reduce_sum ／batch_size 这种计算方式后，调整学习率cost 差距非常大（几十倍），结果感觉有些异常
2、集群模型cost下降 auc不上升，始终是0.5（本地稳步上升）
