### ISSUE TITLE
DyGraph文档中fluid.Layer.nn找不到

### ISSUE THREAD

**Issue by tago-tech** [PaddlePaddle/Paddle#18027]
版本:Fluid1.4
文档中的 动态图机制-DyGraph  章节[http://paddlepaddle.org/documentation/docs/zh/1.4/user_guides/howto/dygraph/DyGraph.html]，在试用Mnist构建网络时，没能找到文章中提到的fluid.Layer.nn接口。尝试用 fluid.layers.* 里面的网络层替代时发现并不可行，fluid.layers.*中的网络层都要求定义 input 参数.而在文档中 定义动态图时的 在 MyLayer的定义教程中提出,"在构造函数中，我们通常会执行一些例如参数初始化，子网络初始化的操作，执行这些操作时不依赖于输入的动态信息".
。。谢谢.

**Comment by junjun315** [comment]
1. 构建动态图使用的Layer时，需要使用fluid.dygraph.Layer作为基类，请注意大小写
2. fluid.Layer.nn.Conv2d 和 fluid.Layer.nn.Pool2d 应该是笔误。可以修改为 fluid.dygraph.Conv2d 和 fluid.dygraph.Pool2d。 我们将在新版修改它

**Comment by tago-tech** [comment]
谢谢。。。
