### ISSUE TITLE
Conventions with API exporting

### ISSUE THREAD

**Issue by wangkuiyi** [PaddlePaddle/Paddle#1803]
I noticed `struct ParameterUpdaterPrivate` defined in [`paddle/api/PaddleAPIPrivate.h`](https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/api/PaddleAPI.h#L812):

```cpp
struct ParameterUpdaterPrivate {
  std::unique_ptr<paddle::ParameterUpdater> updater;
};
```

which is only used in [`paddle/api/PaddleAPI.h`](https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/api/PaddleAPI.h#L880)

```cpp
class ParameterUpdater {
...
private:
  ParameterUpdaterPrivate* m;
};
```

Why wouldn't we use a simpler strategy -- remove the definition of `struct ParameterUpdaterPrivate` and use `std::unique_ptr<paddle::ParameterUpdater> m;` in `PaddleAPI.h`?

```cpp
class ParameterUpdater {
...
private:
  std::unique_ptr<paddle::ParameterUpdater> m;
};
```

I noticed that above case are general conventions in `PaddleAPIPrivate.h` and `PaddleAPI.h`.   Is this demanded by SWIG?

**Comment by typhoonzero** [comment]
Close due to low activity, please feel free to reopen it.
