### ISSUE TITLE
[MKL-DNN] Extend reusing of primitives for Elementwise_add_mkldnn op

### ISSUE THREAD

**Issue by jczaja** [PaddlePaddle/Paddle#18047]
Recently time of creation of primitives was increased , so We need to cache sum primitives 
as used in elementwise_add_mkldnn

**Comment by bingyanghuang** [comment]
Since #18146 has been merged, could you @jczaja help close this PR?

**Comment by jczaja** [comment]
@bingyanghuang O.. forget to close that one. Yes this can be closed now
