### ISSUE TITLE
Not convenient documentation. 

### ISSUE THREAD

**Issue by pengwangucla** [PaddlePaddle/Paddle#1804]
1. From paddlepaddle.org is linked to old document. New document is from the github page.
2. The sophix generated document for python API, when type searching at the right up corner, it stucks at the searching page.
![image](https://cloud.githubusercontent.com/assets/4799604/25102266/94d7147a-236c-11e7-850b-057382fce002.png)

Why is this ? 

Thanks

**Comment by qingqing01** [comment]
closed, since the search function is enabled in new doc website.
