### ISSUE TITLE
使用CPU进行inference发现fluid1.4 c++速度比fluid1.2 python要慢

### ISSUE THREAD

**Issue by dancingpipi** [PaddlePaddle/Paddle#18044]
通过测试发现使用CPU进行inference时，fluid1.4 c++速度比fluid1.2 python要慢，如下：
模型1：
fluid1.4 c++: 40ms
fluid1.2 python:  30ms

模型2：
fluid1.4 c++: 6s
fluid1.2 python: 5s 

fluid1.4 c++已经使用过了mkl和mkldnn，请问下速度慢的原因是什么？

**Comment by chengduoZH** [comment]
什么模型呢？

**Comment by dancingpipi** [comment]
> 什么模型呢？

模型1是一个视频分类网络,
模型2是一个不太深的dnn网络，不过batchsize为166

**Comment by Superjomn** [comment]
export MKL_NUM_THREADS=1
export OMP_NUM_THREADS=1

是底层计算库的线程数设置有问题，上面环境变量试试

**Comment by Superjomn** [comment]
@luotao1 这个现在最新版是设置成1了吗？

**Comment by luotao1** [comment]
1.4.1默认设成1，但可以根据需求自己设置。
```
config.SetCpuMathLibraryNumThreads(xxx);
```

**Comment by luotao1** [comment]
请问python使用的是ParallelExecutor么？即python下的cpu利用率和C++下的cpu利用率分别是多少？可以用top命令看。

**Comment by dancingpipi** [comment]
> 1.4.1默认设成1，但可以根据需求自己设置。
> 
> ```
> config.SetCpuMathLibraryNumThreads(xxx);
> ```

用这个配置多线程可以得到线性速度的提升！！问题搞定
