### ISSUE TITLE
Bug for translayer ? 

### ISSUE THREAD

**Issue by pengwangucla** [PaddlePaddle/Paddle#1805]
Under paddle/gserver/layers/TransLayer.cpp

For back propagation the gradient is directly assigned:

`  MatrixPtr preGrad = getInputGrad(0); `
 ` outputGrad->transpose(preGrad, false);`

Will there be a problem when you have this layer connect to multiple branches?  During the backward process, the gradient will be overwritten by the last branch, while missing the gradient from others.

Thanks.

**Comment by qingqing01** [comment]
Yes, this is a bug.  It should add the transposed `outputGrad`  to `preGrad`.
