### ISSUE TITLE
how to use fluid.DatasetFactory to support serialized format binary like avro?

### ISSUE THREAD

**Issue by lzha106** [PaddlePaddle/Paddle#18055]
fluid.DatasetFactory 创建的 dataset 接口是否可以支持类似 avro 的序列化格式数据？

**Comment by xjqbest** [comment]
原始输入数据可以在pipe command中用户自定义的data generator处理。比如原始数据是序列化的，你可以在data generator中反序列化，处理成dataset可以识别的格式。
