### ISSUE TITLE
Python api print current blob size

### ISSUE THREAD

**Issue by pengwangucla** [PaddlePaddle/Paddle#1806]
Is there a good way to check the layer size during the configuration of the network 

For example 
Can we do the following to output the layer size ? 
```
datadim = 3 * 32 * 32

image = paddle.layer.data(
        name="image", type=paddle.data_type.dense_vector(datadim))
    
print image.size
```
Currently there is error under image.size,  I heard v1 is supporting such attribute ? 
Can we do it in v2?

Thanks

**Comment by NHZlX** [comment]
I close this issue due to inactivity. please feel free to reopen it.
