### ISSUE TITLE
当模型训练使用的batch_size < 使用的GPU/CPU数量，报错提示信息有误

### ISSUE THREAD

**Issue by JiaXiao243** [PaddlePaddle/Paddle#18069]
对cyclegan模型进行训练，设置--batch_size =1 ,使用5个GPU卡对该模型进行训练，报错信息如下：即错误提示信息中batch_size的数值和GPU/CPU的数值写反了。
![image](https://user-images.githubusercontent.com/37854899/59411957-07daf100-8def-11e9-87a8-804bcd4bdfc1.png)
![image](https://user-images.githubusercontent.com/37854899/59411968-0c070e80-8def-11e9-8ff5-68f5f7ec9a37.png)

**Comment by gongweibao** [comment]
训练样本有多少那？

**Comment by JiaXiao243** [comment]
??训练数据用的cityscape数据集~
