### ISSUE TITLE
mpi训练报错__memmove_ssse3_back

### ISSUE THREAD

**Issue by zhouxc** [PaddlePaddle/Paddle#18071]
欢迎您对PaddlePaddle提出建议，非常感谢您对PaddlePaddle的贡献！
在留下您的建议时，辛苦您同步提供如下信息：
- 版本、环境信息
1）PaddlePaddle版本：请提供您的PaddlePaddle版本号，例如1.1
2）CPU/GPU：您是否使用GPU进行训练，如是，请提供您的CUDA和cuDNN版本号
3）系统环境：请您描述系统类型、版本，例如Mac OS 10.14
- 复现信息：如为报错，请给出复现环境、复现步骤
- 建议描述：请您详细描述，您认为需优化的功能

Thank you for contributing to PaddlePaddle.
Before submitting the issue, you could search issue in the github in case that there was a similar issue submitted or resolved before.
Please make sure that this is a feature request. 
**System information**
-PaddlePaddle version （eg.1.1）or CommitID
-CPU: including CPUMKL/OpenBlas/MKLDNN version
-GPU: including CUDA/CUDNN version
-OS Platform (eg.Mac OS 10.14)
**To Reproduce**
Steps to reproduce the behavior
**Describe the feature and the current behavior/state.**
**Any Other info.**

**Comment by zhouxc** [comment]
![image](https://user-images.githubusercontent.com/1280621/59415235-a9fdd780-8df5-11e9-95cd-2eab00114dce.png)
单机训练没w问题，mpi训练报错，可能主要是embedding问题，从32纬改成64纬后开始报这个错，麻烦帮忙看看

**Comment by zhouxc** [comment]
http://10.89.176.25:8900/fileview.html?path=/home/disk1/normandy/maybach/app-user-20190613154619-17200/
失败任务

**Comment by kuke** [comment]
经沟通，原因可能是内存溢出
