### ISSUE TITLE
fluid.layers.embedding 如何多个 feature 间共享？

### ISSUE THREAD

**Issue by lzha106** [PaddlePaddle/Paddle#18070]
请问 paddle 如何实现在多 feature 间共享一个 embedding table？

**Comment by kuke** [comment]
https://github.com/PaddlePaddle/Paddle/blob/f8ecc3de890078429163720712feafc4253880fe/python/paddle/fluid/layers/nn.py#L357

通过param_attr 将所有embedding的参数名设置成一样 就可以共享了

**Comment by lzha106** [comment]
> https://github.com/PaddlePaddle/Paddle/blob/f8ecc3de890078429163720712feafc4253880fe/python/paddle/fluid/layers/nn.py#L357
> 
> 通过param_attr 将所有embedding的参数名设置成一样 就可以共享了

好的，谢谢，请问 paddle embedding 是否支持变长 ids 的查找和聚合，类似 tf 的 https://www.tensorflow.org/api_docs/python/tf/nn/embedding_lookup_sparse 

看官方文档示例，ids 的最后一个维度必须是 1：
http://paddlepaddle.org/documentation/docs/zh/1.4/api_cn/layers_cn.html#embedding

**Comment by kuke** [comment]
@lzha106 paddle fluid的embedding支持稀疏更新，但可能与tf不一样的是，参数本身不能是sparse tensor。目前确实需要ids的最后一个维度为1

**Comment by lzha106** [comment]
@kuke ，多谢，如果是这样的话，对于变长的 feature id list，不知道是否有示例参考下 paddle 如何实现查找及聚合操作？
