### ISSUE TITLE
动态图 saveload功能优化建议

### ISSUE THREAD

**Issue by DDDivano** [PaddlePaddle/Paddle#18096]
load时候没有报错提示，比如load一个不存在的路径，或者路径错误，文件有问题等原因导致没有load成功。但是由于动态图本身的机制也不会有任何报错，还可以正常执行预测，但是结果是随机权重预测出来的结果。这样可能给用户带来困惑，会认为模型训练的不好，错误不方便排查。

**Comment by DogHeadMoon** [comment]
https://github.com/PaddlePaddle/Paddle/pull/19384
