### ISSUE TITLE
with_data_parallel使用的问题？

### ISSUE THREAD

**Issue by yeyupiaoling** [PaddlePaddle/Paddle#18091]
# 环境
 - Ubuntu 16.04
 - PaddlePaddle 1.4.1
 - Python 3.5

# 问题
with_data_parallel 接口：http://paddlepaddle.org/documentation/docs/zh/1.4/api_cn/fluid_cn.html#with_data_parallel

可以使用进行多线程读取
```
exec_strategy = fluid.ExecutionStrategy()
exec_strategy.num_threads = cpu_count() * 4
```

但是也有这个参数places，这个参数是说训练位置吗。还是说数据的读取位置？

**Comment by gongweibao** [comment]
可以不设置。

**Comment by yeyupiaoling** [comment]
@gongweibao 
> 可以不设置。

是什么意思？我是问places这个参数指定训练的位置，还是说读取数据的位置？

**Comment by yeyupiaoling** [comment]
@gongweibao 还有 loss_name 是不是一样要设置的？

**Comment by yeyupiaoling** [comment]
@gongweibao 还有，为什么是CPU的数量 × 4，这个乘上4的作用是什么？
```
cpu_count() * 4
```
