### ISSUE TITLE
集群训练 ParallelExecutor 内存超限

### ISSUE THREAD

**Issue by AWSWXY** [PaddlePaddle/Paddle#18094]
cpu_num 超过1个时就会失败。
任务链接
http://10.182.164.166:8900/fileview.html?path=/home/disk1/normandy/maybach/app-user-20190614122953-18000/

**Comment by seiriosPlus** [comment]
1. 可以适当增大内存
2. 检查一下数据读取的逻辑，看是否是因为数据load过大
2. CPU的ParallelExecutor的strategy设置为Reduce
