### ISSUE TITLE
训练中是否使用fluid.default_main_program().clone(for_test=True)进行测试，训练效果差异巨大

### ISSUE THREAD

**Issue by laoliukan** [PaddlePaddle/Paddle#18102]
训练模型的时候，用fluid.default_main_program().clone(for_test=True)每轮测试test set，最终的得到test set上的效果非常高。
只训练，过程中不测试test set，最终test set上效果比较差，和上面相差很多。

感觉像是使用test set进行训练了一样，请问是什么问题呢？

下面是我的代码 
inference_program = fluid.default_main_program().clone(for_test=True)
result_list = exe.run(
    inference_program,
    feed=feeder.feed(data),
    fetch_list=test_fetch_list)

**Comment by laoliukan** [comment]
1、训练网络是gru+crf，做槽位填充和意图识别，参考baidu/lac代码写的，网络基本一样。
https://github.com/baidu/lac/blob/master/python/network.py

2、用的paddle cpu版本，1.3，1.4.1 都有这种现象

3、训练过程中测试：
后五轮训练集loss：0.00088, 0.000849, 0.000815, 0.000808, 0.000787
训练集acc=1（因为训练数据较少）
最终测试集f值=**0.972**

4、训练过程中不测试：
后五轮训练集loss：0.000919, 0.000903, 0.000889, 0.000875, 0.000861
训练集acc=1（因为训练数据较少）
最终测试集f值=**0.21**（相差特别大！）

**Comment by chengduoZH** [comment]
@laoliukan 可以贴一下你的代码吗？怀疑你是调用完optimizer.minimize(...)之后才调用的clone
另外fluid.default_main_program().clone(for_test=True)不会将program中的反向操作做裁剪。

**Comment by laoliukan** [comment]
哦哦，我是调用optimizer.minimize(...)之后，才调用的fluid.default_main_program().clone(for_test=True)，原来是这个问题，谢谢。
