### ISSUE TITLE
模型训练发现psever报错但是没有明确原因

### ISSUE THREAD

**Issue by sitong188** [PaddlePaddle/Paddle#18101]
提交fluid任务id:  job-0bb5d00ed6f3fc20

log链接：
http://10.182.20.35:8900/fileview.html?path=/home/disk1/normandy/maybach/app-user-20190612201759-16412/
 
psever的报错：
get_pserver_program() is deprecated, call get_pserver_programs() to get pserver main and startup in a single call.get_startup_program() is deprecated, call get_pserver_programs() to get pserver main and startup in a single call.passing pserver_program to get_startup_program() is deprecated, you can use new API get_pserver_programs() to get both pserver main program and startup program.I0612 23:33:35.860657 96127 grpc_server.cc:290] Server listening on 10.182.20.35:62004 selected port: 62004
*** Aborted at 1560479004 (unix time) try "date -d @1560479004" if you are using GNU date ***
*** Error in `/home/disk1/normandy/maybach/app-user-20190612201759-16412/workspace/python27-gcc482/bin/python': free(): corrupted unsorted chunks: 0x00000000050eeec0 ***
*** Error in `/home/disk1/normandy/maybach/app-user-20190612201759-16412/workspace/python27-gcc482/bin/python': free(): corrupted unsorted chunks: 0x00000000050e3cb0 ***
*** Error in `/home/disk1/normandy/maybach/app-user-20190612201759-16412/workspace/python27-gcc482/bin/python': corrupted double-linked list: 0x00000000050e3ca0 ***
*** Error in `/home/disk1/normandy/maybach/app-user-20190612201759-16412/workspace/python27-gcc482/bin/python': double free or corruption (fasttop): 0x00000000050e37a0 ***

**Comment by gongweibao** [comment]
这个看上去是内存损坏，你先用1.4.1试试？
