### ISSUE TITLE
python fields (num_filters and size) in v2 api ? 

### ISSUE THREAD

**Issue by pengwangucla** [PaddlePaddle/Paddle#1811]
In python api v1, we can find out the current layer size and num_filters by calling

```
layer = paddle.layer.img_conv_layer(...)
layer.size  or layer.num_filters 
```

However, in v2, at paddle book, I can not find such fields by 

`print layer.size `

May I know what is the reason of that ?  

It is important because when we are trying to configure a network, we would like to online know what is the current network size by simply print out the network layer size for debugging. 

It is also important for my application on image segmentation by understand the layer size and compare against the labels during test when the input image does not always have the same size. It is much better if we can also output layer.width and layer.height on the fly.

Is there anyone like to figure it out ? 

Thanks

**Comment by helinwang** [comment]
@jacquesqiao Can you take a look at this? I thought you are more familiar with v2 layers.

**Comment by jacquesqiao** [comment]
ok, I will fix this problem.

**Comment by pengwangucla** [comment]
@jacquesqiao May I ask when this feature will be added
