### ISSUE TITLE
ctr模型集群训练cost稳步下降，auc不上升

### ISSUE THREAD

**Issue by AWSWXY** [PaddlePaddle/Paddle#18113]
ctr模型集群训练cost稳步下降，auc不上升，但是本地训练auc稳步上升。
日志如下：
http://10.182.163.140:8900/fileview.html?path=/home/disk1/normandy/maybach/app-user-20190614235742-18510/
版本 fleet api

**Comment by guoshengCS** [comment]
请问是否是用的cluster_train.py这个文件，这个里的`inference = fluid.layers.cos_sim(X=usr_combined_features, Y=usr_combined_features)`是否会有问题呢；另外看到`avg_cost = fluid.layers.reduce_sum(cost)`这个已经是平均的，打印的时候使用`loss_val/args.batch_size`是否是期望的呢，

`群训练cost稳步下降，auc不上升，但是本地训练auc稳步上升`请问这个是完全相同的数据也是这样吗，另外看到还设置了accuracy的指标，可否打印这个指标是否再集群和本地符合预期呢

**Comment by AWSWXY** [comment]
经排查是网络结构错误。修改网络结构auc正常上升

**Comment by guoshengCS** [comment]
问题已解决，先行close，如有需要还请reopen
