### ISSUE TITLE
集群GPU和远程单机GPU，集群GPU训练的模型结果差，模型和数据都一样的

### ISSUE THREAD

**Issue by paulpaul91** [PaddlePaddle/Paddle#18126]
集群GPU和远程单机GPU，集群GPU训练的模型结果差，模型和数据都一样的。
为了测试这个问题，我在远程的GPU上训练好的模型，在远程单机GPU和集群GPU上预测同一份测试集，所有的参数配置都一样，集群上的准确率只有33%，而远程单机GPU有90%，请问有遇到类似问题的吗？

**Comment by jacquesqiao** [comment]
集群GPU和远程单机GPU分别是啥？

**Comment by paulpaul91** [comment]
> 集群GPU和远程单机GPU分别是啥？

公司的GPU队列，单机GPU指的是物理机
