### ISSUE TITLE
Python only interface w/o bash script

### ISSUE THREAD

**Issue by alvations** [PaddlePaddle/Paddle#1813]
Paddle 的 demo 好像都用 shell 和 python 的接口来运行 paddle。

比如在 Text Generation 的 demo 里，user 得用 `train.sh` 接口 `train.conf` 然后在命令行上启用 `paddle` 的binary。最新的 Paddle 版本有只用 Python 指令运行的接口吗？

**Comment by luotao1** [comment]
在[机器翻译教程](https://github.com/PaddlePaddle/book/tree/develop/07.machine_translation)中的train.py，提供了只用python指令运行的接口。

**Comment by alvations** [comment]
@luotao1 太棒了，谢谢！您链接的 Paddle book 已经正式公布了吗？

**Comment by luotao1** [comment]
还没有正式公布，但目前每个示例中的train.py都能正确运行和预测。

**Comment by alvations** [comment]
@luotao1 再次谢谢！
