### ISSUE TITLE
请教复现ArcFace loss 损失函数？

### ISSUE THREAD

**Issue by yeyupiaoling** [PaddlePaddle/Paddle#18143]
在MobileFaceNets模型中，使用的是ArcFace loss 损失函数，我想知道该如何复现这个函数呢？

![image](https://user-images.githubusercontent.com/26297768/59594339-40980480-9126-11e9-9cba-2080e97230fc.png)

**Comment by qingqing01** [comment]
@yeyupiaoling 请参考 https://github.com/PaddlePaddle/models/blob/develop/PaddleCV/metric_learning/losses/arcmarginloss.py 这个实现。

**Comment by yeyupiaoling** [comment]
@qingqing01 这个应该就是我想要的ArcFace loss，谢谢。
