### ISSUE TITLE
RNN生成序列时从非<s>开始

### ISSUE THREAD

**Issue by shateng** [PaddlePaddle/Paddle#1814]
在seq2seq的demo里，生成beam search和GeneratedInput默认第一个时间步以bos_id作为输入，但如果是某些场景比如char-rnn类似的场景，第一个时间步的输入是某个非bos_id的字符的话，怎么生成呢？

**Comment by lcy-seso** [comment]
char-rnn 这个是指用语言模型生成吗？

生成问题总是需要一个输入，否则会变成“凭空生成”。
- 对语言模型，给定前半句话
- 对 seq2seq 模型这样，给定一个源来生成目标。

PaddlePaddle 的seq2seq 需要<s> 符号作为 decoder 的初始状态。

**Comment by shateng** [comment]
是指类似语言模型的生成，怎么在paddle predict的时候给定前半句话呢？用GeneratedInput的话只能从<bos_id>开始

**Comment by lcy-seso** [comment]
语言模型生成目前我们还没有一个现成的demo，这个我来提供一个demo吧。

1.   想要自动生成必须用 recurrent_layer_group 形式的 lstm / gru / rnn，beam search 现在只通过 recurrent_layer_group 来实现。
2.  需要把网络拆成两部分，这两部分的参数共享。 
     + 第一部分用来编码给定的前半句话，得到 hidden state
     + 第二部分用于生成：用第一部分的hidden  state 去boot 第二部分的rnn

**Comment by shateng** [comment]
明白了，多谢！
