### ISSUE TITLE
安装问题

### ISSUE THREAD

**Issue by Jhon714-cooler** [PaddlePaddle/Paddle#18150]
![微信图片_20190617201313](https://user-images.githubusercontent.com/51886349/59605254-fb350080-9140-11e9-9f07-75b6ead2cb2c.jpg)
为什么会出现这个回复

**Comment by yeyupiaoling** [comment]
@Jhon714-cooler 
![image](https://user-images.githubusercontent.com/26297768/59647894-99f84600-91af-11e9-8161-35107874ba68.png)
