### ISSUE TITLE
lstm_unit使用报错

### ISSUE THREAD

**Issue by yuyy0823** [PaddlePaddle/Paddle#18164]
paddle版本 0.15
想简单测试下lstm_unit的实现，运行报错，部分代码和报错信息如下，把lstm换成mlp，其他代码都不变是可以成功运行的，所以应该是lstm_unit使用不对吗？lstm_unit是按照api写的，很简单，没做什么复制操作，求帮忙看下是什么错误啊：

def lstm(input):

    x_t_data = input
    x_t = fluid.layers.fc(input=x_t_data, size=64)
    prev_hidden = fluid.layers.fc(input=x_t_data, size=64)
    prev_cell = fluid.layers.fc(input=x_t_data, size=64)
    hidden_value, cell_value = fluid.layers.lstm_unit(x_t=x_t,
                                   hidden_t_prev=prev_hidden,
                                   cell_t_prev=prev_cell)
    pre = fluid.layers.fc(input=hidden_value, size=2, act='softmax', name='softmax_out')
    pre_scale = fluid.layers.scale(pre, 1.0)
    return pre_scale
def optimizer_setting(args):

    boundaries = map(int, args.boundaries.split(','))
    decay = map(float, args.decay.split(','))
    lr = args.lr
    values = [lr * i for i in decay]
    optimizer = fluid.optimizer.AdamaxOptimizer(
        learning_rate=fluid.layers.piecewise_decay(boundaries, values),
        regularization=fluid.regularizer.L2Decay(0.00005), )
    return optimizer

def build_program(main_prog, startup_prog, is_train, network, args):

    outs = []
    with fluid.program_guard(main_prog, startup_prog):
        py_reader = fluid.layers.py_reader(
            capacity=10000,
            shapes=((-1, 246), (-1, 1)),
            dtypes=["float32", "int64"],
            use_double_buffer=True)
        with fluid.unique_name.guard():
            feats, label = fluid.layers.read_file(py_reader)
            predict = lstm(feats)
            if is_train:
                with fluid.unique_name.guard("train"):
                    loss = fluid.layers.cross_entropy(input=predict, label=label, soft_label=False)
                    loss = fluid.layers.mean(loss)
                    optimizer = optimizer_setting(args)
                    optimizer.minimize(loss)
                outs = [py_reader, loss, feats, predict]
            else:
                with fluid.unique_name.guard("inference"):
                    loss = fluid.layers.cross_entropy(input=predict, label=label, soft_label=False)
                    loss = fluid.layers.mean(loss)
                    accuracy = fluid.layers.accuracy(input=predict, label=label)
                outs = [py_reader, loss, accuracy]
    return outs

报错信息如下
Traceback (most recent call last):
  File "lstm.py", line 330, in <module>
    train(params_dirname, network, args)
  File "lstm.py", line 172, in train
    args=args)
  File "lstm.py", line 125, in build_program
    optimizer.minimize(loss)
  File "/home/yuyuanyuan03/.jumbo/lib/python2.7/site-packages/paddle/fluid/optimizer.py", line 258, in minimize
    [error_clip_callback])
  File "/home/yuyuanyuan03/.jumbo/lib/python2.7/site-packages/paddle/fluid/backward.py", line 590, in append_backward
    _append_backward_vars_(root_block, fwd_op_num, grad_to_var, grad_info_map)
  File "/home/yuyuanyuan03/.jumbo/lib/python2.7/site-packages/paddle/fluid/backward.py", line 426, in _append_backward_vars_
    op_desc.infer_shape(block.desc)
paddle.fluid.core.EnforceNotMet: Input(C@GRAD) should not be null at [/paddle/paddle/fluid/operators/lstm_unit_op.cc:86]
PaddlePaddle Call Stacks:
0       0x7fd1eeb31a16p paddle::platform::EnforceNotMet::EnforceNotMet(std::__exception_ptr::exception_ptr, char const*, int) + 486
1       0x7fd1eecfbbfcp paddle::operators::LstmUnitGradOp::InferShape(paddle::framework::InferShapeContext*) const + 812
2       0x7fd1eebe3586p paddle::framework::OpDesc::InferShape(paddle::framework::BlockDesc const&) const + 886
3       0x7fd1eeb8ecf5p _ZZN8pybind1112cpp_function10initializeIZNS0_C1IvN6paddle9framework6OpDescEIRKNS4_9BlockDescEEINS_4nameENS_9is_methodENS_7siblingEEEEMT0_KFT_DpT1_EDpRKT2_EUlPKS5_S8_E_vISN_S8_EIS9_SA_SB_EEEvOSD_PFSC_SF_ESL_ENUlRNS_6detail13function_callEE1_4_FUNESU_ + 213
4       0x7fd1eeb426f4p pybind11::cpp_function::dispatcher(_object*, _object*, _object*) + 2596
5       0x7fd24cfd4414p PyEval_EvalFrameEx + 25956
6       0x7fd24cfd5160p PyEval_EvalCodeEx + 2240
7       0x7fd24cfd34d1p PyEval_EvalFrameEx + 22049
8       0x7fd24cfd5160p PyEval_EvalCodeEx + 2240
9       0x7fd24cfd34d1p PyEval_EvalFrameEx + 22049
10      0x7fd24cfd5160p PyEval_EvalCodeEx + 2240
11      0x7fd24cfd34d1p PyEval_EvalFrameEx + 22049
12      0x7fd24cfd5160p PyEval_EvalCodeEx + 2240
13      0x7fd24cfd34d1p PyEval_EvalFrameEx + 22049
14      0x7fd24cfd5160p PyEval_EvalCodeEx + 2240
15      0x7fd24cfd34d1p PyEval_EvalFrameEx + 22049
16      0x7fd24cfd5160p PyEval_EvalCodeEx + 2240
17      0x7fd24cfd5272p PyEval_EvalCode + 50
18      0x7fd24cfef65cp
19      0x7fd24cfef730p PyRun_FileExFlags + 144
20      0x7fd24cff0c3cp PyRun_SimpleFileExFlags + 220
21      0x7fd24d0024fcp Py_Main + 3164
22        0x38bfc21b45p __libc_start_main + 245
23            0x400699p

**Comment by yma-admin** [comment]
1.0之前版本问题比较多，建议更新未最新版本。谢谢！
