### ISSUE TITLE
模型训练报错 没有发现具体问题

### ISSUE THREAD

**Issue by sitong188** [PaddlePaddle/Paddle#18163]
作业id:
job-0bb5d0629f36f6f5
job-0bb5d031347a67bc

http://10.182.97.139:8900/fileview.html?path=/home/disk1/normandy/maybach/app-user-20190616193732-20432/
http://10.182.23.158:8900/fileview.html?path=/home/disk1/normandy/maybach/app-user-20190614112407-17954/

**Comment by AIpioneer** [comment]
This issue is closed due to internal processing.
