### ISSUE TITLE
Docker build cannot access mount dir in SELinux enabled docker

### ISSUE THREAD

**Issue by reyoung** [PaddlePaddle/Paddle#1816]
In selinux enabled docker, even we run container as `docker run -v $PWD:/paddle`, `/paddle` cannot be accessed inside docker.

`docker version` is `1.12.6`.

**Comment by Yancey1989** [comment]
According with http://www.projectatomic.io/blog/2015/06/using-volumes-with-docker-can-cause-problems-with-selinux/,  try `docker run -v $PWD:/paddle:Z ...`? But usually, I keep the SELinux disable on host.

**Comment by helinwang** [comment]
Closed due to inactivity.
