### ISSUE TITLE
希望实现高效易用的图网络库和相关的经典图网络模型

### ISSUE THREAD

**Issue by yangapku** [PaddlePaddle/Paddle#18171]
目前图网络逐渐成为研究和业务的热点，TF、pytorch都在其基本框架的基础上推出了图网络库以及经典图网络模型的实现，尤其是基于pytorch已经出现多款相关库——[DGL](https://github.com/dmlc/dgl)（底层同时支持mxnet）以及[pytorch_geometric](https://github.com/rusty1s/pytorch_geometric)。这些库一方面比较高效，可以支持亿级规模的网络的训练和预测，另一方面使用也比较简单，看示例代码都比较简洁，同时对于经典的GCN、GAT以及经典相关论文都有了实现。希望paddle可以尽快实现类似的功能并争取取得性能的优势，这样才能够吸引更多用户选择paddle。

**Comment by yma-admin** [comment]
开发中，会很快发布。敬请期待。

**Comment by yangapku** [comment]
赞～期待，请问是基于静态图还是dygraph的呢？更期望是后者

**Comment by kirayummy** [comment]
> 目前图网络逐渐成为研究和业务的热点，TF、pytorch都在其基本框架的基础上推出了图网络库以及经典图网络模型的实现，尤其是基于pytorch已经出现多款相关库——[DGL](https://github.com/dmlc/dgl)（底层同时支持mxnet）以及[pytorch_geometric](https://github.com/rusty1s/pytorch_geometric)。这些库一方面比较高效，可以支持亿级规模的网络的训练和预测，另一方面使用也比较简单，看示例代码都比较简洁，同时对于经典的GCN、GAT以及经典相关论文都有了实现。希望paddle可以尽快实现类似的功能并争取取得性能的优势，这样才能够吸引更多用户选择paddle。

可以参考一下Paddle Graph Learning (PGL) 框架，目前是处于preview版本，后续会支持更多的功能。
PGL充分利用了Paddle的LoD Tensor特性，相对于DGL保证了灵活性的同时保证了高效性。
GitHub：https://github.com/PaddlePaddle/PGL
文档：https://pgl.readthedocs.io/en/latest/

有问题多多指出，谢谢支持！
