### ISSUE TITLE
smooth l1 loss替换huber loss的时候，是不是要修改下什么呀？ 我参考官方文档替换了下，最后loss反传会报错。

### ISSUE THREAD

**Issue by takecareofbigboss** [PaddlePaddle/Paddle#18172]
smooth l1 loss替换huber loss的时候，是不是要修改下什么呀？ 我参考官方文档替换了下，最后loss反传会报错。
![image](https://user-images.githubusercontent.com/11883059/59658811-5580a080-91d7-11e9-9988-b7193d7a664b.png)
报错信息：
![image](https://user-images.githubusercontent.com/11883059/59658821-5d404500-91d7-11e9-8dcc-4e3fc7368ddc.png)

**Comment by qingqing01** [comment]
@takecareofbigboss Please see doc  http://www.paddlepaddle.org/documentation/docs/zh/1.4/api_cn/layers_cn.html#huber-loss  for huber loss, the last dim must be 1.

**Comment by takecareofbigboss** [comment]
this problem has been solved, and the solution is:
    cost = fluid.layers.huber_loss(fluid.layers.reshape(outputs_masked, shape=[-1, 1]), fluid.layers.reshape(pts_masked, shape=[-1, 1]), 3.0) 
    cost = fluid.layers.reshape(cost, shape=[-1, args.n_pt*2])
    cost = fluid.layers.reduce_sum(cost, dim=1)
    cost = fluid.layers.reshape(cost, shape=[-1, 1])
    cost = cost / num_ones
thanks for qingqing's help.
