### ISSUE TITLE
中文官网有些demo无法跑过

### ISSUE THREAD

**Issue by xiuechen** [PaddlePaddle/Paddle#18179]
http://paddlepaddle.org/documentation/docs/zh/1.4/api_cn/layers_cn.html#sequence-reshape

比如这个，输入需要二维，但是给出的例子中输入是三维的，报错

**Comment by xsrobin** [comment]
感谢您的反馈，1.5版本已经修复了这个文档以及其他的API文档，发布之后会整体解决。
