### ISSUE TITLE
训练中多次调用fluid.io.load_inference_model进行预测，内存一直增长

### ISSUE THREAD

**Issue by laoliukan** [PaddlePaddle/Paddle#18188]
模型是lstm+crf，emb词表大小100多万，每轮都会调用fluid.io.load_inference_model，内存在不断增大，500轮的时候已经增长到几十g了。

**Comment by Superjomn** [comment]
可以贴下相关的代码吗，最好是 forloop，直接load 的，不确定那样是否能复现

**Comment by xiangyubo** [comment]
是不是每次都创建新的 scope 了？看看这篇文章有帮助不？
https://aistudio.baidu.com/aistudio/projectdetail/641295
