### ISSUE TITLE
py_reader的参数疑问（文档不明确）

### ISSUE THREAD

**Issue by chyj4747** [PaddlePaddle/Paddle#18181]
capacity，这个缓冲区大小具体怎么定？文档里大多是64，但这个64对应的具体是什么量？比如内存的64MB？还是64条数据？或者别的什么东西？

**Comment by sneaxiy** [comment]
`capacity`是py_reader内部维护的队列容量大小，单位是batch。如果capacity是64，则py_reader的队列内部最多缓存64个batch的数据。

**Comment by chyj4747** [comment]
> `capacity`是py_reader内部维护的队列容量大小，单位是batch。如果capacity是64，则py_reader的队列内部最多缓存64个batch的数据。

哦哦，多谢
不过麻烦文档里也注明一下，不然以后还是有初学者不知道缓存应该设多少
