### ISSUE TITLE
树莓派3b+编译安装

### ISSUE THREAD

**Issue by DsaltYfish** [PaddlePaddle/Paddle#18190]
本人设备是树莓派3b+，系统是树莓派官方系统
Raspbian Stretch with desktop
Image with desktop based on Debian Stretch
Version:April 2019
Release date:2019-04-08
Kernel version:4.14
Release notes
SHA-256:7e10a446f8e57210d0e9ad02f0c833aabb86e58187b4dc02431aff5a3f1ccb83
按照arm_linux的开发文档，在执行/bin/bash build.sh arm_linux 后遇到
[ 25%] Building CXX object CMakeFiles/paddle-mobile.dir/src/operators/kernel/arm/convolution/conv_kernel.cpp.o
/usr/bin/c++   -DANCHOR_GENERATOR_OP -DASSIGN_VALUE_OP -DBATCHNORM_OP -DBEAM_SEARCH_DECODE_OP -DBEAM_SEARCH_OP -DBILINEAR_INTERP_OP -DBOXCODER_OP -DCAST_OP -DCONCAT_OP -DCONV_OP -DCONV_TRANSPOSE_OP -DCRF_OP -DDENSITY_PRIORBOX_OP -DDEPTHWISECONV_OP -DDEQUANT_OP -DDROPOUT_OP -DELEMENTWISEADD_OP -DELEMENTWISEMUL_OP -DELEMENTWISESUB_OP -DENABLE_EXCEPTION -DFILL_CONSTANT_OP -DFLATTEN_OP -DFUSION_CONVADDADDPRELU_OP -DFUSION_CONVADDBNRELU_OP -DFUSION_CONVADDPRELU_OP -DFUSION_CONVADDRELU_OP -DFUSION_CONVADD_OP -DFUSION_CONVBNADDRELU_OP -DFUSION_CONVBNRELU_OP -DFUSION_CONVRELU_OP -DFUSION_DEQUANT_ADD_BN_OP -DFUSION_DEQUANT_ADD_BN_RELU_OP -DFUSION_DEQUANT_BN_OP -DFUSION_DEQUANT_BN_RELU_OP -DFUSION_DWCONVBNRELU_OP -DFUSION_FC_OP -DGRU_OP -DGRU_UNIT_OP -DIM2SEQUENCE_OP -DINCREMENT_OP -DIS_EMPTY_OP -DLEAKY_RELU_OP -DLESS_THAN_OP -DLOD_RESET_OP -DLOGICAL_AND_OP -DLOGICAL_NOT_OP -DLOGICAL_OR_OP -DLOGICAL_XOR_OP -DLOG_OP -DLOOKUP_OP -DLRN_OP -DMULTICLASSNMS_OP -DMUL_OP -DNEAREST_INTERP_OP -DNORM_OP -DONE_HOT_OP -DPAD2D_OP -DPADDLE_MOBILE_CPU -DPADDLE_MOBILE_USE_OPENMP -DPOLYGONBOXTRANSFORM_OP -DPOOL_OP -DPRELU_OP -DPRIORBOX_OP -DPROPOSAL_OP -DPSROI_POOL_OP -DQUANT_OP -DREAD_FROM_ARRAY_OP -DRELU_OP -DRESHAPE2_OP -DRESHAPE_OP -DRESIZE_OP -DROI_PERSPECTIVE_OP -DSCALE_OP -DSEQUENCE_EXPAND_OP -DSEQUENCE_POOL_OP -DSEQUENCE_SOFTMAX_OP -DSHAPE_OP -DSIGMOID_OP -DSLICE_OP -DSOFTMAX_OP -DSPLIT_OP -DSUM_OP -DTANH_OP -DTOP_K_OP -DTRANSPOSE2_OP -DTRANSPOSE_OP -DWHILE_OP -DWRITE_TO_ARRAY_OP -Dpaddle_mobile_EXPORTS -I/home/pi/paddle-mobile/src  -std=c++11 -O3 -s -DNDEBUG -std=c++14 -mcpu=cortex-a53 -mtune=cortex-a53 -ftree-vectorize -funsafe-math-optimizations -pipe -mlittle-endian -Wno-attributes -fopenmp -O3 -DNDEBUG -fPIC   -fexceptions -o CMakeFiles/paddle-mobile.dir/src/operators/kernel/arm/convolution/conv_kernel.cpp.o -c /home/pi/paddle-mobile/src/operators/kernel/arm/convolution/conv_kernel.cpp
In file included from /home/pi/paddle-mobile/src/operators/kernel/arm/convolution/conv_common.cpp:16:0:
/home/pi/paddle-mobile/src/operators/math/slidingwindow_utils.h: In function ‘void paddle_mobile::operators::math::slidingwindow_fill_bias(float*, const float*, int)’:
/home/pi/paddle-mobile/src/operators/math/slidingwindow_utils.h:137:3: error: ‘float32x4_t’ was not declared in this scope
   float32x4_t vb = vld1q_f32(bias);
   ^~~~~~~~~~~
/home/pi/paddle-mobile/src/operators/math/slidingwindow_utils.h:140:21: error: ‘vb’ was not declared in this scope
     vst1q_f32(dout, vb);
                     ^~
/home/pi/paddle-mobile/src/operators/math/slidingwindow_utils.h:140:23: error: ‘vst1q_f32’ was not declared in this scope
     vst1q_f32(dout, vb);
                       ^
CMakeFiles/paddle-mobile.dir/build.make:2321: recipe for target 'CMakeFiles/paddle-mobile.dir/src/operators/kernel/arm/convolution/conv_common.cpp.o' failed
make[2]: *** [CMakeFiles/paddle-mobile.dir/src/operators/kernel/arm/convolution/conv_common.cpp.o] Error 1
make[2]: *** 正在等待未完成的任务....
make[2]: Leaving directory '/home/pi/paddle-mobile/build/release/arm-linux'
CMakeFiles/Makefile2:70: recipe for target 'CMakeFiles/paddle-mobile.dir/all' failed
make[1]: *** [CMakeFiles/paddle-mobile.dir/all] Error 2
make[1]: Leaving directory '/home/pi/paddle-mobile/build/release/arm-linux'
Makefile:86: recipe for target 'all' failed
make: *** [all] Error 2
models is indeed not empty, DONE!

到这里就停止了
用过make -i发现之后还会有其他编译的问题
请求解答

**Comment by Superjomn** [comment]
这是哪个 repo 的？ 哪个版本的？
好像不是 Paddle org 吧
