### ISSUE TITLE
window从源码编译paddle夯住

### ISSUE THREAD

**Issue by JiaXiao243** [PaddlePaddle/Paddle#18198]
在windows系统上从源码开始编译paddle，正常编译需要4个小时左右，太慢了~强烈建议优化一下~ 若直接使用pip install安装，假如对应cuda、cudnn的小版本不同(例如cuda9.0和9.2，cudnn7.0和7.5)，则无法正常使用paddle。还是需要直接从源码编译安装。
在window上从源码编译paddle一直没有编完。。。
对比linux从源码编译paddle需要40分钟左右。

**Comment by JiaXiao243** [comment]
在window机器上编译，报错信息如下:
![image](https://user-images.githubusercontent.com/37854899/59816618-62280480-934f-11e9-83a1-90c9e586753e.png)
![image](https://user-images.githubusercontent.com/37854899/59829557-4b45da00-9370-11e9-8b1f-96bbbb1cc59e.png)

**Comment by carychai** [comment]
我在windows下编译大概花了40分钟，但是结果是fail，一堆错误，搞了两次都这样，无奈放弃了。因为我的显卡是RTX2060，cuda 8.0不支持.我只有等官方的版本更新了.

**Comment by wopeizl** [comment]
可以贴一些错误截图，初步判断有两个方面是会慢的，
1. github访问速度问题，很多依赖是从github上拉取的，大部分编译任务依赖这些资源，导致整体很慢
2. VS本身编译速度和PC机器差异问题，对比linux服务器来说，一般是要慢一些, 特别是在nvcc的编译方面

**Comment by wopeizl** [comment]
还有1.5之前的版本只支持cuda8，RTX2060应该是不支持的，所以就算编译后也应该不能运行GPU版本

**Comment by wopeizl** [comment]
编译加速是需要解决的一个方面。
