### ISSUE TITLE
inference过程如何获取sub_block中variable的值

### ISSUE THREAD

**Issue by shjwudp** [PaddlePaddle/Paddle#18206]
环境信息：Paddle 1.4.1 on CPU

问题：
inference过程中需要打印中间计算结果（variable）做debug，现在使用插入fetch op的方式能够打印出主block的variable，但是fetch sub_block variable会有问题，错误信息显示找不到variable

请求援助：
有没有支持sub_block的中间值打印debug方法

**Comment by Superjomn** [comment]
可以试试  http://www.paddlepaddle.org.cn/documentation/docs/zh/1.4/api_cn/layers_cn.html#print

Print op
