### ISSUE TITLE
训练两个模型共用embedding，计算梯度出错

### ISSUE THREAD

**Issue by sgcsky** [PaddlePaddle/Paddle#18204]
训练gan模型的时候，dis和gen共用同一个embedding，在minimize的时候报Exception: Accumulator moment1 already exists for parameter emb
要怎么解决呢？
网络里embedding的定义
![image](https://user-images.githubusercontent.com/22487380/59743180-0eabad00-92a2-11e9-9d7d-51314d5efeca.png)
生成网络的代码
![image](https://user-images.githubusercontent.com/22487380/59743014-98a74600-92a1-11e9-8a10-5e88ac2c492a.png)
![image](https://user-images.githubusercontent.com/22487380/59743018-9c3acd00-92a1-11e9-90dd-3dd323ba1ae9.png)
![image](https://user-images.githubusercontent.com/22487380/59742364-208c5080-92a0-11e9-9286-7b09a66325a9.png)

**Comment by seiriosPlus** [comment]
分别在自己的program_guard下调用minimize？
