### ISSUE TITLE
the first dimension of Input(X) must be large than batch size. at [/ssd2/liyukun01/paddle-env/repos/Paddle/paddle/fluid/operators/sequence_ops/sequence_pool_op.h:44]

### ISSUE THREAD

**Issue by Melonzhou** [PaddlePaddle/Paddle#18201]
- 版本、环境信息：
    1）PaddlePaddle版本：1.5.1
    2）GPU：P40、CUDA9.0
    3）python2.7 centos
- 训练信息
    1）单机2张卡
    2）显存20G

报错信息
  epoch: 1, progress: 1910/9600, step: 1100,speed: 123.092166 steps/s
2019-06-18 14:40:26,332-DEBUG: file being processed:./thirdparty/dev_data/dev.tsv
Traceback (most recent call last):
File "train.py", line 91, in <module>
model.train()
File "nlpt/model/base_model.py", line 384, in model.base_model.BaseModel.train
File "nlpt/model/base_model.py", line 429, in model.base_model.BaseModel.do_test_val
File "nlpt/model/classify_model.py", line 120, in model.classify_model.ClassifyModel.evaluate
File "/home/slurm/job/tmp/job-44891/python27-gcc482/lib/python2.7/site-packages/paddle/fluid/executor.py", line 650, in run
use_program_cache=use_program_cache)
File "/home/slurm/job/tmp/job-44891/python27-gcc482/lib/python2.7/site-packages/paddle/fluid/executor.py", line 748, in _run
exe.run(program.desc, scope, 0, True, True, fetch_var_name)
paddle.fluid.core.EnforceNotMet: Invoke operator sequence_pool error.
Python Callstacks: 
File "/home/slurm/job/tmp/job-44891/python27-gcc482/lib/python2.7/site-packages/paddle/fluid/framework.py", line 1712, in append_op
attrs=kwargs.get("attrs", None))
File "/home/slurm/job/tmp/job-44891/python27-gcc482/lib/python2.7/site-packages/paddle/fluid/layer_helper.py", line 43, in append_op
return self.main_program.current_block().append_op(*args, **kwargs)
File "/home/slurm/job/tmp/job-44891/python27-gcc482/lib/python2.7/site-packages/paddle/fluid/layers/nn.py", line 2424, in sequence_pool
"pad_value": pad_value
File "train.py", line 55, in create_model
bow = fluid.layers.sequence_pool(input=emb, pool_type='sum')
File "train.py", line 81, in <module>
model = ClassifyModel(cfg, create_model)
C++ Callstacks: 
Enforce failed. Expected dims[0] >= static_cast<int64_t>(lod[0].size() - 1), but received dims[0]:3 < static_cast<int64_t>(lod[0].size() - 1):10.
The first dimension of Input(X) must be large than batch size. at [/ssd2/liyukun01/paddle-env/repos/Paddle/paddle/fluid/operators/sequence_ops/sequence_pool_op.h:44]
PaddlePaddle Call Stacks: 
0 0x7f6d1249bc35p void paddle::platform::EnforceNotMet::Init<std::string>(std::string, char const*, int) + 357
1 0x7f6d1249bf92p paddle::platform::EnforceNotMet::EnforceNotMet(std::string const&, char const*, int) + 82
2 0x7f6d132f3295p paddle::operators::SequencePoolKernel<paddle::platform::CUDADeviceContext, float>::Compute(paddle::framework::ExecutionContext const&) const + 3845
3 0x7f6d132f33a0p std::_Function_handler<void (paddle::framework::ExecutionContext const&), paddle::framework::OpKernelRegistrarFunctor<paddle::platform::CUDAPlace, false, 0ul, paddle::operators::SequencePoolKernel<paddle::platform::CUDADeviceContext, float> >::operator()(char const*, char const*, int) const::{lambda(paddle::framework::ExecutionContext const&)#1}>::_M_invoke(std::_Any_data const&, paddle::framework::ExecutionContext const&) + 32
4 0x7f6d14204b58p paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&, paddle::framework::RuntimeContext*) const + 376
5 0x7f6d14204f4bp paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&) const + 555
6 0x7f6d142025ecp paddle::framework::OperatorBase::Run(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&) + 300
7 0x7f6d12611e5ep paddle::framework::Executor::RunPreparedContext(paddle::framework::ExecutorPrepareContext*, paddle::framework::Scope*, bool, bool, bool) + 398
8 0x7f6d12612cf4p paddle::framework::Executor::Run(paddle::framework::ProgramDesc const&, paddle::framework::Scope*, int, bool, bool, std::vector<std::string, std::allocator<std::string> > const&, bool) + 132
9 0x7f6d1248dc03p
10 0x7f6d124cc279p
11 0x7f6de8e4d010p PyEval_EvalFrameEx + 16384
12 0x7f6de8e4eb80p PyEval_EvalCodeEx + 2128
13 0x7f6de8e4d08ep PyEval_EvalFrameEx + 16510
14 0x7f6de8e4eb80p PyEval_EvalCodeEx + 2128
15 0x7f6de8ddfa5dp
16 0x7f6de8dbc3c3p PyObject_Call + 67
17 0x7f6de8dcaa0dp
18 0x7f6dc207d363p
19 0x7f6dc7bd9e42p
20 0x7f6dc7bd2f62p
21 0x7f6dc7bf5771p
22 0x7f6de8dbc3c3p PyObject_Call + 67
23 0x7f6de8e4b583p PyEval_EvalFrameEx + 9587
24 0x7f6de8e4eb80p PyEval_EvalCodeEx + 2128
25 0x7f6de8e4ec82p PyEval_EvalCode + 50
26 0x7f6de8e6760fp
27 0x7f6de8e6867ep PyRun_FileExFlags + 126
28 0x7f6de8e697d7p PyRun_SimpleFileExFlags + 199
29 0x7f6de8e79d9dp Py_Main + 3133
30 0x7f6de80bfbd5p __libc_start_main + 245
31 0x4007c1p

代码信息：
`def create_model(pyreader_name, is_inference=False):
    py_reader, list = custom_encoder_tensor(cfg, pyreader_name)
    text_a = list[0]
    text_b = list[1]
    label = list[2]
    text_a_mask = list[3]
    text_b_mask = list[4]
    text_a_lens = list[5]
    text_b_lens = list[6]

    dict_dim = 22812
    emb_dim = 128
    hid_dim = 128

    filter_size = 3
    num_filters = 256

    left = fluid.layers.sequence_unpad(text_a, length=text_a_lens)
    right = fluid.layers.sequence_unpad(text_b, length=text_b_lens)

    left_emb = fluid.layers.embedding(input=left, size=[
        dict_dim, emb_dim], is_sparse=True,
                                 param_attr=attr.ParamAttr(name="emb"))
    right_emb = fluid.layers.embedding(input=right, size=[
        dict_dim, emb_dim], is_sparse=True,
                                 param_attr=attr.ParamAttr(name="emb"))

    left_cnn = fluid.nets.sequence_conv_pool(input=left_emb, filter_size=filter_size,
                                         num_filters=num_filters,
                                         param_attr=attr.ParamAttr(name="conv"), act="relu")
    right_cnn = fluid.nets.sequence_conv_pool(input=right_emb, filter_size=filter_size,
                                         num_filters=num_filters,
                                         param_attr=attr.ParamAttr(name="conv"), act="relu")
    # matching-pair layer
    concat = fluid.layers.concat([left_cnn, right_cnn], axis=1)

    concat_fc = fluid.layers.fc(input=concat, size=hid_dim, param_attr=attr.ParamAttr(
        name="relu.w"), bias_attr=attr.ParamAttr(name="relu.b"), act="relu", name="relu")

    pred = fluid.layers.fc(input=concat_fc, size=2, param_attr=attr.ParamAttr(
        name="cos_sim.w"),bias_attr=attr.ParamAttr(name="cos_sim.b"), act="softmax", name="cos_sim")

    if is_inference:
        feed_targets_name = [text_a.name, text_b.name, text_a_lens.name, text_b_lens.name]
        return feed_targets_name, pred

    cost = fluid.layers.softmax_with_cross_entropy(logits=pred, label=label)
    avg_cost = fluid.layers.reduce_mean(cost)

    graph_vars = collections.OrderedDict()
    graph_vars["loss"] = avg_cost
    graph_vars["classify_infer"] = pred
    graph_vars["label"] = label

    return py_reader, graph_vars`

**Comment by seiriosPlus** [comment]
有打印proto么， 看一下default_main_program

**Comment by Melonzhou** [comment]
怎么打印proto呢，具体我应该打印些什么呢？

**Comment by seiriosPlus** [comment]
可以用这种类似的方法：
```
            with open("{}.{}".format(model_basename, "proto"), "w") as f:
                f.write(str(main_program))
```

如果没有定义过main_program， 可以使用 ```fluid.default_main_program()```.

**Comment by Yuxiao-Liang** [comment]
我也遇到这个问题了，请问楼主怎么解决的
