### ISSUE TITLE
use environment variable to set trainer

### ISSUE THREAD

**Issue by jacquesqiao** [PaddlePaddle/Paddle#1821]
currently we use
```python
paddle.init(xx1=yy1, xx2=yy2)
```
to init paddle, thus we need to change trianier python code if we want to change from local training to cluster training.
### local init
```python
paddle.init(use_gpu=False, trainer_count=1)
```

### cluster training
```python
# cluster init
paddle.init(
            use_gpu=False,
            trainer_count=1,
            port=7164,
            ports_num=1,
            ports_num_for_sparse=1,
            num_gradient_servers=1)
```

so we need to change this to config with environment variable，like:
```shell
export USE_GPU=True
export TRAINER_COUNT=1
...
python train.py
```

**Comment by typhoonzero** [comment]
I think this is resolve by https://github.com/PaddlePaddle/Paddle/pull/2014
