### ISSUE TITLE
Remove the repeat section in Paddle document.

### ISSUE THREAD

**Issue by pengwangucla** [PaddlePaddle/Paddle#1822]
Why there is always a head section in the description of every layer ? 

![image](https://cloud.githubusercontent.com/assets/4799604/25214292/4d12c9b4-254b-11e7-9da6-d11cf35c46dd.png)

Can someone remove it ?

**Comment by helinwang** [comment]
Yes, we discussed it in yesterday's team meeting as well. It will be removed. @luotao1 do you remember who is assigned to do it?

**Comment by luotao1** [comment]
@helinwang I try to remove it yesterday, but don't have a good way except remove this annotation directly.

**Comment by luotao1** [comment]
@reyoung Do you have a good way to remove it?

**Comment by reyoung** [comment]
> > Do you have a good way to remove it?

As we talked yesterday, the `automodule` is used to generate the documentation for all module, the real method should be used is `automethod` or `autoclass`.

See [here](http://www.sphinx-doc.org/en/stable/ext/autodoc.html) for the details.
