### ISSUE TITLE
switch op性能问题

### ISSUE THREAD

**Issue by LihangLiu** [PaddlePaddle/Paddle#18224]
在使用switch op的过程中，发现耗时很久，利用profiler工具查看了下具体的耗时，如下图：
![image](https://user-images.githubusercontent.com/8502179/59820188-73780d80-935d-11e9-8788-cdf9a6366074.png)

 
ps:
1. 模型是常规的dynamic_rnn模型。
2. 加入switch op是为了将rnn的init和单步infer拆成两个子网络来跑inference，但是发现加入switch op后耗时增加很多。
3. 版本相关：centos, fluid1.3, cuda9 cudnn7

**Comment by phlrain** [comment]
定义两个program 可行吗

**Comment by irukawang** [comment]
请问楼主，如何使用switch实现根据不同条件，tensor流入不同网络的，并优化的呢。
