### ISSUE TITLE
模型infer阶段，加入id类string明文特征，不参与计算，只print出来

### ISSUE THREAD

**Issue by sitong188** [PaddlePaddle/Paddle#18230]
我采用的脚本是util.py中方法解析数据，在infer方法里调用model的配置来预测
想把id加进model的预测阶段, 这里想输出 id + infer的该id特征的vector
因为infer也是batch的计算，这里没办法单独再从数据里拿id去拼

我尝试把id当做特征加进model但不参与计算，有个配置
id_conf = DataConfig(name='firstw-1', shape=[-1, 1], dtype='string')
这里dtype='string'报错，请教有没有好的解决办法

**Comment by xiangyubo** [comment]
建个字典，把每个字符和一个正整数对应起来，然后 dtype='int64' 呢？

**Comment by phlrain** [comment]
需求能不能在描述的清楚一些

**Comment by sitong188** [comment]
“建个字典，把每个字符和一个正整数对应起来，然后 dtype='int64' 呢？”
然后打印了下ctr.py解析的id对应上面说的字典是对的 但是运行报了这个错：
Traceback (most recent call last):
  File "predict.py", line 11, in <module>
    model_pack.infer(feeder=feeder, use_cuda=False, model_dir='model/', batch_size=100, is_local=True)
  File "/home1/chensitong03/fluid/fluid_predict/model_pack.py", line 552, in infer
    predict_ad_val, cmatch_val, label_val, cuid_val = parallel_exe.run(fetch_list=fetch_name_list)
  File "/home1/chensitong03/.jumbo/lib/python2.7/site-packages/paddle/fluid/parallel_executor.py", line 276, in run
    return executor.as_numpy(arr)
  File "/home1/chensitong03/.jumbo/lib/python2.7/site-packages/paddle/fluid/executor.py", line 83, in as_numpy
    return [as_numpy(t) for t in tensor]
  File "/home1/chensitong03/.jumbo/lib/python2.7/site-packages/paddle/fluid/executor.py", line 92, in as_numpy
    return LoDTensor itself directly.")
RuntimeError: [Some of your fetched tensors hold LoD information.             They can not be completely cast to Python ndarray.             Please set the parameter 'return_numpy' as 'False' to             return LoDTensor itself directly.193
, 232,

这个是啥问题啊

**Comment by sitong188** [comment]
还有没有解决，cuid用了一个list来标志，比如这样[1,2,3,4,5,6] 每位代表dict里对应index的字符
在model里定义为：
cuid_conf = DataConfig(name='firstw-1', shape=[-1, 1], dtype='int64', lod_level=1)
在这里读出来：
cuid, age, gender, . . . . . ., label = fluid.layers.read_file(py_reader)

然后再infer方法里这样去fetch:
fetch_name_list = [predict_ad.name, cmatch.name, label.name, cuid.name]
run的时候因为报的错，改成了
predict_ad_val, cmatch_val, label_val, cuid_val = parallel_exe.run(fetch_list=fetch_name_list, return_numpy=False)
但是打印cuid_val的时候发现把多个pv的cuid的list拼到了一起：
好比pv1的cuid读进模型是这样：[1,2,3,4,5]   pv2的是[3,4,5,6]
预期能像模型产出层一样变成 [[1,2,3,4,5],[3,4,5,6]]
结果变成了 [[1,2,3,4,5,3,4,5,6]]

这个怎么改呢

**Comment by sneaxiy** [comment]
@sitong188 您可以自行reshape来取值，目前pe取出来的结果确实是您描述那样的。
