### ISSUE TITLE
add more example configurations for PaddlePaddle.

### ISSUE THREAD

**Issue by lcy-seso** [PaddlePaddle/Paddle#1823]
As discussed, it is necessary to add more example configurations for PaddlePaddle, so that users can better know about how to use PaddlePaddle layers through examples. There may be two ways to do this, I hope to collection ideas about which one is better.

1. Do not remove the current demos directory, and add new example to it. 
2. Create a new repo (like Tensorflow https://github.com/tensorflow/models).

Either way, each example has its own directory, we can put configuration file and doc in it.

**Comment by luotao1** [comment]
可以同时考虑 #1725  "remove old api demo"

**Comment by lcy-seso** [comment]
It is expected that these example configurations are more lightweight than PaddleBook, but more heavyweight than API doc.

**Comment by typhoonzero** [comment]
Agree with No. 2. It may be confusing when "demo" and PaddlePaddle book hold some same examples.

**Comment by qingqing01** [comment]
demo:  可提供完整演示，可以比book轻量，不用很多背景+模型介绍等，可以删掉和book重复的篇章吧。
model_config/example: 可以只提供配置，不用完整演示吧，和demo分开两个目录，或者另一个repo都可以。

**Comment by lcy-seso** [comment]
I support to create a new repo to reduce the maintenance cost.

**Comment by wangkuiyi** [comment]
Created new repo https://github.com/PaddlePaddle/models
