### ISSUE TITLE
upsample需求

### ISSUE THREAD

**Issue by dubhex** [PaddlePaddle/Paddle#18231]
请问paddle现在有支持上采样层吗？在API文档中没有找到。

**Comment by xiangyubo** [comment]
我是一般用户哈，回答也只是为了 mark 一下这个问题。
不知道 fluid.layers.resize_nearest 可以吗？我记得我看 yolo 代码里面，通过这个操作把特征图变大过。

**Comment by phlrain** [comment]
请问下这个采样层具体是指什么操作

**Comment by AIpioneer** [comment]
resize op就是上采样 @dubhex
