### ISSUE TITLE
定义卷积网络包括batch_norm层，执行训练时，一轮就停止并抛出错误

### ISSUE THREAD

**Issue by XFrankly** [PaddlePaddle/Paddle#18244]
Thank you for contributing to PaddlePaddle. Submitting an issue is a great help for us.
Both Chinese and English issues are welcome.

It's hard to solve a problem when important details are missing.
Before submitting the issue, look over the following criteria before handing your request in.

- [ ] Was there a similar issue submitted or resolved before ? You could search issue in the github.
- [ ] Did you retrieve your issue from widespread search engines ?
- [ ] Is my description of the issue clear enough to reproduce this problem?
   * If some errors occurred, we need details about `how do you run your code?`, `what system do you use?`, `Are you using GPU or not?`, etc.
   * If you use an recording [asciinema](https://asciinema.org/) to show what you are doing to make it happen, that's awesome! We could help you solve the problem more quickly.
- [ ] Is my description of the issue use the github markdown correctly?
   * Please use the proper markdown syntaxes for styling all forms of writing, e.g, source code, error information, etc.
   * Check out [this page](https://guides.github.com/features/mastering-markdown/) to find out much more about markdown.

环境：baidu aistudio 自建项目跑卷积网络，三层卷积-池化层，一层batch_norm, 一层fc，

    act='softmax'
    prediction1 = fluid.layers.batch_norm(input=conv_pool_3,
                                       act="relu")
    
    prediction = fluid.layers.fc(input=prediction1, size=1000, act=act)

      在训练的时候抛出的错误

![image](https://user-images.githubusercontent.com/18527102/59893592-040f2600-9410-11e9-8714-881786b2be82.png)

EnforceNotMetTraceback (most recent call last)<ipython-input-10-e74f1c7ec767> in <module>()
     23         test_cost, test_acc = exe.run(program=test_program,
     24                                       feed=feeder.feed(data),
---> 25                                       fetch_list=[avg_cost, acc])
     26         test_accs.append(test_acc[0])
     27         test_costs.append(test_cost[0])
/opt/conda/envs/python27-paddle120-env/lib/python2.7/site-packages/paddle/fluid/executor.pyc in run(self, program, feed, fetch_list, feed_var_name, fetch_var_name, scope, return_numpy, use_program_cache)
    563                 scope=scope,
    564                 return_numpy=return_numpy,
--> 565                 use_program_cache=use_program_cache)
    566         else:
    567             if fetch_list and program._is_data_parallel and program._program and (
/opt/conda/envs/python27-paddle120-env/lib/python2.7/site-packages/paddle/fluid/executor.pyc in _run(self, program, exe, feed, fetch_list, feed_var_name, fetch_var_name, scope, return_numpy, use_program_cache)
    640 
    641         self._feed_data(program, feed, feed_var_name, scope)
--> 642         exe.run(program.desc, scope, 0, True, True, fetch_var_name)
    643         outs = self._fetch_data(fetch_list, fetch_var_name, scope)
    644         if return_numpy:
EnforceNotMet: Invoke operator batch_norm_grad error.
Python Callstacks: 
  File "/opt/conda/envs/python27-paddle120-env/lib/python2.7/site-packages/paddle/fluid/framework.py", line 1654, in append_op
    attrs=kwargs.get("attrs", None))
  File "/opt/conda/envs/python27-paddle120-env/lib/python2.7/site-packages/paddle/fluid/layer_helper.py", line 43, in append_op
    return self.main_program.current_block().append_op(*args, **kwargs)
  File "/opt/conda/envs/python27-paddle120-env/lib/python2.7/site-packages/paddle/fluid/layers/nn.py", line 3096, in batch_norm
    "use_global_stats": use_global_stats
  File "<ipython-input-6-f2d1ca606edf>", line 53, in convolutional_neural_network
    act=act)
  File "<ipython-input-7-5ca02098f025>", line 5, in <module>
    predict =  convolutional_neural_network(images)
  File "/opt/conda/envs/python27-paddle120-env/lib/python2.7/site-packages/IPython/core/interactiveshell.py", line 2878, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "/opt/conda/envs/python27-paddle120-env/lib/python2.7/site-packages/IPython/core/interactiveshell.py", line 2818, in run_ast_nodes
    if self.run_code(code, result):
  File "/opt/conda/envs/python27-paddle120-env/lib/python2.7/site-packages/IPython/core/interactiveshell.py", line 2714, in run_cell
    interactivity=interactivity, compiler=compiler, result=result)
  File "/opt/conda/envs/python27-paddle120-env/lib/python2.7/site-packages/ipykernel/zmqshell.py", line 537, in run_cell
    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)
  File "/opt/conda/envs/python27-paddle120-env/lib/python2.7/site-packages/ipykernel/ipkernel.py", line 208, in do_execute
    res = shell.run_cell(code, store_history=store_history, silent=silent)
  File "/opt/conda/envs/python27-paddle120-env/lib/python2.7/site-packages/ipykernel/kernelbase.py", line 399, in execute_request
    user_expressions, allow_stdin)
  File "/opt/conda/envs/python27-paddle120-env/lib/python2.7/site-packages/ipykernel/kernelbase.py", line 233, in dispatch_shell
    handler(stream, idents, msg)
  File "/opt/conda/envs/python27-paddle120-env/lib/python2.7/site-packages/ipykernel/kernelbase.py", line 283, in dispatcher
    return self.dispatch_shell(stream, msg)
  File "/opt/conda/envs/python27-paddle120-env/lib/python2.7/site-packages/tornado/stack_context.py", line 300, in null_wrapper
    return fn(*args, **kwargs)
  File "/opt/conda/envs/python27-paddle120-env/lib/python2.7/site-packages/zmq/eventloop/zmqstream.py", line 438, in _run_callback
    callback(*args, **kwargs)
  File "/opt/conda/envs/python27-paddle120-env/lib/python2.7/site-packages/zmq/eventloop/zmqstream.py", line 486, in _handle_recv
    self._run_callback(callback, msg)
  File "/opt/conda/envs/python27-paddle120-env/lib/python2.7/site-packages/zmq/eventloop/zmqstream.py", line 456, in _handle_events
    self._handle_recv()
  File "/opt/conda/envs/python27-paddle120-env/lib/python2.7/site-packages/tornado/stack_context.py", line 300, in null_wrapper
    return fn(*args, **kwargs)
  File "/opt/conda/envs/python27-paddle120-env/lib/python2.7/site-packages/tornado/ioloop.py", line 1073, in start
    handler_func(fd_obj, events)
  File "/opt/conda/envs/python27-paddle120-env/lib/python2.7/site-packages/ipykernel/kernelapp.py", line 499, in start
    self.io_loop.start()
  File "/opt/conda/envs/python27-paddle120-env/lib/python2.7/site-packages/traitlets/config/application.py", line 658, in launch_instance
    app.start()
  File "/opt/conda/envs/python27-paddle120-env/lib/python2.7/site-packages/ipykernel_launcher.py", line 16, in <module>
    app.launch_new_instance()
  File "/opt/conda/envs/python27-paddle120-env/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/opt/conda/envs/python27-paddle120-env/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
C++ Callstacks: 
holder_ should not be null
Tensor holds no memory. Call Tensor::mutable_data first. at [/paddle/paddle/fluid/framework/tensor.cc:23]
PaddlePaddle Call Stacks: 
0       0x7fda839b7b68p void paddle::platform::EnforceNotMet::Init<std::string>(std::string, char const*, int) + 360
1       0x7fda839b7eb7p paddle::platform::EnforceNotMet::EnforceNotMet(std::string const&, char const*, int) + 87
2       0x7fda8569d4f9p paddle::framework::Tensor::check_memory_size() const + 185
3       0x7fda839bef19p float const* paddle::framework::Tensor::data<float>() const + 25
4       0x7fda841f059ap paddle::operators::BatchNormGradKernel<paddle::platform::CUDADeviceContext, float>::Compute(paddle::framework::ExecutionContext const&) const + 1882
5       0x7fda841f2113p std::_Function_handler<void (paddle::framework::ExecutionContext const&), paddle::framework::OpKernelRegistrarFunctor<paddle::platform::CUDAPlace, false, 0ul, paddle::operators::BatchNormGradKernel<paddle::platform::CUDADeviceContext, float>, paddle::operators::BatchNormGradKernel<paddle::platform::CUDADeviceContext, double>, paddle::operators::BatchNormGradKernel<paddle::platform::CUDADeviceContext, paddle::platform::float16> >::operator()(char const*, char const*, int) const::{lambda(paddle::framework::ExecutionContext const&)#1}>::_M_invoke(std::_Any_data const&, paddle::framework::ExecutionContext const&) + 35
6       0x7fda856496f6p paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&, paddle::framework::RuntimeContext*) const + 662
7       0x7fda85649e64p paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&) const + 292
8       0x7fda8564778cp paddle::framework::OperatorBase::Run(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&) + 332
9       0x7fda83b2c8bep paddle::framework::Executor::RunPreparedContext(paddle::framework::ExecutorPrepareContext*, paddle::framework::Scope*, bool, bool, bool) + 382
10      0x7fda83b2d6ffp paddle::framework::Executor::Run(paddle::framework::ProgramDesc const&, paddle::framework::Scope*, int, bool, bool, std::vector<std::string, std::allocator<std::string> > const&, bool) + 143
11      0x7fda839a735ep
12      0x7fda839ea72ep
13      0x7fdb015791a7p PyEval_EvalFrameEx + 28695
14      0x7fdb0157b6c9p PyEval_EvalCodeEx + 2025
15      0x7fdb01578b98p PyEval_EvalFrameEx + 27144
16      0x7fdb0157b6c9p PyEval_EvalCodeEx + 2025
17      0x7fdb01578b98p PyEval_EvalFrameEx + 27144
18      0x7fdb0157b6c9p PyEval_EvalCodeEx + 2025
19      0x7fdb0157b8eap PyEval_EvalCode + 26
20      0x7fdb01577cc0p PyEval_EvalFrameEx + 23344
21      0x7fdb0157b6c9p PyEval_EvalCodeEx + 2025
22      0x7fdb01578b98p PyEval_EvalFrameEx + 27144
23      0x7fdb0157b6c9p PyEval_EvalCodeEx + 2025
24      0x7fdb01578b98p PyEval_EvalFrameEx + 27144
25      0x7fdb0157b6c9p PyEval_EvalCodeEx + 2025
26      0x7fdb01504567p
27      0x7fdb014df973p PyObject_Call + 67
28      0x7fdb0157469ep PyEval_EvalFrameEx + 9486
29      0x7fdb0157b6c9p PyEval_EvalCodeEx + 2025
30      0x7fdb01578b98p PyEval_EvalFrameEx + 27144
31      0x7fdb0157b6c9p PyEval_EvalCodeEx + 2025
32      0x7fdb01578b98p PyEval_EvalFrameEx + 27144
33      0x7fdb0157b6c9p PyEval_EvalCodeEx + 2025
34      0x7fdb01578b98p PyEval_EvalFrameEx + 27144
35      0x7fdb0157b6c9p PyEval_EvalCodeEx + 2025
36      0x7fdb01578b98p PyEval_EvalFrameEx + 27144
37      0x7fdb0157b6c9p PyEval_EvalCodeEx + 2025
38      0x7fdb01504567p
39      0x7fdb014df973p PyObject_Call + 67
40      0x7fdb0157469ep PyEval_EvalFrameEx + 9486
41      0x7fdb0157b6c9p PyEval_EvalCodeEx + 2025
42      0x7fdb01504567p
43      0x7fdb014df973p PyObject_Call + 67
44      0x7fdb0157469ep PyEval_EvalFrameEx + 9486
45      0x7fdb0157b6c9p PyEval_EvalCodeEx + 2025
46      0x7fdb01578b98p PyEval_EvalFrameEx + 27144
47      0x7fdb0157b6c9p PyEval_EvalCodeEx + 2025
48      0x7fdb01578b98p PyEval_EvalFrameEx + 27144
49      0x7fdb0157b6c9p PyEval_EvalCodeEx + 2025
50      0x7fdb01504567p
51      0x7fdb014df973p PyObject_Call + 67
52      0x7fdb0157469ep PyEval_EvalFrameEx + 9486
53      0x7fdb0157b6c9p PyEval_EvalCodeEx + 2025
54      0x7fdb01578b98p PyEval_EvalFrameEx + 27144
55      0x7fdb0157b6c9p PyEval_EvalCodeEx + 2025
56      0x7fdb01578b98p PyEval_EvalFrameEx + 27144
57      0x7fdb0157b6c9p PyEval_EvalCodeEx + 2025
58      0x7fdb01578b98p PyEval_EvalFrameEx + 27144
59      0x7fdb0157b6c9p PyEval_EvalCodeEx + 2025
60      0x7fdb01578b98p PyEval_EvalFrameEx + 27144
61      0x7fdb0157b6c9p PyEval_EvalCodeEx + 2025
62      0x7fdb0157b8eap PyEval_EvalCode + 26
63      0x7fdb01577cc0p PyEval_EvalFrameEx + 23344
64      0x7fdb0157b6c9p PyEval_EvalCodeEx + 2025
65      0x7fdb01578b98p PyEval_EvalFrameEx + 27144
66      0x7fdb0157b6c9p PyEval_EvalCodeEx + 2025
67      0x7fdb0150447ap
68      0x7fdb014df973p PyObject_Call + 67
69      0x7fdb015a8320p
70      0x7fdb015a89dep Py_Main + 1374
71      0x7fdb00779830p __libc_start_main + 240
72      0x55613287107fp

**Comment by sneaxiy** [comment]
能否给出完整的代码，以便我们复现？
