### ISSUE TITLE
调用fluid.io.save_inference_model后，保存的目录下只有_model_这个文件，没有其他模型参数

### ISSUE THREAD

**Issue by Lizhengo** [PaddlePaddle/Paddle#18250]
调用fluid.io.save_inference_model后，保存的目录下只有_model_这个文件，没有其他模型参数
模型是基于ernie的模型
<img width="769" alt="image" src="https://user-images.githubusercontent.com/28192236/59899922-1184da00-9429-11e9-99f6-57893a7962eb.png">

**Comment by Superjomn** [comment]
__model__ 内容方便给出来吗，我可视化看看

**Comment by Lizhengo** [comment]
已解决，paddle升级到1.3.1以上就可以了，因为BERT用了scale op，1.3.0刚好会触发这个错误,1.3.1之后修复了
