### ISSUE TITLE
landmark 中 resnet152 使用 TensorRT 预测有 diff

### ISSUE THREAD

**Issue by mzchtx** [PaddlePaddle/Paddle#18259]
## 环境
    1）PaddlePaddle版本：1.4.1
    2）CUDA 8.0 + cudnn v7 + TensorRT
    3）系统环境：CentOs 6u3
    4）c++ 预测

## 复现

模型：[landmark retrieval model](https://github.com/PaddlePaddle/models/tree/develop/PaddleCV/Research/landmark) 第二部分

```
python infer_retrieval.py test_retrieval res152_arcmargin
```

使用带 TensorRT 的预测和不带 TensorRT 的预测有 diff，跑第三部分没问题

**Comment by NHZlX** [comment]
您好， 我这边先复现一下。

**Comment by mzchtx** [comment]
看了下，是因为这个 shape 会变导致的。

![image](https://user-images.githubusercontent.com/37564754/63022737-18cede00-bed6-11e9-9719-962ac3a4593a.png)

**Comment by NHZlX** [comment]
trt 接受的输入为模型描述中shape的大小。 Diff产生的原因是因为trt输入的shape和 模型描述中的shape的大小不一致。
