### ISSUE TITLE
fluid.global_scope().find_var 使用问题

### ISSUE THREAD

**Issue by lgone2000** [PaddlePaddle/Paddle#18270]
下面程序中，
print(list(fluid.default_main_program().list_vars()))
可以正确输出所有变量。
但 print('v=', fluid.global_scope().find_var('fc.w_0')) 返回为None
执行 exe.run(fluid.default_startup_program()) 后有可以正常输出变量。

难道var缺省不在global_scope中？如果要求必须执行startup_program, 希望能在文档中明确说明这些变量的状态，以及什么函数是在 startup_program执行后才是可用的。 否则让人混淆。
另外如果内部状态不完整情况下调用find_var ，建议扔一个异常，而不是返回None。

```

def test_find_var():
    input = fluid.layers.data(name='input', shape=[1], dtype='float32')
    fc = fluid.layers.fc(name='fc', input=input, size=10)
    loss = fluid.layers.reduce_sum(input=fc)
    
    print(list(fluid.default_main_program().list_vars()))
    #will output the vars
    
    
    print('v=', fluid.global_scope().find_var('fc.w_0'))
    #output None
    
    exe = fluid.Executor(fluid.CPUPlace())
    exe.run(fluid.default_startup_program())
    print('v=', fluid.global_scope().find_var('fc.w_0'))
    #output fc.w_0

```

**Comment by NHZlX** [comment]
您好 你是要打印模型参数还是模型输出呢

**Comment by NHZlX** [comment]
执行 exe.run(fluid.default_startup_program()) 过程是在加载参数的过程。有必要加入到文档中去。这边会反馈到相关人员。

=======

https://gist.github.com/NHZlX/4116e09952ab54e66dadec094e9769e2 参照这个脚本， python get_var_fluid.py  {your_model_dir} {the_tmp_var_name}  ，该脚本默认输入全为1， 并将对应的中间变量写入到文件中。
