### ISSUE TITLE
ERNIE做dbqa问答时，如何查看测试输出的文本预测结果

### ISSUE THREAD

**Issue by TianTian-O1** [PaddlePaddle/Paddle#18291]
目前测试的展示效果是可以看见损失函数等数据，如果想查看实际输出的文本数据该怎么操作？

**Comment by tianxin1860** [comment]
实际输出的文本数据是指经过 ERNIE 编码后的每个token 的 embedding ?

**Comment by TianTian-O1** [comment]
就像示例一样，预测哈尔滨，冰雪一样，这几个输出结果是怎么一个转化过程呢


 
---原始邮件---
发件人: "tianxin"<notifications@github.com>
发送时间: 2019年6月24日(星期一) 晚上8:33
收件人: "PaddlePaddle/Paddle"<Paddle@noreply.github.com>;
抄送: "Author"<author@noreply.github.com>;"TianZhenGG"<410771376@qq.com>;
主题: Re: [PaddlePaddle/Paddle] ERNIE做dbqa问答时，如何查看测试输出的文本预测结果 (#18291)



实际输出的文本数据是指经过 ERNIE 编码后的每个token 的 embedding ?

**Comment by tianxin1860** [comment]
_“哈尔滨”_ 在预测阶段对应的是  _“MASK MASK MASK”_, 每个 _MASK_ 都有各自对应的 embedding， 这个 embedding 后接 FC 和 softmax 预测该 _MASK_ 对应真实单词的概率分布，然后从概率分布中取概率最大的 Token 作为预测值输出。

**Comment by TianTian-O1** [comment]
ok  谢啦。


 
---原始邮件---
发件人: "tianxin"<notifications@github.com>
发送时间: 2019年6月25日(星期二) 晚上8:26
收件人: "PaddlePaddle/Paddle"<Paddle@noreply.github.com>;
抄送: "Author"<author@noreply.github.com>;"TianZhenGG"<410771376@qq.com>;
主题: Re: [PaddlePaddle/Paddle] ERNIE做dbqa问答时，如何查看测试输出的文本预测结果 (#18291)



“哈尔滨” 在预测阶段对应的是  “MASK MASK MASK”, 每个 MASK 都有各自对应的 embedding， 这个 embedding 后接 FC 和 softmax 预测该 MASK 对应真实单词的概率分布，然后从概率分布中取概率最大的 Token 作为预测值输出。
