### ISSUE TITLE
slice bug

### ISSUE THREAD

**Issue by XipengY** [PaddlePaddle/Paddle#18315]
1. self.new_proposals = fluid.layers.slice(self.proposals, axes=[1], starts=[2], ends=[6])
2. self.new_proposals = fluid.layers.slice(self.proposals, axes=[0, 1], starts=[0, 2], ends=[INT_MAX, 6])
写法1，返回的lod_level=2, 写法2，返回的lod_level=1, 写法2改变了lod_level.

**Comment by wzzju** [comment]
请问可以给出详细具体的例子吗？
