### ISSUE TITLE
Paddle/paddle/fluid/train/demo编译出错：'paddle/fluid/framework/data_feed.pb.h' file not found

### ISSUE THREAD

**Issue by vincentXiyu** [PaddlePaddle/Paddle#18319]
- 版本、环境信息：
    1）PaddlePaddle版本：develop
    2）CPU：Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
    3）GPU：无
    4）系统环境：Mac OS 10.14、Python2.7

- 安装方式信息：
2）本地编译：
PADDLE_LIB=/paddle/lib/dir（自己指定了另外一个本地路径）
cmake .. -DFLUID_INSTALL_DIR=$PADDLE_LIB \
         -DCMAKE_BUILD_TYPE=Release \
         -DWITH_GPU=OFF \
         -DWITH_STYLE_CHECK=OFF \
         -DWITH_MKL=OFF \
         -DWITH_MKLDNN=OFF       

- 复现信息：
所有步骤与/paddle/fluid/train/demo下README一致

- 问题描述：
在最后一步make时报错：
[ 50%] Building CXX object CMakeFiles/demo_trainer.dir/demo_trainer.cc.o
In file included from /my_own_path/Paddle/paddle/fluid/train/demo/demo_trainer.cc:18:
In file included from /my_own_path/paddle/lib/dir/paddle/fluid/framework/executor.h:22:
In file included from /my_own_path/paddle/lib/dir/paddle/fluid/framework/data_set.h:25:
/my_own_path/paddle/lib/dir/paddle/fluid/framework/data_feed.h:35:10: fatal error:
      'paddle/fluid/framework/data_feed.pb.h' file not found
#include "paddle/fluid/framework/data_feed.pb.h"
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
make[2]: *** [CMakeFiles/demo_trainer.dir/demo_trainer.cc.o] Error 1
make[1]: *** [CMakeFiles/demo_trainer.dir/all] Error 2
make: *** [all] Error 2

补充说明：
我自己查找了Paddle/build/paddle/fluid/framework/下面有data_feed.pb.h。
因此我尝试将文件拷贝到$PADDLE_LIB路径下，然后再make，报错：
[ 50%] Building CXX object CMakeFiles/demo_trainer.dir/demo_trainer.cc.o
In file included from /my_own_path/Paddle/paddle/fluid/train/demo/demo_trainer.cc:18:
In file included from /my_own_path/paddle/lib/dir/paddle/fluid/framework/executor.h:22:
In file included from /my_own_path/paddle/lib/dir/paddle/fluid/framework/data_set.h:25:
/my_own_path/paddle/lib/dir/paddle/fluid/framework/data_feed.h:36:10: fatal error:
      'paddle/fluid/framework/fleet/fleet_wrapper.h' file not found
#include "paddle/fluid/framework/fleet/fleet_wrapper.h"
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
make[2]: *** [CMakeFiles/demo_trainer.dir/demo_trainer.cc.o] Error 1
make[1]: *** [CMakeFiles/demo_trainer.dir/all] Error 2
make: *** [all] Error 2

此时，我在Paddle/build/paddle/fluid/framework/下面找不到相应文件了

**Comment by vincentXiyu** [comment]
其实我在docker上安装也会出现一样的问题

Docker编译
cmake .. -DFLUID_INSTALL_DIR=$PADDLE_LIB
-DWITH_GPU=ON 
-DWITH_TESTING=ON

其他按照README去复现就行。会出一样的问题。希望能帮忙看一下，谢谢啦~~

**Comment by kkkkkkkk94** [comment]
出现一模一样的问题，报的错误也是一模一样。手动将缺少文件拷贝到$PADDLE_LIB路径下，就会编译通过，但是会出现连接错误。希望可以解决这个问题。谢谢。。

**Comment by guru4elephant** [comment]
我们会清理依赖，把demo修好

**Comment by guru4elephant** [comment]
it works now @vincentXiyu @kkkkkkkk94

**Comment by LZZhideonbush** [comment]
fatal error: paddle/fluid/framework/data_feed.pb.h: 没有那个文件或目录
 #include "paddle/fluid/framework/data_feed.pb.h"
