### ISSUE TITLE
pyreader加一个traceback.print_exc()可好？

### ISSUE THREAD

**Issue by OleNet** [PaddlePaddle/Paddle#18320]
python/lib/python2.7/site-packages/paddle/fluid/layers/io.py", line [592](https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/fluid/layers/io.py#L592), in __provider_thread__
raise ex
ValueError: too many values to unpack

raise ex前加一个traceback.print_exc()可好？
否则报错的信息都是没有任何意义的信息，完全无助于任何的debug

**Comment by sneaxiy** [comment]
感谢您的建议，我们会考虑在后续版本中添加更完善的错误提示。
