### ISSUE TITLE
卷积后尺寸问题

### ISSUE THREAD

**Issue by 1286667673** [PaddlePaddle/Paddle#18344]
您好：我现在有个问题想请教您
我的输入图像尺寸为：(1, 1, 432, 768)
标签尺寸为：(1, 1, 108, 192)
输入图像经过以下网络计算，计算后的输入图像的尺寸和标签尺寸应不应该一样呢？经过两次池化我感觉是除以4了？为什么老报错elementwise_sub error.
def conv2d_neural_network(self,img):
        # 第一个卷积-池化层
        S_conv_1 = fluid.layers.conv2d(input=img,filter_size=5,num_filters=24,act="relu") 
        S_conv_pool_1 = fluid.layers.pool2d(input=S_conv_1, pool_size=2, pool_stride=2)
         # 第二个卷积-池化层
        S_conv_2 = fluid.layers.conv2d(input=S_conv_pool_1,filter_size=3,num_filters=48,act="relu")
        S_conv_pool_2 = fluid.layers.pool2d(input=S_conv_2, pool_size=2, pool_stride=2)
        # 第三个卷积
        S_conv_pool_3 = fluid.layers.conv2d(input =S_conv_pool_2,num_filters=24,filter_size=3,act="relu")
        # 第四个卷积  
        S_conv_pool_4 = fluid.layers.conv2d(input =S_conv_pool_3,num_filters=12,filter_size=3,act="relu")
        y_predict = fluid.layers.conv2d(input =S_conv_pool_4,num_filters=1,filter_size=1,stride=1)
        return y_predict

**Comment by jerrywgz** [comment]
elementwise_sub error应该是在计算loss的时候报的错，可以在loss前把输入通过fluid.layers.Print 打印出来看下shape。http://www.paddlepaddle.org/documentation/docs/zh/1.4/api_cn/layers_cn.html#print
