### ISSUE TITLE
Mac安装报错，ModuleNotFoundError: No module named 'paddle.fluid.core_noavx'

### ISSUE THREAD

**Issue by DDDivano** [PaddlePaddle/Paddle#18348]
涉及python27 python36 python37
经排查是cpuinfo包返回值不稳定，导致没有走avx分支，noavx没有编译报错。
复现代码
![image](https://user-images.githubusercontent.com/10734244/60168821-1a661900-9838-11e9-9c2a-dd90dd763d80.png)

![image](https://user-images.githubusercontent.com/10734244/60168322-3917e000-9837-11e9-858a-ff111ed43217.png)
![image](https://user-images.githubusercontent.com/10734244/60168358-42a14800-9837-11e9-8651-113707e03908.png)
出错代码位置
core.py 
![image](https://user-images.githubusercontent.com/10734244/60168467-7a0ff480-9837-11e9-848c-0293b165dac9.png)

**Comment by tensor-tang** [comment]
related https://github.com/workhorsy/py-cpuinfo/issues/133
