### ISSUE TITLE
create_parameter can't accept dtype=np.float32

### ISSUE THREAD

**Issue by Genie-Liu** [PaddlePaddle/Paddle#18352]
I'm trying to create tensor myself and find that fluid.layers.create_tensor can accept np.float32 as dtype parameter but fluid.layers.create_parameter can't. Shouldn't they both accept np.float32 or both not.

![pic(3)](https://user-images.githubusercontent.com/34557281/60170796-cf4e0500-983b-11e9-8c9f-0eb79d325260.jpg)

AttributeError: type object 'numpy.float32' has no attribute 'startswith'

There's different way to deal with dtype in these two method:

create_parameter:

https://github.com/PaddlePaddle/Paddle/blob/3c9755bbb948e4a58c6b67dad1fd40a52be696e6/python/paddle/fluid/layer_helper_base.py#L279-L297

create_tensor:

https://github.com/PaddlePaddle/Paddle/blob/3c9755bbb948e4a58c6b67dad1fd40a52be696e6/python/paddle/fluid/framework.py#L470-L480

**Comment by jerrywgz** [comment]
感谢您的反馈，目前确实存在这个问题，我们会尽快商讨解决方案
