### ISSUE TITLE
增量训练，前一次训练能力丢失的问题。

### ISSUE THREAD

**Issue by 707503331** [PaddlePaddle/Paddle#18359]
- 版本、环境信息：
    1）PaddlePaddle版本：1.4.1
    3）GPU：百度1小时的GPU算力卡
    4）系统环境：Python3.5

- 模型信息
1）模型名称 Mobilenet V1
2）自定义数据集 
3）使用算法名称 
4）模型链接
- 复现信息：如为报错，请给出复现环境、复现步骤
- 问题描述：先训练数据集A，再增量训练数据集B，2个数据集没有交接；
A训练完毕，做一次预测，打印出来的是是本次定义的标签；
B训练完毕，用与A同样的预测数据，做一次训练，打印出来的都是B数据集的标签定义；
结论：A数据集训练的“标签”都丢失了，貌似被覆盖了。

以下是我的训练程序(摘自夜雨飘零的博客，改造了部分代码)：
# -*- coding: utf-8 -*-
import os
import shutil
import mobilenet_v1
import paddle as paddle
import reader
import paddle.fluid as fluid

crop_size = 224
resize_size = 250
#checkpoint = 'MobileNet/119'
checkpoint = None
#训练总数
trainNumber = 100
#最后一次训练id
lastTrainNo = trainNumber - 1
classDim = 4000

f = open("log.txt", "w")

# 定义输入层
image = fluid.layers.data(name='image', shape=[3, crop_size, crop_size], dtype='float32')
label = fluid.layers.data(name='label', shape=[1], dtype='int64')

# 获取分类器，因为这次只爬取了6个类别的图片，所以分类器的类别大小为6
model = mobilenet_v1.net(image, classDim)

# 获取损失函数和准确率函数
cost = fluid.layers.cross_entropy(input=model, label=label)
avg_cost = fluid.layers.mean(cost)
acc = fluid.layers.accuracy(input=model, label=label)

# 获取训练和测试程序
test_program = fluid.default_main_program().clone(for_test=True)

# 定义优化方法
optimizer = fluid.optimizer.AdamOptimizer(learning_rate=1e-3,
                                          regularization=fluid.regularizer.L2DecayRegularizer(1e-4))
opts = optimizer.minimize(avg_cost)

# 获取自定义数据
train_reader = paddle.batch(reader=reader.train_reader('../data/data8509/train_list.txt', crop_size, resize_size), batch_size=32)
test_reader = paddle.batch(reader=reader.test_reader('../data/data8509/test_list.txt', crop_size), batch_size=32)

# 定义一个使用GPU的执行器
place = fluid.CUDAPlace(0)
#place = fluid.CPUPlace()
exe = fluid.Executor(place)
# 进行参数初始化
exe.run(fluid.default_startup_program())

if checkpoint is not None:
    print('----加载历史训练数据---%s'%(checkpoint))
    fluid.io.load_persistables(exe, checkpoint, main_program=fluid.default_startup_program())

# 定义输入数据维度
feeder = fluid.DataFeeder(place=place, feed_list=[image, label])

# 训练10次
for pass_id in range(trainNumber):
    # 进行训练
    for batch_id, data in enumerate(train_reader()):
        train_cost, train_acc = exe.run(program=fluid.default_main_program(),
                                        feed=feeder.feed(data),
                                        fetch_list=[avg_cost, acc])

        # 每100个batch打印一次信息
        if batch_id % 100 == 0:
            print('Pass:%d, Batch:%d, Cost:%0.5f, Accuracy:%0.5f' %
                  (pass_id, batch_id, train_cost[0], train_acc[0]),file=f)

    # 进行测试
    test_accs = []
    test_costs = []
    for batch_id, data in enumerate(test_reader()):
        test_cost, test_acc = exe.run(program=test_program,
                                      feed=feeder.feed(data),
                                      fetch_list=[avg_cost, acc])
        test_accs.append(test_acc[0])
        test_costs.append(test_cost[0])
    # 求测试结果的平均值
    test_cost = (sum(test_costs) / len(test_costs))
    test_acc = (sum(test_accs) / len(test_accs))
    print('Test:%d, Cost:%0.5f, Accuracy:%0.5f' % (pass_id, test_cost, test_acc),file=f)
    f.flush()
	#保存模型后续增量训练
    model_path = os.path.join('MobileNet',str(pass_id))
    if not os.path.isdir(model_path):
        os.makedirs(model_path)
    fluid.io.save_persistables(exe, model_path, main_program=fluid.default_main_program())
	
    if pass_id == lastTrainNo:
        # 保存预测模型
        save_path = 'infer_model'
        # 删除旧的模型文件
        shutil.rmtree(save_path, ignore_errors=True)
        # 创建保持模型文件目录
        os.makedirs(save_path)
        # 保存预测模型
        fluid.io.save_inference_model(save_path, feeded_var_names=[image.name], target_vars=[model], executor=exe)
f.close()

**Comment by frankwhzhang** [comment]
"标签"是什么意思 有没有完整的格式化的代码

**Comment by 707503331** [comment]
我能直接发邮件附件给你吗？我可以把代码文件发给你




------------------ 原始邮件 ------------------
发件人: "zhang wenhui"<notifications@github.com>;
发送时间: 2019年6月27日(星期四) 中午11:00
收件人: "PaddlePaddle/Paddle"<Paddle@noreply.github.com>;
抄送: "Kevin Bu"<707503331@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [PaddlePaddle/Paddle] 增量训练，前一次训练能力丢失的问题。 (#18359)




"标签"是什么意思 有没有完整的格式化的代码

**Comment by 707503331** [comment]
标签 就是 trian_list .txt 中的 label值，例如 下面的394：
tt/058477632c562e95ef0e9c035d4c950e.jpg	394
tt/1589d2ddd194fa5396b7ed29a190d476.jpg	394
tt/258feabe7981e091ed158316a7e51dbd.jpg	394

**Comment by 707503331** [comment]
# -*- coding: utf-8 -*-
import os
import shutil
import mobilenet_v1
import paddle as paddle
import reader
import paddle.fluid as fluid

crop_size = 224
resize_size = 250
#checkpoint = 'MobileNet/119'
checkpoint = None
#训练总数
trainNumber = 100
#最后一次训练id
lastTrainNo = trainNumber - 1
classDim = 4000

f = open("log.txt", "w")

# 定义输入层
image = fluid.layers.data(name='image', shape=[3, crop_size, crop_size], dtype='float32')
label = fluid.layers.data(name='label', shape=[1], dtype='int64')

# 获取分类器，因为这次只爬取了6个类别的图片，所以分类器的类别大小为6
model = mobilenet_v1.net(image, classDim)

# 获取损失函数和准确率函数
cost = fluid.layers.cross_entropy(input=model, label=label)
avg_cost = fluid.layers.mean(cost)
acc = fluid.layers.accuracy(input=model, label=label)

# 获取训练和测试程序
test_program = fluid.default_main_program().clone(for_test=True)

# 定义优化方法
optimizer = fluid.optimizer.AdamOptimizer(learning_rate=1e-3,
                                          regularization=fluid.regularizer.L2DecayRegularizer(1e-4))
opts = optimizer.minimize(avg_cost)

# 获取自定义数据
train_reader = paddle.batch(reader=reader.train_reader('../data/data8509/train_list.txt', crop_size, resize_size), batch_size=32)
test_reader = paddle.batch(reader=reader.test_reader('../data/data8509/test_list.txt', crop_size), batch_size=32)

# 定义一个使用GPU的执行器
place = fluid.CUDAPlace(0)
#place = fluid.CPUPlace()
exe = fluid.Executor(place)
# 进行参数初始化
exe.run(fluid.default_startup_program())

if checkpoint is not None:
    print('----加载历史训练数据---%s'%(checkpoint))
    fluid.io.load_persistables(exe, checkpoint, main_program=fluid.default_startup_program())

# 定义输入数据维度
feeder = fluid.DataFeeder(place=place, feed_list=[image, label])

# 训练10次
for pass_id in range(trainNumber):
    # 进行训练
    for batch_id, data in enumerate(train_reader()):
        train_cost, train_acc = exe.run(program=fluid.default_main_program(),
                                        feed=feeder.feed(data),
                                        fetch_list=[avg_cost, acc])

        # 每100个batch打印一次信息
        if batch_id % 100 == 0:
            print('Pass:%d, Batch:%d, Cost:%0.5f, Accuracy:%0.5f' %
                  (pass_id, batch_id, train_cost[0], train_acc[0]),file=f)

    # 进行测试
    test_accs = []
    test_costs = []
    for batch_id, data in enumerate(test_reader()):
        test_cost, test_acc = exe.run(program=test_program,
                                      feed=feeder.feed(data),
                                      fetch_list=[avg_cost, acc])
        test_accs.append(test_acc[0])
        test_costs.append(test_cost[0])
    # 求测试结果的平均值
    test_cost = (sum(test_costs) / len(test_costs))
    test_acc = (sum(test_accs) / len(test_accs))
    print('Test:%d, Cost:%0.5f, Accuracy:%0.5f' % (pass_id, test_cost, test_acc),file=f)
    f.flush()
	#保存模型后续增量训练
    model_path = os.path.join('MobileNet',str(pass_id))
    if not os.path.isdir(model_path):
        os.makedirs(model_path)
    fluid.io.save_persistables(exe, model_path, main_program=fluid.default_main_program())
	
    if pass_id == lastTrainNo:
        # 保存预测模型
        save_path = 'infer_model'
        # 删除旧的模型文件
        shutil.rmtree(save_path, ignore_errors=True)
        # 创建保持模型文件目录
        os.makedirs(save_path)
        # 保存预测模型
        fluid.io.save_inference_model(save_path, feeded_var_names=[image.name], target_vars=[model], executor=exe)
f.close()

**Comment by 707503331** [comment]
# -*- coding: utf-8 -*-
import os
import shutil
import mobilenet_v1
import paddle as paddle
import reader
import paddle.fluid as fluid

crop_size = 224
resize_size = 250
checkpoint = 'MobileNet/119'
#checkpoint = None
#训练总数
trainNumber = 100
#最后一次训练id
lastTrainNo = trainNumber - 1
classDim = 4000
f = open("log.txt", "w")
# 定义输入层
image = fluid.layers.data(name='image', shape=[3, crop_size, crop_size], dtype='float32')
label = fluid.layers.data(name='label', shape=[1], dtype='int64')
# 获取分类器，因为这次只爬取了6个类别的图片，所以分类器的类别大小为6
model = mobilenet_v1.net(image, classDim)
# 获取损失函数和准确率函数
cost = fluid.layers.cross_entropy(input=model, label=label)
avg_cost = fluid.layers.mean(cost)
acc = fluid.layers.accuracy(input=model, label=label)
# 获取训练和测试程序
test_program = fluid.default_main_program().clone(for_test=True)
# 定义优化方法
optimizer = fluid.optimizer.AdamOptimizer(learning_rate=1e-3,regularization=fluid.regularizer.L2DecayRegularizer(1e-4))
opts = optimizer.minimize(avg_cost)
# 获取自定义数据
train_reader = paddle.batch(reader=reader.train_reader('../data/data8509/train_list.txt', crop_size, resize_size), batch_size=32)
test_reader = paddle.batch(reader=reader.test_reader('../data/data8509/test_list.txt', crop_size), batch_size=32)
# 定义一个使用GPU的执行器
#place = fluid.CUDAPlace(0)
place = fluid.CPUPlace()
exe = fluid.Executor(place)
# 进行参数初始化
exe.run(fluid.default_startup_program())
if checkpoint is not None:
    print('----加载历史训练数据---%s'%(checkpoint))
    fluid.io.load_persistables(exe, checkpoint, main_program=fluid.default_main_program())
# 定义输入数据维度
feeder = fluid.DataFeeder(place=place, feed_list=[image, label])
# 训练10次
for pass_id in range(trainNumber):
    # 进行训练
    for batch_id, data in enumerate(train_reader()):
        train_cost, train_acc = exe.run(program=fluid.default_main_program(),feed=feeder.feed(data),fetch_list=[avg_cost, acc])
        # 每100个batch打印一次信息
        if batch_id % 100 == 0:
            print('Pass:%d, Batch:%d, Cost:%0.5f, Accuracy:%0.5f' %(pass_id, batch_id, train_cost[0], train_acc[0]),file=f)
    # 进行测试
    test_accs = []
    test_costs = []
    for batch_id, data in enumerate(test_reader()):
        test_cost, test_acc = exe.run(program=test_program,feed=feeder.feed(data),fetch_list=[avg_cost, acc])
        test_accs.append(test_acc[0])
        test_costs.append(test_cost[0])
    # 求测试结果的平均值
    test_cost = (sum(test_costs) / len(test_costs))
    test_acc = (sum(test_accs) / len(test_accs))
    print('Test:%d, Cost:%0.5f, Accuracy:%0.5f' % (pass_id, test_cost, test_acc),file=f)
    f.flush()
	#保存模型后续增量训练
    model_path = os.path.join('MobileNet',str(pass_id))
    if not os.path.isdir(model_path):
        os.makedirs(model_path)
    fluid.io.save_persistables(exe, model_path, main_program=fluid.default_main_program())	
    if pass_id == lastTrainNo:
        # 保存预测模型
        save_path = 'infer_model'
        # 删除旧的模型文件
        shutil.rmtree(save_path, ignore_errors=True)
        # 创建保持模型文件目录
        os.makedirs(save_path)
        # 保存预测模型
        fluid.io.save_inference_model(save_path, feeded_var_names=[image.name], target_vars=[model], executor=exe)
f.close()

**Comment by 707503331** [comment]
# -*- coding: utf-8 -*-
import os
import shutil
import mobilenet_v1
import paddle as paddle
import reader
import paddle.fluid as fluid

crop_size = 224
resize_size = 250
checkpoint = 'MobileNet/119'
#checkpoint = None
#训练总数
trainNumber = 100
#最后一次训练id
lastTrainNo = trainNumber - 1
classDim = 4000
f = open("log.txt", "w")
#定义输入层
image = fluid.layers.data(name='image', shape=[3, crop_size, crop_size], dtype='float32')
label = fluid.layers.data(name='label', shape=[1], dtype='int64')
#获取分类器，因为这次只爬取了6个类别的图片，所以分类器的类别大小为6
model = mobilenet_v1.net(image, classDim)
#获取损失函数和准确率函数
cost = fluid.layers.cross_entropy(input=model, label=label)
avg_cost = fluid.layers.mean(cost)
acc = fluid.layers.accuracy(input=model, label=label)
#获取训练和测试程序
test_program = fluid.default_main_program().clone(for_test=True)
#定义优化方法
optimizer = fluid.optimizer.AdamOptimizer(learning_rate=1e-3,regularization=fluid.regularizer.L2DecayRegularizer(1e-4))
opts = optimizer.minimize(avg_cost)
#获取自定义数据
train_reader = paddle.batch(reader=reader.train_reader('../data/data8509/train_list.txt', crop_size, resize_size), batch_size=32)
test_reader = paddle.batch(reader=reader.test_reader('../data/data8509/test_list.txt', crop_size), batch_size=32)
#定义一个使用GPU的执行器
#place = fluid.CUDAPlace(0)
place = fluid.CPUPlace()
exe = fluid.Executor(place)
#进行参数初始化
exe.run(fluid.default_startup_program())
if checkpoint is not None:
    print('----加载历史训练数据---%s'%(checkpoint))
    fluid.io.load_persistables(exe, checkpoint, main_program=fluid.default_main_program())
#定义输入数据维度
feeder = fluid.DataFeeder(place=place, feed_list=[image, label])
#训练10次
for pass_id in range(trainNumber):
    #进行训练
    for batch_id, data in enumerate(train_reader()):
        train_cost, train_acc = exe.run(program=fluid.default_main_program(),feed=feeder.feed(data),fetch_list=[avg_cost, acc])
        #每100个batch打印一次信息
        if batch_id % 100 == 0:
            print('Pass:%d, Batch:%d, Cost:%0.5f, Accuracy:%0.5f' %(pass_id, batch_id, train_cost[0], train_acc[0]),file=f)
    #进行测试
    test_accs = []
    test_costs = []
    for batch_id, data in enumerate(test_reader()):
        test_cost, test_acc = exe.run(program=test_program,feed=feeder.feed(data),fetch_list=[avg_cost, acc])
        test_accs.append(test_acc[0])
        test_costs.append(test_cost[0])
    #求测试结果的平均值
    test_cost = (sum(test_costs) / len(test_costs))
    test_acc = (sum(test_accs) / len(test_accs))
    print('Test:%d, Cost:%0.5f, Accuracy:%0.5f' % (pass_id, test_cost, test_acc),file=f)
    f.flush()
	#保存模型后续增量训练
    model_path = os.path.join('MobileNet',str(pass_id))
    if not os.path.isdir(model_path):
        os.makedirs(model_path)
    fluid.io.save_persistables(exe, model_path, main_program=fluid.default_main_program())	
    if pass_id == lastTrainNo:
        #保存预测模型
        save_path = 'infer_model'
        #删除旧的模型文件
        shutil.rmtree(save_path, ignore_errors=True)
        #创建保持模型文件目录
        os.makedirs(save_path)
        #保存预测模型
        fluid.io.save_inference_model(save_path, feeded_var_names=[image.name], target_vars=[model], executor=exe)
f.close()

**Comment by 707503331** [comment]
代码帖到这里面 格式化就被打乱了。

**Comment by 707503331** [comment]
[train2filelog .txt](https://github.com/PaddlePaddle/Paddle/files/3332831/train2filelog.txt)

**Comment by 707503331** [comment]
[train2filelog1.txt](https://github.com/PaddlePaddle/Paddle/files/3332849/train2filelog1.txt)

**Comment by 707503331** [comment]
> "标签"是什么意思 有没有完整的格式化的代码
程序源文件已上传，请看上个留言 txt 内容

**Comment by frankwhzhang** [comment]
训练能力丢失是什么意思？

**Comment by 707503331** [comment]
就是无法识别第一次训练过的图片了。
例如：
我第一次训练 A数据集(内含有2种猫的数据， label 分别为1,2)， tain_list.txt 的数据样例是：
图片1.jpg  1
图片2.jpg  1
.................
图片99.jpg  2
图片100.jpg  2
图片101.jpg  2


我第二次训练 B数据集(内含有2种猫的数据， label 分别为3,4)， tain_list.txt 的数据样例是：
图片1.jpg  3
图片2.jpg  3
.................
图片99.jpg  4
图片100.jpg  4
...................



按上面的数据集训练2次，
第一次训练A数据集，并在最后一轮训练结束时 调用 save_persistent() 保存下模型参数，以便后续增量训练加载;
第一轮结束后，执行预测，能正确的给出预测结果；


第二次训练，首先加载(load_persistent())上一轮保存过的参数，再开始训练，训练的是B数据集；
第二轮结束后，调用同样预测模型，同样的预测数据给出预测结果 却只有3或4，也就是不再识别1,2了；






------------------ 原始邮件 ------------------
发件人: "zhang wenhui"<notifications@github.com>;
发送时间: 2019年6月27日(星期四) 中午1:09
收件人: "PaddlePaddle/Paddle"<Paddle@noreply.github.com>;
抄送: "Kevin Bu"<707503331@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [PaddlePaddle/Paddle] 增量训练，前一次训练能力丢失的问题。 (#18359)




训练能力丢失是什么意思？

**Comment by frankwhzhang** [comment]
我没太明白问题 第二次训练b数据集 不是会更新第一次训练的结果吗 所以模型参数倾向于学习3和4 是不是正常现象

**Comment by 707503331** [comment]
我期望的增量训练结果是这样的：
假设我要训练一个能识别各种动物的模型，但我没办法呢一次收集全所有的动图图片，因此我计划分批次训练；
假设第一天训练猫这种动物，第二天训练狗这种动物，第三天训练大象这种动物。。。。
后一天的训练总不能覆盖第一天的训练结果吧？




------------------ 原始邮件 ------------------
发件人: "zhang wenhui"<notifications@github.com>;
发送时间: 2019年6月27日(星期四) 下午4:31
收件人: "PaddlePaddle/Paddle"<Paddle@noreply.github.com>;
抄送: "Kevin Bu"<707503331@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [PaddlePaddle/Paddle] 增量训练，前一次训练能力丢失的问题。 (#18359)




我没太明白问题 第二次训练b数据集 不是会更新第一次训练的结果吗 所以模型参数倾向于学习3和4 是不是正常现象

**Comment by frankwhzhang** [comment]
可以多训练几轮结果 或者把已有的数据shuffle

**Comment by 707503331** [comment]
我现在的增量 训练方法 对吗？
第一次训练A数据集(label范围 1~10)，第二次训练B数据集（label 范围11~20），两次数据集没有 交集。
能这样训练吗？


paddle paddle 说的增量训练 是什么概念？
我理解的有2中情况：
1、总分类数量（class_dim）不变前提下，增加这些固定分类下的图片数量
2、 新增分类数量(包括图片了)



paddle支持的是是哪一个呀？还是说有其他的理解


我现在理解的是 第1种，验证是不行的。



------------------ 原始邮件 ------------------
发件人: "zhang wenhui"<notifications@github.com>;
发送时间: 2019年6月28日(星期五) 下午4:10
收件人: "PaddlePaddle/Paddle"<Paddle@noreply.github.com>;
抄送: "Kevin Bu"<707503331@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [PaddlePaddle/Paddle] 增量训练，前一次训练能力丢失的问题。 (#18359)




可以多训练几轮结果 或者把已有的数据shuffle
