### ISSUE TITLE
分布式训练时出现Segmentation fault

### ISSUE THREAD

**Issue by lexy0093** [PaddlePaddle/Paddle#18360]
- 版本、环境信息：
    1）PaddlePaddle版本：fluid 1.3.0
- 训练信息
    1）多机
 日志如下：
![image](https://user-images.githubusercontent.com/10195109/60230674-4a113180-98c9-11e9-81e2-de9ba826af4e.png)

**Comment by frankwhzhang** [comment]
请添加一下链接 和详细的问题描述

**Comment by lexy0093** [comment]
paddle cloud jobid:    job-0bb5d136203a9961
日志链接：http://10.73.173.44:8910/fileview.html?type=logsdir&path=/&instance=0.app-user-20190626201719-8090--mcdnn-fluid-test_paddlecloud

**Comment by frankwhzhang** [comment]
本地可以先试一下Mpi任务 方便确认问题
