### ISSUE TITLE
训练是报错 Expected lbl < class_num, but received lbl:389 

### ISSUE THREAD

**Issue by 707503331** [PaddlePaddle/Paddle#18373]
训练的时候报错：
Traceback (most recent call last):
  File "pretrain_model.py", line 147, in <module>
    fetch_list=[avg_cost, acc])
  File "/usr/local/lib/python2.7/dist-packages/paddle/fluid/executor.py", line 472, in run
    self.executor.run(program.desc, scope, 0, True, True)
paddle.fluid.core.EnforceNotMet: Enforce failed. Expected lbl < class_num, but received lbl:389 >= class_num:102.

**Comment by 707503331** [comment]
程序文件如下：

[pretrain_model (copy).txt](https://github.com/PaddlePaddle/Paddle/files/3334092/pretrain_model.copy.txt)

train_list.txt中的一条样本数据：
shunzhitongbao/058ecca8e6374d139f085af27dbf3f97.jpg	389

**Comment by frankwhzhang** [comment]
检查一下label数据异常

**Comment by 707503331** [comment]
W0628 00:44:16.049546   467 device_context.cc:261] Please NOTE: device: 0, CUDA Capability: 70, Driver API Version: 9.2, Runtime API Version: 9.0
W0628 00:44:16.053030   467 device_context.cc:269] device: 0, cuDNN Version: 7.0.
Traceback (most recent call last):
  File "train.py", line 133, in <module>
    fetch_list=[avg_cost, acc])
  File "/opt/conda/lib/python3.6/site-packages/paddle/fluid/executor.py", line 565, in run
    use_program_cache=use_program_cache)
  File "/opt/conda/lib/python3.6/site-packages/paddle/fluid/executor.py", line 642, in _run
    exe.run(program.desc, scope, 0, True, True, fetch_var_name)
paddle.fluid.core.EnforceNotMet: Invoke operator adam error.
Python Callstacks: 
  File "/opt/conda/lib/python3.6/site-packages/paddle/fluid/framework.py", line 1654, in append_op
    attrs=kwargs.get("attrs", None))
  File "/opt/conda/lib/python3.6/site-packages/paddle/fluid/optimizer.py", line 1197, in _append_optimize_op
    stop_gradient=True)
  File "/opt/conda/lib/python3.6/site-packages/paddle/fluid/optimizer.py", line 296, in _create_optimization_pass
    param_and_grad)
  File "/opt/conda/lib/python3.6/site-packages/paddle/fluid/optimizer.py", line 441, in apply_gradients
    optimize_ops = self._create_optimization_pass(params_grads)
  File "/opt/conda/lib/python3.6/site-packages/paddle/fluid/optimizer.py", line 469, in apply_optimize
    optimize_ops = self.apply_gradients(params_grads)
  File "/opt/conda/lib/python3.6/site-packages/paddle/fluid/optimizer.py", line 500, in minimize
    loss, startup_program=startup_program, params_grads=params_grads)
  File "train.py", line 103, in <module>
    opts = optimizer.minimize(avg_cost)
C++ Callstacks: 
Enforce failed. Expected param_dims == ctx->GetInputDim("Moment1"), but received param_dims:100 != ctx->GetInputDim("Moment1"):4000.
Param and Moment1 input of AdamOp should have same dimension at [/paddle/paddle/fluid/operators/optimizers/adam_op.cc:67]
PaddlePaddle Call Stacks: 
0       0x7fc003ca5228p void paddle::platform::EnforceNotMet::Init<std::string>(std::string, char const*, int) + 360
1       0x7fc003ca5577p paddle::platform::EnforceNotMet::EnforceNotMet(std::string const&, char const*, int) + 87
2       0x7fc004ed4f9bp paddle::operators::AdamOp::InferShape(paddle::framework::InferShapeContext*) const + 5307
3       0x7fc005934328p paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&, paddle::framework::RuntimeContext*) const + 584
4       0x7fc005934ae4p paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&) const + 292
5       0x7fc00593240cp paddle::framework::OperatorBase::Run(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&) + 332
6       0x7fc003e173fep paddle::framework::Executor::RunPreparedContext(paddle::framework::ExecutorPrepareContext*, paddle::framework::Scope*, bool, bool, bool) + 382
7       0x7fc003e1823fp paddle::framework::Executor::Run(paddle::framework::ProgramDesc const&, paddle::framework::Scope*, int, bool, bool, std::vector<std::string, std::allocator<std::string> > const&, bool) + 143
8       0x7fc003c948dep
9       0x7fc003cd77cep
10      0x55acb5a90744p _PyCFunction_FastCallDict + 340
11      0x55acb5b1757ep
12      0x55acb5b3c38ap _PyEval_EvalFrameDefault + 778
13      0x55acb5b108e4p
14      0x55acb5b11771p
15      0x55acb5b17505p
16      0x55acb5b3d147p _PyEval_EvalFrameDefault + 4295
17      0x55acb5b108e4p
18      0x55acb5b11771p
19      0x55acb5b17505p
20      0x55acb5b3d147p _PyEval_EvalFrameDefault + 4295
21      0x55acb5b12289p PyEval_EvalCodeEx + 809
22      0x55acb5b1301cp PyEval_EvalCode + 28
23      0x55acb5b953c4p
24      0x55acb5b957c1p PyRun_FileExFlags + 161
25      0x55acb5b959c3p PyRun_SimpleFileExFlags + 451
26      0x55acb5b994b3p Py_Main + 1555
27      0x55acb5a6202ep main + 238
28      0x7fc063c33830p __libc_start_main + 240
29      0x55acb5b42e0ep

**Comment by 707503331** [comment]
label必须是数字吗？ 没看出labe有l异常呀，就是int数字

**Comment by adaxi123** [comment]
@707503331 label必须是int数字，你的class_dim一定要大于你的label数

**Comment by 707503331** [comment]
好的，谢谢了
