### ISSUE TITLE
怎么使用GPU训练PaddlePaddle模型

### ISSUE THREAD

**Issue by heiyexingchen** [PaddlePaddle/Paddle#1838]
1、我按照文档上的方法，将驱动和设备都映射到了容器中，代码只将use_gpu改为true，但是会报错：
Check failed: error == cudaSuccess (30 vs. 0)，cuda版本不合适。我的cuda版本是8.0的，应该怎么修改才会合适呢？
2、第一个方法没有通过，我在网上又看到了nvidia-docker的方法，但是安装后，nvidia-docker服务总是开启失败，查看了一下原因，是因为nvidia-docker-plugin启动失败，这又是什么原因

谢谢~~！

**Comment by helinwang** [comment]
看来您没有使用nvidia-docker，请参考这个教程：http://www.paddlepaddle.org/develop/doc/getstarted/build_and_install/docker_install_en.html

**Comment by heiyexingchen** [comment]
@helinwang 你好，老师。我就是按照这个教程一步一步来得，但是nvidia-docker-plugin启动失败，就没法使用nvidia-docker

**Comment by Yancey1989** [comment]
Hi, @heiyexingchen 可以把`nvidia-docker-plugin`启动失败的完整的报错信息贴一下么？

**Comment by heiyexingchen** [comment]
@Yancey1989 
nvidia-docker.service - NVIDIA Docker plugin
   Loaded: loaded (/usr/lib/systemd/system/nvidia-docker.service; disabled; vendor preset: disabled)
   Active: failed (Result: start-limit) since Fri 2017-04-21 01:24:39 PDT; 9s ago
     Docs: https://github.com/NVIDIA/nvidia-docker/wiki
  Process: 11237 ExecStopPost=/bin/rm -f $SPEC_FILE (code=exited, status=0/SUCCESS)
  Process: 11233 ExecStartPost=/bin/sh -c /bin/echo unix://$SOCK_DIR/nvidia-docker.sock > $SPEC_FILE (code=exited, status=0/SUCCESS)
  Process: 11228 ExecStartPost=/bin/sh -c /bin/mkdir -p $( dirname $SPEC_FILE ) (code=exited, status=0/SUCCESS)
  Process: 11227 ExecStart=/usr/bin/nvidia-docker-plugin -s $SOCK_DIR (code=exited, status=1/FAILURE)
 Main PID: 11227 (code=exited, status=1/FAILURE)

Apr 21 01:24:38 localhost.localdomain systemd[1]: Failed to start NVIDIA Docker plugin.
Apr 21 01:24:38 localhost.localdomain systemd[1]: Unit nvidia-docker.service entere....
Apr 21 01:24:38 localhost.localdomain systemd[1]: nvidia-docker.service failed.
Apr 21 01:24:39 localhost.localdomain systemd[1]: nvidia-docker.service holdoff tim....
Apr 21 01:24:39 localhost.localdomain systemd[1]: start request repeated too quickl...e
Apr 21 01:24:39 localhost.localdomain systemd[1]: Failed to start NVIDIA Docker plugin.
Apr 21 01:24:39 localhost.localdomain systemd[1]: Unit nvidia-docker.service entere....
Apr 21 01:24:39 localhost.localdomain systemd[1]: nvidia-docker.service failed.
Hint: Some lines were ellipsized, use -l to show in full.

**Comment by heiyexingchen** [comment]
@helinwang 下面的错误是我按照PaddlePaddle文档教程里，将驱动还有设备映射到容器中报的错误
42 hl_cuda_device.cc:642] Check failed: cudaSuccess == cudaStat (0 vs. 35) Cuda 
Error: CUDA driver version is insufficient for CUDA runtime version
*** Check failure stack trace: ***
    @     0x7fcf7f754daa  (unknown)
    @     0x7fcf7f754daa  (unknown)
    @     0x7fcf7f754ce4  (unknown)
    @     0x7fcf7f7546e6  (unknown)
    @     0x7fcf7f754ce4  (unknown)
    @     0x7fcf7f757687  (unknown)
    @     0x7fcf7f7546e6  (unknown)
    @     0x7fcf7f757687  (unknown)
    @           0x89466b  hl_stream_synchronize()
    @           0x89466b  hl_stream_synchronize()
    @           0x89466b  hl_stream_synchronize()
    @           0x89466b  hl_stream_synchronize()
    @           0x81e68e  paddle::Argument::resizeAndCopyFrom()
    @           0x81e68e  paddle::Argument::resizeAndCopyFrom()
    @           0x81e68e  paddle::Argument::resizeAndCopyFrom()
    @           0x81e68e  paddle::Argument::resizeAndCopyFrom()
    @           0x566272  paddle::TrainerThread::copyInArgs()
    @           0x566272  paddle::TrainerThread::copyInArgs()
    @           0x566272  paddle::TrainerThread::copyInArgs()
    @           0x56661d  paddle::TrainerThread::forward()
    @           0x56661d  paddle::TrainerThread::forward()
    @           0x56661d  paddle::TrainerThread::forward()
    @           0x5688f5  paddle::TrainerThread::computeThread()
    @     0x7fcf7f2d1a60  (unknown)
    @     0x7fcf80567184  start_thread
    @     0x7fcf7ea3937d  (unknown)
    @              (nil)  (unknown)
/usr/local/bin/paddle: line 109:    41 Aborted                 ${DEBUGGER} 

$MYDIR/../opt/paddle/bin/paddle_trainer ${@:2}

**Comment by Yancey1989** [comment]
According with this issue: https://github.com/NVIDIA/nvidia-docker/issues/116, what's your nvidia-docker version? try reinstall to the latest version?

**Comment by heiyexingchen** [comment]
@Yancey1989
nvidia-doxker-1.0.0.rc.3-1.x86_64.rpn

**Comment by helinwang** [comment]
@heiyexingchen 您提供的错误log跟这个issue的基本一致：https://github.com/NVIDIA/nvidia-docker/issues/135，请问能不能试试其里面提到的解决方法？

**Comment by hedaoyuan** [comment]
Closed this issue,  due to there is no feedback for a long time.

**Comment by yufengwhy** [comment]
请问怎么只使用一块gpu？
我在train函数里面paddle.init(use_gpu=1, trainer_count=1, gpu_id=2)，但是还是使用的全部8块gpu，我想只用其中一块gpu

**Comment by hedaoyuan** [comment]
设置环境变量 CUDA_VISIBLE_DEVICES=0
https://github.com/PaddlePaddle/Paddle/issues/6725

**Comment by yufengwhy** [comment]
好的，多谢。
但是这个[教程](http://doc.paddlepaddle.org/develop/doc_cn/howto/usage/cmd_parameter/use_case_cn.html)有点误导人。谷歌搜索paddle gpu id就会定位到这个教程，然后就一直尝试设置gpu_id，device变量，但是没有用，希望可以更新一下教程，谢谢。
