### ISSUE TITLE
训练attention模型报错Input(Out@GRAD) should not be null

### ISSUE THREAD

**Issue by saberSabersaber** [PaddlePaddle/Paddle#18395]
代码
![code](https://user-images.githubusercontent.com/26018086/60313661-8d83a280-9992-11e9-89ea-bc2b1b2bd2f3.png)
错误
![图片](https://user-images.githubusercontent.com/26018086/60313685-ac823480-9992-11e9-85b2-47e7a7676d13.png)

**Comment by xiangyubo** [comment]
这个是 attention-ocr 的模型吗？看着像是预测的部分...

**Comment by wangguibao** [comment]
已经让用户先排查组网逻辑，如果搞不定，可以添加完整代码，我们这边帮复现

**Comment by wangguibao** [comment]
暂时先关闭，如有需要可以再打开issue
