### ISSUE TITLE
迁移学习，第二次训练会覆第一次训练的结果

### ISSUE THREAD

**Issue by 707503331** [PaddlePaddle/Paddle#18396]
迁移学习，第二次训练结束后，第一次训练时能正确预测的标签 全部 变成了第二轮预测的标签值。
训练逻辑：
1、执行pretrain_model.py。 先导入 百度官方的 ResNet50 模型，使用数据集A，训练10轮，通过save_params()方法保存参数模型；
2、执行train.py。 使用数据集A，通过 load_params() 导入上面保存的参数模型，再执行100轮训练，通过save_inference_model()保存最后的预测模型；

3、重复第1步的操作，区别是使用数据集B；
4、重复第2步的操作，区别是使用数据集B， load_params() 导入的是第3步保存的参数模型；

5、执行预测。使用的预测模型是第4步生成的。 预测结果不对，只能预测数据集B中的数据。

脚本如下：
[pretrain_model (copy).txt](https://github.com/PaddlePaddle/Paddle/files/3337488/pretrain_model.copy.txt)
[train (copy).txt](https://github.com/PaddlePaddle/Paddle/files/3337489/train.copy.txt)

**Comment by wangguibao** [comment]
可以请用户先确认一下原始网络的效果是否ok，如果原始网络没问题，只是迁移过程中出问题，可以请用户在相关圈子里再请教一下
