### ISSUE TITLE
how to run MKLDNN multi-instance 

### ISSUE THREAD

**Issue by luotao1** [PaddlePaddle/Paddle#18406]
Now we use `AnalysisPredictor::SetMkldnnThreadID()` to run MKLDNN multi-instance in unit-tests:
https://github.com/PaddlePaddle/Paddle/blob/de42fe8fd584cca4a804e6e6f178f14b169d33c3/paddle/fluid/inference/tests/api/tester_helper.h#L415-L425
However, this interface is not in `paddle_analysis_config.h`, how do users run MKLDNN multi-instance?
If we expose to users? What's the interface? How about `config.EnableMKLDNN(int mkldnn_thread_id)`?

**Comment by ghost** [comment]
@luotao1 As discussed on the call, SetMkldnnThreadID() is needed only in special case (e.g. use various thread for each iteration). For normal case (e.g. parallel instances of Paddle predictor handling data indepenantly), there is no need to call it. Internally std::thread_id will be used for MKLDNN cache index (as part of key).

To be brief, no public interface need be added for MKLDNN multi-instance mentioned above.

**Comment by luotao1** [comment]
> To be brief, no public interface need be added for MKLDNN multi-instance mentioned above.

Got it. I will remove `AnalysisPredictor::SetMkldnnThreadID()` for clean.
