### ISSUE TITLE
matplot最新版本 3.1.0不支持3.5了

### ISSUE THREAD

**Issue by DDDivano** [PaddlePaddle/Paddle#18400]
win上安装报错。。。
![image](https://user-images.githubusercontent.com/10734244/60327168-c9802d00-99bd-11e9-93fb-c69effdbca72.png)

![image](https://user-images.githubusercontent.com/10734244/60327131-b3726c80-99bd-11e9-8409-000d0e9133fb.png)

**Comment by junjun315** [comment]
requirement里已经增加了关于python3.5对应matplot版本的限定，唯一可能的问题是本地setuptools版本过低导致安装时无法正确识别条件判断。

复现问题发现执行pip install -r 能执行requirement安装，但是在setup_tools 里没有走正确的分支。 继续跟进
