### ISSUE TITLE
mask-rcnn模型conv_affine_channel_fuse_pass有diff，关闭后显存double

### ISSUE THREAD

**Issue by pennypm** [PaddlePaddle/Paddle#18405]
- 版本、环境信息：
    1）PaddlePaddle版本：1.4.1
    2）GPU：CUDA8.0 CUDNN7
    3）系统环境：centOS6.3，Python: 2.7.14
- 模型: maskrcnn 
mask-rcnn模型conv_affine_channel_fuse_pass有diff，关闭后显存double
cnnpredict结果，关闭后正确
![image](https://user-images.githubusercontent.com/34053581/60330646-77dba080-99c5-11e9-81c7-e9a97aa686d8.png)
加上后预测结果错误
![image](https://user-images.githubusercontent.com/34053581/60330759-c12bf000-99c5-11e9-86d0-59f8bdddc8dc.png)

**Comment by Shixiaowei02** [comment]
麻烦贴一下代码

**Comment by pennypm** [comment]
![image](https://user-images.githubusercontent.com/34053581/60331024-5af39d00-99c6-11e9-9163-3f22a320d02c.png)

![image](https://user-images.githubusercontent.com/34053581/60331042-65ae3200-99c6-11e9-85c6-e30658020fc9.png)

**Comment by Shixiaowei02** [comment]
+@NHZlX

**Comment by NHZlX** [comment]
本地复现问题，解决中

**Comment by NHZlX** [comment]
https://github.com/PaddlePaddle/Paddle/pull/18532
