### ISSUE TITLE
通过 CUDAPlace(index) 设置使用的显卡存在bug

### ISSUE THREAD

**Issue by wulipc** [PaddlePaddle/Paddle#18424]
-问题描述： CUDAPlace(index)指定显卡的时候， 判断显存大小的时候， 似乎判断的还是GPU0的显存大小；

-运行报错：
`
Excepted allocating <= available, ...
`

-环境：
    1）PaddlePaddle版本： Fluid 1.3.1
    2）py2, GPU P40, centos

- 复现信息（以使用GPU1为例）：
 1）首先保持GPU0 处于占用状态；
 2）在代码中设置 place 为 CUDAPlace(1)， 且不要设置FLAGS_fraction_of_gpu_memory_to_use;
3）运行代码， 如果不出意外将会报错 ‘Excepted allocating <= available’， 且 available的显存和GPU0的状态比较相似。

 以下方式运行没错：
```
环境变量设一下：export CUDA_VISIBLE_DEVICE=1
然后代码里改成CUDAPlace(0)
```

Contact： HI  wpf_xdu

**Comment by Xreki** [comment]
您的用法是：环境变量设置成`export CUDA_VISIBLE_DEVICE=1`，代码里使用`CUDAPlace(1)`吗？

如果您使用1.5版本，则会报如下错误：
```
+ export CUDA_VISIBLE_DEVICES=1
+ python test.py
Traceback (most recent call last):
  File "test.py", line 67, in <module>
    place = fluid.CUDAPlace(1)
paddle.fluid.core_avx.EnforceNotMet: Invalid CUDAPlace(1), must inside [0, 1) at [/paddle/paddle/fluid/pybind/pybind.cc:792]
PaddlePaddle Call Stacks: 
0       0x7f883268c460p void paddle::platform::EnforceNotMet::Init<char const*>(char const*, char const*, int) + 352
1       0x7f883268c7d9p paddle::platform::EnforceNotMet::EnforceNotMet(std::__exception_ptr::exception_ptr, char const*, int) + 137
2       0x7f883266c157p
3       0x7f88326bf396p
4             0x4eef5ep
5             0x4eeb66p
6             0x4aaafbp
7             0x4c166dp PyEval_EvalFrameEx + 22413
8             0x4b9b66p PyEval_EvalCodeEx + 774
9             0x4eb69fp
10            0x4e58f2p PyRun_FileExFlags + 130
11            0x4e41a6p PyRun_SimpleFileExFlags + 390
12            0x4938cep Py_Main + 1358
13      0x7f88b0212830p __libc_start_main + 240
14            0x493299p _start + 41
```

意思是，如果您`CUDA_VISIBLE_DEVICE`只设置了一个GPU，那么只能使用`CUDAPlace(0)`。

**Comment by wulipc** [comment]
> 您的用法是：环境变量设置成`export CUDA_VISIBLE_DEVICE=1`，代码里使用`CUDAPlace(1)`吗？

不是， 使用的时候没有`export CUDA_VISIBLE_DEVICE=1`， 直接通过 `CUDAPlace(1)` 指定1号GPU； 另外你说的这个代码里面应该是CUDAPlace(0)才对。

**Comment by Xreki** [comment]
> 使用的时候没有export CUDA_VISIBLE_DEVICE=1， 直接通过 CUDAPlace(1) 指定1号GPU

明白了，没有指定`CUDA_VISIBLE_DEVICE`，那默认是使用全部GPU，会在所有GPU上预分配显存。

**Comment by wulipc** [comment]
结论： 即使使用CUDAPlace(index)来指定要使用的GPU， 也要在通过CUDA_VISIBLE_DEVICE变量指定机器上空闲的GPU环境变量。 Thanks to Xreki.
