### ISSUE TITLE
attention ocr 对历史attention weigths 求和训练出错

### ISSUE THREAD

**Issue by saberSabersaber** [PaddlePaddle/Paddle#18432]
error
![图片](https://user-images.githubusercontent.com/26018086/60417039-f9c00980-9c11-11e9-994d-c03f21a1a2d3.png)
![图片](https://user-images.githubusercontent.com/26018086/60417090-152b1480-9c12-11e9-8f1e-4db801a0a0a0.png)

训练代码
![图片](https://user-images.githubusercontent.com/26018086/60417164-4acffd80-9c12-11e9-9c86-3156aa42f7ee.png)
![图片](https://user-images.githubusercontent.com/26018086/60417192-63401800-9c12-11e9-83eb-e77b5f69cfad.png)

**Comment by wanghaoshuang** [comment]
在使用his_attr_weight之前，加一句：

`his_attr_weight.stop_gradient=True`

试试？

**Comment by wanghaoshuang** [comment]
https://github.com/PaddlePaddle/Paddle/issues/9989

**Comment by wanghaoshuang** [comment]
相关 issue: https://github.com/PaddlePaddle/Paddle/issues/14735

**Comment by saberSabersaber** [comment]
加了his_att_weight.stop_gradient=True 这句话还是一样的错误

**Comment by shippingwang** [comment]
循环里加入 已解决
