### ISSUE TITLE
How to start Paddle distributed train

### ISSUE THREAD

**Issue by helinwang** [PaddlePaddle/Paddle#1843]
启动dist train是要用命令行（train.py是其参数）启动，还是通过python paddle.dist.train直接启动，运行python train.py就可？
后者可以支持jupiter notebook。

**Comment by gongweibao** [comment]
>通过python paddle.dist.train直接启动
演示应该演示jupyternotebook直接启动的版本

**Comment by Yancey1989** [comment]
@helinwang `python paddle.dist.train ` 意思是说将提交任务的代码和trainer的代码写在一起么？感觉会有些麻烦，因为每个pod在也会执行`python train.py`，那这样代码就要兼容本地和集群，可能会长这样子：
```python
if DIST_TRAIN:
    paddle_cloud = paddle.cloud.init(configuration_file="./paddle_config.yaml")
    paddle_cloud.dist.train(use-gpu=True, gpu-num=4, )
else:
    // run local train
    run() 
```

或者Jupyter notebook只做本地训练的测试用，因为Paddle Server是一个RESTful HTTP Server，所以提供一个客户端的python package，这样不管是在网站提交还是本地提交都可以很方便的支持了？
Jupyter notebook 可以只运行本地的训练，通过网站上的一个按钮来提交Jupyter notebook中编辑好的代码到集群进行训练？

**Comment by helinwang** [comment]
I think this is done, since the related design doc is already merged: https://github.com/PaddlePaddle/Paddle/blob/develop/doc/design/cluster_train/submit-job.md
