### ISSUE TITLE
Git Repo issue

### ISSUE THREAD

**Issue by 18628271760** [PaddlePaddle/Paddle#18443]
double paddle 开发团队，
贵方的Git Repo可能存在异常，请查证处理。
<img width="484" alt="issue1" src="https://user-images.githubusercontent.com/38900261/60478744-1e6dbd00-9cb6-11e9-8c18-1e094d945e89.png">
<img width="312" alt="issue2" src="https://user-images.githubusercontent.com/38900261/60478778-39d8c800-9cb6-11e9-9d5f-7bdea6c26345.png">

**Comment by heavengate** [comment]
您好，该问题为您git本地配置问题，请参考 https://www.jianshu.com/p/1f800b8e15ac

**Comment by 18628271760** [comment]
我望使用paddle-models的预训练模型去做object detection但是在clone的时候一直克隆不成功，下载zip包也一直失败，请问该怎么办

**Comment by heavengate** [comment]
git config --global http.postBuffer 524288000之后再git clone

**Comment by 18628271760** [comment]
<img width="463" alt="issue3" src="https://user-images.githubusercontent.com/38900261/60482768-74962c80-9cc5-11e9-816e-19bb192706eb.png">

**Comment by heavengate** [comment]
应该是网速太慢的问题，再跑一下
git config --global http.lowSpeedLimit 0
git config --global http.lowSpeedTime 999999
之后再clone

**Comment by 18628271760** [comment]
昨天就试了，家里单位都试了。隔壁tf不像这样，pyt也不这样。

**Comment by heavengate** [comment]
尝试了三台机器未复现该问题，已联系paddle-mobile团队确认

**Comment by 18628271760** [comment]
FYI

**Comment by 18628271760** [comment]
I am so sorry to infor you that your method failded again! Maybe more experts should be involved!



<img width="480" alt="微信图片_20190702142743" src="https://user-images.githubusercontent.com/38900261/60488858-98616e80-9cd5-11e9-9fcc-ddfa624a1b19.png">

**Comment by heavengate** [comment]
麻烦确认一下您本地空间够不够呢

**Comment by 18628271760** [comment]
FYI
<img width="786" alt="all" src="https://user-images.githubusercontent.com/38900261/60499695-94404b80-9ceb-11e9-993e-b2188ed40cdd.png">
<img width="434" alt="C" src="https://user-images.githubusercontent.com/38900261/60499701-973b3c00-9ceb-11e9-8a9c-6bf6181f86ca.png">

**Comment by heavengate** [comment]
```
git clone --depth=1 https://github.com/PaddlePaddle/models
cd models
git fetch --unshallow
```
试下？

**Comment by 18628271760** [comment]
我方对此深表遗憾。
<img width="345" alt="issue" src="https://user-images.githubusercontent.com/38900261/60504717-b7232d80-9cf4-11e9-89b2-fe2dd2e1a14e.png">

**Comment by 18628271760** [comment]
Hi teams,
pls. help to check the pain point before.
![Down](https://user-images.githubusercontent.com/38900261/60513246-4d614e80-9d09-11e9-807d-7381a7a38f5d.png)
