### ISSUE TITLE
预测时 ZeroCopyRun 出core，看不到报错信息

### ISSUE THREAD

**Issue by hxjcarrie** [PaddlePaddle/Paddle#18445]
如题，预测时，调用ZeroCopyRun 出core，看不到内部报错信息。

`auto predictor =paddle::CreatePaddlePredictor<paddle::contrib::AnalysisConfig, paddle::PaddleEngineKind::kAnalysis>(config);`
`...`
`predictor->ZeroCopyRun();`

有什么办法可以看到报错信息

**Comment by heavengate** [comment]
跑之前命令行执行 export GLOG_v=10 试下
