### ISSUE TITLE
【单机cpu训练获取数据问题】请问大家有没有遇到这个问题，是什么原因导致的？怎么解决的？

### ISSUE THREAD

**Issue by heiyexingchen** [PaddlePaddle/Paddle#1844]
*** Aborted at 1492750736 (unix time) try "date -d @1492750736" if you are using GNU date ***
PC: @     0x7fc7aa77c2b2 (unknown)
*** SIGSEGV (@0x3fd) received by PID 192 (TID 0x7fc7a2637700) from PID 1021; stack trace: ***
    @     0x7fc7ab226330 (unknown)
    @     0x7fc7aa77c2b2 (unknown)
    @           0x56a7ba paddle::DenseScanner::fill()
    @           0x56f2ac paddle::PyDataProvider2::getNextBatchInternal()
    @           0x573ae6 paddle::DoubleBuffer::asyncLoadBatch()
    @     0x7fc7a9f88a60 (unknown)
    @     0x7fc7ab21e184 start_thread
    @     0x7fc7a96f037d (unknown)
    @                0x0 (unknown)
/usr/local/bin/paddle: line 109:   192 Segmentation fault      ${DEBUGGER} $MYDIR/../opt/paddle/bin/paddle_trainer ${@:2}

**Comment by reyoung** [comment]
这个问题是目前Paddle的一个bug，不过已经在开发分支修复了。。。新的release正在打包。。

不过这个bug不影响训练。

**Comment by heiyexingchen** [comment]
@reyoung 请问你说的这个开发分支去哪里找，需要源码编译吗？这种方式不会啊

**Comment by helinwang** [comment]
@heiyexingchen 源码编译请参考https://github.com/PaddlePaddle/Paddle/blob/develop/doc/getstarted/build_and_install/docker_install_cn.rst，具体的步骤我在这里写一下：

```
git clone https://github.com/PaddlePaddle/Paddle.git
cd Paddle
docker build -t paddle:dev .
docker run -v $(pwd):/paddle -e "WITH_GPU=OFF" -e "WITH_TEST=ON" paddle:dev
docker build -t paddle:prod -f build/Dockerfile .
```
至此paddle:prod就是编译完成的生产镜像。

要是对文档或者步骤有疑问请随时回复，我会回复以及更新文档，让文档理解起来更容易些。

**Comment by heiyexingchen** [comment]
@helinwang
谢谢老师，在您的帮助下我已经装好了。麻烦您给我推荐一份在docker中集群训练的教程呗，文档上的教程好像不大合适，如果能有实例代码就再好不过了

**Comment by typhoonzero** [comment]
@heiyexingchen you can find the docs under www.paddlepaddle.org

Closing this issue due to low activity, reopen if needed.
