### ISSUE TITLE
fluid.layers.load 不能正常使用

### ISSUE THREAD

**Issue by baihaojie2011** [PaddlePaddle/Paddle#18448]
为使您的问题得到快速解决，在建立Issues前，请您先通过如下方式搜索是否有相似问题:【搜索issue关键字】【使用labels筛选】【官方文档】

如果您没有查询到相似问题，为快速解决您的提问，建立issue时请提供如下细节信息：
- 标题：简洁、精准概括您的问题
- 版本、环境信息：
    1）PaddlePaddle版本：1.4
    2）CPU/GPU：无关
    3）系统环境：无关
    4）Python版本号：无关
    5）显存信息：无关
复现环境：https://aistudio.baidu.com/aistudio/projectDetail/79131

**Comment by heavengate** [comment]
https://github.com/PaddlePaddle/Paddle/blob/85b49d84732d2cf9ada5473b9f0c76dd0a7f1908/python/paddle/fluid/layers/io.py#L1289
确认为此处传参错误，应为`attrs=attrs`，待修复

**Comment by luotao1** [comment]
@heavengate @kagome112 没修复完的issue，先不要关闭，谢谢

**Comment by luotao1** [comment]
@lgone2000 该issue已经在#18447 中修复了。
