### ISSUE TITLE
paddle 1.5安装报找不到funcsigs错误

### ISSUE THREAD

**Issue by wzgwzg** [PaddlePaddle/Paddle#18446]
paddle版本1.5
whl包：paddlepaddle_gpu-1.5.0-cp27-cp27mu-linux_x86_64.whl
机器：厂内阡陌k40虚拟机

报错：ERROR: Could not find a version that satisfies the requirement funcsigs (from paddlepaddle-gpu==1.5.0.post97) (from versions: none)

但是通过pip list可以看到funcsigs已安装，并且uninstall 再重新 install也还是不行

**Comment by heavengate** [comment]
![屏幕快照 2019-07-02 下午1 33 22](https://user-images.githubusercontent.com/12605721/60484996-0144e880-9cce-11e9-93cf-a335a8231d9d.png)
应该是网速太慢，已经装上了
