### ISSUE TITLE
parallel_for failed: invalid resource handle

### ISSUE THREAD

**Issue by miraclebiu** [PaddlePaddle/Paddle#18450]
为使您的问题得到快速解决，在建立Issues前，请您先通过如下方式搜索是否有相似问题:【搜索issue关键字】【使用labels筛选】【官方文档】

如果您没有查询到相似问题，为快速解决您的提问，建立issue时请提供如下细节信息：
- 标题：简洁、精准概括您的问题
- 版本、环境信息：
    1）PaddlePaddle版本：1.4.1 post97
    2）CPU/GPU：GPU训练，CUDA9 cuDNN7
    3）系统环境：centos
    4）Python版本号 python2.7
    5）显存信息
- 复现信息：如为报错，请给出复现环境、复现步骤
在官方yolov3上进行的改进，
   
- 问题描述：请详细描述您的问题，同步贴出报错信息、日志/代码关键片段

F0702 14:33:05.855212 21212 exception_holder.h:34] std::exception caught, parallel_for failed: invalid resource handle
*** Check failure stack trace: ***
    @     0x7f090d5444ad  google::LogMessage::Fail()
    @     0x7f090d547f5c  google::LogMessage::SendToLog()
    @     0x7f090d543fd3  google::LogMessage::Flush()
    @     0x7f090d54946e  google::LogMessageFatal::~LogMessageFatal()
    @     0x7f090ee09e8c  paddle::framework::details::ExceptionHolder::Catch()
    @     0x7f090ee0ed03  _ZZN6paddle9framework7details24ThreadedSSAGraphExecutor5RunOpERKSt10shared_ptrINS0_13BlockingQueueIPNS1_13VarHandleBaseEEEEPNS1_12OpHandleBaseEENKUlvE_clEv
    @     0x7f090e181df3  std::_Function_handler<>::_M_invoke()
    @     0x7f090d4e3c97  std::__future_base::_State_base::_M_do_set()
    @       0x38daa0cbe0  (unknown)
    @     0x7f090ee0e342  _ZNSt13__future_base11_Task_stateISt5_BindIFZN6paddle9framework7details24ThreadedSSAGraphExecutor5RunOpERKSt10shared_ptrINS3_13BlockingQueueIPNS4_13VarHandleBaseEEEEPNS4_12OpHandleBaseEEUlvE_vEESaIiEFvvEE6_M_runEv
F0702 14:33:05.892972 21215 exception_holder.h:34] std::exception caught, parallel_for failed: invalid resource handle
*** Check failure stack trace: ***
    @     0x7f090d4e4fd4  _ZZN10ThreadPoolC1EmENKUlvE_clEv
    @     0x7f090d5444ad  google::LogMessage::Fail()
    @     0x7f094b5b8678  execute_native_thread_routine_compat
    @     0x7f090d547f5c  google::LogMessage::SendToLog()
    @       0x38daa07df3  (unknown)
    @       0x38da2f62cd  (unknown)
    @     0x7f090d543fd3  google::LogMessage::Flush()
    @              (nil)  (unknown)
Aborted

**Comment by heavengate** [comment]
为nccl未正确安装和配置，卡间没法通信，单卡可以跑，多卡不能跑，请参考http://www.paddlepaddle.org.cn/start 正确安装nccl
