### ISSUE TITLE
An C# API is badly needed now!

### ISSUE THREAD

**Issue by 18628271760** [PaddlePaddle/Paddle#18452]
Hi Devps:
An C# API is badly needed for integrating PaddlePaddle object-detect model with .NET framework. Pls. ref:
http://www.emgu.com/wiki/index.php/Emgu_TF

**Comment by heavengate** [comment]
您好，Paddle目前支持python和C++预测库API，您的C# API需求我们已知悉，并在内部统计和确认排期，感谢您对Paddle的支持~
