### ISSUE TITLE
预测模型的存储格式问题

### ISSUE THREAD

**Issue by 18628271760** [PaddlePaddle/Paddle#18457]
技术团队：
根据文档（http://www.paddlepaddle.org.cn/documentation/docs/zh/1.5/api_guides/low_level/inference.html#api-guide-inference）所叙：    参数保存到同一个文件，如设置 model_filename 为 None 、params_filename 为 __params__

实际训练保存后，如下：（“B_0”与“W_0”文件任然存在！）

<img width="532" alt="actuallyResult" src="https://user-images.githubusercontent.com/38900261/60498431-21ce6c00-9ce9-11e9-9ed7-14ab4868a8f7.png">

问题:
1. __modle__ ,__params__ , “B_0”与“W_0”文件保存的内容。

2. “B_0”与“W_0”文件是否是临时多余文件，load模型是否需要。为什么在“参数保存到同一个文件”模式下任存在，未合并到__params__？

3. “B_0”与“W_0”文件产生的个数与什么决定。

**Comment by heavengate** [comment]
1. model保存模型结构，params保存权重，如果指定了params_file是不会保存b_0,w_0这些，您上述保存的w_0, b_0这些文件是不是由于文件夹没有清空导致，并非此次保存的结果
2. 如果指定了params_file, w_0, b_0这些就不需要了，会直接读params
3. b_0, w_0 是网络各层的权重名称，比如说全连接fc层的y=wx+b里的w和b，网络每层都有自己的权重

**Comment by 18628271760** [comment]
经过排查，中间过程还有一个fluid.io.save_inference_model未更改。更改后删除folder在运行，如下：
<img width="559" alt="new" src="https://user-images.githubusercontent.com/38900261/60501685-fc446100-9cee-11e9-96bd-a2f51e88bd49.png">

请问结果是否合理成功，以便close issue。

**Comment by heavengate** [comment]
结果合理，您也可以再排查一下__params__的大小应该是等于原来所有w_0, b_0这些的大小总和

**Comment by 18628271760** [comment]
好的，谢谢帮助。
