### ISSUE TITLE
cudaStreamSynchronize an illegal memory access was encountered errno:77

### ISSUE THREAD

**Issue by miraclebiu** [PaddlePaddle/Paddle#18464]
为使您的问题得到快速解决，在建立Issues前，请您先通过如下方式搜索是否有相似问题:【搜索issue关键字】【使用labels筛选】【官方文档】

如果您没有查询到相似问题，为快速解决您的提问，建立issue时请提供如下细节信息：
- 标题：简洁、精准概括您的问题，例如“Insufficient Memory xxx" ”
- 版本、环境信息：
    1）PaddlePaddle版本：1.5.0 post87
    2）CPU：
    3）GPU：k40
    4）系统环境：centos
- 训练信息
    1）单机，多卡
    2）显存信息
    3）Operator信息
- 复现信息：如为报错，请给出复现环境、复现步骤
- 问题描述：请详细描述您的问题，同步贴出报错信息、日志、可复现的代码片段
cudaStreamSynchronize an illegal memory access was encountered errno:77
*** Check failure stack trace: ***
    @     0x7fd3393026ad  google::LogMessage::Fail()
    @     0x7fd33930615c  google::LogMessage::SendToLog()
    @     0x7fd3393021d3  google::LogMessage::Flush()
    @     0x7fd33930766e  google::LogMessageFatal::~LogMessageFatal()
    @     0x7fd33b2e001d  _ZNSt17_Function_handlerIFvvEZNK6paddle8platform17CUDADeviceContext4WaitEvEUlvE_E9_M_invokeERKSt9_Any_data
    @     0x7fd33b2edaa4  paddle::platform::TemporaryAllocator::Release()
    @     0x7fd33b2e2ff1  paddle::platform::CUDADeviceContext::Wait()
    @     0x7fd33b239ad1  paddle::framework::TransDataDevice()
    @     0x7fd33b238b6e  paddle::framework::TransformData()
    @     0x7fd33b22ffad  paddle::framework::OperatorWithKernel::PrepareData()
    @     0x7fd33b2310dd  paddle::framework::OperatorWithKernel::RunImpl()
    @     0x7fd33b231581  paddle::framework::OperatorWithKernel::RunImpl()
    @     0x7fd33b22eb7c  paddle::framework::OperatorBase::Run()
    @     0x7fd33b02be6a  paddle::framework::details::ComputationOpHandle::RunImpl()
    @     0x7fd33b01e810  paddle::framework::details::OpHandleBase::Run()
    @     0x7fd33afffb86  paddle::framework::details::FastThreadedSSAGraphExecutor::RunOpSync()
    @     0x7fd33affe7ef  paddle::framework::details::FastThreadedSSAGraphExecutor::RunOp()
    @     0x7fd33affebaf  _ZNSt17_Function_handlerIFvvESt17reference_wrapperISt12_Bind_simpleIFS1_ISt5_BindIFZN6paddle9framework7details28FastThreadedSSAGraphExecutor10RunOpAsyncEPSt13unordered_mapIPNS6_12OpHandleBaseESt6atomicIiESt4hashISA_ESt8equal_toISA_ESaISt4pairIKSA_SC_EEESA_RKSt10shared_ptrINS5_13BlockingQueueImEEEEUlvE_vEEEvEEEE9_M_invokeERKSt9_Any_data
    @     0x7fd3393ef2b3  std::_Function_handler<>::_M_invoke()
    @     0x7fd339285ef7  std::__future_base::_State_base::_M_do_set()
    @       0x38c040cbe0  (unknown)
    @     0x7fd33affa232  _ZNSt13__future_base11_Task_stateISt5_BindIFZN6paddle9framework7details28FastThreadedSSAGraphExecutor10RunOpAsyncEPSt13unordered_mapIPNS4_12OpHandleBaseESt6atomicIiESt4hashIS8_ESt8equal_toIS8_ESaISt4pairIKS8_SA_EEES8_RKSt10shared_ptrINS3_13BlockingQueueImEEEEUlvE_vEESaIiEFvvEE6_M_runEv
    @     0x7fd339287474  _ZZN10ThreadPoolC1EmENKUlvE_clEv
    @     0x7fd37483d678  execute_native_thread_routine_compat
    @       0x38c0407df3  (unknown)
    @       0x38bfcf62cd  (unknown)
    @              (nil)  (unknown)
^[[A^C
[1]+  Aborted                 nohup python train_gpl.py > exp1.out

**Comment by heavengate** [comment]
1. 请确认卡上有没其他任务抢占显存
2. 可开启以下lag
export FLAGS_fast_eager_deletion_mode=1
export FLAGS_eager_delete_tensor_gb=0.0
export FLAGS_fraction_of_gpu_memory_to_use=0.98

**Comment by miraclebiu** [comment]
没有作用，仍然出现

**Comment by 0YuanZhang0** [comment]
> 没有作用，仍然出现
我也遇到相同的问题，请问这个问题有解决方案了吗

**Comment by heavengate** [comment]
该问题我本地有复现，定位中

**Comment by heavengate** [comment]
初步确认是1.5使用cudnn7里新增接口的问题，可以尝试下使用1.4版本，或者在fluid.layers.conv2d中指定use_cudnn=False试下

**Comment by wzgwzg** [comment]
我也遇到同样问题了，paddle 1.5 post97
在v100上能正常跑通，在p40上不行

**Comment by chengduoZH** [comment]
@miraclebiu @wzgwzg  你本地使用cudnn版本是什么？

**Comment by shuluoshu** [comment]
我也本地遇到这个问题， cudnn用的是7.3  + cuda 9.0

**Comment by heavengate** [comment]
> 我也本地遇到这个问题， cudnn用的是7.3 + cuda 9.0

用的是paddle1.5 post97么，nvidia驱动什么版本，方便给一下nvidia-smi信息和日志信息么

**Comment by shuluoshu** [comment]
> > 我也本地遇到这个问题， cudnn用的是7.3 + cuda 9.0
> 
> 用的是paddle1.5 post97么，nvidia驱动什么版本，方便给一下nvidia-smi信息和日志信息么

1.5.0 post87 ，显卡驱动 NVIDIA-SMI 396.26                 Driver Version: 396.26   k40 
报错信息见图。

![3](https://user-images.githubusercontent.com/17999845/61260252-0155e580-a7b0-11e9-854f-a44136c335b8.png)

**Comment by heavengate** [comment]
> > > 我也本地遇到这个问题， cudnn用的是7.3 + cuda 9.0
> > 
> > 
> > 用的是paddle1.5 post97么，nvidia驱动什么版本，方便给一下nvidia-smi信息和日志信息么
> 
> 1.5.0 post87 ，显卡驱动 NVIDIA-SMI 396.26 Driver Version: 396.26 k40
> 报错信息见图。
> 
> ![3](https://user-images.githubusercontent.com/17999845/61260252-0155e580-a7b0-11e9-854f-a44136c335b8.png)

cudnn7和cuda8可能存在兼容问题，建议安装1.5.0.post97，更换cuda9.0版本试下

**Comment by shuluoshu** [comment]
> > > > 我也本地遇到这个问题， cudnn用的是7.3 + cuda 9.0
> > > 
> > > 
> > > 用的是paddle1.5 post97么，nvidia驱动什么版本，方便给一下nvidia-smi信息和日志信息么
> > 

> 
> cudnn7和cuda8可能存在兼容问题，建议安装1.5.0.post97，更换cuda9.0版本试下


我本来就是用的paddle1.5 post97 ， cuda 9.0， cudnn7， 还要换啥呢？

**Comment by heavengate** [comment]
> > > > > 我也本地遇到这个问题， cudnn用的是7.3 + cuda 9.0
> > > > 
> > > > 
> > > > 用的是paddle1.5 post97么，nvidia驱动什么版本，方便给一下nvidia-smi信息和日志信息么
> 
> > cudnn7和cuda8可能存在兼容问题，建议安装1.5.0.post97，更换cuda9.0版本试下
> 
> 我本来就是用的paddle1.5 post97 ， cuda 9.0， cudnn7， 还要换啥呢？

nccl版本是多少，可以试下2.4.7

**Comment by liushanshan07** [comment]
求问这个问题如何解决？我在集群P40上训练，也遇到了这个问题。

**Comment by chen5697** [comment]
请问有人解决了吗
cudaStreamSynchronize an illegal memory access was encountered errno:77

**Comment by Menevagol** [comment]
@heavengate 问一下这个问题最后解决了吗？

**Comment by ZHUI** [comment]
我也遇到这个问题，更新最新的develop版本后，发现是elementwise操作的广播有问题导致的，修改后结果正常。
