### ISSUE TITLE
fluid fleet基于dataset提交NCCL2的demo

### ISSUE THREAD

**Issue by sshilei** [PaddlePaddle/Paddle#18475]
有没有fluid1.5中fleet基于dataset提交NCCL2的demo程序。在wiki和官网没有找到。

**Comment by fc500110** [comment]
单机还是分布式？

**Comment by sshilei** [comment]
分布式，提交到孔明集群

**Comment by sandyhouse** [comment]
可以参考这个文档：http://wiki.baidu.com/pages/viewpage.action?pageId=717062476

**Comment by sshilei** [comment]
这个是基于pserver的吧，我要提交到孔明集群，需要NCCL2

**Comment by sandyhouse** [comment]
dataset主要面向CPU异步场景。对于使用nccl2的分布式训练，可以使用fleet+nccl2。
