### ISSUE TITLE
动态图unique_name计数增加

### ISSUE THREAD

**Issue by DDDivano** [PaddlePaddle/Paddle#18476]
模型：se-resnext 动态图。 https://github.com/PaddlePaddle/models/tree/develop/dygraph/se_resnext

在第一轮至第二轮训练时候，unique_name会增加1，之后不会增加了。这个情况可能引发内存泄露，需要排查一下原因。

![image](https://user-images.githubusercontent.com/10734244/60571265-d8902200-9da5-11e9-82a5-3982c1f84fd2.png)

**Comment by tink2123** [comment]
已定位问题，在eval模块使用了新的op，导致unique_name在通过eval之后增加1。

**Comment by DDDivano** [comment]
fixed in https://github.com/PaddlePaddle/models/pull/2699
