### ISSUE TITLE
Fluid如何保存优化方法的状态，之后重新训练的时候恢复它

### ISSUE THREAD

**Issue by yeyupiaoling** [PaddlePaddle/Paddle#18474]
# 环境
 - PaddlePaddle 1.5

# 问题
有时候训练可能会出现中断，重新训练之后，我希望他能够优化方法能够按照之前的训练的情况接着，而不是重新开始，有什么方法做到吗？
```python
bd = [4, 7, 9, 11]
lr = [0.1, 0.01, 0.001, 0.0001, 0.00001]
optimizer = fluid.optimizer.AdamOptimizer(
    learning_rate=fluid.layers.piecewise_decay(boundaries=bd, values=lr),
    epsilon=0.1)
optimizer.minimize(avg_cost)
```

**Comment by junjun315** [comment]
optimizer 一般是一个class，应该没有状态信息。如果有需要保存的中间变量，可以把这个var设置成persistable的方式来进行保存、加载和恢复。
也可以重载一下这个optimizer类，按照刚才说的设置一些需要保存的变量作为输入，来实现自己的优化过程。

**Comment by yeyupiaoling** [comment]
@junjun315 具体 应该如何做呢？

**Comment by junjun315** [comment]
参考这个模型里对于optimizer的处理，https://github.com/PaddlePaddle/models/blob/43cdafbb97e52e6d93cc5bbdc6e7486f27665fc8/PaddleCV/face_detection/train.py#L53 有保存和使用decay信息

**Comment by yeyupiaoling** [comment]
@junjun315 这里只介绍了模型的保存和加载预训练模型
https://github.com/PaddlePaddle/models/blob/43cdafbb97e52e6d93cc5bbdc6e7486f27665fc8/PaddleCV/face_detection/train.py#L181
https://github.com/PaddlePaddle/models/blob/43cdafbb97e52e6d93cc5bbdc6e7486f27665fc8/PaddleCV/face_detection/train.py#L158-L161

并没有介绍 optimizer 的保存和恢复

**Comment by junjun315** [comment]
`optimizer = fluid.optimizer.RMSProp(
            learning_rate=fluid.layers.piecewise_decay(boundaries, values),
            regularization=fluid.regularizer.L2Decay(0.0005),
        )`

类似这里，learning_rate是从参数里拿到的，在save时也会随着program保存。 optimizer class一般没有暂态信息，只是随着初始化参数不同来进行处理。所以可以通过保存参数，然后恢复参数，把参数传入构建optimizer class来进行恢复

**Comment by junjun315** [comment]
我理解你的诉求了。整个optimizer当前paddle框架中没有提供保存的方法，您可以使用如pickle一类的方式来保存这个对象。

**Comment by yeyupiaoling** [comment]
@junjun315 嗯嗯，如果自己手动保存，自己计算再恢复，有点麻烦。如果能像动态图那样保存模型就好了。
