### ISSUE TITLE
变长id导致程序内存占用过大

### ISSUE THREAD

**Issue by lexy0093** [PaddlePaddle/Paddle#18473]
总特征id：8w+，稀疏特征，使用embeding层，但是由于输入embeding为变长ids，需要padding到同一batch的最大长度，不知道如何优化成同一序列输入

**Comment by kuke** [comment]
可以考虑用lod tensor，就不用padding了

**Comment by lexy0093** [comment]
由于embeding后需要乘以权重，不知道lod-tensor这块怎么处理的

**Comment by sandyhouse** [comment]
可以将LoD-Tensor转为普通Tensor后计算，转换方法可以参考：http://www.paddlepaddle.org.cn/documentation/docs/zh/1.5/user_guides/howto/basic_concept/lod_tensor.html

**Comment by sandyhouse** [comment]
可以尝试下下面两种方案，看看是否可以解决内存超限的问题：1. 降低batch_size大小；2. 对index排序，减少padding的数量。
