### ISSUE TITLE
官网提供的Windows预测文档说明不全

### ISSUE THREAD

**Issue by jiangjiajun** [PaddlePaddle/Paddle#18489]
http://www.paddlepaddle.org.cn/documentation/docs/zh/1.5/advanced_usage/deploy/inference/windows_cpp_inference.html 

文档中提到『解压Paddle，Release，fluid_install_dir压缩包』，但在文档中并没找到相应压缩包的下载链接。
希望提供在Windows下各类环境（cuda8.0， 9.0）的paddle预测库

**Comment by junjun315** [comment]
感谢反馈，我们安排在后续版本发布window下预测库压缩包
