### ISSUE TITLE
PaddlePaddle训练图像一定要CHW和BGR顺序吗？

### ISSUE THREAD

**Issue by yeyupiaoling** [PaddlePaddle/Paddle#18487]
# 环境
 - PaddlePaddle 1.5

# 问题
PaddlePaddle训练图像一定要CHW和BGR顺序吗？
能其他的吗？
例如我用CV2读取的图像是WHC，还转换吗？

**Comment by junjun315** [comment]
主要是看对应的op里对于读入数据的处理方式。如果是WHC的格式的，在处理的时候可能不符合目标

**Comment by yeyupiaoling** [comment]
@junjun315 嗯嗯，明白，刚才验证过了。
