### ISSUE TITLE
fluid inference: CPU预测结果不稳定

### ISSUE THREAD

**Issue by dancingpipi** [PaddlePaddle/Paddle#18495]
使用fluid 1.4和1.5做inference时，发现使用CPU计算的时候，结果有些不稳定，误差在1e-3左右。
使用相同的数据执行CPU的inference，结果如下：
第一次运行：
![image](https://user-images.githubusercontent.com/20511825/60648401-6e917e80-9e72-11e9-9b69-671c6b6259fd.png)
第二次运行：
![image](https://user-images.githubusercontent.com/20511825/60648412-76e9b980-9e72-11e9-9c98-3a953ce1e84c.png)
第三次运行：
![image](https://user-images.githubusercontent.com/20511825/60648428-80732180-9e72-11e9-86d9-e6f4ecc750c4.png)

1.4和1.5都有这个问题，模型主要结构是lstm和fc。

**Comment by Superjomn** [comment]
模型配置补充下吧
