### ISSUE TITLE
训练多卡有问题，报错没有明显指向。

### ISSUE THREAD

**Issue by hectorgui** [PaddlePaddle/Paddle#18499]
1）PaddlePaddle版本：1.4
2）CPU：预测若用CPU，请提供CPU型号，MKL/OpenBlas/MKLDNN/等数学库使用情况
3）GPU：Tesla K40m CUDA Version 8.0.44 CUDNN 6.0.5
4）系统环境：CentOS release 6.3 (Final) Python 2.7.3
- 训练信息
    1）单机/4卡
    2）12g
    3）Operator信息

------------------------------------------------
memory_optimize is deprecated. Use CompiledProgram and Executor
W0704 16:43:32.566367 23971 device_context.cc:261] Please NOTE: device: 0, CUDA Capability: 35, Driver API Version: 8.0, Runtime API Version: 8.0
W0704 16:43:32.568605 23971 device_context.cc:269] device: 0, cuDNN Version: 6.0.
4
12
ParallelExecutor is deprecated. Please use CompiledProgram and Executor. CompiledProgram is a central place for optimization and Executor is the unified executor. Example can be found in compiler.py.
W0704 16:43:34.873883 23971 graph.h:204] WARN: After a series of passes, the current graph can be quite different from OriginProgram. So, please avoid using the `OriginProgram()` method!
*** Aborted at 1562229817 (unix time) try "date -d @1562229817" if you are using GNU date ***
PC: @                0x0 (unknown)
*** SIGSEGV (@0x0) received by PID 23971 (TID 0x7fc5983a8700) from PID 0; stack trace: ***
    @     0x7fc597bd4520 (unknown)
    @     0x7fc5971a179f __strncpy_sse2_unaligned
    @     0x7fc4f49f0e4a getCudaPath()
    @     0x7fc4f49f145d p2pCanConnect()
    @     0x7fc4f49db403 fillConnect()
    @     0x7fc4f49e085a ncclCommInitAll
    @     0x7fc54b759c20 paddle::platform::NCCLContextMap::NCCLContextMap()
    @     0x7fc54b755970 paddle::framework::ParallelExecutor::ParallelExecutor()
    @     0x7fc54b63f098 _ZZN8pybind1112cpp_function10initializeIZNS_6detail8initimpl11constructorIJRKSt6vectorIN5boost7variantIN6paddle8platform9CUDAPlaceENS9_8CPUPlaceENS9_15CUDAPinnedPlaceENS6_6detail7variant5void_ESF_SF_SF_SF_SF_SF_SF_SF_SF_SF_SF_SF_SF_SF_SF_SF_EESaISG_EERKS5_ISsSaISsEERKSsPNS8_9framework5ScopeERS5_IST_SaIST_EERKNSR_7details17ExecutionStrategyERKNSX_13BuildStrategyEPNSR_2ir5GraphEEE7executeINS_6class_INSR_16ParallelExecutorEJEEEJELi0EEEvRT_DpRKT0_EUlRNS2_16value_and_holderESK_SO_SQ_ST_SW_S10_S13_S16_E_vJS1J_SK_SO_SQ_ST_SW_S10_S13_S16_EJNS_4nameENS_9is_methodENS_7siblingENS2_24is_new_style_constructorEEEEvOT_PFT0_DpT1_EDpRKT2_ENUlRNS2_13function_callEE1_4_FUNES21_
    @     0x7fc54b5db18e pybind11::cpp_function::dispatcher()
    @     0x7fc597e280e3 PyObject_Call
    @     0x7fc597e3af6f instancemethod_call
    @     0x7fc597e280e3 PyObject_Call
    @     0x7fc597e7e7fe slot_tp_init
    @     0x7fc597e7d468 type_call
    @     0x7fc597e280e3 PyObject_Call
    @     0x7fc597ec1877 PyEval_EvalFrameEx
    @     0x7fc597ec4120 PyEval_EvalCodeEx
    @     0x7fc597ec2491 PyEval_EvalFrameEx
    @     0x7fc597ec4120 PyEval_EvalCodeEx
    @     0x7fc597ec2491 PyEval_EvalFrameEx
    @     0x7fc597ec4120 PyEval_EvalCodeEx
    @     0x7fc597e5026d function_call
    @     0x7fc597e280e3 PyObject_Call
    @     0x7fc597e3af6f instancemethod_call
    @     0x7fc597e280e3 PyObject_Call
    @     0x7fc597e7e7fe slot_tp_init
    @     0x7fc597e7d468 type_call
    @     0x7fc597e280e3 PyObject_Call
    @     0x7fc597ec1877 PyEval_EvalFrameEx
    @     0x7fc597ec4120 PyEval_EvalCodeEx
    @     0x7fc597ec2491 PyEval_EvalFrameEx
Segmentation fault

**Comment by junjun315** [comment]
请贴一下最小复现代码。 另外，1.4版本我们提供了cuda8 cudn7以及cuda8 cudn5的包，您用的是哪一个包？

**Comment by imistyrain** [comment]
cudnn版本不对，用paddle show或者pip list看下用的是哪个版本，换成cudnn7吧

**Comment by kolinwei** [comment]
@hectorgui 你机器上多卡间的p2p开了吗？可以用cuda下的样例程序验证下 samples/0_Simple/simpleP2P

**Comment by LukeALee** [comment]
可以调小一点点batch_size试试
