### ISSUE TITLE
模型保存、lodtensor截断问题

### ISSUE THREAD

**Issue by xuzhenglei1991** [PaddlePaddle/Paddle#18502]
当前的训练方法为 
网络模型：input_word->embedding->gru->fc->crf，
现在是128维的embedding，我想将一些其他特征（26维向量表示）接在embedding产出后面。
我是否需要将输入拆成两个part，第一个part给embedding，将第二个part接在embedding产出的lodtensor后面。这样有一个问题就是如何将lodtensor拆成两个part，如何将两个lodtensor接在一起，而且有一个是FP32类型的，另一个是INT64类型的。
示例程序是https://github.com/baidu/lac/blob/master/python/

**Comment by junjun315** [comment]
当前的embedding，包括后续的操作应该都不支持这样的。因为涉及不同数据类型的对象。有没有可能拆分成真正的两个variable？ 需要注意的是一个program里只支持一个embedding

**Comment by xuzhenglei1991** [comment]
> 当前的embedding，包括后续的操作应该都不支持这样的。因为涉及不同数据类型的对象。有没有可能拆分成真正的两个variable？ 需要注意的是一个program里只支持一个embedding

lodtenser赋值、添加数据 这些操作有没有说明文档呢

**Comment by junjun315** [comment]
http://www.paddlepaddle.org.cn/documentation/docs/zh/1.5/user_guides/howto/basic_concept/lod_tensor.html 查看这个

**Comment by xuzhenglei1991** [comment]
> http://www.paddlepaddle.org.cn/documentation/docs/zh/1.5/user_guides/howto/basic_concept/lod_tensor.html 查看这个

我看了这个 里面我看到了一些把lodtensor中数据的扩充，没有如何把lodtensor中数据维度扩展的操作诶？我现在的需求是需要把128维的embedding输出 和 另一个26维的数组拼接在一起，组成一个新的输出，也就是154维的向量
