### ISSUE TITLE
create_py_reader_by_data数据读取问题

### ISSUE THREAD

**Issue by MaxLingwei** [PaddlePaddle/Paddle#18519]
在slurm集群训练，采用单节点多卡的模式，读取数据的方式如图
![image](https://user-images.githubusercontent.com/14048056/60709304-aff15f00-9f42-11e9-89f2-44cc34ca1203.png)
报错
![image](https://user-images.githubusercontent.com/14048056/60709351-c8617980-9f42-11e9-91d9-0ca56d0037a8.png)

**Comment by liupluswei** [comment]
> 在slurm集群训练，采用单节点多卡的模式，读取数据的方式如图
> ![image](https://user-images.githubusercontent.com/14048056/60709304-aff15f00-9f42-11e9-89f2-44cc34ca1203.png)
> 报错
> ![image](https://user-images.githubusercontent.com/14048056/60709351-c8617980-9f42-11e9-91d9-0ca56d0037a8.png)

The places of matrices must be same
从最后一行log来看，是因为sequence_conv op的参数一部分在CPUPlace，一部分在CUDAPlace导致，您可以检查一下代码排查一下是否有相关错误

**Comment by sneaxiy** [comment]
已解决，不是py_reader的问题。问题原因是ParallelExexcutor必须在run startup之后创建，因为ParallelExexcutor创建时会从0卡往其他卡broadcast参数，所以若在run startup之前创建会导致其他卡上没有参数，从而运行出错。

**Comment by HaoLiuHust** [comment]
@sneaxiy 请问你是咋解决的，我也要有这个问题
