### ISSUE TITLE
cross_entropy报错

### ISSUE THREAD

**Issue by DDDivano** [PaddlePaddle/Paddle#18516]
paddle1.5.0
GAN模型，判别器返回的是下图所示的tensor
![image](https://user-images.githubusercontent.com/10734244/60699686-a1497e80-9f27-11e9-844f-3b96c12cc332.png)
网络结构没有FC，返回的就是一个[batchsize, 1, 1, 1]维度的tensor。我这里batchsize填的是2.经过reshape变成了[batchsize,1]。
`x = self.conv1(inputs)
x = fluid.layers.leaky_relu(x)
x = self.conv2(x)
x = self.BN1(x)
x = fluid.layers.leaky_relu(x)
x = self.conv3(x)
x = self.BN2(x)
x = fluid.layers.leaky_relu(x)
x = self.conv4(x)
x = self.BN3(x)
x = fluid.layers.leaky_relu(x)
x = self.conv5(x)
x = fluid.layers.sigmoid(x)
x = fluid.layers.reshape(x, shape=[-1, 1])
return x`
![image](https://user-images.githubusercontent.com/10734244/60700393-5b41ea00-9f2a-11e9-95da-1b797e55e1b8.png)

由于label全是1.所以这么定义的label
`real_label = np.ones(shape=[batch_size, 1]).astype("int64")
real_label = to_variable(real_label)
real_label.stop_gradient = True`
![image](https://user-images.githubusercontent.com/10734244/60699784-fbe2da80-9f27-11e9-8253-1fed72ec5114.png)
传入函数报错，
![image](https://user-images.githubusercontent.com/10734244/60699793-0604d900-9f28-11e9-9def-8a93dde24b6f.png)
请问如何修改？

**Comment by ceci3** [comment]
您好，在定义real_label的时候定义label的类型是float32试下~， real_label = np.ones(shape=[batch_size, 1]).astype("float32")

**Comment by DDDivano** [comment]
> 您好，在定义real_label的时候定义label的类型是float32试下~， real_label = np.ones(shape=[batch_size, 1]).astype("float32")
![image](https://user-images.githubusercontent.com/10734244/60700862-0010f700-9f2c-11e9-9b81-ac0f153a58ab.png)

**Comment by ceci3** [comment]
cross_entropy里有个属性soft_label还需要设为True ，然后定义label的类型为float32

**Comment by DDDivano** [comment]
> cross_entropy里有个属性soft_label还需要设为True ，然后定义label的类型为float32

多谢，现在不报错了，但是为什么mnist就可以设置整数，而我那么设置就不行呢？

**Comment by ceci3** [comment]
因为你的模型里判别器返回的是float类型的，所以label需要设为float类型的。mnist返回的应该是int类型的数字，所以对应的label也应该是整型~

**Comment by DDDivano** [comment]
> 因为你的模型里判别器返回的是float类型的，所以label需要设为float类型的。mnist返回的应该是int类型的数字，所以对应的label也应该是整型~

Mnist返回的是[batchsize,10]的数据，10中每一位对应每一个数的概率，也是float型的。

**Comment by ceci3** [comment]
那您那边有代码吗？我看下具体的使用然后回答您

**Comment by ceci3** [comment]
cross_entropy如果soft_label设置为False和设置为True，走的是不同的op，设置为False的话op里面会对label做一个one hot
