### ISSUE TITLE
[MKL-DNN] Refactor Acquire API of mkl-dnn integration

### ISSUE THREAD

**Issue by jczaja** [PaddlePaddle/Paddle#18531]
It would be good to refactor Acquire API of mkl-dnn:
- Handler should have forward_pd and backward_pd  not like it is now that all inheriting Handler Types are defining its own attributes. 
- Store PD of Fwd and BWD not to rely on PD given by argument of Acquire API
- All AcquireXXXPrimitiveDesc should be called internally by Handler ,as there is no need to have it exposed to op
- descriptors should only be created when they are used eg. when primitives/memory objects are to be created , not reused
- Move Key genereation inside Handler , not to keep it in a body of Compute method

This task should reduce some  redundancy in mkl-dnn acquire api

Issue added to track this task

**Comment by Sand3r-** [comment]
@jczaja is refactoring finished, and can the issue be closed now?

**Comment by jczaja** [comment]
No, It is work in progress

**Comment by jczaja** [comment]
done (several PRs)
