### ISSUE TITLE
使用ifelse结构报错

### ISSUE THREAD

**Issue by Yukizzz** [PaddlePaddle/Paddle#18545]
使用ifelse结构，true和false block里面网络结构相同，都是简单的3层fc+bn。
报错在下面的代码上
https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/fluid/operators/controlflow/conditional_block_op.cc#L234
去掉bn只留3层fc之后，报了如下新的错误。fc分别是256-128-64维，256是第一层fc的维度。
![image](https://user-images.githubusercontent.com/9652571/60788800-17501e80-a190-11e9-91e1-5125d8f1cf4a.png)

**Comment by sandyhouse** [comment]
看报错信息是参数和梯度的纬度信息不匹配导致的。排查下相关代码吧。
