### ISSUE TITLE
fluid在MPI集群上训练发现GRPC error，core dump后Pserver挂掉

### ISSUE THREAD

**Issue by qnikev** [PaddlePaddle/Paddle#18543]
fluid 1.3版本
本地能够运行，没问题

集群报错如下：
:F0707 22:12:46.674666 27072 grpc_client.cc:418] SendRPC name:[video_fid_his_embedding@GRAD.block9.trainer_3], ep:[10.76.84.50:62001], status:[-1] meets grpc error, error_code:14 error_message:OS Error error_details:
Sun Jul  7 22:12:46 2019[1,3]<stdout>:*** Check failure stack trace: ***
Sun Jul  7 22:12:46 2019[1,3]<stdout>:    @     0x7faffc9bbc0d  google::LogMessage::Fail()
Sun Jul  7 22:12:46 2019[1,3]<stdout>:    @     0x7faffc9bf6bc  google::LogMessage::SendToLog()
Sun Jul  7 22:12:46 2019[1,3]<stdout>:    @     0x7faffc9bb733  google::LogMessage::Flush()
Sun Jul  7 22:12:46 2019[1,3]<stdout>:    @     0x7faffc9c0bce  google::LogMessageFatal::~LogMessageFatal()
Sun Jul  7 22:12:46 2019[1,3]<stdout>:    @     0x7faffd4c330a  paddle::operators::distributed::GRPCClient::Proceed()
Sun Jul  7 22:12:46 2019[1,3]<stdout>:    @     0x7fb008ded8a0  execute_native_thread_routine
Sun Jul  7 22:12:46 2019[1,3]<stdout>:    @     0x7fb0649671c3  start_thread
Sun Jul  7 22:12:46 2019[1,3]<stdout>:    @     0x7fb063f8f12d  __clone
Sun Jul  7 22:12:46 2019[1,3]<stdout>:    @              (nil)  (unknown)
Sun Jul  7 22:13:01 2019[1,3]<stderr>:+ trainer_ret=134
Sun Jul  7 22:13:01 2019[1,3]<stderr>:+ popd
Sun Jul  7 22:13:01 2019[1,3]<stdout>:.//paddle/start_trainer.sh: line 112:  9873 Aborted                 (core dumped) python -u train.py --is_mpi=1
Sun Jul  7 22:13:01 2019[1,3]<stdout>:/home/disk1/task_data/history/20190707/3.app-user-20190707213707-26253--tieba_middlepage_dssm_201907072136_paddlecloud/logs/workspace
Sun Jul  7 22:13:01 2019[1,3]<stderr>:+ exit 134
Sun Jul  7 22:13:33 2019[1,1]<stdout>:F0707 22:13:33.641819  2057 grpc_client.cc:418] SendRPC name:[deep1.w_0@GRAD.block2.trainer_1], ep:[10.76.84.50:62001], status:[-1] meets grpc error, error_code:14 error_message:OS Error error_details:
Sun Jul  7 22:13:33 2019[1,1]<stdout>:*** Check failure stack trace: ***
Sun Jul  7 22:13:33 2019[1,1]<stdout>:    @     0x7f333ee96c0d  google::LogMessage::Fail()
Sun Jul  7 22:13:33 2019[1,1]<stdout>:    @     0x7f333ee9a6bc  google::LogMessage::SendToLog()
Sun Jul  7 22:13:33 2019[1,1]<stdout>:    @     0x7f333ee96733  google::LogMessage::Flush()
Sun Jul  7 22:13:33 2019[1,1]<stdout>:    @     0x7f333ee9bbce  google::LogMessageFatal::~LogMessageFatal()
Sun Jul  7 22:13:33 2019[1,1]<stdout>:    @     0x7f333f99e30a  paddle::operators::distributed::GRPCClient::Proceed()
Sun Jul  7 22:13:33 2019[1,1]<stdout>:    @     0x7f334b2c88a0  execute_native_thread_routine
Sun Jul  7 22:13:33 2019[1,1]<stdout>:    @     0x7f33a6e421c3  start_thread
Sun Jul  7 22:13:33 2019[1,1]<stdout>:    @     0x7f33a646a12d  __clone
Sun Jul  7 22:13:33 2019[1,1]<stdout>:    @              (nil)  (unknown)
Sun Jul  7 22:13:48 2019[1,1]<stderr>:+ trainer_ret=134
![image](https://user-images.githubusercontent.com/34762066/60782030-6e95c500-a177-11e9-9617-9f02909602ca.png)

log地址如下：
http://10.76.135.29:8910/fileview.html?type=logsdir&path=/&instance=0.app-user-20190707213707-26253--tieba_middlepage_dssm_201907072136_paddlecloud

**Comment by qnikev** [comment]
感谢paddle组的解答，是rpc超时的问题，需在config.ini中配置
FLAGS_rpc_deadline=3000000即可

**Comment by sandyhouse** [comment]
Closing this issue. Reopen it if you have any further question.
