### ISSUE TITLE
paddle的models示例中的lexical_analysis模型在单机多卡情况下运行报错

### ISSUE THREAD

**Issue by Bond-H** [PaddlePaddle/Paddle#18544]
- 版本、环境信息：
    1）PaddlePaddle版本：1.4.1
    3）GPU：K40m，Cuda8.0，cuDNN6.2
    4）系统环境：CentOS6.3， Python2.7
- 训练信息
    1）单机单卡模型能正常训练，单机多卡模型出现异常。

- 问题描述：参照文档示例将原模型中的Executor修改为ParallelExecutor，http://www.paddlepaddle.org.cn/documentation/docs/zh/1.4/api_cn/layers_cn.html#py-reader

**主要代码修改部分如下：**

原代码 https://github.com/PaddlePaddle/models/blob/develop/PaddleNLP/lexical_analysis/run_sequence_labeling.py：

修改其中220行的Executor的定义如下：

```
    fluid.Executor(place).run(startup_program)

    # ParallelExecutor
    exec_strategy = fluid.ExecutionStrategy()
    exec_strategy.allow_op_delay = True
    build_strategy = fluid.BuildStrategy()
    build_strategy.reduce_strategy = fluid.BuildStrategy.ReduceStrategy.Reduce

    exe = fluid.ParallelExecutor(use_cuda=True if args.use_cuda else False,
            loss_name=train_ret['avg_cost'].name,
            main_program=train_program if args.do_train else test_program,
            build_strategy=build_strategy,
            exec_strategy=exec_strategy)
```

修改后模型运行报错如下：
Traceback (most recent call last):
  File "run_sequence_labeling_parrallel.py", line 369, in <module>
    main(args)
  File "run_sequence_labeling_parrallel.py", line 278, in main
    train_ret["num_correct_chunks"],
  File "/home/work/huangdingbang/anaconda2/lib/python2.7/site-packages/paddle/fluid/parallel_executor.py", line 303, in run
    self.executor.run(fetch_list, fetch_var_name)
TypeError: run(): incompatible function arguments. The following argument types are supported:
    1. (self: paddle.fluid.core.ParallelExecutor, arg0: List[unicode], arg1: unicode) -> None

Invoked with: <paddle.fluid.core.ParallelExecutor object at 0x7f6fa26f0110>, [name: "mean_0.tmp_0"
type {
  type: LOD_TENSOR
  lod_tensor {
    tensor {
      data_type: FP32
      dims: 1
    }
  }
}
persistable: false
, name: "chunk_eval_0.tmp_3"
type {
  type: LOD_TENSOR
  lod_tensor {
    tensor {
      data_type: INT64
      dims: 1
    }
  }
}
persistable: false
, name: "chunk_eval_0.tmp_4"
type {
  type: LOD_TENSOR
  lod_tensor {
    tensor {
      data_type: INT64
      dims: 1
    }
  }
}
persistable: false
, name: "chunk_eval_0.tmp_5"
type {
  type: LOD_TENSOR
  lod_tensor {
    tensor {
      data_type: INT64
      dims: 1
    }
  }
}
persistable: false
], 'fetch'

**Comment by sandyhouse** [comment]
是修改为单机多卡分布式吗？

**Comment by sandyhouse** [comment]
ParallelExecutor和Executor执行时run函数的参数不一样，该用ParallelExecutor后，参考文档修改下run函数的参数吧。

**Comment by sandyhouse** [comment]
Closing this issue. Reopen it if you have any further question.

**Comment by Bond-H** [comment]
这个error确实是run函数的参数接口不一致导致的，Executor的run函数的fetch_list参数同时支持变量或变量名，而ParallelExecutor的run函数的fetch_list参数只支持变量名，不能输入变量，这种不一致性极容易导致迁移的过程中的出错，并且难以察觉，真心建议对此类问题进行规范化
