### ISSUE TITLE
AttributeError: 'tuple' object has no attribute 'persistable'

### ISSUE THREAD

**Issue by LukeALee** [PaddlePaddle/Paddle#18553]
paddle 踩坑：
fluid.layers.auc(input=probs, label=labels)官方文档说该函数返回的是一个标量（scalar），但实际返回的是一个tuple, 所以如果不关心tuple里除了auc之外其他字段的话正确的用法是
auc,\_,\_=fluid.layers.auc(input=probs, label=labels)，
如果关心的话，返回的tuple内容是
（auc,batch_auc,[batch_stat_pos,batch_stat_neg,stat_pos,stat_neg]）
希望官方能够及时更新文档，要不然怎么用呢。。。

**Comment by sandyhouse** [comment]
感谢您的反馈，我们已记录该问题，并会及时更新文档。

**Comment by sandyhouse** [comment]
Closing this issue. Reopen it if you have any further question.

**Comment by luotao1** [comment]
@sandyhouse @kagome112 用户问题没解决前，不能先关闭。
> 我们已记录该问题，并会及时更新文档

用户不知道什么时候会更新文档。麻烦等更新文档后，写上PR号，再关闭。
