### ISSUE TITLE
Paddle been killed unexpected when running image classification demo

### ISSUE THREAD

**Issue by Karbit** [PaddlePaddle/Paddle#1855]
I installed paddle-0.9.0-cpu-ubuntu14.04.deb on Ubuntu 14.04, and tried to run the image classification demo. The pre-process works OK. But when I run train.sh, the paddle seems to be killed unexpected. Following are the logs of train.sh:

root@jql-VirtualBox:/opt/paddle/paddle-source/paddle/demo/image_classification# sh train.sh
I0422 20:34:34.302465  6318 Util.cpp:155] commandline: /usr/bin/../opt/paddle/bin/paddle_trainer --config=vgg_16_cifar.py --dot_period=10 --log_period=100 --test_all_data_in_one_period=1 --use_gpu=0 --trainer_count=1 --num_passes=300 --save_dir=./cifar_vgg_model 
I0422 20:34:34.302968  6318 Util.cpp:130] Calling runInitFunctions
I0422 20:34:34.303380  6318 Util.cpp:143] Call runInitFunctions done.
[INFO 2017-04-22 20:34:34,629 layers.py:1890] channels=3 size=3072
[INFO 2017-04-22 20:34:34,630 layers.py:1890] output size for __conv_0__ is 32 
[INFO 2017-04-22 20:34:34,634 layers.py:1890] channels=64 size=65536
[INFO 2017-04-22 20:34:34,635 layers.py:1890] output size for __conv_1__ is 32 
[INFO 2017-04-22 20:34:34,639 layers.py:1985] output size for __pool_0__ is 16*16 
[INFO 2017-04-22 20:34:34,642 layers.py:1890] channels=64 size=16384
[INFO 2017-04-22 20:34:34,642 layers.py:1890] output size for __conv_2__ is 16 
[INFO 2017-04-22 20:34:34,648 layers.py:1890] channels=128 size=32768
[INFO 2017-04-22 20:34:34,648 layers.py:1890] output size for __conv_3__ is 16 
[INFO 2017-04-22 20:34:34,653 layers.py:1985] output size for __pool_1__ is 8*8 
[INFO 2017-04-22 20:34:34,655 layers.py:1890] channels=128 size=8192
[INFO 2017-04-22 20:34:34,656 layers.py:1890] output size for __conv_4__ is 8 
[INFO 2017-04-22 20:34:34,660 layers.py:1890] channels=256 size=16384
[INFO 2017-04-22 20:34:34,661 layers.py:1890] output size for __conv_5__ is 8 
[INFO 2017-04-22 20:34:34,666 layers.py:1890] channels=256 size=16384
[INFO 2017-04-22 20:34:34,673 layers.py:1890] output size for __conv_6__ is 8 
[INFO 2017-04-22 20:34:34,677 layers.py:1985] output size for __pool_2__ is 4*4 
[INFO 2017-04-22 20:34:34,680 layers.py:1890] channels=256 size=4096
[INFO 2017-04-22 20:34:34,680 layers.py:1890] output size for __conv_7__ is 4 
[INFO 2017-04-22 20:34:34,685 layers.py:1890] channels=512 size=8192
[INFO 2017-04-22 20:34:34,686 layers.py:1890] output size for __conv_8__ is 4 
[INFO 2017-04-22 20:34:34,690 layers.py:1890] channels=512 size=8192
[INFO 2017-04-22 20:34:34,691 layers.py:1890] output size for __conv_9__ is 4 
[INFO 2017-04-22 20:34:34,695 layers.py:1985] output size for __pool_3__ is 2*2 
[INFO 2017-04-22 20:34:34,696 layers.py:1985] output size for __pool_4__ is 1*1 
[INFO 2017-04-22 20:34:34,705 networks.py:1466] The input order is [image, label]
[INFO 2017-04-22 20:34:34,705 networks.py:1472] The output order is [__cost_0__]
I0422 20:34:34.730306  6318 Trainer.cpp:170] trainer mode: Normal
I0422 20:34:34.951273  6318 PyDataProvider2.cpp:257] loading dataprovider image_provider::processData
[INFO 2017-04-22 20:34:35,075 image_provider.py:51] Image size: 32
[INFO 2017-04-22 20:34:35,075 image_provider.py:52] Meta path: data/cifar-out/batches/batches.meta
[INFO 2017-04-22 20:34:35,075 image_provider.py:58] DataProvider Initialization finished
I0422 20:34:35.076849  6318 PyDataProvider2.cpp:257] loading dataprovider image_provider::processData
[INFO 2017-04-22 20:34:35,077 image_provider.py:51] Image size: 32
[INFO 2017-04-22 20:34:35,077 image_provider.py:52] Meta path: data/cifar-out/batches/batches.meta
[INFO 2017-04-22 20:34:35,077 image_provider.py:58] DataProvider Initialization finished
I0422 20:34:35.079453  6318 GradientMachine.cpp:134] Initing parameters..
I0422 20:34:36.215759  6318 GradientMachine.cpp:141] Init parameters done.
I0422 20:34:36.454990  6320 ThreadLocal.cpp:37] thread use undeterministic rand seed:6321
/usr/bin/paddle: line 109:  6318 Killed                  ${DEBUGGER} $MYDIR/../opt/paddle/bin/paddle_trainer ${@:2}

**Comment by qingqing01** [comment]
I note you use `paddle-0.9.0-cpu-ubuntu14.04.deb`, maybe, the demo you used is too old. We have fixed some problems. You can update your demo.

**Comment by Karbit** [comment]
Thanks for the suggestion. I tried the latest master and develop branches, but they have the same problem. Besides, the sentiment demo also has the problem, so maybe it is caused by settings of OS. Is there any code or document introduce the conditions that paddle kill the training process?

**Comment by qingqing01** [comment]
>  /usr/bin/paddle: line 109: 6318 Killed ${DEBUGGER} $MYDIR/../opt/paddle/bin/paddle_trainer ${@:2}

This phenomenon is usually caused by insufficient memory. I note you used a virtual box ( `root@jql-VirtualBox`), maybe its memory is too small. You can try to increase memory.

**Comment by Karbit** [comment]
Yeah, the demo works well after increase the memory. Thanks very much for help!
