### ISSUE TITLE
如何将本地数据传入embedding的参数矩阵中

### ISSUE THREAD

**Issue by shiyazhou121** [PaddlePaddle/Paddle#18557]
我有个本地词典数据，比如
id  col1 col2 col3
0   0       0      0
1    1        1      1
2   2       2      2
3   3       3      3

我想将数据作为embedding的参数

**Comment by ceci3** [comment]
你好，可以把本地词典保存为numpy格式，然后用 fluid.initializer.NumpyArrayInitializer 这个op来初始化embedding的参数
