### ISSUE TITLE
关于一些函数的参数名的问题

### ISSUE THREAD

**Issue by LaoYang1994** [PaddlePaddle/Paddle#18555]
为什么有的函数的参数名是dim， 有的函数的参数名是axis， 可不可以统一一下..

**Comment by sandyhouse** [comment]
感谢您的反馈，您的建议已记录，我们会在后续版本迭代中综合考量。

**Comment by sandyhouse** [comment]
Closing this issue. Reopen it if you have any further question.

**Comment by luotao1** [comment]
@sandyhouse @kagome112 用户问题没解决前，issue不能关闭。
> 我们会在后续版本迭代中综合考量

这个回答对用户来说信息不够。
