### ISSUE TITLE
windows下flower数据集报错找不到data（key）字段

### ISSUE THREAD

**Issue by DDDivano** [PaddlePaddle/Paddle#18556]
data下的key是二进制表示的，另一台win机器没有这个问题，很奇怪。
![image](https://user-images.githubusercontent.com/10734244/60812992-5056b600-a1c5-11e9-9026-8a2ac871041f.png)

**Comment by junjun315** [comment]
数据集不完整，重新下后应该就好了。侧面反映了这个数据集完整性校验可能有问题
