### ISSUE TITLE
paddle版transformer进行infer的时候报错

### ISSUE THREAD

**Issue by Lizhengo** [PaddlePaddle/Paddle#18574]
运行paddle版本transformer infer的时候出core
<img width="1242" alt="76843939150570b346937fe26088f07e" src="https://user-images.githubusercontent.com/28192236/60943189-c10de780-a317-11e9-862f-17a8aeed5727.png">
其中模型我做了一些改动，layer减少到3，在decoder那块又加了一个特征层。
<img width="577" alt="image" src="https://user-images.githubusercontent.com/28192236/60943255-f9152a80-a317-11e9-8eb5-ddf6b838fa8d.png">

训练的时候是正常的

**Comment by guoshengCS** [comment]
预测的时候有能够正常预测的case吗

**Comment by guoshengCS** [comment]
另外如果是使用Paddle 1.5版本的话，可以另外确认下这个修改 https://github.com/PaddlePaddle/models/pull/2485/files#diff-9deda6138e836033dde12e71dd637fadR284

**Comment by Lizhengo** [comment]
> 预测的时候有能够正常预测的case吗

目前用的是paddle1.3的。
预测的时候没有正常预测的case，但我把一些id信息打出来了
<img width="1255" alt="image" src="https://user-images.githubusercontent.com/28192236/60944155-9cffd580-a31a-11e9-817d-0f7f23dab490.png">
只有这些信息，之后就报错了

**Comment by Lizhengo** [comment]
> 预测的时候有能够正常预测的case吗

另外因为一些策略，我的Eos id 和 bos id是一样的

**Comment by guoshengCS** [comment]
> 另外因为一些策略，我的Eos id 和 bos id是一样的

这个可能会有问题，目前beam_search_op里面对eos的处理是：当pre_id是eos时会强制后续只产生eos，若一个query有beam_size个eos后这个query就结束了，如果Eos id 和 bos id是一样的话，那直接就结束了。不过core掉确实不够好，但即便没有这个core，目前beam_search_op是无法支持这种策略的。

**Comment by Lizhengo** [comment]
> > 另外因为一些策略，我的Eos id 和 bos id是一样的
> 
> 这个可能会有问题，目前beam_search_op里面对eos的处理是：当pre_id是eos时会强制后续只产生eos，若一个query有beam_size个eos后这个query就结束了，如果Eos id 和 bos id是一样的话，那直接就结束了。不过core掉确实不够好，但即便没有这个core，目前beam_search_op是无法支持这种策略的。

我尝试过，bos id和Eos id不一致，也还是报错，说明还是得解决下core这个问题

**Comment by guoshengCS** [comment]
>  我尝试过，bos id和Eos id不一致，也还是报错，说明还是得解决下core这个问题

麻烦在这种情况下将batch_size改为1，并将max_out_len减小到几步，在beam_search后使用layers.Print打印出selected_id，把打印出的内容贴下吧

**Comment by Lizhengo** [comment]
> > 我尝试过，bos id和Eos id不一致，也还是报错，说明还是得解决下core这个问题
> 
> 麻烦在这种情况下将batch_size改为1，并将max_out_len减小到几步，在beam_search后使用layers.Print打印出selected_id，把打印出的内容贴下吧

bug解决了，就是Eos和bos一致的问题，因为我没有改infer脚本里的eos和bos的tag，所以eos和bos还是一致的，把tag改成不一致的就不出core 了
