### ISSUE TITLE
训练过程报错Check failed: len >= 0  peer=: Connection reset by peer[104]

### ISSUE THREAD

**Issue by AWSWXY** [PaddlePaddle/Paddle#18571]
训练过程中报错，稳定复现
任务链接
http://10.87.109.18:8900/fileview.html?path=/home/disk1/normandy/maybach/app-user-20190710010204-9732/

**Comment by FDInSky** [comment]
看了log，没发现Paddle的明确报错信息，建议再排查一下其他方面
