### ISSUE TITLE
TensorRT文档建议

### ISSUE THREAD

**Issue by OliverLPH** [PaddlePaddle/Paddle#18586]
- 版本、环境信息
1）PaddlePaddle版本：Paddle1.5
2）CPU/GPU：CUDA8，cuDNN7 ， P4
3）系统环境：Ubuntu1604

- 建议描述：

[ISSUE10129](https://github.com/PaddlePaddle/Paddle/issues/10129) 就像这个issue里提到的，官方的TensorRT lib，在编进Paddle的时候需要手动添加 ~IPluginFactory()。 

所以我觉得应该可以在官网提供Paddle适配好的TRT的lib吧，这样感觉对用户也比较友好。

或者就像在Docker file里注明的一样，在文档里注明也可以。
![image](https://user-images.githubusercontent.com/14963836/61018563-d5122180-a3c9-11e9-8ee2-a88b181bab5f.png)

- 复现信息：

还有就是在 CUDA8，cuDNN7 编译从Nvidia官网下的 TensorRT-4.0.1.6.Ubuntu-16.04.4.x86_64-gnu.cuda-8.0.cudnn7.1.tar.gz 这个包，不光class IPluginFactory  需添加 ~IPluginFactory()。class IGpuAllocator 也需要添加 virtual ~IGpuAllocator() {} 才能编得过。

**Comment by OliverLPH** [comment]
补充一下错误截图
<img width="1401" alt="image" src="https://user-images.githubusercontent.com/14963836/61030068-254faa80-a3ef-11e9-8dab-ffdde179c5e7.png">

**Comment by NHZlX** [comment]
后续会在官网文档提示一下。

**Comment by dancingpipi** [comment]
mark下，同样遇到这个问题。。我还以为是我的tensorRT有问题。
添加:
virtual ~IPluginFactory(){}
virtual ~IGpuAllocator() {}
