### ISSUE TITLE
Infer输出id

### ISSUE THREAD

**Issue by CruiseSun** [PaddlePaddle/Paddle#18587]
比如有一条要进行预估的样本。1234567890 feature1 feature2 ... featureN，进行infer后我需要能保留1234567890，最终得到1234567890 predict_score。这个1234567890该怎么处理？

**Comment by zhaoyuchen2018** [comment]
这种case需要在预测前先处理下数据，把id保存在另外的地方，结束后然后再把id加回去

**Comment by CruiseSun** [comment]
好的，多谢！！
