### ISSUE TITLE
模型infer时报错

### ISSUE THREAD

**Issue by wlxy** [PaddlePaddle/Paddle#18595]
这个是正在训练的模型：
http://10.156.77.32:8900/fileview.html?path=/home/disk1/normandy/maybach/app-user-20190710160106-2401/

我选用了一个中间模型本地infer，结果报如下错误：
![image](https://user-images.githubusercontent.com/22311242/61031803-cc821100-a3f2-11e9-8ca4-2ea0840348b2.png)

如需复现问题：需替换util.py
ftp://yq01-mco-rd00.yq01.baidu.com/home/disk1/longxiuyun/git_lxy/baidu-2/mbd-stgy/push-ir/paddle_train/src-dense-code-applist-fm/utils.py

jobid:job-0bb5d259b1d78e64

为使您的问题得到快速解决，在建立Issue前，请您先通过如下方式搜索是否有相似问题:【搜索issue关键字】【使用labels筛选】【官方文档】

建立issue时，为快速解决问题，请您根据使用情况给出如下信息：
- 标题：简洁、精准描述您的问题，例如“ssd 模型前置lstm报错  ”
- 版本、环境信息：
    1）PaddlePaddle版本：请提供PaddlePaddle版本号，例如1.1或CommitID
    2）CPU：请提供CPU型号，MKL/OpenBlas/MKLDNN/等数学库的使用情况
    3）GPU：请提供GPU型号，CUDA和CUDNN版本号
    4）系统环境：请说明系统类型、版本（例如Mac OS 10.14），Python版本
- 模型信息
    1）模型名称 2）使用数据集名称 3）使用算法名称 4）模型链接
- 复现信息：如为报错，请给出复现环境、复现步骤
- 问题描述：请详细描述您的问题，同步贴出报错信息、日志/代码关键片段

Thank you for contributing to PaddlePaddle.
Before submitting the issue, you could search issue in the github.Probably there was a similar issue submitted or resolved before.
If there is no solution,please make sure that this is a issue of models including the following details:
**System information**
-PaddlePaddle version （eg.1.1）or CommitID
-CPU: including CPUMKL/OpenBlas/MKLDNN version
-GPU: including CUDA/CUDNN version
-OS Platform (eg.Mac OS 10.14)
-Python version
-Name of Models&Dataset/details of operator
**To Reproduce**
Steps to reproduce the behavior
**Describe your current behavior**
**Code to reproduce the issue**
**Other info / logs**

**Comment by zhaoyuchen2018** [comment]
无法复现，还需要再提供下infer的文件
