### ISSUE TITLE
Residual 结构的Con2D在flatten的时候出现gradient shape mismatch

### ISSUE THREAD

**Issue by YingjingLu** [PaddlePaddle/Paddle#18593]
Enforce failed. Expected x_dims[i + axis] == y_dims[i], but received x_dims[i + axis]:32768 != y_dims[i]:512.
Broadcast dimension mismatch. at [/paddle/paddle/fluid/operators/elementwise/elementwise_op_function.h:63]

    1）PPaddle 1.5
    2）i7 5820k
    3）Titan XP + Gtx 1080ti, Cuda 9 CUDNN 7.3.1
    4）Python36 Ubuntu 18.04
- 训练信息
    1）单卡/多卡
- 复现信息：如为报错，请给出复现环境、复现步骤
- 问题描述：Sphere_Lfw.py  第213行如果在flatten之前有residual 
结构：
`self.out =  self.out + self.conv_4_3_obj( self.conv_4_2_obj( self.out ) )
self.out = fluid.layers.flatten( self.out, axis = 1 )`会报错如下stack trace，
如果去掉residual结构则能正常训练：
`self.out =  self.conv_4_3_obj( self.conv_4_2_obj( self.out ) )
self.out = fluid.layers.flatten( self.out, axis = 1 )`

出现错误的stack trace：
`Traceback (most recent call last):
  File "sphere_face_main.py", line 48, in <module>
    train( MODEL, OPTS.cur_iter )
  File "/home/steven/Desktop/BAIDU/train_helper_sphere.py", line 98, in train
    loss = model.train( sample_pos, label )
  File "/home/steven/Desktop/BAIDU/models/paddle_models/sphere_lfw.py", line 246, in train
    loss = self.get_res( self.loss, self.main_program, sample_pos, label )
  File "/home/steven/Desktop/BAIDU/models/paddle_models/sphere_lfw.py", line 270, in get_res
    fetch_list = [ obj.name ] )
  File "/home/steven/.local/lib/python3.6/site-packages/paddle/fluid/executor.py", line 650, in run
    use_program_cache=use_program_cache)
  File "/home/steven/.local/lib/python3.6/site-packages/paddle/fluid/executor.py", line 748, in _run
    exe.run(program.desc, scope, 0, True, True, fetch_var_name)
paddle.fluid.core_avx.EnforceNotMet: Invoke operator elementwise_add_grad error.
Python Callstacks: 
  File "/home/steven/.local/lib/python3.6/site-packages/paddle/fluid/framework.py", line 1748, in append_op
    attrs=kwargs.get("attrs", None))
  File "/home/steven/.local/lib/python3.6/site-packages/paddle/fluid/layers/math_op_patch.py", line 149, in __impl__
    attrs={'axis': axis})
  File "/home/steven/Desktop/BAIDU/models/paddle_models/sphere_lfw.py", line 213, in construct_clf_mlp
    self.out =  self.out + self.conv_4_3_obj( self.conv_4_2_obj( self.out ) )
  File "/home/steven/Desktop/BAIDU/models/paddle_models/sphere_lfw.py", line 33, in init
    self.construct_clf_mlp()
  File "/home/steven/Desktop/BAIDU/models/paddle_models/sphere_lfw.py", line 19, in __init__
    self.init()
  File "sphere_face_main.py", line 40, in <module>
    MODEL = Sphere_Lfw( SESS, OPTS )
C++ Callstacks: 
Enforce failed. Expected x_dims[i + axis] == y_dims[i], but received x_dims[i + axis]:32768 != y_dims[i]:512.
Broadcast dimension mismatch. at [/paddle/paddle/fluid/operators/elementwise/elementwise_op_function.h:63]
PaddlePaddle Call Stacks: 
0       0x7fb36e557818p void paddle::platform::EnforceNotMet::Init<std::string>(std::string, char const*, int) + 360
1       0x7fb36e557b67p paddle::platform::EnforceNotMet::EnforceNotMet(std::string const&, char const*, int) + 87
2       0x7fb36f08f95cp paddle::operators::get_mid_dims(paddle::framework::DDim const&, paddle::framework::DDim const&, int, int*, int*, int*) + 364
3       0x7fb36fd6c54ap void paddle::operators::ElemwiseGradComputeWithBroadcast<paddle::platform::CUDADeviceContext, float, paddle::operators::IdentityGrad<float>, paddle::operators::IdentityGrad<float> >(paddle::framework::ExecutionContext const&, paddle::framework::DDim const&, paddle::framework::DDim const&, paddle::framework::Tensor const&, paddle::framework::Tensor const&, paddle::framework::Tensor const&, paddle::framework::Tensor const&, int, paddle::framework::Tensor*, paddle::framework::Tensor*, paddle::operators::IdentityGrad<float>, paddle::operators::IdentityGrad<float>) + 170
4       0x7fb36fd6da0bp void paddle::operators::default_elementwise_add_grad<paddle::platform::CUDADeviceContext, float>(paddle::framework::ExecutionContext const&, paddle::framework::Tensor const*, paddle::framework::Tensor const*, paddle::framework::Tensor const*, paddle::framework::Tensor const*, paddle::framework::Tensor*, paddle::framework::Tensor*) + 267
5       0x7fb36fd6dc71p paddle::operators::ElementwiseAddGradKernel<paddle::platform::CUDADeviceContext, float>::Compute(paddle::framework::ExecutionContext const&) const + 353
6       0x7fb36fd6dd33p std::_Function_handler<void (paddle::framework::ExecutionContext const&), paddle::framework::OpKernelRegistrarFunctor<paddle::platform::CUDAPlace, false, 0ul, paddle::operators::ElementwiseAddGradKernel<paddle::platform::CUDADeviceContext, float>, paddle::operators::ElementwiseAddGradKernel<paddle::platform::CUDADeviceContext, double>, paddle::operators::ElementwiseAddGradKernel<paddle::platform::CUDADeviceContext, int>, paddle::operators::ElementwiseAddGradKernel<paddle::platform::CUDADeviceContext, long>, paddle::operators::ElementwiseAddGradKernel<paddle::platform::CUDADeviceContext, paddle::platform::float16> >::operator()(char const*, char const*, int) const::{lambda(paddle::framework::ExecutionContext const&)#1}>::_M_invoke(std::_Any_data const&, paddle::framework::ExecutionContext const&) + 35
7       0x7fb3704b26e7p paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&, paddle::framework::RuntimeContext*) const + 375
8       0x7fb3704b2ac1p paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&) const + 529
9       0x7fb3704b00bcp paddle::framework::OperatorBase::Run(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&) + 332
10      0x7fb36e6e148ep paddle::framework::Executor::RunPreparedContext(paddle::framework::ExecutorPrepareContext*, paddle::framework::Scope*, bool, bool, bool) + 382
11      0x7fb36e6e452fp paddle::framework::Executor::Run(paddle::framework::ProgramDesc const&, paddle::framework::Scope*, int, bool, bool, std::vector<std::string, std::allocator<std::string> > const&, bool) + 143
12      0x7fb36e54897dp
13      0x7fb36e589cb6p
14            0x56204cp _PyCFunction_FastCallDict + 860
15            0x4f88bap
16            0x4f98c7p _PyEval_EvalFrameDefault + 1127
17            0x4f6128p
18            0x4f7d60p
19            0x4f876dp
20            0x4fa6c0p _PyEval_EvalFrameDefault + 4704
21            0x4f6128p
22            0x4f7d60p
23            0x4f876dp
24            0x4fa6c0p _PyEval_EvalFrameDefault + 4704
25            0x4f7a28p
26            0x4f876dp
27            0x4f98c7p _PyEval_EvalFrameDefault + 1127
28            0x4f7a28p
29            0x4f876dp
30            0x4f98c7p _PyEval_EvalFrameDefault + 1127
31            0x4f6128p
32            0x4f7d60p
33            0x4f876dp
34            0x4f98c7p _PyEval_EvalFrameDefault + 1127
35            0x4f6128p
36            0x4f9023p PyEval_EvalCode + 35
37            0x6415b2p
38            0x64166ap PyRun_FileExFlags + 154
39            0x643730p PyRun_SimpleFileExFlags + 400
40            0x62b26ep Py_Main + 1438
41            0x4b4cb0p main + 224
42      0x7fb3bbeefb97p __libc_start_main + 231
43            0x5bdf6ap _start + 42
`

源代码见下（sphere_lfw.py）：
`from __future__ import print_function
import os
from PIL import Image
import matplotlib.pyplot as plt
import numpy as np 
import paddle
import paddle.fluid as fluid
from models.paddle_base.conv import Conv2D, Conv2DTranspose, BatchNormConv2D, BNDepthwiseSeparableConv2D, BNDepthwiseSeparableConv2DTranspose
from models.paddle_base.dense import Dense
from models.paddle_models.paddle_model import Paddle_Model
from models.paddle_models.residual_block import *
from paddle.fluid.layers import relu, prelu, leaky_relu
from models.paddle_models.angle import *
class Sphere_Lfw( Paddle_Model ):
    
    def __init__(self, sess, opts):
        super( Sphere_Lfw, self ).__init__( sess, opts )
        self.is_test = True if ( self.opts.train == 0 ) else False
        self.init()
        self.startup_program = fluid.default_startup_program()
        self.main_program = fluid.default_main_program()
        self.test_program = self.main_program.clone( for_test = True )

        print( self.is_test, self.opts.train )
        # self.is_test = True
        if not self.is_test:
            grad_list = self.construct_optim()
        self.construct_gradient()
        self.sess.run( fluid.default_startup_program() )
    
    def init( self ):
        self.add_input_placeholder()
        self.construct_clf_mlp()
        self.construct_loss()
        os.mkdir( self.opts.cpt_path ) if not os.path.exists( self.opts.cpt_path ) else print()

        self.input_gradient = False
    
    def add_input_placeholder( self ):
        opts = self.opts
        self.sample_pos = fluid.layers.data( name = "sample_pos", shape = opts.sample_shape, 
                                            dtype = "float32", append_batch_size = True,
                                            stop_gradient = False ) 
        self.label_pos = fluid.layers.data( name = "label_pos", shape = [ 1 ], dtype = "int32", append_batch_size = True ) 
    def construct_clf_mlp( self ):
        self.conv_1_1_obj = BatchNormConv2D( 64, 
                                 kernel_w = 3, kernel_h = 3, 
                                 stride_h = 2, stride_v = 2,
                                 pad_h = 1, pad_v = 1,
                                 activation = leaky_relu,
                                 name = "conv_1_1" )
        self.conv_1_2_obj = BatchNormConv2D( 64, 
                                 kernel_w = 3, kernel_h = 3, 
                                 stride_h = 1, stride_v = 1,
                                 pad_h = 1, pad_v = 1,
                                 groups = 64,
                                 activation = leaky_relu,
                                 name = "conv_1_2" )
        self.conv_1_3_obj = BatchNormConv2D( 64, 
                                 kernel_w = 3, kernel_h = 3, 
                                 stride_h = 1, stride_v = 1,
                                 pad_h = 1, pad_v = 1,
                                 groups = 64,
                                 activation = leaky_relu,
                                 name = "conv_1_3" )
        
        self.conv_2_1_obj = BatchNormConv2D( 128, 
                                 kernel_w = 3, kernel_h = 3, 
                                 stride_h = 2, stride_v = 2,
                                 pad_h = 1, pad_v = 1,
                                 groups = 64,
                                 activation = leaky_relu,
                                 name = "conv_2_1" )
        self.conv_2_2_obj = BatchNormConv2D( 128, 
                                 kernel_w = 3, kernel_h = 3, 
                                 stride_h = 1, stride_v = 1,
                                 pad_h = 1, pad_v = 1,
                                 groups = 64,
                                 activation = leaky_relu,
                                 name = "conv_2_2" )
        self.conv_2_3_obj = BatchNormConv2D( 128, 
                                 kernel_w = 3, kernel_h = 3, 
                                 stride_h = 1, stride_v = 1,
                                 pad_h = 1, pad_v = 1,
                                 groups = 64,
                                 activation = leaky_relu,
                                 name = "conv_2_3" )
        
        self.conv_2_4_obj = BatchNormConv2D( 128, 
                                 kernel_w = 3, kernel_h = 3, 
                                 stride_h = 1, stride_v = 1,
                                 pad_h = 1, pad_v = 1,
                                 groups = 64,
                                 activation = leaky_relu,
                                 name = "conv_2_4" )
        self.conv_2_5_obj = BatchNormConv2D( 128, 
                                 kernel_w = 3, kernel_h = 3, 
                                 stride_h = 1, stride_v = 1,
                                 pad_h = 1, pad_v = 1,
                                 groups = 64,
                                 activation = leaky_relu,
                                 name = "conv_2_5" )

        self.conv_3_1_obj = BatchNormConv2D( 256, 
                                 kernel_w = 3, kernel_h = 3, 
                                 stride_h = 2, stride_v = 2,
                                 pad_h = 1, pad_v = 1,
                                 groups = 64,
                                 activation = leaky_relu,
                                 name = "conv_3_1" )
        self.conv_3_2_obj = BatchNormConv2D( 256, 
                                 kernel_w = 3, kernel_h = 3, 
                                 stride_h = 1, stride_v = 1,
                                 pad_h = 1, pad_v = 1,
                                 groups = 64,
                                 activation = leaky_relu,
                                 name = "conv_3_2" )
        self.conv_3_3_obj = BatchNormConv2D( 256, 
                                 kernel_w = 3, kernel_h = 3, 
                                 stride_h = 1, stride_v = 1,
                                 pad_h = 1, pad_v = 1,
                                 groups = 64,
                                 activation = leaky_relu,
                                 name = "conv_3_3" )
        
        self.conv_3_4_obj = BatchNormConv2D( 256, 
                                 kernel_w = 3, kernel_h = 3, 
                                 stride_h = 1, stride_v = 1,
                                 pad_h = 1, pad_v = 1,
                                 groups = 64,
                                 activation = leaky_relu,
                                 name = "conv_3_4" )
        self.conv_3_5_obj = BatchNormConv2D( 256, 
                                 kernel_w = 3, kernel_h = 3, 
                                 stride_h = 1, stride_v = 1,
                                 pad_h = 1, pad_v = 1,
                                 groups = 64,
                                 activation = leaky_relu,
                                 name = "conv_3_5" )

        self.conv_3_6_obj = BatchNormConv2D( 256, 
                                 kernel_w = 3, kernel_h = 3, 
                                 stride_h = 1, stride_v = 1,
                                 pad_h = 1, pad_v = 1,
                                 groups = 64,
                                 activation = leaky_relu,
                                 name = "conv_3_6" )
        self.conv_3_7_obj = BatchNormConv2D( 256, 
                                 kernel_w = 3, kernel_h = 3, 
                                 stride_h = 1, stride_v = 1,
                                 pad_h = 1, pad_v = 1,
                                 groups = 64,
                                 activation = leaky_relu,
                                 name = "conv_3_7" )
        
        self.conv_3_8_obj = BatchNormConv2D( 256, 
                                 kernel_w = 3, kernel_h = 3, 
                                 stride_h = 1, stride_v = 1,
                                 pad_h = 1, pad_v = 1,
                                 groups = 64,
                                 activation = leaky_relu,
                                 name = "conv_3_8" )
        self.conv_3_9_obj = BatchNormConv2D( 256, 
                                 kernel_w = 3, kernel_h = 3, 
                                 stride_h = 1, stride_v = 1,
                                 pad_h = 1, pad_v = 1,
                                 groups = 64,
                                 activation = leaky_relu,
                                 name = "conv_3_9" )
        
        self.conv_4_1_obj = BatchNormConv2D( 512, 
                                 kernel_w = 3, kernel_h = 3, 
                                 stride_h = 2, stride_v = 2,
                                 pad_h = 1, pad_v = 1,
                                 groups = 64,
                                 activation = leaky_relu,
                                 name = "conv_4_1" )
        self.conv_4_2_obj = BatchNormConv2D( 512, 
                                 kernel_w = 3, kernel_h = 3, 
                                 stride_h = 1, stride_v = 1,
                                 pad_h = 1, pad_v = 1,
                                 groups = 64,
                                 activation = leaky_relu,
                                 name = "conv_4_2" )
        self.conv_4_3_obj = BatchNormConv2D( 512, 
                                 kernel_w = 3, kernel_h = 3, 
                                 stride_h = 1, stride_v = 1,
                                 pad_h = 1, pad_v = 1,
                                 groups = 64,
                                 activation = leaky_relu,
                                 name = "conv_4_3" )
        
        self.pre_embed_obj = Dense( 512, activation = leaky_relu, name = "pre_embed" )
        self.embed_obj = Dense( self.opts.class_num, activation = None, name = "embed" )
        # self.embed_obj = Angle_Linear( 512, self.opts.class_num )

        # self.loss_obj = AngleLoss( class_num = self.opts.class_num )

        self.out = self.conv_1_1_obj( self.sample_pos, True )
        self.out = self.out + self.conv_1_3_obj( self.conv_1_2_obj( self.out ) )

        self.out = self.conv_2_1_obj( self.out )
        self.out = self.out + self.conv_2_3_obj( self.conv_2_2_obj( self.out ) )
        self.out = self.out + self.conv_2_5_obj( self.conv_2_4_obj( self.out ) )

        self.out = self.conv_3_1_obj( self.out )
        self.out = self.out + self.conv_3_3_obj( self.conv_3_2_obj( self.out ) )
        self.out = self.out + self.conv_3_5_obj( self.conv_3_4_obj( self.out ) )
        self.out = self.out + self.conv_3_7_obj( self.conv_3_6_obj( self.out ) )
        self.out = self.out + self.conv_3_9_obj( self.conv_3_8_obj( self.out ) )

        self.out = self.conv_4_1_obj( self.out )
        self.out =  self.out + self.conv_4_3_obj( self.conv_4_2_obj( self.out ) )

        self.out = fluid.layers.flatten( self.out, axis = 1 )
        self.embed = self.pre_embed_obj( self.out )
        self.logit = self.embed_obj( self.embed )

    def construct_loss( self ):
        # self.loss = self.loss_obj( self.logit, self.label_pos )
        self.loss = fluid.layers.softmax_with_cross_entropy( self.logit, fluid.layers.one_hot( self.label_pos, 10575 ), soft_label = True)
        self.loss = fluid.layers.mean( self.loss )
    
    def construct_gradient( self ):
        in_grad = fluid.backward.append_backward( self.loss, [ self.sample_pos.name ] )
        print( in_grad ) 
        self.sample_pos_grad = in_grad[ 0 ][ 1 ]

        # grad_list = [ x[ 1 ] for x in grad_list ]
        # [
        #     self.l0_w_grad,
        #     self.l0_b_grad,
        #     self.l1_w_grad,
        #     self.l1_b_grad,
        #     self.logit_w_grad,
        #     self.logit_b_grad
        # ] = grad_list

    def construct_optim( self ):
        self.optim = fluid.optimizer.AdamOptimizer( learning_rate = self.opts.lr, beta1 = 0.9, beta2 = 0.99 )
        _, grad_list = self.optim.minimize( self.loss )

        return grad_list

    def train( self, sample_pos, label):
        loss = self.get_res( self.loss, self.main_program, sample_pos, label )
        return loss

    def get_loss( self, sample_pos, label ):
        loss = self.get_res( self.loss, self.test_program, sample_pos, label )
        return loss

    def get_embedding( self, sample_pos ):
        return self.get_single_result( self.embed, self.test_program, sample_pos )

    def predict( self, sample_pos ):
        return self.get_single_result( self.logit[ 0 ], self.test_program, sample_pos )

    def get_res( self, obj, program, sample_pos, label):
        sample_pos = sample_pos.astype( np.float32 )
        label = label.astype( np.int32 )
        res_list = []
        num = sample_pos.shape[ 0 ]
        cur = 0
        while cur + self.opts.batch_size <= num:
            bs, bl = sample_pos[ cur: cur+self.opts.batch_size, : ], label[ cur: cur+self.opts.batch_size, : ]
            [ res ] = self.sess.run( program = program,
                            feed = { self.sample_pos.name : bs, 
                                     self.label_pos.name: bl },
                            fetch_list = [ obj.name ] )
            res_list.append( res )
            cur += self.opts.batch_size 
        if cur < num:
            bs, bl = sample_pos[ cur:, :  ], label[ cur:, : ]
            [ res ] = self.sess.run( program = program,
                            feed = { self.sample_pos.name : bs, 
                                     self.label_pos.name: bl }, 
                            fetch_list = [ obj.name ] )
            res_list.append( res )
        if len( res.shape ) > 1:
            return np.vstack( res_list )
        else:
            return np.hstack( res_list )

    # def get_double_result( self, obj, program, sample_pos, label ):
    #     sample_near = np.zeros_like( label )
    #     return self.get_res( obj, program, sample_pos, label, sample_near )

    def get_single_result( self, obj, program, sample_pos ):
        sample_neg = np.zeros( ( sample_pos.shape[ 0 ], 1 ) )
        return self.get_res( obj, program, sample_pos, sample_neg )

    def save( self, path ):
        os.mkdir( path )

        inference_path = self.get_infer_path( path )
        param_path = self.get_param_path( path )
        os.mkdir( inference_path )
        os.mkdir( param_path )

        fluid.io.save_inference_model( inference_path, [ "sample_pos" ], [ self.logit[ 0 ] ], self.sess )
        fluid.io.save_persistables( self.sess, param_path, self.main_program )

`
BNConv的class见下：
`class BatchNormConv2D( object ):
    def __init__( self, filters = 8, \
                  kernel_w = 3, kernel_h= 3, 
                  stride_h = 1, stride_v = 1,
                  pad_h = 0, pad_v = 0,
                  dilation_h = 1, dilation_v = 1,
                  activation = None,
                  use_bias = True,
                  kernel_init = fluid.initializer.MSRAInitializer(), bias_init = fluid.initializer.ConstantInitializer(),
                  groups = 1,
                  kernel_regu = None, bias_regu = None,
                  activation_regu = None,
                  bias_constraint = None,
                  reuse = False,
                  trainable = True,
                  name = "BNConv2D" ):
        self.filters = filters
        self.kernel_w = kernel_w
        self.kernel_h = kernel_h
        self.stride_h = stride_h
        self.stride_v = stride_v
        self.pad_h = pad_h
        self.pad_v = pad_v
        self.dilation_v = dilation_v
        self.dilation_h = dilation_h
        self.activation = activation 
        self.use_bias = use_bias,
        self.kernel_init = kernel_init 
        self.bias_init = bias_init 
        self.groups = groups
        self.kernel_regu = kernel_regu
        self.bias_regu = bias_regu 
        self.activation_regu = activation_regu
        self.bias_constraint = bias_constraint
        self.reuse = reuse,
        self.trainable = trainable
        self.name = name
    
    def __call__( self, inputs, transform_input = False ):
        self.w = self.name + "_w"
        self.b = self.name + "_b"
        w_attr = fluid.ParamAttr( name = self.w, 
                                  initializer = self.kernel_init,
                                  regularizer = self.kernel_regu,
                                  trainable = self.trainable )
        b_attr = fluid.ParamAttr( name = self.b, 
                                  initializer = self.bias_init,
                                  regularizer = self.bias_regu,
                                  trainable = self.trainable )
        if transform_input:
            inputs = fluid.layers.transpose( inputs, perm = [ 0, 3, 1, 2 ] )
        print( self.name, "input shape:", inputs.shape )
        """
        [ n, c, h, w ] = inputs.shape
        # calc padding for each side
        filter_w = self.dilation_h * ( self.kernel_w - 1 ) + 1 
        filter_h = self.dilation_v * ( self.kernel_h - 1 ) + 1
        if self.padding.lower() == 'valid':
            width = math.ceil( (  w - filter_w ) / self.stride_h ) + 1
            height = math.ceil( ( h - filter_h ) / self.stride_v ) + 1
        elif self.padding.lower() == "same":
            width = math.ceil( w / self.stride_h )
            height = math.ceil( h / self.stride_v )
        else:
            NotImplementedError( "Not an implemented padding for Conv2D: %s", self.padding )
        print( "width", width, "height", height, [ n, c, h, w ] )
        restructured_w = ( width - 1 ) * self.stride_h + filter_w
        restructured_h = ( height - 1) * self.stride_v + filter_h 

        pad_h = max( math.ceil( ( restructured_w - w ) / 2 ), 0 )
        pad_v = max( math.ceil( ( restructured_h - h ) / 2 ), 0 )

        self.pad_h, self.pad_v = pad_h, pad_v
        print( "pad_v", pad_v, "pad_h", pad_h )
        """
        self.layer_out = fluid.layers.conv2d( input = inputs,
                                              num_filters = self.filters,
                                              filter_size = ( self.kernel_h, self.kernel_w ),
                                              stride = ( self.stride_v, self.stride_h ),
                                              padding = ( self.pad_v, self.pad_h ),
                                              dilation = ( self.dilation_v, self.dilation_h ),
                                              act = None, 
                                              groups = self.groups,
                                              param_attr = w_attr,
                                              bias_attr = b_attr,
                                              name = self.name )
        self.layer_out = fluid.layers.batch_norm( self.layer_out, act = None )
        if self.activation is not None:
            self.layer_out = self.activation( self.layer_out )
        print( self.name, "output shape", self.layer_out.shape )
        print( "--------------------------" )
        return self.layer_out

    def __repr__( self ):

        return self.name  

    def get_weights( self, sess = None ):

        assert ( self.w is not None ) and ( self. b is not None ), "weights in the dense layer should be initialized"

        # place = fluid.CPUPlace()
        # exe = fluid.Executor(place)
        # exe.run(fluid.default_startup_program())
        w = fluid.global_scope().find_var( self.w ).get_tensor()
        b = fluid.global_scope().find_var( self.b ).get_tensor()

        return np.array( w ), np.array( b )`

**Comment by zhaoyuchen2018** [comment]
从报错信息看是在做elementwise的grad的时候两个参数x和y的dim不匹配造成的，一般来说x和y的参数要满足重axis开始往后的dim要相等，具体参考：https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/fluid/operators/elementwise/elementwise_op_function.h#L44

可以打下log看看下面语句的的dim是不是有问题
self.out + self.conv_4_3_obj( self.conv_4_2_obj( self.out ) )

**Comment by YingjingLu** [comment]
语句的dim没有问题，都是（-1,512,8,8）而且两个加起来后面接reshape，conv，pool就没有这个问题，只有flatten时有这个问题

**Comment by zhaoyuchen2018** [comment]
> 语句的dim没有问题，都是（-1,512,8,8）而且两个加起来后面接reshape，conv，pool就没有这个问题，只有flatten时有这个问题

展开后变成了维度变成了32768，和elememntwise的维度不match

**Comment by YingjingLu** [comment]
您好，展开以后32768=512 * 8 * 8的展开数量的，按照doc我理解flatten 就应该把( -1, 512, 8, 8 )在axis=1时的维度展成( -1, 32768 )同样的位置将flatten换为reshape就没有报错

**Comment by zhaoyuchen2018** [comment]
> 您好，展开以后32768=512 * 8 * 8的展开数量的，按照doc我理解flatten 就应该把( -1, 512, 8, 8 )在axis=1时的维度展成( -1, 32768 )同样的位置将flatten换为reshape就没有报错

那你看看reshape和flat之后的dim相同吗，看你报错的信息是在elementwise，从报错信息推断是flat之后的dim有问题

**Comment by YingjingLu** [comment]
已解决。谢谢
