### ISSUE TITLE
关于大规模稀疏id特征embedding的使用问题

### ISSUE THREAD

**Issue by lps683** [PaddlePaddle/Paddle#18590]
目前embedding是否支持int64的id类特征的embedding？
从官网的教程可以get到以下信息
![image](https://user-images.githubusercontent.com/17926197/61019661-8cf4fe00-a3cd-11e9-834d-46db94d83fe0.png)
这个意思是说，id的value是可以大于dictsize的，只是所有id的数量小于dictsize就可以啦
实际操作如下：（fluid1.4）
![image](https://user-images.githubusercontent.com/17926197/61019750-dc3b2e80-a3cd-11e9-86c2-51065ba65397.png)
现在训练集中有一个uid=55796870，这时候报错
![image](https://user-images.githubusercontent.com/17926197/61019774-fb39c080-a3cd-11e9-9b34-b34a1112fb6e.png)
这似乎与教程的意思不相符，是我理解错了么？
请问这类id类特征要如何embedding呢？

**Comment by zhaoyuchen2018** [comment]
代码中是限制id < dict size，https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/fluid/operators/lookup_table_op.h#L88，能贴一下文档的具体地址吗？

**Comment by lps683** [comment]
问题搞清楚了 单机下限制id < dict size，分布式可以支持大规模的id特征
文档https://www.paddlepaddle.org.cn/documentation/docs/zh/1.4/api_guides/low_level/distributed/large_scale_sparse_feature_training.html
