### ISSUE TITLE
MPI分布式训练过程有core，没有core信息 ，同时线下发现不了

### ISSUE THREAD

**Issue by wawltor** [PaddlePaddle/Paddle#18591]
在训练过程中训练任务还没有开始，就有core，线下开启多端口的ps模式复现不了 

日志地址：http://10.104.149.24:8900/fileview.html?path=/home/disk1/normandy/maybach/app-user-20190711105415-3124/

日志信息：
.//paddle/start_trainer.sh: line 112: 21797 Segmentation fault      (core dumped) FLAGS_rpc_deadline=3000000 CPU_NUM=2 python cluster_train.py --is_sparse --is_distributed --sample_workers 2

错误码：139

**Comment by zhaoyuchen2018** [comment]
能贴一下完整日志信息吗，下图中貌似看不到日志

![image](https://user-images.githubusercontent.com/45989343/61021652-f4627c00-a3d4-11e9-89af-0c44214741b4.png)

**Comment by wawltor** [comment]
> 能贴一下完整日志信息吗，下图中貌似看不到日志
> 
> ![image](https://user-images.githubusercontent.com/45989343/61021652-f4627c00-a3d4-11e9-89af-0c44214741b4.png)

日志在workspace的log目录下面

**Comment by zhaoyuchen2018** [comment]
INFO] 2019-07-11 11:11:37,241 [cluster_train.py:  565]:	Namespace(batch_size=128, cache_path='./tmp', data_path='', digraph=False, epoch=2, hidden_size=128, is_distributed=True, is_sparse=True, layer_type='graphsage_mean', lr=0.01, num_layers=2, sample_workers=2, samples=[10, 10], single_usr_embed=False, use_cuda=False, use_pyreader=False, valid=False)
I0711 11:11:37.401131 21797 communicator.cc:63] communicator_independent_recv_thread: 1
I0711 11:11:37.401157 21797 communicator.cc:65] communicator_send_queue_size: 20
I0711 11:11:37.401161 21797 communicator.cc:67] communicator_min_send_grad_num_before_recv: 20
I0711 11:11:37.401165 21797 communicator.cc:69] communicator_thread_pool_size: 5
I0711 11:11:37.401166 21797 communicator.cc:71] communicator_send_wait_times: 5
I0711 11:11:37.401170 21797 communicator.cc:73] communicator_max_merge_var_num: 20
I0711 11:11:37.401171 21797 communicator.cc:75] communicator_fake_rpc: 0
I0711 11:11:37.408079 21797 communicator.cc:274] Communicator start
[INFO] 2019-07-11 11:12:44,230 [cluster_train.py:  147]:	Load redis graph done.
[INFO] 2019-07-11 11:12:44,933 [cluster_train.py:  465]:	check step 1
[INFO] 2019-07-11 11:12:44,969 [redis_reader.py:  238]:	The size of batch:1018
.//paddle/start_trainer.sh: line 112: 21797 Segmentation fault      (core dumped) FLAGS_rpc_deadline=3000000 CPU_NUM=2 python cluster_train.py --is_sparse --is_distributed --sample_workers 2

看起来是分布式报的错误，你在分布式的群里面吗，可以问一下分布式的同学。
另外麻烦把issue里面的ip地址去掉哈。
