### ISSUE TITLE
增量训练加载初始化参数不起作用

### ISSUE THREAD

**Issue by AWSWXY** [PaddlePaddle/Paddle#18609]
采用增量训练的方式，加载参数，看起来没有起到效果
参数加载在参数初始化之后。
exe.run(startup_prog)
if args.init_model is not None:
        print("load model from: %s" % args.init_model)
        sys.stdout.flush()
        fluid.io.load_params(exe, args.init_model)

**Comment by wopeizl** [comment]
分布式环境下用load_persistables替代load_params

**Comment by wopeizl** [comment]
http://10.87.108.33:8900/fileview.html?path=/home/disk1/normandy/maybach/app-user-20190710173646-9925/

**Comment by wopeizl** [comment]
![image](https://user-images.githubusercontent.com/23548796/61111993-7037f380-a4bd-11e9-9f2a-1b29d0672dcc.png)
