### ISSUE TITLE
C++ 创建lodtensor并赋值相关api

### ISSUE THREAD

**Issue by xuzhenglei1991** [PaddlePaddle/Paddle#18600]
当前依赖的paddle版本为baidu/paddlepaddle/paddle@v1.3.0_pb32，
一个300长，lod为{0，300}的26维向量存在一个vector<vector<float>>中，想要将这个转为对应的lodtensor数据，应该如何操作呢？有没有相应的demo供参考一下？

**Comment by OliverLPH** [comment]
我理解你的需求是不是

```cpp
PaddleTensor tensor;
tensor.shape = std::vector<int>({batch_size, channels, height, width});
tensor.data = PaddleBuf(static_cast<void *>(data), sizeof(float) * (batch_size * channels * height * width)); 
tensor.dtype = PaddleDType::FLOAT32;
tensor.lod = {0，300} 
```

**Comment by xuzhenglei1991** [comment]
> 我理解你的需求是不是
> 
> ```c++
> PaddleTensor tensor;
> tensor.shape = std::vector<int>({batch_size, channels, height, width});
> tensor.data = PaddleBuf(static_cast<void *>(data), sizeof(float) * (batch_size * channels * height * width)); 
> tensor.dtype = PaddleDType::FLOAT32;
> tensor.lod = {0，300} 
> ```

这段代码里面哪个是表示dim的呢，我看当前的一维的创建方法是
paddle::framework::DDim dims = {(long)input_count, 1};
int64_t *input_ptr_word = tensor_word.mutable_data<int64_t>(dims, paddle::platform::CPUPlace());
for (int i = 0; i < tensor_word.numel(); ++i) {
        input_ptr_word[i] = input_vector[i];
}
这个有没对应的方法呢

**Comment by zhaoyuchen2018** [comment]
> > 我理解你的需求是不是
> > ```c++
> > PaddleTensor tensor;
> > tensor.shape = std::vector<int>({batch_size, channels, height, width});
> > tensor.data = PaddleBuf(static_cast<void *>(data), sizeof(float) * (batch_size * channels * height * width)); 
> > tensor.dtype = PaddleDType::FLOAT32;
> > tensor.lod = {0，300} 
> > ```
> 
> 这段代码里面哪个是表示dim的呢，我看当前的一维的创建方法是
> paddle::framework::DDim dims = {(long)input_count, 1};
> int64_t *input_ptr_word = tensor_word.mutable_data<int64_t>(dims, paddle::platform::CPUPlace());
> for (int i = 0; i < tensor_word.numel(); ++i) {
> input_ptr_word[i] = input_vector[i];
> }
> 这个有没对应的方法呢

shape里面保存的就是dim的信息

**Comment by OliverLPH** [comment]
> > 我理解你的需求是不是
> > ```c++
> > PaddleTensor tensor;
> > tensor.shape = std::vector<int>({batch_size, channels, height, width});
> > tensor.data = PaddleBuf(static_cast<void *>(data), sizeof(float) * (batch_size * channels * height * width)); 
> > tensor.dtype = PaddleDType::FLOAT32;
> > tensor.lod = {0，300} 
> > ```
> 
> 这段代码里面哪个是表示dim的呢，我看当前的一维的创建方法是
> paddle::framework::DDim dims = {(long)input_count, 1};
> int64_t *input_ptr_word = tensor_word.mutable_data<int64_t>(dims, paddle::platform::CPUPlace());
> for (int i = 0; i < tensor_word.numel(); ++i) {
> input_ptr_word[i] = input_vector[i];
> }
> 这个有没对应的方法呢

噢噢，你把二维向量拼接起来传入应该就可以了，dim用shape表示。

输入数据貌似只能传入flatten数据。
