### ISSUE TITLE
【paddlepaddle_gpu-1.5.0.post107】Compiled with WITH_GPU, but no GPU found in runtime

### ISSUE THREAD

**Issue by aslily1234** [PaddlePaddle/Paddle#18602]
为使您的问题得到快速解决，在建立Issue前，请您先通过如下方式搜索是否有相似问题:【搜索issue关键字】【使用labels筛选】【官方文档】

建立issue时，为快速解决问题，请您根据使用情况给出如下信息：
- 标题：请包含关键词“安装错误”/“编译错误”，例如“Mac编译错误”
- 版本、环境信息：
    1）PaddlePaddle版本：请提供您的PaddlePaddle版本号（如1.1）或CommitID
在官网上查找对应版本【pip3 install paddlepaddle-gpu==1.5.0.post107】，然后下载paddlepaddle_gpu-1.5.0.post107-cp37-cp37m-manylinux1_x86_64.whl 到服务器，再使用pip install paddlepaddle_gpu-1.5.0.post107-cp37-cp37m-manylinux1_x86_64.whl 方式安装的

    2）CPU：请提供CPU型号，MKL/OpenBlas/MKLDNN/等数学库的使用情况

    3）GPU：请提供GPU型号，CUDA和CUDNN版本号
$nvidia-smi
Fri Jul 12 09:54:03 2019       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 410.48                 Driver Version: 410.104                   |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla P100-PCIE...  Off  | 00000000:00:07.0 Off |                    0 |
| N/A   29C    P0    26W / 250W |      0MiB / 16280MiB |      6%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+

$ yum info cuda
Loaded plugins: fastestmirror, langpacks
Repository base is listed more than once in the configuration
Repository updates is listed more than once in the configuration
Repository extras is listed more than once in the configuration
Repository centosplus is listed more than once in the configuration
Repository base is listed more than once in the configuration
Repository updates is listed more than once in the configuration
Repository extras is listed more than once in the configuration
Repository centosplus is listed more than once in the configuration
Loading mirror speeds from cached hostfile
 * base: mirrors.163.com
 * epel: mirrors.yun-idc.com
 * extras: mirrors.cn99.com
 * updates: mirrors.cn99.com
Installed Packages
Name        : cuda
Arch        : x86_64
Version     : 10.0.130
Release     : 1
Size        : 0.0  
Repo        : installed
From repo   : cuda-10-0-local-10.0.130-410.48
Summary     : CUDA meta-package
URL         : http://nvidia.com
License     : NVIDIA Proprietary
Description : Meta-package containing all the available packages required for native CUDA
            : development. Contains the toolkit, samples, driver and documentation.

    4）系统环境：请说明系统类型、版本（如Mac OS 10.14）、Python版本
$cat /proc/version
Linux version 3.10.0-957.10.1.el7.x86_64 (mockbuild@kbuilder.bsys.centos.org) (gcc version 4.8.5 20150623 (Red Hat 4.8.5-36) (GCC) ) #1 SMP Mon Mar 18 15:06:45 UTC 2019

$ipython
Python 3.7.3 (default, Mar 27 2019, 22:11:17) 
Type 'copyright', 'credits' or 'license' for more information
IPython 7.4.0 -- An enhanced Interactive Python. Type '?' for help.

- 安装方式信息：
1）pip安装/docker安装
pip install paddlepaddle_gpu-1.5.0.post107-cp37-cp37m-manylinux1_x86_64.whl

2）本地编译：请提供cmake命令，编译命令
3）docker编译：请提供docker镜像，编译命令            
  特殊环境请注明：如离线安装等
- 复现信息：如为报错，请给出复现环境、复现步骤
- 问题描述：请详细描述您的问题，同步贴出报错信息、日志/代码关键片段
# ipython
import paddlePython 3.7.3 (default, Mar 27 2019, 22:11:17) 
Type 'copyright', 'credits' or 'license' for more information
IPython 7.4.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import paddle                                                                                                                                                                                   
In [2]: import paddle.fluid as fluid                                                                                                                                                                    
**W0712 09:45:14.906232 15821 init.cc:128] Compiled with WITH_GPU, but no GPU found in runtime.**

不知道这个提示是不是没有关联上GPU，如果是，怎么关联机器上的GPU呢？

**Comment by chfguo** [comment]
cuda和运行时的驱动不一致，如果是cuda10的话，nvidia-smi显示的信息，Driver Version >=410
NVIDIA-SMI 410.104      Driver Version: 410.104      CUDA Version: 10.0 
如果不一致可以升级显卡驱动，也可以降低cuda的版本，有一个驱动和cuda的对应表，查一下看看

**Comment by aslily1234** [comment]
> cuda和运行时的驱动不一致，如果是cuda10的话，nvidia-smi显示的信息，Driver Version >=410
> NVIDIA-SMI 410.104 Driver Version: 410.104 CUDA Version: 10.0
> 如果不一致可以升级显卡驱动，也可以降低cuda的版本，有一个驱动和cuda的对应表，查一下看看

我用yum info cuda命令，看到的cuda版本确实已经是 10.0.130版本了，您说的驱动和cuda的对应表方便发一下么？

**Comment by aslily1234** [comment]
驱动和cuda的对应表 : https://docs.nvidia.com/cuda/cuda-toolkit-release-notes/index.html#abstract

重新运行了一遍驱动安装程序， sh NVIDIA-Linux-x86_64-410.104.run 

然后执行nvidia-smi命令：（可以正常显示【NVIDIA-SMI 410.104      Driver Version: 410.104      CUDA Version: 10.0  】了），然后就可以了
Fri Jul 12 14:05:01 2019       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 410.104      Driver Version: 410.104      CUDA Version: 10.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla P100-PCIE...  Off  | 00000000:00:07.0 Off |                    0 |
| N/A   27C    P0    26W / 250W |      0MiB / 16280MiB |      6%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+

**Comment by aslily1234** [comment]
> cuda和运行时的驱动不一致，如果是cuda10的话，nvidia-smi显示的信息，Driver Version >=410
> NVIDIA-SMI 410.104 Driver Version: 410.104 CUDA Version: 10.0
> 如果不一致可以升级显卡驱动，也可以降低cuda的版本，有一个驱动和cuda的对应表，查一下看看

谢谢提示~

**Comment by PHizing** [comment]
我按照网页提示查了对应表，Cuda compilation tools, release 9.0, V9.0.176，NVIDIA-SMI 396.26                 Driver Version: 396.26 。应该是合适的。
仍然报“Compiled with WITH_GPU, but no GPU found in runtime”错误，而且我在这个环境的另一个GPU程序可以正常运行。

**Comment by BeyondYourself** [comment]
> 我按照网页提示查了对应表，Cuda compilation tools, release 9.0, V9.0.176，NVIDIA-SMI 396.26 Driver Version: 396.26 。应该是合适的。
> 仍然报“Compiled with WITH_GPU, but no GPU found in runtime”错误，而且我在这个环境的另一个GPU程序可以正常运行。

我的版本也匹配的，也是报和你一样的错，这个问题解决了吗，我是刚刚升级的paddle1.8.0-GPU
