### ISSUE TITLE
MPI训练过程中出core

### ISSUE THREAD

**Issue by wawltor** [PaddlePaddle/Paddle#18604]
训练过程：在训练过程中出现core，core信息不好定位
参考信息:如果是本地采样在训练过程中不会出core（将训练数据load在trainer上），如果使用redis集群实时采样会出core
日志地址：http://10.104.151.23:8900/fileview.html?path=/home/disk1/normandy/maybach/app-user-20190711110449-3132/

**Comment by seiriosPlus** [comment]
开一下LOG吧 
export GLOG_v=4

**Comment by wawltor** [comment]
> 开一下LOG吧
> export GLOG_v=4

打开 GLOG_v=4日志：http://10.104.149.13:8900/fileview.html?path=/home/disk1/normandy/maybach/app-user-20190715193524-6733/
麻烦看看啊

**Comment by seiriosPlus** [comment]
看不出来，hi上复现一下吧
