### ISSUE TITLE
paddle1.5版本，官方文档在手写字识别的例子有一个错误，导致EnforceNotMet: Invoke operator batch_norm_grad error.

### ISSUE THREAD

**Issue by chfguo** [PaddlePaddle/Paddle#18603]
版本、环境信息
1）PaddlePaddle版本：1.5
2）CPU/GPU：CPU训练正常，GPU出现错误
3）系统环境：Ubuntu 18.04, GPU TX1060Ti, CUDA10
- 官方文档在这个例子中中先定义了
optimizer = fluid.optimizer.Adam(learning_rate=0.001)
optimizer.minimize(avg_loss)
然后设置：
main_program = fluid.default_main_program()
test_program = fluid.default_main_program().clone(for_test=True)
这个地方会导致训练过程中
    avg_loss_val, acc_val = train_test(train_test_program=test_program,
                                       train_test_reader=test_reader,
                                       train_test_feed=feeder)
出错，错误信息EnforceNotMet: Invoke operator batch_norm_grad error
github中的例子是正确的，建议官方文档修复下这个bug

**Comment by wopeizl** [comment]
好的，非常感谢
