### ISSUE TITLE
lstm如何更改激励向量计算方法

### ISSUE THREAD

**Issue by 1160301024** [PaddlePaddle/Paddle#18617]
使用cpu和在paddle文档中下载的情感分析lstm的实例，应该如何更改lstm的激励向量的计算方法？

**Comment by wopeizl** [comment]
你是想换activation函数吗？

**Comment by wopeizl** [comment]
![image](https://user-images.githubusercontent.com/23548796/61125165-a97f5c00-a4db-11e9-9c99-83741d6831a4.png)

**Comment by wopeizl** [comment]
https://www.paddlepaddle.org.cn/documentation/docs/zh/1.5/api_cn/layers_cn/nn_cn.html#dynamic-lstm

**Comment by 1160301024** [comment]
不是activation函数，是peephole连接中c的计算公式

**Comment by wopeizl** [comment]
这种情况下需要自己去改c代码，paddle/paddle/fluid/operators/math/detail/lstm_kernel.h， 
![image](https://user-images.githubusercontent.com/23548796/61198612-54c32780-a70d-11e9-893a-537bf590f613.png)
