### ISSUE TITLE
关于window和ubuntu下numpy中int不同类型的问题

### ISSUE THREAD

**Issue by ididhmc** [PaddlePaddle/Paddle#18615]
欢迎您对PaddlePaddle提出建议，非常感谢您对PaddlePaddle的贡献！
在留下您的建议时，辛苦您同步提供如下信息：
- 版本、环境信息
1）PaddlePaddle版本：PaddlePaddle 1.5
2）CPU/GPU：CPU
3）系统环境：WIN10

- 复现信息：由于window下numpy默认int的数据类型是int32，所以在喂入数据的时候，出现了
paddle.fluid.core_avx.EnforceNotMet: Invoke operator lookup_table error.
原先数据：
![image](https://user-images.githubusercontent.com/41049893/61109119-b0e03e80-a4b6-11e9-9d04-f1e1a83a551f.png)
运行后报错
![image](https://user-images.githubusercontent.com/41049893/61109136-bb023d00-a4b6-11e9-924a-1421aa0ef4e3.png)

- 解决方法： 在喂入数据的时候，加上numpy（[n]）.astype("int64")，将整形重新定义成int64，则可以避免此错误
![image](https://user-images.githubusercontent.com/41049893/61109055-868e8100-a4b6-11e9-96a7-f34491509d55.png)
![image](https://user-images.githubusercontent.com/41049893/61109073-93ab7000-a4b6-11e9-866b-417a88fbd6f1.png)

**Comment by wopeizl** [comment]
文档有问题，需要修复，
user_id = fluid.create_lod_tensor([[np.int64(1)]], [[1]], place)
gender_id = fluid.create_lod_tensor([[np.int64(1)]], [[1]], place)
age_id = fluid.create_lod_tensor([[np.int64(0)]], [[1]], place)
job_id = fluid.create_lod_tensor([[np.int64(10)]], [[1]], place)
movie_id = fluid.create_lod_tensor([[np.int64(783)]], [[1]], place)
category_id = fluid.create_lod_tensor(
    [np.array(
        [10, 8, 9], dtype='int64')], [[3]], place)
movie_title = fluid.create_lod_tensor(
    [np.array(
        [1069, 4140, 2923, 710, 988], dtype='int64')], [[5]], place)

**Comment by hutuxian** [comment]
Fixed: https://github.com/PaddlePaddle/book/pull/773
