### ISSUE TITLE
PaddleDetection retinanet50、101训练好的模型，预测时显存溢出

### ISSUE THREAD

**Issue by gilbert1989** [PaddlePaddle/Paddle#18619]
- 版本、环境信息：
    1）PaddlePaddle版本：v1.5
    2）GPU：p4
    3）系统环境：官方docker 

- 复现信息：python tools/infer.py --config=configs/retinanet_r50_fpn_1x.yml --infer_dir=dataset/coco/test/
- 问题描述：batch_size=1,训练和eval没有问题，infer.py进行预测时，提示显存问题。

W0712 10:46:53.930126  6443 system_allocator.cc:121] Cannot malloc 6647.97 MB GPU memory. Please shrink FLAGS_fraction_of_gpu_memory_to_use or FLAGS_initial_gpu_memory_in_mb or FLAGS_reallocate_gpu_memory_in_mbenvironment variable to a lower value. Current FLAGS_fraction_of_gpu_memory_to_use value is 0.92. Current FLAGS_initial_gpu_memory_in_mb value is 0. Current FLAGS_reallocate_gpu_memory_in_mb value is 0
F0712 10:46:53.930470  6443 legacy_allocator.cc:184] Cannot allocate 33.750000MB in GPU 0, available 639.375000MB, total 7.428101GB, GpuMinChunkSize 256.000000B, GpuMaxChunkSize 6.492160GB, GPU memory used: 6.464097GB
*** Check failure stack trace: ***
    @     0x7ffa1e6f1f6d  google::LogMessage::Fail()
    @     0x7ffa1e6f5a1c  google::LogMessage::SendToLog()
    @     0x7ffa1e6f1a93  google::LogMessage::Flush()
    @     0x7ffa1e6f6f2e  google::LogMessageFatal::~LogMessageFatal()
    @     0x7ffa207435a8  paddle::memory::legacy::Alloc<>()
    @     0x7ffa207438c5  paddle::memory::allocation::LegacyAllocator::AllocateImpl()
    @     0x7ffa20737985  paddle::memory::allocation::AllocatorFacade::Alloc()
    @     0x7ffa20737b0a  paddle::memory::allocation::AllocatorFacade::AllocShared()
    @     0x7ffa2030692c  paddle::memory::AllocShared()
    @     0x7ffa2070a784  paddle::framework::Tensor::mutable_data()
    @     0x7ffa1fef53a0  paddle::operators::ElementwiseAddKernel<>::Compute()
    @     0x7ffa1fef5973  _ZNSt17_Function_handlerIFvRKN6paddle9framework16ExecutionContextEEZNKS1_24OpKernelRegistrarFunctorINS0_8platform9CUDAPlaceELb0ELm0EINS0_9operators20ElementwiseAddKernelINS7_17CUDADeviceContextEfEENSA_ISB_dEENSA_ISB_iEENSA_ISB_lEENSA_ISB_NS7_7float16EEEEEclEPKcSK_iEUlS4_E_E9_M_invokeERKSt9_Any_dataS4_
    @     0x7ffa2067b5f7  paddle::framework::OperatorWithKernel::RunImpl()
    @     0x7ffa2067b9d1  paddle::framework::OperatorWithKernel::RunImpl()
    @     0x7ffa20678fdc  paddle::framework::OperatorBase::Run()
    @     0x7ffa1e73694e  paddle::framework::Executor::RunPreparedContext()
    @     0x7ffa1e739a1f  paddle::framework::Executor::Run()
    @     0x7ffa1e59b22d  _ZZN8pybind1112cpp_function10initializeIZN6paddle6pybindL22pybind11_init_core_avxERNS_6moduleEEUlRNS2_9framework8ExecutorERKNS6_11ProgramDescEPNS6_5ScopeEibbRKSt6vectorISsSaISsEEE85_vIS8_SB_SD_ibbSI_EINS_4nameENS_9is_methodENS_7siblingEEEEvOT_PFT0_DpT1_EDpRKT2_ENUlRNS_6detail13function_callEE1_4_FUNES10_
    @     0x7ffa1e5dcb96  pybind11::cpp_function::dispatcher()
    @           0x4c5326  PyEval_EvalFrameEx
    @           0x4b9b66  PyEval_EvalCodeEx
    @           0x4c1f56  PyEval_EvalFrameEx
    @           0x4b9b66  PyEval_EvalCodeEx
    @           0x4c17c6  PyEval_EvalFrameEx
    @           0x4b9b66  PyEval_EvalCodeEx
    @           0x4c1f56  PyEval_EvalFrameEx
    @           0x4b9b66  PyEval_EvalCodeEx
    @           0x4eb69f  (unknown)
    @           0x4e58f2  PyRun_FileExFlags
    @           0x4e41a6  PyRun_SimpleFileExFlags
    @           0x4938ce  Py_Main
    @     0x7ffa5b6ed830  __libc_start_main
Aborted

**Comment by wopeizl** [comment]
检查一下显卡是不是被其它程序占用了

**Comment by jasonlbx13** [comment]
paddlepaddle默认预占用92%的显存
建议在运行程序前
在shell中进行如下配置:
export FLAGS_eager_delete_tensor_gb=0.0
export FLAGS_fast_eager_deletion_mode=1
export FLAGS_sync_nccl_allreduce=1
export FLAGS_selected_gpus=0        # which GPU to use
export CUDA_VISIBLE_DEVICES=0
export FLAGS_fraction_of_gpu_memory_to_use=0.5
