### ISSUE TITLE
Typing out the specific error types of calling CUDA API

### ISSUE THREAD

**Issue by zhwesky2010** [PaddlePaddle/Paddle#18624]
Error log is currently only prompting the call to the CUDA API to fail. You can't see the detailed error information. It's not good for debug. Optimize it as follows:
Typing out the specific error types of calling CUDA API and prompting users to go to nvidia's official website to see the error value explanation.

**Comment by wopeizl** [comment]
感谢建议，我们会在易用性中加以改进
