### ISSUE TITLE
一机多卡模型训练hang住【复现】

### ISSUE THREAD

**Issue by Bond-H** [PaddlePaddle/Paddle#18629]
- 版本、环境信息：
 1）PaddlePaddle版本：1.4.1
 3）GPU：K40m，Cuda8.0，cuDNN6.2, nccl_2.0.5
 4）系统环境：CentOS6.3， Python2.7
- 问题描述
 单机单卡模型能正常训练，单机多卡模式在训练迭代多个batch后会hang住，同时没有报错信息。

上述情况的复现代码如下所示：
 ```
 git clone https://github.com/Bond-SYSU/models.git
 cd models/PaddleNLP/lexical_analysis
 sh run.sh               # 单机单卡模式
 sh run_parrallel.sh     # 单机多卡模式
 ```

**Comment by Shixiaowei02** [comment]
如hi回复，已由 paddle cloud 同学对接。

**Comment by chengduoZH** [comment]
你装的是什么版本的1.4.1.post85 or 1.4.1.post87 ?
nccl版本是什么？

**Comment by Bond-H** [comment]
从新安装paddle1.5.0.post97的环境，问题已解决
