### ISSUE TITLE
data与feed_list不匹配

### ISSUE THREAD

**Issue by zq19** [PaddlePaddle/Paddle#18636]
这是出错信息：
 Traceback (most recent call last)<ipython-input-33-06c35278f4ac> in <module>
      1 if __name__ == '__main__':
      2     init_log_config()
----> 3     train()
<ipython-input-32-d79348923423> in train()
     52             print(data['image'][0])
     53             loss, acc1, pred_ot = exe.run(train_program,
---> 54                                           feed=feeder.feed(data),
     55                                           fetch_list=train_fetch_list)
     56             print(loss,acc1)
/opt/conda/envs/python35-paddle120-env/lib/python3.5/site-packages/paddle/fluid/data_feeder.py in feed(self, iterable)
    280             assert len(each_sample) == len(converter), (
    281                 "The number of fields in data (%s) does not match " +
--> 282                 "len(feed_list) (%s)") % (len(each_sample), len(converter))
    283             for each_converter, each_slot in six.moves.zip(converter,
    284                                                            each_sample):
AssertionError: The number of fields in data (5) does not match len(feed_list) (2)
我的data信息：
len(data)=2
data.keys()=['image','label']
data['image'][0]:dim: 1, 3, 224, 224
	layout: NCHW
	dtype: float
	data: [0.00392157 ............]

data['label']:lod: {}
	dim: 30, 1
	layout: NCHW
	dtype: int64_t
	data: [0 0 0 0 0 0 2 0 0 0 0 4 0 2 0 0 0 4 0 0 0 4 0 2 2 1 2 0 0 0]

这里是feed的信息：
feeder = fluid.DataFeeder(feed_list=[image, label], place=place,program=train_program)
       batch_reader = feeder.decorate_reader(paddle.batch(train_data_generator(train_images_dir),
                                batch_size=30,
                                drop_last=True),multi_devices=False)

**Comment by zhhsplendid** [comment]
嗨，zq，我们看了你更多的代码，可能不是数据feed的问题，你可以尝试恢复原来的feed方式。有可能是program设置问题：

<img width="974" alt="1a60d86495b7edcf6d0779afd1b860b1" src="https://user-images.githubusercontent.com/7913861/61201743-07988300-a718-11e9-83fd-4b19b772a436.png">

在resnet.context()里返回了一个resnet_program，从你的代码看上去这个program是个main program，因此没初始化startup_program会导致一些resnet里的参数没被初始化。

解决方法：不知道你是不是把整个resnet和你后面增加的fc层弄成一个网络跑。如果那是你的意图的话，那么删除开头红框的train_prog = fluid.Program() 和 train_startup = fluid.Program()，然后将第二个红框的startup_program = fluid.Program() 改为 startup_program = fluid.default_startup_program()，这样resnet的参数才会在startup_program中被初始化。

背景知识：
Program的概念为往paddle里增加op和var，好构建计算图。其中startup_program用来初始化参数。main_program用来跑计算程序。在你之前的代码里，with fluid.program_guard 用于往指定program里添加算子和op，没有with设置时会自动往default startup/main program里添加。因为你之前resnet.context不在with语句里，所以resnet的算子会被添加进default startup program，你重新startup_program = fluid.Program()相当于重启了一个program，把resnet的变量舍弃掉了，不会初始化。

**Comment by zq19** [comment]
您好，非常感谢花时间帮助我来解决问题，按照您说的方法改了之后，还是没效果
def train():
    logger.info("create prog success")
    logger.info("build input custom reader and data feeder")
    
    
    place = fluid.CUDAPlace(0)
     # 选取不同的网络
    logger.info("build newwork")

    input_dict, output_dict, resnet_program = resnet.context()
    
    train_program = resnet_program
    startup_program = fluid.default_startup_program()
    with fluid.program_guard(train_program,startup_program):
        # 定义输入数据的占位符
        image = fluid.layers.data(name='image', shape=[3,224,224], dtype='float32')
        label = fluid.layers.data(name='label', shape=[1], dtype='int64')
        feature_map = output_dict['feature_map'][0]
        flatten1 = fluid.layers.flatten(x=feature_map, axis=0)
        out = fluid.layers.fc(input=flatten1, size=5, act='softmax')
        feeder = fluid.DataFeeder(feed_list=[image, label], place=place,program=train_program)
        batch_reader = paddle.batch(train_data_generator(train_images_dir),
                                batch_size=30,
                                drop_last=True)
        # 定义损失
        cost = fluid.layers.cross_entropy(out, label)
        avg_cost = fluid.layers.mean(x=cost)
        acc_top1 = fluid.layers.accuracy(input=out, label=label, k=1)
        # 选取不同的优化器
        optimizer = fluid.optimizer.RMSProp(learning_rate=1e-3).minimize(avg_cost)
    exe = fluid.Executor(place)
    startup_program.random_seed = 1
    exe.run(startup_program)
    train_fetch_list = [avg_cost.name, acc_top1.name, out.name]

**Comment by zhhsplendid** [comment]
错误一样吗？还是报tensor holder_为空错误？
