### ISSUE TITLE
增量train的时候怀疑没有成功初始化init的模型

### ISSUE THREAD

**Issue by sitongchen** [PaddlePaddle/Paddle#18639]
为使您的问题得到快速解决，在建立Issues前，请您先通过如下方式搜索是否有相似问题:【搜索issue关键字】【使用labels筛选】【官方文档】

job_version="paddle-fluid-v1.2.0"
config.ini中定义：
init_model_path=/app/ecom/fcr/chensitong0/fluid/cross_domain/output/model_/997a2568-e8aa-5519-84fb-247a0c0aac49/job-0bb5d2ac6a4d85ff/output/rank-00000/batch-3500
这里batch-3500文件夹就是上次任务train到auc:0.71的output
然后加载再次训练的时候auc又从0.5开始训，包括auc上涨的速度和上次训都一样
怀疑没有成功初始化，不知道咋排查这个

**Comment by sitongchen** [comment]
第一次任务：
http://10.182.78.16:8900/fileview.html?path=/home/disk1/normandy/maybach/app-user-20190712173920-4503/
第二次任务（怀疑第一次任务的output没有初始化成功）：
http://10.182.17.141:8900/fileview.html?path=/home/disk1/normandy/maybach/app-user-20190714140743-5642/

**Comment by zhhsplendid** [comment]
增量训练时，你是用什么load，save api呢？

相关文档：
https://www.paddlepaddle.org.cn/documentation/docs/zh/1.5/user_guides/howto/training/save_load_variables.html#id8

能否先确认一下使用了正确的存储/载入模型api？

**Comment by AWSWXY** [comment]
我这里遇到了相同的问题。已经参照api 存储 载入模型。
版本：fluid1.4.1
任务运行日志：http://10.87.106.23:8900/fileview.html?path=/home/disk1/normandy/maybach/app-user-20190716103121-11570/
说明：init路径下auc为0.69 训练时第一个batch auc从0.5开始。
代码线下提供。
