### ISSUE TITLE
关于conv2d函数中自定义卷积核疑问

### ISSUE THREAD

**Issue by singlinhaha** [PaddlePaddle/Paddle#18630]
你好,我想请问一下,怎么往conv2d函数传进去自定义的卷积核,而不是采用随机初始化,传进去的卷积核是计算过程某一中间变量,类型是Tensor

**Comment by singlinhaha** [comment]
在复现SiameseRPN的时候遇到这个问题，需要将一个中间的tensor变量作为卷积核，和另外一个tensor变量进行卷积计算，但是发现paddlepaddle好像没办法自定义卷积核

**Comment by Shixiaowei02** [comment]
请问你是在预测还是训练遇到的问题，是使用c++还是python呢？

**Comment by singlinhaha** [comment]
你好,我是在训练的时候遇到这个问题,在搭建网络的时候找不到对应的api实现将一个tensor变量作为卷积核，和另外一个tensor变量进行卷积计算,我用的是python

**Comment by singlinhaha** [comment]
> 请问你是在预测还是训练遇到的问题，是使用c++还是python呢？

你好,我是在训练的时候遇到这个问题,在搭建网络的时候找不到对应的api实现将一个tensor变量作为卷积核，和另外一个tensor变量进行卷积计算,我用的是python

**Comment by Shixiaowei02** [comment]
> > 请问你是在预测还是训练遇到的问题，是使用c++还是python呢？
> 
> 你好,我是在训练的时候遇到这个问题,在搭建网络的时候找不到对应的api实现将一个tensor变量作为卷积核，和另外一个tensor变量进行卷积计算,我用的是python

是的，的确没有现成的api，需要更新模型文件实现这个功能。

**Comment by singlinhaha** [comment]
> > > 请问你是在预测还是训练遇到的问题，是使用c++还是python呢？
> > 
> > 
> > 你好,我是在训练的时候遇到这个问题,在搭建网络的时候找不到对应的api实现将一个tensor变量作为卷积核，和另外一个tensor变量进行卷积计算,我用的是python
> 
> 是的，的确没有现成的api，需要更新模型文件实现这个功能。

是不是说在1.5版本下没法实现这个功能,只能等以后版本更新?

**Comment by Shixiaowei02** [comment]
> > > > 请问你是在预测还是训练遇到的问题，是使用c++还是python呢？
> > > 
> > > 
> > > 你好,我是在训练的时候遇到这个问题,在搭建网络的时候找不到对应的api实现将一个tensor变量作为卷积核，和另外一个tensor变量进行卷积计算,我用的是python
> > 
> > 
> > 是的，的确没有现成的api，需要更新模型文件实现这个功能。
> 
> 是不是说在1.5版本下没法实现这个功能,只能等以后版本更新?

是的。

**Comment by Shixiaowei02** [comment]
您的这个动态更新权重需求我们内部核对确认一下。

**Comment by singlinhaha** [comment]
> 您的这个动态更新权重需求我们内部核对确认一下。

好的,感谢你的回答!
