### ISSUE TITLE
embeding使用is_distributed参数core dump

### ISSUE THREAD

**Issue by lexy0093** [PaddlePaddle/Paddle#18632]
网络结构：
        label = fluid.layers.data(name='label', shape=[1], dtype='int64', lod_level=0)
        index = fluid.layers.data(name='index', shape=[1], dtype='int64', lod_level=1)
        feature = fluid.layers.data(name='feature', shape=[1], dtype='float32', lod_level=1)

        droped = fluid.layers.dropout(x=feature, dropout_prob=self.dropout_prob)
        emb = fluid.layers.embedding(input=index, size=[self.vocab_dim, self.emb_dim], is_sparse=True)
        stk = fluid.layers.expand(feature, expand_times = [1, 256])
        mm = fluid.layers.elementwise_mul(x=emb, y=stk)
        mm_fc = fluid.layers.sequence_pool(input=mm, pool_type='sum')
        fc1 = fluid.layers.relu(x=mm_fc)

        fc2 = fluid.layers.fc(input=fc1, size=self.hid_dim, act='relu')
        pred = fluid.layers.fc(input=[fc1, fc2], size=self.class_dim, act='softmax')

本地2个pserver，2个trainer进行模拟分布式环境，在embeding层使用is_distributed=True参数后报错：
F0715 10:51:13.525717 18176 grpc_client.cc:357] PrefetchRPC name:[prefetch_compress_out_tmp_1], ep:[127.0.0.1:6001], status:[-1] meets grpc error, error_code:14 error_message:Socket closed error_details:
*** Check failure stack trace: ***
    @     0x7f46c726ad9d  google::LogMessage::Fail()
    @     0x7f46c726e84c  google::LogMessage::SendToLog()
    @     0x7f46c726a8c3  google::LogMessage::Flush()
    @     0x7f46c726fd5e  google::LogMessageFatal::~LogMessageFatal()
    @     0x7f46c7cd7444  paddle::operators::distributed::GRPCClient::Proceed()
    @       0x318eab6470  (unknown)
    @       0x318b207851  (unknown)
    @       0x318aee767d  (unknown)
    @              (nil)  (unknown)

**Comment by seiriosPlus** [comment]
看你的网络配置没有使用 `is_distributed=True`

**Comment by lexy0093** [comment]
使用参数is_distributed的原因是：在paddle-cloud上运行时总是在一轮训练结束时，更新参数到pserver上出现以下错误：
F0715 03:05:32.021452 25078 grpc_client.cc:408] GetRPC name:[fc_0.b_0], ep:[10.73.182.22:62000], status:[-1] meets grpc error, error_code:4 error_message:Deadline Exceeded error_details:
*** Check failure stack trace: ***
    @     0x7f610fefac0d  google::LogMessage::Fail()
    @     0x7f610fefe6bc  google::LogMessage::SendToLog()
    @     0x7f610fefa733  google::LogMessage::Flush()
    @     0x7f610feffbce  google::LogMessageFatal::~LogMessageFatal()
    @     0x7f6110a0230a  paddle::operators::distributed::GRPCClient::Proceed()
    @     0x7f61647c18a0  execute_native_thread_routine
    @     0x7f616ce7f1c3  start_thread
    @     0x7f616c4a712d  __clone
    @              (nil)  (unknown)

**Comment by lexy0093** [comment]
> 看你的网络配置没有使用 `is_distributed=True`

网络实际配置是使用了的，只是这边摘出来说而已

**Comment by seiriosPlus** [comment]
> 使用参数is_distributed的原因是：在paddle-cloud上运行时总是在一轮训练结束时，更新参数到pserver上出现以下错误：
> F0715 03:05:32.021452 25078 grpc_client.cc:408] GetRPC name:[fc_0.b_0], ep:[10.73.182.22:62000], status:[-1] meets grpc error, error_code:4 error_message:Deadline Exceeded error_details:
> *** Check failure stack trace: ***
> @ 0x7f610fefac0d google::LogMessage::Fail()
> @ 0x7f610fefe6bc google::LogMessage::SendToLog()
> @ 0x7f610fefa733 google::LogMessage::Flush()
> @ 0x7f610feffbce google::LogMessageFatal::~LogMessageFatal()
> @ 0x7f6110a0230a paddle::operators::distributed::GRPCClient::Proceed()
> @ 0x7f61647c18a0 execute_native_thread_routine
> @ 0x7f616ce7f1c3 start_thread
> @ 0x7f616c4a712d __clone
> @ (nil) (unknown)

是在第一轮训练结束以后进行了评估么？

**Comment by lexy0093** [comment]
第一轮训练结束后，未看到对Test data的数据评估就出现了问题。并且已设置FLAGS_rpc_deadline=6000000 超时时间，怀疑由于参数过大造成

**Comment by seiriosPlus** [comment]
参数过大不是这个错误

**Comment by seiriosPlus** [comment]
> 第一轮训练结束后，未看到对Test data的数据评估就出现了问题。并且已设置FLAGS_rpc_deadline=6000000 超时时间，怀疑由于参数过大造成

你把test关掉试试， 如果确认问题了再说后续的解决方法。

**Comment by lexy0093** [comment]
为什么本地模拟分布式时，使用is_distributed会报上述错误呢？

**Comment by lexy0093** [comment]
> 为什么本地模拟分布式时，使用is_distributed会报上述错误呢？

这个找到原因了，本地运行的脚本中pserver和trainer网络都应该添加上参数is_distributed，而我只添加了trainer导致
