### ISSUE TITLE
关于验证的时候dropout层的梯度问题

### ISSUE THREAD

**Issue by zq19** [PaddlePaddle/Paddle#18647]
出错点：
```shell
t recent call last)<ipython-input-8-e2038d08f664> in <module>
      1 if __name__ == '__main__':
      2     init_log_config()
----> 3     train_val()
<ipython-input-7-a9f48a063fd1> in train_val()
     84             loss, acc1 = exe.run(program=val_main_program,（clone自默认主程序）
     85                                           feed=feeder.feed(data),
---> 86                                           fetch_list=[avg_cost, acc_top1])
出错信息：
C++ Callstacks: 
Enforce failed. Expected ctx->Attrs().Get<bool>("is_test") == false, but received ctx->Attrs().Get<bool>("is_test"):1 != false:0.
GradOp is only callable when is_test is false at [/paddle/paddle/fluid/operators/dropout_op.cc:108]

```

网络dropout层：
```python
block6_dropout = fluid.layers.dropout(x=block5_pool, dropout_prob=0.4)
        
block6_fc1 = fluid.layers.fc(input=block6_dropout,
                                     size=fc_size,
                                     act='relu')
```

**Comment by zq19** [comment]
训练：
for step_id, data in enumerate(train_reader()):
            t1 = time.time()
            loss, acc1 = exe.run(program=fluid.default_main_program(),
                                          feed=feeder.feed(data),
                                          fetch_list=[avg_cost, acc_top1])

验证：
for step_id, data in enumerate(validation_reader()):
            t1 = time.time()
            loss, acc1 = exe.run(program=val_main_program,
                                          feed=feeder.feed(data),
                                          fetch_list=[avg_cost, acc_top1])

**Comment by ysh329** [comment]
> 出错点：
> 
> ```shell
> t recent call last)<ipython-input-8-e2038d08f664> in <module>
>       1 if __name__ == '__main__':
>       2     init_log_config()
> ----> 3     train_val()
> <ipython-input-7-a9f48a063fd1> in train_val()
>      84             loss, acc1 = exe.run(program=val_main_program,（clone自默认主程序）
>      85                                           feed=feeder.feed(data),
> ---> 86                                           fetch_list=[avg_cost, acc_top1])
> 出错信息：
> C++ Callstacks: 
> Enforce failed. Expected ctx->Attrs().Get<bool>("is_test") == false, but received ctx->Attrs().Get<bool>("is_test"):1 != false:0.
> GradOp is only callable when is_test is false at [/paddle/paddle/fluid/operators/dropout_op.cc:108]
> ```
> 
> 网络dropout层：
> 
> ```python
> block6_dropout = fluid.layers.dropout(x=block5_pool, dropout_prob=0.4)
>         
> block6_fc1 = fluid.layers.fc(input=block6_dropout,
>                                      size=fc_size,
>                                      act='relu')
> ```

您好，我看了下您的问题：
```shell
Enforce failed. Expected ctx->Attrs().Get<bool>("is_test") == false, but received ctx->Attrs().Get<bool>("is_test"):1 != false:0.
GradOp is only callable when is_test is false at [/paddle/paddle/fluid/operators/dropout_op.cc:108]
```
这里dropout_op的参数检查失败了，怀疑是op的参数填写不对，建议您先检查`is_test`的值是否正确，预期是`0`，但是给出的是`1`
