### ISSUE TITLE
id类特征进行embedding

### ISSUE THREAD

**Issue by lps683** [PaddlePaddle/Paddle#18657]
求问一下，我现在有一些id类特征，id为int64类型
我相对这些特征进行embedding，需要指定dict_size
那我是否只需要获得id的最大值+1（不超过int64）设置为dictsize即可？
还是需要将id映射成0-n的连续数值么？
如果不做映射是否会影响模型性能，有没有什么推荐的做法呢？
谢谢

**Comment by ysh329** [comment]
您好，可以参考咱们[paddlepaddle/models](https://github.com/PaddlePaddle/models)下相关的embedding模型的使用
