### ISSUE TITLE
normalinitializer随机种子的作用是什么？

### ISSUE THREAD

**Issue by DDDivano** [PaddlePaddle/Paddle#18653]
https://www.paddlepaddle.org.cn/documentation/docs/zh/1.5/api_cn/initializer_cn.html#normalinitializer
固定随机种子之后，在不同的环境，maccpu，linux cpu gpu下跑得到的权重结果也是不同的。
这个是符合预期的吗？
linux cpu
![image](https://user-images.githubusercontent.com/10734244/61293528-7c49eb00-a806-11e9-99b1-4e182aa50930.png)
linux gpu
![image](https://user-images.githubusercontent.com/10734244/61293536-823fcc00-a806-11e9-9e7d-b060ba554fed.png)
mac cpu
![image](https://user-images.githubusercontent.com/10734244/61293575-9683c900-a806-11e9-80b3-c7363be870f2.png)

**Comment by ysh329** [comment]
请问一下，同一台机器上的同一个Device（如CPU、GPU）下，固定随机数种子，你的结果一样嘛

**Comment by DDDivano** [comment]
> 请问一下，同一台机器上的同一个Device（如CPU、GPU）下，固定随机数种子，你的结果一样嘛

不一样

**Comment by DDDivano** [comment]
> 请问一下，同一台机器上的同一个Device（如CPU、GPU）下，固定随机数种子，你的结果一样嘛

同一台机器上同一个硬件是一样的

**Comment by ysh329** [comment]
> > 请问一下，同一台机器上的同一个Device（如CPU、GPU）下，固定随机数种子，你的结果一样嘛
> 
> 同一台机器上同一个硬件是一样的

同一台机器上同一个硬件是一样的，符合预期。

额，如果说作用的话，说明里写了：随机正态（高斯）分布初始化器
