### ISSUE TITLE
Fluid gets poor performance when training in CPU, compared with TF.

### ISSUE THREAD

**Issue by TomorrowIsAnOtherDay** [PaddlePaddle/Paddle#18665]
Code for reproducing the performance could be found [here](
http://gitlab.baidu.com/zhoubo01/paddle-tensorflow), with TF and Paddle version.
As we have observed in our machine, TF runs twice faster than Fluid.

**Comment by luotao1** [comment]
1. 请问使用什么型号的CPU？用`cat /proc/cpuinfo`看下。
2. 请问使用什么版本的paddle，调用了MKL库么？
3. `exec_strategy.num_threads = 48`，从代码看，使用了48个线程。如果CPU core没有超过48个，建议减少该数值。
4. 运行时，查看下`top`利用率，看下paddle和tf对应的CPU利用率分别是多少？

**Comment by luotao1** [comment]
> TF runs twice faster than Fluid

可以贴一下，目前TF和Fluid的运行时间么？以及您怎么测时间的命令，方便我们复现。

**Comment by TomorrowIsAnOtherDay** [comment]
感谢答复。
1. Intel(R) Xeon(R) Gold 5117 CPU @ 2.00GHz
2. paddle版本1.50，通过命令`pip install paddlepaddle-gpu` 安装的。不清楚是否使用的mkl库。
3. 尝试过更少数量的cpu，但是效果没有提升。
4. 建议开发者运行我们提供的代码自行查看。

Q：可以贴一下，目前TF和Fluid的运行时间么？以及您怎么测时间的命令，方便我们复现。
A：根据tqdm里面显示的时间来看的，跑1000个batch的训练耗时。

**Comment by TomorrowIsAnOtherDay** [comment]
在这里贴一下我们本地的性能指标：
fluid: 40 batch/秒
tensorflow: 80 batch / 秒
tensorflow 版本：1.13.1   
安装途径： `pip install tensorflow==1.13.1`

**Comment by luotao1** [comment]
我在E5-2620 v3机器上复现如下。

- 直接运行 http://gitlab.baidu.com/zhoubo01/paddle-tensorflow。

|   | TF  | Paddle  | 
|---|---|---|
| 速度（iteraion/s）  | 62.98  | 25.23  | 
| CPU利用率  |  670% | 109%  |  

由于TF的默认CPU利用率是超过Paddle的，所以速度快。Paddle默认`CPU_NUM=1`。

- 如果增大Paddle的CPU利用率，如`export CPU_NUM=6`

|   | TF  | Paddle  | 
|---|---|---|
| 速度（iteraion/s）  | 62.98  | 62.69  | 
| CPU利用率  |  670% | 404%  | 

在Paddle的CPU利用率小于TF的情况下，速度基本是打平的。

**Comment by TomorrowIsAnOtherDay** [comment]
感谢回复：）
我们这边等明天腾出5117机器之后会根据你的建议，重跑下指标

**Comment by luotao1** [comment]
根据https://www.tensorflow.org/guide/performance/overview#tuning_mkl_for_the_best_performance 
![image](https://user-images.githubusercontent.com/6836917/61634084-1f957700-acc3-11e9-99be-9cfd573d0175.png)
可知TF 默认是全部打满的，类似Issue：https://github.com/tensorflow/tensorflow/issues/7521

因此，将TF的CPU利用率也设成1.
```
#sess = tf.InteractiveSession()
config = tf.ConfigProto(intra_op_parallelism_threads=1, inter_op_parallelism_threads=1, device_count = {'CPU': 1})
sess = tf.InteractiveSession(config=config)
```
结果如下：

|   | TF  | Paddle  | 
|---|---|---|
| 速度（iteraion/s）  | 14.81  | 25.23  | 
| CPU利用率  |  102% | 109%  | 

Paddle单线程CPU速度是快于TF的。

**Comment by TomorrowIsAnOtherDay** [comment]
关于性能问题：
- 添加了CPU的设定之后性能是打平TF的
 `export CPU_NUM=6`
- TF是默认打开多线程的，paddle为什么默认只开了单线程呢？

**Comment by TomorrowIsAnOtherDay** [comment]
再次**感谢**@luotao1 协助，对我们的调研帮助太大了。我们之前只能通过并行的优势和其他框架速度打平，现在底层计算框架的性能也优化了，在速度上就可以全方位战胜他们了。
也希望paddle的同学可以认真**考虑下**默认打开多线程计算，从用户的角度而言，我暂时没想到默认开启多CPU运算的坏处。

**Comment by athulvingt** [comment]
how to change CPU_NUM?

**Comment by TomorrowIsAnOtherDay** [comment]
e.g, export CPU_NUM=6 
@athulvingt

**Comment by athulvingt** [comment]
just type this in command line before running the program?
This what I did, but nothing much happend, it was still running on single CPU thread
`$ export CPU_NUM=6`
`$ python3 deploy/python/infer.py --model=models/retinanet_r50_fpn_1x --video_file=test2.webm`

Am I doing something wrong? @TomorrowIsAnOtherDay

**Comment by athulvingt** [comment]
You said something about reproducing it on TF, I tried to open your link. But it seems to be a dead end. If you have the code could you please send me to daredeviles888@gmail.com @TomorrowIsAnOtherDay 

Thank you

**Comment by TomorrowIsAnOtherDay** [comment]
It's our internal website for code management. I paste the code here. It contains two files: test_speed.py and forward_model.py .
```python
#!/usr/bin/env python
# coding=utf8
# File: test_speed.py
from forward_model import FlappyBirdModel
from paddle import fluid
from tqdm import tqdm
import numpy as np

def main():
    model = FlappyBirdModel(2)
    train_program = fluid.Program()
    with fluid.program_guard(train_program):
        obs = fluid.layers.data(name='obs', shape=[4, 80, 80], dtype='float32')
        action = fluid.layers.data(name='action', shape=[2], dtype='int32')
        target = fluid.layers.data(name='target', shape=[], dtype='float32')

        Q = model.value(obs)
        action = fluid.layers.cast(action, dtype='float32')
        all_Q = fluid.layers.elementwise_mul(action, Q)
        pred_Q = fluid.layers.reduce_sum(all_Q, dim=1)

        cost = fluid.layers.square_error_cost(pred_Q, target)
        cost = fluid.layers.reduce_mean(cost)

        optimizer = fluid.optimizer.Adam(1e-6)
        optimizer.minimize(cost)

    print('hhhhhhhhhhhhh', cost.name)
    exec_strategy = fluid.ExecutionStrategy()
    exec_strategy.num_threads = 48

    build_strategy = fluid.BuildStrategy()
    build_strategy.reduce_strategy = fluid.BuildStrategy.ReduceStrategy.Reduce

    exe = fluid.ParallelExecutor(
        use_cuda=False,
        loss_name=cost.name,
        main_program=train_program,
        build_strategy=build_strategy,
        exec_strategy=exec_strategy)
    normal_exe = fluid.Executor(fluid.CPUPlace())
    normal_exe.run(fluid.default_startup_program())

    # test speed
    BATCH_SIZE = 32
    ACTIONS = 2
    data = [np.random.normal(size=[BATCH_SIZE, 4, 80, 80]).astype('float32'),
            np.random.randint(size=[BATCH_SIZE, ACTIONS], low=0, high=2).astype('int32'),
            np.random.random(size= [BATCH_SIZE]).astype('float32')]
    for i in tqdm(range(1000)):
        exe.run(fetch_list=[],
                feed={'obs': data[0],
                     'action':data[1],
                     'target':data[2]})
if __name__ == '__main__':
    main()
```

```python
#!/usr/bin/env python
# coding=utf8
# File: forward_model.py
import paddle.fluid.layers as layers

class FlappyBirdModel(object):
    def __init__(self, act_dim):
        self.act_dim = act_dim

    def value(self, obs):
        out = layers.conv2d(obs, num_filters=32, filter_size=8, stride=4, padding=2, act='relu')
        out = layers.pool2d(input=out, pool_size=2, pool_stride=2, pool_type='max')
        out = layers.conv2d(out, num_filters=64, filter_size=4, stride=2, padding=1, act='relu')
        out = layers.conv2d(out, num_filters=64, filter_size=3, stride=1, padding=1, act='relu')
        out = layers.flatten(out, axis=1)
        out = layers.fc(out, size=512, act='relu')
        out = layers.fc(out, size=self.act_dim)
        return out
```

**Comment by TomorrowIsAnOtherDay** [comment]
> just type this in command line before running the program?
> This what I did, but nothing much happend, it was still running on single CPU thread
> `$ export CPU_NUM=6`
> `$ python3 deploy/python/infer.py --model=models/retinanet_r50_fpn_1x --video_file=test2.webm`
> 
> Am I doing something wrong? @TomorrowIsAnOtherDay

Note that we should transfer the program using the compile API.

**Comment by athulvingt** [comment]
> > just type this in command line before running the program?
> > This what I did, but nothing much happend, it was still running on single CPU thread
> > `$ export CPU_NUM=6`
> > `$ python3 deploy/python/infer.py --model=models/retinanet_r50_fpn_1x --video_file=test2.webm`
> > Am I doing something wrong? @TomorrowIsAnOtherDay
> 
> Note that we should transfer the program using the compile API.

I exported the model and generated three files, is it transferring the program using the compile API, If not could you please explain how to do it?

I am very much thankful for your quick replies

**Comment by TomorrowIsAnOtherDay** [comment]
Here is an example of transferring the program:
https://github.com/PaddlePaddle/PARL/blob/5054efedd11b93fb34d289ec54a20f01e3156ea6/parl/core/fluid/plutils/compiler.py#L43
