### ISSUE TITLE
训练过程中持续有warning

### ISSUE THREAD

**Issue by sshilei** [PaddlePaddle/Paddle#18667]
W0717 14:40:15.249956 54863 init.cc:161] AVX is available, Please re-compile on local machine

![image](https://user-images.githubusercontent.com/18701471/61353095-81a84380-a8a1-11e9-87c7-a11f044ffcbe.png)

**Comment by MRXLT** [comment]
你好，可以提供一下训练的环境吗

**Comment by sshilei** [comment]
单独hi上提供，谢谢

**Comment by MRXLT** [comment]
重新编译paddle或者使用1.5版本的paddle可以解决
