### ISSUE TITLE
关于公开项目中测试与训练用的同一个main_program的问题

### ISSUE THREAD

**Issue by zq19** [PaddlePaddle/Paddle#18662]
项目地址：https://aistudio.baidu.com/aistudio/projectdetail/44338
![image](https://user-images.githubusercontent.com/50872563/61347148-5f58fa80-a88e-11e9-9ad2-f884be847aad.png)
按理来说测试程序应该为训练程序的clone.(for_test=True),请问这是怎么回事呢

**Comment by weiexcelpro** [comment]
您说的很对, 刚才已经修复了.
