### ISSUE TITLE
pyreader使用问题

### ISSUE THREAD

**Issue by TomorrowIsAnOtherDay** [PaddlePaddle/Paddle#18679]
在pyreader中，我的generator以batch的方式yield出来的，这种情况下怎么处理呢？

我看文档里面只有生成一条样本然后调用函数`decorate_batch_generator`来提供batch的数据的。

**Comment by Meiyim** [comment]
pyreader有3个decorate*  函数，确保找到你想用的方法

**Comment by TomorrowIsAnOtherDay** [comment]
看了源代码才找到，文档里面怎么没有提示这个，希望能修一下文档@Paddle同学
https://github.com/PaddlePaddle/Paddle/blob/41ab76e55baad03af2e57a160137b555b366812e/python/paddle/fluid/reader.py#L619

**Comment by zhhsplendid** [comment]
Hi, decorate_batch_generator是有文档的，链接在这

https://paddlepaddle.org.cn/documentation/docs/zh/1.5/api_cn/io_cn.html#decorate_sample_generator

抱歉，可能文档没让您容易找到，我们后面想办法优化文档。
