### ISSUE TITLE
可否可以自定义Python layer

### ISSUE THREAD

**Issue by tensor-tang** [PaddlePaddle/Paddle#1867]
如题
我看到有C++版的写新layer的文档，但是并没有说是否支持自定义Python layer。

**Comment by lcy-seso** [comment]
PaddlePaddle 目前支持一些基础的数学运算layer来完成一些简单的组合，https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/trainer_config_helpers/layer_math.py   更复杂的layer，还需要添加 C++ 代码。
