### ISSUE TITLE
使用c++接口的多线程，报segment fault

### ISSUE THREAD

**Issue by dancingpipi** [PaddlePaddle/Paddle#18689]
```c++
    DLOG(INFO) << "create main_predictor";
    std::unique_ptr<paddle::PaddlePredictor> main_predictor = CreatePaddlePredictor(config);
    predictors.emplace_back(std::move(main_predictor));

    DLOG(INFO) << "create multi predictors";
    for (int i = 1; i < multi_threads; ++i){
        predictors.emplace_back(std::move(main_predictor->Clone()));
    }
    DLOG(INFO) << "finish predictors";
```
报这个错误：
![image](https://user-images.githubusercontent.com/20511825/61483313-25dbd880-a9cf-11e9-82f3-40a0c1679151.png)

这是什么原因啊，无论是CPU还是GPU都不行。
当multi_threads值为1时，可以正常预测

**Comment by Superjomn** [comment]
确认下，Clone 是线程不安全的，比如在多线程启动前，predictors单线程创建完毕。

另外，把 core 的信息打出来看下，不排除内存啥是否超了

**Comment by Shixiaowei02** [comment]
@z13974509906 请把完整的代码发出来，说明依赖的 Paddle 版本，我们复现一下这个问题。

**Comment by Shixiaowei02** [comment]
非常抱歉，我们的文档给您带来了困扰。我们会尽快修复错误的使用示例。谢谢！

**Comment by Shixiaowei02** [comment]
问题解决，请参考 https://github.com/PaddlePaddle/FluidDoc/pull/1018 ，谢谢！

**Comment by dancingpipi** [comment]
> 确认下，Clone 是线程不安全的，比如在多线程启动前，predictors单线程创建完毕。
> 
> 另外，把 core 的信息打出来看下，不排除内存啥是否超了

确认是线程不安全的吗？我看源码clone是带锁的啊
```c++
std::unique_ptr<PaddlePredictor> AnalysisPredictor::Clone() {
  std::lock_guard<std::mutex> lk(clone_mutex_);
  auto *x = new AnalysisPredictor(config_);
  x->Init(scope_, inference_program_);
  return std::unique_ptr<PaddlePredictor>(x);
}

```

**Comment by Shixiaowei02** [comment]
目前代码实现保证了线程安全，但请在主线程使用 Clone 接口，在每个子线程内调用预测接口。Clone 不保证线程安全，实现可能发生变化。
