### ISSUE TITLE
fluid1.4 inference使用tensorrt找不到libnvinfer.so

### ISSUE THREAD

**Issue by dancingpipi** [PaddlePaddle/Paddle#18680]
系统：centos 7.5
gcc : 4.8.5
fluid版本：1.4

首先在官网上下载了TensorRT4.0的tar包，解压。
然后clone fluid1.4的源码，编译fluid1.4 inference库。

可以看到tensorrt是已经有了的。
![image](https://user-images.githubusercontent.com/20511825/61433363-abc33980-a965-11e9-821d-c992e890d707.png)

但是执行自己程序时，就报错：
![image](https://user-images.githubusercontent.com/20511825/61433419-c9909e80-a965-11e9-91c1-7e3357ae38e3.png)

LD_LIBRARY_PATH已经添加了：
![image](https://user-images.githubusercontent.com/20511825/61433464-f47af280-a965-11e9-8991-1aae3ba417dc.png)

请问要怎么解决这个问题啊。

**Comment by OliverLPH** [comment]
是做C++预测吗？那还需要再把 tensorrt的库文件跟预测代码联编一下
