### ISSUE TITLE
INT8 MKL-DNN performance regression problem

### ISSUE THREAD

**Issue by bingyanghuang** [PaddlePaddle/Paddle#18698]
Paddle develop branch INT8 performance regression problem has not been solved yet. This regression is caused by merged PR #17965 , commit number is 84bb45c054e34f53c290b63d1defd76ac5ab2f94 by @jczaja . Regression data is shown in the following table:
![image](https://user-images.githubusercontent.com/33643817/61521281-717b9a00-aa42-11e9-86db-4dfb8b9b5dec.png)
 Testing command line is `./paddle/fluid/inference/tests/api/test_analyzer_int8_image_classification --infer_model=third_party/inference_demo/int8v2/resnet50/model --infer_data=/~/.cache/paddle/dataset/int8/download/int8_full_val.bin --batch_size=1 --paddle_num_threads=1
`
You can change `--infer_model` with different model name `googlenet, mobilenetv1, mobilenetv2, resnet101, resnet50, vgg16, vgg19` for different benchmarks, refer to [int8v2_readme](https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/fluid/inference/tests/api/int8_mkldnn_quantization.md).

**Comment by bingyanghuang** [comment]
@wojtuss Please help add label `intel`. @jczaja Please investigate this problem. Thanks

**Comment by jczaja** [comment]
I found potential problem of performance regression eg. ConvInt8 is not prepared for Multi-threading and reusing stopped to work for int8 convolution. Problem will go away when conv fp32 and conv int8 
are unified. Meantime I will prepare fast fix (Wendsday EOD) to restore performance for int8.

**Comment by jczaja** [comment]
fixed in #18758
