### ISSUE TITLE
Paddle官方文档 环境变量FLAGS页面 整理建议

### ISSUE THREAD

**Issue by OliverLPH** [PaddlePaddle/Paddle#18697]
- 版本、环境信息
1）PaddlePaddle版本：请提供您的PaddlePaddle版本号，例如1.1
2）CPU/GPU：您是否使用GPU进行训练，如是，请提供您的CUDA和cuDNN版本号
3）系统环境：请您描述系统类型、版本，例如Mac OS 10.14
- 复现信息：如为报错，请给出复现环境、复现步骤
- 建议描述：

[1.5版本环境变量FLAGS](https://www.paddlepaddle.org.cn/documentation/docs/zh/1.5/flags_cn.html) 这个页面里面的环境变量太多了，且分类不太清楚，不熟悉的人用起来非常麻烦。新用户过来一看页面这么多变量就劝退了。

[v2版本参数设置](https://www.paddlepaddle.org.cn/documentation/docs/zh/0.12.0/howto/cmd_parameter/arguments_cn.html) 这里面虽然详细用法没有说得很清楚，但类别分出来看起来就会比较清晰。

而且1.5版本里面的环境变量有的可以在 config里面设置，这里面也没说。
比如 
FLAGS_fraction_of_gpu_memory_to_use 这个参数算比较常用了
<img width="687" alt="9f7db9e7dad2d41535cd816e0103826e" src="https://user-images.githubusercontent.com/14963836/61518988-696d2b80-aa3d-11e9-9cf2-589ec83091d8.png"> 我觉得还可以统一一下环境变量和配置文件里面参数的对应关系。

然后分类可以分出几类，比如按 GPU，CPU分类，分布式，训练，预测等相关的环境变量进行分类

**Comment by xsrobin** [comment]
多谢反馈，我们会参考您的建议进行优化。

**Comment by luotao1** [comment]
同求优化。
