### ISSUE TITLE
PR #18656 add unnecessary input in leaky_relu_grad op

### ISSUE THREAD

**Issue by sneaxiy** [PaddlePaddle/Paddle#18707]
PR #18656 adds unnecessary input in leaky_relu_grad op. Grad ops of activation ops would never need forward input `X` and forward output `Out` as their inputs, because `Out` can be always calculated by `X` in backward pass.

This changing would make the existing GPU memory reuse strategy not work. Please fix it asap. @grygielski .

**Comment by grygielski** [comment]
Could you explain to us why this change is causing a problems as it is only empty input label added without any parameters or so? We use it in MKL-DNN backend for hashing forward calculations to reuse it for grad computing. For that we need common factor to identify corresponding forward/backward pairs and we use Output("Out") as forward key part and Input("Out") as grad key part. This is why we need Input("Out") even if it is not used anywhere else.

**Comment by sneaxiy** [comment]
@grygielski The memory optimization strategy of Paddle during training relies on graph dependency analysis. If an op has additional unnecessary inputs, the strategy would think that the memory of these inputs cannot be reused or released before running this op. Thus, the additional unnecessary inputs would increase the GPU memory consumption.

**Comment by sneaxiy** [comment]
@grygielski If you only need a mapping between forward/backward pair, please use a better way to store this mapping, instead of adding unnecessary inputs in op.

**Comment by grygielski** [comment]
Would it be enough for you if we add #ifdef to check for PADDLE_WITH_MKLDNN flag and then based on that add or not additional Input? I guess that will work as long as you don't want to build paddle with both gpu and mkldnn.

**Comment by sneaxiy** [comment]
But the GPU whl package we release to users is often compiled with MKL. This method may not work.

**Comment by sneaxiy** [comment]
But the GPU whl package we release to users is often compiled with MKL. This method may not work.

**Comment by luotao1** [comment]
Maybe you can use `bool use_mkldnn = ctx.Attr<bool>("use_mkldnn");` to check it runtime?

**Comment by grygielski** [comment]
Ok, I will try to work it out during next work week

**Comment by sneaxiy** [comment]
@grygielski Thanks a lot! We should keep the protobuf description of op consistent in different compiling conditions, so that users can use the saved program either in Paddle compiled with MKL or not. In this way, using `#ifdef PADDLE_WITH_MKLDNN` may not be a good way to solve this problem.

**Comment by grygielski** [comment]
I agree with you but i also wanted to keep mkldnn functor and grad_functor as generic as possible. This is why i tried to avoid conditional cases for specific operators as it adds complexity for further mkldnn activation ops support. Hopefully I can find another, common, unique attribute that connects operator and its grad. Such thing will solve all problems for existing and future mkldnn activations.
