### ISSUE TITLE
pytorch的这段代码fluid怎么实现

### ISSUE THREAD

**Issue by HUSTLX** [PaddlePaddle/Paddle#18704]
![image](https://user-images.githubusercontent.com/12711390/61527867-fde08980-aa4f-11e9-9630-5c36bada2d07.png)
如题，pytorch的这段代码fluid怎么实现，输入input和inst可以认为是大小相同的图像，inst是图像的mask

**Comment by qingqing01** [comment]
@HUSTLX 目前看起来在静态图中，没有直接对应的实现，这段代码是比如插入网络接口中间的吗？ 如果是网络末端，是可以在Python里实现的
