### ISSUE TITLE
训练到第一轮就没有输出了，看日志可能是有问题，但不清楚是为什么

### ISSUE THREAD

**Issue by zhaoyang1708** [PaddlePaddle/Paddle#18719]
使用mpi训练到第一轮就没有输出了，看日志可能是有问题，但不清楚是为什么。求帮助

Mon Jul 22 10:23:43 2019[1,16]<stdout>:Traceback (most recent call last):
Mon Jul 22 10:23:43 2019[1,16]<stdout>:  File "train.py", line 726, in <module>
Mon Jul 22 10:23:43 2019[1,24]<stdout>:use_parallel_executor=bool(args.use_parallel_exe)
Mon Jul 22 10:23:43 2019[1,14]<stdout>:Traceback (most recent call last):
Mon Jul 22 10:23:43 2019[1,16]<stdout>:    use_parallel_executor=bool(args.use_parallel_exe)
Mon Jul 22 10:23:43 2019[1,16]<stdout>:  File "train.py", line 700, in train
Mon Jul 22 10:23:43 2019[1,16]<stdout>:    train_loop(main_program, trainer_id)
Mon Jul 22 10:23:43 2019[1,16]<stdout>:  File "train.py", line 613, in train_loop
Mon Jul 22 10:23:43 2019[1,16]<stdout>:    auc_var.name, auc_var_cos.name, cur_auc.name, cur_auc_cos.name])
Mon Jul 22 10:23:43 2019[1,16]<stdout>:  File "/home/disk1/normandy/maybach/app-user-20190719212232-10626/workspace/python27-gcc482/lib/python2.7/site-packages/paddle/fluid/parallel_executor.py", line 205, in run

**Comment by kuke** [comment]
这个日志没什么信息量，最后部分的输出是什么?

**Comment by zhaoyang1708** [comment]
> 这个日志没什么信息量，最后部分的输出是什么?

F0722 15:23:48.747640  3220 grpc_client.cc:408] GetRPC name:[fc1.w_0.block2], ep:[10.182.5.158:62004], status:[-1] meets grpc error, error_code:4 error_message:Deadline Exceeded error_details:
*** Check failure stack trace: ***
    @     0x7f838e732c0d  google::LogMessage::Fail()
    @     0x7f838e7366bc  google::LogMessage::SendToLog()
    @     0x7f838e732733  google::LogMessage::Flush()
    @     0x7f838e737bce  google::LogMessageFatal::~LogMessageFatal()
    @     0x7f838f337e0e  paddle::operators::distributed::GRPCClient::Proceed()
    @     0x7f839a8418a0  execute_native_thread_routine
    @     0x7f84351cd1c3  start_thread
    @     0x7f84347f512d  __clone
    @              (nil)  (unknown)
.//paddle/start_trainer.sh: line 111: 36630 Aborted                 python -u train.py --use_parallel_exe 1 --batch_size 4096 --cpu_num=8 --data_dir train_data --test_data_dir test_data
这是链接 http://10.182.22.152:8900/fileview.html?path=/home/disk1/normandy/maybach/app-user-20190719212232-10626/

**Comment by seiriosPlus** [comment]
可以尝试把infer先去掉， 看一下是不是由于infer时间过长导致超时

**Comment by zhaoyang1708** [comment]
> 可以尝试把infer先去掉， 看一下是不是由于infer时间过长导致超时

那这个不是训练脚本写错的原因是吧

**Comment by seiriosPlus** [comment]
不是脚本原因， fluid分布式这块机制需要优化

**Comment by zhaoyang1708** [comment]
> 不是脚本原因， fluid分布式这块机制需要优化

好的，十分感谢

**Comment by seiriosPlus** [comment]
先clouse了，后续优化会关联相应pr过来
