### ISSUE TITLE
numpy array multiply tensor

### ISSUE THREAD

**Issue by achao2013** [PaddlePaddle/Paddle#18712]
i have a numpy array "mask" ,  a tensor  involve gradient back propagation. their shape is the same.
 i want to know how to multiply them.
my code is as follows:
cost = fluid.layers.reduce_mean(fluid.layers.abs(label - out)*mask)
it's ok in tensorflow, but it fails in paddle:

  File "/home/work/.jumbo/lib/python2.7/site-packages/paddle/fluid/layers/math_op_patch.py", line 123, in __impl__
    self.block, value=other_var, dtype=lhs_dtype)
  File "/home/work/.jumbo/lib/python2.7/site-packages/paddle/fluid/layers/math_op_patch.py", line 51, in create_scalar
    return create_tensor(block, value, dtype, shape=[1])
  File "/home/work/.jumbo/lib/python2.7/site-packages/paddle/fluid/layers/math_op_patch.py", line 34, in create_tensor
    value = float(value)
TypeError: only size-1 arrays can be converted to Python scalars

**Comment by chengduoZH** [comment]
@achao2013  Can you post the complete code?

**Comment by achao2013** [comment]
it is modified based on the code of models/image_classification/train.py
@chengduoZH 
```
def net_config(image, model, args, is_train, label=0, y_a=0, y_b=0, lam=0.0):
............
vis_mask = imread('data/uv_vis_mask.png')/255.
weight_mask = imread('data/uv_weight_mask.png')/255.
vis_weight = np.tile(vis_mask[np.newaxis,np.newaxis, :,:], [batch_size, 3, 1,1])
weight = np.tile(weight_mask[np.newaxis,np.newaxis, :,:], [batch_size, 3, 1,1])
cost = fluid.layers.reduce_mean(fluid.layers.abs(label - out)*vis_weight*weight)
```

**Comment by chengduoZH** [comment]
@achao2013 
发生错误的地方是这里 `fluid.layers.abs(label - out)*vis_weight`
因为`fluid.layers.abs(label - out)`返回的是一个Variable，目前Variable只能与标量进行加减乘除，所以这里会报错。
另外，对于静态图，一旦计算图构建完成之后，每次迭代时，计算图都是一样的，但是对于每次迭代，batch_size是可以不同的，所以你这种构建模型的方式是有问题的。

**Comment by achao2013** [comment]
我试了下tensor：
vis_mask = imread('data/uv_vis_mask.png')/255.
                weight_mask = imread('data/uv_weight_mask.png')/255.

                vis_weight = np.tile(vis_mask[np.newaxis,np.newaxis, :,:], [batch_size, 3, 1,1])
                fluid.global_scope().var("vis_weight").get_tensor().set(vis_weight, fluid.CPUPlace())
                weight = np.tile(weight_mask[np.newaxis,np.newaxis, :,:], [batch_size, 3, 1,1])
                fluid.global_scope().var("weight").get_tensor().set(weight, fluid.CPUPlace())           
                cost = fluid.layers.reduce_mean(fluid.layers.abs(label - out)*fluid.global_scope().find_var("vis_weight").get_tensor()*fluid.global_scope().find_var("weight").get_tensor())
改成tensor以后还是有问题：
  File "train.py", line 271, in net_config
    cost = fluid.layers.reduce_mean(fluid.layers.abs(label - out)*fluid.global_scope().find_var("vis_weight").get_tensor()*fluid.global_scope().find_var("weight").get_tensor())
  File "/home/work/.jumbo/lib/python2.7/site-packages/paddle/fluid/layers/math_op_patch.py", line 123, in __impl__
    self.block, value=other_var, dtype=lhs_dtype)
  File "/home/work/.jumbo/lib/python2.7/site-packages/paddle/fluid/layers/math_op_patch.py", line 51, in create_scalar
    return create_tensor(block, value, dtype, shape=[1])
  File "/home/work/.jumbo/lib/python2.7/site-packages/paddle/fluid/layers/math_op_patch.py", line 34, in create_tensor
    value = float(value)
TypeError: float() argument must be a string or a number

这个该怎么解决呢 @chengduoZH

**Comment by chengduoZH** [comment]
@achao2013 你还是把你的完整模型发一下吧。
