### ISSUE TITLE
怎么使用resnet50和ernie模型训练图文相关性模型？

### ISSUE THREAD

**Issue by zhangqianjin** [PaddlePaddle/Paddle#18714]
我想用resnet50处理图片，抽取图片特征；用ernie抽取文本特征，把这两部分特征合并进入全连接层计算相关性，求例子？

**Comment by chengduoZH** [comment]
@zhangqianjin 你可以查看Paddle/book中推荐系统章节 ： https://github.com/PaddlePaddle/book/blob/develop/05.recommender_system/README.cn.md
