### ISSUE TITLE
安装paddle后，import paddle.fluid出现undefined symbol错误

### ISSUE THREAD

**Issue by sunhf** [PaddlePaddle/Paddle#18721]
错误信息 python2.7/site-packages/paddle/fluid/../libs/libmkldnn.so.0: undefined symbol: cblas_gemm_s8u8s32_pack_get_size

python版本2.7.3
paddle 版本1.5.1 CPU机器

**Comment by luotao1** [comment]
- 请问是什么CPU机器型号呢？`cat /proc/cpuinfo`看下。
- 安装前有先卸载后安装么？
- 请问系统中有多个python环境么？即运行的paddle是在`python2.7/site-packages/paddle/`路径下么？

**Comment by sunhf** [comment]
cpu 信息：
processor       : 0
vendor_id       : GenuineIntel
cpu family      : 6
model           : 45
model name      : Intel(R) Xeon(R) CPU E5-2620 0 @ 2.00GHz
stepping        : 7
cpu MHz         : 2001.000
cache size      : 15360 KB
physical id     : 0
siblings        : 6
core id         : 0
cpu cores       : 6
apicid          : 0
initial apicid  : 0
fpu             : yes
fpu_exception   : yes
cpuid level     : 13
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good xtopology nonstop_tsc aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 cx16 xtpr pdcm dca sse4_1 sse4_2 x2apic popcnt aes xsave avx lahf_lm ida arat epb xsaveopt pln pts dts tpr_shadow vnmi flexpriority ept vpid
bogomips        : 4000.05
clflush size    : 64
cache_alignment : 64
address sizes   : 46 bits physical, 48 bits virtual
power management:

安装前已经卸载过了

系统有多个python环境，但是运行的paddle确实在python2.7/site-packages/下，否则也import不成功吧

**Comment by luotao1** [comment]
```
错误信息 python2.7/site-packages/paddle/fluid/../libs/libmkldnn.so.0: undefined symbol: 
```
这是import出错吧？

> 运行的paddle确实在python2.7/site-packages/下

这个是默认的python环境么？

**Comment by sunhf** [comment]
import paddle成功了，paddle.fluid不成功。是默认的python环境，并且我用conda安装一份也是如此，在其他机器上用conda环境安装就很容易。

**Comment by luotao1** [comment]
你能看下其他环境下还有`libmkldnn.so.0`么？
> 在其他机器上用conda环境安装就很容易。

是说在其他机器上用conda装paddle是成功的？

**Comment by sunhf** [comment]
当前这个是cpu机器，其他的是gpu机器，gpu是ok的
