### ISSUE TITLE
[MKL-DNN] Add acquire API reusing for quantize , dequantize & requantize ops

### ISSUE THREAD

**Issue by jczaja** [PaddlePaddle/Paddle#18729]
- Reimplement reusing of quantize and dequantize  to be consistent with Acquire API
- Implement reusing using Acquire API for requantize. This should give speedup for INt8 models like googlenet_int8

**Comment by Sand3r-** [comment]
Acqurie API for requantize is done in #22223

**Comment by jczaja** [comment]
tracked internally
