### ISSUE TITLE
使用gpu训练paddlepaddle模型，反而比cpu慢？

### ISSUE THREAD

**Issue by heiyexingchen** [PaddlePaddle/Paddle#1873]
我服务器上有两块gpu，使用的nvidia-docker安装paddlepaddle，trainer_nums最多只能设置为2，use_gpu已经设为true，但是训练速度为什么比单cpu训练还要慢，这不科学啊！请问在项目中还需要配置什么？是不是我哪里没有做到，请求指点！还有我使用的是机械硬盘，没有使用固态硬盘，这个影响多大？

**Comment by hedaoyuan** [comment]
> 但是训练速度为什么比单cpu训练还要慢，这不科学啊!请问在项目中还需要配置什么？

具体慢的现象是如何？比如，CPU训练每个Pass多少时间，GPU每个Pass是多少时间？没有其他配置，use_gpu=true就可以。

另外，你训练的是什么模型？硬盘影响io，主要跟训练数据有关系，但对cpu和gpu训练的影响是一样的。另外，启动训练程序后，可以通过`nvidia-smi `检查一下程序的GPU利用率。

**Comment by guoshengCS** [comment]
Close since no update. Please reopen it if necessary.
