### ISSUE TITLE
模型train没有开始就挂掉了，没有发现挂掉的具体原因是啥

### ISSUE THREAD

**Issue by sitongchen** [PaddlePaddle/Paddle#18745]
选择fluid版本：1.4.1

训练出core，在train.log中报错如下：
Traceback (most recent call last):
  File "train.py", line 649, in <module>
    use_parallel_executor=bool(args.use_parallel_exe)
  File "train.py", line 620, in train
    train_loop(main_program, trainer_id)
  File "train.py", line 525, in train_loop
    exec_strategy=exec_strategy)
  File "/home/disk1/normandy/maybach/app-user-20190723010551-13209/workspace/python27-gcc482/lib/python2.7/site-packages/paddle/fluid/parallel_executor.py", line 134, in __init__
    self._compiled_program._compile(place=self._place, scope=self._scope)
  File "/home/disk1/normandy/maybach/app-user-20190723010551-13209/workspace/python27-gcc482/lib/python2.7/site-packages/paddle/fluid/compiler.py", line 307, in _compile
    scope=self._scope)
  File "/home/disk1/normandy/maybach/app-user-20190723010551-13209/workspace/python27-gcc482/lib/python2.7/site-packages/paddle/fluid/compiler.py", line 278, in _compile_data_parallel
    self._exec_strategy, self._build_strategy, self._graph)
paddle.fluid.core.EnforceNotMet: Compiled withoud cuda! at [/paddle/paddle/fluid/framework/details/multi_devices_graph_pass.cc:979]

before_hook.log 里报错:
Requirement './thirdparty/paddlepaddle-0.15.0-cp27-cp27mu-linux_x86_64.whl' looks like a filename, but the file does not exist
Looking in indexes: http://pip.baidu.com/pypi/simple
Processing ./thirdparty/paddlepaddle-0.15.0-cp27-cp27mu-linux_x86_64.whl
Could not install packages due to an EnvironmentError: [Errno 2] No such file or directory: '/home/disk1/normandy/maybach/app-user-20190723010551-13209/workspace/env_run/thirdparty/paddlepaddle-0.15.0-cp27-cp27mu-linux_x86_64.whl'

You are using pip version 10.0.1, however version 19.1.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.

不知道哪个才是挂掉的问题，一样的代码 之前用fluid=1.2.0可以train

**Comment by gongweibao** [comment]
paddle没有装成功。
![image](https://user-images.githubusercontent.com/10721757/61687731-b14dc480-ad55-11e9-9740-cde275705cfd.png)

**Comment by sitongchen** [comment]
在起任务的 paddlecloud job --job-version "paddle-fluid-v1.4.1"
在before_hook.sh 里写的是
mv ./thirdparty/paddlepaddle-0.0.0-cp27-cp27mu-linux_x86_64.whl.new ./thirdparty/paddlepaddle-0.0.0-cp27-cp27mu-linux_x86_64.whl

../python27-gcc482/bin/python ../python27-gcc482/bin/pip install --upgrade ./thirdparty/paddlepaddle-0.15.0-cp27-cp27mu-linux_x86_64.whl --index-url=http://pip.baidu.com/pypi/simple --trusted-host pip.baidu.com

thirdparty里 mv前后的两个whl都是有的
/app/ecom/fcr/chensitong03/fluid/cross_domain/thirdparty/paddlepaddle-0.0.0-cp27-cp27mu-linux_x86_64.whl
/app/ecom/fcr/chensitong03/fluid/cross_domain/thirdparty/paddlepaddle-0.0.0-cp27-cp27mu-linux_x86_64.whl.new
为啥会装不上呢

**Comment by gongweibao** [comment]
Hi上已经解决。close。
