### ISSUE TITLE
求多模型bagging的demo

### ISSUE THREAD

**Issue by wlxy** [PaddlePaddle/Paddle#18747]
RT

**Comment by wlxy** [comment]
我不是指在train模型的时候bagging,我是指在infer的时候，用两个模型同时对同一个样本打分，然后做bagging

**Comment by gongweibao** [comment]
现在暂时还没有。有了告诉你。

**Comment by NHZlX** [comment]
您好，可以用python分别获取到每个模型的输出，然后手动的实现bagging的逻辑.
