### ISSUE TITLE
建议官方文档使用docker安装部分添加nvidia-docker run

### ISSUE THREAD

**Issue by xiegegege** [PaddlePaddle/Paddle#18753]
欢迎您对PaddlePaddle提出建议，非常感谢您对PaddlePaddle的贡献！
在留下您的建议时，辛苦您同步提供如下信息：
- 版本、环境信息
1）PaddlePaddle版本：paddle1.5
2）CPU/GPU：cuda9 cudnn7
3）系统环境：请您描述系统类型、版本，例如Mac OS 10.14
- 复现信息：如为报错，请给出复现环境、复现步骤
- 建议描述：
[使用Docker安装](https://www.paddlepaddle.org.cn/documentation/docs/zh/1.5/beginners_guide/install/install_Docker.html)页面里的构建、进入Docker容器部分只写了docker run，没写使用gpu的话用nvidia-docker run，新手很容易使用docker run进入容器，然后运行程序报CUDA driver version is insufficient for CUDA runtime version at [/paddle/paddle/fluid/platform/gpu_info.cc:97]，比较难发现问题在哪。

Thank you for contributing to PaddlePaddle.
Before submitting the issue, you could search issue in the github in case that there was a similar issue submitted or resolved before.
Please make sure that this is a feature request. 
**System information**
-PaddlePaddle version （eg.1.1）or CommitID
-CPU: including CPUMKL/OpenBlas/MKLDNN version
-GPU: including CUDA/CUDNN version
-OS Platform (eg.Mac OS 10.14)
**To Reproduce**
Steps to reproduce the behavior
**Describe the feature and the current behavior/state.**
**Any Other info.**

**Comment by gongweibao** [comment]
非常感谢呀！
