### ISSUE TITLE
打印日志发现pyreader输出的seq length变长，请问是怎么实现的？

### ISSUE THREAD

**Issue by yuanzfy** [PaddlePaddle/Paddle#18764]
我在测试paddlepaddle/ernie，发现pyreader输出的seq是变长的，seq_length是128，但是每个batch的seq length都是动态变化的，请问这个是怎么实现的？
![image](https://user-images.githubusercontent.com/4515954/61761028-05ad7e80-ae00-11e9-9da1-a24ad55e92b5.png)

**Comment by guoshengCS** [comment]
128是构建网络时使用的大小，实际运行时是可以动态变化的，运行时会根据实际数据的重新获取，对于变化的seq_length不影响fc等操作，还是可以正常运行的
