### ISSUE TITLE
op lookup_table does not have kernel for data_type[::paddle::platform::float16]

### ISSUE THREAD

**Issue by bipedalBit** [PaddlePaddle/Paddle#18782]
- PaddlePaddle版本：1.5
- CPU
- 系统环境：Ubuntu1604
- Python版本号: 3.7
- 复现信息：把paddle官方的ERNIE模型cast成半精度的版本（加-fp16选项）然后保存inference_model
- 问题描述：
虽然我也不知道哪里用到了lookup_table，请问lookup_table op目前不支持fp16吗？我把paddle官方的ERNIE模型存成半精度的inference_model时报了下面的错：
```op lookup_table does not have kernel for data_type[::paddle::platform::float16]...```

**Comment by guoshengCS** [comment]
这个目前不支持，可能也不是特别有必要，lookup_table作为查表操作可能fp16收益不大
