### ISSUE TITLE
[MKL-DNN] Add Leaky-relu support and conv+leaky_relu fuse pass

### ISSUE THREAD

**Issue by grygielski** [PaddlePaddle/Paddle#18788]
Add LeakyReLU mkldnn support and Conv+LeakyReLU mkldnn pass to improve performance of Face model. This is reopening of #17654 due to PR reversion.

Scope of task:
1. Add mkl-dnn leaky_relu support
2. Add Pass: conv + leaky_relu -> conv_leaky_relu_mkldnn_fuse_pass

**Comment by grygielski** [comment]
I created PR that adds leaky_relu mkldnn support but uses additional attribute added to activation op grad (pointer to corresponding forward activation op): https://github.com/PaddlePaddle/Paddle/pull/18762. Let me know if you accept this universal solution. If not I will just add conditional cases to check for specific operators whose grads takes only X as input. This solution does not add any more parameters to current operators but leads to more complicated development of mkldnn activation operators support. @luotao1

**Comment by grygielski** [comment]
#18762

**Comment by luotao1** [comment]
I agree with `Adding attributes seems too strange` from @sneaxiy  in https://github.com/PaddlePaddle/Paddle/pull/18762#pullrequestreview-265794216.

> If not I will just add conditional cases to check for specific operators whose grads takes only X as input. This solution does not add any more parameters to current operators but leads to more complicated development of mkldnn activation operators support.

Could you easily describe how to do this check? And `more complicated development` will add a lot of codes? 

@jczaja How do you see about it?

**Comment by grygielski** [comment]
To solve this issue for now I would just use something like this in eltwise_forward() and similar one in eltwise_grad() in activation_mkldnn_op.cc
```cpp
if (ctx.op().Type() == "leaky_relu" || Other operators with grad X input) {
  std::string key = ... + ctx.op().Input("X"));
} else {
  std::string key = ... + ctx.op().Output("Out"));
}
```
In spite of it fixes things for now, it requires from developer who will implement further mkldnn operators to know exactly what it is dependent on and put its name in there what makes whole thing kinda hardcoded instead of generic. But the bigger problem is with future parallelization of whole process which is the thing @jczaja will work on in future. I'm trying to make solution that satisfies both, current problem and future ones. Every mkldnn grad operator needs input of forward operator ("X") which we store in cache right now what makes a lot of problems during multi threading (if hash is generated with thread id then same thread have to calculate both forward and backward operation and if it's not there is a possibility of overwriting data). This is why I wanted to somehow push Input("X") to grad operator. One thing that came to our minds is checking in runtime for mkldnn_enable flag and based of that set additional input or not (it won't affect GPU) but I have to try if it works.

**Comment by jczaja** [comment]
@luotao1 If possible I would like to try approach describe by @grygielski  eg. Add additional input to grad based on the fact if this op (or paddle instance)  is to be executed using GPU or MKL-DNN. I assume that we do not support mixed execution of model eg. some ops on GPU some ops on MKL-DNN. So if possible in grad maker we check for use_mkldnn==True , if this is not possible then
We perhaps we can check if model is run on GPU or MKL-DNN and add additional input for MKL-DNN instance.  

This is needed to solve #17960  e.g. to stop passing X from fwd op to grad op via device context and use inputs in exchange.

**Comment by grygielski** [comment]
@luotao1 Could you please check if current commit accelerated face model as old one did? I want to be sure if all works as it should before I post fuse PR. Unfortunately we still didn't manage to run model on our systems.

**Comment by luotao1** [comment]
I check it, the result almost the same in https://github.com/PaddlePaddle/Paddle/pull/18656#issuecomment-513091523. Thanks very much!

**Comment by grygielski** [comment]
Great! I have conv + leaky_relu mkldnn fuse pass almost ready to push. I will do it during next WW. Hopefully it will speed up inference even more.

**Comment by grygielski** [comment]
I'm closing this one since newer version of code is submitted in PR https://github.com/PaddlePaddle/Paddle/pull/18942
