### ISSUE TITLE
本地安装 1.5.1 whl 包 报错（Pillow：The headers or library files could not be found for jpeg）

### ISSUE THREAD

**Issue by jiaqianjing** [PaddlePaddle/Paddle#18785]
本地安装 1.5.1 whl 包，报如下错误：
![image](https://user-images.githubusercontent.com/16071449/61781610-41b00600-ae37-11e9-8b50-9e1bd6107ce9.png)

![image](https://user-images.githubusercontent.com/16071449/61781411-debe6f00-ae36-11e9-9109-c9eb2c46085e.png)
whl 链接：
https://paddle-wheel.bj.bcebos.com/1.5.1-cpu-mkl/paddlepaddle-1.5.1-cp27-cp27mu-linux_x86_64.whl

**Comment by guoshengCS** [comment]
麻烦先试下手动单独安装下Pillow吧

**Comment by jiaqianjing** [comment]
好，但是这样 whl 岂不是没有意义，还要手动安装 pillow 才能安装 paddle 的 whl 包

**Comment by jiaqianjing** [comment]
yum install -y zlib-devel libjpeg-turbo-devel && \
    pip install Pillow
解决安装 Pillow 失败的问题
