### ISSUE TITLE
tensorRT子图预测在高并发的时候，相比原生 paddle 预测速度下降很多

### ISSUE THREAD

**Issue by QsJack** [PaddlePaddle/Paddle#18787]
RT

单并发执行没问题，但是并发数上来后，tensorRT 子图预测的速度下降非常多。主干网络是 resnet50，任务是检测。

从测试的 qps 上来看，6个并发，tensorRT的 qps=1.1+，原始 fluid 的预测 qps=3+。

**Comment by NHZlX** [comment]
问题我这边先记录一下，稍后会进行复现。
