### ISSUE TITLE
使用with_inference_optimize时报错

### ISSUE THREAD

**Issue by tianjie491** [PaddlePaddle/Paddle#18798]
- 版本、环境信息：paddlepaddle1.5.0
    1）PaddlePaddle版本：paddlepaddle1.5.0
    2）CPU：i5-7500_CPU_@_3.40GHz
    3）GPU：v100
    4）系统环境：win10，Python版本：3.5
-预测信息
用CPU或GPU进行预测，使用with_inference_optimize时都会报错，去除下面的代码段则正常
        prog_file = "{}/__model__".format(args.init_checkpoints_type + "/inference_model")
        params_file = "{}/__params__".format(args.init_checkpoints_type + "/inference_model")
        config = fluid.core.AnalysisConfig(prog_file, params_file)
        type_infer_program = compiler.CompiledProgram(type_infer_program)
        type_infer_program.with_inference_optimize(config)

报错信息如下：
e[1me[35m--- Running analysis [ir_graph_build_pass]e[0m
e[1me[35m--- Running analysis [ir_analysis_pass]e[0m
e[32m--- Running IR pass [infer_clean_graph_pass]e[0m
e[32m--- Running IR pass [attention_lstm_fuse_pass]e[0m
e[32m--- Running IR pass [seqconv_eltadd_relu_fuse_pass]e[0m
e[32m--- Running IR pass [fc_lstm_fuse_pass]e[0m
e[32m--- Running IR pass [mul_lstm_fuse_pass]e[0m
e[32m--- Running IR pass [fc_gru_fuse_pass]e[0m
e[32m--- Running IR pass [mul_gru_fuse_pass]e[0m
e[32m--- Running IR pass [seq_concat_fc_fuse_pass]e[0m
e[32m--- Running IR pass [fc_fuse_pass]e[0m
e[37m---  detected 74 subgraphse[0m
e[32m--- Running IR pass [repeated_fc_relu_fuse_pass]e[0m
e[32m--- Running IR pass [squared_mat_sub_fuse_pass]e[0m
e[32m--- Running IR pass [conv_bn_fuse_pass]e[0m
e[32m--- Running IR pass [conv_eltwiseadd_bn_fuse_pass]e[0m
e[32m--- Running IR pass [is_test_pass]e[0m
e[32m--- Running IR pass [runtime_context_cache_pass]e[0m
e[1me[35m--- Running analysis [ir_params_sync_among_devices_pass]e[0m
e[1me[35m--- Running analysis [adjust_cudnn_workspace_size_pass]e[0m
e[1me[35m--- Running analysis [inference_op_replace_pass]e[0m
e[1me[35m--- Running analysis [ir_graph_to_program_pass]e[0m
Traceback (most recent call last):
  File "E:\tools\PyCharm\helpers\pydev\pydevd.py", line 1758, in <module>
    main()
  File "E:\tools\PyCharm\helpers\pydev\pydevd.py", line 1752, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "E:\tools\PyCharm\helpers\pydev\pydevd.py", line 1147, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "E:\tools\PyCharm\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "E:/Project/DBQA/predict_with_csv2.py", line 291, in <module>
    main(args)
  File "E:/Project/DBQA/predict_with_csv2.py", line 239, in main
    type_probs, type_scope)
  File "E:/Project/DBQA/predict_with_csv2.py", line 157, in prediction
    scope=scope)
  File "E:\tools\anaconda\lib\site-packages\paddle\fluid\executor.py", line 668, in run
    return self._run_inference(program._executor, feed)
  File "E:\tools\anaconda\lib\site-packages\paddle\fluid\executor.py", line 758, in _run_inference
    return exe.run(feed)
TypeError: run(): incompatible function arguments. The following argument types are supported:
    1. (self: paddle.fluid.core_avx.AnalysisPredictor, arg0: List[paddle.fluid.core_avx.PaddleTensor]) -> List[paddle.fluid.core_avx.PaddleTensor]

Invoked with: <paddle.fluid.core_avx.AnalysisPredictor object at 0x000000843BB78A08>, {'read_file_0.tmp_0': array([[[   1],
        [ 226],
        [ 170],
        [   4],
        [  75],
        [  10],
        [1464],
        [  17],
        [  11],
（中间的也是数字，省略）
        [1.]]], dtype=float32)}
I0725 10:35:23.495776  6368 analysis_predictor.cc:451] == optimize end ==

相关代码片段：
    ernie_config = ErnieConfig(args.ernie_config_path)  # 读取配置参数
    if args.use_cuda:  # 使用cuda
        place = fluid.CUDAPlace(int(os.getenv('FLAGS_selected_gpus', '0')))
    else:
        os.environ['CPU_NUM'] = str(1)
        place = fluid.CPUPlace()
    exe = fluid.Executor(place)

    reader = task_reader.ClassifyReader(
        vocab_path=args.vocab_path,
        label_map_config=args.label_map_config,
        max_seq_len=args.max_seq_len,
        do_lower_case=args.do_lower_case,
        in_tokens=args.in_tokens,
        random_seed=args.random_seed)

    startup_prog = fluid.Program()
    exe.run(startup_prog)

    type_scope = fluid.core.Scope()
    with fluid.scope_guard(type_scope):
        type_model_path = os.path.join(args.init_checkpoints_type, "inference_model")
        type_infer_program, type_feed_target_names, type_probs = fluid.io.load_inference_model(
            type_model_path, exe, model_filename='__model__', params_filename='__params__')
        prog_file = "{}/__model__".format(args.init_checkpoints_type + "/inference_model")
        params_file = "{}/__params__".format(args.init_checkpoints_type + "/inference_model")
        config = fluid.core.AnalysisConfig(prog_file, params_file)
        type_infer_program = compiler.CompiledProgram(type_infer_program)
        type_infer_program.with_inference_optimize(config)

    wrapper, example_type = reader.pridict_generator(args.law_file,
                                                    question,
                                                    batch_size=args.batch_size)
    index_type = prediction(exe, type_infer_program, wrapper, type_feed_target_names,
                                type_probs, type_scope)

def prediction(exe, prog, predict_data_generator, feed_target_names, probs, scope):
    index = []
    src_ids = feed_target_names[0]
    sent_ids = feed_target_names[2]
    pos_ids = feed_target_names[1]
    input_mask = feed_target_names[3]
    for sample in predict_data_generator():
        src_ids_data = sample[0]
        sent_ids_data = sample[1]
        pos_ids_data = sample[2]
        input_mask_data = sample[3]
        probs[0].persistable = True
        np_probs = exe.run(
            prog,
            feed={src_ids: src_ids_data,
                  sent_ids: sent_ids_data,
                  pos_ids: pos_ids_data,
                  input_mask: input_mask_data},
            fetch_list=probs,
            scope=scope)
        index.extend(np_probs[0])

    lists = list(np.array(index)[:, 1])
    list_new = []
    for index, values in enumerate(lists):
        if values > 0.10:
            list_new.append((index, values))
    index = sorted(list_new, key=lambda x: x[1], reverse=True)[:args.beam_size]
    return index

我看报错说
TypeError: run(): incompatible function arguments. The following argument types are supported:
    1. (self: paddle.fluid.core_avx.AnalysisPredictor, arg0: List[paddle.fluid.core_avx.PaddleTensor]) -> List[paddle.fluid.core_avx.PaddleTensor]
但是不使用with_inference_optimize时是正常的，这是为什么？怎么解决？

**Comment by Superjomn** [comment]
@fc500110 帮看下吧

**Comment by fc500110** [comment]
是在做预测吗

**Comment by tianjie491** [comment]
@fc500110
是的，模型已经训练完了。预测时耗时太长，想通过with_inference_optimize优化下，但是一直实现不了。

**Comment by fc500110** [comment]
建议直接使用[python 预测API](https://www.paddlepaddle.org.cn/documentation/docs/zh/1.5/advanced_usage/deploy/inference/python_infer_cn.html)

**Comment by tianjie491** [comment]
@fc500110 反馈下使用效果：
1、没用python 预测API时，预测100条数据，用时400s，用了之后用时300s，提升25%，提升还是比较大的。
2、config.enable_tensorrt_engine()打开后会报paddle.fluid.core_avx.EnforceNotMet: Pass tensorrt_subgraph_pass has not been registered at [/paddle/paddle/fluid/framework/ir/pass.h:160]这样的错误config.enable_tensorrt_engine(1 << 20, 1,use_static=False, use_calib_mode=True,precision_mode=fluid.core.AnalysisConfig.Precision.Int8)也是一样。如果能够打开tensorRT的话应该会更好吧。
3、预测过程中会有警告：The NaiveExecutor can not work properly if the cmake flag ON_INFER is not set.Please re-compile the inference library by setting the cmake flag ON_INFER=ON if you are running Paddle Inference。好像是需要在cmake里打开ON_INFER开关，但是由于我是新手，不会用cmake，希望你们能更加优化接口，直接在python里封装好。
4、不用python预测API是我的batch_size可以设置32，用了之后最多设置为4，否则报错。不知道是不是我哪里没设置对 Cannot malloc 153.525 MB GPU memory. Please shrink FLAGS_fraction_of_gpu_memory_to_use or FLAGS_initial_gpu_memory_in_mb or FLAGS_reallocate_gpu_memory_in_mbenvironment variable to a lower value. Current FLAGS_fraction_of_gpu_memory_to_use value is 0.01. Current FLAGS_initial_gpu_memory_in_mb value is 0. Current FLAGS_reallocate_gpu_memory_in_mb value is 0
F0727 15:45:07.788070  2772 legacy_allocator.cc:201] Cannot allocate 72.000000MB in GPU 0, available 71.937500MBtotal 16945512448GpuMinChunkSize 256.000000BGpuMaxChunkSize 153.524750MBGPU memory used: 14.753713GB。
5、建议你们能够优化api文档，文档不清晰会造成很多坑啊。
下面贴一下相关代码
import os
os.environ['FLAGS_eager_delete_tensor_gb'] = '0'
os.environ['FLAGS_fraction_of_gpu_memory_to_use'] = '0.01'
    type_scope = fluid.core.Scope()
    with fluid.scope_guard(type_scope):
        type_model_path = os.path.join(args.init_checkpoints_type, "inference_model")
        type_infer_program, type_feed_target_names, type_probs = fluid.io.load_inference_model(
            type_model_path, exe, model_filename='__model__', params_filename='__params__')
        prog_file = "{}/__model__".format(args.init_checkpoints_type + "/inference_model")
        params_file = "{}/__params__".format(args.init_checkpoints_type + "/inference_model")
        config = AnalysisConfig(prog_file, params_file)
        if args.use_cuda:
            config.enable_use_gpu(16000, 0)
            # config.enable_tensorrt_engine()
            # config.enable_tensorrt_engine(1 << 20, 1,use_static=False, use_calib_mode=True,
            #     precision_mode=fluid.core.AnalysisConfig.Precision.Int8)
        else:
            config.disable_gpu()
            config.enable_mkldnn()
        predictor_type = create_paddle_predictor(config)
    index_type = prediction(predictor_type, wrapper, type_feed_target_names,
                                type_probs, type_scope)
def prediction(predictor, predict_data_generator, feed_target_names, probs, scope):
    index = []
    for sample in predict_data_generator():
        max_seq_len = sample[0].shape[1]
        src_ids_data = fake_input(max_seq_len, sample[0], PaddleDType.INT64)
        sent_ids_data = fake_input(max_seq_len, sample[1], PaddleDType.INT64)
        pos_ids_data = fake_input(max_seq_len, sample[2], PaddleDType.INT64)
        input_mask_data = fake_input(max_seq_len, sample[3], PaddleDType.FLOAT32)
        np_probs = predictor.run([src_ids_data, pos_ids_data, sent_ids_data, input_mask_data])
        np_probs = np.array(np_probs[0].data.float_data()).reshape(sample[0].shape[0], 2)
        index.extend(np_probs)

**Comment by tianjie491** [comment]
大佬看看能不能再优化下，最好能在python里完成。

**Comment by fc500110** [comment]
2. 编译Python安装包的时候没有打开TensorRT
3. 不影响
4. 显存设置太大，建议enable_use_gpu的时候设置小一些
5. 由于Python API第一次发布，难免会有一些问题，我们会在后续发版和文档中持续优化

**Comment by DJinsis** [comment]
@fc500110 
你的回答中的，编译Python安装包的时候没有打开TensorRT，是什么意思呢，我也遇到这个错误，paddle fluid create pred    ictor failed, e.info: Pass tensorrt_subgraph_pass has not been registered at [/paddle/paddle/fluid/framework/ir/pass.h:160]
我的加速配置是这样的
![image](https://user-images.githubusercontent.com/9247758/64338198-b9b34380-d013-11e9-9f43-d3b4b7ac75d1.png)
