### ISSUE TITLE
learningRateDecay无法取到lr值，因为是局部变量

### ISSUE THREAD

**Issue by DDDivano** [PaddlePaddle/Paddle#18799]
![image](https://user-images.githubusercontent.com/10734244/61843264-a4ec7780-aecd-11e9-89f1-41ab2e87a16c.png)
直接取_learning_rate.numpy()会调用call方法导致衰减计数不准。
![image](https://user-images.githubusercontent.com/10734244/61843337-d2d1bc00-aecd-11e9-8d3d-ccebc9bb1642.png)

**Comment by DogHeadMoon** [comment]
该PR delay，在optimizer中新增learning_rate()接口，预计会在1.6.1合入，  https://github.com/PaddlePaddle/Paddle/pull/19952
