### ISSUE TITLE
在PSERVER 下使用l2正则会导致 grpc error

### ISSUE THREAD

**Issue by liangpj** [PaddlePaddle/Paddle#18792]
使用 L2正则的时候在分布式环境下训练会导致 grbc error， 如果将节点数设置为1将会没有问题。
![image](https://user-images.githubusercontent.com/11581801/61795057-22c06c80-ae55-11e9-945e-c4d6c8a6144d.png)
错误信息
![image](https://user-images.githubusercontent.com/11581801/61795097-2fdd5b80-ae55-11e9-896c-8ac528057637.png)
如果将regularization参数去掉可以正常运行。

**Comment by wanghaoshuang** [comment]
#18796

**Comment by seiriosPlus** [comment]
请提供一下复现代码，感谢
