### ISSUE TITLE
Parameter server design doc

### ISSUE THREAD

**Issue by helinwang** [PaddlePaddle/Paddle#1880]
无论是否重写parameter server，我们都需要一个清晰的parameter server接口：
- 如果不重写，可以保证修改现有代码不会让可维护性降得更低。以后要重写只用保持接口不变，更换实现即可。
- 如果重写，也需要一个清晰的接口，保证代码质量。

目前parameter server只需要支持：异步SGD，不带动量的优化算法（传统SGD），dense更新。
不需要支持：同步SGD，各种带动量的优化算法，sparse更新。
接口**需要**涵盖目前不需要支持的功能，**不需要**实现不支持的功能。

据我理解，design doc需要以下几块接口的定义：
- 运行parameter server的命令行参数是什么：
  比如： `--port 8000 --save-period 60`

- RPC Server接口伪代码：
  我想象的，举个例子：
  ```c
  int update(string method, list of dense gradients);
  int download(pointer to list of dense gradients);
  int updateSparse(string method, xxx);
  int downloadSparse(xxx);
  int saveModel(string path);
  ```
- RPC client API，python and C/C++
  出于性能考虑update和download貌似只能是C/C++ API (不然数据类型需要经过python中转）。
  - C/C++ API（C或者C++都行，只要表达了意思就好）。如果要用golang重写，实现的时候需要C API：
  我想象的，举个例子：
  ```c
  int update(string method, list of dense gradients);
  int download(pointer to list of dense gradients);
  int updateSparse(string method, xxx);
  int downloadSparse(xxx);
  int saveModel(string path);
  int wait(int t);

  // e.g.,
  // update(...);
  // int errorCode = wait(download(...));
  ```
  - python API（是否只需要保存模型的API？）

- 把parameter server 主干部分（参数存储，更新部分，除去RPC以及使用etcd做service announcement的部分）当作一个库，库的API。
  定义库API可以把RPC代码与主干部分清晰分开。以后保持接口，更换实现会很方便。另外有可能用golang写主程序，编译时候链接这个库。

**Comment by gongweibao** [comment]
我建议重写，起码现在的parameter server的rpc机制有些问题
- socket是block模式的，没有timeout，也没有错误以后失败重试、关闭连接重试机制，也就是传送数据必须要成功。这在节点比较多、网络压力大的情况下容易出问题。
- 一个trainer一个线程，一旦trainer个数多，parameterserver线程调度的压力会很大

**Comment by helinwang** [comment]
go rpc用的on-wire格式gob很有意思：
> From integers we can build all the other types: bytes, strings, arrays, slices, maps, even floats. Floating-point values are represented by their IEEE 754 floating-point bit pattern, stored as an integer, which works fine as long as you know their type, which we always do. By the way, that integer is sent in byte-reversed order because common values of floating-point numbers, such as small integers, have a lot of zeros at the low end that we can avoid transmitting.

https://blog.golang.org/gobs-of-data

**Comment by dzhwinter** [comment]
Design Doc: Parameter Server Process

Parameter Server process 是Paddle中负责模型的存储，更新和模型分片一致性的组件，在整个系统中的作用请参考 distributed training design doc ，本文档包含PServer，PClient，PServerContoller等，涉及到的配置参数均使用大写字母



术语

- PServer: Parameter Server 服务器
- PClient: Parameter Server Client
- PServerController：PServer管理员，启动Server，动态扩容，容灾等
- model: 指深度学习训练之后得到的所有参数，使用这个神经网络可以完成对新数据的预测
- parameters: 神经网络中的参数，包括权重w和偏置b。一个神经网络的模型由大量的参数组成
- shard: 分片，通常指将一个整体拆分成多份的其中的一份。
- model shard: 将一个神经网络参数拆分成多份，每个shard分别存储在其中一台parameter server之上
- parameter block: 多个parameter block构成一个model shard
- 单点故障: 任意时刻只可能同时有一台服务器故障。由于集群中同时存在两台机器故障的概率极低（（平均故障率*平均故障修复时间）^2）只对特殊在线系统考虑两台以上同时故障的容灾。

 PServer

PServer负责:

模型存储，模型更新，注册服务并监听端口事件，PServer个数的动态扩张收缩，负责序列化传输数据。

发送接收数据和命令都使用rpc 接口，例如golang rpc

    class Evaluator;
    class ParameterUpdater;
    class DeviceSet;
    template<PKEY, PVALUE>
    class PServer {
      class ParameterSegments {
      PKEY key; // param_id;
      
      ...
    	}
    RWLock lock;
    int32_t serverId;
    PServerConfig config; // start Pserver config 
    // part 1, store model in device
    // compute resource 
    // thread, memory, deviceset
    syncThreadPool threadPool;
    Device **store_pool[SHARD_NUM];  // memory and gpu memory，2d pointer store a vector of shard pointer. each shard should be unordered_map<ParameterSegments> parameterMap; 
    
    GradientMachine *gmbase; // gradient machine implement forward backward interface, including multineuralnet, recurrnet neuralnet, 
      
    //register operations service,  used between matrix, vectors ooperation
    unorderedmap<string, ?> serviceRegisted;
    
    
    public:
     
      bool isStartedAndAlive(); // for PServerController, check status
      
      // part 2: update parameter
      // *ONLY* use this interface execute the callback
    private:
    // apply update
    ParameterUpdater *updatebase;
    
      typedef std::function<void()> Callback;  // function callback
      void exec();
      void parallelExec();
      or
      
      void doOperation(PrepareOperation& ops, ...); // operator topology
      void doMultipleOperation(PrepareOperation& ops, ...);
      //TODO: op execute need more detail here
      
      // part 4: checkpoint, ignore the difference of save time between PServer nodes.
      // see hash ring, when there is failed worker, kubernates start a new worker and insert into hashring.
      hashring registerWorker;
      
      int32_t saveCheckPoint() {
        //i, counter match save checkpoint condition, grab the RWLock;
        //ii, start new thread, generate unique UUID, write to pfs(filesystem), (TODO: Stop update and wait?)
        //iii, write etcd `/checkpoint/pserver_id : {"uuid": [UUID], "md5", "MD5 sum", "timestamp": xxxx}`
        // iv, delete earlier checkpoint not equal to UUID
        // v, release lock, wait write thread join; 
        return SUCCESS;
      }
      int32_t recoveryFromCheckPoint() {
        getUUIDFrometcd();
        tryLoadCheckPoint();
        PServerController call start interface.
        return SUCCESS;
      }
      
    private:
    // metrics, evaluate the model in runtime
    // every node send runtime statistics to evaluatorServer during training/testing. when training Pass finish(or event handler notify), trainer leader(e.g node_id=0) send rpc call to evaluatorServer process then produce result. 
    //Evaluator base class, for example, AUC, LOSS, AVERAGE 
    //evalbase->sendAsync(EVAL_DATA_STRUCT)
    //evaluatorServer as standalone thread, can be used in jupyter notebook
    Evaluator *evalbase;  
      
    //part 6 : auto scaling 
    see PClient Part
     
    } // PServer
    
    
    class ParameterUpdater {
    Optimizer *base;
    }
    class SparseParameterUpdater {
      
    }
    class SGDOptimizer : Optimizer {
      ...
    } 
    class ASGDOptimizer : Optimizer {
      ...
    } 
    class OWLQNOptimizer : Optimizer {
      ...
    } 



Optimizer需要支持的优化算法

L-BFGS，owlqn，ftrl, TODO：在Paddle中owlqn等需要参数更新方式不同，支持接口是否相同？

sgd (momentum, adagram, adadelta, adam)，pass based

async-sgd



PClient

PClient功能是否已经包含在trainer中？PClient 负责parameter balancer，打包rpc请求转发PServer

    class ParameterPartitioner;
    template<PKEY, PVALUE>
    PClient {
    public:
      
    private:
      // use param_id and node_id as hash key, balance parameter between shard and PServers
      ParameterPartitioner partitioner;
    }
    template<PKEY>
    class ParameterPartitioner {
      hash(param_id, node_id) // impl hash function generate evenly distributed shard_id/PServerid, when auto scaling of PServer, then store 
        
    // auto scaling, do not implement in v1
      rehash(param_id, node_id); // generate new server hash id for each parameter
      
    }



RPCServer

接口类，屏蔽rpc实现，方便移植rpc lib

    // Used for request, package up request into binary
    struct RpcRequest {
        uint64_t _request_id;
        int32_t _src_id;  //node_id
        int32_t _target_id; //node_id
        std::string _target_method_name; 
        std::string _src_method_name;
        BinaryArchive _args;
        static uint64_t s_buffer_size;
    }
    // Used for response, package up response into binary
    struct RpcResponse {
    public:
        uint64_t _request_id;
        int32_t _target_id;
        std::string _target_method_name;
        BinaryArchive _archive;
        int32_t _error_code;



    class AsyncRPCServer {
      static createRequest(RPCRequest*, RPCResponse);
      static AsyncRPCServer& singleton();
      // send rpc call asynchronize
      void send_async(); 
      void send_sync();
      RPCImpl *rpcimpl;
    }

PServerController

根据ParameterServer参数创建和管理PServer instance，从命令行读取参数，从etcd读取参数，运行开始将存活的PServer instance配置存储在etcd中

- 启动和运行参数包括：

/PS_DESIRED:, 启动PServer instance个数，etcd存储格式 /PS_DESIRED:3

/ROOT_PORT：显式指定根端口，PServer端口从PORT+1开始，直到找到可用端口，例如ROOT_PORT=8000, 则PServer0Port=8000，PServer0Port=8001,…，当前存在的PServer实例配置以etcd实时存储为准

etcd存储格式 ROOT_PORT:8000, /PS/0:8000，/PS/1:8001

/CHECKPOINT_PERIOD:PServer运行保存快照存储的时间间隔，default filled

/CHECKPOINT_DIR:保存快照的路径，default filled

- 创建PServer接口

    int32_t loadConfig(fromCLi);
    int32_t loadConfig(frometcd);
    static PServer* create(PServerConfig& );
    static PServer* create(const char* checkpoint_dir);

- 管理PServer实例

    int32_t start(); // start PServer
    int32_t wait();  //wait join
    int32_t countAlive(); // count alive instance

**Comment by helinwang** [comment]
Issue resolved by design doc: https://github.com/PaddlePaddle/Paddle/blob/develop/doc/design/cluster_train/pserver_client.md
