### ISSUE TITLE
预测一段时间报错：what():  unspecified launch failure at

### ISSUE THREAD

**Issue by prozhuchen** [PaddlePaddle/Paddle#18808]
- 版本、环境信息：
    1）PaddlePaddle版本：1.3.1
    2）CPU：
    3）GPU：gpu Tesla P40, cuda9.0 cudnn7
    4）系统环境：centos python2.7

- 问题描述：

使用paddle版本enrie模型预测一段时间后就会报如下错误，看不出来是哪一行的问题，请问是为什么？
```
terminate called after throwing an instance of 'paddle::platform::EnforceNotMet'
  what():  unspecified launch failure at [/paddle/paddle/fluid/framework/details/op_handle_base.cc:37]
PaddlePaddle Call Stacks:
0       0x7feba39b7405p void paddle::platform::EnforceNotMet::Init<char const*>(char const*, char const*, int) + 357
1       0x7feba39b7789p paddle::platform::EnforceNotMet::EnforceNotMet(std::__exception_ptr::exception_ptr, char const*, int) + 137
2       0x7feba523bfe1p paddle::framework::details::OpHandleBase::~OpHandleBase() + 337
3       0x7feba5229e91p paddle::framework::details::FetchOpHandle::~FetchOpHandle() + 17
4       0x7feba3a68489p paddle::framework::ir::Node::~Node() + 73
5       0x7feba3a68631p paddle::framework::ir::Node::~Node() + 17
6       0x7feba522b9cbp paddle::framework::details::ClearFetchOp(paddle::framework::ir::Graph*, std::vector<paddle::framework::details::FetchOpHandle*, std::allocator<paddle::framework::details::FetchOpHandle*> >*) + 1995
7       0x7feba51d7254p paddle::framework::details::ThreadedSSAGraphExecutor::Run(std::vector<std::string, std::allocator<std::string> > const&) + 4660
8       0x7feba51cd9bap paddle::framework::details::ScopeBufferedSSAGraphExecutor::Run(std::vector<std::string, std::allocator<std::string> > const&) + 394
9       0x7feba3af57a2p paddle::framework::ParallelExecutor::Run(std::vector<std::string, std::allocator<std::string> > const&, std::string const&) + 562
10      0x7feba39a7d9ep
11      0x7feba39e2d0ep
12      0x7fec08c9b577p PyEval_EvalFrameEx + 28695
13      0x7fec08c9da99p PyEval_EvalCodeEx + 2025
14      0x7fec08c9af68p PyEval_EvalFrameEx + 27144
15      0x7fec08c9c54ep PyEval_EvalFrameEx + 32750
16      0x7fec08c9c54ep PyEval_EvalFrameEx + 32750
17      0x7fec08c9da99p PyEval_EvalCodeEx + 2025
18      0x7fec08c9dcbap PyEval_EvalCode + 26
19      0x7fec08cb701dp
20      0x7fec08cb81c8p PyRun_FileExFlags + 120
21      0x7fec08cb93e8p PyRun_SimpleFileExFlags + 232
22      0x7fec08ccb67cp Py_Main + 2988
23      0x7fec07eb4b45p __libc_start_main + 245
24      0x7fec08d9d07fp

*** Aborted at 1564038910 (unix time) try "date -d @1564038910" if you are using GNU date ***
PC: @                0x0 (unknown)
*** SIGABRT (@0x1f600006f1e) received by PID 28446 (TID 0x7fec08b9d740) from PID 28446; stack trace: ***
    @     0x7fec0896c130 (unknown)
    @     0x7fec07ec89d9 __GI_raise
    @     0x7fec07eca0e8 __GI_abort
    @     0x7febfe07d3df __gnu_cxx::__verbose_terminate_handler()
    @     0x7febfe07bb16 __cxxabiv1::__terminate()
    @     0x7febfe07af91 __cxa_call_terminate
    @     0x7febfe07b79d __gxx_personality_v0
    @     0x7febfe349f56 _Unwind_RaiseException_Phase2
    @     0x7febfe34a244 _Unwind_RaiseException
    @     0x7febfe07bd1b __cxa_throw
    @     0x7feba523bfff paddle::framework::details::OpHandleBase::~OpHandleBase()
    @     0x7feba5229e91 paddle::framework::details::FetchOpHandle::~FetchOpHandle()
    @     0x7feba3a68489 paddle::framework::ir::Node::~Node()
    @     0x7feba3a68631 paddle::framework::ir::Node::~Node()
    @     0x7feba522b9cb paddle::framework::details::ClearFetchOp()
    @     0x7feba51d7254 paddle::framework::details::ThreadedSSAGraphExecutor::Run()
    @     0x7feba51cd9ba paddle::framework::details::ScopeBufferedSSAGraphExecutor::Run()
    @     0x7feba3af57a2 paddle::framework::ParallelExecutor::Run()
    @     0x7feba39a7d9e _ZZN8pybind1112cpp_function10initializeIZN6paddle6pybindL18pybind11_init_coreERNS_6moduleEEUlRNS2_9framework16ParallelExecutorERKSt6vectorISsSaISsEERKSsE152_vIS8_SD_SF_EINS_4nameENS_9is_methodENS_7siblingEEEEvOT_PFT0_DpT1_EDpRKT2_ENUlRNS_6detail13function_callEE1_4_FUNESX_
    @     0x7feba39e2d0e pybind11::cpp_function::dispatcher()
    @     0x7fec08c9b577 PyEval_EvalFrameEx
    @     0x7fec08c9da99 PyEval_EvalCodeEx
    @     0x7fec08c9af68 PyEval_EvalFrameEx
    @     0x7fec08c9c54e PyEval_EvalFrameEx
    @     0x7fec08c9c54e PyEval_EvalFrameEx
    @     0x7fec08c9da99 PyEval_EvalCodeEx
    @     0x7fec08c9dcba PyEval_EvalCode
    @     0x7fec08cb701d run_mod
    @     0x7fec08cb81c8 PyRun_FileExFlags
    @     0x7fec08cb93e8 PyRun_SimpleFileExFlags
    @     0x7fec08ccb67c Py_Main
    @     0x7fec07eb4b45 __libc_start_main
```

**Comment by tianxin1860** [comment]
> * 版本、环境信息：
>      1）PaddlePaddle版本：1.3.1
>      2）CPU：
>      3）GPU：gpu Tesla P40, cuda9.0 cudnn7
>      4）系统环境：centos python2.7
> * 问题描述：
> 
> 使用paddle版本enrie模型预测一段时间后就会报如下错误，看不出来是哪一行的问题，请问是为什么？
> 
> ```
> terminate called after throwing an instance of 'paddle::platform::EnforceNotMet'
>   what():  unspecified launch failure at [/paddle/paddle/fluid/framework/details/op_handle_base.cc:37]
> PaddlePaddle Call Stacks:
> 0       0x7feba39b7405p void paddle::platform::EnforceNotMet::Init<char const*>(char const*, char const*, int) + 357
> 1       0x7feba39b7789p paddle::platform::EnforceNotMet::EnforceNotMet(std::__exception_ptr::exception_ptr, char const*, int) + 137
> 2       0x7feba523bfe1p paddle::framework::details::OpHandleBase::~OpHandleBase() + 337
> 3       0x7feba5229e91p paddle::framework::details::FetchOpHandle::~FetchOpHandle() + 17
> 4       0x7feba3a68489p paddle::framework::ir::Node::~Node() + 73
> 5       0x7feba3a68631p paddle::framework::ir::Node::~Node() + 17
> 6       0x7feba522b9cbp paddle::framework::details::ClearFetchOp(paddle::framework::ir::Graph*, std::vector<paddle::framework::details::FetchOpHandle*, std::allocator<paddle::framework::details::FetchOpHandle*> >*) + 1995
> 7       0x7feba51d7254p paddle::framework::details::ThreadedSSAGraphExecutor::Run(std::vector<std::string, std::allocator<std::string> > const&) + 4660
> 8       0x7feba51cd9bap paddle::framework::details::ScopeBufferedSSAGraphExecutor::Run(std::vector<std::string, std::allocator<std::string> > const&) + 394
> 9       0x7feba3af57a2p paddle::framework::ParallelExecutor::Run(std::vector<std::string, std::allocator<std::string> > const&, std::string const&) + 562
> 10      0x7feba39a7d9ep
> 11      0x7feba39e2d0ep
> 12      0x7fec08c9b577p PyEval_EvalFrameEx + 28695
> 13      0x7fec08c9da99p PyEval_EvalCodeEx + 2025
> 14      0x7fec08c9af68p PyEval_EvalFrameEx + 27144
> 15      0x7fec08c9c54ep PyEval_EvalFrameEx + 32750
> 16      0x7fec08c9c54ep PyEval_EvalFrameEx + 32750
> 17      0x7fec08c9da99p PyEval_EvalCodeEx + 2025
> 18      0x7fec08c9dcbap PyEval_EvalCode + 26
> 19      0x7fec08cb701dp
> 20      0x7fec08cb81c8p PyRun_FileExFlags + 120
> 21      0x7fec08cb93e8p PyRun_SimpleFileExFlags + 232
> 22      0x7fec08ccb67cp Py_Main + 2988
> 23      0x7fec07eb4b45p __libc_start_main + 245
> 24      0x7fec08d9d07fp
> 
> *** Aborted at 1564038910 (unix time) try "date -d @1564038910" if you are using GNU date ***
> PC: @                0x0 (unknown)
> *** SIGABRT (@0x1f600006f1e) received by PID 28446 (TID 0x7fec08b9d740) from PID 28446; stack trace: ***
>     @     0x7fec0896c130 (unknown)
>     @     0x7fec07ec89d9 __GI_raise
>     @     0x7fec07eca0e8 __GI_abort
>     @     0x7febfe07d3df __gnu_cxx::__verbose_terminate_handler()
>     @     0x7febfe07bb16 __cxxabiv1::__terminate()
>     @     0x7febfe07af91 __cxa_call_terminate
>     @     0x7febfe07b79d __gxx_personality_v0
>     @     0x7febfe349f56 _Unwind_RaiseException_Phase2
>     @     0x7febfe34a244 _Unwind_RaiseException
>     @     0x7febfe07bd1b __cxa_throw
>     @     0x7feba523bfff paddle::framework::details::OpHandleBase::~OpHandleBase()
>     @     0x7feba5229e91 paddle::framework::details::FetchOpHandle::~FetchOpHandle()
>     @     0x7feba3a68489 paddle::framework::ir::Node::~Node()
>     @     0x7feba3a68631 paddle::framework::ir::Node::~Node()
>     @     0x7feba522b9cb paddle::framework::details::ClearFetchOp()
>     @     0x7feba51d7254 paddle::framework::details::ThreadedSSAGraphExecutor::Run()
>     @     0x7feba51cd9ba paddle::framework::details::ScopeBufferedSSAGraphExecutor::Run()
>     @     0x7feba3af57a2 paddle::framework::ParallelExecutor::Run()
>     @     0x7feba39a7d9e _ZZN8pybind1112cpp_function10initializeIZN6paddle6pybindL18pybind11_init_coreERNS_6moduleEEUlRNS2_9framework16ParallelExecutorERKSt6vectorISsSaISsEERKSsE152_vIS8_SD_SF_EINS_4nameENS_9is_methodENS_7siblingEEEEvOT_PFT0_DpT1_EDpRKT2_ENUlRNS_6detail13function_callEE1_4_FUNESX_
>     @     0x7feba39e2d0e pybind11::cpp_function::dispatcher()
>     @     0x7fec08c9b577 PyEval_EvalFrameEx
>     @     0x7fec08c9da99 PyEval_EvalCodeEx
>     @     0x7fec08c9af68 PyEval_EvalFrameEx
>     @     0x7fec08c9c54e PyEval_EvalFrameEx
>     @     0x7fec08c9c54e PyEval_EvalFrameEx
>     @     0x7fec08c9da99 PyEval_EvalCodeEx
>     @     0x7fec08c9dcba PyEval_EvalCode
>     @     0x7fec08cb701d run_mod
>     @     0x7fec08cb81c8 PyRun_FileExFlags
>     @     0x7fec08cb93e8 PyRun_SimpleFileExFlags
>     @     0x7fec08ccb67c Py_Main
>     @     0x7fec07eb4b45 __libc_start_main
> ```

请问 run 哪个脚本报这个错误？

**Comment by prozhuchen** [comment]
> > * 版本、环境信息：
> >      1）PaddlePaddle版本：1.3.1
> >      2）CPU：
> >      3）GPU：gpu Tesla P40, cuda9.0 cudnn7
> >      4）系统环境：centos python2.7
> > * 问题描述：
> > 
> > 使用paddle版本enrie模型预测一段时间后就会报如下错误，看不出来是哪一行的问题，请问是为什么？
> > ```
> > terminate called after throwing an instance of 'paddle::platform::EnforceNotMet'
> >   what():  unspecified launch failure at [/paddle/paddle/fluid/framework/details/op_handle_base.cc:37]
> > PaddlePaddle Call Stacks:
> > 0       0x7feba39b7405p void paddle::platform::EnforceNotMet::Init<char const*>(char const*, char const*, int) + 357
> > 1       0x7feba39b7789p paddle::platform::EnforceNotMet::EnforceNotMet(std::__exception_ptr::exception_ptr, char const*, int) + 137
> > 2       0x7feba523bfe1p paddle::framework::details::OpHandleBase::~OpHandleBase() + 337
> > 3       0x7feba5229e91p paddle::framework::details::FetchOpHandle::~FetchOpHandle() + 17
> > 4       0x7feba3a68489p paddle::framework::ir::Node::~Node() + 73
> > 5       0x7feba3a68631p paddle::framework::ir::Node::~Node() + 17
> > 6       0x7feba522b9cbp paddle::framework::details::ClearFetchOp(paddle::framework::ir::Graph*, std::vector<paddle::framework::details::FetchOpHandle*, std::allocator<paddle::framework::details::FetchOpHandle*> >*) + 1995
> > 7       0x7feba51d7254p paddle::framework::details::ThreadedSSAGraphExecutor::Run(std::vector<std::string, std::allocator<std::string> > const&) + 4660
> > 8       0x7feba51cd9bap paddle::framework::details::ScopeBufferedSSAGraphExecutor::Run(std::vector<std::string, std::allocator<std::string> > const&) + 394
> > 9       0x7feba3af57a2p paddle::framework::ParallelExecutor::Run(std::vector<std::string, std::allocator<std::string> > const&, std::string const&) + 562
> > 10      0x7feba39a7d9ep
> > 11      0x7feba39e2d0ep
> > 12      0x7fec08c9b577p PyEval_EvalFrameEx + 28695
> > 13      0x7fec08c9da99p PyEval_EvalCodeEx + 2025
> > 14      0x7fec08c9af68p PyEval_EvalFrameEx + 27144
> > 15      0x7fec08c9c54ep PyEval_EvalFrameEx + 32750
> > 16      0x7fec08c9c54ep PyEval_EvalFrameEx + 32750
> > 17      0x7fec08c9da99p PyEval_EvalCodeEx + 2025
> > 18      0x7fec08c9dcbap PyEval_EvalCode + 26
> > 19      0x7fec08cb701dp
> > 20      0x7fec08cb81c8p PyRun_FileExFlags + 120
> > 21      0x7fec08cb93e8p PyRun_SimpleFileExFlags + 232
> > 22      0x7fec08ccb67cp Py_Main + 2988
> > 23      0x7fec07eb4b45p __libc_start_main + 245
> > 24      0x7fec08d9d07fp
> > 
> > *** Aborted at 1564038910 (unix time) try "date -d @1564038910" if you are using GNU date ***
> > PC: @                0x0 (unknown)
> > *** SIGABRT (@0x1f600006f1e) received by PID 28446 (TID 0x7fec08b9d740) from PID 28446; stack trace: ***
> >     @     0x7fec0896c130 (unknown)
> >     @     0x7fec07ec89d9 __GI_raise
> >     @     0x7fec07eca0e8 __GI_abort
> >     @     0x7febfe07d3df __gnu_cxx::__verbose_terminate_handler()
> >     @     0x7febfe07bb16 __cxxabiv1::__terminate()
> >     @     0x7febfe07af91 __cxa_call_terminate
> >     @     0x7febfe07b79d __gxx_personality_v0
> >     @     0x7febfe349f56 _Unwind_RaiseException_Phase2
> >     @     0x7febfe34a244 _Unwind_RaiseException
> >     @     0x7febfe07bd1b __cxa_throw
> >     @     0x7feba523bfff paddle::framework::details::OpHandleBase::~OpHandleBase()
> >     @     0x7feba5229e91 paddle::framework::details::FetchOpHandle::~FetchOpHandle()
> >     @     0x7feba3a68489 paddle::framework::ir::Node::~Node()
> >     @     0x7feba3a68631 paddle::framework::ir::Node::~Node()
> >     @     0x7feba522b9cb paddle::framework::details::ClearFetchOp()
> >     @     0x7feba51d7254 paddle::framework::details::ThreadedSSAGraphExecutor::Run()
> >     @     0x7feba51cd9ba paddle::framework::details::ScopeBufferedSSAGraphExecutor::Run()
> >     @     0x7feba3af57a2 paddle::framework::ParallelExecutor::Run()
> >     @     0x7feba39a7d9e _ZZN8pybind1112cpp_function10initializeIZN6paddle6pybindL18pybind11_init_coreERNS_6moduleEEUlRNS2_9framework16ParallelExecutorERKSt6vectorISsSaISsEERKSsE152_vIS8_SD_SF_EINS_4nameENS_9is_methodENS_7siblingEEEEvOT_PFT0_DpT1_EDpRKT2_ENUlRNS_6detail13function_callEE1_4_FUNESX_
> >     @     0x7feba39e2d0e pybind11::cpp_function::dispatcher()
> >     @     0x7fec08c9b577 PyEval_EvalFrameEx
> >     @     0x7fec08c9da99 PyEval_EvalCodeEx
> >     @     0x7fec08c9af68 PyEval_EvalFrameEx
> >     @     0x7fec08c9c54e PyEval_EvalFrameEx
> >     @     0x7fec08c9c54e PyEval_EvalFrameEx
> >     @     0x7fec08c9da99 PyEval_EvalCodeEx
> >     @     0x7fec08c9dcba PyEval_EvalCode
> >     @     0x7fec08cb701d run_mod
> >     @     0x7fec08cb81c8 PyRun_FileExFlags
> >     @     0x7fec08cb93e8 PyRun_SimpleFileExFlags
> >     @     0x7fec08ccb67c Py_Main
> >     @     0x7fec07eb4b45 __libc_start_main
> > ```
> 
> 请问 run 哪个脚本报这个错误？

我自己重写了一下预测的脚本，主要是想询问下这种错误会不会是显卡的问题？因为我换一张卡同样的代码就可以。
