### ISSUE TITLE
编译错误 mkldnn/mul_mkldnn_op.cc:84:5

### ISSUE THREAD

**Issue by kgdev** [PaddlePaddle/Paddle#18805]
/home/kgdev/Paddle/paddle/fluid/operators/mkldnn/mul_mkldnn_op.cc:84:5: error: operation on ‘dst_fmt’ may be undefined [-Werror=sequence-point]

dst_fmt != (dst_fmt = memory::format::ncdhw)) should it be src_fmt != (dst_fmt = memory::format::ncdhw)) ???

**Comment by luotao1** [comment]
请问能提供更详细的信息么
1. 源码编译的commitid 或版本号？
2. 查看下mkldnn版本号：
```
cd build/third_party/mkldnn/src/extern_mkldnn
git log
```
这是目前develop分支对应的：`commit aef88b7c233f48f8b945da310f1b973da31ad033 (HEAD, tag: v0.20.1, origin/rls-v0.20)`

**Comment by luotao1** [comment]
麻烦再提供以下信息：
- gcc 版本号多少
- 是使用什么镜像编译呢？
- cmake命令是什么？

**Comment by kgdev** [comment]
就是感觉这一行是写错了. 你们看一下呢

**Comment by luotao1** [comment]
@Minghui-Intel @bingyanghuang 帮忙看下？

**Comment by bingyanghuang** [comment]
> @Minghui-Intel @bingyanghuang 帮忙看下？

好的，我们来看一下。

**Comment by Minghui-Intel** [comment]
> > @Minghui-Intel @bingyanghuang 帮忙看下？
> 
> 好的，我们来看一下。

PR has been created. #18816
