### ISSUE TITLE
带 Topk 层的模型使用 TensorRT 预测 Softmax 输出 shape 改变，导致 Topk 校验失败

### ISSUE THREAD

**Issue by mzchtx** [PaddlePaddle/Paddle#18810]
# 问题

模型中在 softmax layer 后接了 Topk layer（如下图），使用 TensorRT 子图预测会导致 softmax 的 shape 变化，触发 Topk layer 的校验失败。

![image](https://user-images.githubusercontent.com/37564754/61854246-4258a300-aef0-11e9-9485-a9c0d1095715.png)

错误信息如下图：

![image](https://user-images.githubusercontent.com/37564754/61854353-7af87c80-aef0-11e9-938a-aa9ebe151161.png)

调试发现如果不使用 TensorRT 子图，则 softmax layer 的输出 shape 为[?, 3073]，而加了 TensorRT 子图后，softmax layer 的输出 shape 为[?, 3073, 1, 1]。

而 paddle Topk layer 中默认取的是 shape 中的最后一个 dim，此时 [?, 3073, 1, 1] 这种情况会断言失败。

![image](https://user-images.githubusercontent.com/37564754/61854665-29042680-aef1-11e9-82b9-d844a7fa4bb7.png)

[code](https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/fluid/operators/top_k_op.cc#L38-L41)

# 环境

+ PaddlePaddle版本：1.5
+ CUDA: 8.0
+ TensorRT: 4.0.1.6
+ CUDNN: 7.1

**Comment by NHZlX** [comment]
trt的输出都是四个纬度的，这个案例我这边先记录一下，后续会进行调整。

**Comment by jeng1220** [comment]
@NHZlX , @mzchtx 
Latest TensorRT supports TopK layer, or you need to call `nvinfer1::ITensor::setDimensions` to reshape tensor dimension
