### ISSUE TITLE
迁移学习，加载部分模型参数问题

### ISSUE THREAD

**Issue by rayliu3798** [PaddlePaddle/Paddle#18818]
想要只加载部分模型参数，然后看到Issue#12428中的这个例子，
[SE_ResNeXt50的例子](https://github.com/oraoto/learn_ml/blob/master/paddle/pretrained.ipynb)

但是里面有一段不能理解：
在函数 network(image, train_base_model=False) 中，
```
    # 复制一个只包含base_model的program，放便只加载需要的参数
    base_model_program = fluid.default_main_program().clone() 
```
然后加载参数的时候是加载在这个克隆出来的base_model_program中，
```
    # 加载参数
    load_pretrained_params(exe, base_model_program)
```

但是训练的时候是训练的另一个添加了fc层的program。

查了API说clone()是“创建一个新的、相同的Program”，说明这个clone的program应该是一个独立的program。那这个参数是怎么加载到模型里的呢？

**Comment by wanghaoshuang** [comment]
program只是网络结构的定义，不包含真实数据。

program_a = program_b.clone()

上述语句相当于对program_b做了deepcopy, 但是program_a和program_b内部variables的名称是一样的。

`load_pretrained_params(exe, program_a)`会去遍历`program_a`中所有Parameter (注：Parameter是Variable的子类)的name，然后将权重文件中的data 加载进来，并放在[fluid.global_scope()](https://www.paddlepaddle.org.cn/documentation/docs/zh/1.5/api_cn/executor_cn.html#global-scope)中.
而Scope是一个dict结构，key是variable name, value是对应的数值。

program_a和program_b共用一个scope，所以，你通过program_a加载进来的weights, 其实对program_b也是可见的。
