### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by Cristhine** [PaddlePaddle/Paddle#18829]
代码运行到：exe.run时候不往下运行
print('before run')
            tmp = [v.name for v in fetch_list]
            print("tmp",tmp)
            losses, yolo_losses, smoke_losses, phone_losses, safe_losses, hand_losses, forward_losses, rcnn_cls_loss, rcnn_box_loss, reid_accs = exe.run(compile_program,
                             fetch_list=[v.name for v in fetch_list])
            print('after run ')
然后内部往数据层reader.py函数定位问题是：
I0726 11:52:52.635735 14512 parallel_executor.cc:329] The number of CUDAPlace, which is used in ParallelExecutor, is 1. And the Program will be copied 1 copies
I0726 11:52:52.648255 14512 build_strategy.cc:329] set enable_sequential_execution:1
I0726 11:53:16.614534 14512 build_strategy.cc:340] SeqOnlyAllReduceOps:0, num_trainers:1
/home/vis/data/chezai/det/v6/data/images/aiflow/driver_behavior_201810/data/1000564840,664546799.jpg
h,w 288 352
weight
before mean
out_img before
out_img after
final
after img_reader2
before batch_out
batch_out 1
batch_size 1
total_iter =  0
img_size 320
Segmentation fault
并且测试多次，每次不是同一幅图片 同样的位置。

**Comment by chengduoZH** [comment]
@Cristhine  你这是什么模型？用什么版本的paddle跑的？
在`/tmp/`路径下有`paddle.xxx`文件吗？可以贴一下吗？

**Comment by Cristhine** [comment]
> @Cristhine 你这是什么模型？用什么版本的paddle跑的？
> 在`/tmp/`路径下有`paddle.xxx`文件吗？可以贴一下吗？

用的版本是paddle1.5.1 cuda8 在/tmp/下没有paddle.xxx文件

**Comment by Cristhine** [comment]
> > @Cristhine 你这是什么模型？用什么版本的paddle跑的？
> > 在`/tmp/`路径下有`paddle.xxx`文件吗？可以贴一下吗？
> 
> 用的版本是paddle1.5.1 cuda8 在/tmp/下没有paddle.xxx文件

模型的话是一个改进版的yolov3 模型

**Comment by Cristhine** [comment]
辛苦定位问题，最终问题定位在cudnn版本问题，paddle编译使用的cudnn7.0我使用过程中使用了cudnn6.0

**Comment by fire717** [comment]
我也遇到这个问题了 也是自定义模型 但是我是cpu跑的 use_gpu=False  应该和cudnn无关吧 还是报这个错
