### ISSUE TITLE
运行某些单元测试会卡住,没有报错信息，不方便Debug

### ISSUE THREAD

**Issue by silingtong123** [PaddlePaddle/Paddle#18822]
经过测试在paddlepaddle-gpu的1.4.1和1.5.1版本中，运行的单元测试test_mean_op.py,test_mean_op.py会卡住，而且没有任何报错信息
<img width="665" alt="753277d9f2abd933c183bcf43c9ea47f" src="https://user-images.githubusercontent.com/35439432/61875747-eb69c280-af1d-11e9-8e86-f5bce74ab8ac.png">

**Comment by wanghaoshuang** [comment]
某些情况下，在运行单测前，设置下CUDA_VISIBLE_DEVICES为单卡，会有明显加速。
