### ISSUE TITLE
fluid1.5 fleet.init 调用失败

### ISSUE THREAD

**Issue by sshilei** [PaddlePaddle/Paddle#18828]
按照这个wiki写的程序， http://wiki.baidu.com/pages/viewpage.action?pageId=730430867

 import paddle.fluid.incubate.fleet.collective as fleet
fleet.init()

Traceback (most recent call last):
  File "/home/map/rd/wushilei/code/paddle-frame/baidu/mapsearch/paddle-frame/frame/scheduler/../..//frame/core/gpu_dataset_trainer.py", line 33, in <module>
    fleet.init()
AttributeError: 'module' object has no attribute 'init'

**Comment by Superjomn** [comment]
@wangguibao 找同学看下吧

**Comment by guru4elephant** [comment]
参考https://github.com/PaddlePaddle/Fleet给出的quick start示例，另外请使用最新的develop，我们会在1.5.2发布一些新feature

**Comment by sandyhouse** [comment]
import部分该用下面的语句：
from paddle.fluid.incubate.fleet.collective import fleet
具体可参考：http://wiki.baidu.com/display/PDLPDL/ResNet50+on+ImageNet
@sshilei

**Comment by sshilei** [comment]
> 另外请使用最新的develop，我们会在1.5.2发布一些新feature

谢谢各位。

请问1.5.2的新feature有wiki或者参考文档吗？ develop版从哪里下载？谢谢

**Comment by sshilei** [comment]
@guru4elephant

**Comment by sshilei** [comment]
> quick start 中  ：
> role = role_maker.PaddleCloudRoleMaker(is_collective=True)
> fleet.init(role) 

> 报错
>   File "/home/map/rd/wushilei/code/paddle-frame/baidu/mapsearch/paddle-frame/frame/scheduler/../..//frame/core/gpu_dataset_trainer.py", line 163, in <module>
>     ret = trainer.start(sys.argv)
>   File "/home/map/rd/wushilei/code/paddle-frame/baidu/mapsearch/paddle-frame/frame/scheduler/../..//frame/core/gpu_dataset_trainer.py", line 151, in start
>     self.set_optimizer(FLAGS, net_output)
>   File "/home/map/rd/wushilei/code/paddle-frame/baidu/mapsearch/paddle-frame/frame/scheduler/../..//frame/core/gpu_dataset_trainer.py", line 119, in set_optimizer
>     role = role_maker.PaddleCloudRoleMaker(is_collective=True)
> TypeError: __init__() got an unexpected keyword argument 'is_collective'

**Comment by sshilei** [comment]
https://github.com/PaddlePaddle/Fleet/blob/develop/examples/quick-start/collective_train.py

**Comment by sshilei** [comment]
单机多卡的role_maker应该怎么写呢？wiki上的也不太适合。暂时没有找到。谢谢

**Comment by sandyhouse** [comment]
develop版下载路径可参考：https://www.paddlepaddle.org.cn/documentation/docs/zh/1.5/beginners_guide/install/Tables.html/#ciwhls。
另外你用的哪个版本的paddle @sshilei

**Comment by sshilei** [comment]
我用的是fluid 1.5.1     cuda9-cudnn7-mkl
--

**Comment by sandyhouse** [comment]
建议通过launch.py 启动多进程模式。
