### ISSUE TITLE
单机命令paddle train的参数设置

### ISSUE THREAD

**Issue by ssdyue** [PaddlePaddle/Paddle#1883]
paddle train启动一个trainer进程，其中各参数是在哪定义的？尤其是use_gpu和trainer_count，特别不明白多GPU的调用，在底层是如何运作的？

**Comment by qingqing01** [comment]
@ssdyue use_gpu, trainer_count的意思可以看这个文档：http://www.paddlepaddle.org/develop/doc_cn/howto/usage/cmd_parameter/detail_introduction_cn.html  trainer_count的文档里有解释多GPU的数据划分。 有问题我们可以再讨论 :)

**Comment by ssdyue** [comment]
@qingqing01 谢谢您的回答！我还想问一下：trainer_count实现数据的多GPU并行，那么在paddlepaddle中模型或者算法能否实现多GPU并行？

**Comment by qingqing01** [comment]
> 模型或者算法能否实现多GPU并行？

算法并行不是特别理解你说的，模型并行在PaddlePaddle，可以将不同的layer并行在不同的GPU上，可以参考 http://www.paddlepaddle.org/develop/doc_cn/howto/usage/cmd_parameter/use_case_cn.html#parallel-nn

**Comment by ssdyue** [comment]
@qingqing01 十分感谢！请问下：PaddlePaddle实现数据和模型的多GPU并行，其源码具体是在哪个文件里，想参考下 :)

**Comment by qingqing01** [comment]
在这个文件夹：https://github.com/PaddlePaddle/Paddle/tree/develop/paddle/gserver/gradientmachines 主要涉及MultiGradientMachine 和 ParallelNeuralNetwork。
