### ISSUE TITLE
能否支持 java 进行 infer

### ISSUE THREAD

**Issue by airlsyn** [PaddlePaddle/Paddle#18839]
欢迎您对PaddlePaddle提出建议，非常感谢您对PaddlePaddle的贡献！
在留下您的建议时，辛苦您同步提供如下信息：
- 版本、环境信息
1）PaddlePaddle版本：1,5,1
2）CPU/GPU：CPU
3）系统环境：Mac OS 10.13
- 复现信息：
- 建议描述：能否支持 java 进行 infer

**Comment by yeyupiaoling** [comment]
如果要Java的话，可以使用Android的jni接口，具体请查看 https://github.com/PaddlePaddle/paddle-mobile

**Comment by airlsyn** [comment]
谢谢，我先试试，有问题再来请教。

**Comment by Superjomn** [comment]
Paddle 的应该是不支持 java 预测的，mobile 支持.

目前支持 C++ API；计划支持 C API

**Comment by airlsyn** [comment]
> Paddle 的应该是不支持 java 预测的，mobile 支持.
> 
> 目前支持 C++ API；计划支持 C API

那看样子应该可以通过[javacpp-presets](https://github.com/bytedeco/javacpp-presets)来做个 bind
