### ISSUE TITLE
参数说明跟实际参数不一致

### ISSUE THREAD

**Issue by xjqbest** [PaddlePaddle/Paddle#18855]
# **如下实际并没有这个参数，这种错误很严重啊！**

https://www.paddlepaddle.org.cn/documentation/docs/zh/1.5/api_cn/io_cn.html

![image](https://user-images.githubusercontent.com/12492564/61991097-02272b00-b07e-11e9-8054-47db50b403d0.png)

![image](https://user-images.githubusercontent.com/12492564/61991104-0e12ed00-b07e-11e9-9db0-d1919ee41889.png)

**Comment by yeyupiaoling** [comment]
是啊，vars这个参数只有fluid.io.save_vars() 才有。

**Comment by xjqbest** [comment]
well , since nobody cares， just close.
