### ISSUE TITLE
同一个进程中，执行多个Executor Program、构图，多次inference，他们之间会相互干扰吗？在ut中，一个进程构建多个case每个case构建Program Executor、并构图进行inference，发现只有第一次执行的case才能正确输出，其他case正常输出但输出结果不符合预期。

### ISSUE THREAD

**Issue by kelvict** [PaddlePaddle/Paddle#18859]
同一个进程中，执行多个Executor Program、构图，多次inference，他们之间会相互干扰吗？在ut中，一个进程构建多个case每个case构建Program Executor、并构图进行inference，发现只有第一次执行的case才能正确输出，其他case正常输出但输出结果不符合预期。

**Comment by phlrain** [comment]
同用户线下解决
