### ISSUE TITLE
GPU training with CPU Embedding support

### ISSUE THREAD

**Issue by Yelrose** [PaddlePaddle/Paddle#18850]
是否可以有像tensorflow一样的设置训练的流程有一部分在cpu中执行，一部分在gpu中执行。目前embedding可以在内存放的下，但是在显存放不下，除了使用fleet模式，是否有别的办法替代。

**Comment by Yelrose** [comment]
paddle文档的 force_init_on_cpu等均无效

**Comment by Superjomn** [comment]
目前应该没法支持。  CPU 模式则占显存，GPU 模式，则所有参数会在 GPU 上放一份
