### ISSUE TITLE
能否给出GPU的使用率？

### ISSUE THREAD

**Issue by die1100** [PaddlePaddle/Paddle#18858]
使用notebook的时候，每次都是运行一个单元格，上一个训练的单元格未训练完成，下个也不能执行，但是需要看下显存和GPU使用率是否充分利用，这个时候如果正在执行训练程序，没法看到GPU的使用率。

**Comment by yeyupiaoling** [comment]
@die1100 这是用命令：nvidia-smi  就可以查看了。

**Comment by OliverLPH** [comment]
notebook里可以用 
```shell
!nvidia-smi
```

**Comment by die1100** [comment]
先谢谢两位，我知道这个命令，但是我可能提问错地方了。

我是想给百度的aistudio提建议，因为在线的notebook，运行某些代码单元时会长时间的执行，不会执行其他单元格的代码，但是我想看下显存和使用率是否有充分利用，这个时候在其他的单元格内执行 nvidia-smi 是会等待上个单元格执行完成。

如果是自己本地，可以在命令行执行nvidia-smi看显存，线上的感觉好像没地方看。
