### ISSUE TITLE
单机多卡， lauch多进程， not ready endpoints:['127.0.0.1:6172']

### ISSUE THREAD

**Issue by sshilei** [PaddlePaddle/Paddle#18866]
![image](https://user-images.githubusercontent.com/18701471/62019995-c01ff580-b1f3-11e9-9395-32b55562f1f3.png)

**Comment by sshilei** [comment]
训练启动命令：

${fluid_bin} -m paddle.distributed.launch --selected_gpus="1,2,3" ${root_dir}/frame/core/gpu_dataset_trainer.py --conf_file ${config_conf}

**Comment by sandyhouse** [comment]
--selected_gpus="1,2,3" 应该设置成“0,1,2"
