### ISSUE TITLE
attention 模型预测库cpu下测试内存增长，gpu下显存增长

### ISSUE THREAD

**Issue by saberSabersaber** [PaddlePaddle/Paddle#18868]
attention 模型预测库cpu下测试内存增长，gpu下显存增长

**Comment by sneaxiy** [comment]
请您提供完整的复现环境，方便我们排查原因。

**Comment by Shixiaowei02** [comment]
如hi沟通，问题已修复。

**Comment by fuyi02** [comment]
![image](https://user-images.githubusercontent.com/39895596/62597150-a713f480-b917-11e9-987d-9d28e511e36e.png)
