### ISSUE TITLE
怎么取相反数

### ISSUE THREAD

**Issue by luzm3** [PaddlePaddle/Paddle#18878]
`
outputs = fluid.layers.dropout(outputs, 0.5)
 emission = fluid.layers.fc(size=num_label, input=outputs)
 crf_cost = fluid.layers.linear_chain_crf(
		input=emission,
		label=tags,
		param_attr=fluid.ParamAttr(name="crfw", ))
 avg_cost = fluid.layers.mean(x=crf_cost)
`
1.在这里我想对CRF得出的loss做reduce_mean操作之后再取个相反数，想知道要怎么做？ 2.reduce_mean之后是一个shape为一的loss，如果没有取反的op的话，我需要乘一个等于-1的张量，请问这个张量怎么实现？

**Comment by luzm3** [comment]
<img width="470" alt="image" src="https://user-images.githubusercontent.com/45001329/62037206-f1191e00-b225-11e9-8304-c55c54cc0420.png">
第一问已解决，第二问帮忙解决下呗

**Comment by sneaxiy** [comment]
您可以使用`fluid.layers.fill_constant(shape=[1], dtype='float32', value=-1)`来解决第二个问题。

**Comment by sneaxiy** [comment]
第一个问题也可以用类似方法解决，fill_constant后跟您的tensor相乘即可。

**Comment by luzm3** [comment]
> 第一个问题也可以用类似方法解决，fill_constant后跟您的tensor相乘即可。

好的 谢谢
