### ISSUE TITLE
Loading model fails for book/06.label_semantic_roles

### ISSUE THREAD

**Issue by sanjaymeena** [PaddlePaddle/Paddle#1887]
Hello, 

* docker image : paddlepaddle/paddle:0.10.0rc3 
* demo :  book/06.label_semantic_roles

Issue : Can train model successfully using the provided train.py and the program saves the parameters.  
I tried loading the saved parameters using : 
```
from  paddle.v2.parameters import  Parameters 
f="params_pass_2.tar.gz"
parameters=Parameters.from_tar(f)
```
It fails with following error :  
![image](https://cloud.githubusercontent.com/assets/5145685/25375687/18c8b852-29d4-11e7-8994-0cd5d43b3ab3.png)

**Comment by luotao1** [comment]
you can use following codes to load the saved parameters:
```
with gzip.open('params.tar.gz', 'w') as f:
    parameters = Parameters.to_tar(f)
```

**Comment by sanjaymeena** [comment]
I want to load the parameters back from the saved tar file . The parameters have already been saved during training.

**Comment by sanjaymeena** [comment]
Hi, I am training a Semantic role labeling model on 20k chinese sentences in CONLL2005 format. 

docker image : paddlepaddle/paddle:0.10.0rc3
demo : book/06.label_semantic_roles

I am getting following error . Can you help me decipher what may be going wrong. I checked and data format is correct and works for small amount of data ~100 sentences. 

![image](https://cloud.githubusercontent.com/assets/5145685/25478897/7ed37748-2b75-11e7-80c6-6c4ae13c6038.png)

**Comment by gangliao** [comment]
Hi,

Why not fetch book docker image directly ?https://github.com/PaddlePaddle/book/blob/develop/README.en.md

**Comment by sanjaymeena** [comment]
I had tried following images few times before as well just now : 
* docker.paddlepaddle.org/book
* docker.paddlepaddle.org/book:0.10.0rc2

I get the same error :( what is the solution for this?

![image](https://cloud.githubusercontent.com/assets/5145685/25511860/4a5e7d46-2bfc-11e7-8028-bcc893277a6d.png)

**Comment by gangliao** [comment]
please fetch  `docker.paddlepaddle.org/book:0.10.0rc3`, I update it now.

**Comment by sanjaymeena** [comment]
okay. I will try the jupyter notebook as it is still giving me following error : 
![image](https://cloud.githubusercontent.com/assets/5145685/25513693/c6b44bfc-2c09-11e7-85d4-d7822c51c68a.png)


* I wanted to share that this error is systematic and is occurring when the sentence is the last sentence in the data. The train.py runs till the end of the file data and then while loading next batch throws me the error. 
* I will have double checked the conll05 format of my data and it is the same as present in demo program. I will try jupyter to make sure if it is related to paddle or my data. 
Many thanks for prompt response! have been stuck since many days :(

**Comment by sanjaymeena** [comment]
@gangliao I can run the train.py with my data. Turns out problem was with some syntax in data. Thanks for updated book:0.10.0rc3.

**Comment by sanjaymeena** [comment]
Hi, I still got this error using : book:0.10.0rc3. This was after 26th pass. So probably means something wrong with framework??

![image](https://cloud.githubusercontent.com/assets/5145685/25523926/10fbd6f4-2c3b-11e7-86be-b34d0171d1f8.png)

**Comment by wanghaoshuang** [comment]
About float point exception: #3076
