### ISSUE TITLE
BUG: cifar data reader开启cycle参数存在死循环且效率低下

### ISSUE THREAD

**Issue by Gaffey** [PaddlePaddle/Paddle#18883]
- 版本、环境信息：
    1）PaddlePaddle版本：paddle 1.5 post97

- 复现信息：
在使用`paddle.dataset.cifar.train10()`时添加cycle=True参数，程序会卡死，ctrl+c中断发现卡死在reader中
断点调试发现如下
<img width="1280" alt="image" src="https://user-images.githubusercontent.com/7568594/62044377-650ef280-b235-11e9-8fa3-e17c098acdf6.png">
一个epoch迭代结束后，迭代器没有重置，无法继续迭代，程序不停的在while True内空跑。

另外，建议reader进行修改，每次都做extractfile感觉效率太低

**Comment by sneaxiy** [comment]
cycle这个参数本身应该就是while True死循环的。如果您想cache数据，您可以尝试用`paddle.reader.cache`把数据cache在内存中。

**Comment by Gaffey** [comment]
> cycle这个参数本身应该就是while True死循环的。如果您想cache数据，您可以尝试用`paddle.reader.cache`把数据cache在内存中。

 @sneaxiy 本身死循环不是问题，问题是他没有在取数据

**Comment by sneaxiy** [comment]
感谢您的反馈，这应该是个bug。
