### ISSUE TITLE
paddle在NER上精度明显低于tensorflow

### ISSUE THREAD

**Issue by luzm3** [PaddlePaddle/Paddle#18884]
![image](https://user-images.githubusercontent.com/45001329/62046168-d3ee4a80-b239-11e9-8269-040ef192c3fe.png)

**Comment by luzm3** [comment]
![image](https://user-images.githubusercontent.com/45001329/62046056-8ffb4580-b239-11e9-84ea-c0053cf72e1c.png)
这是paddle的模型结构

**Comment by luzm3** [comment]
![image](https://user-images.githubusercontent.com/45001329/62098609-a64ae500-b2bd-11e9-93e7-2f958e0b77b2.png)

**Comment by luzm3** [comment]
![image](https://user-images.githubusercontent.com/45001329/62098639-cc708500-b2bd-11e9-8717-00f432ac5cd3.png)

**Comment by luzm3** [comment]
上面是tensorflow的模型架构，self.CRF = True，optimizer=Adam(lr=0.001),但是paddle的结果却比tensorflow差4%左右，经过实验发现，paddle在学习率相同的情况下，在该实验中的拟合能力比tensorflow要差很多，下面贴图，想问问大家觉得会是什么原因呢？

**Comment by luzm3** [comment]
下图是在开发集上的评价指标F1的对比
![image](https://user-images.githubusercontent.com/45001329/62098855-c038f780-b2be-11e9-8484-edbdbd8e8c17.png)

**Comment by luzm3** [comment]
环境配置：
GPU:NVIDIA Telsa K80
tensorflow-gpu：1.14
paddlepaddle-gpu:：1.51 
实验设置：
1.基于字的Bilstm + CRF

2.字向量均随机初始化为300维

3.前向和后向lstm细胞单元数均为300

4.batch_size为256

4.评价方式为F1

5.训练集45592个句子，验证集5066个句子，测试集4631个句子

**Comment by heavengate** [comment]
请排查一下方面：
1. 使用相同的输入相同的权重看网络输出是否一致，确认网络结构对齐
2. 确认其他操作是否一致，optimizer等参数是否一致

**Comment by luzm3** [comment]
已解决，是因为cell_activation的原因,lstm中cell_activation要用tanh，而我却用了sigmoid
