### ISSUE TITLE
因为paddle和tf实现模型效果相差较大，因此想了解一下embedding层的矩阵初始化的具体实现

### ISSUE THREAD

**Issue by luzm3** [PaddlePaddle/Paddle#18881]
我最近用paddle和tensorflow分别实现了一下NER模型，超参数据集保持一致，但是paddle却比tensorflow低了4个点，因此想了解一下embedding层和fc层的矩阵初始化方法。

**Comment by adaxi123** [comment]
@luzm3  随机初始化，可以指定随机分布种类，如果没有指定，默认应该是Xavier

**Comment by luzm3** [comment]
好的，谢谢！




------------------ 原始邮件 ------------------
发件人: "adaxi123"<notifications@github.com>; 
发送时间: 2019年7月29日(星期一) 晚上7:38
收件人: "PaddlePaddle/Paddle"<Paddle@noreply.github.com>; 
抄送: "非洲人的美国梦"<2805829069@qq.com>; "Mention"<mention@noreply.github.com>; 
主题: Re: [PaddlePaddle/Paddle] 因为paddle和tf实现模型效果相差较大，因此想了解一下embedding层的矩阵初始化的具体实现 (#18881)




@luzm3  随机初始化，可以指定随机分布种类，如果没有指定，默认应该是Xavier
