### ISSUE TITLE
为什么会出现这个问题，帮我看一下（是打完pip3 install paddlepaddle之后）

### ISSUE THREAD

**Issue by Jhon714-cooler** [PaddlePaddle/Paddle#18886]
/s eta 0:00:08ERROR: Exception:
Traceback (most recent call last):
  File "c:\users\administrator\appdata\local\programs\python\python37\lib\site-p
ackages\pip\_vendor\urllib3\response.py", line 397, in _error_catcher
    yield
  File "c:\users\administrator\appdata\local\programs\python\python37\lib\site-p
ackages\pip\_vendor\urllib3\response.py", line 479, in read
    data = self._fp.read(amt)
  File "c:\users\administrator\appdata\local\programs\python\python37\lib\site-p
ackages\pip\_vendor\cachecontrol\filewrapper.py", line 62, in read
    data = self.__fp.read(amt)
  File "c:\users\administrator\appdata\local\programs\python\python37\lib\http\c
lient.py", line 457, in read
    n = self.readinto(b)
  File "c:\users\administrator\appdata\local\programs\python\python37\lib\http\c
lient.py", line 501, in readinto
    n = self.fp.readinto(b)
  File "c:\users\administrator\appdata\local\programs\python\python37\lib\socket
.py", line 589, in readinto
    return self._sock.recv_into(b)
  File "c:\users\administrator\appdata\local\programs\python\python37\lib\ssl.py
", line 1071, in recv_into
    return self.read(nbytes, buffer)
  File "c:\users\administrator\appdata\local\programs\python\python37\lib\ssl.py
", line 929, in read
    return self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\administrator\appdata\local\programs\python\python37\lib\site-p
ackages\pip\_internal\cli\base_command.py", line 188, in main
    status = self.run(options, args)
  File "c:\users\administrator\appdata\local\programs\python\python37\lib\site-p
ackages\pip\_internal\commands\install.py", line 345, in run
    resolver.resolve(requirement_set)
  File "c:\users\administrator\appdata\local\programs\python\python37\lib\site-p
ackages\pip\_internal\legacy_resolve.py", line 196, in resolve
    self._resolve_one(requirement_set, req)
  File "c:\users\administrator\appdata\local\programs\python\python37\lib\site-p
ackages\pip\_internal\legacy_resolve.py", line 359, in _resolve_one
    abstract_dist = self._get_abstract_dist_for(req_to_install)
  File "c:\users\administrator\appdata\local\programs\python\python37\lib\site-p
ackages\pip\_internal\legacy_resolve.py", line 307, in _get_abstract_dist_for
    self.require_hashes
  File "c:\users\administrator\appdata\local\programs\python\python37\lib\site-p
ackages\pip\_internal\operations\prepare.py", line 199, in prepare_linked_requir
ement
    progress_bar=self.progress_bar
  File "c:\users\administrator\appdata\local\programs\python\python37\lib\site-p
ackages\pip\_internal\download.py", line 1050, in unpack_url
    progress_bar=progress_bar
  File "c:\users\administrator\appdata\local\programs\python\python37\lib\site-p
ackages\pip\_internal\download.py", line 910, in unpack_http_url
    progress_bar)
  File "c:\users\administrator\appdata\local\programs\python\python37\lib\site-p
ackages\pip\_internal\download.py", line 1138, in _download_http_url
    _download_url(resp, link, content_file, hashes, progress_bar)
  File "c:\users\administrator\appdata\local\programs\python\python37\lib\site-p
ackages\pip\_internal\download.py", line 847, in _download_url
    hashes.check_against_chunks(downloaded_chunks)
  File "c:\users\administrator\appdata\local\programs\python\python37\lib\site-p
ackages\pip\_internal\utils\hashes.py", line 75, in check_against_chunks
    for chunk in chunks:
  File "c:\users\administrator\appdata\local\programs\python\python37\lib\site-p
ackages\pip\_internal\download.py", line 815, in written_chunks
    for chunk in chunks:
  File "c:\users\administrator\appdata\local\programs\python\python37\lib\site-p
ackages\pip\_internal\utils\ui.py", line 156, in iter
    for x in it:
  File "c:\users\administrator\appdata\local\programs\python\python37\lib\site-p
ackages\pip\_internal\download.py", line 804, in resp_read
    decode_content=False):
  File "c:\users\administrator\appdata\local\programs\python\python37\lib\site-p
ackages\pip\_vendor\urllib3\response.py", line 531, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "c:\users\administrator\appdata\local\programs\python\python37\lib\site-p
ackages\pip\_vendor\urllib3\response.py", line 496, in read
    raise IncompleteRead(self._fp_bytes_read, self.length_remaining)
  File "c:\users\administrator\appdata\local\programs\python\python37\lib\contex
tlib.py", line 130, in __exit__
    self.gen.throw(type, value, traceback)
  File "c:\users\administrator\appdata\local\programs\python\python37\lib\site-p
ackages\pip\_vendor\urllib3\response.py", line 402, in _error_catcher
    raise ReadTimeoutError(self._pool, None, 'Read timed out.')
pip._vendor.urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='files
.pythonhosted.org', port=443): Read timed out.

C:\Users\Administrator>

**Comment by heavengate** [comment]
看报错信息是无法连接到pip源，可以确认一下是不是网络的问题，或者修改一下pip源的配置到你能连接到的pip源

**Comment by Jhon714-cooler** [comment]
那怎么修改piP源配置

**Comment by Jhon714-cooler** [comment]
@heavengate

**Comment by heavengate** [comment]
https://blog.csdn.net/lwgkzl/article/details/80935453  网络上有很多教程都可以参考下~

**Comment by Jhon714-cooler** [comment]
Microsoft Windows [版本 6.1.7601]
版权所有 (c) 2009 Microsoft Corporation。保留所有权利。

C:\Users\Administrator>pip3 install paddlepaddle
Requirement already satisfied: paddlepaddle in c:\users\administrator\appdata\lo
cal\programs\python\python37\lib\site-packages (1.5.1)
Requirement already satisfied: scipy; python_version >= "3.5" in c:\users\admini
strator\appdata\local\programs\python\python37\lib\site-packages (from paddlepad
dle) (1.3.0)
Requirement already satisfied: Pillow in c:\users\administrator\appdata\local\pr
ograms\python\python37\lib\site-packages (from paddlepaddle) (6.1.0)
Requirement already satisfied: recordio>=0.1.0 in c:\users\administrator\appdata
\local\programs\python\python37\lib\site-packages (from paddlepaddle) (0.1.7)
Requirement already satisfied: graphviz in c:\users\administrator\appdata\local\
programs\python\python37\lib\site-packages (from paddlepaddle) (0.11.1)
Requirement already satisfied: funcsigs in c:\users\administrator\appdata\local\
programs\python\python37\lib\site-packages (from paddlepaddle) (1.0.2)
Requirement already satisfied: pyyaml in c:\users\administrator\appdata\local\pr
ograms\python\python37\lib\site-packages (from paddlepaddle) (5.1.1)
Requirement already satisfied: numpy>=1.12 in c:\users\administrator\appdata\loc
al\programs\python\python37\lib\site-packages (from paddlepaddle) (1.17.0)
Requirement already satisfied: opencv-python in c:\users\administrator\appdata\l
ocal\programs\python\python37\lib\site-packages (from paddlepaddle) (4.1.0.25)
Requirement already satisfied: decorator in c:\users\administrator\appdata\local
\programs\python\python37\lib\site-packages (from paddlepaddle) (4.4.0)
Requirement already satisfied: prettytable in c:\users\administrator\appdata\loc
al\programs\python\python37\lib\site-packages (from paddlepaddle) (0.7.2)
Requirement already satisfied: matplotlib; python_version >= "3.6" in c:\users\a
dministrator\appdata\local\programs\python\python37\lib\site-packages (from padd
lepaddle) (3.1.1)
Requirement already satisfied: six in c:\users\administrator\appdata\local\progr
ams\python\python37\lib\site-packages (from paddlepaddle) (1.12.0)
Requirement already satisfied: protobuf>=3.1.0 in c:\users\administrator\appdata
\local\programs\python\python37\lib\site-packages (from paddlepaddle) (3.9.0)
Requirement already satisfied: requests>=2.20.0 in c:\users\administrator\appdat
a\local\programs\python\python37\lib\site-packages (from paddlepaddle) (2.22.0)
Requirement already satisfied: nltk; python_version >= "3.5" in c:\users\adminis
trator\appdata\local\programs\python\python37\lib\site-packages (from paddlepadd
le) (3.4.4)
Requirement already satisfied: rarfile in c:\users\administrator\appdata\local\p
rograms\python\python37\lib\site-packages (from paddlepaddle) (3.0)
Requirement already satisfied: kiwisolver>=1.0.1 in c:\users\administrator\appda
ta\local\programs\python\python37\lib\site-packages (from matplotlib; python_ver
sion >= "3.6"->paddlepaddle) (1.1.0)
Requirement already satisfied: python-dateutil>=2.1 in c:\users\administrator\ap
pdata\local\programs\python\python37\lib\site-packages (from matplotlib; python_
version >= "3.6"->paddlepaddle) (2.8.0)
Requirement already satisfied: cycler>=0.10 in c:\users\administrator\appdata\lo
cal\programs\python\python37\lib\site-packages (from matplotlib; python_version
>= "3.6"->paddlepaddle) (0.10.0)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 in c:\us
ers\administrator\appdata\local\programs\python\python37\lib\site-packages (from
 matplotlib; python_version >= "3.6"->paddlepaddle) (2.4.2)
Requirement already satisfied: setuptools in c:\users\administrator\appdata\loca
l\programs\python\python37\lib\site-packages (from protobuf>=3.1.0->paddlepaddle
) (40.8.0)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in c:\users\administrator\a
ppdata\local\programs\python\python37\lib\site-packages (from requests>=2.20.0->
paddlepaddle) (3.0.4)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\administrator\appd
ata\local\programs\python\python37\lib\site-packages (from requests>=2.20.0->pad
dlepaddle) (2019.6.16)
Requirement already satisfied: idna<2.9,>=2.5 in c:\users\administrator\appdata\
local\programs\python\python37\lib\site-packages (from requests>=2.20.0->paddlep
addle) (2.8)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in c:\use
rs\administrator\appdata\local\programs\python\python37\lib\site-packages (from
requests>=2.20.0->paddlepaddle) (1.25.3)

C:\Users\Administrator>python
Python 3.7.0 (default, Jun 28 2018, 08:04:48) [MSC v.1912 64 bit (AMD64)] :: Ana
conda, Inc. on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import paddle.fluid
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'paddle'
@heavengate

**Comment by heavengate** [comment]
pip3 list 看下

**Comment by Jhon714-cooler** [comment]
Microsoft Windows [版本 6.1.7601]
版权所有 (c) 2009 Microsoft Corporation。保留所有权利。

C:\Users\Administrator>pip freeze
alabaster==0.7.11
anaconda-client==1.7.2
anaconda-navigator==1.9.2
anaconda-project==0.8.2
appdirs==1.4.3
asn1crypto==0.24.0
astroid==2.0.4
astropy==3.0.4
atomicwrites==1.2.1
attrs==18.2.0
Automat==0.7.0
Babel==2.6.0
backcall==0.1.0
backports.shutil-get-terminal-size==1.0.0
beautifulsoup4==4.6.3
bitarray==0.8.3
bkcharts==0.2
blaze==0.11.3
bleach==2.1.4
bokeh==0.13.0
boto==2.49.0
Bottleneck==1.2.1
certifi==2018.8.24
cffi==1.11.5
chardet==3.0.4
click==6.7
cloudpickle==0.5.5
clyent==1.2.2
colorama==0.3.9
comtypes==1.1.7
conda==4.5.11
conda-build==3.15.1
constantly==15.1.0
contextlib2==0.5.5
cryptography==2.3.1
cycler==0.10.0
Cython==0.28.5
cytoolz==0.9.0.1
dask==0.19.1
datashape==0.5.4
decorator==4.3.0
defusedxml==0.5.0
distributed==1.23.1
docutils==0.14
entrypoints==0.2.3
et-xmlfile==1.0.1
fastcache==1.0.2
filelock==3.0.8
Flask==1.0.2
Flask-Cors==3.0.6
gevent==1.3.6
glob2==0.6
greenlet==0.4.15
h5py==2.8.0
heapdict==1.0.0
html5lib==1.0.1
hyperlink==18.0.0
idna==2.7
imageio==2.4.1
imagesize==1.1.0
incremental==17.5.0
ipykernel==4.10.0
ipython==6.5.0
ipython-genutils==0.2.0
ipywidgets==7.4.1
isort==4.3.4
itsdangerous==0.24
jdcal==1.4
jedi==0.12.1
Jinja2==2.10
jsonschema==2.6.0
jupyter==1.0.0
jupyter-client==5.2.3
jupyter-console==5.2.0
jupyter-core==4.4.0
jupyterlab==0.34.9
jupyterlab-launcher==0.13.1
keyring==13.2.1
kiwisolver==1.0.1
lazy-object-proxy==1.3.1
llvmlite==0.24.0
locket==0.2.0
lxml==4.2.5
MarkupSafe==1.0
matplotlib==2.2.3
mccabe==0.6.1
menuinst==1.4.14
mistune==0.8.3
mkl-fft==1.0.4
mkl-random==1.0.1
more-itertools==4.3.0
mpmath==1.0.0
msgpack==0.5.6
multipledispatch==0.6.0
navigator-updater==0.2.1
nbconvert==5.4.0
nbformat==4.4.0
networkx==2.1
nltk==3.3
nose==1.3.7
notebook==5.6.0
numba==0.39.0
numexpr==2.6.8
numpy==1.15.1
numpydoc==0.8.0
odo==0.5.1
olefile==0.46
openpyxl==2.5.6
packaging==17.1
pandas==0.23.4
pandocfilters==1.4.2
parso==0.3.1
partd==0.3.8
path.py==11.1.0
pathlib2==2.3.2
patsy==0.5.0
pep8==1.7.1
pickleshare==0.7.4
Pillow==5.2.0
pkginfo==1.4.2
pluggy==0.7.1
ply==3.11
prometheus-client==0.3.1
prompt-toolkit==1.0.15
psutil==5.4.7
py==1.6.0
pyasn1==0.4.4
pyasn1-modules==0.2.2
pycodestyle==2.4.0
pycosat==0.6.3
pycparser==2.18
pycrypto==2.6.1
pycurl==7.43.0.2
pyflakes==2.0.0
Pygments==2.2.0
pylint==2.1.1
pyodbc==4.0.24
pyOpenSSL==18.0.0
pyparsing==2.2.0
PySocks==1.6.8
pytest==3.8.0
pytest-arraydiff==0.2
pytest-astropy==0.4.0
pytest-doctestplus==0.1.3
pytest-openfiles==0.3.0
pytest-remotedata==0.3.0
python-dateutil==2.7.3
pytz==2018.5
PyWavelets==1.0.0
pywin32==223
pywinpty==0.5.4
PyYAML==3.13
pyzmq==17.1.2
QtAwesome==0.4.4
qtconsole==4.4.1
QtPy==1.5.0
requests==2.19.1
rope==0.11.0
ruamel-yaml==0.15.46
scikit-image==0.14.0
scikit-learn==0.19.2
scipy==1.1.0
seaborn==0.9.0
Send2Trash==1.5.0
service-identity==17.0.0
simplegeneric==0.8.1
singledispatch==3.4.0.3
six==1.11.0
snowballstemmer==1.2.1
sortedcollections==1.0.1
sortedcontainers==2.0.5
Sphinx==1.7.9
sphinxcontrib-websupport==1.1.0
spyder==3.3.1
spyder-kernels==0.2.6
SQLAlchemy==1.2.11
statsmodels==0.9.0
sympy==1.1.1
tables==3.4.4
tblib==1.3.2
terminado==0.8.1
testpath==0.3.1
toolz==0.9.0
tornado==5.1
tqdm==4.26.0
traitlets==4.3.2
Twisted==18.7.0
unicodecsv==0.14.1
urllib3==1.23
wcwidth==0.1.7
webencodings==0.5.1
Werkzeug==0.14.1
widgetsnbextension==3.4.1
win-inet-pton==1.0.1
win-unicode-console==0.5
wincertstore==0.2
wrapt==1.10.11
xlrd==1.1.0
XlsxWriter==1.1.0
xlwings==0.11.8
xlwt==1.3.0
zict==0.1.3
zope.interface==4.5.0

C:\Users\Administrator>

**Comment by heavengate** [comment]
pip3 list 里面没有paddle，paddle没有安上，重新安装试下

**Comment by Jhon714-cooler** [comment]
还是这样呢
