### ISSUE TITLE
layers.concat() 报错 AttributeError: 'NoneType' object has no attribute 'dtype'

### ISSUE THREAD

**Issue by dingsiyu** [PaddlePaddle/Paddle#18891]
- 版本、环境信息：
    1）PaddlePaddle版本：1.5
    2）CPU/GPU：CUDA 10和cuDNN 7.4
    3）系统环境：centos 6
    4）Python版本号 python3
    5）显存信息
- 复现信息：如为报错，请给出复现环境、复现步骤
- 问题描述：请详细描述您的问题，同步贴出报错信息、日志/代码关键片段

def boolean_mask_(tensor, mask, name="boolean_mask", axis=None):

    mask_int = layers.cast(mask, dtype='int32')
    shape_mask = layers.shape(mask_int)
    ndims_mask = shape_mask.shape[0]
    shape_tensor = layers.shape(tensor)
    if ndims_mask == 0:
      raise ValueError("mask cannot be scalar.")
    if ndims_mask is None:
      raise ValueError(
          "Number of mask dimensions must be specified, even if some dimensions"
          " are None.  E.g. shape=[None] is ok, but shape=None is not.")
    axis = 0 if axis is None else axis
    # shape_tensor[axis:axis + ndims_mask].assert_is_compatible_with(shape_mask)

    leading_size = shape_tensor[axis]
    for i in range(axis + 1, axis + ndims_mask):
        leading_size *= shape_tensor[i]

    if axis == 0:
        if axis + ndims_mask < shape_tensor.shape[0]:
            tensor = layers.reshape(
                tensor,
                layers.concat([[leading_size], layers.shape(tensor)[axis + ndims_mask:]], 0))
        else:
            tensor = layers.reshape(tensor, [leading_size])
    if axis > 0:
        if axis + ndims_mask < shape_tensor.shape[0]:
            tensor = layers.reshape(
                tensor,
                layers.concat([layers.shape(tensor)[:axis], [leading_size],
                               layers.shape(tensor)[axis + ndims_mask:]], 0))
        else:
            tensor = layers.reshape(
                tensor,
                layers.concat([layers.shape(tensor)[:axis], [leading_size]], 0))

    mask_int = layers.reshape(mask_int, [-1])
    return _apply_mask_1d(tensor, mask_int, axis)

a_ = np.array([[1,2,3],[4,5,6],[7,8,9]], dtype='float32')
b_ = layers.create_tensor(dtype='float32')    
layers.assign(a_, b_)
c1 = b_ >= 2.0
c2 = b_ <= 7.0
c_ = layers.logical_and(c1, c2)
    
a_2 = np.array([[[1,2,3],[4,5,6], [2,3,4]], [[2,3,4], [3,4,5], [4,5,6]],
                   [[2,4,5], [1,3,4], [4,2,1]]], dtype='float32')
b_2 = layers.create_tensor(dtype='float32')
layers.assign(a_2, b_2)

re = boolean_mask(b_2, c_)

**Comment by heavengate** [comment]
麻烦贴一下详细报错信息

**Comment by heavengate** [comment]
```
layers.concat([[leading_size], layers.shape(tensor)[axis + ndims_mask:]], 0))
```
concat里面`[leading_size]`是个list，`layers.shape(tensor)[axis + ndims_mask:]`是个variable，不能这么concat

**Comment by dingsiyu** [comment]
![image](https://user-images.githubusercontent.com/21340925/62100968-4ad12500-b2c6-11e9-83ea-0a91f6fb2c46.png)

**Comment by heavengate** [comment]
这个不是concat报的错，是reshape报的错，reshape传入的shape应该是python list/tuple，上面没有必要用fluid.layer.shape获取shape，直接tensor.shape获取一个python list型的shape组合就可以了

**Comment by dingsiyu** [comment]
Traceback (most recent call last):
  File "test.py", line 110, in <module>
    c_, res = test_bool()
  File "test.py", line 80, in test_bool
    re = boolean_mask(b_2, c_)
  File "test.py", line 50, in boolean_mask
    layers.concat([leading_size, tensor.shape[axis + ndims_mask:]], 0))
  File "/home/dingsiyu/bin/anaconda3/lib/python3.6/site-packages/paddle/fluid/layers/tensor.py", line 200, in concat
    out = helper.create_variable_for_type_inference(dtype=helper.input_dtype())
  File "/home/dingsiyu/bin/anaconda3/lib/python3.6/site-packages/paddle/fluid/layer_helper.py", line 96, in input_dtype
    elif dtype != each.dtype:
AttributeError: 'NoneType' object has no attribute 'dtype'

**Comment by heavengate** [comment]
用`tensor.shape`替换`layers.shape(tensor`得到一个python list类型的shape，然后用python list操作就可以，不需要用concat
