### ISSUE TITLE
Mask RCNN batch size大于1 infer问题

### ISSUE THREAD

**Issue by TheodoreG** [PaddlePaddle/Paddle#18899]
Hi，I use the code in https://github.com/PaddlePaddle/models/tree/develop/PaddleCV/rcnn
to do infer.
My code looks like that:
```
  place = fluid.CUDAPlace(0) if cfg.use_gpu else fluid.CPUPlace()
    exe = fluid.Executor(place)

    [inference_program, feed_target_names, fetch_targets] = \
        fluid.io.load_inference_model(
            dirname=cfg.pretrained_model,
            executor=exe,
            model_filename='model',
            params_filename='params'
        )

    infer_reader = reader.infer(cfg.image_path)
    new_infer_reader = reader.infer(cfg.image_path)
   
    dts_res = []
    segms_res = []


    data = next(infer_reader())
    new_data = next(new_infer_reader())

    im_info = [data[0][1]]


    feed_target_vars = [fluid.global_scope().find_var(item) for item in feed_target_names]
    feeder = fluid.DataFeeder(place=place, feed_list=feed_target_names, program=inference_program)

    feed_data = [data[0], new_data[0]]


    result = exe.run(inference_program,
                     feed=feeder.feed(feed_data),
                     fetch_list=fetch_targets,
                     return_numpy=False,
                     use_program_cache=False
                     )

```
But I got following error:
![image](https://user-images.githubusercontent.com/13977118/62105157-2b40f900-b2d4-11e9-90bf-0b55e7ec60b9.png)
It seems when processing `sequence_expand` function in https://github.com/PaddlePaddle/models/blob/develop/PaddleCV/rcnn/models/model_builder.py#L135  that cause such error.
How to fix it ?

**Comment by jerrywgz** [comment]
在rcnn这个目录下的reader现在只是支持单张图片的infer https://github.com/PaddlePaddle/models/blob/develop/PaddleCV/rcnn/reader.py#L181 这里每次只会返回一张图片，所以batch size大于1的话就会报维度不匹配

**Comment by jerrywgz** [comment]
如果batch size大于1，需要对reader做适配，返回一个batch的数据即可

**Comment by heavengate** [comment]
鉴于问题已解决，本issue关闭，如果还有问题请reopen此issue，感谢对PaddlePaddle的支持~
