### ISSUE TITLE
网络构建后和预测维度不一致

### ISSUE THREAD

**Issue by XipengY** [PaddlePaddle/Paddle#18898]
- 版本、环境信息：
    1）PaddlePaddle版本：1.5.0
    2）GPU：GPU：k40， cuda：9.0 cudnn：7.0
    4）系统环境：centos6.3，Python2.7

- 问题描述：
构建网络时，网络维度：
name: "relu_12.tmp_0"
type {
  type: LOD_TENSOR
  lod_tensor {
    tensor {
      data_type: FP32
      dims: -1
      dims: 256
      dims: 48
      dims: 90
    }
    lod_level: 0
  }
}
persistable: false

(Pdb) feat_hi
name: "relu_18.tmp_0"
type {
  type: LOD_TENSOR
  lod_tensor {
    tensor {
      data_type: FP32
      dims: -1
      dims: 256
      dims: 48
      dims: 90
    }
    lod_level: 0
  }
}
persistable: false

运行数据时，维度：
1564463238              The place is:CUDAPlace(0)
Tensor[relu_12.tmp_0]
        shape: [1,256,53,95,]
        dtype: f
        data: 0,0.243098,0.572884,0.76679,0.882325,0.766038,0.827271,0.927123,0.989151,0.815397,
1564463238              The place is:CUDAPlace(0)
Tensor[relu_18.tmp_0]
        shape: [1,256,57,99,]
        dtype: f
        data: 0.0551013,0.0547099,0.064019,0.218591,0.0867817,0.353785,0.459147,0.520205,0.503245,0.520177,

构建网络时，w和h分别时48，90，构建完网络，运行过程中，w和h分别是53、95和57、99，所以在调用fluid.layers.concats时报错了。
C++ Callstacks:
Enforce failed. Expected out_dims[j] == ins[i][j], but received out_dims[j]:53 != ins[i][j]:57.
Input tensors should have the same elements except the specify axis. at [/paddle/paddle/fluid/operators/concat_op.cc:71]

**Comment by heavengate** [comment]
运行时的维度和你feed数据的维度有关，应该是你feed数据维度不一致导致的

**Comment by XipengY** [comment]
(Pdb) batch_data[0][0].shape
(3, 768, 1440)
feed的数据维度好像没有问题

**Comment by XipengY** [comment]
构建网络虽然正常，但是并不能保证构建的是对的，因为不是每一步都检查了正确性。问题在构建网络中参数设置不对，多padding了一次
