### ISSUE TITLE
[MKL-DNN] Improve performance of hashing Key genration using TID

### ISSUE THREAD

**Issue by jczaja** [PaddlePaddle/Paddle#18902]
As disscussed in #18758 Key generation using TID is quite slow and cost upto ~5 FPS on mobilenet v1 model. This issue is to try to speed it up : 
- Limit TID usage if possible
- cache , std::hasher or std::stringstream if possible

**Comment by Sand3r-** [comment]
Since #18758 and other PRs introducing changes to hashing have been introduced, can this issue be closed now?

**Comment by jczaja** [comment]
Yes, once we decreased hashing key and introduced std hasher no further ideas are pending to be verified.
