### ISSUE TITLE
如何获取Variable类型(非ParamAttr类型)参数的值？

### ISSUE THREAD

**Issue by nlp4whp** [PaddlePaddle/Paddle#18909]
我从其他issue中看到了这种方法 (https://github.com/PaddlePaddle/Paddle/issues/10018)
```fluid.global_scope().find_var(var.name).get_tensor()```

但似乎只对ParamAttr类型的变量有效, Variable类型的参数的name是找不到的(返回None)

那比如我创建一个词向量矩阵, 有没有办法可以直接返回它的值呢？
```
word_embedding = fluid.layers.embedding(
        name='word_embedding',
        input=word_ids,
        size=[vocab_len, embedding_dim],
        param_attr=fluid.ParamAttr(
            learning_rate=30,
            initializer=fluid.initializer.Uniform(low=-0.1, high=0.1))
    )
```
非常感谢

**Comment by heavengate** [comment]
Variable都有name的，你可以直接print(word_embedding),可以看到name

**Comment by heavengate** [comment]
或者你直接使用fluid.layers.Print(word_embedding), exe.run之后这个值也会打印出来

**Comment by nlp4whp** [comment]
> 或者你直接使用fluid.layers.Print(word_embedding), exe.run之后这个值也会打印出来

感谢

Variable是有名字的，只是fluid.global_scope().find_var(word_embedding.name)会返回None，所以我猜是scope里找不到变量的name

另外exe.run(fluid.default_startup_program())之后也没有任何显示结果 = = 您了解这种情况么

**Comment by heavengate** [comment]
> > 或者你直接使用fluid.layers.Print(word_embedding), exe.run之后这个值也会打印出来
> 
> 感谢
> 
> Variable是有名字的，只是fluid.global_scope().find_var(word_embedding.name)会返回None，所以我猜是scope里找不到变量的name
> 
> 另外exe.run(fluid.default_startup_program())之后也没有任何显示结果 = = 您了解这种情况么

不是exe.run(fluid.default_startup_program()), 而是实际feed数据的那个exe.run,只有网络跑起来之后才会有数据

**Comment by nlp4whp** [comment]
> > > 或者你直接使用fluid.layers.Print(word_embedding), exe.run之后这个值也会打印出来
> > 
> > 
> > 感谢
> > Variable是有名字的，只是fluid.global_scope().find_var(word_embedding.name)会返回None，所以我猜是scope里找不到变量的name
> > 另外exe.run(fluid.default_startup_program())之后也没有任何显示结果 = = 您了解这种情况么
> 
> 不是exe.run(fluid.default_startup_program()), 而是实际feed数据的那个exe.run,只有网络跑起来之后才会有数据

多谢我试试看

**Comment by heavengate** [comment]
鉴于问题已解决，本issue关闭，如果还有问题请reopen此issue，感谢对PaddlePaddle的支持~
