### ISSUE TITLE
paddle.dataset.common.download函数末尾有一条sys.stderr.write("\n")，导致训练时打印出一堆回车

### ISSUE THREAD

**Issue by sands321** [PaddlePaddle/Paddle#18907]
- 版本、环境信息
1）PaddlePaddle版本: 1.5.1
2）CPU/GPU：CPU
3）系统环境：Mac OS 10.14

- 建议描述：paddle.dataset.common.download函数末尾有一条sys.stderr.write("\n")，导致
训练时，日志中莫名其妙输出一堆回车。比如paddle.dataset.uci_housing.train()等执行时日志中就会出现回车。

**Comment by heavengate** [comment]
paddle.dataset.common.download  只会在下载数据集的时候会调用到，只会调用到一次，而且这个sys.stderr.write("\n")只用于结束下载的进度条显示，应该不会输出回车的
