### ISSUE TITLE
安装paddle报错

### ISSUE THREAD

**Issue by christianahui** [PaddlePaddle/Paddle#18901]
安装时命令为：pip install paddlepaddle-gpu==1.5.0.post97
Python 2.7.14
GPU：00:0d.0 3D controller: NVIDIA Corporation Device 1b38 (rev a1)
cuda：CUDA Version 9.0.176
cudnn：7003
`Looking in indexes: http://pip.baidu.com/pypi/simple
Collecting paddlepaddle-gpu==1.5.0.post97
  Downloading http://pypi.baidu.com/packages/40/37/81e897f785a22b67a5a2aa448a8aaf106b201e85fe605ed29f8870f78a39/paddlepaddle_gpu-1.5.0.post97-cp27-cp27mu-manylinux1_x86_64.whl
     \ 241.4MB 61.2MB/s
Requirement already satisfied: py-cpuinfo==5.0.0 in ./opt/python-2.7/lib/python2.7/site-packages (from paddlepaddle-gpu==1.5.0.post97) (5.0.0)
Requirement already satisfied: decorator in ./opt/python-2.7/lib/python2.7/site-packages (from paddlepaddle-gpu==1.5.0.post97) (4.4.0)
Requirement already satisfied: graphviz in ./opt/python-2.7/lib/python2.7/site-packages (from paddlepaddle-gpu==1.5.0.post97) (0.9)
Requirement already satisfied: requests>=2.20.0 in ./opt/python-2.7/lib/python2.7/site-packages (from paddlepaddle-gpu==1.5.0.post97) (2.22.0)
Requirement already satisfied: prettytable in ./opt/python-2.7/lib/python2.7/site-packages (from paddlepaddle-gpu==1.5.0.post97) (0.7.2)
Requirement already satisfied: matplotlib<=2.2.4; python_version < "3.6" in ./opt/python-2.7/lib/python2.7/site-packages (from paddlepaddle-gpu==1.5.0.post97) (2.2.3)
Requirement already satisfied: scipy<=1.2.1,>=0.19.0; python_version < "3.5" in ./opt/python-2.7/lib/python2.7/site-packages (from paddlepaddle-gpu==1.5.0.post97) (1.1.0)
Requirement already satisfied: opencv-python in ./opt/python-2.7/lib/python2.7/site-packages (from paddlepaddle-gpu==1.5.0.post97) (4.1.0.25)
Requirement already satisfied: numpy>=1.12 in ./opt/python-2.7/lib/python2.7/site-packages (from paddlepaddle-gpu==1.5.0.post97) (1.15.1)
Collecting Pillow (from paddlepaddle-gpu==1.5.0.post97)
  Downloading http://pypi.baidu.com/packages/f7/d6/00368fe7f9acb9454ba5a75a1edda97b7ee9cfe399af4acb6489466be37e/Pillow-5.4.0.tar.gz
     / 15.9MB 62.7MB/s
Requirement already satisfied: protobuf>=3.1.0 in ./opt/python-2.7/lib/python2.7/site-packages (from paddlepaddle-gpu==1.5.0.post97) (3.5.0.post1)
Requirement already satisfied: pyyaml in ./opt/python-2.7/lib/python2.7/site-packages (from paddlepaddle-gpu==1.5.0.post97) (3.13)
Requirement already satisfied: funcsigs in ./opt/python-2.7/lib/python2.7/site-packages (from paddlepaddle-gpu==1.5.0.post97) (1.0.2)
Collecting rarfile (from paddlepaddle-gpu==1.5.0.post97)
Collecting recordio>=0.1.0 (from paddlepaddle-gpu==1.5.0.post97)
  Downloading http://pypi.baidu.com/packages/01/29/ee510d487bb2665e53b0171a6473531a3df86341ade7ab68d879cc6a2ac4/recordio-0.1.5-cp27-cp27mu-manylinux1_x86_64.whl
     / 901kB 115.7MB/s
Requirement already satisfied: nltk<=3.4,>=3.2.2; python_version < "3.5" in ./opt/python-2.7/lib/python2.7/site-packages (from paddlepaddle-gpu==1.5.0.post97) (3.3)
Requirement already satisfied: six in ./opt/python-2.7/lib/python2.7/site-packages (from paddlepaddle-gpu==1.5.0.post97) (1.11.0)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in ./opt/python-2.7/lib/python2.7/site-packages (from requests>=2.20.0->paddlepaddle-gpu==1.5.0.post97) (3.0.4)
Requirement already satisfied: idna<2.9,>=2.5 in ./opt/python-2.7/lib/python2.7/site-packages (from requests>=2.20.0->paddlepaddle-gpu==1.5.0.post97) (2.7)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in ./opt/python-2.7/lib/python2.7/site-packages (from requests>=2.20.0->paddlepaddle-gpu==1.5.0.post97) (1.23)
Requirement already satisfied: certifi>=2017.4.17 in ./opt/python-2.7/lib/python2.7/site-packages (from requests>=2.20.0->paddlepaddle-gpu==1.5.0.post97) (2018.8.24)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 in ./opt/python-2.7/lib/python2.7/site-packages (from matplotlib<=2.2.4; python_version < "3.6"->paddlepaddle-gpu==1.5.0.post97) (2.2.0)
Requirement already satisfied: backports.functools-lru-cache in ./opt/python-2.7/lib/python2.7/site-packages (from matplotlib<=2.2.4; python_version < "3.6"->paddlepaddle-gpu==1.5.0.post97) (1.5)
Requirement already satisfied: subprocess32 in ./opt/python-2.7/lib/python2.7/site-packages (from matplotlib<=2.2.4; python_version < "3.6"->paddlepaddle-gpu==1.5.0.post97) (3.5.2)
Requirement already satisfied: python-dateutil>=2.1 in ./opt/python-2.7/lib/python2.7/site-packages (from matplotlib<=2.2.4; python_version < "3.6"->paddlepaddle-gpu==1.5.0.post97) (2.7.3)
Requirement already satisfied: pytz in ./opt/python-2.7/lib/python2.7/site-packages (from matplotlib<=2.2.4; python_version < "3.6"->paddlepaddle-gpu==1.5.0.post97) (2018.5)
Requirement already satisfied: kiwisolver>=1.0.1 in ./opt/python-2.7/lib/python2.7/site-packages (from matplotlib<=2.2.4; python_version < "3.6"->paddlepaddle-gpu==1.5.0.post97) (1.0.1)
Requirement already satisfied: cycler>=0.10 in ./opt/python-2.7/lib/python2.7/site-packages (from matplotlib<=2.2.4; python_version < "3.6"->paddlepaddle-gpu==1.5.0.post97) (0.10.0)
Requirement already satisfied: setuptools in ./opt/python-2.7/lib/python2.7/site-packages/setuptools-40.6.3-py2.7.egg (from protobuf>=3.1.0->paddlepaddle-gpu==1.5.0.post97) (40.6.3)
Building wheels for collected packages: Pillow
  Running setup.py bdist_wheel for Pillow ... error
  Complete output from command /home/xingzhihui/opt/python-2.7/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-IwmIME/Pillow/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/pip-wheel-vFb4Ok --python-tag cp27:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-2.7
  creating build/lib.linux-x86_64-2.7/PIL
  copying src/PIL/WmfImagePlugin.py -> build/lib.linux-x86_64-2.7/PIL
  copying src/PIL/ImageMorph.py -> build/lib.linux-x86_64-2.7/PIL
  copying src/PIL/TiffTags.py -> build/lib.linux-x86_64-2.7/PIL
  copying src/PIL/PSDraw.py -> build/lib.linux-x86_64-2.7/PIL
  copying src/PIL/TarIO.py -> build/lib.linux-x86_64-2.7/PIL
  copying src/PIL/WebPImagePlugin.py -> build/lib.linux-x86_64-2.7/PIL
  copying src/PIL/ImImagePlugin.py -> build/lib.linux-x86_64-2.7/PIL
  copying src/PIL/OleFileIO.py -> build/lib.linux-x86_64-2.7/PIL
  copying src/PIL/GimpPaletteFile.py -> build/lib.linux-x86_64-2.7/PIL
  copying src/PIL/ImageGrab.py -> build/lib.linux-x86_64-2.7/PIL
  copying src/PIL/ImageStat.py -> build/lib.linux-x86_64-2.7/PIL
  copying src/PIL/_tkinter_finder.py -> build/lib.linux-x86_64-2.7/PIL
  copying src/PIL/McIdasImagePlugin.py -> build/lib.linux-x86_64-2.7/PIL
  copying src/PIL/PsdImagePlugin.py -> build/lib.linux-x86_64-2.7/PIL
  copying src/PIL/GifImagePlugin.py -> build/lib.linux-x86_64-2.7/PIL
  copying src/PIL/ImageChops.py -> build/lib.linux-x86_64-2.7/PIL
  copying src/PIL/GdImageFile.py -> build/lib.linux-x86_64-2.7/PIL
  copying src/PIL/PcxImagePlugin.py -> build/lib.linux-x86_64-2.7/PIL
  copying src/PIL/FitsStubImagePlugin.py -> build/lib.linux-x86_64-2.7/PIL
  copying src/PIL/_binary.py -> build/lib.linux-x86_64-2.7/PIL
  copying src/PIL/BufrStubImagePlugin.py -> build/lib.linux-x86_64-2.7/PIL
  copying src/PIL/BdfFontFile.py -> build/lib.linux-x86_64-2.7/PIL
  copying src/PIL/FtexImagePlugin.py -> build/lib.linux-x86_64-2.7/PIL
  copying src/PIL/CurImagePlugin.py -> build/lib.linux-x86_64-2.7/PIL
  copying src/PIL/ImageDraw2.py -> build/lib.linux-x86_64-2.7/PIL
  copying src/PIL/_util.py -> build/lib.linux-x86_64-2.7/PIL
  copying src/PIL/ExifTags.py -> build/lib.linux-x86_64-2.7/PIL
  copying src/PIL/ImageMode.py -> build/lib.linux-x86_64-2.7/PIL
  copying src/PIL/FliImagePlugin.py -> build/lib.linux-x86_64-2.7/PIL
  copying src/PIL/ImageFont.py -> build/lib.linux-x86_64-2.7/PIL
  copying src/PIL/EpsImagePlugin.py -> build/lib.linux-x86_64-2.7/PIL
  copying src/PIL/Image.py -> build/lib.linux-x86_64-2.7/PIL
  copying src/PIL/MpegImagePlugin.py -> build/lib.linux-x86_64-2.7/PIL
  copying src/PIL/ImagePalette.py -> build/lib.linux-x86_64-2.7/PIL
  copying src/PIL/SgiImagePlugin.py -> build/lib.linux-x86_64-2.7/PIL
  copying src/PIL/ImageTk.py -> build/lib.linux-x86_64-2.7/PIL
  copying src/PIL/PaletteFile.py -> build/lib.linux-x86_64-2.7/PIL
  copying src/PIL/Hdf5StubImagePlugin.py -> build/lib.linux-x86_64-2.7/PIL
  copying src/PIL/ImageQt.py -> build/lib.linux-x86_64-2.7/PIL
  copying src/PIL/IptcImagePlugin.py -> build/lib.linux-x86_64-2.7/PIL
  copying src/PIL/PdfImagePlugin.py -> build/lib.linux-x86_64-2.7/PIL
  copying src/PIL/GbrImagePlugin.py -> build/lib.linux-x86_64-2.7/PIL
  copying src/PIL/FpxImagePlugin.py -> build/lib.linux-x86_64-2.7/PIL
  copying src/PIL/IcnsImagePlugin.py -> build/lib.linux-x86_64-2.7/PIL
  copying src/PIL/__init__.py -> build/lib.linux-x86_64-2.7/PIL
  copying src/PIL/PyAccess.py -> build/lib.linux-x86_64-2.7/PIL
  copying src/PIL/BmpImagePlugin.py -> build/lib.linux-x86_64-2.7/PIL
  copying src/PIL/MpoImagePlugin.py -> build/lib.linux-x86_64-2.7/PIL
  copying src/PIL/TgaImagePlugin.py -> build/lib.linux-x86_64-2.7/PIL
  copying src/PIL/XpmImagePlugin.py -> build/lib.linux-x86_64-2.7/PIL
  copying src/PIL/PcdImagePlugin.py -> build/lib.linux-x86_64-2.7/PIL
  copying src/PIL/ImageOps.py -> build/lib.linux-x86_64-2.7/PIL
  copying src/PIL/GimpGradientFile.py -> build/lib.linux-x86_64-2.7/PIL
  copying src/PIL/ImageCms.py -> build/lib.linux-x86_64-2.7/PIL
  copying src/PIL/SunImagePlugin.py -> build/lib.linux-x86_64-2.7/PIL
  copying src/PIL/IcoImagePlugin.py -> build/lib.linux-x86_64-2.7/PIL
  copying src/PIL/features.py -> build/lib.linux-x86_64-2.7/PIL
  copying src/PIL/FontFile.py -> build/lib.linux-x86_64-2.7/PIL
  copying src/PIL/PalmImagePlugin.py -> build/lib.linux-x86_64-2.7/PIL
  copying src/PIL/ImageShow.py -> build/lib.linux-x86_64-2.7/PIL
  copying src/PIL/ImageEnhance.py -> build/lib.linux-x86_64-2.7/PIL
  copying src/PIL/MspImagePlugin.py -> build/lib.linux-x86_64-2.7/PIL
  copying src/PIL/ContainerIO.py -> build/lib.linux-x86_64-2.7/PIL
  copying src/PIL/XbmImagePlugin.py -> build/lib.linux-x86_64-2.7/PIL
  copying src/PIL/ImtImagePlugin.py -> build/lib.linux-x86_64-2.7/PIL
  copying src/PIL/SpiderImagePlugin.py -> build/lib.linux-x86_64-2.7/PIL
  copying src/PIL/Jpeg2KImagePlugin.py -> build/lib.linux-x86_64-2.7/PIL
  copying src/PIL/DcxImagePlugin.py -> build/lib.linux-x86_64-2.7/PIL
  copying src/PIL/PngImagePlugin.py -> build/lib.linux-x86_64-2.7/PIL
  copying src/PIL/PdfParser.py -> build/lib.linux-x86_64-2.7/PIL
  copying src/PIL/ImageTransform.py -> build/lib.linux-x86_64-2.7/PIL
  copying src/PIL/PpmImagePlugin.py -> build/lib.linux-x86_64-2.7/PIL
  copying src/PIL/JpegImagePlugin.py -> build/lib.linux-x86_64-2.7/PIL
  copying src/PIL/XVThumbImagePlugin.py -> build/lib.linux-x86_64-2.7/PIL
  copying src/PIL/ImageMath.py -> build/lib.linux-x86_64-2.7/PIL
  copying src/PIL/TiffImagePlugin.py -> build/lib.linux-x86_64-2.7/PIL
  copying src/PIL/DdsImagePlugin.py -> build/lib.linux-x86_64-2.7/PIL
  copying src/PIL/ImageFilter.py -> build/lib.linux-x86_64-2.7/PIL
  copying src/PIL/JpegPresets.py -> build/lib.linux-x86_64-2.7/PIL
  copying src/PIL/_version.py -> build/lib.linux-x86_64-2.7/PIL
  copying src/PIL/ImagePath.py -> build/lib.linux-x86_64-2.7/PIL
  copying src/PIL/ImageDraw.py -> build/lib.linux-x86_64-2.7/PIL
  copying src/PIL/MicImagePlugin.py -> build/lib.linux-x86_64-2.7/PIL
  copying src/PIL/ImageFile.py -> build/lib.linux-x86_64-2.7/PIL
  copying src/PIL/BlpImagePlugin.py -> build/lib.linux-x86_64-2.7/PIL
  copying src/PIL/PcfFontFile.py -> build/lib.linux-x86_64-2.7/PIL
  copying src/PIL/GribStubImagePlugin.py -> build/lib.linux-x86_64-2.7/PIL
  copying src/PIL/ImageWin.py -> build/lib.linux-x86_64-2.7/PIL
  copying src/PIL/WalImageFile.py -> build/lib.linux-x86_64-2.7/PIL
  copying src/PIL/PixarImagePlugin.py -> build/lib.linux-x86_64-2.7/PIL
  copying src/PIL/ImageColor.py -> build/lib.linux-x86_64-2.7/PIL
  copying src/PIL/ImageSequence.py -> build/lib.linux-x86_64-2.7/PIL
  running egg_info
  writing src/Pillow.egg-info/PKG-INFO
  writing top-level names to src/Pillow.egg-info/top_level.txt
  writing dependency_links to src/Pillow.egg-info/dependency_links.txt
  reading manifest file 'src/Pillow.egg-info/SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  warning: no files found matching '*.c'
  warning: no files found matching '*.h'
  warning: no files found matching '*.sh'
  no previously-included directories found matching 'docs/_static'
  warning: no previously-included files found matching '.appveyor.yml'
  warning: no previously-included files found matching '.coveragerc'
  warning: no previously-included files found matching '.codecov.yml'
  warning: no previously-included files found matching '.editorconfig'
  warning: no previously-included files found matching '.landscape.yaml'
  warning: no previously-included files found matching '.readthedocs.yml'
  warning: no previously-included files found matching '.travis'
  warning: no previously-included files found matching '.travis/*'
  warning: no previously-included files found matching 'tox.ini'
  warning: no previously-included files matching '.git*' found anywhere in distribution
  warning: no previously-included files matching '*.pyc' found anywhere in distribution
  warning: no previously-included files matching '*.so' found anywhere in distribution
  writing manifest file 'src/Pillow.egg-info/SOURCES.txt'
  running build_ext
  
  
  The headers or library files could not be found for jpeg,
  a required dependency when compiling Pillow from source.
  
  Please see the install instructions at:
     https://pillow.readthedocs.io/en/latest/installation.html
  
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-install-IwmIME/Pillow/setup.py", line 812, in <module>
      raise RequiredDependencyException(msg)
  __main__.RequiredDependencyException:
  
  The headers or library files could not be found for jpeg,
  a required dependency when compiling Pillow from source.
  
  Please see the install instructions at:
     https://pillow.readthedocs.io/en/latest/installation.html
  
  
  
  ----------------------------------------
  Failed building wheel for Pillow
  Running setup.py clean for Pillow
Failed to build Pillow
Installing collected packages: Pillow, rarfile, recordio, paddlepaddle-gpu
  Running setup.py install for Pillow ... error
    Complete output from command /home/xingzhihui/opt/python-2.7/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-IwmIME/Pillow/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-zBZ1pu/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-2.7
    creating build/lib.linux-x86_64-2.7/PIL
    copying src/PIL/WmfImagePlugin.py -> build/lib.linux-x86_64-2.7/PIL
    copying src/PIL/ImageMorph.py -> build/lib.linux-x86_64-2.7/PIL
    copying src/PIL/TiffTags.py -> build/lib.linux-x86_64-2.7/PIL
    copying src/PIL/PSDraw.py -> build/lib.linux-x86_64-2.7/PIL
    copying src/PIL/TarIO.py -> build/lib.linux-x86_64-2.7/PIL
    copying src/PIL/WebPImagePlugin.py -> build/lib.linux-x86_64-2.7/PIL
    copying src/PIL/ImImagePlugin.py -> build/lib.linux-x86_64-2.7/PIL
    copying src/PIL/OleFileIO.py -> build/lib.linux-x86_64-2.7/PIL
    copying src/PIL/GimpPaletteFile.py -> build/lib.linux-x86_64-2.7/PIL
    copying src/PIL/ImageGrab.py -> build/lib.linux-x86_64-2.7/PIL
    copying src/PIL/ImageStat.py -> build/lib.linux-x86_64-2.7/PIL
    copying src/PIL/_tkinter_finder.py -> build/lib.linux-x86_64-2.7/PIL
    copying src/PIL/McIdasImagePlugin.py -> build/lib.linux-x86_64-2.7/PIL
    copying src/PIL/PsdImagePlugin.py -> build/lib.linux-x86_64-2.7/PIL
    copying src/PIL/GifImagePlugin.py -> build/lib.linux-x86_64-2.7/PIL
    copying src/PIL/ImageChops.py -> build/lib.linux-x86_64-2.7/PIL
    copying src/PIL/GdImageFile.py -> build/lib.linux-x86_64-2.7/PIL
    copying src/PIL/PcxImagePlugin.py -> build/lib.linux-x86_64-2.7/PIL
    copying src/PIL/FitsStubImagePlugin.py -> build/lib.linux-x86_64-2.7/PIL
    copying src/PIL/_binary.py -> build/lib.linux-x86_64-2.7/PIL
    copying src/PIL/BufrStubImagePlugin.py -> build/lib.linux-x86_64-2.7/PIL
    copying src/PIL/BdfFontFile.py -> build/lib.linux-x86_64-2.7/PIL
    copying src/PIL/FtexImagePlugin.py -> build/lib.linux-x86_64-2.7/PIL
    copying src/PIL/CurImagePlugin.py -> build/lib.linux-x86_64-2.7/PIL
    copying src/PIL/ImageDraw2.py -> build/lib.linux-x86_64-2.7/PIL
    copying src/PIL/_util.py -> build/lib.linux-x86_64-2.7/PIL
    copying src/PIL/ExifTags.py -> build/lib.linux-x86_64-2.7/PIL
    copying src/PIL/ImageMode.py -> build/lib.linux-x86_64-2.7/PIL
    copying src/PIL/FliImagePlugin.py -> build/lib.linux-x86_64-2.7/PIL
    copying src/PIL/ImageFont.py -> build/lib.linux-x86_64-2.7/PIL
    copying src/PIL/EpsImagePlugin.py -> build/lib.linux-x86_64-2.7/PIL
    copying src/PIL/Image.py -> build/lib.linux-x86_64-2.7/PIL
    copying src/PIL/MpegImagePlugin.py -> build/lib.linux-x86_64-2.7/PIL
    copying src/PIL/ImagePalette.py -> build/lib.linux-x86_64-2.7/PIL
    copying src/PIL/SgiImagePlugin.py -> build/lib.linux-x86_64-2.7/PIL
    copying src/PIL/ImageTk.py -> build/lib.linux-x86_64-2.7/PIL
    copying src/PIL/PaletteFile.py -> build/lib.linux-x86_64-2.7/PIL
    copying src/PIL/Hdf5StubImagePlugin.py -> build/lib.linux-x86_64-2.7/PIL
    copying src/PIL/ImageQt.py -> build/lib.linux-x86_64-2.7/PIL
    copying src/PIL/IptcImagePlugin.py -> build/lib.linux-x86_64-2.7/PIL
    copying src/PIL/PdfImagePlugin.py -> build/lib.linux-x86_64-2.7/PIL
    copying src/PIL/GbrImagePlugin.py -> build/lib.linux-x86_64-2.7/PIL
    copying src/PIL/FpxImagePlugin.py -> build/lib.linux-x86_64-2.7/PIL
    copying src/PIL/IcnsImagePlugin.py -> build/lib.linux-x86_64-2.7/PIL
    copying src/PIL/__init__.py -> build/lib.linux-x86_64-2.7/PIL
    copying src/PIL/PyAccess.py -> build/lib.linux-x86_64-2.7/PIL
    copying src/PIL/BmpImagePlugin.py -> build/lib.linux-x86_64-2.7/PIL
    copying src/PIL/MpoImagePlugin.py -> build/lib.linux-x86_64-2.7/PIL
    copying src/PIL/TgaImagePlugin.py -> build/lib.linux-x86_64-2.7/PIL
    copying src/PIL/XpmImagePlugin.py -> build/lib.linux-x86_64-2.7/PIL
    copying src/PIL/PcdImagePlugin.py -> build/lib.linux-x86_64-2.7/PIL
    copying src/PIL/ImageOps.py -> build/lib.linux-x86_64-2.7/PIL
    copying src/PIL/GimpGradientFile.py -> build/lib.linux-x86_64-2.7/PIL
    copying src/PIL/ImageCms.py -> build/lib.linux-x86_64-2.7/PIL
    copying src/PIL/SunImagePlugin.py -> build/lib.linux-x86_64-2.7/PIL
    copying src/PIL/IcoImagePlugin.py -> build/lib.linux-x86_64-2.7/PIL
    copying src/PIL/features.py -> build/lib.linux-x86_64-2.7/PIL
    copying src/PIL/FontFile.py -> build/lib.linux-x86_64-2.7/PIL
    copying src/PIL/PalmImagePlugin.py -> build/lib.linux-x86_64-2.7/PIL
    copying src/PIL/ImageShow.py -> build/lib.linux-x86_64-2.7/PIL
    copying src/PIL/ImageEnhance.py -> build/lib.linux-x86_64-2.7/PIL
    copying src/PIL/MspImagePlugin.py -> build/lib.linux-x86_64-2.7/PIL
    copying src/PIL/ContainerIO.py -> build/lib.linux-x86_64-2.7/PIL
    copying src/PIL/XbmImagePlugin.py -> build/lib.linux-x86_64-2.7/PIL
    copying src/PIL/ImtImagePlugin.py -> build/lib.linux-x86_64-2.7/PIL
    copying src/PIL/SpiderImagePlugin.py -> build/lib.linux-x86_64-2.7/PIL
    copying src/PIL/Jpeg2KImagePlugin.py -> build/lib.linux-x86_64-2.7/PIL
    copying src/PIL/DcxImagePlugin.py -> build/lib.linux-x86_64-2.7/PIL
    copying src/PIL/PngImagePlugin.py -> build/lib.linux-x86_64-2.7/PIL
    copying src/PIL/PdfParser.py -> build/lib.linux-x86_64-2.7/PIL
    copying src/PIL/ImageTransform.py -> build/lib.linux-x86_64-2.7/PIL
    copying src/PIL/PpmImagePlugin.py -> build/lib.linux-x86_64-2.7/PIL
    copying src/PIL/JpegImagePlugin.py -> build/lib.linux-x86_64-2.7/PIL
    copying src/PIL/XVThumbImagePlugin.py -> build/lib.linux-x86_64-2.7/PIL
    copying src/PIL/ImageMath.py -> build/lib.linux-x86_64-2.7/PIL
    copying src/PIL/TiffImagePlugin.py -> build/lib.linux-x86_64-2.7/PIL
    copying src/PIL/DdsImagePlugin.py -> build/lib.linux-x86_64-2.7/PIL
    copying src/PIL/ImageFilter.py -> build/lib.linux-x86_64-2.7/PIL
    copying src/PIL/JpegPresets.py -> build/lib.linux-x86_64-2.7/PIL
    copying src/PIL/_version.py -> build/lib.linux-x86_64-2.7/PIL
    copying src/PIL/ImagePath.py -> build/lib.linux-x86_64-2.7/PIL
    copying src/PIL/ImageDraw.py -> build/lib.linux-x86_64-2.7/PIL
    copying src/PIL/MicImagePlugin.py -> build/lib.linux-x86_64-2.7/PIL
    copying src/PIL/ImageFile.py -> build/lib.linux-x86_64-2.7/PIL
    copying src/PIL/BlpImagePlugin.py -> build/lib.linux-x86_64-2.7/PIL
    copying src/PIL/PcfFontFile.py -> build/lib.linux-x86_64-2.7/PIL
    copying src/PIL/GribStubImagePlugin.py -> build/lib.linux-x86_64-2.7/PIL
    copying src/PIL/ImageWin.py -> build/lib.linux-x86_64-2.7/PIL
    copying src/PIL/WalImageFile.py -> build/lib.linux-x86_64-2.7/PIL
    copying src/PIL/PixarImagePlugin.py -> build/lib.linux-x86_64-2.7/PIL
    copying src/PIL/ImageColor.py -> build/lib.linux-x86_64-2.7/PIL
    copying src/PIL/ImageSequence.py -> build/lib.linux-x86_64-2.7/PIL
    running egg_info
    writing src/Pillow.egg-info/PKG-INFO
    writing top-level names to src/Pillow.egg-info/top_level.txt
    writing dependency_links to src/Pillow.egg-info/dependency_links.txt
    reading manifest file 'src/Pillow.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    warning: no files found matching '*.c'
    warning: no files found matching '*.h'
    warning: no files found matching '*.sh'
    no previously-included directories found matching 'docs/_static'
    warning: no previously-included files found matching '.appveyor.yml'
    warning: no previously-included files found matching '.coveragerc'
    warning: no previously-included files found matching '.codecov.yml'
    warning: no previously-included files found matching '.editorconfig'
    warning: no previously-included files found matching '.landscape.yaml'
    warning: no previously-included files found matching '.readthedocs.yml'
    warning: no previously-included files found matching '.travis'
    warning: no previously-included files found matching '.travis/*'
    warning: no previously-included files found matching 'tox.ini'
    warning: no previously-included files matching '.git*' found anywhere in distribution
    warning: no previously-included files matching '*.pyc' found anywhere in distribution
    warning: no previously-included files matching '*.so' found anywhere in distribution
    writing manifest file 'src/Pillow.egg-info/SOURCES.txt'
    running build_ext
    
    
    The headers or library files could not be found for jpeg,
    a required dependency when compiling Pillow from source.
    
    Please see the install instructions at:
       https://pillow.readthedocs.io/en/latest/installation.html
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-IwmIME/Pillow/setup.py", line 812, in <module>
        raise RequiredDependencyException(msg)
    __main__.RequiredDependencyException:
    
    The headers or library files could not be found for jpeg,
    a required dependency when compiling Pillow from source.
    
    Please see the install instructions at:
       https://pillow.readthedocs.io/en/latest/installation.html
    
    
    
    ----------------------------------------
Command "/home/xingzhihui/opt/python-2.7/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-IwmIME/Pillow/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-zBZ1pu/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-install-IwmIME/Pillow/`

**Comment by heavengate** [comment]
看报错是jpeg相关的lib没有正确安装，pillow安装不上，可以试下
```
sudo apt-get install libjpeg-dev zlib1g-dev
pip install Pillow
```
参考 https://stackoverflow.com/questions/44043906/the-headers-or-library-files-could-not-be-found-for-jpeg-installing-pillow-on
