### ISSUE TITLE
请问，训练方式如下：单机多卡，每个卡都是独立的数据，如何为每份数据指定对应的GPU呢

### ISSUE THREAD

**Issue by dingsiyu** [PaddlePaddle/Paddle#18918]
- 版本、环境信息：
    1）PaddlePaddle版本：1.5
    2）CPU：
    3）GPU：P40, CUDA:10.0 CUDDN:7.4
    4）系统环境：centos6, python 3.6

**Comment by chengduoZH** [comment]
@dingsiyu 你是怎么输入数据的，feed还是py_reader
如果是feed，在执行的时候，会将数据进行split，比如batch_size=32，用4卡训练，每个张卡训练数据的batch_size为8.
如果是py_reader（异步数据读取），在Python端会通过一个线程从用户提供的数据Reader中读取数据，并将数据放到一个queue中，C++端，每个GPU异步的从queue中取出数据，所以从reader中读取数据在哪个GPU上计算是不确定。

**Comment by dingsiyu** [comment]
py_reader ，读取一个batch的数据后，按照单机的卡数，将数据再进行切分，每份数据再单独的GPU上运行，每个GPU上布置的网络是一样的

**Comment by dingsiyu** [comment]
py_reader, 每读取一个batch的数据后，将数据按照单机卡数再次切分，每份数据在单独的GPU上训练，每个GPU上部署的网络相同

**Comment by dingsiyu** [comment]
我这边网络训练有个特殊要求：
比如读取了第一个batch的数据，并切分成了4份，编号分别为1，2，3，4。4个GPU的编号分别为a,b,c,d。对应关系为1-a, 2-b, 3-c, 4-d。当读取了第二个batch后，同样切割成4份，与GPU的对应关系不能变

**Comment by dingsiyu** [comment]
所以这种情况只能用feed吗

**Comment by chengduoZH** [comment]
目前是的

**Comment by dingsiyu** [comment]
那github上公开的模型中有示例代码吗

**Comment by dingsiyu** [comment]
import numpy.random as random
import paddle
import paddle.fluid as fluid

def reader(limit=5):
    for i in range(limit):
        yield (random.random([784]).astype('float32'), random.random([1]).astype('int64')),

place=fluid.CUDAPlace(0)
data = fluid.layers.data(name='data', shape=[1, 28, 28], dtype='float32')
label = fluid.layers.data(name='label', shape=[1], dtype='int64')

feeder = fluid.DataFeeder(place=place, feed_list=[data, label])
reader = feeder.decorate_reader(reader, multi_devices=False)

exe = fluid.Executor(place)
exe.run(fluid.default_startup_program())
for data in reader():
    exe.run(feed=data)


这是用户手册上的示例，但这个例子举的并不恰当，decorate_reader是针对多卡的函数，但却以单卡来举例，用户并没有办法真正了解该op的正确使用方法。

比如：
对于DataFeeder的实例化中，feeder = fluid.DataFeeder(place=place, feed_list=[data, label])，当使用多GPU时，place参数是place=fluid.CUDAPlace(0)，还是place = [fluid.CUDAPlace(i) for i in range(n)]

**Comment by chengduoZH** [comment]
>  对于DataFeeder的实例化中，feeder = fluid.DataFeeder(place=place, feed_list=[data, label])，当使用多GPU时，place参数是place=fluid.CUDAPlace(0)，还是place = [fluid.CUDAPlace(i) for i in range(n)]

如果是feed的方式，`feeder = fluid.DataFeeder(place=place, feed_list=[data, label])`中的place应该是单个Place，比如`place=fluid.CUDAPlace(0)`，在多卡训练时，会将数据split，然后将GPU0上的拷贝到其他GPU上。
