### ISSUE TITLE
训练到某个batch 在reader中陷入死循环

### ISSUE THREAD

**Issue by Cristhine** [PaddlePaddle/Paddle#18912]
训练网络的过程中,可以正常训练部分batch
结果如下：
Loaded 59468 images
after run
Iter 0, lr 0.000000, smoke_acc 0.0488, phone_acc 0.0413, safe_acc 0.0919, hand_acc 0.0653, forward_acc 0.0428, average loss 1047.4664,                 smooth_loss 10474.6641, cur_loss 10474.6641, yolo_loss 1047.2461, rcnn_cls_loss 0.1949, rcnn_box_loss 0.0251,                 smoke_loss 0.0000, phone_loss 0.0000, safe_loss 0.0003, hand_loss 0.0000, forward_loss 0.0000, average time: 4.63962554932e-05
after run
after run
after run
after run
after run
after run
after run
after run
after run
after run
Iter 10, lr 0.000020, smoke_acc 0.1884, phone_acc 0.2613, safe_acc 0.6603, hand_acc 0.5488, forward_acc 0.3850, average loss 3413.7736,                 smooth_loss 4055.6727, cur_loss 32.6192, yolo_loss 3411.5710, rcnn_cls_loss 1.9221, rcnn_box_loss 0.2540,                 smoke_loss 0.0058, phone_loss 0.0058, safe_loss 0.0052, hand_loss 0.0087, forward_loss 0.0010, average time: 5.36966350079
after run
after run
after run
after run
after run
然后在某一个batch就不往下训练了，没有报错信息，一直停在这里，定位在reader.py函数里是，一直在读取数据；

**Comment by heavengate** [comment]
应该是reader有问题，python train.py --use_multiprocess_reader=False看下报什么错

**Comment by Cristhine** [comment]
> 应该是reader有问题，python train.py --use_multiprocess_reader=False看下报什么错

就是这么运行的，设置的--use_multiprocess_reader=False，batchsize很小是1

**Comment by Cristhine** [comment]
> 应该是reader有问题，python train.py --use_multiprocess_reader=False看下报什么错

paddle读数据是异步的嘛？明明有yield 为何会打印出很多batch的数据 但是就是不运行exe.run

**Comment by heavengate** [comment]
使用multiprocess reader的时候读取数据是异步的，会起多个reader进程读到一个队列里面，训练时从对齐去取，不使用multiprocess reader的时候是同步的，读一个batch的数据跑一个iter
