### ISSUE TITLE
paddle1.5 layers.range op不能接收layers.shape()[i] 做为输入

### ISSUE THREAD

**Issue by jiangbojian** [PaddlePaddle/Paddle#18936]
环境：使用paddlepaddle1.5版本，V100GPU，单卡，CUDA9.0，CUDNN7.1 python2.7
当调用layers.range(start, end, step, dtype)时，如果end传入一个tensor的shape的某一个维度，运行过程中出core,如果把end改为定值，则可以运行通过。

**Comment by baiyfbupt** [comment]
初步判断是因为range()现不支持int64的dytpe引起的core dump，如果需要paddle支持range的int64实现您可以继续在该issue中反馈 @jiangbojian
