### ISSUE TITLE
paddle 1.5.0 训练ocr_ctc dlopen: cannot load any more object with static TLS

### ISSUE THREAD

**Issue by saberSabersaber** [PaddlePaddle/Paddle#18930]
![image](https://user-images.githubusercontent.com/26018086/62197795-14250880-b3b3-11e9-8a1a-3d7f234e6634.png)

**Comment by NHZlX** [comment]
find / -name   {该lib名} 

然后把路径加入到 LD_LIBRARY_PATH中试试

**Comment by saberSabersaber** [comment]
这个已经试过了

**Comment by saberSabersaber** [comment]
![image](https://user-images.githubusercontent.com/26018086/62207340-7b988380-b3c6-11e9-96f8-47bc5b8fa375.png)
![Uploading image.png…]()

**Comment by saberSabersaber** [comment]
![image](https://user-images.githubusercontent.com/26018086/62207702-65d78e00-b3c7-11e9-8964-914d7e1fb86e.png)
![image](https://user-images.githubusercontent.com/26018086/62207719-74be4080-b3c7-11e9-9880-25773b5ca2ba.png)
