### ISSUE TITLE
关于文档缺失问题

### ISSUE THREAD

**Issue by 18628271760** [PaddlePaddle/Paddle#18949]
PaddlePaddle相关负责人：
我司在对智能智能平台进行对比预研过程中，发现贵方的文档有较大缺失。API接口文档局限于fluid子类，其它子类未覆盖。实例程序中引用了其它子类下的函数，如batch，reader, compat等子类函数在实列中出现也未有参考资料。这给评估，学习，工程带来了极大麻烦。希望贵方早日完善文档。
![fyi](https://user-images.githubusercontent.com/38900261/62260963-5d726800-b446-11e9-84b5-115921a974de.jpg)

<img width="157" alt="fyi2" src="https://user-images.githubusercontent.com/38900261/62261012-8135ae00-b446-11e9-83f6-1c5374c0cf9c.png">

**Comment by JiabinYang** [comment]
感谢您的关注，我们正在全力调整相关文档，将在短期内实现改善，敬请关注

**Comment by 18628271760** [comment]
谢谢
