### ISSUE TITLE
MKLDNNDeviceContext Global Variables and Functions Code Clean 

### ISSUE THREAD

**Issue by luotao1** [PaddlePaddle/Paddle#18944]
There are several global variables and functions：
https://github.com/PaddlePaddle/Paddle/blob/fe32879d2abf9efeb2839eba27e8a419852635fc/paddle/fluid/platform/device_context.h#L380-L399
Could they move into `MKLDNNDeviceContext` class? @jczaja @LeoZhao-Intel

**Comment by jczaja** [comment]
I have proposed some encapsulation of those global objects , but mostly they are  thread local storage objects , so It does not seem proper to put them into MKLDNNDeviceContext. Modification is part of 
#21466. Feel free to comment

**Comment by luotao1** [comment]
@jczaja Could you continue the TLS refactoring?

**Comment by jczaja** [comment]
@luotao1 I will work on this task next week

**Comment by jczaja** [comment]
@pawelpiotrowicz Please take a look at that one.

**Comment by pawelpiotrowicz** [comment]
https://github.com/PaddlePaddle/Paddle/pull/23066

**Comment by jczaja** [comment]
merged
