### ISSUE TITLE
Enable gradient clipping.

### ISSUE THREAD

**Issue by qingqing01** [PaddlePaddle/Paddle#1894]
This issue is related to #775 and #1891. I'll try to fix it. On the other hand, is it necessary to enable gradient and error clipping in gru-memory and lstm-memory which are implemented in one cpp file (not in the recurrent layer group)?  @hedaoyuan @lcy-seso

**Comment by lcy-seso** [comment]
Is it necessary to implement norm gradient clipping in PaddlePaddle, for example, [constraint a certain norm](https://www.reddit.com/r/MachineLearning/comments/31b6x8/gradient_clipping_rnns/) of gradient matrix by a threshold?

**Comment by lcy-seso** [comment]
Gradient clipping is critical to the stable training process of RNN models, this issue https://github.com/PaddlePaddle/Paddle/issues/1961 is also related to gradient clipping.
