### ISSUE TITLE
lstm_unit使用报错

### ISSUE THREAD

**Issue by fengchun1213** [PaddlePaddle/Paddle#18961]
paddle版本1.5.1，使用lstm_unit报错，代码如下：
import paddle.fluid as fluid

input = fluid.layers.ones(shape=[1, 256], dtype='float32')
output = fluid.layers.ones(shape=[1, 256], dtype='float32')

prev_hidden = fluid.layers.ones(shape=[1, 256], dtype='float32')
prev_cell = fluid.layers.ones(shape=[1, 256], dtype='float32')

hidden = fluid.layers.lstm_unit(x_t=input,
                                hidden_t_prev=prev_hidden,
                                cell_t_prev=prev_cell)

result = fluid.layers.fc(hidden[0], 256)

cost = fluid.layers.square_error_cost(input=result, label=output)
avg_cost = fluid.layers.reduce_mean(cost)

optimizer = fluid.optimizer.Adadelta(
    learning_rate=1.0, epsilon=1.0e-8, rho=0.95)
optimizer.minimize(avg_cost)

cpu = fluid.core.CPUPlace()
exe = fluid.Executor(cpu)
exe.run(fluid.default_startup_program())
for i in range(100):
    outs = exe.run(
        fetch_list=[avg_cost.name])
    print(outs[0])
报错信息：

Traceback (most recent call last):
  File "/Users/fengchun/Documents/PycharmProjects/crnn_paddle/aaa.py", line 22, in <module>
    optimizer.minimize(avg_cost)
  File "</Users/fengchun/anaconda3/envs/paddlepaddle/lib/python3.7/site-packages/decorator.py:decorator-gen-20>", line 2, in minimize
  File "/Users/fengchun/anaconda3/envs/paddlepaddle/lib/python3.7/site-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
    return wrapped_func(*args, **kwargs)
  File "/Users/fengchun/anaconda3/envs/paddlepaddle/lib/python3.7/site-packages/paddle/fluid/dygraph/base.py", line 87, in __impl__
    return func(*args, **kwargs)
  File "/Users/fengchun/anaconda3/envs/paddlepaddle/lib/python3.7/site-packages/paddle/fluid/optimizer.py", line 594, in minimize
    no_grad_set=no_grad_set)
  File "/Users/fengchun/anaconda3/envs/paddlepaddle/lib/python3.7/site-packages/paddle/fluid/optimizer.py", line 493, in backward
    no_grad_set, callbacks)
  File "/Users/fengchun/anaconda3/envs/paddlepaddle/lib/python3.7/site-packages/paddle/fluid/backward.py", line 578, in append_backward
    _append_backward_vars_(root_block, fwd_op_num, grad_to_var, grad_info_map)
  File "/Users/fengchun/anaconda3/envs/paddlepaddle/lib/python3.7/site-packages/paddle/fluid/backward.py", line 392, in _append_backward_vars_
    op_desc.infer_shape(block.desc)
paddle.fluid.core_avx.EnforceNotMet: Input(C@GRAD) should not be null at [/home/teamcity/work/ef54dc8a5b211854/paddle/fluid/operators/lstm_unit_op.cc:88]
PaddlePaddle Call Stacks: 
0          0x122fd7aacp void paddle::platform::EnforceNotMet::Init<char const*>(char const*, char const*, int) + 636
1          0x122fd77dbp paddle::platform::EnforceNotMet::EnforceNotMet(std::exception_ptr, char const*, int) + 139
2          0x123549e16p paddle::operators::LstmUnitGradOp::InferShape(paddle::framework::InferShapeContext*) const + 1382
3          0x12313ac08p paddle::framework::OpDesc::InferShape(paddle::framework::BlockDesc const&) const + 1464
4          0x1230945b6p void pybind11::cpp_function::initialize<pybind11::cpp_function::cpp_function<void, paddle::framework::OpDesc, paddle::framework::BlockDesc const&, pybind11::name, pybind11::is_method, pybind11::sibling>(void (paddle::framework::OpDesc::*)(paddle::framework::BlockDesc const&) const, pybind11::name const&, pybind11::is_method const&, pybind11::sibling const&)::'lambda'(paddle::framework::OpDesc const*, paddle::framework::BlockDesc const&), void, paddle::framework::OpDesc const*, paddle::framework::BlockDesc const&, pybind11::name, pybind11::is_method, pybind11::sibling>(void&&, paddle::framework::OpDesc (*)(paddle::framework::BlockDesc const&), pybind11::name const&, pybind11::is_method const&, pybind11::sibling const&)::'lambda'(pybind11::detail::function_call&)::operator()(pybind11::detail::function_call&) const + 198
5          0x122fbca38p pybind11::cpp_function::dispatcher(_object*, _object*, _object*) + 3400
6          0x1092b9c48p _PyMethodDef_RawFastCallKeywords + 392
7          0x1092b9710p _PyObject_FastCallKeywords + 592
8          0x1093fa33fp call_function + 399
9          0x1093f7dafp _PyEval_EvalFrameDefault + 45215
10         0x1092b9368p function_code_fastcall + 120
11         0x1093fa265p call_function + 181
12         0x1093f7f99p _PyEval_EvalFrameDefault + 45705
13         0x1093eba42p _PyEval_EvalCodeWithName + 418
14         0x1092b9a73p _PyFunction_FastCallKeywords + 195
15         0x1093fa265p call_function + 181
16         0x1093f7f99p _PyEval_EvalFrameDefault + 45705
17         0x1093eba42p _PyEval_EvalCodeWithName + 418
18         0x1092b9a73p _PyFunction_FastCallKeywords + 195
19         0x1093fa265p call_function + 181
20         0x1093f8052p _PyEval_EvalFrameDefault + 45890
21         0x1093eba42p _PyEval_EvalCodeWithName + 418
22         0x1092b8867p _PyFunction_FastCallDict + 231
23         0x1093f81c6p _PyEval_EvalFrameDefault + 46262
24         0x1093eba42p _PyEval_EvalCodeWithName + 418
25         0x1092b8867p _PyFunction_FastCallDict + 231
26         0x1093f81c6p _PyEval_EvalFrameDefault + 46262
27         0x1093eba42p _PyEval_EvalCodeWithName + 418
28         0x1092b9a73p _PyFunction_FastCallKeywords + 195
29         0x1093fa265p call_function + 181
30         0x1093f7f99p _PyEval_EvalFrameDefault + 45705
31         0x1093eba42p _PyEval_EvalCodeWithName + 418
32         0x1092b9a73p _PyFunction_FastCallKeywords + 195
33         0x1093fa265p call_function + 181
34         0x1093f7d19p _PyEval_EvalFrameDefault + 45065
35         0x1093eba42p _PyEval_EvalCodeWithName + 418
36         0x10944f9a0p PyRun_FileExFlags + 256
37         0x10944f104p PyRun_SimpleFileExFlags + 388
38         0x10947aedcp pymain_main + 9148
39         0x10928becep main + 142
40      0x7fff5cacf3d5p start + 1
41                 0x2p

**Comment by phlrain** [comment]
input prev_hidden  prev_cell  这三个参数由于stop_gradient = true 所以检查失败了，你可以强制把这三个参数的stop_gradient 设置为false

input.stop_gradient = False

**Comment by fengchun1213** [comment]
> stop_gradient

您好，感谢您的回复，我按照您说的加了这三行代码还是出现了刚才那个问题
input.stop_gradient = False
prev_hidden.stop_gradient = False
prev_cell.stop_gradient = False
