### ISSUE TITLE
动态图Transformer报错

### ISSUE THREAD

**Issue by DDDivano** [PaddlePaddle/Paddle#18962]
版本： linux python3.6  develop分支
![image](https://user-images.githubusercontent.com/10734244/62277241-56fce400-b478-11e9-9f59-e7d104fa885b.png)
这里设置成数字才不报错。1.5.1版本无此问题
![image](https://user-images.githubusercontent.com/10734244/62277887-a2fc5880-b479-11e9-8f4b-037331eab327.png)

**Comment by JiabinYang** [comment]
this is because of PR #18813 , and @ceci3 will fix in small change, and I will change model to avoid these problems
