### ISSUE TITLE
win10 MFC paddle   我想在windows下的MFC中使用paddle调用训练好的模型进行预测，但是我没有找到具体的方法，因为我看官网上安装例子中都是python调用。不知道，各位大神能否指点一下？（我理解的应该向opencv一样，下载后配置库文件可头文件的路径即可调用）

### ISSUE THREAD

**Issue by liulihupan** [PaddlePaddle/Paddle#18963]
为使您的问题得到快速解决，在建立Issue前，请您先通过如下方式搜索是否有相似问题:【搜索issue关键字】【使用labels筛选】【官方文档】

建立issue时，为快速解决问题，请您根据使用情况给出如下信息：
- 标题：请包含关键词“安装错误”/“编译错误”，例如“Mac编译错误”
- 版本、环境信息：
    1）PaddlePaddle版本：请提供您的PaddlePaddle版本号（如1.1）或CommitID
    2）CPU：请提供CPU型号，MKL/OpenBlas/MKLDNN/等数学库的使用情况
    3）GPU：请提供GPU型号，CUDA和CUDNN版本号
    4）系统环境：请说明系统类型、版本（如Mac OS 10.14）、Python版本
- 安装方式信息：
1）pip安装/docker安装
2）本地编译：请提供cmake命令，编译命令
3）docker编译：请提供docker镜像，编译命令            
  特殊环境请注明：如离线安装等
- 复现信息：如为报错，请给出复现环境、复现步骤
- 问题描述：请详细描述您的问题，同步贴出报错信息、日志/代码关键片段

Thank you for contributing to PaddlePaddle.
Before submitting the issue, you could search issue in Github in case that there was a similar issue submitted or resolved before.
If there is no solution,please make sure that this is an installation issue including the following details:
**System information**
-PaddlePaddle version （eg.1.1）or CommitID
-CPU: including CPUMKL/OpenBlas/MKLDNN version
-GPU: including CUDA/CUDNN version
-OS Platform (eg. Mac OS 10.14)
-Python version
- Install method: pip install/install with docker/build from source(without docker)/build within docker
- Other special cases that you think may be related to this problem, eg. offline install, special internet condition   
**To Reproduce**
Steps to reproduce the behavior
**Describe your current behavior**
**Code to reproduce the issue**
**Other info / logs**

**Comment by liulihupan** [comment]
我想在windows下的MFC中使用paddle调用训练好的模型进行预测，但是我没有找到具体的方法，因为我看官网上安装例子中都是python调用。不知道，各位大神能否指点一下？（我理解的应该向opencv一样，下载后配置库文件可头文件的路径即可调用）

**Comment by liupluswei** [comment]
> 我想在windows下的MFC中使用paddle调用训练好的模型进行预测，但是我没有找到具体的方法，因为我看官网上安装例子中都是python调用。不知道，各位大神能否指点一下？（我理解的应该向opencv一样，下载后配置库文件可头文件的路径即可调用）

你好，我们暂时还未对windows提供官方的预测库支持，这项工作正在进行中，预计在8月中下旬会在官网上线正式的文档说明。

**Comment by liulihupan** [comment]
非常感谢您得帮助！
