### ISSUE TITLE
网络输出tensor如何取出某一维度

### ISSUE THREAD

**Issue by cqu-ls** [PaddlePaddle/Paddle#18967]
有一层网络的输出output的dims是-1，747，15，如何取出某一维度，例如取出output的第410行，output[410]，并且保证取出值得dims应该是-1*15，而不是15
name: "relu_0.tmp_0"
type {
  type: LOD_TENSOR
  lod_tensor {
    tensor {
      data_type: FP32
      dims: -1
      dims: 747
      dims: 15
    }
    lod_level: 0
  }
}

**Comment by JiabinYang** [comment]
可以试试output[,410,]

**Comment by cqu-ls** [comment]
这样取不出来，这是我的代码，或者您可以自己调试一下取出某个网络输出的某一个维度的值

import paddle.fluid as fluid
from networkx import karate_club_graph, to_numpy_matrix
#准备GCN 网络配置
import numpy as np
zkc = karate_club_graph()
order = sorted(list(zkc.nodes()))
N = len(order)
M = 2


adjacency = fluid.layers.data(name="adjacency",shape=[N,N],dtype='float')
features = fluid.layers.data(name="features",shape=[N,M],dtype='float')
degree = fluid.layers.data(name='degree',shape=[N,N],dtype='float')
label = fluid.layers.data(name='label',shape=[N,1],dtype='float')

weights = fluid.layers.create_parameter(name='w1',shape=[M,10],dtype='float')

def GCN(adjacency,degree,features,weights):
    #d_ = tf.pow(degree,-0.5)#连接度
    y = fluid.layers.matmul(degree,fluid.layers.matmul(adjacency,degree))       
    #kernal = fluid.layers.fc(input=features, size=N, act=None)
    kernal = fluid.layers.matmul(features,weights)   
    out = fluid.layers.relu(fluid.layers.matmul(y,kernal))
    return out

out = GCN(adjacency,degree,features,weights)



A = to_numpy_matrix(zkc, nodelist=order)
#print(A)
I = np.eye(zkc.number_of_nodes())
fea = (np.array([[i,2*i] for i in range(34)])+0.0).astype('float')
#print(type(fea))

A_hat = A + I
D_hat = np.array(np.sum(A_hat, axis=0))[0]
D_hat = D_hat*np.eye(len(D_hat))

#D_hat = np.matrix(np.diag(D_hat))
label_hat = np.append(np.zeros(10)+0.0,(np.ones(24)+0.0)).astype('float')

temp_degree = np.linalg.inv(np.power(D_hat,0.5))

#定义Exector
cpu = fluid.core.CPUPlace() #定义运算场所，这里选择在CPU下训练
exe = fluid.Executor(cpu) #创建执行器
exe.run(fluid.default_startup_program()) #网络参数初始化

#,avg_cost.name
#执行计算
outs = exe.run(feed={'adjacency':A_hat,'features':fea,'degree':temp_degree,'label':label_hat},fetch_list=[out.name])
#验证结果
#print(np.array(outs[0]))
print(out)
print(out[3])
print(out[0,3])

**Comment by JiabinYang** [comment]
可以试试out[:,410,:]

**Comment by cqu-ls** [comment]
这样的方法在执行器run之后是没问题的，但是在网络搭建过程中还是有问题，比如在上面的代码中最后的print(out[:,20,:])放在out之后，而不是放在run之后，就会出现问题

**Comment by cqu-ls** [comment]
还有想问一下有没有这种取出来网络某一层输出中的一维作为下一层网络的输入的Demo？

**Comment by JiabinYang** [comment]
可以参考这段代码：

        import paddle.fluid as fluid
        # from networkx import karate_club_graph, to_numpy_matrix
        #准备GCN 网络配置
        import numpy as np
        N = 20
        M = 2
        
        adjacency = fluid.layers.data(name="adjacency",shape=[N,N],dtype='float')
        features = fluid.layers.data(name="features",shape=[N,M],dtype='float')
        degree = fluid.layers.data(name='degree',shape=[N,N],dtype='float')
        label = fluid.layers.data(name='label',shape=[N,1],dtype='float')
        
        weights = fluid.layers.create_parameter(name='w1',shape=[M,10],dtype='float')
        
        def GCN(adjacency,degree,features,weights):
            #d_ = tf.pow(degree,-0.5)#连接度
            y = fluid.layers.matmul(degree,fluid.layers.matmul(adjacency,degree))
            #kernal = fluid.layers.fc(input=features, size=N, act=None)
            kernal = fluid.layers.matmul(features,weights)
            out = fluid.layers.relu(fluid.layers.matmul(y,kernal))
            return out
        
        out = GCN(adjacency,degree,features,weights)
        print("original is : {}".format(out))
        final = out[:,3,:]
        final_out = fluid.layers.reduce_sum(final)
        print("final is : {}".format(final))
        
        A_hat = np.ones(shape= [2,20,20], dtype='float')
        fea = np.ones(shape= [2,20,2], dtype='float')
        temp_degree = np.ones(shape= [2,20,20], dtype='float')
        label_hat = np.ones(shape= [2,20,1], dtype='float')
        #定义Exector
        cpu = fluid.core.CPUPlace() #定义运算场所，这里选择在CPU下训练
        exe = fluid.Executor(cpu) #创建执行器
        exe.run(fluid.default_startup_program()) #网络参数初始化
        
        #,avg_cost.name
        #执行计算
        outs = exe.run(feed={'adjacency':A_hat,'features':fea,'degree':temp_degree,'label':label_hat},fetch_list=[out.name])
        #验证结果
        #print(np.array(outs[0]))
        print("out is : {}".format(outs))
