### ISSUE TITLE
关于Program的自定义问题

### ISSUE THREAD

**Issue by 18628271760** [PaddlePaddle/Paddle#18964]
PaddlePaddle团队，
Fluid版本的Paddle中使用Program的形式描述计算过程，但如果用户需要按自己业务需求定义多个program，不使用fluid.default_startup_program()可否？
如果可以使用custom program，应该如何定义使用？有例子，参考链接为宜。

**Comment by JiabinYang** [comment]
可以的，您可以参考文档https://www.paddlepaddle.org.cn/documentation/docs/zh/1.5/api_cn/fluid_cn.html#program
在执行时传入自定义的program即可

**Comment by 18628271760** [comment]
tks

**Comment by 18628271760** [comment]
tks

**Comment by 18628271760** [comment]
tks

**Comment by 18628271760** [comment]
tks
