### ISSUE TITLE
FP16 训练过程中出现 "an illegal memory access was encountered"

### ISSUE THREAD

**Issue by mzchtx** [PaddlePaddle/Paddle#18978]
## 环境

+ paddlepaddle-gpu: 1.5.0.post97 
+ python: 2.7.9 
+ Driver Version: 396.26

## 错误信息

如下：

![image](https://user-images.githubusercontent.com/37564754/62347936-0051e180-b52e-11e9-8586-31558863cb91.png)

**Comment by sandyhouse** [comment]
方便提供下如何复现该问题的信息吗（模型，训练脚本和配置等信息）？ @mzchtx

**Comment by mzchtx** [comment]
> 方便提供下如何复现该问题的信息吗（模型，训练脚本和配置等信息）？ @mzchtx

目前没有稳定复现，只有一个任务出现了这种情况，后续再出现同步给你们
