### ISSUE TITLE
TensorRT报错信息需要优化

### ISSUE THREAD

**Issue by OliverLPH** [PaddlePaddle/Paddle#18976]
- 标题：TensorRT报错信息需要优化
- 版本、环境信息：
    1）PaddlePaddle版本：1.5
    2）CPU：
    3）GPU：P4, cuda10,  cudnn7.4, Nvidia-smi:410.79
    4）系统环境：Ubuntu1604，Python2.7，
    5）TRT：TensorRT-5.1.5.0.Ubuntu-16.04.5.x86_64-gnu.cuda-10.0.cudnn7.5.tar
-预测信息
    1）C++预测：请您提供预测库安装包的版本信息，及其中的version.txt文件
    2）CMake包含路径的完整命令

```shell
cmake .. -DWITH_FLUID_ONLY=ON -DWITH_SWIG_PY=OFF -DWITH_PYTHON=ON -DWITH_MKL=ON -DWITH_GPU=ON -DWITH_MKLDNN=OFF -DON_INFER=ON -DCMAKE_BUILD_TYPE=Release -DTENSORRT_ROOT=/lipeihan01/TensorRT/TensorRT-5.1.5.0
```

    3）API信息（如调用请提供）

```python
config.enable_tensorrt_engine(1 << 20, 1,
                                              use_calib_mode=True,
                                              use_static=False,
                                              precision_mode=fluid.core.AnalysisConfig.Precision.Int8)
```

    4）预测库来源：源码编译
- 复现信息：
配置里面使用了 trt float或者trt int8就会挂掉

- 问题描述：请详细描述您的问题，同步贴出报错信息、日志/代码关键片段
![image](https://user-images.githubusercontent.com/14963836/62341154-c88a7000-b514-11e9-94ee-749629212c40.png)

这个是执行之后的报错信息，看不出来错误原因。

但感觉可能是找不到对应的动态链接库，于是把TRT和cuda的库都放进去
```shell
export LD_LIBRARY_PATH=/lipeihan01/TensorRT/TensorRT-5.1.5.0/lib/:$LD_LIBRARY_PATH
export LD_LIBRARY_PATH=/cuda-10.0/lib64/:$LD_LIBRARY_PATH
```

![image](https://user-images.githubusercontent.com/14963836/62341296-58301e80-b515-11e9-91f4-51441cc56620.png)
结果就可以了，虽然会提示cudnn的版本不对。

**之前paddle如果找不到相应库应该是会出现下图的提示信息**
![image](https://user-images.githubusercontent.com/14963836/62341382-b0ffb700-b515-11e9-8743-cb89dd0eb65b.png)

**Comment by jeng1220** [comment]
@OliverLPH ,
After merged #20858 , Cmake will threw a warning - `TensorRT is NOT found` if it fail to find TensorRT, or show the version and path of TensorRT if it find TensorRT.
