### ISSUE TITLE
Tensor 转 LoD-Tensor 示例，为什么输入的是list

### ISSUE THREAD

**Issue by dingsiyu** [PaddlePaddle/Paddle#18986]
- 版本、环境信息：
    1）PaddlePaddle版本：1.5
    2）CPU/GPU：cuda 10, cudnn 7.4
    3）系统环境：centos 6
    4）Python版本号 3

这是官方代码：

**LoD-Tensor 转 Tensor**

import paddle.fluid as fluid
import numpy as np
# 创建一个 LoD-Tensor
a = fluid.create_lod_tensor(np.array([[1.1], [2.2],[3.3],[4.4]]).astype('float32'), [[1,3]], fluid.CPUPlace())
def LodTensor_to_Tensor(lod_tensor):
  # 获取 LoD-Tensor 的 lod 信息
  lod = lod_tensor.lod()
  # 转换成 array
  array = np.array(lod_tensor)
  new_array = []
  # 依照原LoD-Tensor的层级信息，转换成Tensor
  for i in range(len(lod[0]) - 1):
      new_array.append(array[lod[0][i]:lod[0][i + 1]])
  return new_array
new_array = LodTensor_to_Tensor(a)
# 输出结果
print(new_array)

**Tensor 转 LoD-Tensor**
import paddle.fluid as fluid
import numpy as np

def to_lodtensor(data, place):
  # 存储Tensor的长度作为LoD信息
  seq_lens = [len(seq) for seq in data]
  cur_len = 0
  lod = [cur_len]
  for l in seq_lens:
      cur_len += l
      lod.append(cur_len)
  # 对待转换的 Tensor 降维
  flattened_data = np.concatenate(data, axis=0).astype("int64")
  flattened_data = flattened_data.reshape([len(flattened_data), 1])
  # 为 Tensor 数据添加lod信息
  res = fluid.LoDTensor()
  res.set(flattened_data, place)
  res.set_lod([lod])
  return res

# new_array 为上段代码中转换的Tensor
lod_tensor = to_lodtensor(new_array,fluid.CPUPlace())

# 输出 LoD 信息
print("The LoD of the result: {}.".format(lod_tensor.lod()))

# 检验与原Tensor数据是否一致
print("The array : {}.".format(np.array(lod_tensor)))

问题：为什么new_array是个list，按照标题，不是应该是tensor吗？
而且，我直接向to_lodtensor输入一个tensor后，报错。具体如下：

代码：
a = np.array([[1,2,3],[4,5,6],[7,8,9]], dtype="float32")
b = fluid.layers.create_tensor(dtype="float32")
fluid.layers.assign(a,b)
lodtensor = to_lodtensor(b, fluid.CPUPlace)

报错信息：
Traceback (most recent call last):
  File "b.py", line 56, in <module>
    lodtensor = to_lodtensor(b, fluid.CPUPlace)
  File "b.py", line 35, in to_lodtensor
    seq_lens = [len(seq) for seq in data]
  File "b.py", line 35, in <listcomp>
    seq_lens = [len(seq) for seq in data]
TypeError: object of type 'Variable' has no len()

**Comment by dingsiyu** [comment]
如何将tensor转为lod_tensor

**Comment by wzzju** [comment]
您好！在Paddle中所有的Tensor都是LoDTensor，文章标题中所谓的“ tensor”指的是nparray的list，您阅读一下`to_lodtensor `代码实现即可明白。

**Comment by wzzju** [comment]
>> 我直接向to_lodtensor输入一个tensor后，报错。具体如下：
>>
>> 代码：
>> a = np.array([[1,2,3],[4,5,6],[7,8,9]], dtype="float32")
>> b = fluid.layers.create_tensor(dtype="float32")
>> fluid.layers.assign(a,b)
>> lodtensor = to_lodtensor(b, fluid.CPUPlace)
>> 
>> 报错信息：
>> Traceback (most recent call last):
>> File "b.py", line 56, in 
>> lodtensor = to_lodtensor(b, fluid.CPUPlace)
>> File "b.py", line 35, in to_lodtensor
>> seq_lens = [len(seq) for seq in data]
>> File "b.py", line 35, in 
>> seq_lens = [len(seq) for seq in data]
>> TypeError: object of type 'Variable' has no len()

首先，您使用`fluid.layers.create_tensor`创建的b是一个Variable类型，需要通过Executor运行才能得到Tensor结果，这点从报错信息`'Variable' has no len()`即可知道。其次，就算您使用了Executor运行得到的也是LoDTensor，并非Tensor。当然若您不设置LoD信息也可认为得到的就是Tensor，但是这个所谓的Tensor转LoDTensor是不能使用`to_lodtensor`（因为其定义需要的输入是ndarray list，这个list每个元素的长度指明了lod信息），您可以想一下，`to_lodtensor`只有一个输入，如果lod信息不在这个输入中，它便不能将输入转成LoDTensor。如果只是一个Tensor的话，其想要转为LoDTensor也很容易，示例代码如下：
```python
import paddle.fluid as fluid
import numpy as np
a = np.array([[1,2,3],[4,5,6],[7,8,9]], dtype="float32")
b = fluid.layers.create_tensor(dtype="float32")
fluid.layers.assign(a, b)
#定义运算场所
place = fluid.CPUPlace()
#创建执行器
exe = fluid.Executor(place)
exe.run(fluid.default_startup_program())
results = exe.run(fluid.default_main_program(),
                  fetch_list=[b], return_numpy=False)
# 设置了lod的Tensor才是LoDTensor
results[0].set_lod([[0, 1, 3]])
lod_tensor = results[0]
# 输出 LoD 信息
print("The LoD of the result: {}.".format(lod_tensor.lod()))

# 检验与原Tensor数据是否一致
print("The array : {}.".format(np.array(lod_tensor)))
```

**Comment by wzzju** [comment]
再送您一段代码，帮助您理解，示例如下：

```python
import paddle.fluid as fluid
import numpy as np

def to_lodtensor(data, place):
  # 存储Tensor的长度作为LoD信息
  seq_lens = [len(seq) for seq in data] 
  cur_len = 0
  lod = [cur_len]
  for l in seq_lens:
      cur_len += l
      lod.append(cur_len)    
  # 对待转换的 Tensor 降维
  flattened_data = np.concatenate(data, axis=0).astype("int64")
  flattened_data = flattened_data.reshape([len(flattened_data), len(flattened_data[0])])
  # 为 Tensor 数据添加lod信息
  res = fluid.LoDTensor()
  res.set(flattened_data, place)
  res.set_lod([lod])
  return res

def LodTensor_to_Tensor(lod_tensor):
  # 获取 LoD-Tensor 的 lod 信息
  lod = lod_tensor.lod()
  # 转换成 array
  array = np.array(lod_tensor)
  new_array = []
  # 依照原LoD-Tensor的层级信息，转换成Tensor
  for i in range(len(lod[0]) - 1):
      new_array.append(array[lod[0][i]:lod[0][i + 1]])
  return new_array

a = np.array([[1,2,3],[4,5,6],[7,8,9]], dtype="float32")
b = fluid.layers.create_tensor(dtype="float32")
fluid.layers.assign(a, b)
# 设置lod信息，因为create_tensor运行后得到的是LoDTensor
c = fluid.layers.lod_reset(x=b, target_lod=[0, 1, 3])
#定义运算场所
place = fluid.CPUPlace()
#创建执行器
exe = fluid.Executor(place)
exe.run(fluid.default_startup_program())
results = exe.run(fluid.default_main_program(),
                  fetch_list=[c], return_numpy=False)
# 得到的d是一个nparray的list
d = LodTensor_to_Tensor(results[0])
lodtensor = to_lodtensor(d, fluid.CPUPlace())
# 输出 LoD 信息
print("The LoD of the result: {}.".format(lodtensor.lod()))

# 检验与原Tensor数据是否一致
print("The array : {}.".format(np.array(lodtensor)))
```

**Comment by ChChwang** [comment]
> to_lodtensor

训练过程中，reshape 会将lodtensor转为tensor么？后面接warpctc 需要 lodtensor ，怎么转回来呢
