### ISSUE TITLE
编译安装出现error: identifier "__shfl_down" is undefined

### ISSUE THREAD

**Issue by hitwangshuai** [PaddlePaddle/Paddle#18985]
![image](https://user-images.githubusercontent.com/22500910/62365596-11631880-b557-11e9-9c2b-98fc126c32a5.png)
求助编译安装出现上述问题是什么原因

**Comment by wanghaoshuang** [comment]
@hitwangshuai 请问您的系统版本和CUDA，CUDNN版本分别是？

**Comment by wanghaoshuang** [comment]
https://github.com/xmfbit/warpctc-caffe/issues/10

**Comment by wanghaoshuang** [comment]
https://github.com/apache/incubator-mxnet/issues/9632

**Comment by wanghaoshuang** [comment]
https://github.com/SeanNaren/deepspeech.pytorch/issues/397

**Comment by wanghaoshuang** [comment]
看起来是CUDA版本的问题。

**Comment by jeng1220** [comment]
Yes, after CUDA9, `__shfl_down` was deprecated due to safety issue. Please read appendix B.16 in CUDA document ([link](https://docs.nvidia.com/cuda/cuda-c-programming-guide/index.html#warp-shuffle-functions)) 
> Deprecation Notice: __shfl, __shfl_up, __shfl_down, and __shfl_xor have been deprecated in CUDA 9.0 for all devices

To fix this issue, we need to upgrade the third party - `warpctc`.

**Comment by jeng1220** [comment]
@hitwangshuai,
I saw that in `develop` branch of PaddlePaddle, this issue should be fixed ([link](https://github.com/wopeizl/warp-ctc/blob/master/src/reduce.cu#L44)).

```c
#if defined(__CUDACC_VER_MAJOR__) && (__CUDACC_VER_MAJOR__ >= 9)
            shuff = __shfl_down_sync(0xFFFFFFFF, x, offset);
#else
            shuff = __shfl_down(x, offset);
#endif
```
Note: In PaddlePaddle v1.6, this bug was not fixed yet.
