### ISSUE TITLE
请问怎么实现mobilenetV3的hswish激活函数 需要自己写op吗

### ISSUE THREAD

**Issue by Hsintao** [PaddlePaddle/Paddle#18993]
请问怎么实现mobilenetV3的hswish激活函数 需要自己写op吗

**Comment by wangguibao** [comment]
现在还没有支持hswitch激活函数，如果着急用的话，可以自己写OP

**Comment by frankwhzhang** [comment]
这个正在合入 着急的话可以先组一个
<img width="449" alt="acef407589019d9ede8a4ac3fb06f7cc" src="https://user-images.githubusercontent.com/20274488/62444962-9cc7ee00-b791-11e9-822e-36812d510f4d.png">

**Comment by frankwhzhang** [comment]
x * fluid.layers.relu6(x+3.) / 6.

**Comment by Hsintao** [comment]
> x * fluid.layers.relu6(x+3.) / 6.

谢谢回复 这个是动态图的写法吗 原来paddle也可以像pytorch那样写自定义层呀

**Comment by wangguibao** [comment]
Paddle fluid从1.4开始支持动态图机制，请参考这个页面：
https://www.paddlepaddle.org.cn/documentation/docs/zh/1.4/user_guides/howto/dygraph/DyGraph.html
