### ISSUE TITLE
训练时 发生错误AttributeError: module 'paddle.fluid.framework' has no attribute 'cpu_places'

### ISSUE THREAD

**Issue by zhao1425493031** [PaddlePaddle/Paddle#18992]
安装没问题，执行classifier.py训练时，发生错误AttributeError: module 'paddle.fluid.framework' has no attribute 'cpu_places'   

![image](https://user-images.githubusercontent.com/46149054/62419794-c61a4880-b6c3-11e9-8933-496f275f8abf.png)

**Comment by frankwhzhang** [comment]
请贴一下paddle的版本以及运行程序的代码 有可能是代码API和版本没有对应

**Comment by wangguibao** [comment]
看截图好像是在执行paddleHub时遇到的问题？

**Comment by Steffy-zxf** [comment]
感谢反馈，看错误截图，发现paddle 版本为1.2。 出现这个错误的原因是paddle 1.2下没有cpu_place这个接口。可以将paddle升级至1.4以上的版本。另外有关PaddleHub的问题，欢迎在PaddleHub仓库下提issue （https://github.com/PaddlePaddle/PaddleHub）。

**Comment by wangguibao** [comment]
Hi，该issue已经快2个月了，我先关闭了。如有问题可以重新打开，或在PaddleHub repo下提新issue
