### ISSUE TITLE
单机infer时出现grpc error

### ISSUE THREAD

**Issue by lexy0093** [PaddlePaddle/Paddle#18999]
预测代码：
place = fluid.CPUPlace()
exe = fluid.Executor(place)
[inference_program, feed_target_names, fetch_targets] = fluid.io.load_inference_model(model_path, exe)

def infer(index, feature):

    idx_data = [int(i) for i in index.split(' ')]
    fea_data = [float(i) for i in feature.split(' ')]

    idx_data = np.array(idx_data).astype('int64').reshape([1, -1, 1])
    fea_data = np.array(fea_data).astype('float32').reshape([1, -1, 1])

    result = exe.run(inference_program, feed={"index": idx_data, "feature": fea_data}, 
                                   fetch_list=fetch_targets, return_numpy=True)
    label = np.argmax(result[0][0])
    prob = result[0][0][label]
    print label, prob

if __name__ == '__main__':
    infer('1 2 3 4 5', '0.1 0.2 0.3 0.4 0.5')

日志：
I0805 14:00:02.904944 29076 rpc_client.h:101] init rpc client with trainer_id 0
F0805 14:00:02.928972 30293 grpc_client.cc:424] PrefetchRPC name:[embedding_0.tmp_0@xx:62004], ep:[xx:62004], status:[-1] meets grpc error, error_code:14 error_message:OS Error error_details:
*** Check failure stack trace: ***
    @     0x7f5f48e587ed  google::LogMessage::Fail()
    @     0x7f5f48e5c29c  google::LogMessage::SendToLog()
    @     0x7f5f48e58313  google::LogMessage::Flush()
    @     0x7f5f48e5d7ae  google::LogMessageFatal::~LogMessageFatal()
    @     0x7f5f49babb0e  paddle::operators::distributed::GRPCClient::Proceed()
    @       0x318eab6470  (unknown)
    @       0x318b207851  (unknown)
    @       0x318aee767d  (unknown)
    @              (nil)  (unknown)

**Comment by lexy0093** [comment]
#15224 未能解决该问题

**Comment by wangguibao** [comment]
请参考 #15552
可能是保存模型的时候将transpiled program直接保存下来了，其中带了grpc通信OP。#15552的comments提供了一个保存模型program和参数的方法

**Comment by lexy0093** [comment]
paddle版本：paddle-fluid-v1.4.1

网络结构：

        label = fluid.layers.data(name='label', shape=[1], dtype='int64', lod_level=0)
        index = fluid.layers.data(name='index', shape=[1], dtype='int64', lod_level=1)
        feature = fluid.layers.data(name='feature', shape=[1], dtype='float32', lod_level=1)
        droped = fluid.layers.dropout(x=feature, dropout_prob=self.dropout_prob)
        emb = fluid.layers.embedding(input=index, size=[self.vocab_dim, self.emb_dim], is_sparse=True)
        stk = fluid.layers.expand(feature, expand_times = [1, 256])
        mm = fluid.layers.elementwise_mul(x=emb, y=stk)
        mm_fc = fluid.layers.sequence_pool(input=mm, pool_type='sum')
        fc1 = fluid.layers.relu(x=mm_fc)

        fc2 = fluid.layers.fc(input=fc1, size=self.hid_dim, act='relu')
        pred = fluid.layers.fc(input=[fc1, fc2], size=self.class_dim, act='softmax')

保存模型相关代码：

                if self.save_model:
                    now_path = self.save_path + 'class.trainer_' + str(trainer_id)+ '_epoch_' + str(epoch) + '_model/'
                    os.makedirs(now_path)
                    fluid.io.save_inference_model(
                        dirname=now_path,
                        feeded_var_names=[model_layers['index'].name, model_layers['feature'].name],
                        main_program=main_program,
                        target_vars=[model_layers['pred']],
                        executor=exe)
                if self.save_persistables:
                    now_path = self.save_path + 'class.trainer_' + str(trainer_id)+ '_epoch_' + str(epoch) + '_params/'
                    os.makedirs(now_path)
                    fluid.io.save_persistables(
                        executor=exe,
                        main_program=main_program,
                        dirname=now_path)

paddle-cloud日志链接：
http://10.73.173.39:8910/fileview.html?type=logsdir&path=/&instance=0.app-user-20190802193756-62256--mcdnn-fluid-0802_paddlecloud

**Comment by lexy0093** [comment]
分布式训练，embeding加了is_sparse=True，都会在transpile时加上grpc OP，所以会出现grpc的相关错误信息

**Comment by lexy0093** [comment]
贴一下解决办法：

这个是可以用的，只是分布式训练保存的program有问题，不能直接用于load_inference_model

我刚问了一下分布式的同学，一般用法是：
1) 分布式训练训模型并保存参数
2) 单机训练保存一份单机的main_program + 参数
3) 第1步保存的参数+第2步保存的main_program配合，用于预测

有问题指的是由于设置了is_sparse=True，增加了grpc OP，所以就不能直接用于单机预测

单机保存的program另存为__model__，放到模型参数文件夹，会替换掉分布式训练出来的__model__

**Comment by wangguibao** [comment]
用户反馈上述方式可以解决分布式训练，单机infer的问题。该issue关闭
