### ISSUE TITLE
X2Paddle可以转换tf的NLP预训练模型至fluid版本吗，看官方示例只提供了CV的

### ISSUE THREAD

**Issue by dingsiyu** [PaddlePaddle/Paddle#19002]

**Comment by dingsiyu** [comment]
![image](https://user-images.githubusercontent.com/21340925/62444590-7f465480-b790-11e9-8f48-d0bf8527af62.png)
如果tf的模型是以这种格式保存的，那是不是只需要运行这个函数就行了
python tf2fluid/convert.py --meta_file checkpoint/model.meta --ckpt_dir checkpoint \
                           --in_nodes inputs --input_shape None,224,224,3 \
                           --output_nodes vgg_16/fc8/squeezed --use_cuda True \
                           --input_format NHWC --save_dir paddle_model
不需要示例中将模型保存为checkpoint格式这一步骤

**Comment by dingsiyu** [comment]
https://github.com/PaddlePaddle/X2Paddle/blob/master/tensorflow2fluid/vgg_translate_tutorial.ipynb
这个是官方示例

**Comment by jiangjiajun** [comment]
> https://github.com/PaddlePaddle/X2Paddle/blob/master/tensorflow2fluid/vgg_translate_tutorial.ipynb
> 这个是官方示例

是的，可跳过前面的步骤，直接进行转换

**Comment by jiangjiajun** [comment]
此外目前tf2fluid暂只支持CV类的模型，NLP模型不支持
