### ISSUE TITLE
分布式pserver模式增量训练load参数错误

### ISSUE THREAD

**Issue by lexy0093** [PaddlePaddle/Paddle#19013]
按照官方文档进行增量训练：
https://www.paddlepaddle.org.cn/documentation/docs/zh/1.5/user_guides/howto/training/save_load_variables.html
pserver load模型参数，trainer不用load

错误信息：

get_pserver_program() is deprecated, call get_pserver_programs() to get pserver main and startup in a single call.
Traceback (most recent call last):
  File "train_online_20190805_pserver.py", line 329, in <module>
    mcdnn_op.train()
  File "train_online_20190805_pserver.py", line 299, in train
    fluid.io.load_persistables(exe, self.init_model_path, pserver_startup)
  File "/home/work/xxx/fluid1.5Env/lib/python2.7/site-packages/paddle/fluid/io.py", line 742, in load_persistables
    filename=filename)
  File "/home/work/xxx/fluid1.5Env/lib/python2.7/site-packages/paddle/fluid/io.py", line 608, in load_vars
    filename=filename)
  File "/home/work/xxx/fluid1.5Env/lib/python2.7/site-packages/paddle/fluid/io.py", line 623, in load_vars
    new_var = _clone_var_in_block_(load_block, each_var)
  File "/home/work/xxx/fluid1.5Env/lib/python2.7/site-packages/paddle/fluid/io.py", line 94, in _clone_var_in_block_
    lod_level=var.lod_level,
  File "/home/work/xxx/fluid1.5Env/lib/python2.7/site-packages/paddle/fluid/framework.py", line 648, in lod_level
    return self.desc.lod_level()
paddle.fluid.core_avx.EnforceNotMet: Getting 'lod_level' is not supported by the type of var embedding_0.w_0@GRAD.block1. at [/paddle/paddle/fluid/framework/var_desc.cc:173]
PaddlePaddle Call Stacks:
0       0x7fd0654e2b68p void paddle::platform::EnforceNotMet::Init<std::string>(std::string, char const*, int) + 360
1       0x7fd065645b26p paddle::framework::VarDesc::GetLoDLevel() const + 182
2       0x7fd06558610fp
3       0x7fd065511c76p
4             0x49c58bp PyEval_EvalFrameEx + 24795
5             0x49d93ep PyEval_EvalCodeEx + 2190
6             0x4fe241p
7             0x41a753p PyObject_Call + 83
8             0x41d8ecp PyObject_CallFunction + 172
9             0x44d7abp _PyObject_GenericGetAttrWithDict + 379
10            0x498e2bp PyEval_EvalFrameEx + 10619
11            0x49d93ep PyEval_EvalCodeEx + 2190
12            0x49baeap PyEval_EvalFrameEx + 22074
13            0x49d93ep PyEval_EvalCodeEx + 2190
14            0x49baeap PyEval_EvalFrameEx + 22074
15            0x49d93ep PyEval_EvalCodeEx + 2190
16            0x49baeap PyEval_EvalFrameEx + 22074
17            0x49d93ep PyEval_EvalCodeEx + 2190
18            0x49baeap PyEval_EvalFrameEx + 22074
19            0x49d93ep PyEval_EvalCodeEx + 2190
20            0x49baeap PyEval_EvalFrameEx + 22074
21            0x49d93ep PyEval_EvalCodeEx + 2190
22            0x49da52p PyEval_EvalCode + 50
23            0x4bd2f0p PyRun_FileExFlags + 176
24            0x4bd4bcp PyRun_SimpleFileExFlags + 220
25            0x41608cp Py_Main + 3164
26        0x318ae1ecddp __libc_start_main + 253
27            0x415019p

有参考 #15154 更改函数自行load，未报错，在paddle-cloud上进行训练后发现test set 的loss下降不正常

**Comment by wangguibao** [comment]
用户pserver端load参数代码：
![3](https://user-images.githubusercontent.com/1445888/62470790-c3a41580-b7cd-11e9-8e8d-e236d6ac6ab2.PNG)

**Comment by wangguibao** [comment]
向 @seiriosPlus 老师请教，用户的load参数代码修改2个地方：
1
```
t.transpile(trainer_id, pservers=pserver_endpoitns, trainers=trainers, current_endpoint=current_endpoint)
```
这里增加一个current_endpoint = current_endpoint参数
2. 
```
fluid.io.load_persistables(exe, self.init_model_path, pserver_prog)
```
最后一个参数是pserver_prog不是pserver_startup (官网文档有误，已经在修)

**Comment by wangguibao** [comment]
用户反馈，用上述方式修改pserver load参数的代码，可以正常工作。
该issue关闭
