### ISSUE TITLE
模型压缩时 传入Compressor,运行到eval_program报告显存溢出

### ISSUE THREAD

**Issue by Hsintao** [PaddlePaddle/Paddle#19019]
train_program跑完进行eval  又分配一倍的显存
报错信息如下：
2019-08-05 11:41:41,732-INFO: Running evaluation
INFO:paddle.fluid.contrib.slim.core.compressor:Running evaluation
W0805 11:41:45.252403 28074 system_allocator.cc:121] Cannot malloc 9604.77 MB GPU memory. Please shrink FLAGS_fraction_of_gpu_memory_to_use or FLAGS_initial_gpu_memory_in_mb or FLAGS_reallocate_gpu_memory_in_mbenvironment variable to a lower value. Current FLAGS_fraction_of_gpu_memory_to_use value is 0.92. Current FLAGS_initial_gpu_memory_in_mb value is 0. Current FLAGS_reallocate_gpu_memory_in_mb value is 0
F0805 11:41:45.252899 28074 legacy_allocator.cc:201] Cannot allocate 351.562500MB in GPU 0, available 731.562500MBtotal 11523260416GpuMinChunkSize 256.000000BGpuMaxChunkSize 9.379657GBGPU memory used: 8.956496GB
请问怎么解决

**Comment by vincentXiyu** [comment]
我也遇到这个情况，可以尝试把eval时的batch size调比较小，可能会管用。我这边貌似可以跑通，不太确定是不是普遍可以适用。
