### ISSUE TITLE
fluid 1.5.1  提交paddlecloud作业， PaddleCloudRoleMaker | UserDefinedRoleMaker失败

### ISSUE THREAD

**Issue by sshilei** [PaddlePaddle/Paddle#19022]
![image](https://user-images.githubusercontent.com/18701471/62506866-daca1e00-b834-11e9-8de1-f3c7ade583c3.png)

PaddleCloudRoleMaker() endpoints: 10.104.66.32:30000

Traceback (most recent call last):

  File "frame/core/paddlecloud_cpu_trainer.py", line 142, in <module>

    ret = trainer.start(sys.argv)

  File "/root/paddlejob/workspace/env_run/frame/core/base_trainer.py", line 367, in start

    self.set_optimizer(FLAGS, net_output)

  File "frame/core/paddlecloud_cpu_trainer.py", line 82, in set_optimizer

    sgd_optimizer.minimize(net_output['loss'], fluid.default_startup_program())

  File "/usr/local/lib/python2.7/site-packages/paddle/fluid/incubate/fleet/collective/__init__.py", line 125, in minimize

    current_endpoint = fleet.worker_endpoints()[trainer_id]

IndexError: list index out of range

**Comment by gavin1332** [comment]
is it a CPU or GPU task?
could you share your submit script?

**Comment by sshilei** [comment]
CPU, 集群 。 能帮忙提供一下提交paddlecloud分布式任务的例子吗？最好提供一个1.5.1可用的，我找到一些都是基于开发版的，谢谢。

**Comment by sshilei** [comment]
@gavin1332

**Comment by sshilei** [comment]
改成UserDefinedRoleMaker会报另外一个错误
![image](https://user-images.githubusercontent.com/18701471/62514954-75d1f080-b853-11e9-975f-6204f5658d1d.png)

**Comment by sshilei** [comment]
80         sgd_optimizer = fluid.optimizer.SGD(learning_rate=FLAGS.base_lr)
 81
 82         role = os.getenv("TRAINING_ROLE")
 83         trainer_id = int(os.getenv("PADDLE_TRAINER_ID"))
 84         num_trainers = int(os.getenv("PADDLE_TRAINERS_NUM"))
 85         #trainer_endpoints = os.getenv("PADDLE_TRAINER_ENDPOINTS")
 86         #trainer_endpoints = trainer_endpoints.split(',')
 87         port = os.getenv("PADDLE_PORT", "6174")
 88         pserver_ips = os.getenv("PADDLE_PSERVERS")  # ip,ip...
 89         eplist = []
 90         for ip in pserver_ips.split(","):
 91             eplist.append(':'.join([ip, port]))
 92         pserver_endpoints = ",".join(eplist)  # ip:port,ip:port...
 93
 94
 95         if role == "TRAINER":
 96             role_maker = UserDefinedRoleMaker(current_id=trainer_id, role=Role.WORKER, worker_num=num_trainers, server_endpoints=eplist)
 97             fleet.init(role_maker)
 98             sgd_optimizer = fleet.distributed_optimizer(sgd_optimizer)
 99             sgd_optimizer.minimize(net_output['loss'], fluid.default_startup_program())
100         elif role == "PSERVER":
101             role_maker = UserDefinedRoleMaker(current_id=trainer_id, role=Role.SERVER, worker_num=num_trainers, server_endpoints=eplist)
102             fleet.init(role_maker)

**Comment by sshilei** [comment]
` 80         sgd_optimizer = fluid.optimizer.SGD(learning_rate=FLAGS.base_lr)
 81
 82         role = os.getenv("TRAINING_ROLE")
 83         trainer_id = int(os.getenv("PADDLE_TRAINER_ID"))
 84         num_trainers = int(os.getenv("PADDLE_TRAINERS_NUM"))
 85         #trainer_endpoints = os.getenv("PADDLE_TRAINER_ENDPOINTS")
 86         #trainer_endpoints = trainer_endpoints.split(',')
 87         port = os.getenv("PADDLE_PORT", "6174")
 88         pserver_ips = os.getenv("PADDLE_PSERVERS")  # ip,ip...
 89         eplist = []
 90         for ip in pserver_ips.split(","):
 91             eplist.append(':'.join([ip, port]))
 92         pserver_endpoints = ",".join(eplist)  # ip:port,ip:port...
 93
 94
 95         if role == "TRAINER":
 96             role_maker = UserDefinedRoleMaker(current_id=trainer_id, role=Role.WORKER, worker_num=num_trainers, server_endpoints=eplist)
 97             fleet.init(role_maker)
 98             sgd_optimizer = fleet.distributed_optimizer(sgd_optimizer)
 99             sgd_optimizer.minimize(net_output['loss'], fluid.default_startup_program())
100         elif role == "PSERVER":
101             role_maker = UserDefinedRoleMaker(current_id=trainer_id, role=Role.SERVER, worker_num=num_trainers, server_endpoints=eplist)
102             fleet.init(role_maker)`

**Comment by sshilei** [comment]
![image](https://user-images.githubusercontent.com/18701471/62515156-08728f80-b854-11e9-988b-8498e1f1484d.png)

**Comment by seiriosPlus** [comment]
1. 使用的是 transpiler模式还是pslib模式
2. 可以基于develop进行测试和效果验证

**Comment by guru4elephant** [comment]
@sshilei  请使用PaddleCloudRoleMaker，有问题到飞桨Fleet推广群提问，1481295
