### ISSUE TITLE
模型结构里面出现“常数乘以op”的情况导致训练速度变慢

### ISSUE THREAD

**Issue by kebinC** [PaddlePaddle/Paddle#19023]
version1:
```
node_list.append(w * nodes[i])
```
version2:
```
var_w = fluid.layers.create_global_var(
    shape=[scale, scale],
    value=w,
    dtype='float32',
    persistable=True)
node_list.append(
    fluid.layers.elementwise_mul(x=nodes[i], y=var_w))

```

version1速度要比version2 慢很多

**Comment by gavin1332** [comment]
how about
```
var_w = fluid.layers.create_global_var(
    shape=[1, 1],
    value=w,
    dtype='float32',
    persistable=True)

node_list.append(
    fluid.layers.elementwise_mul(x=nodes[i], y=var_w))
```

**Comment by kebinC** [comment]
> how about
> 
> ```
> var_w = fluid.layers.create_global_var(
>     shape=[1, 1],
>     value=w,
>     dtype='float32',
>     persistable=True)
> 
> node_list.append(
>     fluid.layers.elementwise_mul(x=nodes[i], y=var_w))
> ```
shape为 1x1 ， 没办法做broadcast，node[i]的shape（-1， C，scale， scale）

**Comment by gavin1332** [comment]
收到，我反馈一下这个问题
