### ISSUE TITLE
关于paddlehub中ernie和bert中文模型无缝切换的问题

### ISSUE THREAD

**Issue by luzm3** [PaddlePaddle/Paddle#19026]
先贴上官方README的代码
`# 更换name参数即可无缝切换BERT中文模型, 代码示例如下                                                     
  module = hub.Module(name="bert_chinese_L-12_H-768_A-12")`
按README的说法，只需要切换那么即可，但是我在ernie能跑通的情况下，把name更换为中文的bert，却遭遇了错误。

**Comment by luzm3** [comment]
[https://github.com/PaddlePaddle/PaddleHub/tree/release/v1.0.0/demo/sequence-labeling](url)
这是README的链接

**Comment by luzm3** [comment]
补个错误图
![image](https://user-images.githubusercontent.com/45001329/62509320-562fcd80-b83d-11e9-99ed-5294504a41a1.png)

**Comment by luzm3** [comment]
这是我的代码
![image](https://user-images.githubusercontent.com/45001329/62509366-795a7d00-b83d-11e9-833b-585e78654840.png)

**Comment by Steffy-zxf** [comment]
感谢反馈，这是由于 bert module 创建时和当前运行时paddle版本不一致的问题导致的。你可以尝试将paddle降级至 1.4.1。这个bug，我们正在修复。

**Comment by luzm3** [comment]
> 感谢反馈，这是由于 bert module 创建时和当前运行时paddle版本不一致的问题导致的。你可以尝试将paddle降级至 1.4.1。这个bug，我们正在修复。

好的，感谢！！

**Comment by luzm3** [comment]
把版本换至1.4.1，问题已解决
