### ISSUE TITLE
paddle.fluid.core_avx.LoDTensor' object has no attribute 'name'

### ISSUE THREAD

**Issue by Cristhine** [PaddlePaddle/Paddle#19024]
预测时候出现的，预测多张图片时第二张图片出现问题；
Traceback (most recent call last):
  File "infer.py", line 155, in <module>
    infer()
  File "infer.py", line 110, in infer
    fetch_list=[outputs[0].name,outputs[1].name],
AttributeError: 'paddle.fluid.core_avx.LoDTensor' object has no attribute 'name'

代码如下：
with open('./output/test_sample_100_preprocess_data.txt', 'w') as f:
 94         for idx, image_name in enumerate(image_names):
 95             print(idx)
 96             infer_reader = reader.infer(input_size, os.path.join(cfg.image_path, image    _name))
 97             data = next(infer_reader())
 98             #for a in range(3):
 99             #    for b in range(608):
100             #        for c in range(608):
101             #            f.write(str(data[0][0][a][b][c]) + ' ')
102             #f.write('\n')
103
104             #real_img = cv2.imread('./test_image/' + image_name)
105             #height, width, _ = real_img.shape
106
107             im_shape = data[0][1]
108             print('im_shape',im_shape)
109             outputs = exe.run(
110                 fetch_list=[outputs[0].name,outputs[1].name],
111                 #fetch_list=[v[0].name for v in fetch_list],
112                 #fetch_list=[outputs[0].name, outputs[1].name, outputs[2].name, output    s[3].name, outputs[4].name, outputs[5].name, outputs[6].name],
113                 feed=feeder.feed(data),
114                 return_numpy=False)
115             bboxes = np.array(outputs[0]) # modified by wzg
116             forward_features = np.array(outputs[1])

**Comment by gavin1332** [comment]
`outputs[0]` 是Variable还是LodTensor

**Comment by Cristhine** [comment]
> `outputs[0]` 是Variable还是LodTensor

是LodTensor  打印了一下到第二张图就是这样显示('outputs', [<paddle.fluid.core_avx.LoDTensor object at 0x7fd7abcad3e8>, <paddle.fluid.core_avx.LoDTensor object at 0x7fd7abcad308>])
第一张图显示很正常，是这样的('outputs', [name: "multiclass_nms.tmp_0"
type {
  type: LOD_TENSOR
  lod_tensor {
    tensor {
      data_type: FP32
      dims: 22743
      dims: 6
    }
  }
}
persistable: false
, name: "softmax_0.tmp_0"
type {
  type: LOD_TENSOR
  lod_tensor {
    tensor {
      data_type: FP32
      dims: 22743
      dims: 4
    }
    lod_level: 0
  }
}
persistable: false
