### ISSUE TITLE
关于提供C#接口的建议

### ISSUE THREAD

**Issue by 18628271760** [PaddlePaddle/Paddle#19039]
paddle团队 你好，
我是paddlepaddle学习者，对paddlepaddle平台很看好。但是在对公司领导和其它业务部门推荐时，大家反馈paddlepaddle平台文档不全，并且对其它语言的接口较少。我公司涉及对视频图像处理的业务较多，对C#/C++接口有强烈需求。建议在1.6版本推出C#/C++接口，以便加快项目落地。

**Comment by gavin1332** [comment]
你好，paddle原生使用c++开发，对c++非常友好，而且现在有经过多项业务验证的快速c++预测库，这也是相对于国内其他平台的优势，这块你可以放心。
不过据我所知，短期内不会提供c#接口的支持。


> paddlepaddle平台文档不全

至于文档不全问题，可否给一些论据？或者给我们一些建议。因为我们文档一直在建设，持续在完善，经过多个版本的迭代，很多已知问题已经修复。

**Comment by gavin1332** [comment]
> 短期内不会提供c#接口的支持

不过paddle serving**未来**的定位是语言无关的，提交http请求即可。可以关注一下

**Comment by 18628271760** [comment]
云模式和服务器模式并不是适应所有环境，不是万能的。目前这边的需求是能集成到 .net core(C#)平台。  .net core微软最新的后台框架，请慎重考虑对C#的支持。

**Comment by gavin1332** [comment]
OK，我反馈一下这个需求。感谢您的建议！
