### ISSUE TITLE
文本分类，指定文本长度之后如何进行lstm编码

### ISSUE THREAD

**Issue by yuanquan123** [PaddlePaddle/Paddle#19038]
cc = fluid.layers.data(name='cc', shape=[-1, 64, 1], dtype='int64', lod_level=1)
cc_emb = fluid.layers.embedding(
            size=[word_dict_len, 96],
            input=cc,
            param_attr=fluid.ParamAttr(name='w_emb', trainable=True))
forward_hidden_state = fluid.layers.dynamic_gru(input=cc_emb, size=32)
如上代码，我将文本数据padding的固定长度，然后进行embedding，这时的shape是[-1, 64, 96]，然后通过gru编码后直接变成[-1, 32]。

**Comment by gavin1332** [comment]
不用显示指定长度，输入数据保障就行，dynamic_gru操作的是lodtensor，这个数据结构在表示时是二维向量而不是三维向量

**Comment by yuanquan123** [comment]
可是如果我不指定长度，我想将gru编码过后的向量进行self-attention的计算的话，应该怎么实现呢。

**Comment by gavin1332** [comment]
sequence_pad方法了解一下

**Comment by gavin1332** [comment]
https://www.paddlepaddle.org.cn/documentation/docs/zh/1.5/api_cn/layers_cn/nn_cn.html#sequence-pad
