### ISSUE TITLE
分布式设置参数trainable=False，训练结束参数内容发生改变

### ISSUE THREAD

**Issue by Yukizzz** [PaddlePaddle/Paddle#19042]
设置了某个参数trainable=False，但是load init_model之后，训练完保存下来的参数和我load的那个init_model里面的参数不一样，

od -j 28 -f init_model/fc_5.w_0  | head -10
0000034      0.58095753      0.39794534       1.0153178     -0.80564636
0000054       0.8599262       0.2186901    -0.029506208       -1.250106
0000074       -2.276074      -1.8533763      0.43813547      -1.8273996
0000114       0.7638257      0.83346057      -3.1954935      -1.0416312
0000134      -1.1343194      -0.3993221      -2.7130916      -0.3889992
0000154      0.55558234      0.04183614      -1.4330114       1.4115933
0000174      -0.8441208      -0.7790442        0.764243     -0.12310181
0000214      -1.8059375     -0.22318181     -0.77045727      -0.9803658
0000234     -0.40435293     -0.15675284      0.36384565     -0.38523918
0000254       0.5259551      0.40345085      -0.9756449      0.50179625
 od -j 28 -f output/pass-1/fc_5.w_0 | head -10
0000034     -0.06646662      0.11514573    0.0010066032     -0.09367473
0000054   -0.0143265575      0.11739071     -0.02171868   -0.0011521131
0000074     0.112192735      0.13971393      0.07211788     -0.13586007
0000114      0.10148643     -0.12789723     -0.09461781     0.083902925
0000134     -0.15304434     0.057815686     -0.06595666     -0.06934277
0000154    -0.016825661      0.12105726    -0.008254588     -0.10857653
0000174     -0.10800059      0.13651623      0.03450185      0.09174639
0000214     0.012023747     -0.13122742    -0.098293245     -0.05149679
0000234      0.12477304    -0.070680074      0.03537664      0.06489307
0000254     -0.13795781     -0.11744906    -0.039152086      -0.1287903

**Comment by Yukizzz** [comment]
只load参数不训练直接保存的话，设置trainable=False的，参数会变。但是走默认配置，也就是 trainable=True的，参数不会变，
 od -j 28 -f output/pass-2/fc_8.w_0 | head -10  
0000034     -0.67836773     -0.09785643      0.28790843      0.29802382
0000054       0.9142786       1.1055115       2.4652376       -1.459549
0000074       0.5780221       0.7414768       1.5961243       1.2324945
0000114       1.2719272       1.0017662    -0.071284086      -0.2991104
0000134      0.24140625      0.18678504      -0.9043444       0.8021302
0000154      -0.8874393      0.32028443      -0.6627139      0.90538555
0000174       0.9287759       -1.295629       1.4340291    0.0074852374
0000214       0.5407163     -0.91169196     -0.41713968       1.3773816
0000234      0.44697392      0.62320554      -1.4918269      0.22796409
0000254      -1.0872842      -0.5808825       1.0583599     -0.58986527
 od -j 28 -f init_model/fc_8.w_0  | head -10    
0000034      -0.6779204     -0.09794321      0.28775564        0.297877
0000054       0.9142955       1.1057999       2.4648485       -1.459678
0000074      0.57800514        0.741537       1.5962831        1.232453
0000114       1.2716223       1.0016235    -0.071181275      -0.2991213
0000134      0.24144445      0.18663892     -0.90449256        0.802256
0000154       -0.887257       0.3201515      -0.6628245      0.90532005
0000174       0.9287285      -1.2956766       1.4343172    0.0071700145
0000214       0.5405678      -0.9114445      -0.4170221       1.3774531
0000234      0.44644064       0.6232949      -1.4919835      0.22767738
0000254      -1.0869431     -0.58091754       1.0586679       -0.589756

**Comment by gavin1332** [comment]
请提供一下最小可复现配置

**Comment by Yukizzz** [comment]
已在hi上提供～

**Comment by Yukizzz** [comment]
目前发现，

1. cpu分布式跑的话，

- trainable设置为false，load init model之后，无论训练与否，参数内容都**会**改变。（**不符合预期**）

- trainable设置为true的，不训练参数内容不会变，训练才会变。（符合预期）

2. 单机跑的话，

- trainable设置为false，load init model之后，无论训练与否，参数内容都**不会**改变。（**符合预期**）

- trainable设置为true的，不训练参数内容不会变，训练才会变。（符合预期）

因此怀疑是分布式的问题，辛苦同学帮忙继续看下～

**Comment by seiriosPlus** [comment]
分布式load参数在pserver端， 因此不会load不参与优化的参数， 会修复此问题。

解决方法：
1. 将不需要参与训练的参数的 learning设置为 0。
2. 在trainer端独立load trainable=False的参数。
