### ISSUE TITLE
调用fluid.io.save_inference_model时，保存目录只有__model__文件，__params__文件不存在，并报段错误。

### ISSUE THREAD

**Issue by jiangbojian** [PaddlePaddle/Paddle#19044]
paddle1.5  +  python2.7  +  GPU(v100 16G)
有过同学提出过类似的问题
https://github.com/PaddlePaddle/Paddle/issues/18250
解决方法是paddle从1.3.0升级至1.3.1就可以解决。

我使用的paddle版本是1.5，也出了这个问题，是什么原因呢？

**Comment by Xreki** [comment]
https://github.com/PaddlePaddle/Paddle/issues/18250 中是某个op在保存时有bug。你使用的是哪个模型？也不排除其他op出现bug的可能。

**Comment by jiangbojian** [comment]
> #18250 中是某个op在保存时有bug。你使用的是哪个模型？也不排除其他op出现bug的可能。

模型是transformer机器翻译模型，需要注意的是：为了灵活，将要beam search这一整个op拆解成了多个op组装的形式实现。如果使用paddlepaddle提供的beam search这个op，在保存时不会出bug

**Comment by Xreki** [comment]
> 将要beam search这一整个op拆解成了多个op组装的形式实现。

怎么拆的，能否将修改后的代码贴一下。

**Comment by jiangbojian** [comment]
> > 将要beam search这一整个op拆解成了多个op组装的形式实现。
> 
> 怎么拆的，能否将修改后的代码贴一下。

代码可以贴，但是比较多，可以提供调试的环境（机器，运行环境），这样更方便一些。近期能否有排期解决这个问题呢？如果排期比较靠后，需要下一版本paddle才能解决的话，我们就再替换回beam search这个op（但与其他部门，工作量会很大）。

**Comment by Xreki** [comment]
> 代码可以贴，但是比较多

如果你只是替换了`beam_search`这个op，可以只贴下修改的这部分哈，我尝试定位下错误。

> 近期能否有排期解决这个问题呢？

得先确定具体是什么问题，再看是否好解决呀。
