### ISSUE TITLE
如何比较两个__model__文件

### ISSUE THREAD

**Issue by imistyrain** [PaddlePaddle/Paddle#19043]
从别的框架转过来一个模型，是fluid那种合成两个文件存储的，有1M左右。将其转换成每个参数单独存的文件，一共有300多个文件，大小总共有2M。而在此基础上再转回至两个文件的模型时大小变成了1.6M，经过对比发现，params文件大小是一致的，只是__model__文件由原来的100多K变成了600多K，有什么方法能对__model__的结构进行解析吗？

**Comment by gavin1332** [comment]
解析的目的是，我理解params文件一致的话预测结果应该也一致吧？


> 从别的框架转过来一个模型，是fluid那种合成两个文件存储的，有1M左右

这个**存储**又是如何操作的呢？跟后边的**转回至**操作一致吗？

**Comment by imistyrain** [comment]
可通过写文件的方式直接写，__model__变大的原因是存储了op_statck信息。
```
with open("model.txt","w")as f:
        f.write(str(test_program))
```
