### ISSUE TITLE
使用PaddleSlim进行uniform剪裁mobilenet v2模型，训练loss出现nan

### ISSUE THREAD

**Issue by kk12333** [PaddlePaddle/Paddle#19049]
1）PaddlePaddle版本：paddle-fluid-v1.4.1
    2）CPU：无
    3）GPU：cuda8.0，cudnn7.5
    4）系统环境：CentOS release 6.10
- 训练信息
    1）单机4卡 P40
    2）显存：单P40卡显存16G左右
    3）op情况：官网mobilenet v2结构涉及的op
- 问题描述：用PaddleSlim官网uniform pruning的demo，修改为mobilenet v2模型，并修改对应的.yaml配置，直接启动剪裁，finetune出现loss nan

剪裁配置如下：
![image](https://user-images.githubusercontent.com/17851313/62588380-21348100-b8f8-11e9-9c4c-57962f9b29b4.png)

日志：
![image](https://user-images.githubusercontent.com/17851313/62588367-124dce80-b8f8-11e9-991e-27ad79e63e94.png)

**Comment by Xreki** [comment]
你好，尝试过常规的处理nan的方法吗，比如减小`learnin_rate`之类的。

另外，issue能，能贴文字的，建议尽量别贴图哈~

**Comment by kk12333** [comment]
> 你好，尝试过常规的处理nan的方法吗，比如减小`learnin_rate`之类的。
> 
> 另外，issue能，能贴文字的，建议尽量别贴图哈~

调小学率试过了，还是会nan。可以直接看paddlecloud的控制台：http://10.90.251.16:8001/webssh/ai00/c0a1f165-6279-5320-b9e7-e0218c7a87f5/10.255.118.25/49587792.job-0bb5d51472ae75ef-trainer/e3a7009a-5f55-5ca4-841a-de36673a4e38/running/
