### ISSUE TITLE
相同参数多次save模型后infrence的结果不一样

### ISSUE THREAD

**Issue by liuguolian** [PaddlePaddle/Paddle#19045]
跑ernie开源的那个模型代码，代码里train的时候是用的save_persistables保存模型训练变量，inference的时候先load的训练保存的params后，执行save_inference_model保存模型再执行load_inference_model做预测，发现每次save_inference_model的模型用来预测结果都不一样，现在不知道哪次是对的哪次是错的。。

**Comment by gavin1332** [comment]
建议使用save_persistables保存模型参数

**Comment by DDDivano** [comment]
可以看一下这个文档，https://www.paddlepaddle.org.cn/documentation/docs/zh/1.5/api_cn/fluid_cn.html#program。
load起来后，如果没有使用clone函数，执行的话会计算反向，执行一次（inference）后再save是保存的执行反向后的结果，实际这个save的模型和之前的param是有变化的，可能是由于此原因导致你这个问题产生。
