### ISSUE TITLE
一处小BUG？

### ISSUE THREAD

**Issue by Hsintao** [PaddlePaddle/Paddle#19047]
paddle/fluid/contrib/slim/core/compressor.py中
142 行 with open(file_name) as context_file:
改为 with open(file_name,'rb') as context_file:

不改我这边会报错UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 0
无法加载checkpoint

**Comment by gavin1332** [comment]
感谢反馈

**Comment by gavin1332** [comment]
https://github.com/PaddlePaddle/Paddle/blob/e5b9753a1895e7221a05e4d15787dd8b720eaad0/python/paddle/fluid/contrib/slim/core/compressor.py#L142

**Comment by gavin1332** [comment]
@wanghaoshuang 辛苦确认一下这个地方是否有问题

**Comment by wanghaoshuang** [comment]
是的，在某些编码环境下确实是个bug，我们会尽快修复。多谢反馈。
