### ISSUE TITLE
QAT INT8 MKL-DNN Mobilenet-v2 accuracy regression problem

### ISSUE THREAD

**Issue by bingyanghuang** [PaddlePaddle/Paddle#19059]
Reported from Baidu that when they reproduce the MKL-DNN Release 1.5 QAT results on their server CLX 6271 with latest commit, they found that mobilenet-v2 got 0.07% accuracy drop.
![image](https://user-images.githubusercontent.com/33643817/62608750-07645f80-b933-11e9-851d-4e11b5dbb488.png)
This issue is to track this problem. @Sand3r- Please add `intel` table on this issue. Thanks

**Comment by luotao1** [comment]
@wzzju @juncaipeng You can track this issue.

**Comment by bingyanghuang** [comment]
Based on the [QAT 1.0 doc](https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/fluid/contrib/slim/tests/QAT_mkldnn_int8_readme.md) , final accuracy diff for Mobilnet-v1 is acceptable and besides we are transferring to use QAT 2.0 for users. This issue can be closed.
