### ISSUE TITLE
Conv1D needed

### ISSUE THREAD

**Issue by kidozh** [PaddlePaddle/Paddle#19061]
欢迎您对PaddlePaddle提出建议，非常感谢您对PaddlePaddle的贡献！
在留下您的建议时，辛苦您同步提供如下信息：
- 版本、环境信息
1）PaddlePaddle版本：请提供您的PaddlePaddle版本号，例如1.5.1.post97
2）CPU/GPU：CUDA 9 CuDNN 9.2
3）系统环境：Windows 10

最近做信号，比较需要一维卷积，其他深度学习框架诸如TensorFlow, PyTorch和keras 都有一维卷积支持，搞不懂为什么paddle没有这个基本的层。

**Comment by Xreki** [comment]
很抱歉，我们由于人力原因，功能上支持的不够完整。我们会将您的需求转达，也欢迎您来贡献代码，:smile:
