### ISSUE TITLE
profiler 报错

### ISSUE THREAD

**Issue by zhengya01** [PaddlePaddle/Paddle#19068]
profiler功能在v100上没有报错，在p40上报错了

环境：
python：2.7.15
paddle：1.5.1
cuda：9
cudnn：7
gpu：P40
linux：CentOS release 6.3

执行命令：
跑模型PaddleNLP/language_model
python train.py --profile True --rnn_model static --log_path tmp_log_file --max_epoch 1 --data_path data/simple-examples/data/ --batch_size 8 --save_model_dir models_1 --use_gpu False --model_type test --use_py_reader True --parallel True

报错信息：
/paddle/paddle/fluid/platform/device_tracer.cc:414: error: function dynload::cuptiEnableCallback( 1, subscriber_, CUPTI_CB_DOMAIN_RUNTIME_API, cbid) failed with error CUPTI_ERROR_INVALID_PARAMETER.

**Comment by chengduoZH** [comment]
这是因为你环境里面没有装 cupti 工具。
