### ISSUE TITLE
paddle-cloud 40个节点并不比10个节点训练速度快

### ISSUE THREAD

**Issue by lexy0093** [PaddlePaddle/Paddle#19060]
如题，
同样的训练集，测试集
同样的网络结构
在paddle cloud上40个节点的训练速度竟然和10个节点差不多。
请问一下这是为什么呢

40节点日志：http://10.73.161.43:8910/fileview.html?type=logsdir&path=/&instance=0.app-user-20190807114200-66649--mcdnn-fluid-0807_paddlecloud
10节点日志：http://10.73.173.37:8910/fileview.html?type=logsdir&path=/&instance=0.app-user-20190805203101-64397--mcdnn-fluid-0802_paddlecloud

**Comment by ScoThunder** [comment]
这个我们也没办法看出来，mpi集群各个队列机器配置不一样，然后机器也不是独占的，会混布map reduce任务

**Comment by guru4elephant** [comment]
@lexy0093 同学请使用fleet API，你现在使用的是一种非常缓慢的训练方式，请加入飞桨Fleet推广群咨询如何更快的训练。群号1481295
