### ISSUE TITLE
咨询：Warning求解

### ISSUE THREAD

**Issue by lalala805** [PaddlePaddle/Paddle#19077]
模型采用了DynamicRNN, 训练时一直报warning，希望咨询下，这些warning具体指代什么，一般什么情况下会报这样的warning，谢谢。
（代码太多，不好复制，想先简单问下warning指代。）
W0808 19:34:25.880235 41151 while_op.cc:249] dynamic_rnn_input_array_1@GRAD is not found in cur_scope.
W0808 19:34:25.880790 41151 while_op.cc:249] dynamic_rnn_input_array_2@GRAD is not found in cur_scope.
W0808 19:34:25.880913 41151 while_op.cc:249] dynamic_rnn_input_array_0@GRAD is not found in cur_scope.
W0808 19:34:25.913822 41151 while_op.cc:249] dynamic_rnn_input_array_1@GRAD is not found in cur_scope.
W0808 19:34:25.914101 41151 while_op.cc:249] dynamic_rnn_input_array_2@GRAD is not found in cur_scope.
W0808 19:34:25.914186 41151 while_op.cc:249] dynamic_rnn_input_array_0@GRAD is not found in cur_scope.
W0808 19:34:25.949082 41151 while_op.cc:249] dynamic_rnn_input_array_1@GRAD is not found in cur_scope.
W0808 19:34:25.949365 41151 while_op.cc:249] dynamic_rnn_input_array_2@GRAD is not found in cur_scope.
W0808 19:34:25.949451 41151 while_op.cc:249] dynamic_rnn_input_array_0@GRAD is not found in cur_scope.
W0808 19:34:25.984117 41151 while_op.cc:249] dynamic_rnn_input_array_1@GRAD is not found in cur_scope.
W0808 19:34:25.984411 41151 while_op.cc:249] dynamic_rnn_input_array_2@GRAD is not found in cur_scope.
W0808 19:34:25.984467 41151 while_op.cc:249] dynamic_rnn_input_array_0@GRAD is not found in cur_scope.
W0808 19:34:26.161180 41151 while_op.cc:249] dynamic_rnn_input_array_1@GRAD is not found in cur_scope.

**Comment by shippingwang** [comment]
参考 [while op](https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/fluid/operators/controlflow/while_op.cc#L233)
这个 warning 是说某些op的输入是没有反向的

**Comment by lalala805** [comment]
弱问，什么情况下会导致op输入没有反向呢？
示例我看的不太懂，可否简单介绍下呢，谢谢。

**Comment by shippingwang** [comment]
是说某些op，它的输入没有反向，比如说求softmax loss时候的输入（image, label）label就是没有反向的
