### ISSUE TITLE
训练好的模型，在paddlecloud上进行分布式预测

### ISSUE THREAD

**Issue by minhozhou** [PaddlePaddle/Paddle#19073]
测试样本量较大，有5000万，二分类任务需要计算AUC，单机预测需要十几个小时，请问有没有相应的demo？各个节点单独预测对应的样本的话，不知道全局AUC该如何计算。

**Comment by seiriosPlus** [comment]
方法一：
基本做法： 每个节点分别预测，每个节点都生成一份对应的[Predict, Label]的组合的文件，将文件汇总到一个节点，基于这些汇总的文件采用单节点来独立计算一次AUC。

1. PaddleCloud可以申请集群任务， 通过`train_data`的配置将待测试的数据分成N份。
2. 每个节点都会起一个PS,一个TR，注意做好判断。(可以直接在PS中做预测， TR hang住就可以)
3. 每个节点根据自己的`train_data`分配到的预测数据，进行独立预测， 计算出[Predict, Label]写入文件。
4. 将每个节点计算得出的文件汇总到0号节点(通过HDFS/HttpServer等)。
5. 可以先采用https://github.com/seiriosPlus/Paddle/blob/erp/oppo-supported/python/paddle/fluid/contrib/utils/auc.py进行本地auc预测(后续会移入PaddleRepo)， 可得全局AUC结果。
