### ISSUE TITLE
What's the meaning of op_callstack?

### ISSUE THREAD

**Issue by imistyrain** [PaddlePaddle/Paddle#19076]
对比fluid模型差异发现__model__里有个op_callstack里面填了很多值，导致模型明显变大，有什么方法能在保存的时候把这些东西去掉吗？

**Comment by shippingwang** [comment]
参考 https://github.com/PaddlePaddle/Paddle/issues/17576#issuecomment-495050960， 对模型没有影响，不需要处理

**Comment by imistyrain** [comment]
但是文件大了好几倍，我们对大小很敏感，怎么去掉这些信息呢？

**Comment by shippingwang** [comment]
> 但是文件大了好几倍，我们对大小很敏感，怎么去掉这些信息呢？

大好几倍么？不会吧？这个我来反馈一下吧
