### ISSUE TITLE
layers.slice不支持传入动态参数

### ISSUE THREAD

**Issue by jiangbojian** [PaddlePaddle/Paddle#19086]
环境：
paddlepaddle1.5
GPU(v100,16G)
python2.7

问题描述：
使用layers.slice这个op时，不支持传入动态的参数
程序截图
![image](https://user-images.githubusercontent.com/6761054/62755021-db68eb80-baa4-11e9-9016-7dcb1cf10cdd.png)
运行截图
![image](https://user-images.githubusercontent.com/6761054/62755167-79f54c80-baa5-11e9-9e63-403998e28ecd.png)

**Comment by tensor-tang** [comment]
感谢反馈，我们会尽快处理，并评估是否支持。

**Comment by tensor-tang** [comment]
我们会排期支持该功能，感谢反馈。
