### ISSUE TITLE
SetFeedVariable出core

### ISSUE THREAD

**Issue by xiaoyao4573** [PaddlePaddle/Paddle#19092]
1）PaddlePaddle版本：1.5
2）预测库来源：CONFIGS('baidu/paddlepaddle/paddle/@expt-v1.5.0') 
a)当input的tensor的size和实际使用的size不一致时出现以下core：
terminate called after throwing an instance of 'std::runtime_error'
  what():  Exception encounter.
Exception: baidu/paddlepaddle/paddle/paddle/fluid/memory/detail/meta_cache.cc:33 Assertion `desc->check_guards()` failed.
b)当input的tensor的size和实际使用的size一致时正常运行。

**Comment by tensor-tang** [comment]
> 当input的tensor的size和实际使用的size不一致时

请问什么是指实际使用时候的tensor size，是说实际使用的和设置的size不一样吗？

**Comment by xiaoyao4573** [comment]
是的

**Comment by luotao1** [comment]
`PADDLE_ASSERT`的报错信息不够明确，会尽快换成`PADDLE_ENFORCE_XXX`接口来进行报错的。@tensor-tang @Xreki
