### ISSUE TITLE
fluid.layers.softmax_with_cross_entropy函数使用报got an unexpected keyword argument 'return_softmax'

### ISSUE THREAD

**Issue by liuguolian** [PaddlePaddle/Paddle#19097]
gpu环境，代码中使用fluid.layers.softmax_with_cross_entropy函数，
运行环境：http://yq01-sys-hic-p40-0236.yq01.baidu.com:8388/v1/slurmjobs/121278/workspace
报错如下：
File "run_classifier.py", line 114, in main
is_regression=args.is_regression)
File "/home/slurm/job/tmp/job-121278/finetune/classifier.py", line 104, in create_model
logits=logits, label=labels, return_softmax=True)
TypeError: softmax_with_cross_entropy() got an unexpected keyword argument 'return_softmax'

**Comment by tensor-tang** [comment]
抱歉回复晚了。
这个应该是您代码里面写法有误吧，或者是typo
