### ISSUE TITLE
请教一个问题，batchnorm api参数fuse_with_relu 和 act=relu有啥区别？

### ISSUE THREAD

**Issue by DDDivano** [PaddlePaddle/Paddle#19096]
RT

**Comment by tensor-tang** [comment]
抱歉回复晚了

fuse_with_relu侧重会把relu 融合到Batchnorm里面，并且这个选项是在MKLDNN打开的时候才会有效。
act=relu 只是relu是act的一个选项，这种情况下，两者的逻辑是等效的。


给您造成了困扰，在此表示抱歉，这里我们会对文档和API进行完善。

祝好。
