### ISSUE TITLE
在多program条件下，set(): incompatible function arguments. 的错误

### ISSUE THREAD

**Issue by 18628271760** [PaddlePaddle/Paddle#19102]
paddle团队，
我在进行多program尝试时，触发了set(): incompatible function arguments. 的错误。源代码与数据以zip方式上传，请帮忙排查。感谢。

[PaddlePaddle.zip](https://github.com/PaddlePaddle/Paddle/files/3485649/PaddlePaddle.zip)

**Comment by tensor-tang** [comment]
您好，您可以查看我们的[ParallelExecutor](https://www.paddlepaddle.org.cn/documentation/docs/zh/1.5/api_cn/fluid_cn.html#parallelexecutor)例子，其会充分使用机器资源，不需要您自己创建多program。

祝好。

**Comment by 18628271760** [comment]
paddle团队你好，
创建自定义program为以后业务需求，请帮忙查证问题原因，感谢。

**Comment by 18628271760** [comment]
已经解决，多program是可行的，feeder = fluid.DataFeeder(place=cpu, feed_list=[x, label], program=trainOCRProg) 设置place错误引起。
