### ISSUE TITLE
feed data 出错，reorder_datareorder.append(each[self.feeding[name]]) 

### ISSUE THREAD

**Issue by billiecas** [PaddlePaddle/Paddle#19126]
在paddle V2 版本集群训练时，出现如下错误：
 exit 1
Mon Aug 12 10:16:14 2019[1,4]<stderr>:Traceback (most recent call last):
Mon Aug 12 10:16:14 2019[1,4]<stderr>:  File "conf/trainer_config.conf", line 225, in <module>
Mon Aug 12 10:16:14 2019[1,4]<stderr>:    train(1, id_dict, fea_sections, old_model_path)
Mon Aug 12 10:16:14 2019[1,4]<stderr>:  File "conf/trainer_config.conf", line 191, in train
Mon Aug 12 10:16:14 2019[1,4]<stderr>:    num_passes = num_passes)
Mon Aug 12 10:16:14 2019[1,4]<stderr>:  File "/home/disk1/task_data/history/20190812/4.app-user-20190812095735-71137--wanglei82_core0_forum_dura_term_predv1/logs/workspace/python27-gcc482/lib/python2.7/site-packages/paddle/v2/trainer.py", line 153, in train
Mon Aug 12 10:16:14 2019[1,4]<stderr>:    in_args = feeder(data_batch)
Mon Aug 12 10:16:14 2019[1,4]<stderr>:  File "/home/disk1/task_data/history/20190812/4.app-user-20190812095735-71137--wanglei82_core0_forum_dura_term_predv1/logs/workspace/python27-gcc482/lib/python2.7/site-packages/py_paddle/dataprovider_converter.py", line 282, in __call__
Mon Aug 12 10:16:14 2019[1,4]<stderr>:    return self.convert(dat, argument)
Mon Aug 12 10:16:14 2019[1,4]<stderr>:  File "/home/disk1/task_data/history/20190812/4.app-user-20190812095735-71137--wanglei82_core0_forum_dura_term_predv1/logs/workspace/python27-gcc482/lib/python2.7/site-packages/paddle/v2/data_feeder.py", line 134, in convert
Mon Aug 12 10:16:14 2019[1,4]<stderr>:    return DataProviderConverter.convert(self, reorder_data(dat), argument)
Mon Aug 12 10:16:14 2019[1,4]<stderr>:  File "/home/disk1/task_data/history/20190812/4.app-user-20190812095735-71137--wanglei82_core0_forum_dura_term_predv1/logs/workspace/python27-gcc482/lib/python2.7/site-packages/paddle/v2/data_feeder.py", line 130, in reorder_data
Mon Aug 12 10:16:14 2019[1,4]<stderr>:    reorder.append(each[self.feeding[name]])
Mon Aug 12 10:16:14 2019[1,4]<stderr>:IndexError: tuple index out of range

求各位大佬解答

**Comment by wopeizl** [comment]
本地可以跑通过吗？

**Comment by wopeizl** [comment]
v2版本当前已经不再维护更新，如果可以的话尽量使用最新的版本，如release1.5
