### ISSUE TITLE
训练过程中如何获取特定层的梯度数值并对其进行赋值

### ISSUE THREAD

**Issue by lzp1317** [PaddlePaddle/Paddle#19128]
用paddle训练模型过程中需要把多个特定层bnname的梯度取出来做处理然后再赋值回去，通过fluid.default_main_program().list_vars()可以找到梯度变量bnname@GRAD名字，但是用fluid.global_scope().find_var(bnname@GRAD).get_tensor()没有找到变量，不知道有没有接口可以做这件事情呢？

**Comment by lzp1317** [comment]
- 版本、环境信息：
    1）PaddlePaddle版本：paddlepaddle 1.5.0
    2）GPU：预测用GPU，GPU型号Tesla K40m、CUDA9.0和CUDNN7.0
    4）系统环境：CentOS release 6.3

**Comment by wopeizl** [comment]
scope是运行时的，grad var有可能被垃圾回收了，可以设置var.persistable = True来防止被回收，或者放在fetch_list中，如executor.run(fetch_list=[grad_Var])
