### ISSUE TITLE
Your decorated reader has raised an exception!

### ISSUE THREAD

**Issue by dingsiyu** [PaddlePaddle/Paddle#19132]
I0812 13:06:15.183413 93736 buffered_reader.cc:50] BufferedReader
I0812 13:06:15.190088 93741 lod_tensor_blocking_queue.h:62] LoDTensorBlockingQueue close
I0812 13:06:15.190119 93741 blocking_queue.h:100] close queue
WARNING: Logging before flag parsing goes to stderr.
W0812 13:06:15.190216 139712232683264 io.py:597] Your decorated reader has raised an exception!
Exception in thread Thread-1:
Traceback (most recent call last):
File "/home/slurm/job/tmp/job-62830/python/lib/python2.7/threading.py", line 801, in __bootstrap_inner
self.run()
File "/home/slurm/job/tmp/job-62830/python/lib/python2.7/threading.py", line 754, in run
self.__target(*self.__args, **self.__kwargs)
File "/home/slurm/job/tmp/job-62830/python/lib/python2.7/site-packages/paddle/fluid/layers/io.py", line 598, in __provider_thread__
raise ex
ValueError: invalid literal for int() with base 10: ''

I0812 13:06:15.191495 87775 reader.h:115] ResetAll
I0812 13:06:15.191519 87775 buffered_reader.cc:145] ShutdownImpl
I0812 13:06:15.191524 87775 lod_tensor_blocking_queue.h:62] LoDTensorBlockingQueue close
I0812 13:06:15.191526 87775 blocking_queue.h:100] close queue
I0812 13:06:15.191531 87775 blocking_queue.h:90] reopen queue
I0812 13:06:15.473848 87775 reader.h:105] ~ReaderHolder
I0812 13:06:15.473892 87775 buffered_reader.cc:26] ~BufferedReader
I0812 13:06:15.473897 87775 lod_tensor_blocking_queue.h:62] LoDTensorBlockingQueue close
I0812 13:06:15.473901 87775 blocking_queue.h:100] close queue
I0812 13:06:15.473980 87775 reader.cc:73] ~DecoratedReader
I0812 13:06:15.473986 87775 lod_tensor_blocking_queue.h:62] LoDTensorBlockingQueue close
I0812 13:06:15.473990 87775 blocking_queue.h:100] close queue
I0812 13:06:15.474396 87775 reader.h:105] ~ReaderHolder
I0812 13:06:15.474403 87775 lod_tensor_blocking_queue.h:62] LoDTensorBlockingQueue close
I0812 13:06:15.474407 87775 blocking_queue.h:100] close queue
I0812 13:06:15.474511 87775 reader.h:105] ~ReaderHolder
I0812 13:06:15.474515 87775 lod_tensor_blocking_queue.h:62] LoDTensorBlockingQueue close
I0812 13:06:15.474519 87775 blocking_queue.h:100] close queue

**Comment by wopeizl** [comment]
能给一下reader代码么
