### ISSUE TITLE
度量学习 utility.py 中 recall_topk函数参数k没用

### ISSUE THREAD

**Issue by xiangyubo** [PaddlePaddle/Paddle#19135]
度量学习 utility.py 中 recall_topk函数参数k没用，直到现在 develop 和 1.5 版本中都有这个问题。详细见代码77行：
https://github.com/PaddlePaddle/models/blob/develop/PaddleCV/metric_learning/utility.py

**Comment by wopeizl** [comment]
好的，谢谢指出
