### ISSUE TITLE
ernie fine-tune 后做预测，增大batch_size，出现爆显存，但明明有空间

### ISSUE THREAD

**Issue by hallySEU** [PaddlePaddle/Paddle#19140]
ernie fine-tune 后做预测，增大batch_size（从原来的32增加到128），出现爆显存，但明明有空间。
<img width="1259" alt="8874a406703d2e461a9e65e7367f1dcb" src="https://user-images.githubusercontent.com/25191684/62852941-7966eb00-bd1d-11e9-9c63-17e39047863a.png">

<img width="695" alt="03540a90f274d1b91b82b83dbbaea8ce" src="https://user-images.githubusercontent.com/25191684/62852919-67854800-bd1d-11e9-968d-667ff61817cd.png">
()

**Comment by wopeizl** [comment]
申请前需要做计算，当计算资源不足时候就报错了

**Comment by hallySEU** [comment]
> 申请前需要做计算，当计算资源不足时候就报错了

上面不是显示我的计算资源充足吗？可用空间还很多

**Comment by wopeizl** [comment]
相比128来说应该是不够的 ，申请会按128来一次性申请

**Comment by hallySEU** [comment]
> 相比128来说应该是不够的 ，申请会按128来一次性申请

如果当前内存不够，我可以使用其他块gpu吗？怎么做？
