### ISSUE TITLE
conv2d函数说明中英文错误

### ISSUE THREAD

**Issue by wudenggang** [PaddlePaddle/Paddle#19150]
details，错写成detials

    1）PaddlePaddle版本：paddlepaddle 1.5
    2）Python版本号: python-3.7.2.amd64
    5）文件位置：paddle\fluid\layers\nn.py，第2126行
![image](https://user-images.githubusercontent.com/3587832/62865599-83024a00-bd41-11e9-81dc-4226252e2964.png)

**Comment by wopeizl** [comment]
谢谢指出
