### ISSUE TITLE
对embedding之后的结果做加权

### ISSUE THREAD

**Issue by Emma-Ding** [PaddlePaddle/Paddle#19178]
在pslib模式下，现在有一个sequence，【1，2，3，4，5，6】，之前是我embeding之后，做了加和，如下
` 
emb = fluid.layers.embedding(input=data, size=[self._dict_dim, self._emb_dim], is_sparse=True, is_distributed=True, param_attr=fluid.ParamAttr(name=self._user_embedding_name))
         
bow = fluid.layers.sequence_pool(input=emb, pool_type='sum')
`
现在想做个加权和，或者类似最简单的attention，不知道paddle有没有类似的函数?

**Comment by SunGaofeng** [comment]
sequence_pool的时候做加权求和？

**Comment by Emma-Ding** [comment]
> sequence_pool的时候做加权求和？

是的呢
