### ISSUE TITLE
OCR端到端模型预测爆显存和单张图片core住问题

### ISSUE THREAD

**Issue by liushanshan07** [PaddlePaddle/Paddle#19179]
- 版本、环境信息：
    1）PaddlePaddle版本：1.4
    2）GPU：k40/p4、CUDA8.0和CUDNNv7

- 问题描述：
（1）显存持续增长
（2）单张图片core住。
Tensor holds the wrong type, it holds int64_t at [/root/cuda90_cudnnv7/0507/Paddle/paddle/fluid/framework/tensor_impl.h:29]

**Comment by NHZlX** [comment]
这边会对此模型进行复现，并且进行fix。
