### ISSUE TITLE
windows平台中，参数名中带有"/"字符时，使用fluid.io.save_vars保存参数，会出现crash

### ISSUE THREAD

**Issue by nepeplwu** [PaddlePaddle/Paddle#19180]
1）paddle版本：paddlepaddle-gpu-1.5.1.post97
2）系统版本：win10
3）Python版本：3.6

在windows下使用fluid.io.save_vars保存参数，且参数名中带有`/`（如参数名为"xception/entry_flow/conv1/weights"）时，会出现无法保存参数的错误
![593AF7049523271945AAD77537268820](https://user-images.githubusercontent.com/45024560/62930777-ab488200-bdef-11e9-873d-7da0824f912b.jpg)

**Comment by phlrain** [comment]
LGTM
