### ISSUE TITLE
maskrcnn+fpn模型开启显存优化结果diff, 关闭显存过大

### ISSUE THREAD

**Issue by pennypm** [PaddlePaddle/Paddle#19188]
版本、环境信息：
   1）PaddlePaddle版本：1.5.0
   2）GPU：CUDA8.0 CUDNN7
   3）系统环境：centOS6.3，Python: 2.7.14
问题描述：
线上服务代码
conf配置为enable_ir_optim:0，enable_memory_optim:1，当第一张图结果返回-1，后续图片结果异常，异常如下，上图为错误结果，下图为单独跑该图片时的正确结果
![image](https://user-images.githubusercontent.com/34053581/62945903-3e92af00-be12-11e9-9c9c-92d751d23378.png)
![image](https://user-images.githubusercontent.com/34053581/62945883-35094700-be12-11e9-8234-9b30e6d11f2e.png)
后来提供了新的so，在enable_memory_optim开启时，结果有diff
![image](https://user-images.githubusercontent.com/34053581/62948548-22ddd780-be17-11e9-9dfa-9a89f2a16e31.png)
关闭enable_memory_optim后结果无diff,  但是无显存优化效果，显存超标

**Comment by jerrywgz** [comment]
请问这是预测端的显存优化吗？

**Comment by pennypm** [comment]
> 请问这是预测端的显存优化吗？

是的

**Comment by NHZlX** [comment]
在解决中。

**Comment by NHZlX** [comment]
https://github.com/PaddlePaddle/Paddle/pull/19213
