### ISSUE TITLE
请问在预测的过程中如何取出模型的预测值

### ISSUE THREAD

**Issue by snksnc** [PaddlePaddle/Paddle#19185]
我的程序是这样写的：
loss_val, predict = exe.run(test_program,
                                            feed=feeder.feed(data_test),
                                            fetch_list=[loss, predict])
但是报错如下： 
   "Wrong type for fetch_list[%s]: %s" % (i, type(var)))
AssertionError: Wrong type for fetch_list[1]: <type 'numpy.ndarray'>
希望能给予解答，谢谢

**Comment by SunGaofeng** [comment]
这个地方看上去确实会出错fetch_list=[loss, predict]，这里loss和predict都是Variable，但是经过一个iteration之后，
    loss_val, predict = exe.run(test_program,feed=feeder.feed(data_test),fetch_list=[loss, predict])
predict出现在左边，被重新赋值了，type变成了numpy array

请修改成这样子：
  loss_val, predict_val = exe.run(test_program,feed=feeder.feed(data_test),fetch_list=[loss, predict])
