### ISSUE TITLE
关于 iterable PyReader 对象使用的一点疑问

### ISSUE THREAD

**Issue by wulipc** [PaddlePaddle/Paddle#19197]
硬件信息：
    1）PaddlePaddle版本：Fluid 1.50
    2）GPU：v100， CUDA9， cudnn7.1
    3）系统环境：Python2.7， paddlecloud
- 训练信息
    1）单机多卡， 24G mem / pre gpu

我目前使用 Fluid 1.50,  使用 PyReader 优化后 ， 单机多卡训练GPU的利用率有了显著提升， 目前代码训练正常， 但是在使用 iterable PyReader 过程中还有一点疑问， 想咨询一下。

我是参考官方文档 [异步数据读取](https://www.paddlepaddle.org.cn/documentation/docs/zh/1.5/user_guides/howto/prepare_data/use_py_reader.html#user-guides-use-py-reader)  来使用 PyReader 的， 具体而言：
```python
# step 1: 定义data_batch_reader
BATCH_SIZE = 16
def data_batch_reader():
    for images_batch, label_batch in  infinit_batch_generator(BATCH_SIZE):
        yield images_batch , label_batch

# step 2: 定义 PyReader
py_reader = fluid.io.PyReader(...)
py_reader.decorate_batch_generator(data_batch_reader, places=...)

# 8GPU
compiled_prog = fluid.CompiledProgram(fluid.default_main_program()).with_data_parallel(
                  loss_name=..., build_strategy=...)

# step 3: 单机多卡训练
for iter_id, data in enumerate(py_reader(), start=1):
    results = exe.run(program=compiled_prog, fetch_list=..., feed=data)
    ...
```

问题1： 我如果是单卡的 batch_size 是 16， 那么上面代码如果是8卡运行的话， 请问 BATCH_SIZE 因该设置为 16 还是设置为 16*8 ？

问题2： 如果设置的是 BATCH_SIZE 设置的是 16， 那我这么理解对不对： PyReader 维护一个 batch size 为 16 的 batch data 队列， 8个GPU相当是 8个worker， 要是那个work跑完了， PyReader就会送下一个batch的数据到空的GPU， 因此batch size 设置为单GPU的batch size就可以了？

问题3： 如果问题2的直观理解没有偏差，那么加速比如何衡量呢？ 讲道理应该是 8GPU 并行 和  4GPU并行  在相同的时间内， 8GPU 并行的 iter_id （上面代码片段， step3中定义的变量）应该是 4GPU并行  的2倍左右才对吧？   但是，  根据我目前观测到的结果， 8GPU 和 4GPU 在相同的时间内 iter_id 基本是一样的， 所以这个多卡加速在哪里体现了？

以下是一些 8GPU 和 4GPU 的对比数据（任务完全相同， 卡数不同， bs均为16）：

job-id | 卡数 | 利用率 | 运行时长 | iter_id
-- | -- | -- | -- | --
job-0bb5d51112bbb357 | 4 | 90.21% | 1 day 17 hour 44 min   52 sec | 139800
job-0bb5d51123e984ac | 8 | 86.21% | 1 day 17 hour 31 min   35 sec | 130400

**Comment by hutuxian** [comment]
感谢您使用PaddlePaddle
问题1：设置成16即可；
问题2：我理解您说的队列应该指的是pyreader的缓存区，实际上是通过PyReader的capacity来指定的，其他的理解问题不大；
问题3：您的iter_id是表示batch的数量吗？如果是，那么理论情况下，8卡和4卡虽然经历了相同的batch数，但是8卡过的数据是4卡的两倍，从这个角度来说相当于提速一倍。

**Comment by wulipc** [comment]
@hutuxian 感谢回复，任然有以下问题：

请问一下， pyreader的缓存区在内存还是在显存？ 我使用不同类型的decorate (samlpe, batch, list) ,  pyreader占用的空间怎么算？ 比如： 我一个sample占1M，batch size设为16， capacity设为5， 那我使用sample decorator 的时候是不是占用 5M 空间， 使用batch decorator的时候占用80M 空间吗？  还是说这个空间占用和运行卡数也有关系， 是80M * 卡数？

另外，对于
```python
for iter_id, data in enumerate(py_reader(), start=1):
       ...
```
其中的data不应该是一个batch（16 samples）的数据吗？ 所有通过的数据不应该是 16 * iter_id 吗？ 那么8卡过的数据为什么是4卡的两倍呢？

**Comment by hutuxian** [comment]
其实不同的decorate类型的区别只是为了输入数据形式的灵活，内部的占用空间都是以batch为单位，capacity指的是batch数量。也就是拿你的例子来说，应该都是80M。
多张卡（比如8卡）的情况下，每个卡的iter_id增长1，实际上整体的数据读入了batch_size*8这么多条samples的。

**Comment by wulipc** [comment]
Thx a lot.
