### ISSUE TITLE
使用book/fit_a_line中参考官网教程换成从txt读取文件运行出错

### ISSUE THREAD

**Issue by topxxuki** [PaddlePaddle/Paddle#19194]
- 版本、环境信息：
    1）PaddlePaddle版本：1.5
    2）CPU/GPU：cpu
    3）系统环境：Mac OS 10.14
    4）Python版本号:3.7
 -问题：https://github.com/PaddlePaddle/book/blob/develop/01.fit_a_line/train.py 教程代码将train_reader换为官网教程（https://paddlepaddle.org.cn/documentation/docs/zh/1.5/beginners_guide/basics/fit_a_line/README.cn.html)）从txt中读取方式
![image](https://user-images.githubusercontent.com/18697846/62998678-dd64ed00-be9e-11e9-9560-c1ecb706ec5f.png)报错如下：
![image](https://user-images.githubusercontent.com/18697846/62998699-ee156300-be9e-11e9-8957-f68f321bd98f.png)

**Comment by ceci3** [comment]
官网还没有更新过来，可以参考https://github.com/ceci3/book/blob/b72ab6400f78bef4f2082e1da72e30e1df145546/01.fit_a_line/index.cn.html#L225这里

**Comment by topxxuki** [comment]
> 官网还没有更新过来，可以参考[https://github.com/ceci3/book/blob/b72ab6400f78bef4f2082e1da72e30e1df145546/01.fit_a_line/index.cn.html#L225这里](https://github.com/ceci3/book/blob/b72ab6400f78bef4f2082e1da72e30e1df145546/01.fit_a_line/index.cn.html#L225%E8%BF%99%E9%87%8C)

![image](https://user-images.githubusercontent.com/18697846/63003471-cb894700-beaa-11e9-8ccd-f19c34946979.png)
应该是for d in data:吧
另外d[-1:]可以理解为标签值，d[:1]这个选取第一维是为什么呢？

**Comment by topxxuki** [comment]
reader改成如下所示，运行仍有问题：
```
def reader(data):
    for d in data:
        yield d[:-1], d[-1:]
```
![image](https://user-images.githubusercontent.com/18697846/63005265-c3cba180-beae-11e9-88a9-22c07ba82e7e.png)

**Comment by ceci3** [comment]
<img width="504" alt="屏幕快照 2019-08-14 下午4 38 53" src="https://user-images.githubusercontent.com/29245900/63006888-24101280-beb2-11e9-8c64-9d39560a4fcc.png">
先改成这样试下呢，我这里试了是可以的，您那边可以的话我更新到github上，上面那个选第一维是写错了，都是-1

**Comment by ceci3** [comment]
<img width="712" alt="屏幕快照 2019-08-14 下午4 41 03" src="https://user-images.githubusercontent.com/29245900/63006991-65a0bd80-beb2-11e9-97c0-256d51e4883a.png">
先改成这样试下呢，我这里试了是可以的，您那边可以的话我更新到github上，上面那个选第一维是写错了，都是-1。

**Comment by topxxuki** [comment]
可以的，谢谢
