### ISSUE TITLE
训练报段错误Segmentation fault python train.py

### ISSUE THREAD

**Issue by guoxpl** [PaddlePaddle/Paddle#19204]
![image](https://user-images.githubusercontent.com/20251192/63010297-b87d7380-beb8-11e9-9a50-d5f94922c36d.png)
![image](https://user-images.githubusercontent.com/20251192/63010319-c501cc00-beb8-11e9-91f4-c657cd9d661d.png)

**Comment by guoxpl** [comment]
1.4.1与1.5.0都出现此问题，我在paddlecloud slurm机器上运行，这个错误时不时会出现。同一份程序有时候会成功，大部分情况下失败。
使用k8s机器则无此问题。模型是自有的一个常用模型，因该没有问题。
错误发生在单卡run（）的时候。

![image](https://user-images.githubusercontent.com/20251192/63011603-36db1500-bebb-11e9-8345-c58eaf3942b2.png)

**Comment by hutuxian** [comment]
私下沟通解决，暂时关闭。
