### ISSUE TITLE
tensorrt报错不是很明确，只显示Segmentation fault

### ISSUE THREAD

**Issue by xiegegege** [PaddlePaddle/Paddle#19212]
欢迎您对PaddlePaddle提出建议，非常感谢您对PaddlePaddle的贡献！
在留下您的建议时，辛苦您同步提供如下信息：
- 版本、环境信息
1）PaddlePaddle版本：1.5
2）CPU/GPU：cuda9 cudnn7
3）系统环境：ubuntu16
- 复现信息：如为报错，请给出复现环境、复现步骤
- 建议描述：
在使用tensorrt时，有如下报错：
<img width="895" alt="a0f2bdde8c541d9c6afcd445a0f58b4d" src="https://user-images.githubusercontent.com/46314656/63021549-68f87100-bed3-11e9-9a7a-6398a068de49.png">
只有Segmentation fault这个提示，很难定位问题；后来发现编译设置了DTENSORRT_ROOT但没把tensorrt 路径加入到LD_LIBRARY_PATH，报错有没有可能多给点信息呢～

**Comment by hutuxian** [comment]
感谢您的建议，我们会进行评估，并不断完善报错信息。
