### ISSUE TITLE
分布式训练，梯度聚合的方法

### ISSUE THREAD

**Issue by minhozhou** [PaddlePaddle/Paddle#19210]
> Fluid分布式任务可以支持同步训练或异步训练，在同步训练方式下，所有的trainer节点，会在每个mini-batch 同步地合并所有节点的梯度数据并发送给parameter server完成更新

这里面**同步地合并所有节点的梯度数据**，具体每个参数对应的不同trainer节点上的梯度是如何合并的呢？有没有一些参考资料呢？

**Comment by hutuxian** [comment]
感谢使用PaddlePaddle。
实际上各个trainer也是把梯度发送到server端进行合并，只不过同步模式下，会在trainer端进行等待server端合并完成再开始接下来的训练。
Paddle这边提供有分布式训练的例子：https://www.paddlepaddle.org.cn/documentation/docs/zh/1.0/user_guides/howto/training/multi_node.html
https://www.paddlepaddle.org.cn/documentation/docs/zh/1.5/advanced_usage/best_practice/cpu_train_best_practice.html
如果有进一步的需要，欢迎您继续comment。

**Comment by minhozhou** [comment]
> 感谢使用PaddlePaddle。
> 实际上各个trainer也是把梯度发送到server端进行合并，只不过同步模式下，会在trainer端进行等待server端合并完成再开始接下来的训练。
> Paddle这边提供有分布式训练的例子：https://www.paddlepaddle.org.cn/documentation/docs/zh/1.0/user_guides/howto/training/multi_node.html
> https://www.paddlepaddle.org.cn/documentation/docs/zh/1.5/advanced_usage/best_practice/cpu_train_best_practice.html
> 如果有进一步的需要，欢迎您继续comment。

感谢回答，每个trainer节点都会得到所有参数和对应的梯度<param_0，gradient>，然后把这些发给server端合并，<param_0, [gradient_0, gradient_1, gradient_2.....]>，这些梯度是直接相加合并的吗？还是需要进行额外的一些其他算法计算呢

**Comment by hutuxian** [comment]
对梯度的处理方式和优化算法相关。例如最简单的SGD，就是求梯度的平均（或者理解为scale+sum).

**Comment by minhozhou** [comment]
> 对梯度的处理方式和优化算法相关。例如最简单的SGD，就是求梯度的平均（或者理解为scale+sum).

![image](https://user-images.githubusercontent.com/46623470/63081445-305da380-bf76-11e9-8392-55b4100b7b0d.png)

常见的这些优化算法都是直接使用梯度g或者使用梯度g计算出来的g_t更新参数，所以单纯的每个trainer节点上得到的梯度g传到pserver后，是求mean还是求sum作为最终的梯度给到不同的优化算法来计算g_t进行参数更新呢，还是说在trainer节点利用优化算法完成g_t的计算，再将g_t传给pserver进行mean或者sum合并？

**Comment by hutuxian** [comment]
优化算法是在server端进行的。

**Comment by minhozhou** [comment]
> 优化算法是在server端进行的。

我看tensorflow分布式好像是直接梯度求平均，paddle也是直接求平均吗😂

**Comment by hutuxian** [comment]
是的
