### ISSUE TITLE
Expected posix_memalign(&p, alignment, size) == 0, but received posix_memalign(&p, alignment, size):12 != 0:0.

### ISSUE THREAD

**Issue by Emma-Ding** [PaddlePaddle/Paddle#19217]
本地测试，报错

W0814 23:25:14.440135 79433 init.cc:150] AVX is available, Please re-compile on local machine
2019-08-14 23:25:20 batch_size=300
2019-08-14 23:25:20 FILELIST:['local_data/a']
import ujson error: No module named ujson use json
Traceback (most recent call last):
  File "local_train.py", line 13, in <module>
    batch_size=300
  File "/home/dingweiyue/multitask/mtl-model/ctr/mpi_submit/env_run/train.py", line 322, in train
    train_loop(fluid.default_main_program())
  File "/home/dingweiyue/multitask/mtl-model/ctr/mpi_submit/env_run/train.py", line 217, in train_loop
    exe.run(fluid.default_startup_program())
  File "/home/dingweiyue/tools/paddle_fluid/paddle_mpi_fluid/paddle_ids/python27-gcc482/lib/python2.7/site-packages/paddle/fluid/executor.py", line 525, in run
    use_program_cache=use_program_cache)
  File "/home/dingweiyue/tools/paddle_fluid/paddle_mpi_fluid/paddle_ids/python27-gcc482/lib/python2.7/site-packages/paddle/fluid/executor.py", line 593, in _run
    exe.run(program.desc, scope, 0, True, True, fetch_var_name)
paddle.fluid.core.EnforceNotMet: Enforce failed. Expected posix_memalign(&p, alignment, size) == 0, but received posix_memalign(&p, alignment, size):12 != 0:0.
Alloc 3200004096 error! at [/paddle/paddle/fluid/memory/detail/system_allocator.cc:51]
PaddlePaddle Call Stacks:
0       0x7f5b2424386ap void paddle::platform::EnforceNotMet::Init<std::string>(std::string, char const*, int) + 362
1       0x7f5b2522b982p paddle::memory::detail::AlignedMalloc(unsigned long) + 290
2       0x7f5b2522bc07p paddle::memory::detail::CPUAllocator::Alloc(unsigned long*, unsigned long) + 39
3       0x7f5b25228c33p paddle::memory::detail::BuddyAllocator::SystemAlloc(unsigned long) + 51
4       0x7f5b25229b34p paddle::memory::detail::BuddyAllocator::Alloc(unsigned long) + 324
5       0x7f5b25226ac1p void* paddle::memory::legacy::Alloc<paddle::platform::CPUPlace>(paddle::platform::CPUPlace const&, unsigned long) + 177
6       0x7f5b2522772dp paddle::memory::allocation::LegacyAllocator::AllocateImpl(unsigned long, paddle::memory::allocation::Allocator::Attr) + 365
7       0x7f5b2522883bp paddle::memory::allocation::Allocator::Allocate(unsigned long, paddle::memory::allocation::Allocator::Attr) + 27
8       0x7f5b252239dep paddle::memory::allocation::AllocatorFacade::Alloc(boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&, unsigned long, paddle::memory::allocation::Allocator::Attr) + 558
9       0x7f5b25223bdcp paddle::memory::allocation::AllocatorFacade::AllocShared(boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&, unsigned long, paddle::memory::allocation::Allocator::Attr) + 28
10      0x7f5b251eecb0p paddle::memory::AllocShared(boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&, unsigned long, paddle::memory::allocation::Allocator::Attr) + 48
11      0x7f5b251e78a3p paddle::framework::Tensor::mutable_data(boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_>, paddle::framework::proto::VarType_Type, paddle::memory::allocation::Allocator::Attr, unsigned long) + 147
12      0x7f5b244fa807p paddle::operators::FillConstantKernel<float>::Compute(paddle::framework::ExecutionContext const&) const + 503
13      0x7f5b244fa950p std::_Function_handler<void (paddle::framework::ExecutionContext const&), paddle::framework::OpKernelRegistrarFunctor<paddle::platform::CPUPlace, false, 0ul, paddle::operators::FillConstantKernel<float>, paddle::operators::FillConstantKernel<double>, paddle::operators::FillConstantKernel<long>, paddle::operators::FillConstantKernel<int>, paddle::operators::FillConstantKernel<paddle::platform::float16> >::operator()(char const*, char const*, int) const::{lambda(paddle::framework::ExecutionContext const&)#1}>::_M_invoke(std::_Any_data const&, paddle::framework::ExecutionContext const&) + 32
14      0x7f5b251af15dp paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&) const + 733
15      0x7f5b251adc70p paddle::framework::OperatorBase::Run(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&) + 240
16      0x7f5b24351f86p paddle::framework::Executor::RunPreparedContext(paddle::framework::ExecutorPrepareContext*, paddle::framework::Scope*, bool, bool, bool) + 358
17      0x7f5b24352f14p paddle::framework::Executor::Run(paddle::framework::ProgramDesc const&, paddle::framework::Scope*, int, bool, bool, std::vector<std::string, std::allocator<std::string> > const&, bool) + 132
18      0x7f5b24235960p
19      0x7f5b24281685p
20            0x4b4bfap PyEval_EvalFrameEx + 17834
21            0x4b6b28p PyEval_EvalCodeEx + 2040
22            0x4b5d10p PyEval_EvalFrameEx + 22208
23            0x4b6b28p PyEval_EvalCodeEx + 2040
24            0x4b5d10p PyEval_EvalFrameEx + 22208
25            0x4b6b28p PyEval_EvalCodeEx + 2040
26            0x4b5d10p PyEval_EvalFrameEx + 22208
27            0x4b6b28p PyEval_EvalCodeEx + 2040
28            0x4b5d10p PyEval_EvalFrameEx + 22208
29            0x4b6b28p PyEval_EvalCodeEx + 2040
30            0x4b6c52p PyEval_EvalCode + 50
31            0x4e1c7dp PyRun_FileExFlags + 285
32            0x4e3501p PyRun_SimpleFileExFlags + 209
33            0x4159ddp Py_Main + 2925
34      0x7f5b63eecbd5p __libc_start_main + 245
35            0x414b71p

**Comment by hutuxian** [comment]
posix_memalign返回12表示OOM了，可以重点看一下是不是内存申请的太多了，或者有没有出现内存泄漏的情况。
