### ISSUE TITLE
希望在 提交PR注意事项 页面中加入对覆盖率的要求

### ISSUE THREAD

**Issue by lijiancheng0614** [PaddlePaddle/Paddle#19222]
- 版本、环境信息
1）PaddlePaddle版本：1.5
- 复现信息：
如 https://github.com/PaddlePaddle/Paddle/pull/19050 曾因为 Python 行覆盖率未达 90% 而不通过 PR_CI_Coverage 检查。
- 建议描述：
建议在文档中加入对覆盖率的要求，如果能提供如何在本地测试覆盖率就更好了。
https://paddlepaddle.org.cn/documentation/docs/zh/1.5/advanced_usage/development/contribute_to_paddle/submit_pr_guide.html

**Comment by sandyhouse** [comment]
您的需求已记录，感谢您对paddle的支持。

**Comment by luotao1** [comment]
@kh2se2013 请看下这个需求，谢谢！
