### ISSUE TITLE
多次调用exe.run的问题

### ISSUE THREAD

**Issue by kennyLSN** [PaddlePaddle/Paddle#19220]
paddle1.5 由于线上调用，需要多次执行exe.run。
我写了一个单例。将模型初始化全部写了进去。然后当数据来的时候，执行data_generate以及exe.run。但是会有报错。cannot find fetch variable in scope. fetch_var_name is fc_72.tmp_2 at...
PaddlePaddle Call Stacks: Windows not support stack backtrace yet.

我感觉是program使用不对。

**Comment by sandyhouse** [comment]
exe.run的scope不对？方便贴下代码吗？

**Comment by kennyLSN** [comment]
try:
        args = parser.parse_args()

        logger.info("单例load")
        exe_new = initSentenceEmbed().exe
        reader_new = initSentenceEmbed().reader
        infer_program_new = initSentenceEmbed().infer_program
        pyreader_new = initSentenceEmbed().pyreader
        graph_vars_new = initSentenceEmbed().graph_vars

        logger.info("数据处理")

        data_generator = reader_new.data_generator_raw(
            input_data=inputdata,
            batch_size=args.batch_size,
            epoch=100,
            shuffle=False)

        logger.info("数据处理结束")

        infer_program_test = infer_program_new.clone(for_test=True)

        pyreader_new.decorate_tensor_provider(data_generator)
        pyreader_new.start()

        total_cls_emb = []
        total_top_layer_emb = []
        datetimenowTime = datetime.datetime.now()

        logger.info("开始计算")
        try:
            cls_emb, unpad_top_layer_emb = exe_new.run(
                program=infer_program_new,
                fetch_list=[
                    graph_vars_new["cls_embeddings"].name, graph_vars_new[
                        "top_layer_embeddings"].name
                ],
                return_numpy=False)
            logger.info("计算结束")
            total_cls_emb.append(np.array(cls_emb))
            total_top_layer_emb.append(np.array(unpad_top_layer_emb))
            return total_cls_emb
        except fluid.core.EOFException:
            print(fluid.core.EOFException)
            return ""

**Comment by kennyLSN** [comment]
> exe.run的scope不对？方便贴下代码吗？

我把下面的代码封装成了一个服务，每次数据请求的时候，就会调用。其中模型初始化是一个单例

try:
    args = parser.parse_args()

    logger.info("单例load")
    exe_new = initSentenceEmbed().exe
    reader_new = initSentenceEmbed().reader
    infer_program_new = initSentenceEmbed().infer_program
    pyreader_new = initSentenceEmbed().pyreader
    graph_vars_new = initSentenceEmbed().graph_vars

    logger.info("数据处理")

    data_generator = reader_new.data_generator_raw(
        input_data=inputdata,
        batch_size=args.batch_size,
        epoch=100,
        shuffle=False)

    logger.info("数据处理结束")

    infer_program_test = infer_program_new.clone(for_test=True)

    pyreader_new.decorate_tensor_provider(data_generator)
    pyreader_new.start()

    total_cls_emb = []
    total_top_layer_emb = []
    datetimenowTime = datetime.datetime.now()

    logger.info("开始计算")
    try:
        cls_emb, unpad_top_layer_emb = exe_new.run(
            program=infer_program_new,
            fetch_list=[
                graph_vars_new["cls_embeddings"].name, graph_vars_new[
                    "top_layer_embeddings"].name
            ],
            return_numpy=False)
        logger.info("计算结束")
        total_cls_emb.append(np.array(cls_emb))
        total_top_layer_emb.append(np.array(unpad_top_layer_emb))
        return total_cls_emb
    except fluid.core.EOFException:
        print(fluid.core.EOFException)
        return ""

**Comment by kennyLSN** [comment]
下面的代码已经封装成了一个服务，每次请求来的时候都会调用。其中初始化写成了单例模式

try:
    args = parser.parse_args()

    logger.info("单例load")
    exe_new = initSentenceEmbed().exe
    reader_new = initSentenceEmbed().reader
    infer_program_new = initSentenceEmbed().infer_program
    pyreader_new = initSentenceEmbed().pyreader
    graph_vars_new = initSentenceEmbed().graph_vars

    logger.info("数据处理")

    data_generator = reader_new.data_generator_raw(
        input_data=inputdata,
        batch_size=args.batch_size,
        epoch=10,
        shuffle=False)

    logger.info("数据处理结束")

    infer_program_test = infer_program_new.clone(for_test=True)

    pyreader_new.decorate_tensor_provider(data_generator)
    pyreader_new.start()

    total_cls_emb = []
    total_top_layer_emb = []
    datetimenowTime = datetime.datetime.now()

    logger.info("开始计算")
    try:
        cls_emb, unpad_top_layer_emb = exe_new.run(
            program=infer_program_new,
            fetch_list=[
                graph_vars_new["cls_embeddings"].name, graph_vars_new[
                    "top_layer_embeddings"].name
            ],
            return_numpy=False)
        logger.info("计算结束")
        total_cls_emb.append(np.array(cls_emb))
        total_top_layer_emb.append(np.array(unpad_top_layer_emb))
        return total_cls_emb
    except fluid.core.EOFException:
        print(fluid.core.EOFException)
        return ""

**Comment by sandyhouse** [comment]
你程序里面执行startup_program了吗？

**Comment by kennyLSN** [comment]
> 你程序里面执行startup_program了吗？

做过了，在单例里面

**Comment by kennyLSN** [comment]
或者你们有没有这种例子吧？我是做ernie的，想做成一个python服务

**Comment by kennyLSN** [comment]
问题已经解决了，exe.run后面加了一个pyreader.reset（）

**Comment by sandyhouse** [comment]
问题已解决，关闭issue。
