### ISSUE TITLE
pix2pix模型在GPU环境下可以跑通，在CPU环境下无法跑通

### ISSUE THREAD

**Issue by sucuicong** [PaddlePaddle/Paddle#19232]
为使您的问题得到快速解决，在建立Issue前，请您先通过如下方式搜索是否有相似问题:【搜索issue关键字】【使用labels筛选】【官方文档】

建立issue时，为快速解决问题，请您根据使用情况给出如下信息：
- 标题：简洁、精准描述您的问题，例如“ssd 模型前置lstm报错  ”
- 版本、环境信息：
    1）PaddlePaddle版本：请提供PaddlePaddle版本号，例如1.1或CommitID
    2）CPU：请提供CPU型号，MKL/OpenBlas/MKLDNN/等数学库的使用情况
    3）GPU：请提供GPU型号，CUDA和CUDNN版本号
    4）系统环境：请说明系统类型、版本（例如Mac OS 10.14），Python版本
- 模型信息
    1）模型名称  pix2pix
    2）使用数据集名称 cityscapes
    3）使用算法名称 pix2pix
    4）模型链接https://github.com/PaddlePaddle/models/blob/develop/PaddleCV/PaddleGAN/trainer/Pix2pix.py
- 复现信息：如为报错，请给出复现环境、复现步骤 
!python Pix2Pix/train.py --model_net Pix2pix \
                --dataset cityscapes/cityscapes \
                --data_dir data/data10830 \
                --train_list data/data10830/cityscapes/pix2pix_train_list \
                --test_list data/data10830/cityscapes/pix2pix_test_list \
                --crop_type Random \
                --dropout True \
                --gan_mode vanilla \
                --batch_size 1 \
                --epoch=5 \
                --output Pix2Pix/output \
                --use_gpu False
- 问题描述：请详细描述您的问题，同步贴出报错信息、日志/代码关键片段
CPU环境下报错
Traceback (most recent call last):
  File "Pix2Pix/train.py", line 68, in <module>
    train(cfg)
  File "Pix2Pix/train.py", line 50, in train
    model.build_model()
  File "/home/aistudio/Pix2Pix/trainer/Pix2pix.py", line 273, in build_model
    "input_B": tensor_B})
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.5/site-packages/paddle/fluid/executor.py", line 665, in run
    return_numpy=return_numpy)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.5/site-packages/paddle/fluid/executor.py", line 503, in _run_parallel
    exe.feed_and_split_tensor_into_local_scopes(feed_tensor_dict)
paddle.fluid.core_avx.EnforceNotMet: The number(1) of samples of current batch is less than the count(1) of devices(CPU), currently, it is not allowed. You should set the environment variable CPU_NUM in the system to determine the number of devices you need. at [/paddle/paddle/fluid/framework/parallel_executor.cc:658]

Thank you for contributing to PaddlePaddle.
Before submitting the issue, you could search issue in the github.Probably there was a similar issue submitted or resolved before.
If there is no solution,please make sure that this is a issue of models including the following details:
**System information**
-PaddlePaddle version （eg.1.1）or CommitID
-CPU: including CPUMKL/OpenBlas/MKLDNN version
-GPU: including CUDA/CUDNN version
-OS Platform (eg.Mac OS 10.14)
-Python version
-Name of Models&Dataset/details of operator
**To Reproduce**
Steps to reproduce the behavior
**Describe your current behavior**
**Code to reproduce the issue**
**Other info / logs**

**Comment by ceci3** [comment]
您好，请问下您的paddle版本是？这个错误的原因是您设置的CPU_NUM数量大于batch的数量，可以通过export CPU_NUM=1，或者拉取最新的models代码试下~

**Comment by sucuicong** [comment]
Paddle版本是1.5 ，所运行的代码是paddle release1.5版本， 没有修改过任何代码，直接运行的是paddle模型源码，所以CPU_NUM数量设置的问题应该是paddle模型代码编写者在写代码时候没有注意到这个问题造成的，望修改

发件人: lvmengsi <notifications@github.com>
答复: PaddlePaddle/Paddle <reply@reply.github.com>
日期: 2019年8月16日 星期五 上午10:32
收件人: PaddlePaddle/Paddle <Paddle@noreply.github.com>
抄送: "Su,Cuicong" <sucuicong@baidu.com>, Author <author@noreply.github.com>
主题: Re: [PaddlePaddle/Paddle] pix2pix模型在GPU环境下可以跑通，在CPU环境下无法跑通 (#19232)


您好，请问下您的paddle版本是？这个错误的原因是您设置的CPU_NUM数量大于batch的数量，可以通过export CPU_NUM=1，或者拉取最新的models代码试下~

**Comment by ceci3** [comment]
CPU_NUM默认设置的是1，可以检查下是否外部设置了这个环境变量

**Comment by sandyhouse** [comment]
Closing this issue. Reopen it if you have any further question.
