### ISSUE TITLE
paddle的模型能否分成几块区域存储？

### ISSUE THREAD

**Issue by paulpaul91** [PaddlePaddle/Paddle#19235]
paddle的参数能否分区域存储，例如encoder层和decoder层的参数分别存，加载的时候分别可以一起加载或者只加载encoder？是否有这样的实现？

**Comment by sandyhouse** [comment]
以paddle.fluid.io.save_vars(executor, dirname, main_program=None, vars=None, predicate=None, filename=None)为例，可以通过指定vars参数分别保存encoder层和decoder层的参数。

**Comment by sandyhouse** [comment]
Closing this issue. If you have any further question, please reopen it.

**Comment by sandyhouse** [comment]
Closing this issue. If you have any further question, please reopen it.
