### ISSUE TITLE
编译出错 cannot find -lmklml_intel

### ISSUE THREAD

**Issue by Re-bin** [PaddlePaddle/Paddle#19234]
/usr/bin/ld: cannot find -lmklml_intel

CPU不是intel，会是因为这个影响吗

**Comment by sandyhouse** [comment]
原因是找不到mklml_intel库。如果不使用的，可以设置-DWITH_MKL=OFF

**Comment by Re-bin** [comment]
> 原因是找不到mklml_intel库。如果不使用的，可以设置-DWITH_MKL=OFF

请教大神，在哪里设置呢

**Comment by sandyhouse** [comment]
> > 原因是找不到mklml_intel库。如果不使用的，可以设置-DWITH_MKL=OFF
> 
> 请教大神，在哪里设置呢

编译源码的时候设置，cmake的选项。

**Comment by Re-bin** [comment]
> > > 原因是找不到mklml_intel库。如果不使用的，可以设置-DWITH_MKL=OFF
> > 
> > 
> > 请教大神，在哪里设置呢
> 
> 编译源码的时候设置，cmake的选项。

请问可以在代码里面更改嘛，因为我编译的是AnyQ，cmake .. 的时候会生产很多文件，其中包括Paddle，在/AnyQ/build文件夹执行cmake的时候使用命令cmake -DWITH_MKL=OFF .. 之后，进行make，在paddle下载并编译的过程中还是出现了同样的错误。感谢您

**Comment by Re-bin** [comment]
> > > 原因是找不到mklml_intel库。如果不使用的，可以设置-DWITH_MKL=OFF
> > 
> > 
> > 请教大神，在哪里设置呢
> 
> 编译源码的时候设置，cmake的选项。

**无法获取"/home/AnyQ-master/build/third_party/install/paddle/fluid_install_dir/third_party/install/mklml/include/*" 的文件状态(stat): 没有那个文件或目录**
设置了，但是出现了新的问题，这个应该怎么解决。感谢。

**Comment by sandyhouse** [comment]
你的完整的编译选项是什么？

**Comment by Re-bin** [comment]
> 你的完整的编译选项是什么？

已经成功了，谢谢您。

**Comment by sandyhouse** [comment]
Closing this issue. If you have any further question, please reopen it.

**Comment by sandyhouse** [comment]
Closing this issue. If you have any further question, please reopen it.
