### ISSUE TITLE
Paddle C++ Inference时 concat异常慢，有什么优化空间么？

### ISSUE THREAD

**Issue by kelvict** [PaddlePaddle/Paddle#19241]
Paddle C++ Inference时 concat异常慢，有什么优化空间么？
![image](https://user-images.githubusercontent.com/4210638/63138877-a1509a00-c00e-11e9-93e7-56cef5180da3.png)

**Comment by ceci3** [comment]
您好，concat是在CPU上的操作还是GPU操作？

**Comment by kelvict** [comment]
CPU mkl @ceci3

**Comment by luotao1** [comment]
可以先试一下使用mkldnn库，在配置中加入：
`config.EnableMKLDNN()`

**Comment by kelvict** [comment]
已经开过了。 目前配置如下，
![image](https://user-images.githubusercontent.com/4210638/63221917-cbeb5000-c1d2-11e9-9386-ddd625347434.png)

**Comment by Superjomn** [comment]
concat 直接对应 memory copy，目前能用的优化方法都进去了
得尝试模型方面看看怎么规避下大的 concat
