### ISSUE TITLE
paddle支持模型并行训练吗？

### ISSUE THREAD

**Issue by dashulu** [PaddlePaddle/Paddle#19249]
Paddle现在支持模型并行的训练吗？CPU端还是GPU端的？有使用的例子吗？

**Comment by ceci3** [comment]
您好，您说的模型并行具体指的是？单机多卡或者多级多卡那种吗？

**Comment by dashulu** [comment]
> 您好，您说的模型并行具体指的是？单机多卡或者多级多卡那种吗？

举一个例子，假设一个模型有5个layer，2个layer放在gpu卡1剩下3个放在gpu卡2 或者两个layer放在服务器1， 剩下3个layer放在服务器2.

**Comment by ceci3** [comment]
目前还不支持这种操作

**Comment by dashulu** [comment]
那如果模型很大，一台机器的内存放不下去，Paddle是怎么处理的？

**Comment by ceci3** [comment]
计划1.6版本支持超大规模的分类问题~ 别的暂时还不支持
