### ISSUE TITLE
op split_ids does not have kernel for data_type[int] 

### ISSUE THREAD

**Issue by JingChunzhen** [PaddlePaddle/Paddle#19252]
paddle.fluid.core_avx.EnforceNotMet: Invoke operator split_ids error.
op split_ids does not have kernel for data_type[int]  

程序在本地可以运行 
在slurm集群上的单机节点上可以运行
在使用多机节点 pserver模式时出现问题

paddle版本v1.5.0

**Comment by seiriosPlus** [comment]
split_ids 支持的是int64类型的id类型的数据， 请问您 数据定义 是 int64类型的么？

**Comment by JingChunzhen** [comment]
我定义过int64，报的问题是op split_ids does not have kernel for data_type[int64_t]
所以我才替换成了int32

**Comment by seiriosPlus** [comment]
你是跑的GPU的任务？

**Comment by JingChunzhen** [comment]
对的 集群类型:Slurm集群硬件类型:GPU

**Comment by seiriosPlus** [comment]
GPU场景下，不推荐使用is_distributed=True的模式，目前没有经过严格验证过。
