### ISSUE TITLE
fluid.layers.roi_perspective_transform  Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by zhangxiaoqiang7** [PaddlePaddle/Paddle#19257]
paddle 版本：1.5.0
运行环境：python 2.7 cuda 9.0 cudnn 7.3 k40 单卡
问题：
使用以下代码提取roi特征，出core
!
![image](https://user-images.githubusercontent.com/17901811/63159677-a6cdd480-c04e-11e9-941f-c0789e7c88ff.png)
[image](https://user-images.githubusercontent.com/17901811/63159641-8ef65080-c04e-11e9-9740-7dd3d6076195.png)
使用gdb python查看core文件信息如下：
![image](https://user-images.githubusercontent.com/17901811/63159746-ce24a180-c04e-11e9-989c-0d0f8d51e0b2.png)
注释掉该op，使用py_func检查输入正常，shape分别为：self.f:[1L, 128L, 128L, 96L], polys:[6L, 8L], 类型为floa32，polys 信息如下：
![image](https://user-images.githubusercontent.com/17901811/63160145-a550dc00-c04f-11e9-9ccd-be203e88414e.png)

**Comment by SunGaofeng** [comment]
@zhangxiaoqiang7 能提供下具体代码吗，我看能不能在我们机器上复现这个问题？
