### ISSUE TITLE
如何加上环境变量GLOG_vmodule=operator=4

### ISSUE THREAD

**Issue by kidozh** [PaddlePaddle/Paddle#19259]
为使您的问题得到快速解决，在建立Issues前，请您先通过如下方式搜索是否有相似问题:【搜索issue关键字】【使用labels筛选】【官方文档】

如果您没有查询到相似问题，为快速解决您的提问，建立issue时请提供如下细节信息：
- 标题：简洁、精准概括您的问题，例如“Insufficient Memory xxx" ”
- 版本、环境信息：
    1）PaddlePaddle版本：1.5.1.post97
    2）CPU：Anaconda自带的数学库
    3）GPU：CUDA 9 CuDNN 9.2
    4）系统环境：Win10 Python3.5
- 训练信息
    1）单机/多机，单卡/多卡
    2）显存信息
    3）Operator信息

我在官方FAQ里面发现了对于添加这个环境变量的提示，但是在代码里加入了这个没法运行成功
```python
import os

os.environ['GLOG_logtostderr']="1"
os.environ["GLOG_vmodule"]="operator=4"
```

所以我想问问官方正确的姿势，并且能不能当弹出Tensor not initialized yet when Tensor::type() is called.时自动给上所有Tensor信息。

**Comment by ceci3** [comment]
直接
export GLOG_logtostderr=1
export GLOG_vmodule=operator=4
就可以了~
