### ISSUE TITLE
如何reuse scope 或 variable?

### ISSUE THREAD

**Issue by AliceZhang2016** [PaddlePaddle/Paddle#19254]
paddle: 1.5.0 - CPU
在使用预训练的ERNIE时候，希望同时建立两个共享参数的ErnieModel，如何做到像tf.variable_scope中reuse=tf.AUTO_REUSE呢？
在文档中没有查到，对任何建议都非常感谢！

**Comment by ceci3** [comment]
名字相同的话 就相当于是共享参数
