### ISSUE TITLE
如何对于这个shape=[batch,3,h,w]的variable进行mean为[0.406, 0.456, 0.485]，std为[0.225, 0.224, 0.229]的normalize

### ISSUE THREAD

**Issue by Overtown** [PaddlePaddle/Paddle#19250]
如题，想要对于一个输入图像img，进行normalize，查了下文档没有找到合适tensor操作方法，请教如何实现[batch,3,h,w]维度variable的normalize

**Comment by ceci3** [comment]
是输入数据的话 可以在数据预处理的时候 在python层面进行normalize

**Comment by Overtown** [comment]
> 是输入数据的话 可以在数据预处理的时候 在python层面进行normalize

肯定不是输入数据啊～是paddle的variable

**Comment by ceci3** [comment]
看了下paddle目前还不支持传入mean和var的norm，可以定义两个tensor，用elementwise_sub和elementwise_div试下
