### ISSUE TITLE
stargan参数gan_mode=lsgan时无法跑通

### ISSUE THREAD

**Issue by sucuicong** [PaddlePaddle/Paddle#19262]
为使您的问题得到快速解决，在建立Issue前，请您先通过如下方式搜索是否有相似问题:【搜索issue关键字】【使用labels筛选】【官方文档】

建立issue时，为快速解决问题，请您根据使用情况给出如下信息：
- 标题：简洁、精准描述您的问题，例如“ssd 模型前置lstm报错  ”
- 版本、环境信息：
    1）PaddlePaddle版本：请提供PaddlePaddle版本号，例如1.1或CommitID
    2）CPU：请提供CPU型号，MKL/OpenBlas/MKLDNN/等数学库的使用情况
    3）GPU：请提供GPU型号，CUDA和CUDNN版本号
    4）系统环境：请说明系统类型、版本（例如Mac OS 10.14），Python版本
- 模型信息
    1）模型名称  stargan
    2）使用数据集名称 celeba
    3）使用算法名称 stargan
    4）模型链接https://github.com/PaddlePaddle/models/tree/develop/PaddleCV/PaddleGAN
- 复现信息：如为报错，请给出复现环境、复现步骤
参数gan_mode=lsgan时无法跑通
- 问题描述：请详细描述您的问题，同步贴出报错信息、日志/代码关键片段
Traceback (most recent call last):
  File "PaddleGAN/train.py", line 89, in <module>
    train(cfg)
  File "PaddleGAN/train.py", line 73, in train
    model.build_model()
  File "/home/aistudio/PaddleGAN/trainer/StarGAN.py", line 287, in build_model
    self.batch_num)
  File "/home/aistudio/PaddleGAN/trainer/StarGAN.py", line 136, in __init__
    self.d_loss_gp.persistable = True
AttributeError: 'DTrainer' object has no attribute 'd_loss_gp'

Thank you for contributing to PaddlePaddle.
Before submitting the issue, you could search issue in the github.Probably there was a similar issue submitted or resolved before.
If there is no solution,please make sure that this is a issue of models including the following details:
**System information**
-PaddlePaddle version （eg.1.1）or CommitID
-CPU: including CPUMKL/OpenBlas/MKLDNN version
-GPU: including CUDA/CUDNN version
-OS Platform (eg.Mac OS 10.14)
-Python version
-Name of Models&Dataset/details of operator
**To Reproduce**
Steps to reproduce the behavior
**Describe your current behavior**
**Code to reproduce the issue**
**Other info / logs**

**Comment by ceci3** [comment]
StarGAN的lsgan模式没有验证过效果，最新的代码中已经删掉了这个模式，可以拉去最新的代码~
