### ISSUE TITLE
GRU中input_size为什么一定是frame_size的三倍

### ISSUE THREAD

**Issue by zhengkangjie** [PaddlePaddle/Paddle#19276]
在paddle1.5中，gru unit要求input_size必须为frame_size的三倍，并且在官方文档给出的机器翻译教程中，在使用gru unit之前也首先通过一个fc将输入数据的长度变为frame_size*3，这项要求会导致实现的神经网络参数增多，而且这项限制也不是必要的。
相关代码：paddle/fluid/operators/gru_unit_op.cc

**Comment by guoshengCS** [comment]
这是因为Paddle中将这三个对input的计算放在了gru unit的外部，https://www.paddlepaddle.org.cn/documentation/docs/zh/1.5/api_cn/layers_cn/nn_cn.html#gru-unit
<img width="723" alt="image" src="https://user-images.githubusercontent.com/14105589/63248131-41b9ef00-c299-11e9-81d7-47c8b0ef3bcd.png">
所以在使用gru unit之前也首先通过一个fc将输入数据的长度变为frame_size*3，效果是和公式里的一样的

**Comment by HuangLK** [comment]
这么做有什么好处吗？为什么应要把这一步操作分离出来？

**Comment by guoshengCS** [comment]
如果有对input的计算后的结果进行操作的需要，比如进行norm的操作，可以更灵活的支持
