### ISSUE TITLE
SSD 预测如何支持可变 shape ?

### ISSUE THREAD

**Issue by mzchtx** [PaddlePaddle/Paddle#19270]
以 MobileNet-SSD 为例，训练时候的图像输入 shape 为 `3 x 300 x 300`，在预测的时候是否支持可变的输入shape，如 `3 x 300 x 300`，`3 x 512 x 512` ?

**Comment by zhaoyuchen2018** [comment]
一般来说是不支持的，但是如果模型训练的时候可以输入不同shape，那么预测的时候就可以。对于不支持的你可以把数据预处理成训练的shape然后再用。

**Comment by mzchtx** [comment]
> 一般来说是不支持的，但是如果模型训练的时候可以输入不同shape，那么预测的时候就可以。对于不支持的你可以把数据预处理成训练的shape然后再用。

我理解主要是 `prior_box` layer 生成 box 时候限制的，因为 `prior_box` 中的 `min_size` 和 `max_size` 已经保存在模型中，而预测时候只会按照这个对应的 `min_size` 和 `max_size` 生成 box。

以 `MobileNet-SSD 300` 为例， 如下图所示，已经限定了框的 `max_size` 不会超过 300，那如果我用 `3 * 512 * 512` 的输入，`prior_box` 的输入依旧不会超过 300，而此时就无法覆盖超过 300 的目标。

![image](https://user-images.githubusercontent.com/37564754/63254183-dcb8c600-c2a5-11e9-9e6c-8d27a92615b8.png)

考虑到上述情况，是否为训练一个 `3 * 512 * 512` 的模型，然后预测的时候输入 `3 * 300 * 300` 就可以？

**Comment by qingqing01** [comment]
@mzchtx 预测支持变长shape，不用更改配置。 给变长的输入图片即可。

用PaddleDetection示例来说，模型训练输入是300x300，预测采用512x512作为输入，没问题:

```
export PYTHONPATH=`pwd`:$PYTHONPATH
export CUDA_VISIBLE_DEVICES=0
TRANSFORM="[!DecodeImage {to_rgb: true},!ResizeImage {target_size: 512, use_cv2: false, interp: 1},!Permute {},!NormalizeImage {mean: [127.5,127.5,127.5],std:[127.502231,127.502231,127.502231],is_scale: false, is_channel_first: true}]"
python tools/infer.py -c configs/ssd/ssd_mobilenet_v1_voc.yml  --infer_img demo/000000014439.jpg  \
    -o weights=https://paddlemodels.bj.bcebos.com/object_detection/ssd_mobilenet_v1_voc.tar SSDTestFeed.image_shape=[3,512,512] SSDTestFeed.sample_transforms="${TRANSFORM}"

```

**Comment by mzchtx** [comment]
> @mzchtx 预测支持变长shape，不用更改配置。 给变长的输入图片即可。
> 
> 用PaddleDetection示例来说，模型训练输入是300x300，预测采用512x512作为输入，没问题:
> 
> ```
> export PYTHONPATH=`pwd`:$PYTHONPATH
> export CUDA_VISIBLE_DEVICES=0
> TRANSFORM="[!DecodeImage {to_rgb: true},!ResizeImage {target_size: 512, use_cv2: false, interp: 1},!Permute {},!NormalizeImage {mean: [127.5,127.5,127.5],std:[127.502231,127.502231,127.502231],is_scale: false, is_channel_first: true}]"
> python tools/infer.py -c configs/ssd/ssd_mobilenet_v1_voc.yml  --infer_img demo/000000014439.jpg  \
>     -o weights=https://paddlemodels.bj.bcebos.com/object_detection/ssd_mobilenet_v1_voc.tar SSDTestFeed.image_shape=[3,512,512] SSDTestFeed.sample_transforms="${TRANSFORM}"
> ```

是可以预测，不过结果有问题，如下图是输入 `3 * 300 * 300` 的结果：
![image](https://user-images.githubusercontent.com/37564754/63319911-6ae88700-c34e-11e9-88c8-3b0ceb6dd38a.png)

这个是输入 `3 * 512 * 512` 的结果：
![image](https://user-images.githubusercontent.com/37564754/63319973-a7b47e00-c34e-11e9-9598-2763a5850bb5.png)

demo 中的图片没出现这个问题是因为 demo 中图片的目标都比较小，体现不出来，辛苦再确认下
