### ISSUE TITLE
CPU占用时间很多

### ISSUE THREAD

**Issue by fengchun1213** [PaddlePaddle/Paddle#19327]
用profiler看了一下，发现cpu时间好长，一般是什么问题呢
![屏幕快照 2019-08-21 下午6 41 20](https://user-images.githubusercontent.com/48874817/63425514-4de1b000-c443-11e9-9c94-d2edc248821e.png)

**Comment by Shixiaowei02** [comment]
您好，请提供具体版本和代码以便问题调试，谢谢！
