### ISSUE TITLE
dssm模型训练过程中，loss不减小，auc提升慢，模型收敛慢

### ISSUE THREAD

**Issue by wlxy** [PaddlePaddle/Paddle#19321]
求助：
dssm模型训练过程中，loss不减小，auc提升慢，模型收敛慢，增加学习率也没有改善
对于这种情况，可以从哪些方面去优化网络呢？

为使您的问题得到快速解决，在建立Issues前，请您先通过如下方式搜索是否有相似问题:【搜索issue关键字】【使用labels筛选】【官方文档】

如果您没有查询到相似问题，为快速解决您的提问，建立issue时请提供如下细节信息：
- 标题：简洁、精准概括您的问题，例如“Insufficient Memory xxx" ”
- 版本、环境信息：
    1）PaddlePaddle版本：请提供您的PaddlePaddle版本号，例如1.1或CommitID
    2）CPU：预测若用CPU，请提供CPU型号，MKL/OpenBlas/MKLDNN/等数学库使用情况
    3）GPU：预测若用GPU，请提供GPU型号、CUDA和CUDNN版本号
    4）系统环境：请您描述系统类型、版本，例如Mac OS 10.14，Python版本
- 训练信息
    1）单机/多机，单卡/多卡
    2）显存信息
    3）Operator信息
- 复现信息：如为报错，请给出复现环境、复现步骤
- 问题描述：请详细描述您的问题，同步贴出报错信息、日志、可复现的代码片段

Thank you for contributing to PaddlePaddle.
Before submitting the issue, you could search issue in the github in case that there was a similar issue submitted or resolved before.
If there is no solution,please make sure that this is a training issue including the following details:
**System information**
-PaddlePaddle version （eg.1.1）or CommitID
-CPU: including CPUMKL/OpenBlas/MKLDNN version
-GPU: including CUDA/CUDNN version
-OS Platform (eg.Mac OS 10.14)
-Other imformation: Distriuted training/informantion of operator/
Graphics card storage
**To Reproduce**
Steps to reproduce the behavior
**Describe your current behavior**
**Code to reproduce the issue**
**Other info / logs**

**Comment by xyzhou-puck** [comment]
您好，请问您使用的是模型库已有的模型吗？一般来说，模型训练效果不好，可以考虑使用预训练embedding初始化，也可以检查一下每个batch的正负样本是否均衡，数据集是否噪音过大等。

如果方便的话，麻烦发一下您的代码和数据，我们可以帮您debug一下。

**Comment by wlxy** [comment]
job-0bb5d5192f038a4b 这是我在训练过的一个模型，你可以克隆一份任务
谢谢啦～

**Comment by Bradyzzhang** [comment]
> 您好，请问您使用的是模型库已有的模型吗？一般来说，模型训练效果不好，可以考虑使用预训练embedding初始化，也可以检查一下每个batch的正负样本是否均衡，数据集是否噪音过大等。
> 
> 如果方便的话，麻烦发一下您的代码和数据，我们可以帮您debug一下。

你好，我的dssm模型是训练的auc>0.8。采用了负采样，正负比例1：3，但是模型的faiss召回，hitrate只有YouTube DNN的1/3，请问可以帮忙debug一下吗？
