### ISSUE TITLE
使用paddlevideo模型训练时，数据集使用pkl类型会报错：[INFO: kinetics_reader.py:  151]: Error when loading /home/aistudio/PaddleVideo/dataset/youtube8m/youtube8m/pkl/train/trainlp.pkl

### ISSUE THREAD

**Issue by LALAliyao** [PaddlePaddle/Paddle#19330]

**Comment by Shixiaowei02** [comment]
请详细描述一下问题，谢谢

**Comment by LALAliyao** [comment]
> 请详细描述一下问题，谢谢
上面那个问题解决了，请问一下模型预测的时候，infer_result以pkl文件存储，怎样查看视频分类结果呢

**Comment by LALAliyao** [comment]
请问一下最后预测出来的pkl文件，该怎样查看他的结果呢？



---原始邮件---
发件人: "石晓伟"<notifications@github.com>
发送时间: 2019年8月22日(星期四) 上午10:43
收件人: "PaddlePaddle/Paddle"<Paddle@noreply.github.com>;
抄送: "Author"<author@noreply.github.com>;"LALAliyao"<1907381057@qq.com>;
主题: Re: [PaddlePaddle/Paddle] 使用paddlevideo模型训练时，数据集使用pkl类型会报错：[INFO: kinetics_reader.py:  151]: Error when loading /home/aistudio/PaddleVideo/dataset/youtube8m/youtube8m/pkl/train/trainlp.pkl (#19330)



请详细描述一下问题，谢谢
