### ISSUE TITLE
Paddle集群训练过程中报GRPC错误

### ISSUE THREAD

**Issue by yangjing14** [PaddlePaddle/Paddle#19339]
- 版本、环境信息：
    1）PaddlePaddle版本：1.4.1
    2）Paddle Cloud，MPI任务
- 问题描述：
任务链接：http://10.90.102.22:8910/fileview.html?type=logsdir&path=/&instance=0.app-user-20190821225301-12979--train_job_quanmin_siamese2_32_epoch3_4_paddlecloud

训练过程中忽然报Grpc 14的错误，具体日志如下：
Thu Aug 22 01:28:55 2019[1,12]<stdout>:F0822 01:28:55.904119 14626 grpc_client.cc:418] SendRPC name:[emb_title@GRAD.block48.trainer_12], ep:[10.90.122.15:62004], status:[-1] meets grpc error, error_code:14 error_message:OS Error error_details:
Thu Aug 22 01:28:55 2019[1,12]<stdout>:*** Check failure stack trace: ***
Thu Aug 22 01:28:55 2019[1,12]<stdout>:    @     0x7fbfd9126c0d  google::LogMessage::Fail()
Thu Aug 22 01:28:55 2019[1,12]<stdout>:    @     0x7fbfd912a6bc  google::LogMessage::SendToLog()
Thu Aug 22 01:28:55 2019[1,12]<stdout>:    @     0x7fbfd9126733  google::LogMessage::Flush()
Thu Aug 22 01:28:55 2019[1,12]<stdout>:    @     0x7fbfd912bbce  google::LogMessageFatal::~LogMessageFatal()
Thu Aug 22 01:28:55 2019[1,12]<stdout>:    @     0x7fbfd9d2be0e  paddle::operators::distributed::GRPCClient::Proceed()
Thu Aug 22 01:28:55 2019[1,12]<stdout>:    @     0x7fc04349d8a0  execute_native_thread_routine
Thu Aug 22 01:28:55 2019[1,12]<stdout>:    @     0x7fc04e1ae1c3  start_thread
Thu Aug 22 01:28:55 2019[1,12]<stdout>:    @     0x7fc04d7d612d  __clone
Thu Aug 22 01:28:55 2019[1,12]<stdout>:    @              (nil)  (unknown)

**Comment by liangpj** [comment]
一样的问题：
版本框架:
paddle-fluid-v1.2.0
任务链接：
http://10.156.84.25:8900/fileview.html?path=/home/disk1/normandy/maybach/app-user-20190821144228-12567/
报错节点 log:
http://10.156.82.34:8900/fileview.html?path=/home/disk1/normandy/maybach/app-user-20190821144228-12567/
报错信息：
pass_id: 0 batch_F0822 08:18:01.013775 51005 grpc_client.cc:357] SendRPC name:[embedding_0.w_0@GRAD.block0.trainer_0], ep:[10.156.82.27:62004], status:[-1] meets grpc error, error_code:14 error_message:OS Error error_details:
*** Check failure stack trace: ***
    @     0x7f5394dafcdd  google::LogMessage::Fail()
    @     0x7f5394db378c  google::LogMessage::SendToLog()
    @     0x7f5394daf803  google::LogMessage::Flush()
    @     0x7f5394db4c9e  google::LogMessageFatal::~LogMessageFatal()
    @     0x7f5395804994  paddle::operators::distributed::GRPCClient::Proceed()
    @     0x7f536b5858a0  execute_native_thread_routine
    @     0x7f5408d531c3  start_thread
    @     0x7f540837b12d  __clone
    @              (nil)  (unknown)

**Comment by seiriosPlus** [comment]
1. 同步训练还是异步训练
2. 是在训练过程中出的问题还是训练开始出的问题

**Comment by yangjing14** [comment]
> 1. 同步训练还是异步训练
> 2. 是在训练过程中出的问题还是训练开始出的问题

同步训练，训练过程中出现问题

**Comment by seiriosPlus** [comment]
error code 14会在下一个版本中解决此问题，目前的话可以尝试用异步训练或者重试来避免此问题。

**Comment by yangjing14** [comment]
> error code 14会在下一个版本中解决此问题，目前的话可以尝试用异步训练或者重试来避免此问题。

下个版本大概什么时候能用？

**Comment by seiriosPlus** [comment]
> > error code 14会在下一个版本中解决此问题，目前的话可以尝试用异步训练或者重试来避免此问题。
> 
> 下个版本大概什么时候能用？

还需要等待一段时间， 
如果涉及到rpc error code 4， 可以基于这个PR https://github.com/PaddlePaddle/Paddle/pull/18984 
涉及到error code 14， 目前可以尝试异步或者重试。
