### ISSUE TITLE
C++ 预测性能优化

### ISSUE THREAD

**Issue by xiongbinbtbu** [PaddlePaddle/Paddle#19335]
使用cpp的avx_openblas版本接口预测68ms，使用cpp的avx_mkl版本预测173毫秒，按照https://www.paddlepaddle.org.cn/documentation/docs/zh/1.5/advanced_usage/deploy/inference/native_infer.html 添加EnableMKLDNN、EnableMemoryOptim也没有什么效果，如果需要把时延降到10ms可以从哪些地方优化？

**Comment by OliverLPH** [comment]
`config->SetCpuMathLibraryNumThreads(8);`打开这个优化试试呢

**Comment by luotao1** [comment]
> 使用cpp的avx_openblas版本接口预测68ms，使用cpp的avx_mkl版本预测173毫秒

avx_mkl不应该比avx_openblas慢。
- 是一个独立业务，还是加了很多其他业务逻辑呢？
- 库版本号？
- cpu型号
