### ISSUE TITLE
paddlecloud Trainer报错，meets grpc error, error_code:

### ISSUE THREAD

**Issue by sshilei** [PaddlePaddle/Paddle#19331]
F0821 08:28:45.851277  2464 grpc_client.cc:414] FetchBarrierRPC name:[FETCH_BARRIER@RECV], ep:[10.89.140.19:30010], status:[-1] meets grpc error, error_code:4 error_message:Deadline Exceeded error_details:
*** Check failure stack trace: ***
    @     0x7f495d9797ed  google::LogMessage::Fail()
    @     0x7f495d97d29c  google::LogMessage::SendToLog()
    @     0x7f495d979313  google::LogMessage::Flush()
    @     0x7f495d97e7ae  google::LogMessageFatal::~LogMessageFatal()
    @     0x7f495e6ccb0e  paddle::operators::distributed::GRPCClient::Proceed()
    @     0x7f496c5d8470  (unknown)
    @     0x7f4a207aeaa1  start_thread
    @     0x7f4a1fe70c4d  clone
    @              (nil)  (unknown)
Traceback (most recent call last):
  File "frame/core/dataset_reader.py", line 59, in <module>
    dataset_reader.run_from_stdin()
  File "/usr/local/lib/python2.7/site-packages/paddle/fluid/incubate/data_generator/__init__.py", line 135, in run_from_stdin
    sys.stdout.write(self._gen_str(sample))
IOError: [Errno 32] Broken pipe

**Comment by MrChengmo** [comment]
可以给我(chengmo)分享一下cloud任务吗，看一下是不是分布式配置上的问题
