### ISSUE TITLE
How to get 'feeded_var_names' and 'target_vars' so that I can save the inference model?

### ISSUE THREAD

**Issue by prakharg24** [PaddlePaddle/Paddle#19343]
I am new to paddlepaddle. I am trying to reproduce the code present here ->

https://github.com/PaddlePaddle/models/blob/develop/PaddleCV/ssd/train.py

But instead of using save_persistables, I want to do save_inference_model

However save_inference_model requires two extra inputs, 'feeded_var_names' and 'target_vars'. From where can I get this input?

In short, how do I edit the code present in train.py in the repository above, so that I can use save_inference_model instead of save_persistables? (line 225)

Thank You.

**Comment by OliverLPH** [comment]
`feeded_var_names` refers to a list contained names of variables that need to be feeded data during inference.
`target_vars` is variables from which we can get inference results. 

you can have a look at this page [save-inference-model](https://www.paddlepaddle.org.cn/documentation/docs/en/1.5/api/io.html#save-inference-model)

But since train.py loads data via pyreader, I'm not sure the name of `feeded_var_names`, maybe you can try following codes, hope it works.
[nmsed_out](https://github.com/PaddlePaddle/models/blob/85ca049ceb84daf796df5fb65cf12855707f0ea2/PaddleCV/ssd/train.py#L146)
```python
test_py_reader, map_eval, nmsed_out, image = build_program(main_prog=test_prog,
                           startup_prog=startup_prog,
                           train_params=train_params,
                           is_train=False)
feeded_var_names = [image.name]  # or feeded_var_names = ['image'] 
target_vars = nmsed_out
```

**Comment by prakharg24** [comment]
> `feeded_var_names` refers to a list contained names of variables that need to be feeded data during inference.
> `target_vars` is variables from which we can get inference results.
> 
> you can have a look at this page [save-inference-model](https://www.paddlepaddle.org.cn/documentation/docs/en/1.5/api/io.html#save-inference-model)
> 
> But since train.py loads data via pyreader, I'm not sure the name of `feeded_var_names`, maybe you can try following codes, hope it works.
> [nmsed_out](https://github.com/PaddlePaddle/models/blob/85ca049ceb84daf796df5fb65cf12855707f0ea2/PaddleCV/ssd/train.py#L146)
> 
> ```python
> test_py_reader, map_eval, nmsed_out, image = build_program(main_prog=test_prog,
>                            startup_prog=startup_prog,
>                            train_params=train_params,
>                            is_train=False)
> feeded_var_names = [image.name]  # or feeded_var_names = ['image'] 
> target_vars = nmsed_out
> ```
Thank you for the reply @OliverLPH 

After a lot messing around of my own, I did already try exactly what you have mentioned here. This did not present any errors while saving the model and also created a '\_model\_' file inside the folder as I expected.

However, I was trying to save this as an inference model because I wanted to use this model for calculating the score using the script here ->

https://github.com/PaddlePaddle/models/blob/develop/PaddleCV/Research/astar2019/score.py

But when I tried running the inference model (line 76), I got an error saying that the output had 'LOD' information in it and thus I should use 'return_numpy=False'
I also tried doing that, but then I got the error 'too many values to unpack, expected 2, got 1'

My understanding is that the score.py script expects 2 outputs, while I am only providing it 1. Also it expects outputs to not have the 'LOD' information, whatever that is, so that the tensor can be converted to numpy.

Do you have any insights regarding this? @OliverLPH 

Thank You

**Comment by OliverLPH** [comment]
Could please provide a snapshot of that error? I haven't met this error before.

or maybe you can try feed data in this way?
```python
feeder = fluid.DataFeeder(
        place=place,
        feed_list=[image])

boxes_np, scores_np = exe.run(
        program=infer_program,
        feed=feeder.feed(data),
        fetch_list=target_var)
```

**Comment by prakharg24** [comment]
This is the error that I got by simply using the model directory that was formed earlier in score.py script

```
Traceback (most recent call last):
  File "score.py", line 181, in <module>
    score, mAP, flops = compute_score(args.model_dir, args.data_dir, batch_size=args.batch_size)
  File "score.py", line 155, in compute_score
    feeded_var_names, feeder, target_var, batch_size)
  File "score.py", line 65, in use_coco_api_compute_mAP
    fetch_list=target_var)
  File "/home/john/.local/lib/python3.5/site-packages/paddle/fluid/executor.py", line 651, in run
    use_program_cache=use_program_cache)
  File "/home/john/.local/lib/python3.5/site-packages/paddle/fluid/executor.py", line 754, in _run
    outs = as_numpy(outs)
  File "/home/john/.local/lib/python3.5/site-packages/paddle/fluid/executor.py", line 115, in as_numpy
    return [as_numpy(t) for t in tensor]
  File "/home/john/.local/lib/python3.5/site-packages/paddle/fluid/executor.py", line 115, in <listcomp>
    return [as_numpy(t) for t in tensor]
  File "/home/john/.local/lib/python3.5/site-packages/paddle/fluid/executor.py", line 122, in as_numpy
    return LoDTensor itself directly.")
RuntimeError: Some of your fetched tensors hold LoD information.             They can not be completely cast to Python ndarray.             Please set the parameter 'return_numpy' as 'False' to             return LoDTensor itself directly.

```

And when chnged the code to --

```
        boxes_np, scores_np = exe.run(program=infer_program,
                                      feed={feeded_var_names[0]: feeder.feed(data)['image']},
                                      fetch_list=target_var, return_numpy=False)
```

I got this error ->

```
Traceback (most recent call last):
  File "score.py", line 181, in <module>
    score, mAP, flops = compute_score(args.model_dir, args.data_dir, batch_size=args.batch_size)
  File "score.py", line 155, in compute_score
    feeded_var_names, feeder, target_var, batch_size)
  File "score.py", line 65, in use_coco_api_compute_mAP
    fetch_list=target_var, return_numpy=False)
ValueError: not enough values to unpack (expected 2, got 1)
```

I tried to just get the output and print it to see what is happening, so I changes the code to --

```
        sme_ele = exe.run(program=infer_program,
                                      feed={feeded_var_names[0]: feeder.feed(data)['image']},
                                      fetch_list=target_var, return_numpy=False)
        print(sme_ele)
```

And I got this as the output ->
```
[<paddle.fluid.core_avx.LoDTensor object at 0x7f46b993ced8>]
```

Which is clearly only a single element array. That's why I said that I think I am returning only one output while the script expects me to return 2 outputs (boxes_np and scores_np).

**Comment by prakharg24** [comment]
> Could please provide a snapshot of that error? I haven't met this error before.
> 
> or maybe you can try feed data in this way?
> 
> ```python
> feeder = fluid.DataFeeder(
>         place=place,
>         feed_list=[image])
> 
> boxes_np, scores_np = exe.run(
>         program=infer_program,
>         feed=feeder.feed(data),
>         fetch_list=target_var)
> ```

I tried feeding the data this way and got the error
```
Traceback (most recent call last):
  File "score.py", line 181, in <module>
    score, mAP, flops = compute_score(args.model_dir, args.data_dir, batch_size=args.batch_size)
  File "score.py", line 155, in compute_score
    feeded_var_names, feeder, target_var, batch_size)
  File "score.py", line 67, in use_coco_api_compute_mAP
    feed=feeder.feed(data),
  File "/home/john/.local/lib/python3.5/site-packages/paddle/fluid/data_feeder.py", line 282, in feed
    "len(feed_list) (%s)") % (len(each_sample), len(converter))
AssertionError: The number of fields in data (5) does not match len(feed_list) (1)
```

**Comment by prakharg24** [comment]
I think that the score.py expects me to save an inference model whose outputs are boxes and scores. But currently I am saving a model whose output is the final output after nms. So I looked back into train.py and found this 
```
            image, gt_box, gt_label, difficult = fluid.layers.read_file(py_reader)
            locs, confs, box, box_var = build_mobilenet_ssd(image, class_num, image_shape)
            if is_train:
                with fluid.unique_name.guard("train"):
                    loss = fluid.layers.ssd_loss(locs, confs, gt_box, gt_label, box,
                        box_var)
                    loss = fluid.layers.reduce_sum(loss)
                    optimizer = optimizer_setting(train_params)
                    optimizer.minimize(loss)
                outs = [py_reader, loss]
            else:
                with fluid.unique_name.guard("inference"):
                    nmsed_out = fluid.layers.detection_output(
                        locs, confs, box, box_var, nms_threshold=0.45)
                    map_eval = fluid.metrics.DetectionMAP(
                        nmsed_out,
                        gt_label,
                        gt_box,
                        difficult,
                        class_num,
                        overlap_threshold=0.5,
                        evaluate_difficult=False,
                        ap_version=ap_version)
                # nmsed_out and image is used to save mode for inference
                outs = [py_reader, map_eval, nmsed_out, image]
```

Here instead of using nmsed_out, I should probably use box and confs. But I am not sure what box_var and locs are so I am confused as to whether this will be the right way to do it.

Thank You

**Comment by prakharg24** [comment]
It worked!!! Atleast there are no errors. I fed [locs, confs] as target_vars instead of nmsed_out.

Small issue, the expected output of scores_np should be of shape batch * num_classes * num_boxes
But the confs tensor present here gives the output of shape batch * num_boxes * num_classes

Obviously I can simply transpose the output, but my only concern is why this change of shape? I mean will these values go through some other transformation too that I am missing by just doing a transpose?!!

I guess I will only know after I train completely and check the accuracy.

For now, all the errors have been removed.

Thank You.

**Comment by prakharg24** [comment]
Reopened this in case anyone visits this issue for reference. Feeding [locs, confs] as target_vars will not work.

locs -> represent the distortion from the anchor box.
confs -> represent the confidence score (without softmax)
box -> represent anchor boxes
box_var -> represent anchor box variance

'fluid.layers.detection_output' actually does two things. One it converts the above four variable into confidence score and predicted boxes (which is what we actually want). And two it applies NMS on them.

So, this code is the final version that works properly

```
locs, confs, box, box_var = build_mobilenet_ssd(image, class_num, image_shape)

decoded_box = fluid.layers.box_coder(prior_box=box, prior_box_var=box_var, target_box=locs, code_type='decode_center_size')
conf_inf = fluid.layers.softmax(input=confs)
conf_inf = fluid.layers.transpose(conf_inf, perm=[0, 2, 1])
```

Now feed [decoded_box, conf_inf] as target_vars for saving the final inference model.
