### ISSUE TITLE
develop分支上显存不足报CUDNN_STATUS_INTERNAL_ERROR

### ISSUE THREAD

**Issue by xiegegege** [PaddlePaddle/Paddle#19358]
欢迎您对PaddlePaddle提出建议，非常感谢您对PaddlePaddle的贡献！
在留下您的建议时，辛苦您同步提供如下信息：
- 版本、环境信息
1）PaddlePaddle版本：develop分支
2）CPU/GPU：CUDA9 CUDNN7
3）系统环境：centos
- 复现信息：如为报错，请给出复现环境、复现步骤
- 建议描述：请您详细描述，您认为需优化的功能
paddle develop分支上显存不足报CUDNN_STATUS_INTERNAL_ERROR，看不出来是显存不足，建议优化下

**Comment by jucaowei** [comment]
确实
