### ISSUE TITLE
动态图cyclegan训练内存泄露

### ISSUE THREAD

**Issue by DDDivano** [PaddlePaddle/Paddle#19351]
dict每一轮增加4个，variable每一轮增加4个。
在train.py文件中
![image](https://user-images.githubusercontent.com/10734244/63495770-1599aa80-c4f3-11e9-81eb-6ecd67bb2a77.png)
这里增加了4个dict和2个variable
![image](https://user-images.githubusercontent.com/10734244/63495790-221e0300-c4f3-11e9-9d26-c824277b9b60.png)
这里增加了2个variable，这个可解释。
需要排查一下模型forward代码涉及的layer是否存在内存泄露问题。

**Comment by Joejiong** [comment]
增加四个参数吗还是什么？
