### ISSUE TITLE
训练时如何让删除内存中的program_cache

### ISSUE THREAD

**Issue by topxxuki** [PaddlePaddle/Paddle#19357]
<img width="725" alt="MacHi 2019-08-22 18-48-50" src="https://user-images.githubusercontent.com/18697846/63508912-83eb6680-c50d-11e9-93ef-acfc99a4513a.png">
- 版本、环境信息：
    1）PaddlePaddle版本：1.5
    2）系统环境：Mac

请问在executor.run时，如何删除内存中的program_issue

**Comment by zhhsplendid** [comment]
什么叫删除内存中的program_issue呢？

**Comment by topxxuki** [comment]
> 什么叫删除内存中的program_issue呢？

program_cache

**Comment by zhhsplendid** [comment]
use_program_cache是run时的一个参数，默认就是False的。你看看你变量设为False就删了（甚至根本没存）
