### ISSUE TITLE
The protobuf 3.1.0 cause a warning in MacOS building

### ISSUE THREAD

**Issue by reyoung** [PaddlePaddle/Paddle#1936]
The Protobuf's issue is [here](https://github.com/google/protobuf/issues/2182).

Because Paddle treats all warnings as errors, so it will cause Paddle building failed in MacOS. Maybe we should upgrade Paddle's protobuf to 3.2.0.

**Comment by gongweibao** [comment]
Close it since not activate.
Feel free to reopen it.
