### ISSUE TITLE
CPU的预测调用是否需要释放。下面代码跑一下就因为内存不够异常退出

### ISSUE THREAD

**Issue by qingwuzhu** [PaddlePaddle/Paddle#19400]
1）PaddlePaddle版本：cpu_avx_mkl1.5
    2）CPU：CPU版本
下面函数中体中tensor是否需要释放。？？？？
下在函数，在外面使用一个 for循环，当跑到1000次左右，就因为机器没有内存异常退出，运行过程中可以明显看出内存在减少。
for(int i=0;i < 10000; i ++)
 ocrFrCellOrientation("\dateset",  batchData, 1, 32,400)
    
函数体如下：
    int ocrFrCellOrientation(const std::string &model_path,  const float *batchData, int batchsize, int img_width,
                             int img_height) {

        // 1. 创建NativeConfig
        paddle::NativeConfig config;
        config.use_gpu = false;
        config.SetCpuMathLibraryNumThreads(1);
        // 设置模型的参数路径
        config.prog_file  = model_path + "/a.net";
        config.param_file = model_path + "/a.p";
        // 当模型输入是多个的时候，这个配置是必要的。
        config.specify_input_name = true;

        auto predictor = CreatePaddlePredictor(config);

        // 3. 创建输入 tensor
        paddle::PaddleTensor tensor;
        tensor.name = "image";
        tensor.shape = std::vector<int>({batchsize, 1, img_height, img_width});
        tensor.data = paddle::PaddleBuf((void *)(batchData),
                                sizeof(float) * (batchsize * 1 * img_height * img_width));
        tensor.dtype = paddle::PaddleDType::FLOAT32;
        std::vector <paddle::PaddleTensor> paddle_tensor_feeds(1, tensor);

    		// 4. 创建输出 tensor
        std::vector <paddle::PaddleTensor> outputs;
        // 5. 预测
        CHECK(predictor->Run(paddle_tensor_feeds, &outputs, batchsize));
        CHECK_EQ(outputs.size(), 2UL);
        int count0 = 0,count180=0;
        const size_t num_elements = outputs.front().data.length() / sizeof(float);
        printf("num_elements=%d\n", num_elements);
        auto *data_out = static_cast<float *>(outputs.front().data.data());
        float* result = (float*)outputs.front().data.data();
      
        float a1 = *(result+i);

        predictor.release();
    }

**Comment by qingwuzhu** [comment]
补充一下堆栈：
Enforce failed. Expected posix_memalign(&p, alignment, size) == 0, but received posix_memalign(&p, alignment, size):12 != 0:0.
Alloc 524288000 error! at [/paddle/paddle/fluid/memory/detail/system_allocator.cc:57]
PaddlePaddle Call Stacks: 
0       0x7f0dccca5198p void paddle::platform::EnforceNotMet::Init<std::string>(std::string, char const*, int) + 392
1       0x7f0dcdaf5737p paddle::memory::detail::AlignedMalloc(unsigned long) + 295
2       0x7f0dcdaf59f7p paddle::memory::detail::CPUAllocator::Alloc(unsigned long*, unsigned long) + 39
3       0x7f0dcdaf656ap paddle::memory::detail::BuddyAllocator::RefillPool(unsigned long) + 58
4       0x7f0dcdaf6d7fp paddle::memory::detail::BuddyAllocator::Alloc(unsigned long) + 719
5       0x7f0dcdaf3815p void* paddle::memory::legacy::Alloc<paddle::platform::CPUPlace>(paddle::platform::CPUPlace const&, unsigned long) + 181
6       0x7f0dcdaf4545p paddle::memory::allocation::LegacyAllocator::AllocateImpl(unsigned long) + 405
7       0x7f0dcd6f33a3p paddle::memory::allocation::AllocatorFacade::Alloc(boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&, unsigned long) + 227

**Comment by MRXLT** [comment]
你好，可以尝试在预测完成后手动释放输入输出tensor

**Comment by qingwuzhu** [comment]
predictor 这个怎么释放，我发现每次退出后，这个占用的内存不会释放。

**Comment by fc500110** [comment]
不需要release吧

**Comment by fc500110** [comment]
> predictor 这个怎么释放，我发现每次退出后，这个占用的内存不会释放。

智能指针是自动管理内存的，release释放了指针所有权，会造成内存泄漏

**Comment by qingwuzhu** [comment]
即使是去掉下面的release   语句
    predictor.release();
程序也一样内存泄露，我们将函数改为这样
int ocrFrCellOrientation(const std::string &model_path, const float *batchData, int batchsize, int img_width,
int img_height) {
    // 1. 创建NativeConfig
    paddle::NativeConfig config;
    config.use_gpu = false;
    config.SetCpuMathLibraryNumThreads(1);
    // 设置模型的参数路径
    config.prog_file  = model_path + "/a.net";
    config.param_file = model_path + "/a.p";
    // 当模型输入是多个的时候，这个配置是必要的。
    config.specify_input_name = true;

    auto predictor = CreatePaddlePredictor(config);
｝
  只创建predictor ，就退出，一样内在汇露严重，说明 predictor 里面自己管理的内存没有释放。请问应该怎么办？
