### ISSUE TITLE
文档"设置命令行参数"的修改

### ISSUE THREAD

**Issue by luotao1** [PaddlePaddle/Paddle#1940]
修改原因：使用v2 api后，不再使用`paddle train`来调用命令行参数。这些参数中的某些在`paddle init`中能继续使用，但另外一部分就已经失效了。

修改文件：有三个中文文件
- [使用案例](https://github.com/PaddlePaddle/Paddle/blob/develop/doc/howto/usage/cmd_parameter/use_case_cn.md)
- [参数概述](https://github.com/PaddlePaddle/Paddle/blob/develop/doc/howto/usage/cmd_parameter/arguments_cn.md)
- [细节描述](https://github.com/PaddlePaddle/Paddle/blob/develop/doc/howto/usage/cmd_parameter/detail_introduction_cn.md)

网页链接：develop分支的[设置命令行参数](http://www.paddlepaddle.org/develop/doc_cn/howto/usage/cmd_parameter/index_cn.html)

**Comment by joodo** [comment]
@kuke 链接失效

**Comment by shanyi15** [comment]
@joodo  您好，请参考：
官网文档：
http://www.paddlepaddle.org/docs/develop/documentation/zh/howto/cmd_parameter/index_cn.html
github位置：
https://github.com/PaddlePaddle/Paddle/tree/develop/doc/v2/howto/cmd_parameter
