### ISSUE TITLE
fleet模式大embedding，pserver报错

### ISSUE THREAD

**Issue by Yelrose** [PaddlePaddle/Paddle#19401]
![image](https://user-images.githubusercontent.com/5746283/63632397-b27d5480-c667-11e9-8138-0dc13587c697.png)

embedding_size是 (14262238, 128), is_sparse=True， 似乎是14262238*128*4 > max_int

**Comment by Yelrose** [comment]
非pserver模式不会报错

**Comment by MRXLT** [comment]
你好，可以贴一下trainer.py的配置信息以及组网中emdedding相关的信息吗

**Comment by Yelrose** [comment]
```
part_embedding = fluid.layers.embedding(
            input=input,
            size=(14262238,  128),
            is_sparse=True,
            is_distributed=False,
        )
```
我这边自己定位了一下，应该是grpc那边的问题，embedding buffer不能超过uint32, 14262238x128x4=73,022,366,368。这个问题可以修复吗？

**Comment by Yelrose** [comment]
使用is_distributed=False，主要是is_distributed=True下fluid.layers.AdamOptimizer的收敛有问题。

**Comment by MRXLT** [comment]
有两种解决方案：
1、多启用几个trainer与pserver，这里的embedding buffer对单个节点来说太大了
2、使用is_distributed=True，但这里会使用SGD而不是adam，所以需要调节学习率
