### ISSUE TITLE
文档“基本使用概念”的修改

### ISSUE THREAD

**Issue by luotao1** [PaddlePaddle/Paddle#1941]
修改原因：
- 配置示例是基于v1 api，需要修改成v2 api。
- 很多基本概念，如`PyDataProvider2`，在v2 api发布后，需要进行删减或重新撰写。等。
- 分布式训练：原先是采用mpi集群的方式进行描述的，现在也需进行更新。

修改文件：一个中文文件
- [基本使用概念](https://github.com/PaddlePaddle/Paddle/blob/develop/doc/howto/usage/concepts/use_concepts_cn.rst)

网页链接：develop分支的[基本使用概念](http://www.paddlepaddle.org/develop/doc_cn/howto/usage/concepts/use_concepts_cn.html)

**Comment by QiJune** [comment]
目前新手入门部分的文档只有一个编译安装文档，缺乏一个对paddle(基于v2 api)如何进行训练预测任务的说明。在这里可以参考TensorFlow[入门文档](https://www.tensorflow.org/get_started/get_started) 的写作。首先简单介绍paddle中如表示输入数据，定义网络，训练模型；然后给一个线性回归的例子进行说明。
在进阶指南里面可以讲分布式训练，更高级的网络结构，如何优化等。建议把基本使用概念从进阶指南移到新手入门，并进行修改。

**Comment by luotao1** [comment]
同意将“基本使用概念”挪到“新手入门”下面，标题名也可以修改。

> 然后给一个线性回归的例子进行说明

因为book中有线性回归的章节，这里可以讲简单点，然后给个链接。

**Comment by Canpio** [comment]
Close this issue for related PR has been merge.
