### ISSUE TITLE
希望fluid.io.save_inference_model等save方法能支持设置描述信息

### ISSUE THREAD

**Issue by xymyeah** [PaddlePaddle/Paddle#19428]
希望fluid.io.save_inference_model等save方法能支持设置描述（备注）信息，string类型，可以将准确率、loss等效果数据写入到描述信息中，便于后续根据描述信息就能知道模型的效果等数据，也便于模型仓库的对接时直接能读取到该描述（备注）信息

**Comment by bjjwwang** [comment]
感谢建议 ，正在讨论中。

**Comment by lgone2000** [comment]
如果只是保存信息，可以在save前，把描述加到 第一个op的属性里面。
program.block(0).ops[0]._set_attr('modelinfo', 'model1.0')
print program.block(0).ops[0].attr('modelinfo')

**Comment by xymyeah** [comment]
> 如果只是保存信息，可以在save前，把描述加到 第一个op的属性里面。
> program.block(0).ops[0]._set_attr('modelinfo', 'model1.0')
> print program.block(0).ops[0].attr('modelinfo')

这样的话，是需要先load模型才能读取信息，
场景可能是这样的：训练一个10轮的模型，当时训练时通过日志可以知道哪一轮的效果，但是过一段时间之后，日志可能已经丢失了，如果有这样一个mode_info，其保存在模型文件夹中或者跟模型同名的文件，就可以直接就能看到相关的信息
