### ISSUE TITLE
文档“运行分布式训练”的修改

### ISSUE THREAD

**Issue by luotao1** [PaddlePaddle/Paddle#1942]
修改原因：使用v2 api后，用mpi集群训练作业的方式也发生了变化，相应的文档内容和标题也需改变。另外，因为我们有Kubernetes的文档，所以建议这篇标题为“MPI分布式训练”。

修改文件：一个中文文件
- [运行分布式训练](https://github.com/PaddlePaddle/Paddle/blob/develop/doc/howto/usage/cluster/cluster_train_cn.md)

网页链接：develop分支的[运行分布式训练](http://www.paddlepaddle.org/develop/doc_cn/howto/usage/cluster/cluster_train_cn.html)

**Comment by Yancey1989** [comment]
v2 api在Kubernetes集群训练还在开发中，PR: #1906

**Comment by typhoonzero** [comment]
现在的例子我理解是使用fabric和脚本在集群上分别启动pserver和trainer的，需要增加使用OpenMPI还是沿用现在的fabric的方式呢？

**Comment by typhoonzero** [comment]
已和 @luotao1 沟通，考虑到现在还没有文档 详细描述pserver和trainer的启动方式的，在这里着重描述分布式训练的启动和配置方式，简单介绍可以使用fabric或mpi管理工具来管理集群，而不详细展开。
