### ISSUE TITLE
Fleet分布式保存0号机和1号机保存参数权值diff很大

### ISSUE THREAD

**Issue by githubutilities** [PaddlePaddle/Paddle#19439]
利用fleet transpiler模式分布式训练的时候，利用`fluid.save_persistable`方法保存模型参数，
0号机保存的权值和1号机保存的权值diff很大
有以下两个问题：
1. 如何保存参数，以哪台机子为准
2. 如何利用保存参数做分布式预测

**Comment by hong19860320** [comment]
@seiriosPlus 帮忙解答下哈

**Comment by seiriosPlus** [comment]
1. 0号trainer保存参数。
2.目前paddle fluid没有提供明确的分布式预测方法， 如果要分布式预测，建议以每个节点把数据切分，分别做单机预测。

**Comment by hong19860320** [comment]
@githubutilities Hi 能解决你的问题吗？解决了帮忙把issue关闭哈^^

**Comment by githubutilities** [comment]
那0号机和1号机参数有不同是什么问题，pserver是有特殊的参数同步机制么？

**Comment by seiriosPlus** [comment]
> 那0号机和1号机参数有不同是什么问题，pserver是有特殊的参数同步机制么？

ps会诊对训练做很多优化，不同Trainer上的参数可能会有diff。
