### ISSUE TITLE
文档“单双层RNN API对比介绍”

### ISSUE THREAD

**Issue by luotao1** [PaddlePaddle/Paddle#1943]
修改原因：文中使用的示例都是基于v1 api的，需要改成v2 api格式，同时需要将对应的单测示例代码改成v2 api，并保证单测正确。

修改文件：一个中文文件+6个单测示例代码
- [单双层RNN API对比介绍](https://github.com/PaddlePaddle/Paddle/blob/develop/doc/howto/deep_model/rnn/hrnn_rnn_api_compare_cn.rst)
- [sequence_layer_group.conf](https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/gserver/tests/sequence_layer_group.conf)
- [sequence_nest_layer_group.conf](https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/gserver/tests/sequence_nest_layer_group.conf)
- [sequence_rnn.conf](https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/gserver/tests/sequence_rnn.conf)
- [sequence_nest_rnn.conf](https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/gserver/tests/sequence_nest_rnn.conf)
- [sequence_rnn_multi_unequalength_inputs.py](https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/gserver/tests/sequence_rnn_multi_unequalength_inputs.py)
- [sequence_nest_rnn_multi_unequalength_inputs.conf](https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/gserver/tests/sequence_nest_rnn_multi_unequalength_inputs.conf)

网页链接：develop分支的[单双层RNN API对比介绍](http://www.paddlepaddle.org/develop/doc_cn/howto/deep_model/rnn/hrnn_rnn_api_compare_cn.html)

**Comment by luotao1** [comment]
@lcy-seso 已认领。

**Comment by emailweixu** [comment]
Some of the description about recurrent_group is outdated. For example, in [单双层RNN API对比介绍](http://www.paddlepaddle.org/docs/develop/documentation/zh/howto/deep_model/rnn/hrnn_rnn_api_compare_cn.html), targetInLink is mentioned which is deprecated. Also at [双层RNN的使用](http://www.paddlepaddle.org/docs/develop/documentation/zh/howto/deep_model/rnn/recurrent_group_cn.html#permalink-4--rnn-), it lists the restrictions on the sequence types of the inputs to recurrent_groups. There is more restrictions. See the example at paddle/gserver/tests/sequence_rnn_mixed_inputs.py and paddle/gserver/tests/sequence_rnn_matched_inputs.py

**Comment by huiyingl** [comment]
"需要注意的是PaddlePaddle目前只支持子序列数目一样的多输入双层RNN。例如本例中的两个特征，均有三个子序列。每个子序列长度可以不一致，但是子序列的数目必须一样。"
这是教程上的写的。如果我的句子输入由每个词的 char ids 组成 (e.g. I eat it -> [[12], [21, 33, 4], [42, 4]])，那么句子中包含词的个数必须一样多？ 一般句子长度都不一样，那么是要手动padding吗？
