### ISSUE TITLE
关于paddle v2中的paddle.trainer.SGD详细解释

### ISSUE THREAD

**Issue by lizhiqings** [PaddlePaddle/Paddle#19437]
paddle v2 中的 paddle.trainer.SGD(cost=cost_layer_multi,parameters=param...)，如果cost_layer_multi是一个list 包含多个loss（模型是一个多目标），是怎么处理的 ，直接把cost_layer_multi中所有loss 都进行 权值为1 线性加权么？

**Comment by hong19860320** [comment]
是的，在v2版本里面，trainer只能接受一个cost，如果是多个cost，可以考虑线性加权，例如：
cost_sum = paddle.layer.add_to(cost_a, cost_b)

具体可以参考issue: https://github.com/PaddlePaddle/Paddle/issues/1757
