### ISSUE TITLE
[中文数据集情感分析] 在预处理我的中文数据集以后，运行train.sh脚本进行训练，出现段错误。请问如何解决？十分感谢！

### ISSUE THREAD

**Issue by Mr-quan** [PaddlePaddle/Paddle#1944]
错误显示如下：

root@caffe:~/paddlepaddle/paddle/demo/sentiment# sh train.sh
I0428 08:17:43.295579   763 Util.cpp:155] commandline: /usr/bin/../opt/paddle/bin/paddle_trainer --config=trainer_config.py --save_dir=./model_output --job=train --use_gpu=false --trainer_count=4 --num_passes=10 --log_period=10 --dot_period=20 --show_parameter_stats_period=100 --test_all_data_in_one_period=1 
I0428 08:17:43.295797   763 Util.cpp:130] Calling runInitFunctions
I0428 08:17:43.296051   763 Util.cpp:143] Call runInitFunctions done.
[INFO 2017-04-28 08:17:43,550 networks.py:1466] The input order is [word, label]
[INFO 2017-04-28 08:17:43,550 networks.py:1472] The output order is [__cost_0__]
I0428 08:17:43.552901   763 Trainer.cpp:170] trainer mode: Normal
*** Aborted at 1493367463 (unix time) try "date -d @1493367463" if you are using GNU date ***
PC: @           0x76e252 paddle::Weight::Weight()
*** SIGSEGV (@0xa8) received by PID 763 (TID 0x7f1c4d6be780) from PID 168; stack trace: ***
    @     0x7f1c4cfb3330 (unknown)
    @           0x76e252 paddle::Weight::Weight()
    @           0x5a3ec9 paddle::TableProjection::TableProjection()
    @           0x5a44b3 _ZNSt17_Function_handlerIFPN6paddle10ProjectionENS0_16ProjectionConfigESt10shared_ptrINS0_9ParameterEEbEZNS0_14ClassRegistrarIS1_JS3_S6_bEE13registerClassINS0_15TableProjectionEEEvRKSsEUlS3_S6_bE_E9_M_invokeERKSt9_Any_dataS3_S6_b
    @           0x5865e7 paddle::Projection::create()
    @           0x5d841a paddle::MixedLayer::init()
    @           0x62ecaf paddle::NeuralNetwork::init()
    @           0x64d982 paddle::MultiGradientMachine::MultiGradientMachine()
    @           0x6513ee paddle::GradientMachine::create()
    @           0x67c3e8 paddle::TrainerInternal::init()
    @           0x678b3e paddle::Trainer::init()
    @           0x5132a9 main
    @     0x7f1c4b3a4f45 (unknown)
    @           0x51f2a5 (unknown)
    @                0x0 (unknown)
/usr/bin/paddle: line 109:   763 Segmentation fault      (core dumped) ${DEBUGGER} $MYDIR/../opt/paddle/bin/paddle_trainer ${@:2}

**Comment by reyoung** [comment]
请确认您的数据没有问题。。

特别是，返回的词ID是不是大于字典大小？

**Comment by Mr-quan** [comment]
十分感谢您的提醒，我想是我的数据预处理以后得到的数据有问题。
想请问您，用jieba分词工具替代sentiment样例中mose工具后，preprocess.py运行后会有编码错误。
我是在save_dict和save_data两个函数中，创建文件方式改成，f = codecs.open(filename, 'w', 'utf-8')
这样处理以后就不会有编码错误了，但生成的数据似乎是乱码。
请问这种情况该如何解决呢？

**Comment by Mr-quan** [comment]
您好，可能是我的数据处理有问题，我请问您中文数据该如何处理（情感分析那个demo是英文的数据集），中间文件是ascii编码的

**Comment by Yancey1989** [comment]
Close the inactive issue, please reopen it if any update.
