### ISSUE TITLE
docker里编译时出现Unknown CMake command "cc_library".错误

### ISSUE THREAD

**Issue by MornJ** [PaddlePaddle/Paddle#19446]
我使用的时latest-dev版本的docker，paddle版本1.5
_ 57c9afb13299 /home/xji/PaddlePaddle/Paddle/paddle/build {release/1.5} cmake .. -DPY_VERSION=2.7 -DWITH_GPU=ON -DWITH_TESTING=OFF -DCMAKE_BUILD_TYPE=Release
-- The C compiler identification is GNU 4.8.5
-- The CXX compiler identification is GNU 4.8.5
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Error at fluid/memory/detail/CMakeLists.txt:1 (cc_library):
  Unknown CMake command "cc_library".

CMake Warning (dev) in CMakeLists.txt:
  No cmake_minimum_required command is present.  A line of code such as

    cmake_minimum_required(VERSION 3.5)

  should be added at the top of the file.  The version specified may be lower
  if you wish to support older CMake versions for this project.  For more
  information run "cmake --help-policy CMP0000".
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Configuring incomplete, errors occurred!
See also "/home/xji/PaddlePaddle/Paddle/paddle/build/CMakeFiles/CMakeOutput.log".

**Comment by hong19860320** [comment]
感觉像是cmake版本不多，你在docker里面用$cmake --version看看cmake的版本是多少?
建议使用我们官网首页的docker https://www.paddlepaddle.org.cn/start

**Comment by MornJ** [comment]
> 的

_ efdec6cf403e /home cmake --version
cmake version 3.5.1

CMake suite maintained and supported by Kitware (kitware.com/cmake).

cmake应该是这个docker里面自带的

**Comment by JiabinYang** [comment]
请在`Paddle/`目录下建立build目录执行cmake，参考官网的说明https://www.paddlepaddle.org.cn/documentation/docs/zh/1.5/beginners_guide/install/compile/compile_Ubuntu.html#permalink-6--docker-
