### ISSUE TITLE
load_persistables报错：not allowed to load partial data via load_combine_op

### ISSUE THREAD

**Issue by nizihan** [PaddlePaddle/Paddle#19458]
- 版本、环境信息：
    1）PaddlePaddle版本：1.5.0
    2）GPU：CUDA 8.0 和CUDNN 7

训练时采用fluid.io.save_persistables存储模型，finetune时采用fluid.io.load_persistables(exe, args.init_model_dir, filename=args.init_model_filename)报错：

报错信息：
C++ Callstacks: 
You are not allowed to load partial data via load_combine_op, use load_op instead. at [/paddle/paddle/fluid/operators/load_combine_op.h:100]
PaddlePaddle Call Stacks: 
0       0x7f2551780e10p void paddle::platform::EnforceNotMet::Init<char const*>(char const*, char const*, int) + 352
1       0x7f2551781189p paddle::platform::EnforceNotMet::EnforceNotMet(std::__exception_ptr::exception_ptr, char const*, int) + 137
2       0x7f255241a75fp paddle::operators::LoadCombineOpKernel<paddle::platform::CUDADeviceContext, float>::LoadParamsFromBuffer(paddle::framework::ExecutionContext const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&, std::istream*, bool, std::vector<std::string, std::allocator<std::string> > const&) const + 1903
3       0x7f255241aacep paddle::operators::LoadCombineOpKernel<paddle::platform::CUDADeviceContext, float>::Compute(paddle::framework::ExecutionContext const&) const + 798
4       0x7f255241af43p std::_Function_handler<void (paddle::framework::ExecutionContext const&), paddle::framework::OpKernelRegistrarFunctor<paddle::platform::CUDAPlace, false, 0ul, paddle::operators::LoadCombineOpKernel<paddle::platform::CUDADeviceContext, float>, paddle::operators::LoadCombineOpKernel<paddle::platform::CUDADeviceContext, double>, paddle::operators::LoadCombineOpKernel<paddle::platform::CUDADeviceContext, int>, paddle::operators::LoadCombineOpKernel<paddle::platform::CUDADeviceContext, signed char>, paddle::operators::LoadCombineOpKernel<paddle::platform::CUDADeviceContext, long> >::operator()(char const*, char const*, int) const::{lambda(paddle::framework::ExecutionContext const&)#1}>::_M_invoke(std::_Any_data const&, paddle::framework::ExecutionContext const&) + 35
5       0x7f25537f71a7p paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&, paddle::framework::RuntimeContext*) const + 375
6       0x7f25537f7581p paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&) const + 529
7       0x7f25537f4b7cp paddle::framework::OperatorBase::Run(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&) + 332
8       0x7f255190cafep paddle::framework::Executor::RunPreparedContext(paddle::framework::ExecutorPrepareContext*, paddle::framework::Scope*, bool, bool, bool) + 382
9       0x7f255190fb9fp paddle::framework::Executor::Run(paddle::framework::ProgramDesc const&, paddle::framework::Scope*, int, bool, bool, std::vector<std::string, std::allocator<std::string> > const&, bool) + 143
10      0x7f255177229dp
11      0x7f25517b3d36p
12      0x7f259eb55fa4p PyEval_EvalFrameEx + 35060
13      0x7f259eb56c3ep PyEval_EvalCodeEx + 2206
14      0x7f259eb561f7p PyEval_EvalFrameEx + 35655
15      0x7f259eb56c3ep PyEval_EvalCodeEx + 2206
16      0x7f259eb561f7p PyEval_EvalFrameEx + 35655
17      0x7f259eb56c3ep PyEval_EvalCodeEx + 2206
18      0x7f259eb561f7p PyEval_EvalFrameEx + 35655
19      0x7f259eb56c3ep PyEval_EvalCodeEx + 2206
20      0x7f259eb561f7p PyEval_EvalFrameEx + 35655
21      0x7f259eb56c3ep PyEval_EvalCodeEx + 2206
22      0x7f259eb561f7p PyEval_EvalFrameEx + 35655
23      0x7f259eb56c3ep PyEval_EvalCodeEx + 2206
24      0x7f259eb561f7p PyEval_EvalFrameEx + 35655
25      0x7f259eb56345p PyEval_EvalFrameEx + 35989
26      0x7f259eb56c3ep PyEval_EvalCodeEx + 2206
27      0x7f259eb56d52p PyEval_EvalCode + 50
28      0x7f259eb77450p PyRun_FileExFlags + 176
29      0x7f259eb7762fp PyRun_SimpleFileExFlags + 239
30      0x7f259eb8cfd4p Py_Main + 3236
31        0x38bfc21b45p __libc_start_main + 245
32            0x400729p

**Comment by hong19860320** [comment]
麻烦@DogHeadMoon 帮忙看看哈

**Comment by DogHeadMoon** [comment]
请确认save_persistables和load_persistables函数参数设置的filename是否一致？

**Comment by DogHeadMoon** [comment]
如果调用save_persistables仅设置了dir参数、没设置filename参数，而load_persistables设置了filename参数会出现这个错误的，所以请用户排查这对函数的filename参数设置是否正确
