### ISSUE TITLE
arg_max op 不支持 float16 类型

### ISSUE THREAD

**Issue by nbcc** [PaddlePaddle/Paddle#19451]

**Comment by hong19860320** [comment]
可以支持的，下面分别给出了动态图、静态图模式下的示例代码：

动态图示例
import paddle.fluid as fluid
import numpy as np

x_array = np.array([2, 4, 1, 4, 6, 3, 8, 7], dtype="int16")
x_ndarray = np.ndarray(shape=(4, 2), dtype="int16", buffer=x_array)
print(x_ndarray)

with fluid.dygraph.guard():
    x_var = fluid.dygraph.base.to_variable(x_ndarray)
    ret = fluid.layers.argmax(x_var, axis=1)
    print(ret.numpy())

静态图示例
import paddle.fluid as fluid
x = paddle.fluid.layers.data(name="x", shape=[3, 4], dtype="int16")
ret = paddle.fluid.layers.argmax(x, axis=0)

**Comment by nbcc** [comment]
> 可以支持的，下面分别给出了动态图、静态图模式下的示例代码：
> 
> 动态图示例
> import paddle.fluid as fluid
> import numpy as np
> 
> x_array = np.array([2, 4, 1, 4, 6, 3, 8, 7], dtype="int16")
> x_ndarray = np.ndarray(shape=(4, 2), dtype="int16", buffer=x_array)
> print(x_ndarray)
> 
> with fluid.dygraph.guard():
> x_var = fluid.dygraph.base.to_variable(x_ndarray)
> ret = fluid.layers.argmax(x_var, axis=1)
> print(ret.numpy())
> 
> 静态图示例
> import paddle.fluid as fluid
> x = paddle.fluid.layers.data(name="x", shape=[3, 4], dtype="int16")
> ret = paddle.fluid.layers.argmax(x, axis=0)

<img width="803" alt="图片" src="https://user-images.githubusercontent.com/864331/63926722-e3ea8b80-ca7e-11e9-8b86-09f041645b82.png">
