### ISSUE TITLE
文档“FAQ”的修改

### ISSUE THREAD

**Issue by luotao1** [PaddlePaddle/Paddle#1945]
修改原因：FAQ中的一些问题来自v1 api，需要对应逐条考虑是直接删除还是相应修改成v2 api。

修改文件：一个中文文件
- [FAQ](https://github.com/PaddlePaddle/Paddle/blob/develop/doc/faq/index_cn.rst)

网页链接：develop分支的[FAQ](http://www.paddlepaddle.org/develop/doc_cn/faq/index_cn.html)

**Comment by lcy-seso** [comment]
旧版本文档目前已删除，遂close 此issue。
