### ISSUE TITLE
“如何写新的C++ OP” 手册问题

### ISSUE THREAD

**Issue by CerrieJ** [PaddlePaddle/Paddle#19454]
踩坑编译OP后的一点建议:
官方手册链接 
: https://paddlepaddle.org.cn/documentation/docs/zh/1.5/advanced_usage/development/new_op/new_op.html
paddle版本：1.5.1
环境：ubuntu/docker/cpu

手册中 ”概念介绍“ 写到新增op的源码路径如下：
![image](https://user-images.githubusercontent.com/15920960/63750155-7d7b3700-c8df-11e9-84d1-f181f53ce311.png)

手册中 ”编译“ 部分写到：
![image](https://user-images.githubusercontent.com/15920960/63750309-d054ee80-c8df-11e9-9442-6748783a3080.png)

问题一： 按照手册理解即在目录paddle/fluid/operators(假设此路径中的”paddle"文件夹所在路径为当前路径)下 执行 make mul_op ， 但经过踩坑后发现是需要去到 ../build/paddle/fluid/operators下执行make命令
建议这部分能描述清楚一点

问题二：“实现单元测试/编译和执行“ 中写到:
![image](https://user-images.githubusercontent.com/15920960/63750996-27a78e80-c8e1-11e9-84f5-d1926d976bc3.png)
但是从整个文件结构看到，新增的Op的编译测试也是需要cmake整个工程的吧~~  我看上去是这样的，这样操作的话，新增一个op还是比较麻烦的哦，在测试这个op的过程中可能需要编译很多次~~ 尤其如果没有梯子，cmake的过程真的好多包都下不下来~~

最后，希望新增op整体的文档说明更清晰点，让新用户避免踩坑。
另外，之前在手册中看到过错别字，已经忘记位置了，只能你们检查一下

以上几点是我作为paddle初学者的一点建议，如果有不对的地方请指正！

**Comment by lgone2000** [comment]
新增op可以用custom op动态加载的方式，这种可以脱离框架单独编译，相关代码还没合入。可以关注这个pr
https://github.com/PaddlePaddle/Paddle/pull/19256/files#diff-c9f96ccb28613b7efbb83c320448ef7d
