### ISSUE TITLE
Training getting stuck randomly at some point

### ISSUE THREAD

**Issue by prakharg24** [PaddlePaddle/Paddle#19461]
I am trying to replicate the training from here ->

https://github.com/PaddlePaddle/models/tree/develop/PaddleCV/ssd

I have downloaded the latest COCO2017 dataset for the same and I am running train.py like this ->
```
python -u train.py --batch_size=64 --dataset=coco2017 --pretrained_model=../paddle/baseline_model/ --data_dir=../paddle/dataset/
```

Issue : After running completely for Epoch 0 and Epoch 1, during Epoch 2 it faces some issues. There is no error but the training slows down and then gets stuck at some random iteration.

For example,
At the start of epoch 0 ->
```
loading annotations into memory...
Done (t=15.59s)
```

At the start of epoch 1 ->
```
loading annotations into memory...
Done (t=15.41s)
```

But, at the start of epoch 2 ->
```
loading annotations into memory...
Done (t=378.15s)
```

During epoch 0 ->
```
Epoc 0, batch 1310, loss 4.074159, time 1.39149
Epoc 0, batch 1320, loss 4.691533, time 5.41378
Epoc 0, batch 1330, loss 4.654045, time 0.36061
Epoc 0, batch 1340, loss 4.792266, time 1.26742
Epoc 0, batch 1350, loss 4.606212, time 1.18089
Epoc 0, batch 1360, loss 4.391607, time 0.54399
```

During epoch 1 ->
```
Epoc 1, batch 440, loss 4.672965, time 0.36422
Epoc 1, batch 450, loss 4.618147, time 4.47600
Epoc 1, batch 460, loss 4.407829, time 2.84220
Epoc 1, batch 470, loss 4.673919, time 1.97023
Epoc 1, batch 480, loss 4.714933, time 0.31646
```

But, during epoch 2 ->
```
Epoc 2, batch 360, loss 4.637079, time 5.09779
Epoc 2, batch 370, loss 4.449667, time 2.16762
Epoc 2, batch 380, loss 4.684647, time 0.61157
Epoc 2, batch 390, loss 4.453241, time 62.54610
Epoc 2, batch 400, loss 4.338127, time 174.00809
Epoc 2, batch 410, loss 4.431243, time 478.00245
```

It actually gets so worse that I haven't been able to complete my Epoc 2 even after I leave it running for days.

The snippet of code that is actually running the loop ->
```
for epoc_id in range(epoc_num):
    train_reader = reader.train(data_args,
                                train_file_list,
                                batch_size_per_device,
                                shuffle=is_shuffle,
                                use_multiprocess=args.use_multiprocess,
                                num_workers=num_workers,
                                enable_ce=enable_ce)
    train_py_reader.decorate_paddle_reader(train_reader)
    epoch_idx = epoc_id + 1
    start_time = time.time()
    prev_start_time = start_time
    every_epoc_loss = []
    batch_id = 0
    train_py_reader.start()
    while True:
        try:
            prev_start_time = start_time
            start_time = time.time()
            if parallel: # I have also tried with parallel = False. Didn't change what was happening
                loss_v, = train_exe.run(fetch_list=[loss.name])
            else:
                loss_v, = exe.run(train_prog, fetch_list=[loss])
            loss_v = np.mean(np.array(loss_v))
            every_epoc_loss.append(loss_v)
            if batch_id % 10 == 0:
                print("Epoc {:d}, batch {:d}, loss {:.6f}, time {:.5f}".format(
                    epoc_id, batch_id, loss_v, start_time - prev_start_time))
            batch_id += 1
        except (fluid.core.EOFException, StopIteration):
            train_reader().close()
            train_py_reader.reset()
            break

    end_time = time.time()
    total_time += end_time - start_time
    if epoc_id % 1 == 0 or epoc_id == epoc_num - 1:
        best_map, mean_map = test(epoc_id, best_map)
        print("Best test map {0}".format(best_map))
        save_model(str(epoc_id), train_prog, True)
```

Any help on what might be causing this issue or how can I debug it will be helpful.

Thank You

**Comment by qingqing01** [comment]
`PaddleCV/ssd` uses Python multiprocess to process the data.  see `use_multiprocess=args.use_multiprocess` in `train()`.  How much CPU memory on your machine? And how many CPU cores?

**Comment by prakharg24** [comment]
@qingqing01  I am running my code on Titan Xp GPU, which has a memory of 12 GB and 3,840 CUDA cores.

Why would the memory or number for cores cause an issue later in the code? I mean if there was some issue of insufficient memory or similar, why would it run so smoothly for the first 2 epochs and then suddenly start showing problems in the third epoch?

Regardless, if you think that could be a problem, I will try to run it with use_multiprocess=False and see if that changes anything.

**Comment by qingqing01** [comment]
@prakharg24 I'm not sure why. If set `use_multiprocess=False`, traning is slow since the data preprocessing bottleneck.   Defalut use 8 multiprocess (see train.py) and buffer size is 1000 (in  https://github.com/PaddlePaddle/models/blob/develop/PaddleCV/ssd/reader.py#L321 ).

```
def multiprocess_reader(readers, use_pipe=True, queue_size=1000):
   # ...
```

What I asked you above is the CPU memory and  count. you can check by:

```
cat /proc/cpuinfo | grep MemTotal
cat /proc/cpuinfo | grep "physical id" | uniq | wc -l
```

If these are small, maybe can try reduce the num_workes in train.py and buffer size when calling multiprocess_reader.

**Comment by prakharg24** [comment]
@qingqing01 
```
cat /proc/cpuinfo | grep MemTotal
``` 
This gave no output

```
cat /proc/cpuinfo | grep "physical id" | uniq | wc -l
```
This gave output '1'

Without using grep, the output of 
```
cat /proc/cpuinfo
```

is ->
```
processor	: 0
vendor_id	: GenuineIntel
cpu family	: 6
model		: 60
model name	: Intel(R) Core(TM) i5-4460  CPU @ 3.20GHz
stepping	: 3
microcode	: 0x27
cpu MHz		: 3275.975
cache size	: 6144 KB
physical id	: 0
siblings	: 4
core id		: 0
cpu cores	: 4
apicid		: 0
initial apicid	: 0
fpu		: yes
fpu_exception	: yes
cpuid level	: 13
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm cpuid_fault epb invpcid_single pti ssbd ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid xsaveopt dtherm ida arat pln pts md_clear flush_l1d
bugs		: cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass l1tf mds swapgs
bogomips	: 6395.57
clflush size	: 64
cache_alignment	: 64
address sizes	: 39 bits physical, 48 bits virtual
power management:

processor	: 1
vendor_id	: GenuineIntel
cpu family	: 6
model		: 60
model name	: Intel(R) Core(TM) i5-4460  CPU @ 3.20GHz
stepping	: 3
microcode	: 0x27
cpu MHz		: 3305.775
cache size	: 6144 KB
physical id	: 0
siblings	: 4
core id		: 1
cpu cores	: 4
apicid		: 2
initial apicid	: 2
fpu		: yes
fpu_exception	: yes
cpuid level	: 13
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm cpuid_fault epb invpcid_single pti ssbd ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid xsaveopt dtherm ida arat pln pts md_clear flush_l1d
bugs		: cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass l1tf mds swapgs
bogomips	: 6395.57
clflush size	: 64
cache_alignment	: 64
address sizes	: 39 bits physical, 48 bits virtual
power management:

processor	: 2
vendor_id	: GenuineIntel
cpu family	: 6
model		: 60
model name	: Intel(R) Core(TM) i5-4460  CPU @ 3.20GHz
stepping	: 3
microcode	: 0x27
cpu MHz		: 3260.534
cache size	: 6144 KB
physical id	: 0
siblings	: 4
core id		: 2
cpu cores	: 4
apicid		: 4
initial apicid	: 4
fpu		: yes
fpu_exception	: yes
cpuid level	: 13
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm cpuid_fault epb invpcid_single pti ssbd ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid xsaveopt dtherm ida arat pln pts md_clear flush_l1d
bugs		: cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass l1tf mds swapgs
bogomips	: 6395.57
clflush size	: 64
cache_alignment	: 64
address sizes	: 39 bits physical, 48 bits virtual
power management:

processor	: 3
vendor_id	: GenuineIntel
cpu family	: 6
model		: 60
model name	: Intel(R) Core(TM) i5-4460  CPU @ 3.20GHz
stepping	: 3
microcode	: 0x27
cpu MHz		: 3396.297
cache size	: 6144 KB
physical id	: 0
siblings	: 4
core id		: 3
cpu cores	: 4
apicid		: 6
initial apicid	: 6
fpu		: yes
fpu_exception	: yes
cpuid level	: 13
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm cpuid_fault epb invpcid_single pti ssbd ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid xsaveopt dtherm ida arat pln pts md_clear flush_l1d
bugs		: cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass l1tf mds swapgs
bogomips	: 6395.57
clflush size	: 64
cache_alignment	: 64
address sizes	: 39 bits physical, 48 bits virtual
power management:
```

Does this make sense? Based on this, what do you think my queue_size and num_workers shoudl be?

Also, I am little confused on why are we talking about CPU memory and number of cores when my code is actually running on GPU?

**Comment by qingqing01** [comment]
All the data processing is on CPU. In SSD model, this is very time-consuming .  In order to speed, the Python multiprocess is used and put the processed data on buffer queue.  The data processing on CPU and training on CPU is asynchronous.  I worry about too much CPU resource ( including memory) is occupied, leads to the bottleneck of data processing. There is no problem in our machine, since a high CPU configuration.  (A colleague just checked this training last week. ) . Maybe you can change num_workers to 2 (or 4) and reduce queue_size to 512？ I'm not sure. You can try it.

```
cat /proc/cpuinfo | grep "physical id" | uniq | wc -l
18
cat /proc/meminfo | grep MemTotal
MemTotal:       247235640 kB
```

**Comment by prakharg24** [comment]
@qingqing01 Okay I will try with those specifications.

Just for the sake of a theoretical explanation, if the code works for lower number of workers/queue size (I don't know yet if it will), how do you explain that? I mean one batch was processed in around 0.5 seconds in epoch 0 while one batch in epoch 2 took a few hours. Does this imply that the data loader got stuck somewhere? How does reducing reducing the queue_size or number_of_workers help in that?

Thank You

**Comment by qingqing01** [comment]
> imply that the data loader got stuck somewhere?

Yeah.  From your paste above, only 4 CPU on your machine, But use 8 processes for data pre-processing.   This is not efficient.

**Comment by prakharg24** [comment]
@qingqing01  It worked!! With 4 workers and queue_size=512, the training is working smoothly.

For the sake of the issue, I guess it can be closed. But from a systems point of view, I am still not 100% clear on what happened.

Let me just be lay out what I understand. With only 4 CPUs, I was forcing my program to run 8 different processes. I guess that would mean that python would have automatically distributed 2 jobs per CPU. Is that right? I think for my program to behave the way it did, I feel like some sort of deadlock might have formed. But I have two issues with this explanation.

1. Is the backend code for multiprocessing in python written so poorly that just assigning more workers than number of cores crashed it? I don't think that should be the case
2. If it was getting in a deadlock, why always deterministic stopping on epoch 2. I mean I did multiple runs and it always got stuck in epoch 2. It didn't always get stuck in the same batch so maybe there is some non-determinism to it, but I think no good enough explanation if it was simply just a deadlock of some sorts.

P.S: The problem is resolved and the issue can be closed. I was just hoping to understand the problem a little better.

Thank You
