### ISSUE TITLE
分布式训练出来的模型，如何供单机加载预测

### ISSUE THREAD

**Issue by aturbofly** [PaddlePaddle/Paddle#19469]
分布式训练出来了一个模型，但是单机 load模型，执行预测的时候报grpc error。
有https://github.com/PaddlePaddle/Paddle/issues/18999 提到了解决的方法，我也尝试了，
的确用通过单机训练出来的模型里面的__model__ 替换掉分布式训练中的__model__就可以了。但感觉这样根本不能解决问题。能不能实现分布式训练出来的模型，单机直接就能加载并进行预测呢？？

**Comment by hong19860320** [comment]
麻烦@wangguibao帮忙解答下哦

**Comment by wangguibao** [comment]
https://github.com/PaddlePaddle/Paddle/issues/16360

这里有另一个解决方式，试一下看看？

同时请 @seiriosPlus 老师关注!~

**Comment by seiriosPlus** [comment]
使用Paddle FLUID 提供的分布式FleetAPI可以解决此类问题。

FleetAPI包含在1.5.1以后的版本或develop。
