### ISSUE TITLE
paddle不同op，对于 输出的name的处理方式不同，有的是加 .tmp_xx 有的不加

### ISSUE THREAD

**Issue by lgone2000** [PaddlePaddle/Paddle#19478]
paddle不同op，对于 输出的name的处理方式不同，有的是加 .tmp_xx 有的不加， qingqing说加tmp是标准的方式， 希望能改成一致。另外cast op不支持name 参数，希望能加上。

def testname():
    exe = fluid.Executor(fluid.CPUPlace())
    a = fluid.layers.data(name='input', shape=[3, 32, 32], dtype='float32')
    b = fluid.layers.data(name='input', shape=[3, 32, 32], dtype='float32')
    c = fluid.layers.elementwise_sub(a, b, name='sub')
    d = fluid.layers.elementwise_sub(b, a, name='sub')
    e = fluid.layers.fc(input=a, size=10, name='fc')
    f = fluid.layers.fc(input=a, size=10, name='fc')
    
    print a.name
    print b.name
    print c.name
    print d.name
    print e.name
    print f.name
    
输出
input
input
sub
sub
fc.tmp_1
fc.tmp_3

**Comment by wangchaochaohu** [comment]
这边会反馈改进的 谢谢
