### ISSUE TITLE
编译安装出错

### ISSUE THREAD

**Issue by shippingwang** [PaddlePaddle/Paddle#19473]
![image](https://user-images.githubusercontent.com/13645332/63774999-09598700-c911-11e9-991d-4f2f665211d4.png)

CUDA8 CUDNN7 Ubuntu16.04

**Comment by hong19860320** [comment]
从log上看，编译出来文件太大了，在压缩的时候zip包超过了2GB；这是python2.7 zlib的bug https://bugs.python.org/issue23306 ，建议在编译paddle时使用python3；

**Comment by shippingwang** [comment]
> 从log上看，编译出来文件太大了，在压缩的时候zip包超过了2GB；这是python2.7 zlib的bug https://bugs.python.org/issue23306 ，建议在编译paddle时使用python3；

看起来绕过了问题，python2不能解决么？

**Comment by songyouwei** [comment]
[zlib的这个issue](https://bugs.python.org/issue27130)已经在python2.7.13版本修复了，参见[python 2.7.13 release notes](https://hg.python.org/cpython/raw-file/v2.7.13/Misc/NEWS)

PaddlePaddle官网有说明，要求您的 Python 2 版本是 2.7.15+
