### ISSUE TITLE
模型库中有没有多任务学习的model

### ISSUE THREAD

**Issue by sshilei** [PaddlePaddle/Paddle#19490]
paddle模型库中有没有多任务学习的model，辛苦提供一下，谢谢。

**Comment by wangchaochaohu** [comment]
我们这边会反馈  后续考虑是否添加

**Comment by 0YuanZhang0** [comment]
paddle1.6版本中，我们会即将发布一个多任务学习的库；

**Comment by sshilei** [comment]
请问什么时候发布，另外develop版本中可以看到吗？ @wangchaochaohu  @0YuanZhang0

**Comment by 0YuanZhang0** [comment]
现在还没有合入develop版本，大概得到9月底可能才会发布。
