### ISSUE TITLE
动态图中great_than用不了

### ISSUE THREAD

**Issue by zehua9500** [PaddlePaddle/Paddle#19499]
`import numpy as np
import os 
import pandas as pd 
import paddle.fluid as fluid
import paddle 
import cv2
import json
import random
import time

with fluid.dygraph.guard():
    a = fluid.dygraph.to_variable(np.arange(3))
    b = fluid.dygraph.to_variable(np.arange(3))
    out = fluid.layers.greater_than(x=a, y=b)
    print(fluid.layers.elementwise_min(a,b))`

在AI studio上执行这段代码时，notebook会一直在转圈，也不报错

**Comment by wangchaochaohu** [comment]
@phlrain 麻烦看一下

**Comment by wangchaochaohu** [comment]
我这边在本地运行了一下代码 会出现segmentation fault的错误 ，但是去掉out = fluid.layers.greater_than(x=a, y=b)
能够正常原因 应该fluid.layers.greater_than的bug引起的 这边会反馈给动态图团队

**Comment by JiabinYang** [comment]
greater_than目前还不能支持，正在修复
