### ISSUE TITLE
C-API not ready for V2

### ISSUE THREAD

**Issue by emailweixu** [PaddlePaddle/Paddle#1949]
The examples in capi use paddle.utils.dump_config to generate binary model configuration. However dump_config cannot handle v2 model.

**Comment by hedaoyuan** [comment]
I also encountered this problem when deploying the model(from book) to the mobile device. My current practice is add a save to bin API for `Topology`, but need to modify the `train.py` file.

**Comment by emailweixu** [comment]
@hedaoyuan Please file an issue the next time when you encounter any problem

**Comment by hedaoyuan** [comment]
OK, I was trying to deploy a Demo to the mobile this week and found the problem.
