### ISSUE TITLE
level=2 的lod-tensor，在DynamicRNN中对它调用step_input()函数，在CPU上没问题，但是在GPU上报segment fault

### ISSUE THREAD

**Issue by Life-0-1** [PaddlePaddle/Paddle#19514]
一个level=2 的lod-tensor ，在DynamicRNN的block中对它调用step_input()函数，在CPU上运行没问题，但是在GPU上报segment fault。代码如下：
```
drnn = fluid.layers.DynamicRNN()
with drnn.block():
    x_ = drnn.step_input(x)  # 这里 x 是level=2的lod-tensor
```
报错信息如下：
![屏幕快照 2019-08-28 下午3 44 03](https://user-images.githubusercontent.com/14857750/63865080-8f460280-c9e3-11e9-9b39-513dc04129fd.png)

- 版本、环境信息：
    1）PaddlePaddle版本：1.3.0_gpu
    2）CPU：Xeon
    3）GPU：K40 or V100, CUDA 9.0和CUDNN 7.0
    4）系统环境：linux，Python 2.7
- 训练信息
    1）单卡，K40 OR V100
    2）显存信息
    3）Operator信息

**Comment by wangchaochaohu** [comment]
能提供下完整的复现代码吗？
