### ISSUE TITLE
Feature request: RAdam, LookAhead implement and combine them in one

### ISSUE THREAD

**Issue by parap1uie-s** [PaddlePaddle/Paddle#19516]
Is there any implementation plan for RAdam and LookAhead?

RAdam and LookAhead are two recently proposed optimization methods, with higher stability of the optimization process and enable faster convergence.

More over, there is a method about `combine RAdam and LookAhead` into one optimizer, implemented by fast.ai called `ranger`.

- [RAdam](https://arxiv.org/abs/1908.03265)
- [LookAhead](https://arxiv.org/abs/1907.08610)
- [fast.ai ranger](https://forums.fast.ai/t/meet-ranger-radam-lookahead-optimizer/52886): 
- [ a blog of ranger](https://medium.com/@lessw/new-deep-learning-optimizer-ranger-synergistic-combination-of-radam-lookahead-for-the-best-of-2dc83f79a48d)
- [Another blog of ranger](https://www.chainnews.com/articles/997888032240.htm)

----------------

PaddlePaddle是否有实现RAdam及LookAhead的开发计划？

RAdam和LookAhead是两种最近才提出的优化方法，据报告这些方法提升了训练稳定性，可以更快，也更好地让模型收敛。

进一步地，有一种将RAdam和LookAhead融合到一个优化器中的方法，目前fast.ai已有相关实现，被命名为ranger。

相关资料：
- [RAdam](https://arxiv.org/abs/1908.03265)
- [LookAhead](https://arxiv.org/abs/1907.08610)
- [fast.ai ranger](https://forums.fast.ai/t/meet-ranger-radam-lookahead-optimizer/52886): 
- [ 一篇关于ranger的blog](https://medium.com/@lessw/new-deep-learning-optimizer-ranger-synergistic-combination-of-radam-lookahead-for-the-best-of-2dc83f79a48d)
- [另一篇关于ranger的blog](https://www.chainnews.com/articles/997888032240.htm)

**Comment by mapingshuo** [comment]
We have implemented the Lookahead optimizer: https://github.com/PaddlePaddle/Paddle/pull/19386, and we plan to implement the RAdam optimizer as soon as possible.

**Comment by chunyisong** [comment]
什么时候能加入 Ranger发布新版本啊
