### ISSUE TITLE
b at front or a at front for baseMatrix.cu? 

### ISSUE THREAD

**Issue by pengwangucla** [PaddlePaddle/Paddle#1951]
For some math operation in baseMatrix.cu, I am quite confused about whether 'a' is at front or 'b' is at front in Binary Operation. 

For example 

for the square operation: 

```c++
DEFINE_MATRIX_BINARY_OP(Square, b = a * a);
template<class T>
void BaseMatrixT<T>::square2(BaseMatrixT& b) {
  applyBinary(binary::Square<T>(), b);
}
```

However for sqrt operation: 

```c++
DEFINE_MATRIX_BINARY_OP(Sqrt, a = sqrt(b));
template<>
void BaseMatrixT<real>::sqrt2(BaseMatrixT& b) {
  applyBinary(binary::Sqrt<real>(), b);
}
```

This will leads different results for  

```c++
a->square2(b) 
a->sqrt2(b)
```
the first one b = a^2, which we want to a = b^2,  the second one b = a^{1/2} 
Is there any need to fix this @qingqing01

**Comment by hedaoyuan** [comment]
`applyBinary` and `hl_gpu_apply_binary_op` only defined the order of the arguments(from a, b...), no define which is the output, which is the input. So, in the realization of BaseMatrix API, there will be differences. We consider moving these computationally related implementations to `Function`, which defines which argument is output and which arguments are input.

**Comment by hedaoyuan** [comment]
Close this issue, and we will reconstruct Matrix calculation by Eigen.
