### ISSUE TITLE
Where to put Go code

### ISSUE THREAD

**Issue by wangkuiyi** [PaddlePaddle/Paddle#1952]
In our recent discussion on PaddlePaddle Cloud, we are going to have more and more Go code. So, where should we put the code?  Some possibilities:

1. To create a directory `paddle/go` in the `paddlepaddle/paddle` repo, like there's a `tensorflow/go` directory in the `tensorflow/tensorlfow` repo.
1. To create a new repo for each Go package. For example `paddlepaddle/recordio`, so people can get the code via `go get -u github.com/paddlepaddle/recordio`.
1. To create a repo under `paddlepaddle` organization, eg., `paddlepaddle/go`.

Which one do you think should be our choice?

**Comment by gongweibao** [comment]
> To create a directory paddle/go in the paddlepaddle/paddle repo, like there's a tensorflow/go directory in the tensorflow/tensorlfow repo.

+1

When some of  the codes is reconstructed by golang in the future, the old code will disapear from paddlepaddle/paddle/。

**Comment by reyoung** [comment]
I think we could combine the first and the third options together.

I did not see the advantage of the second choice. The reasons are:

* We can use `go get -u github.com/someorg/somerepo/somemodule/somsublib`. So we can get code independently even we put all go sources into one repository.
* If we divide each module into one repository, there will be many repositories in our organization. These repositories are organized without hierarchies.

So we could create a repository in `paddlepaddle/go` (or maybe we should name it `parameter_server`?) and reference this repository as a `git submodule` into `paddlepaddle/Paddle` repository. The advantages of this design are:

* When split Paddle Core into two repositories, C++ part and go part. Developers who familiars with Go and Parameter Server, could not go so deep into C++ details. It could ease the communication and development in Paddle.
* We put go or parameter server part into `paddlepaddle/Paddle` as a submodule, it makes the Paddle's hierarchies clear.
* The go part and C++ part are two repositories, and they can have different compile toolchain, unit test framework, continues integration system. The Paddle develop branch could reference go release branch, so the code of golang could be flux right now.


In the future, I think we could split Paddle core repo into many pieces.  After compile C-API replace SWIG, Python code could be extracted into an independent repository, too.

**Comment by helinwang** [comment]
I vote for the 1st solution, reasons are as follow:

- Easy to modify code involving crossing language boundry (cross c++ and golang).
- Easy to do unit test for integration between c++ and golang.
- The repository will mostly always be in a good state. E.g., not in an intermediate state where submodule changed an interface but main repo is still behind.

Myself is favor of google's monolithic repository approach. Here is some discussion: https://news.ycombinator.com/item?id=10007654

**Comment by typhoonzero** [comment]
Vote for the 1st solution too.

Like v2 python API, the golang version of pserver can be considered as "v2" of the current pserver.

Then we can build all v1 and v2 binaries together to give users some time to deprecate their v1 code and move on to v2.
