### ISSUE TITLE
latest paddle在paddlecloud安装失败

### ISSUE THREAD

**Issue by anpark** [PaddlePaddle/Paddle#19528]
为使您的问题得到快速解决，在建立Issue前，请您先通过如下方式搜索是否有相似问题:【搜索issue关键字】【使用labels筛选】【官方文档】
latest-cpu-mkl/paddlepaddle-latest-cp27-cp27mu-linux_x86_64.whl
在paddlecloud pip install报错
Requirement already satisfied, skipping upgrade: setuptools in /usr/local/lib/python2.7/site-packages (from protobuf>=3.1.0->paddlepaddle==latest) (41.0.1)
Requirement already satisfied, skipping upgrade: singledispatch in /usr/local/lib/python2.7/site-packages (from nltk<=3.4,>=3.2.2; python_version < "3.5"->paddlepaddle==latest) (3.4.0.3)
Installing collected packages: paddlepaddle
  Found existing installation: paddlepaddle 1.5.1
    Uninstalling paddlepaddle-1.5.1:
      Successfully uninstalled paddlepaddle-1.5.1
ERROR: Could not install packages due to an EnvironmentError: [Errno 2] No such file or directory: '/tmp/pip-uninstall-b5vMgu/_foo.so'

建立issue时，为快速解决问题，请您根据使用情况给出如下信息：
- 标题：请包含关键词“安装错误”/“编译错误”，例如“Mac编译错误”
- 版本、环境信息：
    1）PaddlePaddle版本：latest paddle
    2）CPU：paddlecloud
    3）GPU：请提供GPU型号，CUDA和CUDNN版本号
    4）系统环境：请说明系统类型、版本（如Mac OS 10.14）、Python版本
- 安装方式信息：
1）pip安装
2）本地编译：请提供cmake命令，编译命令
3）docker编译：请提供docker镜像，编译命令            
  特殊环境请注明：如离线安装等
- 复现信息：如为报错，请给出复现环境、复现步骤
- 问题描述：请详细描述您的问题，同步贴出报错信息、日志/代码关键片段

Thank you for contributing to PaddlePaddle.
Before submitting the issue, you could search issue in Github in case that there was a similar issue submitted or resolved before.
If there is no solution,please make sure that this is an installation issue including the following details:
**System information**
-PaddlePaddle version （eg.1.1）or CommitID
-CPU: including CPUMKL/OpenBlas/MKLDNN version
-GPU: including CUDA/CUDNN version
-OS Platform (eg. Mac OS 10.14)
-Python version
- Install method: pip install/install with docker/build from source(without docker)/build within docker
- Other special cases that you think may be related to this problem, eg. offline install, special internet condition   
**To Reproduce**
Steps to reproduce the behavior
**Describe your current behavior**
**Code to reproduce the issue**
**Other info / logs**

**Comment by JiabinYang** [comment]
@JepsonWong plz help to check this

**Comment by JepsonWong** [comment]
您好，我拉取paddlecloud原始镜像没有复现这个问题。能提供一下复现步骤吗？

**Comment by anpark** [comment]
@JepsonWong paddlecloud  before_hook.sh: pip install paddle-latest 就可以的
