### ISSUE TITLE
ocr model (如attention ocr , ctc)训练时的超参数在哪修改?

### ISSUE THREAD

**Issue by wenston2006** [PaddlePaddle/Paddle#19531]

**Comment by qingqing01** [comment]
1. 通过 入口参数可以改batch size等超参数。
```
python train.py  --help
```
2. 数据相关在

https://github.com/PaddlePaddle/models/blob/develop/PaddleCV/ocr_recognition/data_reader.py#L34

3. 学些率、正则相关在

CTC： https://github.com/PaddlePaddle/models/blob/develop/PaddleCV/ocr_recognition/crnn_ctc_model.py#L187

Attention:  https://github.com/PaddlePaddle/models/blob/develop/PaddleCV/ocr_recognition/attention_model.py#L20


该模型的易用性会加强~

**Comment by wenston2006** [comment]
@qingqing01 谢谢
