### ISSUE TITLE
预测的时延较大

### ISSUE THREAD

**Issue by lexy0093** [PaddlePaddle/Paddle#19534]
网络结构：
        label = fluid.layers.data(name='label', shape=[1], dtype='int64', lod_level=0)
        index = fluid.layers.data(name='index', shape=[1], dtype='int64', lod_level=1)
        feature = fluid.layers.data(name='feature', shape=[1], dtype='float32', lod_level=1)

        droped = fluid.layers.dropout(x=feature, dropout_prob=self.dropout_prob)
        emb = fluid.layers.embedding(input=index, size=[self.vocab_dim, self.emb_dim], is_sparse=True)
        stk = fluid.layers.expand(feature, expand_times = [1, 256])
        mm = fluid.layers.elementwise_mul(x=emb, y=stk)
        mm_fc = fluid.layers.sequence_pool(input=mm, pool_type='sum')
        fc1 = fluid.layers.relu(x=mm_fc)

        fc2 = fluid.layers.fc(input=fc1, size=self.hid_dim, act='relu')
        pred = fluid.layers.fc(input=[fc1, fc2], size=self.class_dim, act='softmax')

时延分析：
![image](https://user-images.githubusercontent.com/10195109/63935594-6465b800-ca90-11e9-9aa7-462e228f7924.png)

目前分析来看 expand使用时延较多，不知道有没有替代方案或者是优化建议

**Comment by qingqing01** [comment]
麻烦看下能投通过指定 elementwise_mul的axis来broadcast做元素乘，而不用expand。

**Comment by lexy0093** [comment]
可以解决该问题，感谢！
