### ISSUE TITLE
如何提升预测时候的QPS？batch_size设置到50以上就容量不足报错

### ISSUE THREAD

**Issue by hallySEU** [PaddlePaddle/Paddle#19530]
如题：如何提升预测时候的QPS？有多少种方法

目前想采用提高batch_size来提升QPS，但是batch_size设置超过50就报容量不足的错误了。

![image](https://user-images.githubusercontent.com/25191684/63926129-e7c9de00-ca7d-11e9-8dc6-eef6713dc3ff.png)

**Comment by hallySEU** [comment]
背景任务是：两个句子判断逻辑是否是一致的（句子级别的二分类）
使用模型：ernie，20w数据 fine-tune

**Comment by hallySEU** [comment]
已用在线上，希望提高效率

**Comment by NHZlX** [comment]
有没有使用显存/内存优化功能呢
