### ISSUE TITLE
Tensor not initialized yet when Tensor::type() is called

### ISSUE THREAD

**Issue by liushanshan07** [PaddlePaddle/Paddle#19542]
0828 lastest paddle版本，python load inference model时
recurrent op的commit https://github.com/PaddlePaddle/Paddle/pull/17710 导致的Tensor not initialized yet when Tensor::type() is called

**Comment by zhhsplendid** [comment]
经过一些版本的实验，问题可能出在save/load模型过程，转人跟进

**Comment by zhhsplendid** [comment]
Fixed the problem by offline discussion. I will close this issue.
