### ISSUE TITLE
建议实现类似PyTorch里的ImageFolder的这么个接口

### ISSUE THREAD

**Issue by sndnyang** [PaddlePaddle/Paddle#19547]
我看了下文档里没有这么个接口， 这样的话， 不同人要读取imagenet之类的数据集时， 都得自己花费一点工夫去找别人的实现或自己实现一个有点复杂的reader。
PyTorch 的 imagefolder 就比较简单

```
train_dir = os.path.join(data_dir, 'train')
train_dataset = datasets.ImageFolder(train_dir, transforms.Compose(train_transforms))
```
大概两行就能完成一个 reader。

还有， 其他数据集接口  能不能我自行指定一个目录？
如上。

**Comment by luotao1** [comment]
感谢您的建议，我们会内部沟通评估下需求！

**Comment by sndnyang** [comment]
> 感谢您的建议，我们会内部沟通评估下需求！

@luotao1
