### ISSUE TITLE
save inference model剪枝时，错误的减掉rnn block里的op

### ISSUE THREAD

**Issue by liushanshan07** [PaddlePaddle/Paddle#19541]
如题，python inference 挂掉

**Comment by wanghaoshuang** [comment]
这个问题的根本原因是，通过rnn的output回溯不到rnn block内，所以误剪了某些op.

建议提供不做网络剪枝的选项。

在该case中，注释掉这一句即可：https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/fluid/io.py#L1083

**Comment by mapingshuo** [comment]
Prune函数对sub block的情况有处理啊：https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/fluid/framework/prune.cc#L125

@wanghaoshuang 为什么还是误裁了呢？
