### ISSUE TITLE
where is the statistic distribution package now?

### ISSUE THREAD

**Issue by leonleeldc** [PaddlePaddle/Paddle#19548]
原来paddle里面有个distributions的packages, 现在好像没有了，这个链接里的也没有，https://github.com/PaddlePaddle/Paddle/pull/18023. 那我们要用到statictical and probability的东西在哪里呢？tensorflow里面是有个类似的package也叫tf.distributions. 
我们可以调用tf.distributions.Categorical， tf.distributions.kl_divergence and tf.distributions.Normal之类的。

**Comment by luotao1** [comment]
#18023 是在7月5日merge的，不在release1.5里面。如果要使用，可以使用develop版本的whl包。https://www.paddlepaddle.org.cn/documentation/docs/zh/beginners_guide/install/Tables.html/#ciwhls

API接口是：paddle.fluid.layers.Normal，都在layers目录下。
