### ISSUE TITLE
Complete the release note of 0.10.0

### ISSUE THREAD

**Issue by reyoung** [PaddlePaddle/Paddle#1955]
We are finally releasing 0.10.0. Currently, the [release note](https://github.com/PaddlePaddle/Paddle/blob/release/0.10.0/RELEASE.md) was written by our developers. We use `git log --author=MySelf master..release/0.10.0` to get every commit logs by ourselves and summarize them into `features`, `improvements` and `bug fixes`.

But we need an abstraction or a complete summary of this release.

We release a prototype of Paddle V2 API. The API is experimental and will replace V1 API. So we should give a proper introduction of this API.

There also may be some other summary should be added into [release note](https://github.com/PaddlePaddle/Paddle/blob/release/0.10.0/RELEASE.md), and we should check English writing by the way.

**Comment by luotao1** [comment]
After finishing the English release note, we need a Chinese version which can be published in wechat platform.

**Comment by reyoung** [comment]
* English version of the release note is done.
