### ISSUE TITLE
transformer-xl GPU训练速度慢

### ISSUE THREAD

**Issue by dingsiyu** [PaddlePaddle/Paddle#19558]
为使您的问题得到快速解决，在建立Issues前，请您先通过如下方式搜索是否有相似问题:【搜索issue关键字】【使用labels筛选】【官方文档】

如果您没有查询到相似问题，为快速解决您的提问，建立issue时请提供如下细节信息：
- 标题：简洁、精准概括您的问题，例如“Insufficient Memory xxx" ”
- 版本、环境信息：
    1）PaddlePaddle版本：1.5.1
    3）GPU：P40、CUDA10.1和CUDNN7.4
    4）系统环境：centos6  python3.6

我用paddle复现了一个模型，它能够正常运行，结果也是正常的，但是在同等情况下paddle的模型的训练速度与tensorflow的训练速度差距很大
单机单卡：paddle 0.45step/s     tensorlfow 2.5step/s

**Comment by luotao1** [comment]
可以参考下 https://github.com/PaddlePaddle/Paddle/issues/18665#issuecomment-513780210

**Comment by dingsiyu** [comment]
http://gitlab.baidu.com/dingsiyu/transformer-xl

**Comment by luotao1** [comment]
请问：
- tf的版本号是哪个？
- 我们models repo里面也有transformer模型，而且单卡训练速度与TensorFlow持平；多卡训练速度和显存占用优于TensorFlow。https://github.com/PaddlePaddle/benchmark#Transformer
- 可以直接使用models repo下的transformer模型么？

**Comment by dingsiyu** [comment]
回答您的问题：
（1）tf 1.13.1
  (2) 我的代码并不是transformer， 而是transformer-xl，并不能复用，网络结构并不相同

**Comment by luotao1** [comment]
@guoshengCS @kuke 请问能先帮忙看下网络配置方面能否加速么？
