### ISSUE TITLE
docker编译分布式出错

### ISSUE THREAD

**Issue by Yukizzz** [PaddlePaddle/Paddle#19559]
在用docker编译源代码的时候，同样的配置和代码可以正常编译，但是在cmake的时候加上了  -DWITH_DISTRIBUTE=ON 之后，报如下错误
![image](https://user-images.githubusercontent.com/9652571/64017910-5d58ab80-cb5d-11e9-8a15-4ddd70e60822.png)

**Comment by seiriosPlus** [comment]
-DWITH_GRPC=ON
