### ISSUE TITLE
fleet的distribute_transpiler，pserver参数没有正常更新

### ISSUE THREAD

**Issue by Bella-Zhao** [PaddlePaddle/Paddle#19564]
我的任务地址：
http://10.182.163.162:8900/fileview.html?path=/home/disk1/normandy/maybach/app-user-20190830173907-2098/

本地训练时loss下降auc上升，但是在mpi上trainer.log中的auc和loss一直没有变化。用的fleet的distribute_transpiler，发现pserver.log里也没有参数更新的日志
![image](https://user-images.githubusercontent.com/29970079/64020985-8bda8480-cb65-11e9-9017-0d1a92e41fc9.png)

**Comment by seiriosPlus** [comment]
1. 分布式训练需要观察trainer端的日志， 最好看0号trainer的

**Comment by Bella-Zhao** [comment]
经过排查，发现是learning_rate过大导致不收敛，pserver是正常更新的。将learning_rate调到0.002后，auc正常上升，cost下降。
