### ISSUE TITLE
fleet的distribute_transpiler，pserver参数没有正常更新

### ISSUE THREAD

**Issue by Bella-Zhao** [PaddlePaddle/Paddle#19563]
我的任务，本地训练时loss下降auc上升，但是在mpi上trainer.log中的auc和loss一直没有变化。用的fleet的distribute_transpiler，发现pserver.log里也没有参数更新的日志

**Comment by chengduoZH** [comment]
Duplicate with https://github.com/PaddlePaddle/Paddle/issues/19564
