### ISSUE TITLE
使用filter_by_instag 在mpi训练失败

### ISSUE THREAD

**Issue by Yukizzz** [PaddlePaddle/Paddle#19561]
使用filter_by_instag，同样的数据和batchsize，在本地可以成功训练，在mpi上训练失败。报错如下
![image](https://user-images.githubusercontent.com/9652571/64018039-d22be580-cb5d-11e9-8946-11cc72437c7d.png)
mpi链接 http://10.89.170.26:8900/fileview.html?path=/home/disk1/normandy/maybach/app-user-20190830190232-2173/

**Comment by seiriosPlus** [comment]
mpi上节点数是多少， 使用的优化器是什么？
