### ISSUE TITLE
inference构造batch的时候如何把str类型的key带到batch里？

### ISSUE THREAD

**Issue by lxk1990727** [PaddlePaddle/Paddle#19567]
inference构造batch的时候如何把str类型的key带到batch里？

**Comment by luotao1** [comment]
请问能更具体的说一下需求或举个例子么？没有太理解。

**Comment by lxk1990727** [comment]
我的目标是输入：key feature_lst，输出：key score。
现在看py_reader里构造的batch要求都是一个数字型的batch，ins的key传不进去，我想拿到ins的key传入batch内

**Comment by luotao1** [comment]
data层是需要传入int或者float型的，因此py_reader传给data层的是数字型的batch。你可以把string类型的key转成int即可。
