### ISSUE TITLE
Demo/Documentation for model compression

### ISSUE THREAD

**Issue by prakharg24** [PaddlePaddle/Paddle#19577]
I want to compress MobileNet-SSD for object detection. I want to try the following ->
1. 8-bit Quantization
2. Knowledge Distillation
3. Channel Pruning

I think there are inbuilt API functions for some of the above in paddlepaddle. But I haven't found any example that I can directly replicate to do the compression.

I have the following MobileNet-SSD pipeline set up --
https://github.com/PaddlePaddle/models/tree/develop/PaddleCV/ssd

Can someone explain to me in brief how to use inbuilt API function to do model compression in paddlepaddle or point me to a document?

Thank You

**Comment by wanghaoshuang** [comment]
A demo for compression of MobileNet_V1 is [here](https://github.com/PaddlePaddle/models/blob/develop/PaddleSlim/run.sh).

The document of model compression just has Chinese version currently:  https://github.com/PaddlePaddle/models/blob/develop/PaddleSlim/docs/usage.md

**Comment by prakharg24** [comment]
@wanghaoshuang Thanks a lot!! Will look through it

I will have to rely on google translate, but I think it will be fine.
