### ISSUE TITLE
fluid.gradients return error information

### ISSUE THREAD

**Issue by leonleeldc** [PaddlePaddle/Paddle#19593]
我在调用
fluid.gradients(g_pretrain_loss, fluid.global_scope().var("rmc_fc_1_b").get_tensor())
的时候，得到如下错误信息。
{AttributeError}'paddle.fluid.core_avx.LoDTensor' object has no attribute 'block'
我是需要把这个object转成paddle.fluid.LoDTensor吗？怎么转？

**Comment by guoshengCS** [comment]
fluid.gradients接受的参数是 fluid.Variable 类型，` fluid.global_scope().var("rmc_fc_1_b").get_tensor()`的类型是paddle.fluid.core_avx.LoDTensor，把这个换成"rmc_fc_1_b"对应的variable应该就可以了
