### ISSUE TITLE
Feature request: bi tempered loss

### ISSUE THREAD

**Issue by parap1uie-s** [PaddlePaddle/Paddle#19595]
PaddlePaddle是否有实现`bi tempered loss`的计划？

这是google最近提出的一种降低噪声数据对模型训练影响的loss损失函数

相关资料：

https://arxiv.org/abs/1906.03361
https://ai.googleblog.com/2019/08/bi-tempered-logistic-loss-for-training.html

**Comment by guoshengCS** [comment]
这个我们这边评估下，有实现计划的话会在这里反馈给您，多谢支持
