### ISSUE TITLE
是否有办法取得一个scope下面的所有variables or functions as tensorflow

### ISSUE THREAD

**Issue by leonleeldc** [PaddlePaddle/Paddle#19592]
在tensorflow中，我们可以使用下面这个方法取得scope为generator下面的所有变量。
g_vars = get_collection(fluid.layers.GraphKeys.TRAINABLE_VARIABLES, scope='generator')。
我发现我们可以用
g_vars = fluid.name_scope('generator')
得到一个contextlib._GeneratorContextManager，但是好像我们并不能利用它做进一步有用的操作。
多谢

**Comment by gongweibao** [comment]
先在只能用scope.find(var_name),暂时没有iterator 遍历。

**Comment by sneaxiy** [comment]
目前paddle没有这个接口，抱歉。paddle的name_scope和tf的概念不同，paddle的name_scope用于内部处理，对用户不可见，亦不会在变量名前加上特殊前缀。
