### ISSUE TITLE
Faster_rcnn_fpn在ANALYSIS模式下预测崩溃的问题

### ISSUE THREAD

**Issue by dipthomas** [PaddlePaddle/Paddle#19598]
- 系统信息
    1）PaddlePaddle版本：1.5.1
    2）CPU：mklml
    4）系统环境：centos6.3
- 预测信息
    1）C++预测：采用1.5.1预测库版本
    2）预测库来源：BCLOUD编译
- 复现信息：
    1）下载faster_rcnn_fpn模型，并生成__model__，__params__文件；
    2）设置Anslysis参数，并生成predictor；
    3）图像预处理，归一化并将图像宽高按32补齐；
    4）将图像数据，im_info，im_shape输入predictor，
    5）运行网络崩溃；
- 崩溃信息为：
![1](https://user-images.githubusercontent.com/7144992/64141543-114a8700-ce3b-11e9-9610-58a198a26b87.JPG)
根据log信息，分析是在analysis优化过程中，fusion_repeated_fc_relu_op被错误优化；

目前将AnalysisConfig优化关闭能够正常输出结果（SwitchIrOptim(false)）；

**Comment by guoshengCS** [comment]
@Superjomn 可以帮忙看下吗，貌似是经过了fc_fuse_pass和repeated_fc_relu_fuse_pass后shape上出了问题，看了下好像fc_fuse_pass中接受高维输入并设置了in_num_col_dims，但在repeated_fc_relu_fuse_pass中丢掉了，fusion_repeated_fc_relu要求输入是2维的
