### ISSUE TITLE
paddle.fluid.core_avx.Variable

### ISSUE THREAD

**Issue by leonleeldc** [PaddlePaddle/Paddle#19594]
{AttributeError}'paddle.fluid.core_avx.Variable' object has no attribute 'desc'

paddle.fluid.core_avx.Variable是一种什么Variable，里面什么都看不到，也不能用，怎样能转成fluid.layers.Variable

**Comment by leonleeldc** [comment]
我发现我可以使用：program.global_block().var('g_embeddings')得到Parameter变量。

**Comment by guoshengCS** [comment]
paddle.fluid.core_avx.Variable 这个是C++端Variable类的封装，这个确实无法转换成python端的fluid.Variable，两个使用上会有些区别，fluid.Variable主要用于构造网络，paddle.fluid.core_avx.Variable主要用于存取数据，暴露的接口包括这些 https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/fluid/pybind/pybind.cc#L550 ，可以看下是否能满足需求
