### ISSUE TITLE
是否支持在arm架构上编译paddle fluid，有相关文档吗？

### ISSUE THREAD

**Issue by yxnal** [PaddlePaddle/Paddle#19601]
是否支持在arm架构上编译paddle fluid，有相关文档吗？

**Comment by Superjomn** [comment]
目前不支持 arm 上编译 fluid.

端侧预测可以看下 Paddle-Lite

https://github.com/PaddlePaddle/Paddle-Lite

**Comment by yxnal** [comment]
> 目前不支持 arm 上编译 fluid.
> 
> 端侧预测可以看下 Paddle-Lite
> 
> https://github.com/PaddlePaddle/Paddle-Lite

谢谢！请问是没有提供arm上的编译方式，还是本身不支持，有尝试过在arm上编译fluid吗？有什么参考资料吗？

**Comment by yxnal** [comment]
> 目前不支持 arm 上编译 fluid.
> 
> 端侧预测可以看下 Paddle-Lite
> 
> https://github.com/PaddlePaddle/Paddle-Lite

做些修改，在arm上也可以编译 fluid，在jetson nano上已经验证过了。

**Comment by orchardchang** [comment]
> ，在arm上也可以编译 fluid，在jetson nano上已经验证过了

Hi，请问你是做了哪些修改？
