### ISSUE TITLE
Illegal memory access

### ISSUE THREAD

**Issue by zhihongp** [PaddlePaddle/Paddle#19616]
为使您的问题得到快速解决，在建立Issues前，请您先通过如下方式搜索是否有相似问题:【搜索issue关键字】【使用labels筛选】【官方文档】

如果您没有查询到相似问题，为快速解决您的提问，建立issue时请提供如下细节信息：
- 标题：简洁、精准概括您的问题，例如“Insufficient Memory xxx" ”
- 版本、环境信息：
    1）PaddlePaddle版本：请提供您的PaddlePaddle版本号，例如1.1或CommitID
    2）CPU：预测若用CPU，请提供CPU型号，MKL/OpenBlas/MKLDNN/等数学库使用情况
    3）GPU：预测若用GPU，请提供GPU型号、CUDA和CUDNN版本号
    4）系统环境：请您描述系统类型、版本，例如Mac OS 10.14，Python版本
- 训练信息
    1）单机/多机，单卡/多卡
    2）显存信息
    3）Operator信息
- 复现信息：如为报错，请给出复现环境、复现步骤
- 问题描述：请详细描述您的问题，同步贴出报错信息、日志、可复现的代码片段

Thank you for contributing to PaddlePaddle.
Before submitting the issue, you could search issue in the github in case that there was a similar issue submitted or resolved before.
If there is no solution,please make sure that this is a training issue including the following details:
**System information**
-PaddlePaddle version （eg.1.1）or CommitID
-CPU: including CPUMKL/OpenBlas/MKLDNN version
-GPU: including CUDA/CUDNN version
-OS Platform (eg.Mac OS 10.14)
-Other imformation: Distriuted training/informantion of operator/
Graphics card storage
**To Reproduce**
Steps to reproduce the behavior
**Describe your current behavior**
**Code to reproduce the issue**
**Other info / logs**

**Comment by zhihongp** [comment]
Installed the newest develop branch (from wheel) to solve the PReLU speed issue.  While it's much faster now, it bumps into this crash due to illegal memory access.  This error is repeatable: when run the train() process twice sequentially, it crashes in the second one. 

> F0903 14:13:22.534360 31190 all_reduce_op_handle.cc:70] cudaStreamSynchronize an illegal memory access was encountered
*** Check failure stack trace: ***
F0903 14:13:22.534365 31205 device_context.cc:335] cudaStreamSynchronize an illegal memory access was encountered errno:77
*** Check failure stack trace: ***
    @     0x7fba164e3d6d  google::LogMessage::Fail()
    @     0x7fba164e3d6d  google::LogMessage::Fail()
    @     0x7fba164e781c  google::LogMessage::SendToLog()
    @     0x7fba164e781c  google::LogMessage::SendToLog()
    @     0x7fba164e3893  google::LogMessage::Flush()
    @     0x7fba164e3893  google::LogMessage::Flush()
    @     0x7fba164e8d2e  google::LogMessageFatal::~LogMessageFatal()
    @     0x7fba164e8d2e  google::LogMessageFatal::~LogMessageFatal()
    @     0x7fba1850643d  _ZNSt17_Function_handlerIFvvEZNK6paddle8platform17CUDADeviceContext4WaitEvEUlvE_E9_M_invokeERKSt9_Any_data
    @     0x7fba18516094  paddle::platform::TemporaryAllocator::Release()
    @     0x7fba1826aab5  paddle::framework::details::AllReduceOpHandle::RunAllReduceFuncs()
    @     0x7fba18509591  paddle::platform::CUDADeviceContext::Wait()
    @     0x7fba1826bf88  paddle::framework::details::AllReduceOpHandle::RunImpl()
    @     0x7fba182993e7  paddle::framework::details::OpHandleBase::RecordWaitEventOnCtx()
    @     0x7fba1825d276  paddle::framework::details::FastThreadedSSAGraphExecutor::RunOpSync()
    @     0x7fba1825ecd5  paddle::framework::details::FetchOpHandle::WaitInputVarGenerated()
    @     0x7fba1825f004  paddle::framework::details::FetchOpHandle::RunImpl()
    @     0x7fba1825be5f  paddle::framework::details::FastThreadedSSAGraphExecutor::RunOp()
    @     0x7fba1825c21f  _ZNSt17_Function_handlerIFvvESt17reference_wrapperISt12_Bind_simpleIFS1_ISt5_BindIFZN6paddle9framework7details28FastThreadedSSAGraphExecutor10RunOpAsyncEPSt13unordered_mapIPNS6_12OpHandleBaseESt6atomicIiESt4hashISA_ESt8equal_toISA_ESaISt4pairIKSA_SC_EEESA_RKSt10shared_ptrINS5_13BlockingQueueImEEEEUlvE_vEEEvEEEE9_M_invokeERKSt9_Any_data
    @     0x7fba1825d276  paddle::framework::details::FastThreadedSSAGraphExecutor::RunOpSync()
    @     0x7fba165db013  std::_Function_handler<>::_M_invoke()
    @     0x7fba1825be5f  paddle::framework::details::FastThreadedSSAGraphExecutor::RunOp()
    @     0x7fba1825c21f  _ZNSt17_Function_handlerIFvvESt17reference_wrapperISt12_Bind_simpleIFS1_ISt5_BindIFZN6paddle9framework7details28FastThreadedSSAGraphExecutor10RunOpAsyncEPSt13unordered_mapIPNS6_12OpHandleBaseESt6atomicIiESt4hashISA_ESt8equal_toISA_ESaISt4pairIKSA_SC_EEESA_RKSt10shared_ptrINS5_13BlockingQueueImEEEEUlvE_vEEEvEEEE9_M_invokeERKSt9_Any_data
    @     0x7fba1645d707  std::__future_base::_State_base::_M_do_set()
    @     0x7fba5b14f827  __pthread_once_slow
    @     0x7fba165db013  std::_Function_handler<>::_M_invoke()
    @     0x7fba18257952  _ZNSt13__future_base11_Task_stateISt5_BindIFZN6paddle9framework7details28FastThreadedSSAGraphExecutor10RunOpAsyncEPSt13unordered_mapIPNS4_12OpHandleBaseESt6atomicIiESt4hashIS8_ESt8equal_toIS8_ESaISt4pairIKS8_SA_EEES8_RKSt10shared_ptrINS3_13BlockingQueueImEEEEUlvE_vEESaIiEFvvEE6_M_runEv
    @     0x7fba1645d707  std::__future_base::_State_base::_M_do_set()
    @     0x7fba5b14f827  __pthread_once_slow
    @     0x7fba1645edf4  _ZZN10ThreadPoolC1EmENKUlvE_clEv
    @     0x7fba18257952  _ZNSt13__future_base11_Task_stateISt5_BindIFZN6paddle9framework7details28FastThreadedSSAGraphExecutor10RunOpAsyncEPSt13unordered_mapIPNS4_12OpHandleBaseESt6atomicIiESt4hashIS8_ESt8equal_toIS8_ESaISt4pairIKS8_SA_EEES8_RKSt10shared_ptrINS3_13BlockingQueueImEEEEUlvE_vEESaIiEFvvEE6_M_runEv
    @     0x7fba45d99c5c  execute_native_thread_routine_compat
    @     0x7fba5b1476db  start_thread
    @     0x7fba1645edf4  _ZZN10ThreadPoolC1EmENKUlvE_clEv
    @     0x7fba45d99c5c  execute_native_thread_routine_compat
    @     0x7fba5ae7088f  clone
    @     0x7fba5b1476db  start_thread
    @     0x7fba5ae7088f  clone
    @              (nil)  (unknown)

**Comment by wanghaoshuang** [comment]
You can try some flags to reduce the device memory to avoid illegal memory access.

```
export FLAGS_fast_eager_deletion_mode=1
export FLAGS_eager_delete_tensor_gb=0.0
```

**Comment by zhihongp** [comment]
set these variables but problem still exists.  Looking up some older reports, wonder if it's about compatibility issues.  My program runs fine with 'paddlepaddle-gpu 1.5.0.post97', but ran into this error after installing the latest develop branch 'paddlepaddle_gpu-latest-cp37-cp37m-linux_x86_64.whl'.

Other relevant info: cuda-9.2.88, cudnn-7.1.4, nccl_2.2.13-1+cuda9.2_x86_64

**Comment by sneaxiy** [comment]
@zhihongp Could we please show us your code to reproduce the problem for us?

**Comment by zhihongp** [comment]
@sneaxiy sent you a hi msg

**Comment by nizihan** [comment]
> @sneaxiy sent you a hi msg

hi . could you please show us your code how to solve the problem

**Comment by nizihan** [comment]
hi . could you please show us your code how to solve the problem
