### ISSUE TITLE
hsigmoid预测问题

### ISSUE THREAD

**Issue by moonlin7** [PaddlePaddle/Paddle#19613]
paddle fluid怎么使用 hsigmoid训练出出来的参数进行结果的预测

**Comment by guoshengCS** [comment]
预测时使用输入X（形状为[N, D]，N是batch_size，D是特征维度）与hsigmoid训练出出来的参数W（形状为[K, D]，K是二叉树的非叶子节点数，为类别数减去1，D是特征维度）进行矩阵乘，并加上bias B（形状为[K, D]），然后将得到的结果做sigmoid，之后将结果沿着二叉树进行解码得到路径与类别，解码代码可以先行参考这里，https://github.com/PaddlePaddle/models/blob/develop/legacy/hsigmoid/infer.py#L13
