### ISSUE TITLE
fleet 分布式训练环境下 如何打印 loss

### ISSUE THREAD

**Issue by lizhiqings** [PaddlePaddle/Paddle#19626]

**Comment by gongweibao** [comment]
是train_from_dataset那？还是其他的？

**Comment by lizhiqings** [comment]
是 train_from_dataset

[cid:image001.png@01D56341.2E05BE10]

就是这个 ，打印auc 是可以的 用fleet api 提供的 demo就好了 现在想这边怎么打印 当前 dataset计算完的 loss 和 model中定义的其他中间页 结果，单机版可以执行ext.run 传一个fetch_list 就好了，这边怎么弄？

发件人: gongweibao <notifications@github.com>
答复: PaddlePaddle/Paddle <reply@reply.github.com>
日期: 2019年9月4日 星期三 下午4:50
收件人: PaddlePaddle/Paddle <Paddle@noreply.github.com>
抄送: "Li,Zhiqing" <lizhiqing@baidu.com>, Author <author@noreply.github.com>
主题: Re: [PaddlePaddle/Paddle] fleet 分布式训练环境下 如何打印 loss (#19626)

train_from_dataset

**Comment by lizhiqings** [comment]
发件人: "Li,Zhiqing" <lizhiqing@baidu.com>
日期: 2019年9月4日 星期三 下午4:54
收件人: PaddlePaddle/Paddle <reply@reply.github.com>
主题: Re: [PaddlePaddle/Paddle] fleet 分布式训练环境下 如何打印 loss (#19626)


是 train_from_dataset

[cid:image001.png@01D56341.2E05BE10]

就是这个 ，打印auc 是可以的 用fleet api 提供的 demo就好了 现在想这边怎么打印 当前 dataset计算完的 loss 和 model中定义的其他中间页 结果，单机版可以执行ext.run 传一个fetch_list 就好了，这边怎么弄？

发件人: gongweibao <notifications@github.com>
答复: PaddlePaddle/Paddle <reply@reply.github.com>
日期: 2019年9月4日 星期三 下午4:50
收件人: PaddlePaddle/Paddle <Paddle@noreply.github.com>
抄送: "Li,Zhiqing" <lizhiqing@baidu.com>, Author <author@noreply.github.com>
主题: Re: [PaddlePaddle/Paddle] fleet 分布式训练环境下 如何打印 loss (#19626)

train_from_dataset

**Comment by seiriosPlus** [comment]
参考:
```
        exe.train_from_dataset(program=fleet.main_program,
                               dataset=dataset,
                               fetch_list=[acc],
                               fetch_info=["acc"],
                               print_period=10,
                               debug=True)
        sys.stderr.write("epoch {} finished at {} \n".format(i, time.ctime()))
```

```fetch_list``` 中的acc就是会被打印出的结果， loss也是同理

**Comment by gentelyang** [comment]
> 参考:
> 
> ```
>         exe.train_from_dataset(program=fleet.main_program,
>                                dataset=dataset,
>                                fetch_list=[acc],
>                                fetch_info=["acc"],
>                                print_period=10,
>                                debug=True)
>         sys.stderr.write("epoch {} finished at {} \n".format(i, time.ctime()))
> ```
> 
> `fetch_list` 中的acc就是会被打印出的结果， loss也是同理

...这个可以打印出来，但是打印出来不像pyreader那样直观，假如我要将前100个batch输出的auc值放入一个list中，还需要手动放，train_from_dataset的return为None，用起来不是很舒服。

**Comment by seiriosPlus** [comment]
这个正在改了， 马上就会发布相关的输出功能
