### ISSUE TITLE
Focal Loss in SSD

### ISSUE THREAD

**Issue by prakharg24** [PaddlePaddle/Paddle#19639]
I am looking to train MobileNet-SSD as present here,
https://github.com/PaddlePaddle/models/tree/develop/PaddleCV/ssd

However, instead of using the SSD Loss (which samples negative gt anchor boxes to maintain 3:1 ratio), I want to use Focal Loss (as described in RetinaNet).

Is there an inbuilt loss function for such focal loss calculations? If not, what would be the easiest way to implement a custom loss function like that, using the existing paddlepaddle functions?

Any direction or help is appreciated.

Thank You

**Comment by qingqing01** [comment]
You can refer https://www.paddlepaddle.org.cn/documentation/docs/en/1.5/api/layers/detection.html#sigmoid-focal-loss

**Comment by prakharg24** [comment]
Yes that's sigmoid focal loss for an array of class prediction and corresponding gt labels. But how exactly and where will this fir into the a custom loss function to replace ssd_loss?

I mean where in ssd_loss do I need to place sigmoid focal loss to make it work? I am a little confused on that front.

Thank You.

**Comment by qingqing01** [comment]
`ssd_loss` is in  `paddle/fluid/layers/detection.py`

https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/fluid/layers/detection.py#L1246

Maybe you need to change it in your installation lib.  And Thanks for point this, we can put this API in the PaddleCV/PaddleDetection.
