### ISSUE TITLE
placeholder issue

### ISSUE THREAD

**Issue by leonleeldc** [PaddlePaddle/Paddle#19630]
Hi, 
我有一个跟这个issue相似的问题：

fluid.layers.data里面指定的shape与实际输出不符合预期 #15519
我定义如下placeholder.
self.anneal_ph = fluid.layers.data('anneal_ph', shape=[1],
                                           append_batch_size=False,
                                           dtype='float32',
                                           lod_level=0) 

在下面这样使用，
neg_ELBO = neg_ll + self.anneal_ph * KL + 2 * reg_vars

build_graph没有问题，但是在后面输入数据后，就说维度不一致了，实际上，我输入就是一个数，我把append_batch_size设成了false，但是后面计算时，它还是说是两维。

这种怎么办？
多谢！

**Comment by wanghaoshuang** [comment]
你可以先使用[reshape op](https://www.paddlepaddle.org.cn/documentation/docs/zh/1.5/api_cn/layers_cn/nn_cn.html#reshape)强制将self.anneal_ph reshape成[1]

另外，我再确认下paddle的placeholder是不是有问题。

**Comment by leonleeldc** [comment]
用reshape可以过了，奇怪，我原来用unsqueeze过不了。非常感谢。
