### ISSUE TITLE
源码编译失败 nccl和'-m64'

### ISSUE THREAD

**Issue by yxnal** [PaddlePaddle/Paddle#19647]
源码编译paddle gpu版本的时候遇到两个问题（在jetson上的编译）：
1、由于jeston不支持nccl，而我想编译一个只支持单卡的paddle，想去除nccl依赖
（1）paddle是否有关闭nccl的编译选项，或者有什么方式修改编译配置？
（2）如果从编译配置上无法修改，是否可以在源码上屏蔽nccl逻辑，再编译？
2、‘-m64’是否可替换为类似‘-arm64’，应该如何替换。

详细编译错误信息如下：
[ 4%] Building CXX object paddle/fluid/platform/CMakeFiles/enforce.dir/enforce.cc.o
c++: error: unrecognized command line option ‘-m64’
paddle/fluid/platform/CMakeFiles/enforce.dir/build.make:62: recipe for target 'paddle/fluid/platform/CMakeFiles/enforce.dir/enforce.cc.o' failed
make[2]: *** [paddle/fluid/platform/CMakeFiles/enforce.dir/enforce.cc.o] Error 1
CMakeFiles/Makefile2:2538: recipe for target 'paddle/fluid/platform/CMakeFiles/enforce.dir/all' failed
make[1]: *** [paddle/fluid/platform/CMakeFiles/enforce.dir/all] Error 2
Makefile:149: recipe for target 'all' failed
make: *** [all] Error 2

BTW：
1、在之前的issue中：https://github.com/PaddlePaddle/Paddle/issues/11884 看到你们这样的回复：“Supporting TX2 for external users is ongoing.If you are internal users, can you contact us now?”  请问如何联系你们？

**Comment by NHZlX** [comment]
当前paddle还不支持TX2. https://github.com/PaddlePaddle/paddle-lite 正在调研对TX2的支持。

**Comment by yxnal** [comment]
> 当前paddle还不支持TX2. https://github.com/PaddlePaddle/paddle-lite 正在调研对TX2的支持。

谢谢，有具体的时间表吗？

**Comment by NHZlX** [comment]
你对此硬件的模型需求是什么呢（有哪些模型）

**Comment by yxnal** [comment]
> 你对此硬件的模型需求是什么呢（有哪些模型）
感谢解答！
没有特定模型的需求，是想在jetson nano上使用 paddle-gpu 进行常用的训练和预测任务。
您的意思是 可以安装只支持部分模型训练的paddle吗？（删减部分功能的paddle）

而且，jetson nano上运行ubuntu系统，具备gpu显卡资源、cuda、cudnn、tensorRT 等，我认为应该很适合paddle的使用的，torch、mxnet已经提供了官方支持，tensorflow也提供了编译安装的方式

**Comment by jeng1220** [comment]
@yxnal ,
Now, the workaround is to build ARM version of NCCL by yourself. Follow [README.md](https://github.com/NVIDIA/nccl) can solve this issue temporally
