### ISSUE TITLE
安装测试编译问题

### ISSUE THREAD

**Issue by caoxuefengzz** [PaddlePaddle/Paddle#19649]
cxf@cxf-HP-Pavilion-Laptop-14-ce1xxx:~$ python
Python 3.6.8 (default, Jan 14 2019, 11:02:34) 
[GCC 8.0.1 20180414 (experimental) [trunk revision 259383]] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import paddle.fluid as fluid
>>> fluid.install_check.run_check()
Running Verify Fluid Program ... 
W0905 16:49:32.204157 24602 device_context.cc:259] Please NOTE: device: 0, CUDA Capability: 61, Driver API Version: 9.1, Runtime API Version: 9.0
W0905 16:49:32.206833 24602 device_context.cc:267] device: 0, cuDNN Version: 7.6.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/cxf/.local/lib/python3.6/site-packages/paddle/fluid/install_check.py", line 123, in run_check
    test_simple_exe()
  File "/home/cxf/.local/lib/python3.6/site-packages/paddle/fluid/install_check.py", line 119, in test_simple_exe
    exe0.run(startup_prog)
  File "/home/cxf/.local/lib/python3.6/site-packages/paddle/fluid/executor.py", line 651, in run
    use_program_cache=use_program_cache)
  File "/home/cxf/.local/lib/python3.6/site-packages/paddle/fluid/executor.py", line 749, in _run
    exe.run(program.desc, scope, 0, True, True, fetch_var_name)
paddle.fluid.core_avx.EnforceNotMet: Invoke operator fill_constant error.
Python Callstacks: 
  File "/home/cxf/.local/lib/python3.6/site-packages/paddle/fluid/framework.py", line 1842, in _prepend_op
    attrs=kwargs.get("attrs", None))
  File "/home/cxf/.local/lib/python3.6/site-packages/paddle/fluid/initializer.py", line 189, in __call__
    stop_gradient=True)
  File "/home/cxf/.local/lib/python3.6/site-packages/paddle/fluid/framework.py", line 1727, in create_parameter
    initializer(param, self)
  File "/home/cxf/.local/lib/python3.6/site-packages/paddle/fluid/layer_helper_base.py", line 316, in create_parameter
    **attr._to_kwargs(with_initializer=True))
  File "/home/cxf/.local/lib/python3.6/site-packages/paddle/fluid/dygraph/layers.py", line 90, in create_parameter
    default_initializer)
  File "/home/cxf/.local/lib/python3.6/site-packages/paddle/fluid/dygraph/nn.py", line 930, in _build_once
    attr=self._bias_attr, shape=size, dtype=self._dtype, is_bias=True)
  File "/home/cxf/.local/lib/python3.6/site-packages/paddle/fluid/dygraph/layers.py", line 158, in __call__
    self._build_once(*inputs)
  File "/home/cxf/.local/lib/python3.6/site-packages/paddle/fluid/install_check.py", line 40, in forward
    x = self._fc1(inputs)
  File "/home/cxf/.local/lib/python3.6/site-packages/paddle/fluid/dygraph/layers.py", line 162, in __call__
    outputs = self.forward(*inputs)
  File "/home/cxf/.local/lib/python3.6/site-packages/paddle/fluid/install_check.py", line 113, in test_simple_exe
    out0 = simple_layer0(inp0)
  File "/home/cxf/.local/lib/python3.6/site-packages/paddle/fluid/install_check.py", line 123, in run_check
    test_simple_exe()
  File "<stdin>", line 1, in <module>
C++ Callstacks: 
Enforce failed. Expected allocating <= available, but received allocating:1835316578 > available:1701183232.
Insufficient GPU memory to allocation. at [/paddle/paddle/fluid/platform/gpu_info.cc:262]
PaddlePaddle Call Stacks: 
0       0x7f0fa10a9c88p void paddle::platform::EnforceNotMet::Init<std::string>(std::string, char const*, int) + 360
1       0x7f0fa10a9fd7p paddle::platform::EnforceNotMet::EnforceNotMet(std::string const&, char const*, int) + 87
2       0x7f0fa30cac56p paddle::platform::GpuMaxChunkSize() + 630
3       0x7f0fa309ef4ap
4       0x7f0ff5378827p
5       0x7f0fa309e5edp paddle::memory::legacy::GetGPUBuddyAllocator(int) + 109
6       0x7f0fa309f435p void* paddle::memory::legacy::Alloc<paddle::platform::CUDAPlace>(paddle::platform::CUDAPlace const&, unsigned long) + 37
7       0x7f0fa309f975p paddle::memory::allocation::LegacyAllocator::AllocateImpl(unsigned long) + 421
8       0x7f0fa3093a95p paddle::memory::allocation::AllocatorFacade::Alloc(boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&, unsigned long) + 181
9       0x7f0fa3093c1ap paddle::memory::allocation::AllocatorFacade::AllocShared(boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&, unsigned long) + 26
10      0x7f0fa2c9e4fcp paddle::memory::AllocShared(boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&, unsigned long) + 44
11      0x7f0fa30664c4p paddle::framework::Tensor::mutable_data(boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_>, paddle::framework::proto::VarType_Type, unsigned long) + 148
12      0x7f0fa1e5a8dep paddle::operators::FillConstantKernel<float>::Compute(paddle::framework::ExecutionContext const&) const + 494
13      0x7f0fa1e5d9f3p std::_Function_handler<void (paddle::framework::ExecutionContext const&), paddle::framework::OpKernelRegistrarFunctor<paddle::platform::CUDAPlace, false, 0ul, paddle::operators::FillConstantKernel<float>, paddle::operators::FillConstantKernel<double>, paddle::operators::FillConstantKernel<long>, paddle::operators::FillConstantKernel<int>, paddle::operators::FillConstantKernel<paddle::platform::float16> >::operator()(char const*, char const*, int) const::{lambda(paddle::framework::ExecutionContext const&)#1}>::_M_invoke(std::_Any_data const&, paddle::framework::ExecutionContext const&) + 35
14      0x7f0fa300fe07p paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&, paddle::framework::RuntimeContext*) const + 375
15      0x7f0fa30101e1p paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&) const + 529
16      0x7f0fa300d7dcp paddle::framework::OperatorBase::Run(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&) + 332
17      0x7f0fa123455ep paddle::framework::Executor::RunPreparedContext(paddle::framework::ExecutorPrepareContext*, paddle::framework::Scope*, bool, bool, bool) + 382
18      0x7f0fa12375ffp paddle::framework::Executor::Run(paddle::framework::ProgramDesc const&, paddle::framework::Scope*, int, bool, bool, std::vector<std::string, std::allocator<std::string> > const&, bool) + 143
19      0x7f0fa109adedp
20      0x7f0fa10dc076p
21            0x56204cp _PyCFunction_FastCallDict + 860
22            0x4f88bap
23            0x4f98c7p _PyEval_EvalFrameDefault + 1127
24            0x4f6128p
25            0x4f7d60p
26            0x4f876dp
27            0x4fa6c0p _PyEval_EvalFrameDefault + 4704
28            0x4f6128p
29            0x4f7d60p
30            0x4f876dp
31            0x4f98c7p _PyEval_EvalFrameDefault + 1127
32            0x4f6128p
33            0x4f7d60p
34            0x4f876dp
35            0x4f98c7p _PyEval_EvalFrameDefault + 1127
36            0x4f6128p
37            0x4f7d60p
38            0x4f876dp
39            0x4f98c7p _PyEval_EvalFrameDefault + 1127
40            0x4f6128p
41            0x4f9023p PyEval_EvalCode + 35
42            0x6415b2p
43            0x4b2e86p
44            0x4b409cp PyRun_InteractiveLoopFlags + 225
45            0x643933p PyRun_AnyFileExFlags + 83
46            0x62b26ep Py_Main + 1438
47            0x4b4cb0p main + 224
48      0x7f0ff55a9b97p __libc_start_main + 231
49            0x5bdf6ap _start + 42

>>> exit()

**Comment by JiabinYang** [comment]
这个看起来是显存不足造成的，请使用1.5.2版本的paddlepaddle
