### ISSUE TITLE
快速安装，paddlepaddle whl包下载失败

### ISSUE THREAD

**Issue by caoxuefengzz** [PaddlePaddle/Paddle#19650]
*********************************
欢迎使用PaddlePaddle快速安装脚本
*********************************

如果您在安装过程中遇到任何问题，请在https://github.com/PaddlePaddle/Paddle/issues反馈，我们的工作人员将会帮您答疑解惑

本安装包将帮助您在Linux或Mac系统下安装PaddlePaddle,包括
1）安装前的准备
2）开始安装

请按回车键进行下一步...

*********************1. 安装前的准备*****************************

Step 1. 正在检测您的操作系统信息...

          您的系统为：Linux

Step 2. 检测GPU型号和CUDA/cuDNN版本

即将检测您的机器是否含GPU，请按回车键继续...

已在您的机器上找到GPU，即将确认CUDA和CUDNN版本...

检测结果：找到CUDA 9
您的CUDA版本是9

请按回车键进行下一步...

您的CUDNN版本是: CUDNN7

Step 3. 检测数学库

检测到您的机器上配备GPU，推荐您使用mkl数学库

Step 4. 选择要安装的PaddlePaddle版本

请按回车键继续...

               1. 开发版：对应Github上develop分支，如您需要开发、或希望使用PaddlePaddle最新功能，请选用此版本
               2. 稳定版（推荐）：如您无特殊开发需求，建议使用此版本，目前最新的版本号为 1.5.1
                => 请输入数字1或2。如输入其他字符或直接回车，将会默认选择【 2. 稳定版 】 。请在这里输入并回车：2
您选择了数字【2】，为您安装release-1.5.1

Step 5. 检测Python版本

                找到python版本36,使用请输入y,选择其他版本请输n(y/n):y

Step 6.是否使用Python的虚拟环境

                是否使用python  virtualenv虚环境安装(y/n):y
为您使用python虚环境安装
请输入虚拟环境名字：cao
Already using interpreter /usr/bin/python
Using base prefix '/usr'
New python executable in /home/cxf/Downloads/cao/bin/python
Installing setuptools, pip, wheel...
done.
*********************2. 开始安装*****************************
paddlepaddle whl包下载失败

**Comment by Superjomn** [comment]
是网络问题？

有截图吗

确认机器能安装普通python包

**Comment by JiabinYang** [comment]
这个能贴一下完整的截图么

**Comment by JiabinYang** [comment]
fixed in #19106
