### ISSUE TITLE
模型构建中关于使用layers.argmax()后模型报错

### ISSUE THREAD

**Issue by MoranCoder95** [PaddlePaddle/Paddle#19652]
- 版本、环境信息：
    1）PaddlePaddle版本：1.5.0
    2）CPU：
    3）GPU：
    4）系统环境：windows
- 模型信息

```python
class ActorModel(Model):
    def __init__(self, act_dim):
        hid1_size = 400
        hid2_size = 300

        self.fc1 = layers.fc(size=hid1_size, act='relu')
        self.fc2 = layers.fc(size=hid2_size, act='relu')
        self.fc3 = layers.fc(size=act_dim, act='tanh')

    def policy(self, obs):
        hid1 = self.fc1(obs)
        hid2 = self.fc2(hid1)
        means = self.fc3(hid2)
        means = layers.argmax(means, axis=1)
        means = layers.unsqueeze(means, axes=[1])
        return means.astype('float32')

cost = layers.reduce_mean(-1.0 * Q)
optimizer = fluid.optimizer.AdamOptimizer(self.actor_lr)
 optimizer.minimize(cost, parameter_list=self.model.get_actor_params())

```

- 问题描述：
如上定义好模型（用了argmax()）后，然后定义目标函数和优化函数，在进入到 optimizer.minimize(cost, parameter_list=self.model.get_actor_params())时系统报错：
Process finished with exit code -1073741819 (0xC0000005)

请问：对于argmax()梯度反向传播的问题，是不是不能这么定义网络？

**Comment by scarletfrank** [comment]
`def get_actor_params(self): return self.parameters()`

@moranliuyu
应该是这个方法还没定义造成的错误吧，使用PARL中ddpg中有说需要定义这个方法
参考：https://github.com/PaddlePaddle/PARL/blob/develop/examples/DDPG/mujoco_model.py

**Comment by chengduoZH** [comment]
@FrankScarlet  你的完整模型的模型是怎么样的？ 完整的报错信息是什么？

**Comment by scarletfrank** [comment]
> @FrankScarlet 你的完整模型的模型是怎么样的？ 完整的报错信息是什么？

我这边没有错误，我只是切换为DDPG方法时不知道怎么实现 _get_actor_params_ 方法，然后搜到这个issue，后面问人才发现自己漏看了PARL的example

**Comment by chengduoZH** [comment]
@FrankScarlet  就是说现在没问题了，是吗？

**Comment by MoranCoder95** [comment]
已经解决了，非常感谢




------------------ 原始邮件 ------------------
发件人: "chengduo"<notifications@github.com>;
发送时间: 2019年9月10日(星期二) 晚上10:52
收件人: "PaddlePaddle/Paddle"<Paddle@noreply.github.com>;
抄送: "hausser "<384733132@qq.com>;"Mention"<mention@noreply.github.com>;
主题: Re: [PaddlePaddle/Paddle] 模型构建中关于使用layers.argmax()后模型报错 (#19652)




@FrankScarlet  就是说现在没问题了，是吗？
