### ISSUE TITLE
关于fleet的 pslib模式embedding定义

### ISSUE THREAD

**Issue by lizhiqings** [PaddlePaddle/Paddle#19651]
使用 pslib（旧版 非fleet）时，embedding 是下面这种形式，代码中并没有 明确写 layers.embedding（）。。。
<img width="833" alt="111" src="https://user-images.githubusercontent.com/47736115/64330405-7b158d00-d003-11e9-9191-b818a995fdef.png">

但是使用 pslib（新版 fleet的pslib 模式）时 ，下图形式，又明确定义了 layers.embedding（）想了解下 这两种方式有啥区别么 ，还有就是第二种方式 layers.embedding（）中的 self._dict_dim 参数应该不起作用吧，也就是说该embedding 是随着新特征 加入 会 变大吧  

<img width="773" alt="222" src="https://user-images.githubusercontent.com/47736115/64330441-91234d80-d003-11e9-864c-cca907a8d2ee.png">

**Comment by Thunderbrook** [comment]
1. 两种方式无区别
2. self._dict_dim参数不起作用，词表会随着训练更新

**Comment by lizhiqings** [comment]
好的 谢谢
发件人: Thunderbrook <notifications@github.com>
答复: PaddlePaddle/Paddle <reply@reply.github.com>
日期: 2019年9月5日 星期四 下午6:57
收件人: PaddlePaddle/Paddle <Paddle@noreply.github.com>
抄送: "Li,Zhiqing" <lizhiqing@baidu.com>, Author <author@noreply.github.com>
主题: Re: [PaddlePaddle/Paddle] 关于fleet的 pslib模式embedding定义 (#19651)


  1.  两种方式无区别
  2.  self._dict_dim参数不起作用，词表会随着训练更新
