### ISSUE TITLE
本地开发指南文档中镜像构建和测试的方式不可用

### ISSUE THREAD

**Issue by chi2liu** [PaddlePaddle/Paddle#19669]
![image](https://user-images.githubusercontent.com/19861628/64399255-47397680-d09a-11e9-85eb-8edd3f56dc4c.png)
docker run -v $(pwd):/paddle -e "WITH_GPU=OFF" -e "WITH_AVX=ON" -e "WITH_TESTING=ON" paddle:latest-dev 是否可以详细列出build需要执行的命令，当前这个run是无法build的，没带命令

**Comment by yma-admin** [comment]
能否贴一下这页文档的链接？

**Comment by seiriosPlus** [comment]
可以参考 https://www.paddlepaddle.org.cn/documentation/docs/zh/beginners_guide/install/compile/compile_Ubuntu.html
里面写明了 build相关的选项，及build命令
