### ISSUE TITLE
动态图，forward里面写一些layers.reshape、dropout、softmax等操作，会影响到反向传播吗？

### ISSUE THREAD

**Issue by Exception-star** [PaddlePaddle/Paddle#19666]
![image](https://user-images.githubusercontent.com/53971568/64358952-fa25b800-d039-11e9-8908-d55e4301df47.png)

自己写了个dropout2d

**Comment by phlrain** [comment]
如果这些op　是无参数的，不会影响的

**Comment by Exception-star** [comment]
> 如果这些op　是无参数的，不会影响的

意思是可以用reshape, transpose, dropout, matmul等这些函数，梯度回传时是不是要经过这些函数的逆操作？
