### ISSUE TITLE
如何fetch rnn的state_array？

### ISSUE THREAD

**Issue by wickai** [PaddlePaddle/Paddle#19664]
我无法直接fetch出state_array，报错如下：
C++ Callstacks: 
Variable must be type N6paddle9framework9LoDTensorE, the holding type is St6vectorIN6paddle9framework9LoDTensorESaIS2_EE at [/paddle/paddle/fluid/framework/variable.h:37]
![image](https://user-images.githubusercontent.com/14268278/64341766-a4daae00-d01b-11e9-8b01-c570a523bc72.png)

我想知道如何取出state_array， 有没有示例代码？

**Comment by qingqing01** [comment]
可以试下采用tensor_array_to_tensor，将tensor_array拼接成tensor，再fetch:

https://www.paddlepaddle.org.cn/documentation/docs/zh/1.5/api_cn/layers_cn/tensor_cn.html#tensor-array-to-tensor
