### ISSUE TITLE
Demo里Recommendation的training loss问题

### ISSUE THREAD

**Issue by hohaxu** [PaddlePaddle/Paddle#1966]
按照在线文档里面的教程，试着训练了下paddle/demo/recommendation。不知道为什么我training loss比较教程里看起来要高很多?  用的paddle版本是4月30号的896b9c5, 没有做任何改动。

epoch 1  训练： cost=6.11816     在线教程：  cost=3.32155
epoch 2  训练：cost=6.11527
。。。

＝＝＝ training log ＝＝＝
[INFO 2017-05-02 11:20:06,711 networks.py:1472] The input order is [movie_id, title, genres, user_id, gender, age, occupation, rating]
[INFO 2017-05-02 11:20:06,711 networks.py:1478] The output order is [__mse_cost_0__]
I0502 11:20:06.793532 18703 Trainer.cpp:165] trainer mode: Normal
I0502 11:20:06.953569 18703 PyDataProvider2.cpp:243] loading dataprovider dataprovider::process
I0502 11:20:06.992805 18703 PyDataProvider2.cpp:243] loading dataprovider dataprovider::process
W0502 11:20:06.993029 18703 Trainer.cpp:622] --test_all_data_in_one_period was deprecated, since we will always do test on all test set
I0502 11:20:06.993054 18703 GradientMachine.cpp:86] Initing parameters..
I0502 11:20:07.167628 18703 GradientMachine.cpp:93] Init parameters done.
...................................................................................................
I0502 11:22:33.724074 18703 TrainerInternal.cpp:165]  Batch=100 samples=160000 AvgCost=6.33338 CurrentCost=6.33338 Eval:  CurrentEval:
...................................................................................................
I0502 11:24:40.304360 18703 TrainerInternal.cpp:165]  Batch=200 samples=320000 AvgCost=6.27258 CurrentCost=6.21178 Eval:  CurrentEval:
...................................................................................................
I0502 11:26:47.475955 18703 TrainerInternal.cpp:165]  Batch=300 samples=480000 AvgCost=6.2448 CurrentCost=6.18925 Eval:  CurrentEval:
...................................................................................................
I0502 11:28:52.041764 18703 TrainerInternal.cpp:165]  Batch=400 samples=640000 AvgCost=6.22759 CurrentCost=6.17594 Eval:  CurrentEval:
...................................................................................................
I0502 11:30:53.115355 18703 TrainerInternal.cpp:165]  Batch=500 samples=800000 AvgCost=6.21779 CurrentCost=6.17862 Eval:  CurrentEval:
.................................................................I0502 11:32:13.507774 18703 TrainerInternal.cpp:181]  Pass=0 Batch=565 samples=902826 AvgCost=6.21333 Eval:
I0502 11:32:44.170591 18703 Tester.cpp:115]  Test samples=97383 cost=6.11816 Eval:
I0502 11:32:44.170732 18703 GradientMachine.cpp:64] Saving parameters to ./output/pass-00000
...................................................................................................
I0502 11:34:50.525712 18703 TrainerInternal.cpp:165]  Batch=100 samples=160000 AvgCost=6.15603 CurrentCost=6.15603 Eval:  CurrentEval:

**Comment by livc** [comment]
您好，

我运行了一下目前最新的 paddle/demo/recommendation，确实和你的结果差不多。
然后我 track 了下对应教程的修改历史，在这份教程最[初始的提交版本](https://github.com/PaddlePaddle/Paddle/commit/b72beee4f0a9521e97d7f8a5c6ead51f38c05522?short_path=dfbcc24#diff-dfbcc2401f9b7120427aa0a2458ac907)中 cost 也是6点多，推测这个教程的作者在写作时可能网络配置不一致，我会修复一下这个问题，使教程与代码对应，感谢指出！

另外，paddle/demo/recommendation 这实际上是第一版本的API，最新版本 API 的教程在 <http://book.paddlepaddle.org>，您可以参考那个。

**Comment by hohaxu** [comment]
谢谢确认和详细解释！

**Comment by hohaxu** [comment]
不好意思还想问个问题。看到＃2003里面跑到50个epoch以后 “Best pass is 00047,  error is 6.14036”。 这个loss是不是太大了？

貌似 http://book.paddlepaddle.org/ 里面有张训练的图，loss能够达到～3左右？

**Comment by livc** [comment]
@hohaxu 第一版API和目前第二版API的demo写法不太一样，比如v1中构造用户特征和电影特征都是通过`construct_feature`这个函数实现的，因此二者的网络配置也不一样，推荐学习目前最新API版本的demo。
