### ISSUE TITLE
多卡训练模型层数要与卡数相等的问题 paddle.fluid.core_avx.EnforceNotMet

### ISSUE THREAD

**Issue by sunbrother99** [PaddlePaddle/Paddle#19678]
GPU多卡训练两层的语言模型用两张卡就可以正常训练，用四张卡会挂掉，并提示如下paddle.fluid.core_avx.EnforceNotMet: The number(2) of samples of current batch is less than the count(2) of devices(GPU), currently, it is not allowed.  at [/paddle/paddle/fluid/framework/parallel_executor.cc:660]
如果把模型改成四层，四张卡就可以训练，不报错。
看样子是一张卡上一层模型
请问怎么改成卡数与批大小相关而不是与模型层数相关？

**Comment by seiriosPlus** [comment]
batchsize目前是多少？

**Comment by sunbrother99** [comment]
Bathsize是4  16  20  都试过，都不行，且是相同的错误，只有改层数才有变化能跑通

发自我的vivo智能手机

tangwei12 <notifications@github.com>编写：

**Comment by seiriosPlus** [comment]
目前使用的是数据并行的模式， 就是卡数与批大小相关而不是与模型层数的。

你的样本数总体有多少？

**Comment by sunbrother99** [comment]
大约4万多样本，模型是官方的paddleNLP下的model下的语言模型，基本没改
