### ISSUE TITLE
nlp中input的lod-level为2时模型设计问题。

### ISSUE THREAD

**Issue by yuanquan123** [PaddlePaddle/Paddle#19685]
如果我的输入形状是[Batch_size, sequece_len1,  sequece_len2]这样的，进行embedding之后形状变为[Batch_size, sequece_len1,  sequece_len2, emb_dim]，然后我想对sequece_len2这个维度进行pooling操作，请问我该如何实现？
下面这种思路正确吗，实际使用中会报错
test_input = fluid.layers.data(name='test1', shape=[1, 1], dtype='int64', lod_level=2)
test_input_emb = fluid.layers.embedding(input=test_input, size=[vocab_size, 100])
test_sentence_emb = fluid.layers.sequence_pool(test_input_emb, type='sum')

**Comment by seiriosPlus** [comment]
目前lod-level=2在过sequence_pool的时候会报错？

**Comment by yuanquan123** [comment]
是的
  File "nn.py", line 113, in fit
    gcn_repre_real = fluid.layers.sequence_pool(gcn_repre, pool_type='sum')
  File "nn.py", line 228, in <module>
    nn.fit(config)
C++ Callstacks: 
Enforce failed. Expected lod.size() == 1UL, but received lod.size():2 != 1UL:1.
Only support one level sequence now. at [/paddle/paddle/fluid/operators/sequence_ops/sequence_pool_op.h:40]

**Comment by seiriosPlus** [comment]
目前看是op不支持， 并且我们embedding目前应该也不支持lod-level2的
