### ISSUE TITLE
fluid如何实现像numpy那样的高级（magic）索引？

### ISSUE THREAD

**Issue by lsy641** [PaddlePaddle/Paddle#19697]
我在改模型结构时候，需要对一个batch内的输出进行索引，每个example对输出取得下标不同。
问题就是对于一个矩阵，如何做到每行取不同列上的数？我用numpy的时候，magic索引可以做到。

就算我想一个一个example的去索引，但batchsize是未知的，不能用循环。

**Comment by parap1uie-s** [comment]
貌似可以用fluid.layers.gather
