### ISSUE TITLE
训练到一定的阶段，loss变成NaN，每次都是在固定的次数变成NaN

### ISSUE THREAD

**Issue by Exception-star** [PaddlePaddle/Paddle#19694]
![image](https://user-images.githubusercontent.com/53971568/64470701-6576a380-d17a-11e9-8f63-be0a1a90f854.png)

每次都是在这变成NaN，数据是没有问题的，删除了一半数据量，也是在600变成NaN。

减少学习率，情况一样，
是否含有脏数据，我删除后面一半数据进行训练，情况也一样，
修改dropout的概率，从0.1改成0.9，也会出现，只是NaN往后推移了

**Comment by phlrain** [comment]
有尝试过其他例如grad clip，layer norm防止过拟合的策略么

**Comment by Exception-star** [comment]
> 有尝试过其他例如grad clip，layer norm防止过拟合的策略么

![image](https://user-images.githubusercontent.com/53971568/64959961-e2192880-d8c4-11e9-8cf9-ed667549d456.png)
我找到原因了，是softmax_with_cross_entropy计算不稳定，导致出现NaN，我改成了
下面这种，NaN就没有再出现过。
```
logit = fluid.layers.softmax(pred, use_cudnn=False)
loss = fluid.layers.cross_entropy(logit, label, ignore_index=255)
```

**Comment by zhangyimi** [comment]
发现了同样的问题，不管batch多大，模型更新一次后一定会变成NaN。
把softmax_with_cross_entropy换成softmax和corss_entropy就可以了。

**Comment by phlrain** [comment]
> 发现了同样的问题，不管batch多大，模型更新一次后一定会变成NaN。
> 把softmax_with_cross_entropy换成softmax和corss_entropy就可以了。

能方便提供下复现的环境么，我们方便定位解决问题
