### ISSUE TITLE
无法复现《Python 预测 API介绍》官网结果

### ISSUE THREAD

**Issue by RockWater** [PaddlePaddle/Paddle#19698]
按照官网https://www.paddlepaddle.org.cn/documentation/docs/zh/1.5/advanced_usage/deploy/inference/python_infer_cn.html
执行python resnet50_infer.py --model_dir model --prog_file model --params_file params --batch_size 2
错误如下：
Traceback (most recent call last):
  File "infer.py", line 53, in <module>
    main()
  File "infer.py", line 18, in main
    predictor = create_paddle_predictor(config)
paddle.fluid.core_avx.EnforceNotMet: Cannot open file model/__model__ at [/home/teamcity/work/ef54dc8a5b211854/paddle/fluid/inference/api/analysis_predictor.cc:639]

**Comment by OliverLPH** [comment]
看log就是路径问题，把这个`resnet50_infer.py`脚本放到下载模型的文件夹试试

**Comment by RockWater** [comment]
> 看log就是路径问题，把这个`resnet50_infer.py`脚本放到下载模型的文件夹试试
不行呢。都试过了呢。是不是可能是模型版本格式不兼容？
