### ISSUE TITLE
Unused input were processed

### ISSUE THREAD

**Issue by lzhao4ever** [PaddlePaddle/Paddle#1969]
I have input seq0, seq1. In my configure file, only seq0 were used. But seq1 is still in the model and x1 were processed during training and caused size 0 error. The following code illustrate the problem:

seq0=data("seq0")
seq1=data("seq1")
x0=fc(seq0)
x1=fc(seq1)
y=fc(x0)
outputs(y)

**Comment by lcy-seso** [comment]
close this issue due to inactivity.
