### ISSUE TITLE
并发运行，怎么保存每次卷积后的结果

### ISSUE THREAD

**Issue by hg9102** [PaddlePaddle/Paddle#19691]
create_py_reader_by_data

for epoch_id in range(10):
             reader.start()
             try:
                 while True:
                     exe.run(fetch_list=[loss.name])
             except fluid.core.EOFException:
                 reader.reset()

**Comment by phlrain** [comment]
是要fetch 卷积的结果，还是要save到本地，下次reload

**Comment by hg9102** [comment]
@phlrain 保存卷积结果，观察整个过程的变化
