### ISSUE TITLE
什么时候能对tensor做einsum？

### ISSUE THREAD

**Issue by lsy641** [PaddlePaddle/Paddle#19704]
目前只有elemenwise_mul  不够用，希望能出einsum

**Comment by tensor-tang** [comment]
请问您是否有对标的运算逻辑的链接，可以贴一个。

**Comment by lsy641** [comment]
> 请问您是否有对标的运算逻辑的链接，可以贴一个。
谢谢你的回复，einsum是爱因斯坦标记法，通过标记，可以对两个矩阵进行任意的方法求和。链接在下面：
https://cloud.tencent.com/developer/news/437348
举个例子，比方A矩阵维度是abc，B矩阵维度是ac，我想让他们相乘abc * ac = abc，做的运算是对于每一行ai，都做bc*c。
在einsum标记法中只需要指明“abc，ac->abc”就能做响应的求和运算。
numpy.einsum有这个接口

**Comment by zhangyimi** [comment]
同求，numpy，tensorflow，pytorch都有。

**Comment by BeamBin** [comment]
paddle现在支持einsum了吗，，，numpy，tensorflow，pytorch都有

**Comment by Vonderland** [comment]
+1
同问什么之后能支持einsum呢

**Comment by liguoyu666** [comment]
同求，2.0rc还没有einsum

**Comment by ntuyt** [comment]
2.0rc还没有einsum
