### ISSUE TITLE
希望增加合并多个参数文件的方法

### ISSUE THREAD

**Issue by yangzhifeng-code** [PaddlePaddle/Paddle#19703]
fluid中采用分布式训练后，调用save_inference_model方法，即使指定了参数文件名，保存的参数仍然是是分散在各个文件中的。
因为要用训练好的模型和参数，在c++线上加载用于预测，多个文件不太方便，希望增加一个方法，能够将这些分散的参数文件合并在一个文件中。
进一步，如果可行的话，希望可以有将模型和参数保存在单个文件中的方法。

**Comment by lgone2000** [comment]
fluid.io.save_inference_model(
        dirname='test',
        feeded_var_names=['a'],
        target_vars=[d],
        executor=exe,
        main_program=fluid.default_main_program(),
        model_filename='model',
        params_filename='params')

指定params_filename 可以存成一个文件

**Comment by yangzhifeng-code** [comment]
@lgone2000 即使这样写，存储的参数文件也是分散的，因为运行环境是分布式训练。我是百度员工，这个问题我和paddlepaddle群里的值班同学确认过的。希望开发人员能够解决这个问题，这个问题导致线上加载不是很方便。

**Comment by jiangjiajun** [comment]
加载参数分散存储的模型后，再保存一次即可
https://github.com/PaddlePaddle/X2Paddle/blob/develop/tools/merge_params.py
```
python merge_params.py paddle_model/inference_model  new_model_dir
```
