### ISSUE TITLE
paddle::platform::EnforceNotMet'   what():  Cannot get attribute height_sections by type 

### ISSUE THREAD

**Issue by sunhf** [PaddlePaddle/Paddle#19705]
使用c++来预测，依赖baidu/paddlepaddle/paddle@v1.4.1_pb32@git_branch
模型是基于1.5.0的gpu版本训练的
加载模型时出core，错误信息为：
I0909 13:19:23.993065 19076 analysis_predictor.cc:152] load parameters 
terminate called after throwing an instance of 'paddle::platform::EnforceNotMet'
  what():  Cannot get attribute height_sections by type std::vector<int, std::allocator<int> >, its type is std::vector<long, std::allocator<long> > at [baidu/paddlepaddle/paddle/paddle/fluid/framework/attribute.h:42]

具体栈信息如下。
#9  0x000000000130a0c3 in paddle::framework::OpRegistry::CreateOp(paddle::framework::OpDesc const&) ()
#10 0x00000000012fa06d in paddle::framework::NaiveExecutor::CreateOps(paddle::framework::ProgramDesc const&, int, bool) ()
#11 0x00000000012faa9b in paddle::framework::NaiveExecutor::Prepare(paddle::framework::Scope*, paddle::framework::ProgramDesc const&, int, bool) ()
---Type <return> to continue, or q <return> to quit---
#12 0x00000000006db41a in paddle::AnalysisPredictor::PrepareExecutor() ()
#13 0x00000000006e2785 in paddle::AnalysisPredictor::Init(std::shared_ptr<paddle::framework::Scope> const&, std::shared_ptr<paddle::framework::ProgramDesc> const&) ()
#14 0x00000000006e2bf7 in std::unique_ptr<paddle::PaddlePredictor, std::default_delete<paddle::PaddlePredictor> > paddle::CreatePaddlePredictor<paddle::AnalysisConfig, (paddle::PaddleEngineKind)2>(paddle::AnalysisConfig const&) ()
#15 0x00000000006e3811 in std::unique_ptr<paddle::PaddlePredictor, std::default_delete<paddle::PaddlePredictor> > paddle::CreatePaddlePredictor<paddle::AnalysisConfig>(paddle::AnalysisConfig const&) ()

**Comment by tensor-tang** [comment]
麻烦说下模型是什么版本生成的

**Comment by sunhf** [comment]
模型在问题描述中说过了，是1.5.0的，应该是版本不一致导致，但目前有1.5.0对应的c++依赖库吗

**Comment by tensor-tang** [comment]
好的，由于您是内部版本问题，我们内部解决。
