### ISSUE TITLE
paddle 1.5.1 支持的cuda 和 driver 版本是啥？

### ISSUE THREAD

**Issue by dongfangyixi** [PaddlePaddle/Paddle#19718]
环境： cuda 9.2 nvidia driver: 396.26  paddlepaddle 1.5.1  tensorflow 1.9.0
test script:
tensorflow: 
`
import tensorflow as tf
tf.Session()
`
 paddle:
`
from paddle.fluid import core
core.CUDAPlace(0)
`

tensorflow 可以正常运行，cuda 和 driver的版本是匹配的

paddle 报错：
paddle.fluid.core_avx.EnforceNotMet: cudaGetDeviceCount failed in paddle::platform::GetCUDADeviceCount: CUDA driver version is insufficient for CUDA runtime version at [/paddle/paddle/fluid/platform/gpu_info.cc:97] 

请问paddle 1.5.1 支持的cuda 和driver版本是什么

**Comment by dongfangyixi** [comment]
首先，测试环境的cuda 和 cuda driver 可以配对的
![image](https://user-images.githubusercontent.com/6477100/64524833-03f93500-d332-11e9-91a1-a7b01fe090d8.png)
![image](https://user-images.githubusercontent.com/6477100/64524876-23905d80-d332-11e9-9703-1d3729f6452f.png)
![image](https://user-images.githubusercontent.com/6477100/64524890-2a1ed500-d332-11e9-82ec-246b5e6fc4ea.png)

然后 tf和 torch 都没有任何问题。

最后 paddle 1.4.1 运行和没有问题
安装了 1.5.1 就会报这样的错误

请问是什么原因呢

**Comment by imistyrain** [comment]
1.5.1默认好像是cuda10了
```
sudo pip install paddlepaddle-gpu==1.5.1post97
```

**Comment by adaxi987** [comment]
楼上正解
