### ISSUE TITLE
paddle develop分支源码编译错误

### ISSUE THREAD

**Issue by LDOUBLEV** [PaddlePaddle/Paddle#19717]
- 版本、环境信息：
    1）PaddlePaddle版本：最新的develop分支，时间2019-9-9   12:00-17:00
    3）GPU：TeslaV100

- 安装方式信息：
1）docker安装： nvidia-docker run --name paddle-test -v $PWD:/paddle --network=host -it hub.baidubce.com/paddlepaddle/paddle:latest-dev /bin/bash

2）编译命令：cmake .. -DPY_VERSION=2.7 -DWITH_GPU=ON -DWITH_TESTING=OFF -DCMAKE_BUILD_TYPE=Release

fatal: no tag exactly matches 'c78a4781bf57e888937672f8f767b7e7eb0002dd'
![image](https://user-images.githubusercontent.com/26592129/64518553-f9846e80-d324-11e9-8f15-7e01d3215b9c.png)
![image](https://user-images.githubusercontent.com/26592129/64518656-23d62c00-d325-11e9-9b74-2fba2257fb3e.png)

**Comment by LDOUBLEV** [comment]
又重新编译了一下，这次没有报错，cmake和docker镜像都没改变，可以编译通过，但是前两次编译就不通过，可能是随机报错？

**Comment by tensor-tang** [comment]
也有可能是网络问题，因为这个tag好像不是paddle的
