### ISSUE TITLE
Abnormal exit code 139 on Paddle-fluid1.5.0, suspected to be a memory usage problem

### ISSUE THREAD

**Issue by miziki** [PaddlePaddle/Paddle#19712]
paddle fluid 1.5.0
CentOS release 6.3 (Final)
Tesla P40
![image](https://user-images.githubusercontent.com/6149580/64516603-52520800-d321-11e9-8885-e515ad16b1b9.png)
![image](https://user-images.githubusercontent.com/6149580/64516680-77467b00-d321-11e9-9712-3c6a65f23847.png)

**Comment by tensor-tang** [comment]
请问使用的背景是什么，多机多卡？
