### ISSUE TITLE
fleet版本的 回归 或者多分类（比如10类）任务 demo

### ISSUE THREAD

**Issue by lizhiqings** [PaddlePaddle/Paddle#19725]
因为最近用fleet 训练回归任务 发现无法收敛 loss居高不下（mse）

**Comment by seiriosPlus** [comment]
是采用的同步训练还是异步训练？

**Comment by lizhiqings** [comment]
都可以 两个都有的话 可以都发来看下

发件人: tangwei12 <notifications@github.com>
答复: PaddlePaddle/Paddle <reply@reply.github.com>
日期: 2019年9月10日 星期二 上午11:13
收件人: PaddlePaddle/Paddle <Paddle@noreply.github.com>
抄送: "Li,Zhiqing" <lizhiqing@baidu.com>, Author <author@noreply.github.com>
主题: Re: [PaddlePaddle/Paddle] fleet版本的 回归 或者多分类（比如10类）任务 demo (#19725)


是采用的同步训练还是异步训练？

**Comment by seiriosPlus** [comment]
fleet本质上只是一套API。  你可以用单机+小数据集验证效果，然后再上fleet做大规模验证。

目前我们相关的示例有这些可以参考： https://github.com/PaddlePaddle/Fleet/tree/develop/examples

多分类的任务可以参考https://github.com/PaddlePaddle/models中相关的多分类模型。

**Comment by lizhiqings** [comment]
好的 我先看看

发件人: tangwei12 <notifications@github.com>
答复: PaddlePaddle/Paddle <reply@reply.github.com>
日期: 2019年9月10日 星期二 下午3:45
收件人: PaddlePaddle/Paddle <Paddle@noreply.github.com>
抄送: "Li,Zhiqing" <lizhiqing@baidu.com>, Author <author@noreply.github.com>
主题: Re: [PaddlePaddle/Paddle] fleet版本的 回归 或者多分类（比如10类）任务 demo (#19725)

参考

**Comment by lizhiqings** [comment]
第二个链接 返回404

发件人: tangwei12 <notifications@github.com>
答复: PaddlePaddle/Paddle <reply@reply.github.com>
日期: 2019年9月10日 星期二 下午3:45
收件人: PaddlePaddle/Paddle <Paddle@noreply.github.com>
抄送: "Li,Zhiqing" <lizhiqing@baidu.com>, Author <author@noreply.github.com>
主题: Re: [PaddlePaddle/Paddle] fleet版本的 回归 或者多分类（比如10类）任务 demo (#19725)

多分类的任务可以参考

**Comment by seiriosPlus** [comment]
https://github.com/PaddlePaddle/models
