### ISSUE TITLE
Freeze Weights

### ISSUE THREAD

**Issue by prakharg24** [PaddlePaddle/Paddle#19724]
I am trying to implement the MobileNet-SSD model from here,
https://github.com/PaddlePaddle/models/tree/develop/PaddleCV/ssd

I have a dictionary of layer names which I want to freeze and let the rest of them train.

How can I achieve that?
 If you can give an answer in context with the code above, that will be the best, but any answer is appreciated

I tried a few things, not sure where the issue is ->
https://github.com/PaddlePaddle/Paddle/issues/19622#issuecomment-529288426

Thank You

**Comment by prakharg24** [comment]
I tried a few things, not sure where the issue is ->
https://github.com/PaddlePaddle/Paddle/issues/19622#issuecomment-529288426

**Comment by NHZlX** [comment]
Step 1: Observe all parameter names of the current network through the following code and determine the name of the convolution core weight (parameter) to be fixed.


```
for param in fluid.default_main_program().global_block().all_parameters():
    print param.name
```

Step2: Get the corresponding variable according to parameter name:

```
target_var = fluid.default_main_program().global_block().var(param_name)
```


- step3 set variable stop_gradient=True
```
target_var.stop_gradient=True
```

**Comment by prakharg24** [comment]
My prog is actually not the default program, and I am also trying to load some weight values and then freeze the connections, so this is the code that I added,

```
     for param in train_prog.global_block().all_parameters():
        pd_var = fluid.global_scope().find_var(param.name)
        pd_param = pd_var.get_tensor()
        if(param.name in pd_weights):
            print("load: {}".format(param.name))
            pd_param.set(pd_weights[param.name], place)

            target_var = train_prog.global_block().var(param.name)
            target_var.stop_gradient = True
```

And to check whether it worked or not, I am printing the weights of the first layer after every epoch (the first layer is one of those layers whose gradient should be stopped). This is what I did,
```
                for param in train_prog.global_block().all_parameters():
                    pd_var = fluid.global_scope().find_var(param.name)
                    pd_param = pd_var.get_tensor()
                    if(param.name in pd_weights):
                        print("load: {}".format(param.name))
                        print(np.shape(pd_param))
                        print(np.array(pd_param))
                        break
```
And I can see these weights evolving (they are not fixed)

What I think is going wrong, the optimizer.minimize is called before all of these changes are done. So the stop_gradient is not really reflected in the final gradient calculation
I tried different versions of this to see how the optimizer is affecting it, you can see the errors that I got here ->
https://github.com/PaddlePaddle/Paddle/issues/19622#issuecomment-529288426


Specifically, can you tell exactly how in context to the code mentioned, can I freeze the weights?

Thank You

**Comment by NHZlX** [comment]
You can try call optimizer.minimize after these changes are done.

**Comment by prakharg24** [comment]
@NHZlX  I tried doing that in various ways. I tried putting the stop_gradient part inside the build_program function, right before the optimizer.loss

I also tried commenting optimizer.loss inside the function and then doing it after the stop_gradient part is done. I even tried doing optimizer.loss twice, once before as it was already in the code and once after I had done the stop_gradient part.

I have actually mentioned all these and what error I got here ->
https://github.com/PaddlePaddle/Paddle/issues/19622#issuecomment-529288426

Can you please look at the link above and seeing the errors suggest what might have gone wrong?

Thank You
