### ISSUE TITLE
建议支持物体检测的类间nms

### ISSUE THREAD

**Issue by ellinyang** [PaddlePaddle/Paddle#19744]
最近在用ssd训练一批数据，发现同一物体会被模型检测出多个框，且各个框类别不同，因此无法用普通的nms过滤。看到你们开发了内间nms，不知是什么原因一直没合入，希望能早点添加这个功能，作为nms扩展选项。
待合入的类间nms :https://github.com/PaddlePaddle/Paddle/pull/18607/files

**Comment by jerrywgz** [comment]
已支持 https://github.com/PaddlePaddle/Paddle/pull/19228
