### ISSUE TITLE
1.5.1.post107版本动态图下面使用GPU计算equal/not_equal终止,cpu正常

### ISSUE THREAD

**Issue by L-lei** [PaddlePaddle/Paddle#19741]
def run():
    use_cudnn = False
    place = fluid.CUDAPlace(0) if use_cudnn else fluid.CPUPlace()
    with fluid.dygraph.guard(place=place):
        label = to_variable(np.array([-1, 1, -1, -1]).astype('float32'))
        limit = to_variable(np.array([1, 1, 1, 1]).astype('float32'))
        less = fluid.layers.equal(x=label, y=limit)
        print(less)

**Comment by JiabinYang** [comment]
same as #19499

**Comment by JiabinYang** [comment]
正在支持
