### ISSUE TITLE
CPU多核使用DatasetFactory，Queue模式CPU利用率30%， Memory模式CPU利用率是90%

### ISSUE THREAD

**Issue by sshilei** [PaddlePaddle/Paddle#19755]
fluid 1.5.1

其他代码都相同，仅仅是dataset模式不同。

Queue模式
![image](https://user-images.githubusercontent.com/18701471/64665302-9ad60680-d484-11e9-8578-92babd705628.png)

Memory模式
![image](https://user-images.githubusercontent.com/18701471/64665406-028c5180-d485-11e9-81b4-79dc6608d5c7.png)

**Comment by sshilei** [comment]
补充一下，应该不是IO的问题。原因如下，

我有两版代码：模型网络结果和训练集都是相同的， 第一版代码使用Queue模式，CPU利用率也都能达到90%， 第二版模型在第一版基础上进行了一些封装和可扩展的工作，之后同样是Queue模式，CPU利用率就降低了，而且训练变慢了

辛苦帮忙提供一下，有哪些原因会导致dataset的Queue模式CPU利用率下降

**Comment by seiriosPlus** [comment]
train_from_dataset把debug=True打开，看一下训练的耗时占比？
