### ISSUE TITLE
 paddle.fluid.layers.range()维度问题

### ISSUE THREAD

**Issue by xubin1994** [PaddlePaddle/Paddle#19766]
我想实现一个meshgrid(height,width)的功能，但我测试range这个接口只能得到的teonsor的维度是dims =-1,这样还导致我无法对产生的变量reshape为一个向量，也就无法实现矩阵乘，请问有什么解决办法或者实现方式吗？
#print输出的结果test的dims = -1,不像tensorflow那样为(height,)
test2 = paddle.fluid.layers.range(0, height, 1, 'float32')
#以下代码报错
test2 = paddle.fluid.layers.reshape(test2,[height,1])

**Comment by JiabinYang** [comment]
能麻烦您po一下错误的log么

**Comment by JiabinYang** [comment]
或者您试试吧[height，1]改成[height，-1]

**Comment by xubin1994** [comment]
> 或者您试试吧 [height，1] 改成 [height，-1]
我就想实现下面逻辑的代码，可是一直通不过，即使改成[-1,width]也是一样有问题
        vector1 = paddle.fluid.layers.ones(shape=[height,1], dtype='float32')
        vector2 = paddle.fluid.layers.reshape(paddle.fluid.layers.range(0, width, 1, 'float32'),[1,width])
        x_t = paddle.fluid.layers.matmul(vector1,vector2)
改成[-1,width]的错误日志如下：
File "D:/IresNet-PaddlePaddle/stn.py", line 111, in __meshgrid
    x_t = paddle.fluid.layers.matmul(vector1,vector2)
  File "D:\ProgramData\Anaconda3\envs\deeplearning\lib\site-packages\paddle\fluid\layers\nn.py", line 5243, in matmul
    __check_input(x, y)
  File "D:\ProgramData\Anaconda3\envs\deeplearning\lib\site-packages\paddle\fluid\layers\nn.py", line 5232, in __check_input
    (x_shape, y_shape))
ValueError: Invalid inputs for matmul. x: [540, 1], y: [-1, 960]

很是不解，PaddlePaddle对维度的逻辑到底是怎么设计的，为什么对range(0, width）不能resize成[1,width]的维度，这感觉有点反常，tensorflow，pytorch都是没有问题的。

**Comment by JiabinYang** [comment]
这个地方我们后期会进行修改的，感谢建议

**Comment by xubin1994** [comment]
> 这个地方我们后期会进行修改的，感谢建议

那我现在这个逻辑的代码有其它正确的实现方式吗？

**Comment by JiabinYang** [comment]
这个使用[height, -1]会有问题么

**Comment by xubin1994** [comment]
> 这个使用 [height, -1] 会有问题么

矩阵乘那一步报错，我现在的代码是对range(0,width)resize成[-1,width]，我的height=540,width = 960
ValueError: Invalid inputs for matmul. x: [540, 1], y: [-1, 960]，详细的日志见上面

**Comment by Shixiaowei02** [comment]
> > 这个使用 [height, -1] 会有问题么
> 
> 矩阵乘那一步报错，我现在的代码是对range(0,width)resize成[-1,width]，我的height=540,width = 960
> ValueError: Invalid inputs for matmul. x: [540, 1], y: [-1, 960]，详细的日志见上面

这个问题已经在修复，预计 1.6 版本可合入。

**Comment by xubin1994** [comment]
> > > 这个使用 [height, -1] 会有问题么
> > 
> > 
> > 矩阵乘那一步报错，我现在的代码是对 range (0,width) resize 成 [-1,width]，我的 height=540,width = 960
> > ValueError: Invalid inputs for matmul. x: [540, 1], y: [-1, 960]，详细的日志见上面
> 
> 这个问题已经在修复，预计 1.6 版本可合入。

我还是比较关心这个逻辑的代码有其它正确的实现方式吗？我卡在这了···

**Comment by jiangjiajun** [comment]
> > > > 这个使用 [height, -1] 会有问题么
> > > 
> > > 
> > > 矩阵乘那一步报错，我现在的代码是对 range (0,width) resize 成 [-1,width]，我的 height=540,width = 960
> > > ValueError: Invalid inputs for matmul. x: [540, 1], y: [-1, 960]，详细的日志见上面
> > 
> > 
> > 这个问题已经在修复，预计 1.6 版本可合入。
> 
> 我还是比较关心这个逻辑的代码有其它正确的实现方式吗？我卡在这了···

可以这样来写，在reshape时，将shape参数不要写成`[1, width]`，而是`[1, -1]`
```
vector1 = fluid.layers.ones(shape=[height,1], dtype='float32')
vector2 = fluid.layers.range(0, width, 1, 'float32')
vector2 = fluid.layers.reshape(vector2, shape=[1, -1])
x_t = fluid.layers.matmul(vector1,vector2)
```

**Comment by xubin1994** [comment]
> > > > > 这个使用 [height, -1] 会有问题么
> > > > 
> > > > 
> > > > 矩阵乘那一步报错，我现在的代码是对 range (0,width) resize 成 [-1,width]，我的 height=540,width = 960
> > > > ValueError: Invalid inputs for matmul. x: [540, 1], y: [-1, 960]，详细的日志见上面
> > > 
> > > 
> > > 这个问题已经在修复，预计 1.6 版本可合入。
> > 
> > 
> > 我还是比较关心这个逻辑的代码有其它正确的实现方式吗？我卡在这了・・・
> 
> 可以这样来写，在 reshape 时，将 shape 参数不要写成 `[1, width]`，而是 `[1, -1]`
> 
> ```
> vector1 = fluid.layers.ones(shape=[height,1], dtype='float32')
> vector2 = fluid.layers.range(0, width, 1, 'float32')
> vector2 = fluid.layers.reshape(vector2, shape=[1, -1])
> x_t = fluid.layers.matmul(vector1,vector2)
> ```

你这个方法似乎是可行的，另外假设我有一个4维度的tensor U,shape为[batch,channels,height,width],但是我利用batch = U.shape[0]得到的却是-1，而不是我实际传入的batch大小，请问在PadddlePaddle中我怎么取得实际的batch数目，因为有时候我需要对一个tensor复制batch份，所以我想在静态图中取的batch的真实数值

**Comment by jiangjiajun** [comment]
可以用fluid.layers.shape和slice操作组合获得实际的batch数

**Comment by Colorfu1** [comment]
> > > > > > 这个使用 [height, -1] 会有问题么
> > > > > 
> > > > > 
> > > > > 矩阵乘那一步报错，我现在的代码是对 range (0,width) resize 成 [-1,width]，我的 height=540,width = 960
> > > > > ValueError: Invalid inputs for matmul. x: [540, 1], y: [-1, 960]，详细的日志见上面
> > > > 
> > > > 
> > > > 这个问题已经在修复，预计 1.6 版本可合入。
> > > 
> > > 
> > > 我还是比较关心这个逻辑的代码有其它正确的实现方式吗？我卡在这了・・・
> > 
> > 
> > 可以这样来写，在 reshape 时，将 shape 参数不要写成 `[1, width]`，而是 `[1, -1]`
> > ```
> > vector1 = fluid.layers.ones(shape=[height,1], dtype='float32')
> > vector2 = fluid.layers.range(0, width, 1, 'float32')
> > vector2 = fluid.layers.reshape(vector2, shape=[1, -1])
> > x_t = fluid.layers.matmul(vector1,vector2)
> > ```
> 
> 你这个方法似乎是可行的，另外假设我有一个4维度的tensor U,shape为[batch,channels,height,width],但是我利用batch = U.shape[0]得到的却是-1，而不是我实际传入的batch大小，请问在PadddlePaddle中我怎么取得实际的batch数目，因为有时候我需要对一个tensor复制batch份，所以我想在静态图中取的batch的真实数值

可以试着先进行unsqueeze操作，比如在后面增加一个维度，得到一个(-1, 1)的tensor，其实就是(width, 1)维度的tensor，应该可以直接使用了。
