### ISSUE TITLE
Setting up our CI system in our US office.

### ISSUE THREAD

**Issue by reyoung** [PaddlePaddle/Paddle#1978]
We deploy our custom CI system in our Beijing office for GPU unit tests and building Docker images, but the CI System always failed because of bad internet environment in China. The GitHub and docker hub access is intermittent in Beijing. We cannot let our custom CI system send emails to our developers because it is noising now.

Another purpose is we use our CI system to build Paddle docker image automatically. If we set up our CI system in US office, we could push our latest image to Docker Hub immediately.

**Comment by jacquesqiao** [comment]
done by @helinwang
