### ISSUE TITLE
fluid.layers.reduce_mean时维度不正确 Enforce failed. Expected dims[i] < x_rank, but received dims[i]:2 >= x_rank:2.

### ISSUE THREAD

**Issue by leonleeldc** [PaddlePaddle/Paddle#19796]
Hi, 我没有发现这是什么bug，我跟我的的tensorflow版本对照发现维度都一样的，可是，paddle这边在运行到minimize这个generator的loss出错。能帮忙看看吗？

```python
    grad_clip = float(5.0)  # keep the same with the previous setting
    fluid.clip.set_gradient_clip(
        clip=fluid.clip.GradientClipByGlobalNorm(
            clip_norm=grad_clip))
    g_train_op = g_optimizer.minimize(g_loss)
```

从下面我找到具体错误的行是在求variance时出错，说是维度不对：

```python
        variance = squared_difference(inputs, mean)
        print('the shape pf variance at relational_memory_dict.py and the shape of inputs_rank  and norm_axes = ',(variance.shape, inputs_rank, norm_axes))
        #fluid.layers.Print(variance)
        #variance.stop_gradient = True
        variance = fluid.layers.reduce_mean(variance, norm_axes, keep_dim=True)
```

下面是我运行的command line:

```shell
/usr/bin/python3.6 -u /media/data2/dingcheng/workspace/baidu/ccl/MetaCotRelGAN/real/experiments/coco_relgan.py 0 4 0.1 1.0 True False test
```

错误信息如下：

```shell
Traceback (most recent call last):
  File "run_dict.py", line 151, in <module>
    main()
  File "run_dict.py", line 144, in main
    real_train_dict(main_program, generator, generator_meta,  mediator, discriminator, oracle_loader, config)
  File "/media/data2/dingcheng/workspace/baidu/ccl/MetaCotRelGAN/real/real_gan/real_train_dict.py", line 298, in real_train_dict
    md_pretrain_loss_fake)
  File "/media/data2/dingcheng/workspace/baidu/ccl/MetaCotRelGAN/real/real_gan/real_train_dict.py", line 578, in get_train_ops
    g_train_op = g_optimizer.minimize(g_loss)
  File "<decorator-gen-20>", line 2, in minimize
  File "/usr/local/lib/python3.6/dist-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
    return wrapped_func(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/paddle/fluid/dygraph/base.py", line 87, in __impl__
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/paddle/fluid/optimizer.py", line 615, in minimize
    no_grad_set=no_grad_set)
  File "/usr/local/lib/python3.6/dist-packages/paddle/fluid/optimizer.py", line 496, in backward
    no_grad_set, callbacks)
  File "/usr/local/lib/python3.6/dist-packages/paddle/fluid/backward.py", line 706, in append_backward
    _append_backward_vars_(root_block, fwd_op_num, grad_to_var, grad_info_map)
  File "/usr/local/lib/python3.6/dist-packages/paddle/fluid/backward.py", line 518, in _append_backward_vars_
    op_desc.infer_shape(block.desc)
paddle.fluid.core_avx.EnforceNotMet: Invoke operator reduce_mean_grad error.
Python Call stacks: 
  File "/usr/local/lib/python3.6/dist-packages/paddle/fluid/framework.py", line 1824, in append_op
    attrs=kwargs.get("attrs", None))
  File "/usr/local/lib/python3.6/dist-packages/paddle/fluid/layer_helper.py", line 43, in append_op
    return self.main_program.current_block().append_op(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/paddle/fluid/layers/nn.py", line 5000, in reduce_mean
    'reduce_all': True if dim == None else False
  File "/media/data2/dingcheng/workspace/baidu/ccl/MetaCotRelGAN/utils/models/relational_memory_dict.py", line 335, in _layer_norm_compute
    variance = fluid.layers.reduce_mean(variance, norm_axes, keep_dim=True)
  File "/media/data2/dingcheng/workspace/baidu/ccl/MetaCotRelGAN/utils/models/relational_memory_dict.py", line 282, in _attend_over_memory
    memory = self._layer_norm_compute(memory+memory_mlp, w_dict, self.parent_scope_name+ '/aom_ln_mlp')
  File "/media/data2/dingcheng/workspace/baidu/ccl/MetaCotRelGAN/utils/models/relational_memory_dict.py", line 377, in _build
    next_memory, w_dict = self._attend_over_memory(memory_plus_input, w_dict, create_variable)  # [B, N + 1, V * H]
  File "/media/data2/dingcheng/workspace/baidu/ccl/MetaCotRelGAN/utils/models/relational_memory_dict.py", line 405, in __call__
    outputs = self._build(*args, **kwargs)
  File "/media/data2/dingcheng/workspace/baidu/ccl/MetaCotRelGAN/models/rmc_vanilla_dict.py", line 67, in generator
    mem_o_t, h_t, w_dict = gen_mem(x_t, h_tm1, w_dict)
  File "/media/data2/dingcheng/workspace/baidu/ccl/MetaCotRelGAN/real/real_gan/real_train_dict.py", line 92, in real_train_dict
    start_token=config['start_token'])
  File "run_dict.py", line 144, in main
    real_train_dict(main_program, generator, generator_meta,  mediator, discriminator, oracle_loader, config)
  File "run_dict.py", line 151, in <module>
    main()
C++ Call stacks: 
Enforce failed. Expected dims[i] < x_rank, but received dims[i]:2 >= x_rank:2.
The dim should be in the range [-rank(input), rank(input)). at [/paddle/paddle/fluid/operators/reduce_ops/reduce_op.h:226]
PaddlePaddle Call Stacks: 
0       0x7f76f1c15487p std::string paddle::platform::GetTraceBackString<std::string const&>(std::string const&, char const*, int) + 375
1       0x7f76f1c15748p paddle::platform::EnforceNotMet::EnforceNotMet(std::string const&, char const*, int) + 40
2       0x7f76f2d7638dp paddle::operators::ReduceGradOp::InferShape(paddle::framework::InferShapeContext*) const + 1101
3       0x7f76f1d8ef0dp paddle::framework::OpDesc::InferShape(paddle::framework::BlockDesc const&) const + 909
4       0x7f76f1cc136cp
5       0x7f76f1c48856p
6             0x52393bp _PyCFunction_FastCallKeywords + 491
7             0x57dc05p
8             0x5762aep _PyEval_EvalFrameDefault + 1118
9             0x57eb2dp
10            0x57db5cp
11            0x5762aep _PyEval_EvalFrameDefault + 1118
12            0x57535fp
13            0x57ebebp
14            0x57db5cp
15            0x5762aep _PyEval_EvalFrameDefault + 1118
16            0x57535fp
17            0x57ebebp
18            0x57db5cp
19            0x576ff5p _PyEval_EvalFrameDefault + 4517
20            0x57dfd5p PyEval_EvalCodeEx + 645
21            0x4fbc34p
22            0x4e7cdap PyObject_Call + 58
23            0x5778ccp _PyEval_EvalFrameDefault + 6780
24            0x57e302p PyEval_EvalCodeEx + 1458
25            0x4fbc34p
26            0x4e7cdap PyObject_Call + 58
27            0x5778ccp _PyEval_EvalFrameDefault + 6780
28            0x575716p
29            0x57ebebp
30            0x57db5cp
31            0x5762aep _PyEval_EvalFrameDefault + 1118
32            0x57535fp
33            0x57ebebp
34            0x57db5cp
35            0x5762aep _PyEval_EvalFrameDefault + 1118
36            0x57eb2dp
37            0x57db5cp
38            0x5762aep _PyEval_EvalFrameDefault + 1118
39            0x57eb2dp
40            0x57db5cp
41            0x5762aep _PyEval_EvalFrameDefault + 1118
42            0x57eb2dp
43            0x57db5cp
44            0x5762aep _PyEval_EvalFrameDefault + 1118
45            0x57535fp
46            0x5750d3p PyEval_EvalCode + 35
47            0x5ea0c2p
48            0x5ea52ap PyRun_FileExFlags + 154
49            0x5ea2e7p PyRun_SimpleFileExFlags + 423
50            0x5ef7f3p Py_Main + 1571
51            0x4d1f09p main + 233
52      0x7f778627f830p __libc_start_main + 240
53            0x5e7b29p _start + 41


Process finished with exit code 0
```

**Comment by ysh329** [comment]
初步观察，问题出现在`variance = fluid.layers.reduce_mean(variance, norm_axes, keep_dim=True)`导致的维度不匹配，见报错：

```cpp
C++ Call stacks: 
Enforce failed. Expected dims[i] < x_rank, but received dims[i]:2 >= x_rank:2.
```

**Comment by leonleeldc** [comment]
现在我进一步debug, 问题还是没有解决，不过错误已经不在原来的variance那里了。我先把我改后的function贴一下：
   def _layer_norm_compute(self, inputs, w_dict, scope, epsilon=1e-12):
        inputs_shape = inputs.shape
        #print('input shape in relational_memeory_dict.py is=', inputs_shape)
        inputs_rank = len(inputs_shape)

        beta = w_dict[scope + "_beta"]
        gamma = w_dict[scope + "_gamma"]

        norm_axes = list(range(1, inputs_rank))
        #mean = fluid.layers.nn.reduce_mean(inputs, norm_axes, keep_dim=True)
        mean = fluid.layers.nn.reduce_mean(inputs, [-2, -1], keep_dim=True)
        #mean.stop_gradient = True
        # print('the shape pf mean at relational_memory_dict.py and the shape of inputs_rank  and norm_axes = ',
        #       (mean.shape, inputs_rank, norm_axes))
        inputs.stop_gradient = True
        variance = squared_difference(inputs, mean)
        #print('the shape pf variance at relational_memory_dict.py and the shape of inputs_rank  and norm_axes = ',(variance.shape, inputs_rank, norm_axes))
        #fluid.layers.Print(variance)
        #variance.stop_gradient = True
        variance = fluid.layers.reduce_mean(input=variance, dim=norm_axes, keep_dim=True)
        #variance = fluid.layers.reduce_mean(input=variance)
        #variance = fluid.layers.reshape(variance,[variance.shape[0],1,1])
        #print('the shape pf variance at relational_memory_dict.py and the shape of inputs_rank  and norm_axes = ',
              #(variance.shape, inputs_rank, norm_axes))
        inv = rsqrt(variance + epsilon)
        inv = fluid.layers.matmul(inv, fluid.layers.unsqueeze(gamma, [0]))
        tmp1 = fluid.layers.elementwise_mul(inputs, inv)
        tmp2 = fluid.layers.unsqueeze(beta, [0, 0])
        tmp2 = fluid.layers.expand(tmp2,[mean.shape[0], 2, 1])
        tmp3 = fluid.layers.expand(mean,[1, 2, beta.shape[0]])
        print('shape of tmps=', (tmp1.shape, tmp2.shape, tmp3.shape))
        tmp2 = tmp2 - tmp3
        res = fluid.layers.elementwise_mul(tmp1,tmp2)
        return res
错误现在在elementwise_mul(tmp1, tmp2)还是报的维度不一致。但是，我打印的shape是一致的：
shape of tmps= ((64, 2, 1536), (64, 2, 1536), (64, 2, 1536))
shape of tmps= ((64, 2, 512), (64, 2, 512), (64, 2, 512))
shape of tmps= ((64, 2, 512), (64, 2, 512), (64, 2, 512))
shape of tmps= ((64, 2, 1536), (64, 2, 1536), (64, 2, 1536))
shape of tmps= ((64, 2, 512), (64, 2, 512), (64, 2, 512))
shape of tmps= ((64, 2, 512), (64, 2, 512), (64, 2, 512))
for some reason, 在做回传时，
C++ Call stacks: 
Enforce failed. Expected x_dims.size() >= y_dims.size(), but received x_dims.size():2 < y_dims.size():3.
Rank of first input must >= rank of second input. at [/paddle/paddle/fluid/operators/elementwise/elementwise_op.h:185]
PaddlePaddle Call Stacks: 
0       0x7fe187212487p std::string paddle::platform::GetTraceBackString<std::string const&>(std::string const&, char const*, int) + 375
1       0x7fe187212748p paddle::platform::EnforceNotMet::EnforceNotMet(std::string const&, char const*, int) + 40
2       0x7fe188b76eb7p paddle::operators::ElementwiseOpGrad::InferShape(paddle::framework::InferShapeContext*) const + 1351
3       0x7fe18738bf0dp paddle::framework::OpDesc::InferShape(paddle::framework::BlockDesc const&) const + 909
4       0x7fe1872be36cp
5       0x7fe187245856p
6             0x52393bp _PyCFunction_FastCallKeywords + 491
7             0x57dc05p
8             0x5762aep _PyEval_EvalFrameDefault + 1118
9             0x57eb2dp
10            0x57db5cp
11            0x5762aep _PyEval_EvalFrameDefault + 1118
12            0x57535fp
13            0x57ebebp
14            0x57db5cp
15            0x5762aep _PyEval_EvalFrameDefault + 1118
16            0x57535fp
17            0x57ebebp
18            0x57db5cp
19            0x576ff5p _PyEval_EvalFrameDefault + 4517
20            0x57dfd5p PyEval_EvalCodeEx + 645
21            0x4fbc34p
22            0x4e7cdap PyObject_Call + 58
23            0x5778ccp _PyEval_EvalFrameDefault + 6780
24            0x57e302p PyEval_EvalCodeEx + 1458
25            0x4fbc34p
26            0x4e7cdap PyObject_Call + 58
27            0x5778ccp _PyEval_EvalFrameDefault + 6780
28            0x575716p
29            0x57ebebp
30            0x57db5cp
31            0x5762aep _PyEval_EvalFrameDefault + 1118
32            0x57535fp
33            0x57ebebp
34            0x57db5cp
35            0x5762aep _PyEval_EvalFrameDefault + 1118
36            0x57eb2dp
37            0x57db5cp
38            0x5762aep _PyEval_EvalFrameDefault + 1118
39            0x57eb2dp
40            0x57db5cp
41            0x5762aep _PyEval_EvalFrameDefault + 1118
42            0x57eb2dp
43            0x57db5cp
44            0x5762aep _PyEval_EvalFrameDefault + 1118
45            0x57535fp
46            0x5750d3p PyEval_EvalCode + 35
47            0x5ea0c2p
48            0x5ea52ap PyRun_FileExFlags + 154
49            0x5ea2e7p PyRun_SimpleFileExFlags + 423
50            0x5ef7f3p Py_Main + 1571
51            0x4d1f09p main + 233
52      0x7fe21b87c830p __libc_start_main + 240
53            0x5e7b29p _start + 41
Process finished with exit code 0

**Comment by leonleeldc** [comment]
然后，我们又检查了相关的cpp代码：
报的错误在elementwise_op_h的185行，
    PADDLE_ENFORCE_GE(x_dims.size(), y_dims.size(),
                      "Rank of first input must >= rank of second input.");
那个function是：

class ElementwiseOpGrad : public framework::OperatorWithKernel {
 public:
  using framework::OperatorWithKernel::OperatorWithKernel;
  using Tensor = framework::Tensor;

  void InferShape(framework::InferShapeContext *ctx) const override {
    auto out_grad_name = framework::GradVarName("Out");
    PADDLE_ENFORCE(ctx->HasInput("Y"), "Input(Y) should not be null");
    PADDLE_ENFORCE(ctx->HasInput(out_grad_name),
                   "Input(Out@GRAD) should not be null");

    auto x_dims = ctx->GetInputDim(out_grad_name);
    auto y_dims = ctx->GetInputDim("Y");

    PADDLE_ENFORCE_GE(x_dims.size(), y_dims.size(),
                      "Rank of first input must >= rank of second input.");

    auto x_grad_name = framework::GradVarName("X");
    auto y_grad_name = framework::GradVarName("Y");
    if (ctx->HasOutput(x_grad_name)) {
      ctx->ShareDim(out_grad_name, /*->*/ x_grad_name);
      ctx->ShareLoD(out_grad_name, /*->*/ x_grad_name);
    }
    if (ctx->HasOutput(y_grad_name)) {
      ctx->ShareDim("Y", /*->*/ y_grad_name);
      ctx->ShareLoD("Y", /*->*/ y_grad_name);
    }
  }

  framework::OpKernelType GetExpectedKernelType(
      const framework::ExecutionContext &ctx) const override {
    auto input_data_type =
        ctx.Input<Tensor>(framework::GradVarName("Out"))->type();

#ifdef PADDLE_WITH_MKLDNN
    if (platform::CanMKLDNNBeUsed(ctx)) {
      return framework::OpKernelType(input_data_type, ctx.GetPlace(),
                                     framework::DataLayout::kMKLDNN,
                                     framework::LibraryType::kMKLDNN);
    }
#endif
    return framework::OpKernelType(input_data_type, ctx.GetPlace());
  }
};
奇怪的是，那里这两行：
    auto x_dims = ctx->GetInputDim(out_grad_name);
    auto y_dims = ctx->GetInputDim("Y");
也就是x_dims说的是out_grad_name的维度，而不是x的维度，所以导致了x_dims小于了y_dims。
那个ElementwiseOpGrad是在elementwise_mul_op.cc里面注册是call到的 （78行）。
REGISTER_OPERATOR(elementwise_mul_grad, ops::ElementwiseOpGrad,
                  ops::ElementwiseMulDoubleGradDescMaker);

**Comment by leonleeldc** [comment]
这个问题感觉现在解决了，问题还是出在elementwise_mul(tmp1, tmp2)。我们发现，elementwise_mul(tmp1, tmp2)不是它的字面上的意思。有意思的是，我们就简单的把它换成tmp1 * tmp2就可以了，但是后面有个类似做两个loss的加法，loss1+loss2却不行，instead, 要用，fluid.layers.sum(loss1, loss2)。
