### ISSUE TITLE
GPU多机，fluid 1.5.2，报错

### ISSUE THREAD

**Issue by yxfGrace** [PaddlePaddle/Paddle#19790]
使用demo https://github.com/PaddlePaddle/Paddle/blob/v1.5.2/python/paddle/fluid/tests/book/test_machine_translation.py
pserver模式：2个trainer2个pserver
任务报错：
![图片](https://user-images.githubusercontent.com/29363426/64776062-1a013280-d58a-11e9-8c85-8f647ce1f966.png)

**Comment by ysh329** [comment]
初步看，环境是cuDnn7.3 CUDA61，需求助分布式GPU同学

**Comment by ccmeteorljh** [comment]
distributed_lookup_table不支持CUDAPlace，将use_cuda改成false试试
