### ISSUE TITLE
paddle可以支持不同的初始化方式么

### ISSUE THREAD

**Issue by zhangyong15** [PaddlePaddle/Paddle#1979]
如题，比如支持xavier等初始化方式

**Comment by lcy-seso** [comment]
paddle implement a smart initialization that chooses initial weights of a neural network from the range $(\frac{1}{\sqrt{d}},-\frac{1}{\sqrt{d}})$, where $d$ is the number of inputs to a given neuron. 

If you do not specify the mean or standard variance parameter for initializaion, by default, PaddlePaddle uses smart initializaion to initialize weight matrix, you may refer to this https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/trainer_config_helpers/attrs.py#L116.

And you can implement xavier initialization by modifying the paddle.attr.Param attribute of a layer like [this](https://github.com/PaddlePaddle/Paddle/blob/develop/demo/semantic_role_labeling/api_train_v2.py#L40).

**Comment by lcy-seso** [comment]
For smart initialization PaddlePaddle used, you can refer to [this page](https://stats.stackexchange.com/questions/47590/what-are-good-initial-weights-in-a-neural-network).

**Comment by songzy12** [comment]
Just came across this while searching for answers with the same question.

The links in comment#2 are now both outdated. Here are some latest references:
- https://www.paddlepaddle.org.cn/documentation/docs/en/api/paddle/ParamAttr_en.html
- https://www.paddlepaddle.org.cn/documentation/docs/en/api/paddle/nn/initializer/XavierNormal_en.html
