### ISSUE TITLE
fluid1.5 在paddleclould 上运行报 data_norm error 

### ISSUE THREAD

**Issue by lizhiqings** [PaddlePaddle/Paddle#19812]
报错：
/home/disk1/task_data/history/20190916/6.app-user-20190916110604-8973--lizhiqing_core2_middlepage_rank_para_201909161105_paddlecloud/logs/workspace
Mon Sep 16 11:23:16 2019[1,9]<stdout>:I0916 11:23:16.774300 21861 rpc_client.h:101] init rpc client with trainer_id 9
Mon Sep 16 11:23:21 2019[1,9]<stdout>:Traceback (most recent call last):
Mon Sep 16 11:23:21 2019[1,9]<stdout>:  File "train.py", line 221, in <module>
Mon Sep 16 11:23:21 2019[1,9]<stdout>:    train_main(use_cuda=use_cuda, is_sparse=True, is_local=is_local)
Mon Sep 16 11:23:21 2019[1,9]<stdout>:  File "train.py", line 215, in train_main
Mon Sep 16 11:23:21 2019[1,9]<stdout>:    train_loop(t.get_trainer_program())
Mon Sep 16 11:23:21 2019[1,9]<stdout>:  File "train.py", line 185, in train_loop
Mon Sep 16 11:23:21 2019[1,9]<stdout>:    fetch_list=[avg_cost])
Mon Sep 16 11:23:21 2019[1,9]<stdout>:  File "/home/disk1/task_data/history/20190916/9.app-user-20190916110604-8973--lizhiqing_core2_middlepage_rank_para_201909161105_paddlecloud/logs/workspace/python27-gcc482/lib/python2.7/site-packages/paddle/fluid/executor.py", line 650, in run
Mon Sep 16 11:23:21 2019[1,9]<stdout>:    use_program_cache=use_program_cache)
Mon Sep 16 11:23:21 2019[1,9]<stdout>:  File "/home/disk1/task_data/history/20190916/9.app-user-20190916110604-8973--lizhiqing_core2_middlepage_rank_para_201909161105_paddlecloud/logs/workspace/python27-gcc482/lib/python2.7/site-packages/paddle/fluid/executor.py", line 748, in _run
Mon Sep 16 11:23:21 2019[1,9]<stdout>:    exe.run(program.desc, scope, 0, True, True, fetch_var_name)
Mon Sep 16 11:23:21 2019[1,9]<stdout>:paddle.fluid.core_avx.EnforceNotMet: Invoke operator data_norm error.

相关代码：
<img width="999" alt="data_norm_err" src="https://user-images.githubusercontent.com/47736115/64933392-b28fff00-d877-11e9-9708-4921f8aebd50.png">

**Comment by gavin1332** [comment]
看组网的话没有明显错误，能否在本地复现？或者能否改用batch norm?

**Comment by lizhiqings** [comment]
嗯 好了 已经改用 batch_norm

发件人: Yi Liu <notifications@github.com>
答复: PaddlePaddle/Paddle <reply@reply.github.com>
日期: 2019年9月17日 星期二 上午9:49
收件人: PaddlePaddle/Paddle <Paddle@noreply.github.com>
抄送: "Li,Zhiqing" <lizhiqing@baidu.com>, Author <author@noreply.github.com>
主题: Re: [PaddlePaddle/Paddle] fluid1.5 在paddleclould 上运行报 data_norm error (#19812)


看组网的话没有明显错误，能否在本地复现？或者能否改用batch norm?
