### ISSUE TITLE
contribute_to_paddle_en.md should be updated.

### ISSUE THREAD

**Issue by livc** [PaddlePaddle/Paddle#1981]

**Comment by lcy-seso** [comment]
Maybe we always need some detail descriptions for an issue. It is confusing if an issue only has a title but no description.

**Comment by livc** [comment]
Last week we updated the git usage (<https://github.com/PaddlePaddle/Paddle/blob/develop/doc/howto/dev/contribute_to_paddle_cn.md>) in Chinese, then need to have a corresponding English version.
