### ISSUE TITLE
'NoneType' object has no attribute '_copy_to'

### ISSUE THREAD

**Issue by jinyuKING** [PaddlePaddle/Paddle#19823]
环境：python3.6.5  centos6.5  paddlepaddle1.5.1   jupyter

问题描述：打算使用动态图完成一个简单的线性回归，出现报错。

代码：
%matplotlib inline
import matplotlib.pyplot as plt
import paddle
import paddle.fluid as fluid
import numpy as np
import random

print(paddle.__version__) 

num_inputs=2
num_examples=1000
true_w=[2,-3.4]
true_b=4.2
features=np.random.normal(scale=1,size=(num_examples,num_inputs))
labels=true_w[0]*features[:,0]+true_w[1]*features[:,1]
labels+=np.random.normal(scale=0.01,size=labels.shape)

def data_reader(batch_size,features,labels):
    num_examples=len(features)
    indices=list(range(num_examples))
    random.shuffle(indices)
    for i in range(0,num_examples,batch_size):
        j=np.array(indices[i:min(i+batch_size,num_examples)])
        yield features.take((j),axis=0),labels.take((j),axis=0)

w=np.random.normal(scale=0.01,size=(num_inputs,1))
b=np.zeros(shape=(1,)) 

def linreg(X,w,b):
    return np.dot(X,w)+b

def squared_loss(y_hat,y):
    return (y_hat-y.reshape(y_hat.shape))**2/2

def sgd(params,lr,batch_size):
    for param in params:
        param[:]=param-lr*np.gradient(param)/batch_size

lr=0.03
num_epochs=10
net=linreg
loss=squared_loss

with fluid.dygraph.guard():
    for epoch in range(num_epochs):
        for X,y in data_reader(batch_size,features,labels):
            l = loss(net(X, w, b), y)
            print(l)
            l=fluid.dygraph.to_variable(l)
            l.backward()
            print(l.gradient())
            sgd([w,b],lr,batch_size)
        train_l=loss(net(features,w,b),labels)
        print('epoch %d,loss %f'%(epoch+1,train_l.mean()))

报错类型：
AttributeError                            Traceback (most recent call last)
<ipython-input-66-44c21dc3ca70> in <module>
     12             l=fluid.dygraph.to_variable(l)
     13             l.backward()
---> 14             print(l.gradient())
     15             sgd([w,b],lr,batch_size)
     16         train_l=loss(net(features,w,b),labels)

~/shijinyu/software/anaconda3/envs/tensorflow-gpu/lib/python3.6/site-packages/paddle/fluid/framework.py in gradient(self)
    551 
    552     def gradient(self):
--> 553         new_ivar = self._ivar._grad_ivar()._copy_to(core.CPUPlace(), True)
    554         return np.array(new_ivar.value().get_tensor())
    555 

AttributeError: 'NoneType' object has no attribute '_copy_to'

**Comment by gavin1332** [comment]
建议把代码format一下，这样方便复现定位问题

**Comment by jinyuKING** [comment]
`%matplotlib inline
import matplotlib.pyplot as plt
import paddle
import paddle.fluid as fluid
import numpy as np
import random

print(paddle.__version__)

num_inputs=2
num_examples=1000
true_w=[2,-3.4]
true_b=4.2
features=np.random.normal(scale=1,size=(num_examples,num_inputs))
labels=true_w[0]*features[:,0]+true_w[1]*features[:,1]+true_b
labels+=np.random.normal(scale=0.01,size=labels.shape)

def data_reader(batch_size,features,labels):
    num_examples=len(features)
    indices=list(range(num_examples))
    random.shuffle(indices)
    for i in range(0,num_examples,batch_size):
        j=np.array(indices[i:min(i+batch_size,num_examples)])
        yield features.take((j),axis=0),labels.take((j),axis=0)
w=np.random.normal(scale=0.01,size=(num_inputs,1))
b=np.zeros(shape=(1,)) 
def linreg(X,w,b):
    return np.dot(X,w)+b
def squared_loss(y_hat,y):
    return (y_hat-y.reshape(y_hat.shape))**2/2
def sgd(params,lr,batch_size):
    for param in params:
        param[:]=param-lr*np.gradient(param)/batch_size
lr=0.03
num_epochs=10
net=linreg
loss=squared_loss

with fluid.dygraph.guard():
    for epoch in range(num_epochs):
        for X,y in data_reader(batch_size,features,labels):
            l = loss(net(X, w, b), y)
            print(l)
            l=fluid.dygraph.to_variable(l)
            l.backward()
            print(l.gradient())
            sgd([w,b],lr,batch_size)
        train_l=loss(net(features,w,b),labels)
        print('epoch %d,loss %f'%(epoch+1,train_l.mean()))`      jupyter运行的，各个部分比较分散

**Comment by jinyuKING** [comment]
```
%matplotlib` inline
import matplotlib.pyplot as plt
import paddle
import paddle.fluid as fluid
import numpy as np
import random

print(paddle.__version__)

num_inputs=2
num_examples=1000
true_w=[2,-3.4]
true_b=4.2
features=np.random.normal(scale=1,size=(num_examples,num_inputs))
labels=true_w[0]*features[:,0]+true_w[1]*features[:,1]+true_b
labels+=np.random.normal(scale=0.01,size=labels.shape)

def data_reader(batch_size,features,labels):
    num_examples=len(features)
    indices=list(range(num_examples))
    random.shuffle(indices)
    for i in range(0,num_examples,batch_size):
        j=np.array(indices[i:min(i+batch_size,num_examples)])
        yield features.take((j),axis=0),labels.take((j),axis=0)
w=np.random.normal(scale=0.01,size=(num_inputs,1))
b=np.zeros(shape=(1,)) 
def linreg(X,w,b):
    return np.dot(X,w)+b
def squared_loss(y_hat,y):
    return (y_hat-y.reshape(y_hat.shape))**2/2
def sgd(params,lr,batch_size):
    for param in params:
        param[:]=param-lr*np.gradient(param)/batch_size
lr=0.03
num_epochs=10
net=linreg
loss=squared_loss

with fluid.dygraph.guard():
    for epoch in range(num_epochs):
        for X,y in data_reader(batch_size,features,labels):
            l = loss(net(X, w, b), y)
            print(l)
            l=fluid.dygraph.to_variable(l)
            l.backward()
            print(l.gradient())
            sgd([w,b],lr,batch_size)
        train_l=loss(net(features,w,b),labels)
        print('epoch %d,loss %f'%(epoch+1,train_l.mean()))
```
jupyter写的，模块比较散

**Comment by JiabinYang** [comment]
目前Paddle的动态图还不支持numpy组网的方式，具体的使用可以参考https://www.paddlepaddle.org.cn/documentation/docs/zh/user_guides/howto/dygraph/DyGraph.html

**Comment by jinyuKING** [comment]
> 目前Paddle的动态图还不支持numpy组网的方式，具体的使用可以参考https://www.paddlepaddle.org.cn/documentation/docs/zh/user_guides/howto/dygraph/DyGraph.html

感觉paddle的动态图机制跟其他动态图框架比，使用还是有些麻烦，mxnet跟pytorch的代码很容易实现互相迁移，更换功能函数就基本完成了，换成paddle动态图写法就基本要重新组网去写，，，，，
