### ISSUE TITLE
k8s k40 nccl方式跑多机，报如下错

### ISSUE THREAD

**Issue by zhengxiao-yu** [PaddlePaddle/Paddle#19858]
一、资源信息：
trainer个数:      3
trainer进程GPU卡数:   3
GPU卡类型:    gpu_k40
二、错误信息
![image](https://user-images.githubusercontent.com/40815005/65138981-70fd8080-da3e-11e9-80ab-333d34e9ce6c.png)

**Comment by gavin1332** [comment]
是一共3*3=9张卡吗？

**Comment by gavin1332** [comment]
看日志像是nccl的版本跟GPU的驱动不匹配。
能否使用P40测试一下？

**Comment by zhengxiao-yu** [comment]
> 看日志像是nccl的版本跟GPU的驱动不匹配。
> 能否使用P40测试一下？

p40可以跑通，设置如下：
![image](https://user-images.githubusercontent.com/40815005/65211856-b53a6080-dad2-11e9-9d91-e81cbae63190.png)

**Comment by zhengxiao-yu** [comment]
> 看日志像是nccl的版本跟GPU的驱动不匹配。
用的：cuda9+nccl2.1.15

**Comment by Melonzhou** [comment]
搭车追问一下，感觉现在的nccl不只是K40有问题，v100也有同样的问题。
![image](https://user-images.githubusercontent.com/5926307/65213812-33e6cc00-dada-11e9-9bcd-2b73b69ff8d5.png)
nccl_2.3.7-1+cuda9.0_x86_64
paddlegpu-1.5.2版本的

**Comment by Melonzhou** [comment]
NCCL_P2P_DISABLE=0
NCCL_IB_DISABLE=0
这两个参数是什么意思啊？是不是和上面的错误有关啊？

**Comment by gentelyang** [comment]
> NCCL_P2P_DISABLE=0
> NCCL_IB_DISABLE=0
> 这两个参数是什么意思啊？是不是和上面的错误有关啊？
NCCL_P2P_DISABLE是禁用对等传输(p2p)；
NCCL_IB_DISABLE是禁用NCCL的IB / RoCE传输；
