### ISSUE TITLE
linux上paddle=develop第一次编译报错，第二次编译成功

### ISSUE THREAD

**Issue by JiaXiao243** [PaddlePaddle/Paddle#19862]
今天刚刚下载的Paddle的源代码，直接编译，编译过程中会报如下信息：
![image](https://user-images.githubusercontent.com/37854899/65148187-474e5480-da52-11e9-9e4f-09b950c4565a.png)
再重新编译就成功了了。
试了两次，都是这样，之前从来没有出现过。

**Comment by luotao1** [comment]
这是编译错误，缺依赖了。prune加个boost的依赖应该就好了
