### ISSUE TITLE
使用brpc封装paddlepaddle预测

### ISSUE THREAD

**Issue by xiuechen** [PaddlePaddle/Paddle#19860]
1.bthread是复用的吗？还是说请求处理完bthread就释放了，然后下次来请求再构建新的呢？
2.有人用brpc封装paddlepaddle模型进行预测吗，predictor一个pthread一个还是一个bthread一个呀，另外如果一个pthread一个该怎么初始化呢～～

**Comment by shippingwang** [comment]
建议用户使用paddle serving
