### ISSUE TITLE
训练过程中出core，无信息提示

### ISSUE THREAD

**Issue by Joyo2016** [PaddlePaddle/Paddle#19873]
paddle 1.5，cpu
执行transformer训练过程中出core，怀疑是由于数据格式问题导致，但无信息提示，准备训练数据的代码中的print信息也没有显示出来

**Comment by heavengate** [comment]
麻烦粘贴一下关键代码和日志信息，补充一下cuda，cudnn，操作系统版本等信息

**Comment by Joyo2016** [comment]
cpu机器，centos 6.3 64位
        self.paddle_env['exe'].train_from_dataset(program=self.get_main_program(),
                        dataset=self.paddle_env['dataset'],
                        fetch_list=self.debug_tensors,
                        fetch_info=self.debug_tensor_keys,
                        print_period=FLAGS.trace_every_n_steps,
                        debug=FLAGS.debug_mode)

**Comment by heavengate** [comment]
`export GLOG_v=10`可开启调试日志打印，可以打印看下

**Comment by heavengate** [comment]
Paddle原版代码能跑通，目前代码卡在read_data部分，建议排查reader
