### ISSUE TITLE
动态图如何多卡训练？不是用executor的那种

### ISSUE THREAD

**Issue by Exception-star** [PaddlePaddle/Paddle#19874]
动态图如何多卡训练？不是用executor的那种。

还有策略如何设置，例如syncBN

**Comment by heavengate** [comment]
请参考 https://github.com/PaddlePaddle/models/tree/develop/dygraph/resnet , 支持多卡训练，代码中有strategy的获取接口
![屏幕快照 2019-09-19 下午1 55 25](https://user-images.githubusercontent.com/12605721/65216959-34d12b00-dae5-11e9-99ad-6aa7f5a8876f.png)

**Comment by Exception-star** [comment]
> 请参考 https://github.com/PaddlePaddle/models/tree/develop/dygraph/resnet , 支持多卡训练，代码中有strategy的获取接口
> ![屏幕快照 2019-09-19 下午1 55 25](https://user-images.githubusercontent.com/12605721/65216959-34d12b00-dae5-11e9-99ad-6aa7f5a8876f.png)



<img width="592" alt="图片" src="https://user-images.githubusercontent.com/53971568/65222100-f5104080-daf0-11e9-8948-d02bca3a16b9.png">
返回的是None, 运行环境（4卡，cuda8.0）
<img width="794" alt="图片" src="https://user-images.githubusercontent.com/53971568/65222112-fb9eb800-daf0-11e9-85fa-c285f29853e7.png">

**Comment by Exception-star** [comment]
> 请参考 https://github.com/PaddlePaddle/models/tree/develop/dygraph/resnet , 支持多卡训练，代码中有strategy的获取接口
> ![屏幕快照 2019-09-19 下午1 55 25](https://user-images.githubusercontent.com/12605721/65216959-34d12b00-dae5-11e9-99ad-6aa7f5a8876f.png)

<img width="670" alt="图片" src="https://user-images.githubusercontent.com/53971568/65223670-440ba500-daf4-11e9-977a-7f307e144224.png">
如何shi使用同步bn?

**Comment by heavengate** [comment]
动态图当前不支持syncbn
