### ISSUE TITLE
使用paddle开发multi-agent learning，训练过程中出现段错误

### ISSUE THREAD

**Issue by jiangbojian** [PaddlePaddle/Paddle#19882]
程序运行环境:
paddle develop(commit id:85914f7a88f748a3883bfd09df810e910cce3089)
v100 16G 8卡
python2.7
![image](https://user-images.githubusercontent.com/6761054/65220494-677f2180-daed-11e9-8e79-a3c6bf3938af.png)

错误截图如上，错误不能稳定复现，运行过三次，三次都是在不同的step挂掉。
可以打包提供整套运行环境

**Comment by heavengate** [comment]
麻烦贴一下关键代码，版本，环境定信息

**Comment by jiangbojian** [comment]
@heavengate  没法定位错误位置，整个项目代码我都贴过来吗？我可以提供运行的环境

**Comment by heavengate** [comment]
`export GLOG_v=10` 可以把调试日志打出来看下

**Comment by jiangbojian** [comment]
@heavengate 磁盘都打满了，也没出错误。速度太慢了，这样解决不了呀

**Comment by heavengate** [comment]
看报错处在elementwise add上，可以排查一下你的代码里面调用fluid.layers.elemetwise_add的地方或者两个Variable相加的地方

**Comment by jiangbojian** [comment]
@heavengate  代码里没有使用elemetwise_add，但有两个Variable相加的地方，但也都是常规操作，如何避免它报这个错呢？

**Comment by heavengate** [comment]
可以fluid.layers.Print()把两个相加的tensor打出来，看看shape，type这些是不是一致的
