### ISSUE TITLE
概念搞不清楚：Fluid.Parameter V.S. Fluid.Vars V.S. Fluid.Persistables

### ISSUE THREAD

**Issue by OleNet** [PaddlePaddle/Paddle#19893]
[教程](https://www.paddlepaddle.org.cn/documentation/docs/zh/1.5/api_guides/low_level/model_save_reader.html)里说，

> 在 Paddle 中，算子(Operator)的每一个输入和输出都是一个变量（Variable），而参数（Parameter）是变量（Variable）的子类。**持久性变量（Persistables）**是一种在每次迭代结束后均不会被删除的变量。**参数是一种持久性变量**，其在每次迭代后都会被优化器（优化器）更新。训练神经网络本质上就是在更新参数。

根据这段话， 我理解，参数（Parameter）和持久性变量（Persistables）是一回事是吗？

**Comment by heavengate** [comment]
1. persistable是指变量在运行过程中内存不会释放，参数由于在整个运行过程中是要持续学习更新的，所以是persistable的不会被释放，所以Parameter肯定是persistable。
2. 不是一回事，可以认为persistable是一个更广泛的概念，参数是其中之一，有一些非参数的变量也可以设置为persistable

**Comment by OleNet** [comment]
变量的梯度属于persistable吗？

**Comment by OleNet** [comment]
另外一般情况下， save_persistables 是不是和 save_checkpoint 保存的变量范围一样的？
