### ISSUE TITLE
为不能翻墙的用户提供ToolsBox的中国镜像

### ISSUE THREAD

**Issue by llxxxll** [PaddlePaddle/Paddle#1989]
Tool simple：
https://storage.googleapis.com/golang/go1.8.1.linux-amd64.tar.gz

CDN simple:
https://cdn.paddlepaddlehub.com/golang/go1.8.1.linux-amd64.tar.gz

**Comment by typhoonzero** [comment]
ToolsBox 是指啥？另外用户如果只是使用docker，现在可以直接`pip install paddlepaddle`，开发者才需要使用go完成编译。

**Comment by llxxxll** [comment]
当时的想法是把一些翻墙才能用的工具做一个国内镜像，避免用户在安装或者使用过程中因为墙的问题卡住进度。

**Comment by typhoonzero** [comment]
嗯，先Close了使用docker或pypi都有不少可选的国内镜像了～
