### ISSUE TITLE
安装GPU版本不能使用

### ISSUE THREAD

**Issue by lxy417** [PaddlePaddle/Paddle#19902]
- 标题：ubuntu16安装错误
- 版本、环境信息：
    1）PaddlePaddle版本：1.5.2.post107
    2）CPU：i9-9900k
    3）GPU：双2080ti，CUDA9.0或者10.0，cuDNN7.5或者7.6
    4）系统环境：ubuntu16、Python3.6
- 安装方式信息：
1）pip安装
cpu运行没有问题，gpu运行有问题

按着您们的测试运行时候的报错
Running Verify Fluid Program ... 
W0920 13:32:54.945031  7592 dynamic_loader.cc:118] Can not find library: libcublas.so. The process maybe hang. Please try to add the lib path to LD_LIBRARY_PATH.
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/home/shandian_ll/anaconda3/envs/paddle/lib/python3.6/site-packages/paddle/fluid/install_check.py", line 123, in run_check
    test_simple_exe()
  File "/home/shandian_ll/anaconda3/envs/paddle/lib/python3.6/site-packages/paddle/fluid/install_check.py", line 119, in test_simple_exe
    exe0.run(startup_prog)
  File "/home/shandian_ll/anaconda3/envs/paddle/lib/python3.6/site-packages/paddle/fluid/executor.py", line 657, in run
    use_program_cache=use_program_cache)
  File "/home/shandian_ll/anaconda3/envs/paddle/lib/python3.6/site-packages/paddle/fluid/executor.py", line 755, in _run
    exe.run(program.desc, scope, 0, True, True, fetch_var_name)
paddle.fluid.core_avx.EnforceNotMet: Invoke operator fill_constant error.
Python Call stacks: 
  File "/home/shandian_ll/anaconda3/envs/paddle/lib/python3.6/site-packages/paddle/fluid/framework.py", line 1845, in _prepend_op
    attrs=kwargs.get("attrs", None))
  File "/home/shandian_ll/anaconda3/envs/paddle/lib/python3.6/site-packages/paddle/fluid/initializer.py", line 189, in __call__
    stop_gradient=True)
  File "/home/shandian_ll/anaconda3/envs/paddle/lib/python3.6/site-packages/paddle/fluid/framework.py", line 1730, in create_parameter
    initializer(param, self)
  File "/home/shandian_ll/anaconda3/envs/paddle/lib/python3.6/site-packages/paddle/fluid/layer_helper_base.py", line 316, in create_parameter
    **attr._to_kwargs(with_initializer=True))
  File "/home/shandian_ll/anaconda3/envs/paddle/lib/python3.6/site-packages/paddle/fluid/dygraph/layers.py", line 90, in create_parameter
    default_initializer)
  File "/home/shandian_ll/anaconda3/envs/paddle/lib/python3.6/site-packages/paddle/fluid/dygraph/nn.py", line 931, in _build_once
    attr=self._bias_attr, shape=size, dtype=self._dtype, is_bias=True)
  File "/home/shandian_ll/anaconda3/envs/paddle/lib/python3.6/site-packages/paddle/fluid/dygraph/layers.py", line 158, in __call__
    self._build_once(*inputs)
  File "/home/shandian_ll/anaconda3/envs/paddle/lib/python3.6/site-packages/paddle/fluid/install_check.py", line 40, in forward
    x = self._fc1(inputs)
  File "/home/shandian_ll/anaconda3/envs/paddle/lib/python3.6/site-packages/paddle/fluid/dygraph/layers.py", line 162, in __call__
    outputs = self.forward(*inputs)
  File "/home/shandian_ll/anaconda3/envs/paddle/lib/python3.6/site-packages/paddle/fluid/install_check.py", line 113, in test_simple_exe
    out0 = simple_layer0(inp0)
  File "/home/shandian_ll/anaconda3/envs/paddle/lib/python3.6/site-packages/paddle/fluid/install_check.py", line 123, in run_check
    test_simple_exe()
  File "<input>", line 1, in <module>
  File "/home/shandian_ll/anaconda3/envs/paddle/lib/python3.6/code.py", line 91, in runcode
    exec(code, self.locals)
  File "/home/shandian_ll/anaconda3/envs/paddle/lib/python3.6/code.py", line 75, in runsource
    self.runcode(code)
  File "/home/shandian_ll/Downloads/pycharm-community-2019.2.1/helpers/pydev/_pydev_bundle/pydev_console_types.py", line 35, in run
    self.more = self.interpreter.runsource(text, '<input>', symbol)
  File "/home/shandian_ll/Downloads/pycharm-community-2019.2.1/helpers/pydev/pydevconsole.py", line 84, in do_add_exec
    command.run()
  File "/home/shandian_ll/Downloads/pycharm-community-2019.2.1/helpers/pydev/_pydev_bundle/pydev_console_utils.py", line 151, in add_exec
    more = self.do_add_exec(code_fragment)
  File "/home/shandian_ll/Downloads/pycharm-community-2019.2.1/helpers/pydev/pydevconsole.py", line 258, in process_exec_queue
    more = interpreter.add_exec(code_fragment)
  File "/home/shandian_ll/Downloads/pycharm-community-2019.2.1/helpers/pydev/pydevconsole.py", line 411, in start_client
    process_exec_queue(interpreter)
  File "/home/shandian_ll/Downloads/pycharm-community-2019.2.1/helpers/pydev/pydevconsole.py", line 483, in <module>
    pydevconsole.start_client(host, port)
C++ Call stacks: 
Failed to find dynamic library: libcublas.so ( libcublas.so: cannot open shared object file: No such file or directory ) 
 Please specify its path correctly using following ways: 
 Method. set environment variable LD_LIBRARY_PATH on Linux or DYLD_LIBRARY_PATH on Mac OS. 
 For instance, issue command: export LD_LIBRARY_PATH=... 
 Note: After Mac OS 10.11, using the DYLD_LIBRARY_PATH is impossible unless System Integrity Protection (SIP) is disabled. at [/paddle/paddle/fluid/platform/dynload/dynamic_loader.cc:175]
PaddlePaddle Call Stacks: 
0       0x7fd6eda9fd50p void paddle::platform::EnforceNotMet::Init<char const*>(char const*, char const*, int) + 352
1       0x7fd6edaa00c9p paddle::platform::EnforceNotMet::EnforceNotMet(std::__exception_ptr::exception_ptr, char const*, int) + 137
2       0x7fd6efbe75a5p paddle::platform::dynload::GetCublasDsoHandle() + 1813
3       0x7fd6efbc5329p void std::__once_call_impl<std::_Bind_simple<paddle::platform::dynload::DynLoad__cublasCreate_v2::operator()<cublasContext**>(cublasContext**)::{lambda()#1} ()> >() + 9
4       0x7fd78909ba99p
5       0x7fd6efbc64c9p paddle::platform::CublasHandleHolder::CublasHandleHolder(CUstream_st*, cublasMath_t) + 153
6       0x7fd6efbc1ff7p paddle::platform::CUDADeviceContext::CUDADeviceContext(paddle::platform::CUDAPlace) + 567
7       0x7fd6efbc6e68p std::_Function_handler<std::unique_ptr<paddle::platform::DeviceContext, std::default_delete<paddle::platform::DeviceContext> > (), std::reference_wrapper<std::_Bind_simple<paddle::platform::EmplaceDeviceContext<paddle::platform::CUDADeviceContext, paddle::platform::CUDAPlace>(std::map<boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_>, std::shared_future<std::unique_ptr<paddle::platform::DeviceContext, std::default_delete<paddle::platform::DeviceContext> > >, std::less<boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> >, std::allocator<std::pair<boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const, std::shared_future<std::unique_ptr<paddle::platform::DeviceContext, std::default_delete<paddle::platform::DeviceContext> > > > > >*, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_>)::{lambda()#1} ()> > >::_M_invoke(std::_Any_data const&) + 104
8       0x7fd6efbc541ap std::_Function_handler<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> (), std::__future_base::_Task_setter<std::unique_ptr<std::__future_base::_Result<std::unique_ptr<paddle::platform::DeviceContext, std::default_delete<paddle::platform::DeviceContext> > >, std::__future_base::_Result_base::_Deleter>, std::unique_ptr<paddle::platform::DeviceContext, std::default_delete<paddle::platform::DeviceContext> > > >::_M_invoke(std::_Any_data const&) + 42
9       0x7fd6edb69617p std::__future_base::_State_base::_M_do_set(std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> ()>&, bool&) + 39
10      0x7fd78909ba99p
11      0x7fd6efbc875cp std::__future_base::_Deferred_state<std::_Bind_simple<paddle::platform::EmplaceDeviceContext<paddle::platform::CUDADeviceContext, paddle::platform::CUDAPlace>(std::map<boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_>, std::shared_future<std::unique_ptr<paddle::platform::DeviceContext, std::default_delete<paddle::platform::DeviceContext> > >, std::less<boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> >, std::allocator<std::pair<boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const, std::shared_future<std::unique_ptr<paddle::platform::DeviceContext, std::default_delete<paddle::platform::DeviceContext> > > > > >*, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_>)::{lambda()#1} ()>, std::unique_ptr<paddle::platform::DeviceContext, std::default_delete<paddle::platform::DeviceContext> > >::_M_run_deferred() + 220
12      0x7fd6efbc2bd9p paddle::platform::DeviceContextPool::Get(boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&) + 137
13      0x7fd6efb437bap paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&, paddle::framework::RuntimeContext*) const + 58
14      0x7fd6efb43cd1p paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&) const + 529
15      0x7fd6efb3e863p paddle::framework::OperatorBase::Run(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&) + 307
16      0x7fd6edc2adfep paddle::framework::Executor::RunPreparedContext(paddle::framework::ExecutorPrepareContext*, paddle::framework::Scope*, bool, bool, bool) + 398
17      0x7fd6edc2de9fp paddle::framework::Executor::Run(paddle::framework::ProgramDesc const&, paddle::framework::Scope*, int, bool, bool, std::vector<std::string, std::allocator<std::string> > const&, bool) + 143
18      0x7fd6eda911fdp
19      0x7fd6edad2d56p
20      0x558bfa808c54p _PyCFunction_FastCallDict + 340
21      0x558bfa890c0ep
22      0x558bfa8b375ap _PyEval_EvalFrameDefault + 778
23      0x558bfa889e66p
24      0x558bfa88aed6p
25      0x558bfa890b95p
26      0x558bfa8b451cp _PyEval_EvalFrameDefault + 4300
27      0x558bfa889e66p
28      0x558bfa88ae73p
29      0x558bfa890b95p
30      0x558bfa8b375ap _PyEval_EvalFrameDefault + 778
31      0x558bfa88a136p
32      0x558bfa88aed6p
33      0x558bfa890b95p
34      0x558bfa8b375ap _PyEval_EvalFrameDefault + 778
35      0x558bfa88a29ep
36      0x558bfa88aed6p
37      0x558bfa890b95p
38      0x558bfa8b375ap _PyEval_EvalFrameDefault + 778
39      0x558bfa88b9b9p PyEval_EvalCodeEx + 809
40      0x558bfa88c75cp PyEval_EvalCode + 28
41      0x558bfa8b1167p
42      0x558bfa808b91p _PyCFunction_FastCallDict + 145
43      0x558bfa890abcp
44      0x558bfa8b375ap _PyEval_EvalFrameDefault + 778
45      0x558bfa88ac5bp
46      0x558bfa890b95p
47      0x558bfa8b375ap _PyEval_EvalFrameDefault + 778
48      0x558bfa889e66p
49      0x558bfa88ae73p
50      0x558bfa890b95p
51      0x558bfa8b375ap _PyEval_EvalFrameDefault + 778
52      0x558bfa88ac5bp
53      0x558bfa890b95p
54      0x558bfa8b375ap _PyEval_EvalFrameDefault + 778
55      0x558bfa88ac5bp
56      0x558bfa890b95p
57      0x558bfa8b375ap _PyEval_EvalFrameDefault + 778
58      0x558bfa889e66p
59      0x558bfa88ae73p
60      0x558bfa890b95p
61      0x558bfa8b375ap _PyEval_EvalFrameDefault + 778
62      0x558bfa88ac5bp
63      0x558bfa890b95p
64      0x558bfa8b375ap _PyEval_EvalFrameDefault + 778
65      0x558bfa88ac5bp
66      0x558bfa890b95p
67      0x558bfa8b375ap _PyEval_EvalFrameDefault + 778
68      0x558bfa88b9b9p PyEval_EvalCodeEx + 809
69      0x558bfa88c75cp PyEval_EvalCode + 28
70      0x558bfa90c744p
71      0x558bfa90cb41p PyRun_FileExFlags + 161
72      0x558bfa90cd43p PyRun_SimpleFileExFlags + 451
73      0x558bfa910833p Py_Main + 1555
74      0x558bfa7da88ep main + 238
75      0x7fd788ce3830p __libc_start_main + 240
76      0x558bfa8ba160p

**Comment by JepsonWong** [comment]
这个感觉是gpu没装好或者没识别对。不知道您的gpu和paddle包是不是匹配的？我看您贴的gpu环境是cuda9或cuda10？这两个cuda版本对应的paddle包是不一样的。可以提供一下您准确的cuda和cudnn环境吗？

**Comment by JepsonWong** [comment]
目前paddle可能对20系列显卡支持有问题。

**Comment by alwaysbetter1314** [comment]
这个我也遇到了，在flyai竞赛平台上tesla p40+cuda10+paddle post107报错 。

感觉是paddlepaddle对cuda10库加载的问题: paddle 试图从cuda10安装目录下加载libcublas.so。。却找不到， 实际上只有libcublas.so.10.0 这种带后缀的库文件。

加载libcudnn.so同样报错。

下面是keras+tensorflow1.14加载的库（都带后缀）：
![image](https://user-images.githubusercontent.com/18437170/65694328-42b81a80-e0a8-11e9-9432-d6a04c08647e.png)
