### ISSUE TITLE
建议PaddlePaddle支持在树莓派平台上安装运行

### ISSUE THREAD

**Issue by 651778286** [PaddlePaddle/Paddle#19900]
欢迎您对PaddlePaddle提出建议，非常感谢您对PaddlePaddle的贡献！
在留下您的建议时，辛苦您同步提供如下信息：
- 版本、环境信息
1）PaddlePaddle版本：最新版本
2）CPU/GPU：最新款树莓派4的显卡使用的是VideoCore VI 显卡，支持 OpenGL ES 3.x
3）系统环境：Raspbian 10
- 建议描述：在树莓派上无法安装PaddlePaddle，建议添加

**Comment by yxnal** [comment]
> 欢迎您对PaddlePaddle提出建议，非常感谢您对PaddlePaddle的贡献！
> 在留下您的建议时，辛苦您同步提供如下信息：
> 
> * 版本、环境信息
>   1）PaddlePaddle版本：最新版本
>   2）CPU/GPU：最新款树莓派4的显卡使用的是VideoCore VI 显卡，支持 OpenGL ES 3.x
>   3）系统环境：Raspbian 10
> * 建议描述：在树莓派上无法安装PaddlePaddle，建议添加

我在jetson nano上可以安装运行paddle fluid
