### ISSUE TITLE
实现本地训练保存CheckPoint的机制

### ISSUE THREAD

**Issue by reyoung** [PaddlePaddle/Paddle#1991]
如果我们要实现可伸缩的Paddle调度，实现训练保存CheckPoint的机制是一个非常紧急的需求。如果要实现伸缩训练，那我们首先要实现如何保存本地训练的CheckPoint，进而使用CheckPoint可以精度无损的恢复训练过程。

## 现状

Paddle只有保存/载入模型参数的功能，我们在训练模型时不能**精度无损**的恢复训练。Paddle中实现了很多动态学习率优化算法，例如AdaGrad，Adam等。这些优化算法通过记录和处理梯度的历史信息来动态的调整学习率。这些『参数历史信息』、每个参数的『当前学习率』、必要的『中间变量』都需要保存下来才能精度无损的恢复训练。

同时，Paddle的一些Layer本身也需要保存一些模型之外的信息，用于恢复训练或模型预测。例如，BatchNormalization Layer 需要保存当前的滑动平均值和方差来恢复训练。目前，我们使用了构造一个特殊的参数来完成这一功能，但滑动平均值和方差不应该是模型参数的一部分。

目前的参数保存也只支持序列化到文件，这和我们使用Kubernetes开发Paddle Cloud的要求不符。

## 要求

基于以上现状，对Paddle保存CheckPoint的机制有如下要求:

* 保存CheckPoint的方法不能将CheckPoint直接序列化到文件，而是应该将其序列化到文件流。这样做我们既能简单的完成保存本地文件，也能将CheckPoint通过网络或者其他手段发送出去。
*这个机制 可以序列化不同数据类型。仅仅Optimizer需要保存的类型就有`real`, `std::vector<int64_t>`, `paddle::Vector`等类型。
* 这个机制需要在**运行时**注册需要被序列化变量。因为同一个神经网络使用不同的优化算法需要序列化的变量是不同的。而使用何种优化算法是运行时才能决定的。
* 这个机制不只要支持序列化Optimizer中的变量，还要支持更多通用的序列化方式。为了无损的恢复训练，Paddle需要在很多地方都有这种保存机制。

## 何时调用保存CheckPoints

训练过程保存CheckPoint会以C-API形式对外提供，它可以在任何时候被调用。何时被调用交由更高层的程序或者用户决定。

例如在`event_handler`中使用`trainer.serialize_checkpoint()`即可保存在trainer中当前的CheckPoint。

## 哪个进程会保存CheckPoints
本Issue中保存CheckPoint的问题讨论只局限在『单机恢复训练』这一场景中。

但进一步来讲，只有在多机训练中便有哪个进程保存CheckPoints的问题。当前ParameterServer中包含了Optimizer，而在Trainer端包含了Layer的信息。两者都需要保存部分的CheckPoints。因此两个进程需要同时保存CheckPoints。

但如何**同时**保存CheckPoints和多机环境下需要保存哪些信息不在本issue讨论范围内。

## 如何实现该CheckPoint机制

本issue意在说明我们需要保存CheckPoint的机制和该机制需要完成哪些工作。如何实现该机制由后续设计文档说明。

------------
Related issue #1960

**Comment by lcy-seso** [comment]
先提一点，其它的还需要仔细地想想。“可伸缩的Paddle调度，实现训练保存CheckPoint的机制是一个非常紧急的需求” 这句话我还不能完全认同，这个功能确实需要，但不一定是“非常紧急”。

- 对诸多自适应学习算法，诚然PaddlePaddle 目前丢失了“历史信息”，但是“无损回复训练”这个场景是不是有着广泛的需求呢？
    - 加载旧的模型去初始化新的训练任务，会有一定的损失，但是对绝大多数机器学习任务，我们往往关注某种性能指标，而他们最终的收敛点可能不会有太大的差别。
    - 通过调参，在我遇到的大多数例子中，初加载损失掉的历史信息，还是可以重新训练回来的。当然，这对普通用户是不够友好的。
    - 对性能有着比较变态要求的场景，可能需要无损地重启训练，这样的场景我们目前有哪些呢？
    - 这个问题早前我曾经试图做过，当时了解了一下，对不同的算法需要存储的信息都是不一样的，某些算法有可能需要存储大量的信息，存储下来的文件，可能是原始模型参数的3倍甚至更多，用户不了解这个功能频繁存储，也有隐患。我们是不是需要再check 并且估计一些，都有哪些信息是需要存储的呢？
- 我记得 @qingqing01 提到过，caffe 存储了所有的信息，能够无损的重启训练任务，可以请 @qingqing01 也看看。

**Comment by dzhwinter** [comment]
我认为保存checkpoint的逻辑分为两块，model部分和TrainState部分。赞同保存文件流的方式
- model部分
这部分的分歧在于单机情况下，本地不开启PServer进程【1】。PServer的设计中已经包含model checkpoint，单机实现相同接口
- trainState部分
这部分本地保存checkpoint和trainer保存逻辑应该相同。
```c++
class LayerState;
class TrainState {
GloballearningRate;
LayerState;
...
}
```
先不关心序列化问题，问题是这部分保存下来超大。。。，

【1】还在讨论中，倾向保留现有两种逻辑
【2】分布式情况下有time diff，不同的PServer instance保存时间不一致，PServer和Trainer保存时间不一致。导致的diff可以忽略

**Comment by reyoung** [comment]
@dzhwinter 这个issue先不考虑CheckPoint逻辑如何实现，重点讨论CheckPoint是不是应该立刻实现。
不过，也可以顺便聊一下实现:

* 感觉起来不应该『明确的』将CheckPoint分为几个逻辑。而是应该让每个类可以在运行时注册哪些需要序列化。任何类都可以将自己恢复训练需要使用的变量写到CheckPoint中。

@lcy-seso 无损的恢复训练对Paddle Cloud比较重要。因为只有先支持无损的恢复训练，才能支持可伸缩的Paddle。意见如下:

* 确实有经验的开发者，即使训练过程只保存参数之后，也可以通过反复多次的调参恢复训练。但这显然不是Paddle作为一个以『易用性』为追求的框架『应该』的样子。
* 目前确实有几个百度的项目需要这个需求，同时也有Paddle Cloud的需求，是个紧迫的需求。
* 关于无损恢复训练导致『存储空间大』的问题，这是如何使用功能问题。虽然这不是这个ISSUE的讨论范围(即，是否需要紧急的实现这一功能)。另外，相对于内存和显存，硬盘空间总是更大的。

**Comment by QiJune** [comment]
@reyoung  @lcy-seso @dzhwinter 大概想了一下怎么做单机版本的checkpoint，可以讨论一下

- 调查清楚如果恢复训练，有哪些类的状态需要做checkpoint

- 对于需要做checkpoint的类，应该实现相应的方法

```
void registerCheckpoint()
static void saveCheckpoint(std::ofstream& os)
static void loadCheckpoint(std::ifstream& os)
```

- 实现一个Checkpoint类，用于对checkpoint的统一管理，对外提供接口。其他类可以调用registerCheckpoint把相应的方法注册到CheckPoint类中

```
class Checkpoint {
public:
  void save(std::ofstream& os);
  void load(std::ifstream& os);

  std::vector<std::function<void(std::ofstream&)>> saveFunctor_;
  std::vector<std::function<void(std::ifstream&)>> loadFunctor_;

  static Checkpoint* Get() {
    static Checkpoint inst;
    return &inst;
  }
}
```

**Comment by typhoonzero** [comment]
This is implementing by new pserver: https://github.com/PaddlePaddle/Paddle/projects/18. Closing.
