### ISSUE TITLE
预测时用load_persistables载入模型出错

### ISSUE THREAD

**Issue by emy-085** [PaddlePaddle/Paddle#19920]
- 标题：预测时用load_inference_model可以正常预测，用load_persistables会报错
- 版本、环境信息：
    1）PaddlePaddle版本：1.5开发版：8cb48e5aed11806dac52f1f60aa2a88497d12644
    2）GPU：K40, cuda9.0，cudnn_v7.3
    3）系统环境：centos
- 问题描述：训练模型时我同时用save_inference_model和save_persistables保存模型参数，这是得到的参数文件(最后一个是save_persistables的结果)：
![image](https://user-images.githubusercontent.com/55644945/65382234-b79af580-dd32-11e9-8349-c2cce058569d.png)
如下边代码中所示，用load_inference_model可以正常预测，用load_persistables会报错（因为我save_inference_model时只保存了模型计算图的一部分，所以这里必须要用load_persistables去预测）。

==================================================================
详细日志：
define model over ...
W0922 12:09:06.581745 29803 device_context.cc:198] Please NOTE: device: 0, CUDA Capability: 35, Driver API Version: 9.2, Runtime API Version: 8.0
W0922 12:09:06.587692 29803 device_context.cc:206] device: 0, cuDNN Version: 7.3.
!!!A non-EOF exception is thrown.
Traceback (most recent call last):
  File "test.py", line 324, in <module>
    main()
  File "test.py", line 284, in main
    main_program=None, filename='lomoDR_resnet50_iter_80000')
  File "/home/vis/enmengyi/software/anaconda2_paddle1.5_latest_cuda9.0_cudnn7.3_mkl/lib/python2.7/site-packages/paddle/fluid/io.py", line 771, in load_persistables
    filename=filename)
  File "/home/vis/enmengyi/software/anaconda2_paddle1.5_latest_cuda9.0_cudnn7.3_mkl/lib/python2.7/site-packages/paddle/fluid/io.py", line 634, in load_vars
    filename=filename)
  File "/home/vis/enmengyi/software/anaconda2_paddle1.5_latest_cuda9.0_cudnn7.3_mkl/lib/python2.7/site-packages/paddle/fluid/io.py", line 672, in load_vars
    executor.run(load_prog)
  File "/home/vis/enmengyi/software/anaconda2_paddle1.5_latest_cuda9.0_cudnn7.3_mkl/lib/python2.7/site-packages/paddle/fluid/executor.py", line 617, in run
    six.reraise(*sys.exc_info())
  File "/home/vis/enmengyi/software/anaconda2_paddle1.5_latest_cuda9.0_cudnn7.3_mkl/lib/python2.7/site-packages/paddle/fluid/executor.py", line 613, in run
    use_program_cache=use_program_cache)
  File "/home/vis/enmengyi/software/anaconda2_paddle1.5_latest_cuda9.0_cudnn7.3_mkl/lib/python2.7/site-packages/paddle/fluid/executor.py", line 654, in _run_impl
    use_program_cache=use_program_cache)
  File "/home/vis/enmengyi/software/anaconda2_paddle1.5_latest_cuda9.0_cudnn7.3_mkl/lib/python2.7/site-packages/paddle/fluid/executor.py", line 731, in _run_program
    fetch_var_name)
paddle.fluid.core_avx.EnforceNotMet: Invoke operator load_combine error.
Python Call stacks:
  File "/home/vis/enmengyi/software/anaconda2_paddle1.5_latest_cuda9.0_cudnn7.3_mkl/lib/python2.7/site-packages/paddle/fluid/framework.py", line 1824, in append_op
    attrs=kwargs.get("attrs", None))
  File "/home/vis/enmengyi/software/anaconda2_paddle1.5_latest_cuda9.0_cudnn7.3_mkl/lib/python2.7/site-packages/paddle/fluid/io.py", line 671, in load_vars
    attrs={'file_path': os.path.join(load_dirname, filename)})
  File "/home/vis/enmengyi/software/anaconda2_paddle1.5_latest_cuda9.0_cudnn7.3_mkl/lib/python2.7/site-packages/paddle/fluid/io.py", line 634, in load_vars
    filename=filename)
  File "/home/vis/enmengyi/software/anaconda2_paddle1.5_latest_cuda9.0_cudnn7.3_mkl/lib/python2.7/site-packages/paddle/fluid/io.py", line 771, in load_persistables
    filename=filename)
  File "test.py", line 284, in main
    main_program=None, filename='lomoDR_resnet50_iter_80000')
  File "test.py", line 324, in <module>
    main()
C++ Call stacks:
You are not allowed to load partial data via load_combine_op, use load_op instead. at [/home/vis/enmengyi/paddle_env/Paddle/paddle/fluid/operators/load_combine_op.h:105]
PaddlePaddle Call Stacks:
0       0x7f1faa32a799p std::string paddle::platform::GetTraceBackString<char const*>(char const*&&, char const*, int) + 361
1       0x7f1faa32aacap paddle::platform::EnforceNotMet::EnforceNotMet(std::__exception_ptr::exception_ptr, char const*, int) + 154
2       0x7f1faa87d5cfp paddle::operators::LoadCombineOpKernel<paddle::platform::CUDADeviceContext, float>::LoadParamsFromBuffer(paddle::framework::ExecutionContext const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&, std::istream*, bool, std::vector<std::string, std::allocator<std::string> > const&) const + 1887
3       0x7f1faa87db00p paddle::operators::LoadCombineOpKernel<paddle::platform::CUDADeviceContext, float>::Compute(paddle::framework::ExecutionContext const&) const + 1248
4       0x7f1faa87e043p std::_Function_handler<void (paddle::framework::ExecutionContext const&), paddle::framework::OpKernelRegistrarFunctor<paddle::platform::CUDAPlace, false, 0ul, paddle::operators::LoadCombineOpKernel<paddle::platform::CUDADeviceContext, float>, paddle::operators::LoadCombineOpKernel<paddle::platform::CUDADeviceContext, double>, paddle::operators::LoadCombineOpKernel<paddle::platform::CUDADeviceContext, int>, paddle::operators::LoadCombineOpKernel<paddle::platform::CUDADeviceContext, signed char>, paddle::operators::LoadCombineOpKernel<paddle::platform::CUDADeviceContext, long> >::operator()(char const*, char const*, int) const::{lambda(paddle::framework::ExecutionContext const&)#1}>::_M_invoke(std::_Any_data const&, paddle::framework::ExecutionContext const&) + 35
5       0x7f1fac31a59bp paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&, paddle::framework::RuntimeContext*) const + 411
6       0x7f1fac31ab91p paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&) const + 529
7       0x7f1fac315403p paddle::framework::OperatorBase::Run(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&) + 307
8       0x7f1faa4bbf86p paddle::framework::Executor::RunPreparedContext(paddle::framework::ExecutorPrepareContext*, paddle::framework::Scope*, bool, bool, bool) + 294
9       0x7f1faa4beaefp paddle::framework::Executor::Run(paddle::framework::ProgramDesc const&, paddle::framework::Scope*, int, bool, bool, std::vector<std::string, std::allocator<std::string> > const&, bool) + 143
10      0x7f1faa31b9bdp
11      0x7f1faa35d47cp
12      0x7f1fe80fa577p PyEval_EvalFrameEx + 28695
13      0x7f1fe80fca99p PyEval_EvalCodeEx + 2025
14      0x7f1fe80f9f68p PyEval_EvalFrameEx + 27144
15      0x7f1fe80fca99p PyEval_EvalCodeEx + 2025
16      0x7f1fe80f9f68p PyEval_EvalFrameEx + 27144
17      0x7f1fe80fca99p PyEval_EvalCodeEx + 2025
18      0x7f1fe80f9f68p PyEval_EvalFrameEx + 27144
19      0x7f1fe80fca99p PyEval_EvalCodeEx + 2025
20      0x7f1fe80f9f68p PyEval_EvalFrameEx + 27144
21      0x7f1fe80fca99p PyEval_EvalCodeEx + 2025
22      0x7f1fe80f9f68p PyEval_EvalFrameEx + 27144
23      0x7f1fe80fca99p PyEval_EvalCodeEx + 2025
24      0x7f1fe80f9f68p PyEval_EvalFrameEx + 27144
25      0x7f1fe80fca99p PyEval_EvalCodeEx + 2025
26      0x7f1fe80f9f68p PyEval_EvalFrameEx + 27144
27      0x7f1fe80fca99p PyEval_EvalCodeEx + 2025
28      0x7f1fe80fccbap PyEval_EvalCode + 26
29      0x7f1fe811601dp
30      0x7f1fe81171c8p PyRun_FileExFlags + 120
31      0x7f1fe81183e8p PyRun_SimpleFileExFlags + 232
32      0x7f1fe812a67cp Py_Main + 2988
33      0x7f1fe7313b45p __libc_start_main + 245
34      0x7f1fe81fc07fp

===================================================================
预测代码(已省略无关代码)：
```
def main(argv=None):
    """Main function."""
    try:
        os.makedirs(ARGS.result_path)
    except OSError as e:
        if e.errno != 17:
            raise

    # model definition #
    input_image = fluid.layers.data(name='image', shape=[3, 512, 512], dtype='float32')

    # backbone
    if ARGS.backbone == 'Resnet50':
        f_common, f_score, f_geo = resnet.Resnet_East(input_image, 50)
    elif ARGS.backbone == 'Resnet50-official':
        f_common, f_score, f_geo = resnet.Resnet_East_new(input_image, 50)
    elif ARGS.backbone == 'Inception-V4-fpn':
        f_common, f_score, f_geo = inception.InceptionV4_East(input_image, 'fpn')
    elif ARGS.backbone == 'Inception-V4-wnet':
        f_common, f_score, f_geo = inception.InceptionV4_East(input_image, 'wnet')
    else:
        print('Unknown backbone type!')
        exit(-1)
    # DR
    det_proposals = create_tmp_var(name='det_proposals_var', dtype="float32", shape=[-1, 9])
    det_proposals_noscore = create_tmp_var(name='det_proposals_noscore_var', dtype="float32", shape=[-1, 8])
    det_proposals, det_proposals_noscore = fluid.layers.py_func(func=detect,
                                           x=[f_score, f_geo],
                                           out=[det_proposals, det_proposals_noscore])
    print("define model over ...")

    #load model
    place = fluid.CUDAPlace(0) if ARGS.use_gpu else fluid.CPUPlace()
    exe = fluid.Executor(place)
    if ARGS.model_dir:
        #fluid.io.load_inference_model(dirname=ARGS.model_dir,
        #                              executor=exe,
        #                              model_filename=ARGS.model_file,
        #                              params_filename=ARGS.params_file)
        fluid.io.load_persistables(executor=exe, dirname=ARGS.model_dir,
                           main_program=None, filename='lomoDR_resnet50_iter_80000')
    print("load model over ...")

    #loop for infer test images
    im_fn_list = get_images()
    print("test image number: {}".format(len(im_fn_list)))
    for im_fn in im_fn_list:
        print('image_name: {}'.format(im_fn))
        src_im = cv2.imread(im_fn)
        print("src_im: {}".format(src_im.shape))
        start_time = time.time()
        im_resized = src_im.copy()
        im_resized, (ratio_h, ratio_w) = resize_image(im_resized, max_side_len=ARGS.input_size)
        im_resized = im_resized.astype(dtype=np.float32)
        print("im_resized: {}".format(im_resized.shape))

        im_resized.astype(dtype=np.float32)
        #whitening
        im_resized[:, :, 2] -= 0.485 * 255
        im_resized[:, :, 1] -= 0.456 * 255
        im_resized[:, :, 0] -= 0.406 * 255
        im_resized[:, :, 2] /= (255.0 * 0.229)
        im_resized[:, :, 1] /= (255.0 * 0.224)
        im_resized[:, :, 0] /= (255.0 * 0.225)
        im_resized = np.swapaxes(im_resized, 1, 2)
        im_resized = np.swapaxes(im_resized, 1, 0) # C x H x W
        im_resized = im_resized[::-1, :, :]
        #img to tensor
        img_tensor = core.LoDTensor()
        img_data = im_resized[np.newaxis, :, :, :]
        img_tensor.set(img_data, place)

        #forward
        test_program = fluid.default_main_program().clone(for_test=True)
        score, boxes = exe.run(test_program,
                                          feed={'image': img_tensor},
                                          fetch_list=[f_score, det_proposals], return_numpy=False)


if __name__ == '__main__':
    main()
```

**Comment by emy-085** [comment]
save部分代码：
```
import os
import time
import numpy as np
import shutil
from datetime import datetime
import paddle.fluid as fluid

import models.resnet50 as resnet
import models.inception_v4 as inception
from models.proposal_layers import proposal_related_layer, proposal_offset_layer
from models.transform_layers import transform_layer
import models.IRM as IRM

from utils.util import *
from utils import config
from utils import data_gen
from utils import data_gen_zhengfu

# for paddle cloud visualization
import paddlecloud.visual_util as visualdl

def train_net(args):
    ######### DATA ########
    input_image = fluid.layers.data(name='image', shape=[-1, 3, 512, 512], dtype='float32',
                        append_batch_size=False)
    input_score = fluid.layers.data(name='score', shape=[-1, 1, 128, 128], dtype='float32',
                        append_batch_size=False)
    input_geo = fluid.layers.data(name='geo', shape=[-1, 9, 128, 128], dtype='float32',
                        append_batch_size=False)
    input_mask = fluid.layers.data(name='mask', shape=[-1, 1, 128, 128], dtype='float32',
                        append_batch_size=False)
    input_gt_quads = fluid.layers.data(name='gt_quads', shape=[args.roi_batch_size_per_gpu, 9],
                        dtype='float32', append_batch_size=False)

    #debug_print(fluid.layers.shape(input_image), 'input_image shape:')
    #debug_print(fluid.layers.shape(input_gt_quads), 'input_gt_quads shape:')
    ######## DR ########
    f_common, f_score, f_geo = resnet.Resnet_East_new(input_image, 50)
    #f_common, f_score, f_geo = inception.InceptionV4_East(input_image, 'fpn')
    class_loss, offset_loss = resnet.loss(f_score, f_geo, input_score, input_geo, input_mask)
    class_lw, offset_lw = 2.0, 1.0
    det_loss = class_lw * class_loss + offset_lw * offset_loss

    ######## IRM ########
    #1. proposal layer
    det_proposals = create_tmp_var(name='det_proposals_var', dtype="float32", shape=[-1, 10])
    det_proposals = fluid.layers.py_func(func=detect, x=[f_score, f_geo], out=det_proposals)
    #debug_print(det_proposals, 'det_proposals')

    #2. proposal related layer
    ref_proposals = create_tmp_var(name='ref_proposals_var', dtype="float32", shape=[args.roi_batch_size_per_gpu, 8])
    ref_gt_quads = create_tmp_var(name='ref_gt_quads_var', dtype="float32", shape=[args.roi_batch_size_per_gpu, 8])
    ref_labels = create_tmp_var(name='ref_labels_var', dtype="float32", shape=[args.roi_batch_size_per_gpu, 1])
    ref_proposals, ref_gt_quads, ref_labels = fluid.layers.py_func(func=proposal_related_layer,
                                                x=[det_proposals, input_gt_quads],
                                                out=[ref_proposals, ref_gt_quads, ref_labels])
    #debug_print(ref_proposals, 'ref_proposals')

    #3. roi_transform
    f_regions, f_masks, f_tmats = \
            fluid.layers.roi_perspective_transform(f_common,
                                                   ref_proposals,
                                                   transformed_height = 8,
                                                   transformed_width = 64,
                                                   spatial_scale = 0.25)
    debug_print(f_regions, 'f_regions')
    ref_proposals_transf = create_tmp_var(name='ref_proposals_transf_var', dtype="float32",
                                shape=[args.roi_batch_size_per_gpu, 9])
    gt_quads_transf = create_tmp_var(name='gt_quads_transf_var', dtype="float32",
                                shape=[args.roi_batch_size_per_gpu, 9])
    ref_proposals_transf = fluid.layers.py_func(func=transform_layer,
                                                x=[ref_proposals, f_tmats],
                                                out=ref_proposals_transf)
    gt_quads_transf = fluid.layers.py_func(func=transform_layer,
                                           x=[ref_gt_quads, f_tmats],
                                           out=gt_quads_transf)
    #4. compute target
    ref_offset = create_tmp_var(name='ref_offset_var', dtype="float32", shape=[args.roi_batch_size_per_gpu, 8])
    gt_length = create_tmp_var(name='gt_length_var', dtype="float32", shape=[args.roi_batch_size_per_gpu, 8])
    ref_offset, gt_length = fluid.layers.py_func(func=proposal_offset_layer,
                                                 x=[ref_proposals_transf, gt_quads_transf],
                                                 out=[ref_offset, gt_length])

    #5. compute loss
    pred_offset = IRM.ref_branch_sim(f_regions, f_masks)
    debug_print(pred_offset, 'pred_offset: ')
    ref_loss = IRM.ref_loss_L1(pred_offset, ref_offset, ref_labels, gt_length)
    debug_print(ref_loss, 'ref_loss: ')

    ######## TOTAL LOSS ########
    det_lw, ref_lw = 1.0, 1.0
    total_loss = det_lw * det_loss + ref_lw * ref_loss
    print("define model & loss over ...")

    # optimizer & graph definition #
    boundaries = [50000, 100000, 150000, 200000]
    values = [args.learning_rate, args.learning_rate * 0.5, args.learning_rate * 0.1, \
                args.learning_rate * 0.05, args.learning_rate * 0.01]
    lr = fluid.layers.piecewise_decay(boundaries, values)
    opt = fluid.optimizer.RMSProp(
        learning_rate=lr,
        regularization=fluid.regularizer.L2Decay(0.00005))
    opt.minimize(total_loss)

    if args.mem_opt:
        class_loss.persistable = True
        offset_loss.persistable = True
        det_loss.persistable = True
        ref_loss.persistable = True
        total_loss.persistable = True

    place = fluid.CUDAPlace(0) if args.use_gpu else fluid.CPUPlace()
    exe = fluid.Executor(place)
    exe.run(fluid.default_startup_program())
    print("define optimizer & graph over ...")

    # loading pretrained model if it exists #
    if args.init_model_dir:
        fluid.io.load_persistables(exe, args.init_model_dir, filename=args.init_model_filename)
    if args.pretrained_model:
        print('Loading pretrained_model ...')
        def if_exist(var):
            has_var = os.path.exists(os.path.join(args.pretrained_model, var.name))
            if has_var:
                print('var: %s found' % (var.name))
            return has_var
        fluid.io.load_vars(exe, args.pretrained_model, predicate=if_exist)
    print("load init or pretrained model over ...")

    build_strategy = fluid.BuildStrategy()
    build_strategy.enable_inplace = False
    build_strategy.memory_optimize = args.mem_opt
    compiled_prog = fluid.CompiledProgram(fluid.default_main_program()).with_data_parallel(
                  loss_name=total_loss.name, build_strategy=build_strategy)

    fetch_vars = [class_loss, offset_loss, ref_loss, lr]
    var_names = [var.name for var in fetch_vars]

    gpu_num = len(args.gpu_list.split(','))
    print("gpu_num: {}".format(gpu_num))
    # general_v4 data_gen
    #data_reader = data_gen.get_batch(num_workers=args.num_workers,
    #                                 input_size=args.input_size,
    #                                 batch_size=args.img_batch_size * gpu_num)
    # zhengfu data_gen
    data_reader = data_gen_zhengfu.get_batch(num_workers=args.num_workers,
                                     input_size=args.input_size,
                                     batch_size=args.img_batch_size * gpu_num)
    print("prepare data_reader  & feeder over ...")

    # loops for training #
    # save model function
    try:
        os.makedirs(args.model_save_dir)
    except OSError as e:
        if e.errno != 17:
            raise

    def save_model(postfix):
        model_path = os.path.join(args.model_save_dir, postfix)
        if os.path.isdir(model_path):
            shutil.rmtree(model_path)
        print 'save models to %s' % (model_path)
        fluid.io.save_persistables(exe, model_path,
                filename="lomoDR_resnet50_iter_{}".format(postfix))
        fluid.io.save_inference_model(dirname=model_path,
                                      feeded_var_names=['image'],
                                      target_vars=[f_score, f_geo],
                                      model_filename="inference_model_iter_{}".format(postfix),
                                      params_filename="inference_params_iter_{}".format(postfix),
                                      executor=exe)

    # loop
    avg_fl, avg_gl, avg_rl = 0.0, 0.0, 0.0
    start_time = time.time()
    for iter_id in range(1, args.max_iter + 1):
        print('Step {}'.format(iter_id))
        data = next(data_reader)
        f_loss, g_loss = None, None
        results = exe.run(program=compiled_prog, fetch_list=var_names,
                    feed={
                        'image': data[0],
                        'score': data[1],
                        'geo': data[2],
                        'mask':  data[3],
                        'gt_quads': data[4]
                         })
        results = [np.array(result).mean() for result in results]
        f_loss, g_loss, r_loss, _lr = [results[0]], [results[1]], [results[2]], results[3]

        print(f_loss[0], g_loss[0], 1.5 * f_loss[0] + g_loss[0])
        # display
        avg_fl += f_loss[0]
        avg_gl += g_loss[0]
        avg_rl += r_loss[0]
        if iter_id % 10 == 0:
            avg_fl = avg_fl / 10.0
            avg_gl = avg_gl / 10.0
            avg_ref_loss = avg_rl / 10.0
            avg_det_loss = class_lw * avg_fl + offset_lw * avg_gl
            avg_total_loss = det_lw * avg_det_loss + ref_lw * avg_ref_loss
            avg_time = (time.time() - start_time) / 10.0
            sys_time = datetime.now().isoformat()
            print("{}] Iteration = {:07d}, lr = {:.7f}, total_loss = {:.4f}, "
                  "speed = {:.4f} seconds/step".format(\
                    sys_time, iter_id, _lr, avg_total_loss, avg_time))
            print("{}]     class_loss = {:.4f} (* {:.2f} = {:.4f})".format(sys_time,
                    avg_fl, class_lw, class_lw * avg_fl))
            print("{}]     geo_loss = {:.4f} (* {:.2f} = {:.4f})".format(sys_time,
                    avg_gl, offset_lw, offset_lw * avg_gl))
            print("{}]     det_loss = {:.4f} (* {:.2f} = {:.4f})".format(sys_time,
                    avg_det_loss, det_lw, det_lw * avg_det_loss))
            print("{}]     ref_loss = {:.4f} (* {:.2f} = {:.4f})".format(sys_time,
                    avg_ref_loss, ref_lw, ref_lw* avg_ref_loss))

            # paddle cloud visualization
            x_dic = {"x_name": "Step", "x_value": iter_id}
            y_ls = [{"y_name": "det_loss", "y_value": avg_det_loss}, {"y_name": "ref_loss", "y_value": avg_ref_loss}]
            visualdl.show_fluid_trend(x_dic, y_ls)

            avg_fl, avg_gl, avg_rl = 0.0, 0.0, 0.0
            start_time = time.time()
        #save
        if iter_id % args.save_step == 0 or iter_id == args.max_iter:
            save_model(str(iter_id))

    print("training over!")


def main():
    args = config.get_args()
    train_net(args)


if __name__ == "__main__":
    main()
```

**Comment by SunGaofeng** [comment]
预测时推荐用load params

**Comment by SunGaofeng** [comment]
在train的时候save persistable会保存模型参数以及其他persistable的变量比如优化器需要的momentum这些，而inference的时候这种类型的变量在网络里面是没有的，所以在inference的时候会报上面列的错误“You are not allowed to load partial data via load_combine_op”。可以在train的时候使用fluid.io.save_params，然后inference的时候fluid.io.load_params
