### ISSUE TITLE
paddle预测模型，内存超限

### ISSUE THREAD

**Issue by rose100** [PaddlePaddle/Paddle#19940]
调用paddle预测模型，内存一直增长，具体信息如下：
Python版本：python2.7
paddle版本：paddlepaddle-1.5.2 cpu
模型：conv+fc 一层，预测模型
输入shape: shape=[1, 200, 5]
已经排除为输入特征的计算问题上，因为不调用模型正常

**Comment by Exception-star** [comment]
猜测buf_size偏大

**Comment by rose100** [comment]
我用的值是1024偏大吗？ 是调用过程中来不及释放吗？

**Comment by Exception-star** [comment]
> 我用的值是1024偏大吗？ 是调用过程中来不及释放吗？

改成32试试，我以前跑mnist，16G的内存都满了
