### ISSUE TITLE
ubuntu(gcc 5.4)编译C++预测文件，undefined reference to "xxx"

### ISSUE THREAD

**Issue by OliverLPH** [PaddlePaddle/Paddle#19955]
## 版本、环境信息：
    1）PaddlePaddle版本：develop
    2）CPU：None
    3）GPU：cuda8, cuDNN 7
    4）系统环境：Ubuntu1604, gcc 5.4
## 预测信息
    1）C++预测：请您提供预测库安装包的版本信息，及其中的version.txt文件
    2）CMake包含路径的完整命令
    3）API信息（如调用请提供）
    4）预测库来源：官网下载: [下载链接](https://paddle-inference-lib.bj.bcebos.com/latest-gpu-cuda8-cudnn7-avx-mkl/fluid_inference.tgz) https://paddlepaddle.org.cn/documentation/docs/zh/advanced_usage/deploy/inference/build_and_install_lib_cn.html 
## 复现信息：如为报错，请给出复现环境、复现步骤

复现环境：ubuntu1604，gcc5.4 
复现步骤：从官网下载预测库，编译预测文件。

## 问题描述：
报错信息如图，会报undefined reference to "xxx"的错误。
<img width="1440" alt="a7532415ff0adc1a673d6c53f801672e" src="https://user-images.githubusercontent.com/14963836/65489064-f2d92800-dedc-11e9-8131-3005b5c9a43d.png">

重新编译预测库可以解决这个问题，或者改用centos也不会遇到这个问题。

**Comment by sandyhouse** [comment]
编译命令是什么？

**Comment by OliverLPH** [comment]
> 编译命令是什么？

```shell
cmake .. -DWITH_GPU=ON  -DPADDLE_DIR=/pd_solution_test/paddle-infer/Paddle/build_infer_mkldnn/fluid_inference_install_dir/ -DCUDA_LIB=/usr/local/cuda/lib64/ -DOPENCV_DIR=/pd_solution_test/opencv/opencv-3.4.6/release/ -DCUDNN_LIB=/usr/lib/x86_64-linux-gnu/
```
我觉得跟这个编译命令应该没关系吧，这是我编译预测文件的。

**Comment by OliverLPH** [comment]
刚刚验证了下，不是ubuntu的原因，是gcc版本的问题。切换到gcc 4.8.2就不会遇到这个编译的问题了。

**Comment by sandyhouse** [comment]
好的，我也给相关同学反馈下这个问题。

**Comment by fc500110** [comment]
gcc5和gcc4的ABI兼容性问题，添加一个宏-D_GLIBCXX_USE_CXX11_ABI=0，可以参考https://stackoverflow.com/questions/45417707/glibcxx-use-cxx11-abi-gcc-4-8-and-abi-compatibility
