### ISSUE TITLE
ocr_recognition训练attention时报错

### ISSUE THREAD

**Issue by lebronjdw** [PaddlePaddle/Paddle#19951]
版本、环境信息：
paddlepaddle 1.5.1（cpu版本）
anaconda
代码来自场景文字识别的OCR Attention：
https://github.com/PaddlePaddle/models/tree/develop/PaddleCV/ocr_recognition
训练360w中文图集，数据根据要求label.list已经加了相应的宽高
修改代码部分
NUM_CLASSES = 5990
加了打印信息fluid.layers.Print(label_out, message="label_out", summarize=10)
报错显示如下：
finish batch shuffle
1569295129	label_out	The place is:CPUPlace
Tensor[label_out]
	shape: [64,1,]
	dtype: i
	LoD: [[ 0,2,4,6,8,10,12,14,16,18,20,22,24,26,28,30,32,34,36,38,40,42,44,46,48,50,52,54,56,58,60,62,64, ]]
	data: 129,1,795,1,49,1,27,1,2,1,
1569295130	label_out	The place is:CPUPlace
Tensor[label_out]
	shape: [64,1,]
	dtype: i
	LoD: [[ 0,2,4,6,8,10,12,14,16,18,20,22,24,26,28,30,32,34,36,38,40,42,44,46,48,50,52,54,56,58,60,62,64, ]]
	data: 1704,1,459,1,125,1,336,1,14,1,
1569295131	label_out	The place is:CPUPlace
Tensor[label_out]
	shape: [64,1,]
	dtype: i
	LoD: [[ 0,2,4,6,8,10,12,14,16,18,20,22,24,26,28,30,32,34,36,38,40,42,44,46,48,50,52,54,56,58,60,62,64, ]]
	data: 353,1,9,1,264,1,128,1,700,1,
1569295132	label_out	The place is:CPUPlace
Tensor[label_out]
	shape: [64,1,]
	dtype: i
	LoD: [[ 0,2,4,6,8,10,12,14,16,18,20,22,24,26,28,30,32,34,36,38,40,42,44,46,48,50,52,54,56,58,60,62,64, ]]
	data: 366,1,1221,1,2,1,303,1,25,1,
1569295133	label_out	The place is:CPUPlace
Tensor[label_out]
	shape: [64,1,]
	dtype: i
	LoD: [[ 0,2,4,6,8,10,12,14,16,18,20,22,24,26,28,30,32,34,36,38,40,42,44,46,48,50,52,54,56,58,60,62,64, ]]
	data: 103,1,477,1,13,1,110,1,2,1,
1569295134	label_out	The place is:CPUPlace
Tensor[label_out]
	shape: [64,1,]
	dtype: i
	LoD: [[ 0,2,4,6,8,10,12,14,16,18,20,22,24,26,28,30,32,34,36,38,40,42,44,46,48,50,52,54,56,58,60,62,64, ]]
	data: 709,1,31,1,716,1,34,1,158,1,
1569295135	label_out	The place is:CPUPlace
Tensor[label_out]
	shape: [64,1,]
	dtype: i
	LoD: [[ 0,2,4,6,8,10,12,14,16,18,20,22,24,26,28,30,32,34,36,38,40,42,44,46,48,50,52,54,56,58,60,62,64, ]]
	data: 6,1,1142,1,528,1,6,1,435,1,
Traceback (most recent call last):
  File "train.py", line 245, in <module>
    main()
  File "train.py", line 241, in main
    train(args)
  File "train.py", line 172, in train
    results = train_one_batch(data)
  File "train.py", line 132, in train_one_batch
    fetch_list=fetch_vars)
  File "/home/sheldon/anaconda3/envs/pd/lib/python3.7/site-packages/paddle/fluid/executor.py", line 651, in run
    use_program_cache=use_program_cache)
  File "/home/sheldon/anaconda3/envs/pd/lib/python3.7/site-packages/paddle/fluid/executor.py", line 749, in _run
    exe.run(program.desc, scope, 0, True, True, fetch_var_name)
paddle.fluid.core_avx.EnforceNotMet: Invoke operator edit_distance error.
Python Callstacks: 
  File "/home/sheldon/anaconda3/envs/pd/lib/python3.7/site-packages/paddle/fluid/framework.py", line 1771, in append_op
    attrs=kwargs.get("attrs", None))
  File "/home/sheldon/anaconda3/envs/pd/lib/python3.7/site-packages/paddle/fluid/layer_helper.py", line 43, in append_op
    return self.main_program.current_block().append_op(*args, **kwargs)
  File "/home/sheldon/anaconda3/envs/pd/lib/python3.7/site-packages/paddle/fluid/layers/nn.py", line 5430, in edit_distance
    attrs={"normalized": normalized})
  File "/home/sheldon/anaconda3/envs/pd/lib/python3.7/site-packages/paddle/fluid/evaluator.py", line 261, in __init__
    input=input, label=label, ignored_tokens=ignored_tokens)
  File "/home/sheldon/github/models/PaddleCV/ocr_recognition/attention_model.py", line 197, in attention_train_net
    input=maxid, label=label_out, ignored_tokens=[sos, eos])
  File "train.py", line 81, in train
    args, data_shape, num_classes)
  File "train.py", line 241, in main
    train(args)
  File "train.py", line 245, in <module>
    main()
C++ Callstacks: 
Reference string 26 is empty. at [/paddle/paddle/fluid/operators/edit_distance_op.h:42]
PaddlePaddle Call Stacks: 
0       0x7fc4c0a0b950p void paddle::platform::EnforceNotMet::Init<char const*>(char const*, char const*, int) + 352
1       0x7fc4c0a0bcc9p paddle::platform::EnforceNotMet::EnforceNotMet(std::__exception_ptr::exception_ptr, char const*, int) + 137
2       0x7fc4c0ea91d8p paddle::operators::EditDistanceKernel<paddle::platform::CPUPlace, float>::Compute(paddle::framework::ExecutionContext const&) const + 5032
3       0x7fc4c0ea9363p std::_Function_handler<void (paddle::framework::ExecutionContext const&), paddle::framework::OpKernelRegistrarFunctor<paddle::platform::CPUPlace, false, 0ul, paddle::operators::EditDistanceKernel<paddle::platform::CPUPlace, float> >::operator()(char const*, char const*, int) const::{lambda(paddle::framework::ExecutionContext const&)#1}>::_M_invoke(std::_Any_data const&, paddle::framework::ExecutionContext const&) + 35
4       0x7fc4c2a9a057p paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&, paddle::framework::RuntimeContext*) const + 375
5       0x7fc4c2a9a431p paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&) const + 529
6       0x7fc4c2a97a2cp paddle::framework::OperatorBase::Run(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&) + 332
7       0x7fc4c0b9673ep paddle::framework::Executor::RunPreparedContext(paddle::framework::ExecutorPrepareContext*, paddle::framework::Scope*, bool, bool, bool) + 382
8       0x7fc4c0b997dfp paddle::framework::Executor::Run(paddle::framework::ProgramDesc const&, paddle::framework::Scope*, int, bool, bool, std::vector<std::string, std::allocator<std::string> > const&, bool) + 143
9       0x7fc4c09fcfddp
10      0x7fc4c0a3e286p
11      0x559668a19744p _PyMethodDef_RawFastCallKeywords + 596
12      0x559668a19861p _PyCFunction_FastCallKeywords + 33
13      0x559668a856e8p _PyEval_EvalFrameDefault + 21240
14      0x5596689c9539p _PyEval_EvalCodeWithName + 761
15      0x559668a18f57p _PyFunction_FastCallKeywords + 903
16      0x559668a818ccp _PyEval_EvalFrameDefault + 5340
17      0x5596689c9539p _PyEval_EvalCodeWithName + 761
18      0x559668a18f57p _PyFunction_FastCallKeywords + 903
19      0x559668a818ccp _PyEval_EvalFrameDefault + 5340
20      0x5596689c9d09p _PyEval_EvalCodeWithName + 2761
21      0x559668a18f57p _PyFunction_FastCallKeywords + 903
22      0x559668a80806p _PyEval_EvalFrameDefault + 1046
23      0x5596689c9d09p _PyEval_EvalCodeWithName + 2761
24      0x559668a18f57p _PyFunction_FastCallKeywords + 903
25      0x559668a80806p _PyEval_EvalFrameDefault + 1046
26      0x559668a18ccbp _PyFunction_FastCallKeywords + 251
27      0x559668a80806p _PyEval_EvalFrameDefault + 1046
28      0x5596689c9539p _PyEval_EvalCodeWithName + 761
29      0x5596689ca424p PyEval_EvalCodeEx + 68
30      0x5596689ca44cp PyEval_EvalCode + 28
31      0x559668adfb74p
32      0x559668ae9eb1p PyRun_FileExFlags + 161
33      0x559668aea0a3p PyRun_SimpleFileExFlags + 451
34      0x559668aeb195p
35      0x559668aeb2bcp _Py_UnixMain + 60
36      0x7fc4f37f9b97p __libc_start_main + 231
37      0x559668a90062p

**Comment by sandyhouse** [comment]
确认下edit_distance的输入是否有问题，比如字符串是否为空串。

**Comment by lebronjdw** [comment]
> 
输入的label格式都是这样的，你说的空串指的是？
280 48 20455828_2605100732.jpg 263 82 29 56 35 435 890 293 126 129
280 48 20455953_2495695852.jpg 183 17 1454 304 43 259 312 11 130 795
280 48 20456062_1743140291.jpg 153 432 950 150 65 899 115 7 97 49
280 48 20456156_569666054.jpg 466 28 192 99 412 28 199 2 169 27
280 48 20456234_304574174.jpg 1162 61 88 583 638 26 463 39 833 2
280 48 20456468_2872799721.jpg 206 581 167 772 767 55 219 2 561 298
280 48 20456562_2869395312.jpg 970 339 1517 28 1400 124 868 339 239 622

**Comment by sandyhouse** [comment]
Reference string 26 is empty. at [/paddle/paddle/fluid/operators/edit_distance_op.h:42]，是不是有字符串为“”或者None

**Comment by lebronjdw** [comment]
> Reference string 26 is empty. at [/paddle/paddle/fluid/operators/edit_distance_op.h:42]，是不是有字符串为“”或者None

检查了一下train.list的数据，每个字符之间都是只有一个空格，数据上是满足要求的啊

**Comment by sandyhouse** [comment]
可以提供可复现的代码吗？

**Comment by lebronjdw** [comment]
> 可以提供可复现的代码吗？

只改了NUM_CLASSES，唯一不同的是用的360万中文数据集

**Comment by sandyhouse** [comment]
360万中文数据集是开源的吗，有没有链接可以提供？

**Comment by lebronjdw** [comment]
> 360万中文数据集是开源的吗，有没有链

https://pan.baidu.com/s/1dFda6R3?errno=0&errmsg=Auth%20Login%20Sucess&&bduss=&ssnerror=0&traceid=#list/path=%2F

**Comment by lebronjdw** [comment]
> > 360万中文数据集是开源的吗，有没有链
> 
> https://pan.baidu.com/s/1dFda6R3?errno=0&errmsg=Auth%20Login%20Sucess&&bduss=&ssnerror=0&traceid=#list/path=%2F



> 360万中文数据集是开源的吗，有没有链接可以提供？

压缩包大概10G左右，有结果麻烦告知一下

**Comment by sandyhouse** [comment]
有没有其它下载源的数据，没有会员10G下载估计需要好长时间呀！或者有没有可复现的小数据集？

**Comment by lebronjdw** [comment]
> 有没有其它下载源的数据，没有会员10G下载估计需要好长时间呀！或者有没有可复现的小数据集？

你们百度的人都没有会员啊，百度网盘有破解版PanDownload，估计半个小时就下完了

**Comment by sandyhouse** [comment]
你好，能提供下符合训练要求的train_list.txt吗 @lebronjdw

**Comment by lebronjdw** [comment]
> 你好，能提供下符合训练要求的train_list.txt吗 @lebronjdw

不好意思，最近忙着项目的东西，这个train_list.txt在我之前提供的百度网盘的链接里面有，500M左右，如果我自己贴也是这么大

**Comment by sandyhouse** [comment]
你网盘里面的train.txt格式和要求的格式不一样呀，能转换一下并提供吗？我不太了解你的train.txt什么格式。
paddle模型要求的格式：
![image](https://user-images.githubusercontent.com/6737864/67389814-f8a25600-f5cd-11e9-9add-73b9d33ae2cf.png)
网盘中train.txt的格式
![image](https://user-images.githubusercontent.com/6737864/67389882-153e8e00-f5ce-11e9-954c-f8a78777dff3.png)

**Comment by lebronjdw** [comment]
> 你网盘里面的train.txt格式和要求的格式不一样呀，能转换一下并提供吗？我不太了解你的train.txt什么格式。
> paddle模型要求的格式：
> ![image](https://user-images.githubusercontent.com/6737864/67389814-f8a25600-f5cd-11e9-9add-73b9d33ae2cf.png)
> 网盘中train.txt的格式
> ![image](https://user-images.githubusercontent.com/6737864/67389882-153e8e00-f5ce-11e9-954c-f8a78777dff3.png)

我了解你的意思了，paddle是要有宽高，我可以提供我写前缀的代码:
namespace fileaddsuf
{
    class Program
    {
        static void Main(string[] args)
        {

            string[] filelist = File.ReadAllLines(@"train.txt", Encoding.Default);
            for (int linenum = 0; linenum <= filelist.Length - 1; linenum++)
            {
                filelist[linenum] = "280 48 " + filelist[linenum];
            }
            File.WriteAllLines(@"train.txt", filelist, Encoding.Default);
        }
    }
}
这里我写的高是48,是我事先对所有图片都先进行过高度的resize了

**Comment by sandyhouse** [comment]
也就是说，所有图片都是固定的宽280高48？

**Comment by lebronjdw** [comment]
> 也就是说，所有图片都是固定的宽280高48？

数据集原数据是280*32的

**Comment by sandyhouse** [comment]
![image](https://user-images.githubusercontent.com/6737864/67457695-f6400a80-f666-11e9-9b98-2b0f05ef3082.png)
训练脚本要求的label格式是使用','分割的，但是你使用的是空格分割的。

> 输入的label格式都是这样的，你说的空串指的是？
> 280 48 20455828_2605100732.jpg 263 82 29 56 35 435 890 293 126 129
> 280 48 20455953_2495695852.jpg 183 17 1454 304 43 259 312 11 130 795
> 280 48 20456062_1743140291.jpg 153 432 950 150 65 899 115 7 97 49
> 280 48 20456156_569666054.jpg 466 28 192 99 412 28 199 2 169 27
> 280 48 20456234_304574174.jpg 1162 61 88 583 638 26 463 39 833 2
> 280 48 20456468_2872799721.jpg 206 581 167 772 767 55 219 2 561 298
> 280 48 20456562_2869395312.jpg 970 339 1517 28 1400 124 868 339 239 622

**Comment by lebronjdw** [comment]
> ![image](https://user-images.githubusercontent.com/6737864/67457695-f6400a80-f666-11e9-9b98-2b0f05ef3082.png)
> 训练脚本要求的label格式是使用','分割的，但是你使用的是空格分割的。
> 
> > 输入的label格式都是这样的，你说的空串指的是？
> > 280 48 20455828_2605100732.jpg 263 82 29 56 35 435 890 293 126 129
> > 280 48 20455953_2495695852.jpg 183 17 1454 304 43 259 312 11 130 795
> > 280 48 20456062_1743140291.jpg 153 432 950 150 65 899 115 7 97 49
> > 280 48 20456156_569666054.jpg 466 28 192 99 412 28 199 2 169 27
> > 280 48 20456234_304574174.jpg 1162 61 88 583 638 26 463 39 833 2
> > 280 48 20456468_2872799721.jpg 206 581 167 772 767 55 219 2 561 298
> > 280 48 20456562_2869395312.jpg 970 339 1517 28 1400 124 868 339 239 622
okay,好的，我再重新写下
