### ISSUE TITLE
官网文档和代码不符？

### ISSUE THREAD

**Issue by xiuechen** [PaddlePaddle/Paddle#19958]
paddlepaddle.org.cn/documentation/docs/zh/1.5/advanced_usage/deploy/inference/native_infer.html

在这里写道：

PaddleTensor可用于NativePredictor和AnalysisPredictor，在 NativePredictor样例中展示了PaddleTensor的使用方式。 PaddleTensor 定义了预测最基本的输入输出的数据格式，常用字段如下：

name，类型：string，用于指定输入数据对应的模型中variable的名字
shape，类型：vector<int>, 表示一个Tensor的shape
data，类型：PaddleBuf, 数据以连续内存的方式存储在PaddleBuf中，PaddleBuf可以接收外面的数据或者独立malloc内存，详细可以参考头文件中相关定义。
dtype，类型：PaddleType, 有PaddleDtype::FLOAT32, PaddleDtype::INT64, PaddleDtype::INT32三种, 表示 Tensor 的数据类型。
lod，类型：vector<vector<size_t>>，在处理变长输入的时候，需要对 PaddleTensor设置LoD信息。可以参考LoD-Tensor使用说明

但是看代码里面：Paddle/paddle/contrib/inference/paddle_inference_api.h

 40 struct PaddleTensor {
 41   std::string name;  // variable name.
 42   std::vector<int> shape;
 43   PaddleBuf data;  // blob of data.
 44   PaddleDType dtype;
 45 };

并没有lod这个字段啊？怎么在C++中处理lod-tensor呢？

**Comment by OliverLPH** [comment]
在Paddle/paddle/fluid/inference/api/paddle_api.h中有相关定义
```c++
struct PaddleTensor {
  PaddleTensor() = default;
  std::string name;  // variable name.
  std::vector<int> shape;
  PaddleBuf data;  // blob of data.
  PaddleDType dtype;
  std::vector<std::vector<size_t>> lod;  // Tensor+LoD equals LoDTensor
};
```
