### ISSUE TITLE
fluid1.5中fluid.layers.embedding中的is_sparse设置为true 和 false 有啥区别么

### ISSUE THREAD

**Issue by lizhiqings** [PaddlePaddle/Paddle#19987]
fluid1.5中fluid.layers.embedding中的is_sparse设置为true 和 false时，模型训练完保存模型参数，这两种模式下的 模型参数有啥区别么

**Comment by FDInSky** [comment]
这个是训练时进行稀疏更新，节省了显存，在SGD训练时尤为明显，但对最终结果是没有影响的，跟非稀疏方式一样
