### ISSUE TITLE
ParameterConf.proto and attrs.py are not consistent

### ISSUE THREAD

**Issue by lzhao4ever** [PaddlePaddle/Paddle#1999]
In proto/ParameterConf.proto,
ParameterConfig has attribute initial_strategy, but does not have initial_max, initial_min.

In python/paddle/trainer_config_helpers,
class ParameterAttribute has arguments initial_max, initial_min, but not initial_strategy.

**Comment by typhoonzero** [comment]
Close due to low activity, please feel free to reopen it.
