### ISSUE TITLE
yolo v3的预测值能输出负值么？

### ISSUE THREAD

**Issue by 1145520074** [PaddlePaddle/Paddle#19991]
我看 yolov3的输出限定在了图像范围内，但在我的应用中希望位置预测到图像外，比如检测残缺问题时，希望知道原本图像有多大。该怎么修改？

欢迎您对PaddlePaddle提出建议，非常感谢您对PaddlePaddle的贡献！
在留下您的建议时，辛苦您同步提供如下信息：
- 版本、环境信息
1）PaddlePaddle版本：请提供您的PaddlePaddle版本号，例如1.1
2）CPU/GPU：您是否使用GPU进行训练，如是，请提供您的CUDA和cuDNN版本号
3）系统环境：请您描述系统类型、版本，例如Mac OS 10.14
- 复现信息：如为报错，请给出复现环境、复现步骤
- 建议描述：请您详细描述，您认为需优化的功能

Thank you for contributing to PaddlePaddle.
Before submitting the issue, you could search issue in the github in case that there was a similar issue submitted or resolved before.
Please make sure that this is a feature request. 
**System information**
-PaddlePaddle version （eg.1.1）or CommitID
-CPU: including CPUMKL/OpenBlas/MKLDNN version
-GPU: including CUDA/CUDNN version
-OS Platform (eg.Mac OS 10.14)
**To Reproduce**
Steps to reproduce the behavior
**Describe the feature and the current behavior/state.**
**Any Other info.**

**Comment by heavengate** [comment]
当前yolov3检测在训练和预测的时候会对超过边界的框都会对检测框进行裁剪，如果要预测输出负值的话需要自己python实现网络最后两个OP，yolo_box和multiclass_nms，然后网络最后不要用这两个OP处理，改用自定义python代码处理

**Comment by 1145520074** [comment]
> 当前yolov3检测在训练和预测的时候会对超过边界的框都会对检测框进行裁剪，如果要预测输出负值的话需要自己python实现网络最后两个OP，yolo_box和multiclass_nms，然后网络最后不要用这两个OP处理，改用自定义python代码处理

请问这两个 op 的源码在哪里

**Comment by ceci3** [comment]
yolo_box:  https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/fluid/operators/detection/yolo_box_op.h
multiclass_nms:https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/fluid/operators/detection/multiclass_nms_op.cc
