### ISSUE TITLE
how to deal with changing input size

### ISSUE THREAD

**Issue by tensor-tang** [PaddlePaddle/Paddle#2000]
请问怎么处理图像的大小在训练过程中实时改变的情况？应该怎么写dataprovider？
现有的我能看到的情况，好像都只能支持图像大小被fix住的情况，也就是input size是固定，不知道是否支持可变的？

**Comment by lcy-seso** [comment]
目前不支持这种场景，@qingqing01 更了解这个话题，会帮忙解答。谢谢啦。

**Comment by qingqing01** [comment]
可以做到mini-batch内图片的高和宽一致，但也需要小修改代码。如果mini-batch内图片也可以变，目前较难支持。 请问您是哪种场景呢？ mini-batch内也是可变的吗？

**Comment by tensor-tang** [comment]
谢谢你的回复。
现在希望的就是你说的第一种情况：
当前min-batch与下一个min-batch内的layersize可以允许不一样。

希望的是至少Conv，FC，Batchnorm，Relu，还有recurrent layer都能支持这种模式，这样的话code修改量应该挺大的吧。

因为至少我现在看FC的size，是在init的时候就从proto config定好了。
对于conv， 从code上看貌似没太大问题，但是layersize也是从proto就config好了，forward的时候只是根据inputsize改了图片大小，还没有实际测过。

我们现在是object detection的场景。

不知道我现在的理解有没有什么问题，另外对于我说的其他layer是否默认也是不支持的？

**Comment by qingqing01** [comment]
@tensor-tang 你的理解基本没问题的。

对于全卷积网络后面接RNN这种模式(类似OCR应用)，这种图像变长的模式，我们C++核心代码是支持的。如果卷积后面接FC这种，需要使用SPP吧。 

我们推广使用v2 API，当前v2 API还不支持这种变长使用，后期会尽快支持的。

**Comment by tensor-tang** [comment]
我现在希望的是conv，batchnorm， fc，recurrent 这些layer都可以支持batch间layersize可变。
（并不是说我们会把FC接在Conv后面）

既然v2 的API现在不支持 ，那用原来v1的可以吗？
如果可以，具体应该怎么实现呢？有什么地方需要特别注意呢？

谢谢

**Comment by lcy-seso** [comment]
我没有理解这一句 "因为至少我现在看FC的size，是在init的时候就从proto config定好了。" 有什么问题呢？ 每个layer 都需要从配置里面获取的size 来决定自己需要学习的参数有多少，一定是固定的。比如， FC 层需要决定的是这一层有多少个神经元，卷积层需要决定卷积核大小等，参数的size始终都是固定的，是一种design choice。

唯一在变化的是，接受序列输入数据，序列长度在变化。

**Comment by yao-matrix** [comment]
@lcy-seso 参数的size是固定的是OK的。我们的诉求在于我的的场景中BN, conv, rnn层的输入数据的size是variable的，希望Paddle team指教这种情况paddle是支持的吗？如果是支持的，有没有什么tutorial可以教我们如何使用， 谢谢。

**Comment by tensor-tang** [comment]
@lcy-seso 在这个问题里面，我说的size与序列长度无关，指的是每个序列中每个sample的size，也就是我开始说的图像size，而不是参数的size，这里FC例子可能不恰当，没能准确说明我的疑问。

**Comment by qingqing01** [comment]
@tensor-tang  v1的dataprovider也不支持。 

> 如果可以，具体应该怎么实现呢？有什么地方需要特别注意呢？

需要每个mini-batch输入的数据设置图像的height和width，C++里面的接口在这里：https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/parameter/Argument.h#L139，v2的Python API里 https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/v2/trainer.py#L150 这块创建输入参数时需要设置 (可能也没说的很明白)。抱歉，我上面说的"小修改代码"有点误导了你，实现过程是有点麻烦。

我们尽快让v2 API支持吧。

**Comment by tensor-tang** [comment]
@qingqing01 好的，谢谢~
