### ISSUE TITLE
Not all pre-defined networks can be found in V2 doc.

### ISSUE THREAD

**Issue by lcy-seso** [PaddlePaddle/Paddle#2001]
I have a question about v2 API doc.
- As I known the doc is automatically generated from codes, but I fail to find some pre-defined network in V2 API doc.
- For example, provided doc for [Network](http://www.paddlepaddle.org/develop/doc/api/v2/config/networks.html) is generated from [this source file](
https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/trainer_config_helpers/networks.py), but I cannot find `bidirectional_gru`, is this a bug?

**Comment by kuke** [comment]
Seems true. I found the `bidirectional_lstm` but can located `bidirectional_gru` in v2 doc

**Comment by luotao1** [comment]
I will fix it ASAP.
