### ISSUE TITLE
PaddlePredictor开启显存优化影响预测结果

### ISSUE THREAD

**Issue by Meiyim** [PaddlePaddle/Paddle#20020]
使用的版本的paddle_inference包（nightly-build, 版本信息：
```
GIT COMMIT ID: 2c5c6365144a1bc9f36be2af53758c391b321f84
WITH_MKL: ON
WITH_MKLDNN: ON
WITH_GPU: ON
CUDA version: 9.0
CUDNN version: v7
```

AnalysisConfig部分代码：
```C++
  paddle::AnalysisConfig config;
  config.SetModel(FLAGS_model_dir);
  config.EnableUseGpu(100, 0);
  config.SwitchSpecifyInputNames(true);
  config.EnableCUDNN();
  config.SwitchIrOptim(true);
  config.EnableMemoryOptim();

  auto predictor = CreatePaddlePredictor(config);
```
模型结构已经上传：
[__model__.tar.gz](https://github.com/PaddlePaddle/Paddle/files/3655656/__model__.tar.gz)

**Comment by jiweibo** [comment]
> 使用的版本的paddle_inference包（nightly-build, 版本信息：
> 
> ```
> GIT COMMIT ID: 2c5c6365144a1bc9f36be2af53758c391b321f84
> WITH_MKL: ON
> WITH_MKLDNN: ON
> WITH_GPU: ON
> CUDA version: 9.0
> CUDNN version: v7
> ```
> 
> AnalysisConfig部分代码：
> 
> ```c++
>   paddle::AnalysisConfig config;
>   config.SetModel(FLAGS_model_dir);
>   config.EnableUseGpu(100, 0);
>   config.SwitchSpecifyInputNames(true);
>   config.EnableCUDNN();
>   config.SwitchIrOptim(true);
>   config.EnableMemoryOptim();
> 
>   auto predictor = CreatePaddlePredictor(config);
> ```
> 
> 模型结构已经上传：
> [**model**.tar.gz](https://github.com/PaddlePaddle/Paddle/files/3655656/__model__.tar.gz)

没有参数文件吗？我看了你提供的这么模型比较复杂，希望能一块提供参数文件，我们好复现问题
