### ISSUE TITLE
功能实现

### ISSUE THREAD

**Issue by lizhiqings** [PaddlePaddle/Paddle#20031]
fluid1.5 是否有这样一个api，就是：

存在某个tensor，如：label = fluid.layers.data(name='label', shape=[1], dtype='float32')，
现在需要生成一个和 label 形状一样的 tensor叫 temp，但是 每个元素满足这样的条件，当label >=1 时候 temp = 2，当label <1 时候 temp = 1， 类似这样的api

**Comment by ceci3** [comment]
可以试下IfElse这个op

**Comment by lizhiqings** [comment]
有demo 可以参考么 没用过ifelse 这个api

发件人: lvmengsi <notifications@github.com>
答复: PaddlePaddle/Paddle <reply@reply.github.com>
日期: 2019年9月26日 星期四 下午4:30
收件人: PaddlePaddle/Paddle <Paddle@noreply.github.com>
抄送: "Li,Zhiqing" <lizhiqing@baidu.com>, Author <author@noreply.github.com>
主题: Re: [PaddlePaddle/Paddle] 功能实现 (#20031)


可以试下IfElse这个op

**Comment by ceci3** [comment]
https://www.paddlepaddle.org.cn/documentation/docs/zh/1.5/api_cn/layers_cn/control_flow_cn.html#ifelse 可以参考官网的例子
