### ISSUE TITLE
如何拆分embedding 层 解析embedding参数

### ISSUE THREAD

**Issue by lizhiqings** [PaddlePaddle/Paddle#20033]
我的脚本如下，所有特征共享一个embedding层 叫“SparseFeatFactors”，但是执行fluid.io.save_inference_model后 出现了 多个以SparseFeatFactors前缀的文件，想了解下 除了 SparseFeatFactors外其余文件是啥用？
![ppp](https://user-images.githubusercontent.com/47736115/65672997-944ab000-e07c-11e9-9332-0d72cff36dd8.png)
![ooo](https://user-images.githubusercontent.com/47736115/65673002-97de3700-e07c-11e9-9d3a-98c115e8aa53.png)

另外我想做的是：因为这个embedding参数太大了，加载到线上很占用内存，我希望将 这个embedding层参数和 网络其他参数分开，也就是说 在线上c++我只加载 除了embedding之外的网络部分，这时候网络的输入就变成了 自己需要手动检索 embedding 字典 拼接向量。所以离线怎么解析这个SparseFeatFactors文件？

**Comment by ceci3** [comment]
除了 SparseFeatFactors外其余文件都是优化器里的信息，离线加载还是得构造一个相同的网络 t = fluid.global_scope().find_var(name).get_tensor() 通过这种方式得到这个参数。
