### ISSUE TITLE
paddle.fluid.core.EnforceNotMet: Enforce failed. Expected ele_dtype == dtype, but received ele_dtype:5 != dtype:4.

### ISSUE THREAD

**Issue by tianxin1860** [PaddlePaddle/Paddle#20043]
- 版本、环境信息：
    1）PaddlePaddle版本：1.5.0.post107
    2）GPU：P40、CUDA10、Cudnn7.4
    3）系统环境：Python 2.7
- 训练信息
    1）单机8卡
- 问题描述：请详细描述您的问题，同步贴出报错信息、日志、可复现的代码片段
本地机器调试多卡没问题，但是上集群跑分布式任务就报如下错误:
![image](https://user-images.githubusercontent.com/6829601/65737914-9c552f00-e112-11e9-87e8-cc1274e78741.png)

**Comment by zhaoyuchen2018** [comment]
看起来是alloc_continuous_space_for_grad_pass.cc这个PASS在处理的时候出错了，您能提供一下复现代码吗，我让分布式的同学看一下。

**Comment by gongweibao** [comment]
请用1.5.2。
