### ISSUE TITLE
执行代码paddle.fluid.install_check.run_check()报错

### ISSUE THREAD

**Issue by bytekongfrombupt** [PaddlePaddle/Paddle#20046]
为使您的问题得到快速解决，在建立Issue前，请您先通过如下方式搜索是否有相似问题:【搜索issue关键字】【使用labels筛选】【官方文档】

建立issue时，为快速解决问题，请您根据使用情况给出如下信息：
- 标题：请包含关键词“安装错误”/“编译错误”，例如“Mac编译错误”
- 版本、环境信息：
    1）PaddlePaddle版本：最新
    2）CPU：请提供CPU型号，MKL/OpenBlas/MKLDNN/等数学库的使用情况
    3）GPU：cuda10 cudnn7.6
    4）系统环境：linux
- 安装方式信息：
1）pip安装/docker安装
2）本地编译：请提供cmake命令，编译命令
3）docker编译：请提供docker镜像，编译命令            
  特殊环境请注明：如离线安装等
- 复现信息：如为报错，请给出复现环境、复现步骤
- 问题描述：请详细描述您的问题，同步贴出报错信息、日志/代码关键片段
paddle.fluid.install_check.run_check()报错：segmentation fault
![image](https://user-images.githubusercontent.com/33115565/65748031-8ad14e80-e135-11e9-8eaf-b76dbb2ea89c.png)

Thank you for contributing to PaddlePaddle.
Before submitting the issue, you could search issue in Github in case that there was a similar issue submitted or resolved before.
If there is no solution,please make sure that this is an installation issue including the following details:
**System information**
-PaddlePaddle version （eg.1.1）or CommitID
-CPU: including CPUMKL/OpenBlas/MKLDNN version
-GPU: including CUDA/CUDNN version
-OS Platform (eg. Mac OS 10.14)
-Python version
- Install method: pip install/install with docker/build from source(without docker)/build within docker
- Other special cases that you think may be related to this problem, eg. offline install, special internet condition   
**To Reproduce**
Steps to reproduce the behavior
**Describe your current behavior**
**Code to reproduce the issue**
**Other info / logs**

**Comment by zhaoyuchen2018** [comment]
你是用conda安装的么?
还有其他信息打出来吗，试一试ulimit -c unlimited，然后重新运行程序生成一份coredump传上来我们分析下。

**Comment by bytekongfrombupt** [comment]
@zhaoyuchen2018  我是用的pip install paddlepaddle-gpu，没有其他的输出，只有一行segmentation fault，然后我刚才下载了pip install paddlehub，import paddlehub之后paddlehub.model(name='ernie')提示没有这个模型

**Comment by bytekongfrombupt** [comment]
我是不是得重新卸载了安装……

**Comment by zhaoyuchen2018** [comment]
> 我是不是得重新卸载了安装……

我看你的python是Anaconda的，你能不能尝试下不要用conda的python，然后再重新安装一下。

**Comment by bytekongfrombupt** [comment]
@zhaoyuchen2018 emm 可是我用conda创建的虚拟环境，然后不用自带的python是不是会有点复杂

**Comment by zhaoyuchen2018** [comment]
> @zhaoyuchen2018 emm 可是我用conda创建的虚拟环境，然后不用自带的python是不是会有点复杂

其实也不复杂了，如果你本机有安装python的话换一下python的环境变量就可以了。
或者你可以试试conda安装，参考下面的文档:
https://www.paddlepaddle.org.cn/documentation/docs/zh/beginners_guide/install/index_cn.html#conda

**Comment by bytekongfrombupt** [comment]
@zhaoyuchen2018 emmm但是我就是为了方便管理python版本才用的conda，所以我没有在本机安装python，然后我重新conda新建了一个虚拟环境，conda install之后，依然是报错，paddlepaddle部分demo是能运行的，但是刚刚想跑一下ernie的demo，依然提示这个错误

**Comment by zhaoyuchen2018** [comment]
> @zhaoyuchen2018 emmm但是我就是为了方便管理python版本才用的conda，所以我没有在本机安装python，然后我重新conda新建了一个虚拟环境，conda install之后，依然是报错，paddlepaddle部分demo是能运行的，但是刚刚想跑一下ernie的demo，依然提示这个错误

所以现在是paddle安装成功了，也可以运行，但是ernie的demo没办法运行，对吧
