### ISSUE TITLE
Check the possibility of introducing Go to PaddlePaddle

### ISSUE THREAD

**Issue by wangkuiyi** [PaddlePaddle/Paddle#2005]
Go makes programmers highly efficiently.  Here records some surveys and experiments we recently did.

- Building C++/Go hybrid projects:

   https://github.com/gangliao/cmake_cxx_go

- Calling CUDA kernels from Go:

   http://stackoverflow.com/questions/35758750/golang-calling-cuda-library

**Comment by gangliao** [comment]
We already reach this point. The detail can be found in [`cmake/generic.cmake`](https://github.com/PaddlePaddle/Paddle/blob/develop/cmake/generic.cmake)
