### ISSUE TITLE
Feature model inference test fails with mkl-dnn

### ISSUE THREAD

**Issue by ddokupil** [PaddlePaddle/Paddle#20053]
**System information**
-PaddlePaddle version 1.5
-CPU: CLX/MKLDNN version 0.18, 0.19 and 0.20
-OS Platform Ubuntu 16.04
-Python version 2.7.12
-Cmake orders -DCMAKE_BUILD_TYPE=Release -DWITH_GPU=OFF -DWITH_MKLDNN=ON -DWITH_TESTING=ON -DWITH_PROFILER=ON -DWITH_STYLE_CHECK=OFF -DON_INFER=ON -DWITH_INFERENCE_API_TEST=ON
**To Reproduce**
./paddle/fluid/inference/tests/api/test_analyzer_image_classification
--infer_model=<Path to Feature model> --gtest_filter=*compare_mkldnn
**Describe your current behavior**
I0926 13:38:32.002418 47701 analysis_predictor.cc:467] ======= optimize end =======
I0926 13:38:32.004854 47701 tester_helper.h:353] Thread 0, number of threads 1, run 1 times...
E0926 13:38:32.005671 47701 analysis_predictor.cc:323] feed names from program do not have name: [] from specified input
PROFILE: interrupts/evictions/bytes = 136/20/6424
I0926 13:38:33.358453 47701 helper.h:322] ====== threads: 1, thread id: 0 ======
I0926 13:38:33.358496 47701 helper.h:324] ====== batch size: 1, iterations: 1, repetitions: 1 ======
I0926 13:38:33.358501 47701 helper.h:326] ====== batch latency: 1352.88ms, number of samples: 1, sample latency: 1352.88ms, fps: 0.739166, data type: float ======
F0926 13:38:33.372910 47701 tester_helper.h:121] Check failed: std::abs(pdata_ref[j] - pdata[j]) <= FLAGS_accuracy (0.0237388 vs. 0.001)

**Code to reproduce the issue**
**Other info / logs**

**Comment by jczaja** [comment]
Thanks for reporting this problem. I got reproduction on BDW (AVX2 platform). I will investigate that one

**Comment by jczaja** [comment]
Status: Problem seems to be related to FC MKLDNN.

Workaround:
   Add to commandline: `--disable_fc_mkldnn=true`

**Comment by jczaja** [comment]
Root caused was found: FC does support activation operation (currently only relu) and this activation attributure is ignored by FC MKL-DNN. @Sand3r- Is working on FC MKL-DNN INT8 along those changes
there will be support for FC with activations.

**Comment by jczaja** [comment]
@ddokupil  Please check if feature model command line can be stripped off from workaround part "--disable_fc_mkldnn=true"
