### ISSUE TITLE
创建多个 name不同的pyreader时报错

### ISSUE THREAD

**Issue by littlepan0413** [PaddlePaddle/Paddle#20066]
描述：修改了ernie模型，模型中finetune和预测接口都有，在test中先finetune，再predict，两个接口单独测试过没有问题，但是放在同一个文件夹中运行报错，主要是 pyreader创建的问题，
finetune中的两个pyreader
![image](https://user-images.githubusercontent.com/6512760/65814166-eae8f300-e210-11e9-9c8c-8128ec3f1282.png)
预测使用的pyreader（报错）
![image](https://user-images.githubusercontent.com/6512760/65814178-00f6b380-e211-11e9-9395-d6f39ee83bad.png)

查阅 issue，https://github.com/PaddlePaddle/Paddle/issues/16759 三个pyreader_name 已设置不同

报错信息
  File "/home/work/panlu/workspace/baidu/kgx/models/baidu/kgx/models/mt_ernie_classifier.py", line 86, in __init__
    self.__start_model()
  File "/home/work/panlu/workspace/baidu/kgx/models/baidu/kgx/models/mt_ernie_classifier.py", line 104, in __start_model
    ernie_config=self.__ernie_config, tasks_num=self.__tasks_def.tasks_num, is_classify=True)
  File "/home/work/panlu/workspace/baidu/kgx/models/baidu/kgx/models/mt_ernie_utils/finetune/classifier.py", line 46, in create_model
    use_double_buffer=True)
  File "/home/work/anaconda2/envs/paddle_gpu/lib/python2.7/site-packages/paddle/fluid/layers/io.py", line 800, in py_reader
    use_double_buffer=use_double_buffer)
  File "/home/work/anaconda2/envs/paddle_gpu/lib/python2.7/site-packages/paddle/fluid/layers/io.py", line 537, in _py_reader
    feed_queue = core.init_lod_tensor_blocking_queue(var, capacity)
paddle.fluid.core_avx.EnforceNotMet: LoDTensorBlockingQueueHolder::InitOnce() can only be called once at [/paddle/paddle/fluid/operators/reader/lod_tensor_blocking_queue.h:77]
PaddlePaddle Call Stacks:
0       0x7f16ca862e10p void paddle::platform::EnforceNotMet::Init<char const*>(char const*, char const*, int) + 352
1       0x7f16ca863189p paddle::platform::EnforceNotMet::EnforceNotMet(std::__exception_ptr::exception_ptr, char const*, int) + 137
2       0x7f16ca86cc42p paddle::operators::reader::LoDTensorBlockingQueueHolder::InitOnce(unsigned long, bool) + 242
3       0x7f16ca849f3fp
4       0x7f16ca895d36p
5       0x7f1728b6d274p PyEval_EvalFrameEx + 32020
6       0x7f1728b6ea99p PyEval_EvalCodeEx + 2025
7       0x7f1728b6bf68p PyEval_EvalFrameEx + 27144
8       0x7f1728b6ea99p PyEval_EvalCodeEx + 2025
9       0x7f1728b6bf68p PyEval_EvalFrameEx + 27144
10      0x7f1728b6ea99p PyEval_EvalCodeEx + 2025
11      0x7f1728b6bf68p PyEval_EvalFrameEx + 27144
12      0x7f1728b6ea99p PyEval_EvalCodeEx + 2025
13      0x7f1728b6bf68p PyEval_EvalFrameEx + 27144
14      0x7f1728b6ea99p PyEval_EvalCodeEx + 2025
15      0x7f1728af77c7p
16      0x7f1728ad2b73p PyObject_Call + 67
17      0x7f1728ae1a4dp
18      0x7f1728ad2b73p PyObject_Call + 67
19      0x7f1728b2ba84p
20      0x7f1728b2833bp
21      0x7f1728ad2b73p PyObject_Call + 67
22      0x7f1728b69119p PyEval_EvalFrameEx + 15289
23      0x7f1728b6d54ep PyEval_EvalFrameEx + 32750
24      0x7f1728b6d54ep PyEval_EvalFrameEx + 32750
25      0x7f1728b6ea99p PyEval_EvalCodeEx + 2025
26      0x7f1728b6ecbap PyEval_EvalCode + 26
27      0x7f1728b8801dp
28      0x7f1728b891c8p PyRun_FileExFlags + 120
29      0x7f1728b8a3e8p PyRun_SimpleFileExFlags + 232
30      0x7f1728b9c67cp Py_Main + 2988
31      0x7f1727d85b45p __libc_start_main + 245
32      0x7f1728c6e07fp

**Comment by liupluswei** [comment]
从报错上来看比较怀疑还是pyreader_name的原因，可以在paddle源码里面加一行log看看：
1. 通过python -c "import paddle; print(paddle.__file__)" 确认一下paddle的安装路径
2. 在安装路径下面找到${paddle_install_path}\fluid\layers\io.py
3. 在这行代码下面print 一下queue_name: https://github.com/PaddlePaddle/Paddle/blob/c92348c3b927912ba06ba291a0790af1a542dabf/python/paddle/fluid/layers/io.py#L409

如果是一样说明是你的代码可能有些问题，需要你自己排查一下
如果不一样则说明可能是我们的bug，建议你保留一下你的代码，明天上班可以发给我让我看一下具体原因。

**Comment by liupluswei** [comment]
已和用户沟通，是用户代码有误导致接口被调用两次导致
