### ISSUE TITLE
does paddle support data_layer for id?

### ISSUE THREAD

**Issue by jueljust** [PaddlePaddle/Paddle#2007]
id layer will not involved in the calculation, it only used in ouputs for printing the id of predict result
````python
id = data_layer(name="id", size=16)  # id layer , string format, char(16), or varchar(16)
# ... net defination ...
probs = fc_layer(input=lstm_max, size=2, act=SoftmaxActivation())
label = maxid_layer(output)
outputs([id, label, probs])
````

**Comment by lcy-seso** [comment]
If you use old PyData provider, It supports a [String Slot](https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/trainer/PyDataProviderWrapper.py#L138), which is used to carry information to print.

But, it the later version, PaddlePaddle does not support a string slot.

**Comment by qingqing01** [comment]
close since the v2 Python API can print the raw data info when predicting.
