### ISSUE TITLE
单机多卡训练时报有关LD_LIBRARY_PATH的错

### ISSUE THREAD

**Issue by Yiwei98** [PaddlePaddle/Paddle#20089]
尝试进行单机多卡训练时，有报错如下：
![image](https://user-images.githubusercontent.com/44400334/65828553-a2900a80-e2ce-11e9-8278-ca199129dd20.png)
代码片段如下：
![image](https://user-images.githubusercontent.com/44400334/65828558-b3d91700-e2ce-11e9-96e8-0a3c184a5bb6.png)
![image](https://user-images.githubusercontent.com/44400334/65828569-cbb09b00-e2ce-11e9-822a-0e1c66df08f2.png)

**Comment by xjqbest** [comment]
可以先尝试通过export把libnccl.so加入到LD_LIBRARY_PATH
