### ISSUE TITLE
paddle.fluid.core_avx.EnforceNotMet: internal error at [/paddle/paddle/fluid/platform/nccl_helper.h:113]

### ISSUE THREAD

**Issue by Dely-Yu** [PaddlePaddle/Paddle#20085]
代码在本地运行不报错，在集群上运行报错，是什么环境问题引起这种错误？我做了一个对比实验，当训练数据少的时候，不报错。 当加大内存量时，不报错。
这种错误和硬盘空间相关还是和内存相关呢？ 
![image-20190929110528-tsb7c2](https://user-images.githubusercontent.com/29305857/65827762-4e812800-e2c6-11e9-9149-766c18373757.png)

**Comment by Dely-Yu** [comment]
@chengduoZH .请同学解决下。。。

**Comment by chengduoZH** [comment]
@Dely-Yu 好像是NCCL的问题，可以检查一下NCCL的版本等信息。
