### ISSUE TITLE
The example usage is not correct in v2 inference API.

### ISSUE THREAD

**Issue by qingqing01** [PaddlePaddle/Paddle#2008]
The example usage has the argument [batch_size](https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/v2/inference.py#L830) . But this argument is not in `infer` function.
<img width="673" alt="65807b382894b6853ab0596d5" src="https://cloud.githubusercontent.com/assets/7845005/25695830/3cac6024-30e7-11e7-813f-9ae022c9ccb7.png">

**Comment by luotao1** [comment]
I will fix it ASAP
