### ISSUE TITLE
训练时program desc中有fill constant op, 但是实际执行过程中，fill constant op没有被执行到。

### ISSUE THREAD

**Issue by dashulu** [PaddlePaddle/Paddle#20081]
如下配置模型，
![image](https://user-images.githubusercontent.com/4484303/65826671-dada1d80-e2bb-11e9-83be-8f1aed67d119.png)
使用parallel executor进行训练，打印出main program desc，包含了fill_constant_op, 但是在fill_constant_op中加入printf语句，发现没有相应的print输出，即fill_constant_op没有被执行到，请问这个是什么原因？
![image](https://user-images.githubusercontent.com/4484303/65826697-25f43080-e2bc-11e9-93c6-f6eba2563887.png)

**Comment by xjqbest** [comment]
第二个截图这个fill constant是用于反向梯度的，你看有个GRAD。是minimize时候自动添加的。跑的是相应的op的反向，不是前向，你可能是在前向里加的。

**Comment by dashulu** [comment]
> 第二个截图这个fill constant是用于反向梯度的，你看有个GRAD。是minimize时候自动添加的。跑的是相应的op的反向，不是前向，你可能是在前向里加的。
@xjqbest fill_constant op只有一个前向。后面发现没有跑fill_constant_op，而是执行了scale_loss_grad_op_handle, 请问这个是基于什么考虑。

**Comment by chengduoZH** [comment]
@dashulu 你非常细心！
ParallelExecutor里面会将这个fill_constant_op换成scale_loss_grad_op_handle，而这个loss_grad的系数（也就是scale值）与设备数有关，如果是单卡，loss_grad即为1，如果N卡，loss_grad即为1/N。

**Comment by dashulu** [comment]
> @dashulu 你非常细心！
> ParallelExecutor里面会将这个fill_constant_op换成scale_loss_grad_op_handle，而这个loss_grad的系数（也就是scale值）与设备数有关，如果是单卡，loss_grad即为1，如果N卡，loss_grad即为1/N。

@chengduoZH 为什么这么去做？

**Comment by chengduoZH** [comment]
@dashulu 这是为了保证多卡训练时候，参数可以正确更新。
