### ISSUE TITLE
运行ERNIE demo报错segmentation fault

### ISSUE THREAD

**Issue by bytekongfrombupt** [PaddlePaddle/Paddle#20097]
为使您的问题得到快速解决，在建立Issue前，请您先通过如下方式搜索是否有相似问题:【搜索issue关键字】【使用labels筛选】【官方文档】

建立issue时，为快速解决问题，请您根据使用情况给出如下信息：
- 标题：请包含关键词“安装错误”/“编译错误”，例如“Mac编译错误”
- 版本、环境信息：
    1）PaddlePaddle版本：最新
    2）CPU：请提供CPU型号，MKL/OpenBlas/MKLDNN/等数学库的使用情况
    3）GPU：CUDA10.0 CUDNN7.3
    4）系统环境：Linux
- 安装方式信息：
conda install paddlepaddle-gpu cudatoolkit=10.0
![image](https://user-images.githubusercontent.com/33115565/65829994-f22a0280-e2dd-11e9-9071-2ce8528617c7.png)

**Comment by xjqbest** [comment]
请问可以提供运行的脚本和命令，以及报错的堆栈信息么

**Comment by xjqbest** [comment]
can you provide more detailed code and error message
