### ISSUE TITLE
Evaluators are not included in V2 doc.

### ISSUE THREAD

**Issue by lcy-seso** [PaddlePaddle/Paddle#2009]
I find [evaluators](https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/v2/evaluator.py) cannot be found in [V2 API doc](http://www.paddlepaddle.org/develop/doc/api/v2/model_configs.html).  This is inconvenient and not friendly to the users.

**Comment by luotao1** [comment]
I will fix it ASAP.

**Comment by lcy-seso** [comment]
It seems that evaluators cannot be found in V2 API doc again.

**Comment by qingqing01** [comment]
The doc has contained evaluators: 
 http://doc.paddlepaddle.org/develop/doc_cn/api/v2/config/evaluators.html
