### ISSUE TITLE
基于paddlepaddle的翻译模型是否支持预测阶段自定义解码

### ISSUE THREAD

**Issue by dpwu1994** [PaddlePaddle/Paddle#20098]
如题，在paddle v2 版本是尝试过这种做法，但是由于beam_search 无法自定义所以导致预测阶段每次都需要从头开始预测，耗时缓慢，不知道目前的paddlepaddle 版本是否支持自定义解码？

**Comment by dpwu1994** [comment]
https://github.com/PaddlePaddle/models/issues/417 v2版本时提的issue

**Comment by guoshengCS** [comment]
beam_search策略的话在Paddle Fluid中是可以自行实现的，可以参考这里 https://github.com/PaddlePaddle/models/blob/develop/PaddleNLP/unarchived/neural_machine_translation/rnn_search/attention_model.py#L168 。

**Comment by guoshengCS** [comment]
另外目前在做seq2seq api相关的内容，后续beam search策略也可以通过覆盖这里实现 https://github.com/PaddlePaddle/Paddle/pull/19820/files#diff-5ca5a49fa713f2f986b0ba26b778b36aR434

**Comment by dpwu1994** [comment]
看到给的case是经典的NMT model， 不知道transformer 版本的是否也支持？例外咨询下经典的NMT model的beam_size 设置为100 的时候一个query的大概耗时是多少呢？ 如果transformer 版本如果支持beamsearch的话耗时大概是多少？
