### ISSUE TITLE
Fill constant OP的写法重构

### ISSUE THREAD

**Issue by wangchaochaohu** [PaddlePaddle/Paddle#20125]
目前我们可以看到在OP注册的时候我们的 fill_constant是支持如下类型的
![image](https://user-images.githubusercontent.com/13411999/65847169-00762e00-e373-11e9-8553-db6c3a251ccc.png)

但是实现的时候发现任何类型都是可以的，因为我们创建的类型是根据data_type
![image](https://user-images.githubusercontent.com/13411999/65847200-24397400-e373-11e9-9e61-cd41fddf9af8.png)

具体这种写法是否会引起一些bug 还有待调查中

关于这个写法还会有一个很奇怪的现象
我们知道这个函数的API是如下所示 当我们传入的dtype类型和out类型不一致会发生什么现象？
paddle.fluid.layers.fill_constant(shape, dtype, value, force_cpu=False, out=None)

实验结果如下:
![image](https://user-images.githubusercontent.com/13411999/65847668-108f0d00-e375-11e9-9e88-68c902a082e3.png)

也就是说最后的结果是和out 的类型一致的（这个问题应该可以通过类型一致性检查解决 PR https://github.com/PaddlePaddle/Paddle/pull/20075 ）

**Comment by luotao1** [comment]
总结下问题：
1. fill_constant op在注册时只支持float16,float32,float64,int32,int64。但实现的时候任意dtype都可以。具体这种任意dtype是否会引起一些bug，还有待调查中
2. `paddle.fluid.layers.fill_constant(shape, dtype, value, force_cpu=False, out=None)`，dtype和out类型不一样，现在以out类型为准。但可以在#20075 中检查出来。

**Comment by wangchaochaohu** [comment]
我们的代码中python/paddle/fluid/contrib/decoder/beam_search_decoder.py下有如下语句
![image](https://user-images.githubusercontent.com/13411999/65857414-64f6b480-e396-11e9-80cd-80c86dc45826.png)
之前的单测python/paddle/fluid/tests/test_beam_search_decoder.py跑这个是能通过的 


但是自己测试了一下bool类型报错
```
import paddle.fluid as fluid
import numpy as np
out = fluid.layers.data(name='out', shape=[1], dtype= 'bool', append_batch_size=False)
result = fluid.layers.fill_constant(shape=[1], value=0, dtype='bool',   out=out)
exe = fluid.Executor(fluid.CPUPlace())
exe.run(fluid.default_startup_program())
all_result, = exe.run(fetch_list=[result])
print(result)
print(all_result)
```
![image](https://user-images.githubusercontent.com/13411999/65857749-0a118d00-e397-11e9-8e59-b2cee5c71d86.png)

**Comment by wangchaochaohu** [comment]
> 总结下问题：
> 
> 1. fill_constant op在注册时只支持float16,float32,float64,int32,int64。但实现的时候任意dtype都可以。具体这种任意dtype是否会引起一些bug，还有待调查中
> 2. `paddle.fluid.layers.fill_constant(shape, dtype, value, force_cpu=False, out=None)`，dtype和out类型不一样，现在以out类型为准。但可以在#20075 中检查出来。

**Comment by wangchaochaohu** [comment]
首先我们目前的fill_constant 是不支持bool类型的 我刚在https://github.com/PaddlePaddle/Paddle/issues/20125#issuecomment-536438973    里贴了代码  这个代码运行会有错  但是奇怪的是我们以前有的单测里面最后调用 这个fill_constant bool类型没有出错（后续排查应该是OP没有进行compute这个bool的OP并没有进行compute）


然后我修改类型检查的时候遇到了这个调用了fill_constant 的单测的阻挡  我想限制fill_constant 的使用类型但是这个单测使用了bool 类型的fill_constant 所以我CI过不了 应该怎么解决(添加bool类型支持解决）
