### ISSUE TITLE
[MKL-DNN] Add support for fusing FC + activation

### ISSUE THREAD

**Issue by jczaja** [PaddlePaddle/Paddle#20144]
Fully connected of MKL-DNN (inner prod) does support (mkl-dnn 1.0) post operations eg. FC can execute activation as part of FC. This can beenfit some models like: Feature (FC followed by Tanh )
or googlenet.

This issue is to track work on this

**Comment by Sand3r-** [comment]
Implemented by #17641:
https://github.com/PaddlePaddle/Paddle/blob/8fd24021d8ae1bd3807c939258f2124c64928b7c/paddle/fluid/operators/mkldnn/fc_mkldnn_op.cc#L249-L267
