### ISSUE TITLE
多卡训练中关闭batch drop_last无效

### ISSUE THREAD

**Issue by ziyuli** [PaddlePaddle/Paddle#20152]
- 版本、环境信息 
   1）PaddlePaddle版本：1.5.2
    2）CPU：N/A
    3）GPU：8 x TitanX (pascal) CUDA 9.2.88, CUDNN 7.1.4
    4）系统环境：Ubuntu 18.04.2 Python 3.6.7
- 训练信息
    1）单机，多卡
    2）显存信息： 每张卡12GB
   
使用PaddleCV中的resnet50在单机8卡上训练[图形分类](https://github.com/PaddlePaddle/models/tree/develop/PaddleCV/image_classification) ，并尝试将batch drop_last关闭。更改代码如下 `train_reader = paddle.batch(train_reader, batch_size=int(args.batch_size / fluid.core.get_cuda_device_count()), drop_last=False)` 

但实际训练中依旧丢掉了最后一个batch。

在多卡训练下，如果dataset的大小不是batch size的整数倍，是否有其他的办法不drop last ？

**Comment by MRXLT** [comment]
你好，可以尝试用paddle.fluid.layer.batch代替paddle.batch

**Comment by ziyuli** [comment]
使用fluid.layers.batch后报错。错误信息如下：
Traceback (most recent call last):
 File "../train.py", line 318, in <module>
   main()
 File "../train.py", line 313, in main
   train(args)
 File "../train.py", line 206, in train
   batch_size=int(args.batch_size / fluid.core.get_cuda_device_count()))
 File "/usr/local/lib/python3.7/site-packages/paddle/fluid/layers/io.py", line 1063, in batch
   'create_batch_reader', reader, {'batch_size': int(batch_size)})
 File "/usr/local/lib/python3.7/site-packages/paddle/fluid/layers/io.py", line 989, in __create_unshared_decorated_reader__
   attrs=attrs)
 File "/usr/local/lib/python3.7/site-packages/paddle/fluid/framework.py", line 1771, in append_op
   attrs=kwargs.get("attrs", None))
 File "/usr/local/lib/python3.7/site-packages/paddle/fluid/framework.py", line 1118, in __init__
   "not suprt args type , should be[ string_type, binary_type, Varibale]"
ValueError: not suprt args type , should be[ string_type, binary_type, Varibale]

**Comment by MRXLT** [comment]
可以贴一下相关的代码吗

**Comment by ziyuli** [comment]
创建[reader](https://github.com/PaddlePaddle/models/blob/develop/PaddleCV/image_classification/reader.py)的代码与官方提供图形分类的代码一样。
training的部分关键代码如下
```py
train_reader = reader.train(settings=args)
train_reader = paddle.layers.batch(
    train_reader,
    batch_size=int(args.batch_size / fluid.core.get_cuda_device_count()))
train_py_reader.decorate_sample_list_generator(train_reader, place)

for pass_id in range(args.num_epochs):
    train_py_reader.start()
    try:
        while True:
            train_batch_metrics = exe.run(compiled_train_prog, fetch_list=train_fetch_list)
    except fluid.core.EOFException:
        train_py_reader.reset()
```

**Comment by sandyhouse** [comment]
方便贴一下完整的训练代码吗？确认reader没有丢弃部分数据？ 另外你batch size是怎么设置的？
多卡或者多机分布式训练的话推荐使用多进程模式和Fleet API，https://github.com/PaddlePaddle/Fleet/tree/develop/examples 包含一些可供参考的例子。

**Comment by AIpioneer** [comment]
@ziyuli 请问你单卡的时候是否有问题呢？

**Comment by ziyuli** [comment]
理论上reader没有丢弃任何数据。单卡没问题。
完整代码：https://github.com/ziyuli/models/blob/4f11b0f89d1f2a8208fd49b88ff1ca740a5ab762/PaddleCV/image_classification/train.py

**Comment by sandyhouse** [comment]
造成这个现象的原因和batch函数本身无关，batch函数本身并没有丢掉最后的batch。有几种比较简单的处理方法。一种是做图像拼接：填充一部分图像，保证图像数量是总batch size的整数倍。另外一种方法的话是使用多进程模式，即每个卡一个进程的多卡训练方式，我上面的回复给出了一些链接可以参考。

**Comment by chengduoZH** [comment]
@ziyuli 如果在多卡训练时使用py_reader，并且数据集中的batch个数不是卡数的整数倍，则这部分数据会被丢弃。比如数据集中10个batch，你使用的是4卡进行训练，在最后一次迭代时，数据集中只有2个batch，但是因为使用的是4卡训练，因此最后的两个batch会被丢弃。

**Comment by ziyuli** [comment]
所以说如果使用了py_reader我只能将图片补齐到batch的整数倍？没有其他的办法吗？
另外我看到链接里面的例子使用了Fleet API？如果我想用paddle.distributed.launch这种多进程方法网上有例子吗？

**Comment by sandyhouse** [comment]
Fleet API一般也是通过paddle.distributed.launch启动多进程的。所以可以参考上面的例子链接。
