### ISSUE TITLE
Stop printing debug information when calling inferring function

### ISSUE THREAD

**Issue by pkuyym** [PaddlePaddle/Paddle#2015]
Paddle will print debug information when calling inferring function every time.
Debug information shouldn't be printed when doing prediction batch by batch.

For example

> [INFO 2017-05-04 14:43:48,667 networks.py:1472] The input order is [firstw, secondw, thirdw, fourthw]
> [INFO 2017-05-04 14:43:48,668 networks.py:1478] The output order is [__mixed_0__] 

And I have found how to stop the printing action. Just comment line 1472, 1477 and 1478 in file trainer_config_helpers/networks.py

> logger.info("".join(["The input order is [", ", ".join(final_inputs), "]"]))
> logger.info("".join(
>     ["The output order is [", ", ".join(final_outputs), "]"]))

Maybe user can decide whether to print or not.

**Comment by typhoonzero** [comment]
You can add these lines at the beginning of your python code(after the `import` section) to disable the "info" level log:
```python
logger = logging.getLogger('paddle')
logger.setLevel(logging.WARN)
```
