### ISSUE TITLE
Training in multiprocessing.Process falied to run startup program when using GPU

### ISSUE THREAD

**Issue by xueeinstein** [PaddlePaddle/Paddle#20169]
I build a complicate reinforcement learning model in Paddle, with parallel training **two different**  models simultaneously. And one needs to sync the latest weights of another one to generate some target values for training. I implement the second model in `multiprocess.Process`. 

However, the **fresh** forked (no other Paddle program created when fork new process) process failed to run the startup program when using GPU, but success when using CPU.

To make it easy for debug, I reproduce the bug in unit testcases as following:

```python
class TestDynamicsModel(object):
    def test_learner(self):
        self.learner_process()

    def test_learner_process(self):
        process = multiprocessing.Process(target=self.learner_process)
        process.start()
        process.join()
        assert process.exitcode == 0

    def learner_process(self):
        bs = 4
        if machine_info.is_gpu_available():
            place = fluid.CUDAPlace(0)
        else:
            place = fluid.CPUPlace()
        # place = fluid.CPUPlace()
        exe = fluid.Executor(place)

        main, startup = fluid.Program(), fluid.Program()
        with fluid.program_guard(main, startup):
            env = DynamicsModel("env", self.env_config, self.learner_config)
            learner = DynamicsModelLearner(env)
            obs = fluid.layers.data("obs", self.env_config["obs_dims"],
                                    dtype="float32")
            next_obs = fluid.layers.data(
                "next_obs", self.env_config["obs_dims"], dtype="float32")
            actions = fluid.layers.data(
                "actions", [self.env_config["action_dim"]], dtype="float32")
            rewards = fluid.layers.data("rewards", [], dtype="float32")
            dones = fluid.layers.data("dones", [], dtype="bool")
            losses = learner.learn(obs, next_obs, actions, rewards, dones)

        exe.run(startup)
        obs_shape = [bs, *self.env_config["obs_dims"]]
        act_shape = [bs, self.env_config["action_dim"]]
        feed_dict = {
            "obs": np.random.random(obs_shape).astype(np.float32),
            "next_obs": np.random.random(obs_shape).astype(np.float32),
            "actions": np.random.random(act_shape).astype(np.float32),
            "rewards": np.random.random([bs]).astype(np.float32),
            "dones": np.zeros([bs]).astype(bool)
        }
        inspects = exe.run(program=main, feed=feed_dict, fetch_list=losses)
        assert len(inspects) == 4
```

Results:
The testcase `test_learner` passed for running both on CPU and GPU, meaning that the process target function works well.

The testcase `test_learner_process` passed only for running on CPU. When using GPU, it raised an error when init learning rate variable. Check the attachment for details.
[out.txt](https://github.com/PaddlePaddle/Paddle/files/3693903/out.txt)

**Comment by hong19860320** [comment]
> I build a complicate reinforcement learning model in Paddle, with parallel training **two different** models simultaneously. And one needs to sync the latest weights of another one to generate some target values for training. I implement the second model in `multiprocess.Process`.
> 
> However, the **fresh** forked (no other Paddle program created when fork new process) process failed to run the startup program when using GPU, but success when using CPU.
> 
> To make it easy for debug, I duplicate the bug in unit testcases as following:
> 
> ```python
> class TestDynamicsModel(object):
>     def test_learner(self):
>         self.learner_process()
> 
>     def test_learner_process(self):
>         process = multiprocessing.Process(target=self.learner_process)
>         process.start()
>         process.join()
>         assert process.exitcode == 0
> 
>     def learner_process(self):
>         bs = 4
>         if machine_info.is_gpu_available():
>             place = fluid.CUDAPlace(0)
>         else:
>             place = fluid.CPUPlace()
>         # place = fluid.CPUPlace()
>         exe = fluid.Executor(place)
> 
>         main, startup = fluid.Program(), fluid.Program()
>         with fluid.program_guard(main, startup):
>             env = DynamicsModel("env", self.env_config, self.learner_config)
>             learner = DynamicsModelLearner(env)
>             obs = fluid.layers.data("obs", self.env_config["obs_dims"],
>                                     dtype="float32")
>             next_obs = fluid.layers.data(
>                 "next_obs", self.env_config["obs_dims"], dtype="float32")
>             actions = fluid.layers.data(
>                 "actions", [self.env_config["action_dim"]], dtype="float32")
>             rewards = fluid.layers.data("rewards", [], dtype="float32")
>             dones = fluid.layers.data("dones", [], dtype="bool")
>             losses = learner.learn(obs, next_obs, actions, rewards, dones)
> 
>         exe.run(startup)
>         obs_shape = [bs, *self.env_config["obs_dims"]]
>         act_shape = [bs, self.env_config["action_dim"]]
>         feed_dict = {
>             "obs": np.random.random(obs_shape).astype(np.float32),
>             "next_obs": np.random.random(obs_shape).astype(np.float32),
>             "actions": np.random.random(act_shape).astype(np.float32),
>             "rewards": np.random.random([bs]).astype(np.float32),
>             "dones": np.zeros([bs]).astype(bool)
>         }
>         inspects = exe.run(program=main, feed=feed_dict, fetch_list=losses)
>         assert len(inspects) == 4
> ```
> 
> Results:
> The testcase `test_learner` passed for running both on CPU and GPU, meaning that the process target function works well.
> 
> The testcase `test_learner_process` passed only for running on CPU. When using GPU, it raised an error when init learning rate variable. Check the attachment for details.
> [out.txt](https://github.com/PaddlePaddle/Paddle/files/3693903/out.txt)

In order to reproduce the problem, could you plz attach the full code?

**Comment by xueeinstein** [comment]
@hong19860320 A runnable testcase:

```python
# test.py
import pytest
import numpy as np
import multiprocessing
from paddle import fluid

USE_GPU = True

class TestPaddle(object):
    def test_learner(self):
        # pass
        self.learner_process()

    def test_learner_gpu_process(self):
        # failed
        process = multiprocessing.Process(target=self.learner_process)
        process.start()
        process.join()
        assert process.exitcode == 0

    def test_learner_cpu_process(self):
        # pass
        global USE_GPU
        USE_GPU = False
        process = multiprocessing.Process(target=self.learner_process)
        process.start()
        process.join()
        assert process.exitcode == 0

    def learner_process(self):
        bs, in_dim, out_dim = 4, 5, 10
        if USE_GPU and fluid.core.is_compiled_with_cuda():
            place = fluid.CUDAPlace(0)
        else:
            place = fluid.CPUPlace()

        exe = fluid.Executor(place)

        main, startup = fluid.Program(), fluid.Program()
        with fluid.program_guard(main, startup):
            x = fluid.layers.data('x', [in_dim], dtype='float32')
            y_true = fluid.layers.data('y', [out_dim], dtype='float32')
            y_pred = fluid.layers.fc(x, out_dim)
            loss = fluid.layers.reduce_mean(
                fluid.layers.square_error_cost(y_true, y_pred))
            optimizer = fluid.optimizer.AdamOptimizer(learning_rate=1e-3)
            optimizer.minimize(loss)

        exe.run(startup)
        feed_dict = {
            'x': np.random.random([bs, in_dim]).astype(np.float32),
            'y': np.random.random([bs, out_dim]).astype(np.float32)
        }
        inspect = exe.run(program=main, feed=feed_dict, fetch_list=[loss])[0]
        assert inspect.shape == (1,)
```

Execute `py.test -s -vv test.py`, then get output:

[out.txt](https://github.com/PaddlePaddle/Paddle/files/3702724/out.txt)

**Comment by hong19860320** [comment]
I can reproduce the problem, the log is attached as following:
[out.txt](https://github.com/PaddlePaddle/Paddle/files/3706291/out.txt)

**Comment by chengduoZH** [comment]
@xueeinstein Thank you for your feedback, currently, if you use `multiprocessing` in your model, you should move `from paddle import fluid` to your process function, like the following, otherwise, there will have some error.

```
# test.py
import pytest
import numpy as np
import multiprocessing
import os
USE_GPU = True

class TestPaddle(object):
    def _test_learner(self):
        self.learner_process()

    def test_learner_gpu_process(self):
        process = multiprocessing.Process(target=self.learner_process)
        process.start()
        process.join()
        assert process.exitcode == 0

    def test_learner_cpu_process(self):
        global USE_GPU
        USE_GPU = False
        process = multiprocessing.Process(target=self.learner_process)
        process.start()
        process.join()
        assert process.exitcode == 0

    def learner_process(self):
        from paddle import fluid
        bs, in_dim, out_dim = 4, 5, 10
        if USE_GPU and fluid.core.is_compiled_with_cuda():
            place = fluid.CUDAPlace(0)
        else:
            place = fluid.CPUPlace()

        exe = fluid.Executor(place)

        main, startup = fluid.Program(), fluid.Program()
        with fluid.program_guard(main, startup):
            x = fluid.layers.data('x', [in_dim], dtype='float32')
            y_true = fluid.layers.data('y', [out_dim], dtype='float32')
            y_pred = fluid.layers.fc(x, out_dim)
            loss = fluid.layers.reduce_mean(
                fluid.layers.square_error_cost(y_true, y_pred))
            optimizer = fluid.optimizer.AdamOptimizer(learning_rate=1e-3)
            optimizer.minimize(loss)

        exe.run(startup)
        feed_dict = {
            'x': np.random.random([bs, in_dim]).astype(np.float32),
            'y': np.random.random([bs, out_dim]).astype(np.float32)
        }
        inspect = exe.run(program=main, feed=feed_dict, fetch_list=[loss])[0]
        assert inspect.shape == (1,)
```

**Comment by xueeinstein** [comment]
@chengduoZH Thank you for your reply! Your testcases all passed. However, it's quite tricky to disable the first testcase, meaning that you cannot `import paddle` before the subprocess initialized.  

In fact, for our RL model in [PARL](https://github.com/PaddlePaddle/PARL), we have a lot of stuff to create and initialize using Paddle before running the subprocess. Is there any other versatile solution for this issue?

As far as I know, TF and PyTorch can work smoothly in a subprocess without such issue.

**Comment by WorldEditors** [comment]
@chengduoZH this problem has existed for over a month and it is a serious problem in multi-processing usage of Paddle, looking forward to solving it ASAP.

**Comment by gavin1332** [comment]
it is suggested to use `subprocess.Popen` to create subprocess, since `multiprocess.Process` inherits all environments from its parent which may cause duplicated initialization of GPU devices. 
```
import time
import os
import sys 
import subprocess
import numpy as np

USE_GPU = True

def func():
  from paddle import fluid
  bs, in_dim, out_dim = 4, 5, 10
  if USE_GPU and fluid.core.is_compiled_with_cuda():
      place = fluid.CUDAPlace(0)
  else:
      place = fluid.CPUPlace()
  
  exe = fluid.Executor(place)
  
  main, startup = fluid.Program(), fluid.Program()
  with fluid.program_guard(main, startup):
      x = fluid.layers.data('x', [in_dim], dtype='float32')
      y_true = fluid.layers.data('y', [out_dim], dtype='float32')
      y_pred = fluid.layers.fc(x, out_dim)
      loss = fluid.layers.reduce_mean(
          fluid.layers.square_error_cost(y_true, y_pred))
      optimizer = fluid.optimizer.AdamOptimizer(learning_rate=1e-3)
      optimizer.minimize(loss)
  
  exe.run(startup)
  feed_dict = { 
      'x': np.random.random([bs, in_dim]).astype(np.float32),
      'y': np.random.random([bs, out_dim]).astype(np.float32)
  }
  inspect = exe.run(program=main, feed=feed_dict, fetch_list=[loss])[0]
  assert inspect.shape == (1,)

func()

if len(sys.argv) == 1:
  proc = subprocess.Popen([sys.executable, sys.argv[0], 'again'],
                   env=os.environ.copy(),
                   stdout=sys.stdout,
                   stderr=sys.stderr)
  while proc.poll() is None:
    pass

  assert proc.poll() == 0
```

**Comment by xueeinstein** [comment]
@gavin1332 Thank you for your suggestion and code example. In our project, two **different models** are trained via two processes, and use a handy`multiprocessing.Manager()` to control sync and async training.  For simplicity, the provided testcase removes this communication pipeline.  

Anyway, `subprocess.Popen` is a better solution. But I have to rewrite the communication pipeline using `Popen.communicate()` etc. It may take some time.  I'll feedback soon.

**Comment by WorldEditors** [comment]
> it is suggested to use `subprocess.Popen` to create subprocess, since `multiprocess.Process` inherits all environments from its parent which may cause duplicated initialization of GPU devices.

This seems more like a temporary solution, and the bug is left unsolved. "subprocess" is less commonly used compared with "multiprocess". Also "subprocess" has great difficulty in communication between processes.  We are looking forward to fixing this bug.

**Comment by sneaxiy** [comment]
We are dedicated to solve this issue. Please have a wait.

**Comment by sneaxiy** [comment]
@xueeinstein It seems that it is a bug of CUDA. PyTorch has also the same issue (see https://pytorch.org/docs/stable/notes/multiprocessing.html#cuda-in-multiprocessing). Run the following codes using PyTorch 1.1 in CUDA 9.0:
```Python
import multiprocess
import torch

def torch_one_tensor(shape):
    return torch.ones(*shape, device='cuda')

print('CUDA device count: {}'.format(torch.cuda.device_count()))

p = multiprocess.Process(target=torch_one_tensor, args=([3, 4, 5], ))
p.start()
p.join()

assert p.exitcode == 0
```

No matter `import multiprocess` is before `import torch` or not, the error still raises:
```
THCudaCheck FAIL file=/opt/conda/conda-bld/pytorch_1556653000816/work/aten/src/THC/THCGeneral.cpp line=55 error=3 : initialization error
Process Process-1:
Traceback (most recent call last):
  File "/root/miniconda2/envs/pytorch/lib/python2.7/site-packages/multiprocess/process.py", line 267, in _bootstrap
    self.run()
  File "/root/miniconda2/envs/pytorch/lib/python2.7/site-packages/multiprocess/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "test_pytorch_fork.py", line 5, in torch_one_tensor
    return torch.ones(*shape, device='cuda')
  File "/root/miniconda2/envs/pytorch/lib/python2.7/site-packages/torch/cuda/__init__.py", line 163, in _lazy_init
    torch._C._cuda_init()
RuntimeError: cuda runtime error (3) : initialization error at /opt/conda/conda-bld/pytorch_1556653000816/work/aten/src/THC/THCGeneral.cpp:55
Traceback (most recent call last):
  File "test_pytorch_fork.py", line 13, in <module>
    assert p.exitcode == 0
AssertionError
```

We also check that whether it is the problem of CUDA or deep learning framework. But the results indicates that it is the bug of CUDA. CUDA cannot work well when using `fork`. See the pure C++ cuda codes below.

```C++
#include <sys/types.h>
#include <unistd.h>
#include <iostream>
#include <exception>
#include <stdexcept>
#include "cuda.h"
#include "cuda_runtime.h"

#define CUDA_CHECK(cond)  \
  do { \
    auto __cond__ = (cond); \
    if (__cond__ != cudaSuccess) {  \
      throw std::runtime_error("CUDA error " + std::to_string(getpid()) + ": " + std::to_string(int(__cond__)));  \
    } \
  } while (0)

int main()
{
  int dev_cnt;
  CUDA_CHECK(cudaGetDeviceCount(&dev_cnt));
  std::cout << "Device number " << dev_cnt << std::endl;
  std::cout << "Pid of parent is " << getpid() << std::endl;

  auto pid = fork();
  if (pid == 0) {
    std::cout << "Pid of child is " << getpid() << std::endl;
    CUDA_CHECK(cudaSetDevice(0));
  } else {
    CUDA_CHECK(cudaSetDevice(0));
  }

  return 0;
}
```

You can compile the codes above using `nvcc` (the command is `nvcc test_cuda_fork.cu -o test_cuda_fork -std=c++11 && ./test_cuda_fork`, here we suppose that the source file name is `test_cuda_fork.cu`), and exception would be raised too.
```
Device number 8
Pid of parent is 10917
Pid of child is 10919
terminate called after throwing an instance of 'std::runtime_error'
  what():  CUDA error 10919: 3
```

**Comment by xueeinstein** [comment]
@sneaxiy Thank you for your feedback! As you cited, https://pytorch.org/docs/stable/notes/multiprocessing.html#cuda-in-multiprocessing, you should test Pytorch with python3, **not python2.7**.  All my testcases use python 3.6.

Moreover, I wonder if there is a typo `multiprocessing` instead of `multiprocess`. Because `multiprocess` is another third-part [implementation](https://github.com/uqfoundation/multiprocess). 

Actually, I'm trying to rewrite [this TensorFlow model](https://github.com/tensorflow/models/tree/master/research/steve) using Paddle. They implement some complicate parallel training of two different models using `multiprocessing`.

**Comment by sneaxiy** [comment]
@xueeinstein I am sorry that `multiprocess` is a typo. Actually I am using `multiprocessing` to test the codes above. I also try to use PyTorch with Python 3.6 with the same code, but error still raises. This is not the bug of PyTorch or Paddle, but the bug of CUDA when forking. I would try to use the suggestions in PyTorch and test whether it works in Paddle.

**Comment by sneaxiy** [comment]
@xueeinstein Please try the following codes.  Paddle works well too after calling `multiprocessing.set_start_method('spawn')`. I am testing on Python 3.6. PyTorch would fail if not setting 'spawn' for multiprocessing module.

Moreover, `multiprocessing.set_start_method('spawn')` must be called inside `if __name__ == '__main__'` directly or indirectly. See the relative issue in PyTorch https://github.com/pytorch/pytorch/issues/3492 .

```Python
import multiprocessing

USE_TORCH = False

def set_start_method(method):
    multiprocessing.set_start_method(method)

if USE_TORCH:
    import torch

    def create_one_tensor(shape):
        value = torch.ones(*shape, device='cuda', dtype=torch.float32)
        print(value.cpu().numpy())

    def cuda_device_count():
        return torch.cuda.device_count()
else:
    import paddle.fluid as fluid 
    import paddle.fluid.core as core

    def create_one_tensor(shape): 
        ones = fluid.layers.ones(shape=shape, dtype='float32')
        place = fluid.CUDAPlace(0) 
        exe = fluid.Executor(place)
        value = exe.run(fluid.default_main_program(), fetch_list=[ones])[0]
        print(value)

    def cuda_device_count():
        return core.get_cuda_device_count()


def test_main():
    print('CUDA device number {}'.format(cuda_device_count()))
    p = multiprocessing.Process(target=create_one_tensor, args=([3, 4, 5], ))
    p.start()
    p.join()
    assert p.exitcode == 0

'''
set_start_method() must be called inside "if __name__ == '__main__':"
Otherwise, errors would be raised by multiprocessing module.  
'''

if __name__ == '__main__':
    set_start_method('spawn')
    test_main()
```

**Comment by sneaxiy** [comment]
@xueeinstein https://github.com/PaddlePaddle/Paddle/issues/20169#issuecomment-539525206 In this codes above, after the following revision:

```Python
    def test_learner_gpu_process(self):
        multiprocessing.set_start_method('spawn')
        process = multiprocessing.Process(target=self.learner_process)
        process.start()
        process.join()
        assert process.exitcode == 0
```

Paddle would work well too.
