### ISSUE TITLE
热启动训练进程不能恢复

### ISSUE THREAD

**Issue by mensaochun** [PaddlePaddle/Paddle#20188]
**问题：**
在使用分布式arcface loss(paddle.fluid.layers.dist_algo._distributed_arcface_classify)训练的时候，出现了热启动不能恢复训练状态的问题。具体细节如下：
**环境：**
paddle版本：git commit id：0d9538064d9f7bbe006692267db8a2691b760bad
通过fluid.io.save_persistables保存模型之前的loss：
![image](https://user-images.githubusercontent.com/20737237/66363772-f333f180-e9b9-11e9-9594-ef48d52881db.png)
继续运行的loss：
![image](https://user-images.githubusercontent.com/20737237/66363811-165ea100-e9ba-11e9-8158-52d359f0c6d5.png)

通过fluid.io.load_vars恢复之后：
![image](https://user-images.githubusercontent.com/20737237/66363698-b36d0a00-e9b9-11e9-9ad6-b9a715b9e148.png)

对比可知，重新加载进来之后loss差别很大。

这个问题已经和paddle同学沟通过，他们复现了这个问题，同时，在softmax loss上也复现了这个问题，所以这个可能是一个普遍问题，但他们还没有找到原因。这个问题对目前的训练影响很大，望尽快解决。

**Comment by seiriosPlus** [comment]
是使用transpiler模式训练的么？

**Comment by mensaochun** [comment]
> 是使用transpiler模式训练的么？

是的。

**Comment by seiriosPlus** [comment]
transpile的使用相关的代码发一下？

**Comment by sandyhouse** [comment]
已定位，热启动无法回复的原因是reader中没有使用设置seed，导致各个trainer的文件列表是不一致的，进而导致热启动时使用的文件列表和模型保存前的文件列表不一致，出现未训练过的数据。

**Comment by sandyhouse** [comment]
Closing this issue. Reopen it if you have any further question.
