### ISSUE TITLE
Get parameter name and size from Parameter.get_shape()

### ISSUE THREAD

**Issue by pengwangucla** [PaddlePaddle/Paddle#2018]
Want to check parameter shape from parameters, using parameter name and get_shape.

However, the convolutional shape is :
```

flow_up_block1 (1, 1056768)

_flow_up_block1.wbias (128, 1)
```

First, is it possible to make the parameter name consistent ? set .w and .b for weight and bias

Is it better to make the size explicit readable ?   such as input filter  x output filter x kernel height x kernel width ? 

@helinwang  who is in charge of paddle v2 api ?

**Comment by lcy-seso** [comment]
I agree that it is better if the parameter name consistent, in the old version, by default,  .w and .b are for weight and bias separately.

**Comment by lcy-seso** [comment]
This problem has been fixed, so I close this issue.
