### ISSUE TITLE
missing subsequence layer

### ISSUE THREAD

**Issue by CrossLee1** [PaddlePaddle/Paddle#2026]
Given a long sequence, a start position and an end position, I want to use a "subsequence" layer to crop a subsequence within it, but did not find such a layer.
However, in older version, I find it:
Layer(
    name = "sub_out_seq",
    type = "subseq",
    bias = False,
    inputs = ["out_seq", "offset", "size"],
)

Is the new version Paddle support this layer?

**Comment by qingqing01** [comment]
closed, since the `sub_seq` is fixed and exposed in  https://github.com/PaddlePaddle/Paddle/pull/5388 .
