### ISSUE TITLE
连续多次调用save_inference_model保存模型，第二次和第三次保存的模型错误，导致预测失败

### ISSUE THREAD

**Issue by sshilei** [PaddlePaddle/Paddle#20299]
![image](https://user-images.githubusercontent.com/18701471/66462069-e643fa80-eaac-11e9-9dae-7eb6bba3009c.png)

连续三次保存模型，每次的输入和输出不同。但是后面两次保存的模型在预测时出错，没有按输出对输入和算子进行prune。

感谢平烁帮忙跟进及定位问题。

**Comment by mapingshuo** [comment]
你连续三次调用了save_inference_model这个函数：

在第一次调用时，函数在main_program中，cos_sim_0.tmp_0后面添加了scale op, 这一op输出了一个新的var，称作“save_infer_model/scale_0”; 

![image](https://user-images.githubusercontent.com/23031310/66489555-620c6a00-eae2-11e9-8adb-8b0163c7f9fe.png)

第二次调用时，函数在main_program中，fc_0.tmp_2后面又添加了一个scale_op，这一op的输出也是“save_infer_model/scale_0”

![image](https://user-images.githubusercontent.com/23031310/66489526-59b42f00-eae2-11e9-83f2-df0bed4a9c2d.png)

裁剪时用户希望以fc_0.tmp_2(即net_output['model_output']['query'])作为target, 按照save_inference_model的逻辑，即以“save_infer_model/scale_0”做为target。由于“save_infer_model/scale_0”是多个op的输出，所以裁剪时也保留了与cos_sim_0.tmp_0相关的var与op，与预期不符。

**Comment by Superjomn** [comment]
save_inference_model 我们正在重构，目前最好，每次都从训练的program clone 下，从全新的program开始prune

建议训练中 save_persistable 存储学到的参数，训练完离线用 save_inference_model 一次性转化下program

**Comment by mapingshuo** [comment]
> save_inference_model 我们正在重构，目前最好，每次都从训练的program clone 下，从全新的program开始prune
> 
> 建议训练中 save_persistable 存储学到的参数，训练完离线用 save_inference_model 一次性转化下program

已经建议用户在save_inference_model前做clone了，并且已经解决了用户问题。

既然在重构，那等你们的消息吧 :)
