### ISSUE TITLE
Request support for nce operator preserving lod information when using LodTensors as inputs and labels

### ISSUE THREAD

**Issue by Meleeri** [PaddlePaddle/Paddle#20305]
At present paddle erases lod information of outputs when using nce operator with LodTensors as inputs and labels. This is very annoying since I'm trying to use nce_loss to implement a language model where are inputs are lodtensors, and it would be nice to have nce_loss as a drop-in replacement of softmax_cross_entropy_loss without modifing much code.

**Comment by JepsonWong** [comment]
nce op do not support lod currently.
