### ISSUE TITLE
Need to report uninitialized error when paddle.init() is not called

### ISSUE THREAD

**Issue by emailweixu** [PaddlePaddle/Paddle#2031]
Currently if paddle.init() is not called in the beginning, there can be some strange errors not understandable by the user (e.g. #1971 ). We should explicitly check whether paddle.init() is called and report a sensible error message.

**Comment by xinghai-sun** [comment]
Yes. I also encountered the same problem and it wasted me a lot of time.

**Comment by hedaoyuan** [comment]
I think we can add a global flag that is paddle initialized. And increase the judgment that has been initialized before some operation.

**Comment by typhoonzero** [comment]
Close due to low activity, please feel free to reopen it.
