### ISSUE TITLE
Document arguments for paddle.v2.init()

### ISSUE THREAD

**Issue by emailweixu** [PaddlePaddle/Paddle#2032]
Currently, init() accepts dictionary arguments **kwargs, which does not tell what exactly is accepted.
User should be able to see how to use paddle.v2.init() by using 'help(paddle.v2.init)

**Comment by luotao1** [comment]
The document of arguments is writing in #1940 .

**Comment by dzhwinter** [comment]
The PR has been merged, close this issue. Please reopen it if there is any new activity.
