### ISSUE TITLE
第三方库转paddle 

### ISSUE THREAD

**Issue by leesunfreshing** [PaddlePaddle/Paddle#20433]
Hi，目前我用pytorch和第三方库pytorch geometric训练好的模型，由于paddle缺乏相关操作，在用onnx转的时候无法成功。pytorch geometric是专门支持Graph Neural Network的库，依赖于pytorc。链接：https://pytorch-geometric.readthedocs.io/en/latest/。若paddle没有计划扩展PGL对应与pytorch geometric，能否提供支持接口直接调用？后再转模型时提供便利？

**Comment by xyoungli** [comment]
请问转paddle出的什么错误？
