### ISSUE TITLE
一个模型预测的问题

### ISSUE THREAD

**Issue by xiuechen** [PaddlePaddle/Paddle#20432]
在python当中，预测输入是一个二维数组，每个样本input={{0},{0},{0},...{0}},一共有15维schema
在C++该如何构造tensor呢？

无论我怎么写，都报：wrong feed input size, need 15 but get 1

试过输入数组，展开成一维，然后：

tensor.shape={15,1}
tensor.lod={{0,15},{0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15}}

报错。

也试过，输入数组是std::vector<std::vector<uint64_t>> featuremap
tensor.shape={1,1,1,1,1,1,1,1,1,1...1}

同样报错。

**Comment by xyoungli** [comment]
输入是tensor array吗？输入的个数应该是15个，而传递的tensor array的size只有1

**Comment by xiuechen** [comment]
确实是，多谢。
