### ISSUE TITLE
多机任务训练中，pserver节点出错，停止

### ISSUE THREAD

**Issue by wuhaijun2018** [PaddlePaddle/Paddle#20504]
- 版本、环境信息：
    1）PaddlePaddle版本：fluid 1.51
- 训练信息
    1）多机

- 复现信息：多次多机运行，可重复出现
- 问题描述：
![image](https://user-images.githubusercontent.com/37178931/66635128-191ef780-ec41-11e9-8ae5-b99cd6341cd6.png)

**Comment by gentelyang** [comment]
麻烦提交一下复现代码~

**Comment by MrChengmo** [comment]
日志可以贴全一些，看起来是sparse参数在fetch时出现的维度问题。
