### ISSUE TITLE
Make `paddle::Function` as plain Functions

### ISSUE THREAD

**Issue by reyoung** [PaddlePaddle/Paddle#2050]
### Motivations

In the [`function` package](https://github.com/PaddlePaddle/Paddle/tree/develop/paddle/function), class `FunctionBase` is the base class of `Layer` and `Projection`. Indeed, this design is not mandatory. We'd make replace class `FunctionBase` by `std::function`.  An advantage of this change is that we can use Layers and Projections as they are C++ functions:

```cpp
typedef std::function<Error(Tensors& inputs, Tensors& outputs)> CUDAKernel;
CUDAKernel softmax = KernelRegisters.get("softmax");
softmax(ins, outs);
```

Also, we can use `std::bind` to bind the value of some parameters, like we do with functions defined in `std`:

```cpp
Error CosineKernel(Tensors& ins, Tensors& outs, double scale) {
  ...
}

KernelType cos = KernelRegister.get("cos", scale=3.0);
cos(ins, outs);
```

### Actions Items

1. Change the use of class`Function` in layer definitions into`std::function<Error(Tensors& inputs, Tensors& outputs)>`:
   1. Decouple package `function` and `layer`.
   1. Define the conversion from `FunctionBase` to `CUDAKernel`.
   1. Above has been done in #2049.

1. Rewrite class `Register` in package `function`.

**Comment by emailweixu** [comment]
Need to explain why we need to use Layers as functions to have better motivation of this issue.
