### ISSUE TITLE
@LR_DECAY_COUNTER@的值不正确

### ISSUE THREAD

**Issue by nepeplwu** [PaddlePaddle/Paddle#20560]
PaddlePaddle版本：1.5.2

训练模型的时候，使用fluid.layers.piecewise_decay进行lr的decay，发现在训练过程中，完全一样的代码，@LR_DECAY_COUNTER@在每个Epoch训练结束后，有时候会自增1，有时候不会，如下：
![44ED43AC97909093ED5648288F8136FC](https://user-images.githubusercontent.com/45024560/66694198-82574700-ece3-11e9-8fbf-c11fe1395156.JPG)
![F671487D395A277F0430538A4FBC6D4F](https://user-images.githubusercontent.com/45024560/66694200-84210a80-ece3-11e9-9642-40bbe8601521.JPG)

**Comment by MyPandaShaoxiang** [comment]
是分布式训练的么

**Comment by nepeplwu** [comment]
不是，单机单卡训练

**Comment by tink2123** [comment]
请问这个问题是随机出现的吗？每次都是从头开始训练的吗？

**Comment by nepeplwu** [comment]
随机出现的，每次都是从头开始训练，一旦出现该问题的话，从第一个Epoch就会有问题，不会有训练到一半才出现的情况
