### ISSUE TITLE
网络权值共享

### ISSUE THREAD

**Issue by yanyq1990** [PaddlePaddle/Paddle#20575]
- 版本、环境信息：
    1）PaddlePaddle版本：1.5.2.post107
    2）CPU/GPU：Driver API Version: 10.1, Runtime API Version: 10.0，cuDNN Version: 7.6.
    3）系统环境：ubuntu16.04
    4）Python版本号 2.7.12
 
我采用fluid.unique_name.guard来设置网络变量的名称，并用visualdl显示模型结构:
1. 当左右设置不同名称时，代码如下：
```python
with fluid.unique_name.guard('stem-l/'):
    conv1a, conv2a, conv_temp4a, up_1a2a = self.stem_block(view_l)
with fluid.unique_name.guard('stem-r/'):
    conv1b, conv2b, conv_temp4b, up_1b2b = self.stem_block(view_r)
conc = fluid.layers.concat([up_1a2a, up_1b2b], axis=1)
x = conv2d(conc, num_filters=1, filter_size=3, stride=1, padding=1)
return x
```
所显示的模型结构如下:
![graph](https://user-images.githubusercontent.com/22705112/66697129-551b9080-ed05-11e9-8488-3ffb31be27a8.png)

2. 当左右设置一样的名称时，代码如下：
```python
with fluid.unique_name.guard('stem/'):
    conv1a, conv2a, conv_temp4a, up_1a2a = self.stem_block(view_l)
with fluid.unique_name.guard('stem/'):
    conv1b, conv2b, conv_temp4b, up_1b2b = self.stem_block(view_r)
conc = fluid.layers.concat([up_1a2a, up_1b2b], axis=1)
x = conv2d(conc, num_filters=1, filter_size=3, stride=1, padding=1)
return x
```
所显示的模型结构如下:
![share-graph](https://user-images.githubusercontent.com/22705112/66697351-65cd0600-ed07-11e9-871d-079acfdaec44.png)

两种写法打印出conc的shape都是一样的，要实现共享，fluid.unique_name.guard的用法是否正确？这个问题是paddle的bug还是我的用法不对？

**Comment by MyPandaShaoxiang** [comment]
请问你具体是要实现怎样的共享呢

**Comment by yanyq1990** [comment]
> 请问你具体是要实现怎样的共享呢

我的网络是做stereo match的，输入左右两张图片，分别经过conv2d_0和conv2d_4，左右两边在stem的网络中对应的参数共享的，就跟tensorflow里面的reuse一样，最后分别在leaky_relu_7和leaky_relu_15输出，concat连接起来，正常情况下模型结构应该是第1种的，但是第一种左右的参数名是不一样的，而第2种写法，左右参数名一致，但是visualdl显示的结构不对

**Comment by MyPandaShaoxiang** [comment]
你好，第二种基本用法是没有问题的，但在这里可能会和你的需求不太一致。因为unique_name.guard会保证里面的所有名字都一样，所以有可能会出现2中的情况。建议如果想要参数共享，你可以手动对参数进行命名，这样会更安全的实现参数共享；在使用2的用法时，最好让最后一层名字不同，这样会实现1中的效果。

**Comment by yanyq1990** [comment]
已解决，多谢
![graph (1)](https://user-images.githubusercontent.com/22705112/66700258-23b0be00-ed21-11e9-9e67-27ff0ed6fff8.png)
模型结构正确并且两个子网络的参数是共享的
