### ISSUE TITLE
[V2 interface] Missing 'is_evaluator' attributes for the exported evaluators

### ISSUE THREAD

**Issue by wanglovesyang** [PaddlePaddle/Paddle#2057]
Running the one-line script of 
     assert hasattr(paddle.evaluator.classification_error, 'is_evaluator')
fails the assertion.

According to the code, without the attribute of 'is_evaluator', the evaluator cannot be appened to the cost layer.

**Comment by lcy-seso** [comment]
close this issue due to inactivity.
