### ISSUE TITLE
2卡训练无问题，＞2卡报错 cudaStreamSynchronize on illegal memory access errno:77

### ISSUE THREAD

**Issue by OleNet** [PaddlePaddle/Paddle#20588]
![image](https://user-images.githubusercontent.com/3206718/66702101-69c44c80-ed36-11e9-93b9-6b56e944616e.png)

**Comment by OleNet** [comment]
![image](https://user-images.githubusercontent.com/3206718/66702108-95dfcd80-ed36-11e9-8067-4254a823f1b7.png)

**Comment by OleNet** [comment]
528行出错

**Comment by sandyhouse** [comment]
有可复现代码吗 @OleNet

**Comment by sandyhouse** [comment]
多卡训练建议使用多进程模式，可以规避这个问题。

**Comment by emy-085** [comment]
> 多卡训练建议使用多进程模式，可以规避这个问题。

遇到了同样的问题。请问什么是多进程模式？怎样开启？

**Comment by sandyhouse** [comment]
简单的说多进程模式是每个卡一个训练进程，可以类比于分布式训练，一般通过paddle.distributed.lanch启动，可参考https://www.paddlepaddle.org.cn/documentation/docs/zh/user_guides/howto/training/multi_node.html

**Comment by emy-085** [comment]
> 简单的说多进程模式是每个卡一个训练进程，可以类比于分布式训练，一般通过paddle.distributed.lanch启动，可参考https://www.paddlepaddle.org.cn/documentation/docs/zh/user_guides/howto/training/multi_node.html

单机多卡可以用这个模式训练吗？还是必须要多机训练？

**Comment by sandyhouse** [comment]
单机多卡就可以。 @emy-085
