### ISSUE TITLE
a bug~

### ISSUE THREAD

**Issue by wangsouc** [PaddlePaddle/Paddle#2060]
https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/trainer/PyDataProvider2.py

**assert len(each, input_type.dim)**
```
    @staticmethod
    def loop_callback(input_type, each):
        assert isinstance(input_type, InputType)
        if input_type.type == DataType.Dense:
            assert isinstance(each, collections.Sequence)
            for d in each:
                assert isinstance(d, float)
            assert len(each, input_type.dim)
```

**Comment by typhoonzero** [comment]
The error was: 
<img width="826" alt="83b93d2217a5bbaa99b969cec" src="https://cloud.githubusercontent.com/assets/13348433/25832445/299aeb22-349d-11e7-84c3-c6c617936c0f.png">
