### ISSUE TITLE
和pytorch对比，paddle要训练到相同的效果，需要更多的epoch

### ISSUE THREAD

**Issue by Exception-star** [PaddlePaddle/Paddle#20610]
- 版本、环境信息：
    1）PaddlePaddle版本：1.5.2.
    2）GPU：k40
    
- 模型信息
    1）模型名称  DANet
    2）使用数据集名称 Cityscapes

- 问题描述：
      网络结构：两个框架的网络结构已对应，层数，卷积核大小，步长，pad，采样率，BN层的参数设置，初始化方式等都一样。
      数据输入：数据的增强方式都是一样的。
      网络的超参数：优化器都是adam, 学习率一样，正则化系数一致
      
      但是，用paddle要训练到和pytorch相同的效果，需要更多的epoch，需要2倍，甚至更多。
      重复了5，6次都是这个结果。

**Comment by zhupengyang** [comment]
建议尝试逐层对比结果，看是否在某一层上paddle和pytorch有明显不对齐的情况

**Comment by zhupengyang** [comment]
DANet模型需要内部评估下，看后续是否要支持下
