### ISSUE TITLE
What is the difference between Projection and Layer?

### ISSUE THREAD

**Issue by wangkuiyi** [PaddlePaddle/Paddle#2063]
In [pacakge `layer`](https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/gserver/layers/), there are two class hierarchies:

1. one derived from class `Projection`, and
1. another one derived from [class `Layer`](https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/gserver/layers/Layer.h)

What's their relationship?

It seems that usually, a hierarchy should be defined a dedicated package. Should we move the hierarchy based at `Projection` to another package named `projection`?

**Comment by hedaoyuan** [comment]
我觉得没有什么特别的区别，之前有个ISSUE，可以考虑想办法去掉 #1165 .
