### ISSUE TITLE
py_reader返回数据的顺序

### ISSUE THREAD

**Issue by dashulu** [PaddlePaddle/Paddle#20650]
假设py_reader传入一个reader函数返回的数据依次是1，2，3，4。
那在实际训练时，是先传入数据1训练，再传入数据2，再3，以此类推吗？
我用paddle/model的resnet50训练时，好像不是这样的（已经把shuffle选项关了）。

**Comment by willthefrog** [comment]
是这样的。不过可能会根据GPU卡数对传入的数据作partition。请具体描述不符合预期的现象。

**Comment by dashulu** [comment]
@willthefrog 我的训练数据集是：
![image](https://user-images.githubusercontent.com/4484303/66972095-0e8fb280-f0c6-11e9-8128-c4ab2af8743c.png)， 传入py_reader的reader是顺序去读取这些数据,但是实际训练时发现，数据并没有按照第一个样本，第2个样本这样子依次训练。我使用的batch size是4
