### ISSUE TITLE
PaddlePaddle的模型有几种类型？

### ISSUE THREAD

**Issue by TingquanGao** [PaddlePaddle/Paddle#20674]
PaddlePaddle模型类型受训练集影响吗？
比如，我使用coco数据集（json类型）训练，和我使用xml格式的数据集训练，最后得到的模型一样吗？

我自己用xml格式的数据集训练得到的模型如下：
![image](https://user-images.githubusercontent.com/12560511/66918389-d8185000-f051-11e9-9515-a64efea4365b.png)

下载的官方模型如下：
![image](https://user-images.githubusercontent.com/12560511/66918428-ec5c4d00-f051-11e9-8d8f-7ac58b208a11.png)

观察两种模型文件的命名规律，有明显不同，并且加载方式也不一样。请问两种类型的模型，有何区别呢？

**Comment by LielinJiang** [comment]
coco官方的数据集就是json格式的，xml格式的数据是从哪来的，是coco吗？还有训练的模型是paddle detection吗

**Comment by TingquanGao** [comment]
> coco官方的数据集就是json格式的，xml格式的数据是从哪来的，是coco吗？还有训练的模型是paddle detection吗

xml格式的数据集是我们自己的。我们也有json格式的数据集。这两种不同类型的数据集训练出来的模型文件，并不一样，就像上面的截图，是吗？如果是，那这两种不同的模型，有什么区别呢，可以互相转换吗？谢谢！

**Comment by LielinJiang** [comment]
> > coco官方的数据集就是json格式的，xml格式的数据是从哪来的，是coco吗？还有训练的模型是paddle detection吗
> 
> xml格式的数据集是我们自己的。我们也有json格式的数据集。这两种不同类型的数据集训练出来的模型文件，并不一样，就像上面的截图，是吗？如果是，那这两种不同的模型，有什么区别呢，可以互相转换吗？谢谢！

模型的类型和用的数据集无关。你用的是哪里的代码？

**Comment by LielinJiang** [comment]
> > coco官方的数据集就是json格式的，xml格式的数据是从哪来的，是coco吗？还有训练的模型是paddle detection吗
> 
> xml格式的数据集是我们自己的。我们也有json格式的数据集。这两种不同类型的数据集训练出来的模型文件，并不一样，就像上面的截图，是吗？如果是，那这两种不同的模型，有什么区别呢，可以互相转换吗？谢谢！

模型的类型和用的数据集无关。你用的是哪里的代码？

**Comment by TingquanGao** [comment]
> > > coco官方的数据集就是json格式的，xml格式的数据是从哪来的，是coco吗？还有训练的模型是paddle detection吗
> > 
> > 
> > xml格式的数据集是我们自己的。我们也有json格式的数据集。这两种不同类型的数据集训练出来的模型文件，并不一样，就像上面的截图，是吗？如果是，那这两种不同的模型，有什么区别呢，可以互相转换吗？谢谢！
> 
> 模型的类型和用的数据集无关。你用的是哪里的代码？

我们参照的代码是这里的：https://aistudio.baidu.com/aistudio/projectdetail/135289
数据集是我们自己标注的，格式是voc的xml。
训练出来的模型文件是这样的：
![image](https://user-images.githubusercontent.com/12560511/66922885-80caad80-f05a-11e9-8163-6060842572eb.png)

我们训练出来的模型类型，和你们官方给的yolov3的模型类型不同。想知道是怎么回事？谢谢！

**Comment by LielinJiang** [comment]
> > > > coco官方的数据集就是json格式的，xml格式的数据是从哪来的，是coco吗？还有训练的模型是paddle detection吗
> > > 
> > > 
> > > xml格式的数据集是我们自己的。我们也有json格式的数据集。这两种不同类型的数据集训练出来的模型文件，并不一样，就像上面的截图，是吗？如果是，那这两种不同的模型，有什么区别呢，可以互相转换吗？谢谢！
> > 
> > 
> > 模型的类型和用的数据集无关。你用的是哪里的代码？
> 
> 我们参照的代码是这里的：https://aistudio.baidu.com/aistudio/projectdetail/135289
> 数据集是我们自己标注的，格式是voc的xml。
> 训练出来的模型文件是这样的：
> ![image](https://user-images.githubusercontent.com/12560511/66922885-80caad80-f05a-11e9-8163-6060842572eb.png)
> 
> 我们训练出来的模型类型，和你们官方给的yolov3的模型类型不同。想知道是怎么回事？谢谢！

你使用的代码是？有可能是代码不同

**Comment by LielinJiang** [comment]
> > > > coco官方的数据集就是json格式的，xml格式的数据是从哪来的，是coco吗？还有训练的模型是paddle detection吗
> > > 
> > > 
> > > xml格式的数据集是我们自己的。我们也有json格式的数据集。这两种不同类型的数据集训练出来的模型文件，并不一样，就像上面的截图，是吗？如果是，那这两种不同的模型，有什么区别呢，可以互相转换吗？谢谢！
> > 
> > 
> > 模型的类型和用的数据集无关。你用的是哪里的代码？
> 
> 我们参照的代码是这里的：https://aistudio.baidu.com/aistudio/projectdetail/135289
> 数据集是我们自己标注的，格式是voc的xml。
> 训练出来的模型文件是这样的：
> ![image](https://user-images.githubusercontent.com/12560511/66922885-80caad80-f05a-11e9-8163-6060842572eb.png)
> 
> 我们训练出来的模型类型，和你们官方给的yolov3的模型类型不同。想知道是怎么回事？谢谢！

哦哦，这个应该是代码不同，官方给的yolov3模型是https://github.com/PaddlePaddle/models/tree/develop/PaddleCV/PaddleDetection 这里的代码训练出来的。

**Comment by TingquanGao** [comment]
> > > > > coco官方的数据集就是json格式的，xml格式的数据是从哪来的，是coco吗？还有训练的模型是paddle detection吗
> > > > 
> > > > 
> > > > xml格式的数据集是我们自己的。我们也有json格式的数据集。这两种不同类型的数据集训练出来的模型文件，并不一样，就像上面的截图，是吗？如果是，那这两种不同的模型，有什么区别呢，可以互相转换吗？谢谢！
> > > 
> > > 
> > > 模型的类型和用的数据集无关。你用的是哪里的代码？
> > 
> > 
> > 我们参照的代码是这里的：https://aistudio.baidu.com/aistudio/projectdetail/135289
> > 数据集是我们自己标注的，格式是voc的xml。
> > 训练出来的模型文件是这样的：
> > ![image](https://user-images.githubusercontent.com/12560511/66922885-80caad80-f05a-11e9-8163-6060842572eb.png)
> > 我们训练出来的模型类型，和你们官方给的yolov3的模型类型不同。想知道是怎么回事？谢谢！
> 
> 你使用的代码是？有可能是代码不同



> > > > > coco官方的数据集就是json格式的，xml格式的数据是从哪来的，是coco吗？还有训练的模型是paddle detection吗
> > > > 
> > > > 
> > > > xml格式的数据集是我们自己的。我们也有json格式的数据集。这两种不同类型的数据集训练出来的模型文件，并不一样，就像上面的截图，是吗？如果是，那这两种不同的模型，有什么区别呢，可以互相转换吗？谢谢！
> > > 
> > > 
> > > 模型的类型和用的数据集无关。你用的是哪里的代码？
> > 
> > 
> > 我们参照的代码是这里的：https://aistudio.baidu.com/aistudio/projectdetail/135289
> > 数据集是我们自己标注的，格式是voc的xml。
> > 训练出来的模型文件是这样的：
> > ![image](https://user-images.githubusercontent.com/12560511/66922885-80caad80-f05a-11e9-8163-6060842572eb.png)
> > 我们训练出来的模型类型，和你们官方给的yolov3的模型类型不同。想知道是怎么回事？谢谢！
> 
> 哦哦，这个应该是代码不同，官方给的yolov3模型是https://github.com/PaddlePaddle/models/tree/develop/PaddleCV/PaddleDetection 这里的代码训练出来的。

具体是哪里的代码不同呢？是调用的paddle保存模型的接口不同吗？
那这两种类型的模型，有什么区别呢？可以相互转换吗？

**Comment by LielinJiang** [comment]
和保存的接口没什么关系，从你们保存的模型的形式来看，调用的保存模型接口应该是一致的。这两种模型的不同具体要看你们使用的模型结构以及参数的命名，以及数据集的类别。这些都有关系。如果模型结构和数据集的类别相同，理论上是可以互相转换的。需要将你们的代码和官方的代码的参数命名映射起来。
