### ISSUE TITLE
An example to show how to run image classification based on v2 API on cluster

### ISSUE THREAD

**Issue by qingqing01** [PaddlePaddle/Paddle#2070]
这个例子是希望告诉大家如何在集群上训练大规模图像分类，当前基于MPI集群，数据基于ImageNet，集群上的数据打batch适合一些，所以建议对数据打batch。通过集群的例子，重点希望优化的是v2 API图像分类的性能，需要评估下，可能需要优化的是数据IO那块。

另外，希望通过这个例子和[PaddlePaddle/models里图像分类的例子](https://github.com/PaddlePaddle/models/issues/28)对图像预处理这块的代码形成一个比较规范的模块，当前`python/paddle/utils/image_util.py` 和 `python/paddle/utils/image_multiproc.py` 是基于DataProvider的，一些操作也不是很犯规，希望通过这两个例子，把图像预处理一些通用的操作形成规范的代码，方便用户使用。

**Comment by lcy-seso** [comment]
我们是不是也需要对 V2 API 做一些性能回归测试呢？已经有一些关于训练/测试速度变慢的问题出现。

速度一直是PaddlePaddle 的优势，性能下降，对一些需要将已经训练得非常稳定的 V1 任务切换到 V2 的用户，会带来影响。

**Comment by lcy-seso** [comment]
This has been done.
