### ISSUE TITLE
查了好像是一個minibatch 的尺寸不可變 但把batch 設成1 也一樣

### ISSUE THREAD

**Issue by AIpioneer** [PaddlePaddle/Paddle#20719]
![image](https://user-images.githubusercontent.com/50724968/67076156-2dbe3b00-f1bf-11e9-9fa5-a1c6f479e3ff.png)

![image](https://user-images.githubusercontent.com/50724968/67076165-3151c200-f1bf-11e9-9434-2e1a136ac54d.png)
 
thanks

**Comment by luotao1** [comment]
请问是要做变长输入的训练么？下面的示例是否是你想要的？https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/user_guides/howto/prepare_data/feeding_data.html#batchsize
![image](https://user-images.githubusercontent.com/6836917/67085138-dc1eac00-f1d0-11e9-938b-46d4d74f37cf.png)

**Comment by stanchan123** [comment]
我的項目人流密度估計，input 及predict 均為圖片，設定佔位符
```
images=fluid.layers.data(name='images',shape= [3,-1,-1],append_batch_size=False,dtype='float32')
label=fluid.layers.data(name='label',shape=label_size=[1,-1,-1],append_batch_size=False,dtype='float32')
```
把images 輸入到x = fluid.layers.conv2d(input=images, num_filters=64, filter_size=3, padding=1, act='relu') 後出錯


結果出現異常:
```
   3596         for each in shape:
   3597             if each < 0:
-> 3598                 raise ValueError("Parameter shape should not be related with "
   3599                                  "batch-size")
   3600 
ValueError: Parameter shape should not be related with batch-size
```

**Comment by stanchan123** [comment]
BATCH_SIZE= 1     #每次取1张
# 设置训练reader
train_reader = paddle.batch(
    paddle.reader.shuffle(
        train_set(), buf_size=1),
    batch_size=BATCH_SIZE)

# 定义数据生成器
def train_set():
    def reader():
        for index in range(len(part_A_img[0])): #遍历所有图片
            ....
            yield ig_im,groundtruth
    return reader

**Comment by luotao1** [comment]
> 我的項目人流密度估計，input 及predict 均為圖片

请问图片的尺寸是一直在变的么？

**Comment by stanchan123** [comment]
輸入的每張圖片的尺寸都不一樣

Tao Luo <notifications@github.com> 於 2019年10月18日 星期五寫道：

**Comment by luotao1** [comment]
变长输入可以参考下 https://github.com/PaddlePaddle/models/issues/1885 和 https://github.com/PaddlePaddle/models/issues/1776
