### ISSUE TITLE
单机多卡预训练ernie1.0出现 SendRPC name:[NCCLID], ep:[10.12.35.45:6171], status:[-1] meets grpc error, error_code:4 error_message:Deadline Exceeded error_details:

### ISSUE THREAD

**Issue by zuole** [PaddlePaddle/Paddle#20725]
- 版本、环境信息：
    1）PaddlePaddle版本：1.5.1
    3）GPU： Tesla V100 
    4）系统环境：Linux，Python2.7版本
- 训练信息
    1）单机，多卡
    2）显存信息  16160MiB
    3）Operator信息 Linux 

- 问题描述：请详细描述您的问题，同步贴出报错信息、日志、可复现的代码片段

[INFO] 2019-10-18 19:25:08,789 [    train.py:  210]:    Device count 2
[INFO] 2019-10-18 19:25:08,789 [    train.py:  211]:    theoretical memory usage: 
[INFO] 2019-10-18 19:25:08,833 [    train.py:  213]:    (9526.169296073915, 9979.796405410767, 'MB')
[INFO] 2019-10-18 19:25:08,833 [    train.py:  217]:    args.is_distributed: True
[INFO] 2019-10-18 19:25:08,834 [    train.py:  225]:    train_id == 0, sleep 60s
[INFO] 2019-10-18 19:26:08,894 [    train.py:  229]:    worker_endpoints:[u'10.12.35.45:6170', u'10.12.35.45:6171'] trainers_num:2 current_endpoint:10.12.35.45:6170               trainer_id:0
W1018 19:26:10.103168 119202 device_context.cc:259] Please NOTE: device: 0, CUDA Capability: 70, Driver API Version: 9.2, Runtime API Version: 9.0
W1018 19:26:10.106727 119202 device_context.cc:267] device: 0, cuDNN Version: 7.0.
W1018 19:26:10.106756 119202 device_context.cc:293] WARNING: device: 0. The installed Paddle is compiled with CUDNN 7.3, but CUDNN version in your machine is 7.0, which may cause serious incompatible bug. Please recompile or reinstall Paddle with compatible CUDNN version.
I1018 19:26:10.428246 119202 rpc_client.h:101] init rpc client with trainer_id 0
F1018 19:29:10.429860 119306 grpc_client.cc:414] SendRPC name:[NCCLID], ep:[10.12.35.45:6171], status:[-1] meets grpc error, error_code:4 error_message:Deadline Exceeded error_details:
*** Check failure stack trace: ***
    @     0x7f515d89127d  google::LogMessage::Fail()
    @     0x7f515d894d2c  google::LogMessage::SendToLog()
    @     0x7f515d890da3  google::LogMessage::Flush()
    @     0x7f515d89623e  google::LogMessageFatal::~LogMessageFatal()
    @     0x7f515f1620da  paddle::operators::distributed::GRPCClient::Proceed()
    @     0x7f5182a6b8a0  execute_native_thread_routine
    @     0x7f519367b1c3  start_thread
    @     0x7f5192ca312d  __clone
    @              (nil)  (unknown)

**Comment by gongweibao** [comment]
你看一下卡一的日志是什么。贴一下卡1的日志。

**Comment by zuole** [comment]
log0的日志，只有sleep 60s
 ./log/job.log.0
[INFO] 2019-10-21 09:55:30,128 [    train.py:  164]:    pretraining start
[INFO] 2019-10-21 09:55:30,128 [ ernie_v1.py:   51]:    attention_probs_dropout_prob: 0.1
[INFO] 2019-10-21 09:55:30,128 [ ernie_v1.py:   51]:    hidden_act: relu
[INFO] 2019-10-21 09:55:30,128 [ ernie_v1.py:   51]:    hidden_dropout_prob: 0.1
[INFO] 2019-10-21 09:55:30,128 [ ernie_v1.py:   51]:    hidden_size: 768
[INFO] 2019-10-21 09:55:30,128 [ ernie_v1.py:   51]:    initializer_range: 0.02
[INFO] 2019-10-21 09:55:30,128 [ ernie_v1.py:   51]:    max_position_embeddings: 513
[INFO] 2019-10-21 09:55:30,128 [ ernie_v1.py:   51]:    num_attention_heads: 12
[INFO] 2019-10-21 09:55:30,128 [ ernie_v1.py:   51]:    num_hidden_layers: 12
[INFO] 2019-10-21 09:55:30,128 [ ernie_v1.py:   51]:    type_vocab_size: 2
[INFO] 2019-10-21 09:55:30,128 [ ernie_v1.py:   51]:    vocab_size: 18000
[INFO] 2019-10-21 09:55:30,128 [ ernie_v1.py:   52]:    ------------------------------------------------
[INFO] 2019-10-21 09:55:32,772 [    train.py:  210]:    Device count 2
[INFO] 2019-10-21 09:55:32,773 [    train.py:  211]:    theoretical memory usage: 
[INFO] 2019-10-21 09:55:32,814 [    train.py:  213]:    (47274.12795009613, 49525.27690010071, 'MB')
[INFO] 2019-10-21 09:55:32,815 [    train.py:  217]:    args.is_distributed: True
[INFO] 2019-10-21 09:55:32,815 [    train.py:  225]:    train_id == 0, sleep 60s


log1的日志
 ./log/job.log.1
[INFO] 2019-10-21 09:55:30,152 [     args.py:   66]:    -----------  Configuration Arguments -----------
[INFO] 2019-10-21 09:55:30,153 [     args.py:   68]:    batch_size: 8192
[INFO] 2019-10-21 09:55:30,153 [     args.py:   68]:    checkpoints: ./checkpoints
[INFO] 2019-10-21 09:55:30,153 [     args.py:   68]:    decr_every_n_nan_or_inf: 2
[INFO] 2019-10-21 09:55:30,153 [     args.py:   68]:    decr_ratio: 0.8
[INFO] 2019-10-21 09:55:30,153 [     args.py:   68]:    do_test: False
[INFO] 2019-10-21 09:55:30,153 [     args.py:   68]:    epoch: 100
[INFO] 2019-10-21 09:55:30,153 [     args.py:   68]:    ernie_config_path: ./config/ernie_config.json
[INFO] 2019-10-21 09:55:30,153 [     args.py:   68]:    generate_neg_sample: False
[INFO] 2019-10-21 09:55:30,153 [     args.py:   68]:    in_tokens: True
[INFO] 2019-10-21 09:55:30,153 [     args.py:   68]:    incr_every_n_steps: 100
[INFO] 2019-10-21 09:55:30,153 [     args.py:   68]:    incr_ratio: 2.0
[INFO] 2019-10-21 09:55:30,153 [     args.py:   68]:    init_checkpoint: None
[INFO] 2019-10-21 09:55:30,153 [     args.py:   68]:    init_loss_scaling: 102400
[INFO] 2019-10-21 09:55:30,153 [     args.py:   68]:    is_distributed: True
[INFO] 2019-10-21 09:55:30,153 [     args.py:   68]:    learning_rate: 0.0001
[INFO] 2019-10-21 09:55:30,153 [     args.py:   68]:    lr_scheduler: linear_warmup_decay
[INFO] 2019-10-21 09:55:30,153 [     args.py:   68]:    max_seq_len: 512
[INFO] 2019-10-21 09:55:30,153 [     args.py:   68]:    num_train_steps: 1000000
[INFO] 2019-10-21 09:55:30,153 [     args.py:   68]:    save_steps: 10000
[INFO] 2019-10-21 09:55:30,153 [     args.py:   68]:    skip_steps: 10
[INFO] 2019-10-21 09:55:30,153 [     args.py:   68]:    test_filelist: 
[INFO] 2019-10-21 09:55:30,153 [     args.py:   68]:    train_filelist: ./data/train_filelist
[INFO] 2019-10-21 09:55:30,153 [     args.py:   68]:    use_cuda: True
[INFO] 2019-10-21 09:55:30,153 [     args.py:   68]:    use_dynamic_loss_scaling: True
[INFO] 2019-10-21 09:55:30,154 [     args.py:   68]:    use_fast_executor: True
[INFO] 2019-10-21 09:55:30,154 [     args.py:   68]:    use_fp16: False
[INFO] 2019-10-21 09:55:30,154 [     args.py:   68]:    valid_filelist: ./data/valid_filelist
[INFO] 2019-10-21 09:55:30,154 [     args.py:   68]:    validation_steps: 100
[INFO] 2019-10-21 09:55:30,154 [     args.py:   68]:    verbose: False
[INFO] 2019-10-21 09:55:30,154 [     args.py:   68]:    vocab_path: ./config/vocab.txt
[INFO] 2019-10-21 09:55:30,154 [     args.py:   68]:    warmup_steps: 5000
[INFO] 2019-10-21 09:55:30,154 [     args.py:   68]:    weight_decay: 0.01
[INFO] 2019-10-21 09:55:30,154 [     args.py:   68]:    weight_sharing: True
[INFO] 2019-10-21 09:55:30,154 [     args.py:   69]:    ------------------------------------------------
[INFO] 2019-10-21 09:55:30,154 [    train.py:  164]:    pretraining start
[INFO] 2019-10-21 09:55:30,154 [ ernie_v1.py:   51]:    attention_probs_dropout_prob: 0.1
[INFO] 2019-10-21 09:55:30,154 [ ernie_v1.py:   51]:    hidden_act: relu
[INFO] 2019-10-21 09:55:30,154 [ ernie_v1.py:   51]:    hidden_dropout_prob: 0.1
[INFO] 2019-10-21 09:55:30,154 [ ernie_v1.py:   51]:    hidden_size: 768
[INFO] 2019-10-21 09:55:30,154 [ ernie_v1.py:   51]:    initializer_range: 0.02
[INFO] 2019-10-21 09:55:30,154 [ ernie_v1.py:   51]:    max_position_embeddings: 513
[INFO] 2019-10-21 09:55:30,154 [ ernie_v1.py:   51]:    num_attention_heads: 12
[INFO] 2019-10-21 09:55:30,154 [ ernie_v1.py:   51]:    num_hidden_layers: 12
[INFO] 2019-10-21 09:55:30,154 [ ernie_v1.py:   51]:    type_vocab_size: 2
[INFO] 2019-10-21 09:55:30,155 [ ernie_v1.py:   51]:    vocab_size: 18000
[INFO] 2019-10-21 09:55:30,155 [ ernie_v1.py:   52]:    ------------------------------------------------
[INFO] 2019-10-21 09:55:32,825 [    train.py:  210]:    Device count 2
[INFO] 2019-10-21 09:55:32,825 [    train.py:  211]:    theoretical memory usage: 
[INFO] 2019-10-21 09:55:32,867 [    train.py:  213]:    (47274.12795009613, 49525.27690010071, 'MB')
[INFO] 2019-10-21 09:55:32,867 [    train.py:  217]:    args.is_distributed: True
[INFO] 2019-10-21 09:55:32,867 [    train.py:  229]:    worker_endpoints:[u'10.12.35.45:6170', u'10.12.35.45:6171'] trainers_num:2 current_endpoint:10.12.35.45:6171               trainer_id:1
W1021 09:55:36.249538 71888 device_context.cc:259] Please NOTE: device: 1, CUDA Capability: 70, Driver API Version: 9.2, Runtime API Version: 9.0
W1021 09:55:36.253706 71888 device_context.cc:267] device: 1, cuDNN Version: 7.0.
W1021 09:55:36.253736 71888 device_context.cc:293] WARNING: device: 1. The installed Paddle is compiled with CUDNN 7.3, but CUDNN version in your machine is 7.0, which may cause serious incompatible bug. Please recompile or reinstall Paddle with compatible CUDNN version.


看不到特别明显的报错，过了60s之后，log会出现标题的错误

**Comment by gongweibao** [comment]
1. 设置export GLOG_v=10
2. 然后把卡0，卡1的详细日志Hi上发给我。

**Comment by gongweibao** [comment]
检查一下是否有代理?
```
echo $http_proxy
echo $https_proxy
```
