### ISSUE TITLE
文档C++ 预测 API的例子编译后，运行报错：段错误（核心已转储）

### ISSUE THREAD

**Issue by zuokanmingyuli** [PaddlePaddle/Paddle#20724]
-环境信息
```
    1）PaddlePaddle版本：1.5.2.post107
    2）CPU：-
    3）GPU：notebook GTX 1060、CUDA 10.0、CUDNN 7.5.1
    4）系统环境：ubuntu 18.04，Python 3.6.8
```
 -预测信息
    1）C++预测：预测库安装包的版本信息 cuda10.0_cudnn7_avx_mkl，其中的version.txt文件:
```
GIT COMMIT ID: a5696153a013552bfaa612ca407eba318e18ba54
WITH_MKL: ON
WITH_MKLDNN: ON
WITH_GPU: ON
CUDA version: 10.0
CUDNN version: v7
```
    2）CMake包含路径的完整命令:
```
INCLUDE_DIRECTORIES(/home/xxx/paddle_cpp/src/include)
target_link_libraries(paddle_NativePredictor 
/home/xxx/paddle_cpp/src/lib/libpaddle_fluid.so
/home/xxx/paddle_cpp/src/third_party/install/mkldnn/lib/libmkldnn.so.0
/home/xxx/paddle_cpp/src/third_party/install/mklml/lib/libmklml_intel.so
     ) 
```
    3）预测库来源：官网下载
 - 复现信息：
         文档 - C++ 预测 API介绍（https://www.paddlepaddle.org.cn/documentation/docs/zh/advanced_usage/deploy/inference/native_infer.html ） 中的前两个使用样例报错。
         我将文档 - 'C++ 预测 API介绍 - NativePredictor使用样例' 的例子代码放在一个paddle_NativePredictor.cpp中，没有改动，然后写好CMakeLists.txt如上所述，然后编译，未报错，运行可执行程序报错：段错误（核心已转储）
         同样的方法，将代码换成了文档 - 'C++ 预测 API介绍 - AnalysisPredictor 使用样例' ，也是基本是报同样的错。

 - 问题描述：
         C++ 预测 API介绍 - NativePredictor使用样例就是编译好之后报错：段错误（核心已转储），gdb信息如下：
```
Temporary breakpoint 1, main ()
    at /home/abc/paddle_cpp/src/paddle_NativePredictor.cpp:54
54	int main() { 
(gdb) n
56	  paddle::RunNative(1, "./mobilenet");
(gdb) 
Program received signal SIGSEGV, Segmentation fault.
0x00007fffe018319f in std::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string(std::string const&) ()
   from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
(gdb) 
Single stepping until exit from function _ZNSsC2ERKSs,
which has no line number information.
```
第二个例子“AnalysisPredictor使用样例”也报错，同样的方法，仅仅将cpp里的代码换成了文档 - 'C++ 预测 API介绍 - AnalysisPredictor 使用样例' ，报错error: ‘accumulate’ is not a member of ‘std’，于是我在这段代码开头加上了“ #include <numeric>  ”，之后报错如下：
```
CMakeFiles/paddle_NativePredictor.dir/paddle_NativePredictor.cpp.o：在函数‘paddle::CreateConfig(paddle::AnalysisConfig*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)’中：
/home/abc/paddle_cpp2/src/paddle_NativePredictor.cpp:7：对‘paddle::AnalysisConfig::SetModel(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)’未定义的引用
collect2: error: ld returned 1 exit status
CMakeFiles/paddle_NativePredictor.dir/build.make:86: recipe for target 'paddle_NativePredictor' failed
make[2]: *** [paddle_NativePredictor] Error 1
CMakeFiles/Makefile2:72: recipe for target 'CMakeFiles/paddle_NativePredictor.dir/all' failed
make[1]: *** [CMakeFiles/paddle_NativePredictor.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
```
我将代码改写如下：
```
#include "paddle_inference_api.h"
#include <numeric>  
int main() { 
  paddle::AnalysisConfig config;

  int batch_size = 1;
  std::string model_dirname = "./mobilenet";

  config.SetModel(model_dirname);
  config.EnableUseGpu(1000, 0);

  config.SwitchUseFeedFetchOps(false);
  config.SwitchSpecifyInputNames(true);
  // config.SwitchIrDebug(true);

  auto predictor = CreatePaddlePredictor(config);

  return 0;
}

```
编译好之后执行报错：段错误 (核心已转储)
gdb信息如下：
```
64	int main() { 
(gdb) n
66	  paddle::AnalysisConfig config;
(gdb) 
68	  int batch_size = 1;
(gdb) 
69	  std::string model_dirname = "./mobilenet";
(gdb) 
71	  config.SetModel(model_dirname);
(gdb) 
72	  config.EnableUseGpu(10, 0 );
(gdb) 

Program received signal SIGSEGV, Segmentation fault.
__memmove_avx_unaligned_erms ()
    at ../sysdeps/x86_64/multiarch/memmove-vec-unaligned-erms.S:249
249	../sysdeps/x86_64/multiarch/memmove-vec-unaligned-erms.S: 没有那个文件或目录.

```

**Comment by luotao1** [comment]
请问你运行的是哪个文档里的例子，可以把链接贴出来么

**Comment by zuokanmingyuli** [comment]
不好意思没说清楚，链接：
[https://www.paddlepaddle.org.cn/documentation/docs/zh/advanced_usage/deploy/inference/native_infer.html](url)
我运行的是这个页面里的“NativePredictor 使用样例”和“AnalysisPredictor使用样例”

**Comment by zuokanmingyuli** [comment]
不好意思没说清楚，链接：
https://www.paddlepaddle.org.cn/documentation/docs/zh/advanced_usage/deploy/inference/native_infer.html
我运行的是这个页面里的“NativePredictor 使用样例”和“AnalysisPredictor使用样例”

**Comment by luotao1** [comment]
1. 描述部分的格式能否调整下，代码部分用代码格式，方便阅读。
2. 请问模型有下载么？
```
// 模型下载地址 http://paddle-inference-dist.cdn.bcebos.com/tensorrt_test/mobilenet.tar.gz
  paddle::RunNative(1, "./mobilenet");
```

**Comment by zuokanmingyuli** [comment]
@luotao1 
格式调整过来了，模型下载了，目录如下：
root:src
+--build
+--include
+--paddle_NativePredictor.cpp
+--mobilenet
+--third_party
+--lib
+--CMakeLists.txt

**Comment by luotao1** [comment]
可以把你的`paddle_NativePredictor.cpp`和`CMakeLists.txt`两份文件直接上传一下么？

**Comment by zuokanmingyuli** [comment]
好的好的，NativePredictor 使用样例我的文件如下：
paddle_NativePredictor.cpp：
```
#include "paddle_inference_api.h"

namespace paddle {
// 配置NativeConfig
void CreateConfig(NativeConfig *config, const std::string& model_dirname) {
  config->use_gpu=true;
  config->device=0;
  config->fraction_of_gpu_memory=0.1;
  
  /* for cpu
  config->use_gpu=false;
  config->SetCpuMathLibraryNumThreads(1);
  */
  
  // 设置模型的参数路径
  config->prog_file = model_dirname + "model";
  config->param_file = model_dirname + "params";
  // 当模型输入是多个的时候，这个配置是必要的。
  config->specify_input_name = true;
}

void RunNative(int batch_size, const std::string& model_dirname) {
  // 1. 创建NativeConfig
  NativeConfig config;
  CreateConfig(&config, model_dirname);
  
  // 2. 根据config 创建predictor
  auto predictor = CreatePaddlePredictor(config);
  
  int channels = 3;
  int height = 224;
  int width = 224;
  float *data = new float[batch_size * channels * height * width];

  // 3. 创建输入 tensor 
  PaddleTensor tensor;
  tensor.name = "image";
  tensor.shape = std::vector<int>({batch_size, channels, height, width});
  tensor.data = PaddleBuf(static_cast<void *>(data),
                          sizeof(float) * (batch_size * channels * height * width));
  tensor.dtype = PaddleDType::FLOAT32;
  std::vector<PaddleTensor> paddle_tensor_feeds(1, tensor);

  // 4. 创建输出 tensor
  std::vector<PaddleTensor> outputs;
  // 5. 预测
  predictor->Run(paddle_tensor_feeds, &outputs, batch_size);

  const size_t num_elements = outputs.front().data.length() / sizeof(float);
  auto *data_out = static_cast<float *>(outputs.front().data.data());
}
}  // namespace paddle

int main() { 
  // 模型下载地址 http://paddle-inference-dist.cdn.bcebos.com/tensorrt_test/mobilenet.tar.gz
  paddle::RunNative(1, "./mobilenet");
  return 0;
}
```
CMakeLists.txt
```
cmake_minimum_required(VERSION 2.6)

SET(CMAKE_BUILD_TYPE "Debug")
SET(CMAKE_CXX_FLAGS_DEBUG "$ENV{CXXFLAGS} -O0 -Wall -g2 -ggdb")
SET(CMAKE_CXX_FLAGS_RELEASE "$ENV{CXXFLAGS} -O3 -Wall")

# 这句说明了这是要用use_lib.cpp编译成可执行文件，并定义可执行文件的名字
ADD_EXECUTABLE(paddle_NativePredictor paddle_NativePredictor.cpp)

# 包含目录，调用库文件就要包含该库的头文件
INCLUDE_DIRECTORIES(include)

# 库，使用动态库或静态库都是一样的写法
target_link_libraries(paddle_NativePredictor #可执行文件名 
/home/abc/paddle_cpp/src/lib/libpaddle_fluid.so
/home/abc/paddle_cpp/src/third_party/install/mkldnn/lib/libmkldnn.so.0
/home/abc/paddle_cpp/src/third_party/install/mklml/lib/libmklml_intel.so
     ) 

```

**Comment by zuokanmingyuli** [comment]
对于“AnalysisPredictor使用样例”，我将paddle_NativePredictor.cpp中的代码改写如下，其他都没变
```
#include "paddle_inference_api.h"
#include <numeric>  
int main() { 
  paddle::AnalysisConfig config;

  int batch_size = 1;
  std::string model_dirname = "./mobilenet";

  config.SetModel(model_dirname);
  config.EnableUseGpu(1000, 0);

  config.SwitchUseFeedFetchOps(false);
  config.SwitchSpecifyInputNames(true);
  // config.SwitchIrDebug(true);

  auto predictor = CreatePaddlePredictor(config);

  return 0;
}
```

**Comment by zuokanmingyuli** [comment]
@luotao1
好的好的，对于“NativePredictor 使用样例”和“AnalysisPredictor使用样例”，我的文件分别是paddle_cpp.zip和paddle_cpp2.zip，其中CMakeLists.txt路径改一下，然后把下载的include、lib、third_party、mobilenet放进src文件夹，就跟我的一样了。
[paddle_cpp.zip](https://github.com/PaddlePaddle/Paddle/files/3746843/paddle_cpp.zip)
[paddle_cpp2.zip](https://github.com/PaddlePaddle/Paddle/files/3746844/paddle_cpp2.zip)

**Comment by luotao1** [comment]
`/home/abc/paddle_cpp2/src/paddle_NativePredictor.cpp:7：对‘paddle::AnalysisConfig::SetModel(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)’未定义的引用
collect2: error: ld returned 1 exit status`这个是缺少了C++ 11的特性。需要加`set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++11")`试下。

**Comment by zuokanmingyuli** [comment]
...还是报一样的错呀，我把那一句放进了CMakeLists.txt，如下
[CMakeLists.txt](https://github.com/PaddlePaddle/Paddle/files/3747671/CMakeLists.txt)

**Comment by luotao1** [comment]
https://www.paddlepaddle.org.cn/documentation/docs/zh/advanced_usage/deploy/inference/native_infer.html
![image](https://user-images.githubusercontent.com/6836917/67184244-ed0c2f00-f415-11e9-9068-066896808054.png)
![image](https://user-images.githubusercontent.com/6836917/67184257-f2697980-f415-11e9-8260-1832ac67d2a8.png)
我们已经更新了1.6版本的文档，并把完整的示例上传了，您可以下载示例试下。

**Comment by zuokanmingyuli** [comment]
@luotao1 非常不好意思，
我试了下用之前的库和新的打包好的示例，仍然会报错：
`[100%] Linking CXX executable mobilenet_test
CMakeFiles/mobilenet_test.dir/mobilenet_test.o：在函数‘paddle::PrepareTRTConfig(paddle::AnalysisConfig*, int)’中：
/home/abc/paddle_inference_sample_v1.6/sample/inference/mobilenet_test.cc:24：对‘paddle::AnalysisConfig::SetModel(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)’未定义的引用
CMakeFiles/mobilenet_test.dir/mobilenet_test.o：在函数‘__static_initialization_and_destruction_0(int, int)’中：
/home/abc/paddle_inference_sample_v1.6/sample/inference/mobilenet_test.cc:12：对‘google::FlagRegisterer::FlagRegisterer<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >(char const*, char const*, char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*)’未定义的引用
collect2: error: ld returned 1 exit status
CMakeFiles/mobilenet_test.dir/build.make:91: recipe for target 'mobilenet_test' failed
make[2]: *** [mobilenet_test] Error 1
CMakeFiles/Makefile2:72: recipe for target 'CMakeFiles/mobilenet_test.dir/all' failed
make[1]: *** [CMakeFiles/mobilenet_test.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
run_impl.sh: 26: run_impl.sh: ./mobilenet_test: not found
`
使用新提供的预测库（ubuntu14.04_cuda10.0_cudnn7_avx_mkl和ubuntu14.04_cuda10.0_cudnn7_avx_mkl_trt5），会报错找不到第三方库snappystream，我看预测库里确实没有，另外，预测库ubuntu14.04_cuda10.0_cudnn7_avx_mkl_trt5压缩包的fluid_inference/paddle/lib这个目录下是空的，我也没有再去下载一遍确认。
我试了一下安装1.6版本的paddle，但是没有成功，我准备试试自己编译预测库。

**Comment by zuokanmingyuli** [comment]
@luotao1 非常不好意思，
我试了下用我上面用的版本的预测库和新的打包好的示例，仍然会报错：

`[100%] Linking CXX executable mobilenet_test CMakeFiles/mobilenet_test.dir/mobilenet_test.o：在函数‘paddle::PrepareTRTConfig(paddle::AnalysisConfig*, int)’中： /home/xxx/paddle_inference_sample_v1.6/sample/inference/mobilenet_test.cc:24：对‘paddle::AnalysisConfig::SetModel(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)’未定义的引用 CMakeFiles/mobilenet_test.dir/mobilenet_test.o：在函数‘__static_initialization_and_destruction_0(int, int)’中： /home/xxx/paddle_inference_sample_v1.6/sample/inference/mobilenet_test.cc:12：对‘google::FlagRegisterer::FlagRegisterer<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >(char const*, char const*, char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*)’未定义的引用 collect2: error: ld returned 1 exit status CMakeFiles/mobilenet_test.dir/build.make:91: recipe for target 'mobilenet_test' failed make[2]: *** [mobilenet_test] Error 1 CMakeFiles/Makefile2:72: recipe for target 'CMakeFiles/mobilenet_test.dir/all' failed make[1]: *** [CMakeFiles/mobilenet_test.dir/all] Error 2 Makefile:83: recipe for target 'all' failed make: *** [all] Error 2 run_impl.sh: 26: run_impl.sh: ./mobilenet_test: not found`

使用新提供的预测库（ubuntu14.04_cuda10.0_cudnn7_avx_mkl和ubuntu14.04_cuda10.0_cudnn7_avx_mkl_trt5），会报错找不到第三方库snappystream，我看预测库里确实没有，另外，预测库ubuntu14.04_cuda10.0_cudnn7_avx_mkl_trt5压缩包的fluid_inference/paddle/lib这个目录下是空的。
我试了一下安装1.6版本的paddle，但是没有成功，我准备试试自己编译预测库。

**Comment by OliverLPH** [comment]
@zuokanmingyuli 你这个报错原因我也遇到过类似的问题，应该是gcc版本的问题。

1. 他们预测库编译的gcc版本是4.8.2 所以你如果调整下你环境里的gcc版本再试一下应该可以。
2. snappystream，snappy目前新的预测库中都是没有的，自己编译的预测库也没有，可以在CMakeLists.txt中删除对应的指令
3. 自己编译预测库则可以避免编译报错的问题，但snappystream，snappy仍然是缺失的

如果有需要，你可以使用下面的脚本更改下ubunutu gcc版本到gcc4.8.5（建议在docker里的环境用）
```shell
apt-get install -y --no-install-recommends gcc-4.8 g++-4.8 cmake wget unzip git
update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.8 100 
update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 100
```

**Comment by zuokanmingyuli** [comment]
@OliverLPH 我试一试，非常感谢！

**Comment by zuokanmingyuli** [comment]
@OliverLPH 问题解决了，非常感谢！
