### ISSUE TITLE
根据错误信息应该是某个参数有问题，但是没查出来

### ISSUE THREAD

**Issue by AIpioneer** [PaddlePaddle/Paddle#20731]
想做一个中文情绪分析示例，训练数据是7000多行酒店评论， 分为正面、负面评论
数据预处理已经完成，现在在做训练时报错了，根据错误信息应该是某个参数有问题，但查了好长时间没查出来。
![image](https://user-images.githubusercontent.com/50724968/67143985-11e09500-f2a4-11e9-8efe-5f01c2967301.png)

这个是原始数据，第1列为标签，0为负面，1为正面；后面的是评论内容

![image](https://user-images.githubusercontent.com/50724968/67143991-202eb100-f2a4-11e9-92bc-097623bb5e9f.png)

这是经过编码后的数据，第1列为标签，后面是评论内容编码的结果

![image](https://user-images.githubusercontent.com/50724968/67143992-2cb30980-f2a4-11e9-9ee5-3d2ef0b921eb.png)

这是网络模型

![image](https://user-images.githubusercontent.com/50724968/67143997-36d50800-f2a4-11e9-9913-09ec3c841f99.png)
这是训练代码和报错代码段

![image](https://user-images.githubusercontent.com/50724968/67144003-418f9d00-f2a4-11e9-8fe2-ea4ec4b8a52d.png)
这是错误消息

辛苦看一下

**Comment by chengduoZH** [comment]
@AIpioneer  这个报错是在embeding层的计算有问题，你检查一下模型中`ipt`的名字是什么？，并且输出一下`ipt`的shape信息。
