### ISSUE TITLE
paddle.dataset.sentiment 数据集api报错

### ISSUE THREAD

**Issue by DDDivano** [PaddlePaddle/Paddle#20749]
linux下
![image](https://user-images.githubusercontent.com/10734244/67183092-35761d80-f413-11e9-836e-3a62dfb9ea00.png)
mac下
![image](https://user-images.githubusercontent.com/10734244/67183121-4cb50b00-f413-11e9-8869-acdbaa936e48.png)

**Comment by sandyhouse** [comment]
解决方案可参考：https://www.cnblogs.com/wsygdb/p/7902956.html和https://www.imooc.com/qadetail/89863
后面修复一下。

**Comment by sandyhouse** [comment]
fixed by pr #20942
