### ISSUE TITLE
Paddle Fluid 与 Pytorch冲突问题

### ISSUE THREAD

**Issue by zhizunbao-m** [PaddlePaddle/Paddle#20740]
环境：
    1）PaddlePaddle版本：请提供您的PaddlePaddle版本号（如1.1）或CommitID
    2）GPU：预测若用GPU，Tesla M60 CUDA9.0 CUDNN7.4.2
问题描述：
   由于工程正在从pytorch向paddle迁移，部分代码还需要用到torch的在进行包导入
```
import paddle.fluid as fluid
import torch
```
时程序会直接退出，请问有没有解决办法？

**Comment by willthefrog** [comment]
用gcc5以上版本编译paddle应该就可以了。

**Comment by stoicboyoversea** [comment]
I encountered the same problem. Did you solve it by compiling the source code with gcc > 5.0? Thank you.

**Comment by willthefrog** [comment]
this is most likely because of ABI breakage introduced in GCC 5, compiling from source with GCC 5+ should solve this, or you could try latest official build with GCC 8.

**Comment by lin1github** [comment]
遇到同样的问题，我查了一下服务器的GCC版，gcc -v，输出的是gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0，但还是遇到不能同时import paddle.fluid as fluid 和import torch，没有任何报错信息。

**Comment by lin1github** [comment]
经过尝试，将pytorch升级到最新版本，就没这个问题了
