### ISSUE TITLE
conda方式安装后测试时报错

### ISSUE THREAD

**Issue by qq2898** [PaddlePaddle/Paddle#20743]
conda虚拟环境，py3.7, cuda 10
通过conda install paddlepaddle-gpu cudatoolkit=10.0安装，完毕后测试
import paddle.fluid
提示 找不到 objgraph模块

**Comment by baomengxue** [comment]
@qq2898 可以pip install objgraph 或者尝试重新安装conda install paddlepaddle-gpu cudatoolkit=10.0试一哈
