### ISSUE TITLE
Dangerous non-tested layer forward

### ISSUE THREAD

**Issue by pengwangucla** [PaddlePaddle/Paddle#2074]
I recently implement a layer leakyrelu, 

I have a wrong implementation Here in BaseMatrix.cu:

 
```c++
DEFINE_MATRIX_BINARY_PARAMETER_OP(LeakyRelu, ONE_PARAMETER,
                                  b = a >= 0.0f ? a : p);
template<class T>
void BaseMatrixT<T>::leakyRelu(BaseMatrixT& b, T p) { 
  applyBinary(binary::LeakyRelu<T>(p), b); }

DEFINE_MATRIX_BINARY_PARAMETER_OP(LeakyReluDerivative, ONE_PARAMETER,
                                  a *= (b > 0.0f ? 1.0f : p));
template<class T>
void BaseMatrixT<T>::leakyReluDerivative(BaseMatrixT& b, T p) {
  applyBinary(binary::LeakyReluDerivative<T>(p), b);
}
```

Notice the gradient is correct in forward function, while not correct in backward when b < 0

However, when using the test_ActivationGrad, this layer passed the test,  what is the reason of that ? 

Should there also be a customized forward testing that also test the forward value ?

**Comment by lcy-seso** [comment]
Recently, I also got some questions about test_Layer_Grad. When I write a new layer and gives an empty backward function, but test_LayerGrad is always successful. I am very curious about the reason, but I haven't checked it yet.

**Comment by typhoonzero** [comment]
Close due to low activity, please feel free to reopen it.
