### ISSUE TITLE
imdb api用法问题

### ISSUE THREAD

**Issue by DDDivano** [PaddlePaddle/Paddle#20752]
官网的这个dataset api如何使用，可以给出一个示例吗？
![image](https://user-images.githubusercontent.com/10734244/67186252-4c6c3e00-f41a-11e9-811e-7a106c6cfe9d.png)

**Comment by gongweibao** [comment]
https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/fluid/tests/book/high-level-api/test_understand_sentiment_conv_new_api.py

看一下这个是否符合要求？

**Comment by DDDivano** [comment]
这里没有

> https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/fluid/tests/book/high-level-api/test_understand_sentiment_conv_new_api.py
> 
> 看一下这个是否符合要求？

这里没有 build_dict这个api呀

**Comment by gongweibao** [comment]
https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/dataset/tests/imdb_test.py#L35
