### ISSUE TITLE
gpu单卡效果有diff

### ISSUE THREAD

**Issue by aprilvkuo** [PaddlePaddle/Paddle#20750]
![image](https://user-images.githubusercontent.com/9441675/67183480-22b01880-f414-11e9-8629-b61ac92948ed.png)

![image](https://user-images.githubusercontent.com/9441675/67183505-3196cb00-f414-11e9-8848-17cc53203651.png)

CPU 单核和多核都能够稳定复现。随机数种子已经设定

```python
    np.random.seed(0)
    random.seed(0)
    train_prog.random_seed = args.random_seed
    startup_prog.random_seed = args.random_seed
```

**Comment by chengduoZH** [comment]
>  CPU 单核和多核都能够稳定复现

@aprilvkuo 你是GPU计算结果有diff还是CPU？

**Comment by aprilvkuo** [comment]
> > CPU 单核和多核都能够稳定复现
> 
> @aprilvkuo 你是GPU计算结果有diff还是CPU？

CPU多次运行结果无diff，  GPU的计算结果多次运行结果有diff

**Comment by DDDivano** [comment]
> > > CPU 单核和多核都能够稳定复现
> > 
> > 
> > @aprilvkuo 你是GPU计算结果有diff还是CPU？
> 
> CPU多次运行结果无diff， GPU的计算结果多次运行结果有diff

加上这个试试  FLAGS_cudnn_deterministic=True

**Comment by aprilvkuo** [comment]
> > > > CPU 单核和多核都能够稳定复现
> > > 
> > > 
> > > @aprilvkuo 你是GPU计算结果有diff还是CPU？
> > 
> > 
> > CPU多次运行结果无diff， GPU的计算结果多次运行结果有diff
> 
> 加上这个试试 FLAGS_cudnn_deterministic=True

@DDDivano 
你好， 加上这个之后，效果还是有diff
