### ISSUE TITLE
There is no documentation on how to write a user defined reader to read users' data

### ISSUE THREAD

**Issue by lcy-seso** [PaddlePaddle/Paddle#2076]
I find there is no documentation on how to write a user-defined reader to read users' data.

Currently, [PaddleBook](https://github.com/PaddlePaddle/book) and [Paddle/demos](https://github.com/PaddlePaddle/Paddle/tree/develop/demo) are the only officially guide on how to use V2 API. In these examples, the process of feeding raw data to PaddlePaddle are encapsulated, and there is no documentation about how to write a user-defined reader as we previously provided:
- http://deeplearning.baidu.com/doc/deprecated_doc/doc/ui/data_provider/pydataprovider2.html

Though the interface does not change in essence, a documentation about how to create a user-defined reader is still needed.

**Comment by thuyang** [comment]
Hi May I ask if there is a finished documentation for user-defined data provider?
Thank you

**Comment by lcy-seso** [comment]
close this issue due to inactivity.
