### ISSUE TITLE
编译PaddlePaddle时如何动态链接 libcudart.so (CUDA Runtime Library)

### ISSUE THREAD

**Issue by grizzzzzzzzzzly** [PaddlePaddle/Paddle#20765]
- 版本、环境信息：
    1）PaddlePaddle版本：release/1.5, git commit 5df0991f2b28e16ba37001022af6976d6161d840
    2）GPU：NVIDIA RTX 2080Ti, CUDA 10.0, Driver 430
    3）系统环境：Ubuntu 16.04, Python 3.5, GCC 5.4

- 安装方式信息：
      本地编译：

       cmake .. -DPY_VERSION=3.5 -DWITH_GPU=ON -DWITH_DSO=ON -DCUDNN_ROOT=/usr/local/cuda-10.0/lib64 -DCMAKE_BUILD_TYPE=Release -DCUDA_ARCH_NAME=Auto

       make -j16

- 现象：

虽然其余的CUDA库（例如cublas, cudnn等）都是通过dlopen的方式动态加载的，但 CUDA Runtime 库仍然是静态编译的。

为验证这一点，只需安装编译后的wheel包 (pip3 install --user)，检查 core_avx.so 即可：

        readelf -s --wide ~/.local/lib/python3.5/site-packages/paddle/fluid/core_avx.so | grep "cudaGetDeviceCount"

输出为

        19825: 00000000037d5100    19 OBJECT  LOCAL  DEFAULT   14 _ZZ18cudaGetDeviceCountE12__FUNCTION__
 
        22588: 0000000003359e60   402 FUNC    LOCAL  DEFAULT   12 cudaGetDeviceCount

很显然编译时链接了 libcudart_static.a。

- 问题：

我要如何配置cmake，使得编译时链接CUDA Runtime动态库 **libcudart.so** ？

**Comment by grizzzzzzzzzzly** [comment]
参考之前的这个issue https://github.com/PaddlePaddle/Paddle/issues/17603

说明至少某个时期，PaddlePaddle编译后是动态链接**libcudart.so**的。

**Comment by guoshengCS** [comment]
试下这个呢
`option(WITH_DSO         "Compile PaddlePaddle with dynamic linked CUDA" ON)`
  https://github.com/PaddlePaddle/Paddle/blob/develop/CMakeLists.txt#L61

**Comment by grizzzzzzzzzzly** [comment]
> 试下这个呢
> `option(WITH_DSO "Compile PaddlePaddle with dynamic linked CUDA" ON)`
> https://github.com/PaddlePaddle/Paddle/blob/develop/CMakeLists.txt#L61

这个选项我在cmake时打开了（默认就是开的）-DWITH_DSO=ON

根据 configure.cmake，这个选项的作用应该就是设置 -DPADDLE_USE_DSO，
从而控制使用 cublas, cudnn, cupti, curand, nccl 和 tensorrt 时通过dlopen动态打开相应的库。

但 cudart 还是静态链接的。

我尝试过在CUDA_NVCC_FLAGS 里加上 **-cudart=shared** , 然而并没有什么变化 。

**Comment by liupluswei** [comment]
可以cmake 的时候加上-DCUDA_USE_STATIC_CUDA_RUNTIME=OFF

**Comment by grizzzzzzzzzzly** [comment]
> CUDA_USE_STATIC_CUDA_RUNTIME

你好，在 release/1.5 这个分支下面，我在整个Paddle目录下搜索不到包含**CUDA_USE_STATIC_CUDA_RUNTIME**的文件。

不知道是不是在更旧/更新的分支里面才有这个选项？

**Comment by liupluswei** [comment]
这个是Cmake 自带的FindCUDA.cmake里面的flag
https://github.com/Kitware/CMake/blob/master/Modules/FindCUDA.cmake#L144

**Comment by grizzzzzzzzzzly** [comment]
> 这个是Cmake 自带的FindCUDA.cmake里面的flag
> https://github.com/Kitware/CMake/blob/master/Modules/FindCUDA.cmake#L144

谢谢！我去试一下。

**Comment by grizzzzzzzzzzly** [comment]
> 这个是Cmake 自带的FindCUDA.cmake里面的flag
> https://github.com/Kitware/CMake/blob/master/Modules/FindCUDA.cmake#L144

指定这个flag之后，编译出来的 core_avx.so 的确动态链接到了 libcudart.so，

不过third_party/warpctc编译生成的 **libwarpctc.so** 仍然静态链接了 libcudart_static.a。

我尝试过在 cmake/external/warpctc.cmake 里面的 CMAKE_ARGS 中加上了 

    -DCUDA_USE_STATIC_CUDA_RUNTIME=OFF

但从生成的

    build/third_party/warpctc/src/extern_warpctc-build/CMakeCache.txt

中，可以看到 -DCUDA_USE_STATIC_CUDA_RUNTIME=ON。

不知道有没有什么办法可以让编译出来的 **libwarpctc.so** 也动态链接 libcudart.so ?

非常感谢！

**Comment by chensusu11** [comment]
Hi, 我也遇到相同的问题，请问您最后有解决的思路吗？还有您是本机编译还是用的paddle 提供的docker哇？ 谢谢
