### ISSUE TITLE
nccl2训练报错

### ISSUE THREAD

**Issue by yxfGrace** [PaddlePaddle/Paddle#20773]
nccl2分布式模式，2个节点
可以正常训练，但是0号节点在结束训练时报grpc error
![image](https://user-images.githubusercontent.com/29363426/67273194-9162a400-f4f0-11e9-83bc-5b2f37c88bf3.png)
代码中已经执行了close()
![image](https://user-images.githubusercontent.com/29363426/67273045-48aaeb00-f4f0-11e9-97ce-f15e49ab44c0.png)

**Comment by gongweibao** [comment]
nccl2模式还是pserver模式？

**Comment by gongweibao** [comment]
哦。这里有一个bug。去掉close这一行吧。感谢！
