### ISSUE TITLE
BERT新增一维特征embedding，特征值id size=50，遇到Assertion `id < N` failed (received id: 2).问题

### ISSUE THREAD

**Issue by LarryLee-BD** [PaddlePaddle/Paddle#20771]
BERT模型输入新增一维特征，与token，segment，pos特征并列，新增特征向量举例：[2, 2, 2, 2, 2, 2, 2, 0, 0, 0, 0, 0, 0, 3, 0]，该特征的vocab size设为50，新增特征代码：

self._history_marker_types = 50
self._history_marker_emb_name = "history_answer_marker_embedding"
history_marker_emb_out = fluid.layers.embedding(input=history_answer_marker_ids, size=[self._history_marker_types, self._emb_size], dtype=self._dtype,param_attr=fluid.ParamAttr(name=self._history_marker_emb_name, initializer=self._param_initializer))

报错：
Exception: /paddle/paddle/fluid/operators/lookup_table_op.cu:36 Assertion `id < N` failed (received id: 2).
F1022 12:13:08.189927 21381 device_context.cc:333] cudaStreamSynchronize an illegal instruction was encountered errno:73

这是什么问题？size=50不应该满足不了id值

**Comment by guoshengCS** [comment]
这个报错确实是id超过了词表大小，可以在embeding前面使用 `layers.Print(layers.reduce_max(input))`看下最大的id是多少

**Comment by LarryLee-BD** [comment]
好的，我试试
