### ISSUE TITLE
BERT use case

### ISSUE THREAD

**Issue by ddokupil** [PaddlePaddle/Paddle#20778]
Hi,
We'd like to ask you for your BERT use case (in other words: how to test it to better suite your needs).
How do you use BERT? What batch size? How many threads? In Unit Test by default it is BS=8. Do you confirm that?

**Comment by bingyanghuang** [comment]
@luotao1 Could you help provide us some information about this?

**Comment by bingyanghuang** [comment]
Bert configuration we can use default one in the UT. Since we are working on ERNIE, will suspect ERNIE in our CE system. And Baidu will give us their CE script when it's ready.
