### ISSUE TITLE
预测阶段报错 create_double_buffer_reader error

### ISSUE THREAD

**Issue by April0402** [PaddlePaddle/Paddle#20799]
环境信息：
  PaddlePaddle版本：1.5.0
  GPU信息：P4, CUDA 9.0 CUDNN 7.3
  系统环境：python版本 3.5.3

问题描述：
  paddle使用是fluid版，模型是在ernie基础上finetune的阅读理解模型，模型结构和ernie提供的demo一致。在预测时，以服务的形式提供外部访问，并且需要将两个模型同时加载到内存中。在两个模型并发调用时，会出现这个错误。详细信息如下：
![1](https://user-images.githubusercontent.com/9245641/67445552-e82ac380-f63f-11e9-8825-e7d32a3c4052.png)
![2](https://user-images.githubusercontent.com/9245641/67445556-eb25b400-f63f-11e9-8389-a873065a5862.png)
![3](https://user-images.githubusercontent.com/9245641/67445600-0ee8fa00-f640-11e9-9454-d821ed5aa164.png)

**Comment by wanghaoshuang** [comment]
看起来像是没有给py_reader设置data_reader: 
PyReader: 
https://www.paddlepaddle.org.cn/documentation/docs/zh/1.5/api_cn/io_cn.html#decorate_sample_list_generator

py_reader: https://www.paddlepaddle.org.cn/documentation/docs/zh/1.5/api_cn/layers_cn/io_cn.html#py-reader

**Comment by April0402** [comment]
> 看起来像是没有给py_reader设置data_reader:
> PyReader:
> https://www.paddlepaddle.org.cn/documentation/docs/zh/1.5/api_cn/io_cn.html#decorate_sample_list_generator
> 
> py_reader: https://www.paddlepaddle.org.cn/documentation/docs/zh/1.5/api_cn/layers_cn/io_cn.html#py-reader

已经通过decorate_tensor_provider设置了，而且这个单并发的跑infer可以正常，只有多并发跑才会有问题
