### ISSUE TITLE
好奇动态图里反向传播过程相关

### ISSUE THREAD

**Issue by xiangyubo** [PaddlePaddle/Paddle#20814]
版本：paddle 1.5.2
想咨询一个问题，在 paddle 的动态图里面，最后 loss 运行 backward 方法，是会计算整个网络所有参数的梯度吗？
还咨询一下哈，是不是所的 Variable 变量，都会存一个 float32的梯度属性？
我是在看源码的时候有个部分，optimizer.backward 函数里会去获取所有参数的梯度参数
```
for param in parameters:
    if not param.trainable:
        continue
    if param._ivar._grad_ivar() is not None:
        # create gradient variable
        grad_var = Variable(
            block=loss.block,
            name=param._ivar._grad_name(),
            stop_gradient=True,
            ivar=param._ivar._grad_ivar())
        params_grads.append((param, grad_var))
```

**Comment by phlrain** [comment]
backward会计算所有 Variable的梯度，但是只有parameter的梯度属性才会被存储下来，中间变量都是临时的变量，运算完成之后 会被释放。

如果通过设置 stop_gradient  =True，有些反向会计算会被裁剪掉。

**Comment by xiangyubo** [comment]
> backward会计算所有 Variable的梯度，但是只有parameter的梯度属性才会被存储下来，中间变量都是临时的变量，运算完成之后 会被释放。
> 
> 如果通过设置 stop_gradient =True，有些反向会计算会被裁剪掉。

parameter的梯度属性才会被存储下来。
--------------------------------------------------
针对这句话，我这么理解你看对不对：
对于一个 CNN 结构的模型，绝大部分参数都是parameter，那么都会存储一个梯度。当这网络在训练的时候，所占用的内存/显存，比直观上认为的参数要大一倍，对吗？因为一般认为的参数就是定义的那一部分，没包含存储的梯度。

**Comment by xiangyubo** [comment]
> > backward会计算所有 Variable的梯度，但是只有parameter的梯度属性才会被存储下来，中间变量都是临时的变量，运算完成之后 会被释放。
> > 如果通过设置 stop_gradient =True，有些反向会计算会被裁剪掉。
> 
> ## parameter的梯度属性才会被存储下来。
> 针对这句话，我这么理解你看对不对：
> 对于一个 CNN 结构的模型，绝大部分参数都是parameter，那么都会存储一个梯度。当这网络在训练的时候，所占用的内存/显存，比直观上认为的参数要大一倍，对吗？因为一般认为的参数就是定义的那一部分，没包含存储的梯度。

比如 y=conv(x)。conv中的参数和参数对应的梯度都会保存，并且是常驻的。但是训练一个batch的时候，更多的是y会作为临时变量保存，因为反向传播计算需要。而这个部分会比参数多得多，5倍以上。在 1.6之后会默认打开显存释放策略，显存占用大的情况会改善。
