### ISSUE TITLE
预测的时候出core，没有详细信息，不知道问题在哪？

### ISSUE THREAD

**Issue by xiuechen** [PaddlePaddle/Paddle#20813]
Exception: /paddle/paddle/fluid/memory/detail/meta_cache.cc:33 Assertion `desc->check_guards()` failed.
terminate called after throwing an instance of 'std::runtime_error'

debug core信息提示：

(gdb) bt
#0  0x00007f81eb3513f7 in raise () from /opt/compiler/gcc-4.8.2/lib/libc.so.6
#1  0x00007f81eb3527d8 in abort () from /opt/compiler/gcc-4.8.2/lib/libc.so.6
#2  0x00007f81ebc41c65 in __gnu_cxx::__verbose_terminate_handler () at ../../../../libstdc++-v3/libsupc++/vterminate.cc:95
#3  0x00007f81ebc3fe06 in __cxxabiv1::__terminate (handler=<optimized out>) at ../../../../libstdc++-v3/libsupc++/eh_terminate.cc:38
#4  0x00007f81ebc3fe33 in std::terminate () at ../../../../libstdc++-v3/libsupc++/eh_terminate.cc:48
#5  0x00007f81ebc3fdf7 in std::rethrow_exception (ep=...) at ../../../../libstdc++-v3/libsupc++/eh_ptr.cc:228
#6  0x00007f81f7d9c49d in paddle::framework::OperatorBase::Run(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&) () from ./fluid_inference/paddle/lib/libpaddle_fluid.so
#7  0x00007f81f6fb6bfe in paddle::framework::Executor::RunPreparedContext(paddle::framework::ExecutorPrepareContext*, paddle::framework::Scope*, bool, bool, bool) () from ./fluid_inference/paddle/lib/libpaddle_fluid.so
#8  0x00007f81f6e3c3fa in paddle::NativePaddlePredictor::Run(std::vector<paddle::PaddleTensor, std::allocator<paddle::PaddleTensor> > const&, std::vector<paddle::PaddleTensor, std::allocator<paddle::PaddleTensor> >*, int) () from ./fluid_inference/paddle/lib/libpaddle_fluid.so
#9  0x00000000004a06c7 in baidu::pmallrec::GbdtModel::predict (this=0x1e74240, user_id=67483440, user_feature=0x47363060, recallpidlist=..., 
    pidlist=..., get_dict=true, log_id=..., statusstr=...) at baidu/netdisk/dp-pmall-recapi/src/baidu/pmallrec/gbdt_model.cpp:475

**Comment by Superjomn** [comment]
看起来是模型格式有问题，在 protobuf 加载时出现问题
