### ISSUE TITLE
动态图加载模型预测相同数据集结果不固定

### ISSUE THREAD

**Issue by xiangyubo** [PaddlePaddle/Paddle#20829]
- 版本、环境信息：
    1）PaddlePaddle版本：1.5.1
    3）GPU：GPU v100
    4）系统环境：python 3.x，AI Studio 

我自己搭建了一个mobile-net的模型，用于分类。训练了70轮之后，训练集的准确率达到85%，然后我把模型通过 fluid.dygraph.save_persistables 保存。
但是在验证的时候，我通过 fluid.dygraph.load_persistables 加载模型去相同的数据集上验证，准确率很低，而且多次运行时候，准确率还不同。

可以直接在 AI Studio 上 fork 这个项目运行，我已经把训练好的参数保存在当前目录下了，可以不用训练。项目地址： https://aistudio.baidu.com/aistudio/projectdetail/155065

**Comment by phlrain** [comment]
evaluation的时候 是不是切换到了 eval mode， 如果用到了dropout，要切换到eval mode

**Comment by xiangyubo** [comment]
> evaluation的时候 是不是切换到了 eval mode， 如果用到了dropout，要切换到eval mode

有用到 Layer.eval() 这句话，在load_dict 之后就运行了。模型没有用到 dropout

**Comment by xiangyubo** [comment]
现在动态图的加载出现一个奇怪的情况，我的网络构建的时候，对 Conv2D的param_attr设置了ParamAttr(initializer=MSRA())。我保存的参数打印出来看，有 Conv2D_0.w_0，但是我加载进来后，再类似打印参数，就没有这个key了
 for k, v in mobilenet.state_dict().items():
            utils.logger.info("key:{}   value:{}".format(k, v.numpy()))

**Comment by DDDivano** [comment]
根据你的描述，排除一切随机因素，可以判断是没有正确load，所以每次infer的时候都是随机权重然后正确率低并且不是固定值。那么需要排查一下 save是否正确save下来全部的参数，可以贴一下你的代码

**Comment by xiangyubo** [comment]
> 根据你的描述，排除一切随机因素，可以判断是没有正确load，所以每次infer的时候都是随机权重然后正确率低并且不是固定值。那么需要排查一下 save是否正确save下来全部的参数，可以贴一下你的代码

我把我的网络结构换成 alex-net 就能跑，感觉是我构建 mobile-net 的部分有错。不过我不知道错在哪儿，看着像是缺少 add_sublayer，但是不太看得懂这个函数有什么用

```
# -*- coding: UTF-8 -*-
"""
动态图构建的 mobile-net
"""
import paddle.fluid as fluid
import numpy as np
from paddle.fluid import ParamAttr
from paddle.fluid.initializer import MSRA


class ConvBnLayer(fluid.dygraph.Layer):
    """
    卷积 + batch_normal 层
    """
    def __init__(self, name_scope, num_filters, filter_size, stride=1,
                 padding=0, dilation=1, groups=1, act="relu", use_cudnn=True,
                 param_attr=None, bias_attr=None):
        super(ConvBnLayer, self).__init__(name_scope)

        self._conv2d = fluid.dygraph.Conv2D(
            self.full_name(),
            num_filters=num_filters,
            filter_size=filter_size,
            stride=stride,
            padding=padding,
            dilation=dilation,
            groups=groups,
            param_attr=param_attr,
            bias_attr=bias_attr,
            use_cudnn=use_cudnn)
        self._batch_normal = fluid.dygraph.BatchNorm(
            self.full_name(),
            num_channels=num_filters,
            act=act,
            param_attr=ParamAttr(),
            bias_attr=ParamAttr()
        )

    def forward(self, inputs):
        x = self._conv2d(inputs)
        x = self._batch_normal(x)
        return x


class DepthWiseSeparable(fluid.dygraph.Layer):
    """
    深度分离
    """
    def __init__(self, name_scope, num_filters1, num_filters2, stride, groups=1, use_cudnn=True):
        super(DepthWiseSeparable, self).__init__(name_scope)

        self._depth_wise_conv = ConvBnLayer(
            self.full_name(), num_filters=num_filters1, filter_size=3,
            stride=stride, padding=1, groups=groups, use_cudnn=use_cudnn
        )

        self._point_wise_conv = ConvBnLayer(
            self.full_name(), num_filters=num_filters2, filter_size=1,
            stride=1, padding=0, use_cudnn=use_cudnn
        )

    def forward(self, inputs):
        x = self._depth_wise_conv(inputs)
        x = self._point_wise_conv(x)
        return x


class MobileNet(fluid.dygraph.Layer):
    """
    mobile-net
    """
    def __init__(self, name_scope, class_dim):
        super(MobileNet, self).__init__(name_scope)

        self.conv1 = ConvBnLayer(self.full_name(), 32, 3, 2, 1)
        self.conv2_1 = DepthWiseSeparable(self.full_name(), num_filters1=32, num_filters2=64, groups=32, stride=1)
        self.conv2_2 = DepthWiseSeparable(self.full_name(), num_filters1=64, num_filters2=128, groups=64, stride=2)
        self.conv3_1 = DepthWiseSeparable(self.full_name(), num_filters1=128, num_filters2=128, groups=128, stride=1)
        self.conv3_2 = DepthWiseSeparable(self.full_name(), num_filters1=128, num_filters2=256, groups=128, stride=2)
        self.conv4_1 = DepthWiseSeparable(self.full_name(), num_filters1=256, num_filters2=256, groups=256, stride=1)
        self.conv4_2 = DepthWiseSeparable(self.full_name(), num_filters1=256, num_filters2=512, groups=256, stride=2)
        self.conv5_list = []
        for i in range(5):
            conv5_ = DepthWiseSeparable(self.full_name() + str(i + 1), num_filters1=512, num_filters2=512, groups=512, stride=1)
            self.conv5_list.append(conv5_)
        self.conv5_x = DepthWiseSeparable(self.full_name(), num_filters1=512, num_filters2=1024, groups=512, stride=2)
        self.conv6 = DepthWiseSeparable(self.full_name(), num_filters1=1024, num_filters2=1024, groups=1024, stride=1)
        self.pool = fluid.dygraph.Pool2D(self.full_name(), pool_type='avg', pool_stride=1, global_pooling=True)
        self.fc = fluid.dygraph.FC(self.full_name(),
                                   size=class_dim,
                                   act='softmax')

    def forward(self, inputs, label=None):
        out = self.conv1(inputs)
        out = self.conv2_1(out)
        out = self.conv2_2(out)
        out = self.conv3_1(out)
        out = self.conv3_2(out)
        out = self.conv4_1(out)
        out = self.conv4_2(out)
        for conv5_ in self.conv5_list:
            out = conv5_(out)
        out = self.conv5_x(out)
        out = self.conv6(out)
        out = self.pool(out)
        out = self.fc(out)

        if label is not None:
            acc = fluid.layers.accuracy(input=out, label=label)
            return out, acc
        else:
            return out


class Conv2D(fluid.dygraph.Layer):
    def __init__(self, name_scope, num_filters, filter_size, stride=1,
                 padding=0, dilation=1, groups=1, act=None, use_cudnn=False,
                 param_attr=None, bias_attr=None):
        super(Conv2D, self).__init__(name_scope)

        self._conv2d = fluid.dygraph.Conv2D(
            self.full_name(), num_filters=num_filters, filter_size=filter_size,
            stride=stride, padding=padding, dilation=dilation, groups=groups,
            param_attr=param_attr, bias_attr=bias_attr, act=act, use_cudnn=use_cudnn
        )

    def forward(self, inputs):
        x = self._conv2d(inputs)
        return x


class Conv2DPool(fluid.dygraph.Layer):
    def __init__(self, name_scope, num_filters, filter_size, pool_size, pool_stride,
                 pool_padding=0, pool_type='max', global_pooling=False,
                 conv_stride=1, conv_padding=0, conv_dilation=1, conv_groups=1,
                 act=None, use_cudnn=False, param_attr=None, bias_attr=None):
        super(Conv2DPool, self).__init__(name_scope)

        self._conv2d = fluid.dygraph.Conv2D(
            self.full_name(),
            num_filters=num_filters,
            filter_size=filter_size,
            stride=conv_stride,
            padding=conv_padding,
            dilation=conv_dilation,
            groups=conv_groups,
            param_attr=param_attr,
            bias_attr=bias_attr,
            act=act,
            use_cudnn=use_cudnn)

        self._pool2d = fluid.dygraph.Pool2D(
            self.full_name(),
            pool_size=pool_size,
            pool_type=pool_type,
            pool_stride=pool_stride,
            pool_padding=pool_padding,
            global_pooling=global_pooling,
            use_cudnn=use_cudnn)

    def forward(self, inputs):
        x = self._conv2d(inputs)
        x = self._pool2d(x)
        return x


class AlexNet(fluid.dygraph.Layer):
    def __init__(self, name_scope, class_dim):
        super(AlexNet, self).__init__(name_scope)

        self.conv_pool_1 = Conv2DPool(self.full_name(), 64, 11, 3, 2, conv_stride=4, conv_padding=2,
                                      act='relu')
        self.conv_pool_2 = Conv2DPool(self.full_name(), 192, 5, 3, 2, conv_stride=1, conv_padding=2,
                                      act='relu')
        self.conv_3 = Conv2D(self.full_name(), 384, 3, 1, 1, act='relu')
        self.conv_4 = Conv2D(self.full_name(), 256, 3, 1, 1, act='relu')
        self.conv_pool_5 = Conv2DPool(self.full_name(), 256, 3, 3, 2, conv_stride=1, conv_padding=1,
                                      act='relu')

        self.fc6 = fluid.dygraph.FC(self.full_name(), 4096, act='relu')
        self.fc7 = fluid.dygraph.FC(self.full_name(), 4096, act='relu')
        self.fc8 = fluid.dygraph.FC(self.full_name(), class_dim, act='softmax')

    def forward(self, inputs, label=None):
        out = self.conv_pool_1(inputs)
        out = self.conv_pool_2(out)
        out = self.conv_3(out)
        out = self.conv_4(out)
        out = self.conv_pool_5(out)
        out = self.fc6(out)
        out = fluid.layers.dropout(out, 0.5)
        out = self.fc7(out)
        out = fluid.layers.dropout(out, 0.5)
        out = self.fc8(out)

        if label is not None:
            acc = fluid.layers.accuracy(input=out, label=label)
            return out, acc
        else:
            return out


if __name__ == '__main__':
    with fluid.dygraph.guard():
        mobilenet = MobileNet('mobile-net', 3)
        img = np.zeros([2, 3, 224, 224]).astype('float32')
        label = np.zeros([2, 1]).astype('int32')
        img = fluid.dygraph.to_variable(img)
        outs = mobilenet(img).numpy()
        label = fluid.dygraph.to_variable(label)
        label.stop_gradient = True
        loss = fluid.layers.cross_entropy(outs, label)
        avg_loss = fluid.layers.mean(loss)

        # 通过这句话求出损失函数对于 out 的梯度，
        avg_loss.backward()

        print(outs)

```

**Comment by DDDivano** [comment]
> > 根据你的描述，排除一切随机因素，可以判断是没有正确load，所以每次infer的时候都是随机权重然后正确率低并且不是固定值。那么需要排查一下 save是否正确save下来全部的参数，可以贴一下你的代码
> 
> 我把我的网络结构换成 alex-net 就能跑，感觉是我构建 mobile-net 的部分有错。不过我不知道错在哪儿，看着像是缺少 add_sublayer，但是不太看得懂这个函数有什么用
> 
> ```
> # -*- coding: UTF-8 -*-
> """
> 动态图构建的 mobile-net
> """
> import paddle.fluid as fluid
> import numpy as np
> from paddle.fluid import ParamAttr
> from paddle.fluid.initializer import MSRA
> 
> 
> class ConvBnLayer(fluid.dygraph.Layer):
>     """
>     卷积 + batch_normal 层
>     """
>     def __init__(self, name_scope, num_filters, filter_size, stride=1,
>                  padding=0, dilation=1, groups=1, act="relu", use_cudnn=True,
>                  param_attr=None, bias_attr=None):
>         super(ConvBnLayer, self).__init__(name_scope)
> 
>         self._conv2d = fluid.dygraph.Conv2D(
>             self.full_name(),
>             num_filters=num_filters,
>             filter_size=filter_size,
>             stride=stride,
>             padding=padding,
>             dilation=dilation,
>             groups=groups,
>             param_attr=param_attr,
>             bias_attr=bias_attr,
>             use_cudnn=use_cudnn)
>         self._batch_normal = fluid.dygraph.BatchNorm(
>             self.full_name(),
>             num_channels=num_filters,
>             act=act,
>             param_attr=ParamAttr(),
>             bias_attr=ParamAttr()
>         )
> 
>     def forward(self, inputs):
>         x = self._conv2d(inputs)
>         x = self._batch_normal(x)
>         return x
> 
> 
> class DepthWiseSeparable(fluid.dygraph.Layer):
>     """
>     深度分离
>     """
>     def __init__(self, name_scope, num_filters1, num_filters2, stride, groups=1, use_cudnn=True):
>         super(DepthWiseSeparable, self).__init__(name_scope)
> 
>         self._depth_wise_conv = ConvBnLayer(
>             self.full_name(), num_filters=num_filters1, filter_size=3,
>             stride=stride, padding=1, groups=groups, use_cudnn=use_cudnn
>         )
> 
>         self._point_wise_conv = ConvBnLayer(
>             self.full_name(), num_filters=num_filters2, filter_size=1,
>             stride=1, padding=0, use_cudnn=use_cudnn
>         )
> 
>     def forward(self, inputs):
>         x = self._depth_wise_conv(inputs)
>         x = self._point_wise_conv(x)
>         return x
> 
> 
> class MobileNet(fluid.dygraph.Layer):
>     """
>     mobile-net
>     """
>     def __init__(self, name_scope, class_dim):
>         super(MobileNet, self).__init__(name_scope)
> 
>         self.conv1 = ConvBnLayer(self.full_name(), 32, 3, 2, 1)
>         self.conv2_1 = DepthWiseSeparable(self.full_name(), num_filters1=32, num_filters2=64, groups=32, stride=1)
>         self.conv2_2 = DepthWiseSeparable(self.full_name(), num_filters1=64, num_filters2=128, groups=64, stride=2)
>         self.conv3_1 = DepthWiseSeparable(self.full_name(), num_filters1=128, num_filters2=128, groups=128, stride=1)
>         self.conv3_2 = DepthWiseSeparable(self.full_name(), num_filters1=128, num_filters2=256, groups=128, stride=2)
>         self.conv4_1 = DepthWiseSeparable(self.full_name(), num_filters1=256, num_filters2=256, groups=256, stride=1)
>         self.conv4_2 = DepthWiseSeparable(self.full_name(), num_filters1=256, num_filters2=512, groups=256, stride=2)
>         self.conv5_list = []
>         for i in range(5):
>             conv5_ = DepthWiseSeparable(self.full_name() + str(i + 1), num_filters1=512, num_filters2=512, groups=512, stride=1)
>             self.conv5_list.append(conv5_)
>         self.conv5_x = DepthWiseSeparable(self.full_name(), num_filters1=512, num_filters2=1024, groups=512, stride=2)
>         self.conv6 = DepthWiseSeparable(self.full_name(), num_filters1=1024, num_filters2=1024, groups=1024, stride=1)
>         self.pool = fluid.dygraph.Pool2D(self.full_name(), pool_type='avg', pool_stride=1, global_pooling=True)
>         self.fc = fluid.dygraph.FC(self.full_name(),
>                                    size=class_dim,
>                                    act='softmax')
> 
>     def forward(self, inputs, label=None):
>         out = self.conv1(inputs)
>         out = self.conv2_1(out)
>         out = self.conv2_2(out)
>         out = self.conv3_1(out)
>         out = self.conv3_2(out)
>         out = self.conv4_1(out)
>         out = self.conv4_2(out)
>         for conv5_ in self.conv5_list:
>             out = conv5_(out)
>         out = self.conv5_x(out)
>         out = self.conv6(out)
>         out = self.pool(out)
>         out = self.fc(out)
> 
>         if label is not None:
>             acc = fluid.layers.accuracy(input=out, label=label)
>             return out, acc
>         else:
>             return out
> 
> 
> class Conv2D(fluid.dygraph.Layer):
>     def __init__(self, name_scope, num_filters, filter_size, stride=1,
>                  padding=0, dilation=1, groups=1, act=None, use_cudnn=False,
>                  param_attr=None, bias_attr=None):
>         super(Conv2D, self).__init__(name_scope)
> 
>         self._conv2d = fluid.dygraph.Conv2D(
>             self.full_name(), num_filters=num_filters, filter_size=filter_size,
>             stride=stride, padding=padding, dilation=dilation, groups=groups,
>             param_attr=param_attr, bias_attr=bias_attr, act=act, use_cudnn=use_cudnn
>         )
> 
>     def forward(self, inputs):
>         x = self._conv2d(inputs)
>         return x
> 
> 
> class Conv2DPool(fluid.dygraph.Layer):
>     def __init__(self, name_scope, num_filters, filter_size, pool_size, pool_stride,
>                  pool_padding=0, pool_type='max', global_pooling=False,
>                  conv_stride=1, conv_padding=0, conv_dilation=1, conv_groups=1,
>                  act=None, use_cudnn=False, param_attr=None, bias_attr=None):
>         super(Conv2DPool, self).__init__(name_scope)
> 
>         self._conv2d = fluid.dygraph.Conv2D(
>             self.full_name(),
>             num_filters=num_filters,
>             filter_size=filter_size,
>             stride=conv_stride,
>             padding=conv_padding,
>             dilation=conv_dilation,
>             groups=conv_groups,
>             param_attr=param_attr,
>             bias_attr=bias_attr,
>             act=act,
>             use_cudnn=use_cudnn)
> 
>         self._pool2d = fluid.dygraph.Pool2D(
>             self.full_name(),
>             pool_size=pool_size,
>             pool_type=pool_type,
>             pool_stride=pool_stride,
>             pool_padding=pool_padding,
>             global_pooling=global_pooling,
>             use_cudnn=use_cudnn)
> 
>     def forward(self, inputs):
>         x = self._conv2d(inputs)
>         x = self._pool2d(x)
>         return x
> 
> 
> class AlexNet(fluid.dygraph.Layer):
>     def __init__(self, name_scope, class_dim):
>         super(AlexNet, self).__init__(name_scope)
> 
>         self.conv_pool_1 = Conv2DPool(self.full_name(), 64, 11, 3, 2, conv_stride=4, conv_padding=2,
>                                       act='relu')
>         self.conv_pool_2 = Conv2DPool(self.full_name(), 192, 5, 3, 2, conv_stride=1, conv_padding=2,
>                                       act='relu')
>         self.conv_3 = Conv2D(self.full_name(), 384, 3, 1, 1, act='relu')
>         self.conv_4 = Conv2D(self.full_name(), 256, 3, 1, 1, act='relu')
>         self.conv_pool_5 = Conv2DPool(self.full_name(), 256, 3, 3, 2, conv_stride=1, conv_padding=1,
>                                       act='relu')
> 
>         self.fc6 = fluid.dygraph.FC(self.full_name(), 4096, act='relu')
>         self.fc7 = fluid.dygraph.FC(self.full_name(), 4096, act='relu')
>         self.fc8 = fluid.dygraph.FC(self.full_name(), class_dim, act='softmax')
> 
>     def forward(self, inputs, label=None):
>         out = self.conv_pool_1(inputs)
>         out = self.conv_pool_2(out)
>         out = self.conv_3(out)
>         out = self.conv_4(out)
>         out = self.conv_pool_5(out)
>         out = self.fc6(out)
>         out = fluid.layers.dropout(out, 0.5)
>         out = self.fc7(out)
>         out = fluid.layers.dropout(out, 0.5)
>         out = self.fc8(out)
> 
>         if label is not None:
>             acc = fluid.layers.accuracy(input=out, label=label)
>             return out, acc
>         else:
>             return out
> 
> 
> if __name__ == '__main__':
>     with fluid.dygraph.guard():
>         mobilenet = MobileNet('mobile-net', 3)
>         img = np.zeros([2, 3, 224, 224]).astype('float32')
>         label = np.zeros([2, 1]).astype('int32')
>         img = fluid.dygraph.to_variable(img)
>         outs = mobilenet(img).numpy()
>         label = fluid.dygraph.to_variable(label)
>         label.stop_gradient = True
>         loss = fluid.layers.cross_entropy(outs, label)
>         avg_loss = fluid.layers.mean(loss)
> 
>         # 通过这句话求出损失函数对于 out 的梯度，
>         avg_loss.backward()
> 
>         print(outs)
> ```

这个outs不需要.numpy()，而且你这里没有save呀

**Comment by xiangyubo** [comment]
> > > 根据你的描述，排除一切随机因素，可以判断是没有正确load，所以每次infer的时候都是随机权重然后正确率低并且不是固定值。那么需要排查一下 save是否正确save下来全部的参数，可以贴一下你的代码
> > 
> > 
> > 我把我的网络结构换成 alex-net 就能跑，感觉是我构建 mobile-net 的部分有错。不过我不知道错在哪儿，看着像是缺少 add_sublayer，但是不太看得懂这个函数有什么用
> > ```
> > # -*- coding: UTF-8 -*-
> > """
> > 动态图构建的 mobile-net
> > """
> > import paddle.fluid as fluid
> > import numpy as np
> > from paddle.fluid import ParamAttr
> > from paddle.fluid.initializer import MSRA
> > 
> > 
> > class ConvBnLayer(fluid.dygraph.Layer):
> >     """
> >     卷积 + batch_normal 层
> >     """
> >     def __init__(self, name_scope, num_filters, filter_size, stride=1,
> >                  padding=0, dilation=1, groups=1, act="relu", use_cudnn=True,
> >                  param_attr=None, bias_attr=None):
> >         super(ConvBnLayer, self).__init__(name_scope)
> > 
> >         self._conv2d = fluid.dygraph.Conv2D(
> >             self.full_name(),
> >             num_filters=num_filters,
> >             filter_size=filter_size,
> >             stride=stride,
> >             padding=padding,
> >             dilation=dilation,
> >             groups=groups,
> >             param_attr=param_attr,
> >             bias_attr=bias_attr,
> >             use_cudnn=use_cudnn)
> >         self._batch_normal = fluid.dygraph.BatchNorm(
> >             self.full_name(),
> >             num_channels=num_filters,
> >             act=act,
> >             param_attr=ParamAttr(),
> >             bias_attr=ParamAttr()
> >         )
> > 
> >     def forward(self, inputs):
> >         x = self._conv2d(inputs)
> >         x = self._batch_normal(x)
> >         return x
> > 
> > 
> > class DepthWiseSeparable(fluid.dygraph.Layer):
> >     """
> >     深度分离
> >     """
> >     def __init__(self, name_scope, num_filters1, num_filters2, stride, groups=1, use_cudnn=True):
> >         super(DepthWiseSeparable, self).__init__(name_scope)
> > 
> >         self._depth_wise_conv = ConvBnLayer(
> >             self.full_name(), num_filters=num_filters1, filter_size=3,
> >             stride=stride, padding=1, groups=groups, use_cudnn=use_cudnn
> >         )
> > 
> >         self._point_wise_conv = ConvBnLayer(
> >             self.full_name(), num_filters=num_filters2, filter_size=1,
> >             stride=1, padding=0, use_cudnn=use_cudnn
> >         )
> > 
> >     def forward(self, inputs):
> >         x = self._depth_wise_conv(inputs)
> >         x = self._point_wise_conv(x)
> >         return x
> > 
> > 
> > class MobileNet(fluid.dygraph.Layer):
> >     """
> >     mobile-net
> >     """
> >     def __init__(self, name_scope, class_dim):
> >         super(MobileNet, self).__init__(name_scope)
> > 
> >         self.conv1 = ConvBnLayer(self.full_name(), 32, 3, 2, 1)
> >         self.conv2_1 = DepthWiseSeparable(self.full_name(), num_filters1=32, num_filters2=64, groups=32, stride=1)
> >         self.conv2_2 = DepthWiseSeparable(self.full_name(), num_filters1=64, num_filters2=128, groups=64, stride=2)
> >         self.conv3_1 = DepthWiseSeparable(self.full_name(), num_filters1=128, num_filters2=128, groups=128, stride=1)
> >         self.conv3_2 = DepthWiseSeparable(self.full_name(), num_filters1=128, num_filters2=256, groups=128, stride=2)
> >         self.conv4_1 = DepthWiseSeparable(self.full_name(), num_filters1=256, num_filters2=256, groups=256, stride=1)
> >         self.conv4_2 = DepthWiseSeparable(self.full_name(), num_filters1=256, num_filters2=512, groups=256, stride=2)
> >         self.conv5_list = []
> >         for i in range(5):
> >             conv5_ = DepthWiseSeparable(self.full_name() + str(i + 1), num_filters1=512, num_filters2=512, groups=512, stride=1)
> >             self.conv5_list.append(conv5_)
> >         self.conv5_x = DepthWiseSeparable(self.full_name(), num_filters1=512, num_filters2=1024, groups=512, stride=2)
> >         self.conv6 = DepthWiseSeparable(self.full_name(), num_filters1=1024, num_filters2=1024, groups=1024, stride=1)
> >         self.pool = fluid.dygraph.Pool2D(self.full_name(), pool_type='avg', pool_stride=1, global_pooling=True)
> >         self.fc = fluid.dygraph.FC(self.full_name(),
> >                                    size=class_dim,
> >                                    act='softmax')
> > 
> >     def forward(self, inputs, label=None):
> >         out = self.conv1(inputs)
> >         out = self.conv2_1(out)
> >         out = self.conv2_2(out)
> >         out = self.conv3_1(out)
> >         out = self.conv3_2(out)
> >         out = self.conv4_1(out)
> >         out = self.conv4_2(out)
> >         for conv5_ in self.conv5_list:
> >             out = conv5_(out)
> >         out = self.conv5_x(out)
> >         out = self.conv6(out)
> >         out = self.pool(out)
> >         out = self.fc(out)
> > 
> >         if label is not None:
> >             acc = fluid.layers.accuracy(input=out, label=label)
> >             return out, acc
> >         else:
> >             return out
> > 
> > 
> > class Conv2D(fluid.dygraph.Layer):
> >     def __init__(self, name_scope, num_filters, filter_size, stride=1,
> >                  padding=0, dilation=1, groups=1, act=None, use_cudnn=False,
> >                  param_attr=None, bias_attr=None):
> >         super(Conv2D, self).__init__(name_scope)
> > 
> >         self._conv2d = fluid.dygraph.Conv2D(
> >             self.full_name(), num_filters=num_filters, filter_size=filter_size,
> >             stride=stride, padding=padding, dilation=dilation, groups=groups,
> >             param_attr=param_attr, bias_attr=bias_attr, act=act, use_cudnn=use_cudnn
> >         )
> > 
> >     def forward(self, inputs):
> >         x = self._conv2d(inputs)
> >         return x
> > 
> > 
> > class Conv2DPool(fluid.dygraph.Layer):
> >     def __init__(self, name_scope, num_filters, filter_size, pool_size, pool_stride,
> >                  pool_padding=0, pool_type='max', global_pooling=False,
> >                  conv_stride=1, conv_padding=0, conv_dilation=1, conv_groups=1,
> >                  act=None, use_cudnn=False, param_attr=None, bias_attr=None):
> >         super(Conv2DPool, self).__init__(name_scope)
> > 
> >         self._conv2d = fluid.dygraph.Conv2D(
> >             self.full_name(),
> >             num_filters=num_filters,
> >             filter_size=filter_size,
> >             stride=conv_stride,
> >             padding=conv_padding,
> >             dilation=conv_dilation,
> >             groups=conv_groups,
> >             param_attr=param_attr,
> >             bias_attr=bias_attr,
> >             act=act,
> >             use_cudnn=use_cudnn)
> > 
> >         self._pool2d = fluid.dygraph.Pool2D(
> >             self.full_name(),
> >             pool_size=pool_size,
> >             pool_type=pool_type,
> >             pool_stride=pool_stride,
> >             pool_padding=pool_padding,
> >             global_pooling=global_pooling,
> >             use_cudnn=use_cudnn)
> > 
> >     def forward(self, inputs):
> >         x = self._conv2d(inputs)
> >         x = self._pool2d(x)
> >         return x
> > 
> > 
> > class AlexNet(fluid.dygraph.Layer):
> >     def __init__(self, name_scope, class_dim):
> >         super(AlexNet, self).__init__(name_scope)
> > 
> >         self.conv_pool_1 = Conv2DPool(self.full_name(), 64, 11, 3, 2, conv_stride=4, conv_padding=2,
> >                                       act='relu')
> >         self.conv_pool_2 = Conv2DPool(self.full_name(), 192, 5, 3, 2, conv_stride=1, conv_padding=2,
> >                                       act='relu')
> >         self.conv_3 = Conv2D(self.full_name(), 384, 3, 1, 1, act='relu')
> >         self.conv_4 = Conv2D(self.full_name(), 256, 3, 1, 1, act='relu')
> >         self.conv_pool_5 = Conv2DPool(self.full_name(), 256, 3, 3, 2, conv_stride=1, conv_padding=1,
> >                                       act='relu')
> > 
> >         self.fc6 = fluid.dygraph.FC(self.full_name(), 4096, act='relu')
> >         self.fc7 = fluid.dygraph.FC(self.full_name(), 4096, act='relu')
> >         self.fc8 = fluid.dygraph.FC(self.full_name(), class_dim, act='softmax')
> > 
> >     def forward(self, inputs, label=None):
> >         out = self.conv_pool_1(inputs)
> >         out = self.conv_pool_2(out)
> >         out = self.conv_3(out)
> >         out = self.conv_4(out)
> >         out = self.conv_pool_5(out)
> >         out = self.fc6(out)
> >         out = fluid.layers.dropout(out, 0.5)
> >         out = self.fc7(out)
> >         out = fluid.layers.dropout(out, 0.5)
> >         out = self.fc8(out)
> > 
> >         if label is not None:
> >             acc = fluid.layers.accuracy(input=out, label=label)
> >             return out, acc
> >         else:
> >             return out
> > 
> > 
> > if __name__ == '__main__':
> >     with fluid.dygraph.guard():
> >         mobilenet = MobileNet('mobile-net', 3)
> >         img = np.zeros([2, 3, 224, 224]).astype('float32')
> >         label = np.zeros([2, 1]).astype('int32')
> >         img = fluid.dygraph.to_variable(img)
> >         outs = mobilenet(img).numpy()
> >         label = fluid.dygraph.to_variable(label)
> >         label.stop_gradient = True
> >         loss = fluid.layers.cross_entropy(outs, label)
> >         avg_loss = fluid.layers.mean(loss)
> > 
> >         # 通过这句话求出损失函数对于 out 的梯度，
> >         avg_loss.backward()
> > 
> >         print(outs)
> > ```
> 
> 这个outs不需要.numpy()，而且你这里没有save呀

这个只是网络结构的部分，没包含训练。。。完整的可以看我在 AI Studio 上的项目，是公开的。
