### ISSUE TITLE
模型复現CSRNET 出现diff

### ISSUE THREAD

**Issue by stanchan123** [PaddlePaddle/Paddle#20827]
我現將 CSRNET 模型完整部署到PADDLE 上並成功運行，但效果與原模型結果相差很遠，我的模型結構及參數跟原模型應是一樣，已經做了很多了，實在求助無問，能幫我看看到底是什麼調參還是其他問題嗎 ?
以及問有一些PADDLE 复現  要注意的地方嗎?
原模型
https://github.com/Neerajj9/CSRNet-keras

**Comment by stanchan123** [comment]
Stan--項目名為 CSRNet-paddle

**Comment by ceci3** [comment]
模型里并没有别的特殊的op，看原本pytorch代码里有对卷积的weight使用`nn.init.normal_(m.weight, std=0.01)`这种初始化方式，可以把paddle改成相同的试下。另外可以看下是否是一些参数，优化器或者策略没有对上。
