### ISSUE TITLE
相同模型，相同数据情况下，单机训练auc可以收敛提升，但是多机训练auc反而逐渐下降

### ISSUE THREAD

**Issue by wuhaijun2018** [PaddlePaddle/Paddle#20821]
平台：paddlecloud
单机：auc 0.76
多机：auc 从0.6逐渐下降至0.52左右
optimizer ：adam
embedding：IS_SPARSE

多机配置：
    if is_local:
        train_loop(fluid.default_main_program())
    else:
        port = os.getenv("PADDLE_PORT", "6174")
        pserver_ips = os.getenv("PADDLE_PSERVERS")  # ip,ip...
        eplist = []
        for ip in pserver_ips.split(","):
            eplist.append(':'.join([ip, port]))
        pserver_endpoints = ",".join(eplist)  # ip:port,ip:port...
        trainers = int(os.getenv("PADDLE_TRAINERS_NUM", "0"))
        current_endpoint = os.getenv("POD_IP") + ":" + port
        trainer_id = int(os.getenv("PADDLE_TRAINER_ID", "0"))
        t = fluid.DistributeTranspiler()
        t.transpile(trainer_id, pservers=pserver_endpoints, trainers=trainers)
        if training_role == "PSERVER":
            pserver_prog = t.get_pserver_program(current_endpoint)
            pserver_startup = t.get_startup_program(current_endpoint,
                                                    pserver_prog)
            exe.run(pserver_startup)
            exe.run(pserver_prog)
        elif training_role == "TRAINER":
            train_loop(t.get_trainer_program())

**Comment by seiriosPlus** [comment]
1. 分布式是同步训练还是异步训练
2. 从单机切换到分布式有调整参数
3. 分布式训练的规模、数据有无切分

**Comment by wuhaijun2018** [comment]
1. 同步的
2. 没有调整
3. 切分是啥意思，数据都是一样的
