### ISSUE TITLE
c++预测接口，模型调用ZeroCopyRun()出core

### ISSUE THREAD

**Issue by wuhaijun2018** [PaddlePaddle/Paddle#20830]
paddle版本：1.52
模型加载正常，但是调用ZeroCopyRun()接口，出core，麻烦看下
![image](https://user-images.githubusercontent.com/37178931/67538632-40ca9100-f712-11e9-9fe8-65e74c9bdfea.png)

代码：
![image](https://user-images.githubusercontent.com/37178931/67538649-4fb14380-f712-11e9-8b60-ad8943c5c7f5.png)

**Comment by Superjomn** [comment]
paddle 的出错日志有吗，到 core 里面看不出来

**Comment by wuhaijun2018** [comment]
没有

**Comment by wuhaijun2018** [comment]
问下 query embeding的输入数据设置 这块有问题吗？会影响会core吗？

**Comment by NHZlX** [comment]
shell 下设置 `export GLOG_v=4` 可以打印出更多的log。

另外可以贴一下AnalysisConfig设置的代码么

**Comment by wuhaijun2018** [comment]
已经解决，主要是lod-tensor输入数据的配置上有问题，导致数据类型异常，出core，thx
