### ISSUE TITLE
静态图模式下如何将numpy数组传入层以作为常量使用？

### ISSUE THREAD

**Issue by Yogurt2019** [PaddlePaddle/Paddle#20839]
Hi，我在使用静态图模式时，需要向主程序传入一个常量以供使用，在静态图模式下如何实现传入一个常量呢？
我试过使用Tensor中的set()方法，但是在进行矩阵乘法的时候报错：
- File "/home/ddj2/PycharmProjects/image_classification_tax/build_model.py", line 69, in _tax_model
-     p = fluid.layers.matmul(mask, base_result_sf, transpose_x=False, transpose_y=True)
-   File "/home/ddj2/.conda/envs/paddle/lib/python3.7/site-packages/paddle/fluid/layers/nn.py", line 6777, in matmul
-     __check_input(x, y)
-   File "/home/ddj2/.conda/envs/paddle/lib/python3.7/site-packages/paddle/fluid/layers/nn.py", line 6752, in __check_input
-     x_shape = list(x.shape)
- TypeError: 'method' object is not iterable
我只是想传入一个数组常量以和算出来的loss进行乘法计算

**Comment by phlrain** [comment]
可以试下 fill_constant

**Comment by Yogurt2019** [comment]
> 可以试下 fill_constant

你好，fill_constant只能传入一个都是同样数字的数组，但是我想传一个我自己的numpy数组，这种情况应该怎么办呢？

**Comment by xiangyubo** [comment]
> > 可以试下 fill_constant
> 
> 你好，fill_constant只能传入一个都是同样数字的数组，但是我想传一个我自己的numpy数组，这种情况应该怎么办呢？

试试这个呢？
```
param_name = fluid.layers.assign(np.array([1,2,3,4,5], dtype=np.int32))
```

**Comment by Yogurt2019** [comment]
> > > 可以试下 fill_constant
> > 
> > 
> > 你好，fill_constant只能传入一个都是同样数字的数组，但是我想传一个我自己的numpy数组，这种情况应该怎么办呢？
> 
> 试试这个呢？
> 
> ```
> param_name = fluid.layers.assign(np.array([1,2,3,4,5], dtype=np.int32))
> ```

你好，可能我没描述清楚问题，我是想把numpy数组传入一个常量层中，而不是一个Variable中，由于这个数组很大，所以我不想每次feed一个batch数据的时候feed这个数组，这样会把我的内存占满

**Comment by Yogurt2019** [comment]
> > > 可以试下 fill_constant
> > 
> > 
> > 你好，fill_constant只能传入一个都是同样数字的数组，但是我想传一个我自己的numpy数组，这种情况应该怎么办呢？
> 
> 试试这个呢？
> 
> ```
> param_name = fluid.layers.assign(np.array([1,2,3,4,5], dtype=np.int32))
> ```

你好，不好意思之前是我没弄清楚，这个方法是可以的，谢谢!
