### ISSUE TITLE
采用稀疏特征emb后训练没有存储稀疏emb层参数，预测报错

### ISSUE THREAD

**Issue by menghou** [PaddlePaddle/Paddle#20835]
def word_dis_emb(word, dict_size=DICT_SIZE, embed_size=EMBED_SIZE):
    """
    """
    embed = fluid.layers.embedding(
        input=word,
        size=[dict_size, embed_size],
        dtype='float32',
        param_attr=fluid.ParamAttr(
            name="dis_emb",
            learning_rate=5,
            initializer=fluid.initializer.Xavier(fan_in=embed_size, fan_out=embed_size)
            #initializer=fluid.initializer.Normal(scale=1/math.sqrt(dict_size))
            ),
        is_sparse=True,
        is_distributed=True)
    return embed

![image](https://user-images.githubusercontent.com/9972335/67563616-a2f7b600-f753-11e9-803a-72403d3aed1a.png)

**Comment by seiriosPlus** [comment]
1. save使用的是 `save_persistable` 还是 ·save_inerence_model·
2. 如果使用了`save_inerence_model` 拆解的网络中，确认包含 `dis_emb`么？

**Comment by menghou** [comment]
> 1. save使用的是 `save_persistable` 还是 ·save_inerence_model·
> 2. 如果使用了`save_inerence_model` 拆解的网络中，确认包含 `dis_emb`么？

save使用的是‘save_persistable’

**Comment by seiriosPlus** [comment]
把`is_distributed`设置为False.

**Comment by seiriosPlus** [comment]
问题已解决，close
