### ISSUE TITLE
dice_loss如何进行多值图像分割？

### ISSUE THREAD

**Issue by WangTaoSpace** [PaddlePaddle/Paddle#20837]
![image](https://user-images.githubusercontent.com/20881549/67566050-675fea80-f759-11e9-9f2f-4df5a67fe008.png)
上面是我的predict，label的shape，类别为10，为了符合dice_loss的输入我给label加了一个维度。
但是报错
![image](https://user-images.githubusercontent.com/20881549/67566190-c4f43700-f759-11e9-9183-964d843a2026.png)
多谢

**Comment by seiriosPlus** [comment]
这个是说定义的数据类型错误，  one hot 只支持int/int64类型的输入
