### ISSUE TITLE
paddle 1.6.0 训练过程中报错

### ISSUE THREAD

**Issue by yxfGrace** [PaddlePaddle/Paddle#20849]
使用paddle fluid 1.6.0
k8s cpu 2个trainer 2个pserver
正常训练一段时间后报错
![image](https://user-images.githubusercontent.com/29363426/67654979-33b7d700-f98a-11e9-84b7-46f2e0b46761.png)
![image](https://user-images.githubusercontent.com/29363426/67654998-46321080-f98a-11e9-98e1-73dd98469b3f.png)
如果是1个trainer1个pserver，目前还没有发现会报错

**Comment by MrChengmo** [comment]
请问具体的错误是什么呢？可以贴一下报错日志，提供一下复现代码吗？
