### ISSUE TITLE
量化后int8模型如何对输入为float类型数据进行预测？

### ISSUE THREAD

**Issue by yanyq1990** [PaddlePaddle/Paddle#20841]
原模型输入为float（0~1）的RGB图片，模型经过压缩后，卷积核参数量化为int8，在预测时报错，类型不一致，即输入的float类型数据与int8类型卷积核无法计算，这种情况如何处理？

**Comment by tensor-tang** [comment]
可否贴下具体的报错信息，int8量化应该跟输入类型没有直接关系吧。

**Comment by yanyq1990** [comment]
Traceback (most recent call last):
  File "test.py", line 101, in <module>
    main()
  File "test.py", line 88, in main
    fetch_list=fetch_targets)
  File "/usr/local/lib/python2.7/dist-packages/paddle/fluid/executor.py", line 657, in run
    use_program_cache=use_program_cache)
  File "/usr/local/lib/python2.7/dist-packages/paddle/fluid/executor.py", line 755, in _run
    exe.run(program.desc, scope, 0, True, True, fetch_var_name)
paddle.fluid.core_avx.EnforceNotMet: Invoke operator conv2d error.
Python Call stacks: 
  File "/usr/local/lib/python2.7/dist-packages/paddle/fluid/framework.py", line 1774, in append_op
    attrs=kwargs.get("attrs", None))
  File "/usr/local/lib/python2.7/dist-packages/paddle/fluid/layer_helper.py", line 43, in append_op
    return self.main_program.current_block().append_op(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/paddle/fluid/layers/nn.py", line 2181, in conv2d
    'fuse_relu_before_depthwise_conv': False
  File "/data/home/yanyuanqing/documents/projects/iresnet2/model/submodule.py", line 47, in conv2d_leaky_relu
    bias_attr=bias_attr)
  File "/data/home/yanyuanqing/documents/projects/iresnet2/model/iresnet.py", line 30, in stem_block
    name='conv1' + name)                     # 1 / 2
  File "/data/home/yanyuanqing/documents/projects/iresnet2/model/iresnet.py", line 15, in __call__
    conv1a, conv2a, conv_temp4a, up_1a2a = self.stem_block(view_l, 'a')
  File "quantization.py", line 81, in compress
    preds = model(view_l, view_r)
  File "quantization.py", line 145, in <module>
    compress()
C++ Call stacks: 
****Enforce failed. Expected input_data_type == filter_data_type, but received input_data_type:5 != filter_data_type:21.
input and filter data type should be consistent at [/paddle/paddle/fluid/operators/conv_op.cc:117]****
PaddlePaddle Call Stacks:
0       0x7fcd01d1e638p void paddle::platform::EnforceNotMet::Init<std::string>(std::string, char const*, int) + 360
1       0x7fcd01d1e987p paddle::platform::EnforceNotMet::EnforceNotMet(std::string const&, char const*, int) + 87
2       0x7fcd0214960ep paddle::operators::ConvOp::GetExpectedKernelType(paddle::framework::ExecutionContext const&) const + 2190
3       0x7fcd03dc256bp paddle::framework::OperatorWithKernel::ChooseKernel(paddle::framework::RuntimeContext const&, paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&) const + 235
4       0x7fcd03dc46d8p paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&, paddle::framework::RuntimeContext*) const + 728
5       0x7fcd03dc4951p paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&) const + 529
6       0x7fcd03dbf4e3p paddle::framework::OperatorBase::Run(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&) + 307
7       0x7fcd01eab8aep paddle::framework::Executor::RunPreparedContext(paddle::framework::ExecutorPrepareContext*, paddle::framework::Scope*, bool, bool, bool) + 622
8       0x7fcd01eae86fp paddle::framework::Executor::Run(paddle::framework::ProgramDesc const&, paddle::framework::Scope*, int, bool, bool, std::vector<std::string, std::allocator<std::string> > const&, bool) + 143
9       0x7fcd01d0f54dp
10      0x7fcd01d51596p
11            0x4c5b34p PyEval_EvalFrameEx + 36644
12            0x4ba916p PyEval_EvalCodeEx + 790
13            0x4c2c3cp PyEval_EvalFrameEx + 24620
14            0x4ba916p PyEval_EvalCodeEx + 790
15            0x4c24eap PyEval_EvalFrameEx + 22746
16            0x4c210fp PyEval_EvalFrameEx + 21759
17            0x4ba916p PyEval_EvalCodeEx + 790
18            0x4eb1bfp
19            0x4e5e52p PyRun_FileExFlags + 130
20            0x4e4706p PyRun_SimpleFileExFlags + 390
21            0x49380ep Py_Main + 1358
22      0x7fce68c3a830p __libc_start_main + 240
23            0x4931d9p _start + 41

**Comment by yanyq1990** [comment]
主要的就是我加粗显示的两行，提示卷积操作的输入和filter类型必须一致，而现在的是input_data_type:5 != filter_data_type:21，paddle源码定义的FP32 = 5，INT8 = 21，而我图片输入是0~1的float数据，量化后卷积参数为int8的

**Comment by wzzju** [comment]
您好！参见这里：https://paddlepaddle.github.io/Paddle-Lite/v2.0.0-rc/model_quantization/#compressor%E5%92%8C%E9%87%8F%E5%8C%96%E9%85%8D%E7%BD%AE%E6%96%87%E4%BB%B6 ， 若想使用fluid运行量化模型请使用`float_model_save_path `指定的文件路径下的模型。
<img width="857" alt="3cddc8a1c1ff2efe0e98f319d" src="https://user-images.githubusercontent.com/17102274/67824305-e611aa80-fb00-11e9-9b66-2fabb30a9334.png">

**Comment by yanyq1990** [comment]
可是我并不是在server端做预测的啊，那int8的模型现在能在什么情况下使用？
