### ISSUE TITLE
新添加op,加入到模型中运行一段时间后报如下错

### ISSUE THREAD

**Issue by cjt222** [PaddlePaddle/Paddle#20867]
![image](https://user-images.githubusercontent.com/17508662/67736952-7a6a0780-fa44-11e9-849d-dc6bdf36117e.png)

**Comment by wzzju** [comment]
您好！新添加op是您自己定制的op吧，根据您的报错信息可以看出，您的op中对tensor的写操作应该越界了，您可以自查一下。
