### ISSUE TITLE
paddle的服务器部署相关的问题

### ISSUE THREAD

**Issue by AIpioneer** [PaddlePaddle/Paddle#20864]
请问一下，现在在进行paddle的服务器部署，官方文档
https://www.paddlepaddle.org.cn/documentation/docs/zh/advanced_usage/deploy/inference/python_infer_cn.html#paddledtype
中Python 预测 API 使用代码：
tensor = PaddleTensor(name="tensor", data=numpy.array([1, 2, 3], dtype="int32"))
提示
tensor = PaddleTensor(name="tensor", data=np.array([1, 2, 3], dtype="int32"))
TypeError: __init__(): incompatible constructor arguments. The following argument types are supported:
    1. paddle.fluid.core_avx.PaddleTensor()
Invoked with: kwargs: name='tensor', data=array([1, 2, 3], dtype=int32)

是什么原因？

**Comment by fc500110** [comment]
哪个版本

**Comment by AIpioneer** [comment]
1.5

**Comment by AIpioneer** [comment]
升级版本后解决了，谢谢
