### ISSUE TITLE
联邦学习包无法导入

### ISSUE THREAD

**Issue by hanlyto** [PaddlePaddle/Paddle#20873]
- 标题：paddle1.6无法import 联邦学习的包paddle_fl
- 版本、环境信息：
    1）PaddlePaddle版本：1.6
    2）CPU：Ryzen 5 2500U
    3）GPU：无
    4）系统环境：anaconda, python 3.7
- 安装方式信息：
1）pip安装
2）本地编译：请提供cmake命令，编译命令       
  在线安装等，使用的清华大学的镜像安装的paddle1.6
- 复现信息：运行import paddle_fl的时候，显示没有这个包
- 问题描述：在运行网址https://paddlefl.readthedocs.io/en/latest/instruction.html的代码的时候，可以import paddle.fluid，但是不能import paddle_fl

**Comment by frankwhzhang** [comment]
https://github.com/PaddlePaddle/PaddleFL/blob/master/docs/source/examples/md/gru4rec_examples.md 需要Python setup.py install

**Comment by frankwhzhang** [comment]
git clone paddlefl
