### ISSUE TITLE
failed to build PaddlePaddle based on Python3.6.8

### ISSUE THREAD

**Issue by jeng1220** [PaddlePaddle/Paddle#20870]
**System information**

- PaddlePaddle version: 3b31b74
- OS Platform: Ubuntu 18.04.3 LTS
- Python version: 3.6.8
- CMake version: 3.12.1
- GCC version: 7.4.0
- CUDA version: 10.1
- Install method: build from source

**To Reproduce**

```bash
$ cmake -DWITH_PYTHON=ON -DPY_VERSION=3.6 \
    -DWITH_MKL=OFF  \
    -DWITH_TESTING=OFF \
    -DCMAKE_BUILD_TYPE=Release \
    -DWITH_GPU=ON \
    -DON_INFER=ON \
    -DTENSORRT_ROOT=/usr \
    -DCUDA_ARCH_NAME=Auto 
$ make -k -j8
```

**Describe your current behavior**

It threw error message and stop building process:
```
fatal: no tag exactly matches '3b31b74e205dcad70e4c09482dec1ed0eea83d60'
python/CMakeFiles/paddle_python.dir/build.make:904: recipe for target 'python/build/.timestamp' failed
make[2]: *** [python/build/.timestamp] Error 120
CMakeFiles/Makefile2:72032: recipe for target 'python/CMakeFiles/paddle_python.dir/all' failed
make[1]: *** [python/CMakeFiles/paddle_python.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2
```

If I change Python version to 2.7.15, it still will print the error message but building process keep going and can finish process to generate `paddlepaddle_gpu-0.0.0-cp27-cp27mu-linux_x86_64.whl`.
```
fatal: no tag exactly matches '3b31b74e205dcad70e4c09482dec1ed0eea83d60'
```

**Other info / logs**
Original discussion thread is #20786

**Comment by JiabinYang** [comment]
plz show us more log info, since these info is too limited for us to find what goes wrong.

**Comment by jeng1220** [comment]
@JiabinYang ,
That was all information I saw. Yes, this issue is really strange. I checked the file - `python/CMakeFiles/paddle_python.dir/build.make` which was generated by system but didn't find useful information either. What else information do you think may be helpful?

**Comment by jeng1220** [comment]
@JiabinYang ,
It supposedly has connection to 
https://github.com/PaddlePaddle/Paddle/blob/develop/python/CMakeLists.txt#L90
```cmake
add_custom_target(paddle_python ALL DEPENDS ${PADDLE_PYTHON_BUILD_DIR}/.timestamp)
```
Could anyone take a look?

**Comment by jeng1220** [comment]
@JiabinYang ,
I checked remaining file - `build/python/setup.py.log`. It showed that in Python 2.7.15, it threw following error but building process kept going.
```
package init file '/test/workspace/paddle/build27/python/paddle/libs/__init__.py' not found (or not a regular file)
```
On the other hand, Python 3.6.8 stopped the process. This may be the key.


### More log:

**Python 3.6.8**
```bash
running bdist_wheel
running build
running build_py
copying /test/workspace/paddle/build36/python/paddle/check_import_scipy.py -> build/lib.linux-x86_64-3.6/paddle
copying /test/workspace/paddle/build36/python/paddle/batch.py -> build/lib.linux-x86_64-3.6/paddle
copying /test/workspace/paddle/build36/python/paddle/version.py -> build/lib.linux-x86_64-3.6/paddle
copying /test/workspace/paddle/build36/python/paddle/__init__.py -> build/lib.linux-x86_64-3.6/paddle
copying /test/workspace/paddle/build36/python/paddle/compat.py -> build/lib.linux-x86_64-3.6/paddle
copying /test/workspace/paddle/build36/python/paddle/sysconfig.py -> build/lib.linux-x86_64-3.6/paddle
# It stopped so no more message
```

**Python 2.7.15**
```bash
running bdist_wheel
running build
running build_py
copying /test/workspace/paddle/build27/python/paddle/check_import_scipy.py -> build/lib.linux-x86_64-2.7/paddle
copying /test/workspace/paddle/build27/python/paddle/batch.py -> build/lib.linux-x86_64-2.7/paddle
copying /test/workspace/paddle/build27/python/paddle/version.py -> build/lib.linux-x86_64-2.7/paddle
copying /test/workspace/paddle/build27/python/paddle/__init__.py -> build/lib.linux-x86_64-2.7/paddle
copying /test/workspace/paddle/build27/python/paddle/compat.py -> build/lib.linux-x86_64-2.7/paddle
copying /test/workspace/paddle/build27/python/paddle/sysconfig.py -> build/lib.linux-x86_64-2.7/paddle
package init file '/test/workspace/paddle/build27/python/paddle/libs/__init__.py' not found (or not a regular file)
copying /test/workspace/paddle/build27/python/paddle/utils/preprocess_util.py -> build/lib.linux-x86_64-2.7/paddle/utils
copying /test/workspace/paddle/build27/python/paddle/utils/preprocess_img.py -> build/lib.linux-x86_64-2.7/paddle/utils
copying /test/workspace/paddle/build27/python/paddle/utils/plot.py -> build/lib.linux-x86_64-2.7/paddle/utils
copying /test/workspace/paddle/build27/python/paddle/utils/image_util.py -> build/lib.linux-x86_64-2.7/paddle/utils
copying /test/workspace/paddle/build27/python/paddle/utils/torch2paddle.py -> build/lib.linux-x86_64-2.7/paddle/utils
# Too much, remove middle part of message ...
adding 'paddlepaddle_gpu-0.0.0.data/purelib/paddle/include/third_party/threadpool/src/extern_threadpool/ThreadPool.h'
adding 'paddlepaddle_gpu-0.0.0.data/scripts/paddle'
adding 'paddlepaddle_gpu-0.0.0.dist-info/METADATA'
adding 'paddlepaddle_gpu-0.0.0.dist-info/WHEEL'
adding 'paddlepaddle_gpu-0.0.0.dist-info/top_level.txt'
adding 'paddlepaddle_gpu-0.0.0.dist-info/RECORD'
removing build/bdist.linux-x86_64/wheel
# Finish building process
```

**Comment by JiabinYang** [comment]
it seems not the place where the real error happened, try to search with key words `Error` and check if there are other error occurred before?

**Comment by zhhezhhe** [comment]
same problem!
```
fatal: no tag exactly matches '0b75a0c10bc3085ea8a964268d0290b7c137ea93'
package init file 'Paddle/build/python/paddle/libs/__init__.py' not found (or not a regular file)
Traceback (most recent call last):
  File "setup.py", line 397, in <module>
    'install': InstallCommand,
  File "/usr/lib64/python3.6/contextlib.py", line 88, in __exit__
    next(self.gen)
  File "setup.py", line 377, in redirect_stdout
    sys.stdout = origin_stdout
ValueError: underlying buffer has been detached
make[2]: *** [python/build/.timestamp] Error 1
make[1]: *** [python/CMakeFiles/paddle_python.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by JepsonWong** [comment]
> same problem!
> 
> ```
> fatal: no tag exactly matches '0b75a0c10bc3085ea8a964268d0290b7c137ea93'
> package init file 'Paddle/build/python/paddle/libs/__init__.py' not found (or not a regular file)
> Traceback (most recent call last):
>   File "setup.py", line 397, in <module>
>     'install': InstallCommand,
>   File "/usr/lib64/python3.6/contextlib.py", line 88, in __exit__
>     next(self.gen)
>   File "setup.py", line 377, in redirect_stdout
>     sys.stdout = origin_stdout
> ValueError: underlying buffer has been detached
> make[2]: *** [python/build/.timestamp] Error 1
> make[1]: *** [python/CMakeFiles/paddle_python.dir/all] Error 2
> make: *** [all] Error 2
> ```

In order to reduce the log, paddle redirects unnecessary logs to the file, but this will cause problems in some minor versions of Python. **("ValueError: underlying buffer has been detached")**
This can be solved by deleting the code of the redirect part.
**Solution:**
1. Delete the redirection code in the **source directory** **python/setup.py.in** file.
**Remove the following code:**
![image](https://user-images.githubusercontent.com/16509038/70202153-c438c280-1753-11ea-985f-b45f968fac1c.png)
![image](https://user-images.githubusercontent.com/16509038/70202172-d74b9280-1753-11ea-9f5a-c1a1af200c78.png)
**Modify the following code:**
![image](https://user-images.githubusercontent.com/16509038/70202215-fd713280-1753-11ea-87e2-dcfc9c9f9e28.png)
2. Delete the build directory; create a new build directory; re-execute cmake, make commands.

**Comment by jeng1220** [comment]
@JepsonWong,
Thanks for the workaround.

@JiabinYang, @wzzju,
Could you fix this problem by robust way?

**Comment by JepsonWong** [comment]
> @JepsonWong,
> Thanks for the workaround.
> 
> @JiabinYang, @wzzju,
> Could you fix this problem by robust way?

I have fixed it on develop branch.

**Comment by jeng1220** [comment]
confirm fix, close issue

**Comment by qixiaobo** [comment]
same problem here with compile in docker

python/CMakeFiles/paddle_python.dir/build.make:75: recipe for target '.timestamp' failed
make[2]: Leaving directory '/home/PaddleOCR/deploy/pdserving/Serving-0.9.0/build_server'
make[2]: *** [.timestamp] Error 1
make[1]: *** [python/CMakeFiles/paddle_python.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
CMakeFiles/Makefile2:1669: recipe for target 'python/CMakeFiles/paddle_python.dir/all' failed

**Comment by qixiaobo** [comment]
> same problem here with compile in docker
> 
> python/CMakeFiles/paddle_python.dir/build.make:75: recipe for target '.timestamp' failed make[2]: Leaving directory '/home/PaddleOCR/deploy/pdserving/Serving-0.9.0/build_server' make[2]: *** [.timestamp] Error 1 make[1]: *** [python/CMakeFiles/paddle_python.dir/all] Error 2 make[1]: *** Waiting for unfinished jobs.... CMakeFiles/Makefile2:1669: recipe for target 'python/CMakeFiles/paddle_python.dir/all' failed

Scanning dependencies of target paddle_python
[100%] Generating ../.timestamp
^[[91m/root/gopath/pkg/mod: warning: directory does not exist.
/root/gopath/pkg/mod/github.com/grpc-ecosystem/grpc-gateway@v1.15.2/third_party/googleapis: warning: directory does not exist.
^[[0m^[[91mgoogle/api/annotations.proto: File not found.
^[[0m^[[91mgateway.proto: Import "google/api/annotations.proto" was not found or had errors.
^[[0mpython/CMakeFiles/paddle_python.dir/build.make:75: recipe for target '.timestamp' failed
^[[91mmake[2]: *** [.timestamp] Error 1
^[[0mCMakeFiles/Makefile2:1669: recipe for target 'python/CMakeFiles/paddle_python.dir/all' failed
^[[91mmake[1]: *** [python/CMakeFiles/paddle_python.dir/all] Error 2
^[[0mMakefile:129: recipe for target 'all' failed
^[[91mmake: *** [all] Error 2

**Comment by tigflanker** [comment]
和楼上遇到了同样的问题：
python/CMakeFiles/paddle_python.dir/build.make:75: recipe for target '.timestamp' failed
make[2]: *** [.timestamp] Error 1
CMakeFiles/Makefile2:1668: recipe for target 'python/CMakeFiles/paddle_python.dir/all' failed
make[1]: *** [python/CMakeFiles/paddle_python.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
fatal: unable to access 'https://github.com/apache/incubator-brpc/': gnutls_handshake() failed: The TLS connection was non-properly terminated.
Cloning into 'extern_brpc'...
-- Had to git clone more than once:
          2 times.
Note: checking out '1.0.0-rc01'.
... 

Ubuntu16.04，Docker “registry.baidubce.com/paddlepaddle/serving:0.9.0-devel”，python3.7，setuptools 28.8.0，gcc version 8.2.0 (GCC)
感觉问题就反复出在这个点上：python/CMakeFiles/paddle_python.dir/build.make:75: recipe for target '.timestamp' failed
