### ISSUE TITLE
在hadoop上跑paddle预测程序报OMP问题

### ISSUE THREAD

**Issue by oyjxer** [PaddlePaddle/Paddle#20874]
在hadoop上跑paddle预测程序，报这个错，有什么解决办法？
<img width="404" alt="屏幕快照 2019-10-29 下午2 53 33" src="https://user-images.githubusercontent.com/16233945/67745706-e73ecb00-fa5f-11e9-81e8-cdf34cd04e40.png">

**Comment by wzzju** [comment]
您好！你可以在单机上做预测吗？不使用hadoop能正常运行paddle预测程序吗？

**Comment by oyjxer** [comment]
单机运行正常，是不是haddop缺少什么环境变量

**Comment by wzzju** [comment]
您好！请检查您们的hadoop环境。hadoop主要是为了给paddle训练提供数据或者模型参数吧，是否可以考虑使用nfs等功能将hadoop文件系统映射到本地呢。我们这边也没有使用hadoop运行paddle的先例。从错误日志来看，在加载模型的时侯就挂掉了。请您们再检查一下hadoop的配置吧。
