### ISSUE TITLE
测试机上安装paddlepaddle 1.5.0版，打包环境后在opera环境import出错

### ISSUE THREAD

**Issue by April0402** [PaddlePaddle/Paddle#20884]
环境信息：
PaddlePaddle版本：1.5.0
GPU信息：K40m, CUDA 9.0 CUDNN 7.3
系统环境：python版本 3.5.3

问题描述：
测试机上安装paddlepaddle 1.5.0版，打包整个python环境后在opera环境部署，import paddle 出错，具体错误见下图

![屏幕快照 2019-10-29 19 05 16](https://user-images.githubusercontent.com/9245641/67761852-131d7900-fa7f-11e9-8211-1ca7c006e356.png)

**Comment by April0402** [comment]
补充一下，测试机上正常，opera环境出错，GPU卡不一样，系统/GCC版本一样，不确定是否还有其他依赖

**Comment by wzzju** [comment]
您好！看了下，这个好像不是paddle的问题，是您打包后的python环境出错了，是在调用python的sqlite3的系统库时出错了。

**Comment by April0402** [comment]
> 您好！看了下，这个好像不是paddle的问题，是您打包后的python环境出错了，是在调用python的sqlite3的系统库时出错了。

这个应该怎么解决呢？我需要在厂内的opera容器里面使用paddlepaddle，需要一个准备好的python包，而不能在opera上pip安装

**Comment by xiangyubo** [comment]
> > 您好！看了下，这个好像不是paddle的问题，是您打包后的python环境出错了，是在调用python的sqlite3的系统库时出错了。
> 
> 这个应该怎么解决呢？我需要在厂内的opera容器里面使用paddlepaddle，需要一个准备好的python包，而不能在opera上pip安装

这个看起来是 opera 上的 python 缺少一个动态链接库，可能需要你把这个动态链接库也打包进去

**Comment by April0402** [comment]
> > > 您好！看了下，这个好像不是paddle的问题，是您打包后的python环境出错了，是在调用python的sqlite3的系统库时出错了。
> > 
> > 
> > 这个应该怎么解决呢？我需要在厂内的opera容器里面使用paddlepaddle，需要一个准备好的python包，而不能在opera上pip安装
> 
> 这个看起来是 opera 上的 python 缺少一个动态链接库，可能需要你把这个动态链接库也打包进去

确实是这样，把这个加进去之后已经ok了，感谢
