### ISSUE TITLE
使用多进程来预处理数据，各进程内存持续增长

### ISSUE THREAD

**Issue by yzhw9981** [PaddlePaddle/Paddle#20888]
paddlecloud平台GPU训练
由于预处理时间较长，GPU利用率低
参考yolov3的例子改造了多进程预处理数据，GPU利用率100%了，但是内存持续上升，迭代1000多个step后内存占用超过100G。

请帮忙看看
核心代码如下
reader:

ClfExample = namedtuple('ClfExample', ['doc', 'label', 'id'])
class PageClfReader(object):
    def __init__(self,
                 max_seq_len=512,
                 is_inference=False,
                 random_seed=None,
                 for_cn=True,
                 task_id=0):
        self.max_seq_len = max_seq_len
        self.is_inference = is_inference
        self.for_cn = for_cn
        self.task_id = task_id
        self.pad_id = 0
        self.total_seq_len = 0
        np.random.seed(random_seed)

        self.current_example = 0
        self.current_epoch = 0
        self.num_examples = 0

    def get_train_progress(self):
        """Gets progress for training phase."""
        return self.current_example, self.current_epoch
    
    def get_doc_feature(self, features):
        具体业务逻辑省略
        return final_feature
    
    def _general_reader(self, line):
        #if self.current_example % 1000 == 1:
        #    log.info("read " + str(self.current_example) + " examples")
        arr = line.strip('\n').split('\t')
        #log.info("Get line")
        doc_pb = Emb()
        doc_pb.ParseFromString(base64.b64decode(arr[0]))
        doc_emb = [list(sent.emb) for sent in doc_pb.sentences]
        doc_emb = self.get_doc_feature(doc_emb)
        self.total_seq_len += len(doc_emb)
        return ClfExample(
            doc = doc_emb,
            label = ("0" if arr[1] == "1" else "1"),
            id = self.current_example)
    
    def _multi_reader(self, dirname, epoch_num, filelist):
        for epoch in range(0, epoch_num):
            for fn in filelist:
                for line in gzip.open(dirname + '/' + fn):
                    yield self._general_reader(line)

    def _batch_generator(self, dirname, epoch_num, batch_size, file_list):
        batch_records = []
        index = 0
        example_reader = self._multi_reader(dirname, epoch_num, file_list)
        for example in example_reader:
            index += 1
            batch_records.append(example)
            if len(batch_records) >= batch_size:
                yield self._pad_batch_records(batch_records)
                batch_records = []
                self.total_seq_len = 0
        if len(batch_records) > 0:
            yield self._pad_batch_records(batch_records)
    
    def multi_data_generator(self, filename, epoch_num, batch_size, phase=None):
        def f():
            index = 0
            multi_process_worker = MultiProcessReader(worker_num=5)
            multi_process_reader = multi_process_worker.get_msg(self._batch_generator, filename, epoch_num, batch_size)
            for batch in multi_process_reader:
                index += batch_size
                if phase == "train":
                    self.current_example = index

                yield batch
        return f
        
    def _pad_batch_records(self, batch_records):
        batch_doc = [record.doc for record in batch_records]
        batch_doc_positions = [range(0, len(record.doc)) for record in batch_records]
        batch_doc_sent_ids = [[0,] + [1,] * (len(record.doc) - 1) for record in batch_records]
        batch_labels = [record.label for record in batch_records]
        batch_labels = np.array(batch_labels).astype("int64").reshape([-1, 1])

        # padding
        padded_doc_emb, input_mask_doc, seq_lens = pad_batch_data(
            batch_doc, pad_idx=self.pad_id, 
            return_input_mask=True, return_seq_lens=True,
            dim=len(batch_doc[0][0]),inst_paddle_type="float32")
        padded_doc_position = pad_batch_data(
            batch_doc_positions, pad_idx=self.pad_id)
        padded_doc_sent_ids = pad_batch_data(
            batch_doc_sent_ids, pad_idx=self.pad_id)

        return_list = [
            padded_doc_emb, padded_doc_position, padded_doc_sent_ids, input_mask_doc, seq_lens,
            batch_labels
            ]

        return return_list

MultiProcessReader类
import multiprocessing
import os
import gzip
import time
class MultiProcessReader(object):
    def __init__(self, worker_num):
        self.worker_num = worker_num

    def worker(self, queue_output, processor, dirname, files, epoch, batch_size, worker_id):
        filelist = []
        for j in range(len(files)):
            if j % self.worker_num == worker_id:
                filelist.append(files[j])
        print "worker " + str(worker_id) + " will solve " + str(filelist) + " , epoch " + str(epoch)
        batch_reader = processor(dirname, epoch, batch_size, filelist)
        for batch in batch_reader:
            queue_output.put(batch)
        queue_output.put('TERMINAL')
        print "worker " + str(worker_id) + " finished"

    def get_msg(self, processor, dirname, epoch, batch_size):
        files = os.listdir(dirname)
        print files
        output_queue = multiprocessing.Queue(maxsize=100)
        for i in range(self.worker_num):
            reader = multiprocessing.Process(target=self.worker, args=(
                output_queue, processor, dirname, files, epoch, batch_size, i))
            reader.start()
        count = 0
        batch_count = 0
        while True:
            msg = output_queue.get()
            batch_count += 1
            if batch_count % 1000 == 0:
                print "MultiProcessReader queue size " + str(output_queue.qsize())
            if msg == "TERMINAL":
                count = count + 1
                if count == self.worker_num:
                    break
            else:
                yield msg

**Comment by JiabinYang** [comment]
您可以算一下worker*queue_size*batch_size是不是超过了您的内存大小
