### ISSUE TITLE
paddle 有办法知道checkpoint哪些参数没有加载吗？

### ISSUE THREAD

**Issue by OleNet** [PaddlePaddle/Paddle#20889]
paddle 有办法知道checkpoint哪些参数没有加载吗？

**Comment by JiabinYang** [comment]
您使用的是什么接口呢来load的呢

**Comment by OleNet** [comment]
`fluid.io.load_vars`

https://github.com/PaddlePaddle/ERNIE/blob/develop/ernie/utils/init.py#L82

**Comment by JiabinYang** [comment]
`load_vars`是没有的，可以使用新的接口`fluid.load()`，https://www.paddlepaddle.org.cn/documentation/docs/zh/api_cn/io_cn/load_cn.html#paddle.fluid.io.load
里面会有提示
