### ISSUE TITLE
warpctc layers 报错

### ISSUE THREAD

**Issue by liushanshan07** [PaddlePaddle/Paddle#20890]
PaddleCheckError: Expected num_sequences == label_lod.size() - 1, but received num_sequences:4 != label_lod.size() - 1:3.
The number of sequences of Input(Logits) should be equal to that of Input(Label). at [/root/Paddle/paddle/fluid/operators/warpctc_op.h:175]
  [operator < warpctc > error]
W1030 13:04:32.244503  3505 init.cc:205] *** Aborted at 1572411872 (unix time) try "date -d @1572411872" if you are using GNU date ***
W1030 13:04:32.249402  3505 init.cc:205] PC: @                0x0 (unknown)
W1030 13:04:32.251507  3505 init.cc:205] *** SIGTERM (@0x1f400000914) received by PID 3505 (TID 0x7f20df9cc740) from PID 2324; stack trace: ***
W1030 13:04:32.251793  3505 init.cc:205]     @       0x38c040f130 (unknown)
W1030 13:04:32.252043  3505 init.cc:205]     @       0x38c040d7c0 (unknown)
W1030 13:04:32.253288  3505 init.cc:205]     @     0x7f20b8d402a1 semlock_acquire
W1030 13:04:32.255357  3505 init.cc:205]     @     0x7f20dfae11e5 PyEval_EvalFrameEx
W1030 13:04:32.257252  3505 init.cc:205]     @     0x7f20dfae2c3e PyEval_EvalCodeEx
W1030 13:04:32.259196  3505 init.cc:205]     @     0x7f20dfae21f7 PyEval_EvalFrameEx
W1030 13:04:32.261049  3505 init.cc:205]     @     0x7f20dfae2c3e PyEval_EvalCodeEx
W1030 13:04:32.262910  3505 init.cc:205]     @     0x7f20dfa5db68 function_call
W1030 13:04:32.264778  3505 init.cc:205]     @     0x7f20dfa2de93 PyObject_Call
W1030 13:04:32.266641  3505 init.cc:205]     @     0x7f20dfadf886 PyEval_EvalFrameEx
W1030 13:04:32.268512  3505 init.cc:205]     @     0x7f20dfae2345 PyEval_EvalFrameEx
W1030 13:04:32.270372  3505 init.cc:205]     @     0x7f20dfae2345 PyEval_EvalFrameEx
W1030 13:04:32.272233  3505 init.cc:205]     @     0x7f20dfae2c3e PyEval_EvalCodeEx
W1030 13:04:32.273975  3505 init.cc:205]     @     0x7f20dfa5da61 function_call
W1030 13:04:32.275862  3505 init.cc:205]     @     0x7f20dfa2de93 PyObject_Call
W1030 13:04:32.277647  3505 init.cc:205]     @     0x7f20dfa4064f instancemethod_call
W1030 13:04:32.279565  3505 init.cc:205]     @     0x7f20dfa2de93 PyObject_Call
W1030 13:04:32.281370  3505 init.cc:205]     @     0x7f20dfa9de70 slot_tp_init
W1030 13:04:32.283164  3505 init.cc:205]     @     0x7f20dfa91568 type_call
W1030 13:04:32.284997  3505 init.cc:205]     @     0x7f20dfa2de93 PyObject_Call
W1030 13:04:32.286872  3505 init.cc:205]     @     0x7f20dfae080d PyEval_EvalFrameEx
W1030 13:04:32.288733  3505 init.cc:205]     @     0x7f20dfae2345 PyEval_EvalFrameEx
W1030 13:04:32.290618  3505 init.cc:205]     @     0x7f20dfae2c3e PyEval_EvalCodeEx
W1030 13:04:32.292491  3505 init.cc:205]     @     0x7f20dfae21f7 PyEval_EvalFrameEx
W1030 13:04:32.294270  3505 init.cc:205]     @     0x7f20dfa5239c gen_send_ex
W1030 13:04:32.296057  3505 init.cc:205]     @     0x7f20dfad46df builtin_next
W1030 13:04:32.297927  3505 init.cc:205]     @     0x7f20dfae11e5 PyEval_EvalFrameEx
W1030 13:04:32.299782  3505 init.cc:205]     @     0x7f20dfae2c3e PyEval_EvalCodeEx
W1030 13:04:32.301659  3505 init.cc:205]     @     0x7f20dfae21f7 PyEval_EvalFrameEx
W1030 13:04:32.303987  3505 init.cc:205]     @     0x7f20dfae2345 PyEval_EvalFrameEx
W1030 13:04:32.305837  3505 init.cc:205]     @     0x7f20dfae2c3e PyEval_EvalCodeEx
W1030 13:04:32.307691  3505 init.cc:205]     @     0x7f20dfae2d52 PyEval_EvalCode

**Comment by JiabinYang** [comment]
看起来是这个问题：:` Expected num_sequences == label_lod.size() - 1, but received num_sequences:4 != label_lod.size() - 1:3.`

**Comment by liushanshan07** [comment]
> 看起来是这个问题：:` Expected num_sequences == label_lod.size() - 1, but received num_sequences:4 != label_lod.size() - 1:3.`

嗯，我知道是这个问题。辛苦帮忙解读下，是哪个变量的啥东西没对上。

**Comment by JiabinYang** [comment]
`The number of sequences of Input(Logits) should be equal to that of Input(Label)`
