### ISSUE TITLE
Port Majel's important concepts to PaddlePaddle

### ISSUE THREAD

**Issue by wangkuiyi** [PaddlePaddle/Paddle#2089]
In an offline discussion, we believe that we need to rewrite `/paddle/math`, because, during the 4-year long evolution, many hacky changes accumulated.  

For example, initially, we only have class `Vector`. Later when we need 2D data structure, we added class `Matrix`. But neither Vector nor Matrix extends to higher dimensional.  This is obviously the right way to extend from 1D to 2D.  Instead, a new type `Tensor` should have been introduced at that time to replace class `Vector`.

Now we agree that in order to make our codebase readable, we'd have to do a significant rewrite work. And Majel is a good reference.

After talking with Greg Diamos, tech lead of Majel, we agree that instead of porting Majel as a whole bunch of code to PaddlePaddle, what we really need is to port concepts one-by-one.  This is because that

1. Not all concepts implemented in Majel is what PaddlePaddle needed.  For example, PaddlePaddle doesn't need the MPI support, as it has its own parameter servers.
1. Some concepts implemented in Majel should had been in some higher level libraries.  For example, Majel has `scheduler`, which queues kernel launches to make full use of the GPU pipeline.  But this should be implemented somewhere out of Majel indeed.
1. The PaddlePaddle team need to be able to maintain the source code, because Majel team doesn't yet have a plan to open source Majel.  Therefore, it would be great that PaddlePaddle team can write the required concepts again by taking Majel as a reference.

**Comment by wangkuiyi** [comment]
As a first step towards this goal, I am creating https://github.com/PaddlePaddle/Paddle/issues/2090 as an initial trial.

**Comment by gangliao** [comment]
We already here. Thanks, @wangkuiyi  Close this issue.
