### ISSUE TITLE
加载预训练词向量 trainable=False

### ISSUE THREAD

**Issue by gongel** [PaddlePaddle/Paddle#20908]
word_emb_pretrained = fluid.layers.embedding(
                     input=word,
                     size=[word_dict_len, 32],
                    dtype='float32',
                   is_sparse=IS_SPARSE,
                    param_attr=fluid.ParamAttr(
                        learning_rate=0, name="word_emb_pretrained", initializer=uniform_initializer,
                         trainable=False))

通过以上方式加载了预训练的词向量，并保证在下游任务中不被训练，请问怎么查看预训练词向量在训练中是否改变？谢谢

**Comment by JiabinYang** [comment]
可以在`executor`中传入embedding 参数 作为fetch var，每轮获取出来打印check

**Comment by gongel** [comment]
thx
