### ISSUE TITLE
Port a very basic concept in Majel to PaddlePaddle

### ISSUE THREAD

**Issue by wangkuiyi** [PaddlePaddle/Paddle#2090]
I went over the source code of Majel, and it seems that `Place` is a very basic concept and depends on nothing else. Let me try to port it to PaddlePaddle and explore what we need to do for more concepts.

**Comment by wangkuiyi** [comment]
Majel depends on boost heavily. I remember that was a discussion in Google C++ Style Guide that not every package in boost should be used.  But I tend to be lazy here by assuming that those used by Majel are "good" to use.

**Comment by qingqing01** [comment]
Here, `Place` means device?

**Comment by gangliao** [comment]
@wangkuiyi  It's better to replace boost using some light-weight implementation https://github.com/mapbox/variant since it's too heavily

**Comment by gangliao** [comment]
@qingqing01  yeah, `Place` means where is the allocated memory, it could be located in the host or heterogeneous devices.
