### ISSUE TITLE
Adam使用fleet.distributed_optimizer后损失完全没有下降，不使用时损失正常下降

### ISSUE THREAD

**Issue by yangzhifeng-code** [PaddlePaddle/Paddle#20940]
paddle fluid 1.6版本，我的代码使用了fleet的pserver训练方式，在MPI中运行，没有在paddlecloud中运行。提前将所有数据文件平均分给50个节点。训练的时候使用了fleet.distributed_optimizer的Adam优化器，但是每个batch损失不下降。我尝试过调整学习率（1.0~1e-4）、batch_size和gradient clip(10 ~ 0.01)，但是都没有效果。但是，当我不使用fleet.distributed_optimizer，直接用Adam优化时，每个batch损失下降。
所以，我应当怎样调整我的模型，还是fleet.distributed_optimizer这个方法有问题呢。

**Comment by seiriosPlus** [comment]
本地，小数据集有验证效果么？ 是否能收敛？

**Comment by yangzhifeng-code** [comment]
@seiriosPlus 本地小数据集损失会不断下降。

**Comment by yangzhifeng-stat** [comment]
@seiriosPlus 之前使用的fleet.distributed_optimizer的Adam，损失不变。我debug看过输出，二分类任务，最后一层的sigmoid输出，要么都在0.5附近，要么都是一个特别小的数，大概是1e-5还是多少这样子。也就是说，连续两个batch的输出在0.5和特别小的数之间交替，我开始考虑过可能是学习率太大或者gradient clip太大，但是后来我有设置过学习率1e-4，gradient clip 0.01都不行。

**Comment by yangzhifeng-code** [comment]
@seiriosPlus 二分类任务，使用fleet.distributed_optimizer，打印了最终sigmoid层的输出，发现学习率从0.001改到1.0，每个batch的梯度都是1.9e-5左右，输出都是0.5左右。似乎学习率对学习过程没有影响。

**Comment by yangzhifeng-code** [comment]
@seiriosPlus 请问这个怎么解决呢？

**Comment by seiriosPlus** [comment]
沟通后，发现用户使用的模式错误， 已经参考文档在重新训练
