### ISSUE TITLE
paddlecloud mpi fleet 训练结束时出core

### ISSUE THREAD

**Issue by maosengshulei** [PaddlePaddle/Paddle#20946]
- 版本、环境信息：
    1）PaddlePaddle版本：paddlepaddle1.5.1
    2）CPU：
   
模型训练完后出core：
`.//paddle/start_trainer.sh: line 162:  2830 Segmentation fault      (core dumped) python -u cluster_dnn_train.py`

mpi日志链接： http://10.76.127.43:8910/fileview.html?type=logsdir&path=/&instance=0.app-user-20191031192845-36931--shulei_msd_mmoe_dnn_v1_20191031_paddlecloud

**Comment by seiriosPlus** [comment]
用1.6.0
