### ISSUE TITLE
Can not automatically select the cudnn_conv or exconv in v2 API.

### ISSUE THREAD

**Issue by qingqing01** [PaddlePaddle/Paddle#2095]
v2之前版本会将use_gpu等一些全局变量传入config_parse.py，依据这些参数自动选择使用cudnn的conv/batchnorm， 还是普通实现conv/batchnorm。

v2 API中use_gpu这样的参数没有传入config_parse.py，失去了自动选择功能。

**Comment by lcy-seso** [comment]
我也遇到之前使用的同学报这个错误。

**Comment by qingqing01** [comment]
close since the v2 API has supported this feature.
