### ISSUE TITLE
请问池化操作如何mask

### ISSUE THREAD

**Issue by wang001** [PaddlePaddle/Paddle#20973]
假设我存在一个batch为4的矩阵如下：
[[1,2,3,4,5,6,-1e18,-1e18],
[7,8,9,10,-1e18,-1e18,-1e18,-1e18],
[1,2,3,4,5,6,7,8],
[11,12,-1e18,-1e18,-1e18,-1e18,-1e18,-1e18]]
其中-1e18是pad符号，我想对此数据进行均值池化，但是总会碰到pad符号，导致和pad相近的部分池化结果总是不正确。

**Comment by frankwhzhang** [comment]
https://www.paddlepaddle.org.cn/documentation/docs/zh/api_guides/low_level/layers/pooling.html#api-guide-pool 可以参考这里的文档

**Comment by wang001** [comment]
谢谢，sequence_pool函数貌似可用
