### ISSUE TITLE
文档“提交代码规范”

### ISSUE THREAD

**Issue by luotao1** [PaddlePaddle/Paddle#2098]
希望有个文档来说一下提交代码和根据review意见修改代码的一些约定。
包括但不限于：
1. review意见每条都要回复，同意并修改完的给个Done，其他的给自己的回复即可。
2. 如果review意见比较多，给个总体回复说所有意见都修改完了或其他。
3. 如果review意见比较多，建议采用start a review的方式来回复，直接每条回复会造成大量邮件。
4. 提交pr前请尽量注意一下commit数量，如果仅仅修改一个文件但提交了几十个commit，每个commit只做少量的修改，会给reviewer带来困扰。reviewer需要查看每个commit才能知道和上一个版本之间的区别。因此，为方便review，在两次review之间最好保持尽量少的commit，可以通过git commit --amend 补充上次commit。
5. 如果fix了某个issue，在pr的第一个comment框中加上：fix #XXX ，这样pr merge后会自动关闭对应的issue。
6. commit的名称尽量能反映pr的内容。
7. 请人review前，travis ci要已经通过了。如果ci没过，说明代码存在问题，会耗费reviewer的精力。

**Comment by gongweibao** [comment]
我的一个[总结](https://github.com/gongweibao/Paddle/blob/develop/doc/howto/dev/introduction_to_pr.md)，希望对大家有用
