### ISSUE TITLE
把model和params模型文件转成kv格式，嵌入服务时会报如下错误

### ISSUE THREAD

**Issue by superwj1990** [PaddlePaddle/Paddle#20980]
![f5a6578cd3d5cdd236d444372](https://user-images.githubusercontent.com/19602974/68084634-44c58400-fe73-11e9-9aa4-4d5c2ffe333e.jpg)
![e1d7cf873faa34fe6a2716c91](https://user-images.githubusercontent.com/19602974/68084636-48f1a180-fe73-11e9-9ba5-9456048fcab9.jpg)

**Comment by superwj1990** [comment]
已解决，是部分版本paddle在保存inference model时会在最后面加上一层scale层，把其注释掉就可以了。

**Comment by Xreki** [comment]
这个是`identify_scale_op_clean_pass`有bug，你们是自己从源码编译的Paddle？这个pass在最新的Paddle中已经移除了，即使用最新的Paddle应该不会再出现这个错误。

**Comment by gavin1332** [comment]
https://github.com/PaddlePaddle/Paddle/blob/394edd8647ece5cb47f0ac78ae2e43117ceed0c0/python/paddle/fluid/io.py#L1140
As user save model with interface `save_inference_model`, a unexpected op `scale` will be inserted into model, which causes failure in some inference phase.
