### ISSUE TITLE
blazeface使用mkldnn进行预测时报错

### ISSUE THREAD

**Issue by ceci3** [PaddlePaddle/Paddle#20998]
paddle版本：develop

预测脚本数据和模型：

[infer_blazenas_mkldnn.zip](https://github.com/PaddlePaddle/Paddle/files/3803772/infer_blazenas_mkldnn.zip)

报错信息：
![Uploading 屏幕快照 2019-11-04 下午7.35.36.png…]()
<img width="726" alt="屏幕快照 2019-11-04 下午7 35 54" src="https://user-images.githubusercontent.com/29245900/68118208-5d4ca180-ff3a-11e9-8f62-42797607051e.png">
<img width="1437" alt="屏幕快照 2019-11-04 下午7 36 06" src="https://user-images.githubusercontent.com/29245900/68118212-5faefb80-ff3a-11e9-84f9-a7c7dc1181f0.png">

CPU信息：
```
processor	: 0
vendor_id	: GenuineIntel
cpu family	: 6
model		: 85
model name	: Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz
stepping	: 4
microcode	: 0x1
cpu MHz		: 2399.994
cache size	: 4096 KB
physical id	: 0
siblings	: 1
core id		: 0
cpu cores	: 1
apicid		: 0
initial apicid	: 0
fpu		: yes
fpu_exception	: yes
cpuid level	: 13
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon rep_good nopl eagerfpu pni pclmulqdq ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch arat fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm mpx avx512f rdseed adx smap avx512cd xsaveopt xsavec xgetbv1
bogomips	: 4799.98
clflush size	: 64
cache_alignment	: 64
address sizes	: 40 bits physical, 48 bits virtual
power management:
```

**Comment by luotao1** [comment]
@bingyanghuang Could you help see it?

**Comment by wojtuss** [comment]
@ceci3 , could you please provide us with a command for reproducing the error?

**Comment by ceci3** [comment]
1. change the image_path='0_Parade_Parade_0_102.jpg' and model_path='blazeface_nas'
2. python infer_time.py
@wojtuss

**Comment by wojtuss** [comment]
@ceci3 , I have found a reproducing script in the .zip file. The issue is under investigation now.

**Comment by wojtuss** [comment]
@ceci3 , @luotao1 , @bingyanghuang 
A fix is submitted: https://github.com/PaddlePaddle/Paddle/pull/21059
