### ISSUE TITLE
修改SSD目标检测模型，训练时报错“AssertionError: Not compiled with data parallel”

### ISSUE THREAD

**Issue by XDUXK** [PaddlePaddle/Paddle#21000]
**【版本环境信息】**：paddle版本1.6，环境Mac OS 10.14，python版本3.7.0
**【模型名称】**：SSD模型（原型在https://github.com/PaddlePaddle/models/tree/develop/PaddleCV/ssd）
**【数据集】**：没做修改，也是SSD模型的数据集
**【问题描述】**：
我有一个需求，其需要用到目标检测模型ssd，但是其尚无法支持py_reader并且只支持SGD优化器，所以，我将SSD的原有模型（https://github.com/PaddlePaddle/models/tree/develop/PaddleCV/ssd） 进行了修改，主要修改点为：
**1**. 在trainer.py中，将优化器改为SGD
**2**. 在trainer.py中，将py_reader改为使用普通reader，然后在exe.run里面进行feed
**3**. 由于paddle1.6之后，fluid.layers.data接口发生了改变(似乎是建议不再使用)，加上上述2中所述修改，所以在mobilenet_ssd.py中，添加了fluid.data接口定义的变量（用法参考了1.6下multi_box_head的API代码示例）

我按照原有SSD模型的训练命令“python -u train.py --batch_size=64 --dataset=pascalvoc --pretrained_model=pretrained/ssd_mobilenet_v1_coco/”开始训练，结果报错“AssertionError: Not compiled with data parallel”。不知道是哪里出了问题啊？

已将改动的代码文件放在了附件**ssd_revised_code.zip**内：
[ssd_revised_code.zip](https://github.com/PaddlePaddle/Paddle/files/3803893/ssd_revised_code.zip)

**Comment by Xreki** [comment]
你训练时参数`--parallel`的值应该是false，所以走的普通的executor，是单CPU or GPU训练。看出错地方的源码：

https://github.com/PaddlePaddle/Paddle/blob/bf379fef961319ed213df7193cf7bd3997f0c095/python/paddle/fluid/executor.py#L830-L837

你改了feed部分，而且你传的feed是一个list，单CPU or GPU训练时，feed list的长度只能为1，且feed list的每一个成员为一个dict。

这里的报错信息很不合理啊，请@luotao1 @chenwhql 知晓。另外希望Python端的assert也能像PADDLE_ENFORCE一样打印出对比的数据详情。

**Comment by Xreki** [comment]
请问这个issue和https://github.com/PaddlePaddle/PaddleFL/issues/7 是同一个问题吗？

**Comment by XDUXK** [comment]
> 你训练时参数`--parallel`的值应该是false，所以走的普通的executor，是单CPU or GPU训练。看出错地方的源码：
> 
> https://github.com/PaddlePaddle/Paddle/blob/bf379fef961319ed213df7193cf7bd3997f0c095/python/paddle/fluid/executor.py#L830-L837
> 
> 你改了feed部分，而且你传的feed是一个list，单CPU or GPU训练时，feed list的长度只能为1，且feed list的每一个成员为一个dict。
> 
> 这里的报错信息很不合理啊，请@luotao1 @chenwhql 知晓。另外希望Python端的assert也能像PADDLE_ENFORCE一样打印出对比的数据详情。

是的，我这里只有一个CPU，--parallel的值是false。那请问下，我应该怎么改feed部分？



> 请问这个issue和[PaddlePaddle/PaddleFL#7](https://github.com/PaddlePaddle/PaddleFL/issues/7) 是同一个问题吗？

差不多是同一个，后面那个issue是在前一个修改的基础上，进一步改成了联邦学习FL的训练方式，看报错信息是一样的，所以感觉应该是相同的原因吧

**Comment by Xreki** [comment]
> 我应该怎么改feed部分？

当你传的feed是一个list，单CPU or GPU训练时，feed list的长度只能为1，且feed list的每一个成员为一个dict，例如
```python
feed=[{"x":x, "y":y}]
```

你也可以直接传一个dict，即
```python
feed={"x":x, "y":y}
```

**Comment by XDUXK** [comment]
> > 我应该怎么改feed部分？
> 
> 当你传的feed是一个list，单CPU or GPU训练时，feed list的长度只能为1，且feed list的每一个成员为一个dict，例如
> 
> ```python
> feed=[{"x":x, "y":y}]
> ```
> 
> 你也可以直接传一个dict，即
> 
> ```python
> feed={"x":x, "y":y}
> ```

那是不是就是说，给feed传递的数据只能是一个“样本+标签”，不能传一个batch的数据？
我这里是不是需要把trainer.py里面的trainer_reader改了？现在输出np.shape(data)结果是（16，4）
```python
    for epoc_id in range(epoc_num):
        train_reader = reader.train(data_args,
                                train_file_list,
                                batch_size_per_device,
                                shuffle=is_shuffle,
                                use_multiprocess=args.use_multiprocess,
                                num_workers=num_workers,
                                enable_ce=enable_ce)
        # train_py_reader.decorate_paddle_reader(train_reader)
        epoch_idx = epoc_id + 1
        start_time = time.time()
        prev_start_time = start_time
        every_epoc_loss = []
        batch_id = 0
        # train_py_reader.start()
        # while True:
        for data in train_reader():
            if epoc_id == 0:
                print(np.shape(data))
```

**Comment by Xreki** [comment]
这个无论是你在reader里面改，或者是在别的里面改，只要按照给定的格式传入batch数据就行。可以参考这个示例：

https://github.com/PaddlePaddle/models/blob/a4d7a2e4924e20c3fcc5dc87f2faea1530a47d55/PaddleNLP/language_model/train.py#L288-L302
