### ISSUE TITLE
paddle.1.4.1 split tensor梯度问题

### ISSUE THREAD

**Issue by CLeafYeah** [PaddlePaddle/Paddle#21010]
![image](https://user-images.githubusercontent.com/11695656/68176826-3a190500-ffc1-11e9-9477-d16cead6935e.png)
![image](https://user-images.githubusercontent.com/11695656/68176846-456c3080-ffc1-11e9-9a36-be2219ed9dc2.png)

**Comment by shippingwang** [comment]
- 1.4 要set_persistable = true
- 建议升级paddle版本
