### ISSUE TITLE
模型量化KeyError

### ISSUE THREAD

**Issue by dubhex** [PaddlePaddle/Paddle#21020]
使用1.5.2版本paddle进行模型int8量化，参照官方示例量化代码，运行时报错

> Traceback (most recent call last):
  File "src/trainQuant.py", line 127, in <module>
    main()
  File "src/trainQuant.py", line 124, in main
    eval(args)
  File "src/trainQuant.py", line 79, in eval
    freeze_pass.apply(test_graph)
  File "/home/vis/guohanqi/workspace/facelmkQuant_Paddle/env_Paddle1.52/lib/python3.6/site-packages/paddle/fluid/contrib/slim/quantization/quantization_pass.py", line 641, in apply
    self._insert_post_dequant_op(graph, op_node)
  File "/home/vis/guohanqi/workspace/facelmkQuant_Paddle/env_Paddle1.52/lib/python3.6/site-packages/paddle/fluid/contrib/slim/quantization/quantization_pass.py", line 740, in _insert_post_dequant_op
    scale_v = self._var_scale_map[original_var_name]
KeyError: 'conv2d_14.w_0'

模型是1.3版本的paddle训练的，确定可以使用。想请问这个问题该如何解决？

**Comment by slf12** [comment]
请问QuantizationTransformPass这个pass可以运行成功吗？方便贴一下代码吗？QuantizationFreezePass 这个对graph只能运行一次，您是不是多次调用了这个pass？

**Comment by dubhex** [comment]
> 请问QuantizationTransformPass这个pass可以运行成功吗？方便贴一下代码吗？QuantizationFreezePass 这个对graph只能运行一次，您是不是多次调用了这个pass？

> def eval(args):
    # parameters from arguments

    place = fluid.CUDAPlace(0) if args.use_gpu else fluid.CPUPlace()
    exe = fluid.Executor(place)

    val_program, feed_names, fetch_targets = fluid.io.load_inference_model(args.model_path,
                                      exe,
                                      model_filename="model",
                                      params_filename="params")
    val_reader = paddle.batch(reader.val(args), batch_size=100)
    feeder = fluid.DataFeeder(place=place, feed_list=feed_names, program=val_program)

    results=[]
    for batch_id, data in enumerate(val_reader()):
        # print("data: ", len(data), data[0].shape)

        # top1_acc, top5_acc
        result = exe.run(val_program,
                          feed=feeder.feed(data),
                          fetch_list=fetch_targets)
        # result = [np.mean(r) for r in result]
        # results.append(result)
    # result = np.mean(np.array(results), axis=0)

    print("freeze the graph for inference")
    test_graph = IrGraph(core.Graph(val_program.desc), for_test=True)

    freeze_pass = QuantizationFreezePass(
            scope=fluid.global_scope(),
            place=place,
            weight_quantize_type=args.weight_quant_type)
    freeze_pass.apply(test_graph)
    server_program = test_graph.to_program()
    fluid.io.save_inference_model(
            dirname=os.path.join(args.save_path, 'float'),
            feeded_var_names=feed_names,
            target_vars=fetch_targets,
            executor=exe,
            main_program=server_program,
            model_filename='model',
            params_filename='weights')

    print("convert the weights into int8 type")
    convert_int8_pass = ConvertToInt8Pass(
            scope=fluid.global_scope(),
            place=place)
    convert_int8_pass.apply(test_graph)
    server_int8_program = test_graph.to_program()
    fluid.io.save_inference_model(
            dirname=os.path.join(args.save_path, 'int8'),
            feeded_var_names=feed_names,
            target_vars=fetch_targets,
            executor=exe,
            main_program=server_int8_program,
            model_filename='model',
            params_filename='weights')
   
    print("convert the freezed pass to paddle-lite execution")
    mobile_pass = TransformForMobilePass()
    mobile_pass.apply(test_graph)
    mobile_program = test_graph.to_program()
    fluid.io.save_inference_model(
            dirname=os.path.join(args.save_path, 'mobile'),
            feeded_var_names=feed_names,
            target_vars=fetch_targets,
            executor=exe,
            main_program=mobile_program,
            model_filename='model',
            params_filename='weights')
    return

def main():
    args = parser.parse_args()
    # print_arguments(args)
    eval(args)

    if __name__ == '__main__':
        main()

基本就是用的样例代码， 在QuantizationFreezePass这里就出问题了

**Comment by slf12** [comment]
> > 请问QuantizationTransformPass这个pass可以运行成功吗？方便贴一下代码吗？QuantizationFreezePass 这个对graph只能运行一次，您是不是多次调用了这个pass？

> ```
> 
> def main():
> args = parser.parse_args()
> # print_arguments(args)
> eval(args)
> 
> ```
> if __name__ == '__main__':
>     main()
> ```
> 
> 基本就是用的样例代码， 在QuantizationFreezePass这里就出问题了

load的inference model是经过QuantizationTransformPass之后保存的模型吗？IrGraph有个接口draw可以把graph保存在pdf里
def draw(self, save_path, name, marked_nodes=None, remove_ctr_var=True):
        """
        Draw the graph. If `dot` command is installed, the drawn graph
        will be saved as pdf file type, otherwise dot file type is used.

        Args:
            save_path(str): the save path of drawn graph.
            name(str): the name of drawn graph.
            marked_nodes(set(IrNode)): nodes that are needed to be marked.
            Default value is None.
            remove_ctr_var(bool): If it is set True, all control variable nodes
            in the graph will be removed. Default value is True.
        """
您可以用这个接口来看下test_graph是不是可以进行freeze
