### ISSUE TITLE
force_init_on_cpu 这个api的作用是什么？

### ISSUE THREAD

**Issue by DDDivano** [PaddlePaddle/Paddle#21021]
文档链接：https://www.paddlepaddle.org.cn/documentation/docs/zh/api_cn/initializer_cn/force_init_on_cpu_cn.html
文档中说：该接口获得一个是否强制在CPU上初始化变量的布尔型标志位。返回：状态，是否应强制在CPU上强制进行变量初始化

第一句话该如何理解？是指我用这个api他就会强制在CPU上初始化变量吗？但是我用的时候他返回的是false。
第二句话是意思是说这个api返回值告诉我是否应该强制在cpu上进行初始化吗？但是他是根据什么判断我是不是应该在cpu上进行初始化的呢？

**Comment by shippingwang** [comment]
``` 
import paddle
import paddle.fluid as fluid
from paddle.fluid.initializer import init_on_cpu
with init_on_cpu():
    print(paddle.fluid.initializer.force_init_on_cpu())
```

```bash
True
```
这么做看下

**Comment by DDDivano** [comment]
> ```
> import paddle
> import paddle.fluid as fluid
> from paddle.fluid.initializer import init_on_cpu
> with init_on_cpu():
>     print(paddle.fluid.initializer.force_init_on_cpu())
> ```
> 
> ```shell
> True
> ```
> 
> 这么做看下

我知道这样是返回True，那问题是我使用`with init_on_cpu():`这个代码后为啥还要用`paddle.fluid.initializer.force_init_on_cpu()`来判断我是不是要用cpu？
