### ISSUE TITLE
_finalize_strategy_and_create_passes问题

### ISSUE THREAD

**Issue by Mryangkaitong** [PaddlePaddle/Paddle#21039]
想使用paddle 1.6的batch merge功能，仿照给的demo (https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/fluid/tests/unittests/test_dist_base.py#L285) :
![图片](https://user-images.githubusercontent.com/23132307/68271725-7a998100-009c-11ea-802a-b34c9e7e5e18.png)

写了自己的程序
[图片]

结果报错：
[图片]

请问这个怎么解决？谢谢

**Comment by heavengate** [comment]
和 https://github.com/PaddlePaddle/Paddle/issues/21040 是同一问题，当前issue关闭，由https://github.com/PaddlePaddle/Paddle/issues/21040 跟踪
