### ISSUE TITLE
XavierInitializer初始化器中 fan_in 和 fan_out如何使用？

### ISSUE THREAD

**Issue by DDDivano** [PaddlePaddle/Paddle#21035]
https://www.paddlepaddle.org.cn/documentation/docs/zh/api_cn/initializer_cn/XavierInitializer_cn.html

文档中说这个参数会从变量中推断，那是否代表这个参数应该是个唯一确定值，自己指定其他的值会出错？
![image](https://user-images.githubusercontent.com/10734244/68267313-f8559080-008c-11ea-8d11-ea6f0d603a2a.png)

**Comment by heavengate** [comment]
可以指定，如果指定了就用指定的值，如果没指定就从变量中推断
![fan](https://user-images.githubusercontent.com/12605721/68271580-f2b37700-009b-11ea-9450-83122b5430b0.png)
![屏幕快照 2019-11-06 下午1 47 43](https://user-images.githubusercontent.com/12605721/68271605-07900a80-009c-11ea-9097-f882161c5b8e.png)
