### ISSUE TITLE
_finalize_strategy_and_create_passes 问题

### ISSUE THREAD

**Issue by Mryangkaitong** [PaddlePaddle/Paddle#21040]
想使用paddle 1.6的batch merge功能，仿照给的demo (https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/fluid/tests/unittests/test_dist_base.py#L285) :
![图片](https://user-images.githubusercontent.com/23132307/68271725-7a998100-009c-11ea-802a-b34c9e7e5e18.png)

写了自己的程序
![图片](https://user-images.githubusercontent.com/23132307/68271944-2ba01b80-009d-11ea-96d2-0e6aad7fbbcc.png)

结果报错：
![图片](https://user-images.githubusercontent.com/23132307/68271863-f4316f00-009c-11ea-8653-9360639b7071.png)

请问这个怎么解决？谢谢

**Comment by heavengate** [comment]
`_finalize_strategy_and_create_pass`是`BuildStrategy`的接口，需要用`BuildStrategy`对象调用，你的代码中误用了`ExecuteStrategy`
