### ISSUE TITLE
麻烦看一下DecayedAdagradOptimizer的参数decay是否没有生效？

### ISSUE THREAD

**Issue by baomengxue** [PaddlePaddle/Paddle#21047]
- 版本、环境信息：
    1）PaddlePaddle版本：
安装的whl包为：paddlepaddle-1.6.1-cp37-cp37m-macosx_10_6_intel.whl 

- 问题描述：
根据文档描述https://www.paddlepaddle.org.cn/documentation/docs/zh/1.6/api_cn/optimizer_cn/DecayedAdagradOptimizer_cn.html
fluid.optimizer.DecayedAdagradOptimizer的参数decay默认值为0.95
![image](https://user-images.githubusercontent.com/19708914/68277837-05817800-00ab-11ea-9c95-9ed35a982ddd.png)
设置参数decay=0.1后
![image](https://user-images.githubusercontent.com/19708914/68277754-d7039d00-00aa-11ea-9b3c-95a168bbbda2.png)

**Comment by heavengate** [comment]
多跑几轮看看，moment是记录grad的，第一轮decay不会影响到moment

**Comment by baomengxue** [comment]
@heavengate 
moment是通过公式（moment_out=decay∗moment+(1−decay)∗grad∗grad）记录grad，对吧
循环5次，每次打印moment的值在decay=0.95和decay=0.1时的值是一样的
![image](https://user-images.githubusercontent.com/19708914/68286428-0cfd4d00-00bc-11ea-8e6b-2da809902fde.png)

![image](https://user-images.githubusercontent.com/19708914/68286438-125a9780-00bc-11ea-99c9-42d054dcd77f.png)

您看一下呐？
还有请问一下：为什么第一轮decay不会影响到moment呐？

**Comment by heavengate** [comment]
可以fetch`fc_0.w_0_moment_1`试下

**Comment by baomengxue** [comment]
> 可以fetch`fc_0.w_0_moment_1`试下

Cannot find fetch variable in scope, fetch_var_name is fc_0.w_0_moment_1

https://github.com/PaddlePaddle/Paddle/blob/53f1e024d4dcffe76d5b8b7a996eb7ed2ac802cd/python/paddle/fluid/optimizer.py#L1895处decay是否应该作为attrs传入呐？麻烦看下

**Comment by heavengate** [comment]
感谢反馈，这里应该有bug，我们马上修复下
