### ISSUE TITLE
What's mean of period in submit argments

### ISSUE THREAD

**Issue by wangsouc** [PaddlePaddle/Paddle#2105]
What's mean of **period** in submit argments:

like below:

```
python cluster_train \
  --config test/mnist/mnist_cluster_job.py \
  --use_gpu gpu \
  --time_limit 00:30:00 \
  --submitter xxx \
  --num_nodes 2 \
  --job_priority normal \
  --trainer_count 4 \
  --num_passes 1 \
  --log_period 1000 \
  --dot_period 100 \
  --saving_period 1 \
```

**Comment by typhoonzero** [comment]
- log_period: interval of printing logs.
- dot_period: interval of printing dots to stdout. print dot to screen helps us to know that the program is still running.

**Comment by wangsouc** [comment]
how to measure the interval，default batch?

**Comment by typhoonzero** [comment]
Yep. intervals are measured by the number of batches.
