### ISSUE TITLE
V1.6版本中使用 fluid.layers.ssd_loss  API报错过于简单

### ISSUE THREAD

**Issue by GT-ZhangAcer** [PaddlePaddle/Paddle#21055]
V1.6.0 post107版本

在该版本中该API的报错信息不如其他的表现好，感觉可以调整一下，因为输入了很多参数但不能给出具体是哪个参数出现的错误。
如果能给出具体的报错信息，或者是计算这个损失函数中哪个环节上出现的问题就可以很好定位了，如果单纯给出下图报错，静态图下调试有点略难ಥ_ಥ。
![图片](https://user-images.githubusercontent.com/46156734/68292186-48047e00-00c6-11ea-866f-a8d3f7a7524f.png)

![图片](https://user-images.githubusercontent.com/46156734/68292227-64081f80-00c6-11ea-99db-e65076c9d309.png)

**Comment by heavengate** [comment]
上述报错信息在`softmax_with_cross_entropy`截图上下应该会有具体报错信息和调用栈，可以找一下或者把全量报错的截图贴上

**Comment by luotao1** [comment]
https://github.com/PaddlePaddle/Paddle/blob/a71d8fdb876038f1d896357068488e3987d0b7ad/paddle/fluid/operators/math/cross_entropy.cc#L56
确实这里没加报错语句，我们会增强下的。

**Comment by GT-ZhangAcer** [comment]
Debug了一下，发现是在multi_box_head的API中base_size参数与传入的图像尺寸值相差过大而产生的错误。但报错却只显示是计算loss的API所在行有错。如果能体现出multi_box_head的错误，或者是ssd_loss的某个参数有问题，可能在Debug时候更轻松一些。

**Comment by GT-ZhangAcer** [comment]
感谢官方解答，谢谢
