### ISSUE TITLE
paddle.infer output multiple outputs

### ISSUE THREAD

**Issue by pengwangucla** [PaddlePaddle/Paddle#2107]
For paddle api v2,

The infer is only for a single output: 
```
gen_result=paddle.infer(
    output_layer=beam_gen,
    parameters=parameters,
    input=gen_data, 
    field=['id', 'value'])
```
Even for multiple fields,  what should I do if I want to simultaneously obtain multiple outputs from layer1 and layer2, is it possible to upgrade the function as 

```
gen_result=paddle.infer(
    output_layer=[beam_gen1, beam_gen2],
    parameters=parameters,
    input=gen_data, 
    field=['id', 'value'])
```

Also set the gen results to be a list. 

@reyoung @luotao1

**Comment by lcy-seso** [comment]
Hi @pengwangucla  the last large modification of C++ code of beam search is made by me. There are some restrictions on getting the output of a layer in `recurrent_layer_group`.

In the old version (v1),  this can be done by directly put the layer you need in "output of the recurrent layer group", just like you do in the above example. I am not sure whether it works in V2 version. I will check it.

**Comment by lcy-seso** [comment]
I check the C++ codes. I am still not sure whether the v2 infer function can return multiple outputs. But, currently, in the C++ codes, except the first output of beam search (the generated sequence), the other output can be any layer defined in the step function, **but only the top1 result during beam search is returned**.

**Comment by lcy-seso** [comment]
@luotao1 has told me, v2 can print multiple outputs.

I find you use beam search as an example. Beam search is implemented in recurrent layer group, that works very different from others layers in PaddlePaddle.

I guess you do not want outputs of multiples layers in recurrent layer group, but just want to get outputs of more than one layers?

**Comment by pengwangucla** [comment]
> I guess you do not want outputs of multiples layers in recurrent layer group, but just want to get outputs of more than one layers of a network not implemented by recurrent layer group?

I just use beam search as an example,  I just need to output different intermedia output inside a forward network. 

So is the usage the same as I wrote ? just put a list for output_layer ?

**Comment by luotao1** [comment]
@pengwangucla You usage as follows is correct.
```
gen_result=paddle.infer(
    output_layer=[beam_gen1, beam_gen2],
    parameters=parameters,
    input=gen_data, 
    field=['id', 'value'])
```
You can run `print gen_result` to see the result. And the final print order of result is:
`beam_gen1.id, beam_gen2.id, beam_gen1.value, beam_gen2.value`

I will add the usage of multiple outputs in the annotation of `paddle.infer`.
