### ISSUE TITLE
how to close stat log in mpi cluster trainning

### ISSUE THREAD

**Issue by wangsouc** [PaddlePaddle/Paddle#2108]
massive **stat log** produced in mpi cluster trainning，show to close it?

train_arg is:
`train_arg="--port=${use_port} --ports_num=1 --local=0 --dot_period=100 --saving_period=1 --log_period=100 --trainer_count=16 --num_passes=5 --ports_num_for_sparse=1 --local=0"`
test_arg is:
`test_arg="--port=${use_port} --ports_num=1 --distribute_test=0 --job=test --test_pass=0 --test_wait=1 --dot_period=1 --log_period=1000 --saving_period=1 --num_passes=100 --start_pserver=0"`

```
I0512 08:28:23.170152  3608 Stat.cpp:129] ======= StatSet: [GlobalStatInfo] status ======
I0512 08:28:23.170193  3608 Stat.cpp:132] Stat=AucEvaluator                   TID=3608   total=24.217     avg=0.007      max=0.146      min=0.002      count=3200      
I0512 08:28:23.170213  3608 Stat.cpp:132] Stat=client_send                    TID=5638   total=67.141     avg=0.012      max=1.082      min=0.001      
.
.
.
count=3100      
                                          Stat=FwMulTimer                     TID=4196   total=31555.2    avg=10.179     max=108.819    min=0.001      count=3100      
                                          Stat=FwMulTimer                     TID=4188   total=31587.8    avg=10.189     max=101.223    min=0.002      count=3100      
I0512 08:28:23.173894  3608 Stat.cpp:140] ======= BarrierStatSet status ======
I0512 08:28:23.173904  3608 Stat.cpp:153] --------------------------------------------------

```

**Comment by lcy-seso** [comment]
This is due to you compile PaddlePaddle with set `-DWITH_TIME=True`, which is often used in profiling.

If you do not need this information, you can re-compile the source code with `-DWITH_TIME=False`.
