### ISSUE TITLE
PADDLEPADDLE如何搭建一个resnet呢

### ISSUE THREAD

**Issue by HoyTiger** [PaddlePaddle/Paddle#21098]
我想使用paddlepaddle做一唇语的识别，唇语的视频已经切片，并提取了嘴部，请问我该怎么取搭建这个网络呢？

**Comment by SunGaofeng** [comment]
resnet的实现请参考下面这个代码：
https://github.com/PaddlePaddle/models/blob/develop/PaddleCV/image_classification/models/resnet.py
