### ISSUE TITLE
fluid1.5 采用paddlecloud 集群训练后 将模型数据文件下载到本地 用线上c++加载报错 

### ISSUE THREAD

**Issue by lizhiqings** [PaddlePaddle/Paddle#21108]
terminate called after throwing an instance of 'paddle::platform::EnforceNotMet'
  what():  Cannot get attribute height_sections by type std::vector<int, std::allocator<int> >, its type is std::vector<long, std::allocator<long> > at [baidu/paddlepaddle/paddle/paddle/fluid/framework/attribute.h:42]
PaddlePaddle Call Stacks: 
0             0xa01c87p
1             0xa03395p
2             0xad740ep
3             0xadb334p
4            0x13e12f1p
5            0x13e1460p
6            0x13b3879p
7             0xa089e9p
8             0xa095b4p
9             0xa09d01p
10            0x745513p
11            0x749d51p
12            0x74ae49p rankdnn_para_fluid_deepfm_reloader_v1(char const*, RankDnnBatchFluidDeepFmParaV1*&) + 121
13            0x6e963ep
14            0x6de6b4p
15            0x6e4c18p
16           0x14b2321p
17           0x14b2a29p RunTaskOnMultiThread(void*) + 9
18           0x2d3fa0ap bthread::TaskGroup::task_runner(long) + 266
19           0x2d37121p

*** Aborted at 1573455484 (unix time) try "date -d @1573455484" if you are using GNU date ***
PC: @                0x0 (unknown)
*** SIGABRT (@0x1f4000037bf) received by PID 14271 (TID 0x7ffb032f9700) from PID 14271; stack trace: ***
    @     0x7ffb62ffe160 (unknown)
    @     0x7ffb4d9793f7 __GI_raise
    @     0x7ffb4d97a7d8 __GI_abort
    @     0x7ffb4e269c65 __gnu_cxx::__verbose_terminate_handler()
    @     0x7ffb4e267e06 __cxxabiv1::__terminate()
    @     0x7ffb4e267e33 std::terminate()
    @     0x7ffb4e268052 __cxa_throw
    @           0xad7483 _ZNK6paddle9framework16ExtractAttributeISt6vectorIiSaIiEEEclERN5boost7variantINS6_5blankEJifSsS4_S2_IfSaIfEES2_ISsSaISsEEbS2_IbSaIbEEPNS0_9BlockDescElS2_ISG_SaISG_EES2_IlSaIlEEEEE
    @           0xadb334 _ZNK6paddle9framework16TypedAttrCheckerISt6vectorIiSaIiEEEclEPSt13unordered_mapISsN5boost7variantINS7_5blankEJifSsS4_S2_IfSaIfEES2_ISsSaISsEEbS2_IbSaIbEEPNS0_9BlockDescElS2_ISH_SaISH_EES2_IlSaIlEEEEESt4hashISsESt8equal_toISsESaISt4pairIKSsSM_EEE
    @          0x13e12f1 paddle::framework::OpRegistry::CreateOp()
    @          0x13e1460 paddle::framework::OpRegistry::CreateOp()
    @          0x13b3879 paddle::framework::Executor::Prepare()
    @           0xa089e9 paddle::NativePaddlePredictor::Init()
    @           0xa095b4 paddle::CreatePaddlePredictor<>()
    @           0xa09d01 paddle::CreatePaddlePredictor<>()
    @           0x745513 RankDnnBatchFluidDeepFmParaV1::_init_predict_machines()
    @           0x749d51 RankDnnBatchFluidDeepFmParaV1::init()
    @           0x74ae49 rankdnn_para_fluid_deepfm_reloader_v1()
    @           0x6e963e wsy::HotLoader<>::reload()
    @           0x6de6b4 _ZNSt17_Function_handlerIFvvEZN13HotCollection11Global_InitEvEUlvE16_E9_M_invokeERKSt9_Any_data
    @           0x6e4c18 HotObjectLoadThread::run()
    @          0x14b2321 RunTask()
    @          0x14b2a29 RunTaskOnMultiThread()
    @          0x2d3fa0a bthread::TaskGroup::task_runner()
    @          0x2d37121 bthread_make_fcontext

**Comment by sandyhouse** [comment]
请参见报错代码

> terminate called after throwing an instance of 'paddle::platform::EnforceNotMet'
> what():` Cannot get attribute height_sections by type std::vector<int, std::allocator >, its type is 
> std::vector<long, std::allocator >

**Comment by sandyhouse** [comment]
Closing this issue. Reopen it if you have any further question.
