### ISSUE TITLE
Windows10下安装CPU版的C++预测库，编译成功，但无结果输出

### ISSUE THREAD

**Issue by Jockmx** [PaddlePaddle/Paddle#21106]
参考文档：
1.https://www.paddlepaddle.org.cn/documentation/docs/zh/advanced_usage/deploy/inference/windows_cpp_inference.html
2.https://github.com/sjtubinlong/PaddleSolution/tree/master/deploy
    1）PaddlePaddle版本：在官网上下载的最新的1.6版本的预测库cpu_avx_mkl
    2）CPU：Ryzen 2500u
    3）Windows10下使用VS2015编译

我在使用官方提供的cpu预测库编译通过，但始终无法输出结果。
编译结果如下：
![image](https://user-images.githubusercontent.com/38597491/68566178-903dea80-0490-11ea-9c21-2f923f622b4d.png)
我使用官方提供的命令进行预测（路径已按照自己的进行修改）：seg_demo.exe --conf=/path/to/your/conf --input_dir=/path/to/your/input/data/directory
预测始终无反应，后来我用cout的方式定位到错误，发现在使用YAML::LoadFile加载配置文件的时候并没有正确执行，到这一步后，程序就会自动断开。
![image](https://user-images.githubusercontent.com/38597491/68566673-f6773d00-0491-11ea-9393-b2de932f428b.png)
![image](https://user-images.githubusercontent.com/38597491/68566713-1ad31980-0492-11ea-9e90-b4d5669a8b8f.png)
这是为什么，我看到编译的过程中YAML也是成功编译的，但是就是使用不了。。。

**Comment by OliverLPH** [comment]
看起来有可能是yaml文件的路径不对。

可以检查下 yaml的路径是否完全正确，也可以试下对路径加引号
```
seg_demo.exe --conf="D:\\projects\\PaddleSeg\\inference\\conf\\humanseg.yaml" --input_dir="D:\\projects\\PaddleSeg\\inference\\images\humanseg\\"
```

**Comment by Jockmx** [comment]
谢谢，我有检测过我的yaml的路径，是没有问题的。
![image](https://user-images.githubusercontent.com/38597491/68569059-26c1da00-0498-11ea-9abb-ee62aa45bc21.png)
![image](https://user-images.githubusercontent.com/38597491/68569086-36d9b980-0498-11ea-9b9f-2da5a174a8c5.png)

**Comment by Jockmx** [comment]
我十分确定就是YAML的loadfile这步出了问题，但是不知道怎么解决。：(
前一步都可以正确的输出yaml路径。
![image](https://user-images.githubusercontent.com/38597491/68571175-62ab6e00-049d-11ea-9a19-1bbafe707cdb.png)
这个是我的yaml详细参数，莫非是我参数错了？
![image](https://user-images.githubusercontent.com/38597491/68571281-9b4b4780-049d-11ea-850d-abf0cd7d475d.png)

**Comment by silingtong123** [comment]
> 我十分确定就是YAML的loadfile这步出了问题，但是不知道怎么解决。：(
> 前一步都可以正确的输出yaml路径。
> ![image](https://user-images.githubusercontent.com/38597491/68571175-62ab6e00-049d-11ea-9a19-1bbafe707cdb.png)
> 这个是我的yaml详细参数，莫非是我参数错了？
> ![image](https://user-images.githubusercontent.com/38597491/68571281-9b4b4780-049d-11ea-850d-abf0cd7d475d.png)


windows环境下需要将yaml文件中MODLE_PATH里的单反斜杠改为双反斜杠，如下
![image](https://user-images.githubusercontent.com/35439432/68653747-5986d380-0567-11ea-8fb9-d6560a66eec0.png)

**Comment by Jockmx** [comment]
谢谢谢谢，我居然忽略了这一点，十分感谢。
