### ISSUE TITLE
在训练SSD模型中，若detection_output没有输出框，则使用metrics.DetectionMAP会报错

### ISSUE THREAD

**Issue by GT-ZhangAcer** [PaddlePaddle/Paddle#21102]
PaddlePaddle V1.6.1
GPU 107环境

在训练SSD模型中，正常情况下则会像下方那样输出
![图片](https://user-images.githubusercontent.com/46156734/68544349-40621380-03fd-11ea-90bb-a4c7401ca4ea.png)

但如果detection_output没有输出框（不知道是不是没有输出框的原因），则输出的数据会变成这样
![图片](https://user-images.githubusercontent.com/46156734/68544348-39d39c00-03fd-11ea-9214-8a72d8130d17.png)

如果出现这种情况，metrics.DetectionMAP则会报维度不一致错误
![图片](https://user-images.githubusercontent.com/46156734/68544357-55d73d80-03fd-11ea-87a3-8c5224d4dcc6.png)

在训练一些较为难训练的数据集，而且还不使用预训练模型的情况下，这个报错不是很好能避免...

**Comment by jerrywgz** [comment]
https://github.com/PaddlePaddle/PaddleDetection/blob/master/ppdet/modeling/architectures/mask_rcnn.py#L240 可以参考下这里的代码，使用switch判断detection_output的维度是否符合预期，符合预期则使用DetectionMAP，否则就附值为0或者其他值

**Comment by GT-ZhangAcer** [comment]
> https://github.com/PaddlePaddle/PaddleDetection/blob/master/ppdet/modeling/architectures/mask_rcnn.py#L240 可以参考下这里的代码，使用switch判断detection_output的维度是否符合预期，符合预期则使用DetectionMAP，否则就附值为0或者其他值

非常感谢！
