### ISSUE TITLE
没有支持numpy中的repeat操作的算子

### ISSUE THREAD

**Issue by Weili-NLP** [PaddlePaddle/Paddle#21101]
模型库中缺乏支持numpy中的repeat操作的算子

例如：
x = np.array([[1,2],
                       [3,4]])
y = np.repeat(x, [1, 2], axis=1)
array([[1, 2, 2],
           [3, 4, 4]])

**Comment by hutuxian** [comment]
您好，paddle暂时没有提供这个OP，我们会加入需求列表~
