### ISSUE TITLE
Windows无法编译paddle的MKLDNN版本32位

### ISSUE THREAD

**Issue by zhwesky2010** [PaddlePaddle/Paddle#21109]
编译问题：
（电脑配置）Windows10 / Visual Studio 2015

在Windows下编译Paddle的32位版本：
1. cmake配置为：
cmake .. -G "Visual Studio 14 2015 Win64" -A Win32 -DWITH_GPU=ON -DWITH_TESTING=OFF -DCMAKE_BUILD_TYPE=Release -DWITH_MKL=ON

2. 编译paddle.sln，发现在编译外部依赖extern_mkldnn时出现error。

3. 单独下载[mkldnn](https://github.com/intel/mkl-dnn.git)项目进行编译
发现在此处报错：

[该文件路径](https://github.com/intel/mkl-dnn/blob/master/CMakeLists.txt) 第69行

<img width="484" alt="MacHi 2019-11-11 15-49-17" src="https://user-images.githubusercontent.com/52485244/68570190-01829b00-049b-11ea-9596-2f8107b0b40a.png">

问题：

如果我需要编译32位的Paddle，且-DWITH_MKL=ON，能否有办法？MKLDNN是否无法支持32位Windows编译？

（已知：-DWITH_MKL=OFF时，则无此问题）

**Comment by luotao1** [comment]
@bingyanghuang Could you help see it?

**Comment by bingyanghuang** [comment]
@zhouwei25 我跟我们的工程师确认了一下， MKL-DNN不支持32位的环境，所有MKL-DNN的JIT/汇编的代码都是64位的。
