### ISSUE TITLE
麻烦看一下AdamOptimizer结果与官网公式计算得出的结果不一样？

### ISSUE THREAD

**Issue by baomengxue** [PaddlePaddle/Paddle#21110]
版本、环境信息：
   1）PaddlePaddle版本：
安装的whl包为：paddlepaddle-1.6.1-cp37-cp37m-macosx_10_6_intel.whl

AdamOptimizer
https://www.paddlepaddle.org.cn/documentation/docs/zh/1.6/api_cn/optimizer_cn/AdamOptimizer_cn.html

![image](https://user-images.githubusercontent.com/19708914/68571245-866eb400-049d-11ea-8adf-4e74f776bb58.png)

**Comment by baomengxue** [comment]
learning_rate的更新规则源码与官网描述不一致？
源码：
https://github.com/PaddlePaddle/Paddle/blob/35f17ae28f292a602274a93d0398286c3b0f1afb/paddle/fluid/operators/optimizers/adam_op.h#L163 

官网公式：
![image](https://user-images.githubusercontent.com/19708914/68578375-d3a65200-04ac-11ea-8a51-c1ebd18dcfc8.png)

**Comment by sandyhouse** [comment]
你好，看代码里面的注释已经更新，并且和代码的实现是一致的。可能文档还没来得及修复，我给相关同学反馈修复下，感谢您反馈。
![image](https://user-images.githubusercontent.com/6737864/68638506-ba4ce680-053c-11ea-85de-14fd15501317.png)
