### ISSUE TITLE
range op返回数据的shape有问题

### ISSUE THREAD

**Issue by Ashleychen** [PaddlePaddle/Paddle#21113]
在用range op的时候发现当start和end之间的间隔很大(我用的是20000263)的时候，返回的数据shape有问题，返回的range的shape为[20000264,]，当start和end之间的间隔较小(如200多)的时候则不会出现这个问题。
我看官网的说明是说：
<img width="751" alt="Screen Shot 2019-11-11 at 5 18 58 PM" src="https://user-images.githubusercontent.com/4193110/68575680-88d60b80-04a7-11ea-9b24-1be9d3759211.png">
但是我的step并不是浮点数。以下给出了一个demo，可直接运行。
```
import numpy
import paddle.fluid as fluid

#data_size=20000263
#data_size=20000259
data_size=259
data = fluid.layers.data(name="data", shape=[data_size, 1], dtype="int64")
test = fluid.layers.range(0, data_size, 1, dtype='int64')
fluid.layers.Print(input=test, summarize=0)
pred = fluid.layers.cast(x=test, dtype='float32')
pred = fluid.layers.reshape(x=pred, shape=[-1, 1])
pred = fluid.layers.fc(pred, size=1)
loss = fluid.layers.reduce_mean(pred)
optimizer = fluid.optimizer.SGD(learning_rate=1e-3)
optimizer.minimize(loss)
place = fluid.CPUPlace()
exe = fluid.Executor(place=place)
exe.run(fluid.default_startup_program())
tensor = fluid.core.LoDTensor()
tensor.set(numpy.zeros((data_size, 1), dtype='int64').reshape([-1, 1]), fluid.CPUPlace())
results = exe.run(fluid.default_main_program(), feed={'data': tensor},
        fetch_list=pred, return_numpy=False)
```
请问为什么会出现这个问题，是不是bug，如果不是bug的话要怎么绕过这个问题？

**Comment by Ashleychen** [comment]
暂时用slice op绕过了，不过还是麻烦解释一下。

**Comment by slf12** [comment]
> 暂时用slice op绕过了，不过还是麻烦解释一下。

您好，目前定位到是fill_constant op的问题，range 使用了这个op，具体问题在排查中。

感谢您的反馈。

**Comment by wangchaochaohu** [comment]
fill_constant 目前看来对输入较大的数字存在问题  
```
import paddle.fluid as fluid
import numpy as np

result = fluid.layers.fill_constant(dtype="float32", value=30000265, shape=[1])
exe = fluid.Executor(fluid.CPUPlace())
exe.run(fluid.default_startup_program())
all_result, = exe.run(fetch_list=[result])
print(all_result)
```

打印结果是30000264

目前已经查明  30000265和30000264在IEEE 74标准中 float中表示是相同的


![image](https://user-images.githubusercontent.com/13411999/68828386-6da21080-06e0-11ea-9a31-09c8a2eb84c7.png)
Tensorflow 在float32中也有类似的问题，
我们需要解决的是float64的情况下数据表示的正确性
