### ISSUE TITLE
concat未运行时强制检查报错

### ISSUE THREAD

**Issue by littletomatodonkey** [PaddlePaddle/Paddle#21128]
使用resize_bilinear对不同的feature map进行resize之后（actual shape指定实际形状），进行concat，concat编译时提示shape不对，但是在实际运行的时候是可以保证size对齐的，想问下在编译时就得得保证concat的所有feature map的size是一致的吗？

**Comment by ceci3** [comment]
是的，在编译阶段需要保持一致

**Comment by littletomatodonkey** [comment]
嗯嗯好的，但是这样就得保证使用resize op的时候，scale和actual shape能够完全对上是吧（比如说编译时shape需要完全是32或者是64的整数倍等）？我看elemwise_add等op没有这样的检查，是否可以去掉concat的编译shape检查呢？

**Comment by ceci3** [comment]
resize_bilinear这个OP,scale和actual shape只要输入一个就可以了，不需要两个都有

**Comment by ceci3** [comment]
resize_bilinear这个op里，使用output_shape指定值是构图时候检查用的，实际运行时生效的是actual shape这个参数。只要指定好output_shape保证构图时候检查通过就行，scale和output_shape指定一个就可以了，out_shape的优先级高于scale。

**Comment by littletomatodonkey** [comment]
嗯嗯，我试了一下，是可以的，多谢！有个建议，文档里的表述似乎有点矛盾~https://www.paddlepaddle.org.cn/documentation/docs/zh/api_cn/layers_cn/resize_bilinear_cn.html#resize-bilinear
![image](https://user-images.githubusercontent.com/14270174/68652312-2858d400-0564-11ea-8c22-d4231025b16d.png)

**Comment by ceci3** [comment]
好的，感谢~ 我反馈给相关同学
