### ISSUE TITLE
人脸检测输入为128和320时使用mkldnn进行预测速度比不用要慢

### ISSUE THREAD

**Issue by ceci3** [PaddlePaddle/Paddle#21123]
人脸检测输入为128和320时使用mkldnn进行预测速度比不用要慢
速度：
enable_mkldnn: 110.518ms/image
not mkldnn: 69.955ms/image

复现模型和代码（复现代码输入是320的）：
[blaze-lite320.zip](https://github.com/PaddlePaddle/Paddle/files/3834157/blaze-lite320.zip)

cpu信息：
Intel(R) Xeon(R) CPU E5-2650 v4 @ 2.20GHz

**Comment by luotao1** [comment]
补充下：batch_size=1, thread=1. This PR relates #20998. 
@bingyanghuang Could you help see it?

**Comment by wojtuss** [comment]
@ceci3 , for some reason a gemm:blas implementation is being chosen instead of a jit one for convolutions with MKL-DNN. I am investigating the problem.

**Comment by wojtuss** [comment]
@ceci3, the problem is the following: all the convolutions in the model have enforced NCHW data format, which makes the MKL-DNN unable to use faster jit AVX implementation and it falls back to the slower gemm implementation. As a resolution, please do not enforce the NCHW data format in the model.

**Comment by qingqing01** [comment]
@wojtuss  Do you mean we need to train a new mode by NHWC format?   Can the format conversion be optimized automatically during the inference by Pass?

**Comment by wojtuss** [comment]
@ceci3 , @qingqing01 , I mean for the model to be executed using MKL-DNN it is best to not specify the data format (or set it to `any` or `AnyLayout`). This way MKL-DNN can choose the best data format for the current hardware and environment configuration. The data format settings should not matter for training (done without MKL-DNN, I assume), so you can keep the trained weights and modify the model only. Actually, either of the two options should do the job now:

1. (quick) modify your python definition of the model (without setting the data format or setting it to `AnyLayout`) and save it again joining with already trained weights,
2. (more general, in case other models require the same modification) create a pass that can update data format in the operators which use MKL-DNN.

**Comment by qingqing01** [comment]
@wojtuss Actually, we don't set the data-fromat in the model, the defalut `data_format="NCHW"` is from the PaddlePaddle API.  We can try 1 at first.

**Comment by ceci3** [comment]
in paddle python file about conv2d layer, (https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/fluid/layers/nn.py#L1261 ) I need to get num_channels according to data_format, and use num_channels to create filter parameter, so it seems I cannot  set data_format to any..  @wojtuss

**Comment by wojtuss** [comment]
@ceci3 , @qingqing01 
After the latest changes by @jczaja (NHWC support, already merged to the `develop` branch), your problem seems to be resolved. Now, when I run the script with the latest `develop` Paddle branch, a `jit:avx512` implementation is being used for convolution, and on my machine the test shows that with MKL-DNN enabled the performance is 2x better then with MKL-DNN disabled. Please, confirm if the issue is resolved on your machine as well.

**Comment by bingyanghuang** [comment]
@qingqing01 @luotao1 Can this issue be closed?

**Comment by ceci3** [comment]
test result in Paddle 1.7:
enable mkldnn: 48.5534977913 ms per image
disable mkldnn: 65.4569602013 ms per image
cpu: Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz 

enable mkldnn is faster, so close this pr.
