### ISSUE TITLE
DetectionMAP这个OP怎么使用？

### ISSUE THREAD

**Issue by DDDivano** [PaddlePaddle/Paddle#21129]
能否给个能run起来的样例？
https://www.paddlepaddle.org.cn/documentation/docs/zh/api_cn/metrics_cn/DetectionMAP_cn.html
官方这个代码实例没有构造数据，自己构造之后报维度错误，能否给一份能run的样例？

**Comment by jerrywgz** [comment]
https://github.com/PaddlePaddle/models/blob/develop/PaddleCV/ssd/train.py#L136 可以参考ssd中的使用方式

**Comment by ceci3** [comment]
fluid.layers.data如果第一维不是-1的话会自动添加上一个batch size维度，如果想指定batch size维度的话需要添加一个参数append_batch_size=False或者用fluid.data这个OP，需要修改官网示例代码
