### ISSUE TITLE
chain API函数到底应该返回什么？

### ISSUE THREAD

**Issue by DDDivano** [PaddlePaddle/Paddle#21148]
官网API链接：https://www.paddlepaddle.org.cn/documentation/docs/zh/api_cn/io_cn/chain_cn.html

![image](https://user-images.githubusercontent.com/10734244/68729738-bb961600-0605-11ea-9ee3-e7c0b5461dac.png)
按照1部分所说，我理解的是同时读取三个reader的数据合成了一份数据返回，数据结构有更改，按照实际使用情况2部分所说，看起来像是简单的reader的顺序累计成一个reader并逐条返回，数据本身没有更改。所以这个函数到底应该是什么样？（2图里的函数也写错了）

**Comment by FDInSky** [comment]
这个例子比较简单，你可以试一下读一个多维度的数看看，返回的跟1部分是吻合的。

**Comment by DDDivano** [comment]
> 这个例子比较简单，你可以试一下读一个多维度的数看看，返回的跟1部分是吻合的。

事实是2部分是正常的，就是简单的把reader串在一起读取了

**Comment by juncaipeng** [comment]
> > 这个例子比较简单，你可以试一下读一个多维度的数看看，返回的跟1部分是吻合的。
> 
> 事实是2部分是正常的，就是简单的把reader串在一起读取了

是的，源码是使用itertools.chain将多个reader串联，然后进行迭代读取
