### ISSUE TITLE
关于ZeroCopyTensor中的SetLoD问题

### ISSUE THREAD

**Issue by xiuechen** [PaddlePaddle/Paddle#21156]
void SetLoD(const std::vector<std::vector<size_t>>& x);
在这个tensor中需要输入一个二维数组const std::vector<std::vector<size_t>>& x

之前在nativeconfig预测的时候，某个输入tensor（batch_size，每个batch column个元素）的lod是这么设置的。能够正常预测：

                std::vector<uint64_t> lods;
                for (uint32_t j=0;j<=batch_size;j++)
                {
                        lods.emplace_back(j*column);
                }
                tensor.lod.emplace_back(std::move(lods));

请教改为analysisconfig后该如何设置这个LOD

**Comment by FDInSky** [comment]
同样的方式就可以
