### ISSUE TITLE
V1.6版本distributed.launch模块的参数默认值设置与描述不一致

### ISSUE THREAD

**Issue by kexinzhao** [PaddlePaddle/Paddle#21155]
1.6版本的distributed.launch模块新增加了一个参数: `use_paddlecloud`
https://github.com/PaddlePaddle/Paddle/blob/release/1.6/python/paddle/distributed/launch.py#L96-L100

这个bool type参数的default="False", 从描述上看是想设置成默认False，但是因为输入是一个"False"的string，所有非空string都会被认为是True. 所以实际的默认值是True。

这个设置导致我在非paddle cloud上训练时，再次提交训练任务时出错。
改成default=False就没问题了。

**Comment by FDInSky** [comment]
多谢反馈，我们会及时修改

**Comment by danleifeng** [comment]
已修改  #21168   
加入了store_true, 如果不用paddlecloud 就不需要设置`use_paddlecloud`这个参数。
