### ISSUE TITLE
softmax_with_cross_entropy CPU/GPU版本实现不一致

### ISSUE THREAD

**Issue by wangxicoding** [PaddlePaddle/Paddle#21154]
https://github.com/PaddlePaddle/Paddle/blob/fff270eacd83384ad9a62db1af38d7db65dd2cd3/paddle/fluid/operators/softmax_with_cross_entropy_op.h#L59-L63
GPU版本是按照合并简化后公式（下图）实现的，CPU版本目前还是按照softmax + cross_entropy分开的方式计算，需要按合并简化后的公式计算，提升数值稳定性。
![image](https://user-images.githubusercontent.com/10208305/68732700-3e01e400-05cc-11ea-80f4-b728b9c8a9ac.png)

**Comment by FDInSky** [comment]
多谢反馈，我们会及时跟进的

**Comment by FDInSky** [comment]
https://github.com/PaddlePaddle/Paddle/issues/20994 参考这里
