### ISSUE TITLE
关于对于fc的op关于偏置初始化疑问？

### ISSUE THREAD

**Issue by Wahaha1314** [PaddlePaddle/Paddle#21150]
您好，我有一个疑惑就是用fc接口时候，我看官方文档，他对偏置的初始化是全0？如果全0的化，后面的反向更新那不就不更新了？这偏置不就没有意义了吗？为什么他不采用默认初始化全1   还是我理解错了？还有就是如果要对偏置进行配置为初始化全1，该如何操作。

**Comment by FDInSky** [comment]
![image](https://user-images.githubusercontent.com/48318485/68741339-50aa0680-0628-11ea-9372-451b8aac00c0.png)
初始值为0，但梯度不等于0，也可以更新

**Comment by GT-ZhangAcer** [comment]
插眼，看看有没有其它回答
