### ISSUE TITLE
用PaddlePaddle和Tensorflow实现经典CNN网络Vgg

### ISSUE THREAD

**Issue by kerwinner** [PaddlePaddle/Paddle#21167]
Vgg的优势

与AlexNet相比：

相同点

整体结构分五层；

除softmax层外，最后几层为全连接层；

五层之间通过max pooling连接。

不同点

使用3×3的小卷积核代替7×7大卷积核，网络构建的比较深；

由于LRN太耗费计算资源，性价比不高，所以被去掉；

采用了更多的feature map，能够提取更多的特征，从而能够做更多特征的组合。

**Comment by FDInSky** [comment]
请问你的问题是什么？

**Comment by kerwinner** [comment]
误操作，请忽略。
