### ISSUE TITLE
c++预测sample无法运行

### ISSUE THREAD

**Issue by thunder95** [PaddlePaddle/Paddle#21171]
求助，不知道哪里弄错了

环境:
ubuntu：16.04
gcc：5.4
下载的预测库1.6：[预测库压缩包](https://paddle-inference-lib.bj.bcebos.com/1.6.0-gpu-cuda10-cudnn7-avx-mkl-trt5/fluid_inference.tgz)
运行测试的sample: [下载的sample](https://www.paddlepaddle.org.cn/documentation/docs/zh/advanced_usage/deploy/inference/native_infer.html#C++%E9%A2%84%E6%B5%8B%E6%A0%B7%E4%BE%8B%E7%BC%96%E8%AF%91%E6%B5%8B%E8%AF%95)

遇到的问题：
1. 当使用下面的方式就会报错：
`config->SetModel(FLAGS_dirname + "/model", FLAGS_dirname + "/params");`

```
In function `paddle::PrepareTRTConfig(paddle::AnalysisConfig*, int)':
/home/hl/tests/paddle_inference/sample/inference/mobilenet_v2.cc:22: undefined reference to `paddle::AnalysisConfig::SetModel(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
collect2: error: ld returned 1 exit status
```
2. 当使用下面的方式，无论是否开启gpu，都在DisableGPU或EnableUseGpu处中断执行
```
 config->SetProgFile(FLAGS_dirname + "/model");
 config->SetParamsFile(FLAGS_dirname + "/params");
 config->DisableGpu();		 
 //config->EnableUseGpu(100, 0);
```

`Signal: SIGSEGV (Segmentation fault)`

3. 若直接加载模型文件夹，情况同2：
`config->SetModel("./mobilenetv1");`

**Comment by joey12300** [comment]
应该是编译器的问题。你下载的预测库是用gcc4.8编译的，所以你得使用gcc4.8来编译。建议你将gcc和g++都降级为4.8。可使用下面的命令实现降级。
```
sudo apt-get install gcc-4.8 g++-4.8
sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.8 100
sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 100
```

**Comment by thunder95** [comment]
> 应该是编译器的问题。你下载的预测库是用gcc4.8编译的，所以你得使用gcc4.8来编译。建议你将gcc和g++都降级为4.8。可使用下面的命令实现降级。
> 
> ```
> sudo apt-get install gcc-4.8 g++-4.8
> sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.8 100
> sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 100
> ```

非常感谢回复，按照您给的命令实现了降级，但还是同样的问题。
gcc version 4.8.5 (Ubuntu 4.8.5-4ubuntu2)

**Comment by thunder95** [comment]
> 应该是编译器的问题。你下载的预测库是用gcc4.8编译的，所以你得使用gcc4.8来编译。建议你将gcc和g++都降级为4.8。可使用下面的命令实现降级。
> 
> ```
> sudo apt-get install gcc-4.8 g++-4.8
> sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.8 100
> sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 100
> ```

非常感谢，降级gcc后，这步没有报错了。
