### ISSUE TITLE
k8s里面调用模型的时候daemon-kubelet[4173]: W1113  error while getting gpu utilization: nvml: Not Supported

### ISSUE THREAD

**Issue by jinjin123** [PaddlePaddle/Paddle#21175]
- 标题：daemon-kubelet[4173]: W1113  error while getting gpu utilization: nvml: Not Supported
- 版本、环境信息：
    1）PaddlePaddle版本：docker镜像paddlepaddle/paddle:latest-gpu-cuda10.0-cudnn7
    2）CPU/GPU：如果您使用GPU训练，GPU驱动版本: 418，CUDA: 10.0 ，cuDNN版本号：7
    3）系统环境：宿主机ubuntu 18.04 docker镜像paddlepaddle/paddle:latest-gpu-cuda10.0-cudnn7
    4）Python版本号: 2.7.12
    5）显存信息
root@ai:/usr/include# nvidia-smi
Wed Nov 13 14:54:57 2019
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 418.87.00    Driver Version: 418.87.00    CUDA Version: 10.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 650...  On   | 00000000:02:00.0 N/A |                  N/A |
| 30%   36C    P8    N/A /  N/A |    233MiB /  1991MiB |     N/A      Default |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0                    Not Supported                                       |
+-----------------------------------------------------------------------------+
- 复现信息：Ubuntu18.04 下载docker镜像paddlepaddle/paddle:latest-gpu-cuda10.0-cudnn7，之后用k8s 挂载GPU进去    
spec:
      hostname: ai
      containers:
      - name: ai
        image: localhost:32000/ai:latest
        resources:
          limits:
            nvidia.com/gpu: 1
之后调用训练好的ernie模型，查看宿主机tail -f /var/log/syslog 
- 问题描述：请详细描述您的问题，同步贴出报错信息、日志/代码关键片段
使用官方最新的gpu镜像 paddlepaddle/paddle:latest-gpu-cuda10.0-cudnn7，然后k8s挂载gpu进去,基于GPU调用模型
错误:
Nov 13 22:55:41 jimmy-bigserver microk8s.daemon-kubelet[4173]: W1113 22:55:41.191568    4173 container.go:507] Failed to update stats for container "/kubepods/besteffort/pod545853d8-0496-11ea-a922-f2cd03415023/c900cd71ed291959ad12d6fe553cb2483a0664b14233576a7d7e380bb6326e1b": error while getting gpu utilization: nvml: Not Supported
Nov 13 22:55:50 jimmy-bigserver microk8s.daemon-kubelet[4173]: W1113 22:55:50.096809    4173 container.go:507] Failed to update stats for container "/kubepods/besteffort/pod1364300b-061e-11ea-8efe-f2cd03415023/c7060e9b09eacb7ef349cba9705668a5474a4b777c1d62025496c2779786362f": error while getting gpu utilization: nvml: Not Supported
Nov 13 22:57:01 jimmy-bigserver microk8s.daemon-kubelet[4173]: W1113 22:57:01.341081    4173 container.go:507] Failed to update stats for container "/kubepods/besteffort/pod1364300b-061e-11ea-8efe-f2cd03415023/c7060e9b09eacb7ef349cba9705668a5474a4b777c1d62025496c2779786362f": error while getting gpu utilization: nvml: Not Supported
Nov 13 22:57:03 jimmy-bigserver microk8s.daemon-kubelet[4173]: W1113 22:57:03.179429    4173 container.go:507] Failed to update stats for container "/kubepods/besteffort/pod545853d8-0496-11ea-a922-f2cd03415023/c900cd71ed291959ad12d6fe553cb2483a0664b14233576a7d7e380bb6326e1b": error while getting gpu utilization: nvml: Not Supported

**Comment by Boyan-Liu** [comment]
@NHZlX 麻烦召龙看下。
