### ISSUE TITLE
Test examples for multi-threading training on [MKLDNN]

### ISSUE THREAD

**Issue by lidanqing-vv** [PaddlePaddle/Paddle#21173]
@luotao1 Hi, please attach the links here for testing multi-threading training. @jczaja will look into it soon. Thank you very much!

**Comment by luotao1** [comment]
There are two modes:
- `ParallelExecutor`: https://github.com/PaddlePaddle/models/blob/develop/PaddleRec/ctr/dnn/train.py#L142
```
        exec_strategy = fluid.ExecutionStrategy()
        exec_strategy.num_threads = conf.thread_num
```
- `exe.train_from_dataset`: see https://github.com/PaddlePaddle/models/blob/develop/PaddleRec/ctr/deepfm/local_train.py#L37
```
dataset.set_thread(args.num_thread)
...
exe.train_from_dataset(
            program=fluid.default_main_program(),
            dataset=dataset,
            fetch_list=[loss, auc],
            fetch_info=['epoch %d batch loss' % (epoch_id + 1), "auc"],
            print_period=1000,
            debug=False)
```
You can find more cases of these two modes in [models repo](https://github.com/PaddlePaddle/models).

**Comment by jczaja** [comment]
@ddokupil Please have someone from validation look at this one e.g. on testing and integrating this test for purpose muli-threading based training of paddle models.

**Comment by ddokupil** [comment]
I can see it requires models repo to accompany traning the way you stated it. Actually we're removing models repo from execution process to simplify it. Is there a chance to run trainings using unit tests like we run inference?

**Comment by bingyanghuang** [comment]
> I can see it requires models repo to accompany traning the way you stated it. Actually we're removing models repo from execution process to simplify it. Is there a chance to run trainings using unit tests like we run inference?

Hi, darek. Baidu uses python script for training model CE.

**Comment by ddokupil** [comment]
> Hi, darek. Baidu uses python script for training model CE.

Ok,


> @ddokupil Please have someone from validation look at this one e.g. on testing and integrating this test for purpose muli-threading based training of paddle models.

Does this support Bert and Resnet50? In here it says about DeepFM
