### ISSUE TITLE
配置8个cpu训练时候出错，batch_size为512

### ISSUE THREAD

**Issue by Colorfu1** [PaddlePaddle/Paddle#21187]
使用多个cpu设备进行训练，配置CPU_NUM
`use_cuda = False`
`os.environ['CPU_NUM'] = '8'`
`place = fluid.CUDAPlace(0) if use_cuda else fluid.CPUPlace()`
配置dataloader
`dataloader_place = place if ITERABLE else None`
`train_loader.set_sample_list_generator(fluid.io.shuffle(fluid.io.batch(paddle.dataset.mnist.train(), 512), buf_size=1024), places=dataloader_place)`
`test_loader.set_sample_list_generator(fluid.io.batch(paddle.dataset.mnist.test(), 512), places=dataloader_place)`
程序运行后报错
ValueError: Feed a list of tensor, the list should be the same size as places
我不太清楚是哪里出错了，是设置了CPU_NUM之后，dataloader喂给模型的数据需要是CPU_NUM x batch_size x data_size大小吗？

**Comment by zhaoyuchen2018** [comment]
看起来和cpu_num没有什么关系，提示的错误是feed的数据size不一致。你看下官方的mnist是怎么配置的吧

**Comment by Colorfu1** [comment]
> 看起来和cpu_num没有什么关系，提示的错误是feed的数据size不一致。你看下官方的mnist是怎么配置的吧

研究之后发现，os.environ['CPU_NUM'] = '8'只影响exe配置的cpu个数，不影响data_loader配置的cpu个数，所以需要单独对data_loader进行配置。
