### ISSUE TITLE
在Windows10测试环境运行C++ inference失败

### ISSUE THREAD

**Issue by ff3141044702** [PaddlePaddle/Paddle#21184]
使用Windows10专业版+VS2015+cuda9.2+cudnn7.6.1+paddlepaddle 1.5.2的开发环境中，编译运行C++ inference程序，可以使用CPU模式（因为开发环境GPU安装失败）进行预测，但是在Windows10专业版+vc2015(update3)运行时库+.Net 4.5(4.6)运行时库的测试环境中，不管使用CPU还是GPU均报0xc000007b错误。

**Comment by zhaoyuchen2018** [comment]
出错的paddle是什么版本，除了这个0xc000007b还有什么信息打印吗

**Comment by ff3141044702** [comment]
paddle是1.6，除了这个没有别的信息

**Comment by ff3141044702** [comment]
paddle1.5.2和1.6都试过，除了0xc000007b外没有别的信息打印

**Comment by chaoswong1981** [comment]
这种错误我感觉像是库不匹配导致的，可以查查先排队这方面的问题

**Comment by ff3141044702** [comment]
缺少msvcp140.dll、opencv-world346.dll等文件，添加这些文件后CPU模式可用；但是GPU模式报错，跟踪发现问题出在：
im-tensor->copy_from_cpu(input_buffer.data());

**Comment by ff3141044702** [comment]
后来改用CUDA 9.0的版本就没有问题了，按照官方的说法，小版本兼容性会有问题。
