### ISSUE TITLE
windows下训练卡死

### ISSUE THREAD

**Issue by chaoswong1981** [PaddlePaddle/Paddle#21211]
- 版本、环境信息：
    1）PaddlePaddle版本：1.6.1
    2）GPU：NVIDIA Geforce GTX 1660 Ti, CUDA 10.0.130, cuDNN 7.6
    4）系统环境：Windows 10, Python 3.7.5 64bit
- 训练信息
    1）单机
    2）显存信息
    3）使用PaddleDetection的Yolov3模型
- 复现信息：
![1](https://user-images.githubusercontent.com/1501860/69005126-448bb500-0958-11ea-98e7-e171a2a1bda0.png)

- 问题描述：
    开始训练后不久就会出现卡死现象，训练步数不定，有时几百步，有时几千就会卡死不动。

Thank you for contributing to PaddlePaddle.
Before submitting the issue, you could search issue in the github in case that there was a similar issue submitted or resolved before.
If there is no solution,please make sure that this is a training issue including the following details:
**System information**
-PaddlePaddle version （eg.1.1）or CommitID
-CPU: including CPUMKL/OpenBlas/MKLDNN version
-GPU: including CUDA/CUDNN version
-OS Platform (eg.Mac OS 10.14)
-Other imformation: Distriuted training/informantion of operator/
Graphics card storage
**To Reproduce**
Steps to reproduce the behavior
**Describe your current behavior**
**Code to reproduce the issue**
**Other info / logs**

**Comment by liupluswei** [comment]
你好，我们已经发现cudaStreamSynchronize API在windows平台会出现随机hang的问题，目前已经提交PR #21201
