### ISSUE TITLE
Use ConcurrentRemoteParameterUpdater, and use localUpdater_ for other optimization algorithms

### ISSUE THREAD

**Issue by typhoonzero** [PaddlePaddle/Paddle#2121]
Related issue: https://github.com/PaddlePaddle/Paddle/issues/2106#issuecomment-301190012

- We need to use the latest implemented `ConcurrentRemoteParameterUpdater` in python v2 API instead of `RemoteParameterUpdater`.
- When using optimizers like `Adagrad` we need to create a "local" optimizer to do parameter optimization and upload delta (or diff) to parameter server, not just uploading gradients.

Related source codes:
- v2 API creating a remote updater: https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/v2/optimizer.py#L44
- create remote update in c++: https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/api/ParameterUpdater.cpp#L31 calls `auto remoteUpdater = new paddle::RemoteParameterUpdater(
      config->m->getConfig(), passCount, nullptr)` with last argument `nullptr` which means a null `local updater`
- https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/trainer/RemoteParameterUpdater.cpp#L32 constructor of `RemoteParameterUpdater.cpp`

**Comment by helinwang** [comment]
We need to take this issue into consideration when doing new pserver client library integration.

**Comment by dzhwinter** [comment]
The concept `RemoteParameterUpdater` will be removed since it has overlap with parameter server. 
Our new designed pserver client library has been implemented in  https://github.com/PaddlePaddle/Paddle/blob/develop/go/cmd/pserver/pserver.go 
We have a design doc on this problem, please check it out.
