### ISSUE TITLE
EOF Exception is not caught when using pyreader

### ISSUE THREAD

**Issue by mapingshuo** [PaddlePaddle/Paddle#21221]
### 问题描述

我在使用Pyreader做Bert fine-tuning阶段的训练，训练中发现当模型训练到最后，会报如下错误：

```shell
PaddleCheckError: Expected ids_dims[ids_rank - 1] == 1, but received ids_dims[ids_rank - 1]:0 != 1:1.
ShapeError: The last dimensions of the 'Ids' tensor must be 1. But received Ids's last dimensions = 0, Ids's shape = [0]. at [/home/users/dongdaxiang/Paddle/paddle/fluid/operators/lookup_table_op.cc:51]
  [operator < lookup_table > error]
```
报错内容显示exe.run传入了一个空Tensor, 即shape=[]。

可是PyReader遇到文件尾应该会raise EOFException后退出，不会给空数据去训练。

于是我打印了更多log，log显示程序已经抛出了EOFException，但是没有被catch，这个问题应该解决。log如下：

![image](https://user-images.githubusercontent.com/23031310/69037652-35be0480-0a23-11ea-8d0d-3fbc19206c80.png)

### 如何复现这个问题：

按照这个[repo](https://github.com/mapingshuo/Fleet/tree/recompute_examples/examples/recompute/bert)的readme即可复现。默认的数据需要训练2个小时才报错，建议取少量数据，这样可在几分钟内复现错误。

**Comment by skywalk163** [comment]
我遇到了同样的问题。
环境： aistudio 高级版环境： paddlepaddle1.7 python3.7 
出错代码位于：文档1.7-典型案例-自然语言处理-情感分析-构造训练器 代码部分：
https://www.paddlepaddle.org.cn/documentation/docs/zh/user_guides/nlp_case/understand_sentiment/README.cn.html
按手册顺序执行到这里：
exe = fluid.Executor(place)
prediction = inference_program(word_dict)
[avg_cost, accuracy] = train_program(prediction)#训练程序
sgd_optimizer = optimizer_func()#训练优化函数
sgd_optimizer.minimize(avg_cost)
报错信息是：
--------------------------------------------------------------------------EnforceNotMet                             Traceback (most recent call last)<ipython-input-9-fc3cd5c0deee> in <module>
      4 
      5 exe = fluid.Executor(place)
----> 6 prediction = inference_program(word_dict)
      7 [avg_cost, accuracy] = train_program(prediction)#训练程序
      8 sgd_optimizer = optimizer_func()#训练优化函数
<ipython-input-4-aaa0eb51d5af> in inference_program(word_dict)
      5         name="words", shape=[None], dtype="int64", lod_level=1)
      6     dict_dim = len(word_dict)
----> 7     net = convolution_net(data, dict_dim, CLASS_DIM, EMB_DIM, HID_DIM)
      8     # net = stacked_lstm_net(data, dict_dim, CLASS_DIM, EMB_DIM, HID_DIM, STACKED_NUM)
      9     return net
<ipython-input-2-e8715c236067> in convolution_net(data, input_dim, class_dim, emb_dim, hid_dim)
      4 def convolution_net(data, input_dim, class_dim, emb_dim, hid_dim):
      5     emb = fluid.layers.embedding(
----> 6         input=data, size=[input_dim, emb_dim], is_sparse=True)
      7     conv_3 = fluid.nets.sequence_conv_pool(
      8         input=emb,
中间省略部分。。。。。
----------------------
Error Message Summary:
----------------------
Error: ShapeError: The last dimensions of the 'Ids' tensor must be 1. But received Ids's last dimensions = -1, Ids's shape = [-1].
  [Hint: Expected ids_dims[ids_rank - 1] == 1, but received ids_dims[ids_rank - 1]:-1 != 1:1.] at (/paddle/paddle/fluid/operators/lookup_table_op.cc:51)
  [operator < lookup_table > error]

希望能得到解决，谢谢。
