### ISSUE TITLE
Paddlepaddle support python3 

### ISSUE THREAD

**Issue by juliecbd** [PaddlePaddle/Paddle#2123]
I think it is important Paddlepaddle to support python3 as soon as possible. It is very much possible that users perceive paddle not adaptive and not actively maintained. Almost all the deep learning libraries (Tensorflow, Pytorch, Keras etc) all actively support python3.

**Comment by gangliao** [comment]
@juliecbd I strongly agree with you. Hopefully, we can schedule our roadmap to support this feature.

**Comment by typhoonzero** [comment]
We should probably add https://docs.python.org/2/library/2to3.html to the CI system, so that we can build both python2 whl packages and python3 whl packages.
