### ISSUE TITLE
map_structure使用问题

### ISSUE THREAD

**Issue by Angus07** [PaddlePaddle/Paddle#21235]
我有两个tensor，分别是
 index: [batch_size ,1600, 1]
update: [batch_size, 1600]
希望能通过scatter_nd变成：
output: [batch_size, 18000]
在tensorflow中可以通过tf.map_fn实现。现在使用paddle中的utils.map_structure（没有相关文档）来复现，
attn_dists_projected = utils.map_structure(lambda y: layers.scatter_nd(y[0], y[1], [18000]),
                                         (index, update)) 
结果报错了，报错信息如下：

![image](https://user-images.githubusercontent.com/4252318/69121913-67dd6e00-0ad8-11ea-91e9-c6d18eb6a02b.png)

希望能告知正确的用法，或者其他可以实现这个功能的办法。

**Comment by guoshengCS** [comment]
这里map_structure的正确用法是
`attn_dists_projected = utils.map_structure(lambda x,y: layers.scatter_nd(x, y, [18000]), index, update)` 。但可能不是你那边预期的。
这个map_structure其实不太推荐直接使用，是内部接口，做的事情其实就是做函数映射，只是在能够在做的函数映射到同时保持输入的数据结构（list，dict之类），这样输出会和输入具有相同的数据结构。这个只是一个python层的工具函数，不是一个算子。
