### ISSUE TITLE
one_hot api参数失效

### ISSUE THREAD

**Issue by DDDivano** [PaddlePaddle/Paddle#21259]
https://www.paddlepaddle.org.cn/documentation/docs/zh/api_cn/fluid_cn/one_hot_cn.html
 allow_out_of_range这个参数不生效

**Comment by MRXLT** [comment]
你好，可以描述一下遇到的问题吗，具体是什么现象，希望能提供使用的paddle版本、环境、代码等信息

**Comment by DDDivano** [comment]
> 你好，可以描述一下遇到的问题吗，具体是什么现象，希望能提供使用的paddle版本、环境、代码等信息

![image](https://user-images.githubusercontent.com/10734244/69305219-1959dc00-0c5e-11ea-8abb-fdc9032fc761.png)
这个实例2会报错，后端可能没有传递过去那个allow_out_of_range参数

**Comment by DDDivano** [comment]
train_program = fluid.Program()
    startup_program = fluid.Program()
    with fluid.unique_name.guard():
        with fluid.program_guard(train_program, startup_program):
            label = fluid.layers.data(name="label", shape=[4], append_batch_size=False, dtype="int64")
            one_hot_label = fluid.one_hot(input=label, depth=4, allow_out_of_range=True)
            exe = fluid.Executor(fluid.CPUPlace())
            exe.run(startup_program)
            compiled_prog = fluid.compiler.CompiledProgram(train_program)
            x1 = np.array([[1, 1, 5, 0]])

            res = exe.run(compiled_prog,
                          feed={"label": x1}, fetch_list=["one_hot_v2_0.tmp_0"]
                          )[0][0]
            expect = [[0., 1., 0., 0.],
                        [0., 1., 0., 0.],
                        [0., 0., 0., 0.],
                        [1., 0., 0., 0.]]

**Comment by DDDivano** [comment]
```
train_program = fluid.Program()
    startup_program = fluid.Program()
    with fluid.unique_name.guard():
        with fluid.program_guard(train_program, startup_program):
            label = fluid.layers.data(name="label", shape=[4], append_batch_size=False, dtype="int64")
            one_hot_label = fluid.one_hot(input=label, depth=4, allow_out_of_range=True)
            exe = fluid.Executor(fluid.CPUPlace())
            exe.run(startup_program)
            compiled_prog = fluid.compiler.CompiledProgram(train_program)
            x1 = np.array([[1, 1, 5, 0]])
            res = exe.run(compiled_prog,
                          feed={"label": x1}, fetch_list=["one_hot_v2_0.tmp_0"]
                          )[0][0]
            expect = [[0., 1., 0., 0.],
                        [0., 1., 0., 0.],
                        [0., 0., 0., 0.],
                        [1., 0., 0., 0.]]
```

**Comment by MRXLT** [comment]
请问paddle版本是多少呢

**Comment by DDDivano** [comment]
> 请问paddle版本是多少呢

1.6.1

**Comment by gavin1332** [comment]
确认后端支持`allow_out_of_range`功能，但前端没有将该参数传进去，已提PR修复
https://github.com/PaddlePaddle/Paddle/pull/21287

**Comment by gavin1332** [comment]
pr已合入，会在1.6.2版发布。若着急使用可以先仿造pr直接修改python脚本
