### ISSUE TITLE
stack使用报错

### ISSUE THREAD

**Issue by Angus07** [PaddlePaddle/Paddle#21261]
在运行阶段：
![image](https://user-images.githubusercontent.com/4252318/69217259-308ac200-0ba9-11ea-800d-ff3cc284d4ec.png)
注意到这一行，好像是这里错误，但是看输入的形状应该是正确的：
I1120 15:16:47.257516 65396 operator.cc:152] CUDAPlace(0) Op(stack), inputs:{X[reshape2_52.tmp_0:int[3200, 1600]({}), squeeze_0.tmp_0:int64_t[3200, 1600]({})]}, outputs:{Y[stack_2.tmp_0:[0]({})]}.

 相关代码： 
new_src_ids = layers.stack([dec, src_ids], axis=2)
 new_src_ids.stop_gradient= True
其中dec和src_ids都是[3200, 1600]

**Comment by zhaoyuchen2018** [comment]
从log看input的data type不一致，一个是int，一个是int64，有可能造成memory访问越界，建议使用同样的数据类型。
