### ISSUE TITLE
[CPU预测]chinese_ner预测性能下降

### ISSUE THREAD

**Issue by OliverLPH** [PaddlePaddle/Paddle#21266]
- 标题：[CPU预测]chinese_ner预测性能下降40%
- 版本、环境信息：
    1）PaddlePaddle版本：eec9c9cbe7e8
    2）CPU：Intel(R) Xeon(R) CPU E5-2650 v4 @ 2.20GHz，使用MKL，未使用MKLDNN
    3）GPU：无
    4）系统环境：Ubuntu1604
    5）docker镜像：hub.baidubce.com/paddlepaddle/paddle:latest-dev 
-预测信息
    1）C++预测：eec9c9cbe7e8
    2）CMake包含路径的完整命令
    3）API信息（如调用请提供）
    4）预测库来源：自行编译

```shell
cmake .. \
  -DWITH_FLUID_ONLY=ON \
  -DWITH_SWIG_PY=OFF \
  -DWITH_PYTHON=ON \
  -DWITH_MKL=ON \
  -DWITH_GPU=ON \
  -DWITH_MKLDNN=OFF \
  -DON_INFER=ON \
  -DCMAKE_BUILD_TYPE=Release \
  -DWITH_INFERENCE_API_TEST=ON \
  -DWITH_TESTING=ON \                                                                                                             
  -DINFERENCE_DEMO_INSTALL_DIR=/root/.cache/inference_demo
```
- 复现信息：如为报错，请给出复现环境、复现步骤

直接执行`python chinese_ner_ce.py`即可得到速度指标
[codes.zip](https://github.com/PaddlePaddle/Paddle/files/3868946/codes.zip)

模型可以线下提供

- 问题描述：请详细描述您的问题，同步贴出报错信息、日志/代码关键片段

continuous evaluation从该commit开始，速度下降较多
以前的预测速度：0.175 ms/record 左右
当前的预测速度：0.234 ms/record 左右

<img width="814" alt="image" src="https://user-images.githubusercontent.com/14963836/69235588-b8ce8e80-0bcc-11ea-9575-08f0f1e3f336.png">

**Comment by luotao1** [comment]
@yihuaxu @bingyanghuang  https://github.com/PaddlePaddle/Paddle/commit/eec9c9cbe7e841a9b3fef301d8dc9518d6db2452 会导致chinese_ner性能下降，请帮忙看下
