### ISSUE TITLE
使用fluid1.5在paddlecloud上做增量训练 加载参数出错

### ISSUE THREAD

**Issue by lizhiqings** [PaddlePaddle/Paddle#21273]
报错信息如下 
![image](https://user-images.githubusercontent.com/47736115/69299138-c4f93100-0c4a-11ea-96dc-72e75aeb07d7.png)

我是参考的这个链接写的https://www.paddlepaddle.org.cn/documentation/docs/zh/1.5/user_guides/howto/training/save_load_variables.html

下面是我的 脚本
![image](https://user-images.githubusercontent.com/47736115/69299827-8795a300-0c4c-11ea-8474-f0ecc28f50df.png)

![image](https://user-images.githubusercontent.com/47736115/69299214-fbcf4700-0c4a-11ea-9f65-86aeee0c084e.png)

**Comment by NHZlX** [comment]
看起来是使用问题。请check一下自己的模型。
