### ISSUE TITLE
如下图所示，如何完成两个序列的横向拼接

### ISSUE THREAD

**Issue by zhlxys** [PaddlePaddle/Paddle#2128]
![image](https://cloud.githubusercontent.com/assets/12048003/26031205/383f86b6-389d-11e7-8d7e-0b373df319ee.png)

**Comment by luotao1** [comment]
You can use [paddle.v2.layer.concat](http://www.paddlepaddle.org/develop/doc/api/v2/config/layer.html#concat).

**Comment by zhlxys** [comment]
我试过直接拼接不行。代码是这样的：

先对“春天丽日照晴川” 双向编码，将输出连接
src_forward = simple_gru(input=src_embedding, size=encoder_size)
src_backward = simple_gru(input=src_embedding, size=encoder_size, reverse=True)
src_vector = concat_layer(input=[src_forward, src_backward])

然后对主题词“桃花”双向编码，分别得到first_seq和last_seq
topic_forward = simple_gru(input=topic_embedding, size=encoder_size)
topic_backward = simple_gru(input=topic_embedding, size=encoder_size, reverse=True)
topic_forward_last = last_seq(input=topic_forward)
topic_backward_first = first_seq(input=topic_backward)
topic_vector = [topic_forward_last,  topic_backward_first]

如果直接这样拼接两层
merge_vector = concat_layer(input=[topic_vector, src_vector])
在运行时会报错，
BaseMatrix.cu:99] Check failed: dimM + offset.bRow_ <= b.height_

是否有办法将图中的h0和h1拼接起来？

**Comment by lcy-seso** [comment]
请问需要的计算逻辑是怎样的呢？
1. 主题词 “桃 花 <eos>”  是一个3个词的序列，假设encoder_size = N，这就是一个 3 * N 的dense vector
 构成序列
2. “春 天 丽 日 照 晴 川” 是一个7个词的序列，假设encoder_szie = N，这是一个 7 * N 的dense vector 构成的序列
3. 上面两个输入，在逻辑上希望怎样拼接呢？

**Comment by lcy-seso** [comment]
1. 对src_vector 取 first_seq
2. 对topic_vector 去 last_seq
3. 再拼接1和2的输出

**Comment by zhlxys** [comment]
不好意思 我没表达清楚，
我是要把 h0 和 src_forward拼接起来，让h0作为src_forward的第一个

**Comment by zhlxys** [comment]
有办法在src_forward中增加一个h0吗？

**Comment by lcy-seso** [comment]
@zhlxys 抱歉回复较晚。
- PaddlePaddle 中目前没有这样的Layer
- 考虑到程序内部Batch的组织形式，这种拼接会比较奇怪，比较难直接实现。
- 因为一个batch的数据（多条序列）构成一个矩阵，你需要的这种拼接方式，需要把h_0（也是一个batch），逐个插入到src_forward 构成的batch 中
- 这样拼接之后需要进行什么样的操作呢？或许可以从计算的角度找到一个比较好的方式来实现。

**Comment by lcy-seso** [comment]
@zhlxys 抱歉回复较晚。

- 直接拼接h0和src_forward应该是不可以的。h0不是一个序列，而src_forward是一个序列
- PaddlePaddle 中目前没有直接去拼接h0和src_forward的Layer，cancat_layer只能拼接两个序列，拼接可以是两个维度
    - type1: [1, 2, 3, 4] 和 [5, 6, 7, 8] 拼接为 [1 5, 2 6, 3 7, 4 8]
    - type2: [1, 2, 3] 和 [4] 拼接为[1, 2, 3, 4]
- 我还需要再检查一下concat_layer是否暴露了能在这样两种拼接中选择的参数。


- 有一种比较trick的方法，应该可以完成你的需要
    1. 定义一个dummy的data layer，记作d1，在dataprovider里面永远接受输入是一个长度为1的序列，取值随意，比如全0
    2. 用expand_layer把h0扩展成和d1一样长的序列（长度总为1），记作expand1
    3. 采用上面的type2来拼接expand1和src_forward

**Comment by lcy-seso** [comment]
@zhlxys Paddle确实支持type1和type2提到的拼接方式，一些细节我再确认一下，不好意思。

**Comment by lcy-seso** [comment]
@zhlxys 你需要的应该是seq_concat_layer http://www.paddlepaddle.org/develop/doc/api/v2/config/layer.html#seq-concat

但不得不采用上面提到的比较trick的方法，

1. 定义一个dummy的data layer，记作d1，在dataprovider里面永远接受输入是一个长度为1的序列，取值随意，比如全0
2. 用expand_layer把h0扩展成和d1一样长的序列（长度总为1），记作expand1
3. 采用上面的type2来拼接expand1和src_forward

**Comment by QiJune** [comment]
长时间没有更新，暂时close；如有进一步更新，欢迎reopen
