### ISSUE TITLE
optimizer.minimize()的时候出错

### ISSUE THREAD

**Issue by Colorfu1** [PaddlePaddle/Paddle#21291]
在计算knn的时候，算出loss，optimizer反向传播的时候报错。
dgcnn模型需要在模型计算过程中动态计算每条数据的knn数据都是哪些，所以需要使用fluid.layers中的操作来计算knn。错误定位在高亮的那一行
![2](https://user-images.githubusercontent.com/30551427/69393810-2ab1ef80-0d15-11ea-91e7-2285527770e8.PNG)
具体的报错信息为：
![112](https://user-images.githubusercontent.com/30551427/69325480-305ff480-0c85-11ea-8519-5fd9b7db8ada.PNG)
![113](https://user-images.githubusercontent.com/30551427/69325492-348c1200-0c85-11ea-9c9b-a424744fd647.PNG)
我不是很明白到底错误出现在哪里。
但是经过实验之后，发现在reshape的时候把stop_gradient设置成True，整个程序不会报错并且可以得到正确的knn结果。如下图所示，高亮部分为设置stop_gradient。
![3](https://user-images.githubusercontent.com/30551427/69393814-2ede0d00-0d15-11ea-9831-44d1c3cec415.PNG)
请问这到底是什么原因造成的，把stop_gradient设置成True之后，对于整个网络的梯度传播会有什么影响吗？求大神解释一下。

**Comment by bjjwwang** [comment]
@chenwhql 求解答 谢谢

**Comment by chenwhql** [comment]
1. 前面的报错解释
- 报错是说reshape的反向Op的输入梯度为空，反向计算过程中，梯度根据链式法则逐级往回更新，这里应该是某处的配置导致reshape_grad这个反向op的输入没有被计算出来
2. stop_gradient
- 将k_index设置为stop_gradient的话，这个变量的梯度就不再计算了，下面的reshape的反向op reshape_grad就不再执行了，所以也不会出错，计算图中位于它前面的那些运算的梯度也不再计算，就是梯度传递到这里，在这个图分支上，不会再往回传播了
- 这里k_index的梯度应该本来就是没必要计算的，适当的设置变量的stop_gradient属性，可以剪枝不必要的梯度计算逻辑
