### ISSUE TITLE
How to represent sparse matrix in the new tensor library

### ISSUE THREAD

**Issue by QiJune** [PaddlePaddle/Paddle#2130]
In paddle, sparse matrix are organized with [CSR format](https://en.wikipedia.org/wiki/Sparse_matrix#Compressed_sparse_row_.28CSR.2C_CRS_or_Yale_format.29).  Since we decide to use `Array` to represent a tensor with specific `Dim` in the new tensor library, we may use an union struct containing three array to represent sparse matrix. The two of them are `int`, and the left one is `float`.

**Comment by Canpio** [comment]
Close this issue. It's out of date.
