### ISSUE TITLE
[问题请教] 关于安装和模型的一些问题请教

### ISSUE THREAD

**Issue by Renwb1991** [PaddlePaddle/Paddle#21303]
请教两个问题：
1. 如何 paddle.so 判断其需要的cadu和cadnn版本？
2. 定义了一个网络，在加载预训练模型的时候如何知道最后一层fc的名称？

**Comment by bjjwwang** [comment]
@sandyhouse  有时间看下第一题 谢谢
可以打印ProgramDesc
https://www.paddlepaddle.org.cn/documentation/docs/zh/advanced_usage/design_idea/fluid_design_idea.html#blockdesc-and-programdesc
参考这里

**Comment by sandyhouse** [comment]
可以通过ldd查看依赖的版本。
