### ISSUE TITLE
 layers.lod_reset报错

### ISSUE THREAD

**Issue by Angus07** [PaddlePaddle/Paddle#21313]
topk_indices = layers.lod_reset(topk_indices, pre_ids)
其中输入的topk_indices, pre_ids都是int64类型，报错信息如下：

![image](https://user-images.githubusercontent.com/4252318/69399066-acab1400-0d27-11ea-9704-6622af26f0d5.png)

**Comment by bjjwwang** [comment]
目前看起来不能支持lod_reset op 在C++端不能支持int64，会反馈下
