### ISSUE TITLE
【黄埔学院学员遇到问题】PaddleHub运行报错

### ISSUE THREAD

**Issue by newdimitri** [PaddlePaddle/Paddle#21316]
今天跑PaddleHub的Finetune例子（https://github.com/PaddlePaddle/PaddleHub/blob/release/v1.2/tutorial/autofinetune.md）的时候，遇到另一个问题。
 
运行autofinetune的时候报警：
PaddleHub Autofinetune starts round at 0.
WARNING: Program which was ran with hyperparameters as learning_rate=0.0007392373713034229 batch_size=16 was crashed!
 
查看log里面有错误信息
----------------------
Error Message Summary:
----------------------
PaddleCheckError: cudaGetDeviceCount failed in paddle::platform::GetCUDADeviceCountImpl, error code : 38, Please see detail in https://docs.nvidia.com/cuda/cuda-runtime-api/group__CUDART__TYPES.html#group__CUDART__TYPES_1g3f51e3575c2178246db0a94a430e0038: no CUDA-capable device is detected at [/paddle/paddle/fluid/platform/gpu_info.cc:67]
 
我之前是在另一个项目中运行这个例子，python2.7和3.7都报这个错误。看提示是说找不到GPU设备，但该项目的GPU是启用的。
后来我换到目前的项目尝试，这个项目之前运行图像分类迁移的例子是成功的，也是用到了GPU的。

 
项目地址是
https://aistudio.baidu.com/bdvgpu/user/109785/186345/notebooks/186345.ipynb?redirects=1
 
谢谢！

**Comment by wangchaochaohu** [comment]
可能是版本不兼容的原因 尝试下之前的版本看看是否可以？

**Comment by Steffy-zxf** [comment]
@newdimitri 感谢反馈！想问下，你运行PaddleHub AutoDL Finetuner是在ai studio 上运行 还是 自己的机器上呢？
https://aistudio.baidu.com/bdvgpu/user/109785/186345/notebooks/186345.ipynb?redirects=1
你的项目是私密状态，我访问不了，方便公开吗？我试试复现错误。
另外关于PaddleHub的问题，欢迎在PaddleHub repo下提问，https://github.com/paddlepaddle/paddlehub/issues
