### ISSUE TITLE
Change https://www.paddlepaddle.org to https://www.paddlepaddle.org.cn/

### ISSUE THREAD

**Issue by residentx10** [PaddlePaddle/Paddle#21330]
Change https:// www.paddlepaddle.org to https://www.paddlepaddle.org.cn/

Stop with the redirect please....just tell people were the repo really is. Practice truthfulness...

**Comment by wangchaochaohu** [comment]
You can visit https://www.paddlepaddle.org.cn/ for more information about PaddlePaddle. Thanks
