### ISSUE TITLE
Building error on Mac: inference_lib_dist source numbers are not equal to destination numbers

### ISSUE THREAD

**Issue by imistyrain** [PaddlePaddle/Paddle#21348]
为使您的问题得到快速解决，在建立Issue前，请您先通过如下方式搜索是否有相似问题:无

建立issue时，为快速解决问题，请您根据使用情况给出如下信息：
- 标题：building error on Mac: inference_lib_dist source numbers are not equal to destination numbers
- 版本、环境信息：
    1）PaddlePaddle版本：请提供您的PaddlePaddle版本号1.6
    2）CPU：请提供CPU型号，MKL/OpenBlas/MKLDNN/等数学库的使用情况
    3）GPU：No
    4）系统环境：Mac OS 10.14、Python2.7
- 安装方式信息：
本地编译：请提供cmake命令，编译命令

- 复现信息：如为报错，请给出复现环境、复现步骤
- 问题描述：请详细描述您的问题，同步贴出报错信息、日志/代码关键片段
```
cmake -DFLUID_INFERENCE_INSTALL_DIR=$PADDLE_ROOT \
      -DCMAKE_BUILD_TYPE=Release \
      -DWITH_PYTHON=OFF \
      -DWITH_MKL=OFF \
      -DWITH_GPU=OFF  \
      -DON_INFER=ON \
      ..
```

**Comment by sangoly** [comment]
麻烦提供一个报错截图

**Comment by zhwesky2010** [comment]
请问PADDLE_ROOT设置了初值吗？初值是多少？比如设置 PADDLE_ROOT=$pwd/fluid_inference_install_dir

**Comment by imistyrain** [comment]
<img width="1011" alt="image" src="https://user-images.githubusercontent.com/3972356/69540739-5dccdb00-0fc2-11ea-8718-3831ee3748ae.png">

**Comment by imistyrain** [comment]
文档上没说让设PADDLE_ROOT这东西呀

**Comment by zhwesky2010** [comment]
https://www.paddlepaddle.org.cn/documentation/docs/zh/advanced_usage/deploy/inference/build_and_install_lib_cn.html 这个PADDLE_ROOT需要提前设置的，或者你可以删掉-DFLUID_INFERENCE_INSTALL_DIR=$PADDLE_ROOT，使用默认的路径

**Comment by zhwesky2010** [comment]
hi，请问是这个原因吗？可以关闭issue了不

**Comment by imistyrain** [comment]
能给个默认值么，每次输不费劲么？

**Comment by imistyrain** [comment]
而且提示也没说时那个值没设置呀

**Comment by pebble1990** [comment]
您好 我在Linux 也遇到相同的错误 编译后提示 inference_lib_dist source numbers are not equal to destination numbers， 请问是否与目录有关

**Comment by zhwesky2010** [comment]
> 您好 我在Linux 也遇到相同的错误 编译后提示 inference_lib_dist source numbers are not equal to destination numbers， 请问是否与目录有关

现在的版本是统一使用默认路径了，不需要设置了。默认路径是 build/fluid_install_dir 和build/fluid_inference_install_dir，你可以看下这两个目录是不是空的
