### ISSUE TITLE
启动模型遇到paddle.fluid.core_avx.EnforceNotMet: Invoke operator fill_constant error.

### ISSUE THREAD

**Issue by littlepan0413** [PaddlePaddle/Paddle#21343]
启动模型报错
paddle.fluid.core_avx.EnforceNotMet: Invoke operator fill_constant error. 
查看之前类似的问题并尝试调整bach_size并没有解决，也无其他程序占用gpu

cuda版本 10
paddle版本1.5+
gpu 信息
![image](https://user-images.githubusercontent.com/6512760/69517999-5fca7600-0f91-11ea-820d-e8efbfc91b13.png)

报错信息
![image](https://user-images.githubusercontent.com/6512760/69518047-8be5f700-0f91-11ea-8474-d997f4e4e2ed.png)
![image](https://user-images.githubusercontent.com/6512760/69518066-9bfdd680-0f91-11ea-996d-560d87ffd030.png)
![image](https://user-images.githubusercontent.com/6512760/69518100-acae4c80-0f91-11ea-98c8-05d8f3e90cf6.png)

**Comment by wangchaochaohu** [comment]
能贴下具体的代码吗？

**Comment by littlepan0413** [comment]
> 能贴下具体的代码吗？

这是执行start的时候出错，我贴哪部分代码？

**Comment by AIpioneer** [comment]
线下沟通中

**Comment by qingqing01** [comment]
<img width="584" alt="图片" src="https://user-images.githubusercontent.com/7845005/69716029-37cf4400-1144-11ea-9969-679d7ab99ddc.png">

看截图错误，可能和CUDA环境没有设置正确有关，可以看下是否要将CUDA版本是否对应、以及是否要设置lib到LD_LIBRARY_PATH里
