### ISSUE TITLE
量化模型训练报错

### ISSUE THREAD

**Issue by Menevagol** [PaddlePaddle/Paddle#21356]
PaddleCheckError: Expected t->IsInitialized() == true, but received t->IsInitialized():0 != true

**Comment by juncaipeng** [comment]
> PaddleCheckError: Expected t->IsInitialized() == true, but received t->IsInitialized():0 != true

请参考这个issue，#21357。

**Comment by juncaipeng** [comment]
重复的issue，问题已经解决，可以close。
