### ISSUE TITLE
量化模型训练报错

### ISSUE THREAD

**Issue by Menevagol** [PaddlePaddle/Paddle#21357]
PaddleCheckError: Expected t->IsInitialized() == true, but received t->IsInitialized():0 != true
The Tensor in the coalesce_tensor Op's Input Variable Input(conv2d_65.w_0.quantized.dequantized) is not initialized. at [/home/omni/Paddle/paddle/fluid/framework/operator.cc:1155]

paddle是两周前拉取的develop最新的分支编译的，量化模型用的是paddle slim底层api

**Comment by juncaipeng** [comment]
> PaddleCheckError: Expected t->IsInitialized() == true, but received t->IsInitialized():0 != true
> The Tensor in the coalesce_tensor Op's Input Variable Input(conv2d_65.w_0.quantized.dequantized) is not initialized. at [/home/omni/Paddle/paddle/fluid/framework/operator.cc:1155]
> 
> paddle是两周前拉取的develop最新的分支编译的，量化模型用的是paddle slim底层api

请问是使用paddleslim中哪个量化api啊？能给出更多你调用的核心代码吗？

**Comment by CodesFarmer** [comment]
`

    transform_pass = QuantizationTransformPass(
        scope=fluid.global_scope(),
        place=place,
        activation_quantize_type="range_abs_max",
        weight_quantize_type="abs_max")

    transform_pass.apply(main_graph)
    transform_pass.apply(test_graph)
    build_strategy = fluid.BuildStrategy()
    build_strategy.memory_optimize = False
    build_strategy.enable_inplace = False
    binary = fluid.CompiledProgram(main_graph.graph).with_data_parallel(
        loss_name=train_cost.name, build_strategy=build_strategy)
    test_prog = test_graph.to_program()`

**Comment by Menevagol** [comment]
> > PaddleCheckError: Expected t->IsInitialized() == true, but received t->IsInitialized():0 != true
> > The Tensor in the coalesce_tensor Op's Input Variable Input(conv2d_65.w_0.quantized.dequantized) is not initialized. at [/home/omni/Paddle/paddle/fluid/framework/operator.cc:1155]
> > paddle是两周前拉取的develop最新的分支编译的，量化模型用的是paddle slim底层api
> 
> 请问是使用paddleslim中哪个量化api啊？能给出更多你调用的核心代码吗？

`

    transform_pass = QuantizationTransformPass(
        scope=fluid.global_scope(),
        place=place,
        activation_quantize_type="range_abs_max",
        weight_quantize_type="abs_max")

    transform_pass.apply(main_graph)
    transform_pass.apply(test_graph)
    build_strategy = fluid.BuildStrategy()
    build_strategy.memory_optimize = False
    build_strategy.enable_inplace = False
    binary = fluid.CompiledProgram(main_graph.graph).with_data_parallel(
        loss_name=train_cost.name, build_strategy=build_strategy)
    test_prog = test_graph.to_program()`

**Comment by juncaipeng** [comment]
> > > PaddleCheckError: Expected t->IsInitialized() == true, but received t->IsInitialized():0 != true
> > > The Tensor in the coalesce_tensor Op's Input Variable Input(conv2d_65.w_0.quantized.dequantized) is not initialized. at [/home/omni/Paddle/paddle/fluid/framework/operator.cc:1155]
> > > paddle是两周前拉取的develop最新的分支编译的，量化模型用的是paddle slim底层api
> > 
> > 
> > 请问是使用paddleslim中哪个量化api啊？能给出更多你调用的核心代码吗？
> 
> `
> 
> ```
> transform_pass = QuantizationTransformPass(
>     scope=fluid.global_scope(),
>     place=place,
>     activation_quantize_type="range_abs_max",
>     weight_quantize_type="abs_max")
> 
> transform_pass.apply(main_graph)
> transform_pass.apply(test_graph)
> build_strategy = fluid.BuildStrategy()
> build_strategy.memory_optimize = False
> build_strategy.enable_inplace = False
> binary = fluid.CompiledProgram(main_graph.graph).with_data_parallel(
>     loss_name=train_cost.name, build_strategy=build_strategy)
> test_prog = test_graph.to_program()`
> ```

是不是使用多卡训练会出现这个问题？可以尝试添加build_strategy.fuse_all_reduce_ops = False试下。

**Comment by Menevagol** [comment]
> > > > PaddleCheckError: Expected t->IsInitialized() == true, but received t->IsInitialized():0 != true
> > > > The Tensor in the coalesce_tensor Op's Input Variable Input(conv2d_65.w_0.quantized.dequantized) is not initialized. at [/home/omni/Paddle/paddle/fluid/framework/operator.cc:1155]
> > > > paddle是两周前拉取的develop最新的分支编译的，量化模型用的是paddle slim底层api
> > > 
> > > 
> > > 请问是使用paddleslim中哪个量化api啊？能给出更多你调用的核心代码吗？
> > 
> > 
> > `
> > ```
> > transform_pass = QuantizationTransformPass(
> >     scope=fluid.global_scope(),
> >     place=place,
> >     activation_quantize_type="range_abs_max",
> >     weight_quantize_type="abs_max")
> > 
> > transform_pass.apply(main_graph)
> > transform_pass.apply(test_graph)
> > build_strategy = fluid.BuildStrategy()
> > build_strategy.memory_optimize = False
> > build_strategy.enable_inplace = False
> > binary = fluid.CompiledProgram(main_graph.graph).with_data_parallel(
> >     loss_name=train_cost.name, build_strategy=build_strategy)
> > test_prog = test_graph.to_program()`
> > ```
> 
> 是不是使用多卡训练会出现这个问题？可以尝试添加build_strategy.fuse_all_reduce_ops = False试下。

谢谢，是多卡训练，添加这个属性后已经可以正常训练了
