### ISSUE TITLE
Gather_nd op里面增加对LoD信息的保留

### ISSUE THREAD

**Issue by LordAaron** [PaddlePaddle/Paddle#21369]
1）PaddlePaddle版本：例如1.6.1
2）CPU/GPU：CUDA9.0，cudnn7
3）系统环境：centos6.3

- 建议描述：在已有对gather_nd上做一些修改，现在gather_nd的op只支持Tensor的输入，现在希望能扩展到支持LoDTensor的输入，即输出能保留原本输入LoDTensor的LoD信息，现有op在LoDTensor输入之后，输出只有Tensor，没有保留LoD信息。

P.S：Gather_nd的api文档里面 index的变量类型标注错了，不应该是int，而是Variable才对
   https://www.paddlepaddle.org.cn/documentation/docs/zh/api_cn/layers_cn/gather_nd_cn.html#gather-nd

**Comment by ForFishes** [comment]
这个数据类型是说variable里的 `dtype` 。

**Comment by gavin1332** [comment]
但括号里要求填写的是数据类型而非dtype
