### ISSUE TITLE
fluid1.5训好模型预测时，关于cvm特征的问题

### ISSUE THREAD

**Issue by lizhiqings** [PaddlePaddle/Paddle#21370]
首先确认下下图应该就是 infer时候 做前向计算时cvm的api
![image](https://user-images.githubusercontent.com/47736115/69607793-fdd94180-1060-11ea-9469-7edee4313173.png)

但是没有看明白，按照这个写法 输出y的维度不是少了2维么 因为x是加2后copy的？
而且在训练的时候输入是有 show和click的，但是在infer的时候 不知道show和 infer 的 这个还怎么计算？

**Comment by xjqbest** [comment]
如果infer时候不需要cvm特征，infer时候可以直接去掉这个layer。
或者 设置use_cvm=False

**Comment by xjqbest** [comment]
already contact with user.  problem solved
