### ISSUE TITLE
AI studio项目文字识别，在paddle1.4和paddle1.5环境下能够正常训练，但在paddle1.6环境下无法正常训练，表现为输出loss一直为nan.

### ISSUE THREAD

**Issue by sucuicong** [PaddlePaddle/Paddle#21376]
Thank you for contributing to PaddlePaddle. Submitting an issue is a great help for us.
Both Chinese and English issues are welcome.

It's hard to solve a problem when important details are missing.
Before submitting the issue, look over the following criteria before handing your request in.

项目地址：AI studio项目文字识别https://aistudio.baidu.com/aistudio/projectdetail/72574，
可通过fork后运行，paddle1.6环境下loss输出一直为nan, paddle1.4和paddle 1.5环境下能够正常运行。
运行环境：GPU   Python3.7

- [ ] Was there a similar issue submitted or resolved before ? You could search issue in the github.
- [ ] Did you retrieve your issue from widespread search engines ?
- [ ] Is my description of the issue clear enough to reproduce this problem?
   * If some errors occurred, we need details about `how do you run your code?`, `what system do you use?`, `Are you using GPU or not?`, etc.
   * If you use an recording [asciinema](https://asciinema.org/) to show what you are doing to make it happen, that's awesome! We could help you solve the problem more quickly.
- [ ] Is my description of the issue use the github markdown correctly?
   * Please use the proper markdown syntaxes for styling all forms of writing, e.g, source code, error information, etc.
   * Check out [this page](https://guides.github.com/features/mastering-markdown/) to find out much more about markdown.

**Comment by wanghaoshuang** [comment]
https://github.com/PaddlePaddle/models/blob/develop/PaddleCV/ocr_recognition/attention_model.py#L191

需要添加gradient clipping
