### ISSUE TITLE
f1 score loss 实现问题

### ISSUE THREAD

**Issue by nuptxxp** [PaddlePaddle/Paddle#21389]
在paddle上实现了一个f1 loss函数：
`def _compute_loss(self, dec_output):
        tp = fluid.layers.sum(fluid.layers.cast(self.label * dec_output, dtype="float32"))
        tn = fluid.layers.sum(fluid.layers.cast((1 -self.label) * (1 - dec_output), dtype="float32"))
        fp = fluid.layers.sum(fluid.layers.cast((1 -self.label) * dec_output, dtype="float32"))
        fn = fluid.layers.sum(fluid.layers.cast(self.label * (1 - dec_output), dtype="float32"))
        print ("shape:loss", tp.shape, tn.shape, fp.shape, fn.shape)
        p = tp / (tp + fp + 1e-07)
        r = tp / (tp + fn + 1e-07)
        f1 = 2 * p * r / (p + r + 1e-07)
       print ("f1_shape ", f1.shape)
       print ("mean_shape ", fluid.layers.mean(f1))
       print ("loss_shape", 1 - fluid.layers.mean(f1))
       return 1 - fluid.layers.mean(f1), dec_output, self.label
`
输出的shape如下：
shape:loss (-1L, -1L, 3L) (-1L, -1L, 3L) (-1L, -1L, 3L) (-1L, -1L, 3L)
f1_shape  (-1L, -1L, 3L)
mean_shape  name: "mean_0.tmp_0"
type {
  type: LOD_TENSOR
  lod_tensor {
    tensor {
      data_type: FP32
      dims: 1
    }
  }
}
persistable: false

loss_shape name: "tmp_25"
type {
  type: LOD_TENSOR
  lod_tensor {
    tensor {
      data_type: FP32
      dims: 1
    }
    lod_level: 0
  }
}

实际以此loss做训练，结果很怪异，能帮忙看下原因吗，在keras实现此loss函数无问题

**Comment by nuptxxp** [comment]
重新贴下代码：
![image](https://user-images.githubusercontent.com/4417228/69691557-629ca680-110a-11ea-802e-80e5156d59a8.png)

**Comment by xyoungli** [comment]
请问， label和dec_out的shape是什么?数值是0，1？

**Comment by nuptxxp** [comment]
label_out 的shape是(-1L, -1L, 3L)
dec_out的shape是
name: "transpose_3.tmp_0"
type {
  type: LOD_TENSOR
  lod_tensor {
    tensor {
      data_type: FP32
      dims: -1
      dims: -1
      dims: 3
    }
  }
}
persistable: false

**Comment by nuptxxp** [comment]
label数值是3分类的one-hot，
dec_output是经过softmax处理的三个概率值，（LSTM seq2seq的loss函数）

**Comment by xyoungli** [comment]
sum op没有做reduce，请使用reduce_sum试试，设置需要做reduce的dim
