### ISSUE TITLE
使用GPU训练出错，CPU没问题

### ISSUE THREAD

**Issue by gongel** [PaddlePaddle/Paddle#21380]
下面是报错信息图片，烦劳解答一下。
![bug pic](https://github.com/gongel/DemoWeb/blob/master/bug.png)

**Comment by cyj1986** [comment]
这个应该是map find的时候没找到报的错误，光看bug信息无法定位问题

**Comment by gongel** [comment]
有没有可能是CUDA版本不对？

**Comment by cyj1986** [comment]
你的报错信息里提示了cudnn版本是不对的
