### ISSUE TITLE
打开 profiler 后出现 CUPTI_ERROR_INVALID_PARAMETER 错误

### ISSUE THREAD

**Issue by mzchtx** [PaddlePaddle/Paddle#21405]
### 环境

系统：CentOS6.3
python 版本：2.7.14（gcc482 编译）
paddle 版本：1.6.1.post107
NVIDIA Driver 版本：418.39
CUDA 版本：10.0
CUDNN：7.5.1 && 7.6.0
NCCL：2.3.7

已设置 CUPTI 环境变量等，运行[官网示例](https://www.paddlepaddle.org.cn/documentation/docs/zh/advanced_usage/development/profiling/timeline_cn.html)，报以下错误：

![image](https://user-images.githubusercontent.com/37564754/69711403-f89cf500-113b-11ea-847a-a6fa097df3a8.png)

使用 4 卡 P4 训练 resnet50 报错：
![image](https://user-images.githubusercontent.com/37564754/69711548-38fc7300-113c-11ea-80d9-2492cfe1115d.png)

关闭 profiler 没有问题。

**Comment by xyoungli** [comment]
请参考[#3124](https://github.com/PaddlePaddle/models/issues/3124)

**Comment by mzchtx** [comment]
> 请参考[#3124](https://github.com/PaddlePaddle/models/issues/3124)

安装 nccl 了，也设置 cupti 的环境变量了。
