### ISSUE TITLE
GAN demo cant run on paddle docker

### ISSUE THREAD

**Issue by kahitomi** [PaddlePaddle/Paddle#2140]
Im trying run the GAN demo in paddle. It seems that there is no docker image that can make it work immediately.The docker images I tried are:

paddledev/paddle:cpu-latest and cpu-demo-latest. As they are old version, this error is acceptable:
`
Traceback (most recent call last):
  File "gan_trainer.py", line 349, in <module>
    main()
  File "gan_trainer.py", line 271, in main
    copy_shared_parameters(gen_training_machine, dis_training_machine)
  File "gan_trainer.py", line 69, in copy_shared_parameters
    dst_value.copyFrom(src_value)
  File "/usr/local/lib/python2.7/dist-packages/py_paddle/swig_paddle.py", line 708, in <lambda>
    __getattr__ = lambda self, name: _swig_getattr(self, Vector, name)
  File "/usr/local/lib/python2.7/dist-packages/py_paddle/swig_paddle.py", line 57, in _swig_getattr
    raise AttributeError(name)
AttributeError: copyFrom
`

paddlepaddle/paddle:latest. This version lack PIL and other third party lib

paddlepaddle/paddle:latest-dev. At last, I tried build paddle with this version, but it said protobuf not found~

Will be there a demo version? or may update these third party libs

**Comment by QiJune** [comment]
In paddlepaddle/paddle:latest , after downloading mnist dataset, you can run following commands:

```
pip install Pillow
apt-get install python-tk
python gan_trainer.py -d=mnist --use_gpu=0
```

And the training will go on.
