### ISSUE TITLE
使用fluid.io.load_inference_model 加载训练好的模型用于预测时报错

### ISSUE THREAD

**Issue by zhong0033** [PaddlePaddle/Paddle#21411]
- 版本、环境信息：
    1）PaddlePaddle版本：1.5
    2）CPU：预测若用CPU，请提供CPU型号，MKL/OpenBlas/MKLDNN/等数学库使用情况
    4）系统环境：macbook pro 10.15.1
- 问题描述：在ai_studio 上训练好了一个模型，使用save_inference_model 保存后，将model文件夹全部下载，使用fluid.io.load_inference_model 加载模型，在exe.run()时报错，报错如下：
![image](https://user-images.githubusercontent.com/22142705/69728039-a7eac380-115e-11ea-8f09-091ce8fd1ce9.png)

![image](https://user-images.githubusercontent.com/22142705/69727987-8984c800-115e-11ea-8ddc-11e9b9620f45.png)

**Comment by OliverLPH** [comment]
通过log看起来可能是传入数据的格式不对，
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/14963836/69771894-57f51680-11c9-11ea-9cf8-386d737402b8.png">
可以尝试把height_sections 的类型改成`int64`再试下
