### ISSUE TITLE
Mandatory boot_layer argument in paddle.layer.memory if is_seq set True.

### ISSUE THREAD

**Issue by xinghai-sun** [PaddlePaddle/Paddle#2142]
If the argument `is_seq` set `True` for `paddle.layer.memory`, the argument `boot_layer` should be a mandatory instead of an optional. If `boot_layer` is `None` in this case, only a sequence of length ONE will be initialized.

It is suggested to add this to the function docs, or to give a warning when `boot_layer` is not provided if `is_seq` set `True`. Otherwise, it will add difficulties to PaddlePaddle beginners.

**Comment by luotao1** [comment]
目前在C++代码中，会有[提示](https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/gserver/gradientmachines/RecurrentGradientMachine.cpp#L723)
```
CHECK(input.sequenceStartPositions)
        << "boot layer must be a sequence when is_sequence = true";
```
你的意思是在python配置文件需要加上检查：is_seq=True时，boot_layer不能为空，对么？

**Comment by lcy-seso** [comment]
C++  代码这个提示应该不是@xinghai-sun 需要的。想了一下，Memory的is_seq=True的时候，必须有boot_layer 确实如此。

**Comment by xinghai-sun** [comment]
是的，虽然is_seq=True,boot_layer为空也能跑，但是用户可能不知道这样实际上是被初始化为length=1的sequence，造成后面的size不匹配。或者补充在文档上。

**Comment by luotao1** [comment]
I will fix it ASAP.

**Comment by xinghai-sun** [comment]
Great. Thanks!

**Comment by luotao1** [comment]
文档在原先的注释中就有：[layers.py L2869](https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/trainer_config_helpers/layers.py#L2869)
