### ISSUE TITLE
Book.paddlepaddle.org <PaddlePaddle installation guide> url error

### ISSUE THREAD

**Issue by llxxxll** [PaddlePaddle/Paddle#2143]
Book.paddlepaddle.org <PaddlePaddle installation guide> url error

correct url : How to run PaddlePaddle Book  https://github.com/PaddlePaddle/book#运行这本书 or https://github.com/PaddlePaddle/book/blob/develop/README.en.md#running-the-book

Error page list：

- http://book.paddlepaddle.org/01.fit_a_line/index.html
- http://book.paddlepaddle.org/02.recognize_digits/index.html
- http://book.paddlepaddle.org/03.image_classification/index.html
- http://book.paddlepaddle.org/04.word2vec/index.html
- http://book.paddlepaddle.org/05.recommender_system/index.html
- http://book.paddlepaddle.org/06.understand_sentiment/index.html
- http://book.paddlepaddle.org/07.label_semantic_roles/index.html
- http://book.paddlepaddle.org/08.machine_translation/index.html
- http://book.paddlepaddle.org/01.fit_a_line/index.en.html
- http://book.paddlepaddle.org/02.recognize_digits/index.en.html
- http://book.paddlepaddle.org/03.image_classification/index.en.html
- http://book.paddlepaddle.org/04.word2vec/index.en.html
- http://book.paddlepaddle.org/05.recommender_system/index.en.html
- http://book.paddlepaddle.org/06.understand_sentiment/index.en.html
- http://book.paddlepaddle.org/07.label_semantic_roles/index.en.html
- http://book.paddlepaddle.org/08.machine_translation/index.en.html

**Comment by luotao1** [comment]
fix in [#315](https://github.com/PaddlePaddle/book/pull/315) in book repo.
