### ISSUE TITLE
使用pip安装完后 import paddle出错

### ISSUE THREAD

**Issue by Junphy-Jan** [PaddlePaddle/Paddle#21457]
- 标题：安装错误：使用pip install 成功，但是进入python导入 paddle.fluid 时出错
- 版本、环境信息：
    1）PaddlePaddle版本：paddlepaddle-1.6.1
    2）CPU：Intel(R) Xeon(R) Platinum 8163 CPU @ 2.50GHz
    3）GPU：无
    4）系统环境：CentOS 7 python3.5.7  pip19.3.1
- 安装方式信息：
1）pip安装      

- 问题描述：
![安装成功](https://user-images.githubusercontent.com/14165820/69858016-14cf9c00-12cc-11ea-98c6-25919f377d96.png)
通过pip安装成功；
![python导入失败](https://user-images.githubusercontent.com/14165820/69858042-25801200-12cc-11ea-8d75-5126cc6893f7.png)
通过python导入 paddle.fluid时失败 
python环境变量已加入系统变量

**Comment by MyPandaShaoxiang** [comment]
你好，图片无法查看

**Comment by JanJF** [comment]
[cid:image002.png@01D5A6DF.C5570530]
[cid:image006.png@01D5A6DF.C5570530]

可能挂个代理能看到
原图：
[cid:image011.png@01D5A6DF.C5570530][cid:image012.png@01D5A6DF.C5570530]

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

发件人: TianXiaogang<mailto:notifications@github.com>
发送时间: 2019年11月29日 18:04
收件人: PaddlePaddle/Paddle<mailto:Paddle@noreply.github.com>
抄送: JanJF<mailto:microjan@outlook.com>; Author<mailto:author@noreply.github.com>
主题: Re: [PaddlePaddle/Paddle] 使用pip安装完后 import paddle出错 (#21457)


你好，图片无法查看

―

**Comment by Junphy-Jan** [comment]
![python导入失败](https://user-images.githubusercontent.com/14165820/69861435-53b52000-12d3-11ea-99a6-29ed45edc981.png)
![安装成功](https://user-images.githubusercontent.com/14165820/69861438-544db680-12d3-11ea-839d-9dd2d61e2c82.png)

**Comment by MyPandaShaoxiang** [comment]
你的python3是自己编的么？

**Comment by Junphy-Jan** [comment]
> 你的python3是自己编的么？

是通过 make & make install 安装的

**Comment by MyPandaShaoxiang** [comment]
你好，可以参考paddle_installation仓库下的编译脚本 http://icode.baidu.com/repos/baidu/paddle/paddle-installation/blob/master:env/centos_7_cpu_py35.dockerfile

**Comment by MyPandaShaoxiang** [comment]
centos需要安装sqlite-devel，然后重新编一下python3

**Comment by Junphy-Jan** [comment]
> centos需要安装sqlite-devel，然后重新编一下python3

安装之后导入成功，谢谢
