### ISSUE TITLE
关于 fluid.layers.data 更改 lod_level 的一点疑惑

### ISSUE THREAD

**Issue by tsaizehua** [PaddlePaddle/Paddle#21469]
Fluid 1.6，本例无其它特殊环境。

console 调试代码时无意中更改了数据层的 lod_level，报错：
```
x = fluid.layers.data(name="argX", shape=[1], dtype='float32', lod_level=1)
x = fluid.layers.data(name="argX", shape=[1], dtype='float32', lod_level=2)
ValueError: Variable argX has been created before. The previous lod_level is 1; the new lod_level is 2. They are not matched
```
并仔细看了*fluid.layers.data*以及*name*相关的文档，并未找到合理的答案。
“name 用于网络层输出的前缀标识，name值_数字.tmp_数字中的数字会递增。” 一方面常规理解后者定义应该可以正常覆盖前者；另一方面，Fluid 内部的命名也是自增以作区分。

而报错是针对 lod_tensor，难道是 paddle 静态图对网络定义上的某种限制？

谢谢。

**Comment by willthefrog** [comment]
data是网络的输入，命名需要唯一，, 后面会根据命名创建feed dict，所以内部实现没有使用unique_name generator来设置名称。

**Comment by willthefrog** [comment]
另外，1.6以后加入了`fluid.data`，`fluid.layers.data`已经不再推荐使用。

**Comment by tsaizehua** [comment]
> data是网络的输入，命名需要唯一，, 后面会根据命名创建feed dict，所以内部实现没有使用unique_name generator来设置名称。

正因为是同命名，不应该覆盖之前的定义吗？内部实现时数据结构定下来，上层的引用指向就不能动了？因为这个 case 仅仅只是更改了 lod_level 参数，fluid.data也如此。

**Comment by willthefrog** [comment]
weight sharing是按变量名实现的，所以变量不能根据名称随意覆盖。
