### ISSUE TITLE
Not to build all tests into a single big binary

### ISSUE THREAD

**Issue by wangkuiyi** [PaddlePaddle/Paddle#2146]
I noticed that we have the convention to build all tests in a directory into a single binary.  I guess this is why we often have a `test` sub-directory and put all tests in there?

However, it is often that I just want to build and run a single test, but I have to wait a long time for the building of all tests in that directory.  How about we build each `xxx_test.cc` into a binary?

If we are going to do so, it would be great if we can add a CMake function like `cc_test` that calls 

1. `add_executable`
1. `add_dependencies`
1. `target_link_libraries`

**Comment by Canpio** [comment]
Close this issue. The required feature has been done.
