### ISSUE TITLE
旧版本的API

### ISSUE THREAD

**Issue by liangyz23** [PaddlePaddle/Paddle#21464]
您好，我这边有一个旧的模型是用老版本的Paddle实现的，我想看下旧版本的API，在哪儿可以找到呢？是fluid之前的版本。
多谢！

**Comment by zhiqiu** [comment]
您好，官方是可以选择旧版本的。
![image](https://user-images.githubusercontent.com/6888866/69878057-c2f43980-12fe-11ea-9fb9-169186ba1cd1.png)

**Comment by reddancer** [comment]
多谢，选择框换位置了，之前找了一圈没找到。

**Comment by liangyz23** [comment]
谢谢回复，但点开0.12之后，只有很少的内容，关于paddle.layer和paddle.pooling说明都没有
