### ISSUE TITLE
paddleubuntu14.04_cuda10.0_cudnn7_avx_mkl_trt5 使用报错

### ISSUE THREAD

**Issue by barry2025** [PaddlePaddle/Paddle#21479]
PaddleDetection c++ inference库，使用paddleubuntu14.04_cuda10.0_cudnn7_avx_mkl_trt5 fluid_inference报错：
![image](https://user-images.githubusercontent.com/20043808/69944475-5fe2ec80-1522-11ea-8b75-67c1514db5eb.png)
用的基础镜像环境是：
![image](https://user-images.githubusercontent.com/20043808/69944512-7721da00-1522-11ea-89da-0e04c0fdf8dc.png)
请问下这个fluid_inference库编译的时候基础环境是什么？

**Comment by fc500110** [comment]
你的gcc版本是啥

**Comment by fc500110** [comment]
你的gcc版本是啥

**Comment by barry2025** [comment]
gcc-version: 
![image](https://user-images.githubusercontent.com/20043808/69947655-0fbb5880-1529-11ea-828a-28d18f09c633.png)
采用的nvidia/cuda:10.1-cudnn7-devel-centos7中自带的gcc，没有装别的

**Comment by FrostML** [comment]
untu14.04_cuda10.0_cudnn7_avx_mkl_trt5编译时使用的是gcc482

**Comment by barry2025** [comment]
麻烦再请问下基础镜像用的是哪个环境？nvidia提供的cuda10默认的gcc版本都是gcc4.8.5了

**Comment by barry2025** [comment]
应该不是gcc版本的问题。
![image](https://user-images.githubusercontent.com/20043808/69956020-ed7e0680-1539-11ea-9885-9659b8d53ff2.png)
在nvidia/cuda:9.0-cudnn7-devel-centos7下可以使用
![image](https://user-images.githubusercontent.com/20043808/69955934-ba3b7780-1539-11ea-906f-a11ec93bcca3.png)
vidia/cuda:10.1-cudnn7-devel-centos7下不能使用
这两个基础镜像中的gcc版本是一致的，都是gcc4.8.5

**Comment by barry2025** [comment]
centos的libstdc++.so.6 最高只到19：
![image](https://user-images.githubusercontent.com/20043808/70025931-5f595d00-15d9-11ea-8158-affb8aba8977.png)

后来换用nvidia/cuda:.v10.1-cudnn7-devel-ubuntu16.04基础环境后，使用时出现：
![image](https://user-images.githubusercontent.com/20043808/70025860-3042eb80-15d9-11ea-93ff-09d1ca5b3a63.png)

请问下如下fluid_inference库的编译环境是什么？
![Uploading image.png…]()

**Comment by sjtubinlong** [comment]
@barry2025 我们会测试一下两个不同镜像的问题，尽快确认问题。
