### ISSUE TITLE
"cc1plus: all warnings being treated as errors" problem brakes our validation process

### ISSUE THREAD

**Issue by ddokupil** [PaddlePaddle/Paddle#21489]
**System information**
-PaddlePaddle version: Latest Develop branch
-CPU: MKLDNN, CLX
-GPU: Irrelevant/not used
-OS Platform: Ubuntu 18.04
-Python version: 2.7.12
-Install method: building from source, gcc (Ubuntu 5.4.0-6ubuntu1~16.04.11) 5.4.0 20160609
**To Reproduce**
cmake .. -DCMAKE_BUILD_TYPE=Release -DWITH_GPU=OFF -DWITH_MKLDNN=ON -DWITH_TESTING=ON -DWITH_PROFILER=ON -DWITH_STYLE_CHECK=OFF -DON_INFER=ON -DWITH_INFERENCE_API_TEST=ON
**Describe your current behavior**
During make:
cc1plus: all warnings being treated as errors
(...)
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2
**Other info / logs**
make -j 20
[  0%] Built target extern_pybind
[  0%] Built target extern_warpctc
[  0%] Built target extern_gflags
[  0%] Built target extern_dlpack
[  0%] Built target extern_xbyak
[  0%] Built target extern_zlib
[  0%] Built target extern_inference_download_pascalvoc_small_tar_gz
[  1%] Built target extern_eigen3
[  1%] Built target extern_boost
[  1%] Built target extern_inference_download_bert_data_len20_txt_tar_gz
[  1%] Built target extern_inference_download_pascalvoc_val_head_300_tar_gz
[  1%] Built target extern_inference_download_word2vec_inference_model_tar_gz
[  1%] Built target framework_py_proto_init
[  2%] Built target extern_xxhash
[  2%] Built target extern_threadpool
[  2%] Built target extern_inference_download_ResNet50_qat_perf_int8_tar_gz
[  2%] Built target extern_mklml
[  2%] Built target extern_inference_download_Res101_int8_model_tar_gz
[  2%] Built target profiler_py_proto_init
[  2%] Built target extern_inference_download_GoogleNet_int8_model_tar_gz
[  2%] Built target extern_inference_download_resnet50_int8_model_tar_gz
[  2%] Built target extern_inference_download_temp_2Ftransformer_data_txt_tar_gz
[  2%] Built target extern_inference_download_mobilenet_v2_int8_model_tar_gz
[  2%] Built target extern_inference_download_lac_data_txt_tar_gz
[  2%] Built target extern_inference_download_chinese_ner_model_tar_gz
[  2%] Built target extern_inference_download_dam_small_data_txt_tar_gz
[  2%] Built target extern_inference_download_dam_small_model_tar_gz
[  3%] Built target extern_inference_download_Ernie_result_txt_tar_gz
[  3%] Built target extern_inference_download_chinese_ner_data_txt_tar_gz
[  3%] Built target extern_inference_download_lac_model_tar_gz
[  3%] Built target extern_inference_download_rnn1_2Fmodel_tar_gz
[  3%] Built target extern_inference_download_rnn1_2Fdata_txt_tar_gz
[  3%] Built target extern_inference_download_PyramidDNN_model_tar_gz
[  3%] Built target extern_inference_download_Ernie_model_tar_gz
[  3%] Built target extern_inference_download_VGG16_int8_model_tar_gz
[  3%] Built target extern_inference_download_seq_pool1_data_txt_tar_gz
[  3%] Built target extern_inference_download_DAM_data_txt_tar_gz
[  3%] Built target extern_inference_download_rnn2_model_tar_gz
[  3%] Built target extern_inference_download_DAM_model_tar_gz
[  3%] Built target extern_inference_download_PyramidDNN_data_txt_tar_gz
[  3%] Built target extern_inference_download_rnn2_data_txt_tar_gz
[  3%] Built target extern_inference_download_temp_2Ftransformer_model_tar_gz
[  4%] Built target extern_inference_download_resnet50_model_tar_gz
[  6%] Built target extern_inference_download_text_classification_Senta_tar_gz
[  6%] Built target extern_inference_download_Ernie_data_txt_tar_gz
[  7%] Built target extern_inference_download_seq_conv1_data_txt_tar_gz
[  7%] Built target extern_inference_download_inference_vis_demos_2Focr_tar_gz
[  7%] Built target extern_inference_download_mobilenetv1_int8_model_tar_gz
[  7%] Built target extern_inference_download_seq_pool1_model__tar_gz
[  7%] Built target extern_inference_download_seq_conv1_model_tar_gz
[  7%] Built target extern_inference_download_bert_emb128_model_tar_gz
[  8%] Built target extern_inference_download_inference_vis_demos_2Fmobilenet_tar_gz
[  8%] Built target extern_inference_download_text_classification_data_txt_tar_gz
[  9%] Built target extern_inference_download_mobilenet_ssd_int8_model_tar_gz
[  9%] Built target extern_inference_download_googlenet_tar_gz
[  9%] Built target extern_inference_download_ResNet50_qat_perf_tar_gz
[  9%] Built target extern_inference_download_mobilenet_model_tar_gz
[  9%] Built target extern_inference_download_VGG19_int8_model_tar_gz
[  9%] Built target extern_inference_download_imagenet_val_100_tail_tar_gz
[ 10%] Built target extern_inference_download_MobileNetV1_qat_model_tar_gz
[ 10%] Built target extern_inference_download_ResNet50_qat_model_tar_gz
[ 10%] Built target extern_inference_download_MobileNetV2_qat_model_tar_gz
[ 11%] Built target extern_inference_download_VGG16_qat_model_tar_gz
[ 12%] Built target extern_inference_download_ResNet101_qat_model_tar_gz
[ 12%] Built target extern_inference_download_VGG19_qat_model_tar_gz
[ 12%] Built target extern_inference_download_GoogleNet_qat_model_tar_gz
[ 12%] Built target extern_inference_download_MobileNet_qat_perf_tar_gz
[ 13%] Built target extern_glog
[ 13%] Built target extern_protobuf
[ 13%] Built target extern_gtest
[ 13%] Built target flags
[ 13%] Built target extern_mkldnn
Copy generated python proto into directory paddle/fluid/proto/profiler.
Copy generated python proto into directory paddle/fluid/proto.
[ 13%] Built target framework_proto
[ 13%] Built target version
[ 13%] Built target error_codes_proto
[ 13%] Built target timer
[ 13%] Built target imperative_flag
[ 13%] Built target data_feed_proto
[ 13%] Built target boost
[ 13%] Built target activation_functions
[ 13%] Built target paddle_pass_builder
[ 13%] Built target imperative_profiler
[ 13%] Built target trainer_py_proto
[ 14%] Built target zero_copy_tensor_dummy
[ 14%] Built target stringpiece
[ 14%] Built target pretty_log
[ 14%] Built target profiler_py_proto
[ 14%] Built target framework_py_proto
[ 15%] Built target mkldnn
[ 15%] Built target third_party
[ 15%] Built target profiler_proto
[ 16%] Built target cudnn_workspace_helper
[ 16%] Built target trainer_desc_proto
[ 16%] Built target errors
[ 16%] Built target string_helper
[ 16%] Built target attribute
[ 16%] Built target prune
[ 16%] Built target enforce
[ 16%] Built target device_tracer
[ 16%] Built target fs
[ 16%] Built target shell
[ 16%] Built target cpu_info
[ 16%] Built target dynamic_loader
[ 16%] Built target op_proto_maker
[ 16%] Built target ddim
[ 16%] Built target threadpool
[ 16%] Built target benchmark
[ 16%] Built target place
[ 16%] Built target profiler
[ 16%] Built target dynload_mklml
[ 16%] Built target dynload_warpctc
[ 16%] Built target memory_block
[ 16%] Built target op_call_stack
[ 16%] Built target system_allocator
[ 16%] Built target memcpy
[ 16%] Built target allocator
[ 16%] Built target device_memory_aligment
[ 16%] Built target cblas
[ 17%] Built target buddy_allocator
[ 17%] Built target cpu_helper
[ 17%] Built target aligned_allocator
[ 17%] Built target retry_allocator
[ 17%] Built target locked_allocator
[ 17%] Built target cpu_allocator
[ 17%] Built target buffered_allocator
[ 17%] Built target best_fit_allocator
[ 17%] Built target naive_best_fit_allocator
[ 17%] Built target jit_kernel_base
[ 17%] Built target auto_growth_best_fit_allocator
[ 17%] Built target allocator_strategy
[ 17%] Built target jit_kernel_refer
[ 18%] Built target jit_kernel_mix
[ 18%] Built target jit_kernel_mkl
[ 18%] Built target jit_kernel_intrinsic
[ 18%] Built target allocator_facade
[ 18%] Built target jit_kernel_jitcode
[ 18%] Built target malloc
[ 18%] Built target jit_kernel_helper
[ 18%] Built target memory
[ 18%] Built target mask_util
[ 18%] Built target device_context
[ 18%] Built target sampler
[ 18%] Built target data_type
[ 18%] Built target garbage_collector
[ 18%] Built target blas
[ 18%] Built target op_kernel_type
[ 18%] Built target device_code
[ 18%] Built target vol2col
[ 19%] Built target no_need_buffer_vars_inference
[ 19%] Built target shape_inference
[ 19%] Built target lstm_compute
[ 19%] Built target sample_prob
[ 19%] Built target unpooling
[ 19%] Built target pooling
[ 20%] Built target concat_and_split
[ 20%] Built target maxouting
[ 20%] Built target im2col
[ 20%] Built target cross_entropy
[ 20%] Built target nccl_context
[ 20%] Built target sequence_scale
[ 20%] Built target sequence_padding
[ 20%] Built target sequence2batch
[ 20%] Built target cos_sim_functor
[ 20%] Built target paddle_gtest_main
[ 20%] Built target op_info
[ 20%] Built target matrix_bit_code
[ 20%] Built target math_function
[ 20%] Built target fc
[ 21%] Built target unused_var_check
[ 21%] Built target tensor
[ 21%] Built target selected_rows
[ 21%] Built target dlpack_tensor
[ 21%] Built target data_device_transform
[ 22%] Built target lod_tensor
[ 22%] Built target data_type_transform
[ 22%] Built target jit_kernel_benchmark
[ 22%] Built target mkldnn_quantizer_config
[ 22%] Built target buddy_allocator_test
[ 23%] Built target system_allocator_test
[ 23%] Built target buffered_allocator_test
[ 23%] Built target reader
[ 23%] Building CXX object paddle/fluid/memory/allocation/CMakeFiles/test_aligned_allocator.dir/test_aligned_allocator.cc.o
[ 23%] Built target variable_visitor
[ 23%] Built target var_type_traits
[ 23%] Built target variable_helper
[ 23%] Built target lod_rank_table
Scanning dependencies of target softmax
[ 23%] Building CXX object paddle/fluid/memory/allocation/CMakeFiles/best_fit_allocator_test.dir/best_fit_allocator_test.cc.o
[ 23%] Built target box_wrapper
[ 23%] Built target auto_growth_best_fit_allocator_facade_test
Scanning dependencies of target beam_search
[ 23%] Built target retry_allocator_test
Scanning dependencies of target tree2col
Scanning dependencies of target gru_compute
Scanning dependencies of target context_project
[ 23%] Building CXX object paddle/fluid/platform/CMakeFiles/enforce_test.dir/enforce_test.cc.o
Scanning dependencies of target sequence_pooling
Scanning dependencies of target data_layout_transform
[ 23%] Built target cpu_helper_test
[ 23%] Built target allocator_facade_abs_flags_test
[ 23%] Built target allocator_facade_frac_flags_test
Scanning dependencies of target errors_test
[ 23%] Building CXX object paddle/fluid/operators/math/CMakeFiles/softmax.dir/softmax.cc.o
[ 23%] Built target profiler_test
Scanning dependencies of target cpu_info_test
[ 23%] Building CXX object paddle/fluid/operators/math/CMakeFiles/beam_search.dir/beam_search.cc.o
[ 23%] Building CXX object paddle/fluid/platform/CMakeFiles/errors_test.dir/errors_test.cc.o
[ 23%] Building CXX object paddle/fluid/operators/math/CMakeFiles/tree2col.dir/tree2col.cc.o
[ 23%] Building CXX object paddle/fluid/platform/CMakeFiles/cpu_info_test.dir/cpu_info_test.cc.o
[ 23%] Building CXX object paddle/fluid/operators/math/CMakeFiles/gru_compute.dir/gru_compute.cc.o
[ 23%] Built target float16_test
[ 23%] Building CXX object paddle/fluid/operators/math/CMakeFiles/sequence_pooling.dir/sequence_pooling.cc.o
[ 23%] Building CXX object paddle/fluid/operators/math/CMakeFiles/context_project.dir/context_project.cc.o
[ 23%] Building CXX object paddle/fluid/framework/CMakeFiles/data_layout_transform.dir/data_layout_transform.cc.o
Scanning dependencies of target timer_test
Scanning dependencies of target cow_ptr_tests
Scanning dependencies of target selected_rows_functor
Scanning dependencies of target rw_lock_test
Scanning dependencies of target inlined_vector_test
[ 23%] Building CXX object paddle/fluid/platform/CMakeFiles/timer_test.dir/timer_test.cc.o
[ 23%] Building CXX object paddle/fluid/framework/CMakeFiles/cow_ptr_tests.dir/details/cow_ptr_test.cc.o
[ 23%] Building CXX object paddle/fluid/framework/CMakeFiles/rw_lock_test.dir/rw_lock_test.cc.o
Scanning dependencies of target place_test
[ 23%] Building CXX object paddle/fluid/framework/CMakeFiles/inlined_vector_test.dir/inlined_vector_test.cc.o
[ 23%] Building CXX object paddle/fluid/operators/math/CMakeFiles/selected_rows_functor.dir/selected_rows_functor.cc.o
[ 23%] Building CXX object paddle/fluid/platform/CMakeFiles/place_test.dir/place_test.cc.o
Scanning dependencies of target init_test
Scanning dependencies of target op_kernel_type_test
[ 23%] Building CXX object paddle/fluid/platform/CMakeFiles/init_test.dir/init_test.cc.o
[ 23%] Building CXX object paddle/fluid/framework/CMakeFiles/op_kernel_type_test.dir/op_kernel_type_test.cc.o
[ 23%] Linking CXX executable timer_test
[ 23%] Linking CXX executable cpu_info_test
[ 23%] Linking CXX executable cow_ptr_tests
[ 23%] Built target timer_test
Scanning dependencies of target threadpool_test
[ 23%] Building CXX object paddle/fluid/framework/CMakeFiles/threadpool_test.dir/threadpool_test.cc.o
[ 23%] Built target cpu_info_test
Scanning dependencies of target op_proto_maker_test
[ 23%] Building CXX object paddle/fluid/framework/CMakeFiles/op_proto_maker_test.dir/op_proto_maker_test.cc.o
[ 23%] Built target cow_ptr_tests
[ 23%] Linking CXX executable inlined_vector_test
Scanning dependencies of target copy_same_tensor_test
[ 23%] Building CXX object paddle/fluid/framework/CMakeFiles/copy_same_tensor_test.dir/copy_same_tensor_test.cc.o
[ 23%] Built target inlined_vector_test
In file included from /repos/paddle_paddle/paddle/fluid/memory/allocation/test_aligned_allocator.cc:15:0:
/repos/paddle_paddle/build/third_party/install/gtest/include/gtest/gtest.h: In instantiation of 'testing::AssertionResult testing::internal::CmpHelperEQ(const char*, const char*, const T1&, const T2&) [with T1 = long unsigned int; T2 = int]':
/repos/paddle_paddle/build/third_party/install/gtest/include/gtest/gtest.h:1472:23:   required from 'static testing::AssertionResult testing::internal::EqHelper<lhs_is_null_literal>::Compare(const char*, const char*, const T1&, const T2&) [with T1 = long unsigned int; T2 = int; bool lhs_is_null_literal = false]'
/repos/paddle_paddle/paddle/fluid/memory/allocation/test_aligned_allocator.cc:23:266:   required from here
/repos/paddle_paddle/build/third_party/install/gtest/include/gtest/gtest.h:1444:11: error: comparison between signed and unsigned integer expressions [-Werror=sign-compare]
  ​if (lhs == rhs) {
          ​^
cc1plus: all warnings being treated as errors
paddle/fluid/memory/allocation/CMakeFiles/test_aligned_allocator.dir/build.make:62: recipe for target 'paddle/fluid/memory/allocation/CMakeFiles/test_aligned_allocator.dir/test_aligned_allocator.cc.o' failed
make[2]: *** [paddle/fluid/memory/allocation/CMakeFiles/test_aligned_allocator.dir/test_aligned_allocator.cc.o] Error 1
CMakeFiles/Makefile2:2105: recipe for target 'paddle/fluid/memory/allocation/CMakeFiles/test_aligned_allocator.dir/all' failed
make[1]: *** [paddle/fluid/memory/allocation/CMakeFiles/test_aligned_allocator.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
Scanning dependencies of target tuple_test
[ 23%] Building CXX object paddle/fluid/framework/CMakeFiles/tuple_test.dir/tuple_test.cc.o
[ 23%] Linking CXX executable place_test
[ 23%] Built target place_test
In file included from /repos/paddle_paddle/paddle/fluid/memory/allocation/best_fit_allocator_test.cc:21:0:
/repos/paddle_paddle/build/third_party/install/gtest/include/gtest/gtest.h: In instantiation of 'testing::AssertionResult testing::internal::CmpHelperEQ(const char*, const char*, const T1&, const T2&) [with T1 = long unsigned int; T2 = int]':
/repos/paddle_paddle/build/third_party/install/gtest/include/gtest/gtest.h:1472:23:   required from 'static testing::AssertionResult testing::internal::EqHelper<lhs_is_null_literal>::Compare(const char*, const char*, const T1&, const T2&) [with T1 = long unsigned int; T2 = int; bool lhs_is_null_literal = false]'
/repos/paddle_paddle/paddle/fluid/memory/allocation/best_fit_allocator_test.cc:48:330:   required from here
/repos/paddle_paddle/build/third_party/install/gtest/include/gtest/gtest.h:1444:11: error: comparison between signed and unsigned integer expressions [-Werror=sign-compare]
  ​if (lhs == rhs) {
          ​^
cc1plus: all warnings being treated as errors
paddle/fluid/memory/allocation/CMakeFiles/best_fit_allocator_test.dir/build.make:62: recipe for target 'paddle/fluid/memory/allocation/CMakeFiles/best_fit_allocator_test.dir/best_fit_allocator_test.cc.o' failed
make[2]: *** [paddle/fluid/memory/allocation/CMakeFiles/best_fit_allocator_test.dir/best_fit_allocator_test.cc.o] Error 1
CMakeFiles/Makefile2:1743: recipe for target 'paddle/fluid/memory/allocation/CMakeFiles/best_fit_allocator_test.dir/all' failed
make[1]: *** [paddle/fluid/memory/allocation/CMakeFiles/best_fit_allocator_test.dir/all] Error 2
[ 23%] Linking CXX executable rw_lock_test
In file included from /repos/paddle_paddle/paddle/fluid/platform/enforce_test.cc:18:0:
/repos/paddle_paddle/build/third_party/install/gtest/include/gtest/gtest.h: In instantiation of 'testing::AssertionResult testing::internal::CmpHelperNE(const char*, const char*, const T1&, const T2&) [with T1 = long unsigned int; T2 = int]':
/repos/paddle_paddle/paddle/fluid/platform/enforce_test.cc:55:207:   required from here
/repos/paddle_paddle/build/third_party/install/gtest/include/gtest/gtest.h:1573:145: error: comparison between signed and unsigned integer expressions [-Werror=sign-compare]
cc1plus: all warnings being treated as errors
paddle/fluid/platform/CMakeFiles/enforce_test.dir/build.make:62: recipe for target 'paddle/fluid/platform/CMakeFiles/enforce_test.dir/enforce_test.cc.o' failed
make[2]: *** [paddle/fluid/platform/CMakeFiles/enforce_test.dir/enforce_test.cc.o] Error 1
CMakeFiles/Makefile2:3103: recipe for target 'paddle/fluid/platform/CMakeFiles/enforce_test.dir/all' failed
make[1]: *** [paddle/fluid/platform/CMakeFiles/enforce_test.dir/all] Error 2
[ 23%] Linking CXX executable errors_test
[ 23%] Built target rw_lock_test
[ 23%] Built target errors_test
[ 23%] Linking CXX executable init_test
[ 23%] Built target init_test
[ 23%] Linking CXX executable op_kernel_type_test
[ 23%] Built target op_kernel_type_test
[ 23%] Linking CXX executable threadpool_test
[ 23%] Linking CXX static library libgru_compute.a
[ 23%] Built target gru_compute
[ 23%] Built target threadpool_test
[ 23%] Linking CXX static library libcontext_project.a
[ 23%] Built target context_project
[ 23%] Linking CXX executable op_proto_maker_test
[ 23%] Linking CXX static library libbeam_search.a
[ 23%] Built target beam_search
[ 23%] Built target op_proto_maker_test
[ 23%] Linking CXX static library libtree2col.a
[ 23%] Built target tree2col
[ 24%] Linking CXX executable copy_same_tensor_test
[ 24%] Linking CXX static library libdata_layout_transform.a
[ 24%] Built target data_layout_transform
[ 24%] Built target copy_same_tensor_test
[ 24%] Linking CXX executable tuple_test
[ 24%] Linking CXX static library libsoftmax.a
[ 24%] Built target softmax
[ 24%] Built target tuple_test
[ 24%] Linking CXX static library libselected_rows_functor.a
[ 24%] Built target selected_rows_functor
[ 24%] Linking CXX static library libsequence_pooling.a
[ 24%] Built target sequence_pooling
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by luotao1** [comment]
It is reverted by #21437, and will be fixed by #21434 and #21485
