### ISSUE TITLE
[MKL-DNN] Analyze if it is possible to keep one copy of params not two

### ISSUE THREAD

**Issue by jczaja** [PaddlePaddle/Paddle#21493]
MKL-DNN is often keeping params (weights, bias) in its own blocked format. Essentaily it means that  each operators that is having params is keeping two sets of weights (one paddle Tensors and then converted(reordered) weights into MKL-DNN format). This may lead to increased memory cosnumption. Goal of this is task is to analyze if it is possible to keep only one set of weights&biases not two. For example if it is possible to release paddle weights in inference and keep only mkl-dnn weights.

**Comment by willthefrog** [comment]
please take a look @luotao1

**Comment by jczaja** [comment]
I'm working on that one. Very early results are promising e.g. It should be possible to reduce memory usage of MKL-DNN integration quite close to level of Paddle CPU operators.

**Comment by jczaja** [comment]
@luotao1 , @willthefrog 
It is possible to reduce peak memory consumption of DNNL(mkl-dnn) workloads, by overwritting original
filter's params with DNNL ones. 

Before(develop):
![dnnl_memory](https://user-images.githubusercontent.com/15085062/74055432-51acc300-49e0-11ea-8d1e-81a3b096666c.png)

After(#22505):
![dnnl_memory_optimizer](https://user-images.githubusercontent.com/15085062/74055533-79039000-49e0-11ea-93f5-e451b378621b.png)

Notes:
1) Inference only
2) Currently works for convolutions in FP32 DNNL execution . Should be extended for Fully connected
    params to get very close to Paddle CPU memory consumption
3) Problem is that although I overwrite original params , I do not know how to change outer scope's filter's Tensor *layout* and *data_format* as each of Tensors (one from outer/original scope and other from
execution scope are having they own copy of *layout* and *data_format*. See Question 1
4) Int8 support require more work (need to adjust quantization NCHW16C) I need to get an answer to Question 1
5) Current implementation #22505 is only modifying filter data when *memory_size* of DNNL params of specific op is matching original filter's memory_size
6) As for savings, currently only C-API MobiletNetv1 was tested (more tests are running). Peak Memory Consumption:
* Paddle CPU : ~550 MB
* Before MKL-DNN: ~640MB
* After MKL-DNN: ~580 MB

Questions:
1) Data (allocation) is shared among execution scope and original scope. So it can be overwritten. But How can I change original scope's Tensor's atribute eg. *layout* and *data_format* ?

**Comment by luotao1** [comment]
> Data (allocation) is shared among execution scope and original scope. So it can be overwritten. But How can I change original scope's Tensor's attribute eg. layout and data_format

@jczaja Sorry for the late reply. I am not really sure about:
- Do you want to change or not change the original scope's Tensor's attribute? 
- Is overwriting original filter's params with DNNL ones enough? 
- Could you give an example of why do you want to change the original scope's Tensor's attribute?

@sneaxiy Please help to see this memory optimization issue as well.

**Comment by jczaja** [comment]
@luotao1
1. Yes. I want to change original scope's Tensor's attribute e.g layout_ and format_
2. Changing only params (like #22505) is partial success and it is a bit hacky.   Apart from data (params) iteself change of layout_ and format_ is needed to save more memory. And it is not hacky solution
3. Without setting layout_ and format_ of original scope's Tensor (representing weights) to
actual values:
a) sizeof(op A MKL-DNN params) >= sizeof(op A Paddle params). In other words size of MKL-DNN params of given operator is bigger than numel()*sizeof(Tensor Data Type). If We want to overwrite
original tensors params we need to set original scope's Tensor attribs as well. otherwise 
execution will crash (on Tensor::check_memory_size()) or produce bad results when
there is serialization  or when  int8 inference comes after fp32 inference there will be baddly quantized params.

**Comment by luotao1** [comment]
> Without setting layout_ and format_ of original scope's Tensor (representing weights) to
actual values

Why not use `set_layout` and `set_format` function?

**Comment by jczaja** [comment]
@luotao1 When execution is inside of mkl-dnn kernel, I have an access to tensor of local scope. So if If use set_layout and set_format it is only on Tensor of local scope. Original Tensor's layout and format are not changed. I can change data of original tensor becuase original tensor and tensor from local scope they both share data. So I can change data of original tensor, but I cannot change layout and format

**Comment by luotao1** [comment]
How about the following way?
- Access the original scope, find the corresponding variable by name, and get the original tensor.
- Then, use `set_layout` and `set_format` on the original tensor.

**Comment by jczaja** [comment]
@luotao1 Sounds good. How can I access original scope from mkl-dnn op ?

**Comment by luotao1** [comment]
How about using `ExecutionContext::scope()` to access original scope?

https://github.com/PaddlePaddle/Paddle/blob/1b8fe70e482f38941921759492f0c8ec76e29d6a/paddle/fluid/framework/operator.h#L255

Here is `cudnn_lstm_op.cc` example:
https://github.com/PaddlePaddle/Paddle/blob/1b8fe70e482f38941921759492f0c8ec76e29d6a/paddle/fluid/operators/cudnn_lstm_op.cu.cc#L64-L67

But it is not recommended to use `scope->Var()` to create a new variable in an Op.

**Comment by jczaja** [comment]
@luotao1 Many thanks for example, I will check that soon
