### ISSUE TITLE
请问如何同时获得两个模型的梯度信息

### ISSUE THREAD

**Issue by y72428026** [PaddlePaddle/Paddle#21490]
1. 使用的框架是 :PaddlePaddle 1.5.1(python 3.7)
2. 具体的需求就是，载入resnet模型以及mobilenet模型，对输入照片进行分类，然后分别求输入的梯度然后加权相加，利用梯度信息产生对抗样本；
3. 目前遇到的问题是，我单独载入两个模型之一，然后对图像进行分类、对输入求梯度是没问题的。但没法同时使用两个模型。举个例子，后载入的mobilenet, clone的预测模型可以正确分类输入图片的类别，但前载入的resnet clone的预测模型的输出会是和类别完全没关系的值。梯度信息也是如此。
4. 查阅了一些资料后，我猜测是后载入的模型的参数覆盖了前一个模型的name相同的参数。但我不知道怎么样才能分开他们的参数，最终使得两个模型能够同时正确预测图片的类别，同时对输入图片求梯度。麻烦各位大佬解答一下orz

**Comment by willthefrog** [comment]
可以尝试用两套startup和main program分别加载两个模型, 然后手动进行`optimizer.backward`获得gradient。注意Input variable 需要指定`stop_gradient=False` 保证梯度传导。
