### ISSUE TITLE
profiler的代码示例跑不通

### ISSUE THREAD

**Issue by luotao1** [PaddlePaddle/Paddle#21507]
### 问题来源
@lanxianghit 
### 问题描述
运行[profiler的代码示例]( https://www.paddlepaddle.org.cn/documentation/docs/zh/api_cn/profiler_cn/profiler_cn.html#profiler)，出现
![image](https://user-images.githubusercontent.com/6836917/70026114-e3abe000-15d9-11ea-912d-a28d67de64ca.png)
版本号：1.6.1，即使用`pip install paddlepaddle-gpu` 安装的。
### 目前现象
使用develop分支编译后，可以正确运行
![image](https://user-images.githubusercontent.com/6836917/70026193-22419a80-15da-11ea-97ad-4773764940d4.png)

**Comment by DDDivano** [comment]
这个问题在同一代码文件运行完cuda_profiler case后运行profiler会复现，直接运行issue中代码未能复现。
![image](https://user-images.githubusercontent.com/10734244/70027252-adbc2b00-15dc-11ea-86f8-35efc5bfb736.png)
