### ISSUE TITLE
Why paddle/majel depends on libpaddle_gserver.a

### ISSUE THREAD

**Issue by wangkuiyi** [PaddlePaddle/Paddle#2150]
```
λ 90b088504db5 /paddle/build {move_tests} make -j12 place_test/fast
make[1]: *** No rule to make target 'paddle/gserver/libpaddle_gserver.a', needed by 'paddle/majel/place_test'.  Stop.
make[1]: *** Waiting for unfinished jobs....
```

**Comment by wangkuiyi** [comment]
I found the reason: I defined unit tests in `paddle/majel` by calling `add_unittest` defined in [`cmake/util.cmake`](https://github.com/PaddlePaddle/Paddle/blob/develop/cmake/util.cmake).  However,

**Comment by wangkuiyi** [comment]
Also we should 

- remove paddle_test_util https://github.com/PaddlePaddle/Paddle/issues/2153
- remove paddle_test_main https://github.com/PaddlePaddle/Paddle/issues/2152

**Comment by gangliao** [comment]
Now, our refactorization is completely independent to old paddle. So I close this issue
