### ISSUE TITLE
density_prior_box 代码示例错误

### ISSUE THREAD

**Issue by luotao1** [PaddlePaddle/Paddle#21509]
http://ci.paddlepaddle.org/viewLog.html?buildId=231487&tab=buildLog&buildTypeId=YYTest_PrCiCpuPy2&logTab=tree&filter=all&_focus=13387#_state=112
![image](https://user-images.githubusercontent.com/6836917/70027314-d512f800-15dc-11ea-8d6c-ec6a65441bf4.png)

CI没有拦截住。

**Comment by tianshuo78520a** [comment]
[21467](https://github.com/PaddlePaddle/Paddle/pull/21467) 这个PR是修复这个问题，需要先把有问题的代码示例先修改好才能修复这个问题

**Comment by luotao1** [comment]
close due to #21506 and #21467
