### ISSUE TITLE
cmake error about gtest

### ISSUE THREAD

**Issue by wangkuiyi** [PaddlePaddle/Paddle#2151]
In the development container, after running

```
cd /paddle/build
cmake -DCUDNN_ROOT=/usr/ ..
```

I ran 

```
make -j12 place_test
```

where `place_test` is a target I created by adding 

```
add_unittest(place_test place_test.cc)
```
to  `paddle/majel/CMakeLists.txt`.

However, `make` complains about building the libgtest:

```
Scanning dependencies of target place_test
make[3]: *** No rule to make target '../paddle/majel/third_party/install/gtest/lib/libgtest.a', needed by 'paddle/majel/place_test'.  Stop.
```

**Comment by helinwang** [comment]
This is probably fixed, since the gtest in current refactor is working well. Closing for now, please reopen if this issue persists.
