### ISSUE TITLE
chunk_eval num_infer数量大于实际数量

### ISSUE THREAD

**Issue by luzm3** [PaddlePaddle/Paddle#21529]
hi，我在使用chunk_eval的时候发现，num_infer总会大于实际的值，num_label和num_correct是相等的。
![image](https://user-images.githubusercontent.com/45001329/70112970-452f8580-1692-11ea-82ee-785c706695ab.png)
比如说这个序列，把5555555这个序列也识别成一个chunk，所以在这个序列中识别出两个chunk，但是事实上它只有一个，请问这是怎么回事额，感谢感谢

**Comment by zhiqiu** [comment]
您好，请提供一下详细的问题描述，包括：版本、环境，代码等。

**Comment by luzm3** [comment]
版本1.5.1post97
环境是Linux？
![image](https://user-images.githubusercontent.com/45001329/70130872-555c5a80-16bc-11ea-8130-f3e9f80c6d3b.png)

![image](https://user-images.githubusercontent.com/45001329/70130801-2ba33380-16bc-11ea-8b58-9362c1d03dd3.png)

**Comment by luzm3** [comment]
![image](https://user-images.githubusercontent.com/45001329/70131370-285c7780-16bd-11ea-9e60-419b61b45c56.png)
这个是我的字典

**Comment by guoshengCS** [comment]
使用以下代码能够复现问题
```python
import paddle.fluid as fluid
import paddle.fluid.layers as layers

def to_lodtensor(data, place, lod=None):
    data_tensor = fluid.LoDTensor()
    data_tensor.set(data, place)
    if lod is not None:
        data_tensor.set_lod(lod)
    return data_tensor

predict = layers.data(name="predict",
                      shape=[-1, 1],
                      lod_level=2,
                      append_batch_size=False)
label = layers.data(name="label",
                    shape=[-1, 1],
                    lod_level=2,
                    append_batch_size=False)

(precision, recall, f1_score, num_infer_chunks, num_label_chunks,
 num_correct_chunks) = layers.chunk_eval(predict,
                                         label,
                                         chunk_scheme='IOB',
                                         num_chunk_types=4)
layers.Print(num_infer_chunks)

place = fluid.CPUPlace()
executor = fluid.Executor(place)

predict_data = np.array([8, 8, 2, 3, 3, 8, 8, 3, 3, 3, 8, 8],
                        dtype=np.int64)[:, None]
feed_dict = {
    "predict": to_lodtensor(predict_data, place, [[0, predict_data.shape[0]]]),
    "label": to_lodtensor(predict_data, place, [[0, predict_data.shape[0]]])
}
executor.run(feed=feed_dict)
```

原因的话还在排查中，我们看下是否有bug

**Comment by luzm3** [comment]
👌，谢谢！

**Comment by guoshengCS** [comment]
这个在代码实现上确实是对`8, 8, 3, 3, 3`这种有相应的处理，如下 https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/fluid/operators/chunk_eval_op.h#L99
```C++
  bool ChunkBegin(int prev_tag, int prev_type, int tag, int type,
                  int other_chunk_type, int tag_begin, int tag_inside,
                  int tag_end, int tag_single) const {
    if (prev_type == other_chunk_type) return type != other_chunk_type;
    if (type == other_chunk_type) return false;
    if (type != prev_type) return true;
    if (tag == tag_begin) return true;
    if (tag == tag_inside) return prev_tag == tag_end || prev_tag == tag_single;
    if (tag == tag_end) return prev_tag == tag_end || prev_tag == tag_single;
    if (tag == tag_single) return true;
    return false;
  }
```
第一个3时，会执行`if (prev_type == other_chunk_type) return type != other_chunk_type;`，会算作chunk的开始，应该也不算是bug，可以先根据需要统计方式对进行下过滤

**Comment by luzm3** [comment]
好的

**Comment by luzm3** [comment]
> 这个在代码实现上确实是对`8, 8, 3, 3, 3`这种有相应的处理，如下 https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/fluid/operators/chunk_eval_op.h#L99
> 
> ```c++
>   bool ChunkBegin(int prev_tag, int prev_type, int tag, int type,
>                   int other_chunk_type, int tag_begin, int tag_inside,
>                   int tag_end, int tag_single) const {
>     if (prev_type == other_chunk_type) return type != other_chunk_type;
>     if (type == other_chunk_type) return false;
>     if (type != prev_type) return true;
>     if (tag == tag_begin) return true;
>     if (tag == tag_inside) return prev_tag == tag_end || prev_tag == tag_single;
>     if (tag == tag_end) return prev_tag == tag_end || prev_tag == tag_single;
>     if (tag == tag_single) return true;
>     return false;
>   }
> ```
> 
> 第一个3时，会执行`if (prev_type == other_chunk_type) return type != other_chunk_type;`，会算作chunk的开始，应该也不算是bug，可以先根据需要统计方式对进行下过滤

多谢！
