### ISSUE TITLE
Should move content in /paddle/testing/TestUtil.cpp to various packages

### ISSUE THREAD

**Issue by wangkuiyi** [PaddlePaddle/Paddle#2153]
For example, [function `makeRandomSparseMatrix `](https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/testing/TestUtil.cpp#L31) should be moved to `paddle/math`, where Matrix was defined.

**Comment by luotao1** [comment]
But the function `generateSequenceStartPositions` is related to `gserver` and `math` folders. 
```
test_Evaluator.cpp (paddle\gserver\tests)
test_matrixCompare.cpp (paddle\math\tests)
test_NetworkCompare.cpp (paddle\gserver\tests)
test_RecurrentLayer.cpp (paddle\gserver\tests)
test_WarpCTCLayer.cpp (paddle\gserver\tests)
```

**Comment by gongweibao** [comment]
Close it since not activate.
Feel free to reopen it.
