### ISSUE TITLE
node0结束后其他节点不会自动结束

### ISSUE THREAD

**Issue by webary** [PaddlePaddle/Paddle#21534]
- 版本、环境信息：
    1）PaddlePaddle版本：v1.4.1
- 训练信息
    1）多机
- 复现信息：train_loop中每一轮评估后检查是否早停了（看test-acc是否n轮未提升），如果早停就跳出循环，并执行self.exe.close()。然后其他节点仍然继续跑着，不会主动停止。
- 问题描述：其他节点仍然执行，资源一直不释放，达不到早停效果。

**Comment by zhiqiu** [comment]
您好，多机训练建议使用下fleet接口。[使用FleetAPI进行分布式训练](https://www.paddlepaddle.org.cn/documentation/docs/zh/user_guides/howto/training/fleet_api_howto_cn.html)
