### ISSUE TITLE
Unknown CMake command "cc_library"

### ISSUE THREAD

**Issue by welfred** [PaddlePaddle/Paddle#21539]
1）PaddlePaddle版本：1.6
    2）操作系统：windows10
    3）cmake版本：cmake version 3.15.5
    4）生成Demo_ci的solution文件,  执行：cmake .. -G "Visual Studio 14 2015" -A x64 -DWITH_GPU=ON -DWITH_MKL=ON -DWITH_STATIC_LIB=ON -DCMAKE_BUILD_TYPE=Release -DDEMO_NAME=simple_on_word2vec -DPADDLE_LIB=D:\codes\fluid_inference_install_dir

     会报错：
     -- Selecting Windows SDK version  to target Windows 10.0.18362.
CMake Error at details/CMakeLists.txt:16 (cc_library):
  Unknown CMake command "cc_library".
    -- Configuring incomplete, errors occurred!

**Comment by zhiqiu** [comment]
@silingtong123 请看下这个windows编译问题。

**Comment by silingtong123** [comment]
请给出具体复现环境，包括但不限于预测库版本，demo文件地址，CPU信息，GPU信息，CUDA， CUDNN版本等等

**Comment by silingtong123** [comment]
> ```
> 1）PaddlePaddle版本：1.6
> 2）操作系统：windows10
> 3）cmake版本：cmake version 3.15.5
> 4）生成Demo_ci的solution文件,  执行：cmake .. -G "Visual Studio 14 2015" -A x64 -DWITH_GPU=ON -DWITH_MKL=ON -DWITH_STATIC_LIB=ON -DCMAKE_BUILD_TYPE=Release -DDEMO_NAME=simple_on_word2vec -DPADDLE_LIB=D:\codes\fluid_inference_install_dir
> 
>  会报错：
>  -- Selecting Windows SDK version  to target Windows 10.0.18362.
> ```
> 
> CMake Error at details/CMakeLists.txt:16 (cc_library):
> Unknown CMake command "cc_library".
> -- Configuring incomplete, errors occurred!

请给出具体复现环境，包括但不限于预测库版本，demo文件地址，CPU信息，GPU信息，CUDA， CUDNN版本等等

你应该在cmake命令指定CUDA的库目录，例如-DCUDA_LIB=“D:\\cuda\\lib\\x64”

**Comment by welfred** [comment]
@silingtong123 
指定CUDA库目录后问题依旧。
操作系统：win10 家庭中文版
CPU：i5-9400F @2.90G
预测库版本：GIT COMMIT ID: 53f1e024d4dcffe76d5b8b7a996eb7ed2ac802cd
demo文件路径：D:\Paddle\paddle\fluid\inference\api\demo_ci
CUDA:cuda_10.1.243_426.00_win10
GPU: GTX1660
CUDNN:windows10-x64-v7.6.5.32

**Comment by silingtong123** [comment]
> cuda_10.1

你使用的预测库是自己编译的还是官方下载的预测库？官方下载地址https://www.paddlepaddle.org.cn/documentation/docs/zh/advanced_usage/deploy/inference/windows_cpp_inference.html

**Comment by silingtong123** [comment]
> @silingtong123
> 指定CUDA库目录后问题依旧。
> 操作系统：win10 家庭中文版
> CPU：i5-9400F @2.90G
> 预测库版本：GIT COMMIT ID: [53f1e02](https://github.com/PaddlePaddle/Paddle/commit/53f1e024d4dcffe76d5b8b7a996eb7ed2ac802cd)
> demo文件路径：D:\Paddle\paddle\fluid\inference\api\demo_ci
> CUDA:cuda_10.1.243_426.00_win10
> GPU: GTX1660
> CUDNN:windows10-x64-v7.6.5.32

你使用的预测库是自己编译的还是官方下载的预测库？官方下载地址https://www.paddlepaddle.org.cn/documentation/docs/zh/advanced_usage/deploy/inference/windows_cpp_inference.html

**Comment by welfred** [comment]
> > @silingtong123
> > 指定CUDA库目录后问题依旧。
> > 操作系统：win10 家庭中文版
> > CPU：i5-9400F @2.90G
> > 预测库版本：GIT COMMIT ID: [53f1e02](https://github.com/PaddlePaddle/Paddle/commit/53f1e024d4dcffe76d5b8b7a996eb7ed2ac802cd)
> > demo文件路径：D:\Paddle\paddle\fluid\inference\api\demo_ci
> > CUDA:cuda_10.1.243_426.00_win10
> > GPU: GTX1660
> > CUDNN:windows10-x64-v7.6.5.32
> 
> 你使用的预测库是自己编译的还是官方下载的预测库？官方下载地址https://www.paddlepaddle.org.cn/documentation/docs/zh/advanced_usage/deploy/inference/windows_cpp_inference.html

下载的是官方的，没有自己编译，下载的是这个cuda10.0_cudnn7_avx_mkl

**Comment by silingtong123** [comment]
> > > @silingtong123
> > > 指定CUDA库目录后问题依旧。
> > > 操作系统：win10 家庭中文版
> > > CPU：i5-9400F @2.90G
> > > 预测库版本：GIT COMMIT ID: [53f1e02](https://github.com/PaddlePaddle/Paddle/commit/53f1e024d4dcffe76d5b8b7a996eb7ed2ac802cd)
> > > demo文件路径：D:\Paddle\paddle\fluid\inference\api\demo_ci
> > > CUDA:cuda_10.1.243_426.00_win10
> > > GPU: GTX1660
> > > CUDNN:windows10-x64-v7.6.5.32
> > 
> > 
> > 你使用的预测库是自己编译的还是官方下载的预测库？官方下载地址https://www.paddlepaddle.org.cn/documentation/docs/zh/advanced_usage/deploy/inference/windows_cpp_inference.html
> 
> 下载的是官方的，没有自己编译，下载的是这个cuda10.0_cudnn7_avx_mkl

你执行cmake命令的目录是D:\Paddle\paddle\fluid\inference\api\demo_ci\build吗？看起来你在D:\Paddle\paddle\fluid\inference\api\build下执行的CMAKE命令，你确认一下？正常情况下不会使用到details/CMakeLists.txt文件，只会使用到demo_ci\CMakeLists.txt文件

**Comment by welfred** [comment]
> D:\Paddle\paddle\fluid\inference\api\demo_ci

完全按照官方步骤，在D:\Paddle\paddle\fluid\inference\api\demo_ci下建立了build目录，然后在这个目录里面执行cmake

**Comment by silingtong123** [comment]
> > D:\Paddle\paddle\fluid\inference\api\demo_ci
> 
> 完全按照官方步骤，在D:\Paddle\paddle\fluid\inference\api\demo_ci下建立了build目录，然后在这个目录里面执行cmake

有完整的log截图吗？包括目录的
类似
![image](https://user-images.githubusercontent.com/35439432/70212766-e130be00-1772-11ea-8fd2-26257fa6d34e.png)
我在D:\Paddle\paddle\fluid\inference\api\build下执行CMAKE命令，能复现你的问题，你在D:\Paddle\paddle\fluid\inference\api\demo_ci\build下使用CMAKE命令只会使用到demo_ci\CMakeLists.txt，还可能使用到demo_ci子目录下的CMakeLists.txt文件，但此处demo_ci没有除build外的子目录，除非你修改了CMAKE文件

你的paddle源码中最新的commit id信息是？

**Comment by welfred** [comment]
没有修改过CMAKE文件，原始代码中demo_ci目录下也没有子目录，build是自己建立的。
commit id：6ce49eea79b11ff258514b5847e8089b6ab12ef7

**Comment by silingtong123** [comment]
> 没有修改过CMAKE文件，原始代码中demo_ci目录下也没有子目录，build是自己建立的。
> commit id：6ce49eea79b11ff258514b5847e8089b6ab12ef7

希望您能提供完整的log信息

**Comment by welfred** [comment]
> > 没有修改过CMAKE文件，原始代码中demo_ci目录下也没有子目录，build是自己建立的。
> > commit id：6ce49eea79b11ff258514b5847e8089b6ab12ef7
> 
> 希望您能提供完整的log信息
详见附件
[CMakeOutput.log](https://github.com/PaddlePaddle/Paddle/files/3925640/CMakeOutput.log)

**Comment by silingtong123** [comment]
你有CMAKE命令执行时的完整信息吗
类似于这样的截图
![image](https://user-images.githubusercontent.com/35439432/70215340-391df380-1778-11ea-99e0-90436943549d.png)
或者使用重定向方式生成的log文件
在build目录下执行重定向的CMAKE命令：
cmake .. -G "Visual Studio 14 2015" -A x64 -DWITH_GPU=ON -DWITH_MKL=ON -DWITH_STATIC_LIB=ON -DCMAKE_BUILD_TYPE=Release -DDEMO_NAME=simple_on_word2vec -DPADDLE_LIB=D:\Download\inference_lib\fluid_inference_install_dir_161_107\fluid_inference_install_dir  -DCUDA_LIB=D:\10_1\lib\x64 >mylog.txt 2>&1
![image](https://user-images.githubusercontent.com/35439432/70216038-b5650680-1779-11ea-89b3-660ce3d7e1b8.png)

生成的mylog.txt文件就在build目录中
![image](https://user-images.githubusercontent.com/35439432/70215944-8f3f6680-1779-11ea-86f2-e442cc444332.png)

你应该再确认一下你的所在目录

**Comment by welfred** [comment]
> 你有CMAKE命令执行时的完整信息吗
> 类似于这样的截图
> ![image](https://user-images.githubusercontent.com/35439432/70215340-391df380-1778-11ea-99e0-90436943549d.png)
> 或者使用重定向方式生成的log文件
> 在build目录下执行重定向的CMAKE命令：
> cmake .. -G "Visual Studio 14 2015" -A x64 -DWITH_GPU=ON -DWITH_MKL=ON -DWITH_STATIC_LIB=ON -DCMAKE_BUILD_TYPE=Release -DDEMO_NAME=simple_on_word2vec -DPADDLE_LIB=D:\Download\inference_lib\fluid_inference_install_dir_161_107\fluid_inference_install_dir -DCUDA_LIB=D:\10_1\lib\x64 >mylog.txt 2>&1
> ![image](https://user-images.githubusercontent.com/35439432/70216038-b5650680-1779-11ea-89b3-660ce3d7e1b8.png)
> 
> 生成的mylog.txt文件就在build目录中
> ![image](https://user-images.githubusercontent.com/35439432/70215944-8f3f6680-1779-11ea-86f2-e442cc444332.png)
> 
> 你应该再确认一下你的所在目录

我是按照你们帮助文档中的目录建立build，跟你的例子差了一级目录。
我的目录是：D:/Paddle/paddle/fluid/inference/api/demo_ci/build
你的目录是：D:/Paddle/paddle/fluid/inference/api/build
[mylog.txt](https://github.com/PaddlePaddle/Paddle/files/3925775/mylog.txt)


>

**Comment by silingtong123** [comment]
根据你的log信息，你并没有在build目录里执行cmake命令，而是在D:\Paddle\paddle\fluid\inference\api\demo_ci目录下执行的，如你log图中所示
![image](https://user-images.githubusercontent.com/35439432/70219297-8b164780-177f-11ea-982d-ddb6fa22e263.png)
正常情况下，你的CMakeFiles文件夹，应该在
D:\Paddle\paddle\fluid\inference\api\demo_ci\build
![image](https://user-images.githubusercontent.com/35439432/70219611-14c61500-1780-11ea-8da7-7dae05d7a143.png)
而不是D:\Paddle\paddle\fluid\inference\api\demo_ci目录里
![image](https://user-images.githubusercontent.com/35439432/70219657-27404e80-1780-11ea-9fc4-d332b8ccf590.png)

你应该进入到D:\Paddle\paddle\fluid\inference\api\demo_ci\build里执行CMAKE命令，请先清空对应build目录，再执行命令

**Comment by welfred** [comment]
我确定是在D:\Paddle\paddle\fluid\inference\api\demo_ci\build目录里执行cmake命令的，如图所示：
![baidu1](https://user-images.githubusercontent.com/4965297/70223271-65407100-1786-11ea-92c5-d50bc2a605b8.jpg)
build目录是空的，没有CMakeList.txt文件，“cmake..“中的“点点”的意思是到上一层目录去找CMakeList.txt文件？
我的目录结构如图所示：
![baidu2](https://user-images.githubusercontent.com/4965297/70223396-a20c6800-1786-11ea-8300-849200049cfd.jpg)

**Comment by silingtong123** [comment]
你应该保持你demo_ci下的目录干净，删除demo_ci目录下CMakeFiles和CMakeCachE.txt文件 ,然后在清空build目录重新运行CMAKE命令

或者你可以重新下载paddle源码，重新执行一次命令

cmake .. 会到上一层目录中找cmakelist.txt文件,但外部的错误文件会影响在build中cmake命令的执行，经验证在外部demo_ci有错误文件的情况下，会出现该这样的情况，删除文件后可正常构建

**Comment by welfred** [comment]
都清空过无数次了，没用。所以你跟我纠结这么久，其实并不是路径错误的问题，而是可能别的原因。
你验证的过程中，demo_ci 删除了哪个错误文件可正常构建？

**Comment by silingtong123** [comment]
我这边删除demo_ci目录下的CMakeFiles文件夹和CMakeCache.txt文件，在空的build目录中可正常构建

正常情况下demo_ci目录下不应该存在CMakeFiles文件夹和CMakeCache.txt文件

**Comment by ZHOUKAI1** [comment]
> 都清空过无数次了，没用。所以你跟我纠结这么久，其实并不是路径错误的问题，而是可能别的原因。
> 你验证的过程中，demo_ci 删除了哪个错误文件可正常构建？

兄弟，你问题解决了么，我在windows目录下，也是无法cmake

**Comment by AckerlyLau** [comment]
我在编译paddle_inference的时候也出现这个问题，我需要win32版本的paddle_inference，但是官方没有提供32位的版本，自己编译的时候出现在这个错误。
![image](https://github.com/PaddlePaddle/Paddle/assets/32513057/a6a0a93c-207c-45b3-aec6-130852cd292b)
似乎是paddle/utils/string/CMakeLists.txt文件里cc_library的问题？
