### ISSUE TITLE
自己编译Release1.6分支之后Int8无法自动加载calibration参数

### ISSUE THREAD

**Issue by barry2025** [PaddlePaddle/Paddle#21557]
采用如下官方fluid_inference库：
![image](https://user-images.githubusercontent.com/20043808/70200182-98ffa480-174e-11ea-89fa-c3542c6f616f.png)
使用如下设置方式：
![image](https://user-images.githubusercontent.com/20043808/70200257-c3e9f880-174e-11ea-836d-56e985e890d0.png)
运行一次生成校准表后，再运行一次之后infer时间明显加快

自己编译cuda10版本的fluid_inference库，同样的代码，每次运行都在生成校准表。编译version如下：
![image](https://user-images.githubusercontent.com/20043808/70200675-32c75180-174f-11ea-8ece-f062f49a8734.png)

**Comment by cryoco** [comment]
请问是否有将生成的校准表拷贝至模型目录下呢？参考[文档](https://www.paddlepaddle.org.cn/documentation/docs/zh/advanced_usage/deploy/inference/paddle_tensorrt_infer.html#a-name-paddle-trt-int8-paddle-trt-int8-a)第二步，
确认下第二次及之后运行时模型文件夹下存在_opt_cache目录

**Comment by barry2025** [comment]
![image](https://user-images.githubusercontent.com/20043808/70201633-2f819500-1752-11ea-8e5d-c275a4515cfc.png)
模型路径指定为这个就行了是吧，确认是有的。同样的模型地址和代码，采用官方提供的fluid_inference是没有问题的，我自己编译之后有问题，想确认下是代码更新的问题还是我编译的开关问题

**Comment by cryoco** [comment]
能否贴一下第一次运行之后的运行还在生成校准表的log

**Comment by barry2025** [comment]
![image](https://user-images.githubusercontent.com/20043808/70203649-90ac6700-1758-11ea-9df0-3f0573a962db.png)
这是运行万一次之后显示的保存cali文件，然后第二次运行的时候infer速度和第一次生成的时候一致，特别慢

**Comment by NHZlX** [comment]
_opt_cache下是否有art_calib_* 这些文件，贴一下吧

**Comment by barry2025** [comment]
![image](https://user-images.githubusercontent.com/20043808/70207417-b12eee00-1765-11ea-947d-b0ad2d98a39d.png)
确实是有的，重新运行一次，模型地址指向带有_opt_cache的模型，运行到最后还会出现Generating TRT Calibration data。发现第二次之后，第三次再运行又可以加载了，cali文件如下：
![image](https://user-images.githubusercontent.com/20043808/70207950-349d0f00-1767-11ea-828d-478320b6b3d3.png)
所以这个跟生成的校准文件会有关系吗？

**Comment by barry2025** [comment]
我自己也无法复现，重新删除_opt_cache，再跑两次也不行了，跑了很多次，生成了一堆calib文件：
![image](https://user-images.githubusercontent.com/20043808/70211502-3a4b2280-1770-11ea-86ef-ff90b8454630.png)
成功运行一次int8 inference后又开始生成calib了：
![image](https://user-images.githubusercontent.com/20043808/70211569-69619400-1770-11ea-9886-e91c866df87c.png)
如果找不到，应该每次都会重新运行calib，但是这个是成功运行一次之后又开始calib了，实在搞不懂是有啥问题

**Comment by barry2025** [comment]
![image](https://user-images.githubusercontent.com/20043808/70214182-ed6a4a80-1775-11ea-8052-9d38a6157570.png)

![image](https://user-images.githubusercontent.com/20043808/70214057-b136ea00-1775-11ea-84a1-05b47d9b84bb.png)

这是连续跑的两次，前面一次还显示RUN Paddle TRT int8 calibration mode...，然后再跑一次就出现This process is generating calibration table for Paddle TRT int8...，

**Comment by NHZlX** [comment]
可能是bug，branch是develop的代码么，另外方便发一下模型么

**Comment by barry2025** [comment]
branch采用的是release/1.6 采用develop分支编译后，trt_fp32没问题，int8报错：
![image](https://user-images.githubusercontent.com/20043808/70223136-23afc600-1786-11ea-85d9-caef41ebb976.png)

模型链接，里面包含_opt_cache文件：https://bj.bcebos.com/v1/mct-imagedb/tangxin-bos/yolov3_r34_voc.tar.gz

**Comment by barry2025** [comment]
今天早上重新切换release/1.6 分支， commit: 0a4002f，运行官方sample例子fluid_generate_calib_test 对mobilenet进行校准 mobilenetv1出现以下问题，但是校准集可以生成：
![image](https://user-images.githubusercontent.com/20043808/70312737-2fb38a80-184f-11ea-9266-f74646e81d7d.png)

运行yolov3 int8出现如下问题，trt_fp32和trt_fp16没有问题
![image](https://user-images.githubusercontent.com/20043808/70311535-caf73080-184c-11ea-85eb-ec6a09eef24e.png)
这是采用的config参数：
![image](https://user-images.githubusercontent.com/20043808/70312818-5671c100-184f-11ea-905a-983fd2a9df21.png)

**Comment by NHZlX** [comment]
此问题已经复现，正在看

问题已修复。请拉取最新的release/1.6进行测试。

https://github.com/PaddlePaddle/Paddle/pull/21622
https://github.com/PaddlePaddle/Paddle/pull/21619

**Comment by jeng1220** [comment]
@barry2025,
Has your problem been solved?
