### ISSUE TITLE
如何释放一个建好的计算图（program）

### ISSUE THREAD

**Issue by xixiaoyao** [PaddlePaddle/Paddle#21568]
如题，一个program建好后，不需要了，那么如何将这个program以及里面的vars都销毁呢？（目的是为了销毁旧的vars，建立新的同名vars）

Thanks

**Comment by GaoWei8** [comment]
使用的是Python代码吗？可以不引用定义好的program或者var或设置为0

**Comment by xixiaoyao** [comment]
是python。哪怕不引用旧的program，也会报错，因为创建新的program的时候一些新创建的var在旧的program里面已经存在了，会提示已经存在。你说的设置为0是怎么做呢？意思是释放旧的vars吗？

**Comment by GaoWei8** [comment]
组网的时候，定义自己的Program就行，不要写到默认的program里面，可以参考https://github.com/PaddlePaddle/models/blob/develop/PaddleNLP/language_model/train.py#L123
![b4487d9341e2a0be1c44e8c31](https://user-images.githubusercontent.com/53294385/70304690-75675780-183d-11ea-95fb-aa09c178a620.png)
