### ISSUE TITLE
Maybe we need a guide for converting v1 configs to v2

### ISSUE THREAD

**Issue by pengli09** [PaddlePaddle/Paddle#2156]
Maybe it is useful to provide a guide for converting v1 configs to v2 such that v1 API users can simply go through the guide and begin to use the v2 APIs happily. However, currently everyone needs to read nearly all the documents before moving to v2 API.

**Comment by wangkuiyi** [comment]
I believe so.

A related but might be a more urgent issue is that we need to make sure that the v2 API's implementation works.  Currently, we have issues like error messages are not readable.

**Comment by pengli09** [comment]
Got it.

If we are not sure about the correctness of v2 API currently, shall we give some hint of risk on the homepage? Otherwise, I'm worried that if encountering strange errors frequently, new users will be frightened away.
