### ISSUE TITLE
模型预测过程报错PaddleCheckError: Cannot find fetched variable (concat_25.tmp_0) (Perhaps the main_program is not set to ParallelExecutor)

### ISSUE THREAD

**Issue by Weili-NLP** [PaddlePaddle/Paddle#21570]
- 版本、环境信息：
    1）PaddlePaddle版本：1.6.1
    2）GPU：Tesla V100、CUDA 9.2, CUDNN 7.6
    4）系统环境：Centos 7, Python 3.6.9

- 错误信息：

![d1d0ada4dc9de3159ffabe2ed](https://user-images.githubusercontent.com/25901705/70216264-2a384080-177a-11ea-9e05-4e2d58b8a966.png)

复现信息：
`main_prog = fluid.default_main_program()
 startup_prog = fluid.default_startup_program()

with fluid.program_guard(main_prog, startup_prog):
      with fluid.unique_name.guard():
             # create model here

test_prog = main_prog.clone(for_test=True)
exe = fluid.Executor(place)
exe.run(startup_prog)

fluid.io.load_params(
        executor=exe,
        dirname=args.init_from_params,
        main_program=test_prog)

compiled_test_prog = fluid.CompiledProgram(test_prog)
outputs = exe.run(program=compiled_test_prog,
                                                   fetch_list=[out_ids.name],
                                                   return_numpy=False)`

**Comment by GaoWei8** [comment]
可以复查一下这个变量(cancat25.temp_0)是否使用到。打印所有varible看一下。

**Comment by Weili-NLP** [comment]
> 可以复查一下这个变量(cancat25.temp_0)是否使用到。打印所有varible看一下。

通过下面得函数打印test_prog，里面包含变量(cancat25.temp_0)
def print_prog(prog):

    fw = open('program.txt', 'w')
    for name, value in sorted(six.iteritems(prog.block(0).vars)):
        fw.write('name={} value={}'.format(name, value))
    for op in prog.block(0).ops:
        fw.write("op type is {}".format(op.type))
        fw.write("op inputs are {}".format(op.input_arg_names))
        fw.write("op outputs are {}".format(op.output_arg_names))
        for key, value in sorted(six.iteritems(op.all_attrs())):
            if key not in ['op_callstack', 'op_role_var']:
                fw.write(" [ attrs: {}:   {} ]".format(key, value))
    fw.close()

compiled_test_prog 无法打印，没有block属性

**Comment by GaoWei8** [comment]
可以复查一下这个变量(cancat25.temp_0)是否使用到。打印所有varible看一下。
组完网络，在run之前print，可以找到这个变量吗？

**Comment by Weili-NLP** [comment]
> 在run之前print，可以找到这个变量吗？

就是在run之前打印的，打印出来有那个变量。只是compiled_test_prog 无法打印，没有block属性。

**Comment by GaoWei8** [comment]
> > 在run之前print，可以找到这个变量吗？
> 
> 就是在run之前打印的，打印出来有那个变量。只是compiled_test_prog 无法打印，没有block属性。

fluid.CompiledProgram(）这个接口会进行优化，使用普通接口paddle.fluid.Program试一下呢？
