### ISSUE TITLE
设计文档在paddlepaddle.org的展示

### ISSUE THREAD

**Issue by luotao1** [PaddlePaddle/Paddle#2158]
paddlepaddle.org网站上还可以展示的文档：
- 设计文档：doc/design目录下的所有md文档
- benchmark的文档：benchmark/README.md

**Comment by wangkuiyi** [comment]
I don't think that we need to add special sections on paddlepaddle.org to present design docs and benchmarks. It seems that we can just share URLs pointing to where they reside in Github repo.

**Comment by Canpio** [comment]
Close this issue due to inactivity. please feel free to reopen it if more information is available.
