### ISSUE TITLE
打开EnableMemoryOptim开关，如果EnableMKLDNN预测，terminate called after throwing an instance of 'mkldnn::error'

### ISSUE THREAD

**Issue by chalsliu** [PaddlePaddle/Paddle#21598]
在打开EnableMemoryOptim开关的情况下，如果EnableMKLDNN预测
有错误
terminate called after throwing an instance of 'mkldnn::error'
  what():  std::exception

**Comment by luotao1** [comment]
#21826 disable memory optimization pass when mkldnn is on
