### ISSUE TITLE
Shall we add a link to older version docs on paddle's homepage?

### ISSUE THREAD

**Issue by pengli09** [PaddlePaddle/Paddle#2159]
As the major users are still using v1 APIs, shall we add a link to older version docs on paddle's homepage? Otherwise, it will cause a lot of unnecessary troubles to v1 API users.

**Comment by luotao1** [comment]
英文版：
- 将http://www.paddlepaddle.org/的About Us改成Version，做成和English相同的下拉菜单
- 将http://www.paddlepaddle.org/release_doc/中的三个En放到上述下拉菜单中，名字分别为r0.10.0, r0.9.0, r0.9.0a0

中文版：
- 将http://www.paddlepaddle.org/的index_cn.html的“关于我们”改成“版本”，做成和中文相同的下拉菜单
- 将http://www.paddlepaddle.org/release_doc/中的三个Cn放到上述下拉菜单中，名字分别为r0.10.0, r0.9.0, r0.9.0a0

**Comment by chrisxu2016** [comment]
fixed
