### ISSUE TITLE
sequence_pool op 的相关疑问~

### ISSUE THREAD

**Issue by xygaoyuan** [PaddlePaddle/Paddle#21597]
使用paddle版本：v1.6.1

问题：
一个2-level lod-tensor经过 sequence-pool 处理按道理应该变成 1-level lod-tensor，但是输出变量的lod-level = 0

sequence_pool op 代码：
https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/fluid/operators/sequence_ops/sequence_pool_op.cc
这个代码中好像没看到 SetLoDLevel 操作，是否忘记设置输出变量的lod-level?

盼回复，谢谢

**Comment by yiicy** [comment]
请问这个问题是在组网阶段报的错吗

**Comment by xygaoyuan** [comment]
是的

**Comment by xygaoyuan** [comment]
> 请问这个问题是在组网阶段报的错吗

是的，组网阶段报的错误
