### ISSUE TITLE
同一个进程启动两个模型报错，已加入scope

### ISSUE THREAD

**Issue by littlepan0413** [PaddlePaddle/Paddle#21591]
1、按照教程修改如下，加入scope
![image](https://user-images.githubusercontent.com/6512760/70290552-3b815b80-1813-11ea-9fff-dcfc50bc34ae.png)
启动会报错
![image](https://user-images.githubusercontent.com/6512760/70290584-56ec6680-1813-11ea-972d-af025b83231b.png)

2、把后面的run也加入到scope范围内，运行没问题，预测报错
![image](https://user-images.githubusercontent.com/6512760/70290613-72f00800-1813-11ea-9d20-f3e60d682b9a.png)
预测报错信息
![image](https://user-images.githubusercontent.com/6512760/70290635-813e2400-1813-11ea-8145-fa232f7c2e56.png)

**Comment by yiicy** [comment]
https://github.com/PaddlePaddle/Paddle/issues/16661 请参考这个链接试试，应该使用fluid.core.Scope()而不是fluid.Scope()

**Comment by littlepan0413** [comment]
> #16661 请参考这个链接试试，应该使用fluid.core.Scope()而不是fluid.Scope()

报错
![image](https://user-images.githubusercontent.com/6512760/70301725-20741300-1836-11ea-85d5-3e0c0374982f.png)

**Comment by littlepan0413** [comment]
paddle版本1.5
