### ISSUE TITLE
训练模型，跑过几轮后报错paddle.fluid.core.EnforceNotMet或进程killed

### ISSUE THREAD

**Issue by whiker92** [PaddlePaddle/Paddle#21601]
linux虚拟机环境，内存8G

报错信息：
![报错](https://user-images.githubusercontent.com/13618283/70301681-04707180-1836-11ea-88b6-a539334c6546.JPG)

**Comment by yiicy** [comment]
可否在训练过程中实时查看一下内存占用，查看一下是不是内存不足造成的问题

**Comment by whiker92** [comment]
确实是内存不足导致的。节点开的比较多，降低节点可正常运行。
不单是节点多的问题，而是embedding维度太高导致。
