### ISSUE TITLE
yolov3模型训练过程中卡住不动

### ISSUE THREAD

**Issue by itmajing** [PaddlePaddle/Paddle#21602]
- 标题：yolov3模型训练过程中卡住不动
- 版本、环境信息：
    1）PaddlePaddle版本：1.6.1.post107
    2）CPU：i7 7700k
    3）GPU：1080ti
    4）系统环境：win10 conda4.7.12 python3.7.5
- 训练信息
    1）单机单卡
    2）显存信息
    3）Operator信息
- 复现信息：使用PaddleDetection中的yolov3模型训练
- 问题描述：
        使用yolov3_r50vd_dcn模型, 自定义coco数据集, 训练到20000多轮时, 卡住不动;
        使用yolov3_darknet模型, 自定义coco数据集, 训练到9000多轮时, 卡住不动;
![image](https://user-images.githubusercontent.com/24891592/70301777-426d9580-1836-11ea-9147-095dd74a8c5b.png)
![image](https://user-images.githubusercontent.com/24891592/70301801-5a451980-1836-11ea-870e-5af21227d12c.png)

**Comment by yiicy** [comment]
可否提供下显存的信息

**Comment by itmajing** [comment]
@yiicy 
![image](https://user-images.githubusercontent.com/24891592/70404253-64545b80-1a74-11ea-8818-7fd93d368874.png)

**Comment by yiicy** [comment]
你好，windows训练卡住不动的问题我们已经在https://github.com/PaddlePaddle/Paddle/pull/21201/files 这个pr中进行了修复
