### ISSUE TITLE
unitest of ChunkEvaluator show be upgraded to v2 version

### ISSUE THREAD

**Issue by pkuyym** [PaddlePaddle/Paddle#2160]
The location of ChunkEvaluator's unitest configuration is at

> paddle/trainer/tests/chunking.conf

**Comment by luotao1** [comment]
现在 paddle/trainer/tests下面还有很多单测的配置文件是v0版本或v1版本，该如何处理：
![image](https://cloud.githubusercontent.com/assets/6836917/26095934/12f6a36a-3a52-11e7-9eed-85d4d940e547.png)

而且还有二进制的数据集：
- data_bin_part
- mnist_bin_part
