### ISSUE TITLE
paddle有conv1d层吗

### ISSUE THREAD

**Issue by Anikily** [PaddlePaddle/Paddle#21618]
查找了doc发现没有Conv1d，是没有找到吗，还是暂时没有，或者有其他的方式来代替。

**Comment by gfwm2013** [comment]
目前没有这个API，如果想实现conv1d的功能，可按如下顺序进行操作：先进行unsqueeze，再conv2d，最后进行squeeze操作即可。

**Comment by Anikily** [comment]
@gfwm2013 具体在哪一维度上呢？

**Comment by Anikily** [comment]
@gfwm2013 大哥，理我一下啊

**Comment by gfwm2013** [comment]
@Anikily 不好意思，回复慢了…请问你的数据是几维的？如果是3维的，那你可以在第3维或是第4维进行上述操作

**Comment by Anikily** [comment]
@gfwm2013 数据是三维的，我操作了一下，但是提示我squeeze layer is not supported in dygraph mode yet.这可咋办。。
如果现在不能在动态图里实现squeeze的话，那还有别的办法实现conv1d吗？

**Comment by gfwm2013** [comment]
@Anikily 那可以将unsqueeze和squeeze更换成reshape操作，重新试一下

**Comment by Anikily** [comment]
@gfwm2013 如果是B, C, N的话，那我是
fluid.layers.reshape(x, shape=[B, C, N, 1])
Conv2d
x = fluid.layers.reshape(x, shape=[B, C, N])吗？

**Comment by gfwm2013** [comment]
@Anikily 应该是这样的，关于reahspe操作具体可以参考https://www.paddlepaddle.org.cn/documentation/docs/zh/api_cn/layers_cn/reshape_cn.html#reshape
