### ISSUE TITLE
Found regression on BERT inference

### ISSUE THREAD

**Issue by ddokupil** [PaddlePaddle/Paddle#21637]
**System information**
- PaddlePaddle version: 234060f / develop branch
- CPU: including CLX with MKLDNN
- OS Platform Ubuntu 16.04
- Python version: 2.7.12
- Cmake orders
```
 -DCMAKE_BUILD_TYPE=Release -DWITH_GPU=OFF -DWITH_MKLDNN=ON -DWITH_TESTING=ON -DWITH_PROFILER=ON -DWITH_STYLE_CHECK=OFF -DON_INFER=ON -DWITH_INFERENCE_API_TEST=ON
```
- C++version: gcc (Ubuntu 5.4.0-6ubuntu1~16.04.11) 5.4.0 20160609
- API information

**To Reproduce**
Build with above cmake and execute with: 
```bash
/paddle_paddle/build/paddle/fluid/inference/tests/api/test_analyzer_bert
--gtest_filter=Analyzer_bert.profile
--infer_data=/paddle_paddle/build/third_party/inference_demo/bert_emb128/data.txt
--infer_model=/paddle_paddle/build/third_party/inference_demo/bert_emb128/model
--paddle_num_threads=1
--batch_size=1
--repeat=1000
```
**Describe your current behavior**
- Performance on 234060f is 3-4% lower than was on 6cfcbe0 (a committ before)

**Code to reproduce the issue**
**Other info / logs**

**Comment by luotao1** [comment]
@GaoWei8 Please see it.

**Comment by GaoWei8** [comment]
Fix this issue by #21650.

**Comment by ddokupil** [comment]
I can confirm not only it helps with BERT but even produces better results than before regression.

**Comment by Xreki** [comment]
Can you paste the detail performance data here?

**Comment by ddokupil** [comment]
At first I said it helped but cannot prove it anymore, so my previous mesage is invalid. Here are the results:
CPU CLX 6248:
70c073a (release/1.6) fps: 134.699
234060f (regression introduced) fps: 129.938 
Current develop fps: 130.187 

CPU CLX 8280:
6cfcbe0 (pre regression) fps: 143.462
70c073a (release/1.6) fps: 144.5
234060f (regression introduced) fps: 139.224
Fix #21650: fps: 139.194
Current Develop: fps: 139.483

**Comment by bingyanghuang** [comment]
@Xreki We have verified that Gaowei's PR has fixed Bert regression problem. Can this issue be closed?

**Comment by Xreki** [comment]
@ddokupil @bingyanghuang It seems the BERT regression problem is still not fixed yet?

**Comment by bingyanghuang** [comment]
> @ddokupil @bingyanghuang It seems the BERT regression problem is still not fixed yet?

Sorry for the confusion, you are right. I will double check again to give the clear status now.

**Comment by GaoWei8** [comment]
Intel(R)   Xeon(R) Gold 6148:
#21341 (before regression) fps: 114.662
#20972  (regression introduced) fps: 111.629
#21650 fps: 111.36

**Comment by GaoWei8** [comment]
config->DisablePadding();

**Comment by GaoWei8** [comment]
Add an interface to solve the regression: [#22079 ](https://github.com/PaddlePaddle/Paddle/pull/22097)
