### ISSUE TITLE
GPU版编译错误，

### ISSUE THREAD

**Issue by kunde122** [PaddlePaddle/Paddle#21638]
运行ernie中的脚本报错。 
 1）PaddlePaddle版本：gpu版本1.5.1.post107
    2）GPU:Tesla P4，CUDA Version: 9.0，cudnn:7501
    3）系统环境：CentOS Linux release 7.5.1804 (Core)  python3.7
- 安装方式信息：
1）pip安装
2）本地编译,执行sh script/zh_task/ernie_base/run_msra_ner.sh
错误提示：
W1209 17:28:31.056532 232107 init.cc:128] Compiled with WITH_GPU, but no GPU found in runtime.

paddle.fluid.core_avx.EnforceNotMet: cudaGetDeviceCount failed in paddle::platform::GetCUDADeviceCount: CUDA driver version is insufficient for CUDA runtime version at [/paddle/paddle/fluid/platform/gpu_info.cc:97]

**Comment by JepsonWong** [comment]
为什么CUDA9.0安装CUDA10.0的paddle？

![image](https://user-images.githubusercontent.com/16509038/70492590-e3fb2c80-1b3f-11ea-9a19-8590cd19fcc2.png)

**Comment by kunde122** [comment]
> 为什么CUDA9.0安装CUDA10.0的paddle？
> 
> ![image](https://user-images.githubusercontent.com/16509038/70492590-e3fb2c80-1b3f-11ea-9a19-8590cd19fcc2.png)

感谢找到原因了，版本不对
