### ISSUE TITLE
paddle v1.6.1 -DWITH_DSO=OFF gcc482下编译错误

### ISSUE THREAD

**Issue by lllemma** [PaddlePaddle/Paddle#21646]
- 版本、环境信息：
    1）PaddlePaddle版本：paddle v1.6.1
    2）CPU：Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz，-DWITH_MKL=ON，-DWITH_MKLDNN=OFF
    3）GPU：Tesla V100-SXM2，CUDA 10.0.130，CUDNN 7.4.2
    4）系统环境：CentOS release 6.10、Python 2.7.16
- 安装方式信息：
1）本地编译：编译命令        
  cmake .. \
-DWITH_CONTRIB=OFF \
-DWITH_MKL=ON  \
-DWITH_MKLDNN=OFF \
-DWITH_TESTING=ON \
-DCMAKE_BUILD_TYPE=Release \
-DWITH_INFERENCE_API_TEST=ON \
-DON_INFER=ON \
-DWITH_PYTHON=ON \
-DWITH_DSO=OFF
- 复现信息：
- 问题描述：请详细描述您的问题，同步贴出报错信息、日志/代码关键片段
有很多报错，贴出其中一个
![image](https://user-images.githubusercontent.com/50293599/70435649-56c5c280-1ac2-11ea-8b7b-856cdd457f0a.png)

**Comment by DannyIsFunny** [comment]
@JepsonWong   
镜像：paddlepaddle/paddle:latest-gpu-cuda9.0-cudnn7-dev
执行步骤：cmake过程错误
```
cmake ..
-DWITH_CONTRIB=OFF
-DWITH_MKL=ON
-DWITH_MKLDNN=OFF
-DWITH_TESTING=ON
-DCMAKE_BUILD_TYPE=Release
-DWITH_INFERENCE_API_TEST=ON
-DON_INFER=ON
-DWITH_PYTHON=ON
-DWITH_DSO=OFF
```

**Comment by JepsonWong** [comment]
已本地复现，正在定位原因。

**Comment by tianshuo78520a** [comment]
麻烦问下为什么要使用DWITH_DSO=OFF参数？

**Comment by tianshuo78520a** [comment]
我们会在最新的版本取消DWITH_DSO参数，如果您有特殊的需求可以继续回复isuess
