### ISSUE TITLE
executor.py中的报错信息建议优化

### ISSUE THREAD

**Issue by OleNet** [PaddlePaddle/Paddle#21651]
这行报错信息，未免过于模糊和随意了。
作为用户，看到『The following exception is not an EOF exception.』感到很奇怪，完全不知道这条信息在提示我哪里出错了
https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/fluid/executor.py#L773

**Comment by jiweibo** [comment]
感谢反馈，目前我们针对报错信息优化开展了相关工作，已经初步完成了以下几点：
1. 对Paddle的报错信息栈进行了整理与简化，提高可读性
2. 丰富了Paddle的报错类型，并封装了指明报错类型的系列接口
3. 添加了CI监控
后续会继续这方面的工作！
