### ISSUE TITLE
获取lod level信息

### ISSUE THREAD

**Issue by littletomatodonkey** [PaddlePaddle/Paddle#21659]
想问下在编译时怎么获取Variable的lod level的信息呢？我使用`bbox_pred.lod_level`，获得的值是0，但是在运行时使用`fluid.layers.Print( bbox_pred, summarize=0 )`，打印出的变量的tensor为`[0,512,1024]`。
```
1575957509              The place is:CUDAPlace(2)
Tensor[bbox_pred.tmp_0]
        shape: [1024,324,]
        dtype: f
        LoD: [[ 0,512,1024, ]]
        data:
```

**Comment by jiweibo** [comment]
lod信息是可以直接获取的，前提是该variable有效。 根据你的描述信息我理解你的bbox_pred必须等到exe run之后才有效，此时可以直接打印出其lod。 lod的具体信息可以查看https://www.paddlepaddle.org.cn/documentation/docs/zh/user_guides/howto/basic_concept/lod_tensor.html#id3

**Comment by littletomatodonkey** [comment]
好吧，那就是说无法在编译时获取这个Variable的lod level信息，我再试试别的办法
