### ISSUE TITLE
mkldnn预测text_classification结果有误

### ISSUE THREAD

**Issue by OliverLPH** [PaddlePaddle/Paddle#21660]
- 标题：mkldnn预测text_classification结果精度下降
- 版本、环境信息：
    1）PaddlePaddle版本：2de10293964e
    2）CPU：Intel(R) Xeon(R) CPU E5-2650 v4 @ 2.20GHz, MKLDNN AVX
    3）GPU：无
    4）系统环境：Python2.7, Centos6
-预测信息
    1）C++预测：2de10293964e
    2）CMake包含路径的完整命令
    3）API信息（如调用请提供）
```python
config.disable_gpu()
config.enable_mkldnn()
```
    4）预测库来源：自行编译
- 复现信息：如为报错，请给出复现环境、复现步骤
- 问题描述：请详细描述您的问题，同步贴出报错信息、日志/代码关键片段

```shell
exceptions.AssertionError: 0.036529459059238434 != 0.03763990476727486 within 0.001 delta
```

```shell
# 模型和数据下载
wget http://paddle-inference-dist.bj.bcebos.com/text_classification_data.txt.tar.gz
wget http://paddle-inference-dist.bj.bcebos.com/text-classification-Senta.tar.gz
```

复现脚本
[compare_res.txt](https://github.com/PaddlePaddle/Paddle/files/3943326/compare_res.txt)

**Comment by luotao1** [comment]
@bingyanghuang Please help see it.

**Comment by Sand3r-** [comment]
Couldn't reproduce this on my SkyLake machine despite of forcing avx2 implementations of all MKL-DNN layers:
```
mkldnn_verbose,info,Intel MKL-DNN v1.0.0 (commit 518a316a8cd6deb82dc7866bc04bd0355a25c3a4)
mkldnn_verbose,info,Detected ISA is Intel AVX-512 with AVX512BW, AVX512VL, and AVX512DQ extensions
mkldnn_verbose,create:cache miss,cpu,concat,simple:any,undef,src_f32::blocked:ab:f0 src_f32::blocked:ab:f0 dst_f32::blocked:ab:f0,num:2,1x256,0.0078125
mkldnn_verbose,exec,cpu,concat,simple:any,undef,src_f32::blocked:ab:f0 src_f32::blocked:ab:f0 dst_f32::blocked:ab:f0,num:2,1x256,0.0151367
mkldnn_verbose,create:cache miss,cpu,eltwise,jit:avx2,forward_inference,data_f32::blocked:ab:f0 diff_undef::undef::f0,alg:eltwise_tanh:0:0,1x96,0.184814
mkldnn_verbose,exec,cpu,eltwise,jit:avx2,forward_inference,data_f32::blocked:ab:f0 diff_undef::undef::f0,alg:eltwise_tanh:0:0,1x96,0.0012207
mkldnn_verbose,create:cache miss,cpu,softmax,jit:avx2,forward_inference,data_f32::blocked:ab:f0 diff_undef::undef::f0,axis:1,1x2,0.052002
mkldnn_verbose,exec,cpu,softmax,jit:avx2,forward_inference,data_f32::blocked:ab:f0 diff_undef::undef::f0,axis:1,1x2,0.000976562
```
The test passed just fine without yielding any inconsistencies.

**Comment by luotao1** [comment]
@Sand3r- @bingyanghuang Could you use `Intel(R) Xeon(R) CPU E5-2650 v4` or any other AVX2 machine?

**Comment by lidanqing-vv** [comment]
Hi, @OliverLPH @luotao1 

We use local avx2 machine: `Intel(R) Xeon(R) CPU E5-2650 v4 @ 2.20GHz`, but still **CAN NOT** reproduce the error on avx2 machine. ( Our linux system is `CentOS-7`). 

It may because Baidu are using `CentOS-6`, which uses kernel: `Linux 2.6` , and our avx2 machine use kernel: `Linux 3.10.0-957.el7.x86_64`.  (Get kernel info by command `hostnamectl`). 

Now we do not have avx2 machine with `CentOS-6`. Could baidu check if this issue still exists on avx2 machine with `CentOS-7`?
Also please verify if baidu's machine has same instruction sets flags as listed below.

我们的复现情况、版本、环境信息：
   1）PaddlePaddle版本：2de10293964e
   2）CPU：Intel(R) Xeon(R) CPU E5-2650 v4 @ 2.20GHz
   3）系统环境：Python2.7, **CentOS-7**
   4）GPU：无
   5 ) Flags: 
``` fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf eagerfpu pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch epb cat_l3 cdp_l3 intel_ppin intel_pt ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm cqm rdt_a rdseed adx smap xsaveopt cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local dtherm ida arat pln pts spec_ctrl intel_stibp```

复现步骤：
编译好Paddle后，运行 `MKLDNN_VERBOSE=2 python compare_res.py`
日志结果： (如下， 全部为avx2 kernel)
```
mkldnn_verbose,info,Intel(R) MKL-DNN v0.20.0 (Git Hash aef88b7c233f48f8b945da310f1b973da31ad033),Intel(R) Advanced Vector Extensions 2 (Intel(R) AVX2)
mkldnn_verbose,create,concat,simple:any,undef,in:f32_nc out:f32_nc,num:2,1x256,0.00805664
mkldnn_verbose,exec,concat,simple:any,undef,in:f32_nc out:f32_nc,num:2,1x256,0.0180664
mkldnn_verbose,create,eltwise,jit:avx2,forward_inference,fdata:nc fdiff:undef,alg:eltwise_tanh,mb1ic96,0.119141
mkldnn_verbose,exec,eltwise,jit:avx2,forward_inference,fdata:nc fdiff:undef,alg:eltwise_tanh,mb1ic96,0.00292969
mkldnn_verbose,create,softmax,jit:avx2,forward_inference,fdata:nc fdiff:undef,,mb1ic2,0.0620117
mkldnn_verbose,exec,softmax,jit:avx2,forward_inference,fdata:nc fdiff:undef,,mb1ic2,0.00292969
```

**Comment by OliverLPH** [comment]
Hi, @lidanqing-intel 
thanks for your effort.
we have tested this issue in latest develop branch, and it seems alright now.
close this issue since the error is no longer exist.
