### ISSUE TITLE
deformable_conv的使用问题

### ISSUE THREAD

**Issue by wwjjy** [PaddlePaddle/Paddle#21683]
我想将目标检测网络中的普通卷积替换为deformable_conv，请教一下offset应该如何生成，求一个可以运行的demo代码参考一下

**Comment by baiyfbupt** [comment]
hi~ 在[PaddleDetection](https://github.com/PaddlePaddle/PaddleDetection)检测库中使用了deformable_conv，可以参考[PaddleDetection的例子](https://github.com/PaddlePaddle/PaddleDetection/blob/0b965c92685f865e901eda686a19f3850a6a4432/ppdet/modeling/backbones/resnet.py#L153-L182)，用一个卷积层生成offset~
