### ISSUE TITLE
编译错误： ld: cannot find -lpybind

### ISSUE THREAD

**Issue by rensilin** [PaddlePaddle/Paddle#21692]
develop分支， #21569 

cmake参数 `--WITH_PYTHON=OFF`, 不会引入pybind11依赖

**Comment by JepsonWong** [comment]
您好，想问下您是说 #21569 这个PR导致的问题么？

**Comment by JepsonWong** [comment]
是cmake参数 --WITH_PYTHON=OFF 会导致编译失败么？

**Comment by zhiqiu** [comment]
Thanks, fixed in [PR21681](https://github.com/PaddlePaddle/Paddle/pull/21681).
