### ISSUE TITLE
DGCMomentumOptimizer在cpu上报错AttributeError: module 'paddle.fluid.core_avx' has no attribute 'dgc'，gpu没有报错信息

### ISSUE THREAD

**Issue by baomengxue** [PaddlePaddle/Paddle#21697]
CPU：paddlepaddle  1.6.1
![image](https://user-images.githubusercontent.com/19708914/70677851-4d5b7680-1ccb-11ea-8c42-23271291acc4.png)

GPU：paddlepaddle  1.6.1
![image](https://user-images.githubusercontent.com/19708914/70677830-3cab0080-1ccb-11ea-8118-faf925318039.png)

**Comment by FrostML** [comment]
您好，DGCMomentumOptimizer目前只支持在GPU上使用。只支持GPU的多卡或分布式模型。

**Comment by wangxicoding** [comment]
@woshini555 再补充一下，DGC在1.6.2版本修复了一个正则化流程的问题，1.6.1版本在正则化使用上可能有些精度问题，目前1.6.2版本已发布。这里有一个简单的example，可以参考下 https://github.com/PaddlePaddle/Fleet/tree/develop/examples/dgc_example

**Comment by baomengxue** [comment]
> @woshini555 再补充一下，DGC在1.6.2版本修复了一个正则化流程的问题，1.6.1版本在正则化使用上可能有些精度问题，目前1.6.2版本已发布。这里有一个简单的example，可以参考下 https://github.com/PaddlePaddle/Fleet/tree/develop/examples/dgc_example

好的 感谢回复～

> 您好，DGCMomentumOptimizer目前只支持在GPU上使用。只支持GPU的多卡或分布式模型。

感谢回复～
