### ISSUE TITLE
训练时在deformable conv报错

### ISSUE THREAD

**Issue by LordAaron** [PaddlePaddle/Paddle#21701]
paddle官方api文档里面写了deformable conv的两种用法，一种可以用mask，一种可以不用mask；但是我将mask设置为None会报错：
代码：
offset = fluid.layers.conv2d(input=wh_pred,
         num_filters=2*9*n_anchors, groups=n_anchors,
         filter_size=1, stride=1, padding=0)
offset.stop_gradient = True
out = fluid.layers.deformable_conv(input=input,
         offset=offset, mask=None, num_filters=out_ch, filter_size=3, stride=1,            
          padding=1, deformable_groups=n_anchors)
![image](https://user-images.githubusercontent.com/14092826/70680168-4126e780-1cd2-11ea-9ccd-f921162ec6bc.png)

如果使用mask
代码：
offset_mask = fluid.layers.conv2d(input=wh_pred,
         num_filters=3*9*n_anchors, groups=n_anchors,
         filter_size=1, stride=1, padding=0)
offset_mask.stop_gradient = True

offset_channel = 9*n_anchors * 2
mask_channel = 9*n_anchors

offset, mask = fluid.layers.split(
         input=offset_mask,
         num_or_sections=[offset_channel, mask_channel],
         dim=1)
mask = fluid.layers.sigmoid(mask)

out = fluid.layers.deformable_conv(input=input,
         offset=offset, mask=mask, num_filters=out_ch, filter_size=3, stride=1,            
         padding=1, deformable_groups=n_anchors)
在训练时，就会报下面的错误：
![image](https://user-images.githubusercontent.com/14092826/70680492-6ec06080-1cd3-11ea-8b11-be58b8bdf506.png)

**Comment by baiyfbupt** [comment]
hi~ 如果不需要使用mask那就应该对应的是deformable_conv v1，请参考[官网deformable_conv文档](https://www.paddlepaddle.org.cn/documentation/docs/zh/api_cn/layers_cn/deformable_conv_cn.html#deformable-conv)，需要设置`modulated=True`：
```
offset = fluid.layers.conv2d(input=wh_pred,
num_filters=29n_anchors, groups=n_anchors,
filter_size=1, stride=1, padding=0)
offset.stop_gradient = True
out = fluid.layers.deformable_conv(input=input,
offset=offset, mask=None, num_filters=out_ch, filter_size=3, stride=1,
padding=1, deformable_groups=n_anchors, modulated=True)
```

**Comment by LordAaron** [comment]
> hi~ 如果不需要使用mask那就应该对应的是deformable_conv v1，请参考[官网deformable_conv文档](https://www.paddlepaddle.org.cn/documentation/docs/zh/api_cn/layers_cn/deformable_conv_cn.html#deformable-conv)，需要设置`modulated=True`：
> 
> ```
> offset = fluid.layers.conv2d(input=wh_pred,
> num_filters=29n_anchors, groups=n_anchors,
> filter_size=1, stride=1, padding=0)
> offset.stop_gradient = True
> out = fluid.layers.deformable_conv(input=input,
> offset=offset, mask=None, num_filters=out_ch, filter_size=3, stride=1,
> padding=1, deformable_groups=n_anchors, modulated=True)
> ```

没有用，加上modulated=True 还是报跟之前一样的错误

**Comment by baiyfbupt** [comment]
@LordAaron v1应该是加modulated=False, 刚才手误打错了，改过来再试试吧~

**Comment by LordAaron** [comment]
> @LordAaron v1应该是加modulated=False, 刚才手误打错了，改过来再试试吧~

嗯，这个问题解决了，但是用v1也是有一样的deformable conv问题，就是最开始说的第二个引起显存超了的问题

**Comment by LordAaron** [comment]
> > @LordAaron v1应该是加modulated=False, 刚才手误打错了，改过来再试试吧~
> 
> 嗯，这个问题解决了，但是用v1也是有一样的deformable conv问题，就是最开始说的第二个引起显存超了的问题

第二个问题也找到了，确实就是deformable conv操作导致显存爆了，是这个操作很占显存吗？
out = fluid.layers.deformable_conv(input=input,
offset=offset, mask=mask, num_filters=out_ch, filter_size=3, stride=1,
padding=1, deformable_groups=n_anchors)
原本num_filters是1024，现在砍半到512就可以了
我的模型是检测模型，分别在3个layer后面有接deformable conv操作，分别是1024，512，256
现在改为512，256，128可以训练起来
但我在backbone部分加deformable conv前后，好像不会出现这么大的显存占用

**Comment by baiyfbupt** [comment]
这个op本身应该不会特别耗显存，在我们的[PaddleDetection](https://github.com/PaddlePaddle/PaddleDetection/blob/0b965c92685f865e901eda686a19f3850a6a4432/ppdet/modeling/backbones/resnet.py#L153-L182)检测库里很多模型上也验证过。如果确定是显存问题，可以尝试减少batch_size数量或者使用[显存优化策略](https://www.paddlepaddle.org.cn/documentation/docs/zh/advanced_usage/best_practice/memory_optimize.html#best-practice)看看是否能正常训练
