### ISSUE TITLE
关于deformable_conv的预测问题

### ISSUE THREAD

**Issue by wwjjy** [PaddlePaddle/Paddle#21707]
训练阶段deformabel_conv的im2col_step参数设置的为4，是否在freeze之后的预测阶段batch_size大小也得>=4且能被4整除，目前尝试了batch_size为1和batch_size为4的情况，当batch_size为1时，预测的结果很诡异，不符合预期，当batch_size为4时，我送入4幅同样的图像，有时检测结果并不相同，请问这是什么问题。

**Comment by baiyfbupt** [comment]
hi， 请问有测试过batch_size=1时在验证集上的指标吗，是否符合预期？`batch_size为4时，我送入4幅同样的图像，有时检测结果并不相同`是指检测得到bounding box会有差异吗？

**Comment by wwjjy** [comment]
@baiyfbupt  我是通过load_inference_model的方式来测试的batch_size=1时，不管输入的顺序是什么，输出的结果貌似都是两种结果循环出现，然后如果batch_size为4时，我送入四幅同样的图片结果的lod信息会出现类似[0, 0, 0, 1, 1]的情况，我在训练时把im2col_step参数改为1，测试的时候好像一次预测一张就没有问题了

**Comment by baiyfbupt** [comment]
@wwjjy 这里建议用im2col_step=1的方式进行训练，后续我们也会对deformable_conv im2col_step的使用方式进行一次优化，避免现在这种问题
