### ISSUE TITLE
Multiple infer output must have the same size ? 

### ISSUE THREAD

**Issue by pengwangucla** [PaddlePaddle/Paddle#2170]
related to issue #2107 In paddle.infer, it concatenate different output of the same field as follow:

```python
    def infer(self, input, field='value', **kwargs):
        """
        Infer a data by model.
        :param input: input data batch. Should be python iterable object.
        :param field: output field.
        """
        retv = None
        kwargs['input'] = input
        for result in self.iter_infer_field(field=field, **kwargs):
            if retv is None:
                retv = [[] for i in xrange(len(result))]
            for i, item in enumerate(result):
                retv[i].append(item)
  >      retv = [numpy.concatenate(out) for out in retv]
        if len(retv) == 1:
            return retv[0]
        else:
            return retv
```

Why you need to concatenate it ? Can it be done with a 2 d list or a list of dictionary ? So that you don't need to require the shape of each output to be exactly the same ? 

@reyoung

**Comment by lcy-seso** [comment]
I have met the same problem. I will try to fix this.

**Comment by juliecbd** [comment]
Any update on this? I have met the same problem

**Comment by juliecbd** [comment]
I remember I was able to input numpy nd array as input, and it no longer works. I get 

/py_paddle/dataprovider_converter.py", line 112, in pre_scan
    self.__dim__ = reduce(lambda x, y: x * y, self.__shape__)
TypeError: reduce() of empty sequence with no initial value

Error

**Comment by lcy-seso** [comment]
Hi, @juliecbd  Another user has reported the same bug: https://github.com/PaddlePaddle/Paddle/issues/2564.

**Comment by juliecbd** [comment]
Thanks. Yes I have the exact same problem. Could anyone look into this ?

**Comment by lcy-seso** [comment]
@juliecbd I will look into this, Thank you.

**Comment by Canpio** [comment]
Close this issue for related PR has been closed. Please feel free to reopen it.
