### ISSUE TITLE
Difference between paddle-0.10.0-py2-none-any.whl and py_paddle-0.10.0-py2-none-any.whl

### ISSUE THREAD

**Issue by juliecbd** [PaddlePaddle/Paddle#2171]
When I build Paddle from source, there are two *.whl files created

paddle-0.10.0-py2-none-any.whl
py_paddle-0.10.0-py2-none-any.whl

Does anyone know the difference? Do we need to install both, and if yes, in which order we need to install?

Thank you

**Comment by luotao1** [comment]
We need to install both of them, but there is no order when installing them. The difference is paddle-0.10.0-py2-none-any.whl contains the [python/paddle](https://github.com/PaddlePaddle/Paddle/tree/develop/python/paddle) folders, but py_paddle-0.10.0-py2-none-any.whl contains the [paddle/py_paddle](https://github.com/PaddlePaddle/Paddle/tree/develop/paddle/py_paddle) folders.

**Comment by juliecbd** [comment]
Thank you very much. By the way, I installed paddle on another machine (Mac) and it created only 
paddle-0.10.0-py2-none-any.whl
and not 
py_paddle-0.10.0-py2-none-any.whl

In which case the build will install only one *.whl file? And is this enough? 

Thank you

**Comment by wangkuiyi** [comment]
@luotao1 Do you know why we need [paddle/py_paddle](https://github.com/PaddlePaddle/Paddle/tree/develop/paddle/py_paddle) in a separate whl?

**Comment by wangkuiyi** [comment]
@juliecbd to what I know, the only OS Paddle natively supports is Linux. To run on Mac or Windows, we'd have to use Docker.

**Comment by luotao1** [comment]
@reyoung can you help to answer this issue?

**Comment by typhoonzero** [comment]
We currently merge the two whl packages to one. Closing this issue.
