### ISSUE TITLE
eval的时候paddle.fluid.core_avx.EnforceNotMet: Enforce failed.

### ISSUE THREAD

**Issue by xx674967** [PaddlePaddle/Paddle#21721]
版本、环境信息：
   1）PaddlePaddle版本：paddle v1.6.1
   2）CPU：Intel(R) Xeon(R) Gold 5117 CPU @ 2.00GHz，-DWITH_MKL=ON，-DWITH_MKLDNN=OFF
   3）GPU：Tesla P4，CUDA 9，CUDNN 7
   4）系统环境：CentOS Linux release 7.6.1810 (Core)、Python 3.7

问题描述：
ppdet 训好的yolov3模型，batchsize为1 eval的时候会报错，每次都在1500 iter报错，进去看data_feed读进来的图片是正常的，请问这是啥原因？
<img width="1410" alt="1e5bf28a9641bf4b39ce5224f" src="https://user-images.githubusercontent.com/26277179/70716769-f0da7480-1d27-11ea-8aab-37e03423913d.png">

**Comment by heavengate** [comment]
你好，请问使用的PaddleDetection是哪个版本

**Comment by heavengate** [comment]
您好，当前问题长时间未回复，先关闭issue，如果还有问题，可以reopen此issue~
