### ISSUE TITLE
fluid.layers.data_norm 使用报错

### ISSUE THREAD

**Issue by suytingwan** [PaddlePaddle/Paddle#21728]
在静态图中对variable矩阵使用fluid.layers.data_norm归一化，报如下问题

Error Message Summary:
----------------------
PaddleCheckError: op data_norm does not have kernel for data_type[float]:data_layout[ANY_LAYOUT]:place[CUDAPlace(0)]:library_type[PLAIN] at [/paddle/paddle/fluid/framework/operator.cc:1010]
  [operator < data_norm > error]

定义语句为：
        weight = fluid.layers.create_parameter(shape=[self.in_dim, self.out_dim],
                                                    dtype='float32', default_initializer=fluid.initializer.Xavier(uniform=True))

        weight_norm = fluid.layers.data_norm(weight, name='weight')

去掉该归一化步骤可以正常运行，请帮忙看下该op的问题如何解决

**Comment by hutuxian** [comment]
请您提供一下所使用的paddle版本？
data_norm op在1.6.1之前是没有CUDA版本的。预计会在下一个major版本提供CUDA实现。
