### ISSUE TITLE
 fluid.layers.resize_bilinear得到的不是放大两倍的原图

### ISSUE THREAD

**Issue by cisco08** [PaddlePaddle/Paddle#21727]
- 版本、环境信息：
    1）PaddlePaddle版本：paddle1.6
    2）CPU/GPU：CPU
    3）系统环境：Mac OS 10.14
    4）Python版本号 Python3.7
    5）显存信息
- 复现信息：如为报错，请给出复现环境、复现步骤
- 问题描述：
x = plt.imread("微信图片_20191207203405.jpg")
with fluid.dygraph.guard():
    xx = x.reshape((1,C,H,W))
    d = fluid.dygraph.base.to_variable(xx.astype('float32'))
    H, W = d.shape[2:]
    H,W = H*2,W*2
    upsample = fluid.layers.resize_bilinear(d, (H,W),align_corners=False)
    res=fluid.dygraph.base.to_variable(upsample)

res = np.squeeze(res.numpy())

res = res.reshape((res.shape[1],res.shape[2],res.shape[0]))
plt.imshow(res.astype('uint8'))
plt.show()

没有得到放大2倍的图
结果是
![image](https://user-images.githubusercontent.com/8415114/70769473-9e8b6900-1da4-11ea-85f0-84ce75921a1a.png)
尺寸是放大对了，但是结果显示的不对

**Comment by DDDivano** [comment]
老铁我觉得这段代码 `res = res.reshape((res.shape[1],res.shape[2],res.shape[0]))`是不是应该换成transpose？

**Comment by DDDivano** [comment]
你可以看一下 reshape 和transpose的区别 ，你读数据用reshape当转置肯定是错的
