### ISSUE TITLE
如何让reader输出str类型的数据？

### ISSUE THREAD

**Issue by geniusSDNexplorer** [PaddlePaddle/Paddle#21730]
64     data_reader = RelevanceReader()
 65
 66     image = fluid.layers.data(name='image', shape=[3, 224, 224], dtype='float32')
 67     sign = fluid.layers.data(name='segment_sign', shape=[1], dtype='str')
 68     feed_list = [sign, image]
 69     multiprocessing_batch_gen = data_reader.multiprocessing_wrapper(
 70             file_names=input_file_names,
 71             data_sizes=input_data_sizes,
 72             num_workers=5,
 73             epochs=1)
 74     py_reader = fluid.io.PyReader(
 75             feed_list=feed_list,
 76             capacity=20,
 77             use_double_buffer=True,
 78             iterable=True)
 79     py_reader.decorate_batch_generator(multiprocessing_batch_gen, places=places)

如以上代码所示，我的reader输出sign和image两个部分，其中sign是string类型，但是layers.data不支持str类型，所以我的feedlist应该写什么呢？

**Comment by cryoco** [comment]
data层只接受数据类型的输入，可以根据需求将str转为int，或使用word2vec或者embedding等技术把string转为数字
