### ISSUE TITLE
paddle1.5 c++预测出错

### ISSUE THREAD

**Issue by ph2537089017** [PaddlePaddle/Paddle#21748]
1）PaddlePaddle版本：1.5
    2）CPU：预测若用CPU，i5-7200u，MKL=off
    4）系统环境：ubuntu16.04，Python版本3.7
-预测信息
    1）C++预测：1.5，的version.txt：
GIT COMMIT ID: a5696153a013552bfaa612ca407eba318e18ba54
WITH_MKL: OFF
WITH_MKLDNN: OFF
WITH_GPU: OFF
    2）CMake包含路径的完整命令，在qt5.13下编译的
    3）API信息     auto predictor =paddle::CreatePaddlePredictor<paddle::NativeConfig>(config); 出错，且无法使用CHECK（）
    4）预测库来源：官网下载
运行报错：
ERROR: unknown command line flag 'fraction_of_gpu_memory_to_use'

**Comment by juncaipeng** [comment]
从你的信息来看，编译的预测库是没有编译gpu的，‘ fraction_of_gpu_memory_to_use’是设置gpu使用率，是这个导致的问题吗？

**Comment by ph2537089017** [comment]
尝试带gpu的c++预测库后，这个问题没有了，但在执行 auto predictor =CreatePaddlePredictor(config);时程序依然崩溃，不知道什么问题。有没有完整的可以跑通的例程呀？

**Comment by ph2537089017** [comment]
是gcc版本的问题，改成4.8就可以了
但CHECK函数无法使用

**Comment by juncaipeng** [comment]
paddle1.5的c++预测样例，可以参考：https://www.paddlepaddle.org.cn/documentation/docs/zh/1.5/advanced_usage/deploy/inference/native_infer.html

paddle1.6的c++预测样例，可以参考：https://www.paddlepaddle.org.cn/documentation/docs/zh/advanced_usage/deploy/inference/native_infer.html。

**Comment by juncaipeng** [comment]
> 是gcc版本的问题，改成4.8就可以了
> 但CHECK函数无法使用

现在预测的时候CHECK函数报错吗？可以贴上错误信息吗？

**Comment by ph2537089017** [comment]
CHECK(predictor->ZeroCopyRun());
提示显示：CHECK 未定义，无法编译通过

**Comment by juncaipeng** [comment]
> CHECK(predictor->ZeroCopyRun());
> 提示显示：CHECK 未定义，无法编译通过

你应该是使用NativePredictor，所以报错没有定义，不是说check未定义，是ZeroCopyRun未定义。ZeroCopyTensor的使用可避免预测时候准备输入以及获取输出时多余的数据copy，提高预测性能。只可用于AnalysisPredictor。
请再次参考1.5的c++预测文档：https://www.paddlepaddle.org.cn/documentation/docs/zh/1.5/advanced_usage/deploy/inference/native_infer.html

**Comment by ph2537089017** [comment]
NativePredictor 使用样例正常.AnalysisPredictor 使用样例编译报错:

In file included from ../Downloads/fluid_inference/paddle/include/paddle_analysis_config.h:28:0,
                 from ../Downloads/fluid_inference/paddle/include/paddle_inference_api.h:29,
                 from ../untitled/main.cpp:3:
../Downloads/fluid_inference/paddle/include/paddle_api.h:235:43: warning: unused parameter ‘name’ [-Wunused-parameter]
   virtual std::unique_ptr<ZeroCopyTensor> GetInputTensor(
                                           ^
../Downloads/fluid_inference/paddle/include/paddle_api.h:246:43: warning: unused parameter ‘name’ [-Wunused-parameter]
   virtual std::unique_ptr<ZeroCopyTensor> GetOutputTensor(
                                           ^
../untitled/main.cpp: In function ‘void paddle::RunAnalysis(int, std::string)’:
../untitled/main.cpp:104:33: error: ‘CHECK’ was not declared in this scope
   CHECK(predictor->ZeroCopyRun());
                                 ^
make: *** [main.o] Error 1

**Comment by juncaipeng** [comment]
请问再次确认是使用1.5的预测样例加载1.5的预测库进行预测。

‘CHECK’ was not declared in this scope，这个报错应该是没有链接到glog库，你可以尝试将third_party/install/glog加入库环境变量中。

如果你没有特殊需求，建议使用1.6的预测库。

**Comment by ph2537089017** [comment]
使用1.5的预测样例加载1.5的预测库进行预测。
使用1.6的预测样例加载1.6的预测库进行预测。都有&lsquo;CHECK&rsquo;&nbsp;was&nbsp;not&nbsp;declared&nbsp;in&nbsp;this&nbsp;scope这个错误。已经加了glog库。CHECK函数起什么作用的？如果不重要能不能直接预测？


---原始邮件---
发件人: &quot;juncaipeng&quot;<notifications@github.com&gt;
发送时间: 2019年12月16日(周一) 下午3:35
收件人: &quot;PaddlePaddle/Paddle&quot;<Paddle@noreply.github.com&gt;;
抄送: &quot;ph2537089017&quot;<2537089017@qq.com&gt;;&quot;Author&quot;<author@noreply.github.com&gt;;
主题: Re: [PaddlePaddle/Paddle] paddle1.5 c++预测出错 (#21748)



请问再次确认是使用1.5的预测样例加载1.5的预测库进行预测。
 
‘CHECK’ was not declared in this scope，这个报错应该是没有链接到glog库，你可以尝试将third_party/install/glog加入库环境变量中。
 
如果你没有特殊需求，建议使用1.6的预测库。
 
&mdash;

**Comment by juncaipeng** [comment]
报错确实是CHECK没有找到，要不先把这个CHECK去掉，再试下，看模型预测输出是否正确。

**Comment by juncaipeng** [comment]
> 使用1.5的预测样例加载1.5的预测库进行预测。 使用1.6的预测样例加载1.6的预测库进行预测。都有&lsquo;CHECK&rsquo;&nbsp;was&nbsp;not&nbsp;declared&nbsp;in&nbsp;this&nbsp;scope这个错误。已经加了glog库。CHECK函数起什么作用的？如果不重要能不能直接预测？
> […](#)
> ---原始邮件--- 发件人: &quot;juncaipeng&quot;<notifications@github.com&gt; 发送时间: 2019年12月16日(周一) 下午3:35 收件人: &quot;PaddlePaddle/Paddle&quot;<Paddle@noreply.github.com&gt;; 抄送: &quot;ph2537089017&quot;<2537089017@qq.com&gt;;&quot;Author&quot;<author@noreply.github.com&gt;; 主题: Re: [PaddlePaddle/Paddle] paddle1.5 c++预测出错 (#21748) 请问再次确认是使用1.5的预测样例加载1.5的预测库进行预测。 ‘CHECK’ was not declared in this scope，这个报错应该是没有链接到glog库，你可以尝试将third_party/install/glog加入库环境变量中。 如果你没有特殊需求，建议使用1.6的预测库。 &mdash; You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

请问问题解决了吗？

**Comment by ph2537089017** [comment]
十分感谢您的耐心解答，这个问题解决了。希望paddle越来越完善，越来越易用。



---原始邮件---
发件人: "juncaipeng"<notifications@github.com&gt;
发送时间: 2019年12月17日(周二) 上午9:59
收件人: "PaddlePaddle/Paddle"<Paddle@noreply.github.com&gt;;
抄送: "ph2537089017"<2537089017@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [PaddlePaddle/Paddle] paddle1.5 c++预测出错 (#21748)


 
使用1.5的预测样例加载1.5的预测库进行预测。 使用1.6的预测样例加载1.6的预测库进行预测。都有‘CHECK’&nbsp;was&nbsp;not&nbsp;declared&nbsp;in&nbsp;this&nbsp;scope这个错误。已经加了glog库。CHECK函数起什么作用的？如果不重要能不能直接预测？
 …
 ---原始邮件--- 发件人: "juncaipeng"<notifications@github.com&gt; 发送时间: 2019年12月16日(周一) 下午3:35 收件人: "PaddlePaddle/Paddle"<Paddle@noreply.github.com&gt;; 抄送: "ph2537089017"<2537089017@qq.com&gt;;"Author"<author@noreply.github.com&gt;; 主题: Re: [PaddlePaddle/Paddle] paddle1.5 c++预测出错 (#21748) 请问再次确认是使用1.5的预测样例加载1.5的预测库进行预测。 ‘CHECK’ was not declared in this scope，这个报错应该是没有链接到glog库，你可以尝试将third_party/install/glog加入库环境变量中。 如果你没有特殊需求，建议使用1.6的预测库。 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.
  
请问问题解决了吗？

**Comment by juncaipeng** [comment]
好的。不客气。
