### ISSUE TITLE
安装错误，在服务器安装paddle1.5.0.post 安装出错

### ISSUE THREAD

**Issue by ZhaoLiang-GitHub** [PaddlePaddle/Paddle#21752]
在v100机器上安装paddleGPU版本1.5.0.post97,安装完成后，在测试中提醒cudnn版本错误，cuda9需要7.3的cudnn，我本机上是7.1,按照教程https://blog.csdn.net/htt789/article/details/79627015 将我这个环境下的cudnn 修改成了7.3（work账户下是有7.3的），在此测试仍然报错
![image](https://user-images.githubusercontent.com/33596293/70858743-cadcec00-1f42-11ea-87fe-ea48a5258aad.png)

**Comment by JepsonWong** [comment]
应该是cudnn没有升级好。

1. 输入 cat /usr/local/cuda/include/cudnn.h | grep CUDNN_MAJOR -A 2 查看一下cudnn结果。
2. 找到cuda目录，例如 /usr/local/cuda/lib64/ ，然后 cd /usr/local/cuda/lib64/ ，ls | grep libcudnn.so 查看一下结果。
