### ISSUE TITLE
如何使bn既能for_test模式预测，又能backward获取梯度？

### ISSUE THREAD

**Issue by linshufei** [PaddlePaddle/Paddle#21767]
- 版本、环境信息：
    1）PaddlePaddle版本：1.5
    2）CPU：CPU
    3）GPU：无
    4）系统环境：Linux python2.7
- 复现信息：如为报错，请给出复现环境、复现步骤
复现代码如下：
```
import numpy as np
import paddle.fluid as fluid
import paddle.fluid.layers as layers

debug = True
bs = 10
c = 3
h, w = 32, 32

main_program = fluid.Program()
startup_program = fluid.Program()
with fluid.program_guard(main_program, startup_program):
    x = fluid.layers.data(name='x', shape=[-1, c, w, h], dtype='float32')
    x.stop_gradient=False
    bn = fluid.layers.batch_norm(input=x)
    y = fluid.layers.reduce_sum(bn)
    z = fluid.gradients(y, x)
    x1 = x - 0.1 * z[0]
    y1 = fluid.layers.reduce_sum(x1)

if debug:
    test_program = main_program.clone(for_test=True)
else:
    test_program = main_program.clone()

place = fluid.CPUPlace()
exe = fluid.Executor(place)
exe.run(startup_program)
x_data = np.random.rand(bs, c, w, h).astype(np.float32)
print(exe.run(test_program, fetch_list=[y, y1], feed={'x': x_data}))
```
当debug为False时无报错；
当debug为True时报错信息如下：
Traceback (most recent call last):
  File "test.py", line 22, in <module>
    test_program = main_program.clone(for_test=True)
  File "<decorator-gen-15>", line 2, in clone
  File "/home/disk1/vis/linshufei/paddle-release/python-gcc482-paddle/lib/python2.7/site-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
    return wrapped_func(*args, **kwargs)
  File "/home/disk1/vis/linshufei/paddle-release/python-gcc482-paddle/lib/python2.7/site-packages/paddle/fluid/framework.py", line 198, in __impl__
    return func(*args, **kwargs)
  File "/home/disk1/vis/linshufei/paddle-release/python-gcc482-paddle/lib/python2.7/site-packages/paddle/fluid/framework.py", line 3880, in clone
    forward_prog.desc = core.prune_backward(self.desc)
paddle.fluid.core_avx.EnforceNotMet: 0   std::string paddle::platform::GetTraceBackString<std::string const&>(std::string const&, char const*, int)
1   paddle::platform::EnforceNotMet::EnforceNotMet(std::string const&, char const*, int)
2   paddle::framework::PruneBackward(paddle::framework::ProgramDesc const&)
PaddleCheckError: Expected has_loss_op == true, but received has_loss_op:0 != true:1.
The Program need to be pruned its backward partshould have loss operator. at [/paddle/paddle/fluid/framework/prune.cc:379]

- 问题描述：请详细描述您的问题，同步贴出报错信息、日志/代码关键片段
问题：
当debug为True时，program为for_test模式，在调用fluid.gradients时backward计算梯度报错。
如何用batch normalization做forward预测时为for_test模式，也能进行backward计算梯度？

**Comment by JepsonWong** [comment]
for_test=True的情况下无法获取梯度。

请看相关文档：https://www.paddlepaddle.org.cn/documentation/docs/zh/api_cn/fluid_cn/Program_cn.html

![image](https://user-images.githubusercontent.com/16509038/70908852-2c867e80-2047-11ea-9ab6-ff58f3f0cc1d.png)

**Comment by linshufei** [comment]
> for_test=True的情况下无法获取梯度。
> 
> 请看相关文档：https://www.paddlepaddle.org.cn/documentation/docs/zh/api_cn/fluid_cn/Program_cn.html
> 
> ![image](https://user-images.githubusercontent.com/16509038/70908852-2c867e80-2047-11ea-9ab6-ff58f3f0cc1d.png)

目标是要获取对输入数据x的梯度，而同时确保batch normalization和dropout等op在前向计算时使用test模式，目的是生成对抗样本，所以会有这种非常规的需求。

**Comment by JepsonWong** [comment]
> > for_test=True的情况下无法获取梯度。
> > 请看相关文档：https://www.paddlepaddle.org.cn/documentation/docs/zh/api_cn/fluid_cn/Program_cn.html
> > ![image](https://user-images.githubusercontent.com/16509038/70908852-2c867e80-2047-11ea-9ab6-ff58f3f0cc1d.png)
> 
> 目标是要获取对输入数据x的梯度，而同时确保batch normalization和dropout等op在前向计算时使用test模式，目的是生成对抗样本，所以会有这种非常规的需求。

目前不支持这种需求，这种需求我可以帮忙反馈一下。

**Comment by linshufei** [comment]
> > > for_test=True的情况下无法获取梯度。
> > > 请看相关文档：https://www.paddlepaddle.org.cn/documentation/docs/zh/api_cn/fluid_cn/Program_cn.html
> > > ![image](https://user-images.githubusercontent.com/16509038/70908852-2c867e80-2047-11ea-9ab6-ff58f3f0cc1d.png)
> > 
> > 
> > 目标是要获取对输入数据x的梯度，而同时确保batch normalization和dropout等op在前向计算时使用test模式，目的是生成对抗样本，所以会有这种非常规的需求。
> 
> 目前不支持这种需求，这种需求我可以帮忙反馈一下。

好的辛苦反馈一下；
目前我在model定义文件里的batch_norm和dropout layer 里手动将is_test设置为True，代码已跑通，请问该方法是否正确？
如果正确，使用y = network(x)，能否用批量的操作将network里的bn和drop层的is_test参数设置为True，这样可以不改变model定义文件而直接在外部代码中进行批量操作。

**Comment by JepsonWong** [comment]
> > > > for_test=True的情况下无法获取梯度。
> > > > 请看相关文档：https://www.paddlepaddle.org.cn/documentation/docs/zh/api_cn/fluid_cn/Program_cn.html
> > > > ![image](https://user-images.githubusercontent.com/16509038/70908852-2c867e80-2047-11ea-9ab6-ff58f3f0cc1d.png)
> > > 
> > > 
> > > 目标是要获取对输入数据x的梯度，而同时确保batch normalization和dropout等op在前向计算时使用test模式，目的是生成对抗样本，所以会有这种非常规的需求。
> > 
> > 
> > 目前不支持这种需求，这种需求我可以帮忙反馈一下。
> 
> 好的辛苦反馈一下；
> 目前我在model定义文件里的batch_norm和dropout layer 里手动将is_test设置为True，代码已跑通，请问该方法是否正确？
> 如果正确，使用y = network(x)，能否用批量的操作将network里的bn和drop层的is_test参数设置为True，这样可以不改变model定义文件而直接在外部代码中进行批量操作。

您好，您这种行为是可以的。但是目前没有批量改变is_test参数的接口。

**Comment by luotao1** [comment]
@JepsonWong 是否考虑增加一个`FLAGS_is_test=true`的接口，类似目前的`FLAGS_use_mkldnn=true`，批量打开mkldnn kernel的接口。

**Comment by JepsonWong** [comment]
> @JepsonWong 是否考虑增加一个`FLAGS_is_test=true`的接口，类似目前的`FLAGS_use_mkldnn=true`，批量打开mkldnn kernel的接口。

好的，这个我在issue例会上提一下。
