### ISSUE TITLE
import paddle出现ImportError：dlopen：cannot load any more object with static TLS

### ISSUE THREAD

**Issue by OliverLPH** [PaddlePaddle/Paddle#21760]
- 标题：import paddle.fluid 时报错dlopen：cannot load any more object with static TLS
- 版本、环境信息：
    1）PaddlePaddle版本：develop：a6e935f4243e52
    2）CPU：MKL/openblas
    3）GPU：CUDA9/CUDA10
    4）系统环境：paddlepaddle/paddle_manylinux_devel:cuda10.0_cudnn7，centos6.1，gcc482
- 安装方式信息：
1）pip安装/docker安装
2）本地编译：
3）docker编译：paddlepaddle/paddle_manylinux_devel:cuda10.0_cudnn7  
  特殊环境请注明：需升级镜像中的glibc版本
- 复现信息：

由于镜像中的glibc版本仅为2.13，而TensorRT的lib依赖的glibc需高于2.13，所以先升级镜像中的glibc至2.18，升级命令如下。
```shell
wget http://ftp.gnu.org/gnu/glibc/glibc-2.18.tar.gz
tar -xvf glibc-2.18.tar.gz
cd glibc-2.18
unset LD_LIBRARY_PATH # must unset LD_LIBRARY_PATH before compile glibc
mkdir build && cd build && ../configure --prefix=/usr && make -j4 && make install
export LD_LIBRARY_PATH=/opt/rh/devtoolset-2/root/usr/lib64:/opt/rh/devtoolset-2/root/usr/lib:/usr/local/lib64:/usr/local/lib:
```

然后安装ci上编译的develop的cuda9.0_cudnn7_mkl whl包

打开Python 后import paddle.fluid

其中mkl的包会报错。
```shell
Python 2.7.11 (default, Nov 15 2019, 12:44:37)
[GCC 4.8.2 20140120 (Red Hat 4.8.2-15)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import paddle
>>> import paddle.fluid as fluid
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/_internal/cpython-2.7.11-ucs4/lib/python2.7/site-packages/paddle/fluid/__init__.py", line 35, in <module>
    from . import framework
  File "/opt/_internal/cpython-2.7.11-ucs4/lib/python2.7/site-packages/paddle/fluid/framework.py", line 35, in <module>
    from . import core
  File "/opt/_internal/cpython-2.7.11-ucs4/lib/python2.7/site-packages/paddle/fluid/core.py", line 189, in <module>
    raise e
ImportError: dlopen: cannot load any more object with static TLS
>>> exit
Use exit() or Ctrl-D (i.e. EOF) to exit
```

看了这个跟TLS有关的issue[Cannot load any more object with static TLS while executing crnn_ctc on multi-devices](https://github.com/PaddlePaddle/models/issues/1360)后验证了关闭 mkl的whl包，从ci上下载了 cuda9.0_cudnn7_openblas whl包
而openblas的包不报错，且可以正常使用
```shell
Python 2.7.11 (default, Nov 15 2019, 12:44:37)
[GCC 4.8.2 20140120 (Red Hat 4.8.2-15)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import paddle.fluid as fluid
>>> import paddle
>>>
```

- 问题描述：

目前验证过 paddle1.6.1 paddle1.6.2开启mkl的whl包，如果升级了镜像glibc并不会造成该问题。该问题仅在develop上可以复现。

**Comment by JepsonWong** [comment]
收到，已建卡片跟进。

**Comment by luotao1** [comment]
```
$ objdump -t core_avx.so  | grep ".tbss" |awk -F" " '{cmd="c++filt "$5; system(cmd); print $4}'0000000000000000
.tbss
guard variable for paddle::framework::MultiSlotDataFeed::ParseOneInstanceFromPipe(std::vector<paddle::framework::MultiSlotType, std::allocator<paddle::framework::MultiSlotType> >*)::reader
0000000000000008
paddle::framework::MultiSlotDataFeed::ParseOneInstanceFromPipe(std::vector<paddle::framework::MultiSlotType, std::allocator<paddle::framework::MultiSlotType> >*)::reader
0000000000000018
guard variable for paddle::framework::MultiSlotInMemoryDataFeed::ParseOneInstanceFromPipe(paddle::framework::Record*)::reader
0000000000000008
paddle::framework::MultiSlotInMemoryDataFeed::ParseOneInstanceFromPipe(paddle::framework::Record*)::reader
0000000000000018
guard variable for paddle::framework::DownpourWorker::CopyDenseTable()::pull_dense_status
0000000000000008
paddle::framework::DownpourWorker::CopyDenseTable()::pull_dense_status
0000000000000018
guard variable for paddle::framework::FleetWrapper::LocalRandomEngine()::r
0000000000000008
paddle::framework::FleetWrapper::LocalRandomEngine()::r
0000000000000008
paddle::platform::g_event_list
0000000000000010
__tls_guard
0000000000000001
paddle::platform::g_mem_event_list
0000000000000010
paddle::platform::g_thread_id
0000000000000004
paddle::platform::g_mem_thread_id
0000000000000004
__tls_guard
0000000000000001
paddle::platform::(anonymous namespace)::cur_input_shape_str
0000000000000008
paddle::platform::(anonymous namespace)::cur_mkldnn_session_id
0000000000000008
guard variable for paddle::operators::jit::GetFuncCacheMap()::g_func_cache_map
0000000000000008
paddle::operators::jit::GetFuncCacheMap()::g_func_cache_map
0000000000000030
guard variable for paddle::framework::GetThreadLocalUsedVarNameSet()::used_var_name_set
0000000000000008
paddle::framework::GetThreadLocalUsedVarNameSet()::used_var_name_set
0000000000000030
__tls_guard
0000000000000001
paddle::platform::(anonymous namespace)::block_id_stack
0000000000000050
paddle::platform::(anonymous namespace)::annotation_stack
0000000000000050
guard variable for paddle::operators::jit::GetJITCodesMap()::g_jit_codes_map
0000000000000008
paddle::operators::jit::GetJITCodesMap()::g_jit_codes_map
0000000000000030
guard variable for paddle::framework::global_transfer_data_cache()::x
0000000000000008
paddle::framework::global_transfer_data_cache()::x
0000000000000008
guard variable for paddle::framework::global_transfer_scope_cache()::x
0000000000000008
paddle::framework::global_transfer_scope_cache()::x
0000000000000008
paddle::platform::DeviceTracerImpl::AddActiveKindRecords(std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned long, unsigned long, long, long, unsigned int)::local_active_kind_records
0000000000000008
paddle::platform::DeviceTracerImpl::AddMemInfoRecord(unsigned long, unsigned long, unsigned long, paddle::platform::Place const&, std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, long)::local_mem_info_record
0000000000000008
paddle::platform::DeviceTracerImpl::AddCPURecords(std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned long, unsigned long, long, long)::local_cpu_records_
0000000000000008
paddle::platform::DeviceTracerImpl::AddAnnotation(unsigned int, paddle::platform::Event*)::local_correlations_pairs
0000000000000008
```
排查了一下出现`thread_local`的地方，1.6.2后有两处：
- #21086 11月15日 merge
```
void DownpourWorker::CopyDenseTable() {
  if (thread_id_ != 0) {
    return;
  }
  thread_local std::vector<std::future<int32_t>> pull_dense_status;
```
对应上面的
```
guard variable for paddle::framework::DownpourWorker::CopyDenseTable()::pull_dense_status
0000000000000008
paddle::framework::DownpourWorker::CopyDenseTable()::pull_dense_status
0000000000000018
```
- #21169 11月29日merge
```
std::unordered_set<std::string> *GetThreadLocalUsedVarNameSet() {
  thread_local std::unordered_set<std::string> used_var_name_set;
  return &used_var_name_set;
}
```
对应上面的
```
guard variable for paddle::framework::GetThreadLocalUsedVarNameSet()::used_var_name_set
0000000000000008
paddle::framework::GetThreadLocalUsedVarNameSet()::used_var_name_set
0000000000000030
```

**Comment by zhiqiu** [comment]
@OliverLPH @JepsonWong @luotao1 
Would you please try to upgrade glibc to higher version, such as 2.22 or higher ? Here are some information.

> dlopen：cannot load any more object with static TLS

This error message is reported in [elf/dl-open.c](https://sourceware.org/git/?p=glibc.git;a=blob;f=elf/dl-open.c;h=7adf66b221fdbb748b909fdfc436be099801b192;hb=eefa3be8e4c2c721a9f277d8ea2e11180231829f), line 541.


![image](https://user-images.githubusercontent.com/6888866/71507639-2488d300-28c0-11ea-9716-e51621d8b3e4.png)

The condition is number of module(.so) which uses static TLS is larger than `DTV_SURPLUS` which is 14 by default. 


This check is removed in later versions (glibc 2.22 or higher). So I guess we can fix it by,


1.  upgrade glibc to 2.22 or higner,
2. set `DTV_SURPLUS` to a custom value, larger than 14, for example, 32, in sysdeps/generic/ldsodefs.h, and recompile glibc 2.18.

**In addition**,
as far as I know, `core_avx.so` in Paddle is compiled with `-fPIC` option, so the `tls-model` of `core_avx.so` should be `global-dynamic`, which is not related to `STATIC TLS`, ref [gcc](https://gcc.gnu.org/onlinedocs/gcc/Code-Gen-Options.html).
![image](https://user-images.githubusercontent.com/6888866/71507312-0ec6de00-28bf-11ea-9409-44a4217af892.png)

**Comment by luotao1** [comment]
Thanks for @zhiqiu 
> for example, glibc 2.23

Is 2.23 too higher? Both @wanghaoshuang and I prefer to solve it in codes, not operating system
> so the tls-model of core_avx.so should be global-dynamic, which is not related to STATIC TLS

I find a similar issue in pytorch. 
- `I added these compile flags -fPIC -ftls-model=global-dynamic in setup.py, and recompiled pytorch, and it seems to have resolved my issue`. https://github.com/pytorch/pytorch/issues/2083#issuecomment-345330173
- https://github.com/pytorch/pytorch/pull/24889 Use a ptr to reduce TLS

**Comment by zhiqiu** [comment]
@luotao1 We have tried to set `DTV_SURPLUS ` to `32` and recompile `glibc 2.18`,  it works.
And I checked, `glibc 2.22` is sufficient to fix this problem.

**Comment by xsc351072127** [comment]
> @OliverLPH @JepsonWong @luotao1
> Would you please try to upgrade glibc to higher version, such as 2.22 or higher ? Here are some information.
> 
> > dlopen：cannot load any more object with static TLS
> 
> This error message is reported in [elf/dl-open.c](https://sourceware.org/git/?p=glibc.git;a=blob;f=elf/dl-open.c;h=7adf66b221fdbb748b909fdfc436be099801b192;hb=eefa3be8e4c2c721a9f277d8ea2e11180231829f), line 541.
> 
> ![image](https://user-images.githubusercontent.com/6888866/71507639-2488d300-28c0-11ea-9716-e51621d8b3e4.png)
> 
> The condition is number of module(.so) which uses static TLS is larger than `DTV_SURPLUS` which is 14 by default.
> 
> This check is removed in later versions (glibc 2.22 or higher). So I guess we can fix it by,
> 
> 1. upgrade glibc to 2.22 or higner,
> 2. set `DTV_SURPLUS` to a custom value, larger than 14, for example, 32, in sysdeps/generic/ldsodefs.h, and recompile glibc 2.18.
> 
> **In addition**,
> as far as I know, `core_avx.so` in Paddle is compiled with `-fPIC` option, so the `tls-model` of `core_avx.so` should be `global-dynamic`, which is not related to `STATIC TLS`, ref [gcc](https://gcc.gnu.org/onlinedocs/gcc/Code-Gen-Options.html).
> ![image](https://user-images.githubusercontent.com/6888866/71507312-0ec6de00-28bf-11ea-9409-44a4217af892.png)

Thank you very much!!!!
