### ISSUE TITLE
paddle 版本1.6  cpu 多核无法同时处理任务，只能单个核跑。

### ISSUE THREAD

**Issue by gzu-hmjiang** [PaddlePaddle/Paddle#21770]
程序代码中已设置os.environ['CPU_NUM'] = str(2)
def main(use_cuda, is_local):
    """
    main: train and infer
    """
    if use_cuda and not fluid.core.is_compiled_with_cuda():
        return
    os.environ['CPU_NUM'] = str(2)
    # Directory for saving the inference model
    save_dirname = "./output/model/"
    if not os.path.isdir(save_dirname):
        os.makedirs(save_dirname)
    train(use_cuda, save_dirname, is_local)
    #  infer(use_cuda, save_dirname)

if __name__ == '__main__':
    use_cuda = os.getenv("PADDLE_USE_GPU", "0") == "1"
    is_local = True  # os.getenv("PADDLE_IS_LOCAL", "0") == "1"
    main(use_cuda, is_local)
但是开发机上还是跑的单核 cpu，另一个 cpu 的利用率一直没上去。如何解决？

**Comment by JepsonWong** [comment]
方便贴一下您的相关代码么，我本地复现一下。

**Comment by gzu-hmjiang** [comment]
上面写的就是本地代码，数据你随便找一个就可以撒。

**Comment by gzu-hmjiang** [comment]
train 的接口实现的就是训练的过程。

**Comment by JepsonWong** [comment]
> train 的接口实现的就是训练的过程。

我想问的是train里面代码是如何实现的，使用的ParallelExecutor还是Executor。
