### ISSUE TITLE
paddle1.6.1通过save_inference_model保存的二进制词向量转换成文本报错

### ISSUE THREAD

**Issue by rotc** [PaddlePaddle/Paddle#21779]
参考[语义角色标注](https://www.paddlepaddle.org.cn/documentation/docs/zh/beginners_guide/basics/label_semantic_roles/index.html)的代码
```
def load_parameter(file_name, h, w):
    with open(file_name, 'rb') as f:
        f.read(16)  # skip header.
        return np.fromfile(f, dtype=np.float32).reshape(h, w)
```
解析通过`fluid.io.save_inference_model(save_dirname, test_feed_order, [scale_infer], exe)`保存的词向量`term_table`
```
    query_basic_emb = layers.embedding(
        input=query_basic,
        dtype='float32',
        size=[1000002, 128],
        param_attr='term_table',
        is_sparse=IS_SPARSE)
```
报错，看起来是header的大小不对，其中a是保存的二进制term_table路径，看起来`f.read(28)`就可以成功
```
>>> load_parameter(a, 1000002, 128)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "load_embedding.py", line 25, in load_parameter
    return np.fromfile(f, dtype=np.float32).reshape(h, w)
ValueError: cannot reshape array of size 128000259 into shape (1000002,128)
```

**Comment by zhangting2020** [comment]
请问是直接使用了语义角色标注的代码，paddle1.6版本，报错的吗？自己有做什么改动吗？

**Comment by rotc** [comment]
> 请问是直接使用了语义角色标注的代码，paddle1.6版本，报错的吗？自己有做什么改动吗？
不是用语义角色标注代码训练的，是自己的模型训出来，然后save_inference_model保存的

**Comment by rotc** [comment]
> 请问是直接使用了语义角色标注的代码，paddle1.6版本，报错的吗？自己有做什么改动吗？

不是的，用的是自己的模型训练，然后save_inference_model保存的词向量结果

**Comment by zhangting2020** [comment]
能否提供一个可以复现问题的脚本，以方便相关同学排查

**Comment by rotc** [comment]
> 能否提供一个可以复现问题的脚本，以方便相关同学排查

已提供

**Comment by zhangting2020** [comment]
建议通过保存下来的网络描述，拿到embedding的参数名字。根据参数名，获取参数可以参考链接：https://www.paddlepaddle.org.cn/documentation/docs/zh/faq/train_cn.html#q-numpyfcw

**Comment by zhangting2020** [comment]
用户反馈上面给出的方法已解决问题。
