### ISSUE TITLE
运行出错

### ISSUE THREAD

**Issue by Anikily** [PaddlePaddle/Paddle#21773]
W1216 20:15:13.219652 109084 init.cc:212] *** Aborted at 1576498513 (unix time) try "date -d @1576498513" if you are using GNU date ***
W1216 20:15:13.220960 109084 init.cc:212] PC: @                0x0 (unknown)
W1216 20:15:13.221151 109084 init.cc:212] *** SIGFPE (@0x7fa7bee8e778) received by PID 109084 (TID 0x7fa8b289d740) from PID 18446744072617518968; stack trace: ***
W1216 20:15:13.222162 109084 init.cc:212]     @     0x7fa8b248c130 (unknown)
W1216 20:15:13.223608 109084 init.cc:212]     @     0x7fa7bee8e778 paddle::operators::ConvOp::InferShape()
W1216 20:15:13.225199 109084 init.cc:212]     @     0x7fa7c107dc9e paddle::framework::OperatorWithKernel::RuntimeInferShape()
W1216 20:15:13.227766 109084 init.cc:212]     @     0x7fa7c107ab4b paddle::imperative::PreparedOp::Run()
W1216 20:15:13.229153 109084 init.cc:212]     @     0x7fa7beb46677 paddle::imperative::OpBase::Run()
W1216 20:15:13.230280 109084 init.cc:212]     @     0x7fa7beb4ea48 paddle::imperative::Tracer::TraceOp()
W1216 20:15:13.230381 109084 init.cc:212]     @     0x7fa7bea1e661 _ZZN8pybind1112cpp_function10initializeIZN6paddle6pybind14BindImperativeEPNS_6moduleEEUlRNS2_10imperative6TracerERKSsRKSt13unordered_mapISsNS_6handleESt4hashISsESt8equal_toISsESaISt4pairIS9_SC_EEESM_SB_ISsN5boost7variantINSN_5blankEifSsSt6vectorIiSaIiEESQ_IfSaIfEESQ_ISsSaISsEEbSQ_IbSaIbEEPNS2_9framework9BlockDescElSQ_IS11_SaIS11_EESQ_IlSaIlEENSN_6detail7variant5void_ES18_S18_S18_S18_S18_S18_EESE_SG_SaISH_IS9_S19_EEERKNS2_8platform8CPUPlaceEbE16_vIS8_SA_SM_SM_S1C_S1G_bEINS_4nameENS_9is_methodENS_7siblingEEEEvOT_PFT0_DpT1_EDpRKT2_ENUlRNS_6detail13function_callEE1_4_FUNES1Y_
W1216 20:15:13.231215 109084 init.cc:212]     @     0x7fa7be954e26 pybind11::cpp_function::dispatcher()
W1216 20:15:13.232594 109084 init.cc:212]     @     0x7fa8b29cdc54 _PyCFunction_FastCallDict
W1216 20:15:13.233760 109084 init.cc:212]     @     0x7fa8b2a55c0e call_function
W1216 20:15:13.234992 109084 init.cc:212]     @     0x7fa8b2a7875a _PyEval_EvalFrameDefault
W1216 20:15:13.236136 109084 init.cc:212]     @     0x7fa8b2a4ee66 _PyEval_EvalCodeWithName
W1216 20:15:13.237262 109084 init.cc:212]     @     0x7fa8b2a4fe73 fast_function
W1216 20:15:13.238386 109084 init.cc:212]     @     0x7fa8b2a55b95 call_function
W1216 20:15:13.239624 109084 init.cc:212]     @     0x7fa8b2a7875a _PyEval_EvalFrameDefault
W1216 20:15:13.240768 109084 init.cc:212]     @     0x7fa8b2a4ee66 _PyEval_EvalCodeWithName
W1216 20:15:13.241896 109084 init.cc:212]     @     0x7fa8b2a4fed6 fast_function
W1216 20:15:13.243023 109084 init.cc:212]     @     0x7fa8b2a55b95 call_function
W1216 20:15:13.244251 109084 init.cc:212]     @     0x7fa8b2a7951c _PyEval_EvalFrameDefault
W1216 20:15:13.245379 109084 init.cc:212]     @     0x7fa8b2a4ee66 _PyEval_EvalCodeWithName
W1216 20:15:13.246522 109084 init.cc:212]     @     0x7fa8b2a4fed6 fast_function
W1216 20:15:13.247647 109084 init.cc:212]     @     0x7fa8b2a55b95 call_function
W1216 20:15:13.248891 109084 init.cc:212]     @     0x7fa8b2a7951c _PyEval_EvalFrameDefault
W1216 20:15:13.250103 109084 init.cc:212]     @     0x7fa8b2a502db _PyFunction_FastCallDict
W1216 20:15:13.251300 109084 init.cc:212]     @     0x7fa8b29ce01f _PyObject_FastCallDict
W1216 20:15:13.252504 109084 init.cc:212]     @     0x7fa8b29d2aa3 _PyObject_Call_Prepend
W1216 20:15:13.253727 109084 init.cc:212]     @     0x7fa8b29cda5e PyObject_Call
W1216 20:15:13.254964 109084 init.cc:212]     @     0x7fa8b2a79e37 _PyEval_EvalFrameDefault
W1216 20:15:13.256093 109084 init.cc:212]     @     0x7fa8b2a4ee66 _PyEval_EvalCodeWithName
W1216 20:15:13.257293 109084 init.cc:212]     @     0x7fa8b2a5037e _PyFunction_FastCallDict
W1216 20:15:13.258496 109084 init.cc:212]     @     0x7fa8b29ce01f _PyObject_FastCallDict
W1216 20:15:13.259686 109084 init.cc:212]     @     0x7fa8b29d2aa3 _PyObject_Call_Prepend
Floating point exception

**Comment by JepsonWong** [comment]
请问您的GPU、GCC、Paddle环境，程序的完整错误LOG是什么？

**Comment by Anikily** [comment]
@JepsonWong GPU:Tesla V100
GCC:4.8.2
Paddle:1.6.0
CUDA:9.0

**Comment by JepsonWong** [comment]
> @JepsonWong GPU:Tesla V100
> GCC:4.8.2
> Paddle:1.6.0
> CUDA:9.0

麻烦提供一下程序的完整LOG和复现代码。谢谢
