### ISSUE TITLE
Need to add some new algorithm(like direct, winograd) for convolution calculation.

### ISSUE THREAD

**Issue by hedaoyuan** [PaddlePaddle/Paddle#2177]
At present, there are only sgemm and CUDNN-based convolution implementations in Paddle. In a model training or prediction without a GPU, can only select convolution calculations based on sgemm. However, based on the sgemm convolution calculation, performance is not optimal in many scenarios. [see here](https://github.com/soumith/convnet-benchmarks/blob/master/README.md)

We also encountered the problem of convolution computing performance when deploying Paddle into some product environments. At the same time, there are many excellent convolution implementation libraries, I think we can try to import it into Paddle to improve the Paddle convolution calculation performance.

**Comment by hedaoyuan** [comment]
### Convolution performance
Convolution layer performance in a ResNet model with 3x3 kernel. Test in a raspberry environment, and build with NNPACK. We can see that some layers with gemm algorithm performance better, while some layers with wt8x8 algorithm performance better.

![image](https://cloud.githubusercontent.com/assets/21339431/26479863/e284600a-4208-11e7-92c9-c252ca0d9134.png)

**Comment by Xreki** [comment]
NNPACK is supported in v2 Paddle and new features won't be implemented based on v2, so close this issue.
