### ISSUE TITLE
paddle.fluid.embedding 出错

### ISSUE THREAD

**Issue by aixier** [PaddlePaddle/Paddle#21782]
CPU 2
RAM 8GB
Python 3.7
PaddlePaddle 1.6.0
输入数据：
![1](https://user-images.githubusercontent.com/7700464/70963674-34383880-20c4-11ea-8945-b23db9c964af.png)
```
代码：
        print("sliced_feature len ====",sliced_feature.shape)
        paddle.fluid.layers.Print(sliced_feature,summarize=20)
        emb = fluid.layers.embedding(input=sliced_feature, size=[10000, 3*15*108], param_attr=fluid.ParamAttr(learning_rate=30))
```
出错信息：
![2](https://user-images.githubusercontent.com/7700464/70963723-5631bb00-20c4-11ea-962f-facb7632e9cc.png)
@zhangting2020 
[data.txt](https://github.com/PaddlePaddle/Paddle/files/3971391/data.txt)

**Comment by zhangting2020** [comment]
看了下报错内容：embedding的输入(input)的值要在0～10000之间，但是输入的值中存在-1。
可以参考该API的说明，关于输入有提到：input中的id必须满足 0 =< id < size[0] 。https://www.paddlepaddle.org.cn/documentation/docs/zh/api_cn/fluid_cn/embedding_cn.html#embedding
请检查embedding的输入。

**Comment by aixier** [comment]
查到了谢谢
