### ISSUE TITLE
image_util.py 内flip函数修正

### ISSUE THREAD

**Issue by wudenggang** [PaddlePaddle/Paddle#21799]
- 版本、环境信息：
    1）PaddlePaddle版本：paddlle 1.6及之前版本有此问题
![flip函数修正](https://user-images.githubusercontent.com/3587832/71004521-fca9aa80-211c-11ea-9f1b-c6c831d41488.png)

**Comment by zhangting2020** [comment]
你好，这个应该不是一个bug，是flip函数注释存在问题。可以看在crop_img中调用了该函数，传进flip的输入图像实际是K x H x W的：
https://github.com/PaddlePaddle/Paddle/blob/04909137f52a0c6d495c4d882f9ef853a2fcd24d/python/paddle/utils/image_util.py#L45-L49
