### ISSUE TITLE
Tensor holds no memory. Call Tensor::mutable_data first

### ISSUE THREAD

**Issue by liushanshan07** [PaddlePaddle/Paddle#21794]
------------------------------------------
Python Call Stacks (More useful to users):
------------------------------------------
  File "/home/vis/liushanshan/common_env/anaconda2_cuda90_fix_dev/lib/python2.7/site-packages/paddle/fluid/framework.py", line 2423, in append_op
    attrs=kwargs.get("attrs", None))
  File "/home/vis/liushanshan/common_env/anaconda2_cuda90_fix_dev/lib/python2.7/site-packages/paddle/fluid/layer_helper.py", line 43, in append_op
    return self.main_program.current_block().append_op(*args, **kwargs)
  File "/home/vis/liushanshan/common_env/anaconda2_cuda90_fix_dev/lib/python2.7/site-packages/paddle/fluid/layers/nn.py", line 8337, in softmax_with_cross_entropy
    'axis': axis
  File "/home/vis/liushanshan/common_env/anaconda2_cuda90_fix_dev/lib/python2.7/site-packages/paddle/fluid/layers/detection.py", line 1543, in ssd_loss
    conf_loss = nn.softmax_with_cross_entropy(confidence, target_label)
  File "./train.py", line 199, in parallel_exe
    loss = fluid.layers.ssd_loss(locs, confs, gt_box, gt_label, box, box_var)
  File "./train.py", line 374, in <module>
    pretrained_model=args.pretrained_model)

----------------------
Error Message Summary:
----------------------
PaddleCheckError: holder_ should not be null
Tensor holds no memory. Call Tensor::mutable_data first. at [/root/Paddle/paddle/fluid/framework/tensor.cc:23]
  [operator < softmax_with_cross_entropy > error]

报错信息如上，operator < softmax_with_cross_entropy > error

**Comment by zhangting2020** [comment]
该问题是由于Tensor未被初始化。麻烦检查一下softmax_with_cross_entropy的输入是否有数据呢？

**Comment by liushanshan07** [comment]
> 该问题是由于Tensor未被初始化。麻烦检查一下softmax_with_cross_entropy的输入是否有数据呢？

loss = fluid.layers.ssd_loss(locs, confs, gt_box, gt_label, box, box_var)
你好，程序是挂在这句话。我check输入都是有值的，在python2.7/site-packages/paddle/fluid/layers/detection.py的ssd_loss内挂的，如何check？

**Comment by chenwhql** [comment]
你好，有没有C++栈信息，能贴出来一下吗

**Comment by liushanshan07** [comment]
> 你好，有没有C++栈信息，能贴出来一下吗

C++ Call Stacks (More useful to developers):
--------------------------------------------
0   std::string paddle::platform::GetTraceBackString<std::string const&>(std::string const&, char const*, int)
1   paddle::platform::EnforceNotMet::EnforceNotMet(std::string const&, char const*, int)
2   paddle::framework::Tensor::check_memory_size() const
3   paddle::operators::math::SetConstant<paddle::platform::CUDADeviceContext, float>::operator()(paddle::platform::CUDADeviceContext const&, paddle::framework::Tensor*, float)
4   paddle::operators::SoftmaxWithCrossEntropyCUDAKernel<float>::Compute(paddle::framework::ExecutionContext const&) const
5   std::_Function_handler<void (paddle::framework::ExecutionContext const&), paddle::framework::OpKernelRegistrarFunctor<paddle::platform::CUDAPlace, false, 0ul, paddle::operators::SoftmaxWithCrossEntropyCUDAKernel<float>, paddle::operators::SoftmaxWithCrossEntropyCUDAKernel<paddle::platform::float16>, paddle::operators::SoftmaxWithCrossEntropyCUDAKernel<double> >::operator()(char const*, char const*, int) const::{lambda(paddle::framework::ExecutionContext const&)#1}>::_M_invoke(std::_Any_data const&, paddle::framework::ExecutionContext const&)
6   paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&, paddle::framework::RuntimeContext*) const
7   paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&) const
8   paddle::framework::OperatorBase::Run(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&)
9   paddle::framework::details::ComputationOpHandle::RunImpl()
10  paddle::framework::details::FastThreadedSSAGraphExecutor::RunOpSync(paddle::framework::details::OpHandleBase*)
11  paddle::framework::details::FastThreadedSSAGraphExecutor::RunOp(paddle::framework::details::OpHandleBase*, std::shared_ptr<paddle::framework::BlockingQueue<unsigned long> > const&, unsigned long*)
12  std::_Function_handler<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> (), std::__future_base::_Task_setter<std::unique_ptr<std::__future_base::_Result<void>, std::__future_base::_Result_base::_Deleter>, void> >::_M_invoke(std::_Any_data const&)
13  std::__future_base::_State_base::_M_do_set(std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> ()>&, bool&)
14  ThreadPool::ThreadPool(unsigned long)::{lambda()#1}::operator()() const

**Comment by chenwhql** [comment]
感谢提供，看了下代码，发现这是个bug，在PR https://github.com/PaddlePaddle/Paddle/pull/21810 修复

**Comment by liushanshan07** [comment]
> 感谢提供，看了下代码，发现这是个bug，在PR #21810 修复

辛苦。我拿官网ssd model训了下也遇到了同样问题。求问这个bug是啥意思？通俗点帮忙解释下？

**Comment by chenwhql** [comment]
就是当属性axis所在的数据dim为1 的话，会先将输出变量softmax全部初始化为1，loss全部初始化为0，但这属于对tensor的操作，应该在tensor调用mutable_data申请内存之后进行，原程序里设置初值的操作在申请内存之前进行的，所以错了。之前的单测没有测试axis_dim为1的情况

这是程序错误的逻辑，至于为什么要设置1和0，可能得问下写这块代码的人

**Comment by liushanshan07** [comment]
> 就是当属性axis所在的数据dim为1 的话，会先将输出变量softmax全部初始化为1，loss全部初始化为0，但这属于对tensor的操作，应该在tensor调用mutable_data申请内存之后进行，原程序里设置初值的操作在申请内存之前进行的，所以错了。之前的单测没有测试axis_dim为1的情况
> 
> 这是程序错误的逻辑，至于为什么要设置1和0，可能得问下写这块代码的人

求问该bug目前pr合入了吗。拉最新的lastest可以训练吗。

**Comment by zhangting2020** [comment]
> 求问该bug目前pr合入了吗。拉最新的lastest可以训练吗。

bug修复的PR已合入，拉取最新的develop代码即可

**Comment by liushanshan07** [comment]
> > 求问该bug目前pr合入了吗。拉最新的lastest可以训练吗。
> 
> bug修复的PR已合入，拉取最新的develop代码即可

 上周五运行了下latest，出现这个问题。dlopen: cannot load any more object with static TLS

**Comment by JepsonWong** [comment]
> > > 求问该bug目前pr合入了吗。拉最新的lastest可以训练吗。
> > 
> > 
> > bug修复的PR已合入，拉取最新的develop代码即可
> 
> 上周五运行了下latest，出现这个问题。dlopen: cannot load any more object with static TLS

您好，这个问题我们在修复中。

**Comment by keithyin** [comment]
依旧出现了 Tensor holds no memory 问题， 版本 1.8.2 windows

`import paddle.fluid as fluid
import numpy as np
import paddle.fluid as fluid
import paddle

input_ = fluid.layers.data(name="input", shape=[-1, 1], lod_level=1,
                           append_batch_size=False, dtype="int64")  # , stop_gradient=False)
label = fluid.layers.data(
    name="label", shape=[-1, 1], append_batch_size=False, dtype="int64")


embed = fluid.embedding(
    input=input_,
    size=[100, 11],
    dtype='float32')

embed_ = fluid.layers.sequence_pool(embed, pool_type="AVERAGE")

place = fluid.CPUPlace()
exe = fluid.Executor(place)

exe.run(fluid.default_startup_program())

input_value = fluid.create_lod_tensor(data=np.array(
    [[1], [2], [3], [4]]), recursive_seq_lens=[[1, 3]], place=place)


embed_result = exe.run(fluid.default_main_program(), feed={
    label: np.array([[0], [1]]), input_: input_value}, fetch_list=[embed_])
print(embed_result[0].shape)`

**Comment by chenwhql** [comment]
> 依旧出现了 Tensor holds no memory 问题， 版本 1.8.2 windows
> 
> `import paddle.fluid as fluid
> import numpy as np
> import paddle.fluid as fluid
> import paddle
> 
> input_ = fluid.layers.data(name="input", shape=[-1, 1], lod_level=1,
> append_batch_size=False, dtype="int64") # , stop_gradient=False)
> label = fluid.layers.data(
> name="label", shape=[-1, 1], append_batch_size=False, dtype="int64")
> 
> embed = fluid.embedding(
> input=input_,
> size=[100, 11],
> dtype='float32')
> 
> embed_ = fluid.layers.sequence_pool(embed, pool_type="AVERAGE")
> 
> place = fluid.CPUPlace()
> exe = fluid.Executor(place)
> 
> exe.run(fluid.default_startup_program())
> 
> input_value = fluid.create_lod_tensor(data=np.array(
> [[1], [2], [3], [4]]), recursive_seq_lens=[[1, 3]], place=place)
> 
> embed_result = exe.run(fluid.default_main_program(), feed={
> label: np.array([[0], [1]]), input_: input_value}, fetch_list=[embed_])
> print(embed_result[0].shape)`

虽然报错提示一样，但这不是同一个问题，麻烦您新建一个issue，并附上完整的报错信息，我们会帮您处理

**Comment by keithyin** [comment]
> 虽然报错提示一样，但这不是同一个问题，麻烦您新建一个issue，并附上完整的报错信息，我们会帮您处理

找到问题了,  feed 的 key 写错了...    这里能否加一个更人性化的报错提示呢? 该 feed 的没有 feed 给出对应的报错信息
