### ISSUE TITLE
save_vars报错‘Getting 'tensor_desc' is not supported by the type of var _generated_var_0. at [/paddle/paddle/fluid/framework/var_desc.cc:207]’

### ISSUE THREAD

**Issue by XiaoheYou** [PaddlePaddle/Paddle#21795]
1）PaddlePaddle版本：1.4.1
    2）GPU：P4
    3）系统环境：centos6
    4）单卡

- 问题描述：fluid.io.save_vars 报错：
[ERROR 12-17 09:24:35.453 mask_rcnn_workflow_local.py:164] Getting 'tensor_desc' is not supported by the type of var _generated_var_0. at [/paddle/paddle/fluid/framework/var_desc.cc:207]
PaddlePaddle Call Stacks:
0       0x7f315d4e0ff8p void paddle::platform::EnforceNotMet::Init<std::string>(std::string, char const*, int) + 360
1       0x7f315d64f799p paddle::framework::VarDesc::tensor_desc() const + 521
2       0x7f315d64fa6cp paddle::framework::VarDesc::GetShape() const + 28
3       0x7f315d58c0f5p
4       0x7f315d513936p
5             0x4c5326p PyEval_EvalFrameEx + 37958
6             0x4b9b66p PyEval_EvalCodeEx + 774
7             0x4d5669p
8             0x4a5471p PyObject_CallFunction + 497
9             0x41ce79p _PyObject_GenericGetAttrWithDict + 1321
10            0x4bc2f8p PyEval_EvalFrameEx + 1048
11            0x4b9b66p PyEval_EvalCodeEx + 774
12            0x4c1f56p PyEval_EvalFrameEx + 24694
13            0x4b9b66p PyEval_EvalCodeEx + 774
14            0x4c17c6p PyEval_EvalFrameEx + 22758
15            0x4b9b66p PyEval_EvalCodeEx + 774
16            0x4c17c6p PyEval_EvalFrameEx + 22758
17            0x4c141fp PyEval_EvalFrameEx + 21823
18            0x4c141fp PyEval_EvalFrameEx + 21823
19            0x4c141fp PyEval_EvalFrameEx + 21823
20            0x4c141fp PyEval_EvalFrameEx + 21823
21            0x4b9b66p PyEval_EvalCodeEx + 774
22            0x4eb69fp
23            0x4e58f2p PyRun_FileExFlags + 130
24            0x4e41a6p PyRun_SimpleFileExFlags + 390
25            0x4938cep Py_Main + 1358
26      0x7f3215fc0830p __libc_start_main + 240
27            0x493299p _start + 41

**Comment by zhangting2020** [comment]
从上面的log难以确定问题。能提供一个复现问题的脚本吗？

**Comment by XiaoheYou** [comment]
> 从上面的log难以确定问题。能提供一个复现问题的脚本吗？

你们自带的demo，保存模型的时候，把save_persistables改成save_vars就能复现。

**Comment by zhangting2020** [comment]
请问有试过1.6版本吗？可以使用1.6看看会不会出现这个错误

**Comment by zhangting2020** [comment]
建议使用1.6版本。
save接口，请参考：https://www.paddlepaddle.org.cn/documentation/docs/zh/api_cn/io_cn/save_cn.html#save
load接口，请参考：
https://www.paddlepaddle.org.cn/documentation/docs/zh/api_cn/layers_cn/load_cn.html#load

**Comment by zhangting2020** [comment]
与用户沟通后，目前确认应该是1.4版本存在的bug。用户使用save_vars文档说明中的示例代码，在1.4版本中发现无法跑通。我用1.6.0版本测试，运行无问题。用户将升级paddle版本。
