### ISSUE TITLE
lstm operator only gpu devices supported

### ISSUE THREAD

**Issue by zlinker** [PaddlePaddle/Paddle#21796]
**System information**
-PaddlePaddle version: 1.6

I tried to use **fluid.layers.lstm** in a sequential encoding task on cpu mpi cluster, and was surprised to found it unsupported for cpu devices since [version 1.2](https://github.com/PaddlePaddle/Paddle/blob/release/1.2/python/paddle/fluid/layers/nn.py#L492), wondering why it was still incompleted in the [latest version](https://github.com/PaddlePaddle/Paddle/blob/release/1.6/python/paddle/fluid/layers/nn.py#L862) instead of simply calling the **cudnn_lstm** operator?

**Comment by zhangting2020** [comment]
cpu support  of lstm op is currently planned.

**Comment by AoZhang** [comment]
Can I use layers.LSTMCell + layers.rnn instead? Like:
```
lstm_cell = layers.LSTMCell(...)
hidden, state = layers.rnn(lstm_cell, inputs)
```
And what's the difference with `layers.lstm(inputs, ...)`
