### ISSUE TITLE
如何修改训练好的网络参数

### ISSUE THREAD

**Issue by jinxuan777** [PaddlePaddle/Paddle#21807]
已经训练好的imagenet的（VGG）weight中的fc7，想要修改一些位置的weight然后重新保存，有相应的例子不

**Comment by MrChengmo** [comment]
没有一步到位的方法可以实现这个功能，但是可以按照以下步骤尝试一下：

1. load训练好的模型
2. 从scope中取到对应的参数，并转换为nparray的格式，示例
   >print(scope.var("fc_0.w_0").get_tensor().__array__())
3. 用该array修改指定位置的weight
4. 保存该weight
5. 利用该weight初始化模型，并正常保存即可，参考该api:https://www.paddlepaddle.org.cn/documentation/docs/zh/api_cn/initializer_cn/NumpyArrayInitializer_cn.html#numpyarrayinitializer
