### ISSUE TITLE
paddle::CreatePaddlePredictor函数出core

### ISSUE THREAD

**Issue by hustluy** [PaddlePaddle/Paddle#21803]
- 版本、环境信息：
    1）PaddlePaddle版本：1.6.1
    2）GPU：GPU型号：P4，CUDA：10.1，CUDNN：7.5
    3）系统环境：CentOS release 6.3
-预测信息
    1）C++预测：paddlepaddle@v1.6.1-gcc82-cuda10.1-cudnn7.5_PD_BL
    2）API信息：
        paddle::AnalysisConfig config(model_dir);
        config.EnableUseGpu(gpu_memory_size, device);
        if (multi_input == 1) {
            config.SwitchSpecifyInputNames(true);
            config.SwitchUseFeedFetchOps(false);
        }
    3）预测库来源：BCLOUD编译
- 问题描述：堆栈信息如下：
![image](https://user-images.githubusercontent.com/3147108/71046694-01e61400-2174-11ea-860a-58b511a8cd70.png)

**Comment by MrChengmo** [comment]
> * 版本、环境信息：
>      1）PaddlePaddle版本：1.6.1
>      2）GPU：GPU型号：P4，CUDA：10.1，CUDNN：7.5
>      3）系统环境：CentOS release 6.3
>   -预测信息
>      1）C++预测：[paddlepaddle@v1.6.1-gcc82-cuda10.1-cudnn7.5_PD_BL](mailto:paddlepaddle@v1.6.1-gcc82-cuda10.1-cudnn7.5_PD_BL)
>      2）API信息：
>   paddle::AnalysisConfig config(model_dir);
>   config.EnableUseGpu(gpu_memory_size, device);
>   if (multi_input == 1) {
>   config.SwitchSpecifyInputNames(true);
>   config.SwitchUseFeedFetchOps(false);
>   }
>      3）预测库来源：BCLOUD编译
> * 问题描述：堆栈信息如下：
>   ![image](https://user-images.githubusercontent.com/3147108/71046694-01e61400-2174-11ea-860a-58b511a8cd70.png)

已经转交给预测的同学跟进。
