### ISSUE TITLE
似乎是个bug，TypeError: precision_recall_evaluator() got an unexpected keyword argument 'top_k'

### ISSUE THREAD

**Issue by OleNet** [PaddlePaddle/Paddle#2181]
使用sentiment_net.py文件的时候，执行这句话:
```outputs(classification_cost(input=output, label=data_layer('label', 1), evaluator=[precision_recall_evaluator, classification_error_evaluator]))```
会报错
![image](https://cloud.githubusercontent.com/assets/3206718/26150501/2faf7362-3b31-11e7-9234-f2e9a0700854.png)

按照错误信息，改了一下源代码：
paddle/trainer_config_helpers/layers.py line 3853:
![image](https://cloud.githubusercontent.com/assets/3206718/26150533/4eaf427e-3b31-11e7-9083-1f705d10a99c.png)

运行成功了，打印出了我想要的指标。

所以估计这是一个bug。

**Comment by lcy-seso** [comment]
确实是一个bug~ 谢谢你。
