### ISSUE TITLE
linux环境下的离线安装有像windows这样的教程吗

### ISSUE THREAD

**Issue by huangyunhua** [PaddlePaddle/Paddle#21820]
https://paddle-wheel.bj.bcebos.com/1.5.2-win-offline/paddle_windows%E7%A6%BB%E7%BA%BF%E5%AE%89%E8%A3%85%E5%8C%85%E8%AF%B4%E6%98%8E%E6%96%87%E6%A1%A3.pdf

**Comment by MrChengmo** [comment]
linux环境下需要机器安装有docker，然后可以离线的安装含有paddle的docker镜像，以此完成paddle离线的安装。

- 离线安装教程：https://paddle-docker-tar.bj.bcebos.com/%E3%80%8APaddlePaddle%E4%BC%81%E4%B8%9A%E7%A6%BB%E7%BA%BF%E5%AE%89%E8%A3%85%E5%8C%85%E8%AF%B4%E6%98%8E%E6%96%87%E6%A1%A3%E3%80%8B.pdf

- 最新的docker环境：

https://paddle-docker-tar.bj.bcebos.com/1.6.2/paddle-fluid-1.6.2-offline.zip

**Comment by huangyunhua** [comment]
非常感谢，我已经下载了paddle-fluid-1.6.2-offline.tar，可是为什么会有12G这么大呢？

**Comment by MrChengmo** [comment]
> 非常感谢，我已经下载了paddle-fluid-1.6.2-offline.tar，可是为什么会有12G这么大呢？

包含了linux下常用工具，方便在docker中进行开发：
![image](https://user-images.githubusercontent.com/29789135/71089657-4b6a4980-21dc-11ea-8304-9b9d2384aaf1.png)

**Comment by huangyunhua** [comment]
https://blog.csdn.net/m0_37872090/article/details/103626734  这是我写的离线安装Paddle的教程，这样安装安装包只有200M，希可以帮到需要的人。
