### ISSUE TITLE
Topology(...)  生成的模型配置（prototxt），有局限性

### ISSUE THREAD

**Issue by NHZlX** [PaddlePaddle/Paddle#2183]
hi， 我将paddle生成的resnet32模型以protobuf的形式保存成文件，[see prototxt](https://github.com/NHZlX/paddle_issue)，发现，所有的层都会把feature map的size、height、widht固定，这样”写死“ 会有很多局限性吧。比如检测模型的输入不会固定，即使是分类模型，也有可能将模型改成全卷机来接收比训练时候大的输入, [look example](https://github.com/BVLC/caffe/blob/master/examples/net_surgery.ipynb)。

**Comment by lcy-seso** [comment]
@qingqing 比较了解图像，拜托qingqing帮忙看看。谢谢啦~

**Comment by pengwangucla** [comment]
It seems currently for test, paddle has no way to online change size because all the shape is fixed using python, there is no online changing of size in c++ code.

**Comment by qingqing01** [comment]
C++核心代码支持变长，正打算支持mini-batch间变长~

**Comment by qingqing01** [comment]
proto config里计算是依据data_layer设置的size计算得到的。C++代码再计算时会依赖当前mini-batch输入数据的height/width来计算，不会直接使用proto config里计算的值~
