### ISSUE TITLE
paddle怎么创建一个常量矩阵，矩阵里每个元素的值不同，类似于TF的tf.constant([11,22,33])

### ISSUE THREAD

**Issue by xcwei** [PaddlePaddle/Paddle#21831]
paddle怎么创建一个常量矩阵，矩阵里每个元素的值不同，类似于TF的tf.constant([11,22,33])

**Comment by danleifeng** [comment]
可以使用fluid.layers.assign 接口，比如：
`result3 = fluid.layers.assign(np.array([[2.5, 2.5], [2.5, 2.5], [2.5, 2.5]], dtype='float32'))`
更多assign信息可以参考：https://www.paddlepaddle.org.cn/documentation/docs/zh/api_cn/layers_cn/assign_cn.html#cn-api-fluid-layers-assign
