### ISSUE TITLE
对外宣讲碰到的问题

### ISSUE THREAD

**Issue by gongweibao** [PaddlePaddle/Paddle#21830]
1、其它框架模型权重向pp的权重转换支持与否，同时也看到过跨框架的模型转换的，但相对比较简单模型可以转换，不知道pp这块对这个有么有支持？
2、pp自定义算子构建针对部署的规范，是不是只要是C++的一定都支持后续部署？目前了解就是其它平台的算子也有采用C++的，但是都是需要CUDA相关背景知识，不知道pp这块是不是一样？
3、部署后的模型性能对比有么有？包括准确率和运行时间性能，另外部署支持的具体平台有么有列表？（cpu型号等）

**Comment by taoziliu** [comment]
展区开发者反馈：ngc.nvidia.com上的paddle没法正常启动

**Comment by danleifeng** [comment]
感谢您的反馈，已告知相关负责人。

**Comment by NHZlX** [comment]
1. 可以使用x2paddle https://github.com/PaddlePaddle/X2Paddle
2. PP自定义算子构建针对部署还在支持中。
3. Paddle原生预测引擎的支持x86 cpu， nvidia gpu server， nvidia jetson。
PaddleLite支持ARM CPU, Mali GPU, Adreno GPU, Huawei NPU.

另外后续遇到预测相关问题，紧急情况可直接联系相关同学，这样回复会快一些。
