### ISSUE TITLE
Seq2Seq 模型解码端支持动态词表

### ISSUE THREAD

**Issue by AoZhang** [PaddlePaddle/Paddle#21871]
需要实现一个解码端有语法约束的 seq2seq 模型，解码端通过语法知识限制解码词表空间，并解码为树结构。想问一下如何实现不同时间步下的动态词表。

**Comment by guoshengCS** [comment]
是否可以按照需要对在限制词表之外的词的score进行修改（比如设置为-INF）来达到目的呢

**Comment by AoZhang** [comment]
> 是否可以按照需要对在限制词表之外的词的score进行修改（比如设置为-INF）来达到目的呢

我也是想到了类似的方法：在完整词表上计算后，只在我想限定的词表范围内找答案。不过是感觉比较trick啊。paddle 原生有支持类似功能的方法吗。

**Comment by guoshengCS** [comment]
paddle目前支持[py_func](https://www.paddlepaddle.org.cn/documentation/docs/zh/advanced_usage/development/new_op/new_python_op.html)，也可以试下将一些特殊的search操作由py_func实现。一些定制化的功能，可能短期无法支持。
