### ISSUE TITLE
修改预测模型的输入和输出node

### ISSUE THREAD

**Issue by zzcgithub** [PaddlePaddle/Paddle#21893]
paddleslim保存的分类模型的inference model （model && params），默认的feed_target_name是["image", "label"], 默认的fetch_targets是top1的准确率， 如何根据model && params修改feed_target_name是["image"] 和 fetch_targets是分类概率呢？

**Comment by wilhelmzh** [comment]
https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/fluid/io.py#L1123

上面的可以参考下，可以去掉program里面的feed和fetch的op，然后你直接在exe.run里feed和fetch你想要feed和fetch的var，会自动添加对应的feed和fetch op
