### ISSUE TITLE
ImportError: cannot import name 'PostTrainingQuantization' 

### ISSUE THREAD

**Issue by hp-cuiwb** [PaddlePaddle/Paddle#21890]
- 标题：ImportError: cannot import name 'PostTrainingQuantization' 
- 版本、环境信息：
    1）PaddlePaddle版本：paddlepaddle-gpu 1.6.0.post97
    2）CPU/GPU：2080TI
    3）系统环境：Ubuntu16.04
    4）Python版本号  python3.7

**Comment by wilhelmzh** [comment]
你好，
1.6.0版本是没PostTrainingQuantization的，建议升级1.6.2或最新的develop版本
