### ISSUE TITLE
[CPU预测]qat2 int8预测性能下降

### ISSUE THREAD

**Issue by OliverLPH** [PaddlePaddle/Paddle#21918]
- 标题：[CPU预测]qat2 int8预测性能下降
- 版本、环境信息：
    1）PaddlePaddle版本：52a61edaad7 
    2）CPU：Intel(R) Xeon(R) Gold 6271C CPU @ 2.60GHz，MKLDNN
    3）GPU：无
    4）系统环境：hub.baidubce.com/paddlepaddle/paddle:latest-dev， Ubuntu1604
-预测信息
    1）C++预测：52a61edaad
    2）CMake命令
```shell
cmake .. -DWITH_PYTHON=ON \
-DWITH_SWIG_PY=OFF \
-DWITH_FLUID_ONLY=ON \
-DWITH_TESTING=OFF \
-DWITH_GPU=OFF \
-DWITH_MKL=ON \
-DWITH_MKLDNN=ON \
-DON_INFER=ON  \
-DCMAKE_BUILD_TYPE=Release
```

    3）API信息
    4）预测库来源：本地编译
- 复现信息：
测试脚本：https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/fluid/contrib/slim/tests/qat_int8_comparison.py
比较commit：b976ba3e和 commit：52a61edaad7，qat2量化的模型，fps都有一定程度的下降。

- 问题描述：

以mobilenetv2为例，fps从88下降到了83
![mobilenetv2](https://user-images.githubusercontent.com/14963836/71407701-c3ba8a00-2676-11ea-9879-6a26aec80aad.jpg)

mobilenetv1，fps从123下降到了117左右
![mobilnetv1](https://user-images.githubusercontent.com/14963836/71407611-7b02d100-2676-11ea-82f1-54419c847fe3.jpg)

**Comment by lidanqing-vv** [comment]
好的，我现在看下

**Comment by lidanqing-vv** [comment]
@OliverLPH  qat2 performance 现在用c++ 测试测，因为原先的python测试有overhead，小模型性能慢。
c++ 的代码测出来是 mobilenetv1 227.73, mobilenetv2 206.74。
测试command, 请参考https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/fluid/contrib/slim/tests/QAT_mkldnn_int8_readme.md
```
# 1. Save QAT2.0 INT8 model
cd /PATH/TO/PADDLE/build
python ../python/paddle/fluid/contrib/slim/tests/save_qat_model.py --qat_model_path /PATH/TO/DOWNLOAD/MODEL/${QAT2_MODEL_NAME} --int8_model_save_path /PATH/TO/${QAT2_MODEL_NAME}_qat_int8

# 2. Run the QAT2.0 C-API for performance benchmark
cd /PATH/TO/PADDLE/build
OMP_NUM_THREADS=1 paddle/fluid/inference/tests/api/test_analyzer_qat_image_classification ARGS --enable_fp32=false --with_accuracy_layer=false --int8_model=/PATH/TO/${QAT2_MODEL_NAME}_qat_int8 --infer_data=$HOME/.cache/paddle/dataset/int8/download/int8_full_val.bin --batch_size=1 --paddle_num_threads=1
```
提到的两个commit 我在上海6271验证了，mobilenetv1没有下降，mobilenetv2有一点下降，但是不稳定，因为模型小。我再确认一下mobilenetv2

**Comment by OliverLPH** [comment]
@lidanqing-intel 
我这边看主要就是mobilenetv1和mobilenetv2有明显下降。其他比如resnet和vgg用Python的测试仅看得出来有下降的趋势，但变化很小。（e.g. resent101从 19.69 下降到 19.22）

因为之前自动化测试用的是Python的脚本，现在还没更新到C++的脚本。
虽然Python测试小模型会慢一些，但Python预测性能下降和C++预测性能下降应该是一致的吧。

**Comment by lidanqing-intel** [comment]
@OliverLPH 
I found [013225bb68fc117b9e63efa41c329da76d1294e4] fix Execution order of ci_check_unittest, and add it to Linux_py35 (#21640) 
caused mobilenetv2 drop from 85.16 to 80.62 [shanghai 6271]

**Comment by lidanqing-vv** [comment]
@OliverLPH 
1. 这个结果是重复几次得到的？mobilenet小，需要多重复几次。另外batch_num是1000 还是 50000？
2. Python test  --batch_num=5000: 
**mobilenetv1 qat2**
从 b976ba3e 到 52a61edaad7 没有差别
**mobilenetv2 qat2**
before 25e765a4fece809874f5ab35ab44954739c7bdf9, fps 84.93 - 86.87
after 25e765a4fece809874f5ab35ab44954739c7bdf9, fps 80.04 - 83.45

3. C++ test: batch_num 50000
**mobilenetv1 qat2**
从 b976ba3e到52a61edaad7 没有差别
**mobilenetv2 qat2**
b976ba3e83ce0c29d9508afb977a947163682314  195.5799 - 197.9230
52a61edaad715b6c8521c39a279c071458ad0adf 200.8364 - 198.3155

我用的上海6271测的。总的来说，多次重复测全集，c++性能测试中这两个commit之间没有下降。python测试多次重复，在 25e765a4fece809874f5ab35ab44954739c7bdf9 处 Mobilenetv2下降了 1-4 fps。但是python 性能可能没有人去维护了，第一因为结果差于C++测试的(而且document也只显示了c++的)，二是这个commit是framework 和 io 改了代码，我们这边不好改。麻烦改成 C++测性能好吗？script我另外发给你。

**Comment by OliverLPH** [comment]
@lidanqing-intel 
1. batch_num是5000，重复一次得到的数据。

好的，那我就还是改成C++的进行测试吧，C++的script是 [SLIM Quantization-aware training (QAT) on INT8 MKL-DNN](https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/fluid/contrib/slim/tests/QAT_mkldnn_int8_readme.md) 吗？

**Comment by lidanqing-vv** [comment]
> @lidanqing-intel
> 
> 1. batch_num是5000，重复一次得到的数据。
> 
> 好的，那我就还是改成C++的进行测试吧，C++的script是 [SLIM Quantization-aware training (QAT) on INT8 MKL-DNN](https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/fluid/contrib/slim/tests/QAT_mkldnn_int8_readme.md) 吗？

是的，是那个文档。注意模型转化时，下载的是QAT2.0 的模型，不是1.0的模型。为了更清晰，如下
```
# 0. Download the models:
wget http://paddle-inference-dist.bj.bcebos.com/int8/QAT2_models/resnet50_quant.tar.gz
其他模型下载，更改文件名为 resnet101_quant.tar.gz, mobilenetv1_quant.tar.gz, mobilenetv2_quant.tar.gz, vgg16_quant.tar.gz, vgg19_quant.tar.gz 

# 1. Save QAT2.0 INT8 model
cd /PATH/TO/PADDLE/build
python ../python/paddle/fluid/contrib/slim/tests/save_qat_model.py --qat_model_path /PATH/TO/DOWNLOAD/MODEL/${QAT2_MODEL_NAME} --int8_model_save_path /PATH/TO/${QAT2_MODEL_NAME}_qat_int8

# 2. Run the QAT2.0 C-API for performance benchmark
cd /PATH/TO/PADDLE/build
OMP_NUM_THREADS=1 paddle/fluid/inference/tests/api/test_analyzer_qat_image_classification ARGS --enable_fp32=false --with_accuracy_layer=false --int8_model=/PATH/TO/${QAT2_MODEL_NAME}_qat_int8 --infer_data=$HOME/.cache/paddle/dataset/int8/download/int8_full_val.bin --batch_size=1 --paddle_num_threads=1
```
你可以在微信群里找我

**Comment by OliverLPH** [comment]
@lidanqing-intel 
好的，感谢
