### ISSUE TITLE
请问我如何可视化模型压缩后的模型结构？

### ISSUE THREAD

**Issue by hp-cuiwb** [PaddlePaddle/Paddle#21911]
有什么方式吗？

**Comment by yaoxuefeng6** [comment]
请参考下这个：https://github.com/PaddlePaddle/PaddleDetection/tree/release/0.1/slim/prune

**Comment by hp-cuiwb** [comment]
十分感谢，请问只有通道剪裁的可以可视化吗，量化的可以吗？

**Comment by yaoxuefeng6** [comment]
这个文档中的可视化可以作为一个通用的工具 量化的应该也可以的
