### ISSUE TITLE
急：Windows10安装，按照官网一步一步操作，CUDD10和cuDNN7.6.5(7.3.1也装过）等组件我都装了，python和pip版本也装了对应版本，安装过程很顺利没弹红字和错误，可在验证时总是没提示安装成功。

### ISSUE THREAD

**Issue by 18314452550** [PaddlePaddle/Paddle#21913]
1.	我遇到的问题：
Windows10安装，按照官网一步一步操作，CUDD10和cuDNN7.6.5(7.3.1也装过）等组件我都装了，python和pip版本也装了对应版本，安装过程很顺利没弹红字和错误，可在验证时总是没提示安装成功。
2.	版本、环境信息：
   1）windows10专业版，已经激活
   2)  PaddlePaddle版本：1.1
  3）GPU：CUDD10和cuDNN7.6.5（7.3.1装过，但是还是同样的问题，验证没安装成功） 
  4）pip：10.0.1
   5）系统环境：神舟，i5-4210双核处理器  GTX950M  4GB DDR3内存；Python3.7
-pip10.0.1：
6）pip安装：
验证提示代码如下：
 

Running Verify Fluid Program ...
2019-12-24 15:11:55,514-WARNING: You are using GPU version Paddle Fluid, But Your CUDA Device is not set properly
 Original Error is

--------------------------------------------
C++ Call Stacks (More useful to developers):
--------------------------------------------
Windows not support stack backtrace yet.

----------------------
Error Message Summary:
----------------------
Error: cudaGetDeviceCount failed in paddle::platform::GetCUDADeviceCountImpl, error code : 35, Please see detail in https://docs.nvidia.com/cuda/cuda-runtime-api/group__CUDART__TYPES.html#group__CUDART__TYPES_1g3f51e3575c2178246db0a94a430e0038 at (D:\1.6.2\paddle\paddle\fluid\platform\gpu_info.cc:67)

3.	备注：
cuDNN7.3.1装过，可是不行；在Paddle paddle交流群里问了技术员，技术员让换cuDNN7.6.5试试，还是不行。然后管理员让我在这提个问题。
请帮我处理一下安装问题并跟我说一下，急于到平台上调用模型训练，谢谢！
我的电话，李：18314452550.

**Comment by DDDivano** [comment]
看看 cmd下的 nvcc -V 显示什么？

**Comment by 18314452550** [comment]
C:\Users\89420>nvcc -V
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2018 NVIDIA Corporation
Built on Sat_Aug_25_21:08:04_Central_Daylight_Time_2018
Cuda compilation tools, release 10.0, V10.0.130

C:\Users\89420>python -V
Python 3.7.0

C:\Users\89420>pip -V
pip 10.0.1 from d:\python3.7\lib\site-packages\pip (python 3.7)

C:\Users\89420>

**Comment by DDDivano** [comment]
nvidia driver 版本号是？

**Comment by 18314452550** [comment]
可以的话，你可以直接通过QQ：894202593远控我电脑看一下。



C:\Users\89420&gt;nvcc -V
 nvcc: NVIDIA (R) Cuda compiler driver
 Copyright (c) 2005-2018 NVIDIA Corporation
 Built on Sat_Aug_25_21:08:04_Central_Daylight_Time_2018
 Cuda compilation tools, release 10.0, V10.0.130
 
C:\Users\89420&gt;python -V
 Python 3.7.0
 
C:\Users\89420&gt;pip -V
 pip 10.0.1 from d:\python3.7\lib\site-packages\pip (python 3.7)


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Divano"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月24日(星期二) 下午4:44
收件人:&nbsp;"PaddlePaddle/Paddle"<Paddle@noreply.github.com&gt;;
抄送:&nbsp;"李泽立"<894202593@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [PaddlePaddle/Paddle] 急：Windows10安装，按照官网一步一步操作，CUDD10和cuDNN7.6.5(7.3.1也装过等组件我都装了，并且安装过程很顺利没弹任何红字和错误，可在验证时总是没提示安装成功； (#21913)




看看 cmd下的 nvcc -V 显示什么？

**Comment by 18314452550** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Divano"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月24日(星期二) 下午4:55
收件人:&nbsp;"PaddlePaddle/Paddle"<Paddle@noreply.github.com&gt;;
抄送:&nbsp;"李泽立"<894202593@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [PaddlePaddle/Paddle] 急：Windows10安装，按照官网一步一步操作，CUDD10和cuDNN7.6.5(7.3.1也装过）等组件我都装了，python和pip版本也装了对应版本，安装过程很顺利没弹红字和错误，可在验证时总是没提示安装成功。 (#21913)




nvidia driver 版本号是？

**Comment by DDDivano** [comment]
经远程发现用户显卡驱动版本过低。
