### ISSUE TITLE
rank_cost 训练误差出现负数

### ISSUE THREAD

**Issue by fsfszongming256** [PaddlePaddle/Paddle#2194]
如题：
log截图：
![image](https://cloud.githubusercontent.com/assets/26397447/26187637/fee659de-3bcc-11e7-8684-9a76f5dc2a0d.png)

参考layers.py 对rank_cost的解释，似乎不应该出现负数？
C_{i,j} & = -\\tilde{P_{ij}} * o_{i,j} + log(1 + e^{o_{i,j}})

已经检查过训练数据的label，没有异常值

**Comment by qingqing01** [comment]
根据公式是会出现负值的吧， 论文[Learning to Rank using Gradient Descent](http://icml.cc/2015/wp-content/uploads/2015/06/icml_ranking.pdf)中的Figure 1是损失函数图。

**Comment by lcy-seso** [comment]
- 请问是在某个Batch 变成复数吗？
- 能不能去掉中间的统计信息，只留下在变成复数前后几行的log，看一下cost变化的趋势吗？

**Comment by fsfszongming256** [comment]
是在某个Batch变成负数的
cost变化趋势如下：
![image](https://cloud.githubusercontent.com/assets/26397447/26188607/c358e53e-3bd2-11e7-89a7-fecf05cd94c5.png)
