### ISSUE TITLE
请问能提供下剪枝的darknet-yolov3的yml配置文件吗？

### ISSUE THREAD

**Issue by hp-cuiwb** [PaddlePaddle/Paddle#21954]
修改了给的mobilenet yolov3的配置文件的pruned_params，一直报错，请问能提供下剪枝的darknet-yolov3的yml配置文件吗？

**Comment by FDInSky** [comment]
可以参考这个https://github.com/wanghaoshuang/PaddleDetection/tree/prune_yolo/slim/prune_coco

**Comment by wanghaoshuang** [comment]
hi， 建议您使用新的剪裁API，新的API用起来更灵活些。这里是一个使用示例：
https://github.com/wanghaoshuang/PaddleDetection/blob/prune_yolo/slim/prune_coco/train.py#L204-L251

建议先用这个分支，在1月初我们会发正式版本：https://github.com/wanghaoshuang/PaddleSlim/tree/prune
