### ISSUE TITLE
请问提交PR时，各种CI报错是为啥？

### ISSUE THREAD

**Issue by leesusu** [PaddlePaddle/Paddle#21957]
FTRL with sparse update.

**Comment by leesusu** [comment]
![image](https://user-images.githubusercontent.com/2424688/71476334-7d545f00-281f-11ea-9ff2-713b37ab8941.png)

想问下，这个是什么原因？是要在编译的时候，跑通ctest吗？

**Comment by iclementine** [comment]
> ![image](https://user-images.githubusercontent.com/2424688/71476334-7d545f00-281f-11ea-9ff2-713b37ab8941.png)
> 
> 想问下，这个是什么原因？是要在编译的时候，跑通ctest吗？

看不到这个图片，以及是需要跑通几个 CI 的 test。以及部分修改需要 approve。

**Comment by leesusu** [comment]
就是这个pr：
https://github.com/PaddlePaddle/Paddle/pull/21967

**Comment by iclementine** [comment]
你可以查看 build_log.

<img width="749" alt="图片" src="https://user-images.githubusercontent.com/16222986/71480408-dd550080-2833-11ea-9589-e92fae9d01af.png">

可以看到错误的类型。
其中有一个和 PaddleEnforce 的写法升级有关，可以参考 https://github.com/PaddlePaddle/Paddle/wiki/Paddle-Error-Message-Writing-Specification，
其他的具体看 build_log.

**Comment by leesusu** [comment]
build log在哪里看呢？那个是 ci.paddlepaddle.org 的后台吧？我应该看不到
我这边改动只有PADDLE_THROW，文案也是照着其他的op写的，看不出问题来。
@iclementine

**Comment by leesusu** [comment]
呼叫大佬，帮我看下 #21976 的2个CI的问题，我这里看不到细节，感谢 @iclementine

**Comment by iclementine** [comment]
好的。

其中一个和 Paddle Throw 的写法有关。
![Screenshot_2019-12-28 PaddlePRCI Compile PR_CI_CPU_Py2](https://user-images.githubusercontent.com/16222986/71538639-5c982080-2969-11ea-823a-3d583a26e8e8.png)


其中一个是单测的覆盖率不够。
![Screenshot_2019-12-28 Paddle PR_CI_Coverage #51224 (27 Dec 19 08 11) Diff Coverage — TeamCity](https://user-images.githubusercontent.com/16222986/71538644-60c43e00-2969-11ea-93de-f6027ba8a16c.png)

**Comment by leesusu** [comment]
@iclementine 帮忙再看下这2个啥问题，谢啦：

http://ci.paddlepaddle.org/viewLog.html?buildId=259284&buildTypeId=PaddleMac_MacPrCiPython35

http://ci.paddlepaddle.org/viewLog.html?buildId=259287&buildTypeId=Paddle_PrCiPython35

**Comment by iclementine** [comment]
第一个问题是和我们目前遇到的 scipy 版本依赖冲突的问题，我来重新跑一遍，看看问题是否已经修复了。

第二个是 
[Paddle_PR_CI_python35_50650.log](https://github.com/PaddlePaddle/Paddle/files/4015205/Paddle_PR_CI_python35_50650.log)

**Comment by leesusu** [comment]
@iclementine 感谢，之前的问题都已经解决了，我重新提了pr #22092 ，看能否review下🙏

**Comment by iclementine** [comment]
好的，谢谢！

**Comment by leesusu** [comment]
@iclementine 我向你 ijasmine@yeah.net 的邮箱发了封邮件，想交个朋友，望回复～
