### ISSUE TITLE
请问怎么设置全局的随机种子（random seed）保证模型100%可复现？

### ISSUE THREAD

**Issue by heygrain** [PaddlePaddle/Paddle#21963]
如题，这个应该不太涉及开发环境和硬件配置

**Comment by DDDivano** [comment]
设置 program的 random seed https://www.paddlepaddle.org.cn/documentation/docs/zh/api_cn/fluid_cn/Program_cn.html#random_seed ；
可能你还需要设置 numpy 的 numpy.random.seed()；
python 自带的random.seed()；
cudnn使用确定性算法 https://www.paddlepaddle.org.cn/documentation/docs/zh/flags/cudnn_cn.html#flags-cudnn-deterministic；
剩下的可能需要根据具体模型来分析，比如模型中本身带随机性的操作，例如dropout，reader shuffle， 梯度回传累加时候是否是原子加操作等等。

**Comment by heygrain** [comment]
好的，非常感谢，请问环境变量FLAGS_cudnn_deterministic是在每次运行前通过export命令设置吗，就
export FLAGS_cudnn_deterministic=True ?

**Comment by iclementine** [comment]
可以把 FLAGS_cudnn_deterministic=True 和训练命令写在一行，比如说 
```bash
FLAGS_cudnn_deterministic=True python train.py ...
```
这样就只对这个命令有效。

也可以单独写一句 `export FLAGS_cudnn_deterministic=True` 然后运行训练的命令，这样就对当前这个 shell 有效。

**Comment by heygrain** [comment]
ok，非常感谢仔细解答，我没有别的问题了，可以close了
