### ISSUE TITLE
请问fluid.layers.data是否支持稀疏矩阵传入

### ISSUE THREAD

**Issue by heygrain** [PaddlePaddle/Paddle#21973]
请问fluid.layers.data是否支持稀疏矩阵传入，比如
`A = fluid.layers.data(name='A', [None, None], dtype='float32')`
然后在feed的时候给A输入一个numpy/scipy的coo/csr形式的稀疏矩阵
`{'A': mat}`
这个支持吗？
然后如果支持上述稀疏矩阵输入的话，是否支持稀疏矩阵乘法，像pytorch里面的`spmm()`运算，或者tensorlow中的`sparse_tensor_dense_matmul()`运算。

如果不支持，有什么相关建议吗？是只能先用numpy的`toarray()`方法在cpu中将稀疏矩阵转换为普通矩阵再传给A吗？

**Comment by iclementine** [comment]
目前应该不支持的，可以使用 array.todense() 方法转换为 dense 再传。

https://docs.scipy.org/doc/scipy-0.19.0/reference/generated/scipy.sparse.csr_matrix.todense.html

**Comment by heygrain** [comment]
那可以考虑以后支持一下噢，挺常用的运算……torch和tf都有的

**Comment by iclementine** [comment]
我们会评估一下的哦～
