### ISSUE TITLE
训练时异常退出显存不释放

### ISSUE THREAD

**Issue by LiangYongAI** [PaddlePaddle/Paddle#21988]
1、	paddle在训练时如果因为异常原因退出，比如设置过大的batch size程序挂掉退出，但分配的显存然后存在，没有自动回收，用nvidia-smi查看显存信息，GPU-Util是0%，但显存没有释放，这个现象在linux下可以找到进程杀掉，但在windows下只能重启电脑。
![image](https://user-images.githubusercontent.com/15886620/71509856-bf38e000-28c7-11ea-9106-89fa2048304d.png)

**Comment by slf12** [comment]
现在这个问题还没有很好的办法解决。在windows上可以使用任务管理器杀掉进程，释放显存。

**Comment by slf12** [comment]
请问具体的异常情景是怎样的？方便我们对问题进行跟踪处理。
