### ISSUE TITLE
scatter_nd_add 返回 tensor 的 dtype 错误

### ISSUE THREAD

**Issue by AoZhang** [PaddlePaddle/Paddle#22000]
- 环境
   1）PaddlePaddle版本：1.6.2
   2）CPU：Intel(R) Xeon(R) CPU E5-2620 v2
   3）GPU：no
   4）系统环境：CentOS 6.3 ，Python版本 3.6.5

- 复现信息：
```
x = fluid.layers.data(name='x', shape=[3, 3], dtype='float32', append_batch_size=False)
index = fluid.layers.data(name='index', shape=[2, 2], dtype='int64', append_batch_size=False)
update = fluid.layers.data(name='update', shape=[2], dtype='float32', append_batch_size=False)

output = fluid.layers.scatter_nd_add(x, index, update)
print(output.dtype)
```

- 问题描述
print 输出的是 VarType.BOOL，正常不应该是 FP32 吗？但是我打印 output 的值发现是符合预期的。

**Comment by xixiaoyao** [comment]
@ForFishes 麻烦看一下，谢谢~

**Comment by ForFishes** [comment]
paddle1.6.2 没有cherry-pick 该pr：https://github.com/PaddlePaddle/Paddle/pull/21257
该问题之前已修复，请使用最新的develop分支。

**Comment by AoZhang** [comment]
> paddle1.6.2 没有cherry-pick 该pr：#21257
> 该问题之前已修复，请使用最新的develop分支。

请问这个修复会在那个版本 release，有预期的时间吗？

**Comment by xixiaoyao** [comment]
预期1.7版本会修复，大约2月下旬发布哈~
