### ISSUE TITLE
docstrings太多单词拼写错误

### ISSUE THREAD

**Issue by wudenggang** [PaddlePaddle/Paddle#22018]
编写小代码检查paddle docstring太多拼写错误，至少超过200个，估计大佬比较忙。
![image](https://user-images.githubusercontent.com/3587832/71584671-b148c080-2b4e-11ea-9b67-6889c5c20665.png)

**Comment by luotao1** [comment]
感谢您的指出，请问您的代码能贡献出来么？

**Comment by Boyan-Liu** [comment]
您好，感谢您的反馈，我们最近会集中解决，请问您的代码能贡献吗？

**Comment by wudenggang** [comment]
半手工python docstrings单词拼写工具——吴登刚，wudenggang@outlook.com
1、获取某个目录下所有以.py结尾的文件，通过ast解析语法树，获取docstrings。保存在records里(格式：文件名，docstrings开始行号，结尾行号，docstrings)，保存为records.pkl。并将docstrings里的标点去除拆分成字典保存，保存为word_freq.pkl。
2、针对字典每个词，确认是否拼写正常（有大量算法可用）。我采用最简单的，将字典里的单词复制到word文档中自动检查，获取可能拼写错误的单词，保存在（单词.txt）里。
3、反查相关单词在docstrings里的位置，这部分代码不在此电脑上，后续补上（代码也比较简单），保存到rst.pkl中（格式：单词，在docstrings里的位置，docstrings开始行号，结尾行号，docstrings）
[首先阅读文件.txt](https://github.com/PaddlePaddle/Paddle/files/4011477/default.txt)
[paddle-吴登刚.docx](https://github.com/PaddlePaddle/Paddle/files/4011478/paddle-.docx)



[单词.txt](https://github.com/PaddlePaddle/Paddle/files/4011479/default.txt)

python代码在getdoc.txt里面
[getdoc.txt](https://github.com/PaddlePaddle/Paddle/files/4011490/getdoc.txt)

**Comment by Boyan-Liu** [comment]
感谢您的反馈，我们近期统一修改！

**Comment by tianshuo78520a** [comment]
我们使用了您的脚本，在执行后的word文件里发现了一些并不属于Paddle代码里的单词，像是多个单词组合起来的。
例如：distributedoptimizer、mkldnnposttrainingquantstrategy、distributedoptimizer 
看起来像是在拆分单词时候发生了问题。

**Comment by wudenggang** [comment]
大佬，之前拆分单词比较粗糙。代码主要功能是获取所有的docstrings，单词差错功能其实还需要更好的方法。
