### ISSUE TITLE
可以吐槽下paddlepaddle么

### ISSUE THREAD

**Issue by aixier** [PaddlePaddle/Paddle#22038]
1、代码里面嵌套太复杂。导致水平一般的人只能运行demo本身，代码几乎无法修改。
2、实现功能涉及到的知识点太多，一般人很难上手。
归纳起来就是这个一个高手用的东西，不适合推广普及。
 但是高手做项目也不用paddlepaddle这就是矛盾

**Comment by yma-admin** [comment]
可以试试PaddleHub，看看能否满足需求。

**Comment by Aurelius84** [comment]
感谢您的意见反馈，可以使用下paddle目前最新版本1.6.2。我们也会在api封装、文档教程等方面进一步完善和优化，也非常欢迎您提出更多的用户体验方面的意见和建议。

**Comment by fivejjs** [comment]
感觉还不错啊。 如果抽象太搞， 看不到底层， 心慌慌啊。

**Comment by D-DanielYang** [comment]
> 1、代码里面嵌套太复杂。导致水平一般的人只能运行demo本身，代码几乎无法修改。
> 2、实现功能涉及到的知识点太多，一般人很难上手。
> 归纳起来就是这个一个高手用的东西，不适合推广普及。
> 但是高手做项目也不用paddlepaddle这就是矛盾

非常抱歉给您带来不好的使用体验，请问方便沟通一下具体是什么问题么？可以邮件联系我
grasswolfs@163.com
