### ISSUE TITLE
分组卷积报错

### ISSUE THREAD

**Issue by Anikily** [PaddlePaddle/Paddle#22033]
输入shape是(B, 1536, 60, 60)
卷积核3*3， 输出512
设置groups参数为1536，报错如下：
The number of output channels should be divided by groups.But received: the output channels is [512], the shape of filter is [512, 1, 3, 3](the first dimension of filter is output channel), the groups is [1536]

**Comment by Aurelius84** [comment]
请问使用的是conv2d这个api吗？分组卷积里的参数groups和输出channels须满足整除的关系，即output_channels / groups = 整数。

根据你的报错信息来看，是 512 / 1536，结果为小数，不满足整除关系。
