### ISSUE TITLE
Does PaddlePaddle have a demo of Pointer Network

### ISSUE THREAD

**Issue by AoZhang** [PaddlePaddle/Paddle#22041]
Do you have a demo of Pointer Network(like mentioned in [paper](https://arxiv.org/abs/1506.03134)). I can't find any similar ones in PaddleNLP models.

A similar issue is  #10851

**Comment by Aurelius84** [comment]
目前models里也有用到这个模型，只是没有单独的独立出来。可以参考阅读理解模型的实现，这里有一些Pointer Network的代码实现：https://github.com/PaddlePaddle/models/blob/f13e368145c1f65de995d74bc909f43cd8a3da9d/PaddleNLP/models/reading_comprehension/bidaf_model.py

**Comment by Pzoom522** [comment]
请问未来可否将其解耦为单独的摘要模型（pointer generator）？因为这是最常见的摘要baseline，可以极大地方便后续开发。谢谢！
