### ISSUE TITLE
something about the home page 

### ISSUE THREAD

**Issue by NHZlX** [PaddlePaddle/Paddle#2204]
For a newbie, the first thing should be how to install it, but i can not find the direct entrance to the instructions for installation on the home page. [paddle](http://paddlepaddle.org) . The "quick start", and "documents" links don't point  to the installation.

**Comment by NHZlX** [comment]
@llxxxll @wangkuiyi  paddle 支持多种方式安装， 个人感觉paddle 的主页还是没有给一个很友好的安装方式,   我认为caffe2的主页相对友好一些，主页的 get_start -> [install](https://caffe2.ai/docs/getting-started.html?platform=mac&configuration=compile) ,我们是不是可以借鉴一下？

**Comment by luotao1** [comment]
Paddle的主页，需要放上book, models, blog等的链接么？

**Comment by Yancey1989** [comment]
I'll close the inactivate issue, and feel free to reopen it.
