### ISSUE TITLE
组网时如何获取并使用模型参数的梯度？

### ISSUE THREAD

**Issue by XDUXK** [PaddlePaddle/Paddle#22076]
【paddle版本】：CPU 1.6
【机器环境】：MacOS + Python 3.7
【问题描述】：
请问paddle里面有没有方法能够：
1. 在组网时获取到模型参数梯度的Variable变量
2. 基于1中所述梯度的Variable变量和一个已有的梯度数据，定义二者的平方差作为损失loss
3. 通过更新输入数据x（比如更新一个随机输入的噪声图片），而不是网络模型的参数，来最小化2中所述的loss

谢谢！

**Comment by qingqing01** [comment]
[paddle.fluid.gradients](https://www.paddlepaddle.org.cn/documentation/docs/zh/api_cn/fluid_cn/gradients_cn.html#gradients)  可以获取输出对输入的梯度.

**Comment by XDUXK** [comment]
使用fluid.gradients(mean_diff_loss, dummy_x)在获取关于输入数据dummy_x的梯度（应该是二阶导）时有些问题，报下面的错，不知道是什么原因啊？谢谢
![image](https://user-images.githubusercontent.com/26429100/71877185-86b8c200-3163-11ea-8de9-45c00fb87d6c.png)
