### ISSUE TITLE
error when install 0.10 from source in mac

### ISSUE THREAD

**Issue by Superjom** [PaddlePaddle/Paddle#2207]
I tried to install paddle 0.10 from source code in mac.
I had installed protobuf and OpenBlas using brew, and then followed the official documents to compile the source code using CMake.

some error details are as followed, it seems that the cmake script can't detect the system's protobuf, and it failed to download protobuf into `../third_party` .

`
[ 71%] Building CXX object paddle/utils/tests/CMakeFiles/test_Error.dir/test_Error.cpp.o
[ 72%] Building CXX object paddle/utils/tests/CMakeFiles/test_StringUtils.dir/test_StringUtils.cpp.o
make[2]: *** No rule to make target `../third_party/install/protobuf/lib/libprotobuf.a', needed by `paddle/utils/tests/test_CustomStackTracePrint'.  Stop.
make[2]: *** Waiting for unfinished jobs....
make[2]: *** No rule to make target `../third_party/install/protobuf/lib/libprotobuf.a', needed by `paddle/utils/tests/test_SpinLock'.  Stop.
make[2]: *** Waiting for unfinished jobs....
[ 72%] Building CXX object paddle/utils/tests/CMakeFiles/test_CustomStackTracePrint.dir/test_CustomStackTracePrint.cpp.o
[ 72%] Building CXX object paddle/utils/tests/CMakeFiles/test_SpinLock.dir/test_SpinLock.cpp.o
make[1]: *** [paddle/utils/tests/CMakeFiles/test_Error.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
make[1]: *** [paddle/utils/tests/CMakeFiles/test_StringUtils.dir/all] Error 2
make[1]: *** [paddle/utils/tests/CMakeFiles/test_SpinLock.dir/all] Error 2
make[1]: *** [paddle/utils/tests/CMakeFiles/test_CustomStackTracePrint.dir/all] Error 2
make: *** [all] Error 2
`

**Comment by helinwang** [comment]
I think this should be fixed.
