### ISSUE TITLE
sequence_expand 问题

### ISSUE THREAD

**Issue by dongfangyixi** [PaddlePaddle/Paddle#22083]
遇到一个问题是，比如：
x 的 lod = [[0, 1, 2], [0, 5, 10]]
y 的 lod = [[0, 15, 25]]
要把x 的 lod expand成y的在ref level=0
就是 x 的 lod ==> [[0, 15, 25], [0, 5, 10]]
把y的lod expand成 x的 在ref level=1
就是y的lod ==> [[0, 15, 25], [0, 5, 10]]
但是
x = fluid.layers.sequence_expand(x, y, ref_level=0)
报错
x不支持 lod level = 2
y = fluid.layers.sequence_expand(y, x, ref_level=1)
y并没有 expand lod没变。
有什么好办法吗？

**Comment by luotao1** [comment]
1. 第一个问题：x 的 lod expand成y，但报错是x不支持 lod level = 2，sequence_expand确实不支持x的lod level=2。 请见：https://www.paddlepaddle.org.cn/documentation/docs/zh/api_cn/layers_cn/sequence_expand_cn.html#cn-api-fluid-layers-sequence-expand
`x (Variable) - 输入变量，维度为 [M,K] ，lod level至多1的二维Tensor或LoDTensor。数据类型支持int32，int64，float32或float64。`
2. 第二个问题：y的lod expand成 x，y的lod ==> [[0, 15, 25], [0, 5, 10]]，这个lod写法是错的。请问你想转成什么样的呢？

**Comment by dongfangyixi** [comment]
@luotao1

**Comment by dongfangyixi** [comment]
@luotao1

**Comment by dongfangyixi** [comment]
@luotao1 
感谢回复
之前 lod 表述的有问题，抱歉，重新表述一下
是这样的 比如
x 的 lod = [[0, 1, 2], [0, 5, 10]]
y 的 lod = [[0, 2, 5]]
要把x 的 lod expand成y的在ref level=0
就是 x 的 lod ==> [[0, 2, 5], [0, 5, 10, 15, 20, 25]]
把y的lod expand成 x的 在ref level=1
就是y的lod ==> [[0, 2, 5], [0, 5, 10, 15, 20, 25]]
但是
x = fluid.layers.sequence_expand(x, y, ref_level=0)
报错
x不支持 lod level = 2
y = fluid.layers.sequence_expand(y, x, ref_level=1)
y并没有 expand lod没变。
总体上是希望x 在 ref level 0上 根据y的lod 复制。举个例子就是： 假如 x = [[[1,1,1,1,1]], [[2,2,2,2,2]]] 希望变成 x = [[[1,1,1,1,1], [1,1,1,1,1]], [[2,2,2,2,2], [2,2,2,2,2], [2,2,2,2,2,2]]] 这样
对于y也是，只不过是在ref level 1 上根据x的 lod 复制，假如 y = [[1, 2],[3, 4, 5]], 可以变成 y=[[[1,1,1,1,1], [2,2,2,2,2]], [[3,3,3,3,3], [4,4,4,4,4], [5,5,5,5,5]]]
根据您的回复，1 的问题是没有办法绕过去的吗？比如说有没有可能while loop或者 flatten什么的？
2 您再辛苦看看，不知道我的意思是否表述清楚。

**Comment by luotao1** [comment]
> 1 的问题是没有办法绕过去的吗？比如说有没有可能while loop或者 flatten什么的？
2 您再辛苦看看，不知道我的意思是否表述清楚。

@xyzhou-puck 请帮忙看下，非常感谢！

**Comment by xyzhou-puck** [comment]
您好，

1. sequence_expand目前还不支持lod=2的情况，可以通过set_lod（https://www.paddlepaddle.org.cn/documentation/docs/zh/api_cn/fluid_cn/LoDTensor_cn.html#lodtensor）重新设置这个tensor的lod信息，使之变成一个lod=1的lod tensor，只要保证排列是正确的即可。

2.  假如 x = [[[1,1,1,1,1]], [[2,2,2,2,2]]] 希望变成 x = [[[1,1,1,1,1], [1,1,1,1,1]], [[2,2,2,2,2], [2,2,2,2,2], [2,2,2,2,2,2]]] ，目前这个搞不定，因为最后一个是6个2，而不是5个2，如果是5个2，可以把y的lod设置为：[[2, 3]]。
