### ISSUE TITLE
FAQ problem  ：The solution to  “CUDA driver version is insufficient for CUDA runtime version”

### ISSUE THREAD

**Issue by NHZlX** [PaddlePaddle/Paddle#2208]
The 'cuda ' problem may occur when running the paddle  on the docker, #598  and  ['FAQ'](http://www.paddlepaddle.org/doc_cn/faq/index_cn.html#docker-gpu-cuda-driver-version-is-insufficient) has given the answer.  But current docker images of paddle provide cuda8.0 environment.  If the machine is installed cuda7.5 or other earlier versions, the above solution will not work.

**Comment by hedaoyuan** [comment]
The machine needs to update the cuda driver.
