### ISSUE TITLE
Propeller

### ISSUE THREAD

**Issue by leonleeldc** [PaddlePaddle/Paddle#22093]
I am trying to make use of propeller to do the logging for the model training. But my following code return None. Not sure why. I tried to get the original code which is part of ERNIE work. I got None too. 
   
    update_Wall_op = fluid.layers.assign(Wall_clock_time, time_diff)
    loss_summaries = [
        summary.scalar('loss/discriminator', d_loss),
        summary.scalar('loss/g_loss', g_loss),
        summary.scalar('loss/log_pg', log_pg),
        summary.scalar('loss/Wall_clock_time', Wall_clock_time),
        summary.scalar('loss/temperature', temperature)
    ]
    #loss_summary_op = fluid.layers.stack(loss_summaries)
    loss_summary_op = loss_summaries

May you do some help?
Thanks in advance,

**Comment by guoshengCS** [comment]
Sorry, I am not so clear with the question. If it means that log can not work correctly, will some logging setting like `logging.getLogger().setLevel(logging.INFO)` help, maybe some dependencies use `logging.basicConfig()`  which would just be called once and ignore your call again.

**Comment by leonleeldc** [comment]
Ok, I just found out this propeller to be quite similar to the tensorflow counterpart. We can simply replace tf with paddle quickly for it. It claims to be working well in paddlepaddle. If not working yet, I can manage to get by with common logging as well. Hope that this propeller will be workable soon. 
https://github.com/PaddlePaddle/ERNIE/tree/develop/propeller

Thanks,

**Comment by Meiyim** [comment]
hi, @leonleeldc 

`propeller` is not part of PaddlePaddle ecosystem, we are working on it though.

`summary.scalar` returns None, so you can't stack the result. also there is no 'summary_op' in Paddle.
if you want to log a tensor(scalar value or historgram), simply mark the tensor with `summary.scalar` or `summary.histogram`.  propeller will record the tensor and do the logging for you.

you can change your code to:
```python
    summary.scalar('loss/discriminator', d_loss),
    summary.scalar('loss/g_loss', g_loss),
    summary.scalar('loss/log_pg', log_pg),
    summary.scalar('loss/Wall_clock_time', Wall_clock_time),
    summary.scalar('loss/temperature', temperature)
```
