### ISSUE TITLE
Implement scripts to calculate the number of parameters, GPU memory usage, MAdd and FLOPs

### ISSUE THREAD

**Issue by shdyn** [PaddlePaddle/Paddle#22103]
Hi, I cannot find any scripts to implement the above functions. Can you guys please consider to implement the scripts? Thanks.

**Comment by gongweibao** [comment]
Memory usage:https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/fluid/contrib/memory_usage_calc.py

Number of  parameters & MAdd & FLOPs: https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/fluid/contrib/model_stat.py
