### ISSUE TITLE
如何自定义损失函数

### ISSUE THREAD

**Issue by wbchief** [PaddlePaddle/Paddle#22116]
Thank you for contributing to PaddlePaddle. Submitting an issue is a great help for us.
Both Chinese and English issues are welcome.

It's hard to solve a problem when important details are missing.
Before submitting the issue, look over the following criteria before handing your request in.

- [ ] Was there a similar issue submitted or resolved before ? You could search issue in the github.
- [ ] Did you retrieve your issue from widespread search engines ?
- [ ] Is my description of the issue clear enough to reproduce this problem?
   * If some errors occurred, we need details about `how do you run your code?`, `what system do you use?`, `Are you using GPU or not?`, etc.
   * If you use an recording [asciinema](https://asciinema.org/) to show what you are doing to make it happen, that's awesome! We could help you solve the problem more quickly.
- [ ] Is my description of the issue use the github markdown correctly?
   * Please use the proper markdown syntaxes for styling all forms of writing, e.g, source code, error information, etc.
   * Check out [this page](https://guides.github.com/features/mastering-markdown/) to find out much more about markdown.

**Comment by guoshengCS** [comment]
如果这个自定义的损失函数可以使用其他OP组合试下的话，可以直接组合实现。无法组合实现的话Paddle目前支持下面的在框架外自定义OP的方法，可以参照实现需要的损失函数
https://www.paddlepaddle.org.cn/documentation/docs/zh/advanced_usage/development/new_op/new_python_op.html#python-op
https://www.paddlepaddle.org.cn/documentation/docs/zh/advanced_usage/development/new_op/custom_op.html#c-op
