### ISSUE TITLE
Paddle Tensorrt 问题

### ISSUE THREAD

**Issue by zjutlzt** [PaddlePaddle/Paddle#22119]
Paddle Tensorrt 问题

在进行PaddleTensorrt测试得时候  
导出模型   FasterRCNNTestFeed.image_shape=[3,800,800]
尺寸800是可以运得

但是 尺寸 任何一边大于800 就会报错  并且没有错误提示

2.是否有模型加密得建议或者方案??

**Comment by guoshengCS** [comment]
1.  > 尺寸 任何一边大于800 就会报错 

咨询了下 @jerrywgz 感谢，现在tensorrt的shape必须和导出模型的shape一致才行，需要tensorrt6才支持变长输入，这个还在支持中

2. 模型加密的话可以看下这种内存load是否满足需求 #14734 ，使用示例见这里 https://github.com/luotao1/Paddle/blob/743cb840f1235911d163eb4927161cbfc0e803b5/paddle/fluid/inference/tests/api/analyzer_ner_tester.cc#L97

**Comment by zjutlzt** [comment]
您好,感谢 回答,  加密的问题看到了  非常感谢

但是 我在 使用PaddleTRT时(用TRT6.0 重新编译了一次)     export 模型   设置FasterRCNNTestFeed.image_shape=[3,800,800]
的时候   模型可以正常运行  


但是按照   export 模型   设置FasterRCNNTestFeed.image_shape=[3,800,1600]
的时候 程序 直接闪退  
I0108 13:06:21.040693  6417 analysis_predictor.cc:471] ======= optimize end =======
I0108 13:06:21.041179  6417 naive_executor.cc:105] ---  skip [feed], feed -> im_shape
I0108 13:06:21.041188  6417 naive_executor.cc:105] ---  skip [feed], feed -> im_info
I0108 13:06:21.041208  6417 naive_executor.cc:105] ---  skip [feed], feed -> image
I0108 13:06:21.042585  6417 naive_executor.cc:105] ---  skip [save_infer_model/scale_0], fetch -> fetch
段错误 (核心已转储)

没任何提示? 请问是什么情况?

**Comment by zjutlzt** [comment]
> 1. > 尺寸 任何一边大于800 就会报错
> 
> 咨询了下 @jerrywgz 感谢，现在tensorrt的shape必须和导出模型的shape一致才行，需要tensorrt6才支持变长输入，这个还在支持中
> 
> 1. 模型加密的话可以看下这种内存load是否满足需求 #14734 ，使用示例见这里 https://github.com/luotao1/Paddle/blob/743cb840f1235911d163eb4927161cbfc0e803b5/paddle/fluid/inference/tests/api/analyzer_ner_tester.cc#L97

**Comment by 1224wxwx** [comment]
@guoshengCS 请问现在支持用tensorRT6或更高的版本，来支持变长输入了吗
