### ISSUE TITLE
多分类focal loss 报错

### ISSUE THREAD

**Issue by dxc0ap** [PaddlePaddle/Paddle#22128]
PaddlePaddle版本：1.6   
- 训练信息
    1）单机单卡
    2）显存信息
    3）Operator信息
报错信息
Traceback (most recent call last):
  File "run_classifier.py", line 403, in <module>
    main(args)
  File "run_classifier.py", line 114, in main
    is_regression=args.is_regression)
  File "/ssd2/xiangjing/beta/ERNIE_2.0/finetune/classifier.py", line 110, in create_model
    x=logits, label=labels, fg_num=fg_num, gamma=2., alpha=0.25)
  File "/home/users/xiangjing/opt/mms-hpc-devel-pd-gpu-97/lib/python2.7/site-packages/paddle/fluid/layers/detection.py", line 436, in sigmoid_focal_loss
    outputs={"Out": out})
  File "/home/users/xiangjing/opt/mms-hpc-devel-pd-gpu-97/lib/python2.7/site-packages/paddle/fluid/layer_helper.py", line 43, in append_op
    return self.main_program.current_block().append_op(*args, **kwargs)
  File "/home/users/xiangjing/opt/mms-hpc-devel-pd-gpu-97/lib/python2.7/site-packages/paddle/fluid/framework.py", line 1780, in append_op
    attrs=kwargs.get("attrs", None))
  File "/home/users/xiangjing/opt/mms-hpc-devel-pd-gpu-97/lib/python2.7/site-packages/paddle/fluid/framework.py", line 1173, in __init__
    self.desc.infer_shape(self.block.desc)
paddle.fluid.core_avx.EnforceNotMet: Invoke operator sigmoid_focal_loss error.
Python Call stacks:
  File "/home/users/xiangjing/opt/mms-hpc-devel-pd-gpu-97/lib/python2.7/site-packages/paddle/fluid/framework.py", line 1780, in append_op
    attrs=kwargs.get("attrs", None))
  File "/home/users/xiangjing/opt/mms-hpc-devel-pd-gpu-97/lib/python2.7/site-packages/paddle/fluid/layer_helper.py", line 43, in append_op
    return self.main_program.current_block().append_op(*args, **kwargs)
  File "/home/users/xiangjing/opt/mms-hpc-devel-pd-gpu-97/lib/python2.7/site-packages/paddle/fluid/layers/detection.py", line 436, in sigmoid_focal_loss
    outputs={"Out": out})
  File "/ssd2/xiangjing/beta/ERNIE_2.0/finetune/classifier.py", line 110, in create_model
    x=logits, label=labels, fg_num=fg_num, gamma=2., alpha=0.25)
  File "run_classifier.py", line 114, in main
    is_regression=args.is_regression)
  File "run_classifier.py", line 403, in <module>
    main(args)
C++ Call stacks:
Enforce failed. Expected fg_dims.size() == 1, but received fg_dims.size():2 != 1:1.

代码信息：
finetune/classifier.py
将 softmax_with_cross_entropy 改为 函数 fluid.layers.sigmoid_focal_loss，按照帮助文档http://www.caihongshenghuo.com/documentation/docs/zh/1.6/api_cn/layers_cn/sigmoid_focal_loss_cn.html 的写法，报错如上。
fg_num = fluid.layers.data(name='fg_num', shape=[1], dtype='int32')
focal_loss, probs = fluid.layers.sigmoid_focal_loss(x=logits, label=labels, fg_num=fg_num, gamma=2., alpha=0.25)

**Comment by guoshengCS** [comment]
`fg_num = fluid.layers.data(name='fg_num', shape=[1], dtype='int32')` 会自动的添加一个batch_size的维度，得到的shape会是`[-1, 1]`，而sigmoid_focal_loss要求fg_num是一维的，可以试下加上`append_batch_size=False`或者新的[`fluid.data`](https://www.paddlepaddle.org.cn/documentation/docs/zh/api_cn/fluid_cn/data_cn.html#data)接口

**Comment by dxc0ap** [comment]
多谢 guoshengCS，这个问题解决了，接着又出现一个问题，烦请帮忙解答。

代码：
focal_loss, probs = fluid.layers.sigmoid_focal_loss(x=logits, label=labels, fg_num=fg_num, gamma=2., alpha=0.25)
报错：
valueError: too many values to unpack

由于是多标签问题，这里 logits是一个 26 维的 tensor，如下图所示：
logits
name: "fc_73.tmp_1"
type {
  type: LOD_TENSOR
  lod_tensor {
    tensor {
      data_type: FP32
      dims: -1
      dims: 26
    }
    lod_level: 0
  }
}
persistable: false

label 是一维的向量，如下所示：
labels
name: "read_file_0.tmp_5"
type {
  type: LOD_TENSOR
  lod_tensor {
    tensor {
      data_type: INT64
      dims: -1
      dims: 1
    }
    lod_level: 0
  }
}
persistable: false

**Comment by guoshengCS** [comment]
sigmoid_focal_loss的返回值只有一个loss，这里多了一个
`focal_loss, probs = fluid.layers.sigmoid_focal_loss(x=logits, label=labels, fg_num=fg_num, gamma=2., alpha=0.25)`

**Comment by dxc0ap** [comment]
多谢 guoshengCS，还有两个问题想要请教：
1. 因为 sigmoid_focal_loss 不返回预测值，所以我有什么办法能算准确率吗？类似于：
 accuracy = fluid.layers.accuracy(input=probs, label=labels, total=num_seqs)

2. 
代码：
fg_num = fluid.data(name='fg_num', shape=[1], dtype='int32')
focal_loss = fluid.layers.sigmoid_focal_loss(x=logits, label=labels, fg_num=fg_num, gamma=2., alpha=0.25)

报错为：
W0107 17:04:44.223543 89860 device_context.cc:236] Please NOTE: device: 0, CUDA Capability: 70, Driver API Version: 9.2, Runtime API Version: 9.0
W0107 17:04:44.228621 89860 device_context.cc:244] device: 0, cuDNN Version: 7.4.
Load pretraining parameters from /home/users/xiangjing/beta/ERNIE_2.0/ERNIE/params_base.
I0107 17:04:46.554039 89860 parallel_executor.cc:421] The number of CUDAPlace, which is used in ParallelExecutor, is 1. And the Program will be copied 1 copies
I0107 17:04:46.655093 89860 build_strategy.cc:363] SeqOnlyAllReduceOps:0, num_trainers:1
I0107 17:04:46.811445 89860 parallel_executor.cc:285] Inplace strategy is enabled, when build_strategy.enable_inplace = True
I0107 17:04:46.903571 89860 parallel_executor.cc:368] Garbage collection strategy is enabled, when FLAGS_eager_delete_tensor_gb = 0
/home/users/xiangjing/opt/xdevel/lib/python2.7/site-packages/paddle/fluid/executor.py:779: UserWarning: The following exception is not an EOF exception.
  "The following exception is not an EOF exception.")
Traceback (most recent call last):
  File "run_classifier.py", line 403, in <module>
    main(args)
  File "run_classifier.py", line 221, in main
    train_exe.run(fetch_list=[])
  File "/home/users/xiangjing/opt/xdevel/lib/python2.7/site-packages/paddle/fluid/parallel_executor.py", line 311, in run
    return_numpy=return_numpy)
  File "/home/users/xiangjing/opt/xdevel/lib/python2.7/site-packages/paddle/fluid/executor.py", line 780, in run
    six.reraise(*sys.exc_info())
  File "/home/users/xiangjing/opt/xdevel/lib/python2.7/site-packages/paddle/fluid/executor.py", line 775, in run
    use_program_cache=use_program_cache)
  File "/home/users/xiangjing/opt/xdevel/lib/python2.7/site-packages/paddle/fluid/executor.py", line 834, in _run_impl
    return_numpy=return_numpy)
  File "/home/users/xiangjing/opt/xdevel/lib/python2.7/site-packages/paddle/fluid/executor.py", line 674, in _run_parallel
    tensors = exe.run(fetch_var_names)._move_to_list()
paddle.fluid.core_avx.EnforceNotMet:

--------------------------------------------
C++ Call Stacks (More useful to developers):
--------------------------------------------
0   std::string paddle::platform::GetTraceBackString<std::string const&>(std::string const&, char const*, int)
1   paddle::platform::EnforceNotMet::EnforceNotMet(std::string const&, char const*, int)
2   paddle::framework::Tensor::check_memory_size() const
3   int const* paddle::framework::Tensor::data<int>() const
4   paddle::operators::GPUSigmoidFocalLossKernel<paddle::platform::CUDADeviceContext, float>::Compute(paddle::framework::ExecutionContext const&) const
5   std::_Function_handler<void (paddle::framework::ExecutionContext const&), paddle::framework::OpKernelRegistrarFunctor<paddle::platform::CUDAPlace, false, 0ul, paddle::operators::GPUSigmoidFocalLossKernel<paddle::platform::CUDADeviceContext, float>, paddle::operators::GPUSigmoidFocalLossKernel<paddle::platform::CUDADeviceContext, double> >::operator()(char const*, char const*, int) const::{lambda(paddle::framework::ExecutionContext const&)#1}>::_M_invoke(std::_Any_data const&, paddle::framework::ExecutionContext const&)
6   paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, paddle::platform::Place const&, paddle::framework::RuntimeContext*) const
7   paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, paddle::platform::Place const&) const
8   paddle::framework::OperatorBase::Run(paddle::framework::Scope const&, paddle::platform::Place const&)
9   paddle::framework::details::ComputationOpHandle::RunImpl()
10  paddle::framework::details::FastThreadedSSAGraphExecutor::RunOpSync(paddle::framework::details::OpHandleBase*)
11  paddle::framework::details::FastThreadedSSAGraphExecutor::RunOp(paddle::framework::details::OpHandleBase*, std::shared_ptr<paddle::framework::BlockingQueue<unsigned long> > const&, unsigned long*)
12  std::_Function_handler<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> (), std::__future_base::_Task_setter<std::unique_ptr<std::__future_base::_Result<void>, std::__future_base::_Result_base::_Deleter>, void> >::_M_invoke(std::_Any_data const&)
13  std::__future_base::_State_base::_M_do_set(std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> ()>&, bool&)
14  ThreadPool::ThreadPool(unsigned long)::{lambda()#1}::operator()() const

------------------------------------------
Python Call Stacks (More useful to users):
------------------------------------------
  File "/home/users/xiangjing/opt/xdevel/lib/python2.7/site-packages/paddle/fluid/framework.py", line 2488, in append_op
    attrs=kwargs.get("attrs", None))
  File "/home/users/xiangjing/opt/xdevel/lib/python2.7/site-packages/paddle/fluid/layer_helper.py", line 43, in append_op
    return self.main_program.current_block().append_op(*args, **kwargs)
  File "/home/users/xiangjing/opt/xdevel/lib/python2.7/site-packages/paddle/fluid/layers/detection.py", line 511, in sigmoid_focal_loss
    outputs={"Out": out})
  File "/ssd2/xiangjing/beta/ERNIE_2.0/finetune/classifier.py", line 110, in create_model
    label=labels, fg_num=fg_num, gamma=2., alpha=0.25)
  File "run_classifier.py", line 114, in main
    is_regression=args.is_regression)
  File "run_classifier.py", line 403, in <module>
    main(args)

----------------------
Error Message Summary:
----------------------
Error: Tensor holds no memory. Call Tensor::mutable_data first.
  [Hint: holder_ should not be null.] at (/paddle/paddle/fluid/framework/tensor.cc:23)
  [operator < sigmoid_focal_loss > error]

**Comment by guoshengCS** [comment]
1.  有logits的话应该可以根据自己的需要再使用sigmoid等OP得到需要的probs

2. 可以检查确认下sigmoid_focal_loss的输入是否有未赋值的，可以试下使用[fluid.layers.Print](https://www.paddlepaddle.org.cn/documentation/docs/zh/api_cn/layers_cn/Print_cn.html#print)看下哪个打印不出来。

**Comment by dxc0ap** [comment]
代码：
focal_loss = fluid.layers.sigmoid_focal_loss(x=logits, label=labels, fg_num=fg_num, gamma=2., alpha=0.25)

其中 logits 为：
Tensor[fc_73.tmp_1]
	shape: [32,26,]
	dtype: f
	data: 0.73672,0.298391,-0.372229,-0.0389988,0.13084,-0.879335,0.507872,-0.0871518,-0.131122,0.0390038,-0.137695,-0.0973293,-0.235243,-0.0571862,-0.664409,0.960643,0.899028,-0.0418494,0.881592,-1.14847,
labels 为：
tensor[read_file_0.tmp_5]
	shape: [32,1,]
	dtype: l
	data: 5,1,24,2,6,3,1,14,0,2,1,3,1,0,25,1,4,15,25,4,
fg_num 为：
tensor[fill_constant_0.tmp_0]
	shape: [1,]
	dtype: l
	data: 26,

与http://www.caihongshenghuo.com/documentation/docs/zh/1.6/api_cn/layers_cn/sigmoid_focal_loss_cn.html 中参数要求吻合

报错：
--------------------------------------------
C++ Call Stacks (More useful to developers):
--------------------------------------------
0   std::string paddle::platform::GetTraceBackString<char const*>(char const*&&, char const*, int)
1   paddle::platform::EnforceNotMet::EnforceNotMet(std::__exception_ptr::exception_ptr, char const*, int)
2   int const* paddle::framework::Tensor::data<int>() const
3   paddle::operators::GPUSigmoidFocalLossKernel<paddle::platform::CUDADeviceContext, float>::Compute(paddle::framework::ExecutionContext const&) const
4   std::_Function_handler<void (paddle::framework::ExecutionContext const&), paddle::framework::OpKernelRegistrarFunctor<paddle::platform::CUDAPlace, false, 0ul, paddle::operators::GPUSigmoidFocalLossKernel<paddle::platform::CUDADeviceContext, float>, paddle::operators::GPUSigmoidFocalLossKernel<paddle::platform::CUDADeviceContext, double> >::operator()(char const*, char const*, int) const::{lambda(paddle::framework::ExecutionContext const&)#1}>::_M_invoke(std::_Any_data const&, paddle::framework::ExecutionContext const&)
5   paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, paddle::platform::Place const&, paddle::framework::RuntimeContext*) const
6   paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, paddle::platform::Place const&) const
7   paddle::framework::OperatorBase::Run(paddle::framework::Scope const&, paddle::platform::Place const&)
8   paddle::framework::details::ComputationOpHandle::RunImpl()
9   paddle::framework::details::FastThreadedSSAGraphExecutor::RunOpSync(paddle::framework::details::OpHandleBase*)
10  paddle::framework::details::FastThreadedSSAGraphExecutor::RunOp(paddle::framework::details::OpHandleBase*, std::shared_ptr<paddle::framework::BlockingQueue<unsigned long> > const&, unsigned long*)
11  std::_Function_handler<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> (), std::__future_base::_Task_setter<std::unique_ptr<std::__future_base::_Result<void>, std::__future_base::_Result_base::_Deleter>, void> >::_M_invoke(std::_Any_data const&)
12  std::__future_base::_State_base::_M_do_set(std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> ()>&, bool&)
13  ThreadPool::ThreadPool(unsigned long)::{lambda()#1}::operator()() const

------------------------------------------
Python Call Stacks (More useful to users):
------------------------------------------
  File "/home/users/xiangjing/opt/xdevel/lib/python2.7/site-packages/paddle/fluid/framework.py", line 2488, in append_op
    attrs=kwargs.get("attrs", None))
  File "/home/users/xiangjing/opt/xdevel/lib/python2.7/site-packages/paddle/fluid/layer_helper.py", line 43, in append_op
    return self.main_program.current_block().append_op(*args, **kwargs)
  File "/home/users/xiangjing/opt/xdevel/lib/python2.7/site-packages/paddle/fluid/layers/detection.py", line 511, in sigmoid_focal_loss
    outputs={"Out": out})
  File "/ssd2/xiangjing/beta/ERNIE_2.0/finetune/classifier.py", line 127, in create_model
    label=labels, fg_num=fg_num, gamma=2., alpha=0.25)
  File "run_classifier.py", line 114, in main
    is_regression=args.is_regression)
  File "run_classifier.py", line 403, in <module>
    main(args)

----------------------
Error Message Summary:
----------------------
Error: Tensor holds the wrong type, it holds int64_t, but desires to be int at (/paddle/paddle/fluid/framework/tensor_impl.h:30)
  [operator < sigmoid_focal_loss > error]

**Comment by guoshengCS** [comment]
可能是fg_num的数据类型错了，看这里打印的是l(int64)，
```
tensor[fill_constant_0.tmp_0]
shape: [1,]
dtype: l
data: 26,
```
但按照报错说明里看，这里需要是int32的 `Tensor holds the wrong type, it holds int64_t, but desires to be int `

**Comment by dxc0ap** [comment]
代码中的确定义了 dtype='int32'，

fg_num = fluid.layers.fill_constant(shape=[1], value=26, dtype='int32')
focal_loss = fluid.layers.sigmoid_focal_loss(x=logits, label=labels, fg_num=fg_num, gamma=2., alpha=0.25)

错误还是如上。。。

**Comment by guoshengCS** [comment]
可以确认下整个过程中是否fg_num发生了改变，在`fg_num = fluid.layers.fill_constant(shape=[1], value=26, dtype='int32')`后打印下，在`fluid.layers.sigmoid_focal_loss `前打印下
