### ISSUE TITLE
topk op 不回传梯度

### ISSUE THREAD

**Issue by Meiyim** [PaddlePaddle/Paddle#22138]
dev 版本topk op 不回传梯度:
https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/fluid/layers/nn.py#L4740

gather/gather_nd目前都可以传梯度了，topk啥时候也更新一下?

**Comment by guoshengCS** [comment]
目前topk op没有实现对应的反向OP，所以暂时还不能传梯度

**Comment by Meiyim** [comment]
给加个TODO呗

**Comment by bjjwwang** [comment]
已经写完代码了 还在测试当中

**Comment by Meiyim** [comment]
这个问题有更新么，有相关PR可以看么

**Comment by guoshengCS** [comment]
这个已经支持了 https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/fluid/operators/top_k_op.cu#L105
