### ISSUE TITLE
新优化器讨论：Group-Sparsity-Regularized FTRL (G-FTRL)

### ISSUE THREAD

**Issue by leesusu** [PaddlePaddle/Paddle#22131]
我们这边初步的需求是：

FTRL的稀疏性是作用在模型的每个权重上的，粒度较细，对于embedding，每一行特征是一个整体，所以希望产生的稀疏解能作用在一整行上。

为此我们调研了近期facebook的论文：
《[Feature Selection for Facebook Feed Ranking System via a Group-Sparsity-Regularized Training Algorithm](https://research.fb.com/publications/feature-selection-for-facebook-feed-ranking-system-via-a-group-sparsity-regularized-training-algorithm/)》

大致的思想如下：
![image](https://user-images.githubusercontent.com/2424688/71870635-a8a94900-3151-11ea-8226-955b61e0e264.png)

图1、2是论文里的想法，对于nn模型的w，按行或者按列稀疏化，图3是我们这边的拓展，对于embedding，也可以按行进行稀疏化。

因此，我们希望实现G-FTRL优化器，并希望能得到PaddlePaddle社区的宝贵建议。如果可行，我这边会负责跟进编码并提交pr，感谢。

**Comment by leesusu** [comment]
@iclementine 飞宇要不你来瞅瞅，稀疏更新的ftrl也是你review的🤦‍♂️

**Comment by guoshengCS** [comment]
欢迎贡献，可行性还需我们这边确认下，提交PR后，我们这边会及时跟进review。

**Comment by leesusu** [comment]
@guoshengCS 👍感谢

**Comment by leesusu** [comment]
@guoshengCS 帮忙看下这2个CI的问题🙏，具体一些有截图或者log最好，我这边无法登录ci.paddlepaddle.org：

http://ci.paddlepaddle.org/viewLog.html?buildId=268302&buildTypeId=YYTest_PrCiCpuPy2

http://ci.paddlepaddle.org/viewLog.html?buildId=268833&buildTypeId=Paddle_PrCiCoverage

**Comment by iclementine** [comment]
谢谢！
[Compile_PR_CI_CPU_Py2_52197.log](https://github.com/PaddlePaddle/Paddle/files/4051957/Compile_PR_CI_CPU_Py2_52197.log)
[Paddle_PR_CI_Coverage_52008.log](https://github.com/PaddlePaddle/Paddle/files/4051956/Paddle_PR_CI_Coverage_52008.log)
这是目前的两个 log ，你先看一下吧。我重新触发测试了。

**Comment by leesusu** [comment]
@iclementine 

http://ci.paddlepaddle.org/viewLog.html?buildId=268833&buildTypeId=Paddle_PrCiCoverage

**Comment by leesusu** [comment]
@iclementine 


http://ci.paddlepaddle.org/viewLog.html?buildId=268833&buildTypeId=Paddle_PrCiCoverage
**覆盖度**的这个，看不出什么来，build和test的信息，test有个lite_resnet50_test出错，应该和我的修改没什么关系。**帮忙再看下有没有其他信息**。


http://ci.paddlepaddle.org/viewLog.html?buildId=268302&buildTypeId=YYTest_PrCiCpuPy2
这个我看到如下信息：

**0.** You must have one RD (XiaoguangHu01 or lanxianghit) and one TPM (saxon-zh or Boyan-Liu or swtkiwi) approval for the api change for the management reason of API interface.
**1.** You must have one TPM (saxon-zh or Boyan-Liu or swtkiwi) approval for the api change for the management reason of API document.
**2.** You must have one RD (Aurelius84 (Recommend) or liym27 or zhhsplendid)approval for the data_type registration of new operator. More data_type of new operator should be registered in your PR. Please make sure that both float/double (or int/int64_t) have been registered.

**是否需要得到RD和TPM的approval**，对应的pr #22225

**Comment by luotao1** [comment]
> 我这边无法登录ci.paddlepaddle.org

@leesusu 非常抱歉，我们的CI正在安全检测中，通过检测后，会开放游客模式。

**Comment by guoshengCS** [comment]
test有个lite_resnet50_test出错这个正在修复

第2点中提到的问题应该是需要在这里 https://github.com/PaddlePaddle/Paddle/pull/22225/files#diff-f415005dd075a2bddb10bd62a21982fcR146   加上double类型的支持

**Comment by leesusu** [comment]
> 我们的CI正在安全检测中，通过检测后，会开放游客模式。

@luotao1 好的，谢谢～

> test有个lite_resnet50_test出错这个正在修复

@guoshengCS 感谢，这个好了也说一声

**Comment by leesusu** [comment]
@guoshengCS @iclementine 
double支持加上还是报错，帮忙看下：http://ci.paddlepaddle.org/viewLog.html?buildId=269658&buildTypeId=YYTest_PrCiCpuPy2

**Comment by iclementine** [comment]
http://ci.paddlepaddle.org/viewLog.html?buildId=269658&buildTypeId=YYTest_PrCiCpuPy2 这个 log 在这里。
[Compile_PR_CI_CPU_Py2_52233.log](https://github.com/PaddlePaddle/Paddle/files/4052414/Compile_PR_CI_CPU_Py2_52233.log)

因为修改了（增删改）接口，确实是需要RD和TPM的approval。

**Comment by leesusu** [comment]
@XiaoguangHu01 @lanxianghit 

这个CI：
http://ci.paddlepaddle.org/viewLog.html?buildId=269658&buildTypeId=YYTest_PrCiCpuPy2

报这个：
0. You must have one RD (XiaoguangHu01 or lanxianghit) and one TPM (saxon-zh or Boyan-Liu or swtkiwi) approval for the api change for the management reason of API interface.
1. You must have one TPM (saxon-zh or Boyan-Liu or swtkiwi) approval for the api change for the management reason of API document.

是找你们解决吗？帮忙看下，感谢🙏

**Comment by guoshengCS** [comment]
>test有个lite_resnet50_test出错这个正在修复

这个单测已修复，还请pull最新代码

**Comment by leesusu** [comment]
@guoshengCS 👌

**Comment by leesusu** [comment]
@XiaoguangHu01 @lanxianghit 

#22259 新增了接口，需要RD和TPM的approval，帮忙看下，感谢～
报错信息：http://ci.paddlepaddle.org/viewLog.html?buildId=270178&buildTypeId=YYTest_PrCiCpuPy2

**Comment by leesusu** [comment]
@guoshengCS 
coverage还是报错，帮忙看下log：http://ci.paddlepaddle.org/viewLog.html?buildId=270177&buildTypeId=Paddle_PrCiCoverage

**Comment by leesusu** [comment]
@luotao1 这个issue对应的pr #22259 麻烦能看下什么进度了吗？感谢🙏

**Comment by iclementine** [comment]
[Paddle_PR_CI_Coverage_53291.log](https://github.com/PaddlePaddle/Paddle/files/4280067/Paddle_PR_CI_Coverage_53291.log)
[Paddle_PR_CI_python35_52521.log](https://github.com/PaddlePaddle/Paddle/files/4280069/Paddle_PR_CI_python35_52521.log)
[PR_CI_CPU_Py2.log](https://github.com/PaddlePaddle/Paddle/files/4280071/PR_CI_CPU_Py2.log)

目前的 PR_CI_CPU_Py2.log 显示的是缺少 approve，这个不是代码的问题；
Paddle_PR_CI_Coverage_53291.log 显示 python 代码的单测覆盖率不够，还确实就是那三行抛异常的代码没有被覆盖到（可能好需要测试这个）；
Paddle_PR_CI_python35_52521.log 也不是代码的问题，是另一个单测 failed 了。我已经重新跑了这个。

**Comment by leesusu** [comment]
@iclementine 感谢，我再改下 “三行抛异常的覆盖率“
