### ISSUE TITLE
Functionality request: gradient of a gradient

### ISSUE THREAD

**Issue by pengli09** [PaddlePaddle/Paddle#2213]
Currently, we can not implement formula (3) easily in paper _[Improved Training of Wasserstein GANs](https://arxiv.org/abs/1704.00028)_, because we need the gradient of a gradient. Maybe this will be a good functionality to consider in the future.
Reference implementation: https://github.com/igul222/improved_wgan_training/blob/master/gan_toy.py

**Comment by jacquesqiao** [comment]
this feature will be done in Fluid.
