### ISSUE TITLE
训练脚本异常退出时，显存未自动释放

### ISSUE THREAD

**Issue by zhwesky2010** [PaddlePaddle/Paddle#22153]
Paddle在训练时如果因为异常原因退出脚本，比如设置过大的batch size，使得python程序挂掉退出，但分配的显存仍然存在，没有自动回收，GPU-Util是0%，如下图的GPU 6，显存都没有释放。只能通过kill -9杀掉相应进程，这是否是一个bug，或功能不支持的地方？

![image](https://user-images.githubusercontent.com/52485244/71904966-209f5f80-31a2-11ea-9aab-42e1dedcae63.png)

**Comment by QingYuan-L** [comment]
你好　，这个问题为什么关闭了呢？　我也遇到了这个问题，显存没有自动释放
