### ISSUE TITLE
PaddleGAN中的DCGAN的疑惑

### ISSUE THREAD

**Issue by herb711** [PaddlePaddle/Paddle#22151]
DCGAN.py中使用生成器生成图像用于优化判别器时，使用了如下代码
generate_image = exe.run(g_trainer_program,
                                         feed={'noise': noise_data},
                                         fetch_list=[g_trainer.fake])
疑惑的地方是，该代码运行时，是不是生成器也同时进行了优化？为何不用
g_trainer.infer_program 来替代 g_trainer_program ？？

很抱歉百忙之中到扰，如果能够得到回复，万分感谢。

**Comment by herb711** [comment]
当然，训练的时候，确实是一边优化生成器，一边优化判别器。个人疑惑在于，这里是有意为之，还是无意为之。这里使用g_trainer_program时，是否会优化生成器？可不可以使用g_trainer.infer_program来代替。因为后面161行还有
               for _ in six.moves.xrange(self.cfg.num_generator_time):
                    noise_data = np.random.uniform(
                        low=-1.0,
                        high=1.0,
                        size=[self.cfg.batch_size, self.cfg.noise_size]).astype(
                            'float32')
                    g_loss = exe.run(g_trainer_program,
                                     feed={'noise': noise_data},
                                     fetch_list=[g_trainer.g_loss])[0]
这应该也是用于优化生成器的。

**Comment by DDDivano** [comment]
> DCGAN.py中使用生成器生成图像用于优化判别器时，使用了如下代码
> generate_image = exe.run(g_trainer_program,
> feed={'noise': noise_data},
> fetch_list=[g_trainer.fake])
> 疑惑的地方是，该代码运行时，是不是生成器也同时进行了优化？为何不用
> g_trainer.infer_program 来替代 g_trainer_program ？？
> 
> 很抱歉百忙之中到扰，如果能够得到回复，万分感谢。

这块我看了一下代码，g_trainer.infer_program 来替代 g_trainer_program 是不行的，因为定义infer_program用的program.clone， fortest参数是True。会裁剪反向op，不能用来训练。

**Comment by herb711** [comment]
首先感谢回答，但是并不能完全解答我的疑惑。

用于训练生成器确实不能，如果训练中第一次调用run，主要是想获得一张生成图片generate_image，用这个来训练判别器，而非训练生成器。
如果是上述这种想法，可以用g_trainer.infer_program来代替吗？

生成器的训练代码中后面161行还有
for _ in six.moves.xrange(self.cfg.num_generator_time):
noise_data = np.random.uniform(
low=-1.0,
high=1.0,
size=[self.cfg.batch_size, self.cfg.noise_size]).astype(
'float32')
g_loss = exe.run(g_trainer_program,
feed={'noise': noise_data},
fetch_list=[g_trainer.g_loss])[0]

**Comment by herb711** [comment]
我主要是想知道，代码的作者的想法，他编写的思路是如下吗？
1、训练生成器，同时生成一张图片
2、用真图假图训练判别器
3、通过参数控制生成器再训练，默认是再训练1次


这样的话，其实一次过程中，生成器其实是默认训练了2次。
当然也不是说这个有错。我只是想知道作者是否是这样想的。

**Comment by ceci3** [comment]
是的，生成器默认是训练两次的。
流程应该是：
1. 通过生成器拿到一张生成图片，（代码里的program用错了，直接用infer_program就可以）
2.用真假图训练判别器
3.训练两次生成器（这里是因为GAN的训练不稳定，所以通过这种方式来控制生成判别过程中的平衡）

**Comment by DDDivano** [comment]
> 我主要是想知道，代码的作者的想法，他编写的思路是如下吗？
> 1、训练生成器，同时生成一张图片
> 2、用真图假图训练判别器
> 3、通过参数控制生成器再训练，默认是再训练1次
> 
> 这样的话，其实一次过程中，生成器其实是默认训练了2次。
> 当然也不是说这个有错。我只是想知道作者是否是这样想的。

这个写的比较trick。因为一个batch中相当于训练了2次判别器，然后训练生成器那个循环默认是1，可能存在不稳定，应该是训练两次和判别器对抗，所以在开始生成图片的时候训练了一次达到平衡，相当于每个batch训练2次生成器，2次判别器，实际可以第一次直接选择生成图，用inferprogram，不进行训练，然后通过参数调节每一轮生成器训练次数也是可以的（也不一定是说每一轮训练2次就是最佳的）。

**Comment by herb711** [comment]
OK，感谢大神百忙中还能如此细致的为我解惑。很感谢！
我看到找到模型bug可以得积分，上一次我找到dcgan中sigmoid重复的bug，劳烦加一下积分。
herb_711@sina.com
上面是我百度账号，我用它登录的飞浆。

**Comment by adaxiadaxi** [comment]
@herb711 hi，请问你是在哪里看到找到模型bug可以获得积分的信息呢？可以提供下信息的链接嘛，我这边去确认下~

**Comment by herb711** [comment]
链接如下
https://www.paddlepaddle.org.cn/modelbasedetail/stargan

在最后一行
“如何贡献代码

如果你可以修复某个issue或者增加一个新功能，欢迎给我们提交PR。如果对应的PR被接受了，我们将根据贡献的质量和难度进行打分（0-5分，越高越好）。如果你累计获得了10分，可以联系我们获得面试机会或者为你写推荐信。”

**Comment by adaxiadaxi** [comment]
@herb711 hi，同学，其实你也看到了"如果你可以修复某个issue或者增加一个新功能，欢迎给我们提交PR，如果对应的PR被接受了，我们将根据贡献的质量和难度进行打分"。其实我们更鼓励你这边直接提pr修复这个问题，如果pr被采纳了，才会有对应的积分奖励。不过这次可以先记录你找寻模型bug情况，之后再有提pr修复问题或新增功能的pr，我们会累积这次找模型bug的分数~
