### ISSUE TITLE
打开本地文件失败

### ISSUE THREAD

**Issue by tangbozhang** [PaddlePaddle/Paddle#22162]
在aistudio中打开本地文件报错
![image](https://user-images.githubusercontent.com/53244607/71957412-a9f97500-3228-11ea-9a45-b1156e855e89.png)

同样代码，在本地运行正常。

**Comment by tangbozhang** [comment]
aistudio 中paddle版本为1.4.1，本地安装的paddle版本为1.6.1

**Comment by wudenggang** [comment]
aistudio 是Ubuntu系统（非windows），报错内容说找不到对应的文件，更改下目录即可

**Comment by tangbozhang** [comment]
本地计算机为win10，启动的是anaconda中的基于paddle的notebook
[
![image](https://user-images.githubusercontent.com/53244607/72029381-b8936b00-32c0-11ea-8d4e-240aa0848126.png)
](url)

**Comment by tangbozhang** [comment]
![image](https://user-images.githubusercontent.com/53244607/72029437-e4aeec00-32c0-11ea-9ef3-2b0e5590b810.png)

**Comment by tangbozhang** [comment]
> aistudio 是Ubuntu系统（非windows），报错内容说找不到对应的文件，更改下目录即可
怎么修改？

**Comment by tangbozhang** [comment]
找到问题了，aistudio 访问本地路径，需要ip的
