### ISSUE TITLE
cuda9.0 安装后出错

### ISSUE THREAD

**Issue by nealys1049** [PaddlePaddle/Paddle#22178]
----------------------
Error Message Summary:
----------------------
Error: Paddle internal Check failed. (Please help us create a new issue, here we need to find the developer to add a user friendly error message)
  [CUBLAS: execution failed.] at (D:/1.6.2/paddle\paddle/fluid/operators/math/blas_impl.cu.h:34)
  [operator < mul > error]
>>>

**Comment by wanghaoshuang** [comment]
您好，贴一下您运行的代码？以及paddle的安装方式？
