### ISSUE TITLE
fleet gpu 多卡训练的一些疑问

### ISSUE THREAD

**Issue by yang-yq** [PaddlePaddle/Paddle#22192]
1. 用fleet gpu跑单机多卡，把fleet.worker_index()打出来看发现只显示0号卡的训练日志信息，请问一下这种情况符合预期吗？
2. 跑多机多卡（2机4张卡）时，teset的结果和单机单卡的测试集评估结果对不齐。（其中，单机单卡输出步数为12000，多机多卡的单机上的log输出为1500）

**Comment by gongweibao** [comment]
1. 符合预期。

其实都是一个问题。
步数然后*8(加上其他的)就是整体。

**Comment by yang-yq** [comment]
1. 那怎么查看别的卡的训练日志呢？用了CompiledProgram的with_data_parallel之后不是一份数据分给多张卡跑吗？

**Comment by gongweibao** [comment]
能否发下程序，我看你是怎么调用的？以及程序是怎么启动的？
