### ISSUE TITLE
topk op没有反向kernel, 并且文档中没有提示没有反向的kernel

### ISSUE THREAD

**Issue by wawltor** [PaddlePaddle/Paddle#22193]
![image](https://user-images.githubusercontent.com/16698950/72043800-19d13380-32ed-11ea-96f8-f97bf845138e.png)

因为影响了较多的模型的开发，希望增加topk的反向kernel

**Comment by Meiyim** [comment]
附议
Duplicate of #22138

**Comment by webary** [comment]
附议！调试了好久了

**Comment by Meiyim** [comment]
修复之前我先贡献一个权宜之计
```python
import paddle.fluid.layers as L

def topk_with_grad(inputs, k=1):
    _, idx = L.topk(inputs, k) #[., ., ., k]
    idx_flt = L.where(L.cast(L.ones_like(idx), 'bool'))  #[n, 3]
    idx_flt = L.concat([idx_flt[:, :-1], L.reshape(idx, [-1, 1])], 1) #[n, 4]
    idx_flt.stop_gradient = True
    val_flt = L.gather_nd(inputs, idx_flt)
    output_shape = L.concat([L.shape(inputs)[:-1], L.fill_constant(value=k, shape=[1], dtype='int32')])
    output_shape.stop_gradient = True
    val = L.reshape(val_flt, output_shape)
    return val, idx
```

**Comment by webary** [comment]
> 修复之前我先贡献一个权宜之计
> 
> ```python
> def topk_with_grad(inputs, k=1):
>     _, idx = L.topk(inputs, k) #[., ., ., k]
>     idx_flt = L.where(L.cast(L.ones_like(idx), 'bool'))  #[n, 3]
>     idx_flt = L.concat([idx_flt[:, :-1], L.reshape(idx, [-1, 1])], 1) #[n, 4]
>     idx_flt.stop_gradient = True
>     val_flt = L.gather_nd(inputs, idx_flt)
>     output_shape = L.concat([L.shape(inputs)[:-1], L.fill_constant(value=k, shape=[1], dtype='int32')])
>     output_shape.stop_gradient = True
>     val = L.reshape(val_flt, output_shape)
>     return val, idx
> ```

赞！请教下，L是在哪定义的？

**Comment by Meiyim** [comment]
我更新了上面的代码`L = paddle.fluid.layers`

**Comment by Meiyim** [comment]
any update?
