### ISSUE TITLE
[Paddle Book][DL 101]Dead link二级页面死链接

### ISSUE THREAD

**Issue by OleNet** [PaddlePaddle/Paddle#2221]
页面http://www.paddlepaddle.org/release_doc/0.10.0/doc/getstarted/index_en.html点击Deep Learning 101跳转到http://book.paddlepaddle.org/index.en.html

404

**Comment by luotao1** [comment]
fixed by #2358 and now the link is http://www.paddlepaddle.org/release/0.10.0/doc/getstarted/index_en.html
