### ISSUE TITLE
Do you really need parameters argument in paddle.infer in v2 api? 

### ISSUE THREAD

**Issue by pengwangucla** [PaddlePaddle/Paddle#2222]
In paddle infer function, you ask for parameters.

```python
def infer(output_layer, parameters, input, feeding=None, field='value'):

    inferer = Inference(output_layer=output_layer, parameters=parameters)
    return inferer.infer(field=field, input=input, feeding=feeding)
```

Actually, sometimes, a graph with some layers (like padding or resize), which do not contain parameters.

It is not clear why you need parameters in  v2 api

@jacquesqiao

**Comment by jacquesqiao** [comment]
most of the time, a model will contain some parameter, and the inference model need to use the odel to do infer.
