### ISSUE TITLE
调用save_inference_model，pslib模型没有小模型参数情况下，生成了param

### ISSUE THREAD

**Issue by Bella-Zhao** [PaddlePaddle/Paddle#22249]
我的model应该没有小模型参数。
训练链接：http://yq01-hpc-lvliang-mon.dmop.baidu.com:8919/taskinfo.html?appId=app-user-20200112170750-79094
网络配置在model.py 中

保存的xbox地址中出现param：
![image](https://user-images.githubusercontent.com/29970079/72241046-c0d10a80-3620-11ea-85a8-07dd709a5542.png)

我画出拓扑图看了，
应该没有小模型的参数，调用save infernce model保存的，调用代码：
![image](https://user-images.githubusercontent.com/29970079/72241084-d6463480-3620-11ea-86eb-2fd957498b09.png)
不知道为啥会生成param

__model__下载：
ftp://yq01-ps-7-m12-wise011.yq01.baidu.com/home/disk2/zhaoyijin/ffm/pslib_v2/check_tool/example/ffm_model/__model__
params下载
ftp://yq01-ps-7-m12-wise011.yq01.baidu.com/home/disk2/zhaoyijin/ffm/pslib_v2/check_tool/example/ffm_model/params

**Comment by NHZlX** [comment]
可否把网络发下。我本地测试下

**Comment by Bella-Zhao** [comment]
> 可否把网络发下。我本地测试下

ftp://yq01-ps-7-m12-wise011.yq01.baidu.com/home/disk2/zhaoyijin/ffm/pslib_v2/model_train_online_final_multiobj/package/my_nets/model.py

**Comment by NHZlX** [comment]
1. 模型的存储都是通过save op来进行的。
2. shell下设置export GLOG_v=4  
3. 运行save的过程，会打印详细的信息 
![image](https://user-images.githubusercontent.com/5595332/72510921-3ccb8c80-3885-11ea-9383-402014af8284.png)

所以可以看到你这边存储的var是什么
