### ISSUE TITLE
调用save_inference_model，pslib模型没有小模型参数情况下，生成了param

### ISSUE THREAD

**Issue by Bella-Zhao** [PaddlePaddle/Paddle#22248]
我的model应该没有小模型参数。ftp://yq01-ps-7-m12-wise011.yq01.baidu.com/home/disk2/zhaoyijin/ffm/pslib_v2/check_tool/example/ffm_model/__model__

我画出拓扑图看了，应该没有小模型的参数，也是调用save infernce model的，不知道为啥会生成param

**Comment by NHZlX** [comment]
The question is the same as this [one](https://github.com/PaddlePaddle/Paddle/issues/22249).
