### ISSUE TITLE
程序在import paddle.fluid as fluid之后打包无法运行也没有报错

### ISSUE THREAD

**Issue by weikangSDU** [PaddlePaddle/Paddle#22242]
版本、环境信息：
    1）PaddlePaddle版本：1.5.1
    2）CPU/GPU：CPU
    3）系统环境：ubuntu16.04、win10
    4）Python版本号3.6
- 复现信息：无报错
- 问题描述：
无论是我自己写的或者官网上快速开始最简单的第一个实例，在引用paddle.fluid之后都无法正常运行，打包命令为pyinstaller -F test.py,如果为pyinstaller test.py会出现进程一直增加，最终内存爆炸的情况。在打包过程中，我已经添加要求补充的ntlk_data文件夹不引用该依赖则无该问题
![image](https://user-images.githubusercontent.com/53069165/72235386-e05e3800-360c-11ea-96e8-163a0adc8fb3.png)

**Comment by weikangSDU** [comment]
有没有大佬回一下

**Comment by HaiLongEmb** [comment]
@weikangSDU 请问，你找到解决办法了吗？

**Comment by ArtyZe** [comment]
@HaiLongEmb @weikangSDU 同问，请问两位解决了吗？

**Comment by weikangSDU** [comment]
没有，最后没有打包



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "ArtyZe"<notifications@github.com&gt;; 
发送时间: 2020年5月22日(星期五) 下午2:14
收件人: "PaddlePaddle/Paddle"<Paddle@noreply.github.com&gt;; 
抄送: "韦康"<1669300498@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [PaddlePaddle/Paddle] 程序在import paddle.fluid as fluid之后打包无法运行也没有报错 (#22242)





 
@HaiLongEmb @weikangSDU 同问，请问两位解决了吗？

**Comment by ArtyZe** [comment]
@weikangSDU ,那后面怎么操作？用脚本去run python吗？还是c++复现了一下。

有一说一，百度依赖的第三方库着实太多了点，怎么搞都很不方便

**Comment by weikangSDU** [comment]
就没有打包啊，我那是个小项目，整合成一个py文件，把pyc给别人了，你可以加他的官方群去问问。c我一点都不会




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "ArtyZe"<notifications@github.com&gt;; 
发送时间: 2020年5月22日(星期五) 下午2:20
收件人: "PaddlePaddle/Paddle"<Paddle@noreply.github.com&gt;; 
抄送: "韦康"<1669300498@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [PaddlePaddle/Paddle] 程序在import paddle.fluid as fluid之后打包无法运行也没有报错 (#22242)





 
@weikangSDU ,那后面怎么操作？用脚本去run python吗？还是c++复现了一下。
 
有一说一，百度依赖的第三方库着实太多了点，怎么搞都很不方便

**Comment by Microkitty** [comment]
> 
> 
> 版本、环境信息：
>    1）PaddlePaddle版本：1.5.1
>    2）CPU/GPU：CPU
>    3）系统环境：ubuntu16.04、win10
>    4）Python版本号3.6
> 
>     * 复现信息：无报错
> 
>     * 问题描述：
>       无论是我自己写的或者官网上快速开始最简单的第一个实例，在引用paddle.fluid之后都无法正常运行，打包命令为pyinstaller -F test.py,如果为pyinstaller test.py会出现进程一直增加，最终内存爆炸的情况。在打包过程中，我已经添加要求补充的ntlk_data文件夹不引用该依赖则无该问题
>       ![image](https://user-images.githubusercontent.com/53069165/72235386-e05e3800-360c-11ea-96e8-163a0adc8fb3.png)

问题解决了吗，我遇到同样的情况，程序一直卡着进程越来越多

**Comment by weikangSDU** [comment]
> > 版本、环境信息：
> > 1）PaddlePaddle版本：1.5.1
> > 2）CPU/GPU：CPU
> > 3）系统环境：ubuntu16.04、win10
> > 4）Python版本号3.6
> > ```
> > * 复现信息：无报错
> > 
> > * 问题描述：
> >   无论是我自己写的或者官网上快速开始最简单的第一个实例，在引用paddle.fluid之后都无法正常运行，打包命令为pyinstaller -F test.py,如果为pyinstaller test.py会出现进程一直增加，最终内存爆炸的情况。在打包过程中，我已经添加要求补充的ntlk_data文件夹不引用该依赖则无该问题
> >   ![image](https://user-images.githubusercontent.com/53069165/72235386-e05e3800-360c-11ea-96e8-163a0adc8fb3.png)
> > ```
> 
> 问题解决了吗，我遇到同样的情况，程序一直卡着进程越来越多

没有，后面就没整这个了

**Comment by ArtyZe** [comment]
> > 版本、环境信息：
> > 1）PaddlePaddle版本：1.5.1
> > 2）CPU/GPU：CPU
> > 3）系统环境：ubuntu16.04、win10
> > 4）Python版本号3.6
> > ```
> > * 复现信息：无报错
> > 
> > * 问题描述：
> >   无论是我自己写的或者官网上快速开始最简单的第一个实例，在引用paddle.fluid之后都无法正常运行，打包命令为pyinstaller -F test.py,如果为pyinstaller test.py会出现进程一直增加，最终内存爆炸的情况。在打包过程中，我已经添加要求补充的ntlk_data文件夹不引用该依赖则无该问题
> >   ![image](https://user-images.githubusercontent.com/53069165/72235386-e05e3800-360c-11ea-96e8-163a0adc8fb3.png)
> > ```
> 
> 问题解决了吗，我遇到同样的情况，程序一直卡着进程越来越多

其实你把你的exe文件换个电脑或者虚拟机跑一下就可以看到他报的错了。
我的已经解决了，这里其实它就是缺少dll文件，你把paddle下面的那些mdl的dll库同时打包进去就可以了。

**Comment by Microkitty** [comment]
> 
> 
> > > 版本、环境信息：
> > > 1）PaddlePaddle版本：1.5.1
> > > 2）CPU/GPU：CPU
> > > 3）系统环境：ubuntu16.04、win10
> > > 4）Python版本号3.6
> > > ```
> > > * 复现信息：无报错
> > > 
> > > * 问题描述：
> > >   无论是我自己写的或者官网上快速开始最简单的第一个实例，在引用paddle.fluid之后都无法正常运行，打包命令为pyinstaller -F test.py,如果为pyinstaller test.py会出现进程一直增加，最终内存爆炸的情况。在打包过程中，我已经添加要求补充的ntlk_data文件夹不引用该依赖则无该问题
> > >   ![image](https://user-images.githubusercontent.com/53069165/72235386-e05e3800-360c-11ea-96e8-163a0adc8fb3.png)
> > > ```
> > 
> > 
> > 问题解决了吗，我遇到同样的情况，程序一直卡着进程越来越多
> 
> 其实你把你的exe文件换个电脑或者虚拟机跑一下就可以看到他报的错了。
> 我的已经解决了，这里其实它就是缺少dll文件，你把paddle下面的那些mdl的dll库同时打包进去就可以了。

如果找到对应缺失的库了，pyinstaller怎么同步打包

**Comment by ArtyZe** [comment]
> > > > 版本、环境信息：
> > > > 1）PaddlePaddle版本：1.5.1
> > > > 2）CPU/GPU：CPU
> > > > 3）系统环境：ubuntu16.04、win10
> > > > 4）Python版本号3.6
> > > > ```
> > > > * 复现信息：无报错
> > > > 
> > > > * 问题描述：
> > > >   无论是我自己写的或者官网上快速开始最简单的第一个实例，在引用paddle.fluid之后都无法正常运行，打包命令为pyinstaller -F test.py,如果为pyinstaller test.py会出现进程一直增加，最终内存爆炸的情况。在打包过程中，我已经添加要求补充的ntlk_data文件夹不引用该依赖则无该问题
> > > >   ![image](https://user-images.githubusercontent.com/53069165/72235386-e05e3800-360c-11ea-96e8-163a0adc8fb3.png)
> > > > ```
> > > 
> > > 
> > > 问题解决了吗，我遇到同样的情况，程序一直卡着进程越来越多
> > 
> > 
> > 其实你把你的exe文件换个电脑或者虚拟机跑一下就可以看到他报的错了。
> > 我的已经解决了，这里其实它就是缺少dll文件，你把paddle下面的那些mdl的dll库同时打包进去就可以了。
> 
> 如果找到对应缺失的库了，pyinstaller怎么同步打包

修改pyinstaller的spec，然后从pyinstaller -f *.py改为pyinstaller -f *.spec，在spec的data那里指定你要同时包含的dll文件

**Comment by Microkitty** [comment]
> 
> 
> > > > > 版本、环境信息：
> > > > > 1）PaddlePaddle版本：1.5.1
> > > > > 2）CPU/GPU：CPU
> > > > > 3）系统环境：ubuntu16.04、win10
> > > > > 4）Python版本号3.6
> > > > > ```
> > > > > * 复现信息：无报错
> > > > > 
> > > > > * 问题描述：
> > > > >   无论是我自己写的或者官网上快速开始最简单的第一个实例，在引用paddle.fluid之后都无法正常运行，打包命令为pyinstaller -F test.py,如果为pyinstaller test.py会出现进程一直增加，最终内存爆炸的情况。在打包过程中，我已经添加要求补充的ntlk_data文件夹不引用该依赖则无该问题
> > > > >   ![image](https://user-images.githubusercontent.com/53069165/72235386-e05e3800-360c-11ea-96e8-163a0adc8fb3.png)
> > > > > ```
> > > > 
> > > > 
> > > > 问题解决了吗，我遇到同样的情况，程序一直卡着进程越来越多
> > > 
> > > 
> > > 其实你把你的exe文件换个电脑或者虚拟机跑一下就可以看到他报的错了。
> > > 我的已经解决了，这里其实它就是缺少dll文件，你把paddle下面的那些mdl的dll库同时打包进去就可以了。
> > 
> > 
> > 如果找到对应缺失的库了，pyinstaller怎么同步打包
> 
> 修改pyinstaller的spec，然后从pyinstaller -f *.py改为pyinstaller -f *.spec，在spec的data那里指定你要同时包含的dll文件

你当时是缺少哪些dll我先试试

**Comment by ArtyZe** [comment]
> > > > > > 版本、环境信息：
> > > > > > 1）PaddlePaddle版本：1.5.1
> > > > > > 2）CPU/GPU：CPU
> > > > > > 3）系统环境：ubuntu16.04、win10
> > > > > > 4）Python版本号3.6
> > > > > > ```
> > > > > > * 复现信息：无报错
> > > > > > 
> > > > > > * 问题描述：
> > > > > >   无论是我自己写的或者官网上快速开始最简单的第一个实例，在引用paddle.fluid之后都无法正常运行，打包命令为pyinstaller -F test.py,如果为pyinstaller test.py会出现进程一直增加，最终内存爆炸的情况。在打包过程中，我已经添加要求补充的ntlk_data文件夹不引用该依赖则无该问题
> > > > > >   ![image](https://user-images.githubusercontent.com/53069165/72235386-e05e3800-360c-11ea-96e8-163a0adc8fb3.png)
> > > > > > ```
> > > > > 
> > > > > 
> > > > > 问题解决了吗，我遇到同样的情况，程序一直卡着进程越来越多
> > > > 
> > > > 
> > > > 其实你把你的exe文件换个电脑或者虚拟机跑一下就可以看到他报的错了。
> > > > 我的已经解决了，这里其实它就是缺少dll文件，你把paddle下面的那些mdl的dll库同时打包进去就可以了。
> > > 
> > > 
> > > 如果找到对应缺失的库了，pyinstaller怎么同步打包
> > 
> > 
> > 修改pyinstaller的spec，然后从pyinstaller -f *.py改为pyinstaller -f *.spec，在spec的data那里指定你要同时包含的dll文件
> 
> 你当时是缺少哪些dll我先试试

去paddle下面搜就ok了呀，paddle用了mkl的加速库，就是两个相关的dll。
你如果实在懒得打包，我教你一招，把这些dll和你的exe一起发布，程序跑之前把dll先拷贝到system下，就解决了，你就不用重新打包了

**Comment by Microkitty** [comment]
> 
> 
> > > > > > > 版本、环境信息：
> > > > > > > 1）PaddlePaddle版本：1.5.1
> > > > > > > 2）CPU/GPU：CPU
> > > > > > > 3）系统环境：ubuntu16.04、win10
> > > > > > > 4）Python版本号3.6
> > > > > > > ```
> > > > > > > * 复现信息：无报错
> > > > > > > 
> > > > > > > * 问题描述：
> > > > > > >   无论是我自己写的或者官网上快速开始最简单的第一个实例，在引用paddle.fluid之后都无法正常运行，打包命令为pyinstaller -F test.py,如果为pyinstaller test.py会出现进程一直增加，最终内存爆炸的情况。在打包过程中，我已经添加要求补充的ntlk_data文件夹不引用该依赖则无该问题
> > > > > > >   ![image](https://user-images.githubusercontent.com/53069165/72235386-e05e3800-360c-11ea-96e8-163a0adc8fb3.png)
> > > > > > > ```
> > > > > > 
> > > > > > 
> > > > > > 问题解决了吗，我遇到同样的情况，程序一直卡着进程越来越多
> > > > > 
> > > > > 
> > > > > 其实你把你的exe文件换个电脑或者虚拟机跑一下就可以看到他报的错了。
> > > > > 我的已经解决了，这里其实它就是缺少dll文件，你把paddle下面的那些mdl的dll库同时打包进去就可以了。
> > > > 
> > > > 
> > > > 如果找到对应缺失的库了，pyinstaller怎么同步打包
> > > 
> > > 
> > > 修改pyinstaller的spec，然后从pyinstaller -f *.py改为pyinstaller -f *.spec，在spec的data那里指定你要同时包含的dll文件
> > 
> > 
> > 你当时是缺少哪些dll我先试试
> 
> 去paddle下面搜就ok了呀，paddle用了mkl的加速库，就是两个相关的dll。
> 你如果实在懒得打包，我教你一招，把这些dll和你的exe一起发布，程序跑之前把dll先拷贝到system下，就解决了，你就不用重新打包了

主要是不知道要拷贝哪些dll，我已经拷贝了很多了还是不行

**Comment by ArtyZe** [comment]
> > > > > > > > 版本、环境信息：
> > > > > > > > 1）PaddlePaddle版本：1.5.1
> > > > > > > > 2）CPU/GPU：CPU
> > > > > > > > 3）系统环境：ubuntu16.04、win10
> > > > > > > > 4）Python版本号3.6
> > > > > > > > ```
> > > > > > > > * 复现信息：无报错
> > > > > > > > 
> > > > > > > > * 问题描述：
> > > > > > > >   无论是我自己写的或者官网上快速开始最简单的第一个实例，在引用paddle.fluid之后都无法正常运行，打包命令为pyinstaller -F test.py,如果为pyinstaller test.py会出现进程一直增加，最终内存爆炸的情况。在打包过程中，我已经添加要求补充的ntlk_data文件夹不引用该依赖则无该问题
> > > > > > > >   ![image](https://user-images.githubusercontent.com/53069165/72235386-e05e3800-360c-11ea-96e8-163a0adc8fb3.png)
> > > > > > > > ```
> > > > > > > 
> > > > > > > 
> > > > > > > 问题解决了吗，我遇到同样的情况，程序一直卡着进程越来越多
> > > > > > 
> > > > > > 
> > > > > > 其实你把你的exe文件换个电脑或者虚拟机跑一下就可以看到他报的错了。
> > > > > > 我的已经解决了，这里其实它就是缺少dll文件，你把paddle下面的那些mdl的dll库同时打包进去就可以了。
> > > > > 
> > > > > 
> > > > > 如果找到对应缺失的库了，pyinstaller怎么同步打包
> > > > 
> > > > 
> > > > 修改pyinstaller的spec，然后从pyinstaller -f *.py改为pyinstaller -f *.spec，在spec的data那里指定你要同时包含的dll文件
> > > 
> > > 
> > > 你当时是缺少哪些dll我先试试
> > 
> > 
> > 去paddle下面搜就ok了呀，paddle用了mkl的加速库，就是两个相关的dll。
> > 你如果实在懒得打包，我教你一招，把这些dll和你的exe一起发布，程序跑之前把dll先拷贝到system下，就解决了，你就不用重新打包了
> 
> 主要是不知道要拷贝哪些dll，我已经拷贝了很多了还是不行
![image](https://user-images.githubusercontent.com/32027268/88904371-94f93780-d287-11ea-988a-d7807dd934cb.png)
其实这些信息你在打包的时候认真点看，是可以看到他报找不到这个库的warning的

**Comment by Microkitty** [comment]
> 
> 
> > > > > > > > > 版本、环境信息：
> > > > > > > > > 1）PaddlePaddle版本：1.5.1
> > > > > > > > > 2）CPU/GPU：CPU
> > > > > > > > > 3）系统环境：ubuntu16.04、win10
> > > > > > > > > 4）Python版本号3.6
> > > > > > > > > ```
> > > > > > > > > * 复现信息：无报错
> > > > > > > > > 
> > > > > > > > > * 问题描述：
> > > > > > > > >   无论是我自己写的或者官网上快速开始最简单的第一个实例，在引用paddle.fluid之后都无法正常运行，打包命令为pyinstaller -F test.py,如果为pyinstaller test.py会出现进程一直增加，最终内存爆炸的情况。在打包过程中，我已经添加要求补充的ntlk_data文件夹不引用该依赖则无该问题
> > > > > > > > >   ![image](https://user-images.githubusercontent.com/53069165/72235386-e05e3800-360c-11ea-96e8-163a0adc8fb3.png)
> > > > > > > > > ```
> > > > > > > > 
> > > > > > > > 
> > > > > > > > 问题解决了吗，我遇到同样的情况，程序一直卡着进程越来越多
> > > > > > > 
> > > > > > > 
> > > > > > > 其实你把你的exe文件换个电脑或者虚拟机跑一下就可以看到他报的错了。
> > > > > > > 我的已经解决了，这里其实它就是缺少dll文件，你把paddle下面的那些mdl的dll库同时打包进去就可以了。
> > > > > > 
> > > > > > 
> > > > > > 如果找到对应缺失的库了，pyinstaller怎么同步打包
> > > > > 
> > > > > 
> > > > > 修改pyinstaller的spec，然后从pyinstaller -f *.py改为pyinstaller -f *.spec，在spec的data那里指定你要同时包含的dll文件
> > > > 
> > > > 
> > > > 你当时是缺少哪些dll我先试试
> > > 
> > > 
> > > 去paddle下面搜就ok了呀，paddle用了mkl的加速库，就是两个相关的dll。
> > > 你如果实在懒得打包，我教你一招，把这些dll和你的exe一起发布，程序跑之前把dll先拷贝到system下，就解决了，你就不用重新打包了
> > 
> > 
> > 主要是不知道要拷贝哪些dll，我已经拷贝了很多了还是不行
> > ![image](https://user-images.githubusercontent.com/32027268/88904371-94f93780-d287-11ea-988a-d7807dd934cb.png)
> > 其实这些信息你在打包的时候认真点看，是可以看到他报找不到这个库的warning的

果然，解决了，感谢

**Comment by Springzcf** [comment]
用的版本是paddlepaddle 1.8.4，CPU版本，需要对工程进行pyinstaller打包，环境是centos7，打包过程没有错误，但是打包成可执行程序，运行的时候，遇到import paddle 就会卡死，没有报错，查询内存 线程使用情况，每隔几秒就会创建一个线程。但是还没有任何反应。然后写了一个很简单的demo，只有几行代码，from paddle.fluid.core import AnalysisConfig, create_paddle_predictor,也会出现类似的问题。应该在paddle初始化的时候有问题。请问有什么解决方案吗？

**Comment by tianzuishiwo** [comment]
解决方案参考 https://blog.csdn.net/aqqwvfbukn/article/details/120553124
