### ISSUE TITLE
py_func输出类别存在问题

### ISSUE THREAD

**Issue by LordAaron** [PaddlePaddle/Paddle#22250]
Paddle1.6.1 develop版本
out类型中并不支持list[Variale]，图贴不上来，这个链接：https://www.paddlepaddle.org.cn/documentation/docs/zh/api_cn/layers_cn/py_func_cn.html#py-func
源码中也确实没有此类型的判断
P.S. 输入X也存在这个问题，不支持list[Variale]

**Comment by jiweibo** [comment]
> Paddle1.6.1 develop版本
> out类型中并不支持list[Variale]，图贴不上来，这个链接：https://www.paddlepaddle.org.cn/documentation/docs/zh/api_cn/layers_cn/py_func_cn.html#py-func
> 源码中也确实没有此类型的判断
> P.S. 输入X也存在这个问题，不支持list[Variale]

可以参考下这个示例哈
https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/fluid/layers/nn.py#L12528

**Comment by LordAaron** [comment]
> > Paddle1.6.1 develop版本
> > out类型中并不支持list[Variale]，图贴不上来，这个链接：https://www.paddlepaddle.org.cn/documentation/docs/zh/api_cn/layers_cn/py_func_cn.html#py-func
> > 源码中也确实没有此类型的判断
> > P.S. 输入X也存在这个问题，不支持list[Variale]
> 
> 可以参考下这个示例哈
> https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/fluid/layers/nn.py#L12528

嗯，那我理解错了输入X支持list[Variale]的意思
但是输出应该怎么理解呢？我看示例里面没有针对out为list[Variale]的情况

**Comment by jiweibo** [comment]
> > > Paddle1.6.1 develop版本
> > > out类型中并不支持list[Variale]，图贴不上来，这个链接：https://www.paddlepaddle.org.cn/documentation/docs/zh/api_cn/layers_cn/py_func_cn.html#py-func
> > > 源码中也确实没有此类型的判断
> > > P.S. 输入X也存在这个问题，不支持list[Variale]
> > 
> > 
> > 可以参考下这个示例哈
> > https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/fluid/layers/nn.py#L12528
> 
> 嗯，那我理解错了输入X支持list[Variale]的意思
> 但是输出应该怎么理解呢？我看示例里面没有针对out为list[Variale]的情况

这个输入输出是针对于op而言的，elementwise_add这个op输入是俩所以用X=[x1,x2] list [variable]来表示。输出也是针对op而言的，比如写的op输出是两个variable，那么就要用到list了

**Comment by jiweibo** [comment]
该issue长时间没有更新，可以先关闭了，如要继续讨论请再打开
