### ISSUE TITLE
请问，CPU 需支持 MKL，具体指什么啊，i5-4460 支持 MKL么？请教

### ISSUE THREAD

**Issue by lluck42** [PaddlePaddle/Paddle#22258]
RT

**Comment by wzzju** [comment]
> RT

Intel MKL：Intel Math Kernel Library，英特尔数学核心函数库。更多细节，请自行百度`MKL`关键词。MKL是一种数学计算库，i5-4460应该是支持的，具体需要自行安装这个库进行验证。

**Comment by lluck42** [comment]
明白了，多谢哈

发送自 Windows 10 版邮件应用

发件人: Zhen Wang
发送时间: 2020年1月14日 20:59
收件人: PaddlePaddle/Paddle
抄送: lluck42; Author
主题: Re: [PaddlePaddle/Paddle] 请问，CPU 需支持 MKL，具体指什么啊，i5-4460 支持 MKL么？请教 (#22258)

RT
Intel MKL：Intel Math Kernel Library，英特尔数学核心函数库。更多细节，请自行百度MKL关键词。MKL是一种数学计算库，i5-4460应该是支持的，具体需要自行安装这个库进行验证。
