### ISSUE TITLE
paddle在save_inference_model中，用fluid.layers.split失败

### ISSUE THREAD

**Issue by zhengyandan** [PaddlePaddle/Paddle#22251]
paddle在save_inference_model中，用了fluid.layers.split生成的文件不包含split参数失败，反解确认过
1、输入是一个vector，但是一部分vector数据需要data norm，一部分不需要，所有用了split
2、用了1.6版本fluid的python包调用fluid.io.save_inference_model这个接口，产生的描述文件里面没有split参数
3、python版本确认是1.6，测试过，直接fluid.layers.split没有问题

**Comment by NHZlX** [comment]
可否用1.6.2测试下，如果有问题，可否提供下复现的单测。

**Comment by zhengyandan** [comment]
Hi，请问下有1.6.2版本fluid 的python包吗？
有脚本，可以直接提供测试，见附件

发件人: Zhaolong Xing <notifications@github.com<mailto:notifications@github.com>>
答复: PaddlePaddle/Paddle <reply@reply.github.com<mailto:reply@reply.github.com>>
日期: 2020年1月13日 星期一 下午5:24
至: PaddlePaddle/Paddle <Paddle@noreply.github.com<mailto:Paddle@noreply.github.com>>
抄送: "Zheng,Yandan" <zhengyandan@baidu.com<mailto:zhengyandan@baidu.com>>, Author <author@noreply.github.com<mailto:author@noreply.github.com>>
主题: Re: [PaddlePaddle/Paddle] paddle在save_inference_model中，用fluid.layers.split失败 (#22251)


可否用1.6.2测试下，如果有问题，可否提供下复现的单测。

**Comment by Shixiaowei02** [comment]
脚本有错误，一般情况下不应该用 `"tmp_0"` 作为自定义变量的名称。这种名称 Fluid 内部保留用作自动命名中间变量。所以请将 `generate_ad_model.py:14` 修改为下列代码
`cvms_all = fluid.layers.data(name='X', shape=[-1,1454], dtype='float32')`
用 Fluid 1.6.1 以上版本再试一遍，谢谢

**Comment by NHZlX** [comment]
update:  构建模型后需要调用exe.run(fluid.default_startup_program()) 初始化参数，然后才能save inference model ，否则会出现 某tensor 未初始化的错误。
