### ISSUE TITLE
预训练模型

### ISSUE THREAD

**Issue by wbchief** [PaddlePaddle/Paddle#22256]
您好，请问在PaddlePaddle下预训练的VGG16等模型，如何使用这些预训练好的模型来更新自己利用PaddlePaddle构建的动态图模型网络的参数。就如Pytorch中的这段代码：
`mod = models.vgg16(pretrained = True)
fs = self.frontend.state_dict()
ms = mod.state_dict()
for key in fs:
    fs[key] = ms['features.'+key]
    self.frontend.load_state_dict(fs)`

谢谢！在网上没能找到相关资料。

**Comment by NHZlX** [comment]
可以用以下接口：

```
def if_exist(var):
            is_ex = os.path.exists(os.path.join("./InceptionV4_pretrained", var.name))
            print is_ex
            return is_ex 
fluid.io.load_vars(exe, "./InceptionV4_pretrained", predicate=if_exist)
```

**Comment by wbchief** [comment]
Thanks.
