### ISSUE TITLE
安装报错CondaVerificationError: The package for cudatoolkit located at**appears to be corrupted. The path 'lib/libcublas.so' specified in the package manifest cannot be found.

### ISSUE THREAD

**Issue by hmmwjs** [PaddlePaddle/Paddle#22260]
显卡 :Tesla T4
环境 :Ubuntu、cudaV10.0.130、cudnn7.5
安装方式：conda
报错信息：
Preparing transaction: done
Verifying transaction: failed

CondaVerificationError: The package for cudatoolkit located at /home/###/.conda/pkgs/cudatoolkit-10.0.130-0
appears to be corrupted. The path '**lib/libcublas.so**'
specified in the package manifest cannot be found.

CondaVerificationError: The package for cudatoolkit located at /home/###/.conda/pkgs/cudatoolkit-10.0.130-0
appears to be corrupted. The path '**lib/libcublas.so.10.0.130**'
specified in the package manifest cannot be found.
。。。
好多条,只是每条的动态库(粗体部分)不一样

**Comment by hmmwjs** [comment]
![image](https://user-images.githubusercontent.com/25680888/72311052-700fef00-36be-11ea-9c9b-57df7444ad8d.png)

**Comment by wzzju** [comment]
根据报错信息可知，不能正确找到cuda的一些库文件，请确认cuda的安装路径是否配置正确。
