### ISSUE TITLE
调用1.6.2版本fluid自带rnn模块，报tensor未初始化问题

### ISSUE THREAD

**Issue by mtchen2016** [PaddlePaddle/Paddle#22270]
- 版本、环境信息：
    1）PaddlePaddle版本：1.6.2
    2）CPU：本地训练
    3）系统环境：Python2.7
- 训练信息
    1）单机
- 问题描述：
调用fluid自带rnn模块，出现tensor未初始化问题。已经检查过input数据，已经正常初始化。打印过中间变量发现，调用StaticRNN类后，进入recurrent op抛出异常。
----------------------
Error Message Summary:
----------------------
Error: Tensor not initialized yet when Tensor::type() is called.
  [Hint: holder_ should not be null.] at (/paddle/paddle/fluid/framework/tensor.h:139)

**Comment by wzzju** [comment]
> Error: Tensor not initialized yet when Tensor::type() is called.
[Hint: holder_ should not be null.] at (/paddle/paddle/fluid/framework/tensor.h:139)

请问这个错误是因为打印中间变量这个操作导致的吗？不打印中间变量是不是就不会报错？

**Comment by mtchen2016** [comment]
> > Error: Tensor not initialized yet when Tensor::type() is called.
> > [Hint: holder_ should not be null.] at (/paddle/paddle/fluid/framework/tensor.h:139)
> 
> 请问这个错误是因为打印中间变量这个操作导致的吗？不打印中间变量是不是就不会报错？

不是的，即使不打印中间变量，也是同样的错误。联系paddle同学排查，只能定位到打印的错误是static_rnn_0.tmp_0，但是，中间通过中间过程打印来看，static_rnn_0.tmp_0在前面已经被打印输出过。
