### ISSUE TITLE
Add audio data augmentation process to audio data provider.

### ISSUE THREAD

**Issue by xinghai-sun** [PaddlePaddle/Paddle#2227]
- Add audio data augmentation (injecting noise tracks) to [audio data provider](https://github.com/PaddlePaddle/Paddle/issues/2226).
- Please refer to [DS2 paper](https://arxiv.org/abs/1512.02595) and [DS1 paper](https://arxiv.org/abs/1412.5567) for details. 
- Please refer to [deepspeech.pytorch](https://github.com/SeanNaren/deepspeech.pytorch#noise-augmentationinjection).
- Refer to the [DS2 design doc](https://github.com/xinghai-sun/Paddle/tree/ds2_design_doc/doc/design/speech) and update it when necessary.

**Comment by chrisxu2016** [comment]
add simple design doc  https://github.com/chrisxu2016/Paddle/blob/develop/doc/design/speech/README.MD

**Comment by chrisxu2016** [comment]
construct design doc for augmentation：
https://github.com/chrisxu2016/models/blob/develop/deep_speech_2/augmentation/README.md
