### ISSUE TITLE
Cityscape dataset

### ISSUE THREAD

**Issue by leonleeldc** [PaddlePaddle/Paddle#22286]
Hi, 
In models/dygraph/cycle_gan/, the model makes use cityscape to do the cycle_gan training and testing. In the readme, it says that the data can be downloaded with download.py. But it turns out that the downloaded data doesn't contain anything useful. 

I went to cityscape website to download all data. But I didn't see which script to help to organize the data as following. 

data
|-- cityscapes
|   |-- testA
|   |-- testA.txt
|   |-- testB
|   |-- testB.txt
|   |-- trainA
|   |-- trainA.txt
|   |-- trainB
|   `-- trainB.txt

So, what I can do to make the model run with the citiscape data organized as the above structure. 

Thanks,

**Comment by jerrywgz** [comment]
Sure we will fix the download.py for cityscape soon . You can use https://github.com/PaddlePaddle/models/blob/develop/PaddleCV/PaddleGAN/scripts/prepare_cityscapes_dataset.py to preprocess the orginal dataset for now.

**Comment by Shixiaowei02** [comment]
@tink2123 Please pay attention to this issue.

**Comment by leonleeldc** [comment]
Thanks a lot! It works although it seems that the name in the script is a little bit inconsistent. Say, val vs test. And the trainA.txt, trainB.txt, testA.txt and testB.txt are not generated by the script either. I simply use command line "find ./ > trainA.txt" to generate them.
