### ISSUE TITLE
Paddle_V1.3源码编译出错

### ISSUE THREAD

**Issue by bitianchi** [PaddlePaddle/Paddle#22298]
![image](https://user-images.githubusercontent.com/29396595/72409739-95295e00-37a1-11ea-84f4-ff53e98e0157.png)

在链接的时候出错，并且已经设置了DPYTHON_LIBRARY

**Comment by jerrywgz** [comment]
需要检查下python2.7 lib路径是否加入到LD_LIBRARY_PATH中，也可参考该链接https://www.cnblogs.com/zhming26/p/6164131.html
