### ISSUE TITLE
训练place是 cpu，save_param之后，在GPU上load_param会出错？

### ISSUE THREAD

**Issue by dongfangyixi** [PaddlePaddle/Paddle#22306]
如题
error msg:

----------------------
Error Message Summary:
----------------------
InvalidArgumentError: Cannot parse tensor desc
  [Hint: Expected desc.ParseFromArray(buf.get(), size) == true, but received desc.ParseFromArray(buf.get(), size):0 != true:1.] at (/paddle/paddle/fluid/framework/tensor_util.cu:527)
  [operator < load_combine > error]

**Comment by jerrywgz** [comment]
可以提供下可复现的save load代码吗？
