### ISSUE TITLE
子层变量一旦设置为空后在赋值，就会抛出异常

### ISSUE THREAD

**Issue by chunyisong** [PaddlePaddle/Paddle#22313]
paddle 1.6,子层变量一旦设置为空后在赋值，就会抛出异常

![QQ截图20200115201713](https://user-images.githubusercontent.com/7147583/72433423-3cbf8400-37d4-11ea-804f-1a8871ebfccf.png)

call last)<ipython-input-45-87611689617e> in <module>
     36     labels = fluid.dygraph.to_variable(np.ones((10,1),dtype='int64'))
     37     for epoch in range(3):
---> 38         out = model(inputs)
     39         loss = fluid.layers.softmax_with_cross_entropy(out,label=labels)
     40         avgLoss = fluid.layers.mean(loss)
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py in __call__(self, *inputs, **kwargs)
    176                 parallel_helper._broadcast_parameters(self._parameters.values())
    177 
--> 178         outputs = self.forward(*inputs, **kwargs)
    179         self._built = True
    180         return outputs
<ipython-input-45-87611689617e> in forward(self, inputs)
     24         # self.conv2 = None
     25     def forward(self,inputs):
---> 26         y = self.conv(inputs)
     27         short = inputs
     28         short = self.conv2(y)
TypeError: 'NoneType' object is not callable

>

**Comment by jerrywgz** [comment]
这里self.conv2没有定义？

**Comment by chunyisong** [comment]
> 这里self.conv2没有定义？

在26行就出错了，跟conv2没关系
