### ISSUE TITLE
dynamic_lstm如何输入高维数据

### ISSUE THREAD

**Issue by YelZhang** [PaddlePaddle/Paddle#22331]
想使用dynamic_lstm对不定长序列做预测，序列每个pos是一个高维特征list，形如：
[ [1,2],    [1.2,2.1],   [1.3,2.5], ....]  
输入这一段要怎么实现

keras的写法很简单：model_2.add(LSTM(dim, activation='relu',input_shape=(n_steps, n_features)))

**Comment by YelZhang** [comment]
使用lod tensor后，报错是这样
PaddleCheckError: Expected lods.size() == 1UL, but received lods.size():2 != 1UL:1.
Only support one level sequence now
有什么解决方案吗

**Comment by frankwhzhang** [comment]
方便提供下完整代码吗

**Comment by frankwhzhang** [comment]
可以参考官方文档实例https://www.paddlepaddle.org.cn/documentation/docs/zh/api_cn/layers_cn/dynamic_lstm_cn.html#dynamic-lstm

**Comment by YelZhang** [comment]
> 方便提供下完整代码吗

dynamic lstm不支持lodlevel=2
