### ISSUE TITLE
飞桨轻量级目标检测挑战赛，评分模型时异常

### ISSUE THREAD

**Issue by tangbozhang** [PaddlePaddle/Paddle#22355]
用coco数据集、shufflenetv2-ssd，也就是轻量级竞赛里的内容，epoch_num =8 或10，训练出的模型，使用score.py评分时报内存异常，提交到百度后台大概半小时左右可以出成绩（之前正常模型十几分钟），异常截图如下。同样代码和数据epoch_num=1训练出的模型评分正常。
aistudio（paddle 1.5.0）和本地（1.6.1）都出。

![QQ图片20200117152008](https://user-images.githubusercontent.com/53244607/72595768-87acd900-3945-11ea-871f-5a1d5be39f5f.jpg)
![image](https://user-images.githubusercontent.com/53244607/72595856-b925a480-3945-11ea-981c-5c4c560aa5cb.png)

**Comment by mapingshuo** [comment]
请联系组委会工作人员，邮箱zhangshuxia01@baidu.com
