### ISSUE TITLE
paddle 1.6.3 fill_constant函数 dtpye 参数文档和实际校验不一致

### ISSUE THREAD

**Issue by xiangyubo** [PaddlePaddle/Paddle#22383]
paddle 1.6.3版本中，fill_constant函数的参数dtype，类型校验和文档描述的不一致。文档描述的可以是 np.dtype，但实际校验的时候却不认这个类型。

**Comment by heavengate** [comment]
感谢反馈，我们确认修复下~

**Comment by luotao1** [comment]
close due to #22386
