### ISSUE TITLE
激活paddle环境失败

### ISSUE THREAD

**Issue by ahsdx** [PaddlePaddle/Paddle#22392]
python版本是3.7.3
因为我想通过conda方式来安装，按照飞桨官网安装教程，是先在anaconda命令行输入，
`conda create -n paddle_env python=3.7`
结果出错，出错信息见下面
`# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "D:\Anaconda3\lib\site-packages\conda\exceptions.py", line 1074, in __call__
        return func(*args, **kwargs)
      File "D:\Anaconda3\lib\site-packages\conda\cli\main.py", line 84, in _main
        exit_code = do_call(args, p)
      File "D:\Anaconda3\lib\site-packages\conda\cli\conda_argparse.py", line 82, in do_call
        exit_code = getattr(module, func_name)(args, parser)
      File "D:\Anaconda3\lib\site-packages\conda\cli\main_create.py", line 37, in execute
        install(args, parser, 'create')
      File "D:\Anaconda3\lib\site-packages\conda\cli\install.py", line 116, in install
        if context.use_only_tar_bz2:
      File "D:\Anaconda3\lib\site-packages\conda\base\context.py", line 666, in use_only_tar_bz2
        import conda_package_handling.api
      File "D:\Anaconda3\lib\site-packages\conda_package_handling\api.py", line 3, in <module>
        from libarchive.exception import ArchiveError as _LibarchiveArchiveError
      File "D:\Anaconda3\lib\site-packages\libarchive\__init__.py", line 1, in <module>
        from .entry import ArchiveEntry
      File "D:\Anaconda3\lib\site-packages\libarchive\entry.py", line 6, in <module>
        from . import ffi
      File "D:\Anaconda3\lib\site-packages\libarchive\ffi.py", line 48, in <module>
        libarchive = ctypes.cdll.LoadLibrary(libarchive_path)
      File "D:\Anaconda3\lib\ctypes\__init__.py", line 434, in LoadLibrary
        return self._dlltype(name)
      File "D:\Anaconda3\lib\ctypes\__init__.py", line 356, in __init__
        self._handle = _dlopen(self._name, mode)
    OSError: [WinError 126] 找不到指定的模块。

`$ D:\Anaconda3\Scripts\conda-script.py create -n paddle_env python=3.7`

  environment variables:
                 CIO_TEST=<not set>
        CONDA_DEFAULT_ENV=base
                CONDA_EXE=D:\Anaconda3\condabin\..\Scripts\conda.exe
               CONDA_EXES="D:\Anaconda3\condabin\..\Scripts\conda.exe"
             CONDA_PREFIX=D:\Anaconda3
    CONDA_PROMPT_MODIFIER=(base)
         CONDA_PYTHON_EXE=D:\Anaconda3\python.exe
               CONDA_ROOT=D:\Anaconda3
              CONDA_SHLVL=1
                CUDA_PATH=C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.0
                 HOMEPATH=\Users\25895
          NVTOOLSEXT_PATH=C:\Program Files\NVIDIA Corporation\NvToolsExt\
                     PATH=D:\Anaconda3;D:\Anaconda3\Library\mingw-w64\bin;D:\Anaconda3\Library\u
                          sr\bin;D:\Anaconda3\Library\bin;D:\Anaconda3\Scripts;D:\Anaconda3\bin;
                          D:\Anaconda3;D:\Anaconda3\Library\mingw-w64\bin;D:\Anaconda3\Library\u
                          sr\bin;D:\Anaconda3\Library\bin;D:\Anaconda3\Scripts;D:\Anaconda3\bin;
                          D:\Anaconda3\condabin;C:\Program Files\NVIDIA GPU Computing
                          Toolkit\CUDA\v10.0\bin;C:\Program Files\NVIDIA GPU Computing Toolkit\C
                          UDA\v10.0\libnvvp;C:\windows\system32;C:\windows;C:\windows\System32\W
                          bem;C:\windows\System32\WindowsPowerShell\v1.0;C:\windows\System32\Ope
                          nSSH;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program
                          Files\NVIDIA GPU Computing Toolkit\CUDA\v10.0\include;C:\Program
                          Files\NVIDIA GPU Computing Toolkit\CUDA\v10.0\lib;C:\Program
                          Files\NVIDIA GPU Computing Toolkit\CUDA\v10.0\extras\CUPTI\libx64;D:\A
                          naconda3;D:\Anaconda3\Library\mingw-w64\bin;D:\Anaconda3\Library\usr\b
                          in;D:\Anaconda3\Library\bin;D:\Anaconda3\Scripts;D:\Python\Scripts;D:\
                          Python;D:\Python37\Scripts;D:\Python37;C:\Users\25895\AppData\Local\Mi
                          crosoft\WindowsApps
             PSMODULEPATH=C:\Program Files\WindowsPowerShell\Modules;C:\windows\system32\Windows
                          PowerShell\v1.0\Modules
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>

     active environment : base
    active env location : D:\Anaconda3
            shell level : 1
       user config file : C:\Users\25895\.condarc
 populated config files : C:\Users\25895\.condarc
          conda version : 4.7.12
    conda-build version : 3.18.8
         python version : 3.7.3.final.0
       virtual packages : __cuda=10.1
       base environment : D:\Anaconda3  (writable)
           channel URLs : https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/Paddle/win-64
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/Paddle/noarch
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/win-64
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/noarch
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/win-64
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : D:\Anaconda3\pkgs
                          C:\Users\25895\.conda\pkgs
                          C:\Users\25895\AppData\Local\conda\conda\pkgs
       envs directories : D:\Anaconda3\envs
                          C:\Users\25895\.conda\envs
                          C:\Users\25895\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/4.7.12 requests/2.22.0 CPython/3.7.3 Windows/10 Windows/10.0.18362
          administrator : False
             netrc file : None
           offline mode : False

An unexpected error has occurred. Conda has prepared the above report.

If submitted, this report will be used by core maintainers to improve
future releases of conda.
Would you like conda to send this report to the core maintainers?

[y/N]:`
然后我尝试激活paddle环境，失败。
后面尝试加入anconda的环境变量，还是报错

**Comment by OliverLPH** [comment]
看起来是在 `conda create -n paddle_env python=3.7` 这一步出错的
这里是在用conda创建python3.7的虚拟环境，所以不是Paddle的问题。

如果Anaconda是安装的可视化版本
![image](https://user-images.githubusercontent.com/14963836/72873574-1bf2b380-3d2b-11ea-9e10-b4bce77d050d.png)
可以先在Anaconda的的界面里试下能不能创建虚拟环境，如果此处也不行，建议重新安装下Anaconda

**Comment by ahsdx** [comment]
好的，谢谢



---原始邮件---
发件人: "Peihan"<notifications@github.com&gt;
发送时间: 2020年1月22日(周三) 下午3:24
收件人: "PaddlePaddle/Paddle"<Paddle@noreply.github.com&gt;;
抄送: "Author"<author@noreply.github.com&gt;;"ahsdx"<2589561091@qq.com&gt;;
主题: Re: [PaddlePaddle/Paddle] 激活paddle环境失败 (#22392)



看起来是在 conda create -n paddle_env python=3.7 这一步出错的
 这里是在用conda创建python3.7的虚拟环境，所以不是Paddle的问题。
 
如果Anaconda是安装的可视化版本
 
 可以先在Anaconda的的界面里试下能不能创建虚拟环境，如果此处也不行，建议重新安装下Anaconda
