### ISSUE TITLE
jupyter notebook导入paddle出错（通过conda进行安装的paddle）

### ISSUE THREAD

**Issue by ahsdx** [PaddlePaddle/Paddle#22397]
建立issue时，为快速解决问题，请您根据使用情况给出如下信息：
- 版本、环境信息：
    1）PaddlePaddle版本：1.6.3.post107
    2）CPU：i5-9300H，CUDA-7.4和CUDNN-10.0
    4）系统环境：win10家庭中文版、Python3.7
- 安装方式信息：
1）conda安装            
- 复现信息：通过conda安装后在jupyter notebook配置好paddle的python环境后，输入代码
`import paddle`，然后报错
- 问题描述：已经通过conda安装paddle成功了（在anaconda prompt已经测试过，我的操作系统是win10家庭版），然后在jupyter notebook配置好paddle的python环境后，输入代码
import paddle
报错了，报错信息如下：

D:\Anaconda3\envs\paddle_env\lib\site-packages\numpy_init_.py:140: UserWarning: mkl-service package failed to import, therefore Intel(R) MKL initialization ensuring its correct out-of-the box operation under condition when Gnu OpenMP had already been loaded by Python process is not assured. Please install mkl-service package, see http://github.com/IntelPython/mkl-service
from . import _distributor_init

ImportError Traceback (most recent call last)
in
----> 1 import paddle

D:\Anaconda3\envs\paddle_env\lib\site-packages\paddle_init_.py in
15 from paddle.check_import_scipy import check_import_scipy
16
---> 17 check_import_scipy(os.name)
18
19 try:

D:\Anaconda3\envs\paddle_env\lib\site-packages\paddle\check_import_scipy.py in check_import_scipy(OsName)
25 raise ImportError(
26 print_info +
---> 27 "\nplease download visual C++ Redistributable for vs 2015, https://www.microsoft.com/en-us/download/details.aspx?id=48145"
28 )
29 return

ImportError:

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy c-extensions failed.

Try uninstalling and reinstalling numpy.

If you have already done that, then:

Check that you expected to use Python3.7 from "D:\Anaconda3\envs\paddle_env\python.exe",
and that you have no directories in your PATH or PYTHONPATH that can
interfere with the Python and numpy version "1.18.1" you're trying to use.
If (1) looks fine, you can open a new issue at
https://github.com/numpy/numpy/issues. Please include details on:
how you installed Python
how you installed numpy
your operating system
whether or not you have multiple versions of Python installed
if you built from source, your compiler versions and ideally a build log
If you're working with a numpy git repository, try git clean -xdf
(removes all files not under version control) and rebuild numpy.

Note: this error has many possible causes, so please don't comment on
an existing issue about this - open a new one instead.

Original error was: DLL load failed: 找不到指定的模块。

please download visual C++ Redistributable for vs 2015, https://www.microsoft.com/en-us/download/details.aspx?id=48145

我已经安装报错信息下载了vs 2015：vc_redist.x86.exe和vc_redist.x64.exe，并都进行了安装，然后重启，但是打开jupyter notebook ，还是出现如上一样的错误，这个怎么办啊？已经搞了一天了

**Comment by rudaoshi** [comment]
mac下的ipython 一样无法import

```python
In [1]: import paddle.fluid as fluid
ERROR: unknown command line flag 'c'
```

然后整个ipython会退出。 

版本号 1.6.3 

python shell 无此问题。

**Comment by SunGaofeng** [comment]
> mac下的ipython 一样无法import
> 
> ```python
> In [1]: import paddle.fluid as fluid
> ERROR: unknown command line flag 'c'
> ```
> 
> 然后整个ipython会退出。
> 
> 版本号 1.6.3
> 
> python shell 无此问题。

Mac下用命令行可以正常使用？可以检查下mac端ipython里面用到的python路径和版本，是否是安装了paddle的

**Comment by ahsdx** [comment]
好的，谢谢！



---原始邮件---
发件人: "SunGaofeng"<notifications@github.com&gt;
发送时间: 2020年2月4日(周二) 下午3:06
收件人: "PaddlePaddle/Paddle"<Paddle@noreply.github.com&gt;;
抄送: "Author"<author@noreply.github.com&gt;;"ahsdx"<2589561091@qq.com&gt;;
主题: Re: [PaddlePaddle/Paddle] jupyter notebook导入paddle出错（通过conda进行安装的paddle） (#22397)


 
mac下的ipython 一样无法import
 In [1]: import paddle.fluid as fluid ERROR: unknown command line flag 'c'
 
然后整个ipython会退出。
 
版本号 1.6.3
 
python shell 无此问题。
  
Mac下用命令行可以正常使用？可以检查下mac端ipython里面用到的python路径和版本，是否是安装了paddle的

**Comment by SunGaofeng** [comment]
> 建立issue时，为快速解决问题，请您根据使用情况给出如下信息：
> 
> * 版本、环境信息：
>      1）PaddlePaddle版本：1.6.3.post107
>      2）CPU：i5-9300H，CUDA-7.4和CUDNN-10.0
>      4）系统环境：win10家庭中文版、Python3.7
> * 安装方式信息：
>   1）conda安装
> * 复现信息：通过conda安装后在jupyter notebook配置好paddle的python环境后，输入代码
>   `import paddle`，然后报错
> * 问题描述：已经通过conda安装paddle成功了（在anaconda prompt已经测试过，我的操作系统是win10家庭版），然后在jupyter notebook配置好paddle的python环境后，输入代码
>   import paddle
>   报错了，报错信息如下：
> 
> D:\Anaconda3\envs\paddle_env\lib\site-packages\numpy_init_.py:140: UserWarning: mkl-service package failed to import, therefore Intel(R) MKL initialization ensuring its correct out-of-the box operation under condition when Gnu OpenMP had already been loaded by Python process is not assured. Please install mkl-service package, see [http://github.com/IntelPython/mkl-service](https://github.com/IntelPython/mkl-service)
> from . import _distributor_init
> 
> ImportError Traceback (most recent call last)
> in
> ----> 1 import paddle
> 
> D:\Anaconda3\envs\paddle_env\lib\site-packages\paddle_init_.py in
> 15 from paddle.check_import_scipy import check_import_scipy
> 16
> ---> 17 check_import_scipy(os.name)
> 18
> 19 try:
> 
> D:\Anaconda3\envs\paddle_env\lib\site-packages\paddle\check_import_scipy.py in check_import_scipy(OsName)
> 25 raise ImportError(
> 26 print_info +
> ---> 27 "\nplease download visual C++ Redistributable for vs 2015, https://www.microsoft.com/en-us/download/details.aspx?id=48145"
> 28 )
> 29 return
> 
> ImportError:
> 
> IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!
> 
> Importing the numpy c-extensions failed.
> 
> Try uninstalling and reinstalling numpy.
> 
> If you have already done that, then:
> 
> Check that you expected to use Python3.7 from "D:\Anaconda3\envs\paddle_env\python.exe",
> and that you have no directories in your PATH or PYTHONPATH that can
> interfere with the Python and numpy version "1.18.1" you're trying to use.
> If (1) looks fine, you can open a new issue at
> https://github.com/numpy/numpy/issues. Please include details on:
> how you installed Python
> how you installed numpy
> your operating system
> whether or not you have multiple versions of Python installed
> if you built from source, your compiler versions and ideally a build log
> If you're working with a numpy git repository, try git clean -xdf
> (removes all files not under version control) and rebuild numpy.
> 
> Note: this error has many possible causes, so please don't comment on
> an existing issue about this - open a new one instead.
> 
> Original error was: DLL load failed: 找不到指定的模块。
> 
> please download visual C++ Redistributable for vs 2015, https://www.microsoft.com/en-us/download/details.aspx?id=48145
> 
> 我已经安装报错信息下载了vs 2015：vc_redist.x86.exe和vc_redist.x64.exe，并都进行了安装，然后重启，但是打开jupyter notebook ，还是出现如上一样的错误，这个怎么办啊？已经搞了一天了

windows里面的问题看起来像是scipy的问题，能够先检查下scipy是否安装正确吗？

**Comment by ahsdx** [comment]
谢谢，我已经解决了，安装成功了。🤗



---原始邮件---
发件人: "SunGaofeng"<notifications@github.com&gt;
发送时间: 2020年2月4日(周二) 下午3:19
收件人: "PaddlePaddle/Paddle"<Paddle@noreply.github.com&gt;;
抄送: "Author"<author@noreply.github.com&gt;;"ahsdx"<2589561091@qq.com&gt;;
主题: Re: [PaddlePaddle/Paddle] jupyter notebook导入paddle出错（通过conda进行安装的paddle） (#22397)


 
建立issue时，为快速解决问题，请您根据使用情况给出如下信息：
  
版本、环境信息：
 &nbsp; &nbsp;1）PaddlePaddle版本：1.6.3.post107
 &nbsp; &nbsp;2）CPU：i5-9300H，CUDA-7.4和CUDNN-10.0
 &nbsp; &nbsp;4）系统环境：win10家庭中文版、Python3.7 

安装方式信息：
 1）conda安装 

复现信息：通过conda安装后在jupyter notebook配置好paddle的python环境后，输入代码
 import paddle，然后报错 

问题描述：已经通过conda安装paddle成功了（在anaconda prompt已经测试过，我的操作系统是win10家庭版），然后在jupyter notebook配置好paddle的python环境后，输入代码
 import paddle
 报错了，报错信息如下： 
 
D:\Anaconda3\envs\paddle_env\lib\site-packages\numpy_init_.py:140: UserWarning: mkl-service package failed to import, therefore Intel(R) MKL initialization ensuring its correct out-of-the box operation under condition when Gnu OpenMP had already been loaded by Python process is not assured. Please install mkl-service package, see http://github.com/IntelPython/mkl-service
 from . import _distributor_init
 
ImportError Traceback (most recent call last)
 in
 ----&gt; 1 import paddle
 
D:\Anaconda3\envs\paddle_env\lib\site-packages\paddle_init_.py in
 15 from paddle.check_import_scipy import check_import_scipy
 16
 ---&gt; 17 check_import_scipy(os.name)
 18
 19 try:
 
D:\Anaconda3\envs\paddle_env\lib\site-packages\paddle\check_import_scipy.py in check_import_scipy(OsName)
 25 raise ImportError(
 26 print_info +
 ---&gt; 27 "\nplease download visual C++ Redistributable for vs 2015, https://www.microsoft.com/en-us/download/details.aspx?id=48145"
 28 )
 29 return
 
ImportError:
 
IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!
 
Importing the numpy c-extensions failed.
 
Try uninstalling and reinstalling numpy.
 
If you have already done that, then:
 
Check that you expected to use Python3.7 from "D:\Anaconda3\envs\paddle_env\python.exe",
 and that you have no directories in your PATH or PYTHONPATH that can
 interfere with the Python and numpy version "1.18.1" you're trying to use.
 If (1) looks fine, you can open a new issue at
 https://github.com/numpy/numpy/issues. Please include details on:
 how you installed Python
 how you installed numpy
 your operating system
 whether or not you have multiple versions of Python installed
 if you built from source, your compiler versions and ideally a build log
 If you're working with a numpy git repository, try git clean -xdf
 (removes all files not under version control) and rebuild numpy.
 
Note: this error has many possible causes, so please don't comment on
 an existing issue about this - open a new one instead.
 
Original error was: DLL load failed: 找不到指定的模块。
 
please download visual C++ Redistributable for vs 2015, https://www.microsoft.com/en-us/download/details.aspx?id=48145
 
我已经安装报错信息下载了vs 2015：vc_redist.x86.exe和vc_redist.x64.exe，并都进行了安装，然后重启，但是打开jupyter notebook ，还是出现如上一样的错误，这个怎么办啊？已经搞了一天了
  
windows里面的问题看起来像是scipy的问题，能够先检查下scipy是否安装正确吗？

**Comment by SunGaofeng** [comment]
> 谢谢，我已经解决了，安装成功了。🤗
> […](#)

好的，请问您具体是怎么解决的？我们想统计下放到FAQ里面

**Comment by ahsdx** [comment]
我是通过conda安装的，原来是直接进入jupyter notebook，然后将kernel切换成paddle，但是导入paddle还是错误。后面我就先在anaconda prompt里输入activate paddle_env，先进入虚拟环境，然后再输入jupyter notebook，再将kernel切换成paddle，然后导入paddle就成功了。------------------ 原始邮件 ------------------
发件人: "SunGaofeng"<notifications@github.com>
发送时间: 2020年2月4日(星期二) 晚上6:10
收件人: "PaddlePaddle/Paddle"<Paddle@noreply.github.com>;
抄送: "ahsdx"<2589561091@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [PaddlePaddle/Paddle] jupyter notebook导入paddle出错（通过conda进行安装的paddle） (#22397)


 
谢谢，我已经解决了，安装成功了。
 …
  
好的，请问您具体是怎么解决的？我们想统计下放到FAQ里面
 
&mdash;

**Comment by SunGaofeng** [comment]
> 我是通过conda安装的，原来是直接进入jupyter notebook，然后将kernel切换成paddle，但是导入paddle还是错误。后面我就先在anaconda prompt里输入activate paddle_env，先进入虚拟环境，然后再输入jupyter notebook，再将kernel切换成paddle，然后导入paddle就成功了。------------------ 原始邮件 ------------------ 发件人: "SunGaofeng"<notifications@github.com> 发送时间: 2020年2月4日(星期二) 晚上6:10 收件人: "PaddlePaddle/Paddle"<Paddle@noreply.github.com>; 抄送: "ahsdx"<2589561091@qq.com>;"Author"<author@noreply.github.com>; 主题: Re: [PaddlePaddle/Paddle] jupyter notebook导入paddle出错（通过conda进行安装的paddle） (#22397) 谢谢，我已经解决了，安装成功了。 … 好的，请问您具体是怎么解决的？我们想统计下放到FAQ里面 &mdash; You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

这是mac下面的解决方案吧，win10下面安装有问题，后来解决了吗？

**Comment by ahsdx** [comment]
我就在win10里装了paddle啊，我没有苹果笔记本电脑呢，提的问题也都是win10的😮



---原始邮件---
发件人: "SunGaofeng"<notifications@github.com&gt;
发送时间: 2020年2月4日(周二) 晚上7:58
收件人: "PaddlePaddle/Paddle"<Paddle@noreply.github.com&gt;;
抄送: "Author"<author@noreply.github.com&gt;;"ahsdx"<2589561091@qq.com&gt;;
主题: Re: [PaddlePaddle/Paddle] jupyter notebook导入paddle出错（通过conda进行安装的paddle） (#22397)


 
我是通过conda安装的，原来是直接进入jupyter notebook，然后将kernel切换成paddle，但是导入paddle还是错误。后面我就先在anaconda prompt里输入activate paddle_env，先进入虚拟环境，然后再输入jupyter notebook，再将kernel切换成paddle，然后导入paddle就成功了。------------------ 原始邮件 ------------------ 发件人: "SunGaofeng"notifications@github.com 发送时间: 2020年2月4日(星期二) 晚上6:10 收件人: "PaddlePaddle/Paddle"Paddle@noreply.github.com; 抄送: "ahsdx"2589561091@qq.com;"Author"author@noreply.github.com; 主题: Re: [PaddlePaddle/Paddle] jupyter notebook导入paddle出错（通过conda进行安装的paddle） (#22397) 谢谢，我已经解决了，安装成功了。 … 好的，请问您具体是怎么解决的？我们想统计下放到FAQ里面 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.
  
这是mac下面的解决方案吧，win10下面安装有问题，后来解决了吗？

**Comment by stillwaterman** [comment]
我安装完PaddlePaddle后运行paddleseg报错，please download visual C++ Redistributable for vs 2015，Importing the numpy C-extensions failed. 用conda装的。事实上，我电脑有visual C++ Redistributable for vs 2015. 在pycharm中有这个问题，但在anaconda prompt运行没有这个问题
