### ISSUE TITLE
[bug] 在调用 matmul(x,y) 时碰到错误 Input(Y) of MatMulOp should not be null

### ISSUE THREAD

**Issue by rudaoshi** [PaddlePaddle/Paddle#22398]
x 和 y 的创建方式 
x = fluid.layers.data(name=name, shape=shape, dtype=dtype, append_batch_size=False)

y = fluid.layers.create_parameter(shape=value.shape, dtype=dtype,
                          default_initializer=fluid.initializer.NumpyArrayInitializer(value))

但是，x 和 y 不在同一个Python函数中创建。 

根据这个错误，看起来是contex 丢失了 input Y 的信息？

在什么情况下会导致这个问题？如何解决？

**Comment by rudaoshi** [comment]
从源码看，inferShape 需要从context 来读取input信息？

不太明白为什么需要这样处理。直接传入Input信息不是更加直接？

**Comment by rudaoshi** [comment]
x 和 y是同一个block

**Comment by rudaoshi** [comment]
复现程序。 改名字就出错。 

```python

import paddle.fluid as fluid
import numpy
import pytest

def test_matmul():
    
    dtype = "float32"
    x = fluid.layers.data(name="x", shape=[None, 100], dtype=dtype, append_batch_size=False)

    weight = fluid.layers.uniform_random((100, 32), dtype)

    out = fluid.layers.matmul(x, weight)

    with pytest.raises(Exception):

        weight.name = "weight"
        out2 = fluid.layers.matmul(x, weight)

```

**Comment by SunGaofeng** [comment]
这个应该是在python端修改名字之后，c++端创建的变量名字还是以前的，导致按新的名字找不到变量了。不建议手动修改变量的名字
