### ISSUE TITLE
import paddle出错

### ISSUE THREAD

**Issue by ahsdx** [PaddlePaddle/Paddle#22395]
已经通过conda安装paddle成功了（在anaconda prompt已经测试过，我的操作系统是win10家庭版），然后在jupyter notebook配置好paddle的python环境后，输入代码
`import paddle`
报错了，报错信息如下：

> D:\Anaconda3\envs\paddle_env\lib\site-packages\numpy\__init__.py:140: UserWarning: mkl-service package failed to import, therefore Intel(R) MKL initialization ensuring its correct out-of-the box operation under condition when Gnu OpenMP had already been loaded by Python process is not assured. Please install mkl-service package, see http://github.com/IntelPython/mkl-service
  from . import _distributor_init

> ---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-5b4954d53387> in <module>
----> 1 import paddle

D:\Anaconda3\envs\paddle_env\lib\site-packages\paddle\__init__.py in <module>
     15 from paddle.check_import_scipy import check_import_scipy
     16 
---> 17 check_import_scipy(os.name)
     18 
     19 try:

D:\Anaconda3\envs\paddle_env\lib\site-packages\paddle\check_import_scipy.py in check_import_scipy(OsName)
     25                 raise ImportError(
     26                     print_info +
---> 27                     "\nplease download visual C++ Redistributable for vs 2015, https://www.microsoft.com/en-us/download/details.aspx?id=48145"
     28                 )
     29     return

ImportError: 

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy c-extensions failed.
- Try uninstalling and reinstalling numpy.
- If you have already done that, then:
  1. Check that you expected to use Python3.7 from "D:\Anaconda3\envs\paddle_env\python.exe",
     and that you have no directories in your PATH or PYTHONPATH that can
     interfere with the Python and numpy version "1.18.1" you're trying to use.
  2. If (1) looks fine, you can open a new issue at
     https://github.com/numpy/numpy/issues.  Please include details on:
     - how you installed Python
     - how you installed numpy
     - your operating system
     - whether or not you have multiple versions of Python installed
     - if you built from source, your compiler versions and ideally a build log

- If you're working with a numpy git repository, try `git clean -xdf`
  (removes all files not under version control) and rebuild numpy.

Note: this error has many possible causes, so please don't comment on
an existing issue about this - open a new one instead.

Original error was: DLL load failed: 找不到指定的模块。

please download visual C++ Redistributable for vs 2015, https://www.microsoft.com/en-us/download/details.aspx?id=48145

我已经安装报错信息下载了vs 2015：vc_redist.x86.exe和vc_redist.x64.exe，并都进行了安装，然后重启，但是打开jupyter notebook ，还是出现如上一样的错误，这个怎么办啊？已经搞了一天了

**Comment by moollok** [comment]
楼主解决了吗
