### ISSUE TITLE
安装错误

### ISSUE THREAD

**Issue by jackeytanghk** [PaddlePaddle/Paddle#22411]
为使您的问题得到快速解决，在建立Issue前，请您先通过如下方式搜索是否有相似问题:【搜索issue关键字】【使用labels筛选】【官方文档】

建立issue时，为快速解决问题，请您根据使用情况给出如下信息：
- 标题：请包含关键词“安装错误”/“编译错误”，例如“Mac编译错误”
- 版本、环境信息：
    1）PaddlePaddle版本：请提供您的PaddlePaddle版本号（如1.1）或CommitID
    2）CPU：请提供CPU型号，MKL/OpenBlas/MKLDNN/等数学库的使用情况
    3）GPU：请提供GPU型号，CUDA和CUDNN版本号
    4）系统环境：请说明系统类型、版本（如Mac OS 10.14）、Python版本
- 安装方式信息：
1）pip安装/docker安装
2）本地编译：请提供cmake命令，编译命令
3）docker编译：请提供docker镜像，编译命令            
  特殊环境请注明：如离线安装等
- 复现信息：如为报错，请给出复现环境、复现步骤
- 问题描述：请详细描述您的问题，同步贴出报错信息、日志/代码关键片段

### 根据官网安装指南(conda安装)，我的python版本为3.7，但是所有网站上python3的命令都不生效，python2的命令可以执行。使用命令安装，conda install paddlepaddle，显示# All requested packages already installed.。 在python下使用命令 import paddle.fluid，报错。具体信息见下。
CPU： inter(R) core(TM) i5-8265U CPU @1.6GHZ
操作系统：Windows X

但同时使用conda jupyter 输入import paddle.fluid
paddle.fluid.install_check.run_check()
显示如下信息
Running Verify Fluid Program ... 
Your Paddle Fluid works well on SINGLE GPU or CPU.
Your Paddle Fluid works well on MUTIPLE GPU or CPU.
Your Paddle Fluid is installed successfully! Let's start deep Learning with Paddle Fluid now

(base) C:\Users\aic>where python
D:\Anaconda\python.exe
C:\Users\aic\AppData\Local\Microsoft\WindowsApps\python.exe

(base) C:\Users\aic>python --version
Python 3.7.3

(base) C:\Users\aic>python3 --version

(base) C:\Users\aic>python -c "import platform;print(platform.architecture()[0]);print(platform.machine())"
64bit
AMD64

(base) C:\Users\aic>python3 -c "import platform;print(platform.architecture()[0]);print(platform.machine())"

(base) C:\Users\aic>conda install paddlepaddle
Collecting package metadata (repodata.json): done
Solving environment: done

# All requested packages already installed.

(base) C:\Users\aic>python
Python 3.7.3 (default, Mar 27 2019, 17:13:21) [MSC v.1915 64 bit (AMD64)] :: Anaconda, Inc. on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import paddle.fluid
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\Anaconda\lib\site-packages\paddle\fluid\__init__.py", line 35, in <module>
    from . import framework
  File "D:\Anaconda\lib\site-packages\paddle\fluid\framework.py", line 33, in <module>
    from .proto import framework_pb2
  File "D:\Anaconda\lib\site-packages\paddle\fluid\proto\framework_pb2.py", line 11, in <module>
    from google.protobuf import descriptor_pb2
  File "D:\Anaconda\lib\site-packages\google\protobuf\descriptor_pb2.py", line 1840, in <module>
    '__module__' : 'google.protobuf.descriptor_pb2'
TypeError: expected bytes, Descriptor found

**Comment by zhhsplendid** [comment]
从报错信息上来看，是protobuf的错，可能是以下原因之一：

1.protobuf版本过低
2.protobuf支持py2,需要装py3

能否请您试试安装 protobuf-py3 和 upgrade protobuf ？

**Comment by zhaowenqian666** [comment]
> 从报错信息上来看，是protobuf的错，可能是以下原因之一：
> 
> 1.protobuf版本过低
> 2.protobuf支持py2,需要装py3
> 
> 能否请您试试安装 protobuf-py3 和 upgrade protobuf ？

请问gpu版的paddle 1.8.1  应该配套哪个protobuf版本？我是突然有一天不能用了，一周前还是好好的，我目前protobuf的版本是protobuf_py3-2.5.1.dist-info    protobuf-3.6.1-py3.6.egg-info   protobuf-3.12.1.dist-info

**Comment by zhaowenqian666** [comment]
> 从报错信息上来看，是protobuf的错，可能是以下原因之一：
> 
> 1.protobuf版本过低
> 2.protobuf支持py2,需要装py3
> 
> 能否请您试试安装 protobuf-py3 和 upgrade protobuf ？

两个都试过了，不得行

**Comment by lyw615** [comment]
@zhaowenqian666 This problem solved by uninstalling  protobuf from python environment  and installing it by conda. Besides, there are two versions of  protobuf in my environment , which is found after twice uninstallations.  So  the problem may caused by improper installation of protobuf.
