### ISSUE TITLE
【导入paddle模块错误:DLL load failed:找不到指定的程序】

### ISSUE THREAD

**Issue by DMWillie** [PaddlePaddle/Paddle#22412]
为使您的问题得到快速解决，在建立Issue前，请您先通过如下方式搜索是否有相似问题:【搜索issue关键字】【使用labels筛选】【官方文档】

建立issue时，为快速解决问题，请您根据使用情况给出如下信息：
- 标题：请包含关键词“安装错误”/“编译错误”，例如“Mac编译错误”
- 版本、环境信息：
    1）PaddlePaddle版本：请提供您的PaddlePaddle版本号（如1.1）或CommitID
    2）CPU：请提供CPU型号，MKL/OpenBlas/MKLDNN/等数学库的使用情况
    3）GPU：请提供GPU型号，CUDA和CUDNN版本号
    4）系统环境：请说明系统类型、版本（如Mac OS 10.14）、Python版本
- 安装方式信息：
1）pip安装/docker安装
2）本地编译：请提供cmake命令，编译命令
3）docker编译：请提供docker镜像，编译命令            
  特殊环境请注明：如离线安装等
- 复现信息：如为报错，请给出复现环境、复现步骤
- 问题描述：请详细描述您的问题，同步贴出报错信息、日志/代码关键片段

Thank you for contributing to PaddlePaddle.
Before submitting the issue, you could search issue in Github in case that there was a similar issue submitted or resolved before.
If there is no solution,please make sure that this is an installation issue including the following details:
**System information**
-PaddlePaddle version （eg.1.1）or CommitID
-CPU: including CPUMKL/OpenBlas/MKLDNN version
-GPU: including CUDA/CUDNN version
-OS Platform (eg. Mac OS 10.14)
-Python version
- Install method: pip install/install with docker/build from source(without docker)/build within docker
- Other special cases that you think may be related to this problem, eg. offline install, special internet condition   
**To Reproduce**
Steps to reproduce the behavior
**Describe your current behavior**
**Code to reproduce the issue**
**Other info / logs**

**Comment by DMWillie** [comment]
安装版本及环境：win10-AMD64位/python版本3.6/pip版本：19.3.1/CPU版本
问题：安装paddle成功，但是导入import paddle.fluid报错DLL load failed错误
![导入paddle报错](https://user-images.githubusercontent.com/33515898/73602608-f3cc4580-45b1-11ea-869e-b3b720ea3147.png)
百度按照之前有人遇到类似的问题链接：http://ai.baidu.com/forum/topic/show/943038?&pageNo=1
但我也没有找到core.pyd文件，只有以下这两个pyd文件
![paddle依赖文件缺失](https://user-images.githubusercontent.com/33515898/73602602-e747ed00-45b1-11ea-96c5-56aa00e853ea.PNG)
而且打开core_avx.pyd查看缺失的dll文件好多。。。怎么解决
![paddle依赖缺失](https://user-images.githubusercontent.com/33515898/73602609-f464dc00-45b1-11ea-84e6-715a39b8eaa9.PNG)

**Comment by sidneyz139** [comment]
I encounter the same. is there any package which associated with AVX need install?
my environment is LENOVO T530, WIN10 64BIT, Visual Stidio 2019, Python3.7.6, with CUDA 10.0/10.2, cuDNN 7.6.3
Intel i7 3720QM, Intel HD graphics 4000, and NVIIDA NVS 5400M

**Comment by sidneyz139** [comment]
我的机器明明是IntelCPU, 但plateform 显示是AMD64, 这个是问题吗？
![image](https://user-images.githubusercontent.com/53903688/75130564-072e8480-570a-11ea-91a1-75de931b3ae5.png)

**Comment by sidneyz139** [comment]
Intel i7 3720QM支持AVX, 不支持AVX2；需要安装什么AVX支持吗？怎么安装？
另外，我机器上有GPU，安装的paddle版本也是paddlepaddle-gpu, 怎么运行 import paddle.fluid时，会报 AVX DLL 无法加载？

![image](https://user-images.githubusercontent.com/53903688/75130798-224dc400-570b-11ea-8d35-5e0efb76b428.png)
![image](https://user-images.githubusercontent.com/53903688/75130825-3bef0b80-570b-11ea-9f65-ea4f127fa4e3.png)
