### ISSUE TITLE
daynamic_gru训练过程中出现tensor不匹配问题

### ISSUE THREAD

**Issue by mtchen2016** [PaddlePaddle/Paddle#22425]
dynamic_gru算子要求：
input的形状为[序列长度， D*3]
h_0的形状为[序列个数， D]

但是【  https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/fluid/layers/rnn.py   】
里第1839行的dynamic_gru相关代码却要求：序列长度 == 序列个数，这个是不是有问题呢？

**Comment by MRXLT** [comment]
input是lodtensor，input.shape[0]代表的是batch size，也就是序列个数
