### ISSUE TITLE
parameters在经过训练后的shape不一致

### ISSUE THREAD

**Issue by cxysteven** [PaddlePaddle/Paddle#2248]
在v2版本中
parameters = paddle.parameters.create(cost) , 在parameters经过训练后， parameters.get_shape(name)和parameters.get(name).shape
这两个shape是不一样的。
这样导致拷贝参数值（parameter作为拷贝目标）或者set的时候会出现问题。

**Comment by typhoonzero** [comment]
您好，可以补充下可以复现这个问题的代码片段么?方便排查以及fix这个问题。

**Comment by NHZlX** [comment]
I'll close the inactivate issue, and feel free to reopen it.

**Comment by liuhuiCNN** [comment]
@cxysteven 应该是对一维的数据 x 长度为m 变成了 [1 m]的格式
建议先 shape = paramters.get_shape(val)
然后 paramters.set(val.reshape(shape))
