### ISSUE TITLE
多机分布式运行时报错，ValueError: Operator "send" has not been registered.

### ISSUE THREAD

**Issue by jerryniu520126** [PaddlePaddle/Paddle#22501]
- 版本、环境信息：
    1）PaddlePaddle版本：1.6.3
    2）CPU：
![TIM截图20200207191558](https://user-images.githubusercontent.com/46663799/74025165-4eb0d300-49de-11ea-9fd1-45eab8493866.png)

    3）系统环境：Windows 10

- 训练信息
    1）多机，单卡

- 复现信息：
`#!/bin/bash

# start pserver0
python train.py \
    --train_data_path train.txt \
    --is_local 0 \
    --role pserver \
    --endpoints 127.0.0.1:6000,127.0.0.1:6001 \
    --current_endpoint 127.0.0.1:6000 \
    --trainers 2 \
    > pserver0.log 2>&1 &

# start pserver1
python train.py \
    --train_data_path train.txt \
    --is_local 0 \
    --role pserver \
    --endpoints 127.0.0.1:6000,127.0.0.1:6001 \
    --current_endpoint 127.0.0.1:6001 \
    --trainers 2 \
    > pserver1.log 2>&1 &

# start trainer0
python train.py \
    --train_data_path train.txt \
    --is_local 0 \
    --role trainer \
    --endpoints 127.0.0.1:6000,127.0.0.1:6001 \
    --trainers 2 \
    --trainer_id 0 \
    > trainer0.log 2>&1 &

# start trainer1
python train.py \
    --train_data_path train.txt\
    --is_local 0 \
    --role trainer \
    --endpoints 127.0.0.1:6000,127.0.0.1:6001 \
    --trainers 2 \
    --trainer_id 1 \
    > trainer1.log 2>&1 &
`
运行完这个以后出现如下报错信息：
`2020-02-06 20:36:59,184-WARNING: paddle.fluid.layers.create_py_reader_by_data() may be deprecated in the near future. Please use paddle.fluid.io.DataLoader.from_generator() instead.
2020-02-06 20:36:59,418-INFO: run dist training
Traceback (most recent call last):
  File "train.py", line 262, in <module>
    train()
  File "train.py", line 236, in train
    t.transpile(args.trainer_id, pservers=args.endpoints, trainers=args.trainers)
  File "D:\Anaconda3\envs\paddle_env\lib\site-packages\paddle\fluid\transpiler\distribute_transpiler.py", line 699, in transpile
    splited_grad_varname
  File "D:\Anaconda3\envs\paddle_env\lib\site-packages\paddle\fluid\framework.py", line 2506, in _insert_op
    op = Operator(block=self, desc=op_desc, *args, **kwargs)
  File "D:\Anaconda3\envs\paddle_env\lib\site-packages\paddle\fluid\framework.py", line 1788, in __init__
    proto = OpProtoHolder.instance().get_op_proto(type)
  File "D:\Anaconda3\envs\paddle_env\lib\site-packages\paddle\fluid\framework.py", line 1670, in get_op_proto
    raise ValueError("Operator \"%s\" has not been registered." % type)
ValueError: Operator "send" has not been registered.
`

**Comment by wangchaochaohu** [comment]
看报错信息是使用为注册的OP 请问下你在Windows下运行其他程序正常吗？

**Comment by jerryniu520126** [comment]
正常呀，之前在本地跑过一些paddlepaddle的房价预测和其他的demo都没问题，但是这是第一次跑分布式

**Comment by jerryniu520126** [comment]
> 看报错信息是使用为注册的OP 请问下你在Windows下运行其他程序正常吗？

正常呀，之前在本地跑过一些paddlepaddle的房价预测和其他的demo都没问题，但是这是第一次跑分布式

**Comment by wangchaochaohu** [comment]
请问下设置了http_proxy? 麻烦@wangjiawei04帮忙看下

**Comment by bjjwwang** [comment]
需要安装带分布式训练模式的的paddle版本， pip install只有单机版本的。
https://www.paddlepaddle.org.cn/install/doc/tables#%E5%A4%9A%E7%89%88%E6%9C%ACwhl%E5%8C%85%E5%88%97%E8%A1%A8-dev-11 
里面的cpu-mkl 下面的python版本选择一个wheel包安装好 ，例如python 27版本就
用pip install -U paddlepaddle-latest-cp27-cp27mu-linux_x86_64.whl

**Comment by jerryniu520126** [comment]
> 需要安装带分布式训练模式的的paddle版本， pip install只有单机版本的。
> https://www.paddlepaddle.org.cn/install/doc/tables#%E5%A4%9A%E7%89%88%E6%9C%ACwhl%E5%8C%85%E5%88%97%E8%A1%A8-dev-11
> 里面的cpu-mkl 下面的python版本选择一个wheel包安装好 ，例如python 27版本就
> 用pip install -U paddlepaddle-latest-cp27-cp27mu-linux_x86_64.whl


在Anaconda Prompt中，按您的指示运行了pip install -U paddlepaddle-latest-cp37-cp37m-linux_x86_64.whl
但是报错了，报错信息如下：

> ERROR: paddlepaddle-latest-cp37-cp37m-linux_x86_64.whl is not a supported wheel on this platform.

我一直使用的都是Python 3.7, paddlepaddle-latest-cp37-cp37m-linux_x86_64.whl也确实下载到本地了，不知为何说not a supported wheel，望指教

**Comment by MrChengmo** [comment]
> > 需要安装带分布式训练模式的的paddle版本， pip install只有单机版本的。
> > https://www.paddlepaddle.org.cn/install/doc/tables#%E5%A4%9A%E7%89%88%E6%9C%ACwhl%E5%8C%85%E5%88%97%E8%A1%A8-dev-11
> > 里面的cpu-mkl 下面的python版本选择一个wheel包安装好 ，例如python 27版本就
> > 用pip install -U paddlepaddle-latest-cp27-cp27mu-linux_x86_64.whl
> 
> 在Anaconda Prompt中，按您的指示运行了pip install -U paddlepaddle-latest-cp37-cp37m-linux_x86_64.whl
> 但是报错了，报错信息如下：
> 
> > ERROR: paddlepaddle-latest-cp37-cp37m-linux_x86_64.whl is not a supported wheel on this platform.
> 
> 我一直使用的都是Python 3.7, paddlepaddle-latest-cp37-cp37m-linux_x86_64.whl也确实下载到本地了，不知为何说not a supported wheel，望指教

- 您下载的包是在Linux环境下安装的`paddlepaddle-latest-cp37-cp37m-linux_x86_64.whl`，您的运行环境是win10？
- 分布式运行推荐在linux下进行，有很多分布式OP不支持在win下运行
- 可以参考文档：https://github.com/PaddlePaddle/Fleet/tree/develop/examples/distribute_ctr

**Comment by jerryniu520126** [comment]
> > > 需要安装带分布式训练模式的的paddle版本， pip install只有单机版本的。
> > > https://www.paddlepaddle.org.cn/install/doc/tables#%E5%A4%9A%E7%89%88%E6%9C%ACwhl%E5%8C%85%E5%88%97%E8%A1%A8-dev-11
> > > 里面的cpu-mkl 下面的python版本选择一个wheel包安装好 ，例如python 27版本就
> > > 用pip install -U paddlepaddle-latest-cp27-cp27mu-linux_x86_64.whl
> > 
> > 
> > 在Anaconda Prompt中，按您的指示运行了pip install -U paddlepaddle-latest-cp37-cp37m-linux_x86_64.whl
> > 但是报错了，报错信息如下：
> > > ERROR: paddlepaddle-latest-cp37-cp37m-linux_x86_64.whl is not a supported wheel on this platform.
> > 
> > 
> > 我一直使用的都是Python 3.7, paddlepaddle-latest-cp37-cp37m-linux_x86_64.whl也确实下载到本地了，不知为何说not a supported wheel，望指教
> 
> * 您下载的包是在Linux环境下安装的`paddlepaddle-latest-cp37-cp37m-linux_x86_64.whl`，您的运行环境是win10？
> * 分布式运行推荐在linux下进行，有很多分布式OP不支持在win下运行
> * 可以参考文档：https://github.com/PaddlePaddle/Fleet/tree/develop/examples/distribute_ctr

谢谢您的指点

**Comment by joyoFeng** [comment]
> > > 需要安装带分布式训练模式的的paddle版本， pip install只有单机版本的。
> > > https://www.paddlepaddle.org.cn/install/doc/tables#%E5%A4%9A%E7%89%88%E6%9C%ACwhl%E5%8C%85%E5%88%97%E8%A1%A8-dev-11
> > > 里面的cpu-mkl 下面的python版本选择一个wheel包安装好 ，例如python 27版本就
> > > 用pip install -U paddlepaddle-latest-cp27-cp27mu-linux_x86_64.whl
> > 
> > 
> > 在Anaconda Prompt中，按您的指示运行了pip install -U paddlepaddle-latest-cp37-cp37m-linux_x86_64.whl
> > 但是报错了，报错信息如下：
> > > ERROR: paddlepaddle-latest-cp37-cp37m-linux_x86_64.whl is not a supported wheel on this platform.
> > 
> > 
> > 我一直使用的都是Python 3.7, paddlepaddle-latest-cp37-cp37m-linux_x86_64.whl也确实下载到本地了，不知为何说not a supported wheel，望指教
> 
> * 您下载的包是在Linux环境下安装的`paddlepaddle-latest-cp37-cp37m-linux_x86_64.whl`，您的运行环境是win10？
> * 分布式运行推荐在linux下进行，有很多分布式OP不支持在win下运行
> * 可以参考文档：https://github.com/PaddlePaddle/Fleet/tree/develop/examples/distribute_ctr

你好， 我用v1.8.3 checkout仓库，然后按照教程执行分布式范例：https://www.bookstack.cn/read/paddlepaddle-v1.5/8f89485a1910612b.md， 也是遇到：`ValueError: Operator "send" has not been registered.`， 请问是什么情况呢？

编译命令（编译cpu版本，ubuntu19.10）： CXXFLAGS="-Wno-error=pessimizing-move -Wno-error=deprecated-copy" cmake .. -DPY_VERSION=3.7 -DWITH_FLUID_ONLY=ON -DWITH_GPU=OFF -DWITH_TESTING=OFF -DCMAKE_BUILD_TYPE=Release
