### ISSUE TITLE
Paddle Serving 加载GPU模型时失败

### ISSUE THREAD

**Issue by lp1985621** [PaddlePaddle/Paddle#22500]
- 版本、环境信息：
    1）PaddlePaddle版本：1.5.2 GPU版本
    2）GPU：GPU是 Tesla V100-SXM2；CUDA version: 10.0，CUDNN version: v7
    3）CENTOS7 python3.6，
-预测信息
    1）C++预测：GIT COMMIT ID: bf379fef961319ed213df7193cf7bd3997f0c095
    2）PaddlePaddle/Serving 下 cmake -DWITH_GPU=ON .
CPU模型加载成功，GPU模型加载失败，失败信息如下：
I0207 15:56:19.291407 14554 analysis_predictor.cc:88] Profiler is deactivated, and no profiling report will be generated.
I0207 15:56:19.325328 14554 op_compatible_info.cc:201] The default operator required version is missing. Please update the model version.
I0207 15:56:19.325392 14554 analysis_predictor.cc:847] MODEL VERSION: 0.0.0
I0207 15:56:19.325403 14554 analysis_predictor.cc:849] PREDICTOR VERSION: 0.0.0
W0207 15:56:19.325646 14554 analysis_predictor.cc:862]  - Version incompatible (1) cast
W0207 15:56:19.325662 14554 analysis_predictor.cc:862]  - Version incompatible (1) crf_decoding
W0207 15:56:19.325675 14554 analysis_predictor.cc:862]  - Version incompatible (1) dropout
W0207 15:56:19.325687 14554 analysis_predictor.cc:862]  - Version incompatible (1) elementwise_add
W0207 15:56:19.325700 14554 analysis_predictor.cc:862]  - Version incompatible (1) feed
W0207 15:56:19.325711 14554 analysis_predictor.cc:862]  - Version incompatible (1) fetch
W0207 15:56:19.325723 14554 analysis_predictor.cc:862]  - Version incompatible (1) layer_norm
W0207 15:56:19.325736 14554 analysis_predictor.cc:862]  - Version incompatible (1) lookup_table
W0207 15:56:19.325748 14554 analysis_predictor.cc:862]  - Version incompatible (1) matmul
W0207 15:56:19.325760 14554 analysis_predictor.cc:862]  - Version incompatible (1) mul
W0207 15:56:19.325773 14554 analysis_predictor.cc:862]  - Version incompatible (1) relu
W0207 15:56:19.325784 14554 analysis_predictor.cc:862]  - Version incompatible (1) reshape2
W0207 15:56:19.325796 14554 analysis_predictor.cc:862]  - Version incompatible (1) scale
W0207 15:56:19.325809 14554 analysis_predictor.cc:862]  - Version incompatible (1) sequence_unpad
W0207 15:56:19.325820 14554 analysis_predictor.cc:862]  - Version incompatible (1) softmax
W0207 15:56:19.325842 14554 analysis_predictor.cc:862]  - Version incompatible (1) stack
W0207 15:56:19.325855 14554 analysis_predictor.cc:862]  - Version incompatible (1) transpose2
W0207 15:56:19.325866 14554 analysis_predictor.cc:148] WARNING: Results may be DIFF! Please use the corresponding version of the model and prediction library, and do not use the develop branch.

**Comment by wangchaochaohu** [comment]
显示版本不匹配 某些OP的使用对Paddle 版本是有要求的 建议用官方最新的Paddle 1.6.3版本
