### ISSUE TITLE
二次梯度OP需求收集

### ISSUE THREAD

**Issue by wangchaochaohu** [PaddlePaddle/Paddle#22520]
关于OP二次梯度，如有相关需求，可以在这里添加

**Comment by wangchaochaohu** [comment]
目前沟通了解到的是FC层和交叉熵

**Comment by irukawang** [comment]
主要是想对embedding做梯度惩罚，所以embedding之后经过的op都需要二阶梯度，主要是fc bn relu 这一套

**Comment by qyccc** [comment]
paddle现在有什么实现梯度惩罚的方式吗？linear_chain_crf层可以二次求导吗

**Comment by wangchaochaohu** [comment]
> 主要是想对embedding做梯度惩罚，所以embedding之后经过的op都需要二阶梯度，主要是fc bn relu 这一套
这边会返回过去

**Comment by wangchaochaohu** [comment]
> paddle现在有什么实现梯度惩罚的方式吗？linear_chain_crf层可以二次求导吗
目前linear_chain_crf 不支持double grad。 这方面的需求会及时反馈

**Comment by ceci3** [comment]
> paddle现在有什么实现梯度惩罚的方式吗？linear_chain_crf层可以二次求导吗

第一个问题是想问怎么使用梯度惩罚嘛？可以参考https://github.com/PaddlePaddle/models/blob/develop/PaddleCV/gan/trainer/StarGAN.py#L150 GAN里的实现方法。只要网络里的op都支持double grad，就可以。

**Comment by qyccc** [comment]
> > paddle现在有什么实现梯度惩罚的方式吗？linear_chain_crf层可以二次求导吗
> 
> 第一个问题是想问怎么使用梯度惩罚嘛？可以参考https://github.com/PaddlePaddle/models/blob/develop/PaddleCV/gan/trainer/StarGAN.py#L150 GAN里的实现方法。只要网络里的op都支持double grad，就可以。

是的，谢谢。还想请问一下，用了这个方法后在evaluation阶段报错
> ValueError: Operator "mean_grad" has not been registered.
就是因为crf不支持二阶梯度吗，但是train阶段可以跑？

**Comment by ceci3** [comment]
> 主要是想对embedding做梯度惩罚，所以embedding之后经过的op都需要二阶梯度，主要是fc bn relu 这一套

你好，可以麻烦详细列一下有二阶梯度需求的op吗？fc和relu现在是支持的。

**Comment by ceci3** [comment]
> > > paddle现在有什么实现梯度惩罚的方式吗？linear_chain_crf层可以二次求导吗
> > 
> > 
> > 第一个问题是想问怎么使用梯度惩罚嘛？可以参考https://github.com/PaddlePaddle/models/blob/develop/PaddleCV/gan/trainer/StarGAN.py#L150 GAN里的实现方法。只要网络里的op都支持double grad，就可以。
> 
> 是的，谢谢。还想请问一下，用了这个方法后在evaluation阶段报错
> 
> > ValueError: Operator "mean_grad" has not been registered.
> > 就是因为crf不支持二阶梯度吗，但是train阶段可以跑？

你好，一般是训练阶段的时候梯度惩罚添加到loss计算中，train阶段 optimizer.minize的时候才会激活二阶求导这个计算，evaluation阶段我理解的是不需要更新参数，就不会激活二阶求导。可以检查下代码是否写的有问题。

**Comment by qyccc** [comment]
> > > > paddle现在有什么实现梯度惩罚的方式吗？linear_chain_crf层可以二次求导吗
> > > 
> > > 
> > > 第一个问题是想问怎么使用梯度惩罚嘛？可以参考https://github.com/PaddlePaddle/models/blob/develop/PaddleCV/gan/trainer/StarGAN.py#L150 GAN里的实现方法。只要网络里的op都支持double grad，就可以。
> > 
> > 
> > 是的，谢谢。还想请问一下，用了这个方法后在evaluation阶段报错
> > > ValueError: Operator "mean_grad" has not been registered.
> > > 就是因为crf不支持二阶梯度吗，但是train阶段可以跑？
> 
> 你好，一般是训练阶段的时候梯度惩罚添加到loss计算中，train阶段 optimizer.minize的时候才会激活二阶求导这个计算，evaluation阶段我理解的是不需要更新参数，就不会激活二阶求导。可以检查下代码是否写的有问题。

恩恩是的，谢谢。我是在paddlehub上改的，evaluation和train阶段都会跑到loss函数，所以报错了，加了个状态判断就解决了
