### ISSUE TITLE
can not compile padder for 0.10.0

### ISSUE THREAD

**Issue by techiethink** [PaddlePaddle/Paddle#2253]
how to solve the problem for compile at 0.10.0 version, the compiler error like these:

/usr/bin/c++    -std=c++11 -fPIC -fno-omit-frame-pointer -Wall -Wextra -Werror -Wnon-virtual-dtor -Wdelete-non-virtual-dtor -Wno-unused-parameter -Wno-unused-function -Wno-error=literal-suffix -Wno-error=sign-compare -Wno-error=unused-local-typedefs -mavx -O2 -g -DNDEBUG   CMakeFiles/paddle_pserver_main.dir/ParameterServer2Main.cpp.o  -o paddle_pserver_main -rdynamic -Wl,--start-group -Wl,--whole-archive ../gserver/libpaddle_gserver.a ../function/libpaddle_function.a -Wl,--no-whole-archive libpaddle_pserver.a ../trainer/libpaddle_trainer_lib.a libpaddle_network.a ../math/libpaddle_math.a ../utils/libpaddle_utils.a ../parameter/libpaddle_parameter.a ../../proto/libpaddle_proto.a ../cuda/libpaddle_cuda.a ../../../third_party/install/gflags/lib/libgflags.a ../../../third_party/install/glog/lib/libglog.a /opt/OpenBLAS/lib/libopenblas.so /usr/local/lib64/libprotobuf.a ../../../third_party/install/zlib/lib/libz.a -lpython2.7 -lpthread -ldl -Wl,--end-group -Wl,-rpath,/opt/OpenBLAS/lib: 
../math/libpaddle_math.a(MathFunctions.cpp.o): In function `operator()<CBLAS_ORDER, int, int, float*, int, int*>':
/data/home/aronou/project/deep_learn/paddle/paddle/math/MathFunctions.cpp:81: undefined reference to `LAPACKE_sgetrf'
../math/libpaddle_math.a(MathFunctions.cpp.o): In function `operator()<CBLAS_ORDER, int, int, double*, int, int*>':
/data/home/aronou/project/deep_learn/paddle/paddle/math/MathFunctions.cpp:81: undefined reference to `LAPACKE_dgetrf'
../math/libpaddle_math.a(MathFunctions.cpp.o): In function `operator()<CBLAS_ORDER, int, float*, int, int const*>':
/data/home/aronou/project/deep_learn/paddle/paddle/math/MathFunctions.cpp:81: undefined reference to `LAPACKE_sgetri'
../math/libpaddle_math.a(MathFunctions.cpp.o): In function `operator()<CBLAS_ORDER, int, double*, int, int const*>':
/data/home/aronou/project/deep_learn/paddle/paddle/math/MathFunctions.cpp:81: undefined reference to `LAPACKE_dgetri'

**Comment by dzhwinter** [comment]
`undefined reference toLAPACKE_sgetrf` seems it can not link openblas correctly. @gangliao 
Can you uninstall your local openblas in /opt/OpenBLAS?  Paddle will download a fresh new openblas and do that job for you.

**Comment by techiethink** [comment]
@dzhwinter , I get it, thanks.

**Comment by gangliao** [comment]
This issue was solved. So I close it.

**Comment by supermanhuyu** [comment]
i have the same problem,how did you deal with it ? 
https://github.com/PaddlePaddle/Paddle/issues/3880
