### ISSUE TITLE
Paddle-TRT实际测试数据与官网数据差距较大

### ISSUE THREAD

**Issue by hexiaoting** [PaddlePaddle/Paddle#22534]
# 环境
操作系统centos
Intel(R) Xeon(R) CPU E5-2640 v4 @ 2.40GHz
NVIDIA Corporation GK210GL [Tesla K80] (rev a1)
测试模型 ResNet50，MobileNet，ResNet101

# Paddle环境
- fluid_inference 直接下载的安装包
GIT COMMIT ID: fa7ace7cf2859f927c26f1970bbc2f5551532df1
WITH_MKL: ON
WITH_MKLDNN: OFF
WITH_GPU: ON
CUDA version: 10.0
CUDNN version: v7
- 下载了PaddlePaddle  model github repo

# 测试说明
* 按照[Paddle-TRT性能测试](https://www.paddlepaddle.org.cn/documentation/docs/zh/advanced_usage/deploy/inference/paddle_tensorrt_infer.html#id4) 进行本次测试工作。
* 所有的inputsize都是3 * 224 * 224
* 模型出处：
   - mobilenet下载地址：[官网提供的预测样例](https://www.paddlepaddle.org.cn/documentation/docs/zh/advanced_usage/deploy/inference/paddle_tensorrt_infer.html#id2)
   - resnet50 resnet101下载地址：[已发布模型及其性能](https://github.com/PaddlePaddle/models/tree/develop/PaddleCV/image_classification#已发布模型及其性能)
        模型转换转为二进制模型生成model和params文件；最后按照mobilenet的预测样例执行run.sh脚本进行推断
```
python infer.py \
       --model=ResNet50和ResNet101 \
       --pretrained_model=${path_to_pretrain_model} \
       --save_inference=True
```
# 测试结果
![image](https://user-images.githubusercontent.com/7898329/74223202-27fddf80-4cf1-11ea-85ba-53c97e540f61.png)

结果和官网的测试结果差异较大：
![image](https://user-images.githubusercontent.com/7898329/74223250-47950800-4cf1-11ea-8a68-a8df1363681b.png)

Q1: inputsize是多少如何定的呀？
Q2:我处理resnet50和resnet101和官方的paddle-TRT测试对比中的resnet50和resnet101是一样的吗？
Q3：为什么batchsize越大，测试结果和paddle官网的差距越大？
Q4:  已发布模型里面没有inceptionv3呢，那官方的paddle-TRT测试对比的inceptionv3是哪来的？
Q5: Paddle-TRT库是依赖于C++库的是吗？C++库和TRT库是什么关系？TRT库和fluid两种推断方法我可以理解为TRT是在fluid推断的基础上利用nvidia tensorrt做了加速吗？

**Comment by NHZlX** [comment]
1. 目前paddle-trt还不支持dynamic shape。输入的shape需要和模型定义的shape一致。可以下载Netron 软件，将模型文件`model` 修改成`__model__`查看模型的输入的shape。

2. 标准的resnet50/101都是3*224*224，应该是一致的。

3. 此数据测试的卡是P4，看到你的硬件是Tesla K80，我们之前没有在此硬件上进行过测试。运行和Paddle 预测性能相当的原因可能如下：1） Paddle原生预测有和TRT相似的优化， 包括OP间的融合，内存/显存优化，一个较大的差别在于TRT有内部的优化的OP kernel。 2. 此硬件较旧，可能某些trt优化的kernel不能够支持。

4. inceptionv3 这个模型确实没有发布，此数据后续会考虑更新。

5. Paddle-TRT可能理解为是GPU C++预测一个可选项，通过config.EnableTensorRtEngine() 接口进行配置打开TRT选项，分析阶段会启动TRT子图分析。

**Comment by hexiaoting** [comment]
好的，谢谢

**Comment by snowolfhawk** [comment]
> 1. 目前paddle-trt还不支持dynamic shape。输入的shape需要和模型定义的shape一致。可以下载Netron 软件，将模型文件`model` 修改成`__model__`查看模型的输入的shape。
> 2. 标准的resnet50/101都是3_224_224，应该是一致的。
> 3. 此数据测试的卡是P4，看到你的硬件是Tesla K80，我们之前没有在此硬件上进行过测试。运行和Paddle 预测性能相当的原因可能如下：1） Paddle原生预测有和TRT相似的优化， 包括OP间的融合，内存/显存优化，一个较大的差别在于TRT有内部的优化的OP kernel。 2. 此硬件较旧，可能某些trt优化的kernel不能够支持。
> 4. inceptionv3 这个模型确实没有发布，此数据后续会考虑更新。
> 5. Paddle-TRT可能理解为是GPU C++预测一个可选项，通过config.EnableTensorRtEngine() 接口进行配置打开TRT选项，分析阶段会启动TRT子图分析。

paddle-trt内部完全没有使用trt的优化算子，还是部分子图直接生成了trt算子部分使用了paddle自己的？

**Comment by jeng1220** [comment]
@snowolfhawk ,
部分子图直接生成了trt算子，部分使用了paddle自己的
