### ISSUE TITLE
[DNNL] Add DNNL reshape/reshape2 kernel

### ISSUE THREAD

**Issue by grygielski** [PaddlePaddle/Paddle#22543]
Adding DNNL reshape2 kernel could reduce number of layout changes (along with reorders) and lead to improvement of BERT model performance.

**Comment by lidanqing-vv** [comment]
Hi, @jczaja is reshape and reshape2 recently added during BF16 training enabling?

**Comment by jczaja** [comment]
@lidanqing-intel No. reshape2 of oneDNN was not merged. So we just extendeded reshape2 CPU template based implementation to support bf16. reshape2 oneDNN cannot be fully implemented as oneDNN MD.reshape() function does not support blocked layouts. But we could implement reshape2 oneDNN only for non blocking data layouts which would help with BERT.
