### ISSUE TITLE
计算loss时，进行softmax操作的先后会影响loss的值。

### ISSUE THREAD

**Issue by Colorfu1** [PaddlePaddle/Paddle#22559]
在计算loss的时候，当我先做softmax，再做transpose，使用cross_entropy计算损失，得到loss=6.759191
![code2](https://user-images.githubusercontent.com/30551427/74314733-efbdd600-4db0-11ea-827b-6267f8ffb458.PNG)
![loss2](https://user-images.githubusercontent.com/30551427/74314737-f0ef0300-4db0-11ea-9b21-e8d8f9df65d5.PNG)
调整顺序，先transpose，再做softmax，使用cross_entropy计算损失，得到loss=2.243314
![code1](https://user-images.githubusercontent.com/30551427/74312029-c5b5e500-4dab-11ea-8360-f252a9d45545.PNG)
![loss1](https://user-images.githubusercontent.com/30551427/74311912-7cfe2c00-4dab-11ea-9ecd-9f0da6d8b30d.PNG)
在第一种的情况下，模型无法收敛。偶然发现是顺序造成的问题。

**Comment by chenwhql** [comment]
您好，我理解这两种计算应该不是等价的吧，softmax是以某一个轴的下标为索引，对这一轴上其他维度的值进行 激活 + 归一化处理。一般来说，这个索引轴都是表示类别的那个维度（也就是最后一个维度）

您可以看下官方文档：https://www.paddlepaddle.org.cn/documentation/docs/zh/api_cn/layers_cn/softmax_cn.html#paddle.fluid.layers.softmax

softmax里面有一个维度变换操作
![image](https://user-images.githubusercontent.com/22561442/74316915-6230b500-4db5-11ea-9927-763d7b8c9f2a.png)

transpose之前和transpose之后softmax的轴应该是不一样的，所以导致计算也不是等价，您看看是不是这样？

**Comment by Colorfu1** [comment]
> 您好，我理解这两种计算应该不是等价的吧，softmax是以某一个轴的下标为索引，对这一轴上其他维度的值进行 激活 + 归一化处理。一般来说，这个索引轴都是表示类别的那个维度（也就是最后一个维度）
> 
> 您可以看下官方文档：https://www.paddlepaddle.org.cn/documentation/docs/zh/api_cn/layers_cn/softmax_cn.html#paddle.fluid.layers.softmax
> 
> softmax里面有一个维度变换操作
> ![image](https://user-images.githubusercontent.com/22561442/74316915-6230b500-4db5-11ea-9927-763d7b8c9f2a.png)
> 
> transpose之前和transpose之后softmax的轴应该是不一样的，所以导致计算也不是等价，您看看是不是这样？

恩恩，是的
