### ISSUE TITLE
transpose_mkldnn Op中调用了ShareDataWith方法

### ISSUE THREAD

**Issue by gfwm2013** [PaddlePaddle/Paddle#22561]
Paddle框架的OP开发规范中规定[Op禁止调用ShareDataWith和ShareBufferWith方法](https://github.com/PaddlePaddle/Paddle/wiki/ShareDataWith-and-ShareBufferWith-are-prohibited-in-OP)，但在transpose_mkldnn OP的文件[transpose_mkldnn_op.cc](https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/fluid/operators/mkldnn/transpose_mkldnn_op.cc)中仍存在对输入和输出调用ShareDateWith方法。想请教一下，这个是否需要根据OP开发规范将其修改为TensorCopy的形式，还是出于什么考量仍需保留ShareDateWith方法呢？

![image](https://user-images.githubusercontent.com/52460041/74313367-863cc800-4dae-11ea-98c2-b27cc879d67a.png)
![image](https://user-images.githubusercontent.com/52460041/74313384-8c32a900-4dae-11ea-9cfa-e227cde112bb.png)

**Comment by chenwhql** [comment]
这是Op规范的存量问题吗？
发这个issue的目的是，需要商讨？还是发给负责人修改的？

**Comment by gfwm2013** [comment]
嗯呢，是Op规范的存量问题。
因我暂未找到这个Op的负责人，所以提这个issue想商讨一下该Op是否可以按照[Op禁止调用ShareDataWith和ShareBufferWith方法](https://github.com/PaddlePaddle/Paddle/wiki/ShareDataWith-and-ShareBufferWith-are-prohibited-in-OP)中的建议进行修改？

**Comment by chenwhql** [comment]
好的，了解了

**Comment by luotao1** [comment]
请 @bingyanghuang 帮忙看和翻译一下

**Comment by lidanqing-vv** [comment]
@gfwm2013  Can you please take a look at conv_mkldnn_op.cc? Because there is also ShareDataWith in that op. Should we also remove ShareDataWith in conv_mkldnn_op.cc ?

**Comment by gfwm2013** [comment]
@lidanqing-intel  Please remove ShareDataWith in conv_mkldnn_op.cc.

**Comment by lidanqing-vv** [comment]
> @lidanqing-intel Please remove ShareDataWith in conv_mkldnn_op.cc.

Ok

**Comment by lidanqing-vv** [comment]
> > @lidanqing-intel Please remove ShareDataWith in conv_mkldnn_op.cc.
> 
> Ok

**Comment by lidanqing-vv** [comment]
PR #22591 merged
