### ISSUE TITLE
fluid.save接口的参数命名有歧义，使用不方便

### ISSUE THREAD

**Issue by MrChengmo** [PaddlePaddle/Paddle#22578]
欢迎您对PaddlePaddle提出建议，非常感谢您对PaddlePaddle的贡献！
在留下您的建议时，辛苦您同步提供如下信息：
- 版本、环境信息
1）PaddlePaddle版本：1.7
2）CPU/GPU：CPU
3）系统环境：CentOS

在使用fluid.save接口时，该接口的参数为`def save(program, model_path):`，
- 假如传入model_path为`/path/epoch_1`，用户会直观认为模型保存结果如下`/path/epoch_1/model_file`，然而事实上，保存结果为`/path/epoch_1_model_file`。
- 如果训练多个epoch，path下会出现一大堆文件，与paddle其他保存模型的接口表现不一致。
- 为了达到保存为`/path/epoch_1/model_file`的效果，用户除了必须手动创建`/epoch_1`文件夹外，需传入model_path="/path/epoch_1" + "/" + "checkpoint"，才能保存为预期的形式，不方便用户使用与迁移。
- 因为很多训练多轮的场景save&load都是通过迭代文件夹实现的，现在会直接报错。给用户增加了很多迁移的成本。

希望能够针对这个api进行易用性优化。

**Comment by zhupengyang** [comment]
这个确实容易引起理解问题和使用的不方便，我们会评估后进行改进优化，感谢您的建议
