### ISSUE TITLE
yolov3 prune预测模型tensorrt 预测报错

### ISSUE THREAD

**Issue by barry2025** [PaddlePaddle/Paddle#22579]
- 版本、环境信息：
    1）PaddlePaddle版本：1.6.1
    2）GPU：cuda10.1和cuda9
-预测信息
    1）C++预测：version.txt
         GIT COMMIT ID: 70c073a0019f3405f9074579a8c48a43281dfdea
         WITH_MKL: ON
         WITH_MKLDNN: OFF
         WITH_GPU: ON
         CUDA version: 10.1
         CUDNN version: v7  
- 复现信息：剪枝预测模型地址  https://bj.bcebos.com/v1/mct-imagedb/tangxin-bos/yolov3_r34_prune.tar.gz
- 问题描述：
利用c++ 预测接口，采取fp32预测方式可以正常运行，采取tensorrt fp32方式报错：
![image](https://user-images.githubusercontent.com/20043808/74397705-48907b80-4e50-11ea-862c-31e6b80bbae8.png)

通过netron软件查看结构：
![image](https://user-images.githubusercontent.com/20043808/74397772-6cec5800-4e50-11ea-8451-89805e54c241.png)  64288=392*164，说明model维度没有问题
剪枝模型存储为预测模型时：
![image](https://user-images.githubusercontent.com/20043808/74397930-d704fd00-4e50-11ea-8794-b34007bef4ab.png)
checkpoint没有报错，说明参数也没有问题

**Comment by NHZlX** [comment]
可以看到输出的channel和参数并不匹配，请确认模型是否有问题：

![image](https://user-images.githubusercontent.com/5595332/74399470-e5a1e300-4e55-11ea-9b4f-ee4e3678a5f8.png)
