### ISSUE TITLE
py_func中在没有对输出类型为list时的情况做处理

### ISSUE THREAD

**Issue by littletomatodonkey** [PaddlePaddle/Paddle#22581]
paddle1.7版本，py_func中在输出out为list时，没有做处理，导致out_list未被定义，程序报错

https://github.com/PaddlePaddle/Paddle/blob/e78858f19c9d52d22431b453cb0e776e4c98ef99/python/paddle/fluid/layers/nn.py#L12599

**Comment by zhupengyang** [comment]
看上去是个bug，感谢反馈

**Comment by zhupengyang** [comment]
@zhouwei25 看上去是 #21687 修复的时候没有处理list的情况，你来修下？

**Comment by zhwesky2010** [comment]
> @zhouwei25 看上去是 #21687 修复的时候没有处理list的情况，你来修下？

收到
