### ISSUE TITLE
ERROR: flag 'logtostderr' was defined more than once when running inference

### ISSUE THREAD

**Issue by imistyrain** [PaddlePaddle/Paddle#22613]
为使您的问题得到快速解决，在建立Issue前，请您先通过如下方式搜索是否有相似问题:无
- 版本、环境信息：
    1）PaddlePaddle版本：请提供您的PaddlePaddle版本号（如1.7）或CommitID926227c8a30dcaabd5054c132bf862347b4c7ab3
    2）CPU：普通i5，预测若用CPU，未使用MKL等
    3）GPU：无
    4）系统环境: Mac OS 10.14
-预测信息
    1）C++预测：请您提供预测库安装包的版本信息，及其中的version.txt文件
GIT COMMIT ID: 926227c8a30dcaabd5054c132bf862347b4c7ab3
WITH_MKL: OFF
WITH_MKLDNN: OFF
WITH_GPU: OFF
    2）CMake包含路径的完整命令
cmake -DCMAKE_BUILD_TYPE=Release \
      -DWITH_PYTHON=OFF \
      -DWITH_MKL=OFF \
      -DWITH_GPU=OFF  \
      -DON_INFER=ON \
      ..
 make -j2
    3）预测库来源：官网下载
- 复现信息：如为报错，请给出复现环境、复现步骤
- 问题描述：请详细描述您的问题，同步贴出报错信息、日志/代码关键片段
Mac端C++ demo编译完成后运行报
ERROR: flag 'logtostderr' was defined more than once (in files '/tmp/glog-20190323-24114-1a1aa25/glog-0.4.0/src/logging.cc' and 'paddle/build/third_party/glog/src/extern_glog/src/logging.cc').
注: Windows端没有问题

**Comment by fc500110** [comment]
能给一下代码链接么

**Comment by imistyrain** [comment]
问题已经解决，系由brew install opencv@3安装的时候依赖了glog，paddle又打包了一个glog，二者冲突了
brew uninstall glog
brew uninstall opencv@3
源码编译opencv并安装
