### ISSUE TITLE
请问一下，PaddlePaddle官方是否有实现DeepLabV3+模型呢？

### ISSUE THREAD

**Issue by songyuc** [PaddlePaddle/Paddle#22625]
你好！
请问一下，PaddlePaddle官方是否有实现DeepLabV3+模型呢？
期待你的回复！

**Comment by zhiqiu** [comment]
您好，有实现，请参考models库中[deeplabv3](https://github.com/PaddlePaddle/models/tree/develop/PaddleCV/deeplabv3%2B)和[PaddleSeg库](https://github.com/PaddlePaddle/PaddleSeg)。

**Comment by songyuc** [comment]
@zhiqiu ，好的，谢谢你的回复！
