### ISSUE TITLE
SRCNN超分辨率重建效果极差

### ISSUE THREAD

**Issue by Weigaa** [PaddlePaddle/Paddle#22658]
项目参考两个论文的复现：
https://aistudio.baidu.com/aistudio/projectdetail/26965
https://aistudio.baidu.com/aistudio/projectdetail/134147
第一个链接项目项目结果很好但因为框架过老无法fork，只能fork第二个链接，两个复现同一篇论文，但测试结果相差很多，只是分别用了python3和python2实现，但结果差很多的原因是什么？

- 版本、环境信息：
Python版本
Python 3.7
框架版本
PaddlePaddle 1.5.1
硬件信息
当前环境
CPU
8
RAM
32GB
GPU
v100
显存
16GB
磁盘
100GB
- 模型信息
    1）项目算法SRCNN 
    2）项目链接：https://aistudio.baidu.com/aistudio/projectdetail/134147
- 复现信息：直接fork复现第二个链接中的项目
- 问题描述：
  fork结果与原项目一致，原项目实现的结果就比较差。

**Comment by yiicy** [comment]
你好，由于Paddle 版本升级了1.6，部分Ai Studio中的代码升级后正确性还未进行完全测试，对您造成困扰深表遗憾，我们目前正在排查这个问题，如果您有兴趣也可以使用此项目对比下1.6版本的Paddle和老版本Paddle接口使用的一些区别，也有助于您使用Paddle更得心应手
