### ISSUE TITLE
调试问题

### ISSUE THREAD

**Issue by 18106574249** [PaddlePaddle/Paddle#22659]
![Snipaste_2020-02-18_15-16-54](https://user-images.githubusercontent.com/43194667/74713453-9697eb80-5263-11ea-958d-aa98607b37f4.png)

你好 我想了解一下 ERNIE 里面具体的 py reader 的异步处理机制,想一步一步调试看看
但是 在具体调试的时候却无法进入 IO 模块 代码细节 无法在具体的代码行中停留
请问这是什么原因 windows 系统 pycharm IDE

paddlepaddle 1.5版本
cpu  inter core I7-9700
系统  windows10 专业版
单机  

如果您没有查询到相似问题，为快速解决您的提问，建立issue时请提供如下细节信息：
- 标题：简洁、精准概括您的问题，例如“Insufficient Memory xxx" ”
- 版本、环境信息：
    1）PaddlePaddle版本：请提供您的PaddlePaddle版本号，例如1.1或CommitID
    2）CPU：预测若用CPU，请提供CPU型号，MKL/OpenBlas/MKLDNN/等数学库使用情况
    3）GPU：预测若用GPU，请提供GPU型号、CUDA和CUDNN版本号
    4）系统环境：请您描述系统类型、版本，例如Mac OS 10.14，Python版本
- 训练信息
    1）单机/多机，单卡/多卡
    2）显存信息
    3）Operator信息
- 复现信息：如为报错，请给出复现环境、复现步骤
- 问题描述：请详细描述您的问题，同步贴出报错信息、日志、可复现的代码片段

**Comment by yiicy** [comment]
你好，pyreader的部分代码使用c++实现的，无法在python代码中看到具体实现，源码可以参考https://github.com/PaddlePaddle/Paddle/tree/develop/paddle/fluid/operators/reader  这里的实现

**Comment by sneaxiy** [comment]
您好，py_reader底层是通过多线程方式往一个C++的数据队列里异步地送入数据，然后C++有个异步的线程读取队列中的数据。C++部分代码是没办法看到的。

**Comment by 18106574249** [comment]
如果我想对C++代码进行 调试 有什么办法吗

**Comment by sneaxiy** [comment]
@18106574249 您要调试C++代码的话，可能需要您源码编译，然后用gdb等工具debug。
