### ISSUE TITLE
分布式训练保存的模型，单机预测报错

### ISSUE THREAD

**Issue by mengyiliu22** [PaddlePaddle/Paddle#22651]
1）PaddlePaddle版本：fluid 1.6.1 paddlecloud cpu多机训练，1.6.2单机预测
     同样的代码1.19号时候单机预测成功过，目前预测报错信息如下：
![image](https://user-images.githubusercontent.com/15141419/74671550-5d6d6600-51e6-11ea-852f-b9a5ff54ec09.png)

**Comment by GaoWei8** [comment]
报错看起来是参数读取问题。

**Comment by mengyiliu22** [comment]
> 报错看起来是参数读取问题。

设置为is_sparse=True, is_distributed=False；替换__model__文件可解决，但不清楚为什么会有distribute_look_up。
