### ISSUE TITLE
通过pip安装之后目录跟你们在git上公布的目录和文件不一致这是什么原理 都是1.6版本

### ISSUE THREAD

**Issue by 18106574249** [PaddlePaddle/Paddle#22664]
通过pip安装之后目录跟你们在git上公布的目录和文件不一致这是什么原理 都是1.6版本
![微信图片_20200218205521](https://user-images.githubusercontent.com/43194667/74738024-05d80480-5291-11ea-8bee-2b28ead1ff79.png)

**Comment by yiicy** [comment]
你好，你看的是paddle的源代码目录，这个和安装后的目录结构确实是不一样的，如果想验证安装成功与否请参考https://www.paddlepaddle.org.cn/install/doc/windows 验证安装小节

**Comment by yiicy** [comment]
pip安装目录请参考https://github.com/PaddlePaddle/Paddle/tree/develop/python/paddle
