### ISSUE TITLE
麻烦为fluid.layers.assign添加对 float16的支持

### ISSUE THREAD

**Issue by sparrowhole** [PaddlePaddle/Paddle#22674]
标题：

麻烦为fluid.layers.assign支持 float16

版本、环境信息：
   1）PaddlePaddle版本：1.6.1
   2）CPU/GPU：CUDA 10.1, cuDNN 7.0
   3）系统环境：CentOS 7.7
   4）Python版本号: 3.7.4
   5）显存信息: 32G

复现信息：

```Python
fluid.layers.assign(A, B)
# where A is type of float16
```

问题描述：

TypeError: When the type of 'input' in assign is Variable, the data type of 'input' must be float32, float64, int32, int64 or bool, but received float16.

**Comment by gfwm2013** [comment]
@sparrowhole 好的，我会将你的需求反馈至相关负责人处。

**Comment by wawltor** [comment]
已增加对fp16的支持 
https://github.com/PaddlePaddle/Paddle/pull/22744
