### ISSUE TITLE
MPI集群大数据训练时failed

### ISSUE THREAD

**Issue by mtchen2016** [PaddlePaddle/Paddle#22684]
本地小数据集进行调试，一切正常；
MPI集群小数据进行调试，一切正常；
扩大数据集进行训练：出现如下问题，每次可复线：
任务链接：http://yq01-hpc-lvliang-mon.dmop.baidu.com:8919/taskinfo.html?appId=app-user-20200219164222-2520
<img width="879" alt="1222f74e9194d1e13f0ec8b5afffd873" src="https://user-images.githubusercontent.com/59867928/74829691-945d8c00-534c-11ea-8050-c80dfa4ce0f6.png">

**Comment by gfwm2013** [comment]
@xjqbest 麻烦帮忙看一下

**Comment by xjqbest** [comment]
solved
