### ISSUE TITLE
蒸馏的问题

### ISSUE THREAD

**Issue by 18106574249** [PaddlePaddle/Paddle#22680]
您好,请问一下  如果我用paddle训练了一个模型，可否自己做蒸馏,你们蒸馏的源码是开源的吗？
是完全可以自己做蒸馏的把，没有什么限制把

建立issue时，为快速解决问题，请您根据使用情况给出如下信息：
- 标题：简洁、精准描述您的问题，例如“ssd 模型前置lstm报错  ”
- 版本、环境信息：
    1）PaddlePaddle版本：请提供PaddlePaddle版本号，例如1.1或CommitID
    2）CPU：请提供CPU型号，MKL/OpenBlas/MKLDNN/等数学库的使用情况
    3）GPU：请提供GPU型号，CUDA和CUDNN版本号
    4）系统环境：请说明系统类型、版本（例如Mac OS 10.14），Python版本
- 模型信息
    1）模型名称 2）使用数据集名称 3）使用算法名称 4）模型链接
- 复现信息：如为报错，请给出复现环境、复现步骤
- 问题描述：请详细描述您的问题，同步贴出报错信息、日志/代码关键片段

Thank you for contributing to PaddlePaddle.
Before submitting the issue, you could search issue in the github.Probably there was a similar issue submitted or resolved before.
If there is no solution,please make sure that this is a issue of models including the following details:
**System information**
-PaddlePaddle version （eg.1.1）or CommitID
-CPU: including CPUMKL/OpenBlas/MKLDNN version
-GPU: including CUDA/CUDNN version
-OS Platform (eg.Mac OS 10.14)
-Python version
-Name of Models&Dataset/details of operator
**To Reproduce**
Steps to reproduce the behavior
**Describe your current behavior**
**Code to reproduce the issue**
**Other info / logs**

**Comment by wanghaoshuang** [comment]
可以自己做，没有限制。
我们做的一些实验结论，您可以参考下：https://paddlepaddle.github.io/PaddleSlim/model_zoo
使用PaddleSlim做蒸馏的一个教程：https://paddlepaddle.github.io/PaddleSlim/quick_start/distillation_tutorial.html
使用PaddleSlim+PaddleDetection做蒸馏的一个示例：https://github.com/PaddlePaddle/PaddleDetection/tree/master/slim/distillation

**Comment by maomaoyuchengzi** [comment]
> 可以自己做，没有限制。
> 我们做的一些实验结论，您可以参考下：https://paddlepaddle.github.io/PaddleSlim/model_zoo
> 使用PaddleSlim做蒸馏的一个教程：https://paddlepaddle.github.io/PaddleSlim/quick_start/distillation_tutorial.html
> 使用PaddleSlim+PaddleDetection做蒸馏的一个示例：https://github.com/PaddlePaddle/PaddleDetection/tree/master/slim/distillation

您好，请教下，paddle中怎样把前向计算的图片计算的中间层结果拿出来，可以直接查看参数的大小变化；我使用了以下操作：
 split_output_names = ['conv_last_weights']
        student_var = []
        for name in split_output_names:
            student_var.append(fluid.default_main_program().global_block().var(name))
但我无法看到中间的数值结果，我想直接看到中间数值变化；
