### ISSUE TITLE
【编译错误】ubuntu16.04 编译paddleDetection的C++预测库报错

### ISSUE THREAD

**Issue by 1224wxwx** [PaddlePaddle/Paddle#22689]
- 版本、环境信息：
    1）PaddlePaddle版本：1.6.3.post97
    2）CPU：
    3）GPU：K80、CUDA9.0、CUDNN7.1.4
    4）系统环境：ubuntu16.04，python3.7和python2.7，gcc4.8.5，cmake 3.5.1

- 安装方式信息：
1）pip安装：python3 -m pip install paddlepaddle-gpu==1.6.3.post97 -i https://mirror.baidu.com/pypi/simple

- 复现信息：如为报错，请给出复现环境、复现步骤
根据 _https://github.com/PaddlePaddle/PaddleDetection/blob/release/0.1/inference/docs/linux_build.md_ 教程里面的方法，编译安装完opencv后，编译paddleDetection的C++预测库报错。

**opencv的cmake命令如下：**
![image](https://user-images.githubusercontent.com/17800557/74903390-bb1ad180-53e3-11ea-84e7-6739b195fc51.png)

**预测库的cmake命令如下：**
![image](https://user-images.githubusercontent.com/17800557/74903363-acccb580-53e3-11ea-8f14-d1a6de2691f8.png)

- 问题描述：请详细描述您的问题，同步贴出报错信息、日志/代码关键片段
在C++预测库cmake成功完成后，使用make命令报错如下，显示安装的opencv中少个文件：
![image](https://user-images.githubusercontent.com/17800557/74903033-c02b5100-53e2-11ea-9b47-03e6346c8f1e.png)

opencv之前已经成功安装在/home/wushengjian/release-p-test/opencv如下：
![image](https://user-images.githubusercontent.com/17800557/74903095-f668d080-53e2-11ea-9c77-eca7020305d1.png)

另外在make预测库的时候，还会出现很多warning如下：
![image](https://user-images.githubusercontent.com/17800557/74903154-1dbf9d80-53e3-11ea-9edd-028080bd7e2c.png)

Thank you for contributing to PaddlePaddle.
Before submitting the issue, you could search issue in Github in case that there was a similar issue submitted or resolved before.
If there is no solution,please make sure that this is an installation issue including the following details:
**System information**
-PaddlePaddle version （eg.1.1）or CommitID
-CPU: including CPUMKL/OpenBlas/MKLDNN version
-GPU: including CUDA/CUDNN version
-OS Platform (eg. Mac OS 10.14)
-Python version
- Install method: pip install/install with docker/build from source(without docker)/build within docker
- Other special cases that you think may be related to this problem, eg. offline install, special internet condition   
**To Reproduce**
Steps to reproduce the behavior
**Describe your current behavior**
**Code to reproduce the issue**
**Other info / logs**

**Comment by 1224wxwx** [comment]
试了一下，在ubuntu16的官方docker中按照上述方法编译后，同样会有这个错误，最后链接的时候缺少文件，怀疑是不是文档里给的cmake opencv的命令参数不正确导致？

**Comment by 1224wxwx** [comment]
https://github.com/PaddlePaddle/PaddleDetection/blob/release/0.1/inference/docs/linux_build.md 文档里cmake opencv的命令应该是写错了，-DCMAKE_INSTALL_LIBDIR=lib64这个参数会导致把libopencv_imgcodes.a这个文件生成到/root/projects/opencv3/lib64文件夹里，而在make预测库的时候，会去/root/projects/opencv3/lib里找，就会导致找不到报错失败

**Comment by sjtubinlong** [comment]
@1224wxwx hi, 麻烦检查一下是不是opencv的缺失的这个lib在`opencv/lib64`目录下,   如果是需要修改下cmake里面这个路径。

这块的适配我们会优化一下。

**Comment by 1224wxwx** [comment]
@sjtubinlong 对的，是的，发现在cmake的时候去掉-DCMAKE_INSTALL_LIBDIR=lib64这个就好了
