### ISSUE TITLE
如何去除张量中的0元素

### ISSUE THREAD

**Issue by txyugood** [PaddlePaddle/Paddle#22690]
请问在paddle 静态图中，有没有去除一些指定的元素的方法？比如我想去除所有的0，然后生成一个新的张量。
tf 中有boolean_mask可以实现，paddle 中有没有什么办法可以实现？

**Comment by DannyIsFunny** [comment]
你好，经查找暂时没有该接口，Python接口中可以用np.array(tensor) 方法将tensor转化为numpy array，修改numpy array的值，再重新赋值给tensor。详情参考：https://www.paddlepaddle.org.cn/documentation/docs/zh/api_cn/fluid_cn/Tensor_cn.html#tensor

**Comment by txyugood** [comment]
@DannyIsFunny 感谢回复，但是这样在静态图训练过程是不可以的吧。因为  python 的numpy 的操作不会记入图中，只有构建计算图的时候会执行一次。

**Comment by txyugood** [comment]
最后使用控制流自己实现，关闭issue.

**Comment by txyugood** [comment]
发现更好的方法，结合 where 和gather_nd 可以直接实现，不需要控制流。

**Comment by HJYgotoPLAY** [comment]
> 发现更好的方法，结合 where 和gather_nd 可以直接实现，不需要控制流。
求具体的实现方法

**Comment by txyugood** [comment]
例子如下：
```
from paddle import fluid
import numpy as np

tensor1 = fluid.layers.assign(np.array([1,2,0,4,0,5,0,6]).astype('int32'))
idx = fluid.layers.where(tensor1 != 0)
tensor2 = fluid.layers.gather_nd(tensor1, idx)
exe = fluid.Executor(fluid.CPUPlace())
exe.run(fluid.default_startup_program())
r = exe.run(fluid.default_main_program(),fetch_list=[tensor2])
print(r[0])
```
结果为[1 2 4 5 6]

**Comment by HJYgotoPLAY** [comment]
> 例子如下：
> 
> ```
> from paddle import fluid
> import numpy as np
> 
> tensor1 = fluid.layers.assign(np.array([1,2,0,4,0,5,0,6]).astype('int32'))
> idx = fluid.layers.where(tensor1 != 0)
> tensor2 = fluid.layers.gather_nd(tensor1, idx)
> exe = fluid.Executor(fluid.CPUPlace())
> exe.run(fluid.default_startup_program())
> r = exe.run(fluid.default_main_program(),fetch_list=[tensor2])
> print(r[0])
> ```
> 
> 结果为[1 2 4 5 6]

学习了，非常感谢
