### ISSUE TITLE
ASR demo required!

### ISSUE THREAD

**Issue by reyoung** [PaddlePaddle/Paddle#227]
User from gitter talk wants some demo for speech recognition and provides some open source dataset here.
- https://github.com/kaldi-asr/kaldi/tree/master/egs/librispeech
- https://github.com/kaldi-asr/kaldi/tree/master/egs/thchs30
- http://www.openslr.org/resources.php

**Comment by F0REacH** [comment]
+1. Would be nice to see, also demo example of CTC layer/evaluator would be highly appreciated.

**Comment by F0REacH** [comment]
FYI: Guys from NervanaSystems released a few days ago their [DeepSpeech2 implementation](https://github.com/NervanaSystems/deepspeech.git) based on [neon](https://github.com/NervanaSystems/neon.git) / [aeon](https://github.com/NervanaSystems/aeon.git)

**Comment by helinwang** [comment]
Closed due to inactivity, we are working on DS2 on PaddlePaddle.
