### ISSUE TITLE
win10(笔记本GTX1050TI)下安装好cuda10.0和对应的cudnn后检测时报错，更改显卡休眠后重启还是不行

### ISSUE THREAD

**Issue by NanRUN** [PaddlePaddle/Paddle#22701]
"D:\Visual Studio\Python36_64\python.exe" D:/pycharm/Health/learning/1.py
Running Verify Fluid Program ... 
2020-02-20 21:14:34,561-WARNING: You are using GPU version Paddle Fluid, But Your CUDA Device is not set properly
 Original Error is 

--------------------------------------------
C++ Call Stacks (More useful to developers):
--------------------------------------------
Windows not support stack backtrace yet.

----------------------
Error Message Summary:
----------------------
Error: cudaGetDeviceCount failed in paddle::platform::GetCUDADeviceCountImpl, error code : 30, Please see detail in https://docs.nvidia.com/cuda/cuda-runtime-api/group__CUDART__TYPES.html#group__CUDART__TYPES_1g3f51e3575c2178246db0a94a430e0038 at (D:\1.6.3\paddle\paddle\fluid\platform\gpu_info.cc:67)

W0220 21:14:34.561012  2320 init.cc:126] Compiled with WITH_GPU, but no GPU found in runtime.

Process finished with exit code 0

**Comment by zhwesky2010** [comment]
请问CUD版本是多少呢

**Comment by zhwesky2010** [comment]
@NanRUN 请问CUD版本是多少呢

**Comment by NanRUN** [comment]
> @NanRUN 请问CUD版本是多少呢
10.0

**Comment by zhwesky2010** [comment]
@NanRUN 麻烦在cmd命令行里run 一下，nvidia-smi看一下。驱动版本多少，安装好了吗

**Comment by zhwesky2010** [comment]
@NanRUN 然后跑一下 import paddle.fluid as fluid  fluid.install_check.run_check() 看一下结果

**Comment by NanRUN** [comment]
NVIDIA-SMI has failed because it couldn't communicate with the NVIDIA driver. Make sure that the latest NVIDIA driver is installed and running. This can also be happening if non-NVIDIA GPU is running as primary display, and NVIDIA GPU is in WDDM mode.报错

**Comment by NanRUN** [comment]
这是我的显卡的错误：Windows 无法验证此设备所需的驱动程序的数字签名。某软件或硬件最近有所更改，可能安装了签名错误或损毁的文件，或者安装的文件可能是来路不明的恶意软件。 (代码 52)

**Comment by NanRUN** [comment]
@zhouwei25

**Comment by zhwesky2010** [comment]
@NanRUN 1.你这个显卡的驱动没有安装正确，建议通过 GeForce Experience 来自动下载驱动安装。手动可能版本出错http://cn.download.nvidia.com/GFE/GFEClient/3.20.2.34/GeForce_Experience_v3.20.2.34.exe 2. 显卡硬件没有装好。极大可能是第一个的问题

**Comment by zhwesky2010** [comment]
@NanRUN 请问一下，问题解决了吗

**Comment by NanRUN** [comment]
您好 @zhouwei25 ，之前的问题解决了，现在有新问题，晚点给您发

**Comment by zhwesky2010** [comment]
@NanRUN 请问还有问题吗

**Comment by NanRUN** [comment]
2020-02-25 10:43:31,239-INFO: Decompressing C:\Users\Dell/.cache/paddle/weights\yolov3_mobilenet_v1.tar...
Traceback (most recent call last):
  File "tools/train.py", line 338, in <module>
    main()
  File "tools/train.py", line 205, in main
    exe, train_prog, cfg.pretrain_weights, ignore_params=ignore_params)
  File "D:\pycharm\Health\learning\PaddleDetection\ppdet\utils\checkpoint.py", line 98, in load_params
    "exists.".format(path))
ValueError: Model pretrain path C:\Users\Dell/.cache/paddle/weights\yolov3_mobilenet_v1 does not exists.

**Comment by NanRUN** [comment]
2020-02-25 10:43:31,239-INFO: Decompressing C:\Users\Dell/.cache/paddle/weights\yolov3_mobilenet_v1.tar...
Traceback (most recent call last):
  File "tools/train.py", line 338, in <module>
    main()
  File "tools/train.py", line 205, in main
    exe, train_prog, cfg.pretrain_weights, ignore_params=ignore_params)
  File "D:\pycharm\Health\learning\PaddleDetection\ppdet\utils\checkpoint.py", line 98, in load_params
    "exists.".format(path))
ValueError: Model pretrain path C:\Users\Dell/.cache/paddle/weights\yolov3_mobilenet_v1 does not exists.

**Comment by NanRUN** [comment]
这个好像是文件路径有问题，可是不知道从哪改

**Comment by zhwesky2010** [comment]
@NanRUN 这个路径检测不到 C:\Users\Dell/.cache/paddle/weights\yolov3_mobilenet_v1，你查下有没有这个文件，看下yolov3_mobilenet_v1有没有下载下来

**Comment by NanRUN** [comment]
在运行train的时候是有的，运行完后就没了

**Comment by zhwesky2010** [comment]
@NanRUN  traine的时候不是失败了吗？看下C:\Users\Dell\.cache 有没有什么文件，有没有下载的这个log, 比如Download failed之类的内容

**Comment by NanRUN** [comment]
C:\Users\Dell\.cache\paddle这个路径下有一个weights和yolov3_mobilenet_v1两个文件夹，在刚开始运行train下载数据集的时候显示weights下有yolov3_mobilenet_v1.tar_tmp这个文件，但当他报错的时候就不在了

**Comment by zhwesky2010** [comment]
@NanRUN  `shutil.move(tmp_fullname, fullname)`  yolov3_mobilenet_v1.tar_tmp 这个被改名成了yolov3_mobilenet_v1.tar，你看看这个操作成功了没

**Comment by NanRUN** [comment]
没有，这个怎么改呀

**Comment by zhwesky2010** [comment]
那个在 PaddleCV/PaddleDetection/ppdet/utils/download.py的第286行，你搜一下就能看到

**Comment by NanRUN** [comment]
如果是这个有问题怎么修改？

**Comment by zhwesky2010** [comment]
@NanRUN 你可以试一下把 tmp_fullname、fullname先print出来，然后自己用python shulti.move试一下，看一下为什么没有改名成功

**Comment by NanRUN** [comment]
我是在window环境下跑的，是不是因为没有7.tar的解压软件，但是我有winrar，打印后python shulti.move找不到文件

**Comment by zhwesky2010** [comment]
@NanRUN  如果自己查看的话，存在这个文件，但是shutil.move是报找不到，那就挺奇怪了。麻烦再确认下tmp_fullname的变量名和存不存在~

**Comment by zhwesky2010** [comment]
@NanRUN 你可以用Py脚本调试一下

**Comment by NanRUN** [comment]
应该不是改名的问题，我让其直接写为tar格式后还是出现同样的错误：
2020-02-26 22:54:14,934-INFO: Decompressing C:\Users\Dell/.cache/paddle/weights\yolov3_mobilenet_v1.tar...
Traceback (most recent call last):
  File "tools/train.py", line 338, in <module>
    main()
  File "tools/train.py", line 205, in main
    exe, train_prog, cfg.pretrain_weights, ignore_params=ignore_params)
  File "D:\pycharm\Health\learning\PaddleDetection\ppdet\utils\checkpoint.py", line 98, in load_params
    "exists.".format(path))
ValueError: Model pretrain path C:\Users\Dell/.cache/paddle/weights\yolov3_mobilenet_v1 does not exists.

**Comment by NanRUN** [comment]
前面说错了，打印后python shulti.move运行报错

**Comment by NanRUN** [comment]
您好，报错之后我发现这个路径下有这个文件夹生成.cache\paddle\yolov3_mobilenet_v1，里面有241个cnva和yolo开头的文件，但还是报错，是因为找不到文件还是解压到一半失败了呀

**Comment by NanRUN** [comment]
2020-02-26 23:46:18,737-INFO: Decompressing C:\Users\Dell/.cache/paddle/weights\yolov3_mobilenet_v1.tar...
Traceback (most recent call last):
  File "tools/train.py", line 338, in <module>
    main()
  File "tools/train.py", line 205, in main
    exe, train_prog, cfg.pretrain_weights, ignore_params=ignore_params)
  File "D:\pycharm\Health\learning\PaddleDetection\ppdet\utils\checkpoint.py", line 98, in load_params
    "exists.".format(path))
ValueError: Model pretrain path C:\Users\Dell/.cache/paddle/weights\yolov3_mobilenet_v1 does not exists.
这是具体报错

**Comment by NanRUN** [comment]
您好，能帮助一下我吗？

**Comment by zhwesky2010** [comment]
@NanRUN 我看一下哈

**Comment by NanRUN** [comment]
您好，报错之后我发现这个路径下有这个文件夹生成.cache\paddle\yolov3_mobilenet_v1，里面有241个cnva和yolo开头的文件，但还是报错，是因为找不到文件还是解压到一半失败了呀
