### ISSUE TITLE
如何能拿到fluid. ParamAttr参数，在训练过程中跟另外一个矩阵进行运算，比如layers.matmul()矩阵乘运算

### ISSUE THREAD

**Issue by lixuan1** [PaddlePaddle/Paddle#22727]
关于fluid. ParamAttr的参数，如果想拿到该参数在训练过程中进行layers.matmul()运算，总之就是进行运算，有方法可以转成variable类型吗？
<img width="522" alt="屏幕快照 2020-02-22 下午6 18 32" src="https://user-images.githubusercontent.com/9459980/75090712-a899c700-55a0-11ea-8296-ace1eb198534.png">
比如图中这样，我想要拿到这个嵌入的矩阵。因为想要拿到这个嵌入矩阵，去跟一个大数据得来的数据矩阵相乘，相当于又加了个权重分布。请问可以如何处理呢？

**Comment by liym27** [comment]
您好，可以通过param_t = fluid.global_scope().find_var(param_name)获取参数`param_attr`的Variable类型的变量。

**Comment by lixuan1** [comment]
你好，我之前试过该方法，得到的是空值，因为是在模型attention机制定义部分用到，是在训练过程中要用到，还未运行到run部分，所以是空的


 
---原始邮件---
发件人: "liym27"<notifications@github.com&gt;
发送时间: 2020年2月22日 22:09:46
收件人: "PaddlePaddle/Paddle"<Paddle@noreply.github.com&gt;;
抄送: "李萱"<463803586@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [PaddlePaddle/Paddle] 如何能拿到fluid. ParamAttr参数，在训练过程中跟另外一个矩阵进行运算，比如layers.matmul()矩阵乘运算 (#22727)



您好，可以通过param_t = fluid.global_scope().find_var(param_name)获取参数param_attr的Variable类型的变量。

**Comment by liym27** [comment]
不好意思，上述方法需要在run之后才能获取到值。
建议您尝试以下方法：
```
pro = fluid.default_main_program()
var = pro.global_block().var("sentiment_embedding")
```

**Comment by 1254859753** [comment]
请问这个问题解决了么，我也想在词向量中加权呢
