### ISSUE TITLE
如何用Python 预测 API进行多卡预测？

### ISSUE THREAD

**Issue by baiyfbupt** [PaddlePaddle/Paddle#22730]
预测引擎的配置选项`config.enable_use_gpu(100, 0)`一次只能选择一张GPU卡进行预测，有其他方法配置进行多卡预测吗？
https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/advanced_usage/deploy/inference/python_infer_cn.html#paddlepredictor

**Comment by FrostML** [comment]
一个 `predictor` 只支持一个线程，或是一张卡。
如果需要使用多张卡预测，每张卡需要使用不同的 `predictor`。
