### ISSUE TITLE
安装成功，运行失败 LENOVO T530, NVIDA NVS5400M, paddle.fluid ImportError: DLL load failed: 找不到指定的模块。

### ISSUE THREAD

**Issue by sidneyz139** [PaddlePaddle/Paddle#22732]
安装成功，运行失败
第一次安装paddle时曾经有warning错误，后重复安装时，看到的都是already satisfy，无warning/error.
Python3中 import paddle.fluid，报错“ImportError: DLL load failed: 找不到指定的模块。”具体日志见后。
安装指令 
- 版本、环境信息：
    1）PaddlePaddle版本：1.6.3
    2）CPU：Intel i7 3720QM , 
    3）GPU：NVIDIA NVS5400M，Intel HD Graphics 4000; 
          CUDA  10.2/10.0 + CUDNN 7.6.5
    4）系统环境：Lenovo T530, WIN10 professional 64BIT 、Python 3.7.6、PIP 20.0.2
- 安装方式信息：
pip安装 python3 -m pip install paddlepaddle-gpu==1.6.3.post107 -i https://mirror.baidu.com/pypi/simple
  
  特殊环境请注明：
1. 安装时，先按NVidia网站缺省安装的是10.2，不能成功运行后，选择了10.0再次安装，并切换了CUDA路径为10.0的路径
2. 检查版本是，返回的是64bit、AMD64；非常奇怪，明明是IntelCPU, 怎么是AMD64?
3. cudnn 已经拷贝了正确的版本到对应的目录下，不过cuda的安装目录不是缺省目录
4. MKL/OpenBlas/MKLDNN/等数学库的使用情况，不知道是什么，应该怎么检查?

系统运行信息见下面的截屏，错误信息见下面的运行日志
![image](https://user-images.githubusercontent.com/53903688/75113614-6947a500-568a-11ea-945b-e6e7d76c864c.png)
![image](https://user-images.githubusercontent.com/53903688/75113622-78c6ee00-568a-11ea-9b85-fa7f11cb13ae.png)
![image](https://user-images.githubusercontent.com/53903688/75113724-18847c00-568b-11ea-9a0d-64a744535ae3.png)
![image](https://user-images.githubusercontent.com/53903688/75113796-c001ae80-568b-11ea-9326-c8a11b3579fc.png)
![image](https://user-images.githubusercontent.com/53903688/75113827-0a832b00-568c-11ea-8aa9-ecbb6f492be3.png)
![image](https://user-images.githubusercontent.com/53903688/75113959-33f08680-568d-11ea-8f9c-8a33a37a9937.png)

安装日志
C:\Users\SidneyZ>python3 -m pip install paddlepaddle-gpu==1.6.3.post107 -i https://mirror.baidu.com/pypi/simple
Looking in indexes: https://mirror.baidu.com/pypi/simple
Requirement already satisfied: paddlepaddle-gpu==1.6.3.post107 in c:\users\sidneyz\appdata\local\packages\pythonsoftwarefoundation.python.3.7_qbz5n2kfra8p0\localcache\local-packages\python37\site-packages (1.6.3.post107)
Requirement already satisfied: matplotlib; python_version >= "3.6" in c:\users\sidneyz\appdata\local\packages\pythonsoftwarefoundation.python.3.7_qbz5n2kfra8p0\localcache\local-packages\python37\site-packages (from paddlepaddle-gpu==1.6.3.post107) (3.1.2)
Requirement already satisfied: opencv-python in c:\users\sidneyz\appdata\local\packages\pythonsoftwarefoundation.python.3.7_qbz5n2kfra8p0\localcache\local-packages\python37\site-packages (from paddlepaddle-gpu==1.6.3.post107) (4.1.0.25)
Requirement already satisfied: prettytable in c:\users\sidneyz\appdata\local\packages\pythonsoftwarefoundation.python.3.7_qbz5n2kfra8p0\localcache\local-packages\python37\site-packages (from paddlepaddle-gpu==1.6.3.post107) (0.7.2)
Requirement already satisfied: protobuf>=3.1.0 in c:\users\sidneyz\appdata\local\packages\pythonsoftwarefoundation.python.3.7_qbz5n2kfra8p0\localcache\local-packages\python37\site-packages (from paddlepaddle-gpu==1.6.3.post107) (3.11.3)
Requirement already satisfied: funcsigs in c:\users\sidneyz\appdata\local\packages\pythonsoftwarefoundation.python.3.7_qbz5n2kfra8p0\localcache\local-packages\python37\site-packages (from paddlepaddle-gpu==1.6.3.post107) (1.0.2)
Requirement already satisfied: numpy>=1.12; python_version >= "3.5" in c:\users\sidneyz\appdata\local\packages\pythonsoftwarefoundation.python.3.7_qbz5n2kfra8p0\localcache\local-packages\python37\site-packages (from paddlepaddle-gpu==1.6.3.post107) (1.18.1)
Requirement already satisfied: scipy; python_version >= "3.5" in c:\users\sidneyz\appdata\local\packages\pythonsoftwarefoundation.python.3.7_qbz5n2kfra8p0\localcache\local-packages\python37\site-packages (from paddlepaddle-gpu==1.6.3.post107) (1.4.1)
Requirement already satisfied: Pillow in c:\users\sidneyz\appdata\local\packages\pythonsoftwarefoundation.python.3.7_qbz5n2kfra8p0\localcache\local-packages\python37\site-packages (from paddlepaddle-gpu==1.6.3.post107) (7.0.0)
Requirement already satisfied: rarfile in c:\users\sidneyz\appdata\local\packages\pythonsoftwarefoundation.python.3.7_qbz5n2kfra8p0\localcache\local-packages\python37\site-packages (from paddlepaddle-gpu==1.6.3.post107) (3.1)
Requirement already satisfied: decorator in c:\users\sidneyz\appdata\local\packages\pythonsoftwarefoundation.python.3.7_qbz5n2kfra8p0\localcache\local-packages\python37\site-packages (from paddlepaddle-gpu==1.6.3.post107) (4.4.1)
Requirement already satisfied: graphviz in c:\users\sidneyz\appdata\local\packages\pythonsoftwarefoundation.python.3.7_qbz5n2kfra8p0\localcache\local-packages\python37\site-packages (from paddlepaddle-gpu==1.6.3.post107) (0.13.2)
Requirement already satisfied: pyyaml in c:\users\sidneyz\appdata\local\packages\pythonsoftwarefoundation.python.3.7_qbz5n2kfra8p0\localcache\local-packages\python37\site-packages (from paddlepaddle-gpu==1.6.3.post107) (5.3)
Requirement already satisfied: objgraph in c:\users\sidneyz\appdata\local\packages\pythonsoftwarefoundation.python.3.7_qbz5n2kfra8p0\localcache\local-packages\python37\site-packages (from paddlepaddle-gpu==1.6.3.post107) (3.4.1)
Requirement already satisfied: six in c:\users\sidneyz\appdata\local\packages\pythonsoftwarefoundation.python.3.7_qbz5n2kfra8p0\localcache\local-packages\python37\site-packages (from paddlepaddle-gpu==1.6.3.post107) (1.14.0)
Requirement already satisfied: nltk; python_version >= "3.5" in c:\users\sidneyz\appdata\local\packages\pythonsoftwarefoundation.python.3.7_qbz5n2kfra8p0\localcache\local-packages\python37\site-packages (from paddlepaddle-gpu==1.6.3.post107) (3.4.5)
Requirement already satisfied: requests>=2.20.0 in c:\users\sidneyz\appdata\local\packages\pythonsoftwarefoundation.python.3.7_qbz5n2kfra8p0\localcache\local-packages\python37\site-packages (from paddlepaddle-gpu==1.6.3.post107) (2.22.0)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 in c:\users\sidneyz\appdata\local\packages\pythonsoftwarefoundation.python.3.7_qbz5n2kfra8p0\localcache\local-packages\python37\site-packages (from matplotlib; python_version >= "3.6"->paddlepaddle-gpu==1.6.3.post107) (2.4.6)
Requirement already satisfied: cycler>=0.10 in c:\users\sidneyz\appdata\local\packages\pythonsoftwarefoundation.python.3.7_qbz5n2kfra8p0\localcache\local-packages\python37\site-packages (from matplotlib; python_version >= "3.6"->paddlepaddle-gpu==1.6.3.post107) (0.10.0)
Requirement already satisfied: kiwisolver>=1.0.1 in c:\users\sidneyz\appdata\local\packages\pythonsoftwarefoundation.python.3.7_qbz5n2kfra8p0\localcache\local-packages\python37\site-packages (from matplotlib; python_version >= "3.6"->paddlepaddle-gpu==1.6.3.post107) (1.1.0)
Requirement already satisfied: python-dateutil>=2.1 in c:\users\sidneyz\appdata\local\packages\pythonsoftwarefoundation.python.3.7_qbz5n2kfra8p0\localcache\local-packages\python37\site-packages (from matplotlib; python_version >= "3.6"->paddlepaddle-gpu==1.6.3.post107) (2.8.1)
Requirement already satisfied: setuptools in c:\program files\windowsapps\pythonsoftwarefoundation.python.3.7_3.7.1776.0_x64__qbz5n2kfra8p0\lib\site-packages (from protobuf>=3.1.0->paddlepaddle-gpu==1.6.3.post107) (41.2.0)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in c:\users\sidneyz\appdata\local\packages\pythonsoftwarefoundation.python.3.7_qbz5n2kfra8p0\localcache\local-packages\python37\site-packages (from requests>=2.20.0->paddlepaddle-gpu==1.6.3.post107) (1.25.8)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in c:\users\sidneyz\appdata\local\packages\pythonsoftwarefoundation.python.3.7_qbz5n2kfra8p0\localcache\local-packages\python37\site-packages (from requests>=2.20.0->paddlepaddle-gpu==1.6.3.post107) (3.0.4)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\sidneyz\appdata\local\packages\pythonsoftwarefoundation.python.3.7_qbz5n2kfra8p0\localcache\local-packages\python37\site-packages (from requests>=2.20.0->paddlepaddle-gpu==1.6.3.post107) (2019.11.28)
Requirement already satisfied: idna<2.9,>=2.5 in c:\users\sidneyz\appdata\local\packages\pythonsoftwarefoundation.python.3.7_qbz5n2kfra8p0\localcache\local-packages\python37\site-packages (from requests>=2.20.0->paddlepaddle-gpu==1.6.3.post107) (2.8)

C:\Users\SidneyZ>
C:\Users\SidneyZ>python3
Python 3.7.6 (tags/v3.7.6:43364a7ae0, Dec 19 2019, 01:54:44) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import paddle.fluid
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\SidneyZ\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\paddle\fluid\__init__.py", line 35, in <module>
    from . import framework
  File "C:\Users\SidneyZ\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\paddle\fluid\framework.py", line 35, in <module>
    from . import core
  File "C:\Users\SidneyZ\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\paddle\fluid\core.py", line 187, in <module>
    raise e
  File "C:\Users\SidneyZ\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\paddle\fluid\core.py", line 167, in <module>
    from .core_avx import *
ImportError: DLL load failed: 找不到指定的模块。
>>>

**Comment by zhwesky2010** [comment]
@sidneyz139 你好，请问cudnn版本是多少呢？环境变量里的CUDA_PATH路径和你的实际路径对上了吗？

**Comment by zhwesky2010** [comment]
@sidneyz139 麻烦再看一下PATH里的路径有没有cuda相关的？

**Comment by sidneyz139** [comment]
cudnn 7.6.5
CUDA_PATH是正确的。我 import paddle 可以成功，但import paddle.fluid失败。

![image](https://user-images.githubusercontent.com/53903688/75131008-fd0d8580-570b-11ea-8132-19cc7ba60e75.png)
![image](https://user-images.githubusercontent.com/53903688/75131055-2e865100-570c-11ea-94e4-ddb32583e468.png)

**Comment by zhwesky2010** [comment]
@sidneyz139  cudnn都拷贝到了 D:\Program Files\NvidiaGPUToolkit\CUDA\V10.0里了吗，电脑一共装了几个python呢

**Comment by sidneyz139** [comment]
电脑上只有2个，PYTHON 3.7.6是我装的，以前机器上就有；微软那个是安装visural studio 2019自带安装的。 我通常启动是用 python3 理论上是在Python的那个，微软那个不知怎么用，没用过。
cudnn已经都拷贝好了，因为机器上有2个版本的CUDA, 先安装了10.2，不能用，后来又安装了10.0.
对应的目录下，都已经拷贝好了正确版本的cudnn。
多个Python有什么隐患吗？
![image](https://user-images.githubusercontent.com/53903688/75136768-a2caef80-5720-11ea-8928-db6b9986780d.png)
![image](https://user-images.githubusercontent.com/53903688/75137026-68ae1d80-5721-11ea-9c2d-ca13fa966281.png)

**Comment by DDDivano** [comment]
显卡驱动版本？

**Comment by zhwesky2010** [comment]
@sidneyz139  建议用一个全新的python环境试下，可能是之前这个python装过某版本的python库，但是和paddle不符合，因为already satisfy表明其实没有新装。
装完之后，记得看PATH里的环境变量，需要改一下

**Comment by sidneyz139** [comment]
@DDDivano NVIDIA NVS 5400M,  驱动版本 392.58
![image](https://user-images.githubusercontent.com/53903688/75144541-188b8700-5732-11ea-9bc9-0071b0305b73.png)

**Comment by sidneyz139** [comment]
@zhouwei25 
where python 显示只有2个python, 我卸载了之前最早的那个，保留了微软vs2019刚刚安装的那个。
现在用where python, 只显示微软的那个目录，如图。
但当我运行起来python 后，竟然是另外一个没显示的目录里的python在运行。
问题是，这个没有出现在 where python的版本，应该如何卸载？ 直接删除目录吗？
![image](https://user-images.githubusercontent.com/53903688/75147775-12e56f80-5739-11ea-8ec3-a74635a0d856.png)
![image](https://user-images.githubusercontent.com/53903688/75147887-50e29380-5739-11ea-961f-bfa54ec5567d.png)

**Comment by zhwesky2010** [comment]
你可以新装一个python，比如装到 c:\Python36里，那就set PATH=c:\Python36;c:\Python36\scripts;%PATH%，这个PATH是根据顺序来的，把它排前面来就会生效

**Comment by sidneyz139** [comment]
重新安装一个在d:，PATH也修改好了。直接在CMD里运行时，启动的的确是新安装的，新安装的里面也带PIP。
但一旦运行 python3 -m ensurepip，python3 -m pip --version， 就又切换回原来的Python了。
在莫名其妙的目录里 C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.1776.0_x64__qbz5n2kfra8p0
这个目录，根本没有出现在 where python 中，也在安装程序中找不到， PATH中也没有。
这个所谓的foundation下面的python是怎么运行起来的？如何卸载？

![image](https://user-images.githubusercontent.com/53903688/75151427-a327b280-5741-11ea-946c-ec51fd2487d4.png)
![image](https://user-images.githubusercontent.com/53903688/75151539-e3873080-5741-11ea-8d1e-36618139a008.png)
![image](https://user-images.githubusercontent.com/53903688/75151752-660ff000-5742-11ea-9836-438c24e8e6a1.png)

**Comment by sidneyz139** [comment]
要么的是，这个目录的上级目录，无法进入，不让删除这个目录。

**Comment by zhwesky2010** [comment]
因为你的C:/Python37中没有python3.exe，所以python3.exe可能在其他地方。你可以where python3看看。现在你只要使用python（无需python3），默认就是调用C:/Python37/Python.exe，如果是一个纯净的python环境，装paddle试一下。检查下where pip 应该C:/Python37/scripts

**Comment by sidneyz139** [comment]
找到那个莫名其妙目录的来源了，是win10的store的东西，在安装VS2019 python环境是装上的，从store里卸载掉，一切就正常了。
感谢大家的帮助，尤其是 @zhouwei25 提供的检查思路。
