### ISSUE TITLE
fluid.io.save_inference_model 报错

### ISSUE THREAD

**Issue by Angus07** [PaddlePaddle/Paddle#22742]
保存模型时报错
Traceback (most recent call last):
  File "./httpserver.py", line 203, in <module>
    main_test()
  File "./httpserver.py", line 145, in main_test
    target_vars=[seg_ids, seg_scores, data_ids], executor=exe)
  File "/run/chenliangyu/title_http/output/python/lib/python2.7/site-packages/paddle/fluid/io.py", line 1187, in save_inference_model
    prepend_feed_ops(main_program, feeded_var_names)
  File "/run/chenliangyu/title_http/output/python/lib/python2.7/site-packages/paddle/fluid/io.py", line 986, in prepend_feed_ops
    out = global_block.var(name)
  File "/run/chenliangyu/title_http/output/python/lib/python2.7/site-packages/paddle/fluid/framework.py", line 2234, in var
    raise ValueError("var %s not in this block" % name)
ValueError: var input_mask_encoder not in this block

核心调用代码如下：
with fluid.program_guard(fluid.default_main_program(), startup_prog):
    with fluid.unique_name.guard():
        test_graph_vars, seg_ids, seg_scores, data_ids = create_model(
            args,
            pyreader_name='test_reader',
            ernie_config=ernie_config,
            is_prediction=args.do_dec)

test_prog = fluid.default_main_program().clone(for_test=True)

exe = fluid.Executor(place)
path = "./infer_model"
exe.run(startup_prog)
fluid.io.save_inference_model(dirname=path, feeded_var_names=['src_ids', "sent_ids","pos_ids", "input_mask", "input_mask_encoder", "tgt_ids", "init_scores", "parent_idx",
                                                              "tgt_input_mask", "tgt_start_pos", "data_ids"],
                              target_vars=[seg_ids, seg_scores, data_ids], executor=exe)

这个变量是存在的, 代码如下：
    src_ids = layers.data(name="src_ids", shape=[-1, args.max_seq_len, 1], dtype='int64', lod_level=0)
    sent_ids = layers.data(name="sent_ids", shape=[-1, args.max_seq_len, 1], dtype='int64', lod_level=0)
    pos_ids = layers.data(name="pos_ids", shape=[-1, args.max_seq_len, 1], dtype='int64', lod_level=0)
    input_mask = layers.data(name="input_mask", shape=[-1, args.max_seq_len, args.max_seq_len], dtype='float32',
                             lod_level=0)
    input_mask_encoder = layers.data(name="input_mask_encoder", shape=[-1, args.max_seq_len, args.max_seq_len],
                                     dtype='float32', lod_level=0)
    tgt_ids = layers.data(name="tgt_ids", shape=[-1, args.max_seq_len, 1], dtype='int64', lod_level=2)
    init_scores = layers.data(name="init_scores", shape=[-1, 1], dtype='float32', lod_level=2)
    parent_idx = layers.data(name="parent_idx", shape=[-1], dtype='int32', lod_level=0)
    tgt_input_mask = layers.data(name="tgt_input_mask", shape=[-1, 1, args.max_seq_len], dtype='float32', lod_level=0)
    tgt_start_pos = layers.data(name="tgt_start_pos", shape=[-1, 1], dtype='int64', lod_level=0)
    data_ids = layers.data(name="data_ids", shape=[-1, -1], dtype='int64', lod_level=0)

**Comment by Shixiaowei02** [comment]
> 保存模型时报错
> Traceback (most recent call last):
> File "./httpserver.py", line 203, in 
> main_test()
> File "./httpserver.py", line 145, in main_test
> target_vars=[seg_ids, seg_scores, data_ids], executor=exe)
> File "/run/chenliangyu/title_http/output/python/lib/python2.7/site-packages/paddle/fluid/io.py", line 1187, in save_inference_model
> prepend_feed_ops(main_program, feeded_var_names)
> File "/run/chenliangyu/title_http/output/python/lib/python2.7/site-packages/paddle/fluid/io.py", line 986, in prepend_feed_ops
> out = global_block.var(name)
> File "/run/chenliangyu/title_http/output/python/lib/python2.7/site-packages/paddle/fluid/framework.py", line 2234, in var
> raise ValueError("var %s not in this block" % name)
> ValueError: var input_mask_encoder not in this block
> 
> 核心调用代码如下：
> with fluid.program_guard(fluid.default_main_program(), startup_prog):
> with fluid.unique_name.guard():
> test_graph_vars, seg_ids, seg_scores, data_ids = create_model(
> args,
> pyreader_name='test_reader',
> ernie_config=ernie_config,
> is_prediction=args.do_dec)
> 
> test_prog = fluid.default_main_program().clone(for_test=True)
> 
> exe = fluid.Executor(place)
> path = "./infer_model"
> exe.run(startup_prog)
> fluid.io.save_inference_model(dirname=path, feeded_var_names=['src_ids', "sent_ids","pos_ids", "input_mask", "input_mask_encoder", "tgt_ids", "init_scores", "parent_idx",
> "tgt_input_mask", "tgt_start_pos", "data_ids"],
> target_vars=[seg_ids, seg_scores, data_ids], executor=exe)
> 
> 这个变量是存在的, 代码如下：
> src_ids = layers.data(name="src_ids", shape=[-1, args.max_seq_len, 1], dtype='int64', lod_level=0)
> sent_ids = layers.data(name="sent_ids", shape=[-1, args.max_seq_len, 1], dtype='int64', lod_level=0)
> pos_ids = layers.data(name="pos_ids", shape=[-1, args.max_seq_len, 1], dtype='int64', lod_level=0)
> input_mask = layers.data(name="input_mask", shape=[-1, args.max_seq_len, args.max_seq_len], dtype='float32',
> lod_level=0)
> input_mask_encoder = layers.data(name="input_mask_encoder", shape=[-1, args.max_seq_len, args.max_seq_len],
> dtype='float32', lod_level=0)
> tgt_ids = layers.data(name="tgt_ids", shape=[-1, args.max_seq_len, 1], dtype='int64', lod_level=2)
> init_scores = layers.data(name="init_scores", shape=[-1, 1], dtype='float32', lod_level=2)
> parent_idx = layers.data(name="parent_idx", shape=[-1], dtype='int32', lod_level=0)
> tgt_input_mask = layers.data(name="tgt_input_mask", shape=[-1, 1, args.max_seq_len], dtype='float32', lod_level=0)
> tgt_start_pos = layers.data(name="tgt_start_pos", shape=[-1, 1], dtype='int64', lod_level=0)
> data_ids = layers.data(name="data_ids", shape=[-1, -1], dtype='int64', lod_level=0)

您好，可能有两个原因导致此问题：
1、变量不存在于 Block 0；
2、变量不在预测模型保存时提供输入输出节点的连通计算图中，在保存模型时被裁剪。

**Comment by Angus07** [comment]
> > 保存模型时报错
> > Traceback (most recent call last):
> > File "./httpserver.py", line 203, in
> > main_test()
> > File "./httpserver.py", line 145, in main_test
> > target_vars=[seg_ids, seg_scores, data_ids], executor=exe)
> > File "/run/chenliangyu/title_http/output/python/lib/python2.7/site-packages/paddle/fluid/io.py", line 1187, in save_inference_model
> > prepend_feed_ops(main_program, feeded_var_names)
> > File "/run/chenliangyu/title_http/output/python/lib/python2.7/site-packages/paddle/fluid/io.py", line 986, in prepend_feed_ops
> > out = global_block.var(name)
> > File "/run/chenliangyu/title_http/output/python/lib/python2.7/site-packages/paddle/fluid/framework.py", line 2234, in var
> > raise ValueError("var %s not in this block" % name)
> > ValueError: var input_mask_encoder not in this block
> > 核心调用代码如下：
> > with fluid.program_guard(fluid.default_main_program(), startup_prog):
> > with fluid.unique_name.guard():
> > test_graph_vars, seg_ids, seg_scores, data_ids = create_model(
> > args,
> > pyreader_name='test_reader',
> > ernie_config=ernie_config,
> > is_prediction=args.do_dec)
> > test_prog = fluid.default_main_program().clone(for_test=True)
> > exe = fluid.Executor(place)
> > path = "./infer_model"
> > exe.run(startup_prog)
> > fluid.io.save_inference_model(dirname=path, feeded_var_names=['src_ids', "sent_ids","pos_ids", "input_mask", "input_mask_encoder", "tgt_ids", "init_scores", "parent_idx",
> > "tgt_input_mask", "tgt_start_pos", "data_ids"],
> > target_vars=[seg_ids, seg_scores, data_ids], executor=exe)
> > 这个变量是存在的, 代码如下：
> > src_ids = layers.data(name="src_ids", shape=[-1, args.max_seq_len, 1], dtype='int64', lod_level=0)
> > sent_ids = layers.data(name="sent_ids", shape=[-1, args.max_seq_len, 1], dtype='int64', lod_level=0)
> > pos_ids = layers.data(name="pos_ids", shape=[-1, args.max_seq_len, 1], dtype='int64', lod_level=0)
> > input_mask = layers.data(name="input_mask", shape=[-1, args.max_seq_len, args.max_seq_len], dtype='float32',
> > lod_level=0)
> > input_mask_encoder = layers.data(name="input_mask_encoder", shape=[-1, args.max_seq_len, args.max_seq_len],
> > dtype='float32', lod_level=0)
> > tgt_ids = layers.data(name="tgt_ids", shape=[-1, args.max_seq_len, 1], dtype='int64', lod_level=2)
> > init_scores = layers.data(name="init_scores", shape=[-1, 1], dtype='float32', lod_level=2)
> > parent_idx = layers.data(name="parent_idx", shape=[-1], dtype='int32', lod_level=0)
> > tgt_input_mask = layers.data(name="tgt_input_mask", shape=[-1, 1, args.max_seq_len], dtype='float32', lod_level=0)
> > tgt_start_pos = layers.data(name="tgt_start_pos", shape=[-1, 1], dtype='int64', lod_level=0)
> > data_ids = layers.data(name="data_ids", shape=[-1, -1], dtype='int64', lod_level=0)
> 
> 您好，可能有两个原因导致此问题：
> 1、变量不存在于 Block 0；
> 2、变量不在预测模型保存时提供输入输出节点的连通计算图中，在保存模型时被裁剪。

1.怎么确定是由哪个问题导致的？
2.如果不存在于 Block 0, 如何让变量存在于 Block 0?
3.如果变量不在连通计算图中，如何让变量加入到连通计算图中？

**Comment by Shixiaowei02** [comment]
可以将 program 打印出来哈，这是一个 protobuf 形式的数据结构。

我怀疑问题是你保存模型时，并没有将网络所有的输入输出节点加入到 save_inference_model 的参数中，你可以试着将所有叶子变量放到参数列表中，保存完整的计算图，再看下问题是否消失。

我们后续会修改报错消息，的确这个报错不太明确。谢谢。

**Comment by Angus07** [comment]
1.根据我的理解，我已经把所有的输入和输入都放到save_inference_model 的参数中。
2.有值班同学怀疑可能是用name获取变量，但是name被自动加了前缀，导致匹配不上导致的，经过我自己排查，已经排除了这种可能性。
3.我已将运行环境整理给值班同学，帮我看了一天，也没有看出问题。

**Comment by Shixiaowei02** [comment]
<img width="467" alt="8c14b4a0bb65c6598bc905b3d6c7fd75" src="https://user-images.githubusercontent.com/39303645/75682157-ed73db00-5ccf-11ea-907e-db5a88eedb65.png">

看起来是保存预测模型时，图的输入和输出节点试图一致导致的错误。请认真检查程序，确认业务代码原因。谢谢。

**Comment by Angus07** [comment]
尝试把作为输出节点的输入节点去掉了，然后报一样的错误

**Comment by Shixiaowei02** [comment]
将保存模型的参数去掉 "tgt_start_pos", "data_ids"，并设置 ./finetune/seq2seq.py:242 中临时变量的 persistable 为 False 解决当前不能保存的问题。

请后续注意一下 save_inference_model 对参数的必要条件：
1、每个输入都要有与之在图中连通的一个或多个输出节点；
2、节点不能既是输入节点，又是输出节点。
并且注意慎重显式设置变量为 persistable=True。

Paddle 会尽快增强报错信息，将上述警告直接提示给用户。

谢谢

**Comment by Angus07** [comment]
报错信息是找不到input_mask_encoder这个变量，根据我的检查，这个变量应该是参与网络计算的，这个关键问题仍然没有解决。目前保存的图无法进行预测，目前我正在检查原因，不排查是因为这个input_mask_encoder导致的。

**Comment by eshaoliu** [comment]
请问这个问题解决了吗？我也遇到了类似的问题
