### ISSUE TITLE
如何生成随机整数

### ISSUE THREAD

**Issue by txyugood** [PaddlePaddle/Paddle#22750]
遇到一个问题， 在训练过程中，有每次迭代需要生成随机整数的需求，类似 matlab 中 randperm 这种。看了文档和 github 好像没有这种接口，请问有什么办法可以实现吗？

**Comment by juncaipeng** [comment]
目前查看文档没有提供类似的函数，你可以考虑每次迭代的时候，使用feed或者DataLoader传入随机整数。

**Comment by txyugood** [comment]
感谢回复，我需要根据每次迭代的时候某个 Tensor 的值来生成不同数量的随机数。按您说的这种方式的话，是不是就需要先 fetch，然后生成随机数再 feed 了。这样是不是就需要建立多个 program. 重复执行静态图，速度会慢一些吧，程序也会复杂一些？

**Comment by juncaipeng** [comment]
哦哦，目前我已知的是这样，明天问下是否有更好的方法。

**Comment by juncaipeng** [comment]
> 感谢回复，我需要根据每次迭代的时候某个 Tensor 的值来生成不同数量的随机数。按您说的这种方式的话，是不是就需要先 fetch，然后生成随机数再 feed 了。这样是不是就需要建立多个 program. 重复执行静态图，速度会慢一些吧，程序也会复杂一些？

目前没有支持的op实现该功能，另外一种方法是，按照官网文档添加新的op进行实现。
