### ISSUE TITLE
py_func是不是不支持object member function呢？ 如果func需要外部的资源，该怎么做呢？

### ISSUE THREAD

**Issue by fseasy** [PaddlePaddle/Paddle#22770]
- 标题：使用member function 给py_func的func参数，但是报错； 我的func需要访问tensor外的外部资源，该怎么做呢？
- 版本、环境信息：
    1）PaddlePaddle版本：1.6.3
    2）CPU/GPU：CUDA Capability: 70, Driver API Version: 10.1, Runtime API Version: 10.0
    3）系统环境：CentOS 7
    4）Python版本号 3.7.4
    5）显存信息: 32G
- 复现信息：

```

class O(object):
    def __init__(self):
         self._global_data = ["a", "b", "c"]
    def forward(self, t):
          return numpy.array([1,2])

----
o = O()
fluid.layers.py_func(x=t,  func=o.forward, ...)

```

- 问题描述：

报错：
```
py_func raises an exception pybind11::error_already_set, IndexError: tuple index out of range

```

**Comment by jiweibo** [comment]
> o.forward

o.forward函数有两个参数，self和t。但是py_func的输入x只有1个

建议不要使用成员函数作为py_func的参数。

**Comment by fseasy** [comment]
那如果func需要访问外部变量怎么做呢？ 只能将其设为全局变量吗，或者闭包可以吗？
——————
背景是这样的， 我想在这个func里面做 一个 id -> token 的转换，但是这需要访问vocab，如果不能访问它，就不好弄了

**Comment by jiweibo** [comment]
> 那如果func需要访问外部变量怎么做呢？ 只能将其设为全局变量吗
> ——————
> 背景是这样的， 我想在这个func里面做 一个 id -> token 的转换，但是这需要访问vocab，如果不能访问它，就不好弄了

py_func实际上是通过python来加op的方式，本质上还是op，是不依赖外部变量的，只有输入，输出，属性等。比如有了新的激活函数，paddle c++ op还不支持，用户又不想要写c++ op，此时用py_func。

做一个id->token的转换，建议使用其它的方式。我理解的这个用法并不是一个op，自己写函数来处理会比较好

**Comment by fseasy** [comment]
额，我刚刚试了返回闭包函数，报错了；那就是说闭包函数是不行的是吧；
——————
这个其实也算是一个OP； 
在 生成任务（特别是摘要）中，在解码是有一个 block duplicated trigram的操作，需要算生成的序列是否包含连续重复trigram；而我们的id是 sub-token的id，需要先转为完整的token，再判断；
所以是需要这个操作的哈；
我刚刚想到了一个绕过的办法…… 我再试试吧； 

另外，我记得tf的py_function好像支持访问外部变量呢（如果我没记错的话，我看到人家用这个来包装ROUGE计算）？

**Comment by songyouwei** [comment]
id -> token 要访问外部的 vocab，那  id 和 vocab 是可以作为一个 dict 参数给过去的吧

**Comment by fseasy** [comment]
嗯嗯，但是我看Paddle不支持 np.str 这种类型？ 
我其实也不需要完整的 id -> token，其实只需要 `知道这个id对应的token是不是完整token` 就行了，我准备构造一个float的Variable传进去，这样应该可以了吧 = =

**Comment by jiweibo** [comment]
> 嗯嗯，但是我看Paddle不支持 np.str 这种类型？
> 我其实也不需要完整的 id -> token，其实只需要 `知道这个id对应的token是不是完整token` 就行了，我准备构造一个float的Variable传进去，这样应该可以了吧 = =

对的，目前没有支持str。py_func默认接受的参数现在只能是variable（list、tuple等），tf_py_func本质也是接收list tensor的。

**Comment by fseasy** [comment]
额，麻烦看看这个是为什么呀，是我写法错了吗，还是不支持...

```
TypeError: ("The type of 'X' in operator py_func should be one of [basestring(), str, Varibale] in python2, or one of [str, bytes, Variable] in python3.but received : ", (name: "fill_constant_batch_size_like_24.tmp_0"
type {
  type: LOD_TENSOR
  lod_tensor {
    tensor {
      data_type: INT64
      dims: -1
      dims: 0
      dims: 1
    }
  }
}
persistable: false
, name: "duplicated_trigram_blocking_id2is_full_token"
type {
  type: LOD_TENSOR
  lod_tensor {
    tensor {
      data_type: FP32
      dims: 30522
    }
  }
}
persistable: true
))

```

**Comment by jiweibo** [comment]
> 额，麻烦看看这个是为什么呀，是我写法错了吗，还是不支持...
> 
> ```
> TypeError: ("The type of 'X' in operator py_func should be one of [basestring(), str, Varibale] in python2, or one of [str, bytes, Variable] in python3.but received : ", (name: "fill_constant_batch_size_like_24.tmp_0"
> type {
>   type: LOD_TENSOR
>   lod_tensor {
>     tensor {
>       data_type: INT64
>       dims: -1
>       dims: 0
>       dims: 1
>     }
>   }
> }
> persistable: false
> , name: "duplicated_trigram_blocking_id2is_full_token"
> type {
>   type: LOD_TENSOR
>   lod_tensor {
>     tensor {
>       data_type: FP32
>       dims: 30522
>     }
>   }
> }
> persistable: true
> ))
> ```

应该是解析输入后，得到输入列表或tuple里的元素还是tuple。 
tuple(variable0, variable1)，找到需要的varibale，加下索引应该就可以

**Comment by fseasy** [comment]
= =，的确是输入问题，不过应该是已知BUG：
```
py_func(...x=(a, b), ...) ERROR
py_func(...x=[a, b], ...) OK
```
暂时框架跑起来了，我再写下内容…… 
感谢

**Comment by jiweibo** [comment]
> = =，的确是输入问题，不过应该是已知BUG：
> 
> ```
> py_func(...x=(a, b), ...) ERROR
> py_func(...x=[a, b], ...) OK
> ```
> 
> 暂时框架跑起来了，我再写下内容……
> 感谢

https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api_cn/layers_cn/py_func_cn.html

代码示例2中，x=[a,b]和x=(a,b)都没有问题的呀。

**Comment by fseasy** [comment]
这个应该是develop分支吧，我这里还只是1.6.3哈，我刚刚是这样的结果哈，把tuple换成list的确就好了

**Comment by fseasy** [comment]
从
https://github.com/PaddlePaddle/Paddle/blob/release/1.6/python/paddle/fluid/layers/nn.py#L16277
这里看，py_func是不是应该有可能支持member_function呢，只是现在做了参数限定，导致非Variable传不进去？ 如果可以的话，把参数放开应该更好~

**Comment by jiweibo** [comment]
> 从
> https://github.com/PaddlePaddle/Paddle/blob/release/1.6/python/paddle/fluid/layers/nn.py#L16277
> 这里看，py_func是不是应该有可能支持member_function呢，只是现在做了参数限定，导致非Variable传不进去？ 如果可以的话，把参数放开应该更好~

默认要把python端的variable数据传给c++端，目前c++的py_func op还是只能接收variable的；我们理解非variable的参数可以尽量在调用py_func之前处理完。

**Comment by fseasy** [comment]
Variable传给C++是为了获得实际的LodTensor值吗？ 
能不能这样，把非Variable留在Python侧，Variable给C++，C++调用回来，再组合Python侧的参数，给调用函数；
因为我看真正的函数调用发生在Python侧，如果是这样，那就肯定可以实现支持非Variable参数了；
————
个人理解哈，不一定看懂了代码

**Comment by jiweibo** [comment]
> Variable传给C++是为了获得实际的LodTensor值吗？
> 能不能这样，把非Variable留在Python侧，Variable给C++，C++调用回来，再组合Python侧的参数，给调用函数；
> 因为我看真正的函数调用发生在Python侧，如果是这样，那就肯定可以实现支持非Variable参数了；
> ————
> 个人理解哈，不一定看懂了代码

感谢建议，是可以的哈，后续需要升级的时候在考虑加一下

**Comment by fseasy** [comment]
好的，期待升级

**Comment by jiweibo** [comment]
> 好的，期待升级

目前这样做主要是为了接口的统一，c++侧的callable 是 py_func中的前向。

调用过程如下
auto ret = (*callable)(*in_args);

in_args就是lits(variable)，没有加入其它python函数，这里就比较简洁，否则要定义python侧的arg，再绑到c++，最后调用，也能做就是不太漂亮，所以目前是交给用户在python中处理了

**Comment by fseasy** [comment]
啊，到这个程度我就不能很好的理解了哈 😂 
我想py_func的能力上限肯定是支持用户任意的操作，这个也是静态图变“灵活”的关键；现在支持的功能的确已经足够好了哈，如果后续可能再进一步的话当然是更好~
之前我测试，发现在定义的前向函数里可以访问全局变量，不过当时没有很认真的测试，不知是否可以无问题的访问；如果能够无错误地支持全局变量访问，那我想用于py_func的函数也应该可以实现任意的功能，就是不够“简洁” 😂
