### ISSUE TITLE
请问一下，paddle.fluid.layers.mean_iou()函数支持batch图像的计算吗，还是一次只能计算一张图像呢？

### ISSUE THREAD

**Issue by songyuc** [PaddlePaddle/Paddle#22781]
你好！
请问一下，paddle.fluid.layers.mean_iou()函数支持batch多张图像的计算吗，还是一次只能计算一张图像的mIoU呢？
期待你的回复！

**Comment by JepsonWong** [comment]
可以支持一个batch的计算，参见官网文档 https://www.paddlepaddle.org.cn/documentation/docs/zh/1.7/api_cn/layers_cn/mean_iou_cn.html#mean-iou
