### ISSUE TITLE
如何让模型知道是在跑training还是validation？

### ISSUE THREAD

**Issue by hohaxu** [PaddlePaddle/Paddle#2278]
根据文档里，dataprovider里面的is_train可以用来区别是在跑training还是validation

想问下有啥办法可以把这个参数传到模型的文件里？谢谢

**Comment by byzhang** [comment]
@reyoung it sounds an interesting question.

**Comment by jacquesqiao** [comment]
模型具体做的工作，配置完之后已经确定了，要么是training，要么是testing
