### ISSUE TITLE
恢复训练时，损失函数会上升，上升不止一点，有时候是将近5倍

### ISSUE THREAD

**Issue by ahsdx** [PaddlePaddle/Paddle#22791]
Aistudio上进行恢复训练有问题：
下面是恢复训练前的total_loss
2020-02-27 18:09:13,889 - train.py[line:148] - INFO: epoch 35, step 840, total_loss: 0.03663
loss_cls: 0.01022, loss_bbox: 0.02641, fg_num: 103, lr: 0.00133
2020-02-27 18:09:18,844 - train.py[line:148] - INFO: epoch 35, step 845, total_loss: 0.03665
loss_cls: 0.01024, loss_bbox: 0.02641, fg_num: 103, lr: 0.00133
2020-02-27 18:09:22,940 - train.py[line:152] - INFO: Model saved.
2020-02-27 18:09:24,562 - train.py[line:148] - INFO: epoch 36, step 0, total_loss: 0.03443
loss_cls: 0.00772, loss_bbox: 0.02671, fg_num: 113, lr: 0.00133
2020-02-27 18:09:29,837 - train.py[line:148] - INFO: epoch 36, step 5, total_loss: 0.03353
loss_cls: 0.01012, loss_bbox: 0.02341, fg_num: 112, lr: 0.00133
2020-02-27 18:09:35,410 - train.py[line:148] - INFO: epoch 36, step 10, total_loss: 0.03135
loss_cls: 0.00918, loss_bbox: 0.02217, fg_num: 104, lr: 0.00133
2020-02-27 18:09:40,857 - train.py[line:148] - INFO: epoch 36, step 15, total_loss: 0.03251
我的加载预训练的代码：（cfg['pretrained']是我上次模型保存的路径）
    start_program = fluid.default_startup_program()
    main_program = fluid.default_main_program()
    exe.run(start_program)
    if cfg['pretrained'] is not None:
        fluid.io.load_persistables(exe, cfg['pretrained'], start_program)
        # fluid.io.load_persistables(exe, cfg['pretrained'])
    for epoch in range(0,num_epochs):
下面是我恢复训练后的total_loss:
2020-02-28 10:06:46,114 - train.py[line:150] - INFO: epoch 0, step 0, total_loss: 0.19910
loss_cls: 0.11695, loss_bbox: 0.08215, fg_num: 92, lr: 0.00133
2020-02-28 10:06:51,442 - train.py[line:150] - INFO: epoch 0, step 5, total_loss: 0.13470
loss_cls: 0.08358, loss_bbox: 0.05113, fg_num: 101, lr: 0.00133
2020-02-28 10:06:56,578 - train.py[line:150] - INFO: epoch 0, step 10, total_loss: 0.12935
loss_cls: 0.07687, loss_bbox: 0.05247, fg_num: 106, lr: 0.00133
2020-02-28 10:07:01,745 - train.py[line:150] - INFO: epoch 0, step 15, total_loss: 0.14660
loss_cls: 0.09456, loss_bbox: 0.05204, fg_num: 104, lr: 0.00133
2020-02-28 10:07:07,140 - train.py[line:150] - INFO: epoch 0, step 20, total_loss: 0.13445
loss_cls: 0.08643, loss_bbox: 0.04802, fg_num: 103, lr: 0.00133
损失函数上升将近5倍。。。。。。
我的保存模型的代码是：
 fluid.io.save_persistables(dirname=cfg['save_path'],
                                  main_program=main_program, executor=exe)

**Comment by zhangting2020** [comment]
请试试用[save](https://www.paddlepaddle.org.cn/documentation/docs/zh/api_cn/io_cn/save_cn.html#save)接口保存模型，用[load](https://www.paddlepaddle.org.cn/documentation/docs/zh/api_cn/fluid_cn/load_cn.html#load)加载模型

**Comment by ahsdx** [comment]
我刚刚尝试了下，保存模型后，出现了###.pdparams、###.pdopt、###.pdmodel三个文件，但我加载模型用的是fluid.load(fluid.default_main_program(),  '###', exe)，此时恢复训练时，出现如下报错信息：
Traceback (most recent call last):
  File "recover_train.py", line 170, in <module>
    train()
  File "recover_train.py", line 111, in train
    fluid.load(fluid.default_main_program, '/home/aistudio/work/tools/efficientdet-d4-2', exe)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/io.py", line 1593, in load
    parameter_list = list(filter(is_parameter, program.list_vars()))
AttributeError: 'function' object has no attribute 'list_vars'

请问这个怎么解决啊？

**Comment by ahsdx** [comment]
我刚刚尝试了下，保存模型后，出现了###.pdparams、###.pdopt、###.pdmodel三个文件，但我加载模型用的是fluid.load(fluid.default_main_program(), '###', exe)，此时恢复训练时，出现如下报错信息：Traceback (most recent call last):File "recover_train.py", line 170, intrain()File "recover_train.py", line 111, in trainfluid.load(fluid.default_main_program, '/home/aistudio/work/tools/efficientdet-d4-2', exe)File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/io.py", line 1593, in loadparameter_list = list(filter(is_parameter, program.list_vars()))AttributeError: 'function' object has no attribute 'list_vars'请问这个怎么解决啊？



---原始邮件---
发件人: "Zhang Ting"<notifications@github.com&gt;
发送时间: 2020年2月28日(周五) 中午1:38
收件人: "PaddlePaddle/Paddle"<Paddle@noreply.github.com&gt;;
抄送: "Author"<author@noreply.github.com&gt;;"ahsdx"<2589561091@qq.com&gt;;
主题: Re: [PaddlePaddle/Paddle] 恢复训练时，损失函数会上升，上升不止一点，有时候是将近5倍 (#22791)



请试试用save接口保存模型，用load加载模型

**Comment by zhangting2020** [comment]
请检查下你的保存语句，看你上面粘贴的是以下语句
```
fluid.load(fluid.default_main_program, '/home/aistudio/work/tools/efficientdet-d4-2', exe)
```
第一个参数是你的main_program，看你issue描述里，是有定义了一个main_program的，如果确认请传入那个main_program。fluid.default_main_program这个是默认的，即使要使用也应该是下面这样，注意default_main_program后的括号。
```
fluid.load(fluid.default_main_program(), '/home/aistudio/work/tools/efficientdet-d4-2', exe)
```

**Comment by ahsdx** [comment]
谢谢，我就在刚刚已经发现，改回来了。谢谢你了，我还有个问题
，就是这个我用save来保存模型时，需要保存main_program（main_program = fluid.default_main_program）吗？还有恢复训练时，用load接口加载的模型时，需要传进去的Program参数是用fluid.default_startup_program()，还是用fluid.default_main_program()，还是用我保存模型时上面提到的main_program？能不能帮我解答下
------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Zhang Ting"<notifications@github.com&gt;;
发送时间:&nbsp;2020年2月28日(星期五) 下午4:07
收件人:&nbsp;"PaddlePaddle/Paddle"<Paddle@noreply.github.com&gt;;
抄送:&nbsp;"星风…飘渺时空"<2589561091@qq.com&gt;;"State change"<state_change@noreply.github.com&gt;;
主题:&nbsp;Re: [PaddlePaddle/Paddle] 恢复训练时，损失函数会上升，上升不止一点，有时候是将近5倍 (#22791)




请检查下你的保存语句，看你上面粘贴的是以下语句
 fluid.load(fluid.default_main_program, '/home/aistudio/work/tools/efficientdet-d4-2', exe)  
第一个参数是你的main_program，看你issue描述里，是有定义了一个main_program的，如果确认请传入那个main_program。fluid.default_main_program这个是默认的，即使要使用也应该是下面这样，注意default_main_program后的括号。
 fluid.load(fluid.default_main_program(), '/home/aistudio/work/tools/efficientdet-d4-2', exe)

**Comment by zhangting2020** [comment]
- 使用save接口时，main_program是需要传入的。
- save和load这两个接口是搭配使用的，具体地可以参考load的API说明，可以看到示例代码中的用法.如果你的main_program就是fluid.default_main_program()，也就是说你没有重新定义一个main_program，那么就会使用默认的，save和load就都是传入fluid.default_main_program()。
```python
fluid.save(fluid.default_main_program(), "./test_path")
fluid.load(fluid.default_main_program(), "./test_path", exe)
```

**Comment by ahsdx** [comment]
好的，谢谢你。如何自己定义main_program？能给个参考吗



---原始邮件---
发件人: "Zhang Ting"<notifications@github.com&gt;
发送时间: 2020年3月2日(周一) 上午10:47
收件人: "PaddlePaddle/Paddle"<Paddle@noreply.github.com&gt;;
抄送: "State change"<state_change@noreply.github.com&gt;;"ahsdx"<2589561091@qq.com&gt;;
主题: Re: [PaddlePaddle/Paddle] 恢复训练时，损失函数会上升，上升不止一点，有时候是将近5倍 (#22791)


 
使用save接口时，main_program是需要传入的。 

save和load这两个接口是搭配使用的，具体地可以参考load的API说明，可以看到示例代码中的用法.如果你的main_program就是fluid.default_main_program()，也就是说你没有重新定义一个main_program，那么就会使用默认的，save和load就都是传入fluid.default_main_program()。 
 fluid.save(fluid.default_main_program(), "./test_path") fluid.load(fluid.default_main_program(), "./test_path", exe)

**Comment by zhangting2020** [comment]
可以参考两个文档看看哈。
- [default_main_program](https://www.paddlepaddle.org.cn/documentation/docs/zh/api_cn/fluid_cn/default_main_program_cn.html#default-main-program)
- [program_guard](https://www.paddlepaddle.org.cn/documentation/docs/zh/api_cn/fluid_cn/program_guard_cn.html#program-guard)
```python
import paddle.fluid as fluid
main_program = fluid.Program()
startup_program = fluid.Program()
with fluid.program_guard(main_program, startup_program):
    data = fluid.layers.data(name='image', shape=[784, 784], dtype='float32')
    hidden = fluid.layers.fc(input=data, size=10, act='relu')
```

**Comment by ahsdx** [comment]
好的，谢谢(*°∀°)=3



---原始邮件---
发件人: "Zhang Ting"<notifications@github.com&gt;
发送时间: 2020年3月2日(周一) 中午11:11
收件人: "PaddlePaddle/Paddle"<Paddle@noreply.github.com&gt;;
抄送: "State change"<state_change@noreply.github.com&gt;;"ahsdx"<2589561091@qq.com&gt;;
主题: Re: [PaddlePaddle/Paddle] 恢复训练时，损失函数会上升，上升不止一点，有时候是将近5倍 (#22791)



可以参考两个文档看看哈。
  
default_main_program 

program_guard

**Comment by zhangting2020** [comment]
请问描述中所提到的问题是否已经解决了呢？如果已解决，还请关闭issue

**Comment by ahsdx** [comment]
好的，已经关闭了，谢谢你



---原始邮件---
发件人: "Zhang Ting"<notifications@github.com&gt;
发送时间: 2020年3月2日(周一) 中午1:09
收件人: "PaddlePaddle/Paddle"<Paddle@noreply.github.com&gt;;
抄送: "State change"<state_change@noreply.github.com&gt;;"ahsdx"<2589561091@qq.com&gt;;
主题: Re: [PaddlePaddle/Paddle] 恢复训练时，损失函数会上升，上升不止一点，有时候是将近5倍 (#22791)



请问描述中所提到的问题是否已经解决了呢？如果已解决，还请关闭issue
