### ISSUE TITLE
训练部分结果后，paddle.fluid.core.EnforceNotMet: Invoke operator concat error.

### ISSUE THREAD

**Issue by menghou** [PaddlePaddle/Paddle#22792]
前面训练产出了一部分auc数据，后面报了这个错误
![image](https://user-images.githubusercontent.com/9972335/75509455-9ac1c700-5a22-11ea-994a-af43d035795d.png)

**Comment by zhangting2020** [comment]
看报错是：concat这个Op的输出Tensor中包含NAN值，可否先检查下concat这个层输入有无问题？

**Comment by menghou** [comment]
应该没有问题呢，之前跑过，完整跑完，最后预测后有一个brpc的报错，这次是跑了一部分batch后才出现的问题

**Comment by menghou** [comment]
> 看报错是：concat这个Op的输出Tensor中包含NAN值，可否先检查下concat这个层输入有无问题？

应该没有问题呢，之前跑过，完整跑完，最后预测后有一个brpc的报错，这次是跑了一部分batch后才出现的问题

**Comment by zhangting2020** [comment]
@menghou 的补充描述：之前训练的时候没出问题，只是改了下loss函数以及batch size啥的，结果训练了部分batch后才出现那个问题。

建议先确认下是loss函数还是batch size改了引起的错误

**Comment by menghou** [comment]
改用adam优化，已解决
