### ISSUE TITLE
Ubuntu18.04 python3.5安装paddlepaddle失败

### ISSUE THREAD

**Issue by xd905** [PaddlePaddle/Paddle#22798]
- 版本、环境信息：
    1）PaddlePaddle版本：请提供您的PaddlePaddle版本号（如1.1）或CommitID
    2）CPU：请提供CPU型号，MKL/OpenBlas/MKLDNN/等数学库的使用情况
    3）系统环境：ubuntu18.04  python3.5
- 安装方式信息：
1）pip安装
  特殊环境请注明：阿里云服务器默认阿里源 
- 复现信息：
python3 -m pip install paddlepaddle -i https://mirror.baidu.com/pypi/simple
ERROR: Could not find a version that satisfies the requirement paddlepaddle (from versions: none)
ERROR: No matching distribution found for paddlepaddle
python3 -m pip install paddlepaddle -i https://pypi.tuna.tsinghua.edu.cn/simple
ERROR: Could not find a version that satisfies the requirement paddlepaddle (from versions: none)
ERROR: No matching distribution found for paddlepaddle
python3 -m pip install paddlepaddle
Installing collected packages: paddlepaddle
Successfully installed paddlepaddle-1.7.0
python3 进入python解释器，输入import paddle.fluid as fluid
  File "/usr/local/lib/python3.5/sqlite3/dbapi2.py", line 27, in <module>
    from _sqlite3 import *
ImportError: No module named '_sqlite3'
- 问题描述：请详细描述您的问题，同步贴出报错信息、日志/代码关键片段
已经卸载过之前安装的paddlepaddle包了，ubuntu自带python2.7的我用的python3.5，因为阿里云服务器默认阿里源根据官方文档下载失败后所以就去掉了源直接下载，显示下载成功但是import paddle.fluid as fluid时出错
Thank you for contributing to PaddlePaddle.
Before submitting the issue, you could search issue in Github in case that there was a similar issue submitted or resolved before.
If there is no solution,please make sure that this is an installation issue including the following details:
**System information**
-PaddlePaddle version （eg.1.1）or CommitID
-CPU: including CPUMKL/OpenBlas/MKLDNN version
-GPU: including CUDA/CUDNN version
-OS Platform (eg. Mac OS 10.14)
-Python version
- Install method: pip install/install with docker/build from source(without docker)/build within docker
- Other special cases that you think may be related to this problem, eg. offline install, special internet condition   
**To Reproduce**
Steps to reproduce the behavior
**Describe your current behavior**
**Code to reproduce the issue**
**Other info / logs**

**Comment by JepsonWong** [comment]
想问一下您的python3是自己编译的么？

**Comment by xd905** [comment]
> 想问一下您的python3是自己编译的么？

对的，原来自带有python2和python3.6，然后我自己加了个pyhton3.5的

**Comment by JepsonWong** [comment]
> > 想问一下您的python3是自己编译的么？
> 
> 对的，原来自带有python2和python3.6，然后我自己加了个pyhton3.5的

您好，这个问题是编译python3.5之前需要提前安装好相关依赖：
apt-get install -y zlib1g-dev openssl libssl-dev libsqlite3-dev
