### ISSUE TITLE
Permission deniedmake Error1

### ISSUE THREAD

**Issue by morganw** [PaddlePaddle/Paddle#2280]
when I install paddle on centos7, I use sudo make -j `nproc` && make install ,there is an error:

Generating ../../paddle/python/paddle/proto/ParameterServerConfig_pb2.py
/my work path/paddle/python/paddle/proto/ParameterServerConfig_pb2.py: Permission deniedmake[2]: *** [../paddle/python/paddle/proto/ParameterServerConfig_pb2.py] Error 1

I must use root  to install.

**Comment by typhoonzero** [comment]
Try run `make -j nproc && sudo make install` instead. `make install` requires root permissions so add `sudo` before it.
