### ISSUE TITLE
fluid.layers.split 的使用方法 && 训练过程中传入list数组

### ISSUE THREAD

**Issue by aprilvkuo** [PaddlePaddle/Paddle#22816]
# 问题一： split使用方法
报错信息：
我想对第一维进行split操作， 将输入向量拆分成几个list。 但是因为第一维是-1， split操作操作报错信息如下。

```shell
(-1, 128)
(-1, 1)
Traceback (most recent call last):
  File "main.py", line 102, in <module>
    out = model.forward(x, y, split_list)
  File "main.py", line 33, in forward
    sample_per_class_embs =  fluid.layers.split(x, num_or_sections=split_list, dim=0) # 每一个类别的向量
  File "/home/work/guohongjie/miniconda3/lib/python3.6/site-packages/paddle/fluid/layers/nn.py", line 5035, in split
    dim], 'len(num_or_sections) must not be more than input.shape[dim].'
AssertionError: len(num_or_sections) must not be more than input.shape[dim].
```

# 问题2： 我在训练过程中， 每个step想要传入一个list数组， 不知道paddle是否支持

1. 是否feed必须通过feed方式
2.  feed方式是否支持，数据流程是否为( list ->feed ->variable -> list)

**Comment by mapingshuo** [comment]
问题1： 第一维为-1表示这一维度是batch_size, 请问为什么要把不同batch的数据切分开呢？

**Comment by mapingshuo** [comment]
问题2.1：在Paddle中将list转为Tensor后，通过feed输入是一种常见的方式；但是不必须使用feed方式，还有[pyreader](https://paddlepaddle.org.cn/documentation/docs/zh/api_cn/io_cn/PyReader_cn.html#pyreader)等方式。

**Comment by mapingshuo** [comment]
问题2.2 feed方式支持list -> variable -> Run() -> numpy array的方式，你可以把numpy array最后转成自己的list

**Comment by aprilvkuo** [comment]
> 问题1： 第一维为-1表示这一维度是batch_size, 请问为什么要把不同batch的数据切分开呢？

这是model的实际需要， 而且batch_size还是会变化的。

**Comment by mapingshuo** [comment]
问题1：当split_list不固定时，静态图不支持对batch size维度做split，这样会导致输出Tensor的数目不固定，必须要动态图做。
