### ISSUE TITLE
【finetune】如何修改最后一层参数？

### ISSUE THREAD

**Issue by aiot-tech** [PaddlePaddle/Paddle#22812]
【finetune】如果不需要最后一层参数，paddlepaddle该怎么进行这种底层操作呢？有没有相关教程，感觉paddlepaddle的教程很少啊，好多都是高级封装好的了，很难进行定制化操作

**Comment by mapingshuo** [comment]
在paddle中可以使用fluid.io.save_inference_model()接口解决你的需求：
https://paddlepaddle.org.cn/documentation/docs/zh/api_cn/io_cn/save_inference_model_cn.html#save-inference-model
`target_vars`设置成你要裁剪的参数的输入就可以啦

**Comment by aiot-tech** [comment]
你好，我的想法是在加载模型的时候，能不能不将最后一层的参数加载进来，而是随机化的～因为目前有了nextvlad算法的参数了，但是该模型的最后一层输出不是很符合我的需求～

**Comment by aiot-tech** [comment]
有没有接口可以直接修改某一层的参数值，或直接将一个随机初始化的矩阵赋给某一个层的呢

**Comment by mapingshuo** [comment]
您想修改训练好的模型的某一个参数，当然是可以的。我一般是这样做的, load模型之后：
```shell
            embedding_name = "emb1"
            embedding_param = fluid.global_scope().find_var(
                embedding_name)
            if embedding_param:
                embedding_param = embedding_param.get_tensor()
                embedding_param.set(your_numpy_array, place)
```
修改后可以再save_inference_model, 这样模型的参数就被修改了。

**Comment by aiot-tech** [comment]
你的耐心解答让我对paddlepaddle的架构更加的了解，谢谢啦。那假如我想使用paddlepaddle的预训练参数做迁移学习，我就打算修改了最后一层的参数(将输出从3862维改为51维)，我目前的做法是将原先的参数加载进来，到了最后一层，维度不匹配了，paddlepaddle的底层是怎么运作的呢？会不会将先前维度匹配的网络层的参数加载进来呢

    if args.resume:
        # if resume weights is given, load resume weights directly
        assert os.path.exists(args.resume), \
                "Given resume weight dir {} not exist.".format(args.resume)
        fluid.io.load_params(
           exe, '', main_program=train_prog, filename=args.resume)
        # param_load.load_params(
        #     exe, '', main_program=train_prog, filename=args.resume)
        embedding_name ="logits_clf_weights"
        embedding_param_weight = fluid.global_scope().find_var(
            embedding_name)
        if embedding_param_weight:
            embedding_param = embedding_param_weight.get_tensor()
            embedding_param.set(np.random.rand(2048,51).astype(np.float32), place)
        embedding_name="logits_clf_bias"
        embedding_param_bias = fluid.global_scope().find_var(
            embedding_name)
        if embedding_param_bias:
            embedding_param=embedding_param_bias.get_tensor()
            embedding_param.set(np.random.rand(51).astype(np.float32), place)

**Comment by mapingshuo** [comment]
既然是迁移学习，你就要按照迁移后的网络（51维）组网；之后通过load_persistable()来load预训练网络的参数（除了最后一个参数以外的前面所有参数）。

https://paddlepaddle.org.cn/documentation/docs/zh/api_cn/io_cn/load_persistables_cn.html#load-persistables

**Comment by mapingshuo** [comment]
迁移学习在Paddle中最经典的案例之一就是Bert，不妨看一下Paddle中的Bert是怎么做的吧：https://github.com/PaddlePaddle/models/blob/develop/PaddleNLP/PaddleLARK/BERT/utils/init.py#L62

**Comment by aiot-tech** [comment]
太棒了,thx a lot ~

**Comment by yuxulingche** [comment]
@aiot-tech 你好，请问你的问题解决了吗，是怎么解决的呢，我现在也在finetune NextVlad，想把最后一层由3862维改为我自己数据集的类别数
