### ISSUE TITLE
Code coverage for MKL-DNN related files in Release build

### ISSUE THREAD

**Issue by wojtuss** [PaddlePaddle/Paddle#22819]
With the recent code coverage results from the Paddle Coverage Nightly builds the following two files are failing to reach 90% of line code coverage:
1. `paddle_mkldnn_quantizer_config.h`: 83.3%
2. `lrn_mkldnn_op.cc`: 88.7%

The reason for 1. is that PaddlePaddle is being built in Release mode, and optimizations applied by the compiler prevented `lcov` from a precise code coverage measurement. Running the code coverage test on the Debug build shows 100.0% line code coverage for this file. Following the document https://gcc.gnu.org/onlinedocs/gcc/Gcov-and-Optimization.html, _if you want to prove that every single line in your program was executed, you should not compile with optimization at the same time_.

We cannot improve the 2. case. The not covered part of the code is DNNL `lrn` kernel implementation-specific and the behavior can change depending on the hardware we are running PaddlePaddle on and is out of our control.

**Comment by luotao1** [comment]
Got it. Thanks very much for your analysis! You can finish the Code coverage update now.

**Comment by chalsliu** [comment]
Thanks very much! 
The task has been modified to run the code coverage test on the Debug build. We will check for changes.

**Comment by chalsliu** [comment]
Because of the "WITH_COVERAGE = ON" option, it may already be in debug mode.
We will further confirm.

**Comment by chalsliu** [comment]
After setting to debug mode, some cases are stuck, and the result cannot be obtained. We will continue to try to solve the problem. This issue can currently be closed.
Thanks very much!
