### ISSUE TITLE
关于PaddleDetection中anchor匹配部分的疑惑

### ISSUE THREAD

**Issue by zhengzhe97** [PaddlePaddle/Paddle#22833]
![PSVXN77Z7FP`K7 K}`5(K~S](https://user-images.githubusercontent.com/26462054/75747905-21471300-5d59-11ea-95f3-b54f35ce3f48.png)

请问一下，这里anchor和gt_boxes做匹配有点不太理解。不应该是anchor匹配每一张图的gt_boxes，这里gt_boxes的第一维是G（表示批量内真值框的总数）是怎么做匹配的？

**Comment by ForFishes** [comment]
gt_boxes是一个LODtensor 通过LoD level可以得知切取出每张图上真值。

**Comment by qingqing01** [comment]
closed due to https://github.com/PaddlePaddle/PaddleDetection/issues/299
