### ISSUE TITLE
paddle 1.7库编译出错

### ISSUE THREAD

**Issue by XipengY** [PaddlePaddle/Paddle#22870]
paddle 1.7编译出错

- 版本、环境信息：
    1）PaddlePaddle版本：release/1.7
    2）CPU/GPU：GPUk40 CUDA-9 cuDNN-7.6
    3）系统环境：docker centos6.3
    4）Python版本号 python3.7
    5）显存信息

环境变量：
export LD_LIBRARY_PATH=/opt/_internal/cpython-3.7.0/lib/:${LD_LIBRARY_PATH}
export PATH=/opt/_internal/cpython-3.7.0/bin/:${PATH}
export PYTHON_FLAGS="-DPYTHON_EXECUTABLE:FILEPATH=/opt/_internal/cpython-3.7.0/bin/python3.7 -DPYTHON_INCLUDE_DIR:PATH=/opt/_internal/cpython-3.7.0/include/python3.7m -DPYTHON_LIBRARIES:FILEPATH=/opt/_internal/cpython-3.7.0/lib/libpython3.7m.so"
export PYTHON_ABI="cp37-cp37m"
export PY_VERSION=3.7
export WITH_GPU=ON

export CUDNN_ROOT=/paddle/apps/cudnn76/cuda/
export CUDNN_INCLUDE_DIR=/paddle/apps/cudnn76/cuda/include
export CUDNN_LIBRARY=/paddle/apps/cudnn76/cuda/lib64

export C_INCLUDE_PATH=/paddle/apps/nccl_2.4.7_cuda9.0/include:$C_INCLUDE_PATH
export CPLUS_INCLUDE_PATH=/paddle/apps/nccl_2.4.7_cuda9.0/include:$CPLUS_INCLUDE_PATH
export LIBRARY_PATH=/paddle/apps/cudnn76/cuda/lib64:$LIBRARY_PATH
export LD_LIBRARY_PATH=/paddle/apps/nccl_2.4.7_cuda9.0/lib64:/paddle/cudnn76/cuda/lib64:/usr/local/cuda/lib64:$LD_LIBRARY_PATH
export PYTHONPATH=$PYTHONPATH:.

编译选项：
cmake .. -DPYTHON_EXECUTABLE:FILEPATH=/opt/_internal/cpython-3.7.0/bin/python3.7 \
         -DPYTHON_INCLUDE_DIR:PATH=/opt/_internal/cpython-3.7.0/include/python3.7m \
         -DPYTHON_LIBRARIES:FILEPATH=/opt/_internal/cpython-3.7.0/lib/libpython3.7m.so \
         -DWITH_GPU=ON \
         -DWITH_TESTING=OFF \
         -DCMAKE_BUILD_TYPE=Release \
         -DWITH_DISTRIBUTE=ON \
         -DCUDA_ARCH_NAME=Auto \
         -DCMAKE_INSTALL_PREFIX=./output/ \
         -DCUDNN_ROOT=/paddle/apps/cudnn76/cuda \
         -DWITH_FLUID_ONLY=ON \

错误信息：
![image](https://user-images.githubusercontent.com/17317650/75962072-0feb3b80-5efe-11ea-9191-c7f8b2198aa3.png)

**Comment by JepsonWong** [comment]
CUDA_HOME、LIBRARY_PATH、LD_LIBRARY_PATH环境变量输出来看下，看起来像是cuda的一些库没找到。

**Comment by XipengY** [comment]
echo $CUDA_HOME  (CUDA_HOME:是空的)

echo $LIBRARY_PATH
/paddle/apps/cudnn76/cuda/lib64:/paddle/apps/cudnn76/cuda/lib64:/usr/local/cuda/lib64/stubs

echo $LD_LIBRARY_PATH
/paddle/apps/nccl_2.4.7_cuda9.0/lib64:/paddle/cudnn76/cuda/lib64:/usr/local/cuda/lib64:/opt/_internal/cpython-3.7.0/lib/:/paddle/apps/nccl_2.4.7_cuda9.0/lib64:/paddle/cudnn76/cuda/lib64:/opt/_internal/cpython-3.7.0/lib/:/opt/rh/devtoolset-2/root/usr/lib64:/opt/rh/devtoolset-2/root/usr/lib:/usr/local/lib64:/usr/local/lib:/usr/local/nvidia/lib:/usr/local/nvidia/lib64

**Comment by XipengY** [comment]
> CUDA_HOME、LIBRARY_PATH、LD_LIBRARY_PATH环境变量输出来看下，看起来像是cuda的一些库没找到。

echo $CUDA_HOME (CUDA_HOME:是空的)

echo $LIBRARY_PATH
/paddle/apps/cudnn76/cuda/lib64:/paddle/apps/cudnn76/cuda/lib64:/usr/local/cuda/lib64/stubs

echo $LD_LIBRARY_PATH
/paddle/apps/nccl_2.4.7_cuda9.0/lib64:/paddle/cudnn76/cuda/lib64:/usr/local/cuda/lib64:/opt/_internal/cpython-3.7.0/lib/:/paddle/apps/nccl_2.4.7_cuda9.0/lib64:/paddle/cudnn76/cuda/lib64:/opt/_internal/cpython-3.7.0/lib/:/opt/rh/devtoolset-2/root/usr/lib64:/opt/rh/devtoolset-2/root/usr/lib:/usr/local/lib64:/usr/local/lib:/usr/local/nvidia/lib:/usr/local/nvidia/lib64

**Comment by XipengY** [comment]
另外，我刚尝试q相同的环境下切换到release/1.6分支，能正常编译。

**Comment by tianshuo78520a** [comment]
可以尝试使用cudnn7.3编译
