### ISSUE TITLE
Error: Paddle internal Check failed. (Please help us create a new issue, here we need to find the developer to add a user friendly error message)

### ISSUE THREAD

**Issue by Colorfu1** [PaddlePaddle/Paddle#22889]
运行程序的时候出错，完整的报错信息如下所示：
![error](https://user-images.githubusercontent.com/30551427/76043330-28a53100-5f92-11ea-9b7d-98046df92681.PNG)
看定位的位置应该是
File "/home/map/wuwenda/Attention_flow_net_Paddle/core/spatial_transformer_net.py", line 206, in bilinear_sampler
    wb = (x1-x) * (y-y0)
此处的代码应该是做一个双线性插值的代码，不需要使用梯度，没有可训练的Variable。代码段如下：
![error1](https://user-images.githubusercontent.com/30551427/76043465-99e4e400-5f92-11ea-9949-3846f0c92ca9.PNG)
请问是什么原因造成的呢？

**Comment by baiyfbupt** [comment]
hi， 这个问题的报错信息不是很清楚，看代码也没什么问题。所以麻烦复制粘贴一下出问题的这段代码，我帮您调试一下看看？

**Comment by baiyfbupt** [comment]
@chenwhql 同时辛苦一下weihang关注一下这个报错信息问题~

**Comment by chenwhql** [comment]
> @chenwhql 同时辛苦一下weihang关注一下这个报错信息问题~

好的，收到
