### ISSUE TITLE
Ftrl Optimizer 文档描述问题

### ISSUE THREAD

**Issue by JiabinYang** [PaddlePaddle/Paddle#22883]
官网文档中涉及Ftrl Optimizer的描述中并未见到可以配置momentum的选项，那如果这里momentum为None是什么原因导致呢
![image](https://user-images.githubusercontent.com/22361972/75985256-f5798800-5f26-11ea-904a-7627147c661b.png)

**Comment by yaoxuefeng6** [comment]
好像看不到图片

**Comment by JiabinYang** [comment]
![image](https://user-images.githubusercontent.com/22361972/76831024-79a20880-6861-11ea-8d20-8c2037918978.png)
