### ISSUE TITLE
编译python预测库

### ISSUE THREAD

**Issue by zhengrenfeng** [PaddlePaddle/Paddle#22893]
按文档编译后在build目录下得到python目录，在python目录下进行make生成的是python2的paddle,但是我需要的是python3的 要怎么处理？ 直接用python3 setup.py build得到的结果不完整，使用时会报错 so缺少内容

**Comment by baiyfbupt** [comment]
您可以在cmake时通过`-DPY_VERSION`指定想要编译的Python版本，请参考：
![image](https://user-images.githubusercontent.com/28884066/76065520-c9addf00-5fc6-11ea-833b-9ec3229c2210.png)
https://paddlepaddle.org.cn/documentation/docs/zh/install/compile/compile_Ubuntu.html
