### ISSUE TITLE
使用预测代码提示重新编译并设置ON_INFER为ON

### ISSUE THREAD

**Issue by zhengrenfeng** [PaddlePaddle/Paddle#22890]
pip安装paddle1.7，使用预测from paddle.fluid.core import create_paddle_predictor创建的predictor进行预测，出现错误提示：重新编译并设置ON_INFER为ON。
按linux编译预测库的文档操作，cmake -DFLUID_INFERENCE_INSTALL_DIR=/xxx -DCMAKE_BUILD_TYPE=Release -DWITH_PYTHON=ON -DWITH_MKL=OFF -DWITH_GPU=OFF  -DON_INFER=ON -WITH_MKLDNN=OFF -WITH_XBYAK=ON -WITH_NV_JETSON=OFF 。make到最后报错
![image](https://user-images.githubusercontent.com/9197074/76044588-c51d0280-5f95-11ea-8c7e-367ca4fc91ff.png)。
虽然出错，但是还是生成python文件夹，继续使用python setup.py 进行安装，在引入from paddle.fluid.core import PaddleTensor时报错core_avx.so: undefined symbol: _Py_ZeroStruct

**Comment by MyPandaShaoxiang** [comment]
你好，能提供一下编译时的全部log么

**Comment by zhengrenfeng** [comment]
按文档执行步骤：
git clone https://github.com/paddlepaddle/paddle
cd paddle
git checkout v1.7.0
mkdir build
cd build
cmake -DFLUID_INFERENCE_INSTALL_DIR=/xxx -DCMAKE_BUILD_TYPE=Release -DWITH_PYTHON=ON -DWITH_MKL=OFF -DWITH_GPU=OFF  -DON_INFER=ON -WITH_MKLDNN=OFF -WITH_XBYAK=ON -WITH_NV_JETSON=OFF -DWITH_TESTING=OFF
	报错：CMake Error: The source directory "/xxx/paddle/build" does not appear to contain CMakeLists.txt.
		  Specify --help for usage, or press the help button on the CMake GUI.
cd ..
cmake -DFLUID_INFERENCE_INSTALL_DIR=/xxx -DCMAKE_BUILD_TYPE=Release -DWITH_PYTHON=ON -DWITH_MKL=OFF -DWITH_GPU=OFF  -DON_INFER=ON -WITH_MKLDNN=OFF -WITH_XBYAK=ON -WITH_NV_JETSON=OFF -DWITH_TESTING=OFF
make -j16
make inference_lib_dist

编译日志：
[log.txt](https://github.com/PaddlePaddle/Paddle/files/4296259/log.txt)

**Comment by zhengrenfeng** [comment]
应该是目录冲突问题，cmake缺少 .. 导致
