### ISSUE TITLE
A question about config_parser_utils and config_parser

### ISSUE THREAD

**Issue by wangkuiyi** [PaddlePaddle/Paddle#2290]
In directory [python/paddle/trainer_config_helpers](https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/trainer_config_helpers), we have two modules:

1. [config_parser.py](https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/trainer_config_helpers/config_parser.py), and
1. [config_parser_util.py](https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/trainer_config_helpers/config_parser_utils.py)

Both define the following three functions:

1. `def parse_trainer_config(trainer_conf, config_arg_str)`
1. `def parse_network_config(network_conf, config_arg_str='')`
1. `def parse_optimizer_config(optimizer_conf, config_arg_str=''):`

with no more than slight difference.

Does anyone know why we need these seems duplicated function definitions?

**Comment by jacquesqiao** [comment]
yes，these two files are duplicated, I will delete the unused one.

**Comment by wangkuiyi** [comment]
Thanks! @jacquesqiao Looking forward to your PR!

**Comment by jacquesqiao** [comment]
@wangkuiyi https://github.com/PaddlePaddle/Paddle/pull/2293
