### ISSUE TITLE
ctc_greedy_decoder 方法需要支持非 Lod Tensor 参数解码

### ISSUE THREAD

**Issue by xiangyubo** [PaddlePaddle/Paddle#22905]
ctc_greedy_decoder 方法需要支持非 Lod Tensor 参数解码。
原因是现在 paddle 已经发展到1.7，进入动态图时代。动态图本身也弱化了 Lod Tensor 的概念，和组基本的 Tensor 相近。但这个函数接受的参数必须是 Lod Tensor，给使用动态图实现 CRNN 的文字识别解码带来了麻烦。与之配套使用的 ctc_loss 都接受两种类型入参了，这个是不是也应该要有呢？
=================================分割============
我看代码里的文档是支持两种方式，但是官方网页上的文档只写了一种。。。

**Comment by iclementine** [comment]
那应该是文档需要更新了。我提醒一下负责 ctc_greedy_decoder 的同学更新一下文档。
