### ISSUE TITLE
如何调用networks.sequence_conv_pool建立多个卷积池化层

### ISSUE THREAD

**Issue by narrowview** [PaddlePaddle/Paddle#22908]
问题如上，具体可参考https://github.com/PaddlePaddle/Paddle/issues/8323
该问题答案附的链接已失效

**Comment by slf12** [comment]
> 问题如上，具体可参考#8323
> 该问题答案附的链接已失效

请问用的什么paddle版本？https://www.paddlepaddle.org.cn/documentation/docs/zh/api_cn/nets_cn/sequence_conv_pool_cn.html#sequence-conv-pool  #8323 中的链接是老版本了

**Comment by narrowview** [comment]
> > 问题如上，具体可参考#8323
> > 该问题答案附的链接已失效
> 
> 请问用的什么paddle版本？https://www.paddlepaddle.org.cn/documentation/docs/zh/api_cn/nets_cn/sequence_conv_pool_cn.html#sequence-conv-pool #8323 中的链接是老版本了

用的是1.6.1。如果方便的话，可以提供下1.5.2和1.6.1两个版本的使用方法吗？

**Comment by xyzhou-puck** [comment]
Hi，你可以单独使用https://www.paddlepaddle.org.cn/documentation/docs/zh/api_cn/layers_cn/sequence_conv_cn.html#sequence-conv
。
