### ISSUE TITLE
'Conv2D' object has no attribute '_filter_param'

### ISSUE THREAD

**Issue by skywalk163** [PaddlePaddle/Paddle#22910]
1）PaddlePaddle版本：1.7.0
    2) 系统环境：AiStudio 高端版：GPU v100
问题：
学习与运行 飞桨网站-1.7 快速上手-动态图机制 - 使用DyGraph训练模型 第六步，变量及优化器 运行报错：
---> 53     print("_simple_img_conv_pool_1_conv2d W's mean is: {}".format(mnist._simple_img_conv_pool_1._conv2d._filter_param.numpy().mean()))
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py in __getattr__(self, name)
    368             return self._sub_layers[name]
    369         else:
--> 370             return object.__getattribute__(self, name)
    371 
    372     def __setattr__(self, name, value):
AttributeError: 'Conv2D' object has no attribute '_filter_param'

代码链接：
https://www.paddlepaddle.org.cn/documentation/docs/zh/beginners_guide/basic_concept/dygraph/DyGraph.html#id4

相关代码：
with fluid.dygraph.guard():
    epoch_num = 5
    BATCH_SIZE = 64

    mnist = MNIST()
    adam = fluid.optimizer.AdamOptimizer(learning_rate=0.001, parameter_list=mnist.parameters())
    train_reader = paddle.batch(
        paddle.dataset.mnist.train(), batch_size= BATCH_SIZE, drop_last=True)

    np.set_printoptions(precision=3, suppress=True)
    for epoch in range(epoch_num):
        for batch_id, data in enumerate(train_reader()):
            dy_x_data = np.array(
                [x[0].reshape(1, 28, 28)
                 for x in data]).astype('float32')
            y_data = np.array(
                [x[1] for x in data]).astype('int64').reshape(BATCH_SIZE, 1)

            img = fluid.dygraph.to_variable(dy_x_data)
            label = fluid.dygraph.to_variable(y_data)
            label.stop_gradient = True

            cost = mnist(img)
            loss = fluid.layers.cross_entropy(cost, label)
            avg_loss = fluid.layers.mean(loss)

            dy_out = avg_loss.numpy()

            avg_loss.backward()
            adam.minimize(avg_loss)
            mnist.clear_gradients()

            dy_param_value = {}
            for param in mnist.parameters():
                dy_param_value[param.name] = param.numpy()

            if batch_id % 20 == 0:
                print("Loss at step {}: {}".format(batch_id, avg_loss.numpy()))
    print("Final loss: {}".format(avg_loss.numpy()))
    print("_simple_img_conv_pool_1_conv2d W's mean is: {}".format(mnist._simple_img_conv_pool_1._conv2d._filter_param.numpy().mean()))
    print("_simple_img_conv_pool_1_conv2d Bias's mean is: {}".format(mnist._simple_img_conv_pool_1._conv2d._bias_param.numpy().mean()))

报错的是最后两句。

**Comment by slf12** [comment]
请稍等，我找这个教程页面的负责人看下

**Comment by skywalk163** [comment]
1.6版本的代码，在1.6环境下是可以跑通的。
这个1.7版本在1.7环境下报错，是否1.7修改了某些地方。

ps，这个教程有github地址吗？ 那样更方便。

**Comment by phlrain** [comment]
1.6 版本本中 _filter_param 是一个不建议使用接口（遵循python的命名规则 _ 开头的参数名称）， 1.7 中为了方便大家使用，暴露了 conv2d.weight, conv2d.bias来获取 filter 和 bias参数

**Comment by skywalk163** [comment]
非常感谢及时有效的回复！

改用weight和bias两个接口就ok了！ 期间一度被整的很郁闷，不过困难多大，跑通的喜悦就有多大+1 

   print("_simple_img_conv_pool_1_conv2d W's mean is: {}".format(mnist._simple_img_conv_pool_1._conv2d.weight.numpy().mean()))
    print("_simple_img_conv_pool_1_conv2d Bias's mean is: {}".format(mnist._simple_img_conv_pool_1._conv2d.bias.numpy().mean()))
