### ISSUE TITLE
SimpleData defined in config_parser.py and config_parser_extension.py

### ISSUE THREAD

**Issue by wangkuiyi** [PaddlePaddle/Paddle#2291]
In directory [python/paddle/trainer](https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/trainer), global function `SimpleData` are defined in both

1. [config_parser.py](https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/trainer/config_parser.py), and 
1. [config_parser_extension.py](https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/trainer/config_parser_extension.py).

The two definitions are almost the same. 

Do we need both of them?

**Comment by jacquesqiao** [comment]
我在svn日志里面搜了下`python/paddle/trainer/config_parser_extension.py`这个文件的提交记录，发现这个文件是骆涛2016-08-19从`python/paddle/trainer/tests/config_parser_extension.py` 移过来的，不是很确定具体用途，这个时间点大概是paddle开源之前整理代码的阶段，可能需要 @luotao1 帮忙看下。

这个文件目前只在paddle/paddle/trainer/tests/config_parser_test.py被用到：
```python
if __name__ == '__main__':
    parse_config_and_serialize('trainer/tests/test_config.conf', '')
    parse_config_and_serialize(
        'trainer/tests/sample_trainer_config.conf',
        'extension_module_name=paddle.trainer.config_parser_extension')
    parse_config_and_serialize('gserver/tests/pyDataProvider/trainer.conf', '')
```

**Comment by luotao1** [comment]
`SimpleData`确实只是在单测中使用，当时留着的原因是，希望给想自定义数据的用户一个演示。当时定义的数据类似`TrainData`，`TestData`这种。

**Comment by wangkuiyi** [comment]
How about we remove duplicated code? @luotao1

**Comment by luotao1** [comment]
@wangkuiyi  仔细看了下，这两个code目前都不能简单地删掉：
1. config_parser.py 中的simpleData， 主要用于[test_TrainerOnePass](https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/trainer/tests/test_TrainerOnePass.cpp)中的两个单测配置[sample_trainer_config.conf](https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/trainer/tests/sample_trainer_config.conf)和[sample_trainer_config_parallel.conf.conf](https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/trainer/tests/sample_trainer_config_parallel.conf.conf)读数据的部分。因为这个单测是测试训练后的精度是否正常，如果删掉，需要把配置升级成v2 api，且改该单测的逻辑。
2. config_parser_extension.py中的SimpleData，用于[config_parser_test.py](https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/trainer/tests/config_parser_test.py)中测试config_parser.py的`extension_module`是否正常。 @lcy-seso config_parser.py重构的时候还需要extension_module这个功能么？如果不需要的话，整个config_parser_extension.py可以删掉。

**Comment by lcy-seso** [comment]
也看了一下代码，
1. `config_parser_extension.py` 这个文件没有真正的功能上的作用，目前仅仅为了在单测`paddle/trainer/tests/config_parser_extension.py` 中测试config_parser.py的`extension_module`功能是否正常。这个文件放移动到`paddle/trainer/tests`下更合适。
2.  `extension_model`功能是在config_parser.py中实现，config_parser_extension.py 这个单测最好不要删掉。
3. 如果是为了避免代码重复，可以把`config_parser_extension.py`中的`SimpleData`换成另外的用户定义函数。

**Comment by lcy-seso** [comment]
I close this issue due to inactivity. Please feel free to reopen it.
