### ISSUE TITLE
paddleslim1.0 使用demo进行post-quant量化错误

### ISSUE THREAD

**Issue by zzchust** [PaddlePaddle/Paddle#22927]
![image](https://user-images.githubusercontent.com/6135871/76275575-94eba180-62be-11ea-96b8-c77573a171ee.png)
![image](https://user-images.githubusercontent.com/6135871/76275590-9fa63680-62be-11ea-81ed-d7b972cad4dd.png)

具体环境：
python2.7， 
paddlepaddle-1.7.0，
paddleslim1.0

完全按照quant-post的[demo](https://github.com/PaddlePaddle/PaddleSlim/tree/release/1.0.1/demo/quant/quant_post)教程操作， MobileNet模型从[此处](http://paddle-imagenet-models-name.bj.bcebos.com/MobileNetV1_pretrained.tar)下载， 利用export_model.py导出inference model， 然后使用quant_post.py 量化模型。 错误如上图所示。

**Comment by slf12** [comment]
是bn在cudnn版本不一致时的兼容性问题，换成cudnn7.4的paddle已解决。
