### ISSUE TITLE
C++ full include paths

### ISSUE THREAD

**Issue by wangkuiyi** [PaddlePaddle/Paddle#2292]
Our include convention is that if a header file is in the same directory as the source file, we don't have to specify the full include path.

For example, if `a.h` , `b.h`, `z.h`, and `a.cc` are in the same directory `paddle/pserver`, we'd write the following in `a.cc`:

```cpp
#include "a.h"
#include "b.h"
#include "z.h"
#include "paddle/math/matrix.h"
#include "paddle/utils/stringprint.h"
```

However, most auto format tools (Emacs plugins, clang-format, etc) sort header paths enclosed in double-quotes (").   This is reasonable because it

1. allows us to find included header files efficiently in the alphabetical order, and
1. keep header files in the same directory (package) staying together.

However, the sorting would reformat our code as:

```cpp
#include "a.h"
#include "b.h"
#include "paddle/math/matrix.h"
#include "paddle/utils/stringprint.h"
#include "z.h"
```

where "a.h" and "z.h" are no longer staying together, even if they are in the same directory.

So, I propose here that we always write full include paths.  If so, we'd have

```cpp
#include "paddle/pserver/a.h"

#include "paddle/math/matrix.h"
#include "paddle/pserver/b.h"
#include "paddle/pserver/z.h"
#include "paddle/utils/stringprint.h"
```

**Comment by emailweixu** [comment]
How about #include "./a.h" ?

**Comment by typhoonzero** [comment]
I think we already using full include paths in the refactored code, mainly under `paddle/framework`, `paddle/platform` and `paddle/operators`.

I'll close this for now, feel free to open it.
