### ISSUE TITLE
im2sequence的输出形状

### ISSUE THREAD

**Issue by shaunhurryup** [PaddlePaddle/Paddle#22941]
来源:
from paddle.fluid.layer import im2sequence

x.shape = [-1, 1024, 3, 32]    # h=3  w=32
x = im2sequence(x, (x.shape[2], 1), (1, 1))    # filter_size=(3,1)  stride=(1,1)

当使用im2sequence求x的新shape时，通过paddle提供的公式shape={input.batch_size * output_height * output_width, filter_size_height* filter_size_width * input.channels}

input_batch_size = -1
output_height = 1 + (0+0+3-3+1-1) / 1 = 1
output_width = 1 + (0+0+32-1+1-1) / 1 = 32
shape[0] = -32

但是调试时发现x的shape应该是(-1, 3072)，我按照公式求解但是得到了不一样的答案，迫切希望能得到一个解答。

**Comment by huangjun12** [comment]
原因是你只构建了graph而没有实际run起来，batch_size为-1只是一个占位符，请参考如下代码:

import paddle
import paddle.fluid as fluid
import numpy as np

x_shape = [-1, 1024, 3, 32]
x = fluid.layers.data("x", shape = x_shape, dtype="float32")
y = fluid.layers.im2sequence(x, filter_size=(x_shape[2], 1), stride=(1, 1))

x_data = np.random.randn(1, 1024, 3, 32).astype("float32")

#run
exe = fluid.Executor(fluid.CPUPlace())
out, = exe.run(feed={"x":x_data}, fetch_list=[y.name], return_numpy=False)
print(out.shape())

输出log:
(32, 3072)

**Comment by shaunhurryup** [comment]
不好意思，可能我没表达清楚。
我根据公式推导得到的shape[0]的值为-32，但是实际运行得到的shape[0]的值为-1。

我不能理解程序运行时shape[0]的值为什么是-1。

**Comment by huangjun12** [comment]
paddle的静态图模式工作时分【编译】和【执行】两个阶段，原理参考:
https://www.paddlepaddle.org.cn/documentation/docs/zh/beginners_guide/basic_concept/executor.html
结合上面的示例代码:
(1) batch_size在构图阶段不能确定，默认为-1(**这个-1不是数学意义上的-1，你可以把它理解为None**):
x = fluid.layers.data("x", shape = [-1, 1024, 3, 32], dtype="float32") #注意这里的-1
y = fluid.layers.im2sequence(x, filter_size=(x_shape[2], 1), stride=(1, 1)) 
#由于batch_size还未确定，所以如果这一步之后打印y.shape[0]，其值为-1(或者说是None)
(2) 只有在执行阶段，喂入数据后，batch_size的值才能被确定:
#数据: 注意数据的第一维即batch_size设为1
x_data = np.random.randn(1, 1024, 3, 32).astype("float32")  
#喂入数据执行
out, = exe.run(feed={"x":x_data}, fetch_list=[y.name], return_numpy=False)
此时得到的out.shape[0]就是32，与按公式推导的结论一致。
