### ISSUE TITLE
并行模式读取非并行训练模型参数的问题

### ISSUE THREAD

**Issue by mottled233** [PaddlePaddle/Paddle#22949]
您好，我在训练时采用了单卡gpu训练，训练结束后调用 io.save_persistables保存参数。
在预测阶段读取模型时，我计划采用多卡并行，使用
CompiledProgram(self.predict_program). with_data_parallel
进行并行处理，但在读取参数时出现问题（读取使用 io.load_vars）。

我的程序中，如果先读取参数，之后CompiledProgram，会报错
Error: Cannot find fetched variable(qas_ids).(Perhaps the main_program is not set to ParallelExecutor) at (/paddle/paddle/fluid/framework/details/fast_threaded_ssa_graph_executor.cc:145)

如果在先CompiledProgram，后读取参数，会报错
TypeError: program's type should be Program

请问怎么解决？

**Comment by mottled233** [comment]
代码如下：
` # 加载模型参数到网络中
        load_model_params(self.exe, model_path, self.predict_program)

        # 若并行，用并行编译program
        if self.args["use_parallel"]:
            build_strategy = fluid.BuildStrategy()
            # 并行策略暂时写死
            build_strategy.reduce_strategy = fluid.BuildStrategy.ReduceStrategy.Reduce
            self.predict_program = fluid.CompiledProgram(self.predict_program). \
                with_data_parallel(places=TrainEngine.get_data_run_places(self.args),
                                   build_strategy=build_strategy)`

报错信息如下：
`--------------------------------------------
C++ Call Stacks (More useful to developers):
--------------------------------------------
0   std::string paddle::platform::GetTraceBackString<char const*>(char const*&&, char const*, int)
1   paddle::platform::EnforceNotMet::EnforceNotMet(std::__exception_ptr::exception_ptr, char const*, int)
2   paddle::framework::details::FastThreadedSSAGraphExecutor::InsertFetchOps(std::vector<std::string, std::allocator<std::string> > const&, std::vector<paddle::framework::LoDTensor, std::allocator<paddle::framework::LoDTensor> >*, std::unordered_map<std::string, std::vector<paddle::framework::details::VarHandleBase*, std::allocator<paddle::framework::details::VarHandleBase*> >, std::hash<std::string>, std::equal_to<std::string>, std::allocator<std::pair<std::string const, std::vector<paddle::framework::details::VarHandleBase*, std::allocator<paddle::framework::details::VarHandleBase*> > > > >*, std::unordered_map<paddle::framework::details::OpHandleBase*, std::atomic<int>, std::hash<paddle::framework::details::OpHandleBase*>, std::equal_to<paddle::framework::details::OpHandleBase*>, std::allocator<std::pair<paddle::framework::details::OpHandleBase* const, std::atomic<int> > > >*, std::vector<paddle::framework::details::OpHandleBase*, std::allocator<paddle::framework::details::OpHandleBase*> >*, std::vector<paddle::framework::details::OpHandleBase*, std::allocator<paddle::framework::details::OpHandleBase*> >*)
3   paddle::framework::details::FastThreadedSSAGraphExecutor::Run(std::vector<std::string, std::allocator<std::string> > const&)
4   paddle::framework::details::ScopeBufferedMonitor::Apply(std::function<void ()> const&, bool)
5   paddle::framework::details::ScopeBufferedSSAGraphExecutor::Run(std::vector<std::string, std::allocator<std::string> > const&)
6   paddle::framework::ParallelExecutor::Run(std::vector<std::string, std::allocator<std::string> > const&)

----------------------
Error Message Summary:
----------------------
Error: Cannot find fetched variable(qas_ids).(Perhaps the main_program is not set to ParallelExecutor) at (/paddle/paddle/fluid/framework/details/fast_threaded_ssa_graph_executor.cc:145)
`

**Comment by chenwhql** [comment]
> 您好，我在训练时采用了单卡gpu训练，训练结束后调用 io.save_persistables保存参数。
> 在预测阶段读取模型时，我计划采用多卡并行，使用
> CompiledProgram(self.predict_program). with_data_parallel
> 进行并行处理，但在读取参数时出现问题（读取使用 io.load_vars）。

有几点确认下：
1. 这里说用多卡并行，载入时出错？那单卡载入呢？正常吗？
2. 这里不用Io.load_vars，用io.load_persistables试试呢？save，load接口按名字对应的

**Comment by mottled233** [comment]
单卡是正常的。另外我在训练时加载使用的是io.load_persistables，也是正常的（指单卡训练过程，还没有尝试多卡加载），预测时用这个接口可能不符合需求。

**Comment by chenwhql** [comment]
> 预测时用这个接口可能不符合需求

您使用load_vars是直接传入的main_program吗？按理说您只save了persistable的变量，直接load所有的变量没报错吗？

此外：
还是应该在compiledProgram之前load比较合适，您看您报的这个错，是说fetch的这个变量没找到，一般原因可能是：
1. main program里面没有qas_ids这个变量
2. 这个qas_ids不在graph里，不是任何op的输入或者输出，是一个游离变量
（最新版paddle会报出以上两个原因，您可以换新版paddle试试）

因为这边，没有您code和环境，麻烦您先确认下为什么会在这里报fetch出错？是什么原因，qas_ids这个变量是什么状态

**Comment by mottled233** [comment]
是的，直接传入，并判断相应变量文件存不存在，我之前没有关注persistable的问题，但在我的测试过程中问题不大，所有需要的参数都被加载了。
另外，确实这个变量是直接传出来的，没有经过计算，直接fetch，原来这也会有问题啊

**Comment by chenwhql** [comment]
> 另外，确实这个变量是直接传出来的，没有经过计算，直接fetch，原来这也会有问题啊

您的意思是，qas_ids是一个游离变量吗？

游离变量应该是不推荐用的，单卡的时候就是按拓扑顺序执行计算，应该没问题，而多卡要构建计算图，如果没有连到图里，是会报错的

**Comment by minhozhou** [comment]
> > 另外，确实这个变量是直接传出来的，没有经过计算，直接fetch，原来这也会有问题啊
> 
> 您的意思是，qas_ids是一个游离变量吗？
> 
> 游离变量应该是不推荐用的，单卡的时候就是按拓扑顺序执行计算，应该没问题，而多卡要构建计算图，如果没有连到图里，是会报错的

请问分布式训练时游离变量应该如何fetch呢，比如说像实时学习率这种变量

**Comment by chenwhql** [comment]
学习率为什么是游离的呢？不是optimizer的输入吗

**Comment by minhozhou** [comment]
> 学习率为什么是游离的呢？不是optimizer的输入吗

是optimizer的输入，但用decayed_lr = fluid.layers.polynomial_decay(base_lr, train_steps, 0.0001)这种衰减学习率的时候，单机执行可以fetch，分布式的时候就会报错，报错的内容和这个issue上面Error Message Summary差不多，不太清楚原因是啥
![image](https://user-images.githubusercontent.com/46623470/77600669-8d292f80-6f43-11ea-9829-ec8dc9171a75.png)

**Comment by chenwhql** [comment]
具体单机怎么执行的？单机多卡也是正常的吗？分布式怎么执行的？

**Comment by minhozhou** [comment]
> 具体单机怎么执行的？单机多卡也是正常的吗？分布式怎么执行的？

CPU单机可正常输出当前学习率，没有GPU；分布式用的Fleet的接口，基于paddlecloud的MPI

optimizer代码:
```
def optimization(cloud_train, base_lr, loss, train_steps, optimizer='adam'):
    """ optimization
    """
    # decayed_lr = fluid.layers.polynomial_decay(base_lr, train_steps, 0.0025 * 16)
    decayed_lr = fluid.layers.polynomial_decay(
        learning_rate=base_lr,
        decay_steps=train_steps,
        end_learning_rate=0.0001 * base_lr,
        power=1.0,
        cycle=False)
    decayed_lr.persistable = True
    if optimizer == 'sgd':
        optimizer = fluid.optimizer.SGD(
            decayed_lr,
            regularization=fluid.regularizer.L2DecayRegularizer(
                regularization_coeff=0.0025))
    elif optimizer == 'adam':
        # dont use gpu's lazy mode
        optimizer = fluid.optimizer.Adam(decayed_lr)
    else:
        raise ValueError

    if cloud_train == 1:
        config = DistributeTranspilerConfig()
        config.sync_mode = False
        config.runtime_split_send_recv = True
        optimizer = fleet.distributed_optimizer(optimizer, config)
    log.info('learning rate:%f' % (base_lr))
    optimizer.minimize(loss)
    return decayed_lr
```
MPI分布式train部分代码:
```
           decayed_lr = optimization(args.cloud_train, args.lr * num_devices, loss, train_steps, args.optimizer)
            fleet.init_worker()
            exe = fluid.Executor(fluid.CPUPlace())

            exe.run(fleet.startup_program)
            compiled_prog = build_complied_prog(fleet.main_program, loss)
            train_loop(exe, exe, compiled_prog, decayed_lr, loss, reader, args, item_embed, predict_input_list)
```

单机train部分代码：
```
      decayed_lr = optimization(args.cloud_train, args.lr * num_devices, loss, train_steps, args.optimizer)
       place = fluid.CPUPlace()
        exe = fluid.Executor(place)
        exe.run(fluid.default_startup_program())
        train_prog = fluid.default_main_program()
        train_exe = get_parallel_exe(train_prog, loss)

         train_loop(train_exe, exe, train_prog, decayed_lr, loss, reader, args, item_embed, predict_input_list)
```

train_loop代码：
```
def train_loop(train_exe, exe, program, decayed_lr, loss, data_reader, args, src_embed, input_data_list):
    """ train
    """
    model_save_dir = args.output_path
    if not os.path.exists(model_save_dir):
        os.makedirs(model_save_dir)

    trainer_id = int(os.getenv("PADDLE_TRAINER_ID", "0"))
    step = 0
    epoch = 0
    for epoch in range(args.epoch):
        for data in data_reader():
            begin_time = time.time()
            decayed_lr_val, loss_val = train_exe.run(program, fetch_list=[decayed_lr.name, loss], feed=data)
            log.info(decayed_lr_val)
            # decayed_lr_val = np.array(fluid.executor.global_scope().find_var(decayed_lr.name).get_tensor())
            step += 1
            if step % 10 == 0:
                log.info("epoch %s: step %s: loss %.5f speed: %.5f s/step reader qsize: %s" %
                         (epoch, step, np.mean(loss_val), time.time() - begin_time, data_reader.queue.size()))
```

**Comment by chenwhql** [comment]
我尝试到答疑群里找分布式的同学帮你看，但是没人响应😭，要不您把最后回复code和问题再提一个新的issue？相当于置下顶，让问题重新暴露出来，现在和最初的问题不太一样

**Comment by minhozhou** [comment]
> 我尝试到答疑群里找分布式的同学帮你看，但是没人响应😭，要不您把最后回复code和问题再提一个新的issue？相当于置下顶，让问题重新暴露出来，现在和最初的问题不太一样

哈哈，多谢老哥，重提了

**Comment by chenwhql** [comment]
@mottled233 @minhozhou 两位好，后来还有问题吗？这个issue可以关闭了吗？

**Comment by chenwhql** [comment]
先关闭了，有问题再open
