### ISSUE TITLE
预测出core

### ISSUE THREAD

**Issue by Angus07** [PaddlePaddle/Paddle#22948]
错误信息如下：

terminate called after throwing an instance of 'paddle::platform::EnforceNotMet'
  what():  

--------------------------------------------
C++ Call Stacks (More useful to developers):
--------------------------------------------
0   std::string paddle::platform::GetTraceBackString<std::string const&>(std::string const&, char const*, int)
1   paddle::memory::detail::MetadataCache::load(paddle::memory::detail::MemoryBlock const*) const
2   paddle::memory::detail::MemoryBlock::total_size(paddle::memory::detail::MetadataCache const&) const
3   paddle::memory::detail::MemoryBlock::split(paddle::memory::detail::MetadataCache*, unsigned long)
4   paddle::memory::detail::BuddyAllocator::SplitToAlloc(std::_Rb_tree_const_iterator<std::tuple<unsigned long, unsigned long, void*> >, unsigned long)
5   paddle::memory::detail::BuddyAllocator::Alloc(unsigned long)
6   void* paddle::memory::legacy::Alloc<paddle::platform::CPUPlace>(paddle::platform::CPUPlace const&, unsigned long)
7   paddle::memory::allocation::NaiveBestFitAllocator::AllocateImpl(unsigned long)
8   paddle::memory::allocation::AllocatorFacade::Alloc(boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace> const&, unsigned long)
9   paddle::memory::allocation::AllocatorFacade::AllocShared(boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace> const&, unsigned long)
10  paddle::memory::AllocShared(boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace> const&, unsigned long)
11  paddle::framework::Tensor::mutable_data(boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace>, paddle::framework::proto::VarType_Type, unsigned long)
12  paddle::AnalysisPredictor::SetFeed(std::vector<paddle::PaddleTensor, std::allocator<paddle::PaddleTensor> > const&, paddle::framework::Scope*)
13  paddle::AnalysisPredictor::Run(std::vector<paddle::PaddleTensor, std::allocator<paddle::PaddleTensor> > const&, std::vector<paddle::PaddleTensor, std::allocator<paddle::PaddleTensor> >*, int)

----------------------
Error Message Summary:
----------------------
PaddleCheckError: Expected desc->check_guards() == true, but received desc->check_guards():0 != true:1.
 at [baidu/paddlepaddle/paddle/paddle/fluid/memory/detail/meta_cache.cc:33]

Aborted (core dumped)

core在
#18 0x00007f4a98ffb620 in paddle::AnalysisPredictor::Run(std::vector<paddle::PaddleTensor, std::allocator<paddle::PaddleTensor> > const&, std::vector<paddle::PaddleTensor, std::allocator<paddle::PaddleTensor> >*, int) () from libernie-inference.so

**Comment by Shixiaowei02** [comment]
您好，这个错误是指针访问非法了，请检查一下业务代码的指针是否有问题。

**Comment by LihangLiu** [comment]
同碰到这个问题，模型加载没问题，预测run的时候崩了。具体情况是
在预测前创建paddle::PaddleTensor的时候，tensor.data.Resize(size * sizeof(float))中size=500运行正常，size=10000的时候崩了。其他代码和环境一样。
请问是paddle inference的时候，对于tensor的大小有限制么？

**Comment by Shixiaowei02** [comment]
> 同碰到这个问题，模型加载没问题，预测run的时候崩了。具体情况是
> 在预测前创建paddle::PaddleTensor的时候，tensor.data.Resize(size * sizeof(float))中size=500运行正常，size=10000的时候崩了。其他代码和环境一样。
> 请问是paddle inference的时候，对于tensor的大小有限制么？

没有限制。只要出现 
`PaddleCheckError: Expected desc->check_guards() == true, but received desc->check_guards():0 != true:1.
at [baidu/paddlepaddle/paddle/paddle/fluid/memory/detail/meta_cache.cc:33]`
这种报错，就需考虑用户代码内存越界。

**Comment by LihangLiu** [comment]
好的，我查一下，感谢！
