### ISSUE TITLE
load_inference_model增加一层，再save_inference_model

### ISSUE THREAD

**Issue by liyingying05** [PaddlePaddle/Paddle#22955]
已经保存好的inference_model，想要增加一层argmax，多加一个输出再保存，有办法实现吗？https://github.com/PaddlePaddle/Paddle/issues/16053 查到这个issue问题比较类似，请问如何不在网络里面加层实现这个需求

**Comment by Shixiaowei02** [comment]
您好，目前 Paddle 没有 Python 用户接口能够实现此功能。
