### ISSUE TITLE
动态图固定某些层参数时显存占用不会降低

### ISSUE THREAD

**Issue by xbsu** [PaddlePaddle/Paddle#22954]
在paddle1.7中，通过设置某些层的参数stop_gradient=True，使训练中固定参数不变。但设置后显存占用没有相应减少。而在pytorch中设置requires_grad=False会减少相应显存。请问现在版本是否支持该功能？

**Comment by phlrain** [comment]
这个里面应该有两个层面的问题，
1. 1.7之后，paddle上线了auto grow的策略，会根据使用的内存，动态调整显存的占用，通过nvidia-smi查看的显存占用，可能会比实际任务需要的显存要多，但是任务能够承受的最大batch size 是不影响的。
2. 能帮忙提供下pytorch在设置了 requires_grad之后，显存减少的量么，我们来具体分析下

**Comment by xbsu** [comment]
在我的任务中，通过固定resnet50的前三个block，显存下降5140MB，batchsize=30
