### ISSUE TITLE
Paddle-TRT C++ 错误

### ISSUE THREAD

**Issue by zjutlzt** [PaddlePaddle/Paddle#22963]
复现步骤
使用Padlle-TRT-FP32的模型
没有保存成其他模式-直接是__parma__和  __model__ 
1.docker包在  1080ti的  服务器上 编译好 可以运行
2.docker包导入到 2080ti的服务器上运行预测时出现如下错误

I0311 08:51:40.127867  8785 tensorrt_subgraph_pass.cc:285] Prepare TRT engine (Optimize model structure, Select OP kernel etc). This process may cost a lot of time.
E0311 08:51:42.247627  8785 helper.h:65] ../rtSafe/cuda/cudaConvolutionRunner.cpp (303) - Cudnn Error in execute: 8 (CUDNN_STATUS_EXECUTION_FAILED)
E0311 08:51:42.248762  8785 helper.h:65] ../rtSafe/cuda/cudaConvolutionRunner.cpp (303) - Cudnn Error in execute: 8 (CUDNN_STATUS_EXECUTION_FAILED)
terminate called after throwing an instance of 'paddle::platform::EnforceNotMet'
  what():

**Comment by zjutlzt** [comment]
--------------------------------------------
C++ Call Stacks (More useful to developers):
--------------------------------------------
0   std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > paddle::platform::GetTraceBackString<char const*>(char const*&&, char const*, int)
1   paddle::platform::EnforceNotMet::EnforceNotMet(std::__exception_ptr::exception_ptr, char const*, int)
2   paddle::inference::tensorrt::TensorRTEngine::FreezeNetwork()
3   paddle::inference::tensorrt::OpConverter::ConvertBlockToTRTEngine(paddle::framework::BlockDesc*, paddle::framework::Scope const&, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, std::unordered_set<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::hash<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::equal_to<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, paddle::inference::tensorrt::TensorRTEngine*)
4   paddle::inference::analysis::TensorRtSubgraphPass::CreateTensorRTOp(paddle::framework::ir::Node*, paddle::framework::ir::Graph*, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >*) const
5   paddle::inference::analysis::TensorRtSubgraphPass::ApplyImpl(paddle::framework::ir::Graph*) const
6   paddle::framework::ir::Pass::Apply(paddle::framework::ir::Graph*) const
7   paddle::inference::analysis::IRPassManager::Apply(std::unique_ptr<paddle::framework::ir::Graph, std::default_delete<paddle::framework::ir::Graph> >)
8   paddle::inference::analysis::IrAnalysisPass::RunImpl(paddle::inference::analysis::Argument*)
9   paddle::inference::analysis::Analyzer::RunAnalysis(paddle::inference::analysis::Argument*)
10  paddle::AnalysisPredictor::OptimizeInferenceProgram()
11  paddle::AnalysisPredictor::PrepareProgram(std::shared_ptr<paddle::framework::ProgramDesc> const&)
12  paddle::AnalysisPredictor::Init(std::shared_ptr<paddle::framework::Scope> const&, std::shared_ptr<paddle::framework::ProgramDesc> const&)
13  std::unique_ptr<paddle::PaddlePredictor, std::default_delete<paddle::PaddlePredictor> > paddle::CreatePaddlePredictor<paddle::AnalysisConfig, (paddle::PaddleEngineKind)2>(paddle::AnalysisConfig const&)
14  std::unique_ptr<paddle::PaddlePredictor, std::default_delete<paddle::PaddlePredictor> > paddle::CreatePaddlePredictor<paddle::AnalysisConfig>(paddle::AnalysisConfig const&)

**Comment by cryoco** [comment]
您好，麻烦提供下使用的Paddle预测库版本，cuda、cudnn、TensorRT版本哈

**Comment by zjutlzt** [comment]
我想问一下 。  是不是 算力  6.1 编译的paddle-lib     放到7.5的设备上 就会这样？

**Comment by cryoco** [comment]
> 我想问一下 。 是不是 算力 6.1 编译的paddle-lib 放到7.5的设备上 就会这样？

如果是自己编译的paddle的话，需要在编译选项CUDA_ARCH里加入运行设备的架构，比如2080是sm_75，或者设置CUDA_ARCH=All以兼容所有架构

**Comment by zjutlzt** [comment]
好的谢谢那应该就是这个问题了非常感谢，因为我当时在编译的时候，设备架构只到 61，
还有一个问题就是yolov3在在 paddleTrt上  做检测的时候，我使用的是  【3，288，288】的小尺寸，
但是返回的 结果出现了 大于300的坐标。  我想问一下是不是  设置了最小不能低于320的？

**Comment by zjutlzt** [comment]
还是在检测的时候   yolo的 初始长宽必须相同？

**Comment by cryoco** [comment]
您模型的输入shape是多少呢，目前paddle TensorRT还不支持变长输入，预计下个版本1.7.1开始支持

**Comment by zjutlzt** [comment]
我是 [3,320,608] 代码过程都是对的  但是结果是错的

**Comment by zjutlzt** [comment]
对试过了    yolov3
