### ISSUE TITLE
Small performance drop on Resnets

### ISSUE THREAD

**Issue by grygielski** [PaddlePaddle/Paddle#22964]
Merging https://github.com/PaddlePaddle/Paddle/pull/22695 introduced small overhead in convolutions with residual connection. It resulted in performance drop on all Resnet models:

**Performance change [FPS]**

*CLX platform:*
```
resnet50_int8     47.97 -> 46.60
resnet50_fp32     13.28 -> 12.01
resnet101_fp32    7.29 -> 6.65
resnet101_int8    26.78 -> 25.01
```

*SKX platform:*
```
resnet50_int8     22.87 -> 22.46
resnet50_fp32     13.65 -> 12.91
resnet101_fp32    7.37 -> 6.99
resnet101_int8    12.20 -> 12.07
```
It's inevitable result of change from moving Tensor's pointer to copying it's data. I just wanted to let you know and ask what do you think about it?

**Comment by GaoWei8** [comment]
@grygielski Since performance drop on all Resnet models, PR #22695 can be revert. After reverting, the reasons for not following Paddle Operators Standards and this issue link can be added in code comments with one new PR.

**Comment by lidanqing-vv** [comment]
#22985  is merged, so I close this PR @grygielski
