### ISSUE TITLE
文档中的拼写错误

### ISSUE THREAD

**Issue by skywalk163** [PaddlePaddle/Paddle#22972]
文档中拼写错误：
https://www.paddlepaddle.org.cn/documentation/docs/zh/beginners_guide/coding_practice/test_while_training.html

文档-快速上手-编程实践-单机训练-训练过程中评测模型

位于：分别配置训练 fluid.Program 和测试 fluid.Program 小节中的代码拼写错误：
    with fluid.program_gurad(test_program, fluid.Program()):
        test_loss = network(is_test=True)

应该是
    with fluid.program_guard(test_program, fluid.Program()):
        test_loss = network(is_test=True)

**Comment by 1024er** [comment]
好的，感谢，已经给负责人反馈修改了。
