### ISSUE TITLE
paddle1.7 安装后 run_check()失败

### ISSUE THREAD

**Issue by psnine** [PaddlePaddle/Paddle#22981]
1）PaddlePaddle版本：1.7.0
    2）CPU：i7-6800K
    3）GPU：2块 TITAN Xp，CUDA 10.0 和CUDNN 7.6
    4）系统环境：ubuntu 14.04 、Python3.7.6
- 安装方式信息：
conda安装

- 问题描述：请详细描述您的问题，同步贴出报错信息、日志/代码关键片段
paddle.fluid.install_check.run_check() 报错 内容显示如下所示
![NFQ7~G2K~9}6F8KD2M(CZLT](https://user-images.githubusercontent.com/27390152/76489442-5216fe80-6463-11ea-9c25-e32600888795.png)
![QQ截图20200312131443](https://user-images.githubusercontent.com/27390152/76489493-7a9ef880-6463-11ea-8d34-cead6baa70b8.png)

**Comment by JepsonWong** [comment]
直接是段错误么？其他提示信息也没有么？

**Comment by JepsonWong** [comment]
麻烦输出一下cuda、cudnn的配置信息。

**Comment by psnine** [comment]
没有提示信息，到段错误就结束了

>>> paddle.fluid.install_check.run_check()
Running Verify Paddle Program ... 
W0312 10:15:01.107712  4820 device_context.cc:237] Please NOTE: device: 0, CUDA Capability: 61, Driver API Version: 10.0, Runtime API Version
: 10.0W0312 10:15:01.110395  4820 device_context.cc:245] device: 0, cuDNN Version: 7.6.
Your Paddle works well on SINGLE GPU or CPU.
I0312 10:15:01.666990  4820 parallel_executor.cc:440] The Program will be executed on CUDA using ParallelExecutor, 2 cards are used, so 2 pro
grams are executed in parallel.W0312 10:15:02.694221  4820 init.cc:209] Warning: PaddlePaddle catches a failure signal, it may not work properly
W0312 10:15:02.694265  4820 init.cc:211] You could check whether you killed PaddlePaddle thread/process accidentally or report the case to Pa
ddlePaddleW0312 10:15:02.694278  4820 init.cc:214] The detail failure signal is:

W0312 10:15:02.694293  4820 init.cc:217] *** Aborted at 1583979302 (unix time) try "date -d @1583979302" if you are using GNU date ***
W0312 10:15:02.696835  4820 init.cc:217] PC: @                0x0 (unknown)
W0312 10:15:02.696946  4820 init.cc:217] *** SIGSEGV (@0x0) received by PID 4820 (TID 0x7f733257b740) from PID 0; stack trace: ***
W0312 10:15:02.699158  4820 init.cc:217]     @     0x7f733216d340 (unknown)
W0312 10:15:02.701469  4820 init.cc:217]     @                0x0 (unknown)
段错误 (核心已转储)


![cuda](https://user-images.githubusercontent.com/27390152/76502617-518c6100-647f-11ea-9b99-0e5718a35e53.JPG)
![cudnn](https://user-images.githubusercontent.com/27390152/76502630-581ad880-647f-11ea-8f4b-8de045599958.JPG)

**Comment by JepsonWong** [comment]
安装了docker么？能下一个paddle gpu版本的docker测一下么？

**Comment by psnine** [comment]
没装docker

**Comment by JepsonWong** [comment]
无法复现错误，可以尝试安装develop版本的安装包试试看 https://www.paddlepaddle.org.cn/documentation/docs/zh/install/Tables.html#whl-dev

**Comment by psnine** [comment]
链接 502了，是我的问题吗

The server is temporarily unable to service your request due to maintenance downtime or capacity problems. Please try again later.(code:0-5-11.46)

**Comment by JepsonWong** [comment]
> 链接 502了，是我的问题吗
> 
> The server is temporarily unable to service your request due to maintenance downtime or capacity problems. Please try again later.(code:0-5-11.46)

刚刚官网出现了问题 目前应该可以了

**Comment by JepsonWong** [comment]
你可以通过export CUDA_VISIBLE_DEVICES设置一下只跑卡1或者卡2，看看是不是显卡问题。

**Comment by psnine** [comment]
我试了下 通过export CUDA_VISIBLE_DEVICES 可以过run_check了
但是nccl我已经装了，理论上不应该出现只有单卡可以用的问题

**Comment by JepsonWong** [comment]
> 我试了下 通过export CUDA_VISIBLE_DEVICES 可以过run_check了
> 但是nccl我已经装了，理论上不应该出现只有单卡可以用的问题

如果两个卡分别单卡模式下都可以，尝试重启下机器和显卡，如果还不行，怀疑是显卡问题。正常nccl没装会有提示信息，你这个是直接段错误。
