### ISSUE TITLE
paddle的dropout和pytorch api行为有diff

### ISSUE THREAD

**Issue by chajchaj** [PaddlePaddle/Paddle#22988]
dropout_implementation参数的可选值是'downgrade_in_infer'或'upscale_in_train'，
缺省值是'downgrade_in_infer'，这种情况下api行为和pytorch不一致，
dropout_implementation参数改成'upscale_in_train'才能跟pytorch一致。

**Comment by Aurelius84** [comment]
非常感谢您的反馈，我们会做进一步的优化，提升您的使用体验。
