### ISSUE TITLE
训练ERROR。 Tensor holds the wrong type, it holds double, but desires to be float

### ISSUE THREAD

**Issue by Archimondecy** [PaddlePaddle/Paddle#22984]
传入数据：inputs['_y'] = fluid.layers.data(name="_y", shape=[1],  dtype="float32", lod_level=0)
训练计算loss：
cost = fluid.layers.square_error_cost(input=pos_score, label=inputs["_y"])
此处报错，说_y 是double，不是float，求帮忙解决
Tensor holds the wrong type, it holds double, but desires to be float

**Comment by Aurelius84** [comment]
请问`pos_score `是什么类型？

**Comment by Archimondecy** [comment]
> 请问`pos_score `是什么类型？
pos_score 为下面的函数返回
![image](https://user-images.githubusercontent.com/9897441/76503745-60741300-6481-11ea-9638-cd9bc8df721b.png)

pos_score应该没问题，因为我尝试了把input和label全部换成 pos_score可以正常运行
cost = fluid.layers.square_error_cost(input=pos_score, label=pos_score)

而如果都换成inputs['_y']还是会报失败
cost = fluid.layers.square_error_cost(input=inputs["_y"], label=inputs["_y"])

**Comment by Archimondecy** [comment]
已解决，在使用_y之前，先做一次fluid.layers.cast 强制类型转换。
