### ISSUE TITLE
Add function to split datasets into multiple files to do cluster train

### ISSUE THREAD

**Issue by typhoonzero** [PaddlePaddle/Paddle#2298]
We need to add a function to split downloaded datasets to multiple raw files and add function to read a subset of the files for each dataset.

Define split functions like:

```python
def split(count, suffix="%05d"):
```

Define cluster readers like:

```python
def cluster_files_reader(TRAIN_FILE_PATTERN):
    train_file_list = glob.glob(TRAIN_FILE_PATTERN)
    train_file_list.sort()
    my_train_list = []
    for idx, f in enumerate(train_file_list):
        if idx % trainer_count == trainer_id:
            my_train_list.append(f)

    for f in my_train_list:
        # do reader stuff...
```

**Comment by Yancey1989** [comment]
I think the function 
```python
def split(count, suffix="%05d")
``` 
Should be 
```python
def split(reader, count, suffix="%05d")
```

So that we can split the dataset into 100 small files as:
```python
split(paddle.dataset.imikolov.train(...), count=100)
```

**Comment by jacquesqiao** [comment]
Is this a function for one single trainer? What is the purpose of this function, I guess it's for random shuffle?

**Comment by Yancey1989** [comment]
I think `split(...)` a general function which convert data from `reader` to many small files, and for each trainer process, `cluster_files_reader(...)` will select the correct files from so many small files.
