### ISSUE TITLE
8gpu下install_check失败

### ISSUE THREAD

**Issue by janelu9** [PaddlePaddle/Paddle#23005]
宿主机是centos cuda10.1 8卡 也装了nccl
docker是ubuntu16.4 cuda10 装的paddle1.7.post107 单卡检测成功 但多卡检测失败了 不知是何原因啊？
![image](https://user-images.githubusercontent.com/24219258/76605418-62a2a400-654b-11ea-864b-307465c1c351.png)

**Comment by LDOUBLEV** [comment]
请问你是按照哪种方式安装的，这个检测应该不分单卡多卡的

**Comment by JepsonWong** [comment]
已经解决用户问题，某张显卡硬件有问题。
