### ISSUE TITLE
采用fluid.save和fluid.load接口保存和加载模型，，，恢复训练时报错

### ISSUE THREAD

**Issue by ahsdx** [PaddlePaddle/Paddle#23012]
- 版本、环境信息：在aistudio上运行，paddle版本是1.6.2
请问下paddle恢复训练时，想换个优化器怎么做😂？比如原来训练时采用的是Adam，用了warm_up策略，cosine_decay，然后我想换成Adam，piecewise_decay。保存模型时用的是fluid.save接口，恢复模型用的是fluid.load接口。
我直接将Adam优化器里面的学习率改成piecewise_decay后报错了。报错信息如下
/home/aistudio/work/tools
W0314 12:20:32.815095  1315 device_context.cc:236] Please NOTE: device: 0, CUDA Capability: 70, Driver API Version: 9.2, Runtime API Version: 9.0
W0314 12:20:32.819011  1315 device_context.cc:244] device: 0, cuDNN Version: 7.3.
Traceback (most recent call last):
  File "recover_train.py", line 172, in <module>
    train()
  File "recover_train.py", line 116, in train
    fluid.load(fluid.default_main_program(), '/home/aistudio/work/tools/efficientdet/efficientdet-d4-49',exe)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/io.py", line 1624, in load
    v.name, opt_file_name)
AssertionError: Can not find [learning_rate] in model file [/home/aistudio/work/tools/efficientdet/efficientdet-d4-49.pdopt]
后面尝试将先前预训练的模型用save_persistables接口保存，然后在用load_persistables接口加载模型，也还是出错。然后听从paddle群管理员GT建议，将learning_rate_warmup文件删除掉也还是报错（说我learning_rate文件不存在）。请问这个怎么解决？

**Comment by phlrain** [comment]
刚开始是sgd，然后想换成adam？

**Comment by ahsdx** [comment]
刚开始还是Adam，后面也是Adam，只是一开始的Adam的学习率是cosine_decay，还用了wramup策略，后面我想换成piecewise_decay，没有warmup策略。直接在原来优化器改，恢复训练时就报错了



---原始邮件---
发件人: "hong"<notifications@github.com&gt;
发送时间: 2020年3月16日(周一) 中午12:01
收件人: "PaddlePaddle/Paddle"<Paddle@noreply.github.com&gt;;
抄送: "Author"<author@noreply.github.com&gt;;"ahsdx"<2589561091@qq.com&gt;;
主题: Re: [PaddlePaddle/Paddle] 采用fluid.save和fluid.load接口保存和加载模型，，，恢复训练时报错 (#23012)




 
刚开始是sgd，然后想换成adam？

**Comment by chenwhql** [comment]
您可以按以下步骤排查一下：
1. 用save load的情况
- learning_rate这种optimzier的辅助变量存储在本地一个后缀为.pdopt的文件里
- 文件存在的话，找不到变量有可能是变量名发生了变化，您可以打印前后两个模型中的所有参数，看看learning_rate变量名是否一样，可以用以下代码打印：
```
import paddle.fluid.transpiler.details.program_utils as pu
pu.program_to_code(fluid.default_main_program(), skip_op_callstack=True)
```
- 如果变量名一致，仍然出现此问题，能否麻烦您提供下简答的代码demo，我们确认下是否存在隐藏的问题？

2. save_persistables load_persistables的情况
- 用这两个接口，报错和前面使用save load一样吗？
- 如果一样的话，也可以按照上面的方法排查下
- 此外，您也可以试用下save_params和load_params是否还会出现同样问题

**Comment by ahsdx** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    
        
            我觉得您可能误会我意思了，我的learning_rate文件是存在的。我是想换个学习率，原来优化器代码是用下面的代码optimizer = fluid.optimizer.Adam(            learning_rate=fluid.layers.linear_lr_warmup(                fluid.layers.cosine_decay(learning_rate=lr, step_each_epoch=step, epochs=num_epochs),                warmup_steps, start_lr, lr),            regularization=fluid.regularizer.L2Decay(l2_decay),        )然后我想换个学习率，其他的不变，代码如下：optimizer = fluid.optimizer.Adam(            learning_rate=fluid.layers.piecewise_decay(boundaries=[4000, 12000, 20000], values=[0.00004, 0.0000225, 0.00001, 0.0000026]),            regularization=fluid.regularizer.L2Decay(l2_decay),        )换成这个代码后，在进行恢复训练，就报错了，报错最后一行的代码如下：Error: Cannot open file /home/aistudio/work/tools/efficientdet/1efficientdet-d4-49/learning_rate for load op at (/paddle/paddle/fluid/operators/load_op.h:37)   [operator < load > error]不知道paddle支不支持在恢复训练时这样换学习率的操作？所以想询问下，如果我想在恢复训练时更换学习率的话，该怎么样操作？
        
    
    
        
            
        
    
    
     
    
        
                    
            
                
                    
                            
                                
                            
                            
                                2589561091
                            
                    
                        
                            
                                    2589561091@qq.com
                            
                        
                
            
        
        
    
    
        签名由
        网易邮箱大师
        定制
    
 

    在2020年3月17日 13:28，Chen Weihang<notifications@github.com> 写道： 



您可以按以下步骤排查一下：

用save load的情况


learning_rate这种optimzier的辅助变量存储在本地一个后缀为.pdopt的文件里
文件存在的话，找不到变量有可能是变量名发生了变化，您可以打印前后两个模型中的所有参数，看看learning_rate变量名是否一样，可以用以下代码打印：

import paddle.fluid.transpiler.details.program_utils as pu
pu.program_to_code(fluid.default_main_program(), skip_op_callstack=True)


如果变量名一致，仍然出现此问题，能否麻烦您提供下简答的代码demo，我们确认下是否存在隐藏的问题？


save_persistables load_persistables的情况


用这两个接口，报错和前面使用save load一样吗？
如果一样的话，也可以按照上面的方法排查下
此外，您也可以试用下save_params和load_params是否还会出现同样问题


—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by chenwhql** [comment]
> Error: Cannot open file /home/aistudio/work/tools/efficientdet/1efficientdet-d4-49/learning_rate for load op at (/paddle/paddle/fluid/operators/load_op.h:37)  [operator < load > error]

好像是没太理解，您是说learning_rate文件存在，然后您把它删了，然后报这个错误吗？

那您的意思是，不想load learning_rate这个值，用自己新定义的是吗？

那您在save_persistables之后，试试用load_params呢？learning_rate属于persistable的变量，但它不是parameter，如果只load parameter的话，应该不会load它

**Comment by ahsdx** [comment]
对的，我不想load上次模型保存时的learningrate，想更换下，然后用load_persistence那个接口和load接口加载模型时候就错误了。您的意思是让我用load_params接口来保存加载模型试试吗？那我保存模型后，是否需要删掉learning_rate文件，然后自己在定义一个学习率后，再用load_params接口加载模型呢？

---原始邮件---
发件人: "Chen Weihang"<notifications@github.com&gt;
发送时间: 2020年3月17日(周二) 下午3:33
收件人: "PaddlePaddle/Paddle"<Paddle@noreply.github.com&gt;;
抄送: "Author"<author@noreply.github.com&gt;;"ahsdx"<2589561091@qq.com&gt;;
主题: Re: [PaddlePaddle/Paddle] 采用fluid.save和fluid.load接口保存和加载模型，，，恢复训练时报错 (#23012)




  
Error: Cannot open file /home/aistudio/work/tools/efficientdet/1efficientdet-d4-49/learning_rate for load op at (/paddle/paddle/fluid/operators/load_op.h:37)&nbsp; [operator < load &gt; error]
  
好像是没太理解，您是说learning_rate文件存在，然后您把它删了，然后报这个错误吗？
 
那您的意思是，不想load learning_rate这个值，用自己新定义的是吗？
 
那您在save_persistables之后，试试用load_params呢？learning_rate属于persistable的变量，但它不是parameter，如果只load parameter的话，应该不会load它

**Comment by chenwhql** [comment]
> 是否需要删掉learning_rate文件，然后自己在定义一个学习率后，再用load_params接口加载模型呢？

不需要，用load params的话，即使文件存在，应该也不会去读取，您先试试看下

**Comment by ahsdx** [comment]
好的，非常感谢您，我现在
正在训练模型，等稍微时候，我会试试的。谢谢了

---原始邮件---
发件人: "Chen Weihang"<notifications@github.com&gt;
发送时间: 2020年3月17日(周二) 下午3:43
收件人: "PaddlePaddle/Paddle"<Paddle@noreply.github.com&gt;;
抄送: "Author"<author@noreply.github.com&gt;;"ahsdx"<2589561091@qq.com&gt;;
主题: Re: [PaddlePaddle/Paddle] 采用fluid.save和fluid.load接口保存和加载模型，，，恢复训练时报错 (#23012)




  
是否需要删掉learning_rate文件，然后自己在定义一个学习率后，再用load_params接口加载模型呢？
  
不需要，用load params的话，即使文件存在，应该也不会去读取，您先试试看下

**Comment by chenwhql** [comment]
不客气，有问题继续沟通

**Comment by ahsdx** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    
        非常感想，已经解决了，我用load_params接口就行了，请问需要我关闭issue吗？
        
    
        
            
        
    
    
     
    
        
                    
            
                
                    
                            
                                
                            
                            
                                2589561091
                            
                    
                        
                            
                                    2589561091@qq.com
                            
                        
                
            
        
        
    
    
        签名由
        网易邮箱大师
        定制
    
 

    在2020年3月17日 15:53，Chen Weihang<notifications@github.com> 写道： 




不客气，有问题继续沟通



—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by chenwhql** [comment]
嗯嗯，麻烦关闭吧

**Comment by ahsdx** [comment]
好的，已经关闭了

---原始邮件---
发件人: "Chen Weihang"<notifications@github.com&gt;
发送时间: 2020年3月17日(周二) 晚上6:21
收件人: "PaddlePaddle/Paddle"<Paddle@noreply.github.com&gt;;
抄送: "Author"<author@noreply.github.com&gt;;"ahsdx"<2589561091@qq.com&gt;;
主题: Re: [PaddlePaddle/Paddle] 采用fluid.save和fluid.load接口保存和加载模型，，，恢复训练时报错 (#23012)




 
嗯嗯，麻烦关闭吧
