### ISSUE TITLE
paddlepaddle docker 各镜像有什么区别呢？

### ISSUE THREAD

**Issue by llxxxll** [PaddlePaddle/Paddle#2301]
https://hub.docker.com/r/paddlepaddle/paddle/tags/
大小从200MB~2GB不等，只能区分GPU/CPU，其他的区别是什么呢

**Comment by wangkuiyi** [comment]
The meaning of the tags are described here: https://github.com/PaddlePaddle/Paddle/blob/develop/doc/getstarted/build_and_install/docker_install_en.rst#usage-of-cpu-only-and-gpu-images
