### ISSUE TITLE
paddlepaddle是否有类似操作

### ISSUE THREAD

**Issue by zhengzhe97** [PaddlePaddle/Paddle#23013]
paddlepaddle是否有类似numpy的操作

![TIM图片20200315101452](https://user-images.githubusercontent.com/26462054/76693771-d22ca680-66a5-11ea-8575-78f30eb7e524.png)

**Comment by 123malin** [comment]
有的，可以在官网文档中参考where + gather_nd op组合。

**Comment by zhengzhe97** [comment]
我把二维reshape到一维，再用IfElse得到结果，再reshape回去效果一样吧

**Comment by 123malin** [comment]
应该是的，你可以用把结果打印出来，看一下是否符合预期。

**Comment by zhengzhe97** [comment]
是一样的
