### ISSUE TITLE
window编译错误

### ISSUE THREAD

**Issue by yousong1992** [PaddlePaddle/Paddle#23015]
在pycharm用虚拟环境安装paddlepaddle1.7.1，安装成功后运行测试代码import paddle.fluid as fluid 
fluid.install_check.run_check()
报错 Process finished with exit code -1073741819 (0xC0000005)
电脑配置 win10 64位  8GB内存

**Comment by zhwesky2010** [comment]
@yousong1992 这个和pycharm的环境关系比较大，应该不是paddle的问题，请问是在debugger模式下运行的，还是run模式下运行的呢？尽量用run模式
然后用pip show h5py查看下h5py的版本号version是多少？

**Comment by yousong1992** [comment]
谢谢您！发自我的华为手机-------- 原始邮件 --------发件人： Zhou Wei <notifications@github.com>日期： 2020年3月16日周一 晚上9:28收件人： PaddlePaddle/Paddle <Paddle@noreply.github.com>抄送： yousong1992 <dltbjys1992@163.com>, Mention <mention@noreply.github.com>主    题： Re: [PaddlePaddle/Paddle] window编译错误 (#23015)

@yousong1992 这个和pycharm的环境关系比较大，应该不是paddle的问题，请问是在debugger模式下运行的，还是run模式下运行的呢？尽量用run模式

然后用pip show h5py查看下h5py的版本号version是多少？

**Comment by yousong1992** [comment]
收到，已经调试成功。重新安装了下环境即可发自我的华为手机-------- 原始邮件 --------发件人： Zhou Wei <notifications@github.com>日期： 2020年3月16日周一 晚上9:28收件人： PaddlePaddle/Paddle <Paddle@noreply.github.com>抄送： yousong1992 <dltbjys1992@163.com>, Mention <mention@noreply.github.com>主    题： Re: [PaddlePaddle/Paddle] window编译错误 (#23015)

@yousong1992 这个和pycharm的环境关系比较大，应该不是paddle的问题，请问是在debugger模式下运行的，还是run模式下运行的呢？尽量用run模式

然后用pip show h5py查看下h5py的版本号version是多少？

**Comment by zhwesky2010** [comment]
@yousong1992 重新安装了哪些环境呀，判断出来了是什么引起的吗。没问题可以关闭issue了哈

**Comment by yousong1992** [comment]
重新按了conda，然后按照步骤一步步走就行，公司没有网，回家关闭。麻烦了发自我的华为手机-------- 原始邮件 --------发件人： Zhou Wei <notifications@github.com>日期： 2020年3月17日周二 下午3:01收件人： PaddlePaddle/Paddle <Paddle@noreply.github.com>抄送： yousong1992 <dltbjys1992@163.com>, Mention <mention@noreply.github.com>主    题： Re: [PaddlePaddle/Paddle] window编译错误 (#23015)

@yousong1992 重新安装了哪些环境呀，判断出来了是什么引起的吗。没问题可以关闭issue了哈
