### ISSUE TITLE
动态图使用fluid.dygraph.Layer.create_parameter报告缺少参数错误

### ISSUE THREAD

**Issue by zhangylch** [PaddlePaddle/Paddle#23021]
1）PaddlePaddle版本：1.7.0
动态图使用create_parameter出现缺少参数self错误,可是官方文档里并没有这个参数。
下面是一个简单的示例，如果是我使用有问题还希望能够给一个例子，如何使用。
import paddle.fluid as fluid
with fluid.dygraph.guard():
   w=fluid.dygraph.Layer.create_parameter(dtype='float64',shape=[2,2])
报错：
Traceback (most recent call last):
  File "14.py", line 3, in <module>
    w=fluid.dygraph.Layer.create_parameter(dtype='float64',shape=[2,2])
TypeError: create_parameter() missing 1 required positional argument: 'self'

**Comment by qingqing01** [comment]
@zylustc 

此函数需要在继承 fluid.Layer的sub-class中用，而不是当做普通的function调用。正确的用法是:

```

class MyModel(fluid.Layer):
    def __init__(self):
        super(MyModel, self).__init__()
        self.w = self.create_parameter(
            dtype='float64',
            shape=[2, 2])

with fluid.dygraph.guard():
    model = MyModel()
    print(model.w)
```

**Comment by zylustc** [comment]
> @zylustc
> 
> 此函数需要在继承 fluid.Layer的sub-class中用，而不是当做普通的function调用。正确的用法是:
> 
> ```
> 
> class MyModel(fluid.Layer):
>     def __init__(self):
>         super(MyModel, self).__init__()
>         self.w = self.create_parameter(
>             dtype='float64',
>             shape=[2, 2])
> 
> with fluid.dygraph.guard():
>     model = MyModel()
>     print(model.w)
> `非常感谢

**Comment by zhangylch** [comment]
> @zylustc
> 
> 此函数需要在继承 fluid.Layer的sub-class中用，而不是当做普通的function调用。正确的用法是:
> 
> ```
> 
> class MyModel(fluid.Layer):
>     def __init__(self):
>         super(MyModel, self).__init__()
>         self.w = self.create_parameter(
>             dtype='float64',
>             shape=[2, 2])
> 
> with fluid.dygraph.guard():
>     model = MyModel()
>     print(model.w)
> ```

非常感谢

**Comment by zhangylch** [comment]
非常感谢发自我的华为手机-------- 原始邮件 --------发件人： qingqing01 <notifications@github.com>日期： 2020年3月16日周一 11:42收件人： PaddlePaddle/Paddle <Paddle@noreply.github.com>抄送： zyl12138 <ylzustc@mail.ustc.edu.cn>, Mention <mention@noreply.github.com>主    题： Re: [PaddlePaddle/Paddle] 动态图使用fluid.dygraph.Layer.create_parameter报告缺少参数错误 (#23021)

@zylustc

次函数需要在继承 fluid.Layer的sub-class中用，而不是当做普通的function调用。正确的用法是:



class MyModel(fluid.Layer):

    def __init__(self):

        super(MyModel, self).__init__()

        self.w = self.create_parameter(

            dtype='float32',

            shape=[2, 2])



with fluid.dygraph.guard():

    model = MyModel()

    print(model.w)
