### ISSUE TITLE
Exposure of estimated time of training 

### ISSUE THREAD

**Issue by weiexcelpro** [PaddlePaddle/Paddle#23023]
Hi Paddler,

It's very inconvenient that I cannot know how long time I should wait to see the result when the training started.  Especially the training may take a couple of weeks!

Could you consider to add a feature that output the estimated time when the training starts?

Thanks,
Wey

**Comment by qingqing01** [comment]
@weiexcelpro Which model do you use?  In some models, like PaddleDetection, PaddleSeg, give the ETA time.

**Comment by weiexcelpro** [comment]
> @weiexcelpro Which model do you use? In some models, like PaddleDetection, PaddleSeg, give the ETA time.

Could you show me a snapshot? Actually I prefer that here is an interface or API I can call, not parsing the output context. So that I can use this information for a higher integration. 

Or, it'd better be an individual tool.

Thanks,
Wey

**Comment by qingqing01** [comment]
@weiexcelpro  How do you think this ProgressBar  ?https://github.com/PaddlePaddle/hapi/blob/master/progressbar.py#L6 

If give the total-steps and call the `update`,  will print the ETA.
