### ISSUE TITLE
fc layer设置bias_attr=None后仍包含了bias项

### ISSUE THREAD

**Issue by mapingshuo** [PaddlePaddle/Paddle#23033]
复现代码：

```python
import paddle
import paddle.fluid as fluid

x = fluid.layers.data(name='x', shape=[5, 4])
fc = fluid.layers.fc(input=x, size=7, bias_attr=None)
loss = fluid.layers.mean(fc)

sgd = fluid.optimizer.SGD(learning_rate = 0.01)
sgd.minimize(loss)

place = fluid.CPUPlace()
exe = fluid.Executor(place)

exe.run(fluid.default_startup_program())

fluid.io.save_params(exe,
                     "demo_model_dir")

with open("main_program", "w") as f:
  f.write(str(fluid.default_main_program()))
```

![image](https://user-images.githubusercontent.com/23031310/76745989-b9a9b280-67b1-11ea-90e0-72ef46e27f00.png)

而文档中说：“如果 bias_attr 非空，则会创建一个偏置变量（bias variable），并把它累加到输出结果中。”

**Comment by qingqing01** [comment]
文档:  https://www.paddlepaddle.org.cn/documentation/docs/zh/api_cn/layers_cn/fc_cn.html#fc

> bias_attr (ParamAttr) – 指定偏置参数属性的对象。默认值为None，表示使用默认的偏置参数属性。具体用法请参见 ParamAttr 。

是说None的时候，使用默认的bias。是觉得这个有误解？
