### ISSUE TITLE
paddle的crf功能

### ISSUE THREAD

**Issue by qhpeklh5959** [PaddlePaddle/Paddle#23049]
欢迎您对PaddlePaddle提出建议，非常感谢您对PaddlePaddle的贡献！
在留下您的建议时，辛苦您同步提供如下信息：
- 版本、环境信息
1）PaddlePaddle版本：请提供您的PaddlePaddle版本号，例如1.1
2）CPU/GPU：您是否使用GPU进行训练，如是，请提供您的CUDA和cuDNN版本号
3）系统环境：请您描述系统类型、版本，例如Mac OS 10.14
- 复现信息：如为报错，请给出复现环境、复现步骤
- 建议描述：请您详细描述，您认为需优化的功能

Thank you for contributing to PaddlePaddle.
Before submitting the issue, you could search issue in the github in case that there was a similar issue submitted or resolved before.
Please make sure that this is a feature request. 
**System information**
-PaddlePaddle version （eg.1.1）or CommitID
-CPU: including CPUMKL/OpenBlas/MKLDNN version
-GPU: including CUDA/CUDNN version
-OS Platform (eg.Mac OS 10.14)
**To Reproduce**
Steps to reproduce the behavior
**Describe the feature and the current behavior/state.**
**Any Other info.**

paddle的crf是否能够添加input mask功能，以方便在padding的情况下，解码中直接得到目标串的长度，以及在计算似然性的过程中，能够屏蔽掉padding，或者有在联合模型的时候屏蔽掉一些输入的需求。

另外，能否增加constraint矩阵的功能，以做到在做类似于分词这类有强词边界需求的时候，解码过程中能够解出来正确无冲突的标注结果，如BIES序列标注，可按照规则解码。我看到paddle中有chunk_eval功能，为什么没有加入chunk_decode这类功能？

**Comment by guoshengCS** [comment]
目前Paddle的实现应该是屏蔽掉padding的，当前应该能够通过length这个参数屏蔽掉每个sequence在length之后的内容。

> 能否增加constraint矩阵的功能，
这个目前还没有计划 ，可否以pyfunc的形式先自行实现
