### ISSUE TITLE
ValueError: share_vars_from is not compiled and run, so there is no var to share

### ISSUE THREAD

**Issue by paulpaul91** [PaddlePaddle/Paddle#23044]
- 版本、环境信息：
    1）PaddlePaddle版本：paddle 1.7

    3）GPU：预测若用GPU，请提供GPU型号、CUDA和CUDNN版本号
    4）系统环境：请您描述系统类型、版本，例如Mac OS 10.14，Python版本
- 训练信息
    1）单机，多卡
单机多卡，训练过程中有预测环节，设置share_vars_from代码运行报错

**Comment by qingqing01** [comment]
@paulpaul91 share_vars_from的那个compiled的program已经运行了吗？
