### ISSUE TITLE
ValueError: 'Preprocessor_map_while_Merge' is not in list

### ISSUE THREAD

**Issue by rupei110** [PaddlePaddle/Paddle#23045]
paddlepaddle-gpu 版本1.7.0.post107，Centos7 系统， X2paddle转tensorflow官方模型ssd_mobilenet_v1_coco出现错误
![image](https://user-images.githubusercontent.com/50095586/76810214-40997200-6828-11ea-90ef-72b8f4c2be6c.png)
请问这是什么原因

**Comment by Xreki** [comment]
请问您使用的x2paddle的版本是？

**Comment by rupei110** [comment]
> 请问您使用的x2paddle的版本是？

x2paddle 是0.7.1版本

**Comment by jiangjiajun** [comment]
> paddlepaddle-gpu 版本1.7.0.post107，Centos7 系统， X2paddle转tensorflow官方模型ssd_mobilenet_v1_coco出现错误
> ![image](https://user-images.githubusercontent.com/50095586/76810214-40997200-6828-11ea-90ef-72b8f4c2be6c.png)
> 请问这是什么原因

Hi，你好，受限于TensorFlow的SSD模型中部分OP与Paddle实现不同，目前X2Paddle未支持TensorFlow的SSD模型的转换。但Paddle目前有官方检测库，其中包括了SSD模型，建议尝试一下PaddleDetection。
https://github.com/PaddlePaddle/PaddleDetection/blob/release/0.2/docs/MODEL_ZOO_cn.md
