### ISSUE TITLE
paddle transformer翻译模型，支持beamsearch定向翻译吗

### ISSUE THREAD

**Issue by dpwu1994** [PaddlePaddle/Paddle#23048]
如题，有demo吗

**Comment by Xreki** [comment]
Paddle开源的transformer在[这里](https://github.com/PaddlePaddle/models/tree/develop/PaddleNLP/machine_translation/transformer)。请问您说的“定向”具体是指什么？

**Comment by dpwu1994** [comment]
beamsearch + 前缀树实现，翻译出的句子都在提供的集合中

**Comment by Xreki** [comment]
找@guoshengCS 确认过，Paddle的开源实现暂时不支持该功能。
