### ISSUE TITLE
kronecker积和支持复数运算

### ISSUE THREAD

**Issue by gxli2017** [PaddlePaddle/Paddle#23054]
1）PaddlePaddle版本：请提供您的PaddlePaddle版本号，例如1.7.1
2）CPU/GPU：CPU训练
3）系统环境：Mac OS 10.11.6
- 建议描述：
          建议增加支持矩阵的kronecker积运算；
          建议增加支持复数类型的矩阵乘积运算。

**Comment by Xreki** [comment]
您好，感谢您的建议。请问您是在什么场景或模型需要这个功能呢？

**Comment by gxli2017** [comment]
在模拟量子神经网络的场景。因为量子计算是建立在复数域上的矩阵乘积运算，并且伴随着 大量的kronecker积运算

**Comment by Xreki** [comment]
好的，我会反馈下您这个需求的。若您着急使用相应功能的话，可尝试：
1. 使用基础op拼凑出对应的功能
2. 使用[py_func](https://www.paddlepaddle.org.cn/documentation/docs/zh/api_cn/layers_cn/py_func_cn.html#py-func)在Python中定制op，参考文档[如何写新的Python OP](https://www.paddlepaddle.org.cn/documentation/docs/zh/advanced_guide/addon_development/new_op/new_python_op.html)
3. 外部实现C++ op，参考[如何在框架外部自定义C++ OP](https://www.paddlepaddle.org.cn/documentation/docs/zh/advanced_guide/addon_development/new_op/custom_op.html)
