### ISSUE TITLE
动态图中如何进行预训练?

### ISSUE THREAD

**Issue by Quan-zzx** [PaddlePaddle/Paddle#23058]
由于paddlehub还不支持动态图,那我想在动态图里使用预训练的参数该怎么办,就比如我想实现一个VGG+FCN,在VGG中使用预训练好的参数.

**Comment by Xreki** [comment]
动态图可以使用[load_dygraph](https://www.paddlepaddle.org.cn/documentation/docs/zh/api_cn/dygraph_cn/load_dygraph_cn.html#load-dygraph)，可参考[models/dygraph/transformer](https://github.com/PaddlePaddle/models/blob/04bb6a8c369bd3b78352d7aa626e4cb93885bda7/dygraph/transformer/train.py#L98)

**Comment by Quan-zzx** [comment]
> 动态图可以使用[load_dygraph](https://www.paddlepaddle.org.cn/documentation/docs/zh/api_cn/dygraph_cn/load_dygraph_cn.html#load-dygraph)，可参考[models/dygraph/transformer](https://github.com/PaddlePaddle/models/blob/04bb6a8c369bd3b78352d7aa626e4cb93885bda7/dygraph/transformer/train.py#L98)

谢谢

**Comment by Quan-zzx** [comment]
> 动态图可以使用[load_dygraph](https://www.paddlepaddle.org.cn/documentation/docs/zh/api_cn/dygraph_cn/load_dygraph_cn.html#load-dygraph)，可参考[models/dygraph/transformer](https://github.com/PaddlePaddle/models/blob/04bb6a8c369bd3b78352d7aa626e4cb93885bda7/dygraph/transformer/train.py#L98)

不过我尝试了一下,我现在[这里](https://github.com/PaddlePaddle/models/blob/develop/PaddleCV/image_classification/README.md#%E5%B7%B2%E5%8F%91%E5%B8%83%E6%A8%A1%E5%9E%8B%E5%8F%8A%E5%85%B6%E6%80%A7%E8%83%BD),下载了vgg16的预训练模型,然后准备将参数导入动态图,来训练,可是后来发现load_dygraph 这个函数要求模型参数文件后缀为 .pdparams.  所是有什么方法可以解决这个问题?
