### ISSUE TITLE
动态图是否支持对指定Param求梯度

### ISSUE THREAD

**Issue by baiyfbupt** [PaddlePaddle/Paddle#23052]
类似pytorch的
```python
torch.autograd.grad(loss, params)
```
或者paddle 静态图的
```python
fluid.gradients(loss, params)
```
paddle 动态图中目前只找到一种方法，全图backward，再取出目标梯度
```
loss.backward()
grads = [param._grad_ivar() for param in target_params]
```
最后这种方法对整个网络求了梯度，但如果我只需要其中的很小一部分，这种方法可能会有速度问题。想咨询下目前动态图是否可以支持loss仅对指定的param求梯度

**Comment by Xreki** [comment]
动态图目前不支持这个功能，可以在下个版本中支持。
当前，动态图也支持**自动剪枝**的功能，具体见[文档](https://www.paddlepaddle.org.cn/documentation/docs/zh/beginners_guide/basic_concept/dygraph/DyGraph.html#id3)。你可以尝试将不需要计算地图的参数设置`stop_gradient=True`。
