### ISSUE TITLE
关于用conda安装paddle过程的问题

### ISSUE THREAD

**Issue by littleluckhealer8** [PaddlePaddle/Paddle#23072]
当我安装官网快速安装步骤，一步一步安装完后检查时，提示：
```
There is no accurate error hint for this error yet. We are continuously in the process of increasing hint for this kind of error check. It would be helpful if you could inform us of how this conversion went by opening a github issue. And we will resolve it with high priority. 
``` 

但paddle.fluid.install_check.run_check()又提示：
```
your paddle is installed successfully!let's start deep learning with paddle now.
```

由此可能把paddle.fluid未安装，在用Spyder运行程序时提示：
```
no module named"paddle.fluid"
```

omg  我也不知道怎么办啊

**Comment by Xreki** [comment]
> 但paddle.fluid.install_check.run_check()又提示：
> 
> your paddle is installed successfully!let's start deep learning with paddle now.

说明你的Paddle已经安装成功。至少在某个Python版本上已经安装成功了。

> 在用Spyder运行程序时提示：
>
> no module named"paddle.fluid"

请检查一下，你的运行环境上是否有多个Python版本？

**Comment by littleluckhealer8** [comment]
> > 但paddle.fluid.install_check.run_check（）又提示：
> > 您的桨已成功安装！现在就开始使用桨进行深度学习。
> 
> 说明你的Paddle已经安装成功。至少在某个Python版本上已经安装成功了。
> 
> > 在用Spyder运行程序时提示：
> > 没有名为“ paddle.fluid”的模块
> 
> 请检查一下，你的运行环境上是否有多个Python版本？

是有两个python版本，那我卸载了再试试，谢谢您
