### ISSUE TITLE
[DNNL] Refactor activation code

### ISSUE THREAD

**Issue by jczaja** [PaddlePaddle/Paddle#23070]
Growing number of activations of DNNL made part of code bloated and perhaps not very efficient
Goal is to refactor it , so new activations are easier to add/maintain. Relevant code:
 
https://github.com/PaddlePaddle/Paddle/blob/eec10aaba2f6c19bf08f3e4983a1dabcca4a5844/paddle/fluid/platform/mkldnn_reuse.h#L977-L988

**Comment by jczaja** [comment]
@pawelpiotrowicz Please take a look at that. we have PR with swish activtion and Gelu activation so
this refactoring will make it easier to maintain

**Comment by luotao1** [comment]
Could you consider to unify the name of `paddle/fluid/operators/mkldnn/mkldnn_activation_op.h` and `paddle/fluid/operators/mkldnn/activation_mkldnn_op.cc`, such as `activation_mkldnn_op.h`?

**Comment by jczaja** [comment]
tracked internally
