### ISSUE TITLE
paddle1.7 无法导入之前已经保存的模型

### ISSUE THREAD

**Issue by waaaaaaater** [PaddlePaddle/Paddle#23080]
更新paddle1.7  采用动态图，获取之前版本保留的模型，会报错，

在checkpiont文件中的134行 
    with open(params_file_path, 'rb') as f:
        para_dict = pickle.load(f) if six.PY2 else pickle.load(
            f, encoding='latin1')
时，会显示如下的错误
_pickle.UnpicklingError: invalid load key, 'x'.

将版本更改到1.6.2时，就可以正常读取模型

**Comment by DDDivano** [comment]
可以发一下完整代码吗？或者使用fluid.save, fluid.load试试？

**Comment by waaaaaaater** [comment]
试过了，fluid.save是可以load出来的，谢谢
