### ISSUE TITLE
版本升级时增加兼容性说明

### ISSUE THREAD

**Issue by chliang** [PaddlePaddle/Paddle#23093]
现在paddle版本迭代比较快，在版本发布的时候，能不能增加兼容性说明，比如模型方面，1.6.3训练的模型，用1.7 的预测库能否正常运行。

**Comment by lanxianghit** [comment]
> 现在paddle版本迭代比较快，在版本发布的时候，能不能增加兼容性说明，比如模型方面，1.6.3训练的模型，用1.7 的预测库能否正常运行。

1.7版本静态图和预测库满足向后兼容（Backwards Compatibility），所以1.6.3静态图训练的模型，用1.7 的预测库可以正常运行；动态图不满足向后兼容，但由于1.7之前动态图没有提供预测库可预测的功能，所以动态图方面不存在已训出模型和预测库之间的关系。

感谢建议，后续我们会在版本的Release Note中加入兼容性说明。
