### ISSUE TITLE
windows调用paddleV1.7库，进行yolov3目标检测，模型构建报错！

### ISSUE THREAD

**Issue by ZHOUKAI1** [PaddlePaddle/Paddle#23096]
windows7， cuda是9.0 ，i7-6700 16g，P4000
用官方编译好的库，vs2015调用进行目标检测。
[yolo模型连接](https://aistudio.baidu.com/aistudio/projectdetail/273746)

到 predictor = CreatePaddlePredictor(config);就报错：
0x000007FEFCBCA06D 处(位于 windows_mobilenet.exe 中)有未经处理的异常: Microsoft C++ 异常: paddle::platform::EnforceNotMet，位于内存位置 0x00000000000DBBA0 处。

官方给的只有分类代码，没有目标检测例子，难道不通用么。加载分类模型可以跑出结果，目标检测是哪出问题？ c++调用目标检测能否给个实例？
[c++预测](https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/advanced_guide/inference_deployment/inference/native_infer.html)

关键代码：
 // CreateConfig(&config);
  if (FLAGS_use_gpu) {
    config.EnableUseGpu(100, 0);
  }
  config.SetModel( "F:/Paddle/Paddle/paddle/fluid/inference/api/demo_ci/model_resnet/yolo_model",
                  "F:/Paddle/Paddle/paddle/fluid/inference/api/demo_ci/model_resnet/yolo_params");

  // use ZeroCopyTensor, Must be set to false
  config.SwitchUseFeedFetchOps(false);

  // 2. create predictor, prepare input data
  
  std::unique_ptr<PaddlePredictor> predictor;
  predictor = CreatePaddlePredictor(config);

windows上进行c++预测还有一些问题：
1 推理库加载mobilenet能出结果，但是每次分类score不一样，有没有像tensorflow那样可以设置seed？
2 InceptionV4和resnet模型，用python能出结果，推理库加载跑出来的结果都是nan，推理库只支持mobilenet模型？

windows上用paddle进行c++推理太难了，比我的人生还坎坷。

**Comment by OliverLPH** [comment]
@ZHOUKAI1 
目标检测C++部署可以参考下这个链接 [PaddleDetection C++预测部署方案](https://github.com/PaddlePaddle/PaddleDetection/blob/release/0.2/docs/advanced_tutorials/inference/DEPLOYMENT.md)

> 1 推理库加载mobilenet能出结果，但是每次分类score不一样，有没有像tensorflow那样可以设置seed？
这个预测结果取决于你给的输入，理论上输入一致输出就应该是一致的。

> 2 InceptionV4和resnet模型，用python能出结果，推理库加载跑出来的结果都是nan，推理库只支持mobilenet模型？
Python预测和C++预测库预测应该是一致的，需要检查下输入数据是否正确。

**Comment by ZHOUKAI1** [comment]
@OliverLPH  好吧，这个坑先填到这，试试另一个坑
