### ISSUE TITLE
关于自训练模型的上线部署

### ISSUE THREAD

**Issue by ClassmateXiaoyu** [PaddlePaddle/Paddle#23106]
- 版本、环境信息：
    1）PaddlePaddle版本：1.7.1
    2）CPU/GPU：CPU
    3）系统环境：Windows7 64位
    4）Python版本号：3.7.4
    5）显存信息：AMD Radeon HD 6520G ( 512 MB )

我通过paddle.fluid和自采集的经过预处理的自定义数据集训练了一个模型，需要通过什么方式可以实现这个模型的上线部署呢？我在GitHub的paddlepaddle首页看到有一个serving的模块，在paddlepaddle的管网www.paddlepaddle.org.cn上的api文档里有个Python预测部署，这两者有何区别？

**Comment by MRXLT** [comment]
你好，推荐使用Paddle Serving来实现线上模型部署，Paddle Serving是一个部署在线预测服务服务的框架，文档中的Python预测部署是指的实现本地预测的Python API。
关于Paddle Serving的使用可以参考https://github.com/PaddlePaddle/Serving

**Comment by ClassmateXiaoyu** [comment]
> 你好，推荐使用Paddle Serving来实现线上模型部署，Paddle Serving是一个部署在线预测服务服务的框架，文档中的Python预测部署是指的实现本地预测的Python API。
> 关于Paddle Serving的使用可以参考https://github.com/PaddlePaddle/Serving

你好，有无paddle serving的部署案例学习一下？

**Comment by MRXLT** [comment]
请参考这个示例https://github.com/PaddlePaddle/Serving#quick-start-example
PaddleServing代码库中也提供了多种模型的示例代码，https://github.com/PaddlePaddle/Serving/tree/develop/python/examples
