### ISSUE TITLE
前向计算正常，训练提示concat数据类型不匹配

### ISSUE THREAD

**Issue by zhengzhe97** [PaddlePaddle/Paddle#23105]
在测试完前向后，进行训练，训练时报错
![TIM图片20200319182248](https://user-images.githubusercontent.com/26462054/77057477-f9b9a100-6a0e-11ea-8666-058624be5060.png)

以下是相应部分的代码，报错部分代码参考retina_head
![TIM图片20200319182256](https://user-images.githubusercontent.com/26462054/77057539-135ae880-6a0f-11ea-825d-4cbe98b7910b.png)

**Comment by kuke** [comment]
设置 `priors.stop_gradient = True` 呢

**Comment by zhengzhe97** [comment]
这个错误没了，又出来个新的
![3DYF$57NUI6 (}P6(9`ROML](https://user-images.githubusercontent.com/26462054/77130565-68404280-6a93-11ea-8552-0db97d392abe.png)

代码部分是这样的
![0856@CAFTF79EE((EK { GY](https://user-images.githubusercontent.com/26462054/77130843-662ab380-6a94-11ea-8c57-1a0e84fb94f3.png)

**Comment by zhengzhe97** [comment]
![NZDTBZ0FX)DM)_@ESYM B)T](https://user-images.githubusercontent.com/26462054/77130948-c1f53c80-6a94-11ea-9b63-d498d251571a.png)
参考 #21999 添加.stop_gradient = True后正常，想知道是什么导致的
