### ISSUE TITLE
文档学习中的代码报错：operator < lookup_table > error

### ISSUE THREAD

**Issue by skywalk163** [PaddlePaddle/Paddle#23101]
环境： aistudio 高级版环境， paddlepaddle1.7 python3.7
出错代码位于：文档1.7-典型案例-自然语言处理-情感分析-构造训练器 代码部分：
https://www.paddlepaddle.org.cn/documentation/docs/zh/user_guides/nlp_case/understand_sentiment/README.cn.html
按文档手册顺序执行到构造训练器这里：
exe = fluid.Executor(place)
prediction = inference_program(word_dict)
[avg_cost, accuracy] = train_program(prediction)#训练程序
sgd_optimizer = optimizer_func()#训练优化函数
sgd_optimizer.minimize(avg_cost)

结果出现错误，报错信息是：
--------------------------------------------------------------------------EnforceNotMet Traceback (most recent call last) in
4
5 exe = fluid.Executor(place)
----> 6 prediction = inference_program(word_dict)
7 [avg_cost, accuracy] = train_program(prediction)#训练程序
8 sgd_optimizer = optimizer_func()#训练优化函数
in inference_program(word_dict)
5 name="words", shape=[None], dtype="int64", lod_level=1)
6 dict_dim = len(word_dict)
----> 7 net = convolution_net(data, dict_dim, CLASS_DIM, EMB_DIM, HID_DIM)
8 # net = stacked_lstm_net(data, dict_dim, CLASS_DIM, EMB_DIM, HID_DIM, STACKED_NUM)
9 return net
in convolution_net(data, input_dim, class_dim, emb_dim, hid_dim)
4 def convolution_net(data, input_dim, class_dim, emb_dim, hid_dim):
5 emb = fluid.layers.embedding(
----> 6 input=data, size=[input_dim, emb_dim], is_sparse=True)
7 conv_3 = fluid.nets.sequence_conv_pool(
8 input=emb,
中间省略部分。。。。。
Error Message Summary:
Error: ShapeError: The last dimensions of the 'Ids' tensor must be 1. But received Ids's last dimensions = -1, Ids's shape = [-1].
[Hint: Expected ids_dims[ids_rank - 1] == 1, but received ids_dims[ids_rank - 1]:-1 != 1:1.] at (/paddle/paddle/fluid/operators/lookup_table_op.cc:51)
[operator < lookup_table > error]

希望能得到解决，谢谢。
跟这个的报错一样，而且我的这个应该更好复现
https://github.com/PaddlePaddle/Paddle/issues/21221

**Comment by lfchener** [comment]
已经定位到问题，可以先将网络中的 fluid.layers.embedding 替换成 fluid.embedding 来运行。我们会尽快进行修复，感谢反馈。

**Comment by skywalk163** [comment]
非常感谢，我将fluid.layers.embedding 替换成 fluid.embedding后，原来报错的地方可以顺利运行了，但是在运行最后的预测代码的时候，报错。
代码：
with fluid.scope_guard(inference_scope):

    [inferencer, feed_target_names,
     fetch_targets] = fluid.io.load_inference_model(params_dirname, exe)

    assert feed_target_names[0] == "words"
    results = exe.run(inferencer,
                      feed={feed_target_names[0]: tensor_words},
                      fetch_list=fetch_targets,
                      return_numpy=False)
    np_data = np.array(results[0])
    for i, r in enumerate(np_data):
        print("Predict probability of ", r[0], " to be positive and ", r[1],
              " to be negative for review \'", reviews_str[i], "\'")

报错信息：
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/executor.py:782: UserWarning: The following exception is not an EOF exception.
  "The following exception is not an EOF exception.")
---------------------------------------------------------------------------ValueError                                Traceback (most recent call last)<ipython-input-37-299d0c80b074> in <module>
     12                      feed={feed_target_names[0]: tensor_words},
     13                      fetch_list=fetch_targets,
---> 14                      return_numpy=False)
     15    np_data = np.array(results[0])
     16    for i, r in enumerate(np_data):
中间省略
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/executor.py in check_feed_shape_type(var, feed, num_places)
    228                 'The feeded Variable %r should have dimensions = %d, shape = '
    229                 '%r, but received feeded shape %r on each device' %
--> 230                 (var.name, len(var.shape), var.shape, feed_shape))
    231         if not dtype_is_compatible_with(feed._dtype(), var.dtype):
    232             var_dtype_format = convert_dtype(var.dtype) if isinstance(
ValueError: The feeded Variable 'words' should have dimensions = 1, shape = (-1,), but received feeded shape [-1, 1] on each device

**Comment by lfchener** [comment]
你可以重启一下环境试试，我现在运行已经没有问题啦。

**Comment by skywalk163** [comment]
谢谢，在经过一系列操作后，程序终于在aistudio的py37 paddle1.7.1环境跑通。所做的操作包括但不限于：
1 因bug修复，将fluid.layers.embedding 重新加上layers.
2 将原文档训练和推理部分的数据矩阵结构从[None, 1]设置为[1]，同时将fluid.data修改为fluid.layers.data
def inference_program(word_dict):
    data = fluid.layers.data(
        name="words", shape=[1], dtype="int64", lod_level=1)
def train_program(prediction):
    label = fluid.layers.data(name="label", shape=[1], dtype="int64")
也就是我上面的报错“ValueError: The feeded Variable 'words' should have dimensions = 1, shape = (-1,), but received feeded shape [-1, 1] on each device” 可能就是因为数据矩阵结构设置不对造成的。

3 因为编码的问题，需要将导数第二段lod.append([word_dict.get(words, UNK) for words in c])
修改为lod.append([word_dict.get(bytes(words, encoding='utf-8'), UNK) for words in c]) ，否则所有单词会被识别为'<u n k>' ，就是未识别
