### ISSUE TITLE
MPI训练出错

### ISSUE THREAD

**Issue by minhozhou** [PaddlePaddle/Paddle#23110]
paddlecloud多机训练出错，之前成功训练一些step
![image](https://user-images.githubusercontent.com/46623470/77132854-e4d71f00-6a9b-11ea-81f5-65ea415b50c7.png)

![image](https://user-images.githubusercontent.com/46623470/77132820-bd805200-6a9b-11ea-984d-f7588c41cada.png)

同样的代码之前的任务训练成功过，同时同样的代码+同样的数据本地单机训练可以成功
![image](https://user-images.githubusercontent.com/46623470/77132885-0cc68280-6a9c-11ea-8530-1a2c20754a05.png)

0号节点日志地址：http://10.73.105.16:8910/fileview.html?type=logsdir&path=/&instance=0.app-user-20200320084100-68720--icf_a_a_3_2_202003200013_paddlecloud

**Comment by minhozhou** [comment]
补充一下版本信息：CPU、Paddle1.6.1、Python3.7，采用Fleet接口分布式训练

**Comment by seiriosPlus** [comment]
1. 采用的是同步训练还是异步训练
2. 是训练一开始就报错(一个minibatch的信息都没打印)，还是训练中途报错

**Comment by minhozhou** [comment]
> 1. 采用的是同步训练还是异步训练
> 2. 是训练一开始就报错(一个minibatch的信息都没打印)，还是训练中途报错

1. 同步训练
2. 20个minibatch后报错

**Comment by seiriosPlus** [comment]
1. 先换成异步训练看能否正常训练

**Comment by minhozhou** [comment]
好吧，上周这个错误遇到过三次左右，不是很能稳定复现，我先换异步观察，后续出错再更新

**Comment by seiriosPlus** [comment]
同步已知确实会容易出RPC ERROR， 这个目前在修复中， 也可以换新版本尝试一下。
