### ISSUE TITLE
trainer_factory.py 日志会默认创建RootLogger，影响用户正常log输出

### ISSUE THREAD

**Issue by ZHUI** [PaddlePaddle/Paddle#23125]
- 标题：trainer_factory.py 日志会默认创建RootLogger，影响用户正常log输出
- 版本、环境信息：
    1）PaddlePaddle版本：1.7 or 最新develop
    2）CPU/GPU：cpu
    3）系统环境：OS 10.13
    4）Python版本号 3.7

![image](https://user-images.githubusercontent.com/16911935/77219252-e6254c00-6b6e-11ea-95a4-6731c6e33d23.png)

https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/fluid/trainer_factory.py#L22

添加测试flag
```python
import logging
import numpy as np
print("TEST FLAG STRAT")
FORMAT = '%(asctime)s-%(levelname)s: %(message)s'
logging.basicConfig(level=logging.INFO, format=FORMAT)
print("TEST FLAG END")
local_logger = logging.getLogger(__name__)
```

测试结果
```
TEST FLAG STRAT
<RootLogger root (WARNING)>
<StreamHandler <stderr> (NOTSET)>
TEST FLAG END
```

创建了 RootLogger 之后，用户在程序中自定义的日志会被 RootLogger 再次输出在terminal界面输出一次，导致日志重复显示问题。
![image](https://user-images.githubusercontent.com/16911935/77219431-b70fda00-6b70-11ea-8e48-e837c63ef355.png)

**Comment by jshower** [comment]
我在paddle版本1.6.3上遇到同样的问题，用户日志输出的东西会在控制台同样打印一份。修复后辛苦告知一下。

**Comment by ZHUI** [comment]
> 我在paddle版本1.6.3上遇到同样的问题，用户日志输出的东西会在控制台同样打印一份。修复后辛苦告知一下。

我这边目前暂时的解决方案是，用户日志也使用 RootLogger 来打印日志，覆盖掉paddle新建的那个RootLogger。希望对你有帮助
```python
logging.basicConfig(level=logging.INFO, format=fmt)
self.logger =logging.getLogger()
```
