### ISSUE TITLE
使用Senta情感分析模型训练数据一直出错，教程里面的也无法运行

### ISSUE THREAD

**Issue by xiaolei00** [PaddlePaddle/Paddle#23129]

**Comment by wanghaoshuang** [comment]
请问教程链接是？

**Comment by faultXXXXL** [comment]
> 请问教程链接是？

https://aistudio.baidu.com/aistudio/projectdetail/215814

上面是链接。

**Comment by xiaolei00** [comment]
> 请问教程链接是？

https://aistudio.baidu.com/aistudio/projectdetail/216846

上面是链接

**Comment by Steffy-zxf** [comment]
@faultXXXXL 感谢反馈！Senta情感分类教程运行出错，是因为项目中的paddle版本太低了，不支持PaddleHub 1.6.0的功能。请修改你的senta项目中paddle版本为1.7.0。官方项目https://aistudio.baidu.com/aistudio/projectdetail/216846 已修改Paddle版本为1.7.0，并测试过项目可以正常运行。使用PaddleHub过程中有任何问题，欢迎到 PaddleHub repo下提issue https://github.com/PaddlePaddle/PaddleHub
