### ISSUE TITLE
nlp任务中同一个batch数据构成的tensor如何补全成相同维度的结果

### ISSUE THREAD

**Issue by narrowview** [PaddlePaddle/Paddle#23132]
我在用ernie做nlp任务时输入是不定长的，我想把输入的一个batch中的数据都补全成相同维度的结果。
例如：
batch_size是8
输入文本长度是 20
单字的语义向量是768
这个batch得到的原始语义tensor是 8 * 20 * 768维的
我想把这个tensor补全成  8 * 128 *  768 维的，补全部分用5填充
请问这个要怎么做？

**Comment by wanghaoshuang** [comment]
请参考：https://www.paddlepaddle.org.cn/documentation/docs/zh/api_cn/layers_cn/sequence_pad_cn.html#cn-api-fluid-layers-sequence-pad
