### ISSUE TITLE
C++ Call Stacks (More useful to developers):

### ISSUE THREAD

**Issue by ghost** [PaddlePaddle/Paddle#23136]
https://aistudio.baidu.com/aistudio/projectdetail/333086
--------------------------------------------
C++ Call Stacks (More useful to developers):
--------------------------------------------
0   std::string paddle::platform::GetTraceBackString<std::string const&>(std::string const&, char const*, int)
1   paddle::platform::EnforceNotMet::EnforceNotMet(std::string const&, char const*, int)
2   paddle::AnalysisPredictor::SetFeed(std::vector<paddle::PaddleTensor, std::allocator<paddle::PaddleTensor> > const&, paddle::framework::Scope*)
3   paddle::AnalysisPredictor::Run(std::vector<paddle::PaddleTensor, std::allocator<paddle::PaddleTensor> > const&, std::vector<paddle::PaddleTensor, std::allocator<paddle::PaddleTensor> >*, int)

----------------------
Error Message Summary:
----------------------
Error: An error occurred here. There is no accurate error hint for this error yet. We are continuously in the process of increasing hint for this kind of error check. It would be helpful if you could inform us of how this conversion went by opening a github issue. And we will resolve it with high priority.
  - New issue link: https://github.com/PaddlePaddle/Paddle/issues/new
  - Recommended issue content: all error stack information
  [Hint: inputs[i].data.data() should not be null.] at (/paddle/paddle/fluid/inference/api/analysis_predictor.cc:292)

**Comment by Steffy-zxf** [comment]
你好！经过调试，发现你的清理过后的数据text字段有为空的情况，请清除了这些数据再重新运行情感分类任务。
![image](https://user-images.githubusercontent.com/48793257/77717581-cdf47780-701b-11ea-9c2d-087cb1f9511b.png)

同时，如果你想要在情感分类任务上训练一个性能较好的模型，建议使用ernie 完成fine-tune， 参考demo https://github.com/PaddlePaddle/PaddleHub/tree/release/v1.6/demo/text_classification
PaddleHub使用过程中有任何问题，欢迎在PaddleHub repo下提issue，https://github.com/PaddlePaddle/PaddleHub/issues
