### ISSUE TITLE
Ring-Allreduce 同步细节问题

### ISSUE THREAD

**Issue by Mrhs121** [PaddlePaddle/Paddle#23149]
在深度学习训练过程中，计算梯度采用BP算法，其特点是后面层的梯度先被计算，而前面层的梯度慢于前面层，Paddle中的梯度同步是逐层同步还是全部backward之后再整体同步呢？

**Comment by seiriosPlus** [comment]
目前飞桨的梯度同步是逐层同步。

**Comment by Mrhs121** [comment]
非常感谢回答！还有一个问题就是，你们有实现Wait-free Backpropagation这个算法吗，[Poseidon: An Efficient Communication Architecture for Distributed Deep Learning on GPU Clusters]
