### ISSUE TITLE
官网预编译的windows预测库没有导出符号？

### ISSUE THREAD

**Issue by cvfzhong** [PaddlePaddle/Paddle#23143]
https://www.paddlepaddle.org.cn/documentation/docs/zh/advanced_guide/inference_deployment/inference/windows_cpp_inference.html

这里提供的动态链接库，paddle_fluid.lib文件只有2K，dumbin查看.dll也没有导出任何符号，用动态库会报找不到符号的链接错误
看了下源码并没有声明dllexport，linux下默认是全部导出的，vc下编译不声明不行吧？

**Comment by seiriosPlus** [comment]
@zhouwei25

**Comment by zhwesky2010** [comment]
@cvfzhong 您好，现在动态库导出预测库符号还有些问题，`libpaddlefluid.lib`是静态库，可以使用的。paddle_fluid.dll与paddle_fluid.lib是动态库及其对应静态导入库，paddle_fluid.dll如果导出正常大概是400余兆，目前这个库还在测试中，暂且还无法使用。Windows预测部署时请链接静态库`libpaddlefluid.lib`哈~
Linux下动态库可以使用

**Comment by zhwesky2010** [comment]
@cvfzhong 请问下还有没有其他问题，如果没有的话可以关闭issue了哈
