### ISSUE TITLE
C++推理paddleseg模型时，batchsize为2以上时结果图相同

### ISSUE THREAD

**Issue by cyanjustice** [PaddlePaddle/Paddle#23144]
C++推理input图片转换代码：
![image](https://user-images.githubusercontent.com/46018705/77273747-49d68300-6cef-11ea-8ab6-3f6dbd092175.png)
C++推理output图片转换代码：
![image](https://user-images.githubusercontent.com/46018705/77273828-77bbc780-6cef-11ea-9936-67a1494cc57f.png)
batchsize为1时结果正常，2以上时，每个batch输出的结果图片相同

**Comment by Superjomn** [comment]
可以给个可复现，业务无关的单测我们查以下。 内部用户可以走服务群
