### ISSUE TITLE
ValueError: Data Type mismatch: 5 to 3

### ISSUE THREAD

**Issue by 45659301** [PaddlePaddle/Paddle#23168]
paddle报错：
ValueError: Data Type mismatch: 5 to 3

报错行代码：
concated = fluid.layers.concat(self.data_use_var, axis=1)

求解答～

**Comment by seiriosPlus** [comment]
concat的输入一个是float32 ,另外一个是 int64， 不能concat。

**Comment by phlrain** [comment]
请问下 使用的paddle版本是什么， data type mismatch : 5 to 3的问题， 我们在新版本中已经修复了

**Comment by Channingss** [comment]
@phlrain 请问哪个版本已修复，我这边遇到
![image](https://user-images.githubusercontent.com/12471701/79406545-f8f23b80-7fc9-11ea-92ea-1efc5db82ace.png)
