### ISSUE TITLE
使用Python API的时候出现问题

### ISSUE THREAD

**Issue by 606BlueStar** [PaddlePaddle/Paddle#23188]
使用Python API对导出模型保存的inference_model进行预测时报错；
模型为yolov3_mobilenet,成功导出模型，但是使用的时候报如下错误：
----------------------
Error Message Summary:
----------------------
Error: An error occurred here. There is no accurate error hint for this error yet. We are continuously in the process of increasing hint for this kind of error check. It would be helpful if you could inform us of how this conversion went by opening a github issue. And we will resolve it with high priority.
  - New issue link: https://github.com/PaddlePaddle/Paddle/issues/new
  - Recommended issue content: all error stack information
  [Hint: CUDNN_STATUS_BAD_PARAM] at (/paddle/paddle/fluid/operators/batch_norm_op.cu:166)
  [operator < batch_norm > error]

注：
已经尝试了不同的bn模式，bn和sync_bn;
cuda版本为10.1，paddle版本1.7.2；
不用导出模型进行infer的时候也报相同的错误！！！

**Comment by ceci3** [comment]
[Hint: CUDNN_STATUS_BAD_PARAM]  你好，这个报错一般是cudnn版本问题，建议升级cudnn到7.6

**Comment by 606BlueStar** [comment]
我装的就是7.6，查看版本也是7.6，从来没装过7.3






------------------&nbsp;原始邮件&nbsp;------------------
发件人: "ceci3"<notifications@github.com&gt;; 
发送时间: 2020年3月24日(星期二) 晚上6:21
收件人: "PaddlePaddle/Paddle"<Paddle@noreply.github.com&gt;; 
抄送: "开始"<1781843589@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [PaddlePaddle/Paddle] 使用Python API的时候出现问题 (#23188)





 
[Hint: CUDNN_STATUS_BAD_PARAM]  你好，这个报错一般是cudnn版本问题，建议升级cudnn到7.6
