### ISSUE TITLE
检测安装是否成功，报core

### ISSUE THREAD

**Issue by zh215021** [PaddlePaddle/Paddle#23186]
![image](https://user-images.githubusercontent.com/40022359/77393229-8f6e7b00-6dd7-11ea-909b-b44ac72954bd.png)
相同脚本之前可以正常运行，环境变量没有改变，所有conda环境下的paddle都会报core，检测安装是否成功也会报core。

**Comment by JepsonWong** [comment]
麻烦按照issue规范贴上环境变量设置。

paddle是CPU版本还是GPU版本？
如果是GPU版本，麻烦设置一下CUDA_VISIBLE_DEVICES环境变量为0，单卡check下有没有问题。
