### ISSUE TITLE
PyReader偶发性读不到数据

### ISSUE THREAD

**Issue by zhudatu** [PaddlePaddle/Paddle#23184]
paddle版本1.5.2
数据读取采用
self.py_reader = fluid.io.PyReader(
feed_list=self.feature_input + [self.label_input],
capacity=8,
iterable=True)
训练数据量为2，bs=2（2卡），训练时采用for data in train_pyreader()，有时候会出现读不到数据的情况，即train_pyreader()返回为空。偶发性出现。

**Comment by zhudatu** [comment]
数据读取采用
self.py_reader = fluid.io.PyReader(
          feed_list=self.feature_input + [self.label_input],
          capacity=8,
          iterable=True)
训练数据量为2，bs=2（2卡），训练时采用for data in train_pyreader()，有时候会出现读不到数据的情况，即train_pyreader()返回为空。偶发性出现。

**Comment by sneaxiy** [comment]
@zhudatu 能否升级到最新版本1.7试试？可能1.5有个bug，我们已经修复了。

**Comment by zhudatu** [comment]
> @zhudatu 能否升级到最新版本1.7试试？可能1.5有个bug，我们已经修复了。

@sneaxiy 暂时只能用1.5诶。这种情况，每张卡最小多少数据量不容易出现这个bug？

**Comment by sneaxiy** [comment]
> 暂时只能用1.5诶。这种情况，每张卡最小多少数据量不容易出现这个bug？

@zhudatu 这个很难评估，这个不是确定的值，建议还是升级paddle版本吧。
