### ISSUE TITLE
急求帮助！！！！！机器cudnn版本是7.6.5，但是paddle提示是7.3

### ISSUE THREAD

**Issue by 606BlueStar** [PaddlePaddle/Paddle#23194]
**ARNING: device: 0. The installed Paddle is compiled with CUDNN 7.6, but CUDNN version in your machine is 7.3, which may cause serious incompatible bug. Please recompile or reinstall Paddle with compatible CUDNN version.**

查看机器的cudnn版本是7.6。5：
(paddle) senseport@senseport-Z390-UD:~/Senseport/pp$ cat /usr/local/cuda/include/cudnn.h | grep CUDNN_MAJOR -A 2
#define CUDNN_MAJOR 7
#define CUDNN_MINOR 6
#define CUDNN_PATCHLEVEL 5
--
#define CUDNN_VERSION (CUDNN_MAJOR * 1000 + CUDNN_MINOR * 100 + CUDNN_PATCHLEVEL)

#include "driver_types.h"

**Comment by JepsonWong** [comment]
请提供下CUDA_HOME、PATH、LD_LIBRARY_PATH环境变量

**Comment by 606BlueStar** [comment]
# ~/.bashrc: executed by bash(1) for non-login shells.
# see /usr/share/doc/bash/examples/startup-files (in the package bash-doc)
# for examples

# If not running interactively, don't do anything
case $- in
    *i*) ;;
      *) return;;
esac

# don't put duplicate lines or lines starting with space in the history.
# See bash(1) for more options
HISTCONTROL=ignoreboth

# append to the history file, don't overwrite it
shopt -s histappend

# for setting history length see HISTSIZE and HISTFILESIZE in bash(1)
HISTSIZE=1000
HISTFILESIZE=2000

# check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize

# If set, the pattern "**" used in a pathname expansion context will
# match all files and zero or more directories and subdirectories.
#shopt -s globstar

# make less more friendly for non-text input files, see lesspipe(1)
[ -x /usr/bin/lesspipe ] && eval "$(SHELL=/bin/sh lesspipe)"

# set variable identifying the chroot you work in (used in the prompt below)
if [ -z "${debian_chroot:-}" ] && [ -r /etc/debian_chroot ]; then
    debian_chroot=$(cat /etc/debian_chroot)
fi

# set a fancy prompt (non-color, unless we know we "want" color)
case "$TERM" in
    xterm-color|*-256color) color_prompt=yes;;
esac

# uncomment for a colored prompt, if the terminal has the capability; turned
# off by default to not distract the user: the focus in a terminal window
# should be on the output of commands, not on the prompt
#force_color_prompt=yes

if [ -n "$force_color_prompt" ]; then
    if [ -x /usr/bin/tput ] && tput setaf 1 >&/dev/null; then
        # We have color support; assume it's compliant with Ecma-48
        # (ISO/IEC-6429). (Lack of such support is extremely rare, and such
        # a case would tend to support setf rather than setaf.)
        color_prompt=yes
    else
        color_prompt=
    fi
fi

if [ "$color_prompt" = yes ]; then
    PS1='${debian_chroot:+($debian_chroot)}\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\$ '
else
    PS1='${debian_chroot:+($debian_chroot)}\u@\h:\w\$ '
fi
unset color_prompt force_color_prompt

# If this is an xterm set the title to user@host:dir
case "$TERM" in
xterm*|rxvt*)
                                                                                                                                                                                                                1,1           Top
xterm*|rxvt*)
    PS1="\[\e]0;${debian_chroot:+($debian_chroot)}\u@\h: \w\a\]$PS1"
    ;;
*)
    ;;
esac

# enable color support of ls and also add handy aliases
if [ -x /usr/bin/dircolors ]; then
    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
    alias ls='ls --color=auto'
    #alias dir='dir --color=auto'
    #alias vdir='vdir --color=auto'

    alias grep='grep --color=auto'
    alias fgrep='fgrep --color=auto'
    alias egrep='egrep --color=auto'
fi

# colored GCC warnings and errors
#export GCC_COLORS='error=01;31:warning=01;35:note=01;36:caret=01;32:locus=01:quote=01'

# some more ls aliases
alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'

# Add an "alert" alias for long running commands.  Use like so:
#   sleep 10; alert
alias alert='notify-send --urgency=low -i "$([ $? = 0 ] && echo terminal || echo error)" "$(history|tail -n1|sed -e '\''s/^\s*[0-9]\+\s*//;s/[;&|]\s*alert$//'\'')"'

# Alias definitions.
# You may want to put all your additions into a separate file like
# ~/.bash_aliases, instead of adding them here directly.
# See /usr/share/doc/bash-doc/examples in the bash-doc package.

if [ -f ~/.bash_aliases ]; then
    . ~/.bash_aliases
fi

# enable programmable completion features (you don't need to enable
# this, if it's already enabled in /etc/bash.bashrc and /etc/profile
# sources /etc/bash.bashrc).
if ! shopt -oq posix; then
  if [ -f /usr/share/bash-completion/bash_completion ]; then
    . /usr/share/bash-completion/bash_completion
  elif [ -f /etc/bash_completion ]; then
    . /etc/bash_completion
  fi
fi
# added by Anaconda3 5.3.1 installer
# >>> conda init >>>
# !! Contents within this block are managed by 'conda init' !!
__conda_setup="$(CONDA_REPORT_ERRORS=false '/home/senseport/anaconda3/bin/conda' shell.bash hook 2> /dev/null)"
if [ $? -eq 0 ]; then
    \eval "$__conda_setup"
else
    if [ -f "/home/senseport/anaconda3/etc/profile.d/conda.sh" ]; then
        . "/home/senseport/anaconda3/etc/profile.d/conda.sh"
        CONDA_CHANGEPS1=false conda activate base
    else
        \export PATH="/home/senseport/anaconda3/bin:$PATH"
    fi
fi
unset __conda_setup
# <<< conda init <<<
                                                                                                                                                                                                                133,1         Bot

**Comment by 606BlueStar** [comment]
格式有点乱。

**Comment by JepsonWong** [comment]
> 格式有点乱。

麻烦调整下格式吧，或者直接类似 echo $PATH 拿到输出结果就好。
你贴的看不太清晰。

**Comment by 606BlueStar** [comment]
(paddle) senseport@senseport-Z390-UD:~/Senseport/pp$ echo $PATH 
/home/senseport/anaconda3/envs/paddle/bin:/home/senseport/.vscode-server/bin/fe22a9645b44368865c0ba92e2fb881ff1afce94/bin:/home/senseport/.local/bin:/home/senseport/anaconda3/bin:/home/senseport/.vscode-server/bin/fe22a9645b44368865c0ba92e2fb881ff1afce94/bin:/home/senseport/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin

**Comment by JepsonWong** [comment]
> (paddle) senseport@senseport-Z390-UD:~/Senseport/pp$ echo $PATH
> /home/senseport/anaconda3/envs/paddle/bin:/home/senseport/.vscode-server/bin/fe22a9645b44368865c0ba92e2fb881ff1afce94/bin:/home/senseport/.local/bin:/home/senseport/anaconda3/bin:/home/senseport/.vscode-server/bin/fe22a9645b44368865c0ba92e2fb881ff1afce94/bin:/home/senseport/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin

麻烦上面说的环境变量都贴下。

**Comment by 606BlueStar** [comment]
(paddle) senseport@senseport-Z390-UD:~/Senseport/pp$ echo $CUDA_HOME

(paddle) senseport@senseport-Z390-UD:~/Senseport/pp$ echo CUDA_HOME
CUDA_HOME

这个没有输出

**Comment by 606BlueStar** [comment]
(paddle) senseport@senseport-Z390-UD:~/Senseport/pp$ echo $LD_LIBRARY_PATH

(paddle) senseport@senseport-Z390-UD:~/Senseport/pp$ echo LD_LIBRARY_PATH
LD_LIBRARY_PATH

这个也没有。。

**Comment by JepsonWong** [comment]
> (paddle) senseport@senseport-Z390-UD:~/Senseport/pp$ echo $CUDA_HOME
> 
> (paddle) senseport@senseport-Z390-UD:~/Senseport/pp$ echo CUDA_HOME
> CUDA_HOME
> 
> 这个没有输出

LD_LIBRARY_PATH呢？所以您那边cuda环境是怎么设置的？或者是conda自动下载的cuda环境，那就是conda的cuda环境是7.3，您并没有用本机的cuda环境。

**Comment by 606BlueStar** [comment]
已经解决了，谢谢！

**Comment by omtbreak** [comment]
我也出现这个问题，请问您怎么解决的

**Comment by JepsonWong** [comment]
> 我也出现这个问题，请问您怎么解决的

这个其实就是需要重新设置一下cuda环境。
