### ISSUE TITLE
paddle 1.7.1在python3环境下运行fleet-pserver稳定出现报错

### ISSUE THREAD

**Issue by yxfGrace** [PaddlePaddle/Paddle#23201]
paddle 1.7.1  python3安装
运行ctr demo https://github.com/PaddlePaddle/Fleet/tree/develop/examples/ctr
fleet， pserver，cpu环境
出现报错
![image](https://user-images.githubusercontent.com/29363426/77430124-a469ff00-6e15-11ea-9158-9ca8ca4ce781.png)

python2可以正常跑通

**Comment by MrChengmo** [comment]
感谢提出bug，正在跟进py3下存在的问题。如无影响使用，可以暂时先使用py2的版本，Dataset的IO方式目前在py3及win下存在兼容性问题，正在开发中。

关于CTR的详细教程与使用示例可以看这个：https://github.com/PaddlePaddle/models/tree/develop/PaddleRec/ctr/dnn
