### ISSUE TITLE
用ai studio finetune ERNIE时报错AttributeError: 'NoneType' object has no attribute 'split'

### ISSUE THREAD

**Issue by boblee123** [PaddlePaddle/Paddle#23208]
- 版本、环境信息：
在AI STUDIO里运行,
硬件信息
当前环境高级版
CPU
8
RAM
32GB
GPU
v100
显存
16GB
磁盘
100GB
环境配置
Python版本
python3.7
框架版本
PaddlePaddle 1.7.0
- 训练信息

- 复现信息：运行了2次都报同样错误

- 问题描述：请详细描述您的问题，同步贴出报错信息、日志、可复现的代码片段
[INFO] 2020-03-25 10:42:24,756 [run_classifier.py:  401]:	[dev evaluation] ave loss: 0.002844, acc:0.999377, data_num: 17651, elapsed time: 292.497571 s, file: data26313/test.tsv, epoch: 0, steps: 100
Traceback (most recent call last):
  File "./ernie/run_classifier.py", line 447, in <module>
    main(args)
  File "./ernie/run_classifier.py", line 315, in main
    current_epoch, steps)
  File "./ernie/run_classifier.py", line 406, in predict_wrapper
    test_sets = args.test_set.split(',')
AttributeError: 'NoneType' object has no attribute 'split'
terminate called without an active exception
W0325 10:42:25.580196   237 init.cc:209] Warning: PaddlePaddle catches a failure signal, it may not work properly
W0325 10:42:25.580232   237 init.cc:211] You could check whether you killed PaddlePaddle thread/process accidentally or report the case to PaddlePaddle
W0325 10:42:25.580247   237 init.cc:214] The detail failure signal is:

W0325 10:42:25.580253   237 init.cc:217] *** Aborted at 1585104145 (unix time) try "date -d @1585104145" if you are using GNU date ***
W0325 10:42:25.581771   237 init.cc:217] PC: @                0x0 (unknown)
W0325 10:42:25.581877   237 init.cc:217] *** SIGABRT (@0x3e8000000b2) received by PID 178 (TID 0x7f93fe5b5700) from PID 178; stack trace: ***
W0325 10:42:25.582898   237 init.cc:217]     @     0x7f9411f17390 (unknown)
W0325 10:42:25.583844   237 init.cc:217]     @     0x7f9411b71428 gsignal
W0325 10:42:25.584776   237 init.cc:217]     @     0x7f9411b7302a abort
W0325 10:42:25.585433   237 init.cc:217]     @     0x7f93d2a9c84a __gnu_cxx::__verbose_terminate_handler()
W0325 10:42:25.585981   237 init.cc:217]     @     0x7f93d2a9af47 __cxxabiv1::__terminate()
W0325 10:42:25.586578   237 init.cc:217]     @     0x7f93d2a9af7d std::terminate()
W0325 10:42:25.587123   237 init.cc:217]     @     0x7f93d2a9ac5a __gxx_personality_v0
W0325 10:42:25.587615   237 init.cc:217]     @     0x7f93d2d8db97 _Unwind_ForcedUnwind_Phase2
W0325 10:42:25.588107   237 init.cc:217]     @     0x7f93d2d8de7d _Unwind_ForcedUnwind
W0325 10:42:25.589069   237 init.cc:217]     @     0x7f9411f16070 __GI___pthread_unwind
W0325 10:42:25.590018   237 init.cc:217]     @     0x7f9411f0e845 __pthread_exit
W0325 10:42:25.590277   237 init.cc:217]     @     0x564a9ea02e59 PyThread_exit_thread
W0325 10:42:25.590359   237 init.cc:217]     @     0x564a9e888c17 PyEval_RestoreThread.cold.798
W0325 10:42:25.591241   237 init.cc:217]     @     0x7f93ac2c7779 pybind11::gil_scoped_release::~gil_scoped_release()
W0325 10:42:25.591437   237 init.cc:217]     @     0x7f93ac274134 _ZZN8pybind1112cpp_function10initializeIZN6paddle6pybindL22pybind11_init_core_avxERNS_6moduleEEUlRNS2_9operators6reader22LoDTensorBlockingQueueERKSt6vectorINS2_9framework9LoDTensorESaISC_EEE60_bIS9_SG_EINS_4nameENS_9is_methodENS_7siblingEEEEvOT_PFT0_DpT1_EDpRKT2_ENUlRNS_6detail13function_callEE1_4_FUNESY_
W0325 10:42:25.592214   237 init.cc:217]     @     0x7f93ac2e5b21 pybind11::cpp_function::dispatcher()
W0325 10:42:25.592500   237 init.cc:217]     @     0x564a9e984744 _PyMethodDef_RawFastCallKeywords
W0325 10:42:25.592733   237 init.cc:217]     @     0x564a9e984861 _PyCFunction_FastCallKeywords
W0325 10:42:25.592974   237 init.cc:217]     @     0x564a9e9f06e8 _PyEval_EvalFrameDefault
W0325 10:42:25.593189   237 init.cc:217]     @     0x564a9e93481a _PyEval_EvalCodeWithName
W0325 10:42:25.593401   237 init.cc:217]     @     0x564a9e935635 _PyFunction_FastCallDict
W0325 10:42:25.593626   237 init.cc:217]     @     0x564a9e9ed232 _PyEval_EvalFrameDefault
W0325 10:42:25.593837   237 init.cc:217]     @     0x564a9e983ccb _PyFunction_FastCallKeywords
W0325 10:42:25.594070   237 init.cc:217]     @     0x564a9e9eba93 _PyEval_EvalFrameDefault
W0325 10:42:25.594267   237 init.cc:217]     @     0x564a9e983ccb _PyFunction_FastCallKeywords
W0325 10:42:25.594491   237 init.cc:217]     @     0x564a9e9eba93 _PyEval_EvalFrameDefault
W0325 10:42:25.594710   237 init.cc:217]     @     0x564a9e93556b _PyFunction_FastCallDict
W0325 10:42:25.594916   237 init.cc:217]     @     0x564a9e953e53 _PyObject_Call_Prepend
W0325 10:42:25.595155   237 init.cc:217]     @     0x564a9e946dbe PyObject_Call
W0325 10:42:25.595250   237 init.cc:217]     @     0x564a9ea43817 t_bootstrap
W0325 10:42:25.595304   237 init.cc:217]     @     0x564a9e9fe788 pythread_wrapper
W0325 10:42:25.596374   237 init.cc:217]     @     0x7f9411f0d6ba start_thread
Aborted (core dumped)

**Comment by sneaxiy** [comment]
> Traceback (most recent call last):
> File "./ernie/run_classifier.py", line 447, in
> main(args)
> File "./ernie/run_classifier.py", line 315, in main
> current_epoch, steps)
> File "./ernie/run_classifier.py", line 406, in predict_wrapper
> test_sets = args.test_set.split(',')
> AttributeError: 'NoneType' object has no attribute 'split'

您这个应该是因为args.test_set为None，建议检查下代码。
