### ISSUE TITLE
Paddle中paddle.fluid.layers.batch_norm和Pytorch中nn.BatchNorm1d是否对齐？

### ISSUE THREAD

**Issue by aprilvkuo** [PaddlePaddle/Paddle#23216]
只进行infer不训练， 前向传播效果有diff

```python
# 保留了pytorch中的bn参数
self.bn = nn.BatchNorm1d(hidden_size*2)
bn_weight = self.bn.weight.detach().numpy()
bn_bias = self.bn.bias.detach().numpy()
```

省略了numpy保存和加载过程

```python
# paddle中加载bn参数

out = fluid.layers.batch_norm(out, param_attr=para_dict["bn_weight"],bias_attr=para_dict["bn_bias"], is_test=True, do_model_average_for_mean_and_var=True)
   
```

**Comment by aprilvkuo** [comment]
pytorch中， 模型设置了eval()
将模型设置成evaluation模式

**Comment by ceci3** [comment]
你好，`do_model_average_for_mean_and_var`这个参数为什么要设置为True？pytorch中也有对mean和var做模型均值吗？

**Comment by aprilvkuo** [comment]
> 你好，`do_model_average_for_mean_and_var`这个参数为什么要设置为True？pytorch中也有对mean和var做模型均值吗？
没有设置，我只是参数设置遍历一遍。 我把true和false都试了一次，效果都有diff。

**Comment by aprilvkuo** [comment]
> 你好，`do_model_average_for_mean_and_var`这个参数为什么要设置为True？pytorch中也有对mean和var做模型均值吗？

pytorch中还有两个参数， 不知道对效果是否有影响。

 bn_running_mean = self.bn.running_mean.detach().numpy()
 bn_running_var = self.bn.running_var.detach().numpy()

**Comment by ceci3** [comment]
bn_running_mean  bn_running_var这两个代表全局均值和方差，你infer的时候应该是要用全局还是当前batch的均值方差？

**Comment by ceci3** [comment]
在pytorch上用eval()应该是用的全局的均值和方差，但是在paddle的
`out = fluid.layers.batch_norm(out, param_attr=para_dict["bn_weight"],bias_attr=para_dict["bn_bias"], is_test=True, do_model_average_for_mean_and_var=True)`
这种用法里并没有传入全局均值方差，可能是这个原因导致的diff

**Comment by aprilvkuo** [comment]
> 在pytorch上用eval()应该是用的全局的均值和方差，但是在paddle的
> `out = fluid.layers.batch_norm(out, param_attr=para_dict["bn_weight"],bias_attr=para_dict["bn_bias"], is_test=True, do_model_average_for_mean_and_var=True)`
> 这种用法里并没有传入全局均值方差，可能是这个原因导致的diff


麻烦问一下，paddle有办法传入这两个参数吗

**Comment by ceci3** [comment]
可以通过这种方法传入fluid.global_scope().find_var(name_of_mean/var).get_tensor().set(mean/var_data)

**Comment by aprilvkuo** [comment]
> 可以通过这种方法传入fluid.global_scope().find_var(name_of_mean/var).get_tensor().set(mean/var_data)

请问这么设置对吗， 运行有报错
```python
 exe = fluid.Executor(place)
    pro = fluid.default_main_program()
   
    exe.run(fluid.default_startup_program())
    print(np_dict["bn_running_var"])
    print(np_dict["bn_running_mean"])
    fluid.global_scope().find_var("batch_norm_0.w_2").get_tensor().set(np_dict["bn_running_var"]) # var
    fluid.global_scope().find_var("batch_norm_0.w_1").get_tensor().set(np_dict["bn_running_mean"])#mean
  
```



```shell
File "lstm_unit.py", line 178, in main
    fluid.global_scope().find_var("batch_norm_0.w_2").get_tensor().set(np_dict["bn_running_
var"]) # var
TypeError: set(): incompatible function arguments. The following argument types are support
ed:
    1. (self: paddle.fluid.core_avx.Tensor, array: numpy.ndarray[float32], place: paddle::p
latform::CPUPlace) -> None
    2. (self: paddle.fluid.core_avx.Tensor, array: numpy.ndarray[int32], place: paddle::pla
tform::CPUPlace) -> None
    3. (self: paddle.fluid.core_avx.Tensor, array: numpy.ndarray[float64], place: paddle::p
latform::CPUPlace) -> None
    4. (self: paddle.fluid.core_avx.Tensor, array: numpy.ndarray[int64], place: paddle::pla
tform::CPUPlace) -> None
    5. (self: paddle.fluid.core_avx.Tensor, array: numpy.ndarray[bool], place: paddle::plat
form::CPUPlace) -> None
    6. (self: paddle.fluid.core_avx.Tensor, array: numpy.ndarray[uint16], place: paddle::pl
atform::CPUPlace) -> None
    7. (self: paddle.fluid.core_avx.Tensor, array: numpy.ndarray[uint8], place: paddle::platform::CPUPlace) -> None
    8. (self: paddle.fluid.core_avx.Tensor, array: numpy.ndarray[int8], place: paddle::plat
form::CPUPlace) -> None
```

**Comment by aprilvkuo** [comment]
op对应情况
```shell
  inputs {
    parameter: "Bias"
    arguments: "batch_norm_0.b_0"
  }
  inputs {
    parameter: "Mean"
    arguments: "batch_norm_0.w_1"
  }
  inputs {
    parameter: "Scale"
    arguments: "batch_norm_0.w_0"
  }
  inputs {
    parameter: "Variance"
    arguments: "batch_norm_0.w_2"
  }
  inputs {
    parameter: "X"
    arguments: "reduce_mean_0.tmp_0"
  }
```

**Comment by ceci3** [comment]
> > 可以通过这种方法传入fluid.global_scope().find_var(name_of_mean/var).get_tensor().set(mean/var_data)
> 
> 请问这么设置对吗， 运行有报错
> 
> ```python
>  exe = fluid.Executor(place)
>     pro = fluid.default_main_program()
>    
>     exe.run(fluid.default_startup_program())
>     print(np_dict["bn_running_var"])
>     print(np_dict["bn_running_mean"])
>     fluid.global_scope().find_var("batch_norm_0.w_2").get_tensor().set(np_dict["bn_running_var"]) # var
>     fluid.global_scope().find_var("batch_norm_0.w_1").get_tensor().set(np_dict["bn_running_mean"])#mean
>   
> ```
> 
> ```shell
> File "lstm_unit.py", line 178, in main
>     fluid.global_scope().find_var("batch_norm_0.w_2").get_tensor().set(np_dict["bn_running_
> var"]) # var
> TypeError: set(): incompatible function arguments. The following argument types are support
> ed:
>     1. (self: paddle.fluid.core_avx.Tensor, array: numpy.ndarray[float32], place: paddle::p
> latform::CPUPlace) -> None
>     2. (self: paddle.fluid.core_avx.Tensor, array: numpy.ndarray[int32], place: paddle::pla
> tform::CPUPlace) -> None
>     3. (self: paddle.fluid.core_avx.Tensor, array: numpy.ndarray[float64], place: paddle::p
> latform::CPUPlace) -> None
>     4. (self: paddle.fluid.core_avx.Tensor, array: numpy.ndarray[int64], place: paddle::pla
> tform::CPUPlace) -> None
>     5. (self: paddle.fluid.core_avx.Tensor, array: numpy.ndarray[bool], place: paddle::plat
> form::CPUPlace) -> None
>     6. (self: paddle.fluid.core_avx.Tensor, array: numpy.ndarray[uint16], place: paddle::pl
> atform::CPUPlace) -> None
>     7. (self: paddle.fluid.core_avx.Tensor, array: numpy.ndarray[uint8], place: paddle::platform::CPUPlace) -> None
>     8. (self: paddle.fluid.core_avx.Tensor, array: numpy.ndarray[int8], place: paddle::plat
> form::CPUPlace) -> None
> ```

抱歉 刚才少了一个参数，set的时候需要传入place
`fluid.global_scope().find_var(name_of_mean/var).get_tensor().set(mean/var_data, place)`

**Comment by aprilvkuo** [comment]
好的谢谢你哈， 效果已经一致了
