### ISSUE TITLE
注意力机制API添加mask参数

### ISSUE THREAD

**Issue by MiloHang** [PaddlePaddle/Paddle#23219]
[scaled_dot_product_attention](https://www.paddlepaddle.org.cn/documentation/docs/zh/api_cn/nets_cn/scaled_dot_product_attention_cn.html#scaled-dot-product-attention) api 添加mask矩阵以防止padding对Attention网络参数造成的影响
如：
> paddle.fluid.nets.scaled_dot_product_attention(queries, keys, values, num_heads=1, mask=None, dropout_rate=0.0)

**Comment by MiloHang** [comment]
> [scaled_dot_product_attention](https://www.paddlepaddle.org.cn/documentation/docs/zh/api_cn/nets_cn/scaled_dot_product_attention_cn.html#scaled-dot-product-attention) api 添加mask矩阵以防止padding对Attention网络参数造成的影响
> 如：
> 
> > paddle.fluid.nets.scaled_dot_product_attention(queries, keys, values, num_heads=1, mask=None, dropout_rate=0.0)

**Comment by sneaxiy** [comment]
感谢您的反馈，我们会对此需求进行记录和评估。
