### ISSUE TITLE
编写op，blas-gpu使用问题

### ISSUE THREAD

**Issue by littletomatodonkey** [PaddlePaddle/Paddle#23223]
我参考mul_op.cc的写法，想写自己的op，我看blas.sh中的关于MatMul运算的cpu和gpu写法是统一的(blas有一个`DeviceContext`的模板)，因此想基于此调用gpu的GEMM和SCAL等函数，但是提示undefined reference to `void paddle::operators::math::Blas<paddle::platform::CUDADeviceContext>::SCAL<float>(int, float, float*) const'`，想问下cuda版本的SCAL等函数在实现新op中是怎么使用的呢？

**Comment by sneaxiy** [comment]
目前应该没有实现CUDA版本的SCAL，您可以自己添加一个。需要在这些几个特化类里调用cublas的函数调用即可。
https://github.com/PaddlePaddle/Paddle/blob/bba740710d0d6f2088d808e692886b04f52260ac/paddle/fluid/operators/math/blas_impl.cu.h#L31

例如：

```C++
template <typename... ARGS>
static void SCAL(ARGS... args) {
   PADDLE_ENFORCE_CUDA_SUCCESS(platform::dynload::cublasSscal(args...));
}
```

**Comment by littletomatodonkey** [comment]
我看blas和cublas的scal接口不同，这块如果按照下面这种写法的话（为了和cpu scale统一接口）
![image](https://user-images.githubusercontent.com/14270174/77607802-6aecdd00-6f56-11ea-9489-a17c105ec07e.png)
![image](https://user-images.githubusercontent.com/14270174/77607817-7213eb00-6f56-11ea-9779-c0febd466fbf.png)

```
template <>
template <typename T>
void Blas<platform::CUDADeviceContext>::SCAL(int n, const T alpha,
                                             T *x) const {
  context_.CublasCall([&](cublasHandle_t handle) {
    CUBlas<T>::SCAL(handle, n, &alpha, x);
  });
}
```
会有下面的错误
![image](https://user-images.githubusercontent.com/14270174/77607937-ce770a80-6f56-11ea-9484-24da65708093.png)

想问下是我添加的这个接口有问题吗？

**Comment by sneaxiy** [comment]
您调整下SCAL那里的参数顺序和类型就可以了，显式地把所有参数列出来，和cblas统一即可。

**Comment by littletomatodonkey** [comment]
嗯嗯调好了，多谢！
