### ISSUE TITLE
如何把一个数组打乱顺序

### ISSUE THREAD

**Issue by zhengzhe97** [PaddlePaddle/Paddle#23229]
![TW%92(00VV{~1@YVD0003KU](https://user-images.githubusercontent.com/26462054/77597271-459da600-6f39-11ea-9cde-df30db9b5c88.png)
类似numpy的这种操作

**Comment by NHZlX** [comment]
应该没有完全打乱的op， 
有部分打乱的Op：

https://www.paddlepaddle.org.cn/documentation/docs/zh/api_cn/layers_cn/pixel_shuffle_cn.html#pixel-shuffle

https://www.paddlepaddle.org.cn/documentation/docs/zh/api_cn/layers_cn/shuffle_channel_cn.html#shuffle-channel

**Comment by NHZlX** [comment]
请问你这边是否需要在训练中使用shuffle呢，还是只是在预测中使用。如果是训练中使用，麻烦说下使用场景，我们这边会进行集成评估。如果是预测中使用的话，可以将对应的var fetch出来，然后使用python进行shuffle
