### ISSUE TITLE
源码编译，全异步分布式训练，meets grpc error

### ISSUE THREAD

**Issue by leesusu** [PaddlePaddle/Paddle#23225]
**编译环境：**

1. 官方版本，git checkout -b release1.7 remotes/origin/release/1.7
2. 编译镜像：hub.baidubce.com/paddlepaddle/paddle:latest-dev
3. cmake .. -DPY_VERSION=2.7 -DWITH_FLUID_ONLY=ON -DWITH_GPU=OFF -DWITH_TESTING=OFF -DWITH_INFERENCE_API_TEST=OFF -DWITH_COVERAGE=OFF -DCMAKE_BUILD_TYPE=Release -DWITH_DISTRIBUTE=ON
4. 用编译后的镜像，跑全异步训练

**问题描述：**
ps正常：
![image](https://user-images.githubusercontent.com/2424688/77538991-967eb180-6edb-11ea-9690-97d58149ade4.png)

trainer不正常：
![image](https://user-images.githubusercontent.com/2424688/77539039-a9918180-6edb-11ea-9e2f-ab1832cc6dac.png)

应该可以排除代码问题，我用官方镜像（hub.baidubce.com/paddlepaddle/paddle:1.7.1）是可以跑的

**Comment by seiriosPlus** [comment]
-D WITH_GRPC=ON

**Comment by seiriosPlus** [comment]
是不是开了 http_proxy ？

**Comment by leesusu** [comment]
@seiriosPlus 没有🤷‍♂️

**Comment by seiriosPlus** [comment]
自己ping server端的端口，能ping的通么

**Comment by leesusu** [comment]
@seiriosPlus 试了下，可以ping通

**Comment by seiriosPlus** [comment]
我先自行build 1.7.1进行尝试一下

**Comment by leesusu** [comment]
@seiriosPlus 解决了，Dockfile 里加了 http_proxy，👍感谢
