### ISSUE TITLE
运行程序出错，在小数据上没问题

### ISSUE THREAD

**Issue by leidongfeng** [PaddlePaddle/Paddle#23226]
错误日志在下面
<img width="1419" alt="MacHi 2020-03-25 21-07-07" src="https://user-images.githubusercontent.com/16134799/77539635-b06cc400-6edc-11ea-8163-bf595332e00f.png">

**Comment by sneaxiy** [comment]
这个错误应该是内存不足，建议看下机器内存是否充足。
