### ISSUE TITLE
新增paddle.tensor.mul(), paddle.tensor.pow() API

### ISSUE THREAD

**Issue by Steffy-zxf** [PaddlePaddle/Paddle#23253]
1. 新增paddle.tensor.mul(x, y, x_num_col_dims=1, y_num_col_dims=1, out=None, name=None)
   此运算是用于对输入x和y执行矩阵乘法。输入x和y都可以携带LoD（详细程度）信息。但输出仅与输入x共享LoD信息。
   * 参数：
     * x (Variable) - 乘法运算的第一个输入张量Tensor/LoDTensor。
     * y (Variable) - 乘法运算的第二个输入张量Tensor/LoDTensor。
     * x_num_col_dims (int，可选) - 默认值1， 可以将具有两个以上维度的张量作为输入。如果输入x是具有多于两个维度的张量，则输入x将先展平为二维矩阵。展平规则是：前 num_col_dims 将被展平成最终矩阵的第一个维度（矩阵的高度），其余的 rank(x) - num_col_dims 维度被展平成最终矩阵的第二个维度（矩阵的宽度）。结果是展平矩阵的高度等于x的前 x_num_col_dims 维数的乘积，展平矩阵的宽度等于x的最后一个 rank(x)- num_col_dims 个剩余维度的维数的乘积。例如，假设x是一个5-D张量，形状为（2,3,4,5,6），并且 x_num_col_dims 的值为3。 则扁平化后的张量具有的形即为（2x3x4,5x6）=（24,30）。
     * y_num_col_dims (int，可选) - 默认值1， 可以将具有两个以上维度的张量作为输入。如果输入y是具有多于两个维度的张量，则y将首先展平为二维矩阵。 y_num_col_dims 属性确定y的展平方式。有关更多详细信息，请参阅 x_num_col_dims 的注释。
     * out（Variable，可选）- 默认值None，如果out非空，是一个Variable， 则将该运算返回结果赋值给out。如果为None，则程序自动创建一个Variable存储运算结果。
     * name (str，可选) -默认值None，该参数供开发人员打印调试信息时使用，指定该运算输出变量name。如果out和name同时设定不为空，则out优先级高于name，即输出结果以out 变量name为准。

    * 返回：Variable(Tensor)乘法运算输出张量。

2. 新增paddle.tensor.pow(input, exponent, out=None, name=None) 
此运算用于对输入input、exponent，进行指数运算。
    * 参数：
       * input （Variable）- 多维 Tensor 或 LoDTensor ，数据类型为 float32 或 float64 。Pow OP的底数因子。
      * exponent （float32|Variable）- float32 或形状为[1]的 Tensor 或 LoDTensor，数据类型为 float32。Pow OP的指数因子。
      * out（Variable，可选）- 默认值None，如果out非空，是一个Variable， 则将该运算返回结果赋值给out。如果为None，则程序自动创建一个Variable存储运算结果。
      * name （str，可选）- 默认值None， 该参数供开发人员打印调试信息时使用，指定该运算输出变量name。如果out和name同时设定不为空，则out优先级高于name，即输出结果以out 变量name为准。

     * 返回：维度与输入 x 相同的 Tensor 或 LoDTensor，数据类型与 x 相同。

**Comment by NHZlX** [comment]
此为新增op issue。
