### ISSUE TITLE
如何实现类似TF的bias_add

### ISSUE THREAD

**Issue by drhades** [PaddlePaddle/Paddle#23263]

**Comment by NHZlX** [comment]
https://www.paddlepaddle.org.cn/documentation/docs/zh/api_cn/layers_cn/elementwise_add_cn.html#elementwise-add 如果输入的两个都是tensor的话，可以用elementwise add， 这个op支持broad cast

**Comment by drhades** [comment]
@NHZlX 谢谢

paddle中是否可以直接使用conv2d的bias_attr
```
fluid.layers.conv2d(..., 
                    bias_attr= ? , ...)

》bias_attr应该如何生成？
》》bias_attr = 0.1 * fluid.initializer.Normal() #无法相乘
》》bias_attr = 0.1 * fluid.layers.gaussian_random([32]) #Variable无法赋值给ParamAttr
```
来模拟实现TF中CNN的卷积偏置
```
bc1 = tf.Variable(0.1 * tf.random_normal([32]))
tf.nn.bias_add(tf.nn.conv2d(...), bc1)
```

**Comment by drhades** [comment]
bias_attr = fluid.initializer.NumpyArrayInitializer(0.1 * np.random.randn(32))

这样是否可以？

**Comment by drhades** [comment]
`bias_attr = fluid.initializer.NumpyArrayInitializer(0.1 * np.random.randn(32))`

这样是否可以？

**Comment by NHZlX** [comment]
可以的

**Comment by drhades** [comment]
THX
