### ISSUE TITLE
Compiled with WITH_GPU, but no GPU found in runtime 

### ISSUE THREAD

**Issue by HaozhengAN** [PaddlePaddle/Paddle#23268]
基于paddlepaddle/paddle:1.5.2-gpu-cuda9.0-cudnn7镜像构建的新镜像，
![图片](https://user-images.githubusercontent.com/34512369/77718128-0ea0c080-701d-11ea-812a-7a323b607ad9.png)
[work@yq01-gpu-yq-adu-1-28 paddleflow]$ nvidia-smi
Fri Mar 27 11:21:55 2020
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 440.33.01    Driver Version: 440.33.01    CUDA Version: 10.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla P40           On   | 00000000:00:07.0 Off |                    0 |
| N/A   25C    P8     9W / 250W |      0MiB / 22919MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+

系统信息：
![图片](https://user-images.githubusercontent.com/34512369/77718142-16606500-701d-11ea-89dc-d8af4a9585d6.png)
[work@yq01-gpu-yq-adu-1-28 paddleflow]$ cat /etc/issue
CentOS release 6.3 (Final)
Kernel \r on an \m

[work@yq01-gpu-yq-adu-1-28 paddleflow]$ uname -a
Linux yq01-gpu-yq-adu-1-28.epc.baidu.com 3.10.0_3-0-0-15 #1 SMP Fri Jan 12 18:18:11 CST 2018 x86_64 GNU/Linux
![图片](https://user-images.githubusercontent.com/34512369/77718148-1d877300-701d-11ea-9fe1-8e4cf465fb67.png)

cuda 尝试过8.0 9.0 10.0 10.2
cudnn 尝试过 7 7.4 7.6

**Comment by kolinwei** [comment]
能贴下具体的日志吗？
可以尝试看下cuda安装目录下的 example能否正常跑。

**Comment by HaozhengAN** [comment]
<img width="1060" alt="图片" src="https://user-images.githubusercontent.com/34512369/77738481-dfa14380-704a-11ea-8e7d-e7d43420bda0.png">
<img width="1059" alt="图片" src="https://user-images.githubusercontent.com/34512369/77738510-ed56c900-704a-11ea-9022-832c98ac31c0.png">

**Comment by wzzju** [comment]
您好，请问您使用这个镜像是编译最新的develop分支上的代码吗？
您试试`paddlepaddle/paddle:latest-gpu-cuda10.0-cudnn7-dev`这个镜像呢？

**Comment by HaozhengAN** [comment]
这个应该和镜像没有关系，同样的代码和镜像，在centos7上是可以跑的。
]$ nvidia-smi
Fri Mar 27 17:34:54 2020
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 440.33.01    Driver Version: 440.33.01    CUDA Version: 10.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla K40m          On   | 00000000:03:00.0 Off |                    0 |
| N/A   27C    P8    20W / 235W |      0MiB / 11441MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   1  Tesla K40m          On   | 00000000:04:00.0 Off |                    0 |
| N/A   28C    P8    19W / 235W |      0MiB / 11441MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   2  Tesla K40m          On   | 00000000:83:00.0 Off |                    0 |
| N/A   29C    P8    20W / 235W |      0MiB / 11441MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   3  Tesla K40m          On   | 00000000:84:00.0 Off |                    0 |
| N/A   27C    P8    19W / 235W |      0MiB / 11441MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+

$ uname -a
Linux 3.10.0_3-0-0-30 #1 SMP Thu Oct 24 18:34:55 CST 2019 x86_64 x86_64 x86_64 GNU/Linux

cat /etc/issue
CentOS release 7.5 (Final)
Kernel \r on an \m

**Comment by wzzju** [comment]
在容器内再设置一下环境变量试试?
```shell
export LD_LIBRARY_PATH=/usr/lib64:/usr/local/lib:$LD_LIBRARY_PATH
```

如果还是不行的话建议换一个docker镜像再试试，比如paddlepaddle/paddle:latest-gpu-cuda10.0-cudnn7-dev。

请问您创建docker容器的命令是什么？有使用`nvidia-docker`命令吗？

**Comment by JepsonWong** [comment]
"Compiled with WITH_GPU, but no GPU found in runtime" 错误应该是在镜像内没有识别gpu，感觉是nvidia-docker没有将gpu映射进去，您在**镜像里使用 nvidia-smi 命令看看有没有输出**。
