### ISSUE TITLE
fluid.data 创建变量失败，shape问题

### ISSUE THREAD

**Issue by 3wGTA** [PaddlePaddle/Paddle#23270]
同样一段代码在不同机器上结果不一样

在自己机器上面跑
![image](https://user-images.githubusercontent.com/62338824/77719758-0d719280-7021-11ea-8b2e-3a66e41a05b9.png)

报错如下
![image](https://user-images.githubusercontent.com/62338824/77719775-195d5480-7021-11ea-8e68-bb6ca4f4575a.png)

在AIstudio上面跑如下，没有报错

![image](https://user-images.githubusercontent.com/62338824/77719795-267a4380-7021-11ea-8d83-c202dd94921d.png)

上面代码shape改成这样
![image](https://user-images.githubusercontent.com/62338824/77719706-ec10a680-7020-11ea-911f-f91bbcb16700.png)

本机环境：python 3.7.3
![image](https://user-images.githubusercontent.com/62338824/77719988-9688c980-7021-11ea-9cd2-afb9404e3c4e.png)

AIStudio环境
![image](https://user-images.githubusercontent.com/62338824/77719918-6e996600-7021-11ea-9f6e-97fdf278a0c1.png)

更行paddle之后，本地环境运行同样的代码结果如下
![image](https://user-images.githubusercontent.com/62338824/77720456-f338b400-7022-11ea-93a4-2e3a2a3a3d54.png)
代码正常执行
更新后paddle版本如下所示
![image](https://user-images.githubusercontent.com/62338824/77720502-1499a000-7023-11ea-9f8f-2a98aaab7102.png)

解决方法：
更新paddle
![image](https://user-images.githubusercontent.com/62338824/77720615-67735780-7023-11ea-8039-04cd8c42c63d.png)

**Comment by kolinwei** [comment]
不同版本的paddle，目前会有一些不兼容的升级，可以参考下release note中的信息，尽量使用最新的paddle版本。
