### ISSUE TITLE
输入dynamic LSTM前经过fc做线性为什么能提升效率？

### ISSUE THREAD

**Issue by 131250208** [PaddlePaddle/Paddle#23286]
每次进dynamic LSTM前都要进一个fc，这相当于每一层都要多训练一个fc呀，这样做的意义是什么？看文档说线性变换是为了提高效率，为什么这样可以提高效率呢？为什么不直接扩展4份一样的x输入而要通过fc来线性变换呢。还是说进入LSTM以后就不用再做线性变换了，相当于手动进行了四个Wx的过程？

**Comment by guoshengCS** [comment]
这个是是因为公式中的对input的这些计算并不在 dynamic_lstm中包含，因而需要在外部加入fc，只有在外部加上fc才和LSTM在计算上是等价的。和你说的这个一致
>还是说进入LSTM以后就不用再做线性变换了，相当于手动进行了四个Wx的过程

<img width="615" alt="image" src="https://user-images.githubusercontent.com/14105589/77822975-890f3480-7132-11ea-97a9-b1786e0a15fa.png">

>看文档说线性变换是为了提高效率

这四个门一起进行计算确实能够一定程度的提供效率。但其实跟在LSTM内部实现和外部实现无太大关系。在外部实现主要还是因为LSTM内部不包含这些计算。

**Comment by 131250208** [comment]
@guoshengCS 啊，多谢回答，这样设计好像让编码变得很繁琐。希望以后能把这些都封装到LSTM里。

**Comment by Xray112247** [comment]
...找了半天shape对不齐的原因，原来在这
