### ISSUE TITLE
模型出现nan的情况

### ISSUE THREAD

**Issue by zhengzhe97** [PaddlePaddle/Paddle#23288]
- 版本、环境信息：
    1）PaddlePaddle版本：1.7
    2）GPU：V100
    3）训练数据：COCO2017

训练到一定阶段时出现nan，尝试调低学习率和LinearWarmup都会出现这种问题

尝试过输出每次迭代的loss和模型输出，loss和模型输出都比较正常，
会出现这种情况，上次迭代还是正常，下次模型就输出nan

![DP`$Z~%%VC}KDPB @{R C 6](https://user-images.githubusercontent.com/26462054/77818870-1f326300-7111-11ea-814d-3a80009efc02.png)

**Comment by jerrywgz** [comment]
请问下这个是官方提供的检测模型吗？

**Comment by zhengzhe97** [comment]
@jerrywgz 是自己复现的yolact，按照paddledetection改的。下午检测了下数据，数据是没问题的。

**Comment by jerrywgz** [comment]
nan的话一般就是出现除0的情况，可以着重看下几个部分：1. 如果有预训练模型的话可以确认下是否加载正确 2. 确认下reader的预处理中是否会出现box（或mask）为空的情况 3. 模型结构中计算loss的部分是否有考虑到正样本为0的情况

**Comment by zhengzhe97** [comment]
确实是在一个地方出现了除0的情况，但是没有出现警告，讲道理应该有吧，element_div这个op

**Comment by jerrywgz** [comment]
这里我们是需要加强下这个op的数据检查
