### ISSUE TITLE
paddlehub：IndexError: list index out of range

### ISSUE THREAD

**Issue by cvdnn** [PaddlePaddle/Paddle#23291]
- 标题：paddlehub：IndexError: list index out of range
- 版本、环境信息：
    1）PaddlePaddle版本：1.7.1
    4）系统环境：Ubuntu 16.04，Python 3.7
- 训练信息
    1）单机, CPU
    2）显存信息
![outofindex](https://user-images.githubusercontent.com/15883260/77842898-31240c80-71ca-11ea-8459-1158c43e795f.jpg)

**Comment by cvdnn** [comment]
代码详见：https://github.com/PaddlePaddle/PaddleHub/issues/478

**Comment by Steffy-zxf** [comment]
感谢反馈！该问题已在 https://github.com/PaddlePaddle/PaddleHub/issues/478 回复
