### ISSUE TITLE
关于paddle.fluid.layers.pixel_shuffle在动态图中的使用

### ISSUE THREAD

**Issue by ghost** [PaddlePaddle/Paddle#23311]
请教一下，我想要在动态图模式下将一个卷积层，一个像素清洗层，一个激活层打包成为一个子像素卷积模块，请问此时像素清洗层的paddle.fluid.layers.pixel_shuffle()中的输入参数x该怎么处理，此时并没有输入数据。
![1](https://user-images.githubusercontent.com/44671073/77902104-3f018c80-72b3-11ea-812a-481a0d77e297.jpg)
![2](https://user-images.githubusercontent.com/44671073/77902228-707a5800-72b3-11ea-997b-7141d1f9e850.jpg)

**Comment by phlrain** [comment]
pixel_shuffle  是一个没有参数的op，而且是一个function，可以在forward 里面直接调用，x 在forward里面获取
