### ISSUE TITLE
PR 22961 caused significant performance regression on BERT inference

### ISSUE THREAD

**Issue by ddokupil** [PaddlePaddle/Paddle#23319]
-PaddlePaddle version: https://github.com/PaddlePaddle/Paddle/pull/22961
-CPU: including CLX 6248, DNNL1.2
-OS Platform: Ubuntu 16.04
-Python version 2.7.12
-Cmake orders cmake .. -DCMAKE_BUILD_TYPE=Release -DWITH_GPU=OFF -DWITH_MKLDNN=ON -DWITH_TESTING=ON -DWITH_PROFILER=ON -DWITH_STYLE_CHECK=OFF -DON_INFER=ON -DWITH_INFERENCE_API_TEST=ON

execute:
$ /repos/paddle_paddle/build/paddle/fluid/inference/tests/api/test_analyzer_bert --gtest_filter=Analyzer_bert.profile --paddle_num_threads=1 --repeat=1000 -use_mkldnn=true --infer_data=/repos/paddle_paddle/build/third_party/inference_demo/bert_emb128/data.txt  --batch_size=1    --infer_model=/repos/paddle_paddle/build/third_party/inference_demo/bert_emb128/model

We've always had around 132fps on that and after this commit it falls to 106fps

**Comment by jczaja** [comment]
I have noticed this problem when working with BERT using
 Intel(R) Xeon(R) CPU E5-2699 v4 @ 2.20GHz  

current develop(regression):
thread0::gelu                   24000       **15363.7**     0.636816    1.8178      0.640154    **0.576969**

before (older develop):
thread0::gelu  24000   **581.156**  0.022947  0.534694   0.0242148   **0.0485629**

#22961 did remove MKL based GELU implementation and Eigen based implementation was introduced, which seems significantly slower on some of platforms

**Comment by luotao1** [comment]
@iclementine will add MKL based GELU implementation back

**Comment by iclementine** [comment]
work in progress.
https://github.com/PaddlePaddle/Paddle/pull/23420
