### ISSUE TITLE
1.7.1 DataLoader在linux中运行正常，在windows中运行失败

### ISSUE THREAD

**Issue by kinghuin** [PaddlePaddle/Paddle#23329]
1）PaddlePaddle版本：1.7.1
    2）windows
- 训练信息
    1）单机单卡
- 复现信息：
用户反馈：https://github.com/PaddlePaddle/PaddleHub/issues/487
pip install paddlehub，然后运行[本程序](https://github.com/PaddlePaddle/PaddleHub/blob/release/v1.6/demo/image_classification/img_classifier.py)
- 问题描述：使用linux运行正常无误，只有使用windows才会报错，存在操作系统上的运行差异

**Comment by gavin1332** [comment]
PaddleHub项目中已解决，关闭此issue

**Comment by gavin1332** [comment]
可否提供非hub版本的最小可复现代码？

**Comment by kinghuin** [comment]
@gavin1332 
暂时没有最小可复现代码，

dataloader使用处：https://github.com/PaddlePaddle/PaddleHub/blob/release/v1.6/paddlehub/finetune/task/base_task.py#L1056

相应reader代码：https://github.com/PaddlePaddle/PaddleHub/blob/release/v1.6/paddlehub/reader/cv_reader.py#L166

有用户给出了解决方案:

https://github.com/PaddlePaddle/PaddleHub/issues/500

![image](https://user-images.githubusercontent.com/11913168/79203692-f7abfc00-7e6d-11ea-9a96-7c6ff67b0bc1.png)

windows下需要自己转化类型，这是什么原因造成的呢？
