### ISSUE TITLE
调用fluid.layers.lstm时报NameError: name 'core' is not defined

### ISSUE THREAD

**Issue by Pipi24** [PaddlePaddle/Paddle#23328]
- 标题：调用fluid.layers.lstm时报NameError: name 'core' is not defined
- 版本、环境信息：
    1）PaddlePaddle版本：PaddlePaddle 1.7.0
    2）GPU：Tesla v100
    3)  环境：AIstudio

- 问题描述：调用fluid.layers.lstm时报NameError: name 'core' is not defined

- 调用代码
_, last_h, _ = fluid.layers.lstm(
            input=out,
            init_h = init_h,
            init_c = init_c,
            max_len = 32,
            hidden_size =768,
            num_layers = 2,
            dropout_prob = 0.1,
            #is_bidirec = True
            )
- 错误日志
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/layers/rnn.py in lstm(input, init_h, init_c, max_len, hidden_size, num_layers, dropout_prob, is_bidirec, is_test, name, default_initializer, seed)
   2161 
   2162     cache = helper.create_variable(
-> 2163        persistable=True, type=core.VarDesc.VarType.RAW, stop_gradient=True)
   2164 
   2165     helper.append_op(
NameError: name 'core' is not defined

**Comment by luotao1** [comment]
#23142 和 #23289 都已经对这个问题进行修复了。我们会尽快合入这个PR
