### ISSUE TITLE
1.6.2 save_inference_model成功，1.7.0 save_inference_model失败

### ISSUE THREAD

**Issue by kinghuin** [PaddlePaddle/Paddle#23330]
1）PaddlePaddle版本：1.6.2，1.7.0.post97
    2）系统环境：python2.7和python3均出现该问题
- 训练信息
    1）单机单卡
- 复现信息：该问题由用户反馈：https://github.com/PaddlePaddle/PaddleHub/issues/473
复现方式：pip install paddlehub, 之后运行[本程序](https://github.com/PaddlePaddle/PaddleHub/blob/release/v1.6/demo/reading_comprehension/reading_comprehension.py)
PaddleHub中的组网代码 ：https://github.com/PaddlePaddle/PaddleHub/blob/release/v1.6/paddlehub/finetune/task/reading_comprehension_task.py#L409
PaddleHub中的模型保存代码：https://github.com/PaddlePaddle/PaddleHub/blob/release/v1.6/paddlehub/finetune/task/base_task.py#L849
错误信息：
![image](https://user-images.githubusercontent.com/11913168/79449838-80659c00-8016-11ea-86fb-9ec2efd2e5a1.png)

问题描述：1.6.2运行正常，只有1.7失败，存在版本不同运行的差异

**Comment by Shixiaowei02** [comment]
我来跟进这个问题。

**Comment by kinghuin** [comment]
@Shixiaowei02 请问这一问题是否解决了呢？

**Comment by xwen99** [comment]
@Shixiaowei02 请问是否有不降级的解决方案呢，我的模型在 1.6.2 版本会有 bug。。。PaddlePaddle 1.7.0 解决了那个问题，但又会出现与本 issue 一样的问题。。。

**Comment by kinghuin** [comment]
hi，@xwen99 可以升级到1.8.1
