### ISSUE TITLE
本地调试报错 paddle.fluid.core.EnforceNotMet: Enforce failed.

### ISSUE THREAD

**Issue by zhaoyang1708** [PaddlePaddle/Paddle#23342]
本地调试报错
2020-03-31 15:10:37 start to run
2020-03-31 15:10:37 first batch
Traceback (most recent call last):
  File "script/local_train.py", line 17, in <module>
    model_output_back="/home/shawn/novel-bsq/novel-res-cross"
  File "/home/shawn/novel-bsq/novel-res-cin/script/train.py", line 819, in train
    train_loop(fluid.default_main_program())
  File "/home/shawn/novel-bsq/novel-res-cin/script/train.py", line 744, in train_loop
    auc_var_cos.name, cur_auc_cos.name])
  File "/home/shawn/tbbsq/tbbsq-resnet/python27-gcc482/lib/python2.7/site-packages/paddle/fluid/parallel_executor.py", line 297, in run
    self.executor.run(fetch_list, fetch_var_name)
paddle.fluid.core.EnforceNotMet: Enforce failed. Expected out_dims[j] == ins[i][j], but received out_dims[j]:101 != ins[i][j]:202.
Input tensors should have the same elements except the specify axis. at [/home/paddle/qiaolongfei/Paddle/paddle/fluid/operators/concat_op.cc:55]
PaddlePaddle Call Stacks:
0       0x7f245dfc611dp void paddle::platform::EnforceNotMet::Init<std::string>(std::string, char const*, int) + 365
1       0x7f245dfc7230p paddle::platform::EnforceNotMet::EnforceNotMet<char const*, char const*, char const*, char const*, std::string, char const*, std::string, std::string>(char const*, int, char const*, char const*, char const*, char const*, std::string, char const*, std::string, std::string) + 144
2       0x7f245e4ccc52p paddle::operators::ConcatOp::InferShape(paddle::framework::InferShapeContext*) const + 1106
3       0x7f245ed2f86ap paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&) const + 730
4       0x7f245ed2bf75p paddle::framework::OperatorBase::Run(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&) + 229
5       0x7f245ecc44e0p
6       0x7f245ecc41b0p paddle::framework::details::ComputationOpHandle::RunImpl() + 112
7       0x7f245ecd630cp paddle::framework::details::OpHandleBase::Run(bool) + 28
8       0x7f245ec5369dp
9       0x7f245e6c9a03p std::_Function_handler<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> (), std::__future_base::_Task_setter<std::unique_ptr<std::__future_base::_Result<void>, std::__future_base::_Result_base::_Deleter>, void> >::_M_invoke(std::_Any_data const&) + 35
10      0x7f245e691cd7p std::__future_base::_State_base::_M_do_set(std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> ()>&, bool&) + 39
11      0x7f249792f973p pthread_once + 83
12      0x7f245ec52382p
13      0x7f245e692f64p ThreadPool::ThreadPool(unsigned long)::{lambda()#1}::operator()() const + 404
14      0x7f246d4138a0p
15      0x7f249792a1c3p
16      0x7f2496f5212dp clone + 109

**Comment by luotao1** [comment]
1. 从报错格式看，是1.6以前的版本吧，请升级到1.6或者1.7最新版本
2. 错误在concat_op，可着重检查下。
```
paddle.fluid.core.EnforceNotMet: Enforce failed. Expected out_dims[j] == ins[i][j], but received out_dims[j]:101 != ins[i][j]:202.
Input tensors should have the same elements except the specify axis. at [/home/paddle/qiaolongfei/Paddle/paddle/fluid/operators/concat_op.cc:55]
```
