### ISSUE TITLE
Build package with released source code will generate wrong version number.

### ISSUE THREAD

**Issue by wanglei828** [PaddlePaddle/Paddle#2334]
I download the released source code (such as version V0.10.0), and build the package with the command: 
_docker run -v $(pwd):/paddle -e "WITH_GPU=OFF" -e "WITH_AVX=OFF" -e "WITH_TEST=ON" paddlepaddle/paddle:latest-dev_
It generates deb package "paddle-0.1.1-Linux.deb".
After I install the package and run "paddle version", it shows the wrong version number "0.0.0".

**Comment by Xreki** [comment]
You can get the answer from the [FAQ: 11. CMake源码编译，Paddle版本号为0.0.0](https://github.com/PaddlePaddle/Paddle/blob/develop/doc/faq/index_cn.rst#cmake-paddle0-0-0). As it says, you need to run the command `git fetch upstream`.

**Comment by qingqing01** [comment]
Thank you for your feedback.  Maybe the `tag` is not included in the released source code.  @gangliao Could we add the `tag` easily?

**Comment by Xreki** [comment]
I found two problems:
- Release package is not a git repository, so version cannot be got from `git tag`
- There maybe some bugs when generating `.deb` package, which are also in the current develop branch
