### ISSUE TITLE
问题咨询

### ISSUE THREAD

**Issue by pengpeng512** [PaddlePaddle/Paddle#23343]
向你咨询请较问题，https://github.com/MCai416/SEIR-COVID19/blob/master/SEIR%20Python.py 如果我想把这个例子 用paddle实现 请问有什么方法吗
主要是我必须在我的模型中应用paddle ；请帮助看下，哪些地方可以用

**Comment by luotao1** [comment]
请问这是深度学习模型么？这个模型是用来做什么呢？从目前的脚本看，看不出来怎么用

**Comment by pengpeng512** [comment]
不是深度学习的，就是一个动力学模型，参数都定好了；相当于公式和参数都订好了的，可以理解为一个线性回归的f(x)已经得到了。请问可以在样本、和评估预测结果方面用到paddle吗

**Comment by luotao1** [comment]
线性回归可以先参考 https://www.paddlepaddle.org.cn/documentation/docs/zh/user_guides/simple_case/fit_a_line/README.cn.html 或 https://www.paddlepaddle.org.cn/tutorials/projectdetail/328824
