### ISSUE TITLE
多机训练每个节点test loss差异较大

### ISSUE THREAD

**Issue by mengyiliu22** [PaddlePaddle/Paddle#23368]
为使您的问题得到快速解决，在建立Issues前，请您先通过如下方式搜索是否有相似问题:【搜索issue关键字】【使用labels筛选】【官方文档】

如果您没有查询到相似问题，为快速解决您的提问，建立issue时请提供如下细节信息：
- 标题：简洁、精准概括您的问题，例如“Insufficient Memory xxx" ”
- 版本、环境信息：
    1）PaddlePaddle版本：1.6
    2）CPU：预测若用CPU，请提供CPU型号，MKL/OpenBlas/MKLDNN/等数学库使用情况
    3）GPU：预测若用GPU，请提供GPU型号、CUDA和CUDNN版本号
    4）系统环境：请您描述系统类型、版本，例如Mac OS 10.14，Python版本
- 训练信息
    1）多机，多卡
    2）显存信息
    3）Operator信息

0号节点loss为0.25，其余节点loss为0.7，差异较大，请问这种现象正常吗？

**Comment by shippingwang** [comment]
请问具体是什么任务呢？
