### ISSUE TITLE
PaddleCV【多目标追踪的特性支持】

### ISSUE THREAD

**Issue by AlexNorth365** [PaddlePaddle/Paddle#23366]
Hi there,

PaddlePaddle 对多目标追踪的特性支持，目前有什么计划吗？

或者目前有合适的方式，可以解决多目标追踪的业务需求。谢谢！

**Comment by LDOUBLEV** [comment]
paddle 目前没有多目标跟踪的模型，只有[单目标跟踪](https://github.com/PaddlePaddle/models/tree/develop/PaddleCV/tracking)的。如果想实现多目标跟踪，可以利用DBT的方法来做，而且paddle有丰富的[detection模型](https://github.com/PaddlePaddle/PaddleDetection)
