### ISSUE TITLE
Matrix.cpp:2695] Check failed: index[i] >= 0 (-1116557168 vs. 0)

### ISSUE THREAD

**Issue by hitwangshuai** [PaddlePaddle/Paddle#2338]
麻烦帮看一下如下问题：
core信息：
![image](https://cloud.githubusercontent.com/assets/22500910/26663845/23d38a84-46c0-11e7-8975-acdd751375dd.png)

gdb结果：
![image](https://cloud.githubusercontent.com/assets/22500910/26663878/554bf77c-46c0-11e7-92c8-579291600594.png)

dataprovide文件：
![image](https://cloud.githubusercontent.com/assets/22500910/26664362/95ed9d14-46c3-11e7-80e7-13871227aca3.png)
![image](https://cloud.githubusercontent.com/assets/22500910/26664374/b32cb3b0-46c3-11e7-913d-f4d70d796b58.png)

模型配置文件：
![image](https://cloud.githubusercontent.com/assets/22500910/26664385/cffde73e-46c3-11e7-8bd0-5091ec036efb.png)
![image](https://cloud.githubusercontent.com/assets/22500910/26664389/dcddc24e-46c3-11e7-8f6a-9577fca293ca.png)

**Comment by hitwangshuai** [comment]
我本地用dataprovider的脚本训练的模型，计划线上用capi接口调用的，数据格式我check了没问题啊

**Comment by qingqing01** [comment]
>  Check failed: index[i] >= 0 (-1116557168 vs. 0) #2338

上面出的错是使用capi预测出的错吧？ 是如何给的数据呢？ 这个错看样子是 `word`对应的数据没有正确输入。

**Comment by hitwangshuai** [comment]
是capi预测的，传入数据已经按照训练模型时输入的方式给了，特征编号从0（UNK_IDX）开始给的。总维度=特征ID化词典大小 + 1；感觉不像是因为某个特征输入的不对导致的，因为我完全用你们demo里的输入也是这个错误

**Comment by hitwangshuai** [comment]
解决啦，问题出在：1.没有打开下面的注释
![image](https://cloud.githubusercontent.com/assets/22500910/26679948/e101b150-4709-11e7-8f34-b29f9ac78c77.png);
2.注意：paddle_ivector sentence = paddle_ivector_create(
      sentence_ids, sizeof(sentence_ids) / sizeof(int), false, false);如果sentence_ids是栈式变量，第一个布尔变量要传true；
