### ISSUE TITLE
用官方的PointNet网络编译pointnet_lib.so报错error: ‘GradOpPtr’ has not been declared

### ISSUE THREAD

**Issue by a178052771** [PaddlePaddle/Paddle#23425]
- 版本、环境信息：
    1）PaddlePaddle版本：1.7.1
    2）CUDA:9.0
    3）cuDNN：7.3
    4）系统环境：Linux16.4、Python版本2.7
- 安装方式信息：
1）pip安装
- 复现信息：按github的步骤在~/models-develop/PaddleCV/3d_vision/PointNet++/ext_op/src里用sh make.sh编译
- 报错信息：
(tensorflow) xz@xz:~/models-develop/PaddleCV/3d_vision/PointNet++/ext_op/src$ sh make.sh 
/home/xz/.conda/envs/tensorflow/lib/python2.7/site-packages/paddle/include
/home/xz/.conda/envs/tensorflow/lib/python2.7/site-packages/paddle/libs
gather_point_op.cc:97:14: error: ‘GradOpPtr’ has not been declared
   void Apply(GradOpPtr<T> op) const override {
              ^
gather_point_op.cc:97:23: error: expected ‘,’ or ‘...’ before ‘<’ token
   void Apply(GradOpPtr<T> op) const override {
                       ^
gather_point_op.cc: In member function ‘void paddle::operators::GatherPointGradDescMaker<T>::Apply(int) const’:
gather_point_op.cc:99:5: error: ‘op’ was not declared in this scope
     op->SetType("gather_point_grad");
     ^
gather_point_op.cc: In instantiation of ‘class paddle::operators::GatherPointGradDescMaker<paddle::framework::OpDesc>’:
/usr/include/c++/4.8/type_traits:1287:12:   required from ‘struct std::is_base_of<paddle::framework::OperatorBase, paddle::operators::GatherPointGradDescMaker<paddle::framework::OpDesc> >’
/home/xz/.conda/envs/tensorflow/lib/python2.7/site-packages/paddle/include/paddle/fluid/framework/details/op_registry.h:74:25:   required from ‘constexpr const bool paddle::framework::details::internal::IsMatchedBaseTypeImpl<paddle::operators::GatherPointGradDescMaker<paddle::framework::OpDesc>, 0, true>::kValue’
/home/xz/.conda/envs/tensorflow/lib/python2.7/site-packages/paddle/include/paddle/fluid/framework/details/op_registry.h:86:63:   required from ‘constexpr bool paddle::framework::details::internal::IsMatchedBaseType() [with T = paddle::operators::GatherPointGradDescMaker<paddle::framework::OpDesc>; int kPos = 0]’
/home/xz/.conda/envs/tensorflow/lib/python2.7/site-packages/paddle/include/paddle/fluid/framework/details/op_registry.h:118:54:   required by substitution of ‘template<class T> using OpInfoFillTypeGetter = paddle::framework::details::internal::OpInfoFillTypeGetterImpl<T, 0, 8, false, IsMatchedBaseType<T, 0>()> [with T = paddle::operators::GatherPointGradDescMaker<paddle::framework::OpDesc>]’
/home/xz/.conda/envs/tensorflow/lib/python2.7/site-packages/paddle/include/paddle/fluid/framework/details/op_registry.h:125:47:   required from ‘static constexpr paddle::framework::details::OpInfoFillType paddle::framework::details::OpInfoFillTypeID<T>::ID() [with T = paddle::operators::GatherPointGradDescMaker<paddle::framework::OpDesc>]’
/home/xz/.conda/envs/tensorflow/lib/python2.7/site-packages/paddle/include/paddle/fluid/framework/details/op_registry.h:144:71:   recursively required from ‘paddle::framework::details::OperatorRegistrarRecursive<I, false, ARGS ...>::OperatorRegistrarRecursive(const char*, paddle::framework::OpInfo*) [with long unsigned int I = 1ul; ARGS = {paddle::operators::GatherPointOp, paddle::operators::GatherPointOpMaker, paddle::operators::GatherPointGradDescMaker<paddle::framework::OpDesc>, paddle::operators::GatherPointGradDescMaker<paddle::imperative::OpBase>}]’
/home/xz/.conda/envs/tensorflow/lib/python2.7/site-packages/paddle/include/paddle/fluid/framework/details/op_registry.h:144:71:   required from ‘paddle::framework::details::OperatorRegistrarRecursive<I, false, ARGS ...>::OperatorRegistrarRecursive(const char*, paddle::framework::OpInfo*) [with long unsigned int I = 0ul; ARGS = {paddle::operators::GatherPointOp, paddle::operators::GatherPointOpMaker, paddle::operators::GatherPointGradDescMaker<paddle::framework::OpDesc>, paddle::operators::GatherPointGradDescMaker<paddle::imperative::OpBase>}]’
/home/xz/.conda/envs/tensorflow/lib/python2.7/site-packages/paddle/include/paddle/fluid/framework/op_registry.h:63:5:   required from ‘paddle::framework::OperatorRegistrar<ARGS>::OperatorRegistrar(const char*) [with ARGS = {paddle::operators::GatherPointOp, paddle::operators::GatherPointOpMaker, paddle::operators::GatherPointGradDescMaker<paddle::framework::OpDesc>, paddle::operators::GatherPointGradDescMaker<paddle::imperative::OpBase>}]’
gather_point_op.cc:112:1:   required from here
gather_point_op.cc:97:8: error: ‘void paddle::operators::GatherPointGradDescMaker<T>::Apply(int) const [with T = paddle::framework::OpDesc]’ marked override, but does not override
   void Apply(GradOpPtr<T> op) const override {
        ^
group_points_op.cc:105:14: error: ‘GradOpPtr’ has not been declared
   void Apply(GradOpPtr<T> op) const override {
              ^
group_points_op.cc:105:23: error: expected ‘,’ or ‘...’ before ‘<’ token
   void Apply(GradOpPtr<T> op) const override {
                       ^
group_points_op.cc: In member function ‘void paddle::operators::GroupPointsGradDescMaker<T>::Apply(int) const’:
group_points_op.cc:106:5: error: ‘op’ was not declared in this scope
     op->SetType("group_points_grad");
     ^
group_points_op.cc: In instantiation of ‘class paddle::operators::GroupPointsGradDescMaker<paddle::framework::OpDesc>’:
/usr/include/c++/4.8/type_traits:1287:12:   required from ‘struct std::is_base_of<paddle::framework::OperatorBase, paddle::operators::GroupPointsGradDescMaker<paddle::framework::OpDesc> >’
/home/xz/.conda/envs/tensorflow/lib/python2.7/site-packages/paddle/include/paddle/fluid/framework/details/op_registry.h:74:25:   required from ‘constexpr const bool paddle::framework::details::internal::IsMatchedBaseTypeImpl<paddle::operators::GroupPointsGradDescMaker<paddle::framework::OpDesc>, 0, true>::kValue’
/home/xz/.conda/envs/tensorflow/lib/python2.7/site-packages/paddle/include/paddle/fluid/framework/details/op_registry.h:86:63:   required from ‘constexpr bool paddle::framework::details::internal::IsMatchedBaseType() [with T = paddle::operators::GroupPointsGradDescMaker<paddle::framework::OpDesc>; int kPos = 0]’
/home/xz/.conda/envs/tensorflow/lib/python2.7/site-packages/paddle/include/paddle/fluid/framework/details/op_registry.h:118:54:   required by substitution of ‘template<class T> using OpInfoFillTypeGetter = paddle::framework::details::internal::OpInfoFillTypeGetterImpl<T, 0, 8, false, IsMatchedBaseType<T, 0>()> [with T = paddle::operators::GroupPointsGradDescMaker<paddle::framework::OpDesc>]’
/home/xz/.conda/envs/tensorflow/lib/python2.7/site-packages/paddle/include/paddle/fluid/framework/details/op_registry.h:125:47:   required from ‘static constexpr paddle::framework::details::OpInfoFillType paddle::framework::details::OpInfoFillTypeID<T>::ID() [with T = paddle::operators::GroupPointsGradDescMaker<paddle::framework::OpDesc>]’
/home/xz/.conda/envs/tensorflow/lib/python2.7/site-packages/paddle/include/paddle/fluid/framework/details/op_registry.h:144:71:   recursively required from ‘paddle::framework::details::OperatorRegistrarRecursive<I, false, ARGS ...>::OperatorRegistrarRecursive(const char*, paddle::framework::OpInfo*) [with long unsigned int I = 1ul; ARGS = {paddle::operators::GroupPointsOp, paddle::operators::GroupPointsOpMaker, paddle::operators::GroupPointsGradDescMaker<paddle::framework::OpDesc>, paddle::operators::GroupPointsGradDescMaker<paddle::imperative::OpBase>}]’
/home/xz/.conda/envs/tensorflow/lib/python2.7/site-packages/paddle/include/paddle/fluid/framework/details/op_registry.h:144:71:   required from ‘paddle::framework::details::OperatorRegistrarRecursive<I, false, ARGS ...>::OperatorRegistrarRecursive(const char*, paddle::framework::OpInfo*) [with long unsigned int I = 0ul; ARGS = {paddle::operators::GroupPointsOp, paddle::operators::GroupPointsOpMaker, paddle::operators::GroupPointsGradDescMaker<paddle::framework::OpDesc>, paddle::operators::GroupPointsGradDescMaker<paddle::imperative::OpBase>}]’
/home/xz/.conda/envs/tensorflow/lib/python2.7/site-packages/paddle/include/paddle/fluid/framework/op_registry.h:63:5:   required from ‘paddle::framework::OperatorRegistrar<ARGS>::OperatorRegistrar(const char*) [with ARGS = {paddle::operators::GroupPointsOp, paddle::operators::GroupPointsOpMaker, paddle::operators::GroupPointsGradDescMaker<paddle::framework::OpDesc>, paddle::operators::GroupPointsGradDescMaker<paddle::imperative::OpBase>}]’
group_points_op.cc:119:1:   required from here
group_points_op.cc:105:8: error: ‘void paddle::operators::GroupPointsGradDescMaker<T>::Apply(int) const [with T = paddle::framework::OpDesc]’ marked override, but does not override
   void Apply(GradOpPtr<T> op) const override {
        ^
three_interp_op.cc:120:14: error: ‘GradOpPtr’ has not been declared
   void Apply(GradOpPtr<T> op) const override {
              ^
three_interp_op.cc:120:23: error: expected ‘,’ or ‘...’ before ‘<’ token
   void Apply(GradOpPtr<T> op) const override {
                       ^
three_interp_op.cc: In member function ‘void paddle::operators::ThreeInterpGradDescMaker<T>::Apply(int) const’:
three_interp_op.cc:121:5: error: ‘op’ was not declared in this scope
     op->SetType("three_interp_grad");
     ^
three_interp_op.cc: In instantiation of ‘class paddle::operators::ThreeInterpGradDescMaker<paddle::framework::OpDesc>’:
/usr/include/c++/4.8/type_traits:1287:12:   required from ‘struct std::is_base_of<paddle::framework::OperatorBase, paddle::operators::ThreeInterpGradDescMaker<paddle::framework::OpDesc> >’
/home/xz/.conda/envs/tensorflow/lib/python2.7/site-packages/paddle/include/paddle/fluid/framework/details/op_registry.h:74:25:   required from ‘constexpr const bool paddle::framework::details::internal::IsMatchedBaseTypeImpl<paddle::operators::ThreeInterpGradDescMaker<paddle::framework::OpDesc>, 0, true>::kValue’
/home/xz/.conda/envs/tensorflow/lib/python2.7/site-packages/paddle/include/paddle/fluid/framework/details/op_registry.h:86:63:   required from ‘constexpr bool paddle::framework::details::internal::IsMatchedBaseType() [with T = paddle::operators::ThreeInterpGradDescMaker<paddle::framework::OpDesc>; int kPos = 0]’
/home/xz/.conda/envs/tensorflow/lib/python2.7/site-packages/paddle/include/paddle/fluid/framework/details/op_registry.h:118:54:   required by substitution of ‘template<class T> using OpInfoFillTypeGetter = paddle::framework::details::internal::OpInfoFillTypeGetterImpl<T, 0, 8, false, IsMatchedBaseType<T, 0>()> [with T = paddle::operators::ThreeInterpGradDescMaker<paddle::framework::OpDesc>]’
/home/xz/.conda/envs/tensorflow/lib/python2.7/site-packages/paddle/include/paddle/fluid/framework/details/op_registry.h:125:47:   required from ‘static constexpr paddle::framework::details::OpInfoFillType paddle::framework::details::OpInfoFillTypeID<T>::ID() [with T = paddle::operators::ThreeInterpGradDescMaker<paddle::framework::OpDesc>]’
/home/xz/.conda/envs/tensorflow/lib/python2.7/site-packages/paddle/include/paddle/fluid/framework/details/op_registry.h:144:71:   recursively required from ‘paddle::framework::details::OperatorRegistrarRecursive<I, false, ARGS ...>::OperatorRegistrarRecursive(const char*, paddle::framework::OpInfo*) [with long unsigned int I = 1ul; ARGS = {paddle::operators::ThreeInterpOp, paddle::operators::ThreeInterpOpMaker, paddle::operators::ThreeInterpGradDescMaker<paddle::framework::OpDesc>, paddle::operators::ThreeInterpGradDescMaker<paddle::imperative::OpBase>}]’
/home/xz/.conda/envs/tensorflow/lib/python2.7/site-packages/paddle/include/paddle/fluid/framework/details/op_registry.h:144:71:   required from ‘paddle::framework::details::OperatorRegistrarRecursive<I, false, ARGS ...>::OperatorRegistrarRecursive(const char*, paddle::framework::OpInfo*) [with long unsigned int I = 0ul; ARGS = {paddle::operators::ThreeInterpOp, paddle::operators::ThreeInterpOpMaker, paddle::operators::ThreeInterpGradDescMaker<paddle::framework::OpDesc>, paddle::operators::ThreeInterpGradDescMaker<paddle::imperative::OpBase>}]’
/home/xz/.conda/envs/tensorflow/lib/python2.7/site-packages/paddle/include/paddle/fluid/framework/op_registry.h:63:5:   required from ‘paddle::framework::OperatorRegistrar<ARGS>::OperatorRegistrar(const char*) [with ARGS = {paddle::operators::ThreeInterpOp, paddle::operators::ThreeInterpOpMaker, paddle::operators::ThreeInterpGradDescMaker<paddle::framework::OpDesc>, paddle::operators::ThreeInterpGradDescMaker<paddle::imperative::OpBase>}]’
three_interp_op.cc:135:1:   required from here
three_interp_op.cc:120:8: error: ‘void paddle::operators::ThreeInterpGradDescMaker<T>::Apply(int) const [with T = paddle::framework::OpDesc]’ marked override, but does not override
   void Apply(GradOpPtr<T> op) const override {

**Comment by heavengate** [comment]
请使用models release/1.7分支的代码，models develop上的代码适配了Paddle develop上的一些修改，使用models develop代码的话需要Paddle develop编译版本，使用Paddle1.7版本的话请使用modes release/1.7的代码

**Comment by a178052771** [comment]
> 请使用models release/1.7分支的代码，models develop上的代码适配了Paddle develop上的一些修改，使用models develop代码的话需要Paddle develop编译版本，使用Paddle1.7版本的话请使用modes release/1.7的代码

我是按REDEME文档中的p分支源码链接https://www.paddlepaddle.org.cn/install/quick 安装的应该是develop版本，我是学生，不是很懂。谢谢您

**Comment by heavengate** [comment]
`python -c "import paddle; print(paddle.__version__)"`可以查看paddle版本，pip安装的一般是1.7版本，models库用release/1.7版本就可以了

**Comment by a178052771** [comment]
> `python -c "import paddle; print(paddle.__version__)"`可以查看paddle版本，pip安装的一般是1.7版本，models库用release/1.7版本就可以了

请问models库怎样换成release/1.7呢？

**Comment by a178052771** [comment]
> `python -c "import paddle; print(paddle.__version__)"`可以查看paddle版本，pip安装的一般是1.7版本，models库用release/1.7版本就可以了

找到了是您上传的https://github.com/PaddlePaddle/models/tree/release/1.7/ 这个版本是吧，谢谢

**Comment by heavengate** [comment]
是的，如果你已经clone了models模型库的话可以
```
git checkout release/1.7
git pull origin release/1.7
```

**Comment by a178052771** [comment]
> 是的，如果你已经clone了models模型库的话可以
> 
> ```
> git checkout release/1.7
> git pull origin release/1.7
> ```

卡了几天的问题解决了，太感谢了

**Comment by haileewu** [comment]
您好，请问我用pip安装的：pip install paddlepaddle-gpu==1.7.2.post97
但是最后make.sh 的时候报了和楼主同样的错误（一摸一样），请问您知道问题出在哪里吗？

**Comment by haileewu** [comment]
> 是的，如果你已经clone了models模型库的话可以
> 
> ```
> git checkout release/1.7
> git pull origin release/1.7
> ```

您好，请问我用pip安装的：pip install paddlepaddle-gpu==1.7.2.post97
但是最后make.sh 的时候报了和楼主同样的错误（一摸一样），请问您知道问题出在哪里吗？
