### ISSUE TITLE
discrepancy in default layer name caused by using two kinds of api

### ISSUE THREAD

**Issue by guoshengCS** [PaddlePaddle/Paddle#2344]
Since I am implementing caffe2paddle model converter and the saved models are related to layer name, I noticed this problem.  `paddle.v2.layer.img_conv` will get default layer name `__img_conv_layer__XXX`, but `paddle.v2.networks.img_conv_group` which implicitly uses `paddle.trainer_config_helpers.layers.img_conv_layer` will get default layer name `__conv__XXX`. This might be the reason that `__convert_to_v2__` use `wrap_name_default(name_prefix=method_name)` to wrap while `paddle.trainer_config_helpers.layers.img_conv_layer` use `wrap_name_default("conv")`.  Is it possible to get the default layer name in V1 and use this to wrap V2 layer name, and is it necessary to fix this.

**Comment by qingqing01** [comment]
I suggest we rewrite the  `img_conv_group` by `paddle.v2.layer.img_conv` and `paddle.v2.layer.img_pool` in the VGG configuration.

**Comment by guoshengCS** [comment]
This issue has been resolved by up-to-date PaddlePaddle V2 converter `__convert_to_v2__` python code.
