### ISSUE TITLE
can not reproduce the result of  book/03.image_classification/

### ISSUE THREAD

**Issue by NHZlX** [PaddlePaddle/Paddle#2345]
Model: resnet32
dataset: cifar10
using https://github.com/PaddlePaddle/book/blob/develop/03.image_classification/train.py
This looks like overfitting, that the test results are much worse than the training accuracy...
here is the log:
..........................................................................................
Test with Pass 12, score, 1.020731, {'classification_error_evaluator': 0.24729999899864197}

Pass 13, Batch 0, Cost 0.191999, {'classification_error_evaluator': 0.0390625}
5.97 seconds 100 batch
...................................................................................................
Pass 13, Batch 100, Cost 0.157929, {'classification_error_evaluator': 0.0703125}
78.67 seconds 100 batch
...................................................................................................
Pass 13, Batch 200, Cost 0.251160, {'classification_error_evaluator': 0.0859375}
77.86 seconds 100 batch
...................................................................................................
Pass 13, Batch 300, Cost 0.143929, {'classification_error_evaluator': 0.0546875}
58.15 seconds 100 batch

**Comment by qingqing01** [comment]
- The `momentum` and `decay_rate` does not work according to issue https://github.com/PaddlePaddle/Paddle/issues/2042 .

- Need to check data argumentation, like flipping.

**Comment by Canpio** [comment]
Close this issue due to inactivity. please feel free to reopen it if more information is available.
