### ISSUE TITLE
Java integration with PaddlePaddle

### ISSUE THREAD

**Issue by lanking520** [PaddlePaddle/Paddle#23475]
Hi, 

This is not really an issue but I thought it would be easy to reach out to the PaddlePaddle community here, so please close this issue whenever you wish.

I represent the official group responsible of developing DJL, a framework Agnostic Deep Learning framework running on Java. We are quite interested to work with you for a Java frontend that can help the community growing more adoption in JVM.

Here is a quick introduction of DJL:

DeepJavaLibrary (DJL) is a high-level Java-based Deep Learning (DL) Framework that defines patterns for effectively using Java for DL. It takes inspiration from the training and inference experiences within other major DL frameworks, while making changes to better suit Java development practices. It can be used to to create and train models, as well as run inference on production systems.

If you are interested, please reach us directly on one the following channels:

Website: https://djl.ai/
Email: djl-dev@amazon.com
GitHub: https://github.com/awslabs/djl
Slack: https://deepjavalibrary.slack.com/

**Comment by Boyan-Liu** [comment]
Hi,

Thanks for your contact. We are pleased and welcome to have outside contributors.
Please allow us to respond you after the discussion.

**Comment by Boyan-Liu** [comment]
Hi,

We have a high interest in the cooperation. The JavaDoc page on your website shows there have been MXNet and PyTorch. Could you please describe the cooperation details? Such as the same pattern as MXNet and PyTorch or in other ways?
 
Looking forward to your reply.
