### ISSUE TITLE
提出警告W0404 device_context.cc:237] Please NOTE: device: 0, CUDA Capability: 61, Driver API Version: 10.1, Runtime API Version: 10.0

### ISSUE THREAD

**Issue by JunKuangKuang** [PaddlePaddle/Paddle#23487]
`im_shape的维度： (1, 3, 32, 32)
results [array([[3.0364997e-09, 3.1183930e-07, 8.6202290e-06, 4.4916385e-05,
        6.8277484e-05, 7.2606611e-01, 8.2817266e-08, 2.7381164e-01,
        5.1946420e-17, 5.3443872e-10]], dtype=float32)]
infer results: dog
W0404 16:40:48.365986 14840 device_context.cc:237] Please NOTE: device: 0, CUDA Capability: 61, Driver API Version: 10.1, Runtime API Version: 10.0
W0404 16:40:48.373013 14840 device_context.cc:245] device: 0, cuDNN Version: 7.6.`

我是在本地windows运行paddle的，项目是猫狗分类，在使用CPU的时候没有影响，但是使用GPU的时候，就报错，版本如上。

想知道是哪里的原因及如何修改。

**Comment by hutuxian** [comment]
感谢使用Paddle
该信息只是一个提示信息，提示您当前GPU的一些基本情况，是正常的，请放心使用。

**Comment by JunKuangKuang** [comment]
谢谢
