### ISSUE TITLE
用动态图构建SRGAN网络时，出现未知报错信息

### ISSUE THREAD

**Issue by ghost** [PaddlePaddle/Paddle#23489]
![374700](https://user-images.githubusercontent.com/44671073/78430081-57085000-76a7-11ea-8a9a-bec1eb9dcb83.jpg)

**Comment by hutuxian** [comment]
麻烦您多提供一些信息。例如如果运行的是PaddlePaddle/models下面的模型，请提供一下模型库的版本。如果是您自定义的网络，请提供一个最小可复现的代码？

**Comment by ghost** [comment]
> 麻烦您多提供一些信息。例如如果运行的是PaddlePaddle/models下面的模型，请提供一下模型库的版本。如果是您自定义的网络，请提供一个最小可复现的代码？

[srgan-code.zip](https://github.com/PaddlePaddle/Paddle/files/4431293/srgan-code.zip)

**Comment by ghost** [comment]
> > 麻烦您多提供一些信息。例如如果运行的是PaddlePaddle/models下面的模型，请提供一下模型库的版本。如果是您自定义的网络，请提供一个最小可复现的代码？
> 
> [srgan-code.zip](https://github.com/PaddlePaddle/Paddle/files/4431293/srgan-code.zip)

代码给您了，麻烦你看一下，谢谢！

**Comment by hutuxian** [comment]
无法根据提供的代码复现您的报错，应该是有些输入数据没有附上。建议您先通过打印日志的方式定位出错的代码段。现在的信息不足以直接定位错误来源~

**Comment by ghost** [comment]
> 无法根据提供的代码复现您的报错，应该是有些输入数据没有附上。建议您先通过打印日志的方式定位出错的代码段。现在的信息不足以直接定位错误来源~

已将项目完整项目公开于AI Studio，https://aistudio.baidu.com/aistudio/projectdetail/374700
请您看一下，谢谢！

**Comment by hutuxian** [comment]
抱歉回复不及时。建议您先自行定位一下出错的代码行，然后再贴出来进行排查。之前的报错信息不足以判断出出错的原因，谢谢。
