### ISSUE TITLE
fluid.layers.assign op 训练时报错

### ISSUE THREAD

**Issue by maosengshulei** [PaddlePaddle/Paddle#23495]
单机训练时：

       
`vars = list(self.learn_program.list_vars())`

        target_vars = list(
            filter(lambda x: 'GRAD' not in x.name and 'target' in x.name, vars))
        policy_vars_name = [
            x.name.replace('target', 'policy') for x in target_vars
        ]
        policy_vars = list(filter(lambda x: x.name in policy_vars_name, vars))

        policy_vars.sort(key=lambda x: x.name)
        target_vars.sort(key=lambda x: x.name)
        
        with fluid.program_guard(self._sync_program):
            sync_ops = []
            decay = 1.0 - TAU
            for i, var in enumerate(policy_vars):
                #sync_op = fluid.layers.assign(decay * target_vars[i] + (1 - decay) * policy_vars[i], target_vars[i])
                sync_op = fluid.layers.assign(policy_vars[i], target_vars[i])
                sync_ops.append(sync_op)`
训练正常。
当我想把这种hard target updates 的方式换成soft target updates 即：

      
        
        with fluid.program_guard(self._sync_program):
            sync_ops = []
            decay = 1.0 - TAU
            for i, var in enumerate(policy_vars):
                sync_op = fluid.layers.assign(decay * target_vars[i] + (1 - decay) * policy_vars[i], target_vars[i])
                #sync_op = fluid.layers.assign(policy_vars[i], target_vars[i])
                sync_ops.append(sync_op)`          
训练时会报错：
Error: The Input Variable(X) of assign Op used to determine kernel data type is empty or not LoDTensor or SelectedRows.
  [Hint: Expected data_type != dafault_data_type, but received data_type:-1 == dafault_data_type:-1.] at (/home/teamcity/work/ef54dc8a5b211854/paddle/fluid/framework/operator.cc:1303)
  [operator < assign > error]

请教一下错误的原因，和实现soft target update的方法

**Comment by SunGaofeng** [comment]
1、是在CompileTime报错的，还是在RunTime报错的？
2、这里定义的 policy_vars = list(filter(lambda x: x.name in policy_vars_name, vars)) 
能检查下policy_vars中的Variable是否存在吗？可以打印下其中的Variable名字和shape，再就是看下Variable对应的tensor是否存在。

**Comment by maosengshulei** [comment]
1.Runtime时报错的：
![image](https://user-images.githubusercontent.com/26685090/78468348-c767ad80-7749-11ea-80b0-efcfd3d51f74.png)
2. print（policy_vars）的结果：
![image](https://user-images.githubusercontent.com/26685090/78468382-101f6680-774a-11ea-9375-d2e3da2dae07.png)

**Comment by SunGaofeng** [comment]
runtime的时候，policy vars里面的这些Variable是否已经在计算图里面被执行过了，也就是说它们对应的Tensor是否已经有值了？从报错信息来看，应该是这些Variable还没被计算到，他们只在CompileTime的时候被定义了shape和dtype，但是还没有用来存储数据的Tensor（或者LoDTensor）。
可以这样将Variable对应的Tensor取出，

           var_tensor = fluid.global_scope().var(var_name).get_tensor()

请检查下var_tensor的shape，如果Variable没有被计算到的话，var_tensor应该是空的。

**Comment by maosengshulei** [comment]
`

for i, var in enumerate(policy_vars):

            print(var.name)
            var_tensor = fluid.global_scope().var(var.name).get_tensor()
            print(var_tensor)
`

Error: Tensor not initialized yet when Tensor::place() is called.
  [Hint: holder_ should not be null.] at (/home/teamcity/work/ef54dc8a5b211854/paddle/fluid/framework/tensor.h:134)

似乎var_tensor是空的， 但是为什么不影响`sync_op = fluid.layers.assign(policy_vars[i], target_vars[i])` 这个的执行。而换成这个`sync_op = fluid.layers.assign(decay * target_vars[i] + (1 - decay) * policy_vars[i], target_vars[i])`就会报错。

**Comment by maosengshulei** [comment]
> runtime的时候，policy vars里面的这些Variable是否已经在计算图里面被执行过了，也就是说它们对应的Tensor是否已经有值了？从报错信息来看，应该是这些Variable还没被计算到，他们只在CompileTime的时候被定义了shape和dtype，但是还没有用来存储数据的Tensor（或者LoDTensor）。
> 可以这样将Variable对应的Tensor取出，
> 
> ```
>        var_tensor = fluid.global_scope().var(var_name).get_tensor()
> ```
> 
> 请检查下var_tensor的shape，如果Variable没有被计算到的话，var_tensor应该是空的。

我直接print（var_tensor)报错，这说明tensor是空的吗？但是我的程序应该在计算图中被执行过了啊。 不然为什么直接`fluid.layers.assign(policy_vars[i], target_vars[i])`是正常运行，而换成`fluid.layers.assign(decay * target_vars[i] + (1 - decay) * policy_vars[i], target_vars[i])`就报Error: The Input Variable(X) of assign Op used to determine kernel data type is empty or not LoDTensor or SelectedRows.

**Comment by SunGaofeng** [comment]
> 我直接print（var_tensor)报错，这说明tensor是空的吗？但是我的程序应该在计算图中被执行过了啊。 不然为什么直接`fluid.layers.assign(policy_vars[i], target_vars[i])`是正常运行

如果在计算图中已经被执行过了的话，是可以用来做assign op的input的。我前面的表述不准确，我建议您添加的检查var_tensor = fluid.global_scope().var(var_name).get_tensor()，只在CompileTime才会运行，编译时确实var_tensor是空的。Runtime检查Variable的数据应该用fluid.layers.Print(var)

**Comment by SunGaofeng** [comment]
> > runtime的时候，policy vars里面的这些Variable是否已经在计算图里面被执行过了，也就是说它们对应的Tensor是否已经有值了？从报错信息来看，应该是这些Variable还没被计算到，他们只在CompileTime的时候被定义了shape和dtype，但是还没有用来存储数据的Tensor（或者LoDTensor）。
> > 可以这样将Variable对应的Tensor取出，
> > ```
> >        var_tensor = fluid.global_scope().var(var_name).get_tensor()
> > ```
> > 
> > 
> 换成`fluid.layers.assign(decay * target_vars[i] + (1 - decay) * policy_vars[i], target_vars[i])`就报Error: The Input Variable(X) of assign Op used to determine kernel data type is empty or not LoDTensor or SelectedRows.

这里的问题是不是因为target_vars[i]还没有被计算到，导致assign op的input，也就是 decay * target_vars[i] + (1 - decay) * policy_vars[I] ，它里面第一项没有数据？

**Comment by pentakillg** [comment]
这个问题解决了吗
