### ISSUE TITLE
anakin模型转换错误

### ISSUE THREAD

**Issue by liuliuniu** [PaddlePaddle/Paddle#23496]
不知道anakin的问题是否可以在这里获得解答？
https://github.com/PaddlePaddle/Anakin/issues/543

非常感谢！

**Comment by Shixiaowei02** [comment]
您好，Anakin 仓储从 2019 年 4 月起停止维护，请您使用 Paddle Fluid 或 Paddle Lite，如仍有问题请在这里留言，谢谢！

**Comment by liuliuniu** [comment]
> 您好，Anakin 仓储从 2019 年 4 月起停止维护，请您使用 Paddle Fluid 或 Paddle Lite，如仍有问题请在这里留言，谢谢！

谢谢，不知道paddle lite和anakin有没有做过预测性能对比？

**Comment by liuliuniu** [comment]
尝试了下x2paddle，貌似仍然无法支持string类型的node？
`TFGraphNode`中的`dtype_map`没有string类型，转换时报错
raise Exception("Dtype[{}] not in dtype_map".format(dtype))
Exception: Dtype[7] not in dtype_map

**Comment by jiangjiajun** [comment]
> 尝试了下x2paddle，貌似仍然无法支持string类型的node？
> `TFGraphNode`中的`dtype_map`没有string类型，转换时报错
> raise Exception("Dtype[{}] not in dtype_map".format(dtype))
> Exception: Dtype[7] not in dtype_map

Hello，目前X2Paddle确实不支持string类型的节点， 请问你是转什么模型时遇到了上述的问题的呢

**Comment by Shixiaowei02** [comment]
> > 您好，Anakin 仓储从 2019 年 4 月起停止维护，请您使用 Paddle Fluid 或 Paddle Lite，如仍有问题请在这里留言，谢谢！
> 
> 谢谢，不知道paddle lite和anakin有没有做过预测性能对比？

下列性能是 2019 年 4 月份的历史数据，请参考。

Tesla P4, BatchSize = 1, float32

vgg16   
paddle:10.32ms
paddle-anakin:8.62ms

resnet50    
paddle:7.12ms
paddle-trt:5.06ms
paddle-anakin:3.55ms

googlenet
paddle:6.98ms
paddle-trt:2.78ms
paddle-anakin:4.30ms

mobilenet-v1
paddle:1.98ms
paddle-trt:1.26ms
paddle-anakin:1.40ms

**Comment by liuliuniu** [comment]
> > 尝试了下x2paddle，貌似仍然无法支持string类型的node？
> > `TFGraphNode`中的`dtype_map`没有string类型，转换时报错
> > raise Exception("Dtype[{}] not in dtype_map".format(dtype))
> > Exception: Dtype[7] not in dtype_map
> 
> Hello，目前X2Paddle确实不支持string类型的节点， 请问你是转什么模型时遇到了上述的问题的呢

MLP+Attention的结构，特征中已经把string类型的全部去掉，但是tf会自行添加Assert的结点，其类型是string。

**Comment by jiangjiajun** [comment]
> > > 尝试了下x2paddle，貌似仍然无法支持string类型的node？
> > > `TFGraphNode`中的`dtype_map`没有string类型，转换时报错
> > > raise Exception("Dtype[{}] not in dtype_map".format(dtype))
> > > Exception: Dtype[7] not in dtype_map
> > 
> > 
> > Hello，目前X2Paddle确实不支持string类型的节点， 请问你是转什么模型时遇到了上述的问题的呢
> 
> MLP+Attention的结构，特征中已经把string类型的全部去掉，但是tf会自行添加Assert的结点，其类型是string。

如果方便的话，可以将pb模型提供给我这边来debug一下

**Comment by liuliuniu** [comment]
> > > > 尝试了下x2paddle，貌似仍然无法支持string类型的node？
> > > > `TFGraphNode`中的`dtype_map`没有string类型，转换时报错
> > > > raise Exception("Dtype[{}] not in dtype_map".format(dtype))
> > > > Exception: Dtype[7] not in dtype_map
> > > 
> > > 
> > > Hello，目前X2Paddle确实不支持string类型的节点， 请问你是转什么模型时遇到了上述的问题的呢
> > 
> > 
> > MLP+Attention的结构，特征中已经把string类型的全部去掉，但是tf会自行添加Assert的结点，其类型是string。
> 
> 如果方便的话，可以将pb模型提供给我这边来debug一下

我邮件你，感谢~

**Comment by jiangjiajun** [comment]
> > > > > 尝试了下x2paddle，貌似仍然无法支持string类型的node？
> > > > > `TFGraphNode`中的`dtype_map`没有string类型，转换时报错
> > > > > raise Exception("Dtype[{}] not in dtype_map".format(dtype))
> > > > > Exception: Dtype[7] not in dtype_map
> > > > 
> > > > 
> > > > Hello，目前X2Paddle确实不支持string类型的节点， 请问你是转什么模型时遇到了上述的问题的呢
> > > 
> > > 
> > > MLP+Attention的结构，特征中已经把string类型的全部去掉，但是tf会自行添加Assert的结点，其类型是string。
> > 
> > 
> > 如果方便的话，可以将pb模型提供给我这边来debug一下
> 
> 我邮件你，感谢~

我这边大致看了你的模型，目前X2Paddle还缺少不少对应的OP，短期内还无法支持你这边模型的转换。X2Paddle目前主要支持的是CV模型的转换，其它的模型支持目前也在开发中。

**Comment by liuliuniu** [comment]
> > > > > > 尝试了下x2paddle，貌似仍然无法支持string类型的node？
> > > > > > `TFGraphNode`中的`dtype_map`没有string类型，转换时报错
> > > > > > raise Exception("Dtype[{}] not in dtype_map".format(dtype))
> > > > > > Exception: Dtype[7] not in dtype_map
> > > > > 
> > > > > 
> > > > > Hello，目前X2Paddle确实不支持string类型的节点， 请问你是转什么模型时遇到了上述的问题的呢
> > > > 
> > > > 
> > > > MLP+Attention的结构，特征中已经把string类型的全部去掉，但是tf会自行添加Assert的结点，其类型是string。
> > > 
> > > 
> > > 如果方便的话，可以将pb模型提供给我这边来debug一下
> > 
> > 
> > 我邮件你，感谢~
> 
> 我这边大致看了你的模型，目前X2Paddle还缺少不少对应的OP，短期内还无法支持你这边模型的转换。X2Paddle目前主要支持的是CV模型的转换，其它的模型支持目前也在开发中。

好的，谢谢。
