### ISSUE TITLE
百度搜索找到这个页面无法打开https://www.paddlepaddle.org.cn/documentation/docs/zh/1.6/beginners_guide/index_cn.html

### ISSUE THREAD

**Issue by chajchaj** [PaddlePaddle/Paddle#23490]
百度搜索找到这个页面无法打开https://www.paddlepaddle.org.cn/documentation/docs/zh/1.6/beginners_guide/index_cn.html

**Comment by hutuxian** [comment]
我们的官网在最新版对文档页面进行了一些调整，建议您查看如下最新版本的页面：
https://www.paddlepaddle.org.cn/documentation/docs/zh/1.7/beginners_guide/index_cn.html
