### ISSUE TITLE
使用py_func自定义的python op 可以用作激活函数吗

### ISSUE THREAD

**Issue by hubu-wangpei** [PaddlePaddle/Paddle#23497]
不好意思，我是新手，如题目
使用py_func自定义的python op 可以用作激活函数吗，我想使用一个激活函数，但是已有的激活函数列表里没有

**Comment by SunGaofeng** [comment]
首先明确下您的需求，您是否是写一个类似下面这样的代码

       x2 = fluid.layers.fc(x1, 100, act='relu')

想将其中的'relu'换成您自己定义的py_func op（例如名字: pyfunc_xxx）? 如果是这样的话，是不支持写成  x2 = fluid.layers.fc(x1, 100, act='pyfunc_xxx')。
您可以这样子来实现计算过程：

       x2 = fluid.layers.fc(x1, 100, act=None)
       fluid.layers.py_func(func=pyfunc_xxx, x=[x2], out=output)

**Comment by hubu-wangpei** [comment]
感谢
