### ISSUE TITLE
报错InvalidArgumentError: Tensor holds the wrong type

### ISSUE THREAD

**Issue by hubu-wangpei** [PaddlePaddle/Paddle#23504]
以下代码使用fluid.layers.softmax_with_cross_entropy(logits, label)，报错
```python
                x_data, y_data = data
                #print(x_data,y_data)
                img = fluid.dygraph.to_variable(x_data)
                label = fluid.dygraph.to_variable(y_data)
                label=fluid.layers.cast(label,np.int64)
                label=fluid.one_hot(label,2)
                # 运行模型前向计算，得到预测值
                logits = model(img)
                print(logits)
                # 进行loss计算
                loss = fluid.layers.softmax_with_cross_entropy(logits, label)
```
报错信息
>Error Message Summary:----------------------
InvalidArgumentError: Tensor holds the wrong type, it holds float, but desires to be int64_t.
  [Hint: Expected valid == true, but received valid:0 != true:1.] at (/paddle/paddle/fluid/framework/tensor_impl.h:33)

softmax_with_cross_entropy调用参数，感觉没问题啊
![图片](https://user-images.githubusercontent.com/45394242/78552353-efced500-7839-11ea-926b-4e677a42179e.png)

**Comment by sandyhouse** [comment]
如果loss = fluid.layers.softmax_with_cross_entropy(logits, label)这样调用的话，请却掉label=fluid.one_hot(label,2)这句。否则的话，可以设置fluid.layers.softmax_with_cross_entropy的soft_label=True

**Comment by hubu-wangpei** [comment]
> 
> 
> 如果loss = fluid.layers.softmax_with_cross_entropy(logits, label)这样调用的话，请却掉label=fluid.one_hot(label,2)这句。否则的话，可以设置fluid.layers.softmax_with_cross_entropy的soft_label=True

根据您的建议修改后，不会报错了，但是loss为0。我这是一个二分类的问题，label的shape为[batch_size,1]
