### ISSUE TITLE
Use default RDMA library path to build paddle with RDMA support

### ISSUE THREAD

**Issue by typhoonzero** [PaddlePaddle/Paddle#2351]
Currently in `cmake/rdma.cmake` hard coded RDMA library paths. We need to make it more general, and port the dependencies to the repo.

**Comment by Yancey1989** [comment]
Hi @typhoonzero , I see #2352 has already merged, can we close this issue?

**Comment by typhoonzero** [comment]
RDMA support needs more work to be able to build paddle with full support.
