### ISSUE TITLE
希望paddle可以集成更多常用的算法

### ISSUE THREAD

**Issue by DrRyanHuang** [PaddlePaddle/Paddle#23553]
在`tensorflow`中收编了很多常用的算法，如SSIM等。

昨日，想用一个常数卷积核对图片做相关操作，好麻烦，先得 `NumpyArrayInitializer`，然后`ParamAttr`, 最后`Embedding`，有点儿麻烦，希望，paddle也可以集成一些常用的算法

**Comment by ceci3** [comment]
收到，感谢反馈~
