### ISSUE TITLE
Please add the sdist package on PyPI

### ISSUE THREAD

**Issue by marcelotrevisani** [PaddlePaddle/Paddle#23569]
Please add the sdist package on PyPI

**Comment by ceci3** [comment]
Sorry, I'm wondering why do you need this kind of package?

**Comment by marcelotrevisani** [comment]
a lot of package managers need the source distribution to compile, manage and create the packages.
They usually do not use the wheels, (some linux distributions also need it,) such as debian (apt packages), conda, etc..
