### ISSUE TITLE
预测时候CPU跑的结果与GPU跑的结果完全不同

### ISSUE THREAD

**Issue by yzhw9981** [PaddlePaddle/Paddle#23578]
使用python预测，CPU跑的结果与GPU跑的结果完全不同
paddle版本171
GPU环境为paddlecloud默认的GPU环境配置
CPU环境为paddlecloud默认的CPU环境配置
均为单机单卡(单CPU）

为了排除程序上可能潜在的问题，使用训练模式，置lr=0.0，batchsize为相同的值，load预训练好的模型文件后，step1的得出的softmax后向量GPU与CPU有巨大的差异，CPU结果看起来完全是错的，GPU结果正常。

附代码初始化环境的部分。具体业务代码如果需要后续通过hi的方式提供
def main(args):
    config = PageTransformerConfig(args.config_path)
    config.print_config()

    if args.use_cuda:
        #gpu
        dev_list = fluid.cuda_places()
        place = dev_list[0]
        dev_count = len(dev_list)
    else:
        #cpu
        place = fluid.CPUPlace()
        dev_count = int(os.environ.get('CPU_NUM', multiprocessing.cpu_count()))
    exe = fluid.Executor(place)
    trainers = 1
    trainer_id = 0
    if args.is_distributed and args.use_cuda:
        trainers = int(os.getenv("PADDLE_TRAINERS_NUM", "0"))
        trainer_id = int(os.getenv("PADDLE_TRAINER_ID", "0"))

    #declare pyreader
    reader = PageTransformerReader(
        max_seq_len=args.max_seq_len,
        random_seed=args.random_seed)

    if not (args.do_train or args.do_val or args.do_test):
        raise ValueError("For args `do_train`, `do_val` and `do_test`, at "
                         "least one of them must be True.")

    startup_prog = fluid.Program()
    if args.random_seed is not None:
        startup_prog.random_seed = args.random_seed

**Comment by ceci3** [comment]
你好，`step1的得出的softmax后向量GPU与CPU有巨大的差异，`这句话的意识是softmax这个操作之前的值cpu和gpu是一样的，经过一个softmax之后不同了吗？

**Comment by yzhw9981** [comment]
刚才我详细debug了下，在softmax前就有问题了。在输入层，经过一层FC后，CPU上的值有了nan，但是gpu上的值正常

**Comment by yzhw9981** [comment]
#add struct features                                                                                                                                              
        struct_features = fluid.layers.Print(struct_features, message="ori_struct_feature", summarize=-1)                                                                 
        struct_emb = self._layer_norm("struct_emb", fluid.layers.fc(                                                                                                      
                input=struct_features,                                                                                                                                    
                size=self._emb_size,                                                                                                                                      
                act=self._hidden_act,                                                                                                                                     
                num_flatten_dims=2,                                                                                                                                       
                param_attr=fluid.ParamAttr(                                                                                                                               
                    name="struct_fc.w", initializer=self._param_initializer),                                                                                             
                bias_attr=fluid.ParamAttr(                                                                                                                                
                    name="struct_fc.b", initializer=fluid.initializer.Constant(0.))))    

如代码，第一个Print的地方没问题，过了FC之后，isnan输出1

**Comment by yzhw9981** [comment]
def _layer_norm(self, name, input_emb):                                                                                                                               
        fluid.layers.Print(fluid.layers.has_nan(input_emb), message=name+"_nan_test")

**Comment by ceci3** [comment]
fc的话，cpu和gpu调用的都是同一个库，如果cpu出nan，但是gpu没有，那有可能是gpu上对nan之类的值做了什么保护机制。是只有nan那个值不同还是所有的值都不同？

**Comment by yzhw9981** [comment]
这个fc在输入层，出了nan后续肯定都有问题了。这个有短线兼容的方案么，不然我们GPU训出的模型无法在CPU机器上上线呢

**Comment by ceci3** [comment]
请问下cpu和gpu中fc的输入数据是一样的吗？

**Comment by qingqing01** [comment]
@yzhw9981 一般FC的GPU和CPU计算相等的，一个调用cublas，一个调用cblas。不然Paddle框架的单测都过不了。能否把`struct_fc.w`和 `struct_fc.b`都打印下统计值。

```
print('struct_fc.w ', np.sum(np.abs(fluid.global_scope().find_var('struct_fc.w').get_tensor())))
print('struct_fc.b ', np.sum(np.abs(fluid.global_scope().find_var('struct_fc.b').get_tensor())))
```

`struct_features` 能否全部fetch出来，打印下统计值，看下。以及 `self._hidden_act` 是啥？

**Comment by yzhw9981** [comment]
看起来GPU上struct_fc.w已经nan了，bias正常。
激活函数用的relu

**Comment by yzhw9981** [comment]
多谢提醒，问题已经解决。仔细检查数据定位，发现有脏数据（训练数据中有nan）导致了出错。

**Comment by ceci3** [comment]
那这个issue就先关掉了，有别的问题可以在打开。
