### ISSUE TITLE
dygraph模式下，加载预训练模型参数load_vars时出错

### ISSUE THREAD

**Issue by duwenzhao** [PaddlePaddle/Paddle#23602]
- 版本、环境信息：
    1）PaddlePaddle版本：1.7.0
    2）GPU：v100
    4）系统环境：Python3.7
- 训练信息
    1）单机/单卡
    2）显存16GB
  从https://github.com/PaddlePaddle 中下载的预训练模型参数是conv1_1_weights 类型，想在动态图模式下加载这种预训练参数，使用load_vars加载：
src_pretrain_model_path = '/home/aistudio/vgg16/'
def if_exist(var):
    path = os.path.join(src_pretrain_model_path, var.name)
    exist = os.path.exists(path) 
    return exist
with fluid.dygraph.guard(place = fluid.CUDAPlace(0)):
    model = CNN()
    fluid.io.load_vars(executor=fluid.Executor(fluid.CUDAPlace(0)),dirname=src_pretrain_model_path, predicate=if_exist)
报错：
AssertionError: We don't support list_vars in Dygraph mode。
如果使用load_dygraph加载参数，只能加载***.pdparams文件，不能加载类似conv1_1_weights 类型参数。
请问如何在动态图模式下加载这种预训练模型参数，如果使用load_vars，executor怎么设置？

**Comment by FDInSky** [comment]
可以将原先的weight转成numpy，再通过load_dict进行加载

**Comment by duwenzhao** [comment]
使用python的open读取weight，应该从第几个字节开始读取？load_dict是paddle的API吗？在paddle的API中没有搜到load_dict.有这方面的参考代码的地址吗？如果能给个例子最好。@FDInSky
