### ISSUE TITLE
Feel confused about naming rules of variables and functions in python

### ISSUE THREAD

**Issue by pkuyym** [PaddlePaddle/Paddle#2360]
As we all know，functions or variables named like ```__init__、__del__```  etc. are built-in entities in python. Generally speaking, it's not a good idea to name our own functions or variables at the same way. But I find some python codes disobey such rules, is that allowed in paddle's naming rules?

For example, code snippet in python/paddle/v2/optimizer.py:

```python
def __create_local_updater__(self):
        return swig_api.ParameterUpdater.createLocalUpdater(self.__opt_conf__)

def __create_remote_updater__(self, pass_num, use_sparse_updater):
        return swig_api.ParameterUpdater.createRemoteUpdater(
                    self.__opt_conf__, pass_num, use_sparse_updater)
```

**Comment by Yancey1989** [comment]
Hi @pkuyym , Thanks for your attention the source code, I think the name prefixed with the underscore is not only treated as `built-in` entities, but also a private API:

From [Python class module](https://docs.python.org/2/tutorial/classes.html#private-variables-and-class-local-references) document:
> “Private” instance variables that cannot be accessed except from inside an object don’t exist in Python. However, there is a convention that is followed by most Python code: a name prefixed with an underscore (e.g. _spam) should be treated as a non-public part of the API (whether it is a function, a method or a data member). It should be considered an implementation detail and subject to change without notice.

**Comment by pkuyym** [comment]
@Yancey1989 I see. To make variables or functions private, we can just name them like ``` _XX ``` or ``` __XX ```  instead of ``` __XX__ ``` to avoid conflicts with ``` built-in ``` entities. As I know, it's not recommended to name our own variables or functions like ``` __XX__ ```.

**Comment by jacquesqiao** [comment]
http://google.github.io/styleguide/pyguide.html#Nested/Local/Inner_Classes_and_Functions

according to google python code style, our style should be changed. The recommendation style for internal function/variable is `_lower_with_under (protected) or __lower_with_under (private)`

**Comment by Yancey1989** [comment]
Thanks @pkuyym and @jacquesqiao ,  I see, this suggestion is very useful, I'll fix this ASAP.
