### ISSUE TITLE
使用ernie进行finetune时报错

### ISSUE THREAD

**Issue by LMXKO** [PaddlePaddle/Paddle#23612]
- 版本、环境信息：
    1）PaddlePaddle版本：1.7
    2）CPU：32个 Intel(R) Xeon(R) Silver 4110 CPU @ 2.10GHz
    3）GPU：无GPU
    4）系统环境：Centos，Python 2.7
- 模型信息
    1）模型名称 ：ernie
    2）使用数据集名称： dureader
    3）使用算法名称 ：
    4）模型链接：https://ernie.bj.bcebos.com/ERNIE_1.0_max-len-512.tar.gz
- 复现信息：
准备好dureader格式的数据，进行相应的路径配置
运行script/zh_task/ernie_large/run_drcd.sh
报错如下：
![image](https://user-images.githubusercontent.com/35209678/78753755-f760bc00-79a8-11ea-80cb-de636ae35422.png)

- 问题描述：请详细描述您的问题，同步贴出报错信息、日志/代码关键片段

**Comment by FDInSky** [comment]
你好，已经找相关同学帮你排查

**Comment by FDInSky** [comment]
你好，根据你的报错信息，检查一下是不是batch size过大，导致内存爆掉？
