### ISSUE TITLE
动态图构建的网络有类似于save_inference_model的API，用于保存模型，然后预测的吗

### ISSUE THREAD

**Issue by hubu-wangpei** [PaddlePaddle/Paddle#23655]
如题，用动态图构建的网络，save_inference_model好像只能用于保存静态图模型？fluid.save_dygraph只能用于恢复训练？请问如何保存动态图构建的网络，然后可以部署在AI Studio的在线服务上

**Comment by DDDivano** [comment]
https://www.paddlepaddle.org.cn/documentation/docs/zh/api_cn/dygraph_cn/TracedLayer_cn.html#tracedlayer 可以用动态图转静态图，然后使用c++预测库进行预测

**Comment by hubu-wangpei** [comment]
> 
> 
> https://www.paddlepaddle.org.cn/documentation/docs/zh/api_cn/dygraph_cn/TracedLayer_cn.html#tracedlayer 可以用动态图转静态图，然后使用c++预测库进行预测
感谢
