### ISSUE TITLE
yapf version different 

### ISSUE THREAD

**Issue by pengwangucla** [PaddlePaddle/Paddle#2368]
In file python/paddle/trainer_config_helpers/tests/configs/test_config_parser_for_non_file_config.py

The code 

` exec (cmdstr, globals, locals)
`

```
CRLF end-lines remover...............................(no files to check)Skipped
yapf.....................................................................Failed
hookid: yapf
```

In my version, it does not need space after `exec`,  but when submit PR, it report error that there needs a space after `exec`

Is this due to the version difference between my local pre-commit and the online one ? 

Can someone indicate the precommit version online ? 

@gangliao

**Comment by Yancey1989** [comment]
Please trying to execute the command `pre-commit autoupdate` under the Paddle repo directory.
For my local version, it need a space after `exec`.

**Comment by gangliao** [comment]
No update, so I close this issue. New comments are welcome.
