### ISSUE TITLE
paddle 有meta learning 的例子么？

### ISSUE THREAD

**Issue by zle1992** [PaddlePaddle/Paddle#23699]
https://github.com/Feiyang/MetaEmbedding/blob/master/code/example-MovieLens.ipynb
https://github.com/hoyeoplee/MeLU/blob/master/MeLU.py
这是2篇meta learning的代码实现，想知道paddle 有木有类似的例子实现gradient by gradient。

**Comment by zhaoyuchen2018** [comment]
API接口参考这个: https://www.paddlepaddle.org.cn/documentation/docs/zh/api_cn/fluid_cn/gradients_cn.html#gradients.
example：https://github.com/PaddlePaddle/models/blob/develop/PaddleCV/gan/trainer/StarGAN.py#L150

**Comment by zle1992** [comment]
> https://www.paddlepaddle.org.cn/documentation/docs/zh/api_cn/fluid_cn/gradients_cn.html#gradients

![image](https://user-images.githubusercontent.com/16644339/96102816-8840c300-0f09-11eb-8e6f-f81c6ccb4787.png)

参考例子，直接相加不行嘛？
