### ISSUE TITLE
paddledetection如何评估COCO test集

### ISSUE THREAD

**Issue by zhengzhe97** [PaddlePaddle/Paddle#23697]

**Comment by jerrywgz** [comment]
paddledetection默认都是在coco val2017上进行评估的，如果想在test集上测试可以直接在reader的配置文件中设置image_dir和anno_path，具体可以参考https://github.com/PaddlePaddle/PaddleDetection/blob/release/0.2/configs/faster_reader.yml#L39 这里的链接

**Comment by jerrywgz** [comment]
另外，PaddleDetection的相关问题可以在https://github.com/PaddlePaddle/PaddleDetection/issues 里提问，我们每天会有专门负责检测问题的值班同学跟进
