### ISSUE TITLE
cross_entropy(ignore_index)和mean组合使用结果不正确

### ISSUE THREAD

**Issue by kinghuin** [PaddlePaddle/Paddle#23708]
用户反馈组合使用cross_entropy(ignore_index)和sum求出来的结果是正确的
但和 mean组合起来，求出来的结果不正确，
原因可能是cross_entropy的维度依然包括ignore_index的位置，导致mean的分母不正确

![image](https://user-images.githubusercontent.com/11913168/78959017-49761e80-7b1c-11ea-863f-00121a423281.png)

目前是建议用户fetch loss之后在python端自己求mean

**Comment by SunGaofeng** [comment]
这么做是否可以满足需求？
1、cross_entorpy + sum
2、求出label不为ignore index的元素个数 
然后用这两者相除

**Comment by kinghuin** [comment]
这样子就是用户使用cross_entropy(ignore_index)后的后处理得自己注意一点了
