### ISSUE TITLE
PaddleDetection 预测使用trt_fp32、trt_fp16、trt_int8时出现错误

### ISSUE THREAD

**Issue by 606BlueStar** [PaddlePaddle/Paddle#23721]
- 版本、环境信息：
    1）PaddlePaddle版本：1.7.1
    3）GPU：CUDA10.0和CUDNN7.6.5 ; TensorRT:'6.0.1.5'
    4）系统环境：ubuntu18.04,
-预测信息
    1）C++预测：请您提供预测库安装包的版本信息，及其中的version.txt文件
    4）预测方式：https://github.com/PaddlePaddle/PaddleDetection/blob/release/0.2/docs/advanced_tutorials/inference/INFERENCE.md
- 复现信息：使用trt_fp32、trt_fp16、trt_int8模式预测模型时，出现错误，使用fluid模式预测没有问题；错误信息：
Traceback (most recent call last):
  File "tools/paddle_infer.py", line 290, in <module>
    detect_ball = inference_basketball_detection_faster()
  File "tools/paddle_infer.py", line 264, in inference_basketball_detection_faster
    demo = PaddleDetection(FLAGS)
  File "tools/paddle_infer.py", line 223, in __init__
    self.predict = fluid.core.create_paddle_predictor(config)
paddle.fluid.core_avx.EnforceNotMet: 

--------------------------------------------
C++ Call Stacks (More useful to developers):
--------------------------------------------
0   std::string paddle::platform::GetTraceBackString<char const*>(char const*&&, char const*, int)
1   paddle::platform::EnforceNotMet::EnforceNotMet(std::__exception_ptr::exception_ptr, char const*, int)
2   paddle::framework::ir::PassRegistry::Get(std::string const&) const
3   paddle::inference::analysis::IRPassManager::CreatePasses(paddle::inference::analysis::Argument*, std::vector<std::string, std::allocator<std::string> > const&)
4   paddle::inference::analysis::IRPassManager::IRPassManager(paddle::inference::analysis::Argument*)
5   paddle::inference::analysis::IrAnalysisPass::RunImpl(paddle::inference::analysis::Argument*)
6   paddle::inference::analysis::Analyzer::RunAnalysis(paddle::inference::analysis::Argument*)
7   paddle::AnalysisPredictor::OptimizeInferenceProgram()
8   paddle::AnalysisPredictor::PrepareProgram(std::shared_ptr<paddle::framework::ProgramDesc> const&)
9   paddle::AnalysisPredictor::Init(std::shared_ptr<paddle::framework::Scope> const&, std::shared_ptr<paddle::framework::ProgramDesc> const&)
10  std::unique_ptr<paddle::PaddlePredictor, std::default_delete<paddle::PaddlePredictor> > paddle::CreatePaddlePredictor<paddle::AnalysisConfig, (paddle::PaddleEngineKind)2>(paddle::AnalysisConfig const&)
11  std::unique_ptr<paddle::PaddlePredictor, std::default_delete<paddle::PaddlePredictor> > paddle::CreatePaddlePredictor<paddle::AnalysisConfig>(paddle::AnalysisConfig const&)

----------------------
Error Message Summary:
----------------------
Error: Pass tensorrt_subgraph_pass has not been registered at (/paddle/paddle/fluid/framework/ir/pass.h:170)

**Comment by NHZlX** [comment]
依赖的paddle inference lib不具有trt 子图功能。。

**Comment by 606BlueStar** [comment]
https://github.com/PaddlePaddle/PaddleDetection/blob/release/0.2/docs/advanced_tutorials/inference/INFERENCE.md
这里面不是写了可以吗？

**Comment by 606BlueStar** [comment]
> 依赖的paddle inference lib不具有trt 子图功能。。

https://github.com/PaddlePaddle/PaddleDetection/blob/release/0.2/docs/advanced_tutorials/inference/INFERENCE.md
这里面不是写了可以吗？

**Comment by OliverLPH** [comment]
Paddle python api如果要调用trt，需要自己编译

**Comment by NHZlX** [comment]
PaddleDetection预测依赖Paddle Inference 预测lib。 这个lib是在哪里下载的呢

**Comment by 606BlueStar** [comment]
> Paddle python api如果要调用trt，需要自己编译

请问有教程吗？麻烦您发一下，感谢🙏

**Comment by 606BlueStar** [comment]
> Paddle python api如果要调用trt，需要

> PaddleDetection预测依赖Paddle Inference 预测lib。 这个lib是在哪里下载的呢

请问要使用TensorRT，是要在这个教程进行编译吗？
https://www.bookstack.cn/read/paddlepaddle-v1.5/e8703a264212c003.md

**Comment by jeng1220** [comment]
@606BlueStar ,
After paddlepaddle-v1.8, its python API supports TensorRT, so please use v1.8.
