### ISSUE TITLE
动态图模型转静态图不能指定模型文件与参数文件

### ISSUE THREAD

**Issue by L-lei** [PaddlePaddle/Paddle#23725]
版本：
Name: paddlepaddle
Version: 1.7.1

动态图转静态图中不能指定模型文件与参数文件，转换后的文件目录下有很多权重文件
TracedLayer.save_inference_model(self, dirname, feed=None, fetch=None)

fluid.io.save_inference_model(
                dirname=dirname,
                feeded_var_names=feeded_var_names,
                target_vars=target_vars,
                executor=self._exe,
                main_program=self._program.clone())

**Comment by liupluswei** [comment]
感谢反馈，我们会内部讨论这个需求，然后根据优先级安排排期开发，谢谢
