### ISSUE TITLE
Enable resume training from a pre-trained model

### ISSUE THREAD

**Issue by pkuyym** [PaddlePaddle/Paddle#2372]
Currently, paddle only save parts of model leaving Ada/Momentum dropped. However, these information is necessary if we want to resume training from a pre-trained model.

**Comment by lcy-seso** [comment]
This problem has been discussed before. We are considering it. Currently, saving history information for each optimization algorithm may be not very simple , modification should be made to each algorithm. 

Currently, you can set a short saving period, and initialize the training process by the last saved model. This do lead to a decline of learning performance at the beginning when restarting the training process but may not cause a  serious decline.
