### ISSUE TITLE
`fluid.layers.flatten`不能添加到`Sequential`

### ISSUE THREAD

**Issue by DrRyanHuang** [PaddlePaddle/Paddle#23735]
`python3.6`
`paddle1.7`

`fluid.layers.flatten`不能像`tf.Keras`一样添加到`Sequential`中，还是有别的方法添加？

`Sequential`只能添加到动态图的类吗？

**Comment by liupluswei** [comment]
Sequential暂时还无法添加非Layer类型的API，我们会记录您的需求，尽快完善动态图的相关功能

**Comment by ipyffor** [comment]
> `python3.6`
> `paddle1.7`
> 
> `fluid.layers.flatten`不能像`tf.Keras`一样添加到`Sequential`中，还是有别的方法添加？
> 
> `Sequential`只能添加到动态图的类吗？

可以自己实现这个类，就可以加进去了

**Comment by ipyffor** [comment]
> `python3.6`
> `paddle1.7`
> 
> `fluid.layers.flatten`不能像`tf.Keras`一样添加到`Sequential`中，还是有别的方法添加？
> 
> `Sequential`只能添加到动态图的类吗？

和实现网络是一样的
