### ISSUE TITLE
PaddlePaddle Hub

### ISSUE THREAD

**Issue by qo4on** [PaddlePaddle/Paddle#23739]
Does PaddlePaddle have a models hub (like torch hub or tensorflow hub)? I'm looking for a text2mel model such as FastSpeech or Tacotron2.

**Comment by liupluswei** [comment]
Yes, we have a models hub: https://www.paddlepaddle.org.cn/hub. But speech models are not shipped yet.

**Comment by qo4on** [comment]
You have some [mel2wav speach models](https://github.com/PaddlePaddle/Parakeet#pre-trained-models-and-audio-samples). But I didn't find text2mel.
