### ISSUE TITLE
编译windows预测库报错

### ISSUE THREAD

**Issue by HoyTiger** [PaddlePaddle/Paddle#23760]
- 标题：编译windows预测库报错
- 版本、环境信息：
    1）PaddlePaddle版本：1.7
    2）CPU/GPU：CUDA10.2 cudnn 7.5
编译windows预测库报错
![image](https://user-images.githubusercontent.com/42536260/79046300-bf74a580-7c42-11ea-9d87-7064c82aa6b4.png)

到相应目录下确实没找到error_codes.pb.h等文件

**Comment by liupluswei** [comment]
请问你是通过Paddle源码编译预测库，还是集成我们编译好的预测库呢？  如果是通过源码编译，可以提供一下你的操作步骤吗？我这边好复现一下

**Comment by HoyTiger** [comment]
> 请问你是通过Paddle源码编译预测库，还是集成我们编译号的预测库呢？ 如果是通过源码编译，可以提供一下你的操作步骤吗？我这边好复现一下

你好，这个问题我已经解决了。我使用的是vs 2019编译预测库更改成2015就没问题了。

**Comment by liupluswei** [comment]
> > 请问你是通过Paddle源码编译预测库，还是集成我们编译号的预测库呢？ 如果是通过源码编译，可以提供一下你的操作步骤吗？我这边好复现一下
> 
> 你好，这个问题我已经解决了。我使用的是vs 2019编译预测库更改成2015就没问题了。

好的，目前Paddle源码编译并不支持vs2019， 支持vs2017和vs2015

**Comment by patrickwf** [comment]
请问，支持vs2017 x86编译吗？选择mkl选项，会报找不到mkldnn.hpp，版本是release/2.0-rc1
