### ISSUE TITLE
感觉文档不太成熟，然后网站的搜索引擎不好用

### ISSUE THREAD

**Issue by wxl1351641822** [PaddlePaddle/Paddle#23761]
http://www.paddlepaddle.org/
这个的搜索引擎，不能搜api……感觉很难用

**Comment by xjqbest** [comment]
请问是指哪个api呢

**Comment by wxl1351641822** [comment]
![image](https://user-images.githubusercontent.com/42665925/79183330-c3234a80-7e43-11ea-8102-08382e026bdd.png)
就这个搜索引擎，哪个api都很难找。
之前我找过lod_level,想找可以更改它的，找不到。
还找过分割variable?
还找了啥我也不记得……反正印象里没有找到过的。
一己之见，也可能其他人用的很顺手。
在这个搜索引擎里，他名字一样的还算好找，但与其他平台名字不一样的，我也不知道我能搜啥，我也找不到……这种感觉吧。
emmm……我还想找seed，有没有像pytorch那种全局固定seed的api？

**Comment by wxl1351641822** [comment]
![image](https://user-images.githubusercontent.com/42665925/79183629-8c016900-7e44-11ea-8fd7-7c221a701214.png)
你看……就这样。

**Comment by xjqbest** [comment]
收到～ 十分感谢。正是用户的建议，才会让paddle越来越来好用。

**Comment by xjqbest** [comment]
如果你有其他具体case，也可以回复在这里，我这边也会集中反馈给相关人员。

**Comment by wxl1351641822** [comment]
![image](https://user-images.githubusercontent.com/42665925/79715431-48a47000-8306-11ea-9405-abb39f486529.png)
