### ISSUE TITLE
如何在一个program中实现多个minimize操作

### ISSUE THREAD

**Issue by saTan-Y** [PaddlePaddle/Paddle#23778]
对于由两个子网络组成的模型，loss是两个子网络输出之和，想在训练中使用两个optimizer，在一次训练中更新两个optimizer（针对不同参数），求问怎么在一个program中实现两个optimizer的minimize操作？

**Comment by Shixiaowei02** [comment]
PaddlePaddle/models 中有一些任务，如图像检测、分类，里面都用到了多个 loss，可以参考一下，一般用法是将多个 loss 加到一起再求 minimize。例如：

https://github.com/PaddlePaddle/models/blob/6e12f8a1e734ad2f01169687fe60e95ba60652c0/PaddleCV/image_classification/train.py#L247

参见 issue: https://github.com/PaddlePaddle/Paddle/issues/19055

**Comment by saTan-Y** [comment]
> PaddlePaddle/models 中有一些任务，如图像检测、分类，里面都用到了多个 loss，可以参考一下，一般用法是将多个 loss 加到一起再求 minimize。例如：
> 
> https://github.com/PaddlePaddle/models/blob/6e12f8a1e734ad2f01169687fe60e95ba60652c0/PaddleCV/image_classification/train.py#L247
> 
> 参见 issue: #19055

loss是相加的。具体结构是这样的，整个结构由2个子网络构成，loss是2个子网络的输入之和，但我想对这两个子网络用不同的optimizer去更新各自的权重。需要minimize的loss只有1个，但我需要2个optimizer去分别更新各自网络的参数，这个有解决的方法吗？

**Comment by saTan-Y** [comment]
> PaddlePaddle/models 中有一些任务，如图像检测、分类，里面都用到了多个 loss，可以参考一下，一般用法是将多个 loss 加到一起再求 minimize。例如：
> 
> https://github.com/PaddlePaddle/models/blob/6e12f8a1e734ad2f01169687fe60e95ba60652c0/PaddleCV/image_classification/train.py#L247
> 
> 参见 issue: #19055

这个issue我看过，我的loss确实是相加的，但我需要不同的optimzier去更新不同的参数，和这个issue的情况不太一样

**Comment by zhiqiu** [comment]
可以试试直接对相加前的两个loss分别进行minimize？

**Comment by saTan-Y** [comment]
> 可以试试直接对相加前的两个loss分别进行minimize？

一个program里面不能minimize2次，所以来求问

**Comment by zhiqiu** [comment]
> > 可以试试直接对相加前的两个loss分别进行minimize？
> 
> 一个program里面不能minimize2次，所以来求问

调用两次有遇到什么问题或者报错吗？

**Comment by saTan-Y** [comment]
> > > 可以试试直接对相加前的两个loss分别进行minimize？
> > 
> > 
> > 一个program里面不能minimize2次，所以来求问
> 
> 调用两次有遇到什么问题或者报错吗？

又试了一下是可以的

**Comment by zhiqiu** [comment]
> > > > 可以试试直接对相加前的两个loss分别进行minimize？
> > > 
> > > 
> > > 一个program里面不能minimize2次，所以来求问
> > 
> > 
> > 调用两次有遇到什么问题或者报错吗？
> 
> 又试了一下是可以的

嗯嗯，好的

**Comment by saTan-Y** [comment]
> > > > > 可以试试直接对相加前的两个loss分别进行minimize？
> > > > 
> > > > 
> > > > 一个program里面不能minimize2次，所以来求问
> > > 
> > > 
> > > 调用两次有遇到什么问题或者报错吗？
> > 
> > 
> > 又试了一下是可以的
> 
> 嗯嗯，好的

但是保存模型的时候出现了问题。我尝试了2个优化器都用adagrad，如果先调用优化器1，后调用优化器2，优化器1里面的moment参数就没有保存；如果先调用优化器2，后调用优化器1，优化器2的moment参数就没有保存。想问下是什么情况？

**Comment by zhiqiu** [comment]
> > > > > > 可以试试直接对相加前的两个loss分别进行minimize？
> > > > > 
> > > > > 
> > > > > 一个program里面不能minimize2次，所以来求问
> > > > 
> > > > 
> > > > 调用两次有遇到什么问题或者报错吗？
> > > 
> > > 
> > > 又试了一下是可以的
> > 
> > 
> > 嗯嗯，好的
> 
> 但是保存模型的时候出现了问题。我尝试了2个优化器都用adagrad，如果先调用优化器1，后调用优化器2，优化器1里面的moment参数就没有保存；如果先调用优化器2，后调用优化器1，优化器2的moment参数就没有保存。想问下是什么情况？

保存模型用的哪个接口？

**Comment by saTan-Y** [comment]
> > > > > > > 可以试试直接对相加前的两个loss分别进行minimize？
> > > > > > 
> > > > > > 
> > > > > > 一个program里面不能minimize2次，所以来求问
> > > > > 
> > > > > 
> > > > > 调用两次有遇到什么问题或者报错吗？
> > > > 
> > > > 
> > > > 又试了一下是可以的
> > > 
> > > 
> > > 嗯嗯，好的
> > 
> > 
> > 但是保存模型的时候出现了问题。我尝试了2个优化器都用adagrad，如果先调用优化器1，后调用优化器2，优化器1里面的moment参数就没有保存；如果先调用优化器2，后调用优化器1，优化器2的moment参数就没有保存。想问下是什么情况？
> 
> 保存模型用的哪个接口？

fleet.save_inference_model

**Comment by saTan-Y** [comment]
> > > > > > > 可以试试直接对相加前的两个loss分别进行minimize？
> > > > > > 
> > > > > > 
> > > > > > 一个program里面不能minimize2次，所以来求问
> > > > > 
> > > > > 
> > > > > 调用两次有遇到什么问题或者报错吗？
> > > > 
> > > > 
> > > > 又试了一下是可以的
> > > 
> > > 
> > > 嗯嗯，好的
> > 
> > 
> > 但是保存模型的时候出现了问题。我尝试了2个优化器都用adagrad，如果先调用优化器1，后调用优化器2，优化器1里面的moment参数就没有保存；如果先调用优化器2，后调用优化器1，优化器2的moment参数就没有保存。想问下是什么情况？
> 
> 保存模型用的哪个接口？

by the way，我想确认下paddle支持一个program下的多个optimizer操作吗？

**Comment by zhiqiu** [comment]
> > > > > > > > 可以试试直接对相加前的两个loss分别进行minimize？
> > > > > > > 
> > > > > > > 
> > > > > > > 一个program里面不能minimize2次，所以来求问
> > > > > > 
> > > > > > 
> > > > > > 调用两次有遇到什么问题或者报错吗？
> > > > > 
> > > > > 
> > > > > 又试了一下是可以的
> > > > 
> > > > 
> > > > 嗯嗯，好的
> > > 
> > > 
> > > 但是保存模型的时候出现了问题。我尝试了2个优化器都用adagrad，如果先调用优化器1，后调用优化器2，优化器1里面的moment参数就没有保存；如果先调用优化器2，后调用优化器1，优化器2的moment参数就没有保存。想问下是什么情况？
> > 
> > 
> > 保存模型用的哪个接口？
> 
> fleet.save_inference_model
这个接口会对网络进行裁剪，只会保留与指定的feed和target有关的网络部分，你设置两个loss都作为target了吗？

**Comment by saTan-Y** [comment]
> > > > > > > > > 可以试试直接对相加前的两个loss分别进行minimize？
> > > > > > > > 
> > > > > > > > 
> > > > > > > > 一个program里面不能minimize2次，所以来求问
> > > > > > > 
> > > > > > > 
> > > > > > > 调用两次有遇到什么问题或者报错吗？
> > > > > > 
> > > > > > 
> > > > > > 又试了一下是可以的
> > > > > 
> > > > > 
> > > > > 嗯嗯，好的
> > > > 
> > > > 
> > > > 但是保存模型的时候出现了问题。我尝试了2个优化器都用adagrad，如果先调用优化器1，后调用优化器2，优化器1里面的moment参数就没有保存；如果先调用优化器2，后调用优化器1，优化器2的moment参数就没有保存。想问下是什么情况？
> > > 
> > > 
> > > 保存模型用的哪个接口？
> > 
> > 
> > fleet.save_inference_model
> > 这个接口会对网络进行裁剪，只会保留与指定的feed和target有关的网络部分，你设置两个loss都作为target了吗？

我是把两个loss的和作为target的，如果这样的话，是不是用两个优化器的话裁剪注定会有问题？

**Comment by zhiqiu** [comment]
hi, 请把你的code发出来看下

**Comment by saTan-Y** [comment]
> hi, 请把你的code发出来看下

简化了一下主干代码，如下
###input1 为子网络1的输入，input2位子网络2的输入
def model():
	data_list = []
	data.append(input1)
	data.append(input2)
	data.append(label)
	predict1 = fluid.layers.fc(input=input1, size=1, act=None, param_attr=fluid.ParamAttr(name="input1_weight"), bias_attr=fluid.ParamAttr(name="input1_bias"))
	predict2 = fluid.layers.fc(input=input2, size=1, act=None, param_attr=fluid.ParamAttr(name="input2_weight"), bias_attr=fluid.ParamAttr(name="input2_bias"))
	parameter_list1 = [valname.name for valname in fluid.default_main_program().block(0).all_parameters() if "intpu1" in valname.name]
	parameter_list2 = [valname.name for valname in fluid.default_main_program().block(0).all_parameters() if "intpu2" in valname.name]
	predict = predict1 + predict2
	predict = fluid.layers.sigmoid(predict_logits)
	loss = fluid.layers.logloss(input=predict, label=label)
	avg_cost = fluid.layers.mean(x=cost)
	auc_var, batch_auc_var, auc_states = fluid.layers.auc(input=predict, label=label)
	return 
	
data_list, avg_cost, auc_var, batch_auc_var, label, predict, parameter_list1, parameter_list2 = model()

#########省略一些初始化的过程

feed_var_names = []
for data in data_list:
	feed_var_names.append(data.name)
	
optimizer1 = fluid.optimizer.Adam(learning_rate=learning_rate1)
optimizer1 = fleet.distributed_optimizer(optimizer1, strategy)
optimizer1.minimize(avg_cost, parameter_list=parameter_list1)

optimizer2 = fluid.optimizer.Adam(learning_rate=learning_rate2)
optimizer2 = fleet.distributed_optimizer(optimizer2, strategy)
optimizer2.minimize(avg_cost, parameter_list=parameter_list2)

fleet._executor.train_from_dataset(fetch_list=[label, avg_cost, auc_var, batch_auc_var])

fleet.save_inference_model(feeded_var_names=feed_offline_var_names, target_vars=[predict, auc_var, batch_auc_var])

**Comment by saTan-Y** [comment]
> hi, 请把你的code发出来看下

抽取主干代码如下

`###input1 为子网络1的输入，input2位子网络2的输入
def model():
	data_list = []
	data.append(input1)
	data.append(input2)
	data.append(label)
	predict1 = fluid.layers.fc(input=input1, size=1, act=None, param_attr=fluid.ParamAttr(name="input1_weight"), bias_attr=fluid.ParamAttr(name="input1_bias"))
	predict2 = fluid.layers.fc(input=input2, size=1, act=None, param_attr=fluid.ParamAttr(name="input2_weight"), bias_attr=fluid.ParamAttr(name="input2_bias"))
	parameter_list1 = [valname.name for valname in fluid.default_main_program().block(0).all_parameters() if "intpu1" in valname.name]
	parameter_list2 = [valname.name for valname in fluid.default_main_program().block(0).all_parameters() if "intpu2" in valname.name]
	predict = predict1 + predict2
	predict = fluid.layers.sigmoid(predict_logits)
	loss = fluid.layers.logloss(input=predict, label=label)
	avg_cost = fluid.layers.mean(x=cost)
	auc_var, batch_auc_var, auc_states = fluid.layers.auc(input=predict, label=label)
	return 
	
data_list, avg_cost, auc_var, batch_auc_var, label, predict, parameter_list1, parameter_list2 = model()

#########省略一些初始化的过程

feed_var_names = []
for data in data_list:
	feed_var_names.append(data.name)
	
optimizer1 = fluid.optimizer.Adam(learning_rate=learning_rate1)
optimizer1 = fleet.distributed_optimizer(optimizer1, strategy)
optimizer1.minimize(avg_cost, parameter_list=parameter_list1)

optimizer2 = fluid.optimizer.Adam(learning_rate=learning_rate2)
optimizer2 = fleet.distributed_optimizer(optimizer2, strategy)
optimizer2.minimize(avg_cost, parameter_list=parameter_list2)

fleet._executor.train_from_dataset(fetch_list=[label, avg_cost, auc_var, batch_auc_var])

fleet.save_inference_model(feeded_var_names=feed_offline_var_names, target_vars=[predict, auc_var, batch_auc_var])`

**Comment by saTan-Y** [comment]
> hi, 请把你的code发出来看下

###input1 为子网络1的输入，input2位子网络2的输入
def model():
	data_list = []
	data.append(input1)
	data.append(input2)
	data.append(label)
	predict1 = fluid.layers.fc(input=input1, size=1, act=None, param_attr=fluid.ParamAttr(name="input1_weight"), bias_attr=fluid.ParamAttr(name="input1_bias"))
	predict2 = fluid.layers.fc(input=input2, size=1, act=None, param_attr=fluid.ParamAttr(name="input2_weight"), bias_attr=fluid.ParamAttr(name="input2_bias"))
	parameter_list1 = [valname.name for valname in fluid.default_main_program().block(0).all_parameters() if "intpu1" in valname.name]
	parameter_list2 = [valname.name for valname in fluid.default_main_program().block(0).all_parameters() if "intpu2" in valname.name]
	predict = predict1 + predict2
	predict = fluid.layers.sigmoid(predict_logits)
	loss = fluid.layers.logloss(input=predict, label=label)
	avg_cost = fluid.layers.mean(x=cost)
	auc_var, batch_auc_var, auc_states = fluid.layers.auc(input=predict, label=label)
	return data_list, avg_cost, auc_var, batch_auc_var, label, predict, parameter_list1, parameter_list2
	

data_list, avg_cost, auc_var, batch_auc_var, label, predict, parameter_list1, parameter_list2 = model()


#########省略一些初始化的过程


feed_var_names = []
for data in data_list:
	feed_var_names.append(data.name)
	
optimizer1 = fluid.optimizer.Adam(learning_rate=learning_rate1)
optimizer1 = fleet.distributed_optimizer(optimizer1, strategy)
optimizer1.minimize(avg_cost, parameter_list=parameter_list1)

optimizer2 = fluid.optimizer.Adam(learning_rate=learning_rate2)
optimizer2 = fleet.distributed_optimizer(optimizer2, strategy)
optimizer2.minimize(avg_cost, parameter_list=parameter_list2)

fleet._executor.train_from_dataset(fetch_list=[label, avg_cost, auc_var, batch_auc_var])

fleet.save_inference_model(feeded_var_names=feed_offline_var_names, target_vars=[predict, auc_var, batch_auc_var])

**Comment by saTan-Y** [comment]
> hi, 请把你的code发出来看下

有个地方写错了，请以这个为准。
###input1 为子网络1的输入，input2位子网络2的输入
def model():
data_list = []
data.append(input1)
data.append(input2)
data.append(label)
predict1 = fluid.layers.fc(input=input1, size=1, act=None, param_attr=fluid.ParamAttr(name="input1_weight"), bias_attr=fluid.ParamAttr(name="input1_bias"))
predict2 = fluid.layers.fc(input=input2, size=1, act=None, param_attr=fluid.ParamAttr(name="input2_weight"), bias_attr=fluid.ParamAttr(name="input2_bias"))
parameter_list1 = [valname.name for valname in fluid.default_main_program().block(0).all_parameters() if "intpu1" in valname.name]
parameter_list2 = [valname.name for valname in fluid.default_main_program().block(0).all_parameters() if "intpu2" in valname.name]
predict_logits= predict1 + predict2
predict = fluid.layers.sigmoid(predict_logits)
loss = fluid.layers.logloss(input=predict, label=label)
avg_cost = fluid.layers.mean(x=cost)
auc_var, batch_auc_var, auc_states = fluid.layers.auc(input=predict, label=label)
return data_list, avg_cost, auc_var, batch_auc_var, label, predict, parameter_list1, parameter_list2

data_list, avg_cost, auc_var, batch_auc_var, label, predict, parameter_list1, parameter_list2 = model()

#########省略一些初始化的过程

feed_var_names = []
for data in data_list:
feed_var_names.append(data.name)

optimizer1 = fluid.optimizer.Adam(learning_rate=learning_rate1)
optimizer1 = fleet.distributed_optimizer(optimizer1, strategy)
optimizer1.minimize(avg_cost, parameter_list=parameter_list1)

optimizer2 = fluid.optimizer.Adam(learning_rate=learning_rate2)
optimizer2 = fleet.distributed_optimizer(optimizer2, strategy)
optimizer2.minimize(avg_cost, parameter_list=parameter_list2)

fleet._executor.train_from_dataset(fetch_list=[label, avg_cost, auc_var, batch_auc_var])

fleet.save_inference_model(feeded_var_names=feed_offline_var_names, target_vars=[predict, auc_var, batch_auc_var])

**Comment by saTan-Y** [comment]
> hi, 请把你的code发出来看下

有个地方写错了，请以这个为准。
###input1 为子网络1的输入，input2位子网络2的输入
def model():
data_list = []
data.append(input1)
data.append(input2)
data.append(label)
predict1 = fluid.layers.fc(input=input1, size=1, act=None, param_attr=fluid.ParamAttr(name="input1_weight"), bias_attr=fluid.ParamAttr(name="input1_bias"))
predict2 = fluid.layers.fc(input=input2, size=1, act=None, param_attr=fluid.ParamAttr(name="input2_weight"), bias_attr=fluid.ParamAttr(name="input2_bias"))
parameter_list1 = [valname.name for valname in fluid.default_main_program().block(0).all_parameters() if "intpu1" in valname.name]
parameter_list2 = [valname.name for valname in fluid.default_main_program().block(0).all_parameters() if "intpu2" in valname.name]
predict_logits= predict1 + predict2
predict = fluid.layers.sigmoid(predict_logits)
loss = fluid.layers.logloss(input=predict, label=label)
avg_cost = fluid.layers.mean(x=cost)
auc_var, batch_auc_var, auc_states = fluid.layers.auc(input=predict, label=label)
return data_list, avg_cost, auc_var, batch_auc_var, label, predict, parameter_list1, parameter_list2

data_list, avg_cost, auc_var, batch_auc_var, label, predict, parameter_list1, parameter_list2 = model()

#########省略一些初始化的过程

feed_var_names = []
for data in data_list:
feed_var_names.append(data.name)

optimizer1 = fluid.optimizer.Adam(learning_rate=learning_rate1)
optimizer1 = fleet.distributed_optimizer(optimizer1, strategy)
optimizer1.minimize(avg_cost, parameter_list=parameter_list1)

optimizer2 = fluid.optimizer.Adam(learning_rate=learning_rate2)
optimizer2 = fleet.distributed_optimizer(optimizer2, strategy)
optimizer2.minimize(avg_cost, parameter_list=parameter_list2)

fleet._executor.train_from_dataset(fetch_list=[label, avg_cost, auc_var, batch_auc_var])

fleet.save_inference_model(feeded_var_names=feed_var_names, target_vars=[predict, auc_var, batch_auc_var])

**Comment by saTan-Y** [comment]
> hi, 请把你的code发出来看下

https://github.com/PaddlePaddle/Paddle/issues/19055 中提到Paddle不支持一个program里面多个minimize，但我试了一下是可以的

**Comment by starsblinking** [comment]
请问楼主的问题解决了吗？我想对网络中不同的参数用不同的optimizer
