### ISSUE TITLE
官方文档里面找不到paddle.fluid.contrib类，修改网络参数出现ValueError

### ISSUE THREAD

**Issue by ENGWayne** [PaddlePaddle/Paddle#23775]
运行晓曼老师的程序，里面有from  paddle.fluid.contrib.trainer import Trainer和from  paddle.fluid.contrib.inferencer import Inferencer两次对paddle.fluid.contrib类的调用，但是在官方文档里面搜不到这个类，不知道在哪里去找这两个函数的用法，请指教!

from  paddle.fluid.contrib.inferencer import Inferencer
inferencer = Inferencer(
    infer_func=convolutional_neural_network, param_path=params_dirname, place=place)

更改convolutional_neural_network里面的参数之后，出现ValueError
ValueError: Variable conv2d_0.w_0 has been created before. the previous shape is (50, 3, 10, 10); the new shape is (40, 3, 10, 10). They are not matched.

**Comment by Shixiaowei02** [comment]
您好，Inferencer 用法请参见：
https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/fluid/contrib/inferencer.py#L32-L53

Paddle 不允许同一个名称空间（Scope）下出现两个同名的变量（Variable），报错是不符合这条约定引起的。请了解一下 scope_guard 的用法，谢谢！
