### ISSUE TITLE
FC等layer的序列信息在哪里被保存下来

### ISSUE THREAD

**Issue by shenshuijing** [PaddlePaddle/Paddle#2377]
类似sequence_conv_pool实现中， fc后面加了pooling_layer,    参数经过FC的时候， 序列信息是如何被保留下来的？ 看FullyConnectedLayer实现，没看到相关逻辑， 是放到哪个独立的地方吗？

**Comment by luotao1** [comment]
每个layer forward最开始会调用[Layer::forward(passType)]( https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/gserver/layers/Layer.h#L408)
```
virtual void forward(PassType passType) {
    passType_ = passType;
    if (!inputLayers_.empty() && needSequenceInfo_) {
      const Argument& input = getInput(0);
      output_.sequenceStartPositions = input.sequenceStartPositions;
      output_.subSequenceStartPositions = input.subSequenceStartPositions;
      output_.cpuSequenceDims = input.cpuSequenceDims;
    }
  }
```
needSequenceInfo_默认是[True](https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/gserver/layers/Layer.cpp#L45)，即序列信息默认是保留下来的。
