### ISSUE TITLE
batch infer yolov3模型，出来的lod是[[0, 1]]是什么回事？

### ISSUE THREAD

**Issue by dancingpipi** [PaddlePaddle/Paddle#23785]
用的paddle 1.6.1。
用yolov3跑infer，输入是4张图片，返回结果如图：
![image](https://user-images.githubusercontent.com/20511825/79088579-a0c2fb80-7d75-11ea-94ac-42f7b9fb922d.png)

请问下batchsize为4在哪里体现？

**Comment by zhhsplendid** [comment]
https://www.paddlepaddle.org.cn/documentation/docs/zh/api_cn/layers_cn/multiclass_nms_cn.html#multiclass-nms   是的，输出是这个的输出

![image](https://user-images.githubusercontent.com/7913861/79110862-eef3f100-7dad-11ea-9022-5a51eb85ee8e.png)

batch size那一维在lod上。。No那一维相当于包含batchsize和各batch的预测框个数
