### ISSUE TITLE
GPU版本c++编译，但是预测的时候无法使用GPU

### ISSUE THREAD

**Issue by Angus07** [PaddlePaddle/Paddle#23791]
提示错误信息：
E0413 11:55:26.486809 36365 analysis_config.cc:73] Please compile with gpu to EnableGpu()

bcloud build, bcloud local 都试过，都不行。
确认编译结果都更新了。

#edit-mode: -*- python -*-
#coding:utf-8

WORKROOT('../../../')
PLATFORM('centos6u3')
COMPILER('gcc82')
CFLAGS('-g -O3 -pipe -W -Wall -fPIC -fpermissive')
CPPFLAGS('-D_GNU_SOURCE -D__STDC_LIMIT_MACROS -DVERSION=\\\"1.9.8.7\\\"')
CPPFLAGS('-DPYBIND_AVX_MKLML')

#C++ flags.
CXXFLAGS('-g -O3 -pipe -W -Wall -Wno-unused-parameter -fPIC -fpermissive -std=gnu++11')
LDFLAGS('-luuid -lpthread -ldl -lcrypt -lrt -lz -Bsymbolic -rdynamic -Wl,-rpath,./lib')

INCPATHS('. ./include ')
INCPATHS('../../lib/paddlepaddle/include')
INCPATHS('../../../third-64/python/include/')

HEADERS('include/*.h', '$INC')
HEADERS('./*.h', '$INC')

#link flags
CONFIGS('baidu/lib/textone-inference@textone-inference_1-0-2-10_gcc482_PD_BL@git_tag')
CONFIGS("baidu/base/common@stable")
CONFIGS('third-64/boost@boost_1-63-0-101_PD_BL')
CONFIGS("baidu/base/ullib@stable")
CONFIGS("lib2-64/ccode@ccode_3-2-3-2_PD_BL")
CONFIGS("lib2-64/others-ex@others-ex_3-1-25-0_PD_BL")
CONFIGS('baidu/lib/wordseg@wordseg_3-2-47-5_gcc482_PD_BL@git_tag')
CONFIGS('baidu/lib/libcrf@libcrf_2-4-23-1_gcc482_PD_BL@git_tag')
CONFIGS('public/odict@odict_1-1-4-2_PD_BL')
CONFIGS('baidu/base/configure@stable')
CONFIGS('baidu/third-party/protobuf@2b7430d96aeff2bb624c8d52182ff5e4b9f7f18a@git_branch')
CONFIGS('baidu/third-party/gflags@77592648e3f3be87d6c7123eb81cbad75f9aef5a@git_branch')

#CONFIGS('third-64/boost@1.63.0.101@BCLOUD')
CONFIGS('baidu/third-party/gflags@77592648e3f3be87d6c7123eb81cbad75f9aef5a@git_branch')
CONFIGS('baidu/third-party/glog@v0.3.5@git_branch')
CONFIGS('baidu/third-party/mklml@v20180406@git_branch', NeedOutput())
CONFIGS('baidu/third-party/mkl-dnn@a29d8487a63afca3d5b8c5bbdbb473cf8ccc6e51@git_branch', NeedOutput())

**CONFIGS('baidu/lib/paddlepaddle@v1.6.3-gcc82-cuda10.1-cudnn7.5_PD_BL@git_tag', NeedOutput())**

#flags='-g -shared -lstdc++ -pipe -W -Wall -fPIC -O1 -fpermissive -Wno-unused-parameter -Wno-unused-function'
#CXXFLAGS(flags + ' -std=c++11 ')
LIBS('$OUT_ROOT/baidu/lib/paddlepaddle/output/so/libpaddle_fluid.so')
LIBS('$OUT_ROOT/baidu/third-party/mklml/output/so/libmklml_intel.so')
LIBS('$OUT_ROOT/baidu/third-party/mklml/output/so/libmklml_gnu.so')
LIBS('$OUT_ROOT/baidu/third-party/mklml/output/so/libiomp5.so')
LIBS('$OUT_ROOT/baidu/third-party/mkl-dnn/output/so/libmkldnn.so')

LDFLAGS('-lpthread -ldl -lrt')

#UTApplication('model_struct_ie', Sources('./nn.cpp'), LDFLAGS, LinkDeps(True))

#OUTPUT("../../lib/textone-inference/lib/*", '$OUT/lib')

user_sources=GLOB('./title_predictor.cpp')\
            + ' ./util.cpp ' \
            + ' ./main.cpp'
Application('demo', Sources(user_sources),
                    Libraries("../../lib/textone-inference/lib/libbaiduprotect_sec.so"),
                    Libraries("../../lib/textone-inference/lib/libernie-inference.so"),
                    Libraries("../../lib/textone-inference/lib/libiomp5.so"),
                    Libraries("../../lib/textone-inference/lib/libmklml_gnu.so"),
                    Libraries("../../lib/textone-inference/lib/libmklml_intel.so"),
                    Libraries("../../lib/textone-inference/lib/libtextone-inference.so"),
                    Libraries("../../lib/textone-inference/lib/libsentencepiece.so"),
                    LinkDeps(True))

**Comment by jiweibo** [comment]
可以参考下baidu/personal-code/paddle-inference-demo 的BCLOUD文件

**Comment by jiweibo** [comment]
已和用户沟通，确认是依赖textone本身的问题

**Comment by mayank2** [comment]
I am still facing the same issue in paddlepaddle-gpu v2.0

**Comment by mayank2** [comment]
I am still facing the same issue in paddlepaddle-gpu v2.0
