### ISSUE TITLE
PaddlePaddle 创建test_program时clone函数的BUG

### ISSUE THREAD

**Issue by LessSMore** [PaddlePaddle/Paddle#23796]
- 版本、环境信息：
    1）PaddlePaddle版本：1.5.1
    2）GPU：Cuda compilation tools, release 9.2, V9.2.148
    3）系统环境：AI Studio平台GPU版

- 复现信息：当把test_program = fluid.default_main_program().clone(for_test=True)这句话放在optimizer定义之前，没有报错，但是训练出来的cifar10模型的test上的准确率只有50%左右，并且已经收敛，无法上升，如下图
![image](https://user-images.githubusercontent.com/44470582/79094809-3fa62280-7d8b-11ea-932c-de7f26049769.png)
![image](https://user-images.githubusercontent.com/44470582/79094824-50569880-7d8b-11ea-881b-27edf77a16be.png)

可是当test_program定义在optimizer之后，也没有报错，但是test测试集上的准确率上升很多，即便在相同训练轮数下，且还没有收敛，如下图
![image](https://user-images.githubusercontent.com/44470582/79094881-78de9280-7d8b-11ea-8470-075859040cf4.png)
![image](https://user-images.githubusercontent.com/44470582/79094917-91e74380-7d8b-11ea-8b7e-8cea94d2f6e3.png)

因此，我猜测在clone(for_test=True)对模型进行裁剪的时候，没有完全把反向传播的部分裁剪掉，导致测试集在进行测试的时候，也进行了反向传播并对模型进行优化，因此出现以上问题！
希望我能得到答复！！

我的联系方式：zljdanceholic@cau.edu.cn
这是源程序
[377234.zip](https://github.com/PaddlePaddle/Paddle/files/4468169/377234.zip)

**Comment by zhhsplendid** [comment]
嗨，你的猜测是正确的，在测试时不应该把 test_program = fluid.default_main_program().clone(for_test=True)这句话放在optimizer定义之后，原因是optimizer定义时，组网增加了optimizer op，因此clone测试program如果放在之后时，也会把optimizer op添加进测试program，相当于你的测试集也是边训练边预测了，算是某种类似“作弊”的行为，因此在预测集准确率大大提高。

如果是最新版本的paddle，为了避免用户错误配置网络为你说的第二种情况，我们paddle也增加了警告信息解释。

**Comment by zhhsplendid** [comment]
希望能回答到您的问题，我将关闭此卡片，如果有更多追问可以再开启此卡片继续问

**Comment by LessSMore** [comment]
你好，非常感谢你的回复！已经解除我之前的疑惑！ 我想再问一下:  1. 这个被close了是不是其他用户就搜索不到我的问题了呢？ 2. 我刚才看到paddle文档里说的是当for_test＝true时，clone会裁剪部分op，就是说并没有完全阻止反向传播的进行对吗？------------------ 原始邮件 ------------------
发件人: "Huihuang Zheng"<notifications@github.com>
发送时间: 2020年4月14日(星期二) 上午10:20
收件人: "PaddlePaddle/Paddle"<Paddle@noreply.github.com>;
抄送: "LessSMore"<937371423@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [PaddlePaddle/Paddle] PaddlePaddle 创建test_program时clone函数的BUG (#23796)




 
嗨，你的猜测是正确的，在测试时不应该把 test_program = fluid.default_main_program().clone(for_test=True)这句话放在optimizer定义之后，原因是optimizer定义时，组网增加了optimizer op，因此clone测试program如果放在之后时，也会把optimizer op添加进测试program，相当于你的测试集也是边训练边预测了，算是某种类似“作弊”的行为，因此在预测集准确率大大提高。
 
如果是最新版本的paddle，为了避免用户错误配置网络为你说的第&#x4E8C;种情况，我们paddle也增加了警告信息解释。
 
&mdash;

**Comment by zhhsplendid** [comment]
1. close了别人也能搜索到和看到，只是我们团队这边表示我们追踪完这个问题。

2. 看到paddle文档里说的是当for_test＝true时，clone会裁剪部分op，是的，是根据input/output裁剪部分op，根据这部分op对input/output不会有数值影响裁剪掉。但由于optimizer op是会影响输入输出的，因此没被裁剪掉

**Comment by LessSMore** [comment]
谢谢你！我已经明白了！------------------ 原始邮件 ------------------
发件人: "Huihuang Zheng"<notifications@github.com>
发送时间: 2020年4月14日(星期二) 中午11:35
收件人: "PaddlePaddle/Paddle"<Paddle@noreply.github.com>;
抄送: "LessSMore"<937371423@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [PaddlePaddle/Paddle] PaddlePaddle 创建test_program时clone函数的BUG (#23796)




  
 
close了别人也能搜索到和看到，只是我们团队这边表示我们追踪完这个问题。
 
 
 
看到paddle文档里说的是当for_test＝true时，clone会裁剪部分op，是的，是根据input/output裁剪部分op，根据这部分op对input/output不会有数值影响裁剪掉。但由于optimizer op是会影响输入输出的，因此没被裁剪掉
 
  
&mdash;

**Comment by LessSMore** [comment]
你好，我还想问一下，是不是如果用动态图方式，就不用担心会出现这种情况了呢------------------ 原始邮件 ------------------
发件人: "Huihuang Zheng"<notifications@github.com>
发送时间: 2020年4月14日(星期二) 中午11:35
收件人: "PaddlePaddle/Paddle"<Paddle@noreply.github.com>;
抄送: "LessSMore"<937371423@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [PaddlePaddle/Paddle] PaddlePaddle 创建test_program时clone函数的BUG (#23796)




  
 
close了别人也能搜索到和看到，只是我们团队这边表示我们追踪完这个问题。
 
 
 
看到paddle文档里说的是当for_test＝true时，clone会裁剪部分op，是的，是根据input/output裁剪部分op，根据这部分op对input/output不会有数值影响裁剪掉。但由于optimizer op是会影响输入输出的，因此没被裁剪掉
 
  
&mdash;

**Comment by zhiqiu** [comment]
> 你好，我还想问一下，是不是如果用动态图方式，就不用担心会出现这种情况了呢------------------ 原始邮件 ------------------ 发件人: "Huihuang Zheng"<notifications@github.com> 发送时间: 2020年4月14日(星期二) 中午11:35 收件人: "PaddlePaddle/Paddle"<Paddle@noreply.github.com>; 抄送: "LessSMore"<937371423@qq.com>;"Author"<author@noreply.github.com>; 主题: Re: [PaddlePaddle/Paddle] PaddlePaddle 创建test_program时clone函数的BUG (#23796) close了别人也能搜索到和看到，只是我们团队这边表示我们追踪完这个问题。 看到paddle文档里说的是当for_test＝true时，clone会裁剪部分op，是的，是根据input/output裁剪部分op，根据这部分op对input/output不会有数值影响裁剪掉。但由于optimizer op是会影响输入输出的，因此没被裁剪掉 &mdash; You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

hi，你也可以试试新版本paddle-1.7是否还会有这个问题，我们在新版本对clone(for_test=True)的剪枝进行了优化。我理解，你说的文档可能是新版本。

**Comment by LessSMore** [comment]
你好，我想问下，如果是用动态图，在测试前没有加上model. eval这一句，一样会像之前那样，把测试集进行反向传播了，然后正确率会莫名提升是吗？------------------ 原始邮件 ------------------
发件人: "Leo Chen"<notifications@github.com>
发送时间: 2020年4月17日(星期五) 下午3:03
收件人: "PaddlePaddle/Paddle"<Paddle@noreply.github.com>;
抄送: "LessSMore"<937371423@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [PaddlePaddle/Paddle] PaddlePaddle 创建test_program时clone函数的BUG (#23796)




  
你好，我还想问一下，是不是如果用动态图方式，就不用担心会出现这种情况了呢------------------ 原始邮&#x4EF6; ------------------ 发&#x4EF6;人: "Huihuang Zheng"notifications@github.com 发送时间: 2020年4月14日(星期&#x4E8C;) 中午11:35 收&#x4EF6;人: "PaddlePaddle/Paddle"Paddle@noreply.github.com; 抄送: "LessSMore"937371423@qq.com;"Author"author@noreply.github.com; 主题: Re: [PaddlePaddle/Paddle] PaddlePaddle 创建test_program时clone函数的BUG (#23796) close了别人也能搜索到和看到，只是我们团队这边表示我们追踪完这个问题。 看到paddle文档里说的是当for_test＝true时，clone会裁剪部分op，是的，是根据input/output裁剪部分op，根据这部分op对input/output不会有数值影响裁剪掉。但由于optimizer op是会影响输入输出的，因此没被裁剪掉 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.
  
hi，你也可以试试新版本paddle-1.7是否还会有这个问题，我们在新版本对clone(for_test=True)的剪枝进行了优化。我理解，你说的文档可能是新版本。
 
&mdash;
