### ISSUE TITLE
PyPi中paddlepaddle-tiny最新版本为1.6.1

### ISSUE THREAD

**Issue by gary02** [PaddlePaddle/Paddle#23798]
paddlepaddle-tiny出现在1.7.0 的release note中， 为什么发布的tiny版本为1.6.1？
实测1.7.1版本预测性能比1.6.1版本好太多（ 同样500w字数的文本， 预测使用时间从18分钟缩短到不到4分钟）

**Comment by xyzhou-puck** [comment]
hi，你好。

抱歉，因为一些原因，paddlepaddle-tiny没有跟paddle一起发布1.7版本，我们会争取在接下来的版本中做相应的升级。谢谢。
