### ISSUE TITLE
linux编译问题

### ISSUE THREAD

**Issue by CallmeZhangChenchen** [PaddlePaddle/Paddle#23804]
照顾一下上github都很艰难的用户好吗
    1）PaddlePaddle：1.7
    2）CPU：Intel® Xeon(R) CPU E5-1620 v3 @ 3.50GHz × 8 
    3）GPU：2080super，CUDA-10.0，CUDNN7.6
    4）系统环境：ubuntu16.04
本地编译：
cmake -DFLUID_INFERENCE_INSTALL_DIR=./ \
      -DCMAKE_BUILD_TYPE=Release \
      -DWITH_PYTHON=OFF \
      -DWITH_MKL=OFF \
      -DWITH_GPU=ON  \
      -DON_INFER=ON \
      ..
 make -j4

正文：
好了该说正文了，能不能像paddle-lite一样，编译的时候可以加速第三方库的下载的方法。上个github都要转好几十个圈圈才能进来。好就这一点问题。

**Comment by zhhsplendid** [comment]
嗨，你好，lite里一些加速方法是通过删除第三方库还有使用百度的一些云设备达到的，对paddlepaddle当前不太适用，所以可能还是麻烦你调试网络状况，必要时科学访问外网。。。

**Comment by zhhsplendid** [comment]
不过也谢谢您的反馈，我们也会尽快优化paddlepaddle第三方库的下载速度
