### ISSUE TITLE
Confusing convnet demos in paddlepaddle book's ch02 and ch03

### ISSUE THREAD

**Issue by Meleeri** [PaddlePaddle/Paddle#2380]
Hi, I'm facing some difficulty in figuring out how paddle handles cnn convnets. According to demos in paddlepaddle book's ch02 and ch03, all inputs are flattened before fed to the network as the data layer, which is very confusing since no width and height are specified, convolution seems impossible. Is there something missing in the documentation or paddle simply treats inputs as squares when no width and height are specified?

**Comment by luotao1** [comment]
1.  If the input is **Square**, data layer must specify size (height and width are not necessary). And the first conv layer specifies the input channel, we can compute the height/width of this conv layer according to the size of data layer.
2.  If the input is **Rectangle**, data layer must specify both height and width.    
3.  Note that above design is used to compatible with the previous usage.
