### ISSUE TITLE
为什么使用Paddle1.6训练bert模型内存用量比paddle 1.5高

### ISSUE THREAD

**Issue by dashulu** [PaddlePaddle/Paddle#23811]
使用paddle 1.6进行https://github.com/PaddlePaddle/models/tree/develop/PaddleNLP/pretrain_language_models/BERT中语句和句对分类任务的fine-tuning训练，内存使用比paddle v1.5高很多。
paddle v1.5的内存用量：Theoretical memory usage in training: 5956.480 - 6240.122 MB
paddle v1.6的内存用量：Theoretical memory usage in training: 18064.986 - 18925.223 MB.
这个是什么原因导致的？训练配置都是一样的。

**Comment by zhhsplendid** [comment]
谢谢反馈，这个情况很奇怪，因为我们做过显存优化，并且bert属于监控和常用模型，按理说应该不会有3倍差距。请确定这个是paddle的问题？会不会有什么环境配置，输入数据量等等的不同方面？

**Comment by dashulu** [comment]
没有环境变量配置的问题，都是直接跑，数据是一致的，差别可能就是random，但是不会有那么大的影响。而且参数配置中，in_tokens是false

**Comment by dashulu** [comment]
是否差3倍不确定，但是内存用量增加是肯定的，paddle 1.5 8G内存可以跑，但是paddle 1.6不能跑。
这个内存统计是 fluid.contrib.memory_usage得到的。
