### ISSUE TITLE
动态图的Fast-scnn 图像分割网络报错，帮看看哪儿不对

### ISSUE THREAD

**Issue by jaffe-fly** [PaddlePaddle/Paddle#23815]
`Traceback` (most recent call last):
  File "E:/fire_detection/fire_code/mycode/fast_scnn_aaaa.py", line 212, in <module>
    out = net(x)
  File "C:\Users\admin\Anaconda3\lib\site-packages\paddle\fluid\dygraph\layers.py", line 304, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "E:/fire_detection/fire_code/mycode/fast_scnn_aaaa.py", line 29, in forward
    higher_res_features = self.learning_to_downsample(x)
  File "C:\Users\admin\Anaconda3\lib\site-packages\paddle\fluid\dygraph\layers.py", line 304, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "E:/fire_detection/fire_code/mycode/fast_scnn_aaaa.py", line 139, in forward
    x = self.conv(x)
  File "C:\Users\admin\Anaconda3\lib\site-packages\paddle\fluid\dygraph\layers.py", line 304, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "E:/fire_detection/fire_code/mycode/fast_scnn_aaaa.py", line 56, in forward
    x = self.conv(x)
  File "C:\Users\admin\Anaconda3\lib\site-packages\paddle\fluid\dygraph\layers.py", line 304, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "C:\Users\admin\Anaconda3\lib\site-packages\paddle\fluid\dygraph\nn.py", line 234, in forward
    outs = core.ops.conv2d(inputs, attrs)
paddle.fluid.core_avx.EnforceNotMet: 

--------------------------------------------
C++ Call Stacks (More useful to developers):
--------------------------------------------
Windows not support stack backtrace yet.

----------------------
Error Message Summary:
----------------------
Error: An error occurred here. There is no accurate error hint for this error yet. We are continuously in the process of increasing hint for this kind of error check. It would be helpful if you could inform us of how this conversion went by opening a github issue. And we will resolve it with high priority.
  - New issue link: https://github.com/PaddlePaddle/Paddle/issues/new
  - Recommended issue content: all error stack information
  [Hint: CUDNN_STATUS_BAD_PARAM] at (D:/1.7.1/paddle\paddle/fluid/operators/conv_cudnn_helper.h:235)

如果需要，请留邮箱，我把代码发过去

**Comment by zhhsplendid** [comment]
CUDNN_STATUS_BAD_PARAM 有可能是环境问题，cudnn配置不好，cudnn版本不对等，可否检查是否有安装cudnn？相应版本cudnn是否对应paddle版本？如果发现cudnn版本对得上仍然需要更多帮助请继续回复本issue

**Comment by jaffe-fly** [comment]
我已经了CUDA，还有CUDNN的版本 还是报上面的错误
`# -*- coding: utf-8 -*-
__author__ = 'author'
__data__ = '2020/3/15 17:49'

import paddle.fluid as fluid
from paddle.fluid.dygraph import Conv2D,BatchNorm,Sequential
from paddle.fluid import layers

# bn_regularizer = fluid.regularizer.L2DecayRegularizer(regularization_coeff=0.0)

class Fast_SCNN(fluid.dygraph.Layer):
    def __init__(self,num_classes,aux=False,**kwargs):
        super(Fast_SCNN, self).__init__()
        self.aux = aux
        self.learning_to_downsample = LearningtoDownsample(32,48,64)
        self.global_feature_extractor = GlobalFeatureExtractor(64,[64,96,128],128,6,[3,3,3])
        self.feature_fusion = FeatureFusionModule(64,128,128)
        self.classifier = Classifer(128,num_classes)

        if self.aux:
            self.aux_layer = Sequential(
                Conv2D(64,32,3,padding=1),
                BatchNorm(32,act='relu'))

            self.conv = Conv2D(32,num_classes,1)

    def forward(self, x):
        size = x.shape[2:]
        higher_res_features = self.learning_to_downsample(x)
        x = self.global_feature_extractor(higher_res_features)
        x = self.feature_fusion(higher_res_features,x)
        x = self.classifier(x)
        outputs = []
        x = layers.resize_bilinear(x,size)
        outputs.append(x)
        if self.aux:
            auxout = self.aux_layer(higher_res_features)
            auxout = layers.dropout(auxout,dropout_prob=0.1)
            auxout = self.conv(auxout)
            auxout = layers.resize_bilinear(auxout,size)
            outputs.append(auxout)
        return tuple(outputs)



class _ConvBNRelu(fluid.dygraph.Layer):
    def __init__(self,in_channels,numfilters,filter_size=3,stride=1,padding=0,**kwargs):
        super(_ConvBNRelu, self).__init__()
        self.conv = Conv2D(in_channels,numfilters,filter_size,stride,padding)
        self.bn = BatchNorm(numfilters,
                            act='relu')
                            # epsilon=1e-05,
                            # param_attr=fluid.ParamAttr(regularizer=bn_regularizer),
                            # bias_attr=fluid.ParamAttr(regularizer=bn_regularizer))
    def forward(self, x):
        x = self.conv(x)
        x = self.bn(x)
        return x

class _DSconv(fluid.dygraph.Layer):
    def __init__(self,dw_channels,numfilters,stride=1,**kwargs):
        super(_DSconv, self).__init__()
        self.conv1 = Conv2D(dw_channels,num_filters=dw_channels,filter_size=3,stride=stride,padding=1,groups=dw_channels)
        self.bn1 = BatchNorm(dw_channels,act='relu')
        self.conv2 = Conv2D(dw_channels,num_filters=numfilters,filter_size=1)
        self.bn2 = BatchNorm(numfilters,act='relu')

    def forward(self, x):
        x = self.conv1(x)
        x = self.bn1(x)
        x = self.conv2(x)
        x =self.bn2(x)
        return x

class _DWconv(fluid.dygraph.Layer):
    def __init__(self,dw_channels,numfilters,stride=1,**kwargs):
        super(_DWconv, self).__init__()
        self.conv1 = Conv2D(dw_channels,num_filters=numfilters,filter_size=3,stride=stride,padding=1,groups=dw_channels)
        self.bn = BatchNorm(numfilters,act='relu')
    def forward(self,x):
        x = self.conv1(x)
        x =self.bn(x)
        return x

class LinearBottleneck(fluid.dygraph.Layer):
    def __init__(self,in_channels,out_channels,t=6,stride=2,**kwargs):
        super(LinearBottleneck, self).__init__()
        self.use_shortcut = stride == 1 and in_channels == out_channels
        self.block = Sequential(
            #pw
            _ConvBNRelu(in_channels,in_channels*t,1),
            #dw
            _DWconv(in_channels*t,in_channels*t,stride),
            #pw-linear
            Conv2D(in_channels*t,out_channels,filter_size=1),
            BatchNorm(out_channels)
        )

    def forward(self, x):
        out = self.block(x)
        if self.use_shortcut:
            out = x+out
        return out

class PyramidPooling(fluid.dygraph.Layer):
    def __init__(self,in_channels,out_channels,**kwargs):
        super(PyramidPooling, self).__init__()
        inter_channels = int(in_channels / 4)
        self.conv1 = _ConvBNRelu(in_channels,inter_channels,1,**kwargs)
        self.conv2 = _ConvBNRelu(in_channels, inter_channels, 1, **kwargs)
        self.conv3 = _ConvBNRelu(in_channels, inter_channels, 1, **kwargs)
        self.conv4 = _ConvBNRelu(in_channels, inter_channels, 1, **kwargs)
        self.out = _ConvBNRelu(in_channels*2, out_channels, 1, **kwargs)

    def pool(self, x,size):
        return layers.adaptive_pool2d(x,pool_size=size,pool_type='avg')

    def upsample(self,x,size):
        return fluid.layers.resize_bilinear(x,size)

    def forward(self, x):
        size = x.shape[2:]
        feat1 = self.upsample(self.conv1(self.pool(x,1)),size)
        feat2 = self.upsample(self.conv2(self.pool(x, 2)), size)
        feat3 = self.upsample(self.conv3(self.pool(x, 3)), size)
        feat4 = self.upsample(self.conv4(self.pool(x, 6)), size)
        x = layers.concat(input=[x,feat1,feat2,feat3,feat4],axis=1)
        x = self.out(x)
        return x

class LearningtoDownsample(fluid.dygraph.Layer):
    def __init__(self,dw_channels1=32,dw_channels2=48,out_channels=64,**kwargs):
        super(LearningtoDownsample, self).__init__()
        self.conv = _ConvBNRelu(3,dw_channels1,filter_size=3,stride=2)
        self.dsconv1 = _DSconv(dw_channels1,dw_channels2,2)
        self.dsconv2 = _DSconv(dw_channels2,out_channels,2)

    def forward(self, x):
        x = self.conv(x)
        x = self.dsconv1(x)
        x = self.dsconv2(x)
        return x

class GlobalFeatureExtractor(fluid.dygraph.Layer):
    def __init__(self,in_channels=64,block_channels=(64,96,128),out_channels=128,t=6,num_blocks=(3,3,3),**kwargs):
        super(GlobalFeatureExtractor, self).__init__()
        self.bottleneck1 = self._make_layer(LinearBottleneck,in_channels,block_channels[0],num_blocks[0],t,2)
        self.bottleneck2 = self._make_layer(LinearBottleneck, block_channels[0], block_channels[1], num_blocks[1], t, 2)
        self.bottleneck3 = self._make_layer(LinearBottleneck, block_channels[1], block_channels[2], num_blocks[2], t, 1)
        self.ppm = PyramidPooling(block_channels[2],out_channels)


    def _make_layer(self,block,inplanes,planes,blocks,t=6,stride=1):
        layers=[]
        layers.append(block(inplanes,planes,t,stride))
        for i in range(1,blocks):
            layers.append(block(planes,planes,t,1))
        return fluid.dygraph.Sequential(*layers)

    def forward(self, x):
        x = self.bottleneck1(x)
        x = self.bottleneck2(x)
        x = self.bottleneck3(x)
        x = self.ppm(x)
        return x

class FeatureFusionModule(fluid.dygraph.Layer):
    def __init__(self,highter_in_channels,lower_in_channels,out_channels,scale_factor=4,**kwargs):
        super(FeatureFusionModule, self).__init__()
        self.scale_factor = scale_factor
        self.dwconv = _DWconv(lower_in_channels,out_channels,1)
        self.conv_lower_res = Sequential(
            Conv2D(out_channels,out_channels,1),
            BatchNorm(out_channels)
        )
        self.conv_higher_res = Sequential(
            Conv2D(highter_in_channels,out_channels,1),
            BatchNorm(out_channels,act='relu')
        )

    def forward(self, higher_res_feature,lower_res_feature):
        lower_res_feature = layers.resize_bilinear(lower_res_feature,scale=4)
        lower_res_feature = self.dwconv(lower_res_feature)
        lower_res_feature = self.conv_lower_res(lower_res_feature)

        higher_res_feature = self.conv_higher_res(higher_res_feature)
        out = higher_res_feature+lower_res_feature
        return layers.relu(out)

class Classifer(fluid.dygraph.Layer):
    def __init__(self,dw_channels,num_classes,strde=1,**kwargs):
        super(Classifer, self).__init__()
        self.dsconv1 = _DSconv(dw_channels,dw_channels,strde)
        self.dsconv2 = _DSconv(dw_channels,dw_channels,strde)
        self.conv = Conv2D(dw_channels,num_classes,1)


    def forward(self,x):
        x = self.dsconv1(x)
        x = self.dsconv2(x)
        x = layers.dropout(x,dropout_prob=0.1)#输入单元设置为0的概率为0.1。
        x = self.conv(x)
        return x

with fluid.dygraph.guard():
    net = Fast_SCNN(2)
    import numpy as np
    x = np.random.randn(1,3,2,2)
    x = x.astype('float32')
    x = fluid.dygraph.to_variable(x)
    # print(x.shape[2:])
    out = net(x)
    print(net)








`

**Comment by zhhsplendid** [comment]
嗨，你好，观察到已经自己close issue了，是否已经解决了？有更多问题可以再提问
