### ISSUE TITLE
多卡评估时，边训边评估跟加载保存的模型再评估存在diff

### ISSUE THREAD

**Issue by wuyefeilin** [PaddlePaddle/Paddle#23813]
![image](https://user-images.githubusercontent.com/30919197/79122502-60da3380-7dca-11ea-8197-490616b2ccd6.png)
多卡评估时，边训边评估跟加载保存的模型再评估存在diff，误差在万分之几数量级，使用单卡情况没有diff

**Comment by zhhsplendid** [comment]
请提供更多复现步骤/代码或者对我们有帮助的情况，我们好处理相应精度问题

**Comment by zhhsplendid** [comment]
请问有更多更新吗？如果没有更新，我们将之后关闭此卡片，如果有需求请继续本issue提问
