### ISSUE TITLE
相关性问题如何处理？

### ISSUE THREAD

**Issue by jueljust** [PaddlePaddle/Paddle#2382]
经常遇到希望机器自动判定相关性的情况
一般数据是这样的
一个搜索词 一个文档
然后希望机器自动判定搜索词和文档是否相关
文档可能是文章，短句，图片或者音频
一般一个搜索词也仅给出一个文档，并不会给出多个文档
一般仅要求判断是否相关，少数时候会要求对相关度进行打分

**Comment by luotao1** [comment]
1. 可以参考PaddlePaddle/models下的[排序学习文档](https://github.com/PaddlePaddle/models/tree/develop/ltr) 
2. 一个搜索词和一个文档：可以使用pointwise方法。
3. 请问你的数据中：是否有正例也有负例，标记数据的分布如何？

**Comment by jueljust** [comment]
数据分布大概是三七开，一般不是五五

**Comment by jueljust** [comment]
问一下，这个问题的核心是不是怎么提搜索词和文档之间的关系特征，譬如tf,idf之类的。然后根据这些特征算score

**Comment by jueljust** [comment]
嗯，这个问题关键是怎么提特征，模型二分类，回归，learn to rank都可以，我想通了，不是关键不是算法的问题，是提特征的问题
