### ISSUE TITLE
损失函数由cross_entropy更改为dice_loss后，本地训练可以拟合，集群训练auc一直为0.5

### ISSUE THREAD

**Issue by zhaoyang1708** [PaddlePaddle/Paddle#23820]
损失函数之前为cross_entropy，训练正常，更改为dice_loss后，本地2000条ins是可以过拟合的，但集群训练一直为0.5
    sim_ctr = fluid.layers.cos_sim(user_fc_ctr, ad_fc_ctr)
    scale_ctr = fluid.layers.scale(x=sim_ctr, scale=5.0)
    predict_ctr = fluid.layers.fc(name="output2", input=scale_ctr, size=CLASS_SIZE, act="softmax")
    predict_ctr_one = fluid.layers.slice(predict_ctr, axes=[1],starts=[1], ends=[2])
    binary_predict_ctr = predict_ctr
    auc_var, cur_auc, auc_states = fluid.layers.auc(input=binary_predict_ctr, label=label, slide_steps = 20)
    cost = fluid.layers.dice_loss(input=binary_predict_ctr, label=label) 
    avg_cost = fluid.layers.reduce_sum(cost)
    avg_cost = fluid.layers.scale(x=avg_cost, scale=int(os.environ['CPU_NUM']))
任务链接http://10.182.12.37:8910/fileview.html?type=logsdir&path=/&instance=0.app-user-20200413214256-39482--zhaoyang29_online_novelbsq_dice_paddlecloud
![image](https://user-images.githubusercontent.com/16074812/79179989-6d4aa480-7e3b-11ea-943e-4ece3a900ccf.png)

**Comment by zhhsplendid** [comment]
本地训练没有问题，集群训练却有问题，可否麻烦转问paddlecloud？
