### ISSUE TITLE
paddle启动训练出现异常，详见截图

### ISSUE THREAD

**Issue by cvdnn** [PaddlePaddle/Paddle#23824]
- 标题：paddle启动训练出现异常
- 版本、环境信息：
    1）PaddlePaddle版本：1.7.1
    2）CPU：3 GHz Intel Core i7
    4）系统环境：Mac OS 10.13.6 (17G6030)，Python版本：3.7.6
- 训练信息
    1）单机
    3）Operator信息：You could check whether you killed PaddlePaddle thread/process accidentally or report the case to PaddlePaddle

![image](https://user-images.githubusercontent.com/15883260/79182481-7cccec00-7e41-11ea-8e1d-eafac7c56c82.png)

**Comment by ysh329** [comment]
图显示不出来，能贴一下log嘛

**Comment by ysh329** [comment]
hi，能贴一下复现问题的代码嘛，以及相关的log，我这边网络一直显示gihtub的图不出来
