### ISSUE TITLE
自己实现模型报错elem_mul问题

### ISSUE THREAD

**Issue by 3wGTA** [PaddlePaddle/Paddle#23833]
我想实现BiMPM模型，但是在自己定义的一个参数乘法上面出现了问题，不知道怎么解决

模型如下
![image](https://user-images.githubusercontent.com/62338824/79184964-3a5add80-7e48-11ea-8ed1-9a94f859c370.png)

![image](https://user-images.githubusercontent.com/62338824/79184887-01bb0400-7e48-11ea-8e72-b23e276c6362.png)

大概这个形式、
![image](https://user-images.githubusercontent.com/62338824/79185089-8443c380-7e48-11ea-8962-2f144b336605.png)

![image](https://user-images.githubusercontent.com/62338824/79185203-d4228a80-7e48-11ea-9695-3a383d0461fb.png)

在匹配层我自己创建了参数w1，w2...等等，然后

![image](https://user-images.githubusercontent.com/62338824/79185301-18158f80-7e49-11ea-87d7-fae28dd3b9f7.png)

模型实现的一小部分代码
1.
![image](https://user-images.githubusercontent.com/62338824/79185587-ebae4300-7e49-11ea-96b9-ec6ea941ee74.png)
2.
![image](https://user-images.githubusercontent.com/62338824/79185598-f7016e80-7e49-11ea-9326-91e409dd9e92.png)
3.
![image](https://user-images.githubusercontent.com/62338824/79185601-fa94f580-7e49-11ea-878e-b3c75929232b.png)

不知道自己实现那个cos函数对了嘛，总是报elementwise_mul那里的问题，希望推荐下解决方法

我尝试了改elemengwise_mul 的axis，但是还是没能够解决

希望能够帮我解决那个多视角的 cos 函数问题

模型参考的网址：

https://blog.csdn.net/zhang2010hao/article/details/87943489?depth_1-utm_source=distribute.pc_relevant.none-task-blog-BlogCommendFromBaidu-1&utm_source=distribute.pc_relevant.none-task-blog-BlogCommendFromBaidu-1

paddlepaddle：1.7
python：3.7
在aistudio上面也是一样的结果，jupyter直接崩溃重启

**Comment by ysh329** [comment]
能贴一下log嘛，我这里图都显示不出来。。

**Comment by ysh329** [comment]
关于elementwise_mul的op使用，建议参考文档关于axis部分的解释说明：
https://www.paddlepaddle.org.cn/documentation/docs/zh/api_cn/layers_cn/elementwise_mul_cn.html#elementwise-mul
