### ISSUE TITLE
如何将多个预训练的program，然后整合为一个program

### ISSUE THREAD

**Issue by hanguantianxia** [PaddlePaddle/Paddle#23846]
请问如果有一个encoder-decoder模型，现在先把encoder和decoder作为独立的program进行分别单独的预训练，在fine-tuning时候现在想把它们连接在一起，有什么办法吗？

**Comment by ysh329** [comment]
有 构建三个program就行

**Comment by hanguantianxia** [comment]
你的意思是把一个program是encoder，一个program是decoder，第三个program的是encoder和decoder结合？但是目前静态图的参数读取API中，第三个program载入其他program的参数会报错。
![image](https://user-images.githubusercontent.com/22430355/79574168-5aadc500-80f2-11ea-84dd-f508f6432b99.png)
