### ISSUE TITLE
paddlecloud没有正常进行cpu分布式训练

### ISSUE THREAD

**Issue by zhaoyang1708** [PaddlePaddle/Paddle#23853]
训练任务将paddle包升级为1.7.1（paddlepaddle-1.7.1-cp27-cp27m-linux_x86_64.whl），cpu环境，设定80节点，但一直没正常训练
任务链接
http://10.182.11.155:8910/fileview.html?type=logsdir&path=/&instance=0.app-user-20200414182015-40997--zhaoyang29_online_novelbsq_paddlecloud

**Comment by ysh329** [comment]
这个问题可能需要问下paddlecloud分布式的同学
