### ISSUE TITLE
PaddleCloud V100 训练模型速度 低于本地

### ISSUE THREAD

**Issue by JingChunzhen** [PaddlePaddle/Paddle#23851]
为使您的问题得到快速解决，在建立Issues前，请您先通过如下方式搜索是否有相似问题:【搜索issue关键字】【使用labels筛选】【官方文档】

如果您没有查询到相似问题，为快速解决您的提问，建立issue时请提供如下细节信息：
- 标题：简洁、精准概括您的问题，例如“Insufficient Memory xxx" ”
- 版本、环境信息：
    1）PaddlePaddle版本：请提供您的PaddlePaddle版本号，例如1.1或CommitID ：paddle1.5.0  ，paddlecloud 任务：job-0bb5e95226b86e18  
    3）GPU：预测若用GPU，请提供GPU型号、CUDA和CUDNN版本号：GPU：v100
    4）系统环境：请您描述系统类型、版本，例如Mac OS 10.14，Python版本 ：Python2.7
- 训练信息
    1）单机/多机，单卡/多卡 ：单机多卡
    2）显存信息：GPU利用率 66%
    3）Operator信息
- 复现信息：如为报错，请给出复现环境、复现步骤
- 问题描述：请详细描述您的问题，同步贴出报错信息、日志、可复现的代码片段

脚本可以在 paddle cloud env_run 上看到
算力组 使用 yq01-v100-box-1-8，当前 GPU 利用率 66%，咨询了 paddlecloud同学，未发现问题，让问问 paddle 同学是否是组网方面 脚本方面的问题

**Comment by JingChunzhen** [comment]
附咨询paddlecloud 同学 icafe卡片：http://newicafe.baidu.com/issue/paddle-cloud-user-2592/show

**Comment by ysh329** [comment]
之前PaddleCloud有利用率能达到100%或者预期利用率的情况嘛

**Comment by JingChunzhen** [comment]
GPU 利用率 只 作为 参考，主要还是 训练 速度 较慢，和 CPU训练 速度 类似了
