### ISSUE TITLE
paddle1.5.0 fluid.io.load_vars 预测结果不一致

### ISSUE THREAD

**Issue by JingChunzhen** [PaddlePaddle/Paddle#23850]
为使您的问题得到快速解决，在建立Issue前，请您先通过如下方式搜索是否有相似问题:【搜索issue关键字】【使用labels筛选】【官方文档】

建立issue时，为快速解决问题，请您根据使用情况给出如下信息：
- 标题：简洁、精准描述您的问题，例如“ssd 模型前置lstm报错  ”
- 版本、环境信息：
    1）PaddlePaddle版本：请提供PaddlePaddle版本号，例如1.1或CommitID
    2）CPU：请提供CPU型号，MKL/OpenBlas/MKLDNN/等数学库的使用情况
    3）GPU：请提供GPU型号，CUDA和CUDNN版本号
    4）系统环境：请说明系统类型、版本（例如Mac OS 10.14），Python版本
- 模型信息
    1）模型名称 2）使用数据集名称 3）使用算法名称 4）模型链接
- 复现信息：如为报错，请给出复现环境、复现步骤
- 问题描述：请详细描述您的问题，同步贴出报错信息、日志/代码关键片段

Thank you for contributing to PaddlePaddle.
Before submitting the issue, you could search issue in the github.Probably there was a similar issue submitted or resolved before.
If there is no solution,please make sure that this is a issue of models including the following details:
**System information**
-PaddlePaddle version （eg.1.1）or CommitID
-CPU: including CPUMKL/OpenBlas/MKLDNN version
-GPU: including CUDA/CUDNN version
-OS Platform (eg.Mac OS 10.14)
-Python version
-Name of Models&Dataset/details of operator
**To Reproduce**
Steps to reproduce the behavior
**Describe your current behavior**
**Code to reproduce the issue**
**Other info / logs**

paddle 1.5.0 CPU
使用 adam optimizer 生成的 checkpoint 加载模型（fluid.io.load_vars）之后 相同的输入数据 ，出来的结果不一致
将 checkpoint 保存 成 inference model(fluid.io.save_inference_model) 之后 加载 （fluid.io.load_inference_model） 之后 输入相同的数据， 出来的结果 是一致 的
想问下 以上可能的原因是什么？

**Comment by ysh329** [comment]
hi,想问下，这个和adam optimizer有啥关系呢

我看这个API和这个优化器没关，应该是说当时训练使用的优化器对吧，

load_vars-API文档-PaddlePaddle深度学习平台
https://www.paddlepaddle.org.cn/documentation/docs/zh/api_cn/io_cn/load_vars_cn.html#load-vars

**Comment by JingChunzhen** [comment]
adam optimizer 保存的 checkpoint 中间 保存了一些 adam 优化器里面的 变量，这点 在 加载 checkpoint 时 是否 会影响到 输出的结果呢？

**Comment by ysh329** [comment]
> adam optimizer 保存的 checkpoint 中间 保存了一些 adam 优化器里面的 变量，这点 在 加载 checkpoint 时 是否 会影响到 输出的结果呢？

adam optimizer 保存的 checkpoint 中间 保存了一些 adam 优化器里面的 变量，这点 在 加载 checkpoint 时 ，目前看来是，会影响输出结果的。
