### ISSUE TITLE
CPU集群训练失败，pserver问题

### ISSUE THREAD

**Issue by zhaoyang1708** [PaddlePaddle/Paddle#23865]
提交了几次任务都是遇到相同问题
http://10.182.19.142:8910/fileview.html?type=logsdir&path=/&instance=0.app-user-20200414153949-40759--zhaoyang29_online_novelnnq_paddlecloud
http://10.182.19.142:8910/fileview.html?type=logsdir&path=/&instance=0.app-user-20200414202411-41186--zhaoyang29_online_novelnnq_paddlecloud
![image](https://user-images.githubusercontent.com/16074812/79233200-14aaf400-7e9b-11ea-812d-7f70bbc51813.png)
![image](https://user-images.githubusercontent.com/16074812/79233823-ee398880-7e9b-11ea-8d43-e652383f52bd.png)

提了卡片问paddlecloud值班同学，反馈说是pserver挂了，咨询下paddle
paddlecloud排查卡片链接
http://newicafe.baidu.com/issue/paddle-cloud-user-2667/show?from=page

**Comment by ysh329** [comment]
提示worker挂掉了

**Comment by zhaoyang1708** [comment]
> 提示worker挂掉了

请问怎么解决呢，提了几次都是这样

**Comment by zhaoyang1708** [comment]
> 提示worker挂掉了

请问怎么解决呢

**Comment by ysh329** [comment]
我看是work挂掉了，

```
not ready, wait 3 sec to retry...

work not alive
```

感觉应该和分布式有关，可以再看下分布式方面的问题

**Comment by MrChengmo** [comment]
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/29789135/79627718-2f1bf080-816d-11ea-9c81-c6281076f91e.png">

看报错是出现在pserver的Adam op里，建议先本地模拟分布式，拿少量样本跑通，再上分布式，节点数由少至多调试一下。
