### ISSUE TITLE
Linear接在卷积后面，如何得到faltten后的input尺寸？

### ISSUE THREAD

**Issue by lao-xu** [PaddlePaddle/Paddle#23868]
使用paddle1.7动态图，Linear接在卷积后面，要输入faltten后的input尺寸，怎么去得到？难道都要人工计算吗？
        self.pool2 = Pool2D(pool_size=2, pool_stride=2, pool_type='max')                    
        # 创建第3个卷积层
        self.conv3 = Conv2D(num_channels=16, num_filters=120, filter_size=4, act='sigmoid')  
        # 创建全连接层，第一个全连接层的输出神经元个数为64， 第二个全连接层输出神经元个数为分裂标签的类别数        
        self.flatten_shape = `120*50*50`
        self.fc1 = Linear(input_dim=self.flatten_shape, output_dim=64, act='sigmoid')
        self.fc2 = Linear(input_dim=64, output_dim=num_classes,act='softmax')

**Comment by ysh329** [comment]
参考实例代码：

```python
import paddle.fluid as fluid
x = fluid.layers.data(name="x", shape=[4, 4, 3], append_batch_size=False, dtype="float32")
# x shape is [4, 4, 3]
out = fluid.layers.flatten(x=x, axis=2)
# out shape is [16, 3]
```

flatten-API文档-PaddlePaddle深度学习平台
https://www.paddlepaddle.org.cn/documentation/docs/zh/api_cn/layers_cn/flatten_cn.html#flatten


```python
from paddle.fluid.dygraph.base import to_variable
import paddle.fluid as fluid
from paddle.fluid.dygraph import Linear
import numpy as np

data = np.random.uniform( -1, 1, [30, 10, 32] ).astype('float32')
with fluid.dygraph.guard():
    linear = Linear(32, 64)
    data = to_variable(data)
    res = linear(data)  # [30, 10, 64]
```

Linear-API文档-PaddlePaddle深度学习平台
https://www.paddlepaddle.org.cn/documentation/docs/zh/api_cn/dygraph_cn/Linear_cn.html#linear

> Linear接在卷积后面，要输入faltten后的input尺寸，怎么去得到？难道都要人工计算吗？

目前看来是的

**Comment by lao-xu** [comment]
那这还不如1.6版本的方便啊
