### ISSUE TITLE
请问如何计算模型参数

### ISSUE THREAD

**Issue by guoqiang0148666** [PaddlePaddle/Paddle#23861]
感谢你们杰出的工作！

请问如何计算模型的总参数呢？

是训练后的model_final.pdparams文件的大小除以４吗？

**Comment by ysh329** [comment]
是参数的个数，还是参数占用体积呢。
可以参考：模型参数与计算量_Python_hey-yahei-CSDN博客
https://blog.csdn.net/qq_20759449/article/details/93055041
