### ISSUE TITLE
fluid.layers.auc 得到的batch auc = 0

### ISSUE THREAD

**Issue by JingChunzhen** [PaddlePaddle/Paddle#23871]
使用如下 api 进行 inference model 计算 auc，batch_size == 100 
```python
# paddle 1.5.2
global_auc, batch_auc, _ = fluid.layers.auc(input=pred, label=input_label, slide_steps=1)
```
# loss batch_auc global_auc
0	1.86869418621	[0.]	[0.]
1	1.95746719837	[0.97979798]	[0.98492462] # ？
2	1.95067119598	[0.]	[0.98327759]
3	1.92995178699	[0.]	[0.98746867]
4	1.94889438152	[0.]	[0.98797595]
5	1.85230088234	[1.]	[0.99190396]
6	2.05646729469	[0.98989899]	[0.99155891]
7	1.89979791641	[0.98989899]	[0.99144654]
8	1.82984125614	[0.]	[0.9922905]
9	1.674020648	[0.98989899]	[0.99010731]
10	1.9083533287	[0.]	[0.9900975]
11	1.83100903034	[0.98989899]	[0.99024069]
12	1.82303655148	[0.]	[0.9907745]
13	1.82914912701	[0.95959596]	[0.98715876]
14	1.83058965206	[1.]	[0.98912752]
15	1.96960937977	[0.]	[0.98902516]
16	1.80508208275	[0.]	[0.98931953]

问题：
部分 batch_auc == 0 , 但是 global auc 维持 在高位 ？

**Comment by JingChunzhen** [comment]
```python
global_auc, batch_auc, _ = fluid.layers.auc(input=pred, label=input_label, slide_steps=1)
```
slide_step == 1 
slide_step ==10
以上两种情况下，global_auc 的计算方式 的区别是什么？
https://www.paddlepaddle.org.cn/documentation/docs/en/1.5/api/layers/metric_op.html#auc
在以上文档中没有提到不同slide step 情况下 global auc的计算方法

**Comment by JingChunzhen** [comment]
0 1.86869418621 [0.] [0.]
1 1.95746719837 [0.97979798] [0.98492462] # ？
2 1.95067119598 [0.] [0.98327759]
3 1.92995178699 [0.] [0.98746867]
4 1.94889438152 [0.] [0.98797595]

感觉以上情况是 将 batch auc = 0 的 情况 当成 了1 ，计算在 global auc 中

**Comment by MRXLT** [comment]
slide_step对global_auc没有影响， 只影响batch auc的计算范围是当前batch还是包括之前的batch，global_auc是采用的累加值计算的
可以提供以下可复现的代码吗

**Comment by JingChunzhen** [comment]
paddle cloud job id ： job-0bb5e95226b86e18
打开 日志详情 overview 有 env_run
里面的 inference.py 入口函数是 infer()

**Comment by MRXLT** [comment]
经过沟通，代码中保存模型使用的save_presisitables，加载时使用的load_vars，可能导致部分vars加载错误，使用save_inference_model保存和load_inference_model加载时没有出现以上错误

**Comment by JingChunzhen** [comment]
评论错 issue 了~
