### ISSUE TITLE
train_from_dataset memory leak

### ISSUE THREAD

**Issue by LihangLiu** [PaddlePaddle/Paddle#23887]
使用fluid1.6的train_from_dataset接口时，发生了内存泄漏。

系统信息：

- centos
- paddlepaddle-gpu 1.6.0.post107
- cuda10, cudnn7

**Comment by LihangLiu** [comment]
部分代码

    dataset = fluid.DatasetFactory().create_dataset()
    dataset.set_use_var(input_vars)
    dataset.set_batch_size(config['train']['batch_size'])
    dataset.set_thread(config['train']['thread_num'])
    dataset.set_pipe_command("cat")
    filelist = glob('%s/part-*' % fluid_dataset_dir)
    dataset.set_filelist(sub_filelist)
    exe.train_from_dataset(self.train_program, 
                                    dataset, 
                                    fetch_list=self.train_outputs['fetch_dict'].values(),
                                    fetch_info=self.train_outputs['fetch_dict'].keys(),
                                    print_period=self.alg.config['train']['prt_interval'],
                                    scope=self.scope)
`

**Comment by MRXLT** [comment]
你好，我们会对问题进行排查，建议先使用1.7版本的paddle
