### ISSUE TITLE
动态图下如何如何在多核的节点上使用多线程训练

### ISSUE THREAD

**Issue by zhangylch** [PaddlePaddle/Paddle#23881]
paddle version 1.7
   请问一下，如何在动态图下使用多线程，就是实现类似于openmp的功能或者静态图下ParallelExecutor的作用。我发现我在24核的节点上运行作业始终只有一个核被利用。类似于下面的情况

![捕获](https://user-images.githubusercontent.com/56628666/79306545-fd661800-7f27-11ea-89d6-355c4c17f144.JPG)
其中的python3 就是我的作业
而如果我使用openmp在Fortran语言里面重写这个程序或者调用MKL的话是这样的，2400的占用率
![捕获1](https://user-images.githubusercontent.com/56628666/79306837-7cf3e700-7f28-11ea-94ae-4429f2203f4f.JPG)

**Comment by zhiqiu** [comment]
动态图可以用多进程方式的使用多卡。[参考](https://www.paddlepaddle.org.cn/documentation/docs/zh/beginners_guide/basic_concept/dygraph/DyGraph.html#id5)

**Comment by zylustc** [comment]
> 动态图可以用多进程方式的使用多卡。[参考](https://www.paddlepaddle.org.cn/documentation/docs/zh/beginners_guide/basic_concept/dygraph/DyGraph.html#id5)

多进程的方式好像不像共享内存下opnemp的并行，更类似于mpi的并行？我一直以为paddle内部回和MKL库一样自动给做并行的

**Comment by zhangylch** [comment]
> 动态图可以用多进程方式的使用多卡。[参考](https://www.paddlepaddle.org.cn/documentation/docs/zh/beginners_guide/basic_concept/dygraph/DyGraph.html#id5)

你好，这是多卡是针对GPU的，CPU并行也能这样吗？

**Comment by MRXLT** [comment]
你好，CPU并行请在执行训练之前export CPU_NUM={要使用的CPU核数}

**Comment by zhangylch** [comment]
> 你好，CPU并行请在执行训练之前export CPU_NUM={要使用的CPU核数}

我在提交作业的脚本里面加了这一行，没有效果。我想请教下，paddlepaddle动态图的cpu并行可以想GPU多卡那样设置吗？我看里面好多需要用的api都是针对GPU。我以为他内部和MKL库类似自己做的并行优化的

**Comment by MRXLT** [comment]
不好意思，Paddle动态图目前还不支持cpu并行计算，正在开发中

**Comment by zhangylch** [comment]
> 不好意思，Paddle动态图目前还不支持cpu并行计算，正在开发中

好的吧

**Comment by illcat** [comment]
> 不好意思，Paddle动态图目前还不支持cpu并行计算，正在开发中

现在可以了吗
