### ISSUE TITLE
Pool2D说明文档里的默认设置

### ISSUE THREAD

**Issue by lao-xu** [PaddlePaddle/Paddle#23892]
api说明文档里：
class paddle.fluid.dygraph.Pool2D(pool_size=-1, pool_type='max', pool_stride=1, pool_padding=0, global_pooling=False, use_cudnn=True, ceil_mode=False, exclusive=True)

pool_padding (int|list|tuple, 可选) - 填充大小。如果它是一个元组或列表，它必须包含两个整数值，(pool_padding_on_Height, pool_padding_on_Width)。若为一个整数，则表示H和W维度上padding均为该值。默认值为1。

这里默认值应该为0吧

**Comment by MRXLT** [comment]
感谢反馈，我们稍后会修改文档

**Comment by jzhang533** [comment]
这是个非常常用的接口。
这个问题依然存在，抓紧改改吧。
英文文档是对的。
1.8 和 2.0alpha版本都有这个问题。
