### ISSUE TITLE
Ubuntu16.04安装错误

### ISSUE THREAD

**Issue by DCC-lzhy** [PaddlePaddle/Paddle#23903]
- 标题：Ubuntu16.04安装错误”/“编译错误”
- 版本、环境信息：
    1）PaddlePaddle版本：paddlepaddle-gpu 1.7.1.post107
    2）CPU：80  Intel(R) Xeon(R) Gold 6230 CPU @ 2.10GHz
    3）GPU：CUDA Version 10.0.130，CUDNN 7.6.4
    4）系统环境：Ubuntu16.04 python 3.7.7
- 安装方式信息：
1）pip安装
- 复现信息：paddle.fluid.install_check.run_check()，原先运行该命令，提示我缺少动态库nccllib；于是我安装了nccl，再来运行改命令，出现此错误。
- 问题描述：Error Message Summary:
----------------------
Error: An error occurred here. There is no accurate error hint for this error yet. We are continuously in the process of increasing hint for this kind of error check. It would be helpful if you could inform us of how this conversion went by opening a github issue. And we will resolve it with high priority.
  - New issue link: https://github.com/PaddlePaddle/Paddle/issues/new
  - Recommended issue content: all error stack information: out of memory at (/paddle/paddle/fluid/platform/device_context.cc:221)
很奇怪，这个错误。
-------------------------------------------------------------------------------

**Comment by Joejiong** [comment]
nccllib I have the same issue with nccl, hope the team publish some tutorial with how to reinstall nccl library

**Comment by lijianshe02** [comment]
https://www.paddlepaddle.org.cn/documentation/docs/zh/install/compile/compile_Ubuntu.html, ubuntu下安装请参考这个链接
