### ISSUE TITLE
本地训练一轮后报错，稳定复现，集群训练正常

### ISSUE THREAD

**Issue by AWSWXY** [PaddlePaddle/Paddle#23914]
报错如下
F0416 14:01:22.373754  9892 grpc_client.cc:504] SendRPC name:[fc_0.b_0@GRAD.trainer_0], ep:[127.0.0.1:6001], status:[-1] meets grpc error, error_code:4 error_message:Deadline Exceeded error_details:
*** Check failure stack trace: ***
    @     0x7f03e31c75cd  google::LogMessage::Fail()
    @     0x7f03e31cb07c  google::LogMessage::SendToLog()
    @     0x7f03e31c70f3  google::LogMessage::Flush()
    @     0x7f03e31cc58e  google::LogMessageFatal::~LogMessageFatal()
    @     0x7f03e46119ca  paddle::operators::distributed::GRPCClient::Proceed()
    @     0x7f035b2e7cd0  execute_native_thread_routine
    @     0x7f04007e5d14  start_thread
    @     0x7f03ffe15bfd  clone
    @              (nil)  (unknown)

**Comment by lijianshe02** [comment]
请参考这个issue: https://github.com/PaddlePaddle/Paddle/issues/14776
