### ISSUE TITLE
jupyter notebook导入paddle出错”No module named 'paddle'”（之前运行正常）

### ISSUE THREAD

**Issue by tangbozhang** [PaddlePaddle/Paddle#23920]
版本、环境信息：
   1）PaddlePaddle版本：1.7.2.post107
   2）CPU：i7-9300H，CUDA-7.4和CUDNN-10.0
   4）系统环境：win10家庭中文版、Python3.7
安装方式信息：
1）conda安装           
复现信息：通过conda安装后在jupyter notebook配置好paddle的python环境后，输入代码
import paddle，然后报错“ModuleNotFoundError: No module named 'paddle'”

问题描述：通过conda安装paddle成功了（在anaconda prompt 已经测试过，anaconda navigator的虚拟环境中也有paddle信息，我的操作系统是win10家庭版），然后在anaconda navigator 中的虚拟环境中启动jupyter notebook，前段时间使用正常，今天使用时报上述错误。
在notebook中，运行指令“!pip list”，可以看到paddle相关信息
“paddlehub            1.6.1              
paddlepaddle-gpu     1.7.2.post107 ”；
但运行指令“pip list”，没有paddle相关信息。
conda、paddlepadle、paddlehub都升级到最新版本，jupyter notebook卸载重装，仍没有解决问题。

**Comment by wanghaoshuang** [comment]
在notebook里新建code block, 执行以下命令查看下python site-packages在哪个路径：
```
import numpy
print numpy.__file__
```
然后在看下site-packages下有paddle文件夹吗：
```
!ls /your_path/python2.7/site-packages/
```
没有的话，在当前python环境下装下paddle就行了。

**Comment by tangbozhang** [comment]
我是用anconda安装的，anaconda\Lib\site-packages下确实没有paddle相关文件，查看另一运行正常电脑里有文件paddle和paddlepaddle_gpu-1.7.1.post107.dist-info，比对工具发现和“envs\paddle\Lib\site-packages”下的文件paddle和paddlepaddle_gpu-1.7.1.post107.dist-info一样，手动拷贝过去后，还是不行

**Comment by tangbozhang** [comment]
在anconda终端下，切到虚拟环境padlle中 import paddle.fluid
paddle.fluid.install_check.run_check()运行正常。
设置jupyter notebook添加启动虚拟环境padlle，电脑重启后还是不行，感觉jupyter notebook还是没进虚拟环境paddle，进的还是虚拟环境base

**Comment by tangbozhang** [comment]
pycharm进虚拟环境paddle，paddle使用正常
