### ISSUE TITLE
CMake Error at cmake/inference_lib.cmake:270编译错误

### ISSUE THREAD

**Issue by wangzhankun** [PaddlePaddle/Paddle#23959]
## 版本、环境信息：
* PaddlePaddle v1.7.0
* OS jetson nano ubuntu18.04
* ARM aarch64 cortex-a57
* cuda 10.0
* cudnn 7.6.3.28
* python 3.6 virtualenv
## 本地编译
```Bash
cmake .. \
          -DWITH_CONTRIB=OFF \
          -DFLUID_INFERENCE_INSTALL_DIR=/opt/paddle \
          -DWITH_MKL=OFF  \
          -DWITH_MKLDNN=OFF \
          -DWITH_TESTING=OFF \
          -DCMAKE_BUILD_TYPE=Release \
          -DON_INFER=ON \
          -DWITH_PYTHON=ON \
          -DWITH_XBYAK=OFF  \
          -DWITH_NV_JETSON=ON \
          -DPY_VERSION=3.6

```

## 报错
```Bash
CMake Error at cmake/inference_lib.cmake:270 (file):
  file failed to open for writing (No such file or directory):

```

**Comment by hong19860320** [comment]
请参考https://www.paddlepaddle.org.cn/documentation/docs/zh/advanced_guide/inference_deployment/inference/build_and_install_lib_cn.html 页面中的"NVIDIA Jetson嵌入式硬件预测库源码编译"部分，按步骤进行编译，建议直接使用我们预编译好的nv-jetson-cuda10-cudnn7.5-trt5 https://paddle-inference-lib.bj.bcebos.com/1.7.1-nv-jetson-cuda10-cudnn7.5-trt5/fluid_inference.tar.gz

**Comment by wangzhankun** [comment]
确实是按照那个教程进行编译的，但现在关键是cmake都出问题，提示是paddle的文件缺失

**Comment by wangzhankun** [comment]
> 请参考https://www.paddlepaddle.org.cn/documentation/docs/zh/advanced_guide/inference_deployment/inference/build_and_install_lib_cn.html 页面中的"NVIDIA Jetson嵌入式硬件预测库源码编译"部分，按步骤进行编译，建议直接使用我们预编译好的nv-jetson-cuda10-cudnn7.5-trt5 https://paddle-inference-lib.bj.bcebos.com/1.7.1-nv-jetson-cuda10-cudnn7.5-trt5/fluid_inference.tar.gz

官方提供的是C的库，我想用python的库，所以希望能够自行编译

**Comment by hong19860320** [comment]
> 确实是按照那个教程进行编译的，但现在关键是cmake都出问题，提示是paddle的文件缺失

这个不是提示cmake文件缺失，而是cmake脚本往${FLUID_INSTALL_DIR) 、${FLUID_INFERENCE_INSTALL_DIR}、${FLUID_INFERENCE_C_INSTALL_DIR}写文件的时候，发现没有那个目录，或者没有往那个目录读写文件的权限。
建议去掉-DFLUID_INFERENCE_INSTALL_DIR=/opt/paddle 这个参数。
