### ISSUE TITLE
PaddleDetection 迁移学习方法请教

### ISSUE THREAD

**Issue by 670133189** [PaddlePaddle/Paddle#23967]
我现在使用PaddleDetection，用自己标注的数据，已经训练了一个YOLO v3的模型，保存在本地文件中。现在又多了一批训练数据（类别一样），我想继续训练模型，但是PaddleDetection上的迁移学习教程中使用了pretrain_weights和finetune_exclude_pretrained_params这两个参数，其中第一个参数是网址，意思是要从网上下载预训练模型。问题是：

1、那我自己的模型，pretrain_weights是不是就是本地模型的文件路径？

2、使用自己的模型时，finetune_exclude_pretrained_params参数是否有用，该如何使用？

谢谢！

**Comment by wangchaochaohu** [comment]
@heavengate 帮忙看下？

**Comment by heavengate** [comment]
此问题已由 https://github.com/PaddlePaddle/PaddleDetection/issues/530 跟进，当前issue先关闭，如果还有其他问题可以reopen此issue~
