### ISSUE TITLE
Is cuDNN/BLAS, MKL, Neon all BLAS compatible?

### ISSUE THREAD

**Issue by wangkuiyi** [PaddlePaddle/Paddle#2397]
If we represent tensors in the same memory footprint, is it correct that we can call cuDNN, MKL, and Neon to operate tensors on various devices?

**Comment by wangkuiyi** [comment]
OK, BLAS just defined some very primitive and frequently used operations. But all these toolkits are much more powerful than BLAS.

**Comment by gangliao** [comment]
memory layout should be specified if using third-party libs, like MKL, cuDNN, OpenBlas. All of them supports column major, thus that's not a problem.

 In Majel, the internal implementation of `gemm(Array, ...)` also invoked `cublas_gemm(Array.ptr())` and `MKL's cblas_gemm(Array.ptr())`.

@wangkuiyi

**Comment by wangkuiyi** [comment]
Thanks to @gangliao
