### ISSUE TITLE
cpu下ocr_recognition预测结果错误

### ISSUE THREAD

**Issue by prettyocean85** [PaddlePaddle/Paddle#23995]
版本、环境信息：
    1）PaddlePaddle版本：1.7.1

- 问题描述：
使用PaddlePaddle\models\PaddleCV\ocr_recognition训练好的模型预测，模型训练在GPU下完成，在infer源代码基础上修改模型重新保存为固化模型。使用 AnalysisPredictor 方式预测，并使用zerocopytensor。模型和输入完全一致，在GPU下预测结果正确，CPU结果错误，请问可能是什么原因。
GPU预测正确结果
[[ 3]
 [ 2]
 [ 4]
 [ 8]
 [ 7]
 [21]
 [31]
 [14]
 [31]
 [36]
 [35]]
CPU错误结果：
[[ 2]
 [ 2]
 [ 4]
 [ 4]
 [ 4]
 [ 5]
 [ 4]
 [ 5]
 [ 1]
 [ 4]
 [ 5]
 [ 4]
 [31]
 [ 2]
 [ 4]
 [ 5]
 [ 9]
 [ 2]
 [34]
 [34]
 [ 4]]

**Comment by luotao1** [comment]
请试下 https://github.com/PaddlePaddle/Paddle/issues/14837#issuecomment-445830987

**Comment by prettyocean85** [comment]
@luotao1 python使用C++接口预测代码怎么删除fc_gtu_fuse_pass呢？cpu预测部分代码如下
config = AnalysisConfig(model_file_path, pb_file_path)
config.disable_gpu()
config.enable_mkldnn()
config.switch_specify_input_names(True)
config.enable_memory_optim()
config.disable_glog_info()
config.switch_use_feed_fetch_ops(False)#模型运行的时候删去feed和fetchops
predict = fluid.core.create_paddle_predictor(config)

**Comment by OliverLPH** [comment]
@prettyocean85 
```
config = AnalysisConfig(model_file_path, pb_file_path)
config.delete_pass("fc_gru_fuse_pass") 
```
直接delete_pass就行了

**Comment by prettyocean85** [comment]
已解决谢谢
