### ISSUE TITLE
二次求导结果不符合预期（gradient of gradient）

### ISSUE THREAD

**Issue by zenghsh3** [PaddlePaddle/Paddle#23998]
- 版本、环境信息：
    1）PaddlePaddle版本：paddlepaddle-1.7.2
    2）系统环境：linux, cpu, python3

- 问题描述：
进行下述二阶求导时，计算的二阶梯度不符合预期（预期结果：grad1=4, grad2=4，实际结果如下）
![image](https://user-images.githubusercontent.com/5762635/79720594-76dc7c80-8313-11ea-9e54-05ef2ac85fca.png)

- 复现demo（包括了fluid/pytorch/jax）：
https://colab.research.google.com/drive/12VhNZlRClPBjvqy0UWz0u5a_MiEL5MNj

**Comment by chenwhql** [comment]
确实如此，是个bug，我反馈一下

**Comment by qingqing01** [comment]
@zenghsh3 感谢反馈，我们会尽快修复~ 抱歉~

**Comment by qingqing01** [comment]
@zenghsh3  已在 https://github.com/PaddlePaddle/Paddle/pull/24190  中修复
