### ISSUE TITLE
layers.Print()并未显示信息

### ISSUE THREAD

**Issue by shaunhurryup** [PaddlePaddle/Paddle#23996]
链接地址：https://www.paddlepaddle.org.cn/documentation/docs/zh/api_cn/layers_cn/Print_cn.html#print

源码：
```python
import paddle.fluid as fluid
import paddle
import numpy as np

x = fluid.layers.data(name='x', shape=[1], dtype='float32', lod_level=1)
x = fluid.layers.Print(x, message="The content of input layer:")

y = fluid.layers.data(name='y', shape=[1], dtype='float32', lod_level=2)
out = fluid.layers.sequence_expand(x=x, y=y, ref_level=0)
place = fluid.CPUPlace()
exe = fluid.Executor(place)
exe.run(fluid.default_startup_program())
x_d = fluid.create_lod_tensor(np.array([[1.1], [2.2],[3.3],[4.4]]).astype('float32'), [[1,3]], place)
y_d = fluid.create_lod_tensor(np.array([[1.1],[1.1],[1.1],[1.1],[1.1],[1.1]]).astype('float32'), [[1,3], [1,2,1,2]], place)
results = exe.run(fluid.default_main_program(),
                  feed={'x':x_d, 'y': y_d },
                  fetch_list=[out],return_numpy=False)
```

输出：
第一次执行给了个警告：/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/executor.py:804: UserWarning: There are no operators in the program to be executed. If you pass Program manually, please use fluid.program_guard to ensure the current Program is being used.
  warnings.warn(error_info)
第二次执行没什么都没显示

**Comment by chenwhql** [comment]
您好，我用您的源码可以正常打印出来的，结果如下
```
λ yq01-gpu-255-137-12-00 /work/scripts {master} python print_error.py 
grep: warning: GREP_OPTIONS is deprecated; please use an alias or script
/usr/local/lib/python3.5/dist-packages/paddle/fluid/executor.py:1093: UserWarning: There are no operators in the program to be executed. If you pass Program manually, please use fluid.program_guard to ensure the current Program is being used.
  warnings.warn(error_info)
1587383609      The content of input layer:     The place is:CPUPlace
Tensor[x]
        shape: [4,1,]
        dtype: f
        LoD: [[ 0,1,4, ]]
        data: 1.1,2.2,3.3,4.4,
```
Print里面是用C++ std::cout打印的，麻烦您再确认下您的Paddle版本和环境？也可以用官方文档提供的示例执行下试试？

**Comment by shaunhurryup** [comment]
1）感谢你的回复。刚才我在本地试了一下可以正常输出，但是在AI Studio上是没有结果的
![image](https://user-images.githubusercontent.com/45918719/79749935-a8b90780-8342-11ea-835f-be64a870a5d1.png)

2）我想了解下为什么执行的时候会报出如下错误

> UserWarning: There are no operators in the program to be executed. If you pass Program manually, please use fluid.program_guard to ensure the current Program is being used.

**Comment by shaunhurryup** [comment]
补充一下~

Python版本：python3.7
框架版本：PaddlePaddle 1.7.0
GPU版本

**Comment by chenwhql** [comment]
exe.run(fluid.default_startup_program())，您的startup_program里没有要执行的东西，这步操作是一般用来初始化网络参数的，您这个demo很简单，没有参数或者learning_rate需要初始化，所以执行这步的时候，会报没有需要执行的op

**Comment by shaunhurryup** [comment]
可是在AI Studio中为什么输出会没有显示呢

**Comment by chenwhql** [comment]
> 可是在AI Studio中为什么输出会没有显示呢

可能和他们的平台有关吧，我猜jupyter是不是不能捕获C++ std::cout的输出，要不反馈给他们看看？

**Comment by shaunhurryup** [comment]
我觉得可以~

**Comment by chenwhql** [comment]
> 我觉得可以~

可以捕获输出吗？还是可以反馈下？

**Comment by shaunhurryup** [comment]
反馈一下吧，不然平台上用不了，这个Print接口就废了

**Comment by chenwhql** [comment]
好的，您清楚AI Studio的反馈渠道吗？我这边没用Studio，不太清楚。
如果没有框架相关的问题，麻烦您最后关掉这个issue
