### ISSUE TITLE
开发了视频码流的目标检测，然后推流到流媒体服务器，但性能较卡，请问可好的解决思路或方案

### ISSUE THREAD

**Issue by DavidFangx** [PaddlePaddle/Paddle#24010]
具体问题：
我们基于 YOLOv3 DarkNet53 模型，对视频流进行目标识别，把识别结果叠加到视频上去，并以 
  ffmpeg 方式 推流 stmp 到流媒体服务器，但是效果不理想，在流媒体上服务器看最后的视频，非常的卡，请问可好的解决思路或方案? 
谢谢。

**Comment by sjtubinlong** [comment]
当单个帧的处理速度跟不上视频流的帧率就会出现卡顿高延时等情况，这块的优化方向有几个，1. 使用GPU提升预测速度，2. 选择较小的轻量级模型或对模型进行量化   3. 根据实际处理速度，选择性丢失部分帧以保障整体的流畅性。 4. 适当降低视频的分辨率等。

另外需要排除流媒体网络传输速度对性能的影响。

@DavidFangx

**Comment by qingqing01** [comment]
@DavidFangx 目前具体耗时，是在模型预测阶段，还是视频流处理方面？

**Comment by DavidFangx** [comment]
若只使用opencv 读取摄像机视频流 获取帧，再使用 ffmpeg 推流到流媒体服务器不卡。
模型单独预测阶段速度0.25秒/帧。
目前问题是：将模型预测结果通过 ffmpeg 推流 整合 后，在流媒体上服务器看最后的视频，非常的卡

**Comment by DavidFangx** [comment]
解决了啊哈，python 异步处理，就好了

**Comment by njuptzwt** [comment]
> 解决了啊哈，python 异步处理，就好了
最近刚好也需要处理这种模式，想问你一下，这种方式处理，视频的延迟会越来越大，即使不卡？你那边有考虑这个嘛？
