### ISSUE TITLE
frequent CI test failures on certain unit tests

### ISSUE THREAD

**Issue by helinwang** [PaddlePaddle/Paddle#2401]
We need to address these frequent failures for the Teamcity CI system to run smoothly:
```text
[23:28:05]	[Step 1/1] 52 - test_ProtoServer (Failed)
[23:28:05]	[Step 1/1] 56 - test_TrainerOnePass (Failed)
```
http://172.19.32.20:8111/viewLog.html?buildId=1100&buildTypeId=Paddle_PrCi&tab=buildLog&_focus=8207
http://172.19.32.20:8111/viewLog.html?buildId=1103&buildTypeId=Paddle_PrCi&tab=buildLog&_focus=13799

**Comment by wangkuiyi** [comment]
The [error message from test_ProtoServer](http://172.19.32.20:8111/viewLog.html?buildId=1100&buildTypeId=Paddle_PrCi&tab=buildLog&_focus=7358) says

> [23:13:12]	[Step 1/1] F0606 23:13:10.064039 14458 LightNetwork.cpp:397] Check failed: error >= 0 ERROR connecting to 127.0.0.1: Connection refused [111]

The [one from test_TrainerOnePass](http://172.19.32.20:8111/viewLog.html?buildId=1100&buildTypeId=Paddle_PrCi&tab=buildLog&_focus=8163) says

> [23:13:35]	[Step 1/1] F0606 23:13:34.009950 14620 LightNetwork.cpp:397] Check failed: error >= 0 ERROR connecting to 127.0.0.1: Connection refused [111]

These are the same error.  The source code around `paddle/pserver/LightNetwork.cpp:397` is

```cpp
 /// Now connect to the server
  int retry_second = 0;
  int error = 0;
  do {
    error = connect(sockfd, (sockaddr *)&serv_addr, sizeof(serv_addr));
    if (error == ECONNREFUSED) {
      LOG(WARNING) << "connection refused by pserver, try again!";
      if (retry_second++ >= 7) {
        LOG(FATAL) << "connection refused by pserver, maybe pserver failed!";
      }
      std::this_thread::sleep_for(std::chrono::seconds(1));
    } else {
      PCHECK(error >= 0) << "ERROR connecting to " << serverAddr;
    }
  } while (error == ECONNREFUSED);
```

It seems complaining cannot connect to the parameter server.
