### ISSUE TITLE
lod tensor 如何实现argmax

### ISSUE THREAD

**Issue by xxxsssyyy** [PaddlePaddle/Paddle#24014]
想实现的操作：
举例: 现在有一个lodTensor 
lod为 [ [0, 2, 5] ]
data 为  [ [1.1, 2.1, 5.2] ,
                 [5.2, 0.1, 4.3] ,
                [0.2, 10.5, 8.3] ,
                [1, 2.5, 3.3] ,
                [7.1, 2.1, 5.9] ,
               ]

想通过一个argmax操作 对axis = -1
得到的
lod 为[ [0, 2, 5] ]
data 为 [[2] [0] [1] [2] [0]]

现在的代码为:
```
emission = fluid.layers.fc(
            size=label_dict_len,
            input=bigru_output,
            param_attr=fluid.ParamAttr(
                initializer=fluid.initializer.Uniform(
                    low=-init_bound, high=init_bound),
                regularizer=fluid.regularizer.L2DecayRegularizer(
                    regularization_coeff=1e-4))
        )
softmax_decode = fluid.layers.argmax(x=emission, axis=-1)
```

目前的问题：结果中softmax_decode 的lod为空的，想问一下如何解决（主要是实现我上面的需求）

**Comment by chenwhql** [comment]
您好，我看了下源码，fluid.layers.argmax没有保留输入到输出的LoD信息，我反馈一下，后续安排同学修复

**Comment by xxxsssyyy** [comment]
这个问题目前有什么替代方案吗

**Comment by chenwhql** [comment]
> 这个问题目前有什么替代方案吗

应该没有

**Comment by xxxsssyyy** [comment]
您好，这个什么时候修复？修复好的话需要怎么更新paddle才能使用呢

**Comment by wawltor** [comment]
> 您好，这个什么时候修复？修复好的话需要怎么更新paddle才能使用呢
嗯嗯，我们内部对了一下，觉得您这种用法可能不太正确；首先ArgMax op是不支持LodTensor输入的，其次是argmax op输入输出的Lod 信息也不应该相同，修复之后会导致功能歧义；

是否可以通过lod_reset来实现你想要的功能吗？

**Comment by wawltor** [comment]
> 您好，这个什么时候修复？修复好的话需要怎么更新paddle才能使用呢


嗯嗯，我们内部对了一下，觉得您这种用法可能不太正确；首先ArgMax op是不支持LodTensor输入的，其次是argmax op输入输出的Lod 信息也不应该相同，修复之后会导致功能歧义；
是否可以通过lod_reset来实现你想要的功能吗？

**Comment by wawltor** [comment]
已解决问题
