### ISSUE TITLE
prelu api

### ISSUE THREAD

**Issue by lazyjek** [PaddlePaddle/Paddle#2405]
没有定义prelu的接口，activation func只定义了brelu，softrelu和relu函数，而且好像也没有完整的说明文档。请教一下如果想用prelu的话需要怎么修改接口呢。

**Comment by lcy-seso** [comment]
你好，PaddlePaddle 目前是实现了`prelu` 激活函数，https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/trainer/config_parser.py#L1727
但在 `config_parser_helpers` 中没有添加 `python` 接口。我来加上。

**Comment by lazyjek** [comment]
请问加上以后是不是需要更新安装包重新安装？大约什么时候发布呢？

**Comment by lcy-seso** [comment]
hi @lazyjek  I add `prelu` in this PR https://github.com/PaddlePaddle/Paddle/pull/2412.

**Comment by lcy-seso** [comment]
可以不重新安装，在原来的安装环境中，替换掉修改的这几个python脚本即可。

使用方法如下：

```python
import paddle.v2.data_type as data_type
import paddle.v2 as paddle

data = paddle.layer.data(name='input', type=data_type.dense_vector(64))
y = paddle.layer.prelu(data)
```
由于 `prelu` 有需要学习的参数，在`PaddlePaddle` 是一个 layer。
