### ISSUE TITLE
训练报错PaddleCheckError: the latest update of worker 0 is 900 secs ago

### ISSUE THREAD

**Issue by zhaoyang1708** [PaddlePaddle/Paddle#24050]
本地测试过可以跑，cpu集群训练，使用的是paddlecloud平台的paddle1.6.1
PaddleCheckError: the latest update of worker 0 is 900 secs ago, we doubt the the worker is not alive and this may have a bad effect on the fitting result, please check at [/paddle/paddle/fluid/operators/distributed/heart_beat_monitor.cc:83]
W0421 16:27:08.119271  1623 init.cc:205] *** Aborted at 1587457628 (unix time) try "date -d @1587457628" if you are using GNU date ***
W0421 16:27:08.135936  1623 init.cc:205] PC: @                0x0 (unknown)
W0421 16:27:08.153251  1623 init.cc:205] *** SIGABRT (@0x1f50000059f) received by PID 1439 (TID 0x7f5ae6bd2700) from PID 1439; stack trace: ***
W0421 16:27:08.155309  1623 init.cc:205]     @     0x7f5bbfddd160 (unknown)
W0421 16:27:08.157927  1623 init.cc:205]     @     0x7f5bbf34b3f7 __GI_raise
W0421 16:27:08.159860  1623 init.cc:205]     @     0x7f5bbf34c7d8 __GI_abort
W0421 16:27:08.166512  1623 init.cc:205]     @     0x7f5a906f2c65 __gnu_cxx::__verbose_terminate_handler()
W0421 16:27:08.167445  1623 init.cc:205]     @     0x7f5a906f0e06 __cxxabiv1::__terminate()
W0421 16:27:08.168593  1623 init.cc:205]     @     0x7f5a906f0e33 std::terminate()
W0421 16:27:08.169505  1623 init.cc:205]     @     0x7f5a90743935 execute_native_thread_routine
W0421 16:27:08.171325  1623 init.cc:205]     @     0x7f5bbfdd51c3 start_thread
W0421 16:27:08.173754  1623 init.cc:205]     @     0x7f5bbf3fd12d __clone
W0421 16:27:08.175593  1623 init.cc:205]     @                0x0 (unknown)
任务日志链接 http://10.182.22.12:8910/fileview.html?type=logsdir&path=/&instance=1316.app-user-20200421140556-53650--zhaoyang29_online_novelbsq_paddlecloud

**Comment by yongqiangma** [comment]
paddle有一个心跳机制， 就是在异步训练的情况下，为了防止有节点异常退出(但是整个训练还是可以继续的) 导致效果波动， 会有一个机制， 就是0号会记录上一次训练节点梯度的更新时间， 训练没有终止的情况下， 有节点超过15分钟不更新梯度， 则会报刚那个问题， 认为训练异常， 直接终止。
