### ISSUE TITLE
基于paddle的lib编译新程序时电脑卡死

### ISSUE THREAD

**Issue by tangbozhang** [PaddlePaddle/Paddle#24065]
版本、环境信息：
1）PaddlePaddle版本：1.7.2
2）CPU：i7-9300H   16g内存
4）系统环境：win10家庭中文版、Visual Studio 2015 update3 C++ 编译
5）paddle安装包 “cpu_avx_mkl”- |fluid_inference.zip （直接官网下载：https://www.paddlepaddle.org.cn/documentation/docs/zh/advanced_guide/inference_deployment/inference/windows_cpp_inference.html）

自己新写的工程，调用paddle 的头文件和lib库，

编译过程中内存和硬盘速度会占满（100%），一直在编译中，半小时后还是如此，应该是已经卡死
，关闭编译后都恢复正常。
生成的工程dll也无法使用。
具体见下面截图
![image](https://user-images.githubusercontent.com/53244607/79940409-35270f80-8494-11ea-8cb8-db48a003aa88.png)

**Comment by MyPandaShaoxiang** [comment]
请问是用的paddle的c++的库进行编译的么，如果paddle的库是预编好的，编译新程序的时候卡死，建议检查新程序的相关编译选项

**Comment by tangbozhang** [comment]
对的，用的是预编译好的paddle库。
并引用其中的第三方库，编译过程中有个警告
“LINK : warning LNK4098: 默认库“MSVCRT”与其他库的使用冲突；请使用 /NODEFAULTLIB:library”，不知是否与这个警告相关？

**Comment by MyPandaShaoxiang** [comment]
和这个应该没有关系，编译过程中内存增大应该和paddle的库没有关系，可以发一下你的具体的操作，分析下可能造成卡死的原因

**Comment by tangbozhang** [comment]
原因找到了，是由于引用的lib库没有继承导致的。
谢谢
