### ISSUE TITLE
如何向静态图中的 fluid.data 部分feed数据，得到相应的结果

### ISSUE THREAD

**Issue by lang101** [PaddlePaddle/Paddle#24069]
x1 = fluid.data(name="x_1", shape=[None, 3, 4], dtype="float32")
x2 = fluid.data(name="x_2", shape=[None, 3, 4], dtype="float32")
x3 = fluid.data(name="x_3", shape=[None, 3, 4], dtype="float32")
x4 = fluid.data(name="x_4", shape=[None, 3, 4], dtype="float32")

output1 = fluid.layers.elementwise_add(x1, x2)
output2 = fluid.layers.elementwise_div(x2, x3)
output3 = fluid.layers.elementwise_add(x3, x4)

place = fluid.CPUPlace()
exe = fluid.Executor(place)
exe.run(fluid.default_startup_program())
input1 = np.random.random(size=(3, 3, 4)).astype("float32")
input2 = np.random.random(size=(3, 3, 4)).astype("float32")
input3 = np.random.random(size=(3, 3, 4)).astype("float32")
input4 = np.random.random(size=(3, 3, 4)).astype("float32")

""" Err Results"""
feedData = {"x_1": input1, "x_2": input2}
fetch_list = [x1.name, x2.name, output1.name]
x1, x2, res1 = exe.run(feed=feedData, fetch_list=fetch_list)
print("x1: ", x1)
print("x2: ", x2)
print("res1: ", res1)

""" True Results"""
feedData = {"x_1": input1, "x_2": input2, "x_3": input3, "x_4": input4}
fetch_list = [x1.name, x2.name, x3.name, x4.name, output1.name]
x1, x2, x3, x4, res1 = exe.run(feed=feedData, fetch_list=fetch_list)
print("x1: ", x1)
print("x2: ", x2)
print("res1: ", res1)

想要达成的目标：
第一步：只feed x1、x2数据到静态图，run后得到output1的结果。
第二步：只feed x2、x3，run后得到output2的结果。
第三步：只feed x3、x4，run后得到output3的结果。
因为需要对output1进行一些操作后，作为新的输入（这里只是一个简单的例子，因为在实际中是要对output1做一些很复杂的操作，当然简单的可以在图中进行，但是复杂的操作写起来太麻烦了。）

实际情况：
运行后在第一步就会报错“Error: Tensor holds no memory. Call Tensor::mutable_data first.”
意思是定义的x3和x4也必须feed数据进去。但是一次性把x1、x2、x3、x4全部feed就成功。

但是相同的功能，在tensorflow中是可以执行的代码如下：
def tf_test():
    x1 = tf.placeholder(tf.float32, [None, 3, 4], "x1")
    x2 = tf.placeholder(tf.float32, [None, 3, 4], "x2")
    x3 = tf.placeholder(tf.float32, [None, 3, 4], "x3")
    x4 = tf.placeholder(tf.float32, [None, 3, 4], "x4")
    outputs1 = tf.add(x1, x2)
    outputs2 = tf.divide(x2, x3)
    outputs3 = tf.multiply(x3, x4)
    input_1 = np.random.random(size=(3, 3, 4)).astype("float32")
    input_2 = np.random.random(size=(3, 3, 4)).astype("float32")
    input_3 = np.random.random(size=(3, 3, 4)).astype("float32")
    input_4 = np.random.random(size=(3, 3, 4)).astype("float32")
    with tf.Session() as sess:
        feedDict = {
            x1: input_1,
            x2: input_2,
        }
        ox1, ox2, o1 = sess.run([x1, x2, outputs1], feedDict)
        print("x1", ox1)
        print("x2", ox2)
        print("o1", o1)
        print()

简而言之，就是在定义静态图时，feed部分数据，相应的只会进行局部运算（是否计算取决于是否有数据feed），得到局部的计算结果，而不是需要全部都要feed才会有结果。

注：我是刚开始接触paddlepaddle，不太熟悉，望回复，谢谢。

**Comment by zhiqiu** [comment]
hi，目前Paddle develop版本的已支持对静态图根据feed/fetch进行剪枝，裁剪掉网络中不影响fetch的节点，并且支持部分feed。你可以在这里下载[dev版安装包](https://www.paddlepaddle.org.cn/documentation/docs/zh/install/Tables.html#whl-dev)，尝试下是否可以解决你的问题。

使用方式，在run的时候加一个参数use_prune=True，如：
`x1, x2, x3, x4, res1 = exe.run(feed=feedData, fetch_list=fetch_list, use_prune=True)`

**Comment by lang101** [comment]
paddle版本：多版本whl包列表-dev  /  cpu-mkl  /  cp37-cp37m （paddlepaddle-0.0.0-cp37-cp37m-linux_x86_64.whl）
加了参数“use_prune=True” run之后报错，err信息如下：
File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/executor.py", line 1067, in run
    six.reraise(*sys.exc_info())
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/six.py", line 693, in reraise
    raise value
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/executor.py", line 1062, in run
    return_merged=return_merged)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/executor.py", line 1130, in _run_impl
    optimize_ops)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/executor.py", line 748, in _prune_program
    pruned_program = origin_program._prune_with_input(feed_names, targets)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/framework.py", line 4154, in _prune_with_input
    raise ValueError("The target variable must have an "
ValueError: The target variable must have an associated operator that generates it.

找了一下之前有相关err的issue，但是还没有明确的原因。

**Comment by zhiqiu** [comment]
hi，你试下fetch_list = [output1.name]是否可以。

**Comment by lang101** [comment]
这样是可以的，谢谢！

**Comment by zhiqiu** [comment]
> 这样是可以的，谢谢！

hi，类似fetch_list = [x1.name, x2.name, output1.name]这样，把feed加入fetch_list的情况，我提PR支持了。

**Comment by lang101** [comment]
好的，再次感谢
