### ISSUE TITLE
如何获取动态图中构建网络的每个层名称，还有如何加载预训练部分参数到模型里

### ISSUE THREAD

**Issue by fxwfzsxyq** [PaddlePaddle/Paddle#24073]
使用的是目前的最新的版本

**Comment by MyPandaShaoxiang** [comment]
你好，可以使用named_sublayers 获取所有Layer的名称， set_dict 可以设置参数到Layer中，具体可以参考https://www.paddlepaddle.org.cn/documentation/docs/zh/api_cn/dygraph_cn/Layer_cn.html#layer

**Comment by fxwfzsxyq** [comment]
那如何取出某一层的参数，比如我要取出某一个卷积层的初始化参数

**Comment by fxwfzsxyq** [comment]
而且set_dict是给所有层赋值吧，我是想单独给某些层赋值，比如1,3,5我定义的值，2,4,6让他默认

**Comment by MyPandaShaoxiang** [comment]
取参数可以用我上面链接中的named_paramter,里面是所有层名和参数的元组

**Comment by MyPandaShaoxiang** [comment]
设置参数可以用add_parameter,上面链接中都有说明

**Comment by fxwfzsxyq** [comment]
感谢回复，通过上述方式我已经可以训练，训练中我发现loss不下降，有没有什么办法判断梯度是否正常更新
