### ISSUE TITLE
how to fine-tune using paddle?

### ISSUE THREAD

**Issue by AoZhang** [PaddlePaddle/Paddle#2408]
I have a network like [rnn_crf.py](https://github.com/PaddlePaddle/Paddle/blob/develop/v1_api_demo/sequence_tagging/rnn_crf.py).

After training with many machine-mining data, the performace is not good enough. And We want to fine-tune the model with some human-tagging data.

What should I do to perform the fine-tuning?

**Comment by pkuyym** [comment]
You can use a pre-trained model to initialize the parameters.

**Comment by guoshengCS** [comment]
Set  the parameter's values by `Parameters.set` before the training step which is defined in `paddle.v2.parameters` may help you perform fine-tuning.

**Comment by AoZhang** [comment]
> You can use a pre-trained model to initialize the parameters.

@pkuyym Using a pre-trained model as the initializtion parameters may work, but what should I do if I want to fix the first two lstm layer in the network?

@guoshengCS 's method may be one solution, I'll try it. But I still trend to train the model in api 'V1'.

**Comment by guoshengCS** [comment]
Close since no update. Please reopen it if necessary.
