### ISSUE TITLE
YoLoV3前向预测的C++代码

### ISSUE THREAD

**Issue by 606BlueStar** [PaddlePaddle/Paddle#24088]
https://www.paddlepaddle.org.cn/documentation/docs/zh/advanced_guide/performance_improving/inference_improving/paddle_tensorrt_infer.html
上面的trt样例已经测试通过了，需要衣服yoloV3-mobilenet的前向代码，类似fluid_inference/sample/paddle-TRT/mobilenet_test.cc

希望您可以把代码发送到我的邮箱：1781843589@qq.com

非常感谢！

**Comment by zhupengyang** [comment]
> fluid_inference/sample/paddle-TRT/mobilenet_test.cc

- 这个不是本repo的文件吧
- 代码建议自己尝试
