### ISSUE TITLE
The documentation of building doc is not consistent with code.

### ISSUE THREAD

**Issue by lcy-seso** [PaddlePaddle/Paddle#2409]
[This documentation](http://www.paddlepaddle.org/develop/doc_cn/howto/dev/write_docs_cn.html#id2) tells how to build PaddlePaddle's doc. This section
http://www.paddlepaddle.org/develop/doc_cn/howto/dev/write_docs_cn.html#id2 says by running 
```bash
bash build_docs.sh local
```
the documents are built in a local environment rather than in Docker environment.
But it looks that this script does not support a `local` parameter and only works with Docker.

**Comment by luotao1** [comment]
You can use `make paddle_docs paddle_docs_cn` to build in a local environment.
I will add this command later.

**Comment by lcy-seso** [comment]
@luotao1 thank you.

**Comment by QiJune** [comment]
Yes, the build_doc script was modified, and the local building method was removed. But the doc has not updated yet.

**Comment by wangkuiyi** [comment]
I will try update the document after https://github.com/PaddlePaddle/Paddle/issues/2409 is merged.
