### ISSUE TITLE
[Paddle-TRT] potential memory leak

### ISSUE THREAD

**Issue by jeng1220** [PaddlePaddle/Paddle#24107]
`IPlugin*::initialize` and `IPlugin*::terminate` should be always implemented as a pair. Also, resources acquired (e.g. malloc, new \*, cuadMalloc\*, \*Create\*, etc) in IPlugin*::initialize should be released in `IPlugin*::terminate`. Otherwise, it causes memory leak.

I fix a plugin as example, see #24106. Following plugins have the same bug **at least**:

- InstanceNormPlugin
- PReluPlugin
- SkipLayerNormPluginDynamic

Read https://docs.nvidia.com/deeplearning/sdk/tensorrt-developer-guide/index.html#ipluginext to know more.

**Comment by jeng1220** [comment]
@NHZlX 
This is a serious bug. Please assign someone to fix it.

**Comment by NHZlX** [comment]
新版本lib 给到后会进行解决。
