### ISSUE TITLE
multi gpu error using dygraph

### ISSUE THREAD

**Issue by littlecrab999** [PaddlePaddle/Paddle#24116]
paddle1.7
code 

def train():
    place = fluid.CUDAPlace(dygraph.parallel.Env().dev_id)
    #place = fluid.CUDAPlace(1)
    with dygraph.guard(place):
        strategy = dygraph.parallel.prepare_context()
        print(strategy.nranks)
        init_lr = 0.001
        lr_update_step = 50000
        lr = dygraph.PiecewiseDecay(boundaries=[lr_update_step, lr_update_step*2, lr_update_step*3],values=[init_lr, init_lr*0.5, init_lr*0.5*0.5], begin=0)

        ans_path = "./mscoco_train2014_annotations.json"
        que_path = "./Questions_Train_mscoco/OpenEnded_mscoco_train2014_questions.json"
        coco_path = "./train2014"

        Dataset = Dataloader(ans_path, que_path, coco_path)
        train_loader = Dataset.loader(mode='train')
        train_loader = fluid.contrib.reader.distributed_batch_reader(train_loader)
        valid_loader = Dataset.loader(mode='valid')
        valid_loader = fluid.contrib.reader.distributed_batch_reader(valid_loader)

        model = VQAModule("Vqa_model", Dataset.get_question_num_tokens())
        model.train()

        optimizer = fluid.optimizer.AdamOptimizer(learning_rate=lr,
                                                  parameter_list=model.get_train_parameters())

        model = dygraph.parallel.DataParallel(model, strategy)
        EPOCH_NUM = 10
        for epoch_id in range(2, EPOCH_NUM):
            model.train()
            for batch_id, data in enumerate(train_loader()):

                #img, question, answer = data
                model.train()
                img = np.array([x[0].reshape(3,448,448) for x in data]).astype('float32')
                question = np.array([x[1] for x in data]).astype('int64')
                print(question.shape)
                print(img.shape)
                answer = np.array([x[2] for x in data]).astype('int64').reshape(-1, 1)
                img = dygraph.to_variable(img)
                question = dygraph.to_variable(question)
                answer = dygraph.to_variable(answer)

                #model.train()
                predict = model(question, img)
                loss = fluid.layers.cross_entropy(predict, answer)
                avg_loss = fluid.layers.mean(loss)

                avg_loss.backward()
                #print(type(model) == VQAModule)
                model.apply_collective_grads()
                optimizer.minimize(avg_loss)
                model.clear_gradients()
                if batch_id%200==0:
                    acc = fluid.layers.accuracy(predict, answer, k=3)
                    print("epoch: {}, batch: {}, loss is: {}, acc:{}".format(
                        epoch_id, batch_id, avg_loss.numpy(), acc.numpy()))

            fluid.save_dygraph(model.state_dict(), './output/vqa_{}'.format(epoch_id))
            fluid.save_dygraph(optimizer.state_dict(), './output/vqa_{}'.format(epoch_id))

            model.eval()
            accuracy3, accuracy1 = [], []
            for batch_id, data in enumerate(valid_loader()):
                img, question, answer = data
                img = dygraph.to_variable(img)
                question = dygraph.to_variable(question)
                answer = dygraph.to_variable(answer)
                predict = model(question, img)
                acc3 = fluid.layers.accuracy(input=predict, label=answer, k=3)
                acc1 = fluid.layers.accuracy(input=predict, label=answer, k=1)
                accuracy3.append(acc3.numpy())
                accuracy1.append(acc1.numpy())
            print("Valid: epoch:{}, acc3:{}, acc1:{}".format(epoch_id, np.mean(accuracy3), np.mean(accuracy1)))

**error**

Traceback (most recent call last):
  File "train.py", line 127, in <module>
    train()
  File "train.py", line 57, in train
    predict = model(question, img)
  File "/home/work/chenchaojie/env/python3/lib/python3.6/site-packages/paddle/fluid/dygraph/layers.py", line 304, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/home/work/chenchaojie/env/python3/lib/python3.6/site-packages/paddle/fluid/dygraph/parallel.py", line 149, in forward
    return self._layers(*inputs, **kwargs)
  File "/home/work/chenchaojie/env/python3/lib/python3.6/site-packages/paddle/fluid/dygraph/layers.py", line 304, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/home/work/chenchaojie/vqa/model.py", line 175, in forward
    v = self.backbone(img, ['block3'])['block3']
  File "/home/work/chenchaojie/env/python3/lib/python3.6/site-packages/paddle/fluid/dygraph/layers.py", line 304, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/home/work/chenchaojie/vqa/resnet.py", line 278, in forward
    res = self.conv_bn_init(inputs)
  File "/home/work/chenchaojie/env/python3/lib/python3.6/site-packages/paddle/fluid/dygraph/layers.py", line 304, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/home/work/chenchaojie/vqa/resnet.py", line 57, in forward
    res = self.conv(inputs)
  File "/home/work/chenchaojie/env/python3/lib/python3.6/site-packages/paddle/fluid/dygraph/layers.py", line 301, in __call__
    self._parameters.values())
  File "/home/work/chenchaojie/env/python3/lib/python3.6/site-packages/paddle/fluid/dygraph/parallel_helper.py", line 43, in _broadcast_parameters
    collective._broadcast(param, 0, sync_mode=True)
  File "/home/work/chenchaojie/env/python3/lib/python3.6/site-packages/paddle/fluid/layers/collective.py", line 60, in _broadcast
    "root": root})
  File "/home/work/chenchaojie/env/python3/lib/python3.6/site-packages/paddle/fluid/layer_helper.py", line 43, in append_op
    return self.main_program.current_block().append_op(*args, **kwargs)
  File "/home/work/chenchaojie/env/python3/lib/python3.6/site-packages/paddle/fluid/framework.py", line 2516, in append_op
    kwargs.get("stop_gradient", False))
  File "/home/work/chenchaojie/env/python3/lib/python3.6/site-packages/paddle/fluid/dygraph/tracer.py", line 39, in trace_op
    not stop_gradient)
paddle.fluid.core_avx.EnforceNotMet:

**command**
python3  -m paddle.distributed.launch  --selected_gpus=0,1  train.py

same command with single gpu is ok,but if use more than one cpu for the selected_gpus param, error is generated

**Comment by zhupengyang** [comment]
nccl版本需要大于247

**Comment by Lucien7786** [comment]
> nccl版本需要大于247

nccl 256也不好使，cuda 9.0, cudnn 7.6, 单卡没问题。
------------------
-----------  Configuration Arguments -----------
cluster_node_ips: 127.0.0.1
log_dir: None
node_ip: 127.0.0.1
print_config: True
selected_gpus: 0,1,2,3
started_port: 6170
training_script: train.py
training_script_args: []
use_paddlecloud: False
------------------------------------------------
trainers_endpoints: 127.0.0.1:6170,127.0.0.1:6171,127.0.0.1:6172,127.0.0.1:6173 , node_id: 0 , current_node_ip: 127.0.0.1 , num_nodes: 1 , node_ips: ['127.0.0.1'] , nranks: 4

----------------------
Error Message Summary:
----------------------
Error: Place CUDAPlace(0) is not supported, Please check that your paddle compiles with WITH_GPU option or check that your train process hold the correct gpu_id if you use Executor at (/paddle/paddle/fluid/platform/device_context.cc:67)
W0623 21:15:19.671488  7100 init.cc:209] Warning: PaddlePaddle catches a failure signal, it may not work properly
W0623 21:15:19.671520  7100 init.cc:211] You could check whether you killed PaddlePaddle thread/process accidentally or report the case to PaddlePaddle
W0623 21:15:19.671541  7100 init.cc:214] The detail failure signal is:

W0623 21:15:19.671547  7100 init.cc:217] *** Aborted at 1592918119 (unix time) try "date -d @1592918119" if you are using GNU date ***
2020-06-23 21:15:19,671-ERROR: ABORT!!! Out of all 4 trainers, the trainer process with rank=[1, 2, 3] was aborted. Please check its log.
ERROR 2020-06-23 21:15:19,671 launch.py:284] ABORT!!! Out of all 4 trainers, the trainer process with rank=[1, 2, 3] was aborted. Please check its log.
