### ISSUE TITLE
Fleet训练 日志和多卡问题

### ISSUE THREAD

**Issue by shippingwang** [PaddlePaddle/Paddle#24122]
在使用fleet训练时候，有log和多卡输出的一些疑问：

如下方式

```bash
python -m paadle.distributed.launch \
    --log_dir = "./log" \
    train.py
```

这样会
- 在屏幕上输出trainer的config信息并卡住
- log文件会保存在log_dir中
- 程序实际在运行中

NOTE：这种默认方式行为很不一致，既然都存了log 为什么屏幕还是会输出config而且卡住？

若指定log_dir 并且加 重定向
```bash
python -m paddle.distributed.launch \
   --log_dir = "./log" \
    train.py >log.txt 2>&1 &
```
- config信息会重定向到log.txt中
- 程序的log还是会在log_dir里

---

若 不指定 --log_dir
- 不会自动保存文件
- 屏幕输出，输出多卡重复且不一样的信息（在程序中做num_trainer判断会解决输出多张卡的问题），但是多张卡的输出是不一样，这里fleet怎么可以做到多卡输出是一致的？即worker.0 1 2 3的train loss和valid loss一致？

若 不指定 --log_dir 并且加 重定向 > 导出日志
nohup python -m paddle.distributed.launch \
    train.py >log3.txt 2>&1 &

- log最后还是有 config的信息

ps：在此基础 继续 指定 --print_config=0
config 没有更改

**Comment by zhupengyang** [comment]
https://github.com/PaddlePaddle/Fleet fleet相关问题可以去这里提问

**Comment by shippingwang** [comment]
> https://github.com/PaddlePaddle/Fleet fleet相关问题可以去这里提问

fleet集成在paddle里吧....我为什么要再粘贴过去
我写在这里是觉得 可能其他用户出现相似的疑问，那fleet上个issue都去年的事了...

**Comment by sandyhouse** [comment]
> 这样会
> 
> 在屏幕上输出trainer的config信息并卡住
> log文件会保存在log_dir中
> 程序实际在运行中

为了避免输出config信息卡住的问题，可以后台运行命令，如
python -m paadle.distributed.launch \
    --log_dir = "./log" \
    train.py &

>这种默认方式行为很不一致，既然都存了log 为什么屏幕还是会输出config而且卡住？
config信息和log是两个不同的概念。config是机器配置相关的一些信息，如trainer的ip地址，端口等。log里面实际存储的是运行的训练脚本的日志。

> 屏幕输出，输出多卡重复且不一样的信息（在程序中做num_trainer判断会解决输出多张卡的问题），但是多张卡的输出是不一样，这里fleet怎么可以做到多卡输出是一致的？即worker.0 1 2 3的train loss和valid loss一致？
如果没有--log_dir选项，所有的日志都会输出到终端，导致多个trainer的信息混杂显示。fleet本身并不保证多卡的输出是一致的（如loss），这是因为一般而言各个卡上的训练数据是不一样的，所以采用数据并行模式各个卡计算得到的loss值也是不一样的。
