### ISSUE TITLE
ZeroCopyRun()崩溃

### ISSUE THREAD

**Issue by tangbozhang** [PaddlePaddle/Paddle#24146]
版本、环境信息：
1）PaddlePaddle版本：1.7.2
2）CPU：i7-9300H 16g内存
4）系统环境：win10家庭中文版、Visual Studio 2015 update3 C++ 编译
5）paddle安装包 “cpu_avx_mkl”- |fluid_inference.zip （直接官网下载：https://www.paddlepaddle.org.cn/documentation/docs/zh/advanced_guide/inference_deployment/inference/windows_cpp_inference.html）

自己新写的工程，调用paddle 的头文件和lib库，编译通过，运行到m_predictor_->ZeroCopyRun();崩溃，无日志
![image](https://user-images.githubusercontent.com/53244607/80228741-02db0500-8682-11ea-94b1-81c36514ad75.png)
模型配置如下，模型在python下运行正常，模型路径也正常
               paddle::AnalysisConfig config;
		config.SetModel(model_dir + "/paddle_model",
			model_dir + "/paddle_params");
		config.SwitchUseFeedFetchOps(false);// 关闭feed和fetch OP使用，使用ZeroCopy接口必须设置此项
		config.SwitchSpecifyInputNames(true);
		// Memory optimization
		config.EnableMemoryOptim();
		m_predictor_ = std::move(CreatePaddlePredictor(config));

**Comment by jiweibo** [comment]
请问下非调试模式下有报错信息吗，没有报错信息无法确定问题

**Comment by tangbozhang** [comment]
执行到m_predictor_->ZeroCopyRun()时，直接跳过下面的进到try catch(...),没有报错信息，也不影响后面其他功能运行

**Comment by tangbozhang** [comment]
@jiweibo

**Comment by jiweibo** [comment]
可以先用官网提供的mobilenet示例跑一下，看下是库的问题，还是程序的问题

https://www.paddlepaddle.org.cn/documentation/docs/zh/advanced_guide/inference_deployment/inference/native_infer.html#a-name-c-c-a

**Comment by tangbozhang** [comment]
按官方的例子跑 了下，还是ZeroCopyRun()有问题
![image](https://user-images.githubusercontent.com/53244607/80281860-b99dba80-8740-11ea-9a5d-fe065149b85b.png)

**Comment by tangbozhang** [comment]
![image](https://user-images.githubusercontent.com/53244607/80281889-e4880e80-8740-11ea-928c-0c915950eaee.png)

**Comment by tangbozhang** [comment]
[
![image](https://user-images.githubusercontent.com/53244607/80281896-f10c6700-8740-11ea-9ac2-7e30314346ce.png)
](url)

**Comment by tangbozhang** [comment]
D:\>cd D:\codedevelop\tce\ai\paddle\paddle-dll\Paddle\paddle\fluid\inference\api\demo_ci\build\Release

D:\codedevelop\tce\ai\paddle\paddle-dll\Paddle\paddle\fluid\inference\api\demo_ci\build\Release>windows_mobilenet.exe  --modeldir=D:\run-environment\RUN-PADDLE\objectdetection\model\test
WARNING: Logging before InitGoogleLogging() is written to STDERR
I0425 22:00:45.333626 18456 analysis_predictor.cc:84] Profiler is deactivated, and no profiling report will be generated.
I0425 22:00:45.351575 18456 analysis_predictor.cc:833] MODEL VERSION: 1.6.1
I0425 22:00:45.351575 18456 analysis_predictor.cc:835] PREDICTOR VERSION: 1.7.2
e[1me[35m--- Running analysis [ir_graph_build_pass]e[0m
e[1me[35m--- Running analysis [ir_graph_clean_pass]e[0m
e[1me[35m--- Running analysis [ir_analysis_pass]e[0m
e[32m--- Running IR pass [simplify_with_basic_ops_pass]e[0m
e[32m--- Running IR pass [attention_lstm_fuse_pass]e[0m
e[32m--- Running IR pass [seqconv_eltadd_relu_fuse_pass]e[0m
e[32m--- Running IR pass [seqpool_cvm_concat_fuse_pass]e[0m
e[32m--- Running IR pass [fc_lstm_fuse_pass]e[0m
e[32m--- Running IR pass [mul_lstm_fuse_pass]e[0m
e[32m--- Running IR pass [fc_gru_fuse_pass]e[0m
e[32m--- Running IR pass [mul_gru_fuse_pass]e[0m
e[32m--- Running IR pass [seq_concat_fc_fuse_pass]e[0m
e[32m--- Running IR pass [fc_fuse_pass]e[0m
e[32m--- Running IR pass [repeated_fc_relu_fuse_pass]e[0m
e[32m--- Running IR pass [squared_mat_sub_fuse_pass]e[0m
e[32m--- Running IR pass [conv_bn_fuse_pass]e[0m
I0425 22:00:45.780429 18456 graph_pattern_detector.cc:101] ---  detected 75 subgraphs
e[32m--- Running IR pass [conv_eltwiseadd_bn_fuse_pass]e[0m
e[32m--- Running IR pass [conv_transpose_bn_fuse_pass]e[0m
e[32m--- Running IR pass [conv_transpose_eltwiseadd_bn_fuse_pass]e[0m
e[32m--- Running IR pass [is_test_pass]e[0m
e[32m--- Running IR pass [runtime_context_cache_pass]e[0m
e[1me[35m--- Running analysis [ir_params_sync_among_devices_pass]e[0m
e[1me[35m--- Running analysis [adjust_cudnn_workspace_size_pass]e[0m
e[1me[35m--- Running analysis [inference_op_replace_pass]e[0m
e[1me[35m--- Running analysis [ir_graph_to_program_pass]e[0m
I0425 22:00:45.905097 18456 analysis_predictor.cc:462] ======= optimize end =======
I0425 22:00:45.905097 18456 naive_executor.cc:105] ---  skip [feed], feed -> image_shape
I0425 22:00:45.906093 18456 naive_executor.cc:105] ---  skip [feed], feed -> image
I0425 22:00:45.909085 18456 naive_executor.cc:105] ---  skip [save_infer_model/scale_0], fetch -> fetch
I0425 22:00:45.910084 18456 windows_mobilenet.cc:66] Usage: ZeroCopyRun 前

D:\codedevelop\tce\ai\paddle\paddle-dll\Paddle\paddle\fluid\inference\api\demo_ci\build\Release>

**Comment by tangbozhang** [comment]
和模型版本有关系吗？
“I0425 22:00:45.351575 18456 analysis_predictor.cc:833] MODEL VERSION: 1.6.1
I0425 22:00:45.351575 18456 analysis_predictor.cc:835] PREDICTOR VERSION: 1.7.2”

**Comment by tangbozhang** [comment]
在python下使用相同模型，运行是正常的

**Comment by OliverLPH** [comment]
![predict_log](https://user-images.githubusercontent.com/14963836/80295467-6e69c300-87a5-11ea-94f5-509e850df9c7.png)
![predict_codes](https://user-images.githubusercontent.com/14963836/80295470-732e7700-87a5-11ea-8d33-333e8ef1f9e1.png)
我这边试着用`ZeroCopyRun`这个接口跑了下 mobilenet模型，应该是不会崩溃的，可以正常预测。
但Windows目前报错信息不是很易用，因此可能是其他原因导致的错误，但没有报出来。

> 按官方的例子跑 了下，还是ZeroCopyRun()有问题

看到你这个截图里面有 `openblas.dll`，但你在issue开始描述的是使用的 `cpu_avx_mkl` 这个lib库。
那应该和执行文件放在一起的 dll应该是如下几个
![动态库](https://user-images.githubusercontent.com/14963836/80295519-da4c2b80-87a5-11ea-8689-5a13b41446d9.png)
可以再看下是不是这里有问题。

**Comment by silingtong123** [comment]
Hi,你好
1. 你需要确定你使用的预测库是使用的mkl还是openblass预测库
2. 推荐你使用windows demo编译脚本测试demo的运行情况，具体使用方式可参考官网：
https://www.paddlepaddle.org.cn/documentation/docs/zh/advanced_guide/inference_deployment/inference/windows_cpp_inference.html
![image](https://user-images.githubusercontent.com/35439432/80296138-0ae29400-87ab-11ea-9a5e-be222fc06b76.png)

运行选项如截图：
1).  cpu_avx_mkl 
     PaddlePaddle版本：1.7.2
![image](https://user-images.githubusercontent.com/35439432/80296041-6e1ff680-87aa-11ea-9d0c-3dafbeb10e23.png)

2). cpu_avx_openblas
    PaddlePaddle版本：1.7.2
![image](https://user-images.githubusercontent.com/35439432/80296336-a6283900-87ac-11ea-8478-eef4dccf68b6.png)


3. 经过测试这两个预测库在demo上无异常，如果需要进一步跟进，请提供与服务解耦的单测

**Comment by tangbozhang** [comment]
重新下载paddle库，在demo调用mobilenet模型正常。但demo在调用自己训练的模型（ShuffleNetV2_YOLOv3），还是ZeroCopyRun()有问题，图像尺寸已按模型训练时尺寸设置。
![image](https://user-images.githubusercontent.com/53244607/80307070-81a67e00-87f9-11ea-879e-5140242c575c.png)

**Comment by silingtong123** [comment]
方便提供你训练的模型吗？猜测是模型使用方面的问题？

**Comment by tangbozhang** [comment]
同样的模型，python下预测正常。应该是哪里配置的问题导致的。模型比较大如何发您？
pthon预测源码如下
![image](https://user-images.githubusercontent.com/53244607/80310571-04d1cf00-880e-11ea-88a6-48c0ade806d3.png)

**Comment by tangbozhang** [comment]
这是ai studio 地址：https://aistudio.baidu.com/bdcpu7/user/97222/335880/notebooks/335880.ipynb?redirects=1。模型已上传：code/model/freeze_model 
@silingtong123

**Comment by silingtong123** [comment]
1. Yolov3模型应该有2个输入，但是你的C++代码里只有一个
python:
![image](https://user-images.githubusercontent.com/35439432/80327426-9ec96400-886e-11ea-9718-469c1de64297.png)

C++:
![image](https://user-images.githubusercontent.com/35439432/80327509-e8b24a00-886e-11ea-90a9-361d1c58b51d.png)

应该还有一个input_t2 = predictor->GetInputTensor(input_names[1]); 
还一个输入没有赋值，所以报错，官方案例的模型是只有一个输入的

2. 这个地址我无法访问

**Comment by tangbozhang** [comment]
不好意思，昨晚忘了公开了，现在已经公开。paddle里面是否有两个输入的例子呢？
@silingtong123

**Comment by silingtong123** [comment]
1. 暂时没有，不过两个输入和一个输入是一样的设置方式
![image](https://user-images.githubusercontent.com/35439432/80328848-2618d680-8873-11ea-8345-04aefa7e8503.png)
第二个输入input_t2的shape=[batch_size2, channels2, height2, width2]，数据为input2，类似input的初始化方式，再调用copy_from_cpu(input2)

2. 如果不清楚模型的输入，可以使用软件查看输入，如Netron， 模型名字改为__model__，可查看模型信息，如图
![image](https://user-images.githubusercontent.com/35439432/80329185-12ba3b00-8874-11ea-8436-654fab449ca5.png)

**Comment by tangbozhang** [comment]
![image](https://user-images.githubusercontent.com/53244607/80330288-595d6480-8877-11ea-8cbe-0819d8d8885d.png)

**Comment by tangbozhang** [comment]
模型输入，显示一个
![image](https://user-images.githubusercontent.com/53244607/80332457-79902200-887d-11ea-90c5-91a72fd8d387.png)

**Comment by silingtong123** [comment]
![image](https://user-images.githubusercontent.com/35439432/80333205-e1476c80-887f-11ea-9ee0-eefad4c7cabb.png)
你需要点击一下这个0,看右边的INPUTS信息，确定是不是有两个输入,左边一个可能对应右边多个input的

**Comment by tangbozhang** [comment]
还是不行，帮忙看看是哪里问题
![image](https://user-images.githubusercontent.com/53244607/80333793-d1308c80-8881-11ea-9511-8dbe95285e4f.png)

**Comment by tangbozhang** [comment]
![image](https://user-images.githubusercontent.com/53244607/80333825-ed342e00-8881-11ea-94c7-1609ca70dcaf.png)

**Comment by tangbozhang** [comment]
这是ai studio 地址：https://aistudio.baidu.com/aistudio/projectdetail/335880。模型已上传：code/model/freeze_model

**Comment by silingtong123** [comment]
image_shape不能初始化为0
![image](https://user-images.githubusercontent.com/35439432/80334563-2a012480-8884-11ea-8cff-0abd8b7cbf7b.png)
yolov3一般是608

**Comment by tangbozhang** [comment]
修改后，还是不行，麻烦指导下。python里调试信息也显示了
![image](https://user-images.githubusercontent.com/53244607/80336522-11940880-888a-11ea-81a5-ae1ecf247581.png)

**Comment by tangbozhang** [comment]
这是ai studio 项目地址：https://aistudio.baidu.com/aistudio/projectdetail/335880。
模型所在目录：code/model/freeze_model
ZeroCopyRun()这个问题还是未解决，求大神支援

**Comment by silingtong123** [comment]
正在跟进中，有进展会立即回复，可能是框架在windows的问题

**Comment by silingtong123** [comment]
1. 问题出现在image_shape的设置不应该为float,应该为int
![image](https://user-images.githubusercontent.com/35439432/80355372-998a0a80-88aa-11ea-8658-36ddd025f211.png)

2. 旧版本训练的模型为float，但是在新版本的预测库中应该为int
![image](https://user-images.githubusercontent.com/35439432/80355748-0dc4ae00-88ab-11ea-8b28-1d84a9bf2a03.png)
官方API地址：https://www.paddlepaddle.org.cn/documentation/docs/zh/api_cn/layers_cn/yolo_box_cn.html

**Comment by tangbozhang** [comment]
官方demo和自己的程序均已调通。感谢这段时间给我帮助的朋友，特别是以下几个朋友：
@silingtong123 @jiweibo @OliverLPH @wanglun
