### ISSUE TITLE
paddle.v2.infer() prints logs, and currently no way to suppress 

### ISSUE THREAD

**Issue by juliecbd** [PaddlePaddle/Paddle#2415]
If we call paddle.v2.infer(), this prints logs every time, and there is currently no way to suppress. Could we fix this issue? 

```text
probs = paddle.infer(
    output_layer=predict, parameters=parameters, input=test_data)
[INFO 2017-06-07 12:06:37,678 networks.py:1482] The input order is [pixel]
[INFO 2017-06-07 12:06:37,678 networks.py:1488] The output order is [__fc_layer_2__]
```

**Comment by lcy-seso** [comment]
Please refer to this issue https://github.com/PaddlePaddle/Paddle/issues/2015

you can add this to your script
```python
logger = logging.getLogger('paddle')
logger.setLevel(logging.WARN)
```

**Comment by juliecbd** [comment]
Thank you. I think it’s a good idea to document this for other users.

**Comment by lcy-seso** [comment]
Thank you for the advice, I will add this to the API doc.

**Comment by lcy-seso** [comment]
It seems this problem has been solved, so I close this issue.
