### ISSUE TITLE
优化器报错

### ISSUE THREAD

**Issue by Rayarrow94** [PaddlePaddle/Paddle#24171]
Traceback (most recent call last):
  File "local_train.py", line 16, in <module>
    use_parallel_executor=1
  File "/home/disk2/hubo/model/fluid/item2vec/train.py", line 511, in train
    train_loop(fluid.default_main_program())
  File "/home/disk2/hubo/model/fluid/item2vec/train.py", line 473, in train_loop
    fetch_list=[avg_cost.name])
  File "/home/disk2/hubo/anaconda3/lib/python3.6/site-packages/paddle/fluid/parallel_executor.py", line 311, in run
    return_numpy=return_numpy)
  File "/home/disk2/hubo/anaconda3/lib/python3.6/site-packages/paddle/fluid/executor.py", line 775, in run
    six.reraise(*sys.exc_info())
  File "/home/disk2/hubo/anaconda3/lib/python3.6/site-packages/six.py", line 693, in reraise
    raise value
  File "/home/disk2/hubo/anaconda3/lib/python3.6/site-packages/paddle/fluid/executor.py", line 770, in run
    use_program_cache=use_program_cache)
  File "/home/disk2/hubo/anaconda3/lib/python3.6/site-packages/paddle/fluid/executor.py", line 829, in _run_impl
    return_numpy=return_numpy)
  File "/home/disk2/hubo/anaconda3/lib/python3.6/site-packages/paddle/fluid/executor.py", line 669, in _run_parallel
    tensors = exe.run(fetch_var_names)._move_to_list()
paddle.fluid.core_avx.EnforceNotMet: 

--------------------------------------------
C++ Call Stacks (More useful to developers):
--------------------------------------------
0   std::string paddle::platform::GetTraceBackString<std::string const&>(std::string const&, char const*, int)
1   paddle::platform::EnforceNotMet::EnforceNotMet(std::string const&, char const*, int)
2   paddle::framework::OperatorWithKernel::IndicateVarDataType(paddle::framework::ExecutionContext const&, std::string const&) const
3   paddle::operators::ConcatOpGrad::GetExpectedKernelType(paddle::framework::ExecutionContext const&) const
4   paddle::framework::OperatorWithKernel::ChooseKernel(paddle::framework::RuntimeContext const&, paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&) const
5   paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&, paddle::framework::RuntimeContext*) const
6   paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&) const
7   paddle::framework::OperatorBase::Run(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&)
8   paddle::framework::details::ComputationOpHandle::RunImpl()
9   paddle::framework::details::FastThreadedSSAGraphExecutor::RunOpSync(paddle::framework::details::OpHandleBase*)
10  paddle::framework::details::FastThreadedSSAGraphExecutor::RunOp(paddle::framework::details::OpHandleBase*, std::shared_ptr<paddle::framework::BlockingQueue<unsigned long> > const&, unsigned long*)
11  std::_Function_handler<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> (), std::__future_base::_Task_setter<std::unique_ptr<std::__future_base::_Result<void>, std::__future_base::_Result_base::_Deleter>, void> >::_M_invoke(std::_Any_data const&)
12  std::__future_base::_State_base::_M_do_set(std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> ()>&, bool&)
13  ThreadPool::ThreadPool(unsigned long)::{lambda()#1}::operator()() const

------------------------------------------
Python Call Stacks (More useful to users):
------------------------------------------
  File "/home/disk2/hubo/anaconda3/lib/python3.6/site-packages/paddle/fluid/framework.py", line 2459, in append_op
    attrs=kwargs.get("attrs", None))
  File "/home/disk2/hubo/anaconda3/lib/python3.6/site-packages/paddle/fluid/layer_helper.py", line 43, in append_op
    return self.main_program.current_block().append_op(*args, **kwargs)
  File "/home/disk2/hubo/anaconda3/lib/python3.6/site-packages/paddle/fluid/layers/tensor.py", line 297, in concat
    type='concat', inputs=inputs, outputs={'Out': [out]}, attrs=attrs)
  File "/home/disk2/hubo/model/fluid/item2vec/circle_loss.py", line 44, in Circle_Loss
    label = fluid.layers.concat([label_p, label_n], axis=0)
  File "/home/disk2/hubo/model/fluid/item2vec/train.py", line 260, in model
    avg_cost = Circle_Loss(src_fc3, left_fc3, right_fc3)
  File "/home/disk2/hubo/model/fluid/item2vec/train.py", line 392, in train
    data_list, py_reader, avg_cost = model()
  File "local_train.py", line 16, in <module>
    use_parallel_executor=1

----------------------
Error Message Summary:
----------------------
PaddleCheckError: Expected data_type != dafault_data_type, but received data_type:-1 == dafault_data_type:-1.
The Input Variable(Out@GRAD) of concat_grad Op used to determine kernel data type is empty or not LoDTensor or SelectedRows. at [/paddle/paddle/fluid/framework/operator.cc:1203]
  [operator < concat_grad > error]

关联代码：
def Circle_Loss(q, p, n, scale=32, margin=0.25):
    sim_p = fluid.layers.cos_sim(q, p)
    sim_n = fluid.layers.cos_sim(q, n)
    alpha_p = fluid.layers.relu(sim_p * (-1) + 1 + margin)
    alpha_n = fluid.layers.relu(sim_n + margin)
    margin_p = 1 - margin
    margin_n = -margin
    logit_p = scale * alpha_p * (sim_p - margin_p)
    logit_n = scale * alpha_n * (sim_n - margin_n)
    #logit_p = fluid.layers.reshape(scale * alpha_p * (sim_p - margin_p), (-1, 1))
    #logit_n = fluid.layers.reshape(scale * alpha_n * (sim_n - margin_n), (-1, 1))

    label_p = fluid.layers.ones_like(logit_p)
    label_n = fluid.layers.zeros_like(logit_n)
    logit = fluid.layers.concat([logit_p, logit_n], axis=0)
    label = fluid.layers.concat([label_p, label_n], axis=0)
    loss_temp = fluid.layers.cross_entropy(logit, label, soft_label=True)
    #loss_temp = fluid.layers.softmax_with_cross_entropy(logit, label, soft_label=True)

    celoss = fluid.layers.mean(loss_temp)
    return celoss

**Comment by zhiqiu** [comment]
已线下讨论，设置`label.stop_gradient=True`可解决。
该问题在Paddle-1.8+已在框架中统一优化，用户不需要显示地设置`var.stop_gradient=True`，对于所有反向输入都为空的反向op，框架会自动裁剪。详见 https://github.com/PaddlePaddle/Paddle/pull/22246
