### ISSUE TITLE
gpu forward报错，此前报了cudnn的warning

### ISSUE THREAD

**Issue by fxwfzsxyq** [PaddlePaddle/Paddle#24186]
![image](https://user-images.githubusercontent.com/18416103/80329703-bf48ec80-8875-11ea-95d8-129f82c05911.png)
![image](https://user-images.githubusercontent.com/18416103/80329728-cc65db80-8875-11ea-8d47-b73760ef8bec.png)
![image](https://user-images.githubusercontent.com/18416103/80329758-dd165180-8875-11ea-97bf-433df16af428.png)

**Comment by GaoWei8** [comment]
可以先查看一下batch_norm参数传输是否有问题。

**Comment by fxwfzsxyq** [comment]
数据传输是否有问题不是很明白，cpu是能跑的，换gpu就报错了，在ai studio启动的gpu环境是可以跑得

**Comment by GaoWei8** [comment]
那有可能是cudnn版本问题。你的安装包编译环境是cudnn7.6，但是运行机器cudnn环境是7.4。
