### ISSUE TITLE
使用自定义OP后保存预测模型，再加载模型预测时报错

### ISSUE THREAD

**Issue by nuaaceieyty** [PaddlePaddle/Paddle#24185]
我是在在AI Studio上运行的。
写的网络结构里有一个自定义OP，在训练程序里调用此OP无误，保存预测模型也无误。
但加载模型时出现一下报错：
----------------------
Error Message Summary:
----------------------
Error: Invalid python callable id
  [Hint: Expected i < g_py_callables.size(), but received i:2 >= g_py_callables.size():0.] at (/paddle/paddle/fluid/operators/py_func_op.cc:45)
  [operator < py_func > error]
请问这是什么原因？？我应该怎么修改？？

**Comment by GaoWei8** [comment]
错误看起来是py_func报错，从报错信息来看，是没有成功的新增OP。
可以参考[在Python端自定义OP教程](https://www.paddlepaddle.org.cn/documentation/docs/zh/advanced_guide/addon_development/new_op/new_python_op.htmll)确定下新增OP是否有问题。

**Comment by nuaaceieyty** [comment]
> 错误看起来是py_func报错，从报错信息来看，是没有成功的新增OP。
> 可以参考[在Python端自定义OP教程](https://www.paddlepaddle.org.cn/documentation/docs/zh/advanced_guide/addon_development/new_op/new_python_op.htmll)确定下新增OP是否有问题。

我在训练时调用了这个自定义OP，没有问题，应该是新增成功了吧

**Comment by qingqing01** [comment]
@nuaaceieyty save_inference_model不支持包含 py_func。 py_func部分是Python实现，本身也无法在C++预测中用。

**Comment by nuaaceieyty** [comment]
> @nuaaceieyty save_inference_model不支持包含 py_func。 py_func部分是Python实现，本身也无法在C++预测中用。

明白了，谢谢啦
