### ISSUE TITLE
ocr_recognition 模块无法训练，提示“找不到指定的模块”

### ISSUE THREAD

**Issue by titanseason** [PaddlePaddle/Paddle#24200]
直接下载`https://github.com/PaddlePaddle/models`的源码，然后执行
```
python train.py --use_gpu False --parallel=False --model="attention"
```
会提示异常（不指定--model参数也报同样的错误）：
```
Traceback (most recent call last):
  File "train.py", line 18, in <module>
    import paddle.fluid as fluid
  File "C:\Python\Python37\lib\site-packages\paddle\fluid\__init__.py", line 35, in <module>
    from . import framework
  File "C:\Python\Python37\lib\site-packages\paddle\fluid\framework.py", line 35, in <module>
    from . import core
  File "C:\Python\Python37\lib\site-packages\paddle\fluid\core.py", line 194, in <module>
    raise e
  File "C:\Python\Python37\lib\site-packages\paddle\fluid\core.py", line 167, in <module>
    from .core_avx import *
ImportError: DLL load failed: 找不到指定的模块。
```

- 版本、环境信息：
    1）PaddlePaddle版本：1.7.2
    2）CPU：Intel(R) Xeon(R) CPU E5-2680 v4 @2.40GHz
    4）系统环境：Windows Server 2012 R2，Python版本 3.7.7
- 训练信息
    1）单机，CPU训练
- 复现步骤
    在`https://github.com/PaddlePaddle/models`点击`Clone or download`，下载源码，CD至`ocr_recognition`所在的路径，然后执行 `python train.py --use_gpu False --parallel=False --model="attention"`

**Comment by zhwesky2010** [comment]
@titanseason 你好，请问是python37下装好了paddlepaddle吗？麻烦执行一下 C:\Python\Python37\python.exe -m pip install paddlepaddle 更新下环境看下

**Comment by titanseason** [comment]
> 
> 
> @titanseason 你好，请问是python37下装好了paddlepaddle吗？麻烦执行一下 C:\Python\Python37\python.exe -m pip install paddlepaddle 更新下环境看下

我发现有类似的问题，https://github.com/PaddlePaddle/Paddle/issues/22412
我用depends软件，发现了同样缺失了一堆dll文件
![](https://user-images.githubusercontent.com/33515898/73602609-f464dc00-45b1-11ea-84e6-715a39b8eaa9.PNG)

**Comment by zhwesky2010** [comment]
@titanseason 你好，装一下openblas版的paddlepaddle试一下，可能是电脑硬件的原因

**Comment by zhwesky2010** [comment]
@titanseason 
 https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/install/Tables.html#ciwhls-release 这个里面可以下载openblas版本，下载 win_cpu_openblas对应的
