### ISSUE TITLE
SSD_VGG16_512 训练后导出精度严重损失。

### ISSUE THREAD

**Issue by aixier** [PaddlePaddle/Paddle#24233]
**Paddle1.7
detection0.2
python3.7
CPU8
RAM32GB
GPUv100
显存16GB**
模型算法：
https://github.com/PaddlePaddle/PaddleDetection/blob/release/0.2/configs/ssd/ssd_vgg16_512.yml
模型名称：ssd_vgg16
训练参数见附件：

[ssd_vgg16_512.txt](https://github.com/PaddlePaddle/Paddle/files/4544225/ssd_vgg16_512.txt)
导出工具
https://github.com/PaddlePaddle/PaddleDetection/blob/release/0.2/tools/export_model.py
导出前参数模型
链接：https://pan.baidu.com/s/1Yr5fxk8JnQwvZnplQraZLQ 
提取码：3nsq 
导出后模型
链接：https://pan.baidu.com/s/1AT3T9dUvA2uDaHl4lMkqEQ 
提取码：d6b0

**Comment by yiicy** [comment]
你好，我们已经找相关同学复现该问题
