### ISSUE TITLE
能否在官方文档中提供go语言接口编译较为详细的教程

### ISSUE THREAD

**Issue by MaxWellerVladimir** [PaddlePaddle/Paddle#24258]
很开心paddle官方推出go语言接口，但在使用过程出现一些小问题。我在使用paddlepaddle进行go语言编译参照[官方文档](https://www.paddlepaddle.org.cn/documentation/docs/zh/install/Tables.html#Compile)
进行本地编译，但是发现所列文档主要提供python 接口编译指南，所列过程部分没有对go语言编译指导，github go语言[README_cn.md](https://github.com/PaddlePaddle/Paddle/blob/develop/go/README_cn.md)安装指南更是有些难以理解
“首先cmake编译时打开-DON_INFER=ON,在编译目录下得到fluid_inference_c_install_dir,**将该目录移动到当前目录中并重命名为paddle_c**”此处“该目录”具体是指在哪里的目录？是编译的源文件中的
‘Paddle/go/’目录下，还在在生成build文件中？build之后该如何操作？等。
希望官方能够注意下这个问题，感谢各位开发人员辛苦付出！

**Comment by fc500110** [comment]
该目录指的是fluid_inference_c_install_dir，当前目录是paddle/go

**Comment by MaxWellerVladimir** [comment]
> 该目录指的是fluid_inference_c_install_dir，当前目录是paddle/go

不好意思这里编辑错了，实际我是有些不清楚此处所说的当前目录，到底指哪里的目录？谢谢

**Comment by fc500110** [comment]
> > 该目录指的是fluid_inference_c_install_dir，当前目录是paddle/go
> 
> 不好意思这里编辑错了，实际我是有些不清楚此处所说的当前目录，到底指哪里的目录？谢谢

当前目录是README_cn.md所在的目录，也就是Paddle/go
