### ISSUE TITLE
请问有能装paddlehub的docker镜像吗

### ISSUE THREAD

**Issue by peixin-lin** [PaddlePaddle/Paddle#24255]
想pull 一个有paddle的docker后再来安装paddlehub，但是发现paddlepaddle的镜像装的都是python3.5版本的，而paddlehub要求python3.6以上版本，请问有能安装paddlehub的镜像吗

**Comment by Steffy-zxf** [comment]
@peixin-lin 你好！你可以在docker中安装anaconda，之后用conda创建python 3.6以上版本，这样既可以安装paddle，也可以安装paddlehub。目前PaddleHub没有提供官方镜像。任何关于PaddleHub的问题，欢迎在PaddleHub repo下提issue, https://github.com/PaddlePaddle/PaddleHub/issues
