### ISSUE TITLE
TeamCity能否有Tab页面只把错误输出出来

### ISSUE THREAD

**Issue by gongweibao** [PaddlePaddle/Paddle#2426]
在Overview和BuildLog里边都不方便直接看到错误是哪些，是否可以有单独的Tab，只是显示错误的内容？

**Comment by helinwang** [comment]
@gongweibao CI系统是取stdout，只输出错误是比较困难的。要是PR是基于最新的develop branch的话，会含有一个fix commit，即在"Build Log"里只会输出失败的test（成功的test不输出，但还是包含编译时候的输出），能否看看可不可以接受？

**Comment by gongweibao** [comment]
后来我用关键字查找一下，貌似也可以。：）
