### ISSUE TITLE
visualdl不能在页面批量保存图片

### ISSUE THREAD

**Issue by ipyffor** [PaddlePaddle/Paddle#24275]
如题

**Comment by ShenYuhan** [comment]
您好，目前visualdl暂时不支持此功能，您的需求我们已经反馈给相关同学，后续版本会根据需求优化。
如果有关于visualdl的问题，欢迎您在visualdl的repo下交流和提问：
https://github.com/PaddlePaddle/VisualDL

**Comment by PeterPanZH** [comment]
你好，暂时没有实现本功能，您可以在visualdl repo下开一个issue并加上feature标签，我们会有人负责收集需求并讨论，非常感谢。
