### ISSUE TITLE
特殊的乘法

### ISSUE THREAD

**Issue by 3wGTA** [PaddlePaddle/Paddle#24276]
paddlepaddle如何实现如下的矩阵的乘法方式

![image](https://user-images.githubusercontent.com/62338824/80586298-53b67900-8a47-11ea-9a9b-6b925c0a617d.png)

即矩阵a中每一行的元素分别乘以矩阵b中每一行的元素
矩阵a 的形状是 $M,H$
矩阵b 的形状是 $N,H$

最终希望得到的形状是 $M,N,H$

**Comment by gfwm2013** [comment]
@3wGTA 可以考虑通过split + elementwise_mul + concat 的组成完成上述操作
