### ISSUE TITLE
VS引用paddle GPU版本lib报错

### ISSUE THREAD

**Issue by tangbozhang** [PaddlePaddle/Paddle#24278]
版本、环境信息：
1）PaddlePaddle版本：1.7.2
2）CPU：i7-9300H 16g内存
4）系统环境：win10家庭中文版、Visual Studio 2015 update3  专业版C++ 编译
5）paddle库安装包 “cuda10.0_cudnn7_avx_mkl”- |fluid_inference.zip （直接官网下载：https://www.paddlepaddle.org.cn/documentation/docs/zh/advanced_guide/inference_deployment/inference/windows_cpp_inference.html）

自己新写的工程，调用paddle 的头文件和lib库，CPU版本X64位编译通过，运行也正常；GPU版本X64位编译报错“”LINK : fatal error LNK1104: 无法打开文件“D:\soft-develop-environment\paddle\fluid_inference_install_dir_1.7_gpu_cuda10_cudnn7.0\paddle\lib\libpaddle_fluid.lib”
lib库路径正常，libpaddle_fluid.lib大小超过2G。

**Comment by zhwesky2010** [comment]
@tangbozhang 可能是库的大小太大，用VS2015 cmd编译的试下，cmake -G后面的命令改成，cmake -G "Visual Studio 14 2015 Win64" -T host=x64，其他的不边

**Comment by tangbozhang** [comment]
cmake 之前没用过，参考官方设置报错。是否有在vs工具下编译的方法？
![image](https://user-images.githubusercontent.com/53244607/80593763-5370aa80-8a54-11ea-90cb-b7f2d38e55fa.png)

**Comment by zhwesky2010** [comment]
@tangbozhang hi，你这个cmake可以用的，是因为你输入的CUDA目录中间有空格，被判定成两个变量了，你将-DCUDA_LIB后面的这个目录用""包一下，还有就是CMAKE_BUILD_TYPE=Release。cmake之后用msbuild /m /p:Configuration=Release object.vcxproj编译

**Comment by tingnit** [comment]
@tangbozhang 这个原因在于VS默认没有使用64位链接器，打开你VS工程下的.vcxproj文件，从第三行开始添加：
```
<PropertyGroup>
  <PreferredToolArchitecture>x64</PreferredToolArchitecture>
</PropertyGroup>
```
然后重新编译试试
