### ISSUE TITLE
visualdl不能改变图片窗口大小吗

### ISSUE THREAD

**Issue by ipyffor** [PaddlePaddle/Paddle#24274]
每次显示图片都被压缩在窗口里面，直接变形，显示原图又超出窗口外面去了，放缩页面太大，左边部分的滚动条又超出屏幕外面去了

**Comment by gfwm2013** [comment]
您好，1.3.0版本的vdl前端不能调整大小，为了避免图像失真，建议您在后端记录的时候将图片做预处理，我们已经优化了此处功能，此问题在稍后的新版本中将得以解决。
另外，如果有VisualDL相关的问题，也欢迎您来vdl的repo下进行交流、提问。
https://github.com/PaddlePaddle/VisualDL

**Comment by PeterPanZH** [comment]
你好，VisualDL 2.0目前正处在alpha阶段，已经大幅优化了交互，解决了您所说的问题，欢迎试用，也可以敬请期待稍后2.0正式版的发布。有任何意见和建议欢迎在VisualDL repo下提出issue，谢谢。

**Comment by ipyffor** [comment]
怎么试用



影


&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Peter Pan"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月30日(星期四) 下午4:38
收件人:&nbsp;"PaddlePaddle/Paddle"<Paddle@noreply.github.com&gt;;
抄送:&nbsp;"631707329"<631707329@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [PaddlePaddle/Paddle] visualdl不能改变图片窗口大小吗 (#24274)





 
你好，VisualDL 2.0目前正处在alpha阶段，已经大幅优化了交互，解决了您所说的问题，欢迎试用，也可以敬请期待稍后2.0正式版的发布。有任何意见和建议欢迎在VisualDL repo下提出issue，谢谢。
