### ISSUE TITLE
Need StringPiece

### ISSUE THREAD

**Issue by wangkuiyi** [PaddlePaddle/Paddle#2428]
TensorFlow has [class `StringPiece`](http://yangff.coding.me/tf-doc/codebrowser/codebrowser/tensorflow/core/lib/core/stringpiece.h.html#tensorflow::StringPiece). The difference between `StringPiece` and `std::string` is that 

1. `std::string` owns the string.  In particular, it destroys the memory in its destructor,
1. but `StringPiece` doesn't. This allows us to pass strings (and/or substrings) between function invocations efficiently.

For more about `StringPiece`, please refer to [this blog post](http://brownbag.springmetrics.com/2012/08/my-new-friend-stringpiece/).

`StringPiece` is a frequently used in Google's codebase.  

Go types `string` and `error` are almost identical to `StringPiece` -- a pointer to the underlying C string and an integer length.

**Comment by jacquesqiao** [comment]
I also notice this `StringPiece` but don't quite understand it's purpose, thanks for the explanation.
