### ISSUE TITLE
[oneDNN] Add bfloat16 to C-API

### ISSUE THREAD

**Issue by jczaja** [PaddlePaddle/Paddle#24295]
It could good to add bfloat16 inference support to PaddlePaddle.  There will be no quantization, so it should not be that difficult to have Fp32 model converted t bfloat16 (oneDNN has mechanics for that) and
run inference.
1. Extend C-API analysis config to support bfloat16 inference
2. check accuracy

**Comment by lidanqing-vv** [comment]
PR submitted https://github.com/PaddlePaddle/Paddle/pull/25402

**Comment by jczaja** [comment]
done over a few of PRs
