### ISSUE TITLE
指数滑动平均ema不支持并发

### ISSUE THREAD

**Issue by irukawang** [PaddlePaddle/Paddle#24291]
- 版本、环境信息：
    1）PaddlePaddle版本：paddle1.6/paddle1.7/包括mpi集群
    2）系统环境：centOs

- 问题描述：ExponentialMovingAverage 多并发不支持，错误信息如下：
本地，多核错误信息：
[Hint: Expected sorted_ops.size() == topo_ops.size(), but received sorted_ops.size():90 != topo_ops.size():155.] at (/paddle/paddle/fluid/framework/ir/multi_devices_graph_pass/multi_devices_graph_pass.cc:778)
集群，多节点错误信息：
[Hint: Expected dev_id != -1, but received dev_id:-1 == -1:-1.] at (/paddle/paddle/fluid/framework/ir/multi_devices_graph_pass/multi_devices_graph_pass.cc:633)

**Comment by DannyIsFunny** [comment]
你好，当前 `ExponentialMovingAverage `不支持多并发，分布式并发相关功能开发中
