### ISSUE TITLE
无法进入Docker容器：docker: Error response from daemon: OCI runtime create failed: unable to retrieve OCI runtime error

### ISSUE THREAD

**Issue by relaxtheo** [PaddlePaddle/Paddle#24299]
安装quick指南（https://www.paddlepaddle.org.cn/install/quick），在ubuntu 18.04上采用docker方式安装python3_Cuda10版本的paddle，在第7步 用镜像构建并进入Docker容器遇到了下面的错误：

docker: Error response from daemon: OCI runtime create failed: unable to retrieve OCI runtime error (open /run/containerd/io.containerd.runtime.v1.linux/moby/6a245b88265a0646ed388c9fb9d8e64835182902b30cbc773bc249fed07984dc/log.json: no such file or directory): fork/exec /usr/bin/nvidia-container-runtime: no such file or directory: : unknown.
ERRO[0000] error waiting for container: context canceled 

这个问题如何解决？

**Comment by jiweibo** [comment]
请确认下你安装的nvidia docker，最新版的nvidia docker应该是docker run --gpus all的启动方式

**Comment by relaxtheo** [comment]
应该是nvidia-docker没有装好。
重新按照nvidia-docker的要求安装，直接使用docker命令，没有采用quick guide中的nvidia-docker命令，目前看起来是好的
