### ISSUE TITLE
执行paddle.fluid.install_check.run_check()时，出现错误

### ISSUE THREAD

**Issue by qgqinfen** [PaddlePaddle/Paddle#24302]
环境配置：
python3.5 64位
pip 20.1 64位
cuda 9.0 
cudnn 7.6
处理器为X86_64

安装paddlepaddle时 使用下面的命令
python3 -m pip install paddlepaddle-gpu==1.7.2.post97 -i https://mirror.baidu.com/pypi/simple

Running Verify Paddle Program ... 
W0503 11:40:39.469370  7452 device_context.cc:237] Please NOTE: device: 0, CUDA Capability: 75, Driver API Version: 10.1, Runtime API Version: 9.0
W0503 11:40:39.471192  7452 device_context.cc:245] device: 0, cuDNN Version: 7.6.
/home/kxy/anaconda3/envs/paddle/lib/python3.5/site-packages/paddle/fluid/executor.py:789: UserWarning: The following exception is not an EOF exception.
  "The following exception is not an EOF exception.")
Traceback (most recent call last):
  File "/home/kxy/PycharmProjects/paddle/test.py", line 3, in <module>
    paddle.fluid.install_check.run_check()
  File "/home/kxy/anaconda3/envs/paddle/lib/python3.5/site-packages/paddle/fluid/install_check.py", line 124, in run_check
    test_simple_exe()
  File "/home/kxy/anaconda3/envs/paddle/lib/python3.5/site-packages/paddle/fluid/install_check.py", line 122, in test_simple_exe
    fetch_list=[out0.name, param_grads[1].name])
  File "/home/kxy/anaconda3/envs/paddle/lib/python3.5/site-packages/paddle/fluid/executor.py", line 790, in run
    six.reraise(*sys.exc_info())
  File "/home/kxy/anaconda3/envs/paddle/lib/python3.5/site-packages/six.py", line 703, in reraise
    raise value
  File "/home/kxy/anaconda3/envs/paddle/lib/python3.5/site-packages/paddle/fluid/executor.py", line 785, in run
    use_program_cache=use_program_cache)
  File "/home/kxy/anaconda3/envs/paddle/lib/python3.5/site-packages/paddle/fluid/executor.py", line 838, in _run_impl
    use_program_cache=use_program_cache)
  File "/home/kxy/anaconda3/envs/paddle/lib/python3.5/site-packages/paddle/fluid/executor.py", line 912, in _run_program
    fetch_var_name)
paddle.fluid.core_avx.EnforceNotMet: 

--------------------------------------------
C++ Call Stacks (More useful to developers):
--------------------------------------------
0   std::string paddle::platform::GetTraceBackString<char const*>(char const*&&, char const*, int)
1   paddle::platform::EnforceNotMet::EnforceNotMet(std::__exception_ptr::exception_ptr, char const*, int)
2   void paddle::operators::math::Blas<paddle::platform::CUDADeviceContext>::GEMM<float>(CBLAS_TRANSPOSE, CBLAS_TRANSPOSE, int, int, int, float, float const*, float const*, float, float*) const
3   void paddle::operators::math::Blas<paddle::platform::CUDADeviceContext>::MatMul<float>(paddle::framework::Tensor const&, paddle::operators::math::MatDescriptor const&, paddle::framework::Tensor const&, paddle::operators::math::MatDescriptor const&, float, paddle::framework::Tensor*, float) const
4   paddle::operators::MatMulKernel<paddle::platform::CUDADeviceContext, float>::Compute(paddle::framework::ExecutionContext const&) const
5   std::_Function_handler<void (paddle::framework::ExecutionContext const&), paddle::framework::OpKernelRegistrarFunctor<paddle::platform::CUDAPlace, false, 0ul, paddle::operators::MatMulKernel<paddle::platform::CUDADeviceContext, float>, paddle::operators::MatMulKernel<paddle::platform::CUDADeviceContext, double>, paddle::operators::MatMulKernel<paddle::platform::CUDADeviceContext, paddle::platform::float16> >::operator()(char const*, char const*, int) const::{lambda(paddle::framework::ExecutionContext const&)#1}>::_M_invoke(std::_Any_data const&, paddle::framework::ExecutionContext const&)
6   paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, paddle::platform::Place const&, paddle::framework::RuntimeContext*) const
7   paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, paddle::platform::Place const&) const
8   paddle::framework::OperatorBase::Run(paddle::framework::Scope const&, paddle::platform::Place const&)
9   paddle::framework::Executor::RunPreparedContext(paddle::framework::ExecutorPrepareContext*, paddle::framework::Scope*, bool, bool, bool)
10  paddle::framework::Executor::Run(paddle::framework::ProgramDesc const&, paddle::framework::Scope*, int, bool, bool, std::vector<std::string, std::allocator<std::string> > const&, bool, bool)

------------------------------------------
Python Call Stacks (More useful to users):
------------------------------------------
  File "/home/kxy/anaconda3/envs/paddle/lib/python3.5/site-packages/paddle/fluid/framework.py", line 2525, in append_op
    attrs=kwargs.get("attrs", None))
  File "/home/kxy/anaconda3/envs/paddle/lib/python3.5/site-packages/paddle/fluid/dygraph/layer_object_helper.py", line 52, in append_op
    stop_gradient=stop_gradient)
  File "/home/kxy/anaconda3/envs/paddle/lib/python3.5/site-packages/paddle/fluid/dygraph/nn.py", line 944, in forward
    type="matmul", inputs=inputs, outputs={"Out": tmp}, attrs=attrs)
  File "/home/kxy/anaconda3/envs/paddle/lib/python3.5/site-packages/paddle/fluid/dygraph/layers.py", line 304, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/home/kxy/anaconda3/envs/paddle/lib/python3.5/site-packages/paddle/fluid/install_check.py", line 41, in forward
    x = self._linear1(inputs)
  File "/home/kxy/anaconda3/envs/paddle/lib/python3.5/site-packages/paddle/fluid/dygraph/layers.py", line 304, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/home/kxy/anaconda3/envs/paddle/lib/python3.5/site-packages/paddle/fluid/install_check.py", line 113, in test_simple_exe
    out0 = simple_layer0(inp0)
  File "/home/kxy/anaconda3/envs/paddle/lib/python3.5/site-packages/paddle/fluid/install_check.py", line 124, in run_check
    test_simple_exe()
  File "/home/kxy/PycharmProjects/paddle/test.py", line 3, in <module>
    paddle.fluid.install_check.run_check()

----------------------
Error Message Summary:
----------------------
Error: An error occurred here. There is no accurate error hint for this error yet. We are continuously in the process of increasing hint for this kind of error check. It would be helpful if you could inform us of how this conversion went by opening a github issue. And we will resolve it with high priority.
  - New issue link: https://github.com/PaddlePaddle/Paddle/issues/new
  - Recommended issue content: all error stack information
  [Hint: CUBLAS_STATUS_EXECUTION_FAILED] at (/paddle/paddle/fluid/operators/math/blas_impl.cu.h:34)
  [operator < matmul > error]
检查paddlepaddle配置时，出现错误，救救孩子吧。崩溃了。

**Comment by FrostML** [comment]
W0503 11:40:39.469370 7452 device_context.cc:237] Please NOTE: device: 0, CUDA Capability: 75, Driver API Version: 10.1, Runtime API Version: 9.0

看上去是 CUDA 的问题。请问确认是使用的是 CUDA 9 么？可以将 CUDA 9 相关 lib 的路径加入 LD_LIBRARY_PATH

**Comment by qgqinfen** [comment]
> W0503 11:40:39.469370 7452 device_context.cc:237] Please NOTE: device: 0, CUDA Capability: 75, Driver API Version: 10.1, Runtime API Version: 9.0
> 
> 看上去是 CUDA 的问题。请问确认是使用的是 CUDA 9 么？可以将 CUDA 9 相关 lib 的路径加入 LD_LIBRARY_PATH

确定是cuda9，CUDA9相关lib路径也加入到LD_LIBRARY_PATH中
![CY} 6%Z2CBDT)57PMIJD$9A](https://user-images.githubusercontent.com/45931564/80909988-29263200-8d5f-11ea-9555-d33a80196834.png)。安装cudnn7.6.5之后我没有重启机器。

**Comment by FrostML** [comment]
辛苦麻烦 @JepsonWong 看看。

**Comment by JepsonWong** [comment]
麻烦nvidia-smi看看显卡驱动版本，输出PATH、LIBRARY_PATH 、LD_LIBRARY_PATH看看结果。

我给您提供一个测试程序，看看您那边执行会有什么问题呢？

```
//Example 1. Application Using C and CUBLAS: 1-based indexing
//-----------------------------------------------------------
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <cuda_runtime.h>
#include "cublas_v2.h"
#define M 6
#define N 5
#define IDX2F(i,j,ld) ((((j)-1)*(ld))+((i)-1))

static __inline__ void modify (cublasHandle_t handle, float *m, int ldm, int n, int p, int q, float alpha, float beta){
    cublasSscal (handle, n-q+1, &alpha, &m[IDX2F(p,q,ldm)], ldm);
    cublasSscal (handle, ldm-p+1, &beta, &m[IDX2F(p,q,ldm)], 1);
}

int main (void){
    cudaError_t cudaStat;    
    cublasStatus_t stat;
    cublasHandle_t handle;
    int i, j;
    float* devPtrA;
    float* a = 0;
    a = (float *)malloc (M * N * sizeof (*a));
    if (!a) {
        printf ("host memory allocation failed");
        return EXIT_FAILURE;
    }
    for (j = 1; j <= N; j++) {
        for (i = 1; i <= M; i++) {
            a[IDX2F(i,j,M)] = (float)((i-1) * M + j);
        }
    }
    cudaStat = cudaMalloc ((void**)&devPtrA, M*N*sizeof(*a));
    if (cudaStat != cudaSuccess) {
        printf ("device memory allocation failed");
        return EXIT_FAILURE;
    }
    stat = cublasCreate(&handle);
    if (stat != CUBLAS_STATUS_SUCCESS) {
        printf ("CUBLAS initialization failed\n");
        return EXIT_FAILURE;
    }
    stat = cublasSetMatrix (M, N, sizeof(*a), a, M, devPtrA, M);
    if (stat != CUBLAS_STATUS_SUCCESS) {
        printf ("data download failed");
        cudaFree (devPtrA);
        cublasDestroy(handle);
        return EXIT_FAILURE;
    }
    modify (handle, devPtrA, M, N, 2, 3, 16.0f, 12.0f);
    stat = cublasGetMatrix (M, N, sizeof(*a), devPtrA, M, a, M);
    if (stat != CUBLAS_STATUS_SUCCESS) {
        printf ("data upload failed");
        cudaFree (devPtrA);
        cublasDestroy(handle);        
        return EXIT_FAILURE;
    }    
    cudaFree (devPtrA);
    cublasDestroy(handle);
    for (j = 1; j <= N; j++) {
        for (i = 1; i <= M; i++) {
            printf ("%7.0f", a[IDX2F(i,j,M)]);
        }
        printf ("\n");
    }
    free(a);
    return EXIT_SUCCESS;
}
```

1. 程序保存为test.cu文件
2. 编译: nvcc test.cu -o test -lcublas -std=c++11
3. 执行: ./test

**Comment by qgqinfen** [comment]
> 麻烦nvidia-smi看看显卡驱动版本，输出PATH、LIBRARY_PATH 、LD_LIBRARY_PATH看看结果。
> 
> 我给您提供一个测试程序，看看您那边执行会有什么问题呢？
> 
> ```
> //Example 1. Application Using C and CUBLAS: 1-based indexing
> //-----------------------------------------------------------
> #include <stdio.h>
> #include <stdlib.h>
> #include <math.h>
> #include <cuda_runtime.h>
> #include "cublas_v2.h"
> #define M 6
> #define N 5
> #define IDX2F(i,j,ld) ((((j)-1)*(ld))+((i)-1))
> 
> static __inline__ void modify (cublasHandle_t handle, float *m, int ldm, int n, int p, int q, float alpha, float beta){
>     cublasSscal (handle, n-q+1, &alpha, &m[IDX2F(p,q,ldm)], ldm);
>     cublasSscal (handle, ldm-p+1, &beta, &m[IDX2F(p,q,ldm)], 1);
> }
> 
> int main (void){
>     cudaError_t cudaStat;    
>     cublasStatus_t stat;
>     cublasHandle_t handle;
>     int i, j;
>     float* devPtrA;
>     float* a = 0;
>     a = (float *)malloc (M * N * sizeof (*a));
>     if (!a) {
>         printf ("host memory allocation failed");
>         return EXIT_FAILURE;
>     }
>     for (j = 1; j <= N; j++) {
>         for (i = 1; i <= M; i++) {
>             a[IDX2F(i,j,M)] = (float)((i-1) * M + j);
>         }
>     }
>     cudaStat = cudaMalloc ((void**)&devPtrA, M*N*sizeof(*a));
>     if (cudaStat != cudaSuccess) {
>         printf ("device memory allocation failed");
>         return EXIT_FAILURE;
>     }
>     stat = cublasCreate(&handle);
>     if (stat != CUBLAS_STATUS_SUCCESS) {
>         printf ("CUBLAS initialization failed\n");
>         return EXIT_FAILURE;
>     }
>     stat = cublasSetMatrix (M, N, sizeof(*a), a, M, devPtrA, M);
>     if (stat != CUBLAS_STATUS_SUCCESS) {
>         printf ("data download failed");
>         cudaFree (devPtrA);
>         cublasDestroy(handle);
>         return EXIT_FAILURE;
>     }
>     modify (handle, devPtrA, M, N, 2, 3, 16.0f, 12.0f);
>     stat = cublasGetMatrix (M, N, sizeof(*a), devPtrA, M, a, M);
>     if (stat != CUBLAS_STATUS_SUCCESS) {
>         printf ("data upload failed");
>         cudaFree (devPtrA);
>         cublasDestroy(handle);        
>         return EXIT_FAILURE;
>     }    
>     cudaFree (devPtrA);
>     cublasDestroy(handle);
>     for (j = 1; j <= N; j++) {
>         for (i = 1; i <= M; i++) {
>             printf ("%7.0f", a[IDX2F(i,j,M)]);
>         }
>         printf ("\n");
>     }
>     free(a);
>     return EXIT_SUCCESS;
> }
> ```
> 
> 1. 程序保存为test.cu文件
> 2. 编译: nvcc test.cu -o test -lcublas -std=c++11
> 3. 执行: ./test

您好，显卡驱动版本
![显卡驱动版本s](https://user-images.githubusercontent.com/45931564/81152105-3720c080-8fb4-11ea-83ba-420665cecabd.png)
环境变量值
![环境变量path library_path lc_library_path](https://user-images.githubusercontent.com/45931564/81152217-54558f00-8fb4-11ea-8434-c83f162f076f.png)
测试程序的输出结果
![测试程序结果](https://user-images.githubusercontent.com/45931564/81152266-5fa8ba80-8fb4-11ea-90df-9de4c6612eff.png)

**Comment by JepsonWong** [comment]
> > 麻烦nvidia-smi看看显卡驱动版本，输出PATH、LIBRARY_PATH 、LD_LIBRARY_PATH看看结果。
> > 我给您提供一个测试程序，看看您那边执行会有什么问题呢？
> > ```
> > //Example 1. Application Using C and CUBLAS: 1-based indexing
> > //-----------------------------------------------------------
> > #include <stdio.h>
> > #include <stdlib.h>
> > #include <math.h>
> > #include <cuda_runtime.h>
> > #include "cublas_v2.h"
> > #define M 6
> > #define N 5
> > #define IDX2F(i,j,ld) ((((j)-1)*(ld))+((i)-1))
> > 
> > static __inline__ void modify (cublasHandle_t handle, float *m, int ldm, int n, int p, int q, float alpha, float beta){
> >     cublasSscal (handle, n-q+1, &alpha, &m[IDX2F(p,q,ldm)], ldm);
> >     cublasSscal (handle, ldm-p+1, &beta, &m[IDX2F(p,q,ldm)], 1);
> > }
> > 
> > int main (void){
> >     cudaError_t cudaStat;    
> >     cublasStatus_t stat;
> >     cublasHandle_t handle;
> >     int i, j;
> >     float* devPtrA;
> >     float* a = 0;
> >     a = (float *)malloc (M * N * sizeof (*a));
> >     if (!a) {
> >         printf ("host memory allocation failed");
> >         return EXIT_FAILURE;
> >     }
> >     for (j = 1; j <= N; j++) {
> >         for (i = 1; i <= M; i++) {
> >             a[IDX2F(i,j,M)] = (float)((i-1) * M + j);
> >         }
> >     }
> >     cudaStat = cudaMalloc ((void**)&devPtrA, M*N*sizeof(*a));
> >     if (cudaStat != cudaSuccess) {
> >         printf ("device memory allocation failed");
> >         return EXIT_FAILURE;
> >     }
> >     stat = cublasCreate(&handle);
> >     if (stat != CUBLAS_STATUS_SUCCESS) {
> >         printf ("CUBLAS initialization failed\n");
> >         return EXIT_FAILURE;
> >     }
> >     stat = cublasSetMatrix (M, N, sizeof(*a), a, M, devPtrA, M);
> >     if (stat != CUBLAS_STATUS_SUCCESS) {
> >         printf ("data download failed");
> >         cudaFree (devPtrA);
> >         cublasDestroy(handle);
> >         return EXIT_FAILURE;
> >     }
> >     modify (handle, devPtrA, M, N, 2, 3, 16.0f, 12.0f);
> >     stat = cublasGetMatrix (M, N, sizeof(*a), devPtrA, M, a, M);
> >     if (stat != CUBLAS_STATUS_SUCCESS) {
> >         printf ("data upload failed");
> >         cudaFree (devPtrA);
> >         cublasDestroy(handle);        
> >         return EXIT_FAILURE;
> >     }    
> >     cudaFree (devPtrA);
> >     cublasDestroy(handle);
> >     for (j = 1; j <= N; j++) {
> >         for (i = 1; i <= M; i++) {
> >             printf ("%7.0f", a[IDX2F(i,j,M)]);
> >         }
> >         printf ("\n");
> >     }
> >     free(a);
> >     return EXIT_SUCCESS;
> > }
> > ```
> > 
> > 
> > 
> > 1. 程序保存为test.cu文件
> > 2. 编译: nvcc test.cu -o test -lcublas -std=c++11
> > 3. 执行: ./test
> 
> 您好，显卡驱动版本
> ![显卡驱动版本s](https://user-images.githubusercontent.com/45931564/81152105-3720c080-8fb4-11ea-83ba-420665cecabd.png)
> 环境变量值
> ![环境变量path library_path lc_library_path](https://user-images.githubusercontent.com/45931564/81152217-54558f00-8fb4-11ea-8434-c83f162f076f.png)
> 测试程序的输出结果
> ![测试程序结果](https://user-images.githubusercontent.com/45931564/81152266-5fa8ba80-8fb4-11ea-90df-9de4c6612eff.png)

看起来CUBLAS库初始化完毕了，但执行操作有问题，我在写个测试程序您测试下，稍等。

**Comment by JepsonWong** [comment]
这里有一份cublas的测试代码 https://github.com/NVIDIA/cuda-samples/tree/master/Samples/simpleCUBLAS ，辛苦测试下吧

1. clone该仓库
2. 进入/Samples/simpleCUBLAS目录
3. 执行make操作，执行应用程序

**Comment by qgqinfen** [comment]
> 这里有一份cublas的测试代码 https://github.com/NVIDIA/cuda-samples/tree/master/Samples/simpleCUBLAS ，辛苦测试下吧
> 
> 1. clone该仓库
> 2. 进入/Samples/simpleCUBLAS目录
> 3. 执行make操作，执行应用程序

您好，我把CUBLAS测试结果发给您。
![CY} 6%Z2CBDT)57PMIJD$9A](https://user-images.githubusercontent.com/45931564/81252649-08a8f100-9059-11ea-9764-46894a2a456c.png)
问题是出在了这里吗？

**Comment by JepsonWong** [comment]
> > 这里有一份cublas的测试代码 https://github.com/NVIDIA/cuda-samples/tree/master/Samples/simpleCUBLAS ，辛苦测试下吧
> > 
> > 1. clone该仓库
> > 2. 进入/Samples/simpleCUBLAS目录
> > 3. 执行make操作，执行应用程序
> 
> 您好，我把CUBLAS测试结果发给您。
> ![CY} 6%Z2CBDT)57PMIJD$9A](https://user-images.githubusercontent.com/45931564/81252649-08a8f100-9059-11ea-9764-46894a2a456c.png)
> 问题是出在了这里吗？

这个不是测试结果呀，需要执行编译好的simpleCUBLAS应用程序。

**Comment by qgqinfen** [comment]
> > > 这里有一份cublas的测试代码 https://github.com/NVIDIA/cuda-samples/tree/master/Samples/simpleCUBLAS ，辛苦测试下吧
> > > 
> > > 1. clone该仓库
> > > 2. 进入/Samples/simpleCUBLAS目录
> > > 3. 执行make操作，执行应用程序
> > 
> > 
> > 您好，我把CUBLAS测试结果发给您。
> > ![CY} 6%Z2CBDT)57PMIJD$9A](https://user-images.githubusercontent.com/45931564/81252649-08a8f100-9059-11ea-9764-46894a2a456c.png)
> > 问题是出在了这里吗？
> 
> 这个不是测试结果呀，需要执行编译好的simpleCUBLAS应用程序。

![image](https://user-images.githubusercontent.com/45931564/81489280-1dc68f80-92a6-11ea-9870-f43b5ee35ed6.png)
您好，这是测试结果，麻烦您查看。非常感谢。

**Comment by JepsonWong** [comment]
你测试过cuda10环境么？可以使用 `docker pull paddlepaddle/paddle:1.8.0-gpu-cuda10.0-cudnn7` 下载官方docker，然后使用nvidia-docker命令进入docker内部使用gpu环境。

**Comment by LeeYongchao** [comment]
我和他的问题是一样的：
输入：nvcc -V
输出：nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2017 NVIDIA Corporation
Built on Fri_Sep__1_21:08:03_CDT_2017
Cuda compilation tools, release 9.0, V9.0.176

安装：python3 -m pip install paddlepaddle-gpu==1.7.2.post97 -i https://mirror.baidu.com/pypi/simple
测试：paddle.fluid.install_check.run_check()

结果报错：Running Verify Paddle Program ... 
W0605 17:14:53.876421 13483 device_context.cc:237] Please NOTE: device: 0, CUDA Capability: 75, Driver API Version: 10.1, Runtime API Version: 9.0
W0605 17:14:53.926858 13483 device_context.cc:245] device: 0, cuDNN Version: 7.5.
/home/lyc/anaconda3/envs/paddle/lib/python3.6/site-packages/paddle/fluid/executor.py:789: UserWarning: The following exception is not an EOF exception.
  "The following exception is not an EOF exception.")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/lyc/anaconda3/envs/paddle/lib/python3.6/site-packages/paddle/fluid/install_check.py", line 124, in run_check
    test_simple_exe()
  File "/home/lyc/anaconda3/envs/paddle/lib/python3.6/site-packages/paddle/fluid/install_check.py", line 122, in test_simple_exe
    fetch_list=[out0.name, param_grads[1].name])
  File "/home/lyc/anaconda3/envs/paddle/lib/python3.6/site-packages/paddle/fluid/executor.py", line 790, in run
    six.reraise(*sys.exc_info())
  File "/home/lyc/anaconda3/envs/paddle/lib/python3.6/site-packages/six.py", line 703, in reraise
    raise value
  File "/home/lyc/anaconda3/envs/paddle/lib/python3.6/site-packages/paddle/fluid/executor.py", line 785, in run
    use_program_cache=use_program_cache)
  File "/home/lyc/anaconda3/envs/paddle/lib/python3.6/site-packages/paddle/fluid/executor.py", line 838, in _run_impl
    use_program_cache=use_program_cache)
  File "/home/lyc/anaconda3/envs/paddle/lib/python3.6/site-packages/paddle/fluid/executor.py", line 912, in _run_program
    fetch_var_name)
paddle.fluid.core_avx.EnforceNotMet: 

--------------------------------------------
C++ Call Stacks (More useful to developers):
--------------------------------------------
0   std::string paddle::platform::GetTraceBackString<char const*>(char const*&&, char const*, int)
1   paddle::platform::EnforceNotMet::EnforceNotMet(std::__exception_ptr::exception_ptr, char const*, int)
2   void paddle::operators::math::Blas<paddle::platform::CUDADeviceContext>::GEMM<float>(CBLAS_TRANSPOSE, CBLAS_TRANSPOSE, int, int, int, float, float const*, float const*, float, float*) const
3   void paddle::operators::math::Blas<paddle::platform::CUDADeviceContext>::MatMul<float>(paddle::framework::Tensor const&, paddle::operators::math::MatDescriptor const&, paddle::framework::Tensor const&, paddle::operators::math::MatDescriptor const&, float, paddle::framework::Tensor*, float) const
4   paddle::operators::MatMulKernel<paddle::platform::CUDADeviceContext, float>::Compute(paddle::framework::ExecutionContext const&) const
5   std::_Function_handler<void (paddle::framework::ExecutionContext const&), paddle::framework::OpKernelRegistrarFunctor<paddle::platform::CUDAPlace, false, 0ul, paddle::operators::MatMulKernel<paddle::platform::CUDADeviceContext, float>, paddle::operators::MatMulKernel<paddle::platform::CUDADeviceContext, double>, paddle::operators::MatMulKernel<paddle::platform::CUDADeviceContext, paddle::platform::float16> >::operator()(char const*, char const*, int) const::{lambda(paddle::framework::ExecutionContext const&)#1}>::_M_invoke(std::_Any_data const&, paddle::framework::ExecutionContext const&)
6   paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, paddle::platform::Place const&, paddle::framework::RuntimeContext*) const
7   paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, paddle::platform::Place const&) const
8   paddle::framework::OperatorBase::Run(paddle::framework::Scope const&, paddle::platform::Place const&)
9   paddle::framework::Executor::RunPreparedContext(paddle::framework::ExecutorPrepareContext*, paddle::framework::Scope*, bool, bool, bool)
10  paddle::framework::Executor::Run(paddle::framework::ProgramDesc const&, paddle::framework::Scope*, int, bool, bool, std::vector<std::string, std::allocator<std::string> > const&, bool, bool)

------------------------------------------
Python Call Stacks (More useful to users):
------------------------------------------
  File "/home/lyc/anaconda3/envs/paddle/lib/python3.6/site-packages/paddle/fluid/framework.py", line 2525, in append_op
    attrs=kwargs.get("attrs", None))
  File "/home/lyc/anaconda3/envs/paddle/lib/python3.6/site-packages/paddle/fluid/dygraph/layer_object_helper.py", line 52, in append_op
    stop_gradient=stop_gradient)
  File "/home/lyc/anaconda3/envs/paddle/lib/python3.6/site-packages/paddle/fluid/dygraph/nn.py", line 944, in forward
    type="matmul", inputs=inputs, outputs={"Out": tmp}, attrs=attrs)
  File "/home/lyc/anaconda3/envs/paddle/lib/python3.6/site-packages/paddle/fluid/dygraph/layers.py", line 304, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/home/lyc/anaconda3/envs/paddle/lib/python3.6/site-packages/paddle/fluid/install_check.py", line 41, in forward
    x = self._linear1(inputs)
  File "/home/lyc/anaconda3/envs/paddle/lib/python3.6/site-packages/paddle/fluid/dygraph/layers.py", line 304, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/home/lyc/anaconda3/envs/paddle/lib/python3.6/site-packages/paddle/fluid/install_check.py", line 113, in test_simple_exe
    out0 = simple_layer0(inp0)
  File "/home/lyc/anaconda3/envs/paddle/lib/python3.6/site-packages/paddle/fluid/install_check.py", line 124, in run_check
    test_simple_exe()
  File "<stdin>", line 1, in <module>

----------------------
Error Message Summary:
----------------------
Error: An error occurred here. There is no accurate error hint for this error yet. We are continuously in the process of increasing hint for this kind of error check. It would be helpful if you could inform us of how this conversion went by opening a github issue. And we will resolve it with high priority.
  - New issue link: https://github.com/PaddlePaddle/Paddle/issues/new
  - Recommended issue content: all error stack information
  [Hint: CUBLAS_STATUS_EXECUTION_FAILED] at (/paddle/paddle/fluid/operators/math/blas_impl.cu.h:34)
  [operator < matmul > error]

**Comment by SAMSONEE** [comment]
我也是这一步出了问题,显示如下：
![Snipaste_2020-07-06_23-04-35](https://user-images.githubusercontent.com/55627057/86608455-2ce36880-bfdd-11ea-8d69-873421310ec5.png)
这也是同样的问题吗？

**Comment by LiKangyuLKY** [comment]
> 你测试过cuda10环境么？可以使用 `docker pull paddlepaddle/paddle:1.8.0-gpu-cuda10.0-cudnn7` 下载官方docker，然后使用nvidia-docker命令进入docker内部使用gpu环境。

你好，在输入paddle.fluid.install_check.run_check()进行测试时，我遇到了与@qgqinfen 相同的问题，按照你的回复，测试如下：
![image](https://user-images.githubusercontent.com/42792466/91653883-f7d42d80-ead6-11ea-8910-7cf46a97c3bb.png)

该怎么去解决这个问题呢

**Comment by JepsonWong** [comment]
> > 你测试过cuda10环境么？可以使用 `docker pull paddlepaddle/paddle:1.8.0-gpu-cuda10.0-cudnn7` 下载官方docker，然后使用nvidia-docker命令进入docker内部使用gpu环境。
> 
> 你好，在输入paddle.fluid.install_check.run_check()进行测试时，我遇到了与@qgqinfen 相同的问题，按照你的回复，测试如下：
> ![image](https://user-images.githubusercontent.com/42792466/91653883-f7d42d80-ead6-11ea-8910-7cf46a97c3bb.png)
> 
> 该怎么去解决这个问题呢

@tianshuo78520a

**Comment by LiKangyuLKY** [comment]
> > > 你测试过cuda10环境么？可以使用 `docker pull paddlepaddle/paddle:1.8.0-gpu-cuda10.0-cudnn7` 下载官方docker，然后使用nvidia-docker命令进入docker内部使用gpu环境。
> > 
> > 
> > 你好，在输入paddle.fluid.install_check.run_check()进行测试时，我遇到了与@qgqinfen 相同的问题，按照你的回复，测试如下：
> > ![image](https://user-images.githubusercontent.com/42792466/91653883-f7d42d80-ead6-11ea-8910-7cf46a97c3bb.png)
> > 该怎么去解决这个问题呢
> 
> @tianshuo78520a

CUDA10.0有BUG，更换到10.1版本后正常
