### ISSUE TITLE
怀疑cast、log、exp等OP导致的死循环

### ISSUE THREAD

**Issue by huangguanMayday** [PaddlePaddle/Paddle#24304]
第99行换成第100行，就貌似死循环了，训不动:

![image](https://user-images.githubusercontent.com/4018038/80909578-eb73da00-8d5b-11ea-9402-b3c1b99ee694.png)

**Comment by FrostML** [comment]
可以提供下`hinge_loss`和`circle_loss`的实现么？

**Comment by huangguanMayday** [comment]
> 可以提供下`hinge_loss`和`circle_loss`的实现么？

可以私聊发环境给你复现？你是百度员工吗？

**Comment by FrostML** [comment]
同步下目前的结果，两个 loss 相关的实现如下：
![image](https://user-images.githubusercontent.com/7160927/81147280-8b27a700-8fac-11ea-9c9d-e314171e059a.png)

**Comment by FrostML** [comment]
同步下目前的进展，两个 loss 相关的实现如下：
![image](https://user-images.githubusercontent.com/7160927/81147280-8b27a700-8fac-11ea-9c9d-e314171e059a.png)
以及
![image](https://user-images.githubusercontent.com/7160927/81148403-ccb95180-8fae-11ea-874a-0bfb4e86969b.png)
目前调试，是在改小了 dataset.set_thread() 设置的线程数（16->10）之后可以跑通训练。
dataset 的设置如下：
```python
dataset = fluid.DatasetFactory().create_dataset()
dataset.set_batch_size(conf.batch_size)
dataset.set_use_var(input_data)
pipe_command = 'python dataset_reader.py'
dataset.set_pipe_command(pipe_command)
filelist = get_file_list(conf.train_file)
logger.info("filelist: " + str(filelist))

dataset.set_thread(conf.thread_num)
```
转 xjq 跟进

**Comment by zhiqiu** [comment]
经过排查，该问题产生的原因是：
使用circle_loss时网络中会出现NAN，在sequence_topk_avg_pooling实现中会发生`vector[-1]`的内存越界访问，此时函数不能退出退出。因为使用多线程训练，主线程在wait子线程结束，所以发生了hang。

sequence_topk_avg_pooling的问题，@Aurelius84 已提PR进行修复。
