### ISSUE TITLE
训练误差降低，测试误差升高

### ISSUE THREAD

**Issue by LLChocolate** [PaddlePaddle/Paddle#24315]
模型在训练时loss降低，但是在model.eval()后测试，loss反而升高。
应该不是过拟合，因为测试的时候也使用的是训练时的数据集。

**Comment by LLChocolate** [comment]
这是在动态图里出现的问题。

**Comment by JepsonWong** [comment]
loss差别多大呢？如果差别不是很大的话，会不会是dropout、batch_norm这些因素的影响呢？
方便提供下复现程序么？

**Comment by LLChocolate** [comment]
> loss差别多大呢？如果差别不是很大的话，会不会是dropout、batch_norm这些因素的影响呢？
> 方便提供下复现程序么？

差别巨大，我可以把代码直接发到你邮箱吗

**Comment by LLChocolate** [comment]
> loss差别多大呢？如果差别不是很大的话，会不会是dropout、batch_norm这些因素的影响呢？
> 方便提供下复现程序么？

刚刚测试的结果是在如果去掉model.eval的话，结果就正常了

**Comment by LLChocolate** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"zhongpu"<notifications@github.com&gt;;
发送时间:&nbsp;2020年5月6日(星期三) 下午4:52
收件人:&nbsp;"PaddlePaddle/Paddle"<Paddle@noreply.github.com&gt;;
抄送:&nbsp;"542232570"<542232570@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [PaddlePaddle/Paddle] 训练误差降低，测试误差升高 (#24315)





 
loss差别多大呢？如果差别不是很大的话，会不会是dropout、batch_norm这些因素的影响呢？
 方便提供下复现程序么？

**Comment by JepsonWong** [comment]
> > loss差别多大呢？如果差别不是很大的话，会不会是dropout、batch_norm这些因素的影响呢？
> > 方便提供下复现程序么？
> 
> 刚刚测试的结果是在如果去掉model.eval的话，结果就正常了

目前结论是去掉model.eval就正常么？

**Comment by LLChocolate** [comment]
> > > loss差别多大呢？如果差别不是很大的话，会不会是dropout、batch_norm这些因素的影响呢？
> > > 方便提供下复现程序么？
> > 
> > 
> > 刚刚测试的结果是在如果去掉model.eval的话，结果就正常了
> 
> 目前结论是去掉model.eval就正常么？

我发现问题出现在模型中，其中有一段程序是knn和获取动态图特征get_graph_feature，这两段代码加上之后就会出现这种现象。动态图的代码里用到了索引操作，可能在动态图里这种索引操作有问题。

**Comment by LLChocolate** [comment]
> > > loss差别多大呢？如果差别不是很大的话，会不会是dropout、batch_norm这些因素的影响呢？
> > > 方便提供下复现程序么？
> > 
> > 
> > 刚刚测试的结果是在如果去掉model.eval的话，结果就正常了
> 
> 目前结论是去掉model.eval就正常么？你可以发送到 [751681466@qq.com](mailto:751681466@qq.com) 邮箱里面。
最新发现是和优化器有关系……用sgd就正常了，然后用adam把学习率调低到1e-5也正常了……
