### ISSUE TITLE
使用visualdl怎么延续之前的记录

### ISSUE THREAD

**Issue by Fighter-zzp** [PaddlePaddle/Paddle#24316]
我在使用**visual**记录训练数据，但是训练时不小心断了，如果重新训练的话怎么延续之前来的记录？
`train_recall1.add_record(iter_no, r_v[iter_no])
        train_loss1.add_record(iter_no, l_v[iter_no])
        train_recall2.add_record(iter_no, r_v[iter_no] / 1.8)
        train_loss2.add_record(iter_no, l_v[iter_no] * 1.9)`的代码记录训练数据但是前两个既然没绘制出折线图后两个却有？这是为什么？

**Comment by ShenYuhan** [comment]
您好，
1 目前visualdl不支持中断恢复记录，我们会在未来的版本中增加此功能。
2 这个可能需要提供下您的日志我才能确定原因
