### ISSUE TITLE
ValueError: setting an array element with a sequence

### ISSUE THREAD

**Issue by Archimondecy** [PaddlePaddle/Paddle#24310]
1）PaddlePaddle版本：1.6.1
    2）CPU、GPU相同，均复现
    4）系统环境：百度内测试机centos

实现最简单的DNN出现【ValueError: setting an array element with a sequence】错误。实在没有头绪不知道怎么检查求帮助。
错误信息：
![image](https://user-images.githubusercontent.com/9897441/81072339-95986100-8f18-11ea-8b99-1c9abe0f0a8e.png)

最简单的单层DNN也会报错。
读数据：
![image](https://user-images.githubusercontent.com/9897441/81072418-b2349900-8f18-11ea-8aa0-e1cbc59c5004.png)
![image](https://user-images.githubusercontent.com/9897441/81072448-bb256a80-8f18-11ea-8796-f1b0ea52dc13.png)

组网：
![image](https://user-images.githubusercontent.com/9897441/81072596-f45dda80-8f18-11ea-9aa9-39c19b14fcd3.png)

配置：
dataset_mode: Memory
data_reader: pyreader

**Comment by juncaipeng** [comment]
是pyreader配置数据不对，导致错误，可以参考这个issue进行定位：https://github.com/PaddlePaddle/Paddle/issues/15495

建议使用fluid.layers.Print(label), 输出对应的信息。

有更多问题请贴出来。

**Comment by juncaipeng** [comment]
@Archimondecy  请问还有问题吗？

**Comment by Archimondecy** [comment]
> @Archimondecy 请问还有问题吗？

多谢解答，原因后来查到了，是输入的数据有脏数据，导致reshape之后行之间格式错乱报错。
