### ISSUE TITLE
paddlepaddle1.8源码编译安装报错

### ISSUE THREAD

**Issue by dongminghao** [PaddlePaddle/Paddle#24311]
在windows下编译paddle
环境是x86_64 python3.8.2_64  编译成功
安装wheel包时报错。
用python3.7.7_64版本编译出来的wheel可以正常安装。
出错信息
 ERROR: Command errored out with exit status 1:
     command: 'C:\Users\dongm\Anaconda3\envs\paddle1.8cp38\python.exe' 'C:\Users\dongm\Anaconda3\envs\paddle1.8cp38\lib\site-packages\pip\_vendor\pep517\_in_process.py' prepare_metadata_for_build_wheel 'C:\Users\dongm\AppData\Local\Temp\tmp02nada35'
         cwd: C:\Users\dongm\AppData\Local\Temp\pip-install-hw_s7ha2\scipy
    Complete output (216 lines):
    lapack_opt_info:
    lapack_mkl_info:
    No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
    customize MSVCCompiler
      libraries mkl_rt not found in ['C:\\Users\\dongm\\Anaconda3\\envs\\paddle1.8cp38\\lib', 'C:\\', 'C:\\Users\\dongm\\Anaconda3\\envs\\paddle1.8cp38\\libs', 'C:\\Users\\dongm\\Anaconda3\\Library\\lib']
      NOT AVAILABLE

    openblas_lapack_info:
    No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
    customize MSVCCompiler
    No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
    customize MSVCCompiler
      libraries openblas not found in ['C:\\Users\\dongm\\Anaconda3\\envs\\paddle1.8cp38\\lib', 'C:\\', 'C:\\Users\\dongm\\Anaconda3\\envs\\paddle1.8cp38\\libs', 'C:\\Users\\dongm\\Anaconda3\\Library\\lib']
    get_default_fcompiler: matching types: '['gnu', 'intelv', 'absoft', 'compaqv', 'intelev', 'gnu95', 'g95', 'intelvem', 'intelem', 'flang']'
    customize GnuFCompiler
    Could not locate executable g77
    Could not locate executable f77
    customize IntelVisualFCompiler
    Could not locate executable ifort
    Could not locate executable ifl
    customize AbsoftFCompiler
    Could not locate executable f90
    customize CompaqVisualFCompiler
    Could not locate executable DF
    customize IntelItaniumVisualFCompiler
    Could not locate executable efl
    customize Gnu95FCompiler
    Could not locate executable gfortran
    Could not locate executable f95
    customize G95FCompiler
    Could not locate executable g95
    customize IntelEM64VisualFCompiler
    customize IntelEM64TFCompiler
    Could not locate executable efort
    Could not locate executable efc
    customize PGroupFlangCompiler
    Could not locate executable flang
    don't know how to compile Fortran code on platform 'nt'
      NOT AVAILABLE

    openblas_clapack_info:
    No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
    customize MSVCCompiler
    No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
    customize MSVCCompiler
      libraries openblas,lapack not found in ['C:\\Users\\dongm\\Anaconda3\\envs\\paddle1.8cp38\\lib', 'C:\\', 'C:\\Users\\dongm\\Anaconda3\\envs\\paddle1.8cp38\\libs', 'C:\\Users\\dongm\\Anaconda3\\Library\\lib']
      NOT AVAILABLE

    atlas_3_10_threads_info:
    Setting PTATLAS=ATLAS
    No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
    customize MSVCCompiler
      libraries tatlas,tatlas not found in C:\Users\dongm\Anaconda3\envs\paddle1.8cp38\lib
    No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
    customize MSVCCompiler
      libraries lapack_atlas not found in C:\Users\dongm\Anaconda3\envs\paddle1.8cp38\lib
    No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
    customize MSVCCompiler
      libraries tatlas,tatlas not found in C:\
    No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
    customize MSVCCompiler
      libraries lapack_atlas not found in C:\
    No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
    customize MSVCCompiler
      libraries tatlas,tatlas not found in C:\Users\dongm\Anaconda3\envs\paddle1.8cp38\libs
    No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
    customize MSVCCompiler
      libraries lapack_atlas not found in C:\Users\dongm\Anaconda3\envs\paddle1.8cp38\libs
    No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
    customize MSVCCompiler
      libraries tatlas,tatlas not found in C:\Users\dongm\Anaconda3\Library\lib
    No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
    customize MSVCCompiler
      libraries lapack_atlas not found in C:\Users\dongm\Anaconda3\Library\lib
    <class 'numpy.distutils.system_info.atlas_3_10_threads_info'>
      NOT AVAILABLE

    atlas_3_10_info:
    No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
    customize MSVCCompiler
      libraries satlas,satlas not found in C:\Users\dongm\Anaconda3\envs\paddle1.8cp38\lib
    No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
    customize MSVCCompiler
      libraries lapack_atlas not found in C:\Users\dongm\Anaconda3\envs\paddle1.8cp38\lib
    No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
    customize MSVCCompiler
      libraries satlas,satlas not found in C:\
    No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
    customize MSVCCompiler
      libraries lapack_atlas not found in C:\
    No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
    customize MSVCCompiler
      libraries satlas,satlas not found in C:\Users\dongm\Anaconda3\envs\paddle1.8cp38\libs
    No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
    customize MSVCCompiler
      libraries lapack_atlas not found in C:\Users\dongm\Anaconda3\envs\paddle1.8cp38\libs
    No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
    customize MSVCCompiler
      libraries satlas,satlas not found in C:\Users\dongm\Anaconda3\Library\lib
    No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
    customize MSVCCompiler
      libraries lapack_atlas not found in C:\Users\dongm\Anaconda3\Library\lib
    <class 'numpy.distutils.system_info.atlas_3_10_info'>
      NOT AVAILABLE

    atlas_threads_info:
    Setting PTATLAS=ATLAS
    No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
    customize MSVCCompiler
      libraries ptf77blas,ptcblas,atlas not found in C:\Users\dongm\Anaconda3\envs\paddle1.8cp38\lib
    No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
    customize MSVCCompiler
      libraries lapack_atlas not found in C:\Users\dongm\Anaconda3\envs\paddle1.8cp38\lib
    No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
    customize MSVCCompiler
      libraries ptf77blas,ptcblas,atlas not found in C:\
    No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
    customize MSVCCompiler
      libraries lapack_atlas not found in C:\
    No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
    customize MSVCCompiler
      libraries ptf77blas,ptcblas,atlas not found in C:\Users\dongm\Anaconda3\envs\paddle1.8cp38\libs
    No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
    customize MSVCCompiler
      libraries lapack_atlas not found in C:\Users\dongm\Anaconda3\envs\paddle1.8cp38\libs
    No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
    customize MSVCCompiler
      libraries ptf77blas,ptcblas,atlas not found in C:\Users\dongm\Anaconda3\Library\lib
    No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
    customize MSVCCompiler
      libraries lapack_atlas not found in C:\Users\dongm\Anaconda3\Library\lib
    <class 'numpy.distutils.system_info.atlas_threads_info'>
      NOT AVAILABLE

    atlas_info:
    No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
    customize MSVCCompiler
      libraries f77blas,cblas,atlas not found in C:\Users\dongm\Anaconda3\envs\paddle1.8cp38\lib
    No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
    customize MSVCCompiler
      libraries lapack_atlas not found in C:\Users\dongm\Anaconda3\envs\paddle1.8cp38\lib
    No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
    customize MSVCCompiler
      libraries f77blas,cblas,atlas not found in C:\
    No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
    customize MSVCCompiler
      libraries lapack_atlas not found in C:\
    No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
    customize MSVCCompiler
      libraries f77blas,cblas,atlas not found in C:\Users\dongm\Anaconda3\envs\paddle1.8cp38\libs
    No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
    customize MSVCCompiler
      libraries lapack_atlas not found in C:\Users\dongm\Anaconda3\envs\paddle1.8cp38\libs
    No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
    customize MSVCCompiler
      libraries f77blas,cblas,atlas not found in C:\Users\dongm\Anaconda3\Library\lib
    No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
    customize MSVCCompiler
      libraries lapack_atlas not found in C:\Users\dongm\Anaconda3\Library\lib
    <class 'numpy.distutils.system_info.atlas_info'>
      NOT AVAILABLE

    lapack_info:
    No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
    customize MSVCCompiler
      libraries lapack not found in ['C:\\Users\\dongm\\Anaconda3\\envs\\paddle1.8cp38\\lib', 'C:\\', 'C:\\Users\\dongm\\Anaconda3\\envs\\paddle1.8cp38\\libs', 'C:\\Users\\dongm\\Anaconda3\\Library\\lib']
      NOT AVAILABLE

    lapack_src_info:
      NOT AVAILABLE

      NOT AVAILABLE

    setup.py:386: UserWarning: Unrecognized setuptools command ('dist_info --egg-base C:\Users\dongm\AppData\Local\Temp\pip-modern-metadata-qmia9id4'), proceeding with generating Cython sources and expanding templates
      warnings.warn("Unrecognized setuptools command ('{}'), proceeding with "
    Running from scipy source directory.
    C:\Users\dongm\AppData\Local\Temp\pip-build-env-d12t3ngb\overlay\Lib\site-packages\numpy\distutils\system_info.py:624: UserWarning:
        Atlas (http://math-atlas.sourceforge.net/) libraries not found.
        Directories to search for the libraries can be specified in the
        numpy/distutils/site.cfg file (section [atlas]) or by setting
        the ATLAS environment variable.
      self.calc_info()
    C:\Users\dongm\AppData\Local\Temp\pip-build-env-d12t3ngb\overlay\Lib\site-packages\numpy\distutils\system_info.py:624: UserWarning:
        Lapack (http://www.netlib.org/lapack/) libraries not found.
        Directories to search for the libraries can be specified in the
        numpy/distutils/site.cfg file (section [lapack]) or by setting
        the LAPACK environment variable.
      self.calc_info()
    C:\Users\dongm\AppData\Local\Temp\pip-build-env-d12t3ngb\overlay\Lib\site-packages\numpy\distutils\system_info.py:624: UserWarning:
        Lapack (http://www.netlib.org/lapack/) sources not found.
        Directories to search for the sources can be specified in the
        numpy/distutils/site.cfg file (section [lapack_src]) or by setting
        the LAPACK_SRC environment variable.
      self.calc_info()
    Traceback (most recent call last):
      File "C:\Users\dongm\Anaconda3\envs\paddle1.8cp38\lib\site-packages\pip\_vendor\pep517\_in_process.py", line 257, in <module>
        main()
      File "C:\Users\dongm\Anaconda3\envs\paddle1.8cp38\lib\site-packages\pip\_vendor\pep517\_in_process.py", line 240, in main
        json_out['return_val'] = hook(**hook_input['kwargs'])
      File "C:\Users\dongm\Anaconda3\envs\paddle1.8cp38\lib\site-packages\pip\_vendor\pep517\_in_process.py", line 110, in prepare_metadata_for_build_wheel
        return hook(metadata_directory, config_settings)
      File "C:\Users\dongm\AppData\Local\Temp\pip-build-env-d12t3ngb\overlay\Lib\site-packages\setuptools\build_meta.py", line 158, in prepare_metadata_for_build_wheel
        self.run_setup()
      File "C:\Users\dongm\AppData\Local\Temp\pip-build-env-d12t3ngb\overlay\Lib\site-packages\setuptools\build_meta.py", line 249, in run_setup
        super(_BuildMetaLegacyBackend,
      File "C:\Users\dongm\AppData\Local\Temp\pip-build-env-d12t3ngb\overlay\Lib\site-packages\setuptools\build_meta.py", line 143, in run_setup
        exec(compile(code, __file__, 'exec'), locals())
      File "setup.py", line 505, in <module>
        setup_package()
      File "setup.py", line 501, in setup_package
        setup(**metadata)
      File "C:\Users\dongm\AppData\Local\Temp\pip-build-env-d12t3ngb\overlay\Lib\site-packages\numpy\distutils\core.py", line 135, in setup
        config = configuration()
      File "setup.py", line 403, in configuration
        raise NotFoundError(msg)
    numpy.distutils.system_info.NotFoundError: No lapack/blas resources found.
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'C:\Users\dongm\Anaconda3\envs\paddle1.8cp38\python.exe' 'C:\Users\dongm\Anaconda3\envs\paddle1.8cp38\lib\site-packages\pip\_vendor\pep517\_in_process.py' prepare_metadata_for_build_wheel 'C:\Users\dongm\AppData\Local\Temp\tmp02nada35' Check the logs for full command output.

**Comment by zhwesky2010** [comment]
@dongminghao 请问从头到尾用的都是Anaconda3中的python吗，是否有多个python

**Comment by dongminghao** [comment]
没用anaconda，直接从官网下载的python.exe，有多个版本，同时装了3.7和3.8，用系统环境变量做区分

**Comment by zhwesky2010** [comment]
@dongminghao 这个用的是dongm这个user的Anaconda3环境，要不你看下 where python，看下默认的python环境变量对不对，多个的话和顺序也有关系

**Comment by zhwesky2010** [comment]
@dongminghao 感觉是编译时、安装时的python似乎对不上，编译时用的python可以在build/CMakeCache.txt里搜python看下，安装时可以用 where python看下默认是哪个生效了
