### ISSUE TITLE
paddlepaddle-gpu 安装后 import paddle.fluid 提示no module named 'paddle'

### ISSUE THREAD

**Issue by lerry-lee** [PaddlePaddle/Paddle#24320]
系统：win10
python：3.6
cuda:：10
paddle：1.7.2.post.107
安装方式：pip install paddlepaddle-gpu==1.7.2.post107 -i https://mirror.baidu.com/pypi/simple
安装后pip list有paddlepaddle-gpu 1.7.2.post107
但是进入Python模式,
>>>import paddle.fluid
ModuleNotFoundError: No module named 'paddle'
请问该怎么解决呢？

**Comment by JepsonWong** [comment]
您需要check下你的pip对应的python是哪个python。
目前您用python进入的python环境应该不是安装paddle的python。

**Comment by Adarine99** [comment]
你好：
     遇到同样的问题，确认pip 与 python 版本是对应的，paddle确实安装到pyhton环境下，请问是什么原因呢
