### ISSUE TITLE
Please add GELU in-place execution support

### ISSUE THREAD

**Issue by jczaja** [PaddlePaddle/Paddle#24328]
We recently added in-place execution to oneDNN kernels of softmax, elementwise_add and activations.
There is also support in GELU activation, but cannot be used as GELU of PaddlePaddle does not have
InplaceInferer e.g. it does not support in-place execution. If possible , please add GELU in-place execution support .

**Comment by lidanqing-vv** [comment]
GELU activation will bring small performance gain so it will be low priority, jacek just found this is missing so added it.
About date to be ready: no rush

**Comment by jczaja** [comment]
mkldnn_inplace pass is disabled so no need to work on this
