### ISSUE TITLE
疑似文档链接有误

### ISSUE THREAD

**Issue by houj04** [PaddlePaddle/Paddle#24324]
在“分布式GPU训练优秀实践”的文档中：
https://www.paddlepaddle.org.cn/documentation/docs/zh/advanced_guide/performance_improving/multinode_training_improving/dist_training_gpu.html
里面有一段写的是
“使用 pyreader 。参考 这里 使用pyreader，并开启 use_double_buffer 。”
有两个问题：
1、链接点进去不是介绍pyreader的，而是跳到了“快速上手”的文档首页。
2、现在还推荐用pyreader么？隐约记得有dataloader或者其他替代品了。

**Comment by zhangting2020** [comment]
你好，感谢反馈的文档问题，我们会尽快修复。目前不推荐使用pyreader了，请使用[dataloader](https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api_cn/io_cn/DataLoader_cn.html#dataloader)接口。

**Comment by zhangting2020** [comment]
@sandyhouse 请看看“分布式GPU训练优秀实践”的文档问题。需要对pyreader部分修改
