### ISSUE TITLE
请问下PaddlePaddle发布时候用的cudnn是什么版本

### ISSUE THREAD

**Issue by houj04** [PaddlePaddle/Paddle#24327]
在文档中写的是要求7.3+，我自己的机器上装的是7.5.1，运行时会报这样的提示：
WARNING: device: 0. The installed Paddle is compiled with CUDNN 7.6, but CUDNN version in your machine is 7.5, which may cause serious incompatible bug. Please recompile or reinstall Paddle with compatible CUDNN version.
所以想问下，PaddlePaddle编译的时候，上面这句提到的7.6，具体是7.6.x？
这样也方便在自己的机器（包括集群上）预装相应的包。

**Comment by zhangting2020** [comment]
- 是这篇[安装文档](https://www.paddlepaddle.org.cn/documentation/docs/zh/install/index_cn.html)吧，这里确实没有写的很清楚，我们会安排相关同学完善文档。
- 提示的7.6，只要是7.6.x就可以，后面的小版本号并不影响。但是如果是7.5的话，可能会有不兼容问题。

**Comment by houj04** [comment]
不仅仅是这一篇。例如：
https://www.paddlepaddle.org.cn/install/quick
这里也提到了cudnn7.3+，可能会给用户这样一种感觉：文档写的7.3就行，我装了7.5，应该够用了吧，但是怎么还提示有兼容性问题呢。

**Comment by zhangting2020** [comment]
和相关同学确认了下，现在发布的版本是cudnn7.6编译的。这些编译安装相关的文档，我们需要统一完善一下。感谢反馈。

**Comment by houj04** [comment]
收到，多谢~

**Comment by zhangting2020** [comment]
@JepsonWong 麻烦看看上面的文档问题，需要对cudnn版本的说明进行完善
