### ISSUE TITLE
python2.7 同时import paddle 和 multiprocessing,会有随机coredump

### ISSUE THREAD

**Issue by wawltor** [PaddlePaddle/Paddle#24348]
from multiprocessing import Pool
import paddle.fluid

def f(x):
    return x*x

p = Pool(1) 
x = [1,2,3,4,5,6]
y = p.map(f, x)
print y
p.terminate()

**Comment by MrChengmo** [comment]
请问有稳定复现的环境吗？
 1）PaddlePaddle版本：请提供您的PaddlePaddle版本号，例如1.1或CommitID
 2）CPU：预测若用CPU，请提供CPU型号，MKL/OpenBlas/MKLDNN/等数学库使用情况
 3）GPU：预测若用GPU，请提供GPU型号、CUDA和CUDNN版本号
 4）系统环境：请您描述系统类型、版本，例如Mac OS 10.14，Python版本

**Comment by wawltor** [comment]
> 请问有稳定复现的环境吗？
> 1）PaddlePaddle版本：请提供您的PaddlePaddle版本号，例如1.1或CommitID
> 2）CPU：预测若用CPU，请提供CPU型号，MKL/OpenBlas/MKLDNN/等数学库使用情况
> 3）GPU：预测若用GPU，请提供GPU型号、CUDA和CUDNN版本号
> 4）系统环境：请您描述系统类型、版本，例如Mac OS 10.14，Python版本


1)  paddle版本 1.8
2）3）cpu即可，因为是import的时候出错，还没有进入训练和预测，看起来是包之间的兼容性问题
4）centos python2.7
