### ISSUE TITLE
Reader 似乎再读取结束时，Paddle core

### ISSUE THREAD

**Issue by OleNet** [PaddlePaddle/Paddle#24358]
如果您没有查询到相似问题，为快速解决您的提问，建立issue时请提供如下细节信息：
- 标题：简洁、精准概括您的问题，例如“Insufficient Memory xxx" ”
- 版本、环境信息：
    1）PaddlePaddle版本：paddlepaddle gpu 1.7.0
    2）CPU：
    3）GPU：P40, 
    4）系统环境：Centos
- 训练信息
    1）单机多卡
    2）显存信息 22GB

- 复现信息：如为报错，请给出复现环境、复现步骤
- 问题描述：请详细描述您的问题，同步贴出报错信息、日志、可复现的代码片段

![图片](https://user-images.githubusercontent.com/3206718/81409665-17cf9200-9172-11ea-8017-0b211e6c7ed4.png)

![图片](https://user-images.githubusercontent.com/3206718/81409686-23bb5400-9172-11ea-9ee8-3bea7b2cd3e7.png)

Python3会出这个问题， Python2不会

**Comment by MrChengmo** [comment]
你好，看报错信息无法准确定位是Reader 哪个步骤的问题，请问可以提供复现的代码或者环境吗，我找负责Reader API的同学跟进一下。
