### ISSUE TITLE
请问现在怎么conda或pip安装paddle1.6

### ISSUE THREAD

**Issue by A1exy** [PaddlePaddle/Paddle#24356]
为使您的问题得到快速解决，在建立Issue前，请您先通过如下方式搜索是否有相似问题:【搜索issue关键字】【使用labels筛选】【官方文档】

建立issue时，为快速解决问题，请您根据使用情况给出如下信息：
- 标题：请包含关键词“安装错误”/“编译错误”，例如“Mac编译错误”
- 版本、环境信息：
    1）PaddlePaddle版本：请提供您的PaddlePaddle版本号（如1.1）或CommitID
    2）CPU：请提供CPU型号，MKL/OpenBlas/MKLDNN/等数学库的使用情况
    3）GPU：请提供GPU型号，CUDA和CUDNN版本号
    4）系统环境：请说明系统类型、版本（如Mac OS 10.14）、Python版本
- 安装方式信息：
1）pip安装/docker安装
2）本地编译：请提供cmake命令，编译命令
3）docker编译：请提供docker镜像，编译命令            
  特殊环境请注明：如离线安装等
- 复现信息：如为报错，请给出复现环境、复现步骤
- 问题描述：请详细描述您的问题，同步贴出报错信息、日志/代码关键片段

Thank you for contributing to PaddlePaddle.
Before submitting the issue, you could search issue in Github in case that there was a similar issue submitted or resolved before.
If there is no solution,please make sure that this is an installation issue including the following details:
**System information**
-PaddlePaddle version （eg.1.1）or CommitID
-CPU: including CPUMKL/OpenBlas/MKLDNN version
-GPU: including CUDA/CUDNN version
-OS Platform (eg. Mac OS 10.14)
-Python version
- Install method: pip install/install with docker/build from source(without docker)/build within docker
- Other special cases that you think may be related to this problem, eg. offline install, special internet condition   
**To Reproduce**
Steps to reproduce the behavior
**Describe your current behavior**
**Code to reproduce the issue**
**Other info / logs**

**Comment by MrChengmo** [comment]
使用pip安装时，指定paddle版本
```bash
pip install paddlepaddle==1.6.2
```

**Comment by A1exy** [comment]
现在问题是paddle镜像网站https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/Paddle/    并没有paddle1.6的版本了，而本地直接指定版本为1.6时会conda或Pip均报找不到的错误。
![image](https://user-images.githubusercontent.com/7035538/81407470-0a180d80-916e-11ea-979c-5ffd124aa03c.png)
不知道paddle1.6的安装镜像现在放在哪里了   @MrChengmo

**Comment by MrChengmo** [comment]
> 现在问题是paddle镜像网站https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/Paddle/ 并没有paddle1.6的版本了，而本地直接指定版本为1.6时会conda或Pip均报找不到的错误。
> ![image](https://user-images.githubusercontent.com/7035538/81407470-0a180d80-916e-11ea-979c-5ffd124aa03c.png)
> 不知道paddle1.6的安装镜像现在放在哪里了 @MrChengmo

可以使用Python官方源，或百度源，pip 命令 额外参数：

``` bash
pip install paddlepaddle --index-url=http://pip.baidu.com/pypi/simple --trusted-host pip.baidu.com
```

**Comment by A1exy** [comment]
![image](https://user-images.githubusercontent.com/7035538/81468574-f8d50c80-9212-11ea-9159-18689ce536a5.png)

@MrChengmo     试了下不行 ,不是还要翻墙吧。。。

**Comment by DDDivano** [comment]
首先，paddlepaddle-gpu没有1.6.2这个版本号，因为gpu cuda库发布了9，10两个版本，所以1.6.2对应的是1.6.2.post97，1.6.2.post107
pypi源 https://pypi.org/project/paddlepaddle-gpu/1.6.2.post107/
可以参考官网：
![image](https://user-images.githubusercontent.com/10734244/81469450-77cc4400-9217-11ea-9c96-7820c8590906.png)

**Comment by A1exy** [comment]
@DDDivano  好的谢谢
