### ISSUE TITLE
建议提供：限制一个Paddle进程最多可以使用多少显存的方案

### ISSUE THREAD

**Issue by souchip** [PaddlePaddle/Paddle#24364]
在一些情况下，为了提升机器资源利用率，需要在同一个计算节点运行多个Paddle进程。
为了实现显存资源的分配，希望可以限制一个Paddle进程最多可以使用多少显存。
比如，在启动参数中指定。

**Comment by zhiqiu** [comment]
hi，在paddle新版本(1.7.2+)中提供了FLAGS_gpu_memory_limit_mb的flag，可以限制单个任务的GPU显存大小，单位是MB。
