### ISSUE TITLE
 python安装cocoapi遇到错误

### ISSUE THREAD

**Issue by xiaoli-ai** [PaddlePaddle/Paddle#24375]
环境：windows10  paddle1.8  python3.7  CPU   实现maskrcnn
使用conda安装依赖项
编译cocoapi时出错如下：
>>>python setup.py install
running install
running bdist_egg
running egg_info
writing pycocotools.egg-info\PKG-INFO
writing dependency_links to pycocotools.egg-info\dependency_links.txt
writing requirements to pycocotools.egg-info\requires.txt
writing top-level names to pycocotools.egg-info\top_level.txt
reading manifest file 'pycocotools.egg-info\SOURCES.txt'
writing manifest file 'pycocotools.egg-info\SOURCES.txt'
installing library code to build\bdist.win-amd64\egg
running install_lib
running build_py
running build_ext
building 'pycocotools._mask' extension
cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -ID:\anaconda\envs\paddle_mask\lib\site-packages\numpy\core\include -I../common -ID:\anaconda\envs\paddle_mask\include -ID:\anaconda\envs\paddle_mask\include -ID:\VisualStudio\VC\Tools\MSVC\14.16.27023\bin\Hostx64\x64 -ID:\VisualStudio\VC\Tools\MSVC\14.16.27023\include "-ID:\Windows Kits\10\Include\10.0.17763.0\shared" "-ID:\Windows Kits\10\Include\10.0.17763.0\ucrt" "-ID:\Windows Kits\10\Include\10.0.17763.0\um" "-ID:\Windows Kits\10\Include\10.0.17763.0\winrt" /Tc../common/maskApi.c /Fobuild\temp.win-amd64-3.7\Release\../common/maskApi.obj -std=c99
error: command 'cl.exe' failed: No such file or directory

**Comment by mapingshuo** [comment]
编译cocoapi出错，建议在cocoapi库下提问。paddle这边，我帮您找一位paddle detection的老师看看是否熟悉类似问题。

**Comment by qingqing01** [comment]
@xiaoli-ai 搜索了下，是由于win机器没安装C++编译器： https://stackoverflow.com/questions/41724445/python-pip-on-windows-command-cl-exe-failed  可以试下：`pip install pycocotools`
