### ISSUE TITLE
develop版本，transformer模型CPU-MKLDNN预测速度明显下降

### ISSUE THREAD

**Issue by OliverLPH** [PaddlePaddle/Paddle#24373]
**System information**
-PaddlePaddle version: `develop`, `6d8dcc7407`
-CPU: `Intel(R) Xeon(R) CPU E5-2650 v4 @ 2.20GHz`, mkldnn enabled
-GPU: None
-OS Platform (eg.Mac OS 10.14): Ubuntu1604 
-Docker image: `hub.baidubce.com/paddlepaddle/paddle:latest-gpu-cuda10.0-cudnn7-dev`
-Python version: Python3.7
-Cmake orders
-C++version.txt: used python api
-API information: inference configuration
```python
config.disable_gpu()
config.set_cpu_math_library_num_threads(8)
config.enable_mkldnn()
config.switch_ir_optim()
config.enable_profile()
```

**To Reproduce** 

1. run test without mkldnn
```python
python test_transformer.py --model_dir="models/transformer" --data_dir=data/data.txt
```
![image](https://user-images.githubusercontent.com/14963836/81472029-f5984b80-9227-11ea-8617-ec0fcaf19ed9.png)

2. run test with mkldnn
```python
python test_transformer.py --model_dir="models/transformer" --data_dir=data/data.txt --use_mkldnn
```

![mkldnn_transformer](https://user-images.githubusercontent.com/14963836/81472307-b1a64600-9229-11ea-8251-9b82804fc254.jpg)

**Describe your current behavior**
Speed of mkldnn inference is much slower than analysis inference and previous commit(e.g. 8002b2beb4a or 1.7.2)

**Code to reproduce the issue**
[test_transformer.txt](https://github.com/PaddlePaddle/Paddle/files/4603326/test_transformer.txt)

**Other info / logs**

**Comment by lidanqing-vv** [comment]
Hi, @jczaja please take a look at transformer performance drop.

**Comment by lidanqing-vv** [comment]
Hi, @luotao1 , Jacek has verified this issue does not exist after merging #24442 . Maybe Baidu validation verify again on Baidu machines and then we close this issue?

**Comment by OliverLPH** [comment]
Hi, @lidanqing-intel 
I have verified this issue has been fixed. This issue will be closed, thx~
