### ISSUE TITLE
建议框架新增参数，用于选择是否启用 Unified Memory

### ISSUE THREAD

**Issue by souchip** [PaddlePaddle/Paddle#24380]
在一些场景中，我们需要单机能有更大的Memory，同时可以接受Memory的读写速度降低。
可以通过invdia官方提供的cudaMallocManaged()来实现。
https://devblogs.nvidia.com/unified-memory-in-cuda-6/
https://devblogs.nvidia.com/unified-memory-cuda-beginners/

**Comment by zhiqiu** [comment]
关于cuda unified memory，之前有相关的调研：https://github.com/PaddlePaddle/Paddle/wiki/Survey-of-CUDA-Unified-Memory 。

**Comment by senseb** [comment]
> 关于cuda unified memory，之前有相关的调研：https://github.com/PaddlePaddle/Paddle/wiki/Survey-of-CUDA-Unified-Memory 。

调研中提到："tensorflow用Unified Memory来做测试框架，这个倒是可以参考"
这部分有后续的计划吗？

**Comment by zhiqiu** [comment]
目前还未明确安排，后续我们会内部讨论下是否开展。
