### ISSUE TITLE
paddle_trainer.INFO里auc的计算机制？

### ISSUE THREAD

**Issue by wangsouc** [PaddlePaddle/Paddle#2443]
MPI cluster训练，请教一下__auc_evaluator_0__的Eval和CurrentEval的计算机制。
I0612 15:12:50.297226 18323 TrainerInternal.cpp:165]  Batch=2760 samples=11304960 AvgCost=0.113212 CurrentCost=0.109198 Eval: __auc_evaluator_0__=0.7042 classification_error_evaluator=0.02633  CurrentEval: __auc_evaluator_0__=0.727945 classification_error_evaluator=0.0255005

**Comment by jacquesqiao** [comment]
### 
训练逻辑主要在[`TrainerInternal::trainOneBatch`](https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/trainer/TrainerInternal.cpp#L66):

### 1，
先调用[`forwardBackwardBatch`](https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/trainer/TrainerInternal.cpp#L119)，计算出当前batch的gradient，然后调用callback 更新了参数。

### 2，
然后调用了[`eval`](https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/trainer/TrainerInternal.cpp#L146)计算evaluator的值。

### 3，
之后才是显示[`结果`](https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/trainer/TrainerInternal.cpp#L165)

### 结论：
先更新了参数，然后进行evaluat。

**Comment by lcy-seso** [comment]
这个是问 Eval 和 CurrentEval 这两个指标的区别吗？
如果是的话：
- CurrentEval 是在当前Batch上的评估结果
- Eval 是到当前batch 为止，评估结果的平均值

因此，通常，current eval 抖动更强，在第一个pass的时候，current eval 评估效果会更好，eval 看上去更差一些。
