### ISSUE TITLE
yolov2-tiny-voc里面的配置step有个-1怎么理解

### ISSUE THREAD

**Issue by zhengzihe** [PaddlePaddle/Paddle#24431]
![image](https://user-images.githubusercontent.com/58216756/81661342-8eb8a380-946e-11ea-95ae-7c76953ee228.png)

yolov2-tiny-voc里面的配置step有个-1怎么理解，后面的scale学习率不应该是逐step递减的吗，第二个scale为10为什么要这样设计

**Comment by heavengate** [comment]
> ![image](https://user-images.githubusercontent.com/58216756/81661342-8eb8a380-946e-11ea-95ae-7c76953ee228.png)
> 
> yolov2-tiny-voc里面的配置step有个-1怎么理解，后面的scale学习率不应该是逐step递减的吗，第二个scale为10为什么要这样设计

`steps`定义的是从第几个step开始改变学习率，对应改变学习率的系数定义在`scales`里面，`steps`第一个值为-1只是为了占位，其实就是表示`0-100`iters的时候用`0.1`倍的学习率做warmup，100iters的时候还原回来正常的学习率。

另外，darknet的问题建议在darknet repo里提issue https://github.com/pjreddie/darknet
