### ISSUE TITLE
pvanet model INT8 model accuracy drop 10%

### ISSUE THREAD

**Issue by lidanqing-vv** [PaddlePaddle/Paddle#24461]
Customer model pvanet accuracy after QAT INT8 the model accuracy drop 10%

**System information**
-PaddlePaddle version: develop
-CPU: i9 

**To Reproduce**
Download test, dataset and model from 
`shanghai-6271-ip:/data/models/ocr_test_intel_with_data.tgz`
Run following command:
```
sh test_metric.sh models_pvanet/model_folder/ 28
```
**Describe your current behavior**
I have set all relu output datatype, and also set concat to INT8 concat kernel. But the accuracy only improved from `75.03%` to `75.28%`, while the FP32 model accuracy is `85%`

**Describe current result**
fp32:
```
hit_count: 3437 gt_count: 3886 det_count: 3904
recall: 88.45 precision: 88.04 f_measure: 88.24
0.995053826011
```

Qat:
```
hit_count: 3379 gt_count: 3886 det_count: 3890
recall: 86.95 precision: 86.86 f_measure: 86.91
0.994968925718
```

INT8：
```
hit_count: 2937 gt_count: 3886 det_count: 3917
recall: 75.58 precision: 74.98 f_measure: 75.28
0.973782771536
```

**Comment by wojtuss** [comment]
It lools that quantization of short sequences of convolutions (1-2 operators) causes the accuracy to drop. With the use of the `--op_ids_to_skip` introduced in the PR https://github.com/PaddlePaddle/Paddle/pull/24689 those operators were excluded from quantization. The following are the pvnet_ocr test results obtained on a CLX 6248 machine.

affinity settings:
```
export KMP_AFFINITY=granularity=fine,compact,1,0
export KMP_BLOCKTIME=1
```
	
* original QAT model:
	latency: 311.98 ms
	accuracy: 86.91 %
* INT8, all ops quantized:
	latency: 131.31 ms (2.38x faster)
	accuracy: 75.39 % (-11.52 pp)
* INT8, single and double conv2d ops excluded from quantization:
	latency: 145.17 ms (2.15x faster)
	accuracy: 86.23 % (-0.68 pp)

The question of why quantization of all ops causes the accuracy drop compared to the QAT model (fake-quantizing all ops) is being further investigated.

**Comment by juncaipeng** [comment]
@wojtuss How to set op_ids_to_skip for pvnet_ocr model or other models?  Is it too tricky?

**Comment by wojtuss** [comment]
Our investigation led to the following observations:

* The quantization strategy used in the model is `range_abs_max`, which means that a quantization scale for a variable tensor in the model is calculated based on the maximum absolute value of all the values in the tensor over many iterations of the training. This approach is very sensitive to outliers, i.e. to those values in the tensor which are far from the vast majority of all the values.

* Analysis of batch_norm operators' outputs present in the model showed that values of the output tensors are heavily concentrated around 0. Here are examples of histograms (in linear and logarithmic scale), for the variable `conv2_2/2/bn.tmp_2` (an output of a batch_norm op) in the first iteration of the test (in next iterations the pictures are very similar):
![image](https://user-images.githubusercontent.com/19307410/83310039-193d2900-a20b-11ea-8cf2-c75b37bad82f.png)
![image](https://user-images.githubusercontent.com/19307410/83310054-235f2780-a20b-11ea-9101-2cf69fdb583c.png)
(the horizontal axis shows the bucket numbers)

* The `out_threshold` attribute of the batch_norm op preceding the `conv2_2/2/bn.tmp_2` variable is equal to 1.165549635887146, so the quantization scale for this variable is `127/1.165549635887146 = 108.9614685549923`. In the first iteration of the test, the minimum and maximum values in the variable tensor are -0.634301 and 0.50954, so all the values from the tensor after INT8 quantization fit into the interval [-69, 56], while [-128, 127] is available. Considering the heavy concentration of the values around zero, the vast majority of the values are transformed into 0, -1 or 1 during INT8 quantization, causing huge aliasing and information loss.

* If fusing batch_norm operators with convolutions is skipped before INT8 quantization and batch_norm is calculated in FP32 during INT8 inference, the INT8 accuracy reaches 88.20% which is very close to 88.77% obtained from the original QAT model.

Conclusions:
* From our experience, the range-based scaling works best for static variables like conv2d's weights. For activation tensors, moving-average- or KL-based scaling is usually optimal.
* We would suggest applying `moving_average_abs_max` strategy for activation quantization scales computation, so the impact of outliers in the variable tensors could be minimized and the range of the INT8 values could be better utilized, achieving much smaller accuracy drop after INT8 quantization.

**Comment by wojtuss** [comment]
@juncaipeng , as I described in the document `python/paddle/fluid/contrib/slim/tests/QAT_mkldnn_int8_readme.md` in the PR https://github.com/PaddlePaddle/Paddle/pull/24689:
To get an id of a particular operator run the script with the `--debug` option first (see below for the description of the option), and having opened the generated file `qat_int8_cpu_quantize_placement_pass.dot` find the id number written in parentheses next to the name of the operator.

**Comment by lidanqing-vv** [comment]
Some update of this issue according to @wojtuss  :

The pvanet_ocr has a the following structure in the graph:
 
As the output from the second conv2d op is consumed by another conv2d and batch_norm, the fuse `conv_bn_fuse_pass` cannot be applied to it, and quantization sequence has to be broken here to calculate `batch_norm` using FP32.
The idea is to add a pass `conv_bif_bn_fuse_pass` (`bif` stands for bifurcation), which would:
•	add a copy of the upper conv2d op,
•	make the first conv2d output go to the lower conv2d only,
•	make the copy conv2d output go to the batch_norm only.
This way the `conv_bn_fuse_pass` could be applied.
Regarding performance, execution of a longer sequence of INT8 kernels with additional conv2d op should be faster than executing single `conv2d` INT8 op with FP32 batch_norm and relu.

**Comment by wojtuss** [comment]
It turned out that the `conv_bif_bn_fuse_pass` pass cannot work due to the way the `ResidualData` input is handled by oneDNN convolution primitive (it is overwritten by conv, but there are two convs which consume this input).

The next optimization options are to enable INT8 kernel for `batch_norm` and fuse `batch_norm+relu`. We will start working on that in August.
