### ISSUE TITLE
动态图模式下的CRF接口

### ISSUE THREAD

**Issue by yaweisun** [PaddlePaddle/Paddle#24466]
- 版本、环境信息
PaddlePaddle版本：1.7
- 建议描述：
我目前在使用paddle 1.7的静态图模式，需要用到CRF，但是在文档里搜到的带“CRF”的接口（包括linear_chain_crf和crf_decoding）都注明了“该API仅支持【静态图】模式”，请问有相应的动态图接口吗？或者有没有其他替代方案呢？

**Comment by phlrain** [comment]
https://github.com/PaddlePaddle/models/blob/develop/dygraph/lac/sequence_labeling.py#L126
可以参考这个的实现

**Comment by yaweisun** [comment]
> https://github.com/PaddlePaddle/models/blob/develop/dygraph/lac/sequence_labeling.py#L126
> 可以参考这个的实现

好的，感谢！
