### ISSUE TITLE
clone program报错

### ISSUE THREAD

**Issue by zhengzihe** [PaddlePaddle/Paddle#24475]
![image](https://user-images.githubusercontent.com/58216756/81770978-5d92ae80-9514-11ea-9cd5-365cd4e91b2f.png)

![QQ图片20200513122511](https://user-images.githubusercontent.com/58216756/81771421-80719280-9515-11ea-82b6-7cc96731470e.jpg)

训练的时候没问题，验证的时候，clone program报错了

**Comment by yaoxuefeng6** [comment]
你好 请问一下能提供下复现代码吗？ 还是跑哪个官方例子的时候报的这个错误？

**Comment by zhengzihe** [comment]
![image](https://user-images.githubusercontent.com/58216756/81776821-20cdb400-9522-11ea-80d2-37cefa2d2bf4.png)
只是多加了一个自定义的attention层，但是train的过程是没报错的

**Comment by zhengzihe** [comment]
差不多就是继承了paddlehub的sequencetask

**Comment by zhengzihe** [comment]
官方的是单任务，我改成了多任务

**Comment by yaoxuefeng6** [comment]
你好 麻烦验证下提供的demo是否可以跑通 可以在在paddlehub上提个issue？地址： https://github.com/PaddlePaddle/PaddleHub/issues

**Comment by zhengzihe** [comment]
好的，我去hub上提了，issue可以关掉了
