### ISSUE TITLE
关于更多函数功能的建议

### ISSUE THREAD

**Issue by Preston-Dong** [PaddlePaddle/Paddle#24491]
在贵框架已经运行了很多次的代码，感谢提供的平台，不过有一点小建议，能不能增加函数，如相似性指标SSIM，tf和pytorch均提供了接口，可以很方便的运用。
真心希望paddlepaddle越来越好！

**Comment by yaoxuefeng6** [comment]
你好 感谢你的建议，我们后续会评估下这几个功能
