### ISSUE TITLE
tensor索引坐标的问题

### ISSUE THREAD

**Issue by DZhaoXd** [PaddlePaddle/Paddle#24504]
现遇到一个坐标索引问题，tensor A  的 shape 是 [b, w, h]，b是batchsize， w,h分别是长和宽；tensor B 的 shape 是 [b, 3, 2]，表示对batch中的每一个数据都存在3个需要索引的坐标（x, y）。请问怎么根据tensor B 去索引 tensor A得到一个[b, 3]的结果？

**Comment by yaoxuefeng6** [comment]
你好 抱歉目前该功能得文档还未合入https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/tensor/search.py 麻烦先看下这两个函数的源码注释吧。应该满足需求 index_sample, index_select。1.7.2版本有index_sample功能，1.8新版本有这俩功能
