### ISSUE TITLE
Ernie INT8 accuracy drop on 2.0-alpha

### ISSUE THREAD

**Issue by lidanqing-vv** [PaddlePaddle/Paddle#24510]
**System information**
-PaddlePaddle version develop f1c57d648caf103de8e64aa8c2bded1820b50306
-CPU: Intel(R) Xeon(R) Gold 6271C CPU @ 2.60GHz
-Machine: Shanghai-6271  
**To Reproduce**
https://github.com/PaddlePaddle/benchmark/pull/387/files
**Describe your current status**
INT8 Ernie accuracy drop from 0.7964 to  0.794378
**Other info**
Customer want to solve the accuracy drop problem
Please use batch 10. Bathc size 50 will fail

**Comment by lidanqing-vv** [comment]
The commit is  `e1a7a880576f072bf27cbda568bcc4a5bcfb25fd`
```
2020-05-20 18:59:55,181-INFO: Accepted accuracy drop threshold: 0.01. (condition: (FP32_acc - INT8_acc) <= threshold)
2020-05-20 18:59:55,181-INFO: FP32: avg accuracy: 0.802008
2020-05-20 18:59:55,181-INFO: INT8: avg accuracy: 0.794378
```
This commit did INT8 operater fuses and bring performance improvement.

**Comment by sfraczek** [comment]
Aside from what we know here, which is:
* accuracy with disabled **only** reshape_transpose_matmul is good,

We got this new data while analyzing the problem:
* accuracy with disabled **only** scale_matmul fuse is good,
* accuracy with disabled **only** cpu_quantize_squash is good.

**Comment by sfraczek** [comment]
@wojtuss and I have investigated the cause and here is what we concluded.
## analysis of the cause
### Original graph:
![image](https://user-images.githubusercontent.com/17185347/86104343-355c1080-babe-11ea-8869-6e19be769858.png)

mul -> fake_dequantize -> elementwise_add is replaced with Matmul
Which means that biases are on floats (in elementwise_add). Initially, FC, which replaces that, has also biases on floats. It works fine until the following happens: After fuse Reshape Transpose Matmul the dequantize is moved just below FC and then OP->Dequant squash is called, which fuses FC with dequantize.
That makes a pair of output quantization followed by dequantization disappear - which were removing the decimal part of floats. Now the output is on floats from the start so there is no removing of the decimal part.
![image](https://user-images.githubusercontent.com/17185347/86104375-3f7e0f00-babe-11ea-97e9-0e8badfd5825.png)
