### ISSUE TITLE
Empty Document for RNN Configuration

### ISSUE THREAD

**Issue by Haichao-Zhang** [PaddlePaddle/Paddle#2451]
There is no contents for RNN configuration in HOW TO:
http://www.paddlepaddle.org/doc/howto/deep_model/rnn/index_en.html

Previously, there are contents about RNN configuration involving single level RNN, Hierarchical RNN etc.

**Comment by luotao1** [comment]
You can refer to the Chinese version http://www.paddlepaddle.org/develop/doc_cn/howto/deep_model/rnn/index_cn.html firstly.
