### ISSUE TITLE
What is the condition when padding fc is used in inference

### ISSUE THREAD

**Issue by lidanqing-vv** [PaddlePaddle/Paddle#24523]
Intel want to enable fc_mkldnn so here we have some questions about padding. 

1. Is padding in fc explicitly enabled somewhere under some condition or GEMM choose padding by default,
2. Can we get some help on what are the conditions for the padding to enable.
3. Intel would like to add a pass which enables padding in FC when the condition are met.

**Comment by luotao1** [comment]
@GaoWei8 Please have answer it.
