### ISSUE TITLE
train完之后模型使用及性能评估

### ISSUE THREAD

**Issue by Damon-wyg** [PaddlePaddle/Paddle#2452]
在模型跑完之后，在output会有每个pass训练出来的w和bias的二进制文件。请教两个问题：
1. 怎么评估模型的auc？
2. 线上使用这个模型时，具体应该怎么操作？如果是直接加载这个w和bias到线上，线上配置相应的网络结构，然后train的网络修改了，线上也要修改网络结构？

**Comment by qingqing01** [comment]
- 线下评估auc
  可以使用[AUC evalutor](http://www.paddlepaddle.org/develop/doc/api/v2/config/evaluators.html#auc)，在网络配置中使用该evalutor即可。

- 线上使用模型
   - 线上预测：可以参考[C-API](https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/capi/examples/model_inference/README.md)
  - 配置： train的网络修改了，线上需要对应的修改配置和重新加载模型

**Comment by Damon-wyg** [comment]
我用的是v1 api训练的模型，有针对v1的auc评估方法么？

**Comment by qingqing01** [comment]
v1的auc用法相同，接口是这个：https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/trainer_config_helpers/evaluators.py#L196
