### ISSUE TITLE
Design document of refactoring Paddle Paddle implementation.

### ISSUE THREAD

**Issue by reyoung** [PaddlePaddle/Paddle#2453]
There are several docs about refactoring Paddle Paddle implementation.

* [readme.md](https://github.com/PaddlePaddle/Paddle/blob/refactor_docs/doc/design/refactor_discuess/readme.md) Summarize overview and the user interfaces in C++.  How to configure a neural network and train a neural network in C++.
* [memory.md](https://github.com/PaddlePaddle/Paddle/blob/refactor_docs/doc/design/refactor_discuess/memory.md) Type of Variable memory. Maintains all variables' memory. How to implement a faster algorithm to allocate/reallocate memory.
* [variable_and_op.md](https://github.com/PaddlePaddle/Paddle/blob/refactor_docs/doc/design/refactor_discuess/variable_and_op.md) What is metadata of an op? What is an op? How to register an op?
* [kernels.md](https://github.com/PaddlePaddle/Paddle/blob/refactor_docs/doc/design/refactor_discuess/kernels.md) How to implement each op's computation kernel? Should we have a single tensor library or we could let each op's implementation use a different library?  What is the suggestion tensor library that we need to be used? Is there some common method should be shared by each kernel implementation?

* [graph.md](https://github.com/PaddlePaddle/Paddle/blob/refactor_docs/doc/design/refactor_discuess/graph.md) Given a list of op, i.e., a graph. How to convert a forward Graph to a backward Graph? How to convert a single device graph to multiple devices? How to optimize a graph, make computing in place? How to plan to recompute a tensor to save memory?

* [engine.md](https://github.com/PaddlePaddle/Paddle/blob/refactor_docs/doc/design/refactor_discuess/engine.md) Given a graph, which devices of variable could be different, how to run on each device? How to synchronize each device? How to get each variable's result immediately?

Please [Thunbs up] the comments you want to investigate or discuss.

**Comment by reyoung** [comment]
memory.md

**Comment by reyoung** [comment]
readme.md

**Comment by reyoung** [comment]
memory.md

**Comment by reyoung** [comment]
variable_and_op.md

**Comment by reyoung** [comment]
kernels.md

**Comment by reyoung** [comment]
graph.md

**Comment by reyoung** [comment]
engine.md

**Comment by wangkuiyi** [comment]
I closed this issue for the following reasons:

1. questions listed in each topic don't direct to "what is the optimal design". 
1. some questions depend on more fundamental questions. 
1. lack some questions like Tensor library

**Comment by jacquesqiao** [comment]
goto https://github.com/PaddlePaddle/Paddle/issues/2454
