### ISSUE TITLE
直接调用经典模型的问题

### ISSUE THREAD

**Issue by lao-xu** [PaddlePaddle/Paddle#24545]
1, 之前版本可以直接调用经典模型如vgg，为什么现在fluid框架不能直接调用了？
2，fluid框架下如何载入预训练的参数和模型
3，如何在代码里实现冻结微调等迁移过程，而不是直接用paddlehub之类的工具

**Comment by baiyfbupt** [comment]
1.麻烦贴一下调用的链接，如果有报错信息也贴一下报错信息方便定位问题

2.可以用load_vars 载入预训练的参数https://www.paddlepaddle.org.cn/documentation/docs/zh/api_cn/io_cn/load_vars_cn.html#load-vars
可以用load_inference_model 载入训练好的模型结构，但这种方式只能用于预测
https://www.paddlepaddle.org.cn/documentation/docs/zh/api_cn/io_cn/load_inference_model_cn.html#load-inference-model

3.可以用param_attr指定某一层的参数trainable=False，从而冻结这一层训练其它层

**Comment by lao-xu** [comment]
好的。
原先V2版本可以paddle.v2.networks.vgg_16_network
现在fluid怎么调用，必须自己定义吗

**Comment by baiyfbupt** [comment]
> 好的。
> 原先V2版本可以paddle.v2.networks.vgg_16_network
> 现在fluid怎么调用，必须自己定义吗

需要自行定义，可以参考Paddle开源的[模型库](https://github.com/PaddlePaddle)，大部分主流模型的实现都有

**Comment by lao-xu** [comment]
将来的版本是会支持直接调用，还是只支持自定义了？自定义是发展趋势吗

**Comment by baiyfbupt** [comment]
未来也是只支持自定义了，框架内部不会集成经典模型，如果有模型需求请关注我们的模型库~

**Comment by lao-xu** [comment]
好的，支持这么做。就是模型库里静态图比较全，动态图太少
