### ISSUE TITLE
Use float constant for tensorrt::plugin::glue_kernel instead of double

### ISSUE THREAD

**Issue by zlsh80826** [PaddlePaddle/Paddle#24543]
Use 1.0f, 0.5f instead of 1.0, 0.5 in paddle::inference::tensorrt::plugin::glue_kernel
1.0 is double type which will decrease the performance when using trt inference.

**Comment by NHZlX** [comment]
您好 请问您现在是在用trt inference做bert 预测么

**Comment by NHZlX** [comment]
The cuda built-in erf is a double operation, it's very slow. So when using Bert fp32 inference, we suggest not to enable TRT. When using fp16 inferenece, it is recommended to turn on TRT.

**Comment by jeng1220** [comment]
@NHZlX ,
No, he was helping me to verify ERNIE performance. @zlsh80826 is a NVIDIA guy too.

**Comment by NHZlX** [comment]
Ok, but there is no gelu operation in ernie.

**Comment by jeng1220** [comment]
@zlsh80826 ,
Could you clarify that which model has this problem?

**Comment by jeng1220** [comment]
@NHZlX ,
I check the code. The key line is
```c++
const T cdf = 0.5 * (1.0 + erf(in * 0.5 * a));
```
CUDA did provide the single precision version of `erf`, called `erff`. You can refer [here](https://docs.nvidia.com/cuda/cuda-math-api/group__CUDA__MATH__SINGLE.html#group__CUDA__MATH__SINGLE_1g3b8115ff34a107f4608152fd943dbf81).

I think the better way is using template specialization.

**Comment by zlsh80826** [comment]
We are using ERNIE-2.0 model, and the configuration for English dataset in ERNIE involves gelu operation [configuration](https://github.com/PaddlePaddle/ERNIE/blob/0a9ad5114764cbbc31558db5ea34edd10e97a132/script/en_glue/ernie_base/ernie_config.json#L3)
More specifically, we hit this [line](https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/fluid/inference/tensorrt/plugin/gelu_op_plugin.cu#L66) when inferencing Paddle-ERNIE base-2.0 model

**Comment by jeng1220** [comment]
@NHZlX ,
zlsh has submitted the PR #24544 . Please take a look.

**Comment by NHZlX** [comment]
OK
