### ISSUE TITLE
实现mutitask的多分类任务报错

### ISSUE THREAD

**Issue by caijie12138** [PaddlePaddle/Paddle#24569]
为使您的问题得到快速解决，在建立Issues前，请您先通过如下方式搜索是否有相似问题:【搜索issue关键字】【使用labels筛选】【官方文档】

如果您没有查询到相似问题，为快速解决您的提问，建立issue时请提供如下细节信息：
- 标题：简洁、精准概括您的问题，例如“Insufficient Memory xxx" ”
- 版本、环境信息：
    1）PaddlePaddle版本：1.7.2
    2）CPU：
    3）GPU：TITAN Xp ;CUDA Version 10.0.130;
                     #define CUDNN_MAJOR 7
                     #define CUDNN_MINOR 6
                     #define CUDNN_PATCHLEVEL 4
    4）系统环境：Linux version 4.15.0-65-generic (buildd@lgw01-amd64-006) (gcc version 7.4.0 (Ubuntu 7.4.0-1ubuntu1~18.04.1)) Python 3.7.3
- 训练信息
    1）单机单卡
    2）12196MiB
    3）Operator信息
- 复现信息：如为报错，请给出复现环境、复现步骤
- 问题描述：我希望能实现一个multitask的多分类器 按照tutorial里的情感分析的例子来修改代码：

报错信息如下：
Traceback (most recent call last):
  File "goal_planning.py", line 24, in <module>
    main(args,word_dict,train_data[1:],dev_data[1:])
  File "/home/jiabin/caijie/Dialog_recommendation/goal_multitask/train_cnn_classifier.py", line 309, in main
    train(args, params_dirname, word_dict, train_data, test_data)
  File "/home/jiabin/caijie/Dialog_recommendation/goal_multitask/train_cnn_classifier.py", line 162, in train
    prediction_type = inference_program_type(word_dict,main_program_type,star_program)
  File "/home/jiabin/caijie/Dialog_recommendation/goal_multitask/train_cnn_classifier.py", line 81, in inference_program_type
    net = convolution_net_for_type(data, dict_dim, CLASS_TYPE_DIM, EMB_DIM, HID_DIM)
  File "/home/jiabin/caijie/Dialog_recommendation/goal_multitask/train_cnn_classifier.py", line 34, in convolution_net_for_type
    emb = fluid.embedding(input=data, size=[input_dim, emb_dim], is_sparse=True)
  File "/home/jiabin/anaconda3/lib/python3.7/site-packages/paddle/fluid/input.py", line 256, in embedding
    'padding_idx': padding_idx
  File "/home/jiabin/anaconda3/lib/python3.7/site-packages/paddle/fluid/layer_helper.py", line 43, in append_op
    return self.main_program.current_block().append_op(*args, **kwargs)
  File "/home/jiabin/anaconda3/lib/python3.7/site-packages/paddle/fluid/framework.py", line 2525, in append_op
    attrs=kwargs.get("attrs", None))
  File "/home/jiabin/anaconda3/lib/python3.7/site-packages/paddle/fluid/framework.py", line 1880, in __init__
    self.desc.infer_shape(self.block.desc)
paddle.fluid.core_avx.EnforceNotMet:

--------------------------------------------
C++ Call Stacks (More useful to developers):
--------------------------------------------
0   std::string paddle::platform::GetTraceBackString<std::string const&>(std::string const&, char const*, int)
1   paddle::platform::EnforceNotMet::EnforceNotMet(std::string const&, char const*, int)
2   paddle::operators::LookupTableV2Op::InferShape(paddle::framework::InferShapeContext*) const
3   paddle::framework::OpDesc::InferShape(paddle::framework::BlockDesc const&) const

------------------------------------------
Python Call Stacks (More useful to users):
------------------------------------------
  File "/home/jiabin/anaconda3/lib/python3.7/site-packages/paddle/fluid/framework.py", line 2525, in append_op
    attrs=kwargs.get("attrs", None))
  File "/home/jiabin/anaconda3/lib/python3.7/site-packages/paddle/fluid/layer_helper.py", line 43, in append_op
    return self.main_program.current_block().append_op(*args, **kwargs)
  File "/home/jiabin/anaconda3/lib/python3.7/site-packages/paddle/fluid/input.py", line 256, in embedding
    'padding_idx': padding_idx
  File "/home/jiabin/caijie/Dialog_recommendation/goal_multitask/train_cnn_classifier.py", line 34, in convolution_net_for_type
    emb = fluid.embedding(input=data, size=[input_dim, emb_dim], is_sparse=True)
  File "/home/jiabin/caijie/Dialog_recommendation/goal_multitask/train_cnn_classifier.py", line 81, in inference_program_type
    net = convolution_net_for_type(data, dict_dim, CLASS_TYPE_DIM, EMB_DIM, HID_DIM)
  File "/home/jiabin/caijie/Dialog_recommendation/goal_multitask/train_cnn_classifier.py", line 162, in train
    prediction_type = inference_program_type(word_dict,main_program_type,star_program)
  File "/home/jiabin/caijie/Dialog_recommendation/goal_multitask/train_cnn_classifier.py", line 309, in main
    train(args, params_dirname, word_dict, train_data, test_data)
  File "goal_planning.py", line 24, in <module>
    main(args,word_dict,train_data[1:],dev_data[1:])

----------------------
Error Message Summary:
----------------------
Error: Input(Ids) of LookupTableV2Op should not be null.
  [Hint: Expected ctx->HasInput("Ids") == true, but received ctx->HasInput("Ids"):0 != true:1.] at (/paddle/paddle/fluid/operators/lookup_table_v2_op.cc:33)
  [operator < lookup_table_v2 > error]

代码片段：
def inference_program_topic(word_dict, main_program, startup_program):
    dict_dim = len(word_dict)
    with fluid.program_guard(main_program, startup_program):
        data = fluid.data(name="words_topic", shape=[None], dtype="int64", lod_level=1)
    net = convolution_net_for_type(data, dict_dim, CLASS_TOPIC_DIM, EMB_DIM, HID_DIM)
    return net

def inference_program_type(word_dict,main_program, startup_program):
    dict_dim = len(word_dict)
    with fluid.program_guard(main_program, startup_program):
        data = fluid.data(name="words_type", shape=[None], dtype="int64", lod_level=1)
    net = convolution_net_for_type(data, dict_dim, CLASS_TYPE_DIM, EMB_DIM, HID_DIM)
    return net
def train_program_topic(prediction,main_program, startup_program):
    with fluid.program_guard(main_program, startup_program):
        label = fluid.data(name="label_topic", shape=[None, 1], dtype="int64")
    cost = fluid.layers.cross_entropy(input=prediction, label=label)
    avg_cost = fluid.layers.mean(cost)
    accuracy = fluid.layers.accuracy(input=prediction, label=label)
    return [avg_cost, accuracy]

def train_program_type(prediction,main_program, startup_program):
    with fluid.program_guard(main_program, startup_program):
        label = fluid.data(name="label_type", shape=[None, 1], dtype="int64")
    cost = fluid.layers.cross_entropy(input=prediction, label=label)
    avg_cost = fluid.layers.mean(cost)
    accuracy = fluid.layers.accuracy(input=prediction, label=label)
    return [avg_cost, accuracy]

Thank you for contributing to PaddlePaddle.
Before submitting the issue, you could search issue in the github in case that there was a similar issue submitted or resolved before.
If there is no solution,please make sure that this is a training issue including the following details:
**System information**
-PaddlePaddle version （eg.1.1）or CommitID
-CPU: including CPUMKL/OpenBlas/MKLDNN version
-GPU: including CUDA/CUDNN version
-OS Platform (eg.Mac OS 10.14)
-Other imformation: Distriuted training/informantion of operator/
Graphics card storage
**To Reproduce**
Steps to reproduce the behavior
**Describe your current behavior**
**Code to reproduce the issue**
**Other info / logs**

**Comment by iclementine** [comment]
你是参考这个教程 https://www.paddlepaddle.org.cn/tutorials/projectdetail/445594 吗？
以及是否可以把必要的 python 文件发送给我们用于调试？

**Comment by caijie12138** [comment]
对就是参考的这个教程

[归档.zip](https://github.com/PaddlePaddle/Paddle/files/4632633/default.zip)
代码在这个zip里面

**Comment by iclementine** [comment]
> 对就是参考的这个教程
> 
> [归档.zip](https://github.com/PaddlePaddle/Paddle/files/4632633/default.zip)
> 代码在这个zip里面

谢谢反馈，我们正在调试。

**Comment by iclementine** [comment]
因为代码缺少一些部分，不能直接运行

```text
Traceback (most recent call last):
  File "goal_planning.py", line 3, in <module>
    from data_preprocessor import prepare_data
ModuleNotFoundError: No module named 'data_preprocessor'
```

所以要不请你打印一下这些变量的  type 以及 shape
<img width="748" alt="图片" src="https://user-images.githubusercontent.com/16222986/82172405-a378b980-98fc-11ea-9d18-eec3c5a4e970.png">

其中的 data 的 type 和 shape. 因为这里显示的是 LooupTableV2 op 没有接收到输入，可能是 `fluid.embedding` 的输入出了什么问题。

**Comment by caijie12138** [comment]
不好意思 应该是数据没传上来的原因

[goal_multitask.zip](https://github.com/PaddlePaddle/Paddle/files/4642177/goal_multitask.zip)

data的type是：<class 'paddle.fluid.framework.Variable'>
data的shape是：
<img width="968" alt="截屏2020-05-18 13 38 35" src="https://user-images.githubusercontent.com/18359811/82177693-e17dd980-990c-11ea-8d6b-fbd969f1140b.png">

**Comment by caijie12138** [comment]
<img width="419" alt="截屏2020-05-18 13 44 46" src="https://user-images.githubusercontent.com/18359811/82178095-bf388b80-990d-11ea-8035-918696bf4e84.png">
还有一个问题就是 我如果把上图中的fluid.default_main_program()替换为fluid.Program()就会出现 LooupTableV2 op 没有接收到输入这个错误 如果我按照上图的代码来运行的话，报的错是下面这个：
<img width="933" alt="截屏2020-05-18 13 46 46" src="https://user-images.githubusercontent.com/18359811/82178204-06bf1780-990e-11ea-9255-48257c7d28a6.png">

**Comment by iclementine** [comment]
大概找到了问题：

你目前所使用的代码中：使用了多个 program 也使用了多个 executor。我们一般情况下不会这么做，概念上 program 是一个容器，当调用 fluid.embedding 之类的函数时，它们会往这个容器上写入一些东西，也就是静态计算图。然后我们通过 executor 来执行 program。当我们需要控制不同的功能，比如返回 loss1， 或者 返回 loss2 的时候，我们通过 executor.run() 中的 fetch_list 参数来控制。

所以 Program 是计算图组建和执行上单位，而不是功能上的模块。类似 fluid.embedding 的函数具体往哪个容器上写入计算图呢？它们并没有指定自己的目标容器，而是通过上下文管理器来实现。比如这个函数的定义，调用它，就往目标容器上写入一部分计算图：

<img width="732" alt="图片" src="https://user-images.githubusercontent.com/16222986/82181898-f7dc6300-9915-11ea-8fd4-91fb8c00ae99.png">

但是目标容器取决于调用它的时候的上下文：
<img width="731" alt="图片" src="https://user-images.githubusercontent.com/16222986/82182028-2e19e280-9916-11ea-8829-4e540ba20ba2.png">

但是如果 net =... 那一行退一格缩进，就有可能导致 fluid.data 那部分的计算图和 convolution_net_for_type 那部分的计算图写入到不同的容器上。这个需要你做一些修改以确保计算图如你所愿地放到合适的容器上。

因为你的程序中有一个将位于两个不同 program 上的 Variable 相加的操作，这个操作本身可能存在问题。因为它们来自不同的 program, 而且有可能“相加”被添加到另一个 Program 上。(如不指定则使用 paddle 默认的 startup_program 和 main_program).

<img width="670" alt="图片" src="https://user-images.githubusercontent.com/16222986/82183402-7afeb880-9918-11ea-8f03-6131e0fef319.png">

我们一般只用两个 program, 一个用于 train, 另一个用于 start. 还有一个是 startup_program 这里面包含和参数初始化相关的内容。（所以我的建议也是这么做 Program 是整个的计算图，功能模块则由自己定义的函数来实现模块化。）

另外。因为 1.8 版本之前，Program 是会完完整整地执行的。也就是说架设你把两个不相关的功能放到了同一个 program 里面，

```text
(program
    (part-1 ....)
    (part-2 ....))
```

那么这两个部分也都会被计算，如果你只是 feed 了 part-1 需要的输入，那么 part-2 的部分就会报错，认为你没有提供输入。反之亦然。因为 program 就是一种完整执行的东西。你的程序中就包含这样的结构和运行方式。

<img width="602" alt="图片" src="https://user-images.githubusercontent.com/16222986/82187182-9b317600-991e-11ea-98b8-82939ee22554.png">


在 1.8 之前需要做到这个事情，你可能需要使用 fluid.layers.switch 来切换，使得网络只计算某个分支。就跟平时写 if-else 一样。

在 paddle 1.8 中，我们提供了运行时图剪枝的功能。exe.run()中新加了一个参数 use_prune=False, 只要把它设置为 True, 那么就会根据 fetch_list 中的节点进行反溯，只有有需要的节点才会被使用到。但是值得注意的是 minimize() 添加反向计算的部分也是图的一部分。因为开启了剪枝，则也需要把反向的部分加入 fetch_list, 反向才会被执行。（与此相应地，1.8 版本 optimizer.minimize 是有返回值的，它返回一个 Tuple，（optimize_ops, param_grad））.

https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api_cn/executor_cn/Executor_cn.html

<img width="871" alt="图片" src="https://user-images.githubusercontent.com/16222986/82189297-ba7dd280-9921-11ea-87b0-fc0282b89f58.png">


所以建议是升级到 Paddle 1.8 版本。

另外关于使用 paddle 进行多任务学习也推荐参考和使用 PALM.

**Comment by caijie12138** [comment]
感谢耐心回答
