### ISSUE TITLE
不能和lightgbm兼容安装，scipy，和requests的版本要求不同。

### ISSUE THREAD

**Issue by txt2txt** [PaddlePaddle/Paddle#24570]
在aistudio上，paddlepaddle 1.7.1，python3.7，同时安装lightgbm不能通过。
提示，scipy的版本不兼容，
然后降档paddlepaddle1.4.1，然后是requests版本2.9.2，不能和tensoboard兼容。
是否可以解决，还是等着lightgbm自己升级。

**Comment by iclementine** [comment]
Paddle 目前做了 scipy 版本的限制。我问一下负责的同学

<img width="382" alt="图片" src="https://user-images.githubusercontent.com/16222986/82016679-24914000-96b4-11ea-8f8b-1dfdeecb9872.png">

一个可能可行的方案是先装 paddle 再装 lightgbm, lightgbm 可能会重装 scipy 但是，paddle 可能还是可以兼容的。

**Comment by JepsonWong** [comment]
您好，对于scipy等类似包的限制这个估计需要后续梳理下，后续计划要去除这种包的限制。后续可以按照 @iclementine 的方法试试。

**Comment by tianshuo78520a** [comment]
目前最新的Paddle已经解决了这个问题，您可以使用最新的paddle解决这个问题
![image](https://user-images.githubusercontent.com/29832297/87124653-c2237d00-c2bb-11ea-98c8-7f016bc27e37.png)
