### ISSUE TITLE
Paddle Inference API进行预测，如何异步读取数据

### ISSUE THREAD

**Issue by HaiLongEmb** [PaddlePaddle/Paddle#24577]
PaddlePaddle版本：1.7.1
在windows上使用GPU进行预测，我想实现DataLoader类似的异步数据读取，请问有什么方法？
目前Paddle Inference中PythonAPI提供的都是同步送数据的方式，我的场景是这样，一个线程一直在通过predictor.zero_copy_run()进行预测，另一个线程一直在获取摄像头数据，并进行图片预处理然后送给检测线程。有什么办法实现异步reader送数据。

**Comment by iclementine** [comment]
Paddle Inference 只要能接受数据就可以，数据异步加载的实行需要用户自己实现。

**Comment by HaiLongEmb** [comment]
@iclementine 知道了，最后一个问题，如果想把图像预处理也加入模型让GPU处理有什么办法，是在模型的输入层前加np的操作吗？静态图这样不行吧

**Comment by iclementine** [comment]
1. 如果把图像预处理也加入模型，那应该就需要把那部分写入模型定义里。让模型接受更原始的输入；（一般情况下我们可能不会这么做）
2. 或者如果只是希望用 GPU 处理数据，可以把预处理放在数据处理上而不是模型中。可以参考 使用 DALI 或者 cupy 之类的工具。（不过这样子处理后得到的应该是在 GPU 上的数据，不再是 numpy.ndarray 了）

**Comment by HaiLongEmb** [comment]
@iclementine 请教一个问题，使用paddle训练好的模型，直接使用预测模式与Paddle Inference性能上哪个更快，我理解是Paddle Inference应该更快，但我使用eval进行测试帧率比Paddle Inference要高，这是给数据方式不同造成的吗？

**Comment by iclementine** [comment]
如果使用同步数据加载方式，可能会因为需要同步数据处理而被拖慢速度。而异步加载的话也需要数据加载本身比较快，才不会成为模型运行速度的瓶颈。

> @iclementine 请教一个问题，使用paddle训练好的模型，直接使用预测模式与Paddle Inference性能上哪个更快，我理解是Paddle Inference应该更快，但我使用eval进行测试帧率比Paddle Inference要高，这是给数据方式不同造成的吗？
