### ISSUE TITLE
Paddle如何查看一个训练模型的op调用顺序

### ISSUE THREAD

**Issue by dashulu** [PaddlePaddle/Paddle#24573]
定义好一个模型后，paddle进行训练时后端会生成一个graph，如何可视化的看这个graph？

**Comment by dashulu** [comment]
比如预测的时候可以看到
![image](https://user-images.githubusercontent.com/4484303/82006648-de7bb280-969a-11ea-8346-9812d39875a6.png)， 有什么工具能一起看到反向的op顺序吗？

**Comment by iclementine** [comment]
用 save_inference model 并且把参数的梯度作为 target_var 可以使得网络不被裁剪，这样可以查看网络的结构。

https://www.paddlepaddle.org.cn/documentation/docs/zh/api_cn/io_cn/save_inference_model_cn.html#save-inference-model

对于直接将 program_desc 可视化，目前有一个基于 graphviz 的方案但是有些问题。

https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/fluid/net_drawer.py
