### ISSUE TITLE
 'Parameter' object has no attribute 'gradient_clip_attr'

### ISSUE THREAD

**Issue by NULL-JC** [PaddlePaddle/Paddle#24578]
Traceback (most recent call last):
  File "F:/学习资料/计算机/大二/下/人工智能/Text_Analysis/loadModule.py", line 70, in <module>
    metrics_choices=["f1"])
  File "E:\software\program\Python37\lib\site-packages\paddlehub\finetune\task\classifier_task.py", line 179, in __init__
    metrics_choices=metrics_choices)
  File "E:\software\program\Python37\lib\site-packages\paddlehub\finetune\task\classifier_task.py", line 49, in __init__
    metrics_choices=metrics_choices)
  File "E:\software\program\Python37\lib\site-packages\paddlehub\finetune\task\base_task.py", line 299, in __init__
    main_program, for_test=False)
  File "E:\software\program\Python37\lib\site-packages\paddlehub\common\paddle_helper.py", line 274, in clone_program
    dest_program.global_block())
  File "E:\software\program\Python37\lib\site-packages\paddlehub\common\paddle_helper.py", line 147, in _copy_vars_and_ops_in_blocks
    var_info = copy.deepcopy(get_variable_info(var))
  File "E:\software\program\Python37\lib\site-packages\paddlehub\common\paddle_helper.py", line 65, in get_variable_info
    var_info['gradient_clip_attr'] = var.gradient_clip_attr
AttributeError: 'Parameter' object has no attribute 'gradient_clip_attr'

如果您没有查询到相似问题，为快速解决您的提问，建立issue时请提供如下细节信息：
- 标题：简洁、精准概括您的问题，例如“Insufficient Memory xxx" ”
- 版本、环境信息：
    1）PaddlePaddle版本：1.8.0
    2）CPU：i7 7700
    4）系统环境：win10
- 训练信息
    1）单机，单卡

**Comment by NULL-JC** [comment]
# from myDataset import MyDataset
import paddlehub as hub
from paddlehub.dataset.base_nlp_dataset import BaseNLPDataset

class MyDataset(BaseNLPDataset):
    """DemoDataset"""
    def __init__(self):
        # 数据集存放位置
        self.dataset_dir = "data"
        super(MyDataset, self).__init__(
            base_path=self.dataset_dir,
            train_file="train.txt",
            dev_file="valid.txt",
            test_file="valid.txt",
            train_file_with_header=False,
            dev_file_with_header=False,
            test_file_with_header=False,
            # 数据集类别集合
            label_list=["-1", "0", "1"])


dataset=MyDataset()


module = hub.Module(name="ernie")

# 构建Reader
reader = hub.reader.ClassifyReader(
    dataset=dataset,
    vocab_path=module.get_vocab_path(),
    sp_model_path=module.get_spm_path(),
    word_dict_path=module.get_word_dict_path(),
    max_seq_len=128)

# finetune策略
strategy = hub.AdamWeightDecayStrategy(
    weight_decay=0.01,
    warmup_proportion=0.1,
    learning_rate=5e-5)

# 运行配置
config = hub.RunConfig(
    use_cuda=True,
    num_epoch=1,
    checkpoint_dir="model",
    batch_size=32,
    eval_interval=100,
    strategy=strategy)

# Finetune Task
inputs, outputs, program = module.context(
    trainable=True, max_seq_len=128)

# Use "pooled_output" for classification tasks on an entire sentence.
pooled_output = outputs["pooled_output"]

feed_list = [
    inputs["input_ids"].name,
    inputs["position_ids"].name,
    inputs["segment_ids"].name,
    inputs["input_mask"].name,
]

cls_task = hub.TextClassifierTask(
        data_reader=reader,
        feature=pooled_output,
        feed_list=feed_list,
        num_classes=dataset.num_labels,
        config=config,
        metrics_choices=["f1"])

# finetune
run_states = cls_task.finetune_and_eval()

**Comment by iclementine** [comment]
请检查一下 paddlehub 的版本。
目前 paddlehub 还不支持 paddle 1.8 版本，你可以先用 paddle 1.7

paddlehub 1.7 很快就会发布，兼容 paddle 1.8.
