### ISSUE TITLE
It would be better to update documents timely

### ISSUE THREAD

**Issue by kuke** [PaddlePaddle/Paddle#2458]
Paddle keeps evolving everyday, but the documents are out of date, especially the installation guide and  tutorials for new beginners. They are easy to be confused by the difference between code and documents, and keep asking related questions.

So I suggest that we can assign someone to take the responsibility for updating documents timely, to catch up with the changes in Paddle.

**Comment by Yancey1989** [comment]
Yep @kuke, thanks for your suggestion, updating the document timely is very important,  we have a project to enhancement the documents: https://github.com/PaddlePaddle/Paddle/projects/9, and @luotao1 has done a lot of work about this.

**Comment by luotao1** [comment]
@kuke The timely updated document is in http://www.paddlepaddle.org/develop/doc/ and http://www.paddlepaddle.org/develop/doc_cn. They are consistent with the develop branch.

**Comment by kuke** [comment]
@luotao1 Thanks! Really it is hard for you to track every update. Yesterday someone asked question about the GO compiler in installation. Seems that the document hasn't included any guidelines about the setup.
