### ISSUE TITLE
关于协同合作的一些问题

### ISSUE THREAD

**Issue by daniao2017** [PaddlePaddle/Paddle#24587]
请问一下百度的飞浆支持**协同办公吗**？
很好奇，参加了百度的某个比赛，和队员组好队，
但是数据与代码在AL studio上如何分享啊？？？
请问有权限设置相关设置吗？？？
我这边好像只看到notebook能设置公开与私有两种状态，
这种情况下如何协同办公，有权限准入机制吗？？？
**期望大佬的解答**

**Comment by iclementine** [comment]
目前该功能尚未开发。

**Comment by daniao2017** [comment]
> 
> 
> 目前该功能尚未开发。

好的，感谢大佬的回复，期待这一功能的实现
