### ISSUE TITLE
Ubuntu18上安装paddlepaddle-gpu报错

### ISSUE THREAD

**Issue by zhengzihe** [PaddlePaddle/Paddle#24597]
请问一下在Ubuntu18上安装paddlepaddle-gpu真是报上面的错误怎么解决  cuda版本10.0  cudnn7.6.5  LD_LIBRARY_PATH环境变量也设置了

![246563518433956890](https://user-images.githubusercontent.com/58216756/82112239-adc07980-977d-11ea-9bb8-5984c5da25be.png)
![736229024585455196](https://user-images.githubusercontent.com/58216756/82112240-ae591000-977d-11ea-9eb6-b5d53f49f0d6.jpg)

**Comment by slf12** [comment]
可以 ls -l /usr/local/cuda-10.0/lib64 看下有没有libcudnn.so
