### ISSUE TITLE
Paddle will hang using multiply GPU when cuda driver is 367.35

### ISSUE THREAD

**Issue by reyoung** [PaddlePaddle/Paddle#246]
Issue from gitter chat.

When using driver 367.35 and `Titan X` GPU, Paddle will hang when merging gradient, and the [NVIDIA nccl](https://github.com/NVIDIA/nccl/) benchmarks will hang too.

It seems that the driver problems, and same problem occurred in Torch/NCCL(https://github.com/NVIDIA/nccl/issues/39)

**Comment by pineking** [comment]
补充下平台信息：
* CoreOS 系统
* 单机 8卡 GPU TITAN X
* 实验 1022.2.0/367.44，1022.2.0/367.57，1068.9.0/367.35 组合，均有相同 hang 现象

定位 hang 代码：
https://github.com/baidu/Paddle/blob/master/paddle/trainer/TrainerInternal.cpp#L117

**Comment by reyoung** [comment]
The memory copy between two GPU card is the hang position.

**Comment by hedaoyuan** [comment]
This is a third party problem, fix the method see the link in the first comment. In addition, you can also update the driver to repair the running problem.
