### ISSUE TITLE
情感分析-使用文档错误

### ISSUE THREAD

**Issue by shaunhurryup** [PaddlePaddle/Paddle#24605]
CPU  8
RAM  32GB
GPU  v100
显存  16GB
磁盘  100GB
Python版本  python3.7
框架版本  PaddlePaddle 1.7.1

按照[文档](https://www.paddlepaddle.org.cn/documentation/docs/zh/user_guides/nlp_case/understand_sentiment/README.cn.html)要求运行，最后一段代码出现问题
**ValueError: The fed Variable 'words' should have dimensions = 1, shape = (-1,), but received fed shape [-1, 1] on each device**

**Comment by shaunhurryup** [comment]
![image](https://user-images.githubusercontent.com/45918719/82149855-e9e10080-9889-11ea-98bb-a7faba25451e.png)
![image](https://user-images.githubusercontent.com/45918719/82149880-f1080e80-9889-11ea-8dc1-ae06acb05c9e.png)
我在想是不是和word_dict中键的类型为byte而不是str有关

**Comment by GT-ZhangAcer** [comment]
[情感分析reader写法](https://github.com/GT-ZhangAcer/Python3Notes/blob/master/Class_PaddlePaddle/test11_nlp_classify/infer.py)
试试这个

**Comment by GT-ZhangAcer** [comment]
-----------
求官方同学在Window下跑跑官方文档情感分析的预测部分示例：
[情感分析-使用文档](https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/user_guides/nlp_case/understand_sentiment/README.cn.html)
这个示例在较新版本的PaddlePaddle文档中使用的是`fluid.data`接口，会对输入的数据类型进行检查。
然而大部分刚入门的开发者并不了解怎样转换数据类型，Window下默认是int32，需要去转换为int64才能正确执行。报错样例如下：
![图片](https://user-images.githubusercontent.com/46156734/82178187-feff7300-990d-11ea-91b1-35a7c4d218e9.png)

还有一个建议，入门文档尽量不要使用冷门的API
```
reviews_str = [
    'read the book forget the movie', 'this is a great movie', 'this is very bad'
]
reviews = [c.split() for c in reviews_str]

UNK = word_dict['<unk>']
lod = []
for c in reviews:
    lod.append([word_dict.get(words, UNK) for words in c])

base_shape = [[len(c) for c in lod]]

tensor_words = fluid.create_lod_tensor(lod, base_shape, place)
```
日常开发时` fluid.create_lod_tensor`用的次数并不多，不如将推理时的数据准备与训练保持一致。即训练时制作reader，推理时也让开发者模仿，这样入门开发者在自定义数据集时可能会更容易做数据准备。

### 推理时使用reader
```
reviews_str = [
    'read the book forget the movie', 'this is a great movie', 'this is very bad'
]
reviews = [c.split() for c in reviews_str]

word_dict = paddle.dataset.imdb.word_dict()

UNK = word_dict['<unk>']

def reader():
    for sample in reviews:
        sample_data = [word_dict.get(word, UNK) for word in sample]
        sample_data = np.array(sample_data, dtype="int64").reshape(1, -1)
        yield sample_data
```
[查看完整示例](https://github.com/GT-ZhangAcer/Python3Notes/blob/master/Class_PaddlePaddle/test11_nlp_classify/infer.py)

**Comment by shaunhurryup** [comment]
在变量word_dict中，键的类型都为bytes，他的输出大概是这样子的
```python
print(dict_word)
# {b'the': 0, b'and': 1, b'a': 2, b'of': 3, ...}
```

因此通过 `sample_data = [word_dict.get(word, UNK) for word in sample]` 生成的LodTensor值都是一样的
```python
print(sample_data)
# [[5146 5146 5146 5146 5146 5146]]
# [[5146 5146 5146 5146 5146]]
# [[5146 5146 5146 5146]]
```

我把bytes类型的键转换成str后，sample_data的内容符合原来字典的映射关系
```python
# 修改字典bytes类的键
new_dict = {}
for k, v in word_dict.items():
    if isinstance(k, bytes):
        k = k.decode()
        new_dict[k] = v
    else:
        pass

def reader():
    for sample in reviews:
        sample_data = [new_dict.get(word, UNK) for word in sample]
        sample_data = np.array(sample_data, dtype="int64").reshape(1, -1)
        print(sample_data)
        yield sample_data

# [[325   0 276 818   0  16]]
# [[ 9  5  2 78 16]]
# [[ 9  5 51 81]]
```

原来的准确率也存在问题，将word_dict字典的键类型调整后准确率正常，**在文档中的word_dict是不是存在问题呢？**
开始：
Predict probability of  **0.55312973  to be positive** and  0.4468703  to be negative for review ' read the book forget the movie '
Predict probability of  **0.5464905  to be positive** and  0.45350957  to be negative for review ' this is a great movie '
Predict probability of  **0.53886133  to be positive** and  0.46113867  to be negative for review ' this is very bad '

后来：
Predict probability of  **0.488472  to be positive** and  0.511528  to be negative for review ' read the book forget the movie '
Predict probability of  **0.6571248  to be positive** and  0.3428752  to be negative for review ' this is a great movie '
Predict probability of  **0.4568676  to be positive** and  0.5431325  to be negative for review ' this is very bad '

# 修改后的代码
```python
import paddle
import paddle.fluid as fluid
import numpy as np

place = fluid.CUDAPlace(0)
exe = fluid.Executor(place)

reviews_str = [
    'read the book forget the movie', 'this is a great movie', 'this is very bad'
]
reviews = [c.split() for c in reviews_str]

word_dict = paddle.dataset.imdb.word_dict()

UNK = word_dict['<unk>']

# 修改字典bytes类的键
new_dict = {}
for k, v in word_dict.items():
    if isinstance(k, bytes):
        k = k.decode()
        new_dict[k] = v
    else:
        pass

def reader():
    for sample in reviews:
        sample_data = [new_dict.get(word, UNK) for word in sample]
        sample_data = np.array(sample_data, dtype="int64").reshape(1, -1)
        print(sample_data)
        yield sample_data


params_dirname = "./understand_sentiment_conv.inference.model"
[inferencer, feed_target_names, fetch_targets] = fluid.io.load_inference_model(params_dirname, exe)

batch_reader = fluid.io.batch(reader=reader, batch_size=128)
feeder = fluid.DataFeeder(place=place, feed_list=feed_target_names, program=inferencer)

assert feed_target_names[0] == "words"

for data in batch_reader():
    results = exe.run(inferencer,
                      feed=feeder.feed(data),
                      fetch_list=fetch_targets,
                      return_numpy=False)
    np_data = np.array(results[0])
    for i, r in enumerate(np_data):
        print("Predict probability of ", r[0], " to be positive and ", r[1],
              " to be negative for review \'", reviews_str[i], "\'")
```

**Comment by xixiaoyao** [comment]
辛苦 @lfchener  帮忙看一下

**Comment by lfchener** [comment]
@shaoshenchen @GT-ZhangAcer 
该问题已提 pr 修复，感谢反馈！
