### ISSUE TITLE
Whether can remove caffeMode.

### ISSUE THREAD

**Issue by hedaoyuan** [PaddlePaddle/Paddle#2460]
In Paddle's code, `caffeMode` is a value of type bool ([ConvBaseLayer::caffeMode_](https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/gserver/layers/ConvBaseLayer.h#L78) and [caffe_mode](https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/trainer/config_parser.py#L860)). Set to true or false, will affect the output size of the convolution calculation ([outputSize](https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/math/MathUtils.cpp#L71) and [cnn_output_size](https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/trainer/config_parser.py#L1131)).

The calculation result when caffeMode is set to false or true is [as follows](https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/math/MathUtils.h#L48).
```
/**
 * Calculate output size based on caffeMode_.
 * - input(+padding): 0123456789
 * - imageSize(+padding) = 10;
 * - filterSize = 3;
 * - stride = 2;
 * - caffeMode is true:
     - output: (012), (234), (456), (678)
     - outputSize = 4;
 * - caffeMode is false:
 *   - output: (012), (234), (456), (678), (9)
 *   - outputSize = 5;
 */
int outputSize(int imageSize, int filterSize, int padding, int stride, bool caffeMode) {
  int outputSize;
  if (!caffeMode) {
    outputSize = (imageSize - filterSize + 2 * padding + stride - 1) / stride + 1;
  } else {
    outputSize = (imageSize - filterSize + 2 * padding) / stride + 1;
  }
  return outputSize;
}
```

1. The two modes are not the same in some cases.
2. `caffeMode = true` refers to the calculation method in caffe. This method is also used in cudnn. So, if the convolution layer is configured as cudnn, you need to ensure that `caffe_mode = True`.
3. If the `padding` is replaced with `paddingLeft` and `paddingRight` two arguments. In `caffeMode = true` formula, modify the size of the padding can also achieve `caffeMode = false` results.

So, can we remove this configuration argument?

**Comment by qingqing01** [comment]
I think we can remove this argument and keep a standard format, the `caffe_mode=True` format.

**Comment by hedaoyuan** [comment]
The code has been refactored.
