### ISSUE TITLE
hash函数使用出错

### ISSUE THREAD

**Issue by duanfz2314** [PaddlePaddle/Paddle#24612]
官方代码：
import paddle.fluid as fluid
import numpy as np
place = fluid.core.CPUPlace()
# 构建网络
x = fluid.layers.data(name="x", shape=[1], dtype="int32", lod_level=1)
res = fluid.layers.hash(name="res",input=x, hash_size=1000, num_hash=4)
# 创建CPU执行器
exe = fluid.Executor(place)
exe.run(fluid.default_startup_program())
in1 = np.array([[1,2],[3,4]]).astype("int32")
print(in1)
x_i = fluid.core.LoDTensor()
x_i.set(in1,place)
x_i.set_recursive_sequence_lengths([[0,2]])
res = exe.run(fluid.default_main_program(), feed={'x':x_i}, fetch_list=[res], return_numpy=False)
print(np.array(res[0]))
报错：
InvalidArgumentError: The Tensor in the hash Op's Input Variable X(creative_id) is not initialized.
  [Hint: Expected t->IsInitialized() == true, but received t->IsInitialized():0 != true:1.] at (/paddle/paddle/fluid/framework/operator.cc:1264)
  [operator < hash > error]

**Comment by huangjun12** [comment]
我这边试了下没问题的，请问你用的paddle是哪个版本啊

**Comment by duanfz2314** [comment]
我之前在aistudio上尝试的不能使用，现在可以了。请问一下，hash的gpu版本是没有实现吗，我在源码中也没有查到，使用cpu太慢了，还有其他方式可以使用gpu版本的hash layer吗？




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"huangjun12"<notifications@github.com&gt;;
发送时间:&nbsp;2020年5月18日(星期一) 晚上7:15
收件人:&nbsp;"PaddlePaddle/Paddle"<Paddle@noreply.github.com&gt;;
抄送:&nbsp;"天空的颜色*^_^*"<627354011@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [PaddlePaddle/Paddle] hash函数使用出错 (#24612)





 
我这边试了下没问题的，请问你用的paddle是哪个版本啊
