### ISSUE TITLE
我使用 Paddle-Inference，当VS编译C++预测API中的多线程预测实例时，提示缺少libmklml_intel.dll

### ISSUE THREAD

**Issue by HaiLongEmb** [PaddlePaddle/Paddle#24610]
我在build目录下执行的命令是：
cmake .. -G "Visual Studio 14 2015" -A x64 -T host=x64 -DWITH_GPU=ON -DWITH_MKL=ON -DWITH_STATIC_LIB=ON -DCMAKE_BUILD_TYPE=Release -DDEMO_NAME=thread_mobilenet_test -DPADDLE_LIB="E:\deeplearning\fluid_inference_install_dir" -DMSVC_STATIC_CRT=ON -DCUDA_LIB=D:\worktool\CUDA_Development\lib\x64

用VS2015进行生成：
错误	LNK1181	无法打开输入文件“E:\deeplearning\fluid_inference_install_dir\third_party\install\mklml\lib\libmklml_intel.dll”	thread_mobilenet_test

**Comment by Shixiaowei02** [comment]
请确认下 `E:\deeplearning\fluid_inference_install_dir\third_party\install\mklml\lib\libmklml_intel.dll` 文件路径是否的确存在。如果不存在，请告诉我们在您的环境中，`libmklml_intel.dll` 正确的完整路径，以便我们排查问题。谢谢！

**Comment by HaiLongEmb** [comment]
@Shixiaowei02 你好，这个路径是有的，但libmklml_intel.dll没有，fluid_inference_install_dir我是从
cuda10.0_cudnn7_avx_mkl | fluid_inference.zip | MSVC 2015 update 3 | CMake v3.16.0 | 7.5.0 | 10.0
这下载的。这个包里确实没有libmklml_intel.dll，你可以确认一下。

**Comment by HaiLongEmb** [comment]
而且我按照说明编译 Windows 预测库，生成的fluid_inference_install_dir里面也没有libmklml_intel.dll。

**Comment by OliverLPH** [comment]
@HaiLongEmb 
看了下您的问题，应该是由于您下载的多线程预测实例是给linux用的，所以在Windows平台上编译会报错。
因为Windows平台和Linux本身有区别，所以在写cmake时需区分平台。

比如您提到的 `libmklml_intel` 这个文件，这个第三方库只在Linux上是这样命名的。但在Windows上，这个库的命名方式是不一样的，Windows上叫 `mklml.lib` 或者 `mklml.dll`。
所以构造CMakeLists.txt时，应该像下图一样改写下。
![image](https://user-images.githubusercontent.com/14963836/82280360-50b50580-99c1-11ea-95e7-6b4992e6e74e.png)

目前Paddle官网上应该是没有现成的 Windows 多线程预测的实例的，您可以参照这个文件适配下Windows平台应该就可以了。
https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/fluid/inference/api/demo_ci/CMakeLists.txt

**Comment by HaiLongEmb** [comment]
@OliverLPH 感谢你的回答，我安装提示改了一版CMakeLists.txt。但出现如下错误，
![image](https://user-images.githubusercontent.com/32731062/82412215-d8744000-9aa5-11ea-9cb3-6b7655bd128f.png)
CMakeLists.txt 修改如下：右边是修改后的
![image](https://user-images.githubusercontent.com/32731062/82412274-f5107800-9aa5-11ea-890f-46347b076523.png)

请问能再提示一下问题出在哪吗？路径都确认过，并且测试了下载的预测库和自己编译的预测库效果一样。

**Comment by OliverLPH** [comment]
@HaiLongEmb 
您这个报错看起来还是 `mklml.dll` 这个库没加载进去。

可以改成链接静态库试下
```
set(MATH_LIB ${MATH_LIB_PATH}/lib/mklml${CMAKE_STATIC_LIBRARY_SUFFIX}
${MATH_LIB_PATH}/lib/libiomp5md${CMAKE_STATIC_LIBRARY_SUFFIX}
```

**Comment by HaiLongEmb** [comment]
@OliverLPH 确实用静态库可以，而且需要修改的地方还挺多，我修改如下：
![image](https://user-images.githubusercontent.com/32731062/82519087-6e19d900-9b53-11ea-8be7-61b695b169ed.png)
![image](https://user-images.githubusercontent.com/32731062/82519102-75d97d80-9b53-11ea-9589-0db82df7f3d6.png)

请问，最后这个错误是不是这个gflags_static这个库使用有问题啊，后期paddle会推出Windows多线程的例子吗？

**Comment by OliverLPH** [comment]
@HaiLongEmb 
应该还是链接的时候有问题，可能是 gflags相关的 lib，include等路径没找到。

**Comment by molyswu** [comment]
添加gflags_nothreads.lib连接就可以了
