### ISSUE TITLE
cudaFree in free: an illegal memory access was encountered

### ISSUE THREAD

**Issue by Colorfu1** [PaddlePaddle/Paddle#24629]
模型训练过程中遇到错误，在第三个epoch的时候报错：
![error](https://user-images.githubusercontent.com/30551427/82285116-413bb980-99cd-11ea-921d-357b172a54a9.PNG)
不知道是不是空间不够，但是前两个epoch是可以正常训练的，不应该出现空间不够的情况吧

**Comment by 1024er** [comment]
您看一下训练时候的显存变化呢？

**Comment by Colorfu1** [comment]
> 您看一下训练时候的显存变化呢？

我一直拿一个窗口watch显存的占用情况，训练过程中一直没有变过，现存占比一直在10774MiB / 11439MiB。后面跑过几次，在50epoch的时候中断了，报的一样的错误。

**Comment by zhiqiu** [comment]
> > 您看一下训练时候的显存变化呢？
> 
> 我一直拿一个窗口watch显存的占用情况，训练过程中一直没有变过，现存占比一直在10774MiB / 11439MiB。后面跑过几次，在50epoch的时候中断了，报的一样的错误。

hi，你训练的是什么模型？另外，建议设置小一点batch_size试试。
