### ISSUE TITLE
大佬能不能出个dygraph加载bert的demo啊(类似paddleHub那种, 有方案也行)，做NLP有需求

### ISSUE THREAD

**Issue by Zhangbeibei1991** [PaddlePaddle/Paddle#24622]
欢迎您对PaddlePaddle提出建议，非常感谢您对PaddlePaddle的贡献！
在留下您的建议时，辛苦您同步提供如下信息：
- 版本、环境信息
1）PaddlePaddle版本：请提供您的PaddlePaddle版本号，例如1.1
2）CPU/GPU：您是否使用GPU进行训练，如是，请提供您的CUDA和cuDNN版本号
3）系统环境：请您描述系统类型、版本，例如Mac OS 10.14
- 复现信息：如为报错，请给出复现环境、复现步骤
- 建议描述：请您详细描述，您认为需优化的功能

Thank you for contributing to PaddlePaddle.
Before submitting the issue, you could search issue in the github in case that there was a similar issue submitted or resolved before.
Please make sure that this is a feature request. 
**System information**
-PaddlePaddle version （eg.1.1）or CommitID
-CPU: including CPUMKL/OpenBlas/MKLDNN version
-GPU: including CUDA/CUDNN version
-OS Platform (eg.Mac OS 10.14)
**To Reproduce**
Steps to reproduce the behavior
**Describe the feature and the current behavior/state.**
**Any Other info.**

**Comment by huangjun12** [comment]
dygraph下bert的实现请参考 https://github.com/PaddlePaddle/models/tree/develop/dygraph/bert
可以的话请具体描述下需求~

**Comment by ZeyuChen** [comment]
paddlehub很快会支持动态图版本下的一键模型支持，预计会在paddlepaddle 1.8.2支持，目前正在最后的测试阶段，敬请期待。 @Zhangbeibei1991

**Comment by waywaywayw** [comment]
请问能放出更多的中文bert吗，现在你们只有英文的..

**Comment by nepeplwu** [comment]
@waywaywayw 目前paddlehub已经支持bert等Transfomer系列的动态图加载，参考[教程](https://github.com/PaddlePaddle/PaddleHub/blob/develop/demo/text_classification/text_classifier_dygraph.py)，另外，PaddleHub目前有大量的中文语义模型，例如[Ernie](https://www.paddlepaddle.org.cn/hubdetail?name=ERNIE&en_category=SemanticModel)、[Ernie-Tiny](https://www.paddlepaddle.org.cn/hubdetail?name=ernie_tiny&en_category=SemanticModel)、[Bert](https://www.paddlepaddle.org.cn/hubdetail?name=chinese-bert-wwm&en_category=SemanticModel)、[Roberta](https://www.paddlepaddle.org.cn/hubdetail?name=chinese-roberta-wwm-ext&en_category=SemanticModel)、[Eletra](https://www.paddlepaddle.org.cn/hubdetail?name=chinese-electra-small&en_category=SemanticModel)等等，欢迎试用，有遇到任何问题可以提issue到[PaddleHub](https://github.com/PaddlePaddle/PaddleHub/issues)
