### ISSUE TITLE
c++前向接口是否支持半精度模型？

### ISSUE THREAD

**Issue by yaobh** [PaddlePaddle/Paddle#24621]
你好，我训练了一个半精度的ernie模型，使用预测的demo加载模型的时候会报错，请问c++前向接口支持半精度吗？
- 版本、环境信息：
    1）PaddlePaddle版本：1.7.2

**Comment by Shixiaowei02** [comment]
您好，Paddle 在 1.8.0 版本开始支持混合精度 Ernie 预测

**Comment by yaobh** [comment]
> 您好，Paddle 在 1.8.0 版本开始支持混合精度 Ernie 预测

您好，我使用1.8.0版本，并打开了paddle tensorRT的设置，预测时会报如下错误，请问可能是什么原因？
InvalidArgumentError: The DataType of multihead_matmul Op's duplicable Variable BiasQK must be consistent. The current variable type is (::paddle::platform::float16), but the previous variable type is (float). at (Paddle-release-1.8/paddle/fluid/framework/operator.cc:1298)

**Comment by jshower** [comment]
请问如何在1.8版本中，如何使用C++半精度预测。有相关介绍文档吗。
