### ISSUE TITLE
求指导优化训练性能的方法

### ISSUE THREAD

**Issue by houj04** [PaddlePaddle/Paddle#24659]
想提升训练的性能，包括gpu利用率提升和训练时间的缩短。
用了profile工具，打出来的部分信息长这样，不知道是用法不对，还是由于网络比较小（MobileNet）导致的？
Computation time       Total: 2.02751e+06 Ratio: 26.7407%
Framework overhead     Total: 5.55461e+06 Ratio: 73.2593%
此外特地看了GpuMemcpySync的比例很少。
整体的问题是，不知道如何下手。已经用了厂内的某种流式读数据的reader。

**Comment by Aurelius84** [comment]
请问是GPU静态图模型训练么？从profile里看框架开销的比例比较多，profile里有详细的开销分布，可以贴一下相关信息吗？

另外，可以从以下几个方面考虑：

1. 可以将`fluid.compiler.CompiledProgram`对main_program进行编译
2. 使用`ParallelExecutor`代替 `Executor`
3. 使用`BuildStrategy`配置图优化策略
4. 使用`ExecutionStrategy `配置一些执行策略，比如临时变量回收等

可详细参考：[性能调优文档](https://www.paddlepaddle.org.cn/documentation/docs/zh/advanced_guide/performance_improving/singlenode_training_improving/training_best_practice.html)

**Comment by houj04** [comment]
[my_debug.log](https://github.com/PaddlePaddle/Paddle/files/4656023/my_debug.log)

**Comment by Aurelius84** [comment]
辛苦提供下详细的模型代码。

**Comment by Aurelius84** [comment]
从profile日志来看，大部分的时间都消耗在了`fuse_all_reduce`上面了
![image](https://user-images.githubusercontent.com/9301846/82518486-12028500-9b52-11ea-80eb-4561f799e72b.png)

**Comment by houj04** [comment]
补充另一个实验，打开了
``` python
with profiler.profiler(state = 'All', sorted_key = 'total',  tracer_option='AllOpDetail') as prof
```
输出的日志片段：
> Total time: 1.20366e+06
>   Computation time       Total: 424883      Ratio: 35.2994%
>  Framework overhead     Total: 778772      Ratio: 64.7006%

完整的日志文件：
[0bb5ec743a1992bc.profile.worker0.log](https://github.com/PaddlePaddle/Paddle/files/4666250/0bb5ec743a1992bc.profile.worker0.log)

**Comment by gavin1332** [comment]
加2行配置，以resnet50为例：
export FLAGS_fuse_parameter_memory_size=16
export FLAGS_fuse_parameter_groups_size=50
让allreduce fuse指定fuse参数上限和分组数量上限。
