### ISSUE TITLE
框架clip.py，可能存在bug

### ISSUE THREAD

**Issue by spy109** [PaddlePaddle/Paddle#24650]
parl 框架 MADDPG 示例，运行不了，后定位于 
paddle 框架 fluid/clip.py:550行。

param_name 没有校验，导致程序问题。

![IMG_20200520_000143](https://user-images.githubusercontent.com/6716369/82399008-c46d1600-9a86-11ea-8b8c-5cb5701ac74b.jpg)

加入这个代码 后问题解决。
你看下能不能复现，还是是parl的问题

**Comment by spy109** [comment]
551行，加了个校验代码。不知道图能不能看到。

**Comment by Aurelius84** [comment]
感谢您的反馈，另外，确认下您使用的paddle的版本号是哪个？我看了下，这个param_name判断的问题已经在最新版修复了。
