### ISSUE TITLE
ubuntu服务器安装paddle：paddle.fluid.install_check.run_check() 出现问题

### ISSUE THREAD

**Issue by super3kl** [PaddlePaddle/Paddle#24657]
import paddle.fluid as pp
>>> pp.install_check.run_check()
Running Verify Fluid Program ...
W0520 15:26:18.307366 24061 device_context.cc:252] Please NOTE: devic
W0520 15:26:18.312017 24061 device_context.cc:260] device: 0, cuDNN V
W0520 15:26:20.338177 24061 device_context.h:155] WARNING: device: 0.is 7.3, which may cause serious incompatible bug. Please recompile or
Your Paddle Fluid works well on SINGLE GPU or CPU.
W0520 15:26:31.293614 24061 dynamic_loader.cc:120] Can not find libra_PATH.
/home/zhulei/anaconda3/envs/paddle/lib/python3.7/site-packages/paddlen.
  "The following exception is not an EOF exception.")
2020-05-20 15:26:31,316-WARNING: Your Paddle Fluid has some problem w
 1. There is only 1 or 0 GPU visible on your Device;
 2. No.1 or No.2 GPU or both of them are occupied now
 3. Wrong installation of NVIDIA-NCCL2, please follow instruction on
 to test your NCCL, or reinstall it following https://docs.nvidia.com

 Original Error is:

--------------------------------------------
C++ Call Stacks (More useful to developers):
--------------------------------------------
0   std::string paddle::platform::GetTraceBackString<char const*>(cha
1   paddle::platform::EnforceNotMet::EnforceNotMet(std::__exception_p
2   paddle::platform::dynload::GetNCCLDsoHandle()
3   void std::__once_call_impl<std::_Bind_simple<paddle::platform::dyint*)::{lambda()#1} ()> >()
4   paddle::platform::NCCLContextMap::NCCLContextMap(std::vector<padd, unsigned long, unsigned long)
5   paddle::platform::NCCLCommunicator::InitFlatCtxs(std::vector<paddcclUniqueId*, std::allocator<ncclUniqueId*> > const&, unsigned long,
6   paddle::framework::ParallelExecutorPrivate::InitNCCLCtxs(paddle::
7   paddle::framework::ParallelExecutorPrivate::InitOrGetNCCLCommunic
8   paddle::framework::ParallelExecutor::ParallelExecutor(std::vectortor<std::string, std::allocator<std::string> > const&, std::string coor<paddle::framework::Scope*> > const&, paddle::framework::details::Eramework::ir::Graph*)

----------------------
Error Message Summary:
----------------------
Error: Failed to find dynamic library: libnccl.so ( libcudart.so.8.0:
 Please specify its path correctly using following ways:
 Method. set environment variable LD_LIBRARY_PATH on Linux or DYLD_LI
 For instance, issue command: export LD_LIBRARY_PATH=...
 Note: After Mac OS 10.11, using the DYLD_LIBRARY_PATH is impossible orm/dynload/dynamic_loader.cc:177)

Your Paddle Fluid is installed successfully ONLY for SINGLE GPU or CP
 Let's start deep Learning with Paddle Fluid now

使用学校服务器
提示无法找到libcudart.so.8.0  服务器装了 cuda10 和cuda 9  这俩有libcudart.so.9.0 libcudart.so.10.0 但就是没有8.0

**Comment by Aurelius84** [comment]
paddle支持cuda9和cuda10，你可以安装这两个版本的paddle。详见文档：https://www.paddlepaddle.org.cn/

**Comment by tianshuo78520a** [comment]
请问你是怎么安装的paddle的？尝试设置下LD_LIBRARY_PATH环境变量

**Comment by super3kl** [comment]
安装方式：按照 网页提示的 ubuntu + conda 安装的  之前都没有问题
到最后一步 验证信息有问题 我装的就是 cuda 10版本
以下是 conda list
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main    defaults
astor                     0.8.0                    py37_0    defaults
blas                      1.0                         mkl    defaults
ca-certificates           2020.1.1                      0    defaults
cairo                     1.14.12              h8948797_3    defaults
certifi                   2020.4.5.1               py37_0    defaults
cffi                      1.14.0           py37h2e261b9_0    defaults
chardet                   3.0.4                 py37_1003    defaults
cryptography              2.9.2            py37h1ba5d50_0    defaults
cudatoolkit               10.0.130                      0    defaults
cudnn                     7.3.1                cuda10.0_0    defaults
cycler                    0.10.0                   py37_0    defaults
dbus                      1.13.14              hb2f20db_0    defaults
decorator                 4.4.2                      py_0    defaults
expat                     2.2.6                he6710b0_0    defaults
fontconfig                2.13.0               h9420a91_0    defaults
freetype                  2.9.1                h8a8886c_1    defaults
fribidi                   1.0.5                h7b6447c_0    defaults
funcsigs                  1.0.2                    pypi_0    pypi
gast                      0.3.3                      py_0    defaults
glib                      2.63.1               h5a9c865_0    defaults
graphite2                 1.3.13               h23475e2_0    defaults
graphviz                  2.40.1               h21bd128_2    defaults
gst-plugins-base          1.14.0               hbbd80ab_1    defaults
gstreamer                 1.14.0               hb453b48_1    defaults
harfbuzz                  1.8.8                hffaf4a1_0    defaults
icu                       58.2                 he6710b0_3    defaults
idna                      2.9                        py_1    defaults
intel-openmp              2020.1                      217    defaults
jpeg                      9b                   h024ee3a_2    defaults
kiwisolver                1.2.0            py37hfd86e86_0    defaults
ld_impl_linux-64          2.33.1               h53a641e_7    defaults
libedit                   3.1.20181209         hc058e9b_0    defaults
libffi                    3.2.1                hd88cf55_4    defaults
libgcc-ng                 9.1.0                hdf63c60_0    defaults
libgfortran-ng            7.3.0                hdf63c60_0    defaults
libpng                    1.6.37               hbc83047_0    defaults
libprotobuf               3.11.4               hd408876_0    defaults
libstdcxx-ng              9.1.0                hdf63c60_0    defaults
libtiff                   4.1.0                h2733197_0    defaults
libuuid                   1.0.3                h1bed415_2    defaults
libxcb                    1.13                 h1bed415_1    defaults
libxml2                   2.9.9                hea5a465_1    defaults
matplotlib                3.1.3                    py37_0    defaults
matplotlib-base           3.1.3            py37hef1b27d_0    defaults
mkl                       2020.1                      217    defaults
mkl-service               2.3.0            py37he904b0f_0    defaults
mkl_fft                   1.0.15           py37ha843d7b_0    defaults
mkl_random                1.1.0            py37hd6b4f25_0    defaults
ncurses                   6.2                  he6710b0_1    defaults
nltk                      3.4.5                    py37_0    defaults
numpy                     1.18.1           py37h4f9e942_0    defaults
numpy-base                1.18.1           py37hde5b4d6_1    defaults
objgraph                  3.4.1                    pypi_0    pypi
olefile                   0.46                     py37_0    defaults
openssl                   1.1.1g               h7b6447c_0    defaults
paddlepaddle-gpu          1.8.1.post107            pypi_0    pypi
pango                     1.42.4               h049681c_0    defaults
pathlib                   1.0.1                    py37_1    defaults
pcre                      8.43                 he6710b0_0    defaults
pillow                    7.1.2            py37hb39fc2d_0    defaults
pip                       20.0.2                   py37_3    defaults
pixman                    0.38.0               h7b6447c_0    defaults
prettytable               0.7                      pypi_0    pypi
protobuf                  3.11.4           py37he6710b0_0    defaults
py-cpuinfo                5.0.0                      py_0    defaults
pycparser                 2.20                       py_0    defaults
pyopenssl                 19.1.0                   py37_0    defaults
pyparsing                 2.4.7                      py_0    defaults
pyqt                      5.9.2            py37h05f1152_2    defaults
pysocks                   1.7.1                    py37_0    defaults
python                    3.7.7           hcf32534_0_cpython    defaults
python-dateutil           2.8.1                      py_0    defaults
pyyaml                    5.3.1            py37h7b6447c_0    defaults
qt                        5.9.7                h5867ecd_1    defaults
readline                  8.0                  h7b6447c_0    defaults
recordio                  0.1                      pypi_0    pypi
requests                  2.23.0                   py37_0    defaults
scipy                     1.4.1            py37h0b6359f_0    defaults
setuptools                46.4.0                   py37_0    defaults
sip                       4.19.8           py37hf484d3e_0    defaults
six                       1.14.0                   py37_0    defaults
sqlite                    3.31.1               h62c20be_1    defaults
tk                        8.6.8                hbc83047_0    defaults
tornado                   6.0.4            py37h7b6447c_1    defaults
urllib3                   1.25.8                   py37_0    defaults
wheel                     0.34.2                   py37_0    defaults
xz                        5.2.5                h7b6447c_0    defaults
yaml                      0.1.7                had09818_2    defaults
zlib                      1.2.11               h7b6447c_3    defaults
zstd                      1.3.7                h0b5b093_0    defaults

**Comment by tianshuo78520a** [comment]
echo $LD_LIBRARY_PATH 打印下环境变量看看

**Comment by super3kl** [comment]
(paddle) [zhulei@node3 ~]$echo $LD_LIBRARY_PATH
/home/hadoop/anaconda2/lib:/usr/local/lib:/usr/lib64:/usr/local/lib64:/usr/lib:/usr/local/cuda/lib64:$LD_LIBRARY_PATH:/usr/local/cuda/lib64:/share/hpl:/opt/intel/composerxe-2011.4.191/mkl/lib/intel64/:/opt/intel/composerxe-2011.4.191/compiler/lib/intel64/:/opt/openmpi/lib/:/usr/local/cuda-10.0/lib64

**Comment by tianshuo78520a** [comment]
> (paddle) [zhulei@node3 ~]$echo $LD_LIBRARY_PATH
> /home/hadoop/anaconda2/lib:/usr/local/lib:/usr/lib64:/usr/local/lib64:/usr/lib:/usr/local/cuda/lib64:$LD_LIBRARY_PATH:/usr/local/cuda/lib64:/share/hpl:/opt/intel/composerxe-2011.4.191/mkl/lib/intel64/:/opt/intel/composerxe-2011.4.191/compiler/lib/intel64/:/opt/openmpi/lib/:/usr/local/cuda-10.0/lib64


通过export CUDA_VISIBLE_DEVICES设置一下只跑卡1,可能是nccl没有装好。

**Comment by super3kl** [comment]
感谢回答，命令有用
另外那么多卡训练是不是不能了

**Comment by tianshuo78520a** [comment]
> 感谢回答，命令有用
> 另外那么多卡训练是不是不能了

多卡需要安装下nccl，可以参考这个链接：https://developer.nvidia.com/nccl

**Comment by tianshuo78520a** [comment]
> 感谢回答，命令有用
> 另外那么多卡训练是不是不能了

你用的ubuntu什么版本？

**Comment by super3kl** [comment]
14.04  感谢回答
