### ISSUE TITLE
1.8.1版本函数报错,1.5版本却正常。 InvalidArgumentError: The shape of Input(Length) should be [batch_size]. But received (2) 

### ISSUE THREAD

**Issue by geekhch** [PaddlePaddle/Paddle#24664]

**Comment by geekhch** [comment]
新版paddle中这个函数报错，同样的代码在1.5版本中可以正常运行，代码来源是百度关系抽取竞赛的官方baseline。辛苦大佬们验证一下是否框架bug.
InvalidArgumentError: The shape of Input(Length) should be [batch_size]. But received (2) 
[Hint: Expected len_dims.size() == 1, but received len_dims.size():2 != 1:1.] at (D:\1.8.1\paddle\paddle\fluid\operators\sequence_ops\sequence_unpad_op.cc:52)

**Comment by Aurelius84** [comment]
`sequence_pad`和`sequence_unpad`这两个api中的涉及返回或传入的`length`的shape在1.6版本做了升级，之前`length.shape` = [length, 1]，1.6版本之后把最后一维的1给移除了（无用信息）。

详情请参考示例：https://www.paddlepaddle.org.cn/documentation/docs/zh/api_cn/layers_cn/sequence_pad_cn.html#sequence-pad

**Comment by geekhch** [comment]
> 
> 
> `sequence_pad`和`sequence_unpad`这两个api中的涉及返回或传入的`length`的shape在1.6版本做了升级，之前`length.shape` = [length, 1]，1.6版本之后把最后一维的1给移除了（无用信息）。
> 
> 详情请参考示例：https://www.paddlepaddle.org.cn/documentation/docs/zh/api_cn/layers_cn/sequence_pad_cn.html#sequence-pad

明白了，非常感谢

**Comment by vflanker** [comment]
> `sequence_pad`和`sequence_unpad`这两个api中的涉及返回或传入的`length`的shape在1.6版本做了升级，之前`length.shape` = [length, 1]，1.6版本之后把最后一维的1给移除了（无用信息）。
> 
> 详情请参考示例：https://www.paddlepaddle.org.cn/documentation/docs/zh/api_cn/layers_cn/sequence_pad_cn.html#sequence-pad

你好，我遇到的是跟@geekhch一样的问题，也是这个baseline，我把最后一维的信息给去掉了，能往下走，并且按要求，第一个维度写上batch_size。但是运行过了这段代码，又重新回来执行了这段代码，最后还是报了“长度要求为2而我的是1”，但事实是我的还是1维啊。
![image](https://user-images.githubusercontent.com/30745146/94121066-78dad680-fe83-11ea-9ff7-015a9dfb3ebb.png)

**Comment by vflanker** [comment]
> > `sequence_pad`和`sequence_unpad`这两个api中的涉及返回或传入的`length`的shape在1.6版本做了升级，之前`length.shape` = [length, 1]，1.6版本之后把最后一维的1给移除了（无用信息）。
> > 详情请参考示例：https://www.paddlepaddle.org.cn/documentation/docs/zh/api_cn/layers_cn/sequence_pad_cn.html#sequence-pad
> 
> 明白了，非常感谢

你好，最近我使用百度的baseline时也遇到了相同的问题，不过没有解决，可否向您请教解决方法？谢谢。
