### ISSUE TITLE
AIstudio中paddle版本问题

### ISSUE THREAD

**Issue by BeyondYourself** [PaddlePaddle/Paddle#24671]
5.19看到后台公告，AIstudio中Notebook项目支持PaddlePaddle 1.8.0，但是我的环境还是1.4.1。如下图所示：
![image](https://user-images.githubusercontent.com/12640462/82512310-48d09f00-9b42-11ea-8979-5e414cae3b01.png)
另外通过pip list查询到的也是1.4.1的版本：
![image](https://user-images.githubusercontent.com/12640462/82512344-67369a80-9b42-11ea-8b14-0cd85eaac474.png)

**Comment by sbl1996** [comment]
是不是fork的别人的项目，那就是他创建时的paddle版本，如果项目比较老，版本也比较老，试一下下面的操作
![image](https://user-images.githubusercontent.com/13728074/82512668-5175a500-9b43-11ea-9ca5-20af0feb9386.png)
![image](https://user-images.githubusercontent.com/13728074/82512689-60f4ee00-9b43-11ea-8de7-8d707eef17ab.png)
![image](https://user-images.githubusercontent.com/13728074/82512730-8124ad00-9b43-11ea-9ba8-876ef4c6b766.png)

**Comment by BeyondYourself** [comment]
多谢，已经解决。我之前的项目是在公开课中的项目上直接修改的，所以没找到版本切换地方
