### ISSUE TITLE
infer的时候变换输入尺寸报错

### ISSUE THREAD

**Issue by sidatian** [PaddlePaddle/Paddle#24686]
1.包了个函数做推理，函数要在同一个进程调用多次
2.第一次调用的时候，输入name叫data，size是size_1
3.第二次调用的时候，输入name叫data，size是size_2
4.因为size_1和size_2不相等，所以报错说data的size只能是size_1
5.为了解决这个问题，把输入name改成data_size_i,这样不同的输入size有不同name
6.这样做了之后，第二次调用的输入name是data_size_2，但是报错说data_size_1没有初始化

请问推理的时候，变换输入尺寸，应该如何处理

**Comment by SunGaofeng** [comment]
能贴下函数的形式，以及调用的方式吗？
我下面这段示例代码，跟您期望的调用方式是一致的吗，第一次输入图片尺寸[10,3,28,28]，第二次[10, 3, 28, 48]，执行两次exe.run都可以运行

    IMG_ROWS = 28
    IMG_COLS = 28

    X = layers.data(name = "img", shape = [-1, 3, IMG_ROWS, IMG_COLS], dtype = "float32")
    h_conv = layers.conv2d(X, num_filters = 32, filter_size = (3, 3), act = "relu")
    h_conv = layers.conv2d(h_conv, num_filters = 64, filter_size = (3, 3), act = "relu")
    h_pool = layers.pool2d(h_conv, pool_size = (2, 2))
    Y = fluid.layers.reduce_sum(h_pool)

    place = fluid.CPUPlace()
    exe = fluid.Executor(place)
    exe.run(fluid.default_startup_program())

    imgs = np.random.rand(10, 3, IMG_ROWS, IMG_COLS).astype('float32')
    output, = exe.run(program=fluid.default_main_program(),
                           feed = {"img": imgs},
                           fetch_list = [Y])
    print('output = ', output)

    imgs = np.random.rand(10, 3, IMG_ROWS, IMG_COLS+20).astype('float32')
    output, = exe.run(program=fluid.default_main_program(),
                           feed = {"img": imgs},
                           fetch_list = [Y])
    print('output = ', output)
