### ISSUE TITLE
paddle.distributed.launch一个小地方，文档和行为不符

### ISSUE THREAD

**Issue by houj04** [PaddlePaddle/Paddle#24691]
文档：
https://www.paddlepaddle.org.cn/documentation/docs/zh/advanced_guide/distributed_training/cluster_howto.html
里面提到

> 日志：每个训练进程的日志默认会保存在 ./mylog 目录下，您也可以通过参数 --log_dir 进行指定。

但是其实代码里面并没有这个`./mylog`的默认值：
https://github.com/PaddlePaddle/Paddle/blob/release/1.8/python/paddle/distributed/launch.py

``` python
parser.add_argument(
    "--log_dir",
    type=str,
    help="The path for each process's log.If it's not set, the log will printed to default pipe."
)
```

**Comment by LDOUBLEV** [comment]
好的，我反馈下，统一下文档和代码

**Comment by guru4elephant** [comment]
这个页面已经下掉，1.8开始就不再给用户使用，我们会在develop版本增加新的文档，stay tunned. @houj04
