### ISSUE TITLE
spectral norm 怎么对卷积层和全连接层里面的权重进行操作

### ISSUE THREAD

**Issue by MingtaoGuo** [PaddlePaddle/Paddle#24716]
文档里只描述了spectral norm 对一个矩阵进行操作，但是由于paddle中conv和fc中权重weight都封装在函数里面，不知道如何用spectral norm对conv和fc中的权重weight进行操作。

或者有没有存在一个conv函数，权重是非封装的。

**Comment by MingtaoGuo** [comment]
PS. 每次迭代都要对conv和fc中的weight进行一次spectral norm，不知道paddle有没有这个API能够调用，如果没有的话，希望提供一个conv函数，weight是不封装的，能够自己传进去。

希望提供一个静态的接口，谢谢。

**Comment by qingqing01** [comment]
@MingtaoGuo 静态图接口可以参考： https://github.com/PaddlePaddle/models/blob/release/1.8/PaddleCV/tracking/pytracking/libs/Fconv2d_static.py#L19 ，自行加一个这样的函数。Paddle后续的版本会包含输入和weight都作为输入的接口。

**Comment by MingtaoGuo** [comment]
谢谢回复，我试试
