### ISSUE TITLE
浮点数向量序列该如何定义输入？

### ISSUE THREAD

**Issue by jeromeJT** [PaddlePaddle/Paddle#2471]
我的预测任务需要用到浮点数向量序列输入，查看了一下文档和机器翻译的例子，没有弄懂如何定义，麻烦各位帮解答一下，谢谢

yield的数据样例：
[[0.0, 1.0, 0.2903], [0.0, 1.0, 0.291], [0.0, 1.0, 0.2917]]   [0]
data = paddle.layer.data("status",paddle.data_type.dense_vector(params))
这里面的params该如何填写？

**Comment by lcy-seso** [comment]
定义 data_layer如下：
```python
input = paddle.layer.data(
        name='input',
        type=paddle.data_type.dense_vector_sequence(4))
```
python 端读数据接口返回如下格式的python list： [ [ float, float, float, ...], [float, float ....], ... ]

**Comment by lcy-seso** [comment]
1. data 的type 指定错误  `paddle.data_type.dense_vector` --> `paddle.data_type.dense_vector_sequence`
2. 实例中 `params` 变量表示的是一个时间步实向量的维度，对应以上的示例数据，params 的大小为 3

**Comment by jeromeJT** [comment]
后续问题：
dense_vector_sequence无法作为TableProjection的输入了，该换用哪种呢？

背景：使用lstm，lstm不能直接接输入layer，需要做embedding

**Comment by lcy-seso** [comment]
如果要使用 table_projection ，必须使用 integer_value_sequence。

**Comment by jeromeJT** [comment]
不一定要使用table_projection，只要是能让lstm能够run起来就行。

**Comment by lcy-seso** [comment]
1. table_projection 的作用是将离散输入转化为实数输入，只能接受 integer_value_sequence。
2. lstm 的输入是实向量输入。

**Comment by lcy-seso** [comment]
1. 内部文档：http://wiki.baidu.com/pages/viewpage.action?pageId=143955566
2. 外部文档：http://www.paddlepaddle.org/release_doc/0.9.0/doc_cn/ui/data_provider/pydataprovider2.html#input-types

请确定到底需要何种输入。

**Comment by jeromeJT** [comment]
确定需要的是dense_vector_sequence，因为每个时间点会有多个特征，比如 状态、天气、历史信息 等等
