### ISSUE TITLE
pip安装错误

### ISSUE THREAD

**Issue by cyrxdzj** [PaddlePaddle/Paddle#24713]
ubuntu ukylin 20.04
pip3 install paddlepaddle报错。
python3.8.2

**Comment by tianshuo78520a** [comment]
可以把安装的报错信息发下吗？paddle目前没有发布python3.8版本的whl包

**Comment by cyrxdzj** [comment]
官网安装命令报错，命令：python -m pip install paddlepaddle -i https://mirror.baidu.com/pypi/simple
错误信息:
ERROR:Could not find a version that satisfies the requiremeng paddlepaddle (from versions:none)
ERROR:No matching distribution found for paddlepaddle

**Comment by SAMSONEE** [comment]
python的版本太高了，不支持，可以看一下这篇文章：https://blog.csdn.net/weixin_43887162/article/details/104342699

**Comment by tianshuo78520a** [comment]
> 官网安装命令报错，命令：python -m pip install paddlepaddle -i https://mirror.baidu.com/pypi/simple
> 错误信息:
> ERROR:Could not find a version that satisfies the requiremeng paddlepaddle (from versions:none)
> ERROR:No matching distribution found for paddlepaddle

目前Paddle还没有发布python 3.8版本的whl包，可以使用python3.7安装paddle，如果有需要您可以自行编译。参考：https://www.paddlepaddle.org.cn/documentation/docs/zh/install/compile/compile_Ubuntu.html

**Comment by cyrxdzj** [comment]
哦，原来如此。

**Comment by cyrxdzj** [comment]
不过话说回来，何时才能有Python3.8的whl包呢？

**Comment by linhandev** [comment]
期待早日上3.8,manjaro都是最新的python，为了paddle还得装个conda
