### ISSUE TITLE
windows下C++推理开启TRT报错

### ISSUE THREAD

**Issue by cyanjustice** [PaddlePaddle/Paddle#24719]
从官网上下载的最新paddle1.8的源代码，并加入TensorRT路径使用CMAKE进行重新编译，编译全部成功。
未开启TRT时推理正常，开启TRT子图加速模式进行推理会出现如下报错
![image](https://user-images.githubusercontent.com/46018705/82772674-6c615580-9e72-11ea-9e7e-2b01b43b6c2d.png)
![image](https://user-images.githubusercontent.com/46018705/82772683-72573680-9e72-11ea-9519-45a000788e27.png)

**Comment by luotao1** [comment]
您好，Paddle1.8版本对windows源码编译带trt的预测库，并没有验证过。
您能否给出更多的报错信息，以及windows型号/环境？
如您方便，可以将模型/数据/整个复现环境给我们么？

**Comment by cyanjustice** [comment]
目前使用环境为windows10，VS2017。
C++程序执行到这一步就出现如上的报错
![image](https://user-images.githubusercontent.com/46018705/82783967-32a04700-9e92-11ea-89a0-8d68bcc20edf.png)
由于初始化就出现报错，所以与数据无关。
以下链接为编译完成的TRT推理库以及模型，TRT版本为5.1.5。模型使用的是yolov3。
链接：https://pan.baidu.com/s/1_2oE_AqP13Km3y0I865xeg 
提取码：cb4e
谢谢！

**Comment by cryoco** [comment]
你好，请问gpu是什么型号呢

**Comment by cyanjustice** [comment]
RTX2080ti,CUDA10,CUDNN7.5

**Comment by luotao1** [comment]
@silingtong123 请帮忙复现一下，谢谢！

**Comment by OliverLPH** [comment]
@cyanjustice 
您好，我这边用 vs2015编译了 release/1.8带trt的预测库，使用了您提供的yolov3模型，没有遇到这个问题。

config:
![trt_fp16_config](https://user-images.githubusercontent.com/14963836/82894215-cb16f400-9f84-11ea-86ac-a604f3d60505.png)

output:
![trt_fp16_log](https://user-images.githubusercontent.com/14963836/82894596-64460a80-9f85-11ea-95ee-aa776485e617.png)

environment：
* CUDA10
* CUDNN7.3
* vs2015

您可以`set GLOG_v=4`，然后再跑下看看具体是什么错误，有可能是环境里面没找到 `nvinfer.dll` 这个动态库导致的程序直接挂掉。

或者可以试下我编译产出的预测库，看看是否还有问题
> 链接: https://pan.baidu.com/s/1uBPp4Ec9yc6lviXjtpeARw  密码: 16f5

**Comment by silingtong123** [comment]
1. 本地测试正常， 问题未复现
环境：
- CUDA10
- CUDNN7.6
- vs2015

2. 未在你的预测库下面发现tensorrt目录，在windwos使用tensorrrt预测库的时候需要手动将tensorrt的lib目录和include目录，移动到fluid_inference_install/third_party/install/tensorrt(需要手动创建)
- 移动前：
![image](https://user-images.githubusercontent.com/35439432/82896840-34990180-9f89-11ea-9cc7-6aa2c1c4b4f2.png)
- 移动后：
![image](https://user-images.githubusercontent.com/35439432/82896901-53979380-9f89-11ea-8d06-4dee3c51ee53.png)

3. 你可以试试你的预测库能否在demo windows_mobilenet中使用tensorrt（ paddle\fluid\inference\api\demo_ci\windows_mobilenet.cc），需要添加对应代码
![image](https://user-images.githubusercontent.com/35439432/82899050-e423a300-9f8c-11ea-88e6-7b2037ac1fd0.png)
- 确定是否打开USE_TENSORRT编译选项，未打开且再命令窗口输入set GLOG_v=4, 运行程序出现类似如下，并直接退出
![image](https://user-images.githubusercontent.com/35439432/82897951-0ae0da00-9f8b-11ea-8bd8-e66f0aaec79a.png)
    - .exe目录下没有nvinfer.dll，nvinfer_plugin.dll文件
![image](https://user-images.githubusercontent.com/35439432/82898131-509da280-9f8b-11ea-8b27-1e4bb2721522.png)
- 打开USE_TENSORRT编译选项，运行cmake命令并编译运行程序，成功运行
![image](https://user-images.githubusercontent.com/35439432/82898563-1f71a200-9f8c-11ea-9c86-9dda3dea64ac.png)
   -  .exe目录下有nvinfer.dll，nvinfer_plugin.dll文件
![image](https://user-images.githubusercontent.com/35439432/82898646-4039f780-9f8c-11ea-9866-b8a7b43ab36a.png)

**Comment by cyanjustice** [comment]
把两个dll文件放进文件夹里，问题就解决了。感谢！
