### ISSUE TITLE
fleet 修改组网后无法自动生成 网络描述proto

### ISSUE THREAD

**Issue by jzh1992** [PaddlePaddle/Paddle#24710]
修改组网后，精排模型无法自动生成cur_fleet_desc.proto。提示miss service param报错。

**Comment by xjqbest** [comment]
是不是写文件cur_fleet_desc.proto的代码在minimize之前了，只有minimize后才会有fleet_desc

**Comment by xjqbest** [comment]
用户反馈已解决
