### ISSUE TITLE
mask模型 多batch预测会报错

### ISSUE THREAD

**Issue by carol510** [PaddlePaddle/Paddle#24712]
错误信息
----------------------
Error Message Summary:
----------------------
Error: The start row index must be lesser than the end row index.
  [Hint: Expected begin_idx < end_idx, but received begin_idx:0 >= end_idx:0.] at (/paddle/Paddle/paddle/fluid/framework/tensor.cc:83)
  [operator < multiclass_nms > error]
paddle版本1.6.2
代码：

![1590152356055](https://user-images.githubusercontent.com/22268236/82670103-1cff0780-9c6f-11ea-8d90-3e3e48bb831d.jpg)

**Comment by qingqing01** [comment]
@carol510 从错误信息看是nms中计算某项出现了空的，注意要正确加载模型，可以检查nms的输入是否为空。

**Comment by carol510** [comment]
> @carol510 从错误信息看是nms中计算某项出现了空的，注意要正确加载模型，可以检查nms的输入是否为空。
问题为需要batch size一致
