### ISSUE TITLE
关于focal_loss的问题

### ISSUE THREAD

**Issue by luotao1** [PaddlePaddle/Paddle#24725]
来自用户群的问题：
![image](https://user-images.githubusercontent.com/6836917/82800018-8cfad100-9ead-11ea-912c-520d980ed7b9.png)
- 你好，想咨询下[focal_loss](https://www.paddlepaddle.org.cn/documentation/docs/zh/api_cn/layers_cn/sigmoid_focal_loss_cn.html#sigmoid-focal-loss)里为什么要有这样一个fg_num的参数，我看论文里没有这个
- 我把fg_num设成1或者正样本的数量，结果都不太对，loss没有降过。是我的用法不对么？
![image](https://user-images.githubusercontent.com/6836917/82800233-ef53d180-9ead-11ea-947f-bdafc84cec80.png)

**Comment by luotao1** [comment]
@FlyingQianMM 的回答

> 你好，想咨询下focal_loss里为什么要有这样一个fg_num的参数，我看论文里没有这个

![image](https://user-images.githubusercontent.com/6836917/82800181-d4815d00-9ead-11ea-8291-483ca63ff3ae.png)
论文里提到了需要除以正样本数量，如果不需要的话，可以把fg_num设成值为1的tensor

> 我把fg_num设成1或者正样本的数量，结果都不太对，loss没有降过。是我的用法不对么？

用法上看起来没有问题，可以尝试下调整gamma, alpha，这两个都是超参。把gamma设成1， aplha设成0.5，loss外面乘以2，这样是跟cross_entropy等价的

**Comment by luotao1** [comment]
用户尝试调整gamma, alpha都没有效果。

@FlyingQianMM 的回答

![image](https://user-images.githubusercontent.com/6836917/82800431-48bc0080-9eae-11ea-8f2f-11b329bdc13a.png)

1. pred在进入sigmoid_focal_loss之前不要做soft_max操作 
2. sigmoid_focal_loss需要使用fg_num做归一化，所以需要计算下label里面大于0的个数 
3. 返回值是每张图片的focal loss，网络的loss需要把返回值做reduce sum 
4. 预测阶段对pred做sigmoid操作 
5. 改了下你的class_num，原本是26，现在是25。你之前使用的cross_entropy是针对softmax的，目前的focal loss是针对的sigmoid，所以直接用一样的网络结构会有点问题。

TODO：

1. 这个api的目前的示例还是不太能引导用户正确使用，会抽空重新在写下代码示例
2. 后续会把softmax_focal_loss也集成进去

**Comment by Ivancc99** [comment]
> 来自用户群的问题：
> ![image](https://user-images.githubusercontent.com/6836917/82800018-8cfad100-9ead-11ea-912c-520d980ed7b9.png)
> 
> * 你好，想咨询下[focal_loss](https://www.paddlepaddle.org.cn/documentation/docs/zh/api_cn/layers_cn/sigmoid_focal_loss_cn.html#sigmoid-focal-loss)里为什么要有这样一个fg_num的参数，我看论文里没有这个
> * 我把fg_num设成1或者正样本的数量，结果都不太对，loss没有降过。是我的用法不对么？
>   ![image](https://user-images.githubusercontent.com/6836917/82800233-ef53d180-9ead-11ea-947f-bdafc84cec80.png)



> 用户尝试调整gamma, alpha都没有效果。
> 
> @FlyingQianMM 的回答
> 
> ![image](https://user-images.githubusercontent.com/6836917/82800431-48bc0080-9eae-11ea-8f2f-11b329bdc13a.png)
> 
> 1. pred在进入sigmoid_focal_loss之前不要做soft_max操作
> 2. sigmoid_focal_loss需要使用fg_num做归一化，所以需要计算下label里面大于0的个数
> 3. 返回值是每张图片的focal loss，网络的loss需要把返回值做reduce sum
> 4. 预测阶段对pred做sigmoid操作
> 5. 改了下你的class_num，原本是26，现在是25。你之前使用的cross_entropy是针对softmax的，目前的focal loss是针对的sigmoid，所以直接用一样的网络结构会有点问题。
> 
> TODO：
> 
> 1. 这个api的目前的示例还是不太能引导用户正确使用，会抽空重新在写下代码示例
> 2. 后续会把softmax_focal_loss也集成进去

请问能否支持图像分割呢，如果可以的话，N是否可以看作是像素点的数目呢？

**Comment by FlyingQianMM** [comment]
支持图像分割的，N视为总像素点数量

**Comment by Qingcsai** [comment]
建议增加对于分割任务的fg_num计算方法

**Comment by FlyingQianMM** [comment]
> 建议增加对于分割任务的fg_num计算方法

代码示例中已经添加了fg_num获取的示例，可以参考https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/fluid/layers/sigmoid_focal_loss_cn.html#sigmoid-focal-loss

2.0中sigmoid_focal_loss也有fg_num获取的示例，可以参考https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/nn/functional/loss/sigmoid_focal_loss_cn.html#sigmoid-focal-loss
