### ISSUE TITLE
安装问题

### ISSUE THREAD

**Issue by etoilestar** [PaddlePaddle/Paddle#24728]
使用pip安装1.7.1版本时，ubuntu16.04系统，cuda10.1，cudnn7.6.5版本，paddle.fluid.install_check.run_check()报错：Error: Cannot load cudnn shared library. Cannot invoke method cudnnGetVersion at

**Comment by luotao1** [comment]
请问cudnn库是否在系统路径下呢？
可以参考下#17177 和 #22996

**Comment by etoilestar** [comment]
我在bashrc中export路径了

**Comment by luotao1** [comment]
请问你具体装的是哪个版本的？需要装cuda10对应的版本，可以参考 https://github.com/PaddlePaddle/PaddleOCR/issues/63#issuecomment-630557208

**Comment by etoilestar** [comment]
1.7.1我看版本是可以对应的

**Comment by etoilestar** [comment]
我刚刚在最开始提问时已经说过的

**Comment by etoilestar** [comment]
然后我的cuda是10.1

**Comment by luotao1** [comment]
你的安装命令是什么？

**Comment by dpln2020** [comment]
> 请问cudnn库是否在系统路径下呢？
> 可以参考下#17177 和 #22996

您好，我也遇到了同样的问题。
Error Message Summary:
----------------------
Error: Cannot load cudnn shared library. Cannot invoke method cudnnGetVersion at (/paddle/paddle/fluid/platform/dynload/cudnn.cc:63)

系统：centos7；
cuda10.0；
cudnn：7.6.4；
安装命令：python3 -m pip install paddlepaddle-gpu==1.8.1.post107 -i https://mirror.baidu.com/pypi/simple
请问怎么解决呢？

**Comment by dpln2020** [comment]
> 请问cudnn库是否在系统路径下呢？
> 可以参考下#17177 和 #22996

参考上面两个issue，问题已解决。感谢！
