### ISSUE TITLE
打包后from .core_avx import * 报错DLL load failed 找不到指定的模块

### ISSUE THREAD

**Issue by ArtyZe** [PaddlePaddle/Paddle#24721]
1）PaddlePaddle版本：1.6.3
    2）CPU：请提供CPU型号，MKL/OpenBlas/MKLDNN/等数学库的使用情况
![image](https://user-images.githubusercontent.com/32027268/82782931-05529980-9e90-11ea-9dd2-e741aed30012.png)
MKL, Openblas及MKLDNN的DLL均已放在system32下
    4）系统环境：win7
错误信息：
在本机环境下是ok的
打包后，主要是到core.py 在import core_avx核心函数的时候报错，信息如下：
![image](https://user-images.githubusercontent.com/32027268/82783314-c7a24080-9e90-11ea-8e98-72125466dc73.png)
190行即是如下代码：
from .core_avx import *
请问该如何解决，或者是否有大概思路，多谢：）

**Comment by luotao1** [comment]
> 在本机环境下是ok的
打包后，主要是到core.py 在import core_avx核心函数的时候报错

请问是打包后到其他机器上跑就出错了？打包是什么意思呢？

**Comment by ArtyZe** [comment]
@luotao1 
对的，我用pyinstaller打包成一整个exe了。不过问题刚刚解决啦，我刚刚仔细看了下官网对paddle core的要求。需要mkldnn，于是打包的时候我把libs里面提供的dll打包上就解决了 :)
感谢支持

**Comment by luotao1** [comment]
好的，那我就先关闭issue了，如果有其他问题，请再提新的issue！
