### ISSUE TITLE
尝试跑dense_vector_sequence输入的lstm代码出core

### ISSUE THREAD

**Issue by jeromeJT** [PaddlePaddle/Paddle#2473]
尝试跑dense_vector_sequence输入的lstm代码出core，错误信息如下。请问是啥原因呢？网络配置见附件
[train.py.txt](https://github.com/PaddlePaddle/Paddle/files/1077042/train.py.txt)

[INFO 2017-06-15 16:35:45,163 networks.py:1482] The input order is [status, label]
[INFO 2017-06-15 16:35:45,164 networks.py:1488] Th
[train.py.txt](https://github.com/PaddlePaddle/Paddle/files/1077038/train.py.txt)
e output order is [__classification_cost_0__]
I0615 16:35:45.164999 12802 Util.cpp:166] commandline:  --use_gpu=False --trainer_count=1 
[INFO 2017-06-15 16:35:45,171 networks.py:1482] The input order is [status, label]
[INFO 2017-06-15 16:35:45,171 networks.py:1488] The output order is [__classification_cost_0__]
I0615 16:35:45.173748 12802 GradientMachine.cpp:85] Initing parameters..
I0615 16:35:45.173938 12802 GradientMachine.cpp:92] Init parameters done.

Pass 0, Batch 0, Cost 1.050136, {'classification_error_evaluator': 0.0}
.....................................F0615 16:35:50.136675 12802 Matrix.cpp:3283] Check failed: lbl[i] >= 0 (-1 vs. 0) 
*** Check failure stack trace: ***
    @     0x7fa43c9c262d  google::LogMessage::Fail()
    @     0x7fa43c9c60dc  google::LogMessage::SendToLog()
    @     0x7fa43c9c2153  google::LogMessage::Flush()
    @     0x7fa43c9c75ee  google::LogMessageFatal::~LogMessageFatal()
    @     0x7fa43c91af09  paddle::CpuMatrix::oneHotCrossEntropy()
    @     0x7fa43c790065  paddle::CostLayer::forward()
    @     0x7fa43c8364b0  paddle::NeuralNetwork::forward()
    @     0x7fa43c8140f3  paddle::GradientMachine::forwardBackward()
    @     0x7fa43c99e22b  GradientMachine::forwardBackward()
    @     0x7fa43c6b204e  _wrap_GradientMachine_forwardBackward
    @           0x4a9e33  PyEval_EvalFrameEx
    @           0x4ad70d  PyEval_EvalCodeEx
    @           0x4aa88c  PyEval_EvalFrameEx
    @           0x4ad70d  PyEval_EvalCodeEx
    @           0x4aa88c  PyEval_EvalFrameEx
    @           0x4ad70d  PyEval_EvalCodeEx
    @           0x4aa88c  PyEval_EvalFrameEx
    @           0x4ad70d  PyEval_EvalCodeEx
    @           0x4ad842  PyEval_EvalCode
    @           0x4d64c2  PyRun_FileExFlags
    @           0x4d7839  PyRun_SimpleFileExFlags
    @           0x416edd  Py_Main
    @     0x7fa440dc8bd5  __libc_start_main
    @           0x415f91  (unknown)
    @              (nil)  (unknown)
Aborted (core dumped)

**Comment by lcy-seso** [comment]
1. 已经开始打点，说明训练任务已经跑起来。
2. `Check failed: lbl[i] >= 0 (-1 vs. 0)` 这个出错信息提示数据有问题。

**Comment by jeromeJT** [comment]
追查发现，label中存在-1，已解决，谢谢~
