### ISSUE TITLE
[Paddle-TRT] Different behaviors between blockReduce and warpReduce

### ISSUE THREAD

**Issue by zlsh80826** [PaddlePaddle/Paddle#24731]
1) Paddle Version: develop
2) GPU/cuda-10.2/cudnn7.6.5
3) Ubuntu16.04

Hello! There are different behaviors between [blockReduceSum](https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/fluid/operators/math/math_cuda_utils.h#L138) and [warpReduceSum](https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/fluid/operators/math/math_cuda_utils.h#L126). 
[warpReduceSum](https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/fluid/operators/math/math_cuda_utils.h#L126) makes each thread in the warp has a copy of summation. However, [blockReduceSum](https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/fluid/operators/math/math_cuda_utils.h#L138) only ensures the first warp has the summation, which results in one more block synchronization like [here](https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/fluid/operators/math/bert_encoder_functor.cu#L157).

I suggest two solutions, 
1) Change the behavior of blockReduceSum to [AllReduce](https://docs.nvidia.com/deeplearning/nccl/user-guide/docs/usage/operations.html#allreduce), which computes the summation and ensures each thread in the block have the summation copy.
We only need to change one line to do this. Change the [code]((https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/fluid/operators/math/math_cuda_utils.h#L151)) ``val = (threadIdx.x < block_span) ? shared[lane] : static_cast<T>(0.0f);`` to ``val = (lane < block_span) ? shared[lane] : static_cast<T>(0.0f);``. By doing this, each warp has a copy of first round result. Thus, all threads in the block have the reduced values after the second warpReduce.
2) In blockReduceSum, add a condition which lets only the first warp in the block does the second reduction. Because we only need to ensure ``threadIdx.x`` has the correct reduced value ([SoftmaxKernelWithEltadd](https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/fluid/operators/math/bert_encoder_functor.cu#L161) is the only caller), so only the first warp needs to do the second reduction.
i.e. 
```
if (threadIdx.x < warpSize) {  
    val = (threadIdx.x < block_span) ? shared[lane] : static_cast<T>(0.0f);
    val = warpReduceSum<T>(val, mask);
}
```

In my experiments, the first one has higher performance, because we can delete the unnecessary [shared memory copy](https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/fluid/operators/math/bert_encoder_functor.cu#L164) and [__syncthreads](https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/fluid/operators/math/bert_encoder_functor.cu#L166) after calling the blockReduceXXX function.

BTW, the same issue exists in the [blockReduceMax](https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/fluid/operators/math/math_cuda_utils.h#L170) too.

**Comment by NHZlX** [comment]
OK, I'll take a closer look

**Comment by jeng1220** [comment]
@NHZlX,
In experiment, removing unnecessary warp-reduce in softmax is able to achieve 20% speedup
