### ISSUE TITLE
PaddleDetection  运行YOLOV3，使用Python multiprocessing报CUDA driver and runtime could not be initialized。单独运行可以

### ISSUE THREAD

**Issue by xiaoQxiong** [PaddlePaddle/Paddle#24730]
1. paddle版本 1.8.1， 系统环境 ubuntu 16.04  python 版本 3.6.5
2.GPU 1080ti(11G显存)，cpu i7, CUDA 10.1， cudnn 7.6.5
3.使用python 进行预测，基于代码https://github.com/PaddlePaddle/PaddleDetection/blob/release/0.3/tools/infer.py
4.主要问题为：单独运行infer.py 可以，但是将infer.py 集成到multiprocessing中的一个process则报错CUDA driver and runtime could not be initialized
![image](https://user-images.githubusercontent.com/18461494/82816555-f094f680-9ecd-11ea-9196-24f175947f84.png)
process代码：
![image](https://user-images.githubusercontent.com/18461494/82816643-18845a00-9ece-11ea-9d23-45b72e59c0a9.png)
process调用模型：
![image](https://user-images.githubusercontent.com/18461494/82816763-4e294300-9ece-11ea-9305-24761b56a3f8.png)
检测代码：
![image](https://user-images.githubusercontent.com/18461494/82816678-2f2ab100-9ece-11ea-81aa-4ace10aabdd8.png)

请帮忙看一下这个是因为什么原因导致的

**Comment by luotao1** [comment]
可以提到 https://github.com/PaddlePaddle/PaddleDetection Repo下么？

**Comment by xiaoQxiong** [comment]
你好，具体代码连接在 https://github.com/xiaoQxiong/PaddleDetection 这里。其中zzj_monitor_rtmp.py 是运行process，zzj_infer_SCOPE.py 是单独运行的

**Comment by heavengate** [comment]
你做多进程的是预期做什么呢，如果只是为了多进程读取数据的话PaddleDetection可以通过配置文件修改实现多进程异步读取，配置位置在
https://github.com/PaddlePaddle/PaddleDetection/blob/095b03d21befee5d6b0239ce1e13707895ea75e9/configs/yolov3_reader.yml#L111
添加类似`TrainReader`里的`use_process: true`和`worker_num: 8`配置即可

如果是要预测部署的时候支持多进程并发的话，建议使用`deploy/python`下的代码
https://github.com/PaddlePaddle/PaddleDetection/tree/release/0.3/deploy/python

**Comment by xiaoQxiong** [comment]
你好，做多进程是为了加载不同的模型，进行不同的预测任务，例如先检测到person，在person的基础上继续做进一步的检测 分析任务

**Comment by heavengate** [comment]
CUDAPlace是没法在子进程里开的，如果你要实现这个任务建议把模型导出，通过`deploy/python`或者`deploy/cpp`下的预测部署的方式用多进程跑多个模型
https://github.com/PaddlePaddle/PaddleDetection/tree/release/0.3/deploy

**Comment by xiaoQxiong** [comment]
好滴，我试一下， 多谢指导

**Comment by xiaoQxiong** [comment]
你好，按照给的教程，运行export_model.py之后导出的模型在inference_models目录下，并且单独成功运行：
![image](https://user-images.githubusercontent.com/18461494/82921555-180dc100-9fab-11ea-9159-d6f4f4fdb6b2.png)
但是融入process，具体的代码在paddle_detection.py文件中：
![image](https://user-images.githubusercontent.com/18461494/82921613-278d0a00-9fab-11ea-99f2-376c3533f697.png)
但是还是报错：
![image](https://user-images.githubusercontent.com/18461494/82921832-6c18a580-9fab-11ea-82c6-75ef61f310c3.png)
相应代码已经更新到https://github.com/xiaoQxiong/PaddleDetection ，麻烦帮忙看一下

**Comment by heavengate** [comment]
您好，看你的代码里面还是用的根据`CUDAPlace`初始化`Executor`然后去通过`create`去创建program的方法来实现的， 由于你这里是多进程部署，建议通过
https://github.com/PaddlePaddle/PaddleDetection/blob/release/0.3/tools/export_model.py
里先导出模型，再通过`deploy/python/infer.py`里的方法`load_inference_model`来进行多进程部署
https://github.com/PaddlePaddle/PaddleDetection/blob/7bb04787ce99889331973811a1063cf6e3689914/deploy/python/infer.py#L364

**Comment by xiaoQxiong** [comment]
多谢指导，我尝试一下

**Comment by xiaoQxiong** [comment]
你好，我按照给的方法尝试，具体代码 https://github.com/xiaoQxiong/fast_paddle，其中直接使用paddle_detection中main方式使用Yolov3Detection可以，但是运行zzj_monitor_rtmp.py，采取process中运行，还是报获取不到cuda错误。具体的代码已经上传，并且模型也上传了，可以进行复现错误
