### ISSUE TITLE
对梯度变量进行stop gradient出错

### ISSUE THREAD

**Issue by WorldEditors** [PaddlePaddle/Paddle#24735]
代码如下
https://paste.ubuntu.com/p/syJQXnSmDp/
对梯度变量设置stop_gradient=True（第8行）时会出错
报错信息在第10行

Traceback (most recent call last):
  File "test.py", line 10, in <module>
    grad2 = fluid.gradients(net(x - grad1), x)[0] # gradients( (x - 2x)^2) = 2x = 4
IndexError: list index out of range

**Comment by luotao1** [comment]
请问这个网络是想实现什么功能呢？

**Comment by WorldEditors** [comment]
> 请问这个网络是想实现什么功能呢？

这个是Model-Agnostic Meta learning (MAML）算法实现的一个简化版
Anyway, there's a bug and you need to solve it.

**Comment by luotao1** [comment]
请问你是从哪里看到这样的示例用法呢？
related #23998

**Comment by WorldEditors** [comment]
> 请问你是从哪里看到这样的示例用法呢？

Paddle作为深度学习工具，为什么要管从哪里看到的示例用法呢？
从逻辑上是可以这么做的，但是出现问题了
Paddle不应该仅仅只能用固定的编程方式写固定的模型吧

**Comment by luotao1** [comment]
@kuke 觉得配法是没有问题的，猜测 stop gradient 把反向链路上的 var 都停了，导致第二次调用 gradients 的时候，中间遇到了被停掉的 var。我们需要进一步查看[源代码](https://github.com/PaddlePaddle/Paddle/blob/86ca31ab584078a0a7f15c34b0d7146b9e35ffe6/python/paddle/fluid/backward.py#L1601)。

**Comment by WorldEditors** [comment]
> @kuke 觉得配法是没有问题的，猜测 stop gradient 把反向链路上的 var 都停了，导致第二次调用 gradients 的时候，中间遇到了被停掉的 var。我们需要进一步查看[源代码](https://github.com/PaddlePaddle/Paddle/blob/86ca31ab584078a0a7f15c34b0d7146b9e35ffe6/python/paddle/fluid/backward.py#L1601)。

试了下把第八行换成这两句

p2 = grad1 * 2.0 
p2.stop_gradient = True

也是可以通过的

**Comment by zle1992** [comment]
> 代码如下
> https://paste.ubuntu.com/p/syJQXnSmDp/
> 对梯度变量设置stop_gradient=True（第8行）时会出错
> 报错信息在第10行
> 
> Traceback (most recent call last):
> File "test.py", line 10, in
> grad2 = fluid.gradients(net(x - grad1), x)[0] # gradients( (x - 2x)^2) = 2x = 4
> IndexError: list index out of range

请问代码可以给我参考下嘛，我也想用paddle 实现maml

**Comment by zerobest** [comment]
TypeError: The type of 'Filter' in operator conv2d should be one of [basestring(), str, Varibale] in python2, or one of [str, bytes, Variable] in python3.but received : Parameter containing:
Tensor(shape=[64, 3, 3, 3], dtype=float32, place=Place(gpu:0), stop_gradient=False,
代码如下：
def get_face_revolve(cropped):
    pdb.set_trace()
    input = cv2.resize(cropped, (112, 112))
    input = input.astype(np.float64)
    input = paddle.to_tensor(input,stop_gradient= True)
    input = paddle.unsqueeze(input, 0)
    
    _, landmarks = plfd_backbone(input)
    pre_landmark = landmarks[0]
    pre_landmark = pre_landmark.cpu().detach().numpy().reshape(-1, 2) * [112, 112]
    point_dict = {}
    i = 0
    for (x, y) in pre_landmark.astype(np.float32):
        point_dict[f'{i}'] = [x, y]
        i += 1
