### ISSUE TITLE
加载Paddle so即占用713MB显存，主要是哪些占用，是否有优化方案

### ISSUE THREAD

**Issue by senseb** [PaddlePaddle/Paddle#24753]
为使您的问题得到快速解决，在建立Issues前，请您先通过如下方式搜索是否有相似问题:【搜索issue关键字】【使用labels筛选】【官方文档】

如果您没有查询到相似问题，为快速解决您的提问，建立issue时请提供如下细节信息：
- 标题：加载Paddle so即占用713MB显存，可否优化
- 版本、环境信息：
    1）PaddlePaddle版本：837dd47a968d41629979b8c59b5e00896484dec2
    2）CPU：预测若用CPU，请提供CPU型号，MKL/OpenBlas/MKLDNN/等数学库使用情况
    3）GPU：GeForce RTX 2080TI、CUDA 10.0和CUDNN 7.6.0
    4）系统环境：Ubuntu 18.04
- 训练信息
    1）单机单卡
    2）显存：11GB
- 问题描述：请详细描述您的问题，同步贴出报错信息、日志、可复现的代码片段
启动paddle，并验证GPU正常被调用
ython 2.7.12 (default, Apr 15 2020, 17:07:12)
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import paddle
>>> import paddle.fluid as fluid
>>> fluid.install_check.run_check()
Running Verify Fluid Program ...
W0526 11:58:22.318156 25828 device_context.cc:265] Please NOTE: device: 0, CUDA Capability: 75, Driver API Version: 10.0, Runtime API Version: 10.0
W0526 11:58:22.322162 25828 device_context.cc:273] device: 0, cuDNN Version: 7.6.
Your Paddle Fluid works well on SINGLE GPU or CPU.
Your Paddle Fluid works well on MUTIPLE GPU or CPU.
Your Paddle Fluid is installed successfully! Let's start deep Learning with Paddle Fluid now

此时的显存消耗为713MB，是否可以优化。

![image](https://user-images.githubusercontent.com/446326/82899016-da01a480-9f8c-11ea-9a71-13f2f3c10e97.png)

**Comment by kuke** [comment]
主要来自于框架的预分配，相关说明可以参考[这里](https://www.paddlepaddle.org.cn/documentation/docs/zh/advanced_guide/performance_improving/singlenode_training_improving/memory_optimize.html#autogrowth)。

**Comment by senseb** [comment]
> 主要来自于框架的预分配，相关说明可以参考[这里](https://www.paddlepaddle.org.cn/documentation/docs/zh/advanced_guide/performance_improving/singlenode_training_improving/memory_optimize.html#autogrowth)。

按照上述页面，设置显存分配策略为"显存预分配策略", 并且设置FLAGS_fraction_of_gpu_memory_to_use=0, 按照上述页面说法，此时没有提前预分配显存。

还是执行一样的语句，
`import paddle.fluid as fluid; 
fluid.install_check.run_check();`
当前显存的占用量为707MiB，并未明显减少。请问这707MB的显存主要存储的是什么内容，是否有途径能减少这部分显存占用？@kuke 
环境变量：
![image](https://user-images.githubusercontent.com/446326/82975007-e1b55d80-a00d-11ea-93a2-f08ba9201356.png)

显存占用：
![image](https://user-images.githubusercontent.com/446326/82974885-9733e100-a00d-11ea-863d-bc4c39fd92ed.png)

**Comment by kuke** [comment]
这里应该有些 CUDA Device 初始化之后的本底显存占用，不能全部优化掉

**Comment by zhiqiu** [comment]
> > 主要来自于框架的预分配，相关说明可以参考[这里](https://www.paddlepaddle.org.cn/documentation/docs/zh/advanced_guide/performance_improving/singlenode_training_improving/memory_optimize.html#autogrowth)。
> 
> 按照上述页面，设置显存分配策略为"显存预分配策略", 并且设置FLAGS_fraction_of_gpu_memory_to_use=0, 按照上述页面说法，此时没有提前预分配显存。
> 
> 还是执行一样的语句，
> `import paddle.fluid as fluid; fluid.install_check.run_check();`
> 当前显存的占用量为707MiB，并未明显减少。请问这707MB的显存主要存储的是什么内容，是否有途径能减少这部分显存占用？@kuke
> 环境变量：
> ![image](https://user-images.githubusercontent.com/446326/82975007-e1b55d80-a00d-11ea-93a2-f08ba9201356.png)
> 
> 显存占用：
> ![image](https://user-images.githubusercontent.com/446326/82974885-9733e100-a00d-11ea-863d-bc4c39fd92ed.png)

hi，这个问题是这样的，

1. 713MB显存并不是在加载paddle.so时使用的。如果只执行`import paddle.fluid as fluid`应该不会占用这部分显存。

2. 713MB显存应该是`fluid.install_check.run_check();`时占用的，这个check中会跑一个非常简单的网络，只有一层Linear，这个网络本身的显存开销也不大。但是，因为使用CUDA跑，所以需要初始化CUDA本身的一些runtime，这些是713MB显存开销的主要原因。可以看下这个问题和回答：https://stackoverflow.com/questions/7146226/device-memory-for-cuda-kernel-code-is-it-explicitly-manageable。
