### ISSUE TITLE
我感觉文档有一个地方理解有问题

### ISSUE THREAD

**Issue by chengxurensheng666** [PaddlePaddle/Paddle#24758]
![image](https://user-images.githubusercontent.com/48110081/82965305-4c5c9e00-9ffa-11ea-8a72-e886d526720f.png)
这个im_info中的scale应该是指图像卷积完后的尺寸/输入时图像resize的固定尺寸。
但是我看了paddledetection源码和aistu上的案例，im_info都是输入时图像resize的固定尺寸/图像原来的尺寸，举一个例子
A=图像原来的尺寸：1320
B=输入时图像resize的固定尺寸：1300
C=图像卷积完后的尺寸：1300/16=86.25
![image](https://user-images.githubusercontent.com/48110081/82965322-567e9c80-9ffa-11ea-9aba-1b85f5535429.png)
![image](https://user-images.githubusercontent.com/48110081/82965327-59798d00-9ffa-11ea-902d-df328a37f252.png)

im_info文档中写的信息和你们实际的用法不一样
### **按照文档的意思是C/A，但是按照你们样例代码看就是B/A**

**Comment by wanghaoshuang** [comment]
是的，您的理解是对的。
中文文档表述不严谨，我们后续会修复这个中文文档。
