### ISSUE TITLE
Can not load two models in a single Python file.

### ISSUE THREAD

**Issue by helinwang** [PaddlePaddle/Paddle#2476]
<img width="555" alt="screen shot 2017-06-15 at 1 13 30 pm" src="https://user-images.githubusercontent.com/1724178/27199862-75b22d26-51cc-11e7-88a9-2bf88036ba9a.png">

The text in above image says when trying to load the second model, PaddlePaddle is trying to load from a file that has one extra underscore(`_`) in the front.

**Comment by reyoung** [comment]
There are two ways to inference Paddle model,

1. Use C-API. The documentation and example are [here](https://github.com/PaddlePaddle/Paddle/tree/develop/paddle/capi/examples/model_inference).

1. Use Python API. The API reference is [here](http://www.paddlepaddle.org/doc/api/v2/run_logic.html#inference) and the examples are in [book](https://github.com/PaddlePaddle/book) and [models](https://github.com/PaddlePaddle/models) repo. For example, here is an example for [image recognition](https://github.com/PaddlePaddle/book/blob/develop/02.recognize_digits/README.md#application).

Directly using low-level API, like `swig_paddle`, is not suggested.

**Comment by hxhlwf** [comment]
@reyoung  
Thanks for your reply，do you mean that we must use Paddle-V2 Interface?  I just use Paddle-V1 to train and predict.
