### ISSUE TITLE
conda安装paddle报错

### ISSUE THREAD

**Issue by sxthunder** [PaddlePaddle/Paddle#24760]
paddle版本：paddlepaddle-gpu          1.8.1.post97
linux版本：16.04
gpu：1080Ti*4
安装方式：https://www.paddlepaddle.org.cn/install/quick，系统选择ubuntu，安装方式选择conda，python版本选择3，cuda版本选择CUDA9，完全按照步骤依次操作。
cuda版本：9.0
cudnn版本：7.3.1
出错方式：运行paddle.fluid.install_check.run_check()报错。
错误信息
Running Verify Fluid Program ...
W0527 11:54:35.970010 41957 device_context.cc:252] Please NOTE: device: 0, CUDA Capability: 61, Driver API Version: 10.2, Runtime API Version: 9.0
W0527 11:54:35.975121 41957 device_context.cc:260] device: 0, cuDNN Version: 7.3.
/home/liangming/anaconda3/envs/paddle/lib/python3.6/site-packages/paddle/fluid/executor.py:1070: UserWarning: The following exception is not an EOF exception.
  "The following exception is not an EOF exception.")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/liangming/anaconda3/envs/paddle/lib/python3.6/site-packages/paddle/fluid/install_check.py", line 124, in run_check
    test_simple_exe()
  File "/home/liangming/anaconda3/envs/paddle/lib/python3.6/site-packages/paddle/fluid/install_check.py", line 120, in test_simple_exe
    exe0.run(startup_prog)
  File "/home/liangming/anaconda3/envs/paddle/lib/python3.6/site-packages/paddle/fluid/executor.py", line 1071, in run
    six.reraise(*sys.exc_info())
  File "/home/liangming/anaconda3/envs/paddle/lib/python3.6/site-packages/six.py", line 703, in reraise
    raise value
  File "/home/liangming/anaconda3/envs/paddle/lib/python3.6/site-packages/paddle/fluid/executor.py", line 1066, in run
    return_merged=return_merged)
  File "/home/liangming/anaconda3/envs/paddle/lib/python3.6/site-packages/paddle/fluid/executor.py", line 1154, in _run_impl
    use_program_cache=use_program_cache)
  File "/home/liangming/anaconda3/envs/paddle/lib/python3.6/site-packages/paddle/fluid/executor.py", line 1229, in _run_program
    fetch_var_name)
paddle.fluid.core_avx.EnforceNotMet:

--------------------------------------------
C++ Call Stacks (More useful to developers):
--------------------------------------------
0   std::string paddle::platform::GetTraceBackString<char const*>(char const*&&, char const*, int)
1   paddle::platform::EnforceNotMet::EnforceNotMet(std::__exception_ptr::exception_ptr, char const*, int)
2   paddle::platform::CUDAContext::InitCuDNNContext()
3   paddle::platform::CUDAContext::CUDAContext(paddle::platform::CUDAPlace const&, paddle::platform::stream::Priority const&)
4   paddle::platform::CUDADeviceContext::CUDADeviceContext(paddle::platform::CUDAPlace)
5   std::_Function_handler<std::unique_ptr<paddle::platform::DeviceContext, std::default_delete<paddle::platform::DeviceContext> > (), std::reference_wrapper<std::_Bind_simple<paddle::platform::EmplaceDeviceContext<paddle::platform::CUDADeviceContext, paddle::platform::CUDAPlace>(std::map<paddle::platform::Place, std::shared_future<std::unique_ptr<paddle::platform::DeviceContext, std::default_delete<paddle::platform::DeviceContext> > >, std::less<paddle::platform::Place>, std::allocator<std::pair<paddle::platform::Place const, std::shared_future<std::unique_ptr<paddle::platform::DeviceContext, std::default_delete<paddle::platform::DeviceContext> > > > > >*, paddle::platform::Place)::{lambda()#1} ()> > >::_M_invoke(std::_Any_data const&)
6   std::_Function_handler<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> (), std::__future_base::_Task_setter<std::unique_ptr<std::__future_base::_Result<std::unique_ptr<paddle::platform::DeviceContext, std::default_delete<paddle::platform::DeviceContext> > >, std::__future_base::_Result_base::_Deleter>, std::unique_ptr<paddle::platform::DeviceContext, std::default_delete<paddle::platform::DeviceContext> > > >::_M_invoke(std::_Any_data const&)
7   std::__future_base::_State_base::_M_do_set(std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> ()>&, bool&)
8   std::__future_base::_Deferred_state<std::_Bind_simple<paddle::platform::EmplaceDeviceContext<paddle::platform::CUDADeviceContext, paddle::platform::CUDAPlace>(std::map<paddle::platform::Place, std::shared_future<std::unique_ptr<paddle::platform::DeviceContext, std::default_delete<paddle::platform::DeviceContext> > >, std::less<paddle::platform::Place>, std::allocator<std::pair<paddle::platform::Place const, std::shared_future<std::unique_ptr<paddle::platform::DeviceContext, std::default_delete<paddle::platform::DeviceContext> > > > > >*, paddle::platform::Place)::{lambda()#1} ()>, std::unique_ptr<paddle::platform::DeviceContext, std::default_delete<paddle::platform::DeviceContext> > >::_M_run_deferred()
9   paddle::platform::DeviceContextPool::Get(paddle::platform::Place const&)
10  paddle::framework::GarbageCollector::GarbageCollector(paddle::platform::Place const&, unsigned long)
11  paddle::framework::UnsafeFastGPUGarbageCollector::UnsafeFastGPUGarbageCollector(paddle::platform::CUDAPlace const&, unsigned long)
12  paddle::framework::Executor::RunPartialPreparedContext(paddle::framework::ExecutorPrepareContext*, paddle::framework::Scope*, long, long, bool, bool, bool)
13  paddle::framework::Executor::RunPreparedContext(paddle::framework::ExecutorPrepareContext*, paddle::framework::Scope*, bool, bool, bool)
14  paddle::framework::Executor::Run(paddle::framework::ProgramDesc const&, paddle::framework::Scope*, int, bool, bool, std::vector<std::string, std::allocator<std::string> > const&, bool, bool)

----------------------
Error Message Summary:
----------------------
ExternalError:  Cudnn error, CUDNN_STATUS_INTERNAL_ERROR  at (/paddle/paddle/fluid/platform/device_context.h:165)

conda list信息：
_libgcc_mutex             0.1                        main    defaults
astor                     0.8.0                    py36_0    defaults
blas                      1.0                         mkl    defaults
ca-certificates           2020.1.1                      0    defaults
cairo                     1.14.12              h8948797_3    defaults
certifi                   2020.4.5.1               py36_0    defaults
cffi                      1.14.0           py36h2e261b9_0    defaults
chardet                   3.0.4                 py36_1003    defaults
cryptography              2.9.2            py36h1ba5d50_0    defaults
cudatoolkit               9.0                  h13b8566_0    defaults
cudnn                     7.3.1                 cuda9.0_0    defaults
cycler                    0.10.0                   py36_0    defaults
dbus                      1.13.14              hb2f20db_0    defaults
decorator                 4.4.2                      py_0    defaults
expat                     2.2.6                he6710b0_0    defaults
fontconfig                2.13.0               h9420a91_0    defaults
freetype                  2.9.1                h8a8886c_1    defaults
fribidi                   1.0.5                h7b6447c_0    defaults
funcsigs                  1.0.2                    pypi_0    pypi
gast                      0.3.3                      py_0    defaults
glib                      2.63.1               h5a9c865_0    defaults
graphite2                 1.3.13               h23475e2_0    defaults
graphviz                  2.40.1               h21bd128_2    defaults
gst-plugins-base          1.14.0               hbbd80ab_1    defaults
gstreamer                 1.14.0               hb453b48_1    defaults
harfbuzz                  1.8.8                hffaf4a1_0    defaults
icu                       58.2                 he6710b0_3    defaults
idna                      2.9                        py_1    defaults
intel-openmp              2020.1                      217    defaults
jpeg                      9b                   h024ee3a_2    defaults
kiwisolver                1.2.0            py36hfd86e86_0    defaults
ld_impl_linux-64          2.33.1               h53a641e_7    defaults
libedit                   3.1.20181209         hc058e9b_0    defaults
libffi                    3.2.1                hd88cf55_4    defaults
libgcc-ng                 9.1.0                hdf63c60_0    defaults
libgfortran-ng            7.3.0                hdf63c60_0    defaults
libpng                    1.6.37               hbc83047_0    defaults
libprotobuf               3.11.4               hd408876_0    defaults
libstdcxx-ng              9.1.0                hdf63c60_0    defaults
libtiff                   4.1.0                h2733197_0    defaults
libuuid                   1.0.3                h1bed415_2    defaults
libxcb                    1.13                 h1bed415_1    defaults
libxml2                   2.9.9                hea5a465_1    defaults
matplotlib                3.1.3                    py36_0    defaults
matplotlib-base           3.1.3            py36hef1b27d_0    defaults
mkl                       2020.1                      217    defaults
mkl-service               2.3.0            py36he904b0f_0    defaults
mkl_fft                   1.0.15           py36ha843d7b_0    defaults
mkl_random                1.1.0            py36hd6b4f25_0    defaults
ncurses                   6.2                  he6710b0_1    defaults
nltk                      3.4.5                    py36_0    defaults
numpy                     1.18.1           py36h4f9e942_0    defaults
numpy-base                1.18.1           py36hde5b4d6_1    defaults
objgraph                  3.4.1                    pypi_0    pypi
olefile                   0.46                     py36_0    defaults
openssl                   1.1.1g               h7b6447c_0    defaults
paddlepaddle-gpu          1.8.1.post97             pypi_0    pypi
pango                     1.42.4               h049681c_0    defaults
pathlib                   1.0.1                    py36_1    defaults
pcre                      8.43                 he6710b0_0    defaults
pillow                    7.1.2            py36hb39fc2d_0    defaults
pip                       20.0.2                   py36_3    defaults
pixman                    0.38.0               h7b6447c_0    defaults
prettytable               0.7                      pypi_0    pypi
protobuf                  3.11.4           py36he6710b0_0    defaults
py-cpuinfo                5.0.0                      py_0    defaults
pycparser                 2.20                       py_0    defaults
pyopenssl                 19.1.0                   py36_0    defaults
pyparsing                 2.4.7                      py_0    defaults
pyqt                      5.9.2            py36h05f1152_2    defaults
pysocks                   1.7.1                    py36_0    defaults
python                    3.6.10               hcf32534_1    defaults
python-dateutil           2.8.1                      py_0    defaults
pyyaml                    5.3.1            py36h7b6447c_0    defaults
qt                        5.9.7                h5867ecd_1    defaults
readline                  8.0                  h7b6447c_0    defaults
recordio                  0.1                      pypi_0    pypi
requests                  2.23.0                   py36_0    defaults
scipy                     1.4.1            py36h0b6359f_0    defaults
setuptools                46.4.0                   py36_0    defaults
sip                       4.19.8           py36hf484d3e_0    defaults
six                       1.14.0                   py36_0    defaults
sqlite                    3.31.1               h62c20be_1    defaults
tk                        8.6.8                hbc83047_0    defaults
tornado                   6.0.4            py36h7b6447c_1    defaults
urllib3                   1.25.8                   py36_0    defaults
wheel                     0.34.2                   py36_0    defaults
xz                        5.2.5                h7b6447c_0    defaults
yaml                      0.1.7                had09818_2    defaults
zlib                      1.2.11               h7b6447c_3    defaults
zstd                      1.3.7                h0b5b093_0    defaults

**Comment by sxthunder** [comment]
@JepsonWong 麻烦大佬看看

**Comment by gongweibao** [comment]
看上去是cudnn版本太低，能用高版本cudnn试试嘛？比如7.6
