### ISSUE TITLE
'tuple' object is not callable

### ISSUE THREAD

**Issue by Lieberk** [PaddlePaddle/Paddle#24769]
版本、环境信息：
飞浆平台jupyter环境高级版
   1）PaddlePaddle版本：PaddlePaddle 1.8.0
   2）GPU：Tesla V100 
   3）python3.7
训练信息
   1）单机 单卡
   2）显存信息 16GB

错误提示：![问题](https://user-images.githubusercontent.com/57614716/82996070-007c1a00-a037-11ea-8e55-2a95dfbade97.png)
问题位置![Uploading 出错点.png…]()
老师们看一下到底哪里出错了啊，很让人费解。

**Comment by gongweibao** [comment]
能不能贴一下代码，看不太清楚。
