### ISSUE TITLE
训练过程中需要获取lod信息

### ISSUE THREAD

**Issue by txy-cs** [PaddlePaddle/Paddle#24775]
- 版本、环境信息：
    1）PaddlePaddle版本：1.7
    2）GPU：Tesla V100 NVIDIA-SMI 410.79       Driver Version: 410.79       CUDA Version: 10.0 
    3）Centos Python3.6.5
- 训练信息
    1）单机 单卡
    2）显存信息
    3）Operator信息

有个疑问，如下代码：
seq_feature = fluid.layers.data(name='seq',dtype='float32',shape=[228], lod_level=1)
创建了如下输入后，想获取seq_feature的lod信息怎么获得。
尝试了.lod()等不奏效

**Comment by shaunhurryup** [comment]
参考下这个回答吧：
https://ai.baidu.com/forum/topic/show/960041

**Comment by nfmmm** [comment]
作者想问的问题跟我一样，是组网的时候怎么描述已经定义的lodtensor变量的lod信息

**Comment by kuke** [comment]
paddle 目前没有直接获取 lod 的 op，有一个办法，可以用 sequence_pad 对输入的 lod_tensor 进行 pad，该 op 的第二个返回即为 length，可以参考这里

https://www.paddlepaddle.org.cn/documentation/docs/zh/api_cn/layers_cn/sequence_pad_cn.html#cn-api-fluid-layers-sequence-pad
