### ISSUE TITLE
How to define multiple evaluator in v2 API

### ISSUE THREAD

**Issue by helinwang** [PaddlePaddle/Paddle#2477]
This is a question in Paddle user Hi Group. User mentioned in the v1 API, he can create multiple evaluators to calculate score. And he is wondering how can this be done in v2 API.

<img width="608" alt="screen shot 2017-06-15 at 1 19 28 pm" src="https://user-images.githubusercontent.com/1724178/27200089-46f2cc06-51cd-11e7-9873-868adc0a4cc0.png">

**Comment by reyoung** [comment]
In `paddle.v2` API, evaluator's results will store in the `metrics` argument in trainer's event handler. The `metrics` is a Python `dictionary`, every result of evaluators defined in the neural network will be stored in `metrics`. Different evaluator contains different keys.

You can use

```python
 print metrics
 print metrics.keys()
```
to access the evaluate results.

**Comment by lcy-seso** [comment]
Here is the example to use more than one evaluator:
https://github.com/PaddlePaddle/models/blob/develop/sequence_tagging_for_ner/ner.py#L177

**Comment by helinwang** [comment]
Closed due to inactivity, please feel free to reopen.
