### ISSUE TITLE
Inference result have big different when using same model but different GPU configuration.

### ISSUE THREAD

**Issue by helinwang** [PaddlePaddle/Paddle#2478]
User in Paddle Hi Group say that he gets big difference in inference result when using configuration "use_gpu=True, trainer_count=2, gpu_id=1" and "use_gpu=True, trainer_count=1, gpu_id=1".

<img width="571" alt="screen shot 2017-06-15 at 1 37 33 pm" src="https://user-images.githubusercontent.com/1724178/27200725-cf291a4c-51cf-11e7-894f-20ab893d9ad2.png">

**Comment by reyoung** [comment]
The `gpu_id` is used to select which GPU should be used. The `trainer_count` flag is used to select how many GPUs should be used. To set `trainer_count=2` but only set one GPU is used will lead to undefined behavior.

**Comment by hedaoyuan** [comment]
> big difference in inference result  

Is there any specific data to explain what's different? When `trainer_count = 2`, is the number of input samples greater than 2?

**Comment by bjkite** [comment]
text_classification_dnn.py，same test data：
 1. paddle.init(use_gpu=True, trainer_count=2, gpu_id=1)
[ 0.5  0.5] 1
[ 0.5  0.5] 0
[ 0.5  0.5] 1
[ 0.5  0.5] 0
[ 0.5  0.5] 1
[ 0.5  0.5] 0
[ 0.5  0.5] 1
[ 0.5  0.5] 0
[ 0.5  0.5] 1
[ 0.5  0.5] 0
[ 0.5  0.5] 1
[ 0.5  0.5] 0
[ 0.5  0.5] 1
[ 0.5  0.5] 0
[ 0.5  0.5] 1
[ 0.5  0.5] 0
[ 0.5  0.5] 1
[ 0.5  0.5] 0
[ 0.5  0.5] 1
[ 0.5  0.5] 0
[ 0.5  0.5] 1
[ 0.5  0.5] 0
[ 0.5  0.5] 1
[ 0.5  0.5] 0
[ 0.5  0.5] 1
[ 0.5  0.5] 0
[ 0.5  0.5] 1

2.paddle.init(use_gpu=True, trainer_count=1, gpu_id=1)
[ 0.47914657  0.5208534 ] 1
[ 0.96106547  0.03893453] 0
[ 0.77488256  0.22511747] 1
[ 0.39716244  0.60283762] 0
[ 0.00197576  0.99802423] 1
[ 0.68552697  0.31447309] 0
[ 0.01046917  0.9895308 ] 1
[ 0.91882282  0.08117715] 0
[ 0.17015688  0.82984316] 1
[ 0.7268514  0.2731486] 0
[ 0.00369131  0.99630862] 1
[  9.99511719e-01   4.88299993e-04] 0
[ 0.03564688  0.96435314] 1
[ 0.94584548  0.05415451] 0
[ 0.00168092  0.99831909] 1
[ 0.98435587  0.01564413] 0
[  9.90706030e-04   9.99009252e-01] 1
[ 0.51318157  0.48681852] 0
[ 0.00121559  0.99878448] 1
[ 0.9964174   0.00358259] 0
[ 0.02971029  0.97028977] 1
[ 0.40014613  0.59985393] 0
[ 0.00169606  0.99830389] 1
[ 0.74840277  0.25159726] 0
[ 0.00221406  0.99778593] 1
[ 0.74630308  0.25369692] 0
[ 0.05299001  0.94701004] 1
[ 0.48998147  0.51001859] 0
[ 0.29022992  0.70977008] 1
[ 0.94741881  0.05258116] 0
[ 0.00167667  0.99832326] 1

The reason of setting gpu_id=1 is that the 0,3 card is occupied. I found that the 1,3 card can be used by setting gpu_id=1.

**Comment by hedaoyuan** [comment]
> [ 0.5 0.5] 1

Is this the result of a binary classification?  Where the numbers in the brackets indicate the probability of inference for each category. And the numbers outside the brackets indicate which category the inference results are.

**Comment by helinwang** [comment]
Closed due to inactivity, please feel free to reopen.

**Comment by typhoonzero** [comment]
So then how to select gpus to use when using more than 1 gpu? like 

```python
paddle.init(use_gpu=True, trainer_count=2, gpu_id=[0,3])
```

**Comment by wanghaoshuang** [comment]
@typhoonzero 
You can run you script like this: `export CUDA_VISIBLE_DEVICES=0,3; python train.py`

**Comment by typhoonzero** [comment]
From @hedaoyuan 

> 0,3这样的目前不支持，只能是连续的，gpu_id是指起始id，比如比如`gpu_id=1, trainer_count=2`就是用1,2这两个GPU，原因是间隔的可能会遇到跨qpi的问题。另外，可以通过CUDA_VISIBLE_DEVICES来控制用哪几个gpu
