### ISSUE TITLE
使用深监督时反向传播出错

### ISSUE THREAD

**Issue by Willianwatch** [PaddlePaddle/Paddle#24780]
**- 版本、环境信息：**
    1）PaddlePaddle版本：1.7
    2）CPU：
    3）GPU：Tesla V100 
    4）系统环境：AI Studio
- 训练信息
    1）单机，单卡
    2）显存信息 16G
**- 复现信息：**
损失函数：
def tversky(predict, label):
    predict = fluid.layers.sigmoid(predict)
    predict = predict >= 0.5
    predict = fluid.layers.cast(predict, "int32")
    label = fluid.layers.cast(label, "int32")
    true_pos = fluid.layers.reduce_sum(label * predict)
    false_neg = fluid.layers.reduce_sum(label * (1 - predict))
    false_pos = fluid.layers.reduce_sum((1 - label) * predict)

    true_pos = fluid.layers.cast(true_pos, "float32")
    false_neg = fluid.layers.cast(false_neg, "float32")
    false_pos = fluid.layers.cast(false_pos, "float32")
    alpha = 0.7
    smooth = 1.0
    return (true_pos + smooth) / (true_pos + alpha * false_neg + (1 - alpha) * false_pos + smooth)

def tversky_loss(predict, label):
    return 1 - tversky(predict, label)

def focal_tversky_loss(predict, label):
    pt_1 = tversky(predict, label)
    gamma = 0.75
    return fluid.layers.pow((1 - pt_1), gamma)

def deep_supervised_focal_tversky_loss(predict, label):
    logits0, logits1, logits2, logits3 = predict
    label3 = label
    label2 = fluid.layers.resize_nearest(label3, scale=0.5, align_corners=False)
    label1 = fluid.layers.resize_nearest(label2, scale=0.5, align_corners=False)
    label0 = fluid.layers.resize_nearest(label1, scale=0.5, align_corners=False)
    loss0 = focal_tversky_loss(logits0, label0)
    loss1 = focal_tversky_loss(logits1, label1)
    loss2 = focal_tversky_loss(logits2, label2)
    loss3 = focal_tversky_loss(logits3, label3)
    return fluid.layers.reduce_mean(loss0 + loss1 + loss2 + loss3)
模型定义（输出部分）：
    ...
    out1 = self.out_block1(up1)
    out2 = self.out_block2(up2)
    out3 = self.out_block3(up3)
    out4 = self.out_block4(up4)
    return out1, out2, out3, out4
使用模型和损失函数：
    predicted_train_masks = model(train_imgs)
    train_avg_loss = deep_supervised_focal_tversky_loss(predicted_train_masks, train_masks)
    train_avg_loss.backward()

**- 问题描述：请详细描述您的问题，同步贴出报错信息、日志、可复现的代码片段**
2020-05-27 16:44:14,149-INFO: Strart training:
2020-05-27 16:44:14,149-INFO: Using device GPU
2020-05-27 16:44:14,149-INFO: Epochs:      100
2020-05-27 16:44:14,149-INFO: Batch size:  8
W0527 16:44:14.929246  1369 device_context.cc:237] Please NOTE: device: 0, CUDA Capability: 70, Driver API Version: 9.2, Runtime API Version: 9.0
W0527 16:44:14.933475  1369 device_context.cc:245] device: 0, cuDNN Version: 7.3.
2020-05-27 16:44:16,348-INFO: Network:
	1 input channels
	2 output channels (classes)
	Bilinear upscaling
---> train round
epoch: 0, batch: 0, loss is: [3.7218707], mean IoU is: [0.10470868]
Traceback (most recent call last):
  File "train.py", line 81, in <module>
    train_avg_loss.backward()
  File "</opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/decorator.py:decorator-gen-60>", line 2, in backward
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
    return wrapped_func(*args, **kwargs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/framework.py", line 207, in __impl__
    return func(*args, **kwargs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/varbase_patch_methods.py", line 116, in backward
    self._run_backward(backward_strategy, framework._dygraph_tracer())
paddle.fluid.core_avx.EnforceNotMet: 

--------------------------------------------
C++ Call Stacks (More useful to developers):
--------------------------------------------
0   std::string paddle::platform::GetTraceBackString<std::string>(std::string&&, char const*, int)
1   paddle::platform::EnforceNotMet::EnforceNotMet(paddle::platform::ErrorSummary const&, char const*, int)
2   paddle::imperative::TensorAdd(paddle::framework::Variable const&, paddle::framework::Variable*)
3   paddle::imperative::VarBaseAdd(std::shared_ptr<paddle::imperative::VarBase>, paddle::imperative::VarBase*)
4   paddle::imperative::EagerGradientAccumulator::Add(std::shared_ptr<paddle::imperative::VarBase>, unsigned long)
5   paddle::imperative::BasicEngine::SumGradient(paddle::imperative::OpBase*, std::shared_ptr<paddle::imperative::VarBase>, paddle::imperative::VarBase*)
6   paddle::imperative::BasicEngine::Execute()

----------------------
Error Message Summary:
----------------------
Error: Not supported data type int for AddTo at (/paddle/paddle/fluid/imperative/gradient_accumulator.cc:104)

**Comment by gongweibao** [comment]
你贴的代码已经完成失去代码结构了，基本没法看。。。
用
```
代码
```
可以保持代码、日志结构。

从报错上看，https://github.com/PaddlePaddle/Paddle/blob/release/1.7/paddle/fluid/imperative/gradient_accumulator.cc#L103
函数目前只支持float和double数据类型。
