### ISSUE TITLE
C++预测

### ISSUE THREAD

**Issue by dgl547437235** [PaddlePaddle/Paddle#24796]
为使您的问题得到快速解决，在建立Issue前，请您先通过如下方式搜索是否有相似问题:【搜索issue关键字】【使用labels筛选】【官方文档】

如果您没有查询到相似问题，为快速解决您的提问，建立issue时请提供如下细节信息：
- 标题：简洁、精准描述您的问题，例如“最新预测库的API文档在哪儿 ”
- 版本、环境信息：
    1）PaddlePaddle版本：请提供您的PaddlePaddle版本号（如1.1）或CommitID
    2）CPU：预测若用CPU，请提供CPU型号，MKL/OpenBlas/MKLDNN/等数学库使用情况
    3）GPU：预测若用GPU，请提供GPU型号、CUDA和CUDNN版本号
    4）系统环境：请您描述系统类型、版本（如Mac OS 10.14），Python版本
-预测信息
    1）C++预测：请您提供预测库安装包的版本信息，及其中的version.txt文件
    2）CMake包含路径的完整命令
    3）API信息（如调用请提供）
    4）预测库来源：官网下载/特殊环境（如BCLOUD编译）
- 复现信息：如为报错，请给出复现环境、复现步骤
- 问题描述：请详细描述您的问题，同步贴出报错信息、日志/代码关键片段

Thank you for contributing to PaddlePaddle.
Before submitting the issue, you could search issue in the github in case that th
If there is no solution,please make sure that this is an inference issue including the following details :
**System information**
-PaddlePaddle version （eg.1.1）or CommitID
-CPU: including CPUMKL/OpenBlas/MKLDNN version
-GPU: including CUDA/CUDNN version
-OS Platform (eg.Mac OS 10.14)
-Python version
-Cmake orders
-C++version.txt
-API information
**To Reproduce**
Steps to reproduce the behavior
**Describe your current behavior**
**Code to reproduce the issue**
**Other info / logs**

**Comment by dgl547437235** [comment]
version信息为：
GIT COMMIT ID: 
WITH_MKL: OFF
WITH_MKLDNN: OFF
WITH_GPU: OFF
CXX compiler version: 19.16.27039.0

我在windows下使用vs2017编译推断部分，再使用编译完的lib库进行推断，在推断时出现如下的错误信息
“严重性	代码	说明	项目	文件	行	禁止显示状态
错误	LNK2038	检测到“_ITERATOR_DEBUG_LEVEL”的不匹配项: 值“0”不匹配值“2”(source.obj 中)	Project1	C:\Users\dugeliang\source\repos\Project1\Project1\libpaddle_fluid.lib(ddim.obj)	1	
”

**Comment by dgl547437235** [comment]
另外cpu型号是i5-6500，cmka时是使用cmake-gui

**Comment by guoshengCS** [comment]
> 错误 LNK2038 检测到“_ITERATOR_DEBUG_LEVEL”的不匹配项: 值“0”不匹配值“2”

搜索查了下这个报错是可能是由于当前工程是Debug版本，而引用的库文件时Release版本，可否试下将您当前工程的Debug模式改成Release模式

**Comment by dgl547437235** [comment]
![wrong](https://user-images.githubusercontent.com/31400928/83386090-000bc680-a41d-11ea-923c-1371ca2ba806.png)
你好，当前工程和引用得库文件都是release版本

**Comment by guoshengCS** [comment]
可否进一步查看下是否是这个 https://www.cnblogs.com/lisuyun/p/6410393.html 中提到的多线程调试的原因呢
<img width="968" alt="image" src="https://user-images.githubusercontent.com/14105589/83390447-73650680-a424-11ea-863d-3822a5e8aa6c.png">

**Comment by dgl547437235** [comment]
![MDD](https://user-images.githubusercontent.com/31400928/83396430-8b418800-a42e-11ea-9c12-2ae7b6369b8d.png)
![MD](https://user-images.githubusercontent.com/31400928/83396435-8d0b4b80-a42e-11ea-80cf-b8badb330dab.png)
![MT](https://user-images.githubusercontent.com/31400928/83396437-8da3e200-a42e-11ea-8045-a832eb4b0646.png)
![MTD](https://user-images.githubusercontent.com/31400928/83396439-8e3c7880-a42e-11ea-8d00-916df8b3f50b.png)
你好，我将4种配置都试了一遍，都有相关的问题，如图

**Comment by Channingss** [comment]
@dgl547437235 请问这是PaddleDetection的部署模块吗？如果是的话，建议使用最新版本的https://github.com/PaddlePaddle/PaddleDetection/tree/release/0.3/deploy/cpp
