### ISSUE TITLE
CMake issue

### ISSUE THREAD

**Issue by pmajchrzak** [PaddlePaddle/Paddle#24806]
Can't build PaddlePaddle on machine witchout NVIDIA (Only CPU) 
This is blocking issue for us
Used parameters:
```
CMAKE_FLAGS:
   CMAKE_BUILD_TYPE=Release 
   WITH_GPU=OFF 
   WITH_MKLDNN=ON 
   WITH_TESTING=ON 
   WITH_PROFILER=ON 
   WITH_STYLE_CHECK=OFF 
   ON_INFER=ON 
   WITH_INFERENCE_API_TEST=ON

OS_DISTRIBUTION=ubuntu-16_04_mkldnn
```
This problem appears after commit: d1047d0a699689724e037f944f205fbeca7ab1fb
and was mentioned and discussed also there: https://github.com/PaddlePaddle/Paddle/commit/d1047d0a699689724e037f944f205fbeca7ab1fb 

Error message:
```
CMake Error at cmake/inference_lib.cmake:217 (add_dependencies):
  The dependency target "cuda_error_proto" of target "fluid_lib_dist" does
  not exist.
Call Stack (most recent call first):
  CMakeLists.txt:211 (include)
```

**Comment by luotao1** [comment]
#24800 is fixing this issue by @zhouwei25
