### ISSUE TITLE
paddledetection maskrcnn anchor size需求

### ISSUE THREAD

**Issue by achao2013** [PaddlePaddle/Paddle#24808]
maskrcnn得backbone出来的4个层次featuremap，每个特征层只能产生一种anchor size吗，我想设置多个怎么设置，大多数检测任务都需要。

**Comment by jerrywgz** [comment]
https://github.com/PaddlePaddle/PaddleDetection/blob/release/0.3/ppdet/modeling/anchor_heads/rpn_head.py#L355 如果使用的是fpn结构的话，每个feature map得到的anchor size确实只有一种，可以在这里对anchor_generator做修改来得到不同的anchor size，具体的使用方式可以参考https://www.paddlepaddle.org.cn/documentation/docs/zh/2.0-alpha/api_cn/layers_cn/anchor_generator_cn.html

**Comment by achao2013** [comment]
可以不用fpn，但得用rpn，可以每层featuremap多个anchor size吗 @jerrywgz

**Comment by jerrywgz** [comment]
如果不是用fpn只用rpn的话，anchor的获取方式是通过backbone最后一层feature map来得到多个anchor size，https://github.com/PaddlePaddle/PaddleDetection/blob/release/0.3/configs/mask_rcnn_r50_1x.yml#L34 这里是具体mask rcnn中的配置方式。如果说是希望通过从不同feature map上取得不同size的anchor，可能需要修改下源码，这里是生成anchor的逻辑https://github.com/PaddlePaddle/PaddleDetection/blob/release/0.3/ppdet/modeling/anchor_heads/rpn_head.py#L69
