### ISSUE TITLE
windows C++预测库开启TRT模式并设置use_static报错

### ISSUE THREAD

**Issue by cyanjustice** [PaddlePaddle/Paddle#24807]
PaddlePaddle版本：1.8
GPU：RTX2080TI,CUDA10.0,CUDNN7.5
系统环境：WINDOWS10,VS2017,C++
使用config.EnableTensorRtEngine命令，设置use_static为true报错如下：
![image](https://user-images.githubusercontent.com/46018705/83233573-7ca26900-a1c1-11ea-83fa-c2ebc004bd5f.png)
应该是保存文件夹名与模型名冲突了，但EnableTensorRtEngine函数没看到设置保存路径的参数。

**Comment by wanghaoshuang** [comment]
应该是您对目标路径没有写权限，建议您修改下路径权限。

**Comment by cyanjustice** [comment]
目标路径是我的模型路径，已经有__model__的模型文件了，这个函数尝试在这个路径中建立__model__文件夹肯定会报错。现在问题是我没有办法修改这个目标路径。

**Comment by NHZlX** [comment]
看log你是没有权限呀，将你的模型整个目录放到有权限的目录下

**Comment by cyanjustice** [comment]
应该不是权限问题，D盘不是我的系统盘，而且E,F盘都试过了，同样报错，并且VS是使用管理员模式打开的。
