### ISSUE TITLE
数据格式为NHWC时，batch_norm_grad op报错

### ISSUE THREAD

**Issue by sandyhouse** [PaddlePaddle/Paddle#24803]
使用混合精度训练，报如下错误。
----------------------
Error Message Summary:
----------------------
Error: Tensor holds no memory. Call Tensor::mutable_data first.
  [Hint: holder_ should not be null.] at (/home/Paddle/paddle/fluid/framework/tensor.cc:23)
  [operator < batch_norm_grad > error]

根据源码定位了一下，初步确定原因是当数据格式为NHWC时，ResizeToChannelFirst函数（batch_norm_op.h)没有处理input dim size=2的情形，导致transformed_x没有调用mutable_data。
例如，当fc层后面接batch_norm层时，会导致batch_norm_grad op的输入X的input dim size=2.

初步定位是上面原因，但不确定是否是导致报错的最终原因。请OP负责人确认并修复，谢谢。

**Comment by ceci3** [comment]
你好，麻烦贴下可复现代码
