### ISSUE TITLE
官方有BiLSTM-CRF实现的代码样例吗

### ISSUE THREAD

**Issue by GentleCP** [PaddlePaddle/Paddle#24818]
因为最近在尝试用MSRA数据集做命名实体识别，想用BiLSTM+CRF模型，网上的资料大多是tensorflow和pytorch的，paddle官网也没有找到相关的实现样例。不知能否提供一下作为学习。

**Comment by phlrain** [comment]
https://github.com/PaddlePaddle/models/tree/release/1.8/dygraph/lac 

我们有一个分词工具是基于上述模型的说的
