### ISSUE TITLE
如何在程序中手动释放inference model和占用的显存？

### ISSUE THREAD

**Issue by zhizunbao-y** [PaddlePaddle/Paddle#24815]
工程中使用到了pytorch和paddle两个模型，在切换过程中，paddle的inference model引用设为None后，模型显存仍在被占用，导致pytorch模型没有足够的显存加载，请问有什么解决办法？

**Comment by Superjomn** [comment]
目前应该没法彻底清除

inference 里面是进程级的 memory pool，用于多线程下的内存复用，单独退出 memory pool 还会存在。 除非用进程启动 inference，之后单独kill 掉进程。

**Comment by Superjomn** [comment]
我们下个版本可以加个支持的接口，之前的确没怎么遇到手动释放的需求。

**Comment by zhizunbao-y** [comment]
感谢

**Comment by xiangjun2** [comment]
1.8.4版本仍没有找到先关接口
