### ISSUE TITLE
NLP项目组网时候lod_level>1的lodtensor变量如何描述剔除某一层lod信息的变量

### ISSUE THREAD

**Issue by nfmmm** [PaddlePaddle/Paddle#24814]
组网的时候定义了x = fluid.layers.data(name='x', shape=[6], lod_level=2)，
如何通过x获得变量y，y是x剔除了某一层lod信息的变量，好像没找到有现成的接口函数。大家有遇到这个问题吗，lod_reset和lod_append都需要输入lod信息。

**Comment by nfmmm** [comment]
其实想问的就是有没有给lodtensor删除lod信息的接口，就是lod_append反过来的操作。

**Comment by Superjomn** [comment]
lod_tensor 应该直接可以当成 tensor 来用
另外，可以试试，`lod_reset(x,target_lod=[])` 

https://www.paddlepaddle.org.cn/documentation/docs/zh/api_cn/layers_cn/lod_reset_cn.html#lod-reset

**Comment by nfmmm** [comment]
InvalidArgumentError: If Input(Y) is not provided, the output's LoD should be specified by attribute 'target_lod'. But the size of 'target_lod' is 0.
  [Hint: Expected static_cast<int64_t>(level0.size()) > 0, but received static_cast<int64_t>(level0.size()):0 <= 0:0.] at (D:\1.8.1\paddle\paddle\fluid\operators\lod_reset_op.cc:37)
  [operator < lod_reset > error]

**Comment by nfmmm** [comment]
> lod_tensor 应该直接可以当成 tensor 来用
> 另外，可以试试，lod_reset(x,target_lod=[])
> https://www.paddlepaddle.org.cn/documentation/docs/zh/api_cn/layers_cn/lod_reset_cn.html#lod-reset

我试了，不行。
InvalidArgumentError: If Input(Y) is not provided, the output's LoD should be specified by attribute 'target_lod'. But the size of 'target_lod' is 0.
[Hint: Expected static_cast<int64_t>(level0.size()) > 0, but received static_cast<int64_t>(level0.size()):0 <= 0:0.] at (D:\1.8.1\paddle\paddle\fluid\operators\lod_reset_op.cc:37)
[operator < lod_reset > error]
