### ISSUE TITLE
希望保存训练中间状态，支持断点启动及增量训练

### ISSUE THREAD

**Issue by wangsouc** [PaddlePaddle/Paddle#2482]
增量训练在线学习的一个主要问题是程序不稳定，需要断点启动
希望saved中间状态，paddle支持加载saved状态然后继续训练；

**Comment by jacquesqiao** [comment]
ok, in progress

**Comment by typhoonzero** [comment]
功能开发会在Fluid版本中迭代。
暂时关闭此Issue了，如果仍存在问题，可以reopen。
