### ISSUE TITLE
PyReader的next方法报错

### ISSUE THREAD

**Issue by HuangLK** [PaddlePaddle/Paddle#24829]
- 版本、环境信息：
    1）PaddlePaddle版本：1.6.1
    2）CPU/GPU：CPU
    3）系统环境：Linux/Centor 6.3
    4）Python版本号：3.7
- 复现信息：
代码逻辑：
```python
# define reader
reader = fluid.io.PyReader(
        feed_list=[word, target], capacity=batch_size, iterable=True, return_list=False)
reader.decorate_sample_list_generator(batch_reader, places=places)

# train
data_loader = reader()
next(data_loader)  # 拿一个batch的数据
```

- 问题描述：

![image](https://user-images.githubusercontent.com/3390197/83389892-790e1c80-a423-11ea-8c04-ac93a7c85335.png)

**Comment by HuangLK** [comment]
[文档](https://www.paddlepaddle.org.cn/documentation/docs/zh/1.6/api_cn/io_cn/PyReader_cn.html#next)说“*用户不应直接调用此方法*”是指“不推荐”还是“不能用”？

**Comment by HuangLK** [comment]
@sneaxiy 麻烦解答下

**Comment by chenwhql** [comment]
> [文档](https://www.paddlepaddle.org.cn/documentation/docs/zh/1.6/api_cn/io_cn/PyReader_cn.html#next)说“_用户不应直接调用此方法_”是指“不推荐”还是“不能用”？

是指“不能用”，这个文档不应该向用户暴露，我们后续修复下

如果需要获得下一批数据，可以改成这么写：
```
# train
it = reader.__iter__()
it.next()  # 拿一个batch的数据
```

**Comment by HuangLK** [comment]
@chengduoZH  按照你的方法可以了，谢谢解答。
