### ISSUE TITLE
训练中在使用paddle.fluid.layers.reduce_sum接口时候经常会出现nan

### ISSUE THREAD

**Issue by BeyondYourself** [PaddlePaddle/Paddle#24827]
在使用paddle.fluid.layers.reduce_sum（x)时候，结果经常出现nan，最终导致程序终止，其中x参数类型为float，其他参数都作为默认参数设置，reduce_sum计算中应该忽略nan的数据还是需要跳过结果为nan的数据，请教大神指导

**Comment by phlrain** [comment]
reduce sum 目前无法忽略nan的数据
