### ISSUE TITLE
神经网络的计算图应当包含什么?

### ISSUE THREAD

**Issue by reyoung** [PaddlePaddle/Paddle#2483]
除去PyTorch框架外，Tensorflow,MxNet,Caffe2与DyNet均显示的让用户配置计算图(`Graph`)，并且使用执行引擎(`Engine`)执行该计算图。而Paddle目前也是使用`proto::ModelConfig`来表示计算图。

在一个Op Based神经网络框架的计算图中，计算图通常包括`Variable`与`Op`。`Variable`表示计算图中所有的数据节点，而`Op`表示计算图中所有的计算节点。不同神经网络框架对二者的称谓如下:

|  | Variable | op |
| --- | --- | --- |
| Caffe2 | Blob | `OperatorDef` |
| Tensorflow (需要更详细调研)|  TBD | `NodeDef` |
| MxNet (需要更详细调研)| Symbol(Variable) | Symbol(Functor) |
| DyNet | Node(InputNode, ScalarInputNode, ParameterNode) | Node |

可见，计算图中`Variable`和`Op`都是计算图的节点(`Node`)，而计算图之间的关系通过`Node`之间的连接组成的。即，计算图是一个图，图包含节点与边构成。而`Variable`和`Op`都是计算图的节点(`Node`)。

逻辑关系如下图所示

![alt](http://api.paddlepaddle.org/graphviz?dot=https://gist.githubusercontent.com/reyoung/f7214f8b41a4a30322a26005aaef9dca/raw/985487218d5b3f1e50b65403463b13acb8798528/graph.comp.dot)

## 问题:

1. 神经网络的计算图是图，一个图由节点和边构成，`Op`和`Variable`是计算图中的节点，还是边？什么是这个计算图中的节点?什么是这个计算图中的边?
1. Paddle重构中，是否`Variable`与`Op`配置的基类应该是`Node`，而Graph是`Node`的集合与连接关系?
1. Paddle重构中，是否`Variable`就是一种`Op`，只是这个`Op`没有输入，可以直接产生输出？或者，通用的说，类似于DyNet的设计，所有的节点都是`Node`，只是`Op`实现了计算，而`Variable`实现了从全局的查找一个`Tensor`输出?

**Comment by hedaoyuan** [comment]
> 是否Variable与Op配置的基类应该是Node，而Graph是Node的集合？

计算图仅仅表示Node的集合是不够的，要能够表示出Variable之间的链接关系。
可以把Variable看成是节点，Op看成是链接Variable的边，整个计算是Output Variable到Output Variable。

**Comment by reyoung** [comment]
> 计算图仅仅表示Node的集合是不够的，要能够表示出Variable之间的链接关系。
可以把Variable看成是节点，Op看成是链接Variable的边，整个计算是Output Variable到Output Variable。

有道理，已经补充

**Comment by QiJune** [comment]
### 计算图表示
神经网络的本质是一个计算图，那么图就有节点与边，所以需要清晰的定义什么是节点，什么是边。在计算图中，节点里面放置的就是(需要被计算的)数据块；而边描述的是数据块之间的计算关系。请注意，这里的数据块实际上也包括反向计算过程中的gradient数据。

这个边是有向边，方向表示数据块之间的依赖关系，即当前的数据块必须由前一个(或几个)数据块计算得到。而当前数据块的具体计算过程，是在拿到其依赖的数据块之后；因此，我们可以认为具体计算的方法是绑定在当前数据块上面的。

总结如下：

**节点**：包含了数据块，以及计算得到该数据块的计算方法

**边**：节点之间的连接关系。可以用指针表示，每个节点包含若干个指向依赖节点与被依赖节点的指针；或者用整数来表示，即每个节点都给一个整数的唯一id，每个节点需要包含依赖节点与被依赖节点的id

具体的代码描述如下（节点中的data_是由input计算得到的）：

- 用指针来表示边：

```
struct Node;
typedef NodePtr = std::shared_ptr<Node>;

struct Node {
  void compute(std::vector<Blob> input);
  
  Blob data_;
    
  std::vector<NodePtr> children_;
  std::vector<NodePtr> parents_; 
};
```

- 用整数来表示边:

```
struct Node {
  void compute(std::vector<Blob> input);
  
  Blob data_;  
  int id_;
  
  std::vector<int> children_;
  std::vector<int> parents_;
};
```

### 计算图执行
请注意，在**Step 1**中我们认为每个节点中只包含计算得到当前节点数据块的计算方法。

而实际一个Operator中的计算方法，往往是从若干个输入，计算得到若干个输出。也就是说，在**Step 1**中可能若干个节点是有紧密联系的(通常是在gradient反向传播过程中)，它们共同依赖于相同的父节点，并且计算方法也可以共享一个。

Operator不是节点。

计算图的执行阶段是执行描述完毕的计算图，执行引擎需要考虑可以一次性同时计算若干个有紧密关系的节点的情况。

因此，计算图的执行引擎需要根据之前定义得到的计算图，以及Operator中描述的计算方法，来对执行计算过程。

**Comment by reyoung** [comment]
## DyNet计算图详细信息

### 论点1，DyNet的计算图中，Variable和Op都是计算图的节点

DyNet的计算图为[`ComputationGraph`](https://github.com/clab/dynet/blob/master/dynet/dynet.h#L80)类。其中无论是用户的输入，神经网络的参数，还是具体的计算Op都保存在一个[`std::vector<Node*>`](https://github.com/clab/dynet/blob/master/dynet/dynet.h#L425)的数组中，即他们都是计算图的一个节点。

论据:
* [graph.add_input](https://github.com/clab/dynet/blob/v1.0-rc1/dynet/dynet.cc#L134)
* [graph.add_parameters](https://github.com/clab/dynet/blob/v1.0-rc1/dynet/dynet.cc#L148)
* [graph.add_function](https://github.com/clab/dynet/blob/v1.0-rc1/dynet/dynet.h#L216)

### 论点2，DyNet中，节点间的输入输出关系，是计算图的边

在`Node`基类中，记录了变量[`std::vector<VariableIndex> args`](https://github.com/clab/dynet/blob/v1.0-rc1/dynet/dynet.h#L191)，其中`VariableIndex`是一个size_t的typedef。这个`args`记录了当前节点的各个输入，是`vector<Node*> ComputationGraph::nodes`数组的偏移。`args`变量记录了一个计算图中，每一个Node的输入是哪些其他的Node，也就是记录下了计算图的边。

当执行引擎执行[前向](https://github.com/clab/dynet/blob/v1.0-rc1/dynet/exec.cc#L61)和反向计算时，执行引擎负责将`VariableIndex`转换成计算用的`Tensor`。

### 相关问题1，计算图如何获取用户的输入，进行计算?

`InputNode`表示计算图中不需要训练的输入。用户的输入数据，和不需要更新的参数都使用`InputNode`表示。

用户构造`InputNode`的时候，将输入数据通过[构造函数传入](https://github.com/clab/dynet/blob/v1.0-rc1/dynet/param-nodes.h#L34)。用户可以传入一个`std::vector<float>`的指针，进而每一个mini-batch的时候，修改对应的`std::vector<float>`即可以完成新数据的载入。

* [代码地址](https://github.com/clab/dynet/blob/95cac6bdb63b7e20f1402be6be7b15848744302d/python/_dynet.pyx#L777)


### 相关问题2，多个计算图如何共享参数?

因为参数节点也是计算图的一部分，所以有多个计算图如何共享同一个参数的问题。

`ParameterNode`的构造函数是以[`Parameter`](https://github.com/clab/dynet/blob/95cac6bdb63b7e20f1402be6be7b15848744302d/dynet/param-nodes.h#L16)的参数，而DyNet的`Parameter`通过[`Model`](https://github.com/clab/dynet/blob/95cac6bdb63b7e20f1402be6be7b15848744302d/examples/python/xor.py#L9)创建。在DyNet中，Model并不包含神经网络的拓扑结构，而只有参数。所以更像是paddle的`Parameters`概念。

总结起来看，计算图中的`ParameterNode`是通过`Parameter`来创建的，而`Parameter`由`Model`管理，`Model`可以被多个计算图使用。所以可以完成参数的共享。

**Comment by hedaoyuan** [comment]
> 其中无论是用户的输入，神经网络的参数，还是具体的计算Op都保存在一个std::vector<Node*>的数组中，即他们都是计算图的一个节点。
> 每一个Node的输入是哪些其他的Node，也就是记录下了计算图的边。

这里的意思是一共有三种Node（输入，参数，Op）？这里的输入和参数都是指的一块内存数据是吗？
那第二句话中的`Node的输入是其他的Node`，这里
- 如果Op Node的输入是（输入Node或参数Node）；这个好理解
- 如果参数Node的输入是OP Node；应该是理解成参数Node的输入是OpNode的计算结果这样？
- Op Node的输入可以是OpNode吗？
....

**Comment by reyoung** [comment]
> 这里的意思是一共有三种Node（输入，参数，Op）？这里的输入和参数都是指的一块内存数据是吗？

DyNet中没有显示的三种子类，大家都继承自`Node`。

但是，三者有一些区别:

* DyNet中分两个文件记录所有的Node，他们是[`nodes.h`](https://github.com/clab/dynet/blob/v1.0-rc1/dynet/nodes.h)和[`param-nodes`](https://github.com/clab/dynet/blob/v1.0-rc1/dynet/param-nodes.h)。`nodes`里面是所有的计算节点。`param-nodes`里面是所有的参数节点和输入节点。
* `param-nodes`中的参数和输入节点，他们的特点是前向的时候不接受任何数据。参数节点和输入节点的区别是:
   * 参数节点继承自[`ParameterNodeBase`](https://github.com/clab/dynet/blob/v1.0-rc1/dynet/param-nodes.h#L10)，具有合并梯度的接口。可以`accumulate_grad`。

> 如果参数Node的输入是OP Node；应该是理解成参数Node的输入是OpNode的计算结果这样？

参数Node没有输入

> Op Node的输入可以是OpNode吗？

可以。而且很常见。一个Op的输入是另一个OpNode，这表示该Op的输入是另一个OpNode的输出。

**Comment by Canpio** [comment]
说一点个人的理解。
如果一定要用节点和边的角度来理解计算图的话，因为计算图其实是对op的有序排列，那么应该op是节点。边应该用来表示op之间的依赖关系（“依赖关系”指的是“执行A之前必须要先执行B”这样的逻辑），而op之间之所以会产生依赖关系，其实是因为数据上的依赖。例如，opA需要一块数据，而这块数据是opB的产出，因此opA就对opB产生了依赖。所以计算图的边应该是数据，也就是blob。

**Comment by hedaoyuan** [comment]
关于那个`Node的输入是其他的Node`还有其他组合吗？

**Comment by reyoung** [comment]
## Caffe2的计算图的详细信息

### 论点1，caffe2的计算图中只有Op，没有Variable。

![image](https://user-images.githubusercontent.com/728699/27216266-91af4c8a-52a7-11e7-9d57-1ffe2864bcb5.png)

在Caffe2的计算图[`NetDef`](https://github.com/caffe2/caffe2/blob/v0.7.0/caffe2/proto/caffe2.proto#L166)中，只记录了所有的`op`，没有记录`Variable`。

而在[`OperatorDef`](https://github.com/caffe2/caffe2/blob/v0.7.0/caffe2/proto/caffe2.proto#L132)中，Op的输入和输出都是字符串类型。这些字符串都是`Workspace`中的一个key。`Workspace`是一个[map](https://github.com/caffe2/caffe2/blob/v0.7.0/caffe2/core/workspace.h#L216)，这个map是字符串到内存块(Blob,常见情况是Tensor)的映射。

所以，Caffe2中计算图和`Workspace`形成了一种互补关系。

### 论点2, caffe2的计算图的边，是输入输出的名字

在[`OperatorDef`](https://github.com/caffe2/caffe2/blob/v0.7.0/caffe2/proto/caffe2.proto#L132)中，每一个Op都设置了输入输出名字。每一个名字都指代了`Workspace`的不同内存。不同Op间，通过使用相同的名字表示连接关系。

故，caffe2计算图的边，是输入输出的名字。

### 问题1. Caffe2的`Workspace`角色较多，`Variable`的概念不明晰

`Workspace`既表示了一个统一的内存管理，类似于`paddle::Parameters`和DyNet的`Model`，又还有执行逻辑[`Run`](https://github.com/caffe2/caffe2/blob/v0.7.0/caffe2/core/workspace.h#L176)。一个类型负担了很多工作。

在Caffe2的计算图定义中，没有Variable的概念，也缺乏了每一个`Variable`的`dims_`。所以检查用户配置的合法性，shape的推导都发生在了执行过程中。于是用户配置错误的报错时机比较晚。

在Caffe2中shape推导的检查就是可选操作。并且Caffe2设计了一套Lazy初始化内存的机制，保证在shape推导，合法性检查的时候，不去申请内存。仅仅在计算发生的时候申请内存。

神经网络的计算图中，总是需要有`Variable`的，否则数据块的属性(数据类型，float还是int，维度信息，设备信息)很难描述。Caffe2将描述`Variable`的任务交由`Workspace`和`Blob`来完成，使得`Variable`的概念并不明晰。

**Comment by reyoung** [comment]
> 关于那个Node的输入是其他的Node还有其他组合吗？

详见[`add_function`](https://github.com/clab/dynet/blob/v1.0-rc1/dynet/dynet.h#L94)函数。DyNet中只有Function可以使用其他`Node`当做输入。而对于`function`来说，输入的`Node`可以是任何类型。

**Comment by reyoung** [comment]
@Canpio 

> 说一点个人的理解。
如果一定要用节点和边的角度来理解计算图的话，因为计算图其实是对op的有序排列，那么应该op是节点。边应该用来表示op之间的依赖关系（“依赖关系”指的是“执行A之前必须要先执行B”这样的逻辑），而op之间之所以会产生依赖关系，其实是因为数据上的依赖。例如，opA需要一块数据，而这块数据是opB的产出，因此opA就对opB产生了依赖。所以计算图的边应该是数据，也就是blob。

1. 我们先不考虑怎么表达这个计算图，而先考虑这个计算图里面有什么。所以先不用考虑`有序排列`。
2. 从Op角度来看，确实是Op依赖了某一个输入数据，当某一个输入数据ready后才可以执行。但是从`数据`角度看，不也是某一段数据的ready依赖了某一个`Op`的执行么？也就是`Op`执行完才能产生`数据`？

如果我们认为Op是计算图中的节点，计算图中的关系是Variable的话，下图中FC1的输出同时输出给FC2和FC3，那么我们画图为:

![image](https://user-images.githubusercontent.com/728699/27217716-94023a78-52ad-11e7-92d3-918089ea76ba.png)

上图中的青色连线和蓝色连线表示Variable么？那他们是不是同一个Variable？同一个Variable为啥用两条线表示呢？

所以，当我们说OpA对OpB的依赖时，依赖的也是OpB的输出数据，刚才的图应该画为:

![image](https://user-images.githubusercontent.com/728699/27217802-fafccb3a-52ad-11e7-9ff7-26f324774c7c.png)

这种想法里，输出数据被看做了Op的私有属性。而『私有属性』有诸多问题:

* Variables并不方便统一的管理，内存优化等。
* 增加私有属性将`Op`从一个无状态的`函数`退化成了有状态的`类`。

对于Caffe2，它的[依赖关系表示](https://github.com/PaddlePaddle/Paddle/issues/2483#issuecomment-308959455)并不是OpA依赖另一个OpB，而是所有Op都使用`Workspace`中的一个元素。所以他的计算图中没有`Variables`，所有的节点都是`Op`。但Caffe2计算图的边并不是`OpA`依赖于另一个`OpB`，而是每一个Op使用`Workspace`中的哪些内存，输出`Workspace`的哪些内存。

**Comment by jacquesqiao** [comment]
### Mxnet 计算图详细信息
nnvm
nnvm是一个纯的symbol和graph符号表示库，不包含数据管理等功能。其数据结构表示如下，对所有操作的入口都是，通过反向递归outputs找到所有的Node和NodeEntry，NodeEntry对应的是数据，Node对应一个op，Variable是op为null的Node。
```cpp
Symbol {
    std::vector<NodeEntry> outputs;
}
```

![image](https://user-images.githubusercontent.com/3048612/27219815-994aa0ee-52b5-11e7-91d7-6d0f5b0b6d1d.png)


例如对于下面构建的Symbol/Graph：
```python
import mxnet as mx

a = mx.sym.Variable('a')
b = mx.sym.Variable('b')
c = a + b
```

其序列化之后的形式为：
```json
{
  "nodes": [
    {
      "op": "null", 
      "name": "a", 
      "inputs": []
    }, 
    {
      "op": "null", 
      "name": "b", 
      "inputs": []
    }, 
    {
      "op": "elemwise_add", 
      "name": "_plus0", 
      "inputs": [[0, 0, 0], [1, 0, 0]]
    }
  ], 
  "arg_nodes": [0, 1], 
  "node_row_ptr": [0, 1, 2, 3], 
  "heads": [[2, 0, 0]], 
}
```

从json可见，在Mxnet中，通过Node描述来Op和Variable，通过一些辅助成员来描述他们之间的关系：比如arg_nodes, node_row_prt等。

```python
import mxnet as mx
data = mx.symbol.Variable('data')
fc1 = mx.symbol.FullyConnected(data=data, name='fc1', num_hidden=128)
mlp = mx.symbol.SoftmaxOutput(data=fc1, name='softmax')
print mlp.tojson()
```

```json
{
  "nodes": [
    {
      "op": "null", 
      "name": "data", 
      "inputs": []
    }, 
    {
      "op": "null", 
      "name": "fc1_weight", 
      "attr": {"num_hidden": "128"}, 
      "inputs": []
    }, 
    {
      "op": "null", 
      "name": "fc1_bias", 
      "attr": {"num_hidden": "128"}, 
      "inputs": []
    }, 
    {
      "op": "FullyConnected", 
      "name": "fc1", 
      "attr": {"num_hidden": "128"}, 
      "inputs": [[0, 0, 0], [1, 0, 0], [2, 0, 0]]
    }, 
    {
      "op": "null", 
      "name": "softmax_label", 
      "inputs": []
    }, 
    {
      "op": "SoftmaxOutput", 
      "name": "softmax", 
      "inputs": [[3, 0, 0], [4, 0, 0]]
    }
  ], 
  "arg_nodes": [0, 1, 2, 4], 
  "node_row_ptr": [0, 1, 2, 3, 4, 5, 6], 
  "heads": [[5, 0, 0]], 
  "attrs": {"mxnet_version": ["int", 1000]}
}
```

至少从表现形式上，使用Node和Node之间的关系来描述整个计算图，Node既包含计算，也包含数据。

**Comment by Canpio** [comment]
@reyoung

**Comment by Canpio** [comment]
@reyoung 
确实，我刚才也想到了边也边之间可能指的是同一个数据的问题。
那么我觉得数据和操作都应该是图中节点，但是需要保证数据节点和操作节点之间必须是间隔排列的，即不能出现数据和数据或者操作和操作之间的直接连接。

**Comment by jacquesqiao** [comment]
对于Mxnet，在图中使用NodeEntry找到Node，然后再通过Node找到其他的NodeEntry，而对于caffe，只有op，且op之间没有连接关系，他们按照一定的顺序，找到自己需要的数据执行，确实不存在直接连接的情况。

**Comment by reyoung** [comment]
参考Tensorflow的Graph，似乎他的Node同时可以是Variable和Function，边就是Node的配对。
不过Tensorflow中似乎边可以是多个Node的配对，我再看看是为啥。

https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/graph/graph.h

**Comment by reyoung** [comment]
经线下和 @wangkuiyi 讨论，结论如下:

本着`less is exponentially more`的原则，参考Caffe2的实现如下:

```cpp
struct Op {
   vector<string> inputs_;
   vector<string> outputs_;
   string type_;
};
typedef shared_ptr<Op> OpPtr;
struct Graph {
   vector<OpPtr> ops_;
};
```

其中，Op的输入输出均是字符串。这些字符串是`Workspace`中的Key。`Workspace`定义如下:

```cpp
class Tensor;
struct Workspace {
  map<string, TensorPtr> tensors_;
};
```

**Comment by jacquesqiao** [comment]
> struct Op {
   vector<string> inputs_;
   vector<string> outputs_;
   string type_;
};

中是否应该包含OpDef，包含op相关的一些更详细的信息，比如说shape，size？

**Comment by wangkuiyi** [comment]
Caffe2 里有这个struct吗？

```
struct Graph {
   vector<OpPtr> ops_;
};
```

**Comment by reyoung** [comment]
> 中是否应该包含OpDef，包含op相关的一些更详细的信息，比如说shape，size？

确实每一个Op还需要一个[`attrs_`](https://github.com/caffe2/caffe2/blob/master/caffe2/proto/caffe2.proto#L97)字段，这个我开另一个issue讨论吧。

**Comment by wangkuiyi** [comment]
`OpPtr` 是什么？

在Caffe2里，`SimpleNet` 的[data member](https://github.com/caffe2/caffe2/blob/v0.7.0/caffe2/core/net.h#L102)是：

```cpp
vector<unique_ptr<OperatorBase> > operators_;
```

类似的，如果我们要用某种smart pointer，也应该写清楚。如果只是 `Op*`，那就写 `Op*` 好了，不需要 `typedef Op* OpPtr`。

**Comment by reyoung** [comment]
> Caffe2 里有这个struct吗？

@wangkuiyi Caffe2的Graph使用Protobuf message `NetDef`表示，在`SimpleNet`中将protobuf的`NetDef`[中的Op描述与其相对应的Workspace组合，放到添加到本地的`ops_`的`operators_`中](https://github.com/caffe2/caffe2/blob/master/caffe2/core/net.cc#L90)。

**Comment by reyoung** [comment]
> 如果只是 Op*，那就写 Op* 好了

好的。

**Comment by wangkuiyi** [comment]
我看Graph这个struct是不需要了的。

**Comment by wangkuiyi** [comment]
我理解，`SimpleNet`既包括了Net，也包括了执行方式。确实可以decouple一下。我感觉SimpleNet和NetBase可以合为一个Net，而SimpleNet中的执行方式，可以写成另一个class叫 SimpleExecutor。

**Comment by jacquesqiao** [comment]
所以是net中有一个成员变量叫做 executor么，不过executor的执行方式和net的组成方式关系还比较大

**Comment by reyoung** [comment]
> 是net中有一个成员变量叫做 executor么

感觉是 `Executor(net, workspace).execute()`这样。

> executor的执行方式和net的组成方式关系

每个executor如果需要对`Net`有一些特殊的组织，例如增加一些信息，似乎可以在每一个`executor`内部保存这些信息(所以这个设计扩展性没啥问题)? 最简单的`SimpleExecutor`肯定是不需要加这些信息的(所以这个设计目前够用)。

**Comment by reyoung** [comment]
> 中是否应该包含OpDef，包含op相关的一些更详细的信息，比如说shape，size？

Related issue #2499

**Comment by QiJune** [comment]
@wangkuiyi @reyoung @jacquesqiao 
Since we have a [doc](https://github.com/PaddlePaddle/Paddle/blob/develop/doc/design/graph.md)  which claims we will have Computations as Graphs, then what are the nodes and edges of the graph? And how is the C++ class Graph defined, data flow graph, control flow graph or etc.

**Comment by QiJune** [comment]
@jacquesqiao 我仔细看了一下Mxnet的代码，用户在python api中的定义的Variable其实也是Symbol；在这里与用户使用一个FullyConnected的Symbol并没有不同。

请参考如下[代码](https://github.com/dmlc/nnvm/blob/65a1a7104f8dca986c57765012555172239b31b1/src/core/symbolic.cc#L566)
```
Symbol Symbol::CreateVariable(const std::string& name) {
  Symbol s;
  s.outputs.emplace_back(NodeEntry{CreateVariableNode(name), 0, 0});
  return s;
}
```
这里跟Paddle中的Variable的概念有一些不同，Paddle的Variable本质上不应该暴露给用户的。

**Comment by gongweibao** [comment]
Feel free to reopen it!
