### ISSUE TITLE
stdio.h error on the Mac OS X

### ISSUE THREAD

**Issue by vijaymukhi712** [PaddlePaddle/Paddle#2484]
I am using a MacPro running macOS Sierra version 10.12.5

After running cmake .., these are the last lines of the output
-- Paddle version is 0.10.0
-- DROP LINT dataproviders/MultiDataProvider.cpp
-- DROP LINT dataproviders/MultiDataProvider.h
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/vijaymukhi/Desktop/music/paddle/build

When I then run make, this is what I see

Scanning dependencies of target extern_warpctc
[  0%] Creating directories for 'extern_warpctc'
[  0%] Performing download step (git clone) for 'extern_warpctc'
Cloning into 'extern_warpctc'...
Already on 'master'
Your branch is up-to-date with 'origin/master'.
[  1%] No patch step for 'extern_warpctc'
[  1%] No update step for 'extern_warpctc'
[  1%] Performing configure step for 'extern_warpctc'
-- extern_warpctc configure command succeeded.  See also /Users/vijaymukhi/Desktop/music/paddle/third_party/warpctc/src/extern_warpctc-stamp/extern_warpctc-configure-*.log
[  1%] Performing build step for 'extern_warpctc'
Scanning dependencies of target warpctc
[ 25%] Building CXX object CMakeFiles/warpctc.dir/src/ctc_entrypoint.cpp.o
[ 50%] Linking CXX shared library libwarpctc.dylib
[ 50%] Built target warpctc
Scanning dependencies of target test_cpu
[ 75%] Building CXX object CMakeFiles/test_cpu.dir/tests/test_cpu.cpp.o
[100%] Linking CXX executable test_cpu
[100%] Built target test_cpu
[  2%] Performing install step for 'extern_warpctc'
[ 50%] Built target warpctc
[100%] Built target test_cpu
Install the project...
-- Install configuration: "Release"
-- Installing: /Users/vijaymukhi/Desktop/music/paddle/third_party/install/warpctc/lib/libwarpctc.dylib
-- Installing: /Users/vijaymukhi/Desktop/music/paddle/third_party/install/warpctc/include/ctc.h
[  2%] Completed 'extern_warpctc'
[  2%] Built target extern_warpctc
Scanning dependencies of target extern_openblas
[  2%] Creating directories for 'extern_openblas'
[  2%] Performing download step (git clone) for 'extern_openblas'
Cloning into 'extern_openblas'...
Note: checking out 'v0.2.19'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

HEAD is now at 85636ff1... Merge branch 'develop'
[  2%] No patch step for 'extern_openblas'
[  3%] No update step for 'extern_openblas'
[  3%] No configure step for 'extern_openblas'
[  3%] Performing build step for 'extern_openblas'
getarch.c:80:10: fatal error: 'stdio.h' file not found
#include <stdio.h>
         ^
1 error generated.
make[3]: *** [getarch] Error 1
Makefile.system:165: Makefile.conf: No such file or directory
Makefile.system:912: Makefile.: No such file or directory
make[3]: *** No rule to make target `Makefile.'.  Stop.
make[2]: *** [../third_party/openblas/src/extern_openblas-stamp/extern_openblas-build] Error 2
make[1]: *** [CMakeFiles/extern_openblas.dir/all] Error 2
make: *** [all] Error 2

I wrote a small C program which includes the header file, it builds fine with gcc

**Comment by gangliao** [comment]
Hi, you can check the error information under the folder `extern_openblas-build`.

To skip this,  you `brew install openblas` to avoid build openblas by CMake.

```
brew install openblas
cd build && rm -rf *
cmake .. 
make -j8
```

**Comment by vijaymukhi712** [comment]
Thanks for the quick reply, I installed openblas like you said using brew and the error went away.
I then get another error regarding protobuf, used brew to update as I had a older version installed.

Thanks once again.

I am actually writing a book on ANN's where I focus on  Google's Tensorflow/Keras , Facebooks' Pytorch , Amazon's mxnet , Baidu's PaddlePaddle. I start with using good old numpy to create a bare bone Neural Network.  The idea is to help common folks to decide which NN framework they should use by creating the same  applications using each of the frameworks .

**Comment by gangliao** [comment]
That sounds interesting. wish all your best...
