### ISSUE TITLE
Error: the provided recursive_sequence_lengths info is invalid

### ISSUE THREAD

**Issue by MaxLingwei** [PaddlePaddle/Paddle#24840]
paddle: 1.8.1，本地开发机cpu版本；
网络：手写的两层fc+softmax输出

Error: the provided recursive_sequence_lengths info is invalid
  [Hint: Expected CheckLoD(new_offset_lod, vectorize(self.dims()).front()) == true, but received CheckLoD(new_offset_lod, vectorize(self.dims()).front()):0 != true:1.] at (/paddle/paddle/fluid/pybind/pybind.cc:723)

输入的一个batch：
[([2912.0, 864000.0, 278.3, 864000.0, 10.0, 18.0, 0.0, 1200000.0, 0.0], 2), ([13036.0, 5280000.0, 52934.13, 5280000.0, 110.0, 22.0, 0.0, 13200000.0, 0.0], 2), ([8212.0, 1650000.0, 0.0, 1650000.0, 0.0, 39.0, 0.0, 3300000.0, 0.0], 2), ([5747.0, 720000.0, 0.0, 720000.0, 0.0, 15.0, 0.0, 1440000.0, 0.0], 2), ([657.0, 192000.0, 0.0, 192000.0, 0.0, 3.0, 0.0, 384000.0, 0.0], 1), ([92.0, 630000.0, 0.0, 630000.0, 0.0, 12.0, 0.0, 1200000.0, 0.0], 1), ([3197.0, 750000.0, 0.0, 750000.0, 0.0, 10.0, 0.0, 1500000.0, 0.0], 2), ([3678.0, 600000.0, 0.0, 600000.0, 0.0, 13.0, 0.0, 1200000.0, 0.0], 1), ([13183.0, 900000.0, 2538.13, 900000.0, 10.0, 45.0, 0.0, 1800000.0, 0.0], 2), ([3005.0, 142292.82, 0.0, 142292.82, 0.0, 52.0, 0.0, 284585.64, 0.0], 2), ([13036.0, 103740.0, 9046.17, 103740.0, 16.3, 10.0, 1.0, 103740.0, 0.0], 1), ([8140.0, 480000.0, 0.0, 480000.0, 0.0, 19.0, 0.0, 1200000.0, 0.0], 2), ([10440.0, 311143.0, 0.0, 311143.0, 0.0, 16.0, 0.0, 622286.0, 0.0], 0), ([10121.0, 150000.0, 0.0, 150000.0, 0.0, 7.0, 0.0, 300000.0, 0.0], 2), ([3074.0, 300000.0, 0.0, 300000.0, 0.0, 9.0, 0.0, 600000.0, 0.0], 1), ([2896.0, 80000.0, 593.63, 80000.0, 10.0, 10.0, 0.0, 160000.0, 0.0], 2)]

每条训练数据是一个9x1的向量，label为0，1，2
定义数据的方式：
![image](https://user-images.githubusercontent.com/14048056/83477960-29812c80-a4c7-11ea-90e7-2f12e7694e24.png)

模型：
![image](https://user-images.githubusercontent.com/14048056/83482318-951cc700-a4d2-11ea-9c74-bedc871e108d.png)

**Comment by NHZlX** [comment]
将data 中的lod_level 去掉即可
