### ISSUE TITLE
AI Studio上使用GPU进行预测的自动重启问题

### ISSUE THREAD

**Issue by Ryan906k9** [PaddlePaddle/Paddle#24846]
为使您的问题得到快速解决，在建立Issue前，请您先通过如下方式搜索是否有相似问题:【搜索issue关键字】【使用labels筛选】【官方文档】

如果您没有查询到相似问题，为快速解决您的提问，建立issue时请提供如下细节信息：
- 标题：AI Studio上使用GPU进行预测的自动重启问题
[代码和日志.zip](https://github.com/PaddlePaddle/Paddle/files/4715158/default.zip)

- 版本、环境信息：
    1）PaddlePaddle版本：PaddlePaddle 1.8.0
    2）CPU：-
    3）GPU：v100
    4）系统环境：AI Studio，Python版本：3.7

-预测信息

    4）预测库来源：官网下载/特殊环境（如BCLOUD编译）

- 复现信息：无任何报错

- 问题描述：在 AI Studio 上使用 seq2seq 模型，用 GPU 训练没有问题，但是预测的时候，没几个 batch 后 AI Studio 就自动重启，改用 CPU 就没有问题。反馈后 RD 表示这个他们解决不了，是 Paddle 的底层问题，需要到这里来提交 issue。附件是代码和日志截图
[代码和日志.zip](https://github.com/PaddlePaddle/Paddle/files/4715162/default.zip)

**Comment by NHZlX** [comment]
预测建议使用预测接口（需要保证paddle版本1.7以及以上）。 

请参考：
https://paddle-inference.readthedocs.io/en/latest/introduction/quick_start.html

**Comment by Ryan906k9** [comment]
> 预测建议使用预测接口（需要保证paddle版本1.7以及以上）。
> 
> 请参考：
> https://paddle-inference.readthedocs.io/en/latest/introduction/quick_start.html

我尝试了使用，但是简单的网络结构参照案例可以实现
但是在实际运用到一个 NLP 任务中的时候，由于网络结构很复杂，我不确定是否使用正确了
出现了如下报错，是不是没有找到变量名的意思？我该去哪里找这个名字呢？
`---------------------------------------------------------------------------ValueError                                Traceback (most recent call last)<ipython-input-30-359c1be3b3db> in <module>
     18     t = time.strftime("_%Y_%m_%d_%H_%M_%S", time.localtime())
     19     #fluid.io.save_params(exe, model_save_dir+t, main_program=train_prog)
---> 20     fluid.io.save_inference_model(dirname='./s_model', feeded_var_names=['src'], target_vars = [encoder_output], executor=exe, model_filename='model', params_filename='params')
     21 
     22     loader.set_batch_generator(input_func(64, True),
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/io.py in save_inference_model(dirname, feeded_var_names, target_vars, executor, main_program, model_filename, params_filename, export_for_deployment, program_only)
   1219         fetch_var_names = [v.name for v in target_vars]
   1220 
-> 1221         prepend_feed_ops(main_program, feeded_var_names)
   1222         append_fetch_ops(main_program, fetch_var_names)
   1223 
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/io.py in prepend_feed_ops(inference_program, feed_target_names, feed_holder_name)
   1029 
   1030     for i, name in enumerate(feed_target_names):
-> 1031         out = global_block.var(name)
   1032         global_block._prepend_op(
   1033             type='feed',
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/framework.py in var(self, name)
   2278         v = self.vars.get(name, None)
   2279         if v is None:
-> 2280             raise ValueError("var %s not in this block" % name)
   2281         return v
   2282 
ValueError: var src not in this block`

我在程序里面是这么写的：

`EPOCH_NUM = 1
batch_start_time = time.time()
for pass_id in six.moves.xrange(EPOCH_NUM):
    batch_id = 0
    for data in loader():
        loss_val  = exe.run(prog, feed=data, fetch_list=[loss])[0]
        if batch_id % 50 == 0:
            print('pass_id: %d, batch_id: %d, loss: %f' %
                    (pass_id, batch_id, loss_val))
            print("batch running time:{}".format(time.time()-batch_start_time))
            batch_start_time = time.time()
        batch_id += 1
    # 保存模型
    # 获得当前日期和时间
    t = time.strftime("_%Y_%m_%d_%H_%M_%S", time.localtime())
    fluid.io.save_inference_model(dirname='./s_model', feeded_var_names=['src'], target_vars = [decoder_output], executor=exe, model_filename='model', params_filename='params')
    
    loader.set_batch_generator(input_func(64, True),
                            places=places)
    print("model save success")`

**Comment by Ryan906k9** [comment]
> 预测建议使用预测接口（需要保证paddle版本1.7以及以上）。
> 
> 请参考：
> https://paddle-inference.readthedocs.io/en/latest/introduction/quick_start.html

我尝试了使用，但是简单的网络结构参照案例可以实现
但是在实际运用到一个 NLP 任务中的时候，由于网络结构很复杂，我不确定是否使用正确了
出现了如下报错，是不是没有找到变量名的意思？我该去哪里找这个名字呢？
<img width="1095" alt="截屏2020-07-01 上午10 37 57" src="https://user-images.githubusercontent.com/35905925/86197095-46248900-bb87-11ea-8756-3bbc8a914b02.png">
<img width="1113" alt="截屏2020-07-01 上午10 38 07" src="https://user-images.githubusercontent.com/35905925/86197116-50df1e00-bb87-11ea-9f96-9e35a6309c8a.png">


我在程序里面是这么写的：
<img width="827" alt="截屏2020-07-01 上午10 37 23" src="https://user-images.githubusercontent.com/35905925/86197136-5a688600-bb87-11ea-9065-56139205f7fd.png">
