### ISSUE TITLE
保存模型时显示：var label not in this block 

### ISSUE THREAD

**Issue by MaxLingwei** [PaddlePaddle/Paddle#24865]
环境: paddlecloud, v100集群
![image](https://user-images.githubusercontent.com/14048056/83589049-657ac700-a585-11ea-8346-f8be6bc5f77c.png)
想同时把input_fea和label都保存下来

显示这个错误： 
![image](https://user-images.githubusercontent.com/14048056/83589127-90651b00-a585-11ea-8f05-a8692f25ad63.png)

**Comment by jerrywgz** [comment]
在保存inference model的时候输出只有prediction，是与label无关的，此时会将该variable剪裁掉，如果需要的话可以将label也放在fetch list中
