### ISSUE TITLE
module 'paddlehub' has no attribute 'Module'

### ISSUE THREAD

**Issue by Zacharychen1024** [PaddlePaddle/Paddle#24864]
paddle 和paddlehub 都pip安装成功了，但是报错
Traceback (most recent call last):
  File "G:/label/labelImg-master/paddlehub.py", line 3, in <module>
    import paddlehub as hub
  File "G:\label\labelImg-master\paddlehub.py", line 6, in <module>
    humanseg = hub.Module(name='deeplabv3p_xception65_humanseg')
AttributeError: module 'paddlehub' has no attribute 'Module'

**Comment by Steffy-zxf** [comment]
你好！你的paddlepaddle和paddlehub版本各是多少呢？PaddleHub使用过程中，关于PaddleHub的任何问题欢迎在PaddleHub repo下提issue： https://github.com/PaddlePaddle/PaddleHub/issues
