### ISSUE TITLE
使用fluid.io.load_interface_model后，运行时会以一定的概率报错

### ISSUE THREAD

**Issue by Edwardwaw** [PaddlePaddle/Paddle#24871]
环境:python3.7 paddle1.7.1  AI Studio
使用load_interface_model加载模型，进行预测时会以一定的概率报错，现已确定在训练模型某些地方加以改动后保存的模型会出现此问题，比如dataloader中加入image normalization

```python
import numpy as np
from PIL import Image
import paddle.fluid as fluid
import matplotlib.pyplot as plt
import zipfile

mean222=np.array([0.485,0.456,0.406]).reshape((1,1,3))
std222=np.array([0.229,0.224,0.225]).reshape((1,1,3))

test_zfile = zipfile.ZipFile("data/data37389/test_new.zip")
l_test = []
for test_fname in test_zfile.namelist()[1:]:
    l_test.append(test_fname)

test_img = Image.open(l_test[88])

plt.imshow(test_img)
plt.show()
test_img = test_img.resize((640, 480))
test_im = np.array(test_img)
test_im = (test_im / 255.0)
test_im = test_im.transpose().reshape(1, 3, 640, 480).astype('float32')

new_scope=fluid.Scope()
place=fluid.CUDAPlace(0)
infer_exe=fluid.Executor(place)
# infer_exe.run(fluid.default_startup_program())
path="./test_modelProblem/0/"
with fluid.scope_guard(new_scope):
    [inference_program, feed_target_names, fetch_targets] = fluid.io.load_inference_model(dirname=path, executor=infer_exe)
    result=infer_exe.run(inference_program,feed={feed_target_names[0]: test_im},fetch_list=fetch_targets)
    print(result[0].shape)
    res = result[0][0]
    # print(result)
    # plt.imshow(result,cmap=CM.jet)
    print(np.sum(result[0][0][0]))
```

/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/executor.py:782: UserWarning: The following exception is not an EOF exception.
  "The following exception is not an EOF exception.")
---------------------------------------------------------------------------EnforceNotMet                             Traceback (most recent call last)<ipython-input-13-779da9462f5a> in <module>
     29 with fluid.scope_guard(new_scope):
     30     [inference_program, feed_target_names, fetch_targets] = fluid.io.load_inference_model(dirname=path, executor=infer_exe)
---> 31     result=infer_exe.run(inference_program,feed={feed_target_names[0]: test_im},fetch_list=fetch_targets)
     32     print(result[0].shape)
     33     res = result[0][0]
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/executor.py in run(self, program, feed, fetch_list, feed_var_name, fetch_var_name, scope, return_numpy, use_program_cache)
    781                 warnings.warn(
    782                     "The following exception is not an EOF exception.")
--> 783             six.reraise(*sys.exc_info())
    784 
    785     def _run_impl(self, program, feed, fetch_list, feed_var_name,
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/six.py in reraise(tp, value, tb)
    691             if value.__traceback__ is not tb:
    692                 raise value.with_traceback(tb)
--> 693             raise value
    694         finally:
    695             value = None
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/executor.py in run(self, program, feed, fetch_list, feed_var_name, fetch_var_name, scope, return_numpy, use_program_cache)
    776                 scope=scope,
    777                 return_numpy=return_numpy,
--> 778                 use_program_cache=use_program_cache)
    779         except Exception as e:
    780             if not isinstance(e, core.EOFException):
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/executor.py in _run_impl(self, program, feed, fetch_list, feed_var_name, fetch_var_name, scope, return_numpy, use_program_cache)
    829                 scope=scope,
    830                 return_numpy=return_numpy,
--> 831                 use_program_cache=use_program_cache)
    832 
    833         program._compile(scope, self.place)
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/executor.py in _run_program(self, program, feed, fetch_list, feed_var_name, fetch_var_name, scope, return_numpy, use_program_cache)
    903         if not use_program_cache:
    904             self._default_executor.run(program.desc, scope, 0, True, True,
--> 905                                        fetch_var_name)
    906         else:
    907             self._default_executor.run_prepared_ctx(ctx, scope, False, False,
EnforceNotMet: 

--------------------------------------------
C++ Call Stacks (More useful to developers):
--------------------------------------------
0   std::string paddle::platform::GetTraceBackString<std::string const&>(std::string const&, char const*, int)
1   paddle::platform::EnforceNotMet::EnforceNotMet(std::string const&, char const*, int)
2   paddle::framework::Tensor::check_memory_size() const
3   float const* paddle::framework::Tensor::data<float>() const
4   void paddle::operators::ElementwiseComputeEx<paddle::operators::SubFunctor<float, void>, paddle::platform::CUDADeviceContext, float, float>(paddle::framework::ExecutionContext const&, paddle::framework::Tensor const*, paddle::framework::Tensor const*, int, paddle::operators::SubFunctor<float, void>, paddle::framework::Tensor*)
5   void paddle::operators::default_elementwise_sub<paddle::platform::CUDADeviceContext, float>(paddle::framework::ExecutionContext const&, paddle::framework::Tensor const*, paddle::framework::Tensor const*, paddle::framework::Tensor*)
6   paddle::operators::ElementwiseSubKernel<paddle::platform::CUDADeviceContext, float>::Compute(paddle::framework::ExecutionContext const&) const
7   std::_Function_handler<void (paddle::framework::ExecutionContext const&), paddle::framework::OpKernelRegistrarFunctor<paddle::platform::CUDAPlace, false, 0ul, paddle::operators::ElementwiseSubKernel<paddle::platform::CUDADeviceContext, float>, paddle::operators::ElementwiseSubKernel<paddle::platform::CUDADeviceContext, paddle::platform::float16>, paddle::operators::ElementwiseSubKernel<paddle::platform::CUDADeviceContext, double>, paddle::operators::ElementwiseSubKernel<paddle::platform::CUDADeviceContext, int>, paddle::operators::ElementwiseSubKernel<paddle::platform::CUDADeviceContext, long> >::operator()(char const*, char const*, int) const::{lambda(paddle::framework::ExecutionContext const&)#1}>::_M_invoke(std::_Any_data const&, paddle::framework::ExecutionContext const&)
8   paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, paddle::platform::Place const&, paddle::framework::RuntimeContext*) const
9   paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, paddle::platform::Place const&) const
10  paddle::framework::OperatorBase::Run(paddle::framework::Scope const&, paddle::platform::Place const&)
11  paddle::framework::Executor::RunPreparedContext(paddle::framework::ExecutorPrepareContext*, paddle::framework::Scope*, bool, bool, bool)
12  paddle::framework::Executor::Run(paddle::framework::ProgramDesc const&, paddle::framework::Scope*, int, bool, bool, std::vector<std::string, std::allocator<std::string> > const&, bool, bool)

------------------------------------------
Python Call Stacks (More useful to users):
------------------------------------------
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/framework.py", line 2525, in append_op
    attrs=kwargs.get("attrs", None))
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/layer_helper.py", line 43, in append_op
    return self.main_program.current_block().append_op(*args, **kwargs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/layers/loss.py", line 343, in square_error_cost
    outputs={'Out': [minus_out]})
  File "<ipython-input-2-3da42655f3ff>", line 14, in <module>
    cost1 = fluid.layers.square_error_cost(input=predict, label=label)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 3265, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 3183, in run_ast_nodes
    if (yield from self.run_code(code, result)):
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 3018, in run_cell_async
    interactivity=interactivity, compiler=compiler, result=result)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/IPython/core/async_helpers.py", line 67, in _pseudo_sync_runner
    coro.send(None)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 2843, in _run_cell
    return runner(coro)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 2817, in run_cell
    raw_cell, store_history, silent, shell_futures)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/ipykernel/zmqshell.py", line 536, in run_cell
    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/ipykernel/ipkernel.py", line 294, in do_execute
    res = shell.run_cell(code, store_history=store_history, silent=silent)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/tornado/gen.py", line 326, in wrapper
    yielded = next(result)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/ipykernel/kernelbase.py", line 534, in execute_request
    user_expressions, allow_stdin,
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/tornado/gen.py", line 326, in wrapper
    yielded = next(result)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/ipykernel/kernelbase.py", line 267, in dispatch_shell
    yield gen.maybe_future(handler(stream, idents, msg))
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/tornado/gen.py", line 326, in wrapper
    yielded = next(result)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/ipykernel/kernelbase.py", line 357, in process_one
    yield gen.maybe_future(dispatch(*args))
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/tornado/gen.py", line 1147, in run
    yielded = self.gen.send(value)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/tornado/gen.py", line 1233, in inner
    self.run()
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/tornado/stack_context.py", line 300, in null_wrapper
    return fn(*args, **kwargs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/tornado/ioloop.py", line 758, in _run_callback
    ret = callback()
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/asyncio/base_events.py", line 1771, in _run_once
    handle._run()
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/asyncio/base_events.py", line 534, in run_forever
    self._run_once()
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/tornado/platform/asyncio.py", line 132, in start
    self.asyncio_loop.run_forever()
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/ipykernel/kernelapp.py", line 505, in start
    self.io_loop.start()
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/traitlets/config/application.py", line 664, in launch_instance
    app.start()
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/ipykernel_launcher.py", line 16, in <module>
    app.launch_new_instance()
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)

----------------------
Error Message Summary:
----------------------
Error: Tensor holds no memory. Call Tensor::mutable_data first.
  [Hint: holder_ should not be null.] at (/paddle/paddle/fluid/framework/tensor.cc:23)
  [operator < elementwise_sub > error]

**Comment by wzzju** [comment]
从报错信息来看，elementwise_sub op的输入中有tensor没有进行初始化。抱歉，从您贴出的代码及log中不能看出更多信息。dataloader中加入image normalization后是必然出现此问题吗？

**Comment by Edwardwaw** [comment]
```python
from PIL import Image
import h5py
import numpy as np
import cv2
import random
from skimage import exposure, img_as_float
import numpy as np

mean111=np.array([0.485,0.456,0.406]).reshape((1,1,3))
std111=np.array([0.229,0.224,0.225]).reshape((1,1,3))


def load_data(img, ratio, aug,index):
    gt_file = h5py.File(content['annotations'][index]['name'].replace('.jpg','.h5').replace('.png','.h5').replace('train','gt'),'r')
    target= np.asarray(gt_file['density'])
    if aug:
        if False:
        # if random.random()>0.5:
            crop_size = (img.size[0]//2, img.size[1]//2)
        
            if random.random() <=0.44:
                # 4 non-overlapping patches
                dx = int(random.randint(0,1) * crop_size[0])
                dy = int(random.randint(0,1) * crop_size[1])
            else:
                # 5 random patches
                # set seed to ensure for each image the random patches are certain
                # if not set, the crop will be online which means the patches change every time loading, leading to a dynamic training set.
                patch_id = random.randint(0, 4)
                random.seed(index + patch_id * 0.1)
                dx = int(random.random() * crop_size[0])
                random.seed(index + 0.5 + patch_id * 0.1)
                dy = int(random.random() * crop_size[1])
 else:
            img=img
            target=target
        # flip
        if random.random() > 0.5:
            target = np.fliplr(target)
            img = img.transpose(Image.FLIP_LEFT_RIGHT)
        # gamma transform
        if random.random() > 0.7:
            image = img_as_float(img)
            # gamma_img: np.array(dtype=float64) ranging [0,1]
            gamma_img = exposure.adjust_gamma(image, 0.5+random.random())
            gamma_img = gamma_img *255
            gamma_img = np.uint8(gamma_img)
            img = Image.fromarray(gamma_img)
    if ratio>1:
        target = cv2.resize(target, (int(target.shape[1]/ratio),int(target.shape[0]/ratio)), interpolation=cv2.INTER_CUBIC) * (ratio**2)
    # img=np.array(img)/255.0
    # print(img.shape)
    # img=(img-mean111)/std111
    
    return np.array(img)/255.0, targetfrom PIL import Image
```
从目前来看，加入上方注释的2行后会出现此问题，但是这些代码似乎和tensor无关，所以比较奇怪

**Comment by Edwardwaw** [comment]
链接: https://pan.baidu.com/s/1x1QX1A7RPCwaxKeUrbZUBA 提取码: 5zxm
以上是interface model链接，需要补充的一点是训练过程正常

**Comment by wzzju** [comment]
> ```python
> # if random.random()>0.5:
> ```

注释的两行您是指`# if random.random()>0.5: crop_size = (img.size[0]//2, img.size[1]//2)`这句吗？

**Comment by Edwardwaw** [comment]
img=(img-mean111)/std111
是这一行

**Comment by jiweibo** [comment]
> 环境:python3.7 paddle1.7.1 AI Studio
> 使用load_interface_model加载模型，进行预测时会以一定的概率报错，现已确定在训练模型某些地方加以改动后保存的模型会出现此问题，比如dataloader中加入image normalization
> 
> ```python
> import numpy as np
> from PIL import Image
> import paddle.fluid as fluid
> import matplotlib.pyplot as plt
> import zipfile
> 
> mean222=np.array([0.485,0.456,0.406]).reshape((1,1,3))
> std222=np.array([0.229,0.224,0.225]).reshape((1,1,3))
> 
> test_zfile = zipfile.ZipFile("data/data37389/test_new.zip")
> l_test = []
> for test_fname in test_zfile.namelist()[1:]:
>     l_test.append(test_fname)
> 
> test_img = Image.open(l_test[88])
> 
> plt.imshow(test_img)
> plt.show()
> test_img = test_img.resize((640, 480))
> test_im = np.array(test_img)
> test_im = (test_im / 255.0)
> test_im = test_im.transpose().reshape(1, 3, 640, 480).astype('float32')
> 
> new_scope=fluid.Scope()
> place=fluid.CUDAPlace(0)
> infer_exe=fluid.Executor(place)
> # infer_exe.run(fluid.default_startup_program())
> path="./test_modelProblem/0/"
> with fluid.scope_guard(new_scope):
>     [inference_program, feed_target_names, fetch_targets] = fluid.io.load_inference_model(dirname=path, executor=infer_exe)
>     result=infer_exe.run(inference_program,feed={feed_target_names[0]: test_im},fetch_list=fetch_targets)
>     print(result[0].shape)
>     res = result[0][0]
>     # print(result)
>     # plt.imshow(result,cmap=CM.jet)
>     print(np.sum(result[0][0][0]))
> ```
> 
> /opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/executor.py:782: UserWarning: The following exception is not an EOF exception.
> "The following exception is not an EOF exception.")
> ---------------------------------------------------------------------------EnforceNotMet Traceback (most recent call last) in 
> 29 with fluid.scope_guard(new_scope):
> 30 [inference_program, feed_target_names, fetch_targets] = fluid.io.load_inference_model(dirname=path, executor=infer_exe)
> ---> 31 result=infer_exe.run(inference_program,feed={feed_target_names[0]: test_im},fetch_list=fetch_targets)
> 32 print(result[0].shape)
> 33 res = result[0][0]
> /opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/executor.py in run(self, program, feed, fetch_list, feed_var_name, fetch_var_name, scope, return_numpy, use_program_cache)
> 781 warnings.warn(
> 782 "The following exception is not an EOF exception.")
> --> 783 six.reraise(*sys.exc_info())
> 784
> 785 def _run_impl(self, program, feed, fetch_list, feed_var_name,
> /opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/six.py in reraise(tp, value, tb)
> 691 if value.**traceback** is not tb:
> 692 raise value.with_traceback(tb)
> --> 693 raise value
> 694 finally:
> 695 value = None
> /opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/executor.py in run(self, program, feed, fetch_list, feed_var_name, fetch_var_name, scope, return_numpy, use_program_cache)
> 776 scope=scope,
> 777 return_numpy=return_numpy,
> --> 778 use_program_cache=use_program_cache)
> 779 except Exception as e:
> 780 if not isinstance(e, core.EOFException):
> /opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/executor.py in _run_impl(self, program, feed, fetch_list, feed_var_name, fetch_var_name, scope, return_numpy, use_program_cache)
> 829 scope=scope,
> 830 return_numpy=return_numpy,
> --> 831 use_program_cache=use_program_cache)
> 832
> 833 program._compile(scope, self.place)
> /opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/executor.py in _run_program(self, program, feed, fetch_list, feed_var_name, fetch_var_name, scope, return_numpy, use_program_cache)
> 903 if not use_program_cache:
> 904 self._default_executor.run(program.desc, scope, 0, True, True,
> --> 905 fetch_var_name)
> 906 else:
> 907 self._default_executor.run_prepared_ctx(ctx, scope, False, False,
> EnforceNotMet:
> 
> ## C++ Call Stacks (More useful to developers):
> 0 std::string paddle::platform::GetTraceBackString<std::string const&>(std::string const&, char const*, int)
> 1 paddle::platform::EnforceNotMet::EnforceNotMet(std::string const&, char const*, int)
> 2 paddle::framework::Tensor::check_memory_size() const
> 3 float const* paddle::framework::Tensor::data() const
> 4 void paddle::operators::ElementwiseComputeEx<paddle::operators::SubFunctor<float, void>, paddle::platform::CUDADeviceContext, float, float>(paddle::framework::ExecutionContext const&, paddle::framework::Tensor const*, paddle::framework::Tensor const*, int, paddle::operators::SubFunctor<float, void>, paddle::framework::Tensor*)
> 5 void paddle::operators::default_elementwise_sub<paddle::platform::CUDADeviceContext, float>(paddle::framework::ExecutionContext const&, paddle::framework::Tensor const*, paddle::framework::Tensor const*, paddle::framework::Tensor*)
> 6 paddle::operators::ElementwiseSubKernel<paddle::platform::CUDADeviceContext, float>::Compute(paddle::framework::ExecutionContext const&) const
> 7 std::_Function_handler<void (paddle::framework::ExecutionContext const&), paddle::framework::OpKernelRegistrarFunctor<paddle::platform::CUDAPlace, false, 0ul, paddle::operators::ElementwiseSubKernel<paddle::platform::CUDADeviceContext, float>, paddle::operators::ElementwiseSubKernel<paddle::platform::CUDADeviceContext, paddle::platform::float16>, paddle::operators::ElementwiseSubKernel<paddle::platform::CUDADeviceContext, double>, paddle::operators::ElementwiseSubKernel<paddle::platform::CUDADeviceContext, int>, paddle::operators::ElementwiseSubKernel<paddle::platform::CUDADeviceContext, long> >::operator()(char const*, char const*, int) const::{lambda(paddle::framework::ExecutionContext const&)#1}>::_M_invoke(std::_Any_data const&, paddle::framework::ExecutionContext const&)
> 8 paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, paddle::platform::Place const&, paddle::framework::RuntimeContext*) const
> 9 paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, paddle::platform::Place const&) const
> 10 paddle::framework::OperatorBase::Run(paddle::framework::Scope const&, paddle::platform::Place const&)
> 11 paddle::framework::Executor::RunPreparedContext(paddle::framework::ExecutorPrepareContext*, paddle::framework::Scope*, bool, bool, bool)
> 12 paddle::framework::Executor::Run(paddle::framework::ProgramDesc const&, paddle::framework::Scope*, int, bool, bool, std::vector<std::string, std::allocatorstd::string > const&, bool, bool)
> 
> ## Python Call Stacks (More useful to users):
> File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/framework.py", line 2525, in append_op
> attrs=kwargs.get("attrs", None))
> File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/layer_helper.py", line 43, in append_op
> return self.main_program.current_block().append_op(*args, **kwargs)
> File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/layers/loss.py", line 343, in square_error_cost
> outputs={'Out': [minus_out]})
> File "", line 14, in 
> cost1 = fluid.layers.square_error_cost(input=predict, label=label)
> File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 3265, in run_code
> exec(code_obj, self.user_global_ns, self.user_ns)
> File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 3183, in run_ast_nodes
> if (yield from self.run_code(code, result)):
> File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 3018, in run_cell_async
> interactivity=interactivity, compiler=compiler, result=result)
> File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/IPython/core/async_helpers.py", line 67, in _pseudo_sync_runner
> coro.send(None)
> File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 2843, in _run_cell
> return runner(coro)
> File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 2817, in run_cell
> raw_cell, store_history, silent, shell_futures)
> File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/ipykernel/zmqshell.py", line 536, in run_cell
> return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)
> File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/ipykernel/ipkernel.py", line 294, in do_execute
> res = shell.run_cell(code, store_history=store_history, silent=silent)
> File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/tornado/gen.py", line 326, in wrapper
> yielded = next(result)
> File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/ipykernel/kernelbase.py", line 534, in execute_request
> user_expressions, allow_stdin,
> File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/tornado/gen.py", line 326, in wrapper
> yielded = next(result)
> File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/ipykernel/kernelbase.py", line 267, in dispatch_shell
> yield gen.maybe_future(handler(stream, idents, msg))
> File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/tornado/gen.py", line 326, in wrapper
> yielded = next(result)
> File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/ipykernel/kernelbase.py", line 357, in process_one
> yield gen.maybe_future(dispatch(*args))
> File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/tornado/gen.py", line 1147, in run
> yielded = self.gen.send(value)
> File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/tornado/gen.py", line 1233, in inner
> self.run()
> File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/tornado/stack_context.py", line 300, in null_wrapper
> return fn(*args, **kwargs)
> File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/tornado/ioloop.py", line 758, in _run_callback
> ret = callback()
> File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/asyncio/events.py", line 88, in _run
> self._context.run(self._callback, *self._args)
> File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/asyncio/base_events.py", line 1771, in _run_once
> handle._run()
> File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/asyncio/base_events.py", line 534, in run_forever
> self._run_once()
> File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/tornado/platform/asyncio.py", line 132, in start
> self.asyncio_loop.run_forever()
> File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/ipykernel/kernelapp.py", line 505, in start
> self.io_loop.start()
> File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/traitlets/config/application.py", line 664, in launch_instance
> app.start()
> File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/ipykernel_launcher.py", line 16, in 
> app.launch_new_instance()
> File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/runpy.py", line 85, in _run_code
> exec(code, run_globals)
> File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/runpy.py", line 193, in _run_module_as_main
> "**main**", mod_spec)
> 
> ## Error Message Summary:
> Error: Tensor holds no memory. Call Tensor::mutable_data first.
> [Hint: holder_ should not be null.] at (/paddle/paddle/fluid/framework/tensor.cc:23)
> [operator < elementwise_sub > error]

请尝试换成1.8的paddle试一下，可能是因为1.7 save_inference_model接口的问题
