### ISSUE TITLE
动态图LinearLrWarmup的实现有错误

### ISSUE THREAD

**Issue by xbsu** [PaddlePaddle/Paddle#24878]
https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/fluid/dygraph/learning_rate_scheduler.py#L677

**Comment by xbsu** [comment]
return self.lr_ratio_before_warmup * self.step_num

**Comment by xbsu** [comment]
return self.lr_ratio_before_warmup * self.step_num
是否应该改为
return self.start_lr + self.lr_ratio_before_warmup * self.step_num

**Comment by wzzju** [comment]
This is a bug, and it will be fixed later.

**Comment by phlrain** [comment]
https://github.com/PaddlePaddle/Paddle/pull/24913
我们会在这个pr中修复这个问题
