### ISSUE TITLE
slice OP中英文文档与运行结果不一致

### ISSUE THREAD

**Issue by mamingjie-China** [PaddlePaddle/Paddle#24872]
1.8.1版本的slice的描述中，参数axes表述为可选，中英文相同，但如果不添加该参数，会报错，所给出的例子中，也没有指定axes
![image](https://user-images.githubusercontent.com/52770436/83604610-075fdb00-a5a9-11ea-8cbd-6ee159919dd5.png)
![image](https://user-images.githubusercontent.com/52770436/83604658-1e9ec880-a5a9-11ea-9c96-a447f35a465d.png)
![image](https://user-images.githubusercontent.com/52770436/83604846-6d4c6280-a5a9-11ea-9ee9-0653d87f3d94.png)

**Comment by TCChenlong** [comment]
好的，收到，感谢反馈~
