### ISSUE TITLE
模型调用方法求助

### ISSUE THREAD

**Issue by Lieberk** [PaddlePaddle/Paddle#24884]
class Encoder(nn.Module):
    """
    Encoder.
    """

    def __init__(self, encoded_image_size=14):
        super(Encoder, self).__init__()
        self.enc_image_size = encoded_image_size

        resnet = torchvision.models.resnet101(pretrained=True)  # pretrained ImageNet ResNet-101

        # Remove linear and pool layers (since we're not doing classification)
        modules = list(resnet.children())[:-2]
        self.resnet = nn.Sequential(*modules)

        # Resize image to fixed size to allow input images of variable size
        self.adaptive_pool = nn.AdaptiveAvgPool2d((encoded_image_size, encoded_image_size))

上面是用pytorch调用的模型，对模型进行更改，把最后两层去掉。老师，我现在想把这段代码用paddle框架实现，该如何写呢，我找不到方向。对于paddle的预训练模型，能不能访问每一层呢，请老师们帮忙解答一下。

**Comment by wzzju** [comment]
可以使用如下语句方法`fluid.dygraph.Layer`对象的每一层，然后实行你所需的修改。
```python
for name, layer in model.named_sublayers():
    pass
```
也许你可以从[PR代码](https://github.com/PaddlePaddle/Paddle/blob/a9557bd1719ebffe2191c536d4aad0467ad9e8de/python/paddle/fluid/contrib/slim/quantization/dyquant/dygraph_quantization.py#L58)得到一些启发。
