### ISSUE TITLE
auc远低于正常值

### ISSUE THREAD

**Issue by zhaoyang1708** [PaddlePaddle/Paddle#24898]
cpu分布式训练点击率预估模型，设定不同的场景，底层共享，高层更新各自的层，发现日志中auc远低于正常值（0.7左右），有的甚至0.1~0.2，麻烦看下是哪里有问题。
训练日志 http://10.182.12.149:8910/fileview.html?type=logsdir&path=/&instance=0.app-user-20200603103137-78634--zhaoyang29_online_novelnnq_paddlecloud

**Comment by jerrywgz** [comment]
请问具体使用的是哪个模型呢

**Comment by zhaoyang1708** [comment]
> 请问具体使用的是哪个模型呢

网络结构参考的mmoe https://github.com/PaddlePaddle/models/blob/develop/PaddleRec/multi_task/mmoe/mmoe_train.py
但训练数据是抽取的广告曝光日志

**Comment by frankwhzhang** [comment]
建议先控制变量，只优化一个目标，和单任务比较，确定是否是网络结构的问题

**Comment by zhaoyang1708** [comment]
> 建议先控制变量，只优化一个目标，和单任务比较，确定是否是网络结构的问题

之前这样试过，确认网络结构没问题，可以正常收敛
