### ISSUE TITLE
部分网络拟合结果不符合预期

### ISSUE THREAD

**Issue by kahitomi** [PaddlePaddle/Paddle#24899]
网络任务：
sentence为一句话，subject和object分别为句子当中的若干连续词

任务一，sentence -> subject 1  subject 2 ...

任务二，sentence，subject -> object 1，object 2 ...

两个任务的输出，通过在sentence中每一个词上预测，start和end标签进行分类

对应tensorflow代码 https://github.com/weizhepei/CasRel/blob/master/model.py

问题：
在执行任务二的时候，使用小样本观察（20条数据），在一个sentence有多条subject组合的时候，无法在这些数据上都拟合成功，如如下两个数据

sentence，subject 1 -> object 1

sentence，subject 2 -> object 2

推论，subject的信息没有完全融合进sentence中，这一块的逻辑是把表示subject的所有词（或者头尾词）取出来做平均，然后和sentence中的每一个词相加，然后用新的词表示预测类别

tensorflow（keras）源代码是
   ```
 tokens_feature = bert_model([tokens, segments]) 

    sub_head_feature = Lambda(seq_gather)([tokens_feature, sub_head])

    sub_tail_feature = Lambda(seq_gather)([tokens_feature, sub_tail])

    sub_feature = Average()([sub_head_feature, sub_tail_feature])

    tokens_feature = Add()([tokens_feature, sub_feature])

    pred_obj_heads = Dense(num_rels, activation='sigmoid')(tokens_feature) 

    pred_obj_tails = Dense(num_rels, activation='sigmoid')(tokens_feature)
```

对应的paddle代码是（版本1.8.1）
![image](https://user-images.githubusercontent.com/2569549/83723732-b536bc80-a671-11ea-8192-c256c9313a67.png)
![image](https://user-images.githubusercontent.com/2569549/83723760-bcf66100-a671-11ea-9f47-626ba1ad426b.png)
![image](https://user-images.githubusercontent.com/2569549/83723789-c7185f80-a671-11ea-8019-416fd0445f27.png)
![image](https://user-images.githubusercontent.com/2569549/83723801-d0093100-a671-11ea-876e-5fc1db125dfc.png)

希望的结果：
正常拟合数据，对齐tensorflow效果

已经做的一些尝试：
1. 在截取subject片段，做平均之后，给subject添加一个linear变换，再和sentence组合，结果可以拟合，但是最终训练效果比tensorflow低2~4个点（核心问题没有解决）
2. 改用gather方法，结果可以拟合，但是最终效果确下降20+点。在此之上，额外增加1描述的变换，可以得到和1一样的结果。gather代码如下（这里s_in_mask为适应gather nd接口的index表示，获取subject的头尾词）
![image](https://user-images.githubusercontent.com/2569549/83723855-e6af8800-a671-11ea-8216-6b7f3807659d.png)

**Comment by jerrywgz** [comment]
目前如果是希望和tf对齐的话，可以尝试用相同的一份数据并使用相同的权重，在keras和paddle上跑下前向网络看下是哪里的使用有diff。刚确认了下，ernie和kera的bert model结构上是对齐，这部分是验证过的，也可以给相同的tokens_feature和enc_out，然后看网络后半部分的输出是否一致

**Comment by kahitomi** [comment]
> 目前如果是希望和tf对齐的话，可以尝试用相同的一份数据并使用相同的权重，在keras和paddle上跑下前向网络看下是哪里的使用有diff。刚确认了下，ernie和kera的bert model结构上是对齐，这部分是验证过的，也可以给相同的tokens_feature和enc_out，然后看网络后半部分的输出是否一致

这个问题希望解决的点，主要是使用正常的网络结构，无法拟合数据~ 希望看一下这方面的原因

**Comment by jerrywgz** [comment]
用户自身组网问题，目前已解决
