### ISSUE TITLE
fluid.nets.simple_img_conv_pool 没有 data_format 参数

### ISSUE THREAD

**Issue by liuyiding1993** [PaddlePaddle/Paddle#24894]
fluid.layers.conv2d 和 pool2d 是可以指定 data_format 为 NHWC 或者 NCHW，但是 fluid.nets.simple_img_conv_pool 不支持。

simple_img_conv_pool的文档：https://www.paddlepaddle.org.cn/documentation/docs/zh/api_cn/nets_cn/simple_img_conv_pool_cn.html#simple-img-conv-pool

paddle 版本：1.8.1

**Comment by jerrywgz** [comment]
是的，simple_img_conv_pool这个api是将conv2d和pool2d直接拼接得到的，并省略了其中data_format的参数，目前使用默认NCHW的格式，如果希望使用NHWC，可是直接使用conv2d+pool2d进行组合
