### ISSUE TITLE
io.save_inference_model 选择save to memory后拿到的字节码如何保存并解析？

### ISSUE THREAD

**Issue by barry2025** [PaddlePaddle/Paddle#24900]
paddle版本1.8.1
模型库版本：paddledetection 0.3

问题描述：当前调用fluid.io.save_inference_model后会生成__params__，选择save to memory 后返回了字节串：
![image](https://user-images.githubusercontent.com/20043808/83726028-8589b380-a675-11ea-8778-397de8597b06.png)
请问下这个字节串如何保存和解析，想拿到这部分数据进行相关的处理(例如加密之内的)

**Comment by DannyIsFunny** [comment]
你好，这里是将模型中单个权重信息的二进制数据以字节数组的格式返回出来，其内容单个param文件中保存的二进制内容一致

**Comment by DannyIsFunny** [comment]
一般加密流程为：得到字节码后用 算法加密后、保存为二进制数据文件；解析时加载二进制数据文件、算法解密后，在解密出的内存数据加载模型
