### ISSUE TITLE
添加对硬件环境的检测

### ISSUE THREAD

**Issue by wangzhankun** [PaddlePaddle/Paddle#24909]
在使用aistudio的过程中发现paddle paddle不会 环境进行检测报错。即当使用CPU版本的aistudio环境时，当设置```use_cuda = True```会导致aistudio自动重启或者一直显示正在运行，这会对用户造成很大的困扰。希望能够增加检测机制，当当前硬件环境不存在GPU时能够报错提醒用户。

**Comment by jerrywgz** [comment]
https://github.com/PaddlePaddle/models/blob/develop/PaddleCV/image_classification/utils/utility.py#L173 models中的一些模型会通过这种方法来检查当前运行的环境是否符合要求，可以参考～
