### ISSUE TITLE
请问paddle是否即将或已经支持gradient accumulation?

### ISSUE THREAD

**Issue by daizh** [PaddlePaddle/Paddle#24905]
您好, 我看到 #24823 中支持了fp16的梯度累加, 并且在/release/1.8/paddle/fluid/imperative 目录下找到了gradient_accumulator 相关的代码. 

请问paddle是否即将支持或已经支持gradient accumulation了呢?

**Comment by zhiqiu** [comment]
hi，您好，这个PR的梯度累加是指同一batch内，不同op产生同一个梯度的累加（聚合）。例如，a = x + y, b = x * z，在反向时两个反向op会产生x_grad。
如果您需要不同batch之间的梯度累加（扩大batch_size）,还需要稍等我们后续的支持。

**Comment by daizh** [comment]
谢谢, 期待ing

**Comment by daizh** [comment]
请问现在paddle2.0动态图版本中，是否可以实现「不同batch之间的梯度累加」了呢？
