### ISSUE TITLE
如何从paddle模型中提取网络每一层的输入输出特征矩阵？

### ISSUE THREAD

**Issue by taoja12** [PaddlePaddle/Paddle#24907]
比如输入的图片转换成特征矩阵后如图，图片是224x224，所以生成224x224x3的矩阵
![image](https://user-images.githubusercontent.com/44150172/83760594-bda9ea00-a6a7-11ea-9b0c-fef76cd6c05c.png)

输出是图片分类的种类1000种，所以结果的输出是1x1000的矩阵特征值
![image](https://user-images.githubusercontent.com/44150172/83760562-b1be2800-a6a7-11ea-9a73-02bfbd4f6864.png)

我想在想得到网络中任意一层的这种矩阵特征值输出该如何做？
（比如得到第一层卷积层之后的输出，或者某一个全连接层之后的输出）

**Comment by jerrywgz** [comment]
可以将对应variable的名字放到fetch list中

**Comment by taoja12** [comment]
这是我的代码。请问具体应该怎么操作将variable名字放入fetch list中？

import os
import sys
import numpy as np
import paddle.fluid as fluid
from paddle.fluid import core

def load_inference_model(model_path, exe):

    model_abs_path = os.path.join(model_path, '__model__')
    param_abs_path = os.path.join(model_path, '__params__')
    if os.path.exists(model_abs_path) and os.path.exists(param_abs_path):
        return fluid.io.load_inference_model(model_path, exe, '__model__', '__params__')
    else:
        return fluid.io.load_inference_model(model_path, exe)

def feed_randn(block, feed_target_names, batch_size=1, need_save=False):

    feed_dict = dict()

    def set_batch_size(shape, batch_size):
        if shape[0] == -1:
            shape[0] = batch_size
        return shape

    def fill_randn(var_name, batch_size, need_save):
        var = block.var(var_name)
        np_shape = set_batch_size(list(var.shape), 1)
        var_np = {
            core.VarDesc.VarType.BOOL: np.bool_,
            core.VarDesc.VarType.INT32: np.int32,
            core.VarDesc.VarType.INT64: np.int64,
            core.VarDesc.VarType.FP16: np.float16,
            core.VarDesc.VarType.FP32: np.float32,
            core.VarDesc.VarType.FP64: np.float64,
        }
        np_dtype = var_np[var.dtype]
        numpy_array = np.random.random(np_shape).astype(np.float32)
        return numpy_array
    for feed_target_name in feed_target_names:
        feed_dict[feed_target_name] = fill_randn(feed_target_name, batch_size, need_save)
    return feed_dict

def fetch_tmp_vars(block, fetch_targets, var_names_list=None):

    def var_names_of_fetch(fetch_targets):
        var_names_list = []
        for var in fetch_targets:
            var_names_list.append(var.name)
        return var_names_list

    fetch_var = block.var('fetch')
    old_fetch_names = var_names_of_fetch(fetch_targets)
    new_fetch_vars = []
    for var_name in old_fetch_names:
        var = block.var(var_name)
        new_fetch_vars.append(var)

    i = len(new_fetch_vars)
    if var_names_list is None:
        var_names_list = block.vars.keys()
    for var_name in var_names_list:
        # if var_name not in old_fetch_names and var_name != None and var_name != '':
        if '.tmp_' in var_name and var_name not in old_fetch_names:
            var = block.var(var_name)
            new_fetch_vars.append(var)
            block.append_op(
                type='fetch',
                inputs={'X': [var_name]},
                outputs={'Out': [fetch_var]},
                attrs={'col': i})
            i = i + 1
    return new_fetch_vars

def print_results(results, fetch_targets, need_save=True):

    for result in results:
        idx = results.index(result)
        res_np = np.array(result).flatten()
        if res_np.size > 0:
            print('name:', fetch_targets[idx].name, ', size:', res_np.shape, ', avg:', res_np.mean(), \
                  ', min:', res_np.min(), ', max:', res_np.max(), ', arg_max:', np.argmax(res_np))

def fluid_inference_test(model_path, is_feed_randn, arg_name, is_save_result):

    place = fluid.CPUPlace()
    exe = fluid.Executor(place)
    scope = fluid.core.Scope()
    with fluid.scope_guard(scope):
        [net_program, feed_target_names, fetch_targets] = load_inference_model(model_path, exe)
        global_block = net_program.global_block()
        feed_list = feed_randn(global_block, feed_target_names, 1)
        fetch_targets = fetch_tmp_vars(global_block, fetch_targets, arg_name)
        results = exe.run(program=net_program,
                          feed=feed_list,
                          fetch_list=fetch_targets,
                          return_numpy=False)
        print_results(results, fetch_targets, need_save=is_save_result)
        res = np.array(results[0]).flatten()
        sort_index = np.argsort(-res)
        # for i in range(10):
        #     print(" arg " + str(sort_index[i]) + " val " + str(res[sort_index[i]]))

if __name__ == "__main__":

    model_path = ''
    is_feed_ones = False
    is_feed_randn = True
    arg_name = []
    is_save_result = False

    argc = len(sys.argv)
    if argc < 2:
        print('Usage: python ***.py path/to/model arg_name1 arg_name2 ... (arg_names are optional)\n')
        exit()
    model_path = sys.argv[1]
    if argc > 2:
        for i in range(2, argc):
            arg_name.append(sys.argv[i])

    print("arg_names:", arg_name)

    fluid_inference_test(model_path, is_feed_randn, arg_name, is_save_result)

**Comment by jerrywgz** [comment]
如果加载的是inference model的话，需要先手动将fetch op去除，然后将想debug的var的通过名字找到，放到fetch list中，下面是示例代码
```python
def remove_fetch_op(prog):
    for block in prog.blocks:
        for op in block.ops:
            if op.type == "fetch":
                idx = block.opes.index(op)
                block.remove_op(idx)

with fluid.scope_guard(infer_scope):
    [prog, feed, fetch] = fluid.io.load_inference_model('./', exe, '__model__', '__params__')
    remove_fetch_op(prog)
    print(feed, fetch)
    x = fluid.framework._get_var('your_var_name', program=prog)
    print(x)
    tmp = exe.run(prog, feed=feed_list, fetch_list=[x])
    print(tmp)
```

**Comment by taoja12** [comment]
> 如果加载的是inference model的话，需要先手动将fetch op去除，然后将想debug的var的通过名字找到，放到fetch list中，下面是示例代码
> def remove_fetch_op(prog):
>     for block in prog.blocks:
>         for op in block.ops:
>             if op.type == "fetch":
>                 idx = block.opes.index(op)
>                 block.remove_op(idx)
> 
> with fluid.scope_guard(infer_scope):
>     [prog, feed, fetch] = fluid.io.load_inference_model('./', exe, '__model__', '__params__')
>     remove_fetch_op(prog)
>     print(feed, fetch)
>     x = fluid.framework._get_var('your_var_name', program=prog)
>     print(x)
>     tmp = exe.run(prog, feed=feed_list, fetch_list=[x])
>     print(tmp)

我使用 
x = fluid.framework._get_var('vgg_16_conv1_conv1_2_weights', program=prog)
tmp = exe.run(prog, feed=feed_list, fetch_list=[x])

出现错误‘fetch_targets’ does not have save_infer_model/scale_0.tmp_0 variable

import cv2
import numpy as np
import paddle.fluid as fluid

place = fluid.CPUPlace()
exe = fluid.Executor(place)
infer_scope = fluid.core.Scope()

with fluid.scope_guard(infer_scope):
    [prog, feed, fetch] = fluid.io.load_inference_model('../inference_model', exe)

    image = 'imgnet_val_1.jpg'
    image = cv2.imread(image)
    image = cv2.resize(image, (224, 224))
    image = np.array(image).astype('float32').transpose((2, 0, 1)) / 255
    res_list = [image]
    res = res_list[0]
    res = res[np.newaxis, :]
    feed_list = {feed[0]: res}

    # input_image matrix output
    # print(feed_list)

    x = fluid.framework._get_var('vgg_16_conv1_conv1_2_weights', program=prog)

    tmp = exe.run(prog, feed=feed_list, fetch_list=fetch)
    res_np = np.array(tmp).flatten()
    print(res_np)

paddle版本1.7
python 3.6
模型inference_model下载地址
链接: https://pan.baidu.com/s/1Yz_uphSJungpYl_4jWjkCA 提取码: 7va9
