### ISSUE TITLE
fluid.backward 文档不完善

### ISSUE THREAD

**Issue by xwen99** [PaddlePaddle/Paddle#24916]
* 问题：`fluid.backward` 文档不完善：
  * `fluid.backward.gradients`:
    * 此函数在 `targets` 与 `inputs` 属于不同 `program` 时不能使用，然而文档中未给出提示
    * `fluid.gradients` 同样
    * 此种情况应使用 `fluid.backward.append_backward`，文档未给出提示
  * `fluid.backward.append_backward`：
    * `clone program` 时，如果是 `test` 模式，`append` 的梯度会被删掉，文档未给出提示

**Comment by jerrywgz** [comment]
好的，我们会完善下文档，感谢您的反馈
