### ISSUE TITLE
动态图for循环出错

### ISSUE THREAD

**Issue by zhangyimi** [PaddlePaddle/Paddle#24938]
paddle1.8.1 动态图
![image](https://user-images.githubusercontent.com/20926735/83855145-41b4ae00-a74a-11ea-9345-ec0da56c4854.png)
![image](https://user-images.githubusercontent.com/20926735/83855252-6446c700-a74a-11ea-8fee-1b287aac0059.png)

想问下动态图不允许第二种方式么？

**Comment by zhiqiu** [comment]
hi，这个问题应该在develop已经修复了，您可以用dev包试试，近期也会发1.8.2版本修复。

**Comment by zhangyimi** [comment]
好的，多谢~
