### ISSUE TITLE
Question: how/if does TensorFlow's Tensor allocate GPU memory?

### ISSUE THREAD

**Issue by wangkuiyi** [PaddlePaddle/Paddle#2493]
I reviewed the details about how `tensorflow::Tensor` allocate memory in my note https://github.com/PaddlePaddle/Paddle/wiki/tensorflow::Tensor.  However, it seems that it allocate only CPU memory.

@helinwang had thought that `tensorflow::Tensor`'s constructor might accept a raw pointer to externally allocated GPU memory.  But I just checked that the constructor requires an `Allocator` object, other than a pointer.

**Comment by reyoung** [comment]
1. Allocator is an interface class for all devices memory allocation. A tensor takes `Tensor::Tensor(Allocator* a, DataType type, const TensorShape& shape)` as a constructor arguments. We can find [VisitableAllocator](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/common_runtime/visitable_allocator.h#L28) is a subclass of `Allocator`. And GPU allocators, including [GPUDebugAllocator](https://github.com/tensorflow/tensorflow/blob/r1.2/tensorflow/core/common_runtime/gpu/gpu_debug_allocator.h), [PoolAllocator](https://github.com/tensorflow/tensorflow/blob/r1.2/tensorflow/core/common_runtime/gpu/pool_allocator.h#L47), [GPUBFCAllocator](https://github.com/tensorflow/tensorflow/blob/r1.2/tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.h#L37), are sub-class of `VisitableAllocator`. They are defined in `/tensorflow/core/common_runtime/gpu/*_allocator*` files.
1. In OpKernel of TF, it run [forward_input_or_allocate_output]`https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/framework/op_kernel.h#L1381` first and allocate op's output here. In [allocate_output](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/framework/op_kernel.cc#L619), TF new a tensor, and then use [`allocator`](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/framework/op_kernel.cc#L592) to allocate memory. The [`allocator`](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/framework/op_kernel.cc#L249) is basically get from `OpKernel->device_`;

**Comment by wangkuiyi** [comment]
Got it. Thanks! @reyoung
