### ISSUE TITLE
训练报错如下

### ISSUE THREAD

**Issue by AWSWXY** [PaddlePaddle/Paddle#24936]
----------------------
Error Message Summary:
----------------------
Error: Variable value (input) of OP(fluid.layers.embedding) expected >= 0 and < 283925, but got 284239. Please check input value.
  [Hint: Expected ids[i] < row_number, but received ids[i]:284239 >= row_number:283925.] at (/paddle/paddle/fluid/operators/lookup_table_op.h:94)

1
W0605 15:55:10.574888 18079 init.cc:209] Warning: PaddlePaddle catches a failure signal, it may not work properly
W0605 15:55:10.574915 18079 init.cc:211] You could check whether you killed PaddlePaddle thread/process accidentally or report the case to PaddlePaddle
W0605 15:55:10.574921 18079 init.cc:214] The detail failure signal is:

W0605 15:55:10.574929 18079 init.cc:217] *** Aborted at 1591343710 (unix time) try "date -d @1591343710" if you are using GNU date ***
W0605 15:55:10.577302 18079 init.cc:217] PC: @                0x0 (unknown)
W0605 15:55:10.577389 18079 init.cc:217] *** SIGABRT (@0x207000038e9) received by PID 14569 (TID 0x7fb1b4af5700) from PID 14569; stack trace: ***
W0605 15:55:10.579347 18079 init.cc:217]     @     0x7fb23d5f5160 (unknown)
W0605 15:55:10.580796 18079 init.cc:217]     @     0x7fb23cb633f7 __GI_raise
W0605 15:55:10.582262 18079 init.cc:217]     @     0x7fb23cb647d8 __GI_abort
W0605 15:55:10.583017 18079 init.cc:217]     @     0x7fb1a8c4cc65 __gnu_cxx::__verbose_terminate_handler()
W0605 15:55:10.583667 18079 init.cc:217]     @     0x7fb1a8c4ae06 __cxxabiv1::__terminate()
W0605 15:55:10.584373 18079 init.cc:217]     @     0x7fb1a8c4ae33 std::terminate()
W0605 15:55:10.585021 18079 init.cc:217]     @     0x7fb1a8c9d935 execute_native_thread_routine
W0605 15:55:10.586385 18079 init.cc:217]     @     0x7fb23d5ed1c3 start_thread
W0605 15:55:10.587850 18079 init.cc:217]     @     0x7fb23cc1512d __clone
W0605 15:55:10.589207 18079 init.cc:217]     @                0x0 (unknown)

**Comment by AWSWXY** [comment]
版本、环境信息：
   1）PaddlePaddle版本：1.6
   2）CPU：
   3）python 2.7

**Comment by Thunderbrook** [comment]
特征值大于embedding layer的size导致，可调大size
