### ISSUE TITLE
训练Error  Assertion `id < N` failed. Variable value (input) of OP(fluid.layers.embedding) expected >= 0 and < 1853, but got 4460873108026294272. 

### ISSUE THREAD

**Issue by Kevinlsy** [PaddlePaddle/Paddle#24933]
如果您没有查询到相似问题，为快速解决您的提问，建立issue时请提供如下细节信息：
- 版本、环境信息：
    1）PaddlePaddle版本：1.8
    2）CPU：
    3）GPU： CUDA:9.0 CUDNN:7.6
    4）系统环境：CENTOS 6 , python 2.7.12
- 训练信息
    1）单机，单卡
![image](https://user-images.githubusercontent.com/18109329/83846803-c0571e80-a73d-11ea-855a-f35a88eda567.png)

   
- 复现信息：错误看起来像是我输入的id大于variable的尺寸，但是print输出后，没有发现有大于尺寸的id，并且看起来第一个batch已经训练完了。
![image](https://user-images.githubusercontent.com/18109329/83846936-feecd900-a73d-11ea-9bfd-603242667cec.png)每次都会第batch开始报错

- 问题描述：
![image](https://user-images.githubusercontent.com/18109329/83846977-12983f80-a73e-11ea-9eee-f129034992d5.png)
![image](https://user-images.githubusercontent.com/18109329/83847170-5f7c1600-a73e-11ea-98ed-5ae10936a087.png)

**Comment by phlrain** [comment]
是不是ids 里面有负数

**Comment by Kevinlsy** [comment]
> 是不是ids 里面有负数

print输出看起来没有负数。
