### ISSUE TITLE
提取动态图变量中的数据

### ISSUE THREAD

**Issue by a349101311** [PaddlePaddle/Paddle#24947]
需求是将模型中的某特征图中的数据提取出来进行修改，当前动态图变量不支持直接索引修改，所以想到将变量内容提取到numpy数组中修改，但是_var = np.array(var)这样做不到。var为动态图中的变量。
在aistudio上报错信息为：
----------------------
Error Message Summary:
----------------------
Error: end should greater than start
  [Hint: Expected end > start, but received end:2 <= start:2.] at (/paddle/paddle/fluid/operators/slice_op.cc:95)

**Comment by sbl1996** [comment]
```
_var = var.numpy()
_var[0] = 1.
var = to_variable(_var)
```

**Comment by a349101311** [comment]
解决了，谢谢
