### ISSUE TITLE
TypeError: 'paddle.fluid.core_avx.VarBase' object does not support item assignment

### ISSUE THREAD

**Issue by zhangyimi** [PaddlePaddle/Paddle#24940]
paddle1.8.1：动态图如何实现如下的赋值：
![image](https://user-images.githubusercontent.com/20926735/83860925-82b0c080-a752-11ea-8df0-f1b0688c46a7.png)

![image](https://user-images.githubusercontent.com/20926735/83860860-6876e280-a752-11ea-8a03-b590a2572c83.png)

**Comment by zhiqiu** [comment]
hi，您好，这个功能我们会在后面安排支持。

**Comment by zhangyimi** [comment]
现在有什么可替代的操作么

**Comment by a349101311** [comment]
> hi，您好，这个功能我们会在后面安排支持。

如何能将动态图中变量内容提取出来，比如转化成numpy数组

**Comment by ceci3** [comment]
> 现在有什么可替代的操作么

转换成numpy格式，在赋值试下？

**Comment by ceci3** [comment]
> > hi，您好，这个功能我们会在后面安排支持。
> 
> 如何能将动态图中变量内容提取出来，比如转化成numpy数组

直接.numpy()就可以 了

**Comment by zhangyimi** [comment]
> > 现在有什么可替代的操作么
> 
> 转换成numpy格式，在赋值试下？

转成numpy后跟new_x本身的值就没关系吧，new_x是参与梯度传导的

**Comment by ceci3** [comment]
> > > 现在有什么可替代的操作么
> > 
> > 
> > 转换成numpy格式，在赋值试下？
> 
> 转成numpy后跟new_x本身的值就没关系吧，new_x是参与梯度传导的

构造一个mask，np_mask[:, 0] = 0, mask = mask * np_mask这样可以吗
