### ISSUE TITLE
paddle.nn.Pool2D增加data_format参数，跟pool2d保持一致

### ISSUE THREAD

**Issue by jzhang533** [PaddlePaddle/Paddle#24949]
2.0alpha版本（1.8也有这个问题）
我想用Pool2D也想用'NHWC'格式

**Comment by zhiqiu** [comment]
hi，您好，develop版本已经支持了，可以在[这里](https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/install/Tables.html#whl-release)下载。
