### ISSUE TITLE
关于paddle的动态图部署到flask的问题

### ISSUE THREAD

**Issue by zt991211** [PaddlePaddle/Paddle#24951]
```python
@app.route('/predict/<name>')
def prediction(name):
    path=basedir+'\\static\\img\\'+name+'.png'
    img=Image.open(path)
    org_ROI,ROI_PT=get_ROI_region(img)
    with fluid.dygraph.guard(fluid.CPUPlace):
        model = M_net()
        model_state_dict, _ = fluid.load_dygraph('weights/mnet30.pdparams')
        model.load_dict(model_state_dict)
        model.eval()
        img = []
        img.append(transform_img(np.array(ROI_PT)))
        img = np.array(img)
        img = fluid.dygraph.to_variable(img)
        out6, out7, out8, out9, out10 = model(img)
    out10 = out10.numpy()
    out10 = np.reshape(out10, (out10.shape[1], out10.shape[2], out10.shape[3]))
    out10 = np.transpose(out10, (1, 2, 0))
    disc_map = np.array(Image.fromarray(out10[:, :, 0]).resize((600, 600)))
    cup_map = np.array(Image.fromarray(out10[:, :, 1]).resize((600, 600)))
    disc_map[-round(DiscROI_size / 3):, :] = 0
    cup_map[-round(DiscROI_size / 2):, :] = 0
    De_disc_map = cv2.linearPolar(rotate(disc_map, 90), (DiscROI_size / 2, DiscROI_size / 2),
                                  DiscROI_size / 2, cv2.WARP_FILL_OUTLIERS + cv2.WARP_INVERSE_MAP)
    De_cup_map = cv2.linearPolar(rotate(cup_map, 90), (DiscROI_size / 2, DiscROI_size / 2),
                                 DiscROI_size / 2, cv2.WARP_FILL_OUTLIERS + cv2.WARP_INVERSE_MAP)
    ret, De_cup_map = cv2.threshold(De_cup_map, 0.5, 1, cv2.THRESH_BINARY)
    res, De_disc_map = cv2.threshold(De_disc_map, 0.5, 1, cv2.THRESH_BINARY)
    disc_h, disc_w = getCDR(De_disc_map)
    cup_h, cup_w = getCDR(De_cup_map)
    V_cdr=cup_h * 1.00 / disc_h
    print(V_cdr)
    res=make_response(jsonify({"size":str(V_cdr)}))
    res.headers['Access-Control-Allow-Origin'] = '*'
```

使用了guard动态图模式后，该api无法执行返回操作，print操作正常，我推测是动态图的相关模式没有关掉，调用api一直处于等待没有返回值
之前利用函数封装的形式也是同样的问题，https://ai.baidu.com/forum/topic/show/960176
谢谢大佬帮我解答

**Comment by Xreki** [comment]
你好，Paddle的`with fluid.dygraph.guard(fluid.CPUPlace())`应该不存在不能返回这样的问题。我做了一个简单的实验：

```python
import paddle.fluid as fluid
import numpy as np

def prediction():
    x = np.random.random([4, 4]).astype("float32")
    y = np.random.random([4, 4]).astype("float32")
    with fluid.dygraph.guard(fluid.CPUPlace()):
        var_x = fluid.dygraph.to_variable(x)
        var_y = fluid.dygraph.to_variable(y)
        out = fluid.layers.mul(var_x, var_y).numpy()
    return out

if __name__ == '__main__':
    out = prediction()
    print(out)
```

是能正常输出的：
```
$ python test.py
[[1.6791484  1.4669528  1.3813748  0.46385866]
 [0.76390356 0.39018098 0.90615344 0.37601736]
 [1.066571   0.87213814 1.1391505  0.4151447 ]
 [1.4643705  0.912284   1.4869107  0.40906245]]
```

不知道这个实验能否证明问题。另外，能否去除你的测试代码中与dygraph无关的代码，测试下看看功能是否正常？

**Comment by zt991211** [comment]
https://ai.baidu.com/forum/topic/show/960176这是我之前提的问题，就是动态图会有结果，但是无法返回到flask里面，后面我换成静态模型就成功了




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Yiqun Liu"<notifications@github.com&gt;; 
发送时间: 2020年6月8日(星期一) 中午11:26
收件人: "PaddlePaddle/Paddle"<Paddle@noreply.github.com&gt;; 
抄送: "张桐"<814943622@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [PaddlePaddle/Paddle] 关于paddle的动态图部署到flask的问题 (#24951)





 
你好，Paddle的with fluid.dygraph.guard(fluid.CPUPlace())应该不存在不能返回这样的问题。我做了一个简单的实验：
 import paddle.fluid as fluid import numpy as np def prediction():     x = np.random.random([4, 4]).astype("float32")     y = np.random.random([4, 4]).astype("float32")     with fluid.dygraph.guard(fluid.CPUPlace()):         var_x = fluid.dygraph.to_variable(x)         var_y = fluid.dygraph.to_variable(y)         out = fluid.layers.mul(var_x, var_y).numpy()     return out if __name__ == '__main__':     out = prediction()     print(out)
 
是能正常输出的：
 $ python test.py [[1.6791484  1.4669528  1.3813748  0.46385866]  [0.76390356 0.39018098 0.90615344 0.37601736]  [1.066571   0.87213814 1.1391505  0.4151447 ]  [1.4643705  0.912284   1.4869107  0.40906245]]  
不知道这个实验能否证明问题。另外，能否去除你的测试代码中与dygraph无关的代码，测试下看看功能是否正常？

**Comment by Xreki** [comment]
能不能提供一个能复现你这个问题的代码呢？
