### ISSUE TITLE
AttentionLSTM使用--resume指定预训练权重训练报错

### ISSUE THREAD

**Issue by Derek-Kun** [PaddlePaddle/Paddle#24956]
我用命令行
sudo /home/rd/anaconda3/envs/paddle_env/bin/python train.py --model_name=AttentionLSTM --config=./configs/attention_lstm.yaml --log_interval=10 --valid_interval=1 --use_gpu=True --save_dir=./data/checkpoints --fix_random_seed=False 
进行训练，一切正常，可是我下载了 AttentionLSTM.pdparams想用预训练模型做FineTune,命令行如下：
sudo /home/rd/anaconda3/envs/paddle_env/bin/python train.py --model_name=AttentionLSTM --config=./configs/attention_lstm.yaml --log_interval=10 --valid_interval=1 --use_gpu=True --save_dir=./data/checkpoints --fix_random_seed=False --resume=/home/dukun/models-develop/PaddleCV/video/AttentionLSTM

一开始我我resume那儿最后一行写的是AttentionLSTM.pdparams，结果报错说找不到AttentionLSTM.pdparams.pdparams,于是我就把AttentionLSTM.pdparams改成了AttentionLSTM，结果运行之后又报错，报错信息如下：

Traceback (most recent call last):
  File "train.py", line 259, in <module>
    train(args)
  File "train.py", line 166, in train
    fluid.load(train_prog, model_path=args.resume, executor=exe)
  File "/home/rd/anaconda3/envs/paddle_env/lib/python3.6/site-packages/paddle/fluid/io.py", line 1774, in load
    "Optimizer file [{}] not exits".format(opt_file_name)
AssertionError: Optimizer file [/home/dukun/models-develop/PaddleCV/video/AttentionLSTM.pdopt] not exits

请问如何解决?

**Comment by huangjun12** [comment]
看报错信息：pdparams文件保存的是模型参数，pdopt文件存储优化器信息；
代码中的`--resume`参数的功能是：我们在训练时保存下checkpoint(包含模型参数和优化器等信息)，用于后续的断点续传；
而视频库中(https://paddlemodels.bj.bcebos.com/video_classification/AttentionLSTM.pdparams) 提供的只有AttentionLSTM.pdparams文件，没有pdopt文件，故报错。

如果您在使用video_tag，想对其中的attentionLSTM部分进行fine-tune，您需要下载的是
https://github.com/PaddlePaddle/models/tree/develop/PaddleCV/video/application/video_tag 里提供的checkpoint文件。
<img width="954" alt="image" src="https://user-images.githubusercontent.com/22365664/84102440-0c0e0e80-aa43-11ea-9758-d046dfbff4ec.png">

同时参考 (https://github.com/PaddlePaddle/models/tree/develop/PaddleCV/video/application/video_tag/models/attention_lstm) 对应修改模型文件 (https://github.com/PaddlePaddle/models/tree/release/1.8/PaddleCV/video/models/attention_lstm)

**Comment by Derek-Kun** [comment]
好的非常感谢
