### ISSUE TITLE
关于静态图转向动态图的TracedLayer的文档不能实现

### ISSUE THREAD

**Issue by zt991211** [PaddlePaddle/Paddle#24950]
我的相关报错源码如下：
```python
if __name__ == '__main__':
    # 创建模型
    img=[]
    img.append(transform_img(np.array(Image.open('/home/aistudio/work/train-images/V0001_0.png'))))
    img = np.array(img).astype('float32')
    DiscROI_size=600
    with fluid.dygraph.guard():
        model = M_net()
        #启动训练过程
        #train(model)
        model_state_dict, _ = fluid.load_dygraph('/home/aistudio/work/mnet30.pdparams')
        model.load_dict(model_state_dict)
        in_var = fluid.dygraph.to_variable(img)
        out_dygraph, static_layer = fluid.dygraph.TracedLayer.trace(model, inputs=[in_var])
        out_static_graph = static_layer([in_var])
        static_layer.save_inference_model(dirname='/home/aistudio/work/mnet_model')
    place = fluid.CPUPlace()
    exe = fluid.Executor(place)
    program, feed_vars, fetch_vars = fluid.io.load_inference_model('/home/aistudio/work/mnet_model',
    executor=exe)
    fetch, = exe.run(program, feed={feed_vars[0]: in_var},fetch_list=fetch_vars)
    print(fetch.shape)
```

基本是按照文档源码的格式写的，但现在报错了
出现在fluid.io.load_inference_model('/home/aistudio/work/mnet_model',
    executor=exe)这一行

报错原因如下：
报错在那个exe那里
ValueError：‘type’ to initialized an Operator can not be None。

**Comment by Xreki** [comment]
`ValueError：‘type’ to initialized an Operator can not be None`

`load_inference_model`时会根据保存的模型信息来定义Program里面的Variable和Operator，从报错信息来看是在定义Operator出的错，错误原因是Operator的type是None。

请问下您是使用的aistudio上面的示例代码吗，使用的是哪个示例代码呢？能否提供下链接，我这边看能不能复现。

**Comment by zt991211** [comment]
谢谢你，我昨天已经找到错误了，exe和dygraph有冲突，要分开运行就好了。之前那个TracedLayer文档里是两个写在一起的，所以我最开始也是写在一起的，我以为dygraph不会和exe冲突。



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Yiqun Liu"<notifications@github.com&gt;; 
发送时间: 2020年6月8日(星期一) 上午10:49
收件人: "PaddlePaddle/Paddle"<Paddle@noreply.github.com&gt;; 
抄送: "张桐"<814943622@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [PaddlePaddle/Paddle] 关于静态图转向动态图的TracedLayer的文档不能实现 (#24950)





 
ValueError：‘type’ to initialized an Operator can not be None
 
load_inference_model时会根据保存的模型信息来定义Program里面的Variable和Operator，从报错信息来看是在定义Operator出的错，错误原因是Operator的type是None。请问下您是使用的aistudio上面的示例代码吗，使用的是哪个示例代码呢？能否提供下链接，我这边看能不能复现。

**Comment by Xreki** [comment]
> 我昨天已经找到错误了，exe和dygraph有冲突，要分开运行就好了。

👋  

> 之前那个TracedLayer文档里是两个写在一起的，所以我最开始也是写在一起的，我以为dygraph不会和exe冲突。

这个问题，我会向相关负责的同学反馈下。

**Comment by Xreki** [comment]
@zt991211 请问你说的「exe和dygraph有冲突」是什么意思呢？ https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api_cn/imperative_cn/TracedLayer_cn.html#tracedlayer 这个文档的最后一个示例代码，我可以正常运行。

**Comment by zt991211** [comment]
我是在AI studio里面运行的，类似这段代码，一直运行报错，就load那一行，报的就是Type那个错误，然后我想了想，guard外面的exe先注释，运行里面的，有了模型后，把guard那一段注释，再运行外面的exe，就好了。






------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Yiqun Liu"<notifications@github.com&gt;; 
发送时间: 2020年6月8日(星期一) 中午12:10
收件人: "PaddlePaddle/Paddle"<Paddle@noreply.github.com&gt;; 
抄送: "张桐"<814943622@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [PaddlePaddle/Paddle] 关于静态图转向动态图的TracedLayer的文档不能实现 (#24950)





 
@zt991211 请问你说的「exe和dygraph有冲突」是什么意思呢？ https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api_cn/imperative_cn/TracedLayer_cn.html#tracedlayer 这个文档的最后一个示例代码，我可以正常运行。

**Comment by Xreki** [comment]
请问你使用的Paddle版本是多少？有在本地环境尝试过吗？

**Comment by Zaoyee** [comment]
请问可以详细的解决方法吗？我也有相同的问题。我简单的跑了一下 [这里](https://www.paddlepaddle.org.cn/documentation/docs/zh/beginners_guide/basic_concept/dygraph/DyGraph.html) 的例子。

问题也同样出现在`program, feed_vars, fetch_vars = fluid.io.load_inference_model(save_dirname, exe)`
我系统是MacOS 10.15.4，paddle版本是1.8，是在本地运行的。
