### ISSUE TITLE
Red hat 4.85nGetVersion at (/paddle/paddle/fluid/platform/dynload/cudnn.cc:63)

### ISSUE THREAD

**Issue by Derek-Kun** [PaddlePaddle/Paddle#24953]
说是 Can not find library: libcudnn.so. 我也查了之前几个相同问题的，我按CENTOS系统装的1.8.1 GPU版本，CUDA 10.0， CUDNN 7.6.5, 也按照之前提问的在/etc/profile 里添加了环境变量
export CUDNN=/usr/local/cuda/lib64/libcudnn.so.7.6.5:$CUDNN
然后激活了，可是并没有什么卵用，再次运行还是报同样错误， 请问是什么原因

**Comment by heavengate** [comment]
`export CUDNN=/usr/local/cuda/lib64/libcudnn.so.7.6.5:$CUDNN`改为`export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/cuda/lib64/`试下
