### ISSUE TITLE
如何新建序列数据

### ISSUE THREAD

**Issue by OliveLv** [PaddlePaddle/Paddle#24963]
输入是10 X 30的序列数据（一行），表示10个序列，每个序列有30个特征，这种该怎么新建
用 data = fluid.layers.data(name="x", shape=[300],dtype="float32", lod_level=1)
提示：
Error: the provided recursive_sequence_lengths info is invalid
reader是直接返回10X30的list，需要新建fluid.create_lod_tensor？

**Comment by heavengate** [comment]
`data = fluid.data(name='x', shape=[None], dtype='float32', lod_level=1)` 试下呢

**Comment by OliveLv** [comment]
N=10
M=30
data = fluid.data(name='x', shape=[N*M], dtype='float32', lod_level=1)

**reader**
input_list = [1.0,2.0,1.1.....] (300个)
return yield ("x", input_list)
提示：Error: the provided recursive_sequence_lengths info is invalid
  [Hint: Expected CheckLoD(new_offset_lod, vectorize(self.dims()).front()) == true, but received CheckLoD(new_offset_lod, vectorize(self.dims()).front()):0 != true:1.] at (/paddle/paddle/fluid/pybind/pybind.cc:731)

使用：
input_lod = fluid.create_lod_tensor(data=np.array(input_list), recursive_seq_lens=[[len(input_list)]], place=self.place)
return yield ("x", input_lod)
提示 TypeError: object of type 'paddle.fluid.core_avx.LoDTensor' has no len()


辛苦帮忙看下reader怎么设置

**Comment by OliveLv** [comment]
> `data = fluid.data(name='x', shape=[None], dtype='float32', lod_level=1)` 试下呢

还是不行，辛苦帮忙看下reader怎么设置

**Comment by heavengate** [comment]
1. yield和return不要放在一行用，直接yield就可以了，读数据结束了再return
2. 应该yiled的数据格式是list of sample，最外层list包的是sample的数据，sample也是一个list包着每个field的数据

**Comment by OliveLv** [comment]
> 1. yield和return不要放在一行用，直接yield就可以了，读数据结束了再return
> 2. 应该yiled的数据格式是list of sample，最外层list包的是sample的数据，sample也是一个list包着每个field的数据

没有returen，直接用了yield

**Comment by heavengate** [comment]
> > 1. yield和return不要放在一行用，直接yield就可以了，读数据结束了再return
> > 2. 应该yiled的数据格式是list of sample，最外层list包的是sample的数据，sample也是一个list包着每个field的数据
> 
> 没有returen，直接用了yield

看你yield的是一个带字符串的元组，不应该是这种格式，reader里应该yield上面说的list of sample这种格式

**Comment by OliveLv** [comment]
> > > 1. yield和return不要放在一行用，直接yield就可以了，读数据结束了再return
> > > 2. 应该yiled的数据格式是list of sample，最外层list包的是sample的数据，sample也是一个list包着每个field的数据
> > 
> > 
> > 没有returen，直接用了yield
> 
> 看你yield的是一个带字符串的元组，不应该是这种格式，reader里应该yield上面说的list of sample这种格式

主要想了解下lod_level=0和lod_level=1时，reader返回的数据有什么区别
