### ISSUE TITLE
[编译错误] cmake版本为3.12和3.17，PaddlePaddle源码编译报nvcc错误

### ISSUE THREAD

**Issue by juncaipeng** [PaddlePaddle/Paddle#24983]
- 标题：Linux编译错误
- 版本、环境信息：
    1）PaddlePaddle版本：8603b5fb722692bfee148ddf30ee9c3a7d39a5e1
    2）CPU：MKL/OpenBlas/MKLDNN/ 都是使用默认编译选项
    3）GPU：V100，CUDA Version 9.0.176
    4）系统环境：Ubuntu 16.04.4 LTS, Python2.7  
- 复现信息：
    1）cmake命令：
    `cmake .. -DWITH_GPU=ON -DWITH_TESTING=ON -DCMAKE_BUILD_TYPE=Release -DPY_VERSION=2.7`
    2)  cmake为3.10版本，编译正常。cmake为3.12和3.17版本，编译中报nvcc错误，如下
    `nvcc fatal : redefinition of argument 'std'` 。

> 内部汇报case，可以联系 juncai

**Comment by luotao1** [comment]
@T8T9 请帮忙看下
