### ISSUE TITLE
Conv2D的中英文文档不一致。

### ISSUE THREAD

**Issue by jzhang533** [PaddlePaddle/Paddle#24993]
1.8 版本及2.0-alpha版本里的Conv2D关于参数的初始化的方式的描述两边不一样，英文的应该是对的。

中文版：
param_attr (ParamAttr, 可选) - 指定权重参数属性的对象。默认值为None，表示使用默认的权重参数属性。具体用法请参见 ParamAttr 。
如果顺着看ParamAttr，是xavier初始化。

英文版：
param_attr (ParamAttr, optional): The parameter attribute for learnable weights(Parameter)
 |          of conv2d. If it is set to None or one attribute of ParamAttr, conv2d
 |          will create ParamAttr as param_attr. If the Initializer of the param_attr
 |          is not set, the parameter is initialized with :math:`Normal(0.0, std)`,
 |          and the :math:`std` is :math:`(\frac{2.0 }{filter\_elem\_num})^{0.5}`. Default: None.

为使您的问题得到快速解决，在建立Issues前，请您先通过如下方式搜索是否有相似问题:【搜索issue关键字】【使用labels筛选】【官方文档】

如果您没有查询到相似问题，为快速解决您的提问，建立issue时请提供如下细节信息：
- 标题：简洁、精准概括您的问题，例如“Insufficient Memory xxx" ”
- 版本、环境信息：
    1）PaddlePaddle版本：请提供您的PaddlePaddle版本号，例如1.1或CommitID
    2）CPU：预测若用CPU，请提供CPU型号，MKL/OpenBlas/MKLDNN/等数学库使用情况
    3）GPU：预测若用GPU，请提供GPU型号、CUDA和CUDNN版本号
    4）系统环境：请您描述系统类型、版本，例如Mac OS 10.14，Python版本
- 训练信息
    1）单机/多机，单卡/多卡
    2）显存信息
    3）Operator信息
- 复现信息：如为报错，请给出复现环境、复现步骤
- 问题描述：请详细描述您的问题，同步贴出报错信息、日志、可复现的代码片段

Thank you for contributing to PaddlePaddle.
Before submitting the issue, you could search issue in the github in case that there was a similar issue submitted or resolved before.
If there is no solution,please make sure that this is a training issue including the following details:
**System information**
-PaddlePaddle version （eg.1.1）or CommitID
-CPU: including CPUMKL/OpenBlas/MKLDNN version
-GPU: including CUDA/CUDNN version
-OS Platform (eg.Mac OS 10.14)
-Other imformation: Distriuted training/informantion of operator/
Graphics card storage
**To Reproduce**
Steps to reproduce the behavior
**Describe your current behavior**
**Code to reproduce the issue**
**Other info / logs**

**Comment by hutuxian** [comment]
确认一下，您的点是中文版点击ParamAttr，链接过去的是xavier初始化？我这边看到的好像不是这样，链接过去是正常的介绍ParamAttr的页面。

**Comment by jzhang533** [comment]
<img width="1097" alt="Screen Shot 2020-06-10 at 21 09 11" src="https://user-images.githubusercontent.com/29231/84271612-e83feb00-ab5e-11ea-825e-c7527c2a3a9c.png">

**Comment by jzhang533** [comment]
关于`param_attr`这个入参的描述，中文和英文明显对不上。

**Comment by hutuxian** [comment]
感谢反馈！
