### ISSUE TITLE
动态图dataloader报错

### ISSUE THREAD

**Issue by a349101311** [PaddlePaddle/Paddle#24996]
W0610 14:46:24.043071 29632 device_context.cc:252] Please NOTE: device: 0, CUDA Capability: 52, Driver API Version: 10.1, Runtime API Version: 10.0
W0610 14:46:24.046782 29632 device_context.cc:260] device: 0, cuDNN Version: 7.6.
2020-06-10 14:46:26,444-ERROR: DataLoader reader thread raised an exception!
2020-06-10 14:46:26,444 - dataloader_iter.py[line:328] - ERROR: DataLoader reader thread raised an exception!
Traceback (most recent call last):
  File "train.py", line 141, in <module>
    train()
  File "train.py", line 109, in train
    for batch_id, (left, right, disp) in enumerate(loader()):
  File "/home/zhangqi/anaconda3/envs/icprnet/lib/python3.5/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 503, in __next__
    data = self._reader.read_next_var_list()
paddle.fluid.core_avx.EnforceNotMet:

--------------------------------------------
C++ Call Stacks (More useful to developers):
--------------------------------------------
0   std::string paddle::platform::GetTraceBackString<std::string const&>(std::string const&, char const*, int)
1   paddle::platform::EnforceNotMet::EnforceNotMet(std::string const&, char const*, int)
2   paddle::operators::reader::BlockingQueue<std::vector<paddle::framework::LoDTensor, std::allocator<paddle::framework::LoDTensor> > >::Receive(std::vector<paddle::framework::LoDTensor, std::allocator<paddle::framework::LoDTensor> >*)
3   paddle::operators::reader::PyReader::ReadNext(std::vector<paddle::framework::LoDTensor, std::allocator<paddle::framework::LoDTensor> >*)
4   std::_Function_handler<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> (), std::__future_base::_Task_setter<std::unique_ptr<std::__future_base::_Result<unsigned long>, std::__future_base::_Result_base::_Deleter>, unsigned long> >::_M_invoke(std::_Any_data const&)
5   std::__future_base::_State_base::_M_do_set(std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> ()>&, bool&)
6   ThreadPool::ThreadPool(unsigned long)::{lambda()#1}::operator()() const

----------------------
Error Message Summary:
----------------------
Error: Blocking queue is killed because the data reader raises an exception
  [Hint: Expected killed_ != true, but received killed_:1 == true:1.] at (/paddle/paddle/fluid/operators/reader/blocking_queue.h:141)

我换了文档里随机的那个数据集没有Bug，所以貌似是dataset定义的问题
定于数据集代码如下：
class Sceneflow_dataset(Dataset):
    def __init__(self, num_samples, file_list, data_dir, mode, maxdisp):
        self.num_samples = num_samples
        self.file_list = file_list
        self.data_dir = data_dir
        self.mode = mode
        self.maxdisp = maxdisp

    def __getitem__(self, idx):
        lists = []
        with open(self.file_list, 'r') as f:
            for line in f.readlines():
                lines = line.strip()
                lists.append(lines)
        for lines in lists:
            left_image, right_image, disp_image = lines.split()
            left_image = os.path.join(self.data_dir, left_image)
            right_image = os.path.join(self.data_dir, right_image)
            disp_image = os.path.join(self.data_dir, disp_image)

            left = cv2.imread(left_image)
            right = cv2.imread(right_image)
            disp = load_disp(disp_image)
            if self.mode == 'train':
                h, w = left.shape[0:2]
                crop_w, crop_h = 512, 256
                x1 = random.randint(0, w - crop_w)
                y1 = random.randint(0, h - crop_h)

                left = left[y1:y1 + crop_h, x1:x1 + crop_w]
                right = right[y1:y1 + crop_h, x1:x1 + crop_w]
                disp = disp[y1:y1 + crop_h, x1:x1 + crop_w]
                mask = (disp < self.maxdisp) & (disp > 0)
                disp = disp[mask]
                left = transform(left)
                right = transform(right)
                left = left.astype('float32')
                right = right.astype('float32')
                return left, right, disp
            else:
                h, w = left.shape[0:2]
                crop_w, crop_h = 960, 512

                left = left.crop((h - crop_h, w - crop_w, h, w))
                right = right.crop((h - crop_h, w - crop_w, h, w))
                disp = disp[h - crop_h:h, w - crop_w: w]
                mask = (disp < self.maxdisp) & (disp > 0)
                disp = disp[mask]
                left = transform(left)
                right = transform(right)
                left = left.astype('float32')
                right = right.astype('float32')
                return left, right, disp

    def __len__(self):
        return self.num_samples`

**Comment by zhao181** [comment]
题主  您好 请问您这个问题是如何得到解决的?  我的num_workers设为0可正常工作  设置为2就报同样的错误
