### ISSUE TITLE
训练结束前出现PaddlePaddle catches a failure signal, it may not work properly的错误

### ISSUE THREAD

**Issue by hweidream** [PaddlePaddle/Paddle#24991]
padddle版本：1.7，cuda: 9，ducnn：7

terminate called without an active exception
W0610 01:00:51.426717 18382 init.cc:209] Warning: PaddlePaddle catches a failure signal, it may not work properly
W0610 01:00:51.426740 18382 init.cc:211] You could check whether you killed PaddlePaddle thread/process accidentally or report the case to PaddlePaddle
W0610 01:00:51.426757 18382 init.cc:214] The detail failure signal is:

W0610 01:00:51.426764 18382 init.cc:217] *** Aborted at 1591722051 (unix time) try "date -d @1591722051" if you are using GNU date ***
W0610 01:00:51.428297 18382 init.cc:217] PC: @                0x0 (unknown)
W0610 01:00:51.428371 18382 init.cc:217] *** SIGABRT (@0x1f4000074e3) received by PID 29923 (TID 0x7fba96d73700) from PID 29923; stack trace: ***
W0610 01:00:51.429654 18382 init.cc:217]     @     0x7fbada922160 (unknown)
W0610 01:00:51.431064 18382 init.cc:217]     @     0x7fbad9e903f7 __GI_raise
W0610 01:00:51.432423 18382 init.cc:217]     @     0x7fbad9e917d8 __GI_abort
W0610 01:00:51.433231 18382 init.cc:217]     @     0x7fba41badc65 __gnu_cxx::__verbose_terminate_handler()
W0610 01:00:51.433846 18382 init.cc:217]     @     0x7fba41babe06 __cxxabiv1::__terminate()
W0610 01:00:51.434612 18382 init.cc:217]     @     0x7fba41babe33 std::terminate()
W0610 01:00:51.435289 18382 init.cc:217]     @     0x7fba41baba87 __gxx_personality_v0
W0610 01:00:51.435933 18382 init.cc:217]     @     0x7fba85899964 _Unwind_ForcedUnwind_Phase2
W0610 01:00:51.436575 18382 init.cc:217]     @     0x7fba85899cb4 _Unwind_ForcedUnwind
W0610 01:00:51.437805 18382 init.cc:217]     @     0x7fbada920c30 __GI___pthread_unwind
W0610 01:00:51.439019 18382 init.cc:217]     @     0x7fbada91b565 __pthread_exit
W0610 01:00:51.439347 18382 init.cc:217]     @           0x54aadc PyThread_exit_thread
W0610 01:00:51.439632 18382 init.cc:217]     @           0x4f4777 PyEval_RestoreThread
W0610 01:00:51.441542 18382 init.cc:217]     @     0x7fba1c0a79c9 pybind11::gil_scoped_release::~gil_scoped_release()
W0610 01:00:51.441781 18382 init.cc:217]     @     0x7fba1c0543f4 _ZZN8pybind1112cpp_function10initializeIZN6paddle6pybindL22pybind11_init_core_avxERNS_6moduleEEUlRNS2_9operators6reader22LoDTensorBlockingQueueERKSt6vectorINS2_9framework9LoDTensorESaISC_EEE60_bIS9_SG_EINS_4nameENS_9is_methodENS_7siblingEEEEvOT_PFT0_DpT1_EDpRKT2_ENUlRNS_6detail13function_callEE1_4_FUNESY_
W0610 01:00:51.443594 18382 init.cc:217]     @     0x7fba1c0c5d41 pybind11::cpp_function::dispatcher()
W0610 01:00:51.443948 18382 init.cc:217]     @           0x5a9b49 PyCFunction_Call
W0610 01:00:51.444258 18382 init.cc:217]     @           0x4fe586 PyEval_EvalFrameEx
W0610 01:00:51.444308 18382 init.cc:217]     @           0x4ff451 _PyEval_EvalCodeWithName
W0610 01:00:51.444631 18382 init.cc:217]     @           0x4ff538 PyEval_EvalCodeEx
W0610 01:00:51.444885 18382 init.cc:217]     @           0x5a4977 function_call
W0610 01:00:51.445225 18382 init.cc:217]     @           0x437ba0 PyObject_Call
W0610 01:00:51.445526 18382 init.cc:217]     @           0x4f5c80 PyEval_EvalFrameEx
W0610 01:00:51.445875 18382 init.cc:217]     @           0x4fcc8e PyEval_EvalFrameEx
W0610 01:00:51.446180 18382 init.cc:217]     @           0x4fcc8e PyEval_EvalFrameEx
W0610 01:00:51.446228 18382 init.cc:217]     @           0x4ff451 _PyEval_EvalCodeWithName
W0610 01:00:51.446547 18382 init.cc:217]     @           0x4ff538 PyEval_EvalCodeEx
W0610 01:00:51.446799 18382 init.cc:217]     @           0x5a488c function_call
W0610 01:00:51.447139 18382 init.cc:217]     @           0x437ba0 PyObject_Call
W0610 01:00:51.447384 18382 init.cc:217]     @           0x597a8d method_call
W0610 01:00:51.447719 18382 init.cc:217]     @           0x437ba0 PyObject_Call
W0610 01:00:51.448004 18382 init.cc:217]     @           0x4f4df7 PyEval_CallObjectWithKeywords

**Comment by hutuxian** [comment]
报错信息不足以定位出错原因。请尽可能提供一个最小可复现的代码样例，便于我们提供帮助。
Tips，您可以一点一点缩减程序，例如只训练一个batch看是否出错。
