### ISSUE TITLE
三层CNN, cifar10数据集，用momentum不收敛，用adam准确率比tf低3%~4%

### ISSUE THREAD

**Issue by jzhang533** [PaddlePaddle/Paddle#24999]
2.0-alpha 版本的飞桨。
对比结果如下面两张图：

使用adam
![adam](https://user-images.githubusercontent.com/29231/84238444-a6e31780-ab2d-11ea-8fa4-69343379ec26.png)

使用momentum
![momentum](https://user-images.githubusercontent.com/29231/84238463-acd8f880-ab2d-11ea-8c9d-f5a0838765cd.png)

BTW: mnist数据集，mlp网络用momentum可以收敛。

用来复现的notebook（可以在colab上，gpu运行）
https://gist.github.com/jzhang533/df107c3a91d896874b6437caf2907be0

**Comment by hutuxian** [comment]
感谢使用Paddle。
请首先确认是否所有的超参数（学习率，初始化方法等等）都和benchmark的方法对齐？

**Comment by jzhang533** [comment]
肯定是对齐了的啊，我贴复现的代码了，你点开看了吗？

**Comment by parap1uie-s** [comment]
> 肯定是对齐了的啊，我贴复现的代码了，你点开看了吗？

非官方回复

没有理解错的话，你用的是Paddle的动态图模式。

你的notebook里Cell 25里，Paddle模型训练的时候，只有loss计算，但没有backward()和minimize()的操作

关于动态图的使用，可以参考这里
`https://www.paddlepaddle.org.cn/tutorials/projectdetail/386189`

**Comment by shippingwang** [comment]
paddle 的momentum实现和tf 有区别，相同参数不收敛。Adam低3%的问题需要再看

**Comment by jzhang533** [comment]
更新一下：1.8.2版本的paddle，同样的任务和参数设置，用Momentum是可以收敛的。
复现地址：https://gist.github.com/jzhang533/cc74fbb9fa1f1604791accdd520f6def

2.0-alpha版本的paddle，做文本分类也有不收敛的问题。
复现地址：https://gist.github.com/jzhang533/78d7b9674a272e58cd56763b884f5ff6
