### ISSUE TITLE
每一个Op的属性应该如何检查与表示?

### ISSUE THREAD

**Issue by reyoung** [PaddlePaddle/Paddle#2499]
在神经网络框架中，每一个`Op`都有可能设置一些属性信息。譬如对于`cosine_similarity`来说，可以设置的属性为"scale"，默认值是1.0，类型是float型。

这些信息，首先用户可以进行配置，其次神经网络框架需要进行检查。

# 背景

## 用户配置属性信息

在Caffe2/Tensorflow中，由于这二者用户配置信息都使用了`protobuf`，而`protobuf`并没有`variant`类型，于是二者均使用下面这种逻辑实现。

```proto
message Attribute {
  required string name = 1;
  optional int i_val = 2;
  optional float f_val = 3;
  ...
  repeated float floats = 10;
  repeated int64 ints = 12;
}

message Operation {
  ...
  repeated Attribute attrs = 10;
};
```

[Caffe2](https://github.com/caffe2/caffe2/blob/master/caffe2/proto/caffe2.proto#L97)与[Tensorflow](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/framework/attr_value.proto#L16)的实现与上述代码类似。Tensorflow相交于Caffe2，使用了Protobuf3的[map](https://developers.google.com/protocol-buffers/docs/proto#maps)与[oneof](https://developers.google.com/protocol-buffers/docs/proto#using-oneof)语法，使其在C++端访问attrs的效率变高，但是参考protobuf文档，使用oneof与map的Tensorflow与Caffe2的`optional`消息`wire-format`一致。

而MXNet是在C++端实现的属性信息，实现方式为:

```cpp
map<string, string> attrs_;
```
在MXNet中，使用[`Set(void* attr, string val);`](https://github.com/dmlc/dmlc-core/blob/a6c5701219e635fea808d264aefc5b03c3aec314/include/dmlc/parameter.h#L303)进行字符串的解析。

## 框架检查用户的配置:

* Caffe2中没有检查用户配置每一个Op属性的合法性。
* Tensorflow中，Attr的约束使用字符串配置([Example](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/ops/ctc_ops.cc#L32))。使用C++端解析这个字符串，并且检查用户的配置信息。
* MXNet中，因为MXNet使用C++记录用户配置信息和每一个Op的属性约束。直接将属性约束记录成了`std::function`。所以检查用户配置就是执行这些函数即可。

**Comment by reyoung** [comment]
这个讨论是 #2483 的一部分。即讨论在

```cpp
struct Op {
   ...
   map<string, ???> attrs_;
};
```

中，`???`是什么类型的。这个类型用户如何设置默认值，最大值，最小值，类型等检查约束。

**Comment by jacquesqiao** [comment]
我们最终要使用protobuf来表示graph or  graph中的一部分么？
目前caffe和tf用了protobuf，mxnet用c++端的symbol来表示，用json来做序列化和反序列化。

**Comment by reyoung** [comment]
> 我们最终要使用protobuf来表示graph or graph中的一部分么？
目前caffe和tf用了protobuf，mxnet用c++端的symbol来表示，用json来做序列化和反序列化。

这个我们再开另一个issue讨论吧。。我先去新建一个issue讨论这些，列举下使用protobuf和C++做配置信息的优缺点。

**Comment by reyoung** [comment]
我的看法是:

## 配置属性信息的类型

参考majel的实现，Op的配置参数类型可以是[`boost::variant`](http://www.boost.org/doc/libs/1_64_0/doc/html/variant.html)。`boost::variant`是一种强类型的`unoin`，而Op的属性确实需要支持有限多个类型。

具体实现可以为:

```cpp
using Attribute = boost::variant<
    boost::blank,  // default variant value is empty.
    int,
    float,
    std::string,
    std::vector<int>,
    std::vector<float>,
    std::vector<std::string>
  >;
using AttributeMap = std::unordered_map<std::string, Attribute>;
```
所以，Op在C++端的类型可以描述为:

```cpp
struct Op {
   ... // discuessed before
   AttributeMap attrs_;
};
```

### boost::variant的序列化

boost::variant序列化可以使用`visitor`来完成。方法为:

```cpp
struct SimpleSerializer : boost::static_visitor<void> {
  std::ostream& os_;
  SimpleSerializer(std::ostream& os): os_(os) {}

  void operator() (const int & i) {
     os_ << i;
  }
  ...
}

Attribute attr;
boost::apply_visitor(SimpleSerializer(cout), attr);
```

## 神经网络框架检查某一属性，约束某一属性

因为某一属性的类型是`boost::variant`，可以使用visitor获得这个属性的值。之后再调用每一个约束函数即可。约束函数的定义为:

```cpp
using Attribute = boost::variant<boost::blank, float, int>;
template <typename T>
using ConstraintFN = std::function<void(T* attr, bool alreadySet)>;
```
这个函数有两个参数，一个是属性值`attr`，另一个是这个值是否被用户设置过`alreadySet`。当约束不满足的时候，直接在约束函数中`throw exception`即可。而对于一个属性的约束组，定义为:

```cpp
class BaseConstraints {
public:
  virtual void apply(Attribute* attr) const = 0;
};

template <typename T>
class Constraints final: public BaseConstraints {
public:
  std::vector<ConstraintFN<T>> constraints_;

  template <typename FN>
  Constraints<T>& addConstraint(FN f) {
    constraints_.push_back(f);
    return *this;
  }

  Constraints<T>& defaultValue(const T& val) {
    return addConstraint([=](T* attr, bool alreadySet) {
      if (!alreadySet) {
        *attr = val;
      }
    });
  }

  Constraints<T>& largerThan(const T& val) {
    return addConstraint([=](T* attr, bool) {
      if (*attr <= val) {
        throw std::runtime_error("Attribute must larger than val");
      }
    });
  }

  void apply(Attribute* attr) const {
    bool alreadySet = true;
    T* ptr = nullptr;
    if (attr->which() == 0) {  // not set.
      *attr = T();
      alreadySet = false;
    }
    ptr = boost::get<T>(attr);
    for (auto& fn : constraints_) {
      fn(ptr, alreadySet);
    }
  }
};
```

约束函数组`Constaints<T>`有共同的基类`BaseContaints`，这样方便使用基类的指针表示各个类型的子类。而`apply`函数表示使用`Attribute* attr`检查各个约束是否满足，如果不满足则会报错，满足则会将约束修改的结果放回`attr`中。

例如:

```cpp
Attribute attr;
Constraints<int> constraints;
constraints.defaultValue(10).largerThan(0);
constraints.apply(&attr);
LOG(INFO) << boost::get<int>(attr);
```

期待返回结果是`10`。因为属性`attr`并没有设计过值，而在约束中设置了默认值是10。所以返回默认值。

而

```cpp
Attribute attr = -1.0f;
Constraints<float> constraints;
constraints.defaultValue(1.0).largerThan(0);
constraints.apply(&attr);
LOG(INFO) << boost::get<int>(attr);
```
应该抛出异常报错。

而对每一个Op的每一个Attribute，我们使用Constraints设置其约束函数，即可以在运行时检查用户配置参数值的合法性、参数值的类型和设置默认值了。

**Comment by gongweibao** [comment]
Close since it's not activated.
