### ISSUE TITLE
使用protobuf的message还是使用C++结构体描述神经网络?

### ISSUE THREAD

**Issue by reyoung** [PaddlePaddle/Paddle#2500]
在Caffe2，Tensorflow，MXNet与DyNet这四个神经网络框架中，Caffe2与Tensorflow使用`protobuf`描述用户的配置信息，`MXNet`与`DyNet`使用C++数据结构描述用户的配置信息。

# Protobuf与C++描述用户配置的优缺点

## 使用Protobuf描述用户配置的优缺点

* 优点:
  * 天然支持多编程语言的序列化。
* 缺点:
  * Python与C++ 核心的网络配置需要经历一次序列化与反序列化过程，运行时速度较慢。
  * 不支持 `Variant`类型，对于Attribute的表示方式比较复杂。 See #2499

## 使用C++描述用户配置的优缺点

* 优点:
  * 因为没有序列化过程，运行速度快。
  * 有Variant类型(boost::variant或者boost::any)
* 缺点:
  * 需要手写序列化过程。

# 用户配置信息描述的要求

## 快速的、轻量级的用户配置

参考[DyNet的论文](https://arxiv.org/pdf/1701.03980.pdf)中的描述。如果实现动态神经网络，需要用户配置信息是轻量的，快速的。参考该论文23-24页与tensorflow的对比可见，DyNet实现RNN language model的速度明显快于Tensorflow(`2440 vs 636`)，且`DyNet`实现用户配置，仅从代码量上看也远小于`Tensorflow`。

即，使用C++描述神经网络配置，实现简单，速度快。

## 模型序列化与保存

* DyNet不支持拓扑结构的序列化，在预测时要求用户在C++端重新配置一下网络。
* MXNet在C++端手写了将用户配置的C++结构序列化到JSON的过程。

即，使用C++描述神经完了过配置，序列化复杂。

**Comment by reyoung** [comment]
这是issue #2483讨论issue讨论问题的一部分，我们使让用户配置protobuf，然后序列化给Paddle，还是让用户直接配置Paddle的某一个C++结构，例如`Net`，然后直接交由执行器`SimpleExecutor`执行。

**Comment by reyoung** [comment]
如背景介绍所示，使用C++描述用户配置的特点是速度快(省掉了序列化与反序列化)，而使用`protobuf`描述用户配置的特点是序列化方便。

所以有一个简单的想法，可以即让用户操作模型配置速度变快，也可以简单的序列化。那就是用户直接操作C++端的Protobuf对象。实现方式如下:

```protobuf
syntax="proto3"  // for oneof and map
message Attribute {
   oneof value {
     float f;
     string s;
     int i;
   }
}

message Op {
  repeated string inputs = 1;
  repeated string outputs = 2;
  required string type = 3;
  map<string, Attribute> attrs = 4;
}

message Net {
  repeated Op ops = 1;
}
```

而使用C++端的对象，对Protobuf对象进行操作。

```cpp
namespace proto {  // generated protobuf classes
  class Net;
  class Op;
  class Attribute;
}  // namespace proto

namespace net {
class Net {
public:
  void addOp(string type, vec<string> inputs, vec<string> outputs, AttributeMap attrs);
  ...

  void serialize(std::ostream& os) {
     net_.Serialize(os);
  }

  void deserialize(std::istream& is) {
    net_.Deserialize(is);
  }

private:
  proto::Net net_;
};

}

```

**Comment by QiJune** [comment]
做一下记录，[caffe2](https://caffe2.ai/docs/mobile-integration.html)在mobile端也依赖于protobuf，它使用的是一个lite版本

It’s pure C++, with the only non-optional dependencies being:

- Google Protobuf (the lite version, ~300kb)

- Eigen, a BLAS (on Android) is required for certain primitives, and a vectorized vector/matrix manipulation library, and Eigen is the fastest benchmarked on ARM.

**Comment by jacquesqiao** [comment]
目前的设计中，为了支持分布式，已经确定使用protobuf ProgramDesc来描述神经网络了，但是会有一封装来帮助加速。
