### ISSUE TITLE
序列预测，shape不对

### ISSUE THREAD

**Issue by OliveLv** [PaddlePaddle/Paddle#25001]
序列数据，输入shape=[10,36] lod_level=1，预测batch_size=512时，提示

ValueError: The feeded Variable u'x' should have dimensions = 2, shape = (10L, 36L), but received feeded shape [5120L, 36L]

只有batch_size=1才能进行预测，是需要reshape么？网络结构输入是序列数据，未进行embedding，直接cnn。

**Comment by hutuxian** [comment]
根据描述，请尝试把输入的shape指定为[-1, 10, 36]，真实的数据做成shape为[512, 10, 36]的样子。

**Comment by OliveLv** [comment]
cnn用fluid.nets.sequence_conv_pool，如果reshape成[-1,10,36]会报错

**Comment by OliveLv** [comment]
> 根据描述，请尝试把输入的shape指定为[-1, 10, 36]，真实的数据做成shape为[512, 10, 36]的样子。

cnn用的是fluid.nets.sequence_conv_pool，如果reshape成[-1，10，36]会报错
而且train的时候也设置了batch_size，训练时没问题，预测时却有问题
