### ISSUE TITLE
cos_sim 

### ISSUE THREAD

**Issue by zhangyong15** [PaddlePaddle/Paddle#2501]
网络结构
![2017-06-19 11 44 11](https://user-images.githubusercontent.com/22140712/27273960-e85b2f00-5503-11e7-9c8e-1a8a5610c28c.png)
MPI任务，成功运行两个pass，之后报错，报错信息：
![374e29b31e9697f5a146a28ad](https://user-images.githubusercontent.com/22140712/27274424-d419606e-5505-11e7-9e15-ae688dd26368.png)

**Comment by lcy-seso** [comment]
- 应该是 Relu 饱和，输出了全零向量。计算cosine时，为了避免出现除0错误，会检查输入向量是否是全零。

- ps. 希望能够尽量复制粘贴文字错误内容，而不是截图。这样可以被搜索到。

**Comment by zhangyong15** [comment]
那这个如何处理呢？

**Comment by lcy-seso** [comment]
可以试着改为 Tanh 激活。Relu 和 cosine 不是特别好的组合。Relu 只输出正值，而cosine 在 [-1, +1] 之间取值，相当于值域已经被压缩了一半，不会再出现负值。

**Comment by zhangyong15** [comment]
赞曹博
