### ISSUE TITLE
关于深度学习模型的预测值

### ISSUE THREAD

**Issue by ClassmateXiaoyu** [PaddlePaddle/Paddle#25027]
- 版本、环境信息：
    1）PaddlePaddle版本：1.8.1
    2）系统环境：Windows 64位，Python版本3.7
- 模型信息
    1）自训练模型 2）使用自定义数据集 3）RNN
- 问题描述：你好我想请教一个问题，我用自定义的数据集，通过DNN神经网诺训练了一个模型，模型默认返回的是每个label的概率值。那么，神经网诺能否返回一个最优解。比如，根据当前feed的实时值，模型预测出一个概率最高的最优值。

**Comment by ceci3** [comment]
你好，我理解的是您已经训练出来了一个输出每个label的概率值的网络，那在网络后面加一个argmax之类的操作取出来概率最高的类别，不就是预测出概率最高的值了吗？

**Comment by ClassmateXiaoyu** [comment]
> 你好，我理解的是您已经训练出来了一个输出每个label的概率值的网络，那在网络后面加一个argmax之类的操作取出来概率最高的类别，不就是预测出概率最高的值了吗？

你好，argmax这个我有在脚本中写入，其返回值是fetch_map的最大概率的索引。我打个比方，比如训练数据是某地的空气质量（里面有很多不同的参数），经过深度学习后，模型能否根据当前feed的实时数据（比如此时此刻的一组空气质量数据），返回一组最优的空气质量参数值。

**Comment by ceci3** [comment]
您好 我还是不太明白.. 您是想输入一组代表空气质量的数据，输出一个类似给这组空气质量得分的一个意思吗？

**Comment by ClassmateXiaoyu** [comment]
> 您好 我还是不太明白.. 您是想输入一组代表空气质量的数据，输出一个类似给这组空气质量得分的一个意思吗？

有点区别。想通过输入一组代表空气质量的数据，输出也是一组空气质量数据（这个输出的数据要为概率最高的一组数据），这个能实现吗，如果能，需要通过哪种神经网络结构去做（目前用的神经网诺结构返回的是最大概率标签）。

**Comment by ceci3** [comment]
拿到的最大概率和输入空气质量指数之间应该有个映射关系的，直接根据映射取出来不可以吗？

**Comment by ClassmateXiaoyu** [comment]
> 拿到的最大概率和输入空气质量指数之间应该有个映射关系的，直接根据映射取出来不可以吗？

你好，您建议的这个操作怎么实现，是有现成的接口还是需要单独写脚本？

**Comment by ceci3** [comment]
需要自己写一下，感觉python的dict就可以做到了..

**Comment by ClassmateXiaoyu** [comment]
> 需要自己写一下，感觉python的dict就可以做到了..

你好，有没有相关的参考文档。

**Comment by ceci3** [comment]
你好，没有参考文档，如果使用python dict的话，可以搜下python的dict使用，根据需要构建您需要的字典~

**Comment by ClassmateXiaoyu** [comment]
> 你好，没有参考文档，如果使用python dict的话，可以搜下python的dict使用，根据需要构建您需要的字典~

你好，python的dict我知道，但是就这个具体的问题而言应该怎么操作，这个是我关注的。没有文档的话，有没有类似的案例可供参考呢，单靠个人去摸索这效率太低了呀！

**Comment by ceci3** [comment]
大概类似这样：
```python
a=dict()
output = model(input)
a[input] = output
max_input = max(a, key=a.get)
```

**Comment by ClassmateXiaoyu** [comment]
> 大概类似这样：
> 
> ```python
> a=dict()
> output = model(input)
> a[input] = output
> max_input = max(a, key=a.get)
> ```

好的，谢谢，我试一下。
