### ISSUE TITLE
两模型串联训练问题

### ISSUE THREAD

**Issue by wkzza1830** [PaddlePaddle/Paddle#25028]
我的模型由三部分组成，g_program和loss_program为文件中新定义部分，inference_program为之前已训练好的模型。
![program定义](https://user-images.githubusercontent.com/59675268/84456155-ddd23e00-ac91-11ea-8071-5715fa6081e6.png)
现希望将g_program输出与inference_program输入进行串联，利用loss_program计算损失。
<img width="473" alt="训练过程" src="https://user-images.githubusercontent.com/59675268/84456510-b465e200-ac92-11ea-895d-7eb61c1e60c9.png">
但inference_program的输出（logit_2）输出维度与其返回列表（fetch_targets）对应不上：
logit_2[0].shape = (batch_size, 1)
fetch_targets[0].shape = (batch_size, 128)
然而，当文件只包含inference_program一个模型时，输出维度则正常。
这是否与不同模型中变量名重复有关？应当如何修改？

**Comment by ceci3** [comment]
可以打印inference_program看下，实际输出的fetch_targets是不是你想要输出的那个变量。不同模型中变量名重复应该没什么关系，是哪里有重复？

**Comment by wkzza1830** [comment]
重新检查后发现还是g_program与inference_program中的变量名冲突问题，为inference_program新建一个scope后问题得到解决。
