### ISSUE TITLE
win10+Python 3.7.6下无法安装，报错“ERROR: Could not find a version that satisfies the requirement paddlepaddle (from versions: none)”

### ISSUE THREAD

**Issue by Zeeman206** [PaddlePaddle/Paddle#25029]
win10+Python 3.7.6下无法安装，搜了github和百度AI社区，类似问题大多是因为早期Paddle不支持Python 3.7+导致。

- 版本、环境信息：
    1）PaddlePaddle版本：未安装成功，无版本号。
    2）CPU：i7-8565U，MKL已安装（版本mkl_2020.1.216）
    3）GPU：无
    4）系统环境：win10+Python 3.7.6+pip 20.0.2
- 安装方式信息：
1）pip安装
       
  特殊环境请注明：如离线安装等
- 复现信息：
执行python -m pip install paddlepaddle -i https://mirror.baidu.com/pypi/simple命令后出现报错：
ERROR: Could not find a version that satisfies the requirement paddlepaddle (from versions: none)
ERROR: No matching distribution found for paddlepaddle

**Comment by zhwesky2010** [comment]
@Zeeman206 你好，请试一下清华源pip install，百度源可能没有同步

**Comment by Zeeman206** [comment]
@zhouwei25 多谢你及时回复，清华的源也试过，一样的提示。

**Comment by zhwesky2010** [comment]
@Zeeman206 您好，
![image](https://user-images.githubusercontent.com/52485244/84475621-759a5100-acbf-11ea-8122-5ee7418284fa.png)，我这边是可以正常下载的，麻烦你用where python，python --version看一下是不是位置和版本号

**Comment by Zeeman206** [comment]
执行结果如下：
C:\Users>where python
C:\Users\Zeeman\Anaconda3\python.exe
C:\Users\Zeeman\AppData\Local\Microsoft\WindowsApps\python.exe

C:\Users>python --version
Python 3.7.6

**Comment by zhwesky2010** [comment]
@Zeeman206 你好，你这个是使用Anaconda安装的python，请进入Anaconda的cmd，创建虚环境后，使用 conda install paddlepaddle 安装。安装文档是这个https://www.paddlepaddle.org.cn/documentation/docs/zh/install/install_Conda.html
