### ISSUE TITLE
paddledetection fp16 训练问题

### ISSUE THREAD

**Issue by carol510** [PaddlePaddle/Paddle#25032]
model : faster_r50_fpn
训练：
![image](https://user-images.githubusercontent.com/22268236/84474918-40d9ca00-acbe-11ea-8f7f-0dc2af48d7ba.png)
报错：
![image](https://user-images.githubusercontent.com/22268236/84474488-8053e680-acbd-11ea-97eb-be845a694f87.png)

**Comment by willthefrog** [comment]
应该是PaddleDetection的版本太老，和paddle版本不兼容，可以升级下看看。
