### ISSUE TITLE
visualization of model dumped by function merge_v2_model

### ISSUE THREAD

**Issue by Red-Lv** [PaddlePaddle/Paddle#25031]
visualization of model dumped by function merge_v2_model

-PaddlePaddle version: non fluid version, v2 version
-CPU: including CPUMKL/OpenBlas/MKLDNN version
-GPU: including CUDA/CUDNN version
-OS Platform (eg.Mac OS 10.14)
-Python version
-Name of Models&Dataset/details of operator
Note: You can get most of the information by running [summary_env.py](https://github.com/PaddlePaddle/Paddle/blob/develop/tools/summary_env.py). 
**To Reproduce**
Steps to reproduce the behavior
**Describe your current behavior**
**Code to reproduce the issue**
**Other info / logs**

**Comment by ceci3** [comment]
您好，建议升级到fluid，v2版本太早了，已经不维护了..
