### ISSUE TITLE
如何导入预训练模型参数

### ISSUE THREAD

**Issue by lao-xu** [PaddlePaddle/Paddle#25047]
请问动态图下如何加载预训练模型参数？
load_var，load_persistables这些都是静态图的

**Comment by liupluswei** [comment]
请参考这两个api：
https://www.paddlepaddle.org.cn/documentation/docs/zh/api_cn/dygraph_cn/load_dygraph_cn.html
https://www.paddlepaddle.org.cn/documentation/docs/zh/api_cn/dygraph_cn/save_dygraph_cn.html
