### ISSUE TITLE
Jetson nano 编译Paddle Inference报错

### ISSUE THREAD

**Issue by hang245141253** [PaddlePaddle/Paddle#25042]
1）PaddlePaddle版本：1.7.1、 1.8.1、Paddle-2.0.0-alpha0
    2）CPU：Cortex-A57
    3）GPU：CUDA=10.0、CUDNN=7.6.3
    4）系统环境：Ubuntu18.04、Python版本3.6.9、gcc版本7.5.0、g++版本7.5.0

本地编译：cmake ..           \
-DWITH_CONTRIB=OFF          \
 -DWITH_MKL=OFF           \
 -DWITH_MKLDNN=OFF           \
-DWITH_TESTING=OFF          \
 -DCMAKE_BUILD_TYPE=Release         \
  -DON_INFER=ON          \
 -DWITH_PYTHON=ON            \
  -DWITH_XBYAK=OFF            \
    -DWITH_NV_JETSON=ON             \
  -DPY_VERSION=3.6

说明：尝试了1.7.1、 1.8.1、Paddle-2.0.0-alpha0的zip包进行源码编译，都出现了这个问题，不知道是不是因为gcc版本太高的缘故

   报错日志：In file included from /home/jetbot/Paddle-2.0.0-alpha0/paddle/fluid/inference/tensorrt/engine.h:32:0,
                 from /home/jetbot/Paddle-2.0.0-alpha0/paddle/fluid/inference/tensorrt/op_teller.h:21,
                 from /home/jetbot/Paddle-2.0.0-alpha0/paddle/fluid/inference/tensorrt/op_teller.cc:15:
/home/jetbot/Paddle-2.0.0-alpha0/paddle/fluid/inference/tensorrt/plugin/trt_plugin_factory.h:35:7: error: base class ‘class nvinfer1::IPluginFactory’ has accessible non-virtual destructor [-Werror=non-virtual-dtor]
 class PluginFactoryTensorRT : public nvinfer1::IPluginFactory,
       ^~~~~~~~~~~~~~~~~~~~~
In file included from /usr/include/c++/7/memory:80:0,
                 from /home/jetbot/Paddle-2.0.0-alpha0/paddle/fluid/inference/tensorrt/op_teller.h:16,
                 from /home/jetbot/Paddle-2.0.0-alpha0/paddle/fluid/inference/tensorrt/op_teller.cc:15:
/usr/include/c++/7/bits/unique_ptr.h: In instantiation of ‘void std::default_delete<_Tp>::operator()(_Tp*) const [with _Tp = nvinfer1::IOptimizationProfile]’:
/usr/include/c++/7/bits/unique_ptr.h:263:17:   required from ‘std::unique_ptr<_Tp, _Dp>::~unique_ptr() [with _Tp = nvinfer1::IOptimizationProfile; _Dp = std::default_delete<nvinfer1::IOptimizationProfile>]’
/home/jetbot/Paddle-2.0.0-alpha0/paddle/fluid/inference/tensorrt/engine.h:138:23:   required from here
/usr/include/c++/7/bits/unique_ptr.h:78:2: error: ‘nvinfer1::IOptimizationProfile::~IOptimizationProfile()’ is protected within this context
  delete __ptr;
  ^~~~~~
In file included from /usr/include/aarch64-linux-gnu/NvInfer.h:53:0,
                 from /home/jetbot/Paddle-2.0.0-alpha0/paddle/fluid/inference/tensorrt/engine.h:17,
                 from /home/jetbot/Paddle-2.0.0-alpha0/paddle/fluid/inference/tensorrt/op_teller.h:21,
                 from /home/jetbot/Paddle-2.0.0-alpha0/paddle/fluid/inference/tensorrt/op_teller.cc:15:
/usr/include/aarch64-linux-gnu/NvInferRuntime.h:1098:5: note: declared protected here
     ~IOptimizationProfile() noexcept = default;
     ^
cc1plus: all warnings being treated as errors
paddle/fluid/inference/tensorrt/CMakeFiles/tensorrt_op_teller.dir/build.make:62: recipe for target 'paddle/fluid/inference/tensorrt/CMakeFiles/tensorrt_op_teller.dir/op_teller.cc.o' failed
make[2]: *** [paddle/fluid/inference/tensorrt/CMakeFiles/tensorrt_op_teller.dir/op_teller.cc.o] Error 1
CMakeFiles/Makefile2:85655: recipe for target 'paddle/fluid/inference/tensorrt/CMakeFiles/tensorrt_op_teller.dir/all' failed
make[1]: *** [paddle/fluid/inference/tensorrt/CMakeFiles/tensorrt_op_teller.dir/all] Error 2
make[1]: *** 正在等待未完成的任务....

**Comment by FDInSky** [comment]
你的CMake版本是多少，要求使用3.10以上 @hang245141253

**Comment by hang245141253** [comment]
> 你的CMake版本是多少，要求使用3.10以上@ hang245141253

是3.10.2 已经自行解决了 谢谢！

**Comment by FDInSky** [comment]
> > 你的CMake版本是多少，要求使用3.10以上@ hang245141253
> 
> 是3.10.2 已经自行解决了 谢谢！

你好，请问你是怎么解决的？

**Comment by hang245141253** [comment]
> > > 你的CMake版本是多少，要求使用3.10以上@ hang245141253
> > 
> > 
> > 是3.10.2已经自行解决了谢谢！
> 
> 你好，请问你是怎么解决的？

在NvInfer.h里添加了给IPluginFactory 类添加虚析构函数就好了

后面还有个报错 啥名称不记得了 把报错的私有改成公有就不报错了
