### ISSUE TITLE
训练时报错，没有任何提示信息

### ISSUE THREAD

**Issue by liucc09** [PaddlePaddle/Paddle#25041]
1）PaddlePaddle版本：1.7.2
2）GPU：aistudio上的GPU

在训练时莫名其妙报如下错误，aistudio notebook地址：https://aistudio.baidu.com/aistudio/projectdetail/540958  版本1

terminate called after throwing an instance of 'pybind11::error_already_set'
  what():  TypeError: __repr__ returned non-string (type NoneType)
W0612 23:55:16.203984   128 init.cc:209] Warning: PaddlePaddle catches a failure signal, it may not work properly
W0612 23:55:16.204010   128 init.cc:211] You could check whether you killed PaddlePaddle thread/process accidentally or report the case to PaddlePaddle
W0612 23:55:16.204015   128 init.cc:214] The detail failure signal is:

W0612 23:55:16.204020   128 init.cc:217] *** Aborted at 1591977316 (unix time) try "date -d @1591977316" if you are using GNU date ***
W0612 23:55:16.205726   128 init.cc:217] PC: @                0x0 (unknown)
W0612 23:55:16.205821   128 init.cc:217] *** SIGABRT (@0x3e800000080) received by PID 128 (TID 0x7fb8652df700) from PID 128; stack trace: ***
W0612 23:55:16.207077   128 init.cc:217]     @     0x7fb864ec6390 (unknown)
W0612 23:55:16.208257   128 init.cc:217]     @     0x7fb864b20428 gsignal
W0612 23:55:16.209399   128 init.cc:217]     @     0x7fb864b2202a abort
W0612 23:55:16.210263   128 init.cc:217]     @     0x7fb824a6b84a __gnu_cxx::__verbose_terminate_handler()
W0612 23:55:16.210999   128 init.cc:217]     @     0x7fb824a69f47 __cxxabiv1::__terminate()
W0612 23:55:16.211802   128 init.cc:217]     @     0x7fb824a69f7d std::terminate()
W0612 23:55:17.045090   128 init.cc:217]     @     0x7fb824a6a15a __cxa_throw
W0612 23:55:17.046548   128 init.cc:217]     @     0x7fb7fcb92808 pybind11::cpp_function::dispatcher()
W0612 23:55:17.046945   128 init.cc:217]     @     0x56201607b744 _PyMethodDef_RawFastCallKeywords
W0612 23:55:17.047227   128 init.cc:217]     @     0x56201607b861 _PyCFunction_FastCallKeywords
W0612 23:55:17.047458   128 init.cc:217]     @     0x5620160e72bd _PyEval_EvalFrameDefault
W0612 23:55:17.047665   128 init.cc:217]     @     0x56201602c56b _PyFunction_FastCallDict
W0612 23:55:17.047874   128 init.cc:217]     @     0x56201604ae53 _PyObject_Call_Prepend
W0612 23:55:17.048099   128 init.cc:217]     @     0x56201603ddbe PyObject_Call
W0612 23:55:17.048318   128 init.cc:217]     @     0x5620160e4232 _PyEval_EvalFrameDefault
W0612 23:55:17.048524   128 init.cc:217]     @     0x56201602b539 _PyEval_EvalCodeWithName
W0612 23:55:17.048727   128 init.cc:217]     @     0x56201602c635 _PyFunction_FastCallDict
W0612 23:55:17.048934   128 init.cc:217]     @     0x56201604ae53 _PyObject_Call_Prepend
W0612 23:55:17.049046   128 init.cc:217]     @     0x562016082a3a slot_tp_call
W0612 23:55:17.049247   128 init.cc:217]     @     0x5620160838fb _PyObject_FastCallKeywords
W0612 23:55:17.049466   128 init.cc:217]     @     0x5620160e76e8 _PyEval_EvalFrameDefault
W0612 23:55:17.049669   128 init.cc:217]     @     0x56201602c56b _PyFunction_FastCallDict
W0612 23:55:17.049873   128 init.cc:217]     @     0x56201604ae53 _PyObject_Call_Prepend
W0612 23:55:17.050096   128 init.cc:217]     @     0x56201603ddbe PyObject_Call
W0612 23:55:17.050314   128 init.cc:217]     @     0x5620160e4232 _PyEval_EvalFrameDefault
W0612 23:55:17.050516   128 init.cc:217]     @     0x56201602b539 _PyEval_EvalCodeWithName
W0612 23:55:17.050719   128 init.cc:217]     @     0x56201602c635 _PyFunction_FastCallDict
W0612 23:55:17.050923   128 init.cc:217]     @     0x56201604ae53 _PyObject_Call_Prepend
W0612 23:55:17.051034   128 init.cc:217]     @     0x562016082a3a slot_tp_call
W0612 23:55:17.051247   128 init.cc:217]     @     0x5620160838fb _PyObject_FastCallKeywords
W0612 23:55:17.051466   128 init.cc:217]     @     0x5620160e6e86 _PyEval_EvalFrameDefault
W0612 23:55:17.051671   128 init.cc:217]     @     0x56201602c56b _PyFunction_FastCallDict
Aborted (core dumped)

**Comment by ceci3** [comment]
你好，我看版本二是没有问题的，相对版本一是改了什么？

**Comment by liucc09** [comment]
> 
> 
> 你好，我看版本二是没有问题的，相对版本一是改了什么？

我发现把网络的实例化放到with fluid.dygraph.guard()里面就不会报错了。

**Comment by liucc09** [comment]
把网络模型的实例化放到with fluid.dygraph.guard()里面就不再报错了
 
发件人： ceci3
发送时间： 2020-06-16 16:54
收件人： PaddlePaddle/Paddle
抄送： liucc09; Author
主题： Re: [PaddlePaddle/Paddle] 训练时报错，没有任何提示信息 (#25041)
你好，我看版本二是没有问题的，是解决了吗？

**Comment by ceci3** [comment]
好的，我们优化下相关的报错信息~ 感谢反馈~
