### ISSUE TITLE
Reshape 接口在动态图模式下shape参数不允许传入Variable

### ISSUE THREAD

**Issue by zhangyimi** [PaddlePaddle/Paddle#25049]
paddle1.8.1动态图：
batch_size如下图所示：
![image](https://user-images.githubusercontent.com/20926735/84596985-63710c00-ae93-11ea-9669-338875f7163a.png)

当做shape的一个值时，zeros可以，但是reshape却会报错。
![image](https://user-images.githubusercontent.com/20926735/84596964-49372e00-ae93-11ea-8fb7-3c9d335aa2d5.png)

错误如下：
```shell
The type of 'shape' in reshape must be list[int] or tuple(int) in Dygraph mode, but received <class 'tuple'>, which contains Variable.
```

**Comment by mapingshuo** [comment]
这个限制 “The type of 'shape' in reshape must be list[int] or tuple(int) in Dygraph mode” 是在下面PR中添加的，https://github.com/PaddlePaddle/Paddle/pull/21724

请 @zhiqiu 帮忙解答一下。

**Comment by zhiqiu** [comment]
动态图下，如果batch_size是一个tensor，可以传入`batch_size.numpy()`。

**Comment by liupluswei** [comment]
> 动态图下，如果batch_size是一个tensor，可以传入`batch_size.numpy()`。

用户可能是想书写的时候更简单一点，不需要写.numpy()的部分，我们是否能在API内部做统一处理？

**Comment by zhiqiu** [comment]
> > 动态图下，如果batch_size是一个tensor，可以传入`batch_size.numpy()`。
> 
> 用户可能是想书写的时候更简单一点，不需要写.numpy()的部分，我们是否能在API内部做统一处理？

嗯嗯明白，主要是支持这种写法会一定程度影响性能，后面我们再评估下是否支持。
