### ISSUE TITLE
方法咨询

### ISSUE THREAD

**Issue by liangruofei** [PaddlePaddle/Paddle#25048]
我这边有个项目是要对空中飞行的无人机进行检测任务，我想咨询一下咱们这边，用咱们的啥方法作为基础比较好，同时有什么策略的建议
难点：1、目标多数为小目标
2、服务器端运行，速度肯定得稍微接近实时
3、场景包括空中目标和建筑群中的

**Comment by qingqing01** [comment]
考虑到速度和精度的要求，推荐使用PaddleDetection提供的YOLOv3增强版： https://github.com/PaddlePaddle/PaddleDetection/blob/release/0.3/docs/featured_model/YOLOv3_ENHANCEMENT.md

**Comment by liangruofei** [comment]
收到，感谢


在2020年6月15日 14:03，qingqing01<notifications@github.com> 写道：

考虑到速度和精度的要求，推荐使用PaddleDetection提供的YOLOv3增强版： https://github.com/PaddlePaddle/PaddleDetection/blob/release/0.3/docs/featured_model/YOLOv3_ENHANCEMENT.md
