### ISSUE TITLE
Operator "c_allgather" has not been registered

### ISSUE THREAD

**Issue by gobigrassland** [PaddlePaddle/Paddle#25057]
使用PLSC调用从源码编译的paddlepaddle，出现了如下问题：
Operator "c_allgather" has not been registered. 不知该如何解决。
直接使用pip安装的paddlepaddle可以正常运行。之所以自己源码编译paddlepaddle是想深入了解代码，方便日后根据需求做一些定制化开发。

具体错误信息如下：

> File "train_multi_input.py", line 66, in
> train_multi_input()
> File "train_multi_input.py", line 62, in train_multi_input
> ins.train()
> File "PLSC_multi_modelParal_acm/plsc/entry.py", line 948, in train
> dist_strategy=strategy,
> File "PLSC_multi_modelParal_acm/plsc/entry.py", line 448, in build_program
> batch_multi_list=self.train_batch_size_multi
> File "PLSC_multi_modelParal_acm/plsc/models/base_model.py", line 169, in get_output
> batch_multi_list=batch_multi_list)
> File "PLSC_multi_modelParal_acm/plsc/models/dist_algo.py", line 1244, in distributed_arcface_classify
> param_attr=param_attr)
> File "PLSC_multi_modelParal_acm/plsc/models/dist_algo.py", line 977, in arcface_classify
> norm_x, nranks=self.nranks, use_calc_stream=True)
> File "python2.7/dist-packages/paddle/fluid/layers/collective.py", line 128, in _c_allgather
> 'use_calc_stream': use_calc_stream
> File "python2.7/dist-packages/paddle/fluid/layer_helper.py", line 43, in append_op
> return self.main_program.current_block().append_op(*args, **kwargs)
> File "python2.7/dist-packages/paddle/fluid/framework.py", line 2610, in append_op
> attrs=kwargs.get("attrs", None))
> File "python2.7/dist-packages/paddle/fluid/framework.py", line 1870, in init
> proto = OpProtoHolder.instance().get_op_proto(type)
> File "python2.7/dist-packages/paddle/fluid/framework.py", line 1751, in get_op_proto
> raise ValueError("Operator "%s" has not been registered." % type)
> ValueError: Operator "c_allgather" has not been registered

**Comment by gavin1332** [comment]
请确认cmake时是否打开`-DWITH_DISTRIBUTE=ON`开关

**Comment by gobigrassland** [comment]
@gavin1332 谢谢，已经解决
