### ISSUE TITLE
TypeError: The type of 'num_or_sections' in split must be int or list in Dygraph mode, but received <class 'paddle.fluid.core_avx.VarBase'>.

### ISSUE THREAD

**Issue by zhangyimi** [PaddlePaddle/Paddle#25050]
paddle.1.8.1动态图：
感觉这里设计的好不合理呀，num_or_sections必须是int或者list才行，不能是VarBase，从GPU拷贝到CPU也要花时间吧。
![image](https://user-images.githubusercontent.com/20926735/84597225-2443ba80-ae95-11ea-81d8-0ad22b073721.png)

**Comment by liupluswei** [comment]
这个问题与#25049 类似，是一个动态图接口统一设计的问题，集中再#25049 下面讨论吧
