### ISSUE TITLE
not_equal广播时返回类型错误

### ISSUE THREAD

**Issue by zhangyimi** [PaddlePaddle/Paddle#25053]
paddle 1.8.2 动态图，问题如下图所示：
预期返回bool类型，但是返回int64，当a和b的shape一致时返回bool
![image](https://user-images.githubusercontent.com/20926735/84614140-c85e4d80-aef7-11ea-9ef5-7ad8069cbccf.png)

**Comment by zhiqiu** [comment]
Hi，该错误可复现，已提PR修复。
