### ISSUE TITLE
fp 16训练保存

### ISSUE THREAD

**Issue by carol510** [PaddlePaddle/Paddle#25061]
paddle2.0
detection 0.3
hrnet18-diouloss 有问题 
[bug.docx](https://github.com/PaddlePaddle/Paddle/files/4779482/bug.docx)

**Comment by willthefrog** [comment]
这和保存没关系吧，应该是跑不了的，这个backbone里有些op还不支持fp16（resize_nearest)，建议不要使用fp16训练。
