### ISSUE TITLE
demo 跑不通

### ISSUE THREAD

**Issue by yaoxuefeng6** [PaddlePaddle/Paddle#25074]
这个网页的demo：https://www.paddlepaddle.org.cn/documentation/docs/zh/2.0-alpha/beginners_guide/index_cn.html
paddle版本 2.0-alpha

import numpy
import paddle
# 定义输入数据占位符
a = paddle.nn.data(name="a", shape=[1], dtype='int64')
b = paddle.nn.data(name="b", shape=[1], dtype='int64')
# 组建网络（此处网络仅由一个操作构成，即elementwise_add）
result = paddle.elementwise_add(a, b)
# 准备运行网络
cpu = paddle.CPUPlace() # 定义运算设备，这里选择在CPU下训练
exe = paddle.Executor(cpu) # 创建执行器
# 创建输入数据
x = numpy.array([2])
y = numpy.array([3])
# 运行网络
outs = exe.run(
    feed={'a':x, 'b':y}, # 将输入数据x, y分别赋值给变量a，b
    fetch_list=[result]  # 通过fetch_list参数指定需要获取的变量结果
    )
#输出运行结果
print (outs)
#[array([5], dtype=int64)]

报错信息：
---------------------------------------------------------------------------
EnforceNotMet                             Traceback (most recent call last)
<ipython-input-40-1104baedf3fd> in <module>
      5 b = paddle.nn.data(name="b", shape=[1], dtype='int64')
      6 # 组建网络（此处网络仅由一个操作构成，即elementwise_add）
----> 7 result = paddle.elementwise_add(a, b)
      8 # 准备运行网络
      9 cpu = paddle.CPUPlace() # 定义运算设备，这里选择在CPU下训练

/anaconda3/lib/python3.7/site-packages/paddle/fluid/layers/nn.py in elementwise_add(x, y, axis, act, name)
  11369     if in_dygraph_mode():
  11370         return _elementwise_op_in_dygraph(
> 11371             x, y, axis=axis, act=act, op_name='elementwise_add')
  11372 
  11373     return _elementwise_op(LayerHelper('elementwise_add', **locals()))

<decorator-gen-149> in _elementwise_op_in_dygraph(x, y, axis, act, use_mkldnn, op_name)

/anaconda3/lib/python3.7/site-packages/paddle/fluid/wrapped_decorator.py in __impl__(func, *args, **kwargs)
     23     def __impl__(func, *args, **kwargs):
     24         wrapped_func = decorator_func(func)
---> 25         return wrapped_func(*args, **kwargs)
     26 
     27     return __impl__

/anaconda3/lib/python3.7/site-packages/paddle/fluid/framework.py in __impl__(*args, **kwargs)
    218         assert in_dygraph_mode(
    219         ), "We Only support %s in imperative mode, please use fluid.dygraph.guard() as context to run it in imperative Mode" % func.__name__
--> 220         return func(*args, **kwargs)
    221 
    222     return __impl__

/anaconda3/lib/python3.7/site-packages/paddle/fluid/layers/nn.py in _elementwise_op_in_dygraph(x, y, axis, act, use_mkldnn, op_name)
    200                                op_name=None):
    201     op = getattr(core.ops, op_name)
--> 202     out = op(x, y, 'axis', axis, 'use_mkldnn', use_mkldnn)
    203 
    204     return dygraph_utils._append_activation_in_dygraph(

EnforceNotMet: 

--------------------------------------------
C++ Call Stacks (More useful to developers):
--------------------------------------------
0   std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > paddle::platform::GetTraceBackString<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&>(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&&&, char const*, int)
1   paddle::framework::OperatorWithKernel::ParseInputDataType(paddle::framework::ExecutionContext const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, paddle::framework::proto::VarType_Type*) const
2   paddle::framework::OperatorWithKernel::IndicateVarDataType(paddle::framework::ExecutionContext const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) const
3   paddle::operators::ElementwiseOp::GetExpectedKernelType(paddle::framework::ExecutionContext const&) const
4   paddle::imperative::PreparedOp paddle::imperative::PrepareOpImpl<paddle::imperative::VarBase>(paddle::imperative::details::NameVarMapTrait<paddle::imperative::VarBase>::Type const&, paddle::imperative::details::NameVarMapTrait<paddle::imperative::VarBase>::Type const&, paddle::framework::OperatorWithKernel const&, paddle::platform::Place, std::__1::unordered_map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, boost::variant<boost::blank, int, float, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::vector<int, std::__1::allocator<int> >, std::__1::vector<float, std::__1::allocator<float> >, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > >, bool, std::__1::vector<bool, std::__1::allocator<bool> >, paddle::framework::BlockDesc*, long long, std::__1::vector<paddle::framework::BlockDesc*, std::__1::allocator<paddle::framework::BlockDesc*> >, std::__1::vector<long long, std::__1::allocator<long long> >, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_>, std::__1::hash<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::equal_to<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const, boost::variant<boost::blank, int, float, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::vector<int, std::__1::allocator<int> >, std::__1::vector<float, std::__1::allocator<float> >, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > >, bool, std::__1::vector<bool, std::__1::allocator<bool> >, paddle::framework::BlockDesc*, long long, std::__1::vector<paddle::framework::BlockDesc*, std::__1::allocator<paddle::framework::BlockDesc*> >, std::__1::vector<long long, std::__1::allocator<long long> >, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> > > > const&)
5   paddle::imperative::PreparedOp::Prepare(std::__1::map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::vector<std::__1::shared_ptr<paddle::imperative::VarBase>, std::__1::allocator<std::__1::shared_ptr<paddle::imperative::VarBase> > >, std::__1::less<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const, std::__1::vector<std::__1::shared_ptr<paddle::imperative::VarBase>, std::__1::allocator<std::__1::shared_ptr<paddle::imperative::VarBase> > > > > > const&, std::__1::map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::vector<std::__1::shared_ptr<paddle::imperative::VarBase>, std::__1::allocator<std::__1::shared_ptr<paddle::imperative::VarBase> > >, std::__1::less<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const, std::__1::vector<std::__1::shared_ptr<paddle::imperative::VarBase>, std::__1::allocator<std::__1::shared_ptr<paddle::imperative::VarBase> > > > > > const&, paddle::framework::OperatorWithKernel const&, paddle::platform::Place const&, std::__1::unordered_map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, boost::variant<boost::blank, int, float, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::vector<int, std::__1::allocator<int> >, std::__1::vector<float, std::__1::allocator<float> >, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > >, bool, std::__1::vector<bool, std::__1::allocator<bool> >, paddle::framework::BlockDesc*, long long, std::__1::vector<paddle::framework::BlockDesc*, std::__1::allocator<paddle::framework::BlockDesc*> >, std::__1::vector<long long, std::__1::allocator<long long> >, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_>, std::__1::hash<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::equal_to<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const, boost::variant<boost::blank, int, float, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::vector<int, std::__1::allocator<int> >, std::__1::vector<float, std::__1::allocator<float> >, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > >, bool, std::__1::vector<bool, std::__1::allocator<bool> >, paddle::framework::BlockDesc*, long long, std::__1::vector<paddle::framework::BlockDesc*, std::__1::allocator<paddle::framework::BlockDesc*> >, std::__1::vector<long long, std::__1::allocator<long long> >, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> > > > const&)
6   paddle::imperative::OpBase::Run(paddle::framework::OperatorBase const&, std::__1::map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::vector<std::__1::shared_ptr<paddle::imperative::VarBase>, std::__1::allocator<std::__1::shared_ptr<paddle::imperative::VarBase> > >, std::__1::less<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const, std::__1::vector<std::__1::shared_ptr<paddle::imperative::VarBase>, std::__1::allocator<std::__1::shared_ptr<paddle::imperative::VarBase> > > > > > const&, std::__1::map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::vector<std::__1::shared_ptr<paddle::imperative::VarBase>, std::__1::allocator<std::__1::shared_ptr<paddle::imperative::VarBase> > >, std::__1::less<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const, std::__1::vector<std::__1::shared_ptr<paddle::imperative::VarBase>, std::__1::allocator<std::__1::shared_ptr<paddle::imperative::VarBase> > > > > > const&, std::__1::unordered_map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, boost::variant<boost::blank, int, float, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::vector<int, std::__1::allocator<int> >, std::__1::vector<float, std::__1::allocator<float> >, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > >, bool, std::__1::vector<bool, std::__1::allocator<bool> >, paddle::framework::BlockDesc*, long long, std::__1::vector<paddle::framework::BlockDesc*, std::__1::allocator<paddle::framework::BlockDesc*> >, std::__1::vector<long long, std::__1::allocator<long long> >, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_>, std::__1::hash<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::equal_to<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const, boost::variant<boost::blank, int, float, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::vector<int, std::__1::allocator<int> >, std::__1::vector<float, std::__1::allocator<float> >, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > >, bool, std::__1::vector<bool, std::__1::allocator<bool> >, paddle::framework::BlockDesc*, long long, std::__1::vector<paddle::framework::BlockDesc*, std::__1::allocator<paddle::framework::BlockDesc*> >, std::__1::vector<long long, std::__1::allocator<long long> >, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> > > > const&, paddle::platform::Place const&)
7   paddle::imperative::Tracer::TraceOp(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::vector<std::__1::shared_ptr<paddle::imperative::VarBase>, std::__1::allocator<std::__1::shared_ptr<paddle::imperative::VarBase> > >, std::__1::less<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const, std::__1::vector<std::__1::shared_ptr<paddle::imperative::VarBase>, std::__1::allocator<std::__1::shared_ptr<paddle::imperative::VarBase> > > > > > const&, std::__1::map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::vector<std::__1::shared_ptr<paddle::imperative::VarBase>, std::__1::allocator<std::__1::shared_ptr<paddle::imperative::VarBase> > >, std::__1::less<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const, std::__1::vector<std::__1::shared_ptr<paddle::imperative::VarBase>, std::__1::allocator<std::__1::shared_ptr<paddle::imperative::VarBase> > > > > > const&, std::__1::unordered_map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, boost::variant<boost::blank, int, float, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::vector<int, std::__1::allocator<int> >, std::__1::vector<float, std::__1::allocator<float> >, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > >, bool, std::__1::vector<bool, std::__1::allocator<bool> >, paddle::framework::BlockDesc*, long long, std::__1::vector<paddle::framework::BlockDesc*, std::__1::allocator<paddle::framework::BlockDesc*> >, std::__1::vector<long long, std::__1::allocator<long long> >, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_>, std::__1::hash<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::equal_to<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const, boost::variant<boost::blank, int, float, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::vector<int, std::__1::allocator<int> >, std::__1::vector<float, std::__1::allocator<float> >, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > >, bool, std::__1::vector<bool, std::__1::allocator<bool> >, paddle::framework::BlockDesc*, long long, std::__1::vector<paddle::framework::BlockDesc*, std::__1::allocator<paddle::framework::BlockDesc*> >, std::__1::vector<long long, std::__1::allocator<long long> >, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> > > >, paddle::platform::Place const&, bool)
8   paddle::imperative::Tracer::TraceOp(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::vector<std::__1::shared_ptr<paddle::imperative::VarBase>, std::__1::allocator<std::__1::shared_ptr<paddle::imperative::VarBase> > >, std::__1::less<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const, std::__1::vector<std::__1::shared_ptr<paddle::imperative::VarBase>, std::__1::allocator<std::__1::shared_ptr<paddle::imperative::VarBase> > > > > > const&, std::__1::map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::vector<std::__1::shared_ptr<paddle::imperative::VarBase>, std::__1::allocator<std::__1::shared_ptr<paddle::imperative::VarBase> > >, std::__1::less<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const, std::__1::vector<std::__1::shared_ptr<paddle::imperative::VarBase>, std::__1::allocator<std::__1::shared_ptr<paddle::imperative::VarBase> > > > > > const&, std::__1::unordered_map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, boost::variant<boost::blank, int, float, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::vector<int, std::__1::allocator<int> >, std::__1::vector<float, std::__1::allocator<float> >, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > >, bool, std::__1::vector<bool, std::__1::allocator<bool> >, paddle::framework::BlockDesc*, long long, std::__1::vector<paddle::framework::BlockDesc*, std::__1::allocator<paddle::framework::BlockDesc*> >, std::__1::vector<long long, std::__1::allocator<long long> >, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_>, std::__1::hash<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::equal_to<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const, boost::variant<boost::blank, int, float, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::vector<int, std::__1::allocator<int> >, std::__1::vector<float, std::__1::allocator<float> >, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > >, bool, std::__1::vector<bool, std::__1::allocator<bool> >, paddle::framework::BlockDesc*, long long, std::__1::vector<paddle::framework::BlockDesc*, std::__1::allocator<paddle::framework::BlockDesc*> >, std::__1::vector<long long, std::__1::allocator<long long> >, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> > > >)
9   paddle::pybind::imperative_elementwise_add(std::__1::shared_ptr<paddle::imperative::VarBase> const&, std::__1::shared_ptr<paddle::imperative::VarBase> const&, pybind11::args const&)
10  void pybind11::cpp_function::initialize<std::__1::shared_ptr<paddle::imperative::VarBase> (*&)(std::__1::shared_ptr<paddle::imperative::VarBase> const&, std::__1::shared_ptr<paddle::imperative::VarBase> const&, pybind11::args const&), std::__1::shared_ptr<paddle::imperative::VarBase>, std::__1::shared_ptr<paddle::imperative::VarBase> const&, std::__1::shared_ptr<paddle::imperative::VarBase> const&, pybind11::args const&, pybind11::name, pybind11::scope, pybind11::sibling>(std::__1::shared_ptr<paddle::imperative::VarBase> (*&&&)(std::__1::shared_ptr<paddle::imperative::VarBase> const&, std::__1::shared_ptr<paddle::imperative::VarBase> const&, pybind11::args const&), std::__1::shared_ptr<paddle::imperative::VarBase> (*)(std::__1::shared_ptr<paddle::imperative::VarBase> const&, std::__1::shared_ptr<paddle::imperative::VarBase> const&, pybind11::args const&), pybind11::name const&, pybind11::scope const&, pybind11::sibling const&)::'lambda'(pybind11::detail::function_call&)::operator()(pybind11::detail::function_call&) const
11  pybind11::cpp_function::dispatcher(_object*, _object*, _object*)

----------------------
Error Message Summary:
----------------------
InvalidArgumentError: The Tensor in the elementwise_add Op's Input Variable X(a) is not initialized.
  [Hint: Expected t->IsInitialized() == true, but received t->IsInitialized():0 != true:1.] at (/home/teamcity/work/ef54dc8a5b211854/paddle/fluid/framework/operator.cc:1289)

**Comment by yaoxuefeng6** [comment]
是因为没有切换成静态图模式，关闭issue

**Comment by Shixiaowei02** [comment]
> 是因为没有切换成静态图模式，关闭issue

好的。
