### ISSUE TITLE
mask_rcnn模型 mkldnn 预测出错

### ISSUE THREAD

**Issue by OliverLPH** [PaddlePaddle/Paddle#25078]
**System information**
-PaddlePaddle version: `develop`, `028de85`
-CPU: `Intel(R) Xeon(R) CPU E5-2650 v4 @ 2.20GHz`, mkldnn enabled
-GPU: `P4`, `CUDA10`, `CUDNN7.5`, compile with GPU, but run cpu inference
-OS Platform: `Ubuntu1604`
-Dockerfile: `Paddle/tools/manylinux1/Dockerfile.cuda10_cudnn7_gcc48_ubuntu16`
-Python version: 3.7
-Cmake orders
```
cmake .. -DPYTHON_EXECUTABLE:FILEPATH=/usr/local/bin/python3.7 \
         -DPYTHON_INCLUDE_DIR:PATH=/usr/local/include/python3.7m \
         -DPYTHON_LIBRARIES:FILEPATH=/usr/local/lib/libpython3.7m.so \
         -DWITH_FLUID_ONLY=ON \
         -DWITH_GPU=ON \
         -DWITH_TESTING=OFF \
         -DCMAKE_BUILD_TYPE=Release \
         -DON_INFER=ON \
         -DWITH_INFERENCE_API_TEST=OFF \
         -DWITH_MKL=ON \
         -DWITH_MKLDNN=ON \
         -DTENSORRT_ROOT=/usr
```
-C++version.txt
-API information
```python
config = AnalysisConfig(args.model_file, args.params_file)
config.disable_gpu()
config.enable_mkldnn()
config.set_cpu_math_library_num_threads(4)
config.switch_use_feed_fetch_ops(False)
config.switch_specify_input_names(True)
config.enable_memory_optim()
```
Note: You can get most of the information by running [summary_env.py](https://github.com/PaddlePaddle/Paddle/blob/develop/tools/summary_env.py). 
**To Reproduce**
Steps to reproduce the behavior
```shell
python3.7 infer.py --model_file=./mask_rcnn_r50_1x/model/__model__ \
                                --params_file=./mask_rcnn_r50_1x/model/__params__ \
                                --input_file=./mask_rcnn_r50_1x/data/image.txt
```
**Describe your current behavior**
```
----------------------
Error Message Summary:
----------------------
Error: The Input Variable(X) of roi_align Op used to determine kernel data type is empty or not LoDTensor or SelectedRows or LoDTensorArray.
  [Hint: Expected data_type != dafault_data_type, but received data_type:-1 == dafault_data_type:-1.] at (/workspace/paddle/fluid/framework/operator.cc:1339)
  [operator < roi_align > error]
```
![image](https://user-images.githubusercontent.com/14963836/84756586-903d3480-aff5-11ea-886f-c344501a9f78.png)

**Code to reproduce the issue**
[infer.txt](https://github.com/PaddlePaddle/Paddle/files/4785330/infer.txt)

**Other info / logs**

**Comment by jczaja** [comment]
@sneaxiy , @luotao1 I have reproduced the issue and would like You to advice me on it. Problem related to mkldnn_inplace pass. 
  In particular there is a chain of two operators :  .. A -> Relu -> **B** -> Roi_align -> C .. . And after mkldnn_inplace pass applied we have:  A -> Relu -> **A** -> Roi_Align -> C  . mkldnn_inplace pass does rename Input of ROI_align from B -> A . Normally it works fine, but in this model We have block operator:  **conditional_block_infer_op** , and for some reason when this op is created in runtime then
its input instead being shown as A is still B.  Which cause a problem. I can see that when block op is executed then new scope for it is created . Could you please advice me why could possible not updated Var name is seen as input of operator that is inside conditional block ? should renaming Var names be working for operators executed inside **conditional_block_infer_op**?

**Comment by lidanqing-vv** [comment]
@luotao1  这个问题有哪里描述不清楚的吗？这个问题block了Jacek的工作，他让我协助解释，如果有哪里不清楚的话
conditional_block_infer_op 建立了新的scope，
```
      framework::Executor exec(dev_place);
      auto *block = Attr<framework::BlockDesc *>("sub_block");
      exec.Run(*block->Program(), &cur_scope, block->ID(), false);
      scope.DeleteScope(scopes->front());
```
但是在新scope中，上一层scope的`A -> Relu -> A -> Roi_Align -> C`没被使用，而是原始inplace_pass之前的的`A -> Relu -> B -> Roi_align -> C`被使用了

这个有什么解决办法吗？有没有其他方法可以调用，使得Inplace_pass改的图在第二层scope也可见？还是说设计就是这样的？第二层就不可见了？如果设计就是如此，那我们只能把这个pass注释掉，这个模型就不会fail了。
