### ISSUE TITLE
动态图DataParallel使用问题

### ISSUE THREAD

**Issue by zhangyimi** [PaddlePaddle/Paddle#25077]
paddle1.8.2动态图：
`self.model.loss(a,b)`在使用单卡模式没有问题，
但是
`self.model = fluid.dygraph.parallel.DataParallel(self.model, strategy)
self.model.loss(a,b)
`
会报：
`AttributeError: 'DataParallel' object has no attribute 'loss'`，应该如何使用？

另外在多卡模式下每个print多会打印多次，该如何避免，每次打印前都加上
`if fluid.dygraph.parallel.Env().local_rank == 0：`么

**Comment by Shixiaowei02** [comment]
您好，第一个问题，请参考
https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/fluid/dygraph/parallel.py
中所列的接口。
我找同事回复您第二个问题。

**Comment by chenwhql** [comment]
关于多卡会打印多次的问题，本质上是不能避免的，因为多卡使用多进程执行的，每个进程都会执行同一份code，所以每个进程会各自print

如果您想让日志看起来清爽一些，你可以指定launch的存储日志参数，将日志存储到本地后查看，这样每个进程的日志会分开存储

参考：https://www.paddlepaddle.org.cn/documentation/docs/zh/beginners_guide/basic_concept/dygraph/DyGraph.html#id10

![image](https://user-images.githubusercontent.com/22561442/84775237-875a5c00-b011-11ea-97e8-0ec6434c8268.png)

关于Env的介绍，您可以再详细看下文档，local_rank只是个属性
https://www.paddlepaddle.org.cn/documentation/docs/zh/api_cn/dygraph_cn/ParallelEnv_cn.html#parallelenv

**Comment by zhangyimi** [comment]
@Shixiaowei02 @chenwhql 还有一个问题需要请教，我理解paddle动态图实现多GPU的方式是每张卡一个进程，需要用distributed_batch_reader包装dataloader，然后每个进程根据自己的进程id从loader取对应的数据，但是dataloder是各进程自己实例化和shuffle，这样的话是不是每个进程都必须指定相同的seed，不然各自shuffle的会产生不一致的现象
![image](https://user-images.githubusercontent.com/20926735/84774829-f3889000-b010-11ea-95b9-e7a57cf02ef0.png)

**Comment by zhangyimi** [comment]
另外distributed_batch_reader这种实现方式无法被平均分配的batch就会丢掉是么

**Comment by chenwhql** [comment]
两个问题

1. 如果多个进程没有指定seed，shuffle之后的结果是不一样的，确实需要指定seed

2. distributed_batch_reader无法被平均分配，您是指尾部不足卡数的数据吗？那应该是会被丢弃的，不足卡数的话，训练即使前向执行完，反向allrecude也无法执行

另外distributed_batch_reader是不太友好的，比较暴力的解决方案，我们2.0已经实现了功能更丰富的DataLoader，在多卡场景可以尝试下使用DataLoader+BatchSampler读取数据

参考：
https://www.paddlepaddle.org.cn/documentation/docs/en/2.0-alpha/api/io/DataLoader.html#dataloader

**Comment by zhangyimi** [comment]
thx!
