### ISSUE TITLE
all error stack information: out of memory at (/paddle/paddle/fluid/platform/device_context.cc:221)

### ISSUE THREAD

**Issue by hsyy673150343** [PaddlePaddle/Paddle#25086]
Thank you for contributing to PaddlePaddle. Submitting an issue is a great help for us.
Both Chinese and English issues are welcome.

It's hard to solve a problem when important details are missing.
Before submitting the issue, look over the following criteria before handing your request in.

- [x] Was there a similar issue submitted or resolved before ? You could search issue in the github.
- [ ] Did you retrieve your issue from widespread search engines ?
- [x] Is my description of the issue clear enough to reproduce this problem?
   * If some errors occurred, we need details about `how do you run your code?`, `what system do you use?`, `Are you using GPU or not?`, etc.
   * If you use an recording [asciinema](https://asciinema.org/) to show what you are doing to make it happen, that's awesome! We could help you solve the problem more quickly.
- [x] Is my description of the issue use the github markdown correctly?
   * Please use the proper markdown syntaxes for styling all forms of writing, e.g, source code, error information, etc.
   * Check out [this page](https://guides.github.com/features/mastering-markdown/) to find out much more about markdown.

**Comment by Shixiaowei02** [comment]
您好，请准确描述一下您的问题，谢谢！

**Comment by hsyy673150343** [comment]
感谢您百忙之中回复邮件，我问题解决了。昨天是在运行程序的过程中，强制kill了进程，导致GPU显存未能得到释放，后面再次运行程序的时候提示GPU显存不足。










在 2020-06-17 17:43:14，"石晓伟" <notifications@github.com> 写道：

您好，请准确描述一下您的问题，谢谢！

**Comment by Shixiaowei02** [comment]
好的，收到。谢谢您的支持。
