### ISSUE TITLE
c++ 输入格式

### ISSUE THREAD

**Issue by OliveLv** [PaddlePaddle/Paddle#25087]
python版本输入为
fluid.layers.data(name='x', shape=[input_size], dtype='float32')

c++版本输入应该怎么设置？
目前设置为
std::vector<float> features;
paddle::PaddleTensor tensor;
tensor.shape = std::vector<int>(features.size());
tensor.data = paddle::PaddleBuf(&features[0], features.size() * sizeof(float));
tensor.dtype = paddle::PaddleDType::FLOAT32;
但进行预测，提示失败，没报错，辛苦帮忙看下

**Comment by Shixiaowei02** [comment]
```
std::vector<float> features;
tensor.data = paddle::PaddleBuf(features.data(), features.size() * sizeof(float));
```
您好，上面其中的两句改了下，别的没问题

**Comment by OliveLv** [comment]
> ```
> std::vector<float> features;
> tensor.data = paddle::PaddleBuf(features.data(), features.size() * sizeof(float));
> ```
> 
> 您好，上面其中的两句改了下，别的没问题

修改后 还是一样，提示失败，没报错

**Comment by Shixiaowei02** [comment]
> > ```
> > std::vector<float> features;
> > tensor.data = paddle::PaddleBuf(features.data(), features.size() * sizeof(float));
> > ```
> > 
> > 
> > 您好，上面其中的两句改了下，别的没问题
> 
> 
> 修改后 还是一样，提示失败，没报错

请问具体的失败信息是什么，麻烦贴一下吧。

**Comment by OliveLv** [comment]
> > > ```
> > > std::vector<float> features;
> > > tensor.data = paddle::PaddleBuf(features.data(), features.size() * sizeof(float));
> > > ```
> > > 
> > > 
> > > 您好，上面其中的两句改了下，别的没问题
> > 
> > 
> > 修改后 还是一样，提示失败，没报错
> 
> 请问具体的失败信息是什么，麻烦贴一下吧。

整体代码如下
```
paddle::AnalysisConfig model_config(model_path.c_str());
model_config.DisableGpu();
model_config.SwitchIrOptim();
std::unique_ptr<paddle::PaddlePredictor> predictor = paddle::CreatePaddlePredictor(model_config);

std::vector<float> features;
paddle::PaddleTensor tensor;
tensor.shape = std::vector<int>(features.size());
tensor.data = paddle::PaddleBuf(features.data(), features.size() * sizeof(float));
tensor.dtype = paddle::PaddleDType::FLOAT32;
std::vector<paddle::PaddleTensor> slots(1, tensor);
std::vector<paddle::PaddleTensor> outputs;
int ret = predictor->Run(slots, &outputs);

MAP_LOG_DEBUG("debug[%d]", ret);
```
返回为false，没有其他报错信息了，辛苦帮忙看下
debug[0]
