### ISSUE TITLE
关于动态图模式下包含Embedding的训练loss 不降低的问题

### ISSUE THREAD

**Issue by fiyen** [PaddlePaddle/Paddle#25080]
- 版本、环境信息：
    1）PaddlePaddle版本：Paddle 1.8
    2）CPU/GPU：GPU，在AI Studio上用v100训练
    3）系统环境：线上

我用动态图模式搭建模型时，引入Embedding层后就会出现loss不降低的问题，训练一直不收敛。代码截图如下：
![image](https://user-images.githubusercontent.com/35953131/84768132-4c066000-b006-11ea-9431-481caec71cc1.png)

![image](https://user-images.githubusercontent.com/35953131/84768183-63dde400-b006-11ea-854a-3626f3c2cefe.png)

![image](https://user-images.githubusercontent.com/35953131/84768253-853ed000-b006-11ea-8e51-e58959a3e6eb.png)

希望排查一下问题。

**Comment by fiyen** [comment]
没人吗？？

**Comment by fiyen** [comment]
问题已解决。主要原因是Adam优化器创建的时间点不对。在Adam优化器创建的时候，forward函数还没有被访问，所以训练参数没有全部创建。这个时候创建Adam优化器，参数是不全的，所以就会有参数没有被训练。
解决方法是将Adam优化器的创建放到loss后向传播之后。个人尝试Adam每个batch都创建和创建一次差别不大。所以可以用判断条件只创建一次，或者每个batch都创建一次。但是是否影响速度就不清楚了。

**Comment by Maybewuss** [comment]
> 问题已解决。主要原因是Adam优化器创建的时间点不对。在Adam优化器创建的时候，forward函数还没有被访问，所以训练参数没有全部创建。这个时候创建Adam优化器，参数是不全的，所以就会有参数没有被训练。
> 
> 解决方法是将Adam优化器的创建放到loss后向传播之后。个人尝试Adam每个batch都创建和创建一次差别不大。所以可以用判断条件只创建一次，或者每个batch都创建一次。但是是否影响速度就不清楚了。

这也太难顶了。。
