### ISSUE TITLE
Use std::variant instead of boost::variant

### ISSUE THREAD

**Issue by wangkuiyi** [PaddlePaddle/Paddle#2509]
It seems that the difference between std::variant and boost::variant https://stackoverflow.com/a/40204093/724872 shouldn't affect our code.

If we can do so, It seems that we don't have to rely on boost.

**Comment by gangliao** [comment]
I noticed std::variant only works under c++17. @wangkuiyi

**Comment by wangkuiyi** [comment]
Got it! Thanks for the remind! @gangliao I noticed you mentioned that nvcc doesn't support C++17 well in https://github.com/PaddlePaddle/Paddle/pull/2513#discussion_r122896646. Let's keep using `boost::variant`.
