### ISSUE TITLE
新增OP开发碰到的问题

### ISSUE THREAD

**Issue by vslyu** [PaddlePaddle/Paddle#25099]
根据Paddle官网的进阶教程中新增OP的教程——[如何写新增的C++ OP](https://www.paddlepaddle.org.cn/documentation/docs/zh/advanced_guide/addon_development/new_op/new_op.html)，
按照教程所给的步骤：
在build/paddle/fluid/operators目录下，运行下面命令可以进行编译：make mul_op；但是在本地端无法显示无此rule：
```bash
[vslyu@yq01-hpc-bdl161.yq01.baidu.com operators]$ make similarity_focus_op1
/usr/bin/make64 MAC=64 similarity_focus_op1
make64: *** No rule to make target `similarity_focus_op1'.  Stop.
```
请问是还需要修改对应的哪个cmakelists么？~

**Comment by zhhsplendid** [comment]
看上去是没有添加similarity_focus_op1到cmakelist里，你的理解是对的

**Comment by zhhsplendid** [comment]
你添加到你放op那个文件夹下的cmakelist就可以了，然后该cmakelist里其他op的添加方式可以作为示例

**Comment by zhiqiu** [comment]
hi，@vslyu 你需要重新cmake一下，然后再make xx_op。
