### ISSUE TITLE
希望提供保存可恢复训练的网络结构和参数的方法

### ISSUE THREAD

**Issue by chenxiaoyu3** [PaddlePaddle/Paddle#25105]
根据官方文档：
https://www.paddlepaddle.org.cn/documentation/docs/zh/beginners_guide/coding_practice/save_load_variables.html

目前fluid提供的4种save方法中，可增量训练的三种save方法，都是仅保存了变量，不包括program的网络结构本身，使用时，一定要先有program才能load再训练，使用过程中多有不便。

希望能提供保存可恢复训练的网络结构和参数的方法

**Comment by zhupengyang** [comment]
试下 [paddle.fluid.save](https://www.paddlepaddle.org.cn/documentation/docs/zh/api_cn/fluid_cn/save_cn.html#save) ?

**Comment by chenxiaoyu3** [comment]
> 试下 [paddle.fluid.save](https://www.paddlepaddle.org.cn/documentation/docs/zh/api_cn/fluid_cn/save_cn.html#save) ?

这个方法对应的load方法，还是要先有Program，才能load。期望有的是，save program+varialbe，load直接从文件中读取program和variable

**Comment by chenwhql** [comment]
嗯嗯，感谢反馈，我们后续考虑下满足这个需求
