### ISSUE TITLE
index_sample接口找不到

### ISSUE THREAD

**Issue by zhangyimi** [PaddlePaddle/Paddle#25101]
paddle1.8.2：
在fluid.layers下找不到index_sample，如果接口被移除该如何实现类似操作？

**Comment by zhhsplendid** [comment]
有这个的呀？https://www.paddlepaddle.org.cn/documentation/docs/zh/api_cn/layers_cn/index_sample_cn.html#index-sample

**Comment by zhhsplendid** [comment]
你试试paddle.index_sample？

**Comment by zhhsplendid** [comment]
已线下沟通，paddle正好1.8版本没有这个接口，前后都有。。用别的用gather_nd实现了。
