### ISSUE TITLE
cmake在编译paddle推理库的时候报错，百度Google也没找到方法

### ISSUE THREAD

**Issue by tspp520** [PaddlePaddle/Paddle#25106]
![image](https://user-images.githubusercontent.com/13615964/84906698-dcb36d80-b0e4-11ea-8a4c-7a9366fa69d8.png)

CMake Error at D:/pd/cmake-3.16.8-win64-x64/share/cmake-3.16/Modules/CMakeDetermineCompilerId.cmake:352 (message):
No CUDA toolset found.
Call Stack (most recent call first):
D:/pd/cmake-3.16.8-win64-x64/share/cmake-3.16/Modules/CMakeDetermineCompilerId.cmake:32 (CMAKE_DETERMINE_COMPILER_ID_BUILD)
D:/pd/cmake-3.16.8-win64-x64/share/cmake-3.16/Modules/CMakeDetermineCUDACompiler.cmake:72 (CMAKE_DETERMINE_COMPILER_ID)
CMakeLists.txt:31 (enable_language)

Configuring incomplete, errors occurred!
See also "D:/pd/Paddle-develop/vs2015/CMakeFiles/CMakeOutput.log".
See also "D:/pd/Paddle-develop/vs2015/CMakeFiles/CMakeError.log".

**Comment by tspp520** [comment]
路过的大哥大姐，大佬小弟小姐姐，不妨给个答案，感激不尽！

**Comment by zhhsplendid** [comment]
从cmake报错信息看，没有cuda，请检查好您的环境？

**Comment by zhhsplendid** [comment]
嗨，这个卡片您没有更新更多信息，可以查看一下cuda安装情况？或者cmake选项不使用cuda，您试试能否编译成功？已经过去一个月没收到更新，我将关闭此issue，如果您还遇到问题，可以重新打开此issue回复我？
