### ISSUE TITLE
concat广播出错

### ISSUE THREAD

**Issue by zhangyimi** [PaddlePaddle/Paddle#25102]
paddle1.8.2动态图：
rt

![image](https://user-images.githubusercontent.com/20926735/84897994-1c745800-b0d9-11ea-99be-f8f9c1704526.png)

**Comment by zhhsplendid** [comment]
收到，会反馈

**Comment by zhhsplendid** [comment]
嗨，经过更多调研，我们发现numpy，pytorch都不支持形状[3, 1, 1]和[3, 1]的concat，数学意义上不同维度shape concat也不太成立。我们将在下一版本不支持这种concat功能，而是抛出报错信息。

**Comment by wangchaochaohu** [comment]
> 嗨，经过更多调研，我们发现numpy，pytorch都不支持形状[3, 1, 1]和[3, 1]的concat，数学意义上不同维度shape concat也不太成立。我们将在下一版本不支持这种concat功能，而是抛出报错信息。

后续版本会考虑添加报错信息提示这种行为
