### ISSUE TITLE
albert模型EnableMKLDNN和SwitchIrOptim预估出core

### ISSUE THREAD

**Issue by xdylittle** [PaddlePaddle/Paddle#25115]
- 版本、环境信息：
    1）PaddlePaddle版本：v1.8.1-gcc82-mkl-avx-mkldnn_PD_BL
    2）CPU：Intel(R) Xeon(R) CPU E5-2650 v3 @ 2.30GHz, EnableMKLDNN, SwitchIrOptim=true
    4）系统环境：Linux version 2.6.32_1-17-0-0, x86_64

-预测信息
    1）C++预测：v1.8.1-gcc82-mkl-avx-mkldnn_PD_BL
         version.txt:
         GIT COMMIT ID: ea1c05d0e61ddb1bd69b9f7fa82898a9c9859126
         WITH_MKL: ON
         WITH_MKLDNN: ON
         WITH_GPU: OFF
         AVX: ON
    2）CMake包含路径的完整命令
          CONFIGS("baidu/lib/paddlepaddle@v1.8.1-gcc82-mkl-avx-mkldnn_PD_BL@git_tag", NeedPreBuild())
          LIBS('../../lib/paddlepaddle/third_party/install/mklml/lib/libmklml_intel.so')
          LIBS('../../lib/paddlepaddle/third_party/install/mklml/lib/libiomp5.so')
          LIBS('../../lib/paddlepaddle/third_party/install/mkldnn/lib/libdnnl.so.1')
          LIBS('../../lib/paddlepaddle/third_party/install/mkldnn/lib/libmkldnn.so.0')
          LIBS('$OUT_ROOT/baidu/lib/paddlepaddle/output/so/libpaddle_fluid.so')
    3）API信息
          config.DisableGpu();
          config.SetCpuMathLibraryNumThreads(20);
          config.EnableMKLDNN();
          config.SwitchUseFeedFetchOps(false);
          config.SwitchSpecifyInputNames(true);
          config.SwitchIrDebug(false);
          config.SwitchIrOptim(true);
    4）预测库来源：BCLOUD编译

- 问题描述：
按照上面的配置预估模型，同时enablemkldnn和switchiroptim出core
如果去掉enablemkldnn或者switchiroptim设置false则不出core

错误信息：
```
----------------------
Error Message Summary:
----------------------
Error: The VarDescs of persistable variable are not consistency. at (/home/scmbuild/workspaces_cluster.dev/baidu.lib.paddlepaddle/baidu/lib/paddlepaddle/Paddle/paddle/fluid/framework/ir/pass.cc:46)
```
![image](https://user-images.githubusercontent.com/4735227/84975861-14f49380-b159-11ea-8bd5-7af64d8ab398.png)

**Comment by ysh329** [comment]
1. 是单机还是分布式环境呢；
2. SwitchIrOptim(false)试试，看是否能行
