### ISSUE TITLE
Pserver register themselves on etcd.

### ISSUE THREAD

**Issue by typhoonzero** [PaddlePaddle/Paddle#2511]

**Comment by helinwang** [comment]
HI @typhoonzero Please refer to here for the registration process design doc: https://github.com/PaddlePaddle/Paddle/blob/develop/doc/design/cluster_train/README.md#parameter-server-process-1 
Feel free to submit change to design doc in PR if you feel anywhere needs change :)

**Comment by typhoonzero** [comment]
Designs and usages of etcd3 transactions: https://coreos.com/blog/transactional-memory-with-etcd3.html
