### ISSUE TITLE
基于设定目标的L2正则

### ISSUE THREAD

**Issue by DTaoo** [PaddlePaddle/Paddle#25112]
主要需求是这样：
有一个pretrain network N，目标是在一个新的数据集上进行finetune。但是在finetune过程中，希望网络每一个layer的权重被约束在pretrain weight的周围（L2-norm). 以往的L2-norm weight-decay本质上是在约束零点，这是主要区别。请问要实现这样的需求，是不是需要修改一下L2DecayRegularizer类。

谢谢

欢迎您对PaddlePaddle提出建议，非常感谢您对PaddlePaddle的贡献！
在留下您的建议时，辛苦您同步提供如下信息：
- 版本、环境信息
1）PaddlePaddle版本：1.7.1
2）CPU/GPU：您是否使用GPU进行训练，如是，请提供您的CUDA和cuDNN版本号
3）系统环境：PaddleCould v1.7.1
注：您可以通过执行[summary_env.py](https://github.com/PaddlePaddle/Paddle/blob/develop/tools/summary_env.py)获取以上信息。
- 复现信息：如为报错，请给出复现环境、复现步骤
- 建议描述：请您详细描述，您认为需优化的功能

Thank you for contributing to PaddlePaddle.
Before submitting the issue, you could search issue in the github in case that there was a similar issue submitted or resolved before.
Please make sure that this is a feature request. 
**System information**
-PaddlePaddle version （eg.1.1）or CommitID
-CPU: including CPUMKL/OpenBlas/MKLDNN version
-GPU: including CUDA/CUDNN version
-OS Platform (eg.Mac OS 10.14)
Note: You can get most of the information by running [summary_env.py](https://github.com/PaddlePaddle/Paddle/blob/develop/tools/summary_env.py). 
**To Reproduce**
Steps to reproduce the behavior
**Describe the feature and the current behavior/state.**
**Any Other info.**

**Comment by ysh329** [comment]
收到反馈，我问一下我们团队的同学

**Comment by ysh329** [comment]
应该是的，可以先改改看，如果有问题在交流
