### ISSUE TITLE
transformer模型save_inference_model之后进行预测报错

### ISSUE THREAD

**Issue by gromzhu** [PaddlePaddle/Paddle#25122]
将训练好的transformer模型save_inference_model之后，加载保存的inference_model预测，报错shape不同，我用paddle保存模型的时候tensor shape设置的是(none,1)，然后预测的时候我传shape（-1，1）的变量进去报错shape不相等。

报错信息
  File ".jumbo/lib/python2.7/site-packages/paddle/fluid/executor.py", line 225, in check_feed_shape_type
    (var.name, len(var.shape), var.shape, diff_shape))
ValueError: The fed Variable u'init_score' should have dimensions = 1, shape = (0L,), but received fed shape [-1L, 1L] on each device

**Comment by guoshengCS** [comment]
这个可能是由于beam search op没有正确的设置输出的形状导致score的形状变成0了，需要完善下，我们后续修改完善下。也可以暂时将报错这里的`.jumbo/lib/python2.7/site-packages/paddle/fluid/executor.py check_feed_shape_type` 的shape检查先注释掉使用试下，另外C++预测应该是不受这个形状检查的影响的

**Comment by gromzhu** [comment]
> 这个可能是由于beam search op没有正确的设置输出的形状导致score的形状变成0了，需要完善下，我们后续修改完善下。也可以暂时将报错这里的`.jumbo/lib/python2.7/site-packages/paddle/fluid/executor.py check_feed_shape_type` 的shape检查先注释掉使用试下，另外C++预测应该是不受这个形状检查的影响的

注释掉check_feed_shape_type能够预测了，但是结果不对。同样的输入，不使用 save_inference_model 结果正确，但是使用save_inference_model 之后结果出错。

**Comment by jiweibo** [comment]
尝试合入这个pr，重新编个wheel包测试看下，由于models下的transformer组网while内部的输出改变了模型的输入，确认下是不是对于transformer来说裁剪出了问题？
https://github.com/PaddlePaddle/Paddle/pull/23306

**Comment by gromzhu** [comment]
> 尝试合入这个pr，重新编个wheel包测试看下，由于models下的transformer组网while内部的输出改变了模型的输入，确认下是不是对于transformer来说裁剪出了问题？
> #23306

新编译paddle保存的模型可以正常预测了
