### ISSUE TITLE
请问Array 转 tensor的函数是什么？找了很久都没找到

### ISSUE THREAD

**Issue by ChengliangChai** [PaddlePaddle/Paddle#25124]

**Comment by ysh329** [comment]
麻烦具体描述一下问题吧，拜托🙏啦

问下是python还是c++，二者貌似都有array。
如果是 std::array 的话，应该是可以像 vector 到 tensor 一样，通过指针和大小进行构造；如果是 python 的 array，需要先转换为 numpy。

 Paddle 内部好像没有 paddle::Array 这种容器

**Comment by ChengliangChai** [comment]
> 麻烦具体描述一下问题吧，拜托🙏啦
> 
> 问下是python还是c++，二者貌似都有array。
> 如果是 std::array 的话，应该是可以像 vector 到 tensor 一样，通过指针和大小进行构造；如果是 python 的 array，需要先转换为 numpy。
> 
> Paddle 内部好像没有 paddle::Array 这种容器

conv3 = fluid.nets.sequence_conv_pool(emb, num_filters=HID_DIM, filter_size=3, act="tanh",pool_type='sqrt')
 conv4 = fluid.nets.sequence_conv_pool(emb, num_filters=HID_DIM, filter_size=4, act="tanh",pool_type='sqrt')
 inputs = [conv3, conv4]

我想打印inputs, 但是fetch_list只支持tensor,因此感觉需要将inputs转成tensor

 inputs = fluid.layers.assign(np.array([conv3, conv4])) 这样好像也不行~

请问怎么办呢？ 谢谢！
