### ISSUE TITLE
模型使用PaddlePredictor预测保存:Error: Tensor not initialized yet when Tensor::type() is called.

### ISSUE THREAD

**Issue by dianhuasici** [PaddlePaddle/Paddle#25126]
`Error: Tensor not initialized yet when Tensor::type() is called.`
` [Hint: holder_ should not be null.] at (/paddle/paddle/fluid/framework/tensor.h:140)`

使用fluid.io.load_inference_model 是可以正常运行的
加上GLOG_vmodule=operator=4 GLOG_logtostderr=1之后

`I0618 21:33:58.800720  4577 operator.cc:159] CPUPlace Op(elementwise_add), inputs:{X[tmp_0:float[11, 600]({})], Y[tmp_1:float[11, 600]({})]}, outputs:{Out[tmp_2:[0]({})]}.
I0618 21:33:58.800734  4577 operator.cc:1050] expected_kernel_key:data_type[float]:data_layout[ANY_LAYOUT]:place[CPUPlace]:library_type[PLAIN]
I0618 21:33:58.800781  4577 operator.cc:174] CPUPlace Op(elementwise_add), inputs:{X[tmp_0:float[11, 600]({})], Y[tmp_1:float[11, 600]({})]}, outputs:{Out[tmp_2:float[11, 600]({})]}.
I0618 21:33:58.800802  4577 operator.cc:159] CPUPlace Op(tanh), inputs:{X[tmp_2:float[11, 600]({})]}, outputs:{Out[tanh_1.tmp_0:[0]({})]}.
I0618 21:33:58.800815  4577 operator.cc:1050] expected_kernel_key:data_type[float]:data_layout[ANY_LAYOUT]:place[CPUPlace]:library_type[PLAIN]
I0618 21:33:58.800851  4577 operator.cc:174] CPUPlace Op(tanh), inputs:{X[tmp_2:float[11, 600]({})]}, outputs:{Out[tanh_1.tmp_0:float[11, 600]({})]}.
I0618 21:33:58.800865  4577 operator.cc:159] CPUPlace Op(sigmoid), inputs:{X[slice_5.tmp_0:float[11, 600]({})]}, outputs:{Out[sigmoid_2.tmp_0:[0]({})]}.
I0618 21:33:58.800877  4577 operator.cc:1050] expected_kernel_key:data_type[float]:data_layout[ANY_LAYOUT]:place[CPUPlace]:library_type[PLAIN]
I0618 21:33:58.800916  4577 operator.cc:174] CPUPlace Op(sigmoid), inputs:{X[slice_5.tmp_0:float[11, 600]({})]}, outputs:{Out[sigmoid_2.tmp_0:float[11, 600]({})]}.
I0618 21:33:58.800936  4577 operator.cc:159] CPUPlace Op(elementwise_mul), inputs:{X[tanh_1.tmp_0:float[11, 600]({})], Y[sigmoid_2.tmp_0:float[11, 600]({})]}, outputs:{Out[tmp_3:[0]({})]}.
I0618 21:33:58.800949  4577 operator.cc:1050] expected_kernel_key:data_type[float]:data_layout[ANY_LAYOUT]:place[CPUPlace]:library_type[PLAIN]
I0618 21:33:58.800983  4577 operator.cc:174] CPUPlace Op(elementwise_mul), inputs:{X[tanh_1.tmp_0:float[11, 600]({})], Y[sigmoid_2.tmp_0:float[11, 600]({})]}, outputs:{Out[tmp_3:float[11, 600]({})]}.
I0618 21:33:58.801002  4577 operator.cc:159] CPUPlace Op(rnn_memory_helper), inputs:{X[tmp_3:float[11, 600]({})]}, outputs:{Out[encode_fw.tmp_0:[0]({})]}.
I0618 21:33:58.801031  4577 operator.cc:174] CPUPlace Op(rnn_memory_helper), inputs:{X[tmp_3:float[11, 600]({})]}, outputs:{Out[encode_fw.tmp_0:float[11, 600]({})]}.
I0618 21:33:58.801048  4577 operator.cc:159] CPUPlace Op(rnn_memory_helper), inputs:{X[tmp_2:float[11, 600]({})]}, outputs:{Out[encode_fw.tmp_1:[0]({})]}.
I0618 21:33:58.801070  4577 operator.cc:174] CPUPlace Op(rnn_memory_helper), inputs:{X[tmp_2:float[11, 600]({})]}, outputs:{Out[encode_fw.tmp_1:float[11, 600]({})]}.
I0618 21:33:58.801087  4577 operator.cc:159] CPUPlace Op(rnn_memory_helper), inputs:{X[tmp_3:float[11, 600]({})]}, outputs:{Out[encode_fw.tmp_2:[0]({})]}.
I0618 21:33:58.801106  4577 operator.cc:174] CPUPlace Op(rnn_memory_helper), inputs:{X[tmp_3:float[11, 600]({})]}, outputs:{Out[encode_fw.tmp_2:float[11, 600]({})]}.
I0618 21:33:58.801122  4577 operator.cc:159] CPUPlace Op(rnn_memory_helper), inputs:{X[tmp_2:float[11, 600]({})]}, outputs:{Out[encode_fw.tmp_3:[0]({})]}.
I0618 21:33:58.801141  4577 operator.cc:174] CPUPlace Op(rnn_memory_helper), inputs:{X[tmp_2:float[11, 600]({})]}, outputs:{Out[encode_fw.tmp_3:float[11, 600]({})]}.
I0618 21:33:58.801158  4577 operator.cc:159] CPUPlace Op(rnn_memory_helper), inputs:{X[tmp_3:float[11, 600]({})]}, outputs:{Out[encode_fw.tmp_4:[0]({})]}.
I0618 21:33:58.801177  4577 operator.cc:174] CPUPlace Op(rnn_memory_helper), inputs:{X[tmp_3:float[11, 600]({})]}, outputs:{Out[encode_fw.tmp_4:float[11, 600]({})]}.
`

**Comment by ysh329** [comment]
我没看懂，是有什么问题嘛，还请具体描述下
看起来是Tensor没初始化的报错，还请再检查一下

```shell
Error: Tensor not initialized yet when Tensor::type() is called.
[Hint: holder_ should not be null.]
```
