### ISSUE TITLE
onnx模型转换有问题

### ISSUE THREAD

**Issue by HaoLiuHust** [PaddlePaddle/Paddle#25135]
原始模型是mxnet的识别模型，我转换成onnx（onnx已经与mxnet模型比对可以拿到一样的结果）之后用paddle做推理，发现与onnx推理出的结果余弦相似度为0。然后我将mxnet模型转换成caffe之后再用x2paddle转换成paddle模型测试，发现结果与onnx推理出的结果相似度为1

系统：ubuntu16.04  
语言：python3.6  
cuda: 9.2  
cudnn:7.6.5  
paddle：１.８　　

复现材料：
链接：https://pan.baidu.com/s/1VzFeZvj-8YR9Om5RxO2TlQ 
提取码：upej 
其中models里面有onnx模型和caffe模型，paddle_caffe，paddle_onnx分别是caffe和onnx转化成的paddle模型。paddle_eval2.py是测试他们的相似度

**Comment by MRXLT** [comment]
你好，感谢反馈，我们会进行排查和修复

**Comment by Channingss** [comment]
@HaoLiuHust 意思是onnx2paddle和caffe2paddle之后的结果完全一致，但是和onnx本身推理的结果不一致？

**Comment by HaoLiuHust** [comment]
@Channingss 不是，caffe2paddle的结果与onnx本身一致，onnx2paddle不一致

**Comment by Channingss** [comment]
好的，感谢反馈，我这边测试一下。

**Comment by HaoLiuHust** [comment]
这个问题找到原因了么

**Comment by HaoLiuHust** [comment]
有复现么

**Comment by Channingss** [comment]
@HaoLiuHust 麻烦拉取最新的X2Paddle测试一下ONNX2Paddle的正确性，ONNX2Paddle模块最近修复了一些bug，如果还有问题，辛苦再发一下模型。

**Comment by jiachen0212** [comment]
求教，有遇到 pytorch转onnx后可正常预测，但onnx转paddle出现尺寸错误的大佬吗
