### ISSUE TITLE
如何查看每一层的参数

### ISSUE THREAD

**Issue by HaoLiuHust** [PaddlePaddle/Paddle#25136]
使用x2paddle转换出的模型，如何查看每一层参数值呢。用load_inference_model载入之后，用program.blocks[0].all_parameters()获取出来是一个空的list

**Comment by fiyen** [comment]
如果是静态图模式的话，可以run一下fetch_list=[main_program.all_parameters()]来获取。

**Comment by HaoLiuHust** [comment]
@fiyen 也是空的list，这个main_program是load_inference_model返回的吧？

**Comment by ShaneTian** [comment]
静态图，我用 `print(fluid.io.get_program_parameter(train_startup))` 有效

**Comment by HaoLiuHust** [comment]
好神奇。。拿出来也是空的 @ShaneTian

**Comment by fiyen** [comment]
> 好神奇。。拿出来也是空的 @ShaneTian

会不会是你读取的是个空的模型？你的模型可以直接用来做预测任务吗？

**Comment by HaoLiuHust** [comment]
可以的，还测过精度和转换前的模型精度一样，我把模型和脚本上传一下吧

**Comment by HaoLiuHust** [comment]
链接：https://pan.baidu.com/s/1IrYhKHP5rpNBlN-Asbs2nQ 
提取码：0sxj
@fiyen

**Comment by HaoLiuHust** [comment]
如果从model_with_code中读取，然后再load_vars是可以的，先关了吧

**Comment by HaoLiuHust** [comment]
只有load vars行，其他方式不行。。。

**Comment by HaoLiuHust** [comment]
我下载了官方model zoo的模型，想看看权重值，也是没办法看

**Comment by HaoLiuHust** [comment]
找到方法了，用fluid.global_scope().find_var(“var_name”).get_tensor()
