### ISSUE TITLE
可正常训练的代码的reader中，新增运行inference_model时，定义CUDAPlace报错

### ISSUE THREAD

**Issue by wang-kangkang** [PaddlePaddle/Paddle#25138]
模型训练遇到个问题。我的场景是首先有一个可以正常训练的代码，reader使用multiprocess_reader封装，设置worker=8。
现在需要在reader中再跑一个inference_model用于现场打标签。worker=8的话相当于每一个进程中都有一个place。结果程序启动后报错：Error: cudaSetDevice failed in paddle::platform::SetDeviced, error code ，但是我发现定义成fluid.CPUPlace()就能跑。
我尝试把外部的place当作变量传入reader中，也不管用。
请问这个问题该怎么解决

**Comment by MRXLT** [comment]
多进程的reader会导致CUDAPlace在多个进程中初始化造成错误，建议使用python 预测api来执行第一个模型的打标签预测
