### ISSUE TITLE
inference引擎预测时不能使用gpu预测

### ISSUE THREAD

**Issue by 17806242857** [PaddlePaddle/Paddle#25149]
AI studio预装的cuda cudnn版本 
报错：cudnn error ，cudnn_status_not_supported at(/paddle/paddle/fluid/platform/cudnn_desc.h:142)
[operator<conv2d_transpose>error]

**Comment by hong19860320** [comment]
请提供下AI Studio的项目地址，需要提醒的是，启动环境时必须是带有GPU环境。例如下图所示：
![image](https://user-images.githubusercontent.com/9973393/85248983-18538c00-b485-11ea-990a-fb45419a0d74.png)

**Comment by 17806242857** [comment]
> 请提供下AI Studio的项目地址，需要提醒的是，启动环境时必须是带有GPU环境。例如下图所示：
> ![图片](https://user-images.githubusercontent.com/9973393/85248983-18538c00-b485-11ea-990a-fb45419a0d74.png)

环境是gpu环境。两个网络，另一个网络可以预测。

**Comment by hong19860320** [comment]
> > 请提供下AI Studio的项目地址，需要提醒的是，启动环境时必须是带有GPU环境。例如下图所示：
> > ![图片](https://user-images.githubusercontent.com/9973393/85248983-18538c00-b485-11ea-990a-fb45419a0d74.png)
> 
> 环境是gpu环境。两个网络，另一个网络可以预测。

是否能把ai studio 项目开放出来，我们这边好fork后复现问题

**Comment by 17806242857** [comment]
> > > 请提供下AI Studio的项目地址，需要提醒的是，启动环境时必须是带有GPU环境。例如下图所示：
> > > ![图片](https://user-images.githubusercontent.com/9973393/85248983-18538c00-b485-11ea-990a-fb45419a0d74.png)
> > 
> > 
> > 环境是gpu环境。两个网络，另一个网络可以预测。
> 
> 是否能把ai studio项目开放出来，我们这边好fork后复现问题

开放不了。文件太大。

**Comment by hong19860320** [comment]
从报错上看，应该是安装的cudnn的版本问题，你在本地能复现该问题吗？

**Comment by hong19860320** [comment]
想问下，有试过跑其它简单的模型吗？例如resnet-50

**Comment by 17806242857** [comment]
> 想问下，有试过跑其它简单的模型吗？例如resnet-50

今天重新加载不报那个错误了，但是提示内存溢出，允许的内存只有4.462830GB，16GB的gpu而且我也没运行别的程序啊。怎么会溢出

**Comment by hong19860320** [comment]
> > 想问下，有试过跑其它简单的模型吗？例如resnet-50
> 
> 今天重新加载不报那个错误了，但是提示内存溢出，允许的内存只有4.462830GB，16GB的gpu而且我也没运行别的程序啊。怎么会溢出

报错的详细log麻烦贴下哈，还有能提供简单复现的代码吗？我们准备好定位问题

**Comment by 17806242857** [comment]
> > > 想问下，有试过跑其它简单的模型吗？例如resnet-50
> > 
> > 
> > 今天重新加载不报那个错误了，但是提示内存溢出，允许的内存只有4.462830GB，16GB的gpu而且我也没运行别的程序啊。怎么会溢出
> 
> 报错的详细log麻烦贴下哈，还有能提供简单复现的代码吗？我们准备好定位问题

C++ Call Stacks (More useful to developers):
--------------------------------------------
0   std::string paddle::platform::GetTraceBackString<std::string>(std::string&&, char const*, int)
1   paddle::memory::allocation::CUDAAllocator::AllocateImpl(unsigned long)
2   paddle::memory::allocation::AlignedAllocator::AllocateImpl(unsigned long)
3   paddle::memory::allocation::AutoGrowthBestFitAllocator::AllocateImpl(unsigned long)
4   paddle::memory::allocation::Allocator::Allocate(unsigned long)
5   paddle::memory::allocation::RetryAllocator::AllocateImpl(unsigned long)
6   paddle::memory::allocation::AllocatorFacade::Alloc(paddle::platform::Place const&, unsigned long)
7   paddle::memory::allocation::AllocatorFacade::AllocShared(paddle::platform::Place const&, unsigned long)
8   paddle::memory::AllocShared(paddle::platform::Place const&, unsigned long)
9   paddle::framework::Tensor::mutable_data(paddle::platform::Place const&, paddle::framework::proto::VarType_Type, unsigned long)
10  paddle::operators::ElementwiseAddKernel<paddle::platform::CUDADeviceContext, float>::Compute(paddle::framework::ExecutionContext const&) const
11  std::_Function_handler<void (paddle::framework::ExecutionContext const&), paddle::framework::OpKernelRegistrarFunctor<paddle::platform::CUDAPlace, false, 0ul, paddle::operators::ElementwiseAddKernel<paddle::platform::CUDADeviceContext, float>, paddle::operators::ElementwiseAddKernel<paddle::platform::CUDADeviceContext, double>, paddle::operators::ElementwiseAddKernel<paddle::platform::CUDADeviceContext, int>, paddle::operators::ElementwiseAddKernel<paddle::platform::CUDADeviceContext, long>, paddle::operators::ElementwiseAddKernel<paddle::platform::CUDADeviceContext, paddle::platform::float16> >::operator()(char const*, char const*, int) const::{lambda(paddle::framework::ExecutionContext const&)#1}>::_M_invoke(std::_Any_data const&, paddle::framework::ExecutionContext const&)
12  paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, paddle::platform::Place const&, paddle::framework::RuntimeContext*) const
13  paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, paddle::platform::Place const&) const
14  paddle::framework::OperatorBase::Run(paddle::framework::Scope const&, paddle::platform::Place const&)
15  paddle::framework::Executor::RunPartialPreparedContext(paddle::framework::ExecutorPrepareContext*, paddle::framework::Scope*, long, long, bool, bool, bool)
16  paddle::framework::Executor::RunPreparedContext(paddle::framework::ExecutorPrepareContext*, paddle::framework::Scope*, bool, bool, bool)
17  paddle::framework::Executor::Run(paddle::framework::ProgramDesc const&, paddle::framework::Scope*, int, bool, bool, std::vector<std::string, std::allocator<std::string> > const&, bool, bool)

----------------------
Error Message Summary:
----------------------
ResourceExhaustedError: 

Out of memory error on GPU 0. Cannot allocate 5.340576GB memory on GPU 0, available memory is only 4.462830GB.

Please check whether there is any other process using GPU 0.
1. If yes, please stop them, or start PaddlePaddle on another GPU.
2. If no, please decrease the batch size of your model. 

 at (/paddle/paddle/fluid/memory/allocation/cuda_allocator.cc:69)
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/executor.py:1070: UserWarning: The following exception is not an EOF exception.
  "The following exception is not an EOF exception.")
Traceback (most recent call last):
  File "predict.py", line 28, in <module>
    fetch_list = fetch_targets)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/executor.py", line 1071, in run
    six.reraise(*sys.exc_info())
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/six.py", line 703, in reraise
    raise value
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/executor.py", line 1066, in run
    return_merged=return_merged)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/executor.py", line 1154, in _run_impl
    use_program_cache=use_program_cache)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/executor.py", line 1229, in _run_program
    fetch_var_name)
RuntimeError: 

--------------------------------------------
C++ Call Stacks (More useful to developers):
--------------------------------------------
0   std::string paddle::platform::GetTraceBackString<std::string>(std::string&&, char const*, int)
1   paddle::memory::allocation::CUDAAllocator::AllocateImpl(unsigned long)
2   paddle::memory::allocation::AlignedAllocator::AllocateImpl(unsigned long)
3   paddle::memory::allocation::AutoGrowthBestFitAllocator::AllocateImpl(unsigned long)
4   paddle::memory::allocation::Allocator::Allocate(unsigned long)
5   paddle::memory::allocation::RetryAllocator::AllocateImpl(unsigned long)
6   paddle::memory::allocation::AllocatorFacade::Alloc(paddle::platform::Place const&, unsigned long)
7   paddle::memory::allocation::AllocatorFacade::AllocShared(paddle::platform::Place const&, unsigned long)
8   paddle::memory::AllocShared(paddle::platform::Place const&, unsigned long)
9   paddle::framework::Tensor::mutable_data(paddle::platform::Place const&, paddle::framework::proto::VarType_Type, unsigned long)
10  paddle::operators::ElementwiseAddKernel<paddle::platform::CUDADeviceContext, float>::Compute(paddle::framework::ExecutionContext const&) const
11  std::_Function_handler<void (paddle::framework::ExecutionContext const&), paddle::framework::OpKernelRegistrarFunctor<paddle::platform::CUDAPlace, false, 0ul, paddle::operators::ElementwiseAddKernel<paddle::platform::CUDADeviceContext, float>, paddle::operators::ElementwiseAddKernel<paddle::platform::CUDADeviceContext, double>, paddle::operators::ElementwiseAddKernel<paddle::platform::CUDADeviceContext, int>, paddle::operators::ElementwiseAddKernel<paddle::platform::CUDADeviceContext, long>, paddle::operators::ElementwiseAddKernel<paddle::platform::CUDADeviceContext, paddle::platform::float16> >::operator()(char const*, char const*, int) const::{lambda(paddle::framework::ExecutionContext const&)#1}>::_M_invoke(std::_Any_data const&, paddle::framework::ExecutionContext const&)
12  paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, paddle::platform::Place const&, paddle::framework::RuntimeContext*) const
13  paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, paddle::platform::Place const&) const
14  paddle::framework::OperatorBase::Run(paddle::framework::Scope const&, paddle::platform::Place const&)
15  paddle::framework::Executor::RunPartialPreparedContext(paddle::framework::ExecutorPrepareContext*, paddle::framework::Scope*, long, long, bool, bool, bool)
16  paddle::framework::Executor::RunPreparedContext(paddle::framework::ExecutorPrepareContext*, paddle::framework::Scope*, bool, bool, bool)
17  paddle::framework::Executor::Run(paddle::framework::ProgramDesc const&, paddle::framework::Scope*, int, bool, bool, std::vector<std::string, std::allocator<std::string> > const&, bool, bool)

----------------------
Error Message Summary:
----------------------
ResourceExhaustedError: 

Out of memory error on GPU 0. Cannot allocate 5.340576GB memory on GPU 0, available memory is only 4.462830GB.

Please check whether there is any other process using GPU 0.
1. If yes, please stop them, or start PaddlePaddle on another GPU.
2. If no, please decrease the batch size of your model. 

 at (/paddle/paddle/fluid/memory/allocation/cuda_allocator.cc:69)
