### ISSUE TITLE
paddledetection/deploy下的c++例子

### ISSUE THREAD

**Issue by JensenHJS** [PaddlePaddle/Paddle#25145]
paddledetection/deploy文件下的c++推理是用cmake来管理c++代码的。在源文件里我想找到使用的某个函数或者某个命名空间在哪里定义的，怎样快速找到定义，类似pycharm中ctrl+b这样的功能。请问你们一般是在什么ide管理cmake的工程的？我在tx2上装了clion，但是无法使用clion的终端，所以感觉并不能真正在clion中运行c++的例子，同样也无法找到某个函数或者类在哪里定义的。

**Comment by JensenHJS** [comment]
现在我可以在clion里通过终端运行deploy/c++例子了，但是比如src/main.cc第一行代码google命名空间的parsecommand函数，快捷键ctrl+b查找函数定义找不到，但如果fgrep查找关键字parsecommand，又出来一大堆。所以有什么办法可以快速找到某个函数在哪里定义的？

**Comment by bjjwwang** [comment]
一般就直接在Linux终端下直接操作的。
Cmake不需要ide管理就可以的。
不过CLion也可以起到辅助作用，可以用Ctrl + Shift + F全局搜索 或者是其他的快捷键，例如搜索Symbol，搜索Class这种。
