### ISSUE TITLE
Cuda error(35), CUDA driver version is insufficient for CUDA runtime version.

### ISSUE THREAD

**Issue by lujinchao** [PaddlePaddle/Paddle#25157]
* python 版本：2.7.13
* paddle版本：1.8.2，pip安装
* cuda版本：9.0.176
* cudnn版本：7.6.5
* nvidia-smi版本：396.26
* 错误信息
> Traceback (most recent call last):
  File "run_sequence_labeling.py", line 375, in <module>
    main(args)
  File "run_sequence_labeling.py", line 58, in main
    dev_list = fluid.cuda_places()
  File "/home/work/lujinchao/ERNIE-2.2.0/python_paddle_gpu/python/lib/python2.7/site-packages/paddle/fluid/framework.py", line 342, in cuda_places
    device_ids = _cuda_ids()
  File "/home/work/lujinchao/ERNIE-2.2.0/python_paddle_gpu/python/lib/python2.7/site-packages/paddle/fluid/framework.py", line 287, in _cuda_ids
    device_ids = six.moves.range(core.get_cuda_device_count())
paddle.fluid.core_avx.EnforceNotMet:

> C++ Call Stacks (More useful to developers):
0   std::string paddle::platform::GetTraceBackString<char const*>(char const*&&, char const*, int)
1   paddle::platform::EnforceNotMet::EnforceNotMet(std::__exception_ptr::exception_ptr, char const*, int)
2   paddle::platform::GetCUDADeviceCount()

> Error Message Summary:
ExternalError:  Cuda error(35), CUDA driver version is insufficient for CUDA runtime version.
  [Advise: This indicates that the installed NVIDIA CUDA driver is older than the CUDA runtime library. This is not a supported configuration.Users should install an updated NVIDIA display driver to allow the application to run.] at (/paddle/paddle/fluid/platform/gpu_info.cc:65)

**Comment by lujinchao** [comment]
python升级到2.7.15之后，还是报错。

**Comment by hong19860320** [comment]
可以尝试使用这个cuda9的whl包  python -m pip install paddlepaddle-gpu==1.8.2.post97 -i https://mirror.baidu.com/pypi/simple

**Comment by lujinchao** [comment]
谢谢，我刚知道post97中9和7原来是代表版本号，换回1.8.2.post97已经不报这个错了。但是，paddle1.6以上貌似跟我用的ernie模型的版本并不兼容，所以我又降回1.5.x了。
