### ISSUE TITLE
第三方云存储的支持

### ISSUE THREAD

**Issue by PayneJoe** [PaddlePaddle/Paddle#25150]
能否添加更多第三方分布式云存储的插件以便于在云端进行数据预处理、模型训练、模型部署推断、监控等全链路打通？同时PP能够扩展到更多市场

如：HDFS（hadoop)、s3/s3a（aws)、OBS（huawei）、OSS（ali）等等

**Comment by guru4elephant** [comment]
您是指能够直接调用云存储的SDK接口进行训练、部署、监控等吗？

**Comment by PayneJoe** [comment]
> 您是指能够直接调用云存储的SDK接口进行训练、部署、监控等吗？

是的，保证PP框架放到任何一个共有云集群（AWS/HUAWEI/ALI）上就能轻松部署，包括分布式训练及serving 

如果在分布式数据IO层面抽象出interface 来也行，让应用开发者自己拓展开发能支持第三方云存储的插件。据了解，DMLC团队在这块做的好像还不错，dmlc-core 代码内部就有抽象的IO接口，之前在此基础上很轻松就开发了能够支持OBS（huawei）的插件

**Comment by guru4elephant** [comment]
好的，我们研究下如何支持，感谢@PayneJoe的建议

**Comment by PayneJoe** [comment]
Looking forward to your progress! 

Best wishes to PP && BAIDU~
