### ISSUE TITLE
CUDA错误，显示CUDA driver version is insufficient for CUDA runtime

### ISSUE THREAD

**Issue by lambert-lan** [PaddlePaddle/Paddle#25153]
1）GPU：Tesla V100 , CUDA版本：9.0.176,  CUDNN版本：7.3.1
2)  Paddlepaddle版本：1.6.0
3）系统环境：CentOS 7.3、Python版本: 3.6.8

docker内离线安装paddle成功后
运行python程序
>>> import paddle.fluid
W0622 14:37:39.086642 36544 init.cc:132] Compiled with WITH_GPU, but no GPU found in runtime.
>>> paddle.fluid.install_check.run_check()
Running Verify Fluid Program ...
WARNING:root:You are using GPU version Paddle Fluid, But Your CUDA Device is not set properly
 Original Error is 0   std::string paddle::platform::GetTraceBackString<char const*>(char const*&&, char const*, int)
1   paddle::platform::EnforceNotMet::EnforceNotMet(std::__exception_ptr::exception_ptr, char const*, int)
2   paddle::platform::GetCUDADeviceCount()
PaddleCheckError: cudaGetDeviceCount failed in paddle::platform::GetCUDADeviceCountImpl, error code : 35, Please see detail in https://docs.nvidia.com/cuda/cuda-runtime-api/group__CUDART__TYPES.html#group__CUDART__TYPES_1g3f51e3575c2178246db0a94a430e0038: CUDA driver version is insufficient for CUDA runtime version at [/paddle/paddle/fluid/platform/gpu_info.cc:67]

***注：  同环境下运行tensorflow和torch检查GPU均无问题

麻烦指教，谢谢

**Comment by hong19860320** [comment]
从错误信息看，docker 内未发现GPU设备，请在确认使用的是nvidia-docker命令，然后进入docker后使用 nvidia-smi 命令看看有没有输出，最后使用export CUDA_VISIBLE_DEVICES="0"后再尝试下

**Comment by lambert-lan** [comment]
> 从错误信息看，docker 内未发现GPU设备，请在确认使用的是nvidia-docker命令，然后进入docker后使用 nvidia-smi 命令看看有没有输出，最后使用export CUDA_VISIBLE_DEVICES="0"后再尝试下

nvidia-smi 显示正常， 使用export CUDA_VISIBLE_DEVICES="0" 报错信息和原来一样..

**Comment by hong19860320** [comment]
> > 从错误信息看，docker 内未发现GPU设备，请在确认使用的是nvidia-docker命令，然后进入docker后使用 nvidia-smi 命令看看有没有输出，最后使用export CUDA_VISIBLE_DEVICES="0"后再尝试下
> 
> nvidia-smi 显示正常， 使用export CUDA_VISIBLE_DEVICES="0" 报错信息和原来一样..

想确认下，nvidia-smi命令是在docker里面打印的吗？能把输出的信息贴下吗？谢谢

**Comment by lambert-lan** [comment]
对的是在docker里面打印的 ，信息如下，而且我在同一个docker下运行tensorflow和torch都没问题，不知道paddle这里是哪里没配好

[root@e9e91e77e67b #####]# nvidia-smi
Mon Jun 22 15:06:17 2020
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 384.81                 Driver Version: 384.81                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla V100-SXM2...  Off  | 00000000:2D:00.0 Off |                    0 |
| N/A   36C    P0    51W / 300W |      0MiB / 16152MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   1  Tesla V100-SXM2...  Off  | 00000000:32:00.0 Off |                    0 |
| N/A   38C    P0    53W / 300W |      0MiB / 16152MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   2  Tesla V100-SXM2...  Off  | 00000000:5B:00.0 Off |                    0 |
| N/A   36C    P0    52W / 300W |      0MiB / 16152MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   3  Tesla V100-SXM2...  Off  | 00000000:5F:00.0 Off |                    0 |
| N/A   34C    P0    51W / 300W |      0MiB / 16152MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+


> > > 从错误信息看，docker 内未发现GPU设备，请在确认使用的是nvidia-docker命令，然后进入docker后使用 nvidia-smi 命令看看有没有输出，最后使用export CUDA_VISIBLE_DEVICES="0"后再尝试下
> > 
> > 
> > nvidia-smi 显示正常， 使用export CUDA_VISIBLE_DEVICES="0" 报错信息和原来一样..
> 
> 想确认下，nvidia-smi命令是在docker里面打印的吗？能把输出的信息贴下吗？谢谢

对的是在docker里面打印的 ，信息如下，而且我在同一个docker下运行tensorflow和torch都没问题，不知道paddle这里是哪里没配好

[root@e9e91e77e67b athena]# nvidia-smi
Mon Jun 22 15:06:17 2020
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 384.81                 Driver Version: 384.81                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla V100-SXM2...  Off  | 00000000:2D:00.0 Off |                    0 |
| N/A   36C    P0    51W / 300W |      0MiB / 16152MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   1  Tesla V100-SXM2...  Off  | 00000000:32:00.0 Off |                    0 |
| N/A   38C    P0    53W / 300W |      0MiB / 16152MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   2  Tesla V100-SXM2...  Off  | 00000000:5B:00.0 Off |                    0 |
| N/A   36C    P0    52W / 300W |      0MiB / 16152MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   3  Tesla V100-SXM2...  Off  | 00000000:5F:00.0 Off |                    0 |
| N/A   34C    P0    51W / 300W |      0MiB / 16152MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+

**Comment by hong19860320** [comment]
你试试paddle1.82 for cuda9的这个whl包哈 python -m pip install paddlepaddle-gpu==1.8.2.post97 -i https://mirror.baidu.com/pypi/simple
