### ISSUE TITLE
在paddlepaddle安裝成功的情況下，本地跑ai studio課程時，GPU版本自動殺死進程

### ISSUE THREAD

**Issue by 451882471** [PaddlePaddle/Paddle#25154]
W0622 15:00:12.455324  5194 device_context.cc:252] Please NOTE: device: 0, CUDA Capability: 50, Driver API Version: 10.1, Runtime API Version: 10.0
W0622 15:00:12.457255  5194 init.cc:216] Warning: PaddlePaddle catches a failure signal, it may not work properly
W0622 15:00:12.457265  5194 init.cc:218] You could check whether you killed PaddlePaddle thread/process accidentally or report the case to PaddlePaddle
W0622 15:00:12.457269  5194 init.cc:221] The detail failure signal is:

W0622 15:00:12.457274  5194 init.cc:224] *** Aborted at 1592809212 (unix time) try "date -d @1592809212" if you are using GNU date ***
W0622 15:00:12.458534  5194 init.cc:224] PC: @                0x0 (unknown)
W0622 15:00:12.458623  5194 init.cc:224] *** SIGSEGV (@0x0) received by PID 5194 (TID 0x7fe6aeb1e740) from PID 0; stack trace: ***
W0622 15:00:12.459789  5194 init.cc:224]     @     0x7fe6ae70c890 (unknown)
W0622 15:00:12.460836  5194 init.cc:224]     @                0x0 (unknown)

**Comment by hong19860320** [comment]
麻烦提供下AI Studio课程地址，paddlepaddle的版本，以及本地GPU的环境（nvidia-smi）

**Comment by 451882471** [comment]
> 麻烦提供下AI Studio课程地址，paddlepaddle的版本，以及本地GPU的环境（nvidia-smi）

课程地址：https://aistudio.baidu.com/aistudio/projectdetail/583818
paddlepaddle版本：paddlepaddle-gpu   1.8.2.post107


+-----------------------------------------------------------------------------+
| NVIDIA-SMI 435.21       Driver Version: 435.21       CUDA Version: 10.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 960M    Off  | 00000000:01:00.0 Off |                  N/A |
| N/A   57C    P0    N/A /  N/A |    475MiB /  2002MiB |     12%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
在網上找不到類似的解決方法，所以就提了這個issue，謝謝！

**Comment by hong19860320** [comment]
> > 麻烦提供下AI Studio课程地址，paddlepaddle的版本，以及本地GPU的环境（nvidia-smi）
> 
> 课程地址：https://aistudio.baidu.com/aistudio/projectdetail/583818
> paddlepaddle版本：paddlepaddle-gpu 1.8.2.post107
> 
> +-----------------------------------------------------------------------------+
> | NVIDIA-SMI 435.21 Driver Version: 435.21 CUDA Version: 10.1 |
> |-------------------------------+----------------------+----------------------+
> | GPU Name Persistence-M| Bus-Id Disp.A | Volatile Uncorr. ECC |
> | Fan Temp Perf Pwr:Usage/Cap| Memory-Usage | GPU-Util Compute M. |
> |===============================+======================+======================|
> | 0 GeForce GTX 960M Off | 00000000:01:00.0 Off | N/A |
> | N/A 57C P0 N/A / N/A | 475MiB / 2002MiB | 12% Default |
> +-------------------------------+----------------------+----------------------+
> 
> 在網上找不到類似的解決方法，所以就提了這個issue，謝謝！

无法访问到项目，提示是私密的，是否提供下AI Studio公开的课程地址。

**Comment by 451882471** [comment]
> > > 麻烦提供下AI Studio课程地址，paddlepaddle的版本，以及本地GPU的环境（nvidia-smi）
> > 
> > 
> > 课程地址：https://aistudio.baidu.com/aistudio/projectdetail/583818
> > paddlepaddle版本：paddlepaddle-gpu 1.8.2.post107
> > +-----------------------------------------------------------------------------+
> > | NVIDIA-SMI 435.21 Driver Version: 435.21 CUDA Version: 10.1 |
> > |-------------------------------+----------------------+----------------------+
> > | GPU Name Persistence-M| Bus-Id Disp.A | Volatile Uncorr. ECC |
> > | Fan Temp Perf Pwr:Usage/Cap| Memory-Usage | GPU-Util Compute M. |
> > |===============================+======================+======================|
> > | 0 GeForce GTX 960M Off | 00000000:01:00.0 Off | N/A |
> > | N/A 57C P0 N/A / N/A | 475MiB / 2002MiB | 12% Default |
> > +-------------------------------+----------------------+----------------------+
> > 在網上找不到類似的解決方法，所以就提了這個issue，謝謝！
> 
> 无法访问到项目，提示是私密的，是否提供下AI Studio公开的课程地址。

地址：https://aistudio.baidu.com/aistudio/education/group/info/1335
項目位置：作業-》大作业：使用DDPG解决四轴飞行器悬浮任务

**Comment by hong19860320** [comment]
感觉是内存问题，之前也有同学遇到这个问题https://github.com/PaddlePaddle/PaddleHub/issues/542#issuecomment-618966889  https://github.com/PaddlePaddle/PaddleHub/issues/699 ，建议重启下环境试试？

**Comment by 451882471** [comment]
> 感觉是内存问题，之前也有同学遇到这个问题[PaddlePaddle/PaddleHub#542 (comment)](https://github.com/PaddlePaddle/PaddleHub/issues/542#issuecomment-618966889) [PaddlePaddle/PaddleHub#699](https://github.com/PaddlePaddle/PaddleHub/issues/699) ，建议重启下环境试试？

感謝答覆！找到原因了，libcudnn軟連接的源文件選擇錯誤導致了這個問題的出現。

**Comment by hong19860320** [comment]
> > 感觉是内存问题，之前也有同学遇到这个问题[PaddlePaddle/PaddleHub#542 (comment)](https://github.com/PaddlePaddle/PaddleHub/issues/542#issuecomment-618966889) [PaddlePaddle/PaddleHub#699](https://github.com/PaddlePaddle/PaddleHub/issues/699) ，建议重启下环境试试？
> 
> 感謝答覆！找到原因了，libcudnn軟連接的源文件選擇錯誤導致了這個問題的出現。

所以还是cudnn版本问题导致的吗？

**Comment by 451882471** [comment]
> > > 感觉是内存问题，之前也有同学遇到这个问题[PaddlePaddle/PaddleHub#542 (comment)](https://github.com/PaddlePaddle/PaddleHub/issues/542#issuecomment-618966889) [PaddlePaddle/PaddleHub#699](https://github.com/PaddlePaddle/PaddleHub/issues/699) ，建议重启下环境试试？
> > 
> > 
> > 感謝答覆！找到原因了，libcudnn軟連接的源文件選擇錯誤導致了這個問題的出現。
> 
> 所以还是cudnn版本问题导致的吗？

不是版本的问题，具体的问题情况和解决方案我都写在这里了[https://blog.csdn.net/qq451882471/article/details/106967942](url)
