### ISSUE TITLE
多卡训练报错

### ISSUE THREAD

**Issue by HaoLiuHust** [PaddlePaddle/Paddle#25168]
![image](https://user-images.githubusercontent.com/7233091/85367127-3ee3f680-b55b-11ea-87ab-8f4c58d7cb1c.png)
![image](https://user-images.githubusercontent.com/7233091/85367143-44d9d780-b55b-11ea-802a-b2fdfcfa3b8c.png)
会报下面的错误：  
![image](https://user-images.githubusercontent.com/7233091/85367168-51f6c680-b55b-11ea-83d2-7c1034671aa2.png)

**Comment by HaoLiuHust** [comment]
训练代码：
```
import paddle.fluid as fluid
from paddleslim.quant import quant_aware
import numpy as np
import paddle.fluid.reader as reader
import os
import cv2
import models.paddle_caffe2.model_with_code.model as paddle_model
import batch_reader
import math
os.environ['CUDA_VISIBLE_DEVICES']="1,2"

class ArcLinear(object):
	def __init__(self,in_size,out_size,s=64):
		self.in_size=in_size
		self.out_size=out_size
		self.s=s
		self.fc7_w=np.load('fc7_weight_init.npy')
		self.fc7_w=self.fc7_w.T
		param_attr=fluid.ParamAttr(name='fc7_weight',initializer=fluid.initializer.NumpyArrayInitializer(self.fc7_w))
		self.weight=fluid.layers.create_parameter([in_size,out_size],"float32",name="weight",attr=param_attr,is_bias=False)
		self.dtype='float32'

	def __call__(self, inputs):
		x=fluid.layers.l2_normalize(inputs,axis=1,name="embedding norm")
		ww=fluid.layers.l2_normalize(self.weight,axis=1,name="weight norm")
		cos_theta=fluid.layers.mul(x,ww)
		return cos_theta*self.s

def where(condition,x,y):
	cond_int=fluid.layers.cast(condition,x.dtype)
	cond_not_int=fluid.layers.cast(fluid.layers.logical_not(condition),x.dtype)
	out1=fluid.layers.elementwise_mul(x,cond_int)
	out2=fluid.layers.elementwise_mul(y,cond_not_int)

	return fluid.layers.elementwise_add(out1,out2)

class ArcLoss(object):
	def __init__(self,class_num=366984,s=64,m=0.5):
		self.class_num=class_num
		self.s=s
		self.m=m

		self.cos_m=math.cos(m)
		self.sin_m=math.sin(m)
		self.mm=self.sin_m*m
		self.threshold=math.cos(math.pi-m)

	def __call__(self, inputs, labels):
		cos_t=inputs/self.s
		cos_t2 = fluid.layers.square(cos_t,name='cos_2')
		# sin_t2=fluid.layers.elementwise_sub(1,cos_t2,name='sin_2')
		sin_t2=1-cos_t2

		sin_t=fluid.layers.sqrt(sin_t2,name='sin_t')
		cos_mt=fluid.layers.elementwise_sub(cos_t*self.cos_m,
		                                    sin_t*self.sin_m,name='cos_mt')*self.s
		cond_v = cos_t - self.threshold
		cond = fluid.layers.cast(fluid.layers.relu(cond_v, name='if_else'), dtype='bool')
		keep_val = self.s * (cos_t - self.mm)
		cos_mt_temp = where(cond, cos_mt, keep_val)
		mask=fluid.layers.one_hot(labels,self.class_num)
		# mask=fluid.layers.squeeze(mask,[1],name='mask')
		inv_mask=1-mask
		s_cos_t=fluid.layers.cast(cos_t*self.s,dtype='float32')
		out_put=fluid.layers.elementwise_add(fluid.layers.elementwise_mul(s_cos_t,inv_mask),
		                                     fluid.layers.elementwise_mul(cos_mt_temp, mask))

		return out_put


train_program=fluid.Program()
startup_program=fluid.Program()
with fluid.program_guard(train_program,startup_program):
	with fluid.unique_name.guard():
		inputs, outputs,labels = paddle_model.x2paddle_net()
		# hidden=fluid.layers.fc(outputs[0],366984,bias_attr=False)
		fc7=ArcLinear(in_size=512,out_size=366984)
		arc_loss=ArcLoss(class_num=366984,m=0.4)
		loss = fluid.layers.softmax_with_cross_entropy(arc_loss(fc7(outputs[0]),labels[0]),labels[0])
		loss=fluid.layers.mean(loss)
		sgd=fluid.optimizer.SGD(learning_rate=0.0001)
		sgd.minimize(loss)

startup_program.random_seed=1
place=fluid.CUDAPlace(1)
exe=fluid.Executor(fluid.CUDAPlace(1))
exe.run(startup_program)

def if_exist(var):
	b = os.path.exists(os.path.join(param_dir, var.name))
	return b

param_dir="models/paddle_caffe2/model_with_code/"
fluid.io.load_vars(exe, param_dir,
                       train_program,
                   predicate=if_exist)

# train_exe=fluid.ParallelExecutor(use_cuda=True,main_program=train_program,loss_name=loss.name)

# fluid.io.load_vars(exe, param_dir,
#                        startup_program,
#                    predicate=if_exist)


py_reader=fluid.io.PyReader(feed_list=[inputs[0],labels[0]],capacity=10)
py_reader.decorate_batch_generator(batch_reader.BatchReader,places=fluid.cuda_places())

compile_prog=fluid.CompiledProgram(train_program).with_data_parallel(loss_name=loss.name)

for data in py_reader():
	loss_val=exe.run(compile_prog,feed=data,fetch_list=[loss])
	print("loss {}".format(loss_val))

```

**Comment by wangchaochaohu** [comment]
这里单卡没有错误 只是多卡有错误吗？ 使用的是哪个版本的Paddle

**Comment by HaoLiuHust** [comment]
单卡可以运行，最新版本的paddle

**Comment by HaoLiuHust** [comment]
1.8.2

**Comment by wangchaochaohu** [comment]
import models.paddle_caffe2.model_with_code.model as paddle_model
这个是哪个库里面的 我复现的时候出错了

**Comment by HaoLiuHust** [comment]
这个是模型文件···，我上传一下吧

**Comment by HaoLiuHust** [comment]
链接：https://pan.baidu.com/s/19Duu9Eim2jJr_4-t4iBv-A 
提取码：4d7w
@wangchaochaohu @zhhsplendid

**Comment by wangchaochaohu** [comment]
> 链接：https://pan.baidu.com/s/19Duu9Eim2jJr_4-t4iBv-A
> 提取码：4d7w
> @wangchaochaohu @zhhsplendid

![image](https://user-images.githubusercontent.com/13411999/85405247-b2edc100-b592-11ea-95c3-b875bc184a69.png)
是直接运行paddle_quan_reproduce.py对吧？

**Comment by HaoLiuHust** [comment]
> > 链接：https://pan.baidu.com/s/19Duu9Eim2jJr_4-t4iBv-A
> > 提取码：4d7w
> > @wangchaochaohu @zhhsplendid
> 
> ![image](https://user-images.githubusercontent.com/13411999/85405247-b2edc100-b592-11ea-95c3-b875bc184a69.png)
> 是直接运行paddle_quan_reproduce.py对吧？

嗯，是的

**Comment by wangchaochaohu** [comment]
![image](https://user-images.githubusercontent.com/13411999/85495943-0d783300-b60e-11ea-9f9a-eb2cbd792b71.png)
我这里还是跑不通

**Comment by HaoLiuHust** [comment]
额，我用pycharm跑可以的，是不是要加入环境变量呢

**Comment by HaoLiuHust** [comment]
> ![image](https://user-images.githubusercontent.com/13411999/85495943-0d783300-b60e-11ea-9f9a-eb2cbd792b71.png)
> 我这里还是跑不通

大佬，复现了吗

**Comment by wangchaochaohu** [comment]
> > ![image](https://user-images.githubusercontent.com/13411999/85495943-0d783300-b60e-11ea-9f9a-eb2cbd792b71.png)
> > 我这里还是跑不通
> 
> 大佬，复现了吗

![image](https://user-images.githubusercontent.com/13411999/85534589-0bc96200-b644-11ea-8cff-118087b9e2ee.png)
这边出现一个问题 

![image](https://user-images.githubusercontent.com/13411999/85534719-269bd680-b644-11ea-89f3-2522711ec1d8.png)
你试试把CUDAPlace(1)改成CUDAPlace(0)是不是可以

**Comment by HaoLiuHust** [comment]
> > > ![image](https://user-images.githubusercontent.com/13411999/85495943-0d783300-b60e-11ea-9f9a-eb2cbd792b71.png)
> > > 我这里还是跑不通
> > 
> > 
> > 大佬，复现了吗
> 
> ![image](https://user-images.githubusercontent.com/13411999/85534589-0bc96200-b644-11ea-8cff-118087b9e2ee.png)
> 这边出现一个问题
> 
> ![image](https://user-images.githubusercontent.com/13411999/85534719-269bd680-b644-11ea-89f3-2522711ec1d8.png)
> 你试试把CUDAPlace(1)改成CUDAPlace(0)是不是可以

![image](https://user-images.githubusercontent.com/7233091/85726641-dcd8ec00-b728-11ea-9c9e-7b53a394cd95.png)
哦哦，不好意思，把载入那个文件的地方改掉，只是个权重初始化，我本地修改了，打包文件没更新...
...

**Comment by HaoLiuHust** [comment]
改成CUDAPlace(0)确实可以了，必须用0号卡么？

**Comment by wangchaochaohu** [comment]
目前实现似乎是这样 因为Paddle 的0卡默认是多卡参数初始化的卡

**Comment by HaoLiuHust** [comment]
好的大佬，那我就用0号卡了。大佬能帮忙看看这个不 https://github.com/PaddlePaddle/Paddle/issues/25136#issuecomment-650570146  @wangchaochaohu
