### ISSUE TITLE
预测库dll符号不完整

### ISSUE THREAD

**Issue by joey12300** [PaddlePaddle/Paddle#25163]
我在开发一个基于windows 1.8.2版本C++预测库的SDK时，编译的时候遇到以下问题。
![image](https://user-images.githubusercontent.com/10826371/85352966-c7519f80-b539-11ea-9b32-3d37984a3a02.png)
之前我自己编译的cpu develop版本的预测库时，编译不会遇到这个问题。我对比了一下我编译出来的paddle_fluid.dll和官方提供的paddle_fluid.dll的函数符号表时，发现有以下的不同：
我编译的dll（函数符号很齐全，没有出现找不到外部符号的报错）：
![image](https://user-images.githubusercontent.com/10826371/85353474-e3097580-b53a-11ea-9e1e-4a8814a798d6.png)

官方提供的dll（仅有一个符号，1.7.1、1.8.1和1.8.2均如此）：
![image](https://user-images.githubusercontent.com/10826371/85353362-9d4cad00-b53a-11ea-91af-d2d193cf2357.png)

麻烦相关同学看看，感谢～

**Comment by jiweibo** [comment]
可以下载官方cpu的库，重新测试下哈。我复现的时候发现gpu下得到的dll符号确实有点奇怪，这个我再看一下

**Comment by zhwesky2010** [comment]
@joey12300 您好，Windows上动态库的编译是最近dev上才支持的功能，没有cherry-pick到1.8分支上去。官网发布的1.8的win预测包，只有静态库可以正常使用的哈，你可以看下大小，如果dll有几百M才是正常的，几M就是没有导出符号的

**Comment by zhwesky2010** [comment]
@joey12300 请问你自行编译的dll是否可用呢

**Comment by joey12300** [comment]
> @joey12300 请问你自行编译的dll是否可用呢

可用的，起码可以通过编译，但是官方提供的dll暂时无法通过编译，原因是找不到符号。

**Comment by zhwesky2010** [comment]
@

> > @joey12300 请问你自行编译的dll是否可用呢
> 
> 可用的，起码可以通过编译，但是官方提供的dll暂时无法通过编译，原因是找不到符号。

嗯对，Windows在1.8上还不支持导出符号，develop上可以正常导出符号

**Comment by joey12300** [comment]
> 可以下载官方cpu的库，重新测试下哈。我复现的时候发现gpu下得到的dll符号确实有点奇怪，这个我再看一下
cpu版本的dll符号表，好像啥都看不到
![image](https://user-images.githubusercontent.com/10826371/85355886-26b2ae00-b540-11ea-9d84-3ccb4bb969c7.png)

**Comment by joey12300** [comment]
> @
> 
> > > @joey12300 请问你自行编译的dll是否可用呢
> > 
> > 
> > 可用的，起码可以通过编译，但是官方提供的dll暂时无法通过编译，原因是找不到符号。
> 
> 嗯对，Windows在1.8上还不支持导出符号，develop上可以正常导出符号

那是否说明目前1.8无法正常使用dll编译，只有develop版本可以用dll正常编译呢？

**Comment by zhwesky2010** [comment]
> > @
> > > > @joey12300 请问你自行编译的dll是否可用呢
> > > 
> > > 
> > > 可用的，起码可以通过编译，但是官方提供的dll暂时无法通过编译，原因是找不到符号。
> > 
> > 
> > 嗯对，Windows在1.8上还不支持导出符号，develop上可以正常导出符号
> 
> 那是否说明目前1.8无法正常使用dll编译，只有develop版本可以用dll正常编译呢？

是的，1.8编出来是空的，没有导出符号。develop版本新增支持win上导出符号的功能
