### ISSUE TITLE
paddle动态图多卡训练报错

### ISSUE THREAD

**Issue by zhangyimi** [PaddlePaddle/Paddle#25166]
paddle1.8.2动态图，多卡，v100, cuda10（这个错误只在多卡下偶然出现）：

Traceback (most recent call last):
  File "run.py", line 231, in <module>
    train(env)
  File "run.py", line 85, in train
    args, model, dev.loader, puncts)
  File "<decorator-gen-81>", line 2, in epoch_evaluate
  File "/home/work/zhangao/ZoooSP/python/miniconda3/envs/zwp/lib/python3.7/site-packages/paddle/fluid/dygraph/base.py", line 277, in __impl__
    return func(*args, **kwargs)
  File "/mnt/zwp/baidu/nlp/dependency-parser/dependency_parser/parser/model.py", line 188, in epoch_evaluate
    metric(arc_preds, rel_preds, arcs, rels, mask)
  File "/mnt/zwp/baidu/nlp/dependency-parser/dependency_parser/parser/utils/metric.py", line 40, in __call__
    arc_mask = nn.masked_select(arc_preds == arc_golds, mask)
  File "/mnt/zwp/baidu/nlp/dependency-parser/dependency_parser/parser/nets/nn.py", line 113, in masked_select
    select = layers.where(mask)
  File "/home/work/zhangao/ZoooSP/python/miniconda3/envs/zwp/lib/python3.7/site-packages/paddle/fluid/layers/nn.py", line 14882, in where
    return core.ops.where_index(condition)
paddle.fluid.core_avx.EnforceNotMet:

--------------------------------------------
C++ Call Stacks (More useful to developers):
--------------------------------------------
0   std::string paddle::platform::GetTraceBackString<char const*>(char const*&&, char const*, int)
1   paddle::platform::EnforceNotMet::EnforceNotMet(std::__exception_ptr::exception_ptr, char const*, int)
2   paddle::platform::GpuMemcpyAsync(void*, void const*, unsigned long, cudaMemcpyKind, CUstream_st*)
3   void paddle::memory::Copy<paddle::platform::CPUPlace, paddle::platform::CUDAPlace>(paddle::platform::CPUPlace, void*, paddle::platform::CUDAPlace, void const*, unsigned long, CUstream_st*)
4   paddle::framework::TensorCopy(paddle::framework::Tensor const&, paddle::platform::Place const&, paddle::platform::DeviceContext const&, paddle::framework::Tensor*)
5   paddle::operators::CUDAWhereIndexKernel<bool>::Compute(paddle::framework::ExecutionContext const&) const
6   std::_Function_handler<void (paddle::framework::ExecutionContext const&), paddle::framework::OpKernelRegistrarFunctor<paddle::platform::CUDAPlace, false, 2ul, paddle::operators::CUDAWhereIndexKernel<long>, paddle::operators::CUDAWhereIndexKernel<int>, paddle::operators::CUDAWhereIndexKernel<bool>, paddle::operators::CUDAWhereIndexKernel<float>, paddle::operators::CUDAWhereIndexKernel<double> >::operator()(char const*, char const*, int) const::{lambda(paddle::framework::ExecutionContext const&)#1}>::_M_invoke(std::_Any_data const&, paddle::framework::ExecutionContext const&)
7   paddle::imperative::PreparedOp::Run(std::map<std::string, std::vector<std::shared_ptr<paddle::imperative::VarBase>, std::allocator<std::shared_ptr<paddle::imperative::VarBase> > >, std::less<std::string>, std::allocator<std::pair<std::string const, std::vector<std::shared_ptr<paddle::imperative::VarBase>, std::allocator<std::shared_ptr<paddle::imperative::VarBase> > > > > > const&, std::map<std::string, std::vector<std::shared_ptr<paddle::imperative::VarBase>, std::allocator<std::shared_ptr<paddle::imperative::VarBase> > >, std::less<std::string>, std::allocator<std::pair<std::string const, std::vector<std::shared_ptr<paddle::imperative::VarBase>, std::allocator<std::shared_ptr<paddle::imperative::VarBase> > > > > > const&, std::unordered_map<std::string, boost::variant<boost::blank, int, float, std::string, std::vector<int, std::allocator<int> >, std::vector<float, std::allocator<float> >, std::vector<std::string, std::allocator<std::string> >, bool, std::vector<bool, std::allocator<bool> >, paddle::framework::BlockDesc*, long, std::vector<paddle::framework::BlockDesc*, std::allocator<paddle::framework::BlockDesc*> >, std::vector<long, std::allocator<long> >, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_>, std::hash<std::string>, std::equal_to<std::string>, std::allocator<std::pair<std::string const, boost::variant<boost::blank, int, float, std::string, std::vector<int, std::allocator<int> >, std::vector<float, std::allocator<float> >, std::vector<std::string, std::allocator<std::string> >, bool, std::vector<bool, std::allocator<bool> >, paddle::framework::BlockDesc*, long, std::vector<paddle::framework::BlockDesc*, std::allocator<paddle::framework::BlockDesc*> >, std::vector<long, std::allocator<long> >, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> > > > const&)
8   paddle::imperative::OpBase::Run(paddle::framework::OperatorBase const&, std::map<std::string, std::vector<std::shared_ptr<paddle::imperative::VarBase>, std::allocator<std::shared_ptr<paddle::imperative::VarBase> > >, std::less<std::string>, std::allocator<std::pair<std::string const, std::vector<std::shared_ptr<paddle::imperative::VarBase>, std::allocator<std::shared_ptr<paddle::imperative::VarBase> > > > > > const&, std::map<std::string, std::vector<std::shared_ptr<paddle::imperative::VarBase>, std::allocator<std::shared_ptr<paddle::imperative::VarBase> > >, std::less<std::string>, std::allocator<std::pair<std::string const, std::vector<std::shared_ptr<paddle::imperative::VarBase>, std::allocator<std::shared_ptr<paddle::imperative::VarBase> > > > > > const&, std::unordered_map<std::string, boost::variant<boost::blank, int, float, std::string, std::vector<int, std::allocator<int> >, std::vector<float, std::allocator<float> >, std::vector<std::string, std::allocator<std::string> >, bool, std::vector<bool, std::allocator<bool> >, paddle::framework::BlockDesc*, long, std::vector<paddle::framework::BlockDesc*, std::allocator<paddle::framework::BlockDesc*> >, std::vector<long, std::allocator<long> >, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_>, std::hash<std::string>, std::equal_to<std::string>, std::allocator<std::pair<std::string const, boost::variant<boost::blank, int, float, std::string, std::vector<int, std::allocator<int> >, std::vector<float, std::allocator<float> >, std::vector<std::string, std::allocator<std::string> >, bool, std::vector<bool, std::allocator<bool> >, paddle::framework::BlockDesc*, long, std::vector<paddle::framework::BlockDesc*, std::allocator<paddle::framework::BlockDesc*> >, std::vector<long, std::allocator<long> >, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> > > > const&, paddle::platform::Place const&)
9   paddle::imperative::Tracer::TraceOp(std::string const&, std::map<std::string, std::vector<std::shared_ptr<paddle::imperative::VarBase>, std::allocator<std::shared_ptr<paddle::imperative::VarBase> > >, std::less<std::string>, std::allocator<std::pair<std::string const, std::vector<std::shared_ptr<paddle::imperative::VarBase>, std::allocator<std::shared_ptr<paddle::imperative::VarBase> > > > > > const&, std::map<std::string, std::vector<std::shared_ptr<paddle::imperative::VarBase>, std::allocator<std::shared_ptr<paddle::imperative::VarBase> > >, std::less<std::string>, std::allocator<std::pair<std::string const, std::vector<std::shared_ptr<paddle::imperative::VarBase>, std::allocator<std::shared_ptr<paddle::imperative::VarBase> > > > > > const&, std::unordered_map<std::string, boost::variant<boost::blank, int, float, std::string, std::vector<int, std::allocator<int> >, std::vector<float, std::allocator<float> >, std::vector<std::string, std::allocator<std::string> >, bool, std::vector<bool, std::allocator<bool> >, paddle::framework::BlockDesc*, long, std::vector<paddle::framework::BlockDesc*, std::allocator<paddle::framework::BlockDesc*> >, std::vector<long, std::allocator<long> >, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_>, std::hash<std::string>, std::equal_to<std::string>, std::allocator<std::pair<std::string const, boost::variant<boost::blank, int, float, std::string, std::vector<int, std::allocator<int> >, std::vector<float, std::allocator<float> >, std::vector<std::string, std::allocator<std::string> >, bool, std::vector<bool, std::allocator<bool> >, paddle::framework::BlockDesc*, long, std::vector<paddle::framework::BlockDesc*, std::allocator<paddle::framework::BlockDesc*> >, std::vector<long, std::allocator<long> >, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> > > >, paddle::platform::Place const&, bool)
10  paddle::imperative::Tracer::TraceOp(std::string const&, std::map<std::string, std::vector<std::shared_ptr<paddle::imperative::VarBase>, std::allocator<std::shared_ptr<paddle::imperative::VarBase> > >, std::less<std::string>, std::allocator<std::pair<std::string const, std::vector<std::shared_ptr<paddle::imperative::VarBase>, std::allocator<std::shared_ptr<paddle::imperative::VarBase> > > > > > const&, std::map<std::string, std::vector<std::shared_ptr<paddle::imperative::VarBase>, std::allocator<std::shared_ptr<paddle::imperative::VarBase> > >, std::less<std::string>, std::allocator<std::pair<std::string const, std::vector<std::shared_ptr<paddle::imperative::VarBase>, std::allocator<std::shared_ptr<paddle::imperative::VarBase> > > > > > const&, std::unordered_map<std::string, boost::variant<boost::blank, int, float, std::string, std::vector<int, std::allocator<int> >, std::vector<float, std::allocator<float> >, std::vector<std::string, std::allocator<std::string> >, bool, std::vector<bool, std::allocator<bool> >, paddle::framework::BlockDesc*, long, std::vector<paddle::framework::BlockDesc*, std::allocator<paddle::framework::BlockDesc*> >, std::vector<long, std::allocator<long> >, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_>, std::hash<std::string>, std::equal_to<std::string>, std::allocator<std::pair<std::string const, boost::variant<boost::blank, int, float, std::string, std::vector<int, std::allocator<int> >, std::vector<float, std::allocator<float> >, std::vector<std::string, std::allocator<std::string> >, bool, std::vector<bool, std::allocator<bool> >, paddle::framework::BlockDesc*, long, std::vector<paddle::framework::BlockDesc*, std::allocator<paddle::framework::BlockDesc*> >, std::vector<long, std::allocator<long> >, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> > > >)

----------------------
Error Message Summary:
----------------------
ExternalError:  Cuda error(77), an illegal memory access was encountered.
  [Advise: The device encountered a load or store instruction on an invalid memory address. This leaves the process in an inconsistentstate and any further CUDA work will return the same error. To continue using CUDA, the process must be terminated and relaunched. ] at (/paddle/paddle/fluid/platform/gpu_info.cc:276)

W0622 23:38:30.834911 27884 init.cc:216] Warning: PaddlePaddle catches a failure signal, it may not work properly
W0622 23:38:30.834987 27884 init.cc:218] You could check whether you killed PaddlePaddle thread/process accidentally or report the case to PaddlePaddle
W0622 23:38:30.834993 27884 init.cc:221] The detail failure signal is:

W0622 23:38:30.835000 27884 init.cc:224] *** Aborted at 1592840310 (unix time) try "date -d @1592840310" if you are using GNU date ***
W0622 23:38:30.836608 27884 init.cc:224] PC: @                0x0 (unknown)
W0622 23:38:30.836721 27884 init.cc:224] *** SIGSEGV (@0x8) received by PID 27884 (TID 0x7f69e8c4b740) from PID 8; stack trace: ***
W0622 23:38:30.837846 27884 init.cc:224]     @     0x7f69e882f5d0 (unknown)
W0622 23:38:30.842507 27884 init.cc:224]     @     0x7f699926182f paddle::platform::proto::cudaerrorDesc::ByteSizeLong()
W0622 23:38:30.845558 27884 init.cc:224]     @     0x7f6995bf2722 paddle::platform::build_nvidia_error_msg()
W0622 23:38:30.847239 27884 init.cc:224]     @     0x7f69991e7fbf _ZNSt17_Function_handlerIFvP11CUstream_stEZN6paddle8platform22CudaStreamResourcePoolC1EvEUlS1_E0_E9_M_invokeERKSt9_Any_dataS1_
W0622 23:38:30.849206 27884 init.cc:224]     @     0x7f69991e86e3 std::_Sp_counted_ptr<>::_M_dispose()
W0622 23:38:30.851056 27884 init.cc:224]     @     0x7f69991e8bcc paddle::platform::CudaStreamResourcePool::~CudaStreamResourcePool()
W0622 23:38:30.852480 27884 init.cc:224]     @     0x7f69e848cc29 __run_exit_handlers
W0622 23:38:30.853693 27884 init.cc:224]     @     0x7f69e848cc77 __GI_exit
W0622 23:38:30.854863 27884 init.cc:224]     @     0x7f69e847549c __libc_start_main
W0622 23:38:30.855252 27884 init.cc:224]     @     0x55beeba103c0 (unknown)
ERROR 2020-06-22 23:40:35,093 utils.py:422] ABORT!!! Out of all 2 trainers, the trainer process with rank=[0] was aborted. Please check its log.
Traceback (most recent call last):
  File "/home/work/zhangao/ZoooSP/python/miniconda3/envs/zwp/lib/python3.7/site-packages/paddle/distributed/utils.py", line 406, in watch_local_trainers
    terminate_local_procs(procs)
  File "/home/work/zhangao/ZoooSP/python/miniconda3/envs/zwp/lib/python3.7/site-packages/paddle/distributed/utils.py", line 257, in terminate_local_procs
    p.proc.join(timeout=1)
AttributeError: 'Popen' object has no attribute 'join'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/work/zhangao/ZoooSP/python/miniconda3/envs/zwp/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/work/zhangao/ZoooSP/python/miniconda3/envs/zwp/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/work/zhangao/ZoooSP/python/miniconda3/envs/zwp/lib/python3.7/site-packages/paddle/distributed/launch.py", line 237, in <module>
    launch(args)
  File "/home/work/zhangao/ZoooSP/python/miniconda3/envs/zwp/lib/python3.7/site-packages/paddle/distributed/launch.py", line 220, in launch
    alive = watch_local_trainers(procs, cluster.trainers_nranks())
  File "/home/work/zhangao/ZoooSP/python/miniconda3/envs/zwp/lib/python3.7/site-packages/paddle/distributed/utils.py", line 423, in watch_local_trainers
    terminate_local_procs(procs)
  File "/home/work/zhangao/ZoooSP/python/miniconda3/envs/zwp/lib/python3.7/site-packages/paddle/distributed/utils.py", line 257, in terminate_local_procs
    p.proc.join(timeout=1)
AttributeError: 'Popen' object has no attribute 'join'

**Comment by wangchaochaohu** [comment]
能大概贴一下代码吗？做个简答描述

**Comment by zhangyimi** [comment]
def masked_select(input, mask):
        select = layers.where(mask)
        output = layers.gather_nd(input, select)
        return output

这个函数报的错，mask肯定是bool类型的:


tmp_words = layers.pad(words[:, 1:], paddings=[0, 0, 1, 0], pad_value=args.pad_index)
mask = tmp_words != args.pad_index

**Comment by zhiqiu** [comment]
hi，根据报错信息应该是多卡训练进程join出错了，
> AttributeError: 'Popen' object has no attribute 'join'

你可以试试 PR #24767 是否可以解决你的问题。

**Comment by zhangyimi** [comment]
> hi，根据报错信息应该是多卡训练进程join出错了，
> 
> > AttributeError: 'Popen' object has no attribute 'join'
> 
> 你可以试试 PR #24767 是否可以解决你的问题。

好的，这个会在1.8.3中修复么

**Comment by zhiqiu** [comment]
> > hi，根据报错信息应该是多卡训练进程join出错了，
> > > AttributeError: 'Popen' object has no attribute 'join'
> > 
> > 
> > 你可以试试 PR #24767 是否可以解决你的问题。
> 
> 好的，这个会在1.8.3中修复么

应该会的。

**Comment by zhangyimi** [comment]
单卡下碰到同样的问题

Traceback (most recent call last):
  File "run.py", line 249, in <module>
    train(env)
  File "run.py", line 101, in train
    puncts)
  File "<decorator-gen-81>", line 2, in epoch_evaluate
  File "/home/work/zhangao/ZoooSP/python/miniconda3/envs/zwp/lib/python3.7/site-packages/paddle/fluid/dygraph/base.py", line 277, in __impl__
    return func(*args, **kwargs)
  File "/mnt/zwp/0623/baidu/nlp/dependency-parser/dependency_parser/parser/model.py", line 213, in epoch_evaluate
    metric(arc_preds, rel_preds, arcs, rels, mask)
  File "/mnt/zwp/0623/baidu/nlp/dependency-parser/dependency_parser/parser/utils/metric.py", line 43, in __call__
    arc_mask = nn.masked_select(arc_preds == arc_golds, mask)
  File "/mnt/zwp/0623/baidu/nlp/dependency-parser/dependency_parser/parser/nets/nn.py", line 159, in masked_select
    select = layers.where(mask)
  File "/home/work/zhangao/ZoooSP/python/miniconda3/envs/zwp/lib/python3.7/site-packages/paddle/fluid/layers/nn.py", line 14882, in where
    return core.ops.where_index(condition)
paddle.fluid.core_avx.EnforceNotMet: 

--------------------------------------------
C++ Call Stacks (More useful to developers):
--------------------------------------------
0   std::string paddle::platform::GetTraceBackString<char const*>(char const*&&, char const*, int)
1   paddle::platform::EnforceNotMet::EnforceNotMet(std::__exception_ptr::exception_ptr, char const*, int)
2   paddle::platform::GpuMemcpyAsync(void*, void const*, unsigned long, cudaMemcpyKind, CUstream_st*)
3   void paddle::memory::Copy<paddle::platform::CPUPlace, paddle::platform::CUDAPlace>(paddle::platform::CPUPlace, void*, paddle::platform::CUDAPlace, void const*, unsigned long, CUstream_st*)
4   paddle::framework::TensorCopy(paddle::framework::Tensor const&, paddle::platform::Place const&, paddle::platform::DeviceContext const&, paddle::framework::Tensor*)
5   paddle::operators::CUDAWhereIndexKernel<bool>::Compute(paddle::framework::ExecutionContext const&) const
6   std::_Function_handler<void (paddle::framework::ExecutionContext const&), paddle::framework::OpKernelRegistrarFunctor<paddle::platform::CUDAPlace, false, 2ul, paddle::operators::CUDAWhereIndexKernel<long>, paddle::operators::CUDAWhereIndexKernel<int>, paddle::operators::CUDAWhereIndexKernel<bool>, paddle::operators::CUDAWhereIndexKernel<float>, paddle::operators::CUDAWhereIndexKernel<double> >::operator()(char const*, char const*, int) const::{lambda(paddle::framework::ExecutionContext const&)#1}>::_M_invoke(std::_Any_data const&, paddle::framework::ExecutionContext const&)
7   paddle::imperative::PreparedOp::Run(std::map<std::string, std::vector<std::shared_ptr<paddle::imperative::VarBase>, std::allocator<std::shared_ptr<paddle::imperative::VarBase> > >, std::less<std::string>, std::allocator<std::pair<std::string const, std::vector<std::shared_ptr<paddle::imperative::VarBase>, std::allocator<std::shared_ptr<paddle::imperative::VarBase> > > > > > const&, std::map<std::string, std::vector<std::shared_ptr<paddle::imperative::VarBase>, std::allocator<std::shared_ptr<paddle::imperative::VarBase> > >, std::less<std::string>, std::allocator<std::pair<std::string const, std::vector<std::shared_ptr<paddle::imperative::VarBase>, std::allocator<std::shared_ptr<paddle::imperative::VarBase> > > > > > const&, std::unordered_map<std::string, boost::variant<boost::blank, int, float, std::string, std::vector<int, std::allocator<int> >, std::vector<float, std::allocator<float> >, std::vector<std::string, std::allocator<std::string> >, bool, std::vector<bool, std::allocator<bool> >, paddle::framework::BlockDesc*, long, std::vector<paddle::framework::BlockDesc*, std::allocator<paddle::framework::BlockDesc*> >, std::vector<long, std::allocator<long> >, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_>, std::hash<std::string>, std::equal_to<std::string>, std::allocator<std::pair<std::string const, boost::variant<boost::blank, int, float, std::string, std::vector<int, std::allocator<int> >, std::vector<float, std::allocator<float> >, std::vector<std::string, std::allocator<std::string> >, bool, std::vector<bool, std::allocator<bool> >, paddle::framework::BlockDesc*, long, std::vector<paddle::framework::BlockDesc*, std::allocator<paddle::framework::BlockDesc*> >, std::vector<long, std::allocator<long> >, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> > > > const&)
8   paddle::imperative::OpBase::Run(paddle::framework::OperatorBase const&, std::map<std::string, std::vector<std::shared_ptr<paddle::imperative::VarBase>, std::allocator<std::shared_ptr<paddle::imperative::VarBase> > >, std::less<std::string>, std::allocator<std::pair<std::string const, std::vector<std::shared_ptr<paddle::imperative::VarBase>, std::allocator<std::shared_ptr<paddle::imperative::VarBase> > > > > > const&, std::map<std::string, std::vector<std::shared_ptr<paddle::imperative::VarBase>, std::allocator<std::shared_ptr<paddle::imperative::VarBase> > >, std::less<std::string>, std::allocator<std::pair<std::string const, std::vector<std::shared_ptr<paddle::imperative::VarBase>, std::allocator<std::shared_ptr<paddle::imperative::VarBase> > > > > > const&, std::unordered_map<std::string, boost::variant<boost::blank, int, float, std::string, std::vector<int, std::allocator<int> >, std::vector<float, std::allocator<float> >, std::vector<std::string, std::allocator<std::string> >, bool, std::vector<bool, std::allocator<bool> >, paddle::framework::BlockDesc*, long, std::vector<paddle::framework::BlockDesc*, std::allocator<paddle::framework::BlockDesc*> >, std::vector<long, std::allocator<long> >, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_>, std::hash<std::string>, std::equal_to<std::string>, std::allocator<std::pair<std::string const, boost::variant<boost::blank, int, float, std::string, std::vector<int, std::allocator<int> >, std::vector<float, std::allocator<float> >, std::vector<std::string, std::allocator<std::string> >, bool, std::vector<bool, std::allocator<bool> >, paddle::framework::BlockDesc*, long, std::vector<paddle::framework::BlockDesc*, std::allocator<paddle::framework::BlockDesc*> >, std::vector<long, std::allocator<long> >, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> > > > const&, paddle::platform::Place const&)
9   paddle::imperative::Tracer::TraceOp(std::string const&, std::map<std::string, std::vector<std::shared_ptr<paddle::imperative::VarBase>, std::allocator<std::shared_ptr<paddle::imperative::VarBase> > >, std::less<std::string>, std::allocator<std::pair<std::string const, std::vector<std::shared_ptr<paddle::imperative::VarBase>, std::allocator<std::shared_ptr<paddle::imperative::VarBase> > > > > > const&, std::map<std::string, std::vector<std::shared_ptr<paddle::imperative::VarBase>, std::allocator<std::shared_ptr<paddle::imperative::VarBase> > >, std::less<std::string>, std::allocator<std::pair<std::string const, std::vector<std::shared_ptr<paddle::imperative::VarBase>, std::allocator<std::shared_ptr<paddle::imperative::VarBase> > > > > > const&, std::unordered_map<std::string, boost::variant<boost::blank, int, float, std::string, std::vector<int, std::allocator<int> >, std::vector<float, std::allocator<float> >, std::vector<std::string, std::allocator<std::string> >, bool, std::vector<bool, std::allocator<bool> >, paddle::framework::BlockDesc*, long, std::vector<paddle::framework::BlockDesc*, std::allocator<paddle::framework::BlockDesc*> >, std::vector<long, std::allocator<long> >, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_>, std::hash<std::string>, std::equal_to<std::string>, std::allocator<std::pair<std::string const, boost::variant<boost::blank, int, float, std::string, std::vector<int, std::allocator<int> >, std::vector<float, std::allocator<float> >, std::vector<std::string, std::allocator<std::string> >, bool, std::vector<bool, std::allocator<bool> >, paddle::framework::BlockDesc*, long, std::vector<paddle::framework::BlockDesc*, std::allocator<paddle::framework::BlockDesc*> >, std::vector<long, std::allocator<long> >, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> > > >, paddle::platform::Place const&, bool)
10  paddle::imperative::Tracer::TraceOp(std::string const&, std::map<std::string, std::vector<std::shared_ptr<paddle::imperative::VarBase>, std::allocator<std::shared_ptr<paddle::imperative::VarBase> > >, std::less<std::string>, std::allocator<std::pair<std::string const, std::vector<std::shared_ptr<paddle::imperative::VarBase>, std::allocator<std::shared_ptr<paddle::imperative::VarBase> > > > > > const&, std::map<std::string, std::vector<std::shared_ptr<paddle::imperative::VarBase>, std::allocator<std::shared_ptr<paddle::imperative::VarBase> > >, std::less<std::string>, std::allocator<std::pair<std::string const, std::vector<std::shared_ptr<paddle::imperative::VarBase>, std::allocator<std::shared_ptr<paddle::imperative::VarBase> > > > > > const&, std::unordered_map<std::string, boost::variant<boost::blank, int, float, std::string, std::vector<int, std::allocator<int> >, std::vector<float, std::allocator<float> >, std::vector<std::string, std::allocator<std::string> >, bool, std::vector<bool, std::allocator<bool> >, paddle::framework::BlockDesc*, long, std::vector<paddle::framework::BlockDesc*, std::allocator<paddle::framework::BlockDesc*> >, std::vector<long, std::allocator<long> >, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_>, std::hash<std::string>, std::equal_to<std::string>, std::allocator<std::pair<std::string const, boost::variant<boost::blank, int, float, std::string, std::vector<int, std::allocator<int> >, std::vector<float, std::allocator<float> >, std::vector<std::string, std::allocator<std::string> >, bool, std::vector<bool, std::allocator<bool> >, paddle::framework::BlockDesc*, long, std::vector<paddle::framework::BlockDesc*, std::allocator<paddle::framework::BlockDesc*> >, std::vector<long, std::allocator<long> >, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> > > >)

----------------------
Error Message Summary:
----------------------
ExternalError:  Cuda error(77), an illegal memory access was encountered.
  [Advise: The device encountered a load or store instruction on an invalid memory address. This leaves the process in an inconsistentstate and any further CUDA work will return the same error. To continue using CUDA, the process must be terminated and relaunched. ] at (/paddle/paddle/fluid/platform/gpu_info.cc:276)

W0628 00:46:37.419998 20601 init.cc:216] Warning: PaddlePaddle catches a failure signal, it may not work properly
W0628 00:46:37.420078 20601 init.cc:218] You could check whether you killed PaddlePaddle thread/process accidentally or report the case to PaddlePaddle
W0628 00:46:37.420094 20601 init.cc:221] The detail failure signal is:

W0628 00:46:37.420101 20601 init.cc:224] *** Aborted at 1593276397 (unix time) try "date -d @1593276397" if you are using GNU date ***
W0628 00:46:37.421769 20601 init.cc:224] PC: @                0x0 (unknown)
W0628 00:46:37.421870 20601 init.cc:224] *** SIGSEGV (@0x8) received by PID 20601 (TID 0x7f485a397740) from PID 8; stack trace: ***
W0628 00:46:37.423175 20601 init.cc:224]     @     0x7f4859f7b5d0 (unknown)
W0628 00:46:37.427018 20601 init.cc:224]     @     0x7f46d6d4e82f paddle::platform::proto::cudaerrorDesc::ByteSizeLong()
W0628 00:46:37.429356 20601 init.cc:224]     @     0x7f46d36df722 paddle::platform::build_nvidia_error_msg()
W0628 00:46:37.430402 20601 init.cc:224]     @     0x7f46d6cd4fbf _ZNSt17_Function_handlerIFvP11CUstream_stEZN6paddle8platform22CudaStreamResourcePoolC1EvEUlS1_E0_E9_M_invokeERKSt9_Any_dataS1_
W0628 00:46:37.431753 20601 init.cc:224]     @     0x7f46d6cd56e3 std::_Sp_counted_ptr<>::_M_dispose()
W0628 00:46:37.433069 20601 init.cc:224]     @     0x7f46d6cd5bcc paddle::platform::CudaStreamResourcePool::~CudaStreamResourcePool()
W0628 00:46:37.434511 20601 init.cc:224]     @     0x7f4859bd8c29 __run_exit_handlers
W0628 00:46:37.435712 20601 init.cc:224]     @     0x7f4859bd8c77 __GI_exit
W0628 00:46:37.436900 20601 init.cc:224]     @     0x7f4859bc149c __libc_start_main
W0628 00:46:37.437292 20601 init.cc:224]     @     0x55dd973e23c0 (unknown)
run_train.sh: 行 21: 20601 段错误               (吐核)python -u run.py --mode=train --use_cuda --feat=char --preprocess --output_dir=exp/baidu --train_data_path=data/baidu/train.txt --valid_data_path=data/baidu/test.txt --test_data_path=data/baidu/test.txt --pretrained_embedding_dir=data/cc.zh.300.vec --unk=UNK --buckets=15

**Comment by DDDivano** [comment]
可以把mask打印出来吗？类型和值
