### ISSUE TITLE
onnx2paddle转换时报错

### ISSUE THREAD

**Issue by whjdark** [PaddlePaddle/Paddle#25162]
yolo V5（pytorch）onnx转paddle时报错。

assert out_shape, 'neither scales nor output shape is available'
AssertionError: neither scales nor output shape is available

是因为有些操作不支持转吗？

**Comment by Channingss** [comment]
可以试试这个pr：https://github.com/PaddlePaddle/X2Paddle/pull/273
paddle安装1.8以上
