### ISSUE TITLE
关于bool类型的使用问题

### ISSUE THREAD

**Issue by zhangyimi** [PaddlePaddle/Paddle#25170]
paddle1.8.2动态图:
最近在使用paddle的过程中发现bool类型很多操作都不支持（如: unsqueeze, squeeze, concat, reduce_sum等等），在使用中都需要在外面在包一层函数，并且像一些mask_fill, mask_select常用函数都不支持，使用起来非常不方便。
下面是我在使用过程中与bool类型相关自己包装的一些函数：
![image](https://user-images.githubusercontent.com/20926735/85370639-96856080-b561-11ea-8f0d-4ef06fbd13ab.png)
![image](https://user-images.githubusercontent.com/20926735/85370672-a309b900-b561-11ea-8068-ab3888eeccc7.png)
![image](https://user-images.githubusercontent.com/20926735/85370685-aac95d80-b561-11ea-8f5c-cf8c9d59dcb2.png)

希望至少像concat，unsqueeze这些常用操作可以支持

**Comment by wangchaochaohu** [comment]
后续会反馈添加相应的支持 谢谢建议
