### ISSUE TITLE
没有addle.fluid.dygraph.Dropout这个类

### ISSUE THREAD

**Issue by zhao181** [PaddlePaddle/Paddle#25183]
paddle的文档上有介绍这个类  但是安装的paddle里面没有这个类     自己包装好麻烦 尤其涉及到train和eval模式切换的时候

**Comment by chenwhql** [comment]
请问您使用的是哪个版本的paddle？方便把示例code和报错贴一下吗？

**Comment by zhao181** [comment]
我的版本是1.7.2
import paddle
paddle.__version__
Out[7]: '1.7.2'

from paddle import fluid
dropout1=fluid.dygraph.Dropout(p=0.1,is_test=False)
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 2963, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-5-89c46330c68f>", line 1, in <module>
    dropout1=fluid.dygraph.Dropout(p=0.1,is_test=False)
AttributeError: module 'paddle.fluid.dygraph' has no attribute 'Dropout'

**Comment by chenwhql** [comment]
1.7.2的时候还没有这个类，您看的是1.8的文档，如果您要使用这个接口的话，建议升级到1.8的paddle
