### ISSUE TITLE
Paddle 1.7/1.8 是否还需要 fluid.program_guard，fluid.unique_name.guard

### ISSUE THREAD

**Issue by OleNet** [PaddlePaddle/Paddle#25181]
在 已有的paddle项目中，还能看到组网的时候，需要 fluid.program_guard 和 fluid.unique_name.guard语句，如[这里](https://github.com/PaddlePaddle/ERNIE/blob/repro/ernie-gen/run_seq2seq.py#L120)
但是我看最新的Paddle文档中的各种示例，已经不用这个guard了, 例如[这里](https://www.paddlepaddle.org.cn/documentation/docs/zh/api_cn/fluid_cn/data_cn.html#data)

所以问题：
1. 现在写paddle，还需不需要fluid.program_guard，fluid.unique_name.guard
2. 如果需要写，什么时候需要？

**Comment by wangchaochaohu** [comment]
在静态图的时候还是需要写的
