### ISSUE TITLE
windows源码编译

### ISSUE THREAD

**Issue by GLaStu** [PaddlePaddle/Paddle#25187]
windows源码编译时，生成paddle工程后，使用Blend for Visual Studio 2015 打开 paddle.sln 文件，选择平台为 x64，配置为 Release，开始编译。编译开始后会卡在某个工程一直不动。请问是什么原因？怀疑是cmake生成时造成的问题，是否需要修改cmake的配置项？

**Comment by zhwesky2010** [comment]
@GLaStu  您好，请问hang住的位置是哪里，是external project吗？麻烦截个图看下，电脑配置怎么样呢

**Comment by zhwesky2010** [comment]
@GLaStu 可以先把hang住的那个vcxporj单独编译下试试

**Comment by GLaStu** [comment]
电脑配置是内存：16G，显卡：quardo P5000,工作站。配置应该没有问题。卡住的工程是：
![image](https://user-images.githubusercontent.com/20152953/85641968-a6688600-b6c2-11ea-934a-f92e501c53c5.png)

**Comment by GLaStu** [comment]
在这个工程中一直没有反应了

**Comment by GLaStu** [comment]
单独编译这个工程后，依旧在这个地方卡住。

**Comment by GLaStu** [comment]
已经解决了这个问题，原因是VS安装路径有中文。

**Comment by chenwhql** [comment]
> 已经解决了这个问题，原因是VS安装路径有中文。

@GLaStu 请问您还有其他问题吗，可以关闭这个issue了吗

**Comment by zhwesky2010** [comment]
@GLaStu hi，您好，想请问一下 quardo P5000这张GPU的运行速度怎么样？和其他显卡相比呢
