### ISSUE TITLE
动态图中如何自定义反向传播中梯度的变换？

### ISSUE THREAD

**Issue by HighCWu** [PaddlePaddle/Paddle#25198]
- 版本、环境信息：
    1）PaddlePaddle版本：1.8.0
- 问题描述：如何在动态图中自定义一个操作或层的反向传播过程？

静态图中有py_func可以自定义，不过主要功能是自定义op，看源码支持动态图也是在TODO状态。

这种过程应该对标PyTorch中的autograd.Function。

在讨论群中听闻动态图有专门的实现，而不是py_func，发言者暂时想不起API了。

这个功能使操作可微或者实现如revnet中的显存节省。

希望了解对应API，谢谢。

**Comment by chenwhql** [comment]
您好，目前在动态图下实现这个功能也需要自定义C++ op实现，文档可以参考：https://www.paddlepaddle.org.cn/documentation/docs/zh/advanced_guide/addon_development/new_op/custom_op.html

至于类似PyTorch中的autograd.Function的功能，已经在计划中了，人力问题，暂时没有排期，后续会添加的，抱歉

**Comment by HighCWu** [comment]
明白了，期待飞桨的功能更加丰富。

**Comment by dongfangyixi** [comment]
请问现在添加这个功能了吗？
