### ISSUE TITLE
浮点数向量序列和栈式lstm例子匹配出错

### ISSUE THREAD

**Issue by jeromeJT** [PaddlePaddle/Paddle#2519]
@lcy-seso @reyoung 在直接使用dense_vector_sequece接一个fc，再接lstm这样的浅层网络可以正常运行
尝试使用paddlebook中语义角色标注例子中的栈式lstm实现深层网络失败，麻烦帮看一下是哪里出问题了，谢谢~
配置：[train.py.txt](https://github.com/PaddlePaddle/Paddle/files/1087204/train.py.txt)

错误信息：
I0620 14:29:36.920446 25470 GradientMachine.cpp:85] Initing parameters..
I0620 14:29:36.941530 25470 GradientMachine.cpp:92] Init parameters done.
F0620 14:29:37.149533 25490 Matrix.cpp:3275] Check failed: label.getSize() == numSamples (50 vs. 3050) 
*** Check failure stack trace: ***
    @     0x7f3fc48a762d  google::LogMessage::Fail()
    @     0x7f3fc48ab0dc  google::LogMessage::SendToLog()
    @     0x7f3fc48a7153  google::LogMessage::Flush()
    @     0x7f3fc48ac5ee  google::LogMessageFatal::~LogMessageFatal()
F0620 14:29:37.155344 25491 Matrix.cpp:3275] Check failed: label.getSize() == numSamples (50 vs. 3050) 
*** Check failure stack trace: ***
    @     0x7f3fc47fff09  paddle::CpuMatrix::oneHotCrossEntropy()
    @     0x7f3fc48a762d  google::LogMessage::Fail()
    @     0x7f3fc4675065  paddle::CostLayer::forward()
    @     0x7f3fc48ab0dc  google::LogMessage::SendToLog()
    @     0x7f3fc471b4b0  paddle::NeuralNetwork::forward()
    @     0x7f3fc48a7153  google::LogMessage::Flush()
    @     0x7f3fc48ac5ee  google::LogMessageFatal::~LogMessageFatal()
    @     0x7f3fc46fc38c  paddle::TrainerThread::forward()
    @     0x7f3fc47fff09  paddle::CpuMatrix::oneHotCrossEntropy()
    @     0x7f3fc46fe54c  paddle::TrainerThread::computeThread()
    @     0x7f3fc40a58a0  execute_native_thread_routine
    @     0x7f3fc974b1c3  start_thread
    @     0x7f3fc4675065  paddle::CostLayer::forward()
    @     0x7f3fc8d7312d  __clone
    @              (nil)  (unknown)
Aborted (core dumped)

**Comment by wanghaoshuang** [comment]
你可以先参考下这个issue：https://github.com/PaddlePaddle/Paddle/issues/595
我一边看下你配置

**Comment by jeromeJT** [comment]
参考#595，我在output_layer前加了一层pooling，就可以正常运行了，多谢
咱们有比较直观形象解释full_matrix_projection和mix_layer行为的例子吗？

**Comment by jeromeJT** [comment]
参考#595,在output_layer前加了一层pooling就解决了，多谢
