### ISSUE TITLE
Process finished with exit code -1073741819 (0xC0000005)

### ISSUE THREAD

**Issue by zhao181** [PaddlePaddle/Paddle#25199]
CPU +1.7.2

运行5个iteration后 报错 退出
Process finished with exit code -1073741819 (0xC0000005)

**Comment by chenwhql** [comment]
麻烦您提供下更详细的复现demo的报错信息栈

**Comment by zhao181** [comment]
好了 可能是其他地方的错误导致  具体原因未知 但已解决
