### ISSUE TITLE
编译C++预测模型TensorRT报错

### ISSUE THREAD

**Issue by wuxianshen** [PaddlePaddle/Paddle#25209]
编译C++预测模型TensorRT报错：
error: ‘class nvinfer1::IPluginFactory’ has virtual functions and accessible non-virtual destructor [-Werror=non-virtual-dtor]

环境配置：
GIT COMMIT ID: 12f64401aaef8d7a5a74e5098d89d2b1071a7a9d
WITH_MKL: ON
WITH_MKLDNN: ON
WITH_GPU: ON
CUDA version: 10.1
CUDNN version: v7
WITH_TENSORRT: ON

System: Ubuntu 16.04，x86_64
Python version: 3.6.1
CUDA version: 10.1.243
cuDNN version: 7.6.5
Nvidia driver version: 418.87.00

TensorRT version: 6.0.1.5
(TensorRT-6.0.1.5.Ubuntu-16.04.x86_64-gnu.cuda-10.1.cudnn7.6.tar.gz)

报错信息：
`In file included from /home/tao/software/TensorRT-6.0.1.5/include/NvInfer.h:53:0,
                 from /home/tao/work/deep_learning/paddle-cpp/paddle/paddle/fluid/platform/dynload/tensorrt.h:16,
                 from /home/tao/work/deep_learning/paddle-cpp/paddle/paddle/fluid/platform/dynload/tensorrt.cc:15:
/home/tao/software/TensorRT-6.0.1.5/include/NvInferRuntime.h:329:7: error: ‘class nvinfer1::IDimensionExpr’ has virtual functions and accessible non-virtual destructor [-Werror=non-virtual-dtor]
 class IDimensionExpr
       ^
/home/tao/software/TensorRT-6.0.1.5/include/NvInferRuntime.h:925:7: error: ‘class nvinfer1::IPluginFactory’ has virtual functions and accessible non-virtual destructor [-Werror=non-virtual-dtor]
 class IPluginFactory
       ^
cc1plus: all warnings being treated as errors
paddle/fluid/platform/dynload/CMakeFiles/dynload_cuda.dir/build.make:160: recipe for target 'paddle/fluid/platform/dynload/CMakeFiles/dynload_cuda.dir/tensorrt.cc.o' failed
make[2]: *** [paddle/fluid/platform/dynload/CMakeFiles/dynload_cuda.dir/tensorrt.cc.o] Error 1
make[2]: *** Waiting for unfinished jobs....`

提示纯虚类缺少虚析构函数，手动为其补充虚析构函数后编译通过，但使用预测库时链接报错：
/home/tao/work/deep_learning/paddle-cpp/paddle/install_trt/paddle/lib/libpaddle_fluid.so: undefined reference to `nvinfer1::IPluginFactory::~IPluginFactory()'
collect2: error: ld returned 1 exit status
CMakeFiles/induced_vel_deploy.dir/build.make:111: recipe for target 'induced_vel_deploy' failed
make[2]: *** [induced_vel_deploy] Error 1

**Comment by zhupengyang** [comment]
问题已经记录，感谢反馈~

**Comment by NHZlX** [comment]
请参照这里的文档 ：https://paddle-inference.readthedocs.io/en/latest/optimize/paddle_trt.html 
![image](https://user-images.githubusercontent.com/5595332/85939066-138b4e00-b945-11ea-81d6-bf2bd97783d8.png)

**Comment by wuxianshen** [comment]
谢谢大佬，已根据报错信息修改，编译已通过，谢谢谢谢！
