### ISSUE TITLE
有没有办法把 LoDTensor 转成 给动态图使用的 Variable L类型？

### ISSUE THREAD

**Issue by xperzy** [PaddlePaddle/Paddle#25206]
目前看到 to_variable 只支持 np.array， 如果是已经在GPUPlace上的 LoDTensor 是否有办法转成Variable类型呢？

**Comment by zhupengyang** [comment]
可以用to_variable()转下

**Comment by xperzy** [comment]
谢谢，看到 relsase2.0 beta 版本已经支持。
