### ISSUE TITLE
请问动态图模式下怎么使用静态图模型预测

### ISSUE THREAD

**Issue by ipyffor** [PaddlePaddle/Paddle#25203]
因为使用fluid.enable_imperative(place)全局开启动态图导致静态模型不能用，使用fluid.disable_imperative()的话又要重复关闭开启动态图，主要模型是动态图的，有没有类似动态图上下文管理气的方式使用静态图的，或者其他方式，望解答，谢谢

**Comment by phlrain** [comment]
暂时还不支持动态图和静态图混合使用的情况下，整个任务必须全部是动态图或者全部是静态图
