### ISSUE TITLE
ZeroCopyTensor无法使用double类型

### ISSUE THREAD

**Issue by wuxianshen** [PaddlePaddle/Paddle#25204]
使用C++部署预测模型，模型中参数是float64类型，预测程序中使用double类型，提示错误，找不到实例化的模板函数：

`Scanning dependencies of target induced_vel_deploy
[ 50%] Building CXX object CMakeFiles/induced_vel_deploy.dir/main.cpp.o
[100%] Linking CXX executable induced_vel_deploy
CMakeFiles/induced_vel_deploy.dir/main.cpp.o: In function `paddle::test_induced_field(int, int)':
/home/tao/work/tools/induced_vel_process/induced_vel_deploy/main.cpp:75: undefined reference to `void paddle::ZeroCopyTensor::copy_from_cpu<double>(double const*)'
/home/tao/work/tools/induced_vel_process/induced_vel_deploy/main.cpp:93: undefined reference to `void paddle::ZeroCopyTensor::copy_to_cpu<double>(double*)'
collect2: error: ld returned 1 exit status
CMakeFiles/induced_vel_deploy.dir/build.make:111: recipe for target 'induced_vel_deploy' failed
make[2]: *** [induced_vel_deploy] Error 1
CMakeFiles/Makefile2:95: recipe for target 'CMakeFiles/induced_vel_deploy.dir/all' failed
make[1]: *** [CMakeFiles/induced_vel_deploy.dir/all] Error 2
Makefile:103: recipe for target 'all' failed
make: *** [all] Error 2`

C++程序：
`#include <gflags/gflags.h>
#include <glog/logging.h>
#include <numeric>
#include <iostream>
#include <memory>
#include <chrono>
#include "paddle/include/paddle_inference_api.h"

namespace paddle{
    using paddle::AnalysisConfig;

    DEFINE_string(dirname, "../infer_model", "Directory of the inference model.");

    using Time = decltype(std::chrono::high_resolution_clock::now());

    Time time()
    {
        return std::chrono::high_resolution_clock::now();
    }

    double time_diff(Time t1, Time t2)
    {
        typedef std::chrono::microseconds  ms;
        auto diff = t2 - t1;
        ms counter = std::chrono::duration_cast<ms>(diff);
        return counter.count() / 1000.0f;
    }

    void prepare_trt_config(AnalysisConfig* config, int batch_size)
    {
        // 1. Model directory
        // case 1: model_dir contains two files: model + params
        //config->SetModel(FLAGS_dirname + "/model", FLAGS_dirname + "/params");
        // case 2: model_dir contains one model file (__model__) and multiple params
        config->SetModel(FLAGS_dirname);

        // 2. Device
        // config->DisableGpu();
        config->EnableUseGpu(500, 0);

        // 3. General optimization
        // Graph optimization, including operator fusion
        //config->SwitchIrOptim(true);
        // Memory reuse
        //config->EnableMemoryOptim();

        // We use ZeroCopyTensor here, so we set config->SwitchUseFeedFetchOps(false)
        config->SwitchUseFeedFetchOps(false);

    }

    void test_induced_field(int batch_size, int repeat)
    {
        AnalysisConfig config;
        prepare_trt_config(&config, batch_size);

        auto predictor = CreatePaddlePredictor(config);

        int channels = 1;
        int height = 1;
        int width  = 8; // 8 floats as input vector
        int input_num = channels * height * width * batch_size;

        // prepare inputs
        //float *input = new float[input_num];
        //memset(input, 0, input_num * sizeof(float));

        double input[] = {9.38945293e+00, 9.54218483e+00, 4.00937128e+00, 2.98900008e-01,
        7.20000000e+02, 1.02042408e+01, 9.72727203e+00, 4.30936718e+00};
        CHECK(sizeof(input) == input_num * sizeof(double));

        auto input_names = predictor->GetInputNames();
        auto input_t = predictor->GetInputTensor(input_names[0]);
        input_t->Reshape({batch_size, channels, height, width});
        input_t->copy_from_cpu(input);

        // run
        auto time1 = time();
        CHECK(predictor->ZeroCopyRun());
        auto time2 = time();
        std::cout << "batch: " << batch_size
                  << " predict cost: " << time_diff(time1, time2) / static_cast<float>(repeat)
                  << " ms" << std::endl;

        // get the output
        std::vector<double> out_data;
        auto output_names = predictor->GetOutputNames();
        auto output_t = predictor->GetOutputTensor(output_names[0]);
        std::vector<int> output_shape = output_t->shape();
        int out_num = std::accumulate(output_shape.begin(), output_shape.end(), 1, std::multiplies<int>());

        out_data.resize(out_num);
        output_t->copy_to_cpu(out_data.data());

        for ( size_t j = 0; j < out_num; j++ )
        {
            LOG(INFO) << "output[ " << j << " ]: " << out_data[j];
        }
    }
}

int main()
{
    std::cout << "Induced field model inference..." << std::endl;

    paddle::test_induced_field(1, 1);

    return 0;
}
`

**Comment by zhupengyang** [comment]
收到，我们会尽快回复的~

**Comment by zhupengyang** [comment]
ZeroCopyTensor目前不支持double类型，建议转成float。正在考虑在后续添加double的支持~

**Comment by wuxianshen** [comment]
好的谢谢大佬！～
