### ISSUE TITLE
动态图 Dataset+DataLoader读数据 报错

### ISSUE THREAD

**Issue by zhao181** [PaddlePaddle/Paddle#25211]
环境 Aistudio+paddle 1.8.0

num_workers设置为0  可正常工作 
num_workers设置为2  崩溃  

    valLoader=DataLoader(validate_set,
                places=fluid.CUDAPlace(0),
                return_list=True,
                shuffle=False,
                drop_last=False,
                batch_size=4,
                num_workers=2,
                batch_sampler=None,
                feed_list=None,
                collate_fn=None,
                timeout=0,
                use_buffer_reader=True,
                use_shared_memory=True,
                worker_init_fn=None)

    trLoader=DataLoader(train_set,
                places=fluid.CUDAPlace(0),
                return_list=True,
                shuffle=True,
                drop_last=True,
                batch_size=4,
                num_workers=0,
                batch_sampler=None,
                feed_list=None,
                collate_fn=None,
                timeout=0,
                use_buffer_reader=True,
                use_shared_memory=True,
                worker_init_fn=None)

并报错如下：

2020-06-27 12:49:59,484-WARNING: Please NOTE: dygraph can support return as list only. Change to return as list.
2020-06-27 12:49:59,486-WARNING: Please NOTE: dygraph can support return as list only. Change to return as list.
do_ shuffle
2020-06-27 12:51:03,592-ERROR: DataLoader reader thread raised an exception!
2020-06-27 12:51:03,594-ERROR: DataLoader reader thread failed to read data from the multiprocessing.Queue.
Exception in thread Thread-4:
Traceback (most recent call last):
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/reader.py", line 874, in _reader_thread_loop_for_multiprocess
    six.reraise(*sys.exc_info())
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/six.py", line 703, in reraise
    raise value
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/reader.py", line 865, in _reader_thread_loop_for_multiprocess
    tensor_list = self._data_queue.get(timeout=QUEUE_GET_TIMEOUT)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/multiprocessing/queues.py", line 105, in get
    raise Empty
_queue.Empty

---------------------------------------------------------------------------EnforceNotMet                             Traceback (most recent call last)/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/reader.py in __next__(self)
    803         try:
--> 804             return self._reader.read_next_var_list()
    805         except StopIteration:
EnforceNotMet: 

--------------------------------------------
C++ Call Stacks (More useful to developers):
--------------------------------------------
0   std::string paddle::platform::GetTraceBackString<std::string const&>(std::string const&, char const*, int)
1   paddle::platform::EnforceNotMet::EnforceNotMet(std::string const&, char const*, int)
2   paddle::operators::reader::BlockingQueue<std::vector<paddle::framework::LoDTensor, std::allocator<paddle::framework::LoDTensor> > >::Receive(std::vector<paddle::framework::LoDTensor, std::allocator<paddle::framework::LoDTensor> >*)
3   paddle::operators::reader::PyReader::ReadNext(std::vector<paddle::framework::LoDTensor, std::allocator<paddle::framework::LoDTensor> >*)
4   std::_Function_handler<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> (), std::__future_base::_Task_setter<std::unique_ptr<std::__future_base::_Result<unsigned long>, std::__future_base::_Result_base::_Deleter>, unsigned long> >::_M_invoke(std::_Any_data const&)
5   std::__future_base::_State_base::_M_do_set(std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> ()>&, bool&)
6   ThreadPool::ThreadPool(unsigned long)::{lambda()#1}::operator()() const

----------------------
Error Message Summary:
----------------------
Error: Blocking queue is killed because the data reader raises an exception
  [Hint: Expected killed_ != true, but received killed_:1 == true:1.] at (/paddle/paddle/fluid/operators/reader/blocking_queue.h:141)

During handling of the above exception, another exception occurred:
EnforceNotMet                             Traceback (most recent call last)<ipython-input-3-c3a635b10970> in <module>
     44             time1=time()
     45             mLoss,trIdMetric1=train(model, trLoader,
---> 46             optimizer,trCfg, criterion, trMetric=trMetric)
     47             print_metric(trIdMetric1)
     48 
~/codic/tools/trValidate.py in train(model, trLoader, optimizer, trCfg, criterion, trMetric)
      9     trMetric.reset_metric()
     10     totalLoss, totalcnt = 0.0, 0
---> 11     for idx,data in enumerate(trLoader):
     12         #print("lr:",optimizer.current_step_lr())
     13         image = dygraph.to_variable(data[0])
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/reader.py in __next__(self)
    802     def __next__(self):
    803         try:
--> 804             return self._reader.read_next_var_list()
    805         except StopIteration:
    806             self._reset()
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/multiprocess_utils.py in __handler__(signum, frame)
    132         # this handler will be called whenever the child process exits
    133         # normally or abnormally.
--> 134         core._throw_error_if_process_failed()
    135         if current_handler is not None:
    136             current_handler(signum, frame)
EnforceNotMet: 

--------------------------------------------
C++ Call Stacks (More useful to developers):
--------------------------------------------
0   std::string paddle::platform::GetTraceBackString<std::string>(std::string&&, char const*, int)
1   paddle::imperative::ThrowErrorIfLoadProcessFailed()

----------------------
Error Message Summary:
----------------------
FatalError: DataLoader process (pid   1. If run DataLoader by DataLoader.from_generator(...), queue capacity is set by from_generator(..., capacity=xx, ...).
  2. If run DataLoader by DataLoader(dataset, ...), queue capacity is set as 2 times of the max value of num_workers and len(places).
  3. If run by DataLoader(dataset, ..., use_shared_memory=True), set use_shared_memory=False for not using shared memory.) exited is killed by signal: 692.
  It may be caused by insufficient shared storage space. This problem usually occurs when using docker as a development environment.
  Please use command `df -h` to check the storage space of `/dev/shm`. Shared storage space needs to be greater than (DataLoader Num * DataLoader queue capacity * 1 batch data size).
  You can solve this problem by increasing the shared storage space or reducing the queue capacity appropriately.
Bus error at (/paddle/paddle/fluid/imperative/data_loader.cc:165)

**Comment by heavengate** [comment]
```
FatalError: DataLoader process (pid 1. If run DataLoader by DataLoader.from_generator(...), queue capacity is set by from_generator(..., capacity=xx, ...).
2. If run DataLoader by DataLoader(dataset, ...), queue capacity is set as 2 times of the max value of num_workers and len(places).
3. If run by DataLoader(dataset, ..., use_shared_memory=True), set use_shared_memory=False for not using shared memory.) exited is killed by signal: 692.
It may be caused by insufficient shared storage space. This problem usually occurs when using docker as a development environment.
Please use command df -h to check the storage space of /dev/shm. Shared storage space needs to be greater than (DataLoader Num * DataLoader queue capacity * 1 batch data size).
You can solve this problem by increasing the shared storage space or reducing the queue capacity appropriately.
Bus error at (/paddle/paddle/fluid/imperative/data_loader.cc:165)
```

报错信息是共享内存不够，即`/dev/shm`下空间不够，AIStudio上应该用的是默认的64M，单batch的数据空间估计比较大，算上缓存64M不够用，可以把`use_share_memory=False`

**Comment by zhao181** [comment]
好的   操作完正确了

**Comment by liu824** [comment]
你好，我同样遇到了这个问题，但是我使用的是Dataloder.from_generator(),里边没有use_share_memory这个参数，那我该如何操作呢？

**Comment by liu824** [comment]
我把use_multiprocess设置为False不报错了
