### ISSUE TITLE
load_inference_model载入得模型怎么查看每一层的参数？

### ISSUE THREAD

**Issue by HaoLiuHust** [PaddlePaddle/Paddle#25213]
用load_inference_model载入了model zoo里面的模型，然后用program.all_parameters()出来是空列表，怎么查看每一层的参数？

**Comment by zhupengyang** [comment]
fetch_list里面加参数的name，name可以通过netron查看到

**Comment by HaoLiuHust** [comment]
fetch出来的不是推理结果么，我需要的是权重

**Comment by HaoLiuHust** [comment]
我想要查看的是每一层的权重

**Comment by zhupengyang** [comment]
可以试下，fetch理论上是可以获取任何variable的，不一定是推理结果

**Comment by HaoLiuHust** [comment]
> 可以试下，fetch理论上是可以获取任何variable的，不一定是推理结果

哦哦，这个fetch list是加在哪呢

**Comment by HaoLiuHust** [comment]
exe.run里面么

**Comment by zhupengyang** [comment]
> exe.run里面么

是的

**Comment by zhupengyang** [comment]
> exe.run里面么

是的

**Comment by zhupengyang** [comment]
> exe.run里面么

是的

**Comment by HaoLiuHust** [comment]
netron看不了paddle文件

**Comment by HaoLiuHust** [comment]
报错了这么做...

**Comment by zhupengyang** [comment]
> 报错了这么做...

报了什么错？

**Comment by HaoLiuHust** [comment]
找到方法了，用fluid.global_scope().find_var(“var_name”).get_tensor()
