### ISSUE TITLE
使用Linear层出错

### ISSUE THREAD

**Issue by Willianwatch** [PaddlePaddle/Paddle#25226]
- 标题：简洁、精准概括您的问题，例如“Insufficient Memory xxx" ”
- 版本、环境信息：
    1）PaddlePaddle版本：1.8
    2）CPU：无
    3）GPU：Tesla V100
    4）系统环境：AI Studio
- 训练信息
    1）单机，单卡
    2）显存信息
    3）Operator信息
- 复现信息：已将小项目公开，大约50行，请看链接
[https://aistudio.baidu.com/aistudio/projectdetail/596059](url)
- 问题描述：尝试翻译了下GAN by 50 lines, 在linear层处出错，但是感觉维度和数据类型都没有什么问题，求解答

**Comment by willthefrog** [comment]
组网部分放到`fluid.dygraph.guard`里试试？
```python
with fluid.dygraph.guard(device):
  D = Discriminator()
  G = Generator()
```

**Comment by Willianwatch** [comment]
> 组网部分放到`fluid.dygraph.guard`里试试？
> 
> ```python
> with fluid.dygraph.guard(device):
>   D = Discriminator()
>   G = Generator()
> ```

你好，按你说的我解决了这个问题，但是想问下为什么会这样呢？谢谢！

**Comment by willthefrog** [comment]
weight创建是在静态图模式下进行的，所以不是动态图得varbase类型。 如果解决了麻烦close下issue。谢谢。
