### ISSUE TITLE
关于数据读取提速问题

### ISSUE THREAD

**Issue by zhao181** [PaddlePaddle/Paddle#25220]
静态图训练很慢 
比动态图还慢 
发现主要瓶颈在于数据读取

请问
[1] windows下静态图用哪个接口读数据 最快？
[2] linux下 静态图用哪个接口读数据 最快？

[3] 我在程序中使用了py_func函数（每次迭代都使用） 速度慢是否也与此有关？

谢谢 盼回复

**Comment by willthefrog** [comment]
1. & 2.目前推荐的数据读取接口是 `fluid.io.DataLoader`，请注意设置`use_double_buffer=True`
3. `py_func`操作可能会造成多次copy，耗时会相对高一些，如果能通过op组合实现建议使用组合实现。
