### ISSUE TITLE
Report A Little Bug

### ISSUE THREAD

**Issue by leesusu** [PaddlePaddle/Paddle#25229]
In file python/paddle/fluid/optimizer.py, 

![image](https://user-images.githubusercontent.com/2424688/85944095-fa939480-b966-11ea-8b9f-a9ebd45f8457.png)

Solved in #25223

**Comment by willthefrog** [comment]
Thanks for your contribution, will get back to you soon.

**Comment by leesusu** [comment]
@frankwhzhang @willthefrog 推进下这个吧，很小的改动，应该没啥问题，是个很明显的bug，PR的CI也都过了
