### ISSUE TITLE
关于单测框架OPTest类的一个疑问

### ISSUE THREAD

**Issue by DDDivano** [PaddlePaddle/Paddle#25228]
https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/fluid/tests/unittests/op_test.py 中1149行。
self.dtype如果是float16，为什么要单做处理？
我看代码理解是如果是float16类型，一定是只支持GPU，如果GPU不支持这个精度，那么该OP就不支持float16这个类型，CPU是一定不支持float16的，这么理解对吗？
![image](https://user-images.githubusercontent.com/10734244/85943678-16e20200-b964-11ea-9d84-8a7324919f7e.png)

**Comment by willthefrog** [comment]
基本上是这样，目前只有部分op的cuda kernel支持fp16，cpu不支持。

**Comment by DDDivano** [comment]
> 基本上是这样，目前只有部分op的cuda kernel支持fp16，cpu不支持。

好，明白了
