### ISSUE TITLE
本地测试出错：exe.run(startup)出core。

### ISSUE THREAD

**Issue by 1830789843** [PaddlePaddle/Paddle#25238]
具体报错如下。

![Image](https://user-images.githubusercontent.com/40987029/85968796-928d8e80-b9f8-11ea-91c0-ce83f564ba14.png)
![Image2](https://user-images.githubusercontent.com/40987029/85968807-97ead900-b9f8-11ea-8156-5f2046c0913d.png)

集群上，也报该错，但是通过修改配置gpu卡数，已解决。
本地训练，一直报改错。

**Comment by LielinJiang** [comment]
请问paddle版本，模型，和启动命令分别是？

**Comment by 1830789843** [comment]
> 请问paddle版本，模型，和启动命令分别是？

paddle版本：paddle-fluid-v1.6.3

resnet152和bilstm

MP_CONFIG="--selected_gpus=0,1,2"
${python_bin}  -m paddle.distributed.launch ${MP_CONFIG} train.py \
    $BASIC_CONFIG  \
    $TRAIN_STAGE1_CONFIG

**Comment by 1830789843** [comment]
paddle版本paddle-fluid-v1.6.3
模型：resnet152

MP_CONFIG="--selected_gpus=0,1,2"
${python_bin}  -m paddle.distributed.launch ${MP_CONFIG} train.py \
    $BASIC_CONFIG  \
    $TRAIN_STAGE1_CONFIG

**Comment by 1830789843** [comment]
最终解决：使用 export CUDA_VISIBLE_DEVICES 替换 selected_gpus=0,1,2
