### ISSUE TITLE
Windows编译develop分支，映像大小超过允许的最大大小

### ISSUE THREAD

**Issue by hello-web** [PaddlePaddle/Paddle#25269]
CPU：E5-2678 v3
GPU：k80
System：windows server 2019
Visual Studio: Visual Studio 2015 update3
PaddlePaddle: develop
GIT COMMIT ID: 87a4a7ec12be222d070367665dbc2900a5bd3eb6
WITH_MKL: ON
WITH_MKLDNN: ON
WITH_GPU: ON
CUDA version: 9.0
CUDNN version: v7.4
CXX compiler version: 19.0.24215.1

复现信息：
(1) cmake .. -G "Visual Studio 14 2015" -A x64 -T host=x64 -DCMAKE_BUILD_TYPE=Release -DWITH_MKL=ON -DWITH_GPU=ON -DON_INFER=ON -DWITH_PYTHON=OFF -DMSVC_STATIC_CRT=ON
(2) Visual Studio 2015 update3 打开 paddle.sln 文件，选择平台为x64，配置为Release，先编译third_party模块，再编译inference_lib_dist模块。 操作方法：在Visual Studio中选择相应模块，右键选择"生成"（或者"build"）

问题描述：LNK1248	映像大小(100000B15)超过允许的最大大小(FFFFFFFF)	paddle_fluid	...build\paddle\fluid\inference\Release\libpaddle_fluid.lib

**Comment by jiweibo** [comment]
目前develop分支在windows上编出的静态库体积超过4G编译失败，后续会对静态库进行优化。

**Comment by hello-web** [comment]
> 目前develop分支在windows上编出的静态库体积超过4G编译失败，后续会对静态库进行优化。

好的。谢谢。
