### ISSUE TITLE
每个pass只运行两个batch就下一个pass

### ISSUE THREAD

**Issue by twoboysbaba** [PaddlePaddle/Paddle#25275]
mpi训练日志：
http://10.182.83.14:8910/fileview.html?type=logsdir&path=/&instance=335.app-user-20200629220916-129--zhaolei06_paddle_online_besitemcf_all_paddlecloud
![image](https://user-images.githubusercontent.com/24586689/86114378-044f0080-bafd-11ea-9284-515ca0b296d0.png)
本地测试正常
![image](https://user-images.githubusercontent.com/24586689/86114550-4415e800-bafd-11ea-8f4d-bbd70e63cdf2.png)
对应的代码逻辑：
![image](https://user-images.githubusercontent.com/24586689/86114758-922aeb80-bafd-11ea-9f9d-ad7e6e396ce3.png)

**Comment by zhiqiu** [comment]
经沟通排查，原因是mpi上面的train_data数据较少，只有两个batch的数据，可能是上传数据时的问题。
