### ISSUE TITLE
How to skip to validate selected output tensors in python unit tests?

### ISSUE THREAD

**Issue by jczaja** [PaddlePaddle/Paddle#25288]
Hi,

There are operators like LRN which are having one of an outputs (MidOut) that is no use for user , but it contains intermediate data
that are speeding computation of LRN grad operator. In unit tests, (test_check_output) this MidOut is also verified if it contains valid / expected data. Problem is that what is inside MidOut is implementation specific. oneDNN LRN will produce MidOut with diffrent kind of data, because LRN oneDNN grad op is diffrent in implementation to Paddle CPU LRN grad. So unit test may fail
due to diffrent kind of data being put into MidOut. So my question is : is it possible to skip comparing MidOut tensor in Unit tests of LRN oneDNN ? If positive then how can I do that?

**Comment by zhiqiu** [comment]
Hi, you can call `self.check_output(no_check_set=['MidOut'])` , so `MidOut` will not be checked.

**Comment by jczaja** [comment]
@zhiqiu  Thanks for suggestion! To actually have it working I also needed to add *lrn* to *no_check_set_whitelist*.
