### ISSUE TITLE
如何关闭NCCL2支持？

### ISSUE THREAD

**Issue by Derek-Kun** [PaddlePaddle/Paddle#25283]
我系统CentOS8， NCCL支持CentOS8的版本都是2.75以上的，CUDA版本都是10.2以上的，PADLLE最多支持到CUDA10.1和NCCL 2.47, 然后我在CENTOS8上安装了PADDLE以后运行测试程序的时候也说单卡运行没问题，多卡没法运行。然后我用ATTENTION LSTM做训练的时候把nums_gpu特意设置成了1， 也就是单卡训练，可是运行起来以后还是会报错

Error: Failed to find dynamic library: libnccl.so ( libnccl.so: cannot open shared object file: No such file or directory ) 
 Please specify its path correctly using following ways: 
 Method. set environment variable LD_LIBRARY_PATH on Linux or DYLD_LIBRARY_PATH on Mac OS. 
 For instance, issue command: export LD_LIBRARY_PATH=... 
 Note: After Mac OS 10.11, using the DYLD_LIBRARY_PATH is impossible unless System Integrity Protection (SIP) is disabled. at (/paddle/paddle/fluid/platform/dynload/dynamic_loader.cc:177)

我想把NCCL关了，貌似设置NUMS_gpu=1也不行，然后设置export CUDA_VISIBLE_DEVICES=0 之后还是不行，会报错，请问如何解决？

**Comment by zhiqiu** [comment]
hi，单卡执行时不需要加载NCCL的，您可以看下是不是设置了多卡。可以把复现代码发出来看看。

**Comment by Derek-Kun** [comment]
我照着你说的下了一个CENTOS7老版本的NCCL然后重连了一下服务器，单卡可以跑了，但是多卡还是报同样的错误，我先单卡凑合着跑吧，感谢回答。
