### ISSUE TITLE
训练loss出现nan

### ISSUE THREAD

**Issue by junior-talk** [PaddlePaddle/Paddle#25299]
paddlecloud任务: job-0bb5efc13130651a
训练过程中，很快出现loss为nan的情况

尝试过添加梯度裁剪，调整batch size未能解决

设置FLAGS_check_nan_inf后出现如下信息：
![image](https://user-images.githubusercontent.com/20383599/86213693-aed22c80-bbac-11ea-969b-081b13db9903.png)
![image](https://user-images.githubusercontent.com/20383599/86213720-b691d100-bbac-11ea-93de-c71ec83e0b41.png)

**Comment by junior-talk** [comment]
另外，我的loss由a、b两部分相加得到。训练过程中，我将三个值都打印出来，发现a+b != loss。

**Comment by GaoWei8** [comment]
可以考虑learning rate的大小设置。

**Comment by GaoWei8** [comment]
如果不是learning rate的问题的话，应该就是数据里面类似有0，然后运算过程中出现除0之类的问题导致出nan。可以使用scope.find_var打印中间结果查看。
