### ISSUE TITLE
Integrate Caffe layers

### ISSUE THREAD

**Issue by wangkuiyi** [PaddlePaddle/Paddle#253]

**Comment by qingqing01** [comment]
## 编译
- 链入libcaffe
- paddle里的部分wrapper需要caffe源码头文件

## 用户接口
用户接口是Layer形式。

```python
CaffeLayer(input,
           prototxt,  #指定caffe的layer配置， string类型
           name=None，
           param_attr=None,
           bias_attr=None,
           layer_attr=None
           )
```
## Paddle接口
总体原则：

1. Paddle在CaffeLayer里调用Caffe lib。
2. CaffeLayer

- Layer实现
  - Layer里面依据prototxt创建caffe layer对象
  - 创建parameter，并set给Caffe的weights
  - 调用layer的forward/backward
  - parameter调用callback，走Paddle更新流程

- Caffe Wrapper
  - 参数转换wrapper, Blob <-> Argument转换
   
## 可能存在的问题

具体实现时得考虑：

- Parameter构造：
   -  Caffe是在Layer的C++代码 init里设置weight大小，创建并初始化。
   -  Paddle实在python接口config_parse.py里设置parameter size。
   -  caffe的prototxt的配置无法解析到parameter size大小。

- 其他问题...

**Comment by wangkuiyi** [comment]
"MxNet方案"可以加一个连接吗？

**Comment by wangkuiyi** [comment]
@emailweixu 提醒：要注意open source license是否兼容

**Comment by qingqing01** [comment]
mxnet 链接： https://github.com/dmlc/mxnet/tree/master/plugin/caffe

**Comment by qingqing01** [comment]
在集成Caffe中，需要Paddle的数据结构(Argument)和Caffe的数据结构(Blob)共享内存。 包括：value 、grad、cpu内存、gpu内存。

而Blob只有一个接口 [void set_cpu_data(Dtype* data)] (https://github.com/BVLC/caffe/blob/master/include/caffe/blob.hpp#L220) 可以设置Blob的memory。  看了下没有其他的方式。

mxnet的做法是给Caffe了打了patch：  https://patch-diff.githubusercontent.com/raw/BVLC/caffe/pull/4527.patch  

Paddle是否也要这种做？

**Comment by luotao1** [comment]
> Paddle是否也要这种做？

我觉得可以。
