### ISSUE TITLE
cross_entropy算子报label维度错误

### ISSUE THREAD

**Issue by ggjge** [PaddlePaddle/Paddle#25303]
为使您的问题得到快速解决，在建立Issue前，请您先通过如下方式搜索是否有相似问题:【搜索issue关键字】【使用labels筛选】【官方文档】

建立issue时，为快速解决问题，请您根据使用情况给出如下信息：
- 标题：简洁、精准描述您的问题，例如“ssd 模型前置lstm报错  ”
- 版本、环境信息：
    1）PaddlePaddle版本：1.8.2

- 问题描述：请详细描述您的问题，同步贴出报错信息、日志/代码关键片段

输入cross_entropy的label的shape是(m, n, 1)，仍报错：
![image](https://user-images.githubusercontent.com/10115676/86217153-a4fef800-bbb1-11ea-97d4-6ee256ea8c83.png)

代码：
![image](https://user-images.githubusercontent.com/10115676/86216642-f1960380-bbb0-11ea-8667-896c76cf8444.png)

打印label的shape的日志：
![image](https://user-images.githubusercontent.com/10115676/86216746-1b4f2a80-bbb1-11ea-9a34-2d3bd550b909.png)

Thank you for contributing to PaddlePaddle.
Before submitting the issue, you could search issue in the github.Probably there was a similar issue submitted or resolved before.
If there is no solution,please make sure that this is a issue of models including the following details:
**System information**
-PaddlePaddle version （eg.1.1）or CommitID
-CPU: including CPUMKL/OpenBlas/MKLDNN version
-GPU: including CUDA/CUDNN version
-OS Platform (eg.Mac OS 10.14)
-Python version
-Name of Models&Dataset/details of operator
Note: You can get most of the information by running [summary_env.py](https://github.com/PaddlePaddle/Paddle/blob/develop/tools/summary_env.py). 
**To Reproduce**
Steps to reproduce the behavior
**Describe your current behavior**
**Code to reproduce the issue**
**Other info / logs**

**Comment by GaoWei8** [comment]
目前确认用户的输入维度没有问题，并且更换cross_entropy前的API，还是会出现相同问题。

**Comment by shippingwang** [comment]
报错并不是这行cross_entropy, 所以你打印的/debug的地方也不对，请查看代码中其他位置的cross_entropy
