### ISSUE TITLE
用其他模型quant aware出来的int8模型能直接用在paddle里面吗

### ISSUE THREAD

**Issue by HaoLiuHust** [PaddlePaddle/Paddle#25314]
比如我用pytorch或其他框架已经训练好了一个int8模型，这个模型能直接用在paddle或者paddle-lite上吗

**Comment by jiangjiajun** [comment]
> 比如我用pytorch或其他框架已经训练好了一个int8模型，这个模型能直接用在paddle或者paddle-lite上吗

int8模型暂不支持。用Pytorch、Tensorflow或者Caffe正常训练好的模型，可以通过X2Paddle尝试转到Paddle框架。目前支持大多数的图像分类模型，目标检测和语义分割及Gan类型模型也有相应支持。具体模型是否支持取决于X2Paddle是否支持模型所使用到的OP算子。

这里是X2Paddle目前支持的OP算子列表： https://github.com/PaddlePaddle/X2Paddle/blob/develop/op_list.md
这里是X2Paddle目前测试过的一些模型转换： https://github.com/PaddlePaddle/X2Paddle/blob/develop/x2paddle_model_zoo.md
