### ISSUE TITLE
concat运算有误

### ISSUE THREAD

**Issue by mamingjie-China** [PaddlePaddle/Paddle#25318]
在进行模型转换时发现，Paddle(CPU)1.8.2的concat这个OP，如果其中一个输入的维度不确定，一个输入维度确定，例如一个tensor的维度为[-1,-1,-1,-1]，另一个为[1,32,64,64]时，若axis=1，得到的tensor维度为[-1,31,-1,-1]，即直接进行了加减处理，正常结果应该是输出的tensor也是不确定的，即[-1,-1,-1,-1]。望尽快修复
![image](https://user-images.githubusercontent.com/52770436/86242881-f3bf8880-bbd7-11ea-8879-e91dc96ace37.png)

**Comment by GaoWei8** [comment]
目前concat不支持维度不相同的情况下，进行concat计算。

**Comment by GaoWei8** [comment]
需求已收到。

**Comment by mamingjie-China** [comment]
import paddle.fluid as fluid
data0 = fluid.data(dtype='float32', shape=[-1, 20], name='data0')
data1 = fluid.data(dtype='float32', shape=[1, 20], name='data1')
result = fluid.layers.concat([data0, data1])
result

![image](https://user-images.githubusercontent.com/52770436/86243842-9af0ef80-bbd9-11ea-92f3-dc4867e8ff92.png)

**Comment by mamingjie-China** [comment]
> 需求已收到。

import paddle.fluid as fluid
data0 = fluid.data(dtype='float32', shape=[-1, 20], name='data0')
data1 = fluid.data(dtype='float32', shape=[1, 20], name='data1')
result = fluid.layers.concat([data0, data1])
result

![image](https://user-images.githubusercontent.com/52770436/86243950-cbd12480-bbd9-11ea-998e-d8857e1bfc86.png)

**Comment by GaoWei8** [comment]
修复PR已merge。
