### ISSUE TITLE
[operator < feed > error]

### ISSUE THREAD

**Issue by ArtyZe** [PaddlePaddle/Paddle#25317]
使用paddle提供的模型，进行最简单的一次前向预测，报了如下的错误，麻烦帮忙看一下，谢谢
  [Hint: Expected static_cast<size_t>(col) < feed_list.size(), but received static_cast<size_t>(col):0 >= feed_list.size():0.] at (D:\1.6.3\paddle\paddle\fluid\operators\controlflow\feed_op.cc:53)

[operator < feed > error]

**Comment by GaoWei8** [comment]
麻烦贴下代码，看起来是没有feed输入。

**Comment by ArtyZe** [comment]
@GaoWei8 您好，代码如下，我也怀疑是输入的问题，所以我将tensor打印出来是存在的
```
import cv2
import numpy as np
import paddle
from paddle.fluid.core import *

model_path = "C:/Users/OEMUSER/.paddlehub/modules/resnet_v2_50_imagenet/model/"

image = cv2.imread("support_files/elephant.jpg")
image_data = np.array(image).astype("float32")

tensor = PaddleTensor(name="tensor", data=image_data)

print(tensor.as_ndarray())

config = AnalysisConfig(model_path)
config.disable_gpu()
config.switch_ir_optim(False)

predictor = create_paddle_predictor(config)

results = predictor.run([tensor])

print(results)
```
![image](https://user-images.githubusercontent.com/32027268/86242892-f7eba600-bbd7-11ea-91ea-03e4a9460d96.png)
所有的输出信息：
```
I0701 20:26:29.221562  9616 analysis_predictor.cc:138] Profiler is deactivated, and no profiling report will be generated.
I0701 20:26:29.250563  9616 op_compatible_info.cc:201] The default operator required version is missing. Please update the model version.
I0701 20:26:29.250563  9616 analysis_predictor.cc:872] MODEL VERSION: 0.0.0
I0701 20:26:29.251564  9616 analysis_predictor.cc:874] PREDICTOR VERSION: 1.8.2
I0701 20:26:29.252563  9616 analysis_predictor.cc:471] ir_optim is turned off, no IR pass will be executed
e[1me[35m--- Running analysis [ir_graph_build_pass]e[0m
e[1me[35m--- Running analysis [ir_graph_clean_pass]e[0m
e[1me[35m--- Running analysis [ir_analysis_pass]e[0m
e[1me[35m--- Running analysis [ir_params_sync_among_devices_pass]e[0m
e[1me[35m--- Running analysis [adjust_cudnn_workspace_size_pass]e[0m
e[1me[35m--- Running analysis [inference_op_replace_pass]e[0m
e[1me[35m--- Running analysis [ir_graph_to_program_pass]e[0m
I0701 20:26:29.408572  9616 analysis_predictor.cc:493] ======= optimize end =======
Traceback (most recent call last):
  File "paddle_infer.py", line 22, in <module>
    results = predictor.run([tensor])
paddle.fluid.core_avx.EnforceNotMet:

--------------------------------------------
C++ Call Stacks (More useful to developers):
--------------------------------------------
Windows not support stack backtrace yet.

------------------------------------------
Python Call Stacks (More useful to users):
------------------------------------------
  File "/home/zhangxuefei/anaconda2/envs/HUB1.0.0-Paddle1.4.0/lib/python3.6/site-packages/paddle/fluid/framework.py", line 1725, in _prepend_op
    attrs=kwargs.get("attrs", None))
  File "/home/zhangxuefei/anaconda2/envs/HUB1.0.0-Paddle1.4.0/lib/python3.6/site-packages/paddle/fluid/io.py", line 845, in prepend_feed_ops
    attrs={'col': i})
  File "/home/zhangxuefei/anaconda2/envs/HUB1.0.0-Paddle1.4.0/lib/python3.6/site-packages/paddle/fluid/io.py", line 1000, in save_inference_model
    prepend_feed_ops(main_program, feeded_var_names)
  File "/home/zhangxuefei/anaconda2/envs/HUB1.0.0-Paddle1.4.0/lib/python3.6/site-packages/paddlehub/module/module.py", line 676, in serialize_to_path
    executor=exe)
  File "/home/zhangxuefei/anaconda2/envs/HUB1.0.0-Paddle1.4.0/lib/python3.6/site-packages/paddlehub/module/module.py", line 68, in create_module
    module.serialize_to_path(path=module_dir, exe=exe)
  File "create_module.py", line 80, in create_module
    exe=exe)
  File "create_module.py", line 91, in main
    create_module(args)
  File "create_module.py", line 95, in <module>
    main()

----------------------
Error Message Summary:
----------------------
InvalidArgumentError: The column index of current feeding variable is expected to be less than the length of feeding list. But received column index = 0, the length of feeding list = 0
  [Hint: Expected static_cast<size_t>(col) < feed_list.size(), but received static_cast<size_t>(col):0 >= feed_list.size():0.] at (D:\1.8.2\paddle\paddle\fluid\operators\controlflow\feed_op.cc:68)
  [operator < feed > error]
```

**Comment by jiweibo** [comment]
能否用最新的paddle再测一下，也可以跑一下示例代码，看看是不是库的问题
https://www.paddlepaddle.org.cn/documentation/docs/zh/advanced_guide/inference_deployment/inference/python_infer_cn.html#id7

**Comment by ArtyZe** [comment]
也是不行的，那可能是# config = AnalysisConfig(args.model_file)这一句的问题，因为我下载的是params在一个文件夹分散的那种，所以就按照
![image](https://user-images.githubusercontent.com/32027268/86245756-88c48080-bbdc-11ea-8e8f-92917685fa0c.png)
传进去的文件夹路径，把示例代码稍微改了下，只传model_file的路径，
但是示例代码报了同样的错误
![image](https://user-images.githubusercontent.com/32027268/86245815-a0036e00-bbdc-11ea-8f62-124e8fced041.png)

**Comment by jiweibo** [comment]
> 也是不行的，那可能是# config = AnalysisConfig(args.model_file)这一句的问题，因为我下载的是params在一个文件夹分散的那种，所以就按照
> ![image](https://user-images.githubusercontent.com/32027268/86245756-88c48080-bbdc-11ea-8e8f-92917685fa0c.png)
> 传进去的文件夹路径，把示例代码稍微改了下，只传model_file的路径，
> 但是示例代码报了同样的错误
> ![image](https://user-images.githubusercontent.com/32027268/86245815-a0036e00-bbdc-11ea-8f62-124e8fced041.png)

换一下最新的paddle试一下？

**Comment by ArtyZe** [comment]
@jiweibo 已经是最新的版本，
![image](https://user-images.githubusercontent.com/32027268/86247189-b3173d80-bbde-11ea-8abc-2c631dcc5079.png)
顺便问一句，我这个问题是第一次碰到吗？ :(

**Comment by jiweibo** [comment]
> @jiweibo 已经是最新的版本，
> ![image](https://user-images.githubusercontent.com/32027268/86247189-b3173d80-bbde-11ea-8abc-2c631dcc5079.png)
> 顺便问一句，我这个问题是第一次碰到吗？ :(

在本地复现不出这个问题，很奇怪。 要不你在尝试下1.7.0-1.8.0的paddle版本？

**Comment by ArtyZe** [comment]
收到。我来试一下，刚刚下班啦，明天早起试试，多谢🙏




| |
高扬
|
|
邮箱：gaoyang917528@163.com
|

签名由 网易邮箱大师 定制

On 07/01/2020 21:17, Wilber wrote:

@jiweibo 已经是最新的版本，

顺便问一句，我这个问题是第一次碰到吗？ :(

在本地复现不出这个问题，很奇怪。 要不你在尝试下1.7.0-1.8.0的paddle版本？

**Comment by ArtyZe** [comment]
@jiweibo 您好，我觉得可能是我下载的模型和现在的paddlepaddle不匹配，
因为我直接用paddlehub的module去测试，是ok的。
![image](https://user-images.githubusercontent.com/32027268/86310982-ecd55c00-bc51-11ea-80e4-789f95d76817.png)
我下载模型的链接在这里：
```https://github.com/PaddlePaddle/paddle2onnx/blob/develop/docs/model_zoo.md```
顺便问一句，目前paddlehub上各种模型预训练模型在哪里下载呀？

**Comment by jiweibo** [comment]
> @jiweibo 您好，我觉得可能是我下载的模型和现在的paddlepaddle不匹配，
> 因为我直接用paddlehub的module去测试，是ok的。
> ![image](https://user-images.githubusercontent.com/32027268/86310982-ecd55c00-bc51-11ea-80e4-789f95d76817.png)
> 我下载模型的链接在这里：
> `https://github.com/PaddlePaddle/paddle2onnx/blob/develop/docs/model_zoo.md`
> 顺便问一句，目前paddlehub上各种模型预训练模型在哪里下载呀？

可以在models仓库下寻找合适的模型  https://github.com/PaddlePaddle/models。 paddlehub上的模型应该是训练好之后传到cdn上的

**Comment by ArtyZe** [comment]
> > @jiweibo 您好，我觉得可能是我下载的模型和现在的paddlepaddle不匹配，
> > 因为我直接用paddlehub的module去测试，是ok的。
> > ![image](https://user-images.githubusercontent.com/32027268/86310982-ecd55c00-bc51-11ea-80e4-789f95d76817.png)
> > 我下载模型的链接在这里：
> > `https://github.com/PaddlePaddle/paddle2onnx/blob/develop/docs/model_zoo.md`
> > 顺便问一句，目前paddlehub上各种模型预训练模型在哪里下载呀？
> 
> 可以在models仓库下寻找合适的模型 [https://github.com/PaddlePaddle/models。](https://github.com/PaddlePaddle/models%E3%80%82) paddlehub上的模型应该是训练好之后传到cdn上的

我下载后发现都没有__model__文件，之前我就是用的paddlecv中的infer.py来生成的，就造成了前面的错误，请问有其他的方式根据params生成__model__吗？

**Comment by jiweibo** [comment]
> > > @jiweibo 您好，我觉得可能是我下载的模型和现在的paddlepaddle不匹配，
> > > 因为我直接用paddlehub的module去测试，是ok的。
> > > ![image](https://user-images.githubusercontent.com/32027268/86310982-ecd55c00-bc51-11ea-80e4-789f95d76817.png)
> > > 我下载模型的链接在这里：
> > > `https://github.com/PaddlePaddle/paddle2onnx/blob/develop/docs/model_zoo.md`
> > > 顺便问一句，目前paddlehub上各种模型预训练模型在哪里下载呀？
> > 
> > 
> > 可以在models仓库下寻找合适的模型 [https://github.com/PaddlePaddle/models。](https://github.com/PaddlePaddle/models%E3%80%82) paddlehub上的模型应该是训练好之后传到cdn上的
> 
> 我下载后发现都没有__model__文件，之前我就是用的paddlecv中的infer.py来生成的，就造成了前面的错误，请问有其他的方式根据params生成__model__吗？

AnalysisConfig模式的预测，必须使用save_inference_model https://www.paddlepaddle.org.cn/documentation/docs/zh/api_cn/io_cn/save_inference_model_cn.html#save-inference-model  得到的预测格式模型，目前models仓库下应该没有导出预测格式模型，直接下载的是训练格式模型，但是代码中应该提供了转化方法。models仓库下预测格式模型应该会后续逐步更新。

**Comment by ArtyZe** [comment]
> > > > @jiweibo 您好，我觉得可能是我下载的模型和现在的paddlepaddle不匹配，
> > > > 因为我直接用paddlehub的module去测试，是ok的。
> > > > ![image](https://user-images.githubusercontent.com/32027268/86310982-ecd55c00-bc51-11ea-80e4-789f95d76817.png)
> > > > 我下载模型的链接在这里：
> > > > `https://github.com/PaddlePaddle/paddle2onnx/blob/develop/docs/model_zoo.md`
> > > > 顺便问一句，目前paddlehub上各种模型预训练模型在哪里下载呀？
> > > 
> > > 
> > > 可以在models仓库下寻找合适的模型 [https://github.com/PaddlePaddle/models。](https://github.com/PaddlePaddle/models%E3%80%82) paddlehub上的模型应该是训练好之后传到cdn上的
> > 
> > 
> > 我下载后发现都没有__model__文件，之前我就是用的paddlecv中的infer.py来生成的，就造成了前面的错误，请问有其他的方式根据params生成__model__吗？
> 
> AnalysisConfig模式的预测，必须使用save_inference_model https://www.paddlepaddle.org.cn/documentation/docs/zh/api_cn/io_cn/save_inference_model_cn.html#save-inference-model 得到的预测格式模型，目前models仓库下应该没有导出预测格式模型，直接下载的是训练格式模型，但是代码中应该提供了转化方法。models仓库下预测格式模型应该会后续逐步更新。

嗯嗯，多谢。其实我觉得还是有必要提供预测格式模型的，比如类似我这种其实没有训练需求而又想测一下paddle模型的话，感觉上去应该还是挺多的。
然后之前错误的地方应该是我在save model时候和infer时候输入格式不一样导致的。虽然也不太确定，毕竟core的代码都被封装起来看不到了
save:
![image](https://user-images.githubusercontent.com/32027268/86324382-1782dd00-bc71-11ea-9105-ff16b43291e1.png)
infer:
![image](https://user-images.githubusercontent.com/32027268/86324432-29648000-bc71-11ea-9f37-35798e54fe0d.png)

**Comment by jiweibo** [comment]
> > > > > @jiweibo 您好，我觉得可能是我下载的模型和现在的paddlepaddle不匹配，
> > > > > 因为我直接用paddlehub的module去测试，是ok的。
> > > > > ![image](https://user-images.githubusercontent.com/32027268/86310982-ecd55c00-bc51-11ea-80e4-789f95d76817.png)
> > > > > 我下载模型的链接在这里：
> > > > > `https://github.com/PaddlePaddle/paddle2onnx/blob/develop/docs/model_zoo.md`
> > > > > 顺便问一句，目前paddlehub上各种模型预训练模型在哪里下载呀？
> > > > 
> > > > 
> > > > 可以在models仓库下寻找合适的模型 [https://github.com/PaddlePaddle/models。](https://github.com/PaddlePaddle/models%E3%80%82) paddlehub上的模型应该是训练好之后传到cdn上的
> > > 
> > > 
> > > 我下载后发现都没有__model__文件，之前我就是用的paddlecv中的infer.py来生成的，就造成了前面的错误，请问有其他的方式根据params生成__model__吗？
> > 
> > 
> > AnalysisConfig模式的预测，必须使用save_inference_model https://www.paddlepaddle.org.cn/documentation/docs/zh/api_cn/io_cn/save_inference_model_cn.html#save-inference-model 得到的预测格式模型，目前models仓库下应该没有导出预测格式模型，直接下载的是训练格式模型，但是代码中应该提供了转化方法。models仓库下预测格式模型应该会后续逐步更新。
> 
> 嗯嗯，多谢。其实我觉得还是有必要提供预测格式模型的，比如类似我这种其实没有训练需求而又想测一下paddle模型的话，感觉上去应该还是挺多的。
> 然后之前错误的地方应该是我在save model时候和infer时候输入格式不一样导致的。虽然也不太确定，毕竟core的代码都被封装起来看不到了
> save:
> ![image](https://user-images.githubusercontent.com/32027268/86324382-1782dd00-bc71-11ea-9105-ff16b43291e1.png)
> infer:
> ![image](https://user-images.githubusercontent.com/32027268/86324432-29648000-bc71-11ea-9f37-35798e54fe0d.png)

这一块感觉有问题，save_inference_model 传入的feed，必须是训练定好的输入名字，在你这里应该是"image"吧

**Comment by ArtyZe** [comment]
> > > > > > @jiweibo 您好，我觉得可能是我下载的模型和现在的paddlepaddle不匹配，
> > > > > > 因为我直接用paddlehub的module去测试，是ok的。
> > > > > > ![image](https://user-images.githubusercontent.com/32027268/86310982-ecd55c00-bc51-11ea-80e4-789f95d76817.png)
> > > > > > 我下载模型的链接在这里：
> > > > > > `https://github.com/PaddlePaddle/paddle2onnx/blob/develop/docs/model_zoo.md`
> > > > > > 顺便问一句，目前paddlehub上各种模型预训练模型在哪里下载呀？
> > > > > 
> > > > > 
> > > > > 可以在models仓库下寻找合适的模型 [https://github.com/PaddlePaddle/models。](https://github.com/PaddlePaddle/models%E3%80%82) paddlehub上的模型应该是训练好之后传到cdn上的
> > > > 
> > > > 
> > > > 我下载后发现都没有__model__文件，之前我就是用的paddlecv中的infer.py来生成的，就造成了前面的错误，请问有其他的方式根据params生成__model__吗？
> > > 
> > > 
> > > AnalysisConfig模式的预测，必须使用save_inference_model https://www.paddlepaddle.org.cn/documentation/docs/zh/api_cn/io_cn/save_inference_model_cn.html#save-inference-model 得到的预测格式模型，目前models仓库下应该没有导出预测格式模型，直接下载的是训练格式模型，但是代码中应该提供了转化方法。models仓库下预测格式模型应该会后续逐步更新。
> > 
> > 
> > 嗯嗯，多谢。其实我觉得还是有必要提供预测格式模型的，比如类似我这种其实没有训练需求而又想测一下paddle模型的话，感觉上去应该还是挺多的。
> > 然后之前错误的地方应该是我在save model时候和infer时候输入格式不一样导致的。虽然也不太确定，毕竟core的代码都被封装起来看不到了
> > save:
> > ![image](https://user-images.githubusercontent.com/32027268/86324382-1782dd00-bc71-11ea-9105-ff16b43291e1.png)
> > infer:
> > ![image](https://user-images.githubusercontent.com/32027268/86324432-29648000-bc71-11ea-9f37-35798e54fe0d.png)
> 
> 这一块感觉有问题，save_inference_model 传入的feed，必须是训练定好的输入名字，在你这里应该是"image"吧

果然是这样，nice! 只要把tensor的名字改成'image'就ok了，原来这里必须要对应的，我还以为只要把tensor传进去就好了。真的太感谢了！那我就把issue关闭了哈，感激不尽，支持太给力了
