### ISSUE TITLE
dataprovider.py和trainer_config.py生成数据问题

### ISSUE THREAD

**Issue by ssdyue** [PaddlePaddle/Paddle#2532]
写了一个小demo，总是出错，查其原因应该是数据未能传输到模型中。想问一下：
1.读取的是csv数据格式，会有影响吗？
2.如果数据生成成功，送入到paddle，再通过data_layer函数读取出来，送到模型中，这一中间过程，如何能确定数据传输正常呢？

**Comment by lcy-seso** [comment]
- 如果使用的是v2 版本的配置，这个例子，是我用来调试配置的方法：
https://github.com/lcy-seso/models/blob/ba1c3a51e19fc23eb56ced47f6efef6431572762/nmt_without_attention/network_conf.py#L143
- 配置也是一个python脚本可以单独去测试这个配置，而不关心读取数据等部分。

读取数据也是同样道理，稍后我补充一个例子。

**Comment by ssdyue** [comment]
@lcy-seso 谢谢！我使用的是v1版本的配置，我单独测试了trainer_config.py，发现以下错误：
Traceback (most recent call last):
  File "trainer_config.py", line 15, in <module>
    obj='process')
  File "/usr/local/lib/python2.7/dist-packages/paddle/trainer_config_helpers/data_sources.py", line 213, in define_py_data_sources2
    data_cls=py_data2)
  File "/usr/local/lib/python2.7/dist-packages/paddle/trainer_config_helpers/data_sources.py", line 151, in define_py_data_sources
    train_args, train_async, data_cls)
  File "/usr/local/lib/python2.7/dist-packages/paddle/trainer_config_helpers/data_sources.py", line 87, in define_py_data_source
    async_load_data=async))
  File "/usr/local/lib/python2.7/dist-packages/paddle/trainer/config_parser.py", line 1115, in TrainData
    config_assert(not g_config.HasField('data_config'),
NameError: global name 'g_config' is not defined

我发现中间的变量是存在数据的，将input送入模型后，就报错：
[CRITICAL 2017-06-22 02:17:52,585 layer_math.py:106] At least one of the operand of '*' must be a number or a LayerOutput with size=1

后来我怀疑是模型写的有问题，就舍去paddle框架，用python单独写了这个demo，相同的input和模型，结果运行正常。

**Comment by lcy-seso** [comment]
- v1 版本应该不能这样子直接这样运行 `trainer_config.py`。
- 可以先贴一下你的报错吗，我可否直接看下现在是什么错误。

**Comment by ssdyue** [comment]
@lcy-seso 好的！./train.sh之后如下：

I0622 02:39:24.541889  3362 Util.cpp:161] commandline: /usr/bin/../opt/paddle/bin/paddle_trainer --config=trainer_config.py --dot_period=10 --log_period=100 --test_all_data_in_one_period=1 --use_gpu=0 --trainer_count=4 --num_passes=1 --save_dir=./output 
[CRITICAL 2017-06-22 02:39:24,710 layer_math.py:106] At least one of the operand of '*' must be a number or a LayerOutput with size=1
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/paddle/trainer/config_parser.py", line 3599, in parse_config_and_serialize
    config = parse_config(trainer_config, config_arg_str)
  File "/usr/local/lib/python2.7/dist-packages/paddle/trainer/config_parser.py", line 3592, in parse_config
    make_config_environment(trainer_config, config_args))
  File "trainer_config.py", line 43, in <module>
    canY = plss.comput(pc, CV, data_xx, data_yy)
  File "/home/code/v1_api_demo/demo-PLS/PLS.py", line 31, in comput
    w = np.dot(trainx.T, trainy)
  File "/usr/local/lib/python2.7/dist-packages/paddle/trainer_config_helpers/layer_math.py", line 106, in mul
    logger.fatal("At least one of the operand of '*' must be a number"
  File "/usr/local/lib/python2.7/dist-packages/paddle/trainer/config_parser.py", line 3509, in my_fatal
    raise Exception()
Exception
F0622 02:39:24.711187  3362 PythonUtil.cpp:131] Check failed: (ret) != nullptr Current PYTHONPATH: ['/usr/opt/paddle/bin', '/home/code/v1_api_demo/demo-PLS', '/usr/lib/python2.7', '/usr/lib/python2.7/plat-x86_64-linux-gnu', '/usr/lib/python2.7/lib-tk', '/usr/lib/python2.7/lib-old', '/usr/lib/python2.7/lib-dynload', '/usr/local/lib/python2.7/dist-packages', '/usr/lib/python2.7/dist-packages']
Python Error: <type 'exceptions.Exception'> : 
Python Callstack: 
            /usr/local/lib/python2.7/dist-packages/paddle/trainer/config_parser.py : 3599
            /usr/local/lib/python2.7/dist-packages/paddle/trainer/config_parser.py : 3592
            trainer_config.py : 43
            /home/code/v1_api_demo/demo-PLS/PLS.py : 31
            /usr/local/lib/python2.7/dist-packages/paddle/trainer_config_helpers/layer_math.py : 106
            /usr/local/lib/python2.7/dist-packages/paddle/trainer/config_parser.py : 3509
Call Object failed.
*** Check failure stack trace: ***
    @           0xa0f89d  google::LogMessage::Fail()
    @           0xa133e5  google::LogMessage::SendToLog()
    @           0xa0f3c3  google::LogMessage::Flush()
    @           0xa148fe  google::LogMessageFatal::~LogMessageFatal()
    @           0x948a6d  paddle::callPythonFuncRetPyObj()
    @           0x948c71  paddle::callPythonFunc()
    @           0x7e1176  paddle::TrainerConfigHelper::TrainerConfigHelper()
    @           0x7e17ed  paddle::TrainerConfigHelper::createFromFlags()
    @           0x61a526  main
    @     0x7fa7d4787f45  __libc_start_main
    @           0x6339b2  (unknown)
    @              (nil)  (unknown)
/usr/bin/paddle: line 113:  3362 Aborted                 (core dumped) ${DEBUGGER} $MYDIR/../opt/paddle/bin/paddle_trainer ${@:2}

**Comment by ssdyue** [comment]
我不明白rainer_config.py中的define_py_data_sources2（）函数，是如何运作的。查看了其源码，发现它并没有返回值。那到底数据怎么生成的呢？又怎么取出来的？

**Comment by typhoonzero** [comment]
Closing due to low activity, feel free to reopen it!
