### ISSUE TITLE
paddle编译CPU环境出错

### ISSUE THREAD

**Issue by ZSharp7** [PaddlePaddle/Paddle#25331]
GIT COMMIT ID: 0371cf6f9411d410ed4b4bb02becea23677da1ff
CPU: Intel(R) Core(TM) i7-9700 CPU @ 3.00GHz
系统环境: Ubuntu18.04  Anaconda:python37
安装方式: 本地编译
命令:
git clone https://github.com/paddlepaddle/paddle
PADDLE_ROOT=/path/of/paddle
cd Paddle
mkdir build
cd build
cmake -DFLUID_INFERENCE_INSTALL_DIR=$PADDLE_ROOT \
      -DCMAKE_BUILD_TYPE=Release \
      -DWITH_PYTHON=OFF \
      -DWITH_MKL=OFF \
      -DWITH_GPU=OFF  \
      -DON_INFER=ON \
      ..
 make

make这里出现错误, 报错信息如下
[ 98%] Linking CXX shared library libpaddle_fluid.so
/usr/bin/ld: 找不到 ../operators/libdiag_op.a: Too many open files
/usr/bin/ld: 找不到 ../operators/libdist_op.a: Too many open files
/usr/bin/ld: 找不到 ../operators/libdot_op.a: Too many open files
/usr/bin/ld: 找不到 ../operators/libdropout_op.a: Too many open files
/usr/bin/ld: 找不到 ../operators/libedit_distance_op.a: Too many open files
/usr/bin/ld: 找不到 ../operators/libenqueue_op.a: Too many open files
/usr/bin/ld: 找不到 ../operators/liberf_op.a: Too many open files
/usr/bin/ld: 找不到 ../operators/libexpand_as_op.a: Too many open files
/usr/bin/ld: 找不到 ../operators/libexpand_op.a: Too many open files
/usr/bin/ld: 找不到 ../operators/libeye_op.a: Too many open files
/usr/bin/ld: 找不到 ../operators/libfake_dequantize_op.a: Too many open files
/usr/bin/ld: 找不到 ../operators/libfake_quantize_op.a: Too many open files
/usr/bin/ld: 找不到 ../operators/libfc_op.a: Too many open files
/usr/bin/ld: 找不到 ../operators/libfill_any_like_op.a: Too many open files
/usr/bin/ld: 找不到 ../operators/libfill_constant_batch_size_like_op.a: Too many open files
/usr/bin/ld: 找不到 ../operators/libfill_constant_op.a: Too many open files
/usr/bin/ld: 找不到 ../operators/libfill_op.a: Too many open files
/usr/bin/ld: 找不到 ../operators/libfill_zeros_like_op.a: Too many open files
/usr/bin/ld: 找不到 ../operators/libfilter_by_instag_op.a: Too many open files
/usr/bin/ld: 找不到 ../operators/libflatten_op.a: Too many open files
/usr/bin/ld: 找不到 ../operators/libflip_op.a: Too many open files
/usr/bin/ld: 找不到 ../operators/libfsp_op.a: Too many open files
/usr/bin/ld: 找不到 ../operators/libgather_nd_op.a: Too many open files
/usr/bin/ld: 找不到 ../operators/libgather_op.a: Too many open files
/usr/bin/ld: 找不到 ../operators/libgather_tree_op.a: Too many open files
/usr/bin/ld: 找不到 ../operators/libgaussian_random_batch_size_like_op.a: Too many open files
/usr/bin/ld: 找不到 ../operators/libgaussian_random_op.a: Too many open files
/usr/bin/ld: 找不到 ../operators/libgelu_op.a: Too many open files
/usr/bin/ld: 找不到 ../operators/libget_tensor_from_selected_rows_op.a: Too many open files
/usr/bin/ld: 找不到 ../operators/libgrid_sampler_op.a: Too many open files
/usr/bin/ld: 找不到 ../operators/libgroup_norm_op.a: Too many open files
/usr/bin/ld: 找不到 ../operators/libgru_op.a: Too many open files
/usr/bin/ld: 找不到 ../operators/libgru_unit_op.a: Too many open files
/usr/bin/ld: 找不到 ../operators/libhash_op.a: Too many open files
/usr/bin/ld: 找不到 ../operators/libhierarchical_sigmoid_op.a: Too many open files
/usr/bin/ld: 找不到 ../operators/libhinge_loss_op.a: Too many open files
/usr/bin/ld: 找不到 ../operators/libhistogram_op.a: Too many open files
/usr/bin/ld: 找不到 ../operators/libhuber_loss_op.a: Too many open files
/usr/bin/ld: 找不到 ../operators/libim2sequence_op.a: Too many open files
/usr/bin/ld: 找不到 ../operators/libincrement_op.a: Too many open files
/usr/bin/ld: 找不到 ../operators/libindex_sample_op.a: Too many open files
/usr/bin/ld: 找不到 ../operators/libindex_select_op.a: Too many open files
/usr/bin/ld: 找不到 ../operators/libinplace_abn_op.a: Too many open files
/usr/bin/ld: 找不到 ../operators/libinstance_norm_op.a: Too many open files
/usr/bin/ld: 找不到 ../operators/libinterpolate_op.a: Too many open files
/usr/bin/ld: 找不到 ../operators/libinverse_op.a: Too many open files
/usr/bin/ld: 找不到 ../operators/libis_empty_op.a: Too many open files
/usr/bin/ld: 找不到 ../operators/libisfinite_op.a: Too many open files
/usr/bin/ld: 找不到 ../operators/libkldiv_loss_op.a: Too many open files
/usr/bin/ld: 找不到 ../operators/libkron_op.a: Too many open files
/usr/bin/ld: 找不到 ../operators/libl1_norm_op.a: Too many open files
/usr/bin/ld: 找不到 ../operators/liblabel_smooth_op.a: Too many open files
/usr/bin/ld: 找不到 ../operators/liblayer_norm_op.a: Too many open files
/usr/bin/ld: 找不到 ../operators/liblinear_chain_crf_op.a: Too many open files
/usr/bin/ld: 找不到 ../operators/liblinspace_op.a: Too many open files
/usr/bin/ld: 找不到 ../operators/libload_combine_op.a: Too many open files
/usr/bin/ld: 找不到 ../operators/libload_op.a: Too many open files
/usr/bin/ld: 找不到 ../operators/liblod_array_length_op.a: Too many open files
/usr/bin/ld: 找不到 ../operators/liblod_rank_table_op.a: Too many open files
/usr/bin/ld: 找不到 ../operators/liblod_reset_op.a: Too many open files
/usr/bin/ld: 找不到 ../operators/liblod_tensor_to_array_op.a: Too many open files
/usr/bin/ld: 找不到 ../operators/liblog_loss_op.a: Too many open files
/usr/bin/ld: 找不到 ../operators/liblookup_sparse_table_op.a: Too many open files
/usr/bin/ld: 找不到 ../operators/liblookup_table_dequant_op.a: Too many open files
/usr/bin/ld: 找不到 ../operators/liblookup_table_op.a: Too many open files
/usr/bin/ld: 找不到 ../operators/liblookup_table_v2_op.a: Too many open files
/usr/bin/ld: 找不到 ../operators/liblrn_op.a: Too many open files
/usr/bin/ld: 找不到 ../operators/liblstm_op.a: Too many open files
/usr/bin/ld: 找不到 ../operators/liblstm_unit_op.a: Too many open files
/usr/bin/ld: 找不到 ../operators/liblstmp_op.a: Too many open files
/usr/bin/ld: 找不到 ../operators/libmargin_rank_loss_op.a: Too many open files
/usr/bin/ld: 找不到 ../operators/libmatmul_op.a: Too many open files
/usr/bin/ld: 找不到 ../operators/libmax_sequence_len_op.a: Too many open files
/usr/bin/ld: 找不到 ../operators/libmaxout_op.a: Too many open files
/usr/bin/ld: 找不到 ../operators/libmean_iou_op.a: Too many open files
/usr/bin/ld: 找不到 ../operators/libmean_op.a: Too many open files
/usr/bin/ld: 找不到 ../operators/libmerge_lod_tensor_op.a: Too many open files
/usr/bin/ld: 找不到 ../operators/libmerge_selected_rows_op.a: Too many open files
/usr/bin/ld: 找不到 ../operators/libmeshgrid_op.a: Too many open files
/usr/bin/ld: 找不到 ../operators/libminus_op.a: Too many open files
/usr/bin/ld: 找不到 ../operators/libmodified_huber_loss_op.a: Too many open files
/usr/bin/ld: 找不到 ../operators/libmul_op.a: Too many open files
/usr/bin/ld: 找不到 ../operators/libmultiplex_op.a: Too many open files
/usr/bin/ld: 找不到 ../operators/libnce_op.a: Too many open files
/usr/bin/ld: 找不到 ../operators/libnll_loss_op.a: Too many open files
/usr/bin/ld: 找不到 ../operators/libnorm_op.a: Too many open files
/usr/bin/ld: 找不到 ../operators/libone_hot_op.a: Too many open files
/usr/bin/ld: 找不到 ../operators/libone_hot_v2_op.a: Too many open files
/usr/bin/ld: 找不到 ../operators/libp_norm_op.a: Too many open files
/usr/bin/ld: 找不到 ../operators/libpad2d_op.a: Too many open files
/usr/bin/ld: 找不到 ../operators/libpad_constant_like_op.a: Too many open files
/usr/bin/ld: 找不到 ../operators/libpad_op.a: Too many open files
/usr/bin/ld: 找不到 ../operators/libpartial_concat_op.a: Too many open files
/usr/bin/ld: 找不到 ../operators/libpartial_sum_op.a: Too many open files
/usr/bin/ld: 找不到 ../operators/libpixel_shuffle_op.a: Too many open files
/usr/bin/ld: 找不到 ../operators/libpool_op.a: Too many open files
/usr/bin/ld: 找不到 ../operators/libpool_with_index_op.a: Too many open files
/usr/bin/ld: 找不到 ../operators/libpositive_negative_pair_op.a: Too many open files
/usr/bin/ld: 找不到 ../operators/libprelu_op.a: Too many open files
/usr/bin/ld: 找不到 ../operators/libprint_op.a: Too many open files
/usr/bin/ld: 找不到 ../operators/libprroi_pool_op.a: Too many open files
/usr/bin/ld: 找不到 ../operators/libpsroi_pool_op.a: Too many open files
/usr/bin/ld: 找不到 ../operators/libpull_box_extended_sparse_op.a: Too many open files
/usr/bin/ld: 找不到 ../operators/libpull_box_sparse_op.a: Too many open files
/usr/bin/ld: 找不到 ../operators/libpull_sparse_op.a: Too many open files
/usr/bin/ld: 找不到 ../operators/libpull_sparse_v2_op.a: Too many open files
/usr/bin/ld: 找不到 ../operators/libpush_dense_op.a: Too many open files
/usr/bin/ld: 找不到 ../operators/libpyramid_hash_op.a: Too many open files
/usr/bin/ld: 找不到 ../operators/libquantize_op.a: Too many open files
/usr/bin/ld: 找不到 ../operators/libqueue_generator_op.a: Too many open files
/usr/bin/ld: 找不到 ../operators/librandint_op.a: Too many open files
/usr/bin/ld: 找不到 ../operators/librandom_crop_op.a: Too many open files
/usr/bin/ld: 找不到 ../operators/librandperm_op.a: Too many open files
/usr/bin/ld: 找不到 ../operators/librange_op.a: Too many open files
/usr/bin/ld: 找不到 ../operators/librank_attention_op.a: Too many open files
/usr/bin/ld: 找不到 ../operators/librank_loss_op.a: Too many open files
/usr/bin/ld: 找不到 ../operators/libreorder_lod_tensor_by_rank_op.a: Too many open files
/usr/bin/ld: 找不到 ../operators/librequantize_op.a: Too many open files
/usr/bin/ld: 找不到 ../operators/libreshape_op.a: Too many open files
/usr/bin/ld: 找不到 ../operators/libreverse_op.a: Too many open files
/usr/bin/ld: 找不到 ../operators/librnn_memory_helper_op.a: Too many open files
/usr/bin/ld: 找不到 ../operators/libroi_align_op.a: Too many open files
/usr/bin/ld: 找不到 ../operators/libroi_pool_op.a: Too many open files
/usr/bin/ld: 找不到 ../operators/libroll_op.a: Too many open files
/usr/bin/ld: 找不到 ../operators/librow_conv_op.a: Too many open files
/usr/bin/ld: 找不到 ../operators/librun_program_op.a: Too many open files
/usr/bin/ld: 找不到 ../operators/libsample_logits_op.a: Too many open files
/usr/bin/ld: 找不到 ../operators/libsampling_id_op.a: Too many open files
/usr/bin/ld: 找不到 ../operators/libsave_combine_op.a: Too many open files
/usr/bin/ld: 找不到 ../operators/libsave_op.a: Too many open files
/usr/bin/ld: 找不到 ../operators/libscale_op.a: Too many open files
/usr/bin/ld: 找不到 ../operators/libscatter_nd_add_op.a: Too many open files
/usr/bin/ld: 找不到 ../operators/libscatter_op.a: Too many open files
/usr/bin/ld: 找不到 ../operators/libseed_op.a: Too many open files
/usr/bin/ld: 找不到 ../operators/libselect_input_op.a: Too many open files
/usr/bin/ld: 找不到 ../operators/libselect_output_op.a: Too many open files
/usr/bin/ld: 找不到 ../operators/libselu_op.a: Too many open files
/usr/bin/ld: 找不到 ../operators/libshape_op.a: Too many open files
/usr/bin/ld: 找不到 ../operators/libshard_index_op.a: Too many open files
/usr/bin/ld: 找不到 ../operators/libshrink_rnn_memory_op.a: Too many open files
/usr/bin/ld: 找不到 ../operators/libshuffle_batch_op.a: Too many open files
/usr/bin/ld: 找不到 ../operators/libshuffle_channel_op.a: Too many open files
/usr/bin/ld: 找不到 ../operators/libsigmoid_cross_entropy_with_logits_op.a: Too many open files
/usr/bin/ld: 找不到 ../operators/libsign_op.a: Too many open files
/usr/bin/ld: 找不到 ../operators/libsimilarity_focus_op.a: Too many open files
/usr/bin/ld: 找不到 ../operators/libsize_op.a: Too many open files
/usr/bin/ld: 找不到 ../operators/libslice_op.a: Too many open files
/usr/bin/ld: 找不到 ../operators/libsmooth_l1_loss_op.a: Too many open files
/usr/bin/ld: 找不到 ../operators/libsoftmax_op.a: Too many open files
/usr/bin/ld: 找不到 ../operators/libsoftmax_with_cross_entropy_op.a: Too many open files
/usr/bin/ld: 找不到 ../operators/libspace_to_depth_op.a: Too many open files
/usr/bin/ld: 找不到 ../operators/libspectral_norm_op.a: Too many open files
/usr/bin/ld: 找不到 ../operators/libsplit_lod_tensor_op.a: Too many open files
/usr/bin/ld: 找不到 ../operators/libsplit_op.a: Too many open files
/usr/bin/ld: 找不到 ../operators/libsplit_selected_rows_op.a: Too many open files
/usr/bin/ld: 找不到 ../operators/libspp_op.a: Too many open files
/usr/bin/ld: 找不到 ../operators/libsquared_l2_distance_op.a: Too many open files
/usr/bin/ld: 找不到 ../operators/libsquared_l2_norm_op.a: Too many open files
/usr/bin/ld: 找不到 ../operators/libsqueeze_op.a: Too many open files
/usr/bin/ld: 找不到 ../operators/libstack_op.a: Too many open files
/usr/bin/ld: 找不到 ../operators/libstrided_slice_op.a: Too many open files
/usr/bin/ld: 找不到 ../operators/libsum_op.a: Too many open files
/usr/bin/ld: 找不到 ../operators/libtdm_child_op.a: Too many open files
/usr/bin/ld: 找不到 ../operators/libtdm_sampler_op.a: Too many open files
/usr/bin/ld: 找不到 ../operators/libteacher_student_sigmoid_loss_op.a: Too many open files
/usr/bin/ld: 找不到 ../operators/libtemporal_shift_op.a: Too many open files
/usr/bin/ld: 找不到 ../operators/libtensor_array_to_tensor_op.a: Too many open files
/usr/bin/ld: 找不到 ../operators/libtop_k_op.a: Too many open files
/usr/bin/ld: 找不到 ../operators/libtrace_op.a: Too many open files
/usr/bin/ld: 找不到 ../operators/libtranspose_op.a: Too many open files
/usr/bin/ld: 找不到 ../operators/libtree_conv_op.a: Too many open files
/usr/bin/ld: 找不到 ../operators/libtril_triu_op.a: Too many open files
/usr/bin/ld: 找不到 ../operators/libtruncated_gaussian_random_op.a: Too many open files
/usr/bin/ld: 找不到 ../operators/libunbind_op.a: Too many open files
/usr/bin/ld: 找不到 ../operators/libunfold_op.a: Too many open files
/usr/bin/ld: 找不到 ../operators/libuniform_random_batch_size_like_op.a: Too many open files
/usr/bin/ld: 找不到 ../operators/libuniform_random_op.a: Too many open files
/usr/bin/ld: 找不到 ../operators/libunique_op.a: Too many open files
/usr/bin/ld: 找不到 ../operators/libunique_with_counts_op.a: Too many open files
/usr/bin/ld: 找不到 ../operators/libunpool_op.a: Too many open files
/usr/bin/ld: 找不到 ../operators/libunsqueeze_op.a: Too many open files
/usr/bin/ld: 找不到 ../operators/libunstack_op.a: Too many open files
/usr/bin/ld: 找不到 ../operators/libwhere_index_op.a: Too many open files
/usr/bin/ld: 找不到 ../operators/libwhere_op.a: Too many open files
/usr/bin/ld: 找不到 ../operators/libwarpctc_op.a: Too many open files
/usr/bin/ld: 找不到 ../platform/dynload/libdynload_warpctc.a: Too many open files
/usr/bin/ld: 找不到 ../platform/dynload/libdynamic_loader.a: Too many open files
/usr/bin/ld: 找不到 ../operators/math/libsequence_padding.a: Too many open files
/usr/bin/ld: 找不到 ../operators/math/libsequence_scale.a: Too many open files
/usr/bin/ld: 找不到 ../operators/libtensor_formatter.a: Too many open files
/usr/bin/ld: 找不到 ../operators/jit/libjit_kernel_helper.a: Too many open files
/usr/bin/ld: 找不到 ../operators/jit/refer/libjit_kernel_refer.a: Too many open files
/usr/bin/ld: 找不到 ../operators/jit/more/intrinsic/libjit_kernel_intrinsic.a: Too many open files
/usr/bin/ld: 找不到 ../operators/jit/more/mix/libjit_kernel_mix.a: Too many open files
/usr/bin/ld: 找不到 ../operators/jit/gen/libjit_kernel_jitcode.a: Too many open files
/usr/bin/ld: 找不到 ../operators/jit/libjit_kernel_base.a: Too many open files
/usr/bin/ld: 找不到 ../framework/libpaddle_framework.a: Too many open files
/usr/bin/ld: 找不到 ../framework/libexecutor.a: Too many open files
/usr/bin/ld: 找不到 ../operators/controlflow/librecurrent_op_helper.a: Too many open files
/usr/bin/ld: 找不到 ../operators/librecurrent_op.a: Too many open files
/usr/bin/ld: 找不到 ../framework/libexecutor.a: Too many open files
/usr/bin/ld: 找不到 ../operators/controlflow/librecurrent_op_helper.a: Too many open files
/usr/bin/ld: 找不到 ../operators/librecurrent_op.a: Too many open files
/usr/bin/ld: 找不到 ../platform/libmonitor.a: Too many open files
/usr/bin/ld: 找不到 ../platform/liblodtensor_printer.a: Too many open files
/usr/bin/ld: 找不到 ../framework/fleet/libfleet_wrapper.a: Too many open files
/usr/bin/ld: 找不到 ../framework/fleet/libbox_wrapper.a: Too many open files
/usr/bin/ld: 找不到 ../framework/io/libfs.a: Too many open files
/usr/bin/ld: 找不到 ../framework/io/libshell.a: Too many open files
/usr/bin/ld: 找不到 ../platform/libtimer.a: Too many open files
/usr/bin/ld: 找不到 ../string/libstring_helper.a: Too many open files
/usr/bin/ld: 找不到 ../framework/libexecutor_gc_helper.a: Too many open files
/usr/bin/ld: 找不到 ../framework/libgarbage_collector.a: Too many open files
/usr/bin/ld: 找不到 ../operators/controlflow/libconditional_block_op_helper.a: Too many open files
/usr/bin/ld: 找不到 ../operators/controlflow/libconditional_block_op.a: Too many open files
/usr/bin/ld: 找不到 ../framework/libnaive_executor.a: Too many open files
/usr/bin/ld: 找不到 ../framework/ir/libgraph_to_program_pass.a: Too many open files
/usr/bin/ld: 找不到 ../framework/ir/libgraph_pattern_detector.a: Too many open files
/usr/bin/ld: 找不到 ../framework/ir/libgraph_traits.a: Too many open files
/usr/bin/ld: 找不到 ../framework/ir/libfuse_pass_base.a: Too many open files
/usr/bin/ld: 找不到 ../framework/ir/libpass.a: Too many open files
/usr/bin/ld: 找不到 ../framework/ir/libgraph_helper.a: Too many open files
/usr/bin/ld: 找不到 ../framework/ir/libgraph.a: Too many open files
/usr/bin/ld: 找不到 ../framework/ir/libnode.a: Too many open files
/usr/bin/ld: 找不到 ../string/libpretty_log.a: Too many open files
/usr/bin/ld: 找不到 ../framework/liblod_rank_table.a: Too many open files
/usr/bin/ld: 找不到 ../framework/libfeed_fetch_method.a: Too many open files
/usr/bin/ld: 找不到 ../operators/controlflow/libwhile_op_helper.a: Too many open files
/usr/bin/ld: 找不到 ../operators/controlflow/libop_variant.a: Too many open files
/usr/bin/ld: 找不到 ../imperative/liblayer.a: Too many open files
/usr/bin/ld: 找不到 ../framework/libop_registry.a: Too many open files
/usr/bin/ld: 找不到 ../framework/libvariable_helper.a: Too many open files
/usr/bin/ld: 找不到 ../imperative/libimperative_flag.a: Too many open files
/usr/bin/ld: 找不到 ../imperative/libprepared_operator.a: Too many open files
/usr/bin/ld: 找不到 analysis/libanalysis_pass.a: Too many open files
/usr/bin/ld: 找不到 ../framework/libproto_desc.a: Too many open files
/usr/bin/ld: 找不到 ../framework/liboperator.a: Too many open files
/usr/bin/ld: 找不到 ../framework/details/libnan_inf_utils.a: Too many open files
/usr/bin/ld: 找不到 ../framework/libdata_transform.a: Too many open files
/usr/bin/ld: 找不到 ../framework/libdata_device_transform.a: Too many open files
/usr/bin/ld: 找不到 ../framework/libdata_type_transform.a: Too many open files
/usr/bin/ld: 找不到 ../framework/libdata_layout_transform.a: Too many open files
/usr/bin/ld: 找不到 ../operators/math/libmath_function.a: Too many open files
/usr/bin/ld: 找不到 ../operators/math/libblas.a: Too many open files
/usr/bin/ld: 找不到 ../framework/libop_info.a: Too many open files
/usr/bin/ld: 找不到 ../framework/libshape_inference.a: Too many open files
/usr/bin/ld: 找不到 ../framework/libtransfer_scope_cache.a: Too many open files
/usr/bin/ld: 找不到 ../framework/libop_kernel_type.a: Too many open files
/usr/bin/ld: 找不到 ../framework/libunused_var_check.a: Too many open files
/usr/bin/ld: 找不到 ../framework/libno_need_buffer_vars_inference.a: Too many open files
/usr/bin/ld: 找不到 ../framework/libop_call_stack.a: Too many open files
/usr/bin/ld: 找不到 ../framework/libop_proto_maker.a: Too many open files
/usr/bin/ld: 找不到 ../framework/libattribute.a: Too many open files
/usr/bin/ld: 找不到 api/libpaddle_inference_api.a: Too many open files
/usr/bin/ld: 找不到 ../framework/libtrainer_desc_proto.a: Too many open files
/usr/bin/ld: 找不到 ../framework/libdata_feed_proto.a: Too many open files
/usr/bin/ld: 找不到 api/details/libzero_copy_tensor.a: Too many open files
/usr/bin/ld: 找不到 api/details/libreset_tensor_array.a: Too many open files
/usr/bin/ld: 找不到 ../framework/libscope.a: Too many open files
/usr/bin/ld: 找不到 ../framework/libthreadpool.a: Too many open files
/usr/bin/ld: 找不到 ../framework/libvar_type_traits.a: Too many open files
/usr/bin/ld: 找不到 ../framework/libselected_rows.a: Too many open files
/usr/bin/ld: 找不到 api/libanalysis_config.a: Too many open files
/usr/bin/ld: 找不到 ../framework/liblod_tensor.a: Too many open files
/usr/bin/ld: 找不到 ../framework/libtensor.a: Too many open files
/usr/bin/ld: 找不到 ../framework/libdata_type.a: Too many open files
/usr/bin/ld: 找不到 ../platform/libdevice_context.a: Too many open files
/usr/bin/ld: 找不到 ../platform/libcpu_helper.a: Too many open files
/usr/bin/ld: 找不到 ../../../libcblas.a: Too many open files
/usr/bin/ld: 找不到 ../../../third_party/install/openblas/lib/libopenblas.a: Too many open files
/usr/bin/ld: 找不到 ../platform/libcudnn_workspace_helper.a: Too many open files
/usr/bin/ld: 找不到 ../string/libstringpiece.a: Too many open files
/usr/bin/ld: 找不到 ../../../third_party/install/xxhash/lib/libxxhash.a: Too many open files
/usr/bin/ld: 找不到 ../framework/libddim.a: Too many open files
/usr/bin/ld: 找不到 ../memory/libmemory.a: Too many open files
/usr/bin/ld: 找不到 ../memory/libmalloc.a: Too many open files
/usr/bin/ld: 找不到 ../memory/allocation/liballocator_facade.a: Too many open files
/usr/bin/ld: 找不到 ../memory/allocation/liballocator_strategy.a: Too many open files
/usr/bin/ld: 找不到 ../memory/allocation/libcpu_allocator.a: Too many open files
/usr/bin/ld: 找不到 ../memory/allocation/liblocked_allocator.a: Too many open files
/usr/bin/ld: 找不到 ../memory/allocation/libbuffered_allocator.a: Too many open files
/usr/bin/ld: 找不到 ../memory/allocation/libbest_fit_allocator.a: Too many open files
/usr/bin/ld: 找不到 ../memory/allocation/libnaive_best_fit_allocator.a: Too many open files
/usr/bin/ld: 找不到 ../memory/detail/libbuddy_allocator.a: Too many open files
/usr/bin/ld: 找不到 ../memory/detail/libmemory_block.a: Too many open files
/usr/bin/ld: 找不到 ../memory/detail/libsystem_allocator.a: Too many open files
/usr/bin/ld: 找不到 ../platform/libcpu_info.a: Too many open files
/usr/bin/ld: 找不到 ../memory/allocation/libretry_allocator.a: Too many open files
/usr/bin/ld: 找不到 ../memory/allocation/libauto_growth_best_fit_allocator.a: Too many open files
/usr/bin/ld: 找不到 ../memory/allocation/libaligned_allocator.a: Too many open files
/usr/bin/ld: 找不到 ../memory/allocation/liballocator.a: Too many open files
/usr/bin/ld: 找不到 ../platform/libprofiler.a: Too many open files
/usr/bin/ld: 找不到 ../platform/libdevice_tracer.a: Too many open files
/usr/bin/ld: 找不到 ../platform/libprofiler_proto.a: Too many open files
/usr/bin/ld: 找不到 ../framework/libframework_proto.a: Too many open files
/usr/bin/ld: 找不到 ../memory/libmemcpy.a: Too many open files
/usr/bin/ld: 找不到 ../platform/libplace.a: Too many open files
/usr/bin/ld: 找不到 ../platform/libenforce.a: Too many open files
/usr/bin/ld: 找不到 ../platform/libflags.a: Too many open files
/usr/bin/ld: 找不到 ../platform/liberrors.a: Too many open files
/usr/bin/ld: 找不到 ../platform/liberror_codes_proto.a: Too many open files
/usr/bin/ld: 找不到 ../../../third_party/install/protobuf/lib/libprotobuf.a: Too many open files
/usr/bin/ld: 找不到 ../framework/libversion.a: Too many open files
/usr/bin/ld: 找不到 api/libpaddle_pass_builder.a: Too many open files
/usr/bin/ld: 找不到 -lpthread
/usr/bin/ld: 找不到 ../../../third_party/install/glog/lib/libglog.a: Too many open files
/usr/bin/ld: 找不到 ../../../third_party/install/gflags/lib/libgflags.a: Too many open files
/usr/bin/ld: 找不到 -lstdc++
/usr/bin/ld: 找不到 -lm
/usr/bin/ld: 找不到 -lgcc_s
/usr/bin/ld: 找不到 -lc
/usr/bin/ld: 找不到 -lgcc_s
/usr/bin/ld: 找不到 /usr/lib/gcc/x86_64-linux-gnu/7/crtendS.o: Too many open files
/usr/bin/ld: 找不到 /usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/crtn.o: Too many open files
collect2: error: ld returned 1 exit status
paddle/fluid/inference/CMakeFiles/paddle_fluid_shared.dir/build.make:1498: recipe for target 'paddle/fluid/inference/libpaddle_fluid.so' failed
make[2]: *** [paddle/fluid/inference/libpaddle_fluid.so] Error 1
CMakeFiles/Makefile2:71110: recipe for target 'paddle/fluid/inference/CMakeFiles/paddle_fluid_shared.dir/all' failed
make[1]: *** [paddle/fluid/inference/CMakeFiles/paddle_fluid_shared.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by OliverLPH** [comment]
`ulimit -n 4096` 后再试下

**Comment by ZSharp7** [comment]
> `ulimit -n 4096` 后再试下

谢谢，问题已解决：增加系统同一时间最多可开启的文件数至2048
ulimit -n 2048
