### ISSUE TITLE
输入参数乘算出错？TypeError: matmul(): incompatible function arguments. The following argument types are supported:

### ISSUE THREAD

**Issue by Reatris** [PaddlePaddle/Paddle#25343]
1）PaddlePaddle版本：Python版本python3.7  框架版本PaddlePaddle 1.7.1
请问这是什么错误
---------------------------------------------------------------------------TypeError                                 Traceback (most recent call last)<ipython-input-21-e43a997ef626> in <module>

---> 49             `predict = model(temp_images)`
     50             loss = fluid.layers.cross_entropy(labels)
     51             print(loss)
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py in __call__(self, *inputs, **kwargs)
    302             self._built = True
    303 
--> 304         `outputs = self.forward(*inputs, **kwargs)`
    305         return outputs
    306 
<ipython-input-21-e43a997ef626> in forward(self, x)
     19         self.fc1=fluid.dygraph.Linear(input_dim=50,output_dim=10,act='softmax')
     20     def forward(self,x):
---> 21         `x=self.fc(x)`
     22         x=self.fc1(x)
     23         return x
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py in __call__(self, *inputs, **kwargs)
    302             self._built = True
    303 
--> 304         `outputs = self.forward(*inputs, **kwargs)`
    305         return outputs
    306 
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/nn.py in forward(self, input)
    930 
    931         if in_dygraph_mode():
--> 932             `outs = core.ops.matmul(inputs, attrs)`
    933             pre_bias = outs['Out'][0]
    934 

---------------------------------------------------------------------------
TypeError: `matmul(): incompatible function arguments.` The following argument types are supported:
    1. (ins: Dict[str, List[paddle::imperative::VarBase]], attrs: Dict[str, Variant]={}, outs: Dict[str, List[paddle::imperative::VarBase]]={}, out_nums: Dict[str, int]={}) -> Dict[str, List[paddle::imperative::VarBase]]

Invoked with: {'X': [[array([-1.        , -1.        , -1.        , -1.        , -1.     
......
-1.        , -1.        , -1.        , -1.        ,    -1.        , -1.        , -1.        , -1.        ], dtype=float32)]], 
'Y': [name linear_0.w_0, dtype: VarType.FP32 shape: [784, 50] 	lod: {}
	dim: 784, 50
	layout: NCHW
	dtype: float
	data: [0.0791148 0.0628832 -0.0651603 0.0708175 0.0624304 -0.0393643 -0.0419662 0.0626356 0.0291683 -0.00854877 0.0708964 -0.0317977 -0.0239402 -0.0427557 -0.0488643 0.0834179 -0.0267296 -0.0020321 -0.040666 0.0586545 0.0576743 0.0701685 -0.0541784 0.0582303 -0.063577 -0.00766291 0.0837438 -0.0739571 0.0451067 0.0447801 0.0545819 0.0764028 -0.055833 -0.0796971 -0.0110985 -0.0216742 -0.0788903 0.083344 -0.0304876 -0.056753 -0.0413164 0.0463192 0.0490344 -0.0169836 0.045074 -0.0053713 -0.0716594 0.0147961 0.0483962 0.0490969 -0.0546428 0.033084 0.0264729 -0.00659643 
.......
-0.0246536 -0.0425563 0.0768273 0.0810787 0.0368573 -0.0209188 0.0846459 0.0489126 0.0403826 -0.000357052 0.0677768 0.0181675 -0.06574 0.0761544 -8.91959e-05 -0.064635 -0.0173932 -0.050497 -0.0173943]
]}, {'transpose_X': False, 'transpose_Y': False, 'alpha': 1} `

**Comment by gfwm2013** [comment]
@Reatris 根据log来看，应该是`matmul`输入的类型有问题，应该放入`VarBase`类型的变量，却放入了numpy的数组。可以尝试使用`to_variable`接口，将numpy数组转成`VarBase`类型的变量之后再进行`matmul`操作。

**Comment by Reatris** [comment]
@gfwm2013 解决了
