### ISSUE TITLE
启动训练总是有个info信息，能解释一下这是什么情况会触发这样的信息

### ISSUE THREAD

**Issue by BeyondYourself** [PaddlePaddle/Paddle#25344]
在启动训练的时候，日志中第一个出现的info信息为：
`If regularizer of a Parameter has been set by 'fluid.ParamAttr' or 'fluid.WeightNormParamAttr' already. The Regularization[L2Decay, regularization_coeff=0.000100] in Optimizer will not take effect, and it will only be applied to other Parameters!`
什么情况会触发上述的信息，还是只是一个info，能说明一下上面info的意思吗，谢谢

**Comment by gfwm2013** [comment]
@BeyondYourself 在Paddle中，参数的正则化器共能在两个地方设置，一是在某层中通过`ParamAttr`设置，另一个是通过优化器中的正则化统一设置。前者的优先级要高于后者，如果用户在某层已经通过`'fluid.ParamAttr'`等设置过了参数，那么在优化器中的正则化配置就不会对其生效。该info就是对这种情况的一个描述。

**Comment by BeyondYourself** [comment]
明白，谢谢答复
