### ISSUE TITLE
python script hangs when trainer_count > 1 and call trainer.train() more than once.

### ISSUE THREAD

**Issue by juliecbd** [PaddlePaddle/Paddle#2534]
import paddle.v2 as paddle
paddle.init(use_gpu=False, trainer_count=2)

if we set trainer_count > 1, and call trainer.train() more than one time, then the program just hangs. If we set trainer_count=1, the script runs as expected. What could be the reason? Thanks

**Comment by lcy-seso** [comment]
I have met the same bug https://github.com/PaddlePaddle/Paddle/issues/2565.

**Comment by jacquesqiao** [comment]
just to confirm. is it hang when paddle.trian or paddle.infer? Because @lcy-seso meet a similar problem when calling paddle.infer multiple times

**Comment by juliecbd** [comment]
Mine is when train()

**Comment by jacquesqiao** [comment]
thx，can you paste or give a demo to reproduce the problem?

**Comment by juliecbd** [comment]
Yes, just simply

import paddle.v2 as paddle
import paddle.v2.dataset.uci_housing as uci_housing


def main():
    # init
    paddle.init(use_gpu=False, trainer_count=2)

    # network config
    x = paddle.layer.data(name='x', type=paddle.data_type.dense_vector(13))
    y_predict = paddle.layer.fc(input=x, size=1, act=paddle.activation.Linear())
    y = paddle.layer.data(name='y', type=paddle.data_type.dense_vector(1))
    cost = paddle.layer.mse_cost(input=y_predict, label=y)

    # create parameters
    parameters = paddle.parameters.create(cost)

    # create optimizer
    optimizer = paddle.optimizer.Momentum(momentum=0)

    trainer = paddle.trainer.SGD(
        cost=cost, parameters=parameters, update_equation=optimizer)

    feeding = {'x': 0, 'y': 1}

    # event_handler to print training and testing info
    def event_handler(event):
        if isinstance(event, paddle.event.EndIteration):
            if event.batch_id % 100 == 0:
                print "Pass %d, Batch %d, Cost %f" % (
                    event.pass_id, event.batch_id, event.cost)

        if isinstance(event, paddle.event.EndPass):
            result = trainer.test(
                reader=paddle.batch(uci_housing.test(), batch_size=2),
                feeding=feeding)
            print "Test %d, Cost %f" % (event.pass_id, result.cost)

    # training
    trainer.train(
        reader=paddle.batch(
            paddle.reader.shuffle(uci_housing.train(), buf_size=500),
            batch_size=2),
        feeding=feeding,
        event_handler=event_handler,
        num_passes=30)

    trainer.train(
        reader=paddle.batch(
            paddle.reader.shuffle(uci_housing.train(), buf_size=500),
            batch_size=2),
        feeding=feeding,
        event_handler=event_handler,
        num_passes=30)


if __name__ == '__main__':
    main()

**Comment by jacquesqiao** [comment]
thanx, I reproduced this problem with your demo. It's very strange, I will have a look.

**Comment by juliecbd** [comment]
Thank you
