### ISSUE TITLE
fatal error: crypto/cipher.h

### ISSUE THREAD

**Issue by pmajchrzak** [PaddlePaddle/Paddle#25348]
Seems that this commit: 
https://github.com/PaddlePaddle/Paddle/commit/3b8f0a64c2e71d6bfa748b90d214e1f97159a5c1
causes CMake build error:
```
Scanning dependencies of target inference
[ 50%] Building CXX object CMakeFiles/inference.dir/inference.cc.o
In file included from /repos/paddle_paddle/build/fluid_install_dir/paddle/fluid/inference/paddle_analysis_config.h:39:0,
                 from /repos/paddle_paddle/build/fluid_install_dir/paddle/fluid/inference/paddle_inference_api.h:29,
                 from /root/models/benchmark/Inference/c++/ernie/inference.cc:26:
/repos/paddle_paddle/build/fluid_install_dir/paddle/fluid/inference/paddle_api.h:30:27: fatal error: crypto/cipher.h: No such file or directory
compilation terminated.
```

this error applies build_CAPI_ernie  (/root/models/benchmark/Inference/c++/ernie/)
`cmake .. -DPADDLE_ROOT=/repos/paddle_paddle/build/fluid_install_dir -DUSE_GPU=OFF`

**Comment by luotao1** [comment]
@Yanghello @Shixiaowei02 Could you help see it?

**Comment by MRXLT** [comment]
hi, did you compile with the code of the develop branch?  I can't reproduce this error

**Comment by pmajchrzak** [comment]
I’m sorry – my mistake
this error applies build_CAPI_ernie  (/root/models/benchmark/Inference/c++/ernie/)

cmake .. -DPADDLE_ROOT=/repos/paddle_paddle/build/fluid_install_dir -DUSE_GPU=OFF

**Comment by luotao1** [comment]
@MRXLT `benchmark/Inference/c++/ernie/` is this file: https://github.com/PaddlePaddle/benchmark/tree/master/Inference/c%2B%2B/ernie

**Comment by MRXLT** [comment]
if you want to compile with inference library, please set -DPADDLE_ROOT=/repos/paddle_paddle/build/fluid_inference_install_dir

**Comment by pmajchrzak** [comment]
Yeah! Thank You,

Seems to me that this problem is solved wit this suggestion.
Thank You very much!

**Comment by lidanqing-vv** [comment]
Issue does not exist any more
