### ISSUE TITLE
咨询dataloader的batchsize

### ISSUE THREAD

**Issue by houj04** [PaddlePaddle/Paddle#25353]
请参考附件。需要将run.txt改成run.sh，其余两个文件改成py。然后直接执行run.sh就可以了，只依赖paddle以及paddle自己的数据集。

[no_loader.txt](https://github.com/PaddlePaddle/Paddle/files/4864218/no_loader.txt)
[run.txt](https://github.com/PaddlePaddle/Paddle/files/4864219/run.txt)
[loader.txt](https://github.com/PaddlePaddle/Paddle/files/4864220/loader.txt)

背景：我在看dataloader，发现dataloader在不同的卡数的时候，batchsize好像不一样（其实是表现出来的step数不一致）。

作为对比，我写了上面的代码。该shell脚本会用4种方式直接运行，我在训练的一个epoch里面会打印经过了多少个batch。

运行发现，当不使用dataloader的时候，用1个卡或者2个卡，打印出来的count数是一致的。而用了dataloader以后，跑1个卡和2个卡，实际数出来的count数不同。

请问这个是否符合预期：不用dataloader的情况下，不管用几个卡，实际的进行的step数都一样。而用了dataloader的情况下，用不同的卡数，实际进行的step数不一样。

据了解batchsize或者step数，是对收敛有影响的。所以个人感觉“不受卡数影响”更好一些，即no_loader.py里面更好。请帮忙看下，thx~

**Comment by chenwhql** [comment]
同学你好，你这个两个示例程序的batch size不一样，造成这个count差的比较大，no_loader的batch size是128，loader的batch size是512，把loader的batch size改成和no_loader一致，测试结果就可以理解了，更改如下：

```
train_loader.set_sample_list_generator(
    # fluid.io.shuffle(fluid.io.batch(mnist.train(), 512), buf_size=1024), places=places)
    fluid.io.shuffle(fluid.io.batch(mnist.train(), 128), buf_size=1024), places=places)

# test_loader.set_sample_list_generator(fluid.io.batch(mnist.test(), 512), places=places)
test_loader.set_sample_list_generator(fluid.io.batch(mnist.test(), 128), places=places)
```

执行结果如下：

```
+ echo 'run no loader on gpu 0'
run no loader on gpu 0
+ export CUDA_VISIBLE_DEVICES=0
+ CUDA_VISIBLE_DEVICES=0
+ python -u no_loader.py
grep: warning: GREP_OPTIONS is deprecated; please use an alias or script
W0703 03:57:53.853716 13763 device_context.cc:265] Please NOTE: device: 0, CUDA Capability: 61, Driver API Version: 10.1, Runtime API Version: 10.1
W0703 03:57:53.860872 13763 device_context.cc:273] device: 0, cuDNN Version: 7.6.
count is 469
share_vars_from is set, scope is ignored.
count is 79

+ echo 'run no loader on gpu 0,1'
run no loader on gpu 0,1
+ export CUDA_VISIBLE_DEVICES=0,1
+ CUDA_VISIBLE_DEVICES=0,1
+ python -u no_loader.py
grep: warning: GREP_OPTIONS is deprecated; please use an alias or script
W0703 03:58:08.082657 13860 device_context.cc:265] Please NOTE: device: 0, CUDA Capability: 61, Driver API Version: 10.1, Runtime API Version: 10.1
W0703 03:58:08.089797 13860 device_context.cc:273] device: 0, cuDNN Version: 7.6.
W0703 03:58:19.350443 13860 fuse_all_reduce_op_pass.cc:74] Find all_reduce operators: 4. To make the speed faster, some all_reduce ops are fused during training, after fusion, the number of all_reduce ops is 2.
count is 469
share_vars_from is set, scope is ignored.
count is 79

+ echo 'run loader on gpu 0'
run loader on gpu 0
+ export CUDA_VISIBLE_DEVICES=0
+ CUDA_VISIBLE_DEVICES=0
+ python -u loader.py
grep: warning: GREP_OPTIONS is deprecated; please use an alias or script
W0703 03:58:30.684342 13978 device_context.cc:265] Please NOTE: device: 0, CUDA Capability: 61, Driver API Version: 10.1, Runtime API Version: 10.1
W0703 03:58:30.691524 13978 device_context.cc:273] device: 0, cuDNN Version: 7.6.
count is 469
share_vars_from is set, scope is ignored.
count is 79

+ echo 'run loader on gpu 0,1'
run loader on gpu 0,1
+ export CUDA_VISIBLE_DEVICES=0,1
+ CUDA_VISIBLE_DEVICES=0,1
+ python -u loader.py
grep: warning: GREP_OPTIONS is deprecated; please use an alias or script
W0703 03:58:46.206509 14081 device_context.cc:265] Please NOTE: device: 0, CUDA Capability: 61, Driver API Version: 10.1, Runtime API Version: 10.1
W0703 03:58:46.214440 14081 device_context.cc:273] device: 0, cuDNN Version: 7.6.
W0703 03:59:00.838776 14081 fuse_all_reduce_op_pass.cc:74] Find all_reduce operators: 2. To make the speed faster, some all_reduce ops are fused during training, after fusion, the number of all_reduce ops is 1.
count is 234
share_vars_from is set, scope is ignored.
count is 39
```

这时候如果是单卡的话，无论是否使用DataLoader，count都是一样的
如果是多卡，使用DataLoader是不使用DataLoader的1/2，这个我解释下：
- 多卡你要普通reader话，你feed的数据是会被均分给多卡的，比如这里你的batch size是128，那你用普通reader两卡，每张卡的batch size是的64
- 但多卡用DataLoader，DataLoader是异步读取，每次都会读取一个128 batch size的数据，每张卡都会去DataLoader的队列里，取一个128 batch size的数据训练，这时候每张卡的batch size仍然是128，总的batch size是256，这并不会影响收敛，等价于你用普通reader设置batch size 256
- 如果你一定要保证多卡使用DataLoader的count和普通reader一致，把用DataLoader的情况，batch size除以卡数

**Comment by houj04** [comment]
解释非常清楚，多谢多谢~

**Comment by houj04** [comment]
mnist数据集的训练集是6w个，测试集是1w。当单卡的时候，step数是6w/128=468.75，以及1w/128=78.125，实际跑出来是469和79。
当两个卡的时候，step数是6w/256=234.375，以及1w/256=39.0625，实际跑出来是234和39
为啥单卡的时候，是向上取整，而两个卡的时候，是向下取整呢？

**Comment by chenwhql** [comment]
batch size是可变参数，对于最后一个不足batch size128的数据，单卡也是能正常训练的

但是多卡不是这样，多卡每张卡算完是要做梯度同步，要确保两张卡上输入数据的batch size是一样的，所以按照前面说的原理，使用DataLoader的话，训练一轮需要两个完整的batch，就是两个128的batch，这样两张卡才能都有数据，才能同步

所以，默认情况下，DataLoader会丢弃最后不足卡数的bach，也只能丢弃

但如果是使用DataLoader多卡预测，预测时每张卡算完不需要同步，这时候，剩余的不完整数据其实可以被使用，所以DataLoader有个参数：drop_last(1.8以上版本)，预测的话

![image](https://user-images.githubusercontent.com/22561442/86471724-7d09c300-bd70-11ea-993a-fad0e0e265ed.png)
