### ISSUE TITLE
能否在服务器arm64架构上编译和使用

### ISSUE THREAD

**Issue by hargrovee** [PaddlePaddle/Paddle#25362]
各位，目前paddle是否支持arm64架构，能在arm64平台上编译和使用吗？

**Comment by DannyIsFunny** [comment]
当前未发布该功能，但是已经在开发该部分功能，可以参考这个PR修改实现编译，该部分代码当前在飞腾机器上验证过，其它处理器 还需要在验证：
https://github.com/PaddlePaddle/Paddle/pull/25212
![image](https://user-images.githubusercontent.com/45189361/86441080-3a2ef780-bd3e-11ea-8a2d-a13910bc0165.png)
