### ISSUE TITLE
分布式训练，效果的稳定性

### ISSUE THREAD

**Issue by leesusu** [PaddlePaddle/Paddle#25365]
请教个问题，全异步分布式训练，启动多个设置一模一样的训练任务，数据量也足够，这几个任务中，最大和最小的训练AUC差别较大，同样测试AUC也差别较大。除了选用效果最好的训练结果，还有其他办法吗？这个差异在异步训练里是正常的吗？谢谢🙏

**Comment by MrChengmo** [comment]
这个差异是不正常的，若正常训练收敛，在测试集上的auc相差不会很大。

相同实验设置测试集差异很大，可以从以下方面排查下：

- 集群环境的稳定性，不同节点间速度差异过大会影响模型收敛速度

- 数据是否被均匀分配和充分打乱

- 模型是否训练到收敛（排查下batchsize，学习率等因素）

**Comment by leesusu** [comment]
1. 应该不是节点差异，我们这边集群机器是同样的配置
2. 应该不是数据均匀分配，这边数据在hdfs分类上千个part，trainer个数远低于part数
3. 模型是否收敛，这个应该是收敛了，几个月的训练数据

但是batchsize我们比较小，lr比较大可能是个原因，但是这2个我们作为超参调的，保证最终测试AUC比较好

现在我对比2个任务，发现一开始如果训练AUC落后的话，后面基本上就稳定落后，我给你看下前期训练AUC对比：

0.522752	0.524962
0.563906	0.520216
0.596323	0.513046
0.631872	0.509045
0.655556	0.518995
0.677614	0.532329
0.689702	0.541053
0.701943	0.546135
0.710672	0.554792
0.718161	0.562764
0.724464	0.569153
0.728916	0.576337
0.733738	0.582945
0.738071	0.588043
0.741583	0.593901
0.745159	0.597861
0.748928	0.600805
0.751675	0.604279
0.754285	0.607994
0.756663	0.612207

这是print_period=10的时候打印的

直觉上，前期AUC追不上，后期就追不上了，测试AUC也就高不了，但是就有些玄学和麻烦，要手动挑前期训练AUC表现好的

**Comment by MrChengmo** [comment]
> 1. 应该不是节点差异，我们这边集群机器是同样的配置
> 2. 应该不是数据均匀分配，这边数据在hdfs分类上千个part，trainer个数远低于part数
> 3. 模型是否收敛，这个应该是收敛了，几个月的训练数据
> 
> 但是batchsize我们比较小，lr比较大可能是个原因，但是这2个我们作为超参调的，保证最终测试AUC比较好
> 
> 现在我对比2个任务，发现一开始如果训练AUC落后的话，后面基本上就稳定落后，我给你看下前期训练AUC对比：
> 
> 0.522752	0.524962
> 0.563906	0.520216
> 0.596323	0.513046
> 0.631872	0.509045
> 0.655556	0.518995
> 0.677614	0.532329
> 0.689702	0.541053
> 0.701943	0.546135
> 0.710672	0.554792
> 0.718161	0.562764
> 0.724464	0.569153
> 0.728916	0.576337
> 0.733738	0.582945
> 0.738071	0.588043
> 0.741583	0.593901
> 0.745159	0.597861
> 0.748928	0.600805
> 0.751675	0.604279
> 0.754285	0.607994
> 0.756663	0.612207
> 
> 这是print_period=10的时候打印的
> 
> 直觉上，前期AUC追不上，后期就追不上了，测试AUC也就高不了，但是就有些玄学和麻烦，要手动挑前期训练AUC表现好的

看起来和优化器关系很大，你用的是什么Optimizer，这种情况不正常

**Comment by leesusu** [comment]
AdaGrad

**Comment by MrChengmo** [comment]
> AdaGrad

试一下SGD和Adam吧，学习率可以先小一些，排除下优化器的问题，如果还是有这种现象，就需要排查下分布式框架的问题。

**Comment by leesusu** [comment]
好，我试下你说的方法，感谢

**Comment by leesusu** [comment]
@MrChengmo Hi, 我试了SGD和调小学习率，大概结论是这样：
1. 全异步的SGD比全异步的AdaGrad效果稍微稳定些
2. 调小LR，也会稳定些，但是AUC也会降

同时也试了dataset的同步训练，训练效果稳定很多，可能我们最终会先同步，再异步。
