### ISSUE TITLE
在使用paddleseg 的u-net模型时一直在报这个错误求求大佬帮我看一下

### ISSUE THREAD

**Issue by shuhan666** [PaddlePaddle/Paddle#25366]
Error: Blocking queue is killed because the data reader raises an exception
  [Hint: Expected killed_ != true, but received killed_:1 == true:1.] at (D:\1.8.1\paddle\paddle/fluid/operators/reader/blocking_queue.h:141)
  [operator < read > error]
W0703 11:51:43.316778 16908 operator.cc:187] read raises an exception class std::future_error, no state
F0703 11:51:43.316778 16908 exception_holder.h:37] std::exception caught, no state
*** Check failure stack trace: ***
去群里问说吧batch sise调小一点，检查图片，但是我检查了还是这么报错，求求大佬帮帮忙

**Comment by DannyIsFunny** [comment]
你好，paddleseg相关问题建议直接到 Paddle-Seg repo中提Issue询问：
https://github.com/PaddlePaddle/PaddleSeg/issues

**Comment by wuyefeilin** [comment]
@shuhan666 请问你这是在什么情况下碰到这个问题的，也麻烦你把issue提到https://github.com/PaddlePaddle/PaddleSeg/issues，方便seg团队跟进
