### ISSUE TITLE
在源码安装Paddle的时候是否可以使用本地的第三方库，如本地/usr/lib64中的grpc,gflags等进行安装

### ISSUE THREAD

**Issue by tomcheng0618** [PaddlePaddle/Paddle#25377]
非常感谢百度的paddle团队提供这么好的软件为大家使用。由于我是在局域网集群中安装paddle1.8，在源码安装的过程中无法连接外网，但在安装过程中我看到需要下载grpc,eigen等第三方包。我看到我们集群环境中有这些包,在/usr/lib64中用dnf安装的，我想询问使用源码安装的过程中是否我可以直接使用本地的这些包进行安装，如果可以我应该怎么样进行操作。

第一次写issues，希望能得到大大的支持

**Comment by jiweibo** [comment]
openblas可以，其它的暂不支持。
