### ISSUE TITLE
自定义op：实现只计算tensor 部分维度的余弦相似度

### ISSUE THREAD

**Issue by Akeepers** [PaddlePaddle/Paddle#25378]
计算余弦相似度的需求:

1.  类似pytorch的[cosine_similarity](https://pytorch.org/cppdocs/api/function_namespacetorch_1_1nn_1_1functional_1a9dc0b9d03d17ea4a679a3ccd42dc6e66.html), 只计算tensor部分维度余弦相似度，经调研paddle没有对应功能的op

尝试自定义python op时，不知道**如何定义反向函数？**， 可以帮忙给出例子吗？

前向的功能类似, 其中该op：

1. 没有需要学习的参数
2. 在encoder和分类层中间，encoder和分类层都有需要学习的参数

```
def cos_sim_dim(x, y, dim=-1):
    x = np.array(x)  # [batch_size, hidden_dim]
    y = np.array(y)  # [batch_size, seq_len ,hidden_dim]
    batch_size = y.shape[0]
    seq_len = y.shape[1]

    def cos_sim(vector_a, vector_b):
        # 计算两个向量之间余弦相似度
        vector_a = np.mat(vector_a)
        vector_b = np.mat(vector_b)

        num = float(vector_a * vector_b.T)
        denom = np.linalg.norm(vector_a) * np.linalg.norm(vector_b)
        cos = num / denom
        sim = 0.5 + 0.5 * cos
        return sim

    res = []
    for batch_idx in range(batch_size):
        cur = []
        for seq_idx in range(seq_len):
            cur.append(cos_sim(x[batch_idx], y[batch_idx][seq_idx]))
        res.append(cur)
    return np.array(res).astype('float32')
```

**Comment by liym27** [comment]
您好，您可以参考官方文档：[如何写新的Python OP](https://www.paddlepaddle.org.cn/documentation/docs/zh/advanced_guide/addon_development/new_op/new_python_op.html)

**Comment by Akeepers** [comment]
我看了您提到的这个文档。贴的代码是我参考文档写的前向函数。文档中的示例是tanh，但是我想自定义的op，是没有需要学习的参数的。

所以我的问题是，**不太确定这里是否需要定义反向函数，如果需要定义，该如何实现**

**Comment by liym27** [comment]
需要定义反向函数，具体的实现除了参考文档外，需要自行给出反向计算逻辑。
反向计算逻辑可以参考Paddle源码中的op反向逻辑、或者自行搜索反向计算方法。
