### ISSUE TITLE
paddle调用异常

### ISSUE THREAD

**Issue by vinceyzw** [PaddlePaddle/Paddle#25386]
- 报错情况：
Connected to pydev debugger (build 201.7846.77)
W0706 10:48:51.948972  5980 init.cc:209] Warning: PaddlePaddle catches a failure signal, it may not work properly
W0706 10:48:51.948985  5980 init.cc:211] You could check whether you killed PaddlePaddle thread/process accidentally or report the case to PaddlePaddle
W0706 10:48:51.948987  5980 init.cc:214] The detail failure signal is:

W0706 10:48:51.948990  5980 init.cc:217] *** Aborted at 1594003731 (unix time) try "date -d @1594003731" if you are using GNU date ***
W0706 10:48:51.949749  5980 init.cc:217] PC: @                0x0 (unknown)
W0706 10:48:51.949796  5980 init.cc:217] *** SIGSEGV (@0x0) received by PID 5980 (TID 0x7f725de04700) from PID 0; stack trace: ***
W0706 10:48:51.950470  5980 init.cc:217]     @     0x7f725d9f7390 (unknown)
W0706 10:48:51.951126  5980 init.cc:217]     @                0x0 (unknown)

- 版本、环境信息：
    1）PaddlePaddle版本：1.7.2
    2）GPU：RTX2070  cuda10.0   cudnn 7.6.5
    3）系统环境：ubuntu16.04
    4）python版本：3.6.10

# 在Python解释器中输入如下指令，出现上述报错
>>> import paddle.fluid as fluid
>>> fluid.install_check.run_check()

**Comment by tianshuo78520a** [comment]
使用1.8版本的Paddle 测试呢？ 1.7存在该问题的，可以尝试使用1.8以上的Paddle.

**Comment by vinceyzw** [comment]
> 使用1.8版本的Paddle 测试呢？ 1.7存在该问题的，可以尝试使用1.8以上的Paddle.

1.8.0和1.8.2我都试过了，一样的报错。
conda虚拟环境装的包：
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main  
astor                     0.8.1                     <pip>
ca-certificates           2020.6.24                     0  
certifi                   2020.6.20                py36_0  
chardet                   3.0.4                     <pip>
click                     7.1.2                     <pip>
cycler                    0.10.0                    <pip>
decorator                 4.4.2                     <pip>
funcsigs                  1.0.2                     <pip>
gast                      0.3.3                     <pip>
graphviz                  0.14                      <pip>
idna                      2.10                      <pip>
joblib                    0.16.0                    <pip>
kiwisolver                1.2.0                     <pip>
ld_impl_linux-64          2.33.1               h53a641e_7  
libedit                   3.1.20191231         h7b6447c_0  
libffi                    3.3                  he6710b0_2  
libgcc-ng                 9.1.0                hdf63c60_0  
libstdcxx-ng              9.1.0                hdf63c60_0  
matplotlib                3.2.2                     <pip>
ncurses                   6.2                  he6710b0_1  
nltk                      3.5                       <pip>
numpy                     1.19.0                    <pip>
objgraph                  3.4.1                     <pip>
opencv-python             4.3.0.36                  <pip>
openssl                   1.1.1g               h7b6447c_0  
paddlepaddle-gpu          1.8.0.post107             <pip>
pathlib                   1.0.1                     <pip>
Pillow                    7.2.0                     <pip>
pip                       20.1.1                   py36_1  
prettytable               0.7.2                     <pip>
protobuf                  3.12.2                    <pip>
pyparsing                 2.4.7                     <pip>
python                    3.6.10               h7579374_2  
python-dateutil           2.8.1                     <pip>
PyYAML                    5.3.1                     <pip>
rarfile                   3.1                       <pip>
readline                  8.0                  h7b6447c_0  
regex                     2020.6.8                  <pip>
requests                  2.24.0                    <pip>
scipy                     1.3.1                     <pip>
setuptools                47.3.1                   py36_0  
six                       1.15.0                    <pip>
sqlite                    3.32.3               h62c20be_0  
tk                        8.6.10               hbc83047_0  
tqdm                      4.47.0                    <pip>
urllib3                   1.25.9                    <pip>
wheel                     0.34.2                   py36_0  
xz                        5.2.5                h7b6447c_0  
zlib                      1.2.11               h7b6447c_3

**Comment by tianshuo78520a** [comment]
请问报错信息只有这么短么？能否发下全部的日志截图。或者我们能否登陆到您的机器上调试该问题，我们暂时没有RTX2070型号的显卡，暂时没能复现该问题，您可以尝试使用p40或v100型号显卡来跑代码。
希望收到您的回复

**Comment by vinceyzw** [comment]
> 请问报错信息只有这么短么？能否发下全部的日志截图。或者我们能否登陆到您的机器上调试该问题，我们暂时没有RTX2070型号的显卡，暂时没能复现该问题，您可以尝试使用p40或v100型号显卡来跑代码。
> 希望收到您的回复

好消息！！我通过conda安装成功了，conda里自动下载了对应的cuda10.0、cudnn7.5，现在1.8.2可以跑。

但是，我本机环境pytorch-gpu是可以跑起来的，nvidia-smi、nvcc、cudnn都能正常调通，目前找不到自己本机上的问题，如果你们方便也可以帮忙看下。
@tianshuo78520a

**Comment by tianshuo78520a** [comment]
现在的问题是本机环境安装1.8.2跑不通，但是在conda环境下安装的1.8.2就可能正常跑？这是一个奇怪的问题，比较怀疑是不是环境没有安装好？
