### ISSUE TITLE
能否在jetson nano arm64架构上编译和使用

### ISSUE THREAD

**Issue by 60999** [PaddlePaddle/Paddle#25380]
如题：
尝试了一下编译失败，请问有没有编译方法的文档？谢谢！

**Comment by cryoco** [comment]
jetson上编译可以看这个[文档](https://www.paddlepaddle.org.cn/documentation/docs/zh/advanced_guide/inference_deployment/inference/build_and_install_lib_cn.html)，如还有编译报错可以截图发出来哈
