### ISSUE TITLE
训练好的模型能接到物联网平台吗

### ISSUE THREAD

**Issue by ClassmateXiaoyu** [PaddlePaddle/Paddle#25404]
我想咨询一下，飞浆训练好的模型能否部署到物联网平台，比如百度自己的物联网平台，如果可以，应该怎么进行部署，有没有相关的文档？

**Comment by cryoco** [comment]
请问您是要部署到什么硬件上呢

**Comment by cryoco** [comment]
如果要在端侧部署，可以使用Paddle-Lite，可以参考这个[文档](https://paddle-lite.readthedocs.io/zh/latest/)哈

**Comment by ClassmateXiaoyu** [comment]
你好，模型会部通过使用paddle lite署在树莓派之类的硬件上。同时也会做paddle serving的HTTP部署，HTTP部署后，物联网平台能否通过部署的http地址进行模型的访问并返回值？
