### ISSUE TITLE
有动态图模式下可以使用的一维卷积和池化吗

### ISSUE THREAD

**Issue by liu0haha123** [PaddlePaddle/Paddle#25428]
飞桨版本1.7.2
测试代码
import paddle.fluid as fluid
with fluid.dygraph.guard():
    x = fluid.layers.data(name='x', shape=[7, 1], append_batch_size=False,
                          dtype='float32', lod_level=1)

    avg_x = fluid.layers.sequence_pool(input=x, pool_type='average')
    sum_x = fluid.layers.sequence_pool(input=x, pool_type='sum')
    sqrt_x = fluid.layers.sequence_pool(input=x, pool_type='sqrt')
    max_x = fluid.layers.sequence_pool(input=x, pool_type='max')
    last_x = fluid.layers.sequence_pool(input=x, pool_type='last')
    first_x = fluid.layers.sequence_pool(input=x, pool_type='first')

    print(max_x)

报错信息：Traceback (most recent call last):
  File "E:/Paddle/test.py", line 5, in <module>
    avg_x = fluid.layers.sequence_pool(input=x, pool_type='average')
  File "D:\Anaconda\envs\paddle\lib\site-packages\paddle\fluid\layers\sequence_lod.py", line 341, in sequence_pool
    "sequence layer is not supported in dygraph mode yet.")
AssertionError: sequence layer is not supported in dygraph mode yet.

请问有在动态图模式下可以使用的一维卷积和池化吗 或者有什么利用现有的函数替代的方案

**Comment by juncaipeng** [comment]
请参考：
https://www.paddlepaddle.org.cn/documentation/docs/zh/2.0-alpha/api_guides/low_level/layers/conv.html#d
https://www.paddlepaddle.org.cn/documentation/docs/zh/2.0-alpha/api_guides/low_level/layers/pooling.html#sequence-pool

但是我看api都是只支持静态图，目前没有支持动态图。

目前动态图主要在2.0版本有重大升级和支持。

**Comment by liu0haha123** [comment]
自己
