### ISSUE TITLE
语言模型任务中，怎么用前一批次的隐藏状态初始化下一批次的隐藏状态？如图

### ISSUE THREAD

**Issue by wu8320175** [PaddlePaddle/Paddle#25421]
![QQ图片20200707210101](https://user-images.githubusercontent.com/24267883/86786039-1220fa80-c096-11ea-9c5c-42b11eccbb7d.png)

**Comment by wu8320175** [comment]
1.8版本静态图

**Comment by FrostML** [comment]
可以参考下这个模型 language_model：https://github.com/PaddlePaddle/models/tree/release/1.8/PaddleNLP/language_model
然后详细的组网的代码在这里：https://github.com/PaddlePaddle/models/blob/release/1.8/PaddleNLP/shared_modules/models/language_model/lm_model.py#L336
![image](https://user-images.githubusercontent.com/7160927/86869695-98c2ef80-c109-11ea-98d2-33b1fa31a657.png)

**Comment by wu8320175** [comment]
谢谢，问题已解决！ 根据提供的源码我的实现思路是：先定义init_states=fluid.data(name='init_states',shape=[BATCH_SIZE,hidden_size],dtype='float32')，作为模型的数据输入，输入到模型中作为初始化状态。 模型训练时返回metrics = exe.run(main_program,feed={'words':ipt_data[0],'label':ipt_data[1],'init_states':ipt_data[2]},fetch_list=[avg_cost,**states**])fetch_list返回states，作为下一个batch 模型输入的初始状态数据。
