### ISSUE TITLE
关于paddle张量运算的问题

### ISSUE THREAD

**Issue by lxk767363331** [PaddlePaddle/Paddle#25424]
你好，问题是这样的。我现在有2个张量A（8,3,512,512）、B（8,3,512,512）意思分别为（N,C,W,H）现在我要对这两个张量的W，H分别相加然后分别求均值，再得到一个（8,3,512,512）的张量。            
相加我找到的是这个算子 warp=fluid.layers.elementwise_add(x=data, y=down_up_warp, act=None)
求均值我没有找到，warp=warp//2这样是不对的。
请问有算子么 ？或者可以告知我怎么写嘛

**Comment by cryoco** [comment]
可以看下[fluid.layers.mean](https://www.paddlepaddle.org.cn/documentation/docs/zh/api_cn/layers_cn/mean_cn.html#mean)是否满足您的需求

**Comment by lxk767363331** [comment]
这个是求输入的全部平均值，我要做的操作是2个张量中某2个维度加和 再求这俩数的均值
------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Pei Yang"<notifications@github.com&gt;;
发送时间:&nbsp;2020年7月8日(星期三) 上午10:37
收件人:&nbsp;"PaddlePaddle/Paddle"<Paddle@noreply.github.com&gt;;
抄送:&nbsp;"不要冲动保持心态"<767363331@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [PaddlePaddle/Paddle] 关于paddle张量运算的问题 (#25424)





 
可以看下fluid.layers.mean是否满足您的需求

**Comment by cryoco** [comment]
您可以试下[reduce_mean](https://www.paddlepaddle.org.cn/documentation/docs/zh/api_cn/layers_cn/reduce_mean_cn.html#reduce-mean)
