### ISSUE TITLE
关于AIStudio训练报错的问题

### ISSUE THREAD

**Issue by MARD1NO** [PaddlePaddle/Paddle#25430]
您好，今天在AIStudio 的paddle1.8版本下跑代码，报了个错误，重启环境无效
![image](https://user-images.githubusercontent.com/42901638/86866771-2c91bd00-c104-11ea-92ab-26273078af3b.png)
之前在paddle1.7下跑代码也是这个错误，但是代码没改动，第二天重新启动项目后又恢复正常了

这两次运行代码我只修改了自己的batchsize大小，而且我自己拿numpy张量运算检验，最后出来的张量shape是正确的，不知道这个问题出在哪儿？

**Comment by MARD1NO** [comment]
另外补充下，这个训练程序是基于我定义的模型来跑的，我使用numpy自定义张量验证
![image](https://user-images.githubusercontent.com/42901638/86867204-fef94380-c104-11ea-8c4d-93690e0d74b5.png)
![image](https://user-images.githubusercontent.com/42901638/86867216-03256100-c105-11ea-9bf3-f7d2458900dc.png)
最后输出shape是正确的

**Comment by juncaipeng** [comment]
可以给出一个分享版本，我来复现一下吗？

**Comment by MARD1NO** [comment]
> 可以给出一个分享版本，我来复现一下吗？

https://aistudio.baidu.com/aistudio/projectdetail/316583 您好项目地址在这儿，不过这是之前的一个版本。现有的代码都是在此基础增加的。我之前所说的1.7出现的问题在这个版本上也出现过，只不过第二天又可以正常运行了。
问了下官方人员他说这个是日志，并不是报错信息
另外我撰写了一份该项目的使用文档，如果需要可加微信:15220112039

**Comment by MARD1NO** [comment]
> 可以给出一个分享版本，我来复现一下吗？

您好，今天在aistudio把paddle版本换回1.7.0后，报错消失了

**Comment by juncaipeng** [comment]
> > 可以给出一个分享版本，我来复现一下吗？
> 
> 您好，今天在aistudio把paddle版本换回1.7.0后，报错消失了

好的，如果有后续问题可以继续提出~~
