### ISSUE TITLE
一个关于paddle.fluid.layers.space_to_depth的问题

### ISSUE THREAD

**Issue by cyfwry** [PaddlePaddle/Paddle#25432]
欢迎您对PaddlePaddle提出建议，非常感谢您对PaddlePaddle的贡献！
在留下您的建议时，辛苦您同步提供如下信息：
- 版本、环境信息
1）PaddlePaddle版本：1.7,2
2）CPU/GPU：CPU&GPU，用的是ai studio平台环境
3）系统环境：ai studio平台环境
- 复现信息：
我尝试使用api：paddle.fluid.layers.space_to_depth(x, blocksize, name=None)（参考文档https://www.paddlepaddle.org.cn/documentation/docs/zh/api_cn/layers_cn/space_to_depth_cn.html#space-to-depth），但我发现文档中给出的范例不可以成功使用（但示例可以），原因在于pd中的space_to_depth的实现和tf的space_to_depth以及pixelshuffle并不一致，它是从各个channel中提出元素并重组（而不是像其他的，从本channel中提出元素），这导致channel必须能够被blocksize**2整除。
测试代码如下：
import paddle.fluid as fluid
start_prog=fluid.Program()
main_prog=fluid.Program()
with fluid.program_guard(main_prog,start_prog):
    a=fluid.layers.data(name='a',shape=[1,4,4,4],dtype='int64',append_batch_size=False)
    b=fluid.layers.space_to_depth(a,2)

place=fluid.CPUPlace()
exe=fluid.Executor(place)
import numpy as np
input=np.arange(64).reshape(1,4,4,4)
exe.run(start_prog)
exe.run(main_prog,fetch_list=[b],feed={'a':input})
以上代码（与示例一致）能够成功执行

import paddle.fluid as fluid
start_prog=fluid.Program()
main_prog=fluid.Program()
with fluid.program_guard(main_prog,start_prog):
    a=fluid.layers.data(name='a',shape=[1,1,4,4],dtype='int64',append_batch_size=False)
    b=fluid.layers.space_to_depth(a,2)

place=fluid.CPUPlace()
exe=fluid.Executor(place)
import numpy as np
input=np.arange(16).reshape(1,1,4,4)
exe.run(start_prog)
exe.run(main_prog,fetch_list=[b],feed={'a':input})
以上代码（与范例一致）报错：Error: input channel should be divisible of the square of SpaceToDepthOp blocksize
  [Hint: Expected x_dims[1] % (blocksize * blocksize) == 0, but received x_dims[1] % (blocksize * blocksize):1 != 0:0.] at (/paddle/paddle/fluid/operators/space_to_depth_op.cc:63)
  [operator < space_to_depth > error]
- 建议描述：
1、修改范例，使其与正确的示例一致。
2、或许未来考虑出一个和pixelshuffle一致的api？

**Comment by mamingjie-China** [comment]
> 欢迎您对PaddlePaddle提出建议，非常感谢您对PaddlePaddle的贡献！
> 在留下您的建议时，辛苦您同步提供如下信息：
> 
> * 版本、环境信息
>   1）PaddlePaddle版本：1.7,2
>   2）CPU/GPU：CPU&GPU，用的是ai studio平台环境
>   3）系统环境：ai studio平台环境
> * 复现信息：
>   我尝试使用api：paddle.fluid.layers.space_to_depth(x, blocksize, name=None)（参考文档[https://www.paddlepaddle.org.cn/documentation/docs/zh/api_cn/layers_cn/space_to_depth_cn.html#space-to-depth），但我发现文档中给出的范例不可以成功使用（但示例可以），原因在于pd中的space_to_depth的实现和tf的space_to_depth以及pixelshuffle并不一致，它是从各个channel中提出元素并重组（而不是像其他的，从本channel中提出元素），这导致channel必须能够被blocksize**2整除。](https://www.paddlepaddle.org.cn/documentation/docs/zh/api_cn/layers_cn/space_to_depth_cn.html#space-to-depth%EF%BC%89%EF%BC%8C%E4%BD%86%E6%88%91%E5%8F%91%E7%8E%B0%E6%96%87%E6%A1%A3%E4%B8%AD%E7%BB%99%E5%87%BA%E7%9A%84%E8%8C%83%E4%BE%8B%E4%B8%8D%E5%8F%AF%E4%BB%A5%E6%88%90%E5%8A%9F%E4%BD%BF%E7%94%A8%EF%BC%88%E4%BD%86%E7%A4%BA%E4%BE%8B%E5%8F%AF%E4%BB%A5%EF%BC%89%EF%BC%8C%E5%8E%9F%E5%9B%A0%E5%9C%A8%E4%BA%8Epd%E4%B8%AD%E7%9A%84space_to_depth%E7%9A%84%E5%AE%9E%E7%8E%B0%E5%92%8Ctf%E7%9A%84space_to_depth%E4%BB%A5%E5%8F%8Apixelshuffle%E5%B9%B6%E4%B8%8D%E4%B8%80%E8%87%B4%EF%BC%8C%E5%AE%83%E6%98%AF%E4%BB%8E%E5%90%84%E4%B8%AAchannel%E4%B8%AD%E6%8F%90%E5%87%BA%E5%85%83%E7%B4%A0%E5%B9%B6%E9%87%8D%E7%BB%84%EF%BC%88%E8%80%8C%E4%B8%8D%E6%98%AF%E5%83%8F%E5%85%B6%E4%BB%96%E7%9A%84%EF%BC%8C%E4%BB%8E%E6%9C%ACchannel%E4%B8%AD%E6%8F%90%E5%87%BA%E5%85%83%E7%B4%A0%EF%BC%89%EF%BC%8C%E8%BF%99%E5%AF%BC%E8%87%B4channel%E5%BF%85%E9%A1%BB%E8%83%BD%E5%A4%9F%E8%A2%ABblocksize**2%E6%95%B4%E9%99%A4%E3%80%82)
>   测试代码如下：
>   import paddle.fluid as fluid
>   start_prog=fluid.Program()
>   main_prog=fluid.Program()
>   with fluid.program_guard(main_prog,start_prog):
>   a=fluid.layers.data(name='a',shape=[1,4,4,4],dtype='int64',append_batch_size=False)
>   b=fluid.layers.space_to_depth(a,2)
> 
> place=fluid.CPUPlace()
> exe=fluid.Executor(place)
> import numpy as np
> input=np.arange(64).reshape(1,4,4,4)
> exe.run(start_prog)
> exe.run(main_prog,fetch_list=[b],feed={'a':input})
> 以上代码（与示例一致）能够成功执行
> 
> import paddle.fluid as fluid
> start_prog=fluid.Program()
> main_prog=fluid.Program()
> with fluid.program_guard(main_prog,start_prog):
> a=fluid.layers.data(name='a',shape=[1,1,4,4],dtype='int64',append_batch_size=False)
> b=fluid.layers.space_to_depth(a,2)
> 
> place=fluid.CPUPlace()
> exe=fluid.Executor(place)
> import numpy as np
> input=np.arange(16).reshape(1,1,4,4)
> exe.run(start_prog)
> exe.run(main_prog,fetch_list=[b],feed={'a':input})
> 以上代码（与范例一致）报错：Error: input channel should be divisible of the square of SpaceToDepthOp blocksize
> [Hint: Expected x_dims[1] % (blocksize * blocksize) == 0, but received x_dims[1] % (blocksize * blocksize):1 != 0:0.] at (/paddle/paddle/fluid/operators/space_to_depth_op.cc:63)
> [operator < space_to_depth > error]
> 
> * 建议描述：
>   1、修改范例，使其与正确的示例一致。
>   2、或许未来考虑出一个和pixelshuffle一致的api？

PaddlePaddle中有pixel_shuffle这个OP，之前用过，应该是和pytorch里面对齐的，可以试一下看看https://www.paddlepaddle.org.cn/documentation/docs/zh/api_cn/layers_cn/pixel_shuffle_cn.html#pixel-shuffle

**Comment by juncaipeng** [comment]
好的，感谢反馈，已经有负责同学会修复。

如上同学回复，PaddlePaddle中有pixel_shuffle这个OP。
