### ISSUE TITLE
如何实现range索引

### ISSUE THREAD

**Issue by chenwthu** [PaddlePaddle/Paddle#25443]
如何对Tensor实现类似numpy中使用range作为索引的操作，例如`np.array([[1,2,3], [4,5,6]])[range(2), [1,2]]`可以得到`[2,6]`

**Comment by juncaipeng** [comment]
可以使用slice函数：https://www.paddlepaddle.org.cn/documentation/docs/zh/2.0-alpha/api_cn/paddle_cn/slice_cn.html#slice

**Comment by chenwthu** [comment]
slice似乎只能索引到连续的切片？

**Comment by juncaipeng** [comment]
也有strided_slice ：https://www.paddlepaddle.org.cn/documentation/docs/zh/2.0-alpha/api_cn/paddle_cn/strided_slice_cn.html

**Comment by chenwthu** [comment]
`index_sample`可以实现，但好像没有保留梯度图
