### ISSUE TITLE
lookup_table抛出特殊异常

### ISSUE THREAD

**Issue by dingsiyu** [PaddlePaddle/Paddle#25440]
epoch 0 progress 490/12133 pyreader queue size 24
step: 10, ave loss: 0.053850, ave acc: 0.000000, time_cost: 10.359152 s
epoch 0 progress 919/12133 pyreader queue size 46
step: 20, ave loss: 0.000000, ave acc: 0.000000, time_cost: 3.790060 s
epoch 0 progress 1098/12133 pyreader queue size 50
step: 30, ave loss: 0.000000, ave acc: 0.000000, time_cost: 3.348874 s
Error: /paddle/paddle/fluid/operators/lookup_table_op.cu:38 Assertion `id >= 0` failed. Variable value (input) of OP(fluid.layers.embedding) expected >= 0 and < 25000, but got -4647714812233515008. Please check input value.
Error: /paddle/paddle/fluid/operators/lookup_table_op.cu:38 Assertion `id >= 0` failed. Variable value (input) of OP(fluid.layers.embedding) expected >= 0 and < 25000, but got -4647714812233515008. Please check input value.
Error: /paddle/paddle/fluid/operators/lookup_table_op.cu:38 Assertion `id >= 0` failed. Variable value (input) of OP(fluid.layers.embedding) expected >= 0 and < 25000, but got -4647714812233515008. Please check input value.
Error: /paddle/paddle/fluid/operators/lookup_table_op.cu:38 Assertion `id >= 0` failed. Variable value (input) of OP(fluid.layers.embedding) expected >= 0 and < 25000, but got -4647714812233515008. Please check input value.
Error: /paddle/paddle/fluid/operators/lookup_table_op.cu:38 Assertion `id >= 0` failed. Variable value (input) of OP(fluid.layers.embedding) expected >= 0 and < 25000, but got -4647714812233515008. Please check input value.
Error: /paddle/paddle/fluid/operators/lookup_table_op.cu:38 Assertion `id >= 0` failed. Variable value (input) of OP(fluid.layers.embedding) expected >= 0 and < 25000, but got -4647714812233515008. Please check input value.
Error: /paddle/paddle/fluid/operators/lookup_table_op.cu:38 Assertion `id >= 0` failed. Variable value (input) of OP(fluid.layers.embedding) expected >= 0 and < 25000, but got -4647714812233515008. Please check input value.
Error: /paddle/paddle/fluid/operators/lookup_table_op.cu:38 Assertion `id >= 0` failed. Variable value (input) of OP(fluid.layers.embedding) expected >= 0 and < 25000, but got -4647714812233515008. Please check input value.
Error: /paddle/paddle/fluid/operators/lookup_table_op.cu:38 Assertion `id >= 0` failed. Variable value (input) of OP(fluid.layers.embedding) expected >= 0 and < 25000, but got -4647714812233515008. Please check input value.
Error: /paddle/paddle/fluid/operators/lookup_table_op.cu:38 Assertion `id >= 0` failed. Variable value (input) of OP(fluid.layers.embedding) expected >= 0 and < 25000, but got -4647714812233515008. Please check input value.
Error: /paddle/paddle/fluid/operators/lookup_table_op.cu:38 Assertion `id >= 0` failed. Variable value (input) of OP(fluid.layers.embedding) expected >= 0 and < 25000, but got -4647714812233515008. Please check input value.
Error: /paddle/paddle/fluid/operators/lookup_table_op.cu:38 Assertion `id >= 0` failed. Variable value (input) of OP(fluid.layers.embedding) expected >= 0 and < 25000, but got -4647714812233515008. Please check input value.
Error: /paddle/paddle/fluid/operators/lookup_table_op.cu:38 Assertion `id >= 0` failed. Variable value (input) of OP(fluid.layers.embedding) expected >= 0 and < 25000, but got -4647714812233515008. Please check input value.
Error: /paddle/paddle/fluid/operators/lookup_table_op.cu:38 Assertion `id >= 0` failed. Variable value (input) of OP(fluid.layers.embedding) expected >= 0 and < 25000, but got -4647714812233515008. Please check input value.
Error: /paddle/paddle/fluid/operators/lookup_table_op.cu:38 Assertion `id >= 0` failed. Variable value (input) of OP(fluid.layers.embedding) expected >= 0 and < 25000, but got -4647714812233515008. Please check input value.

**Comment by seiriosPlus** [comment]
lookup table OP的输入要求是 [0, N-1)， 可以在lookuptable前加一下[`fluid.layers.Print`](https://www.paddlepaddle.org.cn/documentation/docs/zh/api_cn/layers_cn/Print_cn.html#print) ， 排查一下是不是输入有误.

**Comment by Cppowboy** [comment]
我也遇到同样的问题，我把ids打印出来，发现没有超出范围的数。
我很好奇-4647714812233515008这种超级大的值是怎么来的？
另外吐槽一下，paddle的报错实在是太不直观了，重复打印了一大堆相似的东西，也没有其他信息，具体是哪个embedding，对应的op的name，啥信息也没有
