### ISSUE TITLE
the number of ids can not be zero, you need padding it in data generator

### ISSUE THREAD

**Issue by pipipiapia** [PaddlePaddle/Paddle#25454]
Thu Jul  9 10:41:15 2020[1,1]<stdout>:start load_into_memory
Thu Jul  9 10:41:16 2020[1,1]<stderr>:20/07/09 10:41:16 INFO fs.LibdfsLoader: Trying to load the libdfs library...
Thu Jul  9 10:41:16 2020[1,1]<stderr>:20/07/09 10:41:16 INFO fs.LibdfsLoader: Loaded the libdfs library
Thu Jul  9 10:41:16 2020[1,1]<stderr>:20/07/09 10:41:16 INFO fs.DFileSystem: Loaded the libdfs library
Thu Jul  9 10:41:16 2020[1,1]<stderr>:terminate called after throwing an instance of 'paddle::platform::EnforceNotMet'
Thu Jul  9 10:41:16 2020[1,1]<stderr>:  what():  The number of ids can not be zero, you need padding it in data generator; or if there is something wrong with the data, please check if the data contains unresolvable characters.

pslib 预测报错，预测的是训练样本，理论上不会出现格式问题

**Comment by seiriosPlus** [comment]
可以检查一下数据， 提示有空slot， 需要补0.

**Comment by 45659301** [comment]
离线训练的时候也遇到了这个任务，slot都补0了，最终排查发现问题：参数个数 和你 在定义 dataset的时候的 set var 没对上。
