### ISSUE TITLE
使用opt将Paddle detection训练的模型转为arm下部署出问题

### ISSUE THREAD

**Issue by HongRuHou** [PaddlePaddle/Paddle#25455]
我是用的是Paddle detection的yolov3+resnet50训练出来了一个目标检测模型，使用tools/model_infer可以正常生成__model__和__params__,然后我就是用opt工具将这个初步转换后的模型试着转换为arm下可以部署的cpu模型，就报错了，显示不支持。但是我在官网文档看了下是支持resnet50的，所以就不知道为啥了，有点懵。

Error: This model is not supported, because 1 ops are not supported on 'arm'. These unsupported ops are: 'deformable_conv'.
上述为报错信息

**Comment by zhupengyang** [comment]
paddlelite的deformable_conv OP在develop分支上已经开发完成，可以在下一个release版本使用。现阶段也可以自己使用develop分支编译opt和预测库。

**Comment by HongRuHou** [comment]
我后来换成了Paddle detection库下的mobilenet_v1来训练，但是在opt的时候也遇到个什么版本问题，可以麻烦您帮我看看嘛，这个按理来说不应该是支持的嘛。
I0709 13:42:28.243165 16428 cxx_api.cc:251] Load model from file.
F0709 13:42:28.255749 16428 model_parser.cc:63] Check failed: version == 0U (1924763619 vs. 0) Only version 0 is supported
*** Check failure stack trace: ***
Aborted (core dumped)

**Comment by HongRuHou** [comment]
release版本下载的git有吗？我想在AI STUDIO弄一个试试

**Comment by HongRuHou** [comment]
> paddlelite的deformable_conv OP在develop分支上已经开发完成，可以在下一个release版本使用。现阶段也可以自己使用develop分支编译opt和预测库。

我后来换成了Paddle detection库下的mobilenet_v1来训练，但是在opt的时候也遇到个什么版本问题，可以麻烦您帮我看看嘛，这个按理来说不应该是支持的嘛。
I0709 13:42:28.243165 16428 cxx_api.cc:251] Load model from file.
F0709 13:42:28.255749 16428 model_parser.cc:63] Check failed: version == 0U (1924763619 vs. 0) Only version 0 is supported
*** Check failure stack trace: ***
Aborted (core dumped)

**Comment by zhangting2020** [comment]
> release版本下载的git有吗？我想在AI STUDIO弄一个试试

目前没有，下一个release版本才有。

**Comment by yongqiangma** [comment]
> > paddlelite的deformable_conv OP在develop分支上已经开发完成，可以在下一个release版本使用。现阶段也可以自己使用develop分支编译opt和预测库。
> 
> 我后来换成了Paddle detection库下的mobilenet_v1来训练，但是在opt的时候也遇到个什么版本问题，可以麻烦您帮我看看嘛，这个按理来说不应该是支持的嘛。
> I0709 13:42:28.243165 16428 cxx_api.cc:251] Load model from file.
> F0709 13:42:28.255749 16428 model_parser.cc:63] Check failed: version == 0U (1924763619 vs. 0) Only version 0 is supported
> *** Check failure stack trace: ***
> Aborted (core dumped)

这个问题大概率是 model 文件和 params文件不是一对导致的。

**Comment by ForeverRuri** [comment]
@HongRuHou 这问题解决了吗，我也碰到了。。。

**Comment by pgq10240817** [comment]
试一试
如果转换的是combile模式(也就是有__moble__ & __params__ 这2个文件)
paddle_lite_opt --model_file=./test/__model__  --param_file=./test/__params__ --valid_targets=arm --optimize_out_type=naive_buffer --optimize_out=mobilenet_v1_opt

**Comment by pgq10240817** [comment]
> @HongRuHou 这问题解决了吗，我也碰到了。。。

试一试
如果转换的是combile模式(也就是有__moble__ & params 这2个文件)
paddle_lite_opt --model_file=./test/model --param_file=./test/params --valid_targets=arm --optimize_out_type=naive_buffer --optimize_out=mobilenet_v1_opt
