### ISSUE TITLE
oneDNN support for DyGraph mode

### ISSUE THREAD

**Issue by wojtuss** [PaddlePaddle/Paddle#25466]
In the presence of the dynamic graph (DyGraph) mode in PaddlePaddle a question arises whether the oneDNN (previously named MKL-DNN, DNNL) library can be used to boost dynamic graphs execution. There are several factors which have to be considered when adding oneDNN support to DyGraph mode:

1. Our understanding is that DyGraph mode is most useful during topology designing and model training, as it allows more in-depth analysis of the topology one is working on. For inference workloads, static graphs are preferable due to more performance optimization options.
2. oneDNN-based kernels present in PaddlePaddle employ a primitives caching mechanism which serves two main purposes:
   1) allows reusing forward primitives in subsequent batch iterations in inference mode, avoiding overhead of recreating the primitives,
   2) allows sharing certain objects (oneDNN forward primitive descriptors) between the forward and backward runs, required for creating backward oneDNN primitives during training.
Assuming oneDNN support for DyGraph in training, ii. makes some sort of caching inevitable.
3. Using the current caching mechanism in the DyGraph mode meets problems with caching keys. Primitives are stored in the cache map under keys constructed from (among others) input/output variable names. In DyGraph mode the variable names change between batch iterations, preventing the primitives from being reused. A predictable naming conventions in DyGraph mode would be required or a new caching key creation algorithm would have to be introduced. The latter is not easy to come up with and would probably involve architectural changes and considerable amount of work when updating all the operators.
4. oneDNN support for any operator in training (in any mode) requires both forward and backward kernels implemented using oneDNN. As our past focus for oneDNN-based optimizations was on inference, current support for backward oneDNN kernels is rather scarce. There are not many operators enabled for training yet. 
5. most of the oneDNN-based grad kernels enabled so far did not prove to be much (if at all) faster than grad native kernels.
6. A dynamic graph can be used also in inference mode. However, if performance matters, most probably it is transformed into a static graph and then executed. The point of transformation from dynamic to static graph seems the most suitable for enabling oneDNN optimizations.

In view of the foregoing, we have concerns about reasonableness of adding oneDNN support in DyGraph mode for training, with a prospect of enabling it for inference after converting dynamic graphs into static ones.

Please, share Baidu's perspective on that issue. What are the use case scenarios you would like oneDNN support to help the most with?

**Comment by lidanqing-vv** [comment]
由于PaddlePaddle现在支持动态图（DyGraph）模式，百度提出希望使用oneDNN（以前称为MKL-DNN，DNNL）库来提高动态图的执行速度。目前，向DyGraph模式添加oneDNN支持时，必须考虑以下几个因素：

1. 我们的理解是DyGraph模式在深度学习模型的设计和模型训练阶段最有用，因为它可以对正在处理的模型拓扑进行更深入的分析。对于推理(Inference)的任务，由于更多的性能优化选项，应该首选静态图。
2. PaddlePaddle中目前实现的DNN的内核采用了op 缓存机制，该机制有两个目的：
          **i.**   允许在推理(Inference)模式下的后续迭代中多次重用op，从而避免了重新创建op的开销，
          **ii.**   允许前向传播(forward)和反向传播共享某些对象（oneDNN forward primitive descriptors），因为这也是在训练期间创建反向oneDNN op时所需的。如果要Onednn支持training的Dygraph，那就需要使用缓存，不可避免。
3. 在DyGraph模式下使用op相关(op元描述，primitive descriptors)的缓存机制会遇到缓存的key的问题。因为目前我们使用的key由 input, output等变量名共同构成 。在DyGraph模式下，变量名称在批处理迭代之间更改，导致了无法重用。我们认为DyGraph模式下需要可预测的命名约定(naming convention)，或者必须引入新的缓存密钥创建算法。后者不容易提出，因为涉及所有op更改架构更改等大量工作。
4. 要实现oneDNN 支持dygraph training，必须每个涉及op都要实现前向和反向op(forward and backward)都有onednnl kernel。而上一阶段，我们的工作主要在于Inference optimization，目前实现oneDNN backward kernel (grad kernel)的还比较少
5. 到目前为止，实现了oneDNN的grad内核的也没有比grad native内核快很多（之前注重于inference优化，没有太注重training方面性能测试）。
6. OneDNN 支持动态图也可以在推理阶段使用，目前已经有一个模型可以跑了。但是，如果性能很重要，则是否考虑将其转换为静态图然后执行。从动态图到静态图转换后最适合启用oneDNN优化。

鉴于上述情况，我们在考虑DyGraph模式下添加oneDNN训练的现阶段可行性，并且我们在考虑推理部分是不是提供一个将动态图转换为静态图后进行推理的选项给用户。

请分享百度对此问题的看法。基于我们的描述，现在您希望oneDNN支持最大的用例场景是什么？

**Comment by luotao1** [comment]
@lidanqing-intel 
> 而上一阶段，我们的工作主要在于Inference optimization，目前实现oneDNN backward kernel (grad kernel)的还比较少

基本CV模型，如mobilenet v1/v2, ResNet的训练，oneDNN都是支持的。

> 实现了oneDNN的grad内核的也没有比grad native内核快很多（之前注重于inference优化，没有太注重training方面性能测试）。

基本CV模型上training的性能测试，MKLDNN是比MKL快不少的。Intel内部是有Paddle的benchmark CE系统的。

**Comment by phlrain** [comment]
下个版本我们会主推动态图模式，我们期望无论是在cpu还是gpu模式，动态图训练性能能够达到一个好的性能，就希望能够使用oneDNN，即使oneDNN的grad内核没有比grad native内核快，但是至少forward阶段也是有很大提升；
>OneDNN 支持动态图也可以在推理阶段使用，目前已经有一个模型可以跑了。但是，如果性能很重要，则是否考虑将其转换为静态图然后执行。从动态图到静态图转换后最适合启用oneDNN优化。

将动态图转换为静态图执行的事情，我们也在同步进行，方案是基于语法解析实现的，转换方案并不会100%完美，还是能期望纯的动态图的性能有一个比较好的表现

 > 我们认为DyGraph模式下需要可预测的命名约定(naming convention)，或者必须引入新的缓存密钥创建算法。后者不容易提出，因为涉及所有op更改架构更改等大量工作。

动态图使用oneDNN最大的难点我个人理解应该是在这里，看是是否能找到一个尽善尽美的方案。

**Comment by lidanqing-vv** [comment]
Translation of above comment

In next version, we will mainly promote the dynamic graph mode. We expect that the dynamic graph training performance can achieve a good performance regardless of whether it is in the CPU or GPU mode. We hope we could use oneDNN in dygraph. Even if the grad kernels of oneDNN are not faster than the grad native kernel, we still expect that the forward stage could be greatly speed up.


 > How do baidu think about converting dygraph to static graph
 
 Converting dynamic graphs to static graphs are also what we are working on now. The program is implemented based on lexical analysis models, the conversion solution will not be 100% perfect. We still expect pure dynamic graph can have a better performance
 
 > We believe that a predictable naming convention is required in DyGraph mode, or a new cache key creation algorithm must be introduced. The latter is not easy to propose because of all the work involved in all op changes and schema changes.
 
This is the biggest difficulty in using oneDNN for dynamic graphs. Please discuss with us and share the ideas to find a good solution together (Also with luotao).

**Comment by luotao1** [comment]
For the naming convention, some discussion on https://github.com/PaddlePaddle/Paddle/pull/19318.

**Comment by wojtuss** [comment]
@phlrain , @luotao1 

Thank you for your responses. I want to confirm that we are working on enabling oneDNN support for DyGraph. First results are promissing, training for ResNet50, MobileNetV1 seems to work fine, with oneDNN cache operating, significantly faster than without oneDNN. Testing is in progress. First PRs should come next week.

**Comment by luotao1** [comment]
> We believe that a predictable naming convention is required in DyGraph mode, or a new cache key creation algorithm must be introduced. The latter is not easy to propose because of all the work involved in all op changes and schema changes.

This is the biggest difficulty in using oneDNN for dynamic graphs. Please discuss with us and share the ideas to find a good solution together (Also with luotao).

@wojtuss @jczaja @lidanqing-intel 

https://github.com/PaddlePaddle/Paddle/blob/c3c61d34c1c33ef6aad003cfb17a1a53a2e3d08c/paddle/fluid/operators/mkldnn/mul_mkldnn_op.cc#L293-L295

Now, mkldnn op use the variable name, such as `ctx.OutputName("Out")`, to generate the key. But in dygraph, each iteration will use the different variable name, thus, the key will be different, and mkldnn cache will not hit. Both @phlrain and I wonder that could you generate the key without using the variable name? Could you use op type (such as `ctx.Type()`) instead?

**Comment by wojtuss** [comment]
> Now, mkldnn op use the variable name, such as `ctx.OutputName("Out")`, to generate the key. But in dygraph, each iteration will use the different variable name, thus, the key will be different, and mkldnn cache will not hit. Both @phlrain and I wonder that could you generate the key without using the variable name? Could you use op type (such as `ctx.Type()`) instead?

True, we will try to work it out.

**Comment by jczaja** [comment]
Some comment regarding cache usage, oneDNN cache is speeding up execution of inference and training it also pass some needed data from forward to grad operators. For example Native LRN is having MidOut output to pass some computational data from forward to backward. In case of LRN oneDNN is also using MidOut but there is pool and batch norm oneDNN ops that
need MidOut as well. While we do not have MidOut for pool and batch norm then we use oneDNN cache to pass this data.
This behaviour can be changed (drop using oneDNN cache for dygraph) if only we can add in runtime MidOut outputs&inputs to pool and batch norm  in a similar way as it is done for LRN , but just when oneDNN is used.

**Comment by lidanqing-vv** [comment]
Main functions are merged, we are continue improving it but it will be long process.
