### ISSUE TITLE
图像分类模型预测时候返回空list

### ISSUE THREAD

**Issue by xiangyubo** [PaddlePaddle/Paddle#25462]
使用 paddle1.6.2版本，用 executor 来预测，预测时注明 return_numpy=False。在预测图像分类模型的时候返回了一个空的 list。
创建了多个 executor，不同线程获取不同的 executor。在并发3个线程的时候，能预测2个结果，有个会返回空 list
分类模型是Resnet50，采用预训练模型训练，然后用 slim 剪枝了一下，剪枝率0.5。
感觉不是模型的问题，可能是我 executor 用法不合适或者是多线程的问题

**Comment by zhangting2020** [comment]
能方便贴以下你executor部分使用的代码吗？

**Comment by xiangyubo** [comment]
> 能方便贴以下你executor部分使用的代码吗？

```
# executor_manager.get_executor() 是从一个阻塞队列里获取 executor
executor = executor_manager.get_executor()
    if executor is not None:
        try:
            with fluid.scope_guard(scope):
                outputs = executor.run(inference_program,
                                       feed=infer_dict,
                                       fetch_list=fetch_targets,
                                       return_numpy=False)
        finally:
            executor_manager.return_executor(executor)
```

**Comment by chenwhql** [comment]
方便贴下全的demo吗？

**Comment by xiangyubo** [comment]
> 方便贴下全的demo吗？

额。因为是在业务里，不太好拆分。可以认为就是一开始初始化了几个 executor，放到阻塞队列里。在多线程的时候从队列里取出来用
```
        for i in range(executor_count):
            # executor is thread safe,
            # supports single/multiple-GPU running,
            # and single/multiple-CPU running,
            # if CPU device, only create one for all thread
            if device_type == ExecutorManager.CPU_DEVICE:
                if self.executor_queue.empty():
                    place = fluid.CPUPlace()
                    executor = fluid.Executor(place)
                    self._temp_executor = executor
                else:
                    executor = self._temp_executor
            else:
                device_id = gpu_device_ids[i]
                place = fluid.CUDAPlace(device_id)
                executor = fluid.Executor(place)

            self.executor_queue.put(executor)
```

**Comment by chenwhql** [comment]
好的，出现空的场景是CPU的还是GPU的

**Comment by xiangyubo** [comment]
> 好的，出现空的场景是CPU的还是GPU的

CPU

**Comment by chenwhql** [comment]
好的，您稍等我尝试复现下

**Comment by chenwhql** [comment]
类似这样吧，确实能复现，我再分析下

```

import numpy as np
import threading
import paddle.fluid as fluid
import queue

class ExecutorManager(object):
    def __init__(self, executor_count, device_type):
        self.executor_queue = queue.Queue(executor_count)

        for i in range(executor_count):
            # executor is thread safe,
            # supports single/multiple-GPU running,
            # and single/multiple-CPU running,
            # if CPU device, only create one for all thread
            if device_type == "cpu":
                if self.executor_queue.empty():
                    place = fluid.CPUPlace()
                    executor = fluid.Executor(place)
                    self._temp_executor = executor
                else:
                    executor = self._temp_executor
            else:
                device_id = gpu_device_ids[i]
                place = fluid.CUDAPlace(device_id)
                executor = fluid.Executor(place)

            self.executor_queue.put(executor)

    def get_executor(self):
        return self.executor_queue.get()

    def return_executor(self, executor):
        return self.executor_queue.put(executor)

executor_manager = ExecutorManager(3, "cpu")
place = fluid.CPUPlace()
exe = fluid.Executor(place)
scope = fluid.global_scope()
path = "./save_load/fc.example.model"
[inference_program, feed, fetch] = (
    fluid.io.load_inference_model(dirname=path, executor=exe))

def __thread_main__():
    executor = executor_manager.get_executor()
    if executor is not None:
        try:
            with fluid.scope_guard(scope):
                x = np.random.random((1, 784)).astype('float32')
                outputs = executor.run(inference_program,
                                      feed={feed[0]: x},
                                      fetch_list=fetch,
                                      return_numpy=False)
                print(outputs)
        finally:
            executor_manager.return_executor(executor)

for i in range(3):
    thread = threading.Thread(target=__thread_main__)
    # thread.daemon = True
    thread.start()
```
结果：
```
λ yq01-gpu-255-137-12-00 /work/scripts {master} python thread_exe_test.py 
grep: warning: GREP_OPTIONS is deprecated; please use an alias or script
[<paddle.fluid.core_avx.LoDTensor object at 0x7f3bc610a768>]
[<paddle.fluid.core_avx.LoDTensor object at 0x7f3bc8a42928>]
[]
λ yq01-gpu-255-137-12-00 /work/scripts {master} python thread_exe_test.py 
grep: warning: GREP_OPTIONS is deprecated; please use an alias or script
[<paddle.fluid.core_avx.LoDTensor object at 0x7fee393ee378>]
[<paddle.fluid.core_avx.LoDTensor object at 0x7fee39310340>]
[]
λ yq01-gpu-255-137-12-00 /work/scripts {master} python thread_exe_test.py 
grep: warning: GREP_OPTIONS is deprecated; please use an alias or script
[<paddle.fluid.core_avx.LoDTensor object at 0x7f705933c8f0>]
[<paddle.fluid.core_avx.LoDTensor object at 0x7f7056dd7340>]
[]
```

**Comment by xiangyubo** [comment]
> 类似这样吧，确实能复现，我再分析下
> 
> ```
> 
> import numpy as np
> import threading
> import paddle.fluid as fluid
> import queue
> 
> class ExecutorManager(object):
>     def __init__(self, executor_count, device_type):
>         self.executor_queue = queue.Queue(executor_count)
> 
>         for i in range(executor_count):
>             # executor is thread safe,
>             # supports single/multiple-GPU running,
>             # and single/multiple-CPU running,
>             # if CPU device, only create one for all thread
>             if device_type == "cpu":
>                 if self.executor_queue.empty():
>                     place = fluid.CPUPlace()
>                     executor = fluid.Executor(place)
>                     self._temp_executor = executor
>                 else:
>                     executor = self._temp_executor
>             else:
>                 device_id = gpu_device_ids[i]
>                 place = fluid.CUDAPlace(device_id)
>                 executor = fluid.Executor(place)
> 
>             self.executor_queue.put(executor)
> 
>     def get_executor(self):
>         return self.executor_queue.get()
> 
>     def return_executor(self, executor):
>         return self.executor_queue.put(executor)
> 
> executor_manager = ExecutorManager(3, "cpu")
> place = fluid.CPUPlace()
> exe = fluid.Executor(place)
> scope = fluid.global_scope()
> path = "./save_load/fc.example.model"
> [inference_program, feed, fetch] = (
>     fluid.io.load_inference_model(dirname=path, executor=exe))
> 
> def __thread_main__():
>     executor = executor_manager.get_executor()
>     if executor is not None:
>         try:
>             with fluid.scope_guard(scope):
>                 x = np.random.random((1, 784)).astype('float32')
>                 outputs = executor.run(inference_program,
>                                       feed={feed[0]: x},
>                                       fetch_list=fetch,
>                                       return_numpy=False)
>                 print(outputs)
>         finally:
>             executor_manager.return_executor(executor)
> 
> for i in range(3):
>     thread = threading.Thread(target=__thread_main__)
>     # thread.daemon = True
>     thread.start()
> ```
> 
> 结果：
> 
> ```
> λ yq01-gpu-255-137-12-00 /work/scripts {master} python thread_exe_test.py 
> grep: warning: GREP_OPTIONS is deprecated; please use an alias or script
> [<paddle.fluid.core_avx.LoDTensor object at 0x7f3bc610a768>]
> [<paddle.fluid.core_avx.LoDTensor object at 0x7f3bc8a42928>]
> []
> λ yq01-gpu-255-137-12-00 /work/scripts {master} python thread_exe_test.py 
> grep: warning: GREP_OPTIONS is deprecated; please use an alias or script
> [<paddle.fluid.core_avx.LoDTensor object at 0x7fee393ee378>]
> [<paddle.fluid.core_avx.LoDTensor object at 0x7fee39310340>]
> []
> λ yq01-gpu-255-137-12-00 /work/scripts {master} python thread_exe_test.py 
> grep: warning: GREP_OPTIONS is deprecated; please use an alias or script
> [<paddle.fluid.core_avx.LoDTensor object at 0x7f705933c8f0>]
> [<paddle.fluid.core_avx.LoDTensor object at 0x7f7056dd7340>]
> []
> ```

辛苦排查， 感谢感谢

**Comment by chenwhql** [comment]
![image](https://user-images.githubusercontent.com/22561442/87033415-c480cb00-c218-11ea-870a-4b9a07c98f37.png)
这里的原因是，Paddle Scope在线程之间是共享的，而Scope中同名变量只会有一份，所以这里fetch其实都是一个指针，线程执行的顺序不确定，如果前面一个变量还没有被使用，后面新生成的变量就把它覆盖了，就会出现这样的情况

这里scope也需要维护和线程数相等的备份才是安全的，Scope目前也没有copy这个操作，所以只能load多份了：

```
scopes = []
for i in range(3):
    scope = fluid.Scope()
    path = "./save_load/fc.example.model"
    with fluid.scope_guard(scope):
        [inference_program, feed, fetch] = (
            fluid.io.load_inference_model(dirname=path, executor=exe))
    scopes.append(scope)

def __thread_main__(scope):
    executor = executor_manager.get_executor()
    if executor is not None:
        try:
            with fluid.scope_guard(scope):
                x = np.random.random((1, 784)).astype('float32')
                outputs = executor.run(inference_program,
                                      feed={feed[0]: x},
                                      fetch_list=fetch,
                                      return_numpy=False)
                print(outputs)
        finally:
            executor_manager.return_executor(executor)

for i in range(3):
    thread = threading.Thread(target=__thread_main__, args=(scopes[i],))
    # thread.daemon = True
    thread.start()
```

**Comment by xiangyubo** [comment]
> ![image](https://user-images.githubusercontent.com/22561442/87033415-c480cb00-c218-11ea-870a-4b9a07c98f37.png)
> 这里的原因是，Paddle Scope在线程之间是共享的，而Scope中同名变量只会有一份，所以这里fetch其实都是一个指针，线程执行的顺序不确定，如果前面一个变量还没有被使用，后面新生成的变量就把它覆盖了，就会出现这样的情况
> 
> 这里scope也需要维护和线程数相等的备份才是安全的，Scope目前也没有copy这个操作，所以只能load多份了：
> 
> ```
> scopes = []
> for i in range(3):
>     scope = fluid.Scope()
>     path = "./save_load/fc.example.model"
>     with fluid.scope_guard(scope):
>         [inference_program, feed, fetch] = (
>             fluid.io.load_inference_model(dirname=path, executor=exe))
>     scopes.append(scope)
> 
> def __thread_main__(scope):
>     executor = executor_manager.get_executor()
>     if executor is not None:
>         try:
>             with fluid.scope_guard(scope):
>                 x = np.random.random((1, 784)).astype('float32')
>                 outputs = executor.run(inference_program,
>                                       feed={feed[0]: x},
>                                       fetch_list=fetch,
>                                       return_numpy=False)
>                 print(outputs)
>         finally:
>             executor_manager.return_executor(executor)
> 
> for i in range(3):
>     thread = threading.Thread(target=__thread_main__, args=(scopes[i],))
>     # thread.daemon = True
>     thread.start()
> ```

那要是这样，是否有违 executor 线程安全的这个说法。。。是不是 fetch 指针可以不是全局变量，变成线程安全的呢？比如 threadlocal 的，保证每个线程拿着的都有，不会被覆盖

**Comment by chenwhql** [comment]
> 是不是 fetch 指针可以不是全局变量，变成线程安全的呢？

这个实现上来讲，默认变量在global scope里，如果创建了临时的scope用来装变量，那它就不是全局scope里的了，但也是要维护不同的scope，要每个线程各拿各的，就得各自用各自的scope

**Comment by chenwhql** [comment]
> 那要是这样，是否有违 executor 线程安全的这个说法

这个说法是哪里官方有宣传？

executor确实线程无关，他只是个执行器，但给他的变量是一样的话，他执行的时候也会覆盖

**Comment by xiangyubo** [comment]
> > 那要是这样，是否有违 executor 线程安全的这个说法
> 
> 这个说法是哪里官方有宣传？
> 
> executor确实线程无关，他只是个执行器，但给他的变量是一样的话，他执行的时候也会覆盖

我记得也是在如流群里咨询到的，具体哪儿看到的，不记得了。
scope 有个点我没太懂哈。我再想想

**Comment by chenwhql** [comment]
嗯嗯，解决方法就是每个线程hold自己的scope

**Comment by zhangting2020** [comment]
已和用户确认过，问题已解决
