### ISSUE TITLE
float32类型在logsumexp中引起[inf]数据

### ISSUE THREAD

**Issue by L-lei** [PaddlePaddle/Paddle#25465]
PaddlePaddle版本：paddlepaddle-1.8.1，paddlepaddle-1.8.2
系统环境：ubuntu 16.04
Python版本号 3.5.2
在 exp(x)，reduce_sum函数中也存在下面问题
在这行代码中返回[inf]
 fluid.layers.logsumexp(fluid.dygraph.to_variable(np.array([114.23]).astype('float32')), dim=0)
在这行代码中返回[88.23]
 fluid.layers.logsumexp(fluid.dygraph.to_variable(np.array([88.23]).astype('float32')), dim=0)
在这行代码中返回[114.23]
 fluid.layers.logsumexp(fluid.dygraph.to_variable(np.array([114.23]).astype('float64')), dim=0)
这个临界值大概是89

**Comment by zhangting2020** [comment]
我这边复现，exp和logsumexp都存在inf的问题，但是reduce_sum没有。原因是计算结果超出了float32的表示范围了。用numpy计算可得到结果
```
>>> import numpy as np
>>> np.exp(114.23)
4.0687280951988525e+49
```
可以将上面的代码中，改成float64，可以得到正确结果。

**Comment by L-lei** [comment]
其实这个对我使用基本没影响，pytorch32位64位都可以，建议paddle在这些小细节处理也能得到优化

**Comment by L-lei** [comment]
另外请问下，float32不是可以表示2^32位？？

**Comment by zhangting2020** [comment]
float：
  1bit（符号位） 8bits（指数位） 23bits（尾数位）

 所以，float的范围为-2^128 ~ +2^128，也即-3.40E+38 ~ +3.40E+38

**Comment by L-lei** [comment]
我怎么也没想通那个临界值大概是89左右

**Comment by zhangting2020** [comment]
非常感谢您的建议，我们会安排对这部分优化。
