### ISSUE TITLE
fedora31环境下编译报错

### ISSUE THREAD

**Issue by ecko4869** [PaddlePaddle/Paddle#25477]
In file included from /data/chengdaning/paddle/Paddle/paddle/fluid/framework/io/shell.h:32,
                 from /data/chengdaning/paddle/Paddle/paddle/fluid/framework/io/fs.h:22,
                 from /data/chengdaning/paddle/Paddle/paddle/fluid/framework/io/fs.cc:15:
/data/chengdaning/paddle/Paddle/paddle/fluid/string/string_helper.h: In instantiation of ‘std::string paddle::string::format_string(const char*, ARGS&& ...) [with ARGS = {const char*, const char*}; std::string = std::__cxx11::basic_string<char>]’:
/data/chengdaning/paddle/Paddle/paddle/fluid/framework/io/fs.cc:30:46:   required from here
/data/chengdaning/paddle/Paddle/paddle/fluid/string/string_helper.h:54:23: error: moving a local object in a return statement prevents copy elision [-Werror=pessimizing-move]
   54 |   return std::move(str);
      |                       ^
/data/chengdaning/paddle/Paddle/paddle/fluid/string/string_helper.h:54:23: note: remove ‘std::move’ call
/data/chengdaning/paddle/Paddle/paddle/fluid/string/string_helper.h: In instantiation of ‘std::string paddle::string::format_string(const char*, ARGS&& ...) [with ARGS = {const char*}; std::string = std::__cxx11::basic_string<char>]’:
/data/chengdaning/paddle/Paddle/paddle/fluid/framework/io/fs.cc:115:71:   required from here
/data/chengdaning/paddle/Paddle/paddle/fluid/string/string_helper.h:54:23: error: moving a local object in a return statement prevents copy elision [-Werror=pessimizing-move]
/data/chengdaning/paddle/Paddle/paddle/fluid/string/string_helper.h:54:23: note: remove ‘std::move’ call
In file included from /data/chengdaning/paddle/Paddle/build/third_party/boost/src/extern_boost/boost/mpl/aux_/na_assert.hpp:23,
                 from /data/chengdaning/paddle/Paddle/build/third_party/boost/src/extern_boost/boost/mpl/arg.hpp:25,
                 from /data/chengdaning/paddle/Paddle/build/third_party/boost/src/extern_boost/boost/variant/variant_fwd.hpp:19,
                 from /data/chengdaning/paddle/Paddle/build/third_party/boost/src/extern_boost/boost/variant/variant.hpp:27,
                 from /data/chengdaning/paddle/Paddle/build/third_party/boost/src/extern_boost/boost/variant.hpp:17,
                 from /data/chengdaning/paddle/Paddle/paddle/fluid/platform/variant.h:45,
                 from /data/chengdaning/paddle/Paddle/paddle/fluid/platform/place.h:21,
                 from /data/chengdaning/paddle/Paddle/paddle/fluid/platform/place.cc:15:
/data/chengdaning/paddle/Paddle/build/third_party/boost/src/extern_boost/boost/mpl/assert.hpp:154:21: error: unnecessary parentheses in declaration of ‘assert_arg’ [-Werror=parentheses]
  154 | failed ************ (Pred::************
      |                     ^
/data/chengdaning/paddle/Paddle/build/third_party/boost/src/extern_boost/boost/mpl/assert.hpp:159:21: error: unnecessary parentheses in declaration of ‘assert_not_arg’ [-Werror=parentheses]
  159 | failed ************ (boost::mpl::not_<Pred>::************
      |                     ^
[  9%] Linking CXX static library libcpu_helper.a
[  9%] Built target cpu_helper
cc1plus: all warnings being treated as errors
make[2]: *** [paddle/fluid/platform/CMakeFiles/place.dir/build.make:83: paddle/fluid/platform/CMakeFiles/place.dir/place.cc.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:4293: paddle/fluid/platform/CMakeFiles/place.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
cc1plus: all warnings being treated as errors
make[2]: *** [paddle/fluid/framework/io/CMakeFiles/fs.dir/build.make:83: paddle/fluid/framework/io/CMakeFiles/fs.dir/fs.cc.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:16375: paddle/fluid/framework/io/CMakeFiles/fs.dir/all] Error 2

**Comment by MrChengmo** [comment]
请问一下您的编译环境是什么？

**Comment by tomcheng0618** [comment]
编译器是gcc9.3.1(gcc version 9.3.1 20200408 (Red Hat 9.3.1-2) (GCC) 
操作系统是fedora 31
不只是fluid/string/string_helper.h这里报错，在eighen3,grpc等第三方包中也大量报错

**Comment by MrChengmo** [comment]
> 编译器是gcc9.3.1(gcc version 9.3.1 20200408 (Red Hat 9.3.1-2) (GCC)
> 操作系统是fedora 31
> 不只是fluid/string/string_helper.h这里报错，在eighen3,grpc等第三方包中也大量报错

有没有尝试过使用Paddle官方提供的docker中编译，同时也有可能是没有挂代理，下载出现问题导致编译报错。

**Comment by tomcheng0618** [comment]
由于系统需求，我们可能没有办法使用docker，不过这几个错误基本可以确定是gcc9.3.1造成的

**Comment by luotao1** [comment]
我们官方支持gcc8.2或者gcc4.8.2，您可以降一下gcc版本再进行尝试

**Comment by tomcheng0618** [comment]
我们将所有代码中Werror指令删掉后即可成功在9.3.1下编译。另外在centos8下英伟达已经不再提供cuda10以下版本的cuda，希望cuda版本可以尽快出来。。。。
