### ISSUE TITLE
创建一个自定义的layer

### ISSUE THREAD

**Issue by kjiangab** [PaddlePaddle/Paddle#25478]
我想问一下我想构造一个y=WXz+bias 的 函数应该如何实现呢？其中z是我的输入，W，X, bias都是我的参数，paddle里面目前有类似于这个的层吗？或者我应该用哪个API构建一个自定义的layer？谢谢！

**Comment by MrChengmo** [comment]
目前Paddle的Fc OP可以做到y=Wz + bias

个人理解可以通过创建多个persistables参数，然后通过mul，elementwise_add等op构造出这个表达式:

- 创建参数：https://www.paddlepaddle.org.cn/documentation/docs/zh/api_cn/layers_cn/create_parameter_cn.html#create-parameter

- 矩阵乘法：https://www.paddlepaddle.org.cn/documentation/docs/zh/api_cn/layers_cn/mul_cn.html#mul

- bias需要的加法：https://www.paddlepaddle.org.cn/documentation/docs/zh/api_cn/layers_cn/elementwise_add_cn.html#elementwise-add
