### ISSUE TITLE
在1.8.2中报错。1.7.1的版本不报错

### ISSUE THREAD

**Issue by licy5152** [PaddlePaddle/Paddle#25481]
为使您的问题得到快速解决，在建立Issues前，请您先通过如下方式搜索是否有相似问题:【搜索issue关键字】【使用labels筛选】【官方文档】

如果您没有查询到相似问题，为快速解决您的提问，建立issue时请提供如下细节信息：
- 标题：简洁、精准概括您的问题，例如“Insufficient Memory xxx" ”
- 版本、环境信息：
    1）PaddlePaddle版本：1.8.2
    2）CPU：//
    3）GPU：V100、CUDA 9.2和CUDNN 7.5版本号
    4）系统环境：bml环境，Python3.6版本
 注：您可以通过执行[summary_env.py](https://github.com/PaddlePaddle/Paddle/blob/develop/tools/summary_env.py)获取以上信息。
- 训练信息
    1）单机，单卡
    2）显存信息
    3）Operator信息
- 复现信息：如为报错，请给出复现环境、复现步骤
- 问题描述：请详细描述您的问题，同步贴出报错信息、日志、可复现的代码片段

                optimizer.clear_gradients()
                #反向传播梯度
                loss.backward()
                #最小化损失来优化网络中的权重
                optimizer.minimize(loss)
                #计算网络预测精度
在1.8.2中报错。1.7.1的版本不报错

File "</usr/local/cuda-9.2/conda/envs/py36-paddle/lib/python3.6/site-packages/decorator.py:decorator-gen-76>", line 2, in backward
  File "/home/jovyan/mnt/.local/lib/python3.6/site-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
    return wrapped_func(*args, **kwargs)
  File "/home/jovyan/mnt/.local/lib/python3.6/site-packages/paddle/fluid/framework.py", line 216, in __impl__
    return func(*args, **kwargs)
  File "/home/jovyan/mnt/.local/lib/python3.6/site-packages/paddle/fluid/dygraph/varbase_patch_methods.py", line 116, in backward
    self._run_backward(backward_strategy, framework._dygraph_tracer())
paddle.fluid.core_avx.EnforceNotMet: 

--------------------------------------------
C++ Call Stacks (More useful to developers):
--------------------------------------------
0   std::string paddle::platform::GetTraceBackString<std::string const&>(std::string const&, char const*, int)
1   paddle::platform::EnforceNotMet::EnforceNotMet(std::string const&, char const*, int)
2   paddle::operators::BatchNormGradKernel<paddle::platform::CUDADeviceContext, float>::Compute(paddle::framework::ExecutionContext const&) const
3   std::_Function_handler<void (paddle::framework::ExecutionContext const&), paddle::framework::OpKernelRegistrarFunctor<paddle::platform::CUDAPlace, false, 0ul, paddle::operators::BatchNormGradKernel<paddle::platform::CUDADeviceContext, float>, paddle::operators::BatchNormGradKernel<paddle::platform::CUDADeviceContext, double>, paddle::operators::BatchNormGradKernel<paddle::platform::CUDADeviceContext, paddle::platform::float16> >::operator()(char const*, char const*, int) const::{lambda(paddle::framework::ExecutionContext const&)#1}>::_M_invoke(std::_Any_data const&, paddle::framework::ExecutionContext const&)
4   paddle::imperative::PreparedOp::Run(std::map<std::string, paddle::imperative::SavedVariableWrapperList, std::less<std::string>, std::allocator<std::pair<std::string const, paddle::imperative::SavedVariableWrapperList> > > const&, std::map<std::string, paddle::imperative

**Comment by licy5152** [comment]
--------------------------------------------
C++ Call Stacks (More useful to developers):
--------------------------------------------
0   std::string paddle::platform::GetTraceBackString<std::string const&>(std::string const&, char const*, int)
1   paddle::platform::EnforceNotMet::EnforceNotMet(std::string const&, char const*, int)
2   paddle::operators::BatchNormGradKernel<paddle::platform::CUDADeviceContext, float>::Compute(paddle::framework::ExecutionContext const&) const
3   std::_Function_handler<void (paddle::framework::ExecutionContext const&), paddle::framework::OpKernelRegistrarFunctor<paddle::platform::CUDAPlace, false, 0ul, paddle::operators::BatchNormGradKernel<paddle::platform::CUDADeviceContext, float>, paddle::operators::BatchNormGradKernel<paddle::platform::CUDADeviceContext, double>, paddle::operators::BatchNormGradKernel<paddle::platform::CUDADeviceContext, paddle::platform::float16> >::operator()(char const*, char const*, int) const::{lambda(paddle::framework::ExecutionContext const&)#1}>::_M_invoke(std::_Any_data const&, paddle::framework::ExecutionContext const&)
4   paddle::imperative::PreparedOp::Run(std::map<std::string, paddle::imperative::SavedVariableWrapperList, std::less<std::string>, std::allocator<std::pair<std::string const, paddle::imperative::SavedVariableWrapperList> > > const&, std::map<std::string, paddle::imperative::SavedVariableWrapperList, std::less<std::string>, std::allocator<std::pair<std::string const, paddle::imperative::SavedVariableWrapperList> > > const&, std::unordered_map<std::string, boost::variant<boost::blank, int, float, std::string, std::vector<int, std::allocator<int> >, std::vector<float, std::allocator<float> >, std::vector<std::string, std::allocator<std::string> >, bool, std::vector<bool, std::allocator<bool> >, paddle::framework::BlockDesc*, long, std::vector<paddle::framework::BlockDesc*, std::allocator<paddle::framework::BlockDesc*> >, std::vector<long, std::allocator<long> >, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_>, std::hash<std::string>, std::equal_to<std::string>, std::allocator<std::pair<std::string const, boost::variant<boost::blank, int, float, std::string, std::vector<int, std::allocator<int> >, std::vector<float, std::allocator<float> >, std::vector<std::string, std::allocator<std::string> >, bool, std::vector<bool, std::allocator<bool> >, paddle::framework::BlockDesc*, long, std::vector<paddle::framework::BlockDesc*, std::allocator<paddle::framework::BlockDesc*> >, std::vector<long, std::allocator<long> >, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> > > > const&)
5   paddle::imperative::OpBase::Run(paddle::framework::OperatorBase const&, std::map<std::string, paddle::imperative::SavedVariableWrapperList, std::less<std::string>, std::allocator<std::pair<std::string const, paddle::imperative::SavedVariableWrapperList> > > const&, std::map<std::string, paddle::imperative::SavedVariableWrapperList, std::less<std::string>, std::allocator<std::pair<std::string const, paddle::imperative::SavedVariableWrapperList> > > const&, std::unordered_map<std::string, boost::variant<boost::blank, int, float, std::string, std::vector<int, std::allocator<int> >, std::vector<float, std::allocator<float> >, std::vector<std::string, std::allocator<std::string> >, bool, std::vector<bool, std::allocator<bool> >, paddle::framework::BlockDesc*, long, std::vector<paddle::framework::BlockDesc*, std::allocator<paddle::framework::BlockDesc*> >, std::vector<long, std::allocator<long> >, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_>, std::hash<std::string>, std::equal_to<std::string>, std::allocator<std::pair<std::string const, boost::variant<boost::blank, int, float, std::string, std::vector<int, std::allocator<int> >, std::vector<float, std::allocator<float> >, std::vector<std::string, std::allocator<std::string> >, bool, std::vector<bool, std::allocator<bool> >, paddle::framework::BlockDesc*, long, std::vector<paddle::framework::BlockDesc*, std::allocator<paddle::framework::BlockDesc*> >, std::vector<long, std::allocator<long> >, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> > > > const&, paddle::platform::Place const&)
6   paddle::imperative::BasicEngine::Execute()

----------------------
Error Message Summary:
----------------------
InvalidArgumentError: `is_test = True` CANNOT be used in train program. If you want to use global status in pre_train model, please set `use_global_stats = True`
  [Hint: Expected is_test == false, but received is_test:1 != false:0.] at (/paddle/paddle/fluid/operators/batch_norm_op.cu:530)

**Comment by phlrain** [comment]
看起来属于在定义BatchNorm的时候 把 is_test设置为True了，训练的时候 需要把is_test改成False

**Comment by licy5152** [comment]
请问下，具体要怎么操作呢，实在定义的部分吗

**Comment by licy5152** [comment]
请问下，具体要怎么操作呢，是在定义的时候，因为网络在训练的过程的中需要加载两个网络一个测试，一个训练，两个是同步的。在1.7版本的Paddle时，没有该错误。1.8.2才出现这个问题

**Comment by phlrain** [comment]
1.7中，batchnorm 存在一些bug，在1.8版本进行了修复

可以试下通过model的mode来设置， model_a.train() 设置为训练模式， model_b.eval() 设置为测试模式（切换到.eval 模式之后，测试完成之后，要立马切换到 train 模式，否则会影响model_a的行为; . eval使用到了一些全局信息，修改了model_b mode，同样会影响model_a，这块问题我们已经在修复）

mode切换会影响batchnorm 和dropout的行为， dropout建议使用 class 形势的Dropout
