### ISSUE TITLE
build paddle-gpu with  -DCMAKE_BUILD_TYPE=Debug ERROR

### ISSUE THREAD

**Issue by XuanBaby** [PaddlePaddle/Paddle#25494]
- 标题：请包含关键词“安装错误”/“编译错误”，例如“Mac编译错误”
- 版本、环境信息：
    1）PaddlePaddle版本：1.8.1
    2）CPU：intel 
    3）GPU：cuda10.1  cudnn 7.6.5
    4）系统环境：centos 7.6.1810 
注：您可以通过执行[summary_env.py](https://github.com/PaddlePaddle/Paddle/blob/develop/tools/summary_env.py)获取以上信息。
- 安装方式信息：
2）本地编译：cmake .. -DPYTHON_EXECUTABLE=~/build/python-3.6.8-build/bin/python3 -DPYTHON_INCLUDE_DIR=/public/home/xuanbaby/build/python-3.6.8-build/include -DPYTHON_LIBRARY=/public/home/xuanbaby/build/python-3.6.8-build/lib/ -DWITH_GPU=ON -DWITH_TESTING=ON -DCMAKE_BUILD_TYPE=Debug

![image](https://user-images.githubusercontent.com/29744738/87270786-c93ccc00-c503-11ea-97f5-9cea29be16fa.png)
[ 99%] Built target test_inference_word2vec
[ 99%] Built target op_function_generator
op_function_generator: /public/home/xuanbaby/Paddle-1.8.1/paddle/fluid/string/tinyformat/tinyformat.h:563: const char* paddle::string::tinyformat::detail::streamStateFromFormat(std::ostream&, bool&, int&, const char*, const paddle::string::tinyformat::detail::FormatArg*, int&, int): Assertion `0 && "tinyformat: Not enough conversion specifiers in format string"' failed.
[ 99%] Built target test_analyzer
Child aborted
make[2]: *** [paddle/fluid/pybind/CMakeFiles/op_function_cmd] Error 1
make[1]: *** [paddle/fluid/pybind/CMakeFiles/op_function_cmd.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....

**Comment by ForFishes** [comment]
是不是gcc编译的版本不对。gcc的版本是？

**Comment by luotao1** [comment]
@ForFishes 可能是`-DCMAKE_BUILD_TYPE=Debug`的原因，默认测的都是Release分支，Debug分支有可能编译不过

**Comment by edimetia3d** [comment]
1. 当前的develop分支 631c1f3018261c2e52aca97b716d0333afeb858f 问题依然存在.  不过是另一个地方触发assert了.

2. 是 -DCMAKE_BUILD_TYPE=Debug 导致的, 在Debug模式下, assert会直接terminate程序.  Release下直接忽略掉了, 这样没问题吗?

3. 可以直接把相关的TINYFORMAT_ERROR 注释掉来workaround, make可以继续执行.

**Comment by wojtuss** [comment]
@luotao1 
This issue is also inhibitive for us when working on issues and developing new functionalities.

**Comment by yiakwy** [comment]
@luotao1 @edimetia3d @wojtuss I also commented in #13860. The wrong version of tinyformat source is used and this problem will be exposed in debug mode while contributors mostly work on it.

**Comment by codecookinging** [comment]
#13860 can't resolve this problem, how to resolve it ?
