### ISSUE TITLE
seq2seq模型demo实现的一些问题

### ISSUE THREAD

**Issue by ggjge** [PaddlePaddle/Paddle#25516]
demo地址： https://github.com/PaddlePaddle/models/blob/release/1.8/PaddleNLP/seq2seq/seq2seq/base_model.py

有以下几个问题：
1. 在train.py主程序和base_model.build_graph中有train/eval/beam_search/greedy_search 4种mode，而在后续被调用的_build_decoder方法中，只对train/beam_search两种mode进行了处理，请问eval的时候怎么解码？
![image](https://user-images.githubusercontent.com/10115676/87382037-9d374e80-c5c8-11ea-85bb-a52131c39a54.png)

![image](https://user-images.githubusercontent.com/10115676/87382118-c8ba3900-c5c8-11ea-9f59-e270ec2fee69.png)

2. 对于encoder和decoder每个time step输入的问题
EncoderCell的call方法看上去和DecoderCell的call方法内容一模一样，把上一个time step的output作为当前time step的input，这似乎不太对，认识里只有decoder才这么做，encoder不是应该把src的token依次输入就行了么
![image](https://user-images.githubusercontent.com/10115676/87382468-965d0b80-c5c9-11ea-8f7b-767a28f6d1a7.png)

**Comment by guoshengCS** [comment]
> 请问eval的时候怎么解码

这份代码中没有实现eval时使用beam search或greedy search的功能，eval算了和train一样的loss和ppl来评估。如果需要eval时解码的话也可以先自行实现，可以试下这里eval使用的inference_program修改为beam search的代码 https://github.com/PaddlePaddle/models/blob/release/1.8/PaddleNLP/seq2seq/seq2seq/train.py#L99 ，并保证inference_program和train_program使用相同的参数名（可以通过将网络定义在`with framework.unique_name.guard()`内，使两者都从0开始为参数编号命名来保证）

> 把上一个time step的output作为当前time step的input，这似乎不太对

返回值中的step_input是作为cell的output的，只是命名问题，cell完成的是`step_output, new_state = cell.call(step_input, state)` 的计算
