### ISSUE TITLE
能否在2.0版本中实现动态图的重计算

### ISSUE THREAD

**Issue by geekhch** [PaddlePaddle/Paddle#25528]
- 版本、环境信息
1）PaddlePaddle版本：1.8
2）CPU/GPU：GPU CUDA10.0
3）系统环境：请您描述系统类型、版本，例如Mac OS 10.14

- 建议描述：目前paddle的重计算（RecomputeOptimizer）仅仅实现了静态图相关功能，能否在2.0版本中实现动态图模式下的重计算呢？这对我的nlp相关实验比较重要，感谢开发者们的努力！

**Comment by mapingshuo** [comment]
> * 版本、环境信息
>   1）PaddlePaddle版本：1.8
>   2）CPU/GPU：GPU CUDA10.0
>   3）系统环境：请您描述系统类型、版本，例如Mac OS 10.14
> * 建议描述：目前paddle的重计算（RecomputeOptimizer）仅仅实现了静态图相关功能，能否在2.0版本中实现动态图模式下的重计算呢？这对我的nlp相关实验比较重要，感谢开发者们的努力！

感谢你对重计算的关注，目前动态图的重计算不在2.0规划中，动态图建议尝试使用gradient merge来提升batch size。你是科研需求，还是业务需求？

**Comment by geekhch** [comment]
好的，目前主要是科研需求



---原始邮件---
发件人: "mapingshuo"<notifications@github.com&gt;
发送时间: 2020年7月15日(周三) 中午11:42
收件人: "PaddlePaddle/Paddle"<Paddle@noreply.github.com&gt;;
抄送: "三七"<geekhch@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [PaddlePaddle/Paddle] 能否在2.0版本中实现动态图的重计算 (#25528)




   
版本、环境信息
 1）PaddlePaddle版本：1.8
 2）CPU/GPU：GPU CUDA10.0
 3）系统环境：请您描述系统类型、版本，例如Mac OS 10.14 

建议描述：目前paddle的重计算（RecomputeOptimizer）仅仅实现了静态图相关功能，能否在2.0版本中实现动态图模式下的重计算呢？这对我的nlp相关实验比较重要，感谢开发者们的努力！ 
  
感谢你对重计算的关注，目前动态图的重计算不在2.0规划中，动态图建议尝试使用gradient merge来提升batch size。你是科研需求，还是业务需求？
