### ISSUE TITLE
Paddle编译错误

### ISSUE THREAD

**Issue by DYJNG** [PaddlePaddle/Paddle#25530]
Scanning dependencies of target paddle_pybind
[ 99%] Building CXX object paddle/fluid/pybind/CMakeFiles/paddle_pybind.dir/pybind.cc.o
In file included from ~/Paddle/paddle/fluid/pybind/pybind.cc:81:0:
~/Paddle/paddle/fluid/pybind/tensor_py.h:59:10: error: ‘PYBIND11_DESCR’ does not name a type
   static PYBIND11_DESCR name() { return _("float16"); }
          ^
make[2]: *** [paddle/fluid/pybind/CMakeFiles/paddle_pybind.dir/pybind.cc.o] Error 1
make[1]: *** [paddle/fluid/pybind/CMakeFiles/paddle_pybind.dir/all] Error 2
make: *** [all] Error 2

**Comment by DYJNG** [comment]
pybind版本问题下载的过高，已解决。。

**Comment by lleesg** [comment]
> pybind版本问题下载的过高，已解决。。

请问需要安装pybind哪个版本？
