### ISSUE TITLE
单机多卡训练

### ISSUE THREAD

**Issue by zhengzhe97** [PaddlePaddle/Paddle#25535]
请问一下多卡使用ParallelExecutor接口只需要设置use_gpu=True，然后程序自动调用多卡训练吗

**Comment by yaoxuefeng6** [comment]
需要设置下
如果使用GPU运行模型，即 use_cuda=True ，节点指代GPU， ParallelExecutor 将自动获取在当前机器上可用的GPU资源，用户也可以通过在环境变量设置可用的GPU资源，例如：希望使用GPU0、GPU1计算，export CUDA_VISIBLEDEVICES=0,1
参考：https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api_cn/framework_cn/ParallelExecutor_cn.html#parallelexecutor

**Comment by zhengzhe97** [comment]
@yaoxuefeng6  谢谢回复，成功调用多张显卡会有什么输出吗，
```
W0715 00:36:37.010844  1666 device_context.cc:252] Please NOTE: device: 0, CUDA Capability: 61, Driver API Version: 10.1, Runtime API Version: 9.0
W0715 00:36:37.016928  1666 device_context.cc:260] device: 0, cuDNN Version: 7.3.
```
这是我程序的输出，看起来还是只用了一张卡？

**Comment by zhiqiu** [comment]
> @yaoxuefeng6 谢谢回复，成功调用多张显卡会有什么输出吗，
> 
> ```
> W0715 00:36:37.010844  1666 device_context.cc:252] Please NOTE: device: 0, CUDA Capability: 61, Driver API Version: 10.1, Runtime API Version: 9.0
> W0715 00:36:37.016928  1666 device_context.cc:260] device: 0, cuDNN Version: 7.3.
> ```
> 
> 这是我程序的输出，看起来还是只用了一张卡？

上面的device：0 应该没有显示所有卡的log。是否跑了多卡，可以通过nvidia-smi观察下显卡的使用情况。

p.s. 建议使用CompiledProgram进行多卡训练，它内部会调用ParallelExecutor，使用方式参考[文档](https://www.paddlepaddle.org.cn/documentation/docs/zh/api_cn/fluid_cn/CompiledProgram_cn.html)。
