### ISSUE TITLE
使用textone的ernie-gen预测报错

### ISSUE THREAD

**Issue by niantianlei** [PaddlePaddle/Paddle#25547]
报错信息如下：
![image](https://user-images.githubusercontent.com/24364049/87528099-a6efad80-c6bf-11ea-8f3a-6aa97e653010.png)
环境paddle 1.7.2 
python 2.7.14
cudnn 7.4
cuda 10.0

**Comment by niantianlei** [comment]
补充： 单卡预测，textone版本1.3

**Comment by yaoxuefeng6** [comment]
麻烦提供下代码 能够直接泡起来的复现环境吧 这样没办法排查呀
