### ISSUE TITLE
第一阶段人员分工

### ISSUE THREAD

**Issue by jacquesqiao** [PaddlePaddle/Paddle#2554]
Variable qingqing daoyuan yaming 

Operator longfei qijun yuyang fengjiayi 

Net yanchunwei zhihong wanghaoshuang  xinghai

Scope yuyang longfei yibing 

Tensor fengjiayi qingqing daoyuan liuyiqun luotao 

Memory liaogang

**Comment by reyoung** [comment]
Closed because it seems should be in `Wiki` because it is not an issue.

Please reference wiki page [here](https://github.com/PaddlePaddle/Paddle/wiki/PaddleRefactoringPeople)
