### ISSUE TITLE
dynamic_lstm设置is_reverse=False，输出是正序还是逆序

### ISSUE THREAD

**Issue by xcwei** [PaddlePaddle/Paddle#25577]
请问 fluid.layers.dynamic_lstm 中，如果设置is_reverse=False，则输出的结果是按正序输出还是按逆序输出，例如：
输入是ABCDE，那输出是按ABCDE这个序列输出，还是按EDCBA的输出？

**Comment by baiyfbupt** [comment]
是逆序的输出，可以参考API文档 https://www.paddlepaddle.org.cn/documentation/docs/zh/api_cn/layers_cn/dynamic_lstm_cn.html#dynamic-lstm
![image](https://user-images.githubusercontent.com/28884066/87663202-0b7d3c00-c796-11ea-9b28-54f2a52397e8.png)
