### ISSUE TITLE
ConfigParser NoSectionError

### ISSUE THREAD

**Issue by Damon-wyg** [PaddlePaddle/Paddle#2558]
data_provider和trainer网络结构的设置文件依赖一些配置文件，使用Python的ConfigParser解析，单机运行都是OK的，提交到集群后任务却挂了，报ConfigParser NoSectionError错误
F0622 11:41:37.578871  6639 PythonUtil.cpp:134] Check failed: (ret) != nullptr Current PYTHONPATH: ['/home/disk1/normandy/maybach/38687/workspace', '/home/disk1/normandy/maybach/38687/workspace/python27-gcc482/lib/python2.7/site-packages/setuptools-18.2-py2.7.egg', '/home/disk1/normandy/maybach/38687/workspace/paddle', '/home/disk1/normandy/maybach/38687/workspace', '/home/disk1/normandy/maybach/38687/workspace/thirdparty/thirdparty', '/home/disk1/normandy/maybach/38687/workspace/python27-gcc482/lib/python27.zip', '/home/disk1/normandy/maybach/38687/workspace/python27-gcc482/lib/python2.7', '/home/disk1/normandy/maybach/38687/workspace/python27-gcc482/lib/python2.7/plat-linux2', '/home/disk1/normandy/maybach/38687/workspace/python27-gcc482/lib/python2.7/lib-tk', '/home/disk1/normandy/maybach/38687/workspace/python27-gcc482/lib/python2.7/lib-old', '/home/disk1/normandy/maybach/38687/workspace/python27-gcc482/lib/python2.7/lib-dynload', '/home/disk1/normandy/maybach/38687/workspace/python27-gcc482/lib/python2.7/site-packages']
Python Error: <class 'ConfigParser.NoSectionError'> : No section: 'FS'
Python Callstack: 
代码是这样的：
fs_file='data_fs.cfg'

config = ConfigParser.RawConfigParser(allow_no_value=True)
config.read(fs_file)
fs = config.items('FS')
...
相关依赖都有放到thirdparty中传到集群，请问这是什么原因？

**Comment by typhoonzero** [comment]
如果指定了thirdparty，在集群任务中可以访问`fs_file=thirdparty/thirdparty/data_fs.cfg`，也可以确认任务目录下的`data_fs.cfg`存放路径然后指定`fs_file`的路径。
