### ISSUE TITLE
1.8.2版本的gpu镜像接近15G

### ISSUE THREAD

**Issue by levinxo** [PaddlePaddle/Paddle#25586]
1）PaddlePaddle版本：1.8.2
2）CPU/GPU：GPU
3）系统环境：centos docker
- 建议描述：1.8.2版本的gpu镜像接近15G，希望能缩减一些体积，参考tf GPU镜像不超过5G

**Comment by tianshuo78520a** [comment]
我们的镜像中会自带一些依赖，不需要再去额外下载，所以会比tf大一些，tf的GPU镜像也不止5个G，在docker hub上显示不到5G但实际下载下来会变成10个G左右，镜像这块我们也在优化中，已经列入计划了，感谢您的意见。

**Comment by levinxo** [comment]
@tianshuo78520a 好的，谢谢，观察发现镜像中维护了多个python版本，是镜像太大原因之一，可以考虑只保留高版本的python

**Comment by tianshuo78520a** [comment]
> @tianshuo78520a 好的，谢谢，观察发现镜像中维护了多个python版本，是镜像太大原因之一，可以考虑只保留高版本的python

好的，这是一个好的建议，可以减少我们docker的大小，但还需要和我们内部沟通是否只保留一个python 这个方案。

感谢你的意见。
