### ISSUE TITLE
sequence_conv报错：Error: Input(X, Filter) should be 2-D tensor.

### ISSUE THREAD

**Issue by lliqi-echo** [PaddlePaddle/Paddle#25583]
输入数据为：seq = fluid.layers.data(name='seq', shape=[1], dtype='int64',lod_level=1)
使用文本CNN
def cnn(data, input_dim=4, emb_dim=128, hid_dim=512):
    emb = fluid.embedding(
        input=data, size=[input_dim, emb_dim], is_sparse=True)
    conv_3 = fluid.nets.sequence_conv_pool(
        input=emb,
        num_filters=hid_dim,
        filter_size=4,
        act="tanh",
        pool_type="sqrt")
    conv_4 = fluid.nets.sequence_conv_pool(
        input=emb,
        num_filters=hid_dim,
        filter_size=4,
        act="tanh",
        pool_type="sqrt")
    prediction = fluid.layers.fc(
        input=[conv_3, conv_4], size=2, act="softmax")
    return prediction
训练过程提示sequence_conv报错，Error: Input(X, Filter) should be 2-D tensor.

**Comment by iclementine** [comment]
这个应该是一个形状的问题。

sequence_conv 需要的数据是一个 2D 的 Tensor;
但是你的数据 seq 是一个 base shape 为 [1], lod_level=1 的数据，它的内部的 Tensor 的真实形状是 [-1, 1], -1 的实际值是多个序列的总长度。

过了 embedding 之后，输出的形状是 [-1, 1, embe_dim] （因为 embedding 现在的行为是 后附一个维度），所以已经不是 2D Tensor 了，而是 3D，所以你可以 squeeze 掉中间的维度。
