### ISSUE TITLE
lstm与sequence_cnn结合使用报错：Error: Only support one level sequence now.

### ISSUE THREAD

**Issue by lliqi-echo** [PaddlePaddle/Paddle#25597]
序列数据分类，想要将CNN和lstm结合使用
模型设置如下：
`def cnnlstm(data, input_dim=4, emb_dim=128, hid_dim=512):
    emb = fluid.embedding(
        input=data, size=[input_dim, emb_dim], is_sparse=True)
    conv_3 = fluid.nets.sequence_conv_pool(
        input=emb,
        num_filters=hid_dim,
        filter_size=3,
        act="relu",
        pool_type="max")
    conv_4 = fluid.nets.sequence_conv_pool(
        input=emb,
        num_filters=hid_dim,
        filter_size=4,
        act="relu",
        pool_type="max")
    fc = fluid.layers.fc(input=[conv_3, conv_4], size=512, act='relu')   
    lstm, cell1 = fluid.layers.dynamic_lstm(input=fc, size=512)
    drop = fluid.layers.dropout(x=lstm, dropout_prob=0.5, seed=None)   
    prediction = fluid.layers.fc(input=drop, size=2, act="softmax")
    return prediction
`
数据类型：
seq = fluid.layers.data(name='seq', shape=[None], dtype='int64',lod_level=1)

运行报错：
----------------------
Error Message Summary:
----------------------
Error: Only support one level sequence now.
  [Hint: Expected lods.size() == 1UL, but received lods.size():0 != 1UL:1.] at (/paddle/paddle/fluid/operators/math/sequence2batch.h:79)
  [operator < lstm > error]

望能解答，谢谢！

**Comment by huangjun12** [comment]
看报错是输入不满足要求，[dynamic_lstm op](https://www.paddlepaddle.org.cn/documentation/docs/zh/api_cn/layers_cn/dynamic_lstm_cn.html#dynamic-lstm)需要的输入 LoDTensor的lod level为1，sequence_conv_pool op返回的conv_3和conv_4的lod level为0，得到的fc的lod Level也为0，故报错。 建议换成[lstm op](https://www.paddlepaddle.org.cn/documentation/docs/zh/api_cn/layers_cn/lstm_cn.html#cn-api-fluid-layers-lstm)试下？

**Comment by lliqi-echo** [comment]
你好，根据你的建议，将 dynamic_lstm 替换成了 lstm ，如下：
`def cnnlstm(data, input_dim=256, emb_dim=128):
    emb = fluid.embedding(
        input=data, size=[input_dim, emb_dim], is_sparse=True)
    conv_3 = fluid.nets.sequence_conv_pool(
        input=emb,
        num_filters=512,
        filter_size=3,
        act="relu",
        pool_type="max") 
    conv_4 = fluid.nets.sequence_conv_pool(
        input=emb,
        num_filters=512,
        filter_size=4,
        act="relu",
        pool_type="max")
    conv_5 = fluid.nets.sequence_conv_pool(
        input=emb,
        num_filters=512,
        filter_size=5,
        act="relu",
        pool_type="max")    
    fc = fluid.layers.fc(input=[conv_3, conv_4,conv_5], size=128, act='relu')           
    rnn_out, last_h, last_c = fluid.layers.lstm(fc,[1, 64, 512], [1, 64, 512], 147, 512, 1, dropout_prob=0.5)
    fc = fluid.layers.fc(input=rnn_out, size=128, act='relu') 
    drop = fluid.layers.dropout(x=fc, dropout_prob=0.5, seed=None) 
    prediction = fluid.layers.fc(input=drop, size=2, act="softmax")
    return prediction`

现在又出现了新的错误：
![Uploading image.png…]()

报错中的请问这个core该如何定义？

**Comment by lliqi-echo** [comment]
---------------------------------------------------------------------------NameError                                 Traceback (most recent call last)<ipython-input-15-597579ca65d2> in <module>
     25         label = fluid.layers.data(name='label', shape=[None,1], dtype='int64')
     26         with fluid.unique_name.guard():
---> 27             predict = cnnlstm(data=seq)
     28             cost = fluid.layers.cross_entropy(input=predict, label=label)  #使用交叉熵损失
     29             avg_cost = fluid.layers.mean(cost)
<ipython-input-14-68f0c491b337> in cnnlstm(data, input_dim, emb_dim)
     21         pool_type="max")    
     22     fc = fluid.layers.fc(input=[conv_3, conv_4,conv_5], size=128, act='relu')
---> 23     rnn_out, last_h, last_c = fluid.layers.lstm(fc,[1, 64, 512], [1, 64, 512], 147, 512, 1, dropout_prob=0.5)
     24     fc = fluid.layers.fc(input=rnn_out, size=128, act='relu')
     25     drop = fluid.layers.dropout(x=fc, dropout_prob=0.5, seed=None)
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/layers/rnn.py in lstm(input, init_h, init_c, max_len, hidden_size, num_layers, dropout_prob, is_bidirec, is_test, name, default_initializer, seed)
   2161 
   2162     cache = helper.create_variable(
-> 2163         persistable=True, type=core.VarDesc.VarType.RAW, stop_gradient=True)
   2164 
   2165     helper.append_op(
NameError: name 'core' is not defined

**Comment by huangjun12** [comment]
> fluid.layers.lstm(fc,[1, 64, 512], [1, 64, 512], 147, 512, 1, dropout_prob=0.5)

init_h和init_c应该是维度为 [num_layers,batch_size,hidden_size]的3-D Tensor，而不是list，参考示例:
init_h = fluid.layers.fill_constant( [num_layers, batch_size, hidden_size], 'float32', 0.0 )
init_c = layers.fill_constant( [num_layers, batch_size, hidden_size], 'float32', 0.0 )

**Comment by lliqi-echo** [comment]
谢谢，您的解答。这部分我已修改，但仍然提示相同的错误：
---------------------------------------------------------------------------NameError                                 Traceback (most recent call last)<ipython-input-21-597579ca65d2> in <module>
     25         label = fluid.layers.data(name='label', shape=[None,1], dtype='int64')
     26         with fluid.unique_name.guard():
---> 27             predict = cnnlstm(data=seq)
     28             cost = fluid.layers.cross_entropy(input=predict, label=label)  #使用交叉熵损失
     29             avg_cost = fluid.layers.mean(cost)
<ipython-input-20-a355141e74ce> in cnnlstm(data, input_dim, emb_dim)
     23     init_h = fluid.layers.fill_constant( [1, 64, 512], 'float32', 0.0 )
     24     init_c = fluid.layers.fill_constant( [1, 64, 512], 'float32', 0.0 )
---> 25     rnn_out, last_h, last_c = fluid.layers.lstm(fc,init_h,init_c, 147, 512, 1, dropout_prob=0.5)
     26     fc = fluid.layers.fc(input=rnn_out, size=128, act='relu')
     27     drop = fluid.layers.dropout(x=fc, dropout_prob=0.5, seed=None)
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/layers/rnn.py in lstm(input, init_h, init_c, max_len, hidden_size, num_layers, dropout_prob, is_bidirec, is_test, name, default_initializer, seed)
   2161 
   2162     cache = helper.create_variable(
-> 2163         persistable=True, type=core.VarDesc.VarType.RAW, stop_gradient=True)
   2164 
   2165     helper.append_op(
NameError: name 'core' is not defined

**Comment by huangjun12** [comment]
你使用的是哪个版本的paddle呢

**Comment by lliqi-echo** [comment]
我在AI studio平台操作的
环境配置：
Python版本
python3.7
框架版本
PaddlePaddle 1.7.2

**Comment by guoshengCS** [comment]
`NameError: name 'core' is not defined` 这个报错确实是1.7.2中的问题，还请升级下。或者使用 https://github.com/PaddlePaddle/Paddle/blob/v1.7.2/python/paddle/fluid/layers/rnn.py#L444 这个示例中的方式实现

另外`sequence_conv_pool`这个输出是非序列，如果希望输出序列数据供lstm使用的话，可以再确认下是否符合预期

**Comment by biubiuyi** [comment]
> `NameError: name 'core' is not defined` 这个报错确实是1.7.2中的问题，还请升级下。或者使用 https://github.com/PaddlePaddle/Paddle/blob/v1.7.2/python/paddle/fluid/layers/rnn.py#L444 这个示例中的方式实现
> 
> 另外`sequence_conv_pool`这个输出是非序列，如果希望输出序列数据供lstm使用的话，可以再确认下是否符合预期

1.7.2版本的GRU会有`NameError: name 'core' is not defined` 这个问题么？

**Comment by guoshengCS** [comment]
1.7.2版本中按照
```python
            inputs = fluid.data(name="inputs",
                                shape=[-1, 32, 128],
                                dtype="float32")
            # cell = fluid.layers.GRUCell(hidden_size=128)
            cell = fluid.layers.LSTMCell(hidden_size=128)
            outputs = fluid.layers.rnn(cell=cell, inputs=inputs)
```
这种方式定义的LSTM或GRU不会有这个问题

**Comment by guoshengCS** [comment]
或者也可以修改下报错的文件`/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/layers/rnn.py`，加上`from .. import core`试下

**Comment by biubiuyi** [comment]
> 1.7.2版本中按照
> 
> ```python
>             inputs = fluid.data(name="inputs",
>                                 shape=[-1, 32, 128],
>                                 dtype="float32")
>             # cell = fluid.layers.GRUCell(hidden_size=128)
>             cell = fluid.layers.LSTMCell(hidden_size=128)
>             outputs = fluid.layers.rnn(cell=cell, inputs=inputs)
> ```
> 
> 这种方式定义的LSTM或GRU不会有这个问题

需要双向lstm怎么修改呢

**Comment by guoshengCS** [comment]
```python
            inputs = fluid.data(name="inputs",
                                shape=[-1, 32, 128],
                                dtype="float32")
            # cell = fluid.layers.GRUCell(hidden_size=128)
            fw_cell = fluid.layers.LSTMCell(hidden_size=128)
            fw_outputs = fluid.layers.rnn(cell= fw_cell, inputs=inputs)
            bw_cell = fluid.layers.LSTMCell(hidden_size=128)
            bw_outputs = fluid.layers.rnn(cell= bw_cell, inputs=inputs, is_reverse=True)
```
双向的像这样
