### ISSUE TITLE
建议添加categorical分布的sample和Log_prob函数

### ISSUE THREAD

**Issue by dbsxdbsx** [PaddlePaddle/Paddle#25607]
- 版本、环境信息
1）PaddlePaddle版本：1.8.2
2）CPU/GPU：CUDA10和cuDNN7.6
3）系统环境：win10x64

我在复现强化学习算法时会需要用到从categorical（离散）分布中采样，目前只能先转成numpy类型来取值，要算log_prob的话则再添加个mask来算，参考了官方模型实现：https://github.com/PaddlePaddle/models/blob/release/1.8/dygraph/reinforcement_learning/actor_critic.py
但这样并不方便，所以希望能够像normal分布那样补充完这些基本接口，谢谢。

**Comment by Aurelius84** [comment]
非常感谢您的反馈和建议，我们会尽快支持`categorical.log_prob`接口。
