### ISSUE TITLE
删除不在使用的Dockerfile

### ISSUE THREAD

**Issue by feng626** [PaddlePaddle/Paddle#25603]
移除废置的 Dockerfile 文件，不再使用，后续也不再维护。

**Comment by 1024er** [comment]
请问是要删除镜像么？

**Comment by feng626** [comment]
> 请问是要删除补充么？

不再使用此Dockerfile构建镜像 后续也不在维护

**Comment by lelelelelez** [comment]
> 请问是要删除镜像么？

将Dockerfile进行整合，原Dockerfile.GCC8现统一升级使用Dockerfile.Inference （即tools/manylinux1/Dockerfile.cuda10_cudnn7_gcc8_ubuntu16） 
现将此issue关闭，如仍有问题，可随时打开。
