### ISSUE TITLE
训练过程中，optimizer从SGD换成Adam，模型不收敛；

### ISSUE THREAD

**Issue by YangYangL** [PaddlePaddle/Paddle#25616]
为使您的问题得到快速解决，在建立Issues前，请您先通过如下方式搜索是否有相似问题:【搜索issue关键字】【使用labels筛选】【官方文档】

如果您没有查询到相似问题，为快速解决您的提问，建立issue时请提供如下细节信息：
- 标题：简洁、精准概括您的问题，例如“Insufficient Memory xxx" ”
- 版本、环境信息：
    1）PaddlePaddle版本：请提供您的PaddlePaddle版本号，例如1.1或CommitID
    2）CPU：预测若用CPU，请提供CPU型号，MKL/OpenBlas/MKLDNN/等数学库使用情况
    3）GPU：预测若用GPU，请提供GPU型号、CUDA和CUDNN版本号
    4）系统环境：请您描述系统类型、版本，例如Mac OS 10.14，Python版本
 注：您可以通过执行[summary_env.py](https://github.com/PaddlePaddle/Paddle/blob/develop/tools/summary_env.py)获取以上信息。
- 训练信息
    1）单机/多机，单卡/多卡
    2）显存信息
    3）Operator信息
- 复现信息：如为报错，请给出复现环境、复现步骤
- 问题描述：请详细描述您的问题，同步贴出报错信息、日志、可复现的代码片段

Thank you for contributing to PaddlePaddle.
Before submitting the issue, you could search issue in the github in case that there was a similar issue submitted or resolved before.
If there is no solution,please make sure that this is a training issue including the following details:
**System information**
-PaddlePaddle version （eg.1.1）or CommitID
-CPU: including CPUMKL/OpenBlas/MKLDNN version
-GPU: including CUDA/CUDNN version
-OS Platform (eg.Mac OS 10.14)
-Other imformation: Distriuted training/informantion of operator/
Graphics card storage
Note: You can get most of the information by running [summary_env.py](https://github.com/PaddlePaddle/Paddle/blob/develop/tools/summary_env.py). 
**To Reproduce**
Steps to reproduce the behavior
**Describe your current behavior**
**Code to reproduce the issue**
**Other info / logs**

**Comment by YangYangL** [comment]
版本环境信息：
paddlepaddle1.8.1；
cpu单机训练;
python3.7.7版本;
ubuntu20.04;

训练数据：criteo公开数据集；
训练模型基于官方提供的deepfm模型；

只修改了optimizer，SGD可以正常训练；Adam训练auc到0.59不动了，两个lr都是1e-4，lr*10或者/10都不能收敛

**Comment by Aurelius84** [comment]
> 训练模型基于官方提供的deepfm模型；

请问使用的是PaddleRec里提供的deepfm模型么：https://github.com/PaddlePaddle/PaddleRec/blob/master/models/rank/deepfm/model.py

**Comment by YangYangL** [comment]
是的

**Comment by Aurelius84** [comment]
Adam优化器本身有一些超参，尝试调一下其他beta1和beta2的参数？另外，可否对比下adam和SGD的loss收敛曲线，观察下收敛的值曲线。因为Adam的lr是动态变化的，SGD是保持不变的。
