### ISSUE TITLE
topk中当输入k为tensor时，结果有误

### ISSUE THREAD

**Issue by mamingjie-China** [PaddlePaddle/Paddle#25610]
PaddlePaddle 1.8.1，python3.7
topk中，当输入的k为tensor时，无论tensor的值是多少，结果都是相同
示例代码：
import paddle.fluid as fluid
import paddle.fluid.layers as layers
input2 = layers.data(name="input2", shape=[13, 11], dtype='float32')
vk = fluid.layers.fill_constant(shape=[1], value=6, dtype='int64')
vk_values, vk_indices = layers.topk(input2, k=vk)
print(vk_values, vk_indices)

期望的结果的shape应该是[13, 6]的，但实际运行结果为[13, 1]
![image](https://user-images.githubusercontent.com/52770436/87896653-77ec8980-ca7b-11ea-9a4a-01945c041b89.png)

**Comment by Aurelius84** [comment]
感谢您的反馈。

问题已经定位，原因是输出shape始终为[13, 1]是因为输入的k是个Variable类型，在组网编译期k的数据未知，因此在编译期使用了k为int时的默认值1进行了shape推导，在实际执行时输出的shape为[13, 1]。

这里的问题在于如果k为Variable，可能导致始终返回[13, 1]导致后续组网shape对不上问题，会进行修复。

**Comment by bjjwwang** [comment]
目前可能没办法修复，在思考可能需要禁用输入为tensor的情况

**Comment by Aurelius84** [comment]
> 目前可能没办法修复，在思考可能需要禁用输入为tensor的情况

如果 k 为Tensor类型时，编译期把输出的shape推导为[13, -1]呢？

**Comment by mamingjie-China** [comment]
> > 目前可能没办法修复，在思考可能需要禁用输入为tensor的情况
> 
> 如果 k 为Tensor类型时，编译期把输出的shape推导为[13, -1]呢？

是在做X2Paddle转换一个模型的时候遇到的这个bug，这里有办法绕开tensor的输入，可以把tensor的值给infer出来。但topk另外一个排序的bug希望能够尽快修复。

**Comment by bjjwwang** [comment]
> > 目前可能没办法修复，在思考可能需要禁用输入为tensor的情况
> 
> 如果 k 为Tensor类型时，编译期把输出的shape推导为[13, -1]呢？

按我的理解 只有第一个维度可以是-1， 第二个维度应该是不行的。不知道我会不会理解有误
