### ISSUE TITLE
能否添加一个包，类似torch.cuda，能够提供一些cuda的基本查询功能

### ISSUE THREAD

**Issue by WenmuZhou** [PaddlePaddle/Paddle#25619]
需要的功能如下
1. 查看cuda是否可用，类似torch.cuda.is_available()
2. 查看可用的显卡数量，类似torch.cuda.device_count()

**Comment by Aurelius84** [comment]
上述功能都可以调用[cuda_places接口](https://www.paddlepaddle.org.cn/documentation/docs/zh/api_cn/fluid_cn/cuda_places_cn.html#cuda-places)

1. 查看cuda是否可用
```python
is_available = len(fluid.cuda_places()) > 0
```

2. 查看可用的显卡数量
```python
import paddle.fluid as fluid
cuda_places = fluid.cuda_places()
```

**Comment by WenmuZhou** [comment]
当安装的是cpu版本的paddle时，fluid.cuda_places() 选择报错而不是返回0，这是有什么考量吗？

**Comment by Aurelius84** [comment]
> 当安装的是cpu版本的paddle时，fluid.cuda_places() 选择报错而不是返回0，这是有什么考量吗？

fluid.cuda_places() 这个接口在调用时，会检查当前安装的paddle是否是gpu版本。

感谢您的反馈，我们会优化相关接口，满足类似功能需求。

**Comment by GuanRainy** [comment]
try fluid.is_compiled_with_cuda()
