### ISSUE TITLE
Tensor部分文档有误，获取tensor的shape是通过成员变量获取，而非文档中的通过shape方法获取

### ISSUE THREAD

**Issue by GT-ZhangAcer** [PaddlePaddle/Paddle#25622]
PaddlePaddle版本：1.8
文档链接：https://www.paddlepaddle.org.cn/documentation/docs/zh/api_cn/fluid_cn/Tensor_cn.html#shape-self-paddle-fluid-core-avx-tensor-list-int
```
import paddle.fluid as fluid
import numpy as np

t = fluid.Tensor()
t.set(np.ndarray([5, 30]), fluid.CPUPlace())
print(t.shape())  # 此处文档有误，需要更改为print(t.shape)
```
<img width="944" alt="图片" src="https://user-images.githubusercontent.com/46156734/87930502-ca996600-caba-11ea-808f-43d59dd673b9.png">

**Comment by Aurelius84** [comment]
感谢您的反馈。

我这边使用1.8.0和1.8.3版本，print(t.shape())都是没有问题的。

**Comment by GT-ZhangAcer** [comment]
我的疏忽，没有问清楚用户所使用的版本，感谢~
