### ISSUE TITLE
topk运算结果中，indices结果不正确

### ISSUE THREAD

**Issue by mamingjie-China** [PaddlePaddle/Paddle#25626]
当topk的输入中，出现相同大小的值时，运算结果中，indices的结果在GPU和CPU版本的Paddle中不一致，且不同机器，均在CPU版本下，运算结果也不相同。初步看了一下代码，应该是在排序的时候，所使用的排序算法为不稳定排序所致。
示例代码
import paddle.fluid as fluid
import numpy as np
def gen_data():
    return {
        "input": np.array([[[2, 2, 2, 2], [3,3,2,3], [4, 4, 3, 4]], [[5, 5, 6, 6], [7,7,7,7], [6, 7, 10, 8]]], dtype="float32")
    }

input = fluid.data(name="input", shape=[2,3,4], dtype='float32')
z = fluid.layers.topk(input=input, k=2, name='z')
place = fluid.CPUPlace()
exe = fluid.Executor(place)
print(gen_data()["input"].shape)
print(gen_data()["input"])
z_value, z_index = exe.run(feed=gen_data(),
                    fetch_list=[z[0].name, z[1].name])
print(z_value,"###############", z_index)
CPU结果
![image](https://user-images.githubusercontent.com/52770436/87937992-6bdae900-cac8-11ea-8255-90d0f457bf42.png)
GPU结果
![image](https://user-images.githubusercontent.com/52770436/87938013-74cbba80-cac8-11ea-8ce6-3d506fdc584f.png)

**Comment by Aurelius84** [comment]
感谢反馈。经确认，topk的CPUKernel底层实现调用了`std::partial_sort`，这个算法是不稳定的。我们会修复这个问题。
