### ISSUE TITLE
有用户建议更换Docker默认Python版本

### ISSUE THREAD

**Issue by GT-ZhangAcer** [PaddlePaddle/Paddle#25621]
飞桨1.8 Docker版本中su虽然内置了3.5~3.7版本Python，但默认是Python3.5。部分PaddleClas用户表示在Docker上运行需要3.6+版本支持，希望可以更换默认Docker的Python版本为3.7.
<img width="423" alt="图片" src="https://user-images.githubusercontent.com/46156734/87929994-e2bcb580-cab9-11ea-9853-643fa13ca125.png">

**Comment by shippingwang** [comment]
ppcls并没有要求3.6，您是怎么安装的？

**Comment by shippingwang** [comment]
这个是visualdl的要求 我觉看下visualdl能否支持py3.5？或者不用visualdl功能就将requirement里的visualdl删除吧
