### ISSUE TITLE
fs.cc/mmap_allocator.cc编译报错

### ISSUE THREAD

**Issue by yuewuya20180928** [PaddlePaddle/Paddle#25629]
环境：
    1）PaddlePaddle版本：release/1.8
    2）CPU：X86_64
    3）GPU：无
    4）系统环境：UBUNTU20、Python3.8
    5）G++：g++ (Ubuntu 9.3.0-10ubuntu2) 9.3.0
- 安装方式信息：
1）pip安装/docker安装
2）本地编译：请提供cmake命令，编译命令：
cmake .. -DPY_VERSION=3.8 -DWITH_GPU=OFF -DWITH_TESTING=OFF -DCMAKE_BUILD_TYPE=Release -DON_INFER=ON
make clean
make -j8
编译报错：
Scanning dependencies of target system_allocator
[  6%] Building CXX object paddle/fluid/memory/detail/CMakeFiles/system_allocator.dir/system_allocator.cc.o
[  6%] Linking CXX static library liballocator.a
[  6%] Built target allocator
Scanning dependencies of target device_memory_aligment
[  6%] Building CXX object paddle/fluid/platform/CMakeFiles/device_memory_aligment.dir/device_memory_aligment.cc.o
In file included from /home/yuewuya/Public/openSource/Paddle/paddle/fluid/framework/io/shell.h:32,
                 from /home/yuewuya/Public/openSource/Paddle/paddle/fluid/framework/io/fs.h:22,
                 from /home/yuewuya/Public/openSource/Paddle/paddle/fluid/framework/io/fs.cc:15:
/home/yuewuya/Public/openSource/Paddle/paddle/fluid/string/string_helper.h: In instantiation of ‘std::string paddle::string::format_string(const char*, ARGS&& ...) [with ARGS = {const char*, const char*}; std::string = std::__cxx11::basic_string<char>]’:
/home/yuewuya/Public/openSource/Paddle/paddle/fluid/framework/io/fs.cc:30:46:   required from here
/home/yuewuya/Public/openSource/Paddle/paddle/fluid/string/string_helper.h:54:23: error: moving a local object in a return statement prevents copy elision [-Werror=pessimizing-move]
   54 |   return std::move(str);
      |                       ^
/home/yuewuya/Public/openSource/Paddle/paddle/fluid/string/string_helper.h:54:23: note: remove ‘std::move’ call
/home/yuewuya/Public/openSource/Paddle/paddle/fluid/string/string_helper.h: In instantiation of ‘std::string paddle::string::format_string(const char*, ARGS&& ...) [with ARGS = {const char*}; std::string = std::__cxx11::basic_string<char>]’:
/home/yuewuya/Public/openSource/Paddle/paddle/fluid/framework/io/fs.cc:115:71:   required from here
/home/yuewuya/Public/openSource/Paddle/paddle/fluid/string/string_helper.h:54:23: error: moving a local object in a return statement prevents copy elision [-Werror=pessimizing-move]
/home/yuewuya/Public/openSource/Paddle/paddle/fluid/string/string_helper.h:54:23: note: remove ‘std::move’ call
/home/yuewuya/Public/openSource/Paddle/paddle/fluid/string/string_helper.h: In instantiation of ‘std::string paddle::string::format_string(const char*, ARGS&& ...) [with ARGS = {const char*, const char*, const char*}; std::string = std::__cxx11::basic_string<char>]’:
/home/yuewuya/Public/openSource/Paddle/paddle/fluid/framework/io/fs.cc:345:78:   required from here
/home/yuewuya/Public/openSource/Paddle/paddle/fluid/string/string_helper.h:54:23: error: moving a local object in a return statement prevents copy elision [-Werror=pessimizing-move]
/home/yuewuya/Public/openSource/Paddle/paddle/fluid/string/string_helper.h:54:23: note: remove ‘std::move’ call
Scanning dependencies of target mmap_allocator
[  6%] Building CXX object paddle/fluid/memory/allocation/CMakeFiles/mmap_allocator.dir/mmap_allocator.cc.o
[  6%] Linking CXX static library libdynload_mklml.a
[  6%] Built target dynload_mklml
[  6%] Linking CXX static library libmemory_block.a
[  6%] Built target memory_block
In file included from /home/yuewuya/Public/openSource/Paddle/paddle/fluid/framework/inlined_vector.h:18,
                 from /home/yuewuya/Public/openSource/Paddle/paddle/fluid/memory/allocation/allocator.h:21,
                 from /home/yuewuya/Public/openSource/Paddle/paddle/fluid/memory/allocation/mmap_allocator.h:25,
                 from /home/yuewuya/Public/openSource/Paddle/paddle/fluid/memory/allocation/mmap_allocator.cc:17:
/home/yuewuya/Public/openSource/Paddle/paddle/fluid/memory/allocation/mmap_allocator.cc: In destructor ‘virtual paddle::memory::allocation::MemoryMapWriterAllocation::~MemoryMapWriterAllocation()’:
/home/yuewuya/Public/openSource/Paddle/paddle/fluid/platform/enforce.h:244:67: warning: throw will always call terminate() [-Wterminate]
  244 |         ::paddle::string::Sprintf(__VA_ARGS__), __FILE__, __LINE__); \
      |                                                                   ^
/home/yuewuya/Public/openSource/Paddle/paddle/fluid/platform/enforce.h:348:7: note: in expansion of macro ‘__THROW_ERROR_INTERNAL__’
  348 |       __THROW_ERROR_INTERNAL__(                                                \
      |       ^~~~~~~~~~~~~~~~~~~~~~~~
/home/yuewuya/Public/openSource/Paddle/paddle/fluid/platform/enforce.h:362:3: note: in expansion of macro ‘__PADDLE_BINARY_COMPARE’
  362 |   __PADDLE_BINARY_COMPARE(__VAL0, __VAL1, !=, ==, __VA_ARGS__)
      |   ^~~~~~~~~~~~~~~~~~~~~~~
/home/yuewuya/Public/openSource/Paddle/paddle/fluid/memory/allocation/mmap_allocator.cc:35:3: note: in expansion of macro ‘PADDLE_ENFORCE_NE’
   35 |   PADDLE_ENFORCE_NE(
      |   ^~~~~~~~~~~~~~~~~
/home/yuewuya/Public/openSource/Paddle/paddle/fluid/platform/enforce.h:244:67: note: in C++11 destructors default to noexcept
  244 |         ::paddle::string::Sprintf(__VA_ARGS__), __FILE__, __LINE__); \
      |                                                                   ^
/home/yuewuya/Public/openSource/Paddle/paddle/fluid/platform/enforce.h:348:7: note: in expansion of macro ‘__THROW_ERROR_INTERNAL__’
  348 |       __THROW_ERROR_INTERNAL__(                                                \
      |       ^~~~~~~~~~~~~~~~~~~~~~~~
/home/yuewuya/Public/openSource/Paddle/paddle/fluid/platform/enforce.h:362:3: note: in expansion of macro ‘__PADDLE_BINARY_COMPARE’
  362 |   __PADDLE_BINARY_COMPARE(__VAL0, __VAL1, !=, ==, __VA_ARGS__)
      |   ^~~~~~~~~~~~~~~~~~~~~~~
/home/yuewuya/Public/openSource/Paddle/paddle/fluid/memory/allocation/mmap_allocator.cc:35:3: note: in expansion of macro ‘PADDLE_ENFORCE_NE’
   35 |   PADDLE_ENFORCE_NE(
      |   ^~~~~~~~~~~~~~~~~
/home/yuewuya/Public/openSource/Paddle/paddle/fluid/memory/allocation/mmap_allocator.cc: In destructor ‘virtual paddle::memory::allocation::MemoryMapReaderAllocation::~MemoryMapReaderAllocation()’:
/home/yuewuya/Public/openSource/Paddle/paddle/fluid/platform/enforce.h:244:67: warning: throw will always call terminate() [-Wterminate]
  244 |         ::paddle::string::Sprintf(__VA_ARGS__), __FILE__, __LINE__); \
      |                                                                   ^
/home/yuewuya/Public/openSource/Paddle/paddle/fluid/platform/enforce.h:348:7: note: in expansion of macro ‘__THROW_ERROR_INTERNAL__’
  348 |       __THROW_ERROR_INTERNAL__(                                                \
      |       ^~~~~~~~~~~~~~~~~~~~~~~~
/home/yuewuya/Public/openSource/Paddle/paddle/fluid/platform/enforce.h:362:3: note: in expansion of macro ‘__PADDLE_BINARY_COMPARE’
  362 |   __PADDLE_BINARY_COMPARE(__VAL0, __VAL1, !=, ==, __VA_ARGS__)
      |   ^~~~~~~~~~~~~~~~~~~~~~~
/home/yuewuya/Public/openSource/Paddle/paddle/fluid/memory/allocation/mmap_allocator.cc:42:3: note: in expansion of macro ‘PADDLE_ENFORCE_NE’
   42 |   PADDLE_ENFORCE_NE(
      |   ^~~~~~~~~~~~~~~~~
/home/yuewuya/Public/openSource/Paddle/paddle/fluid/platform/enforce.h:244:67: note: in C++11 destructors default to noexcept
  244 |         ::paddle::string::Sprintf(__VA_ARGS__), __FILE__, __LINE__); \
      |                                                                   ^
/home/yuewuya/Public/openSource/Paddle/paddle/fluid/platform/enforce.h:348:7: note: in expansion of macro ‘__THROW_ERROR_INTERNAL__’
  348 |       __THROW_ERROR_INTERNAL__(                                                \
      |       ^~~~~~~~~~~~~~~~~~~~~~~~
/home/yuewuya/Public/openSource/Paddle/paddle/fluid/platform/enforce.h:362:3: note: in expansion of macro ‘__PADDLE_BINARY_COMPARE’
  362 |   __PADDLE_BINARY_COMPARE(__VAL0, __VAL1, !=, ==, __VA_ARGS__)
      |   ^~~~~~~~~~~~~~~~~~~~~~~
/home/yuewuya/Public/openSource/Paddle/paddle/fluid/memory/allocation/mmap_allocator.cc:42:3: note: in expansion of macro ‘PADDLE_ENFORCE_NE’
   42 |   PADDLE_ENFORCE_NE(
      |   ^~~~~~~~~~~~~~~~~
/home/yuewuya/Public/openSource/Paddle/paddle/fluid/memory/allocation/mmap_allocator.cc: In function ‘std::string paddle::memory::allocation::GetIPCName()’:
/home/yuewuya/Public/openSource/Paddle/paddle/fluid/memory/allocation/mmap_allocator.cc:64:19: error: moving a local object in a return statement prevents copy elision [-Werror=pessimizing-move]
   64 |   return std::move(handle);
      |          ~~~~~~~~~^~~~~~~~
/home/yuewuya/Public/openSource/Paddle/paddle/fluid/memory/allocation/mmap_allocator.cc:64:19: note: remove ‘std::move’ call
[  6%] Linking CXX static library libdevice_memory_aligment.a

**Comment by Aurelius84** [comment]
您好像使用的GCC版本是9.3.0，版本太高了。编译报错是因为：
```
error: moving a local object in a return statement prevents copy elision [-Werror=pessimizing-move]
```
你可以尝试使用GCC8版本解决这个问题。

**Comment by luotao1** [comment]
@Aurelius84 是否需要在代码里提示建议使用GCC8.2呢？

**Comment by yuewuya20180928** [comment]
使用gcc8.4.0有如下的报错：
(paddle-venv) yuewuya@yuewuya-RedmiBook-14:~/Public/openSource/Paddle/build$ make clean
make -j8
(paddle-venv) yuewuya@yuewuya-RedmiBook-14:~/Public/openSource/Paddle/build$ make -j8
[  0%] Built target extern_boost
[  1%] Built target extern_dlpack
[  2%] Built target extern_warpctc
[  2%] Built target extern_xxhash
[  2%] No update step for 'extern_eigen3'
[  3%] Built target extern_threadpool
/bin/sh: line 0: cd: /home/yuewuya/Public/openSource/Paddle/build/third_party/eigen3/src/extern_eigen3: No such file or directory
make[2]: *** [CMakeFiles/extern_eigen3.dir/build.make:97: third_party/eigen3/src/extern_eigen3-stamp/extern_eigen3-update] Error 1
make[1]: *** [CMakeFiles/Makefile2:2586: CMakeFiles/extern_eigen3.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[  3%] Built target extern_zlib
[  3%] Built target extern_download_cudaerror
[  3%] Built target extern_pybind
[  4%] Built target extern_xbyak
[  4%] Built target extern_gflags
[  4%] Built target extern_mklml
[  4%] Performing update step for 'extern_mkldnn'
/bin/sh: line 0: cd: /home/yuewuya/Public/openSource/Paddle/build/third_party/mkldnn/src/extern_mkldnn: No such file or directory
make[2]: *** [CMakeFiles/extern_mkldnn.dir/build.make:96: third_party/mkldnn/src/extern_mkldnn-stamp/extern_mkldnn-update] Error 1
make[1]: *** [CMakeFiles/Makefile2:2932: CMakeFiles/extern_mkldnn.dir/all] Error 2
make: *** [Makefile:130: all] Error 2

**Comment by Aurelius84** [comment]
从报错上来看，是依赖的三方eigen库、mkldnn没有成功下载下来。日志前面是否有出现git clone未完成的日志，可能需要网络代理。

**Comment by Aurelius84** [comment]
> @Aurelius84 是否需要在代码里提示建议使用GCC8.2呢？

嗯，这个可以在cmake文件里添加下检查

**Comment by yuewuya20180928** [comment]
README.md
Eigen's official git repository have been moved to https://gitlab.com/libeigen/eigen

For convenience, this deprecated mirror repository will be kept as is for a short period of time before being deleted.

So please update your git clones & submodules to https://gitlab.com/libeigen/eigen.git as soon as possible.

Also note that it is not possible keep it sync with the new official git repository because the hashes do not match.

Eigen开源库的官方仓库已经改为https://gitlab.com/libeigen/eigen了，为什么不从新的git仓下载，而是从以前的git仓下载？
@Aurelius84

**Comment by Aurelius84** [comment]
@yuewuya20180928 目前依赖的eigen库配置的就是从最新的repo地址下载的，配置在这里：https://github.com/PaddlePaddle/Paddle/blob/develop/cmake/external/eigen.cmake#L25

**Comment by yuewuya20180928** [comment]
/home/yuewuya/Public/openSource/Paddle/paddle/fluid/operators/reduce_ops/reduce_mean_op.cc:103:1:   required from here
/home/yuewuya/Public/openSource/Paddle/build/third_party/eigen3/src/extern_eigen3/unsupported/Eigen/CXX11/src/Tensor/TensorFunctors.h:169:18: error: no match for ‘operator/’ (operand types are ‘const paddle::platform::float16’ and ‘const DenseIndex’ {aka ‘const long int’})
     return accum / scalarCount_;
            ~~~~~~^~~~~~~~~~~~~~
/home/yuewuya/Public/openSource/Paddle/build/third_party/eigen3/src/extern_eigen3/unsupported/Eigen/CXX11/src/Tensor/TensorFunctors.h:169:18: note: candidate: ‘operator/(double, Eigen::DenseIndex {aka long int})’ <built-in>

**Comment by Aurelius84** [comment]
@yuewuya20180928 paddle依赖了指定commit的eigen版本`917060c364181f33a735dc023818d5a54f60e54c `，上述错误应该都是编译器版本过高导致编译不通过。

您可以把gcc版本降到gcc8.2试下，后续我们会更全面的支持更高版本的gcc

**Comment by yuewuya20180928** [comment]
@Aurelius84 多核编译会报错，单核编译不会报错，可能是什么原因造成的？

**Comment by yuewuya20180928** [comment]
@Aurelius84 使用GCC7.5编译还是有这个问题：
/home/yuewuya/Public/openSource/Paddle/build/third_party/eigen3/src/extern_eigen3/unsupported/Eigen/CXX11/src/Tensor/TensorFunctors.h:169:18: error: no match for ‘operator/’ (operand types are ‘const paddle::platform::float16’ and ‘const DenseIndex {aka const long int}’)
     return accum / scalarCount_;
官方推荐使用哪个版本的GCC？如果GCC兼容那就是下载的eigen3的资源的问题了

**Comment by yuewuya20180928** [comment]
(paddle-venv) yuewuya@yuewuya-RedmiBook-14:~/Public/openSource/Paddle/build/python/dist$ pip install -U paddlepaddle-1.8.3-cp38-cp38-linux_x86_64.whl
Processing ./paddlepaddle-1.8.3-cp38-cp38-linux_x86_64.whl
Collecting funcsigs
  Downloading funcsigs-1.0.2-py2.py3-none-any.whl (17 kB)
Collecting opencv-python
  Downloading opencv_python-4.3.0.36-cp38-cp38-manylinux2014_x86_64.whl (43.7 MB)
     |█████████████████████████████▋  | 40.5 MB 14 kB/s eta 0:03:35ERROR: Exception:
Traceback (most recent call last):
  File "/home/yuewuya/.virtualenvs/paddle-venv/lib/python3.8/site-packages/pip/_vendor/urllib3/response.py", line 425, in _error_catcher
    yield
  File "/home/yuewuya/.virtualenvs/paddle-venv/lib/python3.8/site-packages/pip/_vendor/urllib3/response.py", line 507, in read
    data = self._fp.read(amt) if not fp_closed else b""
  File "/home/yuewuya/.virtualenvs/paddle-venv/lib/python3.8/site-packages/pip/_vendor/cachecontrol/filewrapper.py", line 62, in read
    data = self.__fp.read(amt)
  File "/usr/lib/python3.8/http/client.py", line 454, in read
    n = self.readinto(b)
  File "/usr/lib/python3.8/http/client.py", line 498, in readinto
    n = self.fp.readinto(b)
  File "/usr/lib/python3.8/socket.py", line 669, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib/python3.8/ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib/python3.8/ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/yuewuya/.virtualenvs/paddle-venv/lib/python3.8/site-packages/pip/_internal/cli/base_command.py", line 188, in _main
    status = self.run(options, args)
  File "/home/yuewuya/.virtualenvs/paddle-venv/lib/python3.8/site-packages/pip/_internal/cli/req_command.py", line 185, in wrapper
    return func(self, options, args)
  File "/home/yuewuya/.virtualenvs/paddle-venv/lib/python3.8/site-packages/pip/_internal/commands/install.py", line 332, in run
    requirement_set = resolver.resolve(
  File "/home/yuewuya/.virtualenvs/paddle-venv/lib/python3.8/site-packages/pip/_internal/resolution/legacy/resolver.py", line 179, in resolve
    discovered_reqs.extend(self._resolve_one(requirement_set, req))
  File "/home/yuewuya/.virtualenvs/paddle-venv/lib/python3.8/site-packages/pip/_internal/resolution/legacy/resolver.py", line 362, in _resolve_one
    abstract_dist = self._get_abstract_dist_for(req_to_install)
  File "/home/yuewuya/.virtualenvs/paddle-venv/lib/python3.8/site-packages/pip/_internal/resolution/legacy/resolver.py", line 314, in _get_abstract_dist_for
    abstract_dist = self.preparer.prepare_linked_requirement(req)
  File "/home/yuewuya/.virtualenvs/paddle-venv/lib/python3.8/site-packages/pip/_internal/operations/prepare.py", line 467, in prepare_linked_requirement
    local_file = unpack_url(
  File "/home/yuewuya/.virtualenvs/paddle-venv/lib/python3.8/site-packages/pip/_internal/operations/prepare.py", line 255, in unpack_url
    file = get_http_url(
  File "/home/yuewuya/.virtualenvs/paddle-venv/lib/python3.8/site-packages/pip/_internal/operations/prepare.py", line 129, in get_http_url
    from_path, content_type = _download_http_url(
  File "/home/yuewuya/.virtualenvs/paddle-venv/lib/python3.8/site-packages/pip/_internal/operations/prepare.py", line 281, in _download_http_url
    for chunk in download.chunks:
  File "/home/yuewuya/.virtualenvs/paddle-venv/lib/python3.8/site-packages/pip/_internal/cli/progress_bars.py", line 166, in iter
    for x in it:
  File "/home/yuewuya/.virtualenvs/paddle-venv/lib/python3.8/site-packages/pip/_internal/network/utils.py", line 15, in response_chunks
    for chunk in response.raw.stream(
  File "/home/yuewuya/.virtualenvs/paddle-venv/lib/python3.8/site-packages/pip/_vendor/urllib3/response.py", line 564, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "/home/yuewuya/.virtualenvs/paddle-venv/lib/python3.8/site-packages/pip/_vendor/urllib3/response.py", line 529, in read
    raise IncompleteRead(self._fp_bytes_read, self.length_remaining)
  File "/usr/lib/python3.8/contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/yuewuya/.virtualenvs/paddle-venv/lib/python3.8/site-packages/pip/_vendor/urllib3/response.py", line 430, in _error_catcher
    raise ReadTimeoutError(self._pool, None, "Read timed out.")
pip._vendor.urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Read timed out.
(paddle-venv) yuewuya@yuewuya-RedmiBook-14:~/Public/openSource/Paddle/build/python/dist$

**Comment by Aurelius84** [comment]
> 官方推荐使用哪个版本的GCC？

官网推荐GCC8.2

**Comment by Aurelius84** [comment]
> pip._vendor.urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Read timed out.

@yuewuya20180928 报错来看是下载安装其他依赖包时，中断了，你可以使用清华的源试下：
```bash
pip install -U {your_whl} -i https://pypi.tuna.tsinghua.edu.cn/simple
```

**Comment by yuewuya20180928** [comment]
pip install -U paddlepaddle-1.8.3-cp38-cp38-linux_x86_64.whl -i https://pypi.tuna.tsinghua.edu.cn/simple
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Processing ./paddlepaddle-1.8.3-cp38-cp38-linux_x86_64.whl
Collecting funcsigs
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/69/cb/f5be453359271714c01b9bd06126eaf2e368f1fddfff30818754b5ac2328/funcsigs-1.0.2-py2.py3-none-any.whl (17 kB)
Requirement already satisfied, skipping upgrade: six in /home/yuewuya/.virtualenvs/paddle-venv/lib/python3.8/site-packages (from paddlepaddle==1.8.3) (1.15.0)
Collecting graphviz
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/62/dc/9dd6a6b9b8977248e165e075b109eea6e8eac71faa28ca378c3d98e54fbe/graphviz-0.14.1-py2.py3-none-any.whl (18 kB)
Collecting scipy<=1.3.1; python_version >= "3.5"
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/ee/5b/5afcd1c46f97b3c2ac3489dbc95d6ca28eacf8e3634e51f495da68d97f0f/scipy-1.3.1.tar.gz (23.6 MB)
     |████████████████████████████████| 23.6 MB 2.6 MB/s 
  Installing build dependencies ... error
  ERROR: Command errored out with exit status 1:
   command: /home/yuewuya/.virtualenvs/paddle-venv/bin/python /home/yuewuya/.virtualenvs/paddle-venv/lib/python3.8/site-packages/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-1f04bfh5/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.tuna.tsinghua.edu.cn/simple -- wheel setuptools 'Cython>=0.29.2' 'numpy==1.13.3; python_version=='"'"'3.5'"'"' and platform_system!='"'"'AIX'"'"'' 'numpy==1.13.3; python_version=='"'"'3.6'"'"' and platform_system!='"'"'AIX'"'"'' 'numpy==1.14.5; python_version>='"'"'3.7'"'"' and platform_system!='"'"'AIX'"'"'' 'numpy==1.16.0; python_version=='"'"'3.5'"'"' and platform_system=='"'"'AIX'"'"'' 'numpy==1.16.0; python_version=='"'"'3.6'"'"' and platform_system=='"'"'AIX'"'"'' 'numpy==1.16.0; python_version>='"'"'3.7'"'"' and platform_system=='"'"'AIX'"'"''
       cwd: None
  Complete output (2595 lines):
  Ignoring numpy: markers 'python_version == "3.5" and platform_system != "AIX"' don't match your environment
  Ignoring numpy: markers 'python_version == "3.6" and platform_system != "AIX"' don't match your environment
  Ignoring numpy: markers 'python_version == "3.5" and platform_system == "AIX"' don't match your environment
  Ignoring numpy: markers 'python_version == "3.6" and platform_system == "AIX"' don't match your environment
  Ignoring numpy: markers 'python_version >= "3.7" and platform_system == "AIX"' don't match your environment
使用清华源安装其他依赖报错，这个是什么原因导致的？是本地环境不兼容吗？

**Comment by yuewuya20180928** [comment]
大佬们帮帮忙啊，环境安装的问题困扰了很久了，万分感谢

**Comment by Aurelius84** [comment]
@yuewuya20180928 你单独先尝试装一下numpy或scipy试下呢？

这个好像没有与你platform和python版本对应的scipy库？ 或者你尝试下python3.7，python3.6
