### ISSUE TITLE
Question on memory allocators.

### ISSUE THREAD

**Issue by jczaja** [PaddlePaddle/Paddle#25645]
By default PaddlePaddle is NOT using system allocator for memory allocation. FLAGS_use_system_allocator = False.
https://github.com/PaddlePaddle/Paddle/blob/dfb3ae1b9b44f351526d0f5b04e2656e127ed9be/paddle/fluid/memory/allocation/allocator_facade.cc#L117

 What is  adventage of NOT using system allocator for CPU workloads?

**Comment by luotao1** [comment]
@zhiqiu Could you help see it?

**Comment by zhiqiu** [comment]
If `FLAGS_use_system_allocator == True`, the memory allocation calls the system API `malloc` or `cudaMalloc` directly, which may affect performance.

**Comment by jczaja** [comment]
@zhiqiu  Thanks. So is there a way to control how much memory should paddlepaddle allocator pre allocate ? Perhaps extending ENV var controlling amount of memory for start would be useful to reduce number of memory used  for some smaller models ?

**Comment by zhiqiu** [comment]
> start

Currently, `Paddle` uses `naive_best_fit` allocation strategy on CPU place, which pre-allocates a chunk of  memory to use.
By default, the size of pre-allocated CPU meomry is 500mb, which is controlled by `FLAGS_initial_cpu_memory_in_mb`.
https://github.com/PaddlePaddle/Paddle/blob/65b97d62157faad0909cf48bb441c92af36e5655/paddle/fluid/platform/flags.cc#L347

**Comment by zhiqiu** [comment]
> @zhiqiu Thanks. So is there a way to control how much memory should paddlepaddle allocator pre allocate ? Perhaps extending ENV var controlling amount of memory for start would be useful to reduce number of memory used for some smaller models ?

Currently, `Paddle` uses `naive_best_fit` allocation strategy on CPU place, which pre-allocates a chunk of  memory to use.
By default, the size of pre-allocated CPU meomry is 500mb, which is controlled by `FLAGS_initial_cpu_memory_in_mb`.

https://github.com/PaddlePaddle/Paddle/blob/65b97d62157faad0909cf48bb441c92af36e5655/paddle/fluid/platform/flags.cc#L347-L360

So, we can set `FLAGS_initial_cpu_memory_in_mb` to lower value, like 100, to reduce number of memory used for some smaller models.

**Comment by jczaja** [comment]
@zhiqiu Thanks for explanation.
