### ISSUE TITLE
dropout的使用

### ISSUE THREAD

**Issue by xcwei** [PaddlePaddle/Paddle#25640]
如果我用了fluid.layers.dropout，那我是需要在train的网络结构里把is_test设置为False，在测试的网络里设置为True吗
我是用的clone(for_test=True)得到的测试网络，这个要怎么处理，clone的时候会自动把dropout设置为is_test吗

**Comment by LDOUBLEV** [comment]
> 如果我用了fluid.layers.dropout，那我是需要在train的网络结构里把is_test设置为False，在测试的网络里设置为True吗
> 我是用的clone(for_test=True)得到的测试网络，这个要怎么处理，clone的时候会自动把dropout设置为is_test吗

测试网络里要设置为true
clone(for_test=True)得到的测试网络，clone的时候会自动把dropout设置为true
