### ISSUE TITLE
【论文复现】fluid.dygraph.grad()不能求导 PermissionDeniedError: Target var generated_var_0@GRAD should not be nullptr

### ISSUE THREAD

**Issue by ruyijidan** [PaddlePaddle/Paddle#25656]
官方例子没问题.改用简单网络模型也可以,但是改用自己的网络就不能求导了,

    1）PaddlePaddle版本：1.8.2-post107
    2）CPU/GPU：NVIDIA-SMI 418.87.00、CUDA10.0和cuDNN版本号:7.6.0
    3）系统环境：请您描述系统类型、版本，ubuntu1804
    4）Python版本号  3.7.7
    5）显存信息 9927MiB/11176MiB

Traceback (most recent call last):
  File "/home/j/Desktop/testcode/test.py", line 585, in <module>
    print(test_dygraph_grad(None))  # [7.]
  File "/home/j/Desktop/testcode/test.py", line 576, in test_dygraph_grad
    grad_outputs=grad_outputs)[0]
  File "<decorator-gen-29>", line 2, in grad
  File "/home/j/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
    return wrapped_func(*args, **kwargs)
  File "/home/j/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/fluid/framework.py", line 216, in __impl__
    return func(*args, **kwargs)
  File "/home/j/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/fluid/dygraph/base.py", line 563, in grad
    create_graph, retain_graph, allow_unused, only_inputs)
paddle.fluid.core_avx.EnforceNotMet: 

--------------------------------------------
C++ Call Stacks (More useful to developers):
--------------------------------------------
0   std::string paddle::platform::GetTraceBackString<std::string const&>(std::string const&, char const*, int)
1   paddle::platform::EnforceNotMet::EnforceNotMet(std::string const&, char const*, int)
2   paddle::imperative::ReadyGradVarInfoMap::GetTarget(paddle::imperative::VariableWrapper const*) const
3   paddle::imperative::PartialGradTask::CreateResult()
4   paddle::imperative::PartialGradTask::Run()
5   paddle::imperative::PartialGradEngine::Execute()

----------------------
Error Message Summary:
----------------------
PermissionDeniedError: Target var generated_var_0@GRAD should not be nullptr
  [Hint: iter->second should not be null.] at (/paddle/paddle/fluid/imperative/partial_grad_engine.cc:501)

**Comment by ruyijidan** [comment]
复现代码贴一下:



import paddle.fluid as fluid
import numpy as np
import paddle
import paddle.fluid as fluid
import math
from paddle.fluid.dygraph.nn import Conv2D, Pool2D, Linear, BatchNorm
from paddle.fluid.param_attr import ParamAttr
from paddle.fluid.regularizer import L2Decay
from paddle.fluid.dygraph.base import to_variable


class ConvBNLayer(fluid.dygraph.Layer):
    """
    卷积 + BN，BN层之后激活函数默认用leaky_relu
    """

    def __init__(self,
                 ch_in,
                 ch_out,
                 filter_size=3,
                 stride=1,
                 groups=1,
                 padding=0,
                 act="leaky",
                 is_test=True,
                 sn=False):
        super(ConvBNLayer, self).__init__()
        self.sn = sn
        if self.sn:
            self.conv = paddle.fluid.dygraph.SpectralNorm(Conv2D(
                num_channels=ch_in,
                num_filters=ch_out,
                filter_size=filter_size,
                stride=stride,
                padding=padding,
                groups=groups,
                param_attr=ParamAttr(
                    initializer=fluid.initializer.Normal(0., 0.02)),
                bias_attr=False,
                act=None), dim=1, power_iters=1)

        else:
            self.conv = Conv2D(
                num_channels=ch_in,
                num_filters=ch_out,
                filter_size=filter_size,
                stride=stride,
                padding=padding,
                groups=groups,
                param_attr=ParamAttr(
                    initializer=fluid.initializer.Normal(0., 0.02)),
                bias_attr=False,
                act=None)

        self.batch_norm = BatchNorm(
            num_channels=ch_out,
            is_test=is_test,
            param_attr=ParamAttr(
                initializer=fluid.initializer.Normal(0., 0.02),
                regularizer=L2Decay(0.)),
            bias_attr=ParamAttr(
                initializer=fluid.initializer.Constant(0.0),
                regularizer=L2Decay(0.)))
        self.act = act

    def forward(self, inputs):
        out = self.conv(inputs)
        out = self.batch_norm(out)
        if self.act == 'leaky':
            out = fluid.layers.leaky_relu(x=out, alpha=0.1)
        return out


class DownSample(fluid.dygraph.Layer):
    """
    下采样，图片尺寸减半，具体实现方式是使用stirde=2的卷积
    """

    def __init__(self,
                 ch_in,
                 ch_out,
                 filter_size=3,
                 stride=2,
                 padding=1,
                 is_test=True):
        super(DownSample, self).__init__()

        self.conv_bn_layer = ConvBNLayer(
            ch_in=ch_in,
            ch_out=ch_out,
            filter_size=filter_size,
            stride=stride,
            padding=padding,
            is_test=is_test)
        self.ch_out = ch_out

    def forward(self, inputs):
        out = self.conv_bn_layer(inputs)
        return out


class BasicBlock(fluid.dygraph.Layer):
    """
    基本残差块的定义，输入x经过两层卷积，然后接第二层卷积的输出和输入x相加
    """

    def __init__(self, ch_in, ch_out, is_test=True):
        super(BasicBlock, self).__init__()

        self.conv1 = ConvBNLayer(
            ch_in=ch_in,
            ch_out=ch_out,
            filter_size=1,
            stride=1,
            padding=0,
            is_test=is_test
        )
        self.conv2 = ConvBNLayer(
            ch_in=ch_out,
            ch_out=ch_out * 2,
            filter_size=3,
            stride=1,
            padding=1,
            is_test=is_test
        )

    def forward(self, inputs):
        conv1 = self.conv1(inputs)
        conv2 = self.conv2(conv1)
        out = fluid.layers.elementwise_add(x=inputs, y=conv2, act=None)
        return out


class LayerWarp(fluid.dygraph.Layer):
    """
    添加多层残差块，组成resblock网络的一个层级
    """

    def __init__(self, ch_in, ch_out, count, is_test=True):
        super(LayerWarp, self).__init__()

        self.basicblock0 = BasicBlock(ch_in,
                                      ch_out,
                                      is_test=is_test)
        self.res_out_list = []
        for i in range(1, count):
            res_out = self.add_sublayer("basic_block_%d" % (i),  # 使用add_sublayer添加子层
                                        BasicBlock(ch_out * 2,
                                                   ch_out,
                                                   is_test=is_test))
            self.res_out_list.append(res_out)

    def forward(self, inputs):
        y = self.basicblock0(inputs)
        for basic_block_i in self.res_out_list:
            y = basic_block_i(y)
        return y


# 定义上采样模块
class Upsample(fluid.dygraph.Layer):
    def __init__(self, scale=2):
        super(Upsample, self).__init__()
        self.scale = scale

    def forward(self, inputs):
        # get dynamic upsample output shape
        shape_nchw = fluid.layers.shape(inputs)
        shape_hw = fluid.layers.slice(shape_nchw, axes=[0], starts=[2], ends=[4])
        shape_hw.stop_gradient = True
        in_shape = fluid.layers.cast(shape_hw, dtype='int32')
        out_shape = in_shape * self.scale
        out_shape.stop_gradient = True

        # reisze by actual_shape
        out = fluid.layers.resize_nearest(
            input=inputs, scale=self.scale, actual_shape=out_shape)
        return out


DarkNet_cfg = {53: ([1, 1, 1, 1])}


class DarkNet53_conv_body(fluid.dygraph.Layer):
    def __init__(self,

                 is_test=True):
        super(DarkNet53_conv_body, self).__init__()
        self.stages = DarkNet_cfg[53]
        self.stages = self.stages[0:5]

        # 第一层卷积
        self.conv0 = ConvBNLayer(
            ch_in=3,
            ch_out=64,
            filter_size=1,
            stride=1,
            padding=0,
            is_test=is_test)

        # 下采样，使用stride=2的卷积来实现
        self.downsample0 = DownSample(
            ch_in=64,
            ch_out=64,
            is_test=is_test)

        # 添加各个层级的实现
        self.darknet53_conv_block_list = []
        self.downsample_list = []
        for i, stage in enumerate(self.stages):
            conv_block = self.add_sublayer(
                "stage_%d" % (i),
                LayerWarp(32 * (2 ** (i + 1)),
                          32 * (2 ** i),
                          stage,
                          is_test=is_test))
            self.darknet53_conv_block_list.append(conv_block)
        # 两个层级之间使用DownSample将尺寸减半
        for i in range(len(self.stages) - 1):
            downsample = self.add_sublayer(
                "stage_%d_downsample" % i,
                DownSample(ch_in=32 * (2 ** (i + 1)),
                           ch_out=32 * (2 ** (i + 2)),
                           is_test=is_test))
            self.downsample_list.append(downsample)

    def forward(self, inputs):
        out = self.conv0(inputs)
        # print("conv1:",out.numpy())
        out = self.downsample0(out)
        # print("dy:",out.numpy())
        blocks = []
        for i, conv_block_i in enumerate(self.darknet53_conv_block_list):  # 依次将各个层级作用在输入上面
            out = conv_block_i(out)
            blocks.append(out)
            if i < len(self.stages) - 1:
                out = self.downsample_list[i](out)
        return blocks[-1:-4:-1]  # 将C0, C1, C2作为返回值




def test_dygraph_grad(grad_outputs=None):
    with fluid.dygraph.guard(fluid.CPUPlace()):
        fluid.enable_dygraph(fluid.CPUPlace())
        x = fluid.layers.fill_constant(shape=[4,3,256,256], value=1.0, dtype='float32')
        
        x.stop_gradient = False
        backbone = DarkNet53_conv_body(is_test=False)
        C0, C1, C2 = backbone(x)



        # If grad_outputs=None, dy1 = [1], dy2 = [1].
        # If grad_outputs=[g1, g2], then:
        #    - dy1 = [1] if g1 is None else g1
        #    - dy2 = [1] if g2 is None else g2

        # Since y1 = x * x, dx = 2 * x * dy1.
        # Since y2 = x * 3, dx = 3 * dy2.
        # Therefore, the final result would be:
        # dx = 2 * x * dy1 + 3 * dy2 = 4 * dy1 + 3 * dy2.

        dx = fluid.dygraph.grad(
            outputs=[C0],
            inputs=[x],
            grad_outputs=grad_outputs)[0]

        return dx.numpy()


THREE = fluid.layers.fill_constant(shape=[4,3,256,256], value=3.0, dtype='float32')
FOUR = fluid.layers.fill_constant(shape=[4,3,256,256], value=4.0, dtype='float32')

# dy1 = [1], dy2 = [1]
print(test_dygraph_grad(None))  # [7.]
print('11111111111111111111111')
# dy1 = [1], dy2 = [4]
print(test_dygraph_grad([None]))  # [16.]
print('22222222222222222222222222222')
# dy1 = [4], dy2 = [1]
print(test_dygraph_grad([FOUR]))  # [19.]
print('333333333333333333333333333333333')
# dy1 = [3], dy2 = [4]
print(test_dygraph_grad([THREE]))  # [24.]
print('4444444444444444444444444444444444')

**Comment by ruyijidan** [comment]
`
import paddle.fluid as fluid
import numpy as np
import paddle
import paddle.fluid as fluid
import math
from paddle.fluid.dygraph.nn import Conv2D, Pool2D, Linear, BatchNorm
from paddle.fluid.param_attr import ParamAttr
from paddle.fluid.regularizer import L2Decay
from paddle.fluid.dygraph.base import to_variable


class ConvBNLayer(fluid.dygraph.Layer):
    """
    卷积 + BN，BN层之后激活函数默认用leaky_relu
    """

    def __init__(self,
                 ch_in,
                 ch_out,
                 filter_size=3,
                 stride=1,
                 groups=1,
                 padding=0,
                 act="leaky",
                 is_test=True,
                 sn=False):
        super(ConvBNLayer, self).__init__()
        self.sn = sn
        if self.sn:
            self.conv = paddle.fluid.dygraph.SpectralNorm(Conv2D(
                num_channels=ch_in,
                num_filters=ch_out,
                filter_size=filter_size,
                stride=stride,
                padding=padding,
                groups=groups,
                param_attr=ParamAttr(
                    initializer=fluid.initializer.Normal(0., 0.02)),
                bias_attr=False,
                act=None), dim=1, power_iters=1)

        else:
            self.conv = Conv2D(
                num_channels=ch_in,
                num_filters=ch_out,
                filter_size=filter_size,
                stride=stride,
                padding=padding,
                groups=groups,
                param_attr=ParamAttr(
                    initializer=fluid.initializer.Normal(0., 0.02)),
                bias_attr=False,
                act=None)

        self.batch_norm = BatchNorm(
            num_channels=ch_out,
            is_test=is_test,
            param_attr=ParamAttr(
                initializer=fluid.initializer.Normal(0., 0.02),
                regularizer=L2Decay(0.)),
            bias_attr=ParamAttr(
                initializer=fluid.initializer.Constant(0.0),
                regularizer=L2Decay(0.)))
        self.act = act

    def forward(self, inputs):
        out = self.conv(inputs)
        out = self.batch_norm(out)
        if self.act == 'leaky':
            out = fluid.layers.leaky_relu(x=out, alpha=0.1)
        return out


class DownSample(fluid.dygraph.Layer):
    """
    下采样，图片尺寸减半，具体实现方式是使用stirde=2的卷积
    """

    def __init__(self,
                 ch_in,
                 ch_out,
                 filter_size=3,
                 stride=2,
                 padding=1,
                 is_test=True):
        super(DownSample, self).__init__()

        self.conv_bn_layer = ConvBNLayer(
            ch_in=ch_in,
            ch_out=ch_out,
            filter_size=filter_size,
            stride=stride,
            padding=padding,
            is_test=is_test)
        self.ch_out = ch_out

    def forward(self, inputs):
        out = self.conv_bn_layer(inputs)
        return out


class BasicBlock(fluid.dygraph.Layer):
    """
    基本残差块的定义，输入x经过两层卷积，然后接第二层卷积的输出和输入x相加
    """

    def __init__(self, ch_in, ch_out, is_test=True):
        super(BasicBlock, self).__init__()

        self.conv1 = ConvBNLayer(
            ch_in=ch_in,
            ch_out=ch_out,
            filter_size=1,
            stride=1,
            padding=0,
            is_test=is_test
        )
        self.conv2 = ConvBNLayer(
            ch_in=ch_out,
            ch_out=ch_out * 2,
            filter_size=3,
            stride=1,
            padding=1,
            is_test=is_test
        )

    def forward(self, inputs):
        conv1 = self.conv1(inputs)
        conv2 = self.conv2(conv1)
        out = fluid.layers.elementwise_add(x=inputs, y=conv2, act=None)
        return out


class LayerWarp(fluid.dygraph.Layer):
    """
    添加多层残差块，组成resblock网络的一个层级
    """

    def __init__(self, ch_in, ch_out, count, is_test=True):
        super(LayerWarp, self).__init__()

        self.basicblock0 = BasicBlock(ch_in,
                                      ch_out,
                                      is_test=is_test)
        self.res_out_list = []
        for i in range(1, count):
            res_out = self.add_sublayer("basic_block_%d" % (i),  # 使用add_sublayer添加子层
                                        BasicBlock(ch_out * 2,
                                                   ch_out,
                                                   is_test=is_test))
            self.res_out_list.append(res_out)

    def forward(self, inputs):
        y = self.basicblock0(inputs)
        for basic_block_i in self.res_out_list:
            y = basic_block_i(y)
        return y


# 定义上采样模块
class Upsample(fluid.dygraph.Layer):
    def __init__(self, scale=2):
        super(Upsample, self).__init__()
        self.scale = scale

    def forward(self, inputs):
        # get dynamic upsample output shape
        shape_nchw = fluid.layers.shape(inputs)
        shape_hw = fluid.layers.slice(shape_nchw, axes=[0], starts=[2], ends=[4])
        shape_hw.stop_gradient = True
        in_shape = fluid.layers.cast(shape_hw, dtype='int32')
        out_shape = in_shape * self.scale
        out_shape.stop_gradient = True

        # reisze by actual_shape
        out = fluid.layers.resize_nearest(
            input=inputs, scale=self.scale, actual_shape=out_shape)
        return out


DarkNet_cfg = {53: ([1, 1, 1, 1])}


class DarkNet53_conv_body(fluid.dygraph.Layer):
    def __init__(self,

                 is_test=True):
        super(DarkNet53_conv_body, self).__init__()
        self.stages = DarkNet_cfg[53]
        self.stages = self.stages[0:5]

        # 第一层卷积
        self.conv0 = ConvBNLayer(
            ch_in=3,
            ch_out=64,
            filter_size=1,
            stride=1,
            padding=0,
            is_test=is_test)

        # 下采样，使用stride=2的卷积来实现
        self.downsample0 = DownSample(
            ch_in=64,
            ch_out=64,
            is_test=is_test)

        # 添加各个层级的实现
        self.darknet53_conv_block_list = []
        self.downsample_list = []
        for i, stage in enumerate(self.stages):
            conv_block = self.add_sublayer(
                "stage_%d" % (i),
                LayerWarp(32 * (2 ** (i + 1)),
                          32 * (2 ** i),
                          stage,
                          is_test=is_test))
            self.darknet53_conv_block_list.append(conv_block)
        # 两个层级之间使用DownSample将尺寸减半
        for i in range(len(self.stages) - 1):
            downsample = self.add_sublayer(
                "stage_%d_downsample" % i,
                DownSample(ch_in=32 * (2 ** (i + 1)),
                           ch_out=32 * (2 ** (i + 2)),
                           is_test=is_test))
            self.downsample_list.append(downsample)

    def forward(self, inputs):
        out = self.conv0(inputs)
        # print("conv1:",out.numpy())
        out = self.downsample0(out)
        # print("dy:",out.numpy())
        blocks = []
        for i, conv_block_i in enumerate(self.darknet53_conv_block_list):  # 依次将各个层级作用在输入上面
            out = conv_block_i(out)
            blocks.append(out)
            if i < len(self.stages) - 1:
                out = self.downsample_list[i](out)
        return blocks[-1:-4:-1]  # 将C0, C1, C2作为返回值




def test_dygraph_grad(grad_outputs=None):
    with fluid.dygraph.guard(fluid.CPUPlace()):
        fluid.enable_dygraph(fluid.CPUPlace())
        x = fluid.layers.fill_constant(shape=[4,3,256,256], value=1.0, dtype='float32')
        
        x.stop_gradient = False
        backbone = DarkNet53_conv_body(is_test=False)
        C0, C1, C2 = backbone(x)



        # If grad_outputs=None, dy1 = [1], dy2 = [1].
        # If grad_outputs=[g1, g2], then:
        #    - dy1 = [1] if g1 is None else g1
        #    - dy2 = [1] if g2 is None else g2

        # Since y1 = x * x, dx = 2 * x * dy1.
        # Since y2 = x * 3, dx = 3 * dy2.
        # Therefore, the final result would be:
        # dx = 2 * x * dy1 + 3 * dy2 = 4 * dy1 + 3 * dy2.

        dx = fluid.dygraph.grad(
            outputs=[C0],
            inputs=[x],
            grad_outputs=grad_outputs)[0]

        return dx.numpy()


THREE = fluid.layers.fill_constant(shape=[4,3,256,256], value=3.0, dtype='float32')
FOUR = fluid.layers.fill_constant(shape=[4,3,256,256], value=4.0, dtype='float32')

# dy1 = [1], dy2 = [1]
print(test_dygraph_grad(None))  # [7.]
print('11111111111111111111111')
# dy1 = [1], dy2 = [4]
print(test_dygraph_grad([None]))  # [16.]
print('22222222222222222222222222222')
# dy1 = [4], dy2 = [1]
print(test_dygraph_grad([FOUR]))  # [19.]
print('333333333333333333333333333333333')
# dy1 = [3], dy2 = [4]
print(test_dygraph_grad([THREE]))  # [24.]
print('4444444444444444444444444444444444')

`

**Comment by ruyijidan** [comment]
```
import paddle.fluid as fluid
import numpy as np
import paddle
import paddle.fluid as fluid
import math
from paddle.fluid.dygraph.nn import Conv2D, Pool2D, Linear, BatchNorm
from paddle.fluid.param_attr import ParamAttr
from paddle.fluid.regularizer import L2Decay
from paddle.fluid.dygraph.base import to_variable
class ConvBNLayer(fluid.dygraph.Layer):
    def __init__(self,
                 ch_in,
                 ch_out,
                 filter_size=3,
                 stride=1,
                 groups=1,
                 padding=0,
                 act="leaky",
                 is_test=True,
                 sn=False):
        super(ConvBNLayer, self).__init__()
        self.sn = sn
        if self.sn:
            self.conv = paddle.fluid.dygraph.SpectralNorm(Conv2D(
                num_channels=ch_in,
                num_filters=ch_out,
                filter_size=filter_size,
                stride=stride,
                padding=padding,
                groups=groups,
                param_attr=ParamAttr(
                    initializer=fluid.initializer.Normal(0., 0.02)),
                bias_attr=False,
                act=None), dim=1, power_iters=1)
        else:
            self.conv = Conv2D(
                num_channels=ch_in,
                num_filters=ch_out,
                filter_size=filter_size,
                stride=stride,
                padding=padding,
                groups=groups,
                param_attr=ParamAttr(
                    initializer=fluid.initializer.Normal(0., 0.02)),
                bias_attr=False,
                act=None)
        self.batch_norm = BatchNorm(
            num_channels=ch_out,
            is_test=is_test,
            param_attr=ParamAttr(
                initializer=fluid.initializer.Normal(0., 0.02),
                regularizer=L2Decay(0.)),
            bias_attr=ParamAttr(
                initializer=fluid.initializer.Constant(0.0),
                regularizer=L2Decay(0.)))
        self.act = act
    def forward(self, inputs):
        out = self.conv(inputs)
        out = self.batch_norm(out)
        if self.act == 'leaky':
            out = fluid.layers.leaky_relu(x=out, alpha=0.1)
        return out
class DownSample(fluid.dygraph.Layer):
    def __init__(self,
                 ch_in,
                 ch_out,
                 filter_size=3,
                 stride=2,
                 padding=1,
                 is_test=True):
        super(DownSample, self).__init__()
        self.conv_bn_layer = ConvBNLayer(
            ch_in=ch_in,
            ch_out=ch_out,
            filter_size=filter_size,
            stride=stride,
            padding=padding,
            is_test=is_test)
        self.ch_out = ch_out
    def forward(self, inputs):
        out = self.conv_bn_layer(inputs)
        return out
class BasicBlock(fluid.dygraph.Layer):
    def __init__(self, ch_in, ch_out, is_test=True):
        super(BasicBlock, self).__init__()
        self.conv1 = ConvBNLayer(
            ch_in=ch_in,
            ch_out=ch_out,
            filter_size=1,
            stride=1,
            padding=0,
            is_test=is_test)
        self.conv2 = ConvBNLayer(
            ch_in=ch_out,
            ch_out=ch_out * 2,
            filter_size=3,
            stride=1,
            padding=1,
            is_test=is_test )
    def forward(self, inputs):
        conv1 = self.conv1(inputs)
        conv2 = self.conv2(conv1)
        out = fluid.layers.elementwise_add(x=inputs, y=conv2, act=None)
        return out
class LayerWarp(fluid.dygraph.Layer):
    def __init__(self, ch_in, ch_out, count, is_test=True):
        super(LayerWarp, self).__init__()

        self.basicblock0 = BasicBlock(ch_in,
                                      ch_out,
                                      is_test=is_test)
        self.res_out_list = []
        for i in range(1, count):
            res_out = self.add_sublayer("basic_block_%d" % (i),
                                        BasicBlock(ch_out * 2,
                                                   ch_out,
                                                   is_test=is_test))
            self.res_out_list.append(res_out)
    def forward(self, inputs):
        y = self.basicblock0(inputs)
        for basic_block_i in self.res_out_list:
            y = basic_block_i(y)
        return y
class Upsample(fluid.dygraph.Layer):
    def __init__(self, scale=2):
        super(Upsample, self).__init__()
        self.scale = scale
    def forward(self, inputs):
        shape_nchw = fluid.layers.shape(inputs)
        shape_hw = fluid.layers.slice(shape_nchw, axes=[0], starts=[2], ends=[4])
        shape_hw.stop_gradient = True
        in_shape = fluid.layers.cast(shape_hw, dtype='int32')
        out_shape = in_shape * self.scale
        out_shape.stop_gradient = True
        out = fluid.layers.resize_nearest(
            input=inputs, scale=self.scale, actual_shape=out_shape)
        return out
DarkNet_cfg = {53: ([1, 1, 1, 1])}
class DarkNet53_conv_body(fluid.dygraph.Layer):
    def __init__(self,
                 is_test=True):
        super(DarkNet53_conv_body, self).__init__()
        self.stages = DarkNet_cfg[53]
        self.stages = self.stages[0:5]
        self.conv0 = ConvBNLayer(
            ch_in=3,
            ch_out=64,
            filter_size=1,
            stride=1,
            padding=0,
            is_test=is_test)
        self.downsample0 = DownSample(
            ch_in=64,
            ch_out=64,
            is_test=is_test)
        self.darknet53_conv_block_list = []
        self.downsample_list = []
        for i, stage in enumerate(self.stages):
            conv_block = self.add_sublayer(
                "stage_%d" % (i),
                LayerWarp(32 * (2 ** (i + 1)),
                          32 * (2 ** i),
                          stage,
                          is_test=is_test))
            self.darknet53_conv_block_list.append(conv_block)
        for i in range(len(self.stages) - 1):
            downsample = self.add_sublayer(
                "stage_%d_downsample" % i,
                DownSample(ch_in=32 * (2 ** (i + 1)),
                           ch_out=32 * (2 ** (i + 2)),
                           is_test=is_test))
            self.downsample_list.append(downsample)
    def forward(self, inputs):
        out = self.conv0(inputs)
        out = self.downsample0(out)
        blocks = []
        for i, conv_block_i in enumerate(self.darknet53_conv_block_list):
            out = conv_block_i(out)
            blocks.append(out)
            if i < len(self.stages) - 1:
                out = self.downsample_list[i](out)
        return blocks[-1:-4:-1]
def test_dygraph_grad(grad_outputs=None):
    with fluid.dygraph.guard(fluid.CPUPlace()):
        x = fluid.layers.fill_constant(shape=[4, 3, 256, 256], value=1.0, dtype='float32')
        domain = fluid.layers.fill_constant(shape=[4, 1], value=1.0, dtype='int32')
        x.stop_gradient = False
        input = [x, domain]
        conv = paddle.fluid.dygraph.nn.Conv2D(num_channels=3, num_filters=64,
                                              filter_size=1,
                                              padding=0,
                                              stride=1,
                                              act=None)
        backbone = DarkNet53_conv_body(is_test=False)
        y0, y1, y2 = backbone(x)
        dx = fluid.dygraph.grad(
            outputs=[y0],
            inputs=[x],
            grad_outputs=grad_outputs)[0]
        print(dx.shape)
        return dx.numpy()
print(test_dygraph_grad(None))


```

**Comment by ruyijidan** [comment]
我把问题复现的代码贴上了，希望能一起解决

**Comment by ruyijidan** [comment]
有的网络就可以，有的网络就会报错，梯度的指针怎么会变成空呢？开始我以为我的网络有问题，但是darknet和resnet50也都有同样的错误
```
import numpy as np
import argparse
import ast
import paddle
import paddle.fluid as fluid
from paddle.fluid.layer_helper import LayerHelper
from paddle.fluid.dygraph.nn import Conv2D, Pool2D, BatchNorm, Linear
from paddle.fluid.dygraph.base import to_variable

class ConvBNLayer(fluid.dygraph.Layer):
    def __init__(self,
                 num_channels,
                 num_filters,
                 filter_size,
                 stride=1,
                 groups=1,
                 act=None):
        super(ConvBNLayer, self).__init__()

        self._conv = Conv2D(
            num_channels=num_channels,
            num_filters=num_filters,
            filter_size=filter_size,
            stride=stride,
            padding=(filter_size - 1) // 2,
            groups=groups,
            act=None,
            bias_attr=False)

        self._batch_norm = BatchNorm(num_filters, act=act)

    def forward(self, inputs):
        y = self._conv(inputs)
        y = self._batch_norm(y)

        return y


class BottleneckBlock(fluid.dygraph.Layer):
    def __init__(self,
                 num_channels,
                 num_filters,
                 stride,
                 shortcut=True):
        super(BottleneckBlock, self).__init__()

        self.conv0 = ConvBNLayer(
            num_channels=num_channels,
            num_filters=num_filters,
            filter_size=1,
            act='relu')
        self.conv1 = ConvBNLayer(
            num_channels=num_filters,
            num_filters=num_filters,
            filter_size=3,
            stride=stride,
            act='relu')
        self.conv2 = ConvBNLayer(
            num_channels=num_filters,
            num_filters=num_filters * 4,
            filter_size=1,
            act=None)

        if not shortcut:
            self.short = ConvBNLayer(
                num_channels=num_channels,
                num_filters=num_filters * 4,
                filter_size=1,
                stride=stride)

        self.shortcut = shortcut

        self._num_channels_out = num_filters * 4

    def forward(self, inputs):
        y = self.conv0(inputs)
        conv1 = self.conv1(y)
        conv2 = self.conv2(conv1)

        if self.shortcut:
            short = inputs
        else:
            short = self.short(inputs)

        y = fluid.layers.elementwise_add(x=short, y=conv2)

        layer_helper = LayerHelper(self.full_name(), act='relu')
        return layer_helper.append_activation(y)


class MyCNN(fluid.dygraph.Layer):

    def __init__(self,layers=50,class_dim=5):
        super(MyCNN,self).__init__()
        self.layers = layers
        supported_layers = [18,34,50, 101, 152]
        assert layers in supported_layers, \
            "supported layers are {} but input layer is {}".format(supported_layers, layers)
        if layers == 18:
            depth = [2, 2, 2, 2]
        elif layers == 34:
            depth = [3, 4, 6, 3]
        elif layers == 50:
            depth = [3, 4, 6, 3]
        elif layers == 101:
            depth = [3, 4, 23, 3]
        elif layers == 152:
            depth = [3, 8, 36, 3]
        num_channels = [64, 256, 512, 1024]
        num_filters = [64, 128, 256, 512]

        self.conv = ConvBNLayer(
            num_channels=3,
            num_filters=64,
            filter_size=7,
            stride=2,
            act='relu')
        self.pool2d_max = Pool2D(
            pool_size=3,
            pool_stride=2,
            pool_padding=1,
            pool_type='max')

        self.bottleneck_block_list = []
        for block in range(len(depth)):
            shortcut = False
            for i in range(depth[block]):
                bottleneck_block = self.add_sublayer(
                    'bb_%d_%d' % (block, i),
                    BottleneckBlock(
                        num_channels=num_channels[block]
                        if i == 0 else num_filters[block] * 4,
                        num_filters=num_filters[block],
                        stride=2 if i == 0 and block != 0 else 1,
                        shortcut=shortcut))
                self.bottleneck_block_list.append(bottleneck_block)
                shortcut = True

        self.pool2d_avg = Pool2D(
            pool_size=7, pool_type='avg', global_pooling=True)

        self.pool2d_avg_output = num_filters[len(num_filters) - 1] * 4 * 1 * 1

        import math
        stdv = 1.0 / math.sqrt(2048 * 1.0)

        self.out = Linear(self.pool2d_avg_output,
                      class_dim,
                      act='softmax',
                      param_attr=fluid.param_attr.ParamAttr(
                          initializer=fluid.initializer.Uniform(-stdv, stdv)))
    def forward(self, inputs):

        y = self.conv(inputs)
        y = self.pool2d_max(y)
        for bottleneck_block in self.bottleneck_block_list:
            y = bottleneck_block(y)
        y = self.pool2d_avg(y)
        y = fluid.layers.reshape(y, shape=[-1, self.pool2d_avg_output])
        y = self.out(y)
        return y



def test_dygraph_grad(grad_outputs=None):
    with fluid.dygraph.guard(fluid.CPUPlace()):
        x = fluid.layers.fill_constant(shape=[4, 3, 256, 256], value=1.0, dtype='float32')

        x.stop_gradient = False


        cnn=MyCNN()

        y=cnn(x)

        dx = fluid.dygraph.grad(
            outputs=[y],
            inputs=[x],
            grad_outputs=grad_outputs)[0]
        print(dx.shape)
        return dx.numpy()


print(test_dygraph_grad(None))
```

**Comment by ruyijidan** [comment]
@phlrain @lfchener

**Comment by Feynman1999** [comment]
经过测试，好像有类似resnet那样的shortcut就会报这个错？
