### ISSUE TITLE
Windows Inference Issue

### ISSUE THREAD

**Issue by Xu-honghao** [PaddlePaddle/Paddle#25677]
下载的官方Windows预测库，版本cpu_avx_openblas，预测库1.8.3
下载的官方demo，Paddle/paddle/fluid/inference/api/demo_ci/windows_mobilenet.cc
使用lib库的时候出现6个无法解析的外部命令错误
本机cpu型号：Inter Xeon cpu E5620
操作系统：Windows7
vs版本：vs2015 update3

**Comment by jiweibo** [comment]
请问是使用的动态库吗？我本地先尝试复现下。

**Comment by Xu-honghao** [comment]
使用的静态lib库，MT

**Comment by Xu-honghao** [comment]
> 请问是使用的动态库吗？我本地先尝试复现下。

使用的静态lib库，MT

**Comment by jiweibo** [comment]
下载的是 cpu_avx_openblas 预测库，编译选项中WITH_MKL应为OFF，请确认下。

**Comment by Xu-honghao** [comment]
> 下载的是 cpu_avx_openblas 预测库，编译选项中WITH_MKL应为OFF，请确认下。

是的，我自己编译的也是blas的，测试demo也是一样的问题

**Comment by Xu-honghao** [comment]
> 下载的是 cpu_avx_openblas 预测库，编译选项中WITH_MKL应为OFF，请确认下。

请问你那边Windows测试cpu_avx_openblas 预测库是正常的吗？

**Comment by jiweibo** [comment]
> > 下载的是 cpu_avx_openblas 预测库，编译选项中WITH_MKL应为OFF，请确认下。
> 
> 请问你那边Windows测试cpu_avx_openblas 预测库是正常的吗？

我在win10上没复现出问题

**Comment by Xu-honghao** [comment]
好吧，难道是我系统原因吗，可以把你包含头文件和lib的两个目录在群里截图给我看一下吗

**Comment by jiweibo** [comment]
> 好吧，难道是我系统原因吗，可以把你包含头文件和lib的两个目录在群里截图给我看一下吗

预测库解压后默认名称是 fluid_inference_install_dir。

cmake的时候 指定PADDLE_LIB为刚才解压的预测库目录。 如-DPADDLE_LIB=C:\...\fluid_inference_install_dir
