### ISSUE TITLE
Parakeet是否有中文的预训练模型或者训练语料

### ISSUE THREAD

**Issue by yeguang1991** [PaddlePaddle/Paddle#25673]
Parakeet是否有中文的预训练模型或者训练语料

**Comment by kuke** [comment]
感谢关注，中文的预训练模型我们正在准备之中

**Comment by yeguang1991** [comment]
> 感谢关注，中文的预训练模型我们正在准备之中

语料呢，可以提供一下吗

**Comment by kevinxhgao** [comment]
> 感谢关注，中文的预训练模型我们正在准备之中

请问中文普通话的何时可完成？
