### ISSUE TITLE
PanddlePanddle Icon？

### ISSUE THREAD

**Issue by www516717402** [PaddlePaddle/Paddle#25684]
PanddlePandle need a Icon in main interface. Please see pytorch github. 
Hope PandlePandle more and more popular.

**Comment by 123malin** [comment]
> PanddlePandle need a Icon in main interface. Please see pytorch github.
> Hope PandlePandle more and more popular.

Thanks for your opinion, we'll fix it later. Hope PaddlePaddle more popular.
