### ISSUE TITLE
Jetson 在编译 Paddle 出错

### ISSUE THREAD

**Issue by zjutlzt** [PaddlePaddle/Paddle#25691]
Jetson 在编译 Paddle得时候   cmake  .. 得时候报错
版本是 git checkout v1.8.3
请问是什么问题 
CMake Error at cmake/configure.cmake:103 (if):
  if given arguments:

    "VERSION_LESS" "7"

  Unknown arguments specified

**Comment by vslyu** [comment]
Nvidia 的Jeston平台目前只适合用来做推理，不建议在Jeston平台上直接编译Paddle，理由有如下几点：

- Nvidia Jetson nano/TK1/TX1/TX2等板卡为低端嵌入式处理器板卡，上面搭载的四核心ARM A57 CPU性能低下，编译package特别慢；

- 编译package配置更为复杂，需要额外指定好多编译flags，容易配置错误；

 建议你这边可以在[安装与编译 Linux 预测库](https://www.paddlepaddle.org.cn/documentation/docs/zh/advanced_guide/inference_deployment/inference/build_and_install_lib_cn.html)页面找到支持Jeston平台的tar.gz包直接解压安装使用，目前只支持cuda10-cudnn7.5下TRT5的加速，需要对应的jetpack系统包支持，如果你的jetpack系统不支持的话，需要你在本地重新刷一下jetpack。

![image](https://user-images.githubusercontent.com/12137504/88286198-f6b72000-cd22-11ea-8f62-eb2ef7e100da.png)

如果你这边强烈需求是要在Jeston平台上自行编译Paddle预测库的话，建议你这边仔细检查一下cmake的flags是否按照官网的要求配置好，有条件的话可以在x86机器配置专门的arm-gcc工具链进行编译。

另外提供一个可供参考的选项，还可以使用我们的Paddle-Lite进行配置，这是专门针对Jeston嵌入式端进行定制优化的推理预测包，参见教程如下：[PaddleLite使用CUDA预测部署](https://paddle-lite.readthedocs.io/zh/latest/demo_guides/cuda.html)，

**Comment by zjutlzt** [comment]
好的 看来只能用paddle-lite了，我想问一下，paddledetection\Seg  export出来的模型  padllelite可以跑吗？

**Comment by 123malin** [comment]
> 好的 看来只能用paddle-lite了，我想问一下，paddledetection\Seg export出来的模型 padllelite可以跑吗？

应该是可以的，如果有问题，可以在paddle-lite repo下开issue提问。

**Comment by zjutlzt** [comment]
好的 谢谢

**Comment by lleesg** [comment]
> Jetson 在编译 Paddle得时候 cmake .. 得时候报错
> 版本是 git checkout v1.8.3
> 请问是什么问题
> CMake Error at cmake/configure.cmake:103 (if):
> if given arguments:
> 
> ```
> "VERSION_LESS" "7"
> ```
> 
> Unknown arguments specified

met the same problem in Paddle-release-1.8 but disapeared in Paddle-release-2.0-beta
