### ISSUE TITLE
请问静态图有weight_norm的部署吗?

### ISSUE THREAD

**Issue by andylida** [PaddlePaddle/Paddle#25695]
飞桨程序员小哥哥小姐姐你们好~
我现在正在部署一个模型,需要用到weight_norm.我同时写了动态,静态图两种代码.
我看到weight_norm_ParamAttr是一个静态图专用方法.我可以在dygraph中使用他们吗?

如果不行的话,请问能推荐我看哪一部份paddle代码来理解ParamAttr?我可以手动实现一下
谢谢~

**Comment by qingqing01** [comment]
@andylida  weight_norm_ParamAttr不能用到动态图中。

动态图可以参考： https://github.com/PaddlePaddle/Parakeet/blob/develop/parakeet/models/deepvoice3/model.py#L48

**Comment by andylida** [comment]
嗯.动态图我看到了,这几天就在看parakeet😂
谢谢,但我暂时不打算close掉

**Comment by qingqing01** [comment]
@andylida 好的，有问题可以继续交流~
