### ISSUE TITLE
How to fix random seeds so that the same code snippet can yield the same results？

### ISSUE THREAD

**Issue by familyld** [PaddlePaddle/Paddle#25717]
I follow the instruction in [this link](https://www.paddlepaddle.org.cn/documentation/docs/zh/api_cn/fluid_cn/Program_cn.html#random-seed) and set the random seed of the program to be a fixed value, i.e., `prog.random_seed = 1` (I also fix the random seeds of the random and numpy packages and I haven't use GPU so far). However, running the same code snippet still yields different results, e.g., the initialized model parameters are totally different.

Are there any other random seeds needed to be fixed so that I can obtain exactly the same result with the same code? Furthermore, can you provide a little example of how to achieve this goal? Such a feature is of significance since it can help us better analyse the potential problems happened in the training process.

Thank you.

**Comment by qingqing01** [comment]
@familyld  You must also set seed for startup program, you can setting these at the beginning of the code as follows:

```python
# main program

# fluid.default_main_program().random_seed = 1
startup_prog.random_seed = 1  # any seed

# startup program
# fluid.default_main_program().random_seed = 1 
train_prog.random_seed = 1

```

**Comment by familyld** [comment]
@qingqing01 Thank you! Fixing `fluid.default_startup_program().random_seed` is what I need.

**Comment by jellyheadandrew** [comment]
I'm trying to reproduce the training results, []() and I found this . May I ask for detailed explanation on what is `prog` and `startup_prog`, `train_prog` is?
