### ISSUE TITLE
Merge two CI systems and their build-and-test entrypoints

### ISSUE THREAD

**Issue by wangkuiyi** [PaddlePaddle/Paddle#2571]
Now we run the following jobs on two CI systems:

1. TeamCity
   1. build and run with `cmake -DWITH_GPU=ON -DWITH_TESTING=ON` on GPU servers
1. TravisCI
   1. build and run with `cmake -DWITH_GPU=OFF -DWITH_TESTING=ON` on non-GPU servers
   1. build and deploy our documents
   1. source code style checking

where 1.i and 2.i have different entry points. 

For 1.i, the entry point is described in the [.travis.yml](https://github.com/PaddlePaddle/Paddle/blob/develop/.travis.yml) file as ` paddle/scripts/travis/main.sh`.

The entry point of 2.i is one we recommend daily developers use -- [`paddle/scripts/docker/build.sh`](https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/scripts/docker/build.sh).

It would be great if we can merge them into one.

Or, can we simply remove the configuration 2.i, because it seems that 1.i has been doing a complete test?

**Comment by wangkuiyi** [comment]
I think the key to the answer is that if

```
cmake -DWITH_GPU=ON .. && make test
```

covers

```
cmake -DWITH_GPU=OFF .. && make test
```

**Comment by reyoung** [comment]
Yes. The travis ci cpu unittest could be removed because GPU unittests covers all CPU tests
