### ISSUE TITLE
Please re-compile the inference library by setting the cmake flag ON_INFER=ON if you are running Paddle Inference

### ISSUE THREAD

**Issue by Spr1nt0a0** [PaddlePaddle/Paddle#25718]
Please re-compile the inference library by setting the cmake flag ON_INFER=ON if you are running Paddle Inference

**Comment by luotao1** [comment]
What's the problem with you?

**Comment by wangjiechinaghost** [comment]
also have this problem

**Comment by luotao1** [comment]
I guess both of you want to ask why there is a warning `Please re-compile the inference library by setting the cmake flag ON_INFER=ON if you are running Paddle Inference`.

You can see [how to install and build the inference lib](https://www.paddlepaddle.org.cn/documentation/docs/zh/advanced_guide/inference_deployment/inference/build_and_install_lib_cn.html#id12).
- In default, `-DON_INFER=OFF`, which is used for building paddlepaddle training whl
- If you want to build C++ inference lib, you should set `cmake .. -DON_INFER=ON`

**Comment by Spr1nt0a0** [comment]
ok.thx!
