### ISSUE TITLE
ubuntu docker 安装 paddlepaddle，容器内只有python2可以使用

### ISSUE THREAD

**Issue by wuxlun** [PaddlePaddle/Paddle#25723]
在容器内进入python3中编译 import paddle.fluid后报错，但在python2中正常。为什么现在还不支持python3啊？怎样才可以在容器中使用python3

**Comment by kuke** [comment]
在容器内运行 python 默认是 python2，如果要安装 paddle 到 python3 环境，可以按如下的方式运行

`
pip3 install paddlepaddle-gpu==1.8.3.post97 -i https://mirror.baidu.com/pypi/simple
`
