### ISSUE TITLE
使用float16混合精度训练报错InvalidArgumentError: Tensor holds the wrong type, it holds float, but desires to be ::paddle::platform::float16.

### ISSUE THREAD

**Issue by Weili-NLP** [PaddlePaddle/Paddle#25720]
- 版本、环境信息：
    1）PaddlePaddle版本：1.7.2 和 1.8.3
    3）GPU：V100 32g，Cuda10.0
    4）系统环境：Ubuntu 16.04， python3.6.9

![image](https://user-images.githubusercontent.com/25901705/88456288-02cfe880-ceaf-11ea-944c-c7287f15fced.png)
![image](https://user-images.githubusercontent.com/25901705/88456279-f77cbd00-ceae-11ea-8ee2-9855cbab38e4.png)
![image](https://user-images.githubusercontent.com/25901705/88456213-702f4980-ceae-11ea-92d8-4fb001f1b1be.png)

**Comment by luotao1** [comment]
和用户沟通，该问题大概率是bug，因为1.6.3下用户的模型可以跑，1.8.3和1.7.2都有同样的错误

**Comment by luotao1** [comment]
1. 
![image](https://user-images.githubusercontent.com/6836917/88499942-fb692600-cff9-11ea-860d-5ae02da1114c.png)
您的代码中如果有上面这个图片中最后的两行，需要屏蔽掉，新版本混合精度已经不需要这两行了。
2.可以参考 [混合精度训练最佳实践](https://www.paddlepaddle.org.cn/documentation/docs/zh/advanced_guide/performance_improving/amp/amp.html#paddlepaddle-amp)

**Comment by Weili-NLP** [comment]
> ![image](https://user-images.githubusercontent.com/6836917/88499942-fb692600-cff9-11ea-860d-5ae02da1114c.png)
> 您的代码中如果有上面这个图片中最后的两行，需要屏蔽掉，新版本混合精度已经不需要这两行了。
> 2.可以参考 [混合精度训练最佳实践](https://www.paddlepaddle.org.cn/documentation/docs/zh/advanced_guide/performance_improving/amp/amp.html#paddlepaddle-amp)

谢谢，注释掉 cast_fp32_to_fp16后，新版Paddle可以正常运行了

**Comment by xfcygaocan** [comment]
> ![image](https://user-images.githubusercontent.com/6836917/88499942-fb692600-cff9-11ea-860d-5ae02da1114c.png)
> 您的代码中如果有上面这个图片中最后的两行，需要屏蔽掉，新版本混合精度已经不需要这两行了。
> 2.可以参考 [混合精度训练最佳实践](https://www.paddlepaddle.org.cn/documentation/docs/zh/advanced_guide/performance_improving/amp/amp.html#paddlepaddle-amp)

我参考这个方法1，注释掉最后两行。用1.7.2跑了两个数据集效果明显下降。

**Comment by luotao1** [comment]
> 用1.7.2跑了两个数据集效果明显下降。

@xfcygaocan 请问：
- 是1.7.2比1.6.3慢了？
- 有试过1.8.3么？
- 和 https://github.com/PaddlePaddle/Paddle/issues/25743 有关系么？
- 能否提供下网络配置和更详细的信息（比如速度、机型等）

**Comment by Weili-NLP** [comment]
@luotao1 我注释掉最后两行使用1.7.2效果也急剧下降，1.6.3跑出来准确率79.6%，1.7.2跑出来19%，同样的模型代码。
请问注释掉 cast_fp32_to_fp16以后，是不是导致模型没有成功加载参数？

另外，1.6.3下fp16混合精度非常慢，比全精度fp32还要慢很多，GPU使用率也非常低。1.7.2下GPU使用率正常，速度和全精度fp32差不多。这也不太正常，是什么原因导致的呢？

**Comment by xfcygaocan** [comment]
> > 用1.7.2跑了两个数据集效果明显下降。
> 
> @xfcygaocan 请问：
> 
> * 是1.7.2比1.6.3慢了？
> * 有试过1.8.3么？
> * 和 #25743 有关系么？
> * 能否提供下网络配置和更详细的信息（比如速度、机型等）

1.7.2比1.6.3速度快了，但是效果下降
试过1.8.3报同样错误
和 https://github.com/PaddlePaddle/Paddle/issues/25743 是一样的问题

**Comment by luotao1** [comment]
请 @wzzju 帮忙看下

**Comment by wzzju** [comment]
已指导用户使用AMP新接口：https://www.paddlepaddle.org.cn/documentation/docs/zh/advanced_guide/performance_improving/amp/amp.html 。 目前用户试用中。
