### ISSUE TITLE
Windows下通过Visual C++ 9.0编译_swig_decoders时报错，缺stdint.h，如何解决？

### ISSUE THREAD

**Issue by YuHuasong123** [PaddlePaddle/Paddle#25736]
running install
running bdist_egg
running egg_info
writing swig_decoders.egg-info\PKG-INFO
writing top-level names to swig_decoders.egg-info\top_level.txt
writing dependency_links to swig_decoders.egg-info\dependency_links.txt
file swig_decoders.py (for module swig_decoders) not found
reading manifest file 'swig_decoders.egg-info\SOURCES.txt'
writing manifest file 'swig_decoders.egg-info\SOURCES.txt'
installing library code to build\bdist.win-amd64\egg
running install_lib
running build_py
file swig_decoders.py (for module swig_decoders) not found
file swig_decoders.py (for module swig_decoders) not found
running build_ext
building '_swig_decoders' extension
C:\Users\issuser\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0\VC\Bin\amd64\cl.exe /c /nologo /Ox /MD /W3 /GS- /DNDEBUG -I. -Ikenlm -Iopenfst-1.6.3/src/include -ITh
readPool -ID:\SoftInstall\Anaconda\include -ID:\SoftInstall\Anaconda\PC /Tpkenlm/util\bit_packing.cc /Fobuild\temp.win-amd64-2.7\Release\kenlm/util\bit_packing.obj -O3 -DNDEBUG -DKENLM
_MAX_ORDER=6 -std=c++11
cl : Command line warning D9002 : ignoring unknown option '-O3'
cl : Command line warning D9002 : ignoring unknown option '-std=c++11'
bit_packing.cc
kenlm\util/bit_packing.hh(30) : fatal error C1083: Cannot open include file: 'stdint.h': No such file or directory
error: command 'C:\\Users\\issuser\\AppData\\Local\\Programs\\Common\\Microsoft\\Visual C++ for Python\\9.0\\VC\\Bin\\amd64\\cl.exe' failed with exit status 2

**Comment by gongweibao** [comment]
在Docker中尝试可以大幅度降低碰到类似问题的机会。
