### ISSUE TITLE
AMP使用报错

### ISSUE THREAD

**Issue by xfcygaocan** [PaddlePaddle/Paddle#25743]
版本、环境信息：
   1）PaddlePaddle版本：1.8.1
   3）GPU：V100 32g，Cuda10.0
   4）系统环境：Ubuntu 16.04， python3.6.9

1、包含AMP代码如下
![image](https://user-images.githubusercontent.com/14819988/88539272-87ec0680-d043-11ea-8b02-2eb2dd8f37eb.png)

2、报错的log如下
![image](https://user-images.githubusercontent.com/14819988/88539082-22981580-d043-11ea-864b-bb8fe66d1c4d.png)

3、可能的问题
我载入模型参数是部分包含float16，但是在用AMP是layers.reduce_sum不支持float16

**Comment by xfcygaocan** [comment]
我看报错的参数是有个tmp X引起的，这个感觉像是反向传播的梯度。
我通过black_var加入含义float16参数的变量，仍然会报错

**Comment by guoshengCS** [comment]
将`reduce_sum`加入`AutoMixedPrecisionLists`的`custom_black_list`试下呢

**Comment by wzzju** [comment]
从报错信息来看，amp框架在判断参数梯度是否为finite时拿到的参数梯度是fp16类型的，这里不太应该出现这种情况。

> 我载入模型参数是部分包含float16，但是在用AMP是layers.reduce_sum不支持float16

这里您是怎样加载fp16类型权重的呢？另外，这些fp16的权重是如何获得的呢？
