### ISSUE TITLE
pip installation problem

### ISSUE THREAD

**Issue by saviord7** [PaddlePaddle/Paddle#25747]
Hello!
I have got a problem to install paddlepaddle packages with pip3 install.

When  I do `pip3 search paddlepaddle` it gets: 
`dima@dima-pc:/usr/lib/python3.7$ pip3 search paddlepaddle
paddlepaddle (1.8.3)               - Parallel Distributed Deep Learning
paddlepaddle-tiny (1.6.1)          - Parallel Distributed Deep Learning
paddlepaddle-gpu (1.8.3.post107)   - Parallel Distributed Deep Learning
paddle-tokenizer (0.1.0)           - A tokenizer write in PaddlePaddle
plsc (0.1.1)                       - PaddlePaddle Large Scale Classfication Package.
paddlex (1.1.1)                    - PaddlePaddle Entire Process Development Toolkit
paddle-fleet (0.1.1)               - Distributed Training Package Based on PaddlePaddle
paddle-serving-client (0.3.1)      - Paddle Serving Package for saved model with PaddlePaddle
paddle-serving-server (0.3.1)      - Paddle Serving Package for saved model with PaddlePaddle
paddle-serving-app (0.1.1)         - Paddle Serving Package for saved model with PaddlePaddle
paddle-serving-server-gpu (0.3.1)  - Paddle Serving Package for saved model with PaddlePaddle
paddle-fl (1.0.1)                  - Privacy-Preserving Deep Learning Package Based on PaddlePaddle.
paddle2onnx (0.2)                  - is a toolkit for converting trained model to onnx from PaddlePaddle frameworks.
x2paddle (0.7.4)                   - a toolkit for converting trained model to PaddlePaddle from other deep learning frameworks.
paddlehub (1.7.1)                  - A toolkit for managing pretrained models of PaddlePaddle and helping user getting started with transfer learning more efficiently.
`

When I trying install paddlepaddle I have this: 
`dima@dima-pc:/usr/lib/python3.7$ pip3 install paddlepaddle
ERROR: Could not find a version that satisfies the requirement paddlepaddle (from versions: none)
ERROR: No matching distribution found for paddlepaddle
`
Whats wrong ?

**Comment by saviord7** [comment]
I tried at: 
1) Windows 10
2) Ubuntu 20.04
All the same.

**Comment by gongweibao** [comment]
Could you try to use it on utunbut 16.04 or just use our dockerimage: docker pull paddlepaddle/paddle:latest
