### ISSUE TITLE
List of issues for external contributors

### ISSUE THREAD

**Issue by rgr19** [PaddlePaddle/Paddle#25742]
Hi! This great project of PaddlePaddle has touched my spirit, thus I would like to contribute by fixing some bugs, adding tests or features. Is there any existing list from where I could pick some actual development task without the need to browse thru all other "issues"? For me any of Python, C++ (Boost, Eigen, etc...), CMake, Ansible, Docker, K8S is perfect!

**Comment by luotao1** [comment]
非常感谢对paddle如此大的肯定。作为一个开源项目，我们非常欢迎外部的开发者来给共同建设paddle，使paddle变得更好。目前我们每天都能通过issue反馈收到比较多的用户反馈，其中已经有大部分的issue反馈的问题，已经在分析和解决了，我们这几天会梳理下我们的issue，把待解决的问题列表，发布到这里，同时也会定期更新到这个列表，让我们一起把paddle建设的更好。

Thank you so much for the affirmation of the PaddlePaddle. As an open-source project, we welcome external developers to contribute together. At present, we receive many issues every day, and most of them have been analyzed and solved. We will browse our issues in the few days, and publish the list of actual development tasks here. Then, you can choose some interesting issues to solve.

**Comment by rgr19** [comment]
Hello! I really like this answer. Thank You very much for that.

**Comment by phlrain** [comment]
Can you read Chinese？ Most of our issues are written in Chinese. We will help you translate it into English if you can't read Chinese.

**Comment by rgr19** [comment]
![image](https://user-images.githubusercontent.com/54042766/89383907-97cbb080-d6fd-11ea-8fff-1706623fd49e.png)

Now, jokes beside, do You have any list of issues for here? With my buddy right click and hist father "Translate to English" I do not have a problem with language, but with finding some nice to do issues.
