### ISSUE TITLE
两个lod tensor如何做出一个concat矩阵

### ISSUE THREAD

**Issue by wxlu** [PaddlePaddle/Paddle#25759]
假设我有两个lod的句子
```
a=[word_a1, word_a2, ..., word_am], 
b=[word_b1, word_b2, ..., word_bn]
```
这两个句子经过embedding层变成 
```
a=[emb_a1, emb_a2, ..., emb_am], 
b=[emb_b1, emb_b2, ..., emb_bn]
```
现在我想得到一个matrix m, m的第i,j个位置的元素为
```
m[i][j] = concat(emb_ai, emb_bj)
```
这个应该怎么实现呢？注: 真实的输入a,b应该是一个batch的句子。

**Comment by guoshengCS** [comment]
> 现在我想得到一个matrix m, m的第i,j个位置的元素为 m[i][j] = concat(emb_ai, emb_bj)

目前没有找到这种方法，且由于a和b实际上各自包含了多个sequence，各sequence的length不相同，可能也不存在这种matrix（m[i][j]中i对于各sequence可取的值不同）。可以看下以下方法，能产生满足需求数据布局，不过matrix改成了一维

```python
# 将a和b按照lod扩展成相同维度（length_a+length_b）后，将embedding进行concat
a_ = fluid.layers.sequence_expand(a, b)
b_ = fluid.layers.sequence_expand(b, a)
out = fluid.layers.concat([a_, b_], axis=1)
# 此时out的lod可以再使用lod_reset调整
```

**Comment by wxlu** [comment]
> > 现在我想得到一个matrix m, m的第i,j个位置的元素为 m[i][j] = concat(emb_ai, emb_bj)
> 
> 目前没有找到这种方法，且由于a和b实际上各自包含了多个sequence，各sequence的length不相同，可能也不存在这种matrix（m[i][j]中i对于各sequence可取的值不同）。可以看下以下方法，能产生满足需求数据布局，不过matrix改成了一维
> 
> ```python
> # 将a和b按照lod扩展成相同维度（length_a+length_b）后，将embedding进行concat
> a_ = fluid.layers.sequence_expand(a, b)
> b_ = fluid.layers.sequence_expand(b, a)
> out = fluid.layers.concat([a_, b_], axis=1)
> # 此时out的lod可以再使用lod_reset调整
> ```

**Comment by wxlu** [comment]
```
可能也不存在这种matrix
```
您可能没明白我的意思，a是多个sequence, b是多个sequence, 组成的m也是一个sequence不过m中的每个位置的tensor是由a相应位置的lod tensor和b相应位置的lod tensor按照我问题描述中的方式形成的matrix. 之前paddle不是给搜索订制过一个match_matrix_tesor吗，类似于那个，只不过现在的matrix不是每个位置是一个scalar而是每个位置是一个concat的向量。

**Comment by guoshengCS** [comment]
这种定制化的功能应该是没有现成的，可以尝试下 https://github.com/PaddlePaddle/Paddle/issues/25759#issuecomment-665399481 这里的方法
