### ISSUE TITLE
paddle开发人员你们好~有关pybind的问题想要请教

### ISSUE THREAD

**Issue by andylida** [PaddlePaddle/Paddle#25750]
&nbsp;&nbsp;在我之前看parakeet时,看到了weight_norm的操作.它在weight_norm中,采用的方法是:覆盖原层的self.weight属性,改为对自己W_v,W_g两个属性调用后再返回.由于继承了动态图版本的Conv2d,所以我也看了它的源码.我发现在操作时,它会调用core.ops.conv2d()这个操作.然而,core中的ops方法(我估计)封装在了.core_avx中.
<br/>
&nbsp;&nbsp;我想请问的是,.core_avx在哪里?我该怎么查看他?如果是通过pybind关联C++的方法,这些代码又应该如何查看?
<br/>
谢谢!

**Comment by zhiqiu** [comment]
hi, 关于python与c++交互的部分，你可以查看paddle/fluid/pybind目录下的代码。
