### ISSUE TITLE
输入的lod的数据pad和unpad对训练速度的影响

### ISSUE THREAD

**Issue by wxlu** [PaddlePaddle/Paddle#25760]
假设我的数据是一个lod的句子 
`a = [word_a1, word_a2, ..., word_an]`
然后我同一个batch内句子的长度变化比较大，我想在rnn与attention之间来回切换，因为rnn对lod建模比较友好，attention对padding的tensor建模比较友好，所以这个过程会有pad与unpad之间的切换，麻烦问下，怎么操作训练的速度会比较快。

问题细化1:
我的问题是直接对lod的tensor进行attention的操作快呢，还是padding之后再进行attention的操作快。如果是直接对lod的tensor进行attention的操作快有没有什么demo呢？我看到的attention的demo都是针对padding后的定长的tensor进行attentioin.

**Comment by guoshengCS** [comment]
`怎么操作训练的速度会比较快` 是指pad与unpad如何操作快吗
如果rnn部分使用lodtensor，attention部分使用padding tensor的话，在需要切换的时候sequence_pad和sequence_unpad即可

**Comment by wxlu** [comment]
我知道是用sequence_pad和sequence_unpad，我的问题是直接对lod的tensor进行attention的操作快呢，还是padding之后再进行attention的操作快。如果是直接对lod的tensor进行attention的操作快有没有什么demo呢？我看到的attention的demo都是针对padding后的定长的tensor进行attentioin.

**Comment by guoshengCS** [comment]
目前lodtensor进行attention能找到的例子是rnn中的attention https://github.com/guoshengCS/book/blob/f7b0e0c24643966c3d3ab2e37d71e797146cef20/08.machine_translation/train.py 这种，相比于这种按时间步逐个计算，应该还是padding之后再进行attention的操作快
