### ISSUE TITLE
InvalidArgumentError--The 'shape' attribute in ReshapeOp is invalid. 

### ISSUE THREAD

**Issue by greatyang** [PaddlePaddle/Paddle#25769]
- 版本、环境信息：
    1）PaddlePaddle版本：1.7
    2）CPU：aistudio 2核CPU Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz
    3）系统环境：Ubuntu 16.04，python3.7

- 训练信息
    1）单机
    2）显存信息  CPU训练

- 复现信息：执行https://aistudio.baidu.com/aistudio/projectdetail/652522中的虚机中的
python train.py ，数据集中的是自己的数据集，图片尺寸1840*3264

- 问题描述：请详细描述您的问题，同步贴出报错信息、日志、可复现的代码片段
I0728 17:51:26.800616   255 parallel_executor.cc:440] The Program will be executed on CPU using ParallelExecutor, 2 cards are used, so 2 programs are executed in parallel.
W0728 17:51:27.296686   255 fuse_all_reduce_op_pass.cc:74] Find all_reduce operators: 170. To make the speed faster, some all_reduce ops are fused during training, after fusion, the number of all_reduce ops is 113.
I0728 17:51:27.306385   255 build_strategy.cc:365] SeqOnlyAllReduceOps:0, num_trainers:1
I0728 17:51:27.464876   255 parallel_executor.cc:307] Inplace strategy is enabled, when build_strategy.enable_inplace = True
I0728 17:51:27.518146   255 parallel_executor.cc:375] Garbage collection strategy is enabled, when FLAGS_eager_delete_tensor_gb = 0
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/executor.py:782: UserWarning: The following exception is not an EOF exception.
  "The following exception is not an EOF exception.")
Traceback (most recent call last):
  File "train.py", line 181, in <module>
    train(args)
  File "train.py", line 158, in train
    fetch_list, feed=feeder.feed(data))
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/parallel_executor.py", line 311, in run
    return_numpy=return_numpy)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/executor.py", line 783, in run
    six.reraise(*sys.exc_info())
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/six.py", line 693, in reraise
    raise value
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/executor.py", line 778, in run
    use_program_cache=use_program_cache)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/executor.py", line 843, in _run_impl
    return_numpy=return_numpy)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/executor.py", line 677, in _run_parallel
    tensors = exe.run(fetch_var_names)._move_to_list()
paddle.fluid.core_avx.EnforceNotMet: 

--------------------------------------------
C++ Call Stacks (More useful to developers):
--------------------------------------------
0   std::string paddle::platform::GetTraceBackString<std::string const&>(std::string const&, char const*, int)
1   paddle::platform::EnforceNotMet::EnforceNotMet(std::string const&, char const*, int)
2   paddle::operators::ReshapeOp::ValidateShape(std::vector<int, std::allocator<int> >, paddle::framework::DDim const&)
3   paddle::operators::ReshapeOp::InferShape(paddle::framework::InferShapeContext*) const
4   paddle::operators::Reshape2Op::InferShape(paddle::framework::InferShapeContext*) const
5   paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, paddle::platform::Place const&, paddle::framework::RuntimeContext*) const
6   paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, paddle::platform::Place const&) const
7   paddle::framework::OperatorBase::Run(paddle::framework::Scope const&, paddle::platform::Place const&)
8   paddle::framework::details::ComputationOpHandle::RunImpl()
9   paddle::framework::details::OpHandleBase::Run(bool)
10  paddle::framework::details::FastThreadedSSAGraphExecutor::RunOpSync(paddle::framework::details::OpHandleBase*)
11  paddle::framework::details::FastThreadedSSAGraphExecutor::RunOp(paddle::framework::details::OpHandleBase*, std::shared_ptr<paddle::framework::BlockingQueue<unsigned long> > const&, unsigned long*)
12  std::_Function_handler<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> (), std::__future_base::_Task_setter<std::unique_ptr<std::__future_base::_Result<void>, std::__future_base::_Result_base::_Deleter>, void> >::_M_invoke(std::_Any_data const&)
13  std::__future_base::_State_base::_M_do_set(std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> ()>&, bool&)
14  ThreadPool::ThreadPool(unsigned long)::{lambda()#1}::operator()() const

------------------------------------------
Python Call Stacks (More useful to users):
------------------------------------------
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/framework.py", line 2525, in append_op
    attrs=kwargs.get("attrs", None))
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/layer_helper.py", line 43, in append_op
    return self.main_program.current_block().append_op(*args, **kwargs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/layers/nn.py", line 5676, in reshape
    "XShape": x_shape})
  File "/home/aistudio/lib/pose_resnet.py", line 148, in calc_loss
    y = fluid.layers.reshape(target,  (-1, self.k, h*w))
  File "/home/aistudio/lib/pose_resnet.py", line 115, in net
    loss = self.calc_loss(out, target, target_weight)
  File "train.py", line 112, in train
    loss, output = model.net(input=image, target=target, target_weight=target_weight)
  File "train.py", line 181, in <module>
    train(args)

----------------------
Error Message Summary:
----------------------
InvalidArgumentError: The 'shape' attribute in ReshapeOp is invalid. The input tensor X'size must be divisible by known capacity of 'shape'. But received X's shape = [4, 7, 96, 72], X's size = 193536, 'shape' is [-1, 7, 24960], known capacity of 'shape' is -174720.
  [Hint: Expected output_shape[unk_dim_idx] * capacity == -in_size, but received output_shape[unk_dim_idx] * capacity:-174720 != -in_size:-193536.] at (/paddle/paddle/fluid/operators/reshape_op.cc:185)
  [operator < reshape2 > error]

**Comment by guoshengCS** [comment]
> https://aistudio.baidu.com/aistudio/projectdetail/652522

这个项目好像暂未公开，我们这边看不到。如果是shape问题的话，可否确认下自定义数据集中的图片尺寸是否和项目中要求的一致，可以试下resize到相同大小试下

**Comment by greatyang** [comment]
文件名称使用数字序号，同时修改了图片的尺寸，就正常了。
