### ISSUE TITLE
waveflow训练中文模型报错

### ISSUE THREAD

**Issue by yeguang1991** [PaddlePaddle/Paddle#25762]
语料：
![image](https://user-images.githubusercontent.com/66579493/88633421-925fdc00-d0e7-11ea-93dc-d21b07d1d8f4.png)
![image](https://user-images.githubusercontent.com/66579493/88633464-a0156180-d0e7-11ea-9104-2b43b622a188.png)
报错截图：
![image](https://user-images.githubusercontent.com/66579493/88633562-c1764d80-d0e7-11ea-9368-cde06ce532a5.png)
![image](https://user-images.githubusercontent.com/66579493/88633590-cb984c00-d0e7-11ea-90c6-f3748c9e790e.png)

**Comment by iclementine** [comment]
出现这个问题的原因，训练代码中预设了音频的采样率和配置文件中写的采样率相同。
https://github.com/PaddlePaddle/Parakeet/blob/e58e927c5e1265f3ff3a61502f03475e9ebfbd85/examples/waveflow/data.py#L39

LJSpeech 的采样率是 22050Hz, 如果你使用的音频的话，你可以改一下读取音频的方式，让它把音频重采样到指定的采样率，这样应该就能正常训练了。

waveflow 中的 data.py 使用的是 scipy.io.wavfile.read 来读取音频，读出来的是整数类型的，比如说 16 bit 整数类型。
你可以稍微改一下代码，使用 librosa.load 或者用 soundfile.read 来读取音频，这些 API 支持自定义采样率。但是用它们读出来的默认是浮点数 （-1，1 ）之间的 ndarray. 和 scipy.io.wavfile.read 不同，需要改动一下。
