### ISSUE TITLE
单机多卡训练报错Tensor holds no memory. operator < lookup_table_v2 > error

### ISSUE THREAD

**Issue by xiaom5248** [PaddlePaddle/Paddle#25761]
版本信息
Paddle version: 1.7.2
Paddle With CUDA: True
OS: CentOS 6.3
Python version: 2.7.14
CUDA version: 10.0.130
cuDNN version: None.None.None
Nvidia driver version: 418.39

单机单卡训练正常，单机多卡训练报错，报错信息如下：
![image](https://user-images.githubusercontent.com/14197806/88630254-e7e5ba00-d0e2-11ea-85ba-3674026157bd.png)

Python错误栈信息：
![image](https://user-images.githubusercontent.com/14197806/88630320-fd5ae400-d0e2-11ea-877f-877e45969587.png)

网络结构：
![image](https://user-images.githubusercontent.com/14197806/88630372-15326800-d0e3-11ea-9fc4-b4ccd3d71e80.png)

训练代码：
![image](https://user-images.githubusercontent.com/14197806/88630448-31cea000-d0e3-11ea-8430-9b0624d6adb1.png)

参数PARALLEL为False时可正常训练，为True时报上述错误

**Comment by guoshengCS** [comment]
试下PARALLEL为True时将exe.run中`feed=feeder.feed_parallel(data, place_num)`改成`feed=list(feeder.feed_parallel(data, place_num))`，后者是示例用法 https://www.paddlepaddle.org.cn/documentation/docs/zh/api_cn/fluid_cn/DataFeeder_cn.html#feed-parallel-iterable-num-places-none

**Comment by xiaom5248** [comment]
转list之后能跑起来了，不过用了8张卡，只有一张卡的利用率在10%，其余都是0，可能是什么原因啊？
![image](https://user-images.githubusercontent.com/14197806/89751295-09429f00-db02-11ea-8c25-bfe2929fec9f.png)
![image](https://user-images.githubusercontent.com/14197806/89751303-0f388000-db02-11ea-8170-3f5a75d6142d.png)
