### ISSUE TITLE
save_vars 和 load_vars中save_to_memory、vars_from_memory 的用法

### ISSUE THREAD

**Issue by paulpaul91** [PaddlePaddle/Paddle#25775]
通过save_vars 的 save_to_memory可以把模型的内存字节存下来，我现在希望使用vars_from_memory 导入模型参数，应该如何操作

**Comment by guoshengCS** [comment]
可以参考下这里的例子 https://github.com/PaddlePaddle/Paddle/pull/14734/files#diff-a0412360d8335c45fdde74eb65c13013

**Comment by paulpaul91** [comment]
> 可以参考下这里的例子 https://github.com/PaddlePaddle/Paddle/pull/14734/files#diff-a0412360d8335c45fdde74eb65c13013
未理解在python下具体我应该怎么操作，现在我希望对模型内存进行加密，然后解密加载到模型中进行finetune

**Comment by guoshengCS** [comment]
python使用vars_from_memory的话可以参考这里 https://github.com/PaddlePaddle/Paddle/pull/24098

**Comment by paulpaul91** [comment]
> python使用vars_from_memory的话可以参考这里 #24098

大致了解了下，vars_from_memory 加密解密是使用于模型预测？我现在希望load_vars接口走内存加载是不是没有方法？

**Comment by Shixiaowei02** [comment]
https://github.com/PaddlePaddle/Paddle/pull/24098/files#diff-4abc52fe77b9169160d5935269f1b3b4R95

@paulpaul91 您好，此功能是应 `load_inference_model` 支持内存读取加解密的需求做的开发。一般情况下用户不需要直接使用 `save_vars` 接口，如果的确要用到这个功能，请参考上面的测试代码，谢谢！
