### ISSUE TITLE
invalid configuration argument

### ISSUE THREAD

**Issue by zhengzhe97** [PaddlePaddle/Paddle#25784]
paddle版本：1.8.0
运行环境：aistudio

[2020-07-29 09:05:59] trainbatch 0, lr 0.001000, loss 0.000000, time 0.00 sec
W0729 09:05:59.541766 20356 operator.cc:187] elementwise_add raises an exception thrust::system::system_error, parallel_for failed: invalid configuration argument
F0729 09:05:59.541855 20356 exception_holder.h:37] std::exception caught, parallel_for failed: invalid configuration argument
*** Check failure stack trace: ***
    @     0x7fdc4d9217dd  google::LogMessage::Fail()
    @     0x7fdc4d92528c  google::LogMessage::SendToLog()
    @     0x7fdc4d921303  google::LogMessage::Flush()
    @     0x7fdc4d92679e  google::LogMessageFatal::~LogMessageFatal()
    @     0x7fdc508d97c8  paddle::framework::details::ExceptionHolder::Catch()
    @     0x7fdc5097472e  paddle::framework::details::FastThreadedSSAGraphExecutor::RunOpSync()
    @     0x7fdc509720cf  paddle::framework::details::FastThreadedSSAGraphExecutor::RunOp()
    @     0x7fdc50972394  _ZNSt17_Function_handlerIFvvESt17reference_wrapperISt12_Bind_simpleIFS1_ISt5_BindIFZN6paddle9framework7details28FastThreadedSSAGraphExecutor10RunOpAsyncEPSt13unordered_mapIPNS6_12OpHandleBaseESt6atomicIiESt4hashISA_ESt8equal_toISA_ESaISt4pairIKSA_SC_EEESA_RKSt10shared_ptrINS5_13BlockingQueueImEEEEUlvE_vEEEvEEEE9_M_invokeERKSt9_Any_data
    @     0x7fdc4d97eca3  std::_Function_handler<>::_M_invoke()
    @     0x7fdc4d77d4c7  std::__future_base::_State_base::_M_do_set()
    @     0x7fdcc5913a99  __pthread_once_slow
    @     0x7fdc5096e562  _ZNSt13__future_base11_Task_stateISt5_BindIFZN6paddle9framework7details28FastThreadedSSAGraphExecutor10RunOpAsyncEPSt13unordered_mapIPNS4_12OpHandleBaseESt6atomicIiESt4hashIS8_ESt8equal_toIS8_ESaISt4pairIKS8_SA_EEES8_RKSt10shared_ptrINS3_13BlockingQueueImEEEEUlvE_vEESaIiEFvvEE6_M_runEv
    @     0x7fdc4d77f924  _ZZN10ThreadPoolC1EmENKUlvE_clEv
    @     0x7fdc86307421  execute_native_thread_routine_compat
    @     0x7fdcc590c6ba  start_thread
    @     0x7fdcc564241d  clone
    @              (nil)  (unknown)
Aborted (core dumped)

**Comment by zhengzhe97** [comment]
请问这种情况可能是由于什么产生的

**Comment by wanghaoshuang** [comment]
请问这个错误可以稳定复现么？是多卡训练么？如果是多卡训练，确定每个batch内的样本数大于卡数么？
