### ISSUE TITLE
Cublas error, CUBLAS_STATUS_EXECUTION_FAILED

### ISSUE THREAD

**Issue by liyandongpy** [PaddlePaddle/Paddle#25786]
Ubuntu 安装后运行报错。错误如下：
![image](https://user-images.githubusercontent.com/49861986/88753674-613ae680-d18f-11ea-98e7-0f231e2a28e2.png)

问题分析：用的docker是tensorflow 公布的，这个docker安装paddle 就会报错。每次都需要把里面的cuda重新装一下才能运行paddle。

**Comment by wanghaoshuang** [comment]
建议您参考Paddle官方安装教程，使用Paddle提供的docker镜像：https://www.paddlepaddle.org.cn/install/quick#show_info

**Comment by liyandongpy** [comment]
@wanghaoshuang  要是能用docker自然就没有问题了。我现在这个问题有没有办法解决？

**Comment by wanghaoshuang** [comment]
>要是能用docker自然就没有问题了

您用Paddle提供的docker镜像也是有问题么？

>用的docker是tensorflow 公布的

这是指docker镜像么？
