### ISSUE TITLE
Paddle多语言SDK

### ISSUE THREAD

**Issue by reyoung** [PaddlePaddle/Paddle#258]
Paddle目前支持的预测库是使用swig转化成python的api进行预测的。但是很多时候大家并不想使用python作为线上系统的预测语言。而想使用Java或者C++/C进行模型的预测。让用户支持多语言的预测，目前可以有多种实现方式。这里我把实现的想法和目前swig的架构列一下，希望大家参与一下讨论。

## 目前Swig封装的结构

![image](https://cloud.githubusercontent.com/assets/728699/19960274/c4b37010-a1e6-11e6-999c-982f4efeff18.png)

Paddle目前swig接口如上图所示。首先，最下面是Paddle的C++核心部分。这一块C++的核心部分使用的是C++ 11来进行编写(也不排除未来用C++ 14/17)。由于Paddle在最开始设计的时候，没有考虑过多语言接口，所以重构Paddle C++代码的核心部分，来支持swig，并用swig直接生成多语言脚本，是比较复杂的。特别是Paddle的C++使用风格是，尽量使用标准库，尽量使用第三方库，如果可以尽量使用新的feature。如果直接使用swig编译Paddle核心C++库(万一以后我们用C++ 14/17呢？)，会非常复杂。

于是Paddle为了支持多语言的swig接口，写了一个 `Paddle API` 包。这个包是专为swig打造的，主体分为两个部分。

* Paddle.h 这个文件是swig编译的接口文件。这个文件的特点是
  * 只使用C++ 03的feature
  * 不使用任何第三方库，只使用 C++ 标准库
  * 尽量在接口里做一些安全检查，不要将进程挂掉。
  * 使用异常返回检查错误。(更接近于python，java的风格)
* 其余文件是Paddle的C++核心模块与Paddle.h的转接层，尽量做到内存无复制。

在这个`Paddle API`模块之上，我们用swig编译出了 `Python` 语言的接口文件，`swig_paddle.py`。但是，这个接口文件其实是非常`C++`风格的，也和Paddle紧密相关。比如,

* Python的矩阵库常用的是numpy，但是Paddle里面有自己的矩阵库实现。
* Paddle本身载入模型、初始化模型需要很多步骤。但用户其实只需要一句话 `loadModel`

为了让用户可以更加自然的使用paddle python的封装，我们在python端写了一些工具函数/类，monkey patch掉Paddle的一些函数，比如让其能直接返回numpy的矩阵之类的，这样对Python更友好。

以上是Paddle目前的多语言实现。

## Paddle 多语言接口 (Java/Go/Matlab)

Paddle的Java/Go/Matlab预测接口理论上应该和Python的风格一致。整体图示为\:

![image](https://cloud.githubusercontent.com/assets/728699/19961348/23a534cc-a1ed-11e6-8378-ff4ff03a75a4.png)

这个事情感觉理解起来并不是很复杂，实际上就和Python的接口一样。

## Paddle 多语言接口 (C/C++/ObjectiveC)

C/C++/Objective-C的接口和Java、Python的又不太一样。

* 因为，Java、Python不能直接include C/C++头文件
* 内存管理模式也和C/C++有很大差别。
    * 例如Java和Python都是有垃圾回收的语言，所以，在swig和 API中的Paddle.h中，需要将内存管理托管给其他语言。
    * 但是C/C++是手动管理内存的语言，所以需要显示的delete/free对象。

所以，C/C++/Objective-C的接口需要使用另一个思路来做。如果直接使用`Paddle API`模块下的 `Paddle.h` 会有一下几个问题。

* 这个`Paddle.h`是为了swig接口做的，所以内存申请完了并没有释放的code。因为释放原本可以交由其他语言的垃圾回收来做。
* 这个 `Paddle.h`使用了exception作为错误信息，但是C++ exception本质上并不应该被使用。
* 这个 `Paddle.h`太接近于Paddle本身的实现了，需要用户去了解太多知识。

所以，我个人感觉Paddle的C/C++/ObjectiveC的多语言接口应该再在 `Paddle API`之上封装一层C API。给用户预测使用。

整体模块图如下\:

![image](https://cloud.githubusercontent.com/assets/728699/19964145/10849b86-a1fb-11e6-88cb-ab617c9de504.png)

但这个事情这么做，有一种深深地过于复杂的感觉。所以我也不确定是不是这样会好一些。

**Comment by guomin** [comment]
期待

**Comment by reyoung** [comment]
@backyes @wangkuiyi @gangliao @luotao1 @qingqing01 @emailweixu @hedaoyuan @QiJune 

对于Paddle预测库，或者多语言接口。大家有什么建议呢？

另外，
这个多语言接口其实也不只是做预测库，也可以自定义训练流程。

**Comment by reyoung** [comment]
同时强烈建议大家用一下 `graphviz`。画图神器呀。。issue正文里面最后一张图，源码放到下面了

```graphviz
digraph G {
  rankdir=TD;
  PaddleCpp [label="Paddle C++核心部分"]
  subgraph cluster_paddle_api {
    label="Paddle API Layer"
    PaddleAPIH [label="/paddle/api/Paddle.h"]
    PaddleAPICpp [label="/paddle/api/*.cpp"]
  }

  SwigCompiler [label="SWIG编译器"]
  
  subgraph cluster_paddle_py {
    label="python py_paddle package"
    PaddlePy [label="swig_paddle.py"]
    PaddlePyUtil [label="python utils"]
  }

  subgraph cluster_paddle_java {
    label="paddle java api"
    PaddleJava [label="swig_paddle.java"]
    PaddleJavaUtil [label="java <--> paddle adaptor"]
  }

  subgraph cluster_paddle_go {
    label="paddle go api"
    PaddleGo [label="swig_paddle.go"]
    PaddleGoUtil [label="go <--> paddle adaptor"]
  }

  subgraph cluster_paddle_c {
    label="Paddle C api"
    PaddleCUtil [label="C++03 <--> C99 adaptor"]
  }

  PaddleAPICpp -> PaddleCpp [dir=back]
  PaddleAPIH -> PaddleAPICpp [dir=back]
  PaddleCUtil -> PaddleAPIH [dir=back]
  SwigCompiler -> PaddleAPIH [dir=back]
  PaddlePy -> SwigCompiler [dir=back]
  PaddlePyUtil -> PaddlePy [dir=back]

  PaddleJava -> SwigCompiler [dir=back]
  PaddleJavaUtil -> PaddleJava [dir=back]
  
  PaddleGo -> SwigCompiler [dir=back]
  PaddleGoUtil -> PaddleGo [dir=back]
}

```

**Comment by backyes** [comment]
@reyoung 我觉得先梳理解决下眼前的问题：

*  c++ 预测接口， 对很多线上业务，追求效率的应该是使用场景
* python预测。这块好像有些文档之类的不是很完善
* c++  和python接口的相关文档和稳定性测试

首先确保一套相对稳定的方案。

**Comment by backyes** [comment]
Paddle 训练一前一后，分别是dataprovider和predict可能需要进一步加强对接用户最终的需求

dataprovider：
* https://github.com/PaddlePaddle/Paddle/issues/773 

predict：
* c++ 预测接口。 py_paddle预测不能解决所有应用场景，c++预测仍然需要完善，满足部分业务对predict的集成，满足低延迟、集成环境等需求。 


@reyoung @wangkuiyi 这个工作优先级可能要稍微提高一点。 

@pengli09 @lcy-seso 麻烦你们能否从业务角度收集更多具体的需求，列在此处，方便plan。

**Comment by wangkuiyi** [comment]
几个问题和建议：

1. 这个issue是讨论Paddle inference library，还是包括 training 和 inference？如果是前者，标题应该改一下。如果是后者，第一个comment里的第一段只说了inference的事儿。

1. 现在 `paddle/api` 里是既有training的API也有inference API吧。是不是其实不容易拆开讨论？

1. 到底需要支持哪些语言，应该尽量想清楚，按照优先级列一下。因为有些语言的支持是通过SWIG，有些是通过暴露一个C99接口。方法不同，又不可能一步到位支持多个方法，所以必然得有优先顺序。

1. Go接口通常不是通过SWIG，而是基于C99接口封装。

1. 这里讨论的事儿，术语叫“language binding”，我不知道汉语应该怎么说，但是叫“接口”恐怕和“API”混淆。可能就叫 language binding 比较明确。

**Comment by reyoung** [comment]
> 这个issue是讨论Paddle inference library，还是包括 training 和 inference？如果是前者，标题应该改一下。如果是后者，第一个comment里的第一段只说了inference的事儿

讨论Paddle所有的API。其实理论上和后面的API issue有些重复。

> 现在 paddle/api 里是既有training的API也有inference API吧。是不是其实不容易拆开讨论？

是的，因为inference 和training本来就应该是一套api。inference只调用forward, training调用forward, backward和多GPU通信，多机器通信。。

> 到底需要支持哪些语言，应该尽量想清楚，按照优先级列一下。因为有些语言的支持是通过SWIG，有些是通过暴露一个C99接口。方法不同，又不可能一步到位支持多个方法，所以必然得有优先顺序。
Go接口通常不是通过SWIG，而是基于C99接口封装。

C99 最好了。swig并不好用。。所以应该从Paddle C++核心部分直接export一层C-API好了。

> 这里讨论的事儿，术语叫“language binding”，我不知道汉语应该怎么说，但是叫“接口”恐怕和“API”混淆。可能就叫 language binding 比较明确。

就叫language binding吧。。不过其实除了language binding之外，我们可能有一些东西也会在Python里面写，或者Golang里面写。这个也不仅仅是language binding那么简单。而是Paddle分成几层，哪些层可以不用Cpp的问题。

**Comment by pengli09** [comment]
从产品线实际使用PaddlePaddle的同学的反馈来看，以下两个诉求很强烈，希望能够适当考虑：
1. 用PaddlePaddle上线的同学希望PaddlePaddle能够提供预编译好的C++静态库（在非官方支持机器上编译PaddlePaddle确实很困难）；
2. 头文件暴露的函数尽量简洁、用户完全不需要关注PaddlePaddle具体的实现逻辑为好。如果能在grandient machine基础上提供一个很薄的封装，让用户只需要简单几行就可以完成grandient machine等的设置将会非常好。@reyoung  C/C++/ObjectiveC接口那张图中的Paddle C api是在做这件事吗？

**Comment by wangkuiyi** [comment]
@pengli09 谢谢提醒！我们想到一起了。

我们是在套路提供一套标准的C API，不同团队可以在此基础上开发各种 language bindings。另外，做inference（比如prediction）的时候也不需要依赖SWIG了。

**Comment by reyoung** [comment]
Use #849 to tracking latest progress. Closed
