### ISSUE TITLE
DeepSpeech2模型执行demo_server.py时报了个不可用的错误怎么解决？

### ISSUE THREAD

**Issue by YuHuasong123** [PaddlePaddle/Paddle#25804]
python demo_server.py 
-----------  Configuration Arguments -----------
alpha: 2.5
beam_size: 500
beta: 0.3
cutoff_prob: 1.0
cutoff_top_n: 40
decoding_method: ctc_beam_search
host_ip: localhost
host_port: 8086
lang_model_path: ./models/lm/zh_giga.no_cna_cmn.prune01244.klm
mean_std_path: ./data/aishell/mean_std.npz
model_path: ./checkpoints/aishell/step_final
num_conv_layers: 2
num_rnn_layers: 3
rnn_layer_size: 2048
share_rnn_weights: True
specgram_type: linear
speech_save_dir: demo_cache
use_gpu: True
use_gru: False
vocab_path: ./data/aishell/vocab.txt
warmup_manifest: ./data/aishell/manifest.test
------------------------------------------------
2020-07-29 17:10:03,314-INFO: begin to initialize the external scorer for decoding
2020-07-29 17:10:23,598-INFO: language model: is_character_based = 1, max_order = 5, dict_size = 0
2020-07-29 17:10:23,598-INFO: end initializing scorer
-----------------------------------------------------------
Warming up ...
('Warm-up Test Case %d: %s', 0, u'./dataset/data_aishell/wav/test/S0913/BAC009S0913W0464.wav')
W0729 17:10:23.813068  1439 device_context.cc:252] Please NOTE: device: 0, CUDA Capability: 70, Driver API Version: 9.2, Runtime API Version: 9.0
W0729 17:10:23.879007  1439 device_context.cc:260] device: 0, cuDNN Version: 7.3.
/opt/conda/envs/python27-paddle120-env/lib/python2.7/site-packages/paddle/fluid/executor.py:1070: UserWarning: The following exception is not an EOF exception.
  "The following exception is not an EOF exception.")
Traceback (most recent call last):
  File "demo_server.py", line 240, in <module>
    main()
  File "demo_server.py", line 236, in main
    start_server()
  File "demo_server.py", line 221, in start_server
    num_test_cases=3)
  File "demo_server.py", line 138, in warm_up_test
    transcript = audio_process_handler(sample['audio_filepath'])
  File "demo_server.py", line 197, in file_to_transcript
    feeding_dict=data_generator.feeding)
  File "/home/aistudio/DeepSpeech/model_utils/model.py", line 411, in infer_batch_probs
    self.init_from_pretrained_model(exe, infer_program)
  File "/home/aistudio/DeepSpeech/model_utils/model.py", line 161, in init_from_pretrained_model
    filename="params.pdparams")
  File "/opt/conda/envs/python27-paddle120-env/lib/python2.7/site-packages/paddle/fluid/io.py", line 876, in load_params
    filename=filename)
  File "/opt/conda/envs/python27-paddle120-env/lib/python2.7/site-packages/paddle/fluid/io.py", line 750, in load_vars
    filename=filename)
  File "/opt/conda/envs/python27-paddle120-env/lib/python2.7/site-packages/paddle/fluid/io.py", line 804, in load_vars
    executor.run(load_prog)
  File "/opt/conda/envs/python27-paddle120-env/lib/python2.7/site-packages/paddle/fluid/executor.py", line 1071, in run
    six.reraise(*sys.exc_info())
  File "/opt/conda/envs/python27-paddle120-env/lib/python2.7/site-packages/paddle/fluid/executor.py", line 1066, in run
    return_merged=return_merged)
  File "/opt/conda/envs/python27-paddle120-env/lib/python2.7/site-packages/paddle/fluid/executor.py", line 1154, in _run_impl
    use_program_cache=use_program_cache)
  File "/opt/conda/envs/python27-paddle120-env/lib/python2.7/site-packages/paddle/fluid/executor.py", line 1229, in _run_program
    fetch_var_name)
paddle.fluid.core_avx.EnforceNotMet: 

--------------------------------------------
C++ Call Stacks (More useful to developers):
--------------------------------------------
0   std::string paddle::platform::GetTraceBackString<std::string const&>(std::string const&, char const*, int)
1   paddle::platform::EnforceNotMet::EnforceNotMet(std::string const&, char const*, int)
2   paddle::operators::LoadCombineOpKernel<paddle::platform::CUDADeviceContext, float>::LoadParamsFromBuffer(paddle::framework::ExecutionContext const&, paddle::platform::Place const&, std::istream*, bool, std::vector<std::string, std::allocator<std::string> > const&) const
3   paddle::operators::LoadCombineOpKernel<paddle::platform::CUDADeviceContext, float>::Compute(paddle::framework::ExecutionContext const&) const
4   std::_Function_handler<void (paddle::framework::ExecutionContext const&), paddle::framework::OpKernelRegistrarFunctor<paddle::platform::CUDAPlace, false, 0ul, paddle::operators::LoadCombineOpKernel<paddle::platform::CUDADeviceContext, float>, paddle::operators::LoadCombineOpKernel<paddle::platform::CUDADeviceContext, double>, paddle::operators::LoadCombineOpKernel<paddle::platform::CUDADeviceContext, int>, paddle::operators::LoadCombineOpKernel<paddle::platform::CUDADeviceContext, signed char>, paddle::operators::LoadCombineOpKernel<paddle::platform::CUDADeviceContext, long> >::operator()(char const*, char const*, int) const::{lambda(paddle::framework::ExecutionContext const&)#1}>::_M_invoke(std::_Any_data const&, paddle::framework::ExecutionContext const&)
5   paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, paddle::platform::Place const&, paddle::framework::RuntimeContext*) const
6   paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, paddle::platform::Place const&) const
7   paddle::framework::OperatorBase::Run(paddle::framework::Scope const&, paddle::platform::Place const&)
8   paddle::framework::Executor::RunPartialPreparedContext(paddle::framework::ExecutorPrepareContext*, paddle::framework::Scope*, long, long, bool, bool, bool)
9   paddle::framework::Executor::RunPreparedContext(paddle::framework::ExecutorPrepareContext*, paddle::framework::Scope*, bool, bool, bool)
10  paddle::framework::Executor::Run(paddle::framework::ProgramDesc const&, paddle::framework::Scope*, int, bool, bool, std::vector<std::string, std::allocator<std::string> > const&, bool, bool)

------------------------------------------
Python Call Stacks (More useful to users):
------------------------------------------
  File "/opt/conda/envs/python27-paddle120-env/lib/python2.7/site-packages/paddle/fluid/framework.py", line 2610, in append_op
    attrs=kwargs.get("attrs", None))
  File "/opt/conda/envs/python27-paddle120-env/lib/python2.7/site-packages/paddle/fluid/io.py", line 802, in load_vars
    'model_from_memory': vars_from_memory
  File "/opt/conda/envs/python27-paddle120-env/lib/python2.7/site-packages/paddle/fluid/io.py", line 750, in load_vars
    filename=filename)
  File "/opt/conda/envs/python27-paddle120-env/lib/python2.7/site-packages/paddle/fluid/io.py", line 876, in load_params
    filename=filename)
  File "/home/aistudio/DeepSpeech/model_utils/model.py", line 161, in init_from_pretrained_model
    filename="params.pdparams")
  File "/home/aistudio/DeepSpeech/model_utils/model.py", line 411, in infer_batch_probs
    self.init_from_pretrained_model(exe, infer_program)
  File "demo_server.py", line 197, in file_to_transcript
    feeding_dict=data_generator.feeding)
  File "demo_server.py", line 138, in warm_up_test
    transcript = audio_process_handler(sample['audio_filepath'])
  File "demo_server.py", line 221, in start_server
    num_test_cases=3)
  File "demo_server.py", line 236, in main
    start_server()
  File "demo_server.py", line 240, in <module>
    main()

----------------------
Error Message Summary:
----------------------
UnavailableError: Not allowed to load partial data via load_combine_op, please use load_op instead.
  [Hint: Expected buffer->eof() == true, but received buffer->eof():0 != true:1.] at (/paddle/paddle/fluid/operators/load_combine_op.h:115)
  [operator < load_combine > error]

**Comment by wanghaoshuang** [comment]
看起来像模型格式不兼容导致的，还需要  @kuke 帮忙确认下

**Comment by lfchener** [comment]
我看你使用了自己的 language model，猜测可能是文件格式不一致导致的，麻烦先 check 一下文件格式。 @YuHuasong123

**Comment by YuHuasong123** [comment]
**### 但我用自己的 language model去预测又是正常的，应该不是格式的问题，还有没有别的可能？**
 sh run_infer.sh
Download language model ...
./zh_giga.no_cna_cmn.prune01244.klm already exists, download skipped.
-----------  Configuration Arguments -----------
alpha: 2.6
beam_size: 300
beta: 5.0
cutoff_prob: 0.99
cutoff_top_n: 40
decoding_method: ctc_beam_search
error_rate_type: cer
infer_manifest: data/aishell/manifest.test
lang_model_path: models/lm/zh_giga.no_cna_cmn.prune01244.klm
mean_std_path: data/aishell/mean_std.npz
model_path: checkpoints/aishell/step_final
num_conv_layers: 2
num_proc_bsearch: 8
num_rnn_layers: 3
num_samples: 10
rnn_layer_size: 1024
share_rnn_weights: 0
specgram_type: linear
use_gpu: 1
use_gru: 1
vocab_path: data/aishell/vocab.txt
------------------------------------------------
2020-07-30 14:51:21,622-INFO: begin to initialize the external scorer for decoding
2020-07-30 14:51:21,736-INFO: language model: is_character_based = 1, max_order = 5, dict_size = 0
2020-07-30 14:51:21,736-INFO: end initializing scorer
2020-07-30 14:51:21,736-INFO: start inference ...
W0730 14:51:21.810513  8812 device_context.cc:252] Please NOTE: device: 0, CUDA Capability: 70, Driver API Version: 10.2, Runtime API Version: 10.0
W0730 14:51:21.814332  8812 device_context.cc:260] device: 0, cuDNN Version: 7.6.
finish initing model from pretrained params from checkpoints/aishell/step_final

Target Transcription: 甚至出现交易几乎停滞的情况
Output Transcription: 甚至出现交易几乎停滞的情况
Current error rate [cer] = 0.000000

Target Transcription: 一二线城市虽然也处于调整中
Output Transcription: 一二线城市虽然也处于调整中
Current error rate [cer] = 0.000000

Target Transcription: 但因为聚集了过多公共资源
Output Transcription: 但因为聚集了过多公共资源
Current error rate [cer] = 0.000000

Target Transcription: 为了规避三四线城市明显过剩的市场风险
Output Transcription: 为了规避三四线城市明显过剩的市场风险
Current error rate [cer] = 0.000000

Target Transcription: 标杆房企必然调整市场战略
Output Transcription: 标杆房企必然调整市场战略
Current error rate [cer] = 0.000000

Target Transcription: 因此土地储备至关重要
Output Transcription: 因此土地储备至关重要
Current error rate [cer] = 0.000000

Target Transcription: 中原地产首席分析师张大伟说
Output Transcription: 中原地产首席分析师张大伟说
Current error rate [cer] = 0.000000

Target Transcription: 一线城市土地供应量减少
Output Transcription: 一线城市土地供应量减少
Current error rate [cer] = 0.000000

Target Transcription: 也助推了土地市场的火爆
Output Transcription: 也助推了土地市场的火爆
Current error rate [cer] = 0.000000

Target Transcription: 北京仅新增住宅土地供应十宗
Output Transcription: 北京仅新增住宅土地供应时中
Current error rate [cer] = 0.153846
2020-07-30 14:51:26,332-INFO: finish inference

**Comment by YuHuasong123** [comment]
我这边是想通过ASR引擎进行中文语音测试，所用的语音模型和语言模型都是中文的，是不是这个引擎不支持中文呢？

**Comment by YuHuasong123** [comment]
### 我在阿里云服务器上通过ASR引擎进行中文语音测试时，又报出飞桨进程/线程挂掉的问题，怎么解决呢？
 python demo_server.py 
-----------  Configuration Arguments -----------
alpha: 2.5
beam_size: 500
beta: 0.3
cutoff_prob: 1.0
cutoff_top_n: 40
decoding_method: ctc_beam_search
host_ip: localhost
host_port: 8086
lang_model_path: ./models/lm/zh_giga.no_cna_cmn.prune01244.klm
mean_std_path: ./data/aishell/mean_std.npz
model_path: ./checkpoints/aishell/step_final
num_conv_layers: 2
num_rnn_layers: 3
rnn_layer_size: 2048
share_rnn_weights: True
specgram_type: linear
speech_save_dir: demo_cache
use_gpu: True
use_gru: False
vocab_path: ./data/aishell/vocab.txt
warmup_manifest: ./data/aishell/manifest.test
------------------------------------------------
2020-07-30 17:23:29,879-INFO: begin to initialize the external scorer for decoding
2020-07-30 17:23:29,992-INFO: language model: is_character_based = 1, max_order = 5, dict_size = 0
2020-07-30 17:23:29,992-INFO: end initializing scorer
-----------------------------------------------------------
Warming up ...
('Warm-up Test Case %d: %s', 0, u'./dataset/data_aishell/wav/test/S0764/BAC009S0764W0437.wav')
W0730 17:23:30.133558 10593 device_context.cc:252] Please NOTE: device: 0, CUDA Capability: 70, Driver API Version: 10.2, Runtime API Version: 10.0
W0730 17:23:30.137315 10593 device_context.cc:260] device: 0, cuDNN Version: 7.6.
W0730 17:23:32.814687 10593 init.cc:216] Warning: PaddlePaddle catches a failure signal, it may not work properly
W0730 17:23:32.814723 10593 init.cc:218] You could check whether you killed PaddlePaddle thread/process accidentally or report the case to PaddlePaddle
W0730 17:23:32.814729 10593 init.cc:221] The detail failure signal is:

W0730 17:23:32.814739 10593 init.cc:224] *** Aborted at 1596101012 (unix time) try "date -d @1596101012" if you are using GNU date ***
W0730 17:23:32.815600 10593 init.cc:224] PC: @                0x0 (unknown)
W0730 17:23:32.815755 10593 init.cc:224] *** SIGSEGV (@0x50) received by PID 10593 (TID 0x7fbe98fd0740) from PID 80; stack trace: ***
W0730 17:23:32.816442 10593 init.cc:224]     @     0x7fbe98d92630 (unknown)
W0730 17:23:32.817021 10593 init.cc:224]     @     0x7fbe98faabd6 _dl_relocate_object
W0730 17:23:32.817593 10593 init.cc:224]     @     0x7fbe98fb365c dl_open_worker
W0730 17:23:32.818181 10593 init.cc:224]     @     0x7fbe98fae7c4 _dl_catch_error
W0730 17:23:32.818753 10593 init.cc:224]     @     0x7fbe98fb2b7b _dl_open
W0730 17:23:32.819473 10593 init.cc:224]     @     0x7fbe983e9722 do_dlopen
W0730 17:23:32.820057 10593 init.cc:224]     @     0x7fbe98fae7c4 _dl_catch_error
W0730 17:23:32.820772 10593 init.cc:224]     @     0x7fbe983e97e2 __GI___libc_dlopen_mode
W0730 17:23:32.821442 10593 init.cc:224]     @     0x7fbe983c09d5 init
W0730 17:23:32.822003 10593 init.cc:224]     @     0x7fbe98d8920b __pthread_once_slow
W0730 17:23:32.822773 10593 init.cc:224]     @     0x7fbe983c0aec __GI___backtrace
W0730 17:23:32.829479 10593 init.cc:224]     @     0x7fbe271ca5a5 paddle::platform::GetTraceBackString<>()
W0730 17:23:32.833688 10593 init.cc:224]     @     0x7fbe271ca931 paddle::platform::EnforceNotMet::EnforceNotMet()
W0730 17:23:32.838735 10593 init.cc:224]     @     0x7fbe28270d62 paddle::operators::LoadCombineOpKernel<>::LoadParamsFromBuffer()
W0730 17:23:32.844390 10593 init.cc:224]     @     0x7fbe282714ee paddle::operators::LoadCombineOpKernel<>::Compute()
W0730 17:23:32.848124 10593 init.cc:224]     @     0x7fbe28271c13 _ZNSt17_Function_handlerIFvRKN6paddle9framework16ExecutionContextEEZNKS1_24OpKernelRegistrarFunctorINS0_8platform9CUDAPlaceELb0ELm0EJNS0_9operators19LoadCombineOpKernelINS7_17CUDADeviceContextEfEENSA_ISB_dEENSA_ISB_iEENSA_ISB_aEENSA_ISB_lEEEEclEPKcSJ_iEUlS4_E_E9_M_invokeERKSt9_Any_dataS4_
W0730 17:23:32.853608 10593 init.cc:224]     @     0x7fbe2aa1fe00 paddle::framework::OperatorWithKernel::RunImpl()
W0730 17:23:32.861475 10593 init.cc:224]     @     0x7fbe2aa205f1 paddle::framework::OperatorWithKernel::RunImpl()
W0730 17:23:32.865785 10593 init.cc:224]     @     0x7fbe2aa195a1 paddle::framework::OperatorBase::Run()
W0730 17:23:32.873126 10593 init.cc:224]     @     0x7fbe274c7460 paddle::framework::Executor::RunPartialPreparedContext()
W0730 17:23:32.880201 10593 init.cc:224]     @     0x7fbe274c7803 paddle::framework::Executor::RunPreparedContext()
W0730 17:23:32.884308 10593 init.cc:224]     @     0x7fbe274caf6b paddle::framework::Executor::Run()
W0730 17:23:32.884445 10593 init.cc:224]     @     0x7fbe271a438e _ZZN8pybind1112cpp_function10initializeIZN6paddle6pybindL22pybind11_init_core_avxERNS_6moduleEEUlRNS2_9framework8ExecutorERKNS6_11ProgramDescEPNS6_5ScopeEibbRKSt6vectorISsSaISsEEE111_vIS8_SB_SD_ibbSI_EINS_4nameENS_9is_methodENS_7siblingEEEEvOT_PFT0_DpT1_EDpRKT2_ENUlRNS_6detail13function_callEE1_4_FUNES10_
W0730 17:23:32.887208 10593 init.cc:224]     @     0x7fbe27207309 pybind11::cpp_function::dispatcher()
W0730 17:23:32.888168 10593 init.cc:224]     @     0x7fbe990c35f7 PyEval_EvalFrameEx
W0730 17:23:32.888976 10593 init.cc:224]     @     0x7fbe990c5b19 PyEval_EvalCodeEx
W0730 17:23:32.889767 10593 init.cc:224]     @     0x7fbe990c2fe8 PyEval_EvalFrameEx
W0730 17:23:32.890568 10593 init.cc:224]     @     0x7fbe990c5b19 PyEval_EvalCodeEx
W0730 17:23:32.891352 10593 init.cc:224]     @     0x7fbe990c2fe8 PyEval_EvalFrameEx
W0730 17:23:32.892141 10593 init.cc:224]     @     0x7fbe990c5b19 PyEval_EvalCodeEx
W0730 17:23:32.892904 10593 init.cc:224]     @     0x7fbe990c2fe8 PyEval_EvalFrameEx
W0730 17:23:32.893712 10593 init.cc:224]     @     0x7fbe990c5b19 PyEval_EvalCodeEx
段错误
