### ISSUE TITLE
optimizer.minimize(loss)报错EnforceNotMet: Cannot find variable split_2.tmp_0@GRAD

### ISSUE THREAD

**Issue by lossfaller** [PaddlePaddle/Paddle#25816]
我在写一个模型的时候，在optimizer.minimize(loss)这行报错EnforceNotMet: Cannot find variable split_2.tmp_0@GRAD at [/paddle/paddle/fluid/framework/op_desc.cc:193]，注释掉这行可以一键运行，想问一下这是什么问题呢？

**Comment by wanghaoshuang** [comment]
像是"split_2"对应的op的output没有计算梯度，建议您试一下把这个output的stop_gradient设置为True试一下。

**Comment by lossfaller** [comment]
> 像是"split_2"对应的op的output没有计算梯度，建议您试一下把这个output的stop_gradient设置为True试一下。

我是用paddle复现的yolo4然后loss直接用的yolov3_loss是因为这个出的问题吗？如何找到split_2对应的算子呢？

**Comment by lossfaller** [comment]
> 像是"split_2"对应的op的output没有计算梯度，建议您试一下把这个output的stop_gradient设置为True试一下。

最后查到是写CSPDarkNet53,out = fluid.layers.split(all_out, 2,  dim=1)[1] 这一步时候fluid.layers.split(all_out, 2,  dim=1)[0]没有计算梯度，我现在把all_out.stop_gradient=True,怎么只屏蔽fluid.layers.split(all_out, 2,  dim=1)[0]呢？

**Comment by lossfaller** [comment]
> 像是"split_2"对应的op的output没有计算梯度，建议您试一下把这个output的stop_gradient设置为True试一下。

已解决，谢谢
