### ISSUE TITLE
【顶会论文复现吐槽专区】安装问题

### ISSUE THREAD

**Issue by yinyiyu** [PaddlePaddle/Paddle#25819]
1.paddle安装问题，使用conda安装不上paddlepaddle，清华源也添加了
![image](https://user-images.githubusercontent.com/24800963/88874782-7af13200-d252-11ea-8757-e3298915bd00.png)

**Comment by hang245141253** [comment]
帮顶顶~

**Comment by yinyiyu** [comment]
2.使用python3.5用pip安装paddle的时候，有regex找不到的错误，提示升级pip，然后升级后就会出现大段地红色报错
![image](https://user-images.githubusercontent.com/24800963/88875199-69f4f080-d253-11ea-87a8-f305aa1ab30f.png)

**Comment by saxon-zh** [comment]
> 2.使用python3.5用pip安装paddle的时候，有regex找不到的错误，提示升级pip，然后升级后就会出现大段地红色报错
> ![image](https://user-images.githubusercontent.com/24800963/88875199-69f4f080-d253-11ea-87a8-f305aa1ab30f.png)

https://www.shangmayuan.com/a/76b7a2825c984522b2ad67cc.html   可以尝试下这个上面介绍的方案。

**Comment by saxon-zh** [comment]
> 1.paddle安装问题，使用conda安装不上paddlepaddle，清华源也添加了
> ![image](https://user-images.githubusercontent.com/24800963/88874782-7af13200-d252-11ea-8757-e3298915bd00.png)

是两个paddle哈，conda install paddlepaddle
