### ISSUE TITLE
建议官方文档给出PaddlePaddle与Pytorch相互之间关系的说明，尤其是两者是否可以混合在同一个project里使用

### ISSUE THREAD

**Issue by jkren6** [PaddlePaddle/Paddle#25815]
Github上使用Pytorch写的代码比较多，直接用这些代码复现起来比较方便。同时我最近学习了PaddlePaddle关于RL的课程，觉得PARL的框架比较好用。所以产生了以下两点疑问：

- PP与Pytorch是否可以安装在同一个虚拟环境下，如果可以，是否有版本对应关系？

- PP与Pytorch是否可以在同一个project内使用，如果可以需要注意什么？

- 我看PARL底层有用到torch里的代码，所以想了解PP与Pytorch之间的关系。

谢谢！

**Comment by wanghaoshuang** [comment]
>PP与Pytorch是否可以安装在同一个虚拟环境下，如果可以，是否有版本对应关系？

理论上是可以在一个虚拟环境下同时使用的，但是我们没有验证过，所以也无法给出版本对应关系的建议。

>PP与Pytorch是否可以在同一个project内使用，如果可以需要注意什么？

这个应该是不可以的

>我看PARL底层有用到torch里的代码，所以想了解PP与Pytorch之间的关系。

PaddlePaddle与Pytorch没有直接的关系，都相互独立的深度学习框架

**Comment by jkren6** [comment]
谢谢
