### ISSUE TITLE
[论文复现]我还原了个版本在运行就出现了这个问题，上边预测没什么错误

### ISSUE THREAD

**Issue by 1084667371** [PaddlePaddle/Paddle#25820]
![XK0~7{2T F0_4QKIHPJ F50](https://user-images.githubusercontent.com/50902619/88875169-5c3f6b00-d253-11ea-9724-6b8878551071.png)

**Comment by saxon-zh** [comment]
请靳老师看下

**Comment by weiexcelpro** [comment]
这个看起来是opencv的用法问题. 请检查图片路径. 打印license_plate变量进行查看. 

可参考: 
https://stackoverflow.com/questions/52676020/opencv-src-empty-in-function-cvtcolor-error

**Comment by saxon-zh** [comment]
@1084667371 还有问题吗
