### ISSUE TITLE
【顶会论文复现】Aistudio中Cell运行结果过多，不会自动看到最下面的

### ISSUE THREAD

**Issue by yinyiyu** [PaddlePaddle/Paddle#25823]
在代码运行结果过多的试试，cell不会自动显示最下面的结果，只是多出来右边的滑轮，用户体验不好
![image](https://user-images.githubusercontent.com/24800963/88875979-da504180-d254-11ea-8f25-3c41b2a4ed8d.png)

**Comment by weiexcelpro** [comment]
Hi 我是AIStudio的PM, 感谢建议. 我们会考虑优化.
