### ISSUE TITLE
【顶会论文复现】模型加载问题

### ISSUE THREAD

**Issue by yinyiyu** [PaddlePaddle/Paddle#25821]
paddlepaddle在使用mode.load_ditc()报错
![image](https://user-images.githubusercontent.com/24800963/88875725-601fbd00-d254-11ea-9913-111faa58ea92.png)
![image](https://user-images.githubusercontent.com/24800963/88875726-601fbd00-d254-11ea-8488-fb1737707615.png)
![image](https://user-images.githubusercontent.com/24800963/88875737-6746cb00-d254-11ea-84b6-592f8a2f12d8.png)

**Comment by saxon-zh** [comment]
辛苦提供下完整的代码吧
