### ISSUE TITLE
如何保证参数在训练过程中保证非负值？

### ISSUE THREAD

**Issue by KyrieG** [PaddlePaddle/Paddle#25827]
我这边搭建的nn网络中，使用了几个fc层，参数初始化为[0,1] 同时想要保证在训练过程中，每次参数更新后，参数仍然保持非负的状态，例如 某次更新后，某个参数值 = max(0, 当前更新后的值)
请问这个该如何操作呢

**Comment by qingqing01** [comment]
@KyrieG 请问使用的动态图还是静态图？ 

静态图目前没有直接的对weight进行截断的函数。 间接的方法，可以每个step计算后，拿到weight做clip，再进行下一次计算。



动态图是可以在forward前对weight截断，或通过 https://www.paddlepaddle.org.cn/documentation/docs/zh/api_cn/dygraph_cn/Layer_cn.html#register-forward-pre-hook-hook 或 这个PR中加的apply的方式  https://github.com/PaddlePaddle/Paddle/pull/25812/files
