### ISSUE TITLE
【论文复现】GPU不支持cuda10.1

### ISSUE THREAD

**Issue by 1084667371** [PaddlePaddle/Paddle#25826]
paddle paddle啥时候能支持下Windows的cuda10.1呀

**Comment by JunnYu** [comment]
我在Windows10 cuda10.1 cudnn 7.6.5 VS2017 成功编译了paddlepaddle1.8，这个是编译好的地址 https://ws28.cn/f/356veinhf3c ，你可以尝试下载试试，pip install -U paddlepaddle_gpu-1.8.0.post1017-cp37-cp37m-win_amd64.whl

**Comment by 1084667371** [comment]
好的 谢谢谢谢
