### ISSUE TITLE
编译错误：Win10 vs2015下编译paddle1.8, 项目paddle_fluid_c_shared生成失败

### ISSUE THREAD

**Issue by RayCAS2017** [PaddlePaddle/Paddle#25829]
版本、环境信息：
    1）PaddlePaddle版本：1.8,  GIT COMMIT ID: 8bb535b8b34bfd1a1a61043967a8c48c15997a10
    2）CPU：MKL/MKLDNN/ OFF
    3）GPU：GTX1060, CUDA 10.0和CUDNN 7.6

编译时，出现这个问题：
![Linkerror](https://user-images.githubusercontent.com/29969779/88879762-aaf20280-d25d-11ea-806b-d2caed0b9765.jpg)

**Comment by zhwesky2010** [comment]
@RayCAS2017  你好，请问是只编译paddle_fluid_c_shared这个target吗

**Comment by RayCAS2017** [comment]
是编译整个paddle1.8的时候，只有这个项目编译失败。单独编译这个也会失败。不知道这个项目是做什么用？对C++的推理部署有什么影响？

**Comment by RayCAS2017** [comment]
@zhouwei25 是编译整个paddle1.8的时候，只有这个项目编译失败。单独编译这个也会失败。不知道这个项目是做什么用？对C++的推理部署有什么影响？

**Comment by zhwesky2010** [comment]
@RayCAS2017 这个是CAPI的预测库，用于C语言部署，对C++部署没有影响，是不是你这个版本有什么问题，最新的编没什么问题。或者之前的编译目录和产出没有清除？
