### ISSUE TITLE
【论文复现】aistudio大于20M就打不开了，一直转圈圈

### ISSUE THREAD

**Issue by livingbody** [PaddlePaddle/Paddle#25832]
aistudio的ipynb大于20M就打不开了，一直转圈圈，建议能否做个检测，或者缓冲？不要一次加载完毕。

**Comment by GT-ZhangAcer** [comment]
这个是平台问题，和paddle无关

**Comment by weiexcelpro** [comment]
我是AIStudio的PM. 请问您说的ipynb大于20MB打不开, 一直转圈圈, 可否提供一个截图(最好截上url栏)

**Comment by livingbody** [comment]
可以打开了。就是等的时间久一点，比以前好多了。
