### ISSUE TITLE
【论文复现】PaddlePaddle的Anaconda 安装问题

### ISSUE THREAD

**Issue by livingbody** [PaddlePaddle/Paddle#25830]
https://www.paddlepaddle.org.cn/install/quick中提到的Anaconda 安装方法，多次测试不成功。
建议使用oh-my-tuna，避免走弯路。
这个弯弯，已经被n多人问过了，都快哭了。

**Comment by saxon-zh** [comment]
辛苦提供一下相关软硬件、操作系统信息和操作过程及暴漏的问题截图吧，我们跟进看下。
