### ISSUE TITLE
【论文复现】PaddlePaddle的 GPU安装问题

### ISSUE THREAD

**Issue by livingbody** [PaddlePaddle/Paddle#25831]
PaddlePaddle版本 GPU版本给出了CUDA和cuDNN 安装地址，但是国外网址，很难下载下来。
99% GPU版本安装都是卡在这个位置，希望能重视下，解决这个问题。

**Comment by saxon-zh** [comment]
目前CUDA相关安装包是NVIDIA官方提供下载，这个问题飞桨不太能够解决，https://www.baidu.com/s?wd=cudnn%E4%B8%8B%E8%BD%BD%E6%85%A2    可以看看这里的一些相关解决思路。
