### ISSUE TITLE
【顶会论文复现】教程单词错误

### ISSUE THREAD

**Issue by yinyiyu** [PaddlePaddle/Paddle#25836]
![image](https://user-images.githubusercontent.com/24800963/88885259-c31c4e80-d26a-11ea-9b8f-59ae34c2240e.png)
https://www.paddlepaddle.org.cn/tutorials/projectdetail/570711

**Comment by saxon-zh** [comment]
收到，感谢您的反馈，已反馈进行安排修复。

**Comment by saxon-zh** [comment]
已在官网上修复上线，请知悉。
