### ISSUE TITLE
运行代码报错no kernel image is available for execution on the device errno

### ISSUE THREAD

**Issue by JerryLeolfl** [PaddlePaddle/Paddle#25846]
**CentOS6.3+P40+CUDA9.0+cudnn7.6+python3.7安装来自另一台v100的编译的whl包，运行代码时报错**
cudaGetLastError  no kernel image is available for execution on the device errno: 48
*** Check failure stack trace: ***
    @     0x7f0c2636f7ed  google::LogMessage::Fail()
    @     0x7f0c26371b38  google::LogMessage::SendToLog()
    @     0x7f0c2636f2fb  google::LogMessage::Flush()
    @     0x7f0c26372a0e  google::LogMessageFatal::~LogMessageFatal()
    @     0x7f0c2648af21  paddle::platform::CUDADeviceContext::Wait()
    @     0x7f0c2672c0b8  paddle::operators::StackKernel<>::Compute()
    @     0x7f0c2672c54f  _ZNSt17_Function_handlerIFvRKN6paddle9framework16ExecutionContextEEZNKS1_24OpKernelRegistrarFunctorINS0_8platform9CUDAPlaceELb0ELm0EINS0_9operators11StackKernelINS7_17CUDADeviceContextEfEENSA_ISB_dEENSA_ISB_iEENSA_ISB_lEENSA_ISB_NS7_7float16EEEEEclEPKcSK_iEUlS4_E_E9_M_invokeERKSt9_Any_dataS4_
    ...

**Comment by Superjomn** [comment]
参考 https://stackoverflow.com/questions/55538036/cuda-nvcc-no-kernel-image-is-available-for-execution-on-the-device-what-is

这个错误直接的结论是，卡太旧，cuda 太新

**Comment by JerryLeolfl** [comment]
> 参考 https://stackoverflow.com/questions/55538036/cuda-nvcc-no-kernel-image-is-available-for-execution-on-the-device-what-is
> 
> 这个错误直接的结论是，卡太旧，cuda 太新

但是相同的配置pytorch tensorflow都可以用呀

**Comment by Superjomn** [comment]
建议直接安装官方编译好的包，自行编译的变量比较多了
