### ISSUE TITLE
PALM预测相似文本的时候准确率下降了

### ISSUE THREAD

**Issue by yeguang1991** [PaddlePaddle/Paddle#25841]
我把预测的代码封装成提前加载模型，然后有文本来了就直接预测，但是当我同时加载了两个训练模型之后，会影响第一个模型的准确率，请问是什么原因导致的，应该怎么解决？
![image](https://user-images.githubusercontent.com/66579493/88893484-febe1500-d278-11ea-9233-f6bcf8b20e73.png)
这是只加载第一个模型的时候预测的结果：
![image](https://user-images.githubusercontent.com/66579493/88893084-66279500-d278-11ea-9477-81e554a74a75.png)
这是加载第二个模型之后，第一个模型预测的结果
![image](https://user-images.githubusercontent.com/66579493/88893568-20b79780-d279-11ea-8ca3-93ac80ebcd68.png)

**Comment by Superjomn** [comment]
这个是修改的官方提供的模型吗？
方便提供原始模型的链接吗

封装上层看不到具体的细节

**Comment by yeguang1991** [comment]
> 这个是修改的官方提供的模型吗？
> 方便提供原始模型的链接吗
> 
> 封装上层看不到具体的细节

https://github.com/PaddlePaddle/PALM/tree/master/examples/matching
这个模型，我封装了run.py里的for prediction部分，然后按照我上面的封装进行预测，两次预测结果不一样，预测方式大概是这样的
![image](https://user-images.githubusercontent.com/66579493/88989689-c537e900-d30e-11ea-867b-94b8be7c369a.png)

**Comment by yeguang1991** [comment]
> 这个是修改的官方提供的模型吗？
> 方便提供原始模型的链接吗
> 
> 封装上层看不到具体的细节

请问一下是什么原因，有什么办法解决吗
