### ISSUE TITLE
新增input字段报错：var sign_id not in this block

### ISSUE THREAD

**Issue by Joyo2016** [PaddlePaddle/Paddle#25845]
版本：1.6.1
模型新增一个input字段：sign_id
![image](https://user-images.githubusercontent.com/19165659/88898348-29ab6780-d27f-11ea-89f8-4055e048942b.png)

字段值暂时是写死的，为了带一个标记过去，网络用不着这个字段，只需要在net中输出
![image](https://user-images.githubusercontent.com/19165659/88898468-5b243300-d27f-11ea-9a54-2798486ded9a.png)
![image](https://user-images.githubusercontent.com/19165659/88898584-83ac2d00-d27f-11ea-91f8-766eb519c228.png)

执行训练后报错：
![image](https://user-images.githubusercontent.com/19165659/88898632-94f53980-d27f-11ea-8a6a-3ae9132d958a.png)

在net中加上一行print后就跑通了，不知道为啥
![image](https://user-images.githubusercontent.com/19165659/88899770-0c779880-d281-11ea-856c-279b799f6c00.png)

相关代码：
![image](https://user-images.githubusercontent.com/19165659/88898920-ff0dde80-d27f-11ea-8e32-66a4c4d61774.png)
![image](https://user-images.githubusercontent.com/19165659/88898860-eb627800-d27f-11ea-820f-86afdd7b1388.png)

**Comment by NHZlX** [comment]
估计某个环节将没有用到的输入给剪掉了，可以在这个输入后加一个scale op，设置scale为1，可以临时解决这个问题。引起这个问题的具体的原因会继续跟进下。

**Comment by Joyo2016** [comment]
> 估计某个环节将没有用到的输入给剪掉了，可以在这个输入后加一个scale op，设置scale为1，可以临时解决这个问题。引起这个问题的具体的原因会继续跟进下。

可以通过设置避免裁剪吗

**Comment by Superjomn** [comment]
暂时没有其他方法。

直接 data 作为输出得用这个 trick
