### ISSUE TITLE
【论文复现】连运行!ls /home/aistudio/data或导包都在打圈。

### ISSUE THREAD

**Issue by wuyi1405** [PaddlePaddle/Paddle#25849]
在论文复现作业时，启动环境，建立版本，选择版本，运行简单的!ls /home/aistudio/data都在打圈，即使不运行这条简单的命令，直接运行导包，也是还是打圈卡在程序里。请问是什么情况。百度账号:xiaodi1405
![baidu](https://user-images.githubusercontent.com/25198497/88923803-d77d3d00-d2a4-11ea-9dac-a716b443a88c.JPG)

**Comment by wuyi1405** [comment]
在论文复现作业时，启动环境，建立版本，选择版本，运行简单的!ls /home/aistudio/data都在打圈，即使不运行这条简单的命令，直接运行导包，也是还是打圈卡在程序里。请问是什么情况。百度账号:xiaodi1405
![baidu](https://user-images.githubusercontent.com/25198497/88923666-a7359e80-d2a4-11ea-9d17-7f4858b80a5b.JPG)

**Comment by wuyi1405** [comment]
基础版：
https://aistudio.baidu.com/bdvgpu/user/303001/670169/notebooks/670169.ipynb
作业版：
https://aistudio.baidu.com/bdcpu7/user/303001/664581/notebooks/664581.ipynb
运行简单的!ls /home/aistudio/data都在打圈

**Comment by GT-ZhangAcer** [comment]
这个是平台问题，和paddle无关

**Comment by saxon-zh** [comment]
请靳老师看下

**Comment by weiexcelpro** [comment]
我们这边查看一下具体原因

**Comment by weiexcelpro** [comment]
> 
> 
> 在论文复现作业时，启动环境，建立版本，选择版本，运行简单的!ls /home/aistudio/data都在打圈，即使不运行这条简单的命令，直接运行导包，也是还是打圈卡在程序里。请问是什么情况。百度账号:xiaodi1405
> ![baidu](https://user-images.githubusercontent.com/25198497/88923803-d77d3d00-d2a4-11ea-9dac-a716b443a88c.JPG)

hi, 该问题较难定位, 是否可以提供一个QQ号或微信号, 我们RD想和您直接沟通一下, 加快定位速度

**Comment by yuctian** [comment]
重启 环境基本就能解决

**Comment by wuyi1405** [comment]
已经解决，百度开发人员联系我找到原因，原因是浏览器插件屏蔽了websocket，或者网络经过了路由、网关有对websocket类型的消息进行拦截处理。解决办法：可以通过更换浏览器或通过手机的4/5g热点走不通的网络链路来解决。
