### ISSUE TITLE
[论文复现] 弄不懂conv2D参数dilation, group的含义，什么情况可以用这两个参数，还有dilation和上采样的关系又是什么

### ISSUE THREAD

**Issue by minghuisvn** [PaddlePaddle/Paddle#25855]
请问conv2D dilation和group参数是什么意思，什么情况下用得到这两个参数？

**Comment by saxon-zh** [comment]
dilation指的是空洞率，主要是在空洞卷积操作中使用。groups用在分组卷积操作上，对输入数据通道进行分组，groups参数是指定分多少组，目标用户减少训练的卷积核参数。
