### ISSUE TITLE
MPI集群报错,SocketChannel.cpp check failed len >= 0

### ISSUE THREAD

**Issue by zhangyong15** [PaddlePaddle/Paddle#2585]
现象，集群训练报错，Local模式正常。期间使用classification_cost报top k，依照#2574方法尝试解决，报相关错误如下：
Fri Jun 23 15:40:01 2017[1,53]<stderr>:F0623 15:40:01.543020 31957 LightNetwork.cpp:397] Check failed: error >= 0 ERROR connecting to 10.87.100.36: Connection refused [111]
Fri Jun 23 15:40:01 2017[1,53]<stderr>:*** Check failure stack trace: ***
Fri Jun 23 15:40:01 2017[1,53]<stderr>:F0623 15:40:01.543030 32628 LightNetwork.cpp:397] Check failed: error >= 0 ERROR connecting to 10.87.100.36: Connection refused [111]
Fri Jun 23 15:40:01 2017[1,53]<stderr>:*** Check failure stack trace: ***
Fri Jun 23 15:40:01 2017[1,53]<stderr>:    @           0x91316d  google::LogMessage::Fail()
Fri Jun 23 15:40:01 2017[1,53]<stderr>:    @           0x91316d  google::LogMessage::Fail()
Fri Jun 23 15:40:01 2017[1,53]<stderr>:    @           0x916c1c  google::LogMessage::SendToLog()
Fri Jun 23 15:40:01 2017[1,53]<stderr>:    @           0x912c93  google::LogMessage::Flush()
Fri Jun 23 15:40:01 2017[1,53]<stderr>:    @           0x916c1c  google::LogMessage::SendToLog()
Fri Jun 23 15:40:01 2017[1,53]<stderr>:    @           0x912e99  google::LogMessage::~LogMessage()
Fri Jun 23 15:40:01 2017[1,53]<stderr>:    @           0x912c93  google::LogMessage::Flush()
Fri Jun 23 15:40:01 2017[1,53]<stderr>:    @           0x916147  google::ErrnoLogMessage::~ErrnoLogMessage()
Fri Jun 23 15:40:01 2017[1,53]<stderr>:    @           0x912e99  google::LogMessage::~LogMessage()
Fri Jun 23 15:40:01 2017[1,53]<stderr>:    @           0x768fa1  paddle::SocketClient::TcpClient()
Fri Jun 23 15:40:01 2017[1,53]<stderr>:    @           0x916147  google::ErrnoLogMessage::~ErrnoLogMessage()
Fri Jun 23 15:40:01 2017[1,53]<stderr>:    @           0x7691a1  paddle::SocketClient::SocketClient()
Fri Jun 23 15:40:01 2017[1,53]<stderr>:    @           0x768fa1  paddle::SocketClient::TcpClient()
Fri Jun 23 15:40:01 2017[1,53]<stderr>:    @           0xf06e50  paddle::ParameterClient2::init()

**Comment by jacquesqiao** [comment]
第一次错误被证明是集群上存在一些不正确的数据文件：
![image](https://user-images.githubusercontent.com/3048612/27477706-894124fe-583f-11e7-8dea-2568bff24bc6.png)
用户去掉这些错误文件之后，还是报错

**Comment by jacquesqiao** [comment]
第二次错误是因为float point exception.
![image](https://user-images.githubusercontent.com/3048612/27477745-abde1f26-583f-11e7-8428-c2a511796949.png)

建议用户调小学习率，正在测试

**Comment by zhangyong15** [comment]
调小学习率
Mon Jun 26 10:30:50 2017[1,7]<stderr>:+ ./paddle_trainer --num_gradient_servers=100 --trainer_id=7 --pservers=10.87.109.15,10.87.109.18,10.87.109.17,10.87.109.19,10.87.109.12,10.87.109.11,10.87.109.14,10.87.109.13,10.87.109.29,10.87.109.28,10.87.109.27,10.87.106.45,10.87.109.26,10.87.109.21,10.87.106.40,10.87.109.25,10.87.106.43,10.87.106.44,10.87.109.24,10.87.109.23,10.87.106.41,10.87.106.42,10.87.109.22,10.87.89.27,10.87.107.42,10.87.107.43,10.87.107.44,10.87.107.45,10.87.107.41,10.87.107.39,10.87.107.37,10.87.107.38,10.87.107.35,10.87.107.36,10.87.107.33,10.87.107.34,10.87.107.31,10.87.107.32,10.87.107.24,10.87.107.25,10.87.107.26,10.87.107.27,10.87.107.28,10.87.107.29,10.87.107.20,10.87.107.21,10.87.107.22,10.87.107.23,10.87.107.15,10.87.107.16,10.87.107.13,10.87.107.14,10.87.107.19,10.87.107.17,10.87.107.18,10.87.107.11,10.87.107.12,10.87.87.31,10.87.87.33,10.87.87.34,10.87.87.36,10.87.87.37,10.87.87.38,10.87.87.39,10.87.87.22,10.87.87.21,10.87.87.20,10.87.87.25,10.87.87.26,10.87.87.23,10.87.87.24,10.87.87.27,10.87.87.28,10.87.87.11,10.87.87.16,10.87.87.17,10.87.87.18,10.87.87.19,10.87.87.12,10.87.87.13,10.87.87.14,10.87.87.15,10.87.87.45,10.87.87.41,10.87.87.42,10.87.87.44,10.87.138.43,10.87.138.42,10.87.138.41,10.87.138.40,10.87.138.45,10.87.138.44,10.87.138.21,10.87.138.20,10.87.138.29,10.87.138.28,10.87.138.27,10.87.138.26,10.87.138.25,10.87.138.24 --rdma_tcp=tcp --nics=xgbe0 --port=8429 --ports_num=1 --test_all_data_in_one_period=true --log_period=20 --num_passes=50 --trainer_count=8 --config_args=is_cluster=1 --ports_num_for_sparse=1 --local=0 --config=conf/trainer_config.conf --save_dir=./output --use_gpu=0
Mon Jun 26 10:30:51 2017[1,7]<stderr>:[INFO 2017-06-26 10:30:51,104 networks.py:1482] The input order is [ad_user_layer, ad_unit_layer, ad_plan_layer, user_layer, media_layer, label]
Mon Jun 26 10:30:51 2017[1,7]<stderr>:[INFO 2017-06-26 10:30:51,105 networks.py:1488] The output order is [__cost_0__]
Mon Jun 26 10:31:06 2017[1,92]<stderr>:*** Aborted at 1498444266 (unix time) try "date -d @1498444266" if you are using GNU date ***
Mon Jun 26 10:31:06 2017[1,92]<stderr>:PC: @                0x0 (unknown)
Mon Jun 26 10:31:06 2017[1,80]<stderr>:*** Aborted at 1498444266 (unix time) try "date -d @1498444266" if you are using GNU date ***
Mon Jun 26 10:31:06 2017[1,80]<stderr>:PC: @                0x0 (unknown)
Mon Jun 26 10:31:06 2017[1,80]<stderr>:*** SIGSEGV (@0x0) received by PID 7976 (TID 0x7f991b84d780) from PID 0; stack trace: ***
Mon Jun 26 10:31:06 2017[1,80]<stderr>:    @     0x7f991b008160 (unknown)
Mon Jun 26 10:31:06 2017[1,80]<stderr>:    @           0x6bfd35 paddle::ClassificationErrorEvaluator::evalImp()
Mon Jun 26 10:31:06 2017[1,80]<stderr>:    @           0x6b8690 paddle::Evaluator::eval()
Mon Jun 26 10:31:06 2017[1,80]<stderr>:    @           0x6a2708 paddle::CombinedEvaluator::eval()
Mon Jun 26 10:31:06 2017[1,80]<stderr>:    @           0x6a857a paddle::MultiGradientMachine::eval()
Mon Jun 26 10:31:06 2017[1,80]<stderr>:    @           0x74bdf6 paddle::TrainerInternal::trainOneBatch()
Mon Jun 26 10:31:06 2017[1,80]<stderr>:    @           0x749616 paddle::Trainer::trainOneDataBatch()
Mon Jun 26 10:31:06 2017[1,80]<stderr>:    @           0x749abd paddle::Trainer::trainOnePass()
Mon Jun 26 10:31:06 2017[1,80]<stderr>:    @           0x74a375 paddle::Trainer::train()
Mon Jun 26 10:31:06 2017[1,31]<stderr>:*** Aborted at 1498444266 (unix time) try "date -d @1498444266" if you are using GNU date ***
Mon Jun 26 10:31:06 2017[1,80]<stderr>:    @           0x5a3d70 main
Mon Jun 26 10:31:06 2017[1,31]<stderr>:PC: @                0x0 (unknown)
Mon Jun 26 10:31:06 2017[1,92]<stderr>:*** SIGSEGV (@0x0) received by PID 10024 (TID 0x7fe638281780) from PID 0; stack trace: ***
Mon Jun 26 10:31:06 2017[1,92]<stderr>:    @     0x7fe637a3c160 (unknown)
Mon Jun 26 10:31:06 2017[1,92]<stderr>:    @           0x6bfd35 paddle::ClassificationErrorEvaluator::evalImp()
Mon Jun 26 10:31:06 2017[1,92]<stderr>:    @           0x6b8690 paddle::Evaluator::eval()
Mon Jun 26 10:31:06 2017[1,92]<stderr>:    @           0x6a2708 paddle::CombinedEvaluator::eval()
Mon Jun 26 10:31:06 2017[1,31]<stderr>:*** SIGSEGV (@0x0) received by PID 11243 (TID 0x7f2fde0d9780) from PID 0; stack trace: ***
Mon Jun 26 10:31:06 2017[1,92]<stderr>:    @           0x6a857a paddle::MultiGradientMachine::eval()
Mon Jun 26 10:31:06 2017[1,92]<stderr>:    @           0x74bdf6 paddle::TrainerInternal::trainOneBatch()
Mon Jun 26 10:31:06 2017[1,92]<stderr>:    @           0x749616 paddle::Trainer::trainOneDataBatch()
Mon Jun 26 10:31:06 2017[1,31]<stderr>:    @     0x7f2fdd894160 (unknown)
Mon Jun 26 10:31:06 2017[1,92]<stderr>:    @           0x749abd paddle::Trainer::trainOnePass()
Mon Jun 26 10:31:06 2017[1,31]<stderr>:    @           0x6bfd35 paddle::ClassificationErrorEvaluator::evalImp()
Mon Jun 26 10:31:06 2017[1,92]<stderr>:    @           0x74a375 paddle::Trainer::train()
Mon Jun 26 10:31:06 2017[1,92]<stderr>:    @           0x5a3d70 main
Mon Jun 26 10:31:06 2017[1,31]<stderr>:    @           0x6b8690 paddle::Evaluator::eval()
Mon Jun 26 10:31:06 2017[1,31]<stderr>:    @           0x6a2708 paddle::CombinedEvaluator::eval()
Mon Jun 26 10:31:06 2017[1,31]<stderr>:    @           0x6a857a paddle::MultiGradientMachine::eval()
Mon Jun 26 10:31:06 2017[1,31]<stderr>:    @           0x74bdf6 paddle::TrainerInternal::trainOneBatch()
Mon Jun 26 10:31:06 2017[1,31]<stderr>:    @           0x749616 paddle::Trainer::trainOneDataBatch()
Mon Jun 26 10:31:06 2017[1,31]<stderr>:    @           0x749abd paddle::Trainer::trainOnePass()
Mon Jun 26 10:31:06 2017[1,31]<stderr>:    @           0x74a375 paddle::Trainer::train()
Mon Jun 26 10:31:06 2017[1,92]<stderr>:    @     0x7fe636c80bd5 __libc_start_main
Mon Jun 26 10:31:06 2017[1,31]<stderr>:    @           0x5a3d70 main
Mon Jun 26 10:31:06 2017[1,80]<stderr>:    @     0x7f991a24cbd5 __libc_start_main
Mon Jun 26 10:31:06 2017[1,92]<stderr>:    @           0x5b2169 (unknown)
Mon Jun 26 10:31:06 2017[1,80]<stderr>:    @           0x5b2169 (unknown)
Mon Jun 26 10:31:06 2017[1,92]<stderr>:    @                0x0 (unknown)
Mon Jun 26 10:31:06 2017[1,80]<stderr>:    @                0x0 (unknown)
Mon Jun 26 10:31:06 2017[1,31]<stderr>:    @     0x7f2fdcad8bd5 __libc_start_main
Mon Jun 26 10:31:06 2017[1,31]<stderr>:    @           0x5b2169 (unknown)
Mon Jun 26 10:31:06 2017[1,31]<stderr>:    @                0x0 (unknown)
Mon Jun 26 10:31:07 2017[1,45]<stderr>:*** Aborted at 1498444267 (unix time) try "date -d @1498444267" if you are using GNU date ***
Mon Jun 26 10:31:07 2017[1,45]<stderr>:PC: @                0x0 (unknown)
Mon Jun 26 10:31:07 2017[1,31]<stderr>:./train.sh: line 207: 11243 Segmentation fault      PYTHONPATH=./paddle:$PYTHONPATH GLOG_logtostderr=0 GLOG_log_dir="./log" ./paddle_trainer --num_gradient_servers=${OMPI_COMM_WORLD_SIZE} --trainer_id=${OMPI_COMM_WORLD_RANK} --pservers=$ipstring --rdma_tcp=${rdma_tcp} --nics=${nics} ${train_arg} --config=conf/trainer_config.conf --save_dir=./${save_dir} ${extern_arg}
Mon Jun 26 10:31:07 2017[1,31]<stderr>:+ '[' 139 -ne 0 ']'

**Comment by typhoonzero** [comment]
Please refer to latest FAQ: https://github.com/PaddlePaddle/Paddle/blob/develop/doc/faq/index_cn.rst#id15

Close this for now.
