### ISSUE TITLE
【论文复现】ai studio 信息显示错误

### ISSUE THREAD

**Issue by livingbody** [PaddlePaddle/Paddle#25852]
ai studio 信息显示错误

1. 左侧环境--显存，显示16G。
2. 底部性能监控--实时数据，显示32G显存。

两者冲突，信息不一致。

**Comment by shaunhurryup** [comment]
这个是平台问题，和paddle无关

**Comment by GT-ZhangAcer** [comment]
这个是平台问题，和paddle无关

**Comment by saxon-zh** [comment]
请靳老师看一下

**Comment by weiexcelpro** [comment]
这个是因为线上部分GPU型号是16GB显存版本的. 配置显示就低不就高. 
真实配置, 请以实时数据中显示的为准.
