### ISSUE TITLE
paddle inderence 有内存泄漏问题

### ISSUE THREAD

**Issue by wgh1989** [PaddlePaddle/Paddle#25856]
直接使用官方paddle-inference-demo，出现内存泄漏问题
fluid_paddle版本号：官方下载
https://paddle-inference-lib.bj.bcebos.com/latest-gpu-cuda10-cudnn7-avx-mkl/fluid_inference.tgz
GIT COMMIT ID: c9285a18a0e75d20adde189e77afba86b43d5155
WITH_MKL: ON
WITH_MKLDNN: ON
WITH_GPU: ON
CUDA version: 10.0
CUDNN version: v7.6
CXX compiler version: 4.8.2

环境信息：
CUDA-10.0，CUDNN-7.6.5
CentOS-7.7.1908
python-3.6.7

预测信息：
官方下载：Paddle-Inference-Demo，c++，res50示例
https://github.com/PaddlePaddle/Paddle-Inference-Demo/tree/master/c%2B%2B/resnet50
存在内存泄漏：
使用valgrind工具查看
valgrind --tool=memcheck --leak-check=full --log-file=out.txt \
./build/resnet50_test --model_file=models/ResNet50/model --params_file=models/ResNet50/params

![image](https://user-images.githubusercontent.com/35423940/88996972-1ea91380-d321-11ea-8d62-0f099645bc5a.png)

**Comment by NHZlX** [comment]
这个有可能是初始化阶段用到了一些单例没有释放，这种情况对推理阶段没有影戏。模型初始化后，推理期间不会有这种情况

**Comment by wgh1989** [comment]
我这边valgrind分析结果最终指向大多都是libpaddle_fluid.so，您可以用valgrind查一下具体log
目前我们跟paddle相关的多个业务线（包括分类、检测）都出现内存泄漏，麻烦帮忙跟进查一下
下面valgrind部分分析结果，有的是yolo-v3示例，供参考：
![image](https://user-images.githubusercontent.com/35423940/89006421-52903300-d339-11ea-88ca-ec18cc884810.png)
![image](https://user-images.githubusercontent.com/35423940/89006507-7fdce100-d339-11ea-8d2c-ae14b84a013c.png)
![image](https://user-images.githubusercontent.com/35423940/89006620-b7e42400-d339-11ea-91e5-596ff3a99e31.png)
这几个泄漏示例都出现多次，指向都是libpaddle_fluid.so

不管是初始化阶段单例未释放，还是模型推理的内存泄漏，麻烦都帮忙check下，提供一个没有内存泄漏的版本，至少官方demo保证不回出现这个问题，我们具体业务也可以依据demo进行修复，感谢

**Comment by NHZlX** [comment]
可否用单测验证下，某个模型下“循环推理”是否会导致内存上涨的现象

**Comment by wgh1989** [comment]
这个问题线下有同学单独联系我了
“循环推理”zerocopyrun暂时没有发现内存上涨情况
我们业务端的代码还是存在内存上涨情况，我会从zerocopyrun开始往外扩展，持续查看问题所在，有进展会再贴出来

另外，从valgrind分析看，这个demo肯定是存在有申请的内存没有释放的情况（即使是初始化阶段），作为官方demo，也希望修复下这个问题

**Comment by pineking** [comment]
> 这个问题线下有同学单独联系我了
> “循环推理”zerocopyrun暂时没有发现内存上涨情况
> 我们业务端的代码还是存在内存上涨情况，我会从zerocopyrun开始往外扩展，持续查看问题所在，有进展会再贴出来
> 
> 另外，从valgrind分析看，这个demo肯定是存在有申请的内存没有释放的情况（即使是初始化阶段），作为官方demo，也希望修复下这个问题

赞同
