### ISSUE TITLE
【论文复现】 Need to Create DeviceContextPool first Error

### ISSUE THREAD

**Issue by yinyiyu** [PaddlePaddle/Paddle#25853]
![image](https://user-images.githubusercontent.com/24800963/88992414-ecde7f80-d315-11ea-8959-b52c7238eaec.png)

**Comment by GT-ZhangAcer** [comment]
因为notebook没有程序终止的说法，不会自动去释放内存。如果同一个cell被运行两次就会声明两次，从而出现这个问题，不仅是AI Studio上会出现，而且jupyter也会出现。避开这个情况的最好方法是使用非notebook工具来运行代码。
