### ISSUE TITLE
"Not compiled with CUDA" AssertionError: Not compiled with CUDA

### ISSUE THREAD

**Issue by Yuanml1225** [PaddlePaddle/Paddle#25866]
paddlepaddle-1.8.1
paddlehub-1.7.1
CUDA Version 9.2.148
当前环境高级版
CPU 4
RAM 32GB
GPU v100
显存16GB
磁盘100GB

在使用module = hub.Module(name="bert_multi_cased_L-12_H-768_A-12")时，出现
    "Not compiled with CUDA"
AssertionError: Not compiled with CUDA
请问如何解决

**Comment by seiriosPlus** [comment]
使用的Paddle版本不正确，需要使用带CUDA的版本
请使用：
`
python -m pip install paddlepaddle-gpu==1.8.3.post97 -i https://mirror.baidu.com/pypi/simple
`
