### ISSUE TITLE
【论文复现】环境出现过崩溃，不止一次

### ISSUE THREAD

**Issue by zb-tjw** [PaddlePaddle/Paddle#25874]
- 版本、环境信息：
    1）PaddlePaddle版本：PaddlePaddle 1.8.0
    2）Python：python3.7
    3）GPU：v100
    4）复现项目：用GAN来生成Mnist数字
- 训练信息
    1）单机，单卡
    2）显存信息 16GB
    3）应用DCGAN来训练，崩溃出现在晚上9点左右，可能那个时间段用GPU的人数较多，每次做多运行完epoch0和epoch1就崩溃，然后停止环境的时候也会卡好久才能停止。应该不是代码原因，晚上听着课从10点开始再次尝试运行，一直运行到凌晨一点半程序一切正常，自己人为结束的程序。具体的崩溃截图如下：图一是崩溃图，图二是停止环境一直等待的图
![image](https://user-images.githubusercontent.com/23249908/89091825-3e9f0c80-d3df-11ea-8ae9-d18a93fdb52e.png)
![image](https://user-images.githubusercontent.com/23249908/89091826-42cb2a00-d3df-11ea-9914-34363bb2f35a.png)
以前也经常打卡用这个GPU，从来没有遇到过这个情况，请官方关注，如果可以期望收到问题回复

**Comment by weiexcelpro** [comment]
可否提供一下项目网址

**Comment by zb-tjw** [comment]
https://aistudio.baidu.com/bdvgpu32g/user/3260/672372/notebooks/672372.ipynb这个地址可以吗，如果不行可以继续配合百度方面的工作

**Comment by zb-tjw** [comment]
`from __future__ import absolute_import
from __future__ import division
from __future__ import print_function
import paddle
import paddle.fluid as fluid
import os

gf_dim = 64
df_dim = 64
gfc_dim = 1024 * 2
dfc_dim = 1024
img_dim = 28

c_dim = 3
y_dim = 1
output_height = 28
output_width = 28

use_cudnn = True
if 'ce_mode' in os.environ:
    use_cudnn = False


def bn(x, name=None, act='relu'):
    if name is None:
        name = get_parent_function_name()
    #return fluid.layers.leaky_relu(x)
    return fluid.layers.batch_norm(
        x,
        # param_attr=name + '1',
        # bias_attr=name + '2',
        # moving_mean_name=name + '3',
        # moving_variance_name=name + '4',
        # name=name,
        act=act)


def conv(x, num_filters, name=None, act=None):
    if name is None:
        name = get_parent_function_name()
    return fluid.nets.simple_img_conv_pool(
        input=x,
        filter_size=5,
        num_filters=num_filters,
        pool_size=2,
        pool_stride=2,
        # param_attr=name + 'w',
        # bias_attr=name + 'b',
        use_cudnn=use_cudnn,
        act=act)


def fc(x, num_filters, name=None, act=None):
    if name is None:
        name = get_parent_function_name()
    return fluid.layers.fc(
        input=x,
        size=num_filters,
        act=act,
        # param_attr=name + 'w',
        # bias_attr=name + 'b'
        )


def deconv(x,
           num_filters,
           name=None,
           filter_size=5,
           stride=2,
           dilation=1,
           padding=2,
           output_size=None,
           act=None):
    if name is None:
        name = get_parent_function_name()
    return fluid.layers.conv2d_transpose(
        input=x,
        # param_attr=name + 'w',
        # bias_attr=name + 'b',
        num_filters=num_filters,
        output_size=output_size,
        filter_size=filter_size,
        stride=stride,
        dilation=dilation,
        padding=padding,
        use_cudnn=use_cudnn,
        act=act)


def conv_cond_concat(x, y):
    """Concatenate conditioning vector on feature map axis."""
    ones = fluid.layers.fill_constant_batch_size_like(
        x, [-1, y.shape[1], x.shape[2], x.shape[3]], "float32", 1.0)
    return fluid.layers.concat([x, ones * y], 1)


def D_cond(image, y):
    image = fluid.layers.reshape(x=image, shape=[-1, 1, 28, 28])
    yb = fluid.layers.reshape(y, [-1, y_dim, 1, 1])
    x = conv_cond_concat(image, yb)

    h0 = conv(x, c_dim + y_dim, act="leaky_relu")
    h0 = conv_cond_concat(h0, yb)
    h1 = bn(conv(h0, df_dim + y_dim), act="leaky_relu")
    h1 = fluid.layers.flatten(h1, axis=1)

    h1 = fluid.layers.concat([h1, y], 1)

    h2 = bn(fc(h1, dfc_dim), act='leaky_relu')
    h2 = fluid.layers.concat([h2, y], 1)

    h3 = fc(h2, 1, act='sigmoid')
    return h3


def G_cond(z, y):
    s_h, s_w = output_height, output_width
    s_h2, s_h4 = int(s_h // 2), int(s_h // 4)
    s_w2, s_w4 = int(s_w // 2), int(s_w // 4)

    yb = fluid.layers.reshape(y, [-1, y_dim, 1, 1])  #NCHW

    z = fluid.layers.concat([z, y], 1)
    h0 = bn(fc(z, gfc_dim // 2), act='relu')
    h0 = fluid.layers.concat([h0, y], 1)

    h1 = bn(fc(h0, gf_dim * 2 * s_h4 * s_w4), act='relu')
    h1 = fluid.layers.reshape(h1, [-1, gf_dim * 2, s_h4, s_w4])

    h1 = conv_cond_concat(h1, yb)
    h2 = bn(deconv(h1, gf_dim * 2, output_size=[s_h2, s_w2]), act='relu')
    h2 = conv_cond_concat(h2, yb)
    h3 = deconv(h2, 1, output_size=[s_h, s_w], act='tanh')
    return fluid.layers.reshape(h3, shape=[-1, s_h * s_w])

class D(fluid.dygraph.Layer):

    def __init__(self, name_scope):
        super(D,self).__init__(name_scope)

    def forward(self, x):
        x = conv(x, df_dim, act='leaky_relu')
        x = bn(conv(x, df_dim * 2), act='leaky_relu')
        x = bn(fc(x, dfc_dim), act='leaky_relu')
        x = fc(x, 1, act='sigmoid')
        return x

class G(fluid.dygraph.Layer):

    def __init__(self, name_scope):
        super(G,self).__init__(name_scope)

    def forward(self, x):
        x = bn(fc(x, gfc_dim))
        x = bn(fc(x, gf_dim * 2 * img_dim // 4 * img_dim // 4))
        x = fluid.layers.reshape(x, [-1, gf_dim * 2, img_dim // 4, img_dim // 4])
        x = deconv(x, gf_dim * 2, act='relu', output_size=[14, 14])
        x = deconv(x, 1, filter_size=5, padding=2, act='tanh', output_size=[28, 28])
        x = fluid.layers.reshape(x, shape=[-1, 1, 28, 28])
        return x`这是我应用的网络，作业其他部分没有改动，老师如果看不到我的项目可以自己替换上试一下，第二个GAN作业

**Comment by zb-tjw** [comment]
https://aistudio.baidu.com/aistudio/projectdetail/680144

**Comment by weiexcelpro** [comment]
感谢, 已经安排RD去看了.

**Comment by mozhuqing** [comment]
遇到同样问题，特别训练GAN的时候
