### ISSUE TITLE
AttributeError: module 'paddle.fluid' has no attribute 'dygraph_grad_clip'

### ISSUE THREAD

**Issue by howl-anderson** [PaddlePaddle/Paddle#25879]
版本、环境信息：
    1）PaddlePaddle版本：1.8.3
    2）CPU/GPU：CPU
    3）系统环境：Mac OS
    4）Python版本号: 3.6.6

**Comment by phlrain** [comment]
在1.8.3版本中，gradient clip操作进行了动态图和静态图的统一，接口统一导入了 paddle.fluid.clip.中

**Comment by howl-anderson** [comment]
Hi phlrain, 我能在哪里找到关于某一特定 API 的 changelog 、版本变动或者迁移指南么？

**Comment by phlrain** [comment]
https://github.com/PaddlePaddle/models/blob/release/1.8/dygraph/ptb_lm/ptb_dy.py#L335

这种改目录的api 相对来说非常少，clip可以先参考这个的使用

**Comment by howl-anderson** [comment]
@phlrain Thanks! It works now. 

对于其他被这个 issue 困扰的人的建议，有两处改动需要注意：

1. gradient clip 除了换了 module 的位置，还可能 class 的名字有少许变动（e.g. `GradClipByGlobalNorm` -> `GradientClipByGlobalNorm`)
2. 在 Optimizer 中的使用也不同，从 `opt.minimize(loss, grad_clip=g_clip)` 改成 `opt = Optimizer(grad_clip=g_clip)`

希望能对其他人有所帮助。

**Comment by georgeliu95** [comment]
> @phlrain Thanks! It works now.
> 
> 对于其他被这个 issue 困扰的人的建议，有两处改动需要注意：
> 
>     1. gradient clip 除了换了 module 的位置，还可能 class 的名字有少许变动（e.g. `GradClipByGlobalNorm` -> `GradientClipByGlobalNorm`)
> 
>     2. 在 Optimizer 中的使用也不同，从 `opt.minimize(loss, grad_clip=g_clip)` 改成 `opt = Optimizer(grad_clip=g_clip)`
> 
> 
> 希望能对其他人有所帮助。

In my case, it works when `opt.minimize(loss, grad_clip=g_clip)` replaced by `opt.minimize(loss)` instead of `opt = Optimizer(grad_clip=g_clip)`. Anyway, thank you for your suggestions.
