### ISSUE TITLE
【论文复现】训练代码执行器错误，车牌检测作业网络定义那里改成dnn,lenet,vgg,都试过了都不会报这个溢出的错，但是改成ResNet和AlexNet,就都报这个错，ball ball 大佬解决一下。

### ISSUE THREAD

**Issue by Ole168** [PaddlePaddle/Paddle#25876]
---------------------------------------------------------------------------EnforceNotMet                             Traceback (most recent call last)<ipython-input-10-a7c6b101c653> in <module>
     11             labels = np.array([x[1] for x in data]).astype('int64')
     12             labels = labels[:, np.newaxis]
---> 13             image=fluid.dygraph.to_variable(images)
     14             label=fluid.dygraph.to_variable(labels)
     15 
</opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/decorator.py:decorator-gen-153> in to_variable(value, name, zero_copy)
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/wrapped_decorator.py in __impl__(func, *args, **kwargs)
     23     def __impl__(func, *args, **kwargs):
     24         wrapped_func = decorator_func(func)
---> 25         return wrapped_func(*args, **kwargs)
     26 
     27     return __impl__
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/framework.py in __impl__(*args, **kwargs)
    214         assert in_dygraph_mode(
    215         ), "We Only support %s in imperative mode, please use fluid.dygraph.guard() as context to run it in imperative Mode" % func.__name__
--> 216         return func(*args, **kwargs)
    217 
    218     return __impl__
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/base.py in to_variable(value, name, zero_copy)
    565                 persistable=False,
    566                 zero_copy=zero_copy,
--> 567                 name=name if name else '')
    568             return py_var
    569     elif isinstance(value, (core.VarBase, framework.Variable,
EnforceNotMet: 

--------------------------------------------
C++ Call Stacks (More useful to developers):
--------------------------------------------
0   std::string paddle::platform::GetTraceBackString<char const*>(char const*&&, char const*, int)
1   paddle::platform::EnforceNotMet::EnforceNotMet(std::__exception_ptr::exception_ptr, char const*, int)
2   paddle::platform::GpuMemcpySync(void*, void const*, unsigned long, cudaMemcpyKind)

----------------------
Error Message Summary:
----------------------
ExternalError:  Cuda error(4), unspecified launch failure.
  [Advise: An exception occurred on the device while executing a kernel. Common causes include dereferencing an invalid device pointerand accessing out of bounds shared memory. The device cannot be used until cudaThreadExit() is called. All existing device memory allocations are invalid and must be reconstructed if the program is to continue usingCUDA.] at (/paddle/paddle/fluid/platform/gpu_info.cc:281)

**Comment by phlrain** [comment]
建议先降低batch size进行尝试，如果降低了 batch size，程序可以运行，基本可以认为是显存或者共享内存不足导致的问题

**Comment by Ole168** [comment]
> 建议先降低batch size进行尝试，如果降低了 batch size，程序可以运行，基本可以认为是显存或者共享内存不足导致的问题

batch_size改成8还是报同一个错误（枯了，我把项目链接贴出来，ball ball 大佬帮忙看一下哪里出问题了
https://aistudio.baidu.com/bdvgpu32g/user/205079/659998/notebooks/659998.ipynb

**Comment by saxon-zh** [comment]
batchsize从小到大尝试下，=2，=4
