### ISSUE TITLE
【论文复现】PaddlePaddle API文档中的接口：paddle.fluid.dygraph.guard(place=None) 的参数place的说明的修改建议

### ISSUE THREAD

**Issue by S-HuaBomb** [PaddlePaddle/Paddle#25880]
- 版本、环境信息
1）PaddlePaddle版本：1.8
- 问题定位：PaddlePaddle API文档中的接口：[paddle.fluid.dygraph.guard(place=None)](https://www.paddlepaddle.org.cn/documentation/docs/zh/api_cn/dygraph_cn/guard_cn.html)，其中 `place` 参数的说明如下图所示：没有说清楚 `fluid.CPUPlace` 需要传入参数指明GPU
![}FNU(6_ ZNCG{X9ZIQ~QUG](https://user-images.githubusercontent.com/39048551/89101986-9ff2ca00-d437-11ea-858b-0060632581e4.png) 但这个接口：[class paddle.fluid.executor.Executor(place=None)](https://www.paddlepaddle.org.cn/documentation/docs/zh/api_cn/executor_cn/Executor_cn.html)，其中`place` 参数的说明如下图所示： `fluid.CPUPlace(N)` 的表示会更清晰
![3%XDVP{L~({GUZM07P3G648](https://user-images.githubusercontent.com/39048551/89102007-bdc02f00-d437-11ea-9101-73fb95b96c0d.png)
- 建议描述：文档信息相同的地方希望可以描述一致且清晰。

**Comment by phlrain** [comment]
非常提供这样的建议，我们会排期进行优化
