### ISSUE TITLE
【论文复现】动态图模型如何加载静态图预训练模型

### ISSUE THREAD

**Issue by sunjie97** [PaddlePaddle/Paddle#25883]
在做视频分类时希望加载ImageNet预训练参数，但是现有预训练模型都是基于静态图的，如何能将静态图模型参数转为动态图可加载的形式?

**Comment by chenwhql** [comment]
这个功能目前还在完善中，预计会在2.0 beta版发布

相关接口文档及示例：https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api_cn/imperative_cn/jit_cn/load_cn.html

现在这个接口需要安装develop版本的paddle才能使用，如果您急用的话，可以考虑尝试安装下合适版本的develop的包：
https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/install/Tables.html#whl-dev

**Comment by chenwhql** [comment]
> 这个功能目前还在完善中，预计会在2.0 beta版发布
> 
> 相关接口文档及示例：https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api_cn/imperative_cn/jit_cn/load_cn.html
> 
> 现在这个接口需要安装develop版本的paddle才能使用，如果您急用的话，可以考虑尝试安装下合适版本的develop的包：
> https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/install/Tables.html#whl-dev

可能我问题理解有误，这套方案是为了处理不重写动态图code的情况下，复用静态图预训练模型的，如果您已经写了动态图的模型code，可以按照以下步骤将静态图参数载入动态图，这个方法在目前已发布的1.x版本即可使用：

1. 使用[load_program_state](https://www.paddlepaddle.org.cn/documentation/docs/zh/api_cn/io_cn/load_program_state_cn.html)载入静态图预训练参数，得到state_dict
2. 使用[set_dict](https://www.paddlepaddle.org.cn/documentation/docs/zh/api_cn/dygraph_cn/Layer_cn.html#set-dict-stat-dict-include-sublayers-true)方法将state_dict配置到动态图模型中，注意这里将参数use_structured_name设置为False（这个参数未在文档中公开）
```
def set_dict(self,
                 stat_dict,
                 include_sublayers=True,
                 use_structured_name=True):
```

**Comment by sunjie97** [comment]
好的，谢谢
