### ISSUE TITLE
【论文复现】运行官方API文档中的Conv2DTranspose的例子报错

### ISSUE THREAD

**Issue by Welsun** [PaddlePaddle/Paddle#25889]
在运行官方文档中关于Conv2DTranspose的样例代码报错。
样例代码如下：

with fluid.dygraph.guard():
    data = np.random.random((3, 32, 32, 5)).astype('float32')
    conv2DTranspose = fluid.dygraph.nn.Conv2DTranspose(
          'Conv2DTranspose', num_filters=2, filter_size=3)
    ret = conv2DTranspose(fluid.dygraph.base.to_variable(data))

**报错如下：**
![image](https://user-images.githubusercontent.com/30971076/89139719-30352a00-d572-11ea-85ee-ff49c7563d02.png)

![image](https://user-images.githubusercontent.com/30971076/89139691-1b589680-d572-11ea-9e18-6bbbde92305c.png)

**Comment by wzzju** [comment]
您好！如果您使用的是Paddle2.0-alpha版本，请参考对应文档：https://www.paddlepaddle.org.cn/documentation/docs/zh/2.0-alpha/api_cn/dygraph_cn/Conv2DTranspose_cn.html 。Conv2DTranspose在2.0-alpha版本和1.8版本的参数是不同的。
