### ISSUE TITLE
[建议]对于模型搭建部分

### ISSUE THREAD

**Issue by ykallan** [PaddlePaddle/Paddle#25881]
1）PaddlePaddle版本：1.8
2）CPU/GPU：无关
3）系统环境：win10

- 复现信息：无
- 建议描述：
在模型搭建的过程中，不知道paddle，能不能添加类似于torch.nn.Sequential/SequentialList/SequentialDict等功能，方便搭建模型，或者是类似于tf.keras中，提供的高阶api，直接定义一下模型，compile一下就可以run，这样我感觉对于新手来说会很友好，现在我看教程，paddle只有最底层的api可以用来搭建模型，进行训练，这样对于新手来说太不友好了（哭）

所以建议，可以的话，添加高阶api在框架中，方便实现简单的模型搭建

期待您的回复
联系方式： 815583442@qq.com

**Comment by phlrain** [comment]
paddle同样提供了类似Sequence，ModelList等功能，这些api目前在paddle.fluid.dygraph.nn下面
