### ISSUE TITLE
快速开始中yolov3_mobilenet_v1_fruit.yml训练出错

### ISSUE THREAD

**Issue by wangleilei001** [PaddlePaddle/Paddle#25895]
<img width="1438" alt="paddle11" src="https://user-images.githubusercontent.com/13131672/89144162-7c3a9b80-d57f-11ea-9cb3-5480bc6a5424.png">

快速开始中，训练出错，一共两处错误
命令python -u tools/train.py -c configs/yolov3_mobilenet_v1_fruit.yml --eval
issue3770貌似也不相关

**Comment by heavengate** [comment]
你的环境python不支持多进程，把`configs/yolov3_reader.yml`里`TrainReader`的`use_process`设置成False吧
https://github.com/PaddlePaddle/PaddleDetection/blob/34cc67c6f295be909a7a1ad8525cd51ee22ac2a7/configs/yolov3_reader.yml#L55
