### ISSUE TITLE
paddle支持稀疏矩阵格式

### ISSUE THREAD

**Issue by luolimingfighting** [PaddlePaddle/Paddle#25905]
paddle.fluid.layers.data(name, shape, append_batch_size=True, dtype='float32', lod_level=0, type=VarType.SELECTED_ROWS, stop_gradient=True) 用这种方式读取稀疏矩阵时，请问下input的稀疏矩阵格式是怎样的？

**Comment by luolimingfighting** [comment]
比如：
1. [index1 float1, index2 float2, ...]

**Comment by luolimingfighting** [comment]
比如：
1. [index1 float1, index2 float2, ...] 索引加float值，中间空格或者 \t 分隔？
2. numpy 的 csr格式？
等等。。最好能贴个Demo

**Comment by phlrain** [comment]
目前paddle还不支持 feed的时候 支持selected rows的结构

**Comment by luolimingfighting** [comment]
> 目前paddle还不支持 feed的时候 支持selected rows的结构

那title那种方式暂时没有实际用处吗？或者我只能将稀疏矩阵转化为dense才能feed给paddle吗

**Comment by phlrain** [comment]
>或者我只能将稀疏矩阵转化为dense才能feed给paddle吗

是的

> 那title那种方式暂时没有实际用处吗？
这个title的方式具体是指？
