### ISSUE TITLE
Input features and labels

### ISSUE THREAD

**Issue by saviord7** [PaddlePaddle/Paddle#25914]
Hello.
I got a little confused about defining features and labels in input dataset.

For example, I have dataset 100x15. 15 = 14 features + 1 label
How I can say in my code ?

I load my file like this: `data = np.genfromtxt('FILE.csv', delimiter=',') `
What next?

I saw many examples like: 
```
x = fluid.data(name='x', shape=[None, 13], dtype='float32') 
y = fluid.data(name='y', shape=[None, 1], dtype='float32') 
y_predict = fluid.layers.fc(input=x, size=1, act=None) 
```

Okay, I understand that x = features, y = label.

But how I can define this with my dataset?
So, I have loaded `data`. How do I distribute it in X and Y ?

**Comment by wzzju** [comment]
You should create your own data reader according to your business scenario. Please refer to  https://www.paddlepaddle.org.cn/documentation/docs/zh/advanced_guide/data_preparing/static_mode/reader_cn.html and https://www.paddlepaddle.org.cn/documentation/docs/zh/advanced_guide/data_preparing/static_mode/use_py_reader.html#user-guides-use-py-reader .
