### ISSUE TITLE
使用lac模型部署到centos7.6，执行预测时报错

### ISSUE THREAD

**Issue by zhuyingjun-zyj** [PaddlePaddle/Paddle#25913]
W0802 03:33:31.086237 12470 init.cc:216] Warning: PaddlePaddle catches a failure signal, it may not work properly
W0802 03:33:31.086323 12470 init.cc:218] You could check whether you killed PaddlePaddle thread/process accidentally or report the case to PaddlePaddle
W0802 03:33:31.086359 12470 init.cc:221] The detail failure signal is:

W0802 03:33:31.086382 12470 init.cc:224] *** Aborted at 1596310411 (unix time) try "date -d @1596310411" if you are using GNU date ***
W0802 03:33:31.089992 12470 init.cc:224] PC: @                0x0 (unknown)
W0802 03:33:31.090488 12470 init.cc:224] *** SIGSEGV (@0x7f24f6206900) received by PID 12425 (TID 0x7f2464ece700) from PID 18446744073543903488; stack trace: ***
W0802 03:33:31.093632 12470 init.cc:224]     @     0x7f24f5de25d0 (unknown)
W0802 03:33:31.096148 12470 init.cc:224]     @     0x7f24e7e02810 (unknown)
W0802 03:33:31.098834 12470 init.cc:224]     @     0x7f24e7a257b2 (unknown)
W0802 03:33:31.101557 12470 init.cc:224]     @     0x7f24e7a2b7a2 (unknown)
W0802 03:33:31.104245 12470 init.cc:224]     @     0x7f24e7ff8d92 (unknown)
W0802 03:33:31.106792 12470 init.cc:224]     @     0x7f24e7e43832 (unknown)
W0802 03:33:31.109863 12470 init.cc:224]     @     0x7f24f5ddadd5 start_thread
W0802 03:33:31.113646 12470 init.cc:224]     @     0x7f24f53faead __clone
W0802 03:33:31.116614 12470 init.cc:224]     @                0x0 (unknown)

**Comment by wzzju** [comment]
您好，这个报错信息不能提供任何指导方向。请附录代码，机器环境，paddle版本等更详细内容。

**Comment by Shixiaowei02** [comment]
W0802 03:33:31.089992 12470 init.cc:224] PC: @ 0x0 (unknown)
您好，看起来报错可能是空指针导致的，请提供更详细的日志代码以便问题追查，谢谢
