### ISSUE TITLE
【论文复现】自定义Layer

### ISSUE THREAD

**Issue by sunjie97** [PaddlePaddle/Paddle#25923]
如何自定义Layer，实现前向传播和反向传播，我看到fluid.dygraph.layers.Layer的关于反向传播的定义[this line](https://github.com/PaddlePaddle/Paddle/blob/release/1.8/python/paddle/fluid/dygraph/layers.py#L481)，写着不应该自定义backward()函数。那么由类似需求的时候应该如何操作?

**Comment by wzzju** [comment]
请参考[如何写新的C++ OP](https://www.paddlepaddle.org.cn/documentation/docs/zh/advanced_guide/addon_development/new_op/new_op.html)和[如何写新的Python OP
](https://www.paddlepaddle.org.cn/documentation/docs/zh/advanced_guide/addon_development/new_op/new_python_op.html)添加新Op。可参考Linear层的定义：https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/fluid/dygraph/nn.py#L888

**Comment by sunjie97** [comment]
好的，谢谢
