### ISSUE TITLE
【论文复现】如何改变卷积层的weight

### ISSUE THREAD

**Issue by sunjie97** [PaddlePaddle/Paddle#25922]
我想要改变一个Conv2D对象的weight, 但其weight的类型为Parameter，我不知道如何创建一个Parameter实例，查阅了官方文档也没有找到方法，请问如何能够创建一个Parameter对象，有没有将Variable转换成Parameter的方法
报错信息大致如下：
```python
TypeError: assignment to parameter 'weight' should be of type Parameter or None, but got 'Variable'
```

**Comment by saxon-zh** [comment]
可以通过调用 [Layer](https://www.paddlepaddle.org.cn/documentation/docs/zh/api_cn/dygraph_cn/Layer_cn.html#layer) 的 [create_parameter](https://www.paddlepaddle.org.cn/documentation/docs/zh/api_cn/dygraph_cn/Layer_cn.html#create_parameter) 接口来完成。

**Comment by saxon-zh** [comment]
具体的操作例子可以参见：[命令式编程使用教程](https://www.paddlepaddle.org.cn/documentation/docs/zh/beginners_guide/basic_concept/dygraph/DyGraph.html#id6)

**Comment by sunjie97** [comment]
```python
# 这里我想要对conv层的参数进行修改，所以在这里先取出来
params = [x for x in conv_layer.parameters()]
expand_times = [1, 2 * self.new_length, 1, 1]
# 对参数进行修改后，其类型变为Variable
new_kernels = fluid.layers.expand(fluid.layers.reduce_mean(params[0], 1, keep_dim=True), expand_times=expand_times)

# 创建新的conv层
new_conv = Conv2D(2 * self.new_length, conv_layer._num_filters, filter_size=conv_layer._filter_size, stride=conv_layer._stride, 
            padding=conv_layer._padding, bias_attr=conv_layer._bias_attr)

# 这里想要用修改后的参数覆盖新创建的conv层，但是会报参数类型的错误
new_conv.weight = new_kernels  
```
我看到Layer的create_parameter接口只能够创建一个新的变量并重新初始化，好像没有办法做到这一点。
有什么办法能够修改conv层的weight参数来达到以上的目的吗？或者将Variable转换成Parameter也可以

**Comment by wzzju** [comment]
可以尝试使用[state_dict](https://www.paddlepaddle.org.cn/documentation/docs/zh/api_cn/dygraph_cn/Layer_cn.html#state-dict-destination-none-include-sublayers-true)以及[set_dict](https://www.paddlepaddle.org.cn/documentation/docs/zh/api_cn/dygraph_cn/Layer_cn.html#set-dict-stat-dict-include-sublayers-true)解决，参考示例https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/fluid/contrib/slim/tests/test_imperative_qat.py#L309。

**Comment by jerrywgz** [comment]
看你的使用方式是一个卷积权重依赖另一个卷积，这样的话最好的方式应该使用https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/nn/functional/conv.py#L90 这里的conv2d，weight可以作为参数传入api，这个api是latest的paddle版本才会有。如果使用paddle release/1.8版本的话可能要尝试下state_dict和set_dict

**Comment by sunjie97** [comment]
好的，我尝试下

**Comment by jonny4929** [comment]
`import paddle.fluid as fluid
import numpy
with fluid.dygraph.guard():
    f=fluid.dygraph.Conv2D(3,16,3,1,1,param_attr='cov')
    print(f.weight)
    f.weight.set_value(numpy.ones((16,3,3,3),dtype=numpy.float32))
    print(f.weight)`
用set_value()是可行的
