### ISSUE TITLE
AIStudio，参数正常，梯度dim[0]

### ISSUE THREAD

**Issue by hlzonWang** [PaddlePaddle/Paddle#25929]
----------------------
Error Message Summary:
----------------------
InvalidArgumentError: Param and Grad input of AdamOp should have same dimension. But received Param dims: [49805], Grad dims: [0].
  [Hint: Expected param_dims == ctx->GetInputDim("Grad"), but received param_dims:49805 != ctx->GetInputDim("Grad"):0.] at (/paddle/paddle/fluid/operators/optimizers/adam_op.cc:93)
  [operator < adam > error]

**Comment by jerrywgz** [comment]
从报错信息来看是网络参数和对应梯度的纬度不相同导致的，可以先确认下是否加载了预训练权重，而权重中存在不符合预期的shape

**Comment by hlzonWang** [comment]
> 从报错信息来看是网络参数和对应梯度的纬度不相同导致的，可以先确认下是否加载了预训练权重，而权重中存在不符合预期的shape

grad的维度是0……也就是说压根没有梯度，我觉得是添加反向计算卡在哪了，但别的框架上都是可用的，而且是没办法检查，layers.Print压根没结果……

**Comment by hlzonWang** [comment]
问题解决了，是paddlepaddle自动剪枝的锅，关闭后一切正常
