### ISSUE TITLE
 Paddle是否支持类似numpy的x[y > 0.1] = 1操作

### ISSUE THREAD

**Issue by jakeju92** [PaddlePaddle/Paddle#25921]
- 版本、环境信息：
   1）PaddlePaddle版本：1.8
   2）CPU/GPU：CUDA 10.1 和cuDNN 7.6.5
   3）系统环境：Ubuntu 16.04 LTS
   4）Python版本号：3.7.0
   5）显存信息: 8GB

- 问题描述：如题, paddle目前不支持类似如下numpy的操作:
1. 输入为x和y的numpy array，x.shape和y.shape相同
2. y > 0.1的输出为bool mask，这一步paddle是支持的。
3. 但是x[boolean_mask] = 1，这步操作paddle是不支持的，能否给一个workaround，谢谢！

**Comment by wzzju** [comment]
可以尝试使用https://www.paddlepaddle.org.cn/documentation/docs/zh/api_cn/layers_cn/where_cn.html#where 和 https://www.paddlepaddle.org.cn/documentation/docs/zh/api_cn/layers_cn/scatter_nd_cn.html#scatter-nd 解决一下。

**Comment by jerrywgz** [comment]
mask = x > 0.1
y = x * (1 - mask) + mask 
这样就可以实现了

**Comment by jakeju92** [comment]
可以用的，谢谢！
