### ISSUE TITLE
在paddle API fluid.initializer 板块，神经网络权值初始化缺少kaiming initialization的初始化方式

### ISSUE THREAD

**Issue by Ciel04sk** [PaddlePaddle/Paddle#25930]
欢迎您对PaddlePaddle提出建议，非常感谢您对PaddlePaddle的贡献！
在留下您的建议时，辛苦您同步提供如下信息：
- 版本、环境信息
1）PaddlePaddle版本：请提供您的PaddlePaddle版本号，例如1.1
2）CPU/GPU：您是否使用GPU进行训练，如是，请提供您的CUDA和cuDNN版本号
3）系统环境：请您描述系统类型、版本，例如Mac OS 10.14
注：您可以通过执行[summary_env.py](https://github.com/PaddlePaddle/Paddle/blob/develop/tools/summary_env.py)获取以上信息。
- 复现信息：如为报错，请给出复现环境、复现步骤
- 建议描述：请您详细描述，您认为需优化的功能

Thank you for contributing to PaddlePaddle.
Before submitting the issue, you could search issue in the github in case that there was a similar issue submitted or resolved before.
Please make sure that this is a feature request. 
**System information**
-PaddlePaddle version （eg.1.1）or CommitID
-CPU: including CPUMKL/OpenBlas/MKLDNN version
-GPU: including CUDA/CUDNN version
-OS Platform (eg.Mac OS 10.14)
Note: You can get most of the information by running [summary_env.py](https://github.com/PaddlePaddle/Paddle/blob/develop/tools/summary_env.py). 
**To Reproduce**
Steps to reproduce the behavior
**Describe the feature and the current behavior/state.**
**Any Other info.**

**Comment by jerrywgz** [comment]
感谢反馈，kaiming初始化在pytorch中的实现方式如下：https://pytorch.org/docs/stable/nn.init.html#torch.nn.init.kaiming_uniform_
paddle中可以通过https://www.paddlepaddle.org.cn/documentation/docs/zh/api_cn/initializer_cn/XavierInitializer_cn.html#cn-api-fluid-initializer-xavierinitializer xaiver初始化+手动指定fan_in 或fan_out实现等价的初始化方式

**Comment by jakeju92** [comment]
Hi，
可以参考一下下面的代码：

```
def conv_bn(input, out_channels, bn=True, bn_momentum=0.95, act='relu', name=None):
    def _get_kaiming_init():
        fan_in = input.shape[1]
        std = (1.0 / fan_in / 3.0) ** 0.5
        return fluid.initializer.Normal(0., std, 0.)

    param_attr = ParamAttr(name='{}_conv_weight'.format(name),
                           initializer=_get_kaiming_init())
    bias_attr = ParamAttr(name='{}_conv_bias'.format(name)) \
                                  if not bn else False
    out = layers.conv2d(input,
                          num_filters=out_channels,
                          filter_size=1,
                          stride=1,
                          padding=0,
                          dilation=1,
                          param_attr=param_attr,
                          bias_attr=bias_attr,
                          act=act if not bn else None)
    if bn:
        bn_name = name + "_bn"
        out = layers.batch_norm(out,
                                  act=act,
                                  momentum=bn_momentum,
                                  param_attr=ParamAttr(name=bn_name + "_scale", ),
                                  bias_attr=ParamAttr(name=bn_name + "_offset"),
                                  moving_mean_name=bn_name + '_mean',
                                  moving_variance_name=bn_name + '_var')

    return out
```
