### ISSUE TITLE
如何实现多embedding按权融合

### ISSUE THREAD

**Issue by lps683** [PaddlePaddle/Paddle#25940]
使用paddle对特征目前最常用的两种处理方式为
1)word_emb，即fluid.layers.embedding，我理解这种特征比较适合单特征
2)text_cnn，即先fluid.layers.embedding后进行fluid.nets.sequence_conv_pool，目前字符串、多值特征多用该种处理方式

目前有这么一类多值特征，每个值有不同的权重，对这样的特征如何设计embedding更合理？是否有按权融合多值特征embedding的方法呢？谢谢

**Comment by kuke** [comment]
可以为每个值学习一个 embeddding 表？然后加权求和即可

类似于 BERT 的 word/position/sentence embedding，只是这里的权重为 1

https://github.com/PaddlePaddle/models/blob/eb7eb9cd5f2bffe5edd8b7d6a35b46f38a6db498/PaddleNLP/pretrain_language_models/BERT/model/bert.py#L106

**Comment by lps683** [comment]
类似这样 是否可以 paddle本地跑没问题
求和融合以及concat融合方式
![image](https://user-images.githubusercontent.com/17926197/90609152-3267db80-e236-11ea-96cd-34986f6ae3e1.png)
