### ISSUE TITLE
【论文复现】复现TSN网络时，训练和测试均出现“TypeError: not all arguments converted during string formatting”问题.

### ISSUE THREAD

**Issue by Momofilm** [PaddlePaddle/Paddle#25953]
- 版本、环境信息：
    AIstudio环境（GPU）
1）PaddlePaddle版本：PaddlePaddle 1.8.0
2）Python：python3.7
3）GPU：v100
- 复现信息：复现TSN视频分类网络（https://aistudio.baidu.com/aistudio/projectdetail/675993）
- 问题描述：‘!python train.py --use_gpu True --epoch 1’运行训练网络时会出现，以下错误：
Traceback (most recent call last):
  File "train.py", line 127, in <module>
    train(args)
  File "train.py", line 75, in train
    train_model = TSN1.TSNResNet('TSN', train_config['MODEL']['num_layers'],train_config['MODEL']['num_classes'],train_config['MODEL']['seg_num'], 0.00002)
  File "/home/aistudio/model/TSN1.py", line 129, in __init__
    act='relu')
  File "/home/aistudio/model/TSN1.py", line 33, in __init__
    bias_attr=False)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/nn.py", line 201, in __init__
    if self._num_channels % self._groups != 0:
TypeError: not all arguments converted during string formatting
希望得到问题回复！困扰我两天了，无法解决。

**Comment by frankwhzhang** [comment]
这个应该属于python的使用问题，是参数没有对应正确，可以网上查一下这个报错

**Comment by Momofilm** [comment]
@frankwhzhang 请问是TSN1.TSNResNet(）传入参数的问题吗？

**Comment by frankwhzhang** [comment]
可以看一下报错的Line 对应的函数，这个问题是python端的问题 可以参考网上的回答 https://blog.csdn.net/lvsehaiyang1993/article/details/80909984
