### ISSUE TITLE
【论文复现】模型参数和输出数据值

### ISSUE THREAD

**Issue by kgkzhiwen** [PaddlePaddle/Paddle#25991]
【论文复现】
请问要这样才能提取到模型中每一层的现有参数值和数据经过这一层后生成的输出值？

**Comment by frankwhzhang** [comment]
是图片挂了吗 没有看到你说的情况

**Comment by kgkzhiwen** [comment]
没有图片。
我只是想检验当下的参数数值， 以及数据的变化。

**Comment by frankwhzhang** [comment]
可以通过fluid.layers.Print这个接口 https://www.paddlepaddle.org.cn/documentation/docs/zh/api_cn/layers_cn/Print_cn.html#print
