### ISSUE TITLE
【论文复现】lod-Tensor 的加权平均值

### ISSUE THREAD

**Issue by kgkzhiwen** [PaddlePaddle/Paddle#25992]
对于两个或两个以上形态相同的lod-Tensor，要如何获得它们的加权平均值，比如：
0.2 * lodTensor1 + 0.3 * lodTensor2 + 0.5 * lodTensor3

**Comment by frankwhzhang** [comment]
直接按照公式就可以

**Comment by kgkzhiwen** [comment]
所以要取它们的平均值， 可以直接用：
(lodTensor1+lodTensor2+lodTensor3)/3 吗？

**Comment by frankwhzhang** [comment]
可以 也可以用elementwise_add 等一系列操作 https://www.paddlepaddle.org.cn/documentation/docs/zh/api_cn/layers_cn/elementwise_add_cn.html#elementwise-add

**Comment by kgkzhiwen** [comment]
谢谢！
