### ISSUE TITLE
在训练过程中不断吃显存，直到显存不足

### ISSUE THREAD

**Issue by yeyupiaoling** [PaddlePaddle/Paddle#25996]
- 项目：[DeepSpeech](https://github.com/PaddlePaddle/DeepSpeech) [issue](https://github.com/PaddlePaddle/DeepSpeech/issues/482)
 - PaddlePaddle 1.8 
 - CUDA 10
 - Docker
 - 显卡：2080ti 11G

```
export FLAGS_sync_nccl_allreduce=0
export FLAGS_eager_delete_tensor_gb=0
export FLAGS_fraction_of_gpu_memory_to_use=0.98
CUDA_VISIBLE_DEVICES=0,1 python train.py
```

我使用的是docker进行训练，显存为11G，一开始训练只占8G左右，但在训练过程中会出现不断吃显存，直到显存不足挂掉。设置小batch_size也没有用的。

请问这个问题如何解决？

**Comment by Xreki** [comment]
去掉`export FLAGS_eager_delete_tensor_gb=0 export FLAGS_fraction_of_gpu_memory_to_use=0.98`这两个环境变量，使用默认的auto_growth显存分配策略试下呢？

**Comment by yeyupiaoling** [comment]
@Xreki 这三个去掉我都试过了，还是不行。
```
export FLAGS_sync_nccl_allreduce=0
export FLAGS_eager_delete_tensor_gb=0
export FLAGS_fraction_of_gpu_memory_to_use=0.98
```

**Comment by yeyupiaoling** [comment]
@Xreki [DeepSpeech](https://github.com/PaddlePaddle/DeepSpeech) 这个这个模型好像也没用到什么特别的模型吧，就是CNN，RNN（GRU），怎会这样呢？

**Comment by yeyupiaoling** [comment]
本来batch为16可以训练的，但是稍微用大一点的数据集还是会出现显存不足，这是什么道理。batch size再小，loss就是nan了

**Comment by yeyupiaoling** [comment]
应该是音频长度的问题
