### ISSUE TITLE
模型在GPU上inference出错

### ISSUE THREAD

**Issue by renyu310** [PaddlePaddle/Paddle#26009]
paddle版本：1.7.2
GPU： 型号V100， cuda9, cudnn7.0
系统：CentOS release 6.3 
Python 2.7.13

问题描述：
代码：
![image](https://user-images.githubusercontent.com/12406172/89511067-fd09c980-d803-11ea-8825-1884c7ea6880.png)

该代码在CPU模式时预估正常，将gpu打开后出现如下错误， 机器环境上的GPU训练没有异常：
![image](https://user-images.githubusercontent.com/12406172/89509990-9506b380-d802-11ea-97b3-59f5a46fe467.png)

**Comment by Xreki** [comment]
Hi上已回答，Paddle是用cudnn7.6编译的，运行机器上使用的是cudnn7.0，预测是在conv2d_fusion op中报`CUDNN_STATUS_BAD_PARAM`错误，很可能是因为cudnn版本太低，可以先升级下版本看看。

**Comment by renyu310** [comment]
> Hi上已回答，Paddle是用cudnn7.6编译的，运行机器上使用的是cudnn7.0，预测是在conv2d_fusion op中报`CUDNN_STATUS_BAD_PARAM`错误，很可能是因为cudnn版本太低，可以先升级下版本看看。

确实是cudnn版本问题，换成7.6解决了
