### ISSUE TITLE
“混合精度最佳实践”是否还可用？

### ISSUE THREAD

**Issue by Grant-Tao** [PaddlePaddle/Paddle#26014]
这是链接：https://paddlepaddle.org.cn/documentation/docs/zh/advanced_guide/performance_improving/amp/amp.html
但运行出错，在API reference也找不到fluid.contrib.mixed_precision这个模块。错误如下：
```
  optimizer.minimize(loss)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/contrib/mixed_precision/decorator.py", line 211, in minimize
    no_grad_set=no_grad_set)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/contrib/mixed_precision/decorator.py", line 141, in backward
    update_role_var_grad(self._train_program, self._params_grads)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/contrib/mixed_precision/fp16_utils.py", line 294, in update_role_var_grad
    op = g.op
AttributeError: 'paddle.fluid.core_avx.VarBase' object has no attribute 'op'
```

    1） PaddlePaddle版本：1.8
    2）CPU， GPU， 系统环境：aistudio

**Comment by Xreki** [comment]
这是最新的文档，但是是静态图的。从你的log来看，似乎你是想在动态图中使用混合精度训练？

**Comment by Grant-Tao** [comment]
Yes，动态图中不能用？ 另外inference能否用半精度？ 如何用？

**Comment by Grant-Tao** [comment]
@Xreki 我用例子CIFAR10 resnet36  resnet52跑了一下，用mixed_precision比不用慢了不少，mnist例子也一样。能解释一下吗？

**Comment by Xreki** [comment]
> 动态图中不能用？ 

动态图的混合精度训练功能还在开发中。

> 我用例子CIFAR10 resnet36 resnet52跑了一下，用mixed_precision比不用慢了不少，mnist例子也一样。能解释一下吗？

book里面的代码吗？有没有具体的性能数据？

**Comment by Grant-Tao** [comment]
@Xreki  代码在此： https://github.com/PaddlePaddle/book/tree/develop/03.image_classification 
              改动如下：
1. def optimizer_program():
    //return fluid.optimizer.Adam(learning_rate=0.001)
    Adam = fluid.optimizer.Adam(learning_rate=1e-3)
    mp_sgd = fluid.contrib.mixed_precision.decorator.decorate(Adam)
    return mp_sgd

2.  change to nhwc:
def resnet_cifar10(ipt, depth=32):
    perm = [0,2,3,1]
    fluid.layers.transpose(ipt, perm)

3. tell conv2d data format: 
        act=None, data_format='NHWC', 
        bias_attr=bias_attr)
    return fluid.layers.batch_norm(input=tmp, act=act, data_layout='NHWC')

Performance: (Resnet56): 4 epochs
Original:  61 seconds
Mixed_precision: 86 seconds

**Comment by Grant-Tao** [comment]
@Xreki  原因可能是cudnn版本不够。目前aistudio的cudnn版本是7.3，AMP要求版本至少7.4.1.

**Comment by Xreki** [comment]
@Grant-Tao 使用高版本cudnn确实会有一些优化，请问你升级了cudnn版本之后，训练速度有明显的提升吗？

**Comment by Grant-Tao** [comment]
@Xreki 可惜你们AISTUDIO的部门升级一个月也没完成升级。 可否请教个问题：
paddle tensor 的shape也是一个tensor，paddle有获得tensor shape的函数layers.shape, 也有获得tensor shape的list 的函数 tensor.shape(), 但如何把一个表示shape的list变成一个表示shape的tensor，没有相关函数，tensorflow 有个TensorShape（），请问 paddle如何实现？

**Comment by Xreki** [comment]
> 如何把一个表示shape的list变成一个表示shape的tensor

可以使用[assign](https://www.paddlepaddle.org.cn/documentation/docs/zh/api_cn/layers_cn/assign_cn.html#assign)，assign的input参数可以是一个numpy数组，使用示例：

```python
shape_tensor = fluid.layers.assign(np.array(shape_list), dtype='int64'))
```
