### ISSUE TITLE
Switching RPC library in new pserver implement

### ISSUE THREAD

**Issue by typhoonzero** [PaddlePaddle/Paddle#2602]
Related issue: https://github.com/PaddlePaddle/Paddle/issues/1721

We are using `net/rpc` in our implementation currently. In fact, I found that when we writing a client for trainers to call from, we have to implement the c binding first, and then compile it to a shared object(so), and then use swig to export that library, and then using ctypes to import so lib from python. The procedure can be displayed below:

![go pserver](https://user-images.githubusercontent.com/13348433/27529435-0cf5b2a8-5a87-11e7-8d6f-909b9404f501.png)

As we can see, we need to implement so many things. The root cause is that `net/rpc` in go don't have c or python bindings, we have to convert go-written clients to c and then to python.

I would like to introduce a more simple and efficient way using `grpc` instead of `net/rpc` as below:

![go pserver2](https://user-images.githubusercontent.com/13348433/27528279-4b24fae8-5a82-11e7-8b93-35afc9117525.png)

If we all switch to grpc and using python binding to implement the pserver client and master client, it will be much more simpler.

---

Some etcd3 python client bindings:
- https://python-etcd3.readthedocs.io/en/latest/ (https://github.com/kragniz/python-etcd3)

**Comment by jacquesqiao** [comment]
The current master client does not use SWIG but directly import .so build with cgo.

**Comment by jacquesqiao** [comment]
有两条调用路径，一个是swig，这个目前其实绕不开，因为是trainer(cpp) <---> pserver(go) ，第二条路目前是cgo实现的.so，目前master -- client实际上就是做了一些rpc调用，所以如果直接由好用的python binding，client端就不需要写go了，想起来确实不错

**Comment by typhoonzero** [comment]
trainer(cpp) <---> pserver(go) 这条路径也可以简化，由于grpc是有c++ binding的，所以可以直接用c++来调go的pserver接口，而不是先用cgo实现一个c的client，然后再调用。

**Comment by jacquesqiao** [comment]
相当于换一个有多重语言binding的rpc框架，这样各个组件用自己的语言实现就行了，还可以随意切换实现的语言，赞

**Comment by dzhwinter** [comment]
Just follow the related issue link, I found that here is the very close idea [rpc issue](https://github.com/PaddlePaddle/Paddle/issues/647#issuecomment-263489363)
which can be summarized as three points.

1.  go language set up service
2. use gRPC as rpc framework
3. use [flatbuffers](https://github.com/google/flatbuffers) as wire-format.

**Comment by helinwang** [comment]
Thanks for the great suggestion! It very good point that we have a complicated code path due mixing C, C++, Python, Go together, we need to write glue code for language bindings. I would love to have our code reduced (fewer human written code fewer error).

This is a great idea! By using grpc which automatically generates language bindings, we can remove the glue code for RPC written by human, replacing it with grpc's native Python code (as illustrated in the second graph from your comment).

In essence, Go in the client lib is removed, Python calls Go in the remote server directly with grpc.

However, we need to consider this problem: The Go code in the client is not only `net/rpc` code, it also includes important logic. Which can not be replaced by the Python grpc client.

If we take a look at the master client code [here](https://github.com/PaddlePaddle/Paddle/blob/develop/go/master/client.go#L36) it calls `net/rpc`, get the RecordIO Index of the training data, use Go RecordIO to read the training data according to the Index.

If we take a look at the pserver client code [here](https://github.com/PaddlePaddle/Paddle/blob/develop/go/pserver/client.go#L238) and [here](https://github.com/PaddlePaddle/Paddle/blob/develop/go/pserver/client.go#L103), it has the logic to partition parameters into different pservers, and the logic to ask etcd if the current trainer will be the one trainer to init all parameters on pservers.

From the two paragraphs above, we can see that there are big chunk of application logic in Go on then client, which grpc can not replace. So if we want to remove Go part in the client, we will need to write these logic again in Python.

I am not totally convinced to do these logic in Python for the following reasons:
- Python is not statically typed, if anything goes wrong, it very hard to debug. This hurts development speed and maintainability.
- If we want to support other language bindings other than Python, and we write these logic in Python, we need to port them to C or Go again.

**Comment by jacquesqiao** [comment]
> If we take a look at the master client code here it calls net/rpc, gets the RecordIO Index of the training data, uses Go RecordIO to read the training data according to the Index.

If we take a look at the pserver client code here and here, it has the logic to partition parameters into different pservers, and the logic to ask etcd if the current trainer will be the one trainer to init all parameters on pservers.

**Comment by typhoonzero** [comment]
@jacquesqiao  if implement pserver and master client in c++, there's no good choice for etcd client, so we have to call the etcd `gRPC` APIs directly(https://github.com/coreos/etcd/blob/master/Documentation/dev-guide/api_reference_v3.md).
This will make client library more complex and requires more code. 

For pserver client, if using gRPC, it should be implemented using c++ so that the `NewRemoteParameterUpdater` will call it directly, because lack of etcd c++ binding, this work seem will not bring much benifit.

For master client, we can implement using python(recordio have python binding), so it will be simpler, but the client is so small that it will bring not buch benifit at all.

So after some thinking, I would prefer to continue using the current way.
