### ISSUE TITLE
请问 对于设定的不同参数空间，怎么能取出这些变量呢，有没有函数可以用，类似tf.get_collection这样的功能

### ISSUE THREAD

**Issue by JixuH** [PaddlePaddle/Paddle#26022]
我试了试find_var，直接调也是错的 有点懵了，请问有什么好的方法可以取出这些变量呢

![image](https://user-images.githubusercontent.com/48123846/89535204-ac589780-d828-11ea-9c00-8569cb9b6f42.png)

![image](https://user-images.githubusercontent.com/48123846/89535417-00fc1280-d829-11ea-928a-292f17fad92c.png)

![image](https://user-images.githubusercontent.com/48123846/89535446-08232080-d829-11ea-89e9-1a408524840e.png)

**Comment by Xreki** [comment]
您好，`name_scope`设定的只是变量名的前缀，`find_var`接口需要传入变量完整的名字。如果你能拿到该变量，可用var.name获得该变量的name。如果不能拿到该变量，可以使用Program的`list_vars()`（[文档](https://www.paddlepaddle.org.cn/documentation/docs/zh/api_cn/fluid_cn/Program_cn.html#list-vars)）拿到Program里面所有的var，从里面筛选name_scope设置的前缀的变量。
