### ISSUE TITLE
【论文复现】BatchNorm3d的支持

### ISSUE THREAD

**Issue by sunjie97** [PaddlePaddle/Paddle#26049]
我查看了paddle的文档，好像没有提供对BatchNorm3d的支持。目前复现视频分类论文需要用到BatchNorm3d，需要自己实现吗？

**Comment by saxon-zh** [comment]
可以用下这个接口，[paddle.fluid.dygraph.BatchNorm](https://www.paddlepaddle.org.cn/documentation/docs/zh/api_cn/dygraph_cn/BatchNorm_cn.html#batchnorm)

**Comment by sunjie97** [comment]
我看到文档里BatchNorm的`data_layout`参数指定数据格式为“NCHW”或者“NHWC”，而普通BatchNorm3d的输入tensor维度为5(N,C,D,H,W)，如果在paddle里使用是要先reshape后才能处理吗？

**Comment by saxon-zh** [comment]
不用reshape，data_layout之间传NCHW就可以

**Comment by sunjie97** [comment]
直接传5维的tensor，按照 `NCDHW` 的顺序就可以是吗?

**Comment by sunjie97** [comment]
尝试过确实直接传就可以，感谢解答
