### ISSUE TITLE
能搞一下各种经典数据集加载的API吗？还有数据集的增强的API

### ISSUE THREAD

**Issue by mozhuqing** [PaddlePaddle/Paddle#26047]
能搞一下各种经典数据集加载的API吗？还有数据集的增强的API

**Comment by dingjiaweiww** [comment]
请问您指的是哪个数据集加载的API 呢？2.0rc1 版本我们所有内置数据集都有相应的API，目录在paddle.vision.datasets 下面，您可以在官网文档中查询到：https://www.paddlepaddle.org.cn/documentation/docs/zh/2.0-rc1/api/paddle/vision/datasets/cifar/Cifar10_cn.html。数据集增强API 在paddle.vision.transforms 下面，https://www.paddlepaddle.org.cn/documentation/docs/zh/2.0-rc1/api/paddle/vision/transforms/functional/adjust_brightness_cn.html
