### ISSUE TITLE
论文复现  自定义卷积核(不参与学习，只参与计算)

### ISSUE THREAD

**Issue by yuctian** [PaddlePaddle/Paddle#26056]
如何实现自定义卷积核参与卷积运算，不进行梯度更新

**Comment by heavengate** [comment]
Conv2D里有个`param_attr`参数用于指定卷积权重的属性，其中有个`trainable`属性是指定其是否会训练
https://www.paddlepaddle.org.cn/documentation/docs/zh/api_cn/dygraph_cn/Conv2D_cn.html#conv2d
https://www.paddlepaddle.org.cn/documentation/docs/zh/api_cn/fluid_cn/ParamAttr_cn.html#paramattr

**Comment by yuctian** [comment]
> Conv2D里有个`param_attr`参数用于指定卷积权重的属性，其中有个`trainable`属性是指定其是否会训练
> https://www.paddlepaddle.org.cn/documentation/docs/zh/api_cn/dygraph_cn/Conv2D_cn.html#conv2d
> https://www.paddlepaddle.org.cn/documentation/docs/zh/api_cn/fluid_cn/ParamAttr_cn.html#paramattr

感谢您的回复，我想要类似pytorch中F.conv2d(input, conv_kernel)中这个功能，conv_kernel是自定义的一个有特殊功能的卷积核，譬如sobel算子，这个卷积核的数值是固定的，我怎么实现这个功能

**Comment by yuctian** [comment]
> Conv2D里有个`param_attr`参数用于指定卷积权重的属性，其中有个`trainable`属性是指定其是否会训练
> https://www.paddlepaddle.org.cn/documentation/docs/zh/api_cn/dygraph_cn/Conv2D_cn.html#conv2d
> https://www.paddlepaddle.org.cn/documentation/docs/zh/api_cn/fluid_cn/ParamAttr_cn.html#paramattr

谢谢你，我找到了NumpyArrayInitializer，没有问题了
