### ISSUE TITLE
go packages blocked by network

### ISSUE THREAD

**Issue by dzhwinter** [PaddlePaddle/Paddle#2605]
related #2583 

some go packages hosting by google code is blocked, so when we built Paddle from source, we need to solve the built from source dependency problem. 
open this issue here for discussion

**Comment by helinwang** [comment]
@typhoonzero 's PR https://github.com/PaddlePaddle/Paddle/pull/2627 could fix this issue.

**Comment by dzhwinter** [comment]
closed since go package management fix it.
