### ISSUE TITLE
论文复现  自定义parameter问题

### ISSUE THREAD

**Issue by yuctian** [PaddlePaddle/Paddle#26055]
希望提供类似于pytorch中torch.nn.Parameter(torch.FloatTensor([1,2]))对网络层参数用tensor定义的支持

**Comment by heavengate** [comment]
可以使用这个API
https://www.paddlepaddle.org.cn/documentation/docs/zh/api_cn/layers_cn/create_parameter_cn.html#cn-api-fluid-layers-create-parameter

**Comment by yuctian** [comment]
这个API不行，我可能没描述清楚，我的意思是我直接指定参数的数值，譬如卷积核的权重参数，而不是随机初始化或者全部初始化为一个常数，比如我希望我的卷积核是[[0.5,0,-0.5]]

**Comment by yuctian** [comment]
> 可以使用这个API
> https://www.paddlepaddle.org.cn/documentation/docs/zh/api_cn/layers_cn/create_parameter_cn.html#cn-api-fluid-layers-create-parameter

这个API不行，我可能没描述清楚，我的意思是我直接指定参数的数值，譬如卷积核的权重参数，而不是随机初始化或者全部初始化为一个常数，比如我希望我的卷积核是[[0.5,0,-0.5]]

**Comment by yuctian** [comment]
> 可以使用这个API
> https://www.paddlepaddle.org.cn/documentation/docs/zh/api_cn/layers_cn/create_parameter_cn.html#cn-api-fluid-layers-create-parameter

搞定了，谢谢

**Comment by heavengate** [comment]
> > 可以使用这个API
> > https://www.paddlepaddle.org.cn/documentation/docs/zh/api_cn/layers_cn/create_parameter_cn.html#cn-api-fluid-layers-create-parameter
> 
> 搞定了，谢谢

numpy array初始化这个卷积权重么，Conv2D里有个param_attr参数，用于指定权重的属性，权重属性中有个 initializer参数，可以将这个参数指定为NumpyArrayInitializer并用你的numpy array去初始化
https://www.paddlepaddle.org.cn/documentation/docs/zh/api_cn/dygraph_cn/Conv2D_cn.html#conv2d
https://www.paddlepaddle.org.cn/documentation/docs/zh/api_cn/fluid_cn/ParamAttr_cn.html#paramattr
https://www.paddlepaddle.org.cn/documentation/docs/zh/api_cn/initializer_cn/NumpyArrayInitializer_cn.html#numpyarrayinitializer

**Comment by deep-practice** [comment]
fluid.ParamAttr和torch.nn.Parameter是等价的吗？ @heavengate

**Comment by henryccl** [comment]
> > > 可以使用这个API
> > > https://www.paddlepaddle.org.cn/documentation/docs/zh/api_cn/layers_cn/create_parameter_cn.html#cn-api-fluid-layers-create-parameter
> > 
> > 
> > 搞定了，谢谢
> 
> numpy array初始化这个卷积权重么，Conv2D里有个param_attr参数，用于指定权重的属性，权重属性中有个 initializer参数，可以将这个参数指定为NumpyArrayInitializer并用你的numpy array去初始化 https://www.paddlepaddle.org.cn/documentation/docs/zh/api_cn/dygraph_cn/Conv2D_cn.html#conv2d https://www.paddlepaddle.org.cn/documentation/docs/zh/api_cn/fluid_cn/ParamAttr_cn.html#paramattr https://www.paddlepaddle.org.cn/documentation/docs/zh/api_cn/initializer_cn/NumpyArrayInitializer_cn.html#numpyarrayinitializer
你好！我也想使用 numpy array初始化卷积权重，但是你给的链接失效了。我在飞桨的官方文档里也没找到相关的使用方法，求解答。
