### ISSUE TITLE
fusion_group is not enabled for Windows/MacOS now

### ISSUE THREAD

**Issue by DrRyanHuang** [PaddlePaddle/Paddle#26051]
cudnn : 7.6
cuda : 10.0
GTX 1050
paddle1.8.3
Python3.6

GPU版本安装成功后，在log中出现：
```
W0808 10:17:17.948967 15396 build_strategy.cc:170] fusion_group is not enabled for Windows/MacOS now, and only effective when running with CUDA GPU.
```
请问这是什么意思

**Comment by heavengate** [comment]
这个是GPU上的一个训练加速功能，当前只在CUDA上可用，在windows或者MacOS上不可用，这个只是一个性能优化的功能，不影响模型正常训练，可以不关注这条warning日志~

**Comment by DrRyanHuang** [comment]
还是有点儿没懂，在windows上安装的CUDA不能用吗？
@heavengate

**Comment by Xreki** [comment]
@DrRyanHuang fusion_group是一个正在开发中的功能，尚没有经过充分的验证，所以windows上是直接disable了。请问你是跑的哪个模型？另外这条log应该也不影响正常训练？

**Comment by A-k-ing** [comment]
> @DrRyanHuang fusion_group是一个正在开发中的功能，尚没有经过充分的验证，所以windows上是直接disable了。请问你是跑的哪个模型？另外这条log应该也不影响正常训练？

我跑PaddleDetection也遇到这种情况，W1109 19:58:59.794556 31476 build_strategy.cc:170] fusion_group is not enabled for Windows/MacOS now, and only effective when running with CUDA GPU.卡在这里不动
cudnn : 7.6
cuda : 10.0
GTX 1050TI  4G
CPU:ryzen5 1600
paddle1.8.5
Python3.7.8
windows10 1803
