### ISSUE TITLE
［论文复现］ 动态更改网络权重的功能

### ISSUE THREAD

**Issue by kafaichan** [PaddlePaddle/Paddle#26057]
请问paddlepaddle有提供像pytorch一样可以动态更改网络权重的功能吗? 例如说，有没有可能提供如
conv1.weight = Parameter(shape=[], data=numpy_array)的函数调用。

**Comment by heavengate** [comment]
是指根据一个numpy array初始化这个卷积权重么，Conv2D里有个`param_attr`参数，用于指定权重的属性，权重属性中有个` initializer`参数，可以将这个参数指定为`NumpyArrayInitializer`并用你的numpy array去初始化
https://www.paddlepaddle.org.cn/documentation/docs/zh/api_cn/dygraph_cn/Conv2D_cn.html#conv2d
https://www.paddlepaddle.org.cn/documentation/docs/zh/api_cn/fluid_cn/ParamAttr_cn.html#paramattr
https://www.paddlepaddle.org.cn/documentation/docs/zh/api_cn/initializer_cn/NumpyArrayInitializer_cn.html#numpyarrayinitializer

**Comment by kafaichan** [comment]
好的，谢谢
