### ISSUE TITLE
【论文复现】关于自定义卷积核参数和梯度传递问题

### ISSUE THREAD

**Issue by huochf** [PaddlePaddle/Paddle#26065]
楼下有人提到过自定义卷积核的问题，我似乎有些疑问，我现在的需求是使用另外一个网络（比如多层感知器）来输出卷积层的参数，并且将该参数加载到卷积中参与之后的卷积运算，还得要求在误差传播的过程中，该卷积层的误差能够传播到多层感知器中，这该如何实现？我看到楼下有人说到，使用初始化NumpyArrayInitializer，这样似乎截断了误差传递链。

**Comment by saxon-zh** [comment]
稍等，我们的@hutuxian 同学会给您解答一下。

**Comment by huochf** [comment]
@hutuxian 
咱Paddle有提供类似Pytorch中的F.conv2d(x, weights, ...)比较底层的接口吗？
如果没有应该怎么解决这个问题呢？这个操作是论文复现不可跳跃的步骤。
谢谢！！！

**Comment by hutuxian** [comment]
不知道您使用的是哪个版本的paddle？
paddle的develop分支提供了这个功能，https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/nn/functional/conv.py#L90
但是在1.8版本，暂时还不支持这个功能。

**Comment by huochf** [comment]
> 不知道您使用的是哪个版本的paddle？
> paddle的develop分支提供了这个功能，https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/nn/functional/conv.py#L90
> 但是在1.8版本，暂时还不支持这个功能。

哇！就是这个函数，Paddle NB！！！
咱AI Studio能用develop这个版本吗，我目前只能在AI Studio中完成本次复现的工作。

**Comment by saxon-zh** [comment]
可以在AIStudio的终端里面直接装develop的whl包，develop的whl包通过这里下载，

https://www.paddlepaddle.org.cn/documentation/docs/zh/install/Tables.html#whl-dev

目前跟AIStudio的PM确认了下，可以下载paddlepaddle_gpu-latest-cp37-cp37m-linux_x86_64.whl这个来进行安装。

**Comment by huochf** [comment]
> 可以在AIStudio的终端里面直接装develop的whl包，develop的whl包通过这里下载，
> https://www.paddlepaddle.org.cn/documentation/docs/zh/install/Tables.html#whl-dev
> 目前跟AIStudio的PM确认了下，可以下载paddlepaddle_gpu-latest-cp37-cp37m-linux_x86_64.whl这个来进行安装。

好的，好的！！这个回答我非常满意！
Paddle NB！AI Studio NB！

**Comment by hbwslms** [comment]
> 不知道您使用的是哪个版本的paddle？
> paddle的develop分支提供了这个功能，https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/nn/functional/conv.py#L90
> 但是在1.8版本，暂时还不支持这个功能。

我也有类似的问题，现在怎么用自定义的卷积核的问题解决了，但我还想知道怎么让这个卷积核的不会被梯度更新，就像torch里的requires_grad=False一样
