### ISSUE TITLE
【论文复现】能提供类似于torchvision里面的transformer的功能吗

### ISSUE THREAD

**Issue by deep-practice** [PaddlePaddle/Paddle#26060]
比如：
transforms.Normalize(mean=(0.5, 0.5, 0.5), std=(0.5, 0.5, 0.5))
transforms.ToTensor()
这样至少保证大家的输入是一致的

**Comment by deep-practice** [comment]
当然，自己去写也可以，但每个项目都这样去复制粘贴一下，感觉很冗余

**Comment by hutuxian** [comment]
https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/beginners_guide/hapi.html#transform
paddle也提供有一些，这个页面的内容也许对您有帮助~

**Comment by deep-practice** [comment]
新版本的paddle 预计什么时候发布呢？

**Comment by deep-practice** [comment]
API对照表里面
torch.var_mean<==> paddle.fluid.layers.mean
但fluid.layers.mean只是计算均值，没有方差呀
@hutuxian

**Comment by deep-practice** [comment]
unsqueeze操作要通过reshape来实现吗？

**Comment by hutuxian** [comment]
> 新版本的paddle 预计什么时候发布呢？

预计9月，但是AiStudio预期应该可以使用develop版本，使用方法参见：https://github.com/PaddlePaddle/Paddle/issues/26065#issuecomment-671143301

> 但fluid.layers.mean只是计算均值，没有方差呀

https://www.paddlepaddle.org.cn/documentation/docs/zh/2.0-alpha/api_cn/tensor_cn/std_cn.html#std
在2.0alpha或develop版本有提供给这个op。1.8的话，可以通过均值，平方等OP组合得到。

**Comment by deep-practice** [comment]
那在指定维度求均值，也要自己slice吗

**Comment by deep-practice** [comment]
是不是转成numpy再操作就可以了。。

**Comment by hutuxian** [comment]
可以参考`reduce_mean`这个OP~

**Comment by deep-practice** [comment]
很好

**Comment by deep-practice** [comment]
for name,param in model.named_parameters():
         pass
遍历这个列表的时候，如何去改变里面的参数值呢？
@hutuxian
