### ISSUE TITLE
【论文复现】api中是否有生成类似torch.ByteTensor 这类Variable的方法

### ISSUE THREAD

**Issue by Rookieaura** [PaddlePaddle/Paddle#26066]
Pytorch API:
img = torch.ByteTensor(torch.ByteStorage.from_buffer(pic.tobytes()))
reference: https://pytorch.org/docs/stable/tensors.html

问题：
在生成variable时，除了从np.array用to_variable直接生成Tensor外，能否生成 FloatTensor, ByteTensor等指定类型的Tensor？

**Comment by huochf** [comment]
我只知道有astype这个函数，不知道能不能满足你的需求，astype(self, dtype)
例如：
静态图下：
import paddle.fluid as fluid

startup_prog = fluid.Program()
main_prog = fluid.Program()
with fluid.program_guard(startup_prog, main_prog):
    original_variable = fluid.data(name = "new_variable", shape=[2,2], dtype='float32')
    new_variable = original_variable.astype('int64')
    print("new var's dtype is: {}".format(new_variable.dtype))
动态图下：
import paddle.fluid as fluid
import numpy as np

x = np.ones([2, 2], np.float32)
with fluid.dygraph.guard():
    original_variable = fluid.dygraph.to_variable(x)
    print("original var's dtype is: {}, numpy dtype is {}".format(original_variable.dtype, original_variable.numpy().dtype))
    new_variable = original_variable.astype('int64')
    print("new var's dtype is: {}, numpy dtype is {}".format(new_variable.dtype, new_variable.numpy().dtype))
参考：https://www.paddlepaddle.org.cn/documentation/docs/zh/api_cn/fluid_cn/Variable_cn.html#astype-self-dtype
