### ISSUE TITLE
[bug] PaddlePaddle识别不了2080Ti

### ISSUE THREAD

**Issue by Mr-Nineteen** [PaddlePaddle/Paddle#26077]
Python 3.7.4 (default, Jul 21 2020, 17:09:27) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-39)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import paddle.fluid as fluid
>>> gpu_place = fluid.CUDAPlace(0)
>>> fluid.install_check.run_check()
Running Verify Fluid Program ... 
W0810 10:51:18.092149  4231 device_context.cc:252] Please NOTE: device: 0, CUDA Capability: 75, Driver API Version: 10.1, Runtime API Version: 9.0
W0810 10:51:18.098635  4231 device_context.cc:260] device: 0, cuDNN Version: 7.6.

/usr/local/lib/python3.7/site-packages/paddle/fluid/executor.py:1070: UserWarning: The following exception is not an EOF exception.
  "The following exception is not an EOF exception.")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.7/site-packages/paddle/fluid/install_check.py", line 124, in run_check
    test_simple_exe()
  File "/usr/local/lib/python3.7/site-packages/paddle/fluid/install_check.py", line 122, in test_simple_exe
    fetch_list=[out0.name, param_grads[1].name])
  File "/usr/local/lib/python3.7/site-packages/paddle/fluid/executor.py", line 1071, in run
    six.reraise(*sys.exc_info())
  File "/usr/local/lib/python3.7/site-packages/six.py", line 703, in reraise
    raise value
  File "/usr/local/lib/python3.7/site-packages/paddle/fluid/executor.py", line 1066, in run
    return_merged=return_merged)
  File "/usr/local/lib/python3.7/site-packages/paddle/fluid/executor.py", line 1154, in _run_impl
    use_program_cache=use_program_cache)
  File "/usr/local/lib/python3.7/site-packages/paddle/fluid/executor.py", line 1229, in _run_program
    fetch_var_name)
paddle.fluid.core_avx.EnforceNotMet: 

--------------------------------------------
C++ Call Stacks (More useful to developers):
--------------------------------------------
0   std::string paddle::platform::GetTraceBackString<char const*>(char const*&&, char const*, int)
1   paddle::platform::EnforceNotMet::EnforceNotMet(std::__exception_ptr::exception_ptr, char const*, int)
2   void paddle::operators::math::Blas<paddle::platform::CUDADeviceContext>::GEMM<float>(CBLAS_TRANSPOSE, CBLAS_TRANSPOSE, int, int, int, float, float const*, float const*, float, float*) const
3   void paddle::operators::math::Blas<paddle::platform::CUDADeviceContext>::MatMul<float>(paddle::framework::Tensor const&, paddle::operators::math::MatDescriptor const&, paddle::framework::Tensor const&, paddle::operators::math::MatDescriptor const&, float, paddle::framework::Tensor*, float) const
4   paddle::operators::MatMulKernel<paddle::platform::CUDADeviceContext, float>::Compute(paddle::framework::ExecutionContext const&) const
5   std::_Function_handler<void (paddle::framework::ExecutionContext const&), paddle::framework::OpKernelRegistrarFunctor<paddle::platform::CUDAPlace, false, 0ul, paddle::operators::MatMulKernel<paddle::platform::CUDADeviceContext, float>, paddle::operators::MatMulKernel<paddle::platform::CUDADeviceContext, double>, paddle::operators::MatMulKernel<paddle::platform::CUDADeviceContext, paddle::platform::float16> >::operator()(char const*, char const*, int) const::{lambda(paddle::framework::ExecutionContext const&)#1}>::_M_invoke(std::_Any_data const&, paddle::framework::ExecutionContext const&)
6   paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, paddle::platform::Place const&, paddle::framework::RuntimeContext*) const
7   paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, paddle::platform::Place const&) const
8   paddle::framework::OperatorBase::Run(paddle::framework::Scope const&, paddle::platform::Place const&)
9   paddle::framework::Executor::RunPartialPreparedContext(paddle::framework::ExecutorPrepareContext*, paddle::framework::Scope*, long, long, bool, bool, bool)
10  paddle::framework::Executor::RunPreparedContext(paddle::framework::ExecutorPrepareContext*, paddle::framework::Scope*, bool, bool, bool)
11  paddle::framework::Executor::Run(paddle::framework::ProgramDesc const&, paddle::framework::Scope*, int, bool, bool, std::vector<std::string, std::allocator<std::string> > const&, bool, bool)

------------------------------------------
Python Call Stacks (More useful to users):
------------------------------------------
  File "/usr/local/lib/python3.7/site-packages/paddle/fluid/framework.py", line 2610, in append_op
    attrs=kwargs.get("attrs", None))
  File "/usr/local/lib/python3.7/site-packages/paddle/fluid/dygraph/layer_object_helper.py", line 52, in append_op
    stop_gradient=stop_gradient)
  File "/usr/local/lib/python3.7/site-packages/paddle/fluid/dygraph/nn.py", line 962, in forward
    type="matmul", inputs=inputs, outputs={"Out": tmp}, attrs=attrs)
  File "/usr/local/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 461, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/paddle/fluid/install_check.py", line 41, in forward
    x = self._linear1(inputs)
  File "/usr/local/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 461, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/paddle/fluid/install_check.py", line 113, in test_simple_exe
    out0 = simple_layer0(inp0)
  File "/usr/local/lib/python3.7/site-packages/paddle/fluid/install_check.py", line 124, in run_check
    test_simple_exe()
  File "<stdin>", line 1, in <module>

----------------------
Error Message Summary:
----------------------
ExternalError:  Cublas error, CUBLAS_STATUS_EXECUTION_FAILED  at (/paddle/paddle/fluid/operators/math/blas_impl.cu.h:34)
  [operator < matmul > error]

**Comment by sandyhouse** [comment]
应该是CUDA相关环境的问题，可以参考下面的issue：https://github.com/PaddlePaddle/Paddle/issues/24302

**Comment by Mr-Nineteen** [comment]
@sandyhouse P40或者P4没有问题，2080Ti就不行

**Comment by sandyhouse** [comment]
P40和P4和2080Ti的环境都是完全一致的吗，包括安装的CUDA等相关软件？ @Mr-Nineteen

**Comment by Mr-Nineteen** [comment]
@sandyhouse 是的，做成镜像的，环境是一致的

**Comment by sandyhouse** [comment]
> 测试过cuda10环境么？可以使用 docker pull paddlepaddle/paddle:1.8.0-gpu-cuda10.0-cudnn7 下载官方docker，然后使用nvidia-docker命令进入docker内部使用gpu环境。

可以用这个官方镜像试一试。

**Comment by Mr-Nineteen** [comment]
@sandyhouse 你们提供的镜像有python3.7.4(3.7.x)的？

**Comment by sandyhouse** [comment]
可以先用这个镜像测试下是否有问题docker pull paddlepaddle/paddle:1.8.0-gpu-cuda10.0-cudnn7，如果需要特定python版本的话可以在镜像里面自行安装。
