### ISSUE TITLE
【论文复现】How to turn off bias term in InstanceNorm 

### ISSUE THREAD

**Issue by zzz2010** [PaddlePaddle/Paddle#26072]
Hi, in pytorch ,  we can set affine=False in InstanceNorm to turn off bias term.  
However in paddle 1.8,  we can not set bias_attrs=False in InstanceNorm

https://github.com/PaddlePaddle/Paddle/blob/release/1.8/python/paddle/fluid/dygraph/nn.py#L1052

May I know how to reproduce result as InstanceNorm in pytorch using paddle?

Thank you

**Comment by hutuxian** [comment]
A workaround is initialize bias_attrs as zeros and set this parameter's `trainable` attribute as False.
And this problem has been fixed in develop version, you can try it.
