### ISSUE TITLE
论文复现  关于修改中间Tensor值的问题

### ISSUE THREAD

**Issue by yuctian** [PaddlePaddle/Paddle#26070]
grad= self.conv4u(layers.pad(y,(0,0,0,0,1,1,0,0)))
grad[:,:,:,0] = 0.5 * (x[:,:,:,1] - x[:,:,:,0])
类似于实现这样的操作，grad是经过卷积后得到的输出，我需要对grad中部分值重新指定数值，有没有方法可以实现。
以上操作会报错TypeError: 'paddle.fluid.core_avx.VarBase' object does not support item assignment

**Comment by huochf** [comment]
同问，这个问题也困惑了我好久，Paddle里面的Tensor太不灵活了。

**Comment by deep-practice** [comment]
灵活性赶pytorch还是有距离

**Comment by sandyhouse** [comment]
可以试下set_value方法，比如grad.set_value(xxx),参数可以是numpy类型。

**Comment by yuctian** [comment]
求老师们解答，在线等

**Comment by sandyhouse** [comment]
请问你用的是动态图还是静态图，如果是动态图的话，可以用set_value方法吗。比如grad.set_value(xxx)。需要注意的是，可能需要在每次迭代时set_value,而不是在组网时 @yuctian。

**Comment by yuctian** [comment]
> 请问你用的是动态图还是静态图，如果是动态图的话，可以用set_value方法吗。比如grad.set_value(xxx)。需要注意的是，可能需要在每次迭代时set_value,而不是在组网时 @yuctian。

我还没知道试，这样操作 不知道会不会影响梯度回传

**Comment by sandyhouse** [comment]
你需要在什么地方修改，是否可以贴下完整的代码

**Comment by yuctian** [comment]
> 你需要在什么地方修改，是否可以贴下完整的代码

 def forward_grad(self, x):
        grad_x = F.conv2d(F.pad(x, (0,0,0,1)), self.f_grad)#, groups=self.channels)
        grad_x[:,:,-1,:] = 0
        
        grad_y = F.conv2d(F.pad(x, (0,0,0,1)), self.f_grad2)#, groups=self.channels)
        grad_y[:,:,-1,:] = 0
        return grad_x, grad_y
这是在pytorch的代码，要实现这样的功能

**Comment by sandyhouse** [comment]
> 请问你用的是动态图还是静态图，如果是动态图的话，可以用set_value方法吗。比如grad.set_value(xxx)。需要注意的是，可能需要在每次迭代时set_value,而不是在组网时 @yuctian。
> 
> 我还没知道试，这样操作 不知道会不会影响梯度回传

用set_value的话确实影响梯度回传。

另外，如果要实现
```
def forward_grad(self, x):
grad_x = F.conv2d(F.pad(x, (0,0,0,1)), self.f_grad)#, groups=self.channels)
grad_x[:,:,-1,:] = 0

grad_y = F.conv2d(F.pad(x, (0,0,0,1)), self.f_grad2)#, groups=self.channels)
grad_y[:,:,-1,:] = 0
return grad_x, grad_y
```
这段代码的话，paddle动态图目前不支持类似grad_y[:,:,-1:]=0这种赋值方式，提供下面的思路供参考。
```
# grad_y[:,:,-1:]=0
temp = unstack(grad_y, axis=2)
temp[-1] = 0
grad_y = stack(temp, axis=2)
```

**Comment by yuctian** [comment]
> > 请问你用的是动态图还是静态图，如果是动态图的话，可以用set_value方法吗。比如grad.set_value(xxx)。需要注意的是，可能需要在每次迭代时set_value,而不是在组网时 @yuctian。
> > 我还没知道试，这样操作 不知道会不会影响梯度回传
> 
> 用set_value的话确实影响梯度回传。
> 
> 另外，如果要实现
> 
> ```
> def forward_grad(self, x):
> grad_x = F.conv2d(F.pad(x, (0,0,0,1)), self.f_grad)#, groups=self.channels)
> grad_x[:,:,-1,:] = 0
> 
> grad_y = F.conv2d(F.pad(x, (0,0,0,1)), self.f_grad2)#, groups=self.channels)
> grad_y[:,:,-1,:] = 0
> return grad_x, grad_y
> ```
> 
> 这段代码的话，paddle动态图目前不支持类似grad_y[:,:,-1:]=0这种赋值方式，提供下面的思路供参考。
> 
> ```
> # grad_y[:,:,-1:]=0
> temp = unstack(grad_y, axis=2)
> temp[-1] = 0
> grad_y = stack(temp, axis=2)
> ```

谢谢，方法可行

**Comment by chunfeng0301** [comment]
> grad= self.conv4u(layers.pad(y,(0,0,0,0,1,1,0,0)))
> grad[:,:,:,0] = 0.5 * (x[:,:,:,1] - x[:,:,:,0])
> 类似于实现这样的操作，grad是经过卷积后得到的输出，我需要对grad中部分值重新指定数值，有没有方法可以实现。
> 以上操作会报错TypeError: 'paddle.fluid.core_avx.VarBase' object does not support item assignment

有怎么实现上面代码的答案了么？

**Comment by sandyhouse** [comment]
> 这段代码的话，paddle动态图目前不支持类似grad_y[:,:,-1:]=0这种赋值方式，提供下面的思路供参考。
> 
> # grad_y[:,:,-1:]=0
> temp = unstack(grad_y, axis=2)
> temp[-1] = 0
> grad_y = stack(temp, axis=2)

可参考上面的思路实现 @chunfeng0301

**Comment by chunfeng0301** [comment]
> > 这段代码的话，paddle动态图目前不支持类似grad_y[:,:,-1:]=0这种赋值方式，提供下面的思路供参考。
> > # grad_y[:,:,-1:]=0
> > temp = unstack(grad_y, axis=2)
> > temp[-1] = 0
> > grad_y = stack(temp, axis=2)
> 
> 可参考上面的思路实现 @chunfeng0301

谢啦 确实可行

**Comment by chunfeng0301** [comment]
> > 这段代码的话，paddle动态图目前不支持类似grad_y[:,:,-1:]=0这种赋值方式，提供下面的思路供参考。
> > # grad_y[:,:,-1:]=0
> > temp = unstack(grad_y, axis=2)
> > temp[-1] = 0
> > grad_y = stack(temp, axis=2)
> 
> 可参考上面的思路实现 @chunfeng0301
报如下错误
File "/home/aistudio/model/rep_flow_layer_pp.py", line 142, in forward_grad
    grad_x = stack(temp, axis=3)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/layers/nn.py", line 10979, in stack
    attrs={'axis': axis})
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/layer_helper.py", line 43, in append_op
    return self.main_program.current_block().append_op(*args, **kwargs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/framework.py", line 2601, in append_op
    kwargs.get("stop_gradient", False))
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/tracer.py", line 43, in trace_op
    not stop_gradient)
paddle.fluid.core_avx.EnforceNotMet: 

--------------------------------------------
C++ Call Stacks (More useful to developers):
--------------------------------------------
0   std::string paddle::platform::GetTraceBackString<std::string>(std::string&&, char const*, int)
1   paddle::platform::EnforceNotMet::EnforceNotMet(paddle::platform::ErrorSummary const&, char const*, int)

----------------------
Error Message Summary:
----------------------
InvalidArgumentError: Python object is not type of St10shared_ptrIN6paddle10imperative7VarBaseEE at (/paddle/paddle/fluid/pybind/imperative.cc:164)
