### ISSUE TITLE
请问这两句结果是否相同？

### ISSUE THREAD

**Issue by good18** [PaddlePaddle/Paddle#26074]
请问以下两个语句有何区别：
paddle.reader.xmap_readers
paddle.fluid.io.xmap_readers
在管网只查到第2个用法

**Comment by sandyhouse** [comment]
这两个接口的执行效果是一致的，只是报漏出来的接口不一样而已。

**Comment by good18** [comment]
> 这两个接口的执行效果是一致的，只是报漏出来的接口不一样而已。

谢谢

**Comment by sandyhouse** [comment]
Closing this issue. Feel free to reopen it if you have any further question.
