### ISSUE TITLE
【论文复现】参数和偏置初始化

### ISSUE THREAD

**Issue by kgkzhiwen** [PaddlePaddle/Paddle#26073]
在复现中碰到下面这段代码：
        for m in self.modules():            
            if isinstance(m, Conv3d):
                nn.init.kaiming_normal_(m.weight, mode='fan_out', nonlinearity='relu') 
            elif isinstance(m, BatchNorm):
                m.weight.data.fill_(1)
                m.bias.data.zero_()
有几个问题：
1. 怎么样loop得到模型中的每一层layer， sublayer?
2. 然后怎么样设置其中的参数和偏置？
3. 有没有办法把向上面的代码那样把参数或者偏置设为1或0？

谢谢！

**Comment by sandyhouse** [comment]
1. 可以使用sublayers获取所有的层：https://www.paddlepaddle.org.cn/documentation/docs/zh/api_cn/dygraph_cn/Layer_cn.html#sublayers-include-sublayers-true
2. 可以在定义某一层的时候设置改层的相关参数和偏置的值，以上例中的Conv3d为例，可以采用下面的方法通过param_attr和bias_attr设置参数和偏置值。
```
conv3d = fluid.dygraph.nn.Conv3D(
          'Conv3D', 
          num_filters=2, 
          filter_size=3, 
          param_attr="your custom code",
          bias_attr=fluid. ParamAttr(initializer="your initializer"),
          act="relu")
```
3. 可以试下set_value方法，例如：
```
t = to_variable(data)
linear(t)  # call with default weight
custom_weight = np.random.randn(1024, 4).astype("float32")
linear.weight.set_value(custom_weight)  # change existing weight
```

**Comment by kgkzhiwen** [comment]
在构建网络是使用了set_value, 出现了如下错误：
`166             elif isinstance(m, BatchNorm):

--> 167                 m.weight.set_value(fluid.initializer.Constant(value=1))

    168                 m.bias.set_value(fluid.initializer.Constant(value=0))

    169                 #m.weight.data.fill_(1)

</opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/decorator.py:decorator-gen-133> in set_value(self, value)
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/wrapped_decorator.py in __impl__(func, *args, **kwargs)

     23     def __impl__(func, *args, **kwargs):

     24         wrapped_func = decorator_func(func)

---> 25         return wrapped_func(*args, **kwargs)

     26 
     27     return __impl__
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/framework.py in __impl__(*args, **kwargs)

    230         raise AssertionError(
    231             "'%s' should be called by imperative Varible in imperative mode, please use fluid.dygraph.guard() as context to run it in imperative mode"

--> 232             % func.__name__)

    233 

    234     return __impl__
AssertionError: 'set_value' should be called by imperative Varible in imperative mode, please use fluid.dygraph.guard() as context to run it in imperative mode`

请问要如何解决？

**Comment by sandyhouse** [comment]
是否把相关代码放下面的guard下面呢？
```
with fluid.dygraph.guard():
    some codes
```

**Comment by kgkzhiwen** [comment]
这个是要在构建网络的时候进行初始化。在fluid.dygraph.guard()下面达不到这个目标吧？

**Comment by sandyhouse** [comment]
是否可以提供小段的复现代码，试一试。

**Comment by kgkzhiwen** [comment]
`class DenseNet(fluid.dygraph.Layer):
    def __init__(self,  n_input_channels=3, conv1_t_size=7, conv1_t_stride=1,
                 no_max_pool=False,
                 growth_rate=32,
                 block_config=(6, 12, 24, 16),
                 num_init_features=64,
                 bn_size=4,
                 drop_rate=0.5,
                 num_classes=1000):

        super().__init__()
        self.features=Sequential()
        num_features = num_init_features
        for i, num_layers in enumerate(block_config):
            block = _DenseBlock(num_layers=num_layers,
                                num_input_features=num_features,
                                bn_size=bn_size,
                                growth_rate=growth_rate,
                                drop_rate=drop_rate)
            self.features.add_sublayer('denseblock{}'.format(i + 1), block)
            num_features = num_features + num_layers * growth_rate
            
        self.features.add_sublayer('norm5', BatchNorm(num_features, param_attr=fluid.initializer.Constant(value=1),bias_attr=fluid.initializer.Constant(value=0)))

         self.classifier = Linear(num_features, num_classes, bias_attr=fluid.ParamAttr(initializer=fluid.initializer.Constant(value=0)))

        for m in self.sublayers():
            
            if isinstance(m, Conv3D):
                
                m.weight.set_value(paddle.fluid.initializer.MSRAInitializer(uniform=True, fan_in=None, seed=0))
            elif isinstance(m, BatchNorm):
                m.weight.set_value(fluid.initializer.Constant(value=1))
                m.bias.set_value(fluid.initializer.Constant(value=0))            
           
    def forward(self, x):
        out=self.features(x)          
        out = self.classifier(out)
        return out`

搞不通也没关系。我直接利用ParamAttr初始化权重和偏置了。
