### ISSUE TITLE
pip安装paddlepaddle报错

### ISSUE THREAD

**Issue by bkseastone** [PaddlePaddle/Paddle#26085]
安装出现未找到版本错误：
![image](https://user-images.githubusercontent.com/18327200/89755365-bffa4b80-db11-11ea-9cce-0ec75e61c5fd.png)
![image](https://user-images.githubusercontent.com/18327200/89755378-d0122b00-db11-11ea-9bbb-37cbd441d3c4.png)
升级pip后，报错：
![image](https://user-images.githubusercontent.com/18327200/89755394-e7e9af00-db11-11ea-8104-45662dd98058.png)

**Comment by sandyhouse** [comment]
麻烦你用where python，python --version看一下是不是位置和版本号. 另外，你用pip search paddlepaddle的输出是什么？

**Comment by bkseastone** [comment]
python环境问题。已解决。
