### ISSUE TITLE
【论文复现】paddle.fluid.dygraph.SpectralNorm不能直接把Layer传进去吗？

### ISSUE THREAD

**Issue by deep-practice** [PaddlePaddle/Paddle#26084]
SpectralNorm(Conv2D(input_nc, ndf, filter_size=4, stride=2, padding=0))报错
TypeError: 'Conv2D' object is not iterable

如果不能这么组合的话，搭建模型很不方便，不能当作一个整体操作

**Comment by huochf** [comment]
使用静态图spectral_norm的不香吗，不能死板的改名字，pytorch和paddle还是有一定区别的。

**Comment by deep-practice** [comment]
归一化完conv.weight之后，怎么去更新这个conv的weight呢

**Comment by huochf** [comment]
> 归一化完conv.weight之后，怎么去更新这个conv的weight呢

没明白什么意思，其实我对paddle也不熟悉，看到这里没人回复，我就简单说几句，我在复现论文中是在forward使用spectral_norm函数来代替的定义SpectralNorm的。
你还是等开发人员来解答吧！

**Comment by deep-practice** [comment]
spectral_norm只对权重参数进行归一化，但是归一化完之后，要更新那个卷积层的权重参数才行吧，还是说用了spectral_norm之后，对应的卷积的那个权重参数也跟着更新了？

**Comment by huochf** [comment]
> spectral_norm只对权重参数进行归一化，但是归一化完之后，要更新那个卷积层的权重参数才行吧，还是说用了spectral_norm之后，对应的卷积的那个权重参数也跟着更新了？

呀！这个小细节没注意，我觉得使用fluid.nn.functional.conv2d(inputs, weights)可以解决这个问题吧，还是再等等开发人员吧！
我那里似乎写错了。

**Comment by deep-practice** [comment]
是我理解错了，那个就已经是最后的结果了
