### ISSUE TITLE
centos 安装报错

### ISSUE THREAD

**Issue by mvxi** [PaddlePaddle/Paddle#26097]
环境：
python 版本：3.6.4
python pip版本：20.2.1
centos 64bit，x85_64

进行pip安装时： python3 -m pip install paddlepaddle -i https://mirror.baidu.com/pypi/simple
提示错误：
ERROR: Could not find a version that satisfies the requirement paddlepaddle (from versions: none)
ERROR: No matching distribution found for paddlepaddle
请教原因

**Comment by sandyhouse** [comment]
麻烦你用where python，python --version看一下是不是位置和版本号

**Comment by mvxi** [comment]
![image](https://user-images.githubusercontent.com/3888647/89854436-77e93080-dbc6-11ea-9ca0-34bac5668d14.png)

**Comment by mvxi** [comment]
> 麻烦你用where python，python --version看一下是不是位置和版本号

![image](https://user-images.githubusercontent.com/3888647/89854503-9f3ffd80-dbc6-11ea-95bb-2c153e872f05.png)

**Comment by sandyhouse** [comment]
我这边无法复现该问题，你可以参考https://www.paddlepaddle.org.cn/documentation/docs/zh/install/install_CentOS.html 安装步骤确认下，也可以试试别的安装源。如果都不可以的话，可以到https://www.paddlepaddle.org.cn/documentation/docs/zh/install/Tables.html#ciwhls 下载需要的版本的wheel包，本地安装试一试。

**Comment by D-DanielYang** [comment]
> x85_64

https://www.paddlepaddle.org.cn/install/quick
可以对照着这个一步步看下，是不是都满足需求
![image](https://user-images.githubusercontent.com/23690325/90147219-8ac15800-ddb4-11ea-8938-ae414a4c43a8.png)
