### ISSUE TITLE
Protobuf library should upgrade to protobuf 3.3

### ISSUE THREAD

**Issue by reyoung** [PaddlePaddle/Paddle#2609]
The current release of protobuf is [3.3.2](https://github.com/google/protobuf/tree/v3.3.2), but Paddle is using protobuf 3.1.0. In protobuf 3.1.0, there are several bugs which affect our code:

* In Protobuf 3.1.0, `map` in protobuf cannot be compiled by GCC with `-Wextra`.
  * The protobuf issue is https://github.com/google/protobuf/issues/2425.
  * In our [attribute design](https://github.com/PaddlePaddle/Paddle/pull/2555/files#diff-eb713df05f941c315a37b26d38a53ed9), `map` is used to associate from attribute name to value.
* Protobuf 3.1.0 uses a deprecated API on MacOS. 
  * The protobuf issue is https://github.com/google/protobuf/issues/2182
  * Our issue is #1936.

**Comment by reyoung** [comment]
@wangkuiyi @gangliao Should we upgrade our protobuf library? If we should, I could give a PR tomorrow.

**Comment by gangliao** [comment]
@Xreki  I don't have the environment to build the protobuf 3.3.2 on ARM,  @Xreki  Can you please build this version? Is it feasible to upgrade protobuf?

**Comment by Xreki** [comment]
I have tried to build the newest protobuf before and met some problem. In the building process of the newest version, there is a need to generate a binary file and run the binary file. 
In [cmake/libprotoc.cmake](https://github.com/google/protobuf/blob/master/cmake/libprotoc.cmake#L212)
```
add_executable(js_embed ${protobuf_source_dir}/src/google/protobuf/compiler/js/embed.cc)
add_custom_command(
  OUTPUT ${protobuf_source_dir}/src/google/protobuf/compiler/js/well_known_types_embed.cc
  DEPENDS js_embed ${js_well_known_types_sources}
  COMMAND js_embed ${js_well_known_types_sources} > ${protobuf_source_dir}/src/google/protobuf/compiler/js/well_known_types_embed.cc
)
```

Simple command `make` was used, thus all the targets of `Protobuf` will be made. I will try another detailed command like `make libprotobuf` to not build `protoc`.

**Comment by reyoung** [comment]
This issue is blocked by Protobuf's cmake. We cannot upgrade our protobuf from 3.1 to 3.3 because, in 3.2, cmake cannot build a cross-compile protobuf.

The PRs are added and not merged.

* https://github.com/google/protobuf/pull/2998
* https://github.com/google/protobuf/pull/2980

**Comment by qingqing01** [comment]
The https://github.com/google/protobuf/pull/3878 fixed cross-compiling for android.
