### ISSUE TITLE
【论文复现】UGATIT torch.backends.cudnn.benchmark

### ISSUE THREAD

**Issue by sincerevertigo** [PaddlePaddle/Paddle#26118]
if torch.backends.cudnn.enabled and self.benchmark_flag:
            print('set benchmark !')
            torch.backends.cudnn.benchmark = True

paddle复现的话，不需要考虑上面的设置了吧。
谢谢。

**Comment by ceci3** [comment]
不需要的

**Comment by sincerevertigo** [comment]
@ceci3 
谢谢！！！
