### ISSUE TITLE
【论文复现】add_sublayer 出错

### ISSUE THREAD

**Issue by kgkzhiwen** [PaddlePaddle/Paddle#26112]
`       在训练DenseNet 121, 下面的关于add_sublayer的代码训练时出现一个问题。请问要如何解决？

        self.feature0=Sequential()
        self.feature0.add_sublayer('conv1',
                          Conv3D(n_input_channels,
                                num_init_features,
                                filter_size=(conv1_t_size, 7, 7),
                                stride=(conv1_t_stride, 2, 2),
                                padding=(conv1_t_size // 2, 3, 3)))`

/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/tracer.py in trace_op(self, type, inputs, outputs, attrs, stop_gradient)
     41         self.trace(type, inputs, outputs, attrs,
     42                    framework._current_expected_place(), self._train_mode and
---> 43                    not stop_gradient)
     44 
     45     def train_mode(self):
**RuntimeError: parallel_for failed: an illegal memory access was encountered**

**Comment by sandyhouse** [comment]
请问有可复现的代码吗

**Comment by kgkzhiwen** [comment]
好像是参数太大，内存溢出了。
