### ISSUE TITLE
【论文复现】有没有Pytorch Pool3D的替代函数

### ISSUE THREAD

**Issue by kgkzhiwen** [PaddlePaddle/Paddle#26110]
我想问一下有没有Pytorch Pool3D的替代函数？当我用

fluid.layers.pool3d 函数时：

self.features.append(('pool1', pool3d(pool_size=3, pool_stride=2, pool_padding=1, pool_type='max')))

出现下面这个错误：
TypeError: pool3d() missing 1 required positional argument: 'input'

感觉好像是要输入，可是在构造网络的时候，输入还是未知的。

请问要怎么解决这个问题？

**Comment by thrkingd** [comment]
你在动态图的forward函数里面调用fluid.layers.pool3d就有输入了，不要在构造函数里面调用

**Comment by kgkzhiwen** [comment]
明白了。复现原来不是那么简单
