### ISSUE TITLE
【论文复现】请问报这种错是什么原因matmul(): incompatible function arguments. The following argument types are supported:     1. (arg0: paddle::imperative::VarBase, arg1: paddle::imperative::VarBase, arg2: paddle::imperative::VarBase, *args) -> paddle::imperative::VarBase

### ISSUE THREAD

**Issue by liuxianyi** [PaddlePaddle/Paddle#26116]
![image](https://user-images.githubusercontent.com/33951338/89838978-3beea500-db9f-11ea-80f5-00d863e8281e.png)

![image](https://user-images.githubusercontent.com/33951338/89838956-2d07f280-db9f-11ea-8685-ada090a9b7cd.png)

**Comment by sandyhouse** [comment]
从报错信息看是matmul这个算子的输入类型不匹配，可以检查下。（是不是对输入没有采用to_variable调用，比如to_variable(x)之类的。
