### ISSUE TITLE
【论文复现】paddle.incubate.vision.transforms.ColorJitter怎么用？

### ISSUE THREAD

**Issue by thrkingd** [PaddlePaddle/Paddle#26119]
pytorch api的对照表倒数第二个函数paddle.incubate.vision.transforms.ColorJitter在官网文档中搜索不到这个函数，怎么用？

**Comment by ceci3** [comment]
参考这里 https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/incubate/hapi/tests/test_transforms.py#L59
