### ISSUE TITLE
关于NLP模型长短时记忆网络

### ISSUE THREAD

**Issue by YOMO-Lee** [PaddlePaddle/Paddle#26117]
我的项目做的是一个二分类任务，采用的长短时记忆网络，不过这个网络对我好复杂。目前训练数据一致不成功，有谁可以给我看一看怎么解决么
https://aistudio.baidu.com/aistudio/projectdetail/470283?shared=1
这个是项目地址

**Comment by zhijia3278** [comment]
https://aistudio.baidu.com/aistudio/projectdetail/470283?shared=1

**Comment by ceci3** [comment]
打印一下pred 看下是不是训练有什么问题

**Comment by YOMO-Lee** [comment]
@ceci3 大佬，可以留个联系方式么？我想详细请教下

**Comment by adaxiadaxi** [comment]
可以加入飞桨qq群咨询沟通：1108045677 @zhijia3278
