### ISSUE TITLE
【论文复现】矩阵求逆

### ISSUE THREAD

**Issue by sunjie97** [PaddlePaddle/Paddle#26123]
paddle什么矩阵求逆的方法，可以实现类似于`torch.inverse`的功能,(使用numpy会造成梯度丢失)

**Comment by ceci3** [comment]
https://www.paddlepaddle.org.cn/documentation/docs/zh/2.0-alpha/api_cn/tensor_cn/inverse_cn.html#paddle.inverse paddle2.0alpha有相应api

**Comment by sunjie97** [comment]
在aistudio中有方法使用吗？论文复现的时候需要用这个接口，但官方好像没有提供2.0的安装方式

**Comment by ceci3** [comment]
在aistudio的终端 pip install paddlepaddle_gpu==2.0.0a0 手动安装2.0试下
