### ISSUE TITLE
[需求]：镜像paddlepaddle/paddle 1.8.X(gpu)支持CentOS 7.X

### ISSUE THREAD

**Issue by Mr-Nineteen** [PaddlePaddle/Paddle#26125]
[需求]：
           镜像paddlepaddle/paddle 1.8.X(gpu)支持CentOS 7.X

**Comment by adaxiadaxi** [comment]
hi，同学您好，方便加我一下qq吗，我们可以在线联系沟通诉求，比较方便：876010422 主要是想了解下您的需求背景

**Comment by Mr-Nineteen** [comment]
@adaxiadaxi 加你了，同意一下，谢谢
