### ISSUE TITLE
【论文复现】UGATIT nn.BCEWithLogitsLoss() paddle提供同等的方法吗？

### ISSUE THREAD

**Issue by sincerevertigo** [PaddlePaddle/Paddle#26122]
如题

如果没有，一般怎么实现，可否受教。
谢谢。

**Comment by LielinJiang** [comment]
请参考这里：https://github.com/PaddlePaddle/PaddleGAN/blob/master/ppgan/modules/nn.py#L57-L69
![image](https://user-images.githubusercontent.com/50691816/89853268-8eda5380-dbc3-11ea-886e-412e3035f9fe.png)

**Comment by sincerevertigo** [comment]
@LielinJiang 
谢谢。
