### ISSUE TITLE
【论文复现】如何进行类似pytorch 的in-place 操作

### ISSUE THREAD

**Issue by zzz2010** [PaddlePaddle/Paddle#26124]
Hi,    请问如何对VarBase object 进行 in-place 操作？  例如， torch 的 tensor.clamp_(min,max)  是一个in-place 操作， 对应的paddle代码应该是什么呢？ 
是下面这样吗？
 tensor.set_value( fluid.layers.clip(tensor,min,max)  )

谢谢

**Comment by ceci3** [comment]
可以 tensor.set_value( fluid.layers.clip(tensor,min,max) ) 也可以直接assign(fluid.layers.clip(tensor,min,max), tensor)
