### ISSUE TITLE
【论文复现】[已解决(伪)] 关于SpectralNorm的问题

### ISSUE THREAD

**Issue by huochf** [PaddlePaddle/Paddle#26139]
在实现模型时，需要使用spectral归一化，需要对Linear或Conv2D中的参数矩阵进行归一化操作，请问有什么好的方法，下面是我想到的一种方案：
class LinearSNReLU(Linear):

    def __init__(self, in_channels, out_channels):
        super(LinearSNReLU, self).__init__(in_channels, out_channels)

    def forward(self, inputs):
        self.weight = fluid.layers.spectral_norm(self.weight)
        x = super.forward(inputs)
        x = fluid.layers.leaky_relu(x, alpha=0.2)

        return x
可是self.weight类型不对，如何获得模型的权重参数，并对其施加spectral norm操作呢？

**Comment by ceci3** [comment]
可以贴下报错信息吗？

**Comment by huochf** [comment]
> 可以贴下报错信息吗？

TypeError: assignment to parameter 'weight' should be of type Parameter or None, but got 'VarBase'

**Comment by huochf** [comment]
> 可以贴下报错信息吗？

它提示self.weight = fluid.layers.spectral_norm(self.weight)中weight类型不对，这里的self.weight是父类Linear的参数，

**Comment by liuxianyi** [comment]
我也有SpectralNorm的问题，在动图情况下，是如何输入weight_shape的值的，可以不以直接在上一层（Linear，Conv2D)直接推理出来？
![image](https://user-images.githubusercontent.com/33951338/89871852-ada01080-dbea-11ea-940a-9ce7ea497d02.png)

**Comment by huochf** [comment]
> 我也有SpectralNorm的问题，在动图情况下，是如何输入weight_shape的值的，可以不以直接在上一层（Linear，Conv2D)直接推理出来？

如果想省略weight_shape，可以像上面那样使用spectral_norm，

**Comment by ceci3** [comment]
目前不可以，现在动态图只能直接用SpectralNorm 这个接口，下个版本可能支持您上面的那种用法

**Comment by huochf** [comment]
@ceci3 我还想知道SpectralNorm怎么对Conv2D里面的参数做归一化，我在示例程序中找到的都是静态图的，文档中也没有给出具体实例。

**Comment by ceci3** [comment]
```
def spectral_norm(layer, name='weight', n_power_iterations=1, eps=1e-12, dim=0):
    # paddle.fluid.dygraph.Layer.register_forward_pre_hook

    def spectral_norm_pre_hook(layer, x):
        layer.weight = paddle.fluid.layers.spectral_norm(layer.weight, dim=dim, power_iters=n_power_iterations, eps=eps)
        # return x

    layer.register_forward_pre_hook(spectral_norm_pre_hook)

    return layer

spectral_norm(Conv2D)
```
先这样用吧.. 之前的SpectralNorm这个接口我也没看明白要怎么用..

**Comment by huochf** [comment]
@ceci3 我这就去试试，这个回答我很满意！！

**Comment by huochf** [comment]
> def spectral_norm(layer, name='weight', n_power_iterations=1, eps=1e-12, dim=0):
>     # paddle.fluid.dygraph.Layer.register_forward_pre_hook
> 
>     def spectral_norm_pre_hook(layer, x):
>         layer.weight = paddle.fluid.layers.spectral_norm(layer.weight, dim=dim, power_iters=n_power_iterations, eps=eps)
>         # return x
> 
>     layer.register_forward_pre_hook(spectral_norm_pre_hook)
> 
>     return layer
> 
> spectral_norm(Conv2D)
> 
> 先这样用吧.. 之前的SpectralNorm这个接口我也没看明白要怎么用..

我照着你写的这个方法，重写了上面的函数，但是仍然出现上面的错误，
TypeError: assignment to parameter 'weight' should be of type Parameter or None, but got 'VarBase'

我的具体代码如下：
def SpectralNorm(layer, name='weight', n_power_iterations=1, eps=1e-12, dim=0):
    # paddle.fluid.dygraph.Layer.register_forward_pre_hook

    def spectral_norm_pre_hook(layer, x):
        layer.weight = paddle.fluid.layers.spectral_norm(layer.weight, dim=dim, power_iters=n_power_iterations, eps=eps)
        # return x

    layer.register_forward_pre_hook(spectral_norm_pre_hook)

    return layer

class LinearSNReLU(fluid.dygraph.Layer):

    def __init__(self, in_channels, out_channels):
        super(LinearSNReLU, self).__init__()
        self.fc_sn = SpectralNorm(Linear(in_channels, out_channels))


    def forward(self, inputs):
        x = self.fc_sn(inputs)
        x = fluid.layers.leaky_relu(x, alpha=0.2)

        return x

我使用的环境是develop版，我记得楼下有人遇到类似的错误，是由于没有加with fluid.dygraph.guard导致的，可是我利用这个LinearSNReLU组建网络后，调用网络时添加了with语句。

**Comment by huochf** [comment]
@ceci3 麻烦能看下上面的错误吗，我仍然遇到了类型不对的错误。
你写的函数spectral_norm_pre_hook中layer.weight是<class 'paddle.fluid.framework.ParamBase'>类型的，但是spectral_norm函数输入的类型必须是Parameter，
我这里使用的是Develop版本。

**Comment by huochf** [comment]
@ceci3 我今天又重新审视了那个错误，错误在于无法对模块中的weight赋值，
我重写了带有spectral linear的函数，这次可以正确运行，
class LinearSNReLU(Linear):

    def __init__(self, in_channels, out_channels):
        super(LinearSNReLU, self).__init__(in_channels, out_channels)


    def forward(self, inputs):
        weight_sn = fluid.layers.spectral_norm(self.weight)
        x = fluid.layers.matmul(inputs, weight_sn)
        x = fluid.layers.leaky_relu(x, alpha=0.2)

        return x

我避开了对self.weight直接赋值，把weight剥离从模块中开，和inputs直接运算，唯一一点令我疑惑的是，这样会不会影响梯度backwards。希望能得到你的答复，主要是自己对Paddle内部的实现不了解。

**Comment by ceci3** [comment]
这样的话也可以，不会影响梯度的回传。上面这个``` layer.weight = paddle.fluid.layers.spectral_norm(layer.weight, dim=dim, power_iters=n_power_iterations, eps=eps)``` 这句话用set_value的方式的方式把spectral_norm返回的值赋值给layer.weight 也可以

**Comment by ceci3** [comment]
上面那种方法好像是有问题的，稍后 @LielinJiang 会给出正确用法

**Comment by sincerevertigo** [comment]
@ceci3 @LielinJiang 
坐等。。。

**Comment by liuxianyi** [comment]
> @ceci3 我今天又重新审视了那个错误，错误在于无法对模块中的weight赋值，
> 我重写了带有spectral linear的函数，这次可以正确运行，
> class LinearSNReLU(Linear):
> 
> ```
> def __init__(self, in_channels, out_channels):
>     super(LinearSNReLU, self).__init__(in_channels, out_channels)
> 
> 
> def forward(self, inputs):
>     weight_sn = fluid.layers.spectral_norm(self.weight)
>     x = fluid.layers.matmul(inputs, weight_sn)
>     x = fluid.layers.leaky_relu(x, alpha=0.2)
> 
>     return x
> ```
> 
> 我避开了对self.weight直接赋值，把weight剥离从模块中开，和inputs直接运算，唯一一点令我疑惑的是，这样会不会影响梯度backwards。希望能得到你的答复，主要是自己对Paddle内部的实现不了解。

按照你的方式，如果是对Conv2D 进行spectral_norm，会报错
![image](https://user-images.githubusercontent.com/33951338/90081592-501dd800-dd40-11ea-85d7-6aa131581c41.png)
这是我的代码：
```
class Conv2DSNReLU(fluid.dygraph.Conv2D):
    def __init__(self, num_channels, num_filters, filter_size, stride=1, padding=0):
        super(Conv2DSNReLU, self).__init__(num_channels, num_filters, filter_size, stride, padding)

    def forward(self, inputs):
        weight_sn = fluid.layers.spectral_norm(self.weight, dim=1)
        print(weight_sn.shape)
        print(inputs.shape)
        ########reshape？#########
        x = fluid.layers.matmul(inputs, weight_sn)
        x = fluid.layers.leaky_relu(x, alpha=0.2)

        return x
```
是不是需要在matmul上面加一个reshape啊

**Comment by huochf** [comment]
> @ceci3 我今天又重新审视了那个错误，错误在于无法对模块中的weight赋值，
> 我重写了带有spectral linear的函数，这次可以正确运行，
> class LinearSNReLU(Linear):
> def __init__(self, in_channels, out_channels):
>     super(LinearSNReLU, self).__init__(in_channels, out_channels)
> 
> 
> def forward(self, inputs):
>     weight_sn = fluid.layers.spectral_norm(self.weight)
>     x = fluid.layers.matmul(inputs, weight_sn)
>     x = fluid.layers.leaky_relu(x, alpha=0.2)
> 
>     return x
> 
> 我避开了对self.weight直接赋值，把weight剥离从模块中开，和inputs直接运算，唯一一点令我疑惑的是，这样会不会影响梯度backwards。希望能得到你的答复，主要是自己对Paddle内部的实现不了解。
> 
> 按照你的方式，如果是对Conv2D 进行spectral_norm，会报错
> 
> 这是我的代码：
> class Conv2DSNReLU(fluid.dygraph.Conv2D):
>     def __init__(self, num_channels, num_filters, filter_size, stride=1, padding=0):
>         super(Conv2DSNReLU, self).__init__(num_channels, num_filters, filter_size, stride, padding)
> 
>     def forward(self, inputs):
>         weight_sn = fluid.layers.spectral_norm(self.weight, dim=1)
>         print(weight_sn.shape)
>         print(inputs.shape)
>         ########reshape？#########
>         x = fluid.layers.matmul(inputs, weight_sn)
>         x = fluid.layers.leaky_relu(x, alpha=0.2)
> 
>         return x
> 
> 是不是需要在matmul上面加一个reshape啊

@liuxianyi Linear用matmul，Conv2D使用fluid.nn.functional.conv.conv2d(inputs, weights)

**Comment by deep-practice** [comment]
@LielinJiang 正确做法到底是啥？

**Comment by liuxianyi** [comment]
你的环境是2.0的吗，1.8.0没这个函数fluid.nn.functional.conv.conv2d(inputs, weights)

**Comment by huochf** [comment]
> 你的环境是2.0的吗，1.8.0没这个函数fluid.nn.functional.conv.conv2d(inputs, weights)

https://github.com/PaddlePaddle/Paddle/issues/26081#issue-675845774
参考这个，使用开发版，paddle1.8确实没这个函数。

**Comment by liuxianyi** [comment]
> > 你的环境是2.0的吗，1.8.0没这个函数fluid.nn.functional.conv.conv2d(inputs, weights)
> 
> [#26081 (comment)](https://github.com/PaddlePaddle/Paddle/issues/26081#issue-675845774)
> 参考这个，使用开发版，paddle1.8确实没这个函数。

dev版本有，但是dev版不能跑GPU啊，你aistudio不会报错 cudnn incompatiable bug？

**Comment by huochf** [comment]
> 你的环境是2.0的吗，1.8.0没这个函数fluid.nn.functional.conv.conv2d(inputs, weights)
> 
> #26081 (comment)
> 参考这个，使用开发版，paddle1.8确实没这个函数。
> 
> dev版本有，但是dev版不能跑GPU啊，你aistudio不会报错 cudnn incompatiable bug？

那。。会有一个办法，使用静态图，
def conv2d_spectral_norm(input,
                         num_filters=64,
                         filter_size=7,
                         stride=1,
                         stddev=0.02,
                         padding=0,
                         name="conv2d_spectral_norm",
                         norm=None,
                         activation_fn=None,
                         relufactor=0.0,
                         use_bias=False,
                         padding_type=None,
                         initial="normal",
                         is_test=False,
                         norm_affine=True):
    b, c, h, w = input.shape
    height = num_filters
    width = c * filter_size * filter_size
    helper = fluid.layer_helper.LayerHelper("conv2d_spectral_norm", **locals())
    dtype = helper.input_dtype()
    weight_param = fluid.ParamAttr(
        name=name + ".weight_orig",
        initializer=fluid.initializer.Normal(
            loc=0.0, scale=1.0),
        trainable=True)
    weight = helper.create_parameter(
        attr=weight_param,
        shape=(num_filters, c, filter_size, filter_size),
        dtype=dtype)
    weight_spectral_norm = fluid.layers.spectral_norm(
        weight, dim=0, name=name + ".spectral_norm")
    weight = weight_spectral_norm
    if use_bias:
        bias_attr = fluid.ParamAttr(
            name=name + "_b",
            initializer=fluid.initializer.Normal(
                loc=0.0, scale=1.0))
    else:
        bias_attr = False
    conv = conv2d_with_filter(
        input, weight, stride, padding, bias_attr=bias_attr, name=name)
    if norm is not None:
        conv = norm_layer(
            input=conv,
            norm_type=norm,
            name=name + "_norm",
            is_test=is_test,
            affine=norm_affine)
    if activation_fn == 'relu':
        conv = fluid.layers.relu(conv, name=name + '_relu')
    elif activation_fn == 'leaky_relu':
        conv = fluid.layers.leaky_relu(
            conv, alpha=relufactor, name=name + '_leaky_relu')
    elif activation_fn == 'tanh':
        conv = fluid.layers.tanh(conv, name=name + '_tanh')
    elif activation_fn == 'sigmoid':
        conv = fluid.layers.sigmoid(conv, name=name + '_sigmoid')
    elif activation_fn == None:
        conv = conv
    else:
        raise NotImplementedError("activation: [%s] is not support" %
                                  activation_fn)
    return conv

这是官方模型库中的代码。

**Comment by huochf** [comment]
```
def conv2d_spectral_norm(input,
                         num_filters=64,
                         filter_size=7,
                         stride=1,
                         stddev=0.02,
                         padding=0,
                         name="conv2d_spectral_norm",
                         norm=None,
                         activation_fn=None,
                         relufactor=0.0,
                         use_bias=False,
                         padding_type=None,
                         initial="normal",
                         is_test=False,
                         norm_affine=True):
    b, c, h, w = input.shape
    height = num_filters
    width = c * filter_size * filter_size
    helper = fluid.layer_helper.LayerHelper("conv2d_spectral_norm", **locals())
    dtype = helper.input_dtype()
    weight_param = fluid.ParamAttr(
        name=name + ".weight_orig",
        initializer=fluid.initializer.Normal(
            loc=0.0, scale=1.0),
        trainable=True)
    weight = helper.create_parameter(
        attr=weight_param,
        shape=(num_filters, c, filter_size, filter_size),
        dtype=dtype)
    weight_spectral_norm = fluid.layers.spectral_norm(
        weight, dim=0, name=name + ".spectral_norm")
    weight = weight_spectral_norm
    if use_bias:
        bias_attr = fluid.ParamAttr(
            name=name + "_b",
            initializer=fluid.initializer.Normal(
                loc=0.0, scale=1.0))
    else:
        bias_attr = False
    conv = conv2d_with_filter(
        input, weight, stride, padding, bias_attr=bias_attr, name=name)
    if norm is not None:
        conv = norm_layer(
            input=conv,
            norm_type=norm,
            name=name + "_norm",
            is_test=is_test,
            affine=norm_affine)
    if activation_fn == 'relu':
        conv = fluid.layers.relu(conv, name=name + '_relu')
    elif activation_fn == 'leaky_relu':
        conv = fluid.layers.leaky_relu(
            conv, alpha=relufactor, name=name + '_leaky_relu')
    elif activation_fn == 'tanh':
        conv = fluid.layers.tanh(conv, name=name + '_tanh')
    elif activation_fn == 'sigmoid':
        conv = fluid.layers.sigmoid(conv, name=name + '_sigmoid')
    elif activation_fn == None:
        conv = conv
    else:
        raise NotImplementedError("activation: [%s] is not support" %
                                  activation_fn)
    return conv
```

**Comment by Chemino** [comment]
我通过新建`fluid.dygraph.Conv2D`的子类，尝试实现包裹Spectral Norm的卷积层功能：
```
class SpectralNormConv2D(dygraph.Conv2D):
    def __init__(self, num_channels, num_filters, filter_size, stride=1, padding=0, param_attr=None, bias_attr=None, act=None):
        super(SpectralNormConv2D, self).__init__(num_channels=num_channels, num_filters=num_filters, filter_size=filter_size, stride=stride)

    def forward(self, x):
        SpectralNorm = dygraph.SpectralNorm(self.weight.shape)
        self.weight = SpectralNorm(dygraph.to_variable(self.weight))
        return super(SpectralNormConv2D, self).forward(x)
```
程序经测试可以跑通，但我并不确定这样做是否真的实现了Spectral Norm的功能。欢迎大家讨论

**Comment by saxon-zh** [comment]
统一使用这个Issue提供的方案吧，https://github.com/PaddlePaddle/Paddle/issues/26229#issuecomment-674106061
