### ISSUE TITLE
【论文复现】已解决 卷积层报错 TypeError: conv2d(): incompatible function arguments. The following argument types are supported:     1. (arg0: paddle::imperative::VarBase, arg1: paddle::imperative::VarBase, *args) -> paddle::imperative::VarBase

### ISSUE THREAD

**Issue by liuxianyi** [PaddlePaddle/Paddle#26133]
![image](https://user-images.githubusercontent.com/33951338/89857265-32306600-dbce-11ea-93b0-5e0970a9572b.png)

**Comment by ceci3** [comment]
麻烦贴下复现bug的代码，另外网络的实例化需要放在with fluid.dygraph.guard(): 或者fluid.enable_imperative()下面

**Comment by liuxianyi** [comment]
> 麻烦贴下复现bug的代码，另外网络的实例化需要放在with fluid.dygraph.guard(): 或者fluid.enable_imperative()下面

已解决，原因：实例化没有放在with fluid.dygraph.guard():

**Comment by ceci3** [comment]
那我先关掉这个issue了，如果有需要的话可以再打开~

**Comment by R132** [comment]
我出现相同错误的原因是因为：
对输入没有采用to_variable调用，比如to_variable(x)
可以参考
