### ISSUE TITLE
关于ARM64架构的编译问题

### ISSUE THREAD

**Issue by zhangmianhongni** [PaddlePaddle/Paddle#26140]
刚看了1.8.3版本的bug修复信息，有一条是关于飞腾ARM CPU的编译bug修复。
是不是可以理解为1.8.3版本的Paddle已经可以在ARM64架构下进行完整的编译和运行？

**Comment by jiweibo** [comment]
是的，已经在ARM 飞腾上验证过。

编译方式可参考  https://github.com/PaddlePaddle/Paddle/pull/25212

**Comment by zhangyaobo** [comment]
do you share how do it ,about compile and run

**Comment by ddzzfg** [comment]
经过测试，可以确定能在ARM的环境中运行
部分需要通过git的也可以切换回国内的镜像
![image](https://user-images.githubusercontent.com/25924459/89884810-a1bd4a00-dbfc-11ea-8bde-42fb75e1460c.png)
