### ISSUE TITLE
AIStudio的PaddlePaddle版本能更新到1.8.3吗

### ISSUE THREAD

**Issue by deep-practice** [PaddlePaddle/Paddle#26141]
现在版本是1.8.0 跑程序有点bug，自己pip install -U安装的说显卡驱动不匹配
出现的问题跟这个issue一样
 https://github.com/PaddlePaddle/Paddle/issues/25141

**Comment by liuxianyi** [comment]
> 现在版本是1.8.0 跑程序有点bug，自己pip install -U安装的说显卡驱动不匹配
> 出现的问题跟这个issue一样
> #25141

我上午跑2.0的时候也出现了 Cuda版本不满足的情况，而昨天没有问题，很玄学？

**Comment by deep-practice** [comment]
emmmm，那你还是比我幸运一点，我第一次就失败了。

**Comment by ceci3** [comment]
指定一下paddlepaddle安装的环境版本呢？

**Comment by weiexcelpro** [comment]
> #25141

请问是在1.8.0的环境下升级1.8.3吗?
我刚刚尝试了, 没有问题呀. 可否提供更详细的命令或截图
![image](https://user-images.githubusercontent.com/37108001/89967984-5307c280-dc85-11ea-9177-ebb3858a9e13.png)

**Comment by liuxianyi** [comment]
> > #25141
> 
> 请问是在1.8.0的环境下升级1.8.3吗?
> 我刚刚尝试了, 没有问题呀. 可否提供更详细的命令或截图
> ![image](https://user-images.githubusercontent.com/37108001/89967984-5307c280-dc85-11ea-9177-ebb3858a9e13.png)

你检查下
`
import paddle.fluid as fluid   `
`fluid.install_check.run_check()
`
看看是否验证成功，反正我是有问题的？

**Comment by weiexcelpro** [comment]
![image](https://user-images.githubusercontent.com/37108001/89969283-9283de00-dc88-11ea-909e-7ea8981fa340.png)

至少这两句没啥问题

**Comment by weiexcelpro** [comment]
想起来了, 安装完1.8.3 paddlepaddle-gpu之后, 需要立即重启执行器(右上角菜单里), 请问你执行过吗?

**Comment by deep-practice** [comment]
终端安装和Notebook安装有啥不一样？现在安装完倒是不报错了，但会提醒cudnn版本不对

**Comment by deep-practice** [comment]
WARNING: device: 0. The installed Paddle is compiled with CUDNN 7.6, but CUDNN version in your machine is 7.3, which may cause serious incompatible bug. Please recompile or reinstall Paddle with compatible CUDNN version.

**Comment by weiexcelpro** [comment]
.............嗯...............我们再检查一下cuDNN

**Comment by weiexcelpro** [comment]
> WARNING: device: 0. The installed Paddle is compiled with CUDNN 7.6, but CUDNN version in your machine is 7.3, which may cause serious incompatible bug. Please recompile or reinstall Paddle with compatible CUDNN version.

这个是跑什么代码出现的, 我们现在已经开始动手了. 但需要一个验证是否升级成功的脚本或代码sample

**Comment by deep-practice** [comment]
跑什么代码都一样哈，只要是通过pip install -U paddlepaddle-gpu升级到1.8.3，默认是1.8.0的环境
rsion: 10.0
W0813 12:29:52.090279   435 device_context.cc:260] device: 0, cuDNN Version: 7.3.
W0813 12:29:53.316025   435 device_context.h:155] WARNING: device: 0. The installed Paddle is compiled with CUDNN 7.6, but CUDNN version in your machine is 7.3, which may cause serious incompatible bug. Please recompile or reinstall Paddle with compatible CUDNN version.

**Comment by morgan-bc** [comment]
在 ~/.bashrc 里面把LD_LIBRARY_PATH，重新定义一遍，覆盖原来机器里面的定义，这样就可以用aistudio 里面自带的 cudnn7.6了
```
export LD_LIBRARY_PATH=/usr/local/cuda/lib64
```

**Comment by liuxianyi** [comment]
> 在 ~/.bashrc 里面把LD_LIBRARY_PATH，重新定义一遍，覆盖原来机器里面的定义，这样就可以用aistudio 里面自带的 cudnn7.6了
> 
> ```
> export LD_LIBRARY_PATH=/usr/local/cuda/lib64
> ```

我试了以下，把代码加了进去，依然不行啊

**Comment by morgan-bc** [comment]
我是在终端里面跑的，你要先运行 `source ~/.bashrc` 才行，如果你在notebook里运行，可能应该是这样
```
!export LD_LIBRARY_PATH=/usr/local/cuda/lib64 && \
python main.py
```

**Comment by deep-practice** [comment]
今天升级之后，又说cuda driver不对
