### ISSUE TITLE
MPI任务异常，部分pass缺失

### ISSUE THREAD

**Issue by zhangyong15** [PaddlePaddle/Paddle#2614]
总共训练50轮，从MPI日志上来看是成功产出50轮pass，但MPI任务报错
<img width="216" alt="2017-06-27 10 29 31" src="https://user-images.githubusercontent.com/22140712/27568311-8e805c32-5b23-11e7-9b60-da2337634970.png">
HADOOP的输出目录只有30轮，缺失部分pass
<img width="384" alt="2017-06-27 10 31 34" src="https://user-images.githubusercontent.com/22140712/27568354-e7f5809e-5b23-11e7-8a5f-14f34998ce86.png">

**Comment by zhangyong15** [comment]
train.log并无报错信息

**Comment by zhangyong15** [comment]
又一次出现了这个现象，模型训练成功，但是MPI返回错误

**Comment by gangliao** [comment]
@typhoonzero @jacquesqiao Any suggestion?

**Comment by typhoonzero** [comment]
output上传是MPI部分的问题了，我去问下MPI相关的负责人。

**Comment by zhangyong15** [comment]
有后续的进展么

**Comment by typhoonzero** [comment]
This is a more of internal cluster problem, closing this issue
