### ISSUE TITLE
【论文复现】UGATIT torch.optim.Adam parameters weight_decay

### ISSUE THREAD

**Issue by sincerevertigo** [PaddlePaddle/Paddle#26156]
pytroch源码
self.G_optim = torch.optim.Adam(itertools.chain(self.genA2B.parameters(), self.genB2A.parameters()), lr=self.lr, betas=(0.5, 0.999), weight_decay=self.weight_decay)

做了如下的移植，不知是否可以。

paddle
self.G_optim = fluid.optimizer.AdamOptimizer(learning_rate=self.lr, beta1=0.5, beta2=0.999, parameter_list=(self.genA2B.parameters(), self.genB2A.parameters()), regularization=fluid.regularizer.L2Decay(regularization_coeff=self.weight_decay))

主要不确定的点事，parameter_list 和惩罚项 是否能这么用。

谢谢。

**Comment by saxon-zh** [comment]
这个 @ceci3 会稍后进行回复。

**Comment by ceci3** [comment]
可以这么用

**Comment by sincerevertigo** [comment]
@ceci3  
2.0 版本，对应这个方法
fluid.regularizer.L2Decay(regularization_coeff=self.weight_decay)
是什么？
没找到。。。
谢谢。

**Comment by ceci3** [comment]
> @ceci3
> 2.0 版本，对应这个方法
> fluid.regularizer.L2Decay(regularization_coeff=self.weight_decay)
> 是什么？
> 没找到。。。
> 谢谢。

是的

**Comment by sincerevertigo** [comment]
@ceci3 
不好意思。
有点没看明白，可能是我说的不清楚。

2.0 没有这个的意思？
还是说用法一样？
我的paddle现在是2.0alpha版。
现在会报下面的错。

<img width="673" alt="image" src="https://user-images.githubusercontent.com/37995641/89922701-fe872780-dc31-11ea-90f9-8ab58a11d3a9.png">

谢谢。

**Comment by ceci3** [comment]
我本地没有复现出来，安装的2.0alpha的paddle，可以正常用
![image](https://user-images.githubusercontent.com/29245900/89974892-ec8ba000-dc96-11ea-96a9-12f798d6a2f3.png)

**Comment by sincerevertigo** [comment]
@ceci3 
卸载，重装了一遍paddle2.0 就可以了。
原因不明。。。
谢谢。

**Comment by sincerevertigo** [comment]
@ceci3 
self.G_optim = paddle.optimizer.AdamOptimizer(learning_rate=self.lr, beta1=0.5, beta2=0.999, parameter_list=(self.genA2B.parameters(), self.genB2A.parameters()), regularization=paddle.fluid.regularizer.L2Decay(regularization_coeff=self.weight_decay))
通过上面代码设置了， L2Decay。

运行的时候，报如下错误。
<img width="1035" alt="image" src="https://user-images.githubusercontent.com/37995641/89977294-6161d880-dc9d-11ea-98ca-cc44b8cf82e3.png">

**Comment by ceci3** [comment]
https://github.com/PaddlePaddle/models/blob/1bf7264771fb30b588c426e9c153f9b643256971/dygraph/mobilenet/utils/optimizer.py#L175 参考这里的用法，是不是哪里参数类型设置的不对

**Comment by sincerevertigo** [comment]
@ceci3 
pytroch 源码
itertools.chain(self.genA2B.parameters(), self.genB2A.parameters())

在paddle里，如何在一个优化器中设置多个网络参数？
parameter_list=fluid.io.chain(self.genA2B.parameters(), self.genB2A.parameters())
用了上面的方法，还是报错。

<img width="846" alt="image" src="https://user-images.githubusercontent.com/37995641/90041951-96514800-dcfc-11ea-9358-838411bc49e4.png">

**Comment by sincerevertigo** [comment]
@ceci3 
能帮忙看一下不。谢谢。

**Comment by sincerevertigo** [comment]
![image](https://user-images.githubusercontent.com/37995641/90591436-b52c6e80-e215-11ea-8bd3-4692ffe369cb.png)

红框中的实现能否帮忙看一下行不行。

**Comment by ceci3** [comment]
itertools.chain链接的用法在develop的paddle可以，其他版本不行，可以直接用+

**Comment by sincerevertigo** [comment]
谢谢！！！
