### ISSUE TITLE
使用train_from_dataset训练，获取的moment都是0

### ISSUE THREAD

**Issue by ameyais** [PaddlePaddle/Paddle#26151]
使用train_from_dataset训练时，想打印训练时的梯度和优化器计算的moment

我使用下面的方法获取梯度变量和moment变量，加在fetch_list中，使用adagrad训练
fc0_w_grad = fluid.default_main_program().global_block().var("fc_0.b_0@GRAD")
fc0_w_moment = fluid.default_main_program().global_block().var("fc_0.b_0_moment_0")

训练过程中发现，梯度可以正常获取，但是moment打印出来都是0，最后模型保存下来时，查看保存的moment又是有值的
请问这是什么原因呢？需要怎么获取训练中的moment呢？

**Comment by ceci3** [comment]
可以把"fc_0.b_0_moment_0" 放到fetch_list里面打印，这样打出来的是有值的
![image](https://user-images.githubusercontent.com/29245900/89897061-07b3cc80-dc11-11ea-8eaf-5d5742573f1f.png)

**Comment by ameyais** [comment]
> 可以把"fc_0.b_0_moment_0" 放到fetch_list里面打印，这样打出来的是有值的
> ![image](https://user-images.githubusercontent.com/29245900/89897061-07b3cc80-dc11-11ea-8eaf-5d5742573f1f.png)

你是用什么方式训练的呢？
我这边自己拿数据测试，使用exe.run(program, fetch_list=..)训练的话，是可以打出moment的值的，但是拿exe.train_from_dataset(program, fetch_list=...)训练的话，就打出来的moment都是0

**Comment by seiriosPlus** [comment]
是单机训练吗

**Comment by ameyais** [comment]
> 是单机训练吗

不是单机，是多机训练

**Comment by seiriosPlus** [comment]
1. 如果是多机的CPU训练， 即使用ParameterServer的场景：
多机训练的场景下， moment这些和优化器相关的参数不在当前节点存在或当前节点仅存在一个初始的值，不参与模型的训练与给嗯行。 

多机的数据并行模式会将优化相关的计算图拆分至远端， 因此训练节点在训练过程中无法从当前节点获取到正确的优化器相关的参数。

模型在保存时，会主动从远端拉取最新的参数，保存下来。

如果需要在训练过程中获取这些参数：
1. 多保存（当前可以简单应用的方案）
2. 自行组网从远端拉取相应的参数(使用难度较大)

2.如果是多机的GPU训练， 即使用Collective的场景：
理论上每个节点上是可以取到正确的参数的， 如果是此情况，我们需要具体看一下是否有配置错误.

**Comment by ameyais** [comment]
嗯是第一种情况，多机cpu训练
了解了，谢谢解答
