### ISSUE TITLE
【论文复现】UGATIT torch.utils.data.Dataset 在paddle里是否有替代的类

### ISSUE THREAD

**Issue by sincerevertigo** [PaddlePaddle/Paddle#26159]
pytroch源码
class DatasetFolder(data.Dataset):
    def __init__(self, root, loader, extensions, transform=None, target_transform=None):

这个Dataset在paddle里面用哪个类可以代替吗？
用下面这个可以吗？
paddle.fluid.dataloader.Dataset

**Comment by ceci3** [comment]
没有替代，https://www.paddlepaddle.org.cn/documentation/docs/zh/api_cn/io_cn/DataLoader_cn.html#dataloader 查看dataloader的用法，https://github.com/PaddlePaddle/PaddleGAN/blob/master/ppgan/datasets/image_folder.py#L40 参考这里在paddle中使用 类似DatasetFolder的接口

**Comment by liuxianyi** [comment]
可以借鉴百度的一个repo，里面提高高级api [链接](https://github.com/PaddlePaddle/hapi)
![image](https://user-images.githubusercontent.com/33951338/89904914-1358c080-dc1c-11ea-91c9-a1a88c817e11.png)

**Comment by sincerevertigo** [comment]
@ceci3 @liuxianyi 

paddle 2.0 版本
在引入包的时候，报错。

![image](https://user-images.githubusercontent.com/37995641/89928867-05666800-dc3b-11ea-90d6-a77ad34c5d72.png)

**Comment by sincerevertigo** [comment]
谢谢！！！
