### ISSUE TITLE
【论文复现】UGATIT transforms RandomCrop ToTensor

### ISSUE THREAD

**Issue by sincerevertigo** [PaddlePaddle/Paddle#26155]
![image](https://user-images.githubusercontent.com/37995641/89881898-ab44b300-dbf8-11ea-83e1-8f93bd87c223.png)
使用了 2.0 beta版的paddle
https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/beginners_guide/hapi.html#transform
参考了上面的链接，似乎，这两个没有提供。 

这样的话，要怎样实现这个pipeline，能否提供个思路？

**Comment by ceci3** [comment]
https://github.com/PaddlePaddle/PaddleGAN/blob/master/ppgan/datasets/transforms/transforms.py#L4 RandomCrop可以参考这里，ToTensor Paddle里是不需要的

**Comment by sincerevertigo** [comment]
@ceci3 
谢谢！！！

RandomCrop,之前倒是也实现过，但肯定没有这个实现的漂亮。
我的理解是改成下面这样就OK了吧。

train_transform = transforms.Compose([
            transforms.RandomHorizontalFlip(),
            transforms.Resize((self.img_size + 30, self.img_size+30)),
            **RandomCrop(self.img_size),**
            transforms.Normalize(mean=(0.5, 0.5, 0.5), std=(0.5, 0.5, 0.5))
        ])
        test_transform = transforms.Compose([
            transforms.Resize((self.img_size, self.img_size)),
            transforms.Normalize(mean=(0.5, 0.5, 0.5), std=(0.5, 0.5, 0.5))
        ])

**Comment by ceci3** [comment]
是的

**Comment by sincerevertigo** [comment]
@ceci3 
通过cv2读入了一张图片，jpg形式的。
cv2.imread(path)

然后，进行变换的时候，报了下面的错。
是有什么设置不够吗？
谢谢。

training start !
fail to perform transform [<paddle.incubate.hapi.vision.transforms.transforms.Normalize object at 0x13a3dc090>] with error: operands could not be broadcast together with shapes (286,286,3) (3,1,1)  and stack:
Traceback (most recent call last):
  File "/Users/q3-wang/opt/anaconda3/lib/python3.7/site-packages/paddle/incubate/hapi/vision/transforms/transforms.py", line 97, in __call__
    data = f(data)
  File "/Users/q3-wang/opt/anaconda3/lib/python3.7/site-packages/paddle/incubate/hapi/vision/transforms/transforms.py", line 509, in __call__
    return (img - self.mean) / self.std
ValueError: operands could not be broadcast together with shapes (286,286,3) (3,1,1) 

2020-08-12 14:24:11,997-WARNING: DataLoader reader thread raised an exception.
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/Users/q3-wang/opt/anaconda3/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/Users/q3-wang/opt/anaconda3/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/q3-wang/opt/anaconda3/lib/python3.7/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 169, in _thread_loop
    six.reraise(*sys.exc_info())
  File "/Users/q3-wang/opt/anaconda3/lib/python3.7/site-packages/six.py", line 703, in reraise
    raise value
  File "/Users/q3-wang/opt/anaconda3/lib/python3.7/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 145, in _thread_loop
    batch = [self._dataset[i] for i in indices]
  File "/Users/q3-wang/opt/anaconda3/lib/python3.7/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 145, in <listcomp>
    batch = [self._dataset[i] for i in indices]
  File "/Users/q3-wang/Desktop/UGATIT-pytorch-paddle/dataset.py", line 69, in __getitem__
    sample = self.transform(sample)
  File "/Users/q3-wang/opt/anaconda3/lib/python3.7/site-packages/paddle/incubate/hapi/vision/transforms/transforms.py", line 102, in __call__
    raise e
  File "/Users/q3-wang/opt/anaconda3/lib/python3.7/site-packages/paddle/incubate/hapi/vision/transforms/transforms.py", line 97, in __call__
    data = f(data)
  File "/Users/q3-wang/opt/anaconda3/lib/python3.7/site-packages/paddle/incubate/hapi/vision/transforms/transforms.py", line 509, in __call__
    return (img - self.mean) / self.std
ValueError: operands could not be broadcast together with shapes (286,286,3) (3,1,1) 

Traceback (most recent call last):
  File "/Users/q3-wang/Desktop/UGATIT-pytorch-paddle/main.py", line 84, in <module>
    main()
  File "/Users/q3-wang/Desktop/UGATIT-pytorch-paddle/main.py", line 76, in main
    gan.train()
  File "/Users/q3-wang/Desktop/UGATIT-pytorch-paddle/UGATIT.py", line 234, in train
    for i, real_A in enumerate(self.trainA_loader):
  File "/Users/q3-wang/Desktop/UGATIT-pytorch-paddle/dataloader.py", line 81, in __iter__
    for i, data in enumerate(self.dataloader):
  File "/Users/q3-wang/opt/anaconda3/lib/python3.7/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 185, in __next__
    return self._reader.read_next_var_list()
paddle.fluid.core_avx.EnforceNotMet: 


C++ Call Stacks (More useful to developers):

0   std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > paddle::platform::GetTraceBackString<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&>(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, char const*, int)
1   paddle::operators::reader::BlockingQueue<std::__1::vector<paddle::framework::LoDTensor, std::__1::allocator<paddle::framework::LoDTensor> > >::EnforceNotKilled()
2   paddle::operators::reader::BlockingQueue<std::__1::vector<paddle::framework::LoDTensor, std::__1::allocator<paddle::framework::LoDTensor> > >::Receive(std::__1::vector<paddle::framework::LoDTensor, std::__1::allocator<paddle::framework::LoDTensor> >*)
3   paddle::operators::reader::PyReader::ReadNext(std::__1::vector<paddle::framework::LoDTensor, std::__1::allocator<paddle::framework::LoDTensor> >*)
4   std::__1::__packaged_task_func<std::__1::__bind<paddle::operators::reader::BufferedReader::ReadAsync(unsigned long)::$_0>, std::__1::allocator<std::__1::__bind<paddle::operators::reader::BufferedReader::ReadAsync(unsigned long)::$_0> >, unsigned long ()>::operator()()
5   std::__1::packaged_task<unsigned long ()>::operator()()
6   ThreadPool::ThreadPool(unsigned long)::'lambda'()::operator()() const
7   void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, ThreadPool::ThreadPool(unsigned long)::'lambda'()> >(void*)


Error Message Summary:

Error: Blocking queue is killed because the data reader raises an exception
  [Hint: Expected killed_ != true, but received killed_:1 == true:1.] at (/home/teamcity/work/ef54dc8a5b211854/paddle/fluid/operators/reader/blocking_queue.h:141)

**Comment by ceci3** [comment]
h error: operands could not be broadcast together with shapes (286,286,3) (3,1,1)  你这个shape不对吧

**Comment by sincerevertigo** [comment]
@ceci3 

我就是读了一张图片，然后就给了transforms，进行变换。
cv2.imread(path)
之后还需要调整什么吗？
我看文档上似乎也没做什么调整。

![image](https://user-images.githubusercontent.com/37995641/89982514-7c861580-dca8-11ea-9391-576699ae6be0.png)

**Comment by sincerevertigo** [comment]
@ceci3 
感觉是参数的问题。
我试验了官方的代码，可以通过。

**Comment by sincerevertigo** [comment]
@ceci3 

测试结果
train_transform = transforms.Compose([
            transforms.RandomHorizontalFlip(),
            transforms.Resize(size=(self.img_size + 30))
        ])
这两个是可以的。正常变换。

train_transform = transforms.Compose([
            transforms.RandomHorizontalFlip(),
            transforms.Resize(size=(self.img_size + 30)),
            transforms.Normalize(mean=(0.5, 0.5, 0.5), std=(0.5, 0.5, 0.5))
        ])
加上最后那个Normalize就不行了。

Bug？
或者说，在送入最后一个变换的时候，需要reshape？

**Comment by ceci3** [comment]
https://github.com/PaddlePaddle/PaddleGAN/blob/master/ppgan/datasets/base_dataset.py#L95 可以参考下示例代码的写法

**Comment by sincerevertigo** [comment]
多谢，提供代码。
找到问题了。

> https://github.com/PaddlePaddle/PaddleGAN/blob/master/ppgan/datasets/transforms/transforms.py#L4 RandomCrop可以参考这里，ToTensor Paddle里是不需要的

ToTensor paddle的Transforms里面没有，
需要加入下面这个。
transforms.Permute(to_rgb=True),
然后，shape就对上了。

谢谢。

**Comment by GuoQuanhao** [comment]
这是什么版本的paddle，我出现了以下错误，告知我没有这些操作
```python
import paddle
import paddle.fluid as fluid
from PIL import Image
import numpy as np
import cv2

import paddle.incubate.hapi.vision.transforms as transforms


train_transform = transforms.Compose([transforms.RandomHorizontalFlip(),
                                     transforms.Resize(size=(self.img_size + 30)),
                                     transforms.Normalize(mean=(0.5, 0.5, 0.5), std=(0.5, 0.5, 0.5))
                                    ])
```
```
AttributeError                            Traceback (most recent call last)
<ipython-input-9-8b47529f4001> in <module>
----> 1 train_transform = transforms.Compose([transforms.RandomHorizontalFlip(),
      2                                      transforms.Resize(size=(self.img_size + 30)),
      3                                      transforms.Normalize(mean=(0.5, 0.5, 0.5), std=(0.5, 0.5, 0.5))
      4                                     ])

AttributeError: module 'paddle.incubate.hapi.vision.transforms' has no attribute 'Compose'
```
我使用的paadle1.8.3
