### ISSUE TITLE
gather的使用与文档不符

### ISSUE THREAD

**Issue by mamingjie-China** [PaddlePaddle/Paddle#26153]
https://www.paddlepaddle.org.cn/documentation/docs/zh/api_cn/layers_cn/gather_cn.html#gather ，在Paddle1.8.2版本中，gather的参数描述中，index为rank为1，但给出的代码示例中，index的shape=[-1, 1]，有点矛盾，实测gather仅支持1维的index输入，怀疑是文档有问题。另外，想问一下，PaddlePaddle的gather与TF和Pytorch并没有对齐，是否近期有计划对齐？
![image](https://user-images.githubusercontent.com/52770436/89880645-0e354a80-dbf7-11ea-8834-d144afb15ab6.png)
![image](https://user-images.githubusercontent.com/52770436/89880666-14c3c200-dbf7-11ea-8301-5028c1c4cfa6.png)

**Comment by ForFishes** [comment]
确实文档有问题，index的rank应该为1。近期没有和pytorch、tf对齐计划。文档我提个pr修复一下。
