### ISSUE TITLE
【论文复现】UGATIT 关于 pytroch的Parameter 

### ISSUE THREAD

**Issue by sincerevertigo** [PaddlePaddle/Paddle#26157]
<img width="502" alt="image" src="https://user-images.githubusercontent.com/37995641/89888106-fdd69d00-dc01-11ea-9178-32d6f3fadd14.png">
想要移植上面的图层实例归一化类。

Parametter这个paddle形式的话，要怎么处理？
下面这种可以吗？
self.rho = fluid.layers.create_parameter(fluid.Tensor(1, num_features, 1, 1))

谢谢。

**Comment by ceci3** [comment]
self.rho = fluid.layers.create_parameter(shape=(1, num_features, 1, 1),dtype='float32')就可以了，可以参考 https://www.paddlepaddle.org.cn/documentation/docs/zh/api_cn/layers_cn/create_parameter_cn.html#create-parameter 的用法

**Comment by chunfeng0301** [comment]
> self.rho = fluid.layers.create_parameter(shape=(1, num_features, 1, 1),dtype='float32')就可以了，可以参考 https://www.paddlepaddle.org.cn/documentation/docs/zh/api_cn/layers_cn/create_parameter_cn.html#create-parameter 的用法

如何讲一个定义好的ndarray变成paddle可学习参数呢，如下面：
t=fluid.Tensor()
aaa = np.array([[[[-0.5,0,0.5]]]]).astype("float32").repeat(32**2,1)
aaa = np.reshape(aaa,[32,32,1,3])
t.set(aaa,fluid.CPUPlace())

如何将t变成layer中可学习参数

**Comment by sincerevertigo** [comment]
@ceci3 
![image](https://user-images.githubusercontent.com/37995641/90125924-686c1200-dd95-11ea-8392-b18764c73975.png)
Parameter的定义，用了如下方式。
`self.rho = paddle.framework.create_parameter(shape=(1, num_features, 1, 1), dtype='float32')
        self.gamma = paddle.framework.create_parameter(shape=(1, num_features, 1, 1), dtype='float32')
        self.beta = paddle.framework.create_parameter(shape=(1, num_features, 1, 1), dtype='float32')`

fill操作
`self.rho = paddle.tensor.fill_constant(shape=(1, num_features, 1, 1), dtype='float32', value=0)`
这个会报错。
TypeError: assignment to parameter 'rho' should be of type Parameter or None, but got 'VarBase'

要转成numpy去操作吗？能够提供个思路，谢谢。
