### ISSUE TITLE
【论文复现】2.0为啥不能使用GPU 

### ISSUE THREAD

**Issue by liuxianyi** [PaddlePaddle/Paddle#26167]
# 错误日志
![image](https://user-images.githubusercontent.com/33951338/89904387-70a04200-dc1b-11ea-9996-5e9324036a88.png)
# CUDA版本
![image](https://user-images.githubusercontent.com/33951338/89904466-8ca3e380-dc1b-11ea-9391-60817d8e3fd7.png)

**Comment by ceci3** [comment]
```
import paddle.fluid as fluid
fluid.install_check.run_check()
```
用这种方式检查下gpu安装是否有问题。另外1.8没有问题吗？
