### ISSUE TITLE
【论文复现】UGATIT 学习率更新？

### ISSUE THREAD

**Issue by sincerevertigo** [PaddlePaddle/Paddle#26160]
![image](https://user-images.githubusercontent.com/37995641/89890178-7ee36380-dc05-11ea-8633-8eaa58d9c884.png)
pytroch源码里，在训练开始的时候，根据参数操作了一下，优化器的学习率。

再用paddle复现的时候，这块该怎么实现？能否提供一下思路。

谢谢。

**Comment by ceci3** [comment]
https://github.com/PaddlePaddle/PaddleGAN/blob/master/ppgan/solver/lr_scheduler.py#L9 学习率更新可以参考这里。

**Comment by sincerevertigo** [comment]
谢谢！！！
