### ISSUE TITLE
【论文复现】paddle.nn.InstanceNorm在GPU下运行报错

### ISSUE THREAD

**Issue by liuxianyi** [PaddlePaddle/Paddle#26168]
# 错误日志
![image](https://user-images.githubusercontent.com/33951338/89909418-9fb9b200-dc21-11ea-893d-1803928fe3a3.png)
# 代码
![image](https://user-images.githubusercontent.com/33951338/89909641-e1e2f380-dc21-11ea-84ce-645ca2ea2fd4.png)

**Comment by ceci3** [comment]
cudnn版本应该需要升级，上面有warning吗？

**Comment by liuxianyi** [comment]
> cudnn版本应该需要升级，上面有warning吗？
![image](https://user-images.githubusercontent.com/33951338/89960440-a1ab6180-dc71-11ea-966d-7f12ea9961c0.png)

那aistudio可以更新cudnn版本吗 @ceci3

**Comment by ceci3** [comment]
aistudio上的cudnn已经是7.6了，不需要升级

**Comment by weiexcelpro** [comment]
> > cudnn版本应该需要升级，上面有warning吗？
> > ![image](https://user-images.githubusercontent.com/33951338/89960440-a1ab6180-dc71-11ea-966d-7f12ea9961c0.png)
> 
> 那aistudio可以更新cudnn版本吗 @ceci3

Hi 我是AIStudio的PM. AIStudio的不同Paddle环境下的镜像是略有不同的. Paddle1.8.0对应的镜像, 其中cuDNN是7.6.5. 
![image](https://user-images.githubusercontent.com/37108001/89967354-d2949200-dc83-11ea-9a78-d14c48f40f8f.png)

您可以重新编辑项目属性, 以更换镜像
![image](https://user-images.githubusercontent.com/37108001/89967463-18e9f100-dc84-11ea-9cc7-e995f6de2647.png)

**Comment by liuxianyi** [comment]
我现在就是1.8.0的框架，但是依然显示cudnn是7.3版本的。如果我想要切换CUDA的版本，我该怎么操作呢？求指教！ @weiexcelpro

**Comment by weiexcelpro** [comment]
> 我现在就是1.8.0的框架，但是依然显示cudnn是7.3版本的。如果我想要切换CUDA的版本，我该怎么操作呢？求指教！ @weiexcelpro

辛苦执行一下这个命令再截个图? 
cat /usr/local/cuda/include/cudnn.h | grep CUDNN_MAJOR -A 2

**Comment by liuxianyi** [comment]
![image](https://user-images.githubusercontent.com/33951338/89970624-d0363600-dc8b-11ea-8921-8fb19eefda39.png)
这个是截图，目前我用的是paddle的develop版本

**Comment by weiexcelpro** [comment]
嗯, 好奇怪, 我们再深入查看一下.

**Comment by liuxianyi** [comment]
> 嗯, 好奇怪, 我们再深入查看一下.
可以切换CUDA的版本吗，如何切换呢，我想试试10.0？

**Comment by weiexcelpro** [comment]
> > 嗯, 好奇怪, 我们再深入查看一下.
> > 可以切换CUDA的版本吗，如何切换呢，我想试试10.0？

不能, CUDA版本是跟随服务器硬件的, AIStudio自己都升不动. 或说AIStudio自己想升级到CUDA10都需要非常大的成本.

**Comment by liuxianyi** [comment]
> > > 嗯, 好奇怪, 我们再深入查看一下.
> > > 可以切换CUDA的版本吗，如何切换呢，我想试试10.0？
> 
> 不能, CUDA版本是跟随服务器硬件的, AIStudio自己都升不动. 或说AIStudio自己想升级到CUDA10都需要非常大的成本.

那现在情况就是2.0和dev的GPU版本都不能在aistudio上运行了呗？

**Comment by weiexcelpro** [comment]
> > > > 嗯, 好奇怪, 我们再深入查看一下.
> > > > 可以切换CUDA的版本吗，如何切换呢，我想试试10.0？
> > 
> > 
> > 不能, CUDA版本是跟随服务器硬件的, AIStudio自己都升不动. 或说AIStudio自己想升级到CUDA10都需要非常大的成本.
> 
> 那现在情况就是2.0和dev的GPU版本都不能在aistudio上运行了呗？

如果是需要升级cuDNN的, 我们可以去检查并升级. 如果是一定需要CUDA10的, 完全不能跑

**Comment by liuxianyi** [comment]
嗯，好的，如果升级成功后（dev 可以用 gpu），麻烦通知一下，谢谢，辛苦了！ @weiexcelpro

**Comment by OxInsky** [comment]
> > > > > 嗯, 好奇怪, 我们再深入查看一下.
> > > > > 可以切换CUDA的版本吗，如何切换呢，我想试试10.0？
> > > 
> > > 
> > > 不能, CUDA版本是跟随服务器硬件的, AIStudio自己都升不动. 或说AIStudio自己想升级到CUDA10都需要非常大的成本.
> > 
> > 
> > 那现在情况就是2.0和dev的GPU版本都不能在aistudio上运行了呗？
> 
> 如果是需要升级cuDNN的, 我们可以去检查并升级. 如果是一定需要CUDA10的, 完全不能跑

能不能再基础的系统环境中利用conda创建一个env，在env里用conda安装cuda10.0 和cudnn，这个操作我试过，好像可以，cuda就相当于一个编译好的库，可以直接调用！

**Comment by saxon-zh** [comment]
参见AIStudio的升级公告：
1.	用户自行安装1.8.3 遭遇cuDNN异常问题. 
解决方案已经开发完成, 待上线. 
在解决之前, 您可以手动执行命令来解决该问题.
export LD_LIBRARY_PATH=/usr/local/cuda-9.2/lib64:$LD_LIBRARY_PATH
