### ISSUE TITLE
安装飞桨的时候显示安装成功了，但是python测试的时候提示只能使用一块卡。

### ISSUE THREAD

**Issue by daiyuanm** [PaddlePaddle/Paddle#26176]
- 问题：PP安装成功，但是用python测试的时候提示只能使用一块卡。如图：
![image](https://user-images.githubusercontent.com/67545374/89966432-b5f75a80-dc81-11ea-9cce-47b611160475.png)

- 版本、环境信息：
    1）PaddlePaddle版本：1.8.3
    2）CPU：Intel(R) Core(TM) i9-9920X CPU @ 3.50GHz
    3）GPU：两块2080TI，CUDA版本10.2.89，CUDNN是7605
    4）系统环境：ubuntu18.04，python3.6.9

- 安装方式信息：
1）pip安装/docker安装         
- 问题描述：按照步骤安装PP，其余没问题，python测试的时候提示只能使用一块卡。NCCL也重装了一遍，还是存在问题。

![image](https://user-images.githubusercontent.com/67545374/89966750-711ff380-dc82-11ea-88fc-80a7ca0363f4.png)

**Comment by sunxl1988** [comment]
你是怎么安装的？
编译安装开启-DWITH_DISTRIBUTE=ON，pip安装找对应的dist版本

**Comment by daiyuanm** [comment]
> 你是怎么安装的？
> 编译安装开启-DWITH_DISTRIBUTE=ON，pip安装找对应的dist版本
我是用的pip安装： pip install paddlepaddle-gpu

**Comment by daiyuanm** [comment]
> 你是怎么安装的？
> 编译安装开启-DWITH_DISTRIBUTE=ON，pip安装找对应的dist版本

我用的PIP安装： pip install paddlepaddle-gpu

**Comment by FDInSky** [comment]
export CUDA_VISIBLE_DEVICES=... 你的这个环境变量怎么设置的？

**Comment by daiyuanm** [comment]
> export CUDA_VISIBLE_DEVICES=... 你的这个环境变量怎么设置的？

安装的时候也要设置这个？我在跑代码的时候会设置export CUDA_VISIBLE_DEVICES=0，代码可以正常运行
