### ISSUE TITLE
Redesign of dims_ in Tensor

### ISSUE THREAD

**Issue by reyoung** [PaddlePaddle/Paddle#2617]
`Dim<N>` and `DDim` have two advantages:

1. Checking Rank during compile time.
2. The memory of dims are static allocation, not dynamic allocation as `std::vector`.

## Checking Rank

The tensor should be like this

```cpp
template <size_t Rank>
class Tensor {
 public:
  Dim<Rank> dims_;
};
```

So, the different rank of a tensor is different type. Then we use `Variable::Get<Tensor<2>>()` to get a matrix. If the vairable is not typed `Tensor<2>`, then an error occurs.

But we do not want to have template argument now. Our tensor is like

```cpp
class Tensor {
 public:
  DDim dims_;
};
```

then we cannot use type to check Tensor's rank, i.e., we cannot use the major advantage of `Dim<N>`.

## Static Allocation

`Dim<N>` and `DDim` are allocated in once, not like `std::vector` has a `growth` memory. `std::vector` is very slow when memory needs realloc, but `DDim` and `Dim<N>` do have this issue.

However, `DDim` is a `boost::variant`. `sizeof(DDim)` is as large as the maximum rank that Paddle supports. The `sizeof(DDim)` is `48` now, can hold 12 integers. In the neural network, most of tensors' rank is less than 5.

## Simpler solution

Here, I propose two solutions, which could simplify `Dim<N>` and `DDim` design.

1. Just use a `constexpr size_t MAX_RANK=12;` and each tensor holds a variable `size_t dims_[MAX_RANK];`. The advantages of this design and `DDim` are same, static allocation. The disadvantage of this design is we limit our tensor's rank less than 13.

2. Use the `boost::small_vector<size_t, 5> dims_` to represent dims. [`boost::small_vector`](http://www.boost.org/doc/libs/1_60_0/doc/html/boost/container/small_vector.html) is a vector-like container optimized for the case when it contains few elements. If rank is less than 5, dims_ is static allocation at once. Otherwise, it just likes a plain `std::vector`.

Maybe we should change our `dim` design?

**Comment by QiJune** [comment]
I think that take rank as a template parameter of class tensor is acceptable. And Tensor in Eigen also take int rank as template parameter. 
If so, tensor with different rank is actually different class. And we can define a global method reshape to transform tensor.

**Comment by wangkuiyi** [comment]
I have question: how can we define a `make_dim`, so that `make_dim(10, 10, 10)` returns a type `Dim<3>`, which represents a 10x10x10 tensor?

**Comment by wangkuiyi** [comment]
@reyoung suggested that `std::vector<size_t> dims = {10, 10, 10}` can do similar work as `make_dim`. How about we start from 

```cpp
class Tensor {
 public:
  typedef std::vector<size_t> Dim;
...
};
```

and we can change in the future if this typedef is not enough.

**Comment by reyoung** [comment]
> how can we define a make_dim, so that make_dim(10, 10, 10) returns a type Dim<3>, which represents a 10x10x10 tensor?

Maybe we could just use `std::vector<size_t>` as our dimension type. If tensor holds a `DDim`, `std::vector` and `DDim` are both checkings dimension rank in runtime. It seems that it is no need for `Dim<N>` template now.

For optimize memory, we could

```cpp
std::vector<size_t> MakeDims(std::initialize_list<size_t> dim) {
  std::vector<size_t> retv;
  retv.reserve(std::max(5, dim.size()));
  // copy buf to retv here
  return retv;
}
```

and not use `boost::small_vector`

**Comment by wangkuiyi** [comment]
It seems that the assignment between `std::vector` objects would have to call malloc and would be low efficient, so there comes `std::array`.

**Comment by reyoung** [comment]
Closed because `DDim` has been added. Just use `DDim` for now.
