### ISSUE TITLE
【论文复现】UGATIT 关于fill_ 

### ISSUE THREAD

**Issue by sincerevertigo** [PaddlePaddle/Paddle#26173]
pytroch 源码
self.rho = Parameter(torch.Tensor(1, num_features, 1, 1))
self.rho.data.fill_(0.9)

这里的fill操作，在paddle有等价的方法吗？ paddle 2.0版本
要转成np操作？

谢谢。

**Comment by ceci3** [comment]
直接用Constant方式初始化，或者用numpy先定义好一个arrry，用NumpyArrayInitializer 初始化都可以

**Comment by sincerevertigo** [comment]
@ceci3 
谢谢！
