### ISSUE TITLE
PALM已经训练过的模型，有新增样本了怎么继续训练

### ISSUE THREAD

**Issue by yeguang1991** [PaddlePaddle/Paddle#26175]
![image](https://user-images.githubusercontent.com/66579493/89965549-b131a700-dc7f-11ea-9277-4d0d09b057f2.png)
我尝试修改这个参数，但是这样训练之后预测的准确率下降了

**Comment by sunxl1988** [comment]
resume训练时，一般情况要调整学习率的，可以多做几组实验

**Comment by yeguang1991** [comment]
> resume训练时，一般情况要调整学习率的，可以多做几组实验

学习率怎么调整
