### ISSUE TITLE
【论文复现】如何copy 一个模型

### ISSUE THREAD

**Issue by zzz2010** [PaddlePaddle/Paddle#26174]
Hi,   请问如何做到类似 pytorch 中 copy.deepcopy(model)  的效果呢？  就是对 dygraph.layers.Layer 对象进行复制。

谢谢

**Comment by FDInSky** [comment]
请具体描述你的使用场景

**Comment by zzz2010** [comment]
具体场景就是starGAN v2 中：
https://github.com/clovaai/stargan-v2/blob/2a74f3dcd7ad3d1f7f018e7d97bd7622787acc16/core/model.py#L287
 
def build_model(args):
    generator = Generator(args.img_size, args.style_dim, w_hpf=args.w_hpf)
    mapping_network = MappingNetwork(args.latent_dim, args.style_dim, args.num_domains)
    style_encoder = StyleEncoder(args.img_size, args.style_dim, args.num_domains)
    discriminator = Discriminator(args.img_size, args.num_domains)
    generator_ema = copy.deepcopy(generator)
    mapping_network_ema = copy.deepcopy(mapping_network)
    style_encoder_ema = copy.deepcopy(style_encoder) 

直接copy.deepcopy(dygraph.layers.Layer) 是不行的， 有TypeError: can't pickle XXX objects
谢谢

**Comment by FDInSky** [comment]
你可以在声明一个Generator，generator_ema = Generator(args.img_size, args.style_dim, w_hpf=args.w_hpf)

**Comment by rical730** [comment]
请问是否可以实现 `copy.deepcopy(dygraph.layers.Layer)` 这个功能呢？模型复制用起来还是比较顺手的，用户体验更好。

**Comment by rical730** [comment]
目前在Paddle2.0rc0版本里也没办法直接deepcopy模型

```
import paddle
from copy import deepcopy

a = paddle.nn.Layer()
b = deepcopy(a)
```

TypeError: can't pickle Layer objects

**Comment by raindrops2sea** [comment]
Try to fix this in 2.0 @phlrain

**Comment by phlrain** [comment]
> Try to fix this in 2.0 @phlrain

Get it.

**Comment by phlrain** [comment]
> Try to fix this in 2.0 @phlrain

OK... working on it.

**Comment by zhwesky2010** [comment]
> 请问是否可以实现 `copy.deepcopy(dygraph.layers.Layer)` 这个功能呢？模型复制用起来还是比较顺手的，用户体验更好。

您好，请问这个只是复制一个全新的模型，然后各训练各的，彼此参数没有影响对吧。
