### ISSUE TITLE
【论文复现】Aistudio安装development branch后运行报错

### ISSUE THREAD

**Issue by kafaichan** [PaddlePaddle/Paddle#26170]
#26081 我根据issue所列的步骤在aistudio环境安装后，运行程序时发生如图的错误。这似乎是cuda不兼容的问题。我在本地使用cuda 10.2并没有错误。想问一下这在aistudio该如何解决？
![aistudio_snapshot](https://user-images.githubusercontent.com/8078887/89921458-50c74900-dc30-11ea-8e3c-81ade8d8d019.png)

**Comment by ceci3** [comment]
本地编译环境是cuda10，aistudio上是cuda9，所以你本地编译的whl包在aistudio上不兼容，可以直接在官网下载相应cuda9的develop whl包，在aistudio上安装 https://www.paddlepaddle.org.cn/documentation/docs/zh/install/Tables.html#whl-dev

**Comment by kafaichan** [comment]
![q](https://user-images.githubusercontent.com/8078887/89969069-14bfd280-dc88-11ea-869f-a4c890cc449f.jpg)
选那一个?

**Comment by kafaichan** [comment]
![q](https://user-images.githubusercontent.com/8078887/89969562-4a18f000-dc89-11ea-80e9-7e186e3f0d6b.jpg)

![q1](https://user-images.githubusercontent.com/8078887/89969565-4c7b4a00-dc89-11ea-8881-612f0e2446d7.JPG)

![q2](https://user-images.githubusercontent.com/8078887/89969619-703e9000-dc89-11ea-981a-d5c5f2d89d47.JPG)

我在aistudio试安装了红圈标示的两个版本都报了如上的错误.

**Comment by ceci3** [comment]
https://github.com/PaddlePaddle/Paddle/issues/26168#issuecomment-672464634 可以看下这个issue下aistudio的回复

**Comment by ceci3** [comment]
@weiexcelpro 麻烦看下还有这个issue，感谢~

**Comment by weiexcelpro** [comment]
刚才有人提到类似的问题. 首先需要保证的确是CUDA9的Paddle, 因为AIStudio当前是CUDA 9 而且很难升级到CUDA 10. 

其次当前cuDNN安装上可能有问题, 最新的dev Paddle运行时会抛cuDNN异常. 这个还在检查.
