### ISSUE TITLE
【论文复现】动态图里面是否可以声明fluid.layer下面的函数！

### ISSUE THREAD

**Issue by OxInsky** [PaddlePaddle/Paddle#26199]
我在找寻接口的时候发现很多函数都在fluid.layer下面，请问是否可以在动态图的模式下定义静态图中的层呢？速度是否会变慢，这个我自己可以验证，但是还是想请教下专业的回答！

**Comment by sunxl1988** [comment]
可与调用fluid.layers下的api，不需要进行init，类似于pytorch的func下api
