### ISSUE TITLE
【论文复现】请问paddle中是否存在与pytorch中类似功能的nn.ModuleList函数?

### ISSUE THREAD

**Issue by OxInsky** [PaddlePaddle/Paddle#26196]
self.down_blocks = nn.ModuleList(down_blocks)
       down_blocks是一个list 包含了我网络中所有的结构，我需要对这个网络进行forward() ，请问是否有接口完成！

**Comment by sunxl1988** [comment]
参考https://www.paddlepaddle.org.cn/documentation/docs/zh/api_cn/dygraph_cn/Sequential_cn.html#sequential

**Comment by linnnn1** [comment]
请问您找到了paddle中与pytorch中类似功能的nn.ModuleList函数吗

**Comment by linnnn1** [comment]
请问您找到了paddle中与pytorch中类似功能的nn.ModuleList函数吗
