### ISSUE TITLE
【论文复现】paddle中是否有attributes对tensor（VarBase）直接操作？

### ISSUE THREAD

**Issue by Rookieaura** [PaddlePaddle/Paddle#26193]
在pytorch中，可以用attributes对tensor 很方便的进行操作，比如 tensor.size(), tensor.topk() 之类的。请问在paddle中也有类似的方法吗？否则每次都得调用函数并接收，会比较麻烦。

**Comment by OxInsky** [comment]
这个问题我也存在疑问，为什么在tensor上操作都要使用层来完成一些基本的操作，这是为了把网络所有的操作都变化为层的思想来设计的么？

**Comment by saxon-zh** [comment]
是的，相关API会简化使用操作，目前版本还没有这种使用方式，需求已经进入需求池内，我们跟进一下做排期计划。
