### ISSUE TITLE
用paddlepaddle1.5搭建多输入的cnn网络 在网络结构图里看不到第二个输入

### ISSUE THREAD

**Issue by StarryDing** [PaddlePaddle/Paddle#26207]
#定义网络
import paddle.fluid as fluid

def cnn_model(image, mode):
    print(image)
    conv1 = fluid.layers.conv2d(input=image, num_filters=32, filter_size=5, stride=2, act='relu')
    conv2 = fluid.layers.conv2d(input=conv1, num_filters=32, filter_size=5, stride=2)
    bn0 = fluid.layers.batch_norm(input=conv2,act='relu')
    conv3 = fluid.layers.conv2d(input=bn0, num_filters=64, filter_size=5, stride=2, act='relu')
    conv4 = fluid.layers.conv2d(input=conv3, num_filters=64, filter_size=3, stride=2)
    bn1 = fluid.layers.batch_norm(input=conv4,act='relu')
    conv5 = fluid.layers.conv2d(input=bn1, num_filters=128, filter_size=3, stride=1, act='relu')
    conv6 = fluid.layers.conv2d(input=conv5, num_filters=128, filter_size=3, stride=1)
    bn2 = fluid.layers.batch_norm(input=conv6,act='relu')
    
    fc1 = fluid.layers.fc(input=bn2, size=128, act=None)
    drop_fc1 = fluid.layers.dropout(fc1, dropout_prob=0.5)
    fc2 = fluid.layers.fc(input=drop_fc1, size=64, act=None)
    drop_fc2 = fluid.layers.dropout(fc2, dropout_prob=0.5)
    # print(mode)
    concat1 = fluid.layers.concat(input=[drop_fc2, mode], axis=1)
    # print(concat1)
    predict = fluid.layers.fc(input=concat1, size=2)
    return predict

![image](https://user-images.githubusercontent.com/53610587/90000346-a2b8af00-dcc2-11ea-8c63-c4bb03088424.png)
多输入的模型应该在这里有第二个输入进去的啊
上面那个模型我可以跑通 可是为啥我查看网络结构的时候发现这里并没有我第二个输入的接口呢 是有什么api我没用上么

**Comment by kgkzhiwen** [comment]
请问你是用什么软件实现网络可视化？

**Comment by StarryDing** [comment]
@kgkzhiwen 用的Netron
不光是看不到第二个输入 关键是我用paddle_mobile部署的时候好像就没有第二个输入的接口....

**Comment by adaxiadaxi** [comment]
@StarryDing 可以先用VDL试试可视化效果：https://github.com/PaddlePaddle/VisualDL

**Comment by StarryDing** [comment]
@adaxiadaxi 
![image](https://user-images.githubusercontent.com/53610587/90123716-de6e7a00-dd91-11ea-957b-6d889b142c4e.png)
visualdl可视化也是这样....

**Comment by StarryDing** [comment]
@adaxiadaxi 话说定义网络的输入是有什么api需要调用么？刚接触paddlepaddle不是太熟悉.....我这么定义的网络训练的时候也都能跑通 然后部署的时候咋也不行 然后查看了下结构发现有问题....
