### ISSUE TITLE
【论文复现】paddle如何定义可训练的数组

### ISSUE THREAD

**Issue by chunfeng0301** [PaddlePaddle/Paddle#26219]
img_grad = nn.Parameter(torch.FloatTensor([[[[-0.5,0,0.5]]]]).repeat(32,32,1,1))
如上用paddle如何实现
f_grad = (np.array([[[[-0.5,0,0.5]]]]).astype("float32").repeat(32**2,1))#fluid.layers.create_parameter

f_grad2 =  fluid.dygraph.to_variable(f_grad)报如下错误

 "We Only support %s in Dygraph mode, please use fluid.dygraph.guard() as context to run it in Dygraph Mode" % func.__name__
AssertionError: We Only support to_variable in Dygraph mode, please use fluid.dygraph.guard() as context to run it in Dygraph Mode

 use fluid.dygraph.guard() 能进行训练么？？对么

**Comment by sunxl1988** [comment]
可以参考https://www.paddlepaddle.org.cn/documentation/docs/zh/api_cn/fluid_cn/Tensor_cn.html#tensor
动态图是需要fluid.dygraph.guard()

**Comment by chunfeng0301** [comment]
t=fluid.Tensor()

aaa = np.array([[[[-0.5,0,0.5]]]]).astype("float32").repeat(32**2,1)
aaa = np.reshape(aaa,[32,32,1,3])
t.set(aaa,fluid.CPUPlace())
这样t 就和  img_grad = nn.Parameter(torch.FloatTensor([[[[-0.5,0,0.5]]]]).repeat(32,32,1,1))中的img_grad 等价了么?

**Comment by chunfeng0301** [comment]
> 可以参考https://www.paddlepaddle.org.cn/documentation/docs/zh/api_cn/fluid_cn/Tensor_cn.html#tensor
> 动态图是需要fluid.dygraph.guard()

t=fluid.Tensor()

aaa = np.array([[[[-0.5,0,0.5]]]]).astype("float32").repeat(32**2,1)
aaa = np.reshape(aaa,[32,32,1,3])
t.set(aaa,fluid.CPUPlace())
这样t 就和 img_grad = nn.Parameter(torch.FloatTensor([[[[-0.5,0,0.5]]]]).repeat(32,32,1,1))中的img_grad 等价了么?

**Comment by chunfeng0301** [comment]
> 可以参考https://www.paddlepaddle.org.cn/documentation/docs/zh/api_cn/fluid_cn/Tensor_cn.html#tensor
> 动态图是需要fluid.dygraph.guard()
fluid.dygraph.to_variable(xxx) 报如下错误
AttributeError: module 'paddle.fluid.dygraph' has no attribute 'to_variablet'

**Comment by FDInSky** [comment]
to_variable， 不是to_variablet， 名字写错了

**Comment by chunfeng0301** [comment]
报了一堆错误 ，主要是paddlepaddle版本不是1.8

**Comment by liu824** [comment]
> > 可以参考https://www.paddlepaddle.org.cn/documentation/docs/zh/api_cn/fluid_cn/Tensor_cn.html#tensor 
> > 动态图是需要fluid.dygraph.guard（）
> 
> t = fluid.Tensor（）
> 
> aaa = np.array（[[[[-0.5,0,0.5]]]]。astype（“ float32”）。repeat（32 ** 2,1）
> aaa = np.reshape（aaa，[32,32 ，1,3]）
> t.set（aaa，fluid.CPUPlace（））
> 这样t和img_grad = nn.Parameter（torch.FloatTensor（[[[[-0.5,0,0.5]]]））。repeat（ 32,32,1,1））中的img_grad等价了么？

这种方式可以吗？
