### ISSUE TITLE
【论文复现】core_avx.VarBase 如何reshape

### ISSUE THREAD

**Issue by kgkzhiwen** [PaddlePaddle/Paddle#26211]
请问core_avx.VarBase 如何reshape？以下代码出错：

`
out=adaptive_pool3d(out, pool_size=(1,1,1),pool_type='avg')
 
out = self.classifier(out.reshape(features.size(0), -1))
`

**AttributeError: 'paddle.fluid.core_avx.VarBase' object has no attribute 'reshape'**

**Comment by kgkzhiwen** [comment]
搞定了。不好意思，麻烦各位了。

**Comment by ymzlygw** [comment]
> 搞定了。不好意思，麻烦各位了。

请问如何reshape呢
