### ISSUE TITLE
【论文复现】加载保存的模型出错

### ISSUE THREAD

**Issue by deep-practice** [PaddlePaddle/Paddle#26225]
假设定义的网络模型为model = Model()
保存
fluid.save_dygraph(model.state_dict(),"model")
加载
param = fluid.load_dygraph("model")
model.set_dict(param)
加载过程中报错，说某个fc_weight没有

**Comment by Shixiaowei02** [comment]
您好，请提供具体报错信息和必要的复现环境，谢谢！

**Comment by deep-practice** [comment]
项目链接：https://aistudio.baidu.com/aistudio/projectdetail/703942
python main.py --resume True
@Shixiaowei02

**Comment by deep-practice** [comment]
项目在work目录下

**Comment by Shixiaowei02** [comment]
@deep-practice 您好，我这边打开页面显示项目尚未公开
