### ISSUE TITLE
【论文复现】UGATIT 关于expand 

### ISSUE THREAD

**Issue by sincerevertigo** [PaddlePaddle/Paddle#26223]
pytroch 源码
self.rho.expand(input.shape[0], -1, -1, -1)

paddle
rho_expand = paddle.tensor.expand(self.rho, (input.shape[0], 1, 1, 1))

确认一下，paddle的参数是不支持负数的，这里是不是就得用[1]了？

谢谢。

**Comment by oytang** [comment]
torch中-1的维度代表不进行expand，而paddle中为1的维度不进行expand

**Comment by sincerevertigo** [comment]
@Chemino 
谢谢。
