### ISSUE TITLE
【论文复现】GAN综述-实践作业版本保存问题和视频分类综述－实践作业程序丢失问题

### ISSUE THREAD

**Issue by wuyi1405** [PaddlePaddle/Paddle#26230]
1.GAN综述-实践作业版本保存问题：
之前跑完程序后，点保存，停止程序，忘记关notebook页面。再关闭，提示保存，点击保存后。会出现保存2个同名版本。导致提交作业内容显示“Notebook内容过多，无法预览”。重新启动版本，再运行保存后会提示保存2次，即使点击保存一次，也会显示“Notebook内容过多，无法预览”，把版本的名字改了成不同的也没用，会提示一个版本没有同步，另外一个版本可以运行，但是运行后保存也是保存2次。这种情况没法提交作业。
https://aistudio.baidu.com/bdcpu5/user/303001/676465/notebooks/676465.ipynb
![问题1](https://user-images.githubusercontent.com/25198497/90088255-173a2f00-dd51-11ea-9d66-0939e6660e23.PNG)
2.视频分类综述－实践作业程序丢失问题：
生成版本，修改代码，保存了。停止后，重新启动换GPU时（忘记可以直接换环境），py的运行程序不见了，只有data数据文件。
https://aistudio.baidu.com/bdcpu6/user/303001/676478/notebooks/676478.ipynb
![问题2](https://user-images.githubusercontent.com/25198497/90088956-caefee80-dd52-11ea-9086-a4368756f534.PNG)

**Comment by saxon-zh** [comment]
您好，可以将问题反馈至AIStudio邮箱: aistudio@baidu.com或加入AIStudio官方QQ群: 305197519咨询。
