### ISSUE TITLE
【论文复现】如何用数组作为tensor/VarBase 的indices

### ISSUE THREAD

**Issue by zzz2010** [PaddlePaddle/Paddle#26259]
例如：
    import numpy as np
    with fluid.dygraph.guard(place=place):
        print(fluid.layers.randn([16])[fluid.core.VarBase(np.array([1,3]) ) ])

 Currently, VarBase.__getitem__() only allows indexing by Integers, Slices, and tuples of these types, but received paddle.fluid.core_avx.VarBase in 1th slice item

torch 是支持torch.Long array 索引的， 请问paddle 有类似的吗？
谢谢

**Comment by Shixiaowei02** [comment]
您好，目前 Paddle 还不支持以数组作为索引值
