### ISSUE TITLE
【论文复现】UGATIT AIStudio paddle2.0alpha 1.8.3 1.8.4 Cudnn error (使用的都是gpu,cuda9,cudnn7 )

### ISSUE THREAD

**Issue by sincerevertigo** [PaddlePaddle/Paddle#26250]
在AIStudio
通过 
python3 -m pip install paddlepaddle-gpu==2.0.0a0 -i https://mirror.baidu.com/pypi/simple
进行了paddle 2.0 的安装。

运行代码是，先是出了警告。
`WARNING: device: 0. The installed Paddle is compiled with CUDNN 7.6, but CUDNN version in your machine is 7.3, which may cause serious incompatible bug. Please recompile or reinstall Paddle with compatible CUDNN version.
training start !`

然后，经过了几个方法之后，出了。（这些方法在mac上有cpu跑过，是可以跑通的）
Cunn error
`ExternalError:  Cudnn error, CUDNN_STATUS_BAD_PARAM  at (/paddle/paddle/fluid/operators/instance_norm_op.cu:177)`

感觉是Cunn版本和paddle的版本对不上。
查看了版本。
aistudio@jupyter-338261-719442:~/work$ cat /usr/local/cuda/version.txt
CUDA Version 9.2.148
aistudio@jupyter-338261-719442:~/work$ cat /usr/local/cuda/include/cudnn.h | grep CUDNN_MAJOR -A 2
#define CUDNN_MAJOR 7
#define CUDNN_MINOR 6
#define CUDNN_PATCHLEVEL 5

#define CUDNN_VERSION (CUDNN_MAJOR * 1000 + CUDNN_MINOR * 100 + CUDNN_PATCHLEVEL)

#include "driver_types.h"

这里显示的是7.6

现在卡在这里了。。。

谢谢。

**Comment by sincerevertigo** [comment]
安装1.8.3 gpu,cuda9,cudnn7
!export LD_LIBRARY_PATH=/usr/local/cuda/lib64 && 

如上两个操作，解决问题。

**Comment by FL77N** [comment]
> 安装1.8.3 gpu,cuda9,cudnn7
> !export LD_LIBRARY_PATH=/usr/local/cuda/lib64 &&
> 
> 如上两个操作，解决问题。

想问一下，

export LD_LIBRARY_PATH=/usr/local/cuda-9.2/lib64:$LD_LIBRARY_PATH
--


这一行到底是加在哪呢，我加在终端了怎么没有用呢
