### ISSUE TITLE
【论文复现】AI Studio 在data文件夹增大后无法将work文件夹生成进新版本

### ISSUE THREAD

**Issue by Rookieaura** [PaddlePaddle/Paddle#26263]
进行论文复现时，解压data文件夹数据集后，data文件夹体积变大。这时Notebook及整个环境仍可以正常运行，保存在work文件夹内的文件也可以被修改。但是在修改完work文件夹中的代码文件后，在生成新版本时，无法将work文件夹添加进新版本。具体显示为，对话框内，可添加文件列表为空。关闭环境再重新进入后，work文件夹下的所有修改会丢失。

**Comment by saxon-zh** [comment]
AIStudio的问题辛苦发到aistudio@baidu.com问下吧，里面有平台的PM和RD来看。
