### ISSUE TITLE
【论文复现】在Paddlepaddle的IN中，没有像Pytorch中IN的momentum部分

### ISSUE THREAD

**Issue by DrRyanHuang** [PaddlePaddle/Paddle#26262]
RD您好！
在`torch.nn.InstanceNorm2d`中，有实现momentum部分
在Paddle的`instance_norm`或者`InstanceNorm` 均没有momentum部分
我查阅了文档，有关momentum的只有momentum优化器，请问在Paddle中如何实现呢？

期待您的回复！

**Comment by ceci3** [comment]
你好，paddle的instance norm不会计算全局均值和方差，momentum使用来计算全局均值方差时候用到的一个计算动量(参考BatchNorm API计算全局统计量的公式）。你现在是要用instance norm的全局均值方差嘛？如果不是的话，这个参数是没有必要的。 这里的momentum 和momentum优化器不是一个概念~
