### ISSUE TITLE
【论文复现】在命令行模式下，以下代码会报报错 broadcast should not into w broadcast，导致后向传播出现问题？求解答

### ISSUE THREAD

**Issue by liuxianyi** [PaddlePaddle/Paddle#26265]
在命令行模式下，以下代码会报报错，导致后向传播出现问题？求解答
## 错误日志：
![image](https://user-images.githubusercontent.com/33951338/90203007-043b6380-de12-11ea-9dd7-fb4cf4d35172.png)
## 代码
```
import numpy as np
import paddle,itertools
import paddle.fluid as fluid
from paddle.fluid.dygraph import to_variable
import paddle.fluid.dygraph as nn
class adaILN(nn.Layer):
    def __init__(self, num_features, eps=1e-5):
        super(adaILN, self).__init__()
        self.num_features = num_features
        self.eps = eps
        self.rho = fluid.layers.create_parameter(shape=[1,num_features,1,1], dtype='float32',is_bias=True, 
        default_initializer=fluid.initializer.Constant(0.9))
    def forward(self, input):
        ln_mean= fluid.layers.reduce_mean(input, dim=[1, 2, 3], keep_dim=True)
      
        out_ln = input - ln_mean
        
        out1 = (1-fluid.layers.expand(x=self.rho, expand_times=[input.shape[0], 1, 1, 1])) * out_ln
        # 经过初步调试，确定发生错误位置在此处，将此处注释不会报错

        return out1
#高层API的组网方式需要继承Model，Model类实现了模型执行所需的逻辑
class SimpleNet(paddle.fluid.dygraph.Layer):
    def __init__(self):
        super(SimpleNet, self).__init__()
        self.conv = paddle.fluid.dygraph.Conv2D(1,1,filter_size=3,stride=1,padding=1)
        self.iln = adaILN(1)
    def forward(self, x):
        x = self.conv(x)
        x = self.iln(x)
        return x

with paddle.fluid.dygraph.guard(paddle.fluid.CUDAPlace(0)):
    
    model1 = SimpleNet()
    Loss = nn.L1Loss()
    optim = fluid.optimizer.Adam(learning_rate=0.001,
        beta1=0.5,
        beta2=0.999,
        parameter_list=model1.parameters()
            )
    model1.train()

    for i in range(20):
        x1 = np.random.random((2, 1, 256, 256)).astype('float32')
        x1 = to_variable(x1)
        e1= model1(x1)
        #print(e1)
        # e2 = model1(e1)
        loss2 = Loss(e1, x1)
        #print('loss:',loss.numpy())
        # loss = loss1+loss2
        print(loss2.numpy())
        loss2.backward()
        optim.minimize(loss2)
        optim.clear_gradients()
```

_Originally posted by @liuxianyi in https://github.com/PaddlePaddle/Paddle/issues/26192#issuecomment-673821904_

**Comment by sincerevertigo** [comment]
@liuxianyi 
我也遇到了同样的问题。
更诡异的是，你上面那段代码，放在贴在notebook里，shif回车直接执行，不报错。
但是，做成.py文件，通过!python 执行的话，就报错。。。

问题解决了吗？

**Comment by liuxianyi** [comment]
> @liuxianyi
> 我也遇到了同样的问题。
> 更诡异的是，你上面那段代码，放在贴在notebook里，shif回车直接执行，不报错。
> 但是，做成.py文件，通过!python 执行的话，就报错。。。
> 
> 问题解决了吗？

解决不了，我觉得是paddle的layers.expend()底层有bug,现在攻城狮没来解决issue

**Comment by saxon-zh** [comment]
https://github.com/PaddlePaddle/Paddle/issues/25141  可以参考这个Issue将Paddle版本升级到1.8的最新版，今天刚发布了1.8.4

**Comment by liuxianyi** [comment]
> #25141 可以参考这个Issue将Paddle版本升级到1.8的最新版，今天刚发布了1.8.4

1.8.1,1.8.2,1.8.3,1.8.4的GPU环境都不可以使用，cudnn版本低

**Comment by zhhsplendid** [comment]
现在这个应该就是在新的版本里修复了，如果遇到cudnn版本低的问题，不知道有没有办法配置环境？更新cudnn？

**Comment by ruyijidan** [comment]
平台运算符重载可能有问题，本地运行一般是没问题的,尝试把-号换成fluid.layers.elementwise_sub,试试看这样改对不对
`out1 = (fluid.layers.elementwise_sub(1,fluid.layers.expand(x=self.rho, expand_times=[input.shape[0], 1, 1, 1]))) * out_ln`

**Comment by FrankCV2048** [comment]
> 平台运算符重载可能有问题，本地运行一般是没问题的,尝试把-号换成fluid.layers.elementwise_sub,试试看这样改对不对
> `out1 = (fluid.layers.elementwise_sub(1,fluid.layers.expand(x=self.rho, expand_times=[input.shape[0], 1, 1, 1]))) * out_ln`

依然是不行 难受

**Comment by ruyijidan** [comment]
> > 平台运算符重载可能有问题，本地运行一般是没问题的,尝试把-号换成fluid.layers.elementwise_sub,试试看这样改对不对
> > `out1 = (fluid.layers.elementwise_sub(1,fluid.layers.expand(x=self.rho, expand_times=[input.shape[0], 1, 1, 1]))) * out_ln`
> 
> 依然是不行 难受

其他的运算符也可以都试着改一下，我之前就是改了+就好了

**Comment by saxon-zh** [comment]
broadcast should not into w broadcast 这个问题在≥1.8.2版本中已修复，对应PR是https://github.com/PaddlePaddle/Paddle/pull/24869 ，可以将使用的Paddle版本做下升级，当前已发布最新版本是1.8.4。
