### ISSUE TITLE
【论文复现】如何手动设置Learning Rate

### ISSUE THREAD

**Issue by kgkzhiwen** [PaddlePaddle/Paddle#26264]
我想知道如何手动获取当前的Learning Rate.

我想知道如何手动设置当前的Learning Rate。比如当精度达到0.5，我想把它设为0.01；当精度升高到0.7，我想设为0.003；当精度升高到0.8，我想设为0.001.

**Comment by thrkingd** [comment]
可以参考：https://www.paddlepaddle.org.cn/documentation/docs/zh/api_cn/optimizer_cn/MomentumOptimizer_cn.html
