### ISSUE TITLE
k8s launch file for fault tolerant training job (includes Master, Trainer, Pservers).@gongweibao

### ISSUE THREAD

**Issue by gongweibao** [PaddlePaddle/Paddle#2626]

**Comment by helinwang** [comment]
Thank you @gongweibao for working on this issue!

**Comment by Yancey1989** [comment]
What's the meaning of `k8s launch file`? Maybe we can launch the PaddlePaddle Job with PaddleCloud command-line tool?

**Comment by gongweibao** [comment]
同意闫旭的意见，我觉得我们可以直接用paddlecloud的命令行工具来提交任务。 @helinwang 觉得？
https://github.com/PaddlePaddle/cloud/blob/develop/doc/tutorial_cn.md

**Comment by helinwang** [comment]
同意！不好意思，我没说清楚，我建这个issue的目的就是确保paddlecloud的命令行工具正常运行。

**Comment by typhoonzero** [comment]
Closing this issue.
