### ISSUE TITLE
windows编译源码么，报错找不到相关文件

### ISSUE THREAD

**Issue by baigang666** [PaddlePaddle/Paddle#26270]
- 版本、环境信息：
    1）PaddlePaddle版本：1.8.4
    2）GPU：cuda-10.0，cudnn-7.6
    3）系统环境:windows 10
    4)VS版本：2019 社区版

报错：找不到相关文件：提示#include "paddle/fluid/platform/cuda_error.pb.h"   没有此文件
请大神指导一下 谢谢

**Comment by wadefelix** [comment]
看这个 https://github.com/PaddlePaddle/Paddle/issues/26330#issuecomment-674524418
因为protobuf工程没编译过的缘故。

**Comment by zhhsplendid** [comment]
对的，如上所说，cuda_error.pb.h由protobuf生成，可以查看protobuf依赖是否配置正确
