### ISSUE TITLE
train_from_dataset 如何获取tensor？

### ISSUE THREAD

**Issue by dancingpipi** [PaddlePaddle/Paddle#26275]
```
exe.train_from_dataset(
            program=main_program,
            dataset=dataset,
            fetch_list=[loss],
            fetch_info=["[***Train Loss***]: "],
            print_period=1,
            debug=False)
```
这样我只能获得打印值，如何获得返回的tensor？ 比如类似fetch_targets

**Comment by zhhsplendid** [comment]
嗨，请问你的意思是否是不只要fetch的打印值，而是要fetch的tensor，你接下来继续组网用？

**Comment by dancingpipi** [comment]
> 嗨，请问你的意思是否是不只要fetch的打印值，而是要fetch的tensor，你接下来继续组网用？

是的，要根据他的返回值进行一些逻辑操作~

**Comment by zhhsplendid** [comment]
这个恐怕train_from_dataset接口做不到。但是你应该已经有个组网的过程了吧？组网过程是有tensor的，可否组网过程的tensor继续用？

我的意思是，你想做的：

组网 -> train_from_dataset 还能拿到tensor -> 继续组网

我们可否改为这样做：

组网 -> 直接使用想拿的tensor继续组网 -> train_from_dataset 获取两个网络中想要的输出。

**Comment by dancingpipi** [comment]
> 这个恐怕train_from_dataset接口做不到。但是你应该已经有个组网的过程了吧？组网过程是有tensor的，可否组网过程的tensor继续用？
> 
> 我的意思是，你想做的：
> 
> 组网 -> train_from_dataset 还能拿到tensor -> 继续组网
> 
> 我们可否改为这样做：
> 
> 组网 -> 直接使用想拿的tensor继续组网 -> train_from_dataset 获取两个网络中想要的输出。

可能不是这个问题，我觉得我现在的问题变成了，如何在train_from_dataset后获取某个tensor的数值

**Comment by zhhsplendid** [comment]
会在c++打印出来，但当前接口无法返回

**Comment by dancingpipi** [comment]
> 会在c++打印出来，但当前接口无法返回

难受，所以想获得，只能用pyreader或者dataloader接口吗？

**Comment by zhhsplendid** [comment]
嗯，当前是的
