### ISSUE TITLE
【论文复现】UGATIT复现过程变量与pad2d实用问题

### ISSUE THREAD

**Issue by caikw0602** [PaddlePaddle/Paddle#26280]
问题描述：
使用paddle实现ReflectionPad2d函数：
![QQ截图20200814154658](https://user-images.githubusercontent.com/45365909/90226360-77aa9880-de45-11ea-9dad-f7f820b8b17e.png)

但运行时报错如下：
![image](https://user-images.githubusercontent.com/45365909/90226408-885b0e80-de45-11ea-8e04-3441488c870e.png)

试图加入下属代码解决问题：
![image](https://user-images.githubusercontent.com/45365909/90226489-a45eb000-de45-11ea-81f5-9845d388ae95.png)
da

但问题仍没有解决：
![image](https://user-images.githubusercontent.com/45365909/90226528-b2accc00-de45-11ea-9fa4-c5003a038803.png)

![image](https://user-images.githubusercontent.com/45365909/90226554-bc363400-de45-11ea-942a-d55de21b04cc.png)

期待各路大神帮助解决，万分感谢！

**Comment by morgan-bc** [comment]
```
class ReflectionPad2D(fluid.dygraph.Layer):
    def __init__(self, padding):
        super().__init__()
        if isinstance(padding, int):
            self.padding = [padding] * 4
        else:
            self.padding = padding

    def forward(self, x):
        return fluid.layers.pad2d(x, self.padding, mode='reflect')

```

**Comment by ysh329** [comment]
@caikw0602 可以提供一下代码我们试一下
