### ISSUE TITLE
【bug反馈】clip_by_norm函数未考虑除数为零，导致模型计算出现nan

### ISSUE THREAD

**Issue by geekhch** [PaddlePaddle/Paddle#26282]
1）PaddlePaddle版本：1.8
    2）CPU/GPU：GPU
    3）系统环境：dygragh

如图，经过仔细debug，发现是clip_by_norm函数中norm为0的情况下出现nan。
![image](https://user-images.githubusercontent.com/32632844/90229933-4f259d00-de4b-11ea-9c4f-34ad80f8ccc2.png)

**Comment by zhhsplendid** [comment]
谢谢反馈，不过这种情况确实是比较少见，我们后续将进行修复
