### ISSUE TITLE
【论文复现】UGATIT 关于pytroch的apply

### ISSUE THREAD

**Issue by sincerevertigo** [PaddlePaddle/Paddle#26286]
pytroch 源码
`# clip parameter of AdaILN and ILN, applied after optimizer step
                self.genA2B.apply(self.Rho_clipper)
                self.genB2A.apply(self.Rho_clipper)`

apply在paadle里面怎么去实现？有什么可参考的资料吗？
谢谢

**Comment by morgan-bc** [comment]
```
def clip_rho(net, vmin=0, vmax=1):
    for name, param in net.named_parameters():
        if 'rho' in name:
            param.set_value(fluid.layers.clip(param, vmin, vmax))
```

**Comment by ysh329** [comment]
上面 @suishicity 已经给了比较好的例子，主要是用到了`set_value`这个api，这个api应该就是你说的apply，具体见文档，Variable-API文档-PaddlePaddle深度学习平台
https://www.paddlepaddle.org.cn/documentation/docs/zh/api_cn/fluid_cn/Variable_cn.html#set-value

**Comment by sincerevertigo** [comment]
@suishicity @ysh329 
谢谢！！！
