### ISSUE TITLE
[论文复现]  paddle.reader.xmap_readers 数据读取异常terminate called without an active exception

### ISSUE THREAD

**Issue by yuctian** [PaddlePaddle/Paddle#26296]
在用paddle.reader.xmap_readers(mapper, reader, num_threads, buf_size)读取数据的时候遇到了这样的报错，是中途出错的，什么原因
terminate called without an active exception
W0815 10:50:20.376297  7585 init.cc:216] Warning: PaddlePaddle catches a failure signal, it may not work properly
W0815 10:50:20.376339  7585 init.cc:218] You could check whether you killed PaddlePaddle thread/process accidentally or report the case to PaddlePaddle
W0815 10:50:20.376343  7585 init.cc:221] The detail failure signal is:

W0815 10:50:20.376348  7585 init.cc:224] *** Aborted at 1597459820 (unix time) try "date -d @1597459820" if you are using GNU date ***
W0815 10:50:20.378110  7585 init.cc:224] PC: @                0x0 (unknown)
W0815 10:50:20.378398  7585 init.cc:224] *** SIGABRT (@0x3e800001d67) received by PID 7527 (TID 0x7f64369d3700) from PID 7527; stack trace: ***
W0815 10:50:20.379829  7585 init.cc:224]     @     0x7f645997c390 (unknown)
W0815 10:50:20.381067  7585 init.cc:224]     @     0x7f64595d6428 gsignal
W0815 10:50:20.382252  7585 init.cc:224]     @     0x7f64595d802a abort
W0815 10:50:20.383141  7585 init.cc:224]     @     0x7f641393584a __gnu_cxx::__verbose_terminate_handler()
W0815 10:50:20.383903  7585 init.cc:224]     @     0x7f6413933f47 __cxxabiv1::__terminate()
W0815 10:50:20.384737  7585 init.cc:224]     @     0x7f6413933f7d std::terminate()
W0815 10:50:20.385507  7585 init.cc:224]     @     0x7f6413933c5a __gxx_personality_v0
W0815 10:50:20.386207  7585 init.cc:224]     @     0x7f6413880b97 _Unwind_ForcedUnwind_Phase2
W0815 10:50:20.386883  7585 init.cc:224]     @     0x7f6413880e7d _Unwind_ForcedUnwind
W0815 10:50:20.388068  7585 init.cc:224]     @     0x7f645997b070 __GI___pthread_unwind
W0815 10:50:20.389230  7585 init.cc:224]     @     0x7f6459973845 __pthread_exit
W0815 10:50:20.389500  7585 init.cc:224]     @     0x55d11bb71e59 PyThread_exit_thread
W0815 10:50:20.389586  7585 init.cc:224]     @     0x55d11b9f7c17 PyEval_RestoreThread.cold.798
W0815 10:50:20.390378  7585 init.cc:224]     @     0x7f64175a6c9f (unknown)
W0815 10:50:20.390661  7585 init.cc:224]     @     0x55d11baf3744 _PyMethodDef_RawFastCallKeywords
W0815 10:50:20.390897  7585 init.cc:224]     @     0x55d11bafb3cf _PyMethodDescr_FastCallKeywords
W0815 10:50:20.391150  7585 init.cc:224]     @     0x55d11bb5f07c _PyEval_EvalFrameDefault
W0815 10:50:20.391392  7585 init.cc:224]     @     0x55d11baa3539 _PyEval_EvalCodeWithName
W0815 10:50:20.391600  7585 init.cc:224]     @     0x55d11baf2f57 _PyFunction_FastCallKeywords
W0815 10:50:20.391840  7585 init.cc:224]     @     0x55d11bb5a806 _PyEval_EvalFrameDefault
W0815 10:50:20.392067  7585 init.cc:224]     @     0x55d11baa3d09 _PyEval_EvalCodeWithName
W0815 10:50:20.392288  7585 init.cc:224]     @     0x55d11baa4635 _PyFunction_FastCallDict
W0815 10:50:20.392431  7585 init.cc:224]     @     0x55d11bbb2b5b partial_call
W0815 10:50:20.392645  7585 init.cc:224]     @     0x55d11bafb8fb _PyObject_FastCallKeywords
W0815 10:50:20.392869  7585 init.cc:224]     @     0x55d11bb5ee86 _PyEval_EvalFrameDefault
W0815 10:50:20.393090  7585 init.cc:224]     @     0x55d11baa381a _PyEval_EvalCodeWithName
W0815 10:50:20.393311  7585 init.cc:224]     @     0x55d11baa4635 _PyFunction_FastCallDict
W0815 10:50:20.393548  7585 init.cc:224]     @     0x55d11bb5c232 _PyEval_EvalFrameDefault
W0815 10:50:20.393754  7585 init.cc:224]     @     0x55d11baf2ccb _PyFunction_FastCallKeywords
W0815 10:50:20.393991  7585 init.cc:224]     @     0x55d11bb5aa93 _PyEval_EvalFrameDefault
W0815 10:50:20.394205  7585 init.cc:224]     @     0x55d11baf2ccb _PyFunction_FastCallKeywords
W0815 10:50:20.394448  7585 init.cc:224]     @     0x55d11bb5aa93 _PyEval_EvalFrameDefault
Aborted (core dumped)

**Comment by ysh329** [comment]
```shell
terminate called without an active exception
W0815 10:50:20.376297 7585 init.cc:216] Warning: PaddlePaddle catches a failure signal, it may not work properly
W0815 10:50:20.376339 7585 init.cc:218] You could check whether you killed PaddlePaddle thread/process accidentally or report the case to PaddlePaddle
W0815 10:50:20.376343 7585 init.cc:221] The detail failure signal is:

W0815 10:50:20.376348 7585 init.cc:224] *** Aborted at 1597459820 (unix time) try "date -d @1597459820" if you are using GNU date ***
W0815 10:50:20.378110 7585 init.cc:224] PC: @ 0x0 (unknown)
W0815 10:50:20.378398 7585 init.cc:224] *** SIGABRT (@0x3e800001d67) received by PID 7527 (TID 0x7f64369d3700) from PID 7527; stack trace: ***
W0815 10:50:20.379829 7585 init.cc:224] @ 0x7f645997c390 (unknown)
```

日志信息没看明白`whether you killed PaddlePaddle thread/process accidentally or report the case to PaddlePaddle`，什么环境？还希望在提供一些信息哦
