### ISSUE TITLE
[论文复现]  想要在max_pool的同时获取相对应的坐标,同时unsample的同时将值放置在坐标位置上，新增API

### ISSUE THREAD

**Issue by Costwen** [PaddlePaddle/Paddle#26297]
通过查阅fluid.layers.poold这个api的文档发现没有相对应的参数返回坐标值
不知道有没有类似的函数可以解决这个问题
如果没有这类的api,那么如何自己构建一个呢？

**Comment by ysh329** [comment]
两个问题：

1. fluid.layers.poold这个api的文档发现没有相对应的参数返回坐标值，不知道有没有类似的函数；
2. 如何新开发一个api或者算子

----

1. 目前pool2d/3d都没法获取坐标：https://www.paddlepaddle.org.cn/documentation/docs/zh/api_guides/low_level/layers/pooling.html#pool2d-pool3d
2. 如何构建一个新api：https://www.paddlepaddle.org.cn/documentation/docs/zh/advanced_guide/addon_development/new_op/index_cn.html，见新增api
