### ISSUE TITLE
【论文复现】pytorch中 .data 如何用paddle实现

### ISSUE THREAD

**Issue by chunfeng0301** [PaddlePaddle/Paddle#26292]
pytorch中 .data的语义是 获取 Variable 的 内部 Tensor；
论文复现中出现的 pytorch语句 v1 = torch.zeros_like(x.data)

如何用paddle实现 x.data?

**Comment by zhhsplendid** [comment]
假设你的Paddle Variable 是var，
可以调用 vat.get_tensor() 来获取tensor。

不过你这里需要zeros_like其实不知道如何获取tensor时，也可fill_constant为0，shape为x的shape，这种方式也能实现

**Comment by ysh329** [comment]
论文复现中出现的 pytorch语句 v1 = torch.zeros_like(x.data)

如何用paddle实现 x.data：

```python
import paddle.fluid as fluid
x = fluid.data(name='x', dtype='float32', shape=[3])
data = fluid.layers.zeros_like(x) # [0.0, 0.0, 0.0]
```
https://www.paddlepaddle.org.cn/documentation/docs/zh/api_cn/layers_cn/zeros_like_cn.html#zeros-like

此外，还可以参考TensorAPI：https://www.paddlepaddle.org.cn/documentation/docs/zh/api_cn/fluid_cn/Tensor_cn.html#tensor
