### ISSUE TITLE
【论文复现】请问paddle里有没有类似torch里的cpp_extension函数？ 如果没有，在动态图模式下，要怎么样调用CPP/C源码里的函数？

### ISSUE THREAD

**Issue by kgkzhiwen** [PaddlePaddle/Paddle#26299]
请问paddle里有没有类似torch里的cpp_extension函数？ 如果没有，在动态图模式下，要怎么样调用CPP/C源码里的函数？
`from torch.utils.cpp_extension import BuildExtension, CUDAExtension
`

**Comment by saxon-zh** [comment]
如果是想要新增OP的话可以看下这个文档：https://www.paddlepaddle.org.cn/documentation/docs/zh/advanced_guide/addon_development/new_op/index_cn.html

**Comment by ysh329** [comment]
如何在框架外部自定义C++ OP，见文档：https://www.paddlepaddle.org.cn/documentation/docs/zh/advanced_guide/addon_development/new_op/custom_op.html#c-op
