### ISSUE TITLE
【论文复现】使用“fluid.dygraph.nn.Conv3D”API的文档样例代码报错

### ISSUE THREAD

**Issue by EastSmith** [PaddlePaddle/Paddle#26295]
- **问题描述：**
1.新建Aistudio的PaddlePaddle1.80的GPU环境，并!pip install paddlepaddle-gpu==1.8.3.post97
2.copy飞桨文档Conv3D的样例代码到Aistudio上，代码地址：(https://paddlepaddle.org.cn/documentation/docs/zh/api_cn/dygraph_cn/Conv3D_cn.html#id4)
运行之后报错：
![image](https://user-images.githubusercontent.com/67545545/90298434-da8f4480-dec4-11ea-8186-f5a6b19184c5.png)
3.将代码改为如下图所示的代码，也报同样的错误“unsupported operand type(s) for /: 'float' and 'str'”
![image](https://user-images.githubusercontent.com/67545545/90298567-5a1d1380-dec5-11ea-91eb-5ae828376e1a.png)

4.尝试在其他环境下运行同样的代码，发现PaddlePaddle1.62的cpu环境下可以正常运行
![image](https://user-images.githubusercontent.com/67545545/90298659-a9634400-dec5-11ea-8c4c-2f4d1d8570b5.png)
- **请求回复：**
1.能否在issue里给出在PaddlePaddle1.83的GPU环境下“fluid.dygraph.nn.Conv3D”可以正常运行的代码示意。
2.如何修改上面报错代码，使之正常运行。

**Comment by xjhcassy** [comment]
Conv3D第一个参数不是name，或者你要的话就要加name='Conv3D'

**Comment by EastSmith** [comment]
> Conv3D第一个参数不是name，或者你要的话就要加name='Conv3D'

感谢！但是我经过测试发现加name='Conv3D'仍然会报错：“TypeError: __init__() got an unexpected keyword argument 'name'”
![image](https://user-images.githubusercontent.com/67545545/90303891-d2df9800-dee4-11ea-9ae2-8f27298157b4.png)

**Comment by EastSmith** [comment]
已经找到报错的一种解决方案了，加上“num_channels =3”这个参数就可以运行了
![image](https://user-images.githubusercontent.com/67545545/90303958-78930700-dee5-11ea-8b2a-a0bad92d4926.png)

**Comment by ysh329** [comment]
文档没有问题，还请查看Conv3D文档：https://www.paddlepaddle.org.cn/documentation/docs/zh/api_cn/dygraph_cn/Conv3D_cn.html#conv3d

注意参数顺序

```
Conv3D
class paddle.fluid.dygraph.Conv3D(num_channels, num_filters, filter_size, stride=1, padding=0, dilation=1, groups=None, param_attr=None, bias_attr=None, use_cudnn=True, act=None, dtype="float32")
```
