### ISSUE TITLE
[论文复现] 作业SIGSEGV unknow 不明异常Core Dumped

### ISSUE THREAD

**Issue by weiexcelpro** [PaddlePaddle/Paddle#26291]
Core Dumped

- 版本、环境信息：
    1）PaddlePaddle版本：1.8.0
    2）CPU：--
    3）GPU：V100, CUDA 9.2 CUDNN 7.3，
    4）Ubuntu 16. Python3

- 训练信息
    1）单机
    2）16GB

- 复现信息：如为报错，请给出复现环境、复现步骤
- 问题描述：请详细描述您的问题，同步贴出报错信息、日志、可复现的代码片段

![image](https://user-images.githubusercontent.com/37108001/90255561-04217f00-de77-11ea-860c-5e48cb665c55.png)

![image](https://user-images.githubusercontent.com/37108001/90255600-13083180-de77-11ea-84cc-454233bf2331.png)

是在复现营作业链接启动环境的
https://aistudio.baidu.com/bdvgpu32g/user/373608/691575/notebooks/691575.ipynb，

作业的链接是这个：

https://aistudio.baidu.com/aistudio/projectdetail/691575

用户联系方式: 邮箱: 83545202@163.com

---------------
经AIStudio侧查看, 表示看不懂该错误信息是什么意思

**Comment by zhhsplendid** [comment]
这个是SIGSEGV，但原因是unknown，您留下的作业链接对我们其实是不可见的。不知道能否给一些其他关键信息或关键代码？

**Comment by ysh329** [comment]
信息太少，还请提供更多信息~
