### ISSUE TITLE
论文复现：如何实现下列语句，torch.FloatTensor([[[[-0.5,0,0.5]]]]).repeat(1,1,1,1)

### ISSUE THREAD

**Issue by liu824** [PaddlePaddle/Paddle#26306]
issue中有搜到一些，但并没有很明确的对该问题进行说明

**Comment by yuctian** [comment]
可以考虑通过定义卷积使用param_attr中的numpy初始化卷积的方法

**Comment by ysh329** [comment]
如果是动态图，可以考虑用numpy：https://www.paddlepaddle.org.cn/documentation/docs/zh/api_cn/fluid_cn/Variable_cn.html#numpy

如
```python
import paddle.fluid as fluid
from paddle.fluid.dygraph.base import to_variable
from paddle.fluid.dygraph import Linear
import numpy as np

data = np.random.uniform(-1, 1, [30, 10, 32]).astype('float32')
with fluid.dygraph.guard():
    linear = Linear(32, 64)
    data = to_variable(data)
    x = linear(data)
    print(x.numpy())
```

另外，可以参考Tensor API：https://www.paddlepaddle.org.cn/documentation/docs/zh/api_cn/fluid_cn/Tensor_cn.html#tensor

如

```python
import paddle.fluid as fluid
import numpy as np

t = fluid.Tensor()
t.set(np.ndarray([5, 30]), fluid.CPUPlace())
print(t.shape())  # [5, 30]
```

**Comment by liu824** [comment]
> 如果是动态图，可以考虑用numpy：https://www.paddlepaddle.org.cn/documentation/docs/zh/api_cn/fluid_cn/Variable_cn.html#numpy
> 
> 如
> 
> ```python
> import paddle.fluid as fluid
> from paddle.fluid.dygraph.base import to_variable
> from paddle.fluid.dygraph import Linear
> import numpy as np
> 
> data = np.random.uniform(-1, 1, [30, 10, 32]).astype('float32')
> with fluid.dygraph.guard():
>     linear = Linear(32, 64)
>     data = to_variable(data)
>     x = linear(data)
>     print(x.numpy())
> ```
> 
> 另外，可以参考Tensor API：https://www.paddlepaddle.org.cn/documentation/docs/zh/api_cn/fluid_cn/Tensor_cn.html#tensor
> 
> 如
> 
> ```python
> import paddle.fluid as fluid
> import numpy as np
> 
> t = fluid.Tensor()
> t.set(np.ndarray([5, 30]), fluid.CPUPlace())
> print(t.shape())  # [5, 30]
> ```

我需要在初始化的时候使用，请问初始化的时候如何加在guard下呢
