### ISSUE TITLE
help 关于新建OP操作问题 

### ISSUE THREAD

**Issue by ARDUJS** [PaddlePaddle/Paddle#26302]
### 环境
- python 3.7
- PaddlePaddle = 1.7.2
### 问题
我新建了一个OP，我希望输入sequence对象

![input](https://user-images.githubusercontent.com/20811685/90305680-a08b6600-def7-11ea-947c-04e8a58141c4.png)

，输出也是sequence对象，可是我安照官网提供的案例，

```
def create_tmp_var(program, name, dtype, shape):
            # t = fluid.create_lod_tensor(np.ndarray([5, 30]), [[2, 3]], fluid.CPUPlace())
            return program.current_block().create_var(name=name, dtype=dtype, shape=shape)
            
o1 = create_tmp_var(fluid.default_main_program(), name='o1', dtype='float32', shape=[unpad_feature.shape[0], unpad_feature.shape[1]*2])
```

![image](https://user-images.githubusercontent.com/20811685/90305695-b4cf6300-def7-11ea-929e-b47b7db4543c.png)

输出并不是sequence对象，

![image](https://user-images.githubusercontent.com/20811685/90305722-e5af9800-def7-11ea-962f-155b45c8acb9.png)

导致我后续的操作报错

![image](https://user-images.githubusercontent.com/20811685/90305743-2ad3ca00-def8-11ea-8e02-64a2b769fab3.png)

**Comment by ysh329** [comment]
好的收到，能提供一下完整代码嘛。此外，可以看下这个文档： https://www.paddlepaddle.org.cn/documentation/docs/zh/beginners_guide/basic_concept/lod_tensor.html#id3

对应代码实例部分：

```python
x = fluid.layers.data(name='x', shape=[1], dtype='float32', lod_level=1)
y = fluid.layers.data(name='y', shape=[1], dtype='float32', lod_level=2)
out = fluid.layers.sequence_expand(x=x, y=y, ref_level=0)
```
更多见文档。
