### ISSUE TITLE
blas_impl.h:747: Expected dim_a.width_ == dim_b.height_, but received dim_a.width_:1 != dim_b.height_:784

### ISSUE THREAD

**Issue by hxl523** [PaddlePaddle/Paddle#26318]
报错提示：[Hint: Expected dim_a.width_ == dim_b.height_, but received dim_a.width_:1 != dim_b.height_:784.] at (/paddle/paddle/fluid/operators/math/blas_impl.h:747)
错误发生在：课节5：第二章一个案例吃透深度学习(上)：[项目]2.通过极简方案快速构建手写数字识别模型
将所有的教程代码，写到一个model.py文件，并在ai studio运行python model.py,最后预测:
#  预测输出取整，即为预测的数字，打印结果
    print("本次预测的数字是", result.numpy().astype('int32'))的时候出现这个错误
notebook教程里正常运行
项目地址：https://aistudio.baidu.com/bjcpu/user/52668/719950/notebooks/719950.ipynb

**Comment by ysh329** [comment]
你好，请问你是不是有修改代码
