### ISSUE TITLE
在pycharm上运行PaddleSeg人像分割出现了以下问题，请各位大神帮忙看一下是什么问题

### ISSUE THREAD

**Issue by xue160709** [PaddlePaddle/Paddle#26317]
Paddle version: 1.8.4
Paddle With CUDA: False
OS: macOs 10.15.5
Python version: 3.5.4
CUDA version: None
cuDNN version: None
Nvidia driver version: None

在pycharm上运行PaddleSeg实战——人像分割出现了以下问题，请各位大神帮忙看一下是什么问题
Argv: video_infer.py --model_dir pretrained_weights/humanseg_lite_inference
!!! The CPU_NUM is not specified, you should set CPU_NUM in the environment variable list.
CPU_NUM indicates that how many CPUPlace are used in the current task.
And if this parameter are set as N (equal to the number of physical CPU core) the program may be faster.

export CPU_NUM=8 # for example, set CPU_NUM as number of physical CPU core which is 8.

!!! The default number of CPU_NUM=1.
2020-08-15 18:53:05 [INFO]      Model[HumanSegLite] loaded.
W0815 18:53:07.191929 1750080960 init.cc:226] Warning: PaddlePaddle catches a failure signal, it may not work properly
W0815 18:53:07.191959 1750080960 init.cc:228] You could check whether you killed PaddlePaddle thread/process accidentally or report the case to PaddlePaddle
W0815 18:53:07.191964 1750080960 init.cc:231] The detail failure signal is:

W0815 18:53:07.191968 1750080960 init.cc:234] *** Aborted at 1597488787 (unix time) try "date -d @1597488787" if you are using GNU date ***
W0815 18:53:07.192224 1750080960 init.cc:234] PC: @                0x0 (unknown)
W0815 18:53:07.194974 1750080960 init.cc:234] *** SIGSEGV (@0x10) received by PID 65640 (TID 0x7fff68501dc0) stack trace: ***
W0815 18:53:07.195127 1750080960 init.cc:234]     @        0x1014305fd _sigtramp
W0815 18:53:07.195693 1750080960 init.cc:234]     @        0x100029489 CFBundleCopyBundleURL
W0815 18:53:07.197759 1750080960 init.cc:234]     @        0x10b68a8b0 QLibraryInfo::location()
W0815 18:53:07.197899 1750080960 init.cc:234]     @        0x10b68ab0d QLibraryInfo::location()
W0815 18:53:07.198015 1750080960 init.cc:234]     @        0x10b86f754 QCoreApplication::libraryPathsLocked()
W0815 18:53:07.198137 1750080960 init.cc:234]     @        0x10b8700b4 QCoreApplication::addLibraryPath()
W0815 18:53:07.200505 1750080960 init.cc:234]     @        0x10b0490c6 QPlatformIntegrationFactory::keys()
W0815 18:53:07.200915 1750080960 init.cc:234]     @        0x10b05630a QGuiApplicationPrivate::createPlatformIntegration()
W0815 18:53:07.201041 1750080960 init.cc:234]     @        0x10b0578ab QGuiApplicationPrivate::createEventDispatcher()
W0815 18:53:07.201156 1750080960 init.cc:234]     @        0x10b86b47f QCoreApplicationPrivate::init()
W0815 18:53:07.201256 1750080960 init.cc:234]     @        0x10b052009 QGuiApplicationPrivate::init()
W0815 18:53:07.203972 1750080960 init.cc:234]     @        0x10aa7e0fa QApplicationPrivate::init()
W0815 18:53:07.204573 1750080960 init.cc:234]     @        0x10511d179 GuiReceiver::GuiReceiver()
W0815 18:53:07.205054 1750080960 init.cc:234]     @        0x10511c559 cvShowImage
W0815 18:53:07.205572 1750080960 init.cc:234]     @        0x105114393 cv::imshow()
W0815 18:53:07.205976 1750080960 init.cc:234]     @        0x1040e0576 pyopencv_cv_imshow()
W0815 18:53:07.206135 1750080960 init.cc:234]     @        0x1007aed09 PyCFunction_Call
W0815 18:53:07.206254 1750080960 init.cc:234]     @        0x10083ce34 PyEval_EvalFrameEx
W0815 18:53:07.206360 1750080960 init.cc:234]     @        0x10083b424 PyEval_EvalFrameEx
W0815 18:53:07.206776 1750080960 init.cc:234]     @        0x10083d8a0 _PyEval_EvalCodeWithName
W0815 18:53:07.206892 1750080960 init.cc:234]     @        0x10083da01 PyEval_EvalCode
W0815 18:53:07.207000 1750080960 init.cc:234]     @        0x10086bb7e PyRun_FileExFlags
W0815 18:53:07.207101 1750080960 init.cc:234]     @        0x10086be2f PyRun_SimpleFileExFlags
W0815 18:53:07.207209 1750080960 init.cc:234]     @        0x100884d12 Py_Main

**Comment by StudyHou66** [comment]
同样的问题，楼主解决了吗
