### ISSUE TITLE
[论文复现]  动态图如何使用AIStudio中的脚本模式进行训练（动态图怎样用分布式训练方式）

### ISSUE THREAD

**Issue by yuctian** [PaddlePaddle/Paddle#26325]
我在飞浆官网里没有找到相关样例，只有静态图的例子

**Comment by MRXLT** [comment]
你好，分布式训练目前只支持静态图的方式，对动态图的支持正在开发中

**Comment by phlrain** [comment]
https://www.paddlepaddle.org.cn/documentation/docs/zh/beginners_guide/basic_concept/dygraph/DyGraph.html#id10
建议使用这种进行
