### ISSUE TITLE
文档：使用Python和Numpy构建神经网络模型 - 勘误

### ISSUE THREAD

**Issue by limengning** [PaddlePaddle/Paddle#26321]
[https://www.paddlepaddle.org.cn/tutorials/projectdetail/715255](使用Python和Numpy构建神经网络模型) 一文中代码有错误：
![image](https://user-images.githubusercontent.com/10029844/90323587-b51e3b80-df95-11ea-8be4-3e9e7c9dc91e.png)

**Comment by MRXLT** [comment]
感谢反馈，我们会进行修正
