### ISSUE TITLE
paddlepaddle是否提供了上传自己数据的方式

### ISSUE THREAD

**Issue by minghuisvn** [PaddlePaddle/Paddle#26326]
我想用PaddlePaddle建模自己的数据，notebook上上传总是失败。新建项目上传数据集可以，但是数据有一定保密性，上传的数据集会不会被其他人看到。

**Comment by MRXLT** [comment]
你好，是想要在aistudio上上传数据集吗，默认创建的项目都是私有的，不设置为公开，别人是无法使用你的数据集的。可以先使用没有保密性的数据试一下。
