### ISSUE TITLE
【论文复现】UGATIT 关于平台paddle1.8复现过程中var函数的Out of memory error on GPU 0问题

### ISSUE THREAD

**Issue by chfhf** [PaddlePaddle/Paddle#26323]
![1](https://user-images.githubusercontent.com/19964528/90325087-ba858100-dfa9-11ea-8b4a-7bf57faced80.jpg)
**运行到此处都会内存爆掉，排查发现ln_mean没问题，是var(input,dim=[1, 2, 3],keep_dim=True)的问题。**
![2](https://user-images.githubusercontent.com/19964528/90325217-6c717d00-dfab-11ea-89d0-c8bd243fd327.png)

![3](https://user-images.githubusercontent.com/19964528/90325091-edc81000-dfa9-11ea-9904-07cef6a8b19c.jpg)
**下图为var函数，不论我自己写的还是别人写的var函数都会炸掉，不知为何，下图是别人写的，求解答**
![4](https://user-images.githubusercontent.com/19964528/90325163-d50c2a00-dfaa-11ea-96cf-9c5f540c7448.png)

**Comment by MRXLT** [comment]
你好，这个看上去是显存不足，建议减小batch size

**Comment by chfhf** [comment]
> 你好，这个看上去是显存不足，建议减小batch size

batch_size与原论文代码一致默认为1，具体就是循环运行完第一个自适应残差块，到了第二个就爆内存了，不知道该怎么修改，
![12](https://user-images.githubusercontent.com/19964528/90336128-4af4ad80-e00c-11ea-87a6-93bb2ebe81bc.png)
![21](https://user-images.githubusercontent.com/19964528/90336133-4d570780-e00c-11ea-9f87-75f3d2e5a02b.png)

**Comment by MRXLT** [comment]
请问使用的gpu显存是多少

**Comment by chfhf** [comment]
> 请问使用的gpu显存是多少
![22](https://user-images.githubusercontent.com/19964528/90386160-babf7280-e0b6-11ea-87bf-69f39458ebf2.png)
这是最近运行的一次，错误信息如下：
----------------------
Error Message Summary:
----------------------
ResourceExhaustedError: 

Out of memory error on GPU 0. Cannot allocate 4.125977GB memory on GPU 0, available memory is only 3.666870GB.

Please check whether there is any other process using GPU 0.
1. If yes, please stop them, or start PaddlePaddle on another GPU.
2. If no, please decrease the batch size of your model. 

 at (/paddle/paddle/fluid/memory/allocation/cuda_allocator.cc:69)

然后我尝试停止项目并重启，
第一次：Out of memory error on GPU 0. Cannot allocate 1.000000GB memory on GPU 0，available memory is only  85。000000MB
后几次：Out of memory error on GPU 0. Cannot allocate 1.000000GB memory on GPU 0，available memory is only  950MB
最近是：Out of memory error on GPU 0. Cannot allocate 4.125977GB memory on GPU 0, available memory is only 3.666870GB.
不知道是不是因为版本问题，无法完全GPU，不知道下图这个会影响吗？
![11](https://user-images.githubusercontent.com/19964528/90386908-d119fe00-e0b7-11ea-93df-46f97fbf88b8.png)

W0817 18:29:36.685433  2225 device_context.cc:252] Please NOTE: device: 0, CUDA Capability: 70, Driver API Version: 10.1, Runtime API Version: 9.0
W0817 18:29:36.689229  2225 device_context.cc:260] device: 0, cuDNN Version: 7.3.

**Comment by chfhf** [comment]
> > 请问使用的gpu显存是多少
> > ![22](https://user-images.githubusercontent.com/19964528/90386160-babf7280-e0b6-11ea-87bf-69f39458ebf2.png)
> > 这是最近运行的一次，错误信息如下：
> 
> ## Error Message Summary:
> ResourceExhaustedError:
> 
> Out of memory error on GPU 0. Cannot allocate 4.125977GB memory on GPU 0, available memory is only 3.666870GB.
> 
> Please check whether there is any other process using GPU 0.
> 
> 1. If yes, please stop them, or start PaddlePaddle on another GPU.
> 2. If no, please decrease the batch size of your model.
> 
> at (/paddle/paddle/fluid/memory/allocation/cuda_allocator.cc:69)
> 
> 然后我尝试停止项目并重启，
> 第一次：Out of memory error on GPU 0. Cannot allocate 1.000000GB memory on GPU 0，available memory is only 85。000000MB
> 后几次：Out of memory error on GPU 0. Cannot allocate 1.000000GB memory on GPU 0，available memory is only 950MB
> 最近是：Out of memory error on GPU 0. Cannot allocate 4.125977GB memory on GPU 0, available memory is only 3.666870GB.
> 不知道是不是因为版本问题，无法完全GPU，不知道下图这个会影响吗？
> ![11](https://user-images.githubusercontent.com/19964528/90386908-d119fe00-e0b7-11ea-93df-46f97fbf88b8.png)
> 
> W0817 18:29:36.685433 2225 device_context.cc:252] Please NOTE: device: 0, CUDA Capability: 70, Driver API Version: 10.1, Runtime API Version: 9.0
> W0817 18:29:36.689229 2225 device_context.cc:260] device: 0, cuDNN Version: 7.3.



> 请问使用的gpu显存是多少

![7678dcaeee64b610af8ddff60b23218](https://user-images.githubusercontent.com/19964528/90387173-47b6fb80-e0b8-11ea-84ec-c45c58931bea.png)
同时性能监控显示内存接近90%，但报错结果好像也对不上，所以一直卡在这个地方，不知道该怎么继续

**Comment by MRXLT** [comment]
可以试一下用recompute op减小显存占用
https://www.paddlepaddle.org.cn/documentation/docs/zh/api_cn/optimizer_cn/RecomputeOptimizer_cn.html#recomputeoptimizer

**Comment by chfhf** [comment]
此问题已自行解决，UGATIT遇到显存爆掉，基本就是网络中，计算矩阵乘法的问题，需要自行对所有的shape 比对源代码，比较突出的是gmp_weight和gap_weight两处取list(xxx.parameters())[0]此处的shape，paddle和pytorch不一样，注意
