### ISSUE TITLE
[论文复现] 如何获取优化器的参数信息？

### ISSUE THREAD

**Issue by gbstack** [PaddlePaddle/Paddle#26328]
请问如何获取优化器的参数信息？

比如Adam优化器的moment和time step值

**Comment by MRXLT** [comment]
你好，对于lr/beta参数可以在创建adam的时候指定使用的variable，在训练的时候获取对应的variable。但是对于moment和time step这种并不是优化器参数的值暂时无法获取

**Comment by gbstack** [comment]
你好，就是我想检查下优化器的这些值在读取之前保存的参数时，是否正确的读取，该怎么做呢

**Comment by MRXLT** [comment]
动态图可以使用tensor的numpt接口
http://180.76.141.178/documentation/docs/zh/beginners_guide/dygraph/DyGraph.html#id15
静态图可以使用print api
http://180.76.141.178/documentation/docs/zh/api_cn/layers_cn/Print_cn.html#print
对于优化器的一些中间变量可以调用adam.get_opti_var_name_list来获取变量名，然后通过fluid.global_scope().find_var(var_name).get_tensor()获取对应的tensor，然后使用以上方法打印

**Comment by gbstack** [comment]
谢谢 get_opti_var_name_list方法可以成功获取变量名

部分结果
000 = {str} 'conv2d_101.w_0_moment1_0'
001 = {str} 'conv2d_101.w_0_moment2_0'
002 = {str} 'conv2d_101.w_0_beta1_pow_acc_0'
003 = {str} 'conv2d_101.w_0_beta2_pow_acc_0'

但是numpy方法试了下，优化器没有这个方法

还有fluid.global_scope().find_var('conv2d_101.w_0_moment1_0').get_tensor()
其中的fluid.global_scope().find_var('conv2d_101.w_0_moment1_0')返回的是None..

**Comment by MRXLT** [comment]
numpy是tensor的方法，动态图下获取adam中的所有tensor值可以用state_dict
示例代码如下
```
import paddle
import numpy as np
import paddle.fluid as fluid
paddle.disable_static()
inp = np.random.uniform(-0.1, 0.1, [10, 10]).astype("float32")
linear = paddle.nn.Linear(10, 10)
inp = paddle.to_tensor(inp)
out = linear(inp)
loss = paddle.mean(out)

beta1 = paddle.to_tensor([0.9], dtype="float32")
beta2 = paddle.to_tensor([0.99], dtype="float32")

adam = paddle.optimizer.Adam(learning_rate=0.1,
        parameters=linear.parameters(),
        weight_decay=0.01)
out.backward()
adam.step()
adam.clear_grad()

tensor_list = adam.get_opti_var_name_list()
print(beta1.numpy())#beta1的值
print(adam.state_dict())#优化器中所有tensor的值，类型是dict
```
