### ISSUE TITLE
【黄埔学院】windows下编译paddle1.8.4+trt的推理库遇到tensorrt的问题

### ISSUE THREAD

**Issue by RayCAS2017** [PaddlePaddle/Paddle#26335]
- 版本、环境信息：
    1）PaddlePaddle版本：v1.8.4
    2）GPU,1060，CUDA10.0和CUDNN7.6
    4）系统环境：win10家庭版， vs 2015
- 安装方式信息：
1）本地编译：请提供cmake命令，
cmake .. -G "Visual Studio 14 2015 Win64" -DCMAKE_BUILD_TYPE=Release -DWITH_GPU=ON -DWITH_TESTING=OFF -DON_INFER=ON -DWITH_PYTHON=ON -DWITH_MKL=OFF -DWITH_MKLDNN=OFF -DCUDA_ARCH_NAME=All -DPYTHON_EXECUTABLE=C:\\Users\\ray\\.conda\\envs\\paddle1.8\\python.exe -DCUDA_TOOLKIT_ROOT_DIR="C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v10.0" -DTENSORRT_ROOT="E:\\workstation\\ProjectLocal\\TensorRT-7.0.0.11" -DTENSORRT_INCLUDE_DIR="E:\\workstation\\ProjectLocal\\TensorRT-7.0.0.11\\include" -DTENSORRT_LIBRARY_DIR="E:\\workstation\\ProjectLocal\\TensorRT-7.0.0.11\\lib" -DFLUID_INFERENCE_INSTALL_DIR="E:\\workstation\\ProjectLocal\\Paddle2\\infer_lib"

- 问题描述：
编译paddle1.8.4的C++预测库时，遇到tensorrt的问题
![微信图片_20200816224508](https://user-images.githubusercontent.com/29969779/90337413-ea1da300-e014-11ea-9579-9b55c18f35f8.png)

**Comment by MRXLT** [comment]
你好，建议使用tensorrt 6.0试一下

**Comment by RayCAS2017** [comment]
之前有试过1.8.4+trt6.0，也遇到相同的问题。应该不是trt版本的问题。Paddle1.8.4相对Paddle1.8.3关于trt增加一些内容。感觉报错是Paddle\paddle\fluid\inference\tensorrt下面helper.h文件中的新增加这句话：
<img width="498" alt="无标题2" src="https://user-images.githubusercontent.com/29969779/90353654-5a5e1000-e079-11ea-893a-66f649baaa21.png">

这句话是做什么用的？

**Comment by xinsuinizhuan** [comment]
>     * 编译paddle1.8.4的C++预测库时，

你能编译过去？

**Comment by xinsuinizhuan** [comment]
> 
> 
>     * 版本、环境信息：
>          1）PaddlePaddle版本：v1.8.4
>          2）GPU,1060，CUDA10.0和CUDNN7.6
>          4）系统环境：win10家庭版， vs 2015
> 
>     * 安装方式信息：
>       1）本地编译：请提供cmake命令，
>       cmake .. -G "Visual Studio 14 2015 Win64" -DCMAKE_BUILD_TYPE=Release -DWITH_GPU=ON -DWITH_TESTING=OFF -DON_INFER=ON -DWITH_PYTHON=ON -DWITH_MKL=OFF -DWITH_MKLDNN=OFF -DCUDA_ARCH_NAME=All -DPYTHON_EXECUTABLE=C:\Users\ray\.conda\envs\paddle1.8\python.exe -DCUDA_TOOLKIT_ROOT_DIR="C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.0" -DTENSORRT_ROOT="E:\workstation\ProjectLocal\TensorRT-7.0.0.11" -DTENSORRT_INCLUDE_DIR="E:\workstation\ProjectLocal\TensorRT-7.0.0.11\include" -DTENSORRT_LIBRARY_DIR="E:\workstation\ProjectLocal\TensorRT-7.0.0.11\lib" -DFLUID_INFERENCE_INSTALL_DIR="E:\workstation\ProjectLocal\Paddle2\infer_lib"
> 
>     * 问题描述：
>       编译paddle1.8.4的C++预测库时，遇到tensorrt的问题
>       ![微信图片_20200816224508](https://user-images.githubusercontent.com/29969779/90337413-ea1da300-e014-11ea-9579-9b55c18f35f8.png)

我这边，一直在下载库，下载不了，就编译报错。

**Comment by jeng1220** [comment]
@cryoco ,
我剛仔細看log，這問題應是compiler對C++的auto實現問題，vs compiler遇到auto轉型失敗，故問題不在`getPluginRegistry`。

[tensorrt.h#L38](https://github.com/PaddlePaddle/Paddle/blob/release/1.8/paddle/fluid/platform/dynload/tensorrt.h#L38) 回傳為的型別是 `auto`，而[tensorrt.h#L45](https://github.com/PaddlePaddle/Paddle/blob/release/1.8/paddle/fluid/platform/dynload/tensorrt.h#L45) 會一律強制回傳 `nullptr`。

這和我們之前在群上討論的 #26283 是類似的問題，按Paddle v1.8的寫法會有問題，因不是所有函式的回傳型別都是指針，例如`getInferLibVersion`的回傳型別是int，在[tensorrt.h#L45](https://github.com/PaddlePaddle/Paddle/blob/release/1.8/paddle/fluid/platform/dynload/tensorrt.h#L45)會遇到編譯時期轉型錯誤，故我建議用`PADDLE_ENFORCE_NOT_NULL` 取代一律回傳 nullptr 的寫法
