### ISSUE TITLE
windows10 vs2019 编译预测库，实在是编译不过去啊，编译一天，一直报错，可以不可以把要用的库，给弄个百度网盘，上传一下？

### ISSUE THREAD

**Issue by xinsuinizhuan** [PaddlePaddle/Paddle#26330]
为使您的问题得到快速解决，在建立Issue前，请您先通过如下方式搜索是否有相似问题:【搜索issue关键字】【使用labels筛选】【官方文档】

建立issue时，为快速解决问题，请您根据使用情况给出如下信息：
- 标题：请包含关键词“安装错误”/“编译错误”，例如“Mac编译错误”
- 版本、环境信息：
    1）PaddlePaddle版本：请提供您的PaddlePaddle版本号（如1.1）或CommitID
    2）CPU：请提供CPU型号，MKL/OpenBlas/MKLDNN/等数学库的使用情况
    3）GPU：请提供GPU型号，CUDA和CUDNN版本号
    4）系统环境：请说明系统类型、版本（如Mac OS 10.14）、Python版本
注：您可以通过执行[summary_env.py](https://github.com/PaddlePaddle/Paddle/blob/develop/tools/summary_env.py)获取以上信息。
- 安装方式信息：
1）pip安装/docker安装
2）本地编译：请提供cmake命令，编译命令
3）docker编译：请提供docker镜像，编译命令            
  特殊环境请注明：如离线安装等
- 复现信息：如为报错，请给出复现环境、复现步骤
- 问题描述：请详细描述您的问题，同步贴出报错信息、日志/代码关键片段

Thank you for contributing to PaddlePaddle.
Before submitting the issue, you could search issue in Github in case that there was a similar issue submitted or resolved before.
If there is no solution,please make sure that this is an installation issue including the following details:
**System information**
-PaddlePaddle version （eg.1.1）or CommitID
-CPU: including CPUMKL/OpenBlas/MKLDNN version
-GPU: including CUDA/CUDNN version
-OS Platform (eg. Mac OS 10.14)
-Python version
- Install method: pip install/install with docker/build from source(without docker)/build within docker
- Other special cases that you think may be related to this problem, eg. offline install, special internet condition 
Note: You can get most of the information by running [summary_env.py](https://github.com/PaddlePaddle/Paddle/blob/develop/tools/summary_env.py).   

**To Reproduce**
Steps to reproduce the behavior
**Describe your current behavior**
**Code to reproduce the issue**
**Other info / logs**

**Comment by xinsuinizhuan** [comment]
7>-- Had to git clone more than once:
7>CMake Error at F:/baidu_pp/Paddle-develop/build/third_party/protobuf/tmp/extern_protobuf-gitclone.cmake:31 (message):
7>          3 times.
7>  Failed to clone repository:
7>  'https://github.com/protocolbuffers/protobuf.git'
7>
7>
7>已完成生成项目“extern_protobuf.vcxproj”的操作 - 失败。
12>CUSTOMBUILD : error : RPC failed; curl 18 transfer closed with outstanding read data remaining
12>fatal: the remote end hung up unexpectedly
12>fatal: early EOF
12>fatal: index-pack failed
12>Cloning into 'extern_eigen3'..

**Comment by wadefelix** [comment]
> 7>-- Had to git clone more than once:
> 7>CMake Error at F:/baidu_pp/Paddle-develop/build/third_party/protobuf/tmp/extern_protobuf-gitclone.cmake:31 (message):
> 7> 3 times.
> 7> Failed to clone repository:
> 7> 'https://github.com/protocolbuffers/protobuf.git'
> 7>
> 7>
> 7>已完成生成项目“extern_protobuf.vcxproj”的操作 - 失败。
> 12>CUSTOMBUILD : error : RPC failed; curl 18 transfer closed with outstanding read data remaining
> 12>fatal: the remote end hung up unexpectedly
> 12>fatal: early EOF
> 12>fatal: index-pack failed
> 12>Cloning into 'extern_eigen3'..

哈哈，这个问题我刚好解了，能编译了，但是整个工程我还没有完全编译完。你可以看下这个修改 https://github.com/wadefelix/Paddle/commit/ecb44dd6078ee738dcff765bd5538901ac142a6d
官方指的protobuf的代码比较旧，我用protobuf最新的master分支可以编译。
这个修改里另外关于eigen那个，你可以不管。我这儿下载github代码有点儿慢，所以有些大的软件库我只好给建了我本地的镜像库，让这套编译脚本拉我本地代码加速的。

**Comment by xinsuinizhuan** [comment]
> 译完。你可以看下这个修改 [wadefelix@ecb44dd](https://github.com/wadefelix/Paddle/commit/ecb44dd6078ee738dcff765bd5538901ac142a6d)
> 官方指的protobuf的代码比较旧，

您QQ多少，可否加个QQ或者微信，我的QQ742721388，请多指教！

**Comment by xinsuinizhuan** [comment]
> 
> 
> > 7>-- Had to git clone more than once:
> > 7>CMake Error at F:/baidu_pp/Paddle-develop/build/third_party/protobuf/tmp/extern_protobuf-gitclone.cmake:31 (message):
> > 7> 3 times.
> > 7> Failed to clone repository:
> > 7> 'https://github.com/protocolbuffers/protobuf.git'
> > 7>
> > 7>
> > 7>已完成生成项目“extern_protobuf.vcxproj”的操作 - 失败。
> > 12>CUSTOMBUILD : error : RPC failed; curl 18 transfer closed with outstanding read data remaining
> > 12>fatal: the remote end hung up unexpectedly
> > 12>fatal: early EOF
> > 12>fatal: index-pack failed
> > 12>Cloning into 'extern_eigen3'..
> 
> 哈哈，这个问题我刚好解了，能编译了，但是整个工程我还没有完全编译完。你可以看下这个修改 [wadefelix@ecb44dd](https://github.com/wadefelix/Paddle/commit/ecb44dd6078ee738dcff765bd5538901ac142a6d)
> 官方指的protobuf的代码比较旧，我用protobuf最新的master分支可以编译。
> 这个修改里另外关于eigen那个，你可以不管。我这儿下载github代码有点儿慢，所以有些大的软件库我只好给建了我本地的镜像库，让这套编译脚本拉我本地代码加速的。

或者能看到我可以把所有库一个一个都下载都本地，在本地的话，放到哪个文件夹，它会自动加载？

**Comment by wadefelix** [comment]
> > > 7>-- Had to git clone more than once:
> > > 7>CMake Error at F:/baidu_pp/Paddle-develop/build/third_party/protobuf/tmp/extern_protobuf-gitclone.cmake:31 (message):
> > > 7> 3 times.
> > > 7> Failed to clone repository:
> > > 7> 'https://github.com/protocolbuffers/protobuf.git'
> > > 7>
> > > 7>
> > > 7>已完成生成项目“extern_protobuf.vcxproj”的操作 - 失败。
> > > 12>CUSTOMBUILD : error : RPC failed; curl 18 transfer closed with outstanding read data remaining
> > > 12>fatal: the remote end hung up unexpectedly
> > > 12>fatal: early EOF
> > > 12>fatal: index-pack failed
> > > 12>Cloning into 'extern_eigen3'..
> > 
> > 
> > 哈哈，这个问题我刚好解了，能编译了，但是整个工程我还没有完全编译完。你可以看下这个修改 [wadefelix@ecb44dd](https://github.com/wadefelix/Paddle/commit/ecb44dd6078ee738dcff765bd5538901ac142a6d)
> > 官方指的protobuf的代码比较旧，我用protobuf最新的master分支可以编译。
> > 这个修改里另外关于eigen那个，你可以不管。我这儿下载github代码有点儿慢，所以有些大的软件库我只好给建了我本地的镜像库，让这套编译脚本拉我本地代码加速的。
> 
> 或者能看到我可以把所有库一个一个都下载都本地，在本地的话，放到哪个文件夹，它会自动加载？

本地别的，和Paddle不同的文件夹就可以， 修改cmake/目录下需要修改的三方模块的.cmake文件，找到源地址，修改为你保存那个具体git项目的本地目录也可以（git本身就支持本地文件系统作为upstream）。这样就可以让这套编译系统从本地clone代码了。

**Comment by wadefelix** [comment]
我编译完了，wheel包编译制作出来了，但是fluid有关的6个工程失败了。

**Comment by ShawnXsw** [comment]
Paddle\cmake\external\*.cmake 源切换为gitee.com即可

**Comment by xinsuinizhuan** [comment]
> 
> 
> Paddle\cmake\external*.cmake 源切换为gitee.com即可

怎么换？
https://github.com/sabreshao/hipeigen.git 换成 https://gitee.com/sabreshao/hipeigen.git?这更换后，资源都没有

**Comment by wadefelix** [comment]
> > Paddle\cmake\external*.cmake 源切换为gitee.com即可
> 
> 怎么换？
> https://github.com/sabreshao/hipeigen.git 换成 [https://gitee.com/sabreshao/hipeigen.git?这更换后，资源都没有](https://gitee.com/sabreshao/hipeigen.git?%E8%BF%99%E6%9B%B4%E6%8D%A2%E5%90%8E%EF%BC%8C%E8%B5%84%E6%BA%90%E9%83%BD%E6%B2%A1%E6%9C%89)

gitee有个官方的mirror项目，会定义同步上万个仓库。但是也就仅这么多。其它的就要靠自己搜索或建同步项目了。
这个可不是简单把地址里的github替换成gitee这么简单。

我建议若想这么用的话，可以直接clone到本地后，把cmake里的地址改成本地文件系统地址即可。

**Comment by xinsuinizhuan** [comment]
> 
> 
> > > Paddle\cmake\external*.cmake 源切换为gitee.com即可
> > 
> > 
> > 怎么换？
> > https://github.com/sabreshao/hipeigen.git 换成 [https://gitee.com/sabreshao/hipeigen.git?这更换后，资源都没有](https://gitee.com/sabreshao/hipeigen.git?%E8%BF%99%E6%9B%B4%E6%8D%A2%E5%90%8E%EF%BC%8C%E8%B5%84%E6%BA%90%E9%83%BD%E6%B2%A1%E6%9C%89)
> 
> gitee有个官方的mirror项目，会定义同步上万个仓库。但是也就仅这么多。其它的就要靠自己搜索或建同步项目了。
> 这个可不是简单把地址里的github替换成gitee这么简单。
> 
> 我建议若想这么用的话，可以直接clone到本地后，把cmake里的地址改成本地文件系统地址即可。

我试过，貌似不行，我改成了本地目录，但是它还只直接从github上去下载

**Comment by xinsuinizhuan** [comment]
楼主，可不可以，直接在cmake里面去修改，camke里面修改直接指向本地目录？

**Comment by ShawnXsw** [comment]
> > Paddle\cmake\external*.cmake 源切换为gitee.com即可
> 
> 怎么换？
> https://github.com/sabreshao/hipeigen.git 换成 [https://gitee.com/sabreshao/hipeigen.git?这更换后，资源都没有](https://gitee.com/sabreshao/hipeigen.git?%E8%BF%99%E6%9B%B4%E6%8D%A2%E5%90%8E%EF%BC%8C%E8%B5%84%E6%BA%90%E9%83%BD%E6%B2%A1%E6%9C%89)

给你我的吧：https://gitee.com/shawnxu226   里面有paddle third_party需要的镜像库

**Comment by xinsuinizhuan** [comment]
> 
> 
> > > Paddle\cmake\external*.cmake 源切换为gitee.com即可
> > 
> > 
> > 怎么换？
> > https://github.com/sabreshao/hipeigen.git 换成 [https://gitee.com/sabreshao/hipeigen.git?这更换后，资源都没有](https://gitee.com/sabreshao/hipeigen.git?%E8%BF%99%E6%9B%B4%E6%8D%A2%E5%90%8E%EF%BC%8C%E8%B5%84%E6%BA%90%E9%83%BD%E6%B2%A1%E6%9C%89)
> 
> 给你我的吧：https://gitee.com/shawnxu226 里面有paddle third_party需要的镜像库

非常感谢。我看了一下，您仓库里面有6个库：
![图片](https://user-images.githubusercontent.com/40679769/90381874-9791c480-e0b0-11ea-85fb-d0244344f360.png)
貌似，这个pp使用到的就这2个？prontbuf和openblas的有没有？

**Comment by ShawnXsw** [comment]
> > > > Paddle\cmake\external*.cmake 源切换为gitee.com即可
> > > 
> > > 
> > > 怎么换？
> > > https://github.com/sabreshao/hipeigen.git 换成 [https://gitee.com/sabreshao/hipeigen.git?这更换后，资源都没有](https://gitee.com/sabreshao/hipeigen.git?%E8%BF%99%E6%9B%B4%E6%8D%A2%E5%90%8E%EF%BC%8C%E8%B5%84%E6%BA%90%E9%83%BD%E6%B2%A1%E6%9C%89)
> > 
> > 
> > 给你我的吧：https://gitee.com/shawnxu226 里面有paddle third_party需要的镜像库
> 
> 非常感谢。我看了一下，您仓库里面有6个库：
> ![图片](https://user-images.githubusercontent.com/40679769/90381874-9791c480-e0b0-11ea-85fb-d0244344f360.png)
> 貌似，这个pp使用到的就这2个？prontbuf和openblas的有没有？

https://gitee.com/shawnxu226/projects   都有

**Comment by xinsuinizhuan** [comment]
> 
> 
> > > > > Paddle\cmake\external*.cmake 源切换为gitee.com即可
> > > > 
> > > > 
> > > > 怎么换？
> > > > https://github.com/sabreshao/hipeigen.git 换成 [https://gitee.com/sabreshao/hipeigen.git?这更换后，资源都没有](https://gitee.com/sabreshao/hipeigen.git?%E8%BF%99%E6%9B%B4%E6%8D%A2%E5%90%8E%EF%BC%8C%E8%B5%84%E6%BA%90%E9%83%BD%E6%B2%A1%E6%9C%89)
> > > 
> > > 
> > > 给你我的吧：https://gitee.com/shawnxu226 里面有paddle third_party需要的镜像库
> > 
> > 
> > 非常感谢。我看了一下，您仓库里面有6个库：
> > ![图片](https://user-images.githubusercontent.com/40679769/90381874-9791c480-e0b0-11ea-85fb-d0244344f360.png)
> > 貌似，这个pp使用到的就这2个？prontbuf和openblas的有没有？
> 
> https://gitee.com/shawnxu226/projects 都有

看到了。非常感谢。

**Comment by xinsuinizhuan** [comment]
> 
> 
> > > > > > Paddle\cmake\external*.cmake 源切换为gitee.com即可
> > > > > 
> > > > > 
> > > > > 怎么换？
> > > > > https://github.com/sabreshao/hipeigen.git 换成 [https://gitee.com/sabreshao/hipeigen.git?这更换后，资源都没有](https://gitee.com/sabreshao/hipeigen.git?%E8%BF%99%E6%9B%B4%E6%8D%A2%E5%90%8E%EF%BC%8C%E8%B5%84%E6%BA%90%E9%83%BD%E6%B2%A1%E6%9C%89)
> > > > 
> > > > 
> > > > 给你我的吧：https://gitee.com/shawnxu226 里面有paddle third_party需要的镜像库
> > > 
> > > 
> > > 非常感谢。我看了一下，您仓库里面有6个库：
> > > ![图片](https://user-images.githubusercontent.com/40679769/90381874-9791c480-e0b0-11ea-85fb-d0244344f360.png)
> > > 貌似，这个pp使用到的就这2个？prontbuf和openblas的有没有？
> > 
> > 
> > https://gitee.com/shawnxu226/projects 都有
> 
> 看到了。非常感谢。

这个替换的时候，怎么替换？https://gitee.com/shawnxu226/eigen-git-mirror/eigen-git-mirror.git?就是后缀是git,还是？https://gitee.com/shawnxu226/eigen-git-mirror/eigen-git-mirror.tar

**Comment by xinsuinizhuan** [comment]
> 
> 
> > > > > > Paddle\cmake\external*.cmake 源切换为gitee.com即可
> > > > > 
> > > > > 
> > > > > 怎么换？
> > > > > https://github.com/sabreshao/hipeigen.git 换成 [https://gitee.com/sabreshao/hipeigen.git?这更换后，资源都没有](https://gitee.com/sabreshao/hipeigen.git?%E8%BF%99%E6%9B%B4%E6%8D%A2%E5%90%8E%EF%BC%8C%E8%B5%84%E6%BA%90%E9%83%BD%E6%B2%A1%E6%9C%89)
> > > > 
> > > > 
> > > > 给你我的吧：https://gitee.com/shawnxu226 里面有paddle third_party需要的镜像库
> > > 
> > > 
> > > 非常感谢。我看了一下，您仓库里面有6个库：
> > > ![图片](https://user-images.githubusercontent.com/40679769/90381874-9791c480-e0b0-11ea-85fb-d0244344f360.png)
> > > 貌似，这个pp使用到的就这2个？prontbuf和openblas的有没有？
> > 
> > 
> > https://gitee.com/shawnxu226/projects 都有
> 
> 看到了。非常感谢。
您好，我想问一下，最后您编译成功了吗？我这边还没成功，报很多错：
![图片](https://user-images.githubusercontent.com/40679769/90459246-5262a680-e133-11ea-9e89-c2f063fa791e.png)
您这边遇到过没？

**Comment by ShawnXsw** [comment]
> > > > > > > Paddle\cmake\external*.cmake 源切换为gitee.com即可
> > > > > > 
> > > > > > 
> > > > > > 怎么换？
> > > > > > https://github.com/sabreshao/hipeigen.git 换成 [https://gitee.com/sabreshao/hipeigen.git?这更换后，资源都没有](https://gitee.com/sabreshao/hipeigen.git?%E8%BF%99%E6%9B%B4%E6%8D%A2%E5%90%8E%EF%BC%8C%E8%B5%84%E6%BA%90%E9%83%BD%E6%B2%A1%E6%9C%89)
> > > > > 
> > > > > 
> > > > > 给你我的吧：https://gitee.com/shawnxu226 里面有paddle third_party需要的镜像库
> > > > 
> > > > 
> > > > 非常感谢。我看了一下，您仓库里面有6个库：
> > > > ![图片](https://user-images.githubusercontent.com/40679769/90381874-9791c480-e0b0-11ea-85fb-d0244344f360.png)
> > > > 貌似，这个pp使用到的就这2个？prontbuf和openblas的有没有？
> > > 
> > > 
> > > https://gitee.com/shawnxu226/projects 都有
> > 
> > 
> > 看到了。非常感谢。
> > 您好，我想问一下，最后您编译成功了吗？我这边还没成功，报很多错：
> > ![图片](https://user-images.githubusercontent.com/40679769/90459246-5262a680-e133-11ea-9e89-c2f063fa791e.png)
> > 您这边遇到过没？

我编译正常的，运行动态库有些问题正在排查

**Comment by xinsuinizhuan** [comment]
> 运行动态库有些问题正在排查

我大概看了下，是protobuf库有问题，并且少那些文件，你有遇到过吗？

**Comment by baigang666** [comment]
@xinsuinizhuan 
您好，我在win10 vs2015 编译  想问一下：下面这些输入和输出正常么？我编译总是遇到mkl-dnn 编译出错且找不到cuda_error_ph.h 文件

D:\Paddle-1.8.4\build_2015>cmake .. -G "Visual Studio 14 2015" -A x64 -T host=x64 -DCMAKE_BUILD_TYPE=Release -DWITH_MKL=ON -DWITH_GPU=ON -DON_INFER=ON -DWITH_PYTHON=OFF -DMSVC_STATIC_CRT=OFF
-- Found Paddle host system: win32, version:
-- Found Paddle host system's CPU: 8 cores

**Comment by wadefelix** [comment]
问题1 下载github上的第三方库的问题，在相应的cmake文件中更好为国内镜像源或本地镜像源即可。
问题2 protobuf问题，换为最新版protobuf代码可以编译通过。
问题3 `TensorCheckerVisitor.apply`就没有针对`::paddle::platform::float16`的类型执行模板实例化，因为这个float16在这个环境下是个struct。`std::is_floating_point`不包含这个float16.

**Comment by xinsuinizhuan** [comment]
36>I:\PaddlePaddle\PaddlePaddle\Paddle-develop\paddle/fluid/platform/errors.h(23,10): fatal error C1083: 无法打开包括文件: “paddle/fluid/platform/error_codes.pb.h”: No such file or directory
39>I:\PaddlePaddle\PaddlePaddle\Paddle-develop\paddle/fluid/platform/errors.h(23,10): fatal error C1083: 无法打开包括文件: “paddle/fluid/platform/error_codes.pb.h”: No such file or directory
38>I:\PaddlePaddle\PaddlePaddle\Paddle-develop\paddle/fluid/framework/attribute.h(23,10): fatal error C1083: 无法打开包括文件: “paddle/fluid/framework/framework.pb.h”: No such file or directory
40>I:\PaddlePaddle\PaddlePaddle\Paddle-develop\paddle/fluid/platform/errors.h(23,10): fatal error C1083: 无法打开包括文件: “paddle/fluid/platform/error_codes.pb.h”: No such file or directory
40>已完成生成项目“allocator.vcxproj”的操作 - 失败。

报错，没有这些文件，是怎么回事呢？

**Comment by wadefelix** [comment]
> 36>I:\PaddlePaddle\PaddlePaddle\Paddle-develop\paddle/fluid/platform/errors.h(23,10): fatal error C1083: 无法打开包括文件: “paddle/fluid/platform/error_codes.pb.h”: No such file or directory
> 39>I:\PaddlePaddle\PaddlePaddle\Paddle-develop\paddle/fluid/platform/errors.h(23,10): fatal error C1083: 无法打开包括文件: “paddle/fluid/platform/error_codes.pb.h”: No such file or directory
> 38>I:\PaddlePaddle\PaddlePaddle\Paddle-develop\paddle/fluid/framework/attribute.h(23,10): fatal error C1083: 无法打开包括文件: “paddle/fluid/framework/framework.pb.h”: No such file or directory
> 40>I:\PaddlePaddle\PaddlePaddle\Paddle-develop\paddle/fluid/platform/errors.h(23,10): fatal error C1083: 无法打开包括文件: “paddle/fluid/platform/error_codes.pb.h”: No such file or directory
> 40>已完成生成项目“allocator.vcxproj”的操作 - 失败。
> 
> 报错，没有这些文件，是怎么回事呢？

protobuf库没有编译成功。更改那个probobuf的cmake文件https://github.com/wadefelix/Paddle/commit/ecb44dd6078ee738dcff765bd5538901ac142a6d
