### ISSUE TITLE
【黄埔学院】 dev分支动态库(显示) (with CUDA & without TRT) Demo 异常退出

### ISSUE THREAD

**Issue by ShawnXsw** [PaddlePaddle/Paddle#26336]
1）PaddlePaddle版本：dev(9a6a4fbc04b5c5baa1602c64975dcdc41448cebe)
    2）CPU：with MKL，正常。
    3）GPU：2080TI，CUDA Version 10.1.243，CUDNN 7.6.5
    4）OS: Windows 10、Python version: 3.7.7
          Nvidia driver version: 445.87

- 预测信息
GIT COMMIT ID: 9a6a4fbc04b5c5baa1602c64975dcdc41448cebe
WITH_MKL: ON
WITH_MKLDNN: ON
WITH_GPU: ON
CUDA version: 10.1
CUDNN version: v7.6
CXX compiler version: 19.0.24215.1
CUDA_USE_STATIC_CUDA_RUNTIME=**OFF**

- 生成：\fluid_inference_install_dir\paddle\lib\paddle_fluid.lib -102KB
\fluid_inference_install_dir\paddle\lib\paddle_fluid.dll -989554KB

- 预测库来源：Demo_CI
```
cmake .. -G "Visual Studio 14 2015 Win64"  -T host=x64 -DWITH_GPU=ON ^
      -DWITH_MKL=%use_mkl% -DWITH_STATIC_LIB=**OFF** -DCMAKE_BUILD_TYPE=Release -DDEMO_NAME=%demo_name% -DPADDLE_LIB="%paddle_infernece_lib%" -DMSVC_STATIC_CRT=ON -DCUDA_LIB="%cuda_lib_dir%"
```

- 问题描述：
1、CPU模式运行正常
2、GPU模式中断退出：
![image](https://user-images.githubusercontent.com/33308054/90338555-06254280-e01d-11ea-9361-7a81d7f122b7.png)

如上图cuda stream init 开始后，会卡滞数十秒，期间显存由200MB增加至527MB，而后突然退出，显存释放回200MB

**Comment by ShawnXsw** [comment]
>    1）PaddlePaddle版本：dev([9a6a4fb](https://github.com/PaddlePaddle/Paddle/commit/9a6a4fbc04b5c5baa1602c64975dcdc41448cebe))
>    2）CPU：with MKL，正常。
>    3）GPU：2080TI，CUDA Version 10.1.243，CUDNN 7.6.5
>    4）OS: Windows 10、Python version: 3.7.7
> Nvidia driver version: 445.87
> 
> * 预测信息
>   GIT COMMIT ID: [9a6a4fb](https://github.com/PaddlePaddle/Paddle/commit/9a6a4fbc04b5c5baa1602c64975dcdc41448cebe)
>   WITH_MKL: ON
>   WITH_MKLDNN: ON
>   WITH_GPU: ON
>   CUDA version: 10.1
>   CUDNN version: v7.6
>   CXX compiler version: 19.0.24215.1
>   CUDA_USE_STATIC_CUDA_RUNTIME=**OFF**
> * 生成：\fluid_inference_install_dir\paddle\lib\paddle_fluid.lib -102KB
>   \fluid_inference_install_dir\paddle\lib\paddle_fluid.dll -989554KB
> * 预测库来源：Demo_CI
> 
> ```
> cmake .. -G "Visual Studio 14 2015 Win64"  -T host=x64 -DWITH_GPU=ON ^
>       -DWITH_MKL=%use_mkl% -DWITH_STATIC_LIB=**OFF** -DCMAKE_BUILD_TYPE=Release -DDEMO_NAME=%demo_name% -DPADDLE_LIB="%paddle_infernece_lib%" -DMSVC_STATIC_CRT=ON -DCUDA_LIB="%cuda_lib_dir%"
> ```
> 
> * 问题描述：
>   1、CPU模式运行正常
>   2、GPU模式中断退出：
>   ![image](https://user-images.githubusercontent.com/33308054/90338555-06254280-e01d-11ea-9361-7a81d7f122b7.png)
> 
> 如上图cuda stream init 开始后，会卡滞数十秒，期间显存由200MB增加至527MB，而后突然退出，显存释放回200MB

1、附加测试1：
   1）PaddlePaddle版本：tag1.8.4
   2）CPU：with openblas
   3）GPU：2080TI，CUDA Version 10.1.243，CUDNN 7.6.5
   4）OS: Windows 10、Python version: 3.7.7
   5）编译静态库

仍然复现上述问题。

2、附加测试2：
   1）PaddlePaddle版本：tag1.8.4
   2）CPU：with openblas
   3）GPU：2080TI，CUDA Version 10.0，CUDNN 7.4
   4）OS: Windows 10、Python version: 3.7.7
   5）编译静态库
正常运行。

**Comment by jiweibo** [comment]
请问下windows上是否方便使用cuda10.0。

或者先关闭trt，看下cuda10.1下是否可以正常预测

**Comment by AIpioneer** [comment]
cuda10.1.243+cudnn 7.6.5 win10下能否可用，哪怕是静态库版本？

**Comment by jiweibo** [comment]
> cuda10.1.243+cudnn 7.6.5 win10下能否可用，哪怕是静态库版本？

windows上对cuda10.1的支持应该还有点问题，建议使用cuda10.0，后续会专门对此进行优化。

**Comment by AIpioneer** [comment]
10.2后版本可以吗？   我们需要同步其他的推理引擎， 如果可以我们会统一升版本，否则要回退cuda版本

**Comment by ShawnXsw** [comment]
> 请问下windows上是否方便使用cuda10.0。
> 
> 或者先关闭trt，看下cuda10.1下是否可以正常预测

10.1是关闭trt的版本，也有问题。   除了10.0还有其他可选吗？  linux10.1正常是吧？

**Comment by jiweibo** [comment]
> > 请问下windows上是否方便使用cuda10.0。
> > 或者先关闭trt，看下cuda10.1下是否可以正常预测
> 
> 10.1是关闭trt的版本，也有问题。 除了10.0还有其他可选吗？ linux10.1正常是吧？

windows上暂时应该只支持cuda10.0，linux环境下cuda10.0本身好像有问题，支持10.1

**Comment by jiweibo** [comment]
> 10.2后版本可以吗？ 我们需要同步其他的推理引擎， 如果可以我们会统一升版本，否则要回退cuda版本

更高版本的还没有在windows上验证过，还需要我们排期去适配

**Comment by AIpioneer** [comment]
linux呢？

**Comment by jiweibo** [comment]
> linux呢？

目前是主要支持cuda10.1，其他版本的 cuda11会后续排期支持
