### ISSUE TITLE
【论文复现】建议在保存模型函数上加上事务机制

### ISSUE THREAD

**Issue by yxhpy** [PaddlePaddle/Paddle#26348]
最近使用paddle进行论文复现的时候，由于自己网络稳定性不是很好，平台也有时会发生服务器崩溃，这时候我正在训练的模型刚好要保存的时候，突然网络不稳定导致训练进程结束，我再次刷新网页进入训练的时候就无法正常加载模型参数，希望可以加入事务回滚机制，希望采纳

**Comment by lijianshe02** [comment]
谢谢提建议

**Comment by saxon-zh** [comment]
可以在每轮训练的时候保存checkpoint，https://www.paddlepaddle.org.cn/documentation/docs/zh/beginners_guide/basic_concept/dygraph/DyGraph.html#id9

在网络恢复后就可以加载最后一次存储的模型继续训练。

**Comment by yxhpy** [comment]
> 可以在每轮训练的时候保存checkpoint，https://www.paddlepaddle.org.cn/documentation/docs/zh/beginners_guide/basic_concept/dygraph/DyGraph.html#id9
> 
> 在网络恢复后就可以加载最后一次存储的模型继续训练。

我的意思是，保存中间突然断开了进程，以我体验来说感觉paddle的save_dygraph像是一点点的保存，如果保存过程中出现了差错不仅导致原来的文件损坏，还导致新文件也保存失败，虽然我可以通过备份的方式来避免，但我第一次使用如果不知道，很容易导致训练的模型一下子就会毁了，加上事务机制后就是防止保存过程中如果保存有差错，自然就会回滚到覆写之前的状态而不是毁掉源文件了，希望可以采纳一下，增强一下体验。

**Comment by yxhpy** [comment]
> 最近使用paddle进行论文复现的时候，由于自己网络稳定性不是很好，平台也有时会发生服务器崩溃，这时候我正在训练的模型刚好要保存的时候，突然网络不稳定导致训练进程结束，我再次刷新网页进入训练的时候就无法正常加载模型参数，希望可以加入事务回滚机制，希望采纳

ut-2-59b5f3229448> in <module>
      1 model_128 = model.BigGan128()
----> 2 model_128.train()
~/BIGGAN/model.py in train(self)
    197             g = G(name_scope='G', ch=self.ch, z_dim=self.z_dim, use_bais=self.use_bais, is_sn=self.is_sn)
    198             if self.load_param:
--> 199                 d_model, _ = fluid.load_dygraph('d_%s' % self.check_point_name)
    200                 g_model, _ = fluid.load_dygraph('g_%s' % self.check_point_name)
    201                 d.set_dict(d_model)
</opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/decorator.py:decorator-gen-157> in load_dygraph(model_path, keep_name_table)
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/wrapped_decorator.py in __impl__(func, *args, **kwargs)
     23     def __impl__(func, *args, **kwargs):
     24         wrapped_func = decorator_func(func)
---> 25         return wrapped_func(*args, **kwargs)
     26 
     27     return __impl__
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/framework.py in __impl__(*args, **kwargs)
    214         assert in_dygraph_mode(
    215         ), "We Only support %s in imperative mode, please use fluid.dygraph.guard() as context to run it in imperative Mode" % func.__name__
--> 216         return func(*args, **kwargs)
    217 
    218     return __impl__
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/checkpoint.py in load_dygraph(model_path, keep_name_table)
    139     with open(params_file_path, 'rb') as f:
    140         para_dict = pickle.load(f) if six.PY2 else pickle.load(
--> 141             f, encoding='latin1')
    142 
    143     if not keep_name_table and "StructuredToParameterName@@" in para_dict:
UnpicklingError: pickle data was truncated
报错如下，这就是之前我说的情况

**Comment by saxon-zh** [comment]
我们评估一下您的建议。

**Comment by saxon-zh** [comment]
每次存储模型的时候不是增量存储，是基于当前训练得到的参数进行的完整保存，可以每轮训练的时候存储一个独立的文件，避免覆盖破坏，最后可以选择保留一个自己评估后效果最好的参数模型。
