### ISSUE TITLE
gcc82 fluid_inference 运行出core

### ISSUE THREAD

**Issue by barry2025** [PaddlePaddle/Paddle#26354]
- 版本、环境信息：
    1）PaddlePaddle版本：commitID28f871d4bd9f239aefb2118bf3a83225630160af tag:v1.6.1-gcc82-cuda10.1-cudnn7.5_PD_BL
    3）GPU：p4, cuda10.0
    4）系统环境：centos7.6：

问题描述：
使用gpu，Segmentation fault (core dumped) : 
![image](https://user-images.githubusercontent.com/20043808/90372809-90b08500-e0a3-11ea-833d-5ee37a6568c0.png)
不使用gpu：
![image](https://user-images.githubusercontent.com/20043808/90372637-462f0880-e0a3-11ea-819f-3c9449f3dfcc.png)
另：采用gcc485可正常运行

**Comment by Shixiaowei02** [comment]
你好 请检查一下头文件和库是否对应正确，谢谢

**Comment by barry2025** [comment]
请问是什么意思，接口应该没有变吧，直接下载的官方预测库，里面包含了include,lib，还有啥对应关系？

**Comment by barry2025** [comment]
再补充一下问题：
1采用gcc485，gcc485版本的fluid_inference库后，一切正常
2采用gcc82，gcc82版本的fluid_inference库后，代码完全一致，差异就在fluid_inference库，fluid_infrence库包括从官方直接下载的include,lib,third_party三个文件夹，出错问题是
(1)业务代码结合fluid_inference成功编译动态库后，采用dlopen方式，可正常编译bin文件，执行时报segment，gdb报错找不到符号：
![image](https://user-images.githubusercontent.com/20043808/90398548-3841ad80-e0cc-11ea-80ef-1d8a08111bec.png)
但是使用nm命令确实是能看到符号的：
![image](https://user-images.githubusercontent.com/20043808/90398621-53142200-e0cc-11ea-994b-fe33761baf9b.png)
这个问题在采用gcc82的时候才有，gcc485的时候是没有的

(2)不采用dlopen方式，正常把so文件链接到bin当中，编译的时候直接报错：
![image](https://user-images.githubusercontent.com/20043808/90398297-c36e7380-e0cb-11ea-99e5-ed7f922cbfee.png)
查看fluid_inference/include/paddle_analysis_config.h文件，
![image](https://user-images.githubusercontent.com/20043808/90398783-8d7dbf00-e0cc-11ea-8243-08887be383ce.png)
确实是有setsetmodel这个函数的。不懂为什么找不到。而且setmodel函数是在动态库当中用到的，如果有问题应该是编译动态库的时候就出错，但是实际情况是编译动态库没有问提，bin文件连接动态库的时候编译出错

**Comment by barry2025** [comment]
换用10.1环境以后用 comitid：ea1c05d0e61ddb1bd69b9f7fa82898a9c9859126 这个官方预编译库，使用gpu，有了新的错误：
![image](https://user-images.githubusercontent.com/20043808/90467588-20f3d600-e147-11ea-9a93-07373e97d6c9.png)

**Comment by NHZlX** [comment]
此问题通过log看应该是gcc版本不一致的问题。请check下。

**Comment by Shixiaowei02** [comment]
@barry2025 你好，此问题的原因是比较明确的：相同 API（应用程序用户接口）因为编译器的原因产出的 ABI（应用程序二进制接口）不同。这种情况非常大概率是因为前后编译使用的编译器行为不同导致，请在不同环境确认一下。谢谢

**Comment by wgh1989** [comment]
@Shixiaowei02 我这边整合了一个非常简单的环境，复现了以上问题
分别使用gcc-485和gcc-82环境运行官网inference demo
https://github.com/PaddlePaddle/Paddle-Inference-Demo/tree/master/c%2B%2B/yolov3
gcc-485，
![image](https://user-images.githubusercontent.com/35423940/91527476-6d55c780-e938-11ea-8433-d3dd43e9b054.png)
gcc-82，使用厂内aipe基础82镜像
![image](https://user-images.githubusercontent.com/35423940/91527510-7cd51080-e938-11ea-9e1e-14ffaaf09208.png)
代码编译运行：
sh run_impl.sh
./build/yolov3_test -model_file models/yolov3_infer/__model__ --params_file models/yolov3_infer/__params__

输出：
gcc-485可这正常输出
gcc-82 出现Segmentation fault

**Comment by Shixiaowei02** [comment]
问题已在用户群解决，关闭卡片。
