### ISSUE TITLE
【论文复现】Tensor*Tensor问题

### ISSUE THREAD

**Issue by Qdriving** [PaddlePaddle/Paddle#26362]
欢迎您对PaddlePaddle提出建议，非常感谢您对PaddlePaddle的贡献！
在留下您的建议时，辛苦您同步提供如下信息：
- 版本、环境信息
1）PaddlePaddle版本：1.8.3
2）CPU/GPU：AI Studio GPU
3）系统环境：百度AI Studio

- 复现信息：
    aa = to_variable(np.array([[[[1.,2.,3.,4.]]*5]*5]*5))   # 默认的数据类型float32
    bb = to_variable(np.array([[[[4.,3.,2.,1.]]*5]*5]*5))
  
    mask1 = (aa>bb).astype(int)   #比较后的数据类型bool=>int， 当然如果这里将bool=>float32运行是没问题的
    aa=mask1*aa   #报错，TypeError: data type not understood，这个问题搞了我大半天

- 建议描述：当Tensor*Tensor运算的时候自动统一两个Tensor的数据类型为精度高的类型

**Comment by lijianshe02** [comment]
重载的*运算符对两边的数据类型有要求，若想进行这样的操作，还是要准换下数据类型
