### ISSUE TITLE
SocketChannel.cpp:99] Check failed: len > 0     Connection reset by peer [104]

### ISSUE THREAD

**Issue by OrangeJessie** [PaddlePaddle/Paddle#26361]
运行了一段时间后报错，任务自己kill

任务链接：http://yq01-hpc-lvliang01-mon.dmop.baidu.com:8919/taskinfo.html?appId=app-user-20200817102752-37471
请帮忙看一下，感谢。

**Comment by lijianshe02** [comment]
机器网络问题
