### ISSUE TITLE
【论文复现】：Tensor掩码操作

### ISSUE THREAD

**Issue by Qdriving** [PaddlePaddle/Paddle#26363]
欢迎您对PaddlePaddle提出建议，非常感谢您对PaddlePaddle的贡献！
在留下您的建议时，辛苦您同步提供如下信息：
- 版本、环境信息
1）PaddlePaddle版本：1.8
2）CPU/GPU：AI Studio GPU
3）系统环境：AI Studio GPU环境
注：您可以通过执行[summary_env.py](https://github.com/PaddlePaddle/Paddle/blob/develop/tools/summary_env.py)获取以上信息。
- 复现信息：Tensor不支持掩码访问元素，如果转换为numpy运算后再转回Tensor由于numpy不支持GPU，会使运算效率大大降低
- 建议描述：增加掩码操作支持，方便运算过程

**Comment by lijianshe02** [comment]
可以通过gather， gather_nd op来访问
