### ISSUE TITLE
Paddle

### ISSUE THREAD

**Issue by MARD1NO** [PaddlePaddle/Paddle#26382]
您好，最近在看Paddle1.8的文档，请问中英文文档是分开维护的吗
![image](https://user-images.githubusercontent.com/42901638/90464818-b8a1f600-e140-11ea-8547-cfde00062aef.png)
![image](https://user-images.githubusercontent.com/42901638/90464825-bb045000-e140-11ea-9788-da2f9fe15528.png)
一个中文版没有问题，但是在英文版里报错了

**Comment by bjjwwang** [comment]
感谢指出，我记录下，会尽快修复。
