### ISSUE TITLE
Confusion about using fluid.layers functions in dygraph mode

### ISSUE THREAD

**Issue by AndersonZhangyq** [PaddlePaddle/Paddle#26381]
In example code, I found that some funcion in fluid.layers is used in dygraph mode, especially activation function like relu, tanh.
And I found some operations are available in `fluid.layers` while no counterpart could be found in `fluid.dygraph.nn`, such as `fluid.layers.pool3d`.
Is it ok **(gradient with be passed correctly as least)** to assume that we can use all funcion in fluid.layers in dygraph mode?

**Comment by bjjwwang** [comment]
A certain thing is Paddle 2.0 will make users feel much less confused about apis.
But current version, I am consulting specialists how to check the appropriate apis  for dygraph mode.
