### ISSUE TITLE
关于自动化的pyreader.start()调用问题

### ISSUE THREAD

**Issue by Life-0-1** [PaddlePaddle/Paddle#26380]
<img width="743" alt="截屏2020-08-17 下午5 32 35" src="https://user-images.githubusercontent.com/14857750/90461361-a3c16480-e138-11ea-8738-39628e8ab73f.png">
如果所示，当设置 iterable=False，通过loader.start()来载入数据时，必须采用第一种方式才能顺利运行。如果采用第二种，把loader的定义放在后面，数据会无法载入。

**Comment by Life-0-1** [comment]
可以通过设置iterable=True，并手动编写for循环解决这个问题。希望paddle同学能把通过start()，来载入数据这个问题解决，这样可以保持代码的一致性。

**Comment by bjjwwang** [comment]
好的  谢谢 我记录下

**Comment by chenwhql** [comment]
采用 iterable=False的话，原理上调用DataLoader会向当前网络中插入数据读取的op，而数据读取的op需要插入到网络头部，所以这个需要在simple_net之前调用，这里的顺序是耦合的，这也是这种用法的特点和局限，这个在原理上就是这样的

如果需要顺序解耦，需要使用iterable=True的方式

**Comment by chenwhql** [comment]
如前述回答，这个原理上现在无法解耦，2.0建议动静态图都使用迭代式的DataLoader，就没有这个问题了，issue先关闭了
