### ISSUE TITLE
InvalidArgumentError: Python object is not type of St10shared_ptrIN6paddle10imperative7VarBaseEE at (/paddle/paddle/fluid/pybind/imperative.cc:164)

### ISSUE THREAD

**Issue by xjhcassy** [PaddlePaddle/Paddle#26389]
paddle1.8.0GPU 报错： 看不懂，请说明一下
InvalidArgumentError: Python object is not type of St10shared_ptrIN6paddle10imperative7VarBaseEE at (/paddle/paddle/fluid/pybind/imperative.cc:164)

**Comment by bjjwwang** [comment]
这个paddle是哪里来的 自己编译的 还是 pip安装的

**Comment by xjhcassy** [comment]
在aistudio上创建的项目，版本是1.8.0

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

发件人: Jiawei Wang<mailto:notifications@github.com>
发送时间: 2020年8月18日 17:38
收件人: PaddlePaddle/Paddle<mailto:Paddle@noreply.github.com>
抄送: xjhcassy<mailto:ygscutyg@outlook.com>; Author<mailto:author@noreply.github.com>
主题: Re: [PaddlePaddle/Paddle] InvalidArgumentError: Python object is not type of St10shared_ptrIN6paddle10imperative7VarBaseEE at (/paddle/paddle/fluid/pybind/imperative.cc:164) (#26389)


这个paddle是哪里来的 自己编译的 还是 pip安装的

―

**Comment by bjjwwang** [comment]
这个是在什么时候触发的 方便share一下aistudio 的 notebook吗

**Comment by xttian** [comment]
请问这个问题解决了吗，我遇到一个一样的报错是在处理ERNIE的输入的时候，不知道该怎么处理

**Comment by ymzlygw** [comment]
我是因为输入的数据类型不符造成这样的异常

**Comment by tianxiehu** [comment]
所以这个问题最终怎么解决呢？

**Comment by zhengvh** [comment]
有官方的人员来解决一下吗？我是在训练时出现的这个错误。还有一个这个waring:
`- WARNING - paddle.fluid.layers.py_reader() may be deprecated in the near future. Please use paddle.fluid.io.DataLoader.from_generator() instead.`
用的是AIStudio上的paddlepaddle2.0.1

**Comment by zhengvh** [comment]
有官方的人员来解决一下吗？我是在训练时出现的这个错误。还有一个这个waring:
`- WARNING - paddle.fluid.layers.py_reader() may be deprecated in the near future. Please use paddle.fluid.io.DataLoader.from_generator() instead.`
用的是AIStudio上的paddlepaddle2.0.1

**Comment by zhengvh** [comment]
有官方的人员来解决一下吗？我是在训练时出现的这个错误。还有一个这个waring:
`- WARNING - paddle.fluid.layers.py_reader() may be deprecated in the near future. Please use paddle.fluid.io.DataLoader.from_generator() instead.`
用的是AIStudio上的paddlepaddle2.0.1

**Comment by zhengvh** [comment]
有官方的人员来解决一下吗？我是在训练时出现的这个错误。还有一个这个waring:
`- WARNING - paddle.fluid.layers.py_reader() may be deprecated in the near future. Please use paddle.fluid.io.DataLoader.from_generator() instead.`
用的是AIStudio上的paddlepaddle2.0.1

**Comment by zhengvh** [comment]
有官方的人员来解决一下吗？我是在训练时出现的这个错误。还有一个这个waring:
`- WARNING - paddle.fluid.layers.py_reader() may be deprecated in the near future. Please use paddle.fluid.io.DataLoader.from_generator() instead.`
用的是AIStudio上的paddlepaddle2.0.1

**Comment by zhengvh** [comment]
有官方的人员来解决一下吗？我是在训练时出现的这个错误。还有一个这个waring:
`- WARNING - paddle.fluid.layers.py_reader() may be deprecated in the near future. Please use paddle.fluid.io.DataLoader.from_generator() instead.`
用的是AIStudio上的paddlepaddle2.0.1

**Comment by zhengvh** [comment]
有官方的人员来解决一下吗？我是在训练时出现的这个错误。还有一个这个waring:
`- WARNING - paddle.fluid.layers.py_reader() may be deprecated in the near future. Please use paddle.fluid.io.DataLoader.from_generator() instead.`
用的是AIStudio上的paddlepaddle2.0.1

**Comment by BingzhangZhu** [comment]
same question here.

**Comment by thunder95** [comment]
同样的问题， 怎么破啊？

**Comment by ciaochiaociao** [comment]
> 新版本Paddle默认是动态图模式，所以静态图要在代码最前面加上`paddle.enable_static()`。
> 您可以试一下看看~

_Originally posted by @hutuxian in https://github.com/PaddlePaddle/Paddle/issues/29743#issuecomment-749404331_

**Comment by yujiangshui** [comment]
same issue here

**Comment by sjlmg** [comment]
> > 新版本Paddle默认是动态图模式，所以静态图要在代码最前面加上`paddle.enable_static()`。
> > 您可以试一下看看~
> 
> _Originally posted by @hutuxian in [#29743 (comment)](https://github.com/PaddlePaddle/Paddle/issues/29743#issuecomment-749404331)_

非常感谢您的提醒，我已经成功解决了这个问题
