### ISSUE TITLE
Linux安装错误 dlopen: cannot load any more object with static TLS

### ISSUE THREAD

**Issue by zxdawn** [PaddlePaddle/Paddle#26391]
## Info

Output of `python summary_env.py`:
```
/yin_raid/xin/miniconda3/envs/paddle_dev/lib/python3.7/site-packages/paddle/fluid/core.py:189: UserWarning: Load /usr/lib64/libgomp.so.1 failed
  warnings.warn("Load {} failed".format(dso_absolute_path))
summary_env.py:50: DeprecationWarning: dist() and linux_distribution() functions are deprecated in Python 3.5
  plat = platform.linux_distribution()[0]
summary_env.py:51: DeprecationWarning: dist() and linux_distribution() functions are deprecated in Python 3.5
  ver = platform.linux_distribution()[1]

Paddle version: None
Paddle With CUDA: None

OS: SUSE Linux Enterprise Server  11
Python version: 3.7.8

CUDA version: None
cuDNN version: None.None.None
Nvidia driver version: None
```

## Installation

- installed by pip:

```
pip install paddlepaddle -i https://mirror.baidu.com/pypi/simple
```

- outpt of `conda list paddle`:

```
# packages in environment at /yin_raid/xin/miniconda3/envs/paddle_dev:
#
# Name                    Version                   Build  Channel
paddlepaddle              1.8.4                    pypi_0    pypi
```

## Error
```
(paddle_dev) zhangxin@admin:~/softwares/glibc-2.18> python
Python 3.7.8 | packaged by conda-forge | (default, Jul 31 2020, 02:25:08)
[GCC 7.5.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import paddle
/yin_raid/xin/miniconda3/envs/paddle_dev/lib/python3.7/site-packages/paddle/fluid/core.py:189: UserWarnin
  warnings.warn("Load {} failed".format(dso_absolute_path))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/yin_raid/xin/miniconda3/envs/paddle_dev/lib/python3.7/site-packages/paddle/__init__.py", line 37
    import paddle.complex
  File "/yin_raid/xin/miniconda3/envs/paddle_dev/lib/python3.7/site-packages/paddle/complex/__init__.py",
    from . import tensor
  File "/yin_raid/xin/miniconda3/envs/paddle_dev/lib/python3.7/site-packages/paddle/complex/tensor/__init
    from . import math
  File "/yin_raid/xin/miniconda3/envs/paddle_dev/lib/python3.7/site-packages/paddle/complex/tensor/math.p
    from paddle.common_ops_import import *
  File "/yin_raid/xin/miniconda3/envs/paddle_dev/lib/python3.7/site-packages/paddle/common_ops_import.py"
    from paddle.fluid.layer_helper import LayerHelper
  File "/yin_raid/xin/miniconda3/envs/paddle_dev/lib/python3.7/site-packages/paddle/fluid/__init__.py", l
    from . import framework
  File "/yin_raid/xin/miniconda3/envs/paddle_dev/lib/python3.7/site-packages/paddle/fluid/framework.py",
    from . import core
  File "/yin_raid/xin/miniconda3/envs/paddle_dev/lib/python3.7/site-packages/paddle/fluid/core.py", line
    raise e
  File "/yin_raid/xin/miniconda3/envs/paddle_dev/lib/python3.7/site-packages/paddle/fluid/core.py", line
    from .core_avx import *
ImportError: dlopen: cannot load any more object with static TLS
```

## Debug

I've tried to compile the `glibc 2.18` with `DTV_SURPLUS=32` according to this [suggestion](https://github.com/PaddlePaddle/Paddle/issues/21760#issuecomment-569213146) and add it to `LD_LIBRARY_PATH`:
`export LD_LIBRARY_PATH=/public/home/zhangxin/softwares/glibc-2.18:$LD_LIBRARY_PATH`.

**Comment by bjjwwang** [comment]
暂时可能没什么办法 只能换个版本或者换个python环境看看 我先记录下

**Comment by zxdawn** [comment]
@wangjiawei04 你说的换python环境是指换python版本？我试过`3.7.4`，也不行。

另外因为大型机上不能随意更改其他库，只能装到`glibc 2.18`了。

**Comment by zhiqiu** [comment]
hi，请问下你不用conda环境的python是否仍然会出现这个问题呢？

**Comment by fistyee** [comment]
我也遇到了这个问题，请问您解决了吗

> ## Info
> Output of `python summary_env.py`:
> 
> ```
> /yin_raid/xin/miniconda3/envs/paddle_dev/lib/python3.7/site-packages/paddle/fluid/core.py:189: UserWarning: Load /usr/lib64/libgomp.so.1 failed
>   warnings.warn("Load {} failed".format(dso_absolute_path))
> summary_env.py:50: DeprecationWarning: dist() and linux_distribution() functions are deprecated in Python 3.5
>   plat = platform.linux_distribution()[0]
> summary_env.py:51: DeprecationWarning: dist() and linux_distribution() functions are deprecated in Python 3.5
>   ver = platform.linux_distribution()[1]
> 
> Paddle version: None
> Paddle With CUDA: None
> 
> OS: SUSE Linux Enterprise Server  11
> Python version: 3.7.8
> 
> CUDA version: None
> cuDNN version: None.None.None
> Nvidia driver version: None
> ```
> 
> ## Installation
> * installed by pip:
> 
> ```
> pip install paddlepaddle -i https://mirror.baidu.com/pypi/simple
> ```
> 
> * outpt of `conda list paddle`:
> 
> ```
> # packages in environment at /yin_raid/xin/miniconda3/envs/paddle_dev:
> #
> # Name                    Version                   Build  Channel
> paddlepaddle              1.8.4                    pypi_0    pypi
> ```
> 
> ## Error
> ```
> (paddle_dev) zhangxin@admin:~/softwares/glibc-2.18> python
> Python 3.7.8 | packaged by conda-forge | (default, Jul 31 2020, 02:25:08)
> [GCC 7.5.0] on linux
> Type "help", "copyright", "credits" or "license" for more information.
> >>> import paddle
> /yin_raid/xin/miniconda3/envs/paddle_dev/lib/python3.7/site-packages/paddle/fluid/core.py:189: UserWarnin
>   warnings.warn("Load {} failed".format(dso_absolute_path))
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/yin_raid/xin/miniconda3/envs/paddle_dev/lib/python3.7/site-packages/paddle/__init__.py", line 37
>     import paddle.complex
>   File "/yin_raid/xin/miniconda3/envs/paddle_dev/lib/python3.7/site-packages/paddle/complex/__init__.py",
>     from . import tensor
>   File "/yin_raid/xin/miniconda3/envs/paddle_dev/lib/python3.7/site-packages/paddle/complex/tensor/__init
>     from . import math
>   File "/yin_raid/xin/miniconda3/envs/paddle_dev/lib/python3.7/site-packages/paddle/complex/tensor/math.p
>     from paddle.common_ops_import import *
>   File "/yin_raid/xin/miniconda3/envs/paddle_dev/lib/python3.7/site-packages/paddle/common_ops_import.py"
>     from paddle.fluid.layer_helper import LayerHelper
>   File "/yin_raid/xin/miniconda3/envs/paddle_dev/lib/python3.7/site-packages/paddle/fluid/__init__.py", l
>     from . import framework
>   File "/yin_raid/xin/miniconda3/envs/paddle_dev/lib/python3.7/site-packages/paddle/fluid/framework.py",
>     from . import core
>   File "/yin_raid/xin/miniconda3/envs/paddle_dev/lib/python3.7/site-packages/paddle/fluid/core.py", line
>     raise e
>   File "/yin_raid/xin/miniconda3/envs/paddle_dev/lib/python3.7/site-packages/paddle/fluid/core.py", line
>     from .core_avx import *
> ImportError: dlopen: cannot load any more object with static TLS
> ```
> 
> ## Debug
> I've tried to compile the `glibc 2.18` with `DTV_SURPLUS=32` according to this [suggestion](https://github.com/PaddlePaddle/Paddle/issues/21760#issuecomment-569213146) and add it to `LD_LIBRARY_PATH`:
> `export LD_LIBRARY_PATH=/public/home/zhangxin/softwares/glibc-2.18:$LD_LIBRARY_PATH`.

**Comment by hyperji** [comment]
遇到了同样的问题， paddle版本 1.8.5
Python 3.7.6 (default, Jan  8 2020, 19:59:22) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import paddle
/root/anaconda3/lib/python3.7/site-packages/paddle/fluid/core.py:194: UserWarning: Load /usr/lib64/libgomp.so.1 failed
  warnings.warn("Load {} failed".format(dso_absolute_path))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/root/anaconda3/lib/python3.7/site-packages/paddle/__init__.py", line 37, in <module>
    import paddle.complex
  File "/root/anaconda3/lib/python3.7/site-packages/paddle/complex/__init__.py", line 15, in <module>
    from . import tensor
  File "/root/anaconda3/lib/python3.7/site-packages/paddle/complex/tensor/__init__.py", line 15, in <module>
    from . import math
  File "/root/anaconda3/lib/python3.7/site-packages/paddle/complex/tensor/math.py", line 15, in <module>
    from paddle.common_ops_import import *
  File "/root/anaconda3/lib/python3.7/site-packages/paddle/common_ops_import.py", line 15, in <module>
    from paddle.fluid.layer_helper import LayerHelper
  File "/root/anaconda3/lib/python3.7/site-packages/paddle/fluid/__init__.py", line 35, in <module>
    from . import framework
  File "/root/anaconda3/lib/python3.7/site-packages/paddle/fluid/framework.py", line 35, in <module>
    from . import core
  File "/root/anaconda3/lib/python3.7/site-packages/paddle/fluid/core.py", line 273, in <module>
    raise e
  File "/root/anaconda3/lib/python3.7/site-packages/paddle/fluid/core.py", line 243, in <module>
    from .core_avx import *
ImportError: dlopen: cannot load any more object with static TLS

**Comment by hyperji** [comment]
> hi，请问下你不用conda环境的python是否仍然会出现这个问题呢？

会，我遇到了

**Comment by semal** [comment]
我也遇到了同样的问题，还没解决吗？桑心..

**Comment by bjjwwang** [comment]
推荐使用新版本的docker容器，需要升级gcc版本到8.2使用paddle 2.0+
