### ISSUE TITLE
技术咨询，ConvLSTM模型如何在pp上实现？

### ISSUE THREAD

**Issue by miojibaiyu** [PaddlePaddle/Paddle#26406]
技术咨询，ConvLSTM模型如何在pp上实现？，初学者
主要通过lstm思想，做图像时间序列的学习

**Comment by bjjwwang** [comment]
https://github.com/PaddlePaddle/models/search?q=LSTM&unscoped_q=LSTM 可以先参考下models库下关于LSTM相关代码呢。
