### ISSUE TITLE
【论文复现】程序卡死问题

### ISSUE THREAD

**Issue by caikw0602** [PaddlePaddle/Paddle#26425]
通过使用paddle复现论文UGATIT过程中出现的问题：
在执行下面一句代码时，程序一直运行，无报错，但是始终无法执行到下一句代码，卡死在这句指令运行：
![image](https://user-images.githubusercontent.com/45365909/90586954-e81d3500-e20a-11ea-8817-40db5fc38135.png)
程序运行到第一个断点，无法执行到第二个断点处，其中self.gmp_fc()定义为：
![image](https://user-images.githubusercontent.com/45365909/90587049-100c9880-e20b-11ea-80d7-a0edc66fc209.png)

**Comment by hong19860320** [comment]
@caikw0602 能否提供我能简单复现的python脚本吗？

**Comment by caikw0602** [comment]
> @caikw0602 能否提供我能简单复现的python脚本吗？

没问题的，能否提供邮箱or微信？我打包发送？

**Comment by hong19860320** [comment]
直接把脚本贴在这里，或者在AI Studio创建个工程，把链接给我？

**Comment by caikw0602** [comment]
> 直接把脚本贴在这里，或者在AI Studio创建个工程，把链接给我？

好的，我建立了一个Aistudio工程：
https://aistudio.baidu.com/aistudio/clusterprojectdetail/741038

**Comment by hong19860320** [comment]
这个工程不完整吧，是否需要dataset和执行脚本呢？

**Comment by caikw0602** [comment]
> 这个工程不完整吧，是否需要dataset和执行脚本呢？

你好，我新建了一个项目，增加了数据集，运行脚本为'main.py'
https://aistudio.baidu.com/aistudio/projectdetail/741189
