### ISSUE TITLE
【论文复现】如何载入预训练好的参数

### ISSUE THREAD

**Issue by kgkzhiwen** [PaddlePaddle/Paddle#26429]
再这个网址下载来VGG预训练好的模型参数： https://paddle-imagenet-models-name.bj.bcebos.com/VGG19_pretrained.tar

请问要怎么样把这些参数载入到VGG19的动态图中？

**Comment by hong19860320** [comment]
可以参考 https://github.com/PaddlePaddle/models/tree/release/1.8/PaddleCV/image_classification的步骤 ，里面包含vgg的组网脚本（静态图的）。

**Comment by kgkzhiwen** [comment]
我需要动态图的例子。

**Comment by hong19860320** [comment]
可以参考这两个issue 提到的方法

https://github.com/PaddlePaddle/Paddle/issues/25883
https://github.com/PaddlePaddle/Paddle/issues/25719
