### ISSUE TITLE
【Urgent!】paddle.fluid.layers.adaptive_pool2d

### ISSUE THREAD

**Issue by ddummkopfer** [PaddlePaddle/Paddle#26424]
I use  **paddle.fluid.layers.adaptive_pool2d(..., pool_type='max', require_index=True ,...)**
the output index are the index in the global input matrix or the index in the kernel size?

Thank you so much. It is urgent for me.

**Comment by hong19860320** [comment]
The index in the global input matrix, plz ref to https://github.com/PaddlePaddle/Paddle/blob/e89c16b90d0169a994fbb345ff79067ae7c8295c/paddle/fluid/operators/math/pooling.cu#L1245 for more details.

**Comment by ddummkopfer** [comment]
Thank you @hong19860320 so much.
