### ISSUE TITLE
paddle1.8是否有AdamW的实现方案？

### ISSUE THREAD

**Issue by geekhch** [PaddlePaddle/Paddle#26421]
+ PaddlePaddle版本：1.8

在微调ernie的过程中，需要使用weight_decay。但传统Adam被证实与L2正则不兼容，请问paddle中的L2Decay是否能在Adam中使用，这里的Adam优化器是经过修正的吗？

**Comment by geekhch** [comment]
补上论文地址：[DECOUPLED WEIGHT DECAY REGULARIZATION](https://arxiv.org/pdf/1711.05101.pdf)

**Comment by hong19860320** [comment]
1.8版本的AdamW可以参考这个用法https://github.com/PaddlePaddle/Paddle/blob/c4a972c2bf64355b8cfd60ccf5bc9589538871bc/python/paddle/fluid/contrib/extend_optimizer/extend_optimizer_with_weight_decay.py#L121

https://github.com/PaddlePaddle/Paddle/blob/c4a972c2bf64355b8cfd60ccf5bc9589538871bc/python/paddle/fluid/contrib/tests/test_weight_decay_extend.py#L103

**Comment by wxh001qq** [comment]
> 1.8版本的AdamW可以参考这个用法
> 
> https://github.com/PaddlePaddle/Paddle/blob/c4a972c2bf64355b8cfd60ccf5bc9589538871bc/python/paddle/fluid/contrib/extend_optimizer/extend_optimizer_with_weight_decay.py#L121
> 
> https://github.com/PaddlePaddle/Paddle/blob/c4a972c2bf64355b8cfd60ccf5bc9589538871bc/python/paddle/fluid/contrib/tests/test_weight_decay_extend.py#L103

您好，使用你提到的这种方法，报如下错误呢
lib/python2.7/site-packages/paddle/fluid/contrib/extend_optimizer/extend_optimizer_with_weight_decay.py", line 84, in minimize
    for p_grad_sgrad in scaled_params:
TypeError: 'NoneType' object is not iterable
