### ISSUE TITLE
我安装了nvidia-docker，为什么训练的时候使用的是CPU，怎么使用GPU资源

### ISSUE THREAD

**Issue by yeguang1991** [PaddlePaddle/Paddle#26443]

**Comment by hong19860320** [comment]
请使用nvidia-smi命令确认GPU是否可用，然后确认是通过pip install paddlepaddle-gpu 安装了gpu版本的paddle。

**Comment by yeguang1991** [comment]
![image](https://user-images.githubusercontent.com/66579493/90610145-9939c480-e237-11ea-8db5-7f7a607dd6f7.png)
![image](https://user-images.githubusercontent.com/66579493/90610169-a0f96900-e237-11ea-815b-d2011db69d3f.png)
都是正常安装的，我宿主机可以使用GPU训练，但是docker不行

**Comment by yeguang1991** [comment]
> 请使用nvidia-smi命令确认GPU是否可用，然后确认是通过pip install paddlepaddle-gpu 安装了gpu版本的paddle。

都是正常安装的，我宿主机可以使用GPU训练，但是docker不行
![image](https://user-images.githubusercontent.com/66579493/90610291-cbe3bd00-e237-11ea-9170-f00ca7a0e091.png)
![image](https://user-images.githubusercontent.com/66579493/90610302-cf774400-e237-11ea-8d8e-24a9c7bb53f1.png)

**Comment by hong19860320** [comment]
> > 请使用nvidia-smi命令确认GPU是否可用，然后确认是通过pip install paddlepaddle-gpu 安装了gpu版本的paddle。
> 
> 都是正常安装的，我宿主机可以使用GPU训练，但是docker不行
> ![image](https://user-images.githubusercontent.com/66579493/90610291-cbe3bd00-e237-11ea-9170-f00ca7a0e091.png)
> ![image](https://user-images.githubusercontent.com/66579493/90610302-cf774400-e237-11ea-8d8e-24a9c7bb53f1.png)

看环境可以使用GPU的，在训练的时候，使用CUDA place就行了

place=paddle.CUDAPlace(0) if core.is_compiled_with_cuda() \
            else paddle.CPUPlace()

**Comment by hong19860320** [comment]
> > 请使用nvidia-smi命令确认GPU是否可用，然后确认是通过pip install paddlepaddle-gpu 安装了gpu版本的paddle。
> 
> 都是正常安装的，我宿主机可以使用GPU训练，但是docker不行
> ![image](https://user-images.githubusercontent.com/66579493/90610291-cbe3bd00-e237-11ea-9170-f00ca7a0e091.png)
> ![image](https://user-images.githubusercontent.com/66579493/90610302-cf774400-e237-11ea-8d8e-24a9c7bb53f1.png)

docker里面调用nvidia-smi也正常？

**Comment by yeguang1991** [comment]
> > > 请使用nvidia-smi命令确认GPU是否可用，然后确认是通过pip install paddlepaddle-gpu 安装了gpu版本的paddle。
> > 
> > 
> > 都是正常安装的，我宿主机可以使用GPU训练，但是docker不行
> > ![image](https://user-images.githubusercontent.com/66579493/90610291-cbe3bd00-e237-11ea-9170-f00ca7a0e091.png)
> > ![image](https://user-images.githubusercontent.com/66579493/90610302-cf774400-e237-11ea-8d8e-24a9c7bb53f1.png)
> 
> docker里面调用nvidia-smi也正常？

dockers里面不行

**Comment by hong19860320** [comment]
> > > > 请使用nvidia-smi命令确认GPU是否可用，然后确认是通过pip install paddlepaddle-gpu 安装了gpu版本的paddle。
> > > 
> > > 
> > > 都是正常安装的，我宿主机可以使用GPU训练，但是docker不行
> > > ![image](https://user-images.githubusercontent.com/66579493/90610291-cbe3bd00-e237-11ea-9170-f00ca7a0e091.png)
> > > ![image](https://user-images.githubusercontent.com/66579493/90610302-cf774400-e237-11ea-8d8e-24a9c7bb53f1.png)
> > 
> > 
> > docker里面调用nvidia-smi也正常？
> 
> dockers里面不行

嗯看样子docker里面没有gpu的环境，你需要通过nvidia-docker run命令启动docker，Paddle已经提供了ubuntu cuda9和cuda10的docker镜像了 https://www.paddlepaddle.org.cn/

![image](https://user-images.githubusercontent.com/9973393/90731064-bd5ed980-e2fb-11ea-9133-18771623f18d.png)

**Comment by yeguang1991** [comment]
> > > > > 请使用nvidia-smi命令确认GPU是否可用，然后确认是通过pip install paddlepaddle-gpu 安装了gpu版本的paddle。
> > > > 
> > > > 
> > > > 都是正常安装的，我宿主机可以使用GPU训练，但是docker不行
> > > > ![image](https://user-images.githubusercontent.com/66579493/90610291-cbe3bd00-e237-11ea-9170-f00ca7a0e091.png)
> > > > ![image](https://user-images.githubusercontent.com/66579493/90610302-cf774400-e237-11ea-8d8e-24a9c7bb53f1.png)
> > > 
> > > 
> > > docker里面调用nvidia-smi也正常？
> > 
> > 
> > dockers里面不行
> 
> 嗯看样子docker里面没有gpu的环境，你需要通过nvidia-docker run命令启动docker，Paddle已经提供了ubuntu cuda9和cuda10的docker镜像了 https://www.paddlepaddle.org.cn/
> 
> ![image](https://user-images.githubusercontent.com/9973393/90731064-bd5ed980-e2fb-11ea-9133-18771623f18d.png)

用paddle提供的cuda10的镜像，输nvidia-smi也不行
