### ISSUE TITLE
Language on Releases page

### ISSUE THREAD

**Issue by itsallonetome** [PaddlePaddle/Paddle#26458]
Could you find a method of either clearing the "English" language tag on the Release page (so browser translators will work) or some other method for people who aren't fluent in Chinese to understand what's been released.

Thanks.

**Comment by hong19860320** [comment]
Thank you for your advise，we had provided both English and Chinese release note for the main version(1.8.4 and 2.0.alpha) of PaddlePaddle.
plz ref to https://github.com/PaddlePaddle/Paddle/releases for the detail.
![image](https://user-images.githubusercontent.com/9973393/90642820-745c4600-e265-11ea-9f2a-6860cd00312f.png)
![image](https://user-images.githubusercontent.com/9973393/90642948-9a81e600-e265-11ea-9c89-c194420f62cd.png)
