### ISSUE TITLE
[论文复现] 通过creater_parameter创建的层中参数在反向传播的过程之中没有更新

### ISSUE THREAD

**Issue by Costwen** [PaddlePaddle/Paddle#26469]
`

    class adaILN(fluid.dygraph.Layer):

    def __init__(self, in_channels, eps=1e-5):
        super(adaILN, self).__init__()
        self.eps = eps
        self.rho = fluid.layers.create_parameter((1, in_channels, 1, 1), dtype='float32', is_bias=True,
        default_initializer=fluid.initializer.ConstantInitializer(0.9))

    def var(self, input, dim):
        mean = fluid.layers.reduce_mean(input, dim, keep_dim=True)
        tmp = fluid.layers.reduce_mean((input - mean)**2, dim, keep_dim=True)
        return tmp

    def forward(self, input, gamma, beta):
        in_mean, in_var = fluid.layers.reduce_mean(input, dim=[2,3], keep_dim=True), self.var(input, dim =[2,3])
        ln_mean, ln_var = fluid.layers.reduce_mean(input, dim=[1,2,3], keep_dim=True), self.var(input, dim=[1,2,3])
        out_in = (input - in_mean) / fluid.layers.sqrt(in_var + self.eps)
        out_ln = (input - ln_mean) / fluid.layers.sqrt(ln_var + self.eps)
        ex_rho = fluid.layers.expand(self.rho, expand_times = [input.shape[0], 1, 1, 1])
        print("rho",fluid.layers.reduce_mean(self.rho).numpy())
        out = ex_rho * out_in + (1 - ex_rho)*out_ln
        out = out * gamma + beta
        return out

    class ILN(fluid.dygraph.Layer):

    def __init__(self, in_channels, eps=1e-5):
        super(ILN, self).__init__()
        self.eps = eps
        self.rho = fluid.layers.create_parameter((1, in_channels, 1, 1), dtype='float32', is_bias=True,
        default_initializer=fluid.initializer.ConstantInitializer(0.0))
        self.gamma = fluid.layers.create_parameter((1, in_channels, 1, 1), dtype='float32', is_bias=True,
        default_initializer=fluid.initializer.ConstantInitializer(1.0))
        self.beta = fluid.layers.create_parameter((1, in_channels, 1, 1), dtype='float32', is_bias=True,
        default_initializer=fluid.initializer.ConstantInitializer(0.0))
        
    def var(self, input, dim):
        mean = fluid.layers.reduce_mean(input, dim, keep_dim=True)
        tmp = fluid.layers.reduce_mean((input - mean)**2, dim, keep_dim=True)
        return tmp

    def forward(self, input):
        in_mean, in_var = fluid.layers.reduce_mean(input, dim=[2,3], keep_dim=True), self.var(input, dim =[2,3])
        ln_mean, ln_var = fluid.layers.reduce_mean(input, dim=[1,2,3], keep_dim=True), self.var(input, dim=[1,2,3])
        out_in = (input - in_mean) / fluid.layers.sqrt(in_var + self.eps)
        out_ln = (input - ln_mean) / fluid.layers.sqrt(ln_var + self.eps)
        ex_rho = fluid.layers.expand(self.rho, expand_times = [input.shape[0], 1, 1, 1])
        ex_gamma = fluid.layers.expand(self.gamma, expand_times = [input.shape[0], 1, 1, 1])
        ex_beta = fluid.layers.expand(self.beta, expand_times = [input.shape[0], 1, 1, 1])
        print("rho",fluid.layers.reduce_mean(self.rho).numpy())
        print("gamma",fluid.layers.reduce_mean(self.gamma).numpy())
        print("beta",fluid.layers.reduce_mean(self.beta).numpy())
        out = ex_rho * out_in + (1 - ex_rho) * out_ln
        out = out * ex_gamma + ex_beta
        return out

`
通过上述代码创建的rho beta gamma 在反向传播的过程之中参数一直都维持着初始化时候的值

是我的用法不对吗

**Comment by hong19860320** [comment]
得用self.create_parameter创建parameter，不能用fluid.layers.create_parameter

https://github.com/PaddlePaddle/Paddle/blob/f79526c21c81a87faf843d2b80d1b6609431b277/python/paddle/fluid/dygraph/rnn.py#L165

**Comment by Costwen** [comment]
> 得用self.create_parameter创建parameter，不能用fluid.layers.create_parameter
> 
> https://github.com/PaddlePaddle/Paddle/blob/f79526c21c81a87faf843d2b80d1b6609431b277/python/paddle/fluid/dygraph/rnn.py#L165

尝试过还是不行,梯度仍然不更新
同时我也有在用fluid.layers.create_parameter时打印model中的可更新的参数和backward网络的梯度，发现rho都在里面而且梯度并不为0

**Comment by Costwen** [comment]
> > 得用self.create_parameter创建parameter，不能用fluid.layers.create_parameter
> > https://github.com/PaddlePaddle/Paddle/blob/f79526c21c81a87faf843d2b80d1b6609431b277/python/paddle/fluid/dygraph/rnn.py#L165
> 
> 尝试过还是不行,梯度仍然不更新
> 同时我也有在用fluid.layers.create_parameter时打印model中的可更新的参数和backward网络的梯度，发现rho都在里面而且梯度并不为0

找到问题了,问题出在itertool.chain（） 组合出的参数 
paddle的optimizer并不能使用，导致所有的参数都不能更新..

**Comment by rs-lsl** [comment]
你好，请问最后怎么解决的
