### ISSUE TITLE
paddle是否支持自定义优化器

### ISSUE THREAD

**Issue by dbsxdbsx** [PaddlePaddle/Paddle#26471]
如看到一篇新的loss函数论文，可能paddle本身并没有提供其实现，那有没有办法继承某些接口我们自己去写呢？

**Comment by wangchaochaohu** [comment]
如果需要可以参考新增OP的实现 文档 https://www.paddlepaddle.org.cn/documentation/docs/zh/advanced_guide/addon_development/new_op/index_cn.html

欢迎贡献代码
