### ISSUE TITLE
论文复现（3D ResNets for Action Recognition）

### ISSUE THREAD

**Issue by trytodoit227** [PaddlePaddle/Paddle#26474]
加载预训练模型参数后，测试集的准确率（达到95%）与验证集的准确率（70%）相差较大，请问这个过拟合的原因大概是什么因素造成的呢？
![image](https://user-images.githubusercontent.com/64091668/90709839-ae623200-e2cf-11ea-8545-5db3feb2079f.png)
test list文件中显示的这个错误会不会是造成过拟合的原因呢？

**Comment by wangchaochaohu** [comment]
标出来的并不是的错误 过拟合的可能是网络结构或者训练过程中的一些问题

**Comment by huangjun12** [comment]
(1) 不是的，testlist是文本文件，不是代码文件，标红跟错误提示是针对代码文件的，testlist文件标红是属于误标了，问题不在于它；
(2) 加载预训练模型后，需要先在ucf-101数据集上fine-tune，再观察测试集与验证集的准确率；
(3) 如果出现过拟合，可能原因有很多，建议跟源码对齐下超参数，比如学习率、batch_size等。
