### ISSUE TITLE
Paddle是否支持计算张量的范数，需要调用哪个API？

### ISSUE THREAD

**Issue by YanCj** [PaddlePaddle/Paddle#26472]
如题，最近在做对抗样本相关的工作，有时需要在损失函数里约束添加张量的p-范数大小，但是找了好久似乎并没有找到相应的API，例如pytorch中的torch.norm()或是TensorFlow中的tf.norm()

**Comment by wangchaochaohu** [comment]
Paddle2.0是支持的 可以参考文档 https://www.paddlepaddle.org.cn/documentation/docs/zh/2.0-alpha/api_cn/tensor_cn/norm_cn.html
