### ISSUE TITLE
【论文复现】aistudio问题

### ISSUE THREAD

**Issue by chfhf** [PaddlePaddle/Paddle#26473]
点击文件出现：
Request has been terminated Possible causes: the network is offline, Origin is not allowed by Access-Control-Allow-Origin, the page is being unloaded, etc.
怎么解决？

**Comment by wangchaochaohu** [comment]
这边提示应该网络问题

**Comment by saxon-zh** [comment]
可以看看网络通信恢复后是否正常，如果还有问题可以将问题发邮件至aistudio@baidu.com。
