### ISSUE TITLE
【论文复现】pytorch 中的 backward 和 step 对应 paddle 中如何改写

### ISSUE THREAD

**Issue by Ryan906k9** [PaddlePaddle/Paddle#26503]
pytorch 代码如下：
```
Generator_loss = G_loss_A + G_loss_B

            Generator_loss.backward()

            self.G_optim.step()
```

对应paddle 的是只要这么改吗？
```
Generator_loss = G_loss_A + G_loss_B

                Generator_loss.backward()
```

其中`self.G_optim.step()`对应paddle 中的什么呢？

**Comment by saxon-zh** [comment]
可以参见这个文档说明查看对应的API：[命令式编程使用教程](https://www.paddlepaddle.org.cn/documentation/docs/zh/beginners_guide/basic_concept/dygraph/DyGraph.html#id7)
