### ISSUE TITLE
py_reader的layer.read_files出来的var的name塞到save_inference_model的feeded_var_names里面报找不到 ValueError: var read_file_0.tmp_0 not in this block

### ISSUE THREAD

**Issue by kelvi** [PaddlePaddle/Paddle#26521]
py_reader的layer.read_files出来的var的name塞到save_inference_model的feeded_var_names里面报找不到 ValueError: var read_file_0.tmp_0 not in this block
    1）PaddlePaddle版本：1.8.3
    2）CPU：预测若用CPU，请提供CPU型号，MKL/OpenBlas/MKLDNN/等数学库使用情况
    3）GPU：cuda9
    4）系统环境：centos python2.7（如Mac OS 10.14），Python版本

**Comment by chenwhql** [comment]
方便把整个报错栈贴一下吗

**Comment by kelvi** [comment]
已查出，这个case中是因为我在构建var的时候自己指定了个main_program，然而save_inference_model的时候没有指定main_program导致save_inference_model从default_main_program中找不到var。
