### ISSUE TITLE
【论文复现】关于AiStudio脚本任务

### ISSUE THREAD

**Issue by huochf** [PaddlePaddle/Paddle#26534]
咱AI Studio脚本任务中有没有可以永久保存大量文件的路径呐，就如同Notebook那样？
（1）因为咱提供的数据集都是原始数据，数据处理需要耗费大量的时间，比如在TPN那篇论文中，140G的数据集解压一次需要1.4小时，之后没法做抽帧预处理（这样消耗的时间更大）。Few-shot给出的dance数据集如果仅仅只给出视频数据而没有标注的话，从视频帧抽取人体标注也是一个大工作量的任务，不可能每次训练都提取一次标注吧。
（2）训练过程中需要定时保存一下模型，这些模型输出到那个文件目录中？
我刚刚接触脚本任务，对文件组织管理不太清楚，希望得到相关工作人员的反馈，谢谢！

**Comment by chenwhql** [comment]
好的，感谢反馈，我们找AiStudio的同学回复下您

**Comment by saxon-zh** [comment]
@weiexcelpro 辛苦解答一下

**Comment by weiexcelpro** [comment]
> 咱AI Studio脚本任务中有没有可以永久保存大量文件的路径呐，就如同Notebook那样？
> （1）因为咱提供的数据集都是原始数据，数据处理需要耗费大量的时间，比如在TPN那篇论文中，140G的数据集解压一次需要1.4小时，之后没法做抽帧预处理（这样消耗的时间更大）。Few-shot给出的dance数据集如果仅仅只给出视频数据而没有标注的话，从视频帧抽取人体标注也是一个大工作量的任务，不可能每次训练都提取一次标注吧。
> （2）训练过程中需要定时保存一下模型，这些模型输出到那个文件目录中？
> 我刚刚接触脚本任务，对文件组织管理不太清楚，希望得到相关工作人员的反馈，谢谢！

1、可以把标注好的文件作为数据集处理
2、模型输出可以保存在该目录下"/root/paddlejob/workspace/output/"

**Comment by huochf** [comment]
> 咱AI Studio脚本任务中有没有可以永久保存大量文件的路径呐，就如同Notebook那样？
> （1）因为咱提供的数据集都是原始数据，数据处理需要耗费大量的时间，比如在TPN那篇论文中，140G的数据集解压一次需要1.4小时，之后没法做抽帧预处理（这样消耗的时间更大）。Few-shot给出的dance数据集如果仅仅只给出视频数据而没有标注的话，从视频帧抽取人体标注也是一个大工作量的任务，不可能每次训练都提取一次标注吧。
> （2）训练过程中需要定时保存一下模型，这些模型输出到那个文件目录中？
> 我刚刚接触脚本任务，对文件组织管理不太清楚，希望得到相关工作人员的反馈，谢谢！
> 
> 1、可以把标注好的文件作为数据集处理
> 2、模型输出可以保存在该目录下"/root/paddlejob/workspace/output/"

好的，好的，谢谢！

**Comment by huochf** [comment]
> 咱AI Studio脚本任务中有没有可以永久保存大量文件的路径呐，就如同Notebook那样？
> （1）因为咱提供的数据集都是原始数据，数据处理需要耗费大量的时间，比如在TPN那篇论文中，140G的数据集解压一次需要1.4小时，之后没法做抽帧预处理（这样消耗的时间更大）。Few-shot给出的dance数据集如果仅仅只给出视频数据而没有标注的话，从视频帧抽取人体标注也是一个大工作量的任务，不可能每次训练都提取一次标注吧。
> （2）训练过程中需要定时保存一下模型，这些模型输出到那个文件目录中？
> 我刚刚接触脚本任务，对文件组织管理不太清楚，希望得到相关工作人员的反馈，谢谢！
> 
> 1、可以把标注好的文件作为数据集处理
> 2、模型输出可以保存在该目录下"/root/paddlejob/workspace/output/"

和我想到的解决方案差不多。
