### ISSUE TITLE
【论文复现】分布式脚本空间

### ISSUE THREAD

**Issue by sunjie97** [PaddlePaddle/Paddle#26545]
复现TPN的时候使用kinetics400数据集，在提取rgb图像的过程中突然提示任务失败:
![](https://s1.ax1x.com/2020/08/21/dNaDUJ.png)
日志中没什么异常，就是正常输出正在提取的视频:
![](https://s1.ax1x.com/2020/08/21/dNdbFJ.png)
是不是文件大小超出了系统限制？分布式脚本的空间限制是多少？

**Comment by saxon-zh** [comment]
@weiexcelpro 辛苦解答一下

**Comment by weiexcelpro** [comment]
> 复现TPN的时候使用kinetics400数据集，在提取rgb图像的过程中突然提示任务失败:
> ![](https://camo.githubusercontent.com/49f1ddc506927ff984a7d54c6f3eeb06e9b6cf49/68747470733a2f2f73312e617831782e636f6d2f323032302f30382f32312f644e6144554a2e706e67)
> 日志中没什么异常，就是正常输出正在提取的视频:
> ![](https://camo.githubusercontent.com/6f91327581c18690090bc864fce5bfb0df8a0c45/68747470733a2f2f73312e617831782e636f6d2f323032302f30382f32312f644e6462464a2e706e67)
> 是不是文件大小超出了系统限制？分布式脚本的空间限制是多少？

整体空间是300GB的上限. 单个文件尽可能控制在100GB以内吧. 
需要您提供一下任务ID (提交任务之后, 表格最左侧会出现任务编号), 才能继续查看原因.

**Comment by sunjie97** [comment]
好的，大致知道原因了，数据集解压所占的空间远远超过这个空间限制了。谢谢您的解答
