### ISSUE TITLE
AttributeError: module 'paddle.fluid.dygraph' has no attribute 'enable_imperative'

### ISSUE THREAD

**Issue by R132** [PaddlePaddle/Paddle#26547]
使用AIstudio上的paddlepaddle环境，

Python 3.7.4 (default, Aug 13 2019, 20:35:49) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
import paddle
 paddle.__version__
'1.8.0'

 import paddle.fluid as fluid
 fluid.dygraph.enable_imperative()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'paddle.fluid.dygraph' has no attribute 'enable_imperative'

为什么会这样呢？在自己的电脑上可以运行

**Comment by yongqiangma** [comment]
这个和paddle 版本有关，需要添加fluid.dygraph.enable_imperative()

**Comment by chenwhql** [comment]
可以改成用`fluid.enable_dygraph()`去跑
