### ISSUE TITLE
【论文复现】Aistudio问题

### ISSUE THREAD

**Issue by chfhf** [PaddlePaddle/Paddle#26556]
![1](https://user-images.githubusercontent.com/19964528/90949444-91b62d80-e47a-11ea-96fb-745abf7f79f0.png)

项目地址如下
https://aistudio.baidu.com/bdvgpu32g/user/288399/739037/notebooks/739037.ipynb
该问题从昨天开始出现，程序可以正常迭代，但跑到可能上千轮就会内存溢出，反复多次皆是如此，
昨天之前训练上万轮都无错误正常结束，从昨天开始出现问题

**Comment by saxon-zh** [comment]
@weiexcelpro 辛苦看看帮忙定位一下问题
