### ISSUE TITLE
[论文复现] 使用fluid.layers.random_crop 函数处理图像有错误

### ISSUE THREAD

**Issue by Costwen** [PaddlePaddle/Paddle#26555]
![1b09bbc700e340d635e70f03688d035](https://user-images.githubusercontent.com/47916831/90948701-f28e3780-e473-11ea-8887-2b1cbb679881.png)
裁剪之后的图像效果显示有重影

`
    
    def totensor(imgs, type):

    imgs = fluid.dygraph.to_variable(imgs)
    imgs = imgs / 255.
    imgs = fluid.layers.transpose(imgs, (0,3,1,2))
    if type == 'A':
        imgs = fluid.layers.image_resize(imgs, (256+30,256+30))
        imgs = fluid.layers.random_crop(imgs, (256,256))
        imgs = (imgs - 0.5) / 0.5
    else :
        imgs = fluid.layers.image_resize(imgs, (256,256))
        imgs = (imgs - 0.5) / 0.5
    return imgs
`
这是我写的裁剪的代码

**Comment by yongqiangma** [comment]
check一下RGB和BGR的转换时顺序是否正确
