### ISSUE TITLE
【论文复现】如何构建一个权重已知的卷积层？

### ISSUE THREAD

**Issue by R132** [PaddlePaddle/Paddle#26568]
需要使用到高斯滤波进行卷积操作，
通过输入图像计算高斯滤波器卷积核，
pytorch中的conv2d可以通过指定weight=self.weight来实现，Paddle中要如何处理？

查阅了很多api都有一种似是而非的感觉。
使用其他函数库的卷积操作无法使用GPU可能影响效率。

**Comment by zhupengyang** [comment]
- conv2d的参数是个 ParamAttr 对象。
![image](https://user-images.githubusercontent.com/50474132/90974276-470ce200-e55c-11ea-85ad-46df766ec634.png)
- ParamAttr 对象可以通过initializer进行初始化。
![image](https://user-images.githubusercontent.com/50474132/90974288-6146c000-e55c-11ea-8b70-4c844a827954.png)
- [NumpyArrayInitializer](https://www.paddlepaddle.org.cn/documentation/docs/zh/api_cn/initializer_cn/NumpyArrayInitializer_cn.html#numpyarrayinitializer)可以使用numpy数组初始化参数。

**Comment by R132** [comment]
> * conv2d的参数是个 ParamAttr 对象。
>   ![image](https://user-images.githubusercontent.com/50474132/90974276-470ce200-e55c-11ea-85ad-46df766ec634.png)
> * ParamAttr 对象可以通过initializer进行初始化。
>   ![image](https://user-images.githubusercontent.com/50474132/90974288-6146c000-e55c-11ea-8b70-4c844a827954.png)
> * [NumpyArrayInitializer](https://www.paddlepaddle.org.cn/documentation/docs/zh/api_cn/initializer_cn/NumpyArrayInitializer_cn.html#numpyarrayinitializer)可以使用numpy数组初始化参数。

感谢！之前没找到NumpyArrayInitializer，用常数初始化发现不是想要的
