### ISSUE TITLE
[论文复现] torch.optim.Adam和fluid.optimizer.Adam加上weight_decay后，loss无法对齐

### ISSUE THREAD

**Issue by lyl120117** [PaddlePaddle/Paddle#26578]
**自己写了一个简单的网络测试使用Adam看pytorch和paddle的loss能否对齐，torch.optim.Adam有个weight_decay，通过查找相关的文档，fluid.optimizer.Adam也可以设置regularization与之对应，实际测试的结果当都不设置weight_decay这个参数时，loss误差为2e-8，加上weight_decay，loss误差为3.8e-3，为啥加上weight_decay后误差会变这么大？**

**Paddle的实现如下：**
`self.optmizes = fluid.optimizer.AdamOptimizer(learning_rate=0.01,
                                                          parameter_list=self.model.parameters(),
                                                          beta1=0.0,
                                                          beta2=0.99,
                                                          regularization=fluid.regularizer.L2Decay(1e-4)
                                                          )`

**Pytorch的实现如下：**
`self.optmizes = torch.optim.Adam(self.model.parameters(),
                                         lr=0.01, betas=[0.0, 0.99],
                                         weight_decay=1e-4
                                         )`

由于论文复现需要实现torch.optim.Adam中的weight_decay，请问有没有其它方法能实现weight_decay效果？

我这边测试的代码：
[adam.zip](https://github.com/PaddlePaddle/Paddle/files/5114184/adam.zip)

**Comment by zhupengyang** [comment]
你好，与torch的对齐问题 @MRXLT 会进行后续的跟进

**Comment by lyl120117** [comment]
> 你好，与torch的对齐问题 @MRXLT 会进行后续的跟进

谢谢

**Comment by MRXLT** [comment]
你好，请问使用的paddle和torch的版本是多少

**Comment by lyl120117** [comment]
> 你好，请问使用的paddle和torch的版本是多少

torch           1.4.0
torchsummary    1.5.1
torchvision     0.5.0

paddlepaddle-gpu    1.8.4.post107

**Comment by MRXLT** [comment]
你好，使用提供的代码进行对比，不设置weight_decay的时候，paddle和torch的diff如下
![image](https://user-images.githubusercontent.com/16594411/91143076-85cda400-e6e4-11ea-8762-4dfa71537079.png)
设置weight的时候，paddle和torch的diff如下
![image](https://user-images.githubusercontent.com/16594411/91143125-9716b080-e6e4-11ea-9cb0-9755eda0553a.png)
并没没有

 > 实际测试的结果当都不设置weight_decay这个参数时，loss误差为2e-8，加上weight_decay，loss误差为3.8e-3

这么大的区别

实际使用中paddle和torch使用adam训练出的模型效果差的明显吗

**Comment by lyl120117** [comment]
您好，我们对比误差的方式可能不一样，请问您是怎么对比的？

**Comment by ruyijidan** [comment]
![L2](https://user-images.githubusercontent.com/40780469/91184572-5a1bdf80-e71f-11ea-90f0-d514d29049b1.png)
个人的一点理解，增加正则后的损失是与每个权重都有关系的，如果每个权重可以保证是在6位有效数字对齐的，那也保证不了权重**之和**也是6位有效数字是对齐的。参数量很大，**求和**之后的误差自然就会变大。可以试验一下，改用L1正则，个人觉得误差会更大。

**Comment by lyl120117** [comment]
> ![L2](https://user-images.githubusercontent.com/40780469/91184572-5a1bdf80-e71f-11ea-90f0-d514d29049b1.png)
> 个人的一点理解，增加正则后的损失是与每个权重都有关系的，如果每个权重可以保证是在6位有效数字对齐的，那也保证不了权重**之和**也是6位有效数字是对齐的。参数量很大，**求和**之后的误差自然就会变大。可以试验一下，改用L1正则，个人觉得误差会更大。

我用的很简单的网络对比测试的，就一个卷基层，参数量很小哦。

**Comment by MRXLT** [comment]
不好意思，经过确认，paddle的adam优化器实现与论文的计算公式有一些diff，我们正在修复

**Comment by lyl120117** [comment]
> 不好意思，经过确认，paddle的adam优化器实现与论文的计算公式有一些diff，我们正在修复

好的，麻烦您了

**Comment by saxon-zh** [comment]
@lyl120117 经过模型和框架研发同学评估，这个diff对模型影响不是非常大，建议先不使用weight decay来对齐模型，其他部分全部对齐后再对齐weight decay，如果仍然存在问题再反馈给我们继续跟进 :)

**Comment by sys1874** [comment]
@saxon-zh 请问adam的实现与torch 的adam实现有diff 吗？我现在跑的三个模型，都是用的adam优化器，都比torch实现的代码差0.5%的结果
使用的是静态图1.8 的 adam

**Comment by saxon-zh** [comment]
> @saxon-zh 请问adam的实现与torch 的adam实现有diff 吗？我现在跑的三个模型，都是用的adam优化器，都比torch实现的代码差0.5%的结果
> 使用的是静态图1.8 的 adam

如果确定其他的部分都对齐了的话，可以提供下代码，我们让模型研发的同学协助看看。
