### ISSUE TITLE
[论文复现] paddle.fluid.core_avx.VarBase如何转换为array

### ISSUE THREAD

**Issue by mofengboy** [PaddlePaddle/Paddle#26574]
请问 paddle.fluid.core_avx.VarBase如何转换为array

**Comment by zhupengyang** [comment]
可以使用 [numpy()方法](https://www.paddlepaddle.org.cn/documentation/docs/zh/api_cn/fluid_cn/Variable_cn.html#numpy) 转为numpy数组

**Comment by ymzlygw** [comment]
> 可以使用 [numpy()方法](https://www.paddlepaddle.org.cn/documentation/docs/zh/api_cn/fluid_cn/Variable_cn.html#numpy) 转为numpy数组

那么麻烦问下如何反向转换呢？如何将numpy数组转为paddle.fluid.core_avx.VarBase，现在刚好用到这个问题，不知道怎么转换回去。

**Comment by zhupengyang** [comment]
[to_variable()](https://www.paddlepaddle.org.cn/documentation/docs/zh/api_cn/dygraph_cn/to_variable_cn.html#to-variable) : numpy -> VarBase 的转换
