### ISSUE TITLE
torch.autograd.grad到paddle转换后在训练过程中报错，请问什么原因

### ISSUE THREAD

**Issue by hai715** [PaddlePaddle/Paddle#26597]
![image](https://user-images.githubusercontent.com/59641309/91013107-c9a7a700-e619-11ea-9d3f-a598ac426419.png)
该函数使用后在运行中报错
![image](https://user-images.githubusercontent.com/59641309/91013178-df1cd100-e619-11ea-8a53-6228c8867212.png)
![image](https://user-images.githubusercontent.com/59641309/91013208-e7750c00-e619-11ea-8357-25df61fd496e.png)

**Comment by willthefrog** [comment]
可能不支持double grad吧。按错误信息把`create_graph`设为false试下？

**Comment by hai715** [comment]
那不行，我的网络需要把create_graph设为true

**Comment by willthefrog** [comment]
那你的用法可能现在不支持。

**Comment by phlrain** [comment]
这个报错是 batch_norm 没有double grad 的问题

**Comment by qingqing01** [comment]
@hai715 完整的batch-norm实现，还不支持double-grad，另一个可替代的方案，可以参考 https://github.com/PaddlePaddle/models/blob/release/1.4/PaddleCV/gan/cycle_gan/layers.py#L22 instance-norm的子op拼接，拼接一个batch-norm，instance-norm用到的子op都支持double-grad.
