### ISSUE TITLE
paddlle gpu版本与torch同时调用则错误退出

### ISSUE THREAD

**Issue by lin1github** [PaddlePaddle/Paddle#26605]
我安装了paddlepaddle-gpu==1.7.2.post97，pytorch是1.0.1版本，运行下面语句则不会报错，
import paddle
import torch
但是如果是
import paddle.fluid as fluid
import torch
则会出错，退出程序，没有用的报错信息，我个人感觉是cudnn的问题，请指导一下定位问题

**Comment by willthefrog** [comment]
应该是gcc版本问题，如果需要同时使用torch，需要gcc5以上版本的paddle。

**Comment by lin1github** [comment]
报错信息如下：
W0824 20:32:07.544497 10761 init.cc:209] Warning: PaddlePaddle catches a failure signal, it may not work properly
W0824 20:32:07.544538 10761 init.cc:211] You could check whether you killed PaddlePaddle thread/process accidentally or report the case to PaddlePaddle
W0824 20:32:07.544545 10761 init.cc:214] The detail failure signal is:
W0824 20:32:07.544554 10761 init.cc:217] *** Aborted at 1598272327 (unix time) try "date -d @1598272327" if you are using GNU date ***
W0824 20:32:07.548422 10761 init.cc:217] PC: @                0x0 (unknown)
W0824 20:32:07.548569 10761 init.cc:217] *** SIGSEGV (@0x558a9e7d5c20) received by PID 10761 (TID 0x7ffbe32c8740) from PID 18446744072073600032; stack trace: ***
W0824 20:32:07.552098 10761 init.cc:217]     @     0x7ffbe2ec1890 (unknown)
W0824 20:32:07.555570 10761 init.cc:217]     @     0x558a9e7d5c20 (unknown)
错误码异常: exitCode = 139
Process completed unsuccessfully in 4 seconds.

**Comment by willthefrog** [comment]
大概率是gcc版本问题。建议尝试使用gcc5以上版本从源码编译paddle。

**Comment by lin1github** [comment]
> 大概率是gcc版本问题。建议尝试使用gcc5以上版本从源码编译paddle。

我查看了一下，打gcc -v，出的结果是gcc version 7.5.0 (Ubuntu 7.5.0-3ubuntu1~18.04) ，应该是5以上的版本了吧

**Comment by lin1github** [comment]
经过尝试，将pytorch升级到最新版本，就没这个问题了
