### ISSUE TITLE
【论文复现】UGATIT 关于AIStudio脚本模式

### ISSUE THREAD

**Issue by sincerevertigo** [PaddlePaddle/Paddle#26602]
脚本模式下，可以用动图吗？
还是只能用静态图？

谢谢。

**Comment by willthefrog** [comment]
应该都可以吧。

**Comment by saxon-zh** [comment]
是遇到什么问题了吗？

**Comment by sincerevertigo** [comment]
@saxon-zh 
想使用脚本模式进行训练。
但是，代码是用动图实现的，我看脚本的sample好像是静态图的。
有动图的例子吗？
谢谢。

**Comment by saxon-zh** [comment]
@sincerevertigo 可以参照这篇动态图教程做相关代码实现[命令式编程使用教程](https://www.paddlepaddle.org.cn/documentation/docs/zh/beginners_guide/basic_concept/dygraph/DyGraph.html)
