### ISSUE TITLE
使用InMemoryDataset碰到问题

### ISSUE THREAD

**Issue by starsblinking** [PaddlePaddle/Paddle#26618]
运行的就是 https://github.com/PaddlePaddle/models/tree/develop/PaddleRec/ctr/dnn#%E5%BC%95%E5%85%A5dataset 这个例子。
已经能正常跑通了，但是【把“fluid.DatasetFactory().create_dataset()”改成“fluid.DatasetFactory().create_dataset("InMemoryDataset")”，并且在调用exe.train_from_dataset()前加上dataset.load_into_memory()】就出现了很诡异的结果：训练每个epoch时exe.train_from_dataset的耗时变为0秒，并且auc的信息也不打印了（正常结果见上述网页中展示的trainer.0.log）；除此之外，没有任何报错信息，程序正常结束。

请问是我使用方法不对吗？

为使您的问题得到快速解决，在建立Issues前，请您先通过如下方式搜索是否有相似问题:【搜索issue关键字】【使用labels筛选】【官方文档】
   1）PaddlePaddle版本：1.8.3
   2）CPU：用CPU，MKL
   4）系统环境：python2.7.18 ,centos7
注：您可以通过执行summary_env.py获取以上信息。

训练信息
   1）多机

**Comment by willthefrog** [comment]
这个问题建议提到 fleet的repo，“InMemoryDataset”是fleet的组件，提到那边交流更直接。

**Comment by starsblinking** [comment]
> 这个问题建议提到 fleet的repo，“InMemoryDataset”是fleet的组件，提到那边交流更直接。

1. fleet的repo在哪？感觉好像被删了。
2. 这里用到的create_dataset是1.8版的paddle/fluid/dataset.py里的，而不是develop版里才有的paddle/distributed/fleet/dataset/dataset.py里的。所以不应该算是fleet的组件吧？本地数据的读取方式会和是否分布式训练有关吗?

**Comment by willthefrog** [comment]
辛苦 @yaoxuefeng6 安排跟进下。

**Comment by yaoxuefeng6** [comment]
应该需要先set_filelist 然后再load_into_memory 是不是这个顺序反了

**Comment by starsblinking** [comment]
> 应该需要先set_filelist 然后再load_into_memory 是不是这个顺序反了

没反。load_into_memory就是紧邻在exe.train_from_dataset之前的一行命令。

**Comment by starsblinking** [comment]
不知道这个曾经的bug修复了没，paddle同学没再回复，我也没再使用当时的版本和相关函数，就先close了吧。
