### ISSUE TITLE
Aur paddle-gpu一行代码安装

### ISSUE THREAD

**Issue by linhandev** [PaddlePaddle/Paddle#26620]
在arch的arch user respository做了一个paddlepaddle-gpu的包，可以一行代码安装paddle-gpu包括cuda，cudnn等环境。在我的电脑上测试好用
https://aur.archlinux.org/packages/paddlepaddle-gpu/
或许官方可以将这种安装方式放到paddlepaddle.org.cn上，应该是最简洁的安装方法了

**Comment by willthefrog** [comment]
感谢你的支持(虽然arch比较小众😜，如果是deb包意义可能更大些)
几点建议
- paddle源码编译是可以支持cuda11和cudnn8的（目前`[community]`里的版本），不过需要patch才能支持gcc9正常编译。
- python依赖最好使用包管理器安装，直接pip安装依赖不太符合arch的理念。
- 看上去没装nccl，而且默认官方wheel包是不支持distributed的。
- `pkgver`是1.9.7?

**Comment by linhandev** [comment]
这是我第一次写pkgbuild，也没使过ubuntu😂看到有tf的aur感觉可以给paddle也整一个，这几天研究研究大佬提到的功能，尽量搞进去

**Comment by homalozoa** [comment]
可以可以，能帮忙更新下AUR吗兄弟 @linhandev ,Out-of-Date 了。
