### ISSUE TITLE
<<论文复现>>paddle高级API-hapi中hapi.vision.transforms中的Normalize初始化方法中std赋值错误

### ISSUE THREAD

**Issue by xjhcassy** [PaddlePaddle/Paddle#26627]
![image](https://user-images.githubusercontent.com/38745202/91057128-676e9680-e659-11ea-9c7e-0cbede7d291e.png)

**Comment by willthefrog** [comment]
呃，确实是个bug，会跟进修复，谢谢。

**Comment by willthefrog** [comment]
@LielinJiang  可否跟进一下？

**Comment by LielinJiang** [comment]
好的，可以先输入list来绕过一下。像这样normalize = Normalize(mean=[0,0,0], std=[1,1,1])
