### ISSUE TITLE
【论文复现】UGTIT 训练时g loss一直保持在1500左右，请问一下什么原因导致的？

### ISSUE THREAD

**Issue by cgq0816** [PaddlePaddle/Paddle#26622]
[  917/1000000] time: 3815.6953 d_loss: 0.12188511, g_loss: 1448.89843750
[  918/1000000] time: 3819.8836 d_loss: 0.02917238, g_loss: 1459.32421875
[  919/1000000] time: 3824.0383 d_loss: 0.04846196, g_loss: 1647.95532227
[  920/1000000] time: 3828.6340 d_loss: 0.06229257, g_loss: 1470.34814453
[  921/1000000] time: 3832.5813 d_loss: 0.05693095, g_loss: 1545.22729492
[  922/1000000] time: 3837.1286 d_loss: 0.01655540, g_loss: 1442.55834961
[  923/1000000] time: 3841.3376 d_loss: 0.04079375, g_loss: 1429.55493164
[  924/1000000] time: 3845.4217 d_loss: 0.01959240, g_loss: 1559.52734375
[  925/1000000] time: 3849.5384 d_loss: 0.06316221, g_loss: 1447.45922852
[  926/1000000] time: 3853.6473 d_loss: 0.05139202, g_loss: 1452.93127441
[  927/1000000] time: 3857.8100 d_loss: 0.01829061, g_loss: 1491.23034668
[  928/1000000] time: 3861.7862 d_loss: 0.01879046, g_loss: 1472.97729492
[  929/1000000] time: 3866.0233 d_loss: 0.10855635, g_loss: 1449.33398438
[  930/1000000] time: 3870.2667 d_loss: 0.07406638, g_loss: 1439.97705078
[  931/1000000] time: 3874.4432 d_loss: 0.04643098, g_loss: 1572.55334473
[  932/1000000] time: 3878.5090 d_loss: 0.09691430, g_loss: 1425.58154297

**Comment by willthefrog** [comment]
建议提到models里请gan相关的同学帮忙解答。

**Comment by cgq0816** [comment]
已提交到models区，这就关闭啦
