### ISSUE TITLE
<<论文复现>>如何对齐paddle中随机数种子与pytorch中随机数种子

### ISSUE THREAD

**Issue by xjhcassy** [PaddlePaddle/Paddle#26637]

**Comment by LielinJiang** [comment]
当前版本还无法做到。具体是用在什么层中呢？

**Comment by xjhcassy** [comment]
全局的，像torch.manual_seed(opt.manual_seed)这样

**Comment by zhiqiu** [comment]
> 全局的，像torch.manual_seed(opt.manual_seed)这样

hi，我们正在支持torch类似的manual_seed和generator功能。

**Comment by GuoQuanhao** [comment]
这个问题解决了吗，paddle有对应的API了吗 torch.manual_seed

**Comment by GuoQuanhao** [comment]
paddle.framework.seed(seed) 好像在2.0版本找到了

**Comment by ToscanaGoGithub** [comment]
似乎是不能完全对齐的，就算是设置一样的随机数种子，根据这个种子初始化一些参数的时候仍然会与一些区别。只能依靠加载预训练模型来进行对齐

**Comment by yyinsomnia** [comment]
paddle.seed()，用paddle.randint测试过自身是能能稳定随机。
但是用同样的seed，paddle和torch randint出来是不一样的，这个要对齐确实有点勉为其难了。
