### ISSUE TITLE
paddle的动态图部署到flask的会hang住

### ISSUE THREAD

**Issue by June-z93** [PaddlePaddle/Paddle#26635]
为使您的问题得到快速解决，在建立Issue前，请您先通过如下方式搜索是否有相似问题:【搜索issue关键字】【使用labels筛选】【官方文档】

如果您没有查询到相似问题，为快速解决您的提问，建立issue时请提供如下细节信息：
- 标题：简洁、精准描述您的问题，例如“最新预测库的API文档在哪儿 ”
- 版本、环境信息：
    1）PaddlePaddle版本：请提供您的PaddlePaddle版本号（如1.1）或CommitID
          1.8.3
    2）CPU：预测若用CPU，请提供CPU型号，MKL/OpenBlas/MKLDNN/等数学库使用情况
          CPU未使用MKL/OpenBlas/MKLDNN/等数学库
    3）GPU：预测若用GPU，请提供GPU型号、CUDA和CUDNN版本号
    4）系统环境：请您描述系统类型、版本（如Mac OS 10.14），Python版本
       Python 2.7.15
       Red Hat 4.4.4-13
注：您可以通过执行[summary_env.py](https://github.com/PaddlePaddle/Paddle/blob/develop/tools/summary_env.py)获取以上信息。
-预测信息
    1）C++预测：请您提供预测库安装包的版本信息，及其中的version.txt文件
    2）CMake包含路径的完整命令
    3）API信息（如调用请提供）
    4）预测库来源：官网下载/特殊环境（如BCLOUD编译）
- 复现信息：如为报错，请给出复现环境、复现步骤
- 问题描述：请详细描述您的问题，同步贴出报错信息、日志/代码关键片段
动态图部署在flask，return前一句的日志正常输出，但是return没有返回值, 之前看有同样的问题，但是后来没有跟进了https://github.com/PaddlePaddle/Paddle/issues/24951，辛苦再看下

def handle_request(req):
    label = ""
    lable_id = ""
    rate = 0.0
    try:
        data = req["trans"]["text"]
        #logging.debug("start handle request, data:{}".format(data.decode('utf-8')))
        #print data
        data_id = [tokenizer.encode(data)[0]]
        logging.info("handle request, data_id:{}".format(data_id))
        data_tensor = textcnn_predict.D.to_variable(textcnn_predict.np.array(data_id))
        logging.info("textcnn_predict data_tensor")
        lable_id,rate = textcnn_predict.single_infer(text_cnn, data_tensor)
        logging.info("textcnn_predict.single_infer")
        label = label_encoder.inverse_transform(lable_id)

        print label.encode('utf-8')
        #logging.info("handle request end. data:{} lable:{}".format(data, lable))
    except Exception as ex:
        logging.exception("ServiceMngr handler_request Exception [{}]".format(str(ex)))
        return False, label, lable_id, rate
    print label.encode('utf-8')
    print lable_id
    print rate
    print "handle_request success"
    return True, "hello", "word", 0.9

Thank you for contributing to PaddlePaddle.
Before submitting the issue, you could search issue in the github in case that th
If there is no solution,please make sure that this is an inference issue including the following details :
**System information**
-PaddlePaddle version （eg.1.1）or CommitID
-CPU: including CPUMKL/OpenBlas/MKLDNN version
-GPU: including CUDA/CUDNN version
-OS Platform (eg.Mac OS 10.14)
-Python version
-Cmake orders
-C++version.txt
-API information
Note: You can get most of the information by running [summary_env.py](https://github.com/PaddlePaddle/Paddle/blob/develop/tools/summary_env.py). 
**To Reproduce**
Steps to reproduce the behavior
**Describe your current behavior**
**Code to reproduce the issue**
**Other info / logs**

**Comment by LielinJiang** [comment]
如果不部署在flask会有返回值嘛？

**Comment by June-z93** [comment]
会有的
