### ISSUE TITLE
fluid1.8.2 GPU+CPU联合训练

### ISSUE THREAD

**Issue by HsiaChubby** [PaddlePaddle/Paddle#26638]
在使用fluid.1.8.2版本进行GPU与CPU混合训练模型：
![image](https://user-images.githubusercontent.com/24514473/91145093-861b6e80-e6e7-11ea-82b1-18f9d8c830e1.png)

训练过程如下：
![image](https://user-images.githubusercontent.com/24514473/91121568-a5f06980-e6ca-11ea-9a24-65368e36a735.png)

![image](https://user-images.githubusercontent.com/24514473/91121671-e0f29d00-e6ca-11ea-8199-8e8efcac3840.png)

问题描述：
/opt/_internal/cpython-3.7.0/lib/python3.7/site-packages/paddle/fluid/executor.py:1070: UserWarning: The following exception is not an EOF exception.
  "The following exception is not an EOF exception.")
I0824 20:38:44.973078 17551 mmap_allocator.cc:124] PID: 17551, MemoryMapFdSet: set size - 0
Traceback (most recent call last):
  File "trainer_gpu.py", line 94, in <module>
    main(params)
  File "trainer_gpu.py", line 77, in main
    fetch_list=[loss.name]
  File "/opt/_internal/cpython-3.7.0/lib/python3.7/site-packages/paddle/fluid/parallel_executor.py", line 303, in run
    return_numpy=return_numpy)
  File "/opt/_internal/cpython-3.7.0/lib/python3.7/site-packages/paddle/fluid/executor.py", line 1071, in run
    six.reraise(*sys.exc_info())
  File "/opt/_internal/cpython-3.7.0/lib/python3.7/site-packages/six.py", line 703, in reraise
    raise value
  File "/opt/_internal/cpython-3.7.0/lib/python3.7/site-packages/paddle/fluid/executor.py", line 1066, in run
    return_merged=return_merged)
  File "/opt/_internal/cpython-3.7.0/lib/python3.7/site-packages/paddle/fluid/executor.py", line 1167, in _run_impl
    return_merged=return_merged)
  File "/opt/_internal/cpython-3.7.0/lib/python3.7/site-packages/paddle/fluid/executor.py", line 879, in _run_parallel
    tensors = exe.run(fetch_var_names, return_merged)._move_to_list()
paddle.fluid.core_avx.EnforceNotMet: 

--------------------------------------------
C++ Call Stacks (More useful to developers):
--------------------------------------------
0   std::string paddle::platform::GetTraceBackString<std::string const&>(std::string const&, char const*, int)
1   paddle::platform::EnforceNotMet::EnforceNotMet(std::string const&, char const*, int)
2   paddle::framework::OperatorWithKernel::ParseInputDataType(paddle::framework::ExecutionContext const&, std::string const&, paddle::framework::proto::VarType_Type*) const
3   paddle::framework::OperatorWithKernel::IndicateVarDataType(paddle::framework::ExecutionContext const&, std::string const&) const
4   paddle::operators::SequenceMaskOp::GetExpectedKernelType(paddle::framework::ExecutionContext const&) const
5   paddle::framework::OperatorWithKernel::ChooseKernel(paddle::framework::RuntimeContext const&, paddle::framework::Scope const&, paddle::platform::Place const&) const
6   paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, paddle::platform::Place const&, paddle::framework::RuntimeContext*) const
7   paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, paddle::platform::Place const&) const
8   paddle::framework::OperatorBase::Run(paddle::framework::Scope const&, paddle::platform::Place const&)
9   paddle::framework::details::ComputationOpHandle::RunImpl()
10  paddle::framework::details::FastThreadedSSAGraphExecutor::RunOpSync(paddle::framework::details::OpHandleBase*)
11  paddle::framework::details::FastThreadedSSAGraphExecutor::RunOp(paddle::framework::details::OpHandleBase*, std::shared_ptr<paddle::framework::BlockingQueue<unsigned long> > const&, unsigned long*)
12  std::_Function_handler<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> (), std::__future_base::_Task_setter<std::unique_ptr<std::__future_base::_Result<void>, std::__future_base::_Result_base::_Deleter>, void> >::_M_invoke(std::_Any_data const&)
13  std::__future_base::_State_base::_M_do_set(std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> ()>&, bool&)
14  ThreadPool::ThreadPool(unsigned long)::{lambda()#1}::operator()() const

------------------------------------------
Python Call Stacks (More useful to users):
------------------------------------------
  File "/opt/_internal/cpython-3.7.0/lib/python3.7/site-packages/paddle/fluid/framework.py", line 2610, in append_op
    attrs=kwargs.get("attrs", None))
  File "/opt/_internal/cpython-3.7.0/lib/python3.7/site-packages/paddle/fluid/layer_helper.py", line 43, in append_op
    return self.main_program.current_block().append_op(*args, **kwargs)
  File "/opt/_internal/cpython-3.7.0/lib/python3.7/site-packages/paddle/fluid/layers/sequence_lod.py", line 1342, in sequence_mask
    type='sequence_mask', inputs=inputs, outputs={'Y': out}, attrs=attrs)
  File "/root/paddlejob/workspace/env_run/model/bic_user2vec_v2.py", line 152, in bic_user2vec
    mask_sequence = fluid.layers.sequence_mask(x=feature_seq_length, maxlen=maxlen, dtype='float32')
  File "trainer_gpu.py", line 42, in main
    loss, predicts, labels = bic_user2vec.bic_user2vec(inputs, params)
  File "trainer_gpu.py", line 94, in <module>
    main(params)

----------------------
Error Message Summary:
----------------------
InvalidArgumentError: The Tensor in the sequence_mask Op's Input Variable X(wordid_seq_length) is not initialized.
  [Hint: Expected t->IsInitialized() == true, but received t->IsInitialized():0 != true:1.] at (/paddle/paddle/fluid/framework/operator.cc:1289)
  [operator < sequence_mask > error]

**Comment by LielinJiang** [comment]
您好，这个代码没看出来是如何gpu+cpu联合训练的。这个提示像是没有初始化，请问是否有exe.run(start_up_program)

**Comment by HsiaChubby** [comment]
> 您好，这个代码没看出来是如何gpu+cpu联合训练的。这个提示像是没有初始化，请问是否有exe.run(start_up_program)

这个逻辑是这样子的，整个训练任务是在单机多卡环境中执行的，但是因为其中的user embedding比较大，GPU的显卡装不下，所以，user embedding层的op是制定在CPU上进行处理的：
![image](https://user-images.githubusercontent.com/24514473/91143560-494e7800-e6e5-11ea-903c-58a5f17b76a9.png)
然后，也分别对CUDAPlace和CPUPlace进行了初始化的操作
![image](https://user-images.githubusercontent.com/24514473/91143645-6e42eb00-e6e5-11ea-9e78-c6efeca26e53.png)

**Comment by LielinJiang** [comment]
我看了下device guard的demo，不需要创建两个excutor。按照你的模型定义，你只需要gpu的excutor就行了
