### ISSUE TITLE
动态图用tracedlayer转静态图出错

### ISSUE THREAD

**Issue by HawChang** [PaddlePaddle/Paddle#26640]
版本：
1. paddlepaddle-gpu: 1.8.1.post107
2. GPU: P40
3. Driver Version: 440.33.01
4. CUDA Version: 10.2
5. CentOS release 6.3 (Final)
6. Python 2.7.15

问题：
动态图训练好TextCNN模型后，尝试转静态图失败。

模型结构：
![image](https://user-images.githubusercontent.com/7113823/91121914-87d73900-e6cb-11ea-8c7b-45cd36fc95ca.png)
![image](https://user-images.githubusercontent.com/7113823/91121886-7726c300-e6cb-11ea-8208-a80e46639f66.png)

模型转静态图代码：
![image](https://user-images.githubusercontent.com/7113823/91121976-adfcd900-e6cb-11ea-8319-e281158e551d.png)
![image](https://user-images.githubusercontent.com/7113823/91121987-b3f2ba00-e6cb-11ea-8f57-ae088c9ceb95.png)

麻烦看一下这个问题出在哪里

**Comment by zhhsplendid** [comment]
嗨，看你的截图，load_model时显示找不到model文件。底下的报错是变量var找不到，结合你这边找不到model文件，是否可能是没有load进参数导致一些参数var没找到？麻烦你那边查看一下load_model?

**Comment by HawChang** [comment]
> 嗨，看你的截图，load_model时显示找不到model文件。底下的报错是变量var找不到，结合你这边找不到model文件，是否可能是没有load进参数导致一些参数var没找到？麻烦你那边查看一下load_model?

噢，那个地方是模型地址写错，改对地址后还是会有该问题。经排查，我发现是TextCNN模型的forward返回值的问题，我这里设计forward返回值是固定loss和logits，当label为None时，loss为None。 这样设计模型，就会出错。而如果我在label为None时，只返回一个logits，就不会出错。

麻烦看看这个情况的具体原因。

**Comment by zhhsplendid** [comment]
是这样的，TracedLayer的基本原理只是trace，所以无法处理你说的，按输入判断是否为None来运行程序。您是1.8版本，可以试试这里提到的ProgramTranslator：

https://www.paddlepaddle.org.cn/documentation/docs/zh/beginners_guide/basic_concept/dygraph/DyGraph.html#id11
