### ISSUE TITLE
【论文复现】关于动态图加载权重的几个问题

### ISSUE THREAD

**Issue by thunder95** [PaddlePaddle/Paddle#26662]
1. 动态图里怎么加载文件夹的权重， 从paddle/models里下载了预训练权重，是个文件夹， 而不是pdparams格式的，所以就用不了这个api了么: paddle.fluid.dygraph.load_dygraph
2. 下载的Resnet50的权重，官网提供的是2d网络结构的， 我需要升到3维（Resnet50的I3D）， 怎么对每一层做这样的升维操作？

我尝试复现的论文是TPN，想加载Resnet50预训练权重，目前网络已经搭好。

**Comment by LielinJiang** [comment]
1. 当前版本无法使用动态图直接加载文件夹中的权重。
2. 如果resnet50 3d结构不同的话，无法使用resnet50 2d的权重的。

可以尝试将官方论文release的预训练权重转化的paddle的。load_dygraph所需要的权重是dict的形式就行，用pickle保存下来就能加载。论文复现营中应该有这样的一个教程，可以问问老师。
