### ISSUE TITLE
"Unsupported protocol" when download eigen using ExternalProject_Add

### ISSUE THREAD

**Issue by Xreki** [PaddlePaddle/Paddle#2666]
The detailed error information is listed as follows:
```
[  0%] Performing download step (download, verify and extract) for 'eigen3'
-- downloading...
     src='https://bitbucket.org/eigen/eigen/get/3.3.4.tar.gz'
     dst='/home/liuyiqun01/github/Paddle/build/third_party/eigen3/src/3.3.4.tar.gz'
     timeout='none'
CMake Error at eigen3-stamp/download-eigen3.cmake:27 (message):
  error: downloading 'https://bitbucket.org/eigen/eigen/get/3.3.4.tar.gz'
  failed

    status_code: 1
    status_string: "Unsupported protocol"
    log: Protocol "https" not supported or disabled in libcurl

  Closing connection -1

  



make[2]: *** [third_party/eigen3/src/eigen3-stamp/eigen3-download] Error 1
make[1]: *** [CMakeFiles/eigen3.dir/all] Error 2
make: *** [all] Error 2
```

I have googled the error, and found out the reason:
> CMake builds its own curl, without ssl support by default, unless you
point it to the system curl.
>
>You can rebuild CMake with the CMAKE_USE_OPENSSL ON if you have all
the right supporting system libraries installed.
>
>Or you can figure out an http download site to use with the non-ssl builds...

**Comment by QiJune** [comment]
If you have ```hg``` installed in your PC, you can just replace URL and URL_MD5 in cmake/external/eigen.cmake

```
HG_REPOSITORY "https://bitbucket.org/eigen/eigen"
HG_TAG "3.3.4"
```
In baidu, ```jumbo install mercurial``` will get ```hg```.
