### ISSUE TITLE
Add paddlepaddle to conda-forge

### ISSUE THREAD

**Issue by marcelotrevisani** [PaddlePaddle/Paddle#26663]
Could you please add paddlepaddle to conda-forge?
https://github.com/conda-forge/staged-recipes/

**Comment by phlrain** [comment]
We will add paddlepaddle to conda-forge soon.

**Comment by marcelotrevisani** [comment]
it is also related to 
https://github.com/PaddlePaddle/Paddle/issues/23569

**Comment by gbeckenkamp** [comment]
It would be great to have paddlepaddle on conda, I'm also waiting for it.
