### ISSUE TITLE
关于动态图多卡训练的几个问题

### ISSUE THREAD

**Issue by Yuuuuuuuuuuuuuuuuuummy** [PaddlePaddle/Paddle#26670]
1.开启同步bn只需要sync_batch_norm=True就可以了是么

2.builder.strategy Allreduce和reduce的区别在于allreduce每个卡独自更新参数  reduce会将梯度均匀分配？ 怎么感觉反了呢。

3.clear_gradients()有两个 optimizer 和model都有这个功能，动态图里应该怎么使用呢？ 

文档有一些内容过于简单了感觉，希望能出个多卡训练的官方demo  希望能得到解答！ thx！！

**Comment by LielinJiang** [comment]
1. 动态图貌似没有sync_batch_norm=True这些选项把
2. builder.strategy指的是？
3. optimizer 的clear gradients是清理优化器中的参数的梯度，model的clear gradients是清理模型的参数。对应使用就好了

好的，我们会补充动态图多卡的demo的

**Comment by xjhcassy** [comment]
请进快补充，着急使用
