### ISSUE TITLE
关于 paddle.fluid.layers.batch_norm( ) 接口的疑问

### ISSUE THREAD

**Issue by supyer9** [PaddlePaddle/Paddle#26704]
有如下paddle语句：
conv_bn1 = fluid.layers.batch_norm(
            input=conv1,
            param_attr=fluid.initializer.ConstantInitializer(value=1.0),
            bias_attr=fluid.initializer.ConstantInitializer(value=1e-4),
            act="relu")
关于该语句有两个问题：
1.  act='relu' 的作用是进行 BN 后输入到 relu 激活函数中，得出最后的结果吗？
2.  如上语句没有给 param 进行命名，batch_normal将随机命名。 现在我将训练好的模型的参数按顺序取出，得到该语句涉及的 
     有四个参数，名称如下：
          batch_norm_47.w_0
          batch_norm_47.b_0
          batch_norm_47.w_1
          batch_norm_47.w_2
     请问该四个参数值是否是 scale、offset、mean、variance。如果是，是如何对应的？例如 batch_norm_47.w_0 对应 scale？

**Comment by zhiqiu** [comment]
是的，你的理解是对的，四个参数按顺序分布是：scale, bias, mean, varience
