### ISSUE TITLE
您好，怎么样更改loss和yolo_box的代码

### ISSUE THREAD

**Issue by aboutmei** [PaddlePaddle/Paddle#26706]
您好，
         我们在使用自己制作的数据集进行开发任务，网络输出为（4+number_class）* num_anchors原始为（5+number_class），我们出于某种原因不能更改网络的输出维度，所以有想法重写loss和yolo_box以适应此种网络的输出形式，请问应该以什么方式实现这样的输出形式，我们尝试使用python实现静态图下两部分中的loss_function和yolo_box但是并没有work，请问应以怎样正确的思路来更改静态图中的loss与yolo_box，实现我们希望的loss和yolo_box功能来适配这种网络特殊的固定输出形式
十分期望得到你们的回复
祝好

**Comment by zhiqiu** [comment]
@still-wait 请看下这个关于yolo_box的问题。

**Comment by yghstill** [comment]
@justinmeibi 在https://github.com/PaddlePaddle/PaddleDetection/issues/1288  中继续跟进。

**Comment by zhiqiu** [comment]
> @justinmeibi 在[PaddlePaddle/PaddleDetection#1288](https://github.com/PaddlePaddle/PaddleDetection/issues/1288) 中继续跟进。

在PaddlePaddle/PaddleDetection#1288 中跟进，暂时关闭此issue。
