### ISSUE TITLE
同一个模型用1.8.4版本跑报错，1.8.1没有问题

### ISSUE THREAD

**Issue by HaoLiuHust** [PaddlePaddle/Paddle#26705]
![image](https://user-images.githubusercontent.com/7233091/91290575-57c09080-e7c6-11ea-9b9d-f06d7fdba5e5.png)
1.8.4版本报如上错误，切换成1.8.1后没有问题

**Comment by zhiqiu** [comment]
hi，请问下，你的模型中是不是使用了prelu？

**Comment by HaoLiuHust** [comment]
> hi，请问下，你的模型中是不是使用了prelu？

嗯，里面有prelu

**Comment by zhiqiu** [comment]
> > hi，请问下，你的模型中是不是使用了prelu？
> 
> 嗯，里面有prelu

hi，这个问题我们已经修复了，会在后续1.8.5发版中更新，你可以暂时先用下1.8.1。
