### ISSUE TITLE
测试和训练都报这个错

### ISSUE THREAD

**Issue by NameLacker** [PaddlePaddle/Paddle#26719]
W0827 11:01:05.964001 21363 device_context.cc:252] Please NOTE: device: 0, CUDA Capability: 75, Driver API Version: 10.2, Runtime API Version: 10.0
W0827 11:01:05.964174 21363 dynamic_loader.cc:120] Can not find library: libcudnn.so. The process maybe hang. Please try to add the lib path to LD_LIBRARY_PATH.
W0827 11:01:05.964198 21363 dynamic_loader.cc:179] Failed to find dynamic library: libcudnn.so ( libcudnn.so: cannot open shared object file: No such file or directory ) 
 Please specify its path correctly using following ways: 
 Method. set environment variable LD_LIBRARY_PATH on Linux or DYLD_LIBRARY_PATH on Mac OS. 
 For instance, issue command: export LD_LIBRARY_PATH=... 
 Note: After Mac OS 10.11, using the DYLD_LIBRARY_PATH is impossible unless System Integrity Protection (SIP) is disabled.
/opt/miniconda3/envs/yolo/lib/python3.7/site-packages/paddle/fluid/executor.py:1070: UserWarning: The following exception is not an EOF exception.
  "The following exception is not an EOF exception.")
Traceback (most recent call last):
  File "test.py", line 26, in <module>
    [inference_program, feed_target_names, fetch_targets] = fluid.io.load_inference_model(dirname=path, executor=exe)
  File "/opt/miniconda3/envs/yolo/lib/python3.7/site-packages/paddle/fluid/io.py", line 1402, in load_inference_model
    load_persistables(executor, load_dirname, program, params_filename)
  File "/opt/miniconda3/envs/yolo/lib/python3.7/site-packages/paddle/fluid/io.py", line 928, in load_persistables
    filename=filename)
  File "/opt/miniconda3/envs/yolo/lib/python3.7/site-packages/paddle/fluid/io.py", line 751, in load_vars
    filename=filename)
  File "/opt/miniconda3/envs/yolo/lib/python3.7/site-packages/paddle/fluid/io.py", line 805, in load_vars
    executor.run(load_prog)
  File "/opt/miniconda3/envs/yolo/lib/python3.7/site-packages/paddle/fluid/executor.py", line 1071, in run
    six.reraise(*sys.exc_info())
  File "/opt/miniconda3/envs/yolo/lib/python3.7/site-packages/six.py", line 703, in reraise
    raise value
  File "/opt/miniconda3/envs/yolo/lib/python3.7/site-packages/paddle/fluid/executor.py", line 1066, in run
    return_merged=return_merged)
  File "/opt/miniconda3/envs/yolo/lib/python3.7/site-packages/paddle/fluid/executor.py", line 1154, in _run_impl
    use_program_cache=use_program_cache)
  File "/opt/miniconda3/envs/yolo/lib/python3.7/site-packages/paddle/fluid/executor.py", line 1229, in _run_program
    fetch_var_name)
paddle.fluid.core_avx.EnforceNotMet: 

--------------------------------------------
C++ Call Stacks (More useful to developers):
--------------------------------------------
0   std::string paddle::platform::GetTraceBackString<char const*>(char const*&&, char const*, int)
1   paddle::platform::EnforceNotMet::EnforceNotMet(std::__exception_ptr::exception_ptr, char const*, int)
2   paddle::platform::dynload::EnforceCUDNNLoaded(char const*)
3   paddle::platform::CUDADeviceContext::CUDADeviceContext(paddle::platform::CUDAPlace)
4   std::_Function_handler<std::unique_ptr<paddle::platform::DeviceContext, std::default_delete<paddle::platform::DeviceContext> > (), std::reference_wrapper<std::_Bind_simple<paddle::platform::EmplaceDeviceContext<paddle::platform::CUDADeviceContext, paddle::platform::CUDAPlace>(std::map<paddle::platform::Place, std::shared_future<std::unique_ptr<paddle::platform::DeviceContext, std::default_delete<paddle::platform::DeviceContext> > >, std::less<paddle::platform::Place>, std::allocator<std::pair<paddle::platform::Place const, std::shared_future<std::unique_ptr<paddle::platform::DeviceContext, std::default_delete<paddle::platform::DeviceContext> > > > > >*, paddle::platform::Place)::{lambda()#1} ()> > >::_M_invoke(std::_Any_data const&)
5   std::_Function_handler<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> (), std::__future_base::_Task_setter<std::unique_ptr<std::__future_base::_Result<std::unique_ptr<paddle::platform::DeviceContext, std::default_delete<paddle::platform::DeviceContext> > >, std::__future_base::_Result_base::_Deleter>, std::unique_ptr<paddle::platform::DeviceContext, std::default_delete<paddle::platform::DeviceContext> > > >::_M_invoke(std::_Any_data const&)
6   std::__future_base::_State_base::_M_do_set(std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> ()>&, bool&)
7   std::__future_base::_Deferred_state<std::_Bind_simple<paddle::platform::EmplaceDeviceContext<paddle::platform::CUDADeviceContext, paddle::platform::CUDAPlace>(std::map<paddle::platform::Place, std::shared_future<std::unique_ptr<paddle::platform::DeviceContext, std::default_delete<paddle::platform::DeviceContext> > >, std::less<paddle::platform::Place>, std::allocator<std::pair<paddle::platform::Place const, std::shared_future<std::unique_ptr<paddle::platform::DeviceContext, std::default_delete<paddle::platform::DeviceContext> > > > > >*, paddle::platform::Place)::{lambda()#1} ()>, std::unique_ptr<paddle::platform::DeviceContext, std::default_delete<paddle::platform::DeviceContext> > >::_M_run_deferred()
8   paddle::platform::DeviceContextPool::Get(paddle::platform::Place const&)
9   paddle::framework::GarbageCollector::GarbageCollector(paddle::platform::Place const&, unsigned long)
10  paddle::framework::UnsafeFastGPUGarbageCollector::UnsafeFastGPUGarbageCollector(paddle::platform::CUDAPlace const&, unsigned long)
11  paddle::framework::Executor::RunPartialPreparedContext(paddle::framework::ExecutorPrepareContext*, paddle::framework::Scope*, long, long, bool, bool, bool)
12  paddle::framework::Executor::RunPreparedContext(paddle::framework::ExecutorPrepareContext*, paddle::framework::Scope*, bool, bool, bool)
13  paddle::framework::Executor::Run(paddle::framework::ProgramDesc const&, paddle::framework::Scope*, int, bool, bool, std::vector<std::string, std::allocator<std::string> > const&, bool, bool)

----------------------
Error Message Summary:
----------------------
Error: Cannot load cudnn shared library. Cannot invoke method cudnnGetVersion at (/paddle/paddle/fluid/platform/dynload/cudnn.cc:63)

**Comment by NameLacker** [comment]
这是cuda和cudnn的版本

+-----------------------------------------------------------------------------+
| NVIDIA-SMI 440.100      Driver Version: 440.100      CUDA Version: 10.2     |
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
GeForce RTX 2080Ti


nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2019 NVIDIA Corporation
Built on Wed_Oct_23_19:24:38_PDT_2019
Cuda compilation tools, release 10.2, V10.2.89

**Comment by GaoWei8** [comment]
可以看出CUDA的版本信息，可以提供cudnnGetVersion的版本信息吗？

**Comment by NameLacker** [comment]
#define&nbsp;CUDNN_MAJOR&nbsp;7
#define&nbsp;CUDNN_MINOR&nbsp;6
#define&nbsp;CUDNN_PATCHLEVEL&nbsp;5
--
#define&nbsp;CUDNN_VERSION&nbsp;(CUDNN_MAJOR&nbsp;*&nbsp;1000&nbsp;+&nbsp;CUDNN_MINOR&nbsp;*&nbsp;100&nbsp;+&nbsp;CUDNN_PATCHLEVEL)


请看一下，谢谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/Paddle"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年8月27日(星期四) 下午4:12
收件人:&nbsp;"PaddlePaddle/Paddle"<Paddle@noreply.github.com&gt;;
抄送:&nbsp;"breathless"<2589432250@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [PaddlePaddle/Paddle] 测试和训练都报这个错 (#26719)





 
可以看出CUDA的版本信息，可以提供cudnnGetVersion的版本信息吗？

**Comment by GaoWei8** [comment]
> #define&nbsp;CUDNN_MAJOR&nbsp;7 #define&nbsp;CUDNN_MINOR&nbsp;6 #define&nbsp;CUDNN_PATCHLEVEL&nbsp;5 -- #define&nbsp;CUDNN_VERSION&nbsp;(CUDNN_MAJOR&nbsp;*&nbsp;1000&nbsp;+&nbsp;CUDNN_MINOR&nbsp;*&nbsp;100&nbsp;+&nbsp;CUDNN_PATCHLEVEL) 请看一下，谢谢
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "PaddlePaddle/Paddle" <notifications@github.com&gt;; 发送时间:&nbsp;2020年8月27日(星期四) 下午4:12 收件人:&nbsp;"PaddlePaddle/Paddle"<Paddle@noreply.github.com&gt;; 抄送:&nbsp;"breathless"<2589432250@qq.com&gt;;"Author"<author@noreply.github.com&gt;; 主题:&nbsp;Re: [PaddlePaddle/Paddle] 测试和训练都报这个错 (#26719) 可以看出CUDA的版本信息，可以提供cudnnGetVersion的版本信息吗？ — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

抱歉。想问的是cudnn的版本信息。

**Comment by NameLacker** [comment]
显示的就是7.6.5呀






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/Paddle"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年8月27日(星期四) 下午4:32
收件人:&nbsp;"PaddlePaddle/Paddle"<Paddle@noreply.github.com&gt;;
抄送:&nbsp;"breathless"<2589432250@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [PaddlePaddle/Paddle] 测试和训练都报这个错 (#26719)





  
#define&nbsp;CUDNN_MAJOR&nbsp;7 #define&nbsp;CUDNN_MINOR&nbsp;6 #define&nbsp;CUDNN_PATCHLEVEL&nbsp;5 -- #define&nbsp;CUDNN_VERSION&nbsp;(CUDNN_MAJOR&nbsp;&nbsp;1000&nbsp;+&nbsp;CUDNN_MINOR&nbsp;&nbsp;100&nbsp;+&nbsp;CUDNN_PATCHLEVEL) 请看一下，谢谢
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "PaddlePaddle/Paddle" <notifications@github.com&gt;; 发送时间:&nbsp;2020年8月27日(星期四) 下午4:12 收件人:&nbsp;"PaddlePaddle/Paddle"<Paddle@noreply.github.com&gt;; 抄送:&nbsp;"breathless"<2589432250@qq.com&gt;;"Author"<author@noreply.github.com&gt;; 主题:&nbsp;Re: [PaddlePaddle/Paddle] 测试和训练都报这个错 (#26719) 可以看出CUDA的版本信息，可以提供cudnnGetVersion的版本信息吗？ — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.
  
抱歉。想问的是cudnn的版本信息。

**Comment by GaoWei8** [comment]
使用export 重新设置到cudnn的位置呢？
或者直接只用官网提供的docker 镜像环境使用paddle

**Comment by NameLacker** [comment]
好的，我试试，谢谢您




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/Paddle"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年8月27日(星期四) 下午4:51
收件人:&nbsp;"PaddlePaddle/Paddle"<Paddle@noreply.github.com&gt;;
抄送:&nbsp;"breathless"<2589432250@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [PaddlePaddle/Paddle] 测试和训练都报这个错 (#26719)





 
使用export 重新设置到cudnn的位置呢？
 或者直接只用官网提供的docker 镜像环境使用paddle
