### ISSUE TITLE
关于Paddle 文档

### ISSUE THREAD

**Issue by zhixuzhichang** [PaddlePaddle/Paddle#26725]
吐槽一下！感觉 Paddle 的文档是给面向开发 Paddle 的人写的！而不是 给 Paddle 的使用者！所以有些地方阅读难度大！再加上使用人群少！找不到其他人的解析进行参考！会降低 Paddle 的使用体验！

**Comment by GaoWei8** [comment]
谢谢建议，会反馈优化文档。
