### ISSUE TITLE
【论文复现】UGATIT相关

### ISSUE THREAD

**Issue by chfhf** [PaddlePaddle/Paddle#26721]
paddle已有API：adaptive_pool2d， reshape， ones_like，zeros_like
                            unsqueeze，concat， create_parameter，L1Loss，MSELoss
                            sqrt， expand，reduce_sum，reduce_mean， transpose
自行定义API：ReflectionPad2D， ReLU， LeakyReLU，Tanh，
                         Upsample,，var， spectral_norm，BCEWithLogitsLoss，RhoClipper
所有API均通过随机数据进行了参数对齐测试，复现过程中谨慎地替换掉所有API名称并保证传参一致，
但是训练的Dloss降到0.0几，Gloss一直高于1400，无法继续下降，不知道问题出在哪，
因为程序跑通了，而且除了conv和linear无法直接对齐外，其余每一个api都进行了参数对齐测试，
所以想问，到底问题会出现在哪，一开始我猜测是网络参数对齐问题，但是测试没找出来，后来又觉得是损失部分问题，但是损失函数定义也是对齐的，过程也是一致的，
优化器的list是parameter()直接相加，先backword()，再minimize()，再optim.clear_gradients
当不进行预处理transforms，图片传入参数也是对齐的，实在找不到还有可能问题出在哪里，平台版本一直是1.8.3运行。
项目地址：
https://aistudio.baidu.com/bdvgpu/user/288399/759441/notebooks/759441.ipynb
因为这个问题卡了一周了，仍然无法解决，很多人是因为版本问题，切换后就正常了，我这个一直如此，希望能给个指点，因为损失不正常就终止了运行
![1598500290(1)](https://user-images.githubusercontent.com/19964528/91382185-b3892900-e85b-11ea-9325-c2066ae7ac48.png)

**Comment by GaoWei8** [comment]
可以尝试下固定随机层，用相同的输入，逐层比对输出看看是否哪里有diff。

**Comment by chfhf** [comment]
> 可以尝试下固定随机层，用相同的输入，逐层比对输出看看是否哪里有diff。

观察了优化器parameter()列表，
发现pytorch的生成器有88个，paddle有132个，其中paddle将instance_norm加入优化器列表
        pytorch的判别器有60个，paddle有144个，其中paddle将spectral_norm加入优化器列表
因此怀疑是instance_norm或spectral_norm部分问题，对spectral_norm进行参数测试，把pytorch的conv2D的权值作为paddle的conv2D的权值输入，并经过各自的spectral_norm，发现输出是一致的，
想问是固定随层Conv和Linear吗？
还有就是自己定义的层加入优化器列表会产生什么影响，因为pytorch对instance_norm和spectral_norm的参数并没有optim操作，这里paddle和pytorch区别在哪？

**Comment by GaoWei8** [comment]
Conv, Linear, instance_norm应该是和pyorch对齐的。而且你提到其他人已经解决了这个问题。有没有可能在参数设置，op计算等方向和别的项目对齐一下？

**Comment by chfhf** [comment]
> Conv, Linear, instance_norm应该是和pyorch对齐的。而且你提到其他人已经解决了这个问题。有没有可能在参数设置，op计算等方向和别的项目对齐一下？

问题已找到，在于自定义Relu以及LeakyRelu的时候inplace设置若为true，set_value造成模型无法收敛，这是paddle的bug，请尽快修复，举例如下：
`class ReLU(Layer):
    def __init__(self, inplace=True):
        super(ReLU, self).__init__()
        self.inplace = inplace

    def forward(self, x):
        if self.inplace:
            x.set_value(relu(x))
            return x
        else:
            y = relu(x)
            return y`
调用ReLU(true)是无法收敛的，LeakyRelu应该也是同理

**Comment by GaoWei8** [comment]
目前op的inplace功能不建议使用，有计划添加功能由框架自动判断是否inplace。

**Comment by ctkindle** [comment]
检查判别器loss，不应该那么低

**Comment by ctkindle** [comment]
单独检查下判别器各部分的loss和logit

**Comment by ctkindle** [comment]
单独检查下判别器各部分的loss和logit

**Comment by ctkindle** [comment]
单独检查下判别器各部分的loss和logit

**Comment by ctkindle** [comment]
单独检查下判别器各部分的loss和logit

**Comment by ctkindle** [comment]
单独检查下判别器各部分的loss和logit
