### ISSUE TITLE
请问 paddle1.5 中 与 pytorch 中的 API scatter_add 等价的 API 是哪一个？

### ISSUE THREAD

**Issue by zhixuzhichang** [PaddlePaddle/Paddle#26724]
有两个和 pytorch中scatter_add类似但又有区别的 API:
paddle.fluid.layers.scatter 的 index 好像只能是1纬。
sequence_scatter 有 input 是3纬的例子吗？文档看的不是太明白。

**Comment by GaoWei8** [comment]
厂内用户，已解决。建议更新文档。

**Comment by guobayang** [comment]
相同的问题，求答案。x和attention_weighted的形状都为(batch_size, seq_len)
`            p_vocab_extended.scatter_add_(dim=1,
                                          index=x,
                                          src=attention_weighted)  `

**Comment by guobayang** [comment]
请教一下，这样的pytorch代码，paddle应该如何处理？x 和 attention_weighted的shape都是(batch_size, seq_len )。
 `    final_distribution = 
            p_vocab_extended.scatter_add_(dim=1,
                                          index=x,
                                          src=attention_weighted)
`

**Comment by ZHANG-GuiGui** [comment]
请问 @guobayang 解决了吗？同问scatter_add_在paddle中的实现。
