### ISSUE TITLE
build error of paddle fluid_inference tag:v1.7.2

### ISSUE THREAD

**Issue by itslgl** [PaddlePaddle/Paddle#26722]
编译 Linux 预测库报错，请帮忙看看什么问题，谢谢

   1）PaddlePaddle版本：Paddle tag:v1.7.2
    2）root@file:/data/share/user/eric/paddle# cat fluid/build/version.txt
GIT COMMIT ID: 92cc33c0e48a98c07a6cf686a22f15bf396fe701
WITH_MKL: OFF
WITH_MKLDNN: OFF
WITH_GPU: OFF

 3）bash build.sh

PADDLE_ROOT=/data/share/user/eric/paddle/fluid/build/
cd Paddle
mkdir build
cd build
/data/share/user/eric/paddle/fluid/cmake/cmake-3.17.1-Linux-x86_64/bin/cmake -DFLUID_INFERENCE_INSTALL_DIR=$PADDLE_ROOT \
      -DCMAKE_BUILD_TYPE=Release \
      -DWITH_PYTHON=OFF \
      -DWITH_MKL=OFF \
      -DWITH_GPU=OFF  \
      -DON_INFER=ON \
      ..
 make
 make inference_lib_dist

4）get below build error
[ 13%] Building CXX object paddle/fluid/framework/CMakeFiles/unused_var_check.dir/unused_var_check.cc.o
/data/share/user/eric/paddle/Paddle/paddle/fluid/framework/unused_var_check.cc: In function ‘void paddle::framework::CheckUnusedVar(const paddle::framework::OperatorBase&, const paddle::framework::Scope&)’:
/data/share/user/eric/paddle/Paddle/paddle/fluid/framework/unused_var_check.cc:88:57: error: converting to ‘std::unordered_set<std::basic_string<char> >’ from initializer list would use explicit constructor ‘std::unordered_set<_Value, _Hash, _Pred, _Alloc>::unordered_set(std::unordered_set<_Value, _Hash, _Pred, _Alloc>::size_type, const hasher&, const key_equal&, const allocator_type&) [with _Value = std::basic_string<char>; _Hash = std::hash<std::basic_string<char> >; _Pred = std::equal_to<std::basic_string<char> >; _Alloc = std::allocator<std::basic_string<char> >; std::unordered_set<_Value, _Hash, _Pred, _Alloc>::size_type = long unsigned int; std::unordered_set<_Value, _Hash, _Pred, _Alloc>::hasher = std::hash<std::basic_string<char> >; std::unordered_set<_Value, _Hash, _Pred, _Alloc>::key_equal = std::equal_to<std::basic_string<char> >; std::unordered_set<_Value, _Hash, _Pred, _Alloc>::allocator_type = std::allocator<std::basic_string<char> >]’
   std::unordered_set<std::string> no_need_buffer_ins = {};
                                                         ^
paddle/fluid/framework/CMakeFiles/unused_var_check.dir/build.make:82: recipe for target 'paddle/fluid/framework/CMakeFiles/unused_var_check.dir/unused_var_check.cc.o' failed
make[3]: *** [paddle/fluid/framework/CMakeFiles/unused_var_check.dir/unused_var_check.cc.o] Error 1
CMakeFiles/Makefile2:5945: recipe for target 'paddle/fluid/framework/CMakeFiles/unused_var_check.dir/all' failed
make[2]: *** [paddle/fluid/framework/CMakeFiles/unused_var_check.dir/all] Error 2
CMakeFiles/Makefile2:2699: recipe for target 'CMakeFiles/inference_lib_dist.dir/rule' failed
make[1]: *** [CMakeFiles/inference_lib_dist.dir/rule] Error 2
Makefile:392: recipe for target 'inference_lib_dist' failed
make: *** [inference_lib_dist] Error 2

**Comment by juncaipeng** [comment]
是否考虑从paddle官网下载paddle预测库。

v1.8.4:https://www.paddlepaddle.org.cn/documentation/docs/zh/advanced_guide/inference_deployment/inference/build_and_install_lib_cn.html

v1.7.2:https://www.paddlepaddle.org.cn/documentation/docs/zh/1.7/advanced_guide/inference_deployment/inference/build_and_install_lib_cn.html

**Comment by itslgl** [comment]
好的，我试试

**Comment by huyutao3550346** [comment]
@juncaipeng hello 我想问下，除了在官网下载预测库的方式，还有什么办法解决这个编译问题嘛？

**Comment by Shixiaowei02** [comment]
您好，参照 [C++ 规范](https://zh.cppreference.com/w/cpp/container/unordered_set/unordered_set)，不同 C++ 标准 `std::unordered_set<T>` 在构造函数细节上有所不同，这导致您使用列表拷贝初始化时的报错随编译器（C++ 标准库）版本变化而变化。

我理解代码的原作者使用显式初始化的初衷是避免临时变量使用随机值，下面的写法在任何支持 C++11 的编译器上都可通过编译：
```
std::unordered_set<std::string> no_need_buffer_ins{};
// 等价于 std::unordered_set<std::string> no_need_buffer_ins;
```

我们内部一般使用的 GCC 版本是  4.8.2 / 8.2.0，这两种编译器会在 Paddle 每次发版本前进行测试，确保兼容。如果您想了解上述报错原因的进一步细节，请参考相关问题 https://stackoverflow.com/questions/26947704

感谢您对 Paddle 的支持！
