### ISSUE TITLE
模型训练报错

### ISSUE THREAD

**Issue by chenmingwei00** [PaddlePaddle/Paddle#26728]
Traceback (most recent call last):
  File "/root/.pycharm_helpers/pydev/pydevd.py", line 1664, in <module>
    main()
  File "/root/.pycharm_helpers/pydev/pydevd.py", line 1658, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/root/.pycharm_helpers/pydev/pydevd.py", line 1068, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/root/.pycharm_helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/root/comprehension/paddle_seq/src/run_classifier.py", line 447, in <module>
    main(args)
  File "/root/comprehension/paddle_seq/src/run_classifier.py", line 134, in main
    use_fp16=args.use_fp16)
  File "/root/comprehension/paddle_seq/src/optimization.py", line 151, in optimization
    _, param_grads = optimizer.minimize(loss)
  File "</root/anaconda3/lib/python3.7/site-packages/decorator.py:decorator-gen-135>", line 2, in minimize
  File "/root/anaconda3/lib/python3.7/site-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
    return wrapped_func(*args, **kwargs)
  File "/root/anaconda3/lib/python3.7/site-packages/paddle/fluid/dygraph/base.py", line 87, in __impl__
    return func(*args, **kwargs)
  File "/root/anaconda3/lib/python3.7/site-packages/paddle/fluid/optimizer.py", line 594, in minimize
    no_grad_set=no_grad_set)
  File "/root/anaconda3/lib/python3.7/site-packages/paddle/fluid/optimizer.py", line 493, in backward
    no_grad_set, callbacks)
  File "/root/anaconda3/lib/python3.7/site-packages/paddle/fluid/backward.py", line 578, in append_backward
    _append_backward_vars_(root_block, fwd_op_num, grad_to_var, grad_info_map)
  File "/root/anaconda3/lib/python3.7/site-packages/paddle/fluid/backward.py", line 392, in _append_backward_vars_
    op_desc.infer_shape(block.desc)
paddle.fluid.core_avx.EnforceNotMet: Input(Out@GRAD) shouldn't be null. at [/paddle/paddle/fluid/operators/reshape_op.cc:370]
PaddlePaddle Call Stacks: 
0       0x7fda2c8e0950p void paddle::platform::EnforceNotMet::Init<char const*>(char const*, char const*, int) + 352
1       0x7fda2c8e0cc9p paddle::platform::EnforceNotMet::EnforceNotMet(std::__exception_ptr::exception_ptr, char const*, int) + 137
2       0x7fda2cf3fb20p paddle::operators::Reshape2GradOp::InferShape(paddle::framework::InferShapeContext*) const + 800
3       0x7fda2ca52b5ep paddle::framework::OpDesc::InferShape(paddle::framework::BlockDesc const&) const + 862
4       0x7fda2c98c61cp
5       0x7fda2c913286p
6       0x557cf233a744p _PyMethodDef_RawFastCallKeywords + 596
7       0x557cf233a861p _PyCFunction_FastCallKeywords + 33
8       0x557cf23a66e8p _PyEval_EvalFrameDefault + 21240
9       0x557cf2339ccbp _PyFunction_FastCallKeywords + 251
10      0x557cf23a1806p _PyEval_EvalFrameDefault + 1046
11      0x557cf22ea539p _PyEval_EvalCodeWithName + 761
12      0x557cf2339ef5p _PyFunction_FastCallKeywords + 805
13      0x557cf23a1806p _PyEval_EvalFrameDefault + 1046
14      0x557cf22ea539p _PyEval_EvalCodeWithName + 761
15      0x557cf2339f57p _PyFunction_FastCallKeywords + 903
16      0x557cf23a28ccp _PyEval_EvalFrameDefault + 5340
17      0x557cf22ea539p _PyEval_EvalCodeWithName + 761
18      0x557cf22eb635p _PyFunction_FastCallDict + 469
19      0x557cf23a3232p _PyEval_EvalFrameDefault + 7746
20      0x557cf22ea81ap _PyEval_EvalCodeWithName + 1498
21      0x557cf22eb635p _PyFunction_FastCallDict + 469
22      0x557cf23a3232p _PyEval_EvalFrameDefault + 7746
23      0x557cf22ea81ap _PyEval_EvalCodeWithName + 1498
24      0x557cf2339f57p _PyFunction_FastCallKeywords + 903
25      0x557cf23a1806p _PyEval_EvalFrameDefault + 1046
26      0x557cf22ea539p _PyEval_EvalCodeWithName + 761
27      0x557cf2339ef5p _PyFunction_FastCallKeywords + 805
28      0x557cf23a1a93p _PyEval_EvalFrameDefault + 1699
29      0x557cf22ea539p _PyEval_EvalCodeWithName + 761
30      0x557cf2339f57p _PyFunction_FastCallKeywords + 903
31      0x557cf23a28ccp _PyEval_EvalFrameDefault + 5340
32      0x557cf2339ccbp _PyFunction_FastCallKeywords + 251
33      0x557cf23a1806p _PyEval_EvalFrameDefault + 1046
34      0x557cf22ea539p _PyEval_EvalCodeWithName + 761
35      0x557cf22eb424p PyEval_EvalCodeEx + 68
36      0x557cf22eb44cp PyEval_EvalCode + 28
37      0x557cf23b0f8dp
38      0x557cf233a5d9p _PyMethodDef_RawFastCallKeywords + 233
39      0x557cf233a861p _PyCFunction_FastCallKeywords + 33
40      0x557cf23a7526p _PyEval_EvalFrameDefault + 24886
41      0x557cf22ea539p _PyEval_EvalCodeWithName + 761
42      0x557cf2339ef5p _PyFunction_FastCallKeywords + 805
43      0x557cf23a5f29p _PyEval_EvalFrameDefault + 19257
44      0x557cf22ea539p _PyEval_EvalCodeWithName + 761
45      0x557cf2339ef5p _PyFunction_FastCallKeywords + 805
46      0x557cf23a1a93p _PyEval_EvalFrameDefault + 1699
47      0x557cf2339ccbp _PyFunction_FastCallKeywords + 251
48      0x557cf23a1806p _PyEval_EvalFrameDefault + 1046
49      0x557cf22ea539p _PyEval_EvalCodeWithName + 761
50      0x557cf22eb424p PyEval_EvalCodeEx + 68
51      0x557cf22eb44cp PyEval_EvalCode + 28
52      0x557cf2400b74p
53      0x557cf240aeb1p PyRun_FileExFlags + 161
54      0x557cf240b0a3p PyRun_SimpleFileExFlags + 451
55      0x557cf240c195p
56      0x557cf240c2bcp _Py_UnixMain + 60
57      0x7fda6be5b830p __libc_start_main + 240
58      0x557cf23b1062p

**Comment by GaoWei8** [comment]
报错信息显示reshape_op的反向grad为空。
paddle.fluid.core_avx.EnforceNotMet: Input(Out@GRAD) shouldn't be null. at [/paddle/paddle/fluid/operators/reshape_op.cc:370]

**Comment by chenmingwei00** [comment]
> 报错信息显示reshape_op的反向grad为空。
> paddle.fluid.core_avx.EnforceNotMet: Input(Out@GRAD) shouldn't be null. at [/paddle/paddle/fluid/operators/reshape_op.cc:370]

我知道，但是什么原因导致的，
 File "/root/anaconda3/lib/python3.7/site-packages/paddle/fluid/layers/nn.py", line 547, in dynamic_lstm
    'candidate_activation': candidate_activation
  File "/root/comprehension/paddle_seq/src/model/models_lstm.py", line 55, in forward
    forward, cell = fluid.layers.dynamic_lstm(input=forward_proj, size=self.hidden_size * 4, use_peepholes=False)
Enforce failed. Expected lods.size() == 1UL, but received lods.size():0 != 1UL:1.

**Comment by GaoWei8** [comment]
Enforce failed. Expected lods.size() == 1UL, but received lods.size():0 != 1UL:1.

这个报错指输入不是lod的，dynamic_lstm要用lod输入。

**Comment by chenmingwei00** [comment]
> Enforce failed. Expected lods.size() == 1UL, but received lods.size():0 != 1UL:1.
> 
> 这个报错指输入不是lod的，dynamic_lstm要用lod输入。

现在锁定了错误的问题在于
  pyreader = fluid.layers.py_reader(
            capacity=50,
            shapes=[[-1, args.max_seq_len, 1], [-1, args.max_seq_len, 1],
                   [-1, args.max_seq_len, 1], [-1, args.max_seq_len, 1],
                   [-1, args.max_seq_len, 1], [-1,args.paragram_conut,args.paragram_max_len, 1],
                    [-1, 1], [-1, 1]],
            dtypes=[
                'int64', 'int64', 'int64', 'int64', 'float32', 'int64', 'int64', 'int64'
            ],
            lod_levels=[0, 0, 0, 0, 0, 0,0, 0],
            name=task_name + "_" + pyreader_name,
            use_double_buffer=True)
倒数第三个是我自己添加的
 fluid.layers.Print(paragraph)
打印是竟然有非常打的id 
但是我实际feed的最大476
所以报错
Exception: /paddle/paddle/fluid/operators/lookup_table_op.cu:36 Assertion `id < N` failed (received id: 9223372034707292159).
Exception: /paddle/paddle/fluid/operators/lookup_table_op.cu:36 Assertion `id < N` failed (received id: 9223372034707292159).
Exception: /paddle/paddle/fluid/operators/lookup_table_op.cu:36 Assertion `id < N` failed (received id: 9223372034707292159).
Exception: /paddle/paddle/fluid/operators/lookup_table_op.cu:36 Assertion `id < N` failed (received id: 9223372034707292159).
Exception: /paddle/paddle/fluid/operators/lookup_table_op.cu:36 Assertion `id < N` failed (received id: 9223372034707292159).
Exception: /paddle/paddle/fluid/operators/lookup_table_op.cu:36 Assertion `id < N` failed (received id: 9223372034707292159).
Exception: /paddle/paddle/fluid/operators/lookup_table_op.cu:36 Assertion `id < N` failed (received id: 9223372034707292159).
Exception: /paddle/paddle/fluid/operators/lookup_table_op.cu:36 Assertion `id < N` failed (received id: 9223372034707292159).
Exception: /paddle/paddle/fluid/operators/lookup_table_op.cu:36 Assertion `id < N` failed (received id: 9223372034707292159)

**Comment by chenmingwei00** [comment]
更奇怪的是有的数据没问题，有的数据有问题

**Comment by chenmingwei00** [comment]
437,1,1,451,19,1,86,1,1,45,1,13,1,1,401,1,1,50,1,1,1,116,1,1,1,1,13,128,1,1,1,1,193,1,1,6,1,19,1,6,1,38,93,6,1,1,48,1,1,461,1,149,1,1,1,100,13,1,1,92,128,1,6,437,1,1,1,1,1,1,187,327,466,1,4,1,1,6,280,43,2,1,437,1,187,327,466,1,4,1,1,1,1,43,2,1,2,1,4,414,1,1,1,1,43,2,1,1,1,1,1,48,1,1,370,1,48,1,1,401,4,1,1,43,1,38,446,1,47,1,1,1,1,48,7,1,6,1,1,1,1,247,151,366,1,5,138,1,4,4,1,1,2,1,34,1,34,1,4,1,1,1,372,1,1,43,1,34,1,34,1,4,1,437,1,466,13,1,1,372,4,1,1,2,1,372,2,1,1,1,1,1,1,2,434,434,4,1,1,2,1,1,2,1,1,1,1,1,1,2,434,434,4,1,4,1,1,6,281,4,74,8,1,1,437,1,71,1,1,210,48,1,73,139,1,1,1,71,1,48,1,48,1,48,1,73,1,6,1,4,2,1,1,1,1,4,1,1,1,1,2,1,1,1,1,1,1,1,2,1,1,1,1,1,1,1,2,1,1,1,1,4,1,1,1,48,1,1,1,4,1,1,1,2,1,1,1,2,1,2,77,263,1,1,1,2,434,434,4,1,1,1,1,2,1,1,1,2,1,2,77,1,1,1,1,2,434,434,4,1,1,1,2,1,1,1,2,1,2,77,1,1,1,1,2,434,434,4,1,1,1,2,1,1,2,1,1,2,77,1,1,2,434,434,4,1,1,1,2,1,1,2,1,1,2,77,62,1,1,1,2,434,434,4,1,1,1,2,1,1,1,2,1,2,77,1,1,1,1,2,434,434,4,1,1,1,2,1,1,1,2,1,2,77,1,1,2,434,434,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,8,1,2,268,43,1,1,4,270,1,1,1,2,1,2,1,1,2,1,4,1,43,1,1,43,2,1,1,1,1,193,1,1,437,1,48,1,464,1,1,100,13,48,451,1,193,1,48,78,62,1,1,48,1,1,198,13,1,1,466,1,1,4,1,8,1,2,1,43,1,4,1,6,1,78,85,1,45,187,1,48,78,6,38,466,48,78,6,1,1,48,78,6,1,1,48,88,133,19,1,6,4,368,135,1,1,1,13,4,4,1,8,1,

**Comment by GaoWei8** [comment]
你这里读取的是非定长的数据，为什么lod信息设置的都是0呢

**Comment by chenmingwei00** [comment]
一个batch_size,长度不一致，之前看的ernie  fluid.layers.py_reader(设置的lod_levels=[0, 0, 0, 0, 0, 0,0, 0],是这样的
def pad_batch_data(insts,
                   pad_idx=0,
                   return_pos=False,
                   return_input_mask=False,
                   return_max_len=False,
                   return_num_token=False,
                   return_seq_lens=False):
    """
    Pad the instances to the max sequence length in batch, and generate the
    corresponding position data and attention bias.
    """
    return_list = []
    max_len = max(len(inst) for inst in insts)
    # if max_len<256:
    #     print(max_len,'1111111111111111111111111111')
    # Any token included in dict can be used to pad, since the paddings' loss
    # will be masked out by weights and make no effect on parameter gradients.

    inst_data = np.array(
        [inst + list([pad_idx] * (max_len - len(inst))) for inst in insts])
    return_list += [inst_data.astype("int64").reshape([-1, max_len, 1])]

    # position data
    if return_pos:
        inst_pos = np.array([
            list(range(0, len(inst))) + [pad_idx] * (max_len - len(inst))
            for inst in insts
        ])

        return_list += [inst_pos.astype("int64").reshape([-1, max_len, 1])]

    if return_input_mask:
        # This is used to avoid attention on paddings.
        input_mask_data = np.array([[1] * len(inst) + [0] *
                                    (max_len - len(inst)) for inst in insts])
        input_mask_data = np.expand_dims(input_mask_data, axis=-1)
        return_list += [input_mask_data.astype("float32")]

    if return_max_len:
        return_list += [max_len]

    if return_num_token:
        num_token = 0
        for inst in insts:
            num_token += len(inst)
        return_list += [num_token]

    if return_seq_lens:
        seq_lens = np.array([len(inst) for inst in insts])
        return_list += [seq_lens.astype("int64").reshape([-1, 1])]

    return return_list if len(return_list) > 1 else return_list[0]


这个是ernie的一个batch设定的扩充，按他这种，每一个batch的长度也是不定长的都没事的

**Comment by chenmingwei00** [comment]
def pad_batch_content_data(insts,
                   paragram_conut=None,
                   pad_idx=0,
                   return_pos=False,
                   return_input_mask=False,
                   return_max_len=False,
                   return_num_token=False,
                   return_seq_lens=False):
    """
    Pad the instances to the max sequence length in batch, and generate the
    corresponding position data and attention bias.
    insts [ba]
    """
    return_list = []
    lengths_list = []
    paragraph_max_len=paragram_conut
    for inst in insts:
        if len(inst)>paragraph_max_len:
            inst=inst[:paragraph_max_len]
        for temp_seq in inst:
            lengths_list.append(len(temp_seq))
    max_len = max(lengths_list) #所有batch_size最大的句子长度
    # if max_len<256:
    #     print(max_len,'1111111111111111111111111111')
    # Any token included in dict can be used to pad, since the paddings' loss
    # will be masked out by weights and make no effect on parameter gradients.
    inst_data=[]
    for inst in insts:
        temp_inst_data=[]
        for temp_seq in inst:
            temp_inst_data.append(temp_seq + list([pad_idx] * (max_len - len(temp_seq))))
        for k in range(paragraph_max_len-len(inst)):
            temp_inst_data.append([1 for _ in range(max_len)])
        inst_data.append(temp_inst_data)
    inst_data = np.array(inst_data)

    return_list += [inst_data.astype("int64").reshape([-1 , paragraph_max_len, max_len, 1])]

    # position data
    if return_pos:
        inst_pos = np.array([
            list(range(0, len(inst))) + [pad_idx] * (max_len - len(inst))
            for inst in insts
        ])

        return_list += [inst_pos.astype("int64").reshape([-1, max_len, 1])]

    if return_input_mask:
        # This is used to avoid attention on paddings.
        input_mask_data = np.array([[1] * len(inst) + [0] *
                                    (max_len - len(inst)) for inst in insts])
        input_mask_data = np.expand_dims(input_mask_data, axis=-1)
        return_list += [input_mask_data.astype("float32")]

    if return_max_len:
        return_list += [max_len]

    if return_num_token:
        num_token = 0
        for inst in insts:
            num_token += len(inst)
        return_list += [num_token]

    if return_seq_lens:
        seq_lens = np.array([len(inst) for inst in insts])
        return_list += [seq_lens.astype("int64").reshape([-1, 1])]

    return return_list if len(return_list) > 1 else return_list[0]

这是我仿照他写的感觉也没毛病呀

**Comment by chenmingwei00** [comment]
paddle 1.5.1

**Comment by GaoWei8** [comment]
看起来是你修改了load的数据shape格式，所以导致了后面的计算有问题。既然你的计算逻辑没有变，而且是仿照ernie写的。建议到ernie repo下提问issue更有针对性。
https://github.com/PaddlePaddle/ERNIE/issues
