### ISSUE TITLE
InvalidArgumentError: Tensor holds the wrong type, it holds double, but desires to be float.

### ISSUE THREAD

**Issue by xttian** [PaddlePaddle/Paddle#26735]
报错信息：
InvalidArgumentError: Tensor holds the wrong type, it holds double, but desires to be float.
  [Hint: Expected valid == true, but received valid:0 != true:1.] at (/paddle/paddle/fluid/framework/tensor_impl.h:33)
  [operator < cross_entropy > error]

关键代码：
pred_tags = fluid.layers.sigmoid(x=bi_lstm_x)
real_tags = fluid.layers.data(name="real_tags", shape=[_TEXT_LEN, _TAG_DIM], dtype="float32", lod_level=1)
loss = fluid.layers.cross_entropy(input=pred_tags, label=real_tags, soft_label=True)

**Comment by GaoWei8** [comment]
可以看下是不是 real_tags 你定义的类型是float。但是传入的数据的类型是double。

**Comment by xttian** [comment]
> 可以看下是不是 real_tags 你定义的类型是float。但是传入的数据的类型是double。

传入的数据类型指的是numpy数据格式我强制控制一下对吧

**Comment by GaoWei8** [comment]
> > 可以看下是不是 real_tags 你定义的类型是float。但是传入的数据的类型是double。
> 
> 传入的数据类型指的是numpy数据格式我强制控制一下对吧

是的。

**Comment by xttian** [comment]
> > > 可以看下是不是 real_tags 你定义的类型是float。但是传入的数据的类型是double。
> > 
> > 
> > 传入的数据类型指的是numpy数据格式我强制控制一下对吧
> 
> 是的。
