### ISSUE TITLE
模型报错一直没有解决

### ISSUE THREAD

**Issue by chenmingwei00** [PaddlePaddle/Paddle#26756]
Exception: /paddle/paddle/fluid/operators/lookup_table_op.cu:36 Assertion `id < N` failed (received id: 4202603142669781314).
Exception: /paddle/paddle/fluid/operators/lookup_table_op.cu:36 Assertion `id < N` failed (received id: 4202603142669781314).
Exception: /paddle/paddle/fluid/operators/lookup_table_op.cu:36 Assertion `id < N` failed (received id: 4202603142669781314).
Exception: /paddle/paddle/fluid/operators/lookup_table_op.cu:36 Assertion `id < N` failed (received id: 4202603142669781314).
Exception: /paddle/paddle/fluid/operators/lookup_table_op.cu:36 Assertion `id < N` failed (received id: 4202603142669781314).
Exception: /paddle/paddle/fluid/operators/lookup_table_op.cu:36 Assertion `id < N` failed (received id: 4202603142669781314).

**Comment by gfwm2013** [comment]
@chenmingwei00 我看您在[issue#26760](https://github.com/PaddlePaddle/Paddle/issues/26760)中提出了相同的问题，且已经有了回复，麻烦请参考那个issue中的回复。

**Comment by gfwm2013** [comment]
@chenmingwei00 看到您在[issue#26760](https://github.com/PaddlePaddle/Paddle/issues/26760)提出了相同的问题且描述更为详细，为了后续的沟通方便，我们将会以[issue#26760](https://github.com/PaddlePaddle/Paddle/issues/26760)为主，为您提供解答，请知悉。
