### ISSUE TITLE
使用混合精度：AttributeError: 'paddle.fluid.core_avx.VarBase' object has no attribute 'op'

### ISSUE THREAD

**Issue by DrRyanHuang** [PaddlePaddle/Paddle#26753]
Paddlepaddle 1.8.0/1.7.2 都试过，在AI Studio平台

按照官方demo, 混合精度训练最佳实践

只添加了一句代码，出现了: AttributeError: 'paddle.fluid.core_avx.VarBase' object has no attribute 'op'
```python
sgd = SGDOptimizer(learning_rate=1e-3)
# 此处只需要使用fluid.contrib.mixed_precision.decorate将sgd封装成AMP训练所需的
# 优化器mp_sgd，并使用mp_sgd.minimize(avg_loss)代替原来的sgd.minimize(avg_loss)语句即可。
mp_sgd = fluid.contrib.mixed_precision.decorator.decorate(sgd)             # <----------------- 就是它 
mp_sgd.minimize(avg_loss)
```
整体代码在这里(已经公开，可直接打开)：
https://aistudio.baidu.com/aistudio/projectdetail/763655 (update: 2020.08.29 该项目已删除)

**Comment by wzzju** [comment]
Hi，https://www.paddlepaddle.org.cn/documentation/docs/zh/advanced_guide/performance_improving/amp/amp.html 这里的混合精度训练最佳实践是针对静态图的，看了您的代码：
![image](https://user-images.githubusercontent.com/17102274/91547362-60e06780-e956-11ea-9348-fa297842b0ef.png)
您使用的是动态图模型，而针对动态图混合精度训练的功能正在开发中。感谢关注～

**Comment by DrRyanHuang** [comment]
@wzzju 感谢您的回答，再补充一下，PP2.0中可以有动态图版的吗？
