### ISSUE TITLE
模型报错，求解决呀

### ISSUE THREAD

**Issue by chenmingwei00** [PaddlePaddle/Paddle#26760]
陈明威:
if is_classify:
    pyreader = fluid.layers.py_reader(
        capacity=50,
        shapes=[[-1, args.max_seq_len, 1], [-1, args.max_seq_len, 1],
               [-1, args.max_seq_len, 1], [-1, args.max_seq_len, 1],
               [-1, args.max_seq_len, 1], [-1,args.paragram_conut,args.paragram_max_len, 1],
                [-1, 1], [-1, 1]],
        dtypes=[            'int64', 'int64', 'int64', 'int64', 'float32', 'int64', 'int64', 'int64'
        ],
        lod_levels=[0, 0, 0, 0, 0, 1, 0, 0],
        name=task_name + "_" + pyreader_name,
        use_double_buffer=True)

陈明威:
这个是官方提供的代码，我就加了 [-1,args.paragram_conut,args.paragram_max_len, 1]倒数第三个

陈明威:
(src_ids, sent_ids, pos_ids, task_ids, input_mask, paragraph, labels,
 qids) = fluid.layers.read_file(pyreader)

陈明威:
数据处理部分是def _pad_batch_records(self, batch_records,paragram_conut):
    """change data type to model"""
    batch_token_ids = [record.token_ids for record in batch_records]
    batch_text_type_ids = [record.text_type_ids for record in batch_records]
    batch_position_ids = [record.position_ids for record in batch_records]
    batch_labels = [record.label_id for record in batch_records]
    batch_contents_ids = [record.contens_ids for record in batch_records]
    if self.is_classify:
        batch_labels = np.array(batch_labels).astype("int64").reshape([-1, 1])
    elif self.is_regression:
        batch_labels = np.array(batch_labels).astype("float32").reshape([-1, 1])

    if batch_records[0].qid or batch_records[0].qid == 0:
        batch_qids = [record.qid for record in batch_records]
        batch_qids = np.array(batch_qids).astype("int64").reshape([-1, 1])
    else:
        batch_qids = np.array([]).astype("int64").reshape([-1, 1])

    # padding
    padded_token_ids, input_mask = pad_batch_data(
        batch_token_ids, pad_idx=self.pad_id, return_input_mask=True)
    padded_text_type_ids = pad_batch_data(
        batch_text_type_ids, pad_idx=self.pad_id)
    padded_position_ids = pad_batch_data(
        batch_position_ids, pad_idx=self.pad_id)
    padded_contents_ids = pad_batch_content_data(
        batch_contents_ids,paragram_conut=paragram_conut, pad_idx=self.pad_id)
    padded_task_ids = np.ones_like(padded_token_ids, dtype="int64") * self.task_id
    # print( np.max(padded_contents_ids), np.min(padded_contents_ids),'111111111111111111111111')
    if padded_contents_ids.shape[0]<16:
        print(padded_contents_ids.shape,'111111111111111111111111111111111')
    # print(padded_token_ids.shape)
    # if np.max(padded_contents_ids)>500 or np.min(padded_contents_ids)<0:
    #
    #     print('11111111111111111111111111111111111111111111111')
    label_tensor = fluid.LoDTensor()
    label_tensor.set(padded_contents_ids, fluid.CPUPlace())
    return_list = [        padded_token_ids, padded_text_type_ids, pa

陈明威:
其中padded_contents_ids = pad_batch_content_data(
    batch_contents_ids,paragram_conut=paragram_conut, pad_idx=self.pad_id)

陈明威:
是我添加的，padded_contents_ids 在这个地方最大值也就476，数值类型都是int64

陈明威:
读取用的是train_pyreader.decorate_tensor_provider(train_data_generator)

陈明威:
然后最后读出来的数据竟然id变得很大

陈明威:
Exception: /paddle/paddle/fluid/operators/lookup_table_op.cu:36 Assertion `id < N` failed (received id: 4140473109978529412).
Exception: /paddle/paddle/fluid/operators/lookup_table_op.cu:36 Assertion `id < N` failed (received id: 4140473109978529412).
Exception: /paddle/paddle/fluid/operators/lookup_table_op.cu:36 Assertion `id < N` failed (received id: 4140473109978529412).
Exception: /paddle/paddle/fluid/operators/lookup_table_op.cu:36 Assertion `id < N` failed (received id: 4140473109978529412).
Exception: /paddle/paddle/fluid/operators/lookup_table_op.cu:36 Assertion `id < N` failed (received id: 4140473109978529412).
Exception: /paddle/paddle/fluid/operators/lookup_table_op.cu:36 Assertion `id < N` failed (received id: 4140473109978529412).
Exception: /paddle/paddle/fluid/operators/lookup_table_op.cu:36 Assertion `id < N` failed (received id: 4140473109978529412).
Exception: /paddle/paddle/fluid/operators/lookup_table_op.cu:36 Assertion `id < N` failed (received id: 4140473109978529412).
Exception: /paddle/paddle/fluid/operators/lookup_table_op.cu:36 Assertion `id < N` failed (received id: 4140473109978529412).
Exception: /paddle/paddle/fluid/operators/lookup_table_op.cu:36 Assertion `id < N` failed (received id: 4140473109978529412).
Exception: /paddle/paddle/fluid/operators/lookup_table_op.cu:36 Assertion `id < N` failed (received id: 4140473109978529412).

**Comment by chenmingwei00** [comment]
参考的是百度观点阅读理解代码更改https://aistudio.baidu.com/aistudio/projectdetail/247636

**Comment by chenmingwei00** [comment]
没有人回答呀

**Comment by gfwm2013** [comment]
@chenmingwei00 请问一下，为什么要修改这个shape呢？

**Comment by chenmingwei00** [comment]
> @chenmingwei00 请问一下，为什么要修改这个shape呢？

您指的是哪个shape

**Comment by gfwm2013** [comment]
@chenmingwei00 就是您自己添加的这个shape。
`这个是官方提供的代码，我就加了 [-1,args.paragram_conut,args.paragram_max_len, 1]倒数第三个`

**Comment by chenmingwei00** [comment]
由于我的句子的shape是多个一个维度，我对应给的数据shape与此保持一致，最后我改成了同样的shape，还是这样

**Comment by chenmingwei00** [comment]
4649,2747,97,494,390,505,193,33,215,379,421,1400,16,52,14,3348,85,7,200,943,12043,943,421,1400,4,1690,155,32,66,21,1289,865,4,3348,85,11,1690,865,5,25,29,86,1124,2082,4,526,566,73,16,505,633,39,12043,421,1400,16,52,14,673,3243,7,200,943,4,943,15,32,21,1595,17963,421,1400,2145,673,3243,6306,9822,9781,10,168,37,7289,9938,9498,88,34,5,4,255,10,277,7289,9938,9498,862,91,92,160,69,15,16,332,4,6306,9822,9781,392,718,15,321,65,79,29,5,3516,35,248,12043,6306,9822,9781,134,590,362,37,7289,9938,9498,2019,1041,4,71,40,15,19,150,118,307,4,175,116,6306,9822,9781,414,303,19,68,259,28,241,4,263,62,76,5,6159,647,323,443,454,414,303,17963,530,106,1074,796,17963,4,659,9,263,120,696,205,5,3509,9496,4,263,65,5,104,259,490,273,414,303,571,16,295,985,4160,347,639,42,42,42,6306,9592,9781,134,564,994,390,3516,249,42,249,17963,4720,6316,585,17963,173,152,6306,9822,9781,57,41,9,274,19,469,949,74,8064,9889,11367,469,949,74,3516,12,5,3509,9496,2019,1041,4,7,40,140,1086,113,48,22,71,40,385,2654,285,459,12048,414,303,104,112,4,1433,418,129,1459,12048,48,124,93,490,273,67,91,393,197,132,4,517,132,4,137,1153,4,1239,7,92,450,1196,4,3833,8424,450,1196,4,8286,450,1196,43,78,413,41,985,4160,5,36,717,647,490,273,197,132,14,517,132,77,12048,414,303,2717,91,137,1153,4,161,476,79,82,36,137,1153,129,381,441,776,28,5,4,1478,85,340,9,21,227,645,14,386,161,5,543,16,52,337,579,162,449,66,594,453,29,14,21,227,36,520,245,453,29,4,105,340,9,21,227,1274,1143,4,226,115,297,52,1149,7,27,1010,227,1274,1143,4,588,575,226,1839,794,161,645,5,35,138,168,179,416,840,7,27,136,5,1274,1143,17963,17963,42,208,42,97,36,248,366,22,86,304,259,5,331,161,654,389,35,4,48,938,647,858,295,7,218,92,21,227,807,1143,74,17963,1092,95,20,50,159,359,21,227,126,584,209,91,14,72,91,21,227,304,259,12050,17963,483,1487,21,227,172,196,396,38,250,196,235,66,36,4,29,8,269,144,331,120,21,227,161,645,145,265,13,654,389,35,243,223,538,607,1839,794,21,227,161,645,453,17963,16,718,807,1839,6,2494,1839,14,12,533,1839,453,17963,596,530,27,136,22,28,12050,17963,483,1487,556,517,109,21,227,161,645,473,637,4,571,21,227,131,7,1716,12043,249,42,1092,95,28,779,304,259,5,654,389,35,4,48,938,647,858,295,5,7,218,92,21,227,807,1143,275,378,13,74,235,66,5,1557,183,12050,973,66,5,2891,183,12050,
打印的id已经没问题了

 emb_out = fluid.layers.embedding(
            input=data,
            size=[self._voc_size, self._emb_size],
            dtype=self._emb_dtype,
            param_attr=fluid.ParamAttr(
                name=self._word_emb_name, initializer=self._param_initializer),
            is_sparse=False)
这样就还是报那个错

**Comment by chenmingwei00** [comment]
Tensor[read_file_0.tmp_7]
	shape: [16,256,1,]
	dtype: l
	data: 296,404,139,337,1452,78,374,123,327,1653,856,77,432,195,4,1512,304,777,52,171,709,900,441,108,5,566,399,2831,1199,15,16,332,303,777,8,4,321,65,303,777,8,165,86,91,448,111,41,299,263,806,
fluid.layers.Print(data, message="The content of input layer:")

        emb_out = fluid.layers.embedding(
            input=data,
            size=[self._voc_size, self._emb_size],
            dtype=self._emb_dtype,
            param_attr=fluid.ParamAttr(
                name=self._word_emb_name, initializer=self._param_initializer),
            is_sparse=False)
打印的id都没问题了 paddle 是1.5版本的

**Comment by gfwm2013** [comment]
@chenmingwei00 好的，谢谢，我这边先仔细看一下。

**Comment by chenmingwei00** [comment]
好的您看一下，我再贴一下ernie的代码，这边没报错，但是两个代码应该是一样的

ernie代码：
   # padding id in vocabulary must be set to 0
        fluid.layers.Print(src_ids, message="src_ids The content of input layer:")

        emb_out = fluid.layers.embedding(
            input=src_ids,
            size=[self._voc_size, self._emb_size],
            dtype=self._emb_dtype,
            param_attr=fluid.ParamAttr(
                name=self._word_emb_name, initializer=self._param_initializer),
            is_sparse=False)
src_ids打印结果为：
src_ids The content of input layer:	The place is:CUDAPlace(0)
Tensor[read_file_0.tmp_0]
	shape: [16,140,1,]
	dtype: l
	data: 1,456,537,958,392,28,725,212,1114,2,29,246,11,456,537,958,392,1051,699,157,357,845,556,588,36,


我的代码：
 fluid.layers.Print(data, message="The content of input layer:")

        emb_out = fluid.layers.embedding(
            input=data,
            size=[self._voc_size, self._emb_size],
            dtype=self._emb_dtype,
            param_attr=fluid.ParamAttr(
                name=self._word_emb_name, initializer=self._param_initializer),
            is_sparse=False)
打印结果为：
Tensor[read_file_0.tmp_0]
	shape: [16,140,1,]
	dtype: l
	data: 1,456,537,958,392,28,725,212,1114,2,29,246,11,456,537,958,392,1051,699,157,357,845,556,588,36,201,699,4,16,698,212,29,374,704,32,337,798,12,20,8,119,797,40,725,212,135,214,4,32,51,29,246,

**Comment by chenmingwei00** [comment]
我更改了一部代码，增加了一个lstm，下边的是lstm的代码feed

**Comment by chenmingwei00** [comment]
难道emb_out = fluid.layers.embedding(
        input=data,
        size=[self._voc_size, self._emb_size],
        dtype=self._emb_dtype,
        param_attr=fluid.ParamAttr(
            name=self._word_emb_name, initializer=self._param_initializer),
        is_sparse=False)
这个id最后必须加0？？？？

**Comment by chenmingwei00** [comment]
要不我把代码给您您看看

**Comment by chenmingwei00** [comment]
rnn_out, last_h, last_c = layers.lstm(emb, init_h, init_c, max_len, hidden_size, num_layers, dropout_prob=dropout_prob)
发现应付该试着了的错误，直接只有feed_ding

**Comment by chenmingwei00** [comment]
layers.lstm(ernie.emb_out_paragraph,
    #                                       init_h,
    #                                       init_c,
    #                                       args.max_seq_len,
    #                                       ernie_config['hidden_size'],
    #                                       1,
    #                                       dropout_prob=0.2)
所有的batch_size的seq_length必须是一样的吗

**Comment by gfwm2013** [comment]
@chenmingwei00 看起来像是你的输入数据的shape格式，导致了后面计算的问题。既然你是按照ernie模型的逻辑写的，建议到ernie repo下提issue会得到更加有针对性的回答。当然我这边也会帮你继续看这个问题。

Ernie repo链接：https://github.com/PaddlePaddle/ERNIE/issues

**Comment by Cppowboy** [comment]
我也遇到类似的问题，请问后来解决了吗？
