### ISSUE TITLE
internal error in RPCClient

### ISSUE THREAD

**Issue by AWSWXY** [PaddlePaddle/Paddle#26765]
本地训练无误，集群训练报错如下
![image](https://user-images.githubusercontent.com/18156360/91519058-278f0400-e924-11ea-9604-6288fbdcf14c.png)
任务链接
http://10.87.108.23:8900/fileview.html?path=/home/disk1/normandy/maybach/app-user-20200828013925-20693/

**Comment by MrChengmo** [comment]
请问Paddle版本是什么？可否分享下PaddleCloud任务，debug一下

**Comment by AWSWXY** [comment]
1.6.0   job job-0bb5f48a2168aafb

**Comment by MrChengmo** [comment]
> 1.6.0 job job-0bb5f48a2168aafb

看起来paddle版本有些旧，可以换到最新的1.8.x试一试，另外任务 使用paddlecloud的分享功能 分享给chengmo就可以

**Comment by AWSWXY** [comment]
已经分享

**Comment by MrChengmo** [comment]
> 已经分享

好的~已经克隆你的任务开始尝试复现了。
