### ISSUE TITLE
使用swig_paddle进行预测，指定train_count>1时出现数据丢包问题

### ISSUE THREAD

**Issue by whiskytina** [PaddlePaddle/Paddle#2677]
使用swig_paddle进行多线程预估，在初始化时指定trainer_count=4:
```
swig_paddle.initPaddle("--trainer_count=4")
```
随后，构造长度为N的输入序列，对这个序列进行预测，返回一个结果序列。
但是，输入序列的长度不等于返回结果的序列长度，也就是说数据有丢失的问题。

将trainer_count改为1，则不会出现上面的问题。

**Comment by QiJune** [comment]
前一段时间修复了一个MultiGradientMachine的bug。你可以先更新代码，看看问题是否仍然复现。

**Comment by lcy-seso** [comment]
建议简化场景，如果希望问题得到解决，尽量提供可以复现的例子。否则从这样的描述中，根本无从查起。

**Comment by lcy-seso** [comment]
I close this issue due to inactivity. please feel free to reopen it if more information is available.
