### ISSUE TITLE
[oneDNN] Question on adding optional tensors to ops

### ISSUE THREAD

**Issue by jczaja** [PaddlePaddle/Paddle#26783]
I'm trying to  add 'MidOut' **optional** output to pool2d operator. oneDNN BWD needs indices from FWD to to perform GRAD operation (similar like your op: max_pool2d_with_indices).  This 'MidOut' is needed only for oneDNN data , so I do not want PaddlePaddle users to see that Tensor e.g. ideally not to expose this 'MidOut' in API.

Some changes with Disposable 'MidOut': https://github.com/PaddlePaddle/Paddle/pull/26664 , It does not work with dygraph

Can it be done? If positive tell me how can I create output tensor only for internal usage, that will not be exposed in API ?

**Comment by lidanqing-vv** [comment]
oneDNN 训练的计算过程中需要用到'MidOut'， 但是我们不想把这个Tensor暴露给用户，可以给些建议，如何建立一个内部使用的Tensor吗？

**Comment by donproc** [comment]
可以考虑试试ExecutionContext 内的AllocateTmpTensor方法吗？

**Comment by jczaja** [comment]
@donproc If I create tensor in FWD pool2d op using  ExecutionContext::AllocateTmpTensor() how can I reference this Tensor in grad pool2d op?
