### ISSUE TITLE
[论文复现] 如何构建自己的损失函数

### ISSUE THREAD

**Issue by ParsonsZeng** [PaddlePaddle/Paddle#26789]
Paddle: 1.8.0

我想着使用Paddle复现度量学习中的损失函数

其中一个损失函数的操作是

for i in range(batch_size):
            pos_pair_ = sim_mat[i][labels == labels[i]]         <-----这一步出错了
            pos_pair_ = pos_pair_[pos_pair_ < 1 - epsilon]
            neg_pair_ = sim_mat[i][labels != labels[i]]

            neg_pair = neg_pair_[neg_pair_ + self.margin > min(pos_pair_)]
            pos_pair = pos_pair_[pos_pair_ - self.margin < max(neg_pair_)]

其中labels == labels[i]是一个布尔型数据，用于辨别是否为同一类，
但这里发现Paddle不能像numpy，pytorch那样，使用布尔型来提取数据。。这意味着无法这样提取数据的话，就无法进行后续的损失函数计算了。

**Comment by saxon-zh** [comment]
辛苦 @DannyIsFunny 看下

**Comment by DannyIsFunny** [comment]
你好，当前我们的bool无法作为提取数组的index。 建议可以 加个cast把bool转化成int，然后作为提取数组的index
