### ISSUE TITLE
【论文复现】DataLoader

### ISSUE THREAD

**Issue by liu824** [PaddlePaddle/Paddle#26788]
DataLoader的中文文档有残缺，缺失DataLoader的使用，英文是完整的，英文文档附带的代码有错误，应该是from paddle.fluid.io import Dataset, BatchSampler, DataLoader

![image](https://user-images.githubusercontent.com/55372277/91632492-aa42bc80-ea13-11ea-96d0-7fbb93fcc270.png)

**Comment by liu824** [comment]
import numpy as np
import paddle.fluid as fluid
from paddle.io import Dataset, BatchSampler, DataLoader(错误from paddle.fluid.io import Dataset, BatchSampler, DataLoader)

BATCH_NUM = 20
BATCH_SIZE = 16
EPOCH_NUM = 4

IMAGE_SIZE = 784
CLASS_NUM = 10

USE_GPU = False # whether use GPU to run model

# define a random dataset
class RandomDataset(Dataset):
    def __init__(self, num_samples):
        self.num_samples = num_samples

    def __getitem__(self, idx):
        image = np.random.random([IMAGE_SIZE]).astype('float32')
        label = np.random.randint(0, CLASS_NUM - 1, (1, )).astype('int64')
        return image, label

    def __len__(self):
        return self.num_samples

# get places
places = fluid.cuda_places() if USE_GPU else fluid.cpu_places()

**Comment by saxon-zh** [comment]
非常感谢您的反馈，我们跟进修复一下API文档。

**Comment by liu824** [comment]
使用DataLoader这个报错是为什么
2020-08-29 20:33:37,482-ERROR: DataLoader reader thread raised an exception!
Exception in thread Thread-15:
Traceback (most recent call last):
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 443, in _get_data
    data = self._data_queue.get(timeout=self._timeout)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/multiprocessing/queues.py", line 105, in get
    raise Empty
_queue.Empty

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 397, in _thread_loop
    batch = self._get_data()
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 454, in _get_data
    "pids: {}".format(len(failed_workers), pids))
RuntimeError: DataLoader 1 workers exit unexpectedly, pids: 5418

---------------------------------------------------------------------------EnforceNotMet                             Traceback (most recent call last)<ipython-input-13-1d3054fdd7b8> in <module>
     23 # for i in range(len(dataset)):#测试reader
     24 #     print(dataset[i][0].shape,dataset[i][1])
---> 25 for i, (image, label) in enumerate(loader()):#测试loader
     26             print(image.shape,label)
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dataloader/dataloader_iter.py in __next__(self)
    501 
    502             if in_dygraph_mode():
--> 503                 data = self._reader.read_next_var_list()
    504             else:
    505                 if self._return_list:
EnforceNotMet: 

--------------------------------------------
C++ Call Stacks (More useful to developers):
--------------------------------------------
0   std::string paddle::platform::GetTraceBackString<std::string const&>(std::string const&, char const*, int)
1   paddle::platform::EnforceNotMet::EnforceNotMet(std::string const&, char const*, int)
2   paddle::operators::reader::BlockingQueue<std::vector<paddle::framework::LoDTensor, std::allocator<paddle::framework::LoDTensor> > >::Receive(std::vector<paddle::framework::LoDTensor, std::allocator<paddle::framework::LoDTensor> >*)
3   paddle::operators::reader::PyReader::ReadNext(std::vector<paddle::framework::LoDTensor, std::allocator<paddle::framework::LoDTensor> >*)
4   std::_Function_handler<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> (), std::__future_base::_Task_setter<std::unique_ptr<std::__future_base::_Result<unsigned long>, std::__future_base::_Result_base::_Deleter>, unsigned long> >::_M_invoke(std::_Any_data const&)
5   std::__future_base::_State_base::_M_do_set(std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> ()>&, bool&)
6   ThreadPool::ThreadPool(unsigned long)::{lambda()#1}::operator()() const

----------------------
Error Message Summary:
----------------------
Error: Blocking queue is killed because the data reader raises an exception
  [Hint: Expected killed_ != true, but received killed_:1 == true:1.] at (/paddle/paddle/fluid/operators/reader/blocking_queue.h:141)

**Comment by saxon-zh** [comment]
辛苦 @DannyIsFunny 看下

**Comment by DannyIsFunny** [comment]
你好，已经反馈API作者尽快修复文档

**Comment by DannyIsFunny** [comment]
你先用num_workers=0看下流程有没有问题再开多进程吧，然后/dev/shm下的空间多大，比较小的话把use_shared_memory设成False吧
