### ISSUE TITLE
【论文复现】paddle 实现SVD

### ISSUE THREAD

**Issue by zzz2010** [PaddlePaddle/Paddle#26785]
请问paddle 有无类似torch.svd() 的方法？ 如果没有的话， 有无实现的思路呢？ 谢谢

**Comment by saxon-zh** [comment]
辛苦 @DannyIsFunny 看下

**Comment by DannyIsFunny** [comment]
你好，我们当前没有svd的实现方法

**Comment by saxon-zh** [comment]
@zzz2010 这是在复现哪篇论文

**Comment by zzz2010** [comment]
其实FID的计算用SVD （我想做可微分的FID）， spectralnorm 也用到SVD，很多其他地方（不是这次复现）也用的，希望paddle可以在之后版本实现一下。
