### ISSUE TITLE
fluid.dygraph.LayerList 的PR问题

### ISSUE THREAD

**Issue by DrRyanHuang** [PaddlePaddle/Paddle#26795]
在 `Paddle1.8` 或者 `Paddle2.0`中，都遇到了这个问题，建立一个空的`LayerList`不可以直接`insert`

原因可能是：
```python
assert isinstance(index, int) and \
        0 <= index < len(self._sub_layers), \
        "index should be an integer in range [0, len(self))"
```
在该代码中如果当前LayerList 为空，则会抛出 `AssertError`，则需要重新考虑LayerList 为空的情况，
可以加上`len(self._sub_layers) == 0` 的情况，即：
```python
assert isinstance(index, int) and \
        ((0 <= index < len(self._sub_layers)) or (len(self._sub_layers) == 0)), \
        "index should be an integer in range [0, len(self))"
```

我push到了1.8 https://github.com/PaddlePaddle/Paddle/pull/26793 和 2.0 https://github.com/PaddlePaddle/Paddle/pull/26790 ，都没有通过

**Comment by DannyIsFunny** [comment]
![image](https://user-images.githubusercontent.com/45189361/91655843-78e6f100-eae6-11ea-8bfa-ddf53f90e376.png)
你好报错信息显示是因为有一个单测没有通过

**Comment by DrRyanHuang** [comment]
您好，那这个 `LayerList` 为空时，使用`insert`方法会报错，该怎么解决呢？
我将
```python
assert isinstance(index, int) and \
        0 <= index < len(self._sub_layers), \
        "index should be an integer in range [0, len(self))"
```
改为了
```python
assert isinstance(index, int) and \
        ((0 <= index < len(self._sub_layers)) or (len(self._sub_layers) == 0)), \
        "index should be an integer in range [0, len(self))"
```

**Comment by phlrain** [comment]
按照python array insert的行为，如果index=0，直接把数据放在数组的最开始的位置，直接取消这个限制可能会导致后续的往数组插入数据存在问题

在空的LayerList下，建议先试用 extend接口， insert接口的问题，我们会提一个pr来修复
