### ISSUE TITLE
PR没有回复

### ISSUE THREAD

**Issue by DrRyanHuang** [PaddlePaddle/Paddle#26791]
RD您好！感谢您在百忙之中看到这个issue!

我是个git的新手，我有一次PR都没有被回复，请问是我的姿势不对吗？
您可以帮忙看看吗？

[https://github.com/PaddlePaddle/Paddle/pull/4793](https://github.com/PaddlePaddle/models/pull/4793)

**Comment by DannyIsFunny** [comment]
你好，已经反馈相关作者，会尽快回复

**Comment by ceci3** [comment]
已经approve，等CI过完就可以合入了，感谢您的贡献~ @DrRyanHuang
