### ISSUE TITLE
sparse train的隐层size限制

### ISSUE THREAD

**Issue by backyes** [PaddlePaddle/Paddle#268]
注意到目前spase_update时矩阵的width有如下check，且有TODO注释，请问这个limit是否会去除？

@reyoung  来自内部用户issue
![blob-20161018143728-zufluf](https://cloud.githubusercontent.com/assets/920727/19751939/cddeacc4-9c2b-11e6-8492-007778febb5f.png)

![blob-20161018143708-srgvmn](https://cloud.githubusercontent.com/assets/920727/19752853/e7783068-9c32-11e6-9721-9ef96a731ab8.png)

**Comment by wangkuiyi** [comment]
@backyes “如下check”好像没有贴出来？

**Comment by backyes** [comment]
@wangkuiyi

**Comment by reyoung** [comment]
@backyes 

那个文件的哪一行(给出github的一个连接)，然后需要怎么做？

**Comment by backyes** [comment]
This issue comes from internal user，and you had follow this before. I just copy the issue from internal issue.  
For some user, if hidden size is too small, such as 2, the sparse training fails. You have added //TODO to remove this limitation for sparse training. Then, user just is asking for you plan.

**Comment by reyoung** [comment]
Your picture can be accessed ONLY in baidu internal network. You should change the issue description to reference the github code source.
