### ISSUE TITLE
【论文复现】复现insightface里面的损失函数arcface

### ISSUE THREAD

**Issue by zhudibo** [PaddlePaddle/Paddle#26807]
参考pytorch中的arcface损失，采用paddle进行复现，目前已定义好的类如下，不知这样是否可行?请大佬赐教。

```Python
class Arcface(fluid.dygraph.layers):
    # implementation of additive margin softmax loss in https://arxiv.org/abs/1801.05599
    def __init__(self, embedding_size=512, classnum=51332, s=64., m=0.5):
        super(Arcface, self).__init__()
        self.classnum = classnum
        self.kernel = fluid.Tensor(embedding_size, classnum)
        # initial kernel
        self.kernel.data.uniform_(-1, 1).renorm_(2, 1, 1e-5).mul_(1e5)
        self.m = m  # the margin value, default is 0.5
        self.s = s  # scalar value default is 64, see normface https://arxiv.org/abs/1704.06369
        self.cos_m = math.cos(m)
        self.sin_m = math.sin(m)
        self.mm = self.sin_m * m  # issue 1
        self.threshold = math.cos(math.pi - m)

    def forward(self, embbedings, label):
        # weights norm
        nB = len(embbedings)
        kernel_norm = fluid.layers.l2_normalize(self.kernel, axis=0)
        # cos(theta+m)
        cos_theta = fluid.layers.matmul(embbedings, kernel_norm)
        #         output = torch.mm(embbedings,kernel_norm)
        cos_theta = cos_theta.clamp(-1, 1)  # for numerical stability
        cos_theta_2 = fluid.layers.pow(cos_theta, 2)
        sin_theta_2 = 1 - cos_theta_2
        sin_theta = fluid.layers.sqrt(sin_theta_2)
        cos_theta_m = (cos_theta * self.cos_m - sin_theta * self.sin_m)
        # this condition controls the theta+m should in range [0, pi]
        #      0<=theta+m<=pi
        #     -m<=theta<=pi-m
        cond_v = cos_theta - self.threshold
        cond_mask = cond_v <= 0
        keep_val = (cos_theta - self.mm)  # when theta not in [0,pi], use cosface instead
        cos_theta_m[cond_mask] = keep_val[cond_mask]
        output = cos_theta * 1.0  # a little bit hacky way to prevent in_place operation on cos_theta
        idx_ = fluid.layers.arange(0, nB, dtype='int64')
        output[idx_, label] = cos_theta_m[idx_, label]
        output *= self.s  # scale up in order to make softmax work, first introduced in normface
        return output
```

**Comment by liym27** [comment]
请问您是想咨询，您实现的这个类，是否可以在Paddle框架下正常组网使用吗？或者说只是想看实现逻辑是否正确？
Paddle里的损失函数，一般是直接定义普通函数，可以参考https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/fluid/layers/loss.py

**Comment by zhudibo** [comment]
您好，目前paddle官网关于arcfaceloss的复现还没出现，然后我自己对照pytorch版的arc faceloss在paddle框架上复现arcfaceloss. 但不知道自己使用paddle框架复现的insight face中的arcfaceloss是否符合paddle的语法逻辑以及能否在paddle上面正常运行起来？请大佬给点指导，看下我的demo是否有问题，直接调用这个类能否实现arcfaceloss计算损失。

---原始邮件---
发件人: "liym27"<notifications@github.com&gt;
发送时间: 2020年8月31日(周一) 中午12:17
收件人: "PaddlePaddle/Paddle"<Paddle@noreply.github.com&gt;;
抄送: "zhudibo"<1020286694@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [PaddlePaddle/Paddle] 【论文复现】复现insightface里面的损失函数arcface (#26807)




 
请问您是想咨询，您实现的这个类，是否可以在Paddle框架下正常组网使用吗？或者说只是想看实现逻辑是否正确？

**Comment by zhudibo** [comment]
我实现的这个类在paddle框架上正常组网使用和逻辑这块都想咨询一下，请大佬指点，感谢😊



---原始邮件---
发件人: "liym27"<notifications@github.com&gt;
发送时间: 2020年8月31日(周一) 中午12:17
收件人: "PaddlePaddle/Paddle"<Paddle@noreply.github.com&gt;;
抄送: "zhudibo"<1020286694@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [PaddlePaddle/Paddle] 【论文复现】复现insightface里面的损失函数arcface (#26807)




 
请问您是想咨询，您实现的这个类，是否可以在Paddle框架下正常组网使用吗？或者说只是想看实现逻辑是否正确？

**Comment by liym27** [comment]
你好，可以参考这2个文件中的代码：https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/fluid/layers/loss.py，
https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/nn/layer/loss.py

您的代码，大体结构是没有问题的，类名、变量名可能需要再规范化。同时，运算逻辑是否可以再精简？forward函数中，调用了较多函数。
另外，可以增加单测，验证新增代码是否有问题，单测代码可以参考这个，交叉熵损失的单测文件
https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/fluid/tests/unittests/test_cross_entropy_loss.py

**Comment by liym27** [comment]
感谢您复现该损失函数，欢迎提PR给PaddlePaddle仓库，流程可参考
https://www.paddlepaddle.org.cn/documentation/docs/zh/advanced_guide/addon_development/contribute_code/submit_pr_guide.html
有问题请随时沟通，谢谢

**Comment by zhudibo** [comment]
好的，我先验证一下我的demo是否可行，后期再优化一下demo

**Comment by zhudibo** [comment]
好的，我先验证一下我的demo是否可行，后期再优化一下demo

**Comment by zhudibo** [comment]
好的，我先验证一下我的demo是否可行，后期再优化一下demo

**Comment by zhudibo** [comment]
好的，我先验证一下我的demo是否可行，后期再优化一下。能否成为contributors.&nbsp;

---原始邮件---
发件人: "liym27"<notifications@github.com&gt;
发送时间: 2020年8月31日(周一) 下午3:08
收件人: "PaddlePaddle/Paddle"<Paddle@noreply.github.com&gt;;
抄送: "zhudibo"<1020286694@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [PaddlePaddle/Paddle] 【论文复现】复现insightface里面的损失函数arcface (#26807)




 
你好，可以参考这2个文件中的代码：https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/fluid/layers/loss.py，增加新的损失函数。另外，可以增加单测，验证新增代码是否有问题

**Comment by liym27** [comment]
> 好的，我先验证一下我的demo是否可行，后期再优化一下。

好的


> 能否成为contributors

直接提PR即可
