### ISSUE TITLE
功能建议 数据增强

### ISSUE THREAD

**Issue by yang-collect** [PaddlePaddle/Paddle#26804]
可否考虑如pytorch那样提供一站式解决的数据读取以及数据增强的api?
如 : torchvision的transform的一系列方法以及torch.datasets下的一系列的数据io的方法
目前在paddlex上能看到类似的数据增强api,可否考虑移植至paddle上

**Comment by jiweibo** [comment]
可以考虑直接使用paddlex中的增强api，后续会对此进行考虑，感谢建议

**Comment by yang-collect** [comment]
我是直接pillow读取后copy函数用的,/(ㄒoㄒ)/~~,当然也copy了一部分torchvision的哈( •̀ ω •́ )✧

**Comment by saxon-zh** [comment]
@lemonlife2333 马上发布的2.0 beta版本中会上线所需的数据增强、领域数据集、领域经典模型和模型训练评估等高层API，统一数据加载（dataloader+dataset）方式，欢迎试用哈~
