### ISSUE TITLE
【论文复现】paddle中是否有定义好的Sampler类？

### ISSUE THREAD

**Issue by Rookieaura** [PaddlePaddle/Paddle#26805]
在PyTorch中的 torch.utils.data.sampler 有定义好的 Sampler 类，在自定义 sampler 的时候可以继承。请问在paddle中有这样的类吗？与之类似的，还有Dataset 类 和 DataLoader 类，我在查阅API时其实可以看出来，似乎有预先定义好的这些类，但是似乎在文档中并没有体现。

**Comment by jiweibo** [comment]
目前应该是推荐DataLoader的写法
https://www.paddlepaddle.org.cn/documentation/docs/zh/api_cn/io_cn/DataLoader_cn.html#dataloader

dataset，sampler在DataLoader内部用到了，官网上文档好像还没有更新，可以参考代码注释
https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/fluid/dataloader/sampler.py#L23
https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/fluid/dataloader/dataset.py#L23

**Comment by Rookieaura** [comment]
> 目前应该是推荐DataLoader的写法
> https://www.paddlepaddle.org.cn/documentation/docs/zh/api_cn/io_cn/DataLoader_cn.html#dataloader
> 
> dataset，sampler在DataLoader内部用到了，官网上文档好像还没有更新，可以参考代码注释
> https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/fluid/dataloader/sampler.py#L23
> https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/fluid/dataloader/dataset.py#L23

是的，我也看到了DataLoader内部的定义。不过其中Sampler的定义好像只在develop版本中有，论文复现用的1.8版本并没有定义这个类。我看了下，有定义好的BatchSampler类，在有些情况下似乎也可以替代Sampler类被继承，达到同样效果，不知道我理解的有没有问题？

**Comment by jiweibo** [comment]
> > 目前应该是推荐DataLoader的写法
> > https://www.paddlepaddle.org.cn/documentation/docs/zh/api_cn/io_cn/DataLoader_cn.html#dataloader
> > dataset，sampler在DataLoader内部用到了，官网上文档好像还没有更新，可以参考代码注释
> > https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/fluid/dataloader/sampler.py#L23
> > https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/fluid/dataloader/dataset.py#L23
> 
> 是的，我也看到了DataLoader内部的定义。不过其中Sampler的定义好像只在develop版本中有，论文复现用的1.8版本并没有定义这个类。我看了下，有定义好的BatchSampler类，在有些情况下似乎也可以替代Sampler类被继承，达到同样效果，不知道我理解的有没有问题？

本月14号，github会建立2.0 beta的tag，之后可以在这个tag上开发。

1.8的版本是有Sampler 在 python/paddle/fluid/dataloader/sampler.py，Sampler的多个子类应该也能达到同样效果

**Comment by Rookieaura** [comment]
> > > 目前应该是推荐DataLoader的写法
> > > https://www.paddlepaddle.org.cn/documentation/docs/zh/api_cn/io_cn/DataLoader_cn.html#dataloader
> > > dataset，sampler在DataLoader内部用到了，官网上文档好像还没有更新，可以参考代码注释
> > > https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/fluid/dataloader/sampler.py#L23
> > > https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/fluid/dataloader/dataset.py#L23
> > 
> > 
> > 是的，我也看到了DataLoader内部的定义。不过其中Sampler的定义好像只在develop版本中有，论文复现用的1.8版本并没有定义这个类。我看了下，有定义好的BatchSampler类，在有些情况下似乎也可以替代Sampler类被继承，达到同样效果，不知道我理解的有没有问题？
> 
> 本月14号，github会建立2.0 beta的tag，之后可以在这个tag上开发。
> 
> 1.8的版本是有Sampler 在 python/paddle/fluid/dataloader/sampler.py，Sampler的多个子类应该也能达到同样效果

谢谢回复，不过 python/paddle/fluid/dataloader/sampler.py 我在release/1.8的branch下我没有找到。其中的BatchSampler在定义时直接继承的基本Object类。且相关子类仅有BatchSampler一种。

**Comment by jiweibo** [comment]
> > > > 目前应该是推荐DataLoader的写法
> > > > https://www.paddlepaddle.org.cn/documentation/docs/zh/api_cn/io_cn/DataLoader_cn.html#dataloader
> > > > dataset，sampler在DataLoader内部用到了，官网上文档好像还没有更新，可以参考代码注释
> > > > https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/fluid/dataloader/sampler.py#L23
> > > > https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/fluid/dataloader/dataset.py#L23
> > > 
> > > 
> > > 是的，我也看到了DataLoader内部的定义。不过其中Sampler的定义好像只在develop版本中有，论文复现用的1.8版本并没有定义这个类。我看了下，有定义好的BatchSampler类，在有些情况下似乎也可以替代Sampler类被继承，达到同样效果，不知道我理解的有没有问题？
> > 
> > 
> > 本月14号，github会建立2.0 beta的tag，之后可以在这个tag上开发。
> > 1.8的版本是有Sampler 在 python/paddle/fluid/dataloader/sampler.py，Sampler的多个子类应该也能达到同样效果
> 
> 谢谢回复，不过 python/paddle/fluid/dataloader/sampler.py 我在release/1.8的branch下我没有找到。其中的BatchSampler在定义时直接继承的基本Object类。且相关子类仅有BatchSampler一种。

不好意思，我应该看成develop分支了，v1.8.4 tag下 目前确实只有batch_sampler一种
