### ISSUE TITLE
add bool support for reshape op

### ISSUE THREAD

**Issue by flishwang** [PaddlePaddle/Paddle#26812]
so that the reshape op can be applied on the results of logical op like <, >, logical_and and logical_or

**Comment by liym27** [comment]
Thank you for your feedback, we will support it later.

**Comment by mapingshuo** [comment]
reshape_op如果支持 bool 类型，需要考虑反向求导的问题，bool类型是没法求导的，需要讨论一下。

**Comment by mapingshuo** [comment]
This PR support bool type for reshape API: https://github.com/PaddlePaddle/Paddle/pull/27944
