### ISSUE TITLE
paddle.v2.layer.scaling 应用后event.cost 无变化

### ISSUE THREAD

**Issue by hw810** [PaddlePaddle/Paddle#2684]
根据 [#136](https://github.com/PaddlePaddle/Paddle/issues/136) 在cost layer 之后用 scaling, 但在训练时的event.cost 没有体现出变化，是否符合预期？

**Comment by QiJune** [comment]
经检查，是用户配置错误导致的。
需要在初始化trainer的时候，传入cost=cost_after_scale，而不是cost=cost
