### ISSUE TITLE
Paddle动态图转静态图后的产出， 不同paddle版本预测结果有diff

### ISSUE THREAD

**Issue by aprilvkuo** [PaddlePaddle/Paddle#26866]
使用 2.0 alpha 版本进行模型转化，并作为基线。

Python端：
1. paddle1.8版本加载后，预测结果和基线相同。
2. paddle1.6版本加载后，预测结果和基线有diff，不符合预期。

C++预测端：
1. c-api1.6版本加载后，预测结果和基线有diff，不符合预期。(预测结果和python端1.6的结果一致)

**Comment by FrostML** [comment]
我整理下目前的进展情况：
TracedLayer 只是简单的记录，跑过的 op。1.8 和 1.6 版本的数据不一样的话，很可能是 op 层面被改了什么。最好的方式仍是升级 Paddle。
