### ISSUE TITLE
issue未被回复

### ISSUE THREAD

**Issue by shenyt-sanshui** [PaddlePaddle/Paddle#26860]
您好，我之前提的一个关于口罩检测在树莓派上实现的issue未被回复，paddlepaddle新手，这几天找了很多资料还是未能解决，可以麻烦您抽空看看吗非常感谢！！https://github.com/PaddlePaddle/Paddle-Lite/issues/4207

**Comment by DannyIsFunny** [comment]
你好，issue已经回复
![image](https://user-images.githubusercontent.com/45189361/91800772-30514400-ec5c-11ea-8ae7-0f2197fd6f57.png)
