### ISSUE TITLE
【Paddle 2.0-alpha】动态图如何指定使用GPU？

### ISSUE THREAD

**Issue by shaunhurryup** [PaddlePaddle/Paddle#26865]
如题。

**Comment by FrostML** [comment]
可以使用这个接口 https://www.paddlepaddle.org.cn/documentation/docs/zh/2.0-alpha/api_cn/dygraph_cn/guard_cn.html ，指定下 place

**Comment by shaunhurryup** [comment]
> 可以使用这个接口 https://www.paddlepaddle.org.cn/documentation/docs/zh/2.0-alpha/api_cn/dygraph_cn/guard_cn.html ，指定下 place

我用这样的代码
`with fluid.dygraph.guard(fluid.CUDAPlace()):`
在AI Studio只要执行就会重启执行器。另外，使用下面的代码也是会重启执行器
`paddle.enable_imperative(paddle.fluid.CUDAPlace(0))`

**Comment by FrostML** [comment]
"重启执行器" 指的是什么，动态图应该没有执行器的概念了

**Comment by shaunhurryup** [comment]
AI Studio平台里执行，notebook的执行器会重启
