### ISSUE TITLE
服务器部署中，客户端调用的url中的网站要如何填

### ISSUE THREAD

**Issue by shenyt-sanshui** [PaddlePaddle/Paddle#26862]
根据paddle官方对服务器部署的教学https://paddlepaddle.org.cn/hubdetail?name=pyramidbox_lite_server_mask&en_category=FaceDetection

我在pc端输入$ hub serving start -m pyramidbox_lite_server_mask

在树莓派端输入
import requests
import json
import cv2
import base64

def cv2_to_base64(image):
    data = cv2.imencode('.jpg', image)[1]
    return base64.b64encode(data.tostring()).decode('utf8')

# 发送HTTP请求
data = {'images':[cv2_to_base64(cv2.imread("/PATH/TO/IMAGE"))]}
headers = {"Content-type": "application/json"}
url = "http://127.0.0.1:8866/predict/pyramidbox_lite_server_mask"
r = requests.post(url=url, headers=headers, data=json.dumps(data))

# 打印预测结果
print(r.json()["results"])

但是返回连接错误，根据别人的解答是我的http://127.0.0.1:8866/predict/pyramidbox_lite_server_mask  中IP地址错了 ，请问我应该使用的是哪个ip地址呢，是我电脑连接的wifi中ipv4地址吗
![image](https://user-images.githubusercontent.com/59388845/91795293-dba7cc00-ec4f-11ea-946a-930ac2a69d71.png)

**Comment by Steffy-zxf** [comment]
你好！使用你机器的ipv4地址。PaddleHub使用问题欢迎在PaddleHub repo下提问：https://github.com/PaddlePaddle/PaddleHub/issues
