### ISSUE TITLE
多卡训练问题

### ISSUE THREAD

**Issue by Rayaction** [PaddlePaddle/Paddle#26867]
ABORT!!! Out of all 2 trainers, the trainer process with rank=[0, 1] was aborted. Please check its log.

**Comment by FrostML** [comment]
请问有更多的 log 么？另外是如何实现的多卡训练呢？

**Comment by chenwhql** [comment]
> ABORT!!! Out of all 2 trainers, the trainer process with rank=[0, 1] was aborted. Please check its log.

这个是launch脚本最后退出时候的提示，麻烦您贴下具体节点的日志

如果您设置了log_dir指定把日志写到磁盘上了，麻烦到磁盘上找下
