### ISSUE TITLE
paddlepaddle运行时报错

### ISSUE THREAD

**Issue by lyn1225** [PaddlePaddle/Paddle#26881]
ValueError: Variable apc1/weights has been created before. the previous shape is (512, 2048, 1, 1); the new shape is (512, 512, 1, 1). They are not matched.
提示这个错误，调试的时候还没有找出原因，哪位大神能提示一下？

**Comment by FrostML** [comment]
名称是 "apc1/weights" 的 Variable 被多次创建，并且多次创建的 shape 不一致
