### ISSUE TITLE
nano上安装paddlepaddle

### ISSUE THREAD

**Issue by shenyt-sanshui** [PaddlePaddle/Paddle#26899]
请问Nona上现在支持直接安装paddlepaddle，还是说像树莓派一样都是不支持的

**Comment by cryoco** [comment]
您好，nano上目前还不支持pip安装，但支持c++预测库的直接安装，可以从[这里](https://www.paddlepaddle.org.cn/documentation/docs/zh/advanced_guide/inference_deployment/inference/build_and_install_lib_cn.html#id1)下载jetson的预测库
