### ISSUE TITLE
很神奇，测试过程中，报我训练文件中的类型错误，不知道应该修改哪里

### ISSUE THREAD

**Issue by xttian** [PaddlePaddle/Paddle#26896]
Paddle 1.7.2

训练文件entity_relation_train.py训练好的模型通过fluid.io.save_inference_model进行存储

测试文件中通过fluid.io.load_inference_model加载模型进行测试，竟然报错信息在我的训练文件中，很神奇，这是paddle的什么机制
![11111](https://user-images.githubusercontent.com/51705668/91922857-90e68c80-ed01-11ea-802c-4a7a4b0777f0.png)

**Comment by cryoco** [comment]
报错是输入应为int64但传入了double，可以检查下输入类型是否正确哈

**Comment by xttian** [comment]
> 报错是输入应为int64但传入了double，可以检查下输入类型是否正确哈

这个是指的我测试过程中传入的数据是错的吗？

**Comment by cryoco** [comment]
> > 报错是输入应为int64但传入了double，可以检查下输入类型是否正确哈
> 
> 这个是指的我测试过程中传入的数据是错的吗？

是的，embedding的输入应为int64类型，可以检查下是否传入了浮点数。

**Comment by xttian** [comment]
> > > 报错是输入应为int64但传入了double，可以检查下输入类型是否正确哈
> > 
> > 
> > 这个是指的我测试过程中传入的数据是错的吗？
> 
> 是的，embedding的输入应为int64类型，可以检查下是否传入了浮点数。

relation_results = executor.run(
            r_program,
            feed={r_feed_target[0]: np.array(input_tokens, dtype='int64'),
                  r_feed_target[1]: np.array(input_subject_tags, dtype='int64'),
                  r_feed_target[2]: np.array(input_object_tags, dtype='int64')},
            fetch_list=r_fetch_targets)[0]

我已经通过上述方式做了强制转换，还是报错。。。

**Comment by cryoco** [comment]
麻烦贴下模型和测试代码吧

**Comment by xttian** [comment]
> 麻烦贴下模型和测试代码吧

能够加qq私聊， 1284545491
