### ISSUE TITLE
【论文复现】module 'paddle' has no attribute 'tensor'

### ISSUE THREAD

**Issue by fly1642** [PaddlePaddle/Paddle#26895]
**运行代码示例：**
import paddle
import paddle.fluid as fluid
import numpy as np
input_3 = np.random.randint(0, 100, [100, ]).astype('int32')
input_4 = np.random.randint(0, 100, [200, ]).astype('int32')
with fluid.dygraph.guard():
    tensor_3 = fluid.dygraph.to_variable(input_3)
    tensor_4 = fluid.dygraph.to_variable(input_4)
    grid_x, grid_y = paddle.tensor.meshgrid([tensor_3, tensor_4])

**报错：**
---------------------------------------------------------------------------AttributeError                            Traceback (most recent call last)<ipython-input-9-d2b313992c1f> in <module>
      7     tensor_3 = fluid.dygraph.to_variable(input_3)
      8     tensor_4 = fluid.dygraph.to_variable(input_4)
----> 9     grid_x, grid_y = paddle.tensor.meshgrid([tensor_3, tensor_4])
     10     # grid_x, grid_y = fluid.layers.meshgrid([tensor_3, tensor_4])
     11     # print(grid_x,grid_y)
AttributeError: module 'paddle' has no attribute 'tensor'

**API文档有错误：**
https://www.paddlepaddle.org.cn/documentation/docs/zh/api_cn/layers_cn/meshgrid_cn.html#meshgrid

**paddle.tensor.meshgrid改为fluid.layers.meshgrid**运行成功

**Comment by cryoco** [comment]
感谢反馈，我们已经反馈对应同学，会对文档进行修正。
