### ISSUE TITLE
2.0-alpha动态图指定GPU就报错

### ISSUE THREAD

**Issue by shaunhurryup** [PaddlePaddle/Paddle#26894]
两种方法指定使用GPU都会出错：自动重启代码执行器
环境：AI Studio高级版

### 第一种
```python
place = fluid.CUDAPlace(0)
paddle.enable_imperative(place)
```

### 第二种
```python
with fluid.dygraph.guard(fluid.CUDAPlace(0)):
```

**Comment by cryoco** [comment]
您好，可以贴下更详细的报错信息吗

**Comment by shaunhurryup** [comment]
> 您好，可以贴下更详细的报错信息吗

他不会报错，但只要执行调用GPU的语句，就会重启notebook的执行器

**Comment by weiexcelpro** [comment]
> 两种方法指定使用GPU都会出错：自动重启代码执行器
> 环境：AI Studio高级版
> 
> ### 第一种
> ```python
> place = fluid.CUDAPlace(0)
> paddle.enable_imperative(place)
> ```
> 
> ### 第二种
> ```python
> with fluid.dygraph.guard(fluid.CUDAPlace(0)):
> ```

现在Paddle 2.0 RC版已经在AIStudio Notebook中集成. 可否用新版本重试一下?
