### ISSUE TITLE
【2.0 windows】AttributeError: module 'paddle.nn' has no attribute 'functioanl'【文档拼写错误】

### ISSUE THREAD

**Issue by R132** [PaddlePaddle/Paddle#26893]
是因为还没集成进去吗？linux版本是否可用？

信息：
Python 3.7.7 (default, May  6 2020, 11:45:54) [MSC v.1916 64 bit (AMD64)] :: Anaconda, Inc. on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import paddle
>>> paddle.nn.functioanl.interpolate
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'paddle.nn' has no attribute 'functioanl'
>>> paddle.__version__
'2.0.0-alpha0'
>>>

破案了，发现是文档的代码有拼写错误
https://www.paddlepaddle.org.cn/documentation/docs/zh/2.0-alpha/api_cn/nn_cn/interpolate_cn.html#inerpolate
functioanl拼写错了

**Comment by cryoco** [comment]
感谢反馈，已反馈相关同学，我们会尽快改正文档
