### ISSUE TITLE
【论文复现】Out of memory error on GPU 0.

### ISSUE THREAD

**Issue by wszzzx** [PaddlePaddle/Paddle#26892]
训练环境：默认的论文复现环境。
问题描述：训练过程中提示 GPU 已满，减小 batch size 也无法解决该问题。重启 ai studio 也无法解决该问题。
报错信息：Out of memory error on GPU 0. Cannot allocate 1.531250GB memory on GPU 0, available memory is only 
                   416.625000MB.

                   Please check whether there is any other process using GPU 0.
                   1. If yes, please stop them, or start PaddlePaddle on another GPU.
                   2. If no, please decrease the batch size of your model.
类似的 issue：类似的 issue 描述说问题基本就是网络中，计算矩阵乘法的问题。但是我将 pytorch 预训练模型转成 paddle 预训练 
                   模型的时候，是可以成功的，我个人认为可以说明参数尺寸都是一 致的，应该可以排除该问题
代码详情：为了便于阅读，我已公开：https://aistudio.baidu.com/aistudio/projectdetail/761399?shared=1

**Comment by wszzzx** [comment]
补充一下，batch size 设置成16后，程序可以跑起来。

**Comment by FrostML** [comment]
一般情况下，超出显存的范围可以确认下卡是否有占用。
batch_size 的大小会影响中间结果的显存占用，减小 batch_size 也是一种解决超显存问题的方式。
