### ISSUE TITLE
多卡自检不通过 paddlepaddle-gpu-1.8.4.post107

### ISSUE THREAD

**Issue by Jeffrey98-AI** [PaddlePaddle/Paddle#26898]
系统：Ubuntu 16.04
GPU：4卡 P100
cudatoolkit=10.0.130
cudnn=7.6.5
---------------------------------------------------------------------------------------------------------------
自检报错信息：
Your Paddle Fluid works well on SINGLE GPU or CPU.
W0902 10:14:18.053751 36696 init.cc:226] Warning: PaddlePaddle catches a failure signal, it may not work properly
W0902 10:14:18.053872 36696 init.cc:228] You could check whether you killed PaddlePaddle thread/process accidentally or report the case to PaddlePaddle
W0902 10:14:18.053881 36696 init.cc:231] The detail failure signal is:

W0902 10:14:18.053891 36696 init.cc:234] *** Aborted at 1599012858 (unix time) try "date -d @1599012858" if you are using GNU date ***
W0902 10:14:18.057443 36696 init.cc:234] PC: @                0x0 (unknown)
W0902 10:14:18.057744 36696 init.cc:234] *** SIGSEGV (@0x0) received by PID 36696 (TID 0x7f518d16b700) from PID 0; stack trace: ***
W0902 10:14:18.060323 36696 init.cc:234]     @     0x7f518cd56390 (unknown)
W0902 10:14:18.062988 36696 init.cc:234]     @                0x0 (unknown)
Segmentation fault (core dumped)

**Comment by cryoco** [comment]
您好，可以确认下您正确安装了nccl2，参考文档

**Comment by cryoco** [comment]
https://www.paddlepaddle.org.cn/documentation/docs/zh/install/install_Ubuntu.html#cpu-gpu

**Comment by Jeffrey98-AI** [comment]
发现直接用 anaconda 官方提供的 cuda cudnn 多卡不能正常运行，不用虚拟环境重新装了NVIDIA官方的 cuda cudnn nccl2 之后多卡正常
