### ISSUE TITLE
fluid.load()接口加载失败

### ISSUE THREAD

**Issue by Haijunlv** [PaddlePaddle/Paddle#26929]
在paddle1.8.3的情况下，训练完成后用fluid.save()保存出一个包含pdmodel, pdopt, pdparms三个文件的checkpoint。
 用这个checkpoint恢复训练时如果自定义好网络结构，再fluid.load(xxx)，加载成功
如果用pdmodel来反序列化出program,再加载fluid.load(xxxx)， 则加载失败。
失败日志:
![image](https://user-images.githubusercontent.com/28926237/91960034-f9525f80-ed3b-11ea-8c6b-04a40f03be2b.png)

单测脚本:

```
import paddle.fluid as fluid
m_dir = 'export_model/'
def read_program(filepath):
    prog = fluid.Program()
    with open(filepath, 'rb') as fin:
        prog = prog.parse_from_string(fin.read())
        return prog
#train_prog = read_program(f'{m_dir}/train.program')
train_prog = read_program(f'{m_dir}/checkpoint/checkpoint.pdmodel')
exe = fluid.Executor(fluid.CPUPlace())

fluid.io.load(train_prog, f'{m_dir}/checkpoint/checkpoint', exe)
```

**Comment by Haijunlv** [comment]
单测脚本:

`import paddle.fluid as fluid
m_dir = 'export_model/'
def read_program(filepath):
prog = fluid.Program()
with open(filepath, 'rb') as fin:
prog = prog.parse_from_string(fin.read())
return prog
#train_prog = read_program(f'{m_dir}/train.program')
train_prog = read_program(f'{m_dir}/checkpoint/checkpoint.pdmodel')
exe = fluid.Executor(fluid.CPUPlace())

fluid.io.load(train_prog, f'{m_dir}/checkpoint/checkpoint', exe)`

**Comment by Haijunlv** [comment]
`import paddle.fluid as fluid
m_dir = 'work_dirs/hub_objectDet/122129_6_pdparms_ssd/export_model/'
def read_program(filepath):
    prog = fluid.Program()
    with open(filepath, 'rb') as fin:
        prog = prog.parse_from_string(fin.read())
        return prog
train_prog = read_program(f'{m_dir}/checkpoint/checkpoint.pdmodel')
exe = fluid.Executor(fluid.CPUPlace())
fluid.io.load(train_prog, f'{m_dir}/checkpoint/checkpoint', exe)`

**Comment by phlrain** [comment]
有没有相应的save的code，这个不太符合预期，需要分析下save的program及相应的code

**Comment by Haijunlv** [comment]
> 有没有相应的save的code，这个不太符合预期，需要分析下save的program及相应的code
用paddledetection的fulid.save和paddleclas的fluild.save 均会报错
![image](https://user-images.githubusercontent.com/28926237/91982280-96bd8b80-ed5c-11ea-9047-fcc5f18aa279.png)

https://github.com/PaddlePaddle/PaddleDetection/blob/8551de92b9c5bd355f1981dc984850fd69caab39/ppdet/utils/checkpoint.py#L200
![image](https://user-images.githubusercontent.com/28926237/91982302-9f15c680-ed5c-11ea-881f-74fd477edd2c.png)

https://github.com/PaddlePaddle/PaddleClas/blob/f14b3f3062a4b5f97026bab321905ac0c9477c35/ppcls/utils/save_load.py#L135

**Comment by chenwhql** [comment]
![image](https://user-images.githubusercontent.com/22561442/92069931-4a666000-eddd-11ea-96cc-a85729912687.png)

这个原理上就不行，模型save的时候，哪些变量是Parameter这个信息会丢失，举个例子

自己写code搭模型，比如有个fc，自己code跑出来的Program里面，fc的weight的类型是Parameter，同时是个persistable变量
但从序列化的program恢复出来的program里，这个fc的weight是个Variable，同时是个persistable变量

然后下面代码中可以看到，一些本来是Parameter但由于转写之后，丢失了这一属性的，会被误识别为optimizer的参数，从而导致这个找不到的问题

![image](https://user-images.githubusercontent.com/22561442/92070145-e4c6a380-eddd-11ea-8810-1dffbb58e9e7.png)
![image](https://user-images.githubusercontent.com/22561442/92070205-02940880-edde-11ea-86ad-a2eee04736d8.png)

但这个信息丢失的问题是个早期的设计包袱，现在出于兼容旧格式的考虑，并不会去Program中增加这个属性，所以这建议换用别的方式

可以试下用load_program_state得到所有变量的dict，再用set_program_dict配置到解析的program中，类似这样

```
import paddle.fluid as fluid
m_dir = 'export_model/'
def read_program(filepath):
    prog = fluid.Program()
    with open(filepath, 'rb') as fin:
        prog = prog.parse_from_string(fin.read())
        return prog
train_prog = read_program(f'{m_dir}/checkpoint/checkpoint.pdmodel')

state_dict = fluid.io.load_program_state(f'{m_dir}/checkpoint/checkpoint')
fluid.io.set_program_dict(train_prog, state_dict)
```
这个的demo我这边没跑，不一定一遍过，您可以先试试

**Comment by Haijunlv** [comment]
![image](https://user-images.githubusercontent.com/28926237/92084540-2107fd00-edfa-11ea-8051-a8ddc84dae9e.png)
![image](https://user-images.githubusercontent.com/28926237/92084549-22392a00-edfa-11ea-9446-807263238058.png)
尝试后还是失败

**Comment by chenwhql** [comment]
那就奇技淫巧吧，先满足当前需求再说

看了下代码，这里的报错是说scope里面没有相关变量，因为正常来讲要跑stratup_program，但这里其实没有startup_program可以跑，所以可以尝试自己创建一个scope，把变量创建进去

例如：

```
import paddle.fluid as fluid
m_dir = 'export_model/'
def read_program(filepath):
    prog = fluid.Program()
    with open(filepath, 'rb') as fin:
        prog = prog.parse_from_string(fin.read())
        return prog
train_prog = read_program(f'{m_dir}/checkpoint/checkpoint.pdmodel')

train_scope = fluid.Scope()
with fluid.scope_guard(train_scope):
    state_dict = fluid.io.load_program_state(f'{m_dir}/checkpoint/checkpoint')
    for var_name in state_dict:
        var = train_scope.var(var_name)
        tensor = var.get_tensor()
        tensor.set(state_dict[var_name], fluid.CPUPlace())
    fluid.io.set_program_dict(train_prog, state_dict)
```

**Comment by chenwhql** [comment]
您好，如果这个后来可用了，麻烦您close下这个问题

**Comment by Haijunlv** [comment]
> 您好，如果这个后来可用了，麻烦您close下这个问题

还在测试中，如果没问题了会及时反馈

**Comment by Haijunlv** [comment]
经实测，效果可用
