### ISSUE TITLE
训练出错 atexit 

### ISSUE THREAD

**Issue by shippingwang** [PaddlePaddle/Paddle#26941]
最新版paddle编译 训练 遇到这个问题
1.8.4未出现

![c68c03e56bada60a54e013b31](https://user-images.githubusercontent.com/13645332/91973121-450e0480-ed4e-11ea-9397-ba9f1b2ed673.png)

**Comment by cryoco** [comment]
您好，develop版本可能不稳定，建议使用release版本进行训练哈
