### ISSUE TITLE
请教如何取出二维Tensor的某一列

### ISSUE THREAD

**Issue by starsblinking** [PaddlePaddle/Paddle#26947]
大小为2的全连接层（即size=2的fluid.layers.fc）的返回值应该是个shape为[-1，2]的Tensor吧?(还是lod_tensor?求解答)
我想取出这个2维tensor的第二列作为预测目标放进save_inference_model的target_vars, 请问如何取出这个第二列呢(得到一个shape为[-1，1]的Tensor)？

**Comment by cryoco** [comment]
> 大小为2的全连接层（即size=2的fluid.layers.fc）的返回值应该是个shape为[-1，2]的Tensor吧?(还是lod_tensor?求解答)

返回的是Tensor或LoDTensor，数据类型与input类型一致。

> 我想取出这个2维tensor的第二列作为预测目标放进save_inference_model的target_vars, 请问如何取出这个第二列呢(得到一个shape为[-1，1]的Tensor)？

可以使用slice，参考https://www.paddlepaddle.org.cn/documentation/docs/zh/api_cn/layers_cn/slice_cn.html#slice

**Comment by starsblinking** [comment]
可以使用，多谢
