### ISSUE TITLE
【论文复现】cudnn不匹配问题

### ISSUE THREAD

**Issue by Rookieaura** [PaddlePaddle/Paddle#26954]
框架版本为1.8.3，查本机cudnn版本为7.6.5，但是在运行程序时会被识别为7.3。
通过 export LD_LIBRARY_PATH=/home/aistudio/cuda/cuda-9.2/lib64:$LD_LIBRARY_PATH 命令无法排除问题。

报错信息如下：
WARNING: device: 0. The installed Paddle is compiled with CUDNN 7.6, but CUDNN version in your machine is 7.3, which may cause serious incompatible bug. Please recompile or reinstall Paddle with compatible CUDNN version.

ExternalError: Cudnn error, CUDNN_STATUS_BAD_PARAM at (/paddle/paddle/fluid/operators/batch_norm_op.cu:319)
[operator < batch_norm > error]

**Comment by juncaipeng** [comment]
可能存在多个版本的cudnn，建议查找、确定一下，然后删除7.3版本的cudnn。
