### ISSUE TITLE
SetCpuMathLibraryNumThreads 咨询

### ISSUE THREAD

**Issue by luotao1** [PaddlePaddle/Paddle#26953]
paddle_api.h里面对这个函数的注释是说"the number of cpu math library threads"。
举个例子：如果我在程序进程中SetCpuMathLibraryNumThreads(8)，然后create了一个predictor, 之后用Clone()函数复制了100个predictor分别放在100个线程里跑，那么此时"the number of cpu math library threads"是8还是800呢？

即MKL线程的设定是否全局？

**Comment by lidanqing-vv** [comment]
这种情况下是800 个，Adam做了测试

**Comment by luotao1** [comment]
多谢，可以写以下你们的实验过程么？

**Comment by lidanqing-vv** [comment]
./paddle/fluid/inference/tests/api/test_analyzer_image_classification --gtest_filter=Analyzer_resnet50.profile_mkldnn --batch_size=32 --warmup --repeat=10 --infer_model=./third_party/inference_demo/resnet50/model --cpu_num_threads=4 --num_threads=2

然后观察 `htop`命令的显示
