### ISSUE TITLE
dataloader支持返回dict数据吗

### ISSUE THREAD

**Issue by WenmuZhou** [PaddlePaddle/Paddle#26960]
我看调用collate_fn之后，最后把数据当list来遍历的
![image](https://user-images.githubusercontent.com/12406017/92064910-24d35980-edd1-11ea-9a8f-43cbdaf1a6e5.png)

**Comment by juncaipeng** [comment]
可以的，你创建Reader生成训练/预测数据时，可以生成不同类型的数据。
具体请参考：https://www.paddlepaddle.org.cn/documentation/docs/zh/advanced_guide/data_preparing/imperative_mode/dataloader_using.html
