### ISSUE TITLE
capi user documents

### ISSUE THREAD

**Issue by fastback407** [PaddlePaddle/Paddle#2697]
Hi guys,

It'll be great help if you could support user documents about capi.

Thanks.

**Comment by hedaoyuan** [comment]
Can this [README.md](https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/capi/examples/model_inference/README.md) help you?

**Comment by fastback407** [comment]
Is there any documents about the apis such as paddle_matrix_create_sparse()?
If I have 2 slot, and 1 is binary, how to combine them, and how to get the predict result?

**Comment by hedaoyuan** [comment]
> Is there any documents about the apis such as paddle_matrix_create_sparse()?

Sorry, there is no document at present, but most api has annotations. [paddle_matrix_create_sparse](https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/capi/matrix.h#L52)

Here is [an example](https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/capi/examples/model_inference/dense/main.c) of how to use capi inference. Where the `./trainer_config.bin` file is converted from the training file by `convert_protobin.sh`.

**Comment by fastback407** [comment]
Thanks, but what does '10' means in this loop:
  printf("Prob: ");
  for (int i = 0; i < 10; ++i) {
    printf("%.2f ", array[i]);
  }
Where could I get it?

**Comment by hedaoyuan** [comment]
The number 10 comes from [here](https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/capi/examples/model_inference/dense/trainer_config.py#L13), is the output size of the trainer_config.py.
And the [trainer_config.bin](https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/capi/examples/model_inference/dense/main.c#L5) in the demo is converted from [trainer_config.py](https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/capi/examples/model_inference/dense/trainer_config.py).

**Comment by fastback407** [comment]
how to config trainer_config.py?

**Comment by hedaoyuan** [comment]
trainer_config.py is the configuration file used for training.
You can refer to the example inside [tutorials](https://github.com/PaddlePaddle/Paddle/tree/develop/doc/tutorials/quick_start).
