### ISSUE TITLE
请问下数据类numpy.ndarray如何转换为paddle.fluid.core_avx.VarBase类呢？

### ISSUE THREAD

**Issue by ymzlygw** [PaddlePaddle/Paddle#26978]
请问下数据类numpy.ndarray如何转换为paddle.fluid.core_avx.VarBase类呢？

**Comment by juncaipeng** [comment]
举例：
x = np.ones([2, 2], np.float32)
tmp = fluid.core.VarBase(value=x, place=fluid.core.CPUPlace())

VarBase是不对外暴露的。

**Comment by ymzlygw** [comment]
> 举例：
> x = np.ones([2, 2], np.float32)
> tmp = fluid.core.VarBase(value=x, place=fluid.core.CPUPlace())
> 
> VarBase是不对外暴露的。

那咋办...想更改程序的某一段代码，但是因为数据类型无法转成paddle.fluid.core_avx.VarBase无法实现

**Comment by ymzlygw** [comment]
> 举例：
> x = np.ones([2, 2], np.float32)
> tmp = fluid.core.VarBase(value=x, place=fluid.core.CPUPlace())
> 
> VarBase是不对外暴露的。

谢谢，转换成功了。
能问下fluid.core_avx.VarBase是一种什么数据类型呢？我起初还以为是像pytorch里的tensor那样，但是我看paddlepaddle是直接使用tensor的。关着VarBase的说明文档也没有找到

**Comment by juncaipeng** [comment]
VarBase和Variable类似。

**Comment by zhiqiu** [comment]
> > 举例：
> > x = np.ones([2, 2], np.float32)
> > tmp = fluid.core.VarBase(value=x, place=fluid.core.CPUPlace())
> > VarBase是不对外暴露的。
> 
> 谢谢，转换成功了。
> 能问下fluid.core_avx.VarBase是一种什么数据类型呢？我起初还以为是像pytorch里的tensor那样，但是我看paddlepaddle是直接使用tensor的。关着VarBase的说明文档也没有找到

直接使用paddle.fluid.dygraph.to_variable(x)即可，参考：https://www.paddlepaddle.org.cn/documentation/docs/zh/api_cn/dygraph_cn/to_variable_cn.html#cn-api-fluid-dygraph-to-variable

**Comment by ymzlygw** [comment]
> > > 举例：
> > > x = np.ones([2, 2], np.float32)
> > > tmp = fluid.core.VarBase(value=x, place=fluid.core.CPUPlace())
> > > VarBase是不对外暴露的。
> > 
> > 
> > 谢谢，转换成功了。
> > 能问下fluid.core_avx.VarBase是一种什么数据类型呢？我起初还以为是像pytorch里的tensor那样，但是我看paddlepaddle是直接使用tensor的。关着VarBase的说明文档也没有找到
> 
> 直接使用paddle.fluid.dygraph.to_variable(x)即可，参考：https://www.paddlepaddle.org.cn/documentation/docs/zh/api_cn/dygraph_cn/to_variable_cn.html#cn-api-fluid-dygraph-to-variable

谢谢，跟上面方法是同样的效果对么
