### ISSUE TITLE
如何使两个 tensor  纬度相等？

### ISSUE THREAD

**Issue by oyxuan-11** [PaddlePaddle/Paddle#26994]
你好，我想让两个tensor 的dim 一致，该如何操作呢？
具体来说，我想让emb_2 的dims 和emb_1 的dims 一致，是[-1, 64] 而不是[-1, -1]，请问改如何实现呢
![image](https://user-images.githubusercontent.com/26322278/92109793-3d1c9600-ee1c-11ea-8564-24c77eb73d31.png)

代码如下+++++++++++++++++++
import numpy as np
import paddle.fluid as fluid
data = fluid.layers.data(name='sequence', shape=[1], dtype='int64', lod_level=1)

emb_1 = fluid.layers.embedding(input=data, size=[128, 64])
print(emb_1)

emb_1_shape = fluid.layers.shape(emb_1)
emb_1_shape.stop_gradient = True
###因为需要做一些操作需要把 embedding 给reshape
tmp = fluid.layers.reshape(x=emb_1, shape=[-1])
emb_2 = fluid.layers.reshape(x=tmp, shape=[emb_1_shape[0], emb_1_shape[1]])
print(emb_2)

**Comment by oyxuan-11** [comment]
emb_1 的第二个维度不是固定的，这里写64 只是为了方便举例

**Comment by juncaipeng** [comment]
reshape都要求输入tensor的维度是固定的，不能存在-1。

**Comment by phlrain** [comment]
这个属于reshape op 没有争取的获取到emb_1_shape[1]的值，所以推导出[-1, -1]的shape，这个问题，我们会尝试修复下
