### ISSUE TITLE
paddle实现的scaled_dot_product_attention有考虑mask的版本吗

### ISSUE THREAD

**Issue by TyrionZK** [PaddlePaddle/Paddle#26993]
阅读源码后发现，注意力实现只有scaled_dot_product_attention函数，paddlepaddle官方能不能开发更多的注意力模块，包括：
1）加上mask的scaled_dot_product_attention
2）完整的多头注意力
3）自注意力实现

**Comment by juncaipeng** [comment]
@TyrionZK  谢谢提供的需求。我们会尽快提供更多注意力实现的api，请期待。
