### ISSUE TITLE
会不会出现类似keras一样的基于paddlepaddle的高层框架？

### ISSUE THREAD

**Issue by Bjoux2** [PaddlePaddle/Paddle#2700]
会不会出现类似keras一样的基于paddlepaddle的高层框架？
paddlepaddle代码写起来还是有点复杂．

**Comment by hedaoyuan** [comment]
Paddle之前重构了API，V2 API要比V1 API描述上简洁一些。你可以看一下这个[V2 API设计](https://github.com/PaddlePaddle/Paddle/blob/develop/doc/design/api.md) ；
[V2 API的文档](http://www.paddlepaddle.org/doc_cn/api/index_cn.html)。
另外，这里有一些基于[V2 API的demo](http://book.paddlepaddle.org/index.cn.html)，你可以看一下是否符合你的期望。
