### ISSUE TITLE
DataParallel模式，单机多卡怎么计算loss或梯度的

### ISSUE THREAD

**Issue by IamMegatron2025** [PaddlePaddle/Paddle#27025]
问题1：
数据并行模式，pytorch的单机多卡训练原理是：

假设读入一个 batch 的数据，其大小为 [30, 5, 2]，假设采用三张 GPUs，其运行过程大致为：

[1] - 将模型放到主 GPU 上，一般为 cuda:0;

[2] - 把模型同步到 3 张 GPUs 上;

[3] - 将总输入 batch 的数据平分为 3 份，这里每一份大小为 [10, 5, 2]；

[4] - 依次分别作为每个副本模型的输入；

[5] - 每个副本模型分别独立进行前向计算，假设为 [4, 5, 2];

[6] - 从 3 个 GPUs 中收集分别计算后的结果，并按照次序拼接，即 [12, 5, 2]，计算 loss;

[7] - 更新梯度.

但是我读paddlepaddle的[文档](https://www.paddlepaddle.org.cn/documentation/docs/zh/1.5/user_guides/howto/training/cluster_howto.html)，上面说在使用GPU训练时，如果每个trainer节点有多个GPU卡，则会先在每个trainer节点的多个卡之间执行NCCL2通信方式的梯度聚合， 这是和我上面写的pytorch的单机多卡训练时每个卡计算网络输出或loss或梯度的方式不同的，是吗？ 

问题2：数据并行模式下，对于paddle的单机多卡训练：当使用paddle.distributed.launch时，是使用多进程进行训练对吧？具体每个进程是负责一张卡和切分的batch数据进行单独训练的吗？然后loss和梯度又是怎么计算的？ 是每个进程单独计算然后单独更新自己卡上的模型参数? 还是每个进程得到网络输出或loss后，把每个进程的输出或loss汇合到一起计算梯度再更新到每个卡呢？

问题3：类似问题2，数据并行模式下：对于paddle的单机多卡训练，当不使用paddle.distributed.launch时，是一个进程负责问题2中的所以事情吗？ batch数据切分到不同卡上，每个卡计算完网络输出或loss, 每个卡单独计算梯度，然后多个卡之间执行NCCL2通信方式的梯度聚合？

希望得到答复。
Thanks

**Comment by chenwhql** [comment]
1. 这个文档讲得是另外一套分布式训练方法，主要针对静态图讲的，而你问的DataParallel是动态图的，这两者之间关联不是特别大，动态图多卡目前文档也不是非常完善，可以参考这个https://www.paddlepaddle.org.cn/documentation/docs/zh/beginners_guide/basic_concept/dygraph/DyGraph.html#id10
这个方式在之后的版本中还会更新

2. 是多进程，batch的切分应该由DataLoader去做，并不是DataParallel来完成的，看下这个例子：https://github.com/PaddlePaddle/models/blob/release/1.8/dygraph/mnist/train.py
目前数据的切分是由distributed_batch_reader来做的，loss和梯度的计算，是每张卡独立计算loss，scale之后计算反向，最后all reduce更新各卡的梯度，看下面几行代码
https://github.com/PaddlePaddle/models/blob/d27cfec8f4033fc72890cd051eef52d593af66ba/dygraph/mnist/train.py#L220

3. 目前发布的1.8版本仅支持使用launch进行单机多卡训练，这里有个区别，paddle的DataParallel对应的是torch的DistributedDataParallel模式，paddle没有torch的单进程多线程DataParallel，因为这种模式性能欠佳，所以paddle没有支持，所以也不存在由一个进程来负责的情况

**Comment by IamMegatron2025** [comment]
@chenwhql 感谢您的回复。

1. paddle的DataParallel默认是动态图的？我看PaddleClas和PaddleDetection的train.py里定义的program都是静态的啊，他们也是DataParallel模式训练吧？怎么解释呢

2. distributed_batch_reader方法是多进程还是多线程呢？ 我看paddle_models/PaddleCV/metric_learning的reader是多线程[xmap_readers](https://github.com/PaddlePaddle/models/blob/release%2F1.8/PaddleCV/metric_learning/reader.py#L191)，还有我看PaddleClas的batch的切分是用多进程[multiprocess_reader](https://github.com/PaddlePaddle/PaddleClas/blob/master/ppcls/data/reader.py#L227)，这两个和您说的distributed_batch_reader有什么区别？哪个更好？
 
3.如果paddle1.8没有单进程多线程DataParallel， 但是我看paddle_models/PaddleCV/metric_learning的训练就是单进程的啊，如果不加paddle.distributed.launch， 也会默认走多进程使用launch进行单机多卡训练吗？

希望给出解释
Thanks.

**Comment by chenwhql** [comment]
1. 之前paddle都是以静态图为主的，program是静态图的概念，现在paddle默认也是静态图模式，后续2.0会逐渐改成动态图默认，相关的模型才会跟进修改，现在应该还是静态图的模型代码，静态图是支持单进程多线程多卡训练的，不是DataParallel，不是一套

2. distributed_batch_reader本身并没有多线程进程什么的，它只是在当前进程只取对应当前rank的数据，是比较粗放的，之后也会被淘汰，会用DataLoader去做，但1.8上还没有这个特性，另外两个接口只是装饰器，用多线程或多进程去加速一个迭代器的数据读取，建议不要使用，属于历史的低效的实现，现在用了后续切换会不方便，答案是都不够好

3. 单进程是静态图

**Comment by chenwhql** [comment]
不太清楚您的需求到底是什么？

**Comment by chenwhql** [comment]
线下进一步沟通已达成一致，主要需求是了解静态图单机多卡训练的执行原理，和前面说的多卡是类似的
