### ISSUE TITLE
关于Numpy类型数据转fluid.core_avx.VarBase数据类型出现的问题

### ISSUE THREAD

**Issue by ymzlygw** [PaddlePaddle/Paddle#27031]
你好，之前我提了issue问关于Numpy如何转换为fluid.core_avx.VarBase类型，十分感谢你的回答@juncaipeng.
但是实际使用中遇见了另一个问题：

the shape experiment mel:(1, 80, 129), type:<class 'numpy.ndarray'>  这是读入的numpy数据的初始size。

re_shape:<class 'paddle.fluid.core_avx.VarBase'>, size(1, 80, 129)   这是我将numpy数据转为VarBase数据的size。

the shape of mel0:type:<class 'paddle.fluid.core_avx.VarBase'> size:[1, 80, XXX] 这是我想要的数据类型,也是模型中能正常进行处理的数据类型，但是是由圆括号包起来的size。

可以看到转换后数据类型已经是同一种fluid. core_avx.VarBase的了，但是唯一的不同就是圆括号（） 和方括号[]，。这方面该怎么处理呢？（1，80，129)圆括号数据输入完全不能得到正确的输出... 如何再将元组转为数组

**Comment by zhangting2020** [comment]
你是怎么转换的呢？你的需求是要把numpy转tensor吗？

**Comment by ymzlygw** [comment]
> 你是怎么转换的呢？你的需求是要把numpy转tensor吗？

不是，numpy转tensor和tensor转numpy已经没问题了，但是转换完了当我看.shape的时候，输出打印结果还是不一样，一个是（1,80,X),一个是[1，80，X]，这个括号的不同不知道为什么。

**Comment by zhangting2020** [comment]
我这边尝试如下代码：
```
import numpy as np
import paddle
paddle.disable_static()
x = np.ones([2, 2], np.float32)
tmp = paddle.to_tensor(x)
print(tmp.shape)
```
结果：
```
[2L, 2L]
```
如果上面的方式没有解决你的问题，可以提供下能复现问题的代码，方便我们解答
