### ISSUE TITLE
paddlepaddle可以实现对抗训练吗

### ISSUE THREAD

**Issue by TyrionZK** [PaddlePaddle/Paddle#27032]
你好，我想问一下，paddlepaddle可以实现对抗训练吗？
其中有两步必须的操作：1）获取预训练模型嵌入层；2）获取反向传播后的梯度值，类似pytorch中的loss.backward()。
谢谢。

**Comment by zhangting2020** [comment]
是可以的，你可以参考下这个repo的实现，https://github.com/PaddlePaddle/PaddleGAN
