### ISSUE TITLE
有可以可视化feature map的工具吗？

### ISSUE THREAD

**Issue by IamMegatron2025** [PaddlePaddle/Paddle#27037]
如题，请问，paddle有可以可视化feature map的工具吗？我现在使用了paddleDetection的gcb(一种attention网络)，想可视化下feature map，看下gcb有没有学到attention的部分。

期待回复，
Thanks

**Comment by zhangting2020** [comment]
这个工具你可以看看是不是能满足你的需求：https://github.com/PaddlePaddle/InterpretDL
