### ISSUE TITLE
【论文复现】Process finished with exit code -1073741819 (0xC0000005)

### ISSUE THREAD

**Issue by R132** [PaddlePaddle/Paddle#27041]
Pycharm Paddle运行和debug时总是报这个错误中断程序。
代码结构为Layer类的嵌套相互引用，run.py调用各个集成的Layer类进行训练。
运行过程中出现上述代码错误（无任何问题描述）
对单个Layer或集成Layer调试可以查找到诸如类型不匹配之类问题。
（已如此解决很多问题）

现在进行反向传播Layer.backward()操作时同样报这个错误终止，使用相同方法调试就更费力了。

请问造成这种异常终止不返回错误信息的原因是什么？和操作系统有关吗？和是否使用显卡有关吗？

    1）PaddlePaddle版本：paddle2.0-alpha-gpu
    2）CPU：
    3）GPU：CUDA10.0和CUDNN7.4
    4）系统环境：Windows10

另外请问造成backward()操作失败的原因可能有哪些？排查了一天没有找到对应问题

**Comment by R132** [comment]
指定CPU运行：place = fluid.CPUPlace()，问题依然存在，Process finished with exit code -1073741819 (0xC0000005)应该与运行设备无关

**Comment by zhangting2020** [comment]
从描述中暂时不能解释是什么问题导致的。请提供一份最小可复现此问题的代码吧

**Comment by zhangting2020** [comment]
由于和issue27061是同一个问题，用户已在issue 27061中给出了更详细的描述，此issue关闭。

**Comment by xiaosunshin** [comment]
我也是Process finished with exit code -1073741819 (0xC0000005)
先训练的部分可以正常，后来就不行了
