### ISSUE TITLE
paddlepaddle里边类似于 keras这种划分模型的操作怎么实现啊

### ISSUE THREAD

**Issue by yuhangT** [PaddlePaddle/Paddle#27043]
subject_model = Model([t1_in, t2_in], [ps1, ps2])
object_model = Model([t1_in, t2_in, k1_in, k2_in], [po1, po2]) 
train_model = Model([t1_in, t2_in, s1_in, s2_in, k1_in, k2_in, o1_in, o2_in],[ps1, ps2, po1, po2])

比如这样，一个大的模型，和训练过程不太一样，在测试的时候我需要一些中间（ps1,ps2）输出用于推理然后再作为object_model的输入

**Comment by zhangting2020** [comment]
静态图可以通过exe.run(feed=feed_dict, fetch=fetch_list)拿到中间结果，中间结果设置在fetch_list中，然后可以feed给你所说的object_model。详细[参考文档](https://www.paddlepaddle.org.cn/documentation/docs/zh/api_cn/executor_cn/Executor_cn.html#run-program-none-feed-none-fetch-list-none-feed-var-name-feed-fetch-var-name-fetch-scope-none-return-numpy-true-use-program-cache-false-use-prune-false)
