### ISSUE TITLE
Paddle 如何对应Keras中的Input, Dense, Model, Lambda？

### ISSUE THREAD

**Issue by snakecy** [PaddlePaddle/Paddle#27048]
如题：

Paddle 如何对应Keras中的Input, Dense, Model, Lambda？

**Comment by zhangting2020** [comment]
2.0版本中会有高层API：https://www.paddlepaddle.org.cn/documentation/docs/zh/2.0-alpha/api_cn/index_cn.html#id1，
其中有上述提到的：Input、Model

如果不使用高层API，对应关系如下
Input：可用data接口
Dense：可用fc接口
Model：无对应
Lambda：无对应

**Comment by snakecy** [comment]
@zhangting2020 感谢回复，没有对应的话，应该有一种实现过程吧？有实例可以参考么？用的paddle是1.7版本的
