### ISSUE TITLE
集群训练网络连接错误

### ISSUE THREAD

**Issue by shenshuijing** [PaddlePaddle/Paddle#2705]
用小数据量， MPI节点设置1个节点， 可以跑成功
但是当把数据量扩大， 并且将MPI设置成50个节点， 就报一下错误
![image](https://user-images.githubusercontent.com/24400858/27783651-9f111830-6009-11e7-846d-b27930d9df4d.png)
，
我已经在脚本中加了以下设置端口的配置--port=7257

**Comment by hedaoyuan** [comment]
之前有一个类似的错误[issue](https://github.com/PaddlePaddle/Paddle/issues/2585#issuecomment-310628246). 检查一下集群上的数据文件？
