### ISSUE TITLE
在flask中使用动态图模式，会卡死

### ISSUE THREAD

**Issue by Costwen** [PaddlePaddle/Paddle#27050]
版本: paddle 1.8.3 cpu

当在flask上将输入转化为tensor 之后 使用 + - * / 等运算会卡死在原地

同时 也不能正常的使用return 

`
    

    @app.route('/selfie2anime',methods = ['POST','GET'])
    
    def face2anime():

    if request.method == 'POST':

        selfie_file = request.files['selfie_file']
        selfie_file.save("ActivitySelfie2anime/selfie_file.jpg")

           with fluid.dygraph.guard():
        genA2B = ResnetGenerator(in_channels=3, out_channels=3, ngf= 64, n_blocks=4)
        genA2B_para, _ = fluid.load_dygraph("ActivitySelfie2anime/Parameters/genA2B124.pdparams")
        genA2B.load_dict(genA2B_para)
        img = np.array(Image.open("ActivitySelfie2anime/selfie_file.jpg").convert("RGB")).astype(np.float32)
        img = cv2.resize(img,(256, 256))
        img = img / 255.
        img = (img - 0.5) / 0.5
        img = totensor(img)

        fakeA2B, _ , _ = genA2B(img)
        fakeA2B = (denorm(tensor2numpy(fakeA2B[0])) * 255).astype(np.uint8)

        fakeA2B = Image.fromarray(fakeA2B)
        fakeA2B.save("ActivitySelfie2anime/anime.jpg")
    anime_image = np.linspace(0,255,256*256*3).reshape(256,256,-1).astype(np.uint8)
    ret,buf = cv2.imencode(".jpg",anime_image)
    anime_image = Image.fromarray(np.uint8(buf)).tobytes()
    resp = make_response(anime_image)
    resp.headers['Anime-Type'] = 'image/jpeg'
    print(resp)
    return resp
`
当使用上述代码时 程序将会一直卡在return 这个地方并且不会返回，并且如果使用tensor去进行+ - / * 运算也会卡死在相对应处

**Comment by zhangting2020** [comment]
return之前的计算步骤都是正常运行的吗？比如make_response这一步执行正常吗？另外，使用tensor去进行+ - / * 运算也会卡死在相对应处，是任意一段测试代码都会出现这个问题，还是说只是在你的项目中会卡住？

**Comment by Costwen** [comment]
> return之前的计算步骤都是正常运行的吗？比如make_response这一步执行正常吗？另外，使用tensor去进行+ - / * 运算也会卡死在相对应处，是任意一段测试代码都会出现这个问题，还是说只是在你的项目中会卡住？

我有试过输出response 发现是正常的200 
之前也试过将处理过程封装为一个函数 发现不管有没有return 只要有了动态图模式的开启 这个函数都不能正常关闭

`

    from flask import Flask,render_template,request,jsonify,make_response
    from PIL import Image
    import base64
    import cv2
    import paddle.fluid as fluid
    import numpy as np
    import matplotlib.pyplot as plt
    app = Flask(__name__)
    @app.route('/',methods = ['GET'])
    def face2anime():
        # with fluid.dygraph.guard():
            # input_tensor = np.ones((1,3,5,5),dtype=np.float32)
            # input_tensor = fluid.dygraph.to_variable(input_tensor)

        return "1"

    if __name__ == '__main__':
        app.run(debug=True)
`
上述代码访问服务器能正常返回1

`

    from flask import Flask,render_template,request,jsonify,make_response
    from PIL import Image
    import base64
    import cv2
    import paddle.fluid as fluid
    import numpy as np
    import matplotlib.pyplot as plt
    app = Flask(__name__)
    @app.route('/',methods = ['GET'])
    def face2anime():
        with fluid.dygraph.guard():
            input_tensor = np.ones((1,3,5,5),dtype=np.float32)
            print(1)
            input_tensor = fluid.dygraph.to_variable(input_tensor)
            print(1)
        return "1"

    if __name__ == '__main__':
        app.run(debug=True)
`

使用上述代码则会发现两个1能在终端正常输出 但是服务器不会返回1
如果将to_variable注释掉 则能正常返回结果

**Comment by zhangting2020** [comment]
这个应该修改为下面的形式，设置zero_copy=False可解决
```
fluid.dygraph.to_variable(input_tensor, zero_copy=False)
```

**Comment by Costwen** [comment]
> 这个应该修改为下面的形式，设置zero_copy=False可解决
> 
> ```
> fluid.dygraph.to_variable(input_tensor, zero_copy=False)
> ```

感谢，成功解决了问题
