### ISSUE TITLE
【论文复现】VIDIOC_REQBUFS: Inappropriate ioctl for device

### ISSUE THREAD

**Issue by liu824** [PaddlePaddle/Paddle#27062]
训练一段时间后突然报错：VIDIOC_REQBUFS: Inappropriate ioctl for device
![image](https://user-images.githubusercontent.com/55372277/92250259-d2438b80-eefd-11ea-8847-f88bcdf83edc.png)

**Comment by MrChengmo** [comment]
这个报错不是来源于PaddlePaddle，可否提供一下打印 `训练集正确率：xxxx，训练集平均：xxxx` 这段文字附近的代码~
