### ISSUE TITLE
【论文复现】生成器loss无法回传

### ISSUE THREAD

**Issue by R132** [PaddlePaddle/Paddle#27061]
kp_source = self.kp_extractor(x['source'])
        kp_driving = self.kp_extractor(x['driving'])
        # kp_source["value"].backward()  # ok on 09042108

        generated = self.generator(x['source'], kp_source=detach_kp(kp_source), kp_driving=detach_kp(kp_driving))
        generated.update({'kp_source': kp_source, 'kp_driving': kp_driving})  # 似乎是dict的操作
        generated["prediction"].backward()

kp_extractor和generator分别是两个网络，
kp_extractor的输出可以backward() ，generator使用kp_extractor的输出作为部分输入，kp_extractor的结果在detach后generator的结果可以回传梯度，但不进行detach操作则不可以（kp_source的回传已注释，没有执行）
这是什么原因呢？要怎么修改？有没有参考程序？

无法看到错误信息，原因如：
https://github.com/PaddlePaddle/Paddle/issues/27041

**Comment by zhangting2020** [comment]
从你上面的描述中，你测试能够正常运行的代码是：调用2次backward，但第二个网络中，将第一个网络的2个输出detach，对吗？

看上去程序出错应该和你调用了2次backward有关，在第一次backward之后，第一个网络的计算图会被释放。但是第一个网络的输出作为另外第二个网络的输入，之后第二次backward会对这两个变量再次求梯度，导致了程序出错。

而使用了detach后，产生了值与kp_source和kp_driving相同的新的变量，并且和第一个网络计算图是分离的，所以能够运行成功。

看你在issue 27041 中使用的版本是paddle2.0-alpha-gpu，这个问题应该可以使用即将发布的2.0beta版本，通过loss.backward(return_graph=True)解决。
