### ISSUE TITLE
tx2上安装编译linux预测库

### ISSUE THREAD

**Issue by shenyt-sanshui** [PaddlePaddle/Paddle#27063]
我想在tx2上安装编译linux的预测库，看官网的教程有点疑问https://www.paddlepaddle.org.cn/documentation/docs/zh/advanced_guide/inference_deployment/inference/build_and_install_lib_cn.html（官网教程）
![image](https://user-images.githubusercontent.com/59388845/92252243-8cd48d80-ef00-11ea-88f1-d44f8c262655.png)
![image](https://user-images.githubusercontent.com/59388845/92252255-91994180-ef00-11ea-90b4-869e022e7182.png)
请问我在tx2上安装与编译预测库的时候，教程上的直接下载安装和从源码编译是独立的吗，意思是如果我直接下载压缩包进行安装的话，是否就不需要下面的从源码编译这个步骤了呢

**Comment by MrChengmo** [comment]
两者相互独立

- 直接下载安装的是基于release版本的预测库，在指定环境下已经编译好直接使用

- 如果有定制化的设备需求 或 修改了预测库代码，则需要重新从源码编译
