### ISSUE TITLE
paddlepaddle-gpu提示版本不对

### ISSUE THREAD

**Issue by shaofeifei11** [PaddlePaddle/Paddle#27077]
使用gpu跑程序时，给出警告：
![image](https://user-images.githubusercontent.com/50863459/92302253-3f5a2e00-ef9d-11ea-88ac-5e513a1539d7.png)

安装的paddle版本：
![image](https://user-images.githubusercontent.com/50863459/92302268-64e73780-ef9d-11ea-97b7-a2e5e8739079.png)

请问，为了去除这个警告，我应该选择哪个版本，谢谢

**Comment by MrChengmo** [comment]
- 这个报错是提示您环境中的cudnn版本不及预期（7.4<7.6），但仅是warning，不影响正常运行

- 上面这个paddle是CPU版本，下面是paddle1.8.4使用Cuda 10， cudnn 7的版本

GPU所需环境可以参考：https://docs.nvidia.com/deeplearning/cudnn/install-guide/#install-linux

**Comment by shaofeifei11** [comment]
好的，谢谢
