### ISSUE TITLE
【论文复现】执行程序总被Killed，有时会还会关掉浏览器出现“内存溢出，请检查相关程序”的提示

### ISSUE THREAD

**Issue by lyj0123** [PaddlePaddle/Paddle#27072]
为使您的问题得到快速解决，在建立Issues前，请您先通过如下方式搜索是否有相似问题:【搜索issue关键字】【使用labels筛选】【官方文档】

如果您没有查询到相似问题，为快速解决您的提问，建立issue时请提供如下细节信息：
- 标题：简洁、精准概括您的问题，例如“Insufficient Memory xxx" ”
- 版本、环境信息：
    1）PaddlePaddle版本：1.8.0
    2）CPU：使用的CPU  基础版，在ResNet3D 作业中执行的代码
    3）GPU：
    4）系统环境：Python 3.7

- 复现信息：复现ResNet3D的论文，出现了  Loss at epoch 0 step 0: [4.912266], acc: [0.]  我认为应该不是网络和数据读取器的问题
- 问题描述：执行程序被  Killed  ，有时会还会关掉浏览器出现“内存溢出，请检查相关程序”的提示，不知道该如何入手解决，没有出现其他报错信息。

![图片](https://user-images.githubusercontent.com/59153814/92299599-3ad64b00-ef86-11ea-9d09-0aaa96f82fd1.png)

**Comment by MrChengmo** [comment]
请问可以提供复现的代码或者环境吗？也可以提供更详细的报错日志

通常执行程序被kill切没有报错是底层错误，可以先将batchsize以及线程数都调整为最小，逐步加大，看能否复现错误

**Comment by lyj0123** [comment]
> 
谢谢您，已经解决了，在群里也问了，然后有人给出了建议：1. 调小batch_size  2. 删除数据增强。  我采用了调小 batch_size 的方法，现在代码已经可以跑通了。谢谢。

**Comment by MrChengmo** [comment]
在运行前使用export GLOG_v=4 ，可以打印更详细的日志

**Comment by lyj0123** [comment]
> 
> 
> 在运行前使用export GLOG_v=4 ，可以打印更详细的日志

群里还有人建议查一下内存占用，我知道在自己笔记本上用任务管理器查看内存的占用情况，请问一下在 aistudio 中的终端中，怎么查看内存占用的情况 ？

**Comment by MrChengmo** [comment]
> > 在运行前使用export GLOG_v=4 ，可以打印更详细的日志
> 
> 群里还有人建议查一下内存占用，我知道在自己笔记本上用任务管理器查看内存的占用情况，请问一下在 aistudio 中的终端中，怎么查看内存占用的情况 ？

另外开一个终端，使用 `top` 命令看各个进程占用的内存
