### ISSUE TITLE
场景文字识别 里面的sequence label怎么生成的。

### ISSUE THREAD

**Issue by tuxming** [PaddlePaddle/Paddle#27073]
模型： https://www.paddlepaddle.org.cn/modelbasedetail/attention
数据准备里面的sequence label是怎么生成的，

我没有看到具体的关于这个sequence label的说明，搜索结果都是sequence labeling的算法，我想这个sequence label和搜索的哪个应该不是一回事吧，不然，这么复杂的，不应该只提一下。。

有知道的人给解释一下吗

**Comment by MrChengmo** [comment]
sequence_label是指这条训练样本中，图片上的各个字符映射到字典的真值，按照从左至右的顺序排列组成的序列化label

在文档中有这样的说明：

<img width="1106" alt="image" src="https://user-images.githubusercontent.com/29789135/92306519-4f383900-efc2-11ea-98e7-ffb1c225361a.png">

**Comment by tuxming** [comment]
![image](https://user-images.githubusercontent.com/3365777/92306724-eea9fb80-efc3-11ea-9dda-ec41bb9332a5.png)
就拿这个来说吧： 80=Q, 67=D，是什么依据，为啥不是90=Q,50=D， 
我第一时间想到的是ascii，但是Q=81，D=68也对应不上。所以他这个根据什么生成的，我一直搞不懂。

**Comment by MrChengmo** [comment]
> ![image](https://user-images.githubusercontent.com/3365777/92306724-eea9fb80-efc3-11ea-9dda-ec41bb9332a5.png)
> 就拿这个来说吧： 80=Q, 67=D，是什么依据，为啥不是90=Q,50=D，
> 我第一时间想到的是ascii，但是Q=81，D=68也对应不上。所以他这个根据什么生成的，我一直搞不懂。

这个是根据自己的数据集来确定的，可以考虑下面这几种情况：

- 训练过程中，涉及到的字符可能并没有ascii码里那么多，使用ascii表来做字典会浪费内存，降低收敛速度。

- 或者，训练数据中的字符，使用ascii的规则无法覆盖到，比如我们将一个词组作为识别的对象

所以这个字典是根据自己的数据集来确定的

**Comment by tuxming** [comment]
意思就是：我可以自己定义： 1=A,2=B,3=C,4=D，是吗？

**Comment by MrChengmo** [comment]
> 意思就是：我可以自己定义： 1=A,2=B,3=C,4=D，是吗？

是的

**Comment by tuxming** [comment]
> > 意思就是：我可以自己定义： 1=A,2=B,3=C,4=D，是吗？
> 
> 是的

谢谢
