### ISSUE TITLE
本地训练时崩溃

### ISSUE THREAD

**Issue by fastback407** [PaddlePaddle/Paddle#2708]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/paddle/trainer/config_parser.py", line 85, in <module>
    from paddle.proto.DataConfig_pb2 import DataConfig
  File "/usr/local/lib/python2.7/dist-packages/paddle/proto/__init__.py", line 15, in <module>
    from paddle.proto.TrainerConfig_pb2 import OptimizationConfig, TrainerConfig
  File "/usr/local/lib/python2.7/dist-packages/paddle/proto/TrainerConfig_pb2.py", line 9, in <module>
    from google.protobuf import symbol_database as _symbol_database
  File "/usr/local/lib/python2.7/dist-packages/google/protobuf/symbol_database.py", line 61, in <module>
    from google.protobuf import descriptor_pool
  File "/usr/local/lib/python2.7/dist-packages/google/protobuf/descriptor_pool.py", line 65, in <module>
    _USE_C_DESCRIPTORS = descriptor._USE_C_DESCRIPTORS  # pylint: disable=protected-access
AttributeError: 'module' object has no attribute '_USE_C_DESCRIPTORS'
F0703 02:52:12.995499  9920 PythonUtil.cpp:186] Check failed: (module) != nullptr Current PYTHONPATH: ['/home/fastback/work/my_training/train/paddle_api_cmd_1_1_0_2/train/local/run_package', '/usr/lib/python2.7', '/usr/lib/python2.7/plat-x86_64-linux-gnu', '/usr/lib/python2.7/lib-tk', '/usr/lib/python2.7/lib-old', '/usr/lib/python2.7/lib-dynload', '/usr/local/lib/python2.7/dist-packages', '/usr/lib/python2.7/dist-packages', '/usr/lib/python2.7/dist-packages/PILcompat', '/usr/lib/python2.7/dist-packages/gtk-2.0', '/usr/lib/python2.7/dist-packages/ubuntu-sso-client']
Python Error: <type 'exceptions.AttributeError'> : 'module' object has no attribute '_USE_C_DESCRIPTORS'
Python Callstack:
            /usr/local/lib/python2.7/dist-packages/paddle/trainer/config_parser.py : 85
            /usr/local/lib/python2.7/dist-packages/paddle/proto/__init__.py : 15
            /usr/local/lib/python2.7/dist-packages/paddle/proto/TrainerConfig_pb2.py : 9
            /usr/local/lib/python2.7/dist-packages/google/protobuf/symbol_database.py : 61
            /usr/local/lib/python2.7/dist-packages/google/protobuf/descriptor_pool.py : 65
Import paddle.trainer.config_parserError
*** Check failure stack trace: ***
    @           0x93ccdd  google::LogMessage::Fail()
    @           0x940825  google::LogMessage::SendToLog()
    @           0x93c803  google::LogMessage::Flush()
    @           0x941d3e  google::LogMessageFatal::~LogMessageFatal()
    @           0x8a2c8b  paddle::py::import()
    @           0x8a2cfe  paddle::callPythonFuncRetPyObj()
    @           0x8a30cc  paddle::callPythonFunc()
    @           0x7c2ed3  paddle::TrainerConfigHelper::TrainerConfigHelper()
    @           0x7c3514  paddle::TrainerConfigHelper::createFromFlags()
    @           0x601fe2  main
    @     0x7f643c815f45  __libc_start_main
    @           0x6110a9  (unknown)
    @              (nil)  (unknown)
在之前版本的训练过程中没有问题，只是用新版的trainer替换了旧版的trainer

**Comment by hedaoyuan** [comment]
> 只是用新版的trainer替换了旧版的trainer

这个替换的是哪几个文件？怎么替换的？

**Comment by fastback407** [comment]
只替换了paddle_trainer，别的都保留了

**Comment by hedaoyuan** [comment]
只替换`paddle_trainer`是不够的，两个版本之间python包相关的文件一般也会有改动的。编译了不同版本的paddle，还是需要通过pip卸载掉之前的版本，重新安装完整的paddle。

**Comment by fastback407** [comment]
配置文件需要改动吗，有没有相关的说明？
另外，预测时会报以下错误：
I0703 19:52:30.068681 15134 Util.cpp:166] commandline:  --use_gpu=False
[libprotobuf ERROR /home/fastback/work/paddle/third_party/protobuf/src/protobuf/src/google/protobuf/message_lite.cc:119] Can't parse message of type "paddle.ModelConfig" because it is missing required fields: type
Invoke paddle error 3
paddle_gradient_machine_create_for_inference(&machine, buf, (int)size)
用的是之前版本的binary_conf，因为是用gen_bin_conf生成的二进制配置文件，所以不知道该怎么改配置来适应新版本。
对于版本变更这种情况，都有哪些地方需要更改呢？

**Comment by hedaoyuan** [comment]
> 配置文件需要改动吗，有没有相关的说明？
> 对于版本变更这种情况，都有哪些地方需要更改呢？

[参考这里](https://github.com/PaddlePaddle/Paddle/blob/develop/doc/getstarted/build_and_install/build_from_source_en.md#build-and-install-1), Build Paddle之后的install步骤是install `wheels/*.whl`，而不是替换paddle_trainer. 配置文件不属于Paddle Build的产出，不需要修改。

**Comment by fastback407** [comment]
之前版本的trainer_config.conf该怎么处理呢
之前版本的预测，需要predict和binary conf，现在版本对这两部分是怎么实现的，要做什么修改？

**Comment by hedaoyuan** [comment]
`之前版本`指的是哪一个版本？`trainer_config.conf`不需要处理。当前版本的预测[参考这里](https://github.com/PaddlePaddle/Paddle/tree/develop/paddle/capi/examples/model_inference)，predict需要参考[例子](https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/capi/examples/model_inference/dense/main.c)写，binary conf参考[Convert configuration file to protobuf binary](https://github.com/PaddlePaddle/Paddle/tree/develop/paddle/capi/examples/model_inference#convert-configuration-file-to-protobuf-binary)这一节。

**Comment by hedaoyuan** [comment]
Closed due to inactivity, please feel free to reopen.
