### ISSUE TITLE
自己设计的网络进行图像分类，无法收敛，loss一直在0.69315，acc一直是0.5左右，检查了很多方面还是找不出问题 #23501

### ISSUE THREAD

**Issue by HeMancute** [PaddlePaddle/Paddle#27096]
如题，改造了ReST-Net模型。在训练WOW隐写算法在0.4bpp嵌入率的时候检测效果有80%左右，还是挺不错的。但是在训练WOW隐写算法在0.2bpp嵌入率的时候的时候，最后的全连接层输出的预测值都是比较小的值，在0附近（下面有图），经过sigmoid函数后的值都在0.5左右。导致acc一直在0.5上下，loss在0.69左右，试过很多网上的方法，都不行。训练集里正反例各一半，训练时，随机读取。lr从0.001开始下降。
![image](https://user-images.githubusercontent.com/29950131/92337330-661e7e80-f0db-11ea-999c-5c92a9b9af21.png)

**Comment by HeMancute** [comment]
求助，感谢各位大佬帮助

**Comment by mapingshuo** [comment]
关于具体模型收敛的问题，我们可能帮不了你，非常抱歉。
