### ISSUE TITLE
Documentation about how to write documentation.

### ISSUE THREAD

**Issue by reyoung** [PaddlePaddle/Paddle#271]
Write a documentation to show:
- How paddle docs are organized.
- How to write `paddle docs`
- How to build `paddle docs` and `preview documentation locally`
- How does `www.paddlepaddle.org` update documentation.

**Comment by reyoung** [comment]
Related to #270 .

**Comment by backyes** [comment]
相关PR已经merged了，所以close这个issue。

**Comment by reyoung** [comment]
其实还没写完。
