### ISSUE TITLE
[discuss] pserver need a DB for saving and read checkpoint?

### ISSUE THREAD

**Issue by dzhwinter** [PaddlePaddle/Paddle#2711]
Do we need a DB to saving and read checkpoint? 
For the checkpoint feature, we need to write it periodically and replace the old checkpoint.  
with a DB:
pros:
- do not need to read/write fs, speed up read/write
- save parameter and training state base key immediately, do not need any manually replace old file operation.

cons:
- more dependencies,  consume resources in backend.
- need to write convert tool if we need the checkpoint file.

here DB refer to key-value database, e.g. `rocksdb`, `leveldb`

**Comment by helinwang** [comment]
> do not need to read/write fs, speed up read/write

DB will not be faster than appending to file: as far as I know, the fastest DB uses [LSM tree](https://en.wikipedia.org/wiki/Log-structured_merge-tree), which is a data structure based on file append. rocksdb and leveldb  both use LSM tree.

> do not need any manually replace old file operation.

This is true.

It seems that we don't have to write too much code for saving to file (within 400 lines of code I guess). I am a little reluctant to add extra dependencies, it's pretty easy to setup in k8s. But for users when don't use k8s and want to use our distributed training, maybe it's too hard to setup.

**Comment by dzhwinter** [comment]
> DB will not be faster than appending to file: as far as I know, the fastest DB for writing uses LSM tree, which is a data structure based on file append. rocksdb and leveldb both use LSM tree.

I never take a look into the data structure in detail, only know that both of them use LSM tree indeed.  
According to your comments,  there will be no benefit in performance gain at all. But it is strange, [`caffe2`](https://github.com/caffe2/caffe2/blob/master/caffe2/python/checkpoint.py#L115) choose DB as checkpoint's backend.  
`caffe2`'s choice not a reason for my statement, I am just curious, since they have so many experiences in caffe1.

**Comment by gongweibao** [comment]
Feel free to reopen it.
