### ISSUE TITLE
请问palm怎么使用已有的模型进行持续训练？

### ISSUE THREAD

**Issue by yeguang1991** [PaddlePaddle/Paddle#27119]
我使用PALM框架训练了一个模型之后，训练样本增加了，请问怎么做到不用重新训练，在原来的模型基础上只训练增加的样本

**Comment by mapingshuo** [comment]
你好，这个问题和PALM无关。你需要先load训练好的模型到内存，然后继续训练就可以了。
load训练好的模型的方法是：在run完startup_program之后，使用load_params接口加载训练好的模型：

https://paddlepaddle.org.cn/documentation/docs/zh/api_cn/io_cn/load_params_cn.html#load-params

**Comment by mapingshuo** [comment]
请参考：https://github.com/PaddlePaddle/models/blob/d27cfec8f4033fc72890cd051eef52d593af66ba/PaddleNLP/pretrain_language_models/BERT/utils/init.py#L54
