### ISSUE TITLE
给1.8.2的gpu镜像新增用户后，通过新用户来启动镜像会报错

### ISSUE THREAD

**Issue by levinxo** [PaddlePaddle/Paddle#27154]
- 版本、环境信息：
    1）PaddlePaddle版本：docker镜像1.8.2-gpu-cuda10.0-cudnn7 以及1.7.1-gpu-cuda10.0-cudnn7
    4）系统环境：centos7的docker环境
- 复现信息：

1. 通过dockerfile或者通过commit方式新增用户并构建新镜像：
`useradd -d /home/newuserxxx -m -g users -s /bin/bash newuserxxx`
2. 通过`docker run -it --rm -u1000:100 new_image bash`进入新镜像实例化的容器，会提示
`bash: /root/.bashrc: Permission denied`。
如下图所示：
![no permission](https://user-images.githubusercontent.com/2005694/92424670-86237000-f1b7-11ea-8fe5-b30ed93a5010.png)
3. 若通过`docker run -it --rm new_image bash`直接进入容器，而不指定用户，默认登录的是root账号。进入容器后再从root账号`su - new_user`是正常的。

**Comment by levinxo** [comment]
根据分析，应该是下面这行代码的问题，没有考虑到可能会使用其他用户
https://github.com/PaddlePaddle/Paddle/blob/develop/tools/dockerfile/Dockerfile.ubuntu#L220

`CMD source ~/.bashrc`

**Comment by tianshuo78520a** [comment]
可能是这个原因导致的，这个使用场景比较小众我们没有测试到，我们先记下后续再进行修改。你可以先在自己本地在dockerfile中删除这句构建试试。

**Comment by levinxo** [comment]
@tianshuo78520a 后来基于cuda10.1镜像来构建，只安装了python3.6，然后用pip来安装paddle-gpu，镜像体积也减少了很多
