### ISSUE TITLE
PaddleClas如何用预训练模型？ （-m参数老是错误）

### ISSUE THREAD

**Issue by Derek-Kun** [PaddlePaddle/Paddle#27156]
我看有一个10万分类的预训练模型，下载下来以后里面是一个ResNet50_vd_10w_pretrained文件夹，里面都是weights,mean,variance等文件，下载的其它ResNet50_vd_pretrained预训练模型里面也是这样， 看教程说分类预测框架有三种，下载的哪些预训练模型都没有MODEL文件，所以我猜应该是persistable 模型，可是不管是模型转换然后再预测还是直接 “训练引擎 + persistable 模型预测”，都有一个 “--m=模型名称 “参数，我填了ResNet50_vd_10w_pretrained就报错说KEY错误，里面的介绍是”model_file(简写 m)：模型文件路径，如 ./resnet50-vd/model“，可是persistable 模型里面根本就没有MODEL文件，要转换的还还是要输入
python tools/export_model.py
--m=模型名称
--p=persistable 模型路径
--o=model和params保存路径

我真不知道该怎么用预训练模型预测了。有大神来讲一下吗？

**Comment by ForFishes** [comment]
请问这个模型是在哪里下载的？是对应哪个repo呢？

**Comment by Derek-Kun** [comment]
你好，我在PaddleClas上下载的，那边已经有人回复了，非常感谢~
