### ISSUE TITLE
【论文复现ECO】opt设置后，无法调节weight decay的decay mult。

### ISSUE THREAD

**Issue by Rayaction** [PaddlePaddle/Paddle#27162]
optimizer设置为momentum后，加载模型参数，可以找到learning rate的mult lr，但是weight decay那一项没有找到

**Comment by ForFishes** [comment]
![image](https://user-images.githubusercontent.com/19485646/92449722-0b754780-f1ed-11ea-8372-b43061c71d1d.png)
这样设置不可以吗？

**Comment by Rayaction** [comment]
> ![image](https://user-images.githubusercontent.com/19485646/92449722-0b754780-f1ed-11ea-8372-b43061c71d1d.png)
> 这样设置不可以吗？

论文复现中bias和weight是设置不一样的decay mult和lr mult

**Comment by Rayaction** [comment]
哦我重述一下，是没有找到decay mult

**Comment by ForFishes** [comment]
weight decay不是一个数吗？为什么会保存。

**Comment by Rayaction** [comment]
> weight decay不是一个数吗？为什么会保存。

return [
            {'params': first_3d_conv_weight, 'lr_mult': 5 if self.modality == 'Flow' else 1, 'decay_mult': 1,
             'name': "first_3d_conv_weight"},
            {'params': first_3d_conv_bias, 'lr_mult': 10 if self.modality == 'Flow' else 2, 'decay_mult': 0,
             'name': "first_3d_conv_bias"},
            {'params': normal_weight, 'lr_mult': 1, 'decay_mult': 1,
             'name': "normal_weight"},
            {'params': normal_bias, 'lr_mult': 2, 'decay_mult': 0,
             'name': "normal_bias"},
            {'params': bn, 'lr_mult': 1, 'decay_mult': 0,
             'name': "BN scale/shift"},
        ]

**Comment by Rayaction** [comment]
> weight decay不是一个数吗？为什么会保存。

为了防止模型参数太复杂导致过拟合，一般在目标函数计算的时候加入了正则项，所谓的weight_decay其实就是正则项前面的那个权值，设置偏大可以令模型在学习过程中约束参数的复杂程度。

除了全局设置的学习率lr和权重衰减项也就是weight_decay，每一个需要学习参数的layer都还有局部的加权值，分别是lr_mult和decay_mult，而对于卷积层的话，w和b都属于可以学习的参数，所以在学习更新中他们都有属于自己的lr_mult和decay_mult。
