### ISSUE TITLE
本地能跑的paddle预测程序部署到阿里云ubuntu上时报错：You could check whether you killed PaddlePaddle thread/process accidentally or report the case to PaddlePaddle

### ISSUE THREAD

**Issue by zt991211** [PaddlePaddle/Paddle#27182]
PaddlePaddle版本：1.8.0
python版本：3.7
使用gunicorn+flask部署paddlepaddle
@app.route('/predict/<name>')
def prediction(name):
    path=basedir+'\\static\\img\\'+name+'.png'
    img1=Image.open(path)
    org_ROI,ROI_PT=get_ROI_region(img1)
    img = []
    img.append(transform_img(np.array(ROI_PT)))
    img = np.array(img).astype('float32')
    place = fluid.CPUPlace()
    exe = fluid.Executor(place)
    in_var = img
    program, feed_vars, fetch_vars = fluid.io.load_inference_model('weights\\mnet_model\\home\\aistudio\\work\\mnet_model',
                                                                   executor=exe)
    fetch = exe.run(program, feed={feed_vars[0]: in_var}, fetch_list=fetch_vars)
    out10 = fetch[4]
    out10 = np.reshape(out10, (out10.shape[1], out10.shape[2], out10.shape[3]))
    out10 = np.transpose(out10, (1, 2, 0))
    disc_map = np.array(Image.fromarray(out10[:, :, 0]).resize((600, 600)))
    cup_map = np.array(Image.fromarray(out10[:, :, 1]).resize((600, 600)))
    disc_map[-round(DiscROI_size / 3):, :] = 0
    cup_map[-round(DiscROI_size / 2):, :] = 0
    De_disc_map = cv2.linearPolar(rotate(disc_map, 90), (DiscROI_size / 2, DiscROI_size / 2),
                                  DiscROI_size / 2, cv2.WARP_FILL_OUTLIERS + cv2.WARP_INVERSE_MAP)
    De_cup_map = cv2.linearPolar(rotate(cup_map, 90), (DiscROI_size / 2, DiscROI_size / 2),
                                 DiscROI_size / 2, cv2.WARP_FILL_OUTLIERS + cv2.WARP_INVERSE_MAP)
    ret, De_cup_map = cv2.threshold(De_cup_map, 0.5, 1, cv2.THRESH_BINARY)
    res, De_disc_map = cv2.threshold(De_disc_map, 0.5, 1, cv2.THRESH_BINARY)
    disc_h, disc_w = getCDR(De_disc_map)
    cup_h, cup_w = getCDR(De_cup_map)
    V_cdr=cup_h * 1.00 / disc_h
    W_cdr=cup_w * 1.00/ disc_w
    res=make_response(jsonify({"VCDR":str(V_cdr), "WCDR":str(W_cdr)}))
    res.headers['Access-Control-Allow-Origin'] = '*'
    return res
本地能跑上给出结果，但部署到阿里云服务器上时，一直报错，paddle进程一直被杀死

**Comment by ForFishes** [comment]
能否把环境信息和错误信息多贴一些。从这些比较难以判断。

**Comment by sshimii** [comment]
我也遇到这个问题了，大佬解决了嘛

**Comment by zt991211** [comment]
有点久远了，当时我是用的动态图的方式，后面我转换成了静态图加载，就没出什么问题了。------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;shimii&quot;<notifications@github.com&gt;
发送时间:&nbsp;2020年11月5日(星期四) 下午3:03
收件人:&nbsp;&quot;PaddlePaddle/Paddle&quot;<Paddle@noreply.github.com&gt;;
抄送:&nbsp;&quot;zt991211&quot;<814943622@qq.com&gt;;&quot;Author&quot;<author@noreply.github.com&gt;;
主题:&nbsp;Re: [PaddlePaddle/Paddle] 本地能跑的paddle预测程序部署到阿里云ubuntu上时报错：You could check whether you killed PaddlePaddle thread/process accidentally or report the case to PaddlePaddle (#27182)

**Comment by sshimii** [comment]
> 有点久远了，当时我是用的动态图的方式，后面我转换成了静态图加载，就没出什么问题了。------------------&nbsp;原始邮件&nbsp;------------------ 发件人:&nbsp;&quot;shimii&quot;<notifications@github.com&gt; 发送时间:&nbsp;2020年11月5日(星期四) 下午3:03 收件人:&nbsp;&quot;PaddlePaddle/Paddle&quot;<Paddle@noreply.github.com&gt;; 抄送:&nbsp;&quot;zt991211&quot;<814943622@qq.com&gt;;&quot;Author&quot;<author@noreply.github.com&gt;; 主题:&nbsp;Re: [PaddlePaddle/Paddle] 本地能跑的paddle预测程序部署到阿里云ubuntu上时报错：You could check whether you killed PaddlePaddle thread/process accidentally or report the case to PaddlePaddle (#27182)

谢谢大佬，我是调用情感分析的时候碰到的，我再研究研究o(╥﹏╥)o

**Comment by jtyoui** [comment]
我也遇到了。我排查了一天发现是多线程造成的。
我的代码如下：
```Python
print('-------start-----------')
reader.decorate_tensor_provider(wrapper)
reader.start()
np_infers = exe.run(program=main_program, fetch_list=fetch_list, use_program_cache=True)
reader.reset()
print('-------end-----------')
```
错误如下：

```
-------start-----------
-------start-----------
-------start-----------
-------start-----------
-------start-----------
-------start-----------
-------start-----------
-------start-----------
-------start-----------
-------start-----------
W0205 14:09:49.280166  9080 init.cc:216] Warning: PaddlePaddle catches a failure signal, it may not work properly
W0205 14:09:49.280190  9080 init.cc:218] You could check whether you killed PaddlePaddle thread/process accidentally or report the case to PaddlePaddle
W0205 14:09:49.280195  9080 init.cc:221] The detail failure signal is:

W0205 14:09:49.280200  9080 init.cc:224] *** Aborted at 1612505389 (unix time) try "date -d @1612505389" if you are using GNU date ***
W0205 14:09:49.281352  9080 init.cc:224] PC: @                0x0 (unknown)
W0205 14:09:49.281571  9080 init.cc:224] *** SIGSEGV (@0x18) received by PID 9023 (TID 0x7f0c60df9700) from PID 24; stack trace: ***
W0205 14:09:49.282974  9080 init.cc:224]     @     0x7f0ccebe3730 (unknown)
W0205 14:09:49.288301  9080 init.cc:224]     @     0x7f0c92f51000 paddle::framework::Executor::RunPreparedContext()
W0205 14:09:49.288421  9080 init.cc:224]     @     0x7f0c92c37e20 _ZZN8pybind1112cpp_function10initializeIZN6paddle6pybindL22pybind11_init_core_avxERNS_6moduleEEUlRNS2_9framework8ExecutorEPNS6_22ExecutorPrepareContextEPNS6_5ScopeEbbbE108_vIS8_SA_SC_bbbEINS_4nameENS_9is_methodENS_7siblingEEEEvOT_PFT0_DpT1_EDpRKT2_ENUlRNS_6detail13function_callEE1_4_FUNESU_
W0205 14:09:49.289373  9080 init.cc:224]     @     0x7f0c92cabff6 pybind11::cpp_function::dispatcher()
W0205 14:09:49.289505  9080 init.cc:224]     @           0x5d6a44 _PyMethodDef_RawFastCallKeywords
W0205 14:09:49.289594  9080 init.cc:224]     @           0x5d83a0 _PyObject_FastCallKeywords
W0205 14:09:49.289738  9080 init.cc:224]     @           0x54b011 (unknown)
W0205 14:09:49.289786  9080 init.cc:224]     @           0x5520d3 _PyEval_EvalFrameDefault
W0205 14:09:49.289872  9080 init.cc:224]     @           0x54b912 _PyEval_EvalCodeWithName
W0205 14:09:49.289954  9080 init.cc:224]     @           0x5d7692 _PyFunction_FastCallKeywords
W0205 14:09:49.290078  9080 init.cc:224]     @           0x54ae40 (unknown)
W0205 14:09:49.290125  9080 init.cc:224]     @           0x54f0af _PyEval_EvalFrameDefault
W0205 14:09:49.290210  9080 init.cc:224]     @           0x54b912 _PyEval_EvalCodeWithName
W0205 14:09:49.290292  9080 init.cc:224]     @           0x5d7692 _PyFunction_FastCallKeywords
W0205 14:09:49.290416  9080 init.cc:224]     @           0x54ae40 (unknown)
W0205 14:09:49.290462  9080 init.cc:224]     @           0x54f0af _PyEval_EvalFrameDefault
W0205 14:09:49.290546  9080 init.cc:224]     @           0x54b912 _PyEval_EvalCodeWithName
W0205 14:09:49.290633  9080 init.cc:224]     @           0x5d7692 _PyFunction_FastCallKeywords
W0205 14:09:49.290761  9080 init.cc:224]     @           0x54ae40 (unknown)
W0205 14:09:49.290807  9080 init.cc:224]     @           0x54f0af _PyEval_EvalFrameDefault
W0205 14:09:49.290892  9080 init.cc:224]     @           0x54b912 _PyEval_EvalCodeWithName
W0205 14:09:49.290977  9080 init.cc:224]     @           0x5d7692 _PyFunction_FastCallKeywords
W0205 14:09:49.291025  9080 init.cc:224]     @           0x54e17c _PyEval_EvalFrameDefault
W0205 14:09:49.291083  9080 init.cc:224]     @           0x5d86d6 _PyFunction_FastCallDict
W0205 14:09:49.291131  9080 init.cc:224]     @           0x54f61c _PyEval_EvalFrameDefault
W0205 14:09:49.291211  9080 init.cc:224]     @           0x5d739c _PyFunction_FastCallKeywords
W0205 14:09:49.291268  9080 init.cc:224]     @           0x54e31c _PyEval_EvalFrameDefault
W0205 14:09:49.291352  9080 init.cc:224]     @           0x5d739c _PyFunction_FastCallKeywords
W0205 14:09:49.291400  9080 init.cc:224]     @           0x54e31c _PyEval_EvalFrameDefault
W0205 14:09:49.291451  9080 init.cc:224]     @           0x5d86d6 _PyFunction_FastCallDict
W0205 14:09:49.291576  9080 init.cc:224]     @           0x4d9d12 (unknown)
W0205 14:09:49.291723  9080 init.cc:224]     @           0x5dad46 PyObject_Call
```
显然在执行` exe.run(program=main_program, fetch_list=fetch_list, use_program_cache=True)`命令阻塞了。从而导致错误。
但是我不知道怎么去解决这样的问题。请大佬指点？？？
