### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'nranks'

### ISSUE THREAD

**Issue by xsliangjxing** [PaddlePaddle/Paddle#27196]
- 版本、环境信息：
    1）PaddlePaddle版本：paddlepaddle-gpu 1.8.4post 107
    2）GPU：NVIDIA-SMI 441.22       Driver Version: 441.22       CUDA Version: 10.2           cuDNN Version: 7.6
    4）系统环境：win10，Python 3.7.6

- 训练信息
    1）单机/多卡（selected_gpus=0）
    2）workerlog.0:
         Traceback (most recent call last):
  File "E:\VBA\python\linear_knowledge\train.py", line 92, in <module>
    train_multi_gpu()
  File "E:\VBA\python\linear_knowledge\train.py", line 81, in train_multi_gpu
    avg_loss = model.scale_loss(avg_loss)
  File "E:\mdw\b_env\lib\site-packages\paddle\fluid\dygraph\parallel.py", line 333, in scale_loss
    if not self._is_data_parallel_mode():
  File "E:\mdw\b_env\lib\site-packages\paddle\fluid\dygraph\parallel.py", line 457, in _is_data_parallel_mode
    return self._strategy.nranks > 1
AttributeError: 'NoneType' object has no attribute 'nranks'
W0908 23:01:58.059443 13476 device_context.cc:252] Please NOTE: device: 0, CUDA Capability: 50, Driver API Version: 10.2, Runtime API Version: 10.0
W0908 23:01:58.132462 13476 device_context.cc:260] device: 0, cuDNN Version: 7.6.

- 复现信息：本人在尝试使用GPU多卡训练的时候，跳出以上错误，代码为飞桨平台课程原码（https://aistudio.baidu.com/aistudio/projectdetail/882250），训练前终端启用过launch（python -m paddle.distributed.launch --selected_gpus=0 --log_dir E:\python\mypractice E:\python\mypractice\train_multi_gpu.py）无报错。
                    另外我在尝试使用跟原码不一样个人版本（处理数据方式不一样）并在终端启用launch时，直接报出同样错误。我想不出解决办法了特此提出这个issue。 求解答， 谢谢！

**Comment by ForFishes** [comment]
代码能够贴一下。这个连接，没有权限登入。还有这个是windows环境，不支持nccl，所以GPU分布式是不支持的。

**Comment by xsliangjxing** [comment]
> 
> 
> 代码能够贴一下。这个连接，没有权限登入。还有这个是windows环境，不支持nccl，所以GPU分布式是不支持的。

--**谢谢回复，代码如下，另外您的意思是在windows环境使用飞桨就是没有办法采用GPU分布吗...？**
import os
import random
import paddle
import paddle.fluid as fluid
from paddle.fluid.dygraph.nn import Conv2D, Pool2D, Linear
import numpy as np
from PIL import Image

import gzip
import json


# 定义数据集读取器
def load_data(mode='train'):
    # 读取数据文件
    datafile = r'C://Users//sai//Downloads//mnist.json.gz'
    print('loading mnist dataset from {} ......'.format(datafile))
    data = json.load(gzip.open(datafile))
    # 读取数据集中的训练集，验证集和测试集
    train_set, val_set, eval_set = data

    # 数据集相关参数，图片高度IMG_ROWS, 图片宽度IMG_COLS
    IMG_ROWS = 28
    IMG_COLS = 28
    # 根据输入mode参数决定使用训练集，验证集还是测试
    if mode == 'train':
        imgs = train_set[0]
        labels = train_set[1]
    elif mode == 'valid':
        imgs = val_set[0]
        labels = val_set[1]
    elif mode == 'eval':
        imgs = eval_set[0]
        labels = eval_set[1]
    # 获得所有图像的数量
    imgs_length = len(imgs)
    # 验证图像数量和标签数量是否一致
    assert len(imgs) == len(labels), \
        "length of train_imgs({}) should be the same as train_labels({})".format(
            len(imgs), len(labels))

    index_list = list(range(imgs_length))

    # 读入数据时用到的batchsize
    BATCHSIZE = 100

    # 定义数据生成器
    def data_generator():
        # 训练模式下，打乱训练数据
        if mode == 'train':
            random.shuffle(index_list)
        imgs_list = []
        labels_list = []
        # 按照索引读取数据
        for i in index_list:
            # 读取图像和标签，转换其尺寸和类型
            img = np.reshape(imgs[i], [1, IMG_ROWS, IMG_COLS]).astype('float32')
            label = np.reshape(labels[i], [1]).astype('int64')
            imgs_list.append(img)
            labels_list.append(label)
            # 如果当前数据缓存达到了batch size，就返回一个批次数据
            if len(imgs_list) == BATCHSIZE:
                yield np.array(imgs_list), np.array(labels_list)
                # 清空数据缓存列表
                imgs_list = []
                labels_list = []

        # 如果剩余数据的数目小于BATCHSIZE，
        # 则剩余数据一起构成一个大小为len(imgs_list)的mini-batch
        if len(imgs_list) > 0:
            yield np.array(imgs_list), np.array(labels_list)

    return data_generator


# 定义模型结构
class MNIST(fluid.dygraph.Layer):
    def __init__(self):
        super(MNIST, self).__init__()

        # 定义一个卷积层，使用relu激活函数
        self.conv1 = Conv2D(num_channels=1, num_filters=20, filter_size=5, stride=1, padding=2, act='relu')
        # 定义一个池化层，池化核为2，步长为2，使用最大池化方式
        self.pool1 = Pool2D(pool_size=2, pool_stride=2, pool_type='max')
        # 定义一个卷积层，使用relu激活函数
        self.conv2 = Conv2D(num_channels=20, num_filters=20, filter_size=5, stride=1, padding=2, act='relu')
        # 定义一个池化层，池化核为2，步长为2，使用最大池化方式
        self.pool2 = Pool2D(pool_size=2, pool_stride=2, pool_type='max')
        # 定义一个全连接层，输出节点数为10
        self.fc = Linear(input_dim=980, output_dim=10, act='softmax')

    # 定义网络的前向计算过程
    def forward(self, inputs):
        x = self.conv1(inputs)
        x = self.pool1(x)
        x = self.conv2(x)
        x = self.pool2(x)
        x = fluid.layers.reshape(x, [x.shape[0], 980])
        x = self.fc(x)
        return x


def train_multi_gpu():
    ##修改1-从环境变量获取使用GPU的序号
    place = fluid.CUDAPlace(fluid.dygraph.parallel.Env().dev_id)

    with fluid.dygraph.guard(place):

        ##修改2-对原模型做并行化预处理
        strategy = fluid.dygraph.parallel.prepare_context()
        model = MNIST()
        model = fluid.dygraph.parallel.DataParallel(model, strategy)

        model.train()

        # 调用加载数据的函数
        train_loader = load_data('train')
        ##修改3-多GPU数据读取，必须确保每个进程读取的数据是不同的
        train_loader = fluid.contrib.reader.distributed_batch_reader(train_loader)

        optimizer = fluid.optimizer.SGDOptimizer(learning_rate=0.01, parameter_list=model.parameters())
        EPOCH_NUM = 5
        for epoch_id in range(EPOCH_NUM):
            for batch_id, data in enumerate(train_loader()):
                # 准备数据
                image_data, label_data = data
                image = fluid.dygraph.to_variable(image_data)
                label = fluid.dygraph.to_variable(label_data)

                predict = model(image)

                loss = fluid.layers.cross_entropy(predict, label)
                avg_loss = fluid.layers.mean(loss)

                # 修改4-多GPU训练需要对Loss做出调整，并聚合不同设备上的参数梯度
                avg_loss = model.scale_loss(avg_loss)
                avg_loss.backward()
                model.apply_collective_grads()
                # 最小化损失函数，清除本次训练的梯度
                optimizer.minimize(avg_loss)
                model.clear_gradients()

                if batch_id % 200 == 0:
                    print("epoch: {}, batch: {}, loss is: {}".format(epoch_id, batch_id, avg_loss.numpy()))

    # 保存模型参数
    fluid.save_dygraph(model.state_dict(), 'mnist')

train_multi_gpu()

终端命令：python -m paddle.distributed.launch --selected_gpus=0 --log_dir E:\python\mypractice E:\python\mypractice\train_multi_gpu.p

**Comment by ForFishes** [comment]
![image](https://user-images.githubusercontent.com/19485646/92675137-4e503000-f351-11ea-84a6-578079c50094.png)
windows下，不支持nccl，所以现在目前不支持多卡gpu。你的代码看，没什么问题，建议用linux系统试下。

**Comment by xsliangjxing** [comment]
明白了，非常感谢~
