### ISSUE TITLE
Paddle预测同一个网络不同step保存的模型预测性能差异大

### ISSUE THREAD

**Issue by aprilvkuo** [PaddlePaddle/Paddle#27199]
# 一、训练paddle版本
2.0-alpha， 使用TracedLayer动转静部署。
    
# 二、 主要使用的op
GRUUnit, 固定了序列长度。

# 三、capi版本
    1）PaddlePaddle版本：baidu/lib/paddlepaddle@v1.8.4-gcc82-mkl-avx-mkldnn_PD_BL
    2）CPU

# 四、 模型以及耗时情况
1) 100step的model，  单线程CPU， 每条query平均耗时约为3.5ms。
2) 收敛后的model， 单线程CPU， 每条query平均耗时约为30ms。

# 五、 模型代码

![image](https://user-images.githubusercontent.com/9441675/92548578-fa2e4880-f289-11ea-8c17-fa283d7fbf02.png)

![image](https://user-images.githubusercontent.com/9441675/92548555-eaaeff80-f289-11ea-801e-4cac0b684eca.png)

**Comment by jiweibo** [comment]
请问能否提供预测单测和这两个模型，我本地对比测试下

**Comment by juncaipeng** [comment]
测试代码：
http://icode.baidu.com/repos/baidu/personal-code/guohongjie-paddle-pred/blob/lib_paddle_18:test/demo_0902_fo_paddle_18.cpp

![image](https://user-images.githubusercontent.com/52520497/93076044-5396dd00-f6b9-11ea-9d4d-76259a035000.png)



速度快的模型：

http://bj.bcebos.com/unit-test/guohongjie/model_res_debug.gz?authorization=bce-auth-v1%2F9060efba387a48a2a907559e66c49f25%2F2020-09-14T03%3A36%3A20Z%2F-1%2F%2F11c5cc3616338f87cda09648dba7d5914c301cfce1e69422b7ce5445e2e8e20e


速度慢的模型：
http://bj.bcebos.com/unit-test/guohongjie/model_res.gz?authorization=bce-auth-v1%2F9060efba387a48a2a907559e66c49f25%2F2020-09-14T03%3A36%3A27Z%2F-1%2F%2Fdd01695afc55936baf372dc59635a0b78c42325045f843594f623b19147b0791


cpu上单线程profile数据：

![image](https://user-images.githubusercontent.com/52520497/93056199-af07a180-f69e-11ea-99d3-5722bb321149.png)
