### ISSUE TITLE
lack of C++ documentation / API reference

### ISSUE THREAD

**Issue by flishwang** [PaddlePaddle/Paddle#27211]
All I can find about how to write new C++/cuda operators are:
https://www.paddlepaddle.org.cn/documentation/docs/en/advanced_guide/addon_development/new_op/new_op_en.html
https://www.paddlepaddle.org.cn/documentation/docs/zh/advanced_guide/addon_development/new_op/op_notes.html

These are examples about how to write new operators. But I cannot find any detailed documentation about the classes or macros used in the examples. The only way to learn to use them is reading the source code or just guessing the meanings.

I wonder if it's possible to provide some API reference for the most frequently used classes and macros when writing a C++ operator, like Tensor, LodTensor, context, etc.. It is wonderful if there are C++ docs not only the getting_started, but also a tutorial and API reference, (i.e. http://eigen.tuxfamily.org/dox/classEigen_1_1Array.html ).

**Comment by Heeenrrry** [comment]
@flishwang Hi, thanks for your attention! More supports for C++ development will be included in next release later this year. Docs and examples will be given. We would like to inform you in the first instance later.

**Comment by flishwang** [comment]
> @flishwang Hi, thanks for your attention! More supports for C++ development will be included in next release later this year. Docs and examples will be given. We would like to inform you in the first instance later.

Thanks for your timely reply! I'll wait for the docs and new features in the next release.
