### ISSUE TITLE
paddlepaddle中一维膨胀卷积实现问题

### ISSUE THREAD

**Issue by yuhangT** [PaddlePaddle/Paddle#27216]
现在paddlepaddle中实现一维膨胀卷积，但是序列卷积API中并没有膨胀系数，所以用二维卷积来实现

![image](https://user-images.githubusercontent.com/49428064/92591917-5799b800-f2d1-11ea-86ca-6ac46f244b02.png)

但是效果和在keras中实现的一维膨胀卷积效果相差比较大，不知道是不是用二维实现一维的时候出现了问题？
keras中的代码：
![image](https://user-images.githubusercontent.com/49428064/92592052-8ca60a80-f2d1-11ea-8d15-5cf25d1fc235.png)

**Comment by heavengate** [comment]
conv的输入默认是NCHW格式，你reshape的时候指定shape里1在第二维，这一维是C，可以放在最后一维

**Comment by yuhangT** [comment]
> conv的输入默认是NCHW格式，你reshape的时候指定shape里1在第二维，这一维是C，可以放在最后一维

请问C是通道数，不是应该将通道数设为1吗？比如一个维度为64*  256*  128的   64为batch_size  256为max_len（最大句长）  128为词向量维度，不是N=64  C=1  H=256  W=128  吗？

**Comment by heavengate** [comment]
如果你的数据是64* 256* 128，你想把通道C设置成1，那数据格式就是[64, 1, 256, 128]，这本身就是一个使用Conv2D的NCHW格式，不需要用到一维卷积

**Comment by yuhangT** [comment]
> 如果你的数据是64* 256* 128，你想把通道C设置成1，那数据格式就是[64, 1, 256, 128]，这本身就是一个使用Conv2D的NCHW格式，不需要用到一维卷积

您好，我再重申以下我的问题，我的初衷是实现一维卷积网络，但是在paddle里边序列卷积没有膨胀系数这个参数，所以考虑用二维卷积去实现一维卷积，输入数据是64* 256* 128的 64为batch_size 256为max_len（最大句长） 128为词向量维度，现在是这样实现的

![image](https://user-images.githubusercontent.com/49428064/93012848-1574bd00-f5d6-11ea-866d-404906336fca.png)

在原keras版本是这样实现的：

![image](https://user-images.githubusercontent.com/49428064/93012702-f6c1f680-f5d4-11ea-8d58-2b5a82c6573f.png)

由于我们实现结果f1值和keras版本有10个点的差距，我们检查了所有代码，感觉可能是这个卷积网络的实现出现了问题，请您帮忙看下，我们这样实现有问题吗？

**Comment by heavengate** [comment]
> > 如果你的数据是64* 256* 128，你想把通道C设置成1，那数据格式就是[64, 1, 256, 128]，这本身就是一个使用Conv2D的NCHW格式，不需要用到一维卷积
> 
> 您好，我再重申以下我的问题，我的初衷是实现一维卷积网络，但是在paddle里边序列卷积没有膨胀系数这个参数，所以考虑用二维卷积去实现一维卷积，输入数据是64* 256* 128的 64为batch_size 256为max_len（最大句长） 128为词向量维度，现在是这样实现的
> 
> ![image](https://user-images.githubusercontent.com/49428064/93012848-1574bd00-f5d6-11ea-866d-404906336fca.png)
> 
> 在原keras版本是这样实现的：
> 
> ![image](https://user-images.githubusercontent.com/49428064/93012702-f6c1f680-f5d4-11ea-8d58-2b5a82c6573f.png)
> 
> 由于我们实现结果f1值和keras版本有10个点的差距，我们检查了所有代码，感觉可能是这个卷积网络的实现出现了问题，请您帮忙看下，我们这样实现有问题吗？

如果你要一个数据使用Conv1D，这个数据的格式应该是[N, C, H]，对应你的数据64*256*128，应该是N=64, C=256, H=128这样来实现，为啥要加一个shape为1的C通道呢，加入了一个shape为1的C通道后数据格式是[N, C, H, W]，这个应该过Conv2D

**Comment by heavengate** [comment]
> > > 如果你的数据是64* 256* 128，你想把通道C设置成1，那数据格式就是[64, 1, 256, 128]，这本身就是一个使用Conv2D的NCHW格式，不需要用到一维卷积
> > 
> > 
> > 您好，我再重申以下我的问题，我的初衷是实现一维卷积网络，但是在paddle里边序列卷积没有膨胀系数这个参数，所以考虑用二维卷积去实现一维卷积，输入数据是64* 256* 128的 64为batch_size 256为max_len（最大句长） 128为词向量维度，现在是这样实现的
> > ![image](https://user-images.githubusercontent.com/49428064/93012848-1574bd00-f5d6-11ea-866d-404906336fca.png)
> > 在原keras版本是这样实现的：
> > ![image](https://user-images.githubusercontent.com/49428064/93012702-f6c1f680-f5d4-11ea-8d58-2b5a82c6573f.png)
> > 由于我们实现结果f1值和keras版本有10个点的差距，我们检查了所有代码，感觉可能是这个卷积网络的实现出现了问题，请您帮忙看下，我们这样实现有问题吗？
> 
> 如果你要一个数据使用Conv1D，这个数据的格式应该是[N, C, H]，对应你的数据64_256_128，应该是N=64, C=256, H=128这样来实现，为啥要加一个shape为1的C通道呢，加入了一个shape为1的C通道后数据格式是[N, C, H, W]，这个应该过Conv2D。
如果是想一个原本走Conv1D的数据走Conv2D，应该增加W，而不是增加C
