### ISSUE TITLE
加载预训练模型遇到问题

### ISSUE THREAD

**Issue by bjkite** [PaddlePaddle/Paddle#2721]
加载预训练模型遇到如下问题：
1. 对预训练模型的fc层做了修改，但是加载模型的时候还是按照原模型的形状加载，报错
2.将上述fc层用name=“xxx”重命名，仍然加载原模型的参数，而且新fc层的形状参数出错。
    out = paddle.layer.fc(  
        name=“gg_fc”,                                                                  
        input=conv10,                                                                         
        size=emb_dim,                                                                         
        act=paddle.activation.Relu(),                                                         
        layer_attr=paddle.attr.Extra(drop_rate=0.5)) 
这里，conv10是1000维，emb_dim是200维，但是报如下错误，变成了(200,2136)，后面(1000,41190)是预训练模型在这一层的形状。
ValueError: Value shape mismatch, expect (200, 2136), should (1000, 41190)

3. caffe 模型到 paddle模型转换，参数对不上
caffe配置如下 ：
name: ""
layers {
  layer {
    name: "conv1"
    type: "conv"
    num_output: 64
    weight_filler {
      type: "gaussian"
      std: 0.001
    }
    bias_filler {
      type: "constant"
      value: 0
    }
    pad: 0
    kernelsize: 7
    group: 1
    stride: 2
  }
  bottom: "data"
  top: "conv1"
}
layers {
  layer {
    name: "conv1_neuron"
    type: "relu"
  }
  bottom: "conv1"
  top: "conv1"
}
layers {
  layer {
    name: "pool1"
    type: "pool"
    kernelsize: 3
    stride: 3
    pool: MAX
  }
  bottom: "conv1"
  top: "pool1"
}
layers {
  layer {
    name: "cmrnorm1"
    type: "lrn"
    local_size: 5
    alpha: 0.0005
    beta: 0.75
  }
  bottom: "pool1"
  top: "cmrnorm1"
}
padlle对应配置如下：
conv1 = paddle.networks.simple_img_conv_pool(
            input=input,
            num_channel=3,
            pool_size=3,
            pool_stride=3,
            num_filters=64,
            filter_size=7,
            conv_stride=2,
            groups=1,
            act=paddle.activation.Relu(),
            pool_type=paddle.pooling.Max())
使用转化后的模型加载参数，在这一层，报如下错误：
ValueError: Value shape mismatch, expect (1, 1179648), should (1, 9408)
形状差别很大，是不是不能使用simple_img_conv_pool，要严格按照单层来映射？

**Comment by qingqing01** [comment]
问题1：
> 这里，conv10是1000维，emb_dim是200维，但是报如下错误，变成了(200,2136)，后面(1000,41190)是预训练模型在这一层的形状。
> ValueError: Value shape mismatch, expect (200, 2136), should (1000, 41190)

初始化是按照参数名字匹配的，如果对fc层的size做了修改， 如何和预训练模型的大小(1000,41190)不匹配，不能用来初始化，需要将初始化的文件里的`gg_fc`这个对应的参数删除掉。 另外变成`(200,2136)` 不确定是不是因为名字对应错了。

问题2：

> 形状差别很大，是不是不能使用simple_img_conv_pool，要严格按照单层来映射？

有可能是caffe模型到paddle模型转换后的名字没有对应上, [文档](https://github.com/PaddlePaddle/models/tree/develop/image_classification/caffe2paddle)写了一些注意事项。

**Comment by guoshengCS** [comment]
第一个问题的话，可以尝试把tar模型文件解压去掉不需要的layer然后再重新打包；或者可以按如下自行加载模型的代码，过滤掉不需要重模型加载的layer
```python
    # Create parameters
    parameters = paddle.parameters.create(cost)
    with gzip.open('model.tar.gz', 'r') as f:
        fparameters = paddle.parameters.Parameters.from_tar(f)
    for param_name in fparameters.names():
        if param_name in parameters.names(): # append some rules to filter
            parameters.set(param_name, fparameters.get(param_name))
```

第二个问题的话，simple_img_conv_pool默认会使用`conv_pool`进行命名（会产生`___conv_pool_0___conv.w0`的参数名），这与单层默认命名有差别，按照单层来映射应该可以
```python
@wrap_name_default("conv_pool")
def simple_img_conv_pool(input,
                         filter_size,
                         num_filters,
                         pool_size,
                         name=None,
                         pool_type=None,
                         act=None,
                         groups=1,
                         conv_stride=1,
                         conv_padding=0,
                         bias_attr=None,
                         num_channel=None,
                         param_attr=None,
                         shared_bias=True,
                         conv_layer_attr=None,
                         pool_stride=1,
                         pool_padding=0,
                         pool_layer_attr=None):
```
