### ISSUE TITLE
官方网站代码注释出现了参数书写错误

### ISSUE THREAD

**Issue by wangye707** [PaddlePaddle/Paddle#27210]
官网链接：https://www.paddlepaddle.org.cn/tutorials/projectdetail/811979#anchor-10
描述：Resnet模型的层数描述中，对152的注释描述为了50。
细节：paddle官网1.8版本->教程->零基础入门深度学习->深度学习实践应用:计算机视觉->图像分类->ResNet的代码中
           `elif layers == 152:
            #ResNet50包含多个模块，其中第2到第5个模块分别包含3、8、36、3个残差块
            depth = [3, 8, 36, 3]`
           152的注释写成了50
截图：
![image](https://user-images.githubusercontent.com/39162106/92580138-9f641380-f2c0-11ea-9e95-c8f6a401b0ed.png)

**Comment by wulei123456789** [comment]
同学您好，非常感谢您给我们反馈飞桨教程的问题，您的意见对我们非常重要。
您反馈的问题，飞桨教程已经修改，欢迎您继续使用，如遇到问题，随时联系我们，谢谢！
![image](https://user-images.githubusercontent.com/59363068/92694096-1eb51e00-f379-11ea-8304-e8f1c488320c.png)

**Comment by morestart** [comment]
飞桨卷积API介绍
飞桨卷积算子对应的API是paddle.fluid.dygraph.Conv2D，用户可以直接调用API进行计算，也可以在此基础上修改。常用的参数如下：
filter_size(int|tuple) - 卷积核大小，可以是整数，比如3，表示卷积核的高和宽均为3 ；或者是两个整数的list，例如[3,2]，表示卷积核的高为3，宽为2。
stride(int|tuple) - 步幅，可以是整数，默认值为1，表示垂直和水平滑动步幅均为1；或者是两个整数的list，例如[3,2]，表示垂直滑动步幅为3，水平滑动步幅为2。
padding(int|tuple) - 填充大小，可以是整数，比如1，表示竖直和水平边界填充大小均为1；或者是两个整数的list，例如[2,1]，表示竖直边界填充大小为2，水平边界填充大小为1。
act（str）- 应用于输出上的激活函数，如Tanh、Softmax、Sigmoid，Relu等，默认值为None。

卷积API介绍部分 查看源码此处应为元组 而非列表

**Comment by wulei123456789** [comment]
非常感谢您使用飞桨教程，并提出宝贵意见，您的意见对我们飞桨的改进和优化至关重要。
------------------------------
问题答复如下：
在dygraph.Conv2D API中，代码对于数据格式没有限制，元组和列表都可以。
-----------------------------
如果您还有其他问题或疑惑，请随时联系我们，谢谢！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/Paddle"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年9月14日(星期一) 下午5:07
收件人:&nbsp;"PaddlePaddle/Paddle"<Paddle@noreply.github.com&gt;;
抄送:&nbsp;"小红莓"<143150@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [PaddlePaddle/Paddle] 官方网站代码注释出现了参数书写错误 (#27210)





 
飞桨卷积API介绍
 飞桨卷积算子对应的API是paddle.fluid.dygraph.Conv2D，用户可以直接调用API进行计算，也可以在此基础上修改。常用的参数如下：
 filter_size(int|tuple) - 卷积核大小，可以是整数，比如3，表示卷积核的高和宽均为3 ；或者是两个整数的list，例如[3,2]，表示卷积核的高为3，宽为2。
 stride(int|tuple) - 步幅，可以是整数，默认值为1，表示垂直和水平滑动步幅均为1；或者是两个整数的list，例如[3,2]，表示垂直滑动步幅为3，水平滑动步幅为2。
 padding(int|tuple) - 填充大小，可以是整数，比如1，表示竖直和水平边界填充大小均为1；或者是两个整数的list，例如[2,1]，表示竖直边界填充大小为2，水平边界填充大小为1。
 act（str）- 应用于输出上的激活函数，如Tanh、Softmax、Sigmoid，Relu等，默认值为None。
 
卷积API介绍部分 查看源码此处应为元组 而非列表
