### ISSUE TITLE
Required clang-format version is too old for Ubuntu 18.04

### ISSUE THREAD

**Issue by wojtuss** [PaddlePaddle/Paddle#27214]
In the file `tools/codestyle/clang_format.hook` there is a requirement for the clang-format version to be 3.8. However, on Ubuntu 18.04 LTS, supported by PaddlePaddle, the 3.8 version is not generally available from repositories, 3.9 is available instead. Can we update the code and use 3.9 version?

**Comment by luotao1** [comment]
> Can we update the code and use 3.9 version

Sorry, since it may affect a lot of codes and developers, we could not directly update the codes. We will have a discussion internally.

@wojtuss Is the difference large in code format between the 3.8 version and 3.9 version?

**Comment by wojtuss** [comment]
There are some, but not many differences in the code after running 3.9. I include the diff after running 3.9 on the whole Paddle project.
[after-clang-format-3.9.txt](https://github.com/PaddlePaddle/Paddle/files/5194722/after-clang-format-3.9.txt)

**Comment by luotao1** [comment]
Got it, after our internal discussion, we will update the result here.

**Comment by lidanqing-vv** [comment]
@wojtuss  Baidu said recently because of RC release, this issue will be delayed. Baidu will rearrange the priority of all issues
