### ISSUE TITLE
expand操作是否会开额外的空间？

### ISSUE THREAD

**Issue by Maybewuss** [PaddlePaddle/Paddle#27227]
pytorch的expand不会，paddle下的呢？

**Comment by yaoxuefeng6** [comment]
expand是有开额外的空间的，paddle的实现和pytorch的还是又一些区别的。  这个我们会后续评估下

**Comment by Maybewuss** [comment]
请问这个后续有评估吗？卡片直接关闭是咋回事啊？这op能像pytorch拆成expand和repeat两个api吗？expand只复制视图可以吗，不然我模型里面里涉及到这些操作贼容易爆显存。
