### ISSUE TITLE
AnalysisPredictor怎么部署ernie模型？

### ISSUE THREAD

**Issue by yeguang1991** [PaddlePaddle/Paddle#27229]

**Comment by shangzhizhou** [comment]
和其他模型没有什么区别的，具体可以参考https://www.paddlepaddle.org.cn/documentation/docs/zh/advanced_guide/inference_deployment/inference/native_infer.html
更多示例：https://github.com/PaddlePaddle/Paddle-Inference-Demo

**Comment by yeguang1991** [comment]
> 和其他模型没有什么区别的，具体可以参考https://www.paddlepaddle.org.cn/documentation/docs/zh/advanced_guide/inference_deployment/inference/native_infer.html
> 更多示例：https://github.com/PaddlePaddle/Paddle-Inference-Demo

config = AnalysisConfig(),这个参数应该怎么传，我直接把模型路径传进去，总是报错，模型是这样的
![image](https://user-images.githubusercontent.com/66579493/92690891-4e155c00-f374-11ea-9220-9837b4f40e47.png)

**Comment by shangzhizhou** [comment]
具体的AnalysisConfig使用示例请看一下上一个回复的链接。config->SetModel("./model_dir");
仍未解决请贴一下具体的报错内容和code

**Comment by yeguang1991** [comment]
> 具体的AnalysisConfig使用示例请看一下上一个回复的链接。config->SetModel("./model_dir");
> 仍未解决请贴一下具体的报错内容和code

code
![image](https://user-images.githubusercontent.com/66579493/92848420-cafc1080-f41c-11ea-8b8e-37334caccec7.png)
error
![image](https://user-images.githubusercontent.com/66579493/92848546-eb2bcf80-f41c-11ea-8caf-5b8a3f46d98c.png)
模型
![image](https://user-images.githubusercontent.com/66579493/92848827-3514b580-f41d-11ea-96a7-764733b134ec.png)

**Comment by yeguang1991** [comment]
> 具体的AnalysisConfig使用示例请看一下上一个回复的链接。config->SetModel("./model_dir");
> 仍未解决请贴一下具体的报错内容和code

Code:
from paddle.fluid.core import create_paddle_predictor
from paddle.fluid.core import AnalysisConfig

config = AnalysisConfig('C:\mnt\matching\model\800001\ckpt.step2154')
config.disable_gpu()
config.enable_mkldnn()
predictor = create_paddle_predictor(config)

ERROR:
Traceback (most recent call last):
  File "C:/matching2/test.py", line 9, in <module>
    predictor = create_paddle_predictor(config)
paddle.fluid.core_avx.EnforceNotMet: 

--------------------------------------------
C++ Call Stacks (More useful to developers):
--------------------------------------------
Windows not support stack backtrace yet.

----------------------
Error Message Summary:
----------------------
Error: Cannot open file C:\mnt\matching\model\800001\ckpt.step2154/__model__ at (D:\1.8.1\paddle\paddle\fluid\inference\api\analysis_predictor.cc:703)

I0911 10:56:38.820966 12432 analysis_predictor.cc:138] Profiler is deactivated, and no profiling report will be generated.

**Comment by shangzhizhou** [comment]
请确认下模型目录里是否有__model__文件，如果没有，请确认下保存模型使用的方法是否正确。如果后续要做预测， 请选择 save_inference_model 进行变量和网络的保存，具体请参考
https://www.paddlepaddle.org.cn/documentation/docs/zh/beginners_guide/coding_practice/save_load_variables.html
