### ISSUE TITLE
如何通过 numpy 转 VarBase 获取正确的shape？

### ISSUE THREAD

**Issue by ymzlygw** [PaddlePaddle/Paddle#27226]
你好，我对某个学习模型中的某一个变量进行了.shape和.type查看，获得信息如下：
<class 'paddle.fluid.core_avx.VarBase'> size:[1, 80, 832]
现在我手头有一个 a.shape = (80,832) 的numpy类型变量，想转化为上面同规格变量.进行升维和numpy转VarBase后，获得如下信息：re_shape:<class 'paddle.fluid.core_avx.VarBase'>, size(1, 80, 832)

但是转化后的变量与原抽取出的变量不同，一个是【1，80，832】 ，一个是（1，80，832），而且发现不能使用tuple转list。
那么如何reshape才能得到【1，80，832】呢？

**Comment by yaoxuefeng6** [comment]
能提供下代码示例吗？

**Comment by ymzlygw** [comment]
> 能提供下代码示例吗？

好的，代码例:
mel.shape
-> (832,80)

 re_mel = torch.from_numpy(mel.T)
 re_mel1 = re_mel.unsqueeze(0)
 re_mel2 = re_mel1.numpy()
re_mel2.shape
->(1,80,832)

--numpy转VarBase:
ex_mel1 = fluid.dygraph.to_variable(re_mel2)    “<class 'paddle.fluid.core_avx.VarBase'>, size(1, 80, 832)”

原模型中抽出的变量shape：<class 'paddle.fluid.core_avx.VarBase'> size:[1, 80, 832]，    括号不一样

**Comment by yaoxuefeng6** [comment]
你好 我尝试复现下你的场景 代码中动态图使用了reshape api 结果输出的shape是一致的呀，后两个都是中括号
```python
mel = np.random.rand(832,80)
re_mel = torch.from_numpy(mel.T)
re_mel1 = re_mel.unsqueeze(0)
re_mel2 = re_mel1.numpy()
print(re_mel2.shape)

with fluid.dygraph.guard():
    ex_mel1 = fluid.dygraph.to_variable(re_mel2)
    print(ex_mel1.shape)
    x1_var = fluid.dygraph.to_variable(mel)
    x2 = paddle.fluid.layers.reshape(x1_var, shape=[1,80,832])
    print(x2.shape)
```
(1, 80, 832)
[1, 80, 832]
[1, 80, 832]

**Comment by ymzlygw** [comment]
> 你好 我尝试复现下你的场景 代码中动态图使用了reshape api 结果输出的shape是一致的呀，后两个都是中括号
> 
> ```python
> mel = np.random.rand(832,80)
> re_mel = torch.from_numpy(mel.T)
> re_mel1 = re_mel.unsqueeze(0)
> re_mel2 = re_mel1.numpy()
> print(re_mel2.shape)
> 
> with fluid.dygraph.guard():
>     ex_mel1 = fluid.dygraph.to_variable(re_mel2)
>     print(ex_mel1.shape)
>     x1_var = fluid.dygraph.to_variable(mel)
>     x2 = paddle.fluid.layers.reshape(x1_var, shape=[1,80,832])
>     print(x2.shape)
> ```
> 
> (1, 80, 832)
> [1, 80, 832]
> [1, 80, 832]

奇怪了，我的原代码是这样的：读取一个.npy文件，然后进行转换，

        output_mel_dir = './output-mel/2_mel_en.npy'
        experiment_mel = np.load(output_mel_dir)
        print("the shape experiment mel:{}, type:{}".format(experiment_mel.shape, type(experiment_mel)))
        experiment_mel1 = fluid.dygraph.to_variable(experiment_mel)
        print("re_shape:{}, size:{}".format(type(experiment_mel1), experiment_mel.shape)

结果输出是这样：
       the shape experiment mel:(1, 80, 129), type:<class 'numpy.ndarray'>
       re_shape:<class 'paddle.fluid.core_avx.VarBase'>, size:(1, 80, 129)
还是圆括号（），到底是什么问题呢

**Comment by ymzlygw** [comment]
> 你好 我尝试复现下你的场景 代码中动态图使用了reshape api 结果输出的shape是一致的呀，后两个都是中括号
> 
> ```python
> mel = np.random.rand(832,80)
> re_mel = torch.from_numpy(mel.T)
> re_mel1 = re_mel.unsqueeze(0)
> re_mel2 = re_mel1.numpy()
> print(re_mel2.shape)
> 
> with fluid.dygraph.guard():
>     ex_mel1 = fluid.dygraph.to_variable(re_mel2)
>     print(ex_mel1.shape)
>     x1_var = fluid.dygraph.to_variable(mel)
>     x2 = paddle.fluid.layers.reshape(x1_var, shape=[1,80,832])
>     print(x2.shape)
> ```
> 
> (1, 80, 832)
> [1, 80, 832]
> [1, 80, 832]

我又试着比较了一下，如果是直接用np.random.rand创建的numpy对象，再进行之前的转换的话，确实是中括号【】，但是如果是np.load读取的numpy对象，转换完就只能是圆括号()，这是什么原因...........

**Comment by yaoxuefeng6** [comment]
可能和numpy的用法有关
