### ISSUE TITLE
`cc_binary` DEPS should handle dependencies order

### ISSUE THREAD

**Issue by reyoung** [PaddlePaddle/Paddle#2723]
Currently, `generic.cmake` provides `cc_binary` to compile c++ binary. It uses `DEPS` arguments to get like libraries. But setting `DEPS` should in a link correct order, i.e., if several libraries need to be linked, the library A depends on library B, the link order must be `A B` not `B A`. [Reference link](https://stackoverflow.com/questions/45135/why-does-the-order-in-which-libraries-are-linked-sometimes-cause-errors-in-gcc/409470#409470)

It seems we should provide an API easy to use, so maybe we should make libraries surrounded by

```
-Wl,--start-group
...
-Wl,--end-group
```

I am not quite sure are there any disadvantages for `start-group/end-group`. So please do not hesitate to comment if you have any concerns about this issue.

If `start-group/end-group` is OK for us, I will give an PR within today.

**Comment by wangkuiyi** [comment]
The linkage order is related with dependency propagation, and I think this issue is highly related to https://github.com/PaddlePaddle/Paddle/issues/2728.  I personally hope that CMake has provided both dependency propagation and ordering for us, but I am not sure. @gangliao is the expert of CMake.

**Comment by reyoung** [comment]
This issue is fixed because #2728 is fixed. The dependency order is handle by #2728 .
