### ISSUE TITLE
官方文档中lstm接口,使用bilstm时无法得到正确的返回结果？

### ISSUE THREAD

**Issue by wu8320175** [PaddlePaddle/Paddle#27249]
版本、环境信息：
    1）PaddlePaddle版本：1.8-静态图
 LSTM文档：https://www.paddlepaddle.org.cn/documentation/docs/zh/api_cn/layers_cn/lstm_cn.html#lstm

![image](https://user-images.githubusercontent.com/24267883/92745306-d287cf00-f3b4-11ea-81d3-0162c6d11bd3.png)
文档中说了配置好相应参数后应该返回2*hidden_size，但是我按下面的代码配置为啥得不到正确的返回呢？
```
import paddle.fluid as fluid
import paddle.fluid.layers as layers

emb_dim = 256
vocab_size = 10000
data = fluid.layers.data(name='x1', shape=[-1, 100, 1],
               dtype='int64')
emb = fluid.layers.embedding(input=data, size=[vocab_size, emb_dim], is_sparse=True)
batch_size = 20
max_len = 100
dropout_prob = 0.2
hidden_size = 150
num_layers = 1
init_h = layers.fill_constant( [num_layers*2, batch_size, hidden_size], 'float32', 0.0 )
init_c = layers.fill_constant( [num_layers*2, batch_size, hidden_size], 'float32', 0.0 )
rnn_out, last_h, last_c = layers.lstm(emb,init_h, init_c, max_len, hidden_size, num_layers,is_bidirec=True, dropout_prob=dropout_prob)
rnn_out.shape,last_h.shape,last_c.shape
# rnn_out.shape  # (-1, 100, 150)
# last_h.shape  # (2, 20, 150)
# last_c.shape  # (2, 20, 150)
```
lastc和lasth能得到正确结果但是rnn_out明显不对呀 [batch_size,seq_len,hidden_size∗2]应该是(-1, 100, 300)呀？

**Comment by guoshengCS** [comment]
1.8版本这个接口有些问题，还请更新版本，或者使用类似如下方式建立bilstm
```python
            inputs = fluid.data(name="inputs",
                                shape=[-1, 32, 128],
                                dtype="float32")
            # cell = fluid.layers.GRUCell(hidden_size=128)
            fw_cell = fluid.layers.LSTMCell(hidden_size=128)
            fw_outputs = fluid.layers.rnn(cell= fw_cell, inputs=inputs)
            bw_cell = fluid.layers.LSTMCell(hidden_size=128)
            bw_outputs = fluid.layers.rnn(cell= bw_cell, inputs=inputs, is_reverse=True)
```

**Comment by wu8320175** [comment]
感谢您的回复。首先bilstm的问题我已经使用了类似您的方案解决了，我最近的目的是想在aitudio上使用paddle复现复现出一篇论文的代码，但是原代码中中间夹杂了RNN dropout机制,所以想使用paddle中类似的lstm_api。
```
lstm = tf.contrib.cudnn_rnn.CudnnLSTM(
            num_layers=num_layers,
            num_units=rnn_size,
            input_mode="linear_input",
            direction="bidirectional",
            dropout=1 - keep_prob)
```

抱歉。 我没注意还有一位版本号，我使用了1.84这个版本，不知道是不是最新版本？我在aistudio上使用这个lstm api依然无法返回正确结果, 您的意思是在1.8所有版本这个api依然都存在问题吗？   
我测试的情况： https://aistudio.baidu.com/aistudio/projectdetail/913586
![image](https://user-images.githubusercontent.com/24267883/92989793-69fe3680-f509-11ea-9133-9cca0fd1cf4f.png)

**Comment by guoshengCS** [comment]
> 在1.8所有版本这个api依然都存在问题吗？

是的。如果希望加上dropout的话可以参考这里 https://github.com/PaddlePaddle/models/blob/release/1.8/PaddleNLP/seq2seq/seq2seq/base_model.py#L32

**Comment by wu8320175** [comment]
好的，刚刚已经尝试了。非常感谢！
