### ISSUE TITLE
Windows python2.7安装paddle develop有个报错。 Microsoft Visual C++ 9.0 is required

### ISSUE THREAD

**Issue by DDDivano** [PaddlePaddle/Paddle#27253]
报错信息。
error: Microsoft Visual C++ 9.0 is required (Unable to find vcvarsall.bat). Get it from http://aka.ms/vcpython27
影响：
只会在windows  python2.7 出现。导致paddle安装失败

应为最新版本的paddle 包含了netifaces，安装这个依赖的时候，引发了这个错误。解决方案是去https://www.microsoft.com/en-us/download/confirmation.aspx?id=44266 下载一个微软支持 python2.7 的一个编译器。由于这个网站下载很慢，我们是不是可以考虑在官网上Q&A或者哪里给出这个在bos上的连接，协助用户解决问题？

**Comment by zhwesky2010** [comment]
已经加了文档，后面说明，后面会去除Windows上的这个依赖
