### ISSUE TITLE
mkldnn 多线程多次推理导致内存泄露，内存阶跃是增长

### ISSUE THREAD

**Issue by zhouyongxyz** [PaddlePaddle/Paddle#27252]
使用Paddle C++ 对 Paddle OCR 进行推理，发现设置MKLDNN 之后，多次对图像进行推理内存会一直增加，阶跃增加。
PaddleOCR 文档中也提到这个问题，该问题看前面有 @luotao1 解决过mkl memory leak 问题，但是我测试了目前的develop 版本
还是存在这个问题。

**Comment by baiyfbupt** [comment]
建议使用1.8.4版本的Paddle, 最新develop分支的PaddleOCR
并且设置use_zero_copy_run参数为False，这样应该可以解决这个问题
https://github.com/PaddlePaddle/PaddleOCR/blob/967115b8e9dee3e36e9451c6a65b5cda2d8e4bc8/deploy/cpp_infer/tools/config.txt#L7

**Comment by zhouyongxyz** [comment]
use_zero_copy_run 是设置成 false 还是 true，看paddleocr 的提交是 true为了解决内存泄露问题。但是我实测两个在多线程中依旧存在内存泄露问题。https://github.com/PaddlePaddle/PaddleOCR/issues/706 这样的改动就会

**Comment by LDOUBLEV** [comment]
use_zero_copy_run 设置为False

**Comment by zhouyongxyz** [comment]
实际测试的时候，如果只是单纯的线程里循环好像没有泄露。但是配合cpp-httplib 这个c++库从http 调过来，多调用几次就会出现内存一直在增加，取消mkldnn 就没有问题。

**Comment by zhouyongxyz** [comment]
> use_zero_copy_run 设置为False

实际测试了，就是paddleocr 官方的测试代码，https://github.com/PaddlePaddle/PaddleOCR/tree/develop/deploy/cpp_infer 里面，只要不停的更换推理的图片，就会发现内存一直在涨
![image](https://user-images.githubusercontent.com/11956180/93168779-41b74780-f756-11ea-9060-524b58b0fd37.png)

**Comment by luotao1** [comment]
请参考 https://github.com/PaddlePaddle/PaddleOCR/issues/429#issuecomment-665423728 ，同时不要使用ZeroCopyRun接口，使用Run接口即可。

**Comment by zhouyongxyz** [comment]
目前实测是有效果的，内存可以控制住了。多谢多谢

> 请参考 [PaddlePaddle/PaddleOCR#429 (comment)](https://github.com/PaddlePaddle/PaddleOCR/issues/429#issuecomment-665423728) ，同时不要使用ZeroCopyRun接口，使用Run接口即可。
