### ISSUE TITLE
release/1.8编译失败

### ISSUE THREAD

**Issue by python-bookworm** [PaddlePaddle/Paddle#27261]
-- Found Paddle host system: ubuntu, version: 18.04.5
-- Found Paddle host system's CPU: 6 cores
-- The CXX compiler identification is GNU 7.5.0
-- The C compiler identification is GNU 7.5.0
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- CXX compiler: /usr/bin/c++, version: GNU 7.5.0
-- C compiler: /usr/bin/cc, version: GNU 7.5.0
-- AR tools: /usr/bin/ar
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Found Git: /usr/bin/git (found version "2.17.1") 
-- Performing Test MMX_FOUND
-- Performing Test MMX_FOUND - Success
-- Performing Test SSE2_FOUND
-- Performing Test SSE2_FOUND - Success
-- Performing Test SSE3_FOUND
-- Performing Test SSE3_FOUND - Success
-- Performing Test AVX_FOUND
-- Performing Test AVX_FOUND - Success
-- Performing Test AVX2_FOUND
-- Performing Test AVX2_FOUND - Success
-- Performing Test AVX512F_FOUND
-- Performing Test AVX512F_FOUND - Failed
-- BOOST_VERSION: 1.41.0, BOOST_URL: http://paddlepaddledeps.bj.bcebos.com/boost_1_41_0.tar.gz
-- warp-ctc library: /home/rex-han/下载/Paddle/build/third_party/install/warpctc/lib/libwarpctc.so
-- Download dependence[cudaerror] from http://paddlepaddledeps.bj.bcebos.com/cudaErrorMessage.tar.gz
-- MKLML_VER: csrmm2_mklml_lnx_2019.0.2, MKLML_URL: http://paddlepaddledeps.bj.bcebos.com/csrmm2_mklml_lnx_2019.0.2.tgz
-- Found cblas and lapack in MKLML (include: /home/rex-han/下载/Paddle/build/third_party/install/mklml/include, library: /home/rex-han/下载/Paddle/build/third_party/install/mklml/lib/libmklml_intel.so)
-- Set /home/rex-han/下载/Paddle/build/third_party/install/mkldnn/llib to runtime path
-- Build MKLDNN with MKLML /home/rex-han/下载/Paddle/build/third_party/install/mklml
-- MKLDNN library: /home/rex-han/下载/Paddle/build/third_party/install/mkldnn/lib/libdnnl.so
-- Protobuf protoc executable: /home/rex-han/下载/Paddle/build/third_party/install/protobuf/bin/protoc
-- Protobuf-lite library: /home/rex-han/下载/Paddle/build/third_party/install/protobuf/lib/libprotobuf-lite.a
-- Protobuf library: /home/rex-han/下载/Paddle/build/third_party/install/protobuf/lib/libprotobuf.a
-- Protoc library: /home/rex-han/下载/Paddle/build/third_party/install/protobuf/lib/libprotoc.a
-- Protobuf version: 3.1.0
-- Found PythonInterp: /usr/bin/python2.7 (found suitable version "2.7.17", minimum required is "2.7") 
CMake Error at /usr/share/cmake-3.10/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find PythonLibs (missing: PYTHON_LIBRARIES PYTHON_INCLUDE_DIRS)
  (Required is at least version "2.7")
Call Stack (most recent call first):
  /usr/share/cmake-3.10/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake-3.10/Modules/FindPythonLibs.cmake:262 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  cmake/external/python.cmake:18 (FIND_PACKAGE)
  cmake/third_party.cmake:240 (include)
  CMakeLists.txt:156 (include)

-- Configuring incomplete, errors occurred!
See also "/home/rex-han/下载/Paddle/build/CMakeFiles/CMakeOutput.log".
See also "/home/rex-han/下载/Paddle/build/CMakeFiles/CMakeError.log".

按照官网教程，报错如上，-- Performing Test AVX512F_FOUND - Failed  和  Could NOT find PythonLibs (missing: PYTHON_LIBRARIES PYTHON_INCLUDE_DIRS)  求解，谢谢

**Comment by baiyfbupt** [comment]
编译失败主要源于`Could NOT find PythonLibs (missing: PYTHON_LIBRARIES PYTHON_INCLUDE_DIRS)`这个报错，可以找下本机的Python环境路径，然后参考下面的-D选项在cmake时配置Python路径
cmake .. -D PYTHON_LIBRARIES=/usr/lib/libpython2.7.a -D PYTHON_INCLUDE_DIRS=/usr/include/
