### ISSUE TITLE
paddle release/1.2 编译失败

### ISSUE THREAD

**Issue by python-bookworm** [PaddlePaddle/Paddle#27260]
-- Found Paddle host system: ubuntu, version: 18.04.5
-- Found Paddle host system's CPU: 6 cores
-- CXX compiler: /usr/bin/c++, version: GNU 7.5.0
-- C compiler: /usr/bin/cc, version: GNU 7.5.0
-- MKLML_VER: mklml_lnx_2019.0.20180710, MKLML_URL: http://paddlepaddledeps.cdn.bcebos.com/mklml_lnx_2019.0.20180710.tgz
-- Protobuf protoc executable: /home/rex-han/下载/Paddle/build/third_party/install/protobuf/bin/protoc
-- Protobuf-lite library: /home/rex-han/下载/Paddle/build/third_party/install/protobuf/lib/libprotobuf-lite.a
-- Protobuf library: /home/rex-han/下载/Paddle/build/third_party/install/protobuf/lib/libprotobuf.a
-- Protoc library: /home/rex-han/下载/Paddle/build/third_party/install/protobuf/lib/libprotoc.a
-- Protobuf version: 3.1
-- Could NOT find PythonLibs (missing: PYTHON_LIBRARIES PYTHON_INCLUDE_DIRS) (Required is at least version "2.7")
-- Could NOT find PY_pip (missing: PY_PIP) 
CMake Error at cmake/python_module.cmake:27 (message):
  python module pip is not found
Call Stack (most recent call first):
  cmake/external/python.cmake:72 (find_python_module)
  CMakeLists.txt:196 (include)

-- Configuring incomplete, errors occurred!
See also "/home/rex-han/下载/Paddle/build/CMakeFiles/CMakeOutput.log".
See also "/home/rex-han/下载/Paddle/build/CMakeFiles/CMakeError.log".

ubuntu18.04 GPU cuda10.0+cudnn7.5 编译时候报错

**Comment by baiyfbupt** [comment]
同 https://github.com/PaddlePaddle/Paddle/issues/27261
