### ISSUE TITLE
paddle1.8.4使用amp混合精度训练报错ValueError: var lod_tensor_blocking_queue_0 not in this block，使用float32训练没有问题

### ISSUE THREAD

**Issue by Weili-NLP** [PaddlePaddle/Paddle#27265]
PaddlePaddle1.8.4，cuda10.1，cudnn7.4，V100 32g，python3.7.4

报错信息如下：
![image](https://user-images.githubusercontent.com/25901705/92904912-d15aae80-f455-11ea-906c-dcf7654c30e6.png)

**Comment by baiyfbupt** [comment]
可以排查下这个var是否不在global_block中。
program中可能有多个block，这个var在一些其他block中导致找不到。因为目前amp只能对global block中的OP做处理，这种情况会引起出错

**Comment by Cppowboy** [comment]
我也遇到同样的问题，请问后来解决了吗？
