### ISSUE TITLE
一维膨胀卷积问题

### ISSUE THREAD

**Issue by yuhangT** [PaddlePaddle/Paddle#27275]
在keras中的一维膨胀卷积（文本序列batch_size,max_sequence_len,word_size）是这样的：

![image](https://user-images.githubusercontent.com/49428064/92988768-1e478f00-f501-11ea-9434-bbe9a1dcdcb5.png)

我们转到paddlepaddle里边是这样实现的：

![image](https://user-images.githubusercontent.com/49428064/92988776-2e5f6e80-f501-11ea-93ac-dcfd2bd75abc.png)

请问这样转化有什么问题吗？因为实验结果有些误差，排除了其他方面，感觉可能是这膨胀卷积有问题

**Comment by LielinJiang** [comment]
感觉reshape的地方有点问题，我的理解这里想要交换数据格式（NLC->NCL,NCL->NC1L?）可以尝试使用transpose和unsqueeze

2.0rc版本已经实现了conv1d，可以参考这两个地方
https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/nn/layer/conv.py#L116
https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/nn/functional/conv.py#L99
