### ISSUE TITLE
In function `PaddleOCR::CRNNRecognizer::LoadModel error: ld returned 1 exit status

### ISSUE THREAD

**Issue by li829** [PaddlePaddle/Paddle#27271]
为使您的问题得到快速解决，在建立Issue前，请您先通过如下方式搜索是否有相似问题:【搜索issue关键字】【使用labels筛选】【官方文档】

建立issue时，为快速解决问题，请您根据使用情况给出如下信息：
- 标题：ubuntu 16.04 c++demo
- 版本、环境信息：
    1）PaddlePaddle版本：预测版1.8.4
    2）CPU：i5
    3）GPU：1060TI，CUDA-10.0和CUDNN-7.6
    4）系统环境：ubuntu16.04
注：您可以通过执行[summary_env.py](https://github.com/PaddlePaddle/Paddle/blob/develop/tools/summary_env.py)获取以上信息。
- 安装方式信息：
- 复现信息：paddle采用官网下载的直接安装版， 预测版1.8.4
- 问题描述：在sh build.sh编译到100%时，链接库报错：
CMakeFiles/ocr_system.dir/src/ocr_det.cpp.o: In function `PaddleOCR::DBDetector::LoadModel(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)':
/home/liyuewen/code1/ocr_c++/src/ocr_det.cpp:21: undefined reference to `paddle::AnalysisConfig::SetModel(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
CMakeFiles/ocr_system.dir/src/ocr_rec.cpp.o: In function `PaddleOCR::CRNNRecognizer::LoadModel(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)':
/home/liyuewen/code1/ocr_c++/src/ocr_rec.cpp:121: undefined reference to `paddle::AnalysisConfig::SetModel(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
collect2: error: ld returned 1 exit status

**Comment by littletomatodonkey** [comment]
可以提供下build.sh的详细配置信息吗？看着像是没有找到对应的预测库

**Comment by li829** [comment]
这个问题我解决了，原因可能是官方下载的直接安装那个包不能在我的主机环境下用，需要从源码重新在自己的主机上编译一遍才能用。
