### ISSUE TITLE
c++ 预测报错

### ISSUE THREAD

**Issue by yunmi** [PaddlePaddle/Paddle#27276]
--------------------------------------------
C++ Call Stacks (More useful to developers):
--------------------------------------------
0   std::string paddle::platform::GetTraceBackString<std::string const&>(std::string const&, char const*, int)
1   paddle::operators::FusionRepeatedFCReluOp::InferShape(paddle::framework::InferShapeContext*) const
2   paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, paddle::platform::Place const&, paddle::framework::RuntimeContext*) const
3   paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, paddle::platform::Place const&) const
4   paddle::framework::OperatorBase::Run(paddle::framework::Scope const&, paddle::platform::Place const&)
5   paddle::framework::NaiveExecutor::Run()
6   paddle::AnalysisPredictor::Run(std::vector<paddle::PaddleTensor, std::allocator<paddle::PaddleTensor> > const&, std::vector<paddle::PaddleTensor, std::allocator<paddle::PaddleTensor> >*, int)

----------------------
Error Message Summary:
----------------------
InvalidArgumentError: The length of Bias must be equal with w_dims[1], but received product(b_dims[1]) = 128, w_dims[1][1] = 132.
  [Hint: Expected framework::product(b_dims[i]) == w_dims[i][1], but received framework::product(b_dims[i]):128 != w_dims[i][1]:132.] at (/tmp/paddlepaddle/Paddle/paddle/fluid/operators/fused/fusion_repeated_fc_relu_op.cc:77)

**Comment by Shixiaowei02** [comment]
你好，从报错上看是 FC 层的输入不合法。请检查模型输入尺寸，并尝试设置 `switch_ir_optim=false` 看问题是否修复，谢谢。

**Comment by yunmi** [comment]
在c++预测中将model_config.SwitchIrOptim() 改为model_config.SwitchIrOptim(false) 可解决此问题；
可以说明一下原理么，如果想保持使用switch_ir_optim=true是需要在训练模型时增加配置么？

**Comment by Shixiaowei02** [comment]
> 在c++预测中将model_config.SwitchIrOptim() 改为model_config.SwitchIrOptim(false) 可解决此问题；
> 可以说明一下原理么，如果想保持使用switch_ir_optim=true是需要在训练模型时增加配置么？

IR Optimization 代指计算图融合和优化步骤，正常情况下开关此选项得到的预测结果应该一致。不一致的情况看起来应该是预测图优化的某个步骤暂时不适用此模型，需要我们复现后修复此问题。如果方便麻烦提供一下模型地址，谢谢！

**Comment by yunmi** [comment]
暂时未遇到预测不一致的情况~ 只是 switch_ir_optim=true时无法预测，如之前回答已通过model_config.SwitchIrOptim(false) 解决~

**Comment by xcgworker** [comment]
我也遇到了这个问题，执行
 config->SwitchIrOptim(false); 
就可以了。

**Comment by xcgworker** [comment]
我是静态图转动态图后保存的结果，预测就报这个错。
python中执行这个静态图没有问题，只有C++中才有这个问题。
模型就是resnet50vd_10w 的模型取前面一小部分后转静态图保存的。
[resnet50vd_sub_0.tar.gz](https://github.com/PaddlePaddle/Paddle/files/5648458/resnet50vd_sub_0.tar.gz)

**Comment by xcgworker** [comment]
> > 在c++预测中将model_config.SwitchIrOptim() 改为model_config.SwitchIrOptim(false) 可解决此问题；
> > 可以说明一下原理么，如果想保持使用switch_ir_optim=true是需要在训练模型时增加配置么？
> 
> IR Optimization 代指计算图融合和优化步骤，正常情况下开关此选项得到的预测结果应该一致。不一致的情况看起来应该是预测图优化的某个步骤暂时不适用此模型，需要我们复现后修复此问题。如果方便麻烦提供一下模型地址，谢谢！

我上面提供的附件看你有没有用。

**Comment by xcgworker** [comment]
> > 在c++预测中将model_config.SwitchIrOptim() 改为model_config.SwitchIrOptim(false) 可解决此问题；
> > 可以说明一下原理么，如果想保持使用switch_ir_optim=true是需要在训练模型时增加配置么？
> 
> IR Optimization 代指计算图融合和优化步骤，正常情况下开关此选项得到的预测结果应该一致。不一致的情况看起来应该是预测图优化的某个步骤暂时不适用此模型，需要我们复现后修复此问题。如果方便麻烦提供一下模型地址，谢谢！

我上面提供的附件看有没有用。
