### ISSUE TITLE
`cc_binary` and `cc_library` cannot link  dependencies of dependendency

### ISSUE THREAD

**Issue by reyoung** [PaddlePaddle/Paddle#2728]
The demo code is [here](https://github.com/PaddlePaddle/Paddle/pull/2726).

The issues are

* `lib_b` depends on lib_a.
* if a binary only depends on `lib_b`, that binary cannot link `lib_a` implicitly. We must declare the lib_a is also a dependency of that binary.

Should we make `cc_binary` and `cc_library` can lik the dependencies of dependency or not?

I think it is a little bit complex to implement this feature. Because it should handle `diamond dependence` problem and `circle dependence` problem

But if we do not implement this feature, the final binary of paddle should be very complex to write. Like

```cmake
cc_binary(final_bin SRC final_bin_main.cc DEPS A B C D E ....) // a lot deps.
```

**Comment by wangkuiyi** [comment]
I confirm I noticed this problem too.

@gangliao knows more about the dependency propagation mechanism of CMake.  The current generic.cmake is using this mechanism.

**Comment by reyoung** [comment]
@gangliao 

Maybe this [link](http://floooh.github.io/2016/01/12/cmake-dependency-juggling.html) is helpful. See the solution section.

It seems that invoke `target_link_libraries` to a static library could make cmake resolve dependencies correctly. It is silly since the static library does not actually link another. But it might be a solution to solve this problem.
