### ISSUE TITLE
在华为云Tesla T4 GPU的机器上,默认安装的是CUDA10.1,安装paddle-gpu后无法正常工作

### ISSUE THREAD

**Issue by TouyaAkira** [PaddlePaddle/Paddle#27295]
为使您的问题得到快速解决，在建立Issue前，请您先通过如下方式搜索是否有相似问题:【搜索issue关键字】【使用labels筛选】【官方文档】

建立issue时，为快速解决问题，请您根据使用情况给出如下信息：
- 标题：请包含关键词“安装错误”/“编译错误”，例如“Mac编译错误”
- 版本、环境信息：
    1）PaddlePaddle版本：请提供您的PaddlePaddle版本号1.8.4.post107
    2）CPU：Intel SkyLake 6151 3.0GHz 8核
    3）GPU：Tesla T4，CUDA10.1和CUDNN7.6.5
    4）系统环境：CentOS7、Python3.7.7(使用conda安装)
华为云镜像名称:CentOS 7.5 64bit with Tesla Driver 418.67 and Cuda 10.1
安装Anaconda最新版,然后运行:
conda create -n paddle python=3.7.7
conda activate paddle
conda install paddlepaddle-gpu
默认会安装cudnn7.6.5 + cuda10.0(和系统上原来的cuda10.1不一致,造成冲突)
(paddle) [root@dplearning tools]# nvidia-smi
NVIDIA-SMI has failed because it couldn't communicate with the NVIDIA driver. Make sure that the latest NVIDIA driver is installed and running.
这里本来是显示cuda10.1安装正常的,问题就是,在已经安装有cuda10.1的机器上,到底怎么安装paddlepaddle?到底是否支持?底层要做什么事情?

**Comment by TouyaAkira** [comment]
在conda install paddlepaddle-gpu之前
****************************************
Paddle version: None
Paddle With CUDA: None

OS: CentOS Linux 7.8.2003
Python version: 3.7.7

CUDA version: None
cuDNN version: None.None.None
Nvidia driver version: 418.67
****************************************
然后运行:conda install paddlepaddle-gpu cudnn=7.6.5 cudatoolkit=10.1
报错信息如下:
Package cudnn conflicts for:
paddlepaddle-gpu -> cudnn[version='>=7.3,<7.4|>=7.6,<7.7']
cudnn=7.6.5

Package libstdcxx-ng conflicts for:
cudnn=7.6.5 -> cudatoolkit[version='>=10.2,<10.3'] -> libstdcxx-ng[version='>=7.3.0']
paddlepaddle-gpu -> graphviz -> libstdcxx-ng[version='>=7.2.0|>=7.3.0']
python=3.7.7 -> libffi[version='>=3.2.1,<3.3a0'] -> libstdcxx-ng[version='>=7.2.0']
python=3.7.7 -> libstdcxx-ng[version='>=7.3.0']

Package cudatoolkit conflicts for:
cudatoolkit=10.1
paddlepaddle-gpu -> cudatoolkit[version='>=10.0,<10.1|>=9.0,<9.1']
paddlepaddle-gpu -> cudnn[version='>=7.6,<7.7'] -> cudatoolkit[version='10.0.*|9.0.*|>=10.1,<10.2|>=9.2,<9.3|>=10.2,<10.3|9.2.*']The following specifications were found to be incompatible with your CUDA driver:

  - feature:/linux-64::__cuda==10.1=0
  - feature:|@/linux-64::__cuda==10.1=0

Your installed CUDA driver is: 10.1

应该怎么安装paddle?是否paddle就不支持cuda10.1??

**Comment by DDDivano** [comment]
https://www.paddlepaddle.org.cn/documentation/docs/zh/install/install_Conda.html

![image](https://user-images.githubusercontent.com/10734244/93169339-7a0b5580-f757-11ea-85d2-332339e080f1.png)

**Comment by phlrain** [comment]
目前paddle还未支持cuda10.1

conda activate 之后nvidia-smi错误的问题，能否帮忙确认下，diactivate之后，是不是正常

**Comment by TouyaAkira** [comment]
已经解决了,Paddle没问题,实际上我已经安装了CUDA11的驱动,然后在安装paddle的时候,仍可以用cudatookkit10.2的版本
nvidia-smi
Thu Apr 22 12:40:28 2021       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.32.03    Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:21:01.0 Off |                    0 |
| N/A   42C    P0    26W /  70W |   1270MiB / 15109MiB |      0%      Default |
|                               |                      |                  N/A |

CUDA version11.2,但runtime版本10.2,不冲突,谢谢!
