### ISSUE TITLE
关于自定义SSIM图像相似性指标的问题

### ISSUE THREAD

**Issue by Preston-Dong** [PaddlePaddle/Paddle#27297]

**Comment by Preston-Dong** [comment]
我用skimage以及python版本的ssim算出来0.4左右，用这个自己写的直接就0.99了……想请大佬帮忙看看，万分感谢

**Comment by Aurelius84** [comment]
是否是guassian生成的windows有差别呢？

**Comment by Preston-Dong** [comment]
> 是否是guassian生成的windows有差别呢？

emmm，我看看哈

**Comment by Preston-Dong** [comment]
> > 是否是guassian生成的windows有差别呢？
> 
> emmm，我看看哈

多谢呀，我把生成的高斯核换了，得到了一个正确的结果

**Comment by Preston-Dong** [comment]
您好！不知道大佬还在不在，关于自己写的SSIM评价指标，我用1-ssim()做损失函数，在训练过程中出现了负值，也有超过1的，实在是不知道哪儿再能改进了，想请教请教！万分感激

**Comment by Preston-Dong** [comment]
> 是否是guassian生成的windows有差别呢？

您好！不知道大佬还在不在，关于自己写的SSIM评价指标，我用1-ssim()做损失函数，在训练过程中出现了负值，也有超过1的，实在是不知道哪儿再能改进了，想请教请教！万分感激

**Comment by Aurelius84** [comment]
> 在训练过程中出现了负值，

这个是loss出现了负值？可能需要检查一下什么样图片数据导致了`1-ssim()`出现了负值和大于1的情况。可能是你的计算公式有一些问题，导致`ssim()`的值不是[0,1]之间。
