### ISSUE TITLE
SgdLocalUpdater support L1 weight decay.

### ISSUE THREAD

**Issue by backyes** [PaddlePaddle/Paddle#273]
Optional solutions:
- Bugfix:  if l1 is used, do not use SgdLocalUpdater.
- remove SgdLocalUpdater.
- enable SgdLocalUpdater support parameter-level optimizater.

@backyes

**Comment by wangkuiyi** [comment]
@backyes 请说明：

1. 为什么需要" L1 weight decay for SGDLocalUpdater“？
1. 如果确实需要，应该如何支持。

根据这些信息，我们才能理性判断下一步的处理方式，比如放进哪个 milestone里。

**Comment by backyes** [comment]
@wangkuiyi 

这个问题来自https://github.com/baidu/Paddle/issues/267 衍生出来，属于增强实现。
由于历史原因，SGDLocalUpdater仅支持不支持parameter level的optimization 算法，故不支持parameter level L1 weight。 
上面的comments已经给出可选解决方法提纲思路，详细思路需要coder review后确定。

**Comment by qingqing01** [comment]
The [`SgdThreadUpdater`](https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/api/ParameterUpdater.cpp#L30) for local training and [`RemoteParameterUpdater`](https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/api/ParameterUpdater.cpp#L50) for cluster training are used in Python API.  The `SgdLocalUpdater` is not used now. So close this issue, if any questions, we will fix it the new issue.
