### ISSUE TITLE
安装paddle报错

### ISSUE THREAD

**Issue by zcswdt** [PaddlePaddle/Paddle#27338]
您好，我在本地docker环境下根据paddle镜像，启动了一个容器，接着按照文档安装了paddle，但是在运行进入python解释器，然后输入import paddle.fluid和paddle.fluid.install_check.run_check()会报错。如下：
![image](https://user-images.githubusercontent.com/43515926/93283729-b5fbf480-f803-11ea-891c-987b2c7eddd7.png)

如下操作是我启动docker容器的命令：
![image](https://user-images.githubusercontent.com/43515926/93283787-d166ff80-f803-11ea-95d0-64b4dfce1502.png)
![image](https://user-images.githubusercontent.com/43515926/93283806-d88e0d80-f803-11ea-85d6-739c8ed33e9f.png)

这个是我本地的驱动版本和cuda版本：
![image](https://user-images.githubusercontent.com/43515926/93283855-ee9bce00-f803-11ea-8a88-09d3a330bd65.png)

**Comment by lfchener** [comment]
你可以先尝试以下这几种解决方案：
![image](https://user-images.githubusercontent.com/6771821/93287327-ce700d00-f80b-11ea-8b6a-a3e79968d7a1.png)

**Comment by LDOUBLEV** [comment]
link: https://github.com/PaddlePaddle/PaddleOCR/issues/703

**Comment by tianshuo78520a** [comment]
请问你用的是Paddle官网提供的镜像么？感觉是nccl没有装上

**Comment by zcswdt** [comment]
> 请问你用的是Paddle官网提供的镜像么？感觉是nccl没有装上

对，用的是官方镜像直接装的，如下是我的安装命令。
nvidia-docker run --name ppocr -v $PWD:/paddle --network=host -it hub.baidubce.com/paddlepaddle/paddle:latest-gpu-cuda10.0-cudnn7-dev /bin/bash

**Comment by tianshuo78520a** [comment]
用的Paddle版本是？

**Comment by zcswdt** [comment]
> 用的Paddle版本是？

上面发的有我具体安装步骤，
![image](https://user-images.githubusercontent.com/43515926/93290316-03339280-f813-11ea-8dae-00f05cd98fc3.png)

**Comment by tianshuo78520a** [comment]
你可以试下1.8.4版本，RTX 型号GPU 暂时没有环境测试，或者你可以使用V100或者P40显卡

**Comment by zcswdt** [comment]
> 你可以试下1.8.4版本，RTX 型号GPU 暂时没有环境测试，或者你可以使用V100或者P40显卡

您好，谢谢悉心指导哈。第一、关于1.8.4版本的，昨天有你们的技术人员叫我下载了，升级以后还是报错的。
![image](https://user-images.githubusercontent.com/43515926/93297460-dcca2300-f823-11ea-84a4-1f9aab458fdd.png)

![image](https://user-images.githubusercontent.com/43515926/93297639-42b6aa80-f824-11ea-8be7-51dd4d8b39dc.png)

第二、对于显卡问题，这个是硬件条件了，不太好改变。对于RTX显卡，也是英伟达的显卡啊，而且我觉得用这个型号显卡的人不在少数啊，RTX2080TI或者是低版本的的，基本上都是标配啊。

**Comment by tianshuo78520a** [comment]
1.先确认所有卡的显存没有被占用，我看截图卡1已经使用了
![image](https://user-images.githubusercontent.com/29832297/93298418-c9b85280-f825-11ea-8b11-40f4d3af4325.png)

2.设置export CUDA_VISIBLE_DEVICES=0，使用单卡执行看下是否还会报错？

**Comment by phlrain** [comment]
能看下你的nccl版本么，paddle支持的nccl版本是>=247

**Comment by zcswdt** [comment]
> export CUDA_VISIBLE_DEVICES=0

1显卡被人占用了，不过我没有跑模型训练哎，只是输入import paddle.fluid 和  paddle.fluid.install_check.run_check()
这两个命令。就报错。

**Comment by zcswdt** [comment]
> 能看下你的nccl版本么，paddle支持的nccl版本是>=247

请教一下，这个查看nccl版本如何查看？

**Comment by phlrain** [comment]
> > 能看下你的nccl版本么，paddle支持的nccl版本是>=247
> 
> 请教一下，这个查看nccl版本如何查看？

如果是我们的官方docker， 可以通过 ll /usr/lib/x86_64-linux-gnu/libnccl.so* 看下编号

同时也检查下，你的机器的1号卡 被什么别的资源占用了，可以尝试kill掉进程，释放资源

**Comment by zcswdt** [comment]
> ll /usr/lib/x86_64-linux-gnu/libnccl.so*

![image](https://user-images.githubusercontent.com/43515926/93303596-56670e80-f82e-11ea-8e7f-ef2eaad6724a.png)
我的1号x显卡别人在训练模型，目前不太好杀掉。要不，我单独只用0号显卡启一个容器？这样就只要0号这一个显卡了。

**Comment by zcswdt** [comment]
> > ll /usr/lib/x86_64-linux-gnu/libnccl.so*
> 
> ![image](https://user-images.githubusercontent.com/43515926/93303596-56670e80-f82e-11ea-8e7f-ef2eaad6724a.png)
> 我的1号显显卡别人在训练模型，目前不太好杀掉。要不，我单独只用0号显卡启一个容器？这样就只有0号这一个显卡了。

**Comment by zcswdt** [comment]
> > > ll /usr/lib/x86_64-linux-gnu/libnccl.so*

> > ![image](https://user-images.githubusercontent.com/43515926/93303596-56670e80-f82e-11ea-8e7f-ef2eaad6724a.png)
> > 我的1号显显卡别人在训练模型，目前不太好杀掉。要不，我单独只用0号显卡启一个容器？这样就只有0号这一个显卡了。

**Comment by zcswdt** [comment]
> > > > ll /usr/lib/x86_64-linux-gnu/libnccl.so*

 ![image](https://user-images.githubusercontent.com/43515926/93303596-56670e80-f82e-11ea-8e7f-ef2eaad6724a.png)
 我的1号显显卡别人在训练模型，目前不太好杀掉。要不，我单独只用0号显卡启一个容器？这样就只有0号这一个显卡了。

**Comment by zcswdt** [comment]
> > > > ll /usr/lib/x86_64-linux-gnu/libnccl.so*

 ![image](https://user-images.githubusercontent.com/43515926/93303596-56670e80-f82e-11ea-8e7f-ef2eaad6724a.png)
 我的1号显显卡别人在训练模型，目前不太好杀掉。要不，我单独只用0号显卡启一个容器？这样就只有0号这一个显卡了。

**Comment by phlrain** [comment]
> > > > > ll /usr/lib/x86_64-linux-gnu/libnccl.so*
> 
> ![image](https://user-images.githubusercontent.com/43515926/93303596-56670e80-f82e-11ea-8e7f-ef2eaad6724a.png)
> 我的1号显显卡别人在训练模型，目前不太好杀掉。要不，我单独只用0号显卡启一个容器？这样就只有0号这一个显卡了。

通过 CUDA_VISIBLE_DEVICES=0 设置下，只用一个卡跑任务就行了，run check失败是多卡的时候，一个卡被占用失败了，可以跑单卡的任务

**Comment by zcswdt** [comment]
> > > > > > ll /usr/lib/x86_64-linux-gnu/libnccl.so*
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/43515926/93303596-56670e80-f82e-11ea-8e7f-ef2eaad6724a.png)
> > 我的1号显显卡别人在训练模型，目前不太好杀掉。要不，我单独只用0号显卡启一个容器？这样就只有0号这一个显卡了。
> 
> 通过 CUDA_VISIBLE_DEVICES=0 设置下，只用一个卡跑任务就行了，run check失败是多卡的时候，一个卡被占用失败了，可以跑单卡的任务

您好，我刚才在我的另外一个服务器上进行了相同安装操作，最后在这个服务器上执行是可以用的。
![image](https://user-images.githubusercontent.com/43515926/93307853-1145db00-f834-11ea-8a39-97f9fd25aa33.png)
![image](https://user-images.githubusercontent.com/43515926/93307874-17d45280-f834-11ea-98aa-f910dc0bb785.png)
![image](https://user-images.githubusercontent.com/43515926/93307896-20c52400-f834-11ea-80fd-f9201e6c32b3.png)
这是我的T4显卡配置
![image](https://user-images.githubusercontent.com/43515926/93308318-b1036900-f834-11ea-98b8-c0ceb221b189.png)
