### ISSUE TITLE
Add support for INT8 quantization of fusion_gru op

### ISSUE THREAD

**Issue by wojtuss** [PaddlePaddle/Paddle#27330]
Please, enable INT8 quantization of the `fusion_gru` op using oneDNN-based INT8 kernel.

**Comment by wojtuss** [comment]
After enabling INT8 quantization of the fusion_gru op (a PR will be submitted soon) we achieved the following accuracy result for the QAT GRU model on a CLX 6248 (with VNNI support):

  | qat (fp32) | int8 | diff
-- | -- | -- | --
Precision | 0.89198 | 0.89221 | 0.00023
Recall | 0.89449 | 0.89412 | -0.00037
F1 score | 0.89323 | 0.89316 | -0.00007

**Comment by lidanqing-vv** [comment]
PR #27481  submitted

**Comment by wojtuss** [comment]
A support for INT8 quantization of the GRU model is added to Paddle. The only piece we are waiting to add here is a version of oneDNN with additional GRU INT8 optimizations. The upgrade of oneDNN will be submitted in the PR https://github.com/PaddlePaddle/Paddle/pull/28420.

**Comment by wojtuss** [comment]
The PR [#28420](https://github.com/PaddlePaddle/Paddle/pull/28420) is merged so the support for INT8 quantization of the GRU model is done.
