### ISSUE TITLE
训练设置不同学习率

### ISSUE THREAD

**Issue by ARDUJS** [PaddlePaddle/Paddle#27347]
### 环境
- python 3.7.5
- paddle 1.7.2
### 问题

> 我需要对一矩阵的某一列设置不同的学习率，求一demo， help

**Comment by lfchener** [comment]
建议你可以把这一列取出来作为一个单独的参数并指定学习率。

**Comment by ARDUJS** [comment]
您好，paddle有没提供取出一列的api

**Comment by lfchener** [comment]
https://www.paddlepaddle.org.cn/documentation/docs/zh/api_cn/layers_cn/slice_cn.html#slice
参考 slice，或者直接 a[:,0,:]

**Comment by ARDUJS** [comment]
我现在是LodTensor 变量，取某一列，是否需要pad后再取或者有啥骚操作
