### ISSUE TITLE
windows7, python2.7.18安装paddle出错。

### ISSUE THREAD

**Issue by ydchen9** [PaddlePaddle/Paddle#27361]
1）PaddlePaddle版本：根据官网给的安装语句安装的python -m pip install paddlepaddle -i https://pypi.tuna.tsinghua.edu.cn/simple
    2）CPU：请提供CPU型号。这在安装之前测试过，显示AMD64，符合官网说的安装要求。
    3）GPU：请提供GPU型号。无
    4）系统环境：win7、Python版本:2.7.18

具体出现的错误如下：
![1](https://user-images.githubusercontent.com/26667822/93332551-9640ec80-f854-11ea-8ac2-bc42f374195d.png)
![2](https://user-images.githubusercontent.com/26667822/93332565-993bdd00-f854-11ea-8106-2048161bde1c.png)
![4](https://user-images.githubusercontent.com/26667822/93332934-2e3ed600-f855-11ea-8288-6ae5b02f5e23.png)

请问paddle现在还能在python2.7上安装吗？

**Comment by ydchen9** [comment]
通过conda install paddlepaddle安装成功了。

**Comment by zhwesky2010** [comment]
2.7现在在Windows上还是支持的。
