### ISSUE TITLE
新版paddle的编码问题

### ISSUE THREAD

**Issue by fastback407** [PaddlePaddle/Paddle#2737]
配置如下：
################################### Data Configuration ###################################
TrainData(ProtoData(files = "train.list"))

################################### Algorithm Configuration ###################################

Settings(

)

################################### Network Configuration ###################################
Layer(type = "data", name = "spa", size = 334)
Layer(type = "data", name = "cont", size = 5479)

之前用的是1102，想问下，在新版的paddle上预测，该如何编码(c++)，用paddle_matrix_create_sparse吗？

**Comment by qingqing01** [comment]
如果输入类型是sparse类型，可以参考这个例子：https://github.com/PaddlePaddle/Paddle/tree/develop/paddle/capi/examples/model_inference/sparse_binary

**Comment by fastback407** [comment]
属于dense sparse 和 sequence的混合类型，该如何拼接？
