### ISSUE TITLE
AIStudio内存溢出

### ISSUE THREAD

**Issue by thailand88** [PaddlePaddle/Paddle#27374]
![图片](https://user-images.githubusercontent.com/29336122/93417962-d5fee700-f8db-11ea-94e3-3bc84a38d311.png)

**Comment by 123malin** [comment]
同issue https://github.com/PaddlePaddle/Paddle/issues/27373 , 可以提供一下复现环境链接吗？另外检查机器内存是否满足程序运行需要的内存，也可以尝试减小batch_size等方法。

**Comment by thailand88** [comment]
> 
> 
> 同issue #27373 , 可以提供一下复现环境链接吗？另外检查机器内存是否满足程序运行需要的内存，也可以尝试减小batch_size等方法。

是检测本机内存还是AIStudio的内存？
