### ISSUE TITLE
Each config can only be used for one predictor

### ISSUE THREAD

**Issue by ming5432ming** [PaddlePaddle/Paddle#27387]
之前1.7.2一直可以使用，现在重新bcloud local了一下，发现不能用了，报错如下：

data/fluid_models/face_segmentation/face_segmentation.conf start init !
WARNING: Logging before InitGoogleLogging() is written to STDERR
I0917 18:46:43.960003 25002 paddle_helper.h:246] init_paddlepredictor
I0917 18:46:43.960059 25002 paddle_helper.h:187] [date:Sep 17 2020][time:18:46:18][version:1.9.8.7][provider:vis-arch]
I0917 18:46:43.960070 25002 paddle_helper.h:200] paddle version: 1.8.0
commit: 0231f58e5
branch: HEAD
I0917 18:46:43.960119 25002 paddle_helper.h:203] [wiki: https://dwz.cn/jLej3OTv]
I0917 18:46:43.960135 25002 conf_parser.cpp:38] read_text_file!
I0917 18:46:43.960202 25002 paddle_helper.h:146] Predictor::init_model()
W0917 18:46:43.960275 25002 paddle_helper.h:294] fail to get specify_input_name from conf, set as false
I0917 18:46:43.960291 25002 paddle_helper.h:311] use gpu!
I0917 18:46:43.960307 25002 paddle_helper.h:98] Predictor::init_gpu()
W0917 18:46:43.960323 25002 conf_parser.cpp:167] fail to get: test_fluid_multiclass_gpu_memory_mb
W0917 18:46:43.960335 25002 paddle_helper.h:103] fail to get gpu_memory_mb from conf, set as 1024
W0917 18:46:43.960367 25002 conf_parser.cpp:202] fail to get: test_fluid_multiclass_infer_engine
W0917 18:46:43.960379 25002 paddle_helper.h:111] disable infer engine
W0917 18:46:43.960391 25002 conf_parser.cpp:202] fail to get: test_fluid_multiclass_delete_pass
W0917 18:46:43.960400 25002 conf_parser.cpp:202] fail to get: test_fluid_multiclass_append_pass
terminate called after throwing an instance of 'paddle::platform::EnforceNotMet'
  what():

--------------------------------------------
C++ Call Stacks (More useful to developers):
--------------------------------------------
0   std::string paddle::platform::GetTraceBackString<char const*>(char const*&&, char const*, int)
1   paddle::platform::EnforceNotMet::EnforceNotMet(std::__exception_ptr::exception_ptr, char const*, int)
2   std::unique_ptr<paddle::PaddlePredictor, std::default_delete<paddle::PaddlePredictor> > paddle::CreatePaddlePredictor<paddle::AnalysisConfig>(paddle::AnalysisConfig const&)

----------------------
Error Message Summary:
----------------------
Error: Note: Each config can only be used for one predictor. at (/home/scmbuild/workspaces_cluster.dev/baidu.lib.paddlepaddle/baidu/lib/paddlepaddle/Paddle/paddle/fluid/inference/api/analysis_predictor.cc:505)

**Comment by jiweibo** [comment]
每一个Config只能初始化一个Predictor，请确认下是不是多次用到了同一个Predictor。

可以参考demo样例  https://paddle-inference-dist.bj.bcebos.com/tensorrt_test/paddle_inference_sample_v1.7.tar.gz

**Comment by Colorfu1** [comment]
我也遇到了这个问题，检查过后没有使用多个config啊。我之前1.6+cuda8没出现过这个问题，但是换到cuda9就有了。不知道是不是TensorRT的问题。
