### ISSUE TITLE
paddle.fluid.layers.unfold op不支持输入feature的shape存在多个-1

### ISSUE THREAD

**Issue by rfdeng** [PaddlePaddle/Paddle#27397]
paddle.fluid.layers.unfold(x, kernel_size, strides=1, paddings=0, dilation=1, name=None)

unfolding层的第一个输入参数x，其shape不支持多个-1的描述方式。
对应代码及报错：
![image](https://user-images.githubusercontent.com/24435688/93570802-26eb0a00-f9c6-11ea-99de-e05af292593b.png)
![image](https://user-images.githubusercontent.com/24435688/93570819-2bafbe00-f9c6-11ea-986b-e73d29515b2f.png)
![image](https://user-images.githubusercontent.com/24435688/93570841-32d6cc00-f9c6-11ea-82ee-8fdbb9c7b60c.png)

第一次调用unfold时，对应输入的shape为 （-1， 6， 1024， 768）是没问题的。
第二次调用unfold时，对应输入的shape为（-1， 16， -1， -1）报错。

**Comment by lijianshe02** [comment]
op要根据输入的(h,w)计算输出shape, 肯定是不支持(h,w）为-1的
