### ISSUE TITLE
Error installing with pip on MacBook Pro

### ISSUE THREAD

**Issue by fanglicheng** [PaddlePaddle/Paddle#27390]
Clean installation on a MacBook Pro:

➜  speech_paddle_dy git:(master) ✗ python3 -m pip install paddle                                                                              
Defaulting to user installation because normal site-packages is not writeable
Collecting paddle
  Using cached paddle-1.0.2.tar.gz (579 kB)
    ERROR: Command errored out with exit status 1:
     command: /Library/Developer/CommandLineTools/usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/dr/h6vr7s1n6zzgv2nk__kplkhh0000gp/T/pip-install-zqc4q9x6/paddle/setup.py'"'"'; __file__='"'"'/private/var/folders/dr/h6vr7s1n6zzgv2nk__kplkhh0000gp/T/pip-install-zqc4q9x6/paddle/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/dr/h6vr7s1n6zzgv2nk__kplkhh0000gp/T/pip-pip-egg-info-2o0e7zsb
         cwd: /private/var/folders/dr/h6vr7s1n6zzgv2nk__kplkhh0000gp/T/pip-install-zqc4q9x6/paddle/
    Complete output (7 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/dr/h6vr7s1n6zzgv2nk__kplkhh0000gp/T/pip-install-zqc4q9x6/paddle/setup.py", line 3, in <module>
        import paddle
      File "/private/var/folders/dr/h6vr7s1n6zzgv2nk__kplkhh0000gp/T/pip-install-zqc4q9x6/paddle/paddle/__init__.py", line 5, in <module>
        import common, dual, tight, data, prox
    ModuleNotFoundError: No module named 'common'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by wangxicoding** [comment]
The package name is wrong.  You need install with `python3 -m pip install paddlepaddle`
More detail can see this https://www.paddlepaddle.org.cn/install/quick

**Comment by fanglicheng** [comment]
Thanks, I guess there's no version supporting Python 3.8 then? 

➜  speech_paddle_dy git:(master) ✗ python3 -m pip install paddlepaddle -i https://pypi.tuna.tsinghua.edu.cn/simple
Defaulting to user installation because normal site-packages is not writeable
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
ERROR: Could not find a version that satisfies the requirement paddlepaddle (from versions: none)
ERROR: No matching distribution found for paddlepaddle

**Comment by wangxicoding** [comment]
Thanks for your feedback. Paddle only supports Python 2.7.15+/3.5.1+/3.6/3.7 (64 bit) for now. Python3.8 support is already in the follow-up development plan.
