### ISSUE TITLE
在1.8.4版本动态图版本之中使用fluid.layers.conv2d报错

### ISSUE THREAD

**Issue by Costwen** [PaddlePaddle/Paddle#27394]
- 版本、环境信息
1）PaddlePaddle版本：1.8.4
2）CPU/GPU：GPU
3）系统环境：AiStudio

当在动态图版本之中使用
```py
fluid.layers.conv2d
```
或者
```
fluid.layers.conv2d_transpose
``` 
等方式的时候,在运行的时候会报错
但如果使用fluid.dygraph.Conv2D等方式就不会报错

报错提示 
Error: Cannot get attribute groups by type int ,its type is bool at(/paddle/paddle/fluid/framework/attribute.h:42)

这是因为在动态图中不支持使用静态图的api(需要计算梯度)

**Comment by wangxicoding** [comment]
是的，fluid.layers.conv2d是静态图API，不支持动态图。
另外paddle2.0beta版已发布https://github.com/PaddlePaddle/Paddle/releases ，动态图体验有较大提升，欢迎试用
