### ISSUE TITLE
jetson xavier nx安装paddlepaddle

### ISSUE THREAD

**Issue by shenyt-sanshui** [PaddlePaddle/Paddle#27402]
请问jetson xavier nx上可以直接安装paddlepaddle吗  
架构是64bit arrch64的，看到官网说不支持arm64的，但是不知道arrch64是否支持安装呢

**Comment by wangxicoding** [comment]
直接python安装吗？编译可以试试 https://www.paddlepaddle.org.cn/documentation/docs/zh/advanced_guide/inference_deployment/inference/build_and_install_lib_cn.html

**Comment by wangxicoding** [comment]
麻烦 @shangzhizhou 跟进一下~

**Comment by shangzhizhou** [comment]
可以编译安装，下面贴一下我们在jetpack4.3，jetson tx2上的编译过程，请参考一下
1.环境准备：
自测使用硬件jetson tx2，使用nvidia sdk manager 1.20刷机jetpack4.3（内置ubuntu18.04、python2.7、cuda10.0、cudnn7.6、tensorrt6.0）
2.编译：
  a）更改tensorrt头文件，解决因tensorrt导致的编译失败

     /usr/include/aarch64-linux-gnu/NvInferRuntime.h增加虚析构函数"virtual ~IPluginFactory() {}"

  b）删除python对opencv的依赖，jetson软件包内置opencv，且版本比paddle更新，删除依赖使用内置，也不降级jetson原有软件包。

   在python/requirements.txt中删除opencv-python<=4.2.0.32

 c）安装编译时需要的python包

   apt install python-pip

   pip install protobuf

   pip install patchelf

 d）编译

cmake .. \

  -DWITH_CONTRIB=OFF \

  -DWITH_MKL=OFF  \

  -DWITH_MKLDNN=OFF \

  -DWITH_TESTING=OFF \

  -DCMAKE_BUILD_TYPE=Release \

  -DWITH_XBYAK=OFF  \

  -DWITH_NCCL=OFF \

  -DWITH_NV_JETSON=ON

make

3.安装：

 a）安装python依赖   

   pip install setuptools

   pip install scikit-build

   #for scipy

   sudo apt-get install liblapack-dev

   sudo apt-get install gfortran

   #for pillow

   sudo apt-get install libfreetype6-dev

   sudo apt-get install libjpeg-dev

   sudo apt-get install libpng12-dev

 b）安装paddle

pip install -U ./python/dist/paddlepaddle_gpu-0.0.0-cp27-cp27mu-linux_x86_64.whl



4.使用：

python    ./python/paddle/fluid/tests/unittests/ir/inference/test_conv_elementwise_add_fuse_pass.py
可以验证组网、预测、tensorrt均可正常使用

**Comment by shenyt-sanshui** [comment]
> 可以编译安装，下面贴一下我们在jetpack4.3，jetson tx2上的编译过程，请参考一下
> 1.环境准备：
> 自测使用硬件jetson tx2，使用nvidia sdk manager 1.20刷机jetpack4.3（内置ubuntu18.04、python2.7、cuda10.0、cudnn7.6、tensorrt6.0）
> 2.编译：
> a）更改tensorrt头文件，解决因tensorrt导致的编译失败
> 
> ```
>  /usr/include/aarch64-linux-gnu/NvInferRuntime.h增加虚析构函数"virtual ~IPluginFactory() {}"
> ```
> 
> b）删除python对opencv的依赖，jetson软件包内置opencv，且版本比paddle更新，删除依赖使用内置，也不降级jetson原有软件包。
> 
> 在python/requirements.txt中删除opencv-python<=4.2.0.32
> 
> c）安装编译时需要的python包
> 
> apt install python-pip
> 
> pip install protobuf
> 
> pip install patchelf
> 
> d）编译
> 
> cmake .. \
> 
> -DWITH_CONTRIB=OFF \
> 
> -DWITH_MKL=OFF \
> 
> -DWITH_MKLDNN=OFF \
> 
> -DWITH_TESTING=OFF \
> 
> -DCMAKE_BUILD_TYPE=Release \
> 
> -DWITH_XBYAK=OFF \
> 
> -DWITH_NCCL=OFF \
> 
> -DWITH_NV_JETSON=ON
> 
> make
> 
> 3.安装：
> 
> a）安装python依赖
> 
> pip install setuptools
> 
> pip install scikit-build
> 
> #for scipy
> 
> sudo apt-get install liblapack-dev
> 
> sudo apt-get install gfortran
> 
> #for pillow
> 
> sudo apt-get install libfreetype6-dev
> 
> sudo apt-get install libjpeg-dev
> 
> sudo apt-get install libpng12-dev
> 
> b）安装paddle
> 
> pip install -U ./python/dist/paddlepaddle_gpu-0.0.0-cp27-cp27mu-linux_x86_64.whl
> 
> 4.使用：
> 
> python ./python/paddle/fluid/tests/unittests/ir/inference/test_conv_elementwise_add_fuse_pass.py
> 可以验证组网、预测、tensorrt均可正常使用

谢啦!
