### ISSUE TITLE
Torch的register_buffer在paddle有什么对应的API吗

### ISSUE THREAD

**Issue by whjdark** [PaddlePaddle/Paddle#27411]
Pytorch的register_buffer在paddle上如何实现？
![_G $0UILLU54PY4HI{VJ4JA](https://user-images.githubusercontent.com/44253501/93658628-e2b44400-fa6f-11ea-8ffd-44f5ae60d27e.png)

**Comment by qingqing01** [comment]
@whjdark 

在Paddle中，采用`self.create_parameter`，然后不需要训练的话，设置stop_gradient=True，可以参考BatchNorm中的写法:


https://github.com/PaddlePaddle/Paddle/blob/99626502f747cc85d518d87267cec821ffbf69a3/python/paddle/fluid/dygraph/nn.py#L1297-L1305
