### ISSUE TITLE
paddle bert输入问题

### ISSUE THREAD

**Issue by chaojiewang94** [PaddlePaddle/Paddle#27419]
bert中lodtensor输入
https://github.com/PaddlePaddle/models/blob/release/1.8/PaddleNLP/pretrain_language_models/BERT/model/classifier.py

您好，上面Bert的demo中src_ids 输入形状是(None,None),即Batch_size*Max_seq_len;
我想问的是既然输入定义是Lod tensor，那么Bert中的src_ids输入能不能和lstm里面的Lodtensor一样，把Batch_size维度和seq_lens维度合成到一个维度上面，这样就不需要对短句子进行padding了。

请问有这样做的吗，有类似的code可以参考吗，谢谢

lstm里面的lodtensor输入
https://github.com/baidu/information-extraction/blob/master/bin/p_classification/p_train.py

**Comment by luotao1** [comment]
@guoshengCS 可以帮忙看下这个问题么

**Comment by wds2014** [comment]
试了下将二维的List传到lodtensor里，第一维表示batch_size大小，第二维表示每篇文章的长度，注意第二维不一样长，报如下错误：
---------------------
"\n\tFaild to convert input data to a regular ndarray :\n\t* Usually "
----------------------

**Comment by guoshengCS** [comment]
> bert中lodtensor输入
https://github.com/PaddlePaddle/models/blob/release/1.8/PaddleNLP/pretrain_language_models/BERT/model/classifier.py

这个实现中并未使用和支持lodtensor，src_ids 输入形状`(None,None)`对应了`(batch_size, max_sequence_length_in_batch)`这样一个形状。

**Comment by chaojiewang94** [comment]
@guoshengCS 有使用lodtensor的Bert版本吗，还是说Bert必须要将输入padding成max_sequence_length_in_batch

**Comment by chaojiewang94** [comment]
@guoshengCS 还有就是，我看了src_ids的类型是lodtensor，lod_level是０；这边的lod_level是０，是不是表示它不是个lod_tensor?

**Comment by guoshengCS** [comment]
> 有使用lodtensor的Bert版本吗

这个目前没有

> 这边的lod_level是０，是不是表示它不是个lod_tensor

这个是这样的

**Comment by chaojiewang94** [comment]
@guoshengCS 谢谢你，最后一个问题，为啥没有lodtensor版本的Bert，理论上不成立，还是用了lodtensor后没法内部矩阵运算

**Comment by guoshengCS** [comment]
lodtensor在除了MultiHeadAttention部分都是可以的直接使用的，而MultiHeadAttention部分由于使用matmul（BatchedGEMM）这个要求batch维度和position维度分开。如果确实希望使用lodtensor的话也可以尝试在其他部分使用lodtensor，MultiHeadAttention前后进行[sequence_pad](https://www.paddlepaddle.org.cn/documentation/docs/zh/api_cn/layers_cn/sequence_pad_cn.html#sequence-pad)和[sequence_unpad](https://www.paddlepaddle.org.cn/documentation/docs/zh/api_cn/layers_cn/sequence_unpad_cn.html#sequence-unpad)进行lodtensor和tensor的转换。
