### ISSUE TITLE
fluid.layers.conv2d()中关于创建filter的问题

### ISSUE THREAD

**Issue by lyn1225** [PaddlePaddle/Paddle#27415]
pytorch中nn.functional.conv2d()方法支持创建形如[out_channels,in_channels,filter_height,filter_width]的filter。paddle中的fluid.layers.conv2d()的api中关于该方法的介绍也提到filter可以是一个列表。可是我在将创建好的filter参数传入该方法时，没有输出,程序一直卡在这里不能继续运行。想请教各位大神，我该如何解决。

**Comment by qingqing01** [comment]
`fluid.layers.conv2d()` 不支持传入filter。

paddle 2.0-beta中支持functional的写法，即传入filter。可以参考: https://www.paddlepaddle.org.cn/documentation/docs/zh/2.0-beta/api/paddle/nn/functional/conv/conv2d_cn.html#conv2d

您是动态图、还是静态图？ paddle版本是多少呢？

**Comment by lyn1225** [comment]
感谢你的回答。按照你给的链接，我安装了这个新的版本，可以使用。另外还有一个问题想请教一下，paddle发布的paddlecv库中提供了在线体验一些分割模型的项目，这些公开项目支持这个paddle 2.0-beta版本吗？

**Comment by lyn1225** [comment]
> `fluid.layers.conv2d()` 不支持传入filter。
> 
> paddle 2.0-beta中支持functional的写法，即传入filter。可以参考: https://www.paddlepaddle.org.cn/documentation/docs/zh/2.0-beta/api/paddle/nn/functional/conv/conv2d_cn.html#conv2d
> 
> 您是动态图、还是静态图？ paddle版本是多少呢？
