### ISSUE TITLE
Something about network input

### ISSUE THREAD

**Issue by Yuuuuuuuuuuuuuuuuuummy** [PaddlePaddle/Paddle#27417]
I noticed that, some dygraph demos in paddle2.0beta version just input nd.array class into the network. Does it have the difference between using to_variable() or to_tensor() to convert data and directly input ndarray ? If it does, what's the difference? Or which method should we use in paddle2.0beta. Thanks for your time and hope to get reply!

**Comment by luotao1** [comment]
> some dygraph demos in paddle2.0beta version just input nd.array class into the network

Could you give the URL of these dygraph demos?

**Comment by luotao1** [comment]
> some dygraph demos in paddle2.0beta version just input nd.array class into the network

`to_tensor` is an alias of `to_varaible`, and we should use to_variable() or to_tensor() to convert data, otherwise, there may be some error. (see #26116, )

Could you give the URL of these dygraph demos just input nd.array class into the network? We will have a check on it.

**Comment by Yuuuuuuuuuuuuuuuuuummy** [comment]
> > some dygraph demos in paddle2.0beta version just input nd.array class into the network
> 
> `to_tensor` is an alias of `to_varaible`, and we should use to_variable() or to_tensor() to convert data, otherwise, there may be some error. (see #26116, )
> 
> Could you give the URL of these dygraph demos just input nd.array class into the network? We will have a check on it.

@luotao1 

In this [link](https://github.com/PaddlePaddle/PaddleSeg/blob/52ef0ee505a00ed8c81f95759887e56062f0941b/dygraph/core/train.py#L29), in line 89, *image* and *label* is np.ndarray class, however in line 92, the image is directly inputed into the ddp_model. Maybe there is some implicit transform, but I don't notice. If it is, please let me know!  thx!!

**Comment by luotao1** [comment]
![image](https://user-images.githubusercontent.com/6836917/93853294-34660400-fce6-11ea-86bf-c08ad8c2f10a.png)
Dataloader returns loader, and each element in the loader is a Tensor. You can see the [Dataloader example](https://www.paddlepaddle.org.cn/documentation/docs/zh/api_cn/io_cn/DataLoader_cn.html#dataloader).
![image](https://user-images.githubusercontent.com/6836917/93853465-7d1dbd00-fce6-11ea-8c47-518e4e5a8cb2.png)
But we will update the `return type`, and tell users `each element in the loader is a Tensor`
![image](https://user-images.githubusercontent.com/6836917/93853574-aa6a6b00-fce6-11ea-91bf-86d4c795dbf5.png)

**Comment by Yuuuuuuuuuuuuuuuuuummy** [comment]
@luotao1 
I see, thx! May be my previous experiments have some bugs.
