### ISSUE TITLE
处理bert 等模型不定长问题

### ISSUE THREAD

**Issue by wds2014** [PaddlePaddle/Paddle#27425]
-------------------------------------------------
paddlepaddle 可以处理bert等NLP模型不定长问题吗？？
一般做法是通过padding 的方式强制每个batch内长度一致，能否通过lodtensor的方式直接处理不定长文本问题，来提高效率？？
谢谢 ！！
--------------------------------
 版本、环境信息：
    1）PaddlePaddle版本：1.7.2
    2）GPU：2080TI
    3）系统环境：UBUNTU16.04, python=3.6

**Comment by gongweibao** [comment]
现在暂时没有这样的对比数据。有了之后告知。感谢！
