### ISSUE TITLE
Proposal: remove get_place and set_place

### ISSUE THREAD

**Issue by wangkuiyi** [PaddlePaddle/Paddle#2742]
Currently in [paddle/platform/place.h](https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/platform/place.h) we have

```cpp
void set_place(const Place &);
const Place &get_place();
```

It looks convenient and flexible being able to create a Tensor on the default device.  However, it also makes it possible that some tensors created on an explicitly specified device cannot work together with those on the default device if the specified one differs from the default one.

This can be summarized as the evil of *mutable* global variables.  Let's remove them, and require that places are always specified explicitly.

**Comment by wangkuiyi** [comment]
I think that in Python, we can have some global status, including default place and default root scope, for the convenience of programming.  But in the C++ world, I'd suggest that we don't maintain global status.

**Comment by wangkuiyi** [comment]
Also, if we remove `set_place` and `get_place`, we wouldn't need

```cpp
typedef boost::variant<CPUPlace, GPUPlace> Place;
```

This helps us removing the dependency to boost.

**Comment by reyoung** [comment]
> But in the C++ world, I'd suggest that we don't maintain global status.

CUDA Device is actually a thread local information in CUDA library. This `get_place`/`set_place` is global function because CUDA API `cudaSetDevice` is global function.

**Comment by Canpio** [comment]
1. The `Place` of a tensor is specified only when we call `mutable_data()`. Before `mutable_data()` is called, a newly constructed tensor has no `dims`, `place` nor data_ptr. See [tensor.h](https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/framework/tensor.h) for implementation details.
If `get_place()` is removed, we have to offer an explicit `Place` every time we call `mutable_data()`. However, it also looks reasonable.

2. Removing `set_place()` and `get_place()` can't help us get ride of 
```cpp
typedef boost::variant<CPUPlace, GPUPlace> Place;
```
As a common container of `GpuPlace` and `CpuPlace`, `Place` is used in many other positions like:
https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/framework/tensor.h#L90
