### ISSUE TITLE
need a preliminary solution of GAN

### ISSUE THREAD

**Issue by Superjom** [PaddlePaddle/Paddle#2744]
GAN是目前比较热门的模型，很早确定要做，但一直hold
考虑到重构至少需要两个月，周期比较长，是否应该先给出一个初步的解决方案？
目前看之前的book里的可以做，但可能需要在v2里加一些封装
@llxxxll @reyoung @lcy-seso @xinghai-sun

**Comment by lcy-seso** [comment]
重构之后，新框架将对此类模型有很好的支持。暂不考虑在旧框架下继续GAN的工作，引起先close 此issue。
