### ISSUE TITLE
为何没有一个确定输出尺寸的函数？

### ISSUE THREAD

**Issue by fiyen** [PaddlePaddle/Paddle#27485]
几个月以前，就已经有人提及过这个问题：在ConvXD之后接ConvXD，或者Linear层时，会很不友好地要求输入channels或input_dim的值，然而这个值是需要人工计算的（channels上一层已经输入过，下一层本应该顺应上一层的参数不需要再输入这个值了）。但是现在的问题是paddle至今没有出自动计算的函数，这一点会造成很不必要的麻烦。
重申，在__init__中定义ConvXD后面的层时，总是需要人工计算特征数量或搬运之前已经有的值，人工计算很不友好。希望可以有相关的自动计算的函数。
代码示例如下：
![image](https://user-images.githubusercontent.com/35953131/93963335-7b5c0400-fd8f-11ea-8f2f-967392196767.png)

**Comment by fiyen** [comment]
图片挂了，再发一次：
![捕获](https://user-images.githubusercontent.com/35953131/93963604-2ff62580-fd90-11ea-995f-c8de18b960fb.PNG)

**Comment by GT-ZhangAcer** [comment]
图没挂，我这边可以看到。插个眼...

**Comment by wanghaoshuang** [comment]
多谢反馈，我们会优化下这个问题。

**Comment by fiyen** [comment]
https://aistudio.baidu.com/aistudio/projectdetail/1024182，我自己先写了一个函数，暂时解决一些问题。但是毕竟是个外挂，算不上好用，希望官方补充。
