### ISSUE TITLE
reduce_sum 输出值问题

### ISSUE THREAD

**Issue by TWLemontree** [PaddlePaddle/Paddle#27491]
with dygraph.guard():      
    x = fluid.layers.ones((128, 3, 28, 28), dtype='float32')     
    xi = fluid.layers.reshape(x, shape=(x.shape[0], -1, 3, x.shape[2], x.shape[3]))     
    xi2 = fluid.layers.reduce_sum(fluid.layers.square(xi), dim=2)     
    print(xi2) 

我在复现别人的代码时，用到了这样一段代码。xi2 本来应该输出元素全为 3 的张量，但不知道为什么值全部为 0 ！这给我造成了极大地困惑qwq

**Comment by TWLemontree** [comment]
![微信图片_20200923145356](https://user-images.githubusercontent.com/22110194/93977133-9ee17780-fdac-11ea-952f-fb60a04b992f.png)

**Comment by TWLemontree** [comment]
![torch](https://github.com/TWLemontree/issue_use_img/blob/master/%E5%BE%AE%E4%BF%A1%E5%9B%BE%E7%89%87_20200923145356.png)
![pp](https://github.com/TWLemontree/issue_use_img/blob/master/%E5%BE%AE%E4%BF%A1%E5%9B%BE%E7%89%87_20200923145456.png)

**Comment by wanghaoshuang** [comment]
请问您使用的paddle版本是？

**Comment by TWLemontree** [comment]
这个问题已经解决了，pp 1.8.x ，静态图下有问题，开启动态图就好了。有人试了试 2.0 b ，静态图动态图均无此问题。

**Comment by TWLemontree** [comment]
这个问题已经解决了，pp 1.8.x 版本，开启高级模式（GPU）问题解决，用基础模式（CPU）跑出现此问题。有大佬用 2.0 b 试了试，CPU GPU 均无此问题。

**Comment by TWLemontree** [comment]
这个问题已经解决了，pp 1.8.x 版本，开启高级模式（GPU）问题解决，用基础模式（CPU）跑出现此问题。有大佬用 2.0 b 试了试，CPU GPU 均无此问题。



在 2020-09-24 00:32:47，"whs" <notifications@github.com> 写道：

请问您使用的paddle版本是？
