### ISSUE TITLE
编译错误 - paddle/fluid/inference/tensorrt/helper.h

### ISSUE THREAD

**Issue by jeff41404** [PaddlePaddle/Paddle#27508]
版本、环境信息：
   1）PaddlePaddle版本：1.8
   2）CPU：Intel(R) Xeon(R) CPU E5-2650 v4 @ 2.20GHz
   3）GPU：Tesla P40，cuda 10.1，cudnn 7，gcc 8.2
   4）系统环境：Ubuntu 16.04、Python 3.6
![编译过程中 helper h 报错信息](https://user-images.githubusercontent.com/8555991/93996039-55048b80-fdc4-11ea-8338-4427fda31c04.JPG)

**Comment by wanghaoshuang** [comment]
@peiyang
帮忙看下这个问题？
