### ISSUE TITLE
关于paddle框架中hierarchical allreduce(2D ncclallreduce)代码实现以及使用方法的疑问

### ISSUE THREAD

**Issue by Frank00001** [PaddlePaddle/Paddle#27501]
我仔细浏览了paddle针对2D ncclallreduce算法开源的代码，主要有两点疑问：
1、在机器内,各个节点是否应该使用ncclreducescatter进行同步通信？
     根据腾讯提出的hirerarchical allreduce,如下图所示，在第一阶段各个组内intra rings时，每个计算节点都会接收上一个相邻节点发送的数据，并发送数据到相邻的下一个节点上，形成一个环形ring的逻辑。
![2](https://user-images.githubusercontent.com/43396077/93980664-80ca4600-fdb1-11ea-9c3d-ed401d3eeaba.png)
     但是在paddle实现这一同步算法时（Add multi-ncclcomm and 2D ncclallreduce support. #17263），第一阶段在第各个组内进行intra ring同步时，使用ncclreduce函数，这就没有构成一个环形ring的过程，请问此处代码是不是应该用ncclreducescatter进行替换？
2、关于2D ncclallreduce的使用方法
   我在飞桨GPU训练优秀实践的教程中，没有找到ringallreduce以及hierarchical allreduce(2D ncclallreduce)的具体使用方法。如下图所示，如果想使用hierarchical allreduce的话，是不是设置dist_strategy.use_hierarchical_allreduce=True即可，这个参数设置未在文档中进行说明；并且ringallreduce同步方式的使用方法也未在文档中说明。
![3](https://user-images.githubusercontent.com/43396077/93985844-2c769480-fdb8-11ea-90f1-151988e1cf92.PNG)

十分期待您的解答！

**Comment by wanghaoshuang** [comment]
@seiriosPlus 帮忙看下这个问题？

**Comment by gavin1332** [comment]
Hierarchical Allreduce和2D Allreduce不是同一个算法。

**Comment by Frank00001** [comment]
> Hierarchical Allreduce和2D Allreduce不是同一个算法。

我这里提到的2D Allreduce其实是paddlepaddle开发人员对分层allreduce的一种叫法（Add multi-ncclcomm and 2D ncclallreduce support. #17263）。请问您说的2D Allreduce是sony提出的一种同步方案吗？[https://arxiv.org/abs/1811.05233](url)

**Comment by gavin1332** [comment]
是的，在真2D allreduce出来之前，大家把**分层allreduce**也称为2D allreduce，实际上是不准确的。

**Comment by gavin1332** [comment]
ok，那你对分层allreduce是有什么疑问呢？

**Comment by gongweibao** [comment]
感谢！@Frank00001.
1. PR的标题写错了，是hierarchical allreduce 而非2Dallreduce
2. 论文中的描述：
![image](https://user-images.githubusercontent.com/10721757/94112781-82ab0c80-fe78-11ea-905a-7094f3ffc2ca.png)

**Comment by gavin1332** [comment]
https://fleet-x.readthedocs.io/en/latest/

**Comment by gavin1332** [comment]
我们近期正在整理paddle分布式训练文档，并且把应用fleet进行分布式训练的接口正式化，其中包含层次allreduce的使用。请关注：
https://fleet-x.readthedocs.io/en/latest/

BTW, 版本有一定的要求：paddlepaddle-2.0.0-rc-gpu及以上。我们的RC版将在10.28发布，相关代码已经合入develop

**Comment by Frank00001** [comment]
> ok，那你对分层allreduce是有什么疑问呢？

我的疑问主要是在第一个阶段（组内同步）：按照腾讯论文的描述，第一个阶段组内各个计算节点做reduce操作。但是需要注意的是，此处的reduce描述并不准确，如下图所示，第一个阶段每个分组内的节点通信过程构成了环形ring的逻辑，应该是用reduce-scatter。我认为此处paddlepaddle对各个组内的节点使用ncclreduce进行同步是不合适的，应该使用ncclreducescatter方法。此处更改为ncclreducescatter后，paddle实现的hierarchical allreduce才可以叫做hierarchical ringallreduce！
![image](https://user-images.githubusercontent.com/43396077/94113488-8be8a900-fe79-11ea-9564-8819fa3e3234.png)

**Comment by gongweibao** [comment]
```
我认为此处paddlepaddle对各个组内的节点使用ncclreduce进行同步是不合适的，应该使用ncclreducescatter方法
```
何以见得？因为论文中的`partial result`吗？单台机器也是 `partial result`。

**Comment by Frank00001** [comment]
> 我认为在ncclreducescatter是一个ring的过程，请问ncclreduce同步是一个ring的过程吗？
此外，第一步按照腾讯论文下图的描述，每个节点都会收到与之相邻的上一个节点发送过来的梯度，并发送梯度至相邻的下一个节点。以此构成环形通信过程。
![2](https://user-images.githubusercontent.com/43396077/94115910-f2bb9180-fe7c-11ea-8fa0-377590e99f25.png)

**Comment by gongweibao** [comment]
哦。我知道你的问题了。看这里：https://docs.nvidia.com/deeplearning/nccl/user-guide/docs/api/colls.html
```
Reduce data in sendbuff from all GPUs using the op operation and leave the reduced result scattered over the devices so that the recvbuff on rank i will contain the i-th block of the result.
```
如果第一步是`ncclreducescatter`, 紫色节点只包含` i-th block of the result`，也就是一部分结果，第二步要进行多个`allreduce`才行，而不是图示的一个；第三步也不用`broadcast`，`allgather`就好了。而那样就是 2dallreduce了。

`ncclreduce`看怎么实现的，我没有找到其实现的资料，是不是分成两步：第一步执行`ncclreducescatter`以便充分利用并发，第二步再`reduce`到一个卡上？这个是猜测。

**Comment by Frank00001** [comment]
> 我们近期正在整理paddle分布式训练文档，并且把应用fleet进行分布式训练的接口正式化，其中包含层次allreduce的使用。请关注：
> https://fleet-x.readthedocs.io/en/latest/
> 
> BTW, 版本有一定的要求：paddlepaddle-2.0.0-rc-gpu及以上。我们的RC版将在10.28发布，相关代码已经合入develop
非常感谢！！
