### ISSUE TITLE
编译错误 - paddle/fluid/inference/tensorrt/plugin/trt_plugin.h

### ISSUE THREAD

**Issue by jeff41404** [PaddlePaddle/Paddle#27509]
版本、环境信息：
   1）PaddlePaddle版本：1.8
   2）CPU：Intel(R) Xeon(R) CPU E5-2650 v4 @ 2.20GHz
   3）GPU：Tesla P40，cuda 10.1，cudnn 7，gcc 8.2
   4）系统环境：Ubuntu 16.04、Python 3.6
![编译过程中 trt_plugin h 报错信息](https://user-images.githubusercontent.com/8555991/93996229-9432dc80-fdc4-11ea-9f0b-a37d76723af7.JPG)

**Comment by wanghaoshuang** [comment]
@cryoco 麻烦看下这个问题？
