### ISSUE TITLE
编译错误 - paddle/fluid/platform/dynload/tensorrt.h

### ISSUE THREAD

**Issue by jeff41404** [PaddlePaddle/Paddle#27507]
- 版本、环境信息：
    1）PaddlePaddle版本：1.8
    2）CPU：Intel(R) Xeon(R) CPU E5-2650 v4 @ 2.20GHz
    3）GPU：Tesla P40，cuda 10.1，cudnn 7，gcc 8.2
    4）系统环境：Ubuntu 16.04、Python 3.6
![编译过程中 tensorrt h 报错信息](https://user-images.githubusercontent.com/8555991/93994772-d824e200-fdc2-11ea-8d5a-d761d4180115.JPG)

**Comment by wanghaoshuang** [comment]
@cryoco 帮忙看下这个问题？

**Comment by cryoco** [comment]
您好，您
https://github.com/PaddlePaddle/Paddle/issues/27509
https://github.com/PaddlePaddle/Paddle/issues/27508
https://github.com/PaddlePaddle/Paddle/issues/27507
几个issue是同一个问题，该问题我们在develop已经修复，尚未cherry-pick到1.8版本，感谢反馈，我们会加以修复
