### ISSUE TITLE
Assign new id when we restart a task?

### ISSUE THREAD

**Issue by gongweibao** [PaddlePaddle/Paddle#2752]
>Task分发给Trainer的一个要做的事情，Trainer貌似不需要知道这是第几个Epoch。
我大概明白为什么需要Epoch，为的是唯一标示一个Task，不然多个机器可能会有同一个Task的不同Epoch
这样看来的话，是不是考虑每个Task分发出去的时候就给一个新的ID就好？

https://github.com/PaddlePaddle/Paddle/pull/2719#discussion_r125538655

**Comment by gongweibao** [comment]
我也曾经想过这个问题，只是一个`task`的多个副本都在运行的时候，任何一个副本finish了都代表这个`task` finish了。如果每个task是一个`uniq id`，这种情况该如何解决？

**Comment by typhoonzero** [comment]
每个task 对应唯一的id时符合情理的，而且这个task被重放之后id不应该变化，这样可以在job结束之后知道每个task运行了几次，哪些没有被运行。

生成唯一id的方法可以参考uuid的[RFC](https://tools.ietf.org/html/rfc4122)

https://stackoverflow.com/questions/1785503/when-should-i-use-uuid-uuid1-vs-uuid-uuid4-in-python

http://www.sohamkamani.com/blog/2016/10/05/uuid1-vs-uuid4/

**Comment by gongweibao** [comment]
有冲突。有的汇报成功，有的汇报失败，次序还有变化，该如何处理？

**Comment by Yancey1989** [comment]
同意 @typhoonzero 

> 有冲突。有的汇报成功，有的汇报失败，次序还有变化，该如何处理？

这里的冲突是说：Task-a被一个Trainer获取并训练失败，在汇报时因为网络原因一直失败，master等待超时后又将Task-a加入到TODO队列里并被其他Trainer获取并训练， 这时第一个Trainer又可以正常的汇报task状态，导致Task-a会出现在Pending和Failed两个队列里面么？

如果是这样的话，感觉唯一的ID更是必要的了吧，Trainer汇报时检查一下是不是在Pending队列里，如果在的话就舍弃掉，再获取一个新的task来训练就好了？

**Comment by typhoonzero** [comment]
> 有冲突。有的汇报成功，有的汇报失败，次序还有变化，该如何处理？

`TaskEntry`中加上对应的历史信息即可。

**Comment by gongweibao** [comment]
我考虑了一下task的问题，并且线下和 @typhoonzero 聊了一下，我的思路是这样的：
[The life cycle of a single task is illustrated below](https://github.com/PaddlePaddle/Paddle/tree/develop/doc/design/cluster_train#task-queue)这个图严格来说是有问题的，他只能说明master 记录的task的`life cycle`信息。实际执行里边，task的状态主要通过`timeout`(不可知问题)和`task fail`(task 感知且汇报)。这样的情况下，`task`其实是可以有多个副本在同时执行(`task0` timeout之后，启动`task1`，`task1`超时，再启动`task2`)。
1. 一个副本在报告状态的时候，`task`可以在`master`记录的各种队列中`todo`,`done`,`fail`,`pending`. 所以只检查在`pending`中是否存在是不对的:https://github.com/PaddlePaddle/Paddle/blob/develop/go/master/service.go#L366

1. 一个副本报告执行成功，`task`执行成功；一个副本报告失败或者`timeout`,`task`未必失败--因为可以重试或者其他副本有可能报告成功。

**Comment by typhoonzero** [comment]
先考虑实现简单的版本吧。

**Comment by helinwang** [comment]
赞讨论！倾向于"如果做简化"提出的几点。
