### ISSUE TITLE
docker下运行ctr预估模型，报错

### ISSUE THREAD

**Issue by zhangzhenyue1** [PaddlePaddle/Paddle#2753]
## **docker环境**：
Docker version 1.12.6, build 3a094bd/1.12.6
## **paddle环境**：
paddlepaddle/paddle:0.10.0
## **运行脚本及报错信息**：
python train.py --train_data_path train.txt
Illegal instruction(core dumped)
## **代码示例**：
https://github.com/PaddlePaddle/models/blob/develop/ctr/train.py 
## **数据示例**：
id,click,hour,C1,banner_pos,site_id,site_domain,site_category,app_id,app_domain,app_category,device_id,device_ip,device_model,device_type,device_conn_type,C14,C15,C16,C17,C18,C19,C20,C21
10000174058809263569,1,14103100,1005,0,235ba823,f6ebf28e,f028772b,ecad2386,7801e8d9,07d7df22,a99f214a,69f45779,0eb711ec,1,0,8330,320,50,761,3,175,100075,23
10000182526920855428,1,14103100,1005,0,1fbe01fe,f3845767,28905ebd,ecad2386,7801e8d9,07d7df22,a99f214a,e8d44657,ecb851b2,1,0,22676,320,50,2616,0,35,100083,51
40多行
## **虚拟机信息**：
系统参数：
processor	: 0
vendor_id	: GenuineIntel
cpu family	: 6
model		: 47
model name	: Intel(R) Xeon(R) CPU E7- 4820  @ 2.00GHz
stepping	: 2
microcode	: 0x36
cpu MHz		: 1994.956
cache size	: 18432 KB
physical id	: 0
siblings	: 1
core id		: 0
cpu cores	: 1
apicid		: 0
initial apicid	: 0
fpu		: yes
fpu_exception	: yes
cpuid level	: 11
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts mmx fxsr sse sse2 ss syscall nx rdtscp lm constant_tsc arch_perfmon pebs bts nopl xtopology tsc_reliable nonstop_tsc aperfmperf pni pclmulqdq ssse3 cx16 sse4_1 sse4_2 x2apic popcnt aes hypervisor lahf_lm ida arat epb dtherm
bogomips	: 3990.07
clflush size	: 64
cache_alignment	: 64
address sizes	: 40 bits physical, 48 bits virtual
power management:

processor	: 1
vendor_id	: GenuineIntel
cpu family	: 6
model		: 47
model name	: Intel(R) Xeon(R) CPU E7- 4820  @ 2.00GHz
stepping	: 2
microcode	: 0x36
cpu MHz		: 1994.956
cache size	: 18432 KB
physical id	: 2
siblings	: 1
core id		: 0
cpu cores	: 1
apicid		: 2
initial apicid	: 2
fpu		: yes
fpu_exception	: yes
cpuid level	: 11
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts mmx fxsr sse sse2 ss syscall nx rdtscp lm constant_tsc arch_perfmon pebs bts nopl xtopology tsc_reliable nonstop_tsc aperfmperf pni pclmulqdq ssse3 cx16 sse4_1 sse4_2 x2apic popcnt aes hypervisor lahf_lm ida arat epb dtherm
bogomips	: 3990.07
clflush size	: 64
cache_alignment	: 64
address sizes	: 40 bits physical, 48 bits virtual
power management:

**Comment by Yancey1989** [comment]
Try the Docker image with no AVX `paddlepaddle/paddle:0.10.0rc3-noavx`.

**Comment by zhangzhenyue1** [comment]
3ks，问题解决了
