### ISSUE TITLE
Could you please add test for NHWC model inference?

### ISSUE THREAD

**Issue by jczaja** [PaddlePaddle/Paddle#27547]
Hi, 

oneDNN is implementing NHWC  model inference in fairly complex way and We are not able to test this only with unit test. It would be very helpful if there is a C-API / python API test that is running inference using CPU as well as oneDNN and then compare results. That would help in making sure that oneDNN's  NHWC support is in sync with CPU.

**Comment by luotao1** [comment]
We have some NHWC model inference (C-API/python API) in CE, like #20589 and #25537 (maybe add in CE later). But I don't know whether there is C-API / python API test that is running inference in unit-tests.

**Comment by jczaja** [comment]
thanks
