### ISSUE TITLE
Paddle 中使用 Dropout，训练时会做 Inverted Dropout 吗？

### ISSUE THREAD

**Issue by 20092136** [PaddlePaddle/Paddle#2755]
feed forward 前是否会除以 dropout rate？或者说预测时是否需要手动关闭 dropout 再将权值乘以相同 scale 呢？

**Comment by lcy-seso** [comment]
- 在 Paddle 中，训练时，dropout 是在激活中做的，生成一个 mask，drop 掉部分连接。
- 预测时，请务必保留配置中设置的 `droprate` 不要改变，**不需要关闭dropout**。预测过程前向计算完之后，点乘`droprate`。

**Comment by 20092136** [comment]
`预测过程前向计算完之后，点乘droprate`

**Comment by 20092136** [comment]
`预测过程前向计算完之后，点乘droprate`意思是 Paddle 在预测过程中会这么做，还是我需要手动这么做呢？

**Comment by lcy-seso** [comment]
- 是自动的，预测什么都不需要修改。
- 唯一需要保证的仅有：**预测时千万不要把droprate从配置中删掉或者修改droprate的值**，否认当中间隐层加入 dropout 预测结果会是错误的。

**Comment by lcy-seso** [comment]
paddle 使用的不是 inverted dropout 方式。

**Comment by 20092136** [comment]
好的，明白了，谢谢
