### ISSUE TITLE
paddle 1.8 在电脑运行环境，不识别函数fluid.layers.sigmoid

### ISSUE THREAD

**Issue by Sno-dl** [PaddlePaddle/Paddle#27552]
- 问题描述：
在”零基础入门深度学习“ -> 深度学习实践应用：计算机视觉 -> 图像分类教程中，使用AIStudio可以正常运行教程的代码。

但是使用单机环境的时候，代码报错，fluid.layers.sigmoid 函数提示错误 ”Undefined variable from import: sigmoid“
如下图所示
![34](https://user-images.githubusercontent.com/71628186/94154448-7773d300-feb0-11ea-89b1-7c3502e2814f.jpg)

运行环境    
1）PaddlePaddle版本：1.8.4.0
2）系统环境：windows 10，Python版本 3.6.8
3）CPU版本

谢谢

**Comment by Superjomn** [comment]
好的，我们联合 aistudio 追下这个问题。

谢谢反馈 ：）
