### ISSUE TITLE
如何让模型启动后一直保持待机状态？

### ISSUE THREAD

**Issue by Derek-Kun** [PaddlePaddle/Paddle#27564]
比方说我这里有好几批图片，我用图片分类的网络做预测，每次通过命令行
python infer.py --pretrained_model=${path_to_pretrain_model} 来预测一批图片，但是等下一批图片过来的时候，又要执行
python infer.py --pretrained_model=${path_to_pretrain_model}
我注意到模型每次加载都需要10秒左右，真正用来预测图片的时间可能只有0.01秒，请问有办法让模型加载以后就一直处于待机状态，有新图片传输进来就直接预测吗？

**Comment by seiriosPlus** [comment]
reader不要结束就可以的.. reader不退出. 训练也不会结束.

**Comment by Derek-Kun** [comment]
我说的是模型训练好以后用模型去infer别的图片，每次只预测一张，比方说我这里有100张图片，不是说把100张图片看成一批输入，而是类似我现在有一个网站，用户可以上传图片，上传一张我就预测一张，用户上传的时间是不确定的，但是如果每次用户上传我都执行一次infer.py，启动和关闭模型就要十几秒的时间，但是实际预测图片的时间只有0.01秒。

> 
> 
> reader不要结束就可以的.. reader不退出. 训练也不会结束.
