### ISSUE TITLE
deeplabv3p_xception MKLDNN prediction failed

### ISSUE THREAD

**Issue by OliverLPH** [PaddlePaddle/Paddle#27567]
**System information**
-PaddlePaddle version: develop, 597345d17b5f6252878bfb0f62133f77f485d7ef
-CPU: Intel(R) Xeon(R) CPU E5-2650 v4 @ 2.20GHz, mkldnn enabled
-GPU: P4, CUDA10, CUDNN7.5, compile with GPU, but run cpu inference
-OS Platform: Ubuntu1604
-Dockerfile: Paddle/tools/manylinux1/Dockerfile.cuda10_cudnn7_gcc48_ubuntu16
-Python version: 3.7
-Cmake orders
-C++version.txt
-API information
Note: You can get most of the information by running [summary_env.py](https://github.com/PaddlePaddle/Paddle/blob/develop/tools/summary_env.py). 
**To Reproduce**
Steps to reproduce the behavior
```python
config = AnalysisConfig(args.model_file, args.params_file)
config.disable_gpu()
config.enable_mkldnn()
config.switch_use_feed_fetch_ops(False)
config.switch_specify_input_names(True)
# config.delete_pass("depthwise_conv_mkldnn_pass")  # this pass has bug
```

**Describe your current behavior**
```shell
--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
0   paddle::AnalysisPredictor::ZeroCopyRun()
1   paddle::framework::NaiveExecutor::Run()
2   paddle::framework::OperatorBase::Run(paddle::framework::Scope const&, paddle::platform::Place const&)
3   paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, paddle::platform::Place const&) const
4   paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, paddle::platform::Place const&, paddle::framework::RuntimeContext*) const
5   std::_Function_handler<void (paddle::framework::ExecutionContext const&), paddle::framework::OpKernelRegistrarFunctor<paddle::platform::CPUPlace, false, 0ul, paddle::operators::ConvMKLDNNOpKernel<float, float> >::operator()(char const*, char const*, int) const::{lambda(paddle::framework::ExecutionContext const&)#1}>::_M_invoke(std::_Any_data const&, paddle::framework::ExecutionContext const&)
6   void paddle::operators::ConvMKLDNNOpKernel<float, float>::ComputeFP32<float>(paddle::framework::ExecutionContext const&) const
7   paddle::operators::ConvMKLDNNHandlerT<float, float, float>::ConvMKLDNNHandlerT(paddle::framework::ExecutionContext const&, paddle::platform::MKLDNNDeviceContext const&, dnnl::engine, paddle::platform::Place, paddle::framework::Tensor const*, paddle::framework::Tensor const*, paddle::framework::Tensor const*, paddle::framework::Tensor*, std::string const&)
8   paddle::platform::EnforceNotMet::EnforceNotMet(std::string const&, char const*, int)
9   paddle::platform::GetCurrentTraceBackString()

----------------------
Error Message Summary:
----------------------
UnimplementedError: Dilation in oneDNN convolution is not implemented yet
  [Hint: Expected is_conv3d ? dilations.size() == 3 && dilations[0] == 1 && dilations[1] == 1 && dilations[2] == 1 : dilations.size() == 2 && dilations[0] == 1 && dilations[1] == 1 == true, but received is_conv3d ? dilations.size() == 3 && dilations[0] == 1 && dilations[1] == 1 && dilations[2] == 1 : dilations.size() == 2 && dilations[0] == 1 && dilations[1] == 1:0 != true:1.] (at /workspace/paddle/fluid/operators/mkldnn/conv_mkldnn_op.cc:195)
  [operator < conv2d > error]
```

**Code to reproduce the issue**
[deeplabv3_mkldnn_bug.txt](https://github.com/PaddlePaddle/Paddle/files/5281499/deeplabv3_mkldnn_bug.txt)

python3 deeplabv3_mkldnn_bug.py --model_file=./deeplabv3p_xception_769-fp32/model --params_file=./deeplabv3p_xception_769-fp32/params

**Other info / logs**
![image](https://user-images.githubusercontent.com/14963836/94244830-0aae1680-ff4c-11ea-9cac-ea18e738d822.png)

**Comment by OliverLPH** [comment]
Model download link:https://dubox.com/s/1nPLPca6GVMWxJwbfQXYilw 
Password:bzhs

**Comment by lidanqing-vv** [comment]
@juncaipeng @OliverLPH 

1. The native CPU config also cause the demo failure as follows:
```
----------------------
Error Message Summary:
----------------------
InvalidArgumentError: The 2-th dimension of input[0] and input[1] is expected to be equal.But received input[0]'s shape = [1, 256, 33, 33], input[1]'s shape = [1, 256, 49, 49].
  [Hint: Expected inputs_dims[0][j] == inputs_dims[i][j], but received inputs_dims[0][j]:33 != inputs_dims[i][j]:49.] (at /home/li/repo/Paddle/paddle/fluid/operators/concat_op.h:63)
```
It seems this demo does not have correct input dimension matching the model's dimension. model is as follows:
![image](https://user-images.githubusercontent.com/47151829/95694841-55aa7800-0c34-11eb-8932-013cbd3434c4.png)
But the demo gives input as follows:
```
fake_input = np.random.randn(1, 3, 769, 769).astype("float32")
input_tensor.reshape([1, 3, 769, 769])
```


Should it be like this ?
```
fake_input = np.random.randn(1, 3, 513, 513).astype("float32")
input_tensor.reshape([1, 3, 513, 513])
```

2. I changed input as above and added dilated mkldnn convolution,  the demo test passed with enable_mkldnn(). But this demo does not give any accuracy. Do you have a model having accuracy layer ? If not, I will add UT and submit the PR.

**Comment by OliverLPH** [comment]
@lidanqing-intel 
I use netron visualize this model, but I find the input of this model  is [1, 3, 769, 769]
![image](https://user-images.githubusercontent.com/14963836/95701298-cf198900-0c7b-11eb-852d-fed98aa3a812.png)



I will change input to [1, 3, 513, 513] and try in mkldnn and cpu mode.


> I changed input as above and added dilated mkldnn convolution, the demo test passed with enable_mkldnn(). But this demo does not give any accuracy. Do you have a model having accuracy layer ? If not, I will add UT and submit the PR.

This model is the only one I have now.
