### ISSUE TITLE
load_params 失败，打不开参数文件

### ISSUE THREAD

**Issue by hexo** [PaddlePaddle/Paddle#27563]
Error: Cannot open file model_stage3/mmoe_video_v1_2020_09_24_20_10_23_2.8341595313204144_2.833708877872916_5.956663941128373/batch_norm_1.w_0 for load op at (/home/teamcity/work/ef54dc8a5b211854/paddle/fluid/operators/load_op.h:38)
  [operator < load > error]

**Comment by chenjiaoAngel** [comment]
这个是运行fluid 程序出现的问题吗？

**Comment by hexo** [comment]
是的，感觉是读取的参数名字和实际不一致，实际没有这个batch_norm_1.w_0 文件。这个需要怎么解决呢，
![image](https://user-images.githubusercontent.com/20752493/94240273-a720ea80-ff45-11ea-97cf-a516cdca41a9.png)

**Comment by hexo** [comment]
![image](https://user-images.githubusercontent.com/20752493/94240352-c3bd2280-ff45-11ea-8f71-01a9ca1bfb77.png)
shi实际的文件是这个，对不上，是不是需要定义bath_norm 的时候写定name呢

**Comment by chenjiaoAngel** [comment]
这个建议去paddle paddle用户群（1560738）咨询下
