### ISSUE TITLE
未找到-o命令

### ISSUE THREAD

**Issue by fsted** [PaddlePaddle/Paddle#27574]
- 标题：未找到-o命令
- 版本、环境信息：
    1）PaddlePaddle版本：1.8.4.post107
    2）CPU：Intel(R) Xeon(R) Gold 6240C CPU @ 2.60GHz
    3）GPU：Persistence-M
    4）系统环境：Ubuntu 7.5.0-3ubuntu1~18.04，Python3.7

- 问题描述：使用以下命令开始跑模型：
python -m paddle.distributed.launch \
            --selected_gpus="0" \
                tools/eval.py \
                        -c ./configs/eval.yaml
                        -o pretrained_model="./pretrained/ResNet50_vd_ssld_pretrained"

倒是可以跑
末尾显示未找到命令"-o"，求问这是怎么回事

**Comment by danleifeng** [comment]
1. 请问你直接跑单卡有问题么
```
python tools/eval.py -c ./configs/eval.yaml -o pretrained_model="./pretrained/ResNet50_vd_ssld_pretrained"
```
2. tools/eval.py代码里传入参数-o是否正常？
