### ISSUE TITLE
VisualDL问题

### ISSUE THREAD

**Issue by lyn1225** [PaddlePaddle/Paddle#27580]
按照官方教程下载并使用VisualDL,但是在浏览器中显示不了，提示“无法访问此网站，localhost拒绝了我们的连接请求”。这如何解决？

**Comment by ShenYuhan** [comment]
可以放一下浏览器的截图以及启动visualdl后服务端的截图吗

**Comment by phlrain** [comment]
也有可能是端口的问题，有些机器会限制8000一下端口的访问

**Comment by lyn1225** [comment]
![](https://github.com/lyn1225/test/blob/master/2.PNG)
![](https://github.com/lyn1225/test/blob/master/3.PNG)

**Comment by lyn1225** [comment]
[](https://github.com/lyn1225/test/blob/master/2.PNG)

**Comment by lyn1225** [comment]
![image](https://github.com/lyn1225/test/blob/master/2.PNG)

**Comment by lyn1225** [comment]
[text](E:\Google_download\2.png)

**Comment by lyn1225** [comment]
![image](https://github.com/lyn1225/images/blob/master/aachen_000000_000019_leftImg8bit.png)

**Comment by lyn1225** [comment]
![image](https://github.com/lyn1225/images/blob/master/2.PNG)

**Comment by lyn1225** [comment]
1[image](https://github.com/lyn1225/images/blob/master/3.PNG)

**Comment by lyn1225** [comment]
@ShenYuhan 
![image](https://github.com/lyn1225/images/blob/master/2.PNG)
![image](https://github.com/lyn1225/images/blob/master/3.PNG)

**Comment by YixinKristy** [comment]
> @lyn1225 


查看了您的截图，发现您使用的aistudio上的vdl，不需要重新开窗口，左侧有「启动VisualDL」的按钮可以使用的哈
<p align="center">
<img src="https://user-images.githubusercontent.com/48054808/95651824-60bfb400-0b1f-11eb-90d9-04403b284bb5.png" width="50%"/>
</p>
