### ISSUE TITLE
Windows 10 VS 2019 CPU Paddle Develop编译错误

### ISSUE THREAD

**Issue by unco2020** [PaddlePaddle/Paddle#27584]
\paddle\fluid\framework文件夹data_type.h中错误：
错误	C2672	“paddle::framework::details::TensorCheckerVisitor<paddle::platform::CPUDeviceContext>::apply”: 未找到匹配的重载函数	。C:\Projects\Paddle2.0\Soruce\paddle\fluid\framework\data_type.h	79	

错误	C2770	“void paddle::framework::details::TensorCheckerVisitor<paddle::platform::CPUDeviceContext>::apply(std::enable_if<std::is_integral<T>::value,void>::type *) const”的显式 模板 参数无效	nan_inf_utils	C:\Projects\Paddle2.0\Soruce\paddle\fluid\framework\data_type.h	79	

导致nan_inf_utils项目编译不成功。不能生成libnan_inf_utils.lib
_ForEachDataType_(VisitDataTypeCallback)

**Comment by unco2020** [comment]
nan_inf_util_detail.cc和nan_inf_util_detail.h有些问题，注释掉nan_inf_util_detail.h中的

 /*template <typename T>
  void apply(
      typename std::enable_if<std::is_integral<T>::value>::type* = 0) const {
    VLOG(10) << var_name_ << " need not to check, it's type is not float point";
  }*/

 /* template <typename T>
  void apply(typename std::enable_if<std::is_floating_point<T>::value>::type* =
                 0) const;*/

注释掉：nan_inf_util_detail.cc中的
//template <>
//template <typename T>
//void TensorCheckerVisitor<platform::CPUDeviceContext>::apply(
//    typename std::enable_if<std::is_floating_point<T>::value>::type*) const {
//  // use env strategy control in future, -1=print_all.
//  int print_num = 3;
//  CheckNanInf(tensor_.data<T>(), tensor_.numel(), print_num, op_type_,
//              var_name_);
//}

template <>
void tensor_check<platform::CPUDeviceContext>(const std::string& op_type,
                                              const std::string& var_name,
                                              const framework::Tensor& tensor,
                                              const platform::Place& place) {
  TensorCheckerVisitor<platform::CPUDeviceContext> vistor(op_type, var_name,
                                                          tensor, place);
//  VisitDataType(tensor.type(), vistor);
}

编译时通过了，不知道有啥影响。

**Comment by zhhsplendid** [comment]
注释掉的地方是检查nan/inf的工具，所以如果不使用，这样编译没有影响

**Comment by unco2020** [comment]
protobuf编译有问题，cmake中的Tag有问题，换一下就好了
