### ISSUE TITLE
Can not find [GB_resnet9block_c1_norm_w] in model file [model/checkpoints/74/net_G.pdparams]

### ISSUE THREAD

**Issue by wles1995** [PaddlePaddle/Paddle#27582]
PaddlePaddle版本：PaddlePaddle 1.8.4
Python版本：python 3.7

AssertionError: Can not find [GB_resnet9block_c1_norm_w] in model file [model/checkpoints/74/net_G.pdparams]

![image](https://user-images.githubusercontent.com/58210069/94342268-92764c80-0042-11eb-80d3-b6b96f104068.png)
调用图一第一个红框里的语句，可以查出下列的参数名称：其中明显包含了“GB_resnet9block_c1_norm_w”

![image](https://user-images.githubusercontent.com/58210069/94342274-9efaa500-0042-11eb-80db-5d9f06bca4cd.png)
而调用图一第二个红圈时，却报错如下图所示：
![image](https://user-images.githubusercontent.com/58210069/94342282-a6ba4980-0042-11eb-9d2b-0dc23f4c8a21.png)
错误信息如下图所示：
![image](https://user-images.githubusercontent.com/58210069/94342354-19c3c000-0043-11eb-8430-20fbdce00ff3.png)

求解答

**Comment by phlrain** [comment]
能提供下 net_G save的命令么
