### ISSUE TITLE
uwsgi部署推理模型请求频繁或者并发程序报错、内存也泄露

### ISSUE THREAD

**Issue by L-lei** [PaddlePaddle/Paddle#27618]
请求频繁或者并发请求出现问题
问题1：程序推理时报错
问题2：内存会一直增大
python版本3.6
paddlepaddle版本1.8.4
推理主要部分
    infer_scope = fluid.core.Scope()
    with fluid.scope_guard(infer_scope):
               exe = fluid.Executor(place)
               program, feed_names, fetch_targets = fluid.io.load_inference_model()
               exe.run(program,feed=inputs,fetch_list=fecth_targets,return_numpy=False)

报错内容
----------------------
Error Message Summary:
----------------------
Error: Tensor not initialized yet when Tensor::type() is called.
  [Hint: holder_ should not be null.] at (/paddle/paddle/fluid/framework/tensor.h:140)
  [operator < conv2d > error]

  File "./utils/obj_infer.py", line 442, in predict
    return_numpy=False)
  File "/usr/local/lib64/python3.6/site-packages/paddle/fluid/executor.py", line 1071, in run
    six.reraise(*sys.exc_info())
  File "/usr/local/lib/python3.6/site-packages/six.py", line 703, in reraise
    raise value
  File "/usr/local/lib64/python3.6/site-packages/paddle/fluid/executor.py", line 1066, in run
    return_merged=return_merged)
  File "/usr/local/lib64/python3.6/site-packages/paddle/fluid/executor.py", line 1154, in _run_impl
    use_program_cache=use_program_cache)
  File "/usr/local/lib64/python3.6/site-packages/paddle/fluid/executor.py", line 1229, in _run_program
    fetch_var_name)
paddle.fluid.core_avx.EnforceNotMet: 

--------------------------------------------
C++ Call Stacks (More useful to developers):
--------------------------------------------
0   std::string paddle::platform::GetTraceBackString<std::string const&>(std::string const&, char const*, int)
1   paddle::platform::EnforceNotMet::EnforceNotMet(std::string const&, char const*, int)
2   paddle::framework::Tensor::type() const
3   paddle::operators::ConvOp::GetExpectedKernelType(paddle::framework::ExecutionContext const&) const
4   paddle::framework::OperatorWithKernel::ChooseKernel(paddle::framework::RuntimeContext const&, paddle::framework::Scope const&, paddle::platform::Place const&) const
5   paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, paddle::platform::Place const&, paddle::framework::RuntimeContext*) const
6   paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, paddle::platform::Place const&) const
7   paddle::framework::OperatorBase::Run(paddle::framework::Scope const&, paddle::platform::Place const&)
8   paddle::framework::Executor::RunPartialPreparedContext(paddle::framework::ExecutorPrepareContext*, paddle::framework::Scope*, long, long, bool, bool, bool)
9   paddle::framework::Executor::RunPreparedContext(paddle::framework::ExecutorPrepareContext*, paddle::framework::Scope*, bool, bool, bool)
10  paddle::framework::Executor::Run(paddle::framework::ProgramDesc const&, paddle::framework::Scope*, int, bool, bool, std::vector<std::string, std::allocator<std::string> > const&, bool, bool)

**Comment by L-lei** [comment]
推理部署这坑怕是踏不出来了，直接定义个全局exe = fluid.Executor(place)；
program, feed_names, fetch_targets = fluid.io.load_inference_model()不报异常，内存泄露好像也没有了。不使用infer_scope = fluid.core.Scope()；with fluid.scope_guard(infer_scope)没法部署多个模型，使用它在报请求频繁或者并发请求就报异常。这个用的自相矛盾

**Comment by Shixiaowei02** [comment]
你好，请问您是使用 Python 进行模型的并发部署吗？请把可复现的脚本模型发给我们，并且尝试使用 C++ 复现问题。谢谢

**Comment by L-lei** [comment]
是的，我整理个复现的demo怎么给你们呢

**Comment by Shixiaowei02** [comment]
> 是的，我整理个复现的demo怎么给你们呢

请问是否方便给一个外网或者网盘链接？

模型可以用类似网络，parameter 如果铭感用跑一个 pass 出来的随机模型也行

**Comment by L-lei** [comment]
好的，我弄好后发你百度网盘链接地址

**Comment by Superjomn** [comment]
另外，可以大概描述下，模型结构是否包含 rnn 相关，输入输出 shape 是固定不变还是会变化（除了 batchsize）

**Comment by L-lei** [comment]
> 另外，可以大概描述下，模型结构是否包含 rnn 相关，输入输出 shape 是固定不变还是会变化（除了 batchsize）

链接：https://pan.baidu.com/s/1Bv46c-h7ohoU1LLan2Uoaw 密码：8ki3

**Comment by Shixiaowei02** [comment]
> > 另外，可以大概描述下，模型结构是否包含 rnn 相关，输入输出 shape 是固定不变还是会变化（除了 batchsize）
> 
> 链接：https://pan.baidu.com/s/1Bv46c-h7ohoU1LLan2Uoaw 密码：8ki3

看了一下您的文件，请问能否再简化一下问题：去除服务相关的代码和前后处理？变成这样的一个单文件，只依赖 paddle 和 numpy 的demo
```
import paddle.fluid as fluid
import numpy as np

# Build the model
main_prog = fluid.Program()
startup_prog = fluid.Program()
with fluid.program_guard(main_prog, startup_prog):
    data = fluid.layers.data(name="img", shape=[64, 784], append_batch_size=False)
    w = fluid.layers.create_parameter(shape=[784, 200], dtype='float32')
    b = fluid.layers.create_parameter(shape=[200], dtype='float32')
    hidden_w = fluid.layers.matmul(x=data, y=w)
    hidden_b = fluid.layers.elementwise_add(hidden_w, b)
place = fluid.CPUPlace()
exe = fluid.Executor(place)
exe.run(startup_prog)

# Save the inference model
path = "./infer_model"
fluid.io.save_inference_model(dirname=path, feeded_var_names=['img'],
             target_vars=[hidden_b], executor=exe, main_program=main_prog)

# Demo one. Not need to set the distributed look up table, because the
# training doesn't use a distributed look up table.
[inference_program, feed_target_names, fetch_targets] = (
    fluid.io.load_inference_model(dirname=path, executor=exe))
tensor_img = np.array(np.random.random((1, 64, 784)), dtype=np.float32)
results = exe.run(inference_program,
              feed={feed_target_names[0]: tensor_img},
              fetch_list=fetch_targets)

# Demo two. If the training uses a distributed look up table, the pserver
# endpoints list should be supported when loading the inference model.
# The below is just an example.
endpoints = ["127.0.0.1:2023","127.0.0.1:2024"]
[dist_inference_program, dist_feed_target_names, dist_fetch_targets] = (
    fluid.io.load_inference_model(dirname=path,
                                  executor=exe,
                                  pserver_endpoints=endpoints))
```

**Comment by L-lei** [comment]
import os
import random
import time

import numpy as np
import cv2
from paddle import fluid

curren_path = os.path.abspath(os.path.dirname(os.path.dirname('__file__')))
# model_dir = os.path.join(curren_path, 'digitRecognition/models/infer_model')
model_dir = 'models/infer_model'
#方式一
# place = fluid.CPUPlace()
# exe = fluid.Executor(place)
# exe.run(fluid.default_startup_program())
# program, feed_names, fetch_targets = fluid.io.load_inference_model(
#     dirname=model_dir,
#     executor=exe,
#     model_filename='__model__',
#     params_filename='__params__'
# )
#
#
# def run(img_list,res_data=[]):
#     img_list = [cv2.resize(img, (28, 28)) for img in img_list]
#     gray_img_list = [cv2.cvtColor(img, cv2.COLOR_BGR2GRAY) for img in img_list]
#     input_img = np.array(gray_img_list).reshape(-1, 1, 28, 28).astype('float32')
#     outs = exe.run(program,
#                    feed={feed_names[0]: input_img},
#                    fetch_list=fetch_targets,
#                    return_numpy=False)
#     if len(outs)<1:
#         res_data.append([])
#         return []
#     result = np.array(outs[0])
#
#     max_v = [float(res[np.argmax(res)]) for res in result]
#     res_data.append(max_v)
#     return max_v



# #方式二
def run(img_list,res_data=[]):
    infer_scope = fluid.core.Scope()
    with fluid.scope_guard(infer_scope):
        place = fluid.CPUPlace()
        exe = fluid.Executor(place)
        exe.run(fluid.default_startup_program())
        program, feed_names, fetch_targets = fluid.io.load_inference_model(
            dirname=model_dir,
            executor=exe,
            model_filename='__model__',
            params_filename='__params__'
        )

        img_list = [cv2.resize(img, (28, 28)) for img in img_list]
        gray_img_list = [cv2.cvtColor(img, cv2.COLOR_BGR2GRAY) for img in img_list]
        input_img = np.array(gray_img_list).reshape(-1, 1, 28, 28).astype('float32')
        outs = exe.run(program,
                       feed={feed_names[0]: input_img},
                       fetch_list=fetch_targets,
                       return_numpy=False)
        if len(outs)<1:
            res_data.append([])
            return []
        result = np.array(outs[0])

        max_v = [float(res[np.argmax(res)]) for res in result]
        res_data.append(max_v)
        return max_v

if __name__ == '__main__':
    # img = cv2.imread(os.path.join(curren_path, 'smoke_fire/smoke/9.jpg'))
    # max_v = run(img)
    # print(max_v)
    img_dir = os.path.join(curren_path, 'image')
    img_list=[os.path.join(img_dir,i) for i in os.listdir(img_dir)]* 10
    max_img_len = 6
    slice20=random.sample(img_list, max_img_len)


    #这是单线程是串行执行
    # for num in range(10):
    #     for i in range(max_img_len):
    #         img = cv2.imread(slice20[i])
    #         max_v=run([img])
    #         print(max_v)
    #     time.sleep(10)


    #这是多线程是并行执行
    import threading
    import time
    for num in range(10):
        thread_list = []
        res_data = []

        for i in range(max_img_len):
            img = cv2.imread(slice20[i])
            thread_list.append(threading.Thread(target=run,args=([img],res_data)))

        [t.start() for t in thread_list]
        [t.join() for t in thread_list]
        print(res_data)
        time.sleep(10)

**Comment by L-lei** [comment]
多线程版本的，infer2放到digitRecognition目录下
链接：https://pan.baidu.com/s/1Icj5LHZvGSFBRrC5si4Pjg 密码：9ado

**Comment by L-lei** [comment]
我不知道你们收到后面发的文件没，我给的对你们有用没，我打算关闭这个提问
