### ISSUE TITLE
Implementation of NewRemoteParameterUpdater use wrong type of proto configs

### ISSUE THREAD

**Issue by typhoonzero** [PaddlePaddle/Paddle#2761]
In `NewRemoteParameterUpdater.cpp:53` uses `parameters_[i]->getConfig()` which is of protobuf "ParameterConfig.proto", then the serialized data is passed to pserver and pserver use it to create a new optimizer implementation which uses "OptimizerConfig.proto", leading to wrong config of optimizers:

```
INFO[0004] New Optimizer Created with config:            ConfigSize=34 ElementType=4 ParamSize=52
INFO[0004] New Optimizer Created with config:            ConfigSize=34 ElementType=4 ParamSize=4
I0706 12:43:02.781574 20702 NewRemoteParameterUpdater.cpp:61] paddle_begin_init_params done
I0706 12:43:02.781584 20702 NewRemoteParameterUpdater.cpp:66] NewRemoteParameterUpdater initialized
b [ 0.]
w [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
```

**Comment by jacquesqiao** [comment]
ok, I will fix this

**Comment by dzhwinter** [comment]
new optimizer need to be added in python `optimizer.py`, I think.
