### ISSUE TITLE
export FLAGS_use_mkldnn=True [operator < conv2d > error] paddle.__version__=1.7.2 or paddle.__version__=1.8.4

### ISSUE THREAD

**Issue by RenyanDiao** [PaddlePaddle/Paddle#27648]
fluid模型预测，想使用mkldnn库在cpu上加速，但是却出现了错误。。
但是本身模型预测正确，use_mkl也可以。模型是res2net50
![image](https://user-images.githubusercontent.com/52916011/94384961-71167d00-0176-11eb-8713-fb3c7688f21d.png)

**Comment by jerrywgz** [comment]
请问下paddle是如何安装的呢，可以确认下安装版本是否支持mkldnn

**Comment by RenyanDiao** [comment]
> 请问下paddle是如何安装的呢，可以确认下安装版本是否支持mkldnn

我就是pip安装的cpu版本，这样是支持mkldnn的吧
![image](https://user-images.githubusercontent.com/52916011/94386719-eb490080-017a-11eb-9999-84b403f298ff.png)

**Comment by jerrywgz** [comment]
可以参考这里给配置中增加下enable_mkldnn https://www.paddlepaddle.org.cn/documentation/docs/zh/1.8/advanced_guide/inference_deployment/inference/python_infer_cn.html#id2

**Comment by RenyanDiao** [comment]
> 可以参考这里给配置中增加下enable_mkldnn https://www.paddlepaddle.org.cn/documentation/docs/zh/1.8/advanced_guide/inference_deployment/inference/python_infer_cn.html#id2

还是报错
![image](https://user-images.githubusercontent.com/52916011/94509759-a2ab4900-0247-11eb-814b-e52f7ac73000.png)

**Comment by RenyanDiao** [comment]
好像是这个模型的问题。。。换一个是可以的

**Comment by jerrywgz** [comment]
那可以看下是不是模型转换成inference model时候的问题
