### ISSUE TITLE
神经网络优化器中有用到次梯度吗？像layers.elementwise_max, layers.clip这些不可导的op是不是通过次梯度计算的？

### ISSUE THREAD

**Issue by ydchen9** [PaddlePaddle/Paddle#27674]
如题。

**Comment by jerrywgz** [comment]
是指的double backward吗，这个两个op确实还不支持

**Comment by ydchen9** [comment]
> 是指的double backward吗，这个两个op确实还不支持

不是指double backward。我是迷惑这两个（layers.elementwise_max、layers.clip）不可导的op是怎么处理它的导数的？能告诉我大致的思路吗？谢谢！在paddle中确实有用到，比如在强化学习的PPO算法中，如下图：
![QQ截图20200928182214](https://user-images.githubusercontent.com/26667822/94421039-8f509d00-01b7-11eb-9b6c-c97cb45d1466.png)

**Comment by jerrywgz** [comment]
https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/fluid/operators/clip_op.h#L53 可以参考这里的实现，在clip的反向中，直接分情况处理反向输出

**Comment by ydchen9** [comment]
好的。非常感谢。
