### ISSUE TITLE
确认networks中sequence_conv_pool的计算过程

### ISSUE THREAD

**Issue by xhzhang1212** [PaddlePaddle/Paddle#2769]
在API的介绍中（http://www.paddlepaddle.org/doc_cn/api/v2/config/networks.html#sequence-conv-pool）提到计算过程：Text input => Context Projection => FC Layer => Pooling => Output.
想进一步确认下细节
1.  Context Projection 对于文本卷积，效果举例： origin sequence is [A B C D E F G], context len is 3, then after context projection and not set padding_attr, sequence will be [ 0AB ABC BCD CDE DEF EFG FG0 ]
2. FC Layer：对于上一步中的类似『ABC』这样的词组（即 这几个词组成的词向量矩阵）通过fc层，转换为hidden dim长度的向量
3. Pooling：对于 [ 0AB ABC BCD CDE DEF EFG FG0 ] 通过FC产出的 n个 hidden dim向量，取出每个维度上最大的值，组成新的hidden dim向量，即产出结果

请问我这么理解ok么？

**Comment by lcy-seso** [comment]
这个理解完全正确。

**Comment by Canpio** [comment]
Close the issue for it has been solved.
