### ISSUE TITLE
The performance of matmul  op depends the weight

### ISSUE THREAD

**Issue by juncaipeng** [PaddlePaddle/Paddle#27704]
We find the performance of matmul op is quiet different when the weight is different.

**System information**
* Paddle inference library: develop or 1.8.4, c++ api, use mkl
* CPU: 6148
* OS: Ubuntu 16.04.5 LTS
* GCC: 4.8.5

**To Reproduce**
* Compile the inference library or download paddle_1.8.4_ubuntu_cpu_avx_mkl from [url](https://www.paddlepaddle.org.cn/documentation/docs/zh/advanced_guide/inference_deployment/inference/build_and_install_lib_cn.html)
* Download code from [url](https://pan.baidu.com/s/1WI2j8rOUW_iu-gjcUPXtKA), password: 6xs3
* Update the LIB_DIR in run.sh
* Test the performance of matmul. Except that the weight of matmul is different, the two models are the same.
    * `sh run.sh $PWD/test_model_slow $PWD/input_slow.txt`
    * `sh run.sh $PWD/test_model_fast $PWD/input_fast.txt`

**The Results**

![image](https://user-images.githubusercontent.com/52520497/94520555-0db44a00-025f-11eb-9e34-70d9b71928ea.png)

The average cost of matmul op is 9.48ms.

![image](https://user-images.githubusercontent.com/52520497/94520685-46ecba00-025f-11eb-9064-ab652bcaf7f2.png)
 
The average cost of matmul op is 0.604ms.

**Comment by juncaipeng** [comment]
@lidanqing-intel  Please analyze this problem.

**Comment by jczaja** [comment]
@juncaipeng We have seen something very similar in the past. Problem was that some of values of weights are FP32 denormalized values e.g +0, -0 etc. Then execution on such a data is very slow. To have this fixed model need to be processed at the beginning e.g. We should have a IR pass checking if values are denomrlized and if positive round it to normalized one. We have this partially done (only in pass conv+ affine_channel fuse, https://github.com/PaddlePaddle/Paddle/pull/26779/files) , but it should be checked for all model.

**Comment by lidanqing-vv** [comment]
![image](https://user-images.githubusercontent.com/47151829/95573910-73a58c00-0a2c-11eb-870c-0e8768db6480.png)

I printed the variable weights 'create_parameter_0.w_0' and matmul output 'matmul_0.tmp_0' during execution. You can see Left side which is fast model, most data are in float. Right side which is slow model, many values are in double. 

So during execution, because of the weights data itself, paddle chose double for calculation for slow model, so the right side(slow model) get  slower compared to left side (fast model)

I think Jacek's comments could help this issue.

**Comment by lidanqing-vv** [comment]
@juncaipeng  I got some help from MKL team and checked adding following code in the main function. The slow model now has same performance as fast model. Could you add these lines and verify if the customer's real model's accuracy is still good?
```
#include <pmmintrin.h>
_MM_SET_DENORMALS_ZERO_MODE(_MM_DENORMALS_ZERO_ON);
#include <xmmintrin.h>
_MM_SET_FLUSH_ZERO_MODE(_MM_FLUSH_ZERO_ON);
```

**Comment by juncaipeng** [comment]
@jczaja @lidanqing-intel  Thanks for the help.  I also verified that the performance of the two models is the same, and the customer will check the accuracy recently.

**Comment by juncaipeng** [comment]
@jczaja @lidanqing-intel   The customer has solved this problem by jczaja's method.
