### ISSUE TITLE
embedding_layer层产出的词向量的两个问题

### ISSUE THREAD

**Issue by xhzhang1212** [PaddlePaddle/Paddle#2770]
1. embedding_layer层产出的词向量是根据词语的语意距离产出还是id距离产出
问题如上。在http://www.paddlepaddle.org/doc_cn中搜索embedding_layer看到这样一句话：

利用单词Id查找该单词对应的连续向量(维度为word_dim)， 输入N个单词，输出为N个word_dim维度向量
emb = embedding_layer(input=word, size=word_dim)

这是说，embedding_layer的向量只是根据id产出的连续向量而非能表示语意距离的向量？

2. 我将embedding_layer设计为我的netword中的一层，那么在整个模型的迭代过程中，这个embedding层的产出是否也是会随着迭代而变化？

**Comment by shenhui0509** [comment]
2.会迭代变化
1.embeddding layer有weights，一般是初始化为随机值。embedding layer的主要作用是降维，其输出向量根据id距离生成，将vocab_size的高维度one-hot向量embedding到低维度。

**Comment by Canpio** [comment]
Close due to the problem has been solved.
