### ISSUE TITLE
batch_norm和data_norm的疑问

### ISSUE THREAD

**Issue by starsblinking** [PaddlePaddle/Paddle#27707]
请问paddle.fluid.layers.batch_norm和paddle.fluid.layers.data_norm有什么区别？看功能描述好像差不多，但看python源码又发现函数所调用的op需要的参数相差很多。核心问题：
1. 实现的功能都是批正则化吗？训练和预测时这两个函数分别有什么区别？
2. 为什么batch_norm有is_test和use_global_stats这两个参数而data_norm没有？难道data_norm不用区分训练和预测、全局和batch吗？？?
3. data_norm里param_attr里的batch_size是做什么用的？和我训练时设置的batch_size需要一致吗？
4. 有没有已知的运行模式上的坑（cpu、分布式之类的），比如哪个函数只能在什么模式/依赖库下跑，不然为啥需要两个函数呢?

1.8.5

**Comment by Thunderbrook** [comment]
1、是的；data_norm是统计所有节点的样本，而batch_norm不会；data_norm只支持二维输入
2、是的，data_norm不区分
3、batch_size是对样本数量这一统计量的初始化值；不需要一致
4、在分布式场景中较常使用data_norm

**Comment by starsblinking** [comment]
> 1、是的；data_norm是统计所有节点的样本，而batch_norm不会；data_norm只支持二维输入
> 2、是的，data_norm不区分
> 3、batch_size是对样本数量这一统计量的初始化值；不需要一致
> 4、在分布式场景中较常使用data_norm

1,2: “data_norm是统计所有节点的样本”，“data_norm不区分”,也就是说data_norm在训练时直接就是只用了全局变量？相当于"global_norm"?
4.分布式场景下（比如参数服务器模式下），最新全局变量保存在server，每个woker训练每个batch时从server拉取、更新后再push给server。对吧？

**Comment by Thunderbrook** [comment]
1、是的
2、可以这样理解
