### ISSUE TITLE
paddle' has no attribute 'enable_static' AIstudio上跑别人项目训练或者评估时有时候跑通有时候会出现这个报错，这是为什么。

### ISSUE THREAD

**Issue by minhoooo1** [PaddlePaddle/Paddle#27710]
File "pdseg/vis.py", line 203, in <module>
    paddle.enable_static()
AttributeError: module 'paddle' has no attribute 'enable_static'

**Comment by Thunderbrook** [comment]
可以升级下paddle版本

**Comment by GT-ZhangAcer** [comment]
版本问题，可以参考当前环境下的paddlepaddle版本+对应版本文档找到切换API
