### ISSUE TITLE
请问如何在LSTM中连接GCN网络?

### ISSUE THREAD

**Issue by Masterkmp** [PaddlePaddle/Paddle#27726]
**我用的是paddle静态图.。现在我定义好了GCN的layer**
![图片](https://user-images.githubusercontent.com/37642547/94555485-3acc2100-028e-11eb-9f60-20e5334f5096.png)
**然后想在LSTM后面拼接GCN，但是这里不知道怎么做了，官方文档和issue似乎也没有这个问题，现在写到这里**
![图片](https://user-images.githubusercontent.com/37642547/94555778-ad3d0100-028e-11eb-9c9a-508a827eef2b.png)
**现在需要用lstm_concat作为GCN网络的输入，在biLstm后面衔接GCN，请问怎么做呢？能否提供具体实现方法？
说明：我实际是在做论文复现，关于这里的GCN的输入信息看下面的图（这是pytorch代码,现在在用paddle的pgl做）**
![图片](https://user-images.githubusercontent.com/37642547/94556426-9f3bb000-028f-11eb-994d-ae6c26771d3e.png)

**Comment by ZHUI** [comment]
此处如果图结构为邻接矩阵，使用PGL较难实现。
建议先将邻接矩阵 转换为 PGL 的图结构，把图结构feed到网络中，然后再去调用 PGL  send recv 实现 GCN操作。
