### ISSUE TITLE
关于lstm进行序列输出的问题

### ISSUE THREAD

**Issue by lastrei** [PaddlePaddle/Paddle#27737]
和tensor的文本生成代码一样，比如有一段话[a,b,c,d,e] 然后我定义[a,b,c,d]为输入[b,c,d,e]为label，
输入的定义如下
```python
 data = fluid.layers.data(
        name="words", shape=[None], dtype="int64", lod_level=1)
```
没有问题，但是我同样这样定义输出label的时候就会一直报维度不对的问题，如果我把label定义为a,b,c,d后的下一个字e 然后定义label 
```python 
label = fluid.layers.data(name="label", shape=[None], dtype="int64")
```
进行训练就没有任何问题：

![image](https://user-images.githubusercontent.com/32331131/94644822-e0c66c80-031c-11eb-8f9a-a67235629cb1.png)
只预测下一个词没有问题

![image](https://user-images.githubusercontent.com/32331131/94644915-1c613680-031d-11eb-9e0e-79753e12c98a.png)
![image](https://user-images.githubusercontent.com/32331131/94644944-2d11ac80-031d-11eb-9823-5c5c80edb292.png)
但是将label指定为一个序列就会报错

麻烦问一下 ，如果让它输出一个序列，占位符里的shape格式到底该怎么写？

**Comment by Xreki** [comment]
> 但是将label指定为一个序列就会报错

请问具体是什么错误啊？
