### ISSUE TITLE
use the same pattr of a layer during one training process

### ISSUE THREAD

**Issue by yuhao2480444683** [PaddlePaddle/Paddle#27753]
I want to use the parameter of one layer calculate two same operation，how？
eg:
    here is a simple layer class, I only want one fc layer in my model, but I need to calculate two operation use this fc layer.
If i define as follow, there are two different fc parameter.

    any_layer(data1, data2)

    {

        output1 = fluid.layer.fc(input=data1)

        output2 =  fluid.layer.fc(input=data2)

    }

What I want is:
    output1 = fc(data1)  output2 = fc(data2)
but they use the same parameter for one fc layer, how?

Then, is there a easy way to use BiDirectional LSTM in dygragh model, I want to define the param of BDLSTM in __init__ function

Thank you for answering.

**Comment by yuhao2480444683** [comment]
fc is very simple, it have a param as W, which can define in __init__ function.
But I use the model in exe.run, it doesn't have the init and forward function, only has model definition.

**Comment by heavengate** [comment]
fc API has an arguments as `param_attr` for parameter definition, define both parameter with the same name and they will share the same parameter
