### ISSUE TITLE
fleetrun: command not found

### ISSUE THREAD

**Issue by Frank00001** [PaddlePaddle/Paddle#27757]
- 版本、环境信息：
    1）PaddlePaddle版本：1.8.5
    2）GPU：cuda10.0,cudnn7.6.4
    3）系统环境：ubuntu16.04、Python3.6

- 安装方式信息：
1）pip安装paddlepaddle和fleet-x
python -m pip install paddlepaddle-gpu==1.8.5.post107 
pip install fleet-x
 2）nccl安装
nccl版本为2.6.3   
3)mpich（MPI）安装
sudo apt-get install -y mpich

问题：我们想使用FleetAPI运行paddle分布式代码的时候，输入fleetrun命令时，出现fleetrun: command not found的错误
![image](https://user-images.githubusercontent.com/43396077/95037369-5ce5f900-06fd-11eb-970f-84e2bb25b5b4.png)

**Comment by Frank00001** [comment]
> 你好，可以pip list 看下安装情况
您好，pip list安装情况如下
Package              Version                 
-------------------- ------------------------
absl-py              0.7.1                   
astor                0.8.0                   
backcall             0.1.0                   
bleach               3.0.2                   
certifi              2018.10.15              
cffi                 1.11.5                  
chainer              4.5.0                   
chardet              3.0.4                   
click                7.1.2                   
cloudpickle          0.6.1                   
cntk-gpu             2.6                     
cycler               0.10.0                  
Cython               0.29                    
dask                 0.20.0                  
decorator            4.3.0                   
entrypoints          0.2.3                   
filelock             3.0.10                  
fleet-x              0.0.5                   
funcsigs             1.0.2                   
gast                 0.3.3                   
get                  1.0.3                   
google-pasta         0.1.7                   
graphviz             0.8.4                   
grpcio               1.14.1                  
grpcio-tools         1.32.0                  
h5py                 2.9.0                   
idna                 2.6                     
ipykernel            5.1.0                   
ipython              7.1.1                   
ipython-genutils     0.2.0                   
ipywidgets           7.4.2                   
jedi                 0.13.1                  
Jinja2               2.10                    
joblib               0.17.0                  
jsonschema           2.6.0                   
jupyter              1.0.0                   
jupyter-client       5.2.3                   
jupyter-console      6.0.0                   
jupyter-core         4.4.0                   
Keras                2.2.4                   
Keras-Applications   1.0.8                   
Keras-Preprocessing  1.1.0                   
kiwisolver           1.0.1                   
lightgbm             2.2.1                   
Mako                 1.0.7                   
Markdown             3.1.1                   
MarkupSafe           1.0                     
matplotlib           3.0.0                   
mistune              0.8.4                   
mkl-fft              1.0.6                   
mkl-random           1.0.1                   
mmdnn                0.3.1                   
mock                 3.0.5                   
mxnet                1.3.0.post0             
nbconvert            5.3.1                   
nbformat             4.4.0                   
networkx             2.2                     
nltk                 3.5                     
notebook             5.6.0                   
numpy                1.15.4                  
objgraph             3.4.1                   
opencv-python        3.4.3.18                
paddlepaddle-gpu     1.8.5.post107           
pandas               0.23.4                  
pandocfilters        1.4.2                   
parso                0.3.1                   
pathlib              1.0.1                   
pexpect              4.6.0                   
pickleshare          0.7.5                   
Pillow               7.2.0                   
pip                  18.1                    
post                 1.0.2                   
prettytable          1.0.0                   
prometheus-client    0.4.2                   
prompt-toolkit       2.0.7                   
protobuf             3.6.1                   
ptyprocess           0.6.0                   
public               2.0.1                   
pycparser            2.19                    
pydot                1.2.4                   
Pygments             2.2.0                   
pygpu                0.7.6                   
pyparsing            2.2.2                   
python-dateutil      2.7.5                   
pytz                 2018.5                  
PyWavelets           1.0.1                   
PyYAML               3.13                    
pyzmq                17.1.2                  
qtconsole            4.4.2                   
query-string         1.0.2                   
rarfile              4.0                     
regex                2020.9.27               
request              1.0.2                   
requests             2.24.0                  
scikit-image         0.14.1                  
scikit-learn         0.20.0                  
scipy                1.1.0                   
Send2Trash           1.5.0                   
setuptools           40.5.0                  
six                  1.11.0                  
sklearn              0.0                     
tensorboard          1.14.0                  
tensorflow           1.14.0                  
tensorflow-estimator 1.14.0                  
termcolor            1.1.0                   
terminado            0.8.1                   
testpath             0.4.2                   
tflearn              0.3.2                   
Theano               1.0.3+2.g3e47d39ac.dirty
toolz                0.9.0                   
torch                0.4.1                   
torchfile            0.1.0                   
torchnet             0.0.4                   
torchvision          0.2.1                   
tornado              5.1.1                   
tqdm                 4.28.1                  
traitlets            4.3.2                   
urllib3              1.22                    
visdom               0.1.8.5                 
wcwidth              0.1.7                   
webencodings         0.5.1                   
websocket-client     0.53.0                  
Werkzeug             0.15.5                  
wheel                0.32.2                  
widgetsnbextension   3.4.2                   
wrapt                1.11.2                  
xgboost              0.80

**Comment by ceci3** [comment]
https://fleet-x.readthedocs.io/en/latest/paddle_fleet_rst/fleetrun_usage_cn.html#id2. 您好，文档里的使用要求是要安装paddlepaddle 2.0rc或以上版本 
![image](https://user-images.githubusercontent.com/29245900/95535781-dc383d00-0a1b-11eb-87e9-b776a8817561.png)

**Comment by ceci3** [comment]
你好，需要安装develop版本的paddle

**Comment by Frank00001** [comment]
请问paddle的develop版本如何安装呢？我使用python -m pip install paddlepaddle 2.0-rc安装失败！
![image](https://user-images.githubusercontent.com/43396077/95540898-8ae07b80-0a24-11eb-8e00-f6c94595d95c.png)

**Comment by ceci3** [comment]
2.0rc版本还没发布，develop版本安装链接：https://www.paddlepaddle.org.cn/documentation/docs/zh/install/Tables.html#whl-dev

**Comment by Frank00001** [comment]
> 2.0rc版本还没发布，develop版本安装参考链接：https://www.paddlepaddle.org.cn/documentation/docs/zh/install/Tables.html#whl-dev
按照paddlepaddle给出的分布式collective文档https://fleet-x.readthedocs.io/en/latest/paddle_fleet_rst/fleet_collective_training_practices_cn.html#resnet50，在运行fleet.init(is_collective=True)发生错误：Gloo init with FILE: need_init_all: False, args: {'dfs.path': '/tmp/tmpl5o0ej9l', 'store.prefix': ''}
具体错误如下:
/usr/local/miniconda3/envs/dl/lib/python3.6/site-packages/sklearn/externals/joblib/externals/cloudpickle/cloudpickle.py:47: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp
Gloo init with FILE: need_init_all: False, args: {'dfs.path': '/tmp/tmpl5o0ej9l', 'store.prefix': ''}
Traceback (most recent call last):
  File "fleet.py", line 21, in <module>
    fleet.init(is_collective=True)
  File "/usr/local/miniconda3/envs/dl/lib/python3.6/site-packages/paddle/distributed/fleet/base/fleet_base.py", line 183, in init
    self._role_maker._generate_role()
  File "/usr/local/miniconda3/envs/dl/lib/python3.6/site-packages/paddle/distributed/fleet/base/role_maker.py", line 837, in _generate_role
    self._gloo_init()
  File "/usr/local/miniconda3/envs/dl/lib/python3.6/site-packages/paddle/distributed/fleet/base/role_maker.py", line 823, in _gloo_init
    server_num=self._server_num(),
  File "/usr/local/miniconda3/envs/dl/lib/python3.6/site-packages/paddle/distributed/fleet/base/role_maker.py", line 608, in _server_num
    return len(self._get_pserver_endpoints())
TypeError: object of type 'NoneType' has no len()

**Comment by danleifeng** [comment]
> https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/install/Tables.html#whl-dev
您好，官网提供的develop 分支whl包可能会有延迟性，您的问题已经在最新的develop分支代码中解决。
可以期待一下10.28发布的paddle-2.0rc稳定版本。
如果想尽快试用fleet分布式训练最新功能，可以选择使用源码编译paddle：https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/install/compile/compile_Ubuntu.html#ubuntu
