### ISSUE TITLE
训练/预测时偶发性报错Compiled with WITH_GPU, but no GPU found in runtime.

### ISSUE THREAD

**Issue by topxxuki** [PaddlePaddle/Paddle#27752]
Thank you for contributing to PaddlePaddle. Submitting an issue is a great help for us.
Both Chinese and English issues are welcome.

It's hard to solve a problem when important details are missing.
Before submitting the issue, look over the following criteria before handing your request in.

- [ ] Was there a similar issue submitted or resolved before ? You could search issue in the github.
- [ ] Did you retrieve your issue from widespread search engines ?
- [ ] Is my description of the issue clear enough to reproduce this problem?
   * If some errors occurred, we need details about `how do you run your code?`, `what system do you use?`, `Are you using GPU or not?`, etc.
   * If you use an recording [asciinema](https://asciinema.org/) to show what you are doing to make it happen, that's awesome! We could help you solve the problem more quickly.
- [ ] Is my description of the issue use the github markdown correctly?
   * Please use the proper markdown syntaxes for styling all forms of writing, e.g, source code, error information, etc.
   * Check out [this page](https://guides.github.com/features/mastering-markdown/) to find out much more about markdown.
在同一个机器上运行代码，偶发性报错Compiled with WITH_GPU, but no GPU found in runtime.

![image](https://user-images.githubusercontent.com/18697846/94896582-6fbfba00-04c0-11eb-83c4-3723b03d0bb8.png)

GPU型号 
![image](https://user-images.githubusercontent.com/18697846/94896620-8534e400-04c0-11eb-9c63-8b6e9a284e3f.png)

paddlepaddle-gpu 1.6.1.post97
本地cuda版本9.0.176

**Comment by heavengate** [comment]
看着是偶现检测不到GPU，可以确认一下CUDA，nvidia driver这些是否正确安装，版本是否匹配
