### ISSUE TITLE
3080显卡无法使用paddle(it dosen't work in RTX 3080)

### ISSUE THREAD

**Issue by limulimu** [PaddlePaddle/Paddle#27751]
paddle.fluid.check_install.run_check()卡死，等待无结果，GPU满负荷，不消耗显存。
显卡为MSI RTX3080 主机为MSI P100。WIN10 64位专业版。
1.paddle版本1.8-1.8.5均试过不行。
2.CUDA 9,10,10.2,11 均不行，cudnn7.6 8.1也均不行。
3.pip 安装和 anaconda 安装也均不行。

另外我的老机器是是2070MQ的，经常容易出现无法申请到显存，然后强退的错误。

**Comment by DDDivano** [comment]
nvidia-gpu 架构目前发布的包只支持到最高Turing架构，即sm75，3080是Ampere架构sm80，发布包目前不支持这个架构，可以根据官网教程自行编译一个包。
