### ISSUE TITLE
paddle2.0编译出现多处依赖库找不到

### ISSUE THREAD

**Issue by mysalter** [PaddlePaddle/Paddle#27762]
paddle2.0编译出现多处依赖库找不到
以下列举几个：
718>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(234,5): warning MSB8064: 项“D:\lkx\paddle\Paddle\build\CMakeFiles\1687d9c4cada6a917d1934f54e48b5b0\paddle_fluid_dummy_7_dummy.c.rule”的自定义生成成功，但指定的依赖项“d:\lkx\paddle\paddle\build\paddle\fluid\operators\release\libcorrelation_op.lib”不存在。这可能会导致增量生成无法正常工作。
718>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(234,5): warning MSB8064: 项“D:\lkx\paddle\Paddle\build\CMakeFiles\1687d9c4cada6a917d1934f54e48b5b0\paddle_fluid_dummy_7_dummy.c.rule”的自定义生成成功，但指定的依赖项“d:\lkx\paddle\paddle\build\paddle\fluid\operators\release\libcos_sim_op.lib”不存在。这可能会导致增量生成无法正常工作。
718>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(234,5): warning MSB8064: 项“D:\lkx\paddle\Paddle\build\CMakeFiles\1687d9c4cada6a917d1934f54e48b5b0\paddle_fluid_dummy_7_dummy.c.rule”的自定义生成成功，但指定的依赖项“d:\lkx\paddle\paddle\build\paddle\fluid\operators\release\libcrf_decoding_op.lib”不存在。这可能会导致增量生成无法正常工作。
718>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(234,5): warning MSB8064: 项“D:\lkx\paddle\Paddle\build\CMakeFiles\1687d9c4cada6a917d1934f54e48b5b0\paddle_fluid_dummy_7_dummy.c.rule”的自定义生成成功，但指定的依赖项“d:\lkx\paddle\paddle\build\paddle\fluid\operators\release\libcrop_op.lib”不存在。这可能会导致增量生成无法正常工作。
718>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(234,5): warning MSB8064: 项“D:\lkx\paddle\Paddle\build\CMakeFiles\1687d9c4cada6a917d1934f54e48b5b0\paddle_fluid_dummy_7_dummy.c.rule”的自定义生成成功，但指定的依赖项“d:\lkx\paddle\paddle\build\paddle\fluid\operators\release\libcrop_tensor_op.lib”不存在。这可能会导致增量生成无法正常工作。
718>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(234,5): warning MSB8064: 项“D:\lkx\paddle\Paddle\build\CMakeFiles\1687d9c4cada6a917d1934f54e48b5b0\paddle_fluid_dummy_7_dummy.c.rule”的自定义生成成功，但指定的依赖项“d:\lkx\paddle\paddle\build\paddle\fluid\operators\release\libcross_entropy_op.lib”不存在。这可能会导致增量生成无法正常工作。
718>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(234,5): warning MSB8064: 项“D:\lkx\paddle\Paddle\build\CMakeFiles\1687d9c4cada6a917d1934f54e48b5b0\paddle_fluid_dummy_7_dummy.c.rule”的自定义生成成功，但指定的依赖项“d:\lkx\paddle\paddle\build\paddle\fluid\operators\release\libcross_op.lib”不存在。这可能会导致增量生成无法正常工作。
718>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(234,5): warning MSB8064: 项“D:\lkx\paddle\Paddle\build\CMakeFiles\1687d9c4cada6a917d1934f54e48b5b0\paddle_fluid_dummy_7_dummy.c.rule”的自定义生成成功，但指定的依赖项“d:\lkx\paddle\paddle\build\paddle\fluid\operators\release\libctc_align_op.lib”不存在。这可能会导致增量生成无法正常工作。
718>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(234,5): warning MSB8064: 项“D:\lkx\paddle\Paddle\build\CMakeFiles\1687d9c4cada6a917d1934f54e48b5b0\paddle_fluid_dummy_7_dummy.c.rule”的自定义生成成功，但指定的依赖项“d:\lkx\paddle\paddle\build\paddle\fluid\operators\release\libcudnn_lstm_op.lib”不存在。这可能会导致增量生成无法正常工作。

**Comment by wzzju** [comment]
VS2017和VS2019还没有支持，可能会存在一些问题，建议尝试使用VS2015进行Paddle windows编译。
