### ISSUE TITLE
vs2019编译的时候 找不到framework.pb.h

### ISSUE THREAD

**Issue by mysalter** [PaddlePaddle/Paddle#27761]
paddle 2.0编译
多处出现D:/lkx/paddle/Paddle\paddle/fluid/framework/attribute.h(23): fatal error C1083: 无法打开包括文件: “paddle/fluid/framework/framework.pb.h”: No such file or directory

**Comment by wzzju** [comment]
VS2017和VS2019还没有支持，可能会存在一些问题，建议尝试使用VS2015进行Paddle windows编译。
