### ISSUE TITLE
Variable need to support reference

### ISSUE THREAD

**Issue by Superjomn** [PaddlePaddle/Paddle#2777]
In one step of RNN, a previous state's memory is needed, so it is natural to have a design with multiple `Scope`s as follows:

- create a `state` and a `pre-state` in current step scope
- reference current `pre-state` to the `state` in preivous step scope (or copy the variable)

So, if the Variable support `reference`,  it will help to save the copy.

**Comment by luotao1** [comment]
If the Variable don't support `shareDataFrom`, the code is : 
```
auto mem = scope->CreateVariable(attr.pre_var)->GetMutable<Tensor>(); 
auto linked_mem = linked_scope->GetVariable(attr.var)->GetMutable<Tensor>(); 
mem->ShareDataFrom<float>(*linked_mem);
```
else, the code will be simpler:
```
auto mem = scope->CreateVariable(attr.pre_var);
auto linked_mem = linked_scope->GetVariable(attr.var)
mem->ShareDataFrom(*linked_mem);
```
