### ISSUE TITLE
使用while循环预测主题报错

### ISSUE THREAD

**Issue by Derek-Kun** [PaddlePaddle/Paddle#27782]
我在paddle的image_classification代码里加入了while语句循环Main方法， 并检测一个文件夹内有没有图片，有图片的话就执行一次main函数，然后删掉文件夹内的图片，等下一张图片传入到该文件夹的时候while循环语句检测到新的图片，于是又执行main方法，类似于这样
![图片](https://user-images.githubusercontent.com/57475881/95559947-1f5dd480-0a4b-11eb-88fb-d6a9d2b0bb32.png)
可是只有在第一次循环的时候有效，第二次循环的时候就会报错：
UnavailableError: Load operator fail to open file /home/video_cls/models/PaddleCV/image_classification/output/ResNet200_vd_pretrained/fc_1.w_0, please check whether the model file is complete or damaged.   [Hint: Expected static_cast<bool>(fin) == true, but received static_cast<bool>(fin):0 != true:1.] at (/paddle/paddle/fluid/operators/load_op.h:41)   [operator < load > error]

看原因应该是这行代码有问题：
![图片](https://user-images.githubusercontent.com/57475881/95560005-33a1d180-0a4b-11eb-9f60-f379f31a47aa.png)

请问该如何实现让infer.py的main方法循环预测？

**Comment by MRXLT** [comment]
你好，如果是想要进行预测可以参考这个链接https://www.paddlepaddle.org.cn/documentation/docs/zh/advanced_guide/inference_deployment/inference/python_infer_cn.html#id7
不需要每次都进行参数的加载
