### ISSUE TITLE
怎么加载预训练的embedding层，（embedding里面的两个脚本怎么使用）

### ISSUE THREAD

**Issue by WoNiuHu** [PaddlePaddle/Paddle#2778]
RT. 现在需要将paddlepaddle框架里面的embedding层替换成我在网络上找到的word2vec字典，然后用这个字典来embedding, 这个embedding层怎么外接。另外看到embedding目录下有三个脚本，请问这个脚本怎么使用。谢谢

**Comment by guoshengCS** [comment]
加载预训练的embedding层的话如下：
```python
# 通过is_static=True设置embedding层的param_attr为固定
emb_para = paddle.attr.Param(name='emb', initial_std=0., is_static=True)
paddle.layer.embedding(size=word_dim, input=x, param_attr=emb_para)
```
```python
# 创建parameters后将embedding层参数赋值为预训练的词向量
parameters = paddle.parameters.create(crf_cost)
parameters.set('emb', load_parameter(conll05.get_embedding(), 44068, 32))
```
完整示例见PaddleBook[语义角色标注](https://github.com/PaddlePaddle/book/blob/develop/07.label_semantic_roles/train.py)一节。

另外，不是特别清楚embedding目录是指的哪个示例，可以的话给下链接吧。

**Comment by luotao1** [comment]
> embedding层替换成我在网络上找到的word2vec字典，然后用这个字典来embedding

可以直接换字典，用新的字典来做embedding

**Comment by Canpio** [comment]
已经线下解答

**Comment by HynUx** [comment]
疑问:
1.  求parameters.set的文档, 各参数意义, 对不同类型的layers的参数预定义时, 传入的初始化参数有啥格式要求
2. 如果要对加载的pre-train词表继续进行训练或者finetune, 是不是定义embedding的时候is_static=False就可以了?

**Comment by zishuaiz** [comment]
api文档写详细点吧
用paddle太痛苦了，api全靠猜！

**Comment by guoshengCS** [comment]
1. `parameters.set`接受两个参数，第一个是该param在网络配置时的name，第二个是类型是`np.ndarray` 的matrix；设置embedding的话，一行是一个word的词向量，行号对应index，注意在data_provider产生数据时对每个word给出对应的index
2. 如果要继续训练设置`is_static=False`即可

**Comment by MangoLiu** [comment]
说实话，在NLP文本上，paddle还真不如lego好用。
各种疑惑。
lego和paddle合并，很是不解和苦恼。

**Comment by zhishui3** [comment]
> 加载预训练的embedding层的话如下：
> 
> ```python
> # 通过is_static=True设置embedding层的param_attr为固定
> emb_para = paddle.attr.Param(name='emb', initial_std=0., is_static=True)
> paddle.layer.embedding(size=word_dim, input=x, param_attr=emb_para)
> ```
> 
> ```python
> # 创建parameters后将embedding层参数赋值为预训练的词向量
> parameters = paddle.parameters.create(crf_cost)
> parameters.set('emb', load_parameter(conll05.get_embedding(), 44068, 32))
> ```
> 
> 完整示例见PaddleBook[语义角色标注](https://github.com/PaddlePaddle/book/blob/develop/07.label_semantic_roles/train.py)一节。
> 
> 另外，不是特别清楚embedding目录是指的哪个示例，可以的话给下链接吧。

您好，请问
emb_para = paddle.attr.Param(name='emb', initial_std=0., is_static=True)
paddle.layer.embedding(size=word_dim, input=x, param_attr=emb_para)
这个怎么用的，怎么报错
emb_para = paddle.attr.Param(name='emb', initial_std=0., is_static=True)
AttributeError: 'module' object has no attribute 'attr'

**Comment by guoshengCS** [comment]
@zhishui3 这个已经是比较老的版本了，新版本使用参考这里 https://www.paddlepaddle.org.cn/documentation/docs/zh/faq/train_cn.html#q-embedding

**Comment by zhishui3** [comment]
> @zhishui3 这个已经是比较老的版本了，新版本使用参考这里 https://www.paddlepaddle.org.cn/documentation/docs/zh/faq/train_cn.html#q-embedding
O(∩_∩)O谢谢您！
