### ISSUE TITLE
paddle2.0beta 安装文档出现严重错误！

### ISSUE THREAD

**Issue by ralph0813** [PaddlePaddle/Paddle#27794]
下午尝试安装paddle2.0beta版本时参考ubuntu安装文档，确认到可以使用cuda10.1，但是一直出现报错:
`Error: Failed to find dynamic library: libcublas.so ( libcublas.so: cannot open shared object file: No such file or directory ) `
来回折腾一下午，甚至重装系统，从20.04降级到18.04，问题仍然无法解决。后来尝试使用cuda10.0问题解决了！
请尽快修改文档，避免其他开发者在环境配置方面耽误太多时间！

文档链接：https://www.paddlepaddle.org.cn/documentation/docs/zh/2.0-beta/install/install_Ubuntu.html

错误位置：环境准备 GPU 版本支持 CUDA 10.0/10.1

**Comment by MRXLT** [comment]
感谢反馈，我们会尽快更新文档
