### ISSUE TITLE
解压训练模型失败

### ISSUE THREAD

**Issue by xhzhang1212** [PaddlePaddle/Paddle#2779]
![image](https://user-images.githubusercontent.com/29705965/27992107-57d97584-64be-11e7-8c0c-5106ce6c1f6f.png)
压缩模型时的语句：
![image](https://user-images.githubusercontent.com/29705965/27992112-6cfeb5f0-64be-11e7-966f-afacea90874c.png)
解压模型时的语句：
![image](https://user-images.githubusercontent.com/29705965/27992120-962b9420-64be-11e7-90ba-90df912bda93.png)
请问我该如何解决

**Comment by xhzhang1212** [comment]
tar -xf 是可以成功解压的~~解决方案：
1. tar -xf cnn_params_pass_00006.tar.gz
2. tar -zcf cnn_params_pass_00006_new.tar.gz ___*
新模型就可以用了~~cnn_params_pass_00006_new.tar.gz

**Comment by jzh1992** [comment]
我也遇到这个问题, 感谢楼主
