### ISSUE TITLE
预测时加载模型报错

### ISSUE THREAD

**Issue by yeguang1991** [PaddlePaddle/Paddle#27801]
使用fluid.io.save_persistables()保存模型，传入filename='model',
加载时时同样传入filename='model'，
fluid.io.load_persistables(self._exe, model_path, main_program=self._pred_init_prog, filename='model')

报错：
![image](https://user-images.githubusercontent.com/66579493/95647701-23016200-0b04-11eb-9e6d-a7d41237c203.png)

**Comment by lijianshe02** [comment]
报错日志打不开，还请提供详细的报错信息

**Comment by lijianshe02** [comment]
请check模型路径是否正确

**Comment by yeguang1991** [comment]
@lijianshe02 模型路径跟filename=None时，使用的路径一样，filename=None时可以正常保存和加载，filename='model'时，会出现上述错误
