### ISSUE TITLE
文本分类的attention机制

### ISSUE THREAD

**Issue by Masterkmp** [PaddlePaddle/Paddle#27821]
paddle官方没有关于文本分类的attention机制静态代码的实现，请问能否提供完整代码？

**Comment by lijianshe02** [comment]
这个没有哈，有一些翻译文本生成上使用attention的不知道是否可以参考来搞
https://github.com/PaddlePaddle/models/tree/release/1.8/PaddleNLP/machine_translation/transformer
https://github.com/PaddlePaddle/models/tree/release/1.8/PaddleNLP/seq2seq/seq2seq
