### ISSUE TITLE
lstm拼接attention报错

### ISSUE THREAD

**Issue by Masterkmp** [PaddlePaddle/Paddle#27825]
意实现这里
![图片](https://user-images.githubusercontent.com/37642547/95681836-8ed2f000-0c14-11eb-8966-2a52080ddabf.png)
怎么写呢？（下面的不对）
![图片](https://user-images.githubusercontent.com/37642547/95681841-972b2b00-0c14-11eb-95c3-c8e3503fd430.png)

**Comment by bjjwwang** [comment]
不好意思才收到 我查看一下
