### ISSUE TITLE
<论文复现> paddle中convLSTM的实现？

### ISSUE THREAD

**Issue by zhongqing0507** [PaddlePaddle/Paddle#27826]
paddle中如何实现convLSTM？？比较急！谢谢。

**Comment by hong19860320** [comment]
Paddle官方还没有支持，但是我在github找到了一个实现 https://github.com/xyzhou-puck/paddle_in_example/blob/e049a9154e2d42f03b13092801bc1e061b8e762b/part4%20easy%20tutorials/conv_lstm/ConvLSTM.py
这位同学是Paddle NLP的大佬，值得信赖^^
