### ISSUE TITLE
使用CPU预测报错 Intel MKL function load error: cpu specific dynamic library is not loaded.

### ISSUE THREAD

**Issue by Derek-Kun** [PaddlePaddle/Paddle#27842]
我用paddle目录下的image_classification里的infer对图片进行分类，在GPU上运行时一切正常，可是当参数设置use_gpu=False后预测，就会报错  Intel MKL function load error: cpu specific dynamic library is not loaded. 我定位了一下发现报错位置是这一行代码
，
![图片](https://user-images.githubusercontent.com/57475881/95704360-22430a00-0c83-11eb-8e0b-0eee5643feef.png)

在网上查也没找到相关问题，请问如何处理？

**Comment by hong19860320** [comment]
试试这两个issue中的解决办法 https://github.com/PaddlePaddle/PaddleOCR/issues/673 https://github.com/PaddlePaddle/PaddleOCR/issues/440

**Comment by Derek-Kun** [comment]
好的我研究一下，感谢

**Comment by Derek-Kun** [comment]
问题已解决，亲测之前的换scipy和numpy版本方法可用
paddlepaddle==1.8.3
scipy==1.1.0
paddlehub==1.7.1
numpy==1.19.1

**Comment by wangzhanwei666** [comment]
paddlepaddle==2.2.2
paddleocr==2.4
scipy==1.5.0
numpy=1.19.1
亲测可用，主要是numpy的版本得升以下，原来1.18.5不行，报上面的错误

**Comment by wangdacheng** [comment]
paddlepaddle==2.2.2
paddleocr==2.4
scipy==1.6.3
numpy==1.19.3

will solve this problem.

**Comment by riwkjh** [comment]
For my case, I encountered with numpy version 1.2.1, and after downgraded to 1.20 the error disappeared. 
My setting is:
paddlepaddle==2.2.2
paddleocr==2.4
scipy==1.7.3
numpy==1.20

**Comment by greenfigo2015** [comment]
paddleocr                 2.5.0.3                 
paddlepaddle              2.3.1                  
scipy                     1.8.1                 
numpy                     1.22.3          

when in CPU mode, it will also have the same bug, any clue to solve it?

Thanks.

**Comment by enkhtogtokh** [comment]
Just upgrade your numpy. That fixed the problem.
My case numpy==1.21.0 cause some other libs needs this old version. But it fixes the problem.
