### ISSUE TITLE
怎么关闭某些参数的梯度更新

### ISSUE THREAD

**Issue by AWSWXY** [PaddlePaddle/Paddle#27894]
想咨询下如何关闭某些参数的更新，使用什么api

**Comment by wangchaochaohu** [comment]
param_attr中的learning_rate设置为0就可以了

**Comment by AWSWXY** [comment]
有没有相关的项目，模型 可以参考

**Comment by wangchaochaohu** [comment]
https://github.com/PaddlePaddle/models/blob/release/1.8/PaddleCV/gan/network/base_network.py#L55 可以参考下

**Comment by starsblinking** [comment]
> param_attr中的learning_rate设置为0就可以了

请问这么操作的话是不是只会影响这个被修改learning_rate的参数，网络中反向传播的梯度值、其他persistable参数的梯度与最终的更新值不变、与这个被修改的learning_rate无关？
