### ISSUE TITLE
var src_ids not in this block

### ISSUE THREAD

**Issue by shikeno** [PaddlePaddle/Paddle#27916]
为使您的问题得到快速解决，在建立Issue前，请您先通过如下方式搜索是否有相似问题:【搜索issue关键字】【使用labels筛选】【官方文档】

建立issue时，为快速解决问题，请您根据使用情况给出如下信息：
- 标题：简洁、精准描述您的问题，例如“ssd 模型前置lstm报错  ”
- 版本、环境信息：
    1）PaddlePaddle版本：1.6.2.post97
    2）CPU：Intel(R) Xeon(R) Gold 6271C CPU @ 2.60GHz
    3）GPU：T4, cuda10.1

问题：
我有一个训练好的bert的inference_model，我需要params文件所以我想用load_inference_model，和save_inference_model转化出来params文件。我并不知道里面有哪些层，所以就有了下面的代码，但是利用load_inference_model接口拿到的feed_target_names 并不能在save接口里面使用，提示『var src_ids not in this block』。
有什么办法可以解决『var src_ids not in this block』这个问题，或者可以让我生成一个params文件吗。我现在只有一个模型，没有其他的

代码
import paddle.fluid as fluid

exe = fluid.Executor(fluid.CPUPlace())
param_path = "./models/"
prog = fluid.default_main_program()
[inference_program, feed_target_names, fetch_targets] = fluid.io.load_inference_model(executor=exe, dirname=param_path)

fluid.io.save_inference_model(dirname=".", feeded_var_names=feed_target_names, target_vars=fetch_targets, executor=exe, params_filename="params")

**Comment by chenwhql** [comment]
你是想把分散存储的params转换成存储到一个大文件中吗

**Comment by shikeno** [comment]
> 你是想把分散存储的params转换成存储到一个大文件中吗

是的

**Comment by chenwhql** [comment]
save_inference_model的时候指定下吗main_program参数试试呢
![image](https://user-images.githubusercontent.com/22561442/95958500-cc619400-0e33-11eb-9c03-ec8868799408.png)
main_program= inference_program

**Comment by shikeno** [comment]
> save_inference_model的时候指定下吗main_program参数试试呢
> ![image](https://user-images.githubusercontent.com/22561442/95958500-cc619400-0e33-11eb-9c03-ec8868799408.png)
> main_program= inference_program

嗯嗯，用这个参数可以了！感谢同学！
