### ISSUE TITLE
Add command values to beginning of log and use paddle.enable_mkldnn()) to instead of FLAGS_use_mkldnn

### ISSUE THREAD

**Issue by lidanqing-vv** [PaddlePaddle/Paddle#27935]
Customer request:

Could you add some MKLDNN-related print log when use FLAGS_use_mkldnn?
Could you add new api like paddle.enable_static() (eg. paddle.enable_mkldnn()) to instead of FLAGS_use_mkldnn?

Dygraph training doc
[Dygraph_Training_Reproduction.txt](https://github.com/PaddlePaddle/Paddle/files/5383932/Dygraph_Training_Reproduction.txt)

**Comment by luotao1** [comment]
Discussed with @OliverLPH,  in order to see whether we use the mkldnn in th log ([train_Resnet_b32_real2.log](https://github.com/PaddlePaddle/Paddle/files/5406095/train_Resnet_b32_real2.log), now we must use `export MKLDNN_VERBOSE=1`) easily
- Could you add some MKLDNN-related print log when use `FLAGS_use_mkldnn`?
- Could you add new api like `paddle.enable_static()` (eg. `paddle.enable_mkldnn()`) to instead of `FLAGS_use_mkldnn`?

**Comment by OliverLPH** [comment]
@lidanqing-intel 
By following your reproduce document, here is my test results, plz have a look.

model | dataset | type | mode | acc result | comment
-- | -- | -- | -- | -- | --
Resnet_b32 | flowers | OneDNN | real | acc1: 75.10%  acc5: 93.40% | OMP=20


model | dataset | type | mode | epoch_cost(s) | RSS memory(KB) | RSS memory(MB) | comment
-- | -- | -- | -- | -- | -- | -- | --
Resnet_b32 | flowers | OneDNN | CE | 285.27 | 5152648 | 5031.88 | OMP=20
Resnet_b32 | flowers | Native | CE | 1062.77 | 3319124 | 3241.33 | OMP=20

It seems when enable mkldnn, it has rapid speed-up compared with disable it.
However, it also occpy around 2GB more memory costs.

Another thing need to notice is when disbale mkldnn, trainning process will get NaN
![image](https://user-images.githubusercontent.com/14963836/96549756-7fbe0300-12e2-11eb-88f3-ebdb3ac6f9ae.png)

**Comment by lidanqing-vv** [comment]
@arlesniak  Hi, Artur, please add command values to log, and use paddle.enable_mkldnn()) to instead of FLAGS_use_mkldnn.

**Comment by arlesniak** [comment]
We can add flag value to the beginning of the models repo Resnet log.

**Comment by arlesniak** [comment]
As we agreed lately [PR 25773](https://github.com/PaddlePaddle/Paddle/pull/25773) mkldnn code is depending on using global FLAGS_use_mkldnn
