### ISSUE TITLE
paddlepaddle-tiny源码

### ISSUE THREAD

**Issue by chengji77** [PaddlePaddle/Paddle#27934]
请问PyPi上paddlepaddle-tiny是从这个repo编译来的吗？

我们现在需要在arm64上运行paddlepaddle-tiny，PyPi上没有现成的wheel，但找不到对应的源码。

**Comment by chenwhql** [comment]
https://github.com/PaddlePaddle/Paddle/tree/paddle_tiny_install

应该是从一个分支编译来的，但已经不再维护了

**Comment by chengji77** [comment]
谢谢
