### ISSUE TITLE
Conv_bias_mkldnn_fuse_pass supports the dilations be any value

### ISSUE THREAD

**Issue by juncaipeng** [PaddlePaddle/Paddle#27931]
When the dilations of conv is not 1, the conv_bias_mkldnn_fuse_pass will fail.

#27329 has fixed the bug as [url](https://github.com/PaddlePaddle/Paddle/pull/27329/files#diff-f7483bc545486c858e8c7d04701c3dee3ce237affb50401814c72c20194b5741R88), and it skips fusing conv + bias when the dilations is 1.

@lidanqing-intel  Please check whether the conv_bias_mkldnn_fuse_pass can support the dilations be any value.

**Comment by lidanqing-vv** [comment]
@juncaipeng #27914 This PR support dilated conv of any values, and I remove the PADDLE_ENFORCE in conv_bias_mkldnn_fuse_pass

**Comment by lidanqing-vv** [comment]
PR merged
