### ISSUE TITLE
动态图转静态图保存后，载入模型时，无法改变输入数据的batchsize

### ISSUE THREAD

**Issue by doge-ac-cn** [PaddlePaddle/Paddle#27957]
PaddlePaddle版本：1.8
保存模型代码
`    out_dygraph, static_layer = TracedLayer.trace(DeepSortNet, inputs=[image])
    static_layer.save_inference_model('infer_model')`

使用模型的代码
`image = np.random.random([1,3,128, 64]).astype('float32')
program, feed_vars, fetch_vars = fluid.io.load_inference_model('infer_model', exe)
fetch, = exe.run(program, feed={feed_vars[0]: image}, fetch_list=fetch_vars)`

在生产环境部署时，batch_size必须和训练时的batch_size一致，否则会产生如下报错

`InvalidArgumentError: The 'shape' in ReshapeOp is invalid. The input tensor X'size must be equal to the capacity of 'shape'. But received X's shape = [128, 128, 1, 1], X's size = 16384, 'shape' is [1, 128], the capacity of 'shape' is 128.
  [Hint: Expected capacity == in_size, but received capacity:128 != in_size:16384.] at (D:\1.8.5\paddle\paddle\fluid\operators\reshape_op.cc:206)`

这也就意味着使用TracedLayer和load_inference_model接口，如果需要改变服务器端的batch_size，就必须重新训练模型。
请问有什么解决方法或者api可以实现可以在加载模型后，使用任意长度的batch_size吗

**Comment by yongqiangma** [comment]
从LOG没法定位问题，方便吧保存后的model文件给看下吗？

**Comment by doge-ac-cn** [comment]
是这样的，我batch_size 128的时候生成了模型。
使用模型的时候如果使用128以外的batch_size就会报错。
请问有没有相关接口可以生成支持变长batch_size的模型。

**Comment by doge-ac-cn** [comment]
不是产生了bug，只是对功能上有疑问。

**Comment by QingYuan-L** [comment]
我也遇到了类似的问题，就是手写了一个模型，定义的batchsize为64，之后导出模型，去作部署，使用的 paddle inference，发现必须也将输入数据的batchszie调整成64一次送入多张图片， 按理来说不是应该在推断的时候可以支持送入任意batch大小的图片吗？

**Comment by DogeZen** [comment]
train.py
`import paddle
import paddle.fluid as fluid
from PIL import Image
import os
import numpy as np
from paddle.fluid.dygraph import to_variable, TracedLayer

from deepsort_net import Mylayer

# 指定参数
train_dir = "dataset/people_reid/train"
test_dir = "dataset/people_reid/val"
BATCH_SIZE = 128
NUM_EPOCHES = 1
RANDOM_POOL_SIZE = 100000  # 随机池
num_classes = 751
# 指定gpu
place = fluid.CUDAPlace(0)
fluid.enable_imperative(place)


# 指定投入训练数据的reader生成器
def train_generater():
    def __reader__():
        imageclass = 0
        for class_name in os.listdir(train_dir):

            for image_name in os.listdir(train_dir + "/" + class_name):
                image_path = train_dir + "/" + class_name + "/" + image_name
                image = Image.open(image_path).resize((128, 64), Image.ANTIALIAS)
                image = np.array(image).astype(np.float32)
                image = np.reshape(image, [3, 128, 64])

                yield image / 255.0 * 2.0 - 1.0, imageclass
            imageclass += 1

    return __reader__


# 指定投入预测数据的reader生成器
def test_generater():
    def __reader__():
        imageclass = 0
        for class_name in os.listdir(test_dir):

            for image_name in os.listdir(test_dir + "/" + class_name):
                image_path = test_dir + "/" + class_name + "/" + image_name
                image = Image.open(image_path).resize((128, 64), Image.ANTIALIAS)
                image = np.array(image).astype(np.float32)
                image = np.reshape(image, [3, 128, 64])

                yield image / 255.0 * 2.0 - 1.0, imageclass
            imageclass += 1

    return __reader__


# 指定投入预测数据的reader生成器
def predict_generater():
    def __reader__():

        for class_name in os.listdir(test_dir):

            for image_name in os.listdir(test_dir + "/" + class_name):
                image_path = test_dir + "/" + class_name + "/" + image_name
                image = Image.open(image_path).resize((128, 64), Image.ANTIALIAS)
                image = np.array(image).astype(np.float32)
                image = np.reshape(image, [3, 128, 64])
                yield image / 255.0 * 2.0 - 1.0

    return __reader__


# 使用sample数据生成器作为DataLoader的数据源
train_loader = fluid.io.DataLoader.from_generator(capacity=10)
train_loader.set_sample_generator(paddle.reader.shuffle(train_generater(), RANDOM_POOL_SIZE), batch_size=BATCH_SIZE,
                                  places=place)

test_loader = fluid.io.DataLoader.from_generator(capacity=10)
test_loader.set_sample_generator(test_generater(), batch_size=BATCH_SIZE, places=place)

predict_loader = fluid.io.DataLoader.from_generator(capacity=10)
predict_loader.set_sample_generator(predict_generater(), batch_size=1, places=place)

# 初始化神经网络
DeepSortNet = Mylayer()
# 添加优化器
adam = fluid.optimizer.AdamOptimizer(learning_rate=0.001, parameter_list=DeepSortNet.parameters())

with fluid.dygraph.guard():
    # 执行训练/预测
    for epoch_idx in range(NUM_EPOCHES):

        # 训练
        DeepSortNet.train()
        # 添加准确度管理器
        accuracy_manager = fluid.metrics.Accuracy()
        print("epoch  %d  " % epoch_idx)
        for data in train_loader():
            # 投入数据
            image, label = data
            label = label.astype(np.int64)
            image = fluid.dygraph.to_variable(image)
            label = fluid.dygraph.to_variable(label)
            # 执行前向
            acc, loss = DeepSortNet(image, label)
            # 执行反向
            loss.backward()
            # 梯度更新
            adam.minimize(loss)
            # 清除梯度
            adam.clear_gradients()
            accuracy_manager.update(acc.numpy(), BATCH_SIZE)
        print("train accuracy: %.6f , loss %.2f" % (accuracy_manager.eval(), loss))
        # 评估
        DeepSortNet.eval()
        accuracy_manager = fluid.metrics.Accuracy()
        for data in test_loader():
            # 投入数据
            image, label = data
            label = label.astype(np.int64)
            image = fluid.dygraph.to_variable(image)
            label = fluid.dygraph.to_variable(label)
            # 执行前向
            acc, loss = DeepSortNet(image, label)

            accuracy_manager.update(acc.numpy(), BATCH_SIZE)
            # 每隔十次训练,输出一次准确率

        print("test accuracy: %.6f , loss %.2f" % (accuracy_manager.eval(), loss))

    image = np.random.random([1, 3, 128, 64]).astype('float32')
    image = fluid.dygraph.to_variable(image)
    out_dygraph, static_layer = TracedLayer.trace(DeepSortNet, inputs=[image])
    static_layer.save_inference_model('infer_model')
`

**Comment by doge-ac-cn** [comment]
问题解决了
我定义网络时有这步
`x = fluid.layers.reshape(x, [x.shape[0], x.shape[1]])`
导致生成静态图时reshape操作被固定为(128,128)
后面传batch_size不一致的就会报错
如果改成
`x = x[:, :, 0, 0]`
则不会产生这样的问题
