### ISSUE TITLE
CAPI预测结果和不为1

### ISSUE THREAD

**Issue by fingthinking** [PaddlePaddle/Paddle#2795]
![image](https://user-images.githubusercontent.com/5517388/28017922-bd139b60-65ad-11e7-9bfb-805641e77ae6.png)
![image](https://user-images.githubusercontent.com/5517388/28017961-ef50e6a0-65ad-11e7-9fbe-cee10594ab59.png)
按照下面这个配置，生成的train_config.bin，读入capi里面，预测出来的结果如：
![image](https://user-images.githubusercontent.com/5517388/28017983-074bcdb0-65ae-11e7-9168-d01c9ce642e6.png)
为什么Prob出来的两个值的加和不等于1？

**Comment by QiJune** [comment]
在预测的时候，只需要softmax输出的，不需要计算cost
请检查一下预测网络配置

**Comment by QiJune** [comment]
得到反馈，以解决问题，所以close issue
