### ISSUE TITLE
请问有没有lstm这个api的使用的具体案例，看官方文档还是不大会用，找到的大部分都是dynamic_lstm的

### ISSUE THREAD

**Issue by liu824** [PaddlePaddle/Paddle#27964]
请问有没有lstm这个api的使用的具体案例，看官方文档还是不大会用，找到的大部分都是dynamic_lstm的

**Comment by yongqiangma** [comment]
是在静态图下用还是在动态图下用呢？

**Comment by liu824** [comment]
动态图的

**Comment by SWHL** [comment]
同求

**Comment by wkzqn** [comment]
+1

**Comment by lfchener** [comment]
2.0 已经新增了 LSTM 相关的 API，可以参考：
https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/nn/layer/rnn/LSTM_cn.html#lstm
