### ISSUE TITLE
job-0bb5f87f68f24516 数据读取问题

### ISSUE THREAD

**Issue by MrIce0501** [PaddlePaddle/Paddle#27977]
job-0bb5f87f68f24516 这个任务训练数据读取出现问题，请问是哪里的问题？
![image](https://user-images.githubusercontent.com/40877122/96100175-a78a2100-0f06-11eb-9f9a-ac722e5b96b3.png)

**Comment by MrIce0501** [comment]
![image](https://user-images.githubusercontent.com/40877122/96094913-832b4600-0f00-11eb-8669-bb707381f18f.png)

**Comment by yongqiangma** [comment]
给你一个可复现的单测吧
