### ISSUE TITLE
dlopen core_avx.so出core

### ISSUE THREAD

**Issue by foreverhui** [PaddlePaddle/Paddle#27986]
c++调用python脚本，c++进程引入了tcmalloc，在import module的过程中，dlopen core_avx.so动态库，在初始化core_avx.so出core。并且出core的堆栈不是稳定产生。
![image](https://user-images.githubusercontent.com/15011807/96108237-eb355880-0f0f-11eb-95b8-1bffd667e781.png)

**Comment by yongqiangma** [comment]
给一个可复现的单测吧？
