### ISSUE TITLE
请教关于反向传播时梯度与优化器的关系

### ISSUE THREAD

**Issue by starsblinking** [PaddlePaddle/Paddle#27984]
在 https://www.paddlepaddle.org.cn/documentation/docs/zh/advanced_guide/addon_development/new_op/new_op.html 中给出了如何新增一个op；我想请教一下如何判断梯度是否被优化器影响？
具体点说，假设我要实现一个简单的透传layer，调用一个透传op，该op实现: 把输入X直接传给输出Y，把输出Y的梯度传给X并累加到属于该layer的持久化变量Z，即
(X, Z)----->Y， Y=X, dZ=dY, dX=dY
这样训练完成之后我就得到了训练过程中dY的累加值Z。(1)但我如何判断（或实现）dZ是否受到了优化器的影响？(2)比如Z累加的是dY还是dY*learning_rate（或者是adam中更复杂的结果)?(3)如果我使用adam优化器，并设置变量Z的learning_rate为1会怎么样样？(4)会在该变量上使用learning_rate=1(beta1,beta2保持不变)的adam优化器吗？
(5)另外，非持久化变量X的梯度在反向传播时应该完全不受优化器影响对吧？

说白了，我是对优化器在训练时的作用过程不了解，也好像没看到相关的文档。我刚学习paddle，辛苦大佬帮忙回答下上面的问题(1)~(5)哈。如果打字费劲，也可以如流语音。多谢指导！

**Comment by MRXLT** [comment]
优化器作用在参数更新的时候，不会影响本次反向计算中梯度的值，只会影响参数更新的值

**Comment by starsblinking** [comment]
> 优化器作用在参数更新的时候，不会影响本次反向计算中梯度的值，只会影响参数更新的值

多谢。您的回复相当于回答了上述问题(1)，即优化器不修改dZ，只是影响Z利用dZ进行更新的过程；同时，问题(5)不存在了。辛苦对问题(2)~(4)也解答下吧。

**Comment by MRXLT** [comment]
z累加的是优化器的计算结果，
lr设为1会导致每次更新的参数变化很大，模型可能会不收敛
第4个问题不太明白是什么意思
