### ISSUE TITLE
paddle源码编译（osx）报各种module找不到的问题

### ISSUE THREAD

**Issue by liujinseu** [PaddlePaddle/Paddle#280]
从源码编译，最后cmake ..时
Could NOT find PY_google.protobuf (missing:  PY_GOOGLE.PROTOBUF)
CMake Error at cmake/FindPythonModule.cmake:27 (message):
  python module google.protobuf is not found
若通过-D设置路径后，又会有其他的如Could not find PY_wheel等其他找不到的情况

**Comment by backyes** [comment]
可以提供更多的系统版本 ，编译命令等详细信息么？



-------- 原始邮件 --------
发件人：liujinseu <notifications@github.com>
时间：周四 10月27日 23:47
收件人：baidu/Paddle <Paddle@noreply.github.com>
主题：[baidu/Paddle] paddle源码编译（osx）报各种module找不到的问题 (#280)


从源码编译，最后cmake ..时
Could NOT find PY_google.protobuf (missing: PY_GOOGLE.PROTOBUF)
CMake Error at cmake/FindPythonModule.cmake:27 (message):
python module google.protobuf is not found
若通过-D设置路径后，又会有其他的如Could not find PY_wheel等其他找不到的情况

**Comment by gangliao** [comment]
@liujinseu  

You can simply type 'ccmake ..' and change the following items with correct path, for example, compiling Paddle from my Mac OS X.

```                                                                                                    
 PYTHON_NUMPY_INCLUDE_DIR         /Library/Python/2.7/site-packages/numpy/core/include                                                    
 PY_GOOGLE.PROTOBUF               /Library/Python/2.7/site-packages/google/protobuf                                                       
 PY_PIP                           /Library/Python/2.7/site-packages/pip                                                                   
 PY_WHEEL                         /usr/local/lib/python2.7/site-packages/wheel                                                            
 SWIG_BINARY_PATH                 /usr/local/bin/swig                         
```

**Comment by wangkuiyi** [comment]
@liujinseu 请贴一下编译的完整 log ，以便大家分析问题。也让这个 issue 对其他读者有参考意思。

**Comment by gangliao** [comment]
@liujinseu  Any update on your move??

**Comment by liujinseu** [comment]
osx 10.10版本，cmake .. -DWITH_GPU=OFF -DWITH_DOC=OFF
报错如下：

**Comment by liujinseu** [comment]
![paddle_cmake](https://cloud.githubusercontent.com/assets/9606308/19888873/64c18262-a06c-11e6-9886-b16567a0a507.png)

**Comment by gangliao** [comment]
@liujinseu 

你可以尝试：

```
pip install wheel
cmake .. -DWITH_GPU=OFF -DPY_WHEEL=/usr/local/lib/python2.7/site-packages/wheel
```
`/usr/local/lib/python2.7/site-packages/wheel` 你可以替换成你本地的wheel路径。

谢谢

**Comment by liujinseu** [comment]
设置后，执行make，报如下问题：

[ 67%] Built target paddle_gserver
Scanning dependencies of target test_CommandLineParser
usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
   or: setup.py --help [cmd1 cmd2 ...]
   or: setup.py --help-commands
   or: setup.py cmd --help

error: invalid command 'bdist_wheel'
[ 68%] Building CXX object paddle/utils/tests/CMakeFiles/test_CommandLineParser.dir/test_CommandLineParser.cpp.o
make[2]: *** [python/build/.timestamp] Error 1
make[1]: *** [python/CMakeFiles/paddle_python.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 68%] Linking CXX executable test_CommandLineParser
Done processing test_CommandLineParser.cpp

**Comment by gangliao** [comment]
http://stackoverflow.com/questions/26664102/why-can-i-not-create-a-wheel-in-python
看起来你需要：
```
pip install setuptools
pip install setuptools --upgrade
```

**Comment by liujinseu** [comment]
@gangliao 安装了，还是报刚才的问题

**Comment by gangliao** [comment]
@liujinseu  能否 `make VERBOSE=1` 粘贴一下详细的错误信息。 谢谢。

**Comment by gangliao** [comment]
@reyoung 
https://github.com/tensorflow/tensorflow/issues/348 是否和python多个版本有关。。。

**Comment by liujinseu** [comment]
@gangliao 的确是的，python 多个路径问题。

**Comment by reyoung** [comment]
@liujinseu I will add this problem to FAQ.

When cmake find python interpretor and python libs, it always find a different version of Python, if there are many pythons installed. In this situation, you should explicit select which python should be used. I will give some instructions this afternoon, and you could also search cmake documentation to get answer if you are in hurry.

Related Issue #297

**Comment by reyoung** [comment]
@gangliao And do not explicit set the python package by cmake. Just make sure the python libs and python interpretor are the same python could solve all these kind of problems.

Explicit set python package may be failed when there are some native extension of this python package, such as numpy.

**Comment by wangkuiyi** [comment]
Paddle now officially support Docker images. Dockerfiles are at https://github.com/PaddlePaddle/Paddle/tree/develop/paddle/scripts/docker and updated documents are at https://github.com/PaddlePaddle/Paddle/blob/develop/doc/getstarted/build_and_install/docker_install.rst.

Since Mac and Windows and Linux all supports Docker, above changes provides an official way to build and run Paddle without the need to build from source code.  Hence close this issue.
