### ISSUE TITLE
如何删除在program中已存在的名字？

### ISSUE THREAD

**Issue by ydchen9** [PaddlePaddle/Paddle#28007]
我的平台是：win7,` 64位，python2.7.18，paddle1.8.4。
建立了一个ParamAttr(name="fc_weight_I"）名字之后，如何删除它？因为我在做循环训练模型的过程，每次循环时，都要进行build program， 这时会出现名字冲突的错误，但又不能不build program，因为模型的结构虽然一样，但图片的尺寸大小不同。
![QQ截图20201016150602](https://user-images.githubusercontent.com/26667822/96223870-365b7400-0fc1-11eb-8149-4f373ae6e818.png)
![QQ截图20201016150621](https://user-images.githubusercontent.com/26667822/96223872-378ca100-0fc1-11eb-8047-9635ab062ea8.png)

**Comment by zhupengyang** [comment]
代码格式可以调整下吗？

不能删除。如果是两个模型的话，可以使用不同的 ```with fluid.program_guard(...)``` 包起来

**Comment by ydchen9** [comment]
不好意思，我是GitHub技术太菜了。我试过，但编辑的时候好好的，一提交就没了代码格式，我现在先用图片显示。用了insert code命令也没用。


您说的用with fluid.program_guard(...)我用了，我在每个循环里面是有两个不同的program的，它们分别在两个不同的with fluid.program_guard(...)里。但是，每次循环时都需要重新构建这两个program，因为输入图片的尺寸发生变化，尽管两个网络的结构是不变的。

我用了close()命令也没用。paddle机制是否是生成一个program之后，就无法再清除该program中的变量，直到程序停止？而且，我每次进入循环时都是重新开启一个fluid.Executor(place)，待循环结束将它close()。按理说在此之中建立的program应该都被释放，可是并没有，当进行下次循环时，就出现名字冲突的错误。

**Comment by zhupengyang** [comment]
这是program混乱了

**Comment by zhupengyang** [comment]
我看你是只有一个模型，那么请全局都用相同的program，中间任何时候都不需要改变或者定义新的program，整个模型的相关信息都会存储在这个program中。

**Comment by ydchen9** [comment]
是的，我确实在中间定义了新的program了（采用循环同一个子函数来生成program）。可是我要实现的功能里有个循环，每次循环是要改变输入数据的size，这样的话，如果不重新定义program能实现吗？我想了想，似乎行不通，因为一旦build program之后，输入数据就和后面的网络固定住了，下次循环再进入这个program也没法改这个program的拓补结构了。是不是这样？除非新建一个program，我现在就是这样做的。

**Comment by zhupengyang** [comment]
需要改变大小的维度用 -1 表示，会在执行过程中根据你实际的输入数据进行正确匹配的

**Comment by ydchen9** [comment]
非常感谢！这解决了我输入数据维度变化的问题。但是还有一个问题，我的filter size是和输入数据尺寸一样大的，有没有处理这种情况的filter size的设置呢？

**Comment by ydchen9** [comment]
目前直接采用修改变量名的方法（name="fc1_weight_O"+str(jobs_num)），避免了名字冲突错误，可以跑通。但不知是否导致内存崩溃。

**Comment by zhupengyang** [comment]
> 我的filter size是和输入数据尺寸一样大的，有没有处理这种情况的filter size的设置呢？

只要是匹配的就可以

**Comment by ydchen9** [comment]
> 只要是匹配的就可以

由于filter size是和输入数据的尺寸一样，-1也能实现filter size的尺寸根据输入数据调整吗？

**Comment by zhupengyang** [comment]
> -1也能实现filter size的尺寸根据输入数据调整吗？

不能。从逻辑上说，filter size应该是固定的，否则是无法训练的，建议你确认下自己的网络到底应该是什么结构的

**Comment by ydchen9** [comment]
好的，明白。我的网络中filter size和输入数据尺寸一样，都是固定的。我在做调参实验，要做多组不同的输入数据尺寸，想写个循环程序实现，所以就有了要改变输入数据尺寸和filter size尺寸的问题。
