### ISSUE TITLE
RNN Op Plan

### ISSUE THREAD

**Issue by luotao1** [PaddlePaddle/Paddle#2801]
# TODOs
- [x] 依赖 parent scope 中的 Variable 统一用 inputs 传入，方便 key 查重
- [x] RNN 嵌套，需要支持在外界定义好 step net，传入给 RNN
- [x] RNNOp 的 InferShape

# RecurrentOp 依赖
1. tensor中希望加上copy和share函数，目前是用memcpy函数直接写的。
2. `Tensor.mutable_data()` 支持 

# RecurrentOp的计划
1. Tensor格式目前设计为<seq_len, batch_size, dim>，即定长的序列输入。之后会考虑设计一个seq_tensor，采用和sequenceStartPositions类似的存储方式，来定义变长的序列输入。
1. 支持external_memory，参考 [@lcy-seso 的配置](https://github.com/lcy-seso/paddle_confs_v1/blob/master/mt_with_external_memory/gru_attention_with_external_memory.conf)。
1. 支持嵌套RNN。
1. 支持跨时间步连接的RNN。

**Comment by luotao1** [comment]
@QiJune @Canpio 求在tensor中加上copy函数

**Comment by qingqing01** [comment]
1.  An embedding operator (or table lookup operator) for the RNN network.
2. Python API for RNN operator.

**Comment by lcy-seso** [comment]
从任务list中看到此issue已完成，因此close掉，如果有需要请大家建立新的issue讨论，谢谢啦。
