### ISSUE TITLE
静态图如何循环每个batch 中的数据，maml 实现

### ISSUE THREAD

**Issue by zle1992** [PaddlePaddle/Paddle#28015]
maml中，一个batch包含 多个task, 每个task 更新完梯度，下一个task 用新的梯度继续更新，这个过程是串行的。难点是 paddle  是静态图，无法循环batch 中每个task。 TF直接给模型传的tensor。 paddle 使用静态图分布式训练，有什么好的办法实现maml么？
￼https://zhuanlan.zhihu.com/p/66926599
![image](https://user-images.githubusercontent.com/16644339/96223142-06f83780-0fc0-11eb-942f-c2462cdf3b6e.png)

tf 代码：https://github.com/cbfinn/maml/blob/master/maml.py#L99

torch 代码：

https://github.com/dragen1860/MAML-Pytorch/blob/master/meta.py#L81
￼
![image](https://user-images.githubusercontent.com/16644339/96223259-35761280-0fc0-11eb-9c67-ec1cdbd1bbc7.png)

**Comment by zhupengyang** [comment]
用 [while_loop](https://www.paddlepaddle.org.cn/documentation/docs/zh/api_cn/layers_cn/while_loop_cn.html#while-loop) 循环操作试试

**Comment by zle1992** [comment]
> 用 [while_loop](https://www.paddlepaddle.org.cn/documentation/docs/zh/api_cn/layers_cn/while_loop_cn.html#while-loop) 循环操作试试

可以具体帮忙实现下么

比如如下数据emb_1，如何取每个batch
import paddle.fluid as fluid
data = fluid.layers.data(name='sequence', shape=[1], dtype='int64', lod_level=1)
emb_1 = fluid.embedding(input=data, size=[128, 64])

**Comment by zhupengyang** [comment]
希望你可以自己尝试下哦
