### ISSUE TITLE
使用paddle trt int8性能与fp32性能无差异

### ISSUE THREAD

**Issue by shikeno** [PaddlePaddle/Paddle#28016]
为使您的问题得到快速解决，在建立Issue前，请您先通过如下方式搜索是否有相似问题:【搜索issue关键字】【使用labels筛选】【官方文档】

如果您没有查询到相似问题，为快速解决您的提问，建立issue时请提供如下细节信息：
- 标题：简洁、精准描述您的问题，例如“最新预测库的API文档在哪儿 ”
- 版本、环境信息：
    1）PaddlePaddle版本：请提供您的PaddlePaddle版本号（如1.1）或CommitID
    2）CPU：预测若用CPU，请提供CPU型号，MKL/OpenBlas/MKLDNN/等数学库使用情况
    3）GPU：T4， 
                  CUDA Driver API Version: 10.1, 
                  CUDA Runtime API Version: 10.1
                  cuDNN Version: 7.6
                  TensorRT6.0.1.5
    4）系统环境：请您描述系统类型、版本（如Mac OS 10.14），Python版本
注：您可以通过执行[summary_env.py](https://github.com/PaddlePaddle/Paddle/blob/develop/tools/summary_env.py)获取以上信息。
- 复现信息：如为报错，请给出复现环境、复现步骤
- 问题描述：
按照官网wiki （https://www.paddlepaddle.org.cn/documentation/docs/zh/advanced_guide/performance_improving/inference_improving/paddle_tensorrt_infer.html#Paddle-TRT_INT8%E4%BD%BF%E7%94%A8 ）
里的方法，尝试用Alexnet 分别跑了fp32的性能与int8的性能，发现性能基本相同，而使用mobilenetv1 的时候会有显著的优化效果。想请帮忙看一下是什么原因

![image](https://user-images.githubusercontent.com/44427541/96222573-19be3c80-0fbf-11eb-80a5-94cad20cb2db.png)

![image](https://user-images.githubusercontent.com/44427541/96223741-fdbb9a80-0fc0-11eb-8b80-31000f0ccda0.png)

**Comment by cryoco** [comment]
您好，麻烦提供下alexnet的inference model和您的测试代码，我们复现定位下原因，谢谢

**Comment by shikeno** [comment]
使用的文件是官网wiki里的fluid_generate_calib_test.cc， fluid_int8_test.cc，只修改了模型文件。模型链接wget http://gzhxy-dstream-pn00018.gzhxy.baidu.com:8911/paddle_alexnet.tar.gz

**Comment by shikeno** [comment]
> 使用的文件是官网wiki里的fluid_generate_calib_test.cc， fluid_int8_test.cc，只修改了模型文件。模型链接wget http://gzhxy-dstream-pn00018.gzhxy.baidu.com:8911/paddle_alexnet.tar.gz

https://paddle-inference-dist.bj.bcebos.com/tensorrt_test/paddle_inference_sample_v1.7.tar.gz

**Comment by cryoco** [comment]
您好，我们定位了下原因，应该在于目前paddle-trt尚未支持卷积层的padding为4维。
![image](https://user-images.githubusercontent.com/12407750/96227730-19c23a80-0fc7-11eb-83b4-66262e83e377.png)
对于非2维padding的conv层，目前会使用paddle原生gpu kernel而非TRT运行。如果模型的计算密度集中在conv层的话，对其他部分使用TRT int8加速相比fp32带来的收益就不明显了。
我们会在下个版本中增加对4维padding的conv的TRT支持。目前您可以手动将模型中conv的padding改为2维，方法如下：
1. 在模型构建代码中将所有conv2d的padding参数改为2维，例如原本是1,1,1,1的改为1,1；
2. 重新加载训练好的参数checkpoint（无需重新训练）；
3. 重新调用save_inference_model接口保存推理模型。

**Comment by shikeno** [comment]
> 您好，我们定位了下原因，应该在于目前paddle-trt尚未支持卷积层的padding为4维。
> ![image](https://user-images.githubusercontent.com/12407750/96227730-19c23a80-0fc7-11eb-83b4-66262e83e377.png)
> 对于非2维padding的conv层，目前会使用paddle原生gpu kernel而非TRT运行。如果模型的计算密度集中在conv层的话，对其他部分使用TRT int8加速相比fp32带来的收益就不明显了。
> 我们会在下个版本中增加对4维padding的conv的TRT支持。目前您可以手动将模型中conv的padding改为2维，方法如下：
> 
> 1. 在模型构建代码中将所有conv2d的padding参数改为2维，例如原本是1,1,1,1的改为1,1；
> 2. 重新加载训练好的参数checkpoint（无需重新训练）；
> 3. 重新调用save_inference_model接口保存推理模型。

那就是和精度没关系，fp32和int8都是gpu kernel所以性能差不多，如果调整之后，那fp32也会有性能上的提升吧

**Comment by cryoco** [comment]
> > 您好，我们定位了下原因，应该在于目前paddle-trt尚未支持卷积层的padding为4维。
> > ![image](https://user-images.githubusercontent.com/12407750/96227730-19c23a80-0fc7-11eb-83b4-66262e83e377.png)
> > 对于非2维padding的conv层，目前会使用paddle原生gpu kernel而非TRT运行。如果模型的计算密度集中在conv层的话，对其他部分使用TRT int8加速相比fp32带来的收益就不明显了。
> > 我们会在下个版本中增加对4维padding的conv的TRT支持。目前您可以手动将模型中conv的padding改为2维，方法如下：
> > 
> > 1. 在模型构建代码中将所有conv2d的padding参数改为2维，例如原本是1,1,1,1的改为1,1；
> > 2. 重新加载训练好的参数checkpoint（无需重新训练）；
> > 3. 重新调用save_inference_model接口保存推理模型。
> 
> 那就是和精度没关系，fp32和int8都是gpu kernel所以性能差不多，如果调整之后，那fp32也会有性能上的提升吧

是的，调整之后conv会有原生fp32 kernel->TRT fp32的加速，在此基础上开启int8还会有fp32 -> int8的加速

**Comment by shikeno** [comment]
> > > 您好，我们定位了下原因，应该在于目前paddle-trt尚未支持卷积层的padding为4维。
> > > ![image](https://user-images.githubusercontent.com/12407750/96227730-19c23a80-0fc7-11eb-83b4-66262e83e377.png)
> > > 对于非2维padding的conv层，目前会使用paddle原生gpu kernel而非TRT运行。如果模型的计算密度集中在conv层的话，对其他部分使用TRT int8加速相比fp32带来的收益就不明显了。
> > > 我们会在下个版本中增加对4维padding的conv的TRT支持。目前您可以手动将模型中conv的padding改为2维，方法如下：
> > > 
> > > 1. 在模型构建代码中将所有conv2d的padding参数改为2维，例如原本是1,1,1,1的改为1,1；
> > > 2. 重新加载训练好的参数checkpoint（无需重新训练）；
> > > 3. 重新调用save_inference_model接口保存推理模型。
> > 
> > 
> > 那就是和精度没关系，fp32和int8都是gpu kernel所以性能差不多，如果调整之后，那fp32也会有性能上的提升吧
> 
> 是的，调整之后conv会有原生fp32 kernel->TRT fp32的加速，在此基础上开启int8还会有fp32 -> int8的加速

好的，感谢
