### ISSUE TITLE
加载模型报错

### ISSUE THREAD

**Issue by hanzhy-code** [PaddlePaddle/Paddle#28039]
在模型训练的时候,使用fluid.io.save_persistables(或者fluid.io.save_params)保存模型,然后使用fluid.io.load_persistables(或者fluid.io.load_params)加载模型,结果报错了.错误如下:
----------------------
Error Message Summary:
----------------------
UnavailableError: Load operator fail to open file /home/aistudio/work/model_weights/paddle_unet_base_1_100/conv2d_0.w_0, please check whether the model file is complete or damaged.
  [Hint: Expected static_cast<bool>(fin) == true, but received static_cast<bool>(fin):0 != true:1.] at (/paddle/paddle/fluid/operators/load_op.h:41)
  [operator < load > error]

我看了路径没有问题.遇到相同问题的帮忙解决一下,谢谢

**Comment by willthefrog** [comment]
确认下 `/home/aistudio/work/model_weights/paddle_unet_base_1_100/conv2d_0.w_0`是否存在？如果存在建议重新保存下试试，确实可能出现文件损坏的情况。

**Comment by hanzhy-code** [comment]
你好:
十分感谢您的回复.是这样的,之前我用的是paddle1.8.4版本,后面我换成1.8.0版本之后上述问题就不存在了.至于具体原因我也不清楚了.



在 2020-10-17 20:02:45，"Yang Zhang" <notifications@github.com> 写道：

确认下 /home/aistudio/work/model_weights/paddle_unet_base_1_100/conv2d_0.w_0是否存在？如果存在建议重新保存下试试，确实可能出现文件损坏的情况。
