### ISSUE TITLE
30系显卡支持

### ISSUE THREAD

**Issue by shiontao** [PaddlePaddle/Paddle#28036]
手上有3090的机器，不知道能不能用paddle

**Comment by willthefrog** [comment]
rtx 30系需要nvidia 450.36以上的驱动，450.36最低需要cuda 11.0才能兼容，目前paddle官方没有发布 cuda 11的版本，原则上也不保证cuda 11的兼容性，但是可以尝试自行从源码编译。

**Comment by mingren8888** [comment]
> rtx 30系需要nvidia 450.36以上的驱动，450.36最低需要cuda 11.0才能兼容，目前paddle官方没有发布 cuda 11的版本，原则上也不保证cuda 11的兼容性，但是可以尝试自行从源码编译。

这个450.36最低需要cuda11.0才能兼容，是从哪看到的呢？ 虽然cuda10不能发挥450.36的全部功能，但是450.36可以发挥cuda10的全部功能吧，向下兼容吧

**Comment by cole-dda** [comment]
3年过后，30系列仍然不支持（或者说非常慢）。官方只会关闭issue，根本不去测试问题。让大家怎么支持paddle，怎么用？如果需要测试，使用自家的paddleocr+paddle2.3.2+30系列显卡测试即可。
