### ISSUE TITLE
在多线程预测中，使用GPU时执行copy_from_cpu时崩溃！！只使用CPU没有问题，若程序比较小也没问题。

### ISSUE THREAD

**Issue by mingren8888** [PaddlePaddle/Paddle#28044]
GPU gtx1070 cuda 10.0 cudnn7.6
主线程用来初始化，并且在主线程中，预测了一张图片来进行warmup，可以正常执行。 在新创建检测线程中，执行预测步骤时，会崩溃到copy_from_cpu。模型是图像分割模型。崩溃如下：
![image](https://user-images.githubusercontent.com/26703287/96347894-7e6cba80-10d7-11eb-915e-48c3f6ccd7b3.png)
不使用GPU预测时没问题。

**Comment by mingren8888** [comment]
0x00007FFBBF169156 (Infer.dll) (Face.exe 中)处有未经处理的异常: 0xC0000005: 读取位置 0x0000000000000000 时发生访问冲突。

**Comment by mingren8888** [comment]
问题已解决，崩溃的版本的检测线程是在界面初始化函数中创建并启动，当将检测线程改为在点击开始检测按钮再启动，就不会发生访问冲突了，具体原因还不清楚。

**Comment by JaneBai** [comment]
我也遇到同样的问题。在主线程初始化并检测没有问题。在其中某个线程里，GPU推理就会崩溃，但CPU没有问题
