### ISSUE TITLE
<论文复现> 请问如何加载预训练参数

### ISSUE THREAD

**Issue by zhongqing0507** [PaddlePaddle/Paddle#28046]
我用save_dygraph 和load_dygraph api 保存和加载参数， 只能用于相同网络结构吗？
当我改变最后几层的网络结构时，加载模型出错。改变了部分结构后只能重新训练模型，请问需要怎么保存和加载参数？才能只训练我改变的那一部分网络结构，未改变的加载我之前训练的参数。谢谢。

**Comment by LielinJiang** [comment]
load_dygraph后，你会得到之前保存的参数，格式是一个dict，{参数名：参数值（numpy格式）}。你修改网络后，部分参数名和参数的形状会发生变化，你可以通过new_model.state_dict()得到修改后的网络的参数字典，与之前load进来的参数字典做一个判断，如果名字在新的参数字典中，且形状一致就加载。举个例子：
path_a = save_dygraph(old_net)
old_params, _ = load_dygraph(path_a)

new_net = build_net()
new_params = new_net.state_dict()

convert_params = {}
for k, v in old_params.items():
    if k in new_params and (list(old_params[k].shape) == list(new_params[k].shape)):
         convert_params[k] = v

new_net.set_dict(convert_params)

**Comment by zhongqing0507** [comment]
感谢！

发送自 Windows 10 版邮件应用

发件人: LielinJiang
发送时间: 2020年10月19日 10:12
收件人: PaddlePaddle/Paddle
抄送: zhongqing0507; Author
主题: Re: [PaddlePaddle/Paddle] <论文复现> 请问如何加载预训练参数 (#28046)

load_dygraph后，你会得到之前保存的参数，格式是一个dict，{参数名：参数值（numpy格式）}。你修改网络后，部分参数名和参数的形状会发生变化，你可以通过new_model.state_dict()得到修改后的网络的参数字典，与之前load进来的参数字典做一个判断，如果名字在新的参数字典中，且形状一致就加载。举个例子：
path_a = save_dygraph(old_net)
old_params, _ = load_dygraph(path_a)
new_net = build_net()
new_params = new_net.state_dict()
convert_params = {}
for k, v in old_params.items():
if k in new_params and (list(old_params[k].shape) == list(new_params[k].shape)):
convert_params[k] = v
new_net.set_dict(convert_params)
