### ISSUE TITLE
AGX Xavier 预测报错

### ISSUE THREAD

**Issue by mingquanyuan** [PaddlePaddle/Paddle#28047]
**硬件平台**: Jetson AGX Xavier (32G)

**系统信息**

PaddlePaddle GIT COMMIT ID: 832458d516ad52454ce3227a2983f8b347708b1b(develop)
WITH_MKL: OFF
WITH_MKLDNN: OFF
WITH_GPU: ON
CUDA version: 10.0
CUDNN version: v7.6
CXX compiler version: 7.5.0
WITH_TENSORRT: ON
TensorRT version: v6

OS Platform: Ubuntu 18.04.4 LTS
Python version: 3.6.9
CMake version: 3.10.2
JetPack version: 4.3

**安装方式**: 本地编译

**cmake命令**
```
cmake .. \
          -DWITH_CONTRIB=OFF \
          -DWITH_MKL=OFF  \
          -DWITH_MKLDNN=OFF \
          -DWITH_TESTING=OFF \
          -DCMAKE_BUILD_TYPE=Release \
          -DON_INFER=ON \
          -DWITH_PYTHON=ON \
          -DWITH_XBYAK=OFF  \
          -DWITH_NV_JETSON=ON \
          -DPY_VERSION=3 \
          -DCUDA_ARCH_NAME=Auto

make TARGET=ARMV8 -j8
make inference_lib_dist
```

**预测使用模型**：[PaddleOCR](https://github.com/PaddlePaddle/PaddleOCR/blob/develop/doc/doc_ch/quickstart.md) 

**预测使用代码**：[链接](https://github.com/PaddlePaddle/PaddleOCR/blob/develop/doc/doc_ch/quickstart.md#3%E5%8D%95%E5%BC%A0%E5%9B%BE%E5%83%8F%E6%88%96%E8%80%85%E5%9B%BE%E5%83%8F%E9%9B%86%E5%90%88%E9%A2%84%E6%B5%8B)

**报错信息**
```
python3 tools/infer/predict_det.py --image_dir=./doc/imgs  --det_model_dir=./models/ch_det_mv3_db --cls_model_dir=./models/ch_ppocr_mobile_v1.1_cls_infer  --use_angle_cls=True --use_space_char=True --use_gpu=True
W1016 17:47:30.430263 28914 analysis_predictor.cc:1042] Deprecated. Please use CreatePredictor instead.


--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
0   paddle::framework::SignalHandle(char const*, int)
1   paddle::platform::GetCurrentTraceBackString[abi:cxx11]()

----------------------
Error Message Summary:
----------------------
FatalError: A serious error (Segmentation fault) is detected by the operating system. (at /home/mingquan-agx/Downloads/Paddle/paddle/fluid/platform/init.cc:303)
  [TimeInfo: *** Aborted at 1602888450 (unix time) try "date -d @1602888450" if you are using GNU date ***]
  [SignalInfo: *** SIGSEGV (@0x7fab035090) received by PID 28914 (TID 0x7fab070010) from PID 18446744072283705488 ***]

Segmentation fault (core dumped)
```

**Comment by LDOUBLEV** [comment]
1. 可以检查下paddle是否安装成功
```
import paddle.fluid
paddle.fluid.install_check.run_check()
```
如果输出`Your Paddle Fluid is installed successfully!`类似信息，表示安装成功
2. 你的cudnn版本是？如果高于cudnn 7 ，试试降低cudnn版本，cuda10 cudnn7是可以的

**Comment by mingquanyuan** [comment]
> 1. 可以检查下paddle是否安装成功
> 
> ```
> import paddle.fluid
> paddle.fluid.install_check.run_check()
> ```
> 
> 如果输出`Your Paddle Fluid is installed successfully!`类似信息，表示安装成功
> 2. 你的cudnn版本是？如果高于cudnn 7 ，试试降低cudnn版本，cuda10 cudnn7是可以的

1. paddle应该是安装成功
```
>>> import paddle
>>> 
>>> 
>>> paddle.fluid.install_check.run_check()
Running Verify Fluid Program ... 
W1018 21:33:03.196411 32136 device_context.cc:338] Please NOTE: device: 0, CUDA Capability: 72, Driver API Version: 10.0, Runtime API Version: 10.0
W1018 21:33:03.197809 32136 device_context.cc:346] device: 0, cuDNN Version: 7.6.
Your Paddle Fluid works well on SINGLE GPU or CPU.
I1018 21:33:19.265276 32136 parallel_executor.cc:365] Cross op memory reuse strategy is enabled, when build_strategy.memory_optimize = True or garbage collection strategy is disabled, which is not recommended
Your Paddle Fluid works well on MUTIPLE GPU or CPU.
Your Paddle Fluid is installed successfully! Let's start deep Learning with Paddle Fluid now
```

2. cudnn版本以及其它系统信息(paddle_inference_install_dir/version.txt)
```
GIT COMMIT ID: 832458d516ad52454ce3227a2983f8b347708b1b
WITH_MKL: OFF
WITH_MKLDNN: OFF
WITH_GPU: ON
CUDA version: 10.0
CUDNN version: v7.6
CXX compiler version: 7.5.0
WITH_TENSORRT: ON
TensorRT version: v6
```

**Comment by LDOUBLEV** [comment]
--image_dir=./doc/imgs/11.jpg   指定到单张图像可以预测吗

**Comment by mingquanyuan** [comment]
> --image_dir=./doc/imgs/11.jpg 指定到单张图像可以预测吗

单张图片也是报同样的错误，但是如果用cpu推理（`--use_gpu=False`）就可以成功，只是推理速度很慢。

**Comment by mingquanyuan** [comment]
debug的时候，是在tools/infer/utility.py 中134行 `predictor = create_paddle_predictor(config)`出的问题。这一行之前可以打印，这行之后就打印不出来东西了。

**Comment by cryoco** [comment]
https://github.com/PaddlePaddle/PaddleOCR/blob/develop/tools/infer/utility.py#L126
您好，麻烦把这一行注释掉，然后发一下运行和报错的完整log吧

**Comment by mingquanyuan** [comment]
> https://github.com/PaddlePaddle/PaddleOCR/blob/develop/tools/infer/utility.py#L126
> 您好，麻烦把这一行注释掉，然后发一下运行和报错的完整log吧

注掉这一行之后，用GPU的时候貌似还是同样的报错:

```
python3 tools/infer/predict_det.py --image_dir=./doc/imgs/11.jpg  --det_model_dir=./models/ch_ppocr_server_v1.1_det_infer   --use_gpu=True
W1019 10:07:57.569133  6191 analysis_predictor.cc:1042] Deprecated. Please use CreatePredictor instead.


--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
0   paddle::framework::SignalHandle(char const*, int)
1   paddle::platform::GetCurrentTraceBackString[abi:cxx11]()

----------------------
Error Message Summary:
----------------------
FatalError: A serious error (Segmentation fault) is detected by the operating system. (at /home/mingquan-agx/Downloads/Paddle/paddle/fluid/platform/init.cc:303)
  [TimeInfo: *** Aborted at 1603120077 (unix time) try "date -d @1603120077" if you are using GNU date ***]
  [SignalInfo: *** SIGSEGV (@0x7f9d154090) received by PID 6191 (TID 0x7f9d1a6010) from PID 18446744072050000016 ***]

Segmentation fault (core dumped)
```

下面是不用GPU情况下的log，看起来一切正常:

```
python3 tools/infer/predict_det.py --image_dir=./doc/imgs/11.jpg  --det_model_dir=./models/ch_ppocr_server_v1.1_det_infer   --use_gpu=False
W1019 10:08:09.090574  6215 analysis_predictor.cc:1042] Deprecated. Please use CreatePredictor instead.
I1019 10:08:09.091015  6215 analysis_predictor.cc:139] Profiler is deactivated, and no profiling report will be generated.
--- Running analysis [ir_graph_build_pass]
--- Running analysis [ir_graph_clean_pass]
--- Running analysis [ir_analysis_pass]
--- Running IR pass [simplify_with_basic_ops_pass]
--- Running IR pass [attention_lstm_fuse_pass]
--- Running IR pass [seqconv_eltadd_relu_fuse_pass]
--- Running IR pass [seqpool_cvm_concat_fuse_pass]
--- Running IR pass [mul_lstm_fuse_pass]
--- Running IR pass [fc_gru_fuse_pass]
--- Running IR pass [mul_gru_fuse_pass]
--- Running IR pass [seq_concat_fc_fuse_pass]
--- Running IR pass [fc_fuse_pass]
--- Running IR pass [repeated_fc_relu_fuse_pass]
--- Running IR pass [squared_mat_sub_fuse_pass]
--- Running IR pass [conv_bn_fuse_pass]
I1019 10:08:09.556282  6215 graph_pattern_detector.cc:100] ---  detected 24 subgraphs
--- Running IR pass [conv_eltwiseadd_bn_fuse_pass]
--- Running IR pass [conv_transpose_bn_fuse_pass]
--- Running IR pass [conv_transpose_eltwiseadd_bn_fuse_pass]
I1019 10:08:09.593791  6215 graph_pattern_detector.cc:100] ---  detected 1 subgraphs
--- Running IR pass [is_test_pass]
--- Running IR pass [runtime_context_cache_pass]
--- Running analysis [ir_params_sync_among_devices_pass]
--- Running analysis [adjust_cudnn_workspace_size_pass]
--- Running analysis [inference_op_replace_pass]
--- Running analysis [ir_graph_to_program_pass]
I1019 10:08:09.677604  6215 analysis_predictor.cc:537] ======= optimize end =======
start call
Predict time of ./doc/imgs/11.jpg: 6.496880292892456
```

**Comment by mingquanyuan** [comment]
> https://github.com/PaddlePaddle/PaddleOCR/blob/develop/tools/infer/utility.py#L126
> 
> 您好，麻烦把这一行注释掉，然后发一下运行和报错的完整log吧

您好，这个问题有新的进展吗？谢谢🙏

**Comment by cryoco** [comment]
看起来是在初始化的时候挂掉了。请问别的模型在GPU下可以正常运行么

**Comment by mingquanyuan** [comment]
> 看起来是在初始化的时候挂掉了。请问别的模型在GPU下可以正常运行么

OCR的文字识别模型没有问题

**Comment by cryoco** [comment]
我们正在获取可用的xavier设备用于复现，可以先gdb看一下core的堆栈信息么

**Comment by mingquanyuan** [comment]
> 我们正在获取可用的xavier设备用于复现，可以先gdb看一下core的堆栈信息么

这个具体怎么操作，不太会。。。

**Comment by PUZZER** [comment]
> 我们正在获取可用的xavier设备用于复现，可以先gdb看一下core的堆栈信息么

设备：jetson xavier NX
jetpack：4.4
WITH_MKL: OFF
WITH_MKLDNN: OFF
WITH_GPU: ON
CUDA version: 10.2
CUDNN version: v8.0
Tensorrt：7.1.3.0
Namespace(cls=False, cls_batch_num=30, cls_image_shape='3, 48, 192', cls_model_dir='/home/puzzer/.paddleocr/cls', cls_thresh=0.9, det=True, det_algorithm='DB', det_db_box_thresh=0.5, det_db_thresh=0.3, det_db_unclip_ratio=2.0, det_east_cover_thresh=0.1, det_east_nms_thresh=0.2, det_east_score_thresh=0.8, det_max_side_len=960, det_model_dir='/home/puzzer/.paddleocr/det', enable_mkldnn=False, gpu_mem=8000, image_dir=None, ir_optim=True, label_list=['0', '180'], lang='ch', max_text_length=25, rec=True, rec_algorithm='CRNN', rec_batch_num=30, rec_char_dict_path='./ppocr/utils/ppocr_keys_v1.txt', rec_char_type='ch', rec_image_shape='3, 32, 320', rec_model_dir='/home/puzzer/.paddleocr/rec/ch', use_angle_cls=False, use_gpu=True, use_pdserving=False, use_space_char=True, use_tensorrt=True, use_zero_copy_run=False)
W1202 17:32:22.805721 29193 analysis_predictor.cc:1042] Deprecated. Please use CreatePredictor instead.
一样的问题，虽然并不影响paddleocr预测执行，但是tensorrt加速貌似没有起作用

**Comment by jiafuzeng** [comment]
![image](https://user-images.githubusercontent.com/39875080/135907583-54997704-8775-4a13-a039-de1924108df1.png)
