### ISSUE TITLE
大佬们能提供一些关于PaddleEDL 弹性资源训练的文档么？

### ISSUE THREAD

**Issue by zhaozheng09** [PaddlePaddle/Paddle#28058]
我尝试在代码和git的文档上找了下，但没有发现什么有用的信息，除了代码中的一小段注释，如下:
`
python/paddle/distributed/fleet/base/distributed_strategy.py

1046:    def elastic(self):

1048:        Indicating whether we want to do current distributed training on clusters with elastic resources.

1051:        return self.strategy.elastic

1053:    @elastic.setter

1055:    def elastic(self, flag):

1057:            self.strategy.elastic = flag

1059:            print("WARNING: elastic should have value of bool type")
`
想问下：除了这一小段注释之外，还有什么文档可以学习下，Paddle是如何动态弹性扩大和缩小作业资源规模的么？

**Comment by zhiqiu** [comment]
hi，你可以看下这里的文档：https://github.com/elasticdeeplearning/edl

**Comment by zhaozheng09** [comment]
> hi，你可以看下这里的文档：https://github.com/elasticdeeplearning/edl

想问下，我们支持ps架构下异步梯度更新的弹性这种模式么？我在文档中并没有看到。
