### ISSUE TITLE
如何在动态图中加载 PaddleClas 的 vgg-16 预训练模型

### ISSUE THREAD

**Issue by TWLemontree** [PaddlePaddle/Paddle#28055]
PaddleClas 提供的 vgg-16 预训练模型中的文件，保存的是每一层网络的参数（conv1_1_weights, conv1_2_weights ...），而动态图保存模型保存的是 .pdparams 和 .pdopt 文件。我如何在动态图中加载 PaddleClas 提供的 vgg-16 预训练模型呢？

**Comment by TWLemontree** [comment]
如果有一个具体的、简单的 demo 就更好了，请不要提供复杂的工程样例，作为一个新手，看起来会非常吃力otz

**Comment by littletomatodonkey** [comment]
以动态图代码加载静态图预训练模型为例，可以指定参数`load_static_weights=True`，脚本如下所示，

https://github.com/PaddlePaddle/PaddleClas/blob/8e42f786da57bb1fcb243af4defb5b989334f4ba/tools/eval.sh#L5

**Comment by TWLemontree** [comment]
虽然没太看懂在哪里加载的参数，但是我的问题已经解决了，还是谢谢您！

https://aistudio.baidu.com/aistudio/projectdetail/1124272

我是通过上述项目给出的方法解决的问题otz



在 2020-10-19 14:56:54，"littletomatodonkey" <notifications@github.com> 写道：

以动态图代码加载静态图预训练模型为例，可以指定参数load_static_weights=True，脚本如下所示，

https://github.com/PaddlePaddle/PaddleClas/blob/8e42f786da57bb1fcb243af4defb5b989334f4ba/tools/eval.sh#L5
