### ISSUE TITLE
do_model_average

### ISSUE THREAD

**Issue by starsblinking** [PaddlePaddle/Paddle#28072]
https://www.paddlepaddle.org.cn/documentation/docs/zh/api_cn/fluid_cn/ParamAttr_cn.html#paramattr 里写默认值为False，看代码好像默认值是True？

1. 感觉默认值为False比较合理吧？
2. 貌似没懂这个参数什么意思，希望能说明下。我理解的模型平均应该有其他参数（比如衰减率啥的）来配合使用吧，这里怎么就一个flag呢？

1.8.5

**Comment by zhiqiu** [comment]
中文文档应该是写错了，默认值确实是True。不过，目前这个参数应该是只有在ModelAverage中会用到，所以设置为True不会影响其他情况的使用。参考：https://www.paddlepaddle.org.cn/documentation/docs/zh/2.0-beta/api/paddle/optimizer/ModelAverage_cn.html。
