### ISSUE TITLE
加预训练的embedding层参数出错误

### ISSUE THREAD

**Issue by WoNiuHu** [PaddlePaddle/Paddle#2807]
外接embedding层的时候，用的v1版本的paddle, 先把本地的embedding词典转成二进制之后，传入，再加embedding里面的词和id做了一个word_dict 传入，跑的时候出现以下错误。
请帮忙看下哈.
```text
F0711 15:20:57.064468 15230 Parameter.cpp:383] Check failed: s.read(reinterpret_cast<char*>(vec.getData()), header.size * sizeof(real)) 
*** Check failure stack trace: ***
    @          0x13b4438  google::LogMessage::Fail()
    @          0x13b4390  google::LogMessage::SendToLog()
    @          0x13b3e25  google::LogMessage::Flush()
    @          0x13b6be6  google::LogMessageFatal::~LogMessageFatal()
    @           0x82e17f  paddle::Parameter::load()
    @           0x82e86d  paddle::Parameter::load()
    @           0x6d90ba  paddle::GradientMachine::loadParameters()
    @           0x712efc  paddle::ParameterUtil::loadParametersWithPath()
    @           0x70202f  paddle::Trainer::init()
    @           0x591ee9  main
    @     0x7f4433a81bd5  __libc_start_main
    @           0x59dbf5  (unknown)
/home/huhaibing01/tools/paddlell/bin/paddle_local: line 109: 15230 Aborted                 ${DEBUGGER} $MYDIR/../opt/paddle/bin/paddle_trainer ${@:2}
```

**Comment by QiJune** [comment]
“外接embedding层的时候，用的v1版本的paddle, 先把本地的embedding词典转成二进制之后，传入，再加embedding里面的词和id做了一个word_dict 传入，跑的时候出现以下错误。”
没太理解这个过程，能麻烦稍微详细一点吗？

**Comment by WoNiuHu** [comment]
因为需要外加一个embedding层，所以做了如下处理。
1. emb = embedding_layer(input=data, size=emb_dim, param_attr=ParamAttr(name='_source_language_embedding'))  这个_source_language_embedding文件是本地的embedding文件除去第一列词之后的向量做了二进制转换之后的文件。
2. dataprovider中的word_dict换成了原始embedding文件的词和对应每一行的id的映射。settings.word_dict
3. def stacked_lstm_net(input_dim,
                     class_dim=2,
                     emb_dim=50,
                     hid_dim=512,
                     stacked_num=3,
                     is_predict=False):
网络中的emb_dim改成了embedding文件中向量的维度，50维。
然后跑的时候出现了上面的报错。

**Comment by QiJune** [comment]
这个向量做二进制转换是paddle通过保存参数来实现的吗？

**Comment by WoNiuHu** [comment]
对，用的你们这边的脚本https://github.com/WoNiuHu/Paddle/blob/develop/v1_api_demo/model_zoo/embedding/paraconvert.py

**Comment by luotao1** [comment]
> dataprovider中的word_dict换成了原始embedding文件的词和对应每一行的id的映射

word_dict不能用原始的映射吧。embedding文件都换了，字典也应该更新呀。

**Comment by WoNiuHu** [comment]
这里说的原始就是本地的embedding文件的词-id(对应行)的映射

**Comment by lcy-seso** [comment]
* 请参考这个 issue https://github.com/PaddlePaddle/Paddle/issues/2812
* 这个问题的出现是因为参数转过过程没有正确的转化为可以被PaddlePaddle加载的参数
* 建议按照 https://github.com/PaddlePaddle/Paddle/issues/2812 这个 issue 里面对 Paddle 参数的解释，自己再做一遍转化。

**Comment by luotao1** [comment]
@lcy-seso 是说 [paraconvert.py](https://github.com/PaddlePaddle/Paddle/blob/develop/v1_api_demo/model_zoo/embedding/paraconvert.py)的转换流程写的有问题？

**Comment by lcy-seso** [comment]
我没有说 paraconver.py 写得有问题，只是说转换结果有问题。上面这个错误是转化引起的，这个脚本使用是否正确没有排除。

**Comment by WoNiuHu** [comment]
@lcy-seso  你那个地方的矩阵是随机生成的，然后转成二进制，我这里是要load一个已有的矩阵，这个不一样吧？

**Comment by lcy-seso** [comment]
@WoNiuHu 那是一个实例程序，你把随机矩阵换成你需要的即可。

**Comment by WoNiuHu** [comment]
@lcy-seso hi，按照你的脚本重新跑了一下二进制的转化。现在出现这种的，然后就直接跳出了。
I0712 14:19:19.295415  5174 PyDataProvider2.cpp:257] loading dataprovider dataprovider::process
[INFO 2017-07-12 14:19:23,378 dataprovider.py:26] dict len : 5590593
I0712 14:19:23.396491  5174 GradientMachine.cpp:123] Loading parameters from ./opinion_data/pre-car
I0712 14:19:24.078368  5174 Parameter.cpp:344] missing parameters [./opinion_data/pre-car/___fc_layer_0__.w0] while loading model.
I0712 14:19:24.078407  5174 Parameter.cpp:354] ___fc_layer_0__.w0 missing, set to random.
I0712 14:19:24.093816  5174 Parameter.cpp:344] missing parameters [./opinion_data/pre-car/___fc_layer_0__.wbias] while loading model.
I0712 14:19:24.093829  5174 Parameter.cpp:354] ___fc_layer_0__.wbias missing, set to random.
I0712 14:19:24.093876  5174 Parameter.cpp:344] missing parameters [./opinion_data/pre-car/___lstmemory_0__.w0] while loading model.
I0712 14:19:24.093881  5174 Parameter.cpp:354] ___lstmemory_0__.w0 missing, set to random.
I0712 14:19:24.098644  5174 Parameter.cpp:344] missing parameters [./opinion_data/pre-car/___lstmemory_0__.wbias] while loading model.
I0712 14:19:24.098651  5174 Parameter.cpp:354] ___lstmemory_0__.wbias missing, set to random.
I0712 14:19:24.098726  5174 Parameter.cpp:344] missing parameters [./opinion_data/pre-car/___fc_layer_1__.w0] while loading model.
I0712 14:19:24.098731  5174 Parameter.cpp:354] ___fc_layer_1__.w0 missing, set to random.
I0712 14:19:24.117671  5174 Parameter.cpp:344] missing parameters [./opinion_data/pre-car/___fc_layer_1__.w1] while loading model.
I0712 14:19:24.117678  5174 Parameter.cpp:354] ___fc_layer_1__.w1 missing, set to random.

脚本如下：
def get_para_count(input):
    """
    Compute the total number of embedding parameters in input text file.
    input: the name of input text file
    """
    numRows = 1
    paraDim = 0
    with open(input) as f:
        line = f.readline()
        line = line.strip()
        paraDim = len(line.split(" "))
        for line in f:
            numRows += 1
    print(paraDim)
    return numRows * (paraDim-1)

def text2binary(input, output, paddle_head=True):
    """
    Convert a text parameter file of embedding model to be a binary file.
    input: the name of input text parameter file, for example:
           -0.7845433,1.1937413,-0.1704215,...
           0.0000909,0.0009465,-0.0008813,...
           ...
           the format is:
           1) it doesn't have filehead
           2) each line stores the same dimension of parameters,
              the separator is commas ','
    output: the name of output binary parameter file, the format is:
           1) the first 16 bytes is filehead:
             version(4 bytes), floatSize(4 bytes), paraCount(8 bytes)
           2) the next (paraCount * 4) bytes is parameters, each has 4 bytes
    """
    #fi = open(input, "r")
    #fo = open(output, "wb")

    newHead = struct.pack("iil", 0, 4, get_para_count(input))
    np.random.seed()
    #header = struct.pack("iil", 0, 4, height * width)
    param = np.float32(np.random.rand(5590593, 50))
    fi = open(input, 'r')
    count_i = 0
    for line in fi:
        line = line.split(" ")
        count_j = 0
        for x in range(1, len(line)):
                param[count_i][count_j] = float(line[x])
                count_j += 1
        count_i += 1
    with open(output, "wb") as fparam:
        fparam.write(newHead + param.tostring())

**Comment by WoNiuHu** [comment]
@lcy-seso  另外我的词向量本身是二进制的，所以它到ID的映射也是二进制-对应行数的映射。这个有没有影响？

**Comment by lcy-seso** [comment]
1. 从运行log看，在加载参数的过程并没有报错。`___fc_layer_1__.w1 missing, set to random` 这样的信息是正常的，意思是这个参数没有提供初始化，将采用随机初始化。
2. "词向量本身是二进制的，所以它到ID的映射" 这一句没有理解。
    - 1. 本身是二进制的，请先还原会明文，然后再转成paddle 可以接受的格式
    - 2.  “所以它到ID的映射” 这一句指的是网络中什么运算？

**Comment by WoNiuHu** [comment]
@lcy-seso  1. 但是运行到这里就直接退出了，没有进行train。2.因为在dataprovider.py中，需要一个词向量到对应id(行)的映射，`word_slot = [
                settings.word_dict[w] for w in words if w in settings.word_dict
            ]` 这里的word_dict我就是把词向量到行做了一个map。

**Comment by lcy-seso** [comment]
1.  退出的原因在别处，已经和加载参数没有关系了。从贴出的日志里面看不出来。
2.  id 是一个词在词典中的序号，只要这个序号符合你的预期即可。

**Comment by WoNiuHu** [comment]
@lcy-seso  我看train.log也是到这里就结束了。这个是train的配置。
`paddle train --config=${config} \
                 --save_dir=${output} \
                 --init_model_path='./opinion_data/pre-car' \
                 --load_missing_parameter_strategy=rand \
                 --job=train \
                 --use_gpu=false \
                 --trainer_count=5 \
                 --num_passes=2 \
                 --log_period=10 \
                 --dot_period=20 \
                 --show_parameter_stats_period=100 \
                 --test_all_data_in_one_period=1 \
                 2>&1 | tee 'train.log'
    paddle usage -l train.log -e $? -n "sentiment_train" >/dev/null 2>&1`
train.log里面讲完参数缺失，set to random ，然后就 
`+ paddle usage -l train.log -e 0 -n sentiment_train
+ rc=0
+ exit 0`
退出了，所以接下来从哪里去调？

**Comment by lcy-seso** [comment]
1. 请在脚本里面加上，然后贴实际运行时候这些参数的实际值，而不是一段代码。
    ```bash
    set -x
    ```
2. 以上都不是退出的原因，可以以我的经验来建议，退出是因为没有数据，读数据过程有问题。

**Comment by WoNiuHu** [comment]
@lcy-seso  1. 这个加过的。
                   2. `config=${base_dir}/trainer_config.py
    output=./model_output`  config是上述文件，output模型输出，  
   `--init_model_path='./opinion_data/pre-car'`  pre-car里面，有这些文件`dict.txt  labels.list  _source_language_embedding  test.list  test_part_000  train.list  train_part_000` 分别是 词向量-id的映射，embedding的二进制文件，test_part_000的路径，测试集，train_part_000的路径，训练集。
加载数据的地方 `define_py_data_sources2(
        train_list,
        test_list,
        module="dataprovider",
        obj="process",
        args={'dictionary': dict_file})`

**Comment by luotao1** [comment]
> [INFO 2017-07-12 14:19:23,378 dataprovider.py:26] dict len : 5590593

字典有500w行多？字典是最新的么？

**Comment by WoNiuHu** [comment]
@luotao1 嗯，字典500多万行，最新的

**Comment by WoNiuHu** [comment]
@lcy-seso @luotao1 这个问题还是没有解决。。。感觉你们之前应该也会碰到这种问题？

**Comment by lcy-seso** [comment]
在我的经验里只遇到过一种情况，训练任务什么也没有做，没有出错而退出： data provider 没有提供任何数据，训练任务任务没有数据要处理，但其它环节并无异常，因此会退出。

我的建议依然是请优先检测读数据过程。

**Comment by WoNiuHu** [comment]
@lcy-seso  我查看了一下，数据确实是有的，加载数据的方式如下：
define_py_data_sources2(
        train_list,
        test_list,
        module="dataprovider",
        obj="process",
        args={'dictionary': dict_file})
然后在dataprovider.py中，产生一个word_dict 的map, 代码如下：
def hook(settings, dictionary, **kwargs):
    settings.word_dict = {}
    with open(dictionary, 'r') as f:
        for i, line in enumerate(open(dictionary, 'r')):
            settings.word_dict[line.split('\t')[0]] = i
    settings.input_types = [
        integer_value_sequence(len(settings.word_dict)), integer_value(2)
    ]
    settings.logger.info('dict len : %d' % (len(settings.word_dict)))

**Comment by lcy-seso** [comment]
不是说有没有加载数据的代码，是真的有给训练程序返回数据了吗？这个是静态代码，根本看不出来信息。

**Comment by pkuyym** [comment]
@lcy-seso 已引导用户进行排查，定位到问题确实是dataprovider没有产生有效数据，导致网络没有训练
@WoNiuHu 这个issue如果已经fix，麻烦close掉吧
