### ISSUE TITLE
网络train/eval模式异常

### ISSUE THREAD

**Issue by chenwthu** [PaddlePaddle/Paddle#28089]
Paddle版本2.0.0b0，一个网络train/eval模式的改变会影响其他网络
demo代码输出False, False，期望为True, False
```
  0 import paddle
  1 import paddle.nn as nn
  2 
  3 class Net1(nn.Layer):
  4     def __init__(self):
  5         super(Net1, self).__init__()
  6         self.linear = nn.Linear(2, 3)
  7 
  8     def forward(self, x):
  9         return self.linear(x)
 10 
 11 class Net2(nn.Layer):
 12     def __init__(self):
 13         super(Net2, self).__init__()
 14         self.linear = nn.Linear(2, 3)
 15 
 16     def forward(self, x):
 17         return self.linear(x)
 18 
 19 paddle.disable_static()
 20 net1 = Net1()
 21 net1.eval()
 22 net2 = Net2()
 23 net2.train()
 24 to_float = lambda x: paddle.to_tensor(x, dtype='float32')
 25 print(net1(to_float([[1,2]])).stop_gradient)
 26 print(net2(to_float([[1,2]])).stop_gradient)
```

**Comment by zhiqiu** [comment]
hi，目前框架的实现中，net.eval()不会改变网络中tensor的stop_gradient属性，只会改变运行时是否记录反向的行为。

**Comment by chenwthu** [comment]
但上述代码如果先设置net1.train()再设置net2.eval()，结果是两个网络输出的stop_gradient都变为True，导致net1无法正常训练参数
我希望实现同时存在两个网络，其中一个能正常训练，另一个只负责推理，而不需要在训练或推理前再分别切换train/eval

**Comment by zhiqiu** [comment]
> 但上述代码如果先设置net1.train()再设置net2.eval()，结果是两个网络输出的stop_gradient都变为True，导致net1无法正常训练参数
> 我希望实现同时存在两个网络，其中一个能正常训练，另一个只负责推理，而不需要在训练或推理前再分别切换train/eval

确实是这样，原因是在切换eval mode的时候除了修改net的模式，还会同时修改一个全局的tracer的模式。所以，net1和net2中后一个修改会生效到全局tracer模式中。代码：
https://github.com/PaddlePaddle/Paddle/blob/a5f65d516fd3b05ec3ad80549e2fb3d839cd9905/python/paddle/fluid/dygraph/layers.py#L134-L140

这个我们会讨论下怎么优化下比较好。
