### ISSUE TITLE
Error in installing paddlepaddle

### ISSUE THREAD

**Issue by quanfan7** [PaddlePaddle/Paddle#28099]
We tried to install by using 
"conda install paddlepaddle"
but have been receiving the error message 

"PackagesNotFoundError: The following packages are not available from current channels:

  - paddlepaddle"

So how to fix the error? Thanks a lot.

**Comment by GaoWei8** [comment]
Please follow this tutorial to try to install paddlepadlle：https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/install/index_cn.html#pip

**Comment by zhupengyang** [comment]
试试conda换清华源
