### ISSUE TITLE
py2环境安装paddle1.8.4失败

### ISSUE THREAD

**Issue by ellinyang** [PaddlePaddle/Paddle#28106]
- 版本、环境信息：
    1）PaddlePaddle版本：paddlepaddle-gpu==1.8.4.post97
    3）GPU：请提供GPU型号，CUDA9和CUDNN7
    4）系统环境：Ubuntu 16.04.6 LTS、Python2.7.12

报错：pip安装失败
pip install paddlepaddle-gpu==1.8.4.post97
报错信息如下：
    
![image](https://user-images.githubusercontent.com/20673237/96537987-17632780-12ca-11eb-8263-dda238dc8207.png)

**Comment by GaoWei8** [comment]
应该是镜像没连接上，设下代理或者换镜像源。参考官网：https://www.paddlepaddle.org.cn/install/quick
