### ISSUE TITLE
如何自定义优化器？How can I define custom optimizers?

### ISSUE THREAD

**Issue by chenwthu** [PaddlePaddle/Paddle#28136]
paddle 2.0.0b0 动态图模式如何自定义优化器（主要实现修改梯度的操作）
如果继承Optimizer类有参考文档或代码吗？或者有其他推荐的写法？

**Comment by GaoWei8** [comment]
参考这个文档：https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/optimizer/Optimizer_cn.html#optimizer
