### ISSUE TITLE
add_sublayer的作用

### ISSUE THREAD

**Issue by xiaomujiang** [PaddlePaddle/Paddle#28135]
add_sublayer在很多网络都有，没找到详细的解释， 文档中说：添加子层实例。可以通过self.name访问该sublayer。
 如果不给实例加名字的话，是不是可以不加 add_sublayer？ 还是add_sublayer添加子层实例，这个怎么理解？    
for i in range(groups):
            conv2d = self.add_sublayer(
                'bb_%d' % i,
                fluid.dygraph.Conv2D(
                    init_num_channels, num_filters=num_filters, filter_size=3,
                    stride=1, padding=1, act='relu'
                )
            )
            self._conv2d_list.append(conv2d)
            init_num_channels = num_filters

**Comment by GaoWei8** [comment]
```
class MySequential(paddle.nn.Layer):
    def __init__(self, *layers):
        super(MySequential, self).__init__()
        if len(layers) > 0 and isinstance(layers[0], tuple):
            for name, layer in layers:
                self.add_sublayer(name, layer)
        else:
            for idx, layer in enumerate(layers):
                self.add_sublayer(str(idx), layer)

    def forward(self, input):
        for layer in self._sub_layers.values():
            input = layer(input)
        return input

fc1 = paddle.nn.Linear(10, 3)
fc2 = paddle.nn.Linear(3, 10, bias_attr=False)
model = MySequential(fc1, fc2)
print(model._sub_layers['1'])
for prefix, layer in model.named_sublayers():
    print(prefix, layer)
```
通过 add_sublayer的参数name进行访问。
