### ISSUE TITLE
训练train_from_dataset 成功训练1个epoch后，第二个epoch出错

### ISSUE THREAD

**Issue by YangYangL** [PaddlePaddle/Paddle#28145]
1）PaddlePaddle版本：1.8.3，GPU v100，cuda 10.0

- 训练信息
    1）单机 单卡训练

![da2d3fe0e6f786d7ae36109b43b76544](https://user-images.githubusercontent.com/5180089/96597351-502deb80-1320-11eb-9d59-59326f0e5663.png)

**Comment by GaoWei8** [comment]
报错看起来是第二个epoch，fetch的参数变成ndarray。
类似于跑第一个epoch的时候，之前a=b(b是variable)。比如第一个epoch结束的时候，做了一些操作，a=c(c是numpy)

**Comment by YangYangL** [comment]
已解决，谢谢
