### ISSUE TITLE
使用paddle源码编译c++库时出错

### ISSUE THREAD

**Issue by huyutao3550346** [PaddlePaddle/Paddle#28149]
报错内容：
/home/xxx/paddle/paddle/fluid/framework/unused_var_check.cc: In function ‘void paddle::framework::CheckUnusedVar(const paddle::framework::OperatorBase&, const paddle::framework::Scope&)’:
/home/xxx/paddle/paddle/fluid/framework/unused_var_check.cc:82:57: error: converting to ‘std::unordered_set<std::basic_string >’ from initializer list would use explicit constructor ‘std::unordered_set<_Value, _Hash, _Pred, _Alloc>::unordered_set(std::unordered_set<_Value, _Hash, _Pred, _Alloc>::size_type, const hasher&, const key_equal&, const allocator_type&) [with _Value = std::basic_string; _Hash = std::hash<std::basic_string >; _Pred = std::equal_to<std::basic_string >; _Alloc = std::allocator<std::basic_string >; std::unordered_set<_Value, _Hash, _Pred, _Alloc>::size_type = long unsigned int; std::unordered_set<_Value, _Hash, _Pred, _Alloc>::hasher = std::hash<std::basic_string >; std::unordered_set<_Value, _Hash, _Pred, _Alloc>::key_equal = std::equal_to<std::basic_string >; std::unordered_set<_Value, _Hash, _Pred, _Alloc>::allocator_type = std::allocator<std::basic_string >]’
std::unordered_setstd::string no_need_buffer_ins = {};
^
make[2]: *** [paddle/fluid/framework/CMakeFiles/unused_var_check.dir/unused_var_check.cc.o] Error 1
make[1]: *** [paddle/fluid/framework/CMakeFiles/unused_var_check.dir/all] Error 2
make: *** [all] Error 2

编译选项：cmake -DFLUID_INFERENCE_INSTALL_DIR=/home/xxx/paddle/libs -DCMAKE_BUILD_TYPE=Release -DWITH_PYTHON=OFF -DON_INFER=ON -DWITH_GPU=ONWITH_MKL=OFF -DWITH_MKLDNN=OFF -DWITH_XBYAK=ON -DWITH_NV_JETSON=OFF .. && make && make inference_lib_dist

环境：
GIT COMMIT ID: 1e01335e195d993f3c5c97bed3a15a6f9170acea
WITH_MKL: ON
WITH_MKLDNN: OFF
WITH_GPU: ONWITH_MKL=OFF
CUDA version: 9.2
CUDNN version: v7.6
CXX compiler version: 4.9.2

在https://github.com/PaddlePaddle/Paddle/issues/26722
看到了相同的问题。但是我的系统版本是centos7.6.1810，
无法安装ubuntu14.04版本的预测库。
只能使用源码编译的方式。

**Comment by edimetia3d** [comment]
您好,我们正在复现问题. 

在问题复现前. 根据错误信息, 建议您可以先尝试应用下面的修改,看看能否正常编译


Step1. 定位到 paddle/fluid/framework/unused_var_check.cc:82

Step2. 将
```cpp
std::unordered_set<std::string> no_need_buffer_ins = {};
```
改为
```cpp
std::unordered_set<std::string> no_need_buffer_ins;
```

**Comment by edimetia3d** [comment]
您好. 

我们初步判定该问题只能在 g++ 4.9.2 下复现, 按照之前的建议进行修改可以解决问题.

请您尝试一下, 看看问题是否仍然存在.期待您的反馈

**Comment by huyutao3550346** [comment]
@edimetia3d 你好，很高兴能为我解答，在修改后重新编译，原错误消失了，但仍然出现其他的错误。
修改步骤为：
![image](https://user-images.githubusercontent.com/29395068/96680526-4354da80-13a8-11eb-9fbe-9f08e173cffe.png)

错误代码为：
 Building CXX object paddle/fluid/operators/controlflow/CMakeFiles/while_op_helper.dir/while_op_helper.cc.o
/home/huyutao/paddle/paddle/fluid/imperative/layer.cc: In member function ‘void paddle::imperative::OpBase::SetType(const string&)’:
/home/huyutao/paddle/paddle/fluid/imperative/layer.cc:271:64: error: converting to ‘paddle::framework::AttributeMap {aka std::unordered_map<std::basic_string<char>, boost::variant<boost::blank, int, float, std::basic_string<char>, std::vector<int>, std::vector<float>, std::vector<std::basic_string<char> >, bool, std::vector<bool>, paddle::framework::BlockDesc*, long int, std::vector<paddle::framework::BlockDesc*>, std::vector<long int> > >}’ from initializer list would use explicit constructor ‘std::unordered_map<_Key, _Tp, _Hash, _Pred, _Alloc>::unordered_map(std::unordered_map<_Key, _Tp, _Hash, _Pred, _Alloc>::size_type, const hasher&, const key_equal&, const allocator_type&) [with _Key = std::basic_string<char>; _Tp = boost::variant<boost::blank, int, float, std::basic_string<char>, std::vector<int>, std::vector<float>, std::vector<std::basic_string<char> >, bool, std::vector<bool>, paddle::framework::BlockDesc*, long int, std::vector<paddle::framework::BlockDesc*>, std::vector<long int> >; _Hash = std::hash<std::basic_string<char> >; _Pred = std::equal_to<std::basic_string<char> >; _Alloc = std::allocator<std::pair<const std::basic_string<char>, boost::variant<boost::blank, int, float, std::basic_string<char>, std::vector<int>, std::vector<float>, std::vector<std::basic_string<char> >, bool, std::vector<bool>, paddle::framework::BlockDesc*, long int, std::vector<paddle::framework::BlockDesc*>, std::vector<long int> > > >; std::unordered_map<_Key, _Tp, _Hash, _Pred, _Alloc>::size_type = long unsigned int; std::unordered_map<_Key, _Tp, _Hash, _Pred, _Alloc>::hasher = std::hash<std::basic_string<char> >; std::unordered_map<_Key, _Tp, _Hash, _Pred, _Alloc>::key_equal = std::equal_to<std::basic_string<char> >; std::unordered_map<_Key, _Tp, _Hash, _Pred, _Alloc>::allocator_type = std::allocator<std::pair<const std::basic_string<char>, boost::variant<boost::blank, int, float, std::basic_string<char>, std::vector<int>, std::vector<float>, std::vector<std::basic_string<char> >, bool, std::vector<bool>, paddle::framework::BlockDesc*, long int, std::vector<paddle::framework::BlockDesc*>, std::vector<long int> > > >]’
op_ = framework::OpRegistry::CreateOp(type, {}, {}, {}, false);

**Comment by Shixiaowei02** [comment]
您好，参照 [C++ 规范](https://zh.cppreference.com/w/cpp/container/unordered_set/unordered_set)，不同 C++ 标准 `std::unordered_set<T>` 在构造函数细节上有所不同，这导致您使用列表拷贝初始化时的报错随编译器（C++ 标准库）版本变化而变化。

我理解代码的原作者使用显式初始化的初衷是避免临时变量使用随机值，下面的写法在任何支持 C++11 的编译器上都可通过编译：
```
std::unordered_set<std::string> no_need_buffer_ins{};
// 等价于 std::unordered_set<std::string> no_need_buffer_ins;
```

我们内部一般使用的 GCC 版本是 4.8.2 / 8.2.0，这两种编译器会在 Paddle 每次发版本前进行测试，确保兼容。如果您想了解上述报错原因的进一步细节，请参考相关问题 https://stackoverflow.com/questions/26947704

感谢您对 Paddle 的支持！

**Comment by huyutao3550346** [comment]
非常感谢您的回答，我这边使用GCC4.8.2后，就能完成编译了。

**Comment by Shixiaowei02** [comment]
> 非常感谢您的回答，我这边使用GCC4.8.2后，就能完成编译了。

不客气~~
