### ISSUE TITLE
可以支持rtx30系列GPU吗？

### ISSUE THREAD

**Issue by qsrc** [PaddlePaddle/Paddle#28141]
迁移之前的代码，初始化在create_paddle_predictor卡住，应该是GPU版本配适问题。

- 版本、环境信息：
    1）PaddlePaddle版本：2.0.0b0
    2）CPU：10900k
    3）GPU：rtx3090, CUDA: 10.0.130, CUDNN: 7.6.5
    4）系统环境：python3.7.9

**Comment by leeyy2020** [comment]
30系列显卡主流框架运行现在都费劲，paddle现在够呛能支持

**Comment by GaoWei8** [comment]
会反馈下支持特殊硬件的需求。

**Comment by zhwesky2010** [comment]
@qsrc 您好，请问下系统版本是Windows还是Linux呢
