### ISSUE TITLE
有几个问题提出如下

### ISSUE THREAD

**Issue by BlackHorseQ** [PaddlePaddle/Paddle#28156]
我就举几个例子：
1.没有1维卷积和池化，应该是有Sequence_pool这两个api，无法选择，步长，我现在是用2维卷积实现一维卷积。
2.lstm的api，三个lstm无一好用。
3.gru的api竟然需要传入隐藏矩阵，hidden_matrix意义不明
4.还有就是动态图和静态图泾渭不分明。
5.命名规范不一致

**Comment by GT-ZhangAcer** [comment]
<img width="387" alt="图片" src="https://user-images.githubusercontent.com/46156734/96678265-f7a03200-13a3-11eb-969a-cf343f72f7d7.png">
《素质》

**Comment by jzhang533** [comment]
感谢反馈。
在即将发布的2.0RC版本中，paddle team已经解决了大量这类问题。
目前，你可以先体验已经发布的2.0beta版本：
https://www.paddlepaddle.org.cn/documentation/docs/zh/2.0-beta/guides/index_cn.html
