### ISSUE TITLE
2.0-beta版本的lstm中本地英文说明中的例子缺少变量，maxlen

### ISSUE THREAD

**Issue by BlackHorseQ** [PaddlePaddle/Paddle#28170]
Examples:
    .. code-block:: python
        
        import paddle.fluid as fluid
        import paddle.fluid.layers as layers

        emb_dim = 256
        vocab_size = 10000
        data = fluid.data(name='x', shape=[None, 100], dtype='int64')
        emb = fluid.embedding(input=data, size=[vocab_size, emb_dim], is_sparse=True)
        batch_size = 20
        dropout_prob = 0.2
        input_size = 100
        hidden_size = 150
        num_layers = 1
        init_h = layers.fill_constant( [num_layers, batch_size, hidden_size], 'float32', 0.0 )
        init_c = layers.fill_constant( [num_layers, batch_size, hidden_size], 'float32', 0.0 )
        rnn_out, last_h, last_c = layers.lstm( emb, init_h, init_c,                     max_len, hidden_size, num_layers,                     dropout_prob=dropout_prob)
        rnn_out.shape  # (-1, 100, 150)
        last_h.shape  # (1, 20, 150)
        last_c.shape  # (1, 20, 150)
File:      /opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/layers/rnn.py
Type:      function

**Comment by BlackHorseQ** [comment]
追加一个，在2.0中那个例子通过不了

**Comment by BlackHorseQ** [comment]
也就是说函数更新了，但是api的说明还是1.8

**Comment by BlackHorseQ** [comment]
应该将
init_h = layers.fill_constant( [num_layers, batch_size, hidden_size], 'float32', 0.0 )
init_c = layers.fill_constant( [num_layers, batch_size, hidden_size], 'float32', 0.0 )
改成
init_h = layers.fill_constant( [num_layers, max_len, emb_dim], 'float32', 0.0 )
init_c = layers.fill_constant( [num_layers, max_len, emb_dim], 'float32', 0.0 )
可以通过但是意义不明

**Comment by jzhang533** [comment]
hi, 2.0beta下，RNN系列的API可以使用
```
paddle.nn.LSTM
paddle.nn.GRU
```
这里也有一个使用LSTM完成机器翻译任务的示例，供参考：
https://www.paddlepaddle.org.cn/documentation/docs/zh/2.0-beta/tutorial/nlp_case/seq2seq_with_attention/seq2seq_with_attention.html
