### ISSUE TITLE
百度aistudio上使用paddle2.0beta中lstm，报错Cudnn error, CUDNN_STATUS_EXECUTION_FAILED

### ISSUE THREAD

**Issue by BlackHorseQ** [PaddlePaddle/Paddle#28173]
为使您的问题得到快速解决，在建立Issue前，请您先通过如下方式搜索是否有相似问题:【搜索issue关键字】【使用labels筛选】【官方文档】

如果您没有查询到相似问题，为快速解决您的提问，建立issue时请提供如下细节信息：
- 标题：简洁、精准描述您的问题，例如“最新预测库的API文档在哪儿 ”
- 版本、环境信息：
    1）PaddlePaddle版：2.0beta
    2）CPU：百度aistudio 32g内存，32g显卡
    3）GPU：预测若用GPU，请提供GPU型号、CUDA和CUDNN版本号
- 复现信息：如为报错，请给出复现环境、复现步骤
- 问题描述：请详细描述您的问题，同步贴出报错信息、日志/代码关键片段
class base_model(fluid.dygraph.Layer):
    def __init__(self, classes_num: int):
        super().__init__()
        self.max_len = 5
        self.hidden_size = 128
        self.dropout_prob = 0.2
        self.num_layers = 2
        self.batch_size = 32
        self.init_h = layers.fill_constant([self.num_layers, self.max_len, 20], 'float32', 0.0 )
        self.init_c = layers.fill_constant([self.num_layers, self.max_len, 20], 'float32', 0.0 )
    def forward(self, input):
        #input:（batch_size, max_len, dim)
        
        x = input
        print(x.shape)
        rnn_out, last_h, last_c = layers.lstm(input=x, init_h = self.init_h, init_c = self.init_c, 
                                                max_len = self.max_len, hidden_size = self.hidden_size, 
                                                num_layers = self.num_layers, dropout_prob=self.dropout_prob, is_bidirec=True)
        rnn_out = layers.reshape(rnn_out, shape=[rnn_out.shape[0], 1, rnn_out.shape[1], rnn_out.shape[2]])
        mean_pool_out = layers.pool2d(rnn_out,pool_type='avg', pool_size=(rnn_out.shape[2], 1), pool_stride=(rnn_out.shape[2], 1))
        max_pool_out = layers.pool2d(rnn_out,pool_type='max', pool_size=(rnn_out.shape[2], 1), pool_stride=(rnn_out.shape[2], 1))
        r_shape = (mean_pool_out.shape[0], mean_pool_out.shape[-1])
        mean_pool_out = layers.reshape(mean_pool_out, shape=r_shape)
        max_pool_out = layers.reshape(max_pool_out, shape=r_shape)
        add_output = mean_pool_out + max_pool_out
        concat_output = layers.concat((mean_pool_out, max_pool_out), axis=1)

        output = layers.fc(concat_output, size=4)
        return output
if __name__ == '__main__':
    # 创建模型
    # with fluid.dygraph.guard():
    program = fluid.default_main_program()
    program.random_seed = 2020
    model = base_model(4)
    print('start training ... {} kind'.format(4))
    model.train()
    epoch_num = 30
    # 定义优化器
    opt = fluid.optimizer.Adam(learning_rate=0.01, parameter_list=model.parameters())
    # 定义数据读取器，训练数据读取器和验证数据读取器
    x = joblib.load('train/preprocess_file/20190701_x.pkl')
    y = joblib.load('train/preprocess_file/20190701_y.pkl')
    train_loader = data_loader(x, y)
    valid_loader = data_loader(x, y)

    best_acc = 0
    valid_acc = 0

    print('start training ... {} kind'.format(4))
    for epoch in range(epoch_num):
        all_loss = 0
        model.train()
        pbar = tqdm(train_loader())
        
        for batch_id, data in enumerate(pbar):
            x_data, y_data = data
            x = fluid.dygraph.to_variable(x_data)
            label = fluid.dygraph.to_variable(y_data)
            label = fluid.one_hot(label, depth=4)
            # 运行模型前向计算，得到预测值
            logits = model(x)
            # 进行loss计算
            softmax_logits = fluid.layers.softmax(logits)
            loss = fluid.layers.cross_entropy(softmax_logits, label, soft_label=True)
            avg_loss = fluid.layers.mean(loss)
            all_loss += avg_loss.numpy()
            avg_l = all_loss/(batch_id + 1)
            pbar.set_description("epoch: {}, batch_id: {}, loss is: {}, avg loss is: {}, valid acc is: {}".format(epoch, batch_id, avg_loss.numpy(), avg_l, 
            valid_acc))
            avg_loss.backward()
            opt.minimize(avg_loss)
            model.clear_gradients()
            # break
        model.eval()
        accuracies = []
        losses = []
        for batch_id, data in enumerate(valid_loader()):
            x_data, y_data = data
            img = fluid.dygraph.to_variable(x_data)
            label = fluid.dygraph.to_variable(y_data)
            # 运行模型前向计算，得到预测值
            logits = model(img)
            # 计算sigmoid后的预测概率，进行loss计算
            pred = fluid.layers.softmax(logits['clipwise_output'])
            acc = fluid.layers.accuracy(pred, fluid.layers.reshape(label, [-1, 1]))
            accuracies.append(acc.numpy())
        valid_acc = np.mean(accuracies)
        if valid_acc > best_acc and epoch >= 2:
            if valid_acc < 0.98:
                continue
            best_acc = np.mean(accuracies)
            # # save params of model
            fluid.save_dygraph(model.state_dict(), './params/{}fold_{}epoch_{:.3f}'.format(fold, epoch,best_acc))
            # save optimizer state
            fluid.save_dygraph(opt.state_dict(), './params/{}fold_{}epoch_{:.3f}'.format(fold, epoch, best_acc))

start training ... 4 kind

输出

0it [00:00, ?it/s]
=============get feature ==========
=============get feature ==========
start training ... 4 kind
[32, 5, 20]
---------------------------------------------------------------------------EnforceNotMet                             Traceback (most recent call last)<ipython-input-14-bb5124902d20> in <module>
     31             label = fluid.one_hot(label, depth=4)
     32             # 运行模型前向计算，得到预测值
---> 33             logits = model(x)
     34             # 进行loss计算
     35             softmax_logits = fluid.layers.softmax(logits)
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py in __call__(self, *inputs, **kwargs)
    693 
    694         with param_guard(self._parameters), param_guard(self._buffers):
--> 695             outputs = self.forward(*inputs, **kwargs)
    696 
    697         for forward_post_hook in self._forward_post_hooks.values():
<ipython-input-13-dc908a061df5> in forward(self, input)
     16         rnn_out, last_h, last_c = layers.lstm(input=x, init_h = self.init_h, init_c = self.init_c, 
     17                                                 max_len = self.max_len, hidden_size = self.hidden_size,
---> 18                                                 num_layers = self.num_layers, dropout_prob=self.dropout_prob, is_bidirec=True)
     19         rnn_out = layers.reshape(rnn_out, shape=[rnn_out.shape[0], 1, rnn_out.shape[1], rnn_out.shape[2]])
     20         mean_pool_out = layers.pool2d(rnn_out,pool_type='avg', pool_size=(rnn_out.shape[2], 1), pool_stride=(rnn_out.shape[2], 1))
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/layers/rnn.py in lstm(input, init_h, init_c, max_len, hidden_size, num_layers, dropout_prob, is_bidirec, is_test, name, default_initializer, seed)
   2495             'is_test': is_test,
   2496             'dropout_prob': dropout_prob,
-> 2497             'seed': seed,
   2498         })
   2499     return out, last_h, last_c
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/layer_helper.py in append_op(self, *args, **kwargs)
     41 
     42     def append_op(self, *args, **kwargs):
---> 43         return self.main_program.current_block().append_op(*args, **kwargs)
     44 
     45     def multiple_input(self, input_param_name='input'):
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/framework.py in append_op(self, *args, **kwargs)
   2869                                        kwargs.get("outputs", {}), attrs
   2870                                        if attrs else {},
-> 2871                                        kwargs.get("stop_gradient", False))
   2872         else:
   2873             op_desc = self.desc.append_op()
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/tracer.py in trace_op(self, type, inputs, outputs, attrs, stop_gradient)
     43         self.trace(type, inputs, outputs, attrs,
     44                    framework._current_expected_place(), self._train_mode and
---> 45                    not stop_gradient)
     46 
     47     def train_mode(self):
EnforceNotMet: 

--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
0   paddle::imperative::Tracer::TraceOp(std::string const&, paddle::imperative::NameVarBaseMap const&, paddle::imperative::NameVarBaseMap const&, paddle::framework::AttributeMap, paddle::platform::Place const&, bool)
1   paddle::imperative::OpBase::Run(paddle::framework::OperatorBase const&, paddle::imperative::NameVarBaseMap const&, paddle::imperative::NameVarBaseMap const&, paddle::framework::AttributeMap const&, paddle::platform::Place const&)
2   paddle::imperative::PreparedOp::Run(paddle::imperative::NameVarBaseMap const&, paddle::imperative::NameVarBaseMap const&, paddle::framework::AttributeMap const&)
3   std::_Function_handler<void (paddle::framework::ExecutionContext const&), paddle::framework::OpKernelRegistrarFunctor<paddle::platform::CUDAPlace, false, 0ul, paddle::operators::CudnnLSTMGPUKernel<float>, paddle::operators::CudnnLSTMGPUKernel<double> >::operator()(char const*, char const*, int) const::{lambda(paddle::framework::ExecutionContext const&)#1}>::_M_invoke(std::_Any_data const&, paddle::framework::ExecutionContext const&)
4   paddle::operators::CudnnLSTMGPUKernel<float>::Compute(paddle::framework::ExecutionContext const&) const
5   paddle::platform::EnforceNotMet::EnforceNotMet(std::__exception_ptr::exception_ptr, char const*, int)
6   std::string paddle::platform::GetTraceBackString<char const*>(char const*&&, char const*, int)
7   paddle::platform::GetCurrentTraceBackString()

----------------------
Error Message Summary:
----------------------
ExternalError:  Cudnn error, CUDNN_STATUS_EXECUTION_FAILED  (at /paddle/paddle/fluid/operators/cudnn_lstm_op.cu.cc:99)
  [operator < cudnn_lstm > error]

**Comment by GaoWei8** [comment]
lstm接口在2.0版本中进行重构。layers.lstm接口已废弃，2.0rc版会发布最新的class LSTM。

**Comment by guoshengCS** [comment]
这里报CUDNN_STATUS_EXECUTION_FAILED这个错可能是因为init_h和init_c的shape的不太正确，看贴的代码是`self.init_h = layers.fill_constant([self.num_layers, self.max_len, 20], 'float32', 0.0 )`，正确的形状应该不包含max_len，应该是`  [num_layers,batch_size,hidden_size]`（单向）或者` [num_layers∗2,batch_size,hidden_size]
 `（双向），可以参考这里的文档 https://www.paddlepaddle.org.cn/documentation/docs/zh/2.0-rc1/api/paddle/fluid/layers/lstm_cn.html#lstm 。

另外看贴代码是使用的动态图，`fluid.layers.lstm`这个接口只能用于静态图，这也有些问题。建议使用Paddle 2.0中提供的LSTM接口，可以参考这里 https://www.paddlepaddle.org.cn/documentation/docs/zh/2.0-rc1/api/paddle/nn/layer/rnn/LSTM_cn.html#lstm ，新的接口对于CPU和GPU相较之前都有性能上的提升，这里是一个简单的例子：
```python
import paddle
import paddle.fluid as fluid
import numpy as np
paddle.seed(123)
np.random.seed(123)

batch_size = 64
max_len = 128
in_size = 128
hid_size = 128
num_layers = 2 
rnn = paddle.nn.LSTM(in_size, hid_size, num_layers, direction="bidirectional")
seq_len = np.random.randint(1, max_len, (batch_size,))
for i in range(10):
    x = paddle.randn((batch_size, max_len, in_size))
    x.stop_gradient = False
    prev_h = paddle.randn((num_layers * 2, batch_size, hid_size))
    prev_c = paddle.randn((num_layers * 2, batch_size, hid_size))
    seq_len = paddle.to_tensor(seq_len)
    y, (h, c) = rnn(x, (prev_h, prev_c), seq_len)
    loss = paddle.mean(h)
    loss.backward()
    optimizer = paddle.optimizer.Adam(learning_rate=0.1, parameters=rnn.parameters())
    optimizer.step()
    optimizer.clear_grad()
```

此外在PaddleNLP中也提供了LSTM做文本分类的模型代码 ，可以参考 https://github.com/PaddlePaddle/models/tree/release/2.0-beta/PaddleNLP/examples/text_classification/rnn
