### ISSUE TITLE
有没有Paddle版本对应Tensorrt版本查询表格？

### ISSUE THREAD

**Issue by ulanbator** [PaddlePaddle/Paddle#28174]
环境：
tensorrt                  6.0.1.5     
paddlepaddle-gpu          1.8.5.post97  

报错信息：
TensorRT dynamic library (libnvinfer.so) that Paddle depends on is not configured correctly. (error code is libnvinfer.so: cannot open shared object file: No such file or directory)
  Suggestions:
  1. Check if TensorRT is installed correctly and its version is matched with paddlepaddle you installed.
  2. Configure TensorRT dynamic library environment variables as follows:
  - Linux: set LD_LIBRARY_PATH by `export LD_LIBRARY_PATH=...`
  - Windows: set PATH by `set PATH=XXX;2020-10-21 16:38:16,329-INFO: not find model file path ./inference/ch_ppocr_mobile_v1.1_det_infer//model

搞PaddleOCR的环境搞一天了，不是这错就是那不兼容，好难。。。。。。。

**Comment by cryoco** [comment]
您好，paddleocr尚未支持tensorrt预测，这段只是系统中不包含TRT时的warning信息，不影响您继续使用paddleocr。这段warning确实有些不明确，我们在下一个版本中对其进行了精简，感谢反馈。

**Comment by ulanbator** [comment]
谢谢！

**Comment by knightyxp** [comment]
aistudio@jupyter-428915-1047397:~/work/PaddleSeg$ python ./pdseg/train.py --use_gpu --cfg ./configs/ocrnet_lane.yaml
TensorRT dynamic library (libnvinfer.so) that Paddle depends on is not configured correctly. (error code is libnvrtc.so.11.0: cannot open shared object file: No such file or directory)
  Suggestions:
  1. Check if TensorRT is installed correctly and its version is matched with paddlepaddle you installed.
  2. Configure TensorRT dynamic library environment variables as follows:
  - Linux: set LD_LIBRARY_PATH by `export LD_LIBRARY_PATH=...`
  - Windows: set PATH by `set PATH=XXX;Traceback (most recent call last):
  File "./pdseg/train.py", line 457, in <module>
    paddle.enable_static()
AttributeError: module 'paddle' has no attribute 'enable_static'
同样的错误 aistudio cuda9.2根本找不到tensorrt对应的版本 哭了
