### ISSUE TITLE
使用 Paddle-Lite的opt工具将训练的模型转为arm下部署出问题

### ISSUE THREAD

**Issue by liucaiji** [PaddlePaddle/Paddle#28189]
我在百度AI平台高级版上训练了一个目标检测的模型，然后参考 Paddle-Lite的文档用opt工具将这个初步转换后的模型试着转换为arm下可以部署的模型，第一次因为使用的Norm Type为gn的预训练模型，报错不支持。在换bn的模型重新训练过后准备转换时出现了新的错误。
model_parser.cc:64] Check failed: version == 0U (4200848394 vs. 0) Only version 0 is supported
*** Check failure stack trace: ***

整个操作过程如下
paddle_lite_opt --model_dir=freeze_model       --valid_targets=arm       --optimize_out_type=naive_buffer       --optimize_out=mobilenet_opt
WARNING: Logging before InitGoogleLogging() is written to STDERR
I1021 20:49:09.718012  6415 cxx_api.cc:254] Load model from file.
F1021 20:49:09.739815  6415 model_parser.cc:64] Check failed: version == 0U (4200848394 vs. 0) Only version 0 is supported
*** Check failure stack trace: ***
Aborted (core dumped)

**Comment by hong19860320** [comment]
请示用最新版（2.6.3）的opt工具 https://github.com/PaddlePaddle/Paddle-Lite/releases/tag/v2.6.3 重新生成模型试试 ，建议在运行opt工具前，设置环境变量export GLOG_v=5，把详细的错误信息贴上来，谢谢。
