### ISSUE TITLE
参照 model 中 dygraph 版本的 CycleGAN 代码进行复现，失败

### ISSUE THREAD

**Issue by TWLemontree** [PaddlePaddle/Paddle#28187]
我参照 paddle 的 model 仓库里 dygraph 中的 CycleGAN 代码，编写了我自己的 CycleGAN 代码。我跑了下 pp 官方的代码，效果很 nice ， 但我自己的代码跑出来全是噪声图片，我改了3个星期代码，完全不知道错误到底出在哪里。

https://aistudio.baidu.com/aistudio/projectdetail/1137630?qq-pf-to=pcqq.c2c&shared=1

求大佬帮我看一眼otz，自闭，谢谢您了otz

**Comment by tink2123** [comment]
可以给两个网络同样的输入和同样的初始化，然后查看一下各层的输入结果，比对一下哪里有diff。

**Comment by TWLemontree** [comment]
好的


| |
W. Tan
|
|
邮箱：tw_lemontree@163.com
|

签名由 网易邮箱大师 定制

在2020年10月22日 11:05，xiaoting 写道：

可以给两个网络同样的输入和同样的初始化，然后查看一下各层的输入结果，比对一下哪里有diff。

**Comment by tink2123** [comment]
大概看了一下你的组网代码，好像没有找到反卷积层的定义，可以再参考一下models里的结构～
