### ISSUE TITLE
PaddlePaddle的一点小建议

### ISSUE THREAD

**Issue by yulu12138** [PaddlePaddle/Paddle#28193]
欢迎您对PaddlePaddle提出建议，非常感谢您对PaddlePaddle的贡献！
在留下您的建议时，辛苦您同步提供如下信息：
- 版本、环境信息
1）PaddlePaddle版本：请提供您的PaddlePaddle版本号，例如1.1
2）CPU/GPU：您是否使用GPU进行训练，如是，请提供您的CUDA和cuDNN版本号
3）系统环境：请您描述系统类型、版本，例如Mac OS 10.14
注：您可以通过执行[summary_env.py](https://github.com/PaddlePaddle/Paddle/blob/develop/tools/summary_env.py)获取以上信息。
- 复现信息：如为报错，请给出复现环境、复现步骤
- 建议描述：请您详细描述，您认为需优化的功能

Thank you for contributing to PaddlePaddle.
Before submitting the issue, you could search issue in the github in case that there was a similar issue submitted or resolved before.
Please make sure that this is a feature request. 
**System information**
-PaddlePaddle version （eg.1.1）or CommitID
-CPU: including CPUMKL/OpenBlas/MKLDNN version
-GPU: including CUDA/CUDNN version
-OS Platform (eg.Mac OS 10.14)
Note: You can get most of the information by running [summary_env.py](https://github.com/PaddlePaddle/Paddle/blob/develop/tools/summary_env.py). 
**To Reproduce**
Steps to reproduce the behavior
**Describe the feature and the current behavior/state.**
**Any Other info.**
请问可以类似TensorFlow一样增加gpu加速sklearn的支持吗。初学者对于sklearn的使用较频繁，使用AI studio训练sklearn里的模型时比较慢，但是又不可以使用TensorFlow进行gpu加速，因此希望能够增加一些这方面的依赖。

**Comment by gfwm2013** [comment]
@yulu12138 感谢建议，您的需求我会向内部进行反馈的。

**Comment by gp1322719830** [comment]
可否添加模型版本号这个成员变量，方便模型更新，校验、维护
