### ISSUE TITLE
Can Tensor::Slice support for begin_idx==end_idx

### ISSUE THREAD

**Issue by flishwang** [PaddlePaddle/Paddle#28190]
Currently, the end_idx passed toTensor::Slice must be larger than begin_idx (see:
https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/fluid/framework/tensor.cc : 93)

However,  a slice with size 0 is quite useful, i.e. when getting data from an empty slot of a LodTensor.
Meanwhile, I notice that it's valid to declare a tensor with size 0.

So I wonder if it's possible to remove this restriction and allow slicing a tensor with begin_idx == end_idx?

**Comment by gfwm2013** [comment]
@flishwang Thank you for your suggestion, I will feedback internally whether your suggestion is feasible.
