### ISSUE TITLE
embedding层可能用float64时有bug？

### ISSUE THREAD

**Issue by starsblinking** [PaddlePaddle/Paddle#28206]
简单描述下。例如，我在输入data层后接一个paddle.fluid.layers.embedding层，设dtype=float32，后接其他网络结构，这时能正常训练：
x = embedding(..., dtype='float32')
y = other_network(x)
但如果将embedding层的dtype改为float64, 后接paddle.fluid.layers.cast转为float32（为保证后续网络输入类型不受影响)，再接原来同样的其他网络，则会报错:
x = embedding(..., dtype='float64')
x = cast(x, 'float32')
y = other_network(x)

报错信息：
Error Message Summary:

InvalidArgumentError: Tensor holds the wrong type, it holds double, but desires to be float.
  [Hint: Expected valid == true, but received valid:0 != true:1.] at (/paddle/paddle/fluid/framework/tensor_impl.h:33)
  [operator < distributed_lookup_table > error]
terminate called after throwing an instance of 'paddle::platform::EnforceNotMet'
  what():

C++ Call Stacks (More useful to developers):

0   std::string paddle::platform::GetTraceBackString<std::string const&>(std::string const&, char const*, int)
1   paddle::platform::EnforceNotMet::EnforceNotMet(std::string const&, char const*, int)
2   float const* paddle::framework::Tensor::data< float >() const
3   paddle::operators::distributed::prefetch_core(std::vector<long, std::allocator<long> > const&, std::vector<std::pair<std::string, std::string>, std::allocator<std::pair<std::string, std::string> > > const&, std::vector<long, std::allocator<long> > const&, paddle::framework::ExecutionContext const&, paddle::framework::Scope const&, std::unordered_map<long, std::vector<float, std::allocator< float > >, std::hash<long>, std::equal_to<long>, std::allocator<std::pair<long const, std::vector<float, std::allocator< float > > > > >*)
4   paddle::operators::distributed::prefetchs(std::vector<std::string, std::allocator<std::string> > const&, std::vector<std::string, std::allocator<std::string> > const&, std::string const&, bool, std::vector<std::string, std::allocator<std::string> > const&, std::vector<std::string, std::allocator<std::string> > const&, std::vector<long, std::allocator<long> > const&, paddle::framework::ExecutionContext const&, paddle::framework::Scope const&)
5   paddle::operators::DistributedLookupTableKernel< float >::Compute(paddle::framework::ExecutionContext const&) const
6   std::_Function_handler<void (paddle::framework::ExecutionContext const&), paddle::framework::OpKernelRegistrarFunctor<paddle::platform::CPUPlace, false, 0ul, paddle::operators::DistributedLookupTableKernel< float > >::operator()(char const*, char const*, int) const::{lambda(paddle::framework::ExecutionContext const&)#1}>::_M_invoke(std::_Any_data const&, paddle::framework::ExecutionContext const&)
7   paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, paddle::platform::Place const&, paddle::framework::RuntimeContext*) const
8   paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, paddle::platform::Place const&) const
9   paddle::framework::OperatorBase::Run(paddle::framework::Scope const&, paddle::platform::Place const&)
10  paddle::framework::HogwildWorker::TrainFiles()

注意到其中有 'DistributedLookupTableKernel< float >'字样，看起来是embeding层没有设为double类型？

- 版本、环境信息：
    1）PaddlePaddle版本：1.8.5

- 训练信息
    1）多机，cpu，fleet.parameter_server.distribute_transpiler

**Comment by DannyIsFunny** [comment]
你好，我们当前embedding层还不支持设置为double类型

**Comment by starsblinking** [comment]
> 你好，我们当前embedding层还不支持设置为double类型

对double的支持在开发计划内了吗? 如果没有的话，希望未来能支持一下～我有这方面的需求。多谢！

**Comment by starsblinking** [comment]
文档里目前写着的是支持double https://www.paddlepaddle.org.cn/documentation/docs/zh/api_cn/fluid_cn/embedding_cn.html#embedding
