### ISSUE TITLE
Win10 Py3.8 import paddle.fluid报错ImportError: DLL load failed while importing core_avx

### ISSUE THREAD

**Issue by snow-orld** [PaddlePaddle/Paddle#28205]
运行环境：
```
Paddle version: None
Paddle With CUDA: None
OS: Windows 10
Python version: 3.8.4
CUDA version: None
cuDNN version: None
Nvidia driver version: None
```

安装方式pip
```
python -m pip install paddlepaddle -i https://pypi.tuna.tsinghua.edu.cn/simple
```

成功安装后，运行```pip list```确认已安装paddlepaddle
```
Package           Version
----------------- ----------
...
paddlepaddle      1.8.5
```

在cmd中进入python解释器：
```
> python
>>> import paddle.fluid
```
报错：
```
Python 3.8.4 (tags/v3.8.4:dfa645a, Jul 13 2020, 16:46:45) [MSC v.1924 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import paddle.fluid
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Program Files\Python38\lib\site-packages\paddle\__init__.py", line 37, in <module>
    import paddle.complex
  File "C:\Program Files\Python38\lib\site-packages\paddle\complex\__init__.py", line 15, in <module>
    from . import tensor
  File "C:\Program Files\Python38\lib\site-packages\paddle\complex\tensor\__init__.py", line 15, in <module>
    from . import mat
  File "C:\Program Files\Python38\lib\site-packages\paddle\complex\tensor\math.py", line 15, in <module>
    from paddle.common_ops_import import *
  File "C:\Program Files\Python38\lib\site-packages\paddle\common_ops_import.py", line 15, in <module>
    from paddle.fluid.layer_helper import LayerHelper
  File "C:\Program Files\Python38\lib\site-packages\paddle\fluid\__init__.py", line 35, in <module>
    from . import framework
  File "C:\Program Files\Python38\lib\site-packages\paddle\fluid\framework.py", line 35, in <module>
    from . import core
  File "C:\Program Files\Python38\lib\site-packages\paddle\fluid\core.py", line 273, in <module>
    raise e
  File "C:\Program Files\Python38\lib\site-packages\paddle\fluid\core.py", line 243, in <module>
    from .core_avx import *
ImportError: DLL load failed while importing core_avx: 找不到指定的模块。
```

**Comment by gfwm2013** [comment]
@snow-orld 可以尝试一下使用python3.8.0

**Comment by snow-orld** [comment]
我在另一台Win10笔记本上安装后不会报错，导入成功。用的也是Python3.8.4

**Comment by gfwm2013** [comment]
@snow-orld 可能这台windows机器的环境存在着一些问题。

**Comment by snow-orld** [comment]
已解决。
```C:\Program Files\Python38\lib\site-packages\paddle\fluid```文件夹下的core_avx.pyd加载出错，[因为](https://support.pyxll.com/hc/en-gb/articles/360041392893-Error-importing-Python-module-DLL-load-failed#:~:text=DLL%20load%20failed%3A%20The%20specified%20module%20could%20not,that%20is%20what%20this%20error%20is%20telling%20you.):

>DLL load failed: The specified module could not be found When a Python extension module is compiled it may depend on some additional libraries called DLLs, or Dynamic Link Libraries. If these DLLs can't be found when trying to load the Python extension module then the module won't be able to be imported and that is what this error is telling you.

出问题的台式机只装了Microsoft Visual C++ 2015 Redistributable，运行OK的笔记本上是Microsoft Visual C++ 2017 Redistributable。 安装Microsoft Visual C++ 2017 Redistributable后，问题解决。

Microsoft Visual C++ 2017 Redistributable安装方法：https://social.msdn.microsoft.com/Forums/vstudio/en-US/e653a57a-bc32-4134-87bf-df33058f0531/download-microsoft-visual-c-2017-redistributable

**Comment by AlbieRWang** [comment]
> 已解决。
> `C:\Program Files\Python38\lib\site-packages\paddle\fluid`文件夹下的core_avx.pyd加载出错，[因为](https://support.pyxll.com/hc/en-gb/articles/360041392893-Error-importing-Python-module-DLL-load-failed#:~:text=DLL%20load%20failed%3A%20The%20specified%20module%20could%20not,that%20is%20what%20this%20error%20is%20telling%20you.):
> 
> > DLL load failed: The specified module could not be found When a Python extension module is compiled it may depend on some additional libraries called DLLs, or Dynamic Link Libraries. If these DLLs can't be found when trying to load the Python extension module then the module won't be able to be imported and that is what this error is telling you.
> 
> 出问题的台式机只装了Microsoft Visual C++ 2015 Redistributable，运行OK的笔记本上是Microsoft Visual C++ 2017 Redistributable。 安装Microsoft Visual C++ 2017 Redistributable后，问题解决。
> 
> Microsoft Visual C++ 2017 Redistributable安装方法：https://social.msdn.microsoft.com/Forums/vstudio/en-US/e653a57a-bc32-4134-87bf-df33058f0531/download-microsoft-visual-c-2017-redistributable

谢谢，但是好奇怪哦用的微软的常用运行库安装的vc++ 不行，卸载之后再装链接里的正常了

**Comment by cloudy-sfu** [comment]
我在使用pyinstaller打包依赖paddlepaddle的程序时出现了相同问题. 在普通*.py脚本运行时, paddlepaddle会在 `C:\Users\username\AppData\Local\` 位置创建一个以 `_MEI` 开头的随机文件夹, 并且里面包含依赖库, 例如 paddle 文件夹, 但是缺少 `paddle/libs`.
