### ISSUE TITLE
框架外自定义c++ operator报错：bad_allocator

### ISSUE THREAD

**Issue by flishwang** [PaddlePaddle/Paddle#28207]
基于rpn_target_assign_op.cc的代码在框架外自定义算子遇到报错，请问这个报错信息是什么意思，代码哪里写错了，应该如何调试？
之前基于generate_proposals_op.cc generate_proposals_op.cu的代码改的算子是可以正常运行的。

- 版本、环境信息：
Paddle version: 1.8.3
Paddle With CUDA: True

OS: debian stretch/sid
Python version: 3.7.7

CUDA version: 10.1.243
cuDNN version: 7.6.5
Nvidia driver version: 418.87.00

- 训练信息
    1）单机，CPU

步骤：

将paddle 1.8.3源代码中的rpn_target_assign_op.cc拷出至src目录，将代码中的RpnTargetAssign替换为RpnTargetAssign2，
将代码中的rpn_target_assign替换为rpn_target_assign2，其它内容不变。代码如文件所示：
[rpn_target_assign2_op.cc.txt](https://github.com/PaddlePaddle/Paddle/files/5419952/rpn_target_assign2_op.cc.txt)

然后执行：
g++-4.8 src/rpn_target_assign2_op.cc -o build/rpn_target_assign.so -DPADDLE_WITH_MKLDNN -O3 -g -I /home/bwang/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/include/third_party/ -I /home/bwang/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/include -I /usr/local/cuda/bin/../include  -shared -fPIC -std=c++11 -L /home/bwang/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/libs -L /usr/local/pycharm/bin -L /usr/local/cuda/lib64 -L /usr/local/lib -Wl,-rpath=/home/bwang/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/libs:/usr/local/pycharm/bin:/usr/local/cuda/lib64:/usr/local/lib: -lpaddle_framework -lcudart

成功生成build/rpn_target_assign.so

然后将python代码中的rpn_target_assign函数拷出，将其中的rpn_target_assign替换为rpn_target_assign2，代码如文件所示：
[rpn_target_lib.py.txt](https://github.com/PaddlePaddle/Paddle/files/5419956/rpn_target_lib.py.txt)

最后执行测试代码：

```

from paddle import fluid
import rpn_target_lib
import numpy as np
bbox_pred=fluid.layers.data(name='data',shape=[1,10,4],dtype='float32',append_batch_size=False)
cls_logits=fluid.layers.data(name='cls_logits',shape=[1,10,1],dtype='float32',append_batch_size=False)
anchor=fluid.layers.data(name='anchor',shape=[10,4],dtype='float32',append_batch_size=False)
anchor_var=fluid.layers.data(name='anchor_var',shape=[10,4],dtype='float32',append_batch_size=False)
gt_boxes=fluid.layers.data(name='gt_boxes',shape=[2,4],dtype='float32',append_batch_size=False)
is_crowd=fluid.layers.data(name='is_crowd',shape=[2],dtype='int32',append_batch_size=False)
im_info=fluid.layers.data(name='im_info',shape=[1,3],dtype='float32',append_batch_size=False)
outs=rpn_target_lib.rpn_target_assign2(bbox_pred,cls_logits,anchor,anchor_var,gt_boxes,is_crowd,im_info,6,0,0.5,0.5,0.5,True)
place=fluid.CPUPlace()
exe=fluid.Executor(place)

feeds={
    'data': np.zeros((1,10,4),dtype='float32'),
    'cls_logits': np.arange(0,1,0.1).reshape(1,10,1),
    'anchor': np.array([[0,0,10,10],[10,10,20,20],[20,20,30,30],
                        [30,30,40,40],[40,40,50,50],[50,50,60,60],
                        [60,60,70,70],[70,70,80,80],[80,80,90,90],[90,90,100,100]],dtype='float32'),
    'anchor_var': np.ones((10,4),dtype='float32'),
    'gt_boxes': fluid.create_lod_tensor(np.array([[0,0,10,10],[99,99,110,110]]),[[2]],place),
    'is_crowd': fluid.create_lod_tensor(np.array([0,0],dtype='int32'),[[2]],place),
    'im_info': fluid.create_lod_tensor(np.array([[200,200,1.0]]),[[1]],place)
}

outs=exe.run(feed=feeds,fetch_list=outs)

```

报错，仅提示bad_alloc。

在PaddleDetection中使用新生成的算子，可得到更详细的报错信息如下：
```
W1022 10:48:17.883935 14544 operator.cc:187] rpn_target_assign2 raises an exception std::bad_alloc, std::bad_alloc
F1022 10:48:17.883988 14544 exception_holder.h:37] std::exception caught, std::bad_alloc
*** Check failure stack trace: ***
    @     0x7f17d8fc6add  google::LogMessage::Fail()
    @     0x7f17d8fca58c  google::LogMessage::SendToLog()
    @     0x7f17d8fc6603  google::LogMessage::Flush()
    @     0x7f17d8fcba9e  google::LogMessageFatal::~LogMessageFatal()
    @     0x7f17dc1975b8  paddle::framework::details::ExceptionHolder::Catch()
    @     0x7f17dc2326ae  paddle::framework::details::FastThreadedSSAGraphExecutor::RunOpSync()
    @     0x7f17dc23004f  paddle::framework::details::FastThreadedSSAGraphExecutor::RunOp()
    @     0x7f17dc230314  _ZNSt17_Function_handlerIFvvESt17reference_wrapperISt12_Bind_simpleIFS1_ISt5_BindIFZN6paddle9framework7details28FastThreadedSSAGraphExecutor10RunOpAsyncEPSt13unordered_mapIPNS6_12OpHandleBaseESt6atomicIiESt4hashISA_ESt8equal_toISA_ESaISt4pairIKSA_SC_EEESA_RKSt10shared_ptrINS5_13BlockingQueueImEEEEUlvE_vEEEvEEEE9_M_invokeERKSt9_Any_data
    @     0x7f17d9023fb3  std::_Function_handler<>::_M_invoke()
    @     0x7f17d8e1f647  std::__future_base::_State_base::_M_do_set()
    @     0x7f1824648a99  __pthread_once_slow
    @     0x7f17dc22c4e2  _ZNSt13__future_base11_Task_stateISt5_BindIFZN6paddle9framework7details28FastThreadedSSAGraphExecutor10RunOpAsyncEPSt13unordered_mapIPNS4_12OpHandleBaseESt6atomicIiESt4hashIS8_ESt8equal_toIS8_ESaISt4pairIKS8_SA_EEES8_RKSt10shared_ptrINS3_13BlockingQueueImEEEEUlvE_vEESaIiEFvvEE6_M_runEv
    @     0x7f17d8e21aa4  _ZZN10ThreadPoolC1EmENKUlvE_clEv
    @     0x7f1816364421  execute_native_thread_routine_compat
    @     0x7f18246416ba  start_thread
    @     0x7f182437741d  clone
    @              (nil)  (unknown)

Process finished with exit code 134 (interrupted by signal 6: SIGABRT)
```

**Comment by flishwang** [comment]
进一步定位发现，当程序执行到：

**Comment by flishwang** [comment]
进一步定位发现，当程序执行到：
gt_boxes->lod()
时，就会报错。

generate_proposals_op.cc能正常运行，是因为context.Input只有Tensor，没有LodTensor
为什么LodTensor::lod()的执行会报bad_alloc这个错呢？

**Comment by DannyIsFunny** [comment]
你好，已经反馈相关开发同学，在等待其反馈

**Comment by qingqing01** [comment]
@flishwang 我们先排查下。 另外,

在fluid.data定义时，注意是LoDTensor的，请注意正确设置 lod_level，比如`gt_boxes`:

```
gt_boxes=fluid.layers.data(name='gt_boxes',shape=[2,4],dtype='float32',append_batch_size=False, lod_level=1)
```

**Comment by flishwang** [comment]
> @flishwang 我们先排查下。 另外,
> 
> 在fluid.data定义时，注意是LoDTensor的，请注意正确设置 lod_level，比如`gt_boxes`:
> 
> ```
> gt_boxes=fluid.layers.data(name='gt_boxes',shape=[2,4],dtype='float32',append_batch_size=False, lod_level=1)
> ```

好的。请问你们能复现这个问题吗？

另外我设法通过python端组合ops，绕过了这个需求。所以这个问题不是很急。

**Comment by qingqing01** [comment]
@flishwang 问题已经复现了，有结论会同步出来。

**Comment by qingqing01** [comment]
@flishwang  编译的命令有误, 需增加以下宏开关:

```
-DPADDLE_WITH_CUDA -DEIGEN_USE_GPU -DPADDLE_USE_DSO -DPADDLE_WITH_MKLDNN
```

原因是您安装的是GPU的whl包，[注意文档中的注意点](https://www.paddlepaddle.org.cn/documentation/docs/zh/advanced_guide/addon_development/new_op/custom_op.html#id1)，即使您这个Op是CPU的op，仍需要加这些CUDA相关的宏开关，原因是底层的LoD的数据结构在ONLY CPU和CUDA编译时不同，需要保持和您安装的PaddlePaddle包一致:

https://github.com/PaddlePaddle/Paddle/blob/1c385e26f9e6727c66f971a33f930c59f75a6639/paddle/fluid/framework/mixed_vector.h#L34

我通过下载您的cc和py代码，可以正确测试:

编译命令:
make.sh
```
include_dir=$( python -c 'import paddle; print(paddle.sysconfig.get_include())' )
lib_dir=$( python -c 'import paddle; print(paddle.sysconfig.get_lib())' )
echo $include_dir
echo $lib_dir

g++ rpn_target_assign2_op.cc -o rpn_target_assign2_op.so -shared -fPIC -std=c++11 -O3 -DPADDLE_WITH_CUDA -DEIGEN_USE_GPU -DPADDLE_USE_DSO -DPADDLE_WITH_MKLDNN \
  -I ${include_dir} \
  -I ${include_dir}/third_party \
  -I /paddle/work/github/Paddle \
  -I /usr/local/cuda/include/ \
  -L ${lib_dir} -lpaddle_framework
```

测试代码:
```python
import paddle
import paddle.fluid as fluid
import rpn_target_lib
import numpy as np

# paddle.enable_static() 最新的rc版本需要

bbox_pred=fluid.layers.data(name='data',shape=[1,10,4],dtype='float32',append_batch_size=False)
cls_logits=fluid.layers.data(name='cls_logits',shape=[1,10,1],dtype='float32',append_batch_size=False)
anchor=fluid.layers.data(name='anchor',shape=[10,4],dtype='float32',append_batch_size=False)
anchor_var=fluid.layers.data(name='anchor_var',shape=[10,4],dtype='float32',append_batch_size=False)
gt_boxes=fluid.layers.data(name='gt_boxes',shape=[2,4],dtype='float32',append_batch_size=False, lod_level=1)
is_crowd=fluid.layers.data(name='is_crowd',shape=[2],dtype='int32',append_batch_size=False, lod_level=1)
im_info=fluid.layers.data(name='im_info',shape=[1,3],dtype='float32',append_batch_size=False)
outs=rpn_target_lib.rpn_target_assign2(bbox_pred,cls_logits,anchor,anchor_var,gt_boxes,is_crowd,im_info,6,0,0.5,0.5,0.5,True)
place=fluid.CPUPlace()
exe=fluid.Executor(place)

feeds={
    'data': np.zeros((1,10,4),dtype='float32'),
    'cls_logits': np.arange(0,1,0.1).reshape(1,10,1),
    'anchor':  np.array([[0,0,10,10],[10,10,20,20],[20,20,30,30],
                        [30,30,40,40],[40,40,50,50],[50,50,60,60],
                        [60,60,70,70],[70,70,80,80],[80,80,90,90],[90,90,100,100]],dtype='float32'),
    'anchor_var': np.ones((10,4),dtype='float32'),
    'gt_boxes': fluid.create_lod_tensor(np.array([[0,0,10,10],[99,99,110,110]], dtype='float32'),[[2]],place),
    'is_crowd': fluid.create_lod_tensor(np.array([0,0],dtype='int32'),[[2]],place),
    'im_info': fluid.create_lod_tensor(np.array([[200,200,1.0]], dtype='float32'),[[1]],place)
}


outs=exe.run(feed=feeds,fetch_list=outs, return_numpy=False)

print(np.array(outs[0]))
```

输出:

```
[[0. ]
 [0.3]
 [0.4]
 [0.6]
 [0.9]]
```

**Comment by flishwang** [comment]
> @flishwang 编译的命令有误, 需增加以下宏开关:
> 
> ```
> -DPADDLE_WITH_CUDA -DEIGEN_USE_GPU -DPADDLE_USE_DSO -DPADDLE_WITH_MKLDNN
> ```
> 
> 原因是您安装的是GPU的whl包，[注意文档中的注意点](https://www.paddlepaddle.org.cn/documentation/docs/zh/advanced_guide/addon_development/new_op/custom_op.html#id1)，即使您这个Op是CPU的op，仍需要加这些CUDA相关的宏开关，原因是底层的LoD的数据结构在ONLY CPU和CUDA编译时不同，需要保持和您安装的PaddlePaddle包一致:
> 
> https://github.com/PaddlePaddle/Paddle/blob/1c385e26f9e6727c66f971a33f930c59f75a6639/paddle/fluid/framework/mixed_vector.h#L34
> 
> 我通过下载您的cc和py代码，可以正确测试:
> 
> 编译命令:
> make.sh
> 
> ```
> include_dir=$( python -c 'import paddle; print(paddle.sysconfig.get_include())' )
> lib_dir=$( python -c 'import paddle; print(paddle.sysconfig.get_lib())' )
> echo $include_dir
> echo $lib_dir
> 
> g++ rpn_target_assign2_op.cc -o rpn_target_assign2_op.so -shared -fPIC -std=c++11 -O3 -DPADDLE_WITH_CUDA -DEIGEN_USE_GPU -DPADDLE_USE_DSO -DPADDLE_WITH_MKLDNN \
>   -I ${include_dir} \
>   -I ${include_dir}/third_party \
>   -I /paddle/work/github/Paddle \
>   -I /usr/local/cuda/include/ \
>   -L ${lib_dir} -lpaddle_framework
> ```
> 
> 测试代码:
> 
> ```python
> import paddle
> import paddle.fluid as fluid
> import rpn_target_lib
> import numpy as np
> 
> # paddle.enable_static() 最新的rc版本需要
> 
> bbox_pred=fluid.layers.data(name='data',shape=[1,10,4],dtype='float32',append_batch_size=False)
> cls_logits=fluid.layers.data(name='cls_logits',shape=[1,10,1],dtype='float32',append_batch_size=False)
> anchor=fluid.layers.data(name='anchor',shape=[10,4],dtype='float32',append_batch_size=False)
> anchor_var=fluid.layers.data(name='anchor_var',shape=[10,4],dtype='float32',append_batch_size=False)
> gt_boxes=fluid.layers.data(name='gt_boxes',shape=[2,4],dtype='float32',append_batch_size=False, lod_level=1)
> is_crowd=fluid.layers.data(name='is_crowd',shape=[2],dtype='int32',append_batch_size=False, lod_level=1)
> im_info=fluid.layers.data(name='im_info',shape=[1,3],dtype='float32',append_batch_size=False)
> outs=rpn_target_lib.rpn_target_assign2(bbox_pred,cls_logits,anchor,anchor_var,gt_boxes,is_crowd,im_info,6,0,0.5,0.5,0.5,True)
> place=fluid.CPUPlace()
> exe=fluid.Executor(place)
> 
> feeds={
>     'data': np.zeros((1,10,4),dtype='float32'),
>     'cls_logits': np.arange(0,1,0.1).reshape(1,10,1),
>     'anchor':  np.array([[0,0,10,10],[10,10,20,20],[20,20,30,30],
>                         [30,30,40,40],[40,40,50,50],[50,50,60,60],
>                         [60,60,70,70],[70,70,80,80],[80,80,90,90],[90,90,100,100]],dtype='float32'),
>     'anchor_var': np.ones((10,4),dtype='float32'),
>     'gt_boxes': fluid.create_lod_tensor(np.array([[0,0,10,10],[99,99,110,110]], dtype='float32'),[[2]],place),
>     'is_crowd': fluid.create_lod_tensor(np.array([0,0],dtype='int32'),[[2]],place),
>     'im_info': fluid.create_lod_tensor(np.array([[200,200,1.0]], dtype='float32'),[[1]],place)
> }
> 
> 
> outs=exe.run(feed=feeds,fetch_list=outs, return_numpy=False)
> 
> print(np.array(outs[0]))
> ```
> 
> 输出:
> 
> ```
> [[0. ]
>  [0.3]
>  [0.4]
>  [0.6]
>  [0.9]]
> ```

辛苦了！
文档里可能有歧义：
```
通过NVCC编译CUDA源文件时，需要加编译选项 -DPADDLE_WITH_CUDA -DEIGEN_USE_GPU -DPADDLE_USE_DSO
```
让我觉得通过g++编译cpp文件时不需要加。。。。

另外文档里的example:

```
g++ relu_op.cc relu_op.cu.o -o relu2_op.so -shared -fPIC -std=c++11 -O3 -DPADDLE_WITH_MKLDNN \
  -I ${include_dir} \
  -I ${include_dir}/third_party \
  -L /usr/local/cuda/lib64 \
  -L ${lib_dir} -lpaddle_framework -lcudart
```
这部分对relu_op.cc进行了编绎，是否意味着也需要加上述3个编绎选项？

**Comment by qingqing01** [comment]
@flishwang  您说的有道理，文档确实存在一些歧义。relu_op.cc按理觉得也需要加上。
