### ISSUE TITLE
人脸口罩预测出错

### ISSUE THREAD

**Issue by huyutao3550346** [PaddlePaddle/Paddle#28229]
- 版本、环境信息：
    1）PaddlePaddle版本：1.8.4(源码编译的形式)
    2）CPU：无
    3）GPU：CUDA=9.2，CUDNN=7.6
    4）系统环境：请您描述系统类型、版本（如Mac OS 10.14），Python版本
注：您可以通过执行[summary_env.py](https://github.com/PaddlePaddle/Paddle/blob/develop/tools/summary_env.py)获取以上信息。
-预测信息
    1）C++预测：
           version文件内容：
> > GIT COMMIT ID: 1e01335e195d993f3c5c97bed3a15a6f9170acea
> > WITH_MKL: ON
> > WITH_MKLDNN: ON
> > WITH_GPU: ON
> > WITH_MKL=OFF
> > CUDA version: 9.2
> > CUDNN version: v7.6
> > CXX compiler version: 4.8.5

    2）CMake包含路径的完整命令

CMake内容：
[CMakeLists.txt](https://github.com/PaddlePaddle/Paddle/files/5427841/CMakeLists.txt)

    3）API信息（如调用请提供）
    4）预测库来源：源代码编译
- 复现信息：如为报错，请给出复现环境、复现步骤
- 问题描述：

在使用https://github.com/PaddlePaddle/PaddleHub/tree/release/v1.8/demo/mask_detection/cpp 中的demo对图片进行预测。
结果再预测A图片时，运行正常。
下图为图片A：
![A](https://user-images.githubusercontent.com/29395068/96967845-abd7bf00-1542-11eb-9f1c-c878a9cf5d7b.jpg)

在预测B图片时，人脸检测部分代码正常，但是到口罩分类的时候，也就是这句代码时：
![image](https://user-images.githubusercontent.com/29395068/96968039-f6593b80-1542-11eb-94e0-c228b24bebfa.png)
程序就崩溃了，具体的报错内容在后面。
下图为图片B：
![B](https://user-images.githubusercontent.com/29395068/96968099-10931980-1543-11eb-862a-d304cc7dace3.jpg)

报错内容:
W1023 07:03:59.783375 143195 device_context.cc:252] Please NOTE: device: 0, CUDA Capability: 37, Driver API Version: 10.1, Runtime API Version: 9.2
W1023 07:03:59.787618 143195 device_context.cc:260] device: 0, cuDNN Version: 7.6.
-------------------------------这里开始报错-------------------------------------
terminate called after throwing an instance of 'paddle::platform::EnforceNotMet'
  what():  

--------------------------------------------
C++ Call Stacks (More useful to developers):
--------------------------------------------
0   std::string paddle::platform::GetTraceBackString<char const*>(char const*&&, char const*, int)
1   paddle::platform::EnforceNotMet::EnforceNotMet(std::__exception_ptr::exception_ptr, char const*, int)
2   paddle::platform::ScopedTensorDescriptor::descriptor(cudnnTensorFormat_t, cudnnDataType_t, std::vector<int, std::allocator<int> > const&, int)
3   paddle::operators::CUDNNConvFusionOpKernel<float>::Compute(paddle::framework::ExecutionContext const&) const
4   std::_Function_handler<void (paddle::framework::ExecutionContext const&), paddle::framework::OpKernelRegistrarFunctor<paddle::platform::CUDAPlace, false, 0ul, paddle::operators::CUDNNConvFusionOpKernel<float>, paddle::operators::CUDNNConvFusionOpKernel<double> >::operator()(char const*, char const*, int) const::{lambda(paddle::framework::ExecutionContext const&)#1}>::_M_invoke(std::_Any_data const&, paddle::framework::ExecutionContext const&)
5   paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, paddle::platform::Place const&, paddle::framework::RuntimeContext*) const
6   paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, paddle::platform::Place const&) const
7   paddle::framework::OperatorBase::Run(paddle::framework::Scope const&, paddle::platform::Place const&)
8   paddle::framework::NaiveExecutor::Run()
9   paddle::AnalysisPredictor::ZeroCopyRun()

------------------------------------------
Python Call Stacks (More useful to users):
------------------------------------------

----------------------
Error Message Summary:
----------------------
ExternalError:  Cudnn error, CUDNN_STATUS_BAD_PARAM  at (/home/huyutao/paddle/paddle/fluid/platform/cudnn_helper.h:246)
  [operator < conv2d_fusion > error]
Aborted (core dumped)

**Comment by juncaipeng** [comment]
paddle c++预测库主要支持cuda9.0和cuda10.0。口罩demo的文档有进行说明，如下图。你环境是cuda9.2，可能是此处导致问题。

![image](https://user-images.githubusercontent.com/52520497/96971804-37078380-1548-11eb-938a-2c64a3241e13.png)

建议使用paddle提供的预测库和运行环境。

**Comment by huyutao3550346** [comment]
@juncaipeng 非常感谢你的解答，由于我的环境还有其他的库是依附于cuda9.2编译的，所以要将paddle部署在我的环境中，还是要使用cuda9.2版本。
我还有一个疑问，如果cuda的问题，为什么图片A能顺利执行？如果是环境问题的话，一般来说，运行图片A应该也是会直接奔溃的吧。

**Comment by huyutao3550346** [comment]
刚刚加了下打印，发现是由于检测不到B图片的人脸，传了一个空的值到口罩分类模型中。将图片等比缩放下，就能跑通了。
