### ISSUE TITLE
<论文复现> paddle 函数报错

### ISSUE THREAD

**Issue by zhongqing0507** [PaddlePaddle/Paddle#28223]
我用的aistudio 环境是python 3.7 paddle 1.8.0, 当我运行程序时，报错： 
 elementwise_op_function.h:1068] Error, broadcast should not into w broadcast。
看到社区说需要更新paddle版本，我更到了paddle 1.8.5, 出现以下问题：

TensorRT dynamic library (libnvinfer.so) that Paddle depends on is not configured correctly. (error code is libnvrtc.so.11.0: cannot open shared object file: No such file or directory)
  Suggestions:
  1. Check if TensorRT is installed correctly and its version is matched with paddlepaddle you installed.
  2. Configure TensorRT dynamic library environment variables as follows:
  - Linux: set LD_LIBRARY_PATH by `export LD_LIBRARY_PATH=...`

请问怎么配置？谢谢！

**Comment by cryoco** [comment]
您好，这个信息只是在环境没找到TensorRT的时候的一个warning，不影响您继续使用paddle进行论文复现。这个信息有些不明确，我们在后续版本对其做了精简，感谢反馈。
