### ISSUE TITLE
报错怎么解决？

### ISSUE THREAD

**Issue by Masterkmp** [PaddlePaddle/Paddle#28235]
![图片](https://user-images.githubusercontent.com/37642547/97014532-0aba2a00-157d-11eb-9c0b-ddd4676e4d85.png)

**Comment by juncaipeng** [comment]
从log来看，是mul op输入维度错误，num_col_dims必须小于输入x的维度数量。
具体使用方法请参考：https://www.paddlepaddle.org.cn/documentation/docs/zh/api_cn/layers_cn/mul_cn.html#mul
