### ISSUE TITLE
paddle中有没有，pytorch 中mask_fill对应的函数，paddle中mask_select是改变了shape

### ISSUE THREAD

**Issue by BlackHorseQ** [PaddlePaddle/Paddle#28238]
是不是增加一些mask_select的功能使其不改变形状呢？
还是需要自己实现

x[x == 0] = 1

以及如何实现

**Comment by FrostML** [comment]
Paddle 目前还没有 masked_fill，我这边反馈一下。
关于这个功能，可以试试 `result = x * mask` 能否满足需求，`mask` 是一个仅有 0/1 的 Tensor，与 x 的 shape 相同，可以通过 比如 `paddle.cast((x == 0), dtype='float32')` 可以获得
