### ISSUE TITLE
求均值结果不一样

### ISSUE THREAD

**Issue by CZDGitH** [PaddlePaddle/Paddle#28239]
![QQ图片20201025183303](https://user-images.githubusercontent.com/40756915/97104659-9a341a00-16f0-11eb-8cc4-5fc9e349b44f.png)
![QQ图片20201025183314](https://user-images.githubusercontent.com/40756915/97104661-9c967400-16f0-11eb-8785-0fc18ee7f0ab.png)
https://www.paddlepaddle.org.cn/tutorials/projectdetail/1086957#anchor-1
我发现用计算方法求均值和用mean求的结果不一样，麻烦看下是什么原因？

**Comment by FrostML** [comment]
您好，对于求 mean 的操作，我这里测试是可以对上的
![image](https://user-images.githubusercontent.com/7160927/97142436-96a99d00-179b-11eb-999b-2a683660e7ac.png)

输出是：
![image](https://user-images.githubusercontent.com/7160927/97129169-33a70e80-1779-11eb-956e-1dbc86243bde.png)


您出现以上的问题应该是`training_data = data`之后，对 `data` 做了处理导致的，可以尝试将这个地方换成拷贝`training_data = data.copy()`，可以得到相同的结果。
