### ISSUE TITLE
paddle-gpu版本执行fluid.install_check.run_check()长时间运行（长时间不出结果 >10min）

### ISSUE THREAD

**Issue by SunHao-TSU** [PaddlePaddle/Paddle#28249]
win10系统，cuda版本10.0，cudnn版本7.6，paddle版本1.8及2.0，python版本3.7.9.
CPU 至强e5 2640，GPU 3090.
安装方式，pip 安装。

现象：
执行fluid.install_check.run_check()后，程序长时间后台运行，不反馈结果。
（cpu版本可以执行成功）

长时间运行后出现结果：
**Process finished with exit code -1**

ps: nvcc -V 信息
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2018 NVIDIA Corporation
Built on Sat_Aug_25_21:08:04_Central_Daylight_Time_2018
Cuda compilation tools, release 10.0, V10.0.130

---------------------------------------------
该机器上，**pytorch-gpu已经测试通过**

**Comment by cryoco** [comment]
请问您的机器是单卡还是多卡呢，您可以先试下能否正常使用paddle的功能

**Comment by SunHao-TSU** [comment]
> 请问您的机器是单卡还是多卡呢，您可以先试下能否正常使用paddle的功能

您好，飞桨不可以使用。
使用paddle的包会出现下面的的报错提示：

**Traceback (most recent call last):
  File "E:/prog/test/main.py", line 22, in <module>
    paddle.disable_static()
AttributeError: module 'paddle' has no attribute 'disable_static'**

**Comment by cryoco** [comment]
请问您是在测试官网的教程文档吗，需要保证官网文档的版本和paddle的版本一致哈
![image](https://user-images.githubusercontent.com/12407750/97173611-ce303d80-17cb-11eb-9b28-6026e3741a29.png)
您这个报错来看可能是您本地的paddle版本还没有`disable_static()`这个接口。

**Comment by SunHao-TSU** [comment]
> 请问您是在测试官网的教程文档吗，需要保证官网文档的版本和paddle的版本一致哈
> ![image](https://user-images.githubusercontent.com/12407750/97173611-ce303d80-17cb-11eb-9b28-6026e3741a29.png)
> 您这个报错来看可能是您本地的paddle版本还没有`disable_static()`这个接口。


我目前测试的就是2.0版本，用的也是2.0的官方实例代码。
cpu版本可以正常跑，gpu就不行。
（我电脑是双cpu+3090gpu）会有影响吗？

**Comment by cryoco** [comment]
您是安装的paddlepaddle-gpu==2.0.0-beta0版本吗

**Comment by SunHao-TSU** [comment]
> 您是安装的paddlepaddle-gpu==2.0.0-beta0版本吗

是的，确定。非常奇怪~

**Comment by SunHao-TSU** [comment]
> 您是安装的paddlepaddle-gpu==2.0.0-beta0版本吗

您好，确实是版本不对。修改版本之后，执行测试程序，执行结果与执行“fluid.install_check.run_check()”相同，即：程序在后台长时间运行没有结果。

**Comment by SunHao-TSU** [comment]
> 请问您的机器是单卡还是多卡呢，您可以先试下能否正常使用paddle的功能

有可能是3090和cuda10.0不适配导致的。 等paddle更新了win10 cuda11 我再尝试吧。
