### ISSUE TITLE
1.如何冻结参数 2.如何截取参数

### ISSUE THREAD

**Issue by applezjm** [PaddlePaddle/Paddle#28247]
1.如何在训练过程中冻结参数，求给一个示例

2.我们save_params的参数格式是16 * 768，如何截取前2 * 768个参数并重新save成相同格式？

**Comment by cryoco** [comment]
1.您指的冻结参数是指停止梯度回传吗？这里有一个[示例](https://www.paddlepaddle.org.cn/documentation/docs/zh/2.0-beta/api/paddle/fluid/framework/Variable_cn.html#id12)。
2.paddle目前暂不支持这种操作哈

**Comment by doge-ac-cn** [comment]
哇，为什么会有16 * 768的网络层参数呀，是用在什么地方的，好奇

**Comment by applezjm** [comment]
> 哇，为什么会有16 * 768的网络层参数呀，是用在什么地方的，好奇

poly-encoder
