### ISSUE TITLE
训练的时候提示build_strategy.cc:170] fusion_group is not enabled for Windows/MacOS now, and only effective when running with CUDA GPU.

### ISSUE THREAD

**Issue by tz28** [PaddlePaddle/Paddle#28244]
为使您的问题得到快速解决，在建立Issues前，请您先通过如下方式搜索是否有相似问题:【搜索issue关键字】【使用labels筛选】【官方文档】

如果您没有查询到相似问题，为快速解决您的提问，建立issue时请提供如下细节信息：
- 标题：训练的时候日志显示build_strategy.cc:170] fusion_group is not enabled for Windows/MacOS now, and only effective when running with CUDA GPU.然后就不训练了。
- 版本、环境信息：
    1）PaddlePaddle版本：1.8.2
    2）CPU：MPI集群
    3）GPU：无
    4）系统环境：
 注：您可以通过执行[summary_env.py](https://github.com/PaddlePaddle/Paddle/blob/develop/tools/summary_env.py)获取以上信息。
- 训练信息
    1）MPI分布式训练

- 问题描述：
![image](https://user-images.githubusercontent.com/9672354/97140989-d02cd900-1798-11eb-960f-186df09f389e.png)

Thank you for contributing to PaddlePaddle.
Before submitting the issue, you could search issue in the github in case that there was a similar issue submitted or resolved before.
If there is no solution,please make sure that this is a training issue including the following details:
**System information**
-PaddlePaddle version （eg.1.1）or CommitID
-CPU: including CPUMKL/OpenBlas/MKLDNN version
-GPU: including CUDA/CUDNN version
-OS Platform (eg.Mac OS 10.14)
-Other imformation: Distriuted training/informantion of operator/
Graphics card storage
Note: You can get most of the information by running [summary_env.py](https://github.com/PaddlePaddle/Paddle/blob/develop/tools/summary_env.py). 
**To Reproduce**
Steps to reproduce the behavior
**Describe your current behavior**
**Code to reproduce the issue**
**Other info / logs**

**Comment by xxlest** [comment]
遇到同样的问题 没人解决吗？

**Comment by yanchaoguo** [comment]
> 遇到同样的问题 没人解决吗？
+1

**Comment by A-k-ing** [comment]
```
2020-11-09 19:32:35,887-WARNING: Illegal image file: D:\Workspace\AI\Detection\PCB_DATASET\images\08_short_03.jpg, and it will be ignored
2020-11-09 19:32:35,887-WARNING: Found an empty segmentation in annotations: im_id: 589.
2020-11-09 19:32:35,888-WARNING: Found an empty segmentation in annotations: im_id: 589.
2020-11-09 19:32:35,888-WARNING: Found an empty segmentation in annotations: im_id: 589.
2020-11-09 19:32:35,888-WARNING: Found an empty segmentation in annotations: im_id: 590.
2020-11-09 19:32:35,889-WARNING: Found an empty segmentation in annotations: im_id: 590.
2020-11-09 19:32:35,889-WARNING: Found an empty segmentation in annotations: im_id: 590.
2020-11-09 19:32:35,889-WARNING: Illegal image file: D:\Workspace\AI\Detection\PCB_DATASET\images\04_short_17.jpg, and it will be ignored
2020-11-09 19:32:35,890-WARNING: Found an empty segmentation in annotations: im_id: 592.
2020-11-09 19:32:35,891-WARNING: Found an empty segmentation in annotations: im_id: 592.
2020-11-09 19:32:35,891-WARNING: Found an empty segmentation in annotations: im_id: 592.
W1109 19:32:35.962229 71108 build_strategy.cc:170] fusion_group is not enabled for Windows/MacOS now, and only effective when running with CUDA GPU.
```
直接卡住了

标题：训练的时候日志显示build_strategy.cc:170] fusion_group is not enabled for Windows/MacOS now, and only effective when running with CUDA GPU.然后就不训练了。

版本、环境信息：
   1）PaddlePaddle版本：1.8.5
   2）CPU：RYZEN 5 1600
   3）GPU：GTX 1050TI 4G
   4）系统环境：Windows10 1803 教育版
环境变量  MKL_DEBUG_CPU_TYPE=5

**Comment by cryoco** [comment]
> 遇到同样的问题 没人解决吗？



> > 遇到同样的问题 没人解决吗？
> > +1



> ```
> 2020-11-09 19:32:35,887-WARNING: Illegal image file: D:\Workspace\AI\Detection\PCB_DATASET\images\08_short_03.jpg, and it will be ignored
> 2020-11-09 19:32:35,887-WARNING: Found an empty segmentation in annotations: im_id: 589.
> 2020-11-09 19:32:35,888-WARNING: Found an empty segmentation in annotations: im_id: 589.
> 2020-11-09 19:32:35,888-WARNING: Found an empty segmentation in annotations: im_id: 589.
> 2020-11-09 19:32:35,888-WARNING: Found an empty segmentation in annotations: im_id: 590.
> 2020-11-09 19:32:35,889-WARNING: Found an empty segmentation in annotations: im_id: 590.
> 2020-11-09 19:32:35,889-WARNING: Found an empty segmentation in annotations: im_id: 590.
> 2020-11-09 19:32:35,889-WARNING: Illegal image file: D:\Workspace\AI\Detection\PCB_DATASET\images\04_short_17.jpg, and it will be ignored
> 2020-11-09 19:32:35,890-WARNING: Found an empty segmentation in annotations: im_id: 592.
> 2020-11-09 19:32:35,891-WARNING: Found an empty segmentation in annotations: im_id: 592.
> 2020-11-09 19:32:35,891-WARNING: Found an empty segmentation in annotations: im_id: 592.
> W1109 19:32:35.962229 71108 build_strategy.cc:170] fusion_group is not enabled for Windows/MacOS now, and only effective when running with CUDA GPU.
> ```
> 
> 直接卡住了
> 
> 标题：训练的时候日志显示build_strategy.cc:170] fusion_group is not enabled for Windows/MacOS now, and only effective when running with CUDA GPU.然后就不训练了。
> 
> 版本、环境信息：
> 1）PaddlePaddle版本：1.8.5
> 2）CPU：RYZEN 5 1600
> 3）GPU：GTX 1050TI 4G
> 4）系统环境：Windows10 1803 教育版
> 环境变量 MKL_DEBUG_CPU_TYPE=5

您好，fusion_group is not enabled for Windows/MacOS now, and only effective when running with CUDA GPU应为一句正常提示，训练中止可能另有原因，可以另提issue问下，会有值班同学回复。

**Comment by licheer111** [comment]
cmd命令行中检查一下自己安装的GPU版本是否正确

**Comment by luotiaotiao** [comment]
有没有人解决这个问题呀？解决的大佬指导一下呗
