### ISSUE TITLE
paddlepaddle-gpu==1.8.5.post107安装报错：“系统无法访问此文件”

### ISSUE THREAD

**Issue by dongyangli-del** [PaddlePaddle/Paddle#28240]
![image](https://user-images.githubusercontent.com/62006079/97106462-bd64c680-16fc-11eb-835e-7e5744a0d80c.png)

    1）PaddlePaddle版本：paddlepaddle-gpu==1.8.5.post107
    4）系统环境：Win10
- 安装方式信息：
1）pip安装
- 问题描述：我用pip安装tensorflow-gpu就可以用，安装paddlepaddle-gpu在命令行引入就报错说系统无法访问此文件，请问这是怎么回事？？

**Comment by zhwesky2010** [comment]
@dongyangli-del 您好，显示python的nltk没有安装好，因为paddle依赖了这个python模块，所以报错，tf没有依赖这个。麻烦在python解释下直接import nltk看下，或者重装下nltk呢

**Comment by dongyangli-del** [comment]
![image](https://user-images.githubusercontent.com/62006079/97706187-38105600-1af0-11eb-9e5c-80b8bef85961.png)
我用pip install 的时候发现已经有这个nltk库了，但是实际import 的时候却仍旧报错：“系统无法访问此文件”

**Comment by zhwesky2010** [comment]
@dongyangli-del 这个应该不是Paddle的问题，是paddle所依赖的python nltk库没有装好，有缺少的Windows操作系统相关DLL。建议 1. 卸载并重装nltk，2.安装https://www.microsoft.com/en-us/download/details.aspx?id=48145 ，可能包含需要的dll。
