### ISSUE TITLE
paddlepaddle中 有类似于clone或者deepcopy的功能的api嘛

### ISSUE THREAD

**Issue by BlackHorseQ** [PaddlePaddle/Paddle#28255]
如题，请问该如何实现deeocopy的功能

**Comment by cryoco** [comment]
您好，可以使用cast（https://www.paddlepaddle.org.cn/documentation/docs/zh/api_cn/layers_cn/cast_cn.html#cast ）
将变量cast为相同的类型，可以实现类似deepcopy的功能
