### ISSUE TITLE
AI Studio训练自动断开

### ISSUE THREAD

**Issue by Monday-Leo** [PaddlePaddle/Paddle#28254]
在AI Studio用算力卡训练模型时，可以正常运行，算力卡充足，一周也没有超过70个小时，训练到五六个小时，就会自动断开，说是长期不活跃，请问这种情况怎么解决，训练过程不就是在等待的过程中，都没有碰电脑。

**Comment by weiexcelpro** [comment]
我是AIStudio的PM. 抱歉带来不便. 
Notebook网页端的设计是这样的, 前端页面和后端服务器, 相互会做心跳检查. 如果前端页面关闭, 或断网, 后端无法检测到前端心跳, 则过一个小时就会自动关闭项目环境. 我这里猜测是电脑进入休眠状态, 后台判断为您已经关机了.

**Comment by weiexcelpro** [comment]
您也可以提供一下项目页面的url, 和发生时间, 我们去确认一下.
