### ISSUE TITLE
未来是否会加入基于int64 Tensor进行索引，进而GetItem和SetItem

### ISSUE THREAD

**Issue by HighCWu** [PaddlePaddle/Paddle#28263]
- 版本、环境信息
1）PaddlePaddle版本：2.0.0 beta
2）CPU/GPU：cuda9.2
3）系统环境：Ubuntu 18.04
- 复现信息：
现在可以做到这样：
`
a = paddle.randn([2,3,3])
a[:1] = 0
`
但无法做到这样，会报错只支持整数和slice进行索引：
`
a[a<0] = 0
`
更复杂的，像是使用meshgrid生成三个维度坐标索引，进行`a[b,c,d] = 0`的操作，其中b、c、d可以是相同shape的int64的Tensor
- 建议描述：我觉得既然加入了索引SetItem的功能，在发布正式版前应该一步到位，实现用Tensor进行索引的功能。我想知道，这项功能是否在计划中。

**Comment by jiweibo** [comment]
非常感谢建议，后续会评估此需求，考虑将其加入发版计划中

**Comment by HighCWu** [comment]
好的，期待你们的进步😁

**Comment by liym27** [comment]
> 非常感谢建议，后续会评估此需求，考虑将其加入发版计划中

@HighCWu
目前仅支持 整数、python slice、[...] 3种情况。因为性能、inplace操作等方面的考虑 ，其他情况目前暂不支持。

另外，setitem 是 inplace 操作，目前在反向梯度计算时具有一定风险：该操作会原地修改该 Tensor 的数值，且原值不会被保存。如果被修改的 Tensor 参与梯度计算，将仅会使用修改后的数值，这可能会给梯度计算引入风险。Paddle 会对具有风险的操作进行检测和报错，该功能会合入正式版。
可查看官方文档：https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/guides/01_paddle2.0_introduction/basic_concept/tensor_introduction_cn.html#id7

之后我们将统一评估需求后在正式版中发布完善的功能。

**Comment by HighCWu** [comment]
> > 非常感谢建议，后续会评估此需求，考虑将其加入发版计划中
> 
> @HighCWu
> 目前仅支持 整数、python slice、[...] 3种情况。因为性能、inplace操作等方面的考虑 ，其他情况目前暂不支持。
> 
> 另外，setitem 是 inplace 操作，目前在反向梯度计算时具有一定风险：该操作会原地修改该 Tensor 的数值，且原值不会被保存。如果被修改的 Tensor 参与梯度计算，将仅会使用修改后的数值，这可能会给梯度计算引入风险。Paddle 会对具有风险的操作进行检测和报错，该功能会合入正式版。
> 可查看官方文档：https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/guides/01_paddle2.0_introduction/basic_concept/tensor_introduction_cn.html#id7
> 
> 之后我们将统一评估需求后在正式版中发布完善的功能。

总之,getitem支持tensor会很棒。事实上，setItem更多是为了便捷的赋初值，还有一些非梯度操作的需求。
或者梯度赋予，给hard计算添加soft的梯度，如将softmax的结果替换为max的结果但依旧使用softmax的反传方式。我还听过将nearest插值结果替换为bilinear，但依旧使用nearest的反传方式来加快训练这样的神奇操作。
虽然我对这些并没有太多了解，不过确实有在很多代码里看到这样的应用。
而setitem使用tensor进行索引赋值，我目前想到的是字典查表时方便存值，若是一张512x512x100的大表，一堆数据进行存取的话，作为整体进行赋值肯定非常费劲，而查的是哪行哪列肯定是计算获得的，不太可能用普通的索引方式索引。
这大概是我想到的更宽泛的应用性。

**Comment by liym27** [comment]
> 总之,getitem支持tensor会很棒。事实上，setItem更多是为了便捷的赋初值，还有一些非梯度操作的需求。
> 或者梯度赋予，给hard计算添加soft的梯度，如将softmax的结果替换为max的结果但依旧使用softmax的反传方式。我还听过将nearest插值结果替换为bilinear，但依旧使用nearest的反传方式来加快训练这样的神奇操作。
> 虽然我对这些并没有太多了解，不过确实有在很多代码里看到这样的应用。
> 而setitem使用tensor进行索引赋值，我目前想到的是字典查表时方便存值，若是一张512x512x100的大表，一堆数据进行存取的话，作为整体进行赋值肯定非常费劲，而查的是哪行哪列肯定是计算获得的，不太可能用普通的索引方式索引。
> 这大概是我想到的更宽泛的应用性。

感谢您关于使用场景上的意见，对我们很有帮助！欢迎随时提出宝贵的建议。

**Comment by HighCWu** [comment]
> > 总之,getitem支持tensor会很棒。事实上，setItem更多是为了便捷的赋初值，还有一些非梯度操作的需求。
> > 或者梯度赋予，给hard计算添加soft的梯度，如将softmax的结果替换为max的结果但依旧使用softmax的反传方式。我还听过将nearest插值结果替换为bilinear，但依旧使用nearest的反传方式来加快训练这样的神奇操作。
> > 虽然我对这些并没有太多了解，不过确实有在很多代码里看到这样的应用。
> > 而setitem使用tensor进行索引赋值，我目前想到的是字典查表时方便存值，若是一张512x512x100的大表，一堆数据进行存取的话，作为整体进行赋值肯定非常费劲，而查的是哪行哪列肯定是计算获得的，不太可能用普通的索引方式索引。
> > 这大概是我想到的更宽泛的应用性。
> 
> 感谢您关于使用场景上的意见，对我们很有帮助！欢迎随时提出宝贵的建议。

确实，如果有使用场景的话应该会更好评估一些，一开始提出issue的时候没想那么多。
之后有任何建议我也会随时提出的😄
