### ISSUE TITLE
linear act参数如果指定leaky_relu  , alpha参数要如何配置？

### ISSUE THREAD

**Issue by habout632** [PaddlePaddle/Paddle#28283]
linear act参数如果指定leaky_relu  , alpha参数要如何配置？

**Comment by zhangting2020** [comment]
- linear层如果指定参数act为leaky_relu，使用的是默认的alpha值，也就是0.02，可以参见官网上leaky_relu的文档说明。
- 如果你不想用0.02这个默认值，可以将linear的act设置为None，linear后再加一个leaky_relu层，去手动调整alpha

**Comment by zhangting2020** [comment]
@habout632 请问上述回复是否解决了你的问题呢？

**Comment by zhangting2020** [comment]
如无问题，issue先关闭，后续如果有新的问题，可以另提issue
