### ISSUE TITLE
请问一下对于一层参数如何直接xavier归一化？

### ISSUE THREAD

**Issue by BlackHorseQ** [PaddlePaddle/Paddle#28282]
比如像这种方式初始化。
for p in self.parameters():
            if p.dim()>1:
                print(p.shape)
                nn.initializer.Xavier(p)
但是似乎p没什么变化。

**Comment by zhangting2020** [comment]
上面的使用方法是错误的：Xavier是一个class，首先你要创建一个Xavier的对象。所以建议代码修改为：
```python
xavier = nn.initializer.Xavier()
for p in self.parameters():
    if p.dim()>1:
        print(p.shape)
        xavier(p)
```

**Comment by zhangting2020** [comment]
@BlackHorseQ 请问提供的方案是否解决了你的问题呢？

**Comment by BlackHorseQ** [comment]
> @BlackHorseQ 请问提供的方案是否解决了你的问题呢？

好像没有，会报错，我看例子都是将这个函数作为参数传给某一一层，没有直接归一化参数的

**Comment by zhangting2020** [comment]
报了什么错呢？
