### ISSUE TITLE
The meaning of Paddle command line flag --test_period is not clear.

### ISSUE THREAD

**Issue by backyes** [PaddlePaddle/Paddle#283]
Paddle 提供了一个命令行参数 [--test_period](http://www.paddlepaddle.org/doc/ui/cmd_argument/detail_introduction.html?highlight=test_period)，但是其意思并不明确：
- How long period(pass) to wait until next testing? 
- How many samples used for one test ?

```
void Tester::testOnePeriod() {
  DataBatch dataBatch;
  int64_t batchSize = config_->getOptConfig().batch_size();
  bool testAllData =
      intconfig_->testPeriod == 0 || intconfig_->testAllDataInOnePeriod;
  int batches =
      testAllData ? std::numeric_limits<int>::max() : intconfig_->testPeriod;

```

Here test_period indicates two meaning:
- batches used for testing
- wait N batches training passed, then do testing.

It's is confusing, and not be correct in doc：
http://www.paddlepaddle.org/doc/ui/cmd_argument/detail_introduction.html?highlight=test_period

related issue：
https://github.com/baidu/Paddle/pull/279
https://github.com/baidu/Paddle/issues/266

@reyoung @emailweixu

**Comment by reyoung** [comment]
the documentation is not good. Add another issue fix docs first.

**Comment by backyes** [comment]
原代码理解起来应该是为了避免在pass未结束前的test做一小部分batch的test，而不是全量的数据。为此混淆了test_period的含义。

solution：
*  我们添加两个变量option, 
--test_batches_while_training, 指示在pass未结束前的test用多少batch test
--test_batches_at_end, 指示在pass结束后的test用多少batch test。

@reyoung @emailweixu @luotao1 @qingqing01  你们的意见呢？

**Comment by reyoung** [comment]
基本同意，尤其是在这个接口没有被广泛使用的时候，赶紧把这个不符合直觉的接口改了。

@其他人 的意见。

**Comment by wangkuiyi** [comment]
从上面的讨论看，貌似大致意思是：paddle提供了一个命令行参数 --test_period，但是其意思并不清晰。如果是这个意思，那么我赞同修改这个接口。但是还有几个问题：

不管是上面英语的comment还是汉语的comment，语文水平都是0分 —— 几乎没有一个句子的主谓宾是全的。这导致读者很难理解讨论者在说什么。更别提提出意见了。

我举几个例子：

> doubt on --test_period meaning.

没有主语。如果加上主语，应该是 I doubt on --test_period meaning. 实际上，即便如此意思也不清楚 —— 一个issue不是抒情散文，不是用来抒发个人感想的，而是一篇议论文，以客观为要。这里可以改成

> The meaning of Paddle command line flag --test_period is not clear.

**Comment by wangkuiyi** [comment]
我之前在几家大互联网公司的工作中都体会到：工程师们对自然语言（语文水平）的重视远不如编程语言。我小时候也是如此。我是受到一些老师们的说法的影响了，比如：

> 学好数理化，走遍天下都不怕

还有

> 数学是一切科学之母

到时同学们更重视数理学科，而语文成了小姑娘抒情的玩意儿，不是理科男应该关注的。

多年之后，我发现这些说法错的都很离谱，甚至混蛋。

我在北京和硅谷的公司里看到了很多“学好了数理化”的聪明人，但是大都被人鄙视成“码农”，甚至自嘲为“码农”。或者说“不知道自己应该干什么，每天等着老板派活儿“。这样一直混到中年，仍然懵懂着，每天能想到的就是为什么今年给我调薪这么少 —— 因为不会出题，只会解题的人，薪水就是会很少。

可是怎么能出题呢？这是一个经验积累的过程。要想经验积累的快，除了自己奋力尝试，还要认真总结，最好还能一伙儿人分享总结。这些”总结“和”分享“的基础，都是语文！

实际上，数学只是对物理现象的一种符号表示，物理是数学之母，而不是反过来。

如果说有一种学科是科学之母，那得是”逻辑学“。按照现代科学（science）的定义，逻辑是形成理论的基础。

历史上，每一个伟大文明的语文教学都是逻辑：

1. 佛教讲究”因明“——说明白原因和结果——这就是逻辑
1. 儒学讲究”策论“——这是被我们鄙视的科举考试的基础，这是奠定了最近一千年中华文明的基础。
1. 古希腊文明的基础是”逻辑“，这是logic这个词的出处。

希望这个项目里的朋友们，仔细想想我说的这个事儿 —— ** 语文是一切科学之母**
