### ISSUE TITLE
fluid.enable_imperative 传入Place报错

### ISSUE THREAD

**Issue by morgan-bc** [PaddlePaddle/Paddle#28305]
fluid.enable_imperative 传入Place报错
- 版本、环境信息：
    1）PaddlePaddle版本：paddlepaddle-gpu==1.8.5.post107
    2）CPU/GPU：GPU
    3）系统环境：win10
    4）Python: 3.7

首次运行 fluid.enable_imperative(fluid.CPUPlace) 或  fluid.enable_imperative(fluid.CUDAPlace) 是报错，错误如下
```
--------------------------------------------
C++ Call Stacks (More useful to developers):
--------------------------------------------
Windows not support stack backtrace yet.

----------------------
Error Message Summary:
----------------------
InvalidArgumentError: Incompatible Place Type: supports CUDAPlace, CPUPlace, and CUDAPinnedPlace, but got Unknown Type! at (D:\1.8.5\paddle\paddle\fluid\pybind\imperative.cc:812)
```
如果第一次报错后在同一运行环境中（如Notebook 和 ipython）再次运行该命令则不会报错。经过在 AIStudio 中试验发现，Linux 下 1.8.4 版本同样会出现这样的问题

**Comment by MrChengmo** [comment]
使用下面的方式使用该API

```python
fluid.dygraph.enable_imperative(fluid.CPUPlace())
```
