### ISSUE TITLE
Whether the OperatorBase needs an initial interface?

### ISSUE THREAD

**Issue by qingqing01** [PaddlePaddle/Paddle#2830]
Now the `OperatorBase` has one default empty constructor. And each operator will be created by calling this empty constructor in [`OpRegistry:: CreateOp()`](https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/framework/op_registry.h#L110).  Where to do the operations which only need to be done once in the operator? For example, we create [an auxiliary object in the RNN operator](https://github.com/PaddlePaddle/Paddle/pull/2775/files#diff-72841cad8b4bc5f442f13cc08c846ee2R103). so, whether the OperatorBase needs an initial interface?

**Comment by Canpio** [comment]
I think we can add a virtual `Init` function which does nothing in `OperatorBase`:
```cpp
virtual void init() {}
```
and overwrite it in any `Op` that need some initialization.

`Op->Init()` could be called in `OpRegistry::CreateOp()` after attribute check.
