### ISSUE TITLE
paddlepaddle不支持3090显卡的新架构

### ISSUE THREAD

**Issue by octaviawfx** [PaddlePaddle/Paddle#28304]
手里一台服务器系统Ubuntu 16.04，CUDA版本10.0，Nvidia驱动版本455.28。
安装了两张显卡Nvidia 2070s，Nvidia 3090。
使用官方给的测试代码“paddle.fluid.install_check.run_check()”，结果使用2070s显卡，paddlepaddle通过测试，而使用3090显卡，运行之后就一直卡住；另外，paddleocr可使用这台服务器的2070s显卡上运行，使用3090显卡也会一直卡住；

**Comment by MrChengmo** [comment]
可以参考这个ISSUE: https://github.com/PaddlePaddle/Paddle/issues/28036, Paddle暂时还没有发布支持CUDA11的新版本，可以自行尝试编译
