### ISSUE TITLE
Load libgomp.so.1 failed

### ISSUE THREAD

**Issue by starsblinking** [PaddlePaddle/Paddle#28315]
import paddle.fluid时出现:

.../anaconda3/lib/python3.8/site-packages/paddle/fluid/core.py:194: UserWarning: Load /opt/compiler/gcc-8.2/lib/libgomp.so.1 failed
  warnings.warn("Load {} failed".format(dso_absolute_path))

但是paddle.fluid.install_check.run_check()一切正常。/opt/compiler/gcc-8.2/lib/libgomp.so.1 -> libgomp.so.1.0.0文件是存在的

请问这个Load libgomp.so.1 failed会对后续训练/预测有影响吗？

- 版本、环境信息：
centos 6u3
python 3.8.3 from Anaconda3-2020.07-Linux-x86_64.sh
paddle 1.8.5 通过pip安装

系统默认的gcc环境我切成了厂内的gcc82:
_#_ ~/.bashrc
export PATH="/opt/compiler/gcc-8.2/bin:$PATH"
export C_INCLUDE_PATH="/opt/compiler/gcc-8.2/include/:/usr/include/:$C_INCLUDE_PATH"
export LIBRARY_PATH="/opt/compiler/gcc-8.2/lib64/:/usr/lib64/:$LIBRARY_PATH"

**Comment by MrChengmo** [comment]
run_check() 检查通过，则正常训练预测没有影响

**Comment by starsblinking** [comment]
多谢。试了一下，暂时没发现单机训练有啥问题。
