### ISSUE TITLE
paddle2.0rc没有更新 fluid.layers.transpose对应的接口

### ISSUE THREAD

**Issue by Darki-luo** [PaddlePaddle/Paddle#28322]
paddle2.0rc版本没有更新对应的transpose更换维度的api接口

**Comment by ForFishes** [comment]
https://www.paddlepaddle.org.cn/documentation/docs/zh/2.0-rc/api/paddle/fluid/layers/transpose_cn.html#transpose
这个接口不对吗？

**Comment by Darki-luo** [comment]
fluid以后不是要弃用了吗？


 
---原始邮件---
发件人: "ShenLiang"<notifications@github.com&gt;
发送时间: 2020年10月30日 19:24:51
收件人: "PaddlePaddle/Paddle"<Paddle@noreply.github.com&gt;;
抄送: "Author"<author@noreply.github.com&gt;;"Darki-luo"<darwon@foxmail.com&gt;;
主题: Re: [PaddlePaddle/Paddle] paddle2.0rc没有更新 fluid.layers.transpose对应的接口 (#28322)




 
https://www.paddlepaddle.org.cn/documentation/docs/zh/2.0-rc/api/paddle/fluid/layers/transpose_cn.html#transpose
 这个接口不对吗？

**Comment by ForFishes** [comment]
https://github.com/PaddlePaddle/Paddle/blob/18c86fb2fb209c0dfcc785c253457cf0ed4790b8/python/paddle/fluid/layers/nn.py#L5449
不是弃用，直接用paddle.transpose,就可以调用，它取了个别名。

**Comment by Darki-luo** [comment]
找到了，paddle API说明文档里没有找到，以为被去掉了


 
---原始邮件---
发件人: "ShenLiang"<notifications@github.com&gt;
发送时间: 2020年10月30日 19:35:53
收件人: "PaddlePaddle/Paddle"<Paddle@noreply.github.com&gt;;
抄送: "Author"<author@noreply.github.com&gt;;"Darki-luo"<darwon@foxmail.com&gt;;
主题: Re: [PaddlePaddle/Paddle] paddle2.0rc没有更新 fluid.layers.transpose对应的接口 (#28322)




 
https://github.com/PaddlePaddle/Paddle/blob/18c86fb2fb209c0dfcc785c253457cf0ed4790b8/python/paddle/fluid/layers/nn.py#L5449
 不是弃用，直接用paddle.transpose,就可以调用，它取了个别名。

**Comment by ForFishes** [comment]
收到，这里属于文档没有描述清楚。后续会对文档进行修复。感谢您的反馈。
