### ISSUE TITLE
3070显卡

### ISSUE THREAD

**Issue by LemonQC** [PaddlePaddle/Paddle#28329]
Windows系统，3070显卡，安装2.0rc，但是一直卡在测试不动，无法调用显卡

**Comment by ForFishes** [comment]
给一下相应的cuda，cudnn等环境？

**Comment by LemonQC** [comment]
> 给一下相应的cuda，cudnn等环境？

cuda10.2，cudnn7.6.5

![Uploading Snipaste_2020-10-30_20-51-41.png…]()

**Comment by LemonQC** [comment]
> 给一下相应的cuda，cudnn等环境？
不好意思，网络不好，重新传一次
![Snipaste_2020-10-30_20-51-41](https://user-images.githubusercontent.com/30914380/97707259-fd0f2200-1af1-11eb-880f-9cc518b29af5.png)

**Comment by ForFishes** [comment]
这边找相关同学看下，稍等。

**Comment by ForFishes** [comment]
您好，3070我们现在不支持这个架构，安装不了，30系列显卡要等CUDA11.

**Comment by zhwesky2010** [comment]
您好，2.0计划支持Cuda11 @ForFishes
