### ISSUE TITLE
2.0-rc0 Adam diff

### ISSUE THREAD

**Issue by starsblinking** [PaddlePaddle/Paddle#28325]
看了下 2.0-rc0 Release Note, 其中提到 “修复Adam优化器计算公式与论文有diff的bug”。想知道下是什么样的diff，能简单说下并给个修复的commit链接吗？我看下要不要从1.8.5升级到2.0rc。
多谢

**Comment by MRXLT** [comment]
你好，这个是修复的PR：https://github.com/PaddlePaddle/Paddle/pull/27778
修复了epsilon的值与原公式不一致的问题，默认情况下epsilon为1e-8，修正后乘上了sqrt(1-beta2)。默认值的情况下这个修正对adam的计算结果影响非常小。

**Comment by starsblinking** [comment]
懂啦，多谢。还有个问题，假设beta2设为0.99999，epsilon为1e-8，那么在未修复的情况下，相当于刚开始训练时epsilon变为了1e-3，这对于那些**出现次数较少的稀疏特征**是不是会有点影响(学习速率变慢)？换言之，如果我使用了paddle.fluid.layers.embedding，那么该lookup_table中不同id对应的beta2_pow_是不是会不一样(即不同id在论文公式中的t是不是不一样)、与出现次数有关（只有样本出现一次该id才会beta2_pow_[id] *= beta2) ?

**Comment by MRXLT** [comment]
> 假设beta2设为0.99999，epsilon为1e-8，那么在未修复的情况下，相当于刚开始训练时epsilon变为了1e-3

这里应该是未修复的情况下是1e-8，修复之后是1e-11
理论上是会减小每一步的梯度变化的值，不过影响非常小


> paddle.fluid.layers.embedding，那么该lookup_table中不同id对应的beta2_pow_是不是会不一样(即不同id在论文公式中的t是不是不一样)、与出现次数有关（只有样本出现一次该id才会beta2_pow_[id] *= beta2) ?

是的

**Comment by starsblinking** [comment]
多谢！
