### ISSUE TITLE
2.0-rc0 分布式稀疏参数

### ISSUE THREAD

**Issue by starsblinking** [PaddlePaddle/Paddle#28327]
看了下 2.0-rc0 Release Note ，其中提到“大规模稀疏功能进行了升级，支持int64范围内的.......”。
这个描述的意思应该是现在非pslib模式也能用吧？貌似之前这个功能从某版本开始就是bug状态，然后也缺乏文档。这不是一个单纯的功能，而是一整套的，所以希望增加文档详细说明下（如果暂不能整理出一套可公开的文档，**强烈希望**在内网wiki写下也行！！！)，重点包括:
a1)保存相关。例如，该多机训练下保存在不同机器的分布式参数文件如何手动聚合成单一词表文件(希望有简单好用的api接口，我看到某个老的issue中讲当时是保存在多个机器上需要手动聚合的， 如果目前的版本中调用save_persistable就已经自动完成聚合到单台机器就更好了)？
a2)保存相关。例如，含大规模稀疏embedding的模型一般都是要外挂查询词表的(比如xbox、xbuiltin或者哪怕std::map)，所以目前paddle保存模型时使用的"__model__"+"prams"文件组成模式感觉是不合适的，"__model__"+"所有非稀疏参数的prams"+"所有稀疏参数的查询词典"；当前或未来的paddle如何支持这种方式？
b)推理相关。如(a)中所述外挂词表的方式，如何读取模型和infer?个人猜想：可以在保存时丢弃data层和embeding层，自己通过外挂词表查询得到embedding作为input送给embeding层后面的层。

强烈希望尽快完善 **非pslib** 下的相关功能，多谢paddle同学！

**Comment by MrChengmo** [comment]
您好~感谢您对Paddle分布式的关注：

- 大规模稀疏文档正在逐渐完善中，目前厂内外Paddle的大规模参数服务器功能在逐步整合，pslib的相关功能也随之开源。

- 2.0rc中的保存支持一键自动保存与聚合

- 2.0rc中的大规模稀疏参数是通过明文词典形式存储在集群中的，可以支持自定义查询

- 目前推理还没有做进一步的工作，欢迎提供您的建议或贡献代码。

如果有更多问题或建议，欢迎如流联系我（程默）

**Comment by seiriosPlus** [comment]
感谢您的关注， 2.0 RC重新优化了大规模稀疏的功能，目前能够支持[0, INT64] 范围内的ID，支持自动增长和增量训练， 加入了特征准入机制及大规模稀疏模型保存功能，支持多个大规模稀疏表并支持多种优化策略， 针对您的问题我做一个简单的回复， 更多的想详情可以联系(程默)。

1. 在带有大规模稀疏的模型中，稠密参数(fc的权重之类)，稀疏参数(非大规模稀疏的稀疏参数)会被0号trainer保存，大规模稀疏参数会分布式保存，每一个pserver均会存下来当前pserver所拥有的稀疏参数，每个稀疏参数都包含了当前节点的(ID, VEC)的键值对，其中ID就是paddle.layers.data输入的原始ID，不再需要聚合到一起， 当前保存下来的格式还是paddle特有的SelectedRows(很遗憾有个保存成明文的接口暂时没有暴露)。  理论上，把参数解析成明文，您有很多种方法完成聚合。

2. 当前考虑到拆分大规模稀疏到其他储存设备是线上预测的常规需求， 在分布式场景下，暂时不把prams合并成一份， 目前保存维持原设计。 后续如果有计划升级，我们会充分考虑的。

3. 你说的没有错， 线上infer一般会对模型进行剪裁， 一方面， 将大规模稀疏的参数存入KV服务， 另外一方面剪裁网络，将data层和embeding层可能还有pooling及concat放到用户端自行运算， 后面的部分才会经过paddle的预测库进行计算。 

4. 从SelecedRows中解析出明文不是很困难，官方有很多事例和教程，如果还是不会操作的话，欢迎留言。

PS: 我们在2.0正式版发布的时候，会有更大的优化和提升， 感谢关注。

**Comment by seiriosPlus** [comment]
原大规模稀疏只支持SGD优化(不管配置了啥，最后都会强行改成SGD)， 当前版本已经能支持任意的优化器了，其中针对常用的SGD/Adam专门做了速度优化。

**Comment by starsblinking** [comment]
好的，您的回复我看懂了，多谢！我后面探索下从SelecedRows中解析出明文看看。

还有一个关键问题，在2.0 RC里面进行增量训练的时候，如何载入已有的模型呢（包括已有模型参数文件的准备和使用api载入参数两部分）？我目前用的1.8.5，
1) 在准备已有模型文件部分的操作是：从hdfs上或者通过其他途径把原来由fleet.save_persistables保存得到的文件夹直接放到**每一台server**下，然后用fleet.init_server(persistables_dir)初始化后接着训练即可。此时我不用考虑上次训练时到底使用了几个节点，反正每个server下都有一份完整的本地参数数据。那么当存在大规模稀疏参数的时候呢？是否要求两次训练时节点一模一样，并且每一台server下存放的那一部分SelecedRows也要与上次训练时一模一样吗？**如果我上次训练时用了80个节点，这次就只能用40个节点（或者反过来）怎么办呢？**
2) 有大规模稀疏参数时载入已有模型用哪个api呢，还是通过fleet.init_server(persistables_dir)吗？
