### ISSUE TITLE
windows10  pip 安装paddlepaddle2.0.0rc0 报错

### ISSUE THREAD

**Issue by uflexnihao** [PaddlePaddle/Paddle#28324]
- 版本、环境信息：
    1）PaddlePaddle版本：2.0.0rc0
    3）GPU：CUDA Version 10.1.243
    4）系统环境：windows10 18363.1139   python3.6
- 安装方式信息：
  1）pip安装

- 复现信息：如为报错，请给出复现环境、复现步骤
在pycharm中选择安装paddlepaddle-gpu 2.0.0rc0，报错信息如下（直接在cmd中，启动venv环境中pip安装，报同样错误）：
Could not find a version that satisfied the requirement  paddlepaddle-gpu 2.0.0rc0 ，后面版本列表中只有2.0.0a0

- 问题描述：请详细描述您的问题，同步贴出报错信息、日志/代码关键片段
【困惑】：
今天对比安装了一下pytorch，安装最新版本1.7.0（https://pytorch.org/ 页面提示中，自动选择的cuda10.2），针对cuda10.2的torch安装成功；   
然后，本机也选择cuda10.2，根据https://www.paddlepaddle.org.cn/  页面的提示安装，报的错误就是前面的错误。
安装针对cuda10.1版的paddlepaddle，则成功。

**Comment by uflexnihao** [comment]
另，此版paddlepaddle在运行时，报的版本｛ CUDA Capability: 52, Driver API Version: 10.2｝，明明装的是cuda10.1版的
********************************************
W1030 16:17:27.004675 11640 device_context.cc:338] Please NOTE: device: 0, CUDA Capability: 52, Driver API Version: 10.2, Runtime API Version: 10.2
W1030 16:17:27.004675 11640 device_context.cc:346] device: 0, cuDNN Version: 7.6.

**Comment by ForFishes** [comment]
感觉这个问题是安装的时候虽然选择了10.2，可能没有生效。实际运行，代码检测环境中的cuda版本，发现是10.2.
怀疑是安装检测的方式和运行检测的方式不一致导致的。

**Comment by ForFishes** [comment]
您好，3070我们现在不支持这个架构，安装不了，30系列显卡要等CUDA11.

**Comment by ForFishes** [comment]
![image](https://user-images.githubusercontent.com/19485646/97709610-95f36c80-1af5-11eb-930c-53b62a5ed054.png)
您好，windows包太大 pip传不上去 不能直接pip install 需要 pip install -f 官网有命令

**Comment by ForFishes** [comment]
![image](https://user-images.githubusercontent.com/19485646/97710785-29796d00-1af7-11eb-96b9-9f6ace5403b7.png)
你这么安装试一下。

**Comment by uflexnihao** [comment]
我就是按照 https://www.paddlepaddle.org.cn 官网自动提示的安装命令安装成功的（cuda选的10.1能成功，10.2失败）（cmd中启动了venv环境后）：
pip install paddlepaddle-gpu==2.0.0rc.post101 -f https://paddlepaddle.org.cn/whl/stable.html

**Comment by DDDivano** [comment]
> 我就是按照 https://www.paddlepaddle.org.cn 官网自动提示的安装命令安装成功的（cuda选的10.1能成功，10.2失败）（cmd中启动了venv环境后）：
> pip install paddlepaddle-gpu==2.0.0rc.post101 -f https://paddlepaddle.org.cn/whl/stable.html

python -m pip install paddlepaddle-gpu==2.0.0rc0   -f https://paddlepaddle.org.cn/whl/stable.html 这么安装试试，10.2版本
