### ISSUE TITLE
paddle安装验证时出现segmentation fault

### ISSUE THREAD

**Issue by Zwette** [PaddlePaddle/Paddle#28321]
环境：
显卡：8张1080ti
系统版本：Ubuntu16.04
cuda：Nvidia-smi 显示的cuda11.0， nvcc -C显示cuda9.0， 但本机上还有个cuda10.2版本的（非默认cuda）
cudnn：7.6.5
反复安装了n次都失败。

Case1: conda 虚拟环境env1(py3.6)下pip安装，先安装了nccl：2.3.7，再run下面的命令
“python -m pip install paddlepaddle-gpu==1.8.4.post97 -i https://pypi.tuna.tsinghua.edu.cn/simple”
安装完成后提示：
![image](https://user-images.githubusercontent.com/41946061/97666772-4e4eef80-1ab9-11eb-9848-6fd764fc54fe.png)

Case2: conda 虚拟环境env2(py3.6)下conda安装
同样的错误，只是segmentation中的PID不一样。

Case3: conda 虚拟环境env2(py3.7)下先安装cudatoolkit=10.1, cudnn=7.6.5, 又下载了一次nccl2.4.7安装，再用pip或者conda 安装paddle。
同样的错误，PID不一样。

**Comment by ForFishes** [comment]
收到，我看一下这个问题。

**Comment by ForFishes** [comment]
是不是因为本地cuda版本太多导致的？

**Comment by Zwette** [comment]
> 是不是因为本地cuda版本太多导致的？

应该不是。因为我能用单张卡能跑，多张卡就有问题，我总觉得是nccl的问题，但是nccl我也是按照官网的command装的，就很奇怪。

**Comment by ForFishes** [comment]
应该是conda环境对Pip不生效的原因，可以用conda安装试一下。
