### ISSUE TITLE
AiStuido 不能使用GPU训练

### ISSUE THREAD

**Issue by cyy53589** [PaddlePaddle/Paddle#28332]
- 版本、环境信息：
    1）PaddlePaddle版本：AIStudio 默认 (1.7)
    2）CPU：AIStudio 默认 
    3）GPU：AIStudio 默认
    4）系统环境：AIStudio 默认
- 训练信息
    1）单机，单卡
    2）显存信息: V100
    3）Operator信息: 没有错误提示，
- 复现信息：在AiStudio 上运行任何GPU代码都不行
- 问题描述：
```python
with fluid.dygraph.guard(place = fluid.CUDAPlace(0)):
    model = DummyDNN()
    dummy_preds = model(dummy_data)
```
![image](https://user-images.githubusercontent.com/19870089/97774484-1a47fd00-1b93-11eb-94bc-0015e6e6ee24.png)

**Comment by weiexcelpro** [comment]
> * 版本、环境信息：
>      1）PaddlePaddle版本：AIStudio 默认 (1.7)
>      2）CPU：AIStudio 默认
>      3）GPU：AIStudio 默认
>      4）系统环境：AIStudio 默认
> * 训练信息
>      1）单机，单卡
>      2）显存信息: V100
>      3）Operator信息: 没有错误提示，
> * 复现信息：在AiStudio 上运行任何GPU代码都不行
> * 问题描述：
> 
> ```python
> with fluid.dygraph.guard(place = fluid.CUDAPlace(0)):
>     model = DummyDNN()
>     dummy_preds = model(dummy_data)
> ```
> 
> ![image](https://user-images.githubusercontent.com/19870089/97774484-1a47fd00-1b93-11eb-94bc-0015e6e6ee24.png)

可否提供一下你遇到问题的项目的网址?

**Comment by cyy53589** [comment]
重启环境解决了
