### ISSUE TITLE
embedding索引超过最大值会报错ExternalError:  Cuda error(719), unspecified launch failure.

### ISSUE THREAD

**Issue by BlackHorseQ** [PaddlePaddle/Paddle#28336]
平台百度aistudio，2.0rc
emb = nn.Embedding(num_embeddings=3, embedding_dim=2, padding_idx=0)
x = paddle.to_tensor(np.array([2,1,3,0]))
emb(x)
ExternalError:  Cuda error(719), unspecified launch failure.
  [Advise: Please search for the error code(719) on website( https://docs.nvidia.com/cuda/archive/10.0/cuda-runtime-api/group__CUDART__TYPES.html#group__CUDART__TYPES_1g3f51e3575c2178246db0a94a430e0038 ) to get Nvidia's official solution about CUDA Error.] (at /paddle/paddle/fluid/platform/gpu_info.cc:291)
[ ]
之后只能重启才继续使用显卡。你们应该去查一下底层，理论应该报错，index 3 is more than 3之类的

**Comment by seiriosPlus** [comment]
收到，我们检查一下这个， 稍后会同步结论.

**Comment by seiriosPlus** [comment]
已经复现了你的结论，我们查证并修复一下。
