### ISSUE TITLE
图像分割方面输入导入出错

### ISSUE THREAD

**Issue by prj-jxust** [PaddlePaddle/Paddle#28334]
```
import numpy as np
from paddle.io import Dataset
patches_imgs_train = np.load('E:/Efficient_DRIVE/patches_imgs_train.npy')
patches_masks_train = np.load('E:/Efficient_DRIVE/patches_masks_train.npy')
class Reader(Dataset):
    def __init__(self):
        super().__init__()
        self.image = patches_imgs_train
        self.label = patches_masks_train
    def __getitem__(self, index):
        img = np.array(self.image[index], dtype="float32")
        label = np.array(self.label[index], dtype="float32")
        return img, label
    def __len__(self):
        return len(self.image)
import paddle as pp
CLASSIFY_NUM = 10
IMAGE_SHAPE_C = 3
IMAGE_SHAPE_H = 30
IMAGE_SHAPE_W = 15
class Net(pp.nn.Layer):
    def __init__(self):
        super().__init__()
        self.layer1 = pp.nn.Conv2D(in_channels=1, out_channels=1, kernel_size=3)
    def forward(self, x):
        layer1 = self.layer1(x)
        return layer1
input_define = pp.static.InputSpec(shape=[-1, 1, 64, 64],
                                   dtype="float32",
                                   name="img")
label_define = pp.static.InputSpec(shape=[-1, 1,64, 64],
                                       dtype="float32",
                                       name="label")
model = pp.Model(Net(), inputs=input_define, labels=label_define)
optimizer = pp.optimizer.Adam(learning_rate=0.001, parameters=model.parameters())

model.prepare(optimizer=optimizer,
                loss=pp.nn.CrossEntropyLoss(),
                metrics=pp.metric.Accuracy())
model.fit(train_data=Reader(),
            batch_size=32,
            epochs=2,
            save_dir="output/",
            save_freq=5,
            log_freq=1000,
            shuffle=True)

print("训练完毕")`
```

报以下错误
```
----------------------
Error Message Summary:
----------------------
InvalidArgumentError: The tensor rank of Input(Label) must be 3.
  [Hint: Expected label_dims.size() == 3, but received label_dims.size():4 != 3:3.] (at D:\2.0.0-rc0\paddle\paddle\fluid\operators\nll_loss_op.cc:71)
  [operator < nll_loss > error]
```

本文数据是存储在npy中的四维数组，分别为【引索，通道数，长，宽】=【1000，1，64，64】

**Comment by prj-jxust** [comment]
`import numpy as np
from paddle.io import Dataset
patches_imgs_train = np.load('E:/Efficient_DRIVE/patches_imgs_train.npy')
patches_masks_train = np.load('E:/Efficient_DRIVE/patches_masks_train.npy')
class Reader(Dataset):
    def __init__(self):
        super().__init__()
        self.image = patches_imgs_train
        self.label = patches_masks_train
    def __getitem__(self, index):
        img = np.array(self.image[index], dtype="float32")
        label = np.array(self.label[index], dtype="float32")
        return img, label
    def __len__(self):
        return len(self.image)
import paddle as pp
CLASSIFY_NUM = 10
IMAGE_SHAPE_C = 3
IMAGE_SHAPE_H = 30
IMAGE_SHAPE_W = 15
class Net(pp.nn.Layer):
    def __init__(self):
        super().__init__()
        self.layer1 = pp.nn.Conv2D(in_channels=1, out_channels=1, kernel_size=3)
    def forward(self, x):
        layer1 = self.layer1(x)
        return layer1
input_define = pp.static.InputSpec(shape=[-1, 1, 64, 64],
                                   dtype="float32",
                                   name="img")
label_define = pp.static.InputSpec(shape=[-1, 1,64, 64],
                                       dtype="float32",
                                       name="label")
model = pp.Model(Net(), inputs=input_define, labels=label_define)
optimizer = pp.optimizer.Adam(learning_rate=0.001, parameters=model.parameters())

model.prepare(optimizer=optimizer,
                loss=pp.nn.CrossEntropyLoss(),
                metrics=pp.metric.Accuracy())
model.fit(train_data=Reader(),
            batch_size=32,
            epochs=2,
            save_dir="output/",
            save_freq=5,
            log_freq=1000,
            shuffle=True)

print("训练完毕")`

**Comment by prj-jxust** [comment]
import numpy as np
from paddle.io import Dataset
patches_imgs_train = np.load('E:/Efficient_DRIVE/patches_imgs_train.npy')
patches_masks_train = np.load('E:/Efficient_DRIVE/patches_masks_train.npy')
class Reader(Dataset):
    def __init__(self):
        super().__init__()
        self.image = patches_imgs_train
        self.label = patches_masks_train
    def __getitem__(self, index):
        img = np.array(self.image[index], dtype="float32")
        label = np.array(self.label[index], dtype="float32")
        return img, label
    def __len__(self):
        return len(self.image)
import paddle as pp
CLASSIFY_NUM = 10
IMAGE_SHAPE_C = 3
IMAGE_SHAPE_H = 30
IMAGE_SHAPE_W = 15
class Net(pp.nn.Layer):
    def __init__(self):
        super().__init__()
        self.layer1 = pp.nn.Conv2D(in_channels=1, out_channels=1, kernel_size=3)
    def forward(self, x):
        layer1 = self.layer1(x)
        return layer1
input_define = pp.static.InputSpec(shape=[-1, 1, 64, 64],
                                   dtype="float32",
                                   name="img")
label_define = pp.static.InputSpec(shape=[-1, 1,64, 64],
                                       dtype="float32",
                                       name="label")
model = pp.Model(Net(), inputs=input_define, labels=label_define)
optimizer = pp.optimizer.Adam(learning_rate=0.001, parameters=model.parameters())

model.prepare(optimizer=optimizer,
                loss=pp.nn.CrossEntropyLoss(),
                metrics=pp.metric.Accuracy())
model.fit(train_data=Reader(),
            batch_size=32,
            epochs=2,
            save_dir="output/",
            save_freq=5,
            log_freq=1000,
            shuffle=True)

print("训练完毕")

**Comment by prj-jxust** [comment]
为什么label的rank必须为3？其实我还是不知道错在哪里

**Comment by LielinJiang** [comment]
这是CrossEntropyLoss的定义，具体可以参考文档：https://www.paddlepaddle.org.cn/documentation/docs/zh/2.0-rc/api/paddle/nn/layer/loss/CrossEntropyLoss_cn.html#id2。
举个简单的例子，比如预测一个像素点属于哪个类别（一共有三个类别0，1，2），这时候你的预测是[n, 3]形状的tensor，第一维是batch size，现在我们假设batch_size = 1，那么你的预测可能是[[0.1, 0.3, 0.6]]，假设这个像素点真实的类别为2，这时候你的label为[2]就行，而不需要是[[0,0,1]]，在我的理解这样其实对用户更友好一些，你不需要对label做一遍label one hot.
