### ISSUE TITLE
Does AnalysisConfig and AnalysisPredictor support loading model from memory?

### ISSUE THREAD

**Issue by flishwang** [PaddlePaddle/Paddle#28338]
As https://github.com/PaddlePaddle/Paddle/pull/22562, https://github.com/PaddlePaddle/Paddle/pull/24099 does,  fluid.io.load_inference_model can load models from memory by setting dirname to None in Python now.

I wonder whether create_paddle_predictor supports this behavior because I cannot find any information in the docs or issues.

If not, is it possible to support loading models from memory as the load_inference_model does?

**Comment by Shixiaowei02** [comment]
@flishwang ，您好，我们计划在 2.0 版本统一这个接口的内存与文件读写功能，统一使用 BytesIO 进行封装。这部分工作预计这个月中旬完成。目前预测模型从内存中加载需要参考 https://github.com/PaddlePaddle/Paddle/pull/24099 中的做法。谢谢
