### ISSUE TITLE
PADDLE_ENFORCE need to enable output of function calling stack

### ISSUE THREAD

**Issue by Superjom** [PaddlePaddle/Paddle#2833]
When debugging program, I get following error:

![image](https://user-images.githubusercontent.com/328693/28146658-16d930ae-67ae-11e7-8b3d-2baaad47ed54.png)

The exception gives a  line number which points to an underlying tool function, but this is no help, what I really want is to find out what the caller function is.

If I replace this line's `PADDLE_ENFORCE` to GLOG's `CHECK`, it works as expected:

![image](https://user-images.githubusercontent.com/328693/28146752-d8ea8d00-67ae-11e7-8597-7b364327b30a.png)

The frame 10's log is what I really want, but an exception can only tell me frame 9 get an error.

So

- whether an exception given by `PADDLE_ENFORCE` can give enough debug info like GLOG's `CHECK'? 
- If no, because debug info is necessary to the developer, can we add a switch into `PADDLE_ENFORCE` macro and switch between exception and CHECK?
- I found that the core codes of TensorFlow used CHECK, but the wrapper use exception, so there must be some principle, not to use exception across the whole project.

**Comment by jacquesqiao** [comment]
应该可以改造成打出stack的

**Comment by Superjom** [comment]
The result of discussion:

- use `NDEBUG` as a switch, switch between `CHECK` and exception.
