### ISSUE TITLE
模型预测，Executor和AnalysisPredictor表现不一致

### ISSUE THREAD

**Issue by flishwang** [PaddlePaddle/Paddle#28337]
Paddle version: 1.8.3
GPU cuda 10.1 / cudnn 7.6
python 3.7

基于paddleDetection yolov3搞的模型，通过tools/export_model.py导出，模型文件如下：
[single_scale.zip](https://github.com/PaddlePaddle/Paddle/files/5470129/single_scale.zip)

根据https://github.com/PaddlePaddle/PaddleDetection/blob/master/deploy/python/infer.py ，
通过fluid.io.load_inference_model 加载模型，可以得到fetch_variables名称为：
save_infer_model/scale_0.tmp_0
save_infer_model/scale_0.tmp_1
预测结果也是正常的。

但通过fluid.core.create_paddle_predictor(config)加载模型，调用predictor.get_output_names()得到的变量为：
bn5a_branch1.output.1.tmp_2
res5c.add.output.5.tmp_1
并不是保存模型时需要的输出变量，进而导致预测出问题。
日志如下：
'''
I1101 10:51:39.630983  4620 analysis_predictor.cc:138] Profiler is deactivated, and no profiling report will be generated.
I1101 10:51:39.647606  4620 analysis_predictor.cc:872] MODEL VERSION: 1.8.3
I1101 10:51:39.647634  4620 analysis_predictor.cc:874] PREDICTOR VERSION: 1.8.3
--- Running analysis [ir_graph_build_pass]
--- Running analysis [ir_graph_clean_pass]
--- Running analysis [ir_analysis_pass]
--- Running IR pass [is_test_pass]
--- Running IR pass [simplify_with_basic_ops_pass]
--- Running IR pass [conv_affine_channel_fuse_pass]
--- Running IR pass [conv_eltwiseadd_affine_channel_fuse_pass]
--- Running IR pass [conv_bn_fuse_pass]
I1101 10:51:39.928872  4620 graph_pattern_detector.cc:101] ---  detected 72 subgraphs
--- Running IR pass [conv_eltwiseadd_bn_fuse_pass]
--- Running IR pass [embedding_eltwise_layernorm_fuse_pass]
--- Running IR pass [multihead_matmul_fuse_pass_v2]
--- Running IR pass [fc_fuse_pass]
--- Running IR pass [fc_elementwise_layernorm_fuse_pass]
--- Running IR pass [conv_elementwise_add_act_fuse_pass]
I1101 10:51:40.292726  4620 graph_pattern_detector.cc:101] ---  detected 32 subgraphs
--- Running IR pass [conv_elementwise_add2_act_fuse_pass]
I1101 10:51:40.307087  4620 graph_pattern_detector.cc:101] ---  detected 16 subgraphs
--- Running IR pass [conv_elementwise_add_fuse_pass]
I1101 10:51:40.314051  4620 graph_pattern_detector.cc:101] ---  detected 30 subgraphs
--- Running IR pass [transpose_flatten_concat_fuse_pass]
--- Running IR pass [runtime_context_cache_pass]
--- Running analysis [ir_params_sync_among_devices_pass]
I1101 10:51:40.323407  4620 ir_params_sync_among_devices_pass.cc:41] Sync params from CPU to GPU
--- Running analysis [adjust_cudnn_workspace_size_pass]
--- Running analysis [inference_op_replace_pass]
--- Running analysis [memory_optimize_pass]
I1101 10:51:40.406996  4620 memory_optimize_pass.cc:223] Cluster name : im_id  size: 8
I1101 10:51:40.407017  4620 memory_optimize_pass.cc:223] Cluster name : cast_0.tmp_0  size: 8
I1101 10:51:40.407021  4620 memory_optimize_pass.cc:223] Cluster name : res5c.add.output.5.tmp_1  size: 8192
I1101 10:51:40.407023  4620 memory_optimize_pass.cc:223] Cluster name : bn5c_branch2b.output.1.tmp_2  size: 2048
I1101 10:51:40.407027  4620 memory_optimize_pass.cc:223] Cluster name : split_1.tmp_1  size: 36
I1101 10:51:40.407029  4620 memory_optimize_pass.cc:223] Cluster name : bn5a_branch1.output.1.tmp_2  size: 8192
I1101 10:51:40.407032  4620 memory_optimize_pass.cc:223] Cluster name : res3d.add.output.5.tmp_1  size: 2048
I1101 10:51:40.407034  4620 memory_optimize_pass.cc:223] Cluster name : res4f.add.output.5.tmp_1  size: 4096
I1101 10:51:40.407037  4620 memory_optimize_pass.cc:223] Cluster name : bn5c_branch2b.output.1.tmp_0  size: 2048
I1101 10:51:40.407039  4620 memory_optimize_pass.cc:223] Cluster name : res5c_branch2b.conv2d.output.1.tmp_0  size: 2048
I1101 10:51:40.407042  4620 memory_optimize_pass.cc:223] Cluster name : im_info_slice_0  size: 4
I1101 10:51:40.407045  4620 memory_optimize_pass.cc:223] Cluster name : im_info  size: 12
I1101 10:51:40.407047  4620 memory_optimize_pass.cc:223] Cluster name : image  size: 12
--- Running analysis [ir_graph_to_program_pass]
I1101 10:51:40.431720  4620 analysis_predictor.cc:493] ======= optimize end =======
I1101 10:51:40.431819  4620 naive_executor.cc:95] ---  skip [feed], feed -> image
I1101 10:51:40.431825  4620 naive_executor.cc:95] ---  skip [feed], feed -> im_info
I1101 10:51:40.431833  4620 naive_executor.cc:95] ---  skip [feed], feed -> im_id
I1101 10:51:40.433290  4620 naive_executor.cc:95] ---  skip [bn5a_branch1.output.1.tmp_2], fetch -> fetch
I1101 10:51:40.433301  4620 naive_executor.cc:95] ---  skip [res5c.add.output.5.tmp_1], fetch -> fetch
W1101 10:51:40.518177  4620 device_context.cc:252] Please NOTE: device: 0, CUDA Capability: 75, Driver API Version: 10.1, Runtime API Version: 10.0
W1101 10:51:40.520723  4620 device_context.cc:260] device: 0, cuDNN Version: 7.6.

'''

**Comment by chenjiaoAngel** [comment]
请问使用的paddle-lite版本是？预测库和头文件有同事更新吗？

**Comment by chenjiaoAngel** [comment]
基于paddleDetection yolov3搞的模型，通过tools/export_model.py导出，模型文件如下：
single_scale.zip这个压缩包里面的模型不全，只有model没有params

**Comment by chenjiaoAngel** [comment]
基于paddleDetection yolov3搞的模型，通过tools/export_model.py导出，模型文件如下：
single_scale.zip这个压缩包里面的模型不全，只有model没有params 请问使用的paddle-lite版本是？预测库和头文件有同事更新吗？

**Comment by chenjiaoAngel** [comment]
请问使用的paddle-lite版本是？预测库和头文件有同步更新吗？

**Comment by flishwang** [comment]
> 基于paddleDetection yolov3搞的模型，通过tools/export_model.py导出，模型文件如下：
> single_scale.zip这个压缩包里面的模型不全，只有model没有params

params文件太大了，所以没有上传。这个bug可能跟特定的模型权重相关吗？我稍后会上传一下权重文件。

没有使用paddle-lite，并且确认环境中未安装paddle-lite的python包。使用的python代码：
```
from paddle import fluid
config=fluid.core.AnalysisConfig(model_path,param_path)
config.enable_use_gpu(3000,0)
config.switch_ir_optim(True)
config.enable_memory_optim()
config.switch_use_feed_fetch_ops(False)
predictor=fluid.core.create_paddle_predictor(config)
```

**Comment by flishwang** [comment]
> 基于paddleDetection yolov3搞的模型，通过tools/export_model.py导出，模型文件如下：
> single_scale.zip这个压缩包里面的模型不全，只有model没有params

https://pan.baidu.com/s/1T9iQQ_d8xPEWcO2AL6x8Fg 提取码ti9a

**Comment by shangzhizhou** [comment]
试下config.switch_ir_optim(False)可以么

**Comment by flishwang** [comment]
> 试下config.switch_ir_optim(False)可以么

刚上传的那个模型跑不起来，显存不够用。

另外定位到AnalysisPredictorl输出变量不太对的原因，跟config.enable_memory_optim()有关。
打开memory_optim，predictor能成功创建，但输出的变量不对。
关闭memory_optim，predictor能成功创建，输出变量也是对的，但实际执行时会报显存不够的错

**Comment by flishwang** [comment]
输出日志中，
```
I1101 10:51:40.431819 4620 naive_executor.cc:95] --- skip [feed], feed -> image
I1101 10:51:40.431825 4620 naive_executor.cc:95] --- skip [feed], feed -> im_info
I1101 10:51:40.431833 4620 naive_executor.cc:95] --- skip [feed], feed -> im_id
I1101 10:51:40.433290 4620 naive_executor.cc:95] --- skip [bn5a_branch1.output.1.tmp_2], fetch -> fetch
I1101 10:51:40.433301 4620 naive_executor.cc:95] --- skip [res5c.add.output.5.tmp_1], fetch -> fetch
```
fetch的变量虽然名字不对，但实际的变量应该是对的。输出结果出错可能是其它的原因。

**Comment by jiweibo** [comment]
> 输出日志中，
> 
> ```
> I1101 10:51:40.431819 4620 naive_executor.cc:95] --- skip [feed], feed -> image
> I1101 10:51:40.431825 4620 naive_executor.cc:95] --- skip [feed], feed -> im_info
> I1101 10:51:40.431833 4620 naive_executor.cc:95] --- skip [feed], feed -> im_id
> I1101 10:51:40.433290 4620 naive_executor.cc:95] --- skip [bn5a_branch1.output.1.tmp_2], fetch -> fetch
> I1101 10:51:40.433301 4620 naive_executor.cc:95] --- skip [res5c.add.output.5.tmp_1], fetch -> fetch
> ```
> 
> fetch的变量虽然名字不对，但实际的变量应该是对的。输出结果出错可能是其它的原因。

开先内存复用，会导致tensor名字对不上，但是结果是没问题的
