### ISSUE TITLE
如何求矩阵内积？

### ISSUE THREAD

**Issue by Vonderland** [PaddlePaddle/Paddle#28342]
目前有paddle.fluid.layers.dot(x, y, name=None)，但是这个只支持1-D的Tensor，如果是batch的情况下，如何比较直接地求内积呢？即[batch_size, dimension]大小的两个矩阵求大小为[batch_size, 1]内积。感谢！

**Comment by QIcaptain** [comment]
使用mutual函数

**Comment by frankwhzhang** [comment]
2.0 可以参考这个页面https://www.paddlepaddle.org.cn/documentation/docs/zh/2.0-rc/guides/01_paddle2.0_introduction/basic_concept/tensor_introduction_cn.html#id8
