### ISSUE TITLE
paddle-trt 加载yolo模型error

### ISSUE THREAD

**Issue by shikeno** [PaddlePaddle/Paddle#28343]
rt
报错信息：
InvalidArgumentError: Input(ImgSize) should be a 2-D tensor.But received Imgsize size(1)
  [Hint: Expected dim_imgsize.size() == 2, but received dim_imgsize.size():1 != 2:2.] (at /home/paddle/paddle/fluid/operators/detection/yolo_box_op.cc:51)
  [operator < yolo_box > error]
Aborted (core dumped)
![image](https://user-images.githubusercontent.com/44427541/97831307-931d9500-1d0a-11eb-9feb-d601b5f38dd8.png)

预测代码：
![image](https://user-images.githubusercontent.com/44427541/97831332-a29cde00-1d0a-11eb-864b-7c7d60b94e9e.png)

应该是代码有问题，想请问下该怎么改

**Comment by frankwhzhang** [comment]
是官方提供的代码吗

**Comment by shikeno** [comment]
> 是官方提供的代码吗

是的

**Comment by shikeno** [comment]
> > 是官方提供的代码吗
> 
> 是的

https://paddle-inference-dist.bj.bcebos.com/tensorrt_test/paddle_inference_sample_v1.7.tar.gz

**Comment by frankwhzhang** [comment]
这是预测相关的问题吗

**Comment by Superjomn** [comment]
是某个具体的 Op，输入应该是二维，现在是1维

如果是官方的代码，是不是模型换了？

**Comment by shikeno** [comment]
> 这是预测相关的问题吗

是呀，在用TensorRT预测

**Comment by chenjiaoAngel** [comment]
请问模型哪个OP的输入是一维的呢？我们这可以看看相应OP是否支持

**Comment by shikeno** [comment]
模型用的是这个
链接: https://pan.baidu.com/s/12hPpx9yUQXgsCENnWq-w6w  密码: 0uu8

**Comment by Superjomn** [comment]
模型换了，那可能输入的维度也对不上了
还是得看你们模型具体的输入维度，得跟代码对上，这个代码得做针对模型的修改

具体是这一行

![image](https://user-images.githubusercontent.com/328693/97859278-5a49e400-1d3b-11eb-9381-e35cd45be479.png)

**Comment by shikeno** [comment]
> 模型换了，那可能输入的维度也对不上了
> 还是得看你们模型具体的输入维度，得跟代码对上，这个代码得做针对模型的修改
> 
> 具体是这一行
> 
> ![image](https://user-images.githubusercontent.com/328693/97859278-5a49e400-1d3b-11eb-9381-e35cd45be479.png)

对对，和原模型少了一个input，加上就好了。多谢！

**Comment by shikeno** [comment]
又有一个问题，跑batch_size = 4 的时候，core dumped 了。
![image](https://user-images.githubusercontent.com/44427541/97867579-13fb8180-1d49-11eb-9836-f52850e09ec0.png)

**Comment by shangzhizhou** [comment]
请问是不是显存不够了呢，batch 超过4都会core么，如果不是，请提供一下完成的测试代码和模型，方便我们复现跟进问题
