### ISSUE TITLE
对paddle中tensor设置的疑问

### ISSUE THREAD

**Issue by lyn1225** [PaddlePaddle/Paddle#28340]
paddle中tensor可以设置成NCHW形式，N代表了batch size。但是在调试的时候发现进入模型中进行处理的实际数据流是（-1,C,H,W）的形式，对于这个-1的设置不是很理解。有时候我是需要N进行处理操作的，但是取到的确是-1。这个该如何解决？

**Comment by QIcaptain** [comment]
-1代表不确定批次，因为一批数据可能不被整除，比如一共有99个数据，batch_size=16,则最后一批数据是3个6*16+3，-1就是为了这种情况发生占位用的，表明一个batch中size可能会发生变化。
