### ISSUE TITLE
`OpProtoAndCheckerMaker` not support indefinite inputs

### ISSUE THREAD

**Issue by Superjom** [PaddlePaddle/Paddle#2835]
Currently, OpProtoAndCheckerMaker has a `AddInput` which adds one input

`AddInput`'s definition is 

```c++
  void AddInput(const std::string& name, const std::string& comment)
```

but in `RecurrentOp`, it can receive an indefinite inputs, for example:

```python
RecurrentOp(x0, x1)
RecurrentOp(x0, x1, x2, x3, x4)
```

It is hard to make a `RecurrentOp`'s definition using this function.

**Comment by jacquesqiao** [comment]
AddInput just add a name of Var, but the data type of var is not configured

**Comment by Superjom** [comment]
The result of discussion:

- a complex input format, but offer a developer-friendly OperatorBase APIs.
