### ISSUE TITLE
2.0rc distributed::RecvLodTensor core

### ISSUE THREAD

**Issue by starsblinking** [PaddlePaddle/Paddle#28356]
0. 首先介绍我原来的环境： paddlepaddle_v1.8.5, PS+CPU, fleet+PaddleCloudRoleMaker, exe.train_from_dataset 正常训练

1. 将1.8.5升级为2.0rc，并补上一句paddle.enable_static()，报如下core:

_--------------------------------------_
C++ Traceback (most recent call last):
_--------------------------------------_
0   ThreadPool::ThreadPool(unsigned long)::{lambda()#1}::operator()() const
1   std::__future_base::_State_base::_M_do_set(std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> ()>&, bool&)
2   std::_Function_handler<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> (), std::__future_base::_Task_setter<std::unique_ptr<std::__future_base::_Result<void>, std::__future_base::_Result_base::_Deleter>, void> >::_M_invoke(std::_Any_data const&)
3   paddle::operators::distributed::ParameterRecv<float>::operator()(paddle::operators::distributed::CommContext const&, paddle::framework::Scope const&, bool)
4   void paddle::operators::distributed::RecvLodTensor<float>(paddle::operators::distributed::CommContext const&, paddle::framework::Scope const&)
5   paddle::framework::LoDTensor const& paddle::framework::Variable::Get<paddle::framework::LoDTensor>() const
6   paddle::framework::SignalHandle(char const*, int)
7   paddle::platform::GetCurrentTraceBackString()

_----------------------_
Error Message Summary:
_----------------------_
FatalError: A serious error (Segmentation fault) is detected by the operating system. (at /paddle/paddle/fluid/platform/init.cc:303)
  [TimeInfo: *** Aborted at 1604318803 (unix time) try "date -d @1604318803" if you are using GNU date ***]
  [SignalInfo: *** SIGSEGV (@0x0) received by PID 223646 (TID 0x7f62fdc3e700) from PID 0 ***]

没其他信息了

2. 将 paddle.fluid.incubate.fleet.parameter_server.distribute_transpiler.distributed_strategy 、paddle.fluid.incubate.fleet.parameter_server.distribute_transpiler.fleet 、 paddle.fluid.incubate.fleet.base.role_maker 换为 paddle.distributed.fleet.DistributedStrategy 、paddle.distributed.fleet 、paddle.distributed.fleet.base.role_maker ， 还是报如上core

模型都没变啊，求解答（难道还是得回1.8苟着么>.<

忆往昔，2.0-beta的Release Note里还写着：“Paddle 2.x版本推荐用户使用位于paddle根目录下的API，同时在paddle.fluid目录下保留了所有的Paddle 1.x版本的API。按照设计，Paddle 1.x版本训练的代码，不做任何修改，即可在Paddle 2.x版本上正常运行；”。

**Comment by starsblinking** [comment]
目前只知道是fleet.init_worker()跑不通

**Comment by frankwhzhang** [comment]
1481295 可以在这个群提问

**Comment by starsblinking** [comment]
问题解决，多谢tangwei！

**Comment by lleesg** [comment]
> 问题解决，多谢tangwei！

could u share  the solution？

**Comment by FD-Liekkas** [comment]
> 问题解决，多谢tangwei！

求解决办法，我也遇到了相同的问题，谢谢了～！

**Comment by starsblinking** [comment]
把init_worker放在exe.run(fluid.default_startup_program())的后面而不是前面
