### ISSUE TITLE
fill_constant_batch_size_like

### ISSUE THREAD

**Issue by starsblinking** [PaddlePaddle/Paddle#28357]
请问1.8中的fill_constant_batch_size_like在2.0里对应哪个api呢？

**Comment by frankwhzhang** [comment]
paddle.full + paddle.shape

**Comment by starsblinking** [comment]
Hi, 你提到的paddle.shape是指有个函数paddle.shape(input)可以实时获取运行时的input的shape吗？我没查到这样的api。
另外，paddle.full定义的静态图要求是不是要求声明的时候就确定好shape呢，可以像fill_constant_batch_size_like一样让shape的第一维为-1吗？
