### ISSUE TITLE
安装错误，官网方式10.1版本后出现You are using GPU version Paddle, but your CUDA device is not set properly.

### ISSUE THREAD

**Issue by mysalter** [PaddlePaddle/Paddle#28360]
- 版本、环境信息：
    1）PaddlePaddle版本：2.0.0rc0
    2）GPU： GPU型号geforce gtx 1060，CUDA Version 10.1.120 
    3）系统环境：windows10、Python3.8.6
- 安装方式信息：
1）pip安装
使用的官网的pip安装命令
python -m pip install paddlepaddle-gpu==2.0.0rc0.post101 -f https://paddlepaddle.org.cn/whl/stable.html

- 问题描述：请详细描述您的问题，同步贴出报错信息、日志/代码关键片段
Python 3.8.6 (tags/v3.8.6:db45529, Sep 23 2020, 15:52:53) [MSC v.1927 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import paddle.fluid as fluid
W1102 23:37:44.784431   516 init.cc:157] Compiled with WITH_GPU, but no GPU found in runtime.
C:\Python38\lib\site-packages\paddle\fluid\framework.py:294: UserWarning: You are using GPU version Paddle, but your CUDA device is not set properly. CPU device will be used by default.
  warnings.warn(
>>> fluid.install_check.run_check()
Running Verify Fluid Program ...
WARNING:root:You are using GPU version Paddle Fluid, But Your CUDA Device is not set properly
 Original Error is

--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
Not support stack backtrace yet.

----------------------
Error Message Summary:
----------------------
ExternalError:  Cuda error(35), CUDA driver version is insufficient for CUDA runtime version.
  [Advise: This indicates that the installed NVIDIA CUDA driver is older than the CUDA runtime library. This is not a supported configuration.Users should install an updated NVIDIA display driver to allow the application to run.] (at D:\2.0.0-rc0\paddle\paddle\fluid\platform\gpu_info.cc:68)

0

我找的网上的资料安装了CUDA也配置了环境变量，电脑里的tensorflow和pytorch的gpu版本能用，不知道哪里有问题不能识别CUDA

**Comment by DDDivano** [comment]
nvcc -V 查看一下显示什么 ， echo %PATH% 看看显示什么？

**Comment by mysalter** [comment]
C:\Users\xiaomililkx>nvcc -V
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2019 NVIDIA Corporation
Built on Sun_Jul_28_19:12:52_Pacific_Daylight_Time_2019
Cuda compilation tools, release 10.1, V10.1.243

C:\Users\xiaomililkx>echo %PATH%
C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.1\bin;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.1\libnvvp;C:\Python38\Scripts\;C:\Python38\;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files\Git\cmd;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\ProgramFiles\NVIDIA GPU ComputingToolkit\CUDA\v10.1\lib\x64;C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR;C:\Program Files\NVIDIA Corporation\Nsight Compute 2019.4.0\;C:\Program Files (x86)\Windows Kits\8.1\Windows Performance Toolkit\;C:\Program Files\CMake\bin;C:\mysoftware\openCV\build\x64\vc15\bin;C:\Users\xiaomililkx\AppData\Local\Microsoft\WindowsApps;C:\Program Files\Bandizip\;C:\Microsoft VS Code\bin

**Comment by mysalter** [comment]
> nvcc -V 查看一下显示什么 ， echo %PATH% 看看显示什么？

C:\Users\xiaomililkx>nvcc -V
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2019 NVIDIA Corporation
Built on Sun_Jul_28_19:12:52_Pacific_Daylight_Time_2019
Cuda compilation tools, release 10.1, V10.1.243

C:\Users\xiaomililkx>echo %PATH%
C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.1\bin;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.1\libnvvp;C:\Python38\Scripts;C:\Python38;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0;C:\Windows\System32\OpenSSH;C:\Program Files\Git\cmd;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\ProgramFiles\NVIDIA GPU ComputingToolkit\CUDA\v10.1\lib\x64;C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR;C:\Program Files\NVIDIA Corporation\Nsight Compute 2019.4.0;C:\Program Files (x86)\Windows Kits\8.1\Windows Performance Toolkit;C:\Program Files\CMake\bin;C:\mysoftware\openCV\build\x64\vc15\bin;C:\Users\xiaomililkx\AppData\Local\Microsoft\WindowsApps;C:\Program Files\Bandizip;C:\Microsoft VS Code\bin

**Comment by zhwesky2010** [comment]
@mysalter 显卡驱动有问题，把显卡驱动装好就可以，Advise: This indicates that the installed NVIDIA CUDA driver is older than the CUDA runtime library. This is not a supported configuration.Users should install an updated NVIDIA display driver to allow the application to run.

**Comment by mysalter** [comment]
多谢，修好了

**Comment by mysalter** [comment]
多谢，修好了

**Comment by MrSworder** [comment]
你好，我在安装好Paddle的条件下，打开python后 import paddle，显示警告“You are using GPU version Paddle, but your CUDA device is not set properly. CPU device will be used by default."我也检查了显卡驱动，已更新到最新。但还是有这个警告，请您帮忙解答疑惑

**Comment by MrSworder** [comment]
我的paddle版本：2.0.0
cuda版本10.1
cudnn版本7.6.5
显卡是 GeForce GTX TITAN X

**Comment by MrSworder** [comment]
显卡是 GeForce GTX TITAN X

**Comment by DDDivano** [comment]
> 我的paddle版本：2.0.0
> cuda版本10.1
> cudnn版本7.6.5
> 显卡是 GeForce GTX TITAN X

PATH是什么

**Comment by majintao1994** [comment]
你好，我也遇到了同样的问题，系统是Ubuntu16.04，padlde2.0.cuda10.1，cudnn7.6.5，cuda测试没问题，请问可以帮忙看看吗
![微信图片_20201208110202](https://user-images.githubusercontent.com/38645277/101453851-ef5b8080-396a-11eb-8625-293622350641.png)
![微信图片_20201208110221](https://user-images.githubusercontent.com/38645277/101453862-f4b8cb00-396a-11eb-9372-0c0caf5b2cab.png)
![cw](https://user-images.githubusercontent.com/38645277/101453871-f8e4e880-396a-11eb-989c-6204f1cc0f2a.png)

**Comment by yiran-THU** [comment]
报告同样的问题，win10，padlde2.0.cuda10.1，cudnn7.6.5，cuda测试没问题

**Comment by jiushinakecai** [comment]
我也遇到了同样的问题， @mysalter 请问你是怎么弄好的？

**Comment by zhwesky2010** [comment]
> 报告同样的问题，win10，padlde2.0.cuda10.1，cudnn7.6.5，cuda测试没问题

CUDA驱动是什么，nvidia-smi看下

**Comment by ZiQiangXie** [comment]
遇到同样的问题，ubuntu16.04，cuda10.0，cudnn7.6.5，显卡驱动版本410.18，安装的paddle版本2.0.2或2.1.0，显卡是2080ti，多卡；
看过其他issue以及网上其他方法，重启过／设置过CUDA_VISILBE_DEVICES/等等都尝试了还是不行；
但是之前在同一个机器上安装过1.8.1版本的没有问题；在使用的其他框架正常使用；
警告信息：
 Compiled with WITH_GPU, but no GPU found in runtime.
You are using GPU version Paddle, but your CUDA device is not set properly. CPU device will be used by default.

nvcc -V输出：
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2018 NVIDIA Corporation
Built on Sat_Aug_25_21:08:01_CDT_2018
Cuda compilation tools, release 10.0, V10.0.130

**Comment by ZiQiangXie** [comment]
遇到同样的问题，ubuntu16.04，cuda10.0，cudnn7.6.5，显卡驱动版本410.18，安装的paddle版本2.0.2或2.1.0，显卡是2080ti，多卡；
看过其他issue以及网上其他方法，重启过／设置过CUDA_VISILBE_DEVICES/等等都尝试了还是不行；
但是之前在同一个机器上安装过1.8.1版本的没有问题；在使用的其他框架正常使用；
警告信息：
 Compiled with WITH_GPU, but no GPU found in runtime.
You are using GPU version Paddle, but your CUDA device is not set properly. CPU device will be used by default.

nvcc -V输出：
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2018 NVIDIA Corporation
Built on Sat_Aug_25_21:08:01_CDT_2018
Cuda compilation tools, release 10.0, V10.0.130

**Comment by LinXin04** [comment]
同样的问题，请问有解决吗？

nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2019 NVIDIA Corporation
Built on Sun_Jul_28_19:07:16_PDT_2019
Cuda compilation tools, release 10.1, V10.1.243

**Comment by UncleLLD** [comment]
请参考这块的安装版本要求： [https://www.paddlepaddle.org.cn/install/quick?docurl=/documentation/docs/zh/install/pip/linux-pip.html](https://www.paddlepaddle.org.cn/install/quick?docurl=/documentation/docs/zh/install/pip/linux-pip.html)

![image](https://user-images.githubusercontent.com/16642335/146504172-29b8cc92-44be-4182-aadd-e60397e65454.png)

**Comment by aleaaaa** [comment]
请问训练的时候遇到过这种问题吗？

OSError: (External)  Cuda error(6), the launch timed out and was terminated.
  [Advise: This indicates that the device kernel took too long to execute. This can only occur if timeouts are enabled - see th
e deviceproperty kernelExecTimeoutEnabled for more information. This leaves the process in an inconsistent state and any further CUDA work will return the same error.To continue using CUDA, the process must be terminated and relaunched.] (at D:\v2.0.1\paddle\paddle\fluid\platform\gpu_info.cc:301)
