### ISSUE TITLE
2.0rc版本如何读取1.8版本的参数

### ISSUE THREAD

**Issue by QIcaptain** [PaddlePaddle/Paddle#28369]
最近在使用2.0rc版本的paddle复现BERT,因为不想自己预训练一次，所以想直接加载官方之前的参数。
请问如何实现

**Comment by yaoxuefeng6** [comment]
你好 直接用之前的API应该是可以的 请问具体遇到了什么问题吗？

**Comment by QIcaptain** [comment]
还没有，先过来确定一下。

**Comment by QIcaptain** [comment]
> 你好 直接用之前的API应该是可以的 请问具体遇到了什么问题吗？
你好。动态图里没有相关读取参数的说明
