### ISSUE TITLE
训练图模型超时/hang住问题

### ISSUE THREAD

**Issue by twoboysbaba** [PaddlePaddle/Paddle#28375]
任务id：job-0bb5f9ebc9adcd49
mpi：http://yq01-hpc-lvliang01-mon.dmop.baidu.com:8919/taskinfo.html?appId=app-user-20201101214829-74840
只要epoch设置超过1就会出超时问题，具体出错日志
W1102 21:14:35.889020  1432 src/brpc/input_messenger.cpp:213] Fail to read from fd=37 SocketId=51539610918@10.182.80.17:8001@52683: Connection reset by peer
E1102 21:14:35.901399  1457 baidu/paddlepaddle/pslib/src/communicate/downpour_ps_client.cc:186] resquest cmd_id:2 failed, err:[E104]Fail to read from fd=37 SocketId=51539610918@10.182.80.17:8001@52683: Connection reset by peer [R1][E111]Fail to connect SocketId=51539611058@10.182.80.17:8001@34310: Connection refused [R2][E112]Not connected to 10.182.80.17:8001 yet [R3][E112]Not connected to 10.182.80.17:8001 yet
E1102 21:14:35.939002  2183 fleet_wrapper.cc:353] fleet pull sparse failed, status[-1]
I1102 21:14:36.001779  1461 src/brpc/socket.cpp:2118] Checking SocketId=2@10.182.80.17:8001

**Comment by yaoxuefeng6** [comment]
可以尝试下在每个epoch开始的时候调一下fleet._role_maker._barrier_worker()，让所有的节点在训练同一个epoch之前同步一下。
