### ISSUE TITLE
Paddle如何配置可学习参数

### ISSUE THREAD

**Issue by costume24** [PaddlePaddle/Paddle#28371]
现在我有两个loss需要做加权，想要将权值配置为两个初始化为1的可学习参数，请问是使用paddle.fluid.layers.create_parameter()这个op就可以吗？如何指定初始化值？

**Comment by yaoxuefeng6** [comment]
你好 是可以的 如果需要进行初始化 可以传入default_initializer指定的initializer，initializer可以参考https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/nn/initializer/constant/Constant_cn.html

**Comment by costume24** [comment]
那么如果我想在训练完成后打印这两个参数的值，应该怎么做呢？是在PDC上训练

**Comment by costume24** [comment]
> 你好 是可以的 如果需要进行初始化 可以传入default_initializer指定的initializer，initializer可以参考https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/nn/initializer/constant/Constant_cn.html

在PDC上训练的话，是不是在配置文件中打开debug就可以打印出所有参数的值了呢？
