### ISSUE TITLE
dataloader报错

### ISSUE THREAD

**Issue by QIcaptain** [PaddlePaddle/Paddle#28385]
paddle2.0rc
ERROR:root:DataLoader reader thread raised an exception!
FatalError: Blocking queue is killed because the data reader raises an exception.
  [Hint: Expected killed_ != true, but received killed_:1 == true:1.] 
代码
data_loader = DataLoader(dataset,
                        batch_size=2,
                        shuffle=True,
                        drop_last=True,
                        num_workers=1)
for i, data in enumerate(data_loader()):
    next_sentence_output, mask_token_output = bertlm(paddle.reshape(data['sentence'], shape=[1, -1]), paddle.reshape(data['segment'], shape=[1, -1]))
    print(data)
    if i>10:
        break

**Comment by QIcaptain** [comment]
dataloader不能返回dict型数据？这有点难受啊

**Comment by yaoxuefeng6** [comment]
dataloader是用可以参考文档哈：https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/io/DataLoader_cn.html#dataloader

**Comment by BlackHorseQ** [comment]
> dataloader是用可以参考文档哈：

什么玩意，这玩意都看过了，我的问题看没看啊，就给我甩出来doc，还有你们觉得自己文档写得非常好嘛？

**Comment by chenxiaozeng** [comment]
您好，dataloader返回的数据类型不是dict，目前可以通过这种方式获取sentence：for batch_id, (sent, label) in enumerate(train_loader()):
