### ISSUE TITLE
paddle 1.8 没有conv1d吗

### ISSUE THREAD

**Issue by Darki-luo** [PaddlePaddle/Paddle#28392]
paddle1.8.x目前没有conv1d的api接口吗？需要用到但是好像没有

**Comment by yaoxuefeng6** [comment]
你好 是有的 https://www.paddlepaddle.org.cn/documentation/docs/zh/api_cn/layers_cn/conv2d_cn.html#conv2d

**Comment by Czeyola** [comment]
这不是conv2d么

**Comment by Darki-luo** [comment]
> 你好 是有的 https://www.paddlepaddle.org.cn/documentation/docs/zh/api_cn/layers_cn/conv2d_cn.html#conv2d

这个是conv2d，怎么实现conv1d3个维度的处理啊？
