### ISSUE TITLE
如何获取X2paddle转的模型的网络结构？

### ISSUE THREAD

**Issue by zhuguiqian** [PaddlePaddle/Paddle#28414]
通过X2paddle将一个onnx模型转成了paddle模型，如果去读取模型的网络结构（例如onnx里的graph)，另外如何获取指定层的weight和bias的值，请教一下，多谢多谢

**Comment by baiyfbupt** [comment]
模型结构可以用visualdl https://github.com/PaddlePaddle/VisualDL 查看，参数weight及bias的值可以通过以下代码这样获取：
```python
param = fluid.global_scope().find_var(param_name)
if param is not None:
    param_in_numpy = np.array(param.get_tensor())
```
param_name为你需要查看的参数名

**Comment by zhuguiqian** [comment]
> 模型结构可以用netron https://github.com/lutzroeder/netron 查看，参数weight及bias的值可以通过以下代码这样获取：
> 
> ```python
> param = fluid.global_scope().find_var(param_name)
> if param is not None:
>     param_in_numpy = np.array(param.get_tensor())
> ```
> 
> param_name为你需要查看的参数名

读取weight和bias的方法可以用，多谢。
查看模型除了netron，请问还有其他接口吗？因为我这边不仅仅需要查看，可能还需要进行截断，将一个模型分成多个子模型，你们有模型截断的例子吗？

**Comment by baiyfbupt** [comment]
目前还不支持

**Comment by zhuguiqian** [comment]
> 目前还不支持

OK，多谢
