### ISSUE TITLE
paddle2.0rc动态图多卡训练问题

### ISSUE THREAD

**Issue by liguoyu666** [PaddlePaddle/Paddle#28418]
单机４卡环境，paddle1.8版本能够多卡训练，换成2.0rc后，模仿动态图的paddleseg改写部分代码，训练自己的模型时，发现不能使用多卡。
`nranks = paddle.distributed.ParallelEnv().nranks

local_rank = paddle.distributed.ParallelEnv().local_rank`
结果为１，０
使用官方文档提供的　[https://fleet-x.readthedocs.io/en/latest/paddle_fleet_rst/fleet_dygraph_quick_start_cn.html](url)下的4.3. 单机多卡训练的demo，能够多卡训练。
请问现在单机多卡训练用文档提供的这种方式吗？

**Comment by danleifeng** [comment]
> 请问现在单机多卡训练用文档提供的这种方式吗？

是的，使用这种方式可以启动单机多卡和多机训练，您可以根据这个demo改写一下。

请问现在还遇到这个问题吗，可以提供下最简单能复现你错误的代码，报错信息等，方便排查。

**Comment by CeciliaPYY** [comment]
上面的链接失效了，可以提供一个有效链接么？

**Comment by CeciliaPYY** [comment]
> > 请问现在单机多卡训练用文档提供的这种方式吗？
> 
> 是的，使用这种方式可以启动单机多卡和多机训练，您可以根据这个demo改写一下。
> 
> 请问现在还遇到这个问题吗，可以提供下最简单能复现你错误的代码，报错信息等，方便排查。

我这边单机两卡也是这样的问题，有没有具体的文档说明啊，从1.8.0过来的，环境变量也设置了为什么每次都还是单卡在使用呢？paddle安装时候的run_check的两卡验证也通过了。

**Comment by danleifeng** [comment]
> 上面的链接失效了，可以提供一个有效链接么？

抱歉，最近fleet的文档正在完善修复中，可以参考下：https://github.com/PaddlePaddle/FleetX/blob/develop/examples/resnet/train_fleet.py#L58
