### ISSUE TITLE
移动端分布式训练

### ISSUE THREAD

**Issue by habout632** [PaddlePaddle/Paddle#28426]
paddle可以支持移动端分布式训练吗　这样子的话，我们就可以使用大量手机，利用手机自带的cpu, gpu(ai 芯片)进行分布式训练，　通过在手机上安装paddle app之后，就可以分布式训练.虽然每部手机的性能赶不上数据中心的gpu, 但是手机量大
运行paddle app的用户　可以按时长收取一点费用

场景：
１．PARL训练需要大量的cpu运行simulator(上万台),gpu(深度学习)
２．普通的学习者，公司可以利用大量手机进行训练，节省成本

**Comment by iclementine** [comment]
这个场景目前分布式还不支持，因为它涉及到训练的稳健性以及数据在多个设备之间共享等问题。但是联邦学习PaddleFL有进行过一些探索。你可以了解一下：

https://github.com/PaddlePaddle/PaddleFL
这个是 README  https://github.com/PaddlePaddle/PaddleFL/blob/master/README_cn.md


另外，分布式训练的弹性调度这一块我们也有做一些工作，EDL了解一下~
https://github.com/elasticdeeplearning/edl
