### ISSUE TITLE
Support variable length input

### ISSUE THREAD

**Issue by jacquesqiao** [PaddlePaddle/Paddle#2842]
### Background
Some Operator needs variable length input, but the current op_proto does not support this feature. So we need to add this.

###  Discuss
- Add an attr such as "is_sequence_input" into op_proto to tell python to set input as List.
the interface of python should be:
```python
fc(input=[x1, x2], y=[y1, y2], ...)
```

- python will put all the list into one list of input, and set the index into op_desc as attr.

**Comment by Superjom** [comment]
Result of a discussion with @reyoung @jacquesqiao @qingqing01 

- variable length input will be stored as a 1-D vector, and mixed in op's `inputs_`(also a 1-D vector)
- use special attributes of Op to specify offsets of a variable length input
- the offsets stored in op's attributes may have different formats, for example:
   - 1-D id list to identify each input's offset of the mutable length input
   - store each id of mutable inputs in adjacent, and just store end offsets in the attribute(will save memory).
- offer OP developer more friendly interfaces to get inputs as follows:
   - if "x" is registered as an input in Op's proto, when writing Op in C++, a developer just need to use `Input("x")` to get `x`'s content.
   - if "xs" is a variable length input, use `Inputs("xs")` to get a 1-D vector.
   - these helper interfaces can help to hide the details of how the framework supports the variable length inputs, and make it more extensible and flexible.
