### ISSUE TITLE
WARNING:root:You are using GPU version Paddle Fluid, But Your CUDA Device is not set properly

### ISSUE THREAD

**Issue by H-Chen110** [PaddlePaddle/Paddle#28428]
- 版本、环境信息：
    1）PaddlePaddle版本：官网Paddle 1.8  PaddleSeg
    2）GPU：2080ti 双卡，CUDA 10.0，CUDNN7.6+
    3）系统环境：ubuntu18.04 
    4）显卡驱动：nvidia 455
- 安装方式信息：conda 安装（官网提供指令）
           

- 问题描述1：安装完成运行后运行paddle.fluid.install_check.run_check()报错
>>> paddle.fluid.install_check.run_check()
Running Verify Fluid Program ... 
WARNING:root:You are using GPU version Paddle Fluid, But Your CUDA Device is not set properly 
Original Error is 

--------------------------------------------
C++ Call Stacks (More useful to developers):
--------------------------------------------
0   std::string paddle::platform::GetTraceBackString<char const*>(char const*&&, char const*, int)
1   paddle::platform::EnforceNotMet::EnforceNotMet(std::__exception_ptr::exception_ptr, char const*, int)
2   paddle::platform::GetCUDADeviceCount()

----------------------
Error Message Summary:
----------------------
ExternalError:  Cuda error(30), unknown error.
  [Advise: This indicates that an unknown internal error has occurred. ] at (/paddle/paddle/fluid/platform/gpu_info.cc:65)

- 问题描述2：运行PaddleSeg/pdseg/train.py 报错

#运行双gpu，先使用单卡测试
%set_env CUDA_VISIBLE_DEVICES=0
!python pdseg/train.py --use_gpu --cfg ./deeplabv3p_resnet50_vd_cityscapes.yaml
############################报错信息############################33
File "pdseg/train.py", line 454, in main
    train(cfg)
  File "pdseg/train.py", line 222, in train
    place = fluid.CUDAPlace(gpu_id) if args.use_gpu else fluid.CPUPlace()
paddle.fluid.core_avx.EnforceNotMet: 

--------------------------------------------
C++ Call Stacks (More useful to developers):
--------------------------------------------
0   std::string paddle::platform::GetTraceBackString<char const*>(char const*&&, char const*, int)
1   paddle::platform::EnforceNotMet::EnforceNotMet(std::__exception_ptr::exception_ptr, char const*, int)
2   paddle::platform::GetCUDADeviceCount()

----------------------
Error Message Summary:
----------------------
ExternalError:  Cuda error(30), unknown error.
  [Advise: This indicates that an unknown internal error has occurred. ] at (/paddle/paddle/fluid/platform/gpu_info.cc:65)

**Comment by iclementine** [comment]
看起来是环境配置的问题，可以先尝试查看以下的方面：

1. conda 环境下是否安装了正确版本的 cudatoolkit;
2. 环境中的 cublas cuda cudnn 等的版本是否能搭配。

**Comment by iclementine** [comment]
经过我们这边的试验，在显卡被占用的情况下，或者 CUDA_VISIBLE_DEVICES 环境变量为空之类的时候，也会得到错误。
![图片](https://user-images.githubusercontent.com/16222986/98642822-03f72980-2369-11eb-8502-075e917529c3.png)

你可以截图给我看看 Original Error 是什么？

**Comment by H-Chen110** [comment]
![Uploading image.png…]()

**Comment by H-Chen110** [comment]
![05f78b2f94c3eaecfae8e041a0abe36](https://user-images.githubusercontent.com/54975621/98677882-a7136780-2398-11eb-8b60-6cc5258401ec.png)
Original Error 是空白的，并无任何内容，cudatoolkit版本：10.0，cudnn：7.6.5。
还有一个疑问是，我在网上查找能查询cuda版本的命令，显示的版本不一样，不清楚以哪个版本为确。如下：
1.使用cat /usr/local/cuda/version.txt命令，显示cuda版本10.0
![1](https://user-images.githubusercontent.com/54975621/98678295-4a647c80-2399-11eb-87c6-d9727fbb2f8a.png)
2.使用nvcc -V 命令，显示cuda版本9.1
![2](https://user-images.githubusercontent.com/54975621/98678306-4f293080-2399-11eb-8ceb-661bf945f88f.png)
感谢您的解答！！

**Comment by H-Chen110** [comment]
经本人在其他框架上的测试，发现也无法识别cuda信息，所以可以确定是电脑安装cuda等出现的问题。
谢谢各位开发小哥哥的耐心解答！！
