### ISSUE TITLE
reduce_sum使用错误

### ISSUE THREAD

**Issue by xiaomujiang** [PaddlePaddle/Paddle#28437]
使用reduce报错：
    output = exe.run(feed={"input",x},fetch_list=[result])
TypeError: unhashable type: 'numpy.ndarray'

测试代码：
import paddle.fluid as fluid
import numpy as np
# y 是一个shape为[2, 2, 2]的Tensor元素如下:
#      [[[1, 2], [3, 4]],
#      [[5, 6], [7, 8]]]
# 接下来的示例中，我们在每处函数调用后面都标注出了它的结果张量。
data = fluid.data(name='input', shape=[2, 2, 2], dtype='float32')
result = fluid.layers.reduce_sum(data, dim=[2]) # [10, 26]
place = fluid.CPUPlace()
exe = fluid.Executor(place)
exe.run(fluid.default_startup_program())
a = [1, 2] ; b = [3, 4]; c = [5, 6];d=[7,8]
x = np.array([[a,b],[c,d]])
print(x,x.shape,data.shape,result.shape)
output = exe.run(feed={"input",x},fetch_list=[result])
print(output)

**Comment by iclementine** [comment]
这个是调用代码的问题了。
feed={"input",x} 你的意思是  feed={"input": x} 吧。
ndarray 是 Unhashable 的，因此也不能用作字典的 key.
