### ISSUE TITLE
Ubuntu1604编译paddle到extern_crytopp就不动了

### ISSUE THREAD

**Issue by nhsy0105** [PaddlePaddle/Paddle#28438]
- 版本、环境信息：
    1）PaddlePaddle版本：paddle-2.0.0_rc和beta都试过，都是一样的情况
    2）CPU：40 Intel(R) Xeon(R) CPU E5-2630 v4 @ 2.20GHz
    3）GPU:  NVIDIA TESLA P40
    4）系统环境：UBUNTU16.04、Python版本2.7.12

- 安装方式信息：本地编译：
![image](https://user-images.githubusercontent.com/30465953/98205955-08d86980-1f74-11eb-8ac1-070094d0f79d.png)

![image](https://user-images.githubusercontent.com/30465953/98205991-168def00-1f74-11eb-81b7-4ef14ccb2d1f.png)

**Comment by nhsy0105** [comment]
大佬们帮忙看看啊。。。

**Comment by iclementine** [comment]
能看出是 failed 在哪个 target 吗？
可以用 make 不带 -j 看看具体是哪个 target 出错。

**Comment by nhsy0105** [comment]
![image](https://user-images.githubusercontent.com/30465953/98516713-cda5a580-22a7-11eb-88a7-f591737f5a96.png)

**Comment by nhsy0105** [comment]
![捕获2](https://user-images.githubusercontent.com/30465953/98517528-042ff000-22a9-11eb-990f-e3958f27ebb1.JPG)

**Comment by nhsy0105** [comment]
@iclementine 请帮忙看看，多谢啦

**Comment by iclementine** [comment]
看来是 gflags 安装失败。

可以先看看 extern_gflags-install-*.log 有什么线索。
以及，要不试试删除 build 下的 third party 目录再试一次？

**Comment by iclementine** [comment]
之前曾经编译成功过吗？

**Comment by tianshuo78520a** [comment]
请问gcc版本是多少，建议不要本地编译，可以使用官网提供的docker环境编译。本地环境差异比较大，不容易排查原因。

**Comment by zhangcj13** [comment]
你好，我也遇到同样问题，就卡在这build extern_crytopp不动了 @nhsy0105 ，后来在ubuntu16.04下编译成功了么，有解决方案么？
