### ISSUE TITLE
本地训练报错如下

### ISSUE THREAD

**Issue by AWSWXY** [PaddlePaddle/Paddle#28447]
----------------------
Error Message Summary:
----------------------
Error: Blocking queue is killed because the data reader raises an exception
  [Hint: Expected killed_ != true, but received killed_:1 == true:1.] at (/paddle/paddle/fluid/operators/reader/blocking_queue.h:141)
  [operator < read > error]
I1105 17:01:01.587981  3369 communicator.cc:1102] communicator stopped, send thread exit
terminate called after throwing an instance of 'std::system_error'
  what():  Invalid argument
W1105 17:01:01.588717  1859 init.cc:209] Warning: PaddlePaddle catches a failure signal, it may not work properly
W1105 17:01:01.588735  1859 init.cc:211] You could check whether you killed PaddlePaddle thread/process accidentally or report the case to PaddlePaddle
W1105 17:01:01.588747  1859 init.cc:214] The detail failure signal is:

W1105 17:01:01.588757  1859 init.cc:217] *** Aborted at 1604566861 (unix time) try "date -d @1604566861" if you are using GNU date ***
W1105 17:01:01.590524  1859 init.cc:217] PC: @                0x0 (unknown)
W1105 17:01:01.590600  1859 init.cc:217] *** SIGABRT (@0x20700000743) received by PID 1859 (TID 0x7fa5ca501700) from PID 1859; stack trace: ***
W1105 17:01:01.591900  1859 init.cc:217]     @     0x7fa5ca0d8160 (unknown)
W1105 17:01:01.593241  1859 init.cc:217]     @     0x7fa5c96463f7 __GI_raise
W1105 17:01:01.594547  1859 init.cc:217]     @     0x7fa5c96477d8 __GI_abort
W1105 17:01:01.595672  1859 init.cc:217]     @     0x7fa5b14a6c65 __gnu_cxx::__verbose_terminate_handler()
W1105 17:01:01.596700  1859 init.cc:217]     @     0x7fa5b14a4e06 __cxxabiv1::__terminate()
W1105 17:01:01.597745  1859 init.cc:217]     @     0x7fa5b14a3ec9 __cxa_call_terminate
W1105 17:01:01.598801  1859 init.cc:217]     @     0x7fa5b14a4a7a __gxx_personality_v0
W1105 17:01:01.599805  1859 init.cc:217]     @     0x7fa5bbb53853 _Unwind_RaiseException_Phase2
W1105 17:01:01.600817  1859 init.cc:217]     @     0x7fa5bbb53beb _Unwind_RaiseException
W1105 17:01:01.601871  1859 init.cc:217]     @     0x7fa5b14a5045 __cxa_throw
W1105 17:01:01.602944  1859 init.cc:217]     @     0x7fa5b14f6640 std::__throw_system_error()
W1105 17:01:01.604030  1859 init.cc:217]     @     0x7fa5b14f7688 std::thread::join()
W1105 17:01:01.605553  1859 init.cc:217]     @     0x7fa5a59290d5 paddle::operators::distributed::HalfAsyncCommunicator::~HalfAsyncCommunicator()
W1105 17:01:01.607146  1859 init.cc:217]     @     0x7fa5a59292e1 paddle::operators::distributed::SyncCommunicator::~SyncCommunicator()
W1105 17:01:01.608569  1859 init.cc:217]     @     0x7fa5a5929311 paddle::operators::distributed::SyncCommunicator::~SyncCommunicator()
W1105 17:01:01.610038  1859 init.cc:217]     @     0x7fa5a551c2e9 std::_Sp_counted_base<>::_M_release()
W1105 17:01:01.611311  1859 init.cc:217]     @     0x7fa5c9648eb9 __run_exit_handlers
W1105 17:01:01.612617  1859 init.cc:217]     @     0x7fa5c9648f05 __GI_exit
W1105 17:01:01.613931  1859 init.cc:217]     @     0x7fa5c9632bdc __libc_start_main
W1105 17:01:01.614128  1859 init.cc:217]     @           0x414b71 (unknown)
W1105 17:01:01.615367  1859 init.cc:217]     @                0x0 (unknown)

**Comment by iclementine** [comment]
从报错信息上来看是 DataLoader 报错了。
请问你用的 paddle 版本是？使用动态图还是静态图？是否使用 DataLoader? 
可以先 debug 一下 DataLoader, 确保它能够正常使用，正常迭代。
