### ISSUE TITLE
paddlepaddle删除embedding层参数文件，再加载模型文件失败？

### ISSUE THREAD

**Issue by Jarlonyan** [PaddlePaddle/Paddle#2844]
我们的问题是： 将paddle训练得到的模型文件中的embedding层的参数文件删除，再用paddle.parameters加载剩余层的参数文件，结果是加载不了。为什么？怎么可以实现加载？

**Comment by typhoonzero** [comment]
现在是不支持直接删除层然后加载的。考虑如果这个是一个通用的需求，可以增加。
看下是否和下面这个issue类似呢？如果是要减小embedding层参数提高加载速度考虑可以裁剪下embedding层： 

Related: https://github.com/PaddlePaddle/Paddle/issues/2812

**Comment by dzhwinter** [comment]
> 将paddle训练得到的模型文件中的embedding层的参数文件删除

调用init_from_tar加载参数文件。替换可以构造一个fake emebedding dict，注意name和embedding dim相同。

**Comment by typhoonzero** [comment]
@dzhwinter @Jarlonyan 不太确定这样的接口是否会比较通用，比如：

```python
parameters.from_tar(skip_layers=["__embedding_1__"])
```

**Comment by Jarlonyan** [comment]
@typhoonzero, parameters.from_tar的参数列表没有skip_layers，只有('f', 'params', 'tar', 'finfo', 'conf', 'param_name')

**Comment by dzhwinter** [comment]
从模型加载的skip_layers正在开发中

**Comment by qingqing01** [comment]
可以参考这个issue：https://github.com/PaddlePaddle/Paddle/issues/2663 。`init_from_tar`可以满足~

**Comment by Jarlonyan** [comment]
@qingqing01 , init_from_tar不是我想要的。因为这个init_from_tar还是调用了 from_tar这个函数，它会将所有的层的参数都加载进去，然后我需要哪些部分层的参数，它就给我返回。但问题是，我压根就不想用from_tar加载所有层的参数，因为embedding层参数太大，加载会太慢。

`python
tar_param = Parameters.from_tar(f)
for pname in tar_param.names():
    if pname in self.names():
         self.set(pname, tar_param.get(pname))
`

**Comment by dzhwinter** [comment]
[demo for skip layer](https://github.com/PaddlePaddle/models/pull/164)

**Comment by typhoonzero** [comment]
@Jarlonyan @qingqing01 提供的方法中，可以先解压输出的模型tar包，并删除期望不加载的参数文件，然后重新打包，再调用`init_from_tar` 即可满足。

**Comment by Jarlonyan** [comment]
@typhoonzero ，我的版本是v2版，升级过。但是源码中并没有 `init_from_tar ` 这个接口。

**Comment by typhoonzero** [comment]
这个功能是18天前merge的，需要更新到最近的版本才行。

**Comment by qingqing01** [comment]
@Jarlonyan   用`init_from_tar`可以有两种方式满足要求：

1. 如 @typhoonzero 所讲: 

> 可以先解压输出的模型tar包，并删除期望不加载的参数文件，然后重新打包，再调用init_from_tar 即可满足。

2. 如果**不想** `解压输出的模型tar包，并删除期望不加载的参数文件，然后重新打包`，可以更改配置embedding层的参数名字，例如：

例如原始配置为：

```
    data = paddle.layer.data("word",
                paddle.data_type.integer_value_sequence(dict_dim))
    emb = paddle.layer.embedding(input=data, size=emb_dim)

    # ... 省略中间配置
    out_layer = xxx  #输出层
``

可以更改为：

```
    data = paddle.layer.data("word",
                paddle.data_type.integer_value_sequence(100)) #假如这里更改了词典大小
    emb = paddle.layer.embedding(input=data, size=emb_dim,
                param_attr=paddle.attr.Param(name='emb'))  #这里改成了参数名字为`emb`

    # ... 省略中间配置
    out_layer = xxx  # 输出层
```

然后`init_from_tar`用法：

```
    parameters = paddle.parameters.create(out_layer)
    with gzip.open('models/dnn_params_pass_00000.tar.gz') as f:
      parameters.init_from_tar(f)

    # 如果还想用其他参数初始化embedding层，可以用`set`函数：
    small = np.random.rand(100, 28) # 100是词典大小，28是embedding维度
    parameters.set('emb', small)  # emb是embedding参数名字
```

**Comment by dzhwinter** [comment]
maybe we can add this script demo to embedding demo?  
@Canpio

**Comment by typhoonzero** [comment]
Currently `init_from_tar` can cover most of the cases: https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/v2/parameters.py#L371

Closing this issue for now, feel free to reoopen it.
