### ISSUE TITLE
模型预测速度在两台机器上不一致

### ISSUE THREAD

**Issue by zhangyimi** [PaddlePaddle/Paddle#28443]
版本：paddle1.8.2 动态图
想问下影响模型预测速度的因素有哪些？
训练了两个不同结构模型a和b，batch为1 cpu模式下，第一台机器上a模型比b快近一倍，第二台机器速度却相同。
![image](https://user-images.githubusercontent.com/20926735/98213541-2c091600-1f80-11eb-84cd-6a7d6f0b749b.png)

**Comment by iclementine** [comment]
影响的因素可能有：
1. 机器的配置；
2. 机器的繁忙程度；
3. 运行时环境哦，各种库的版本。

**Comment by zhangyimi** [comment]
问题已经解决，发现同一台机器不同gcc版本编译的python对模型预测速度有显著影响。
