### ISSUE TITLE
CPU上mkldnn加载多个模型预测问题

### ISSUE THREAD

**Issue by luotao1** [PaddlePaddle/Paddle#28459]
根据外部用户的反馈，实测发现，使用CPU mkldnn加载多个模型预测时，会导致模型预测结果有diff的问题。

复现环境： Ubuntu 16.04 paddlepaddle==2.0.0rc0

复现问题的模型和代码已上传在此icafe中（3个模型均为MobileNetv2分类模型)

问题复现情况：
[test.tar.gz](https://github.com/PaddlePaddle/Paddle/files/5498977/test.tar.gz)

解压上传的附件后，进入目录

1. 执行 python merge_test.py 1 会同时加载3个模型，并分别预测同一个输入数据，结果如下：

====1 5 0.81950974 5.0102745e-22 0.16666667

====xx 3 0.94060355 6.0438254e-09 0.16666667

====3 4 0.6412412 8.9865025e-20 0.16666667

分别表示模型"1", 模型"xx"和模型"3"的输出

2. 执行python merge_test.py 0 只会加载模型"xx"进行预测，结果如下：

====xx 2 0.7462423 6.9529786e-33 0.16666667

两者存在明显的差异，预测label发生了变化。而在修改merge_test.py，将use_gpu设为True之后，再重新测试，则两个预测结果没有变化。或者将MKLDNN关闭，即去掉`config.enable_mkldnn()`这句，也是正常的。

**Comment by jczaja** [comment]
@luotao1 Candidate fix to issue is here: https://github.com/PaddlePaddle/Paddle/pull/28758 . could you please test it and let us know if issue is gone?
