### ISSUE TITLE
多线程预测问题

### ISSUE THREAD

**Issue by wwjjy** [PaddlePaddle/Paddle#28451]
为使您的问题得到快速解决，在建立Issue前，请您先通过如下方式搜索是否有相似问题:【搜索issue关键字】【使用labels筛选】【官方文档】

求问一下python端想要 多线程的加载多个同结构、同变量名但是参数不同的模型进行预测，应该如何正确的加载并使用，求一个例子~

**Comment by iclementine** [comment]
详细说一下你的需求？
你是要用 inference model 的方式进行预测？

**Comment by wwjjy** [comment]
@iclementine 模型是save_inference_model保存的，这些模型有相同的结构，同时每一层的命名也相同，但是在不同的数据集上进行训练的，所以实际加载进来的参数是不同的。现在就需要在不同的线程里，使用不同的模型进行预测

**Comment by iclementine** [comment]
既然参数是不同的，是否可以用多个进程进行预测？
推荐到预测用户群咨询。2260150
