### ISSUE TITLE
安装paddle

### ISSUE THREAD

**Issue by yinggangtian** [PaddlePaddle/Paddle#28476]
欢迎您对PaddlePaddle提出建议，非常感谢您对PaddlePaddle的贡献！
在留下您的建议时，辛苦您同步提供如下信息：
- 版本、环境信息
1）PaddlePaddle版本：1.8
2）CPU/GPU：CPU
3）系统环境：ubuntu20.04   python3.8
建议;
适配ubuntu20.04的安装环境

**Comment by lfchener** [comment]
已收到您的反馈，我们会尽快讨论，结论将会第一时间同步在这里。

**Comment by swtkiwi** [comment]
您这个问题可能是因为我们在1.8.5以上才支持python3.8，辛苦安装1.8.5

**Comment by swtkiwi** [comment]
我们大概会在近期3个迭代中增加对此需求的支持，感谢您的建议
