### ISSUE TITLE
训练时候报错

### ISSUE THREAD

**Issue by Darki-luo** [PaddlePaddle/Paddle#28473]
不是一开始就出现这个报错，而是会在训练几轮后随机出现报错中止，在aistudio中多卡训练也是某几张卡报错中止，其他卡可以正常训练
File "train.py", line 194, in main
    train_loss.backward()
  File "<decorator-gen-76>", line 2, in backward
  File "/opt/_internal/cpython-3.7.0/lib/python3.7/site-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
    return wrapped_func(*args, **kwargs)
  File "/opt/_internal/cpython-3.7.0/lib/python3.7/site-packages/paddle/fluid/framework.py", line 216, in __impl__
    return func(*args, **kwargs)
  File "/opt/_internal/cpython-3.7.0/lib/python3.7/site-packages/paddle/fluid/dygraph/varbase_patch_methods.py", line 121, in backward
    framework._dygraph_tracer(), retain_graph)
paddle.fluid.core_avx.EnforceNotMet: 

--------------------------------------------
C++ Call Stacks (More useful to developers):
--------------------------------------------
0   std::string paddle::platform::GetTraceBackString<char const*>(char const*&&, char const*, int)
1   paddle::platform::EnforceNotMet::EnforceNotMet(std::__exception_ptr::exception_ptr, char const*, int)
2   paddle::operators::CUDNNConvGradOpKernel<float>::Compute(paddle::framework::ExecutionContext const&) const
3   std::_Function_handler<void (paddle::framework::ExecutionContext const&), paddle::framework::OpKernelRegistrarFunctor<paddle::platform::CUDAPlace, false, 0ul, paddle::operators::CUDNNConvGradOpKernel<float>, paddle::operators::CUDNNConvGradOpKernel<double>, paddle::operators::CUDNNConvGradOpKernel<paddle::platform::float16> >::operator()(char const*, char const*, int) const::{lambda(paddle::framework::ExecutionContext const&)#1}>::_M_invoke(std::_Any_data const&, paddle::framework::ExecutionContext const&)
4   paddle::imperative::PreparedOp::Run(paddle::imperative::NameVariableWrapperMap const&, paddle::imperative::NameVariableWrapperMap const&, paddle::framework::AttributeMap const&)
5   paddle::imperative::OpBase::Run(paddle::framework::OperatorBase const&, paddle::imperative::NameVariableWrapperMap const&, paddle::imperative::NameVariableWrapperMap const&, paddle::framework::AttributeMap const&, paddle::platform::Place const&)
6   paddle::imperative::BasicEngine::Execute()

----------------------
Error Message Summary:
----------------------
ExternalError:  Cudnn error, CUDNN_STATUS_EXECUTION_FAILED  at (/paddle/paddle/fluid/operators/conv_cudnn_op.cu:625)

terminate called after throwing an instance of 'paddle::platform::EnforceNotMet'
  what():  

--------------------------------------------
C++ Call Stacks (More useful to developers):
--------------------------------------------
0   std::string paddle::platform::GetTraceBackString<char const*>(char const*&&, char const*, int)
1   paddle::platform::EnforceNotMet::EnforceNotMet(std::__exception_ptr::exception_ptr, char const*, int)
2   paddle::platform::stream::CUDAStream::Wait() const
3   paddle::platform::stream::CUDAStream::Destroy()
4   paddle::platform::stream::CUDAStream::~CUDAStream()
5   paddle::platform::CUDAContext::~CUDAContext()
6   std::_Sp_counted_ptr<paddle::platform::CUDAContext*, (__gnu_cxx::_Lock_policy)2>::_M_dispose()
7   std::_Sp_counted_base<(__gnu_cxx::_Lock_policy)2>::_M_release()
8   paddle::platform::CUDADeviceContext::~CUDADeviceContext()
9   paddle::platform::CUDADeviceContext::~CUDADeviceContext()
10  paddle::platform::NCCLCommImpl::~NCCLCommImpl()
11  paddle::platform::NCCLCommContext::ReleaseNCCLComms()

----------------------
Error Message Summary:
----------------------
ExternalError:  Cuda error(77), an illegal memory access was encountered.
  [Advise: The device encountered a load or store instruction on an invalid memory address. This leaves the process in an inconsistentstate and any further CUDA work will return the same error. To continue using CUDA, the process must be terminated and relaunched. ] at (/paddle/paddle/fluid/platform/stream/cuda_stream.cc:65)

W1108 20:25:22.972716   564 init.cc:226] Warning: PaddlePaddle catches a failure signal, it may not work properly
W1108 20:25:22.972744   564 init.cc:228] You could check whether you killed PaddlePaddle thread/process accidentally or report the case to PaddlePaddle
W1108 20:25:22.972748   564 init.cc:231] The detail failure signal is:

W1108 20:25:22.972770   564 init.cc:234] *** Aborted at 1604838322 (unix time) try "date -d @1604838322" if you are using GNU date ***
W1108 20:25:22.974328   564 init.cc:234] PC: @                0x0 (unknown)
W1108 20:25:22.974391   564 init.cc:234] *** SIGABRT (@0x234) received by PID 564 (TID 0x7fa2703f6700) from PID 564; stack trace: ***
W1108 20:25:22.975423   564 init.cc:234]     @     0x7fa26f875020 (unknown)
W1108 20:25:22.976475   564 init.cc:234]     @     0x7fa26ebebf69 __GI_raise
W1108 20:25:22.977478   564 init.cc:234]     @     0x7fa26ebed38a __GI_abort
W1108 20:25:22.978354   564 init.cc:234]     @     0x7fa25c3e5c65 __gnu_cxx::__verbose_terminate_handler()
W1108 20:25:22.979151   564 init.cc:234]     @     0x7fa25c3e3e06 __cxxabiv1::__terminate()
W1108 20:25:22.979907   564 init.cc:234]     @     0x7fa25c3e2ec9 __cxa_call_terminate
W1108 20:25:22.980679   564 init.cc:234]     @     0x7fa25c3e3a7a __gxx_personality_v0
W1108 20:25:22.981433   564 init.cc:234]     @     0x7fa25c8b7383 (unknown)
W1108 20:25:22.982177   564 init.cc:234]     @     0x7fa25c8b7457 _Unwind_Resume
W1108 20:25:22.983953   564 init.cc:234]     @     0x7fa21c6c5825 paddle::platform::stream::CUDAStream::Destroy()
W1108 20:25:22.985940   564 init.cc:234]     @     0x7fa21930fed7 paddle::platform::stream::CUDAStream::~CUDAStream()
W1108 20:25:22.988555   564 init.cc:234]     @     0x7fa219308528 paddle::platform::CUDAContext::~CUDAContext()
W1108 20:25:22.990183   564 init.cc:234]     @     0x7fa2193100aa std::_Sp_counted_ptr<>::_M_dispose()
W1108 20:25:22.991598   564 init.cc:234]     @     0x7fa218f195c9 std::_Sp_counted_base<>::_M_release()
W1108 20:25:22.992811   564 init.cc:234]     @     0x7fa21930749f paddle::platform::CUDADeviceContext::~CUDADeviceContext()
W1108 20:25:22.996287   564 init.cc:234]     @     0x7fa219307681 paddle::platform::CUDADeviceContext::~CUDADeviceContext()
W1108 20:25:22.997964   564 init.cc:234]     @     0x7fa21c0bda99 paddle::platform::NCCLCommImpl::~NCCLCommImpl()
W1108 20:25:22.999450   564 init.cc:234]     @     0x7fa21c0bb907 paddle::platform::NCCLCommContext::ReleaseNCCLComms()
W1108 20:25:23.000577   564 init.cc:234]     @     0x7fa26ebee829 __run_exit_handlers
W1108 20:25:23.001734   564 init.cc:234]     @     0x7fa26ebee875 __GI_exit
W1108 20:25:23.002836   564 init.cc:234]     @     0x7fa26ebd8b4c __libc_start_main
W1108 20:25:23.002882   564 init.cc:234]     @           0x4006c1 (unknown)
W1108 20:25:24.186699   563 init.cc:226] Warning: PaddlePaddle catches a failure signal, it may not work properly
W1108 20:25:24.186754   563 init.cc:228] You could check whether you killed PaddlePaddle thread/process accidentally or report the case to PaddlePaddle
W1108 20:25:24.186759   563 init.cc:231] The detail failure signal is:

W1108 20:25:24.186764   563 init.cc:234] *** Aborted at 1604838324 (unix time) try "date -d @1604838324" if you are using GNU date ***
ERROR 2020-11-08 20:25:24,186 utils.py:419] ABORT!!! Out of all 8 trainers, the trainer process with rank=[1] was aborted. Please check its log.
W1108 20:25:24.188431   563 init.cc:234] PC: @                0x0 (unknown)
W1108 20:25:24.188701   563 init.cc:234] *** SIGTERM (@0x13c) received by PID 563 (TID 0x7f86ec774700) from PID 316; stack trace: ***

**Comment by LDOUBLEV** [comment]
麻烦提供下你的环境，包括：
1. paddle版本、cudnn版本、cuda版本

AIstudio上只有一个GPU吧，可以多卡训练吗

**Comment by Darki-luo** [comment]
> 麻烦提供下你的环境，包括：
> 
> 1. paddle版本、cudnn版本、cuda版本  paddle1.8.5 cudnn 7.6.5 cuda 10.0
> 
> AIstudio上只有一个GPU吧，可以多卡训练吗 
AIstudio 脚本后台任务 8卡任务，遇到过2张卡在训练时出现上述报错，上面报错的内容就是aistuidio上输出的内容。

**Comment by LDOUBLEV** [comment]
可以稳定复现吗？能否提供下复现环境
