### ISSUE TITLE
shm被逐渐占满的问题

### ISSUE THREAD

**Issue by ctkindle** [PaddlePaddle/Paddle#28474]
ai studio paddle2.0rc（beta也是同样状况） gpu 

使用Dataloader读取数据时，shm会被逐渐占满，直至报错。

num_worker=0时，按文档说明不启用子进程。但是，我在Dataset的__getitme__（）里打印标记时发现，还是打印了多次（有时是6次）。num_wroker=1时，打印3ci。这是怎么回事，进程数量不是依据num_worker而定么？

**Comment by LDOUBLEV** [comment]
shm会被逐渐占满的问题，将use_shared_memory设置为False，或者在启动docker时，把共享内存设置大一点；


num_wroker=1时，打印3次的问题，是不是你的batch_size设置的大于1

**Comment by ctkindle** [comment]
谢谢，已经好了。
