### ISSUE TITLE
## 内部测试paddle bot 功能，值班请忽略##

### ISSUE THREAD

**Issue by dingjiaweiww** [PaddlePaddle/Paddle#28471]
为使您的问题得到快速解决，在建立Issue前，请您先通过如下方式搜索是否有相似问题:【搜索issue关键字】【使用labels筛选】【官方文档】

求问一下python端想要 多线程的加载多个同结构、同变量名但是参数不同的模型进行预测，应该如何正确的加载并使用，求一个例子~

**Comment by lelelelelez** [comment]
测试

**Comment by dingjiaweiww** [comment]
test

**Comment by dingjiaweiww** [comment]
testtest

**Comment by dingjiaweiww** [comment]
test10086

**Comment by dingjiaweiww** [comment]
TEST
