### ISSUE TITLE
paddle动态图中如何使用LSTM呢？

### ISSUE THREAD

**Issue by wkzqn** [PaddlePaddle/Paddle#28487]
可以像keras那样堆叠多个LSTM层吗？我看paddle的lstm可以选择有多个层，然后大多数人都使用的dynamic_lstm这个接口，但是dynamic_lstm只能使用一个LSTM层？看了官方的LSTM API感觉还是不会用LSTM，有没有人能够帮助我一下？

**Comment by lfchener** [comment]
可以使用 LSTM API：https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/nn/layer/rnn/LSTM_cn.html#lstm
其中 num_layers 参数可以指定 LSTM 的层数。
![image](https://user-images.githubusercontent.com/6771821/98536635-0c952480-22c3-11eb-9f97-69b393bf7281.png)
