### ISSUE TITLE
Warning: PaddlePaddle catches a failure signal, it may not work properly

### ISSUE THREAD

**Issue by 631961895** [PaddlePaddle/Paddle#28491]
为使您的问题得到快速解决，在建立Issues前，请您先通过如下方式搜索是否有相似问题:【搜索issue关键字】【使用labels筛选】【官方文档】

如果您没有查询到相似问题，为快速解决您的提问，建立issue时请提供如下细节信息：
- 标题：简洁、精准概括您的问题
- 版本、环境信息：
    1）PaddlePaddle版本：
       paddle-serving-app        0.1.2
       paddle-serving-client     0.3.2
       paddle-serving-server-gpu 0.3.2.post10 
       paddlepaddle              1.8.5
    2）CPU/GPU：NVIDIA-SMI 430.40       Driver Version: 430.40       CUDA Version: 10.1 cudnn 7.6
    3）系统环境：ubuntu 16.04
    4）Python版本号 3.6.10
    5）显存信息
 注：您可以通过执行[summary_env.py](https://github.com/PaddlePaddle/Paddle/blob/develop/tools/summary_env.py)获取以上信息。
- 复现信息：多线程，多请求
- 问题描述：

*** Check failure stack trace: ***
W1109 14:13:19.165050  3432 init.cc:226] Warning: PaddlePaddle catches a failure signal, it may not work properly
W1109 14:13:19.165206  3432 init.cc:228] You could check whether you killed PaddlePaddle thread/process accidentally or report the case to PaddlePaddle
W1109 14:13:19.165244  3432 init.cc:231] The detail failure signal is:

W1109 14:13:19.165268  3432 init.cc:234] *** Aborted at 1604902399 (unix time) try "date -d @1604902399" if you are using GNU date ***
W1109 14:13:19.173751  3432 init.cc:234] PC: @                0x0 (unknown)
W1109 14:13:19.175218  3432 init.cc:234] *** SIGABRT (@0x3ee00000b64) received by PID 2916 (TID 0x7fdc957fd700) from PID 2916; stack trace: ***
W1109 14:13:19.180501  3432 init.cc:234]     @     0x7fde4b978fd0 (unknown)
W1109 14:13:19.184645  3432 init.cc:234]     @     0x7fde4b978f47 gsignal
W1109 14:13:19.187784  3432 init.cc:234]     @     0x7fde4b97a8b1 abort
W1109 14:13:19.188179  3432 init.cc:234]     @     0x7fdd78ec8bb9 google::logging_fail()
W1109 14:13:19.188958  3432 init.cc:234]     @     0x7fdd78eca86d google::LogMessage::Fail()
W1109 14:13:19.189558  3432 init.cc:234]     @     0x7fdd78ece31c google::LogMessage::SendToLog()
W1109 14:13:19.190533  3432 init.cc:234]     @     0x7fdd78eca393 google::LogMessage::Flush()
W1109 14:13:19.191032  3432 init.cc:234]     @     0x7fdd78ecf82e google::LogMessageFatal::~LogMessageFatal()
W1109 14:13:19.191762  3432 init.cc:234]     @     0x7fdd78f926f7 baidu::paddle_serving::sdk_cpp::StubImpl<>::initialize()
W1109 14:13:19.192704  3432 init.cc:234]     @     0x7fdd78ef2708 baidu::paddle_serving::sdk_cpp::Variant::initialize()
W1109 14:13:19.193222  3432 init.cc:234]     @     0x7fdd78ef1817 baidu::paddle_serving::sdk_cpp::Endpoint::initialize()
W1109 14:13:19.193624  3432 init.cc:234]     @     0x7fdd78ef84bd baidu::paddle_serving::sdk_cpp::PredictorApi::create()
W1109 14:13:19.194011  3432 init.cc:234]     @     0x7fdd78ebe534 _ZZN8pybind1112cpp_function10initializeIZN5baidu14paddle_serving13general_modelL28pybind11_init_serving_clientERNS_6moduleEEUlRNS4_15PredictorClientERKSsE8_vIS8_SA_EINS_4nameENS_9is_methodENS_7siblingEEEEvOT_PFT0_DpT1_EDpRKT2_ENUlRNS_6detail13function_callEE1_4_FUNESS_.49864
W1109 14:13:19.194411  3432 init.cc:234]     @     0x7fdd78e9edb2 pybind11::cpp_function::dispatcher()
W1109 14:13:19.194532  3432 init.cc:234]     @           0x566ddc _PyCFunction_FastCallDict
W1109 14:13:19.194645  3432 init.cc:234]     @           0x50a783 (unknown)
W1109 14:13:19.194749  3432 init.cc:234]     @           0x50c1f4 _PyEval_EvalFrameDefault
W1109 14:13:19.194857  3432 init.cc:234]     @           0x507f24 (unknown)
W1109 14:13:19.194962  3432 init.cc:234]     @           0x509c50 (unknown)
W1109 14:13:19.195066  3432 init.cc:234]     @           0x50a64d (unknown)
W1109 14:13:19.195168  3432 init.cc:234]     @           0x50c1f4 _PyEval_EvalFrameDefault
W1109 14:13:19.195271  3432 init.cc:234]     @           0x509918 (unknown)
W1109 14:13:19.195377  3432 init.cc:234]     @           0x50a64d (unknown)
W1109 14:13:19.195478  3432 init.cc:234]     @           0x50c1f4 _PyEval_EvalFrameDefault
W1109 14:13:19.195580  3432 init.cc:234]     @           0x507f24 (unknown)
W1109 14:13:19.195647  3432 init.cc:234]     @           0x509202 _PyFunction_FastCallDict
W1109 14:13:19.195760  3432 init.cc:234]     @           0x594b01 (unknown)
W1109 14:13:19.195868  3432 init.cc:234]     @           0x54a17f (unknown)
W1109 14:13:19.195973  3432 init.cc:234]     @           0x5517c1 (unknown)
W1109 14:13:19.196074  3432 init.cc:234]     @           0x5a9eec _PyObject_FastCallKeywords
W1109 14:13:19.196180  3432 init.cc:234]     @           0x50a783 (unknown)
W1109 14:13:19.196280  3432 init.cc:234]     @           0x50c1f4 _PyEval_EvalFrameDefault

**Comment by lfchener** [comment]
请移步 paddle Serving repo 下提 issue
https://github.com/PaddlePaddle/Serving/issues
