### ISSUE TITLE
We only support 'data()' in static graph mode.......

### ISSUE THREAD

**Issue by python-bookworm** [PaddlePaddle/Paddle#28493]
在运行训练程序时候，报错：
AssertionError: We only support 'data()' in static graph mode, please call 'paddle.enable_static()' to enter static graph mode
按照#27495问题的方案，并没有解决问题，运行 主机环境：ubuntu18.04,cuda10.0,cudnn7.5,paddlepaddle-gpu==2.0
请教下是什么问题导致报错?

**Comment by lfchener** [comment]
paddle 2.0-rc  以后默认开启动态图模式，您的模型如果是使用静态图实现的话，请在代码前显示调用 ``paddle.enable_static()`` 开启静态图模式，再运行。

**Comment by python-bookworm** [comment]
> paddle 2.0-rc 以后默认开启动态图模式，您的模型如果是使用静态图实现的话，请在代码前显示调用 `paddle.enable_static()` 开启静态图模式，再运行。

好的，已经加了静态开启的模式，可以正常运行，谢谢。

**Comment by smartmark-pro** [comment]
@lfchener  我遇到了类似的报错, 我是用来调用bertservice的, 使用的命令是
``` bash
hub serving start bert_service -m roberta_wwm_ext_chinese_L-24_H-1024_A-16--use_gpu --gpu 0 --port 8866
```
环境信息

- paddlehub 1.8.3
- paddlepaddle-gpu       2.0.0rc0.post101

如果当前无法使用, 切换低于2.0版本的paddlepaddle-gpu就行了么

**Comment by smartmark-pro** [comment]
> @lfchener 我遇到了类似的报错, 我是用来调用bertservice的, 使用的命令是
> 
> ```shell
> hub serving start bert_service -m roberta_wwm_ext_chinese_L-24_H-1024_A-16--use_gpu --gpu 0 --port 8866
> ```
> 
> 环境信息
> 
> * paddlehub 1.8.3
> * paddlepaddle-gpu       2.0.0rc0.post101
> 
> 如果当前无法使用, 切换低于2.0版本的paddlepaddle-gpu就行了么

换低版本没什么问题, 不考虑该问题了
