### ISSUE TITLE
Unable to minimize the CTC training error on large sequences (>1000 timesteps)

### ISSUE THREAD

**Issue by F0REacH** [PaddlePaddle/Paddle#285]
I've tried to compare warp-ctc torch7 bindings with Paddle CTC -> [test repo see logs](https://github.com/F0REacH/ctc-demo) 
Warp-ctc torch implementation - works just fine. 
Paddle with the same data and the same network structure can't successfully minimize the training error.

I am unable to isolate the problem by changing hyperparameters, network type/size, optim. functions, switching between CPU/GPU. 
It seems the only solution that works is to truncate sequences to ~500 timesteps.

**Any possible solutions/suggestions how to make this work with large varying length sequences (3000-5000 timesteps each)?**

Using latest master as:

> cmake -DWITH_GPU=ON -DWITH_DOC=OFF -DCMAKE_INSTALL_PREFIX=/opt/paddle ..

**Comment by wangkuiyi** [comment]
@F0REacH This is a very interesting comparison! Thank you for publishing the experiment in a Github repo. We really appreciate your comparison as we see it a great chance to make Paddle better.

Can you please also let us know how to re-run your experiments and some numbers that we are expected to reproduce?  For example, could you please add an README.md in your [repo](https://github.com/F0REacH/ctc-demo).  We'd be happy to try to reproduce the comparison so could we have more clue on making Paddle better.

**Comment by F0REacH** [comment]
Added README.md with installation/execution instructions.

**Comment by qingqing01** [comment]
@F0REacH Thanks for your feedback. I will reproduce this problem and give you a solution soon.

**Comment by qingqing01** [comment]
@F0REacH The argument `norm_by_times` in cc_layer is `False` by default. You can set it `True`. I'm not sure this argument is True or False in torch. You can set it `True` to try again.

**Comment by F0REacH** [comment]
Ok @qingqing01 I've tested it for 20 minutes with the norm_by_times=True option. Seems like the problem persists. I'll try to test it more with different learning rates etc.

**Comment by qingqing01** [comment]
@F0REacH  Maybe there is something wrong with your data processing. The sample number is always 1 in the logs, like 
https://raw.githubusercontent.com/F0REacH/ctc-demo/master/ctc-paddle-demo/train_lr0.0001_cpu_single_01csv_file_full_length.log

Is there any data introduction link?

**Comment by F0REacH** [comment]
@qingqing01 Well, as I understand, sample number is always 1, because I'm using just one sample: 1 batch with 1 sample and this sample contains 3967 timesteps and each timestep is a vector of size 24. I've tried to load bigger batches with more samples, - got the same problem as before. Anyway, thanks for the hint - I'll test data section more thoroughly.

**Comment by F0REacH** [comment]
Same problem with more simple data sample: [generated.csv](https://github.com/F0REacH/ctc-demo/blob/master/resources/generated.csv).

**Comment by F0REacH** [comment]
@qingqing01 OK I've ran some tests with different data samples and found out, that seems like this problem is not caused by sequence length, but rather by some specific data/configuration combination. I've added [working](https://github.com/F0REacH/ctc-demo/blob/master/resources/working.csv) and [failing](https://github.com/F0REacH/ctc-demo/blob/master/resources/failing.csv) data samples and logs, see [commit](https://github.com/F0REacH/ctc-demo/commit/57ad84d0570d29594ddb89de0cd8520db12d2e65). Main points of interest are lines \# 95-96 in [failing.csv](https://github.com/F0REacH/ctc-demo/blob/master/resources/failing.csv) when I use only first 95 lines of this file - everything works, but full version - fails.
