### ISSUE TITLE
error met when running ppyolo in TX2 

### ISSUE THREAD

**Issue by lleesg** [PaddlePaddle/Paddle#28505]
**ENV：**
TX2、Ubuntu18.04、CUDA10.2、python3.6、Paddle-release-2.0-beta(on TX2, though it shows it's "PREDICTOR VERSION: 0.0.0" below...)

**problem description：**
I successfully run YOLOv3 model correctly on TX2 with both TRT on and  off, but errors occured when run PPYOLO:

- error info when TRT off :

W1110 10:14:23.840741 15941 analysis_predictor.cc:578] The one-time configuration of analysis predictor failed, which may be due to native predictor called first and its configurations taken effect.
I1110 10:14:23.840863 15941 analysis_predictor.cc:139] Profiler is deactivated, and no profiling report will be generated.
I1110 10:14:23.905185 15941 op_compatible_info.cc:203] The default operator required version is missing. Please update the model version.
I1110 10:14:23.905287 15941 analysis_predictor.cc:952] MODEL VERSION: 2.0.0
I1110 10:14:23.905313 15941 analysis_predictor.cc:954] PREDICTOR VERSION: 0.0.0
W1110 10:14:23.905586 15941 analysis_predictor.cc:967]  - Version incompatible (1) assign_value
W1110 10:14:23.905628 15941 analysis_predictor.cc:967]  - Version incompatible (1) batch_norm
W1110 10:14:23.905649 15941 analysis_predictor.cc:967]  - Version incompatible (1) clip
W1110 10:14:23.905668 15941 analysis_predictor.cc:967]  - Version incompatible (1) concat
W1110 10:14:23.905686 15941 analysis_predictor.cc:967]  - Version incompatible (1) conv2d
W1110 10:14:23.905705 15941 analysis_predictor.cc:967]  - Version incompatible (1) deformable_conv
W1110 10:14:23.905722 15941 analysis_predictor.cc:967]  - Version incompatible (1) elementwise_add
W1110 10:14:23.905740 15941 analysis_predictor.cc:967]  - Version incompatible (1) elementwise_div
W1110 10:14:23.905758 15941 analysis_predictor.cc:967]  - Version incompatible (1) elementwise_mul
W1110 10:14:23.905777 15941 analysis_predictor.cc:967]  - Version incompatible (1) feed
W1110 10:14:23.905795 15941 analysis_predictor.cc:967]  - Version incompatible (1) fetch
W1110 10:14:23.905813 15941 analysis_predictor.cc:967]  - Version incompatible (1) fill_constant
W1110 10:14:23.905833 15941 analysis_predictor.cc:967]  - Version incompatible (1) leaky_relu
W1110 10:14:23.905851 15941 analysis_predictor.cc:967]  - Version incompatible (1) log
W1110 10:14:23.905869 15941 analysis_predictor.cc:967]  - Version incompatible (1) matrix_nms
W1110 10:14:23.905887 15941 analysis_predictor.cc:967]  - Version incompatible (1) nearest_interp
W1110 10:14:23.905905 15941 analysis_predictor.cc:967]  - Version incompatible (1) pool2d
W1110 10:14:23.905922 15941 analysis_predictor.cc:967]  - Version incompatible (1) pow
W1110 10:14:23.905939 15941 analysis_predictor.cc:967]  - Version incompatible (1) relu
W1110 10:14:23.905956 15941 analysis_predictor.cc:967]  - Version incompatible (1) scale
W1110 10:14:23.905974 15941 analysis_predictor.cc:967]  - Version incompatible (1) sigmoid
W1110 10:14:23.905992 15941 analysis_predictor.cc:967]  - Version incompatible (1) slice
W1110 10:14:23.906008 15941 analysis_predictor.cc:967]  - Version incompatible (1) split
W1110 10:14:23.906034 15941 analysis_predictor.cc:967]  - Version incompatible (1) transpose2
W1110 10:14:23.906069 15941 analysis_predictor.cc:967]  - Version incompatible (1) yolo_box
W1110 10:14:23.906091 15941 analysis_predictor.cc:195] WARNING: Results may be DIFF! Please use the corresponding version of the model and prediction library, and do not use the develop branch.
--- Running analysis [ir_graph_build_pass]
--- Running analysis [ir_graph_clean_pass]
--- Running analysis [ir_analysis_pass]
--- Running IR pass [is_test_pass]
--- Running IR pass [simplify_with_basic_ops_pass]
--- Running IR pass [conv_affine_channel_fuse_pass]
--- Running IR pass [conv_eltwiseadd_affine_channel_fuse_pass]
--- Running IR pass [conv_bn_fuse_pass]
I1110 10:14:24.605396 15941 graph_pattern_detector.cc:100] ---  detected 73 subgraphs
--- Running IR pass [conv_eltwiseadd_bn_fuse_pass]
--- Running IR pass [embedding_eltwise_layernorm_fuse_pass]
--- Running IR pass [multihead_matmul_fuse_pass_v2]
--- Running IR pass [fc_fuse_pass]
--- Running IR pass [fc_elementwise_layernorm_fuse_pass]
--- Running IR pass [conv_elementwise_add_act_fuse_pass]
I1110 10:14:24.837189 15941 graph_pattern_detector.cc:100] ---  detected 32 subgraphs
--- Running IR pass [conv_elementwise_add2_act_fuse_pass]
I1110 10:14:24.882223 15941 graph_pattern_detector.cc:100] ---  detected 16 subgraphs
--- Running IR pass [conv_elementwise_add_fuse_pass]
I1110 10:14:24.905661 15941 graph_pattern_detector.cc:100] ---  detected 31 subgraphs
--- Running IR pass [transpose_flatten_concat_fuse_pass]
--- Running IR pass [runtime_context_cache_pass]
--- Running analysis [ir_params_sync_among_devices_pass]
I1110 10:14:24.973222 15941 ir_params_sync_among_devices_pass.cc:41] Sync params from CPU to GPU
--- Running analysis [adjust_cudnn_workspace_size_pass]
--- Running analysis [inference_op_replace_pass]
--- Running analysis [memory_optimize_pass]
I1110 10:14:25.903678 15941 memory_optimize_pass.cc:223] Cluster name : im_size  size: 8
I1110 10:14:25.903739 15941 memory_optimize_pass.cc:223] Cluster name : slice_40.tmp_0  size: 23104
I1110 10:14:25.903756 15941 memory_optimize_pass.cc:223] Cluster name : pool2d_0.tmp_0  size: 5914624
I1110 10:14:25.903771 15941 memory_optimize_pass.cc:223] Cluster name : concat_5.tmp_0  size: 7393280
I1110 10:14:25.903786 15941 memory_optimize_pass.cc:223] Cluster name : res2a.add.output.5.tmp_1  size: 23658496
I1110 10:14:25.903800 15941 memory_optimize_pass.cc:223] Cluster name : slice_33.tmp_0  size: 1848320
I1110 10:14:25.903815 15941 memory_optimize_pass.cc:223] Cluster name : yolo_box0.tmp_0  size: 17328
I1110 10:14:25.903829 15941 memory_optimize_pass.cc:223] Cluster name : image  size: 4435968
I1110 10:14:25.903843 15941 memory_optimize_pass.cc:223] Cluster name : slice_38.tmp_0  size: 92416
I1110 10:14:25.903857 15941 memory_optimize_pass.cc:223] Cluster name : tmp_31  size: 23104
I1110 10:14:25.903872 15941 memory_optimize_pass.cc:223] Cluster name : pool2d_6.tmp_0  size: 739328
I1110 10:14:25.903884 15941 memory_optimize_pass.cc:223] Cluster name : transpose_1.tmp_0  size: 1386240
I1110 10:14:25.903898 15941 memory_optimize_pass.cc:223] Cluster name : slice_34.tmp_0  size: 92416
I1110 10:14:25.903913 15941 memory_optimize_pass.cc:223] Cluster name : res2b.add.output.5.tmp_1  size: 23658496
I1110 10:14:25.903926 15941 memory_optimize_pass.cc:223] Cluster name : yolo_box1.tmp_0  size: 69312
I1110 10:14:25.903939 15941 memory_optimize_pass.cc:223] Cluster name : slice_30.tmp_0  size: 92416
I1110 10:14:25.903954 15941 memory_optimize_pass.cc:223] Cluster name : pow_16.tmp_0  size: 23104
I1110 10:14:25.903967 15941 memory_optimize_pass.cc:223] Cluster name : sigmoid_14.tmp_0  size: 23104
I1110 10:14:25.903980 15941 memory_optimize_pass.cc:223] Cluster name : tmp_27  size: 23104
--- Running analysis [ir_graph_to_program_pass]
I1110 10:14:26.139062 15941 analysis_predictor.cc:513] ======= optimize end =======
I1110 10:14:26.139322 15941 naive_executor.cc:102] ---  skip [feed], feed -> im_size
I1110 10:14:26.139362 15941 naive_executor.cc:102] ---  skip [feed], feed -> image
I1110 10:14:26.148713 15941 naive_executor.cc:102] ---  skip [res2a.add.output.5.tmp_1], fetch -> fetch
W1110 10:14:26.270795 15941 device_context.cc:320] Please NOTE: device: 0, CUDA Capability: 62, Driver API Version: 10.2, Runtime API Version: 10.2
W1110 10:14:26.282234 15941 device_context.cc:328] device: 0, cuDNN Version: 8.0.
/usr/lib/python3/dist-packages/apport/report.py:13: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import fnmatch, glob, traceback, errno, sys, atexit, locale, imp
Traceback (most recent call last):
  File "/home/dji/Desktop/code/Paddle-Inference-Demo-master_lisg/python/yolov3/infer_yolov3.py", line 109, in <module>
    result = run(pred, [data, im_shape])  
  File "/home/dji/Desktop/code/Paddle-Inference-Demo-master_lisg/python/yolov3/infer_yolov3.py", line 61, in run
    predictor.zero_copy_run()
paddle.fluid.core_noavx.EnforceNotMet: 

  Compile Traceback (most recent call last):
    File "e:\Majoring\AI\PaddlePaddle\PaddleDetection\PaddleDetection-release-0.4_lisg\tools\export_model.py", line 251, in <module>
      main()
    File "e:\Majoring\AI\PaddlePaddle\PaddleDetection\PaddleDetection-release-0.4_lisg\tools\export_model.py", line 213, in main
      test_fetches = model.test(feed_vars, exclude_nms=FLAGS.exclude_nms)
    File "e:\Majoring\AI\PaddlePaddle\PaddleDetection\PaddleDetection-release-0.4_lisg\ppdet\modeling\architectures\yolo.py", line 176, in test
      return self.build(feed_vars, mode='test', exclude_nms=exclude_nms)
    File "e:\Majoring\AI\PaddlePaddle\PaddleDetection\PaddleDetection-release-0.4_lisg\ppdet\modeling\architectures\yolo.py", line 61, in build
    File "e:\Majoring\AI\PaddlePaddle\PaddleDetection\PaddleDetection-release-0.4_lisg\ppdet\modeling\backbones\resnet.py", line 485, in __call__
      res = self.layer_warp(res, i)
    File "e:\Majoring\AI\PaddlePaddle\PaddleDetection\PaddleDetection-release-0.4_lisg\ppdet\modeling\backbones\resnet.py", line 427, in layer_warp
      gcb_name=gcb_name)
    File "e:\Majoring\AI\PaddlePaddle\PaddleDetection\PaddleDetection-release-0.4_lisg\ppdet\modeling\backbones\resnet.py", line 340, in bottleneck
      dcn_v2=(i == 1 and dcn_v2))
    File "e:\Majoring\AI\PaddlePaddle\PaddleDetection\PaddleDetection-release-0.4_lisg\ppdet\modeling\backbones\resnet.py", line 185, in _conv_norm
      name=_name + '.conv2d.output.1')
    File "E:\ProgramFiles\Anaconda3\lib\site-packages\paddle\fluid\layers\nn.py", line 1597, in conv2d
      "data_format": data_format,
    File "E:\ProgramFiles\Anaconda3\lib\site-packages\paddle\fluid\layer_helper.py", line 43, in append_op
      return self.main_program.current_block().append_op(*args, **kwargs)
    File "E:\ProgramFiles\Anaconda3\lib\site-packages\paddle\fluid\framework.py", line 2917, in append_op
      attrs=kwargs.get("attrs", None))
    File "E:\ProgramFiles\Anaconda3\lib\site-packages\paddle\fluid\framework.py", line 2014, in __init__
      for frame in traceback.extract_stack():

--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
0   paddle::AnalysisPredictor::ZeroCopyRun()
1   paddle::framework::NaiveExecutor::Run()
2   paddle::framework::OperatorBase::Run(paddle::framework::Scope const&, paddle::platform::Place const&)
3   paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, paddle::platform::Place const&) const
4   paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, paddle::platform::Place const&, paddle::framework::RuntimeContext*) const
5   std::_Function_handler<void (paddle::framework::ExecutionContext const&), paddle::framework::OpKernelRegistrarFunctor<paddle::platform::CUDAPlace, false, 0ul, paddle::operators::CUDNNConvFusionOpKernel<float>, paddle::operators::CUDNNConvFusionOpKernel<double> >::operator()(char const*, char const*, int) const::{lambda(paddle::framework::ExecutionContext const&)#1}>::_M_invoke(std::_Any_data const&, paddle::framework::ExecutionContext const&)
6   paddle::operators::CUDNNConvFusionOpKernel<float>::Compute(paddle::framework::ExecutionContext const&) const
7   paddle::platform::EnforceNotMet::EnforceNotMet(std::__exception_ptr::exception_ptr, char const*, int)
8   std::string paddle::platform::GetTraceBackString<char const*>(char const*&&, char const*, int)
9   paddle::platform::GetCurrentTraceBackString[abi:cxx11]()

----------------------
Error Message Summary:
----------------------
ExternalError:  Cudnn error, CUDNN_STATUS_EXECUTION_FAILED  (at /home/dji/Desktop/disk/Paddle-release-2.0-beta/paddle/fluid/operators/fused/conv_fusion_op.cu:311)
  [operator < conv2d_fusion > error]

- error info when TRT on (also extremely slow：708542ms):
W1110 10:21:29.401307 17962 analysis_predictor.cc:578] The one-time configuration of analysis predictor failed, which may be due to native predictor called first and its configurations taken effect.
I1110 10:21:29.401432 17962 analysis_predictor.cc:139] Profiler is deactivated, and no profiling report will be generated.
I1110 10:21:29.464711 17962 op_compatible_info.cc:203] The default operator required version is missing. Please update the model version.
I1110 10:21:29.464803 17962 analysis_predictor.cc:952] MODEL VERSION: 2.0.0
I1110 10:21:29.464828 17962 analysis_predictor.cc:954] PREDICTOR VERSION: 0.0.0
W1110 10:21:29.465101 17962 analysis_predictor.cc:967]  - Version incompatible (1) assign_value
W1110 10:21:29.465152 17962 analysis_predictor.cc:967]  - Version incompatible (1) batch_norm
W1110 10:21:29.465173 17962 analysis_predictor.cc:967]  - Version incompatible (1) clip
W1110 10:21:29.465191 17962 analysis_predictor.cc:967]  - Version incompatible (1) concat
W1110 10:21:29.465209 17962 analysis_predictor.cc:967]  - Version incompatible (1) conv2d
W1110 10:21:29.465226 17962 analysis_predictor.cc:967]  - Version incompatible (1) deformable_conv
W1110 10:21:29.465245 17962 analysis_predictor.cc:967]  - Version incompatible (1) elementwise_add
W1110 10:21:29.465262 17962 analysis_predictor.cc:967]  - Version incompatible (1) elementwise_div
W1110 10:21:29.465279 17962 analysis_predictor.cc:967]  - Version incompatible (1) elementwise_mul
W1110 10:21:29.465296 17962 analysis_predictor.cc:967]  - Version incompatible (1) feed
W1110 10:21:29.465314 17962 analysis_predictor.cc:967]  - Version incompatible (1) fetch
W1110 10:21:29.465334 17962 analysis_predictor.cc:967]  - Version incompatible (1) fill_constant
W1110 10:21:29.465353 17962 analysis_predictor.cc:967]  - Version incompatible (1) leaky_relu
W1110 10:21:29.465369 17962 analysis_predictor.cc:967]  - Version incompatible (1) log
W1110 10:21:29.465386 17962 analysis_predictor.cc:967]  - Version incompatible (1) matrix_nms
W1110 10:21:29.465404 17962 analysis_predictor.cc:967]  - Version incompatible (1) nearest_interp
W1110 10:21:29.465420 17962 analysis_predictor.cc:967]  - Version incompatible (1) pool2d
W1110 10:21:29.465436 17962 analysis_predictor.cc:967]  - Version incompatible (1) pow
W1110 10:21:29.465453 17962 analysis_predictor.cc:967]  - Version incompatible (1) relu
W1110 10:21:29.465469 17962 analysis_predictor.cc:967]  - Version incompatible (1) scale
W1110 10:21:29.465485 17962 analysis_predictor.cc:967]  - Version incompatible (1) sigmoid
W1110 10:21:29.465502 17962 analysis_predictor.cc:967]  - Version incompatible (1) slice
W1110 10:21:29.465518 17962 analysis_predictor.cc:967]  - Version incompatible (1) split
W1110 10:21:29.465536 17962 analysis_predictor.cc:967]  - Version incompatible (1) transpose2
W1110 10:21:29.465553 17962 analysis_predictor.cc:967]  - Version incompatible (1) yolo_box
W1110 10:21:29.465574 17962 analysis_predictor.cc:195] WARNING: Results may be DIFF! Please use the corresponding version of the model and prediction library, and do not use the develop branch.
I1110 10:21:29.466562 17962 analysis_predictor.cc:449] TensorRT subgraph engine is enabled
--- Running analysis [ir_graph_build_pass]
--- Running analysis [ir_graph_clean_pass]
--- Running analysis [ir_analysis_pass]
--- Running IR pass [conv_affine_channel_fuse_pass]
--- Running IR pass [conv_eltwiseadd_affine_channel_fuse_pass]
--- Running IR pass [shuffle_channel_detect_pass]
--- Running IR pass [quant_conv2d_dequant_fuse_pass]
--- Running IR pass [delete_quant_dequant_op_pass]
--- Running IR pass [simplify_with_basic_ops_pass]
--- Running IR pass [embedding_eltwise_layernorm_fuse_pass]
--- Running IR pass [multihead_matmul_fuse_pass_v2]
--- Running IR pass [skip_layernorm_fuse_pass]
--- Running IR pass [conv_bn_fuse_pass]
I1110 10:21:30.310256 17962 graph_pattern_detector.cc:100] ---  detected 73 subgraphs
--- Running IR pass [fc_fuse_pass]
--- Running IR pass [tensorrt_subgraph_pass]
I1110 10:21:30.551087 17962 tensorrt_subgraph_pass.cc:115] ---  detect a sub-graph with 158 nodes
I1110 10:21:30.576210 17962 tensorrt_subgraph_pass.cc:321] Prepare TRT engine (Optimize model structure, Select OP kernel etc). This process may cost a lot of time.
I1110 10:21:32.672781 17962 engine.cc:83] Run Paddle-TRT FP16 mode
I1110 10:22:14.076041 17962 tensorrt_subgraph_pass.cc:115] ---  detect a sub-graph with 4 nodes
I1110 10:22:14.077877 17962 tensorrt_subgraph_pass.cc:321] Prepare TRT engine (Optimize model structure, Select OP kernel etc). This process may cost a lot of time.
I1110 10:22:14.079044 17962 engine.cc:83] Run Paddle-TRT FP16 mode
I1110 10:22:15.501123 17962 tensorrt_subgraph_pass.cc:115] ---  detect a sub-graph with 25 nodes
I1110 10:22:15.506562 17962 tensorrt_subgraph_pass.cc:321] Prepare TRT engine (Optimize model structure, Select OP kernel etc). This process may cost a lot of time.
I1110 10:22:15.513082 17962 engine.cc:83] Run Paddle-TRT FP16 mode
I1110 10:23:28.580720 17962 tensorrt_subgraph_pass.cc:115] ---  detect a sub-graph with 13 nodes
I1110 10:23:28.584486 17962 tensorrt_subgraph_pass.cc:321] Prepare TRT engine (Optimize model structure, Select OP kernel etc). This process may cost a lot of time.
I1110 10:23:28.590802 17962 engine.cc:83] Run Paddle-TRT FP16 mode
I1110 10:23:38.184165 17962 tensorrt_subgraph_pass.cc:115] ---  detect a sub-graph with 13 nodes
I1110 10:23:38.187851 17962 tensorrt_subgraph_pass.cc:321] Prepare TRT engine (Optimize model structure, Select OP kernel etc). This process may cost a lot of time.
I1110 10:23:38.195144 17962 engine.cc:83] Run Paddle-TRT FP16 mode
I1110 10:23:48.002578 17962 tensorrt_subgraph_pass.cc:115] ---  detect a sub-graph with 4 nodes
I1110 10:23:48.004381 17962 tensorrt_subgraph_pass.cc:321] Prepare TRT engine (Optimize model structure, Select OP kernel etc). This process may cost a lot of time.
I1110 10:23:48.005442 17962 engine.cc:83] Run Paddle-TRT FP16 mode
I1110 10:23:49.392982 17962 tensorrt_subgraph_pass.cc:115] ---  detect a sub-graph with 28 nodes
I1110 10:23:49.398624 17962 tensorrt_subgraph_pass.cc:321] Prepare TRT engine (Optimize model structure, Select OP kernel etc). This process may cost a lot of time.
I1110 10:23:49.410517 17962 engine.cc:83] Run Paddle-TRT FP16 mode
I1110 10:24:08.889302 17962 tensorrt_subgraph_pass.cc:115] ---  detect a sub-graph with 4 nodes
I1110 10:24:08.891063 17962 tensorrt_subgraph_pass.cc:321] Prepare TRT engine (Optimize model structure, Select OP kernel etc). This process may cost a lot of time.
I1110 10:24:08.892202 17962 engine.cc:83] Run Paddle-TRT FP16 mode
I1110 10:24:10.282735 17962 tensorrt_subgraph_pass.cc:115] ---  detect a sub-graph with 40 nodes
I1110 10:24:10.290323 17962 tensorrt_subgraph_pass.cc:321] Prepare TRT engine (Optimize model structure, Select OP kernel etc). This process may cost a lot of time.
I1110 10:24:10.330322 17962 engine.cc:83] Run Paddle-TRT FP16 mode
--- Running IR pass [conv_bn_fuse_pass]
--- Running IR pass [conv_elementwise_add_act_fuse_pass]
--- Running IR pass [conv_elementwise_add2_act_fuse_pass]
--- Running IR pass [conv_elementwise_add_fuse_pass]
--- Running IR pass [transpose_flatten_concat_fuse_pass]
--- Running analysis [ir_params_sync_among_devices_pass]
I1110 10:24:44.699743 17962 ir_params_sync_among_devices_pass.cc:41] Sync params from CPU to GPU
--- Running analysis [adjust_cudnn_workspace_size_pass]
--- Running analysis [inference_op_replace_pass]
--- Running analysis [memory_optimize_pass]
I1110 10:24:44.958851 17962 memory_optimize_pass.cc:223] Cluster name : yolo_box0.tmp_0  size: 17328
I1110 10:24:44.958932 17962 memory_optimize_pass.cc:223] Cluster name : im_size  size: 8
I1110 10:24:44.958956 17962 memory_optimize_pass.cc:223] Cluster name : pow_13.tmp_0  size: 23104
I1110 10:24:44.958973 17962 memory_optimize_pass.cc:223] Cluster name : tmp_24  size: 23104
I1110 10:24:44.958989 17962 memory_optimize_pass.cc:223] Cluster name : concat_19.tmp_0  size: 7277760
I1110 10:24:44.959005 17962 memory_optimize_pass.cc:223] Cluster name : transpose_1.tmp_0  size: 1386240
I1110 10:24:44.959020 17962 memory_optimize_pass.cc:223] Cluster name : concat_18.tmp_0  size: 363888
I1110 10:24:44.959035 17962 memory_optimize_pass.cc:223] Cluster name : transpose_2.tmp_0  size: 5544960
I1110 10:24:44.959050 17962 memory_optimize_pass.cc:223] Cluster name : transpose_0.tmp_0  size: 346560
I1110 10:24:44.959066 17962 memory_optimize_pass.cc:223] Cluster name : yolo_box1.tmp_0  size: 69312
I1110 10:24:44.959081 17962 memory_optimize_pass.cc:223] Cluster name : yolo_box2.tmp_0  size: 277248
--- Running analysis [ir_graph_to_program_pass]
I1110 10:24:45.226670 17962 analysis_predictor.cc:513] ======= optimize end =======
I1110 10:24:45.227457 17962 naive_executor.cc:102] ---  skip [feed], feed -> im_size
I1110 10:24:45.227505 17962 naive_executor.cc:102] ---  skip [feed], feed -> image
I1110 10:24:45.232653 17962 naive_executor.cc:102] ---  skip [concat_19.tmp_0], fetch -> fetch
W1110 10:24:45.349030 17962 device_context.cc:320] Please NOTE: device: 0, CUDA Capability: 62, Driver API Version: 10.2, Runtime API Version: 10.2
W1110 10:24:45.349779 17962 device_context.cc:328] device: 0, cuDNN Version: 8.0.
iter:0, Cost time: 708542ms
/media/a6e91094-25f9-4de3-9925-de0d6f2fc0bb/code/Paddle-Inference-Demo-master_lisg/python/yolov3/utils.py:44: RuntimeWarning: invalid value encountered in less
  if score < threshold:

**code：**
import numpy as np
import argparse
import cv2
from PIL import Image

from paddle.fluid.core import AnalysisConfig
from paddle.fluid.core import create_paddle_predictor

from utils import preprocess, draw_bbox
import time

def create_predictor(args):
  if args.model_dir is not "":   #non-combined
    config = AnalysisConfig(args.model_dir)
  else:                          #combined
    config = AnalysisConfig(args.model_file, args.params_file)

  config.switch_use_feed_fetch_ops(False) 
  config.enable_memory_optim()       
  if args.use_gpu:
    config.enable_use_gpu(1000, 0)    
  else:
    config.set_cpu_math_library_num_threads(4)             

  config.enable_tensorrt_engine(  \
    1 << 30,    # workspace_size
    1,          # max_batch_size
    3,          # min_subgraph_size
    AnalysisConfig.Precision.Float32,
    # AnalysisConfig.Precision.Half, 
    False,      # use_static
    False,      # use_calib_mode
    )

  predictor = create_paddle_predictor(config)
  return predictor

def run(predictor, img):  
  input_names = predictor.get_input_names()        
  for i, name in enumerate(input_names):    
    input_tensor = predictor.get_input_tensor(name) 
    input_tensor.reshape(img[i].shape)             
    input_tensor.copy_from_cpu(img[i].copy())      

  predictor.zero_copy_run()

  output_names = predictor.get_output_names()      
  results = []
  for i, name in enumerate(output_names):
    output_tensor = predictor.get_output_tensor(name) 
    output_data = output_tensor.copy_to_cpu()        )
    results.append(output_data)
  return results

def parse_args():
    parser = argparse.ArgumentParser()
    parser.add_argument("--model_file", type=str, default="", help="Model filename, Specify this when your model is a combined model.")
    parser.add_argument("--params_file", type=str, default="", help="Parameter filename, Specify this when your model is a combined model.")
    parser.add_argument("--model_dir", type=str, default="", help="Model dir, If you load a non-combined model, specify the directory of the model.")
    parser.add_argument("--use_gpu", type=int, default=0, help="Whether use gpu.")
    return parser.parse_args()

if __name__ == '__main__':
  args = parse_args()

  args.__setattr__("model_file", "/yolov3_infer/__model__")
  args.__setattr__("params_file", "/yolov3_infer/__params__")
  args.__setattr__("use_gpu", 1)

  img_name = '/kite.jpg' 
  save_img_name = 'output.jpg'                    
  im_size = 608

  pred = create_predictor(args) 
  iters = 1
  for i in range(iters):
    ticks = time.time()
    img = cv2.imread(img_name)
    data = preprocess(img, im_size)
    im_shape = np.array([im_size, im_size]).reshape((1,2)).astype(np.int32)
    result = run(pred, [data, im_shape])  

  img = Image.open(img_name).convert('RGB').resize((im_size, im_size))
  draw_bbox(img, result[0], save_name=save_img_name)

**Comment by liuhuiCNN** [comment]
hi, thank you for your feedback.
I had test ppyolo on TX2 using paddle inference lib version 1.8.4, and it is OK. Please ref [TX2_build](https://github.com/PaddlePaddle/PaddleDetection/blob/master/deploy/cpp/docs/TX2_build.md) for more details.
And we will test on paddle inference lib version 2.0, and will replay asap. Thank you.

**Comment by lleesg** [comment]
> hi, thank you for your feedback.
> I had test ppyolo on TX2 using paddle inference lib version 1.8.4, and it is OK. Please ref [TX2_build](https://github.com/PaddlePaddle/PaddleDetection/blob/master/deploy/cpp/docs/TX2_build.md) for more details.
> And we will test on paddle inference lib version 2.0, and will replay asap. Thank you.

hello dear Liu，regarding the error 
“ExternalError: Cudnn error, CUDNN_STATUS_EXECUTION_FAILED (at /home/dji/Desktop/disk/Paddle-release-2.0-beta/paddle/fluid/operators/fused/conv_fusion_op.cu:311)
[operator < conv2d_fusion > error]”

I updated to paddle2.0rc but the error remains，did u get any idea? 3q~


I did some experiment:
**code1:**
    config.enable_tensorrt_engine(  \
        1 << 30, 
        1,   
        3,    
        Config.Precision.Float32, 
        False,    
        False,  
        )
**code2:**  
     config.switch_ir_option(False)
    # see https://github.com/PaddlePaddle/Paddle/issues/30132#issuecomment-755125908

1.**no code1 or code 2:** met the CUDNN_STATUS_EXECUTION_FAILED  error as above topic show
2.**add code1 and code2:** run successfully and get right predictions but didn't enable TRT
3.**only code1:** run successfully but get wrong prediction of which the scores are very low——about 0.01


I need TRT for  acceleration, and I can't figure out what's happening during the three cases..
