### ISSUE TITLE
docker环境可否支持notebook？

### ISSUE THREAD

**Issue by ghost** [PaddlePaddle/Paddle#28502]
## 问题：
由于个人电脑的性能限制和运行环境等多方面因素，而比较喜欢docker这种方便的部署方法。官方也给出了docker的部署解决方案，但是有一点特别不人性化的地方，就是docker容器部署成功后需要进入容器，在安装vim后才能开始编码，不说vim工具的学习成本，我想也不会有人会长时间连接服务器，并且进入容器编码吧，这明显不太方便！
## 建议：
希望在paddle容器中集成notebook环境，对外开放端口，用浏览器可以直接访问，就如同aistudio中的操作环境一样。这样就可以避免那么麻烦的登录服务器进入容器编码的繁杂操作，还可以解决个人电脑性能不足、环境搭建不方便等问题！

### 望采纳！！！！！！！！！

**Comment by OliverLPH** [comment]
目前官方镜像里是没有notebook的。但启动容器时映射所需端口，安装notebook，然后进入容器在对应端口开启jupyter服务也可以达到你需要的效果

**Comment by wadefelix** [comment]
您好，暂时可以使用此项目  https://github.com/PaddlePaddle/book 提供的那个 `paddlepaddle/book` 镜像，就是一个jupyter notebook。
发布新版本的且更规范的jupyter镜像已在考虑中

**Comment by wadefelix** [comment]
> 您好，暂时可以使用此项目 https://github.com/PaddlePaddle/book 提供的那个 `paddlepaddle/book` 镜像，就是一个jupyter notebook。 发布新版本的且更规范的jupyter镜像已在考虑中

补充：
https://hub.docker.com/r/paddlepaddle/paddle 
2.1和2.2均发布了相应的jupyter镜像，如最新版本的镜像是`paddlepaddle/paddle:2.2.2-jupyter`

**Comment by ghost** [comment]
好的，谢谢贡献，我之前用的1.x的版本，没有找到jupyter功能，需要自己去搭建，现在2.x的已经有了
