### ISSUE TITLE
通过接口保存用户训练作业的checkpoint

### ISSUE THREAD

**Issue by KingCSer** [PaddlePaddle/Paddle#28501]
配置：paddlepaddle-1.8.5-gpu docker安装
paddle里面有没有调度保存训练作业checkpoint的接口？如果没有，怎样在io里面写一个保存用户训练作业程序checkpoint的接口，该接口怎样与用户训练作业交互？

**Comment by lfchener** [comment]
静态图可参考：https://www.paddlepaddle.org.cn/documentation/docs/zh/api_guides/low_level/model_save_reader.html#api-guide-model-save-reader
动态图可参考：https://www.paddlepaddle.org.cn/documentation/docs/zh/beginners_guide/basic_concept/dygraph/DyGraph.html#id9
