### ISSUE TITLE
想问下PADDLE

### ISSUE THREAD

**Issue by MARD1NO** [PaddlePaddle/Paddle#28506]
![图片](https://user-images.githubusercontent.com/42901638/98622728-25461e80-2345-11eb-8e8a-b402b46c75a9.png)
您好，想问下Paddle2.0的日志功能能关闭吗

**Comment by 123malin** [comment]
你好，感谢使用Paddle。目前这些日志打印是不能关闭的～

**Comment by MARD1NO** [comment]
> 你好，感谢使用Paddle。目前这些日志打印是不能关闭的～

好的谢谢～
