### ISSUE TITLE
dynamic_lstm 中 sequence_length 如何设置

### ISSUE THREAD

**Issue by Ryan906k9** [PaddlePaddle/Paddle#28526]
请教 paddle.fluid.layers.dynamic_lstm 中 sequence_length 如何设置？

**Comment by wangxicoding** [comment]
用rnn这个
https://paddlepaddle.org.cn/documentation/docs/zh/api_cn/layers_cn/rnn_cn.html#rnn
或者使用2.0里面的`paddle.nn.LSTM ` https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/nn/layer/rnn/LSTM_cn.html#lstm

**Comment by Ryan906k9** [comment]
> 用rnn这个
> https://paddlepaddle.org.cn/documentation/docs/zh/api_cn/layers_cn/rnn_cn.html#rnn
> 或者使用2.0里面的`paddle.nn.LSTM ` https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/nn/layer/rnn/LSTM_cn.html#lstm

感谢回复，我问这个问题的原因是我在分析一个项目代码，其中用到了 paddle.fluid.layers.dynamic_lstm，但是查询API文档没有看到设置 sequence_length 的地方，那意味着dynamic_lstm的序列长度默认为一个batch的大小吗？
