### ISSUE TITLE
Nan 训练的时候会有 Nan

### ISSUE THREAD

**Issue by OleNet** [PaddlePaddle/Paddle#28539]
![image](https://user-images.githubusercontent.com/3206718/98779451-d8d70d80-242e-11eb-9de7-7bbc4b458f3c.png)
训练的时候会有nan，在 step 114521 的时候loss 还好好的， 是 1.66312， 但是下一步就nan了。
我在nan的时候，把很多变量都打印了出来， 可以看到 word_embedding 都是nan， 感觉很奇怪，因为loss看起来也不是很大的样子。 
这种情况下要怎么办呢？

**Comment by wangxicoding** [comment]
静态图可以用nan_inf工具检查一下具体是什么地方出的nan  https://www.paddlepaddle.org.cn/documentation/docs/zh/advanced_guide/flags/check_nan_inf_cn.html#id5 。 另外是不是lr太大，可能导致出nan了
