### ISSUE TITLE
C-API的通用预测程序

### ISSUE THREAD

**Issue by fty8788** [PaddlePaddle/Paddle#2853]
现阶段C-API的使用介绍感觉比较简单，不够具体，导致初学者开发预测程序的难度不小。
能否提供基于C-API的通用预测程序，包括加载模型、读入测试数据、计算模型输出等基本功能。

**Comment by jacquesqiao** [comment]
https://github.com/PaddlePaddle/Paddle/tree/develop/paddle/capi/examples/model_inference  可以参考下这个文档

**Comment by jacquesqiao** [comment]
请问是厂里的同学么？

**Comment by lcy-seso** [comment]
@fty8788 是对的，我们不能只靠这样一个简单的文档来说明CAPI的使用，必须有例子。已经开始计划会给models 下面的例子加上 CAPI 预测接口，完成日期待进一步确认告知大家。

**Comment by fty8788** [comment]
赞，多谢两位

**Comment by lcy-seso** [comment]
@fty8788 在这个issue 下回复各位此事的进度。

**Comment by Jarlonyan** [comment]
@fty8788 ，2楼给的文档还是太简单啊。。我的问题是，模型输入不是dense，sparse-weight， sparse-non-weight，而是这三种的混合。请问有没有demo啊？？

**Comment by guoshengCS** [comment]
@reyoung 已在Hi群中提供静态库的下载连接http://yq01-idl-gpu-jpaas-let00.yq01.baidu.com:8111/viewLog.html?buildTypeId=Paddle_CapiBin&buildId=lastSuccessful

**Comment by Jarlonyan** [comment]
@guoshengCS ，你说的这个库我也用了，也不行。。。请问有没有文档。

**Comment by guoshengCS** [comment]
对于Hi中提供的未找到头文件的报错信息，可以尝试下按报错从Paddle代码中提取头文件组织下include的目录结构

**Comment by Jarlonyan** [comment]
这个问题，我踩的坑比较多，编译链接了一天。 guoshengCS 上面提供了静态库的下载链接。。。
1. 开始的时候，按照 http://wiki.baidu.com/pages/viewpage.action?pageId=333193833， 只链接paddle中的库，错误
2. 然后将那四个压缩包解压缩，find所有的.a文件，将所有的库链接进去，还是错误。
3. 最后，我只将其中的mkl目录和  third_party/install目录下的静态库链接进去， OK了。
这里记录下，希望大家不要犯跟我一样的低级错误。
