### ISSUE TITLE
Paddle安装后验证

### ISSUE THREAD

**Issue by 642721838** [PaddlePaddle/Paddle#28540]
老师您好，我安装paddle完了验证的时候一直是正在验证，没有出现安装成功的提示，请问怎么解决啊。

> 
![image](https://user-images.githubusercontent.com/46669502/98784811-a204f580-2436-11eb-926e-47e7791b0fbe.png)

**Comment by wangxicoding** [comment]
稍等一会，多按下回车应该好了

**Comment by 642721838** [comment]
我回车了，也等了很久，但是没反应，我的GPU是RTX3090的




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/Paddle"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年11月11日(星期三) 下午5:33
收件人:&nbsp;"PaddlePaddle/Paddle"<Paddle@noreply.github.com&gt;;
抄送:&nbsp;"棉花糖"<642721838@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [PaddlePaddle/Paddle] Paddle安装后验证 (#28540)





 
稍等一会，多按下回车应该好了

**Comment by 642721838** [comment]
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp;
您好，我按照您的方法就出现了这个
顺便补充一下，我的系统是Windows，GPU是RTX3090
您看怎么解决
或者你给个qq吧，这样方便交流
谢谢







------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/Paddle"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年11月11日(星期三) 下午5:33
收件人:&nbsp;"PaddlePaddle/Paddle"<Paddle@noreply.github.com&gt;;
抄送:&nbsp;"棉花糖"<642721838@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [PaddlePaddle/Paddle] Paddle安装后验证 (#28540)





 
稍等一会，多按下回车应该好了

**Comment by wangxicoding** [comment]
就一直卡着吗，你的QQ就是用户名？

**Comment by 642721838** [comment]
642721838


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/Paddle"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年11月11日(星期三) 晚上6:23
收件人:&nbsp;"PaddlePaddle/Paddle"<Paddle@noreply.github.com&gt;;
抄送:&nbsp;"棉花糖"<642721838@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [PaddlePaddle/Paddle] Paddle安装后验证 (#28540)





 
就一直卡着吗，你的QQ就是用户名？
