### ISSUE TITLE
paddle有没有计划在未来实现fft,stft等运算

### ISSUE THREAD

**Issue by nx5216** [PaddlePaddle/Paddle#28546]
我有些音频数据目前端到端训练效果不好，只能先用stft处理，考虑到硬盘的存储又只能在线转换，scipy，librosa满足不了速度要求
,pytorch和tensorflow都提供了原生的时频运算，我想请问下未来paddle会考虑加入这些运算吗

**Comment by wangxicoding** [comment]
您好，这些都是语音方面的算子吧，一般您常用的都有哪些，我们内部会安排调研评估，未来有计划尽快回复~

**Comment by nx5216** [comment]
我现在常用的就是fft,stft以及它的逆运算，具体可参考pytorch中相关的算子

**Comment by wangxicoding** [comment]
好的，感谢反馈，我们将尽快安排调研评估~
