### ISSUE TITLE
paddle.vision.ImageFolder 正常要返回target, 但是只返回了sample

### ISSUE THREAD

**Issue by habout632** [PaddlePaddle/Paddle#28548]
def __getitem__(self, index):
        """
        Args:
            index (int): Index

        Returns:
            tuple: (sample, target) where target is class_index of the target class.
        """
        path = self.samples[index]
        sample = self.loader(path)
        if self.transform is not None:
            sample = self.transform(sample)
        return [sample]

    def __len__(self):
        return len(self.samples)

**Comment by LielinJiang** [comment]
这个应该是文档的问题，ImageFolder只返回图片。想要放回target的，可以使用DatasetFolder

**Comment by MrXnneHang** [comment]
三年之后ImageFolder依然是返回sample
