### ISSUE TITLE
2.0rc版本是否支持在Windows下的TensorRT加速预测，有没有C++版本的预测库？

### ISSUE THREAD

**Issue by TianCaibailei** [PaddlePaddle/Paddle#28552]
在Paddle 2.0rc版本中，是否支持Windows下的TensorRT预测，有没有C++版本的支持TRT的预测库？
如果支持Windows下TRT加速，可以支持哪些模型？

**Comment by shangzhizhou** [comment]
您好，当前预编译的版本里还没有加入tensorRT，但是可以通过源码编译，cmake指定TENSORRT_ROOT。PaddleInference里TensorRT对模型的支持并不一定是完成的模型支持，也可能只有一部分跑在trt中，支持常见的大部分模型。

**Comment by TianCaibailei** [comment]
> 您好，当前预编译的版本里还没有加入tensorRT，但是可以通过源码编译，cmake指定TENSORRT_ROOT。PaddleInference里TensorRT对模型的支持并不一定是完成的模型支持，也可能只有一部分跑在trt中，支持常见的大部分模型。

使用源码编译会报错停止，提示找不到CUDA,但是我的CUDA已经通过传入的参数指定了，暂不清楚什么原因。
另外trt是否支持PPYOLO或者YOLOV3的模型？

**Comment by shangzhizhou** [comment]
1. 请贴一下具体的cmake选项和报错信息
2. ppyolo和yolov3都支持部分跑在trt里。

**Comment by TianCaibailei** [comment]
> 1. 请贴一下具体的cmake选项和报错信息
> 2. ppyolo和yolov3都支持部分跑在trt里。

`D:\>cd D:\Documents\Paddle\Paddle_2.0rc

D:\Documents\Paddle\Paddle_2.0rc>cd build

D:\Documents\Paddle\Paddle_2.0rc\build>cmake .. -G "Visual Studio 16 2019" -A x64 -T host=x64 -DCMAKE_BUILD_TYPE=Release -DWITH_MKL=ON -DWITH_GPU=ON -DON_INFER=ON -DWITH_PYTHON=OFF -DCUDA_TOOKIT_ROOT_DIR="C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.0"
-- Found Paddle host system: win32, version:
-- Found Paddle host system's CPU: 12 cores
-- Selecting Windows SDK version 10.0.18362.0 to target Windows 10.0.18363.
CMake Error at D:/Program Files/CMake/share/cmake-3.18/Modules/CMakeDetermineCompilerId.cmake:367 (message):
  No CUDA toolset found.
Call Stack (most recent call first):
  D:/Program Files/CMake/share/cmake-3.18/Modules/CMakeDetermineCompilerId.cmake:32 (CMAKE_DETERMINE_COMPILER_ID_BUILD)
  D:/Program Files/CMake/share/cmake-3.18/Modules/CMakeDetermineCUDACompiler.cmake:243 (CMAKE_DETERMINE_COMPILER_ID)
  CMakeLists.txt:42 (enable_language)


-- Configuring incomplete, errors occurred!
See also "D:/Documents/Paddle/Paddle_2.0rc/build/CMakeFiles/CMakeOutput.log".
See also "D:/Documents/Paddle/Paddle_2.0rc/build/CMakeFiles/CMakeError.log".`

CMakeError.log的内容如下：
`Determining if the include file pthread.h exists failed with the following output:
Change Dir: D:/Documents/Paddle/Paddle_2.0rc/build/CMakeFiles/CMakeTmp

Run Build Command(s):C:/Program Files (x86)/Microsoft Visual Studio/2019/Professional/MSBuild/Current/Bin/MSBuild.exe cmTC_0e2e4.vcxproj /p:Configuration=Debug /p:Platform=x64 /p:VisualStudioVersion=16.0 /v:m && 用于 .NET Framework 的 Microsoft (R) 生成引擎版本 16.7.0+b89cb5fde

  版权所有(C) Microsoft Corporation。保留所有权利。
  用于 x64 的 Microsoft (R) C/C++ 优化编译器 19.27.29112 版
  CheckIncludeFile.c

  版权所有(C) Microsoft Corporation。保留所有权利。

  cl /c /Zi /W3 /WX- /diagnostics:column /Od /Ob0 /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\"Debug\"" /D _MBCS /Gm- /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"cmTC_0e2e4.dir\Debug\\" /Fd"cmTC_0e2e4.dir\Debug\vc142.pdb" /Gd /TC /errorReport:queue D:\Documents\Paddle\Paddle_2.0rc\build\CMakeFiles\CMakeTmp\CheckIncludeFile.c

D:\Documents\Paddle\Paddle_2.0rc\build\CMakeFiles\CMakeTmp\CheckIncludeFile.c(1,10): fatal error C1083: 无法打开包括文件: “pthread.h”: No such file or directory [D:\Documents\Paddle\Paddle_2.0rc\build\CMakeFiles\CMakeTmp\cmTC_0e2e4.vcxproj]`

**Comment by zhwesky2010** [comment]
@TianCaibailei 麻烦重新装一下CUDA吧，这个不是TRT的问题，GPU下的paddle应该就没法编过。因为CUDA需要在VS先安装之后再安装，另外VS2019目前没有检测过，可能有其他问题。

**Comment by TianCaibailei** [comment]
> 您好，当前预编译的版本里还没有加入tensorRT，但是可以通过源码编译，cmake指定TENSORRT_ROOT。PaddleInference里TensorRT对模型的支持并不一定是完成的模型支持，也可能只有一部分跑在trt中，支持常见的大部分模型。

请问是这样指定TENSORRT_ROOT=“我的TensorRT的目录”吗？

**Comment by shangzhizhou** [comment]
> > 您好，当前预编译的版本里还没有加入tensorRT，但是可以通过源码编译，cmake指定TENSORRT_ROOT。PaddleInference里TensorRT对模型的支持并不一定是完成的模型支持，也可能只有一部分跑在trt中，支持常见的大部分模型。
> 
> 请问是这样指定TENSORRT_ROOT=“我的TensorRT的目录”吗？

是的。
