### ISSUE TITLE
dim axis命名我觉得可以统一一下

### ISSUE THREAD

**Issue by habout632** [PaddlePaddle/Paddle#28551]
paddle.fluid.layers.reduce_sum(input, dim=None, keep_dim=False, name=None)[源代码]
paddle.chunk(x, chunks, axis=0, name=None)[源代码]

有的地方叫axis, 有的地方叫dim
dim axis命名我觉得可以统一一下

**Comment by wangxicoding** [comment]
感谢反馈，目前paddle 2.0的api都统一称axis了，fluid下基于兼容性考虑，未做更改。
