### ISSUE TITLE
Different framework inference performance gap: 同样的MobileNetV2模型在CPU上使用mkldnn预测，Paddle预测速度低于OpenVINO两倍多

### ISSUE THREAD

**Issue by jiangjiajun** [PaddlePaddle/Paddle#28555]
1）PaddlePaddle版本：1.8.5.post108
    2）CPU：型号如下
![image](https://user-images.githubusercontent.com/19339784/98811106-3c773000-245b-11eb-85fb-3ba186598caa.png)

 其中Paddle模型在OpenVINO的部署，通过Paddle2ONNX将paddle模型转换为ONNX，再部署在OpenVINO上，最终测试到指标如下
| paddle(mkl_thread=8) | paddle(mkl_thread=12) | paddle(mkl_thread=16) | paddle(mkl_thread=24) | OpenVINO |
| :--------------------- | :--------------------- | :--------------------- | :--------------------- | :--------------------- | 
|8.22ms | 5.41ms | 5.16ms | 6.21ms | 2.31ms |

上面可以看到，
- paddle最快的速度是使用16个线程加速mkldnn时，单张图片可以在5.16ms完成
- openvino无线程设置，默认则是单张图片预测用时2.31ms

Paddle和OpenVINO的测试模型及代码见网盘分享

链接: https://pan.baidu.com/s/1vUX-s73SUoq8sHqSGJJs2Q  密码: 29e2
--来自百度网盘超级会员V5的分享

以上为paddlepaddle-gpu 1.8.5在Linux上的测试，此外也同步在Windows上测试了paddlepaddle-gpu 2.0.0rc0，测试用时情况如下图所示
![image](https://user-images.githubusercontent.com/19339784/98812252-1e123400-245d-11eb-8c5c-3dfa9a191702.png)

- 可以看到openvino的预测速度仍然为Paddle的2倍多

Windows配置如下
![image](https://user-images.githubusercontent.com/19339784/98812298-308c6d80-245d-11eb-86b4-3b617127091c.png)

**Comment by luotao1** [comment]
PaddleX使用OpenVINO的部署文档：https://paddlex.readthedocs.io/zh_CN/develop/deploy/openvino/introduction.html

**Comment by jiangjiajun** [comment]
上面百度网盘提供的模型和代码包中，包含了Paddle模型和转好的OpenVINO IR，以及Paddle的Python预测代码和OpenVINO的Python预测代码，在环境中只要安装好paddlepaddle-gpu和OpenVINO后，即可分别进行预测，OpenVINO推荐安装2021.1版本（上文中测试即为该版本）

OpenVINO安装参考：https://docs.openvinotoolkit.org/latest/index.html

**Comment by lidanqing-vv** [comment]
model and data is downloaded at `shanghai-6271-ip:/data/issue_28555`, for Intel colleague

**Comment by arogowie-intel** [comment]
I've tried to reproduce this issue and don't see that big difference on provided mobilenetv2 model:

Machine: Intel(R) Xeon(R) Gold 6152 CPU @ 2.10GHz,  I used Paddle build from sources as well as installed from PyPI (different versions):
* commit: b6f86b849138d56a2e170a619979e81420bdea19
* cmake args:
```
  -DCMAKE_BUILD_TYPE=Release -DWITH_GPU=OFF -DWITH_AVX=ON -DWITH_DISTRIBUTE=OFF -DWITH_MKLDNN=ON -DON_INFER=ON -DWITH_TESTING=OFF -DWITH_INFERENCE_API_TEST=OFF -DWITH_NCCL=OFF -DWITH_PYTHON=ON -DPY_VERSION=3.6 -DWITH_LITE=OFF
```
I've exported following variables before execution of the scripts:
```
export KMP_AFFINITY=granularity=fine,compact,1,0
export KMP_BLOCKTIME=1
```

Moreover I've modified the script to not include the random generation of input data inside benchmarked loop. Instead I just generated them before. Following are the results of 1000 iterations:

| framework | time | comments |
| :---:  | :---:    | :---     |
| OpenVINO | __2.1139__  | 
| OpenVINO | 2.1659   | uses 44 threads - logical cores
| Paddle | __2.7515__  | thr=20 (develop)
| Paddle | 2.9823  | thr=20 (pip paddlepaddle-gpu==1.8.5.post107) 
| Paddle | 10.3662 | thr=1 (pip paddlepaddle==2.0.0rc0)
| Paddle | 4.3982  | thr=4 (pip paddlepaddle==2.0.0rc0)
| Paddle | 3.0769  | thr=12 (pip paddlepaddle==2.0.0rc0)
| Paddle | 2.9192  | thr=16 (pip paddlepaddle==2.0.0rc0)
| Paddle | 2.8913  | thr=20 (pip paddlepaddle==2.0.0rc0)
| Paddle | 2.9756  | thr=24 (pip paddlepaddle==2.0.0rc0)
| Paddle | 3.1630  | thr=32 (pip paddlepaddle==2.0.0rc0)
| Paddle | 3.1677  | thr=44 (pip paddlepaddle==2.0.0rc0)

If we compare two best results OV: 2.1139 and PP 2.7515 the latter is slower around 30%.

**Comment by arogowie-intel** [comment]
After more analysis, I found that Paddle's version didn't run oneDNN kernel for FC layer, so I enabled it. However, since it's run only once it doesn't improve the performance much. 
The profiling of paddle gives result:
```
-------------------------     Overhead Summary      -------------------------

Total time: 3014.46
  Computation time       Total: 2261.56     Ratio: 75.0235%
  Framework overhead     Total: 752.908     Ratio: 24.9765%

-------------------------     GpuMemCpy Summary     -------------------------

GpuMemcpy                Calls: 0           Total: 0           Ratio: 0%

-------------------------       Event Summary       -------------------------

Event                        Calls       Total       Min.        Max.        Ave.        Ratio.
thread0::conv2d              54060       2862.36     0.035869    10.0784     0.0529478   0.949542
thread0::load_combine        1           54.6529     54.6529     54.6529     54.6529     0.0181302
thread0::fc                  1020        33.6945     0.025972    4.5694      0.0330338   0.0111776
thread0::pool2d              1020        31.3245     0.027603    0.22873     0.0307103   0.0103914
thread0::softmax             1020        17.4531     0.014811    0.171933    0.0171109   0.0057898
thread0::scale               1020        14.9788     0.012648    0.046882    0.0146851   0.00496898
```
I'm attaching table which compares times reported by oneDNN and MKL-DNN libraries for each kernel. [prof_result_mkldnn_table.txt](https://github.com/PaddlePaddle/Paddle/files/5574382/prof_result_mkldnn_table.txt). It shows that Paddle's one are faster for each case. This is not surprising since Paddle uses newer version of library:
Paddle uses: oneDNN v1.6.0 (commit 361725600224f41b7347a1c6bee9b04d1e6c14d7)
OV uses: Intel MKL-DNN v0.18.0 (commit 6547f0b6aac2725bd4e36197e19fb1a6f2ee2f51)

An average from all oneDNN convolution kernels reported by oneDNN is: 0,02392261ms. Compared to what Paddle profiler reports (  0.0529478ms ) there is huge overhead somewhere apart execution. After detailed profiling of PaddlePaddle conv2d kernel execution I've found there only small opportunity to optimize. The one introduced in #29188. The updated execution time in provided script is now around 2.6418ms.

**Comment by arogowie-intel** [comment]
Below is detailed profiling of `OperatorWithKernel::RunImpl` function using `__rdtsc()` intrinsic.
The summary is prepared by specially written for this purpose profiler class.

```
--------------------------------- Profiling Summary ---------------------------------
Name                                                           Calls       Avg Time    Min Time    Max Time    Ratio (%)
ChooseKernel                                                   58141       47.1166     26          41930       0.000394492
compute.conv_Compute.ComputeFP32.AcquireForwardPrimitive       54060       1456.5      894         1335340     0.0113388
compute.conv_Compute.ComputeFP32.get_attributes_and_dev_ctx    54060       1472.54     1198        30416       0.0114637
compute.conv_Compute.ComputeFP32.WeightsWithReorder            54060       1551.71     1120        598228      0.01208
compute.conv_Compute.ComputeFP32.AcquireBiasMemWithReorder     54060       1627.06     1174        100254      0.0126666
compute.conv_Compute.ComputeFP32.SrcWithReorder.all            54060       3470.98     2376        90968       0.0270215
compute.conv_Compute.ComputeFP32.DestMem                       54060       3630.7      2288        3671470     0.0282649
InferShape                                                     57121       7028.99     1796        81512       0.057819
compute.conv_Compute.ComputeFP32.createHandler.all             54060       7139.81     5898        16283894    0.0555834
compute.conv_Compute.ComputeFP32.primitive_exec                54060       52414.2     22136       10369300    0.408044
compute.conv_Compute.ComputeFP32.all                           54060       95984.9     61972       21987468    0.747241
compute.all                                                    58141       98448       5278        22026822    0.824273
compute.conv_Compute.all                                       54060       100900      66496       22003518    0.785505
Overall                                                        58141       119436      20874       22162542    1
------------------------
```
The "Overall" is whole scope of `OperatorWithKernel::RunImpl`function. The rows corresponds to (nested) scopes.

With this we can see that `ComputeFP32.all`, that is kernel invocation and execution takes ~74%, 
whereas pure execution takes ~41%. The rest 33% is the boilerplate to invoke kernel plus profiler 
overhead. The profiler overhead can take up to 34% (test run with profiler: 3,5640s and w/o: 2,6418).
The remaining part of `RunImpl` function except the `compute` part takes ~18% of overall time, with 
`InferShape` being significant part of it (6%). In the kernel execution and invocation there is nothing 
much left to optimize, thus the most of difference between OpenVINO and Paddle probably comes from 
framework overhead.

**Comment by luotao1** [comment]
@arogowie-intel Thanks for your analysis, do you mean after following optimizations, Paddle will run faster than OpenVino?

- merge #29188 
- enable FC MKLDNN layer. We don't enable FC MKLDNN since it sometimes run faster but sometimes slower https://github.com/PaddlePaddle/Paddle/pull/15226/files#diff-8148a83acbd003053a9529118a6564903af9ba9306a28edd5f45c127443b0ef2R159
- InferShape being significant part of it(6%). We need to optimize InferShape?

**Comment by luotao1** [comment]
<img width="1024" alt="图片" src="https://user-images.githubusercontent.com/6836917/100715076-a4cd8780-33f1-11eb-8e90-26d1ce5e7edf.png">
链接: https://pan.baidu.com/s/1rRMcGvaxhfleV_rSV2xNeg  密码: fabk
放了ResNet50、MobileNetV2、YOLOv3和UNet四个模型，每个模型目录里都有一个infer.py，进入相应目录执行python infer.py即可预测

**Comment by arogowie-intel** [comment]
@luotao1 The points you mentioned probably won't suffice to run faster than OV. The [29188](https://github.com/PaddlePaddle/Paddle/pull/29188) PR give just ~4%. 
I've made some more analysis to see just the overhead of oneDNN kernel setup, and to see what consumes time apart compute part in Paddle. 
Here is the result for ResNet50 (I've downloaded it from PaddleClas repo)
```
--------------------------------- Profiling Summary ---------------------------------
Name            Calls       Avg         Min         Max         Ratio
ChooseKernel    59161       57.0501     24          33598       0.000219553
PrepareData     56104       8867.62     1798        729276      0.032363
InferShape      58141       8998.56     200         1036678     0.0340332
compute.all     59161       230685      10834       162436680   0.887774
Overall         59161       259847      34116       162576062   1
------------------------
```
Here is profiling of Convolution kernel also for ResNet50 model:
```
--------------------------------- Profiling Summary ---------------------------------
Name                          Calls       Avg         Min         Max         Ratio
ComputeFP32.primitive_exec    54060       208905      60736       11430010    0.762588
ComputeFP32.all               54060       238191      90128       26398702    0.869492
Overall                       59161       250322      25128       146413144   1
------------------------
```
So the conclusion is that oneDNN setup takes ~10% and Paddle overhead is ~12%.
And below is for MobileNetV2:
```

--------------------------------- Profiling Summary ---------------------------------
Name            Calls       Avg         Min         Max         Ratio
ChooseKernel    58141       47.2482     32          38806       0.000489059
InferShape      57121       6367.93     428         249808      0.0647571
PrepareData     56103       7169.76     1220        2664228     0.0716117
compute.all     58141       72521.7     5176        22662162    0.75066
Overall         58141       96610.5     23118       22858332    1
------------------------
```
Here is profiling of Convolution kernel also for MobilenetV2 model:
```
--------------------------------- Profiling Summary ---------------------------------
Name                          Calls       Avg         Min         Max         Ratio
ComputeFP32.primitive_exec    54060       51261.2     21504       8989504     0.528923
ComputeFP32.all               54060       75171.5     42316       20888496    0.775634
Overall                       58141       90113.5     14868       21058642    1
------------------------
```
Here conclusion is that oneDNN setup takes ~25% and Paddle overhead is 25%.
As you can see the results depends in general on used model. 

We are working on minimizing the oneDNN setup footprint. Could you take a look at `InferShapes` and `PrepareData` and try to reduce their execution time?

**Comment by luotao1** [comment]
> Could you take a look at `InferShapes` and `PrepareData` and try to reduce their execution time

Yes, these two execution times are known before, we have already tried some ways to reduce their execution time. And we will go-ahead to continue this work. If we have any progress, I will update in this issue.

**Comment by jczaja** [comment]
@jiangjiajun Can you provide openvino (single thread) and PaddlePaddle (single thread) execution times?

**Comment by jiangjiajun** [comment]
Hi, @jczaja There's a report that shows the performance comparison between OpenVINO and PaddlePaddle-MKLDNN

Under batch=1, thread=1, CPU: Intel(R) Xeon(R) Gold 5117 CPU @ 2.00GHz (12核)
ShffuleNetV2_x1 with PaddlePaddle-MKLDNN is about 5ms
ShuffleNetV2_x1 with OpenVINO is about 3ms

**Comment by jczaja** [comment]
@jiangjiajun Thanks for info. We will look to that one.

**Comment by jakpiase** [comment]
Hi, ShuffleNetV2 FP32 for PaddlePaddle-MKLDNN will be speedup by ~22% after merging this PR: https://github.com/PaddlePaddle/Paddle/pull/39756

**Comment by yaomichael** [comment]
notes from 5/20 meeting: 
@jiangjiajun is benchmarking against OpenVINO and will have data with more models shortly. No action needed from Intel until then.
