### ISSUE TITLE
visualdl正常运行，但是在网页不显示

### ISSUE THREAD

**Issue by liguoyu666** [PaddlePaddle/Paddle#28562]
我在自己电脑上能正常运行visualdl，且在网页能够可视化结果，
在另一台电脑上运行visualdl后，提示正常，但是打开网页一片空白。
![2020-11-12 10-19-22屏幕截图](https://user-images.githubusercontent.com/47743761/98887251-99f99400-24d0-11eb-965d-afed9aada045.png)
![2020-11-12 10-18-46屏幕截图](https://user-images.githubusercontent.com/47743761/98887263-9d8d1b00-24d0-11eb-941f-018e3207e7d1.png)

**Comment by JZ-LIANG** [comment]
请提供更多的日志信息帮助定位问题

**Comment by YixinKristy** [comment]
windows开启visualdl页面空白，有几个原因，可供自查
1 使用最新版chrome浏览器，如果不行，转下
2 强制刷新浏览器，如果不行，转下
3 注册表被修改，参考解决 https://github.com/PaddlePaddle/VisualDL/issues/834
目前遇到的问题基本这三步可以解决

**Comment by liguoyu666** [comment]
> windows开启visualdl页面空白，有几个原因，可供自查
> 1 使用最新版chrome浏览器，如果不行，转下
> 2 强制刷新浏览器，如果不行，转下
> 3 注册表被修改，参考解决 [PaddlePaddle/VisualDL#834](https://github.com/PaddlePaddle/VisualDL/issues/834)
> 目前遇到的问题基本这三步可以解决

谢谢，我是ubuntu系统，能正常使用那台是chrome浏览器，不能用的那台是系统自带的firefox浏览器，换个浏览器试哈

**Comment by liguoyu666** [comment]
> windows开启visualdl页面空白，有几个原因，可供自查
> 1 使用最新版chrome浏览器，如果不行，转下
> 2 强制刷新浏览器，如果不行，转下
> 3 注册表被修改，参考解决 [PaddlePaddle/VisualDL#834](https://github.com/PaddlePaddle/VisualDL/issues/834)
> 目前遇到的问题基本这三步可以解决

感谢，的确是浏览器的问题，换成google chrome就能正常显示了

**Comment by Liugazn** [comment]
我是在AI STUDIO运行的 打开网页但是一片空白
