### ISSUE TITLE
Design Network as a kind of Operator

### ISSUE THREAD

**Issue by jacquesqiao** [PaddlePaddle/Paddle#2857]
1. The most important thing for a Network is it's input, output and Run. It just works like an Operator does. So we will design Network as a kind of Operator.
2. For a network, except for input/output/Run, it also needs a special API `AddOp` because a network Op will manage several Operator inside itself.

**Comment by helinwang** [comment]
Sorry maybe this question is naive, does our operator contain both forward and backward, or forward is an Op and backward is another Op? If the latter, will we have two networks -- forward is a network (Op), backward is another network (Op)?

**Comment by jacquesqiao** [comment]
@helinwang yes, you are right, Op does not contain forward and backword, Op only have Run(), so backward op is another Op and backward network is also another Op.
