### ISSUE TITLE
is:issue is:open cmake fails on AArch64, Fedora 33 due to Protobuf version conflict 

### ISSUE THREAD

**Issue by LutzWeischerFujitsu** [PaddlePaddle/Paddle#28581]
cmake .. -DPY_PIP=/usr/bin/pip -DPY_NUMPY=$HOME/.local/lib/python3.9/site-packages/numpy -DPY_WHEEL=$HOME/.local/lib/python3.9/site-packages/wheel -DPY_GOOGLE.PROTOBUF=$HOME/.local/lib/python3.9/site-packages/protobuf
-- Found Paddle host system: , version:
-- Found Paddle host system's CPU: 48 cores
-- CXX compiler: /usr/bin/c++, version: GNU 10.2.1
-- C compiler: /usr/bin/cc, version: GNU 10.2.1
-- AR tools: /usr/bin/ar
-- Do not have AVX2 intrinsics and disabled MKL-DNN
-- BOOST_VERSION: 1.41.0, BOOST_URL: http://paddlepaddledeps.bj.bcebos.com/boost_1_41_0.tar.gz
-- warp-ctc library: /data/jw/PaddlePaddle/build/third_party/install/warpctc/lib/libwarpctc.so
-- Found OpenBLAS (include: /usr/include, library: /usr/lib64/libopenblas.so)
-- Found lapack in OpenBLAS (include: /usr/include/openblas)
CMake Warning at /usr/share/cmake/Modules/FindProtobuf.cmake:500 (message):
  Protobuf compiler version doesn't match library version 3.13.0
Call Stack (most recent call first):
  cmake/external/protobuf.cmake:18 (FIND_PACKAGE)
  cmake/third_party.cmake:230 (include)
  CMakeLists.txt:216 (include)

-- Protobuf protoc executable: /data/jw/PaddlePaddle/build/third_party/install/protobuf/bin/protoc
-- Protobuf-lite library: /data/jw/PaddlePaddle/build/third_party/install/protobuf/lib/libprotobuf-lite.a
-- Protobuf library: /data/jw/PaddlePaddle/build/third_party/install/protobuf/lib/libprotobuf.a
-- Protoc library: /data/jw/PaddlePaddle/build/third_party/install/protobuf/lib/libprotoc.a
-- Protobuf version: 3.1.0
CMake Error at cmake/external/python.cmake:74 (MESSAGE):
  Found Python Protobuf < 3.0.0, please use pip to upgrade protobuf.  pip
  install -U protobuf
Call Stack (most recent call first):
  cmake/third_party.cmake:236 (include)
  CMakeLists.txt:216 (include)

-- Configuring incomplete, errors occurred!
See also "/data/jw/PaddlePaddle/build/CMakeFiles/CMakeOutput.log".
See also "/data/jw/PaddlePaddle/build/CMakeFiles/CMakeError.log".

**Comment by JZ-LIANG** [comment]
It seem the Protobuf version is lower than [requirements](https://github.com/JZ-LIANG/Paddle/blob/6218e6dc2d1026e7a0588e2a8f1d8e6327dc7f64/python/requirements.txt#L4). Try update the Protobuf first.

**Comment by LutzWeischerFujitsu** [comment]
Tried with a fresh install, latest protobuf, but make fails: 
Scanning dependencies of target protoc
make[5]: Leaving directory '/data/jw/PaddlePaddle/build/third_party/protobuf/src/extern_protobuf-build'
make  -f CMakeFiles/protoc.dir/build.make CMakeFiles/protoc.dir/build
make[5]: Entering directory '/data/jw/PaddlePaddle/build/third_party/protobuf/src/extern_protobuf-build'
[ 99%] Building CXX object CMakeFiles/protoc.dir/data/jw/PaddlePaddle/build/third_party/protobuf/src/extern_protobuf/src/google/protobuf/compiler/main.cc.o
/usr/bin/c++ -DGOOGLE_PROTOBUF_CMAKE_BUILD -DHAVE_PTHREAD -DHAVE_ZLIB -I/data/jw/PaddlePaddle/build/third_party/protobuf/src/extern_protobuf-build -I/data/jw/PaddlePaddle/build/third_party/protobuf/src/extern_protobuf/src -isystem /data/jw/PaddlePaddle/build/third_party/install/zlib/include -Wno-error=deprecated-declarations -Wno-deprecated-declarations -O3 -DNDEBUG -fPIE -o CMakeFiles/protoc.dir/data/jw/PaddlePaddle/build/third_party/protobuf/src/extern_protobuf/src/google/protobuf/compiler/main.cc.o -c /data/jw/PaddlePaddle/build/third_party/protobuf/src/extern_protobuf/src/google/protobuf/compiler/main.cc
[100%] Linking CXX executable protoc
/usr/bin/cmake -E cmake_link_script CMakeFiles/protoc.dir/link.txt --verbose=1
/usr/bin/c++  -Wno-error=deprecated-declarations -Wno-deprecated-declarations -O3 -DNDEBUG -rdynamic CMakeFiles/protoc.dir/data/jw/PaddlePaddle/build/third_party/protobuf/src/extern_protobuf/src/google/protobuf/compiler/main.cc.o -o protoc  libprotobuf.a libprotoc.a libprotobuf.a -lpthread /data/jw/PaddlePaddle/build/third_party/install/zlib/lib/libz.so
make[5]: Leaving directory '/data/jw/PaddlePaddle/build/third_party/protobuf/src/extern_protobuf-build'
[100%] Built target protoc
make[4]: Leaving directory '/data/jw/PaddlePaddle/build/third_party/protobuf/src/extern_protobuf-build'
/usr/bin/cmake -E cmake_progress_start /data/jw/PaddlePaddle/build/third_party/protobuf/src/extern_protobuf-build/CMakeFiles 0
make[3]: Leaving directory '/data/jw/PaddlePaddle/build/third_party/protobuf/src/extern_protobuf-build'
cd /data/jw/PaddlePaddle/build/third_party/protobuf/src/extern_protobuf-build && /usr/bin/cmake -E touch /data/jw/PaddlePaddle/build/third_party/protobuf/src/extern_protobuf-stamp/extern_protobuf-build
[  4%] Performing install step for 'extern_protobuf'
cd /data/jw/PaddlePaddle/build/third_party/protobuf/src/extern_protobuf-build && /usr/bin/cmake -Dmake=make -P /data/jw/PaddlePaddle/build/third_party/protobuf/src/extern_protobuf-stamp/extern_protobuf-install-Release.cmake
-- extern_protobuf install command succeeded.  See also /data/jw/PaddlePaddle/build/third_party/protobuf/src/extern_protobuf-stamp/extern_protobuf-install-*.log
cd /data/jw/PaddlePaddle/build/third_party/protobuf/src/extern_protobuf-build && /usr/bin/cmake -E touch /data/jw/PaddlePaddle/build/third_party/protobuf/src/extern_protobuf-stamp/extern_protobuf-install
[  5%] Completed 'extern_protobuf'
/usr/bin/cmake -E make_directory /data/jw/PaddlePaddle/build/CMakeFiles
/usr/bin/cmake -E touch /data/jw/PaddlePaddle/build/CMakeFiles/extern_protobuf-complete
/usr/bin/cmake -E touch /data/jw/PaddlePaddle/build/third_party/protobuf/src/extern_protobuf-stamp/extern_protobuf-done
make[2]: Leaving directory '/data/jw/PaddlePaddle/build'
[  5%] Built target extern_protobuf
make[1]: Leaving directory '/data/jw/PaddlePaddle/build'
make: *** [Makefile:149: all] Error 2

**Comment by TuringZhu** [comment]
python3.9 macOS Big Sur Version 11.1
[CMakeError.log](https://github.com/PaddlePaddle/Paddle/files/6180582/CMakeError.log)
