### ISSUE TITLE
[oneDNN Dygraph] QA测试文档

### ISSUE THREAD

**Issue by lidanqing-vv** [PaddlePaddle/Paddle#28598]
@luotao1  Hi, this is test doc for QA. If any issues, please let me know.
[oneDNN_DyTraining_Resnet50_Test_Doc.txt](https://github.com/PaddlePaddle/Paddle/files/5535004/oneDNN_DyTraining_Resnet50_Test_Doc.txt)

**Comment by luotao1** [comment]
[动态图mkldnn测试数据-new-0.xlsx](https://github.com/PaddlePaddle/Paddle/files/5594896/mkldnn.-new-0.xlsx)
 @OliverLPH test it successfully.
