### ISSUE TITLE
安装paddlepaddle时报错:命令行输入python进入python3.7之后,import 错误：ImportError: DLL load failed: 系统无法访问此文件。

### ISSUE THREAD

**Issue by dongyangli-del** [PaddlePaddle/Paddle#28613]
win10环境，根据官方文档一步一步装的paddlepaddle-gpu，之前在另一个电脑上也是按照相应方法进行的安装，就可以正常使用，请问这是什么问题呢？

**Comment by 123malin** [comment]
可以参考一下这个issue，看是否可以解决你的问题：https://github.com/PaddlePaddle/Paddle/issues/22732

**Comment by dongyangli-del** [comment]
我试了paddle的cpu版本和gpu版本，都显示同样的报错：无法访问此文件，但是import tensorflow就是可以的，请问这又是为什么呢？

**Comment by zhwesky2010** [comment]
@dongyangli-del 您好，麻烦检查一下python安装是否正确。如果python安装正确的话，可能是系统缺少某个dll，尝试安装https://www.microsoft.com/en-us/download/details.aspx?id=48145 试试

**Comment by zhwesky2010** [comment]
@dongyangli-del 请问这个https://www.microsoft.com/en-us/download/details.aspx?id=48145 装好了吗

**Comment by dongyangli-del** [comment]
@zhouwei25 你好，直接重装了Anaconda2021,重装后问题已解决 @

**Comment by dongyangli-del** [comment]
@zhouwei25 你好，直接重装了Anaconda2021,重装后问题已解决

**Comment by dongyangli-del** [comment]
@zhouwei25 你好，直接重装了Anaconda2021,重装后问题已解决 @

**Comment by dongyangli-del** [comment]
@zhouwei25 你好，直接重装了Anaconda2021,重装后问题已解决
