### ISSUE TITLE
保存训练参数

### ISSUE THREAD

**Issue by KingCSer** [PaddlePaddle/Paddle#28617]
版本：paddle-1.8.5-gpu-cuda10.0-cudnn7
所有的save接口都是在训练程序train()内调用保存参数的，怎样在训练程序外保存训练参数？
例如，怎样实现：
main()
    train()
    save_persistables()
使得train()程序发生异常时自动保存一次参数

**Comment by 123malin** [comment]
train函数将save_persistables()需要用到的参数返回，然后在main函数中调用save接口呢？
