### ISSUE TITLE
paddle安装报错

### ISSUE THREAD

**Issue by ARDUJS** [PaddlePaddle/Paddle#28618]
### 环境
- 系统 Linux node223 3.10.0-957.12.2.el7.x86_64 #1 SMP Tue May 14 21:24:32 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
- cuda 9.2
- python 3.7.4
### 安装命令
> 根据官网
![image](https://user-images.githubusercontent.com/20811685/99093028-ec3fcf80-260c-11eb-85e5-f591522fa9c9.png)
> 报错 只是cpu版
> 后来我执行，python3 -m pip install paddlepaddle-gpu==1.7.2.post107 -i https://mirror.baidu.com/pypi/simple

### 出现问题

![image](https://user-images.githubusercontent.com/20811685/99093200-21e4b880-260d-11eb-89ec-88eb77f9a089.png)

![image](https://user-images.githubusercontent.com/20811685/99093168-17c2ba00-260d-11eb-9a63-6d6821c3c35e.png)

----------------------
Error Message Summary:
----------------------
Error: Failed to find dynamic library: libcublas.so ( libcublas.so: cannot open shared object file: No such file or directory ) 
 Please specify its path correctly using following ways: 
 Method. set environment variable LD_LIBRARY_PATH on Linux or DYLD_LIBRARY_PATH on Mac OS. 
 For instance, issue command: export LD_LIBRARY_PATH=... 
 Note: After Mac OS 10.11, using the DYLD_LIBRARY_PATH is impossible unless System Integrity Protection (SIP) is disabled. at (/paddle/paddle/fluid/platform/dynload/dynamic_loader.cc:177)

**Comment by tianshuo78520a** [comment]
请问你是使用cpu还是gpu版本报的错？
你的cuda环境是9.2 安装cuda10使用上会报错

**Comment by tianshuo78520a** [comment]
echo $LD_LIBRARY_PATH 看下你的libcublas.so 文件是否在这个环境变量中
