### ISSUE TITLE
2.0 RC 中文API文档中，paddle.nn.AdaptiveMaxPool2D链接无效

### ISSUE THREAD

**Issue by unseenme** [PaddlePaddle/Paddle#28627]
在这个页面中：
https://www.paddlepaddle.org.cn/documentation/docs/zh/2.0-rc/api/index_cn.html

左边的列表中可以看到AdaptiveMaxPool2D。
但是打不来相关内容。

**Comment by vslyu** [comment]
> AdaptiveMaxPool2D

收到你的反馈，感谢你的发现，我们会尽快修复文档这个这个bug～
您可以先在源码处查看API的example：https://github.com/PaddlePaddle/Paddle/blob/release/2.0-rc/python/paddle/nn/layer/pooling.py#L919-L983

**Comment by luotao1** [comment]
https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/nn/AdaptiveMaxPool2D_cn.html 最新已经修复了。
