### ISSUE TITLE
小建议，为paddle.summary添加直接输入

### ISSUE THREAD

**Issue by HighCWu** [PaddlePaddle/Paddle#28620]
- 版本、环境信息
1）PaddlePaddle版本：2.0rc0
- 建议描述：

当前版本paddle.summary允许填写shape大小，但不支持直接输入Tensor以及其它符号，建议增加类似于args、kwargs之类的传参。我查看源码时也观察到函数实现中还是用shape生成了Tensor，直接输入Tensor也应该被允许。

建议用例:

```python
paddle.summary(net, paddle.randn([4,3,128,128]), use_something=True)
```

或者:

```python
paddle.summary(net, args={'input': paddle.randn([4,3,128,128]), 'use_something': True})
```

其中`use_something`为模型forward过程中进行条件分支的参数。

**Comment by LielinJiang** [comment]
感谢您的建议。这方面我们评估一下
