### ISSUE TITLE
paddle.vision.ImageFolder() 使用pillow作为backend的时候，报错

### ISSUE THREAD

**Issue by habout632** [PaddlePaddle/Paddle#28623]
paddle.vision.ImageFolder() 使用pillow作为backend的时候，报错
提示　unknown data type PIl.Image.Image

我换成cv2就好了
set_image_backend('cv2')

dataloader加载图片出来的tensor是
data type uint8 
data format nhwc
这两个是不是可以直接一步到位　在ImageFolder里面直接转成float32 nchw返回呢？

**Comment by LielinJiang** [comment]
这个image folder是返回图片格式的数据，如果您需要神经网络的数据，可以手动添加需要的transform。
