### ISSUE TITLE
2.0 RC 中文API文档中，找不到paddle.nn.MaxPool2D

### ISSUE THREAD

**Issue by unseenme** [PaddlePaddle/Paddle#28626]
左边的列表中也找不到。
用右上角的搜索也找不到。

**Comment by vslyu** [comment]
收到你的反馈，感谢你的发现，我们会尽快修复文档这个这个bug～
您可以先在源码处查看paddle.nn.MaxPool2D   API的example：https://github.com/PaddlePaddle/Paddle/blob/release/2.0-rc/python/paddle/nn/layer/pooling.py#L414-L480

**Comment by luotao1** [comment]
https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/nn/MaxPool2D_cn.html 最新已经修复了
