### ISSUE TITLE
paddle 和 CUDA 10.2 兼容问题

### ISSUE THREAD

**Issue by Echo0117** [PaddlePaddle/Paddle#28628]
请问一下 paddle 2.0 rc 是支持 cuda 10.2 的话，那 paddle 1.8 还会更新能支持 cuda 10.2 的版本吗，有的话大概是什么时候呢？
还有就是 paddle 2.0 的稳定版大概什么时候出呀～

**Comment by pangyoki** [comment]
目前 paddle 1.8 还没有计划支持 cuda 10.2 ，我们会收集用户需求，后续持续跟进。请问你这边有什么需求吗？
paddle 2.0稳定版计划在12月中旬发布，到时候请关注。

**Comment by Echo0117** [comment]
嗯嗯我们也是希望能尽量都兼容的。
对了，问一下这里说的 GPU 运算能力是怎么评分的呀，跟下图 NVIDA 网站上给他们不同机型 GPU 的计算能力评分是一个吗
[image: image.png]
[image: image.png]

pangyoki <notifications@github.com> 于2020年11月15日周日 下午2:47写道：

**Comment by pangyoki** [comment]
图片没显示出来，麻烦重新发一下

**Comment by Echo0117** [comment]
这样可以看到吗，放到附件里了

pangyoki <notifications@github.com> 于2020年11月16日周一 上午10:54写道：

**Comment by pangyoki** [comment]
还是没看到，你试试复制图片后直接粘贴到对话框里可以吗？

**Comment by Echo0117** [comment]
我直接把图片里的文字也复制过来了，您看一下～
选择CPU/GPU

   -

   如果您的计算机没有 NVIDIA® GPU，请编译CPU版的PaddlePaddle
   -

   如果您的计算机有NVIDIA® GPU，并且满足以下条件，推荐编译GPU版的PaddlePaddle
   - CUDA 工具包 9.0/10.0/10.1/10.2 配合 cuDNN v7.6.5+
      - GPU运算能力超过3.0的硬件设备


NVIDIA Data Center Products
<https://www.nvidia.com/en-us/data-center/products/>
GPUCompute Capability
NVIDIA A100 <https://www.nvidia.com/en-us/data-center/a100/> 8.0
NVIDIA T4 <https://www.nvidia.com/en-us/data-center/tesla-t4/> 7.5
NVIDIA V100 <https://www.nvidia.com/en-us/data-center/tesla-v100/> 7.0
Tesla P100 <http://www.nvidia.com/object/tesla-p100.html> 6.0
Tesla P40 <http://www.nvidia.com/object/accelerate-inference.html> 6.1
Tesla P4 <http://www.nvidia.com/object/accelerate-inference.html> 6.1



[image: image.png]
[image: image.png]

pangyoki <notifications@github.com> 于2020年11月16日周一 上午11:05写道：

**Comment by pangyoki** [comment]
您这里给出的Paddle的运算能力的定义与nvidia给出的Compute Capability是一致的。

**Comment by pangyoki** [comment]
您这里给出的Paddle提示中GPU运算能力的定义与nvidia给出的Compute Capability是一致的。

**Comment by Echo0117** [comment]
嗯嗯好的，那就是 nvidia GeForce 系列的个人显卡也是可以支持 paddle 的哈

pangyoki <notifications@github.com> 于2020年11月16日周一 上午11:42写道：

**Comment by pangyoki** [comment]
嗯嗯是的

**Comment by Echo0117** [comment]
嗨，我想再请问一下 paddlehub 里的 bert 模型能支持 TensorRT 6 的预测吗～
官网上好像没有教程，网上找到的也都是 C++ 写的

pangyoki <notifications@github.com> 于2020年11月16日周一 下午12:20写道：
