### ISSUE TITLE
paddle.vision.DatasetFolder提示不支持图片格式

### ISSUE THREAD

**Issue by habout632** [PaddlePaddle/Paddle#28624]
![Screenshot from 2020-11-14 15-50-54](https://user-images.githubusercontent.com/3166070/99142600-7fbae400-2691-11eb-82b9-4df7f23f699c.png)
　但是目录下明明是有的

**Comment by habout632** [comment]
使用ImageFolder 就没有这个问题

**Comment by habout632** [comment]
提示信息　不太准确　'/data2/stargan_v1/hands/test/green'　是因为这个目录下　已经没有目录了　所以报错了　不是文件扩展名的问题

**Comment by vslyu** [comment]
麻烦能再提供更为详细的上下文信息吗？～paddle主框架里面并没有你图片中get_eval_loader的接口，这个函数是你这边自己封装的吗～

**Comment by LielinJiang** [comment]
感谢您的反馈，我们优化一下提示信息。
