### ISSUE TITLE
注释的文字拼写错误

### ISSUE THREAD

**Issue by habout632** [PaddlePaddle/Paddle#28625]
paddle.vision.folder.py
def has_valid_extension(filename, extensions):
    """Checks if a file is a vilid extension.
应该是valid extension

    Args:
        filename (str): path to a file
        extensions (tuple of str): extensions to consider (lowercase)

    Returns:
        bool: True if the filename ends with one of given extensions
    """
    return filename.lower().endswith(extensions)

**Comment by vslyu** [comment]
感谢您反馈的拼写错误，我们还在后续改进～

**Comment by vslyu** [comment]
建议您也可以自行修改并且Pull Request至paddle的develop分支中，我们欢迎您这样的忠实用户为paddle贡献力量

**Comment by LielinJiang** [comment]
感谢您的建议，我们马上修复一下
