### ISSUE TITLE
paddle.fluid.dygraph.BCELoss模块在AIstudio paddle2.0加载不了

### ISSUE THREAD

**Issue by wuyeyanjiuyuan** [PaddlePaddle/Paddle#28630]
![2 0加载BCELoss](https://user-images.githubusercontent.com/57974682/99180883-2fad5180-2765-11eb-9554-6316614503de.PNG)

希望官方能把BCELoss加载到平台上

**Comment by pangyoki** [comment]
> ![2 0加载BCELoss](https://user-images.githubusercontent.com/57974682/99180883-2fad5180-2765-11eb-9554-6316614503de.PNG)
> 
> 希望官方能把BCELoss加载到平台上

感谢反馈，试试 `from paddle.nn import BCELoss` 可以吗？

**Comment by wuyeyanjiuyuan** [comment]
> > ![2 0加载BCELoss](https://user-images.githubusercontent.com/57974682/99180883-2fad5180-2765-11eb-9554-6316614503de.PNG)
> > 希望官方能把BCELoss加载到平台上
> 
> 感谢反馈，试试`from paddle.nn import BCELoss`可以吗？

### **已解决**
谢谢帮助！原来`BCELoss`模块现在是挂在`paddle.nn`目录下面
![加载bceloss成功](https://user-images.githubusercontent.com/57974682/99181404-3e960300-2769-11eb-9daf-a5abc4a2cd8f.PNG)
等官方文档修改下文字说明就好了

**Comment by pangyoki** [comment]
> > > ![2 0加载BCELoss](https://user-images.githubusercontent.com/57974682/99180883-2fad5180-2765-11eb-9554-6316614503de.PNG)
> > > 希望官方能把BCELoss加载到平台上
> > 
> > 
> > 感谢反馈，试试`from paddle.nn import BCELoss`可以吗？
> 
> ### **已解决**
> 
> 谢谢帮助！原来`BCELoss`模块现在是挂在`paddle.nn`目录下面
> ![加载bceloss成功](https://user-images.githubusercontent.com/57974682/99181404-3e960300-2769-11eb-9daf-a5abc4a2cd8f.PNG)
> 等官方文档修改下文字说明就好了

是的。由于您使用的是paddle 2.0版本，官方文档也请参考2.0版本的api，或者develop版本文档。
<img width="1072" alt="图片" src="https://user-images.githubusercontent.com/26408901/99181976-d6e1b700-276c-11eb-8b0c-3d1b9f95b4cd.png">

**Comment by pangyoki** [comment]
是的。
由于您使用的是paddle 2.0版本，官方文档也请参考2.0版本的相关api，例如使用develop版本查询：
<img width="1072" alt="图片" src="https://user-images.githubusercontent.com/26408901/99181993-f24cc200-276c-11eb-934b-97fc0d508b62.png">
