### ISSUE TITLE
ERNIE模型在ai studio中重新pretrain的问题

### ISSUE THREAD

**Issue by luming159** [PaddlePaddle/Paddle#28634]
在百度的GPU环境中使用ERNIE模型
![image](https://user-images.githubusercontent.com/55949550/99202059-e43c8700-27e8-11eb-8daa-757aa078641f.png)

中运行pretrain的readme文件
![image](https://user-images.githubusercontent.com/55949550/99202070-edc5ef00-27e8-11eb-9272-bf91d3468784.png)

出现很多bug
首先是第一个制作预训练数据，需要的是paddlepaddle-gpu1.7的环境和paddle-propeller==0.3.1dev1以及paddle-ernie，说明文档中没有说明。
到运行下面开始预训练的时候需要热启的模型参数、字典、json文件也做好放在
![image](https://user-images.githubusercontent.com/55949550/99202082-f4ecfd00-27e8-11eb-9060-1bc5e87ba6f4.png)

最后还是报错
![image](https://user-images.githubusercontent.com/55949550/99202088-fb7b7480-27e8-11eb-9099-dc753844180b.png)

这个开始以为是版本问题因为在文档中只有1.8之后的版本中才有这个方法属性。
但是改了1.8的版本也不行，应该是上面的返回值有问题。
![image](https://user-images.githubusercontent.com/55949550/99202100-07ffcd00-27e9-11eb-8d0b-f37eeaf7cfba.png)

请问到底怎么才能在baidu的环境里自己重新预训练模型呢？打扰了！

**Comment by Meiyim** [comment]
nrank问题见这个issue. https://github.com/PaddlePaddle/ERNIE/issues/477
因为paddle更新太快，这个pretrain脚本只在paddle 1.7上完成过测试。后续这个repo会更新到paddle2.0
