### ISSUE TITLE
2.0 中如何使用 Lod Tensor

### ISSUE THREAD

**Issue by cheerser** [PaddlePaddle/Paddle#28632]
在文档看到，`基于 2.0 的开发任务，请使用 paddle 目录下的 API，不要再使用 paddle.fluid 目录下的 API。`请问，Lod Tensor是不是要废弃了？如果要废弃，则希望可以保留这一独特且优秀的功能。如果不废弃，则希望给出具体的一些新版API用法。

**Comment by pangyoki** [comment]
感谢您的反馈。
Paddle 2.0是兼容性升级，`paddle.fluid`下的API仍然可以使用，只是更推荐使用`paddle`目录下的API。
`Lod Tensor`没有废弃，现在仍然可以通过`paddle.fluid.LoDTensor`使用。
目前2.0暂时还没有在paddle目录下实现`Lod Tensor`，后续会展开支持，谢谢。

**Comment by cheerser** [comment]
很期待后续！paddle加油

**Comment by pangyoki** [comment]
谢谢支持~
