### ISSUE TITLE
PaddleSeg提供的分割模型准确率问题

### ISSUE THREAD

**Issue by lyn1225** [PaddlePaddle/Paddle#28650]
根据官方提供的PaddleSeg代码，使用PSPNet在Cityscapes数据集上进行训练（只使用train），预训练模型是官方提供的resnet101_v2_pspnet。因为是在ai studio上进行训练，受限于GPU显存大小，batch_size只能设置为4，normalization为bn，
最终在val数据集上的mlou只能达到70.66。原始论文中的pspnet模型在cityscapes test数据集上的mlou是78.4，那么pspnet模型在val 数据集上的mlou应该要大于这个数字。虽然我的batch_size是4，与论文中设置的16有一定差距，同时PaddleSeg代码中也没有提供Auxiliary Loss的实现方式，但是我想这两个因素所能影响的mlou差距应该不会达到7点几这么大吧？或者说是因为预训练模型的限制才导致较低的mlou？希望有关大佬给予解答。

**Comment by wuyefeilin** [comment]
> 根据官方提供的PaddleSeg代码，使用PSPNet在Cityscapes数据集上进行训练（只使用train），预训练模型是官方提供的resnet101_v2_pspnet。因为是在ai studio上进行训练，受限于GPU显存大小，batch_size只能设置为4，normalization为bn，
> 最终在val数据集上的mlou只能达到70.66。原始论文中的pspnet模型在cityscapes test数据集上的mlou是78.4，那么pspnet模型在val 数据集上的mlou应该要大于这个数字。虽然我的batch_size是4，与论文中设置的16有一定差距，同时PaddleSeg代码中也没有提供Auxiliary Loss的实现方式，但是我想这两个因素所能影响的mlou差距应该不会达到7点几这么大吧？或者说是因为预训练模型的限制才导致较低的mlou？希望有关大佬给予解答。

bs减少到4导致miou减少是正常的。你可以尝试减小学习率，让后增加训练轮数，这样miou应该会涨一些。

如果有更多的疑问可以到https://github.com/PaddlePaddle/PaddleSeg进行提问
