### ISSUE TITLE
nano上进行部署调用GPU报错

### ISSUE THREAD

**Issue by Fitz-Fitz** [PaddlePaddle/Paddle#28651]
- 版本、环境信息：
    1）PaddlePaddle版本：paddleinference编译好的paddlepaddle-gpu-0.0.0
    2）硬件版本：jetson nano
    3）系统环境：jetpack4.3 python3.6.9 cuda 10.0 cudnn7.6

在nano上跑自己模型的时候使用GPU报错如下：

W1115 15:58:03.358932 9830 device_context.cc:265] Please NOTE: device: 0, CUDA Capability: 53, Driver API Version: 10.0, Runtime API Version: 10.0
W1115 15:58:03.604619 9830 device_context.cc:273] device: 0, cuDNN Version: 7.6.
W1115 15:58:46.768879 9830 operator.cc:187] elementwise_mul raises an exception thrust::system::system_error, parallel_for failed: too many resources requested for launch
Traceback (most recent call last):
File "infer_yolov3.py", line 85, in
result = run(pred, [data, im_shape])
File "infer_yolov3.py", line 39, in run
predictor.zero_copy_run()
RuntimeError: parallel_for failed: too many resources requested for launch

若设置时设置不使用GPU则无问题

**Comment by cryoco** [comment]
您好，我们之前应该修复过类似您这种报错的问题，见[PR#25689](https://github.com/PaddlePaddle/Paddle/pull/25689)，麻烦确认下您使用的版本是否在这个修改之后哈，也可以直接下载最新的[jetson预测库](https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/guides/05_inference_deployment/inference/build_and_install_lib_cn.html#id1)看下是否还有该问题。

**Comment by Fitz-Fitz** [comment]
好的感谢您
顺便请问咱们paddle有提供编译好的修复后版本的whl包不

**Comment by cryoco** [comment]
> 好的感谢您
> 顺便请问咱们paddle有提供编译好的修复后版本的whl包不

目前还没有，我们计划在下一个版本（2.0-rc1）开始发布jetson上的预测whl包，大概在12月中旬哈

**Comment by Fitz-Fitz** [comment]
好嘞，感谢您

**Comment by Fitz-Fitz** [comment]
> > 好的感谢您
> > 顺便请问咱们paddle有提供编译好的修复后版本的whl包不
> 
> 目前还没有，我们计划在下一个版本（2.0-rc1）开始发布jetson上的预测whl包，大概在12月中旬哈

请问现在推出了不

**Comment by cryoco** [comment]
> > > 好的感谢您
> > > 顺便请问咱们paddle有提供编译好的修复后版本的whl包不
> > 
> > 
> > 目前还没有，我们计划在下一个版本（2.0-rc1）开始发布jetson上的预测whl包，大概在12月中旬哈
> 
> 请问现在推出了不

已经发布了哈
https://www.paddlepaddle.org.cn/documentation/docs/zh/2.0-rc1/install/Tables.html#whl-release

**Comment by Fitz-Fitz** [comment]
> > > > 好的感谢您
> > > > 顺便请问咱们paddle有提供编译好的修复后版本的whl包不
> > > 
> > > 
> > > 目前还没有，我们计划在下一个版本（2.0-rc1）开始发布jetson上的预测whl包，大概在12月中旬哈
> > 
> > 
> > 请问现在推出了不
> 
> 已经发布了哈
> https://www.paddlepaddle.org.cn/documentation/docs/zh/2.0-rc1/install/Tables.html#whl-release

感谢感谢！！！
请问本次提供的whl包有支持tensorRT不

**Comment by jiamingming-004** [comment]
你好，可以留个联系方式不？

**Comment by jiamingming-004** [comment]
> 

你好，可以留个邮箱，请教一些部署的细节不？
