### ISSUE TITLE
LNK2019:无法解析的外部符号 “public：void__cdecl paddle::ZeroCopyTensor::Reshape(...”

### ISSUE THREAD

**Issue by shuangyichen** [PaddlePaddle/Paddle#28662]
1）CommitID：a44085bed80d72296118f3e97516bef340baf3aa
    2）CPU：i5-6300U
    3）GPU：无
    4）系统环境：win10

-预测信息
    1）C++预测：GIT COMMIT ID: a44085bed80d72296118f3e97516bef340baf3aa
WITH_MKL: OFF
WITH_MKLDNN: OFF
WITH_GPU: OFF

    2）CMake包含路径的完整命令 下载的安装包，没有编译
    3）API信息（如调用请提供）
    4）预测库来源：官网下载
- 复现信息：如为报错，请给出复现环境、复现步骤
- 问题描述：请详细描述您的问题，同步贴出报错信息、日志/代码关键片段

```c++
#include "mainwindow.h"
#include "paddle_inference_api.h"
#include <QApplication>

//static const int height = 224;
//static const int width = 224;
//static const int channels = 3;
using namespace paddle;
void CreateConfig(paddle::AnalysisConfig* config, const std::string& model_dirname) {
  // 模型从磁盘进行加载
//  config->SetModel(model_dirname + "/model",
//                   model_dirname + "/params");
    config->SetModel(model_dirname + "/__model__",
                       model_dirname + "/__params__");
//   config->SetModel(model_dirname);
  // 如果模型从内存中加载，可以使用SetModelBuffer接口
  // config->SetModelBuffer(prog_buffer, prog_size, params_buffer, params_size);
  config->EnableUseGpu(100 /*设定GPU初始显存池为MB*/,  0 /*设定GPU ID为0*/); //开启GPU预测

  /* for cpu
  config->DisableGpu();
  config->EnableMKLDNN();   // 开启MKLDNN加速
  config->SetCpuMathLibraryNumThreads(10);
  */

  // 使用ZeroCopyTensor，此处必须设置为false
  config->SwitchUseFeedFetchOps(false);
  // 若输入为多个，此处必须设置为true
  config->SwitchSpecifyInputNames(true);
  config->SwitchIrDebug(true); 		// 可视化调试选项，若开启，则会在每个图优化过程后生成dot文件
  // config->SwitchIrOptim(false); 	// 默认为true。如果设置为false，关闭所有优化
  // config->EnableMemoryOptim(); 	// 开启内存/显存复用
}

void RunAnalysis(int batch_size, std::string model_dirname) {
  // 1. 创建AnalysisConfig
  paddle::AnalysisConfig config;
  CreateConfig(&config, model_dirname);

  // 2. 根据config 创建predictor，并准备输入数据，此处以全0数据为例
  auto predictor = CreatePaddlePredictor(config);
  int channels = 3;
  int height = 224;
  int width = 224;
  int all = channels*height*width;
//  float input[batch_size*channels*height*width];
  float *input  = new float[channels*height*width];

    for(int i=0;i<channels*height*width;i++)
    {
        input[i] = {0};
    }
//  float input[150528];
//  for(int i=0;i<150528;i++)
//  {
//      input[i] = {0};
//  }


  // 3. 创建输入
  // 使用了ZeroCopy接口，可以避免预测中多余的CPU copy，提升预测性能
  auto input_names = predictor->GetInputNames();
  auto input_t = predictor->GetInputTensor(input_names[0]);
  input_t->Reshape({batch_size, channels, height, width});
  input_t->copy_from_cpu(input);

  // 4. 运行预测引擎
//  CHECK(predictor->ZeroCopyRun());
  predictor->ZeroCopyRun();
  // 5. 获取输出
  std::vector<float> out_data;
  auto output_names = predictor->GetOutputNames();
  auto output_t = predictor->GetOutputTensor(output_names[0]);
  std::vector<int> output_shape = output_t->shape();
  int out_num = std::accumulate(output_shape.begin(), output_shape.end(), 1, std::multiplies<int>());

  out_data.resize(out_num);
  output_t->copy_to_cpu(out_data.data());
}


int main(int argc, char *argv[])
{
    QApplication a(argc, argv);
//    MainWindow w;
//    w.show();

//    paddle::RunAnalysis(1, "./mobilenet");
    RunAnalysis(1, "D:/Users/ThinkPad/paddlex_workspace/P0002-T0003_export_model/inference_model");
    return a.exec();
}
```

报错：main.obj:-1: error: LNK2019: 无法解析的外部符号 "public: void __cdecl paddle::ZeroCopyTensor::Reshape(class std::vector<int,class std::allocator<int> > const &)" (?Reshape@ZeroCopyTensor@paddle@@QEAAXAEBV?$vector@HV?$allocator@H@std@@@std@@@Z)，该符号在函数 "void __cdecl RunAnalysis(int,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >)" (?RunAnalysis@@YAXHV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z) 中被引用

感觉像是没有找到lib
但在Qt pro文件中已经引用

`INCLUDEPATH += C:/Users/ThinkPad/Downloads/fluid_inference_install_dir_1/fluid_inference_install_dir/paddle/include
LIBS +=$$quote(-LD:/Users/ThinkPad/Paddle/build/paddle_inference_install_dir/paddle/lib)`

**Comment by jiweibo** [comment]
linux下要加上-lpaddle_fluid -L./paddle_inference_install_dir/paddle/lib 这两个才可以正确引用，windows上应该一致，显示加上libpaddle_fluid.dll试一下？

**Comment by shuangyichen** [comment]
> linux下要加上-lpaddle_fluid -L./paddle_inference_install_dir/paddle/lib 这两个才可以正确引用，windows上应该一致，显示加上libpaddle_fluid.dll试一下？

`INCLUDEPATH += C:/Users/ThinkPad/Downloads/fluid_inference_install_dir_1/fluid_inference_install_dir/paddle/include
LIBS +=$$quote(-LC:/Users/ThinkPad/Downloads/fluid_inference_install_dir_1/fluid_inference_install_dir/paddle/lib/libpaddle_fluid.lib)
INCLUDEPATH += C:/Users/ThinkPad/Downloads/fluid_inference_install_dir_1/fluid_inference_install_dir/paddle/lib/paddle_fluid.dll`

加了 仍然报同样的错 我下下来的包里只有paddle_fluid.dll没有ibpaddle_fluid.dll

**Comment by smalie2222** [comment]
您好，请问您解决这个问题了吗
