### ISSUE TITLE
paddle Inference 使用时报错

### ISSUE THREAD

**Issue by Heuchler7** [PaddlePaddle/Paddle#28668]
使用aistudio的高级版环境进行预测，预测中使用gpu进行计算，之前使用load_inference_model 配合exe.run进行预测完全没有问题，结果准确。为优化预测速度改为paddle inference进行预测时出错， paddle inference 使用代码如下：
use_cuda = 1
#-------------------------------------------------------------
place = fluid.CUDAPlace(0) if use_cuda else fluid.CPUPlace()
exe = fluid.Executor(place)

def create_predictor(path):
    config = AnalysisConfig(path)
    config.switch_use_feed_fetch_ops(False)
    if use_cuda:
        config.enable_use_gpu(100, 0)  #用gpu预测时加入此参数
    else:
        config.cpu_math_library_num_threads(2)

    config.enable_mkldnn()
    config.enable_memory_optim()
    config.switch_ir_optim(False) #关闭模型图分析阶段的任何图优化
    predictor = create_paddle_predictor(config)
    return predictor

def run(predictor, data):
    input_names = predictor.get_input_names()
    for i, name in enumerate(input_names):
        input_tensor = predictor.get_input_tensor(name)
        input_tensor.reshape(data[i].shape)
        this_data = data[i].copy()
        input_tensor.copy_from_cpu(this_data)
    predictor.zero_copy_run()

    results = []
    output_names = predictor.get_output_names()
    for i, name in enumerate(output_names):
        output_tensor = predictor.get_output_names(name)
        output_data = output_tensor.copy_to_cpu()
        results.append(output_data)

    return results

报出错误如下：

Traceback (most recent call last):
  File "cuthold_noWE_evaluate.py", line 111, in <module>
    f1, recall, precision, use_time = evaluate(test_data, psPath = _psPath, osPath=_osPath, charsFile=charsFile, schemasFile=schemasFile, e_p=eva_params)
  File "cuthold_noWE_evaluate.py", line 56, in evaluate
    Psro = pre.predict(text)
  File "/home/aistudio/Inference.py", line 120, in predict
    result.append(self.extract_items(text))
  File "/home/aistudio/Inference.py", line 77, in extract_items
    results = run(self.Spredictor, T1input)
  File "/home/aistudio/Inference.py", line 38, in run
    predictor.zero_copy_run()
paddle.fluid.core_avx.EnforceNotMet: 

--------------------------------------------
C++ Call Stacks (More useful to developers):
--------------------------------------------
0   std::string paddle::platform::GetTraceBackString<std::string const&>(std::string const&, char const*, int)
1   paddle::platform::EnforceNotMet::EnforceNotMet(std::string const&, char const*, int)
2   paddle::operators::UnsqueezeOp::GetOutputShape(std::vector<int, std::allocator<int> >, paddle::framework::DDim const&)
3   paddle::operators::UnsqueezeOp::InferShape(paddle::framework::InferShapeContext*) const
4   paddle::operators::Unsqueeze2Op::InferShape(paddle::framework::InferShapeContext*) const
5   paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, paddle::platform::Place const&, paddle::framework::RuntimeContext*) const
6   paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, paddle::platform::Place const&) const
7   paddle::framework::OperatorBase::Run(paddle::framework::Scope const&, paddle::platform::Place const&)
8   paddle::framework::NaiveExecutor::Run()
9   paddle::AnalysisPredictor::ZeroCopyRun()

------------------------------------------
Python Call Stacks (More useful to users):
------------------------------------------
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/framework.py", line 2525, in append_op
    attrs=kwargs.get("attrs", None))
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/layer_helper.py", line 43, in append_op
    return self.main_program.current_block().append_op(*args, **kwargs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/layers/nn.py", line 5818, in unsqueeze
    "XShape": x_shape})
  File "/home/aistudio/model.py", line 46, in made_mask
    x = layers.unsqueeze(x, axes=2)
  File "/home/aistudio/model.py", line 240, in student_model
    mask = made_mask(t1_in)
  File "JointTrainner.py", line 39, in <module>
    ls1, ls2, lo1, lo2, ps1, ps2, po1, po2, mask = student_model(cfg=cfg)

----------------------
Error Message Summary:
----------------------
Error: An error occurred here. There is no accurate error hint for this error yet. We are continuously in the process of increasing hint for this kind of error check. It would be helpful if you could inform us of how this conversion went by opening a github issue. And we will resolve it with high priority.
  - New issue link: https://github.com/PaddlePaddle/Paddle/issues/new
  - Recommended issue content: all error stack information
  [Hint: Expected cur <= cur_output_size, but received cur:2 > cur_output_size:1.] at (/paddle/paddle/fluid/operators/unsqueeze_op.cc:89)
  [operator < unsqueeze2 > error]

**Comment by jiweibo** [comment]
请问下预测库的版本和训练的版本一致吗？

**Comment by Heuchler7** [comment]
我们没有特意安装inference库，选择的训练版本是1.7.2，以为二者是捆绑安装的

**Comment by jiweibo** [comment]
感觉应该是版本问题，新版本应该修复了。一个临时的解决办法，能否把unsqueeze的axis从负数调为正数，这样应该能规避这个问题吧，可以试一下。

**Comment by Heuchler7** [comment]
x = layers.unsqueeze(x, axes=2)这一句里报错
我们现在报错的地方给的是正数的axis,如果是版本问题我们可以手动安装相对应1.7.2paddle合适的Inference版本么？

**Comment by Heuchler7** [comment]
不对，我们好像应用环境只能用跟1.7.2paddle一起装上去的Inference版本，在这种情况下有办法解决这个问题吗？

**Comment by jiweibo** [comment]
https://github.com/PaddlePaddle/Paddle/blob/v1.7.2/paddle/fluid/operators/unsqueeze_op.cc#L89

看样子是这里挂了，看样子，输入x的shape是一维的，这是不是不符合预期啊

**Comment by Heuchler7** [comment]
嗯嗯，谢谢您，我先仔细看下，这里在预测时预期进去unsqueeze的是一个shape为（1，文本长度）的tensor, 想升维成（1，文本长度，1）

**Comment by Heuchler7** [comment]
刚才仔细研读了下这个算子的cc代码还有我们自己的模型，这里输入应该是符合预期的。主要很奇怪的是之前使用load_inference_model做预测是没有问题的， 照理来说调用的应该都是这个算子，为什么现在在Inference内就跑不了了呢？

**Comment by jiweibo** [comment]
设置环境变量，export GLOG_v=4，能够打印每一层的输出shape，方便调试

**Comment by Heuchler7** [comment]
好的，Thanks♪(･ω･)ﾉ，我去输出看看

**Comment by Heuchler7** [comment]
I1117 14:18:13.536463  1717 naive_executor.cc:105] ---  skip [feed], feed -> K1
I1117 14:18:13.536470  1717 naive_executor.cc:105] ---  skip [feed], feed -> T1
I1117 14:18:13.537283  1717 naive_executor.cc:105] ---  skip [my_po1.tmp_2], fetch -> fetch
I1117 14:18:13.537302  1717 naive_executor.cc:105] ---  skip [my_po2.tmp_2], fetch -> fetch
I1117 14:18:13.537308  1717 scope.cc:169] Create variable feed
I1117 14:18:13.537320  1717 scope.cc:169] Create variable fetch
I1117 14:18:13.541802  1717 auto_growth_best_fit_allocator.cc:97] Not found and reallocate 5888, and remaining 256
I1117 14:18:13.542131  1717 dynamic_loader.cc:94] Try to find library: libcublas.so from default system path.
W1117 14:18:13.862568  1717 device_context.cc:237] Please NOTE: device: 0, CUDA Capability: 70, Driver API Version: 10.1, Runtime API Version: 9.0
I1117 14:18:13.862640  1717 dynamic_loader.cc:94] Try to find library: libcudnn.so from default system path.
W1117 14:18:13.867228  1717 device_context.cc:245] device: 0, cuDNN Version: 7.3.
W1117 14:18:15.507689  1717 naive_executor.cc:45] The NaiveExecutor can not work properly if the cmake flag ON_INFER is not set.
W1117 14:18:15.507743  1717 naive_executor.cc:47] Unlike the training phase, all the scopes and variables will be reused to save the allocation overhead.
W1117 14:18:15.507756  1717 naive_executor.cc:50] Please re-compile the inference library by setting the cmake flag ON_INFER=ON if you are running Paddle Inference
I1117 14:18:15.507822  1717 naive_executor.cc:55] 140500864571136 run Op(unsqueeze2), inputs:{AxesTensor[], AxesTensorList[], X[T1:int64_t[700]({})]}, outputs:{Out[unsqueeze2_0.tmp_0:[0]({})], XShape[unsqueeze2_0.tmp_1:[0]({})]}. on scope 0x5572f3eb27c0
I1117 14:18:15.507838  1717 operator.cc:159] CUDAPlace(0) Op(unsqueeze2), inputs:{AxesTensor[], AxesTensorList[], X[T1:int64_t[700]({})]}, outputs:{Out[unsqueeze2_0.tmp_0:[0]({})], XShape[unsqueeze2_0.tmp_1:[0]({})]}.
I1117 14:18:15.507870  1717 operator.cc:1050] expected_kernel_key:data_type[int64_t]:data_layout[ANY_LAYOUT]:place[CUDAPlace(0)]:library_type[PLAIN]
Traceback (most recent call last):
  File "cuthold_noWE_evaluate.py", line 111, in <module>
    f1, recall, precision, use_time = evaluate(test_data, psPath = _psPath, osPath=_osPath, charsFile=charsFile, schemasFile=schemasFile, e_p=eva_params)
  File "cuthold_noWE_evaluate.py", line 56, in evaluate
    Psro = pre.predict(text)
  File "/home/aistudio/distill700NWE8headsWithSoft/cuthold_noWE_SubmitForEInference.py", line 120, in predict
    result.append(self.extract_items(text))
  File "/home/aistudio/distill700NWE8headsWithSoft/cuthold_noWE_SubmitForEInference.py", line 77, in extract_items
    results = run(self.Spredictor, T1input)
  File "/home/aistudio/distill700NWE8headsWithSoft/cuthold_noWE_SubmitForEInference.py", line 38, in run
    predictor.zero_copy_run()
paddle.fluid.core_avx.EnforceNotMet: 

这个是因为cmake那个flag没有设置的原因吗？刚打印看了下报错

**Comment by jiweibo** [comment]
我理解和这个ON_INFER option应该是没关系的。

预测过程中比较奇怪的地方是，根据你的描述，x的shape是[1, 文本长度]，这样的话 cur_output_size 应该是2的，但是报错显示是1，怀疑是上一层的结果出现了错误。

**Comment by Heuchler7** [comment]
这边在创建config时设置config.switch_use_feed_fetch_ops(False)用于显式地在模型运行的时候删去feed和fetchops, 后面运行时也是采用的predictor.zero_copy_run(), 之后进网后第一步运算就是这里的unsqueeze了，前面照这么说是没有上一层的。

**Comment by jiweibo** [comment]
input_tensor.reshape(data[i].shape)

data[i].shape 的维度匹配吗？

**Comment by Heuchler7** [comment]
找到了，是输入时维度忘了维护，data[i]自动给我们的网络输入降了维，现在终于不报这个错误了。谢谢您！新的问题我们先找找基本问题看看是不是类似这种小问题
