### ISSUE TITLE
安装2.0rc版本paddlepaddle速度过慢

### ISSUE THREAD

**Issue by vslyu** [PaddlePaddle/Paddle#28661]
按照官网安装说明文档https://www.paddlepaddle.org.cn/install/quick/zh/2.0rc-linux-pip，
安装指令：
```python -m pip install paddlepaddle-gpu==2.0.0rc0.post101 -f https://paddlepaddle.org.cn/whl/stable.html```
下载速度超级慢，希望优化下缓存节点
![image](https://user-images.githubusercontent.com/12137504/99256116-dc63fd80-284f-11eb-98c4-90b0ae97527d.png)

**Comment by wanghuancoder** [comment]
@vslyu 感谢您的建议！我们将尽快排查相关业务，进行优化~
