### ISSUE TITLE
unique_op.cu(181): error : identifier "range" is undefined

### ISSUE THREAD

**Issue by xazeng** [PaddlePaddle/Paddle#28664]
vs2015 编译推测库，出现错误如下：

1>  F:\Project\Paddle\build\paddle\fluid\operators>"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.1\bin\nvcc.exe" -gencode=arch=compute_30,code=\"sm_30,compute_30\" -gencode=arch=compute_35,code=\"sm_35,compute_35\" -gencode=arch=compute_50,code=\"sm_50,compute_50\" -gencode=arch=compute_52,code=\"sm_52,compute_52\" -gencode=arch=compute_60,code=\"sm_60,compute_60\" -gencode=arch=compute_61,code=\"sm_61,compute_61\" -gencode=arch=compute_70,code=\"sm_70,compute_70\" -gencode=arch=compute_75,code=\"sm_75,compute_75\" --use-local-env --cl-version 2015 -ccbin "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\x86_amd64" -x cu  -IF:\Project\Paddle\build -IF:\Project\Paddle\paddle\fluid\framework\io -IF:\Project\Paddle\build\third_party\install\zlib\include -IF:\Project\Paddle\build\third_party\install -IF:\Project\Paddle\build\third_party\install\gflags\include -IF:\Project\Paddle\build\third_party\install\glog\include -IF:\Project\Paddle\build\third_party\boost\src\extern_boost -IF:\Project\Paddle\build\third_party\eigen3\src\extern_eigen3 -IF:\Project\Paddle\build\third_party\threadpool\src\extern_threadpool -IF:\Project\Paddle\build\third_party\dlpack\src\extern_dlpack\include -IF:\Project\Paddle\build\third_party\install\xxhash\include -IF:\Project\Paddle\build\third_party\install\warpctc\include -IF:\Project\Paddle\build\third_party\install\mklml\include -IF:\Project\Paddle\build\third_party\install\protobuf\include -IC:\Users\ZEN\AppData\Local\Programs\Python\Python38\include -I"C:\Users\ZEN\AppData\Local\Programs\Python\Python38\Lib\site-packages\numpy\core\include" -IF:\Project\Paddle\build\third_party\pybind\src\extern_pybind\include -IF:\Project\Paddle\build\third_party\cub\src\extern_cub -IF:\Project\Paddle\build\third_party\install\cryptopp\include -IC:\tools\cuda\include -I"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.1\include" -IF:\Project\Paddle -IF:\Project\Paddle\build\..\paddle\fluid\framework\io -I"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.1\include"     --keep-dir x64\RelWithDebInfo -maxrregcount=0  --machine 64 --compile -cudart static -w --expt-relaxed-constexpr -O2 -std=c++14 -Xcompiler="/EHsc /wd4244 /wd4267 /wd4819 /bigobj /arch:AVX" -g   -D_WINDOWS -D_MWAITXINTRIN_H_INCLUDED -D__STRICT_ANSI__ -DNDEBUG -DGOOGLE_GLOG_DLL_DECL= -D"CUDA_VERSION_MAJOR=\"10\"" -D"CUDA_VERSION_MINOR=\"1\"" -D"CUDA_TOOLKIT_ROOT_DIR=\"C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.1\"" -D"CUDNN_MAJOR_VERSION=\"7\"" -DPADDLE_WITH_MKLML -DLAPACK_FOUND -DPADDLE_VERSION=0.0.0 -DPADDLE_VERSION_INTEGER=0 -DPADDLE_DISABLE_PROFILER -DPADDLE_WITH_AVX -D_XKEYCHECK_H -DPADDLE_DLL_INFERENCE -DPADDLE_WITH_CUDA -DEIGEN_USE_GPU -DPADDLE_ON_INFERENCE -DPADDLE_WITH_CRYPTO -D"CMAKE_INTDIR=\"RelWithDebInfo\"" -DWIN32 -D_WINDOWS -DNDEBUG -DGOOGLE_GLOG_DLL_DECL= -D"CUDA_VERSION_MAJOR=\"10\"" -D"CUDA_VERSION_MINOR=\"1\"" -D"CUDA_TOOLKIT_ROOT_DIR=\"C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.1\"" -D"CUDNN_MAJOR_VERSION=\"7\"" -DPADDLE_WITH_MKLML -DLAPACK_FOUND -DPADDLE_VERSION=0.0.0 -DPADDLE_VERSION_INTEGER=0 -DPADDLE_DISABLE_PROFILER -DPADDLE_WITH_AVX -D_XKEYCHECK_H -DPADDLE_DLL_INFERENCE -DPADDLE_WITH_CUDA -DEIGEN_USE_GPU -DPADDLE_ON_INFERENCE -DPADDLE_WITH_CRYPTO -D"CMAKE_INTDIR=\"RelWithDebInfo\"" -D_MBCS -Xcompiler "/EHsc /W0 /nologo /O2 /FS  /MT /GR" -o unique_op.dir\RelWithDebInfo\/unique_op.cu.obj "F:\Project\Paddle\paddle\fluid\operators\unique_op.cu"
1>F:/Project/Paddle/paddle/fluid/operators/unique_op.cu(181): error : identifier "range" is undefined
1>            detected during:
1>              instantiation of "void paddle::operators::UniqueFlattendCUDATensor<InT,IndexT,equal_T,not_equal_T>(const paddle::framework::ExecutionContext &, const paddle::operators::Tensor &, paddle::operators::Tensor *, __nv_bool, __nv_bool, __nv_bool, equal_T, not_equal_T, int64_t) [with InT=float, IndexT=int, equal_T=thrust::equal_to<float>, not_equal_T=thrust::not_equal_to<float>]"
1>  (386): here
1>              instantiation of "void paddle::operators::UniqueFlattendCUDAFunctor<DeviceContext, InT>::apply<IndexT>() const [with DeviceContext=paddle::platform::CUDADeviceContext, InT=float, IndexT=int]"
1>  F:\Project\Paddle\paddle/fluid/framework/data_type.h(125): here
1>              instantiation of "void paddle::framework::VisitDataTypeTiny(paddle::framework::proto::VarType::Type, Visitor) [with Visitor=paddle::operators::UniqueFlattendCUDAFunctor<paddle::platform::CUDADeviceContext, float>]"
1>  (450): here
1>              instantiation of "void paddle::operators::UniqueKernel<paddle::platform::CUDADeviceContext, InT>::Compute(const paddle::framework::ExecutionContext &) const [with InT=float]"
1>  F:\Project\Paddle\paddle/fluid/framework/op_registry.h(140): here
1>              implicit generation of "paddle::operators::UniqueKernel<paddle::platform::CUDADeviceContext, InT>::~UniqueKernel() [with InT=float]"
1>  F:\Project\Paddle\paddle/fluid/framework/op_registry.h(140): here
1>              instantiation of class "paddle::operators::UniqueKernel<paddle::platform::CUDADeviceContext, InT> [with InT=float]"
1>  F:\Project\Paddle\paddle/fluid/framework/op_registry.h(140): here
1>              implicit generation of "paddle::operators::UniqueKernel<paddle::platform::CUDADeviceContext, InT>::UniqueKernel() [with InT=float]"
1>  F:\Project\Paddle\paddle/fluid/framework/op_registry.h(140): here
1>              instantiation of class "paddle::operators::UniqueKernel<paddle::platform::CUDADeviceContext, InT> [with InT=float]"
1>  F:\Project\Paddle\paddle/fluid/framework/op_registry.h(140): here
1>              instantiation of "void paddle::framework::OpKernelRegistrarFunctor<PlaceType, false, I, KernelTypes...>::operator()(const char *, const char *, int) const [with PlaceType=paddle::platform::CUDAPlace, I=0ULL, KernelTypes=<paddle::operators::UniqueKernel<paddle::platform::CUDADeviceContext, float>, paddle::operators::UniqueKernel<paddle::platform::CUDADeviceContext, double>, paddle::operators::UniqueKernel<paddle::platform::CUDADeviceContext, int32_t>, paddle::operators::UniqueKernel<paddle::platform::CUDADeviceContext, int64_t>>]"
1>  F:\Project\Paddle\paddle/fluid/framework/op_registry.h(163): here
1>              instantiation of "paddle::framework::OpKernelRegistrar<PlaceType, KernelType...>::OpKernelRegistrar(const char *, const char *, int) [with PlaceType=paddle::platform::CUDAPlace, KernelType=<paddle::operators::UniqueKernel<paddle::platform::CUDADeviceContext, float>, paddle::operators::UniqueKernel<paddle::platform::CUDADeviceContext, double>, paddle::operators::UniqueKernel<paddle::platform::CUDADeviceContext, int32_t>, paddle::operators::UniqueKernel<paddle::platform::CUDADeviceContext, int64_t>>]"
1>  (467): here
1>
1>F:/Project/Paddle/paddle/fluid/operators/unique_op.cu(182): error : type name is not allowed
1>            detected during:
1>              instantiation of "void paddle::operators::UniqueFlattendCUDATensor<InT,IndexT,equal_T,not_equal_T>(const paddle::framework::ExecutionContext &, const paddle::operators::Tensor &, paddle::operators::Tensor *, __nv_bool, __nv_bool, __nv_bool, equal_T, not_equal_T, int64_t) [with InT=float, IndexT=int, equal_T=thrust::equal_to<float>, not_equal_T=thrust::not_equal_to<float>]"
1>  (386): here
1>              instantiation of "void paddle::operators::UniqueFlattendCUDAFunctor<DeviceContext, InT>::apply<IndexT>() const [with DeviceContext=paddle::platform::CUDADeviceContext, InT=float, IndexT=int]"
1>  F:\Project\Paddle\paddle/fluid/framework/data_type.h(125): here
1>              instantiation of "void paddle::framework::VisitDataTypeTiny(paddle::framework::proto::VarType::Type, Visitor) [with Visitor=paddle::operators::UniqueFlattendCUDAFunctor<paddle::platform::CUDADeviceContext, float>]"
1>  (450): here
1>              instantiation of "void paddle::operators::UniqueKernel<paddle::platform::CUDADeviceContext, InT>::Compute(const paddle::framework::ExecutionContext &) const [with InT=float]"
1>  F:\Project\Paddle\paddle/fluid/framework/op_registry.h(140): here
1>              implicit generation of "paddle::operators::UniqueKernel<paddle::platform::CUDADeviceContext, InT>::~UniqueKernel() [with InT=float]"
1>  F:\Project\Paddle\paddle/fluid/framework/op_registry.h(140): here
1>              instantiation of class "paddle::operators::UniqueKernel<paddle::platform::CUDADeviceContext, InT> [with InT=float]"
1>  F:\Project\Paddle\paddle/fluid/framework/op_registry.h(140): here
1>              implicit generation of "paddle::operators::UniqueKernel<paddle::platform::CUDADeviceContext, InT>::UniqueKernel() [with InT=float]"
1>  F:\Project\Paddle\paddle/fluid/framework/op_registry.h(140): here
1>              instantiation of class "paddle::operators::UniqueKernel<paddle::platform::CUDADeviceContext, InT> [with InT=float]"
1>  F:\Project\Paddle\paddle/fluid/framework/op_registry.h(140): here
1>              instantiation of "void paddle::framework::OpKernelRegistrarFunctor<PlaceType, false, I, KernelTypes...>::operator()(const char *, const char *, int) const [with PlaceType=paddle::platform::CUDAPlace, I=0ULL, KernelTypes=<paddle::operators::UniqueKernel<paddle::platform::CUDADeviceContext, float>, paddle::operators::UniqueKernel<paddle::platform::CUDADeviceContext, double>, paddle::operators::UniqueKernel<paddle::platform::CUDADeviceContext, int32_t>, paddle::operators::UniqueKernel<paddle::platform::CUDADeviceContext, int64_t>>]"
1>  F:\Project\Paddle\paddle/fluid/framework/op_registry.h(163): here
1>              instantiation of "paddle::framework::OpKernelRegistrar<PlaceType, KernelType...>::OpKernelRegistrar(const char *, const char *, int) [with PlaceType=paddle::platform::CUDAPlace, KernelType=<paddle::operators::UniqueKernel<paddle::platform::CUDADeviceContext, float>, paddle::operators::UniqueKernel<paddle::platform::CUDADeviceContext, double>, paddle::operators::UniqueKernel<paddle::platform::CUDADeviceContext, int32_t>, paddle::operators::UniqueKernel<paddle::platform::CUDADeviceContext, int64_t>>]"
1>  (467): here
1>
1>F:/Project/Paddle/paddle/fluid/operators/unique_op.cu(181): error : identifier "range" is undefined
1>            detected during:

**Comment by jiweibo** [comment]
请尝试切换到tag 2.0rc之后编译，我看了下现在的代码里没有Unique_op.cu文件

**Comment by xazeng** [comment]
@jiweibo 从 release/2.0rc 切到  tag2.0rc 后，还是有 unique_op.cu 这个文件
![image](https://user-images.githubusercontent.com/3202516/99350794-285b8480-28da-11eb-91b8-2c66f41e0820.png)

**Comment by jiweibo** [comment]
获取最新看到了这个op，windows ci测试都正常，看了下unique_op中报错的地方，没发现奇怪的地方。怀疑是环境的问题，要不先试下1.8.5tag能否编过？

**Comment by xazeng** [comment]
谢谢
1.8.5tag 编过也没有意义。
两台机器，都是 cuda10.1，一台gtx1050ti，一台 gtx2060s，驱动都更新了，cudnn_version=7650，python3.8，vs2015
编译都提示这个错误
