### ISSUE TITLE
建议paddle onehot增加稀疏能力

### ISSUE THREAD

**Issue by tz28** [PaddlePaddle/Paddle#28671]
欢迎您对PaddlePaddle提出建议，非常感谢您对PaddlePaddle的贡献！
在留下您的建议时，辛苦您同步提供如下信息：

- 建议描述：背景：目前有很多场景采用onehot离散特征+LR模型的模式。之所以采用onehot肯定线上考虑没法embedding。而目

**Comment by Joejiong** [comment]
你好已经反馈

**Comment by Joejiong** [comment]
好的，可以将您的建议写的详细一点，谢谢

**Comment by tz28** [comment]
> 好的，可以将您的建议写的详细一点，谢谢

**背景描述**：因为线上原因无法使用embedding+everything的模式，只能采用简单的onehot+LR模式。但是如果一个离散特征取值个数为百万级，那么如果使用onehot将会把该特征扩展为百万维度，这个维度内存上是吃不消的。
**建议：**因为onehot只有一个位置为1，其他都0，也就是说是非常稀疏的。这部分是可以优化的节省存储空间。像我厂之前的BML和pulsar等机器学习框架均是支持onehot稀疏的。也就是无论你特征取值个数多少，bml和pulsar上使用onehot完全不会出现像paddle那样的内存爆炸。

**Comment by Joejiong** [comment]
ok, 收到反馈，已经加入任务池
