### ISSUE TITLE
飞桨2.0 文档里动转静例程执行问题

### ISSUE THREAD

**Issue by skywalk163** [PaddlePaddle/Paddle#28670]
飞桨2.0 文档：教程，里面的动态图转静态图，基本用法里面的：基于源代码转写的ProgramTranslator 部分：

https://www.paddlepaddle.org.cn/documentation/docs/zh/2.0-rc/guides/04_dygraph_to_static/basic_usage_cn.html#programtranslator

程序例子是：

        import paddle

        @paddle.jit.to_static
        def func(input_var)
            # if判断与输入input_var的shape有关
            if input_var.shape[0] > 1:
                out = paddle.cast(input_var, "float64")
            else:
                out = paddle.cast(input_var, "int64")

        in_np = np.array([-2]).astype('int')
        input_var = paddle.to_tensor(in_np)
        func(input_var)

有如下几个问题：
1 def func(input_var)后面没有冒号。
2 func函数没有return数据
3 我测试在2.0rc版本下，不管输入几，都是两句都执行，跟“基于trace的TracedLayer”例子里面的情况一样，分支语句无法正常执行。

我的测试代码： 

        import paddle
        import numpy as np

        @paddle.jit.to_static
        def func(input_var):
            # if判断与输入input_var的shape有关
            if input_var.shape[0] > 1:
                out = paddle.cast(input_var, "float64")
                out = paddle.add(out, -out)
            else:
                out = paddle.cast(input_var, "int64")
                out = paddle.add(out, out)
            return out
        in_np = np.array([-2]).astype('int')
        input_var = paddle.to_tensor(in_np)
        temp=func(input_var)
        print(temp)
        in_np = np.array([2]).astype('int')
        input_var = paddle.to_tensor(in_np)
        temp=func(input_var)
        print(temp)

输出结果：

        Tensor(shape=[1], dtype=int64, place=CUDAPlace(0), stop_gradient=True,
       [-4])
        Tensor(shape=[1], dtype=int64, place=CUDAPlace(0), stop_gradient=True,
       [4])

显然判断语句没有正常运行 。

我的问题是： 

1 在有判断语句的情况下，是否ProgramTranslator 方式也像TracedLayer方式存在问题？ 

2 飞桨使用的Python3的开源AST处理 gast库 ，这部分在教程里只有描述，能像ProgramTranslator 部分给样例代码吗 ？

**Comment by Joejiong** [comment]
你好，马上反馈，谢谢

**Comment by Joejiong** [comment]
麻烦 @zhhsplendid 帮忙看下

**Comment by zhhsplendid** [comment]
嗨，谢谢反馈文档问题，我们马上查看和修改一下。但是你给的例子怎么说没有正常执行呢？

in_np = np.array([-2]).astype('int') 时，输出 Tensor 值为 -4
in_np = np.array([2]).astype('int') 时，输出 Tensor 值为 4

两个例子里都是shape[0] > 1不成立，走了else底下的
out = paddle.cast(input_var, "int64")
out = paddle.add(out, out)

何来“显然判断语句没有正常运行” ？

**Comment by skywalk163** [comment]
谢谢，看错了，看成了取input_var[0]的值了，原来是取shape值的[0] ,我说不应该ProgramTranslator 对判断语句出问题哈。


非常感谢。
