### ISSUE TITLE
运行时报Check failed: in_->ids错误

### ISSUE THREAD

**Issue by youan1** [PaddlePaddle/Paddle#2867]
[issue_script_and_input_case.zip](https://github.com/PaddlePaddle/Paddle/files/1147793/issue_script_and_input_case.zip)

麻烦看看上述脚本哪里错了，相应脚本为1.py，输入的base case为issue_sample，错误如下：

![image](https://user-images.githubusercontent.com/30172793/28204828-0663146a-68b2-11e7-82e5-5971dbfa3fc6.png)

谢谢！

**Comment by hedaoyuan** [comment]
看以来像是数据feeding有问题，但不确定是哪个slot的问题。另外，我没能跑起来你给的这个例子。

**Comment by hedaoyuan** [comment]
接embedding层的lyaer.data需要用integer_value，而不是sparse_binary_vector。
[参考这里](https://github.com/PaddlePaddle/Paddle/blob/b0c6331cde727f2e3097c89dcfe07b74325451af/doc/api/data_provider/pydataprovider2_cn.rst#input_types) 
···
data1 = paddle.layer.data("slot1",
                          paddle.data_type.sparse_binary_vector(
                              slot1_size))
data2 = paddle.layer.data("slot2",
                          paddle.data_type.sparse_binary_vector(
                              slot2_size))
data3 = paddle.layer.data("slot3",
                          paddle.data_type.sparse_binary_vector(
                              slot3_size))
data4 = paddle.layer.data("slot4",
                          paddle.data_type.sparse_binary_vector(
                              slot4_size))
···

**Comment by hedaoyuan** [comment]
@youan1 上面那个回复有问题，如果样本中是序列数据，应该用integer_value_sequence才对。

**Comment by lcy-seso** [comment]
- @youan1 请尽量不要在 issue 中贴图片，不能够被其它用户搜索到。请优先自己调试。

- 上面的出错信息是`embedding` 层需要接受 word index 作为输入，但是这一层现在的数据输出是空。通常都是因为`data layer` 中使用了错误的数据类型，而 reader 中也返回了错误的类型，导致 `embedding`层去读取数据时，数据为空。请检查data layer 使用的数据类型，以及reader是否返回了该类型。@hedaoyuan 是对的，应该使用 `integer_value_sequence` 而不是 `sparse_binary_vector`。

- 如果却是因为我们文档缺失造成使用不便利，请尽管提issue给我们，我们会通过文档来close此issue。

**Comment by youan1** [comment]
在issue中贴图片的问题，您说的对，这样使得答疑结果不能被大家更好的共享，下次会注意

另外参考文档使用integer_value_sequence时，其解释为"Data type of a sequence of integer",这里有不解，认为是输入是一个序列类型（类比dense_vector和dense_vector_sequence ）,所以才请paddle同学 帮忙看看
