### ISSUE TITLE
paddle一键编译版本安装报错：ImportError: No module named site

### ISSUE THREAD

**Issue by HugoLian** [PaddlePaddle/Paddle#2870]
下载内部一键编译版本，运行：
sh build.sh cpu nonrdma
最后报错ImportError: No module named site 很快退出安装。

![image](https://user-images.githubusercontent.com/22980558/28206836-1a55d6d0-68ba-11e7-8ffb-64ba6deb50e5.png)

PS, 我之前这台机器2016年下半年安装过一键编译版本，不知道和之前的安装有没有冲突。
请各位大神帮我看一下吧！

**Comment by pkuyym** [comment]
这个是pthon的环境问题，你可以试试运行python，看是否报错

**Comment by wanghaoshuang** [comment]
@HugoLian 执行 `pip install site` 后试试？

**Comment by HugoLian** [comment]
@pkuyym 就是这个问题，现在可以了，非常感谢！
