### ISSUE TITLE
auc函数需要改善

### ISSUE THREAD

**Issue by starsblinking** [PaddlePaddle/Paddle#28719]
真实业务场景中，能用的到的功能更多的是在多机训练完一段时间的情况下，用户自己把各台机器的stat_pos和stat_neg都gather到一台机器上算个auc就完事了。事实上，用户很多时候需要的，仅此而已。而目前的 fluid.layers.auc 做了多余的消耗计算量的无用功。希望paddle同学能新增一个auc函数(或者你们给旧函数增加新参数来控制也行)，其与fluid.layers.auc的区别如下：
1. 不需要计算batch的状态数据，所以可以去掉一个batch的append_op(auc)，留下另一个
2. 在auc_op.h里面去掉auc值相关的计算(比如calcAuc函数)

尤其是上述第二点，在某些情况下，用户需要设一个很大的num_thresholds（比如10w），而每训练一个batch都需要强制遍历一个这么长的数组来算auc（我不算了还不行么>.<)，这是很恐怖的。给用户一个简单的统计（全局or单机的)stat_pos和stat_neg的op可能是一个不错的选则:)

**Comment by TeslaZhao** [comment]
您好，感谢您的建议，已转交给内部相关同学

**Comment by dingjiaweiww** [comment]
Just test comment, please ignore ~
