### ISSUE TITLE
动态图中对数据进行修改，运行时会报错'paddle.fluid.core_avx.VarBase' object does not support item assignment

### ISSUE THREAD

**Issue by balckman-1996** [PaddlePaddle/Paddle#28725]
动态图中对数据进行修改,生成的数据填补入im_fake[:,64:192,64:192,:]中，运行时会报错'paddle.fluid.core_avx.VarBase' object does not support item assignment
im_fake_2_real_local = generator(im_fake)
im_fake[:,64:192,64:192,:]=im_fake_2_real_local

**Comment by TeslaZhao** [comment]
转换成numpy格式，在赋值试试一下

**Comment by balckman-1996** [comment]
变量可以转换成numpy格式么
传入的数据是 im_fake = fluid.dygraph.to_variable(im_fake)变量格式的

**Comment by zhwesky2010** [comment]
@balckman-1996 最新的develop应该基本支持了。 麻烦装下 https://www.paddlepaddle.org.cn/documentation/docs/zh/install/Tables.html#whl-dev 最新的dev包试试哈

**Comment by balckman-1996** [comment]
好的，已解决，谢谢
