### ISSUE TITLE
使用深度可分离网络反而变慢了

### ISSUE THREAD

**Issue by lizhaohu** [PaddlePaddle/Paddle#28743]
我将网络的7层cnn换成了mobilenetv1中的7层 depthwiseseoarable网络，网络耗时仅仅从120ms降到80ms，速度提高怎么这么少？和论文中不一致呢

**Comment by zhwesky2010** [comment]
@lizhaohu 您好，请问是复现的哪篇论文呢

**Comment by zhwesky2010** [comment]
@lizhaohu 您好，7层CNN换成mobilenetv1，确实会快一些，但是具体快多少我们还不确定，请问下是哪篇论文呢

**Comment by littletomatodonkey** [comment]
你好，可以单独测下1个conv和深度可分离卷积的速度哈，您说的这个速度提高的对比是在哪里看到的呢？

**Comment by lizhaohu** [comment]
> @lizhaohu 您好，请问是复现的哪篇论文呢



> @lizhaohu 您好，7层CNN换成mobilenetv1，确实会快一些，但是具体快多少我们还不确定，请问下是哪篇论文呢

@zhouwei25 您好，我是直接仿照paddle中的mobilenet.py，然后直接换成深度可分离卷积的，从100ms提高到了80ms，720p的图片，1060+6g的显卡，如果使用mobilenetv2的方式反而会编程100ms->300ms，我看网络中是先使用1*1进行升维，然后再使用的深度可分离卷积

**Comment by lizhaohu** [comment]
> 高的对比是在哪里看到的呢

@littletomatodonkey 好的 我试试，，我记得原始论文提高的挺多的
