### ISSUE TITLE
Paddleslim的使用【黄埔学院】

### ISSUE THREAD

**Issue by liuxi1007** [PaddlePaddle/Paddle#28740]
您好，请问有适用于paddle 2.0-rc版本程序的paddleslim包吗？

**Comment by zhwesky2010** [comment]
您好，如果在GPU上预测，每个版本都可以，如果在CPU上预测，请选择Paddle 2.0对应的PaddleSlim 1.2.0版本：
pip install paddleslim==1.2.0 -i https://pypi.tuna.tsinghua.edu.cn/simple

**Comment by liuxi1007** [comment]
谢谢
