### ISSUE TITLE
运行mask rcnn出错，其他的都可以，在ai studio上运行的

### ISSUE THREAD

**Issue by baiwan9kiwi** [PaddlePaddle/Paddle#28753]
为使您的问题得到快速解决，在建立Issues前，请您先通过如下方式搜索是否有相似问题:【搜索issue关键字】【使用labels筛选】【官方文档】

如果您没有查询到相似问题，为快速解决您的提问，建立issue时请提供如下细节信息：
- 标题：简洁、精准概括您的问题，例如“Insufficient Memory xxx" ”
- 版本、环境信息：
    1）PaddlePaddle版本：请提供您的PaddlePaddle版本号，例如1.1或CommitID
    2）CPU：预测若用CPU，请提供CPU型号，MKL/OpenBlas/MKLDNN/等数学库使用情况
    3）GPU：预测若用GPU，请提供GPU型号、CUDA和CUDNN版本号
    4）系统环境：请您描述系统类型、版本，例如Mac OS 10.14，Python版本
 注：您可以通过执行[summary_env.py](https://github.com/PaddlePaddle/Paddle/blob/develop/tools/summary_env.py)获取以上信息。
- 训练信息
    1）单机/多机，单卡/多卡
    2）显存信息
    3）Operator信息
- 复现信息：如为报错，请给出复现环境、复现步骤
- 问题描述：请详细描述您的问题，同步贴出报错信息、日志、可复现的代码片段

Thank you for contributing to PaddlePaddle.
Before submitting the issue, you could search issue in the github in case that there was a similar issue submitted or resolved before.
If there is no solution,please make sure that this is a training issue including the following details:
**System information**
-PaddlePaddle version （eg.1.1）or CommitID
-CPU: including CPUMKL/OpenBlas/MKLDNN version
-GPU: including CUDA/CUDNN version
-OS Platform (eg.Mac OS 10.14)
-Other imformation: Distriuted training/informantion of operator/
Graphics card storage
Note: You can get most of the information by running [summary_env.py](https://github.com/PaddlePaddle/Paddle/blob/develop/tools/summary_env.py). 
**To Reproduce**
Steps to reproduce the behavior
**Describe your current behavior**
**Code to reproduce the issue**
**Other info / logs**

W1119 14:52:04.917482  1907 init.cc:226] Warning: PaddlePaddle catches a failure signal, it may not work properly
W1119 14:52:04.917670  1907 init.cc:228] You could check whether you killed PaddlePaddle thread/process accidentally or report the case to PaddlePaddle
W1119 14:52:04.917685  1907 init.cc:231] The detail failure signal is:

W1119 14:52:04.917699  1907 init.cc:234] *** Aborted at 1605768724 (unix time) try "date -d @1605768724" if you are using GNU date ***
W1119 14:52:04.920356  1907 init.cc:234] PC: @                0x0 (unknown)
W1119 14:52:04.920743  1907 init.cc:234] *** SIGSEGV (@0x100000029) received by PID 1844 (TID 0x7f399974a700) from PID 41; stack trace: ***
W1119 14:52:04.922940  1907 init.cc:234]     @     0x7f3a22351390 (unknown)
W1119 14:52:04.926961  1907 init.cc:234]     @     0x7f39ad467ef8 paddle::memory::detail::MemoryBlock::Split()
W1119 14:52:04.932113  1907 init.cc:234]     @     0x7f39ad466422 _ZN6paddle6memory6detail14BuddyAllocator12SplitToAllocESt23_Rb_tree_const_iteratorISt5tupleIJmmPvEEEm
W1119 14:52:04.938035  1907 init.cc:234]     @     0x7f39ad466905 paddle::memory::detail::BuddyAllocator::Alloc()
W1119 14:52:04.942857  1907 init.cc:234]     @     0x7f39ad4568f5 paddle::memory::legacy::Alloc<>()
W1119 14:52:04.947901  1907 init.cc:234]     @     0x7f39ad457895 paddle::memory::allocation::NaiveBestFitAllocator::AllocateImpl()
W1119 14:52:04.950899  1907 init.cc:234]     @     0x7f39ad44f3df paddle::memory::allocation::AllocatorFacade::Alloc()
W1119 14:52:04.954990  1907 init.cc:234]     @     0x7f39ad44f62a paddle::memory::allocation::AllocatorFacade::AllocShared()
W1119 14:52:04.957769  1907 init.cc:234]     @     0x7f39ad44edfc paddle::memory::AllocShared()
W1119 14:52:04.960870  1907 init.cc:234]     @     0x7f39ad43b5b2 paddle::framework::Tensor::mutable_data()
W1119 14:52:04.964670  1907 init.cc:234]     @     0x7f39aca92633 paddle::operators::SampleMaskForOneImage<>()
W1119 14:52:04.971513  1907 init.cc:234]     @     0x7f39aca9427f paddle::operators::GenerateMaskLabelsKernel<>::Compute()
W1119 14:52:04.974150  1907 init.cc:234]     @     0x7f39aca95af3 _ZNSt17_Function_handlerIFvRKN6paddle9framework16ExecutionContextEEZNKS1_24OpKernelRegistrarFunctorINS0_8platform8CPUPlaceELb0ELm0EINS0_9operators24GenerateMaskLabelsKernelIfEEEEclEPKcSE_iEUlS4_E_E9_M_invokeERKSt9_Any_dataS4_
W1119 14:52:04.978880  1907 init.cc:234]     @     0x7f39ad3b3ac0 paddle::framework::OperatorWithKernel::RunImpl()
W1119 14:52:04.985458  1907 init.cc:234]     @     0x7f39ad3b42b1 paddle::framework::OperatorWithKernel::RunImpl()
W1119 14:52:04.989212  1907 init.cc:234]     @     0x7f39ad3ad271 paddle::framework::OperatorBase::Run()
W1119 14:52:04.994994  1907 init.cc:234]     @     0x7f39ad0bcb56 paddle::framework::details::ComputationOpHandle::RunImpl()
W1119 14:52:04.999918  1907 init.cc:234]     @     0x7f39ad062d31 paddle::framework::details::FastThreadedSSAGraphExecutor::RunOpSync()
W1119 14:52:05.005266  1907 init.cc:234]     @     0x7f39ad06082f paddle::framework::details::FastThreadedSSAGraphExecutor::RunOp()
W1119 14:52:05.007220  1907 init.cc:234]     @     0x7f39ad060af4 _ZNSt17_Function_handlerIFvvESt17reference_wrapperISt12_Bind_simpleIFS1_ISt5_BindIFZN6paddle9framework7details28FastThreadedSSAGraphExecutor10RunOpAsyncEPSt13unordered_mapIPNS6_12OpHandleBaseESt6atomicIiESt4hashISA_ESt8equal_toISA_ESaISt4pairIKSA_SC_EEESA_RKSt10shared_ptrINS5_13BlockingQueueImEEEEUlvE_vEEEvEEEE9_M_invokeERKSt9_Any_data
W1119 14:52:05.013495  1907 init.cc:234]     @     0x7f39a9fdb603 std::_Function_handler<>::_M_invoke()
W1119 14:52:05.019770  1907 init.cc:234]     @     0x7f39a9dd52f7 std::__future_base::_State_base::_M_do_set()
W1119 14:52:05.021979  1907 init.cc:234]     @     0x7f3a2234ea99 __pthread_once_slow
W1119 14:52:05.023806  1907 init.cc:234]     @     0x7f39ad05ccc2 _ZNSt13__future_base11_Task_stateISt5_BindIFZN6paddle9framework7details28FastThreadedSSAGraphExecutor10RunOpAsyncEPSt13unordered_mapIPNS4_12OpHandleBaseESt6atomicIiESt4hashIS8_ESt8equal_toIS8_ESaISt4pairIKS8_SA_EEES8_RKSt10shared_ptrINS3_13BlockingQueueImEEEEUlvE_vEESaIiEFvvEE6_M_runEv
W1119 14:52:05.030056  1907 init.cc:234]     @     0x7f39a9dd7754 _ZZN10ThreadPoolC1EmENKUlvE_clEv
W1119 14:52:05.031349  1907 init.cc:234]     @     0x7f39e2d45421 execute_native_thread_routine_compat
W1119 14:52:05.033422  1907 init.cc:234]     @     0x7f3a223476ba start_thread
W1119 14:52:05.035519  1907 init.cc:234]     @     0x7f3a2207d41d clone
W1119 14:52:05.037561  1907 init.cc:234]     @                0x0 (unknown)
Segmentation fault (core dumped)
以上是我的报错信息，在aistudio上运行的，python3.7，paddle版本1.8.4，GPU V100，运行模型是mask_rcnn_r101_fpn_1x.yml

**Comment by zhwesky2010** [comment]
@baiwan9kiwi 您好，如果只有一行代码 ``import paddle`` 是否也会报错呢，这个问题应该与mask rcnn 是没有关系的，是paddle的安装问题

**Comment by baiwan9kiwi** [comment]
你好，我是在ai studio上创建项目并且运行的，我在notebook运行了 import paddle 并没有报错
![image](https://user-images.githubusercontent.com/57944244/99776556-f8b3b300-2b4b-11eb-8aba-20c577751f42.png)

**Comment by zhwesky2010** [comment]
@baiwan9kiwi 麻烦运行一下 ``import paddle ``  ``paddle.fluid.install_check.run_check()`` ，先确认一下Paddle能否正常跑

**Comment by baiwan9kiwi** [comment]
![image](https://user-images.githubusercontent.com/57944244/99779237-bab88e00-2b4f-11eb-8fae-9fcc2b9d639f.png)
你好，是可以运行的

**Comment by zhwesky2010** [comment]
@baiwan9kiwi 看起来是PE执行时，显存访问越界的错误，而这块内存已经被释放了，因此可能是该模型触发了的框架调度中存在的一个bug。请问是模型是如何运行的，是哪个代码地址，我们测试下这个模型~

**Comment by zhwesky2010** [comment]
@baiwan9kiwi 系统和卡数是多少呢

**Comment by baiwan9kiwi** [comment]
我的电脑就是win10的，edge登录的ai studio
环境配置：![image](https://user-images.githubusercontent.com/57944244/99779952-c8bade80-2b50-11eb-8669-e00edc1303ae.png)
模型地址：PaddleDetection-release-0.4/configs/mask_rcnn_r101_fpn_1x.yml
不单单是这个模型，mask类型的都跑不了，而YOLO和ssd系列都可以运行
数据集：是我们自己的数据集，coco格式
