### ISSUE TITLE
关于模型部署时数据的预处理

### ISSUE THREAD

**Issue by Fitz-Fitz** [PaddlePaddle/Paddle#28751]
请问通过paddlex训练完模型导出后，在移动端上部署，送入预测网络前图像对应的预处理要完成哪些，在哪里可以查看到这类信息？感谢

**Comment by zhwesky2010** [comment]
@Fitz-Fitz 您好，https://paddle-lite.readthedocs.io/zh/latest/quick_start/tutorial.html 这里是Paddle移动端部署的流程，https://paddle-lite.readthedocs.io/zh/latest/index.html Paddle-Lite整体介绍

**Comment by Fitz-Fitz** [comment]
感谢您提供的文档，已全部阅读，但仍存在一些疑惑，请您指教：
我的部署设备是jetson nano，部署软件环境是基于paddle编译的paddle inference。
在部署时，加载配置和进行推理间，需要数据预处理。而对于通过paddlex训练导出的模型，请问如何确定模型输入时需要的预处理操作

**Comment by jiangjiajun** [comment]
> 感谢您提供的文档，已全部阅读，但仍存在一些疑惑，请您指教：
> 我的部署设备是jetson nano，部署软件环境是基于paddle编译的paddle inference。
> 在部署时，加载配置和进行推理间，需要数据预处理。而对于通过paddlex训练导出的模型，请问如何确定模型输入时需要的预处理操作

PaddleX的预处理操作，都在导出的模型中的model.yml中有描述，其相应的实现可以参考PaddleX的预测代码
https://github.com/PaddlePaddle/PaddleX/tree/develop/deploy

其中Jetson上部署PaddleX训练的模型参考：https://paddlex.readthedocs.io/zh_CN/develop/deploy/nvidia-jetson.html

**Comment by Fitz-Fitz** [comment]
> > 感谢您提供的文档，已全部阅读，但仍存在一些疑惑，请您指教：
> > 我的部署设备是jetson nano，部署软件环境是基于paddle编译的paddle inference。
> > 在部署时，加载配置和进行推理间，需要数据预处理。而对于通过paddlex训练导出的模型，请问如何确定模型输入时需要的预处理操作
> 
> PaddleX的预处理操作，都在导出的模型中的model.yml中有描述，其相应的实现可以参考PaddleX的预测代码
> https://github.com/PaddlePaddle/PaddleX/tree/develop/deploy
> 
> 其中Jetson上部署PaddleX训练的模型参考：https://paddlex.readthedocs.io/zh_CN/develop/deploy/nvidia-jetson.html

感谢您的资料，已经成功在nano上编译paddlex，但是使用GPU时报错如下

----------------------
Error Message Summary:
----------------------
ExternalError:  Cuda error(48), no kernel image is available for execution on the device.
  [Advise: Please search for the error code(48) on website( https://docs.nvidia.com/cuda/archive/10.0/cuda-runtime-api/group__CUDART__TYPES.html#group__CUDART__TYPES_1g3f51e3575c2178246db0a94a430e0038 ) to get Nvidia's official solution about CUDA Error.] (at /media/paddle/a2a27488-590d-40c0-aec9-20efadb82b81/wangye19/Paddle/paddle/fluid/platform/gpu_info.cc:324)
  [operator < elementwise_add > error]
[1]+  Killed                  ./build/demo/video_detector --model_dir=/home/trash/Downloads/new_inference_model --use_camera=1 --use_gpu=0 --gpu_id=0 --show_result=1
Aborted (core dumped)

**Comment by jiangjiajun** [comment]
上面看这个命令是在将use_gpu设为0时出的错，为了判断是使用相机出的错，还是其它问题，建议运行一下分类的程序classifier测试下。

分类模型可在此下载 https://bj.bcebos.com/paddlex/models/mobilenetv3_small_ssld_imagenet.tar.gz （下载后需手动将模型导出为Inference模型格式），模型目录中包含一张图片可供测试。 

为了便于快速解决问题，也可加QQ群1045148026进行反馈
