### ISSUE TITLE
Improve exception safety with smart pointers

### ISSUE THREAD

**Issue by elfring** [PaddlePaddle/Paddle#2877]
Would you like to [wrap any pointer data members](https://github.com/PaddlePaddle/Paddle/blob/9b755c068462bf66373222fc6b486cbecefe885d/paddle/optimizer/adadelta_optimizer.h#L10 "Update candidate: AdadeltaOptimizer class") with the template class “[std::unique_ptr](https://en.wikipedia.org/wiki/Smart_pointer#unique_ptr "Description for usage of smart pointers")”?

**Comment by hedaoyuan** [comment]
I also think use std::unique_ptr is better.

**Comment by elfring** [comment]
Will any further software evolution happen in the mentioned area?

**Comment by JiayiFeng** [comment]
Thank you for attention! For we have totally focused on the developing of Fluid(a new version of Paddle), all legacy code (Paddle V1/V2) is no longer updated.

**Comment by elfring** [comment]
Will any more development results be published for “Fluid”?

**Comment by JiayiFeng** [comment]
We have released several versions of Fluid, the newest one is 0.14.0. You can see the c++ code here :
https://github.com/PaddlePaddle/Paddle/tree/develop/paddle/fluid
 and Python code here:
https://github.com/PaddlePaddle/Paddle/tree/develop/python/paddle/fluid
