### ISSUE TITLE
jetson nano上编译paddle-lite出错

### ISSUE THREAD

**Issue by Fitz-Fitz** [PaddlePaddle/Paddle#28782]
jetson nano ， jetpack 4.4 编译paddle-lite，参考网址：https://paddle-lite.readthedocs.io/zh/latest/demo_guides/cuda.html

编译报错，查看cmakeerro.log文件内容如下：

Determining if the pthread_create exist failed with the following output:
Change Dir: /home/trash/Desktop/Paddle-Lite-develop/build_cuda/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/make" "cmTC_4748a/fast"
/usr/bin/make -f CMakeFiles/cmTC_4748a.dir/build.make CMakeFiles/cmTC_4748a.dir/build
make[1]: Entering directory '/home/trash/Desktop/Paddle-Lite-develop/build_cuda/CMakeFiles/CMakeTmp'
Building C object CMakeFiles/cmTC_4748a.dir/CheckSymbolExists.c.o
/usr/bin/cc   -fPIC    -o CMakeFiles/cmTC_4748a.dir/CheckSymbolExists.c.o   -c /home/trash/Desktop/Paddle-Lite-develop/build_cuda/CMakeFiles/CMakeTmp/CheckSymbolExists.c
Linking C executable cmTC_4748a
/usr/bin/cmake -E cmake_link_script CMakeFiles/cmTC_4748a.dir/link.txt --verbose=1
/usr/bin/cc -fPIC     -rdynamic CMakeFiles/cmTC_4748a.dir/CheckSymbolExists.c.o  -o cmTC_4748a 
CMakeFiles/cmTC_4748a.dir/CheckSymbolExists.c.o: In function `main':
CheckSymbolExists.c:(.text+0x14): undefined reference to `pthread_create'
CheckSymbolExists.c:(.text+0x18): undefined reference to `pthread_create'
collect2: error: ld returned 1 exit status
CMakeFiles/cmTC_4748a.dir/build.make:97: recipe for target 'cmTC_4748a' failed
make[1]: *** [cmTC_4748a] Error 1
make[1]: Leaving directory '/home/trash/Desktop/Paddle-Lite-develop/build_cuda/CMakeFiles/CMakeTmp'
Makefile:126: recipe for target 'cmTC_4748a/fast' failed
make: *** [cmTC_4748a/fast] Error 2

File /home/trash/Desktop/Paddle-Lite-develop/build_cuda/CMakeFiles/CMakeTmp/CheckSymbolExists.c:
/* */
#include <pthread.h>

int main(int argc, char** argv)
{
  (void)argv;
#ifndef pthread_create
  return ((int*)(&pthread_create))[argc];
#else
  (void)argc;
  return 0;
#endif
}

Determining if the function pthread_create exists in the pthreads failed with the following output:
Change Dir: /home/trash/Desktop/Paddle-Lite-develop/build_cuda/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/make" "cmTC_6c09d/fast"
/usr/bin/make -f CMakeFiles/cmTC_6c09d.dir/build.make CMakeFiles/cmTC_6c09d.dir/build
make[1]: Entering directory '/home/trash/Desktop/Paddle-Lite-develop/build_cuda/CMakeFiles/CMakeTmp'
Building C object CMakeFiles/cmTC_6c09d.dir/CheckFunctionExists.c.o
/usr/bin/cc   -fPIC -DCHECK_FUNCTION_EXISTS=pthread_create   -o CMakeFiles/cmTC_6c09d.dir/CheckFunctionExists.c.o   -c /usr/share/cmake-3.10/Modules/CheckFunctionExists.c
Linking C executable cmTC_6c09d
/usr/bin/cmake -E cmake_link_script CMakeFiles/cmTC_6c09d.dir/link.txt --verbose=1
/usr/bin/cc -fPIC -DCHECK_FUNCTION_EXISTS=pthread_create    -rdynamic CMakeFiles/cmTC_6c09d.dir/CheckFunctionExists.c.o  -o cmTC_6c09d -lpthreads 
/usr/bin/ld: cannot find -lpthreads
collect2: error: ld returned 1 exit status
CMakeFiles/cmTC_6c09d.dir/build.make:97: recipe for target 'cmTC_6c09d' failed
make[1]: *** [cmTC_6c09d] Error 1
make[1]: Leaving directory '/home/trash/Desktop/Paddle-Lite-develop/build_cuda/CMakeFiles/CMakeTmp'
Makefile:126: recipe for target 'cmTC_6c09d/fast' failed
make: *** [cmTC_6c09d/fast] Error 2

Performing C++ SOURCE FILE Test MMX_FOUND failed with the following output:
Change Dir: /home/trash/Desktop/Paddle-Lite-develop/build_cuda/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/make" "cmTC_4b988/fast"
/usr/bin/make -f CMakeFiles/cmTC_4b988.dir/build.make CMakeFiles/cmTC_4b988.dir/build
make[1]: Entering directory '/home/trash/Desktop/Paddle-Lite-develop/build_cuda/CMakeFiles/CMakeTmp'
Building CXX object CMakeFiles/cmTC_4b988.dir/src.cxx.o
/usr/bin/c++    -DMMX_FOUND -mmmx   -o CMakeFiles/cmTC_4b988.dir/src.cxx.o -c /home/trash/Desktop/Paddle-Lite-develop/build_cuda/CMakeFiles/CMakeTmp/src.cxx
c++: error: unrecognized command line option ‘-mmmx’
CMakeFiles/cmTC_4b988.dir/build.make:65: recipe for target 'CMakeFiles/cmTC_4b988.dir/src.cxx.o' failed
make[1]: *** [CMakeFiles/cmTC_4b988.dir/src.cxx.o] Error 1
make[1]: Leaving directory '/home/trash/Desktop/Paddle-Lite-develop/build_cuda/CMakeFiles/CMakeTmp'
Makefile:126: recipe for target 'cmTC_4b988/fast' failed
make: *** [cmTC_4b988/fast] Error 2

Return value: 1
Source file was:

#include <mmintrin.h>
int main()
{
    _mm_setzero_si64();
    return 0;
}
Performing C++ SOURCE FILE Test SSE2_FOUND failed with the following output:
Change Dir: /home/trash/Desktop/Paddle-Lite-develop/build_cuda/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/make" "cmTC_a4826/fast"
/usr/bin/make -f CMakeFiles/cmTC_a4826.dir/build.make CMakeFiles/cmTC_a4826.dir/build
make[1]: Entering directory '/home/trash/Desktop/Paddle-Lite-develop/build_cuda/CMakeFiles/CMakeTmp'
Building CXX object CMakeFiles/cmTC_a4826.dir/src.cxx.o
/usr/bin/c++    -DSSE2_FOUND -msse2   -o CMakeFiles/cmTC_a4826.dir/src.cxx.o -c /home/trash/Desktop/Paddle-Lite-develop/build_cuda/CMakeFiles/CMakeTmp/src.cxx
c++: error: unrecognized command line option ‘-msse2’
CMakeFiles/cmTC_a4826.dir/build.make:65: recipe for target 'CMakeFiles/cmTC_a4826.dir/src.cxx.o' failed
make[1]: *** [CMakeFiles/cmTC_a4826.dir/src.cxx.o] Error 1
make[1]: Leaving directory '/home/trash/Desktop/Paddle-Lite-develop/build_cuda/CMakeFiles/CMakeTmp'
Makefile:126: recipe for target 'cmTC_a4826/fast' failed
make: *** [cmTC_a4826/fast] Error 2

Return value: 1
Source file was:

#include <emmintrin.h>
int main()
{
    _mm_setzero_si128();
    return 0;
}
Performing C++ SOURCE FILE Test SSE3_FOUND failed with the following output:
Change Dir: /home/trash/Desktop/Paddle-Lite-develop/build_cuda/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/make" "cmTC_6d681/fast"
/usr/bin/make -f CMakeFiles/cmTC_6d681.dir/build.make CMakeFiles/cmTC_6d681.dir/build
make[1]: Entering directory '/home/trash/Desktop/Paddle-Lite-develop/build_cuda/CMakeFiles/CMakeTmp'
Building CXX object CMakeFiles/cmTC_6d681.dir/src.cxx.o
/usr/bin/c++    -DSSE3_FOUND -msse3   -o CMakeFiles/cmTC_6d681.dir/src.cxx.o -c /home/trash/Desktop/Paddle-Lite-develop/build_cuda/CMakeFiles/CMakeTmp/src.cxx
c++: error: unrecognized command line option ‘-msse3’
CMakeFiles/cmTC_6d681.dir/build.make:65: recipe for target 'CMakeFiles/cmTC_6d681.dir/src.cxx.o' failed
make[1]: *** [CMakeFiles/cmTC_6d681.dir/src.cxx.o] Error 1
make[1]: Leaving directory '/home/trash/Desktop/Paddle-Lite-develop/build_cuda/CMakeFiles/CMakeTmp'
Makefile:126: recipe for target 'cmTC_6d681/fast' failed
make: *** [cmTC_6d681/fast] Error 2

Return value: 1
Source file was:

#include <pmmintrin.h>
int main()
{
    __m128d a = _mm_set1_pd(6.28);
    __m128d b = _mm_set1_pd(3.14);
    __m128d result = _mm_addsub_pd(a, b);
    result = _mm_movedup_pd(result);
    return 0;
}
Performing C++ SOURCE FILE Test AVX_FOUND failed with the following output:
Change Dir: /home/trash/Desktop/Paddle-Lite-develop/build_cuda/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/make" "cmTC_a83df/fast"
/usr/bin/make -f CMakeFiles/cmTC_a83df.dir/build.make CMakeFiles/cmTC_a83df.dir/build
make[1]: Entering directory '/home/trash/Desktop/Paddle-Lite-develop/build_cuda/CMakeFiles/CMakeTmp'
Building CXX object CMakeFiles/cmTC_a83df.dir/src.cxx.o
/usr/bin/c++    -DAVX_FOUND -mavx   -o CMakeFiles/cmTC_a83df.dir/src.cxx.o -c /home/trash/Desktop/Paddle-Lite-develop/build_cuda/CMakeFiles/CMakeTmp/src.cxx
c++: error: unrecognized command line option ‘-mavx’
CMakeFiles/cmTC_a83df.dir/build.make:65: recipe for target 'CMakeFiles/cmTC_a83df.dir/src.cxx.o' failed
make[1]: *** [CMakeFiles/cmTC_a83df.dir/src.cxx.o] Error 1
make[1]: Leaving directory '/home/trash/Desktop/Paddle-Lite-develop/build_cuda/CMakeFiles/CMakeTmp'
Makefile:126: recipe for target 'cmTC_a83df/fast' failed
make: *** [cmTC_a83df/fast] Error 2

Return value: 1
Source file was:

#include <immintrin.h>
int main()
{
    __m256 a = _mm256_set_ps (-1.0f, 2.0f, -3.0f, 4.0f, -1.0f, 2.0f, -3.0f, 4.0f);
    __m256 b = _mm256_set_ps (1.0f, 2.0f, 3.0f, 4.0f, 1.0f, 2.0f, 3.0f, 4.0f);
    __m256 result = _mm256_add_ps (a, b);
    return 0;
}
Performing C++ SOURCE FILE Test AVX2_FOUND failed with the following output:
Change Dir: /home/trash/Desktop/Paddle-Lite-develop/build_cuda/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/make" "cmTC_34c50/fast"
/usr/bin/make -f CMakeFiles/cmTC_34c50.dir/build.make CMakeFiles/cmTC_34c50.dir/build
make[1]: Entering directory '/home/trash/Desktop/Paddle-Lite-develop/build_cuda/CMakeFiles/CMakeTmp'
Building CXX object CMakeFiles/cmTC_34c50.dir/src.cxx.o
/usr/bin/c++    -DAVX2_FOUND -mavx2   -o CMakeFiles/cmTC_34c50.dir/src.cxx.o -c /home/trash/Desktop/Paddle-Lite-develop/build_cuda/CMakeFiles/CMakeTmp/src.cxx
c++: error: unrecognized command line option ‘-mavx2’
CMakeFiles/cmTC_34c50.dir/build.make:65: recipe for target 'CMakeFiles/cmTC_34c50.dir/src.cxx.o' failed
make[1]: *** [CMakeFiles/cmTC_34c50.dir/src.cxx.o] Error 1
make[1]: Leaving directory '/home/trash/Desktop/Paddle-Lite-develop/build_cuda/CMakeFiles/CMakeTmp'
Makefile:126: recipe for target 'cmTC_34c50/fast' failed
make: *** [cmTC_34c50/fast] Error 2

Return value: 1
Source file was:

#include <immintrin.h>
int main()
{
    __m256i a = _mm256_set_epi32 (-1, 2, -3, 4, -1, 2, -3, 4);
    __m256i result = _mm256_abs_epi32 (a);
    return 0;
}
Performing C++ SOURCE FILE Test AVX512F_FOUND failed with the following output:
Change Dir: /home/trash/Desktop/Paddle-Lite-develop/build_cuda/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/make" "cmTC_bc598/fast"
/usr/bin/make -f CMakeFiles/cmTC_bc598.dir/build.make CMakeFiles/cmTC_bc598.dir/build
make[1]: Entering directory '/home/trash/Desktop/Paddle-Lite-develop/build_cuda/CMakeFiles/CMakeTmp'
Building CXX object CMakeFiles/cmTC_bc598.dir/src.cxx.o
/usr/bin/c++    -DAVX512F_FOUND -mavx512f   -o CMakeFiles/cmTC_bc598.dir/src.cxx.o -c /home/trash/Desktop/Paddle-Lite-develop/build_cuda/CMakeFiles/CMakeTmp/src.cxx
c++: error: unrecognized command line option ‘-mavx512f’
CMakeFiles/cmTC_bc598.dir/build.make:65: recipe for target 'CMakeFiles/cmTC_bc598.dir/src.cxx.o' failed
make[1]: *** [CMakeFiles/cmTC_bc598.dir/src.cxx.o] Error 1
make[1]: Leaving directory '/home/trash/Desktop/Paddle-Lite-develop/build_cuda/CMakeFiles/CMakeTmp'
Makefile:126: recipe for target 'cmTC_bc598/fast' failed
make: *** [cmTC_bc598/fast] Error 2

Return value: 1
Source file was:

#include <immintrin.h>
int main()
{
    __m512i a = _mm512_set_epi32 (-1, 2, -3, 4, -1, 2, -3, 4,
                                  13, -5, 6, -7, 9, 2, -6, 3);
    __m512i result = _mm512_abs_epi32 (a);
    return 0;
}
Performing C SOURCE FILE Test C_COMPILER_SUPPORT_FLAG__Wnon_virtual_dtor failed with the following output:
Change Dir: /home/trash/Desktop/Paddle-Lite-develop/build_cuda/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/make" "cmTC_ed56a/fast"
/usr/bin/make -f CMakeFiles/cmTC_ed56a.dir/build.make CMakeFiles/cmTC_ed56a.dir/build
make[1]: Entering directory '/home/trash/Desktop/Paddle-Lite-develop/build_cuda/CMakeFiles/CMakeTmp'
Building C object CMakeFiles/cmTC_ed56a.dir/src.c.o
/usr/bin/cc   -fPIC -fno-omit-frame-pointer -Werror -Wall -Wextra -DC_COMPILER_SUPPORT_FLAG__Wnon_virtual_dtor   -Wnon-virtual-dtor -o CMakeFiles/cmTC_ed56a.dir/src.c.o   -c /home/trash/Desktop/Paddle-Lite-develop/build_cuda/CMakeFiles/CMakeTmp/src.c
cc1: error: command line option '-Wnon-virtual-dtor' is valid for C++/ObjC++ but not for C [-Werror]
cc1: all warnings being treated as errors
CMakeFiles/cmTC_ed56a.dir/build.make:65: recipe for target 'CMakeFiles/cmTC_ed56a.dir/src.c.o' failed
make[1]: *** [CMakeFiles/cmTC_ed56a.dir/src.c.o] Error 1
make[1]: Leaving directory '/home/trash/Desktop/Paddle-Lite-develop/build_cuda/CMakeFiles/CMakeTmp'
Makefile:126: recipe for target 'cmTC_ed56a/fast' failed
make: *** [cmTC_ed56a/fast] Error 2

Source file was:
int main(void) { return 0; }
Performing C SOURCE FILE Test C_COMPILER_SUPPORT_FLAG__Wdelete_non_virtual_dtor failed with the following output:
Change Dir: /home/trash/Desktop/Paddle-Lite-develop/build_cuda/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/make" "cmTC_018e8/fast"
/usr/bin/make -f CMakeFiles/cmTC_018e8.dir/build.make CMakeFiles/cmTC_018e8.dir/build
make[1]: Entering directory '/home/trash/Desktop/Paddle-Lite-develop/build_cuda/CMakeFiles/CMakeTmp'
Building C object CMakeFiles/cmTC_018e8.dir/src.c.o
/usr/bin/cc   -fPIC -fno-omit-frame-pointer -Werror -Wall -Wextra -DC_COMPILER_SUPPORT_FLAG__Wdelete_non_virtual_dtor   -Wdelete-non-virtual-dtor -o CMakeFiles/cmTC_018e8.dir/src.c.o   -c /home/trash/Desktop/Paddle-Lite-develop/build_cuda/CMakeFiles/CMakeTmp/src.c
cc1: error: command line option '-Wdelete-non-virtual-dtor' is valid for C++/ObjC++ but not for C [-Werror]
cc1: all warnings being treated as errors
CMakeFiles/cmTC_018e8.dir/build.make:65: recipe for target 'CMakeFiles/cmTC_018e8.dir/src.c.o' failed
make[1]: *** [CMakeFiles/cmTC_018e8.dir/src.c.o] Error 1
make[1]: Leaving directory '/home/trash/Desktop/Paddle-Lite-develop/build_cuda/CMakeFiles/CMakeTmp'
Makefile:126: recipe for target 'cmTC_018e8/fast' failed
make: *** [cmTC_018e8/fast] Error 2

Source file was:
int main(void) { return 0; }
Performing C SOURCE FILE Test C_COMPILER_SUPPORT_FLAG__Wno_error_parentheses_equality failed with the following output:
Change Dir: /home/trash/Desktop/Paddle-Lite-develop/build_cuda/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/make" "cmTC_c5f7e/fast"
/usr/bin/make -f CMakeFiles/cmTC_c5f7e.dir/build.make CMakeFiles/cmTC_c5f7e.dir/build
make[1]: Entering directory '/home/trash/Desktop/Paddle-Lite-develop/build_cuda/CMakeFiles/CMakeTmp'
Building C object CMakeFiles/cmTC_c5f7e.dir/src.c.o
/usr/bin/cc   -fPIC -fno-omit-frame-pointer -Werror -Wall -Wextra -Wno-unused-parameter -Wno-unused-function -Wno-error=literal-suffix -Wno-error=sign-compare -Wno-error=unused-local-typedefs -DC_COMPILER_SUPPORT_FLAG__Wno_error_parentheses_equality   -Wno-error=parentheses-equality -o CMakeFiles/cmTC_c5f7e.dir/src.c.o   -c /home/trash/Desktop/Paddle-Lite-develop/build_cuda/CMakeFiles/CMakeTmp/src.c
cc1: error: -Werror=parentheses-equality: no option -Wparentheses-equality
CMakeFiles/cmTC_c5f7e.dir/build.make:65: recipe for target 'CMakeFiles/cmTC_c5f7e.dir/src.c.o' failed
make[1]: *** [CMakeFiles/cmTC_c5f7e.dir/src.c.o] Error 1
make[1]: Leaving directory '/home/trash/Desktop/Paddle-Lite-develop/build_cuda/CMakeFiles/CMakeTmp'
Makefile:126: recipe for target 'cmTC_c5f7e/fast' failed
make: *** [cmTC_c5f7e/fast] Error 2

Source file was:
int main(void) { return 0; }
Performing C++ SOURCE FILE Test CXX_COMPILER_SUPPORT_FLAG__Wno_error_parentheses_equality failed with the following output:
Change Dir: /home/trash/Desktop/Paddle-Lite-develop/build_cuda/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/make" "cmTC_344e3/fast"
/usr/bin/make -f CMakeFiles/cmTC_344e3.dir/build.make CMakeFiles/cmTC_344e3.dir/build
make[1]: Entering directory '/home/trash/Desktop/Paddle-Lite-develop/build_cuda/CMakeFiles/CMakeTmp'
Building CXX object CMakeFiles/cmTC_344e3.dir/src.cxx.o
/usr/bin/c++    -std=c++11 -fPIC -fno-omit-frame-pointer -Werror -Wall -Wextra -Wnon-virtual-dtor -Wdelete-non-virtual-dtor -Wno-unused-parameter -Wno-unused-function -Wno-error=literal-suffix -Wno-error=sign-compare -Wno-error=unused-local-typedefs -DCXX_COMPILER_SUPPORT_FLAG__Wno_error_parentheses_equality   -Wno-error=parentheses-equality -o CMakeFiles/cmTC_344e3.dir/src.cxx.o -c /home/trash/Desktop/Paddle-Lite-develop/build_cuda/CMakeFiles/CMakeTmp/src.cxx
cc1plus: error: -Werror=parentheses-equality: no option -Wparentheses-equality
CMakeFiles/cmTC_344e3.dir/build.make:65: recipe for target 'CMakeFiles/cmTC_344e3.dir/src.cxx.o' failed
make[1]: *** [CMakeFiles/cmTC_344e3.dir/src.cxx.o] Error 1
make[1]: Leaving directory '/home/trash/Desktop/Paddle-Lite-develop/build_cuda/CMakeFiles/CMakeTmp'
Makefile:126: recipe for target 'cmTC_344e3/fast' failed
make: *** [cmTC_344e3/fast] Error 2

Source file was:
int main() { return 0; }
Performing C SOURCE FILE Test C_COMPILER_SUPPORT_FLAG__gencode failed with the following output:
Change Dir: /home/trash/Desktop/Paddle-Lite-develop/build_cuda/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/make" "cmTC_a7738/fast"
/usr/bin/make -f CMakeFiles/cmTC_a7738.dir/build.make CMakeFiles/cmTC_a7738.dir/build
make[1]: Entering directory '/home/trash/Desktop/Paddle-Lite-develop/build_cuda/CMakeFiles/CMakeTmp'
Building C object CMakeFiles/cmTC_a7738.dir/src.c.o
/usr/bin/cc   -fPIC -fno-omit-frame-pointer -Werror -Wall -Wextra -Wno-unused-parameter -Wno-unused-function -Wno-error=literal-suffix -Wno-error=sign-compare -Wno-error=unused-local-typedefs -Wno-error=ignored-attributes -Wno-error=terminate -Wno-error=int-in-bool-context -Wimplicit-fallthrough=0 -Wno-error=maybe-uninitialized -DC_COMPILER_SUPPORT_FLAG__gencode   -gencode -o CMakeFiles/cmTC_a7738.dir/src.c.o   -c /home/trash/Desktop/Paddle-Lite-develop/build_cuda/CMakeFiles/CMakeTmp/src.c
cc: error: unrecognized debug output level 'encode'
CMakeFiles/cmTC_a7738.dir/build.make:65: recipe for target 'CMakeFiles/cmTC_a7738.dir/src.c.o' failed
make[1]: *** [CMakeFiles/cmTC_a7738.dir/src.c.o] Error 1
make[1]: Leaving directory '/home/trash/Desktop/Paddle-Lite-develop/build_cuda/CMakeFiles/CMakeTmp'
Makefile:126: recipe for target 'cmTC_a7738/fast' failed
make: *** [cmTC_a7738/fast] Error 2

Source file was:
int main(void) { return 0; }
Performing C SOURCE FILE Test C_COMPILER_SUPPORT_FLAG_arch_compute_62,code_sm_62 failed with the following output:
Change Dir: /home/trash/Desktop/Paddle-Lite-develop/build_cuda/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/make" "cmTC_9714c/fast"
/usr/bin/make -f CMakeFiles/cmTC_9714c.dir/build.make CMakeFiles/cmTC_9714c.dir/build
make[1]: Entering directory '/home/trash/Desktop/Paddle-Lite-develop/build_cuda/CMakeFiles/CMakeTmp'
Building C object CMakeFiles/cmTC_9714c.dir/src.c.o
/usr/bin/cc   -fPIC -fno-omit-frame-pointer -Werror -Wall -Wextra -Wno-unused-parameter -Wno-unused-function -Wno-error=literal-suffix -Wno-error=sign-compare -Wno-error=unused-local-typedefs -Wno-error=ignored-attributes -Wno-error=terminate -Wno-error=int-in-bool-context -Wimplicit-fallthrough=0 -Wno-error=maybe-uninitialized -DC_COMPILER_SUPPORT_FLAG_arch_compute_62,code_sm_62   arch=compute_62,code=sm_62 -o CMakeFiles/cmTC_9714c.dir/src.c.o   -c /home/trash/Desktop/Paddle-Lite-develop/build_cuda/CMakeFiles/CMakeTmp/src.c
cc: error: arch=compute_62,code=sm_62: No such file or directory
CMakeFiles/cmTC_9714c.dir/build.make:65: recipe for target 'CMakeFiles/cmTC_9714c.dir/src.c.o' failed
make[1]: *** [CMakeFiles/cmTC_9714c.dir/src.c.o] Error 1
make[1]: Leaving directory '/home/trash/Desktop/Paddle-Lite-develop/build_cuda/CMakeFiles/CMakeTmp'
Makefile:126: recipe for target 'cmTC_9714c/fast' failed
make: *** [cmTC_9714c/fast] Error 2

Source file was:
int main(void) { return 0; }

**Comment by haozech** [comment]
你好！感谢反馈，jetson设备目前不能使用paddle-lite，请使用paddle-inference预测库进行部署~
