### ISSUE TITLE
怎样获取用户训练作业信息

### ISSUE THREAD

**Issue by KingCSer** [PaddlePaddle/Paddle#28798]
版本：paddle-1.8.5-gpu-cuda10.0-cudnn7
问题：
1）怎样获取用户训练作业共有多少个epoch，以及当前进行到第几个epoch？
2）怎样得知用户当前所用gpu号，以及剩余可用gpu号？
3）怎样获取用户训练程序的完成状态？（完成 or 未完成）

**Comment by haozech** [comment]
你好，感谢反馈。您所提的这几个问题，在正常情况下应该都是由用户自己定义/掌握的。您是在什么环境进行训练的呢？是否使用的是Ai Studio

**Comment by KingCSer** [comment]
> 你好，感谢反馈。您所提的这几个问题，在正常情况下应该都是由用户自己定义/掌握的。您是在什么环境进行训练的呢？是否使用的是Ai Studio

对，正常情况下是由用户程序定义的，但是因项目需要，我们想要在别的配置文件里单独定义这些接口，不知道paddle里是否有相关API和可参考的资料，谢谢！

**Comment by saxon-zh** [comment]
@yangkangkangkang 咱们这几个问题中涉及到的功能接口具体是什么样的使用场景呀，辛苦完整描述下哈，我们来针对性的评估下功能需求
