### ISSUE TITLE
Add top k classification error on conv

### ISSUE THREAD

**Issue by gangliao** [PaddlePaddle/Paddle#288]
integrate this code into github repo

**Comment by wangkuiyi** [comment]
@gangliao 请说明

1. 为什么会有这个需求，
1. 为了解决它需要做什么

给定这些信息，我们才有依据如何处理，比如放进哪个milestone里。

**Comment by gangliao** [comment]
@wangkuiyi 
This request comes from image classification that already been implemented four months ago,
which needs a little change to merge "Modern" PaddlePaddle.

**Comment by wangkuiyi** [comment]
@gangliao As this has been done months ago, I guess there has been a PR? Can we post a link to the PR here?

**Comment by gangliao** [comment]
It's in our internal `cooder` review platform.

**Comment by qingqing01** [comment]
Close this issue, since it has been supported.
