### ISSUE TITLE
wrong number or type of arguments for overloaded function 'IVector_create'

### ISSUE THREAD

**Issue by youan1** [PaddlePaddle/Paddle#2881]
[script_train_test_file.zip](https://github.com/PaddlePaddle/Paddle/files/1148433/script_train_test_file.zip)
相应的脚本与训练测试数据都已经提供，谢谢！

![image](https://user-images.githubusercontent.com/30172793/28213258-e35a032c-68d7-11e7-994d-af04ec15e50e.png)

**Comment by hedaoyuan** [comment]
这个错误与这个issue基本一致，https://github.com/PaddlePaddle/Paddle/issues/2422。
应该是feeding 这个地方有问题。不过你这个config 600多行看起比较费劲，稍等我看一下。

**Comment by youan1** [comment]
看了上面这个帖子，他的解释是"lstm 的输出是一个序列，配置中没有 pooling 层，label 这个 data_layer 的 type 不对，应该是 integer_value_sequence"，但是我脚本里没有lstm，就普通神经网络，不会是输出序列，感觉跟我的问题还是不太一样，麻烦帮忙分析一下

**Comment by hedaoyuan** [comment]
最后一个解释是comment解释的是feeding写错了，label对应的slot写错了。你这个config里面有32个slot，每个slot的数据是否都是跟对应layer的配置和你给的样本中的一样的，这个我还在看。

**Comment by youan1** [comment]
最后一个解释的feeding错误我看了的，跟我的不太一样，他的错误是用了一个feeding dict ，但是编码重复了
feeding = {'status': 0, 'label': 0} 
has a bug. It should be like this:

feeding = {'status': 0, 'label': 1}
我用的是一个feeding数组，不应该存在上述编码重复的问题

**Comment by hedaoyuan** [comment]
那个是由于feed时序号填错了，导致feed给label这个slot的数据类型与label这个layer要的数据类型不一致。我怀疑你的这些slot中也是有类似不一致的问题。

**Comment by youan1** [comment]
嗯，在调试过程中，我看到前面有一些样本是处理成功了的，然后数据是一个脚本产出的，所以不知道这个会不会是原因

**Comment by lcy-seso** [comment]
我建议使用问题请首先自行调试。

**Comment by youan1** [comment]
在issue中贴图片的问题，您说的对，这样使得答疑结果不能被大家更好的共享，下次会注意

另外参考文档使用integer_value_sequence时，其解释为"Data type of a sequence of integer",这里有不解，认为是输入是一个序列类型（类比dense_vector和dense_vector_sequence ）,所以才请paddle同学 帮忙看看

**Comment by lcy-seso** [comment]
Paddle v2 确实没有官方正式地文档来说明输入数据的应该如何组织，这是我们在文档方面的缺失。
