### ISSUE TITLE
使用docker安装paddle 1.8.5，然后安装parl，运行时报错paddle与cuda不适配

### ISSUE THREAD

**Issue by YeFeiyangx** [PaddlePaddle/Paddle#28841]
使用官网docker命令安装paddle，然后安装parl。出现如下错误:
CUDA_VISIBLE_DEVICES found gpu count: 1
Found non-empty CUDA_VISIBLE_DEVICES. 
But PARL found that Paddle was not complied with CUDA, which may cause issues. 
Thus PARL will not use GPU.

**Comment by haozech** [comment]
您好，从报错信息上来看首先您需要确认安装gpu版本的paddle还是cpu版本的，如果是gpu版本，那么您需要安装与cuda版本匹配的paddle，请参考这里 https://www.paddlepaddle.org.cn/documentation/docs/zh/install/Tables.html#whl-release  选择适合的whl包安装

**Comment by YeFeiyangx** [comment]
> 您好，从报错信息上来看首先您需要确认安装gpu版本的paddle还是cpu版本的，如果是gpu版本，那么您需要安装与cuda版本匹配的paddle，请参考这里 https://www.paddlepaddle.org.cn/documentation/docs/zh/install/Tables.html#whl-release 选择适合的whl包安装

嗯嗯，的确，docker里面的paddle包不大对。换一个版本，就没有那条报错信息了。但是程序卡在了

nvidia-smi -L found gpu count: 1 处，只显示了
W1121 08:29:54.839927    67 device_context.cc:236] Please NOTE: device: 0, CUDA Capability: 86, Driver API Version: 11.1, Runtime API Version: 9.0
W1121 08:29:54.841588    67 device_context.cc:244] device: 0, cuDNN Version: 7.6.
两条警告，就再也不往下运行了，请问是怎么回事？

**Comment by YeFeiyangx** [comment]
一段时间后跳出如下信息。。。。。  
File "/paddle/agv_agent.py", line 28, in __init__
    super(Agent, self).__init__(algorithm)
  File "/usr/local/lib/python3.7/site-packages/parl/core/fluid/agent.py", line 85, in __init__
    self.fluid_executor.run(fluid.default_startup_program())
  File "/usr/local/lib/python3.7/site-packages/paddle/fluid/executor.py", line 780, in run
    six.reraise(*sys.exc_info())
  File "/usr/local/lib/python3.7/site-packages/six.py", line 703, in reraise
    raise value
  File "/usr/local/lib/python3.7/site-packages/paddle/fluid/executor.py", line 775, in run
    use_program_cache=use_program_cache)
  File "/usr/local/lib/python3.7/site-packages/paddle/fluid/executor.py", line 822, in _run_impl
    use_program_cache=use_program_cache)
  File "/usr/local/lib/python3.7/site-packages/paddle/fluid/executor.py", line 899, in _run_program
    fetch_var_name)
RuntimeError: parallel_for failed: no kernel image is available for execution on the device

**Comment by hello-web** [comment]
> > 您好，从报错信息上来看首先您需要确认安装gpu版本的paddle还是cpu版本的，如果是gpu版本，那么您需要安装与cuda版本匹配的paddle，请参考这里[https://www.paddlepaddle.org .cn / documentation / docs / zh / install / Tables.html＃whl-release](https://www.paddlepaddle.org.cn/documentation/docs/zh/install/Tables.html#whl-release)选择适合的whl包安装
> 
> 嗯嗯，的确，docker里面的paddle包不大对。换一个版本，就没有那条报错信息了。但是程序卡在了
> 
> nvidia-smi -L找到gpu计数：1处，只显示了
> W1121 08：29：54.839927 67 device_context.cc:236]请注意：设备：0，CUDA功能：86，驱动程序API版本：11.1，运行时API版本： 9.0
> W1121 08：29：54.841588 67 device_context.cc:244]设备：0，cuDNN版本：7.6。
> 两条警告，就再也不往下运行了，请问是怎么回事？

目前不支持30系列显卡，参考：https://github.com/PaddlePaddle/Paddle/issues/27530
