### ISSUE TITLE
Dataset类__getitem__()无法返回字典类型数据

### ISSUE THREAD

**Issue by HXia-XXL** [PaddlePaddle/Paddle#28881]
在Dataset类中定义 __getitem__()方法中，需要传很多数据。如果用return字典类型

` def  __getitem__():                             `
`      # process code                         `
`       sample：{                                 `
`                 ‘image1’：data1,            ` 
`                 'image2'：data2,             `
`                 'image3'：data3,             `
`                 'image4'：data4,}            `
`      return sample                             `

后面就无法通过Dataloader取出，报错：
`error blocking queue is killed because the data reader raises an exception`

只能返回List
`return image1,image2,image3`

在pytorch中可以返回字典类型数据，可能是方法中多了 __add__()这一个
`def __add__(self, other: 'Dataset[T_co]') -> 'ConcatDataset[T_co]':        `
`        return ConcatDataset([self, other])                                              `

**Comment by chenjiaoAngel** [comment]
DataLoader的底层实现不支持dict，只支持numpy array
可以通过返回numpy array的list格式进行支持

**Comment by HXia-XXL** [comment]
好的，感谢。
