### ISSUE TITLE
【2.0 API文档内测】DataLoader 文档问题

### ISSUE THREAD

**Issue by Mesilenceki** [PaddlePaddle/Paddle#28898]
文档问题描述：
paddle.io.DataLoader 文档评估

API文档描述是否清晰？
中文：5分，整体描述比较清楚；
英文：5分

参数说明是否清晰
中文：5分
英文：5分

返回/形状说明是否清晰
中文：5分，形状描写的很清楚，但是格式有些问题；
英文：5分

示例代码是否有效？
中文：4分，示例代码比较详细, example有点问题,需要预先在运行前设定静态图运行模式；
英文：4分

中英文内容是否一致？
一致

其他
无

整体评价
5分, DataLoader作为训练流程中必不可少的一步, 文档和示例代码介绍的比较详细, 代码需要点小的补充；

**Comment by skywalk163** [comment]
文档里的这句话我不明白：

from_generator ( feed_list=None, capacity=None, use_double_buffer=True, iterable=True, return_list=False, use_multiprocess=False, drop_last=True ) ¶
警告
这个API将在未来版本废弃，推荐使用支持多进程并发加速的 paddle.io.DataLoader

意思是说  from_generator  要被废弃吗 ？
