### ISSUE TITLE
Investigating profilers

### ISSUE THREAD

**Issue by gangliao** [PaddlePaddle/Paddle#289]
For PaddlePaddle, we use `REGISTER_TIMER_INFO` to set a timer for performance tuning.

For instance, the timer in `BilinearInterpLayer.cpp` to statistics:

``` c++
  {
    REGISTER_TIMER_INFO("FwBilinearInterpTimer", getName().c_str());
    outV->bilinearForward(*inV, inImgH_, inImgW_, outImgH_, outImgW_,
      numChannels_);
  }
```

But, there exist some state of the art profilers to tune performance more intuitively.
for instance, `nvvp`[performance analysis GUI] and `nvprof` [command line tools].

I will add a doc section about how to use profiler on PaddlePaddle for our teams and developers before Milestone 0.8.2.

**Comment by wangkuiyi** [comment]
@gangliao 是已经决定了要改用用哪个 profiler 了吗？如果已经决定过了，比如用 nvprof，那么标题可以改成 "Document Paddle profiling using nvprof"。如果还没有，标题应该是 "Investigate profilers"，然后列出你准别调研的profilers，以及对应的 URL。

**Comment by gangliao** [comment]
@wangkuiyi 

Since Paddle is heavily dependent on GPU hardwares, it's better to use NV related profilers.

nvvp and nvprof:
https://developer.nvidia.com/nvidia-visual-profiler
http://people.maths.ox.ac.uk/gilesm/cuda/lecs/NV_Profiling_lowres.pdf
http://www.robots.ox.ac.uk/~seminars/seminars/Extra/2015_10_08_JeremyAppleyard.pdf
