### ISSUE TITLE
tensor问题

### ISSUE THREAD

**Issue by lyn1225** [PaddlePaddle/Paddle#28903]
paddle中创建NCHW张量后，经过resize_bilinear或adaptive_pool2d处理后（处理后的形状保持一致），实际的数据会发生变化吗？经过验证在pytorch中数据不会发生变化，但是不知道在paddle中是否也是不变的，请大佬解答。

**Comment by chenjiaoAngel** [comment]
只要保证处理前后shape一样 ，数据不会变化
