### ISSUE TITLE
The input of 'fc' layer must be matrix

### ISSUE THREAD

**Issue by newaccount3** [PaddlePaddle/Paddle#2892]
[script_train_test_file.zip]script_train_test_file.zip

错误如题， 相应脚本和数据已经提供， 搜索到俩篇同类型issue

issues/708， 解决办法是将integer_value_sequence改为sparse_non_value_slot ，但查文档后发现sparse_non_value_slot和sparse_binary_vector描述完全一样，而sparse_binary_vector在上一个issue中paddle同学已经不建议使用

issues/331，解决办法为It means that input.value is nullptr. So check you data and dataprovider，这个是否意味着 输入slot不能为null。如果数据slot为空（存在这种情况），该如何处理

另外该错误是否与别的slot类型配置错误有关，目前数据输入有三种，参考文档后分别使用下面的数据类型1）固定长度稠密数据，使用的是dense_vector，2）稀疏无序数据，比如关键词的词袋类型，使用的 integer_value_sequence, 用于做embedding 3) 稀疏无序带权数据，如37:0.768 43:0.656等，使用的是 sparse_vector，连接fc layer，请问这样使用是否合理

谢谢！

**Comment by qingqing01** [comment]
Duplicated with #2889 , so close.
