### ISSUE TITLE
paddle.nn no attributes AdaptiveAvgPool2d

### ISSUE THREAD

**Issue by jordan2013** [PaddlePaddle/Paddle#28942]
为使您的问题得到快速解决，在建立Issues前，请您先通过如下方式搜索是否有相似问题:【搜索issue关键字】【使用labels筛选】【官方文档】

如果您没有查询到相似问题，为快速解决您的提问，建立issue时请提供如下细节信息：
- 标题：简洁、精准概括您的问题，例如“Insufficient Memory xxx" ”
- 版本、环境信息：
    1）PaddlePaddle版本：PaddlePaddle 2.0.0rc
    2）CPU：AiStudio
    3）GPU：AiStudio
    4）系统环境：AiStudio python 3.7 PaddleSeg0.6/0.7
- 训练信息
    1）单卡
    2）显存信息
    3）Operator信息
- 复现信息：PaddelSeg0.6/0.7的动态图，使用hrnet作为BackBone，has_se设置为True时
- 问题描述：
    PaddleSeg/dygraph/paddleseg/models/backbones/hrnet.py文件中421行，如下语句
import paddle
import paddle.nn as nn
import paddle.nn.functional as F
.......
      self.pool2d_gap = nn.AdaptiveAvgPool2d(1)

报错：paddle.nn no attributes AdaptiveAvgPool2d

Thank you for contributing to PaddlePaddle.
Before submitting the issue, you could search issue in the github in case that there was a similar issue submitted or resolved before.
If there is no solution,please make sure that this is a training issue including the following details:
**System information**
-PaddlePaddle version （eg.1.1）or CommitID
-CPU: including CPUMKL/OpenBlas/MKLDNN version
-GPU: including CUDA/CUDNN version
-OS Platform (eg.Mac OS 10.14)
-Other imformation: Distriuted training/informantion of operator/
Graphics card storage
Note: You can get most of the information by running [summary_env.py](https://github.com/PaddlePaddle/Paddle/blob/develop/tools/summary_env.py). 
**To Reproduce**
Steps to reproduce the behavior
**Describe your current behavior**
**Code to reproduce the issue**
**Other info / logs**

**Comment by HXia-XXL** [comment]
AdaptiveAvgPool2d()是xx火炬的函数，paddle里面是AdaptiveAvgPool2D()

**Comment by jordan2013** [comment]
醉了。PaddleSeg0.6/0.7中，把自家的API拼成了别家的
