### ISSUE TITLE
Roll 函数的实现现在有gpu支持了吗？ 

### ISSUE THREAD

**Issue by OleNet** [PaddlePaddle/Paddle#28965]
如题：Roll 函数的实现现在有gpu支持了吗？ 
2个月前的roll函数， 还是cpu实现，所以会很慢
现在有gpu支持了吗？ 如果没有，在哪个版本会支持呢？

**Comment by qili93** [comment]
Roll函数在最新的2.0RC版本中已经有CUDA Kernel的实现了。
