### ISSUE TITLE
运行时间问题

### ISSUE THREAD

**Issue by lizhaohu** [PaddlePaddle/Paddle#28970]
请问同样的配置，python版本和c++版本耗时差别大吗？在什么级别。比如我是用python+paddle，7层cnn+720p+1060显卡，一次预测，耗时100ms，那么假设我换成c++版本的耗时大概是多少呢？

**Comment by qili93** [comment]
推理的话Python在启动的时候耗时会比C++多一点，但是启动之后只计算每次预测的耗时的话和C++不会有特别明显的差异。
