### ISSUE TITLE
paddle2.0-rc 版本的安装

### ISSUE THREAD

**Issue by zhixuzhichang** [PaddlePaddle/Paddle#28987]
Python3.7
Centos 6.3
安装 paddle2.0-rc 后, import paddle 后报错如下:

ImportError: /opt/compiler/gcc-4.8.2/lib/libstdc++.so.6: version `CXXABI_1.3.8' not found (required by /ssd2/liujiqiang/tools/paddle/paddle2.0-rc/lib/python3.7/site-packages/paddle/fluid/core_avx.so)

谢谢。

**Comment by qili93** [comment]
这个应该是GCC版本过低导致的，建议升级GCC版本
