### ISSUE TITLE
Dataloader报错信息提示

### ISSUE THREAD

**Issue by habout632** [PaddlePaddle/Paddle#29014]
我在使用Ｄataloader Dataset过程中经常遇到这个异常，这个异常很不友好　不知道哪里报错了．找了半天最后发现是
Transform过程中提示　自定义Dataset出错了　这个异常提示　我觉得可以更详细一点

paddle.fluid.core_avx.EnforceNotMet: 

--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
0   std::thread::_State_impl<std::thread::_Invoker<std::tuple<ThreadPool::ThreadPool(unsigned long)::{lambda()#1}> > >::_M_run()
1   std::__future_base::_State_baseV2::_M_do_set(std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> ()>*, bool*)
2   paddle::operators::reader::PyReader::ReadNext(std::vector<paddle::framework::LoDTensor, std::allocator<paddle::framework::LoDTensor> >*)
3   paddle::operators::reader::BlockingQueue<std::vector<paddle::framework::LoDTensor, std::allocator<paddle::framework::LoDTensor> > >::Receive(std::vector<paddle::framework::LoDTensor, std::allocator<paddle::framework::LoDTensor> >*)
4   paddle::platform::EnforceNotMet::EnforceNotMet(std::string const&, char const*, int)
5   paddle::platform::GetCurrentTraceBackString[abi:cxx11]()

Error Message Summary:
----------------------
FatalError: Blocking queue is killed because the data reader raises an exception.
  [Hint: Expected killed_ != true, but received killed_:1 == true:1.] (at /paddle/paddle/fluid/operators/reader/blocking_queue.h:154)

**Comment by T8T9** [comment]
您好，能否提供一个完整的测试程序，或完整的错误信息？

**Comment by chenwhql** [comment]
您好，DataLoader这边的处理逻辑在子线程和子进程中处理的居多，然后子进程和子线程会抛出自己的错误，最后主进程发现子进程出错会报这个，真正的报错提示应该在这段报错的上面，您看看这段报错上面是否由您需要的提示

这个后续我们也想办法优化下，感谢反馈

**Comment by Talon330** [comment]
同样遇到dataset中含有transforms就会出现上述报错，暂时只能设置num_workers=0来解决，请问您是如何解决这个问题的呢？

**Comment by FredHuang16** [comment]
问题解决了吗
