### ISSUE TITLE
paddle 2.0正式版什么时候发布啊，有时间表吗，会支持cuda 11吗？

### ISSUE THREAD

**Issue by David20160511** [PaddlePaddle/Paddle#29017]
你好：
我的机器上装的RTX 3080的显卡，我装了cuda 10, paddlepaddle-gpu==1.8.5.post107 , 但是现在运行代码报错。我看issue中有人回答说paddle 2.0正式版会支持cuda 11，是吗？想确认一下会支持吗，2.0正式版什么时候会发布呢？

**Comment by T8T9** [comment]
应该没有测试过，如果cuda11 和cuda 10 不兼容的话，就不支持。paddle 2.0 将于 12月初发布，支持的特性可参考：

https://www.paddlepaddle.org.cn/documentation/docs/zh/2.0-rc/release_note_cn.html
https://www.paddlepaddle.org.cn/documentation/docs/zh/2.0-rc/install/index_cn.html
