### ISSUE TITLE
 模型训练中出现NAN

### ISSUE THREAD

**Issue by menghou** [PaddlePaddle/Paddle#29025]
![image](https://user-images.githubusercontent.com/9972335/100064617-bc46c680-2e6d-11eb-87bf-f09f66050ef3.png)

**Comment by T8T9** [comment]
请把您的环境信息，paddle版本信息发出来，最好附上产生这个问题的demo

**Comment by menghou** [comment]
![image](https://user-images.githubusercontent.com/9972335/100071475-0fbd1280-2e76-11eb-83ae-e77ccfa325bd.png)

**Comment by menghou** [comment]
> 请把您的环境信息，paddle版本信息发出来，最好附上产生这个问题的demo

demo是把代码附上吗

**Comment by T8T9** [comment]
> > 请把您的环境信息，paddle版本信息发出来，最好附上产生这个问题的demo
> 
> demo是把代码附上吗

方便的话可以贴一个与业务无关的可复现这个问题的代码，方便排查。

**Comment by T8T9** [comment]
可参考 https://www.paddlepaddle.org.cn/documentation/docs/zh/advanced_guide/flags/check_nan_inf_cn.html 排查
