### ISSUE TITLE
PaddlePaddle applications and threads

### ISSUE THREAD

**Issue by jczaja** [PaddlePaddle/Paddle#29037]
When PaddlePaddle is used from multiple threads e.g. each thread(external to PaddlePaddle) is doing inference. is it possible that  threads are sharing one instance of Executor/Naive Executor or each thread is keeping its own instance of executor?

We could optimize caching of oneDNN objects by reducing key e.g. making thread ID optional part of the key if only when there is muti-thread inference (each external thread is using PaddlePaddle) each thread is having its own NaiveExecutor not that NaiveExecutor is shared among threads.

**Comment by luotao1** [comment]
> is it possible that threads are sharing one instance of Executor/Naive Executor or each thread is keeping its own instance of executor

each thread is keeping its own instance of executor. You can refer to our official inference example. https://www.paddlepaddle.org.cn/documentation/docs/en/advanced_guide/inference_deployment/inference/native_infer_en.html#tuning-with-multi-thread
![image](https://user-images.githubusercontent.com/6836917/100179958-126d4580-2f12-11eb-90ba-37fa4a4cffe6.png)

**Comment by jczaja** [comment]
thanks
