### ISSUE TITLE
how could I compile the source to support cuda 11.1?

### ISSUE THREAD

**Issue by chikiuso** [PaddlePaddle/Paddle#29071]
hi, how could I compile the source to support cuda 11.1? or when will paddlepaddle support cuda 11.1? thanks for your help.

**Comment by T8T9** [comment]
paddlepaddle hasn't been tested on cuda11.1 yet. You can pay attention to paddle-2.0 release note to get latest infomation:

https://www.paddlepaddle.org.cn/documentation/docs/zh/2.0-rc/release_note_cn.html
https://www.paddlepaddle.org.cn/documentation/docs/zh/2.0-rc/install/index_cn.html
