### ISSUE TITLE
Profiler 在 CUDA10.1 环境下 频发 Segmentation fault 

### ISSUE THREAD

**Issue by Eric-seu** [PaddlePaddle/Paddle#29082]
问题环境：
    1）PaddlePaddle版本：develop
    3）GPU：cuda10.1 cudnn7.6.5
    4）ubuntu16.04， gcc5.4.0
训练设置：
    4）模型： ResNet101 、 ResNet50（如果是小的dome模型， 没有问题，大模型才出问题）
    5） profiler 记录 10 个 step
 
在该环境下可以正常训练、预测，但是如果运行 paddle profiler， 则会出现如下错误 （概率大概 50%）， 有时能在log 中打印profiler 信息，但是无法生成 profiler （timeline）文件。

相同代码换成 cuda10.0 环境则没有问题，能正常profiler 且生成 timeline 文件， cuda10.1 就报错。

worker0：
--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
0   paddle::framework::SignalHandle(char const*, int)
1   paddle::platform::GetCurrentTraceBackString[abi:cxx11]()

----------------------
Error Message Summary:
----------------------
FatalError: `Segmentation fault` is detected by the operating system.
  [TimeInfo: *** Aborted at 1606225766 (unix time) try "date -d @1606225766" if you are using GNU date ***]
  [SignalInfo: *** SIGSEGV (@0x7165) received by PID 1115 (TID 0x7f4129fff700) from PID 29029 ***]

worker1：
--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
0   paddle::platform::DisableProfiler(paddle::platform::EventSortingKey, std::string const&)
1   paddle::platform::DeviceTracerImpl::Disable()
2   cuptiActivityFlushAll
3   paddle::framework::SignalHandle(char const*, int)
4   paddle::platform::GetCurrentTraceBackString[abi:cxx11]()

----------------------
Error Message Summary:
----------------------
FatalError: `Termination signal` is detected by the operating system.
  [TimeInfo: *** Aborted at 1606225774 (unix time) try "date -d @1606225774" if you are using GNU date ***]
  [SignalInfo: *** SIGTERM (@0x3b2) received by PID 1130 (TID 0x7ff93178d700) from PID 946 ***]

**Comment by luotao1** [comment]
关于这个问题， @wanghuancoder 当时做了一个完整的定位。结论是：怀疑是CUDA10.1的bug，待Paddle升级到CUDA10.2或CUDA11时，再验证一下该问题是否存在。
### 一、代码问题定位：

Bug的程序执行路径为：

1.在Profiler的Reset/Disable函数被调用时，会执行CUPTI的cuptiActivityFlushAll
https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/fluid/platform/device_tracer.cc#L439
https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/fluid/platform/device_tracer.cc#L602

2.cuptiActivityFlushAll将阻塞等待，并触发CPUTI，将捕获的所有CUDA Event通过bufferCompleted函数通知给Paddle。这个回调机制，CUPTI有一个单独线程负责回调。

https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/fluid/platform/device_tracer.cc#L175

3.**在异常发生时，cuptiActivityFlushAll触发了回调线程启动回调。但在还没有回调到bufferCompleted函数时，在CPUTI内部，就崩溃了。因此整个调用栈中没有Paddle代码**。
```
Warning: PaddlePaddle catches a failure signal, it may not work properly

You could check whether you killed PaddlePaddle thread/process accidentally or report the case to PaddlePaddle
The detail failure signal is:
*** Aborted at 1595935555 (unix time) try "date -d @1595935555" if you are using GNU date ***
PC: @                0x0 (unknown)
*** SIGSEGV (@0x4c90) received by PID 19558 (TID 0x7f91b9ba8700) from PID 19600; stack trace: ***
    @     0x7f9125b379de google::(anonymous namespace)::FailureSignalHandler()
    @     0x7f91ca3d1390 (unknown)
    @     0x7f91bbcf8d4e (unknown)
    @     0x7f91bbcfc158 (unknown)
    @     0x7f91bbe735f8 (unknown)
    @     0x7f91ca3c76ba start_thread
    @     0x7f91c99ed41d clone
    @                0x0 (unknown)
Segmentation fault
```

### 二、环境对比

开发机复现情况：

1. 能够复现
```
Please NOTE: device: 0, CUDA Capability: 61, Driver API Version: 10.1, Runtime API Version: 10.1
device: 0, cuDNN Version: 7.6.
GCC8.2
cmake .. -DPY_VERSION=2.7 -DWITH_GPU=ON -DPADDLE_WITH_NCCL=ON -DWITH_TESTING=ON -DCMAKE_BUILD_TYPE=Release
```

2.不能够复现
```
Please NOTE: device: 0, CUDA Capability: 61, Driver API Version: 10.1, Runtime API Version: 10.0
device: 0, cuDNN Version: 7.5.
GCC5.4
cmake .. -DPY_VERSION=2.7 -DWITH_GPU=ON -DPADDLE_WITH_NCCL=ON -DWITH_TESTING=ON -DCMAKE_BUILD_TYPE=Release
```

### 三、其它补充说明

1. 效率云去掉-DWITH_COVERAGE=ON，一样有问题。
2. 去掉ctest，写一个demo，保持与单测网络一致，问题消失（测了20次），因此不影响用户使用。
3. **锁定代码路径的方法为：打印bufferCompleted的线程ID，与崩溃时错误栈线程ID相等。而且必在cuptiActivityFlushAll时触发**。
4. **压缩单测网络结构，到极简单的网络，从必现到概率复现**。
5. 注释掉EnableActivity中的逻辑（也就是不回调任何Event）是可以正常运行的。
6. 注释bufferCompleted中的逻辑保留free(buffer)，仍旧崩溃。因此与我们的代码无关。
7. Executor单测，ctest没报问题。但有异常抛出：
```
    652: /Paddle/build_coverage/python/paddle/utils/profiler.py:110: UserWarning: Profiler is not disabled becuase following exception:
    652: disable_profiler(): incompatible function arguments. The following argument types are supported:
    652:     1. (arg0: paddle.fluid.core_avx.EventSortingKey, arg1: unicode) -> None
    652: 
    652: Invoked with: EventSortingKey.kDefault, None
    652:   format(e))

```

### 改进措施：

**我们怀疑是CUDA10.1的bug，待Paddle升级到CUDA10.2或CUDA11时，再验证一下该问题是否存在。**

related #25200

**Comment by Rayaction** [comment]
> 关于这个问题， @wanghuancoder 当时做了一个完整的定位。结论是：怀疑是CUDA10.1的bug，待Paddle升级到CUDA10.2或CUDA11时，再验证一下该问题是否存在。
> 
> ### 一、代码问题定位：
> Bug的程序执行路径为：
> 
> 1.在Profiler的Reset/Disable函数被调用时，会执行CUPTI的cuptiActivityFlushAll
> https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/fluid/platform/device_tracer.cc#L439
> https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/fluid/platform/device_tracer.cc#L602
> 
> 2.cuptiActivityFlushAll将阻塞等待，并触发CPUTI，将捕获的所有CUDA Event通过bufferCompleted函数通知给Paddle。这个回调机制，CUPTI有一个单独线程负责回调。
> 
> https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/fluid/platform/device_tracer.cc#L175
> 
> 3.**在异常发生时，cuptiActivityFlushAll触发了回调线程启动回调。但在还没有回调到bufferCompleted函数时，在CPUTI内部，就崩溃了。因此整个调用栈中没有Paddle代码**。
> 
> ```
> Warning: PaddlePaddle catches a failure signal, it may not work properly
> 
> You could check whether you killed PaddlePaddle thread/process accidentally or report the case to PaddlePaddle
> The detail failure signal is:
> *** Aborted at 1595935555 (unix time) try "date -d @1595935555" if you are using GNU date ***
> PC: @                0x0 (unknown)
> *** SIGSEGV (@0x4c90) received by PID 19558 (TID 0x7f91b9ba8700) from PID 19600; stack trace: ***
>     @     0x7f9125b379de google::(anonymous namespace)::FailureSignalHandler()
>     @     0x7f91ca3d1390 (unknown)
>     @     0x7f91bbcf8d4e (unknown)
>     @     0x7f91bbcfc158 (unknown)
>     @     0x7f91bbe735f8 (unknown)
>     @     0x7f91ca3c76ba start_thread
>     @     0x7f91c99ed41d clone
>     @                0x0 (unknown)
> Segmentation fault
> ```
> 
> ### 二、环境对比
> 开发机复现情况：
> 
> 1. 能够复现
> 
> ```
> Please NOTE: device: 0, CUDA Capability: 61, Driver API Version: 10.1, Runtime API Version: 10.1
> device: 0, cuDNN Version: 7.6.
> GCC8.2
> cmake .. -DPY_VERSION=2.7 -DWITH_GPU=ON -DPADDLE_WITH_NCCL=ON -DWITH_TESTING=ON -DCMAKE_BUILD_TYPE=Release
> ```
> 
> 2.不能够复现
> 
> ```
> Please NOTE: device: 0, CUDA Capability: 61, Driver API Version: 10.1, Runtime API Version: 10.0
> device: 0, cuDNN Version: 7.5.
> GCC5.4
> cmake .. -DPY_VERSION=2.7 -DWITH_GPU=ON -DPADDLE_WITH_NCCL=ON -DWITH_TESTING=ON -DCMAKE_BUILD_TYPE=Release
> ```
> 
> ### 三、其它补充说明
> 1. 效率云去掉-DWITH_COVERAGE=ON，一样有问题。
> 2. 去掉ctest，写一个demo，保持与单测网络一致，问题消失（测了20次），因此不影响用户使用。
> 3. **锁定代码路径的方法为：打印bufferCompleted的线程ID，与崩溃时错误栈线程ID相等。而且必在cuptiActivityFlushAll时触发**。
> 4. **压缩单测网络结构，到极简单的网络，从必现到概率复现**。
> 5. 注释掉EnableActivity中的逻辑（也就是不回调任何Event）是可以正常运行的。
> 6. 注释bufferCompleted中的逻辑保留free(buffer)，仍旧崩溃。因此与我们的代码无关。
> 7. Executor单测，ctest没报问题。但有异常抛出：
> 
> ```
>     652: /Paddle/build_coverage/python/paddle/utils/profiler.py:110: UserWarning: Profiler is not disabled becuase following exception:
>     652: disable_profiler(): incompatible function arguments. The following argument types are supported:
>     652:     1. (arg0: paddle.fluid.core_avx.EventSortingKey, arg1: unicode) -> None
>     652: 
>     652: Invoked with: EventSortingKey.kDefault, None
>     652:   format(e))
> ```
> 
> ### 改进措施：
> **我们怀疑是CUDA10.1的bug，待Paddle升级到CUDA10.2或CUDA11时，再验证一下该问题是否存在。**
> 
> related #25200

这个问题10.2的cuda还存在啊///
