### ISSUE TITLE
infer时报错float point exception (core dumped)

### ISSUE THREAD

**Issue by zhangzhenyue1** [PaddlePaddle/Paddle#2909]
版本：paddle:0.10.0rc3-noavx
代码：https://github.com/Superjom/models-1/tree/ctr2/ctr 针对自己的input数据做了一些修改
问题：在mac上安装这个版本，跑代码，能正常出结果，将代码和数据迁移到内网机器上(无avx)，报下面错误。
暂时也不法确定是机器问题还是数据问题。
代码在[ctr.zip](https://github.com/PaddlePaddle/Paddle/files/1151613/ctr.zip)，执行命令可以看run.sh

![wechatimg13](https://user-images.githubusercontent.com/5304770/28205382-58218762-68b4-11e7-8008-513a4645b23e.jpeg)

**Comment by Superjom** [comment]
paddle版本问题，你的机器不支持AVX
https://github.com/PaddlePaddle/Paddle/issues/1358

**Comment by zhangzhenyue1** [comment]
有办法解决这个问题吗？只能换机器了？

**Comment by Superjom** [comment]
paddle 安装非 avx 的版本？ 具体的安装方法参考下文档吧

**Comment by zhangzhenyue1** [comment]
我在docker里面安装的是paddle:0.10.0rc3-noavx 这个版本。。

**Comment by Superjom** [comment]
浮点数溢出，可以通过调学习率啥的解决。

不过最简单的，你在内网机器上训练再预测试试

**Comment by zhangzhenyue1** [comment]
嗯，我是在内网机器上训练的。
我再试试调整下。

**Comment by zhangzhenyue1** [comment]
看起来是数据问题。做了两个尝试：
1. 换了一种类型的数据
2. 还是用原来数据，不用lr，只用dnn
2种方法都能在内网机器正常运行

不过还是不清楚train和infer是同一份训练数据，为啥train不报错，infer报错

**Comment by Jarlonyan** [comment]
请问，您最后找到原因了吗？？@zhangzhenyue1

**Comment by zhangzhenyue1** [comment]
没有了。

**Comment by buptwds** [comment]
我也遇到这个问题，请问如何解决，用的例子里ctr的那个Wide&Deep模型

**Comment by zhangzhenyue1** [comment]
我前面总结了呀

**Comment by buptwds** [comment]
最近发现了这个问题可能的原因，train和infer实现的方式不同，infer时要求sparse_binary_vector读入数据，由于读入的是值为1的下标，因此必须从0开始，而train似乎没有要求必须从0开始。
