### ISSUE TITLE
请问不使用TRT的情况下，c++引擎推断中是否支持使用fp16精度？

### ISSUE THREAD

**Issue by peif1987** [PaddlePaddle/Paddle#29111]
c++ api的接口里看起来只有在使用TRT的部分可以直接使用FP16。

**Comment by yinhaofeng** [comment]
要看API是否注册了FP16，没有注册的话是不支持的

**Comment by peif1987** [comment]
> 要看API是否注册了FP16，没有注册的话是不支持的

我的流程是用pytorch训练的模型，导出为onnx后，用x2paddle转换为paddel模型后，再调用libpaddle_fluid.so去做推断。之前都是用TensorRT C++写推断代码的。

所以想了解有没有和TensorRT类似的方式，在模型序列化时就转为fp16的？
您指的API是否注册了FP16，是指算子吗？假如注册了FP16，应该怎么用呢？

**Comment by yinhaofeng** [comment]
你指的是不是tensorrt里面convert-to-uff工具将模型转换成fp16精度存储的功能

**Comment by peif1987** [comment]
> 你指的是不是tensorrt里面convert-to-uff工具将模型转换成fp16精度存储的功能

对，我用的是onnx转tensorrt的部分，应该和convert-to-uff是类似的。
可以用TensorRT里自带的trtexec将onnx模型序列化，trtexec有一个参数是--fp16，打开的话就能得到fp16精度的序列化模型。
也可以用python或者c++接口自己转换，原理和trtexec类似。
我就是想了解下paddle里有没有提供类似的功能，可以将模型直接保存为fp16精度的模型，模型大小也更小，推断时速度更快，精度没有损失。

**Comment by yinhaofeng** [comment]
https://www.paddlepaddle.org.cn/documentation/docs/zh/advanced_guide/performance_improving/inference_improving/paddle_tensorrt_infer.html#a-name-paddle-trt-paddle-trt-a
precision参数，类型：enum class Precision {kFloat32 = 0, kHalf, kInt8,};, 默认值为AnalysisConfig::Precision::kFloat32。指定使用TRT的精度，支持FP32（kFloat32），FP16（kHalf），Int8（kInt8）。若需要使用Paddle-TRT int8离线量化校准，需设定precision为 AnalysisConfig::Precision::kInt8, 且设置use_calib_mode 为true。

**Comment by peif1987** [comment]
我问的问题就是不使用TRT的情况下，Paddle的C++推断API里是否可以直接支持fp16。
你提到的这个是必须用TRT才可以， 假如我编译Paddle时不想添加TensorRT，Paddle能不能用fp16推断？
或者对于TRT还不支持的op, fp16要怎么支持呢？

**Comment by yinhaofeng** [comment]
目前还没有支持paddle原生的fp16推理，应该是只能用TRT。我们有计划支持，但目前还在等待开发。
