### ISSUE TITLE
多卡训练的时候报错

### ISSUE THREAD

**Issue by lebronlh** [PaddlePaddle/Paddle#29160]
![image](https://user-images.githubusercontent.com/48409264/100414856-bb07da80-30b5-11eb-95de-e1ff8129c161.png)
单卡训练的时候可以，我一旦使用多卡训练就会报错，我的使用方式是这样的。
# # 第2处改动，初始化并行环境
    #dist.init_parallel_env()
    # # 第3处改动，增加paddle.DataParallel封装
    #net = paddle.DataParallel(net)
，具体的报错我没截图下来，好像是说dist的初始化那里出错了

**Comment by dyning** [comment]
想问下单卡和多卡启动命令是什么？
