### ISSUE TITLE
麒麟上安装paddle1.8的时候，在最后一步make TARGET=ARMV8 -j$(nproc) 提示缺少cpuid.h文件

### ISSUE THREAD

**Issue by fumenglin** [PaddlePaddle/Paddle#29166]
在麒麟v10上安装paddel1.8版本时候，按你们源码安装教程，在后面编译时候，提示缺少cpuid.h文件；找了你们相关的文件有x86的cpuid.h文件，请问有arm版本的cpuid.h文件么？或者这个问题有其他解决方案呢？谢谢！

**Comment by jiweibo** [comment]
请尝试1.8.5版本，cmake的时候 加上WITH_XBYAK=OFF

**Comment by fumenglin** [comment]
我用2.0rc版本，就可以了。
