### ISSUE TITLE
paddle2.0-rc文档有漏洞和伪代码引起的不适

### ISSUE THREAD

**Issue by jhcgt4869** [PaddlePaddle/Paddle#29175]
地址：`https://www.paddlepaddle.org.cn/documentation/docs/zh/2.0-rc/guides/01_paddle2.0_introduction/basic_concept/tensor_introduction_cn.html#matrix2-d-tensor-rank2`
位置：其他属性Tensor的dtype
错误：

![image](https://user-images.githubusercontent.com/61859193/100433916-b7d11680-30d6-11eb-9206-972379233e88.png)
int64_tensor.dtype错写成了int64_tensor.dthpe

位置：上面介绍了通过Python数据来创建Tensor的方法，我们也可以通过 Numpy array 来创建Tensor
![image](https://user-images.githubusercontent.com/61859193/100434133-02eb2980-30d7-11eb-9656-81220c3ffbbf.png)
这个地方虽然说了是伪代码，但是没有标识看着很奇怪，也很别扭，其他地方都可以用就这个地方报错了，希望加以标注。

**Comment by dyning** [comment]
感谢您的反馈。我们尽快修复。
