### ISSUE TITLE
关于paddle 2.0rc版本paddle.fluid.layers.yolov3_loss的疑问【黄埔学院】

### ISSUE THREAD

**Issue by liuxi1007** [PaddlePaddle/Paddle#29194]
### 文档问题描述：
paddle.fluid.layers.yolov3_loss(x, gt_box, gt_label, anchors, anchor_mask, class_num, ignore_thresh, downsample_ratio, gt_score=None, use_label_smooth=True, name=None
请问paddle.fluid.layers.yolov3_loss模块中 anchors可以是长宽不相等的锚点吗？
分别如下设置是否可以，这两个要如何用在此模块中？
 "anchors": [[10.0, 13.0], [16.0, 30.0], [33.0, 23.0],  
                [30.0, 61.0], [62.0, 45.0], [59.0, 119.0],  
                [116.0, 90.0], [156.0, 198.0], [373.0, 326.0]], 
 "anchor_mask": [[0, 1, 2], [3, 4, 5], [6, 7, 8]],

**Comment by yghstill** [comment]
@liuxi1007 yolov3_loss支持长宽不相等的锚点的

**Comment by liuxi1007** [comment]
> @liuxi1007 yolov3_loss支持长宽不相等的锚点的
您好，请问报这个错是因为什么？
TypeError: trace(): incompatible function arguments. The following argument types are supported:
    1. (self: paddle.fluid.core_avx.Tracer, arg0: str, arg1: Dict[str, handle], arg2: Dict[str, handle], arg3: Dict[str, Variant], arg4: paddle::platform::XPUPlace, arg5: bool) -> None
    2. (self: paddle.fluid.core_avx.Tracer, arg0: str, arg1: Dict[str, handle], arg2: Dict[str, handle], arg3: Dict[str, Variant], arg4: paddle::platform::CUDAPlace, arg5: bool) -> None
    3. (self: paddle.fluid.core_avx.Tracer, arg0: str, arg1: Dict[str, handle], arg2: Dict[str, handle], arg3: Dict[str, Variant], arg4: paddle::platform::CPUPlace, arg5: bool) -> None

**Comment by liuxi1007** [comment]
谢谢。
