### ISSUE TITLE
A website for document updated in develop branch

### ISSUE THREAD

**Issue by luotao1** [PaddlePaddle/Paddle#292]
Now http://www.paddlepaddle.org/doc/ and http://www.paddlepaddle.org/doc_cn/ is auto-updated with master branch. However, there are some documents updated on develop branch, thus, should we provide another website for develop?

**Comment by reyoung** [comment]
In my opinion, the documentation should be stable for each release. So the docs of release branch should be the docs on website.

The nightly doc update for develop branch is also cool, but it is not very important currentlly. In milestone 0.8.1, there are many issues not done, and we should focus on them within two weeks.

It is very kind if you have time to contribute it, if the milestone has been done. 

Also, others' comment is needed, especially the nightly docs is necessary or not.

**Comment by luotao1** [comment]
http://www.paddlepaddle.org/develop/doc 和  http://www.paddlepaddle.org/develop/doc_cn 是develop分支的网站。
