### ISSUE TITLE
使用v2代码多机运行deepspeech2相关问题

### ISSUE THREAD

**Issue by THUHJ** [PaddlePaddle/Paddle#2920]
当在使用deepspech2进行多机实验的时候，将trainer = paddle.trainer.SGD的参数修改为is_local=False,同时设置了pserver_spec。在运行的时候提示

```text
Traceback (most recent call last):
  File "train.py", line 360, in <module>
    main()
  File "train.py", line 356, in main
    train()
  File "train.py", line 350, in train
    feeding=train_generator.feeding)
  File "/usr/local/lib/python2.7/dist-packages/paddle/v2/trainer.py", line 132, in train
    self.__pserver_spec__)
  File "/usr/local/lib/python2.7/dist-packages/paddle/v2/optimizer.py", line 79, in create_updater
    pserver_spec)
  File "/usr/local/lib/python2.7/dist-packages/paddle/v2/optimizer.py", line 52, in __create_new_remote_updater__
    self.__opt_conf__, pserver_spec)
  File "/usr/local/lib/python2.7/dist-packages/py_paddle/swig_paddle.py", line 2179, in createNewRemoteUpdater
    return _swig_paddle.ParameterUpdater_createNewRemoteUpdater(config, pserverSpec)
RuntimeError:  
```

RuntimeError之后没有别的内容了。请问这种现象可能是由于什么原因导致的呢？
还是现在多机只能使用像v1的代码吗？似乎没有找到针对v2多机的文档。

**Comment by Yancey1989** [comment]
1. 是否启动了parameter server？
1. v2 trainer在启动时需要在`paddle.init`时候增加PServer的地址，例如
```python
paddle.init(use_gpu=False,
    pservers="127.0.0.1:7164", 
    port=7164, 
    num_gradient_servers=${YOUR TRAINER COUNT}, 
    ports_num=1, 
    ports_num_for_sparse=1)
```

BTW, 会尽快补上v2多机的文档。

**Comment by THUHJ** [comment]
非常感谢！之前没有添加init，我试一下～

**Comment by THUHJ** [comment]
在init中增加了PServer地址的参数之后还是提示一样的error信息。

补充信息：
使用lsof -i命令可以看到
COMMAND    PID USER   FD   TYPE  DEVICE SIZE/OFF NODE NAME
paddle_ps 6081 root  121u  IPv4 3661426      0t0  TCP 8c4d2e756387:3000 (LISTEN)
paddle_ps 6081 root  123u  IPv4 3661428      0t0  TCP 8c4d2e756387:3001 (LISTEN)
Pserver确实在监听指定的端口。


不知道还有没有其他的可能？或者有什么方法可以追踪这个error的具体信息嘛，现在这个error没有别的提示信息不知道怎么调试好～

**Comment by Yancey1989** [comment]
@THUHJ 能贴下你PServer的启动参数么？另外可以把`paddle.trainer.SGD()`中`pserver_spec`这个参数起到，只在`paddle.init`时指定PServer的地址。

**Comment by THUHJ** [comment]
PS启动参数：
paddle pserver --num_gradient_servers 1 \
 --nics eth0 \
 --port 3000 \
 --ports_num 1 \
 --ports_num_for_sparse 1

trainer = paddle.trainer.SGD(
        cost=cost, parameters=parameters, update_equation=optimizer,
                is_local=False,
        pserver_spec="10.30.40.109:3000")

 paddle.init(use_gpu=args.use_gpu, trainer_count=args.trainer_count,
        pservers="10.30.40.109:3000",
        port=3000, 
        num_gradient_servers=1, 
        ports_num=1, 
        ports_num_for_sparse=1)
    train()

本机的ip就是10.30.40.109

**Comment by typhoonzero** [comment]
@THUHJ 目前在创建trainer时先不要使用`pserver_spec="10.30.40.109:3000"`这个参数，这个参数是正在开发的另一个功能，去掉这个参数即可。

**Comment by THUHJ** [comment]
@typhoonzero 你好,谢谢你之前的回答！

我把pserver_spec="10.30.40.109:3000"这个参数去掉之后，现在已经实现了两台机器，一台开pserver, 一台开gradient_servers，可以通信和正常训练。

但在我尝试开两个gradient_servers的时候会error
pserver上的日志信息：
root@54a969f9f427:/model/deep_speech_2# ./run-psserver.sh 
I0718 03:58:30.014904  4314 Util.cpp:166] commandline: /usr/bin/../opt/paddle/bin/paddle_pserver_main --num_gradient_servers 2 --nics eth0 --port 3000 --ports_num 1 --ports_num_for_sparse 1 
I0718 03:58:39.640100  4314 ParameterServerController.cpp:83] number of parameterServer instances: 2
I0718 03:58:39.640147  4314 ParameterServerController.cpp:87] Starting parameterServer[0]
I0718 03:58:39.640884  4314 ParameterServerController.cpp:87] Starting parameterServer[1]
I0718 03:58:39.640925  4314 ParameterServerController.cpp:96] Waiting parameterServer[0]
I0718 03:58:39.640998  4387 LightNetwork.cpp:269] tcp server start 
I0718 03:58:39.641229  4388 LightNetwork.cpp:269] tcp server start 
I0718 03:58:39.800237  4389 LightNetwork.cpp:322] worker started, peer = 10.30.40.110
I0718 03:58:41.847481  4389 ParameterServer2.cpp:256] pserver: setParameter
I0718 03:58:41.847616  4389 ParameterServer2.cpp:302] pserver: new cpuvector: size=4194304
I0718 03:58:41.926148  4390 LightNetwork.cpp:322] worker started, peer = 10.30.40.110
I0718 03:59:22.153103  4555 LightNetwork.cpp:322] worker started, peer = 172.17.0.1
F0718 03:59:24.153277  4555 ParameterServer2.cpp:158] Check failed: **!configMap_.count(config.para_id()) Duplicated parameter name: ___fc_layer_3__.wbias
*** Check failure stack trace: *****
    @           0xac7b2d  google::LogMessage::Fail()
    @           0xac9e78  google::LogMessage::SendToLog()
    @           0xac761b  google::LogMessage::Flush()
    @           0xacad4e  google::LogMessageFatal::~LogMessageFatal()
    @           0x85ddea  paddle::ParameterServer2::setConfig()
    @           0x8616fb  std::_Function_handler<>::_M_invoke()
    @           0x86b0c4  _ZNSt17_Function_handlerIFvSt10unique_ptrIN6paddle9MsgReaderESt14default_deleteIS2_EESt8functionIFvRKSt6vectorI5iovecSaIS8_EEEEEZNS1_11ProtoServer23registerServiceFunctionINS1_16SetConfigRequestEEEvRKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES6_IFvRKT_S6_IFvRKN6google8protobuf11MessageLiteEEEEEEUlS5_SE_E_E9_M_invokeERKSt9_Any_dataOS5_OSE_
    @           0x87665a  paddle::ProtoServer::handleRequest()
    @           0x8742ff  paddle::SocketWorker::run()
    @     0x7f2f1f8a5c80  (unknown)
    @     0x7f2f1ff826ba  start_thread
    @     0x7f2f1f00b3dd  clone
    @              (nil)  (unknown)
/usr/bin/paddle: line 113:  4314 Aborted                 (core dumped) ${DEBUGGER} $MYDIR/../opt/paddle/bin/paddle_pserver_main ${@:2}

之前在一个pserver和一个gradient_server的时候也遇到过这个问题，当时是由于我配置的pserver和gradient_server中有参数不一致导致的（不小心把一个--ports_num_for_sparse设置为1 另一个设置为0了），把参数改一致就跑通了。
但现在参数都一致了，不知道为什么还有这个问题。

具体参数如下：
pserver:
paddle pserver --num_gradient_servers 2 \
 --nics eth0 \
 --port 3000 \
 --ports_num 1 \
 --ports_num_for_sparse 1

两个gradient server:参数相同
 --pserver 10.30.40.109 \
 --port 3000 \
 --num_gradient_servers 2 \
 --ports_num 1 \
 --ports_num_for_sparse 1 \
--if_cluster True \

 trainer = paddle.trainer.SGD(
        cost=cost, parameters=parameters, update_equation=optimizer, is_local=not args.if_cluster)
paddle.init(use_gpu=args.use_gpu, trainer_count=args.trainer_count,
	        pservers=args.pservers,
	        port=args.port, 
	        num_gradient_servers=args.num_gradient_servers, 
	        ports_num=args.ports_num, 
	        ports_num_for_sparse=args.ports_num_for_sparse)

**Comment by THUHJ** [comment]
补充：
pserver在10.30.40.109.这台机器上
gradient server 一个在10.30.40.109上一个在10.30.40.110上，
172.17.0.1 是10.30.40.109的内部ip。

我是用docker跑的，在建的时候绑定了3000 3001端口。

**Comment by Yancey1989** [comment]
看到了 @typhoonzero 正在写的多机训练的文档，很赞！https://github.com/PaddlePaddle/Paddle/pull/2072 ， @THUHJ 欢迎Review相关的文档：）

**Comment by Canpio** [comment]
问题已经解答，因此关闭issue
