### ISSUE TITLE
多机多卡分布式训练出错

### ISSUE THREAD

**Issue by KingCSer** [PaddlePaddle/Paddle#29203]
版本：paddle-1.8.5-gpu-cuda10.0-cudnn7.img
多机多卡分布式集群训练：（自定义集群）
问题：在2个node中训练时，当在一个node中ctrl+C强制退出训练后，另一个node却没有退出训练，而是卡在当前的epoch。怎样使得2个node同时退出训练？

**Comment by hutuxian** [comment]
现在暂时没有这个机制，建议在另一个节点通过kill命令杀死进程。
