### ISSUE TITLE
label是dense_vector时，如何用auc_evaluator

### ISSUE THREAD

**Issue by Damon-wyg** [PaddlePaddle/Paddle#2921]
如题，label是dense_vector格式，维度是1时，对结果使用auc_evaluator做评估，结果auc都是0，评估无效，评估时的网络结构如下（问题背景是，在评估cos_sim应用于ctr场景的效果）：
```python
cost = cos_sim(a=user_media_fc_layer1, b=ad_fc_layer2, scale=1)
rc = regression_cost(input=cost, label=label)
eval = auc_evaluator(rc, label)
outputs(rc)
```
请教如何处理

之前label使用interger，使用auc_evaluator是OK的，是不是上述场景下，label已经是一个vector导致的，有没有办法转换？

**Comment by lcy-seso** [comment]
- 您好，从代码看 https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/gserver/evaluators/Evaluator.cpp#L397， AUC 这个evaluator 输入的类别标签必须是 `intege_value`。
- 您试试构造一个额外的`integer_value`类似的类别标签，和 label 取值完全一样，但是类型不同，只作为这个Evaluator的输入。

**Comment by Damon-wyg** [comment]
在配置网络结构的时候，有办法对dense_vector的label做一个强转换吗？比如我从label向量中取出label[0]（这里只为表意，这样取是不行的）

**Comment by lcy-seso** [comment]
- 可以通过修改改代码实现，但暂时确实不支持。
- integer_value 存储在 `Argument.ids` ，而dense存储在 `Arguments.value`。Paddle中有类似这样的层，可以从两者中任意一个读取类别标签，稍后我们可以提PR进行修改，如果较急，可以先试试临时fix一下。

**Comment by Damon-wyg** [comment]
另外，cos_sim是【-1，1】的取值，而interge_value的值是0、1，这是不是也会影响auc的评估？

**Comment by lcy-seso** [comment]
这种情况，无法使用 Paddle 内置的 AUC Evaluator，目前 AUC evaluator 的计算逻辑是针对二值离散类别标签，建议打印出预测值，在外部评估吧。

**Comment by Damon-wyg** [comment]
好吧，多谢解答
