### ISSUE TITLE
目前的Paddle V2版本是否支持每个pass训练完成后的模型都保存到HDFS的output目录

### ISSUE THREAD

**Issue by youan1** [PaddlePaddle/Paddle#2922]
如题

参考了 issues/1637，他提到如果 saving_period 改成1 就支持每pass保存模型，请问 paddle V2也支持么，用法是否为--saving_period 1, 另外该功能是否在v2中缺省打开的，谢谢

**Comment by Yancey1989** [comment]
在v2中保存保存模型可以在[event_handler](http://doc.paddlepaddle.org/doc/api/v2/run_logic.html#event)中保存,参考代码https://github.com/PaddlePaddle/book/blob/develop/03.image_classification/train.py#L69 ，

> 保存到HDFS的output目录
应该是说的MPI的集群训练把？直接写在当前`output/`目录下，MPI在job结束时会将此目录下的数据保存在提交时的`--output` 参数指定的HDFS目录下，另外建议只有0号trainer来保存模型，否则HDFS上的数据会有冲突。

**Comment by youan1** [comment]
是的，是在MPI集群上，对比了上述代码，在我的event_handle里有模型保存的代码，所以就是 1）Paddle V2是不支持每个pass完成后就保存一遍模型的，一定要等到job结束后才能拿到所有pass的模型，对么 2）如果在中间过程中杀死job，前面已完成的model pass会保存么

**Comment by jacquesqiao** [comment]
v2支持每个pass都保存一遍模型，但是这个保存是保存在0号trainer机器上了

**Comment by Yancey1989** [comment]
>Paddle V2是不支持每个pass完成后就保存一遍模型的，一定要等到job结束后才能拿到所有pass的模型，对么 

v2支持每个pass保存一遍模型，但在MPI上由于存储机制的原因，需要等待Job结束之后才会拿到所有pass的模型

> 2）如果在中间过程中杀死job，前面已完成的model pass会保存么

这个我需要确认一下，稍后给出答复。

**Comment by Yancey1989** [comment]
@youan1 不好意思回复晚了，被kill的job也会将output保存在HDFS上。

**Comment by Canpio** [comment]
问题已经解答。因此关闭issue
