### ISSUE TITLE
mac编译报错

### ISSUE THREAD

**Issue by xcgworker** [PaddlePaddle/Paddle#29231]
1）PaddlePaddle版本：develop分支 7b5a8e46decf5cf35d6f9ff29fb24ff6bc0e79b9

    2）编译器版本：Apple clang version 11.0.3 (clang-1103.0.32.62)

编译报错：
![error](https://user-images.githubusercontent.com/55661104/100610394-9aa47e00-334a-11eb-8457-139e0d43acff.jpg)

我cmake执行的是：
cmake -DWITH_GPU=OFF -DWITH_TESTING=OFF -DWITH_AVX=OFF   -DPY_VERSION=3.7 ..

**Comment by tianshuo78520a** [comment]
我们最近会解决这个问题，添加一个编译Tensort的参数，默认不会去编trt，但目前的develop分支无法解决这个问题。
你可以从以下3个方案中选择合适你的方法解决：
1.机器的TRT需要升级，如果你使用的是官网镜像，可以重新pull更新镜像
2.如果你不需要编译Tensort可以选择删除/usr/include/NvInfer.h文件，清空build目录重新编译
3.可以手动更新Tensort，你需要使用大于6的版本，可以使用以下命令
```
 wget -q https://paddle-ci.cdn.bcebos.com/TRT/TensorRT-7.1.3.4.Ubuntu-16.04.x86_64-gnu.cuda-11.0.cudnn8.0.tar.gz --no-check-certificate
 tar -zxf TensorRT-7.1.3.4.Ubuntu-16.04.x86_64-gnu.cuda-11.0.cudnn8.0.tar.gz -C /usr/local
 cp -rf /usr/local/TensorRT-7.1.3.4/include/* /usr/include/ && cp -rf /usr/local/TensorRT-7.1.3.4/lib/* /usr/lib/
 rm TensorRT-7.1.3.4.Ubuntu-16.04.x86_64-gnu.cuda-11.0.cudnn8.0.tar.gz
```

**Comment by xcgworker** [comment]
我觉得可能是编译器的问题，linux上用g++编译没有问题，但是在mac上使用clang就有问题了。
<img width="527" alt="image" src="https://user-images.githubusercontent.com/55661104/100617127-0390f380-3355-11eb-912e-1804a7dadfd8.png">
可能这种写法需要开启C++比较高级的特性，我试一下看clang加C++-17的特性后会不会有问题。

**Comment by tianshuo78520a** [comment]
![image](https://user-images.githubusercontent.com/29832297/100689199-fc063480-33be-11eb-8d3d-7d7eef774388.png)
我的clang版本是10.0.0，不应该是版本问题，你清空下build目录，重新cmake，make应该可以解决问题。

**Comment by xcgworker** [comment]
v2.0.0-rc0在我mac编译成功了，我先用这个版本好了。

**Comment by jzhang533** [comment]
@xcgworker 在mac上，清空build目录，重新编译能够成功，可能是paddle依赖的pybind到 2.4.3引起的 ：#28284
