### ISSUE TITLE
文档注释不够严谨的问题

### ISSUE THREAD

**Issue by jhcgt4869** [PaddlePaddle/Paddle#29239]
在学习文档，进行书写文字的过程中，发现了文档中部分注释不够严谨。不知道是我过于杠精还是个人感觉技术文章、文档应该严谨猜对，特提isse 
地址：https://www.paddlepaddle.org.cn/documentation/docs/zh/2.0-rc/guides/01_paddle2.0_introduction/basic_concept/tensor_introduction_cn.html
位置：Tensor的操作，修改tensor
原因：里面生成Tensor写明了是float32，但是注释结果却是int经过实际操作结果也是[[1.,1.,1.][1.,1.,1.]]
文档：
![image](https://user-images.githubusercontent.com/61859193/100694120-4db3bc80-33c9-11eb-8917-756a4ff1f464.png)
验证：
![image](https://user-images.githubusercontent.com/61859193/100694146-5efcc900-33c9-11eb-9e86-0f6f0aaa94bf.png)
.numpy:
![image](https://user-images.githubusercontent.com/61859193/100694183-80f64b80-33c9-11eb-81c2-652011b480d9.png)

对此有些不解，虽然文档看的懂，但是就是感觉很奇怪，提一个文档，希望得到一个好的理解方式

**Comment by ZHUI** [comment]
收到反馈问题，我们会进一步完善，提高文档质量。

**Comment by ZHUI** [comment]
@liym27  辛苦文档负责人帮忙完善。

https://github.com/PaddlePaddle/FluidDoc/blame/develop/doc/paddle/guides/01_paddle2.0_introduction/basic_concept/tensor_introduction_cn.md#L379

https://github.com/PaddlePaddle/FluidDoc/blame/develop/doc/paddle/guides/01_paddle2.0_introduction/basic_concept/tensor_introduction_en.md#L388

**Comment by liym27** [comment]
> @liym27 辛苦文档负责人帮忙完善。
> 
> https://github.com/PaddlePaddle/FluidDoc/blame/develop/doc/paddle/guides/01_paddle2.0_introduction/basic_concept/tensor_introduction_cn.md#L379
> 
> https://github.com/PaddlePaddle/FluidDoc/blame/develop/doc/paddle/guides/01_paddle2.0_introduction/basic_concept/tensor_introduction_en.md#L388

@jhcgt4869 好的，非常感谢您的建议。技术文档应当严谨，是之前撰写文档的疏忽，将尽快修正。 
有问题或者建议，欢迎随时 issue 提出。

**Comment by liym27** [comment]
该问题已修复，https://github.com/PaddlePaddle/FluidDoc/pull/2979
在[develop 版本](https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/guides/01_paddle2.0_introduction/basic_concept/tensor_introduction_cn.html#id7)的可看到修改后的文档（官网develop 版本的文档有一定延迟），修改后的文档将随 Paddle 2.0 正式版发布。
