### ISSUE TITLE
2.0rc版本 错误保存模型参数为.pkl格式

### ISSUE THREAD

**Issue by HXia-XXL** [PaddlePaddle/Paddle#29245]
把参数错误保存为.pkl格式，测试时也可以正常导入，但在训练集和测试集的预测结果都完全错误。
请问是因为这个参数文件格式错误的原因嘛？
有没有补救措施能把正确的参数文件copy回来，还是需要重新训练了？？
谢谢。
`#储存参数`
`paddle.save(model.state_dict(),'params.pkl')`
`#加载参数`
`model.set_state_dict(paddle.load('params.pkl'))`

**Comment by ZHUI** [comment]
可以打印出来load进来的 state_dict，看是否符合预期。
一般加载没有问题的话，应该是save的时候，参数就出现了问题。
至于命名格式，能load应该问题不大。

**Comment by HXia-XXL** [comment]
好的。感谢。
