### ISSUE TITLE
使用PALM的联合训练，实际训练轮次和设置的不一致

### ISSUE THREAD

**Issue by yeguang1991** [PaddlePaddle/Paddle#29249]
https://github.com/PaddlePaddle/PALM/blob/master/examples/multi-task/run.py

我设置num_epochs=10，但是intent训练了50多轮
![image](https://user-images.githubusercontent.com/66579493/100710220-5cf73200-33ea-11eb-9720-2809ac4c883e.png)

**Comment by frankwhzhang** [comment]
num_epochs设置的slot部分

**Comment by yeguang1991** [comment]
> num_epochs设置的slot部分

如果设置intent部分的话，slot训练轮次太少了

请问应该怎么设置，才能让slot和intent都训练10轮？
