### ISSUE TITLE
Paddle Python module does not provide version info.

### ISSUE THREAD

**Issue by tanzhongyibidu** [PaddlePaddle/Paddle#2924]
Just like other python module for example,
import bumpy as np
print np.__version__
it will return its version as 1.12.1

so suggest that paddle python module add this version info
import paddle.v2 as paddle
print paddle.__version__
it will return some version information
it is a common practice.

**Comment by Yancey1989** [comment]
Good point! Thanks for @tanzhongyibidu , I think we also need the git commit ID for the module. Such as:
```bash
>>> import paddle
>>> print paddle.version
git_commit_id: c40707b6fd3f6bb8b62dcd14e4d6626313a31094
version: 0.10.0
```

**Comment by jinfagang** [comment]
What is this??

```
<module 'paddle.version' from '/Library/Python/2.7/site-packages/paddle/version.pyc'>
```
```
import paddle

print paddle.version
```

**Comment by Yancey1989** [comment]
Please try the following code:
```bash
>>> import paddle
>>> print paddle.version.full_version
0.11.0
>>> print paddle.version.commit
d43469b74e74b9c1b2a96fd731d2740367955adb
```
