### ISSUE TITLE
咨询是否有内存和显存之间复制数据的API

### ISSUE THREAD

**Issue by skywalk163** [PaddlePaddle/Paddle#29240]
正在修改《动手学深度学习》的8.3节的代码到飞桨2.0版本 。 

8.3 自动并行计算
8.3.2. 计算和通信的并行计算
在同时使用CPU和GPU的计算中，经常需要在内存和显存之间复制数据，造成数据的通信。在下面的例子中，我们在GPU上计算，然后将结果复制回CPU使用的内存。

请问飞桨是否有如MXNet那样的内存/显存之间复制数据的API，如果没有，我就把文档里这一小节空出来就好了。

**Comment by ZHUI** [comment]
使用GPU训练的话，是存在训练数据往GPU上拷贝的。

**Comment by skywalk163** [comment]
飞桨是否不能单独设定运算在cpu或者gpu？ 

我看到有这句，是全局设置的：paddle.set_device("gpu")
还有这句：with paddle.fluid.device_guard("gpu"): 
该API仅支持【静态图】模式。在动态图下测试，全局为gpu，设置为cpu，最终还是从gpu运算的。

**Comment by skywalk163** [comment]
也就是我们没有再放开手动在内存里copy数据这些操作，飞桨系统内部自动实现了。

那么同样道理，运算是不是也是自动实现的？

**Comment by ZHUI** [comment]
目前的计算逻辑，是自动copy。device是gpu时候，有tensor在cpu上，cpu的tensor会自动copy到gpu，再进行计算。

如果要自己copy数据的话，可以尝试使用 paddle.to_tensor，指定place进行操作。

https://www.paddlepaddle.org.cn/documentation/docs/zh/2.0-rc/api/paddle/tensor/creation/to_tensor_cn.html#to-tensor

**Comment by skywalk163** [comment]
谢谢，根据你的提示把8.3节 同步计算写完了，基本复现了花书的例子。

主要思路就是用with paddle.fluid.dygraph.guard(cpuplace): 语句来设定执行的设备，
用paddle.to_tensor 实现内存和显存的数据copy 

公开项目地址：https://aistudio.baidu.com/aistudio/projectdetail/231100

**Comment by ZHUI** [comment]
> 谢谢，根据你的提示把8.3节 同步计算写完了，基本复现了花书的例子。
> 
> 主要思路就是用with paddle.fluid.dygraph.guard(cpuplace): 语句来设定执行的设备，
> 用paddle.to_tensor 实现内存和显存的数据copy
> 
> 公开项目地址：https://aistudio.baidu.com/aistudio/projectdetail/231100

感谢为 paddle 做出的贡献， for batter paddle!
