### ISSUE TITLE
使用LSTM出现无法运行的问题，不报错，AIstudio执行器中断

### ISSUE THREAD

**Issue by liu824** [PaddlePaddle/Paddle#29258]
我的初始模型为：
#定义DNN网络
```
class MyModel(fluid.dygraph.Layer):
    '''
    DNN网络
    '''
    def __init__(self):
        super(MyModel,self).__init__()
        self.fc1=fluid.dygraph.Linear(5*24*7,32,act='relu')
        self.fc2=fluid.dygraph.Linear(32,1)
        
    def forward(self,input):        # forward 定义执行实际运行时网络的执行逻辑
        '''前向计算'''
        # print('input',input.shape)
        input =fluid.layers.reshape(input,shape=[-1,5*24*7])
        out=self.fc1(input)
        out=self.fc2(out)
        # print(out.shape)
        return out
```
可以正常运行，为了尝试LSTM这个API，我将它加在fc1层前面：
```
class MyLSTMModel(fluid.dygraph.Layer):
    def __init__(self):
        super(MyLSTMModel,self).__init__()
        self.rnn = paddle.nn.LSTM(7, 7, 2)
        
        self.fc1=fluid.dygraph.Linear(5*24*7,32,act='relu')
        self.fc2=fluid.dygraph.Linear(32,1)
        
    def forward(self,input):        # forward 定义执行实际运行时网络的执行逻辑
        '''前向计算'''
        input,(h,c)=rnn(input)

        input =fluid.layers.reshape(input,shape=[-1,5*24*7])
        out=self.fc1(input)
        out=self.fc2(out)
        # print(out.shape)
        return out
```
输入输出都对齐了，但是一加上就无法运行，直接执行器中断。逐层排除之后，发现导致程序无法运行的地方在loss.backward()即反向传播过程中，将它注释之后程序可以运行。

**Comment by ZHUI** [comment]
请问一下，使用的paddle版本是？
可以使用develop版本或者最新的2.0rc版本尝试。
这边再develop版本下，未能复现问题。

develop 版本地址 https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/install/Tables.html#whl-dev

**Comment by liu824** [comment]
我使用的是2.0rc版本

**Comment by liu824** [comment]
这是我的项目https://aistudio.baidu.com/aistudio/projectdetail/1291489?shared=1

**Comment by liu824** [comment]
https://aistudio.baidu.com/aistudio/projectdetail/1291489?shared=1

**Comment by ZHUI** [comment]
![image](https://user-images.githubusercontent.com/16911935/100736890-5bd7fc00-340e-11eb-926f-0901a43203e9.png)

aistudio 运行截图
> 这是我的项目https://aistudio.baidu.com/aistudio/projectdetail/1291489?shared=1

**Comment by liu824** [comment]
![image](https://user-images.githubusercontent.com/55372277/100738030-f71da100-340f-11eb-82c2-0114f459ec8e.png)
我每次运行都重启，按照您上面的方法

**Comment by liu824** [comment]
代码是一样的
![image](https://user-images.githubusercontent.com/55372277/100738800-1bc64880-3411-11eb-850f-bda3399a9572.png)

**Comment by liu824** [comment]
我发现原因了，使用我使用高级版本的时候无法运行，使用cpu版本可以

**Comment by ZHUI** [comment]
此处为2.0rc LSTM API GPU 版本的BUG。我跑的是CPU的，所以未能复现。
最新develop版本已修复。

两种解决方案：

1. 需要设置 `input.stop_gradient=False` 
2. 安装最新的develop版本Paddle. https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/install/Tables.html#whl-dev

**Comment by liu824** [comment]
好的
