### ISSUE TITLE
2.0rc版本 测试时BatchSize需要和训练时的一致嘛？

### ISSUE THREAD

**Issue by HXia-XXL** [PaddlePaddle/Paddle#29250]
训练阶段BatchSize=16，测试时候设置model.eval()一张一张进行预测，结果完全错误。
设置成model.train()一张一张进行预测，结果大致正确，但精度较低。

我的理解是，设置eval()模式就固定了模型的BN层参数，是我训练阶段的BatchSize设置的太大了嘛
而且看到官方示例里面，测试集的BatchSize=32
`# 加载测试数据集
test_loader = paddle.io.DataLoader(test_dataset, places=paddle.CPUPlace(), batch_size=32, drop_last=True)

mnist.eval()`
就对这方面有一些困惑。
谢谢！

**Comment by HXia-XXL** [comment]
不好意思。AI studio上训练的模型做了改动。本地模型没有做相应更改。现在正常了。耽误大家时间了抱歉。
不过注意力模块顺序变动了参数也能正常导入。Interesting。

**Comment by ZHUI** [comment]
` 测试时BatchSize需要和训练时的一致` 理论上是不需要的。
建议可以在部分BN层参数前，查看打印train()和eval()时候的diff情况。

**Comment by HXia-XXL** [comment]
感谢。已经找到问题了。是本地模型忘记调整注意力模块顺序了。那这样load参数时候会不会忽略这个不匹配的层？

**Comment by ZHUI** [comment]
> 感谢。已经找到问题了。是本地模型忘记调整注意力模块顺序了。那这样load参数时候会不会忽略这个不匹配的层？

不清楚你的具体问题。state_dict中参数name是一致的话，就可以成功加载参数。可以打印下state_dict中参数的keys看看。如果名字不匹配，会跳过。
