### ISSUE TITLE
不想提issue的issue

### ISSUE THREAD

**Issue by jhcgt4869** [PaddlePaddle/Paddle#29251]
地址：https://www.paddlepaddle.org.cn/documentation/docs/zh/2.0-rc/guides/01_paddle2.0_introduction/basic_concept/tensor_introduction_cn.html#id4

问题：逻辑运算符操作处，同一个操作使用的函数名不正确
![image](https://user-images.githubusercontent.com/61859193/100711643-8b760c80-33ec-11eb-9475-6b0d1583813d.png)
![image](https://user-images.githubusercontent.com/61859193/100711684-992b9200-33ec-11eb-818e-78352e0c0c57.png)

使用官方代码报错：
![image](https://user-images.githubusercontent.com/61859193/100711739-afd1e900-33ec-11eb-8a21-81b0b50d6238.png)
![image](https://user-images.githubusercontent.com/61859193/100711759-b5c7ca00-33ec-11eb-9eee-a96558b87281.png)

解决方案：添加了原文档中的paddle.disable_static()
个人认为：应该添加提示，否则有好大一部分的代码会报错

地址：https://www.paddlepaddle.org.cn/documentation/docs/zh/2.0-rc/api/paddle/tensor/logic/equal_cn.html

问题：复制官方api代码出现报错
![image](https://user-images.githubusercontent.com/61859193/100712065-1f47d880-33ed-11eb-9ca7-ec44abb54d33.png)
查找后发现根本没有这个类库
通过官方源码发现解决方案，个人认为是文档未修改或者缺少类库
![image](https://user-images.githubusercontent.com/61859193/100712159-47cfd280-33ed-11eb-8c00-506cd9f0688b.png)

希望对api和文档进行修复，我们对平paddle的期待很高，希望他越来越好！！！

**Comment by ZHUI** [comment]
@jhcgt4869 

1. `问题：逻辑运算符操作处，同一个操作使用的函数名不正确`
已知bug，develop已经修复。
可以尝试 https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/install/Tables.html#whl-dev 
2. `问题：复制官方api代码出现报错`
文档错误，develop已经修复。https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/tensor/logic.py#L184

**Comment by jhcgt4869** [comment]
第一个我指的是equal写成了euqal
第二直接导入paddle对逻辑运算符操作会报错，是不是应该加个操作连接或者地址？？？或者报错解决方案？？？

**Comment by jhcgt4869** [comment]
![image](https://user-images.githubusercontent.com/61859193/100715522-46ed6f80-33f2-11eb-95d4-8a1657d82051.png)
这个地方的代码报错，并没有得到解决啊

**Comment by ZHUI** [comment]
> 第一个我指的是equal写成了euqal

好的，谢谢，确实是文档问题。 @zhouwei25 辛苦相关同学完善。
https://github.com/PaddlePaddle/FluidDoc/blob/develop/doc/paddle/guides/01_paddle2.0_introduction/basic_concept/tensor_introduction_en.md
https://github.com/PaddlePaddle/FluidDoc/blob/develop/doc/paddle/guides/01_paddle2.0_introduction/basic_concept/tensor_introduction_cn.md

> 第二直接导入paddle对逻辑运算符操作会报错，是不是应该加个操作连接或者地址？？？或者报错解决方案？？？

"加个操作连接或者地址？？？或者报错解决方案？？？" 具体指?

`添加了原文档中的paddle.disable_static()` 2.0rc开始默认动态图，不再需要用`paddle.disable_static()`， 相关文档代码也会被删除，

slice op的bug已经修复了, 还有floor_divide问题，也可以提供样例，我这边再验证下。

**Comment by ZHUI** [comment]
> ![image](https://user-images.githubusercontent.com/61859193/100715522-46ed6f80-33f2-11eb-95d4-8a1657d82051.png)
> 这个地方的代码报错，并没有得到解决啊

github repo上的文档已经修复。官网还没有update到最新版本
https://github.com/PaddlePaddle/FluidDoc/blob/develop/doc/paddle/api/paddle/tensor/logic/equal_cn.rst
https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/tensor/logic.py#L184

**Comment by jhcgt4869** [comment]
前面的已经收到，现在使用
![image](https://user-images.githubusercontent.com/61859193/100718075-e102e700-33f5-11eb-94de-b160f6ab9919.png)
![Uploading image.png…]()
全部都报错要怎么样解决

**Comment by jhcgt4869** [comment]
前面的已经收到，现在使用整除和全部的逻辑运算符都会报错要怎么样处理？
![](https://user-images.githubusercontent.com/61859193/100718075-e102e700-33f5-11eb-94de-b160f6ab9919.png)
![image](https://user-images.githubusercontent.com/61859193/100718458-54a4f400-33f6-11eb-8d99-47b763cab0da.png)

**Comment by ZHUI** [comment]
> 前面的已经收到，现在使用整除和全部的逻辑运算符都会报错要怎么样处理？

> 整除

floor_divide 目前支持 int32 和 int64的数据类型。符合预期。
![image](https://user-images.githubusercontent.com/16911935/100719279-62a74480-33f7-11eb-88ef-b407cbba058a.png)
https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/tensor/math/floor_divide_cn.html#floor-divide

> 全部的逻辑运算符 报错

已知bug，develop已经修复。
可以尝试 https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/install/Tables.html#whl-dev

**Comment by jhcgt4869** [comment]
也就是aistudio目前还不支持是吧。
那个刚刚发现那个画框的api在API库里面没有，这……
![image](https://user-images.githubusercontent.com/61859193/100720132-86b75580-33f8-11eb-86a5-f20c688a2577.png)

**Comment by ZHUI** [comment]
> 也就是aistudio目前还不支持是吧。
> 那个刚刚发现那个画框的api在API库里面没有，这……

对，得自己去安装develop版本。
reduce类的 op 收到反馈，已确认有问题，感谢。

**Comment by jhcgt4869** [comment]
好的，paddle生态需要大家一起维护

**Comment by ZHUI** [comment]
> 好的，paddle生态需要大家一起维护

感谢反馈，for batter paddle！
