### ISSUE TITLE
训练的时候加载的外部预训练的embedding也作为参数参加训练

### ISSUE THREAD

**Issue by WoNiuHu** [PaddlePaddle/Paddle#2927]
hi，RT。CNN-non-static: Same as above but the pretrained vectors are fine-tuned for each task.
加载embedding层的语句，

```python
emb = embedding_layer(input=data, size=emb_dim, param_attr=ParamAttr(name='_source_language_embedding'))`

emb_para = ParameterAttribute(name='emb', initial_std=0., learning_rate=0.)
fc1 = fc_layer(input=emb, size=hid_dim, act=linear, bias_attr=bias_attr, param_attr=emb_para)
```

是这样处理？不确定是不是加对了？

**Comment by lcy-seso** [comment]
1. 请把  `parameters.set`调用放在 `paddle.parameters.create`调用之后。
2. 下面的代码把学习率设置为0，`embedding`这个参数将不再更新，请确定这是您需要。
    ```python
    emb_para = ParameterAttribute(name='emb', initial_std=0., learning_rate=0.)
    ```

**Comment by WoNiuHu** [comment]
@lcy-seso 那个第一条

> parameters.set 
> paddle.parameters.create
分别指的是哪一个？
没搞清楚是怎么用的？这里能详细点么？

**Comment by WoNiuHu** [comment]
@lcy-seso 是这个意思？
`emb_para = ParameterAttribute(name='emb', initial_std=0., `learning_rate=hid_lr)`
    `emb= embedding_layer(input=data, size=emb_dim, param_attr=ParamAttr(name='_source_language_embedding'))`
    `fc1 = fc_layer(input=emb, size=hid_dim, act=linear, bias_attr=bias_attr, param_attr=emb_para)`

**Comment by lcy-seso** [comment]
- please take this as an example. https://github.com/PaddlePaddle/book/blob/develop/07.label_semantic_roles/train.py#L142

**Comment by WoNiuHu** [comment]
@lcy-seso 这两行对应的0.9的版本是？`# create parameters
    parameters = paddle.parameters.create(crf_cost)

    parameters.set('emb', load_parameter(conll05.get_embedding(), 44068, 32))`

**Comment by lcy-seso** [comment]
- please first put all the pretrained parameters into a local directory. Then set `init_model_path` to this directory and set `load_missing_parameter_strategy` to `rand` at the same time.
- There is the document:
http://doc.paddlepaddle.org/release_doc/0.9.0/doc/ui/cmd_argument/detail_introduction.html#train

**Comment by WoNiuHu** [comment]
@lcy-seso Hi，第一条在train的参数里面已经设置好了。
<pre><code> --init_model_path='./opinion_data/pre-car' \
                 --load_missing_parameter_strategy=rand \
</code></pre>

**Comment by lcy-seso** [comment]
just have a try.

**Comment by WoNiuHu** [comment]
@lcy-seso 跑起来是没有问题，但是我不确定这样做是否是和我预期的做法一样？
<pre><code>
_source_language_embedding avg_abs_val=0.169549    max_val=5.95178     avg_abs_grad=3.59753e-06 max_grad=1.03223
</code></pre>
我只要看到 embedding的avg_abs_val每次在更新，是不是理论上就满足需求了？

**Comment by WoNiuHu** [comment]
@lcy-seso hi，有些参数的地方不懂，再请教下你哈，
<pre><code>
emb = embedding_layer(input=data, size=emb_dim, param_attr=ParamAttr(name='_source_language_embedding'))
</code></pre>
是不是这边直接这样设置，_source_language_embedding 是预训练的词向量文件，然后在train里面设置
<pre><code>
--init_model_path='./opinion_data/pre-car' \
                 --load_missing_parameter_strategy=rand \
</pre></code>
这个emb已经是 "pretrained
vectors are fine-tuned for each task" ? 每次的 _source_language_embedding 的avg_abs_val每次在更新就表示emb作为参数在训练中更新吗？
然后这个
<pre><code>
    emb_para = ParameterAttribute(name='emb', initial_std=0., learning_rate=hid_lr)
    emb = embedding_layer(input=data, size=emb_dim, param_attr=ParamAttr(name='_source_language_embedding'))
    fc1 = fc_layer(input=emb, size=hid_dim, act=linear, bias_attr=bias_attr, param_attr=emb_para)
</pre><code>
的emb_para其实是fc1里面的权重向量？ param_attr 是权重向量的参数吗？

**Comment by lcy-seso** [comment]
1. 设置 `init_model_path` 和 `load_missing_parameter_strategy` 就可以。
2. `param_attr=ParamAttr(name='_source_language_embedding')` 设置的是词向量层参数，也就是词表。不是全连接的权重。

**Comment by Canpio** [comment]
问题已经解答，因此关闭issue
