### ISSUE TITLE
图像处理-老照片修复或者超分时均报此错误，请问下怎么解决

### ISSUE THREAD

**Issue by UFREE-CODE** [PaddlePaddle/Paddle#29287]
错误信息：  framework._dygraph_tracer().eval_mode()
AttributeError: 'NoneType' object has no attribute 'eval_mode'

paddle/paddlehub 均是最新版，
photo_restoration
类别图像 - 图像编辑
网络-
数据集-
模型概述
photo_restoration 是针对老照片修复的模型。它主要由两个部分组成：着色和超分。着色模型基于deoldify，超分模型基于realsr. 用户可以根据自己的需求选择对图像进行着色或超分操作。因此在使用该模型时，请预先安装deoldify和realsr两个模型。

**Comment by haoyuying** [comment]
请使用paddle2.0，paddlehub1.8.3使用该模型，目前paddlehub2.0与其他1.8模型适配还存在适配问题，将会尽快解决。

**Comment by UFREE-CODE** [comment]
paddle2.0.0a0&nbsp; 是这个版本吗？谢谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "haoyuying"<notifications@github.com&gt;; 
发送时间: 2020年12月2日(星期三) 下午3:22
收件人: "PaddlePaddle/Paddle"<Paddle@noreply.github.com&gt;; 
抄送: "mlh"<673313181@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [PaddlePaddle/Paddle] 图像处理-老照片修复或者超分时均报此错误，请问下怎么解决 (#29287)





 
请使用paddle2.0，paddlehub1.8.3使用该模型，目前paddlehub2.0与其他1.8模型适配还存在适配问题，将会尽快解决。
 
&mdash;

**Comment by haoyuying** [comment]
不是，现在这个模型能跑通的环境是paddle2.0rc和paddlehub1.8.3，如果你不着急用，我今明两天会重新上线模型适配新版hub，上线之后我会第一时间通知您，敬请期待。

**Comment by UFREE-CODE** [comment]
嗯，不着急，主要是看看照片怎么修复，模型好大，几个模型就几个g



---原始邮件---
发件人: "haoyuying"<notifications@github.com&gt;
发送时间: 2020年12月2日(周三) 下午3:54
收件人: "PaddlePaddle/Paddle"<Paddle@noreply.github.com&gt;;
抄送: "Author"<author@noreply.github.com&gt;;"百无一用是书生"<673313181@qq.com&gt;;
主题: Re: [PaddlePaddle/Paddle] 图像处理-老照片修复或者超分时均报此错误，请问下怎么解决 (#29287)




 
不是，现在这个模型能跑通的环境是paddle2.0rc和paddlehub1.8.3，如果你不着急用，我今明两天会重新上线模型适配新版hub，上线之后我会第一时间通知您，敬请期待。

**Comment by UFREE-CODE** [comment]
ResourceExhaustedError: Fail to alloc memory of 4976644096 size.
&nbsp; [Hint: p should not be null.] (at D:\2.0.0-rc0\paddle\paddle\fluid\memory\deta
il\system_allocator.cc:69)
&nbsp; [operator < conv2d &gt; error]



paddle2.0rc和paddlehub1.8.3 安装了这个版本还是不能跑老照片修复






------------------&nbsp;原始邮件&nbsp;------------------
发件人: "haoyuying"<notifications@github.com&gt;; 
发送时间: 2020年12月2日(星期三) 下午3:54
收件人: "PaddlePaddle/Paddle"<Paddle@noreply.github.com&gt;; 
抄送: "mlh"<673313181@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [PaddlePaddle/Paddle] 图像处理-老照片修复或者超分时均报此错误，请问下怎么解决 (#29287)





 
不是，现在这个模型能跑通的环境是paddle2.0rc和paddlehub1.8.3，如果你不着急用，我今明两天会重新上线模型适配新版hub，上线之后我会第一时间通知您，敬请期待。
 
&mdash;

**Comment by UFREE-CODE** [comment]
ResourceExhaustedError: Fail to alloc memory of 4976644096 size.
&nbsp; [Hint: p should not be null.] (at D:\2.0.0-rc0\paddle\paddle\fluid\memory\deta
il\system_allocator.cc:69)
&nbsp; [operator < conv2d &gt; error]



paddle2.0rc和paddlehub1.8.3 安装了这个版本还是不能跑老照片修复，我电脑是16G内存






------------------ 原始邮件 ------------------
发件人: "haoyuying"<notifications@github.com&gt;; 
发送时间: 2020年12月2日(星期三) 下午3:54
收件人: "PaddlePaddle/Paddle"<Paddle@noreply.github.com&gt;; 
抄送: "mlh"<673313181@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [PaddlePaddle/Paddle] 图像处理-老照片修复或者超分时均报此错误，请问下怎么解决 (#29287)





 
不是，现在这个模型能跑通的环境是paddle2.0rc和paddlehub1.8.3，如果你不着急用，我今明两天会重新上线模型适配新版hub，上线之后我会第一时间通知您，敬请期待。

**Comment by haoyuying** [comment]
这个应该是内存不够的错误，paddle2.0rc和paddlehub1.8.3是可以跑的，一些用户已经用起来了，跑照片修复最好用小一点的照片，超分是4倍超分，占用内存很大。

**Comment by UFREE-CODE** [comment]
修复后照片是变大了，但是不清楚，还不如原图清晰



---原始邮件---
发件人: "haoyuying"<notifications@github.com&gt;
发送时间: 2020年12月2日(周三) 下午5:38
收件人: "PaddlePaddle/Paddle"<Paddle@noreply.github.com&gt;;
抄送: "Author"<author@noreply.github.com&gt;;"百无一用是书生"<673313181@qq.com&gt;;
主题: Re: [PaddlePaddle/Paddle] 图像处理-老照片修复或者超分时均报此错误，请问下怎么解决 (#29287)




 
这个应该是内存不够的错误，paddle2.0rc和paddlehub1.8.3是可以跑的，一些用户已经用起来了，跑照片修复最好用小一点的照片，超分是4倍超分，占用内存很大。

**Comment by haoyuying** [comment]
换下其他的照片试下，realsr这个效果还是可以的，我上了适配2.0paddlehub+2.0rc paddle的老照片修复模型，你可以下载1.0.1版本的试下.

**Comment by UFREE-CODE** [comment]
好的，非常感谢，一般1M的照片，要多大内存运行？



---原始邮件---
发件人: "haoyuying"<notifications@github.com&gt;
发送时间: 2020年12月2日(周三) 晚上7:15
收件人: "PaddlePaddle/Paddle"<Paddle@noreply.github.com&gt;;
抄送: "Author"<author@noreply.github.com&gt;;"百无一用是书生"<673313181@qq.com&gt;;
主题: Re: [PaddlePaddle/Paddle] 图像处理-老照片修复或者超分时均报此错误，请问下怎么解决 (#29287)




 
换下其他的照片试下，realsr这个效果还是可以的，我上了适配2.0paddlehub+2.0rc paddle的老照片修复模型，你可以下载1.0.1版本的试下.

**Comment by haoyuying** [comment]
最好图像不要超过800*800，具体没测过，但是照片修复这个模型内存占的最大的是realsr部分。
