### ISSUE TITLE
动态图模式不支持一维卷积

### ISSUE THREAD

**Issue by furtherlearningYan** [PaddlePaddle/Paddle#29286]
paddle 2.0 动态图模式不支持RowConv和SequenceConv
我将别人的torch模型改写成paddle的，网络结构中间有一维卷积，
torch中有nn.Conv1D函数，而paddle有RowConv和SequenceConv，但是动态模式下都不支持这两种。
请问一下，paddle中有没有动态图支持的一维卷积方式。

**Comment by joey12300** [comment]
> paddle 2.0 动态图模式不支持RowConv和SequenceConv
> 我将别人的torch模型改写成paddle的，网络结构中间有一维卷积，
> torch中有nn.Conv1D函数，而paddle有RowConv和SequenceConv，但是动态模式下都不支持这两种。
> 请问一下，paddle中有没有动态图支持的一维卷积方式。

Paddle 2.0-rc1 试试paddle.nn.Conv1D

**Comment by lfchener** [comment]
> paddle 2.0 动态图模式不支持RowConv和SequenceConv
> 我将别人的torch模型改写成paddle的，网络结构中间有一维卷积，
> torch中有nn.Conv1D函数，而paddle有RowConv和SequenceConv，但是动态模式下都不支持这两种。
> 请问一下，paddle中有没有动态图支持的一维卷积方式。

Conv1D API  可参照：https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/nn/layer/conv.py#L153

**Comment by furtherlearningYan** [comment]
好的，非常谢谢！希望paddle越做越好




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Li Fuchen"<notifications@github.com&gt;; 
发送时间: 2020年12月2日(星期三) 下午2:50
收件人: "PaddlePaddle/Paddle"<Paddle@noreply.github.com&gt;; 
抄送: "so"<2917086992@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [PaddlePaddle/Paddle] 动态图模式不支持一维卷积 (#29286)





  
paddle 2.0 动态图模式不支持RowConv和SequenceConv
 我将别人的torch模型改写成paddle的，网络结构中间有一维卷积，
 torch中有nn.Conv1D函数，而paddle有RowConv和SequenceConv，但是动态模式下都不支持这两种。
 请问一下，paddle中有没有动态图支持的一维卷积方式。
  
Conv1D API  可参照：https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/nn/layer/conv.py#L153

**Comment by furtherlearningYan** [comment]
好的，可以了，非常感谢



---原始邮件---
发件人: "Jack Zhou"<notifications@github.com&gt;
发送时间: 2020年12月2日(周三) 中午12:41
收件人: "PaddlePaddle/Paddle"<Paddle@noreply.github.com&gt;;
抄送: "Author"<author@noreply.github.com&gt;;"furtherlearningYan"<2917086992@qq.com&gt;;
主题: Re: [PaddlePaddle/Paddle] 动态图模式不支持一维卷积 (#29286)




  
paddle 2.0 动态图模式不支持RowConv和SequenceConv
 我将别人的torch模型改写成paddle的，网络结构中间有一维卷积，
 torch中有nn.Conv1D函数，而paddle有RowConv和SequenceConv，但是动态模式下都不支持这两种。
 请问一下，paddle中有没有动态图支持的一维卷积方式。
  
Paddle 2.0-rc1 试试paddle.nn.Conv1D
