### ISSUE TITLE
使用paddle静态图训练模型，模型文件里有_model__文件，不清楚_model__干嘛的？

### ISSUE THREAD

**Issue by zhudibo-unwulian** [PaddlePaddle/Paddle#29296]
大佬，我使用paddle静态图训练模型后，模型文件保存的参数如下：
/home/un/work/mobilenetv2/ssr_model/gender-model/conv3x3_1_bn_mean
/home/un/work/mobilenetv2/ssr_model/gender-model/conv3x3_1_bn_offset
/home/un/work/mobilenetv2/ssr_model/gender-model/conv3x3_1_bn_scale
/home/un/work/mobilenetv2/ssr_model/gender-model/conv3x3_1_bn_variance
/home/un/work/mobilenetv2/ssr_model/gender-model/conv3x3_1_weights
/home/un/work/mobilenetv2/ssr_model/gender-model/conv3x3_2_bn_mean
/home/un/work/mobilenetv2/ssr_model/gender-model/conv3x3_2_bn_offset
/home/un/work/mobilenetv2/ssr_model/gender-model/conv3x3_2_bn_scale
/home/un/work/mobilenetv2/ssr_model/gender-model/conv3x3_2_bn_variance
/home/un/work/mobilenetv2/ssr_model/gender-model/conv3x3_2_weights
/home/un/work/mobilenetv2/ssr_model/gender-model/conv3x3_3_bn_mean
/home/un/work/mobilenetv2/ssr_model/gender-model/conv3x3_3_bn_offset
/home/un/work/mobilenetv2/ssr_model/gender-model/conv3x3_3_bn_scale
/home/un/work/mobilenetv2/ssr_model/gender-model/conv3x3_3_bn_variance
/home/un/work/mobilenetv2/ssr_model/gender-model/conv3x3_3_weights
/home/un/work/mobilenetv2/ssr_model/gender-model/conv3x3_4_bn_mean
/home/un/work/mobilenetv2/ssr_model/gender-model/conv3x3_4_bn_offset
/home/un/work/mobilenetv2/ssr_model/gender-model/conv3x3_4_bn_scale
/home/un/work/mobilenetv2/ssr_model/gender-model/conv3x3_4_bn_variance
/home/un/work/mobilenetv2/ssr_model/gender-model/conv3x3_4_weights
/home/un/work/mobilenetv2/ssr_model/gender-model/conv3x3_5_weights
/home/un/work/mobilenetv2/ssr_model/gender-model/conv3x3_s1_bn_mean
/home/un/work/mobilenetv2/ssr_model/gender-model/conv3x3_s1_bn_offset
/home/un/work/mobilenetv2/ssr_model/gender-model/conv3x3_s1_bn_scale
/home/un/work/mobilenetv2/ssr_model/gender-model/conv3x3_s1_bn_variance
/home/un/work/mobilenetv2/ssr_model/gender-model/conv3x3_s1_weights
/home/un/work/mobilenetv2/ssr_model/gender-model/conv3x3_s2_bn_mean
/home/un/work/mobilenetv2/ssr_model/gender-model/conv3x3_s2_bn_offset
/home/un/work/mobilenetv2/ssr_model/gender-model/conv3x3_s2_bn_scale
/home/un/work/mobilenetv2/ssr_model/gender-model/conv3x3_s2_bn_variance
/home/un/work/mobilenetv2/ssr_model/gender-model/conv3x3_s2_weights
/home/un/work/mobilenetv2/ssr_model/gender-model/conv3x3_s3_bn_mean
/home/un/work/mobilenetv2/ssr_model/gender-model/conv3x3_s3_bn_offset
/home/un/work/mobilenetv2/ssr_model/gender-model/conv3x3_s3_bn_scale
/home/un/work/mobilenetv2/ssr_model/gender-model/conv3x3_s3_bn_variance
/home/un/work/mobilenetv2/ssr_model/gender-model/conv3x3_s3_weights
/home/un/work/mobilenetv2/ssr_model/gender-model/conv3x3_s4_bn_mean
/home/un/work/mobilenetv2/ssr_model/gender-model/conv3x3_s4_bn_offset
/home/un/work/mobilenetv2/ssr_model/gender-model/conv3x3_s4_bn_scale
/home/un/work/mobilenetv2/ssr_model/gender-model/conv3x3_s4_bn_variance
/home/un/work/mobilenetv2/ssr_model/gender-model/conv3x3_s4_weights
/home/un/work/mobilenetv2/ssr_model/gender-model/conv3x3_s5_weights
/home/un/work/mobilenetv2/ssr_model/gender-model/conv_pool_s_layer1_weights
/home/un/work/mobilenetv2/ssr_model/gender-model/conv_pool_s_layer2_weights
/home/un/work/mobilenetv2/ssr_model/gender-model/conv_pool_x_layer1_weights
/home/un/work/mobilenetv2/ssr_model/gender-model/conv_pool_x_layer2_weights
/home/un/work/mobilenetv2/ssr_model/gender-model/delta_s1_fc.b_0
/home/un/work/mobilenetv2/ssr_model/gender-model/delta_s1_fc.w_0
/home/un/work/mobilenetv2/ssr_model/gender-model/delta_s2_fc.b_0
/home/un/work/mobilenetv2/ssr_model/gender-model/delta_s2_fc.w_0
/home/un/work/mobilenetv2/ssr_model/gender-model/delta_s3_fc.b_0
/home/un/work/mobilenetv2/ssr_model/gender-model/delta_s3_fc.w_0
/home/un/work/mobilenetv2/ssr_model/gender-model/feat_a_s1_fc.b_0
/home/un/work/mobilenetv2/ssr_model/gender-model/feat_a_s1_fc.w_0
/home/un/work/mobilenetv2/ssr_model/gender-model/feat_a_s2_fc.b_0
/home/un/work/mobilenetv2/ssr_model/gender-model/feat_a_s2_fc.w_0
/home/un/work/mobilenetv2/ssr_model/gender-model/feat_a_s3_fc.b_0
/home/un/work/mobilenetv2/ssr_model/gender-model/feat_a_s3_fc.w_0
/home/un/work/mobilenetv2/ssr_model/gender-model/local_s1_fc.b_0
/home/un/work/mobilenetv2/ssr_model/gender-model/local_s1_fc.w_0
/home/un/work/mobilenetv2/ssr_model/gender-model/local_s2_fc.b_0
/home/un/work/mobilenetv2/ssr_model/gender-model/local_s2_fc.w_0
/home/un/work/mobilenetv2/ssr_model/gender-model/local_s3_fc.b_0
/home/un/work/mobilenetv2/ssr_model/gender-model/local_s3_fc.w_0
/home/un/work/mobilenetv2/ssr_model/gender-model/__model__
/home/un/work/mobilenetv2/ssr_model/gender-model/output_fc.b_0
/home/un/work/mobilenetv2/ssr_model/gender-model/output_fc.w_0
/home/un/work/mobilenetv2/ssr_model/gender-model/pred_a_s1_fc.b_0
/home/un/work/mobilenetv2/ssr_model/gender-model/pred_a_s1_fc.w_0
/home/un/work/mobilenetv2/ssr_model/gender-model/pred_a_s2_fc.b_0
/home/un/work/mobilenetv2/ssr_model/gender-model/pred_a_s2_fc.w_0
/home/un/work/mobilenetv2/ssr_model/gender-model/pred_a_s3_fc.b_0
/home/un/work/mobilenetv2/ssr_model/gender-model/pred_a_s3_fc.w_0
/home/un/work/mobilenetv2/ssr_model/gender-model/s_layer1_mix.b_0
/home/un/work/mobilenetv2/ssr_model/gender-model/s_layer1_mix.w_0
/home/un/work/mobilenetv2/ssr_model/gender-model/s_layer2_mix.b_0
/home/un/work/mobilenetv2/ssr_model/gender-model/s_layer2_mix.w_0
/home/un/work/mobilenetv2/ssr_model/gender-model/s_layer4_mix.b_0
/home/un/work/mobilenetv2/ssr_model/gender-model/s_layer4_mix.w_0
/home/un/work/mobilenetv2/ssr_model/gender-model/x_layer1_mix.b_0
/home/un/work/mobilenetv2/ssr_model/gender-model/x_layer1_mix.w_0
/home/un/work/mobilenetv2/ssr_model/gender-model/x_layer2_mix.b_0
/home/un/work/mobilenetv2/ssr_model/gender-model/x_layer2_mix.w_0
/home/un/work/mobilenetv2/ssr_model/gender-model/x_layer4_mix.b_0
/home/un/work/mobilenetv2/ssr_model/gender-model/x_layer4_mix.w_0
其中存在一个__model__文件，不清楚这个文件时干嘛的，在前向推理的时候，是否需要这个文件？请大佬指点。

**Comment by joey12300** [comment]
> 大佬，我使用paddle静态图训练模型后，模型文件保存的参数如下：
> /home/un/work/mobilenetv2/ssr_model/gender-model/conv3x3_1_bn_mean
> /home/un/work/mobilenetv2/ssr_model/gender-model/conv3x3_1_bn_offset
> /home/un/work/mobilenetv2/ssr_model/gender-model/conv3x3_1_bn_scale
> /home/un/work/mobilenetv2/ssr_model/gender-model/conv3x3_1_bn_variance
> /home/un/work/mobilenetv2/ssr_model/gender-model/conv3x3_1_weights
> /home/un/work/mobilenetv2/ssr_model/gender-model/conv3x3_2_bn_mean
> /home/un/work/mobilenetv2/ssr_model/gender-model/conv3x3_2_bn_offset
> /home/un/work/mobilenetv2/ssr_model/gender-model/conv3x3_2_bn_scale
> /home/un/work/mobilenetv2/ssr_model/gender-model/conv3x3_2_bn_variance
> /home/un/work/mobilenetv2/ssr_model/gender-model/conv3x3_2_weights
> /home/un/work/mobilenetv2/ssr_model/gender-model/conv3x3_3_bn_mean
> /home/un/work/mobilenetv2/ssr_model/gender-model/conv3x3_3_bn_offset
> /home/un/work/mobilenetv2/ssr_model/gender-model/conv3x3_3_bn_scale
> /home/un/work/mobilenetv2/ssr_model/gender-model/conv3x3_3_bn_variance
> /home/un/work/mobilenetv2/ssr_model/gender-model/conv3x3_3_weights
> /home/un/work/mobilenetv2/ssr_model/gender-model/conv3x3_4_bn_mean
> /home/un/work/mobilenetv2/ssr_model/gender-model/conv3x3_4_bn_offset
> /home/un/work/mobilenetv2/ssr_model/gender-model/conv3x3_4_bn_scale
> /home/un/work/mobilenetv2/ssr_model/gender-model/conv3x3_4_bn_variance
> /home/un/work/mobilenetv2/ssr_model/gender-model/conv3x3_4_weights
> /home/un/work/mobilenetv2/ssr_model/gender-model/conv3x3_5_weights
> /home/un/work/mobilenetv2/ssr_model/gender-model/conv3x3_s1_bn_mean
> /home/un/work/mobilenetv2/ssr_model/gender-model/conv3x3_s1_bn_offset
> /home/un/work/mobilenetv2/ssr_model/gender-model/conv3x3_s1_bn_scale
> /home/un/work/mobilenetv2/ssr_model/gender-model/conv3x3_s1_bn_variance
> /home/un/work/mobilenetv2/ssr_model/gender-model/conv3x3_s1_weights
> /home/un/work/mobilenetv2/ssr_model/gender-model/conv3x3_s2_bn_mean
> /home/un/work/mobilenetv2/ssr_model/gender-model/conv3x3_s2_bn_offset
> /home/un/work/mobilenetv2/ssr_model/gender-model/conv3x3_s2_bn_scale
> /home/un/work/mobilenetv2/ssr_model/gender-model/conv3x3_s2_bn_variance
> /home/un/work/mobilenetv2/ssr_model/gender-model/conv3x3_s2_weights
> /home/un/work/mobilenetv2/ssr_model/gender-model/conv3x3_s3_bn_mean
> /home/un/work/mobilenetv2/ssr_model/gender-model/conv3x3_s3_bn_offset
> /home/un/work/mobilenetv2/ssr_model/gender-model/conv3x3_s3_bn_scale
> /home/un/work/mobilenetv2/ssr_model/gender-model/conv3x3_s3_bn_variance
> /home/un/work/mobilenetv2/ssr_model/gender-model/conv3x3_s3_weights
> /home/un/work/mobilenetv2/ssr_model/gender-model/conv3x3_s4_bn_mean
> /home/un/work/mobilenetv2/ssr_model/gender-model/conv3x3_s4_bn_offset
> /home/un/work/mobilenetv2/ssr_model/gender-model/conv3x3_s4_bn_scale
> /home/un/work/mobilenetv2/ssr_model/gender-model/conv3x3_s4_bn_variance
> /home/un/work/mobilenetv2/ssr_model/gender-model/conv3x3_s4_weights
> /home/un/work/mobilenetv2/ssr_model/gender-model/conv3x3_s5_weights
> /home/un/work/mobilenetv2/ssr_model/gender-model/conv_pool_s_layer1_weights
> /home/un/work/mobilenetv2/ssr_model/gender-model/conv_pool_s_layer2_weights
> /home/un/work/mobilenetv2/ssr_model/gender-model/conv_pool_x_layer1_weights
> /home/un/work/mobilenetv2/ssr_model/gender-model/conv_pool_x_layer2_weights
> /home/un/work/mobilenetv2/ssr_model/gender-model/delta_s1_fc.b_0
> /home/un/work/mobilenetv2/ssr_model/gender-model/delta_s1_fc.w_0
> /home/un/work/mobilenetv2/ssr_model/gender-model/delta_s2_fc.b_0
> /home/un/work/mobilenetv2/ssr_model/gender-model/delta_s2_fc.w_0
> /home/un/work/mobilenetv2/ssr_model/gender-model/delta_s3_fc.b_0
> /home/un/work/mobilenetv2/ssr_model/gender-model/delta_s3_fc.w_0
> /home/un/work/mobilenetv2/ssr_model/gender-model/feat_a_s1_fc.b_0
> /home/un/work/mobilenetv2/ssr_model/gender-model/feat_a_s1_fc.w_0
> /home/un/work/mobilenetv2/ssr_model/gender-model/feat_a_s2_fc.b_0
> /home/un/work/mobilenetv2/ssr_model/gender-model/feat_a_s2_fc.w_0
> /home/un/work/mobilenetv2/ssr_model/gender-model/feat_a_s3_fc.b_0
> /home/un/work/mobilenetv2/ssr_model/gender-model/feat_a_s3_fc.w_0
> /home/un/work/mobilenetv2/ssr_model/gender-model/local_s1_fc.b_0
> /home/un/work/mobilenetv2/ssr_model/gender-model/local_s1_fc.w_0
> /home/un/work/mobilenetv2/ssr_model/gender-model/local_s2_fc.b_0
> /home/un/work/mobilenetv2/ssr_model/gender-model/local_s2_fc.w_0
> /home/un/work/mobilenetv2/ssr_model/gender-model/local_s3_fc.b_0
> /home/un/work/mobilenetv2/ssr_model/gender-model/local_s3_fc.w_0
> /home/un/work/mobilenetv2/ssr_model/gender-model/**model**
> /home/un/work/mobilenetv2/ssr_model/gender-model/output_fc.b_0
> /home/un/work/mobilenetv2/ssr_model/gender-model/output_fc.w_0
> /home/un/work/mobilenetv2/ssr_model/gender-model/pred_a_s1_fc.b_0
> /home/un/work/mobilenetv2/ssr_model/gender-model/pred_a_s1_fc.w_0
> /home/un/work/mobilenetv2/ssr_model/gender-model/pred_a_s2_fc.b_0
> /home/un/work/mobilenetv2/ssr_model/gender-model/pred_a_s2_fc.w_0
> /home/un/work/mobilenetv2/ssr_model/gender-model/pred_a_s3_fc.b_0
> /home/un/work/mobilenetv2/ssr_model/gender-model/pred_a_s3_fc.w_0
> /home/un/work/mobilenetv2/ssr_model/gender-model/s_layer1_mix.b_0
> /home/un/work/mobilenetv2/ssr_model/gender-model/s_layer1_mix.w_0
> /home/un/work/mobilenetv2/ssr_model/gender-model/s_layer2_mix.b_0
> /home/un/work/mobilenetv2/ssr_model/gender-model/s_layer2_mix.w_0
> /home/un/work/mobilenetv2/ssr_model/gender-model/s_layer4_mix.b_0
> /home/un/work/mobilenetv2/ssr_model/gender-model/s_layer4_mix.w_0
> /home/un/work/mobilenetv2/ssr_model/gender-model/x_layer1_mix.b_0
> /home/un/work/mobilenetv2/ssr_model/gender-model/x_layer1_mix.w_0
> /home/un/work/mobilenetv2/ssr_model/gender-model/x_layer2_mix.b_0
> /home/un/work/mobilenetv2/ssr_model/gender-model/x_layer2_mix.w_0
> /home/un/work/mobilenetv2/ssr_model/gender-model/x_layer4_mix.b_0
> /home/un/work/mobilenetv2/ssr_model/gender-model/x_layer4_mix.w_0
> 其中存在一个__model__文件，不清楚这个文件时干嘛的，在前向推理的时候，是否需要这个文件？请大佬指点。

你好，这是model文件，记录模型结构的。推理时需要加载模型结构

**Comment by spencergotowork** [comment]
> > 大佬，我使用paddle静态图训练模型后，模型文件保存的参数如下：
> > /home/un/work/mobilenetv2/ssr_model/gender-model/conv3x3_1_bn_mean
> > /home/un/work/mobilenetv2/ssr_model/gender-model/conv3x3_1_bn_offset
> > /home/un/work/mobilenetv2/ssr_model/gender-model/conv3x3_1_bn_scale
> > /home/un/work/mobilenetv2/ssr_model/gender-model/conv3x3_1_bn_variance
> > /home/un/work/mobilenetv2/ssr_model/gender-model/conv3x3_1_weights
> > /home/un/work/mobilenetv2/ssr_model/gender-model/conv3x3_2_bn_mean
> > /home/un/work/mobilenetv2/ssr_model/gender-model/conv3x3_2_bn_offset
> > /home/un/work/mobilenetv2/ssr_model/gender-model/conv3x3_2_bn_scale
> > /home/un/work/mobilenetv2/ssr_model/gender-model/conv3x3_2_bn_variance
> > /home/un/work/mobilenetv2/ssr_model/gender-model/conv3x3_2_weights
> > /home/un/work/mobilenetv2/ssr_model/gender-model/conv3x3_3_bn_mean
> > /home/un/work/mobilenetv2/ssr_model/gender-model/conv3x3_3_bn_offset
> > /home/un/work/mobilenetv2/ssr_model/gender-model/conv3x3_3_bn_scale
> > /home/un/work/mobilenetv2/ssr_model/gender-model/conv3x3_3_bn_variance
> > /home/un/work/mobilenetv2/ssr_model/gender-model/conv3x3_3_weights
> > /home/un/work/mobilenetv2/ssr_model/gender-model/conv3x3_4_bn_mean
> > /home/un/work/mobilenetv2/ssr_model/gender-model/conv3x3_4_bn_offset
> > /home/un/work/mobilenetv2/ssr_model/gender-model/conv3x3_4_bn_scale
> > /home/un/work/mobilenetv2/ssr_model/gender-model/conv3x3_4_bn_variance
> > /home/un/work/mobilenetv2/ssr_model/gender-model/conv3x3_4_weights
> > /home/un/work/mobilenetv2/ssr_model/gender-model/conv3x3_5_weights
> > /home/un/work/mobilenetv2/ssr_model/gender-model/conv3x3_s1_bn_mean
> > /home/un/work/mobilenetv2/ssr_model/gender-model/conv3x3_s1_bn_offset
> > /home/un/work/mobilenetv2/ssr_model/gender-model/conv3x3_s1_bn_scale
> > /home/un/work/mobilenetv2/ssr_model/gender-model/conv3x3_s1_bn_variance
> > /home/un/work/mobilenetv2/ssr_model/gender-model/conv3x3_s1_weights
> > /home/un/work/mobilenetv2/ssr_model/gender-model/conv3x3_s2_bn_mean
> > /home/un/work/mobilenetv2/ssr_model/gender-model/conv3x3_s2_bn_offset
> > /home/un/work/mobilenetv2/ssr_model/gender-model/conv3x3_s2_bn_scale
> > /home/un/work/mobilenetv2/ssr_model/gender-model/conv3x3_s2_bn_variance
> > /home/un/work/mobilenetv2/ssr_model/gender-model/conv3x3_s2_weights
> > /home/un/work/mobilenetv2/ssr_model/gender-model/conv3x3_s3_bn_mean
> > /home/un/work/mobilenetv2/ssr_model/gender-model/conv3x3_s3_bn_offset
> > /home/un/work/mobilenetv2/ssr_model/gender-model/conv3x3_s3_bn_scale
> > /home/un/work/mobilenetv2/ssr_model/gender-model/conv3x3_s3_bn_variance
> > /home/un/work/mobilenetv2/ssr_model/gender-model/conv3x3_s3_weights
> > /home/un/work/mobilenetv2/ssr_model/gender-model/conv3x3_s4_bn_mean
> > /home/un/work/mobilenetv2/ssr_model/gender-model/conv3x3_s4_bn_offset
> > /home/un/work/mobilenetv2/ssr_model/gender-model/conv3x3_s4_bn_scale
> > /home/un/work/mobilenetv2/ssr_model/gender-model/conv3x3_s4_bn_variance
> > /home/un/work/mobilenetv2/ssr_model/gender-model/conv3x3_s4_weights
> > /home/un/work/mobilenetv2/ssr_model/gender-model/conv3x3_s5_weights
> > /home/un/work/mobilenetv2/ssr_model/gender-model/conv_pool_s_layer1_weights
> > /home/un/work/mobilenetv2/ssr_model/gender-model/conv_pool_s_layer2_weights
> > /home/un/work/mobilenetv2/ssr_model/gender-model/conv_pool_x_layer1_weights
> > /home/un/work/mobilenetv2/ssr_model/gender-model/conv_pool_x_layer2_weights
> > /home/un/work/mobilenetv2/ssr_model/gender-model/delta_s1_fc.b_0
> > /home/un/work/mobilenetv2/ssr_model/gender-model/delta_s1_fc.w_0
> > /home/un/work/mobilenetv2/ssr_model/gender-model/delta_s2_fc.b_0
> > /home/un/work/mobilenetv2/ssr_model/gender-model/delta_s2_fc.w_0
> > /home/un/work/mobilenetv2/ssr_model/gender-model/delta_s3_fc.b_0
> > /home/un/work/mobilenetv2/ssr_model/gender-model/delta_s3_fc.w_0
> > /home/un/work/mobilenetv2/ssr_model/gender-model/feat_a_s1_fc.b_0
> > /home/un/work/mobilenetv2/ssr_model/gender-model/feat_a_s1_fc.w_0
> > /home/un/work/mobilenetv2/ssr_model/gender-model/feat_a_s2_fc.b_0
> > /home/un/work/mobilenetv2/ssr_model/gender-model/feat_a_s2_fc.w_0
> > /home/un/work/mobilenetv2/ssr_model/gender-model/feat_a_s3_fc.b_0
> > /home/un/work/mobilenetv2/ssr_model/gender-model/feat_a_s3_fc.w_0
> > /home/un/work/mobilenetv2/ssr_model/gender-model/local_s1_fc.b_0
> > /home/un/work/mobilenetv2/ssr_model/gender-model/local_s1_fc.w_0
> > /home/un/work/mobilenetv2/ssr_model/gender-model/local_s2_fc.b_0
> > /home/un/work/mobilenetv2/ssr_model/gender-model/local_s2_fc.w_0
> > /home/un/work/mobilenetv2/ssr_model/gender-model/local_s3_fc.b_0
> > /home/un/work/mobilenetv2/ssr_model/gender-model/local_s3_fc.w_0
> > /home/un/work/mobilenetv2/ssr_model/gender-model/**model**
> > /home/un/work/mobilenetv2/ssr_model/gender-model/output_fc.b_0
> > /home/un/work/mobilenetv2/ssr_model/gender-model/output_fc.w_0
> > /home/un/work/mobilenetv2/ssr_model/gender-model/pred_a_s1_fc.b_0
> > /home/un/work/mobilenetv2/ssr_model/gender-model/pred_a_s1_fc.w_0
> > /home/un/work/mobilenetv2/ssr_model/gender-model/pred_a_s2_fc.b_0
> > /home/un/work/mobilenetv2/ssr_model/gender-model/pred_a_s2_fc.w_0
> > /home/un/work/mobilenetv2/ssr_model/gender-model/pred_a_s3_fc.b_0
> > /home/un/work/mobilenetv2/ssr_model/gender-model/pred_a_s3_fc.w_0
> > /home/un/work/mobilenetv2/ssr_model/gender-model/s_layer1_mix.b_0
> > /home/un/work/mobilenetv2/ssr_model/gender-model/s_layer1_mix.w_0
> > /home/un/work/mobilenetv2/ssr_model/gender-model/s_layer2_mix.b_0
> > /home/un/work/mobilenetv2/ssr_model/gender-model/s_layer2_mix.w_0
> > /home/un/work/mobilenetv2/ssr_model/gender-model/s_layer4_mix.b_0
> > /home/un/work/mobilenetv2/ssr_model/gender-model/s_layer4_mix.w_0
> > /home/un/work/mobilenetv2/ssr_model/gender-model/x_layer1_mix.b_0
> > /home/un/work/mobilenetv2/ssr_model/gender-model/x_layer1_mix.w_0
> > /home/un/work/mobilenetv2/ssr_model/gender-model/x_layer2_mix.b_0
> > /home/un/work/mobilenetv2/ssr_model/gender-model/x_layer2_mix.w_0
> > /home/un/work/mobilenetv2/ssr_model/gender-model/x_layer4_mix.b_0
> > /home/un/work/mobilenetv2/ssr_model/gender-model/x_layer4_mix.w_0
> > 其中存在一个__model__文件，不清楚这个文件时干嘛的，在前向推理的时候，是否需要这个文件？请大佬指点。
> 
> 你好，这是model文件，记录模型结构的。推理时需要加载模型结构

这个__model__如何生成，为什么我下载的模型文件里只有pdiparams 和 pdmodel 文件，但是好像C++从目录加载模型的时候会检索这个__model__文件，请问改如何生成呢？
