### ISSUE TITLE
paddle 2.0 安装问题

### ISSUE THREAD

**Issue by xialei2821212670** [PaddlePaddle/Paddle#29314]
我尝试安装了2.0版本的paddle-gpu，但是遇到了问题，初步认为vc的dll 安装问题，尝试去重新安装vc 2015~2019。 成功的把1.8.4的paddle-gpu 给弄的找不到vc环境。于是我尝试重新一个个安装vc ,直到1.8.4重新运行，但是切换到2.0版本还是出现ImportError: DLL load failed: 找不到指定的程序。
成功安装1.8.4
![image](https://user-images.githubusercontent.com/57654726/100954654-f2f89d00-354f-11eb-9494-b526eb006fa2.png)
尝试2.0
![image](https://user-images.githubusercontent.com/57654726/100954729-191e3d00-3550-11eb-8930-0d360742ef83.png)

**Comment by wawltor** [comment]
相应的同学已经在排查问题了，请稍候~~

**Comment by DDDivano** [comment]
在anaconda环境下可以使用conda install 来安装paddlepaddle

**Comment by XieYunshen** [comment]
可以在anaconda prompt窗口下使用pip安装,或者重新安装Python，不使用anaconda的Python

**Comment by xialei2821212670** [comment]
> 在anaconda环境下可以使用conda install来安装paddlepaddle

你好，我尝试过conda 安装。还是一样的

**Comment by xialei2821212670** [comment]
你好，麻烦问下，这个安装的问题如何解决。

**Comment by yeyupiaoling** [comment]
我的也是这个问题，我安装的版本是CPU版本，CPU信息：
![image](https://user-images.githubusercontent.com/26297768/101272321-26dcf800-37c6-11eb-9846-b67dc48ba711.png)

错误信息：
```
>>> import paddle
Error: Can not import noavx core while this file exists C:\Python37\lib\site-packages\paddle\fluid\core_noavx.pyd
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python37\lib\site-packages\paddle\__init__.py", line 37, in <module>
    import paddle.complex
  File "C:\Python37\lib\site-packages\paddle\complex\__init__.py", line 15, in <module>
    from . import tensor
  File "C:\Python37\lib\site-packages\paddle\complex\tensor\__init__.py", line 15, in <module>
    from . import math
  File "C:\Python37\lib\site-packages\paddle\complex\tensor\math.py", line 15, in <module>
    from paddle.common_ops_import import *
  File "C:\Python37\lib\site-packages\paddle\common_ops_import.py", line 15, in <module>
    from paddle.fluid.layer_helper import LayerHelper
  File "C:\Python37\lib\site-packages\paddle\fluid\__init__.py", line 35, in <module>
    from . import framework
  File "C:\Python37\lib\site-packages\paddle\fluid\framework.py", line 35, in <module>
    from . import core
  File "C:\Python37\lib\site-packages\paddle\fluid\core.py", line 320, in <module>
    raise e
  File "C:\Python37\lib\site-packages\paddle\fluid\core.py", line 287, in <module>
    from .core_noavx import *
ImportError: DLL load failed: 找不到指定的程序。
```

**Comment by xialei2821212670** [comment]
> 我的也是这个问题，我安装的版本是CPU版本，CPU信息：
> ![图片](https://user-images.githubusercontent.com/26297768/101272321-26dcf800-37c6-11eb-9846-b67dc48ba711.png)
> 
> 错误信息：
> 
> ```
> >>> import paddle
> Error: Can not import noavx core while this file exists C:\Python37\lib\site-packages\paddle\fluid\core_noavx.pyd
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "C:\Python37\lib\site-packages\paddle\__init__.py", line 37, in <module>
>     import paddle.complex
>   File "C:\Python37\lib\site-packages\paddle\complex\__init__.py", line 15, in <module>
>     from . import tensor
>   File "C:\Python37\lib\site-packages\paddle\complex\tensor\__init__.py", line 15, in <module>
>     from . import math
>   File "C:\Python37\lib\site-packages\paddle\complex\tensor\math.py", line 15, in <module>
>     from paddle.common_ops_import import *
>   File "C:\Python37\lib\site-packages\paddle\common_ops_import.py", line 15, in <module>
>     from paddle.fluid.layer_helper import LayerHelper
>   File "C:\Python37\lib\site-packages\paddle\fluid\__init__.py", line 35, in <module>
>     from . import framework
>   File "C:\Python37\lib\site-packages\paddle\fluid\framework.py", line 35, in <module>
>     from . import core
>   File "C:\Python37\lib\site-packages\paddle\fluid\core.py", line 320, in <module>
>     raise e
>   File "C:\Python37\lib\site-packages\paddle\fluid\core.py", line 287, in <module>
>     from .core_noavx import *
> ImportError: DLL load failed: 找不到指定的程序。
> ```

我尝试cpu 也是这个情况，GPU一样。等待工作人员查看吧

**Comment by xialei2821212670** [comment]
> 相应的同学已经在排查问题了，请稍候~~

你好，有复现过这个问题？

**Comment by DDDivano** [comment]
> > 相应的同学已经在排查问题了，请稍候~~
> 
> 你好，有复现过这个问题？

这个报错是因为电脑没有avx指令集，所以他调用了noavx的core，但是我们机器没有noavx的cpu，所以这边无法复现该问题。

**Comment by DDDivano** [comment]
> > 相应的同学已经在排查问题了，请稍候~~
> 
> 你好，有复现过这个问题？

安装10.0试试？

**Comment by xialei2821212670** [comment]
![image](https://user-images.githubusercontent.com/57654726/103090460-03220a80-462c-11eb-8d70-11aef69782e7.png)


> > > 相应的同学已经在排查问题了，请稍候~~
> > 
> > 
> > 你好，有复现过这个问题？
> 
> 安装10.0试试？

![image](https://user-images.githubusercontent.com/57654726/103090470-09b08200-462c-11eb-9f8f-6e9b445a9952.png)

y应该支持指令的吧

**Comment by swtkiwi** [comment]
https://www.microsoft.com/en-us/download/details.aspx?id=48145 辛苦先装下编译器相关的dll试下
