### ISSUE TITLE
在云上的机器跑gpu的版本的报错

### ISSUE THREAD

**Issue by WoNiuHu** [PaddlePaddle/Paddle#2931]
hi，在云上的机器跑的gpu的版本的报错如下：
`root@311257b81a76:/work# bash run.sh lstm_train

I0718 02:20:33.320343    36 Util.cpp:155] commandline: /usr/local/bin/../opt/paddle/bin/paddle_trainer --config=trainer_config.py --save_dir=./model_output --job=train --use_gpu=true --trainer_count=1 --num_passes=2 --log_period=10 --dot_period=20 --show_parameter_stats_period=100 --test_all_data_in_one_period=1 

I0718 02:22:57.979029    36 Util.cpp:130] Calling runInitFunctions

I0718 02:22:57.980270    36 Util.cpp:143] Call runInitFunctions done.

[INFO 2017-07-18 02:22:59,474 networks.py:1466] The input order is [word, label]
[INFO 2017-07-18 02:22:59,474 networks.py:1472] The output order is [__cost_0__]
I0718 02:22:59.617970    36 Trainer.cpp:170] trainer mode: Normal

F0718 02:22:59.624567    36 hl_gpu_matrix_kernel.cuh:181] Check failed: cudaSuccess == err (0 vs. 8) [hl_gpu_apply_unary_op failed] CUDA error: invalid device function
*** Check failure stack trace: ***`

已经安装nvidia-docker 和 paddledev/paddle:gpu-release-v0.9.0 的镜像，

**Comment by hedaoyuan** [comment]
@WoNiuHu 相似的问题参考 #34
paddledev/paddle:gpu-release-v0.9.0的镜像可能不是用`sm_60`编译的，不支持你的环境。

**Comment by WoNiuHu** [comment]
@hedaoyuan 

Cirrus Logic GD 5446
NVIDIA Corporation Device 1b00 (rev a1)

**Comment by helinwang** [comment]
@hedaoyuan 我理解v0.10.0不支持v1 API（具体请看https://github.com/PaddlePaddle/Paddle/issues/2946#issuecomment-316199804），我来帮@WoNiuHu编译一个v0.9.0的CUDA 8 docker镜像吧。

**Comment by typhoonzero** [comment]
@helinwang v0.10.0 应该是支持v1 API的。v2 API仅是在v1基础之上增加了新的python binding入口，v1的使用方式在develop分支是一直可以使用的。

**Comment by WoNiuHu** [comment]
@helinwang 辛苦辛苦

**Comment by helinwang** [comment]
@typhoonzero 请看https://github.com/PaddlePaddle/Paddle/issues/2946#issuecomment-316199804，我测试了一下`paddlepaddle/paddle:0.10.0rc2`是无法跑`https://github.com/PaddlePaddle/Paddle/tree/develop/v1_api_demo/mnist`这个demo的。

**Comment by WoNiuHu** [comment]
@helinwang @typhoonzero 所以这个问题的解决方案是？

**Comment by helinwang** [comment]
@WoNiuHu 请用0.10.0的docker image运行，操作方法是和0.9.0的docker image一致的。

**Comment by Canpio** [comment]
Close this issue due to inactivity. please feel free to reopen it if more information is available.
