### ISSUE TITLE
paddle.fluid.layers.lstm权重赋值

### ISSUE THREAD

**Issue by Jorsen0** [PaddlePaddle/Paddle#29328]
- 版本、环境信息：
    1）PaddlePaddle版本：1.8.4
    2）CPU/GPU：CUDA10
    3）系统环境：ubuntu16.04
    4）Python版本号：3.6.5
    5）显存信息

- 问题描述：请问有没有为LSTM的权重进行赋值的AP，就是讲numpy数组赋值到lstm，如果有的话权重的维度是什么样的呢，四个门的顺序又是如何呢？

**Comment by wawltor** [comment]
在lstm中有个选项，可以使用https://www.paddlepaddle.org.cn/documentation/docs/zh/api_cn/initializer_cn/NumpyArrayInitializer_cn.html#numpyarrayinitializer 来进行初始化

**Comment by Jorsen0** [comment]
> 在lstm中有个选项，可以使用https://www.paddlepaddle.org.cn/documentation/docs/zh/api_cn/initializer_cn/NumpyArrayInitializer_cn.html#numpyarrayinitializer 来进行初始化

好的，多谢解答，如果我这样初始化的话，weight维度是什么样的呢，bias的初始化需要怎么做呢

**Comment by wawltor** [comment]
不好意思现在才看到，我看了一下具体的实现逻辑，确实不太好用NumpyInitializer，你是否可以切换2.0 rc动态图的API，动态图的版本是可以很轻松只是weight和bias的初始化的设置的
