### ISSUE TITLE
1.8.5cpu版本，是否支持Windows Server 2019 64位？

### ISSUE THREAD

**Issue by yilvshifeng** [PaddlePaddle/Paddle#29320]
>>> import paddle
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\deploy\env\Python\Python36\lib\site-packages\paddle\__init__.py", line 35, in <module>
    batch = batch.batch
NameError: name 'batch' is not defined
>>>
提示错误“NameError: name 'batch' is not defined”，
安装版本如下：
Collecting paddlepaddle==1.8.5
  Downloading https://mirror.baidu.com/pypi/packages/fe/13/57206330cfde448145676181b6a71fcb608f2359e6b58b5381dd913474cb/paddlepaddle-1.8.5-cp36-cp36m-win_amd64.whl

**Comment by wawltor** [comment]
相应的同学已经在排查了，请稍候 ~~

**Comment by DDDivano** [comment]
可以详细说下 paddle和 python安装方式吗？因为这个路径本身就是有问题的，少了个 \\
![image](https://user-images.githubusercontent.com/10734244/100973554-b50e6f80-3575-11eb-9346-3fe87b42944e.png)

**Comment by yilvshifeng** [comment]
> 可以详细说下 paddle和 python安装方式吗？因为这个路径本身就是有问题的，少了个 \
> ![image](https://user-images.githubusercontent.com/10734244/100973554-b50e6f80-3575-11eb-9346-3fe87b42944e.png)

python是使用python-3.6.5-amd64.exe安装包方式安装，paddlepaddle是pip安装，命令：pip install paddlepaddle -i https://mirror.baidu.com/pypi/simple

**Comment by yilvshifeng** [comment]
> 可以详细说下 paddle和 python安装方式吗？因为这个路径本身就是有问题的，少了个 \
> ![image](https://user-images.githubusercontent.com/10734244/100973554-b50e6f80-3575-11eb-9346-3fe87b42944e.png)

>>> import paddle
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\deploy\env\Python\Python36\lib\site-packages\paddle\__init__.py", line 35, in <module>
    batch = batch.batch
NameError: name 'batch' is not defined
>>>
完整的提示如上，那里少的“\”可能是后面不小心删掉了，抱歉！！！

**Comment by DDDivano** [comment]
路径应该是在 File "C:\deploy\env\Python\Python36\lib\site-packages\paddle\_init_.py", line 35

**Comment by DDDivano** [comment]
> > 可以详细说下 paddle和 python安装方式吗？因为这个路径本身就是有问题的，少了个 
> > ![image](https://user-images.githubusercontent.com/10734244/100973554-b50e6f80-3575-11eb-9346-3fe87b42944e.png)
> 
> > > > import paddle
> > > > Traceback (most recent call last):
> > > > File "", line 1, in 
> > > > File "C:\deploy\env\Python\Python36\lib\site-packages\paddle__init__.py", line 35, in 
> > > > batch = batch.batch
> > > > NameError: name 'batch' is not defined
> 
> 完整的提示如上，那里少的“\”可能是后面不小心删掉了，抱歉！！！

import paddle.batch
batch = batch.batch

直接打这个报错吗

**Comment by yilvshifeng** [comment]
> > 可以详细说下 paddle和 python安装方式吗？因为这个路径本身就是有问题的，少了个 
> > ![image](https://user-images.githubusercontent.com/10734244/100973554-b50e6f80-3575-11eb-9346-3fe87b42944e.png)
> 
> > > > import paddle
> > > > Traceback (most recent call last):
> > > > File "", line 1, in 
> > > > File "C:\deploy\env\Python\Python36\lib\site-packages\paddle__init__.py", line 35, in 
> > > > batch = batch.batch
> > > > NameError: name 'batch' is not defined
> 
> 完整的提示如上，那里少的“\”可能是后面不小心删掉了，抱歉！！！

编辑的时候是有“\”的，提交之后，在这里显示就少了“\”！！！这里的路径没有错的！

**Comment by yilvshifeng** [comment]
> > > 可以详细说下 paddle和 python安装方式吗？因为这个路径本身就是有问题的，少了个
> > > ![image](https://user-images.githubusercontent.com/10734244/100973554-b50e6f80-3575-11eb-9346-3fe87b42944e.png)
> > 
> > 
> > > > > import paddle
> > > > > Traceback (most recent call last):
> > > > > File "", line 1, in
> > > > > File "C:\deploy\env\Python\Python36\lib\site-packages\paddle__init__.py", line 35, in
> > > > > batch = batch.batch
> > > > > NameError: name 'batch' is not defined
> > 
> > 
> > 完整的提示如上，那里少的“\”可能是后面不小心删掉了，抱歉！！！
> 
> import paddle.batch
> batch = batch.batch
> 
> 直接打这个报错吗

一样的报错：
>>> import paddle.batch
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\deploy\env\Python\Python36\lib\site-packages\paddle\__init__.py", line 35, in <module>
    batch = batch.batch
NameError: name 'batch' is not defined

**Comment by baixiaoming555** [comment]
同样遇到这个问题，解决了么

**Comment by baixiaoming555** [comment]
用conda安装成功了

**Comment by yilvshifeng** [comment]
> 同样遇到这个问题，解决了么

还是没有解决，同样的系统，同样的配置，同样的安装方式在有的机器上可以，有的却又不行！没找到原因！
