### ISSUE TITLE
本地多卡训练时，程序终止，服务器用户退出

### ISSUE THREAD

**Issue by shinianzhihou** [PaddlePaddle/Paddle#29334]
- 版本、环境信息：
Paddle version: 1.8.5
Paddle With CUDA: True
OS: debian buster/sid
Python version: 3.6.11
CUDA version: 10.0.130
cuDNN version: 7
Nvidia driver version: 450.80.02
- 训练信息
    1）单机多卡
    2）显存增长到一定时，程序异常终止，服务器当前用户直接退出，尝试调小batchsize也无效。
运行命令是：
export CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7
python       pdseg/train.py --use_gpu \
                            --cfg  ../configs/deeplab_res2net_vd.yaml\
                            --use_vdl \
                            --vdl_log_dir ../logs/deeplab_res2net_vd_resume10/ \
                            --log_steps 20 \
                            --use_mpio \
                            --do_eval \
                            SOLVER.LR 0.05 \
                            BATCH_SIZE 120 \
                            SOLVER.LR_WARMUP True \
                            SOLVER.LR_WARMUP_STEPS 100 \
                            TRAIN.SNAPSHOT_EPOCH 1 \
                            TRAIN.SYNC_BATCH_NORM True \
                            TRAIN.PRETRAINED_MODEL_DIR ./saved_model/deeplab_res2net_vd/10

**Comment by shinianzhihou** [comment]
可能是mpio的问题，我关了--use_mpio 就行了，但是速度降了很多

**Comment by shinianzhihou** [comment]
又出现这个问题了，请问可能是什么原因呀？为什么会导致服务器的用户下线呢

**Comment by wawltor** [comment]
@wuyefeilin 帮这个同学看看这个问题哈

**Comment by wuyefeilin** [comment]
@shinianzhihou 请把issue提到https://github.com/PaddlePaddle/PaddleSeg中，方便我们跟踪哈。

有可能是因为资源超载引起的问题.  cuDNN version: 7, 具体是7.几给一下哈
