### ISSUE TITLE
集成baidu-rpc出现unknow command line flag 'use_gpu'

### ISSUE THREAD

**Issue by fingthinking** [PaddlePaddle/Paddle#2933]
本问题是[使用C-API，链接`libpaddle_capi_whole.a`库，运行的时候遇到UnKnown class type: data](https://github.com/PaddlePaddle/Paddle/issues/2863)尝试解决问题中遇到，主要显示内容如下：
![unknow command line flag](https://user-images.githubusercontent.com/5517388/28206544-f0999184-68b8-11e7-93f7-17fb2cb43fa8.png)
其问题是在使用动态库`libpaddle_capi_shared.so`的时候，gflags不识别--use_gpu=False参数。
原使用方式为：
```C++
char* argv[] = {(char*)"--use_gpu=False"};
 // init paddle
CHECK(paddle_init(1, (char**)argv));
```
通过将代码改为：
```C++
char* argv[] = {(char*)"--use_gpu=False"};
 // init paddle
CHECK(paddle_init(0, (char**)argv));
```
即不传参数了，将该问题解决
但该解决方案属于治标不治本的方法，如果今后有需要使用gpu的需求，仍将面临该问题。

提供一些思路，在使用libpaddle_capi_whole.a的时候，遇到一些编译问题，其中包括gflags与baidu-rpc的兼容性问题，baidu-rpc中使用的gflag的版本是2.0，其中关键不兼容代码：
```C++
FlagRegisterer::FlagRegisterer(const char* name, const char* type,
                               const char* help, const char* filename,
                               void* current_storage, void* defvalue_storage) {
  if (help == NULL)
    help = "";
  // FlagValue expects the type-name to not include any namespace
  // components, so we get rid of those, if any.
  if (strchr(type, ':'))
    type = strrchr(type, ':') + 1;
  FlagValue* current = new FlagValue(current_storage, type, false);
  FlagValue* defvalue = new FlagValue(defvalue_storage, type, false);
  // Importantly, flag_ will never be deleted, so storage is always good.
  CommandLineFlag* flag = new CommandLineFlag(name, help, filename,
                                              current, defvalue);
  FlagRegistry::GlobalRegistry()->RegisterFlag(flag);   // default registry
}
```
而在paddle中使用的gflags的版本为2.2.0以上，代码如：
```C++
template <typename FlagType>
FlagRegisterer::FlagRegisterer(const char* name,
                               const char* help,
                               const char* filename,
                               FlagType* current_storage,
                               FlagType* defvalue_storage) {
  FlagValue* const current = new FlagValue(current_storage, false);
  FlagValue* const defvalue = new FlagValue(defvalue_storage, false);
  RegisterCommandLineFlag(name, help, filename, current, defvalue);
}
```
即2.2版本的gflags与2.0版本存在不兼容问题，该问题通过在2.2版本中增加2.0版本的不兼容代码及相关逻辑，可以解决，但是还是没能够识别出use_gpg参数，这个就不明白为什么了，请paddle帮忙解答疑惑。

**Comment by Superjom** [comment]
总结下

- 是因为两者gflags版本不一致，用trick解决版本不一致后出现 `use_gpu` 不识别？

**Comment by fingthinking** [comment]
@Superjom 我也不清楚是什么原因导致的，使用动态库的时候以及baidu-rpc默认的gflags，会出现问题，我替换成修改后的gflags, 仍然会出现这个问题，有点儿搞不明白原因。

**Comment by Superjom** [comment]
现在用的是 gflags 2.2 版本？ 是和paddle匹配的版本？

**Comment by fingthinking** [comment]
@Superjom 用的2.0版本，baidu-rpc需要的，2.2版本与2.0无法兼容，我之前尝试修改源码让他们兼容了，但是还是会报出这个错误。

**Comment by Superjom** [comment]
感觉还是 gflags 版本造成的奇怪问题，从代码上看， `use_gpu` 和其他flag没有任何区别，但无法出来感觉是版本没法打平。

Paddle 现在依赖gflags 2.2版本，2.0版本没法保证没有问题。
