### ISSUE TITLE
You are using Paddle compiled with TensorRT, but TensorRT dynamic library is not found. Ignore this if TensorRT is not needed.>>> 

### ISSUE THREAD

**Issue by sun-ching** [PaddlePaddle/Paddle#29362]
when i input "import paddle.fluid",the computer give me an error"You are using Paddle compiled with TensorRT, but TensorRT dynamic library is not found. Ignore this if TensorRT is not needed.>>>"
so what should i do ?
thank you!

**Comment by qingqing01** [comment]
@sun-ching If you do not use TensorRT for inference, you can ingore this wanring.

**Comment by sun-ching** [comment]
> @sun-ching If you do not use TensorRT for inference, you can ingore this wanring.
i will use TesorRT.what should i do ?

**Comment by sun-ching** [comment]
> @sun-ching If you do not use TensorRT for inference, you can ingore this wanring.



> @sun-ching If you do not use TensorRT for inference, you can ingore this wanring.



> @sun-ching If you do not use TensorRT for inference, you can ingore this wanring.

But i will use TensorRT,so what should i do?Thank you

**Comment by qingqing01** [comment]
@sun-ching You can try to download TensorRT library, and set lib into LD_LIBRARY_PATH.

**Comment by feymanpriv** [comment]
> @sun-ching You can try to download TensorRT library, and set lib into LD_LIBRARY_PATH.

Hi @qingqing01 , when using paddle2.0.0, cuda10.2 and cudnn8, it throws the same error even the TRT lib is added to LD_LIBRARY_PATH.

**Comment by TTgogogo** [comment]
@feymanpriv, @sun-ching, I found the same problem, have you fixed it? Pls provide me the solution.

**Comment by Aganlengzi** [comment]
I have the same WARNING, but when I set LD_LIBRARY_PATH, it is solved.
I am using Paddle develop compiled by myself with CUDA 11.1 cudnn8.1.1 and TensorRT-7.2.3.4
<img width="997" alt="image" src="https://user-images.githubusercontent.com/5997715/185016439-140e3c4a-002d-4c18-b0a8-d861a418d1e2.png">

<img width="445" alt="image" src="https://user-images.githubusercontent.com/5997715/185016496-992fdd6d-1710-4d20-9157-b95fea9450a1.png">

<img width="502" alt="image" src="https://user-images.githubusercontent.com/5997715/185016746-53f6388b-0b9e-439c-a2a6-e214c76b36bd.png">

**Comment by wanghaoshuang** [comment]
## Question

```
RuntimeError: (NotFound) TensorRT is needed, but TensorRT dynamic library is not found.
  [Hint: dso_handle should not be null.] (at /paddle/paddle/fluid/platform/dynload/tensorrt.cc:47)
```
It will throw [ TensorRT NotFound error](https://github.com/PaddlePaddle/Paddle/blob/v2.4.1/paddle/phi/backends/dynload/tensorrt.cc#L46) if it can't load `libnvinfer.so` ([code](https://github.com/PaddlePaddle/Paddle/blob/v2.4.1/paddle/phi/backends/dynload/tensorrt.cc#L58)) or `libnvinfer_plugin.so` ([code](https://github.com/PaddlePaddle/Paddle/blob/v2.4.1/paddle/phi/backends/dynload/tensorrt.cc#L69)) in linux.

## Solution

### Step1: Prepend path of TensorRT library into LD_LIBRARY_PATH
Find the correct installed TensorRT: 
```
find / -name libnvinfer.so*
```
Or reinstall TensoRT: https://docs.nvidia.com/deeplearning/tensorrt/install-guide/index.html#installing-tar
Add path: 
```
export LD_LIBRARY_PATH=${directory of libnvinfer.so}:$LD_LIBRARY_PATH
# and check
env
```

### Step2: Make sure the dependencies can be found

```
# check the dependencies of libnvinfer.so.8
ldd libnvinfer.so.8
# output means all the dependencies can be found
        linux-vdso.so.1 =>  (0x00007ffcb671b000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f5f6c6a3000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f5f6c49f000)
        librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f5f6c297000)
        libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f5f6bf15000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f5f6bc0c000)
        libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f5f6b9f6000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f5f6b62c000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f5f8a0f7000)
```

```
# check the dependencies of libnvinfer_plugin.so
ldd libnvinfer_plugin.so

# output means libcublas.so.11,   libcublasLt.so.11 and  libcudnn.so.8  can't be found
        linux-vdso.so.1 =>  (0x00007ffd566d7000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f70516c4000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f70514c0000)
        librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f70512b8000)
        libcublas.so.11 => not found
        libcublasLt.so.11 => not found
        libcudnn.so.8 => not found
        libnvinfer.so.8 => /mnt/whs/envs/TensorRT-8.5.1.7/lib/libnvinfer.so.8 (0x00007f7033a81000)
        libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f70336ff000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f70333f6000)
        libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f70331e0000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f7032e16000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f705424a000)
```
So find installed cublas&cudnn and add their path into LD_LIBRARY_PATH. 
And use `ldd libnvinfer_plugin.so` to check it.

**Comment by shiyutang** [comment]
After append path and checking everything, still failing. @wanghaoshuang
![image](https://github.com/PaddlePaddle/Paddle/assets/34859558/a2672acd-51b9-4da4-ae4d-6ac88d565683)

**Comment by Wangzheee** [comment]
应该是没有找到cudnn，继续在LD_LIBRARY_PATH中设置一下 cudnn的lib路径
