### ISSUE TITLE
内部服务器不能联网，怎么使用jumbo一键安装paddle，谢谢，各种单独编译的答案就不用提了，太麻烦了

### ISSUE THREAD

**Issue by zhangqianjin** [PaddlePaddle/Paddle#2938]

**Comment by livc** [comment]
目前PaddlePaddle不能使用Jumbo安装，内网用户请参考 http://wiki.baidu.com/pages/viewpage.action?pageId=327596892 。

**Comment by helinwang** [comment]
@zhangqianjin 请看下@livc的答案哈，虽然没有jumbo安装，但是有二进制直接下载。
