### ISSUE TITLE
2.0rc 抢先版本 cuda 10.2 训练报段错误

### ISSUE THREAD

**Issue by Rayaction** [PaddlePaddle/Paddle#29389]
使用paddleseg分割库，paddle2.0版本
export CUDA_VISIBLE_DEVICES=0
跑pdseg中的train.py时，报以下错误：
Error Message Summary:
----------------------
FatalError: A serious error (Segmentation fault) is detected by the operating system. (at /paddle/paddle/fluid/platform/init.cc:303)
请问如何解决

**Comment by Rayaction** [comment]
具体点的报错如下：
There are 1570/1574 varaibles in ./pretrained_model/ocnet_w18_bn_cityscapes are loaded.
Use multi-thread reader


--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
0   paddle::framework::SignalHandle(char const*, int)
1   paddle::platform::GetCurrentTraceBackString[abi:cxx11]()

----------------------
Error Message Summary:
----------------------
FatalError: A serious error (Segmentation fault) is detected by the operating system. (at /paddle/paddle/fluid/platform/init.cc:303)
  [TimeInfo: *** Aborted at 1607139882 (unix time) try "date -d @1607139882" if you are using GNU date ***]
  [SignalInfo: *** SIGSEGV (@0x0) received by PID 72277 (TID 0x7fced744c700) from PID 0 ***]

**Comment by luotao1** [comment]
duplicated with https://github.com/PaddlePaddle/PaddleSeg/issues/653

**Comment by Rayaction** [comment]
> duplicated with [PaddlePaddle/PaddleSeg#653](https://github.com/PaddlePaddle/PaddleSeg/issues/653)

是的，我两边都提了。您这边看下解决下

**Comment by iotctech** [comment]
使用paddle训练模型遇到同样问题，batch size增大后，直接报错，batch size小的时候可以运行

Paddle2.0rc + cuda10.2

错误日志
```
--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
0   paddle::framework::SignalHandle(char const*, int)
1   paddle::platform::GetCurrentTraceBackString[abi:cxx11]()

----------------------
Error Message Summary:
----------------------
FatalError: A serious error (Segmentation fault) is detected by the operating system. (at /paddle/paddle/fluid/platform/init.cc:303)
  [TimeInfo: *** Aborted at 1607262598 (unix time) try "date -d @1607262598" if you are using GNU date ***]
  [SignalInfo: *** SIGSEGV (@0x0) received by PID 33792 (TID 0x7fe152008740) from PID 0 ***]
```

**Comment by Rayaction** [comment]
6

> 使用paddle训练模型遇到同样问题，batch size增大后，直接报错，batch size小的时候可以运行
> 
> Paddle2.0rc + cuda10.2
> 
> 错误日志
> 
> ```
> --------------------------------------
> C++ Traceback (most recent call last):
> --------------------------------------
> 0   paddle::framework::SignalHandle(char const*, int)
> 1   paddle::platform::GetCurrentTraceBackString[abi:cxx11]()
> 
> ----------------------
> Error Message Summary:
> ----------------------
> FatalError: A serious error (Segmentation fault) is detected by the operating system. (at /paddle/paddle/fluid/platform/init.cc:303)
>   [TimeInfo: *** Aborted at 1607262598 (unix time) try "date -d @1607262598" if you are using GNU date ***]
>   [SignalInfo: *** SIGSEGV (@0x0) received by PID 33792 (TID 0x7fe152008740) from PID 0 ***]
> ```

我设置的bs在10,1版本可以运行的。但是是10.1搭配1.8.5版本paddle，然后换成10.2搭配2.0就不行了

**Comment by Rayaction** [comment]
> 使用paddle训练模型遇到同样问题，batch size增大后，直接报错，batch size小的时候可以运行
> 
> Paddle2.0rc + cuda10.2
> 
> 错误日志
> 
> ```
> --------------------------------------
> C++ Traceback (most recent call last):
> --------------------------------------
> 0   paddle::framework::SignalHandle(char const*, int)
> 1   paddle::platform::GetCurrentTraceBackString[abi:cxx11]()
> 
> ----------------------
> Error Message Summary:
> ----------------------
> FatalError: A serious error (Segmentation fault) is detected by the operating system. (at /paddle/paddle/fluid/platform/init.cc:303)
>   [TimeInfo: *** Aborted at 1607262598 (unix time) try "date -d @1607262598" if you are using GNU date ***]
>   [SignalInfo: *** SIGSEGV (@0x0) received by PID 33792 (TID 0x7fe152008740) from PID 0 ***]
> ```

果真，我bs从调小后可以跑

**Comment by qingchunnianshao** [comment]
batch_size 改成1 我的也还是有这个问题，请问你这个问题解决了吗
