### ISSUE TITLE
nvalidArgumentError: Python object is not type of class std::shared_ptr<class paddle::imperative::VarBase> 

### ISSUE THREAD

**Issue by BullShitMaker** [PaddlePaddle/Paddle#29395]
- 版本、环境信息：
    1）PaddlePaddle版本：paddle2.0rs
    3）GPU：RTX2080TI
    4）系统环境：WIN10 Python3.7.9
- 训练信息
    1）单卡
    2）显存信息
    3）Operator信息
- 复现信息：如为报错，请给出复现环境、复现步骤
- 问题描述：
Exception has occurred: EnforceNotMet

--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
Not support stack backtrace yet.

----------------------
Error Message Summary:
----------------------
InvalidArgumentError: Python object is not type of class std::shared_ptr<class paddle::imperative::VarBase> (at D:\2.0.0-rc0\paddle\paddle\fluid\pybind\imperative.cc:216)
  File "paddle-NLP\DuEL_Baseline\ernie\finetune\type_pairwise_ranker.py", line 96, in create_model
    use_double_buffer=True,
  File "paddle-NLP\DuEL_Baseline\ernie\run_type_pairwise_ranker.py", line 124, in main
    is_regression=args.is_regression,
  File "paddle-NLP\DuEL_Baseline\ernie\run_type_pairwise_ranker.py", line 507, in <module>
    main(args)

**Comment by luotao1** [comment]
> paddle-NLP\DuEL_Baseline\ernie

1. 请问跑的是官方的例子，还是您自己的例子？如果是自己的例子，是否有复现代码？
2. 请问是直接运行出错，还是跑了一段时间出错呢？
3. 相同的程序在linux上会出错么？

**Comment by BullShitMaker** [comment]
> > paddle-NLP\DuEL_Baseline\ernie
> 
> 1. 请问跑的是官方的例子，还是您自己的例子？如果是自己的例子，是否有复现代码？
> 2. 请问是直接运行出错，还是跑了一段时间出错呢？
> 3. 相同的程序在linux上会出错么？

1. 官方例子，没复现代码，只是想跑通
2. 直接出错
3. 没用linux

所以我这个程序的问题到底是什么

**Comment by luotao1** [comment]
能否给一下官方例子的链接？

**Comment by DabeyHolmes** [comment]
我也有类似的问题
我运行的是这个代码
https://github.com/PaddlePaddle/Research/tree/master/KG/ACL2021_GRAN
它原本的配置是
## Requirements
This project should work fine with the following environments:
- Python 2.7.15 for data preprocessing
- Python 3.6.5 for training & evaluation with:
    -  PaddlePaddle 1.5.0
    -  numpy 1.16.3
- GPU with CUDA 9.0, CuDNN v7, and NCCL 2.3.7
但是我是使用的最新的paddle2.2 python3.8
我运行这个代码会直接报错，windows linux都会报相同错
```
C:\ProgramData\Anaconda3\envs\tl\lib\site-packages\paddle\fluid\layers\io.py:721: DeprecationWarning: The 'warn' function is deprecated, use 'warning' instead
  'paddle.fluid.layers.py_reader() may be deprecated in the near future. '
WARNING:root:paddle.fluid.layers.py_reader() may be deprecated in the near future. Please use paddle.fluid.io.DataLoader.from_generator() instead.
Traceback (most recent call last):
  File "./src/run.py", line 453, in <module>
    main(args)
  File "./src/run.py", line 258, in main
    pyreader_name='train_reader', config=config)
  File "./src/run.py", line 125, in create_model
    use_double_buffer=True)
  File "C:\ProgramData\Anaconda3\envs\tl\lib\site-packages\paddle\fluid\layers\io.py", line 729, in py_reader
    use_double_buffer=use_double_buffer)
  File "C:\ProgramData\Anaconda3\envs\tl\lib\site-packages\paddle\fluid\layers\io.py", line 453, in _py_reader
    'ranks': ranks
  File "C:\ProgramData\Anaconda3\envs\tl\lib\site-packages\paddle\fluid\framework.py", line 3167, in append_op
    kwargs.get("stop_gradient", False))
  File "C:\ProgramData\Anaconda3\envs\tl\lib\site-packages\paddle\fluid\dygraph\tracer.py", line 45, in trace_op
    not stop_gradient)
ValueError: (InvalidArgument) Python object is not type of class std::shared_ptr<class paddle::imperative::VarBase> (at ..\paddle\fluid\pybind\imperative.cc:79)
```

**Comment by dotrywhile-wm** [comment]
请问您解决了吗

**Comment by DabeyHolmes** [comment]
> 请问您解决了吗

我没解决，不知道楼主解决了没

**Comment by 15283829383** [comment]
我也出现了同样的问题，请问有人解决了吗

**Comment by 15283829383** [comment]
> 您好，我们已经收到了您的问题，会安排技术人员尽快解答您的问题，请耐心等待。请您再次检查是否提供了清晰的问题描述、复现代码、环境&版本、报错信息等。同时，您也可以通过查看[官网API文档](https://www.paddlepaddle.org.cn/documentation/docs/zh/api_cn/index_cn.html)、[常见问题](https://www.paddlepaddle.org.cn/documentation/docs/zh/faq/index_cn.html)、[历史Issue](https://github.com/PaddlePaddle/Paddle/issues)、[AI社区](https://ai.baidu.com/forum/topic/list/168)来寻求解答。祝您生活愉快～
> 
> Hi! We've received your issue and please be patient to get responded. We will arrange technicians to answer your questions as soon as possible. Please make sure that you have posted enough message to demo your request. You may also check out the [API](https://www.paddlepaddle.org.cn/documentation/docs/zh/api_cn/index_cn.html)，[FAQ](https://www.paddlepaddle.org.cn/documentation/docs/zh/faq/index_cn.html)，[Github Issue](https://github.com/PaddlePaddle/Paddle/issues) and [AI community](https://ai.baidu.com/forum/topic/list/168) to get the answer.Have a nice day!

请问这个问题解决了吗
