### ISSUE TITLE
关于社区论坛最近常被广告脚本攻击

### ISSUE THREAD

**Issue by jingsongliujing** [PaddlePaddle/Paddle#29398]
建议进行广告过滤，给我们社区开发者更好的体验

**Comment by luotao1** [comment]
您好，感谢您的反馈，请问是 AI社区：https://ai.baidu.com/forum/topic/list/168 么？

> 常被广告脚本攻击

请问有具体示例可以看下么？

**Comment by jingsongliujing** [comment]
是的，具体是昨天和前天，具体请看链接图片[https://bbq.leceshi.cn/one.jpg](https://bbq.leceshi.cn/one.jpg)
[https://bbq.leceshi.cn/two.jpg](https://bbq.leceshi.cn/two.jpg)

**Comment by luotao1** [comment]
收到，周一帮您反馈社区管理人员，非常感谢！！
