### ISSUE TITLE
动态图 dataloader 图片文件名报错

### ISSUE THREAD

**Issue by merlinarer** [PaddlePaddle/Paddle#29399]
想用dataloader在load一个batch图片的时候同时把这些图片的文件名读进去
重写了__getitem__
![image](https://user-images.githubusercontent.com/71754029/101270488-803c2b80-37b4-11eb-89c7-e41801d2529f.png)
但是报错了
![image](https://user-images.githubusercontent.com/71754029/101270459-410dda80-37b4-11eb-9b01-1bf52e8d22f1.png)
是不是还需要改那个地方？

**Comment by heavengate** [comment]
DataLoader现在还不支持string数据类型，需要输入数据都是可以转化为numpy array的，string数据类型我们会尽快支持，目前的版本还不支持图片文件名
