### ISSUE TITLE
关于paddleseg的问题

### ISSUE THREAD

**Issue by lyn1225** [PaddlePaddle/Paddle#29396]
在ai studio上使用paddleseg库训练语义分割模型。数据集是Cityscapes。我每次分配到的是32G的V100，所以batch_size只能设置为4。官方提供的PSPNet代码，使用resnet_v2_pspnet模型，batch_size=4, bn，经过epoch=80轮训练后，在val 上测试的mlou 是70.66。自已提了一个简单的新模型，相同的实验条件下，val上测试的mlou是73.07，如果使用gn，大概可以在高0.6mlou。但是因为GPU显存的限制，无法扩大batch_size来测试所提模型的性能。实验室条件资源有限，所以想问下是否可以分配更大显存的GPU以供使用？如果后续会发论文的话，也会注明所用的语言为paddle，平台为ai studio。

**Comment by luotao1** [comment]
> 所以想问下是否可以分配更大显存的GPU以供使用

您好，ai studio上最大就是V100-32G的卡了，如果您的显存不够，建议您可以用多卡训练。
可参考文档：https://aistudio.baidu.com/aistudio/projectdetail/913043 其中[PaddleDetection：PCB瑕疵检测(支持多卡训练)](https://aistudio.baidu.com/aistudio/clusterprojectdetail/1029223) 有使用8卡训练的例子。ai studio上最大可以用到8卡。
