### ISSUE TITLE
文档中有言语漏洞需要修复

### ISSUE THREAD

**Issue by jhcgt4869** [PaddlePaddle/Paddle#29402]
地址：https://www.paddlepaddle.org.cn/documentation/docs/zh/2.0-rc/guides/01_paddle2.0_introduction/basic_concept/broadcasting_cn.html
位置：

![无标题](https://user-images.githubusercontent.com/61859193/101272622-d31fde00-37c8-11eb-8d4c-7488062a97ad.jpg)
情况：划线地方“的y来匹配多了”

然后：
![image](https://user-images.githubusercontent.com/61859193/101272758-365e4000-37ca-11eb-8ed7-80f133d237ff.png)
paddel2.0不是没有：paddle.disable_static()嘛

![image](https://user-images.githubusercontent.com/61859193/101273104-9c989200-37cd-11eb-9afb-ec3616b1417e.png)
这个qinzu前缀不是取消了吗？

**Comment by jhcgt4869** [comment]
![image](https://user-images.githubusercontent.com/61859193/101274213-184b0c80-37d7-11eb-958a-f65ce61e4acb.png)
API里面都没有：elementwise了

![image](https://user-images.githubusercontent.com/61859193/101274219-2b5ddc80-37d7-11eb-8bf1-72182d09812f.png)
这个要怎么处理？？？

**Comment by gongweibao** [comment]
1. 多了一个来
2. disable_static是有的
3. elementwise在paddle.fluid.layers下。

**Comment by jhcgt4869** [comment]
![](https://ai-studio-static-online.cdn.bcebos.com/04aae0d5b1cc473abf85beaeb3759378162fd42f5f464c82977a3f0d60a3edaf)




那既然知道elementwise在paddle.fluid.layers下，为什么文档li里面不注释修改呢？？？
还是报错的，这文档就真的这么水，不能够仔细看的？？？
文档里面最基础的东西都跑不出来，都是报错，怎么样让新手参加，怎么样让其他外行人信服，怎么样超过国际深度学习框架，就算我们这一批paddle爱好者，在paddle环境中不断努力，积极的营造paddle生态，一个文档做不好，大楼做不好，名片做不好，又有谁会真的相信这是一个好的产品呢？？？看到了aistudio里面积极向上的ppde们，有名的坑，寂寞等，几乎每天有新的文章，帮帮团的小伙伴们不断答疑解惑，但是很多时候却很无奈，GT老哥“水群无数”为了生态努力先前，于航现在为了把paddle推向大众视野用CSDN不断向前，而我们一个文档都漏洞白出，这里是我们paddle的门面，这个都弄不好，一个范例都是bug，这么多人这么多宣传那不是付之东流？？？
我这段时间就看了Tensor和一个广播，发现了至少4处问题，有API未更换的，有源码错误的，有文字漏洞的……
大家都辛苦为了一个更好的社区为了国产开源的深度学习框架大家都在努力奋斗，你们是第一线，还希望你们能够辛苦一下！！！

**Comment by gongweibao** [comment]
感谢您的工匠精神，我们已经安排人修改了。同时我们也会安排去请教一下`看到了aistudio里面积极向上的ppde们，有名的坑，寂寞等，`等同学的意见，让更多的人参与到paddle的精益求精的过程中来。
再次感谢！

**Comment by jhcgt4869** [comment]
也感谢你们的辛苦付出，刚刚态度有点急躁，请见谅，你们是这一块最辛苦的！感谢！
