### ISSUE TITLE
在华为鲲鹏处理器上编译错误

### ISSUE THREAD

**Issue by xcgworker** [PaddlePaddle/Paddle#29401]
试了一下在华为鲲鹏处理器上编译，报错：
<img width="792" alt="image" src="https://user-images.githubusercontent.com/55661104/101271935-8afdbd00-37c2-11eb-9a44-1be64d68103b.png">

cmake -DWITH_GPU=OFF -DWITH_TESTING=OFF -DWITH_AVX=OFF -DON_INFER=ON  -DPY_VERSION=3.7 ..

操作系统是debian10.

**Comment by jiweibo** [comment]
cmake的时候加上-DWITH_XBYAK=OFF -DWITH_ARM=ON
