### ISSUE TITLE
GPU训练报错：RuntimeError: parallel_for failed: invalid configuration argument

### ISSUE THREAD

**Issue by sxzhou1937** [PaddlePaddle/Paddle#29403]
环境：py3.7
cuda 10.0
paddle：paddlepaddle-gpu 1.8.5
[看过这个链接未找到答案](https://github.com/PaddlePaddle/Paddle/issues/26322)

我这里报错显示为：
![image](https://user-images.githubusercontent.com/19250976/101275043-9f02e800-37dd-11eb-8242-c21fe57a9711.png)
![image](https://user-images.githubusercontent.com/19250976/101275049-a4603280-37dd-11eb-9a36-914b047d1553.png)

代码部分：
![image](https://user-images.githubusercontent.com/19250976/101275058-c0fc6a80-37dd-11eb-911b-5c5a90ad3baa.png)

其中，CPU可以完成训练，但是效率十分低效；GPU就会报以上错误，请路过的大佬看一下问题所在！感谢~~

主要参考自深度学习NLP入门的课程里的项目，但是数据集换成了我自己的。网络改动部分是添加了一个卷积，和dropout，但是这个不会造成影响吧，不然CPU也不能训练了。

**Comment by gongweibao** [comment]
你是用的哪个样例？链接发出来。

**Comment by sxzhou1937** [comment]
> 你是用的哪个样例？链接发出来。

您好，是按照这个写的https://aistudio.baidu.com/aistudio/projectdetail/1302631
