### ISSUE TITLE
分布式训练数据并行问题

### ISSUE THREAD

**Issue by KingCSer** [PaddlePaddle/Paddle#29400]
版本：paddlepaddle-1.8.5
问题：多机多卡分布式训练中是做的数据并行吗？数据并行具体的实现在哪一部分？

**Comment by gongweibao** [comment]
默认是数据并行。哪一部分是指什么？

**Comment by KingCSer** [comment]
就是数据并行的代码实现是在paddle中哪个文件里？------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;gongweibao&quot;<notifications@github.com&gt;
发送时间:&nbsp;2020年12月6日(星期天) 晚上9:47
收件人:&nbsp;&quot;PaddlePaddle/Paddle&quot;<Paddle@noreply.github.com&gt;;
抄送:&nbsp;&quot;yangkangkangkang&quot;<3182164906@qq.com&gt;;&quot;Author&quot;<author@noreply.github.com&gt;;
主题:&nbsp;Re: [PaddlePaddle/Paddle] 分布式训练数据并行问题 (#29400)
