### ISSUE TITLE
请问DetectionMAP如何使用？一张图片中多个识别目标可否使用这个API计算map？

### ISSUE THREAD

**Issue by liuxi1007** [PaddlePaddle/Paddle#29415]
- 版本、环境信息：
    1）PaddlePaddle版本：paddle 2.0-rc
- 训练信息
    1）单机，单卡
    2）显存信息10GB
- 代码：
```
`class paddle.fluid.metrics.DetectionMAP(input, gt_label, gt_box, gt_difficult=None, class_num=None, background_label=0, overlap_threshold=0.5, evaluate_difficult=True, ap_version='integral')[源代码]
```
请问DetectionMAP如何使用？一张图片中多个识别目标可否使用这个API计算map？

**Comment by jerrywgz** [comment]
https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/fluid/metrics.py#L805 可以参考这里的说明，一张图片中如果有多个物体的话也是可以使用的

**Comment by liuxi1007** [comment]
> https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/fluid/metrics.py#L805 可以参考这里的说明，一张图片中如果有多个物体的话也是可以使用的

您好，请问DetectionMAP可以在动态图的情况下使用吗？gt_label, gt_box需要设置lod_level的值为1，静态图中是在定义接口的时候设置的，而动态图好像不支持这个属性，默认lod_level值为0。请问在动态图下DetectionMAP要如何使用？
```
InvalidArgumentError: Only support LodTensor of lod_level with 1 in label, but received 0.
  [Hint: Expected label_lod.size() == 1UL, but received label_lod.size():0 != 1UL:1.] (at /paddle/paddle/fluid/operators/detection_map_op.h:85)
  [operator < detection_map > error]
```

**Comment by jerrywgz** [comment]
嗯这个api动态图暂时还不支持，我们目前正在PaddleDetection这个repo中集成SSD模型，当中会适配动态图版本的detectionmap

**Comment by liuxi1007** [comment]
> 嗯这个api动态图暂时还不支持，我们目前正在PaddleDetection这个repo中集成SSD模型，当中会适配动态图版本的detectionmap

谢谢。
