### ISSUE TITLE
在MPI集群上训练模型在哪里查看AUC结果

### ISSUE THREAD

**Issue by youan1** [PaddlePaddle/Paddle#2943]
RT，有几个问题，请paddle同学帮忙解答：

1） 在哪里查看每个pass接受后的测试数据集上的AUC结果
2） MPI有多个节点，每个节点都有一份完整的模型，是每个节点每个 pass都会把整个测试数据集拿过来使用本机模型计算一遍AUC么
3）如果是这样，每个pass的AUC以哪个节点的数值为准呢

谢谢！

**Comment by Superjom** [comment]
如果训练数据是重复 shuffle过的，那随便一个节点上的数据都可以认为是总体数据上的一个随机抽样。

任意节点上的AUC也可以认为可以代表总体数据上的AUC。

前提是，训练数据是随机shuffle过的。

**Comment by youan1** [comment]
多谢

那么还是两个问题 1)在哪里看AUC的结果， 2）随机抽样的比例是多少

**Comment by Superjom** [comment]
AUC需要在模型里配置，参考 https://github.com/PaddlePaddle/models/blob/develop/text_classification/train.py#L122

抽样比例看自己的数据了，结论是，shuffle过的数据，单个节点上模型的AUC可以看做是总数据的AUC。

**Comment by youan1** [comment]
@Superjom 抽样比例需要配置的么，还是 paddle已经固定了的

**Comment by Superjom** [comment]
> 那随便一个节点上的数据都可以 **认为** 是总体数据上的一个随机抽样。

“认为” 不是真抽样

**Comment by youan1** [comment]
好的，多谢
另外看了上面的代码实例：
感觉AUC应该是在下面这段代码里打印的
            if test_reader is not None:
                result = trainer.test(reader=test_reader, feeding=feeding)
                logger.info("Test at Pass %d, %s \n" % (event.pass_id,
                                                        result.metrics))
对么

2）这部分日志会打印到哪里去，去哪里查看

**Comment by helinwang** [comment]
@youan1 您好，是在那里打印的，具体在`result.metrics`中。会被打印到stderr

logger创建代码：https://github.com/PaddlePaddle/models/blob/develop/text_classification/utils.py#L8
要是想打印到stdout可以参考：https://stackoverflow.com/questions/14058453/making-python-loggers-output-all-messages-to-stdout-in-addition-to-log/14058475

相关代码：
https://github.com/PaddlePaddle/Paddle/blob/c45195746bbe57e7c3a6d8b46666fa11a6dfdf20/paddle/gserver/evaluators/Evaluator.cpp#L492
https://github.com/PaddlePaddle/Paddle/blob/1faf5e0313d6a9d30d3c22ea84e0d008b13924f1/python/paddle/v2/event.py#L29
