### ISSUE TITLE
用DataFeeder 读lod 数据会报错

### ISSUE THREAD

**Issue by xcwei** [PaddlePaddle/Paddle#29439]
![image](https://user-images.githubusercontent.com/7373579/101334851-5d447100-38b3-11eb-8f49-eac837e443b6.png)

如图，使用DataFeeder读lod数据报错，代码如下
![image](https://user-images.githubusercontent.com/7373579/101334951-7f3df380-38b3-11eb-9f79-ce5552edcd72.png)
![image](https://user-images.githubusercontent.com/7373579/101335024-9846a480-38b3-11eb-83b0-fa677a0b7a8f.png)

与这个issue问题基本一样
https://github.com/PaddlePaddle/Paddle/issues/29439

**Comment by guoshengCS** [comment]
如果是LoDTensor的话，产生的data可以试下使用list

**Comment by xcwei** [comment]
> 如果是LoDTensor的话，产生的data可以试下使用list

没太明白，是说把什么转成list

**Comment by guoshengCS** [comment]
比如原来rand_x和rand_xs都是使用`fluid.create_lod_tensor`创建的LoDTensor，直接使用list或numpy array即可，不用再使用`fluid.create_lod_tensor`
