### ISSUE TITLE
Core dumped when use  FusedEmbeddingSeqPoolKernel

### ISSUE THREAD

**Issue by cerlee** [PaddlePaddle/Paddle#29444]
为使您的问题得到快速解决，在建立Issue前，请您先通过如下方式搜索是否有相似问题:【搜索issue关键字】【使用labels筛选】【官方文档】

如果您没有查询到相似问题，为快速解决您的提问，建立issue时请提供如下细节信息：
- 标题：Core dumped when use  FusedEmbeddingSeqPoolKernel
- 版本、环境信息：
    1）PaddlePaddle版本：请提供您的PaddlePaddle版本号（如1.1）或CommitID
    2）CPU：with mkl lib
    4）系统环境：CentOS release 4.3 (Final)  
2.6.32_1-19-0-0 #2 SMP Wed Aug 31 20:43:21 CST 2016 x86_64 x86_64 x86_64 GNU/Linux
-预测信息
- 复现信息：如为报错，请给出复现环境、复现步骤
- 问题描述：

![image2020-12-7_15-31-15](https://user-images.githubusercontent.com/3771823/101343896-a26ea000-38bf-11eb-9097-b443c53e893d.png)

**Comment by guoshengCS** [comment]
是否可以先不使用fused_embedding_seq_pool呢，这个是在contrib下面可能不是特别完备

**Comment by cerlee** [comment]
@guoshengCS 目前看绕不开，输入为空得时候core的，这个能修复下吗？

**Comment by guoshengCS** [comment]
使用普通的embedding层加sequence_pool也有这个问题吗，可否将空的数据过滤下呢

**Comment by cerlee** [comment]
目前处理是空数据做了过滤，不过这个问题希望你们也周知哈
