### ISSUE TITLE
链接了libpaddlue_fluid.dylib的python库不能和paddle一同使用

### ISSUE THREAD

**Issue by xcgworker** [PaddlePaddle/Paddle#29452]
我自已封装了一个python库，链接了libpaddlue_fluid.dylib。单独import 这个python库和paddle库 没有问题，但是同时import 时就有问题了：

>>> import paddle
WARNING: Do not have avx core. You may not build with AVX, but AVX is supported on local machine.
 You could build paddle WITH_AVX=ON to get better performance.
The original error is: No module named 'paddle.fluid.core_avx'
>>> import pysym
ERROR: something wrong with flag 'devices' in file '/Users/elaine/lab/contrib/Paddle/paddle/fluid/inference/io.cc'.  One possibility: file '/Users/elaine/lab/contrib/Paddle/paddle/fluid/inference/io.cc' is being linked both statically and dynamically into this executable.

**Comment by wanghaoshuang** [comment]
>我自已封装了一个python库，链接了libpaddlue_fluid.dylib

您这里是静态链接吧？给成动态链接试试？

**Comment by xcgworker** [comment]
<img width="1275" alt="image" src="https://user-images.githubusercontent.com/55661104/101434507-9c230700-3945-11eb-8f7c-de071bb93e99.png">
我用的mac的xcode编译的,链接的是动态库，应该不是静态链接吧。 paddle是按标准的cmake + make,
