### ISSUE TITLE
Momentum 优化器的动量因子设置问题

### ISSUE THREAD

**Issue by DrRyanHuang** [PaddlePaddle/Paddle#29450]
文档中的更新公式是这个：
![](https://latex.codecogs.com/svg.latex?velocity%20=%20mu%20\times%20velocity%20+%20gradient)
![](https://latex.codecogs.com/svg.latex?param%20=%20param%20-%20lr%20\times%20velocity)

抛开正负号不说，也就是实际上的动量因子是 `lr*mu` , lr == 0.001, mu==0.9，两者相乘这也太太太太太太太太太太太太太太太太太太太太小了吧
一般动量因子是0.5-09，请问老铁，API的momentum和文档的`nu` 是一个东西吗

**Comment by guoshengCS** [comment]
> API的momentum和文档的nu 是一个东西吗

是的，API的momentum和文档中的`mu`是同一个。
