### ISSUE TITLE
数据并行的代码实现部分在哪里

### ISSUE THREAD

**Issue by KingCSer** [PaddlePaddle/Paddle#29454]
版本: paddlepaddle-1.8.5
在多机多卡分布式训练中（自定义集群），数据并行的代码是在哪里实现的？以及all gather部分的代码是在哪里实现的？

**Comment by sandyhouse** [comment]
1.8.5版本下，数据并行的主入口可以参见python/paddle/fluid/incubate/fleet/collective/__init__.py文件中的CollectiveOptimizer类。
all_gather实现代码参见：paddle/fluid/operators/collective/c_allgather_op.[h,cc,cu.cc]文件。

**Comment by KingCSer** [comment]
好的，谢谢！
