### ISSUE TITLE
paddle2.0rc版本支持多输出吗？

### ISSUE THREAD

**Issue by qq345481843** [PaddlePaddle/Paddle#29453]
我在前向传播forward()中return一个list<tensor>可是当list中的tensor有多个时就会报错。

错误信息：
D:\Developer\Anaconda\envs\paddle2.0\lib\site-packages\paddle\nn\layer\norm.py:637: UserWarning: When training, we now always track global mean and variance.
  "When training, we now always track global mean and variance.")
Traceback (most recent call last):
  File "D:/Developer/Workplace/Python/project/maritime-situation-awareness-paddle/tools/trainer.py", line 19, in <module>
    model.fit(train_dataset, batch_size=1, epochs=10)
  File "D:\Developer\Anaconda\envs\paddle2.0\lib\site-packages\paddle\hapi\model.py", line 1469, in fit
    logs = self._run_one_epoch(train_loader, cbks, 'train')
  File "D:\Developer\Anaconda\envs\paddle2.0\lib\site-packages\paddle\hapi\model.py", line 1839, in _run_one_epoch
    data[len(self._inputs):])
  File "D:\Developer\Anaconda\envs\paddle2.0\lib\site-packages\paddle\hapi\model.py", line 937, in train_batch
    loss = self._adapter.train_batch(inputs, labels)
  File "D:\Developer\Anaconda\envs\paddle2.0\lib\site-packages\paddle\hapi\model.py", line 654, in train_batch
    losses = self.model._loss(*(to_list(outputs) + labels))
  File "D:\Developer\Anaconda\envs\paddle2.0\lib\site-packages\paddle\fluid\dygraph\layers.py", line 829, in __call__
    outputs = self.forward(*inputs, **kwargs)
TypeError: forward() takes 3 positional arguments but 5 were given
W1208 08:49:29.838227 11360 device_context.cc:338] Please NOTE: device: 0, CUDA Capability: 61, Driver API Version: 10.2, Runtime API Version: 10.2
W1208 08:49:29.838227 11360 device_context.cc:346] device: 0, cuDNN Version: 7.6.

Process finished with exit code 1

具体模型代码：
class MSAHead(paddle.nn.Layer):
    def __init__(self):
        super(MSAHead, self).__init__()
        # 装载配置文件
        self.config = Config

        # 用于语义分割
        self.conv1 = BnReluConv2d(in_channels=4*256, out_channels=self.config.stuff_class_num+1, kernel_size=3, padding=1)

        # 方案二 沿用语义分割的思路，直接输入预测
        self.conv2 = BnReluConv2d(in_channels=4*256, out_channels=self.config.object_class_num+1, kernel_size=3, padding=1)
        self.conv3 = BnReluConv2d(in_channels=4*256, out_channels=4, kernel_size=3, padding=1)

    def forward(self, inputs):
        # inputs: 接受FPN输出的四层特征图 [P2, P3, P4, P5]
        preds = paddle.concat(inputs, axis=1)
        w, h = preds.shape[2], preds.shape[3]

        # 语义分割分支
        # 背景类别分类
        cls_preds = self.conv1(preds)
        cls_preds = F.upsample(cls_preds, [w*4, h*4])

        # 目标检测分支
        # 方案二
        # 目标类别分类
        det_cls_preds = self.conv2(preds)
        det_box_preds = self.conv3(preds)

        return [cls_preds, det_cls_preds, det_box_preds]

**Comment by wanghaoshuang** [comment]
Paddle2.0RC的动态图API支持多输出。

>File "D:\Developer\Anaconda\envs\paddle2.0\lib\site-packages\paddle\hapi\model.py", line 654, in train_batch
losses = self.model._loss(*(to_list(outputs) + labels))
File "D:\Developer\Anaconda\envs\paddle2.0\lib\site-packages\paddle\fluid\dygraph\layers.py", line 829, in call
outputs = self.forward(*inputs, **kwargs)
TypeError: forward() takes 3 positional arguments but 5 were given

从以上报错信息看，是您给`loss` layer的输入太多了。

您MSAHead中forward的输出会送给您注册的loss layer，如果参数列表不匹配的话会报这个错。

**Comment by qq345481843** [comment]
感谢答复，问题已经解决了。的确是我loss参数传入没写好。
