### ISSUE TITLE
参数是否一致

### ISSUE THREAD

**Issue by KingCSer** [PaddlePaddle/Paddle#29487]
版本：paddlepaddle-1.8.5
问题：分布式多机多卡训练（自定义集群）中每个node最终保存的参数是否完全相同？以及在训练过程中每个epoch结束后保存的参数是否也完全相同？

**Comment by wanghaoshuang** [comment]
>每个node最终保存的参数是否完全相同？以及在训练过程中每个epoch结束后保存的参数是否也完全相同？

在parameter server模式下，是相同的
