### ISSUE TITLE
【PaddleClas】HRNet_W18_C 动态图和静态图模型在开启mkldnn C++预测报错，直接使用cpu可以正常预测

### ISSUE THREAD

**Issue by JiaXiao243** [PaddlePaddle/Paddle#29506]
CPU: Intel(R) Xeon(R) Gold 5117 CPU 

动态图模型地址：http://10.255.103.42:8990/infer_dygraph/HRNet_W18_C/
静态图模型地址：http://10.255.103.42:8990/infer_static/HRNet_W18_C/

报错信息：
![image](https://user-images.githubusercontent.com/37854899/101570935-5bdd8a80-3a12-11eb-8a99-0f2d6dbb72ec.png)

**Comment by OliverLPH** [comment]
@lidanqing-intel 
Hi, we met two problems when using mkldnn prediction, please help see this issue.

model download links


1. HRNet_W18_C model
Both dygraph model and static graph model has this issue.

> CPU: Intel(R) Xeon(R) Gold 5117 CPU
> 
> 动态图模型地址：http://10.255.103.42:8990/infer_dygraph/HRNet_W18_C/
> 静态图模型地址：http://10.255.103.42:8990/infer_static/HRNet_W18_C/
> 
> 报错信息：
> ![image](https://user-images.githubusercontent.com/37854899/101570935-5bdd8a80-3a12-11eb-8a99-0f2d6dbb72ec.png)

**Comment by OliverLPH** [comment]
@lidanqing-intel
Hi, we met two problems when using mkldnn prediction, please help see this issue.

model download link：
```shell
Link:https://dubox.com/s/1mqJKDpl7A0lQendtIJHjHg 
Password:4duq
```

reproduce code：
```shell
https://github.com/PaddlePaddle/PaddleClas/blob/dygraph/deploy/cpp_infer/readme_en.md
```

1. HRNet_W18_C model
Both dygraph model and static graph model has this issue. Error message is shown below

> CPU: Intel(R) Xeon(R) Gold 5117 CPU
> 
> 报错信息：
> ![image](https://user-images.githubusercontent.com/37854899/101570935-5bdd8a80-3a12-11eb-8a99-0f2d6dbb72ec.png)

However, I can run both HRNet_W18_C models on `Intel(R) Xeon(R) CPU E5-2650 v4 @ 2.20GHz CPU`. In this scenario, we thought this error may because of `Intel(R) Xeon(R) Gold 5117 CPU`?


**System information**
-PaddlePaddle version: develop
-CPU: Intel(R) Xeon(R) Gold 5117 CPU @ 2.00GHz, mkldnn enabled
-GPU: T4, CUDA10, CUDNN7.5, compile with GPU, but run cpu inference
-OS Platform: Ubuntu1604
-Dockerfile: Paddle/tools/manylinux1/Dockerfile.cuda10_cudnn7_gcc48_ubuntu16
-Python version: 3.7
-Cmake orders
-C++version.txt
-API information

**Inference config**
https://github.com/PaddlePaddle/PaddleClas/blob/dygraph/deploy/cpp_infer/src/cls.cpp#L22
```cpp
void Classifier::LoadModel(const std::string &model_path,
                           const std::string &params_path) {
  paddle_infer::Config config;
  config.SetModel(model_path, params_path);

  if (this->use_gpu_) {
    config.EnableUseGpu(this->gpu_mem_, this->gpu_id_);
  } else {
    config.DisableGpu();
    if (this->use_mkldnn_) {
      config.EnableMKLDNN();
      // cache 10 different shapes for mkldnn to avoid memory leak
      config.SetMkldnnCacheCapacity(10);
    }
    config.SetCpuMathLibraryNumThreads(this->cpu_math_library_num_threads_);
  }

  config.SwitchUseFeedFetchOps(false);
  // true for multiple input
  config.SwitchSpecifyInputNames(true);

  config.SwitchIrOptim(true);

  config.EnableMemoryOptim();
  config.DisableGlogInfo();
  this->predictor_ = CreatePredictor(config);
}
```

**Comment by OliverLPH** [comment]
2. SE_ResNeXt50_vd_32x4d static graph model
This model can also be downloaded from previous comment. And reproduce codes are same too.

And this issue can be reproduce either on `E5-2650` and `5117`.
```shell
I1209 04:53:05.006502  6835 analysis_predictor.cc:547] ======= optimize end =======
I1209 04:53:05.006641  6835 naive_executor.cc:105] ---  skip [feed], feed -> image
I1209 04:53:05.008369  6835 naive_executor.cc:105] ---  skip [save_infer_model/scale_0.tmp_0], fetch -> fetch
I1209 04:53:05.008447  6835 clas_benchmark.cc:38] batch_size: 1	,channels: 3	,height: 224	,width: 224
terminate called after throwing an instance of 'paddle::platform::EnforceNotMet'
  what():  In user code:

    File "tools/export_model.py", line 86, in <module>
      main()
    File "tools/export_model.py", line 68, in main
      out = create_model(args, model, image, class_dim=args.class_dim)
    File "tools/export_model.py", line 49, in create_model
      out = model.net(input=input, class_dim=class_dim)
    File "/paddle/PaddleClas/ppcls/modeling/architectures/se_resnext_vd.py", line 147, in net
      name=str(n) + '_' + str(i + 1))
    File "/paddle/PaddleClas/ppcls/modeling/architectures/se_resnext_vd.py", line 198, in bottleneck_block
      name='conv' + name + '_x1')
    File "/paddle/PaddleClas/ppcls/modeling/architectures/se_resnext_vd.py", line 243, in conv_bn_layer
      param_attr=ParamAttr(name=name + '_weights'), )
    File "/usr/local/lib/python3.7/site-packages/paddle/fluid/layers/nn.py", line 1597, in conv2d
      "data_format": data_format,
    File "/usr/local/lib/python3.7/site-packages/paddle/fluid/layer_helper.py", line 43, in append_op
      return self.main_program.current_block().append_op(*args, **kwargs)
    File "/usr/local/lib/python3.7/site-packages/paddle/fluid/framework.py", line 2917, in append_op
      attrs=kwargs.get("attrs", None))
    File "/usr/local/lib/python3.7/site-packages/paddle/fluid/framework.py", line 2014, in __init__
      for frame in traceback.extract_stack():

    InvalidArgumentError: The Input Variable(Input) of (conv2d) Operator used to determine kernel data type is empty or not LoDTensor or SelectedRows or LoDTensorArray.
      [Hint: Expected data_type != dafault_data_type, but received data_type:-1 == dafault_data_type:-1.] (at /paddle/paddle/fluid/framework/operator.cc:1479)
      [Hint: If you need C++ stacktraces for debugging, please set `FLAGS_call_stack_level=2`.]
      [operator < conv2d > error]
```

**Comment by lidanqing-vv** [comment]
Both 1 and 2 can be reproduced in i9 machine

**Comment by lidanqing-vv** [comment]
@luotao1 @OliverLPH 
```
/home/li/repo/Paddle/paddle/fluid/pybind/op_function_impl.h:82:41: warning: missing terminating " character
     imperative::NameVarBaseMap outs = {{"Out};
                                         ^
/home/li/repo/Paddle/paddle/fluid/pybind/op_function_impl.h:82:5: error: missing terminating " character
     imperative::NameVarBaseMap outs = {{"Out};
     ^
/home/li/repo/Paddle/paddle/fluid/pybind/op_function_impl.h:86:17: warning: missing terminating " character
     return outs["Out
                 ^
/home/li/repo/Paddle/paddle/fluid/pybind/op_function_impl.h:86:5: error: missing terminating " character
     return outs["Out
     ^
In file included from /home/li/repo/Paddle/paddle/fluid/pybind/op_function.h:154:0,
                 from /home/li/repo/Paddle/paddle/fluid/pybind/imperative.cc:43:
/home/li/repo/Paddle/paddle/fluid/pybind/op_function_impl.h:114:41: warning: missing terminating " character
     imperative::NameVarBaseMap outs = {{"OutputBox};
                                         ^
/home/li/repo/Paddle/paddle/fluid/pybind/op_function_impl.h:114:5: error: missing terminating " character
     imperative::NameVarBaseMap outs = {{"OutputBox};
     ^
/home/li/repo/Paddle/paddle/fluid/pybind/op_function_impl.h:120:17: warning: missing terminating " character
     return outs["OutputBox
                 ^
/home/li/repo/Paddle/paddle/fluid/pybind/op_function_impl.h:120:5: error: missing terminating " character
     return outs["OutputBox
     ^
/home/li/repo/Paddle/paddle/fluid/pybind/op_function_impl.h:132:41: warning: missing terminating " character
     imperative::NameVarBaseMap outs = {{"Out};
                                         ^
/home/li/repo/Paddle/paddle/fluid/pybind/op_function_impl.h:132:5: error: missing terminating " character
     imperative::NameVarBaseMap outs = {{"Out};
     ^
/home/li/repo/Paddle/paddle/fluid/pybind/op_function_impl.h:136:17: warning: missing terminating " character
     return outs["Out
                 ^
/home/li/repo/Paddle/paddle/fluid/pybind/op_function_impl.h:136:5: error: missing terminating " character
     return outs["Out
     ^
/home/li/repo/Paddle/paddle/fluid/pybind/op_function_impl.h:210:41: warning: missing terminating " character
     imperative::NameVarBaseMap outs = {{"Output};
```
按照PaddleClas repo的Readme.md操作后，发现`FLAGS_call_stack_level=2 sh tools/run.sh` 不显示backtrace。
后来我们想进入源码调试，于是我们开启`-DCMAKE_BUILD_TYPE=Debug`，但是make -j 12 报错，如上。
应该是Debug开启时，这个临时文件op_function_impl.h的生成有错误，上一个release还没有这个问题。
麻烦你们看一下吧，之前只是training时开启debug有问题，现在inference开启debug也出问题了。我们组现在每个人都有任务，实在没有时间。而且上一个release还没有这个问题，你们应该有有经验的同事了解这块的。谢谢了！

**Comment by luotao1** [comment]
> /home/li/repo/Paddle/paddle/fluid/pybind/op_function_impl.h:82:5: error: missing terminating " character
     imperative::NameVarBaseMap outs = {{"Out};

@lidanqing-intel Which branch do you use? Our develop branch does not have `op_function_impl.h` in https://github.com/PaddlePaddle/Paddle/tree/develop/paddle/fluid/pybind

**Comment by lidanqing-vv** [comment]
`op_function_impl.h` is a generated file when you do `make -j 12`. It is not in the code. 

Reproduction steps:
```
cmake .. -DWITH_GPU=OFF -DWITH_DISTRIBUTE=OFF -DWITH_MKLDNN=ON -DCMAKE_BUILD_TYPE=Debug -DON_INFER=ON  
make -j 12
```

**Comment by OliverLPH** [comment]
@lidanqing-intel 
enable `FLAGS_call_stack_level=2` has no effect issue is Inference internal bugs, @jiweibo will fix inference `gflags` related bugs in the future.
could you try `ulimit -c unlimited` and use core file to debug as an alternative method

**Comment by OliverLPH** [comment]
@lidanqing-intel 
C++ backtrace can be shown after https://github.com/PaddlePaddle/Paddle/pull/29798

**Comment by wojtuss** [comment]
The issue is caused by reusing wrong primitives from mkldnn cache after the `mkldnn_inplace_pass` is executed.
A PR with a fix is submitted: https://github.com/PaddlePaddle/Paddle/pull/30404.

**Comment by OliverLPH** [comment]
@wojtuss 
Could this PR https://github.com/PaddlePaddle/Paddle/pull/30404 fix both HRNet_W18_C and SE_ResNeXt50_vd_32x4d issues?

**Comment by wojtuss** [comment]
> @wojtuss
> Could this PR #30404 fix both HRNet_W18_C and SE_ResNeXt50_vd_32x4d issues?

Yes, both models work fine.

**Comment by OliverLPH** [comment]
@wojtuss 
many thanks, we will verify it soon

**Comment by OliverLPH** [comment]
@wojtuss 
Hi, we have tested https://github.com/PaddlePaddle/Paddle/pull/30404, but we still encounter `SE_ResNeXt50_vd_32x4d` crash issue  with `hub.baidubce.com/paddlepaddle/paddle:latest-gpu-cuda10.0-cudnn7-dev` docker images. 
If we use `paddlepaddle/paddle:latest-dev-cuda10.1-cudnn7-gcc82` image, `SE_ResNeXt50_vd_32x4d` model can infer without problem.
could you help investigate this environment bugs？

**Comment by T8T9** [comment]
> @wojtuss
> Hi, we have tested #30404, but we still encounter `SE_ResNeXt50_vd_32x4d` crash issue with `hub.baidubce.com/paddlepaddle/paddle:latest-gpu-cuda10.0-cudnn7-dev` docker images.
> If we use `paddlepaddle/paddle:latest-dev-cuda10.1-cudnn7-gcc82` image, `SE_ResNeXt50_vd_32x4d` model can infer without problem.
> could you help investigate this environment bugs？

Hi, @wojtuss, we did some debug on this bug for different environments:

**Environments**:
- env0：centos 7， gcc 4.8.5
- env1：ubuntu-16.04，gcc 4.8.5
- env2：ubuntu-18.04 gcc 7.5.0
- env3:  hub.baidubce.com/paddlepaddle/paddle:latest-gpu-cuda10.0-cudnn7-dev

**Conclusion**:
|Build Env|  Run Env| Build Status | Run Status |
|-|-|-|-|
|env0| env0 | :heavy_check_mark: | :heavy_check_mark: | 
|env1|env1|:heavy_check_mark:|:x: ([ERROR: InvalidArgumentError](#issuecomment-741535526))|
|env3|env3|:heavy_check_mark:|:x: ([ERROR: InvalidArgumentError](#issuecomment-741535526))|
|env2| env2 | :heavy_check_mark: | :heavy_check_mark: | 
|env1|env2|:heavy_check_mark:|:heavy_check_mark:|
|env2|env1|:heavy_check_mark:|:x: (ERROR: ABI-incompatible with libstdc++.so and libm.so )|

**Conjecture**:
1. There is something wrong with [mkldnn source code](https://github.com/oneapi-src/oneDNN).
Or
1. There is something wrong with gcc 4.8.5 on ubuntu 16.04 (env1), which is rarely.

Plz re-debug this bug. Thanks.

**Comment by wojtuss** [comment]
I have reproduced the error on Ubuntu 16.04. The models contain long sequences of elementwise_add and relu operators. The sequences are too long for the mkldnn_inplace_pass to handle them properly. We will try to fix the pass, but for now we recommend turning the pass off. @jczaja has submitted a suitable PR for that: https://github.com/PaddlePaddle/Paddle/pull/30588.

**Comment by luotao1** [comment]
@wojtuss @jczaja Please cherry-pick #30588 to release/2.0, @JiaXiao243 test it solves the `SE_ResNeXt50_vd_32x4d` crash.

**Comment by wojtuss** [comment]
@luotao1 , done: https://github.com/PaddlePaddle/Paddle/pull/30710
