### ISSUE TITLE
 AttributeError: module 'cv2' has no attribute 'INTER_LINEAR'

### ISSUE THREAD

**Issue by wanghaisheng** [PaddlePaddle/Paddle#29507]
https://github.com/PaddlePaddle/PaddleOCR/issues/1321#

PPOCRLabel下opencv冲突问题 PaddleOCR开发人员建议在此询问
macos 10.15.7 (19H15)
conda管理python环境

尝试conda下新建3.6和3.8的环境 执行下面步骤 也还是类似的问题
(py3.6) wenke@wenkedeMac-mini PPOCRLabel % pip3 uninstall opencv-python
WARNING: Skipping opencv-python as it is not installed.
(py3.6) wenke@wenkedeMac-mini PPOCRLabel % pip3 install opencv-contrib-python-headless
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Requirement already satisfied: opencv-contrib-python-headless in /opt/anaconda3/envs/py3.6/lib/python3.6/site-packages (4.4.0.46)
Requirement already satisfied: numpy>=1.13.3 in /opt/anaconda3/envs/py3.6/lib/python3.6/site-packages (from opencv-contrib-python-headless) (1.19.2)
(py3.6) wenke@wenkedeMac-mini PPOCRLabel % python3 PPOCRLabel.py       
Traceback (most recent call last):
  File "PPOCRLabel.py", line 34, in <module>
    from paddleocr import PaddleOCR
  File "/opt/anaconda3/envs/py3.6/lib/python3.6/site-packages/paddleocr/__init__.py", line 16, in <module>
    from .paddleocr import PaddleOCR
  File "/opt/anaconda3/envs/py3.6/lib/python3.6/site-packages/paddleocr/paddleocr.py", line 28, in <module>
    from tools.infer import predict_system
  File "../tools/infer/predict_system.py", line 21, in <module>
    import tools.infer.utility as utility
  File "../tools/infer/utility.py", line 17, in <module>
    from ppocr.utils.utility import initial_logger
  File "../ppocr/utils/utility.py", line 19, in <module>
    import paddle
  File "/opt/anaconda3/envs/py3.6/lib/python3.6/site-packages/paddle/__init__.py", line 275, in <module>
    import paddle.vision
  File "/opt/anaconda3/envs/py3.6/lib/python3.6/site-packages/paddle/vision/__init__.py", line 18, in <module>
    from . import transforms
  File "/opt/anaconda3/envs/py3.6/lib/python3.6/site-packages/paddle/vision/transforms/__init__.py", line 15, in <module>
    from . import transforms
  File "/opt/anaconda3/envs/py3.6/lib/python3.6/site-packages/paddle/vision/transforms/transforms.py", line 29, in <module>
    from . import functional as F
  File "/opt/anaconda3/envs/py3.6/lib/python3.6/site-packages/paddle/vision/transforms/functional.py", line 84, in <module>
    def resize(img, size, interpolation=cv2.INTER_LINEAR):
AttributeError: module 'cv2' has no attribute 'INTER_LINEAR'

···
(py3.8) wenke@wenkedeMac-mini PPOCRLabel % python3 PPOCRLabel.py
PPOCRLabel.py:1096: SyntaxWarning: "is" with a literal. Did you mean "=="?
if trans_dic["label"] is "" and mode == 'Auto':
PPOCRLabel.py:1898: SyntaxWarning: "is not" with a literal. Did you mean "!="?
if result[0][0] is not '':
PPOCRLabel.py:2090: SyntaxWarning: "is" with a literal. Did you mean "=="?
assert output is 0, "operate the cmd have some problems ,please check whether there is a in the lib "
Traceback (most recent call last):
File "PPOCRLabel.py", line 34, in
from paddleocr import PaddleOCR
File "../paddleocr.py", line 28, in
from tools.infer import predict_system
File "../tools/infer/predict_system.py", line 26, in
import tools.infer.predict_det as predict_det
File "../tools/infer/predict_det.py", line 35, in
from ppocr.data.det.db_process import DBProcessTest
File "../ppocr/data/det/db_process.py", line 23, in
from .data_augment import AugmentData
File "../ppocr/data/det/data_augment.py", line 13, in
import imgaug
File "/opt/anaconda3/envs/py3.8/lib/python3.8/site-packages/imgaug/init.py", line 7, in
from imgaug.imgaug import * # pylint: disable=redefined-builtin
File "/opt/anaconda3/envs/py3.8/lib/python3.8/site-packages/imgaug/imgaug.py", line 53, in
cv2.INTER_NEAREST, cv2.INTER_LINEAR, cv2.INTER_AREA, cv2.INTER_CUBIC]
AttributeError: module 'cv2' has no attribute 'INTER_NEAREST'
···

**Comment by swtkiwi** [comment]
大概是Opencv版本问题，请手动安装低版本的Opencv试试 pip install opencv-python==4.2.0.32

**Comment by wanghaisheng** [comment]
@swtkiwi 
```
python3 PPOCRLabel.py    
objc[54322]: Class QMacAutoReleasePoolTracker is implemented in both /opt/anaconda3/envs/py3.6/lib/python3.6/site-packages/cv2/.dylibs/QtCore (0x10fab9700) and /opt/anaconda3/envs/py3.6/lib/python3.6/site-packages/PyQt5/Qt/lib/QtCore.framework/Versions/5/QtCore (0x13d5e3198). One of the two will be used. Which one is undefined.
objc[54322]: Class QT_ROOT_LEVEL_POOL__THESE_OBJECTS_WILL_BE_RELEASED_WHEN_QAPP_GOES_OUT_OF_SCOPE is implemented in both /opt/anaconda3/envs/py3.6/lib/python3.6/site-packages/cv2/.dylibs/QtCore (0x10fab9778) and /opt/anaconda3/envs/py3.6/lib/python3.6/site-packages/PyQt5/Qt/lib/QtCore.framework/Versions/5/QtCore (0x13d5e3210). One of the two will be used. Which one is undefined.
objc[54322]: Class KeyValueObserver is implemented in both /opt/anaconda3/envs/py3.6/lib/python3.6/site-packages/cv2/.dylibs/QtCore (0x10fab97a0) and /opt/anaconda3/envs/py3.6/lib/python3.6/site-packages/PyQt5/Qt/lib/QtCore.framework/Versions/5/QtCore (0x13d5e3238). One of the two will be used. Which one is undefined.
objc[54322]: Class RunLoopModeTracker is implemented in both /opt/anaconda3/envs/py3.6/lib/python3.6/site-packages/cv2/.dylibs/QtCore (0x10fab97f0) and /opt/anaconda3/envs/py3.6/lib/python3.6/site-packages/PyQt5/Qt/lib/QtCore.framework/Versions/5/QtCore (0x13d5e3288). One of the two will be used. Which one is undefined.
Namespace(cls=True, cls_batch_num=30, cls_image_shape='3, 48, 192', cls_model_dir='/Users/wenke/.paddleocr/cls', cls_thresh=0.9, det=True, det_algorithm='DB', det_db_box_thresh=0.5, det_db_thresh=0.3, det_db_unclip_ratio=2.0, det_east_cover_thresh=0.1, det_east_nms_thresh=0.2, det_east_score_thresh=0.8, det_max_side_len=960, det_model_dir='/Users/wenke/.paddleocr/det', enable_mkldnn=False, gpu_mem=8000, image_dir=None, ir_optim=True, label_list=['0', '180'], lang='ch', max_text_length=25, rec=True, rec_algorithm='CRNN', rec_batch_num=30, rec_char_dict_path='./ppocr/utils/ppocr_keys_v1.txt', rec_char_type='ch', rec_image_shape='3, 32, 320', rec_model_dir='/Users/wenke/.paddleocr/rec/ch', use_angle_cls=True, use_gpu=False, use_pdserving=False, use_space_char=True, use_tensorrt=False, use_zero_copy_run=False)
dt_boxes num : 1, elapse : 0.0309751033782959
cls num  : 1, elapse : 0.012377262115478516
rec_res num  : 1, elapse : 0.04668402671813965
zsh: segmentation fault  python3 PPOCRLabel.py

```

**Comment by Evezerest** [comment]
需要先卸载目前的opencv，然后安装headless版本https://github.com/Evezerest/PaddleOCR/tree/dy3/PPOCRLabel#macos

**Comment by Evezerest** [comment]
尝试一下 `pip install opencv-contrib-python-headless==4.2.0.32`，我这边用4.4的headless也是ok的

**Comment by Evezerest** [comment]
补充一下：需要先将环境中opencv的相关包都删除干净，再安装headless

**Comment by wanghaisheng** [comment]
@Evezerest 你说的环境里是说我这个conda下面的py3.6  咋就算清理干净了

**Comment by chaosjeyli** [comment]
遇到了一模一样的问题，想问下楼主解决了吗~

**Comment by Evezerest** [comment]
先pip list看一下环境中opencv的库有哪些，然后删除非headless的opencv
