### ISSUE TITLE
Hard to read code in Tensor

### ISSUE THREAD

**Issue by wangkuiyi** [PaddlePaddle/Paddle#2951]
What doesn't this following line in `Tensor::mutable_data` mean?

```cpp
 return reinterpret_cast<T*>(reinterpret_cast<uintptr_t>(holder_->ptr()) + offset_); 
```

Why not just use `static_cast<T*>`?

**Comment by Canpio** [comment]
A `PlaceHolder` may be shared by more than one tensor. So `offset_` here is used to indicate the byte offset between `PlaceHolder::ptr_` and where tensor's data really begins.

**Comment by Canpio** [comment]
A PlaceHolder may be shared by more than one tensor. So offset_ here is used to indicate the byte offset between PlaceHolder::ptr_ and where tensor's data really begins.
However, `void*` is not allowed to do addition in standard C++, so we have to cast it into `uintptr_t`, which means a pointer's address.  And `uintptr_t` is not able to be cast into  `T*` by `static_cast<T*>`.

**Comment by wangkuiyi** [comment]
http://en.cppreference.com/w/cpp/language/reinterpret_cast  reinterpret_cast doesn't compile into any CPU instructions.
