### ISSUE TITLE
预计什么时候支持 ML Compute？

### ISSUE THREAD

**Issue by T-baby** [PaddlePaddle/Paddle#29510]
2.0 有计划支持 苹果的 ML Compute吗？tensorflow 2.4 已经支持了。

**Comment by Superjomn** [comment]
你好，2.0 应该没有支持这个。
看了下， ML Compute 相关资料还比较欠缺，我们会持续关注这个哈

**Comment by linkerlin** [comment]
> 你好，2.0 应该没有支持这个。
> 看了下， ML Compute 相关资料还比较欠缺，我们会持续关注这个哈

国内大量的开发人员用是MacOS，所以对MLCompute对支持是一个机器学习框架对胜负手。
