### ISSUE TITLE
Code style of tensor_types.h

### ISSUE THREAD

**Issue by wangkuiyi** [PaddlePaddle/Paddle#2952]
1. `struct TType` ==> `struct Eigen`
1. Remove `Flat`, which is identical to `Vec`.
1. Rename `Vec` to complete word `Vector`.
1. Rename file `tensor_types.h` to `eigen.h`.

**Comment by wangkuiyi** [comment]
What is "unsupported/Eigen/CXX11/Tensor"?

**Comment by wangkuiyi** [comment]
tensor_types.h doesn't have unit tests.  There are obvious bugs like in the definition of TTypes::Vec, there is a template parameter `NDIMS=1`.

**Comment by QiJune** [comment]
@wangkuiyi The current developement version of Eigen (post-3.2) supports Tensors. This support is experimental and a moving target.
TensorFlow is also using Eigen Tensor and Tensor provides united codes for both CPU and GPU.

And the template parameter ```NDIMS=1``` is not used for TTypes::Vec.

**Comment by QiJune** [comment]
The Flat method will do reshape operation. If you have a four dimension Tensor, ```t.flat<float>()``` will return a one dimension Eigen TensorMap.
And Vec method is just transfer one dimension Tensor to one dimension Eigen TensorMap.
