### ISSUE TITLE
安装paddlepaddleGPU版本出错

### ISSUE THREAD

**Issue by tutouyubeiyi** [PaddlePaddle/Paddle#29524]
前面的流程都很顺畅，结果在检验的时候报错cudnn64_7.dll not found。下载方式如下
![image](https://user-images.githubusercontent.com/55478640/101631734-c9fc6e80-3a5f-11eb-997e-c77382e05346.png)

**cuda和cudaa配置如下**

![image](https://user-images.githubusercontent.com/55478640/101631833-f87a4980-3a5f-11eb-8b93-6b889405bffe.png)

**报错如下：**

![image](https://user-images.githubusercontent.com/55478640/101631862-0334de80-3a60-11eb-9197-624d96b63281.png)

**Comment by zhwesky2010** [comment]
@zhangxiang123168 您好，请问CUDA10.0和cudnn7.6.5+是否装好了，需要在Nvidia官网下载cudnn并拷贝到相应文件夹里

**Comment by tutouyubeiyi** [comment]
> @zhangxiang123168 您好，请问CUDA10.0和cudnn7.6.5+是否装好了，需要在Nvidia官网下载cudnn并拷贝到相应文件夹里

感谢您的回复，CUDA和cudnn都安装好了，但是拷贝到文件夹的操作似乎没做搞，请问需要装到哪个文件夹呢
