### ISSUE TITLE
[API] `nn.Layer.train`接口动静一致性问题

### ISSUE THREAD

**Issue by Meiyim** [PaddlePaddle/Paddle#29534]
测试版本： paddle-develop
测试代码:
```
import paddle as p
p.enable_static()
l=p.nn.Linear(3,3)
l.train()
```
测试输出：
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/conda/envs/py36/lib/python3.6/site-packages/paddle/fluid/dygraph/layers.py", line 136, in train
    framework._dygraph_tracer().train_mode()
AttributeError: 'NoneType' object has no attribute 'train_mode'
```

预期结果：
正常返回，并且`l.training is True`

**Comment by chenwhql** [comment]
这个可以完善下，但静态图模式下Layer的train和eval没有实际意义，正常就是eval的，如果后面append backward的话才是train，所以在静态图下，这里`l.training is True`是可以，但可能没什么具体意义

**Comment by Meiyim** [comment]
我觉得我们API里`nn.Layers.eval`的概念和`paddle.no_grad`的概念耦合了。

按照pytorch的思路, eval/ train只是一个所有sublayers间能保持一致的flag, 用户根据这个flag改变自己forward的行为，例如。在`self.training =True`时执行dropout在 `self.trianing=False`时就跳过dropout，还有很多用户自定义策略都需要拿到这个flag。

而是否生成backward应该由`paddle.no_grad` / `paddle.enable_grad` 来控制。

另外说一点，如果在`nn.Layers.eval` 中改变全局状态`tracer.train_mode()`的话，代码中存在两个Layer，一个是train,一个是eval(蒸馏场景)。那到底这个全局状态是trian还是eval呢？

**Comment by chenwhql** [comment]
是的，您说的这个问题我们已经修复了，分离了这两者的概念，在后续发布版本中上线，https://github.com/PaddlePaddle/Paddle/pull/29064

**Comment by chenwhql** [comment]
静态图兼容的问题，我后面也修复一下

**Comment by Meiyim** [comment]
我看这个PR依旧是在`nn.Layers.train`里修改了全局的状态。

**Comment by chenwhql** [comment]
这个PR之后，全局的`_train_mode`只是一个flag，和执行时是否生成backward已经没关系了

**Comment by chenwhql** [comment]
修复PR已合入
