### ISSUE TITLE
Alpine Linux v3.10 pip安装错误

### ISSUE THREAD

**Issue by YueWang1996** [PaddlePaddle/Paddle#29530]
系统环境：
NAME="Alpine Linux"
ID=alpine
VERSION_ID=3.10.5
PRETTY_NAME="Alpine Linux v3.10"
HOME_URL="https://alpinelinux.org/"
BUG_REPORT_URL="https://bugs.alpinelinux.org/"

Python版本：python 3.7.7
Pip 版本：pip 19.2.3
安装方式：pip安装          

安装代码及出现的问题：
```
bash-5.0# python3 --version
Python 3.7.7
bash-5.0# python3 -m pip --version
pip 19.2.3 from /usr/lib/python3.7/site-packages/pip (python 3.7)
bash-5.0# python3 -c "import platform;print(platform.architecture()[0]);print(platform.machine())"
64bit
x86_64
bash-5.0# python3 -m pip install paddlepaddle -i https://mirror.baidu.com/pypi/simple
Looking in indexes: https://mirror.baidu.com/pypi/simple
Collecting paddlepaddle
  ERROR: Could not find a version that satisfies the requirement paddlepaddle (from versions: none)
ERROR: No matching distribution found for paddlepaddle
WARNING: You are using pip version 19.2.3, however version 20.3.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
bash-5.0# python3 -m pip install paddlepaddle -i https://pypi.tuna.tsinghua.edu.cn/simple
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Collecting paddlepaddle
  ERROR: Could not find a version that satisfies the requirement paddlepaddle (from versions: none)
ERROR: No matching distribution found for paddlepaddle
WARNING: You are using pip version 19.2.3, however version 20.3.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
bash-5.0# pip3 search paddlepaddle
paddlepaddle (1.8.5)                      - Parallel Distributed Deep Learning
paddlepaddle-tiny (1.6.1)                 - Parallel Distributed Deep Learning
paddlepaddle-gpu (1.8.5.post107)          - Parallel Distributed Deep Learning
paddle-tokenizer (0.1.0)                  - A tokenizer write in PaddlePaddle
paddle-ner (0.1.0)                        - A NER extractor write in PaddlePaddle
paddlex (1.2.8)                           - PaddlePaddle Entire Process Development Toolkit
paddlenlp (2.0.0a1)                       - PaddlePaddle NLP Model Core Library
plsc (0.1.1)                              - PaddlePaddle Large Scale Classfication Package.
ppgan (0.1.2)                             - Awesome GAN toolkits based on PaddlePaddle
paddle-fleet (0.1.1)                      - Distributed Training Package Based on PaddlePaddle
paddle2onnx (0.4)                         - a toolkit for converting trained model of PaddlePaddle to ONNX.
paddle-serving-client (0.3.2)             - Paddle Serving Package for saved model with PaddlePaddle
paddle-serving-server-gpu (0.3.2.post10)  - Paddle Serving Package for saved model with PaddlePaddle
paddle-serving-server (0.3.2)             - Paddle Serving Package for saved model with PaddlePaddle
paddle-serving-app (0.1.2)                - Paddle Serving Package for saved model with PaddlePaddle
paddle-fl (1.1.0)                         - Privacy-Preserving Deep Learning Package Based on PaddlePaddle.
x2paddle (0.8.9)                          - a toolkit for converting trained model to PaddlePaddle from other deep learning frameworks.
paddlehub (1.8.3)                         - A toolkit for managing pretrained models of PaddlePaddle and helping user getting started with
                                            transfer learning more efficiently.
paddleocr (1.1.1)                         - Awesome OCR toolkits based on PaddlePaddle &#65288;8.6M ultra-lightweight pre-trained model,
                                            support training and deployment among server, mobile, embeded and IoT devices
bash-5.0# pip3 install paddlepaddle 
Collecting paddlepaddle
  ERROR: Could not find a version that satisfies the requirement paddlepaddle (from versions: none)
ERROR: No matching distribution found for paddlepaddle
WARNING: You are using pip version 19.2.3, however version 20.3.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.

```
因为项目需要，必须要在Alpine Linux系统下进行安装，求解决办法，谢谢！

**Comment by YueWang1996** [comment]
> 系统环境：
> NAME="Alpine Linux"
> ID=alpine
> VERSION_ID=3.10.5
> PRETTY_NAME="Alpine Linux v3.10"
> HOME_URL="https://alpinelinux.org/"
> BUG_REPORT_URL="https://bugs.alpinelinux.org/"
> 
> Python版本：python 3.7.7
> Pip 版本：pip 19.2.3
> 安装方式：pip安装         
> 
> 安装代码及出现的问题：
> 
> ```
> bash-5.0# python3 --version
> Python 3.7.7
> bash-5.0# python3 -m pip --version
> pip 19.2.3 from /usr/lib/python3.7/site-packages/pip (python 3.7)
> bash-5.0# python3 -c "import platform;print(platform.architecture()[0]);print(platform.machine())"
> 64bit
> x86_64
> bash-5.0# python3 -m pip install paddlepaddle -i https://mirror.baidu.com/pypi/simple
> Looking in indexes: https://mirror.baidu.com/pypi/simple
> Collecting paddlepaddle
>   ERROR: Could not find a version that satisfies the requirement paddlepaddle (from versions: none)
> ERROR: No matching distribution found for paddlepaddle
> WARNING: You are using pip version 19.2.3, however version 20.3.1 is available.
> You should consider upgrading via the 'pip install --upgrade pip' command.
> bash-5.0# python3 -m pip install paddlepaddle -i https://pypi.tuna.tsinghua.edu.cn/simple
> Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
> Collecting paddlepaddle
>   ERROR: Could not find a version that satisfies the requirement paddlepaddle (from versions: none)
> ERROR: No matching distribution found for paddlepaddle
> WARNING: You are using pip version 19.2.3, however version 20.3.1 is available.
> You should consider upgrading via the 'pip install --upgrade pip' command.
> bash-5.0# pip3 search paddlepaddle
> paddlepaddle (1.8.5)                      - Parallel Distributed Deep Learning
> paddlepaddle-tiny (1.6.1)                 - Parallel Distributed Deep Learning
> paddlepaddle-gpu (1.8.5.post107)          - Parallel Distributed Deep Learning
> paddle-tokenizer (0.1.0)                  - A tokenizer write in PaddlePaddle
> paddle-ner (0.1.0)                        - A NER extractor write in PaddlePaddle
> paddlex (1.2.8)                           - PaddlePaddle Entire Process Development Toolkit
> paddlenlp (2.0.0a1)                       - PaddlePaddle NLP Model Core Library
> plsc (0.1.1)                              - PaddlePaddle Large Scale Classfication Package.
> ppgan (0.1.2)                             - Awesome GAN toolkits based on PaddlePaddle
> paddle-fleet (0.1.1)                      - Distributed Training Package Based on PaddlePaddle
> paddle2onnx (0.4)                         - a toolkit for converting trained model of PaddlePaddle to ONNX.
> paddle-serving-client (0.3.2)             - Paddle Serving Package for saved model with PaddlePaddle
> paddle-serving-server-gpu (0.3.2.post10)  - Paddle Serving Package for saved model with PaddlePaddle
> paddle-serving-server (0.3.2)             - Paddle Serving Package for saved model with PaddlePaddle
> paddle-serving-app (0.1.2)                - Paddle Serving Package for saved model with PaddlePaddle
> paddle-fl (1.1.0)                         - Privacy-Preserving Deep Learning Package Based on PaddlePaddle.
> x2paddle (0.8.9)                          - a toolkit for converting trained model to PaddlePaddle from other deep learning frameworks.
> paddlehub (1.8.3)                         - A toolkit for managing pretrained models of PaddlePaddle and helping user getting started with
>                                             transfer learning more efficiently.
> paddleocr (1.1.1)                         - Awesome OCR toolkits based on PaddlePaddle &#65288;8.6M ultra-lightweight pre-trained model,
>                                             support training and deployment among server, mobile, embeded and IoT devices
> bash-5.0# pip3 install paddlepaddle 
> Collecting paddlepaddle
>   ERROR: Could not find a version that satisfies the requirement paddlepaddle (from versions: none)
> ERROR: No matching distribution found for paddlepaddle
> WARNING: You are using pip version 19.2.3, however version 20.3.1 is available.
> You should consider upgrading via the 'pip install --upgrade pip' command.
> ```
> 
> 因为项目需要，必须要在Alpine Linux系统下进行安装，求解决办法，谢谢！

安装错误为：
  ERROR: Could not find a version that satisfies the requirement paddlepaddle (from versions: none)
ERROR: No matching distribution found for paddlepaddle

**Comment by swtkiwi** [comment]
建议升级下pip版本，到20.2.2+

**Comment by YueWang1996** [comment]
> 建议升级下pip版本，到20.2.2+

你好，谢谢回复。 已经尝试过升级pip至20.3.1，问题仍旧没有得到解决。
```
bash-5.0# pip install --upgrade pip
Requirement already satisfied: pip in /usr/lib/python3.7/site-packages (20.3.1)
bash-5.0# python3 -m pip install paddlepaddle-gpu==1.8.5.post107 -i https://mirror.baidu.com/pypi/simple
Looking in indexes: https://mirror.baidu.com/pypi/simple
ERROR: Could not find a version that satisfies the requirement paddlepaddle-gpu==1.8.5.post107
ERROR: No matching distribution found for paddlepaddle-gpu==1.8.5.post107
bash-5.0# python3 -m pip install paddlepaddle-gpu==1.8.5 -i https://pypi.tuna.tsinghua.edu.cn/simple
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
ERROR: Could not find a version that satisfies the requirement paddlepaddle-gpu==1.8.5
ERROR: No matching distribution found for paddlepaddle-gpu==1.8.5
```
目前正在尝试Ubuntu下的本机源码编译，希望能成功吧

**Comment by YueWang1996** [comment]
> > 建议升级下pip版本，到20.2.2+
> 
> 你好，谢谢回复。 已经尝试过升级pip至20.3.1，问题仍旧没有得到解决。
> 
> ```
> bash-5.0# pip install --upgrade pip
> Requirement already satisfied: pip in /usr/lib/python3.7/site-packages (20.3.1)
> bash-5.0# python3 -m pip install paddlepaddle-gpu==1.8.5.post107 -i https://mirror.baidu.com/pypi/simple
> Looking in indexes: https://mirror.baidu.com/pypi/simple
> ERROR: Could not find a version that satisfies the requirement paddlepaddle-gpu==1.8.5.post107
> ERROR: No matching distribution found for paddlepaddle-gpu==1.8.5.post107
> bash-5.0# python3 -m pip install paddlepaddle-gpu==1.8.5 -i https://pypi.tuna.tsinghua.edu.cn/simple
> Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
> ERROR: Could not find a version that satisfies the requirement paddlepaddle-gpu==1.8.5
> ERROR: No matching distribution found for paddlepaddle-gpu==1.8.5
> ```
> 
> 目前正在尝试Ubuntu下的本机源码编译，希望能成功吧

alpine musl编译安装链接：https://github.com/chen-zhiyu/Paddle/tree/develop/paddle/scripts/musl_build

**Comment by terwer** [comment]
貌似找到了一个解决方案，用 slim 版本，例如：
```
FROM python:3.9.20-slim-bookworm
```
