### ISSUE TITLE
出现未定义的引用错误

### ISSUE THREAD

**Issue by hpuyj** [PaddlePaddle/Paddle#29542]
安装C++版本是，出现以下错误。
安装的是ubuntu14.04_cuda10.0_cudnn7_avx_mkl
运行这个地址的：<a>https://www.paddlepaddle.org.cn/documentation/docs/zh/1.7/advanced_guide/inference_deployment/inference/native_infer.html</a>
是不是不兼容自己的系统。感觉没什么错误的呀。是不是只能ubuntu14.04可以安装，18.04不能用
-- Build files have been written to: /home/novasky/文档/paddlepaddle/sample/paddle-TRT/build
Scanning dependencies of target fluid_int8_test
[ 50%] Building CXX object CMakeFiles/fluid_int8_test.dir/fluid_int8_test.o
[100%] Linking CXX executable fluid_int8_test
CMakeFiles/fluid_int8_test.dir/fluid_int8_test.o：在函数‘paddle::PrepareTRTConfig(paddle::AnalysisConfig*, int)’中：
/home/novasky/文档/paddlepaddle/sample/paddle-TRT/fluid_int8_test.cc:32：对‘paddle::AnalysisConfig::SetModel(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)’未定义的引用
CMakeFiles/fluid_int8_test.dir/fluid_int8_test.o：在函数‘__static_initialization_and_destruction_0(int, int)’中：
/home/novasky/文档/paddlepaddle/sample/paddle-TRT/fluid_int8_test.cc:13：对‘google::FlagRegisterer::FlagRegisterer<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >(char const*, char const*, char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*)’未定义的引用
collect2: error: ld returned 1 exit status
CMakeFiles/fluid_int8_test.dir/build.make:103: recipe for target 'fluid_int8_test' failed
make[2]: *** [fluid_int8_test] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/fluid_int8_test.dir/all' failed
make[1]: *** [CMakeFiles/fluid_int8_test.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
run_impl.sh: 26: run_impl.sh: ./fluid_int8_test: not found

**Comment by seiriosPlus** [comment]
你好， 能提供一下Ubuntu 14.04 和Ubuntu 18.04 中的gcc版本吗？
