### ISSUE TITLE
在训练过程中打印的提示，怎么消除

### ISSUE THREAD

**Issue by Darki-luo** [PaddlePaddle/Paddle#29546]
paddle2.0 python=3.8在训练过程中打印的提示，怎么消除？
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/layers/utils.py:77: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
  return (isinstance(seq, collections.Sequence) and

**Comment by seiriosPlus** [comment]
收到，目前应该没有办法消除， 这个问题我们修复一下吧.
