### ISSUE TITLE
C++预测-每预测一次内存增加一次 CPU MKL

### ISSUE THREAD

**Issue by Fire-Star** [PaddlePaddle/Paddle#29558]
![image](https://user-images.githubusercontent.com/17548618/101793400-b7a63180-3b40-11eb-8572-e922486b6e9f.png)

![image](https://user-images.githubusercontent.com/17548618/101793558-e58b7600-3b40-11eb-8bd0-87e57125b63e.png)

**Comment by Superjomn** [comment]
麻烦增加下，paddle版本，使用的场景，机器环境的信息

另外，
这个可以提供一个可以复现这个问题的case吗？ 尽量跟具体的业务解耦
如果模型数据需要保密，可以给一个类似的模型，但问题能复现出来的，我们能复现就很容易定位了
