### ISSUE TITLE
softmax_with_cross_entropy softlabel

### ISSUE THREAD

**Issue by merlinarer** [PaddlePaddle/Paddle#29557]
调用softmax_with_cross_entropy计算loss的时候，soft_label=True，报错信息如下：
![image](https://user-images.githubusercontent.com/71754029/101780066-01871b80-3b31-11eb-893b-0a929fbbcc3b.png)
是因为数据类型出错，仔细检查之后发现，自定义的dataset类的__getitem__是返回的fp32没错，但是到softmax_with_cross_entropy的时候就变成了VarType.INT64，softlabel（nchw）维度上也是没有问题的，但是由于被转为了VarType.INT64，label都变成了0
![image](https://user-images.githubusercontent.com/71754029/101779871-c4228e00-3b30-11eb-9675-203aa1873270.png)
我仔细看了paddle的dataloader实现，没有找到是在哪改变了label的数据类型，求指点

**Comment by phlrain** [comment]
能否检查下，for batch in train_reader() 得到的batch里面的 数据类型
或者提供下DataLoader的使用方式
