### ISSUE TITLE
不能在notebook使用numba

### ISSUE THREAD

**Issue by FjjRichard** [PaddlePaddle/Paddle#29573]
from numba import jit

@jit(nopython=True)
def calc(img_temp, rows, cols, minval,maxval):
    for i in np.arange(rows):
        for j in np.arange(cols):
            #避免除以0的报错
            if maxval - minval == 0:
                result = 1
            else:
                result = maxval - minval
            img_temp[i, j] = int((img_temp[i, j] - minval) / result * 255)

运行后，不断转圈圈，没法使用，一样代码，在本地运行没有问题。请问在aistudio 的notebook使用numba是不是有特别要注意的地方？

**Comment by richarddddd198** [comment]
`from numba import jit
@jit(nopython=True)
def calc(img_temp, rows, cols, minval,maxval):
    for i in np.arange(rows):
        for j in np.arange(cols):
            #避免除以0的报错
            if maxval - minval == 0:
                result = 1
            else:
                result = maxval - minval
            img_temp[i, j] = int((img_temp[i, j] - minval) / result * 255)`

**Comment by shinichiye17** [comment]
您好，AI Studio相关的问题，烦请发邮件至aistudio@baidu.com，会有专业同学为您解答~
