### ISSUE TITLE
[hub.docker] Install Guild 死链

### ISSUE THREAD

**Issue by HorseJia** [PaddlePaddle/Paddle#2957]
https://hub.docker.com/r/paddledev/paddle/

Installation
Check out the Install Guide to install from
pre-built packages (docker image, deb package) or
directly build on Linux and Mac OS X from the source code.

其中『Install Guild』的链接 http://paddlepaddle.org/doc/build/ 是死链

**Comment by guoshengCS** [comment]
这个 https://hub.docker.com/r/paddledev/paddle/ 过期了，包含最新镜像的页面见这里 https://hub.docker.com/r/paddlepaddle/paddle/
