### ISSUE TITLE
paddle.to_tensor不能接受list[Tensor]或tuple[Tensor]类型的输入

### ISSUE THREAD

**Issue by chenwthu** [PaddlePaddle/Paddle#29584]
paddle版本：2.0.0rc0
`paddle.to_tensor`输入为list[Tensor]或tuple[Tensor]时会抛出ValueError，包括所有元素等长和只有一个元素的情况

**Comment by frankwhzhang** [comment]
有详细的代码和报错信息嘛

**Comment by chenwthu** [comment]
<img width="1230" alt="screenshot" src="https://user-images.githubusercontent.com/16147671/102069774-2f25da80-3e39-11eb-8cdc-1c6feca1fcb7.png">

在这个例子中希望得到`shape=[1,3]`的tensor

目前`paddle.to_tensor`支持输入为原生float列表、numpy数组、单个tensor等类型，但不支持输入tensor列表，希望能加入支持

**Comment by zhiqiu** [comment]
这种场景下，对单个tensor可以用reshape，对多个tensor的list可以用concat，这些API有更明确的行为是不是更合适一些？

**Comment by chenwthu** [comment]
我遇到的场景是有多种不同类型的输入，如果可以用同一个api处理就比较方便，例如`map(to_tensor, [ndarray, tensor])`
