### ISSUE TITLE
如何在同一个程序里面load两个paddlepaddle模型

### ISSUE THREAD

**Issue by Xsx93** [PaddlePaddle/Paddle#29585]
请问如何在同一个程序里面load两个模型，我在同一个程序中load 两个模型，一个用于人脸检测，一个用于人脸属性识别。能够运行但是人脸检测结果是错的，本来是一个，检测出很多个，大小位置也不正确

**Comment by frankwhzhang** [comment]
是使用的官方模型吗

**Comment by Xsx93** [comment]
不是官方模型，自己训练的
paddlepaddle-gpu==1.8.5-post107

`       place = fluid.CUDAPlace(0) if args.use_gpu else fluid.CPUPlace()
        exe_facedetect = fluid.Executor(place)
        place2 = fluid.CUDAPlace(0) if args.use_gpu else fluid.CPUPlace()
        exe_faceage = fluid.Executor(place2)
        [inference_program_facedetect, feed_target_names_facedetect,fetch_targets_facedetect] = fluid.io.load_inference_model(modelPath, exe_facedetect)
        [inference_program_faceage, feed_target_names_faceage,fetch_targets_faceage] = fluid.io.load_inference_model(model_path_faceage, exe_faceage)
`
请问这种load方式正确吗
