### ISSUE TITLE
paddle2.0 高层API vgg无法指定num_classes

### ISSUE THREAD

**Issue by lwbmowgli** [PaddlePaddle/Paddle#29592]
通过查看源代码

![image](https://user-images.githubusercontent.com/32731935/102067292-d7d23b00-3e35-11eb-823e-c68018e18f28.png)

如果调用paddle.vision.models.vgg11(pretrained=False, batch_norm=False, **kwargs)这个API，则num_classes参数写死为1000，无法对其赋值。建议将那句话注释掉。负责就需要用户自己来改源代码。

**Comment by yukavio** [comment]
在develop版本下这个问题已经解决了
https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/vision/models/vgg.py#L122
需要的话可以在：https://www.paddlepaddle.org.cn/documentation/docs/zh/1.8/install/Tables.html#whl-dev 下载安装最新的版本
