### ISSUE TITLE
请问在paddle 2.0-rc 动态图下实现网络中不同层设置的学习率不同。

### ISSUE THREAD

**Issue by liuxi1007** [PaddlePaddle/Paddle#29609]
- 版本、环境信息：
   1）PaddlePaddle版本：paddle 2.0-rc
- 训练信息
   1）单机，单卡
   2）显存信息10GB
- 问题
在paddle 2.0-rc 动态图下实现网络中不同层设置的学习率不同。如网络卷积层学习率为1e-5，全连接和分类层设为1e-2。

**Comment by jzhang533** [comment]
可以用两个optimizer来进行模型优化。

optimizer1里的parameters的列表和optimizer2里的parameters的列表分别设置为不同的网络层的参数。
示例如下：

```python
linear1 = paddle.nn.Linear(1024, 512)
linear2 = paddle.nn.Linear(512, 256)

conv = paddle.nn.Conv2D(128, 256, 3)

optimizer1 = paddle.optimizer.SGD(1e-5, linear1.parameters()+linear2.parameters())
optimizer2 = paddle.optimizer.SGD(1e-2, conv.parameters())
```

**Comment by Xreki** [comment]
可以使用`paddle.ParamAttr`设置，请参考https://github.com/PaddlePaddle/PaddleClas/blob/dc124ecb46f66b5d4ab42cbbd392fd1886c5fe3f/ppcls/modeling/architectures/resnet_vd.py#L58

**Comment by liuxi1007** [comment]
谢谢。

**Comment by zhijiejia** [comment]
> 可以用两个optimizer来进行模型优化。
> 
> optimizer1里的parameters的列表和optimizer2里的parameters的列表分别设置为不同的网络层的参数。
> 示例如下：
> 
> ```python
> linear1 = paddle.nn.Linear(1024, 512)
> linear2 = paddle.nn.Linear(512, 256)
> 
> conv = paddle.nn.Conv2D(128, 256, 3)
> 
> optimizer1 = paddle.optimizer.SGD(1e-5, linear1.parameters()+linear2.parameters())
> optimizer2 = paddle.optimizer.SGD(1e-2, conv.parameters())
> ```

我也是这样做的，同时每个optimizer 还有一个scheduler, 但是我发现有一个学习率不改变？
