### ISSUE TITLE
paddle iOS版，模拟器编译不过

### ISSUE THREAD

**Issue by pengpeng-wang** [PaddlePaddle/Paddle#29608]
iOS_demo下，编译ocr_demo项目，真机可以正常运行，模拟器会报错，能否给出一个合并【模拟器+真机】后的libpaddle_api_light_bundled.a文件，应该是差模拟器的.a导致的吧？

![860C74C15FC29D5B3734FFCAD20CDCB2](https://user-images.githubusercontent.com/17318811/102167751-fd108900-3ec9-11eb-8a28-3a1015e4a2ad.jpg)

**Comment by Xreki** [comment]
Paddle-Lite的问题，建议到https://github.com/PaddlePaddle/Paddle-Lite/issues 提issue。
