### ISSUE TITLE
4卡下做shuffle bn出现UnimplementedError

### ISSUE THREAD

**Issue by itisianlee** [PaddlePaddle/Paddle#29610]
为使您的问题得到快速解决，在建立Issues前，请您先通过如下方式搜索是否有相似问题:【搜索issue关键字】【使用labels筛选】【官方文档】
- 版本、环境信息：
  - paddle 2.0rc，GPU是tesla P4
  - CUDA 10.0, CUDNN v7.6
  - 系统：centos 6
  - python 3.7
- 训练信息
  - 4卡训练
- 问题描述
![image](https://user-images.githubusercontent.com/23066570/102169441-2d0d5b80-3ecd-11eb-9d57-6d1e833d64bd.png)
![image](https://user-images.githubusercontent.com/23066570/102169465-3b5b7780-3ecd-11eb-8c12-dba09324119a.png)

- 平常多卡训练在4张卡上的log是一致的，但是这次0号卡上的log不一样。以下是workerlog.0的输出
![image](https://user-images.githubusercontent.com/23066570/102169570-78c00500-3ecd-11eb-8636-4cd00cde09a5.png)

**Comment by Xreki** [comment]
请检查一下运行时的环境变量设置，需要设置`export CUDA_VISIBLE_DEVICES="0,1,2,3"`。

从你贴出的log来看，错误的原因应该是运行时没有找到GPU设备。如果不是环境变量的问题，可以发一下你启动的命令哈。

**Comment by itisianlee** [comment]
> 请检查一下运行时的环境变量设置，需要设置`export CUDA_VISIBLE_DEVICES="0,1,2,3"`。
> 
> 从你贴出的log来看，错误的原因应该是运行时没有找到GPU设备。如果不是环境变量的问题，可以发一下你启动的命令哈。

![image](https://user-images.githubusercontent.com/23066570/102177252-1c191600-3ede-11eb-92ad-c04d971c2694.png)

**Comment by Xreki** [comment]
`python -m paddle.distributed.launch --gpus=$CUDA_VISIBLE_DEVICES train.py`试试？

**Comment by Xreki** [comment]
用户进一步定位到，代码中使用了all_gather，再使用randperm就报错。怀疑可能是randperm的bug，不能生成其他卡上的数据，改成使用ones就可以在不同卡上生成不同cudaplace的数据。randperm默认使用CUDAPlace(0)，导致其他卡找不到类似CUDAPlace(1)。代码如下：
![image](https://user-images.githubusercontent.com/12538138/102293592-60f68880-3f82-11eb-9d82-37a5d0fb5c94.png)

是否randperm的问题，还在进一步确认中。
