### ISSUE TITLE
Paddle1.8/1.8.5 Building failed.

### ISSUE THREAD

**Issue by gootsing** [PaddlePaddle/Paddle#29619]
-OS: Ubuntu 18.04.5
-CPU: AMD RYZEN 3800XT
-GPU: AMD VEGA VII
-Paddle: Branch 1.8 or release_1.8.5
Configure as: cmake .. -DWITH_GPU=OFF -DWITH_AMD_GPU=ON -DPY_VERSION=3.6.0 -DWITH_NCCL=OFF -DCMAKE_MODULE_PATH=/opt/rocm/hip/cmake
Building command: make -j10
Error Message:
/home/guqin/Documents/Github/Paddle/paddle/fluid/pybind/op_function_impl.h: In function ‘std::shared_ptr<paddle::imperative::VarBase> paddle::pybind::imperative_pad_constant_like(const pybind11::handle&, const pybind11::handle&, const pybind11::args&)’:
/home/guqin/Documents/Github/Paddle/paddle/fluid/pybind/op_function_impl.h:6458:12: error: ‘CastPyHandleToVarBase’ was not declared in this scope
   auto X = CastPyHandleToVarBase("pad_constant_like", "X", 0, X_, false);
 
On 2.x, it builds OK. And the function "CastPyHandleToVarBase" could be found in paddle/fluid/pybind/op_function.h. But in 1.x, it's not there.

**Comment by Xreki** [comment]
Paddle does not support AMD GPU now. And the pull request in reviewing now. Please wait for it.

**Comment by gootsing** [comment]
Yes, but it has problems in building not only for ROCM, but also for CPU version, while 2.x does not have problems in building.

**Comment by Xreki** [comment]
Can you give your cmake command and Paddle's commit?

**Comment by gootsing** [comment]
Here it is:
commit 967c3fef093f94e4da754eed62462b8c9770ac0f (HEAD -> rel1.8, origin/release/1.8)
cmake .. -DPY_VERSION=3.6.0 -DWITH_AVX=OFF -DWITH_GPU=OFF
-- commit: 967c3fef09
-- branch: rel1.8
-- Configuring done
-- Generating done
-- Build files have been written to: /home/guqin/Documents/Github/Paddle/build_cpu
...
/home/guqin/Documents/Github/Paddle/paddle/fluid/pybind/op_function_impl.h: In function ‘std::tuple<std::shared_ptr<paddle::imperative::VarBase>, std::shared_ptr<paddle::imperative::VarBase> > paddle::pybind::imperative_target_assign(const pybind11::handle&, const pybind11::handle&, const pybind11::args&)’:
/home/guqin/Documents/Github/Paddle/paddle/fluid/pybind/op_function_impl.h:7587:12: error: ‘CastPyHandleToVarBase’ was not declared in this scope
   auto X = CastPyHandleToVarBase("target_assign", "X", 0, X_, false);
            ^~~~~~~~~~~~~~~~~~~~~
....

**Comment by Joejiong** [comment]
This `CastPyHandleToVarBase` function was added with  v2.0.0-rc1, not sure if this function should be cherry-pick to v1.8.
```
Print user-friendly error message in core.ops (#26261)

* print user-friendly error message

* adjust error sumary
 develop (#26261)  v2.0.0-rc1 
…
 v2.0.0-beta0
@zhiqiu
zhiqiu committed on 17 Aug 
```
