### ISSUE TITLE
notebooks/06.understand_sentiment/README.cn.ipynb 与 train.py不一致

### ISSUE THREAD

**Issue by HorseJia** [PaddlePaddle/Paddle#2963]
原文
『
## 应用模型
可以使用训练好的模型对电影评论进行分类，下面程序展示了如何使用`paddle.infer`接口进行推断。
```
out = convolution_net(dict_dim, class_dim=class_dim, is_predict=True)
 # out = stacked_lstm_net(dict_dim, class_dim=class_dim, stacked_num=3, is_predict=True)
```

而 train.py 中convolution_net、stacked_lstm_net方法并没有实现 is_predict 参数

**Comment by hedaoyuan** [comment]
> 可以使用训练好的模型对电影评论进行分类，下面程序展示了如何使用paddle.infer接口进行推断。

嗯，那个文档转换成ipython文件后是可以直接运行。文档的代码和`train.py`确实有点差别，train.py只实现了文档中的训练部分逻辑。

**Comment by gongweibao** [comment]
Feel free to reopen it!
