### ISSUE TITLE
ErrorClipByValue 算子问题

### ISSUE THREAD

**Issue by lizhiqings** [PaddlePaddle/Paddle#29664]
需求：希望对 tensor的值做 截断 大于1的 变成1 小于0的变成0
![image](https://user-images.githubusercontent.com/47736115/102214312-0b36c780-3f13-11eb-8b17-0d79faa1da41.png)

![image](https://user-images.githubusercontent.com/47736115/102214369-20135b00-3f13-11eb-8f89-8a266e6a72b3.png)

**Comment by Xreki** [comment]
你好，从你报错信息的堆栈看出，出错地方在于：
![image](https://user-images.githubusercontent.com/12538138/102297971-3f4dcf00-3f8b-11eb-9332-6fc98ac85b09.png)

fluid.clip.ErrorClipByValue是一个class，所以应该是你的用法不对。具体用法请参考文档：https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/fluid/clip/ErrorClipByValue_cn.html#errorclipbyvalue

**Comment by lizhiqings** [comment]
好的，我现在想对

发件人: Yiqun Liu <notifications@github.com>
答复: PaddlePaddle/Paddle <reply@reply.github.com>
日期: 2020年12月16日 星期三 上午10:42
收件人: PaddlePaddle/Paddle <Paddle@noreply.github.com>
抄送: "Li,Zhiqing" <lizhiqing@baidu.com>, Author <author@noreply.github.com>
主题: Re: [PaddlePaddle/Paddle] ErrorClipByValue 算子问题 (#29664)

你的

**Comment by lizhiqings** [comment]
好的 我现在想对output_dur1做截断 这个应该怎么写呢 那个例子好复杂写的，或者还有其他类似算子实现这种功能么
[cid:image001.png@01D6D399.5A1A5320]

发件人: Yiqun Liu <notifications@github.com>
答复: PaddlePaddle/Paddle <reply@reply.github.com>
日期: 2020年12月16日 星期三 上午10:42
收件人: PaddlePaddle/Paddle <Paddle@noreply.github.com>
抄送: "Li,Zhiqing" <lizhiqing@baidu.com>, Author <author@noreply.github.com>
主题: Re: [PaddlePaddle/Paddle] ErrorClipByValue 算子问题 (#29664)

你的

**Comment by Xreki** [comment]
嗯嗯，我刚刚又去查了下文档，`ErrorClipByValue`这类的接口，是用来统一对梯度做clip。如果你想对某个特定的tensor做clip，可以使用`fluid.layers.clip`，文档见：https://www.paddlepaddle.org.cn/documentation/docs/zh/api_cn/layers_cn/clip_cn.html#clip

**Comment by lizhiqings** [comment]
En. 好的 多谢

发件人: Yiqun Liu <notifications@github.com>
答复: PaddlePaddle/Paddle <reply@reply.github.com>
日期: 2020年12月16日 星期三 上午10:53
收件人: PaddlePaddle/Paddle <Paddle@noreply.github.com>
抄送: "Li,Zhiqing" <lizhiqing@baidu.com>, Author <author@noreply.github.com>
主题: Re: [PaddlePaddle/Paddle] ErrorClipByValue 算子问题 (#29664)

fluid.layers.clip
