### ISSUE TITLE
will PaddlePaddle support aarch64？ is this on a roadmap now？

### ISSUE THREAD

**Issue by hubblezzhu** [PaddlePaddle/Paddle#29661]
will PaddlePaddle support aarch64？ or is this on a roadmap now？
any help will be highly appreciated. thanks

**Comment by Xreki** [comment]
Paddle does not support any arm architecture now, and there is not a roadmap to support training with Paddle for it. But if you want to inference, you can use Paddle-Lite.

----

**Update** : inference using Paddle is already supported on aarch64.
