### ISSUE TITLE
Clone函数内部实现中无用的锁可以去掉

### ISSUE THREAD

**Issue by whocdb** [PaddlePaddle/Paddle#29699]
https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/fluid/inference/api/api_impl.cc
中的Clone函数中用到了锁，目的是为了防止多线程clone出现问题,然而当前的clone还是深clone(也许后面会使用浅Clone)，并不存在并发性问题，因此该lock可以先注释掉，否则Clone可能因为锁而导致等待。

**Comment by Superjomn** [comment]
你好，感谢反馈！

这个的确有道理，我们会排期修改下这块，之前应该是浅拷贝有一些问题。

比较倡导大家在启动多线程之前，先clone/create 好所有的predictor，这个方式会让多线程服务稳定很多。

对应clone这个我们会看下，会专门支持绝对的浅拷贝。
