### ISSUE TITLE
关于paddle.nn.Flatten() API页面无法打开的问题

### ISSUE THREAD

**Issue by jhcgt4869** [PaddlePaddle/Paddle#29696]
地址：[paddle.nn.Flatten()说明文档：https://www.paddlepaddle.org.cn/documentation/docs/zh/2.0-rc/api/paddle/fluid/dygraph/Flatten_cn.html](https://www.paddlepaddle.org.cn/documentation/docs/zh/2.0-rc/api/paddle/fluid/dygraph/Flatten_cn.html)
版本：2.0-rc
情况描述：改说明文档无法打开，直接会直接跳转[https://www.paddlepaddle.org.cn/documentation/docs/zh/2.0-rc/guides/index_cn.html](https://www.paddlepaddle.org.cn/documentation/docs/zh/2.0-rc/guides/index_cn.html)

**Comment by jhcgt4869** [comment]
paddle.metric.accuracy():[说明文档https://www.paddlepaddle.org.cn/documentation/docs/zh/2.0-rc/api/paddle/metric/metrics/accuracy_cn.html](https://www.paddlepaddle.org.cn/documentation/docs/zh/2.0-rc/api/paddle/metric/metrics/accuracy_cn.html)也无法打开，直接跳转到首页

**Comment by heavengate** [comment]
感谢反馈，已转需求跟进中~
