### ISSUE TITLE
paddle 2.0-rc计算map的问题

### ISSUE THREAD

**Issue by liuxi1007** [PaddlePaddle/Paddle#29693]
- 版本、环境信息：
1）PaddlePaddle版本：paddle 2.0-rc
- 训练信息
1）单机，单卡
2）显存信息10GB
- 问题
请问使用fluid.metrics.DetectionMAP API时，由于lod_level=1在paddle 2.0-rc动态图模式下不支持，所以无法使用。请问此API在paddle 2.0-rc静态图模式下可以使用吗？是否可以动态图和静态图模式混用，将静态图作为一个算子给动态图调用？请问具体实现方法是什么？

**Comment by heavengate** [comment]
动态图要使用的话可以参考下  https://github.com/PaddlePaddle/PaddleDetection/blob/d2dd8a53389ed85bee087ccaac16eaa0769fac79/ppdet/utils/map_utils.py#L57
