### ISSUE TITLE
cmake FindPythonLibs and FindPythonIterp get inconsistent python version

### ISSUE THREAD

**Issue by emailweixu** [PaddlePaddle/Paddle#297]
It seems that FindPythonInterp gets the version which used by user, while FindPythonLibs can get some other installled version. Should make FindPythonLibs find the one used by user. May need to write a new FindPythonLibs script.

**Comment by wangkuiyi** [comment]
I noticed that @zhangjinchao01 authored https://github.com/baidu/Paddle/blame/develop/cmake/FindPythonModule.cmake.  Is it a good idea to assign this issue to him?

**Comment by backyes** [comment]
Currently I am working on some compiling issues, @wangkuiyi I will take charge of this. @emailweixu Can guide me how to reproduce this issue?
