### ISSUE TITLE
When mkldnn is turned on, some dynamic graph models have worse prediction performance than static graph models

### ISSUE THREAD

**Issue by JiaXiao243** [PaddlePaddle/Paddle#29709]
1. Test Data
![image](https://user-images.githubusercontent.com/37854899/102359977-6be60300-3fec-11eb-9fa2-291b4e352c07.png)

2. Profile Data
![image](https://user-images.githubusercontent.com/37854899/102360002-730d1100-3fec-11eb-93d7-ca0f37ebab99.png)

3. reproduce code：
https://github.com/PaddlePaddle/PaddleClas/blob/dygraph/deploy/cpp_infer/readme_en.md

4. model download link：
 Link: https://dubox.com/s/11--AYtRlkOCwxQAAcPAc6w 
Password: ndv7
Intranet：http://10.255.103.42:8990/infer_static.tar
                  http://10.255.103.42:8990/infer_dygraph.tar

5. machine: Intel 6148

**Comment by luotao1** [comment]
- Res2Net50_26w_4s 和 DPN68 ，网络结构相同，但 conv2d 性能差异较大，是因为动态图得到的模型参数中包含更多的 denormal float value（异常值，如 8.04432e-21），即非常接近于0的值。cpu在计算包含这些denormal value时，性能相比 normal value 会下降 100x 倍。#29924  xiaowei 已修复
- VGG和AlexNet：2.0 的 matmul 和 1.8 的 mul 性能有差异。将matmul映射到mul后支持融合，可以起到一定加速。#29911 @juncaipeng 已修复

**Comment by luotao1** [comment]
复测结果 @JiaXiao243 
![图片](https://user-images.githubusercontent.com/6836917/103516534-b0f2ac00-4eab-11eb-991c-a57a6d98b64c.png)
