### ISSUE TITLE
[2.0 release] oneDNN related attributes need to add Op version compatibillity

### ISSUE THREAD

**Issue by lidanqing-vv** [PaddlePaddle/Paddle#29703]
Add op version compatibility to following ops
1）requantize
 The added attribute 'Shift_in' is not yet registered.
2）quantize
 The added attribute 'Shift' is not yet registered.
3）dequantize
 The added attribute 'Shift' is not yet registered.

**Comment by heavengate** [comment]
你好，麻烦给一下报错部分关键代码和版本信息、环境信息等，另外我们最近发布的2.0.0.rc1版本，可以试一下能否解决你的问题

**Comment by lidanqing-vv** [comment]
@heavengate  不好意思，这是提给Intel同事他们将实现的task。暂时不需要Baidu的同事帮助哈，谢谢
