### ISSUE TITLE
Use mkldnn to predict on windows, some models report errors.

### ISSUE THREAD

**Issue by JiaXiao243** [PaddlePaddle/Paddle#29710]
1. Turn on mkldnn and use ResNet50_vd, HRNet_W18_C, SE_ResNeXt50_vd_32x4d model to make C++ prediction, error message is shown bellow.
![image](https://user-images.githubusercontent.com/37854899/102361250-fc711300-3fed-11eb-96c9-2aededb8cf86.png)
When mkldnn is not turned on, all these models can  can be predicted normally.

2. ResNeSt50_fast_1s1x64d report an application error
![b36c43a2994af1f185d62fcb6b0d797d](https://user-images.githubusercontent.com/37854899/102439986-57405400-405a-11eb-8c41-33c2a217c308.jpg)

 3. reproduce code：
https://github.com/PaddlePaddle/PaddleClas/blob/dygraph/deploy/cpp_infer/readme_en.md

4. model download link：
Link:https://dubox.com/s/11--AYtRlkOCwxQAAcPAc6w
Password:ndv7

5. CPU:  Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz

**Comment by lidanqing-vv** [comment]
@JiaXiao243  不一定是系统的问题，可能是机型支持指令的问题。是什么机器，可以打印一下`lscpu`吗

**Comment by JiaXiao243** [comment]
![D10CC60CED2BE5A92102293E8FE563DD](https://user-images.githubusercontent.com/37854899/102437664-e1d28480-4055-11eb-8509-020cb9b3bc04.jpg)

@lidanqing-intel     Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz

**Comment by lidanqing-vv** [comment]
@luotao1  这个是不是可以在Linux上复现啊。不是windows only的问题把？

**Comment by luotao1** [comment]
是windows only的问题，linux上测过没有问题的。

**Comment by jiweibo** [comment]
> @luotao1 这个是不是可以在Linux上复现啊。不是windows only的问题把？

@lidanqing-intel 

我定位到是mkldnn_inplace_pass的问题，但是没找到解决的办法。
config.pass_builder()->DeletePass("mkldnn_inplace_pass"); 能够临时规避问题


出问题的原因，windows上发生了错误的复用逻辑。

![image](https://user-images.githubusercontent.com/26377421/103740569-6e0f1080-5032-11eb-9a7f-d11a150e7f19.png)

**Comment by jczaja** [comment]
@luotao1 , @JiaXiao243 , @juncaipeng  Could you please share graphs of executed model with mkldnn_inplace enabled from
Windows platform and from Linux platform ?

**Comment by jiweibo** [comment]
@jczaja 

The test model is SE_ResNeXt50_vd_32x4d.

config.SwitchIrDebug(true)  to get dot graph.

set environment variable GLOG_v=4 to record detailed log.

- Linux platform

[linux.log](https://github.com/PaddlePaddle/Paddle/files/5784944/linux.log)

The log is too long, you can view mkldnn_inplace releated logs from line 74840.

[82_ir_mkldnn_inplace_pass.dot.zip](https://github.com/PaddlePaddle/Paddle/files/5784946/82_ir_mkldnn_inplace_pass.dot.zip)


- Windows platform

[82_ir_mkldnn_inplace_pass.dot.zip](https://github.com/PaddlePaddle/Paddle/files/5785509/82_ir_mkldnn_inplace_pass.dot.zip)

[windows.log](https://github.com/PaddlePaddle/Paddle/files/5785523/windows.log)

It seems that there is some problem in outputting large log to file on windows, the log at the end is truncated

**Comment by luotao1** [comment]
Close this issue since we use #30681 to track the mkldnn_inplace_pass problem.
