### ISSUE TITLE
怎么获取序列的长度并且遍历序列中的每个元素呢？

### ISSUE THREAD

**Issue by JayEworld** [PaddlePaddle/Paddle#29722]
背景：有一变长序列，我想针对不同的序列长度做不同的处理。

我定义了一个变长的序列tensor：fluid.layers.data(name=i, shape=[1], dtype="int64", lod_level=1)
（1）怎么获取变长序列的长度呢？
（2）怎么实现遍历序列里的元素呢？
如果以上无法实现，我就想能不能通过在生成样本的时候把序列长度算出来存下来，请问存下来的这个数怎么传到网络结构的定义里呢？

求哪位大佬能帮忙解答下！

**Comment by hutuxian** [comment]
1. 可以使用size op
2. 得具体看遍历想做的操作
3. 也可以实现，再新建一个input传入这个数就行
