### ISSUE TITLE
linux系统安装gpu版本的paddle出现问题 

### ISSUE THREAD

**Issue by VVIZE-ops** [PaddlePaddle/Paddle#29737]
版本、环境信息
   1）PaddlePaddle版本：1.85
    2）GPU：GeForce GTX 1070，CUDA :  V9.1.85

    3）系统环境：18.04.1-Ubuntu, python 3.7

- 安装方式信息：
   1）pip

- 问题描述：安装成功后使用时报错:
- ExternalError:  Cuda error(30), unknown error.
  [Advise: This indicates that an unknown internal error has occurred. ] at (/paddle/paddle/fluid/platform/gpu_info.cc:65)

**Comment by hutuxian** [comment]
贴一下完整的安装命令？

**Comment by VVIZE-ops** [comment]
> 贴一下完整的安装命令？
安装命令是指的这个么
python -m pip install paddlepaddle-gpu==1.8.5.post97 -i https://mirror.baidu.com/pypi/simple

**Comment by hutuxian** [comment]
机器上运行其他的cuda程序可以成功吗？

**Comment by VVIZE-ops** [comment]
> 机器上运行其他的cuda程序可以成功吗？

现在已经彻底出问题了，，大概确定是显卡驱动问题
