### ISSUE TITLE
fleet.split_file error in python3.8

### ISSUE THREAD

**Issue by BladeSun** [PaddlePaddle/Paddle#29752]
https://github.com/PaddlePaddle/Paddle/blob/7c2affaa26cd3ed73915127243b067bb3a7958b4/python/paddle/fluid/incubate/fleet/base/fleet_base.py#L193

TypeError: slice indices must be integers or None or have an __index__ method

Paddle Version: 1.8.5
Python Version: 3.8.5

The problem is caused by different integer division behavior in py2/3.

I think the division operator in this function should change to // according to [PEP-238].(https://www.python.org/dev/peps/pep-0238/)

**Comment by seiriosPlus** [comment]
我们修一下.
