### ISSUE TITLE
Please release Pointer Generator implementation 

### ISSUE THREAD

**Issue by Pzoom522** [PaddlePaddle/Paddle#29751]
Hi,

[Pointer Generator](https://arxiv.org/abs/1704.04368) is one of the most popular baseline in text summarisation studies. It also serves as the building block of several very competitive models. Therefore, if Pointer Summariser can be included into your model zoo, it will greatly encourage the development of Paddle-based summarisation systems:wink:

Many thanks!

**Comment by guoshengCS** [comment]
We will put it into our near future plans. Thanks for your support and welcome to join the development of Paddle-based summarisation systems.

**Comment by Pzoom522** [comment]
Thanks a lot for your kind response. I will close this issue for now, but please do remember to refer to it / leave a comment upon further updates!
