### ISSUE TITLE
restore 导入模型参数时报错

### ISSUE THREAD

**Issue by YeFeiyangx** [PaddlePaddle/Paddle#29760]
我用linux训练的保存的模型文件ckpt，然后在windows环境下不能用restore方法导入，有解决方法嘛？
报错如下：
UnavailableError: LoadCombine operator fails to open file

[Hint: Expected static_cast<bool>(fin) == true, but received static_cast<bool>(fin):0 != true:1.] at (D:\1.8.5\paddle\paddle/fluid/operators/load_combine_op.h:50)

模型版本都是1.8.5的CPU版本

**Comment by sandyhouse** [comment]
确认下加载的文件有没有问题。

**Comment by YeFeiyangx** [comment]
> 确认下加载的文件有没有问题。

文件没有问题哈，我搬到了linux上，就可以了。
