### ISSUE TITLE
2.0rc版本，AI Studio上 cross entropy 报错

### ISSUE THREAD

**Issue by HXia-XXL** [PaddlePaddle/Paddle#29762]
代码之前都是好的。刚才运行一下，paddle.nn.functional.cross_entropy报错：
`ValueError: (InvalidArgument) Input(Logits) and Input(Label) should in same shape in dimensions except axis.
  [Hint: Expected logits_dims[i] == labels_dims[i], but received logits_dims[i]:5 != labels_dims[i]:512.] (at /paddle/paddle/fluid/operators/softmax_with_cross_entropy_op.cc:145)`

input和label的形状不同。可是之前都可以正常运行。

input shape： [8, 5, 512, 512]
label shape： [8, 512, 512]

请问是需要把input也变成[8,512,512]嘛？

**Comment by sandyhouse** [comment]
https://www.paddlepaddle.org.cn/documentation/docs/zh/2.0-rc1/api/paddle/nn/functional/loss/cross_entropy_cn.html#cross-entropy 参见API文档，除了axis参数指定的维度外，input和label其它维度的值需要一致。

**Comment by HXia-XXL** [comment]
您好， 我把label的shape 改成 [8 1 512 512] 然后设置 axis = 1 就可以运行了。代码前几天都能正常运行。今天报错就很奇怪。
还有 请问，默认axis = -1 是什么意思？

**Comment by HXia-XXL** [comment]
好像之前的2.0 rc版本里，cross-entropy没有axis这个参数。我本地环境里没有。最近是不是又更新了？

**Comment by sandyhouse** [comment]
axis=-1表示最后一个维度。有可能有更新。

**Comment by HXia-XXL** [comment]
好的。谢谢！
