### ISSUE TITLE
ubuntu安装错误

### ISSUE THREAD

**Issue by VVIZE-ops** [PaddlePaddle/Paddle#29773]
1）PaddlePaddle版本：1.8.5
    2）GPU：rtx1070     cuda:10.0    cudnn:7.6
    3）系统环境：ubuntu18.04  python 3.6

使用conda install paddlepaddle-gpu cudatoolkit=10.0 安装时报错，

报错信息：
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.

PackagesNotFoundError: The following packages are not available from current channels:

  - paddlepaddle-gpu

Current channels:

  - https://conda.anaconda.org/conda-forge/linux-64
  - https://conda.anaconda.org/conda-forge/noarch
  - https://repo.anaconda.com/pkgs/main/linux-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/linux-64
  - https://repo.anaconda.com/pkgs/r/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.

**Comment by ceci3** [comment]
conda config --add channels https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
conda config --add channels https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/
conda config --add channels https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/Paddle/
conda config --set show_channel_urls yes

你好，可以添加清华源试下

**Comment by VVIZE-ops** [comment]
> conda config --add channels https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
> conda config --add channels https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/
> conda config --add channels https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/Paddle/
> conda config --set show_channel_urls yes
> 
> 你好，可以添加清华源试下

好像还是不行，报错是
collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: / 
The environment is inconsistent, please check the package plan carefully
The following packages are causing the inconsistency:
还有好多这种
  - defaults/linux-64::statsmodels==0.9.0=py36h3010b51_0

**Comment by ceci3** [comment]
看起来是环境不一致 ，试下 conda update anaconda，
还是不可以的话试下：
conda clean --all
conda update --all

**Comment by VVIZE-ops** [comment]
> 看起来是环境不一致 ，试下 conda update anaconda，
> 还是不可以的话试下：
> conda clean --all
> conda update --all

问题解决了，真的是太感谢了

**Comment by ceci3** [comment]
那我先关掉这个issue咯，有别的问题可以再打开~

**Comment by VVIZE-ops** [comment]
> 看起来是环境不一致 ，试下 conda update anaconda，
> 还是不可以的话试下：
> conda clean --all
> conda update --all



> 那我先关掉这个issue咯，有别的问题可以再打开~

今天安装的时候又出问题了，，使用‘conda install paddlepaddle-gpu==1.8.5 cudatoolkit=10.0 -c paddle‘命令安装一直卡在 solving environment  这里

**Comment by VVIZE-ops** [comment]
电脑配置还是一样的，卡在solving environment 半个小时还是没有反应

**Comment by ceci3** [comment]
是在同一台机器上重新安装一遍吗？
