### ISSUE TITLE
paddle2.0rc1总是在装gpu版本时报错驱动太老，但1.8版本可以安装

### ISSUE THREAD

**Issue by cole-dda** [PaddlePaddle/Paddle#29787]
gpu:
<img width="698" alt="screenshot_3968" src="https://user-images.githubusercontent.com/1077830/102741628-dd77d580-438d-11eb-9bb1-4467447506a6.png">

cuda: 10.0.130

paddle: 2.0.0.rc1

异常：
<img width="1122" alt="screenshot_3969" src="https://user-images.githubusercontent.com/1077830/102741670-fc766780-438d-11eb-9c32-bfffb98e59ee.png">

但是nvidia的官方文档说明：
<img width="628" alt="screenshot_3970" src="https://user-images.githubusercontent.com/1077830/102741754-2a5bac00-438e-11eb-90dd-22d4cdbc458e.png">

如果安装的是paddle-1.8.5的版本，就可以正常运行。

**Comment by ysh329** [comment]
猜测可能是卡太老了，建议换新卡试试
