### ISSUE TITLE
转模型参数

### ISSUE THREAD

**Issue by huochf** [PaddlePaddle/Paddle#29780]
我在将pytorch参数转成paddle参数时，遇到点不懂的地方。

paddle中模型的state_dict中参数的类型是ParamBase，
而pytorch中state_dict中参数的类型是Tensor。

我的想法是将Tensor转成numpy，然后将numpy转成ParamBase，
当时由于我对paddle 的API不熟悉，
请问如何将numpy转成ParamBase。

在线等，加急！！

**Comment by Shixiaowei02** [comment]
您好，请尝试使用 `create-parameter` 算子创建参数，并用 `initializer.NumpyArrayInitializer` 进行初始化，谢谢！
https://www.paddlepaddle.org.cn/documentation/docs/zh/api_cn/layers_cn/create_parameter_cn.html#create-parameter
https://www.paddlepaddle.org.cn/documentation/docs/zh/api_cn/initializer_cn/NumpyArrayInitializer_cn.html#numpyarrayinitializer

**Comment by huochf** [comment]
> 您好，请尝试使用 `create-parameter` 算子创建参数，并用 `initializer.NumpyArrayInitializer` 进行初始化，谢谢！
> https://www.paddlepaddle.org.cn/documentation/docs/zh/api_cn/layers_cn/create_parameter_cn.html#create-parameter
> https://www.paddlepaddle.org.cn/documentation/docs/zh/api_cn/initializer_cn/NumpyArrayInitializer_cn.html#numpyarrayinitializer

emmm，直接使用load_dict就可以，看来你们工作人员对框架不熟悉呀！！！

model.load_dict(renamed_state_dict)

其中renamed_state_dict是我从pytorch中抠出来来的参数，格式转成了numpy.ndarray，
完美完成参数转换！！！！

**Comment by huochf** [comment]
> > 您好，请尝试使用 `create-parameter` 算子创建参数，并用 `initializer.NumpyArrayInitializer` 进行初始化，谢谢！
> > https://www.paddlepaddle.org.cn/documentation/docs/zh/api_cn/layers_cn/create_parameter_cn.html#create-parameter
> > https://www.paddlepaddle.org.cn/documentation/docs/zh/api_cn/initializer_cn/NumpyArrayInitializer_cn.html#numpyarrayinitializer
> 
> emmm，直接使用load_dict就可以，看来你们工作人员对框架不熟悉呀！！！
> 
> model.load_dict(renamed_state_dict)
> 
> 其中renamed_state_dict是我从pytorch中抠出来来的参数，格式转成了numpy.ndarray，
> 完美完成参数转换！！！！

也可能我没说明白问题~~
