### ISSUE TITLE
executor.py:1093: UserWarning: There are no operators in the program to be executed. 

### ISSUE THREAD

**Issue by eashow** [PaddlePaddle/Paddle#29783]
C:\Users\eashow\AppData\Local\Programs\Python\Python37\lib\site-packages\paddle\fluid\executor.py:1093: UserWarning: There are no operators in the program to be executed. If you pass Program manually, please use fluid.program_guard to ensure the current Program is being used.

这个警告怎么去掉呀？是什么意思？

**Comment by eashow** [comment]
原码：
# 获取每句话的单词数量
base_shape = [[len(c) for c in data]]

# 生成预测数据
tensor_words = fluid.create_lod_tensor(data, base_shape, place)

# 执行预测
result = exe.run(program=infer_program,
                 feed={feeded_var_names[0]: tensor_words},
                 fetch_list=target_var)

**Comment by ysh329** [comment]
这个警告影响你计算结果嘛
