### ISSUE TITLE
文档错别字 typo 小bug

### ISSUE THREAD

**Issue by jhcgt4869** [PaddlePaddle/Paddle#29793]
地址：[https://www.paddlepaddle.org.cn/documentation/docs/zh/2.0-rc1/api/paddle/vision/datasets/cifar/Cifar10_cn.html](https://www.paddlepaddle.org.cn/documentation/docs/zh/2.0-rc1/api/paddle/vision/datasets/cifar/Cifar10_cn.html)

![image](https://user-images.githubusercontent.com/61859193/102745419-e7ea9d00-4396-11eb-8d2d-6669ede8075c.png)

数据集包含10中类别.应该是数据集包含10种类别.吧？

个人看法，如理解有误表示抱歉！

**Comment by jhcgt4869** [comment]
[https://www.paddlepaddle.org.cn/documentation/docs/zh/2.0-rc1/api/paddle/vision/datasets/cifar/Cifar100_cn.html](https://www.paddlepaddle.org.cn/documentation/docs/zh/2.0-rc1/api/paddle/vision/datasets/cifar/Cifar100_cn.html)也是一样

**Comment by ysh329** [comment]
收到。我们后面会改进，已经反馈文档pm

**Comment by TCChenlong** [comment]
感谢反馈 已修复 https://www.paddlepaddle.org.cn/documentation/docs/zh/2.0-rc1/api/paddle/vision/datasets/cifar/Cifar10_cn.html~
