### ISSUE TITLE
Try to unify memory allocation in Paddle

### ISSUE THREAD

**Issue by reyoung** [PaddlePaddle/Paddle#2979]
We have a brand new `paddle::memory` module to manage our memory allocation. But the current main stream of Paddle is using memory allocation in `paddle/math`.

We should unify memory allocation to make the main stream of Paddle can allocate/deallocate memory faster and make code cleaner.

Related issue #751

**Comment by typhoonzero** [comment]
Closing this issue since we have `paddle/memory`.
