### ISSUE TITLE
静态图amp与`paddle.optimizer.AdamW`不兼容

### ISSUE THREAD

**Issue by Meiyim** [PaddlePaddle/Paddle#29794]
[这行](https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/fluid/contrib/mixed_precision/decorator.py#L222)代码中将`minimze` 拆解成`bacward`和`apply_optimize `
导致`AdamW`中进行weight_decay的[逻辑](https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/optimizer/adamw.py#L195)被绕过.

诸如此类的问题应该还有其他处（如regularizer,param_attr的插入），可能amp这块需要重新考虑兼容性问题。

**Comment by zhiqiu** [comment]
> [这行](https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/fluid/contrib/mixed_precision/decorator.py#L222)代码中将`minimze` 拆解成`bacward`和`apply_optimize `
> 导致`AdamW`中进行weight_decay的[逻辑](https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/optimizer/adamw.py#L195)被绕过.
> 
> 诸如此类的问题应该还有其他处（如regularizer,param_attr的插入），可能amp这块需要重新考虑兼容性问题。

嗯嗯，这个问题我们也注意到了，已经有计划修复。

**Comment by Meiyim** [comment]
any update?

**Comment by wangxicoding** [comment]
@Meiyim 已修复，试一下~
