### ISSUE TITLE
Hint: Expected desc->total_size >= size, but received desc->total_size:0 < size:4096

### ISSUE THREAD

**Issue by KaiyuanGao** [PaddlePaddle/Paddle#29791]
训练日志：http://10.182.101.144:8900/fileview.html?path=/home/disk1/normandy/maybach/app-user-20201220021818-38148/

非常简单的网络，cpu内存设置为200g，仍然报内存错误，麻烦看一下，谢谢！

![image](https://user-images.githubusercontent.com/33422503/102743742-0fd80180-4393-11eb-8869-2882bbf6d1fc.png)

**Comment by ysh329** [comment]
paddle版本？截取多一写日志，贴出来，

你给的链接不知道点进去看哪个。。

**Comment by KaiyuanGao** [comment]
你好，paddle版本1.7.1
全部的训练日志在链接：workspace-->log-->app-->train.log里可以看到
模型代码可以在：workspace-->env_run-->train.py 里看到
