### ISSUE TITLE
use var name to get variable instead of index

### ISSUE THREAD

**Issue by jacquesqiao** [PaddlePaddle/Paddle#2980]
Now in Operator or Kernel's Run/Infershape function, we may use index such as Input(0)/Ouptput(1)  to get variable from scope,  there are several problem of use index:

1. We have to remember what the meaning of each index is. In OpProto, we declare  the variable name and the name have it's meaning, such as "weight" "bias". Index do not have meaning and is hard to remember.
2. For variant input/output, we do not know the real index of the variable we want. It's hard to get what we want with index.

so we should use name declared in OpProto to get var from scope.

**Comment by typhoonzero** [comment]
Closing. I think it's already implemented.
