### ISSUE TITLE
C++预测CreatePaddlePredictor报错

### ISSUE THREAD

**Issue by ShuojieMo** [PaddlePaddle/Paddle#29812]
-预测信息
    1）C++预测： paddlepaddle1.8.0 ，
                            GIT COMMIT ID: 0231f58e592ad9f673ac1832d8c495c8ed65d24f
                            WITH_MKL: OFF
                            WITH_MKLDNN: OFF
                            WITH_GPU: OFF
    2）API信息：调用CreatePaddlePredictor读取预测模型报错，具体代码如下：
  `        AnalysisConfig config;
          CreateConfig(&config, model_dirname);
          auto predictor = CreatePaddlePredictor(config);`

- 问题描述：
原模型在python环境下训练，使用save_inference_model保存为预测模型，然后使用在C++预测时使用CreatePaddlePredictor调用该模型，具体报错信息如下：
`WARNING: Logging before InitGoogleLogging() is written to STDERR
I1222 09:35:05.791483 61693 analysis_predictor.cc:138] Profiler is deactivated, and no profiling report will be generated.
W1222 09:35:05.791641 61693 init.cc:166] AVX is available, Please re-compile on local machine
I1222 09:35:05.801527 61693 analysis_predictor.cc:872] MODEL VERSION: 1.8.5
I1222 09:35:05.801555 61693 analysis_predictor.cc:874] PREDICTOR VERSION: 1.8.0
--- Running analysis [ir_graph_build_pass]
--- Running analysis [ir_graph_clean_pass]
--- Running analysis [ir_analysis_pass]
--- Running IR pass [simplify_with_basic_ops_pass]
--- Running IR pass [attention_lstm_fuse_pass]
--- Running IR pass [seqconv_eltadd_relu_fuse_pass]
--- Running IR pass [seqpool_cvm_concat_fuse_pass]
--- Running IR pass [fc_lstm_fuse_pass]
--- Running IR pass [mul_lstm_fuse_pass]
--- Running IR pass [fc_gru_fuse_pass]
--- Running IR pass [mul_gru_fuse_pass]
I1222 09:35:05.861667 61693 graph_pattern_detector.cc:101] ---  detected 2 subgraphs
terminate called after throwing an instance of 'paddle::platform::EnforceNotMet'
  what():  

--------------------------------------------
C++ Call Stacks (More useful to developers):
--------------------------------------------

----------------------
Error Message Summary:
----------------------
NotFoundError: Node not found for PDNode fc_nobias_gru_fuse/fc/3/elementwise_add_out
  [Hint: Expected subgraph.count(fc_pattern.elementwise_add_out_n()) != 0UL, but received subgraph.count(fc_pattern.elementwise_add_out_n()):0 == 0UL:0.] at (/ssd4/moshuojie/Downloads/Paddle/paddle/fluid/framework/ir/fc_gru_fuse_pass.cc:123)`

**Comment by lijianshe02** [comment]
问题已经反馈，谢谢

**Comment by ShuojieMo** [comment]
> 问题已经反馈，谢谢

好的 谢谢

**Comment by JZZ-NOTE** [comment]
你好，根据报错信息无法定位具体问题，请问可以提供模型和单测吗？另外，可以尝试 paddle 的最新 2.2 版本，1.8 的版本比较老了
