### ISSUE TITLE
AI Studio 2.0rc版本中 paddle.numpy()数据更改

### ISSUE THREAD

**Issue by HXia-XXL** [PaddlePaddle/Paddle#29823]
label从迭代器中取出来是Tensor类型，【0，20】的范围。但是，
label = label.numpy() 会让label的最大/小值变化，
现在会出现：
-464714812233515008
不知道为什么，而且是随机蹦出来异常值，导致程序中断

**Comment by HXia-XXL** [comment]
或者还有别的方法把Tensor转成ndarray类型嘛

**Comment by lijianshe02** [comment]
问题应该不是tensor转numpy()造成的，请检查您最初的数据是否存在这样的异常值

**Comment by HXia-XXL** [comment]
谢谢您，模型跑到现在没出现问题了。
