### ISSUE TITLE
pp2.0 Conv2DTranspose 输出值 shape 问题

### ISSUE THREAD

**Issue by TWLemontree** [PaddlePaddle/Paddle#29827]
强烈建议 2.0 的 Conv2DTranspose 接口再加上属性 output_size ！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！

使用本接口时，通常希望上采样至整数倍的！比如我输入特征图是 256*256，我肯定希望他输出 512*512，而不是 513*513 或 511*511 之类的奇怪的东西！！！！！！

**Comment by lijianshe02** [comment]
谢谢您的反馈，我们会评估改进

**Comment by lijianshe02** [comment]
class paddle.fluid.dygraph.Conv2DTranspose(num_channels, num_filters, filter_size, output_size=None, padding=0, stride=1, dilation=1, groups=None, param_attr=None, bias_attr=None, use_cudnn=True, act=None, dtype='float32')
2.0的接口如上所示，是有output_size参数的
