### ISSUE TITLE
paddle1.8.4 core_dump

### ISSUE THREAD

**Issue by ellinyang** [PaddlePaddle/Paddle#29825]
物理机：Linux
镜像：paddle1.8.4-gpu-cuda9.0-cudnn7
驱动情况：
![image](https://user-images.githubusercontent.com/20673237/102862545-361da000-446c-11eb-8ed1-01242e1d1908.png)
在ssd上、mask_rcnn训练时，偶尔会报如下错误信息，但是重试后又成功了，请问有什么可能的原因？
![image](https://user-images.githubusercontent.com/20673237/102862619-53526e80-446c-11eb-8988-96456a4d0ad7.png)

**Comment by lijianshe02** [comment]
请查看是否是显存不够造成的

**Comment by ellinyang** [comment]
我们显存是足够的，V100机型也会报这样的错误。同样的代码，同样的机器上，错误的模型重试就成功了。目前观测到主要在paddle1.8.4上才会出现这个情况。
今天在yolov3_mobilenetv1上也发生了这样的情况
