### ISSUE TITLE
fluid.layers.dynamic_lstm() 变长序列输入支持

### ISSUE THREAD

**Issue by caoyu1664** [PaddlePaddle/Paddle#29831]
paddle version: 1.8
python version: 3.6

paddle.fluid.layers.dynamic_lstm()可以支持变长序列输入吗？
根据文档，该接口输入为 [T,4∗hidden_size]  的多维 LoDTensor。将输入剥掉padding后构造成LoDTensor即可实现变长lstm?

**Comment by lijianshe02** [comment]
看文档是这样的

**Comment by caoyu1664** [comment]
> 看文档是这样的

请问有实现lstm变长输入的demo吗？我尝试把输入tenser转numpy后，剥掉padding并用paddle.fluid.create_lod_tensor()构建LodTensor送入lstm并没有成功，看起来静态图并不支持这样做？

**Comment by lijianshe02** [comment]
这个我咨询下相关同学再回复您
