### ISSUE TITLE
WIN下PaddlePaddle2 GPU RC1安装问题

### ISSUE THREAD

**Issue by livingbody** [PaddlePaddle/Paddle#29835]
<img width="782" alt="微信图片_20201222185355" src="https://user-images.githubusercontent.com/8059137/102881095-4e4ee880-4487-11eb-8bcc-8ae59b42c62a.png">
![微信图片_20201222185323](https://user-images.githubusercontent.com/8059137/102881164-69b9f380-4487-11eb-9bfa-bedb69dfb0ec.png)

**Comment by lijianshe02** [comment]
报错信息是找不到cudnn找不到，请在正确安装完cuda, cudnn后，设置相应的PATH

**Comment by livingbody** [comment]
<img width="744" alt="mmexport1608798747053" src="https://user-images.githubusercontent.com/8059137/103075101-e8d53600-4605-11eb-93d1-d02741f23bff.png">
