### ISSUE TITLE
VS2017编译release/2.0-rc1版本报找不到“mkldnn.hpp”

### ISSUE THREAD

**Issue by patrickwf** [PaddlePaddle/Paddle#29839]
如题，cmake打开选项WITH_MKL编译时会出现找不到“mkldnn.hpp”

**Comment by lijianshe02** [comment]
查看一下mkl有没有下载下来，有时因为网络问题可能没有下载下来

**Comment by patrickwf** [comment]
> 查看一下mkl有没有下载下来，有时因为网络问题可能没有下载下来

在\Paddle\build\third_party\mkldnn\src\extern_mkldnn\include 目录下已经存在mkldnn.hpp文件了

**Comment by patrickwf** [comment]
> 查看一下mkl有没有下载下来，有时因为网络问题可能没有下载下来
mkldnn似乎是编译错误，只支持64位？
log显示
CMake Error at CMakeLists.txt:87 (message):
  oneDNN supports 64 bit platforms only

**Comment by luotao1** [comment]
@zhouwei25 @Avin0323 两位看下？
