### ISSUE TITLE
这里感觉是sed用得走火入魔了

### ISSUE THREAD

**Issue by mikeshi80** [PaddlePaddle/Paddle#29846]
https://github.com/PaddlePaddle/Paddle/blob/7b33720c90da72889fa65829a4e7c0edc0e8f986/tools/dockerfile/ci_dockerfile.sh#L22

其实不需要先用这么复杂的方法，先算出文件的行数，然后在该行的后面用sed插入新的一行的，直接使用 `<<` 符号不就是在文本文件最后添加一行嘛

**Comment by bjjwwang** [comment]
好的 感谢建议

**Comment by starsblinking** [comment]
233
