### ISSUE TITLE
How to use LoD-Tensor in Dynamic Graph?

### ISSUE THREAD

**Issue by Dice21** [PaddlePaddle/Paddle#29848]
I'm coding with **dynamic graph** and I want to use **LoD-Tensor**  to process variable-length sequences.
I have searched in documents but only found APIs used in static graph.
Can any one tell me is there any APIs to process variable-length sequences in dynamic graph?

**Comment by bjjwwang** [comment]
No, lod-tensor is not available in dygraph mode.
I will consult someone to address the replacement of lod-tensor in dygraph.

**Comment by bjjwwang** [comment]
it is recommended to add padding elements to adjust the variable length.
