### ISSUE TITLE
Ｂｕｇ

### ISSUE THREAD

**Issue by cqray1990** [PaddlePaddle/Paddle#29845]
paddle version:2.0rc1
cuda 10.0,cudnn7.x
用ｐｙｃｈａｒｍ调试ｐａｄｄｌｅ代码中途强制终端停止调试，会出现闪退，电脑上的程序全都退出了，代码可以正常跑的，就是调试出问题

**Comment by bjjwwang** [comment]
用的是静态图还是动态图模式 可能不一定可以这么做。我讨论下反馈情况

**Comment by cqray1990** [comment]
用的是动态图

**Comment by WenmuZhou** [comment]
插眼

**Comment by chaoyu0804** [comment]
出现相同问题
paddlepaddle-cpu==2.0.2
python=3.7

**Comment by WenmuZhou** [comment]
mark

**Comment by cqray1990** [comment]
@WenmuZhou 闪退的问题还没有解决啊，又出现了啊

**Comment by Amanda-Barbara** [comment]
@WenmuZhou 在pycharm使用paddlex运行程序，终止运行后，pycharm还是会闪退
