### ISSUE TITLE
Conv layer check "layer_type" err while use "cudnn_convt" or "cudnn_conv" in gpu mode

### ISSUE THREAD

**Issue by wanghaoshuang** [PaddlePaddle/Paddle#2984]
Conv layer will check 'use_gpu' option while  `layer_type` is setted  to `cudnn_conv` at [code](https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/trainer/config_parser.py#L1825-L1826). But conv layer can't can get `use_gpu` option correctly at [here](https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/trainer/config_parser.py#L1819). I guess the solution of parsing `use_gpu` from cmd line is not compatible with v2 api.
We can fix this bug by:
1. Remove check use_gpu
2. Put `use_gpu` option into os.environ.iteritems() while [paddle.init()](https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/v2/__init__.py#L60) is called.
3. Or other better solution?

And another bug:
`cudnn_convt` should be added [here](https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/trainer_config_helpers/layers.py#L157)  for supporting trans_conv in gpu mode.

**Comment by hedaoyuan** [comment]
I think we can consider removing `exconv` and `cudnn_conv` type, only to retain the `conv` type. In the c++ code to determine the use of exconv or cudnn_conv calculation method.
