### ISSUE TITLE
cuda11上多卡训练报错

### ISSUE THREAD

**Issue by swtkiwi** [PaddlePaddle/Paddle#29847]
![191608691997_ pic_hd](https://user-images.githubusercontent.com/27208573/102954426-661d7f80-450e-11eb-87ca-279ad200619e.jpg)
单卡训练没问题，使用的是AIStation的多实例提交，不是单环境双卡时出现问题。用的是paddle的distributed函数

**Comment by gongweibao** [comment]
怎么启动的？能不能把启动方式发上来？

**Comment by acelib02** [comment]
![图片](https://user-images.githubusercontent.com/66370384/102975337-dc37db80-453a-11eb-9629-8a276a6ed1cf.png)
启动方式如图所示

**Comment by acelib02** [comment]
启动脚本如下：
#!/usr/bin/env bash

export PYTHONPATH=$PWD:$PYTHONPATH
python3 -m paddle.distributed.launch --gpus="0,1" tools/train.py -c ./config/ResNet/ResNet50.yaml -o print_interval-10

**Comment by sandyhouse** [comment]
paddle用的什么版本，模型使动态图还是静态图？另外，多实例提交是什么意思，同时提交多个任务吗？

**Comment by acelib02** [comment]
Paddle使用的是docker hub的rc2-2.0.0-cuda11镜像；

模型使用动态图；

多实例是客户在AIStation训练平台里通过多实例提交运行任务，相当于两个docker实例配的分布式训练（8卡单服务器）

 

有一个镜像交流群，是否可以在群里进行交流？

----- 原始邮件 -----
发件人：lilong12 <notifications@github.com>
收件人：PaddlePaddle/Paddle <Paddle@noreply.github.com>
抄送人：acelib02 <libaoran_89@sina.com>,  Comment <comment@noreply.github.com>
主题：Re:_[PaddlePaddle/Paddle]_cuda11上多卡训练报错_(#29847)
日期：2020年12月23日 16点28分



paddle用的什么版本，模型使动态图还是静态图？另外，多实例提交是什么意思，同时提交多个任务吗？

**Comment by sandyhouse** [comment]
看报错信息是端口冲突，导致绑定失败，但不了解具体的机器环境。贴下完整的日志信息，并且贴下log/workerlog.x文件的内容吧。

**Comment by acelib02** [comment]
附件是客户提供的log信息。
----- 原始邮件 -----
发件人：lilong12 <notifications@github.com>
收件人：PaddlePaddle/Paddle <Paddle@noreply.github.com>
抄送人：acelib02 <libaoran_89@sina.com>,  Comment <comment@noreply.github.com>
主题：Re:_[PaddlePaddle/Paddle]_cuda11上多卡训练报错_(#29847)
日期：2020年12月23日 19点32分



看报错信息是端口冲突，导致绑定失败，但不了解具体的机器环境。贴下完整的日志信息，并且贴下log/workerlog.x文件的内容吧。

**Comment by sandyhouse** [comment]
附件在什么地方，并没有看到。

**Comment by acelib02** [comment]
已重传附件。附件的log内容如下：
------
grep: warning: GREP_OPTIONS is deprecated; please use an alias or scriptTraceback (most recent call last):
  File "tools/train.py", line 29, in <module>
    from ppcls.data import Reader
  File "/test01/PaddleClas-dygraph/ppcls/__init__.py", line 19, in <module>
    from .data import *
  File "/test01/PaddleClas-dygraph/ppcls/data/__init__.py", line 15, in <module>
    from .reader import Reader
  File "/test01/PaddleClas-dygraph/ppcls/data/reader.py", line 22, in <module>
    from . import imaug
  File "/test01/PaddleClas-dygraph/ppcls/data/imaug/__init__.py", line 23, in <module>
    from .operators import DecodeImage
  File "/test01/PaddleClas-dygraph/ppcls/data/imaug/operators.py", line 25, in <module>
    import cv2
ImportError: No module named 'cv2'
grep: warning: GREP_OPTIONS is deprecated; please use an alias or script
Traceback (most recent call last):
  File "tools/train.py", line 29, in <module>
    from ppcls.data import Reader
  File "/test01/PaddleClas-dygraph/ppcls/__init__.py", line 19, in <module>
    from .data import *
  File "/test01/PaddleClas-dygraph/ppcls/data/__init__.py", line 15, in <module>
    from .reader import Reader
  File "/test01/PaddleClas-dygraph/ppcls/data/reader.py", line 24, in <module>
    from ppcls.utils import logger
  File "/test01/PaddleClas-dygraph/ppcls/utils/__init__.py", line 17, in <module>
    from . import model_zoo
  File "/test01/PaddleClas-dygraph/ppcls/utils/model_zoo.py", line 23, in <module>
    import tqdm
ImportError: No module named 'tqdm'
grep: warning: GREP_OPTIONS is deprecated; please use an alias or script
I1222 16:43:31.142839   516 nccl_context.cc:179] init nccl context nranks: 2 local rank: 1 gpu id: 1 ring id: 0
W1222 16:43:32.916322   516 device_context.cc:320] Please NOTE: device: 1, GPU Compute Capability: 8.0, Driver API Version: 11.0, Runtime API Version: 11.0
W1222 16:43:32.920051   516 device_context.cc:330] device: 1, cuDNN Version: 8.0.
server not ready, wait 3 sec to retry...
not ready endpoints:['127.0.0.1:60001']
server not ready, wait 3 sec to retry...
not ready endpoints:['127.0.0.1:60001']
server not ready, wait 3 sec to retry...
not ready endpoints:['127.0.0.1:60001']
server not ready, wait 3 sec to retry...
not ready endpoints:['127.0.0.1:60001']
server not ready, wait 3 sec to retry...
not ready endpoints:['127.0.0.1:60001']
server not ready, wait 3 sec to retry...
not ready endpoints:['127.0.0.1:60001']
server not ready, wait 3 sec to retry...
not ready endpoints:['127.0.0.1:60001']
server not ready, wait 3 sec to retry...
not ready endpoints:['127.0.0.1:60001']
server not ready, wait 3 sec to retry...
not ready endpoints:['127.0.0.1:60001']
server not ready, wait 3 sec to retry...
not ready endpoints:['127.0.0.1:60001']
grep: warning: GREP_OPTIONS is deprecated; please use an alias or script
grep: warning: GREP_OPTIONS is deprecated; please use an alias or script
I1222 16:46:59.120170   901 nccl_context.cc:179] init nccl context nranks: 2 local rank: 1 gpu id: 1 ring id: 0
W1222 16:46:59.995787   901 device_context.cc:320] Please NOTE: device: 1, GPU Compute Capability: 8.0, Driver API Version: 11.0, Runtime API Version: 11.0
W1222 16:46:59.999712   901 device_context.cc:330] device: 1, cuDNN Version: 8.0.
grep: warning: GREP_OPTIONS is deprecated; please use an alias or script
I1222 16:47:21.679802  1094 nccl_context.cc:179] init nccl context nranks: 2 local rank: 1 gpu id: 1 ring id: 0
W1222 16:47:22.521466  1094 device_context.cc:320] Please NOTE: device: 1, GPU Compute Capability: 8.0, Driver API Version: 11.0, Runtime API Version: 11.0
W1222 16:47:22.524753  1094 device_context.cc:330] device: 1, cuDNN Version: 8.0.
server not ready, wait 3 sec to retry...
not ready endpoints:['127.0.0.1:60052']
server not ready, wait 3 sec to retry...
not ready endpoints:['127.0.0.1:60052']
server not ready, wait 3 sec to retry...
not ready endpoints:['127.0.0.1:60052']
server not ready, wait 3 sec to retry...
not ready endpoints:['127.0.0.1:60052']
server not ready, wait 3 sec to retry...
not ready endpoints:['127.0.0.1:60052']
server not ready, wait 3 sec to retry...
not ready endpoints:['127.0.0.1:60052']
server not ready, wait 3 sec to retry...
not ready endpoints:['127.0.0.1:60052']
server not ready, wait 3 sec to retry...
not ready endpoints:['127.0.0.1:60052']
server not ready, wait 3 sec to retry...
not ready endpoints:['127.0.0.1:60052']
server not ready, wait 3 sec to retry...
not ready endpoints:['127.0.0.1:60052']
grep: warning: GREP_OPTIONS is deprecated; please use an alias or script
I1222 16:53:54.503665  1289 nccl_context.cc:179] init nccl context nranks: 2 local rank: 1 gpu id: 1 ring id: 0
W1222 16:53:55.470510  1289 device_context.cc:320] Please NOTE: device: 1, GPU Compute Capability: 8.0, Driver API Version: 11.0, Runtime API Version: 11.0
W1222 16:53:55.476626  1289 device_context.cc:330] device: 1, cuDNN Version: 8.0.
server not ready, wait 3 sec to retry...
not ready endpoints:['127.0.0.1:60001']
server not ready, wait 3 sec to retry...
not ready endpoints:['127.0.0.1:60001']
grep: warning: GREP_OPTIONS is deprecated; please use an alias or script
I1222 16:55:24.149829  1534 nccl_context.cc:179] init nccl context nranks: 2 local rank: 1 gpu id: 1 ring id: 0
W1222 16:55:25.007056  1534 device_context.cc:320] Please NOTE: device: 1, GPU Compute Capability: 8.0, Driver API Version: 11.0, Runtime API Version: 11.0
W1222 16:55:25.010737  1534 device_context.cc:330] device: 1, cuDNN Version: 8.0.
server not ready, wait 3 sec to retry...
not ready endpoints:['127.0.0.1:60001']
server not ready, wait 3 sec to retry...
not ready endpoints:['127.0.0.1:60001']
server not ready, wait 3 sec to retry...
not ready endpoints:['127.0.0.1:60001']
server not ready, wait 3 sec to retry...
not ready endpoints:['127.0.0.1:60001']
grep: warning: GREP_OPTIONS is deprecated; please use an alias or script
I1223 02:45:16.442513  1754 nccl_context.cc:179] init nccl context nranks: 2 local rank: 1 gpu id: 1 ring id: 0
W1223 02:45:17.463632  1754 device_context.cc:320] Please NOTE: device: 1, GPU Compute Capability: 8.0, Driver API Version: 11.0, Runtime API Version: 11.0
W1223 02:45:17.469348  1754 device_context.cc:330] device: 1, cuDNN Version: 8.0.
server not ready, wait 3 sec to retry...
not ready endpoints:['127.0.0.1:60001']
server not ready, wait 3 sec to retry...
not ready endpoints:['127.0.0.1:60001']
server not ready, wait 3 sec to retry...
not ready endpoints:['127.0.0.1:60001']
server not ready, wait 3 sec to retry...
not ready endpoints:['127.0.0.1:60001']
server not ready, wait 3 sec to retry...
not ready endpoints:['127.0.0.1:60001']
server not ready, wait 3 sec to retry...
not ready endpoints:['127.0.0.1:60001']
server not ready, wait 3 sec to retry...
not ready endpoints:['127.0.0.1:60001']
server not ready, wait 3 sec to retry...
not ready endpoints:['127.0.0.1:60001']
server not ready, wait 3 sec to retry...
not ready endpoints:['127.0.0.1:60001']
server not ready, wait 3 sec to retry...
not ready endpoints:['127.0.0.1:60001']
server not ready, wait 3 sec to retry...
not ready endpoints:['127.0.0.1:60001']
server not ready, wait 3 sec to retry...
not ready endpoints:['127.0.0.1:60001']
server not ready, wait 3 sec to retry...
not ready endpoints:['127.0.0.1:60001']
server not ready, wait 3 sec to retry...
not ready endpoints:['127.0.0.1:60001']
server not ready, wait 3 sec to retry...
not ready endpoints:['127.0.0.1:60001']
server not ready, wait 3 sec to retry...
not ready endpoints:['127.0.0.1:60001']
server not ready, wait 3 sec to retry...
not ready endpoints:['127.0.0.1:60001']
server not ready, wait 3 sec to retry...
not ready endpoints:['127.0.0.1:60001']
server not ready, wait 3 sec to retry...
not ready endpoints:['127.0.0.1:60001']
server not ready, wait 3 sec to retry...
not ready endpoints:['127.0.0.1:60001']
server not ready, wait 3 sec to retry...
not ready endpoints:['127.0.0.1:60001']
server not ready, wait 3 sec to retry...
not ready endpoints:['127.0.0.1:60001']
server not ready, wait 3 sec to retry...
not ready endpoints:['127.0.0.1:60001']
server not ready, wait 3 sec to retry...
not ready endpoints:['127.0.0.1:60001']
server not ready, wait 3 sec to retry...
not ready endpoints:['127.0.0.1:60001']
server not ready, wait 3 sec to retry...
not ready endpoints:['127.0.0.1:60001']
server not ready, wait 3 sec to retry...
not ready endpoints:['127.0.0.1:60001']
server not ready, wait 3 sec to retry...
not ready endpoints:['127.0.0.1:60001']
server not ready, wait 3 sec to retry...
not ready endpoints:['127.0.0.1:60001']
server not ready, wait 3 sec to retry...
not ready endpoints:['127.0.0.1:60001']
server not ready, wait 3 sec to retry...
not ready endpoints:['127.0.0.1:60001']
server not ready, wait 3 sec to retry...
not ready endpoints:['127.0.0.1:60001']
server not ready, wait 3 sec to retry...
not ready endpoints:['127.0.0.1:60001']
server not ready, wait 3 sec to retry...
not ready endpoints:['127.0.0.1:60001']
server not ready, wait 3 sec to retry...
not ready endpoints:['127.0.0.1:60001']
server not ready, wait 3 sec to retry...
not ready endpoints:['127.0.0.1:60001']
server not ready, wait 3 sec to retry...
not ready endpoints:['127.0.0.1:60001']
server not ready, wait 3 sec to retry...
not ready endpoints:['127.0.0.1:60001']
server not ready, wait 3 sec to retry...
not ready endpoints:['127.0.0.1:60001']
server not ready, wait 3 sec to retry...
not ready endpoints:['127.0.0.1:60001']
server not ready, wait 3 sec to retry...
not ready endpoints:['127.0.0.1:60001']
server not ready, wait 3 sec to retry...
not ready endpoints:['127.0.0.1:60001']
server not ready, wait 3 sec to retry...
not ready endpoints:['127.0.0.1:60001']
server not ready, wait 3 sec to retry...
not ready endpoints:['127.0.0.1:60001']
server not ready, wait 3 sec to retry...
not ready endpoints:['127.0.0.1:60001']
server not ready, wait 3 sec to retry...
not ready endpoints:['127.0.0.1:60001']
server not ready, wait 3 sec to retry...
not ready endpoints:['127.0.0.1:60001']
server not ready, wait 3 sec to retry...
not ready endpoints:['127.0.0.1:60001']
server not ready, wait 3 sec to retry...
not ready endpoints:['127.0.0.1:60001']
server not ready, wait 3 sec to retry...
not ready endpoints:['127.0.0.1:60001']
server not ready, wait 3 sec to retry...
not ready endpoints:['127.0.0.1:60001']
server not ready, wait 3 sec to retry...
not ready endpoints:['127.0.0.1:60001']
server not ready, wait 3 sec to retry...
not ready endpoints:['127.0.0.1:60001']
server not ready, wait 3 sec to retry...
not ready endpoints:['127.0.0.1:60001']
server not ready, wait 3 sec to retry...
not ready endpoints:['127.0.0.1:60001']
server not ready, wait 3 sec to retry...
not ready endpoints:['127.0.0.1:60001']
server not ready, wait 3 sec to retry...
not ready endpoints:['127.0.0.1:60001']
server not ready, wait 3 sec to retry...
not ready endpoints:['127.0.0.1:60001']
server not ready, wait 3 sec to retry...
not ready endpoints:['127.0.0.1:60001']
server not ready, wait 3 sec to retry...
not ready endpoints:['127.0.0.1:60001']
server not ready, wait 3 sec to retry...
not ready endpoints:['127.0.0.1:60001']
server not ready, wait 3 sec to retry...
not ready endpoints:['127.0.0.1:60001']
server not ready, wait 3 sec to retry...
not ready endpoints:['127.0.0.1:60001']
server not ready, wait 3 sec to retry...
not ready endpoints:['127.0.0.1:60001']
server not ready, wait 3 sec to retry...
not ready endpoints:['127.0.0.1:60001']
server not ready, wait 3 sec to retry...
not ready endpoints:['127.0.0.1:60001']
server not ready, wait 3 sec to retry...
not ready endpoints:['127.0.0.1:60001']
server not ready, wait 3 sec to retry...
not ready endpoints:['127.0.0.1:60001']
server not ready, wait 3 sec to retry...
not ready endpoints:['127.0.0.1:60001']
server not ready, wait 3 sec to retry...
not ready endpoints:['127.0.0.1:60001']
server not ready, wait 3 sec to retry...
not ready endpoints:['127.0.0.1:60001']
server not ready, wait 3 sec to retry...
not ready endpoints:['127.0.0.1:60001']
server not ready, wait 3 sec to retry...
not ready endpoints:['127.0.0.1:60001']
server not ready, wait 3 sec to retry...
not ready endpoints:['127.0.0.1:60001']
server not ready, wait 3 sec to retry...
not ready endpoints:['127.0.0.1:60001']
server not ready, wait 3 sec to retry...
not ready endpoints:['127.0.0.1:60001']
server not ready, wait 3 sec to retry...
not ready endpoints:['127.0.0.1:60001']
server not ready, wait 3 sec to retry...
not ready endpoints:['127.0.0.1:60001']
server not ready, wait 3 sec to retry...
not ready endpoints:['127.0.0.1:60001']
server not ready, wait 3 sec to retry...
not ready endpoints:['127.0.0.1:60001']
server not ready, wait 3 sec to retry...
not ready endpoints:['127.0.0.1:60001']
server not ready, wait 3 sec to retry...
not ready endpoints:['127.0.0.1:60001']
server not ready, wait 3 sec to retry...
not ready endpoints:['127.0.0.1:60001']
server not ready, wait 3 sec to retry...
not ready endpoints:['127.0.0.1:60001']
server not ready, wait 3 sec to retry...
not ready endpoints:['127.0.0.1:60001']
server not ready, wait 3 sec to retry...
not ready endpoints:['127.0.0.1:60001']
server not ready, wait 3 sec to retry...
not ready endpoints:['127.0.0.1:60001']
server not ready, wait 3 sec to retry...
not ready endpoints:['127.0.0.1:60001']
server not ready, wait 3 sec to retry...
not ready endpoints:['127.0.0.1:60001']
server not ready, wait 3 sec to retry...
not ready endpoints:['127.0.0.1:60001']
server not ready, wait 3 sec to retry...
not ready endpoints:['127.0.0.1:60001']
server not ready, wait 3 sec to retry...
not ready endpoints:['127.0.0.1:60001']
server not ready, wait 3 sec to retry...
not ready endpoints:['127.0.0.1:60001']
server not ready, wait 3 sec to retry...
not ready endpoints:['127.0.0.1:60001']
server not ready, wait 3 sec to retry...
not ready endpoints:['127.0.0.1:60001']
server not ready, wait 3 sec to retry...
not ready endpoints:['127.0.0.1:60001']
server not ready, wait 3 sec to retry...
not ready endpoints:['127.0.0.1:60001']
server not ready, wait 3 sec to retry...
not ready endpoints:['127.0.0.1:60001']
server not ready, wait 3 sec to retry...
not ready endpoints:['127.0.0.1:60001']
server not ready, wait 3 sec to retry...
not ready endpoints:['127.0.0.1:60001']
server not ready, wait 3 sec to retry...
not ready endpoints:['127.0.0.1:60001']
server not ready, wait 3 sec to retry...
not ready endpoints:['127.0.0.1:60001']
server not ready, wait 3 sec to retry...
not ready endpoints:['127.0.0.1:60001']
server not ready, wait 3 sec to retry...
not ready endpoints:['127.0.0.1:60001']
server not ready, wait 3 sec to retry...
not ready endpoints:['127.0.0.1:60001']
server not ready, wait 3 sec to retry...
not ready endpoints:['127.0.0.1:60001']
server not ready, wait 3 sec to retry...
not ready endpoints:['127.0.0.1:60001']
server not ready, wait 3 sec to retry...
not ready endpoints:['127.0.0.1:60001']
server not ready, wait 3 sec to retry...
not ready endpoints:['127.0.0.1:60001']
server not ready, wait 3 sec to retry...
not ready endpoints:['127.0.0.1:60001']
server not ready, wait 3 sec to retry...
not ready endpoints:['127.0.0.1:60001']
server not ready, wait 3 sec to retry...
not ready endpoints:['127.0.0.1:60001']
server not ready, wait 3 sec to retry...
not ready endpoints:['127.0.0.1:60001']
server not ready, wait 3 sec to retry...
not ready endpoints:['127.0.0.1:60001']
server not ready, wait 3 sec to retry...
not ready endpoints:['127.0.0.1:60001']
server not ready, wait 3 sec to retry...
not ready endpoints:['127.0.0.1:60001']
server not ready, wait 3 sec to retry...
not ready endpoints:['127.0.0.1:60001']
server not ready, wait 3 sec to retry...
not ready endpoints:['127.0.0.1:60001']
server not ready, wait 3 sec to retry...
not ready endpoints:['127.0.0.1:60001']
server not ready, wait 3 sec to retry...
not ready endpoints:['127.0.0.1:60001']
server not ready, wait 3 sec to retry...
not ready endpoints:['127.0.0.1:60001']
server not ready, wait 3 sec to retry...
not ready endpoints:['127.0.0.1:60001']
server not ready, wait 3 sec to retry...
not ready endpoints:['127.0.0.1:60001']
server not ready, wait 3 sec to retry...
not ready endpoints:['127.0.0.1:60001']
server not ready, wait 3 sec to retry...
not ready endpoints:['127.0.0.1:60001']
server not ready, wait 3 sec to retry...
not ready endpoints:['127.0.0.1:60001']
server not ready, wait 3 sec to retry...
not ready endpoints:['127.0.0.1:60001']
server not ready, wait 3 sec to retry...
not ready endpoints:['127.0.0.1:60001']
server not ready, wait 3 sec to retry...
not ready endpoints:['127.0.0.1:60001']
server not ready, wait 3 sec to retry...
not ready endpoints:['127.0.0.1:60001']
server not ready, wait 3 sec to retry...
not ready endpoints:['127.0.0.1:60001']
server not ready, wait 3 sec to retry...
not ready endpoints:['127.0.0.1:60001']
server not ready, wait 3 sec to retry...
not ready endpoints:['127.0.0.1:60001']
server not ready, wait 3 sec to retry...
not ready endpoints:['127.0.0.1:60001']
server not ready, wait 3 sec to retry...
not ready endpoints:['127.0.0.1:60001']
server not ready, wait 3 sec to retry...
not ready endpoints:['127.0.0.1:60001']
server not ready, wait 3 sec to retry...
not ready endpoints:['127.0.0.1:60001']
server not ready, wait 3 sec to retry...
not ready endpoints:['127.0.0.1:60001']
server not ready, wait 3 sec to retry...
not ready endpoints:['127.0.0.1:60001']
server not ready, wait 3 sec to retry...
not ready endpoints:['127.0.0.1:60001']
server not ready, wait 3 sec to retry...
not ready endpoints:['127.0.0.1:60001']
server not ready, wait 3 sec to retry...
not ready endpoints:['127.0.0.1:60001']

----------
----- 原始邮件 -----
发件人：lilong12 <notifications@github.com>
收件人：PaddlePaddle/Paddle <Paddle@noreply.github.com>
抄送人：acelib02 <libaoran_89@sina.com>,  Comment <comment@noreply.github.com>
主题：Re:_[PaddlePaddle/Paddle]_cuda11上多卡训练报错_(#29847)
日期：2020年12月24日 10点51分



附件在什么地方，并没有看到。

**Comment by sandyhouse** [comment]
这个日志是多次运行的日志混在一起了吗？另外，这是个多卡任务，这个日志是不是只是给出了一张卡上的日志？稍微整理下日志吧，并且把所有卡的日志都贴一下吧。只需要一次运行的日志，不要多次运行的日志混在一起，不太好区分（运行前删除下log目录）

**Comment by duanyaohui** [comment]
**这是第一张卡的日志**
I1224 10:26:23.885565   337 nccl_context.cc:179] init nccl context nranks: 2 local rank: 0 gpu id: 0 ring id: 0
Process Process-2:
Traceback (most recent call last):
  File "/usr/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/usr/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.7/dist-packages/paddle/distributed/parallel.py", line 49, in _start_kv_server
    http_server = KVServer(int(port), size=size)
  File "/usr/local/lib/python3.7/dist-packages/paddle/distributed/fleet/utils/http_server.py", line 165, in __init__
    self.http_server = KVHTTPServer(port, KVHandler)
  File "/usr/local/lib/python3.7/dist-packages/paddle/distributed/fleet/utils/http_server.py", line 142, in __init__
    super(KVHTTPServer, self).__init__(('', port), handler)
  File "/usr/lib/python3.7/socketserver.py", line 452, in __init__
    self.server_bind()
  File "/usr/lib/python3.7/http/server.py", line 137, in server_bind
    socketserver.TCPServer.server_bind(self)
  File "/usr/lib/python3.7/socketserver.py", line 466, in server_bind
    self.socket.bind(self.server_address)
OSError: [Errno 98] Address already in use
W1224 10:26:24.740589   337 device_context.cc:320] Please NOTE: device: 0, GPU Compute Capability: 8.0, Driver API Version: 11.0, Runtime API Version: 11.0
W1224 10:26:24.744740   337 device_context.cc:330] device: 0, cuDNN Version: 8.0.
server not ready, wait 3 sec to retry...
not ready endpoints:['127.0.0.1:60001']
server not ready, wait 3 sec to retry...
not ready endpoints:['127.0.0.1:60001']
server not ready, wait 3 sec to retry...
not ready endpoints:['127.0.0.1:60001']
server not ready, wait 3 sec to retry...
not ready endpoints:['127.0.0.1:60001']
**这是第二张卡的日志**
grep: warning: GREP_OPTIONS is deprecated; please use an alias or script
I1224 10:26:23.885589   342 nccl_context.cc:179] init nccl context nranks: 2 local rank: 1 gpu id: 1 ring id: 0
W1224 10:26:24.740778   342 device_context.cc:320] Please NOTE: device: 1, GPU Compute Capability: 8.0, Driver API Version: 11.0, Runtime API Version: 11.0
W1224 10:26:24.744298   342 device_context.cc:330] device: 1, cuDNN Version: 8.0.
**这是endpoints的日志**
PADDLE_TRAINER_ENDPOINTS: 
127.0.0.1:60001
127.0.0.1:60849

**Comment by sandyhouse** [comment]
一、是否使用fleetx数据下载功能；
二、请看下60001端口是被什么进程占用

**Comment by duanyaohui** [comment]
您好，目前并没有使用fleetx数据下载功能，检查了下60001端口未被占用，是要在执行训练的代码里检查吗？

**Comment by gongweibao** [comment]
这段日志是不是卡2的？怀疑卡2的进程是不是已经退出了。
```
grep: warning: GREP_OPTIONS is deprecated; please use an alias or scriptTraceback (most recent call last):
  File "tools/train.py", line 29, in <module>
    from ppcls.data import Reader
  File "/test01/PaddleClas-dygraph/ppcls/__init__.py", line 19, in <module>
    from .data import *
  File "/test01/PaddleClas-dygraph/ppcls/data/__init__.py", line 15, in <module>
    from .reader import Reader
  File "/test01/PaddleClas-dygraph/ppcls/data/reader.py", line 22, in <module>
    from . import imaug
  File "/test01/PaddleClas-dygraph/ppcls/data/imaug/__init__.py", line 23, in <module>
    from .operators import DecodeImage
  File "/test01/PaddleClas-dygraph/ppcls/data/imaug/operators.py", line 25, in <module>
    import cv2
ImportError: No module named 'cv2'
grep: warning: GREP_OPTIONS is deprecated; please use an alias or script
Traceback (most recent call last):
  File "tools/train.py", line 29, in <module>
    from ppcls.data import Reader
  File "/test01/PaddleClas-dygraph/ppcls/__init__.py", line 19, in <module>
    from .data import *
  File "/test01/PaddleClas-dygraph/ppcls/data/__init__.py", line 15, in <module>
    from .reader import Reader
  File "/test01/PaddleClas-dygraph/ppcls/data/reader.py", line 24, in <module>
    from ppcls.utils import logger
  File "/test01/PaddleClas-dygraph/ppcls/utils/__init__.py", line 17, in <module>
    from . import model_zoo
  File "/test01/PaddleClas-dygraph/ppcls/utils/model_zoo.py", line 23, in <module>
    import tqdm
ImportError: No module named 'tqdm'
```

能否看看60001这个端口已经打开？是被卡2的进程打开的？

**Comment by duanyaohui** [comment]
您发的那个是之前的log文件，请看我最新的那个，我用的是动态图版本的代码，我看分布式用的是paddle.distributed，并不是fleet，会不会是这个的问题啊？

**Comment by sandyhouse** [comment]
> 您好，目前并没有使用fleetx数据下载功能，检查了下60001端口未被占用，是要在执行训练的代码里检查吗？

是的，在训练过程中检查，而不是退出训练后检查。

**Comment by duanyaohui** [comment]
但是每次训练我看端口号都会改变啊，这个如何固定呢？还是设置一个范围，自己去扫那样？

**Comment by gongweibao** [comment]
嗯。每次都是寻找的没有被其他的程序占用的端口。每次都是同样的问题？

**Comment by duanyaohui** [comment]
是啊，每次都是报OSError: [Errno 98] Address already in use

**Comment by duanyaohui** [comment]
目前是在浪潮的AIStation下运行的 会不会和这个有关系？

**Comment by acelib02** [comment]
如果涉及到开发环境的端口配置，现在AIStation的开发环境-更多配置里可以映射端口，但会随机进行映射。

是否paddle需要将端口进行固定映射，不能进行更改？


----- 原始邮件 -----
发件人：Yaohui Duan <notifications@github.com>
收件人：PaddlePaddle/Paddle <Paddle@noreply.github.com>
抄送人：acelib02 <libaoran_89@sina.com>,  Comment <comment@noreply.github.com>
主题：Re:_[PaddlePaddle/Paddle]_cuda11上多卡训练报错_(#29847)
日期：2020年12月29日 14点33分



目前是在浪潮的AIStation下运行的 会不会和这个有关系？

**Comment by sandyhouse** [comment]
可以试试最新develop分支代码，已经解决了这个问题。

**Comment by duanyaohui** [comment]
develop分支是哪个？我看只有master，dygraph, release/2.0-rc1和2.0-beta四个分支，是release/2.0-rc1吗？

**Comment by sandyhouse** [comment]
develop分支指的是Paddle框架：https://github.com/PaddlePaddle/Paddle

**Comment by duanyaohui** [comment]
这个是1.8.5版本的吧？目前1.8.5版本的paddle好像不支持cuda11吧？

**Comment by gongweibao** [comment]
cuda11向上兼容。

**Comment by duanyaohui** [comment]
我之前在cuda11上用过1.8.5版本的 一直报错 后来换成2.0.0就好了
