### ISSUE TITLE
paddle没找到实现稀疏矩阵的办法

### ISSUE THREAD

**Issue by L-Ymeng** [PaddlePaddle/Paddle#29852]
我的模型需要一个18W乘18W的二维矩阵，但其中只有66W的数据，所以这个矩阵很稀疏，想问paddle有没有办法实现这样的矩阵
我在使用TensorFlow的时候，有SparseTensor方法能够实现，现在想用paddle试试，但是没找到。

**Comment by bjjwwang** [comment]
很可能没有，我先记录下这个问题，明天更新回复。

**Comment by L-Ymeng** [comment]
好的
