### ISSUE TITLE
paddlepaddle的Pool2D向下取整问题

### ISSUE THREAD

**Issue by Tridu33** [PaddlePaddle/Paddle#29850]
[具体写在百度ai studio论坛上面](https://ai.baidu.com/forum/topic/show/980806)

**Comment by bjjwwang** [comment]
如果是动态图的话 https://www.paddlepaddle.org.cn/documentation/docs/zh/2.0-rc1/api/paddle/fluid/dygraph/Pool2D_cn.html#pool2d 
静态图 https://www.paddlepaddle.org.cn/documentation/docs/zh/2.0-rc1/api/paddle/fluid/layers/pool2d_cn.html#pool2d
这里应该是给出了ceil_mode
