### ISSUE TITLE
paddle 2.0 版本安装问题 

### ISSUE THREAD

**Issue by xialei2821212670** [PaddlePaddle/Paddle#29868]
![image](https://user-images.githubusercontent.com/57654726/103050152-93316700-45ce-11eb-865f-bbc31d871cad.png)

![image](https://user-images.githubusercontent.com/57654726/103050184-a93f2780-45ce-11eb-9248-029465c5c9c1.png)
![image](https://user-images.githubusercontent.com/57654726/103050200-b9570700-45ce-11eb-83c5-91e75a86beb7.png)
![image](https://user-images.githubusercontent.com/57654726/103050224-cd9b0400-45ce-11eb-8b5b-ebf174f97a4c.png)
采用conda ,安装出现错误，C++ 运行库安装。已经尝试多次。

**Comment by zhwesky2010** [comment]
@xialei2821212670 麻烦先安装下这个试试 https://www.microsoft.com/en-us/download/details.aspx?id=48145

**Comment by xialei2821212670** [comment]
> @ xialei2821212670麻烦先安装下这个试试[https://www.microsoft.com/zh-cn/download/details.aspx?id=48145](https://www.microsoft.com/en-us/download/details.aspx?id=48145)

你好，我安装过，刚尝试重新安装，还是出现问题。

**Comment by zhwesky2010** [comment]
@xialei2821212670 确保这个vs的已经成功安装好了吧，这个是DLL加载时加载时表示找不到，一般可能是加载路径不对，或者是就没有安装这个dll，但是python不会告诉是哪个没找到，所以直接凭肉眼不太好看。可以先在终端里设置下环境变量 set GLOG_v=5吗？另外，pip安装是不是也会有这个问题呢

**Comment by xialei2821212670** [comment]
> @ xialei2821212670确保这个vs的已经成功安装好了吧，这个是DLL加载时加载时表示找到，一般可能是加载路径不对，或者是就没有安装这个dll，但是python不会告诉是其中没找到，所以直接凭肉眼不太好看。可以先在终端里设置下环境变量set GLOG_v = 5吗？另外，pip安装是不是也会有这个问题呢
是在系统里设置环境变量？pip 安装也是这个问题

**Comment by xialei2821212670** [comment]
> @ xialei2821212670确保这个vs的已经成功安装好了吧，这个是DLL加载时加载时表示找到，一般可能是加载路径不对，或者是就没有安装这个dll，但是python不会告诉是其中没找到，所以直接凭肉眼不太好看。可以先在终端里设置下环境变量set GLOG_v = 5吗？另外，pip安装是不是也会有这个问题呢
![Uploading image.png…]()
是这样？

**Comment by zhwesky2010** [comment]
@xialei2821212670 您好，我这边图片加载不到

**Comment by xialei2821212670** [comment]
你好，
![image](https://user-images.githubusercontent.com/57654726/103251498-d36c5d00-49b3-11eb-85bb-5380815db712.png)
是这？

**Comment by xialei2821212670** [comment]
> @ xialei2821212670您好，我这边图片加载不到
![image](https://user-images.githubusercontent.com/57654726/103253531-95276b80-49bc-11eb-899b-95d4fe223778.png)
.是这样操作？

**Comment by zhwesky2010** [comment]
@xialei2821212670 您好，原生python安装也会出现这个问题吗，可能是anaconda与原生的python3.8的加载逻辑不同，能否看下不用anaconda的情况呢

**Comment by xialei2821212670** [comment]
> @ xialei2821212670您好，原生python安装也会出现这个问题吗，可能是anaconda与原生的python3.8的加载逻辑不同，能否看下不用anaconda的情况呢
你好，我刚刚尝试了一下，原生的python3.8.5，他通过了验证，我很想知道是anconda有些问题?还是习惯了conda的安装和管理
