### ISSUE TITLE
高层接口 paddle.model报错

### ISSUE THREAD

**Issue by Darki-luo** [PaddlePaddle/Paddle#29863]
在使用高层接口中读取dataset 计算损失函数时报错，提示维度不同，
ValueError: (InvalidArgument) Input(Logits) and Input(Label) should in same shape in dimensions except axis.
  [Hint: Expected logits_dims[i] == labels_dims[i], but received logits_dims[i]:2 != labels_dims[i]:1.] (at /paddle/paddle/fluid/operators/softmax_with_cross_entropy_op.cc:145)
  [Hint: If you need C++ stacktraces for debugging, please set `FLAGS_call_stack_level=2`.]
  [operator < softmax_with_cross_entropy > error]

构建的dataset 的输出是 iamge, label  (shape是 CHW）shape 是要变成 HWC吗，我看示例的dataset是HWC

print(im.shape) # [3, 256, 256]
print(la.shape)  #(1, 256, 256)

model.fit(train_dataset,
        val_dataset,
        epochs=10,
        log_freq=1,
        batch_size=4,
        verbose=1,
)

The loss value printed in the log is the current step, and the metric is the average value of previous step.
Epoch 1/10
---------------------------------------------------------------------------ValueError                                Traceback (most recent call last)<ipython-input-78-b55e2a791d20> in <module>
      4         log_freq=1,
      5         batch_size=4,
----> 6         verbose=1,
      7 
      8 )
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/hapi/model.py in fit(self, train_data, eval_data, batch_size, epochs, eval_freq, log_freq, save_dir, save_freq, verbose, drop_last, shuffle, num_workers, callbacks)
   1490         for epoch in range(epochs):
   1491             cbks.on_epoch_begin(epoch)
-> 1492             logs = self._run_one_epoch(train_loader, cbks, 'train')
   1493             cbks.on_epoch_end(epoch, logs)
   1494 
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/hapi/model.py in _run_one_epoch(self, data_loader, callbacks, mode, logs)
   1797             if mode != 'predict':
   1798                 outs = getattr(self, mode + '_batch')(data[:len(self._inputs)],
-> 1799                                                       data[len(self._inputs):])
   1800                 if self._metrics and self._loss:
   1801                     metrics = [[l[0] for l in outs[0]]]
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/hapi/model.py in train_batch(self, inputs, labels)
    938               print(loss)
    939         """
--> 940         loss = self._adapter.train_batch(inputs, labels)
    941         if fluid.in_dygraph_mode() and self._input_info is None:
    942             self._update_inputs()
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/hapi/model.py in train_batch(self, inputs, labels)
    654                 * [to_variable(x) for x in inputs])
    655 
--> 656         losses = self.model._loss(*(to_list(outputs) + labels))
    657         losses = to_list(losses)
    658         final_loss = fluid.layers.sum(losses)
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py in __call__(self, *inputs, **kwargs)
    882                 self._built = True
    883 
--> 884             outputs = self.forward(*inputs, **kwargs)
    885 
    886             for forward_post_hook in self._forward_post_hooks.values():
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/nn/layer/loss.py in forward(self, input, label)
    247             soft_label=self.soft_label,
    248             axis=self.axis,
--> 249             name=self.name)
    250 
    251         return ret
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/nn/functional/loss.py in cross_entropy(input, label, weight, ignore_index, reduction, soft_label, axis, name)
   1218             soft_label=soft_label,
   1219             ignore_index=ignore_index,
-> 1220             axis=axis)
   1221         if weight is not None:
   1222             weight_gather = core.ops.gather_nd(weight, label)  #trans to sample
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/layers/loss.py in softmax_with_cross_entropy(logits, label, soft_label, ignore_index, numeric_stable_mode, return_softmax, axis)
   1262             logits, label, 'soft_label', soft_label, 'ignore_index',
   1263             ignore_index, 'numeric_stable_mode', numeric_stable_mode, 'axis',
-> 1264             axis)
   1265         if not return_softmax:
   1266             return loss
ValueError: (InvalidArgument) Input(Logits) and Input(Label) should in same shape in dimensions except axis.
  [Hint: Expected logits_dims[i] == labels_dims[i], but received logits_dims[i]:2 != labels_dims[i]:1.] (at /paddle/paddle/fluid/operators/softmax_with_cross_entropy_op.cc:145)
  [Hint: If you need C++ stacktraces for debugging, please set `FLAGS_call_stack_level=2`.]
  [operator < softmax_with_cross_entropy > error]

**Comment by laowang-7** [comment]
> Since you haven't replied for more than a year, we have closed this issue/pr. If the problem is not solved or there is a follow-up one, please reopen it at any time and we will continue to follow up. 由于您超过一年未回复，我们将关闭这个issue/pr。 若问题未解决或有后续问题，请随时重新打开，我们会继续跟进。

你好我也遇到了同样的问题，请问怎么解决

**Comment by lllulll** [comment]
我也遇到了这个问题，怎么解决呢？

**Comment by clSpider** [comment]
我也遇到了这个问题，怎么解决呢？ 而且是在第一次训练内存超过报错之后 第二次运行的时候报错的。

[2023-03-19 23:57:58,381] [ WARNING] - Some weights of ErnieForTokenClassification were not initialized from the model checkpoint at ernie-3.0-medium-zh and are newly initialized: ['classifier.weight', 'ernie.pooler.dense.bias', 'ernie.pooler.dense.weight', 'classifier.bias']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
[TRAIN] Epoch:0 - Step:1 - Loss: 1.753421
[TRAIN] Epoch:0 - Step:2 - Loss: 1.290716
Traceback (most recent call last):
  File "G:/python_project/demo/PaddleNLP/examples/information_extraction/waybill_ie/run_ernie.py", line 149, in <module>
    loss = paddle.mean(loss_fn(logits, labels))
  File "D:\Anaconda\envs\paddle\lib\site-packages\paddle\fluid\dygraph\layers.py", line 930, in __call__
    return self._dygraph_call_func(*inputs, **kwargs)
  File "D:\Anaconda\envs\paddle\lib\site-packages\paddle\fluid\dygraph\layers.py", line 915, in _dygraph_call_func
    outputs = self.forward(*inputs, **kwargs)
  File "D:\Anaconda\envs\paddle\lib\site-packages\paddle\nn\layer\loss.py", line 397, in forward
    ret = paddle.nn.functional.cross_entropy(
  File "D:\Anaconda\envs\paddle\lib\site-packages\paddle\nn\functional\loss.py", line 1735, in cross_entropy
    _, out = _C_ops.softmax_with_cross_entropy(
ValueError: (InvalidArgument) Input(Logits) and Input(Label) should in same shape in dimensions except axis.
  [Hint: Expected logits_dims[i] == labels_dims[i], but received logits_dims[i]:84 != labels_dims[i]:85.] (at ..\paddle/fluid/operators/softmax_with_cross_entropy_op.cc:164)
  [operator < softmax_with_cross_entropy > error]
