### ISSUE TITLE
文档中示例的疑惑

### ISSUE THREAD

**Issue by jhcgt4869** [PaddlePaddle/Paddle#29860]
地址：https://www.paddlepaddle.org.cn/documentation/docs/zh/2.0-rc1/guides/02_paddle2.0_develop/02_data_load_cn.html

![image](https://user-images.githubusercontent.com/61859193/102982372-6127f280-4545-11eb-800c-aa41ac53e30e.png)
这里的结果是怎么的出来的，这个`train_dataset`哪里来的，上面导入的也应该是`train_dataset2`或`val_dataset2`这里莫名其妙就出现了。

而且这个文档里面的代码不能够一键复制了，结果却可以？？？
不便于借鉴和使用，换句话说，我一键复制你的结果有什么用嘛？我不要代码要结果，这个地方的设置根据有点“反人类”

以上为个人认知，如果有理解错误表示抱歉，各位维护人员辛苦！

**Comment by bjjwwang** [comment]
好 感谢指出问题。 我理解应该是几段代码是有上下文关系的， 在第一段代码中是有`train_dataset`。如果需要复现的话，可以把上下文都摘进来。然后print你需要的部分就好。

**Comment by jhcgt4869** [comment]
看了一下确实是上面手写识别的数据，但是感觉好奇怪，能不能多加一句注释（说好的是外部数据，最后有用自带的拿来演示，好奇怪）
