### ISSUE TITLE
2.0rc版本如何设置随机数种子

### ISSUE THREAD

**Issue by HXia-XXL** [PaddlePaddle/Paddle#29875]
请问2.0rc版本怎么设置随机数种子

**Comment by hong19860320** [comment]
可以使用paddle.framework.seed(seed)，具体文档可以参考 https://www.paddlepaddle.org.cn/documentation/docs/zh/2.0-rc1/api/paddle/framework/random/seed_cn.html#seed

**Comment by HXia-XXL** [comment]
感谢！
