### ISSUE TITLE
paddle 2.0 exe.run(fluid.default_startup_program())  使用1.8预测报错

### ISSUE THREAD

**Issue by wa3926** [PaddlePaddle/Paddle#29871]
File "F:/workspacesvue/workspace/znfz_zx2020/mypaddle/predictZbdw.py", line 22, in predict
    exe.run(fluid.default_startup_program())
  File "F:\Anaconda3\lib\site-packages\paddle\fluid\executor.py", line 1107, in run
    six.reraise(*sys.exc_info())
  File "F:\Anaconda3\lib\site-packages\six.py", line 703, in reraise
    raise value
  File "F:\Anaconda3\lib\site-packages\paddle\fluid\executor.py", line 1105, in run
    return_merged=return_merged)
  File "F:\Anaconda3\lib\site-packages\paddle\fluid\executor.py", line 1229, in _run_impl
    use_program_cache=use_program_cache)
  File "F:\Anaconda3\lib\site-packages\paddle\fluid\executor.py", line 1318, in _run_program
    arr = scope.find_var(fetch_var_name).get_fetch_list()
AttributeError: 'NoneType' object has no attribute 'get_fetch_list'

预测的1.8版本训练的 cnn 文本分类模型     上面是使用2.0预测报错  下面是预测部分代码  

def predict(content):
    # 用训练好的模型进行预测并输出预测结果
    # 创建执行器
    place = fluid.CPUPlace()
    exe = fluid.Executor(place)
    exe.run(fluid.default_startup_program())
    save_path=basepath+"infer_model/"
    # 从模型中获取预测程序、输入数据名称列表、分类器
    [infer_program, feeded_var_names, target_var] = fluid.io.load_inference_model(dirname=save_path, executor=exe)
    data = []
    data.append(get_data(replaceStr_key(content)))

    # 获取每句话的单词数量
    base_shape = [[len(c) for c in data]]

    # 生成预测数据
    tensor_words = fluid.create_lod_tensor(data, base_shape, place)
    # print("feeded_var_names[0]",feeded_var_names[0])
    # print("tensor_words",tensor_words)
    #print("target_var",target_var)
    # 执行预测
    result = exe.run(program=infer_program,
                     feed={feeded_var_names[0]: tensor_words},
                     fetch_list=target_var)

**Comment by hong19860320** [comment]
你是厂内用户吗？如果不是，建议给下完整的复现问题的脚本哈？

**Comment by wa3926** [comment]
@hong19860320  #coding:utf-8
#文本分类
import sys
import os
curPath = os.path.abspath(os.path.dirname(__file__))
rootPath = os.path.abspath(os.path.dirname(curPath)+os.path.sep+".")
sys.path.append(rootPath)
# 导入必要的包
import numpy as np
import paddle.fluid as fluid
from util.oracle_util import get_connection
from util.str_util import replaceStr_key,get_propertiesvalue
syst=get_propertiesvalue("system")
basepath="D://paddle//zx//zndw1202//"
if syst=='0':
    basepath="/ai/nlp/zhzx/data/zndw1202/"
def predict(content):
    # 用训练好的模型进行预测并输出预测结果
    # 创建执行器
    place = fluid.CPUPlace()
    exe = fluid.Executor(place)
    exe.run(fluid.default_startup_program())
    save_path=basepath+"infer_model/"
    # 从模型中获取预测程序、输入数据名称列表、分类器
    [infer_program, feeded_var_names, target_var] = fluid.io.load_inference_model(dirname=save_path, executor=exe)
    data = []
    # 获取图片数据
    # dbconn = get_connection()
    # cur = dbconn.cursor()
    # sql="select id,content,zbdwn from zh_zx_tab t where id='019baa72-8281-4de7-8231-5291101b3fe6'"
    # cur.execute(sql)
    #
    # for result in cur:
    #     print("str(result[1])",str(result[1]))
    #     data.append(get_data(replaceStr_key(str(result[1]))))
    # cur.close()
    # dbconn.close()
    #print("data",data)
    # data1 = get_data('市民来电反映：河畔花城停车费问题，与市民核实信息，市民不知是谁收取费用，有无收费指示牌。已建议市民核实后来电反映，市民知晓办结。')
    # data2 = get_data('刘先生来电反映：1月11日16点在帝景豪庭南门向东20米处的理发店（孙老师的店）花费50元理发，其表示费用由原价30元涨到50元，对费用涨价较多不认可，商家表示过年均会涨价，来电核实过年期间涨价较多是否合理。')
    data.append(get_data(replaceStr_key(content)))
    # data.append(data2)

    # 获取每句话的单词数量
    base_shape = [[len(c) for c in data]]

    # 生成预测数据
    tensor_words = fluid.create_lod_tensor(data, base_shape, place)
    # print("feeded_var_names[0]",feeded_var_names[0])
    # print("tensor_words",tensor_words)
    #print("target_var",target_var)
    # 执行预测
    result = exe.run(program=infer_program,
                     feed={feeded_var_names[0]: tensor_words},
                     fetch_list=target_var)

    # 分类名称
    dic={'市金融监管局':'0','市财政局':'1','市水利局':'2','市生态环境局':'3','市委宣传部':'4','市商务局':'5',
         '市市场监管局':'6','市自然资源和规划局':'7','市人社局':'8','市民政局':'9','市文旅局':'10','市住建局':'11',
         '市交通局':'12','市卫健委':'13','市城管局':'14','市教育局':'15','市公安局':'16','市发改委':'17',
         '市工信局':'18','市农业农村局':'19'
         }
    names =list(dic.keys())

    # 获取结果概率最大的label
    # for a in result[0][0]:
    #     a='{:.5f}'.format(a)
    #     print("a",a)
    res=[]
    for i in range(len(data)):
        lab = np.argsort(result)[0][i][-1]
        lab2 = np.argsort(result)[0][i][-2]
        lab3 = np.argsort(result)[0][i][-3]
        return {names[lab]:str(result[0][i][lab]),names[lab2]:str(result[0][i][lab2]),names[lab3]:str(result[0][i][lab3])}
        # print('预测结果标签为：%d， 名称为：%s， 概率为：%f' % (lab, names[lab], result[0][i][lab]))
        # print('预测结果标签为：%d， 名称为：%s， 概率为：%f' % (lab2, names[lab2], result[0][i][lab2]))
        # print('预测结果标签为：%d， 名称为：%s， 概率为：%f' % (lab3, names[lab3], result[0][i][lab3]))

# 获取数据
def get_data(sentence):
    # 读取数据字典
    with open(basepath+'dict_txt.txt', 'r', encoding='utf-8') as f_data:
        dict_txt = eval(f_data.readlines()[0])
    dict_txt = dict(dict_txt)
    # 把字符串数据转换成列表数据
    keys = dict_txt.keys()
    data = []
    for s in sentence:
        # 判断是否存在未知字符
        if not s in keys:
            s = '<unk>'
        data.append(int(dict_txt[s]))
    return np.array(data, dtype = np.int64)

if __name__ == '__main__':
    print(predict('城市安全是最大的民生。党的十九大报告提出：加强水利、铁路、公路、水运、航空、管道、电网、信息、物流等基础设施网络建设。习近平总书记提出健全国家安全体系，加强国家安全法治保障，提高防范和抵御安全风险能力。中共中央办公厅、国务院办公厅印发《关于推进城市安全发展的意见》，提出加强城市安全体系建设的路径和具体措施。目前，随着全区经济快速发展，城区道路交通路网逐步健全完善。'))

**Comment by wa3926** [comment]
@hong19860320  就是执行预测报错了  之前1.8是好的   最近用到2.0的一个模型 就升级了   现在想知道2.0的预测这边应该怎么写

**Comment by hong19860320** [comment]
在程序最开始调用下paddle.enable_static() 试试

**Comment by wa3926** [comment]
@hong19860320  可以了  谢谢  是新版本开始 一定要声明只用 静态图是吗

**Comment by hong19860320** [comment]
> @hong19860320 可以了 谢谢 是新版本开始 一定要声明只用 静态图是吗

是的，2.0默认使用动态图哦
