### ISSUE TITLE
动态图导出预测模型CPU下开启IR优化结果出错

### ISSUE THREAD

**Issue by ggyuan** [PaddlePaddle/Paddle#29886]
版本、环境信息：
1）1.8.5
2）CPU: Intel(R) Xeon(R) Gold 6271C CPU @ 2.60GHz
3）系统环境CentOS Linux release 7.5.1804 (Core), Python 3.7.6
问题描述:
![image](https://user-images.githubusercontent.com/5819753/103075722-28505200-4607-11eb-8322-b31705f328da.png)

![image](https://user-images.githubusercontent.com/5819753/103075451-98aaa380-4606-11eb-82cf-c3ce78e41c7b.png)
相同模型，在config中打开和关闭switch_ir_optim结果有diff，打开时只有batch中第一个结果正确

复现信息：
内部提出，请如流上联系古桂元，提供单测文件

**Comment by hong19860320** [comment]
麻烦志强@DannyIsFunny帮忙看下哈，感觉是某个op fuse pass有bug，这个最好@ggyuan 在厂内开个卡片，把复现环境放下哦

**Comment by ggyuan** [comment]
> 麻烦志强@DannyIsFunny帮忙看下哈，感觉是某个op fuse pass有bug，这个最好@ggyuan 在厂内开个卡片，把复现环境放下哦

已经在厂内建好卡片了，复现环境也放上去了

**Comment by hong19860320** [comment]
> > 麻烦志强@DannyIsFunny帮忙看下哈，感觉是某个op fuse pass有bug，这个最好@ggyuan 在厂内开个卡片，把复现环境放下哦
> 
> 已经在厂内建好卡片了，复现环境也放上去了

好的，我已经看到有预测的同学在跟了
