### ISSUE TITLE
windows编译MD版DLL问题

### ISSUE THREAD

**Issue by fengkuangxiaxia** [PaddlePaddle/Paddle#29884]
- 版本、环境信息
1）PaddlePaddle版本：1.8.5
2）CPU/GPU：CPU
3）系统环境：Win7

- 官方文档编译说明错误

CUDA_TOOKIT_ROOT_DIR应该是CUDA_TOOKIT_ROOT_DIR才对

https://www.paddlepaddle.org.cn/documentation/docs/zh/advanced_guide/inference_deployment/inference/windows_cpp_inference.html

![image](https://user-images.githubusercontent.com/3814174/103072971-a9a4e600-4601-11eb-8f4f-dbc088b7581a.png)

- cryptopp.cmake导致不能编译MD版本

cryptopp.cmake中强制将MD改成了MT，而不像主CMakeLists.txt中根据参数指定MD或MT

**Comment by hong19860320** [comment]
官网那个问题是不是说拼写少了个L啊？CUDA_TOOLKIT_ROOT_DIR

**Comment by zhwesky2010** [comment]
@fengkuangxiaxia  cryptopp.cmake这个问题在develop上应该修好了，文档这里是少了个字母，应该 `CUDA_TOOLKIT_ROOT_DIR` ，我们后续会修复 @jiweibo
