### ISSUE TITLE
Paddle运行过程中每个Pass只跑了一个batch

### ISSUE THREAD

**Issue by youan1** [PaddlePaddle/Paddle#2989]
RT，python运行过程中每个pass值跑了一个batch就结束了，在代码里我们期望每过10个batch就打印出信息，但是本地调试每个pass只打印了一个 batch,就是batch 0。相应的脚本已经上传。
[script_test_folder.zip](https://github.com/PaddlePaddle/Paddle/files/1161590/script_test_folder.zip)

            if event.batch_id % 10 == 0:
                print "\nPass %d, Batch %d, Cost %f, %s" % (
                    event.pass_id, event.batch_id, event.cost, event.metrics)

**Comment by livc** [comment]
你上传的脚本中写的是每100个batch打印一次，你设置的batch size是64，也就是每6400条数据打印一次。训练数据有9814行，9814/6400=1，所以只会打印一次。

**Comment by youan1** [comment]
嗯，1) 按照上面的脚本，也应该打印两次 batch 0一次，batch 100的时候打印一次， 2） 哪怕我把if event.batch_id % 5 == 0: 也还是只打印batch 0 的，麻烦再检查一下

**Comment by livc** [comment]
你的reader使用了paddle.v2.reader.firstn(reader, n)，其用法请参考：http://doc.paddlepaddle.org/doc/api/v2/data.html 。所以log打不出来。
