### ISSUE TITLE
建议paddle.vision和paddleseg整合

### ISSUE THREAD

**Issue by Darki-luo** [PaddlePaddle/Paddle#29895]
最近发现paddleseg也可以用pip安装，调用包，和高层api接口paddle.vision很像，但相互调用有些问题，比如直接用paddle.Model（）调用paddleseg的miou计算等还是会有一些问题，希望可以考虑整合一下这个接口，直接拆出来给paddleseg，做一些兼容的适配

**Comment by wangchaochaohu** [comment]
您好 这边会慎重考虑你的意见进行反馈
