### ISSUE TITLE
centos7编译错误, 错误相关信息：c++: internal compiler error: 已杀死 (program cc1plus)

### ISSUE THREAD

**Issue by Cerdore** [PaddlePaddle/Paddle#29908]
- 版本、环境信息：
    1）PaddlePaddle版本：1.8
    2）CPU：Intel(R) Xeon(R) Silver 4110 CPU @ 2.10GHz
    3）GPU：Tesla P40，CUDA10.1 和CUDNN7
    4）系统环境：Centos 7、Python 3.6.8 
    5）其他配置： gcc-7.5.0, cmake-3.19.2
    6）内存大小：
![image](https://user-images.githubusercontent.com/24353799/103125881-847aab00-46c7-11eb-9b10-4660d830ccce.png)

- 安装方式信息：
1）本地编译：
------cmake命令
cmake .. -DPY_VERSION=3.6.8 -DPYTHON_INCLUDE_DIR=/usr/inlude/python3.6m -DPYTHON_LIBRARY=/usr/lib64/libpython3.so -DWITH_GPU=ON -DWITH_TESTING=OFF -DCMAKE_BUILD_TYPE=Release
------编译命令
make -j$(nproc)   【本机为 make -j32】。

-----尝试方案：
1） 在出错后，曾尝试删除 build文件夹重新cmake并使用make -j4 /  make -j2；也曾尝试增加swap空间大小。已经加到了如上所示大小，swap大概8G，内存大概156G。
2）修改gcc 版本， 之前为 4.8.5 ， 现修改为gcc7.5.0

- 复现信息：如为报错，请给出复现环境、复现步骤
- 问题描述：请详细描述您的问题，同步贴出报错信息、日志/代码关键片段

报错信息：

`[ 37%] Building CXX object src/cpu/CMakeFiles/dnnl_cpu.dir/gemm/s8x8s32/jit_avx2_u8_copy_an_kern.cpp.o
c++: internal compiler error: 已杀死 (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <https://gcc.gnu.org/bugs/> for instructions.
make[5]: *** [src/cpu/CMakeFiles/dnnl_cpu.dir/gemm/s8x8s32/jit_avx2_u8_copy_an_kern.cpp.o] 错误 4
make[5]: *** 正在等待未完成的任务....
c++: internal compiler error: 已杀死 (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <https://gcc.gnu.org/bugs/> for instructions.
make[5]: *** [CMakeFiles/libprotoc.dir/home/xschen/Paddle/build/third_party/protobuf/src/extern_protobuf/src/google/protobuf/compiler/cpp/cpp_map_field.cc.o] 错误 4
make[5]: *** 正在等待未完成的任务....
c++: internal compiler error: 已杀死 (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <https://gcc.gnu.org/bugs/> for instructions.
make[5]: *** [CMakeFiles/libprotoc.dir/home/xschen/Paddle/build/third_party/protobuf/src/extern_protobuf/src/google/protobuf/compiler/cpp/cpp_helpers.cc.o] 错误 4
[ 57%] Building CXX object CMakeFiles/libprotoc.dir/home/xschen/Paddle/build/third_party/protobuf/src/extern_protobuf/src/google/protobuf/compiler/cpp/cpp_message.cc.o
c++: internal compiler error: 已杀死 (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <https://gcc.gnu.org/bugs/> for instructions.
make[5]: *** [CMakeFiles/libprotoc.dir/home/xschen/Paddle/build/third_party/protobuf/src/extern_protobuf/src/google/protobuf/compiler/cpp/cpp_field.cc.o] 错误 4
c++: internal compiler error: 已杀死 (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <https://gcc.gnu.org/bugs/> for instructions.
make[5]: *** [CMakeFiles/libprotoc.dir/home/xschen/Paddle/build/third_party/protobuf/src/extern_protobuf/src/google/protobuf/compiler/cpp/cpp_generator.cc.o] 错误 4
c++: internal compiler error: 已杀死 (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <https://gcc.gnu.org/bugs/> for instructions.
make[5]: *** [CMakeFiles/libprotoc.dir/home/xschen/Paddle/build/third_party/protobuf/src/extern_protobuf/src/google/protobuf/compiler/cpp/cpp_file.cc.o] 错误 4
c++: internal compiler error: 已杀死 (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <https://gcc.gnu.org/bugs/> for instructions.
make[5]: *** [src/cpu/CMakeFiles/dnnl_cpu.dir/gemm/s8x8s32/jit_avx2_gemm_s8u8s32_kern.cpp.o] 错误 4
c++: internal compiler error: 已杀死 (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <https://gcc.gnu.org/bugs/> for instructions.
make[5]: *** [src/cpu/CMakeFiles/dnnl_cpu.dir/gemm/f32/jit_sse41_kernel_sgemm_kern.cpp.o] 错误 4
c++: internal compiler error: 已杀死 (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <https://gcc.gnu.org/bugs/> for instructions.
make[5]: *** [src/cpu/CMakeFiles/dnnl_cpu.dir/gemm/gemm_driver.cpp.o] 错误 4
c++: internal compiler error: 已杀死 (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <https://gcc.gnu.org/bugs/> for instructions.
make[5]: *** [src/cpu/CMakeFiles/dnnl_cpu.dir/gemm/gemm_info.cpp.o] 错误 4
c++: internal compiler error: 已杀死 (program cc1plus)
c++: internal compiler error: 已杀死 (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <https://gcc.gnu.org/bugs/> for instructions.
Please submit a full bug report,
with preprocessed source if appropriate.
See <https://gcc.gnu.org/bugs/> for instructions.
make[5]: *** [src/cpu/CMakeFiles/dnnl_cpu.dir/gemm/f32/ref_gemm_f32.cpp.o] 错误 4
make[5]: *** [src/cpu/CMakeFiles/dnnl_cpu.dir/gemm/f32/jit_sse41_kernel_b0_sgemm_kern.cpp.o] 错误 4
c++: internal compiler error: 已杀死 (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <https://gcc.gnu.org/bugs/> for instructions.
make[5]: *** [src/cpu/CMakeFiles/dnnl_cpu.dir/gemm/f32/jit_avx_kernel_b0_sgemm_kern.cpp.o] 错误 4
c++: internal compiler error: 已杀死 (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <https://gcc.gnu.org/bugs/> for instructions.
c++: internal compiler error: 已杀死 (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <https://gcc.gnu.org/bugs/> for instructions.
make[5]: *** [src/cpu/CMakeFiles/dnnl_cpu.dir/gemm/f32/jit_sse41_f32_copy_bt_kern.cpp.o] 错误 4
c++: internal compiler error: 已杀死 (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <https://gcc.gnu.org/bugs/> for instructions.
make[5]: *** [src/cpu/CMakeFiles/dnnl_cpu.dir/gemm/f32/jit_sse41_f32_copy_bn_kern.cpp.o] 错误 4
c++: internal compiler error: 已杀死 (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <https://gcc.gnu.org/bugs/> for instructions.
make[5]: *** [src/cpu/CMakeFiles/dnnl_cpu.dir/gemm/f32/jit_avx_f32_copy_at_kern.cpp.o] 错误 4
c++: internal compiler error: 已杀死 (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <https://gcc.gnu.org/bugs/> for instructions.
make[5]: *** [src/cpu/CMakeFiles/dnnl_cpu.dir/gemm/f32/jit_avx_f32_copy_bn_kern.cpp.o] 错误 4
make[5]: *** [src/cpu/CMakeFiles/dnnl_cpu.dir/gemm/f32/jit_avx2_f32_copy_at_kern.cpp.o] 错误 4
c++: internal compiler error: 已杀死 (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <https://gcc.gnu.org/bugs/> for instructions.
make[5]: *** [src/cpu/CMakeFiles/dnnl_cpu.dir/gemm/f32/jit_avx512_core_f32_copy_at_kern.cpp.o] 错误 4
c++: internal compiler error: 已杀死 (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <https://gcc.gnu.org/bugs/> for instructions.
c++: internal compiler error: 已杀死 (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <https://gcc.gnu.org/bugs/> for instructions.
c++: internal compiler error: 已杀死 (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <https://gcc.gnu.org/bugs/> for instructions.
make[5]: *** [src/cpu/CMakeFiles/dnnl_cpu.dir/gemm/f32/jit_avx_gemm_f32.cpp.o] 错误 4
make[5]: *** [src/cpu/CMakeFiles/dnnl_cpu.dir/gemm/f32/jit_sse41_f32_copy_at_kern.cpp.o] 错误 4
make[5]: *** [src/cpu/CMakeFiles/dnnl_cpu.dir/gemm/f32/jit_avx2_f32_copy_an_kern.cpp.o] 错误 4
c++: internal compiler error: 已杀死 (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <https://gcc.gnu.org/bugs/> for instructions.
make[5]: *** [src/cpu/CMakeFiles/dnnl_cpu.dir/gemm/f32/jit_avx_f32_copy_an_kern.cpp.o] 错误 4
c++: internal compiler error: 已杀死 (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <https://gcc.gnu.org/bugs/> for instructions.
c++: internal compiler error: 已杀死 (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <https://gcc.gnu.org/bugs/> for instructions.
c++: internal compiler error: 已杀死 (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <https://gcc.gnu.org/bugs/> for instructions.
make[5]: *** [src/cpu/CMakeFiles/dnnl_cpu.dir/gemm/f32/jit_avx512_core_f32_copy_an_kern.cpp.o] 错误 4
make[5]: *** [src/cpu/CMakeFiles/dnnl_cpu.dir/gemm/f32/jit_avx512_core_f32_copy_bt_kern.cpp.o] 错误 4
c++: internal compiler error: 已杀死 (program cc1plus)
c++: internal compiler error: 已杀死 (program cc1plus)
make[5]: Please submit a full bug report,
with preprocessed source if appropriate.
*** [src/cpu/CMakeFiles/dnnl_cpu.dir/gemm/f32/jit_avx_kernel_sgemm_kern.cpp.o] 错误 4See <https://gcc.gnu.org/bugs/> for instructions.
Please submit a full bug report,
with preprocessed source if appropriate.

See <https://gcc.gnu.org/bugs/> for instructions.
make[5]: *** [src/cpu/CMakeFiles/dnnl_cpu.dir/gemm/bf16/jit_avx512_core_s16_copy_at_kern.cpp.o] 错误 4
make[5]: *** [src/cpu/CMakeFiles/dnnl_cpu.dir/gemm/f32/jit_sse41_f32_copy_an_kern.cpp.o] 错误 4
c++: internal compiler error: 已杀死 (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <https://gcc.gnu.org/bugs/> for instructions.
make[5]: *** [src/common/CMakeFiles/dnnl_common.dir/memory_zero_pad.cpp.o] 错误 4
make[4]: *** [src/common/CMakeFiles/dnnl_common.dir/all] 错误 2
make[4]: *** 正在等待未完成的任务....
c++: internal compiler error: 已杀死 (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <https://gcc.gnu.org/bugs/> for instructions.
make[5]: *** [src/cpu/CMakeFiles/dnnl_cpu.dir/cpu_convolution_list.cpp.o] 错误 4
c++: internal compiler error: 已杀死 (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <https://gcc.gnu.org/bugs/> for instructions.
make[5]: *** [src/cpu/CMakeFiles/dnnl_cpu.dir/cpu_reorder.cpp.o] 错误 4
make[4]: *** [src/cpu/CMakeFiles/dnnl_cpu.dir/all] 错误 2
make[3]: *** [all] 错误 2
make[2]: *** [third_party/mkldnn/src/extern_mkldnn-stamp/extern_mkldnn-build] 错误 2
make[1]: *** [CMakeFiles/extern_mkldnn.dir/all] 错误 2
make[1]: *** 正在等待未完成的任务....
make[4]: *** [CMakeFiles/libprotoc.dir/all] 错误 2
make[3]: *** [all] 错误 2
make[2]: *** [third_party/protobuf/src/extern_protobuf-stamp/extern_protobuf-build] 错误 2
make[1]: *** [CMakeFiles/extern_protobuf.dir/all] 错误 2
make: *** [all] 错误 2
`

**Comment by wangchaochaohu** [comment]
可以使用swapoff -a 命令先释放空间 然后在编译过程中free -m 查看swp空间的使用情况

**Comment by Cerdore** [comment]
> 可以使用swapoff -a 命令先释放空间 然后在编译过程中free -m 查看swp空间的使用情况

你好，我截图中的内存是以M为单位的，刚才描述的有问题。内存是156个G，Swap我本来是4G，然后我又给Swap加了4G。所以感觉不是swap的问题吧。

**Comment by wangchaochaohu** [comment]
尝试下gcc 8.2版本 能不能编译通过

**Comment by tianshuo78520a** [comment]
请问  问题有解决么？

**Comment by Cerdore** [comment]
> 请问 问题有解决么？

不好意思，那个节点宕机了，可能要过几天才能去机房修一下...

**Comment by chccc1994** [comment]
请问，这个问题怎么解决？
