### ISSUE TITLE
flowers dataset in models/image_classification/ : Check failed: (size_t)lbl[i] < dim (102 vs. 102)

### ISSUE THREAD

**Issue by livc** [PaddlePaddle/Paddle#2991]
```
$ python train.py alexnet
I0720 07:55:44.889372   979 Util.cpp:166] commandline:  --use_gpu=False --trainer_count=1
[INFO 2017-07-20 07:55:44,893 layers.py:2428] output for __conv_0__: c = 96, h = 54, w = 54, size = 279936
[INFO 2017-07-20 07:55:44,895 layers.py:2553] output for __pool_0__: c = 96, h = 27, w = 27, size = 69984
[INFO 2017-07-20 07:55:44,897 layers.py:2428] output for __conv_1__: c = 256, h = 27, w = 27, size = 186624
[INFO 2017-07-20 07:55:44,898 layers.py:2553] output for __pool_1__: c = 256, h = 13, w = 13, size = 43264
[INFO 2017-07-20 07:55:44,900 layers.py:2428] output for __conv_2__: c = 384, h = 13, w = 13, size = 64896
[INFO 2017-07-20 07:55:44,902 layers.py:2428] output for __conv_3__: c = 384, h = 13, w = 13, size = 64896
[INFO 2017-07-20 07:55:44,903 layers.py:2428] output for __conv_4__: c = 256, h = 13, w = 13, size = 43264
[INFO 2017-07-20 07:55:44,905 layers.py:2553] output for __pool_2__: c = 256, h = 6, w = 6, size = 9216
I0720 07:55:46.787047   979 GradientMachine.cpp:85] Initing parameters..
I0720 07:55:49.133716   979 GradientMachine.cpp:92] Init parameters done.

Pass 0, Batch 0, Cost 28.005539, {'classification_error_evaluator': 0.9765625}
F0720 07:57:06.771085   979 Matrix.cpp:3286] Check failed: (size_t)lbl[i] < dim (102 vs. 102)
*** Check failure stack trace: ***
    @     0x7f7ee7da345d  google::LogMessage::Fail()
    @     0x7f7ee7da57a8  google::LogMessage::SendToLog()
    @     0x7f7ee7da2f4b  google::LogMessage::Flush()
    @     0x7f7ee7da667e  google::LogMessageFatal::~LogMessageFatal()
    @     0x7f7ee7cbfb65  paddle::CpuMatrix::oneHotCrossEntropy()
    @     0x7f7ee7ab8048  paddle::CostLayer::forward()
    @     0x7f7ee7b1db9e  paddle::NeuralNetwork::forward()
    @     0x7f7ee7d730f0  GradientMachine::forwardBackward()


    image = paddle.layer.data(
    @     0x7f7ee7989284  _wrap_GradientMachine_forwardBackward
    @           0x4cb45e  PyEval_EvalFrameEx
    @           0x4c2765  PyEval_EvalCodeEx
    @           0x4ca8d1  PyEval_EvalFrameEx
    @           0x4c2765  PyEval_EvalCodeEx
    @           0x4ca099  PyEval_EvalFrameEx
    @           0x4c2765  PyEval_EvalCodeEx
    @           0x4ca099  PyEval_EvalFrameEx
    @           0x4c2765  PyEval_EvalCodeEx
    @           0x4ca8d1  PyEval_EvalFrameEx
    @           0x4c2765  PyEval_EvalCodeEx
    @           0x4c2509  PyEval_EvalCode
    @           0x4f1def  (unknown)
    @           0x4ec652  PyRun_FileExFlags
    @           0x4eae31  PyRun_SimpleFileExFlags
    @           0x49e14a  Py_Main
    @     0x7f7f04e4c830  __libc_start_main
    @           0x49d9d9  _start
    @              (nil)  (unknown)
[1]    979 abort      python train.py alexnet
```

**Comment by psersonal-cjy** [comment]
你好 解决了嘛

**Comment by defineconst** [comment]
你好 解决了嘛?谢谢。

[INFO 2018-12-10 14:22:03,694 layers.py:2689] output for pool6_mbox_loc: c = 24, h = 1, w = 1, size = 24
[INFO 2018-12-10 14:22:03,696 layers.py:2689] output for pool6_mbox_conf: c = 12, h = 1, w = 1, size = 12
I1210 14:22:07.396968  2441 GradientMachine.cpp:94] Initing parameters..
I1210 14:22:09.943565  2441 GradientMachine.cpp:101] Init parameters done.
F1210 14:22:13.446383  2441 Matrix.cpp:3688] Check failed: (size_t)lbl[i] < dim (2 vs. 2)
*** Check failure stack trace: ***
    @     0x7f63dff74bcd  google::LogMessage::Fail()
    @     0x7f63dff7867c  google::LogMessage::SendToLog()
    @     0x7f63dff746f3  google::LogMessage::Flush()
    @     0x7f63dff79b8e  google::LogMessageFatal::~LogMessageFatal()
    @     0x7f63dfd9c542  paddle::CpuMatrix::oneHotCrossEntropy()
    @     0x7f63dfbc9e92  paddle::MultiBoxLossLayer::forward()
    @     0x7f63dfc7ef4d  paddle::NeuralNetwork::forward()
    @     0x7f63dfc7fc63  paddle::GradientMachine::forwardBackward()
    @     0x7f63dff50a04  GradientMachine::forwardBackward()
    @     0x7f63dfb1c689  _wrap_GradientMachine_forwardBackward
    @           0x4c2e1e  PyEval_EvalFrameEx
    @           0x4b9b66  PyEval_EvalCodeEx
    @           0x4c1f56  PyEval_EvalFrameEx
    @           0x4b9b66  PyEval_EvalCodeEx
    @           0x4c17c6  PyEval_EvalFrameEx
    @           0x4b9b66  PyEval_EvalCodeEx
    @           0x4c17c6  PyEval_EvalFrameEx
    @           0x4b9b66  PyEval_EvalCodeEx
    @           0x4c1f56  PyEval_EvalFrameEx
    @           0x4b9b66  PyEval_EvalCodeEx
    @           0x4eb69f  (unknown)
    @           0x4e58f2  PyRun_FileExFlags
    @           0x4e41a6  PyRun_SimpleFileExFlags
    @           0x4938ce  Py_Main
    @     0x7f642cd25830  __libc_start_main
    @           0x493299  _start
    @              (nil)  (unknown)

**Comment by psersonal-cjy** [comment]
解决了，谢谢




| |
陈金毓
邮箱：13261904407@163.com
|

签名由 网易邮箱大师 定制

On 12/10/2018 14:26, defineconst wrote:

你好 解决了嘛?谢谢。

[INFO 2018-12-10 14:22:03,694 layers.py:2689] output for pool6_mbox_loc: c = 24, h = 1, w = 1, size = 24
[INFO 2018-12-10 14:22:03,696 layers.py:2689] output for pool6_mbox_conf: c = 12, h = 1, w = 1, size = 12
I1210 14:22:07.396968 2441 GradientMachine.cpp:94] Initing parameters..
I1210 14:22:09.943565 2441 GradientMachine.cpp:101] Init parameters done.
F1210 14:22:13.446383 2441 Matrix.cpp:3688] Check failed: (size_t)lbl[i] < dim (2 vs. 2)
*** Check failure stack trace: ***
@ 0x7f63dff74bcd google::LogMessage::Fail()
@ 0x7f63dff7867c google::LogMessage::SendToLog()
@ 0x7f63dff746f3 google::LogMessage::Flush()
@ 0x7f63dff79b8e google::LogMessageFatal::~LogMessageFatal()
@ 0x7f63dfd9c542 paddle::CpuMatrix::oneHotCrossEntropy()
@ 0x7f63dfbc9e92 paddle::MultiBoxLossLayer::forward()
@ 0x7f63dfc7ef4d paddle::NeuralNetwork::forward()
@ 0x7f63dfc7fc63 paddle::GradientMachine::forwardBackward()
@ 0x7f63dff50a04 GradientMachine::forwardBackward()
@ 0x7f63dfb1c689 _wrap_GradientMachine_forwardBackward
@ 0x4c2e1e PyEval_EvalFrameEx
@ 0x4b9b66 PyEval_EvalCodeEx
@ 0x4c1f56 PyEval_EvalFrameEx
@ 0x4b9b66 PyEval_EvalCodeEx
@ 0x4c17c6 PyEval_EvalFrameEx
@ 0x4b9b66 PyEval_EvalCodeEx
@ 0x4c17c6 PyEval_EvalFrameEx
@ 0x4b9b66 PyEval_EvalCodeEx
@ 0x4c1f56 PyEval_EvalFrameEx
@ 0x4b9b66 PyEval_EvalCodeEx
@ 0x4eb69f (unknown)
@ 0x4e58f2 PyRun_FileExFlags
@ 0x4e41a6 PyRun_SimpleFileExFlags
@ 0x4938ce Py_Main
@ 0x7f642cd25830 __libc_start_main
@ 0x493299 _start
@ (nil) (unknown)
