### ISSUE TITLE
paddle2.0.0rc1版本有内存泄漏问题

### ISSUE THREAD

**Issue by rillzhang** [PaddlePaddle/Paddle#29919]
操作系统：centos7
机器配置：显卡3080ti，cpu i5 9代，内存 16G，固态硬盘
paddle版本：2.0.0rc1
cuda版本：11.0
python版本：3.6

图片是一张手机上随便截的图，180k的jpg图片。图片一开始就读入了，每隔300毫秒循环识别这一张图。显存稳定在6G多一点。内存不断在增加，大概20分钟以后，内存占满，程序挂掉。
还请帮忙解答一下是什么原因，是跟调用方式有关吗？

示例代码如下：
`ocr_engine: paddleocr.PaddleOCR = None
ocr_engine = paddleocr.PaddleOCR()

img = cv.imread('./out.jpg', 1)

while True:
results = ocr_engine.ocr(img)
texts = list(map(lambda x: x[1][0], results))
print("result : ", texts)
time.sleep(0.3)

**Comment by wangchaochaohu** [comment]
这里是使用PaddleOCR得接口代码吗？
@MissPenguin 能帮忙看下这个问题吗？

**Comment by LDOUBLEV** [comment]
To: https://github.com/PaddlePaddle/PaddleOCR/issues/1581

**Comment by rillzhang** [comment]
收到，谢谢

**Comment by jiweibo** [comment]
cudnn8.0存在内存泄露，请换成cudnn7试下

或者临时关闭两个用到cudnn泄露位置的pass
python 写法
config.delete_pass('conv_elementwise_add_act_fuse_pass')
config.delete_pass('conv_elementwise_add2_act_fuse_pass')
