### ISSUE TITLE
https://github.com/PaddlePaddle/Paddle/issues/19433 這個沒解決爲什麼給關了？？？？？？？現在還有這種情況

### ISSUE THREAD

**Issue by lizhaohu** [PaddlePaddle/Paddle#29910]
https://github.com/PaddlePaddle/Paddle/issues/19433　同樣的問題，請幫忙看看謝謝

**Comment by wangchaochaohu** [comment]
按照反馈 可以把底层所有的path清空了 然后手动设置了需要的include以及lib就行了
