### ISSUE TITLE
error about unsupported/Eigen/CXX11/Tensor

### ISSUE THREAD

**Issue by tensor-tang** [PaddlePaddle/Paddle#2993]
I found a compile issue

> paddle/platform/device_context.h:25:42: fatal error: unsupported/Eigen/CXX11/Tensor: No such file or directory
 #include <unsupported/Eigen/CXX11/Tensor>

This error sometimes occurred sometimes not, seems about the third party need dependency?

My `cmake3.5.2`

**Comment by QiJune** [comment]
DeviceContext depends on eigen3. So, eigen3 must be downloaded first. In multi-thread compiling process, sometimes the eigen3 download first, and sometimes not.

Is you codes the latest one? The bug has been fixed and please update with latest develop branch.

**Comment by gangliao** [comment]
I found @tensor-tang already followed @QiJune 's comment, so I will close this issue
