### ISSUE TITLE
ImportError: libssl.so.1.1: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by starsblinking** [PaddlePaddle/Paddle#29959]
2.0rc1能正常装。
刚刚试了下develop版，结果import paddle报错ImportError: libssl.so.1.1: cannot open shared object file: No such file or directory
请问这是develop版才有的问题还是后面的版本都需要1.1以上的openssl？
centos7的集群表示鸭梨山大。。。

**Comment by willthefrog** [comment]
应该不是必须的，只是编包的环境里装了，所以链的openssl 1.1的so，如果实在不能满足可以尝试源码编译。

**Comment by willthefrog** [comment]
而且这个估计也不是paddle的直接依赖

**Comment by starsblinking** [comment]
看来，目前只能是跑develop版的时候手动在机器上装一下openssl。。。如果你们没法改nightly build的环境话

**Comment by willthefrog** [comment]
> 看来，目前只能是跑develop版的时候手动在机器上装一下openssl。。。如果你们没法改nightly build的环境话

嗯，这样也是可以的。

**Comment by starsblinking** [comment]
发现在我的centos 6u3的开发机上还是不行。。。。。。
ldd python3.8/site-packages/paddle/fluid/core_avx.so 会发现还需要GLIBC_2.17、GLIBCXX_3.4.19、CXXABI_1.3.7等等。。。。。。

**Comment by willthefrog** [comment]
建议还是自己编译，官方包可能已经迁移gcc8了

**Comment by starsblinking** [comment]
多谢。更新换代到gcc8也是好事，可惜厂内多数机器的系统实在太老了。

经过一晚上的折腾，我成功在cenos6上升级了GLIBC和GLIBCXX（谨慎模仿，系统可能直接报废导致需要重装)，已经可以正常运行用pip安装的develop版了～
后面再有问题的话，我就自己编译吧
