### ISSUE TITLE
paddle2.0和pytorch在计算mean时输出的形状不同

### ISSUE THREAD

**Issue by liguoyu666** [PaddlePaddle/Paddle#29951]
`import torch

a = torch.rand([8,3,128,128])
b = a.mean()
print(b.shape)   # torch.Size([ ])`

`import paddle

c = paddle.rand([8,3,128,128])
d = c.mean()
print(d.shape)   # [1]`

paddle输出的shape为[1]，要用哪个api才能达到pytorch输出的shape [ ]

**Comment by willthefrog** [comment]
目前paddle还不支持scalar tensor，后续版本可能会改进。

**Comment by liguoyu666** [comment]
> 目前paddle还不支持scalar tensor，后续版本可能会改进。

那shape为[1]，有啥方法可以变为[ ] 而值不变吗？还是说现版本shape没法变为[ ]

**Comment by willthefrog** [comment]
目前应该是不支持[]

**Comment by liguoyu666** [comment]
> 目前应该是不支持[]

好的，谢谢

**Comment by zhwesky2010** [comment]
@liguoyu666 你好，请问如果支持为shape=[]，会带来哪些方面的正面收益呢

**Comment by zhwesky2010** [comment]
@liguoyu666 

你好，飞桨将于2.5版本全面支持0维Tensor，上述反馈的0D问题也将同时解决。（索引API需要设置 `export FLAGS_set_to_1d=0`，其他API无需设置）

欢迎试用并安装develop 版本的paddle whl包，将体验最新的0维特性：https://www.paddlepaddle.org.cn/install/quick?docurl=/documentation/docs/zh/develop/install/pip/linux-pip.html
安装命令：
`pip install paddlepaddle-gpu==0.0.0.post112 -f https://www.paddlepaddle.org.cn/whl/linux/gpu/develop.html`

---
Hello, Paddle will fully support the 0-dimensional Tensor in version 2.5, and the 0D issue will also be resolved at the same time.
Welcome to try and install the develop version of the paddle whl package, and you will experience the latest 0-dimensional features: https://www.paddlepaddle.org.cn/install/quick?docurl=/documentation/docs/zh/develop/install/pip/linux -pip.html
Install Command:
`pip install paddlepaddle-gpu==0.0.0.post112 -f  https://www.paddlepaddle.org.cn/whl/linux/gpu/develop.html `
