### ISSUE TITLE
Two overlapped PR merges

### ISSUE THREAD

**Issue by skylian** [PaddlePaddle/Paddle#2996]
Two days ago, my PR (#2572) about enabling error clipping for FC layer from a month ago was accepted and merged. I just found out that 15 days ago, there was another PR(#2757) targeting the same issue. Both PRs modified the file [config_parser.py](https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/trainer/config_parser.py). I think for that file, it is better to discard my change.

**Comment by gangliao** [comment]
Thanks for your great contribution! Could you help us to reach that point?

**Comment by skylian** [comment]
I should say sorry for the trouble. 

I made changes at [line 1583](https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/trainer/config_parser.py#L1583) and [line 1601](https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/trainer/config_parser.py#L1601) in [config_parser.py](https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/trainer/config_parser.py) in PR#2572. However, in PR#2757, the support of error clipping is moved to LayerBase ([line 1357](https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/trainer/config_parser.py#L1357)), which makes my changes totally unnecessary, though not harmful.
