### ISSUE TITLE
paddle-gpu无法检测到GPU卡

### ISSUE THREAD

**Issue by christianahui** [PaddlePaddle/Paddle#29978]
运行fluid.CUDAPlace(0)提示无法找到GPU，运行f.install_check.run_check()也没有cuda的信息（我不需要安装多卡可运行的paddle，只要能在单卡上运行就行）
![image](https://user-images.githubusercontent.com/15339499/103256451-53042700-49c8-11eb-9ab9-c4ef72873ad0.png)
cuda和cudnn版本如下，运行nvidia-smi也能查看到机器上的8个卡：
![image](https://user-images.githubusercontent.com/15339499/103256498-77600380-49c8-11eb-978d-297c99529253.png)
辛苦帮忙查看，多谢！

**Comment by LielinJiang** [comment]
内部沟通解决，似乎是gcc版本的问题
