### ISSUE TITLE
StaticInputV2 in Docker Container no attribute to_proto

### ISSUE THREAD

**Issue by gibiansky** [PaddlePaddle/Paddle#2998]
I get the following error: 

```
File "paddlepaddle.py", line 205, in build_model
   parameters = paddle.parameters.create(losses)
 File "/usr/local/lib/python2.7/dist-packages/paddle/v2/parameters.py", line 19, in create
   topology = Topology(layers)
 File "/usr/local/lib/python2.7/dist-packages/paddle/v2/topology.py", line 69, in __init__
   layers, extra_layers=extra_layers)
 File "/usr/local/lib/python2.7/dist-packages/paddle/v2/layer.py", line 96, in parse_network
   return __parse__(__real_func__)
 File "/usr/local/lib/python2.7/dist-packages/paddle/trainer_config_helpers/config_parser_utils.py", line 32, in parse_network_config
   config = config_parser.parse_config(network_conf, config_arg_str)
 File "/usr/local/lib/python2.7/dist-packages/paddle/trainer/config_parser.py", line 3597, in parse_config
   trainer_config()
 File "/usr/local/lib/python2.7/dist-packages/paddle/v2/layer.py", line 89, in __real_func__
   real_output = [each.to_proto(context=context) for each in output_layers]
 File "/usr/local/lib/python2.7/dist-packages/paddle/v2/config_base.py", line 109, in to_proto
   context=context)
 File "/usr/local/lib/python2.7/dist-packages/paddle/v2/config_base.py", line 109, in to_proto
   context=context)
 File "/usr/local/lib/python2.7/dist-packages/paddle/v2/config_base.py", line 109, in to_proto
   context=context)
 File "/usr/local/lib/python2.7/dist-packages/paddle/v2/config_base.py", line 112, in to_proto
   self.__parent_layers__[layer_name])
 File "/usr/local/lib/python2.7/dist-packages/paddle/v2/config_base.py", line 111, in <lambda>
   v1_layer = map(lambda x: x.to_proto(context=context),
 File "/usr/local/lib/python2.7/dist-packages/paddle/v2/config_base.py", line 112, in to_proto
   self.__parent_layers__[layer_name])
 File "/usr/local/lib/python2.7/dist-packages/paddle/v2/config_base.py", line 111, in <lambda>
   v1_layer = map(lambda x: x.to_proto(context=context),
 File "/usr/local/lib/python2.7/dist-packages/paddle/v2/config_base.py", line 112, in to_proto
   self.__parent_layers__[layer_name])
 File "/usr/local/lib/python2.7/dist-packages/paddle/v2/config_base.py", line 111, in <lambda>
   v1_layer = map(lambda x: x.to_proto(context=context),
 File "/usr/local/lib/python2.7/dist-packages/paddle/v2/config_base.py", line 112, in to_proto
   self.__parent_layers__[layer_name])
 File "/usr/local/lib/python2.7/dist-packages/paddle/v2/config_base.py", line 111, in <lambda>
   v1_layer = map(lambda x: x.to_proto(context=context),
AttributeError: 'StaticInputV2' object has no attribute 'to_proto'
```

The code is 

```
for i in range(layers):
        if static is not None:
            inputs = [inputs, paddle.layer.StaticInputV2(static)]
        fwd = paddle.networks.lstmemory_group(input=inputs, size=size)
        bwd = paddle.networks.lstmemory_group(input=inputs, size=size, reverse=True)
        inputs = paddle.layer.concat(input=[fwd, bwd])

    final_states = paddle.layer.concat(input=[
        paddle.layer.last_seq(input=fwd),
        paddle.layer.first_seq(input=bwd),
    ])
    return final_states, inputs
```

`paddle.layer.StaticInput` does not exist, only `paddle.layer.StaticInputV2`. 

`static` (in the code above) is created by a `paddle.layer.concat` operation.

I have also tried `paddle.networks.simple_lstm` in place of `paddle.networks.lstmemory_group`. 

I don't understand what is happening or why this error occurs. Please help me figure it out!

**Comment by gangliao** [comment]
Could you give us your Docker image version?
Is It `0.10.0`?

**Comment by gibiansky** [comment]
Yes, it is.

**Comment by gibiansky** [comment]
I used the instructions [here](https://github.com/PaddlePaddle/book/blob/develop/README.md#running-the-book), which specify that docker image version.

**Comment by gangliao** [comment]
Thanks. I will check this now. BTW, the above code snippet is from `paddlepaddle book` or your own code?

**Comment by gibiansky** [comment]
It is my own code.

**Comment by lcy-seso** [comment]
* The docker image 0.10.0 hasn't been updated for quite a long time. I recommend using the image with the latest/latest-gpu (https://hub.docker.com/r/paddlepaddle/book/tags/) tag.
* `StaticInputV2` and `GeneratedInputV2` currently has been unified into `StaticInput` and `GeneratedInput`. There is no `StaticInputV2` and `GeneratedInputV2`  anymore (but the way to use them does not change, just remove the suffix). So, I think it is better to use the latest/latest-gpu.
* I find you are writing a bi-directional LSTM encoder, here is an example of LSTM encoder-decoder  https://github.com/lcy-seso/models/blob/gen_chinese_poetry/generate_chinese_poetry/network_conf.py#L10 based on the latest PaddlePaddle version. You can check it as an example.

**Comment by gibiansky** [comment]
I tried the `latest-gpu` tag and it is no different. In fact, if I look in `/usr/local/lib/python2.7/dist-packages/paddle`, the latest file modification dates are May 19th. Is that image supposed to be different than 0.10?

**Comment by gangliao** [comment]
well, if you check the docker hub: https://hub.docker.com/r/paddlepaddle/book/tags/, `latest-gpu` is our nightly-docker-image.

Also, @lcy-seso mentioned `bi-directional LSTM encoder`, it's in our repo `paddle/models`: https://github.com/PaddlePaddle/models, you can check the `travis.yml` https://github.com/PaddlePaddle/models/blob/develop/.travis.yml#L24 to figure out how it works under docker container.

Thank you so much.

**Comment by helinwang** [comment]
@gibiansky Could you try `docker pull paddlepaddle/paddle:latest-gpu` to get the latest?

```
➜  paddle git:(develop) ✗ docker pull paddlepaddle/paddle:latest-gpu
latest-gpu: Pulling from paddlepaddle/paddle
Status: Downloaded newer image for paddlepaddle/paddle:latest-gpu
➜  paddle git:(develop) ✗ docker run -it paddlepaddle/paddle:latest-gpu bash
root@57f90d33dc89:/# ls -lh /usr/local/lib/python2.7/dist-packages/paddle
total 28K
-rw-r--r-- 1 root staff  609 Jul 25 08:52 __init__.py
-rw-r--r-- 1 root staff  134 Jul 25 08:53 __init__.pyc
drwxr-sr-x 2 root staff 4.0K Jul 25 08:53 proto
drwxr-sr-x 2 root staff 4.0K Jul 25 08:53 trainer
drwxr-sr-x 2 root staff 4.0K Jul 25 08:53 trainer_config_helpers
drwxr-sr-x 2 root staff 4.0K Jul 25 08:53 utils
drwxr-sr-x 7 root staff 4.0K Jul 25 08:53 v2
```
As you can see that the files are modified on July 25.

**Comment by gibiansky** [comment]
I have checked that that works. The issue is that `paddlepaddle/book` works but `docker.paddlepaddle.org/book` is not updated (I think). I just spoke to Yi about it and he will check it out.

**Comment by wangkuiyi** [comment]
We used to manually build and push Docker images to docker.paddlepaddle.org.  I think this issue reveals that manual work is not reliable.  Fortunately, we have TeamCity now. @helinwang is configuring TeamCity to automatically build and push Docker images.  Thanks to @gibiansky and @juliecbd  for reporting this issue. @helinwang will update later.

**Comment by helinwang** [comment]
It has been fixed. I have configured TeamCity CI to update docker.paddlepaddle.org as well for both docker.paddlepaddle.org/paddle and docker.paddlepaddle.org/book.
