### ISSUE TITLE
编译最新的release/2.0的时候 一直提示我各种包的路径，并且卡在protobuf版本 提示

### ISSUE THREAD

**Issue by Nagisakurumi** [PaddlePaddle/Paddle#29990]
![image](https://user-images.githubusercontent.com/18586645/103269844-9c1ca100-49f1-11eb-83d9-62b7656abc9d.png)
这个是我目前因为写各种包然后cmake的参数变得特别多
CMake Error at cmake/external/python.cmake:74 (MESSAGE):
  Found Python Protobuf < 3.0.0, please use pip to upgrade protobuf.  pip
  install -U protobuf
Call Stack (most recent call first):
  cmake/third_party.cmake:236 (include)
  CMakeLists.txt:221 (include)
最后卡到这里。
![image](https://user-images.githubusercontent.com/18586645/103269946-dede7900-49f1-11eb-9c98-3e9445f486c0.png)
这个是我已经安装的protobuf
不知道怎么继续下去，感觉官方写的例子 不能让我完全 照着跑下去。

**Comment by Nagisakurumi** [comment]
cmake .. -DPY_VERSION=3.6 -DPY_PIP=/root/anaconda3/envs/ocr/bin -DPYTHON_EXECUTABLE:FILEPATH=/root/anaconda3/envs/ocr/bin -DPYTHON_INCLUDE_DIR:PATH=/root/anaconda3/envs/ocr/include -DPYTHON_LIBRARY:FILEPATH=/root/anaconda3/lib/libpython3.so -DWITH_GPU=ON -DWITH_TESTING=OFF -DCMAKE_BUILD_TYPE=Release -DPY_NUMPY=/root/anaconda3/envs/ocr/lib/python3.6/site-packages/numpy -DPY_WHEEL=/root/anaconda3/envs/ocr/lib/python3.6/site-packages/wheel -DPY_GOOGLE.PROTOBUF=/root/anaconda3/envs/ocr/lib/python3.6/site-packages/protobuf-3.14.0 -DPYTHON_NUMPY_INCLUDE_DIR=/root/anaconda3/envs/ocr/lib/python3.6/site-packages/numpy/core/include/

这个是参数，上面图片没出来这里补上
protobuf我 pip install protobuf 3.14

**Comment by LielinJiang** [comment]
```
-DPY_VERSION=3.7
-DPYTHON_EXECUTABLE=/workspace/miniconda3/envs/py37/bin/python3.7
-DPYTHON_INCLUDE_DIR=/workspace/miniconda3/envs/py37/include/python3.7m
-DPYTHON_LIBRARY=/workspace/miniconda3/envs/py37/lib/libpython3.7m.so
-DWITH_TESTING=ON
-DCMAKE_INSTALL_PREFIX=./output/
-DCMAKE_BUILD_TYPE=Release
-DWITH_PYTHON=ON
-DWITH_MKL=ON
-DWITH_GPU=ON
-DWITH_DISTRIBUTE=ON
```
这是我的cmake选项，可以正常编译的。你的似乎和我有些不同，可以参考下。

**Comment by Nagisakurumi** [comment]
我试了一下 我用acanconda 创建了3.7的虚拟环境 然后使用 上面的 参数 路径改成自己的 但是还是报 一样的错误，我的cuda是11.0 还有cudnn是8.0.3

**Comment by LielinJiang** [comment]
protobuf 是否也安装在了相应的虚拟环境中？实在不行，建议您还是使用下paddle 的docker：https://hub.docker.com/r/paddlepaddle/paddle

**Comment by zhwesky2010** [comment]
@Nagisakurumi 您好，显示是protobuf版本低于3.0.0，
![image](https://user-images.githubusercontent.com/52485244/103543474-8f101e00-4ed9-11eb-8aca-883cc7bf0b3c.png)
源码中会进行检查，能否 pip install -U protobuf 升级再看下

**Comment by YueWang1996** [comment]
您好，我也遇到了和您一样的问题，请问这个问题有解决吗？

**Comment by nbcc** [comment]
> @Nagisakurumi 您好，显示是protobuf版本低于3.0.0，
> ![image](https://user-images.githubusercontent.com/52485244/103543474-8f101e00-4ed9-11eb-8aca-883cc7bf0b3c.png)
> 源码中会进行检查，能否 pip install -U protobuf 升级再看下

<img width="1335" alt="图片" src="https://user-images.githubusercontent.com/864331/115830594-1bbbf900-a443-11eb-864e-a4bad1d92642.png">

@zhouwei25 这个已经指定 PY_google.protobuf 包地址了，包版本是 3.15.8 为什么还是会报错？
