### ISSUE TITLE
python导入paddle 自己的模块出错

### ISSUE THREAD

**Issue by AshburnLee** [PaddlePaddle/Paddle#30005]
- 问题
  于2020年12月29日，使用paddle develop分支编包，当 import 如下模块时，出错：
  
  ![截屏2020-12-29 20 07 15](https://user-images.githubusercontent.com/18277990/103282667-743d3580-4a11-11eb-81f0-49c31aa61f4c.png)
  
  paddle 的 commit ID 为: a1d9a14e89f6ae6734f6be47b539327868a7ef91。当 checkout 到之前 commit 后不再出错。

- 版本、环境信息：
  paddle develop 分支，commit ID 如上，GPU 版本，V100，cuda11，cudnn8，Linux version 3.10.0_3-0-0-34。python3.7
- 复现
  在 python3.7 命令行直接 import 即可。

**Comment by LielinJiang** [comment]
可以使用hardsigmoid.
具体请参考这个pr：https://github.com/PaddlePaddle/Paddle/pull/29928

**Comment by AshburnLee** [comment]
没问题了，多谢解答
