### ISSUE TITLE
v2 API supports config dumping

### ISSUE THREAD

**Issue by wangkuiyi** [PaddlePaddle/Paddle#3001]
In v1 API, we have https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/utils/dump_config.py. Do we
 have similar stuff in v2 API?

**Comment by jacquesqiao** [comment]
can use following code to dump the protobuf config:
```python
topology = paddle.topology.Topology(cost)
print topology.proto()
```

**Comment by lcy-seso** [comment]
but, I think you can use `paddle.v2.layer.parse_network`.
Here is my example:

```python
import sys
import math
import gzip

from paddle.v2.layer import parse_network
import paddle.v2 as paddle


def fc_net(dict_dim, class_num, emb_dim=28, hidden_layer_sizes=[28, 8]):
    # define the input layers
    data = paddle.layer.data("word",
                             paddle.data_type.integer_value_sequence(dict_dim))
    lbl = paddle.layer.data("label", paddle.data_type.integer_value(class_num))

    emb = paddle.layer.embedding(input=data, size=emb_dim)
    seq_pool = paddle.layer.pooling(
        input=emb, pooling_type=paddle.pooling.Max())

    for idx, hidden_size in enumerate(hidden_layer_sizes):
        hidden_init_std = 1.0 / math.sqrt(hidden_size)
        hidden = paddle.layer.fc(
            input=hidden if idx else seq_pool,
            size=hidden_size,
            act=paddle.activation.Tanh(),
            param_attr=paddle.attr.Param(initial_std=hidden_init_std))

    prob = paddle.layer.fc(
        input=hidden,
        size=class_num,
        act=paddle.activation.Softmax(),
        param_attr=paddle.attr.Param(initial_std=1.0 / math.sqrt(class_num)))

    return paddle.layer.classification_cost(input=prob, label=lbl)


if __name__ == "__main__":
    adam_optimizer = paddle.optimizer.Adam(
        learning_rate=1e-3,
        regularization=paddle.optimizer.L2Regularization(rate=1e-3),
        model_average=paddle.optimizer.ModelAverage(average_window=0.5))
    cost = fc_net(
        dict_dim=1024, class_num=2, emb_dim=28, hidden_layer_sizes=[28, 8])
    print parse_network(cost)
```

**Comment by lcy-seso** [comment]
I think the benefits are:
* If you use `paddle.v2.layer.parse_network`, you do not need to define the `trainer` and just focus on debugging the network topology.
* you do not need to modify PaddlePaddle's codes.

But do remember, before defining network topology, first define `optimizer`, otherwise, some globally set tuning parameter will not work.

**Comment by lcy-seso** [comment]
In @jacquesqiao 's method, if `optimizer` is not included, some globally set parameters, such as decay rate,  will not be seen in the dump result, if this is acceptable.

**Comment by lcy-seso** [comment]
or just `print self.__topology_in_proto__`after this line https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/v2/trainer.py#L62

**Comment by byzhang** [comment]
@wangkuiyi  @jacquesqiao  @lcy-seso , thanks!  does parse_network generates model_config only, or also includes data_config and opt_config, test_data_config, save_dir, start_pass... ?

**Comment by byzhang** [comment]
dump_config supports --whole

**Comment by lcy-seso** [comment]
- In V2 API,  we do not have `data_config`  anymore. Data are directly fed to paddle trainer instance.  Topology and optimizer configurations make up all configurations PaddlePaddle needs.
- `parse_network` does not print and `opt_config`, it only prints network topology. If you need `opt_config`, you can temporarily print after this line https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/v2/optimizer.py#L28.
- I think we can add `dump_config supports --whole` into `paddle.utils`.

**Comment by byzhang** [comment]
yes, and it's also easier to load the proto in a C++ app.

**Comment by lcy-seso** [comment]
I will fix this.

**Comment by lcy-seso** [comment]
- I this issue https://github.com/PaddlePaddle/Paddle/issues/2766  is also related to dumping the configure and serializing it.
- we should update `paddle.utils.dump_config`.

**Comment by Xreki** [comment]
Already  fixed, see https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/utils/dump_v2_config.py .
