### ISSUE TITLE
编译release2.0 不过 卡在 UINT64_MAX not found

### ISSUE THREAD

**Issue by Nagisakurumi** [PaddlePaddle/Paddle#30012]
daErrorMessage.tar.gz
-- Looking for UINT64_MAX
-- Looking for UINT64_MAX - not found
-- Looking for UINT64_MAX
-- Looking for UINT64_MAX - not found
CMake Error at cmake/flags.cmake:102 (message):
  Cannot find symbol UINT64_MAX
Call Stack (most recent call first):
  CMakeLists.txt:233 (include)

**Comment by zhiqiu** [comment]
> daErrorMessage.tar.gz
> -- Looking for UINT64_MAX
> -- Looking for UINT64_MAX - not found
> -- Looking for UINT64_MAX
> -- Looking for UINT64_MAX - not found
> CMake Error at cmake/flags.cmake:102 (message):
> Cannot find symbol UINT64_MAX
> Call Stack (most recent call first):
> CMakeLists.txt:233 (include)

请问下您的编译环境和编译选项是？

**Comment by Nagisakurumi** [comment]
编译环境 是 anaconda 下的虚拟环境 python3.6 编译选项 cmake .. -DPY_VERSION=3.6 -DWITH_GPU=ON -DWITH_TESTING=OFF -DCMAKE_BUILD_TYPE=Release

**Comment by Nagisakurumi** [comment]
系统是centeros

**Comment by zhiqiu** [comment]
paddle代码拉的是哪个分支？

**Comment by Nagisakurumi** [comment]
release/2.0

**Comment by zhiqiu** [comment]
> 系统是centeros

请问下centos是哪个版本？另外，建议使用paddle提供的docker镜像编译，因为docker中的环境都配置好了。可参考：https://www.paddlepaddle.org.cn/documentation/docs/zh/2.0-rc1/install/compile/linux-compile.html

**Comment by Nagisakurumi** [comment]
centeros7

**Comment by zhiqiu** [comment]
> centeros7

你是按照 https://www.paddlepaddle.org.cn/documentation/docs/zh/2.0-rc1/install/compile/linux-compile.html#span-id-compile-from-host-span 的步骤操作的吗？

**Comment by Nagisakurumi** [comment]
我是根据 1.8的版本下的centeros 编译教程来的

**Comment by zhiqiu** [comment]
> 我是根据 1.8的版本下的centeros 编译教程来的

建议你用docker试试，因为这个报错看起来和paddle代码好像关系不大，是cmake阶段检测环境的报错。

**Comment by Nagisakurumi** [comment]
那好吧
我再去尝试一下

**Comment by zhiqiu** [comment]
> 那好吧
> 我再去尝试一下

嗯嗯好的，有进展或问题随时反馈。

**Comment by hermitgreen** [comment]
I found same problem and I solved it by change compiler to gcc8.2.0
