### ISSUE TITLE
Check Failed: size != 0

### ISSUE THREAD

**Issue by youan1** [PaddlePaddle/Paddle#3002]
错误如题，本地调试时出现如下问题，相应的脚本文件和数据已经上传，请Paddle同学帮忙看看

F0721 11:04:24.647970 25445 MemoryHandle.cpp:49] Check failed: size != 0  allocate 0 bytes
*** Check failure stack trace: ***
    @     0x7f56f41f9e6d  google::LogMessage::Fail()
    @     0x7f56f41fd91c  google::LogMessage::SendToLog()
    @     0x7f56f41f9993  google::LogMessage::Flush()
[script_test_folder2.zip](https://github.com/PaddlePaddle/Paddle/files/1164344/script_test_folder2.zip)

    @     0x7f56f41fee2e  google::LogMessageFatal::~LogMessageFatal()
    @     0x7f56f4165b39  paddle::CpuMemoryHandle::CpuMemoryHandle()
    @     0x7f56f413b6be  paddle::CpuVectorT<>::CpuVectorT()
    @     0x7f56f413c39a  paddle::VectorT<>::create()
    @     0x7f56f41e2e02  IVector::create()
    @     0x7f56f3ee4f87  _wrap_IVector_create
    @           0x4a9e33  PyEval_EvalFrameEx
    @           0x4ad70d  PyEval_EvalCodeEx
    @           0x4aa88c  PyEval_EvalFrameEx
    @           0x4aa9a7  PyEval_EvalFrameEx
    @           0x4aa9a7  PyEval_EvalFrameEx
    @           0x4ad70d  PyEval_EvalCodeEx
    @           0x51c1f0  function_call

**Comment by gangliao** [comment]
duplicate #2670
请确保paddle 传输的数据不为空，可以在yield之前check下数据。

**Comment by youan1** [comment]
@gangliao ，比如某个稀疏数据slot，确实没有一个数据，这种paddle不支持，是吧

**Comment by youan1** [comment]
有结论了么

**Comment by lcy-seso** [comment]
@gangliao 回答的就是正确答案，请确保 paddle 传输的数据不为空，可以在yield之前check下数据，否则不会出现这个错误。上面的错误是整个batch全部是空数据。

**Comment by youan1** [comment]
@lcy-seso ，在集群上面运行，每个batch 3000条，为什么会出现整个 batch都是空数据的问题，这个从道理上解释不过去，2） 如果某个稀疏数据slot为空，这种padddle支持不支持，为空的是否需要预处理

**Comment by youan1** [comment]
另外，同一批数据，在另外一个集群跑过去了

**Comment by typhoonzero** [comment]
I'm closing this due to low activity, feel free to reopen.

**Comment by chaos-dd** [comment]
这个问题有结论吗？  @gangliao ，比如某个稀疏数据slot，确实没有一个数据，这种paddle不支持。 是这个问题吗？
