### ISSUE TITLE
飞桨2.0.0RC1 高层API例程报错

### ISSUE THREAD

**Issue by skywalk163** [PaddlePaddle/Paddle#30029]
在AIStudio项目版本升级到2.0.0RC1后，发现原来2.0.0.RC0下运行正常的程序报错，到手册找到rc1版本的高层api例程，同样报错。

AIStudio项目版本升级应该是内部升的，现在不管是以前创建的2.0环境，还是新创建项目选择2.0，进入之后都是RC1版本。

高层api例程地址：https://www.paddlepaddle.org.cn/documentation/docs/zh/2.0-rc1/guides/01_paddle2.0_introduction/upgrade_guide_cn.html#id12

项目地址：https://aistudio.baidu.com/aistudio/projectdetail/1222066

报错如下：

`/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/distributed/parallel.py:119: UserWarning: Currently not a parallel execution environment, `paddle.distributed.init_parallel_env` will not do anything.
  "Currently not a parallel execution environment, `paddle.distributed.init_parallel_env` will not do anything."
WARNING:root:DataLoader reader thread raised an exception.
Exception in thread Thread-4:
Traceback (most recent call last):
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 338, in _thread_loop
    six.reraise(*sys.exc_info())
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/six.py", line 703, in reraise
    raise value
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 308, in _thread_loop
    batch = self._dataset_fetcher.fetch(indices)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dataloader/fetcher.py", line 65, in fetch
    data = self.collate_fn(data)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 95, in default_collate_fn
    raise RuntimeError("Unknown data type {}".format(type(slot[0])))
RuntimeError: Unknown data type <class 'PIL.Image.Image'>

The loss value printed in the log is the current step, and the metric is the average value of previous step.
Epoch 1/2
---------------------------------------------------------------------------SystemError                               Traceback (most recent call last)<ipython-input-10-6abdb7766493> in <module>
     16 
     17 # 启动训练
---> 18 model.fit(train_dataset, epochs=2, batch_size=64, log_freq=200)
     19 
     20 # 启动评估
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/hapi/model.py in fit(self, train_data, eval_data, batch_size, epochs, eval_freq, log_freq, save_dir, save_freq, verbose, drop_last, shuffle, num_workers, callbacks)
   1490         for epoch in range(epochs):
   1491             cbks.on_epoch_begin(epoch)
-> 1492             logs = self._run_one_epoch(train_loader, cbks, 'train')
   1493             cbks.on_epoch_end(epoch, logs)
   1494 
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/hapi/model.py in _run_one_epoch(self, data_loader, callbacks, mode, logs)
   1774     def _run_one_epoch(self, data_loader, callbacks, mode, logs={}):
   1775         outputs = []
-> 1776         for step, data in enumerate(data_loader):
   1777             # data might come from different types of data_loader and have
   1778             # different format, as following:
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dataloader/dataloader_iter.py in __next__(self)
    354         try:
    355             if in_dygraph_mode():
--> 356                 return self._reader.read_next_var_list()
    357             else:
    358                 if self._return_list:
SystemError: (Fatal) Blocking queue is killed because the data reader raises an exception.
  [Hint: Expected killed_ != true, but received killed_:1 == true:1.] (at /paddle/paddle/fluid/operators/reader/blocking_queue.h:154)
  [Hint: If you need C++ stacktraces for debugging, please set `FLAGS_call_stack_level=2`.]`

**Comment by skywalk163** [comment]
仔细看了一下文档，发现RC1和RC0 的paddle.vision.datasets.MNIST返回 有不同的地方
RC0 返回的是tensor，RC1默认返回的是PIL.Image.Image，因此RC1 需要多加一句，并在返回函数里多加一个参数“transform=ToTensor()”

如：

from paddle.vision.transforms import ToTensor
train_dataset = paddle.vision.datasets.MNIST(mode='train', transform=ToTensor())

个人认为这样比原来代码繁琐了很多，而且会导致以前写的涉及到vision高层API的代码统统会报错 ，建议将 transform=ToTensor() 设置为默认 。

**Comment by zhiqiu** [comment]
多谢反馈，我找相关同学一起看下这个问题。

**Comment by skywalk163** [comment]
按照上面写的修改代码后，能跑通，但是gpu下速度跟cpu一样快甚至更慢 。

我这个项目里专门有同步/异步时间比较的代码：https://aistudio.baidu.com/aistudio/projectdetail/196937

运行项目根目录文件：python paddlemem.py sync 
以前是3秒左右，现在是27秒左右 。

**Comment by LielinJiang** [comment]
1.之所以这么做是为了区分图像和tensor的概念，对于大多数的神经网络我们需要的是归一化的后格式为"CHW"浮点数输入，这也是ToTensor做的事情。而图像的格式是HWC，且数值范围为（0-255）。这样的输入会造成大多数任务不能很好的收敛。
2.目前ToTensor和dataloader不太适配，我们正在改进。可以先用transpose+normalize代替

**Comment by skywalk163** [comment]
好的，谢谢回复，此问题关闭。

**Comment by skywalk163** [comment]
好的，谢谢回复，此问题关闭。
