### ISSUE TITLE
Op Fusion Pattern Matcher算法详细文档

### ISSUE THREAD

**Issue by buaabai** [PaddlePaddle/Paddle#30021]
#### Is there more detail docs about algorithms in graph_pattern_matcher, such as the role of HitGroup, bi_record, etc?

**Comment by Superjomn** [comment]
你好，这个主要是内部的一个接口，所以没有文档。

原理很naive，我们没有用啥高端的或者学术的标准算法，只是 greedy 的匹配，但由于计算图规模基本就 千 左右，所以没有明显的性能问题。

大的原理是，手动构造一个 pattern 的子图，然后用这个子图去model的计算图里做匹配，具体地

- 先匹配每个pattern 节点
- 通过pattern节点互相的连接进一步做筛选，以及分组（类似 union find）
- 最后将识别好的子图 s 返回

**Comment by buaabai** [comment]
通过再次研读代码有了进一步的理解，非常感谢您的回答。

**Comment by buaabai** [comment]
还想请问一个关于查找到的子图重复的问题，目前是采用了hash的方法来删除子图，[#13550](https://github.com/PaddlePaddle/Paddle/issues/13550)提到了hash的问题，没办法完全剔除所有重复子图，目前有什么好的解决方案吗？在实际op fusion过程中，是否可以理解为，即使遇到了重复的子图，但已经做了op fusion，重复的子图已经不存在了，就意味着不需要进行fusion操作了，从而一定程度上重复子图并不影响最终的fusion结果。

**Comment by Superjomn** [comment]
对，可以这么认为。 
具体的fuse过程是串行处理每个子图，所以执行中没有进一步发现问题。
另外，可以子图节点排个序再计算hash key，应该能解决这个问题

**Comment by buaabai** [comment]
非常感谢您的回答！
