### ISSUE TITLE
2.0 develop成功编译预测库（paddle_fluid.dll），但是使用时会报错：无法定位程序输入点dnnl_post_ops_append_sum_v2于动态链接库paddle_fluid.dll

### ISSUE THREAD

**Issue by TianCaibailei** [PaddlePaddle/Paddle#30026]
为使您的问题得到快速解决，在建立Issue前，请您先通过如下方式搜索是否有相似问题:【搜索issue关键字】【使用labels筛选】【官方文档】

如果您没有查询到相似问题，为快速解决您的提问，建立issue时请提供如下细节信息：
- 标题：简洁、精准描述您的问题，例如“最新预测库的API文档在哪儿 ”
- 版本、环境信息：
    1）PaddlePaddle版本：2.0 develop
    2）CPU：I7 10750H MKL=On
    3）GPU：GTX1660Ti、CUDA 10.0 和CUDNN 7.6
    4）系统环境：Windows 10
注：您可以通过执行[summary_env.py](https://github.com/PaddlePaddle/Paddle/blob/develop/tools/summary_env.py)获取以上信息。
-预测信息
    1）C++预测：请您提供预测库安装包的版本信息，及其中的version.txt文件
    2）CMake包含路径的完整命令
    3）API信息（如调用请提供）
    4）预测库来源：自行编译paddle 2.0 develop得到，编译目标为dll（非静态库）
- 复现信息：如为报错，请给出复现环境、复现步骤
- 问题描述：下载paddlepaddle 2.0 develop源码后，对源码进行编译，选择了使用gpu，并提供cuda以及cudnn、tensorrt等选项，成功编译为paddle_fluid.dll，后使用此dll对应的lib库，对paddlex中cpp文件夹中的demo进行编译，成功编译后，启动demo进行预测，在加载paddle_fluid.dll时就立刻报错，提示无法找到程序入口点，函数名称是：dnnl_post_ops_append_sum_v2。帮忙查看一下是什么问题？
-

**Comment by jiangjiajun** [comment]
请问你这里是出于什么需求需要自行编译预测库呢？直接下载已经编译好的预测库进行编译预测，也存在类似问题吗

**Comment by TianCaibailei** [comment]
你们提供下载的预测库，不带有TensorRT加速

**Comment by jiangjiajun** [comment]
当前的问题是，代码在不开启TensorRT的前提下，CPU和GPU预测都能正常使用，但开启TensorRT就会出错是吗？

https://github.com/PaddlePaddle/Paddle-Inference-Demo/tree/master/c%2B%2B/resnet50 请尝试使用您编译的预测包，编译此分类代码，并开启TensorRT进行测试，如若存在问题的话，那说明应该是编译的预测包存在问题，我再帮忙找预测库的同学帮忙来看下

**Comment by TianCaibailei** [comment]
> 当前的问题是，代码在不开启TensorRT的前提下，CPU和GPU预测都能正常使用，但开启TensorRT就会出错是吗？
> 
> https://github.com/PaddlePaddle/Paddle-Inference-Demo/tree/master/c%2B%2B/resnet50 请尝试使用您编译的预测包，编译此分类代码，并开启TensorRT进行测试，如若存在问题的话，那说明应该是编译的预测包存在问题，我再帮忙找预测库的同学帮忙来看下

按照这个链接下载了模型和demo代码，并对demo代码进行编译，预测库使用的是我从paddle develop 2.0源码编译出来的，首先测试了不开启tensorRT的情况，可以正常预测。
第二步，开启TensorRT进行预测，会报错。具体操作如下：
这是开启TensortRT的代码：
`std::shared_ptr<Predictor> InitPredictor() {
	Config config;
	if (FLAGS_model_dir != "") {
		config.SetModel(FLAGS_model_dir);
	}
	config.SetModel(FLAGS_model_file, FLAGS_params_file);
	config.EnableUseGpu(100, 0);
	config.EnableMKLDNN();
	config.EnableTensorRtEngine(1 << 20      	   /*workspace_size*/,
								FLAGS_batch_size   /*max_batch_size*/,
								3                  /*min_subgraph_size*/,
								paddle::AnalysisConfig::Precision::kFloat32 /*precision*/,
								false              /*use_static*/,
								false              /*use_calib_mode*/);

	// Open the memory optim.
	config.EnableMemoryOptim();
	return CreatePredictor(config);
}
`


报错位置是CreatePredictor(config);
报错的内容是：


0x00007FF9E4843B29 处(位于 classifier.exe 中)引发的异常: Microsoft C++ 异常: paddle::platform::EnforceNotMet，位于内存位置 0x000000B9190FE6F0 处。
0x00007FF9E4843B29 处(位于 classifier.exe 中)引发的异常: Microsoft C++ 异常: [rethrow]，位于内存位置 0x0000000000000000 处。
0x00007FF9E4843B29 处(位于 classifier.exe 中)引发的异常: Microsoft C++ 异常: paddle::platform::EnforceNotMet，位于内存位置 0x000000B9190FE6F0 处。
0x00007FF9E4843B29 处(位于 classifier.exe 中)有未经处理的异常: Microsoft C++ 异常: paddle::platform::EnforceNotMet，位于内存位置 0x000000B9190FE6F0 处。


std中输出的信息如下：


`WARNING: Logging before InitGoogleLogging() is written to STDERR
E0105 14:40:57.156863 23340 paddle_pass_builder.cc:139] GPU not support MKLDNN yet
E0105 14:40:57.880926 23340 paddle_pass_builder.cc:139] GPU not support MKLDNN yet
E0105 14:40:59.102661 23340 paddle_pass_builder.cc:139] GPU not support MKLDNN yet
E0105 14:41:01.530181 23340 paddle_pass_builder.cc:139] GPU not support MKLDNN yet
I0105 14:41:01.531173 23340 analysis_predictor.cc:139] Profiler is deactivated, and no profiling report will be generated.
I0105 14:41:01.554112 23340 analysis_predictor.cc:474] TensorRT subgraph engine is enabled
I0105 14:41:01.554112 23340 analysis_predictor.cc:502] MKLDNN is enabled
e[1me[35m--- Running analysis [ir_graph_build_pass]e[0m
e[1me[35m--- Running analysis [ir_graph_clean_pass]e[0m
e[1me[35m--- Running analysis [ir_analysis_pass]e[0m
(InvalidArgument) Pass tensorrt_subgraph_pass has not been registered.
  [Hint: Expected Has(pass_type) == true, but received Has(pass_type):0 != true:1.] (at E:\Document\Paddle\Paddle-develop\paddle/fluid/framework/ir/pass.h:211)
  [Hint: If you need C++ stacktraces for debugging, please set `FLAGS_call_stack_level=2`.]`

**Comment by cryoco** [comment]
您好，从报错信息来看，您自行编译的预测库并未将TensorRT编译进去。从2.0开始编译预测库时默认不开启TRT，若要开启TRT需要设置编译选项WITH_TENSORRT=ON，并设置TENSORRT_ROOT为TRT根目录路径。可以确认下哈

**Comment by TianCaibailei** [comment]
> 您好，从报错信息来看，您自行编译的预测库并未将TensorRT编译进去。从2.0开始编译预测库时默认不开启TRT，若要开启TRT需要设置编译选项WITH_TENSORRT=ON，并设置TENSORRT_ROOT为TRT根目录路径。可以确认下哈

这个我还特意确认过，确实是开启过，开启的具体选项是：-DWITH_TENSORRT=ON -TENSORRT_ROOT="我的tensorRT库路径"
我再重新用以上参数生成一下解决方案，重新编译一下试试，如有问题再反馈，谢谢支持。

**Comment by cryoco** [comment]
> > 您好，从报错信息来看，您自行编译的预测库并未将TensorRT编译进去。从2.0开始编译预测库时默认不开启TRT，若要开启TRT需要设置编译选项WITH_TENSORRT=ON，并设置TENSORRT_ROOT为TRT根目录路径。可以确认下哈
> 
> 这个我还特意确认过，确实是开启过，开启的具体选项是：-DWITH_TENSORRT=ON -TENSORRT_ROOT="我的tensorRT库路径"
> 我再重新用以上参数生成一下解决方案，重新编译一下试试，如有问题再反馈，谢谢支持。

可以发下您cmake过程的log，如果成功开启了TRT，在日志中会有显示。

**Comment by TianCaibailei** [comment]
我

> > > 您好，从报错信息来看，您自行编译的预测库并未将TensorRT编译进去。从2.0开始编译预测库时默认不开启TRT，若要开启TRT需要设置编译选项WITH_TENSORRT=ON，并设置TENSORRT_ROOT为TRT根目录路径。可以确认下哈
> > 
> > 
> > 这个我还特意确认过，确实是开启过，开启的具体选项是：-DWITH_TENSORRT=ON -TENSORRT_ROOT="我的tensorRT库路径"
> > 我再重新用以上参数生成一下解决方案，重新编译一下试试，如有问题再反馈，谢谢支持。
> 
> 可以发下您cmake过程的log，如果成功开启了TRT，在日志中会有显示。

**使用的选项是-DWITH_TENSORRT=ON -DTENSORRT_ROOT="我的TensorRT库目录"
以下是cmake的log，帮忙确认一下是否已经开启TensorRT，谢谢！**


`-- Found Paddle host system: win32, version: 
-- Found Paddle host system's CPU: 48 cores
-- Selecting Windows SDK version 10.0.14393.0 to target Windows 10.0.17763.
-- CUDA compiler: x:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.0/bin/nvcc.exe, version: NVIDIA 10.0.130
-- CXX compiler: D:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/amd64/cl.exe, version: MSVC 19.0.24215.1
-- C compiler: D:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/amd64/cl.exe, version: MSVC 19.0.24215.1
-- AR tools: D:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/amd64/lib.exe
-- Use static C runtime time, refer to https://docs.microsoft.com/en-us/cpp/c-runtime-library/crt-library-features?view=vs-2019
-- CUDA detected: 10.0.130
-- WARNING: This is just a warning for publishing release.
      You are building GPU version without supporting different architectures.
      So the wheel package may fail on other GPU architectures.
      You can add -DCUDA_ARCH_NAME=All in cmake command
      to get a full wheel package to resolve this warning.
      While, this version will still work on local GPU architecture.
-- Automatic GPU detection failed. Building for all known architectures.
-- NVCC_FLAGS_EXTRA:  -gencode arch=compute_30,code=sm_30 -gencode arch=compute_35,code=sm_35 -gencode arch=compute_50,code=sm_50 -gencode arch=compute_52,code=sm_52 -gencode arch=compute_60,code=sm_60 -gencode arch=compute_61,code=sm_61 -gencode arch=compute_70,code=sm_70 -gencode arch=compute_75,code=sm_75
-- Current cuDNN header is X:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.0/include/cudnn.h Current cuDNN version is v7.6. 
-- Current TensorRT header is X:/Program Files/NVIDIA GPU Computing Toolkit/TensorRT-7.0.0.11/include/NvInfer.h. Current TensorRT version is v7. 
-- Disable XBYAK in Windows and MacOS
-- BOOST_VERSION: 1.41.0, BOOST_URL: http://paddlepaddledeps.bj.bcebos.com/boost_1_41_0.tar.gz
-- warp-ctc library: E:/Document/Paddle/Paddle-develop/build/third_party/install/warpctc/bin/warpctc.dll
-- MKLML_VER: mklml_win_2019.0.5.20190502, MKLML_URL: https://paddlepaddledeps.bj.bcebos.com/mklml_win_2019.0.5.20190502.zip
-- Found cblas and lapack in MKLML (include: E:/Document/Paddle/Paddle-develop/build/third_party/install/mklml/include, library: E:/Document/Paddle/Paddle-develop/build/third_party/install/mklml/lib/mklml.lib)
-- Set E:/Document/Paddle/Paddle-develop/build/third_party/install/mkldnn/lib to runtime path
-- MKLDNN library: E:/Document/Paddle/Paddle-develop/build/third_party/install/mkldnn/bin/mkldnn.lib
-- Using custom protobuf library in E:/Document/Paddle/Paddle-develop/build/third_party/install/protobuf.
-- Protobuf protoc executable: E:/Document/Paddle/Paddle-develop/build/third_party/install/protobuf/bin/protoc.exe
-- Protobuf-lite library: E:/Document/Paddle/Paddle-develop/build/third_party/install/protobuf/lib/libprotobuf-lite.lib
-- Protobuf library: E:/Document/Paddle/Paddle-develop/build/third_party/install/protobuf/lib/libprotobuf.lib
-- Protoc library: E:/Document/Paddle/Paddle-develop/build/third_party/install/protobuf/lib/libprotoc.lib
-- Protobuf version: 3.1
-- Download dependence[cudaerror] from http://paddlepaddledeps.bj.bcebos.com/cudaErrorMessage.tar.gz
-- Paddle version is 0.0.0
-- Cannot find CUPTI, GPU Profiling is incorrect.
-- Enable Intel OpenMP with E:/Document/Paddle/Paddle-develop/build/third_party/install/mklml/lib/libiomp5md.lib
-- On inference mode, will take place some specific optimization.
-- commit: 
-- branch: 
-- Configuring done
-- Generating done
-- Build files have been written to: E:/Document/Paddle/Paddle-develop/build
`

**Comment by cryoco** [comment]
> Current TensorRT header is X:/Program Files/NVIDIA GPU Computing Toolkit/TensorRT-7.0.0.11/include/NvInfer.h. Current TensorRT version is v7

从log来看是开启了TRT的，报出tensorrt_subgraph_pass has not been registered这个错误不太符合预期，麻烦您提供下编译的预测库和复现代码吧

**Comment by TianCaibailei** [comment]
> > Current TensorRT header is X:/Program Files/NVIDIA GPU Computing Toolkit/TensorRT-7.0.0.11/include/NvInfer.h. Current TensorRT version is v7
> 
> 从log来看是开启了TRT的，报出tensorrt_subgraph_pass has not been registered这个错误不太符合预期，麻烦您提供下编译的预测库和复现代码吧


**预测库太大，我上传到百度网盘：**
链接: https://pan.baidu.com/s/1HoIqKcUVTx-1R4i2R_76EQ 提取码: wav7 复制这段内容后打开百度网盘手机App，操作更方便哦

**使用的Demo代码和模型在此位置：**
https://github.com/PaddlePaddle/Paddle-Inference-Demo/tree/master/c%2B%2B/resnet50

**启用tensorrt的代码只是在此demo中的InitPredictor()函数中添加了关于TensorRT的代码：**
	config.EnableTensorRtEngine(1 << 20      	   /*workspace_size*/,
								FLAGS_batch_size   /*max_batch_size*/,
								3                  /*min_subgraph_size*/,
								paddle::AnalysisConfig::Precision::kFloat32 /*precision*/,
								false              /*use_static*/,
								false              /*use_calib_mode*/);

**Comment by TianCaibailei** [comment]
> > Current TensorRT header is X:/Program Files/NVIDIA GPU Computing Toolkit/TensorRT-7.0.0.11/include/NvInfer.h. Current TensorRT version is v7
> 
> 从log来看是开启了TRT的，报出tensorrt_subgraph_pass has not been registered这个错误不太符合预期，麻烦您提供下编译的预测库和复现代码吧

**昨晚开启TensorRT重新编译一份，vision内容如下：**
GIT COMMIT ID: 
WITH_MKL: ON
WITH_MKLDNN: ON
WITH_GPU: ON
CUDA version: 10.0
CUDNN version: v7.6
CXX compiler version: 19.0.24215.1
WITH_TENSORRT: ON
TensorRT version: v7

从这里看应该是已经开启了TensorRT了，经过对Demo项目（https://github.com/PaddlePaddle/Paddle-Inference-Demo/tree/master/c%2B%2B/resnet50）的测试，可以开启TensorRT预测，传参可以使用use_static=true方式，也可以使用use_calib_mode=true的方式，暂时未测试执行时间的差异，说明TensorRT已经可以正常跑了。

**但是当我迁移到另外一个“物体检测”模型的时候，仍然会报错，帮忙看看是什么原因，报错内容如下：**

0x00007FF9E4843B29 处(位于 detector.exe 中)引发的异常: Microsoft C++ 异常: paddle::platform::EnforceNotMet，位于内存位置 0x0000004B7594CE80 处。
0x00007FF9E4843B29 处(位于 detector.exe 中)引发的异常: Microsoft C++ 异常: [rethrow]，位于内存位置 0x0000000000000000 处。
0x00007FF9E4843B29 处(位于 detector.exe 中)引发的异常: Microsoft C++ 异常: paddle::platform::EnforceNotMet，位于内存位置 0x0000004B7594CE80 处。
0x00007FF9E4843B29 处(位于 detector.exe 中)有未经处理的异常: Microsoft C++ 异常: paddle::platform::EnforceNotMet，位于内存位置 0x0000004B7594CE80 处。

**黑窗口输出内容如下：**

`WARNING: Logging before InitGoogleLogging() is written to STDERR
W0106 08:27:55.552467 10952 analysis_predictor.cc:1058] Deprecated. Please use CreatePredictor instead.
I0106 08:27:57.454380 10952 analysis_predictor.cc:139] Profiler is deactivated, and no profiling report will be generated.
I0106 08:27:57.479313 10952 analysis_predictor.cc:474] TensorRT subgraph engine is enabled
e[1me[35m--- Running analysis [ir_graph_build_pass]e[0m
e[1me[35m--- Running analysis [ir_graph_clean_pass]e[0m
e[1me[35m--- Running analysis [ir_analysis_pass]e[0m
e[32m--- Running IR pass [conv_affine_channel_fuse_pass]e[0m
e[32m--- Running IR pass [conv_eltwiseadd_affine_channel_fuse_pass]e[0m
e[32m--- Running IR pass [shuffle_channel_detect_pass]e[0m
e[32m--- Running IR pass [quant_conv2d_dequant_fuse_pass]e[0m
e[32m--- Running IR pass [delete_quant_dequant_op_pass]e[0m
e[32m--- Running IR pass [simplify_with_basic_ops_pass]e[0m
e[32m--- Running IR pass [embedding_eltwise_layernorm_fuse_pass]e[0m
e[32m--- Running IR pass [multihead_matmul_fuse_pass_v2]e[0m
e[32m--- Running IR pass [skip_layernorm_fuse_pass]e[0m
e[32m--- Running IR pass [conv_bn_fuse_pass]e[0m
I0106 08:27:57.977026 10952 graph_pattern_detector.cc:101] ---  detected 72 subgraphs
e[32m--- Running IR pass [fc_fuse_pass]e[0m
e[32m--- Running IR pass [tensorrt_subgraph_pass]e[0m
I0106 08:27:58.207365 10952 tensorrt_subgraph_pass.cc:119] ---  detect a sub-graph with 202 nodes
I0106 08:27:58.221328 10952 tensorrt_subgraph_pass.cc:338] Prepare TRT engine (Optimize model structure, Select OP kernel etc). This process may cost a lot of time.
E0106 08:27:59.014207 10952 helper.h:78] Parameter check failed at: Network.cpp::nvinfer1::Network::addInput::957, condition: isValidDims(dims, hasImplicitBatchDimension())
(InvalidArgument) Adding input image failed in TensorRT inference network. Please recheck your input.
  [Hint: input should not be null.] (at E:\Document\Paddle\Paddle-develop\paddle\fluid\inference\tensorrt\engine.cc:235)
  [Hint: If you need C++ stacktraces for debugging, please set `FLAGS_call_stack_level=2`.]`


模型文件和新编译出的dll已上传百度网盘，预测库位置如下：
链接: https://pan.baidu.com/s/1NVxr01Z4ywV8S1gTEgCZlQ 提取码: 8ys5 复制这段内容后打开百度网盘手机App，操作更方便哦

模型文件位置如下：
链接: https://pan.baidu.com/s/1fUJKPmzzdAg4BP7ZPzVo5A 提取码: gt37 复制这段内容后打开百度网盘手机App，操作更方便哦

使用的是PaddleX中关于C++的Demo：detect.cpp（paddlex/deploy/cpp/demo/detector.cpp），位置如下：
https://github.com/PaddlePaddle/PaddleX/blob/develop/deploy/cpp/demo/detector.cpp

**Comment by TianCaibailei** [comment]
@cryoco @zhiqiu @jiangjiajun 
大佬们，帮忙看一下是什么问题，谢谢啦。
ps：模型在不开启tensorRT时，可以正常预测。模型类型是yolov3，同时也测试过图像分类的模型，也是报同样的错误。
![报错](https://user-images.githubusercontent.com/69564975/103733539-eec71000-5024-11eb-912b-362bda895d1c.jpg)

**Comment by jiangjiajun** [comment]
好，我们在本地测试下先

**Comment by syyxsxx** [comment]
您好，PaddleX使用TensorRT进行推理，在导出inference模型得时候需要固定input_shape，固定input_shape导出inference模型后可以解决这个问题，具体可以参考
https://paddlex.readthedocs.io/zh_CN/develop/deploy/export_model.html

**Comment by Huihuihh** [comment]
遇到同样的问题，确实，原来paddlex导出的yolov3模型需要添加input_shape，才能使用tensorrt
