### ISSUE TITLE
在v2的API下，如何运行分布式训练

### ISSUE THREAD

**Issue by Karbit** [PaddlePaddle/Paddle#3003]
现在paddle的文档里针对分布式训练的介绍似乎还是原来v1的版本，见：
http://doc.paddlepaddle.org/doc/howto/usage/cluster/cluster_train_en.html
不知道在新的版本下如何运行分布式训练，有没有相关文档介绍，谢谢！

**Comment by typhoonzero** [comment]
这个PR还在Review和跟进中：https://github.com/PaddlePaddle/Paddle/pull/2072，merge之后会更新到网站上～

**Comment by Karbit** [comment]
好滴，谢谢~ 这个回复速度太赞了！
