### ISSUE TITLE
Paddle-Inference的golangDemo错误

### ISSUE THREAD

**Issue by mervyn81** [PaddlePaddle/Paddle#30039]
严格按照文档教程一步步操作, 在windows和Ubuntu中都无法运行.

_/root/go_projects/PaddleInference/paddle
../paddle/common.go:20:11: fatal error: paddle_c_api.h: No such file or directory
// #include <paddle_c_api.h>
^~~~~~~~~~~~~~~~
compilation terminated.

**Comment by shangzhizhou** [comment]
请提供完整的代码工程，方便复现问题，谢谢。

**Comment by qili93** [comment]
@mervyn81  
Golang demo的文档和代码都有所更新，请参照最新的中文文档
https://paddle-inference.readthedocs.io/en/latest/quick_start/go_demo.html

其中`paddle_c_api.h` 位于预测库文件夹中的这个位置，


![image](https://user-images.githubusercontent.com/16605440/103395383-e7a58b00-4b68-11eb-91a0-797c1c1ee852.png)

> 注意运行godemo之前需要现对文件夹进行如下2步操作，否则无法找到`paddle_c_api.h` 头文件

![image](https://user-images.githubusercontent.com/16605440/103395419-086de080-4b69-11eb-937f-60801191e570.png)

**Comment by mervyn81** [comment]
@qili93

> Golang demo的文档和代码都有所更新，请参照最新的中文文档
> https://paddle-inference.readthedocs.io/en/latest/quick_start/go_demo.html
> 
> 其中`paddle_c_api.h` 位于预测库文件夹中的这个位置，
> 
> ![image](https://user-images.githubusercontent.com/16605440/103395383-e7a58b00-4b68-11eb-91a0-797c1c1ee852.png)
> 
> > 注意运行godemo之前需要现对文件夹进行如下2步操作，否则无法找到`paddle_c_api.h` 头文件
> 
> ![image](https://user-images.githubusercontent.com/16605440/103395419-086de080-4b69-11eb-937f-60801191e570.png)

对不起, 图片我看不到, 但是我已经按照文档那两个步骤:
1.将本章节 第1步 中的 paddle_inference_c_install_dir 移到到 Paddle/go 目录下，并将 paddle_inference_c_install_dir 重命名为 paddle_c
2.本章节 第2步 中下载的模型和数据文件夹 data 移动到 Paddle/go 目录下

包括 : export LD_LIBRARY_PATH=`pwd`/paddle_c/paddle/lib:$LD_LIBRARY_PATH
这是windows上的错误信息:

GOROOT=C:\Go #gosetup
GOPATH=C:\Users\Administrator\go #gosetup
C:\Go\bin\go.exe build -o C:\Users\Administrator\AppData\Local\Temp\___go_build_mobilenet_go.exe "C:\Users\Administrator\go\Paddle Inference\demo\mobilenet.go" #gosetup
# _/C_/Users/Administrator/go/Paddle_Inference/paddle
..\paddle\common.go:20:11: fatal error: paddle_c_api.h: No such file or directory
 // #include <paddle_c_api.h>
           ^~~~~~~~~~~~~~~~
compilation terminated.

代码的话, 能不能在QQ群里传呢? 太大, GitHub太慢了

**Comment by xox9001** [comment]
我也是一样的错误，都是按文档上做的
