### ISSUE TITLE
如何查看网络结构

### ISSUE THREAD

**Issue by cklient** [PaddlePaddle/Paddle#30043]
怎样可视化查看网络结构

**Comment by GaoWei8** [comment]
可以参考官网教程：https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/tutorial/quick_start/high_level_api/high_level_api.html#id12
或：https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/guides/03_VisualDL/visualdl.html
