### ISSUE TITLE
Python如何生成TensorRT的校准表？

### ISSUE THREAD

**Issue by yeyupiaoling** [PaddlePaddle/Paddle#30048]
- PaddlePaddle 1.8.5
 - windows 10

我在这个文档上看到将Float32的模型转换成Int8的模型的介绍，请问如何使用Python实现这个生成校准表呢？
https://www.paddlepaddle.org.cn/documentation/docs/zh/advanced_guide/performance_improving/inference_improving/paddle_tensorrt_infer.html#a-name-paddle-trt-int8-paddle-trt-int8-a

https://github.com/PaddlePaddle/Paddle-Inference-Demo/blob/ff8091c4ce87c591a7d89b95fa1e1f47ebcc2a5d/python/paddle_trt/infer_trt_ernie.py#L17-L22

**Comment by shangzhizhou** [comment]
准备好真实业务场景的数据，配置开启TensorRT的时候use_calib_mode设置为true，此时进入统计输入数据，生成校准表的状态，数据输入完毕后，请保证程序正常退出（predictor的析构函数正常调用），即可生成校准表到模型文件目录。下次启动use_calib_mode设置为false，程序便会加载校准表（精度请设置为int8）

**Comment by yeyupiaoling** [comment]
@shangzhizhou 关键是这个数据如何输入，能否给一个简单dome看看，

**Comment by shangzhizhou** [comment]
您好，和正常的推理过程是一致的，demo可以参考https://github.com/PaddlePaddle/Paddle-Inference-Demo/tree/master/c%2B%2B

**Comment by yeyupiaoling** [comment]
@shangzhizhou 好的，解决了。谢谢。
