### ISSUE TITLE
dockerfile里面好像没有启动ssh服务的命令

### ISSUE THREAD

**Issue by Hitvz** [PaddlePaddle/Paddle#3005]
# Configure OpenSSH server. c.f. https://docs.docker.com/engine/examples/running_ssh_service
RUN mkdir /var/run/sshd
RUN echo 'root:root' | chpasswd
RUN sed -ri 's/^PermitRootLogin\s+.*/PermitRootLogin yes/' /etc/ssh/sshd_config
RUN sed -ri 's/UsePAM yes/#UsePAM yes/g' /etc/ssh/sshd_config
EXPOSE 22

这上面是dockerfile默认的内容，但是并没有启动openssh的命令啊，按照官方文档应该说可以后台运行--docker run -d -p 2202:22 -p 8888:8888 paddledev/paddle:<version>-dev
再运行--ssh -p 2202 root@localhost
但是openssh服务都没开启，远程被拒绝，是不是应该加入下面这个命令
CMD ["/usr/sbin/sshd", "-D"]
当然我没有试过构建过，但是拉取（pull）的镜像都是没有openssh-server的这个我可以确定，dockerfile里面有安装openssh-server的命令，但是却没有发现开启服务的相关命令。安装了ssh服务又不开启。

**Comment by gangliao** [comment]
你不好 不知道你用的是哪一个docker image。  

目前Paddle Docker确实没有内置 openssh-server. @typhoonzero @Yancey1989

**Comment by Yancey1989** [comment]
Hi @Hitvz , 只有在开发环境镜像中才会装有OpenSSH服务, 代码见：https://github.com/PaddlePaddle/Paddle/blob/develop/Dockerfile#L79， 镜像的话请使用paddlepaddle/paddle:latest-dev

**Comment by Hitvz** [comment]
@Yancey1989 是的，有没考虑过，在在开发版本（dev）中，添加openssh-server，并添加自启，到底jupyter notebook没有ide（比如PyCharm）调试（远程调试）的感觉。我现在的做法是安装openssh，再docker commit一下，最后自己写个脚本辅助启动，不知道有没这添加的考虑。
