### ISSUE TITLE
c++预测API，如何载入VGG预训练好的模型？

### ISSUE THREAD

**Issue by GreenValue** [PaddlePaddle/Paddle#30057]
- 版本、环境信息：
    1）PaddlePaddle版本：1.8.5
    4）系统环境：nvidia_docker 1.8.5-gpu-cuda10.0-cudnn7
-预测信息
    1）C++预测：
      fluid_inference_c_install_dir# cat version.txt 
      GIT COMMIT ID: 
      WITH_MKL: OFF
      WITH_MKLDNN: OFF
      WITH_GPU: ON
      CUDA version: 10.0
      CUDNN version: v7.6
      CXX compiler version: 4.8.5
      WITH_TENSORRT: ON
      TensorRT version: v6
    2）CMake包含路径的完整命令
    3）API信息（如调用请提供）
    4）预测库来源：https://paddle-imagenet-models-name.bj.bcebos.com/VGG19_pretrained.tar
    5）预测样列来源：https://paddle-inference-dist.bj.bcebos.com/tensorrt_test/paddle_inference_sample_v1.7.tar.gz

- 复现信息：
  ①我使用VGG19，故预测库已解压
VGG19_pretrained/
├── conv1_1_weights
├── conv1_2_weights
├── conv2_1_weights
├── conv2_2_weights
├── conv3_1_weights
├── conv3_2_weights
├── conv3_3_weights
├── conv3_4_weights
├── conv4_1_weights
├── conv4_2_weights
├── conv4_3_weights
├── conv4_4_weights
├── conv5_1_weights
├── conv5_2_weights
├── conv5_3_weights
├── conv5_4_weights
├── fc6_offset
├── fc6_weights
├── fc7_offset
├── fc7_weights
├── fc8_offset
└── fc8_weights
  ② 代码已指定model路径
  DEFINE_string(dirname, "./VGG19_pretrained", "Directory of the inference model.");
  config->SetModel(FLAGS_dirname);
  ③编译后运行  ./mobilenet_test 
  
- 问题描述：报错   Error: Cannot open file ./VGG19_pretrained/__model__ at (/paddle/paddle/paddle/fluid/inference/api/analysis_predictor.cc:733)
 **但VGG19_pretrained里面也没有model文件呀！**
- 日志
I1231 11:57:43.253325 18060 analysis_predictor.cc:138] Profiler is deactivated, and no profiling report will be generated.
terminate called after throwing an instance of 'paddle::platform::EnforceNotMet'
  what():  

--------------------------------------------
C++ Call Stacks (More useful to developers):
--------------------------------------------
0   std::string paddle::platform::GetTraceBackString<char const*>(char const*&&, char const*, int)
1   paddle::platform::EnforceNotMet::EnforceNotMet(std::__exception_ptr::exception_ptr, char const*, int)
2   paddle::AnalysisPredictor::LoadProgramDesc()
3   paddle::AnalysisPredictor::PrepareProgram(std::shared_ptr<paddle::framework::ProgramDesc> const&)
4   paddle::AnalysisPredictor::Init(std::shared_ptr<paddle::framework::Scope> const&, std::shared_ptr<paddle::framework::ProgramDesc> const&)
5   std::unique_ptr<paddle::PaddlePredictor, std::default_delete<paddle::PaddlePredictor> > paddle::CreatePaddlePredictor<paddle::AnalysisConfig, (paddle::PaddleEngineKind)2>(paddle::AnalysisConfig const&)
6   std::unique_ptr<paddle::PaddlePredictor, std::default_delete<paddle::PaddlePredictor> > paddle::CreatePaddlePredictor<paddle::AnalysisConfig>(paddle::AnalysisConfig const&)

----------------------
Error Message Summary:
----------------------
Error: **Cannot open file ./VGG19_pretrained/__model__ at (/paddle/paddle/paddle/fluid/inference/api/analysis_predictor.cc:733)**

Aborted (core dumped)

**Comment by qili93** [comment]
@GreenValue VGG19_pretrained文件里面只有训练参数没有模型文件，这个是保存的checkpoint, 不是推理模型，推理模型需要用save_inference_io文件保存下来，你可以参考从这里下载推理模型，是有模型文件的(有VGG16和VGG19)
https://paddle-lite.readthedocs.io/zh/latest/introduction/support_model_list.html

如果你要自己训练模型，那一定需要用这个人API把模型保存下来
https://www.paddlepaddle.org.cn/documentation/docs/zh/api_cn/io_cn/save_inference_model_cn.html#save-inference-model

**Comment by GreenValue** [comment]
@qili93 感谢。可以加载 VGG19的推理模型。

- 请问如何input一张图片呢？

bool test_map_cnn(int batch_size, int repeat) {
  AnalysisConfig config;
  PrepareTRTConfig(&config, batch_size);
  auto predictor = CreatePaddlePredictor(config);

  int channels = 3;
  int height = 224;
  int width = 224;
  int input_num = channels * height * width * batch_size;

### 我的这个修改对吗？ 修改开始↓
#if 1 // 使用VGG推理模型
  std::string image_data;
  std::string image_path = "./test_img/1.jpg";
  common::Files::instance()->read_one_file_to_string(image_path, image_data);
  __float* input = **(float*)(image_data.data()); // input若是图片，那就把图片的内容的指针这样赋值过去，就可以了吗？__
#else
  // prepare inputs
  float *input = new float[input_num];
  memset(input, 0, input_num * sizeof(float));
#endif
### 修改结束↑
  auto input_names = predictor->GetInputNames();
  auto input_t = predictor->GetInputTensor(input_names[0]);
  input_t->Reshape({batch_size, channels, height, width});
  input_t->copy_from_cpu(input);

  。。。。。。省略。。。。。。
}

**Comment by GreenValue** [comment]
#30068 
我新建了issue，故关闭这个

**Comment by GreenValue** [comment]
@qili93 
这里下载推理模型，可以用paddle Hub来加载，进行预测吗？若可以，如何操作？
https://paddle-lite.readthedocs.io/zh/latest/introduction/support_model_list.html

**Comment by GreenValue** [comment]
> @GreenValue VGG19_pretrained文件里面只有训练参数没有模型文件，这个是保存的checkpoint, 不是推理模型，推理模型需要用save_inference_io文件保存下来，你可以参考从这里下载推理模型，是有模型文件的(有VGG16和VGG19)
> https://paddle-lite.readthedocs.io/zh/latest/introduction/support_model_list.html
> 

上面链接中VGG19是通过x2paddle转换的？还是自己训练出来的？
![image](https://user-images.githubusercontent.com/16701660/106112019-bc25b880-6187-11eb-81b7-36e480812027.png)

@qili93 
x2paddle --framework=caffe --prototxt=VGG_ILSVRC_19_layers_deploy.prototxt --weight=VGG_ILSVRC_19_layers.caffemodel --save_dir=pd_model --paddle_type static

VGG_ILSVRC_19_layers.caffemodel：
[http://www.robots.ox.ac.uk/~vgg/software/very_deep/caffe/VGG_ILSVRC_19_layers.caffemodel](url)
