### ISSUE TITLE
paddle1.8.5动态图的GRUUnit

### ISSUE THREAD

**Issue by btobab** [PaddlePaddle/Paddle#30060]
paddle1.8.5动态图的GRUUnit文档给出的例子不是很详细，还是不太会用，有没有详细一些的讲解丫

**Comment by gfwm2013** [comment]
@IamDestiny 请问你想要是什么方面的讲解？是关于计算步骤还是其他什么的呢？

**Comment by btobab** [comment]
@gfwm2013 是具体使用方面的讲解

**Comment by btobab** [comment]
能写篇博客讲讲吗？

**Comment by gfwm2013** [comment]
@IamDestiny 如果是关于使用方面的困惑，可能需要你具体说明一下你的困惑，要不然也很难较为精准的解决你现在遇到的问题

**Comment by btobab** [comment]
我在做NLP，是关于文本生成的，我的困惑是在模型搭建中，GRUUnit要如何实例化，并且forward过程中hidden_state要如何如何初始化以及如何循环调用
