### ISSUE TITLE
ubuntu 18.04 cuda11安装paddle时出现问题

### ISSUE THREAD

**Issue by znzhou3069** [PaddlePaddle/Paddle#30061]
ubuntu 18.04
cuda11

xx@xxx:~$ python -m pip install paddlepaddle-gpu==2.0.0rc1.post110 -f https://paddlepaddle.org.cn/whl/stable.html
Collecting paddlepaddle-gpu==2.0.0rc1.post110
  Could not find a version that satisfies the requirement paddlepaddle-gpu==2.0.0rc1.post110 (from versions: 1.2.0.post85, 1.2.0.post87, 1.2.0.post97, 1.2.1.post85, 1.2.1.post87, 1.2.1.post97, 1.3.0.post85, 1.3.0.post87, 1.3.0.post97, 1.3.1.post85, 1.3.1.post87, 1.3.1.post97, 1.3.2.post85, 1.3.2.post87, 1.3.2.post97, 1.4.0.post85, 1.4.0.post87, 1.4.0.post97, 1.4.1.post85, 1.4.1.post87, 1.4.1.post97, 1.5.0.post87, 1.5.0.post97, 1.5.0.post107, 1.5.1.post87, 1.5.1.post97, 1.5.1.post107, 1.5.2.post87, 1.5.2.post97, 1.5.2.post107, 1.6.0rc0.post107, 1.6.0.post97, 1.6.0.post107, 1.6.1.post97, 1.6.1.post107, 1.6.2.post97, 1.6.2.post107, 1.6.3.post97, 1.6.3.post107, 1.7.0.post97, 1.7.0.post107, 1.7.1.post97, 1.7.1.post107, 1.7.2.post97, 1.7.2.post107, 1.8.0.post97, 1.8.0.post107, 1.8.1.post97, 1.8.1.post107, 1.8.2.post97, 1.8.2.post107, 1.8.3.post97, 1.8.3.post107, 1.8.4.post97, 1.8.4.post107, 1.8.5.post97, 1.8.5.post107, 2.0.0a0, 2.0.0b0, 2.0.0rc0, 2.0.0rc1)
No matching distribution found for paddlepaddle-gpu==2.0.0rc1.post110

**Comment by raindrops2sea** [comment]
有没有对照对应的安装说明页排查一下：https://www.paddlepaddle.org.cn/install/quick?docurl=/documentation/docs/zh/2.0-rc1/install/pip/linux-pip.html   比如是不是python或pip版本问题。

**Comment by zhwesky2010** [comment]
@znzhou3069 您好，-f 指定的whl包查找路径https://paddlepaddle.org.cn/whl/stable.html   没有生效，是pip版本低于20.2.2就没法使用-f正确指定路径，麻烦用 ``python --version`` 和 ``python -m pip --version`` 先看下版本哈，如果低于pip版本低于`20.2.2`，先用 python -m pip install --upgrade pip 升级到下就可以了哈

**Comment by znzhou3069** [comment]
确实是pip的问题，已通过更新pip解决。感谢支持。
