### ISSUE TITLE
ubuntu18.04虚拟机make编译错误fatal: unable to access 'https://gitlab.com/libeigen/eigen.git/': gnutls_handshake() failed: Error in the pull function.

### ISSUE THREAD

**Issue by hitomi-black** [PaddlePaddle/Paddle#30067]
按照官网操作：
cmake -DFLUID_INFERENCE_INSTALL_DIR=$PADDLE_ROOT \
      -DCMAKE_BUILD_TYPE=Release \
      -DWITH_FLUID_ONLY=ON \
      -DWITH_SWIG_PY=OFF \
      -DWITH_PYTHON=OFF \
      -DWITH_MKL=OFF \
      -DWITH_GPU=OFF  \
      -DON_INFER=ON \
      ..
make
之后
出现如下错误：
Cloning into 'extern_eigen3'...
fatal: unable to access 'https://gitlab.com/libeigen/eigen.git/': gnutls_handshake() failed: Error in the pull function.
Cloning into 'extern_eigen3'...
fatal: unable to access 'https://gitlab.com/libeigen/eigen.git/': gnutls_handshake() failed: Error in the pull function.
Cloning into 'extern_eigen3'...
fatal: unable to access 'https://gitlab.com/libeigen/eigen.git/': gnutls_handshake() failed: Error in the pull function.
-- Had to git clone more than once:
          3 times.
CMake Error at /home/smuvision/Downloads/Paddle/build/third_party/eigen3/tmp/extern_eigen3-gitclone.cmake:66 (message):
  Failed to clone repository: 'https://gitlab.com/libeigen/eigen.git'

CMakeFiles/extern_eigen3.dir/build.make:90: recipe for target 'third_party/eigen3/src/extern_eigen3-stamp/extern_eigen3-download' failed
make[2]: *** [third_party/eigen3/src/extern_eigen3-stamp/extern_eigen3-download] Error 1
CMakeFiles/Makefile2:196: recipe for target 'CMakeFiles/extern_eigen3.dir/all' failed
make[1]: *** [CMakeFiles/extern_eigen3.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by liym27** [comment]
报错显示无法访问 https://gitlab.com/libeigen/eigen.git/，该问题本地无法复现。
请问是否在您的机器环境下，是否可以成功使用 git clone https://gitlab.com/libeigen/eigen.git?

**Comment by hitomi-black** [comment]
> 报错显示无法访问 [https://gitlab.com/libeigen/eigen.git/，该问题本地无法复现。](https://gitlab.com/libeigen/eigen.git/%EF%BC%8C%E8%AF%A5%E9%97%AE%E9%A2%98%E6%9C%AC%E5%9C%B0%E6%97%A0%E6%B3%95%E5%A4%8D%E7%8E%B0%E3%80%82)
> 请问是否在您的机器环境下，是否可以成功使用 git clone https://gitlab.com/libeigen/eigen.git?

是的，无法访问https开头的，只能访问http开头的，请问如何设置，把make时的clone链接全部换成http格式

**Comment by liym27** [comment]
建议优先配置机器环境，支持访问https。
如果想替换https，可以直接将 cmake 文件中的 https 替换即可。
如，https://gitlab.com/libeigen/eigen.git 的替换位置在这里：https://github.com/PaddlePaddle/Paddle/blob/develop/cmake/external/eigen.cmake#L20
