### ISSUE TITLE
Paddle2.0如何使用高级API对每个batch预测结果单独做处理？

### ISSUE THREAD

**Issue by iotctech** [PaddlePaddle/Paddle#30069]
## 问题描述
使用高级API预测过程中，需要对每个batch size的结果单独处理后，在拼接到一起，调用`Model. predict()`方法，底层API调用没有问题，想了解下是否可以通过`Callback`来实现每个batch数据单独处理。

在`on_predict_batch_end()`回调如何获取每个batch预测的result？

另外，使用如下代码测试，推理感觉还是一张一张图片单独预测的，感觉速度非常慢，是什么原因呢？
```
    resnet = paddle.vision.resnet101(num_classes=5)
    model = paddle.Model(resnet, input)
    model.load(public_para["modle_path"])
    model.prepare()
    
    test_loader = paddle.io.DataLoader(test_dataset,
                                       batch_size=public_para["batch_size"],
                                       num_workers=5)
    
    for i, image in enumerate(test_loader()):
        predictions.extend([model.predict_batch(image)[0][0].argmax()])
```

**Comment by liym27** [comment]
>使用高级API预测过程中，需要对每个batch size的结果单独处理后，在拼接到一起，调用Model. predict()方法，底层API调用没有问题，想了解下是否可以通过Callback来实现每个batch数据单独处理。

能够提供下更详细的使用场景，以及复现代码？

> 另外，使用如下代码测试，推理感觉还是一张一张图片单独预测的，感觉速度非常慢，是什么原因呢？

这个需要麻烦您提供下您测试的速度数据

**Comment by iotctech** [comment]
> > 使用高级API预测过程中，需要对每个batch size的结果单独处理后，在拼接到一起，调用Model. predict()方法，底层API调用没有问题，想了解下是否可以通过Callback来实现每个batch数据单独处理。
> 
> 能够提供下更详细的使用场景，以及复现代码？
> 
> > 另外，使用如下代码测试，推理感觉还是一张一张图片单独预测的，感觉速度非常慢，是什么原因呢？
> 
> 这个需要麻烦您提供下您测试的速度数据

使用场景是测试数据，通过Model.predict接口，分batch送入，每个batch返回的结果需要单独处理一下，去除不需要的数据，存入list，想要通过Callback方式实现，能否在Callback中获取到每个batch返回的预测结果数据？

**Comment by liym27** [comment]
@qingqing01 你好，麻烦看一下这个问题，高级API model.predict使用 callback参数的用法

**Comment by qingqing01** [comment]
@iotctech 

传递给Callbacks的logs里没有预测的结果，参考如下代码，因此无法通过callback实现。

https://github.com/PaddlePaddle/Paddle/blob/88e6dc4ac5a5f0a4ed0c54365e4210528da6f3ab/python/paddle/hapi/model.py#L1823-L1828

其他方式:

1. 如你上面使用方法，采用Model.predict_batch接口。
2. 在Model的forward里计算之后，对每个batch的数据先做处理，比如把argmax放到forward里。使用Model.predict接口。

**Comment by iotctech** [comment]
@qingqing01 明白了，非常感谢。
