### ISSUE TITLE
jetson nano 使用CPU推理,获得结果正确,使用GPU却无法得到正常结果. 

### ISSUE THREAD

**Issue by githubchange** [PaddlePaddle/Paddle#30064]
#转自：https://github.com/PaddlePaddle/Paddle-Lite/issues/4680
设备:jetson nano
cuda:10.2.89
opencv 4.1.1
trt:7.1.3.0
cudnn:8.0.0.180
设置predictor代码:

             def create_(model, params): 

                      config = AnalysisConfig(model, params)  # 解析模型

                      config.enable_use_gpu(memory_pool_init_size_mb=100, device_id=0)

                      config.switch_ir_optim(True)   # IR优化(默认开启)

                        # 开启TensorRT预测，精度为fp32，开启int8离线量化
                         #config.enable_tensorrt_engine(
                         #                            workspace_size = 1<<30,
                         #                            max_batch_size=1, 
                         #                            min_subgraph_size=5,
                         #                            precision_mode=AnalysisConfig.Precision.Float32,
                         #                            use_static=True, 
                         #                            use_calib_mode=False)
                            
                     config.switch_use_feed_fetch_ops(False) # i

                     config.enable_memory_optim()

                     config.switch_specify_input_names(True)

                     predictor = create_paddle_predictor(config)

                      return predictor
将其中config.enable_use_gpu(memory_pool_init_size_mb=100, device_id=0)注释掉,可以获得正确结果.

目前在C++推理下同样出现该问题，develop分支及2.0.0*分支都已尝试。推理程序已在window(cuda10.0 cudnn7.6)下验证可得到正确结果。

**Comment by jiweibo** [comment]
能否提供下模型，我复现下

**Comment by githubchange** [comment]
模型已发送请查收。

**Comment by githubchange** [comment]
模型已发送请查收。

**Comment by lleesg** [comment]
met the same problem,  mark for solution..

**Comment by tianhechao** [comment]
tx2同样的现象

**Comment by suiyi1420** [comment]
一样遇到这种问题，CPU模式下识别正常，使用GPU识别结果都是错的，或者根本识别不到

[https://github.com/PaddlePaddle/PaddleOCR/issues/2749](url)

**Comment by QQ39272490** [comment]
楼上的你们的问题解决了吗？

**Comment by MiShiDeHaiLuo** [comment]
一样的问题·····不过现在GPU可以推理但是无法开启cudnn和tensor加速

**Comment by blackhitomi** [comment]
请问这个问题解决了吗 我也遇到一样的问题，x86下的GPU推理正常，jetson nano的GPU推理结果不正常：
https://github.com/PaddlePaddle/PaddleOCR/issues/6395
