### ISSUE TITLE
VGG19推理模型，c++预测API（AnalysisPredictor）预测时，在paddle_inference_sample_v1.7 基础上，如何input一张图片？

### ISSUE THREAD

**Issue by GreenValue** [PaddlePaddle/Paddle#30068]
- 版本、环境信息：
   1）PaddlePaddle版本：1.8.5
   2）系统环境：nvidia_docker 1.8.5-gpu-cuda10.0-cudnn7
   3）C++预测库：fluid_inference_c_install_dir# cat version.txt
GIT COMMIT ID:
WITH_MKL: OFF
WITH_MKLDNN: OFF
WITH_GPU: ON
CUDA version: 10.0
CUDNN version: v7.6
CXX compiler version: 4.8.5
WITH_TENSORRT: ON
TensorRT version: v6
   4）推理模型文件：https://paddle-lite.readthedocs.io/zh/latest/introduction/support_model_list.html
   5）预测样列来源：https://paddle-inference-dist.bj.bcebos.com/tensorrt_test/paddle_inference_sample_v1.7.tar.gz

- 在paddle_inference_sample_v1.7\sample\inference\mobilenet_test.cc中的test_map_cnn函数中， 请问如何input一张图片呢？

bool test_map_cnn(int batch_size, int repeat) {
AnalysisConfig config;
PrepareTRTConfig(&config, batch_size);
auto predictor = CreatePaddlePredictor(config);

int channels = 3;
int height = 224;
int width = 224;
int input_num = channels * height * width * batch_size;

**我的这个修改对吗？ 修改开始**↓
#if 1 // 使用VGG推理模型
std::string image_data;
std::string image_path = "./test_img/1.jpg";
common::Files::instance()->read_one_file_to_string(image_path, image_data); // 读取图片内容到string
float* input = *(float)(image_data.data()); **// input若是图片，那就把图片的内容的指针这样赋值过去，就可以了吗？**
#else
// prepare inputs
float *input = new float[input_num];
memset(input, 0, input_num * sizeof(float));
#endif

**修改结束↑**
auto input_names = predictor->GetInputNames();
auto input_t = predictor->GetInputTensor(input_names[0]);
input_t->Reshape({batch_size, channels, height, width});
input_t->copy_from_cpu(input);

。。。。。。省略。。。。。。
}

**Comment by liym27** [comment]
您好，请问您修改的文件来源是哪里的呢？
下载链接来自哪里？

**Comment by GreenValue** [comment]
预测示实例
下载：https://paddle-inference-dist.bj.bcebos.com/tensorrt_test/paddle_inference_sample_v1.7.tar.gz
解压后：在paddle_inference_sample_v1.7\sample\inference\mobilenet_test.cc中的test_map_cnn函数

**Comment by liym27** [comment]
因为该问题需要找到负责该样例的同事，所以麻烦问下 下载链接在哪里看到的呢？

**Comment by GreenValue** [comment]
官网：https://www.paddlepaddle.org.cn/documentation/docs/zh/advanced_guide/inference_deployment/inference/native_infer.html#C++%E9%A2%84%E6%B5%8B%E6%A0%B7%E4%BE%8B%E7%BC%96%E8%AF%91%E6%B5%8B%E8%AF%95
![image](https://user-images.githubusercontent.com/16701660/103516894-3aa27980-4eac-11eb-86f4-ecb767b6bcd5.png)

**Comment by liym27** [comment]
好的，已反馈给相关同学。

**Comment by juncaipeng** [comment]
按照你提供的代码，只需要保证输入predictor tensor的指针是指向float类型的图像数据，具体图像数据的格式和数据类型，你需要自己考虑清楚。

这里有更多例子：https://paddle-inference.readthedocs.io/en/latest/#

**Comment by GreenValue** [comment]
float类型的图像数据？是什么意思？
譬如jpg图片，float类型的图片数据如何获取？
直接把jpg图片的内容读到内存中，然后内存强制转换为float类型，这似乎不合适吧？
请指导一下。 
这里面也没有读取图片的列子https://paddle-inference.readthedocs.io/en/latest/#

**Comment by GreenValue** [comment]
float类型的图片数据如何获取？
给个样列代码，就好了。

**Comment by juncaipeng** [comment]
这里面有挺多例子：https://paddle-inference.readthedocs.io/en/latest/#

**Comment by GreenValue** [comment]
我需要的是float类型的图片数据如何获取的列子。
您给的例子如下，input数据都是写成1了。但我的input数据是图片。图片如何输入呢？

- c++的列子

// 准备输入数据
int input_size = 1 * 3 * 224 * 224;
std::vector<float> input_data(input_size, 1);

- c的列子

  int input_size     = batch * channel * height * width;
  float* input_data  = malloc(sizeof(float) * input_size);
  int i = 0;
  for (i = 0; i < input_size ; i++){ 
      input_data[i] = 1.0f; 
  }

**Comment by juncaipeng** [comment]
这部分图像处理部分的知识+基础c++知识，请网上查看资料，推荐资料：https://www.opencv-srf.com/p/introduction.html

**Comment by GreenValue** [comment]
我写的函数
// |filename|:image path
bool readImage(const string& filename,
  const int height, const int width, const bool is_color) {
  // read file to open cv mat
  cv::Mat cv_img;
  int cv_read_flag = (is_color ? CV_LOAD_IMAGE_COLOR : CV_LOAD_IMAGE_GRAYSCALE);
  cv::Mat cv_img_origin = cv::imread(filename, cv_read_flag);
  if (!cv_img_origin.data) {
    LOG(ERROR) << "Could not open or find file " << filename;
    return false;
  }
  if (height > 0 && width > 0) { // resize
    cv::resize(cv_img_origin, cv_img, cv::Size(width, height));
  }
  else {
    cv_img = cv_img_origin;
  }

  // cv mat to buffer
  int n_channels = cv_img.channels();
  int n_height = cv_img.rows;
  int n_width = cv_img.cols;
  int n_buf_size = n_channels * n_height * n_width;
  std::string buffer(n_buf_size, ' ');
  for (int h = 0; h < n_height; ++h) {
    const uchar* ptr = cv_img.ptr<uchar>(h);
    int img_index = 0;
    for (int w = 0; w < n_width; ++w) {
      for (int c = 0; c < n_channels; ++c) {
        int datum_index = (c * n_height + h) * n_width + w;
        buffer[datum_index] = static_cast<char>(ptr[img_index++]);
      }
    }
  }

  // buffer to float vector
  std::vector<float> f_blob(n_buf_size, 0.0f);
  int i = 0;
  for (auto& it : buffer) f_blob[i++] = (float)(it); // 转为float

  /**/ now use f_blob**
  return true;
}
