### ISSUE TITLE
关于paddle2.0动态图API

### ISSUE THREAD

**Issue by qdd1234** [PaddlePaddle/Paddle#30063]
请问paddle2.0动态图API里面和pytorch里面repeat功能类似的API是什么

**Comment by jiweibo** [comment]
可参考expand和expand_as API

https://www.paddlepaddle.org.cn/documentation/docs/zh/2.0-rc1/api/paddle/tensor/manipulation/expand_as_cn.html
https://www.paddlepaddle.org.cn/documentation/docs/zh/2.0-rc1/api/paddle/tensor/manipulation/expand_cn.html

**Comment by jiweibo** [comment]
可参考expand和expand_as API

https://www.paddlepaddle.org.cn/documentation/docs/zh/2.0-rc1/api/paddle/tensor/manipulation/expand_as_cn.html
https://www.paddlepaddle.org.cn/documentation/docs/zh/2.0-rc1/api/paddle/tensor/manipulation/expand_cn.html
