### ISSUE TITLE
padddle1.8.5 无法查找到包是什么问题啊？

### ISSUE THREAD

**Issue by hdyzhuxun** [PaddlePaddle/Paddle#30070]
安装的CPU版本的padddle1.8.5    仅仅一个 import paddle.fluid   报错 
    module = self._system_import(name, *args, **kwargs)
ModuleNotFoundError: No module named 'paddle.fluid'; 'paddle' is not a package

**Comment by liym27** [comment]
您好，麻烦提供下安装环境以及安装指令，谢谢

**Comment by hdyzhuxun** [comment]
> 您好，麻烦提供下安装环境以及安装指令，谢谢

我已解决。谢谢啦
