### ISSUE TITLE
1.8动态图gru模型在py2正常运行，在py3下卡住

### ISSUE THREAD

**Issue by HawChang** [PaddlePaddle/Paddle#30088]
- 版本、环境信息：
    1）python环境有两个：

        2.7.15、3.7.9
    2）系统环境不变

        - Paddle version: 1.8.1
        - Paddle With CUDA: True
        - OS: CentOS 6.3
        - CUDA version: 10.2.89
        - cuDNN version: None.None.None
        - Nvidia driver version: 440.33.01
        - GPU：Tesla P40

- 训练信息

    单机，单卡

- 复现信息

    复现代码在[这里](https://github.com/HawChang/text_utils/tree/master/text_utils_v2/examples/test_py3)，直接运行test_py3.py即可。

- 问题描述：请详细描述您的问题，同步贴出报错信息、日志、可复现的代码片段
    搭建了GRU网络(出问题的网络)和LSTM网络(作对照)及其对应单测。
    - LSTM网络在python2&3下均可运行；
    - 但GRU网络在**python2下可运行，在python3下会卡住**，log日志停留在base_model文件的166行("train model start")，**且ctrl+c无反应，只能kill**。

        python2下GRU网络：
![image](https://user-images.githubusercontent.com/7113823/103527564-86a9ea00-4ebd-11eb-98c3-aad50bf24060.png)
        python3下GRU网络：
![image](https://user-images.githubusercontent.com/7113823/103527651-a4774f00-4ebd-11eb-995f-ff03459f4881.png)

    - 如果把gru的网络结构调小，例如:emb_dim=2、gru_dim=16、fc_hid_dim=32，在python3下可运行
        把test_py3.py中的GRU网络调小
![image](https://user-images.githubusercontent.com/7113823/103527878-fb7d2400-4ebd-11eb-91de-a77dd36a7eea.png)
        就不会卡住了
![image](https://user-images.githubusercontent.com/7113823/103527992-29faff00-4ebe-11eb-922b-156cad8d944c.png)

**Comment by liym27** [comment]
麻烦确认下python3 下，logging.info("train model start") 之后，具体卡在哪一步呢？

**Comment by HawChang** [comment]
卡在了199行backward：
![image](https://user-images.githubusercontent.com/7113823/103530412-59ac0600-4ec2-11eb-881c-7e250bcbdb9a.png)

**Comment by liym27** [comment]
好的，经沟通，梳理当前的问题：

model 1 对应 参数 w1; model 2 参数 w2
loss_a 由 model1 model2 共同计算的结果，即 loss_a 与 w1 w2 均有关
loss_b 仅与 model1 有关，即 loss_b 与 w1 有关

step 1: 计算出 loss_a 但 仅更新 w1 (未更新w2)
step 2: 然后，计算loss_b 「期望」更新 w2

当前无法 更新w2，是因为 loss_b 与 w2 无关。
期望：能更新 w2，因为 step_1 与 w2 相关（因为step1 更新 w1 时，用到了 w2 的值，即 w1与w2相关。
而 loss_b 与 w1 相关，也期望 loss_b 与 w2相关）

**Comment by liym27** [comment]
好的，也在线下进行同步沟通。当前正在跟进该问题。
