### ISSUE TITLE
dygraph模式下，手动更新模型后，梯度无法正确计算

### ISSUE THREAD

**Issue by liuyiding1993** [PaddlePaddle/Paddle#30080]
- 版本、环境信息：
    1）PaddlePaddle版本：1.8.5
    2）CPU： Intel(R) Xeon(R) CPU E5-2650 v4 @ 2.20GHz
    3）GPU： CUDA 9.0;  CUDNN: 7.0;  NVIDIA Tesla K40m
    4）系统环境：Python-2.7.8; 系统：3.10.0_3-0-0-7 #207 SMP Wed Jul 26 13:22:55 CST 2017 x86_64 x86_64 x86_64 GNU/Linux

demo代码：
```

import paddle.fluid as fluid
import numpy as np


if __name__ == '__main__':
    np_inp = np.array([[1.0, 2.0, -1.0]], dtype=np.float32)
    with fluid.dygraph.guard():
        var_inp = fluid.dygraph.to_variable(np_inp)
        var_inp.stop_gradient = True
        model = fluid.dygraph.Linear(3, 1)
        vnet = fluid.dygraph.Linear(3, 1)
        optimizer_vnet = fluid.optimizer.Adam(learning_rate=0.001, parameter_list=vnet.parameters())
        for batch_idx in range(1):
            model.train()
            cost = model(var_inp)
            weight = vnet(var_inp)
            loss = fluid.layers.reduce_mean(cost * weight)
            model.clear_gradients()
            g = fluid.dygraph.grad(loss, model.parameters(), retain_graph=True)

            state_dict = model.state_dict()
            for i, k in enumerate(state_dict):
                state_dict[k] -= 1e-2 * g[i]
            model.set_dict(state_dict)

            cost = model(var_inp)
            loss = fluid.layers.reduce_mean(cost)
            g = fluid.dygraph.grad(loss, vnet.parameters(), retain_graph=True)

```
报错：
Traceback (most recent call last):
  File "dygraph_demo.py", line 33, in <module>
    g = fluid.dygraph.grad(loss, vnet.parameters(), retain_graph=True)
  File "<decorator-gen-29>", line 2, in grad
  File "/home/ssd4/yiding/python_env/Python-2.7.8/lib/python2.7/site-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
    return wrapped_func(*args, **kwargs)
  File "/home/ssd4/yiding/python_env/Python-2.7.8/lib/python2.7/site-packages/paddle/fluid/framework.py", line 216, in __impl__
    return func(*args, **kwargs)
  File "/home/ssd4/yiding/python_env/Python-2.7.8/lib/python2.7/site-packages/paddle/fluid/dygraph/base.py", line 563, in grad
    create_graph, retain_graph, allow_unused, only_inputs)
paddle.fluid.core_avx.EnforceNotMet: 

--------------------------------------------
C++ Call Stacks (More useful to developers):
--------------------------------------------
0   std::string paddle::platform::GetTraceBackString<std::string const&>(std::string const&, char const*, int)
1   paddle::platform::EnforceNotMet::EnforceNotMet(std::string const&, char const*, int)
2   paddle::imperative::PartialGradTask::CreateResult()
3   paddle::imperative::PartialGradTask::Run()
4   paddle::imperative::PartialGradEngine::Execute()

----------------------
Error Message Summary:
----------------------
InvalidArgumentError: The 0-th input does not appear in the backward graph. Please check the input variable or set allow_unused=True to get None result.
  [Hint: Expected allow_unused_ == true, but received allow_unused_:0 != true:1.] at (/paddle/paddle/fluid/imperative/partial_grad_engine.cc:1012)

这个错的意思就是最后一行计算梯度的时候没有发现loss和vnet的参数有关，但是实际上是有影响的，这个反向图没有建立起来，请问如何让梯度可以回传到vnet，从而进行vnet的更新。谢谢。

**Comment by liym27** [comment]
从你的模型代码来看，loss 与 vnet没关系。

demo的核心部分：
```
cost = model(var_inp)
weight = vnet(var_inp)
loss = fluid.layers.reduce_mean(cost * weight)
model.clear_gradients()
g = fluid.dygraph.grad(loss, model.parameters(), retain_graph=True)

cost = model(var_inp)
loss = fluid.layers.reduce_mean(cost)  # ！这个loss 显然与 model有关，与vnet无关。这行应该删掉，才符合预期

g = fluid.dygraph.grad(loss, vnet.parameters(), retain_graph=True)
```

**Comment by liuyiding1993** [comment]
> 从你的模型代码来看，loss 与 vnet没关系。
> 
> demo的核心部分：
> 
> ```
> cost = model(var_inp)
> weight = vnet(var_inp)
> loss = fluid.layers.reduce_mean(cost * weight)
> model.clear_gradients()
> g = fluid.dygraph.grad(loss, model.parameters(), retain_graph=True)
> 
> cost = model(var_inp)
> loss = fluid.layers.reduce_mean(cost)  # ！这个loss 显然与 model有关，与vnet无关。这行应该删掉，才符合预期
> 
> g = fluid.dygraph.grad(loss, vnet.parameters(), retain_graph=True)
> ```

感谢回复。您copy出来的demo核心部分没有包括model更新这一步：
```
state_dict = model.state_dict()
for i, k in enumerate(state_dict):
    state_dict[k] -= 1e-2 * g[i]
    model.set_dict(state_dict)
```
model更新时的梯度是和vnet有关的，所以更新之后的model也和vnet有关，从而计算出来的loss应该也是和vnet有关的。

这个模型有人用pytorch实现过，原理是没问题的，可以参考以下代码的196-227行，我的demo是基于这个原理实现的。
https://github.com/xjtushujun/meta-weight-net/blob/bd1fd3e297c59df7c5264fb636c67d8ee03bcf0d/MW-Net.py#L79

**Comment by liym27** [comment]
好的，经沟通，梳理当前的问题：

model 1 对应 参数 w1; model 2 参数 w2
loss_a 由 model1 model2 共同计算的结果，即 loss_a 与 w1 w2 均有关
loss_b 仅与 model1 有关，即 loss_b 与 w1 有关

step 1: 计算出 loss_a 但 仅更新 w1 (未更新w2)
step 2: 然后，计算loss_b 「期望」更新 w2

当前无法 更新w2，是因为 loss_b 与 w2 无关。
期望：能更新 w2，因为 step_1 与 w2 相关（因为step1 更新 w1 时，用到了 w2 的值，即 w1与w2相关。
而 loss_b 与 w1 相关，也期望 loss_b 与 w2相关）
