### ISSUE TITLE
gridsample不支持高分辨率图采样产出低分辨率图

### ISSUE THREAD

**Issue by zzchust** [PaddlePaddle/Paddle#30082]
PaddlePaddle版本：1.8.0
gridsample官方过说明： https://www.paddlepaddle.org.cn/documentation/docs/zh/api_cn/layers_cn/grid_sampler_cn.html#grid-sampler

实际使用问题：
![image](https://user-images.githubusercontent.com/6135871/103516787-0d55cb80-4eac-11eb-97d8-177b0d48dfef.png)
**X的shape为：(-1L, 3L, 400L, 400L)， grid的shape为：(-1L, 224L, 224L, 2L)，X为高分辨率图， grid为sample的网格点（降采样），因X与grid的维度不一致，paddle报错。**

对标pytorch的grid-sample已经很早支持这个功能了：
1. cvpr2019： https://github.com/researchmm/tasn/blob/master/tasn-pytorch/mymodel/tasn.py#L235
2. eccv2018:  https://github.com/recasens/Saliency-Sampler/blob/master/saliency_sampler.py#L115

希望paddle能帮助实习该op

**Comment by LielinJiang** [comment]
这个问题应该已经解决，可以尝试一下2.0版本

**Comment by zzchust** [comment]
2.0 版本是动态图版本吧？ 是否支持上线呢？或者是否支持使用静态图中使用该op呢

**Comment by liym27** [comment]
@zzchust  2.0 版本只是默认开启动态图。如果使用静态图的话，可以调用 `paddle.enable_static()` 开启静态图模式，其余代码无需更改。
静态图中可以使用该op.

另外我们也有动转静功能，支持用户写动态图代码，但可以转为静态图模型保存 上线。感兴趣可以关注 官方教程 [动态图转静态图](https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/guides/04_dygraph_to_static/index_cn.html)
