### ISSUE TITLE
paddle单机版本改造成分布式版本

### ISSUE THREAD

**Issue by zhangzhenyue1** [PaddlePaddle/Paddle#3008]
目前已经跑通[单机版的模型](https://github.com/Superjom/models-1/tree/develop/ctr)。
也跑通[分布式的例子](https://github.com/PaddlePaddle/Paddle/blob/develop/doc/howto/usage/k8s/k8s_distributed_cn.md)   

想将单机版本改造成分布式版本，发现这两个版本的接口差别很大。
有简单的方法，改改单机版的配置，直接用单机版的代码吗？

**Comment by typhoonzero** [comment]
上面链接中分布式的例子是基于paddle V1版本 API的。V2 API的分布式训练的文档还在编写中。

将上面的"单机版的模型"改为可以分布式执行的v2版本是比较容易的

Related： https://github.com/PaddlePaddle/Paddle/issues/3003
