### ISSUE TITLE
MKLDNN Errror：the outputs is wrong when batch_size is larger than 1

### ISSUE THREAD

**Issue by juncaipeng** [PaddlePaddle/Paddle#30089]
Thank you for contributing to PaddlePaddle.
Before submitting the issue, you could search issue in the github in case that th
If there is no solution,please make sure that this is an inference issue including the following details :
**System information**
-PaddlePaddle version （eg.1.1）or CommitID ： 
-CPU: MKLDNN
-GPU: None
-OS Platform: ubuntu 16.04
-Python version: 3.7
-Cmake orders
-C++version.txt
-API information
Note: You can get most of the information by running [summary_env.py](https://github.com/PaddlePaddle/Paddle/blob/develop/tools/summary_env.py). 
**To Reproduce**

Download the demo (Link:https://dubox.com/s/17M1tdffUMH5AW5Fi5_vHhg Password:5aaa) and refer to the readme

Error:
```
raceback (most recent call last):
  File "test.py", line 64, in <module>
      predictor.run()
      NotImplementedError:

      --------------------------------------
      C++ Traceback (most recent call last):
      --------------------------------------
      0   paddle::AnalysisPredictor::ZeroCopyRun()
      1   paddle::framework::NaiveExecutor::Run()
      2   paddle::framework::OperatorBase::Run(paddle::framework::Scope const&, paddle::platform::Place const&)
      3   paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, paddle::platform::Place const&) const
      4   paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, paddle::platform::Place const&, paddle::framework::RuntimeContext*) const
      5   std::_Function_handler<void (paddle::framework::ExecutionContext const&), paddle::framework::OpKernelRegistrarFunctor<paddle::platform::CPUPlace, false, 0ul, paddle::operators::MKLDNNActivationKernel<paddle::operators::MKLDNNActivationFunc<float, (dnnl::algorithm)175> > >::operator()(char const*, char const*, int) const::{lambda(paddle::framework::ExecutionContext const&)#1}>::_M_invoke(std::_Any_data const&, paddle::framework::ExecutionContext const&)
      6   paddle::operators::MKLDNNActivationKernel<paddle::operators::MKLDNNActivationFunc<float, (dnnl::algorithm)175> >::Compute(paddle::framework::ExecutionContext const&) const
      7   void paddle::operators::eltwise_forward<float>(paddle::framework::ExecutionContext const&, dnnl::algorithm)
      8   paddle::platform::EnforceNotMet::EnforceNotMet(paddle::platform::ErrorSummary const&, char const*, int)
      9   paddle::platform::GetCurrentTraceBackString[abi:cxx11]()

      ----------------------
      Error Message Summary:
      ----------------------
      UnimplementedError: Input dim must be with 2, 3 or 4 (at /work/Paddle/paddle/fluid/operators/mkldnn/activation_mkldnn_op.cc:98)
        [operator < sigmoid > error]
```

Besides, when batch_size is larger than 1, the output of batch_size 1 is  right, but the outputs of other batch_size  are wrong.

**Comment by juncaipeng** [comment]
@lidanqing-intel  Please compare the outputs of enabling MKLDNN and disabling MKLDNN. When enable MKLDNN, only the result of batch_num 1 is right, others are wrong.

**Comment by juncaipeng** [comment]
用户反馈问题如下：
![image](https://user-images.githubusercontent.com/52520497/103764648-d374f880-5056-11eb-89b0-85b0c049fd7a.png)

**Comment by lidanqing-vv** [comment]
matmul fuse后这一步的计算有错误，matmul输出 t_39 变量有inf了。还是考虑format的问题，明天我再问下Jacek

![image](https://user-images.githubusercontent.com/47151829/103841403-d215f100-5093-11eb-98bc-06ebab1cb4ae.png)

**Comment by lidanqing-vv** [comment]
一些kernel的cache key有问题问题，比如
```
std::string key = platform::CreateKey(dev_ctx, batch_size, out_name);
```
改为
 ```
std::string key = platform::CreateKey(dev_ctx, in_tz, out_name);
```
就不再出现inf问题。但是现在后面4个虽然不再是nan和inf，但是数值上还是不对，继续调查中,可能是别的地方有问题

**Comment by juncaipeng** [comment]
丹青分析这个模型的输入固定为[1, 1]， batch_size直接固定为1，对于batch_size大于1的情况，mkldnn优化执行应该是出现不对。但是这个错误的根源应该是组网训练、保存模型时输入shape不对。

用户是使用paddle1.8的动态图训练保存的预测模型，已经用paddle1.7.2预测库验证可以，所以等用户后续升级到paddle2.0后在看是否有问题。建议该issue先关闭。
