### ISSUE TITLE
faster-rcnn预测报错：  [Hint: Expected begin_idx < end_idx, but received begin_idx:0 >= end_idx:0.] at (/home/teamcity/work/ef54dc8a5b211854/paddle/fluid/framework/tensor.cc:83)   [operator < distribute_fpn_proposals > error]

### ISSUE THREAD

**Issue by RenyanDiao** [PaddlePaddle/Paddle#30091]
为使您的问题得到快速解决，在建立Issue前，请您先通过如下方式搜索是否有相似问题:【搜索issue关键字】【使用labels筛选】【官方文档】

如果您没有查询到相似问题，为快速解决您的提问，建立issue时请提供如下细节信息：
- 标题：简洁、精准描述您的问题，例如“最新预测库的API文档在哪儿 ”
- 版本、环境信息：
    1）PaddlePaddle版本：请提供您的PaddlePaddle版本号（如1.1）或CommitID
    2）CPU：预测若用CPU，请提供CPU型号，MKL/OpenBlas/MKLDNN/等数学库使用情况
    3）GPU：预测若用GPU，请提供GPU型号、CUDA和CUDNN版本号
    4）系统环境：请您描述系统类型、版本（如Mac OS 10.14），Python版本
注：您可以通过执行[summary_env.py](https://github.com/PaddlePaddle/Paddle/blob/develop/tools/summary_env.py)获取以上信息。
-预测信息
    1）C++预测：请您提供预测库安装包的版本信息，及其中的version.txt文件
    2）CMake包含路径的完整命令
    3）API信息（如调用请提供）
    4）预测库来源：官网下载/特殊环境（如BCLOUD编译）
- 复现信息：如为报错，请给出复现环境、复现步骤
- 问题描述：请详细描述您的问题，同步贴出报错信息、日志/代码关键片段

Thank you for contributing to PaddlePaddle.
Before submitting the issue, you could search issue in the github in case that th
If there is no solution,please make sure that this is an inference issue including the following details :
**System information**
-PaddlePaddle version （eg.1.1）or CommitID
-CPU: including CPUMKL/OpenBlas/MKLDNN version
-GPU: including CUDA/CUDNN version
-OS Platform (eg.Mac OS 10.14)
-Python version
-Cmake orders
-C++version.txt
-API information
Note: You can get most of the information by running [summary_env.py](https://github.com/PaddlePaddle/Paddle/blob/develop/tools/summary_env.py). 
**To Reproduce**
Steps to reproduce the behavior
**Describe your current behavior**
**Code to reproduce the issue**
**Other info / logs**

**Comment by RenyanDiao** [comment]
![image](https://user-images.githubusercontent.com/52916011/103536111-dd6af000-4ecc-11eb-9800-e18750c4ad36.png)
![image](https://user-images.githubusercontent.com/52916011/103536151-f1165680-4ecc-11eb-9740-b2f56dfe0802.png)

**Comment by liym27** [comment]
报错显示 `The start row index must be less than the end row index.`，定位发现，是 distribute_fpn_proposals 接口 的输入 `rois_num` 的不符合要求，麻烦确认下 `rois_num` 是否有问题

**Comment by RenyanDiao** [comment]
我是用load_inference_program载入的，这个rois_num怎么自己设置吗？

**Comment by liym27** [comment]
跑的代码是什么？可以麻烦贴一下demo 代码看看吗

**Comment by RenyanDiao** [comment]
![image](https://user-images.githubusercontent.com/52916011/103542383-cd0c4280-4ed7-11eb-95c3-1b0ada0dd2d2.png)
朋友说他也遇到过，是训练发散了导致的

**Comment by liym27** [comment]
好的。请问 现在问题是否已经得到解决了？

**Comment by RenyanDiao** [comment]
> 好的。请问 现在问题是否已经得到解决了？

没有呀，我觉得是rpn_head.get_proposals可能一个roi都没有，可是怎么会出现这种情况呢

**Comment by RenyanDiao** [comment]
> 好的。请问 现在问题是否已经得到解决了？

我没觉得我这是训练发散了，因为我的loss都是0.13几

**Comment by RenyanDiao** [comment]
![image](https://user-images.githubusercontent.com/52916011/103604480-33cb4380-4f4c-11eb-9ee8-241cc158eb40.png)
我发现，我在做量化之后出现了这个问题，是不是weight里最大值为nan或者0，导致转换出来的weight有不合法的值，导致计算的bbox没有一个是前景的可能性

**Comment by RenyanDiao** [comment]
然而我查了一下 量化的scale没有一个不合法的值

**Comment by jerrywgz** [comment]
你是直接加载了量化之后的模型吗？如果不做量化的话，load进来训练有问题吗？从报错来看确实是roi为空导致的

**Comment by RenyanDiao** [comment]
> 你是直接加载了量化之后的模型吗？如果不做量化的话，load进来训练有问题吗？从报错来看确实是roi为空导致的

量化之后有问题，原始没有问题。我发现了是有weight的值有nan的问题，这个估计得叫slim的同学看一下

**Comment by jerrywgz** [comment]
嗯嗯这个可以在PaddleSlim里反馈下
