### ISSUE TITLE
RTX3070能否使用paddlepaddle-gpu，运行模型是出错

### ISSUE THREAD

**Issue by janyChan** [PaddlePaddle/Paddle#30092]
服务器显卡是rtx3070，安装paddle后运行模型出错
cuda装的是10.0版本
想问下，rtx3070是否支持现有的paddle版本？
谢谢

**Comment by liym27** [comment]
您好，目前 rtx3070 还不支持Paddle. 当前我们已经在规划支持中，谢谢
