### ISSUE TITLE
paddlepaddle-gpu2.0.0rc1版本中的一个bug

### ISSUE THREAD

**Issue by xiulianzw** [PaddlePaddle/Paddle#30107]
CUDA环境：
 CUDA：V10.0.130
cudnn：7.6.5

安装paddlepaddle-gpu 1.8.5之后，测试

> >>> import paddle.fluid as fluid
> TensorRT dynamic library (libnvinfer.so) that Paddle depends on is not configured correctly. (error code is libnvinfer.so: cannot open shared object file: No such file or directory)
>   Suggestions:
>   1. Check if TensorRT is installed correctly and its version is matched with paddlepaddle you installed.
>   2. Configure TensorRT dynamic library environment variables as follows:
>   - Linux: set LD_LIBRARY_PATH by `export LD_LIBRARY_PATH=...`
>   - Windows: set PATH by `set PATH=XXX;>>> fluid.install_check.run_check()
> Running Verify Fluid Program ... 
> W0105 12:17:58.486372 168066 device_context.cc:252] Please NOTE: device: 0, CUDA Capability: 61, Driver API Version: 10.2, Runtime API Version: 10.0
> W0105 12:17:58.493080 168066 device_context.cc:260] device: 0, cuDNN Version: 7.6.
> Your Paddle Fluid works well on SINGLE GPU or CPU.
> W0105 12:18:05.146318 168066 fuse_all_reduce_op_pass.cc:74] Find all_reduce operators: 2. To make the speed faster, some all_reduce ops are fused during training, after fusion, the number of all_reduce ops is 1.
> Your Paddle Fluid works well on MUTIPLE GPU or CPU.
> Your Paddle Fluid is installed successfully! Let's start deep Learning with Paddle Fluid now

安装paddlepaddle-gpu2.0.0rc1之后，测试

> > >>> import paddle
> >>> paddle.utils.run_check()
> Running verify PaddlePaddle program ... 
> W0105 12:16:53.456194 167978 device_context.cc:320] Please NOTE: device: 0, GPU Compute Capability: 6.1, Driver API Version: 10.2, Runtime API Version: 10.2
> W0105 12:16:53.459367 167978 device_context.cc:330] device: 0, cuDNN Version: 8.0.
> PaddlePaddle works well on 1 GPU.
> W0105 12:16:54.981242 167978 parallel_executor.cc:491] Cannot enable P2P access from 0 to 2
> W0105 12:16:54.981288 167978 parallel_executor.cc:491] Cannot enable P2P access from 0 to 3
> W0105 12:16:55.648530 167978 parallel_executor.cc:491] Cannot enable P2P access from 1 to 2
> W0105 12:16:55.648576 167978 parallel_executor.cc:491] Cannot enable P2P access from 1 to 3
> W0105 12:16:55.648587 167978 parallel_executor.cc:491] Cannot enable P2P access from 2 to 0
> W0105 12:16:55.648595 167978 parallel_executor.cc:491] Cannot enable P2P access from 2 to 1
> W0105 12:16:56.586725 167978 parallel_executor.cc:491] Cannot enable P2P access from 3 to 0
> W0105 12:16:56.586769 167978 parallel_executor.cc:491] Cannot enable P2P access from 3 to 1
> W0105 12:16:59.653086 167978 fuse_all_reduce_op_pass.cc:75] Find all_reduce operators: 2. To make the speed faster, some all_reduce ops are fused during training, after fusion, the number of all_reduce ops is 2.
> PaddlePaddle works well on 4 GPUs.
> PaddlePaddle is installed successfully! Let's start deep learning with PaddlePaddle now.
> 

同样的环境下，**1.8.5输出的cudnn版本是7.6而2.0rc1输出的版本却是8.0**，然后我再使用最新版的PaddleOCR的时候也发现了，之前装的1.8.5版本的，可以正常运行。2.0版本的却报错，报错信息如下

--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
0   paddle::framework::SignalHandle(char const*, int)
1   paddle::platform::GetCurrentTraceBackString[abi:cxx11]()

----------------------
Error Message Summary:
----------------------
FatalError: `Segmentation fault` is detected by the operating system.
  [TimeInfo: *** Aborted at 1609820464 (unix time) try "date -d @1609820464" if you are using GNU date ***]
  [SignalInfo: *** SIGSEGV (@0x0) received by PID 168205 (TID 0x7ff1ba2a2700) from PID 0 ***]

Segmentation fault (core dumped)

所以现在不确定是不是这个bug引起的，CPU版本的可以正常运行。

**Comment by FrostML** [comment]
可以尝试安装使用 2.0rc1 cudnn 7.6 版本的 Paddle 试试看，对齐下 Paddle 的 cudnn 版本和环境的 cudnn 版本。

**Comment by xiulianzw** [comment]
系统配置的环境实际上就是cuda10和cudnn7.6，和用1.8.5版本输出的一致，不知道为啥2.0rc1输出会是8.0。新版本的paddle是用的配置环境下的cuda环境吗？还是读取的其他的？ @FrostML

**Comment by xxxpsyduck** [comment]
try specified version for cuda 10 as suggested [here](https://www.paddlepaddle.org.cn/install/quick?docurl=/documentation/docs/zh/2.0-rc1/install/pip/linux-pip.html)

**Comment by FrostML** [comment]
可以确认下本地是否有多个 cudnn 版本，这里获取的应该是本地的 cudnn 版本。
```
device_context.cc:330] device: 0, cuDNN Version: 8.0.
```
可以把 7.6 的版本加入环境变量中放在 8.0 的前面。
