### ISSUE TITLE
test_analysis_predictor单测失败

### ISSUE THREAD

**Issue by XieYunshen** [PaddlePaddle/Paddle#30119]
**System information**
-PaddlePaddle version （eg.1.1）or CommitID
-CPU: including CPUMKL/OpenBlas/MKLDNN version
-GPU: including CUDA/cuDNN version
-OS Platform and Distribution(eg.Mac OS 10.14)
-Python version 
Note: You can get most of the information by running [summary_env.py](https://github.com/PaddlePaddle/Paddle/blob/develop/tools/summary_env.py). 
**To Reproduce**
Steps to reproduce the behavior
**Describe your current behavior**
**Code to reproduce the issue**
test_analysis_predictor单测在压测中一直报错
https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/fluid/inference/api/analysis_predictor_tester.cc
![image](https://user-images.githubusercontent.com/32428676/103622962-638d4200-4f72-11eb-9a25-451827f2758b.png)
https://xly.bce.baidu.com/paddlepaddle/paddle/newipipe/detail/2278634/job/3228247
CI上的coverage任务运行这个单测是可以通过的
![image](https://user-images.githubusercontent.com/32428676/103623104-96cfd100-4f72-11eb-9805-e55f4157a84e.png)
https://xly.bce.baidu.com/paddlepaddle/paddle/newipipe/detail/2279648/job/3229509
**Other info / logs**

**Comment by luotao1** [comment]
@wozna @lidanqing-intel Could you help fix this unit-test? The machine is 5117.

**Comment by wozna** [comment]
@luotao1  Yes I have prepared fix in PR https://github.com/PaddlePaddle/Paddle/pull/30191
