### ISSUE TITLE
源码安装问题

### ISSUE THREAD

**Issue by wanxin-code** [PaddlePaddle/Paddle#30124]
**- 版本、环境信息**：
    1）PaddlePaddle版本：2.0
    2）CPU：i9-
    3）GPU：rtx3090， cuda=11.1， cudnn=8.0.5
    4）系统环境：ubuntu20.04， python=3.8(conda 环境)

请问该环境下，当前的paddle版本是否支持源码编译安装？

**Comment by FrostML** [comment]
rtx3090 目前暂不支持。
