### ISSUE TITLE
Check failed: in2_mat.getHeight() == 1LU || in2_mat.getHeight() == num_samples

### ISSUE THREAD

**Issue by iyishengyoun** [PaddlePaddle/Paddle#3012]
运行paddle的时候遇到Check failed: in2_mat.getHeight() == 1LU || in2_mat.getHeight() == num_samples，这种错误一般是由什么引起的

**Comment by guoshengCS** [comment]
这种是对数据的size进行check时报的错，应该是数据的问题，可以先check下数据

**Comment by wanghaoshuang** [comment]
Closing due to low activity. Feel free to reopen it.
