### ISSUE TITLE
Anaconda版paddlepaddle-gpu不使用conda安装的cudatoolkit和cudnn

### ISSUE THREAD

**Issue by gongliyu** [PaddlePaddle/Paddle#30131]
使用"conda install -c paddle paddlepaddle-gpu"后，conda自动安装cudatoolkit 10.2和cudnn 7.6包以及paddlepaddle-gpu 2.0.0rc1。但是在运行代码时paddle总是找系统安装在"/usr/local/cuda"位置的cudatoolkit和cudnn。如果使用LD_LIBRARY_PATH=/conda/lib/path，则paddle提示找不到cuda.

conda的使用逻辑是尽量把依赖的二进制库放在conda自己的环境中，以减少对操作系统的环境依赖。anaconda版本的paddlepaddle-gpu配置了正确的依赖(所以conda可以安装正确的cudatoolkit和cudnn)，但在运行时却不使用这些安装的依赖而去系统中找依赖，应该时个issue.

例如PyTorch在anaconda下安装的话，操作系统只需要有cuda driver就可以了，不需要cudatoolkit和cudnn.

**Comment by gongliyu** [comment]
Reopen-it, seems the problem still exist

**Comment by skylark36** [comment]
Same problem

**Comment by gongliyu** [comment]
@cryoco Any update on this problem?

**Comment by Aurou** [comment]
同样的问题还是还是存在
