### ISSUE TITLE
使用AnalysisConfig 和原生的exe推理结果不对齐

### ISSUE THREAD

**Issue by yeyupiaoling** [PaddlePaddle/Paddle#30132]
- PaddlePaddle 1.8.5.post107
 - Ubuntu 18.04 or Windows 10
 - MobileNet V2

通过实验结果证明 XXXConfig 的输出结果都一致，是不是我少了什么步骤？

**Comment by cryoco** [comment]
您好，您可以对照下这篇文档：https://www.paddlepaddle.org.cn/documentation/docs/zh/advanced_guide/inference_deployment/inference/python_infer_cn.html
您似乎没有在`input_tensor.copy_from_cpu(img)`之前执行这一步
```
input_tensor.reshape([batch_size, 3, 224, 224])
```
可以试下加上是否能够解决

**Comment by yeyupiaoling** [comment]
@cryoco 这个加不加输出结果都是一模一样的。我的代码也跟你发的文档中的代码没什么差别。

**Comment by yeyupiaoling** [comment]
@cryoco 我觉得这个`input_tensor.reshape([batch_size, 3, 224, 224])`不工作，因为我尝试把输入的图像转换为一维数组，同时也使用reshape，但是执行推理是就报输入shape不正确。
```python
  # 获取输入的名称
    input_names = predictor.get_input_names()
    input_tensor = predictor.get_input_tensor(input_names[0])
    input_tensor.reshape([1, 3, 224, 224])

    # 设置输入
    img = preprocess(args.image_path, operators)
    input_tensor.copy_from_cpu(img.flatten().tolist())
```

**Comment by cryoco** [comment]
设置config.switch_ir_optim(False)试试

**Comment by yeyupiaoling** [comment]
@cryoco 结果并没有变化。

**Comment by cryoco** [comment]
上面那个改动是关闭了预测期间的所有优化，相当于在跑exe了，结果应该是一样的。
可能还是输入没有对齐，您可否在两种方式feed数据时把feed进去的数据打印对比下是否一致

**Comment by yeyupiaoling** [comment]
@cryoco 我使用以下代码判断过了，输出是True。数据是一模一样的。是不是文档上还是少了什么步骤
```
    b = np.load('test.npy')

    print(np.array_equal(img, b))
```

**Comment by cryoco** [comment]
> @cryoco 我觉得这个`input_tensor.reshape([batch_size, 3, 224, 224])`不工作，因为我尝试把输入的图像转换为一维数组，同时也使用reshape，但是执行推理是就报输入shape不正确。
> 
> ```python
>   # 获取输入的名称
>     input_names = predictor.get_input_names()
>     input_tensor = predictor.get_input_tensor(input_names[0])
>     input_tensor.reshape([1, 3, 224, 224])
> 
>     # 设置输入
>     img = preprocess(args.image_path, operators)
>     input_tensor.copy_from_cpu(img.flatten().tolist())
> ```

这里输入不用flatten，直接用img就可以了

**Comment by yeyupiaoling** [comment]
@cryoco 这个我测试的，用这个是报错的。所以我没用这个，还是问题上面的代码

**Comment by yeyupiaoling** [comment]
@cryoco 我在exe上面复现了这样的错误，具体这样做的，首先去掉改变通道顺序的代码，使得数据保持原来的（224, 224, 3）
```
img = img.transpose((2, 0, 1))
```

然后使用`data = data.reshape(3, 224, 224)`强制变化成(3, 224, 224)，最后在加上`data = np.expand_dims(data, axis=0)`，这的输出结果就跟AnalysisConfig的一样了

**Comment by cryoco** [comment]
> @cryoco 我在exe上面复现了这样的错误，具体这样做的，首先去掉改变通道顺序的代码，使得数据保持原来的（224, 224, 3）
> 
> ```
> img = img.transpose((2, 0, 1))
> ```
> 
> 然后使用`data = data.reshape(3, 224, 224)`强制变化成(3, 224, 224)，最后在加上`data = np.expand_dims(data, axis=0)`，这的输出结果就跟AnalysisConfig的一样了

那在使用AnalysisConfig时加上这个操作是不是就可以了

**Comment by yeyupiaoling** [comment]
@cryoco 这个是exe复现AnalysisConfig错误的情况，AnalysisConfig加上这个还是一样的问题。

**Comment by yeyupiaoling** [comment]
@cryoco 你不觉得这个是AnalysisConfig对数据的读取的问题吗？感觉他好像把数据打乱了

**Comment by cryoco** [comment]
您这个模型的输入shape是多少，是nhwc还是nchw的呢？可以用netron可视化查看

**Comment by yeyupiaoling** [comment]
@cryoco 输入是nchw，用exe和AnalysisConfig同样的数据

**Comment by cryoco** [comment]
从您的测试结果可以看出，exe和predictor的区别并非计算有差异，而是实际输入的数据的排布不同，但AnalysisConfig并不会在输入时对layout做任何的处理。您可以试试用“exe复现AnalysisConfig错误的情况”的逆操作来对AnalysisConfig的输入进行处理试试。

**Comment by yeyupiaoling** [comment]
@cryoco 我试过了，没用，还是错误的。要不要给模型给模型你试试

**Comment by cryoco** [comment]
好的，提供下您的模型和测试图片吧

**Comment by yeyupiaoling** [comment]
@cryoco 模型超过了10m，这里不能上传，你在QQ群上吗？我发给您。

**Comment by WeipengChan** [comment]
@cryoco  我也遇到了跟你一样的问题，输入是一模一样的。我用fluid load的模型用exe run结果是对的，用AnalysisConfig就结果不对。而且我尝试了cpu和gpu模式，还是错的，但是cpu和gpu模式错的还不一样。

**Comment by yeyupiaoling** [comment]
@WeipengChan 我的不是报错，是AnalysisConfig预测结果不对而已

**Comment by WeipengChan** [comment]
> @WeipengChan 我的不是报错，是AnalysisConfig预测结果不对而已

@WeipengChan 我的不是报错，是AnalysisConfig预测结果不对而已
是的。我打错了，能输出，结果不对。肯定是某个结构出了问题。只是不知怎么查而已

**Comment by yeyupiaoling** [comment]
@WeipengChan 我也不清楚，我也搞了好久。

**Comment by WeipengChan** [comment]
> @WeipengChan 我也不清楚，我也搞了好久。
我就搞了一上午，就确认是他们AnalysisConfig调用的优化函数有问题了，模型本身肯定是没问题了。

**Comment by yeyupiaoling** [comment]
@WeipengChan 模型肯定没有问题的，exe run都正常。

**Comment by WeipengChan** [comment]
> @WeipengChan 模型肯定没有问题的，exe run都正常。

是的，我们情况一样，可能只是模型不同。

**Comment by yeyupiaoling** [comment]
@cryoco 请问什么时候可以解决呢？

**Comment by lleesg** [comment]
> 设置config.switch_ir_optim(False)

你好，我遇到的问题下，设置config.switch_ir_optim(False)与否结果完全不同：设置则正确（请忽略对风筝的错误判断，我的模型里只关心人）、否则预测不出任何东西。但我又需要TRT加速，请问有无解决思路？谢谢
![output - 110253](https://user-images.githubusercontent.com/16949144/104264269-48688800-54c6-11eb-9ced-b8c5038356c0.jpg)

more infos in https://github.com/PaddlePaddle/Paddle/issues/28505#issuecomment-758365090

**Comment by yeyupiaoling** [comment]
@WeipengChan 你解决这个问题了吗？

**Comment by yeyupiaoling** [comment]
@qingqing01 我是真的没有办法了，才@您，希望您不要介意，您有时间可以帮我看看这个问题所在吗？谢谢。

**Comment by yeyupiaoling** [comment]
@WeipengChan 这个问题你如何解决的？

**Comment by yeyupiaoling** [comment]
原来是少了`copy()`
```python
img = preprocess(args.image_path, operators)
input_tensor.copy_from_cpu(img.copy())
```
