### ISSUE TITLE
x2paddle转换模型时，paddle报错

### ISSUE THREAD

**Issue by Huihuihh** [PaddlePaddle/Paddle#30150]
环境信息：
Paddle version: 2.0.0-rc1
Paddle With CUDA: False

OS: Ubuntu 18.04
Python version: 3.6.9

CUDA version: None
cuDNN version: None.None.None
Nvidia driver version: None

使用最新的x2paddle转换tensorflow模型时，遇到paddle报错：
paddle.__version__ = 2.0.0-rc1
/usr/local/lib/python3.6/dist-packages/tensorflow/python/pywrap_tensorflow_internal.py:15: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp
Now translating model from tensorflow to paddle.
Total nodes: 316
Nodes converting ...
Converting node 316 ...
Nodes converted.
dygraph_conv2d_add_fuse_pass done!
dygraph_tf_batchnorm_fuse_pass done!
dygraph_prelu_fuse_pass done!
Optimize Transpose Layers...99.66%
Transpose layers optimized, before: transpose_num=34, after: transpose_num=32
transpose_eliminate_pass done!
Traceback (most recent call last):
  File "/usr/local/bin/x2paddle", line 11, in <module>
    load_entry_point('x2paddle==1.0.0rc1', 'console_scripts', 'x2paddle')()
  File "/usr/local/lib/python3.6/dist-packages/x2paddle-1.0.0rc1-py3.6.egg/x2paddle/convert.py", line 273, in main
  File "/usr/local/lib/python3.6/dist-packages/x2paddle-1.0.0rc1-py3.6.egg/x2paddle/convert.py", line 138, in tf2paddle
  File "/usr/local/lib/python3.6/dist-packages/x2paddle-1.0.0rc1-py3.6.egg/x2paddle/core/program.py", line 243, in gen_model
  File "/usr/local/lib/python3.6/dist-packages/x2paddle-1.0.0rc1-py3.6.egg/x2paddle/core/program.py", line 291, in gen_dygraph_model
  File "/usr/local/lib/python3.6/dist-packages/x2paddle-1.0.0rc1-py3.6.egg/x2paddle/core/program.py", line 551, in gen_dygraph_code
  File "/usr/local/lib/python3.6/dist-packages/x2paddle-1.0.0rc1-py3.6.egg/x2paddle/core/util.py", line 62, in remove_default_attrs
AttributeError: module 'paddle.nn' has no attribute 'Pad4D'

**Comment by SunAhong1993** [comment]
> 环境信息：
> Paddle version: 2.0.0-rc1
> Paddle With CUDA: False
> 
> OS: Ubuntu 18.04
> Python version: 3.6.9
> 
> CUDA version: None
> cuDNN version: None.None.None
> Nvidia driver version: None
> 
> 使用最新的x2paddle转换tensorflow模型时，遇到paddle报错：
> paddle.**version** = 2.0.0-rc1
> /usr/local/lib/python3.6/dist-packages/tensorflow/python/pywrap_tensorflow_internal.py:15: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
> import imp
> Now translating model from tensorflow to paddle.
> Total nodes: 316
> Nodes converting ...
> Converting node 316 ...
> Nodes converted.
> dygraph_conv2d_add_fuse_pass done!
> dygraph_tf_batchnorm_fuse_pass done!
> dygraph_prelu_fuse_pass done!
> Optimize Transpose Layers...99.66%
> Transpose layers optimized, before: transpose_num=34, after: transpose_num=32
> transpose_eliminate_pass done!
> Traceback (most recent call last):
> File "/usr/local/bin/x2paddle", line 11, in
> load_entry_point('x2paddle==1.0.0rc1', 'console_scripts', 'x2paddle')()
> File "/usr/local/lib/python3.6/dist-packages/x2paddle-1.0.0rc1-py3.6.egg/x2paddle/convert.py", line 273, in main
> File "/usr/local/lib/python3.6/dist-packages/x2paddle-1.0.0rc1-py3.6.egg/x2paddle/convert.py", line 138, in tf2paddle
> File "/usr/local/lib/python3.6/dist-packages/x2paddle-1.0.0rc1-py3.6.egg/x2paddle/core/program.py", line 243, in gen_model
> File "/usr/local/lib/python3.6/dist-packages/x2paddle-1.0.0rc1-py3.6.egg/x2paddle/core/program.py", line 291, in gen_dygraph_model
> File "/usr/local/lib/python3.6/dist-packages/x2paddle-1.0.0rc1-py3.6.egg/x2paddle/core/program.py", line 551, in gen_dygraph_code
> File "/usr/local/lib/python3.6/dist-packages/x2paddle-1.0.0rc1-py3.6.egg/x2paddle/core/util.py", line 62, in remove_default_attrs
> AttributeError: module 'paddle.nn' has no attribute 'Pad4D'

这边X2Paddle该OP转换存在问题，修改后回复您。

**Comment by SunAhong1993** [comment]
该问题已解决，您可重新更新X2Paddle的代码，进行转换，更新方式如下：
```
pip uninstall x2paddle
git clone https://github.com/PaddlePaddle/X2Paddle.git
cd X2Paddle
python setup.py install
```
同时更新Paddle的Python源码中的python/paddle/nn/functional/common.py，更改信息详见https://github.com/PaddlePaddle/Paddle/pull/30231/files。

**Comment by Huihuihh** [comment]
是的，已经解决，多谢
