### ISSUE TITLE
paddle2.0中创建variable用什么函数？ 1.8中是用layers.create_parameter

### ISSUE THREAD

**Issue by zzchust** [PaddlePaddle/Paddle#30162]

**Comment by QinchengZhang** [comment]
用Layer的create_parameter方法

**Comment by QinchengZhang** [comment]
import paddle

class MyLayer(paddle.nn.Layer):
    def __init__(self):
        super(MyLayer, self).__init__()
        self.a = self.create_parameter([1,1])

    def forward(self, input):
        return self.a(input)
