### ISSUE TITLE
paddlelite转换优化量化模型和预测错误 lite2.7

### ISSUE THREAD

**Issue by RenyanDiao** [PaddlePaddle/Paddle#30192]
为使您的问题得到快速解决，在建立Issue前，请您先通过如下方式搜索是否有相似问题:【搜索issue关键字】【使用labels筛选】【官方文档】

建立issue时，为快速解决问题，请您根据使用情况给出如下信息：
- 标题：简洁、精准描述您的问题，例如“ssd 模型前置lstm报错  ”
- 版本、环境信息：
    1）PaddlePaddle版本：请提供PaddlePaddle版本号，例如1.1或CommitID
    2）CPU：请提供CPU型号，MKL/OpenBlas/MKLDNN/等数学库的使用情况
    3）GPU：请提供GPU型号，CUDA和CUDNN版本号
    4）系统环境：请说明系统类型、版本（例如Mac OS 10.14），Python版本
 注：您可以通过执行[summary_env.py](https://github.com/PaddlePaddle/Paddle/blob/develop/tools/summary_env.py)获取以上信息。
- 模型信息
    1）模型名称 2）使用数据集名称 3）使用算法名称 4）模型链接
- 复现信息：如为报错，请给出复现环境、复现步骤
- 问题描述：请详细描述您的问题，同步贴出报错信息、日志/代码关键片段

Thank you for contributing to PaddlePaddle.
Before submitting the issue, you could search issue in the github.Probably there was a similar issue submitted or resolved before.
If there is no solution,please make sure that this is a issue of models including the following details:
**System information**
-PaddlePaddle version （eg.1.1）or CommitID
-CPU: including CPUMKL/OpenBlas/MKLDNN version
-GPU: including CUDA/CUDNN version
-OS Platform (eg.Mac OS 10.14)
-Python version
-Name of Models&Dataset/details of operator
Note: You can get most of the information by running [summary_env.py](https://github.com/PaddlePaddle/Paddle/blob/develop/tools/summary_env.py). 
**To Reproduce**
Steps to reproduce the behavior
**Describe your current behavior**
**Code to reproduce the issue**
**Other info / logs**

**Comment by RenyanDiao** [comment]
![image](https://user-images.githubusercontent.com/52916011/103867548-83537000-5102-11eb-82e6-8250f4173796.png)

**Comment by RenyanDiao** [comment]
![image](https://user-images.githubusercontent.com/52916011/103868618-1214bc80-5104-11eb-84b7-1ac692ef7759.png)
这为什么会是个bool值。。

**Comment by juncaipeng** [comment]
这个可能只是一个warning，opt执行是否正常结束？可以直接测试转换后的模型是否正确执行。

**Comment by RenyanDiao** [comment]
> 这个可能只是一个warning，opt执行是否正常结束？可以直接测试转换后的模型是否正确执行。

倒是生成了.nb文件，但是在arm上运行结果完全不对，这是个int8模型，本身int8模型运行以及预测没有问题

**Comment by RenyanDiao** [comment]
密密麻麻的框，conf还都挺高

**Comment by RenyanDiao** [comment]
这个bool值，会参与conv elementwise等等计算，所以结果肯定不对啊，我觉得这是lite的bug

**Comment by juncaipeng** [comment]
嗯，这个问题可以到paddlelite repo提issue，让相关同学跟进。

输出的log太多，你可以关闭。

你使用相同的输入，在paddle上执行和lite上执行，看输出是否有差异。

**Comment by RenyanDiao** [comment]
> 嗯，这个问题可以到paddlelite repo提issue，让相关同学跟进。
> 
> 输出的log太多，你可以关闭。
> 
> 你使用相同的输入，在paddle上执行和lite上执行，看输出是否有差异。

怎么关闭，python没有传参可以让我关log的，你知道的话，跟我说说

**Comment by juncaipeng** [comment]
在shell端执行 export GLOG_v=0 关闭大量log信息
