### ISSUE TITLE
使用flask搭建服务同时集成paddlepaddle模型和tensorflow模型时，tensorflow模型预测速度变慢

### ISSUE THREAD

**Issue by qiuming-93** [PaddlePaddle/Paddle#30193]
- 标题：使用flask搭建服务同时集成paddlepaddle模型和tensorflow模型时，tensorflow模型预测速度变慢
- 版本、环境信息：
    1）PaddlePaddle版本：paddlepaddle-gpu==1.8.5.post97
    2）CPU/GPU：CPU
    3）系统环境：centos7.6
    4）Python3.6

**Comment by qiuming-93** [comment]
甚至不需要搭建paddlepaddle的模型，只需要import paddle就会导致该情况，
是否在导入时paddle就已经申请并占有了大部分的资源，导致tensorflow模型预测速度变慢

**Comment by juncaipeng** [comment]
我找相关同学来看下这个问题。

**Comment by juncaipeng** [comment]
这个问题是tf变慢了，不是paddle变慢了，相关同学反馈paddle这边没办法帮忙解决。
建议用tf 的 profile 分析一下哪些op速度变慢了，到 tf 那边提issue问问如何解决。

**Comment by qiuming-93** [comment]
升级tensorflow版本后问题解决
