### ISSUE TITLE
编译安装后执行 import paddle.v2 as paddle 报ImportError: No module named v2 错误

### ISSUE THREAD

**Issue by duanxian** [PaddlePaddle/Paddle#3022]
如题，按照 http://deeplearning.baidu.com/doc/local_compile.html  步骤进行安装，报上述错误

**Comment by wanghaoshuang** [comment]
paddle-0.10.0-py2-none-any.whl

**Comment by duanxian** [comment]
/paddle/paddle_internal_release_tools/idl/paddle/output/opt/paddle/share/wheels/目录下有paddle-0.9.0-py2-none-any.whl及py_paddle-0.9.0-cp27-cp27m-linux_x86_64.whl两个文件，执行pip uninstall paddle-0.9.0-py2-none-any.whl 和 pip uninstall py_paddle-0.9.0-cp27-cp27m-linux_x86_64.whl 后，重新执行pip install paddle-0.9.0-py2-none-any.whl报错：IOError: [Errno 2] No such file or directory: '/paddle/paddle_internal_release_tools/idl/paddle/paddle-0.9.0-py2-none-any.whl'

**Comment by wanghaoshuang** [comment]
@duanxian 
这样试下：
```
unzip paddle-0.9.0-py2-none-any.whl -d paddle-0.9.0-py2
cp -r paddle-0.9.0-py2/* $PYTHON_PATH/lib/python2.7/site-packages/
```
对`py_paddle-0.9.0-cp27-cp27m-linux_x86_64.whl`也做以上操作。

**Comment by duanxian** [comment]
上面IOError: [Errno 2] No such file or directory: '/paddle/paddle_internal_release_tools/idl/paddle/paddle-0.9.0-py2-none-any.whl'是因为我没有到
/paddle/paddle_internal_release_tools/idl/paddle/output/opt/paddle/share/wheels/ 下执行，现在执行
`pip install paddle-0.9.0-py2-none-any.whl  `   
`pip install py_paddle-0.9.0-cp27-cp27m-linux_x86_64.whl`
后$PYTHON_PATH/lib/python2.7/site-packages/中有相应的文件夹，但是
`import paddle.vs as paddle`
仍然出错： `ImportError: No module named v2`

**Comment by duanxian** [comment]
`pip uninstall paddle-0.9.0-py2-none-any.whl `和
`pip uninstall py_paddle-0.9.0-cp27-cp27m-linux_x86_64.whl` 后，
执行
```
unzip paddle-0.9.0-py2-none-any.whl -d paddle-0.9.0-py2
cp -r paddle-0.9.0-py2/* $PYTHON_PATH/lib/python2.7/site-packages/
```
对py_paddle-0.9.0-cp27-cp27m-linux_x86_64.whl也做以上操作，仍然出错：
 `ImportError: No module named v2`

**Comment by wanghaoshuang** [comment]
@duanxian 你看下$PYTHON_PATH/lib/python2.7/site-packages/paddle下有v2这个文件夹么？

**Comment by duanxian** [comment]
这是路径：
paddle/paddle_internal_release_tools/idl/paddle/output/python27-gcc482/lib/python2.7/site-packages/paddle
文件：
-rw-rw-r--  1 work work  599 Jul 23 15:34 __init__.py
-rw-rw-r--  1 work work  235 Jul 23 15:36 __init__.pyc
drwxrwxr-x  2 work work 4096 Jul 23 15:34 proto
drwxrwxr-x  2 work work 4096 Jul 23 15:34 trainer
drwxrwxr-x  2 work work 4096 Jul 23 15:34 trainer_config_helpers
drwxrwxr-x  2 work work 4096 Jul 23 15:34 utils
没有v2文件夹

**Comment by duanxian** [comment]
@wanghaoshuang

**Comment by wanghaoshuang** [comment]
@duanxian 哦，那就是版本不对了，可能是Paddle的最新代码没下载成功，在你参考的文档里有：
> 机器如果能访问github，脚本会自动下载Paddle源码库；机器如果不能访问github，脚本会提示手动下载Paddle源码，并替换Paddle目录。

要不你clone下最新的Paddle，重新编译下？

**Comment by wanghaoshuang** [comment]
@duanxian 你确认下`paddle_internal_release_tools/idl/paddle/Paddle/python/paddle/` 下有v2么？

**Comment by Threven** [comment]
本人小白，请问import paddle.v2 as paddle 直接在终端中执行吗？为什么我的执行之后，就只有光标在闪，是要等很久吗？

**Comment by typhoonzero** [comment]
@Threven 终端交互式执行 import 一般很快回执行成功，import成功是没有提示信息的。如果import没有报错退出，一致等待，请检查是否是机器磁盘负载过高等因素。

**Comment by Threven** [comment]
@typhoonzero 我安装了系统负载指示器，几乎没有负载。另外我import sys也是这样的。import命令是直接把对应的模块拷贝进去吗？我新建了一个文件夹，然后在终端里import sys或者paddle.v2就会卡住，我强制停止（或者切换到别的程序再切换回来，终端也会像执行完一样跳到下一行没有任何提示）之后，文件夹里就会有对应文件，nano读取文件发现里面代码前面正常后面全是16进制的数了

**Comment by Threven** [comment]
@typhoonzero 是系统的问题吗？Ubuntu 16.04 LTS (x_64)

**Comment by typhoonzero** [comment]
1. python的import是在python intepreter的内存中加载对应的模块，不会拷贝文件。
2. `import paddle.v2 as paddle`需要在python终端中运行：
    ```
    python
    >>> import paddle.v2 as paddle
    >>>
    ```
    如果看到这样的现象说明是成功了

**Comment by Threven** [comment]
@typhoonzero 可以了，非常感谢！

**Comment by bolt163** [comment]
真操蛋，没见到这么难用的第3方开源框架

**Comment by LittleBenXi** [comment]
安装成功了paddle
`Successfully installed paddlepaddle-gpu-1.3.0.post97`
遇到这个问题，请问如何解决
```
import paddle.v2 as paddle
ModuleNotFoundError: No module named 'paddle.v2'
```

**Comment by aaronlyt** [comment]
请问怎么解决的呢

**Comment by luotao1** [comment]
1.3版本不支持v2了，如果要使用v2，请使用1.2版本。

**Comment by LittleBenXi** [comment]
DeepSpeech得在python2.7环境下运行，安装paddle的时候也得是python2.7环境。在python3环境下安装，就会报这个错误。


| |
李同学
|
|
15210009859@163.com
|
签名由网易邮箱大师定制
在2019年3月29日 15:06，aaronlyt<notifications@github.com> 写道：

请问怎么解决的呢
