### ISSUE TITLE
官网发布的windows的预测动态连接库有问题，猜测没有将函数引出

### ISSUE THREAD

**Issue by ouyangguang0726** [PaddlePaddle/Paddle#30228]
https://www.paddlepaddle.org.cn/documentation/docs/zh/advanced_guide/inference_deployment/inference/windows_cpp_inference.html
安装与编译 Windows 预测库页面上下载的所有版本的静态库都可用，但是动态库都不可用
cpu_avx_mkl版本只有两个文件libpaddle_fluid.lib和paddle_fluid.dll，libpaddle_fluid.lib应该是静态库，paddle_fluid.dll的用于链接的lib文件没有
cuda10.0_cudnn7_avx_mkl版本里有paddle_fluid.lib，但是只有2Kb，几乎没有任何函数引出，动态链接时找不到函数
我以前下载的版本是正常的，最近这个版本应该有问题，现在历史版本找不到了，能给个历史版本链接吗？

**Comment by jiweibo** [comment]
https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/guides/05_inference_deployment/inference/windows_cpp_inference.html

请从该页面下载库试试

因为windows库体积的限制，windows cuda将不提供静态库。

**Comment by zhangting2020** [comment]
@ouyangguang0726 请问您的问题是否已解决？如果已解决，我们将关闭issue
