### ISSUE TITLE
如何使用pre-train的明文embedding词表去初始化Paddle的embedding

### ISSUE THREAD

**Issue by tonyhu20116543** [PaddlePaddle/Paddle#3023]
用Google的word2vec工具预训练了60M语料得出来的embedding明文词表，Paddle怎么用它去初始化CNN网络中的embedding向量，API接口是啥？怎么做

**Comment by tonyhu20116543** [comment]
能提供一个使用的demo吗

**Comment by typhoonzero** [comment]
dup: https://github.com/PaddlePaddle/Paddle/issues/2778

**Comment by lcy-seso** [comment]
I close this issue because it is duplicate to https://github.com/PaddlePaddle/Paddle/issues/2778, please feel free to reopen it if you have new problem.
