### ISSUE TITLE
profile 工具在aistudio中无法显示内容

### ISSUE THREAD

**Issue by waaaaaaater** [PaddlePaddle/Paddle#30242]
在aistudio的环境中使用profile工具，但是打印出profile  report

在pycahrm环境中可以使用。

请问有什么办法可以在aistudio中也看到profile report的结果吗？

**Comment by MrChengmo** [comment]
可以尝试将程序的输出结果重定向的一个文件中试试，在AIstudio的note中类似这样:

```shell
!python -u train.py &> log.txt &
```

**Comment by TCChenlong** [comment]
请问下你这边用的是什么profile工具？

**Comment by waaaaaaater** [comment]
@TCChenlong 

参考的这个官方示例
https://www.paddlepaddle.org.cn/documentation/docs/zh/advanced_guide/performance_improving/device_switching/device_switching.html
