### ISSUE TITLE
有适配Ubuntu（1660ti+cuda11.1）的版本么

### ISSUE THREAD

**Issue by ccbptm** [PaddlePaddle/Paddle#30253]
如题所示：
建立issue时，为快速解决问题，请您根据使用情况给出如下信息：
- 标题：请包含关键词“安装错误”/“编译错误”，例如“Mac编译错误”
- 版本、环境信息：
****************************************
Paddle version: None
Paddle With CUDA: None
OS: Ubuntu 18.04
Python version: 2.7.17
CUDA version: 11.1.74
Build cuda_11.1.TC455_06.29069683_0
cuDNN version: None.None.None
Nvidia driver version: 455.38
****************************************

- 安装方式信息：
1）pip安装/docker安装
2）本地编译：请提供cmake命令，编译命令
3）docker编译：请提供docker镜像，编译命令            
  特殊环境请注明：如离线安装等
- 复现信息：如为报错，请给出复现环境、复现步骤
- 问题描述：请详细描述您的问题，同步贴出报错信息、日志/代码关键片段

**Comment by danleifeng** [comment]
您好，可参考https://www.paddlepaddle.org.cn/ 上的安装指南，根据pip/conda/docker的安装方式，选择适合您的命令：
![image](https://user-images.githubusercontent.com/52735331/104144594-c2cdd500-53fe-11eb-89ac-6342a97a339e.png)
