### ISSUE TITLE
我需要的灵活的神经网络框架支持什么功能

### ISSUE THREAD

**Issue by lcy-seso** [PaddlePaddle/Paddle#3028]
@Superjom 建议写一些我作为用户，对神经网络框架会有什么样的功能需求。这里是简单写一些，不涉及具体的设计，仅抛砖引玉。

神经网络就像搭积木，当现有积木不能满足实现新的 idea 时，就需要自己来造积木，或者用旧积木拼新积木。开发新的模型，通常无外乎三件事情：写新的layer / op，写新的损失函数，动态连接网络。

1. 写新的 layer  / op
    - **像写公式一样写前向反向**，这一点我相信可以通过支持细粒度的 OP 来实现，以及通过将操作 Tensor 的各种运行也直接暴露给用户。

2. 写新的损失函数
    - 损失函数是学习任务的核心，深度学习的出现让花在“特征工程”上的时间，转向了“cost工程”。
    - 除了学习任务的常见损失函数，实际上用户会定制各种千奇百怪的损失函数，即使是细粒度的 OP 也无法解决，这时需要对 Tensor直接操作。
    - 把前向/反向怎么算扔给用户在（Paddle的）外部实现。前向/反向本质上只要返回 tensor，前向返回最终计算结果，反向返回对参数的导数，对输入的导数。
    -  对 Tensor 直接操作的结果能够再次还给框架，继续参于网络其它部分的BP过程。

3. 动态构建网络结构需要两种逻辑控制 ：循环和条件
    * 神经网络的构建类似于程序语言的三种执行逻辑：
        1. 顺序结构
            - 只要依次 forward-backward 网络中的每一个计算单元（layer 或者 细粒度的operator），也就是静态图。
        2. 条件结构
            - 需要支持逻辑运算operator，来判断条件是否成立，可能会包括：（1）与、或、非、异或；（2）判等、比大小
        3. 循环结构
            - 循环结构三要素：循环变量、循环体和循环终止条件，只有循环终止条件是需要考虑和设计的，也同样是条件结构需要解决的问题。

---
  * 我个人认为，pytorch 的极端动态性是和python是一种动态语言绑定在一起
  * 我见过的最大的一部分动态网络，用户是在向框架描述如何根据（1）输入数据；（2）前层计算结果来连接一些预定义子模型的连接策略，也就是需要：“条件”和“循环”两种操作。
  * 我个人觉得“以静换动”已经可以满足很大一部分需要，因为连接策略始终是静态的，只有输入数据和运算结果是动态的，不必在一开始便追求极致地动态性。
---

4. 灵活的输入数据操作 operator （这个基于 Tensor 其实比较简单）
    - 当网络具有一定的动态性时，也会需要一些相应的数据处理：对 tensor 的选择行/列、裁剪、拼接，重组为神经网络中下一个op 需要的输入数据。

简单地总结一下，我需要框架能够非常方便（留给我处理的越少越好）实现两个大的功能：
1.  直接操作 tensor （像numpy和matlab的矩阵操作）：获取网络任一层的计算结果和梯度。
2.  循环和条件 operator （含逻辑判断operator）

**Comment by QiJune** [comment]
为什么需要直接操作tensor呢，足够细粒度的Op应该可以满足用户自定义的cost吧。
如果用户真的定义了千奇百怪的cost函数，那么用户就自己实现一个cost op，这个成员函数可以拿到tensor，然后在这个成员函数里面定义对tensor的操作。

**Comment by lcy-seso** [comment]
对，其实可以这样说，可以把需要做的所有开发都归结到写一个新的 OP。

对我来说，需要做的所有事情如果必须用一句话来概括，可能就是：写前向写反向。如果有自动求导或者细粒度的OP，连反向都不需要写，是最好的。我不喜欢写反向，因为复杂的计算想打包在一起算，而不是啥都靠拼，这时候梯度需要推公式，容易错。

可能这是一个锦上添花的东西，决定了想让用户用什么方式来写 OP。

* 用C++，编译进 Paddle是没问题的。那用户是不是需要了解一些Paddle实现的细节？
* 如果暴露 tensor，用户可以自己在外部用自己喜欢的任意方式来实现自己需要的计算。这时候暴露的只是一个概念。

**Comment by Superjom** [comment]
意思应该是，为了方便调研，支持用python写op，因为可能有一些细粒度不支持的op，而非必须用C++，很多搞学术的c++一般不太行。

现在tf-based-keras 也支持python 直接写 op，方法就是，将tensor 转成 numpy，python-based-op 操作之，之后再赋值回目标tensor。

支持并不一定太难。
@QiJune

**Comment by QiJune** [comment]
@lcy-seso 
关于反向过程是否需要书写：
- 如果用户用paddle提供的细粒度的op组合成一个cost op，那么他就不需要自己写反向的过程
- 如果用户打算自己写一个奇怪的op，那么用户就需要自己实现cost op，然后书写前向和反向的计算过程

关于是否暴露tensor：
因为现在的设计是用户先描述网络，然后再执行网络。而暴露tensor之后，对tensor的操作会直接对应到内存或显存，这里可能有两个问题：
- 对tensor的操作是立即执行的，这个与之前先描述再执行的设计有冲突
- 需要完成一个支持CPU/GPU的矩阵库，否则用户是很难写在GPU上的tensor操作的

**Comment by lcy-seso** [comment]
@QiJune  明白。并不是一定需要，而是描述一种我自己常常会遇到的需求。灵活性和效率可能不能兼顾。

有办法写前向或者反向就可以，只是，这个过程越方便越好。

**Comment by lcy-seso** [comment]
我觉得并不需要并不需要极致的动态性。

**Comment by QiJune** [comment]
@lcy-seso @Superjom 
总结一下刚才的讨论：
- paddle以后会提供把python的一个函数注册为op的接口。当用户需要些一个复杂的操作时，就在python端写一个操作numpy的函数，然后把这个函数注册为op。
- 同时，对GPU训练的情况，由paddle来负责拷贝数据，从而实现python op在CPU上的计算。

这样能够提供一定的灵活性，性能会较低。追求性能的话，就需要自己在C++/CUDA里面实现自己的Op。

**Comment by Superjom** [comment]
补充下

1. 优先实现 tf 的那一套 cond op, 以支持工业级的应用
2. dynet 那一套如果代价比较小，可以后续加入
3. 支持 python 写 op/cost/layer ， tensor 会自动转到 Numpy，用户代码只需要操作 numpy 便可

@lcy-seso @reyoung @QiJune

**Comment by lcy-seso** [comment]
我觉得没有必要追求dynet的动态网络，只需要“以静态换取动态”就可以。

**Comment by jacquesqiao** [comment]
现在的python接口已经把tensor暴露出来了，是可以直接操作的，直接转换成numpy了

**Comment by lcy-seso** [comment]
不要随便说搞研究的C++不行啊。。。这是一种选择，真正的学习能力可以学会任何东西。剩下的只是练习而已。

**Comment by Superjom** [comment]
我错了，是为了节约调研op的时间

```
`````````````````````-/://````````````````````````
``/::/```````````::..o  `//```````````````````````
`+.  `o````````.o`.+y-  `:+``````.-::///////:.````
`+. `-/o````````o` .o:  .+o//++++//:---------+o.``
``:::.`.````..``.+-.-:``..`````````.....------:s``
`````````:+/-```    ``     :.           `.-----y``
````````:s       ``-s`     `-+os-         `.---o.`
````````y.      -oo:`         `` ..---::`  .---+.`
````````h   `----::`           .-`     `/+``---/.`
````````y  :-      /+`        `:         -o`---:.`
````````s .:        +/        `/         `y`---:-`
````````y ./        o/         /.        o:.---/-`
````````y  :/`    .++`          -//:-.   .+----+.`
````````y  `+   /+:`   /----/     `.-+.   `o---s``
````````y  :-  `o`     +oooos         +    /:-:s``
````````o: :-   o`     :o+++y`        /`   `+-y.``
````````.+/s-..-o.```  .y+++s:```....-//..-:y+.```
````````````.+++oooyyo:ss::::h/:s::::::::-.```````
`````````````:///::o+.:oo-/+o/`-o.````````````````
``````````````````...`++/:-.-so+//````````````````
````````````o::-`````.s/////:-yys/````````````````
````````````-/ ++``-/:.--+/-::++o`````````````````
````````.++::`.o:--s-.::+/.::::/s///---...````````
``````````-////++oy/o++ooo+/+///s+o////////:-`````
`````````````.--::///////////+++////////::--.`````
```

**Comment by lcy-seso** [comment]
哈哈哈~ 科学家永远会有一堆现成框架做不出来的模型，他们希望神经网络就是在写公式，O(∩_∩)O~

立志做研究的那群人，有足够的学习能力学会任何框架，并不是能够轻易取悦的人群。相反，我觉得能够提高效率，降低深度学习的门槛，支持工业级别的应用是优先目标。
