### ISSUE TITLE
CUDNN_STATUS_EXECUTION_FAILED，operator < conv2d_fusion > error

### ISSUE THREAD

**Issue by lleesg** [PaddlePaddle/Paddle#30290]
**ENV：**
TX2、Ubuntu18.04、CUDA10.2、cudnn 8.0.0、jetpack 4.4、python3.6、Paddle-release-2.0-rc0

**Problem description：**
It's ok using CPU, but met error when using GPU:

dji@manifold2:~/Desktop/Paddle-Inference-Demo-master_lisg$ /usr/bin/python3 /home/dji/Desktop/Paddle-Inference-Demo-master_lisg/python/yolov3/infer_yolov3.py
W0111 14:06:22.129977  4282 analysis_predictor.cc:1042] Deprecated. Please use CreatePredictor instead.
W0111 14:06:24.379465  4282 analysis_predictor.cc:604] The one-time configuration of analysis predictor failed, which may be due to native predictor called first and its configurations taken effect.
I0111 14:06:24.379587  4282 analysis_predictor.cc:139] Profiler is deactivated, and no profiling report will be generated.
--- Running analysis [ir_graph_build_pass]
--- Running analysis [ir_graph_clean_pass]
--- Running analysis [ir_analysis_pass]
--- Running IR pass [is_test_pass]
--- Running IR pass [simplify_with_basic_ops_pass]
--- Running IR pass [conv_affine_channel_fuse_pass]
--- Running IR pass [conv_eltwiseadd_affine_channel_fuse_pass]
--- Running IR pass [conv_bn_fuse_pass]
I0111 14:06:25.305115  4282 graph_pattern_detector.cc:100] ---  detected 73 subgraphs
--- Running IR pass [conv_eltwiseadd_bn_fuse_pass]
--- Running IR pass [embedding_eltwise_layernorm_fuse_pass]
--- Running IR pass [multihead_matmul_fuse_pass_v2]
--- Running IR pass [fc_fuse_pass]
--- Running IR pass [fc_elementwise_layernorm_fuse_pass]
--- Running IR pass [conv_elementwise_add_act_fuse_pass]
I0111 14:06:25.582264  4282 graph_pattern_detector.cc:100] ---  detected 32 subgraphs
--- Running IR pass [conv_elementwise_add2_act_fuse_pass]
I0111 14:06:25.643519  4282 graph_pattern_detector.cc:100] ---  detected 16 subgraphs
--- Running IR pass [conv_elementwise_add_fuse_pass]
I0111 14:06:25.673298  4282 graph_pattern_detector.cc:100] ---  detected 31 subgraphs
--- Running IR pass [transpose_flatten_concat_fuse_pass]
--- Running IR pass [runtime_context_cache_pass]
--- Running analysis [ir_params_sync_among_devices_pass]
I0111 14:06:25.752739  4282 ir_params_sync_among_devices_pass.cc:45] Sync params from CPU to GPU
--- Running analysis [adjust_cudnn_workspace_size_pass]
--- Running analysis [inference_op_replace_pass]
--- Running analysis [memory_optimize_pass]
I0111 14:06:26.571358  4282 memory_optimize_pass.cc:198] Cluster name : yolo_box0.tmp_0  size: 17328
I0111 14:06:26.571424  4282 memory_optimize_pass.cc:198] Cluster name : image  size: 4435968
I0111 14:06:26.571465  4282 memory_optimize_pass.cc:198] Cluster name : res2c.add.output.5.tmp_1  size: 23658496
I0111 14:06:26.571482  4282 memory_optimize_pass.cc:198] Cluster name : transpose_0.tmp_0  size: 25992
I0111 14:06:26.571499  4282 memory_optimize_pass.cc:198] Cluster name : res4a.add.output.5.tmp_1  size: 5914624
I0111 14:06:26.571516  4282 memory_optimize_pass.cc:198] Cluster name : tmp_31  size: 23104
I0111 14:06:26.571532  4282 memory_optimize_pass.cc:198] Cluster name : res5c.add.output.5.tmp_1  size: 2957312
I0111 14:06:26.571547  4282 memory_optimize_pass.cc:198] Cluster name : leaky_relu_6.tmp_0  size: 1478656
I0111 14:06:26.571563  4282 memory_optimize_pass.cc:198] Cluster name : concat_5.tmp_0  size: 7393280
I0111 14:06:26.571579  4282 memory_optimize_pass.cc:198] Cluster name : leaky_relu_2.tmp_0  size: 739328
I0111 14:06:26.571595  4282 memory_optimize_pass.cc:198] Cluster name : sigmoid_11.tmp_0  size: 69312
I0111 14:06:26.571611  4282 memory_optimize_pass.cc:198] Cluster name : slice_34.tmp_0  size: 92416
I0111 14:06:26.571626  4282 memory_optimize_pass.cc:198] Cluster name : res2b.add.output.5.tmp_1  size: 23658496
I0111 14:06:26.571641  4282 memory_optimize_pass.cc:198] Cluster name : yolo_box1.tmp_0  size: 69312
I0111 14:06:26.571656  4282 memory_optimize_pass.cc:198] Cluster name : pow_16.tmp_0  size: 23104
I0111 14:06:26.571673  4282 memory_optimize_pass.cc:198] Cluster name : tmp_27  size: 23104
I0111 14:06:26.571689  4282 memory_optimize_pass.cc:198] Cluster name : im_size  size: 8
I0111 14:06:26.571705  4282 memory_optimize_pass.cc:198] Cluster name : slice_39.tmp_0  size: 23104
--- Running analysis [ir_graph_to_program_pass]
I0111 14:06:26.813918  4282 analysis_predictor.cc:537] ======= optimize end =======
I0111 14:06:26.814158  4282 naive_executor.cc:102] ---  skip [feed], feed -> im_size
I0111 14:06:26.814227  4282 naive_executor.cc:102] ---  skip [feed], feed -> image
I0111 14:06:26.823889  4282 naive_executor.cc:102] ---  skip [res2b.add.output.5.tmp_1], fetch -> fetch
W0111 14:06:27.003343  4282 device_context.cc:338] Please NOTE: device: 0, CUDA Capability: 62, Driver API Version: 10.2, Runtime API Version: 10.2
W0111 14:06:27.008149  4282 device_context.cc:346] device: 0, cuDNN Version: 8.0.
/usr/lib/python3/dist-packages/apport/report.py:13: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import fnmatch, glob, traceback, errno, sys, atexit, locale, imp
Traceback (most recent call last):
  File "/home/dji/Desktop/Paddle-Inference-Demo-master_lisg/python/yolov3/infer_yolov3.py", line 112, in <module>
    result = run(pred, [data, im_shape])  
  File "/home/dji/Desktop/Paddle-Inference-Demo-master_lisg/python/yolov3/infer_yolov3.py", line 62, in run
    predictor.zero_copy_run()
paddle.fluid.core_noavx.EnforceNotMet: 

  Compile Traceback (most recent call last):
    File "e:\majoring\AI\PaddlePaddle\PaddleDetection\PaddleDetection-release-0.5_lisg\tools\export_model.py", line 93, in <module>
      main()
    File "e:\majoring\AI\PaddlePaddle\PaddleDetection\PaddleDetection-release-0.5_lisg\tools\export_model.py", line 63, in main
      test_fetches = model.test(feed_vars, exclude_nms=FLAGS.exclude_nms)
    File "e:\majoring\AI\PaddlePaddle\PaddleDetection\PaddleDetection-release-0.5_lisg\ppdet\modeling\architectures\yolo.py", line 165, in test
      return self.build(feed_vars, mode='test', exclude_nms=exclude_nms)
    File "e:\majoring\AI\PaddlePaddle\PaddleDetection\PaddleDetection-release-0.5_lisg\ppdet\modeling\architectures\yolo.py", line 61, in build
      body_feats = self.backbone(im)
    File "e:\majoring\AI\PaddlePaddle\PaddleDetection\PaddleDetection-release-0.5_lisg\ppdet\modeling\backbones\resnet.py", line 477, in __call__
      res = self.layer_warp(res, i)
    File "e:\majoring\AI\PaddlePaddle\PaddleDetection\PaddleDetection-release-0.5_lisg\ppdet\modeling\backbones\resnet.py", line 420, in layer_warp
      gcb_name=gcb_name)
    File "e:\majoring\AI\PaddlePaddle\PaddleDetection\PaddleDetection-release-0.5_lisg\ppdet\modeling\backbones\resnet.py", line 333, in bottleneck
      dcn_v2=(i == 1 and dcn_v2))
    File "e:\majoring\AI\PaddlePaddle\PaddleDetection\PaddleDetection-release-0.5_lisg\ppdet\modeling\backbones\resnet.py", line 181, in _conv_norm
      name=_name + '.conv2d.output.1')
    File "E:\ProgramFiles\Anaconda3\lib\site-packages\paddle\fluid\layers\nn.py", line 1597, in conv2d
      "data_format": data_format,
    File "E:\ProgramFiles\Anaconda3\lib\site-packages\paddle\fluid\layer_helper.py", line 43, in append_op
      return self.main_program.current_block().append_op(*args, **kwargs)
    File "E:\ProgramFiles\Anaconda3\lib\site-packages\paddle\fluid\framework.py", line 2917, in append_op
      attrs=kwargs.get("attrs", None))
    File "E:\ProgramFiles\Anaconda3\lib\site-packages\paddle\fluid\framework.py", line 2014, in __init__
      for frame in traceback.extract_stack():

--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
0   paddle::AnalysisPredictor::ZeroCopyRun()
1   paddle::framework::NaiveExecutor::Run()
2   paddle::framework::OperatorBase::Run(paddle::framework::Scope const&, paddle::platform::Place const&)
3   paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, paddle::platform::Place const&) const
4   paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, paddle::platform::Place const&, paddle::framework::RuntimeContext*) const
5   std::_Function_handler<void (paddle::framework::ExecutionContext const&), paddle::framework::OpKernelRegistrarFunctor<paddle::platform::CUDAPlace, false, 0ul, paddle::operators::CUDNNConvFusionOpKernel<float>, paddle::operators::CUDNNConvFusionOpKernel<double> >::operator()(char const*, char const*, int) const::{lambda(paddle::framework::ExecutionContext const&)#1}>::_M_invoke(std::_Any_data const&, paddle::framework::ExecutionContext const&)
6   paddle::operators::CUDNNConvFusionOpKernel<float>::Compute(paddle::framework::ExecutionContext const&) const
7   paddle::platform::EnforceNotMet::EnforceNotMet(std::__exception_ptr::exception_ptr, char const*, int)
8   std::string paddle::platform::GetTraceBackString<char const*>(char const*&&, char const*, int)
9   paddle::platform::GetCurrentTraceBackString[abi:cxx11]()

----------------------
Error Message Summary:
----------------------
ExternalError:  Cudnn error, CUDNN_STATUS_EXECUTION_FAILED  (at /home/dji/Desktop/disk/paddle/paddle/fluid/operators/fused/conv_fusion_op.cu:319)
  [operator < conv2d_fusion > error]

**Is this error caused by cudnn 8.0.0? but from "2.0-rc0 Release Note" I read "预测库支持cuda10.2-cudnn8-trt7.1的版本"**

**Comment by ForFishes** [comment]
This error is generally caused by a mismatched environment. Be able to tell your graphics card model and cudnn / cuda version number. Maybe your graphics card does not support cudnn.

**Comment by lleesg** [comment]
> This error is generally caused by a mismatched environment. Be able to tell your graphics card model and cudnn / cuda version number. Maybe your graphics card does not support cudnn.

I export the model from AIStudio which also use PaddlePaddle 2.0.0rc, and the target platform is Jetson TX2 in which ENV is:
Ubuntu 18.04
cuda 10.2.89
cudnn 8.0.0
jetpack 4.4
TensorRT v7

 could u offer more infos? 3q~~

**Comment by lleesg** [comment]
> This error is generally caused by a mismatched environment. Be able to tell your graphics card model and cudnn / cuda version number. Maybe your graphics card does not support cudnn.

I did some experiment:
**code1:**
    config.enable_tensorrt_engine(  \
        1 << 30, 
        1,   
        3,    
        Config.Precision.Float32, 
        False,    
        False,  
        )
**code2:**  
     config.switch_ir_option(False)
    # see https://github.com/PaddlePaddle/Paddle/issues/30132#issuecomment-755125908


1.**no code1 or code 2:** met the CUDNN_STATUS_EXECUTION_FAILED  error as above topic show
2.**add code1 and code2:** run successfully and get right predictions but didn't enable TRT
3.**only code1:** run successfully but get wrong prediction of which the scores are very low——about 0.01


I need TRT for  acceleration, and I can't figure out what's happening during the three cases..

**Comment by shangzhizhou** [comment]
Maybe it is a bug of cudnn like this, https://forums.developer.nvidia.com/t/nx-jp44-cudnn-internal-logic-error/124805。You can try to delete conv_fuse passes（conv_bn_fuse_pass, conv_elementwise_add_act_fuse_pass,  conv_elementwise_add2_act_fuse_pass, conv_elementwise_add_fuse_pass） with config.delete_pass("xx") api.

**Comment by lleesg** [comment]
> Maybe it is a bug of cudnn like this, [https://forums.developer.nvidia.com/t/nx-jp44-cudnn-internal-logic-error/124805。You](https://forums.developer.nvidia.com/t/nx-jp44-cudnn-internal-logic-error/124805%E3%80%82You) can try to delete conv_fuse passes（conv_bn_fuse_pass, conv_elementwise_add_act_fuse_pass, conv_elementwise_add2_act_fuse_pass, conv_elementwise_add_fuse_pass） with config.delete_pass("xx") api.

thank u, it worked. and waiting for this bug getting fixed...
