### ISSUE TITLE
运行官方示例，阻塞在tensors = exe.run(fetch_var_names, return_merged)._move_to_list()

### ISSUE THREAD

**Issue by bjkxt** [PaddlePaddle/Paddle#30298]
如果您没有查询到相似问题，为快速解决您的提问，建立issue时请提供如下细节信息：
- 标题：简洁、精准概括您的问题，例如“Insufficient Memory xxx" ”
- 版本、环境信息：
    1）PaddlePaddle版本：1.8
    2）CPU：more /proc/cpuinfo
processor	: 0
vendor_id	: GenuineIntel
cpu family	: 6
model		: 85
model name	: Intel(R) Xeon(R) Silver 4214 CPU @ 2.20GHz
stepping	: 7
microcode	: 83886124
cpu MHz		: 2194.849
cache size	: 16896 KB
physical id	: 0
siblings	: 24
core id		: 0
cpu cores	: 12
apicid		: 0
initial apicid	: 0
fpu		: yes
fpu_exception	: yes
cpuid level	: 22
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_pe
rfmon pebs bts rep_good xtopology nonstop_tsc aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadli
ne_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch ida arat epb xsaveopt pln pts dtherm hwp_epp tpr_shadow vnmi flexpriority ept vpid fsgsbase bmi1 hle avx2 smep bmi2 erms invpc
id rtm cqm avx512f rdseed adx avx512cd cqm_llc cqm_occup_llc
bogomips	: 4389.69
clflush size	: 64
cache_alignment	: 64
address sizes	: 46 bits physical, 48 bits virtual
power management:
    3）GPU：未使用
    4）系统环境：CentOS release 6.9 (Final)
 注：您可以通过执行[summary_env.py](https://github.com/PaddlePaddle/Paddle/blob/develop/tools/summary_env.py)获取以上信息。
执行结果如下：
****************************************
Paddle version: 1.8.5
Paddle With CUDA: False
OS: CentOS 6.9
Python version: 3.8.7
CUDA version: None
cuDNN version: None.None.None
Nvidia driver version: None
****************************************

- 训练信息
    1）单机/多机，单卡/多卡
    2）显存信息
    3）Operator信息
- 复现信息：如为报错，请给出复现环境、复现步骤
- 问题描述：请详细描述您的问题，同步贴出报错信息、日志、可复现的代码片段

执行官方文档https://www.paddlepaddle.org.cn/tutorials/projectdetail/487871中关于同步训练的例子，完整代码来自于https://github.com/MrChengmo/Fleet/tree/re_ctr/examples/distribute_ctr

执行本地模拟分布式时，无论方法一和方法二都会在某处卡住不动

方法一 运行local_cluster.sh脚本
sh local_cluster.sh sync
方法二 运行飞桨内置的一个启动器launch_ps
python -m paddle.distributed.launch_ps --worker_num 2 --server_num 2 train.py

通过在代码中加调试信息，发现是停在sync_train.py中语句：
loss_val, auc_val, batch_auc_val = exe.run(
                        program=compiled_prog,
                        fetch_list=[
                            avg_cost.name, auc_var.name, batch_auc_var.name
                        ])
继续调试，最终是停在 python3.8/site-packages/paddle/fluid/executor.py 中的 tensors = exe.run(fetch_var_names, return_merged)._move_to_list() 这一句，导致worker创建失败，整个训练过程无法完成。

请问应该如何才能使训练正常完成？

**Comment by MrChengmo** [comment]
请问使用的paddle版本是？来源代码的示例是paddle 1.6版本的，分布式-ps同步模式经过了很多次迭代，可能会有问题

**Comment by MrChengmo** [comment]
运行同步模式时，需要在环境变量中 

```
export CPU_NUM=X
```

X等于你配置的训练线程数

**Comment by bjkxt** [comment]
> 请问使用的paddle版本是？来源代码的示例是paddle 1.6版本的，分布式-ps同步模式经过了很多次迭代，可能会有问题

我的Paddle version: 1.8.5
如果是代码较旧，请问在哪里能找到适合1.8版本的代码？

**Comment by bjkxt** [comment]
> 运行同步模式时，需要在环境变量中
> 
> ```
> export CPU_NUM=X
> ```
> 
> X等于你配置的训练线程数

在通过sh local_cluster.sh sync启动的方式中，local_cluster.sh中已经设置了export CPU_NUM=2
同时我打印了参数params，其值为Namespace(batch_size=1000, cloud=0, **cpu_num=2**, dense_feature_dim=13, embedding_size=10, epochs=1, is_sparse=True, learning_rate=0.0001, log_path='result', model_path='model', name='ctr-dnn', sparse_feature_dim=1000001, test=True, test_files_path='test_data', train_files_path='train_data')

**Comment by MrChengmo** [comment]
> > 请问使用的paddle版本是？来源代码的示例是paddle 1.6版本的，分布式-ps同步模式经过了很多次迭代，可能会有问题
> 
> 我的Paddle version: 1.8.5
> 如果是代码较旧，请问在哪里能找到适合1.8版本的代码？

- https://github.com/PaddlePaddle/models/tree/release/1.8/PaddleRec/ctr/dnn 这个是官方示例
- 不推荐运行`同步模式`，速度相对较慢
- 如果运行同步模式，需要设置下CPU_NUM的环境变量，并且确保各个节点上的文件数量batch级别一致
- 需要配置同步模式的strategy 

```python
# train.py 208 行
strategy = DistributeTranspilerConfig()
strategy.sync_mode = True
#strategy.runtime_split_send_recv = True
```

**Comment by bjkxt** [comment]
> > > 请问使用的paddle版本是？来源代码的示例是paddle 1.6版本的，分布式-ps同步模式经过了很多次迭代，可能会有问题
> > 
> > 
> > 我的Paddle version: 1.8.5
> > 如果是代码较旧，请问在哪里能找到适合1.8版本的代码？
> 
> * https://github.com/PaddlePaddle/models/tree/release/1.8/PaddleRec/ctr/dnn 这个是官方示例
> * 不推荐运行`同步模式`，速度相对较慢
> * 如果运行同步模式，需要设置下CPU_NUM的环境变量，并且确保各个节点上的文件数量batch级别一致
> * 需要配置同步模式的strategy
> 
> ```python
> # train.py 208 行
> strategy = DistributeTranspilerConfig()
> strategy.sync_mode = True
> #strategy.runtime_split_send_recv = True
> ```

多谢，我用新代码再试下，非常感谢您的耐心解答
