### ISSUE TITLE
关于 paddle.norm 对 p = inf 的实现疑问

### ISSUE THREAD

**Issue by MARD1NO** [PaddlePaddle/Paddle#30293]
您好，关于Paddle内部对norm的实现我有些许疑问
![图片](https://user-images.githubusercontent.com/42901638/104151532-3a5c2e00-5418-11eb-9da3-d2ce56999b2e.png)
是norm类型为 inf 的时候
根据numpy文档（也可参考pytorch文档，pytorch是为了对齐Numpy的）
对于无穷范数应该定义为
![图片](https://user-images.githubusercontent.com/42901638/104151709-accd0e00-5418-11eb-9884-9d0b5f0169d7.png)

但是我感觉Paddle计算无穷范数的代码存在一定问题，相关代码地址在 https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/tensor/linalg.py#L174

而且与Pytorch运行结果也不一致

相关测试代码在
```python
import torch
import numpy as np
import paddle


a = np.random.randn(3, 3)
print("Input a is: ", a)
torch_a = torch.Tensor(a)

porder = np.inf

print(torch.linalg.norm(torch_a, ord=porder)) 

paddle_a = paddle.Tensor(a)
print(paddle.norm(paddle_a, p=porder))

print(np.linalg.norm(a, ord=porder))

```

感觉问题是出在 https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/tensor/linalg.py#L300-L301
对axis判断条件的不合理

**Comment by ZHUI** [comment]
感谢您的提问。
此处确实为，Paddle对 无穷**矩阵**范数 的支持有误。
目前调用的实现，计算的是 无穷**向量**范数，将矩阵作为向量看待。

实现没有对齐numpy， 我们将会进一步修改。你可以暂时通过组合op，实现需求。感谢！

**Comment by ZHUI** [comment]
感谢您的提问。
此处确实为，Paddle对 无穷**矩阵**范数 的支持有误。
目前调用的实现，计算的是 无穷**向量**范数，将矩阵作为向量看待。

实现没有对齐numpy， 我们将会进一步修改。您可以暂时通过组合op，实现需求。感谢！

**Comment by ZHUI** [comment]
> 感谢您的提问。
> 此处确实为，Paddle对 无穷**矩阵**范数 的支持有误。
> 目前调用的实现，计算的是 无穷**向量**范数，将矩阵作为向量看待。
> 
> 实现没有对齐numpy， 我们将会进一步修改。您可以暂时通过组合op，实现需求。感谢！

目前的行为与 torch.norm 一致，与torch.linalg.norm 的实现存在diff。
具体对齐的策略，我们会进一步讨论。

**Comment by MARD1NO** [comment]
> > 感谢您的提问。
> > 此处确实为，Paddle对 无穷**矩阵**范数 的支持有误。
> > 目前调用的实现，计算的是 无穷**向量**范数，将矩阵作为向量看待。
> > 实现没有对齐numpy， 我们将会进一步修改。您可以暂时通过组合op，实现需求。感谢！
> 
> 目前的行为与 torch.norm 一致，与torch.linalg.norm 的实现存在diff。
> 具体对齐的策略，我们会进一步讨论。

感谢您的回复～
