### ISSUE TITLE
Ubuntu安装错误

### ISSUE THREAD

**Issue by ccbptm** [PaddlePaddle/Paddle#30312]
1）PaddlePaddle版本：1.8.5
    2）CPU：请提供CPU型号，MKL/OpenBlas/MKLDNN/等数学库的使用情况
    3）GPU：1660ti + CUDA：10.0.130 + cudnn：7.6.5
    4）系统环境：
                  Paddle version: None
                  Paddle With CUDA: None
                 OS: Ubuntu 18.04
                 Python version: 2.7.17
                 CUDA version: 10.0.130
                 cuDNN version: 7.6.5
                 Nvidia driver version: 455.38

- 安装方式信息：
1）pip安装（python -m pip install paddlepaddle-gpu==1.8.5.post107 -i https://mirror.baidu.com/pypi/simple）           
- 复现信息：报错
- 
- 问题描述：请详细描述您的问题，同步贴出报错信息、日志/代码关键片段

```
 Installing build dependencies ... done
  Getting requirements to build wheel ... error
  ERROR: Command errored out with exit status 1:
   command: /usr/bin/python /usr/local/lib/python2.7/dist-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /tmp/tmpXGpwWT
       cwd: /tmp/pip-install-G1K3Ea/opencv-python
  Complete output (22 lines):
  Traceback (most recent call last):
    File "/usr/local/lib/python2.7/dist-packages/pip/_vendor/pep517/_in_process.py", line 280, in <module>
      main()
    File "/usr/local/lib/python2.7/dist-packages/pip/_vendor/pep517/_in_process.py", line 263, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/usr/local/lib/python2.7/dist-packages/pip/_vendor/pep517/_in_process.py", line 114, in get_requires_for_build_wheel
      return hook(config_settings)
    File "/tmp/pip-build-env-PyuMcH/overlay/lib/python2.7/site-packages/setuptools/build_meta.py", line 146, in get_requires_for_build_wheel
      return self._get_build_requires(config_settings, requirements=['wheel'])
    File "/tmp/pip-build-env-PyuMcH/overlay/lib/python2.7/site-packages/setuptools/build_meta.py", line 127, in _get_build_requires
      self.run_setup()
    File "/tmp/pip-build-env-PyuMcH/overlay/lib/python2.7/site-packages/setuptools/build_meta.py", line 243, in run_setup
      self).run_setup(setup_script=setup_script)
    File "/tmp/pip-build-env-PyuMcH/overlay/lib/python2.7/site-packages/setuptools/build_meta.py", line 142, in run_setup
      exec(compile(code, __file__, 'exec'), locals())
    File "setup.py", line 448, in <module>
      main()
    File "setup.py", line 99, in main
      % {"ext": re.escape(sysconfig.get_config_var("EXT_SUFFIX"))}
    File "/usr/lib/python2.7/re.py", line 210, in escape
      s = list(pattern)
  TypeError: 'NoneType' object is not iterable
  ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/bin/python /usr/local/lib/python2.7/dist-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /tmp/tmpXGpwWT Check the logs for full command output.
```

**Comment by ForFishes** [comment]
这应该是opencv的版本安装错了，你单独安装一下opencv试一下。
pip install opencv-python==4.4.0.42 -U

**Comment by ccbptm** [comment]
> 这应该是opencv的版本安装错了，你单独安装一下opencv试一下。
> pip install opencv-python==4.4.0.42 -U

DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support pip 21.0 will remove support for this functionality.
Defaulting to user installation because normal site-packages is not writeable
ERROR: Could not find a version that satisfies the requirement opencv-python==4.4.0.42-U (from versions: 3.1.0.0, 3.1.0.1, 3.1.0.2, 3.1.0.3, 3.1.0.4, 3.1.0.5, 3.2.0.6, 3.2.0.7, 3.2.0.8, 3.3.0.9, 3.3.0.10, 3.3.1.11, 3.4.0.12, 3.4.0.14, 3.4.1.15, 3.4.2.16, 3.4.2.17, 3.4.3.18, 3.4.4.19, 3.4.5.20, 3.4.6.27, 3.4.7.28, 3.4.8.29, 3.4.9.31, 3.4.10.37, 4.0.0.21, 4.0.1.23, 4.0.1.24, 4.1.0.25, 4.1.1.26, 4.1.2.30, 4.2.0.32, 4.3.0.38)
ERROR: No matching distribution found for opencv-python==4.4.0.42-U

**Comment by ccbptm** [comment]
> 这应该是opencv的版本安装错了，你单独安装一下opencv试一下。
> pip install opencv-python==4.4.0.42 -U

我已经解决问题了，最后安装了4.2.0.32 的opencv-python
谢谢您的帮助
