### ISSUE TITLE
有没有人编译成功jetson tx2的Python库，1.8.x版本的？

### ISSUE THREAD

**Issue by yeyupiaoling** [PaddlePaddle/Paddle#30319]
有没有人编译成功jetson tx2的Python库，1.8.x版本的？
 - Ubuntu 18.04
 - CUDA 10.0

有编译成功的，可以提供一下whl包吗？，谢谢！

**Comment by lleesg** [comment]
配置很难完全一样，建议重新编译下，有具体问题也许能帮上忙

**Comment by yeyupiaoling** [comment]
@LLeeSG TX2安装的系统不都是一样的吗？例如CUDA版本，TensorRT版本，Python版本，不应该是一样的吗？

我现在遇到的问题是报numpy没安装，但是我确确实实安装了。不知道这是为啥。

**Comment by lleesg** [comment]
> @LLeeSG TX2安装的系统不都是一样的吗？例如CUDA版本，TensorRT版本，Python版本，不应该是一样的吗？
> 
> 我现在遇到的问题是报numpy没安装，但是我确确实实安装了。不知道这是为啥。

不一定完全一样，比如我用的JETPACK4.4，CUDNN8。。
发一下详细信息？

**Comment by TCChenlong** [comment]
Linux 下 Paddle 1.8 的编译可以参考这个文档：https://www.paddlepaddle.org.cn/documentation/docs/zh/install/compile/linux-compile.html
2.0 rc1的编译可以参考这个文档：https://www.paddlepaddle.org.cn/documentation/docs/zh/2.0-rc1/install/compile/linux-compile.html
Paddle Inference 可以参考这个文档：https://paddle-inference.readthedocs.io/en/latest/demo_tutorial/cuda_jetson_demo.html#

**Comment by yeyupiaoling** [comment]
自行编译的Paddle的TX2的Python安装包，这里提供给同环境下载的同学下载。
 - Ubuntu 18.04
 - Python 3.6
 - jetpack 4.3
 - CUDA 10.0

下载链接：[点击下载](https://download.csdn.net/download/qq_33200967/14141147)

TX2必须要安装numpy1.18.5才行，否则报错。
```
pip3 install numpy==1.18.5  -i https://mirrors.aliyun.com/pypi/simple/
```

顺便提供C++库：[点击下载](https://download.csdn.net/download/qq_33200967/14141152)
