### ISSUE TITLE
为什么paddle训练过程中打印的__auc_evaluator_0__和classification_error_evaluator都为0

### ISSUE THREAD

**Issue by JayEworld** [PaddlePaddle/Paddle#3031]
你好，我提交了paddle任务在集群上进行训练，发现训练过程中输出大量__auc_evaluator_0__和classification_error_evaluator都为0的日志：
Mon Jul 24 17:03:02 2017[1,8]<stdout>:Pass 1, Batch 3, Cost 0.247531, {'__auc_evaluator_0__': 0.0, 'classification_error_evaluator': 0.0}
Mon Jul 24 17:03:02 2017[1,7]<stdout>:
Mon Jul 24 17:03:02 2017[1,7]<stdout>:Pass 1, Batch 3, Cost 0.248483, {'__auc_evaluator_0__': 0.0, 'classification_error_evaluator': 0.0}
请问这是怎么回事儿呢？
![image](https://user-images.githubusercontent.com/16730384/28516731-d1b90c98-7094-11e7-92c8-48d6a1b02140.png)

**Comment by dzhwinter** [comment]
样本分布不均衡导致，在一个batch中，都是负样本，计算auc为0.
另外，提issue请贴log，不要贴图。
