### ISSUE TITLE
paddle.distribution.Normal没有rsample

### ISSUE THREAD

**Issue by ShuaibinLi** [PaddlePaddle/Paddle#30321]
在实现策略梯度时需要用到rsample函数的reparameterization trick
torch中的如下
![image](https://user-images.githubusercontent.com/76139596/104262938-90d27680-54c3-11eb-9b10-ae134605554c.png)

**Comment by rical730** [comment]
rsample相比较sample可以回传梯度，在复现强化学习算法SAC的过程中非常关键，建议Paddle动态图也实现该功能。

**Comment by pangyoki** [comment]
近期会实现这个功能。

**Comment by pangyoki** [comment]
> 在实现策略梯度时需要用到rsample函数的reparameterization trick
> torch中的如下
> ![image](https://user-images.githubusercontent.com/76139596/104262938-90d27680-54c3-11eb-9b10-ae134605554c.png)

这个图片看不了，可以再发一下吗？

**Comment by rical730** [comment]
> 这个图片看不了，可以再发一下吗？

可以直接查看API：https://pytorch.org/docs/1.7.1/distributions.html#torch.distributions.distribution.Distribution.rsample

**Comment by pangyoki** [comment]
Paddle中的sample方法实际上与pytorch中的rsample一致，可以反向传播。麻烦看下paddle.distribution.Normal.sample方法能否满足需求。

**Comment by rical730** [comment]
刚刚测试了一下，确实是带梯度的 0.0，感谢同步信息，建议可以在文档上做出说明
