### ISSUE TITLE
同样的输入，gather api1.8.5版本和2.0rc0的结果不一样

### ISSUE THREAD

**Issue by Melon-Zhou** [PaddlePaddle/Paddle#30327]
1.8.5 paddle-gpu版本
2.0rc0 paddle-gpu版本

op调用代码
![image](https://user-images.githubusercontent.com/16741165/104277556-01888b80-54e2-11eb-9ebc-a0dd9f6c5807.png)

1.8.5的输入和输出
![image](https://user-images.githubusercontent.com/16741165/104277598-16651f00-54e2-11eb-8590-8190646a755c.png)

2.0rc0的输入和输出
![image](https://user-images.githubusercontent.com/16741165/104277644-2846c200-54e2-11eb-91b2-6a59a219e527.png)

**Comment by ForFishes** [comment]
这个看只是lod信息的diff吧。1.8的版本丢失了lod信息，2.0修复了这个问题，所以lod信息存在diff。

**Comment by Melon-Zhou** [comment]
有什么办法能把这个lod信息去掉吗？

**Comment by ForFishes** [comment]
def lod_reset(x, y=None, target_lod=None)使用这个api吧，重新设置lod为空。

**Comment by Melon-Zhou** [comment]
> def lod_reset(x, y=None, target_lod=None)使用这个api吧，重新设置lod为空。

这个方法不行，y和target_lod不能同时为空。 target_lod设置成[]也不行。还有其他办法吗？
