### ISSUE TITLE
跑集群任务时，提示：ImportError: /lib64/tls/libc.so.6: version `GLIBC_2.14' not found 

### ISSUE THREAD

**Issue by zyz282994112** [PaddlePaddle/Paddle#3033]
尝试跑集群任务时，提示：ImportError: /lib64/tls/libc.so.6: version `GLIBC_2.14' not found (required by /home/work/zhangyizhou/generate_title/paddle/python27/lib/python2.7/lib-dynload/_collections.so)

**Comment by dzhwinter** [comment]
由于编译的版本gcc版本高于运行的线上机器版本导致。libc是gcc包含的基础库之一，`GLIBC_XXX`字段标识了libc版本。
可以通过`strings  /lib64/tls/libc.so.6  | grep -i glibc` 确认当前的libc版本是否符合要求。
解决方法是找到线上机器部署的高版本gcc，设置 
`LD_LIBRARY_PATH=<GCC_LIBRARY_PATH>/lib64:$:LD_LIBRARY_PATH`

**Comment by dzhwinter** [comment]
close this issue since it has been solved. If there is any question, please let us know.

**Comment by lxk1990727** [comment]
我提交任务的时候，出现同样的错误ImportError: /lib64/tls/libc.so.6: version `GLIBC_2.14' not found (required by /home/work/zhangyizhou/generate_title/paddle/python27/lib/python2.7/lib-dynload/_collections.so)，在提交脚本里添加LD_LIBRARY_PATH=/opt/compiler/gcc-4.8.2/lib64:$LD_LIBRARY_PATH，又报了 /bin/bash: error while loading shared libraries: /opt/compiler/gcc-4.8.2/lib64/libc.so.6: ELF file OS ABI invalid 错误。

**Comment by lcy-seso** [comment]
close this issue due to inactivity.

**Comment by waterzxj** [comment]
python 版本的问题
