### ISSUE TITLE
使用Paddle-TensorRT库预测动态shape和Static mode冲突

### ISSUE THREAD

**Issue by jedibobo** [PaddlePaddle/Paddle#30350]
- 标题：使用Paddle-TensorRT库预测动态shape和Static mode冲突
- 版本、环境信息：
    1）PaddlePaddle版本：v2.0.0-rc0
    2）CPU：6230R
    3）GPU：Geforce 3090， CUDA 11 ，TRT 7
    4）系统环境：Ubuntu18.04LTS Python 3.7.9

-预测信息
    1）python预测时使用Dynamic shape时如果使用Static mode的时候会冲突。
具体操作如下：我使用Float32或者Half精度。同时设置static mode和dynamic shape，生成的序列文件不能用。
报错如下：
W0112 13:48:25.660892  6355 tensorrt_subgraph_pass.cc:293] The Paddle lib links the 7216 version TensorRT, make sure the runtime TensorRT you are using is no less than this version, otherwise, there might be Segfault!
E0112 13:48:26.261205  6355 helper.h:78] INVALID_ARGUMENT: getPluginCreator could not find plugin pool_plugin version 1
E0112 13:48:26.261236  6355 helper.h:78] safeDeserializationUtils.cpp (322) - Serialization Error in load: 0 (Cannot deserialize plugin since corresponding IPluginCreator not found in Plugin Registry)
E0112 13:48:26.261353  6355 helper.h:78] INVALID_STATE: std::exception
E0112 13:48:26.261407  6355 helper.h:78] INVALID_CONFIG: Deserialize the cuda engine failed.
Traceback (most recent call last):
  File "test.py", line 96, in <module>
    pred = init_predictor(args)
  File "test.py", line 37, in init_predictor
    predictor = create_predictor(config)
paddle.fluid.core_avx.EnforceNotMet: 

--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
0   paddle_infer::Predictor::Predictor(paddle::AnalysisConfig const&)
1   std::unique_ptr<paddle::PaddlePredictor, std::default_delete<paddle::PaddlePredictor> > paddle::CreatePaddlePredictor<paddle::AnalysisConfig, (paddle::PaddleEngineKind)2>(paddle::AnalysisConfig const&)
2   paddle::AnalysisPredictor::Init(std::shared_ptr<paddle::framework::Scope> const&, std::shared_ptr<paddle::framework::ProgramDesc> const&)
3   paddle::AnalysisPredictor::PrepareProgram(std::shared_ptr<paddle::framework::ProgramDesc> const&)
4   paddle::AnalysisPredictor::OptimizeInferenceProgram()
5   paddle::inference::analysis::Analyzer::RunAnalysis(paddle::inference::analysis::Argument*)
6   paddle::inference::analysis::IrAnalysisPass::RunImpl(paddle::inference::analysis::Argument*)
7   paddle::inference::analysis::IRPassManager::Apply(std::unique_ptr<paddle::framework::ir::Graph, std::default_delete<paddle::framework::ir::Graph> >)
8   paddle::framework::ir::Pass::Apply(paddle::framework::ir::Graph*) const
9   paddle::inference::analysis::TensorRtSubgraphPass::ApplyImpl(paddle::framework::ir::Graph*) const
10  paddle::inference::analysis::TensorRtSubgraphPass::CreateTensorRTOp(paddle::framework::ir::Node*, paddle::framework::ir::Graph*, std::vector<std::string, std::allocator<std::string > > const&, std::vector<std::string, std::allocator<std::string > >*) const
11  paddle::inference::tensorrt::TensorRTEngine::Deserialize(std::string const&)
12  paddle::platform::EnforceNotMet::EnforceNotMet(std::string const&, char const*, int)
13  paddle::platform::GetCurrentTraceBackString[abi:cxx11]()

----------------------
Error Message Summary:
----------------------
FatalError: Building TRT cuda engine failed when deserializing engine info. Please check:
1. Your TRT serialization is generated and loaded on the same GPU architecture;
2. The Paddle Inference version of generating serialization file and doing inference are consistent.
  [Hint: infer_engine_ should not be null.] (at /home/liuyibo/build_github/Paddle/paddle/fluid/inference/tensorrt/engine.h:246)

推理脚本：
import numpy as np
import argparse
import cv2
import os
from paddle.inference import Config
from paddle.inference import create_predictor

from utils import preprocess

def init_predictor(args):
    if args.model_dir is not "":
        config = Config(args.model_dir)
    else:
        config = Config(args.model_file, args.params_file)

    config.enable_memory_optim()
    if args.use_gpu:
        config.enable_use_gpu(1000, 0)
        config.enable_tensorrt_engine(
	    workspace_size=1<<20,
 	    max_batch_size=1,
        min_subgraph_size=3,
        precision_mode=Config.Precision.Float32,
        use_static=True,
        use_calib_mode=False)
        min_input_shape = {"image":[1,3, 10, 10]}
        max_input_shape = {"image":[1,3, 224, 224]}
        opt_input_shape = {"image":[1,3, 100, 100]}
        config.set_trt_dynamic_shape_info(min_input_shape, max_input_shape, opt_input_shape)
    else:
        # If not specific mkldnn, you can set the blas thread.
        # The thread num should not be greater than the number of cores in the CPU.
        config.set_cpu_math_library_num_threads(4)
        config.enable_mkldnn()

    predictor = create_predictor(config)
    return predictor

def run(predictor, img):
    # copy img data to input tensor
    input_names = predictor.get_input_names()
    for i, name in enumerate(input_names):
        input_tensor = predictor.get_input_handle(name)
        input_tensor.reshape(img[i].shape)
        input_tensor.copy_from_cpu(img[i].copy())

    # do the inference
    predictor.run()

    results = []
    # get out data from output tensor
    output_names = predictor.get_output_names()
    for i, name in enumerate(output_names):
        output_tensor = predictor.get_output_handle(name)
        output_data = output_tensor.copy_to_cpu()
        results.append(output_data)

    return results

def parse_args():
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--model_file",
        type=str,
        default="",
        help="Model filename, Specify this when your model is a combined model."
    )
    parser.add_argument(
        "--params_file",
        type=str,
        default="",
        help=
        "Parameter filename, Specify this when your model is a combined model."
    )
    parser.add_argument(
        "--model_dir",
        type=str,
        default="",
        help=
        "Model dir, If you load a non-combined model, specify the directory of the model."
    )
    parser.add_argument("--use_gpu",
                        type=int,
                        default=0,
                        help="Whether use gpu.")
    return parser.parse_args()

import time 
count=0
num=0
if __name__ == '__main__':
    args = parse_args()
    pred = init_predictor(args)
    img_size=96
    path="./3"
    for root,dirs,files in os.walk(path):
        for file in files:
            img_name = root + '/' + file
            img_saving_path = img_name.replace('.jpg', 'result_' + str(round(time.time() * 1000)) + '.jpg')
            save_img_name = 'result/' + img_saving_path.split('/')[-1]
            img = cv2.imread(img_name)

            start=time.time()
            img = preprocess(img,img_size)
            result = run(pred, [img])
            end=time.time()
            print("fps: ",1/(end-start))
            num+=1
            print("class index: ", np.argmax(result[0][0]))
            if np.argmax(result[0][0])==3:
                count+=1
    print("precision:",count/num)

但是，如果我删除那个序列文件夹。然后先打开static mode关闭dynamic shape，就可以正常加载。如果之后不用dynamic shape，可以正常推理。但是如果加载dynamic shape就没有正确结果。
E0112 13:55:07.131140  8375 helper.h:78] Parameter check failed at: engine.cpp::setBindingDimensions::1128, condition: engineDims.nbDims == dimensions.nbDims
E0112 13:55:07.131161  8375 helper.h:78] Parameter check failed at: engine.cpp::enqueueV2::605, condition: !mEngine.hasImplicitBatchDimension()
fps:  1751.2751565762005
class index:  0

**Comment by cryoco** [comment]
您好，我们尚未支持TRT7.2，目前最高支持到TRT7.1.3，您可以用这个版本试下

**Comment by jedibobo** [comment]
> 您好，我们尚未支持TRT7.2，目前最高支持到TRT7.1.3，您可以用这个版本试下

也就是说7.2 的trt支持同时动态shape和static mode吗？

**Comment by cryoco** [comment]
您指的static mode是序列化功能吗？这个功能和动态shape不冲突的，您的报错可能是因为paddle-trt对7.2尚未做支持，而非这两个功能有冲突。

**Comment by jedibobo** [comment]
> 您指的static mode是序列化功能吗？这个功能和动态shape不冲突的，您的报错可能是因为paddle-trt对7.2尚未做支持，而非这两个功能有冲突。

emm我用的那个trt就是7.1.3的，然后遇到冲突的啊。

**Comment by cryoco** [comment]
> W0112 13:48:25.660892 6355 tensorrt_subgraph_pass.cc:293] The Paddle lib links the 7216 version TensorRT

您报错log里显示您编译Paddle预测库时链接的是TRT 7.2.1.6，这个版本需要和运行时链接的版本保持一致，建议都使用7.1.3

**Comment by jedibobo** [comment]
> > W0112 13:48:25.660892 6355 tensorrt_subgraph_pass.cc:293] The Paddle lib links the 7216 version TensorRT
> 
> 您报错log里显示您编译Paddle预测库时链接的是TRT 7.2.1.6，这个版本需要和运行时链接的版本保持一致，建议都使用7.1.3

抱歉啊看错了，7.1.3是我jetson上的。。。一时脑残。

**Comment by jedibobo** [comment]
一直现在服务器上调试完才放到agx上的。

**Comment by jedibobo** [comment]
感谢嗷
