### ISSUE TITLE
paddle.arange中的问号是何意？

### ISSUE THREAD

**Issue by A-Pai** [PaddlePaddle/Paddle#30369]
详见https://ai.baidu.com/forum/topic/show/981502

**Comment by yaoxuefeng6** [comment]
感谢反馈，我本地没有复现这个问题，
![image](https://user-images.githubusercontent.com/49230821/104402879-42d87400-5592-11eb-801e-2e1c8736c0af.png)
针对您的反馈，会及时通知相关人员
