### ISSUE TITLE
BlurPool论文复现问题

### ISSUE THREAD

**Issue by lwbmowgli** [PaddlePaddle/Paddle#30373]
- 标题：BlurPool论文复现报错
- 版本、环境信息：
    1）PaddlePaddle版本：2.0rc1

    3）GPU：2080 
    4）系统环境：python3.8 torch1.7

- 模型信息
   pytorch中定义如下：

`

        class BlurPool(nn.Module):
            def __init__(self, channels, pad_type='reflect', filt_size=4, stride=2, pad_off=0):
                super(BlurPool, self).__init__()
                self.filt_size = filt_size
                self.pad_off = pad_off
                self.pad_sizes = [int(1.*(filt_size-1)/2), int(np.ceil(1.*(filt_size-1)/2)), int(1.*(filt_size-1)/2), int(np.ceil(1.*(filt_size-1)/2))]
                self.pad_sizes = [pad_size+pad_off for pad_size in self.pad_sizes]
                self.stride = stride
                self.off = int((self.stride-1)/2.)
                self.channels = channels
        
                if(self.filt_size==1):
                    a = np.array([1.,])
                elif(self.filt_size==2):
                    a = np.array([1., 1.])
                elif(self.filt_size==3):
                    a = np.array([1., 2., 1.])
                elif(self.filt_size==4):    
                    a = np.array([1., 3., 3., 1.])
                elif(self.filt_size==5):    
                    a = np.array([1., 4., 6., 4., 1.])
                elif(self.filt_size==6):    
                    a = np.array([1., 5., 10., 10., 5., 1.])
                elif(self.filt_size==7):    
                    a = np.array([1., 6., 15., 20., 15., 6., 1.])
        
                filt = torch.Tensor(a[:,None]*a[None,:])
                filt = filt/torch.sum(filt)
                self.register_buffer('filt', filt[None,None,:,:].repeat((self.channels,1,1,1)))
        
                self.pad = get_pad_layer(pad_type)(self.pad_sizes)
        
            def forward(self, inp):
                if(self.filt_size==1):
                    if(self.pad_off==0):
                        return inp[:,:,::self.stride,::self.stride]    
                    else:
                        return self.pad(inp)[:,:,::self.stride,::self.stride]
                else:
                    return F.conv2d(self.pad(inp), self.filt, stride=self.stride, groups=inp.shape[1])
        
              def get_pad_layer(pad_type):
                    if(pad_type in ['refl','reflect']):
                        PadLayer = nn.ReflectionPad2d
                    elif(pad_type in ['repl','replicate']):
                        PadLayer = nn.ReplicationPad2d
                    elif(pad_type=='zero'):
                        PadLayer = nn.ZeroPad2d
                    else:
                        print('Pad type [%s] not recognized'%pad_type)
                    return PadLayer
`

我的测试脚本如下

`
                        import torch
                        import antialiased_cnns
                        from torchsummary import summary
                  
                  
                  # C = 10 # example feature channel size
                  # blurpool = antialiased_cnns.BlurPool(C, stride=2) # BlurPool layer; use to downsample a feature map
                  # ex_tens = torch.Tensor(1,C,128,128)
                  # print(blurpool(ex_tens).shape)
                  
                  test = torch.nn.Sequential(
                      torch.nn.Conv2d(in_channels=3, out_channels=32, kernel_size=(3, 3)),
                      antialiased_cnns.BlurPool(channels = 32),
                      # paddle.nn.Conv2D(in_channels=3, out_channels=32, kernel_size=(3, 3))
                  )
                  
                  test.cuda()
                  
                  summary(test, (3, 28, 28))
`

- 复现信息：
在paddle2.0rc1中的复现脚本如下：
`
                import paddle.nn.functional as F
                
                class BlurPool(paddle.nn.Layer):
                    def __init__(self, channels, pad_type='reflect', filt_size=4, stride=2, pad_off=0):
                        super(BlurPool, self).__init__()
                        self.filt_size = filt_size
                        self.pad_off = pad_off
                        self.pad_sizes = [int(1.*(filt_size-1)/2), int(np.ceil(1.*(filt_size-1)/2)), int(1.*(filt_size-1)/2), int(np.ceil(1.*(filt_size-1)/2))]
                        self.pad_sizes = [pad_size+pad_off for pad_size in self.pad_sizes]
                        self.stride = stride
                        self.off = int((self.stride-1)/2.)
                        self.channels = channels
                
                        if(self.filt_size==1):
                            a = np.array([1.,])
                        elif(self.filt_size==2):
                            a = np.array([1., 1.])
                        elif(self.filt_size==3):
                            a = np.array([1., 2., 1.])
                        elif(self.filt_size==4):    
                            a = np.array([1., 3., 3., 1.])
                        elif(self.filt_size==5):    
                            a = np.array([1., 4., 6., 4., 1.])
                        elif(self.filt_size==6):    
                            a = np.array([1., 5., 10., 10., 5., 1.])
                        elif(self.filt_size==7):    
                            a = np.array([1., 6., 15., 20., 15., 6., 1.])
                        # a = paddle.Tensor(a)
                        print(a.shape)
                        filt = paddle.Tensor(a[:,None]*a[None,:])
                        filt = filt/paddle.sum(filt)
                        self.register_buffer('filt', filt[None,None,:,:].expand((self.channels,1,1,1)))
                
                        self.pad = get_pad_layer(pad_type)(self.pad_sizes)
                
                    def forward(self, inp):
                        if(self.filt_size==1):
                            if(self.pad_off==0):
                                return inp[:,:,::self.stride,::self.stride]    
                            else:
                                return self.pad(inp)[:,:,::self.stride,::self.stride]
                        else:
                            return F.conv2d(self.pad(inp), self.filt, stride=self.stride, groups=inp.shape[1])
                
                def get_pad_layer(pad_type):
                    if(pad_type in ['refl','reflect']):
                        PadLayer = nn.ReflectionPad2d
                    elif(pad_type in ['repl','replicate']):
                        PadLayer = nn.ReplicationPad2d
                    elif(pad_type=='zero'):
                        PadLayer = nn.ZeroPad2d
                    else:
                        print('Pad type [%s] not recognized'%pad_type)
                    return PadLayer
`

测试脚本如下：

`
          test = paddle.nn.Sequential(
              paddle.nn.Conv2D(in_channels=3, out_channels=32, kernel_size=(3, 3)),
              BlurPool(channels = 32),
              # paddle.nn.Conv2D(in_channels=3, out_channels=32, kernel_size=(3, 3))
          )
          test.cuda()
          paddle.summary(test, (-1, 3, 28, 28))

`
- 问题描述：报错信息如下：
![image](https://user-images.githubusercontent.com/32731935/104404250-30ac0500-5595-11eb-8eaf-9e8beed18c76.png)

torch和paddle2.0中对于Tensor的处理是否存在较大差别，为什么会出现维度问题。我在torch下是没有错误的。请RD大佬帮忙看看，给个解决方法。谢谢！需要注意的是，paddle2.0rc1中tensor未支持repeat这个API，我使用了expand代替了torch中的repeat。

**Comment by yaoxuefeng6** [comment]
跟进中

**Comment by lwbmowgli** [comment]
兄弟，跟进情况怎么样啦？
