### ISSUE TITLE
在jetson Xavier 上安装 paddlepaddle源码进行编译 报错  

### ISSUE THREAD

**Issue by weiluonika** [PaddlePaddle/Paddle#30377]
collect2: error: ld returned 1 exit status
paddle/fluid/pybind/CMakeFiles/paddle_pybind.dir/build.make:1307: recipe for target 'paddle/fluid/pybind/libpaddle_pybind.so' failed
make[2]: *** [paddle/fluid/pybind/libpaddle_pybind.so] Error 1
CMakeFiles/Makefile2:57407: recipe for target 'paddle/fluid/pybind/CMakeFiles/paddle_pybind.dir/all' failed
make[1]: *** [paddle/fluid/pybind/CMakeFiles/paddle_pybind.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2

参考链接：https://www.jianshu.com/p/09a0fd569247

**Comment by yaoxuefeng6** [comment]
请问下有更具体的报错信息吗？ 我们同学反馈2.0-rc1版本是可以稳定编译的，可以试试哈

**Comment by weiluonika** [comment]
> 请问下有更具体的报错信息吗？ 我们同学反馈2.0-rc1版本是可以稳定编译的，可以试试哈

我是在编译python推理库的时候出现的错误 ，c++推理库是可以编译成功的

**Comment by lleesg** [comment]
> 请问下有更具体的报错信息吗？ 我们同学反馈2.0-rc1版本是可以稳定编译的，可以试试哈

基于tx2
rc1上也出现了pybind的错误，详细信息放到了这https://github.com/PaddlePaddle/Paddle/issues/30387#issuecomment-760586432
rc0我成功编译了的

**Comment by vic1006** [comment]
ENV：
TX2、Ubuntu18.04、CUDA10.2、cudnn 8.0.0、jetpack 4.4、python3.6、Paddle-release-2.0-rc0

ERROR：
[ 26%] Building CXX object paddle/fluid/operators/reduce_ops/CMakeFiles/reduce_max_op.dir/reduce_max_op.cc.o
Killed
paddle/fluid/operators/reduce_ops/CMakeFiles/frobenius_norm_op.dir/build.make:86: recipe for target 'paddle/fluid/operators/reduce_ops/CMakeFiles/frobenius_norm_op.dir/frobenius_norm_op.cu.o' failed
make[2]: *** [paddle/fluid/operators/reduce_ops/CMakeFiles/frobenius_norm_op.dir/frobenius_norm_op.cu.o] Error 137
CMakeFiles/Makefile2:79346: recipe for target 'paddle/fluid/operators/reduce_ops/CMakeFiles/frobenius_norm_op.dir/all' failed
make[1]: *** [paddle/fluid/operators/reduce_ops/CMakeFiles/frobenius_norm_op.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 26%] Building CUDA object paddle/fluid/operators/reduce_ops/CMakeFiles/reduce_max_op.dir/reduce_max_op.cu.o
[ 26%] Building CUDA object paddle/fluid/operators/reduce_ops/CMakeFiles/reduce_min_op.dir/reduce_min_op.cu.o
Killed
paddle/fluid/operators/reduce_ops/CMakeFiles/reduce_max_op.dir/build.make:86: recipe for target 'paddle/fluid/operators/reduce_ops/CMakeFiles/reduce_max_op.dir/reduce_max_op.cu.o' failed
make[2]: *** [paddle/fluid/operators/reduce_ops/CMakeFiles/reduce_max_op.dir/reduce_max_op.cu.o] Error 137
make[2]: *** Waiting for unfinished jobs....
[ 26%] Building CUDA object paddle/fluid/operators/reduce_ops/CMakeFiles/reduce_min_op.dir/reduce_min_op.part.cu.o
CMakeFiles/Makefile2:79842: recipe for target 'paddle/fluid/operators/reduce_ops/CMakeFiles/reduce_max_op.dir/all' failed
make[1]: *** [paddle/fluid/operators/reduce_ops/CMakeFiles/reduce_max_op.dir/all] Error 2

**Comment by vic1006** [comment]
> ENV：
> TX2、Ubuntu18.04、CUDA10.2、cudnn 8.0.0、jetpack 4.4、python3.6、Paddle-release-2.0-rc0
> 
> ERROR：
> [ 26%] Building CXX object paddle/fluid/operators/reduce_ops/CMakeFiles/reduce_max_op.dir/reduce_max_op.cc.o
> Killed
> paddle/fluid/operators/reduce_ops/CMakeFiles/frobenius_norm_op.dir/build.make:86: recipe for target 'paddle/fluid/operators/reduce_ops/CMakeFiles/frobenius_norm_op.dir/frobenius_norm_op.cu.o' failed
> make[2]: *** [paddle/fluid/operators/reduce_ops/CMakeFiles/frobenius_norm_op.dir/frobenius_norm_op.cu.o] Error 137
> CMakeFiles/Makefile2:79346: recipe for target 'paddle/fluid/operators/reduce_ops/CMakeFiles/frobenius_norm_op.dir/all' failed
> make[1]: *** [paddle/fluid/operators/reduce_ops/CMakeFiles/frobenius_norm_op.dir/all] Error 2
> make[1]: *** Waiting for unfinished jobs....
> [ 26%] Building CUDA object paddle/fluid/operators/reduce_ops/CMakeFiles/reduce_max_op.dir/reduce_max_op.cu.o
> [ 26%] Building CUDA object paddle/fluid/operators/reduce_ops/CMakeFiles/reduce_min_op.dir/reduce_min_op.cu.o
> Killed
> paddle/fluid/operators/reduce_ops/CMakeFiles/reduce_max_op.dir/build.make:86: recipe for target 'paddle/fluid/operators/reduce_ops/CMakeFiles/reduce_max_op.dir/reduce_max_op.cu.o' failed
> make[2]: *** [paddle/fluid/operators/reduce_ops/CMakeFiles/reduce_max_op.dir/reduce_max_op.cu.o] Error 137
> make[2]: *** Waiting for unfinished jobs....
> [ 26%] Building CUDA object paddle/fluid/operators/reduce_ops/CMakeFiles/reduce_min_op.dir/reduce_min_op.part.cu.o
> CMakeFiles/Makefile2:79842: recipe for target 'paddle/fluid/operators/reduce_ops/CMakeFiles/reduce_max_op.dir/all' failed
> make[1]: *** [paddle/fluid/operators/reduce_ops/CMakeFiles/reduce_max_op.dir/all] Error 2

我的问题解决了，tx2的8G内存不够用，需要增加swap空间（增加5G能编译过）
不过后面又遇到磁盘空间不够的问题，在尝试解决。
