### ISSUE TITLE
PaddleInference开启TensorRT后，PPYOLO预测结果错误

### ISSUE THREAD

**Issue by lleesg** [PaddlePaddle/Paddle#30387]
**ENV：**
TX2、Ubuntu18.04、CUDA10.2、cudnn 8.0.0、jetpack 4.4、python3.6、Paddle-release-2.0-rc0

**Problem description：**
以下PPYOLO采用相同权重。

- 不使用TensorRT时，PPYOLO预测正确：

![output - 152157](https://user-images.githubusercontent.com/16949144/104419652-b9d23480-55b3-11eb-9f51-23a7039b072a.jpg)

- 使用TensorRT时，PPYOLO完全无法正确预测（同配置下YOLO预测正确）：

![output - 141638](https://user-images.githubusercontent.com/16949144/104419699-cd7d9b00-55b3-11eb-8550-05aa1450fe52.jpg)

**TRT相关代码**
    if args.model_dir is not "":
        config = Config(args.model_dir)
    else:
        config = Config(args.model_file, args.params_file)

    config.enable_memory_optim()
    if args.use_gpu:
        config.enable_use_gpu(1000, 0)
    else:
        # If not specific mkldnn, you can set the blas thread.
        # The thread num should not be greater than the number of cores in the CPU.
        config.set_cpu_math_library_num_threads(4)
        config.enable_mkldnn()

    config.enable_tensorrt_engine( 
      1 << 30,
      1,
      3,
      Config.Precision.Float32,
      False,
      False,
    )

是否是我TRT使用代码有问题？谢谢~

**Comment by cryoco** [comment]
您好，您可以更新到2.0-rc1版本试下，我们中间修复了一些导致ppyolo在jetson设备上计算错误的bug

**Comment by lleesg** [comment]
> 您好，您可以更新到2.0-rc1版本试下，我们中间修复了一些导致ppyolo在jetson设备上计算错误的bug

编译rc1过程中，报错，请问有无办法解决（是编译器版本问题么，我的GCC是7.4.0）：
[ 65%] Generating paddle_fluid.dir/conditional_block_op.objdir
[ 65%] Generating paddle_fluid.dir/op_variant.objdir
In file included from /home/dji/Desktop/disk/paddle/paddle/fluid/pybind/pybind.cc:90:0:
/home/dji/Desktop/disk/paddle/paddle/fluid/pybind/tensor_py.h:63:43: error: the type ‘const pybind11::detail::descr’ of constexpr variable ‘pybind11::detail::npy_format_descriptor<paddle::platform::float16>::name’ is not literal
   static constexpr auto name = _("float16");
                                           ^
In file included from /home/dji/Desktop/disk/paddle/build/third_party/pybind/src/extern_pybind/include/pybind11/cast.h:15:0,
                 from /home/dji/Desktop/disk/paddle/build/third_party/pybind/src/extern_pybind/include/pybind11/attr.h:13,
                 from /home/dji/Desktop/disk/paddle/build/third_party/pybind/src/extern_pybind/include/pybind11/pybind11.h:43,
                 from /home/dji/Desktop/disk/paddle/paddle/fluid/framework/python_headers.h:23,
                 from /home/dji/Desktop/disk/paddle/paddle/fluid/operators/py_func_op.h:16,
                 from /home/dji/Desktop/disk/paddle/paddle/fluid/pybind/pybind.cc:58:
/home/dji/Desktop/disk/paddle/build/third_party/pybind/src/extern_pybind/include/pybind11/detail/descr.h:108:7: note: ‘pybind11::detail::descr’ is not literal because:
 class descr {
       ^~~~~
/home/dji/Desktop/disk/paddle/build/third_party/pybind/src/extern_pybind/include/pybind11/detail/descr.h:108:7: note:   ‘pybind11::detail::descr’ is not an aggregate, does not have a trivial default constructor, and has no constexpr constructor that is not a copy or move constructor
In file included from /home/dji/Desktop/disk/paddle/paddle/fluid/pybind/pybind.cc:90:0:
/home/dji/Desktop/disk/paddle/paddle/fluid/pybind/tensor_py.h:63:25: error: in-class initialization of static data member ‘const pybind11::detail::descr pybind11::detail::npy_format_descriptor<paddle::platform::float16>::name’ of non-literal type
   static constexpr auto name = _("float16");
                         ^~~~
/home/dji/Desktop/disk/paddle/paddle/fluid/pybind/tensor_py.h:63:43: error: call to non-constexpr function ‘pybind11::detail::descr pybind11::detail::_(const char*)’
   static constexpr auto name = _("float16");
                                           ^
/home/dji/Desktop/disk/paddle/paddle/fluid/pybind/tensor_py.h:80:44: error: the type ‘const pybind11::detail::descr’ of constexpr variable ‘pybind11::detail::npy_format_descriptor<paddle::platform::bfloat16>::name’ is not literal
   static constexpr auto name = _("bfloat16");
                                            ^
/home/dji/Desktop/disk/paddle/paddle/fluid/pybind/tensor_py.h:80:25: error: in-class initialization of static data member ‘const pybind11::detail::descr pybind11::detail::npy_format_descriptor<paddle::platform::bfloat16>::name’ of non-literal type
   static constexpr auto name = _("bfloat16");
                         ^~~~
/home/dji/Desktop/disk/paddle/paddle/fluid/pybind/tensor_py.h:80:44: error: call to non-constexpr function ‘pybind11::detail::descr pybind11::detail::_(const char*)’
   static constexpr auto name = _("bfloat16");
                                            ^
In file included from /home/dji/Desktop/disk/paddle/paddle/fluid/pybind/pybind.cc:90:0:
/home/dji/Desktop/disk/paddle/paddle/fluid/pybind/tensor_py.h:99:46: error: the type ‘const pybind11::detail::descr’ of constexpr variable ‘pybind11::detail::npy_format_descriptor<paddle::platform::complex64>::name’ is not literal
   static constexpr auto name = _("complext64");
                                              ^
/home/dji/Desktop/disk/paddle/paddle/fluid/pybind/tensor_py.h:99:25: error: in-class initialization of static data member ‘const pybind11::detail::descr pybind11::detail::npy_format_descriptor<paddle::platform::complex64>::name’ of non-literal type
   static constexpr auto name = _("complext64");
                         ^~~~
/home/dji/Desktop/disk/paddle/paddle/fluid/pybind/tensor_py.h:99:46: error: call to non-constexpr function ‘pybind11::detail::descr pybind11::detail::_(const char*)’
   static constexpr auto name = _("complext64");
                                              ^
/home/dji/Desktop/disk/paddle/paddle/fluid/pybind/tensor_py.h:118:47: error: the type ‘const pybind11::detail::descr’ of constexpr variable ‘pybind11::detail::npy_format_descriptor<paddle::platform::complex128>::name’ is not literal
   static constexpr auto name = _("complext128");
                                               ^
/home/dji/Desktop/disk/paddle/paddle/fluid/pybind/tensor_py.h:118:25: error: in-class initialization of static data member ‘const pybind11::detail::descr pybind11::detail::npy_format_descriptor<paddle::platform::complex128>::name’ of non-literal type
   static constexpr auto name = _("complext128");
                         ^~~~
/home/dji/Desktop/disk/paddle/paddle/fluid/pybind/tensor_py.h:118:47: error: call to non-constexpr function ‘pybind11::detail::descr pybind11::detail::_(const char*)’
   static constexpr auto name = _("complext128");
                                               ^
[ 65%] Generating paddle_fluid.dir/conditional_block_op_helper.objdir

**Comment by lleesg** [comment]
> > 您好，您可以更新到2.0-rc1版本试下，我们中间修复了一些导致ppyolo在jetson设备上计算错误的bug
> 
> 编译rc1过程中，报错，请问有无办法解决（是编译器版本问题么，我的GCC是7.4.0）：
> [ 65%] Generating paddle_fluid.dir/conditional_block_op.objdir
> [ 65%] Generating paddle_fluid.dir/op_variant.objdir
> In file included from /home/dji/Desktop/disk/paddle/paddle/fluid/pybind/pybind.cc:90:0:
> /home/dji/Desktop/disk/paddle/paddle/fluid/pybind/tensor_py.h:63:43: error: the type ‘const pybind11::detail::descr’ of constexpr variable ‘pybind11::detail::npy_format_descriptorpaddle::platform::float16::name’ is not literal
> static constexpr auto name = _("float16");
> ^
> In file included from /home/dji/Desktop/disk/paddle/build/third_party/pybind/src/extern_pybind/include/pybind11/cast.h:15:0,
> from /home/dji/Desktop/disk/paddle/build/third_party/pybind/src/extern_pybind/include/pybind11/attr.h:13,
> from /home/dji/Desktop/disk/paddle/build/third_party/pybind/src/extern_pybind/include/pybind11/pybind11.h:43,
> from /home/dji/Desktop/disk/paddle/paddle/fluid/framework/python_headers.h:23,
> from /home/dji/Desktop/disk/paddle/paddle/fluid/operators/py_func_op.h:16,
> from /home/dji/Desktop/disk/paddle/paddle/fluid/pybind/pybind.cc:58:
> /home/dji/Desktop/disk/paddle/build/third_party/pybind/src/extern_pybind/include/pybind11/detail/descr.h:108:7: note: ‘pybind11::detail::descr’ is not literal because:
> class descr {
> ^~~~~
> /home/dji/Desktop/disk/paddle/build/third_party/pybind/src/extern_pybind/include/pybind11/detail/descr.h:108:7: note: ‘pybind11::detail::descr’ is not an aggregate, does not have a trivial default constructor, and has no constexpr constructor that is not a copy or move constructor
> In file included from /home/dji/Desktop/disk/paddle/paddle/fluid/pybind/pybind.cc:90:0:
> /home/dji/Desktop/disk/paddle/paddle/fluid/pybind/tensor_py.h:63:25: error: in-class initialization of static data member ‘const pybind11::detail::descr pybind11::detail::npy_format_descriptorpaddle::platform::float16::name’ of non-literal type
> static constexpr auto name = _("float16"); ^~~~ /home/dji/Desktop/disk/paddle/paddle/fluid/pybind/tensor_py.h:63:43: error: call to non-constexpr function ‘pybind11::detail::descr pybind11::detail::_(const char*)’
> static constexpr auto name = _("float16");
> ^
> /home/dji/Desktop/disk/paddle/paddle/fluid/pybind/tensor_py.h:80:44: error: the type ‘const pybind11::detail::descr’ of constexpr variable ‘pybind11::detail::npy_format_descriptorpaddle::platform::bfloat16::name’ is not literal
> static constexpr auto name = _("bfloat16");
> ^
> /home/dji/Desktop/disk/paddle/paddle/fluid/pybind/tensor_py.h:80:25: error: in-class initialization of static data member ‘const pybind11::detail::descr pybind11::detail::npy_format_descriptorpaddle::platform::bfloat16::name’ of non-literal type
> static constexpr auto name = _("bfloat16"); ^~~~ /home/dji/Desktop/disk/paddle/paddle/fluid/pybind/tensor_py.h:80:44: error: call to non-constexpr function ‘pybind11::detail::descr pybind11::detail::_(const char*)’
> static constexpr auto name = _("bfloat16");
> ^
> In file included from /home/dji/Desktop/disk/paddle/paddle/fluid/pybind/pybind.cc:90:0:
> /home/dji/Desktop/disk/paddle/paddle/fluid/pybind/tensor_py.h:99:46: error: the type ‘const pybind11::detail::descr’ of constexpr variable ‘pybind11::detail::npy_format_descriptorpaddle::platform::complex64::name’ is not literal
> static constexpr auto name = _("complext64");
> ^
> /home/dji/Desktop/disk/paddle/paddle/fluid/pybind/tensor_py.h:99:25: error: in-class initialization of static data member ‘const pybind11::detail::descr pybind11::detail::npy_format_descriptorpaddle::platform::complex64::name’ of non-literal type
> static constexpr auto name = _("complext64"); ^~~~ /home/dji/Desktop/disk/paddle/paddle/fluid/pybind/tensor_py.h:99:46: error: call to non-constexpr function ‘pybind11::detail::descr pybind11::detail::_(const char*)’
> static constexpr auto name = _("complext64");
> ^
> /home/dji/Desktop/disk/paddle/paddle/fluid/pybind/tensor_py.h:118:47: error: the type ‘const pybind11::detail::descr’ of constexpr variable ‘pybind11::detail::npy_format_descriptorpaddle::platform::complex128::name’ is not literal
> static constexpr auto name = _("complext128");
> ^
> /home/dji/Desktop/disk/paddle/paddle/fluid/pybind/tensor_py.h:118:25: error: in-class initialization of static data member ‘const pybind11::detail::descr pybind11::detail::npy_format_descriptorpaddle::platform::complex128::name’ of non-literal type
> static constexpr auto name = _("complext128"); ^~~~ /home/dji/Desktop/disk/paddle/paddle/fluid/pybind/tensor_py.h:118:47: error: call to non-constexpr function ‘pybind11::detail::descr pybind11::detail::_(const char*)’
> static constexpr auto name = _("complext128");
> ^
> [ 65%] Generating paddle_fluid.dir/conditional_block_op_helper.objdir

在paddle 2.0.0正式版也有同样的问题。
解决办法：删除third_party中的pybind文件夹


——但是“使用TensorRT时，PPYOLO完全无法正确预测”还是没解决。。

**Comment by tianhechao** [comment]
> X2、Ubuntu18.04、CUDA10.2、cudnn 8.0.0、jetpack 4.4、python3.6、Paddle-release-2.0-rc0

请问你的问题是否解决？

**Comment by lleesg** [comment]
> > X2、Ubuntu18.04、CUDA10.2、cudnn 8.0.0、jetpack 4.4、python3.6、Paddle-release-2.0-rc0
> 
> 请问你的问题是否解决？

TRT的问题还木有解决

**Comment by lleesg** [comment]
顶一下，为什么PPYOLO开启TensorRT后预测结果就错误呢？

看TRT官方文档：https://paddle-inference.readthedocs.io/en/latest/optimize/paddle_trt.html中的支持表格，意思是TRT不支持PPYOLO？

**Comment by lleesg** [comment]
把jetson更新到paddle inference 2.0.2，paddle detection 2.0，利用deploy/python/infer.py进行检测，发现只要开了GPU就检测不到结果（用CPU正常），用config.switch_ir_optim(False)也不行。

请各位老师看看呢？

**Comment by liwang54321** [comment]
我用jetson nx 使用gpu就会报错，请问一下知道这个是为什么吗
```bash
lw@lw:~/Workspace/PaddleDetection/deploy/cpp$ ./app-trt --model_dir=/home/lw/Workspace/project_pd_rc/inference_model_v2 --image_file=./ZNJT_SH_0022019042414154177.jpg  --use_gpu
WARNING: Logging before InitGoogleLogging() is written to STDERR
I0526 23:36:08.786552 28852 analysis_config.cc:424] use_dlnne_:0
I0526 23:36:08.786695 28852 analysis_config.cc:424] use_dlnne_:0
I0526 23:36:08.786783 28852 analysis_config.cc:424] use_dlnne_:0
I0526 23:36:08.786829 28852 analysis_config.cc:424] use_dlnne_:0
total images = 1, batch_size = 1, total steps = 1
terminate called after throwing an instance of 'paddle::platform::EnforceNotMet'
  what():  

--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
0   void paddle_infer::Tensor::CopyFromCpu<float>(float const*)
1   paddle::platform::DeviceContextPool::Get(paddle::platform::Place const&)
2   std::__future_base::_Deferred_state<std::thread::_Invoker<std::tuple<paddle::platform::EmplaceDeviceContext<paddle::platform::CUDADeviceContext, paddle::platform::CUDAPlace>(std::map<paddle::platform::Place, std::shared_future<std::unique_ptr<paddle::platform::DeviceContext, std::default_delete<paddle::platform::DeviceContext> > >, std::less<paddle::platform::Place>, std::allocator<std::pair<paddle::platform::Place const, std::shared_future<std::unique_ptr<paddle::platform::DeviceContext, std::default_delete<paddle::platform::DeviceContext> > > > > >*, paddle::platform::Place)::{lambda()#1}> >, std::unique_ptr<paddle::platform::DeviceContext, std::default_delete<paddle::platform::DeviceContext> > >::_M_complete_async()
3   std::_Function_handler<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> (), std::__future_base::_Task_setter<std::unique_ptr<std::__future_base::_Result<std::unique_ptr<paddle::platform::DeviceContext, std::default_delete<paddle::platform::DeviceContext> > >, std::__future_base::_Result_base::_Deleter>, std::thread::_Invoker<std::tuple<paddle::platform::EmplaceDeviceContext<paddle::platform::CUDADeviceContext, paddle::platform::CUDAPlace>(std::map<paddle::platform::Place, std::shared_future<std::unique_ptr<paddle::platform::DeviceContext, std::default_delete<paddle::platform::DeviceContext> > >, std::less<paddle::platform::Place>, std::allocator<std::pair<paddle::platform::Place const, std::shared_future<std::unique_ptr<paddle::platform::DeviceContext, std::default_delete<paddle::platform::DeviceContext> > > > > >*, paddle::platform::Place)::{lambda()#1}> >, std::unique_ptr<paddle::platform::DeviceContext, std::default_delete<paddle::platform::DeviceContext> > > >::_M_invoke(std::_Any_data const&)
4   paddle::platform::CUDADeviceContext::CUDADeviceContext(paddle::platform::CUDAPlace)
5   paddle::platform::CUDAContext::CUDAContext(paddle::platform::CUDAPlace const&, paddle::platform::stream::Priority const&)
6   paddle::platform::CUDAContext::InitCuSolverContext()
7   paddle::platform::EnforceNotMet::EnforceNotMet(paddle::platform::ErrorSummary const&, char const*, int)
8   paddle::platform::GetCurrentTraceBackString[abi:cxx11]()

----------------------
Error Message Summary:
----------------------
ExternalError:  Cublas error, `CUSOLVER_STATUS_INTERNAL_ERROR`. An internal cuSolver operation failed. This error is usually caused by a cudaMemcpyAsync() failure.  (at /home/lw/Workspace/Paddle/paddle/fluid/platform/device_context.h:381)
```

**Comment by lleesg** [comment]
更新至2.1，问题解决
