### ISSUE TITLE
2.0版本的LodTensor问题

### ISSUE THREAD

**Issue by Maybewuss** [PaddlePaddle/Paddle#30396]
查看文档后发现，在升级到2.0版本后弱化了LodTensor的概念，并且在动态图模式下貌似不支持LodTensor类型的输入。
LodTensor应该算是1.x版本中paddle的一大亮点，在2.0中被弱化之后paddle仍然能保持对变长数据处理的高效性吗？

**Comment by yaoxuefeng6** [comment]
取决于具体的任务，在常见的任务类型上，使用padding / bucketing 策略还是能达到不错的性能的。在静态图模式下，因为是兼容性升级，之前的LodTensor相关的都可以使用

**Comment by starsblinking** [comment]
我觉得处理变长输入是基本功能，而不是什么亮点吧。好奇为啥你们在讨论“高效性”、“性能”，是因为有低效的可替代api？除了用lod_level=1的data层能处理离散变长输入（比如query的切词，实现不知道某样本该特征会切成几个部分），还有什么可用的api呢？

你们说的该不会是。。。强行用一个固定宽度的input（比如shape=[-1,10]的data），如果变长输入长度小（比如切词结果只有3个部分），剩下的（10-3=7）部分就用0来填充的方案吧。。。恐怖
