### ISSUE TITLE
静态图和动态图如何选择

### ISSUE THREAD

**Issue by qiuming-93** [PaddlePaddle/Paddle#30406]
为使您的问题得到快速解决，在建立Issues前，请您先通过如下方式搜索是否有相似问题:【搜索issue关键字】【使用labels筛选】【官方文档】

如何选择使用静态图还是动态图？
我在别的博客上看到
Q:作为新手,我应该如何选择?使用静态图好还是动态图好?
A:目前飞桨官方在主推动态图,即命令式编程。如果您是新手,建议从动态图开始学习;如果您有一定的基础,可以尝试静态图。因为最后训练出来的模型肯定是需要部署的,目前使用用命令式编程(动态图)得到的模型文件不能很方便的部署,因此对部署有需求的话,建议使用静态图。

我想知道动态图和静态图该如何选择，二者在预测性能及精度上是否有区别，部署的话我会使用flask搭建服务来部署，可能基于CPU或GPU上进行预测

**Comment by yaoxuefeng6** [comment]
可以优先使用动态图进行前期调研，理论上动静应该是一致的，后续有性能要求的时候可以在静态图上进行部署

**Comment by qiuming-93** [comment]
好的，我有看到过有issue讨论动态图转静态图的，所以是先使用动态图进行训练，训练好之后再转静态图即可是吗？这个转换之后不需要重新训练吧？

**Comment by qiuming-93** [comment]
动态图和静态图在训练时的性能有差距吗？差距大吗

**Comment by yaoxuefeng6** [comment]
可以看看这些文档有帮助吗：https://www.paddlepaddle.org.cn/documentation/docs/zh/2.0-rc1/guides/04_dygraph_to_static/index_cn.html#id1

**Comment by yaoxuefeng6** [comment]
一开始还是推荐使用动态图哈，功能也相对比较完善的

**Comment by qiuming-93** [comment]
查了些资料，也看了些静态库和动态库的代码对比，除了python原生的控制逻辑之外，没看出太多明显区别（实现上），有没相对较全的文档介绍这二者的

**Comment by skywalk163** [comment]
动态图和静态图的区别，可以理解为解释执行和编译执行的区别，动态图就是原生python编程习惯，而静态图其实是加了编译层，理论上编译的要比解释的快，但实际上有些任务速度区别不大，因为原生python也可以优化的很快，况且大部分算力和时间是消耗在gpu上了。
飞桨完全可以动态图编程和训练，训练结束后直接就可以自由的选择存储动态图模型还是静态图模型。存储为动态图模型方便以后的继续训练和优化，存储为静态图模型就是为了上项目和落地。

简单来说，工业应用之前，研发/竞赛/训练，最优选择都是动态图。工业落地优选静态图（落地前的工作还是动态图为主）。
