### ISSUE TITLE
1.3版本不支持v2了，如果要使用v2，请使用1.2版本。

### ISSUE THREAD

**Issue by JPyer** [PaddlePaddle/Paddle#30423]
1.3版本不支持v2了，如果要使用v2，请使用1.2版本。

_Originally posted by @luotao1 in https://github.com/PaddlePaddle/Paddle/issues/3022#issuecomment-477909402_
But I install version1.2 is not use。

**Comment by baiyfbupt** [comment]
paddle v1,v2版本已经不再维护了，建议使用2.0稳定版
https://www.paddlepaddle.org.cn/

**Comment by JPyer** [comment]
Okay, thank you!
