### ISSUE TITLE
使用python编写并进行训练所得的模型保存之后能否使用C++加载模型进行预测

### ISSUE THREAD

**Issue by qiuming-93** [PaddlePaddle/Paddle#30444]
使用python编写并进行训练所得的模型保存之后能否使用C++加载模型进行预测？
二者能否无缝兼容，能否正常运行在CPU/GPU环境上
paddlepaddle-gpu: 1.8.5

**Comment by baiyfbupt** [comment]
可以的，C++预测请参考paddle-inference使用文档: https://paddle-inference.readthedocs.io/en/latest/

**Comment by qiuming-93** [comment]
好的
