### ISSUE TITLE
高层API 数据集Imikolov报错

### ISSUE THREAD

**Issue by skywalk163** [PaddlePaddle/Paddle#30456]
为使您的问题得到快速解决，在建立Issues前，请您先通过如下方式搜索是否有相似问题:【搜索issue关键字】【使用labels筛选】【官方文档】

如果您没有查询到相似问题，为快速解决您的提问，建立issue时请提供如下细节信息：
- 标题：简洁、精准概括您的问题
- 版本、环境信息：
    1）PaddlePaddle版本：AIStudio 飞桨2.0.0rc1 

高层API class paddle.text.datasets.Imikolov，我把例子里的数据类型改为data_type='NGRAM' ，报错
import paddle
from paddle.text.datasets import Imikolov

class SimpleNet(paddle.nn.Layer):
    def __init__(self):
        super(SimpleNet, self).__init__()

    def forward(self, src, trg):
        return paddle.sum(src), paddle.sum(trg)

imikolov = Imikolov(mode='train', data_type='NGRAM') #, window_size=2

for i in range(10):
    src, trg = imikolov[i]
    src = paddle.to_tensor(src)
    trg = paddle.to_tensor(trg)

    model = SimpleNet()
    src, trg = model(src, trg)
    print(src.numpy().shape, trg.numpy().shape)

报错信息为：
---------------------------------------------------------------------------AssertionError                            Traceback (most recent call last)<ipython-input-13-7f07526c1200> in <module>
     10 
     11 
---> 12 imikolov = Imikolov(mode='train', data_type='NGRAM') #, window_size=2
     13 
     14 for i in range(10):
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/text/datasets/imikolov.py in __init__(self, data_file, data_type, window_size, mode, min_word_freq, download)
    103 
    104         # read dataset into memory
--> 105         self._load_anno()
    106 
    107     def word_count(self, f, word_freq=None):
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/text/datasets/imikolov.py in _load_anno(self)
    148             for l in f:
    149                 if self.data_type == 'NGRAM':
--> 150                     assert self.window_size > -1, 'Invalid gram length'
    151                     l = ['<s>'] + l.strip().split() + ['<e>']
    152                     if len(l) >= self.window_size:
AssertionError: Invalid gram length

直接用这句：
train_dataset_Imikolov = paddle.text.datasets.Imikolov(data_type = 'NGRAM')
或者
train_dataset_Imikolov = paddle.text.datasets.Imikolov()
也是报同样的错误

**Comment by baiyfbupt** [comment]
https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/text/datasets/imikolov.py#L79
window size 默认值 为-1， Imikolov(mode='train', data_type='NGRAM') 这里改成Imikolov(mode='train', window_size =2， data_type='NGRAM')试试吧

**Comment by skywalk163** [comment]
谢谢，加上window_size就ok了
