### ISSUE TITLE
MacOS 15 本机源码编译Paddle 出现 Python.h file not found 

### ISSUE THREAD

**Issue by JiabinYang** [PaddlePaddle/Paddle#30497]
MacOS 15 使用Python3 作为Python 解释器参与编译 Paddle develop 分支代码出现以下错误：
pybind11: Python.h file not found 

解决方案：
export C_INCLUDE_PATH=[Python.h 所在目录]
可以使用命令 find / -name Python.h 找到需要使用的python对应的Python.h的位置

**Comment by iclementine** [comment]
cmake 选项中加入 -DPYTHON_INCLUDE_DIR=python.h 的地址 也可以
