### ISSUE TITLE
老版本paddle怎么加载新版本模型weights 

### ISSUE THREAD

**Issue by miraclebiu** [PaddlePaddle/Paddle#30495]
怎么把pdparams文件转换成，一堆散的文件，旧的代码无法load进新pdparams，load接口已按照ppcls修改，报错AssertionError: Variable [ reduce_mean_0.tmp_0 ] Not found, Please make sure run startup program，但是在代码中，load之前已经exe.run(startup_prog)

**Comment by iclementine** [comment]
ppcls 是什么？
没有更多的上下文信息。
动态图还是静态图，怎么保存参数的，新版本的版本号是什么，旧版本的版本号是什么，新旧的代码的等价性能否保证。

P.S. 这个问题的终极大招是转换模型。

**Comment by miraclebiu** [comment]
> ppcls 是什么？
> 没有更多的上下文信息。
> 动态图还是静态图，怎么保存参数的，新版本的版本号是什么，旧版本的版本号是什么，新旧的代码的等价性能否保证。
> 
> P.S. 这个问题的终极大招是转换模型。

是的，旧的代码是静态图，1.7的，paddleClas里面下载的模型以前是一个文件夹，里面是散的文件，现在是新的pdparams，我们如何把新的转换成旧的，方便之前的代码load？

**Comment by iclementine** [comment]
可以用新版的 paddle 和新版的模型代码,先把模型初始化出来, 然后加载保存的 pdparams 参数, 然后用旧的格式保存一份. 参考

https://www.paddlepaddle.org.cn/documentation/docs/zh/api_cn/io_cn/save_params_cn.html#save-params
