### ISSUE TITLE
Paddle 运算精度不高？？？

### ISSUE THREAD

**Issue by huochf** [PaddlePaddle/Paddle#30502]
我在使用InstanceNorm时，结果出现了极大的偏差。

输入一个值全部为-54.67994308的Variable，按理来说，经过InstanceNorm后结果应该对于对于的偏置（由于归一化减去均值为0）
可是结果却出现了极大的偏差，输出为0.93586272 而不是0.03429652（正确输出，即对于的偏置）

然后我仔细debug了一下， 发现paddle计算精度不高

```
print(L.reduce_max(test_data[0][0]) ) # -54.67994308
print(L.reduce_min(test_data[0][0]) ) # -54.67994308
print(L.reduce_sum(test_data[0][0] / (256 * 256))) # -54.67974091
print(L.reduce_sum(test_data[0][0]) / (256 * 256)) # -54.67974091
```

按理来说，结果归一化后，减去均值应该对于0，可以由于均值的计算存在偏差，所以归一化（减去均值再除以偏差）之后为0.99999

唉！！！不知道我理解的对不对。

在线等回复！

**Comment by huochf** [comment]
若上面的解释的不清楚，可以运行一下代码，

```
`import numpy as np 
import paddle.fluid.dygraph as dg
import paddle.fluid.layers as L

norm = dg.InstanceNorm(4)
test_data = dg.to_variable(np.ones((1, 4, 256, 256)).astype("float32"))
output_1 = norm(test_data - 54.67994308 )
print(output_1) # 0.85590988

norm = dg.InstanceNorm(4)
test_data = dg.to_variable(np.ones((1, 4, 256, 256)).astype("float32"))
output_2 = norm(test_data - 54.6799 )
print(output_2) # 0.85757309 

norm = dg.InstanceNorm(4)
test_data = dg.to_variable(np.ones((1, 4, 256, 256)).astype("float32"))
output_3 = norm(test_data - 54.6 )
print(output_3) # -0.78827506

norm = dg.InstanceNorm(4)
test_data = dg.to_variable(np.ones((1, 4, 256, 256)).astype("float32"))
output_4 = norm(test_data - 54. )
print(output_4) # 0. `
```

这里给出了我在aistudio的notebook环境下的输出结果，

0.85590988 [1, 4, 256, 256]
0.85757309 [1, 4, 256, 256]
-0.78827506 [1, 4, 256, 256]
0. [1, 4, 256, 256]

**Comment by huochf** [comment]
我猜测可能是计算均值的时候，出现了偏差。希望能够得到回复！

**Comment by huangjun12** [comment]
> 若上面的解释的不清楚，可以运行一下代码，
> 
> ```
> `import numpy as np 
> import paddle.fluid.dygraph as dg
> import paddle.fluid.layers as L
> 
> norm = dg.InstanceNorm(4)
> test_data = dg.to_variable(np.ones((1, 4, 256, 256)).astype("float32"))
> output_1 = norm(test_data - 54.67994308 )
> print(output_1) # 0.85590988
> 
> norm = dg.InstanceNorm(4)
> test_data = dg.to_variable(np.ones((1, 4, 256, 256)).astype("float32"))
> output_2 = norm(test_data - 54.6799 )
> print(output_2) # 0.85757309 
> 
> norm = dg.InstanceNorm(4)
> test_data = dg.to_variable(np.ones((1, 4, 256, 256)).astype("float32"))
> output_3 = norm(test_data - 54.6 )
> print(output_3) # -0.78827506
> 
> norm = dg.InstanceNorm(4)
> test_data = dg.to_variable(np.ones((1, 4, 256, 256)).astype("float32"))
> output_4 = norm(test_data - 54. )
> print(output_4) # 0. `
> ```
> 
> 这里给出了我在aistudio的notebook环境下的输出结果，
> 
> 0.85590988 [1, 4, 256, 256]
> 0.85757309 [1, 4, 256, 256]
> -0.78827506 [1, 4, 256, 256]
> 0. [1, 4, 256, 256]

抱歉还是没太明白问题。。。

InstanceNorm2D可以参考[文档说明](https://www.paddlepaddle.org.cn/documentation/docs/zh/2.0-rc1/api/paddle/nn/layer/norm/InstanceNorm2D_cn.html#instancenorm2d)

写了段代码测试，希望可以帮助理解: 

```
import paddle
import numpy as np
norm = paddle.nn.InstanceNorm2D(4)
test_data = paddle.to_tensor(np.ones((1, 4, 256, 256)).astype("float32"))
output_1 = norm(test_data - 54.67994308 )
print(output_1[0,0,0,0])
```

输出日志为:

```
Tensor(shape=[1], dtype=float32, place=CUDAPlace(0), stop_gradient=False, [0.])
```

以上代码输出为0。

**Comment by huochf** [comment]
在Aistudio notebook环境中，运行
```
import paddle
import numpy as np
norm = paddle.nn.InstanceNorm2D(4)
test_data = paddle.to_tensor(np.ones((1, 4, 256, 256)).astype("float32"))
output_1 = norm(test_data - 54.67994308 )
print(output_1[0,0,0,0])
```
得到
```
Tensor(shape=[1], dtype=float32, place=CPUPlace, stop_gradient=False,
       [0.85590988])
```
我再看看吧，好像是我这里的AiStudio的环境有问题。

**Comment by huochf** [comment]
好的，问题解决了，
在CPU环境中运行您所给代码，输出为
```
Tensor(shape=[1], dtype=float32, place=CPUPlace, stop_gradient=False,
       [0.85590988])
```

我又更换到GPU环境中，输出和你相符。

**Comment by huochf** [comment]
谢谢您！给研发人员加鸡腿！！！
