### ISSUE TITLE
如何同时加载多个预训练模型？

### ISSUE THREAD

**Issue by hailong23-jin** [PaddlePaddle/Paddle#30501]
假设我现在有三个预训练模型A，B，C。然后有三个独立的文件分别对应这三个模型预训练的参数。现在我想在自己的神经网络中同时使用这三个预训练模型，要怎么样进行加载呢？
伪代码：
```
modelA = PretainModelA()
modelB = PretainModelB()
modelC = PretainModelC()

paddle.fluid.io.load_vars(exe, model_path_A, main_progaram) 
```
上面的伪代码，是只加载了模型A么？如果要分别加载A、B、C三个模型该怎么处理呢？

**Comment by iclementine** [comment]
调用三次?
paddle.fluid.io.load_vars(exe, model_path_A, main_progaram) 
paddle.fluid.io.load_vars(exe, model_path_B, main_progaram) 
paddle.fluid.io.load_vars(exe, model_path_C, main_progaram)
