### ISSUE TITLE
实现简单实例报错

### ISSUE THREAD

**Issue by Hsoms** [PaddlePaddle/Paddle#30504]
程序：
"""
Created on Sat Jan 16 20:48:21 2021

@author: 杨
"""
import paddle
import paddle.fluid as fluid
import numpy as np

paddle.enable_static()

#定义数据
train_data=np.array([[1.0],[2.0],[3.0],[4.0]]).astype("float32")
y_true=np.array([[2.0],[4.0],[6.0],[8.0]]).astype("float32")

#定义神经网络
x=fluid.layers.data(name="x",shape=[1],dtype="float32")
y=fluid.layers.data(name="y",shape=[1],dtype="float32")
y_predict=fluid.layers.fc(input=x,size=1,act=None)

#定义损失函数
cost=fluid.layers.cross_entropy(input=y_predict,label=y)  #交叉熵损失函数
avg_cost=fluid.layers.mean(cost)

#定义优化方法

sgd_optimizer=fluid.optimizer.SGD(learning_rate=0.01)
sgd_optimizer.minimize(avg_cost)

#在cpu内执行训练
cpu=fluid.CPUPlace()
#创建框架执行器
exe=fluid.Executor(cpu)

#参数初始化
exe.run(fluid.default_startup_program())

#开始训练
outs=exe.run(feed={"x":train_data,"y":y_true
                   },fetch_list=[y_predict.name,avg_cost.name])

报错信息：
InvalidArgumentError: Tensor holds the wrong type, it holds float, but desires to be int64_t.
      [Hint: Expected valid == true, but received valid:0 != true:1.] (at D:\2.0.0rc1\paddle\paddle/fluid/framework/tensor_impl.h:33)
      [Hint: If you need C++ stacktraces for debugging, please set `FLAGS_call_stack_level=2`.]
      [operator < cross_entropy2 > error]

**Comment by huangjun12** [comment]
y和y_true的数据类型不对，把float32改成int64看看

**Comment by Hsoms** [comment]
> y和y_true的数据类型不对，把float32改成int64看看

报相同的错误

**Comment by huangjun12** [comment]
以下程序是可以跑的

```
import paddle
import paddle.fluid as fluid
import numpy as np

paddle.enable_static()

#定义数据
train_data=np.array([[1.0],[2.0],[3.0],[4.0]]).astype("float32")
y_true=np.array([[0],[0.1],[0.2],[0.4]]).astype("int64")

#定义神经网络
x=fluid.layers.data(name="x",shape=[1],dtype="float32")
y=fluid.layers.data(name="y",shape=[1],dtype="int64")
y_predict=fluid.layers.fc(input=x,size=1,act=None)

#定义损失函数
cost=fluid.layers.cross_entropy(input=y_predict,label=y) #交叉熵损失函数
avg_cost=fluid.layers.mean(cost)

#定义优化方法

sgd_optimizer=fluid.optimizer.SGD(learning_rate=0.01)
sgd_optimizer.minimize(avg_cost)

#在cpu内执行训练
cpu=fluid.CPUPlace()
#创建框架执行器
exe=fluid.Executor(cpu)

#参数初始化
exe.run(fluid.default_startup_program())

#开始训练
outs=exe.run(feed={"x":train_data,"y":y_true
},fetch_list=[y_predict.name,avg_cost.name])

print(outs[0])
```

输出日志:
```
[[-1.3605814]
 [-2.7211628]
 [-4.081744 ]
 [-5.4423256]]
```

您可以参考一下看看
