### ISSUE TITLE
动态图中有没有paddle.fluid.layers.sequence_pad的替代函数呀

### ISSUE THREAD

**Issue by hailong23-jin** [PaddlePaddle/Paddle#30511]
今天在写代码的时候遇到了这两个函数sequence_pad和sequence_unpad，但是这两个函数在动态图中不能使用，请问在动态图中有没有类似的实现呀

**Comment by Aurelius84** [comment]
动态图下可以在数据预处理时，对变长的数据进行自定义padding处理。

比如：继承paddle.io.Dataset，在`__getitem__`方法中自定义数据样本的padding逻辑。

可以参考如下教程文档：
https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/guides/02_paddle2.0_develop/03_data_preprocessing_cn.html#id3
