### ISSUE TITLE
请教两个问题

### ISSUE THREAD

**Issue by starsblinking** [PaddlePaddle/Paddle#30521]
1. 在 test_static_save_load.py 中出现了多处 "if isinstance(var, framework.Parameter) or var.persistable:" ， 请问 这里 "isinstance(var, framework.Parameter)" 的作用是什么呢? 直接 “if var.persistable:" 可以吗？什么情况下or的前面为真后面为假呢？
https://github.com/PaddlePaddle/Paddle/blob/18ecd433f558b16f069e6fb3a2028fda34716eb9/python/paddle/fluid/tests/unittests/test_static_save_load.py#L309 

2. 当前develop分支里是不是 paddle.fluid.load=paddle.fluid.io.load=paddle.static.load, paddle.fluid.save=paddle.fluid.io.save=paddle.static.save? 均用于静态图?

**Comment by zhwesky2010** [comment]
@starsblinking 
1.参数都是persistable的，可能有非参数的普通variable也被是persistable，但是可以将参数设置为非persistable的  
2.对的，都是别名的关系，static只能在静态图下用

**Comment by starsblinking** [comment]
总觉得，既然保存的目标是persistable的var，那只保留后一个判断就足够了，前面的是多余的
