### ISSUE TITLE
len(ptr) = 1 的时候 panic: reflect: slice index out of range

### ISSUE THREAD

**Issue by vic-93** [PaddlePaddle/Paddle#30575]
golang 1.4.12
pandle 1.8.5

当我预测单条数据，返回接口只有一个数值时，这个地方会panic，改成 value.Index(0).Kind() 可以正常运行

![image](https://user-images.githubusercontent.com/13634356/105020085-d2de5800-5a81-11eb-80c3-4a76160fe2b4.png)

**Comment by Shixiaowei02** [comment]
你好，目前`go` 语言还处于beta阶段，请优先使用C++和python接口，我们会在2.1版本做go API的升级，谢谢
