### ISSUE TITLE
InvalidArgumentError: Input(X) Tensor of SequencePoolOp does not contain LoD information.

### ISSUE THREAD

**Issue by vic-93** [PaddlePaddle/Paddle#30571]
环境：pandle 1.8.5 , golang1.4.12
实时预测提示LoD Tensor这个错误是什么意思？

`InvalidArgumentError: Input(X) Tensor of SequencePoolOp does not contain LoD information.
  [Hint: Expected lod_level > 0, but received lod_level:0 <= 0:0.] at (/paddle/paddle/fluid/operators/sequence_ops/sequence_pool_op.h:43)
  [operator < sequence_pool > error]
SIGABRT: abort
PC=0x7f1c2a0f0428 m=0 sigcode=18446744073709551610`

![image](https://user-images.githubusercontent.com/13634356/105009012-ee8f3180-5a74-11eb-8522-0aa2ebbef855.png)

**Comment by zhupengyang** [comment]
输入是需要设置lod的，可以检查下

**Comment by vic-93** [comment]
golang的api没有找到设置lod的方法

**Comment by vic-93** [comment]
@zhupengyang
