### ISSUE TITLE
paddle打包到hadoop上跑有的part会以下错误（一个机器可能有多个reducer同时跑），有的却没有问题：

### ISSUE THREAD

**Issue by huangguanMayday** [PaddlePaddle/Paddle#30591]
![image](https://user-images.githubusercontent.com/4018038/105122577-6ca11600-5b11-11eb-8dd1-005de70e6683.png)
![image](https://user-images.githubusercontent.com/4018038/105122666-9c501e00-5b11-11eb-90fd-a908f2c42288.png)
![image](https://user-images.githubusercontent.com/4018038/105122587-71fe6080-5b11-11eb-909e-0360501263e1.png)
![image](https://user-images.githubusercontent.com/4018038/105122703-ab36d080-5b11-11eb-90e4-b08394f86a28.png)

**Comment by huangguanMayday** [comment]
![Uploading image.png…]()

**Comment by wangxicoding** [comment]
cpu mpi的集群吗，看这些log感觉可能是环境的问题
