### ISSUE TITLE
HUAWEI,Kunpeng 920+麒麟V10，编译错误

### ISSUE THREAD

**Issue by yjygit** [PaddlePaddle/Paddle#30624]
CPU:HUAWEI,Kunpeng 920
OS:麒麟V110
编译报错
Scanning dependencies of target buffered_reader
[ 15%] Building CXX object paddle/fluid/operators/reader/CMakeFiles/buffered_reader.dir/buffered_reader.cc.o
[ 15%] Linking CXX executable jit_kernel_benchmark
/usr/bin/ld: 当搜索用于 /root/paddle/build/third_party/install/mklml/lib/libiomp5.so 时跳过不兼容的 -liomp5 
/usr/bin/ld: 找不到 -liomp5
collect2: error: ld returned 1 exit status
paddle/fluid/operators/jit/CMakeFiles/jit_kernel_benchmark.dir/build.make:135: recipe for target 'paddle/fluid/operators/jit/jit_kernel_benchmark' failed
make[2]: *** [paddle/fluid/operators/jit/jit_kernel_benchmark] Error 1
CMakeFiles/Makefile2:67327: recipe for target 'paddle/fluid/operators/jit/CMakeFiles/jit_kernel_benchmark.dir/all' failed
make[1]: *** [paddle/fluid/operators/jit/CMakeFiles/jit_kernel_benchmark.dir/all] Error 2
make[1]: *** 正在等待未完成的任务....
[ 15%] Linking CXX static library libvariable_visitor.a
[ 15%] Built target variable_visitor
[ 15%] Linking CXX static library libbuffered_reader.a
[ 15%] Built target buffered_reader
[ 15%] Linking CXX static library libmath_function.a
[ 15%] Built target math_function
Makefile:132: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by jiweibo** [comment]
请使用2.0的paddle 

参考编译文档 https://www.paddlepaddle.org.cn/install/quick?docurl=/documentation/docs/zh/2.0-rc1/install/compile/arm-compile.html
