### ISSUE TITLE
paddle detection GPU使用报错Cublas error, CUBLAS_STATUS_NOT_INITIALIZED

### ISSUE THREAD

**Issue by tucker666** [PaddlePaddle/Paddle#30622]
1）PaddlePaddle版本：paddlepaddle_gpu-2.0.0rc1.post100-cp36-cp36m-linux_x86_64.whl
使用下图的padlle进行安装
![image](https://user-images.githubusercontent.com/53161743/105273630-a851e380-5bd6-11eb-8818-3e69fa166772.png)
CUDA版本为10.0
![image](https://user-images.githubusercontent.com/53161743/105273832-fff04f00-5bd6-11eb-8b96-dab24e44f625.png)
![image](https://user-images.githubusercontent.com/53161743/105273854-0979b700-5bd7-11eb-8ad7-b7256c10613c.png)
运行PaddleDetection模型ResNet101-vd-FPN-Dcnv2时cpu正常，GPU报错
![image](https://user-images.githubusercontent.com/53161743/105273976-434abd80-5bd7-11eb-9940-1eed15d95516.png)
请问是什么问题，谢谢！

**Comment by JZ-LIANG** [comment]
麻烦贴一下 c++ 栈报错信息：
export FLAGS_call_stack_level=2

**Comment by tucker666** [comment]
> 麻烦贴一下 c++ 栈报错信息：
> export FLAGS_call_stack_level=2

![image](https://user-images.githubusercontent.com/53161743/105285103-ae53be80-5bee-11eb-81c3-7aa0e92ec525.png)

**Comment by tucker666** [comment]
还想问下，为啥CPU跑的那么慢啊，十几秒中的样子，看文档里V100上能达到20fps这样子，差距这么多的么

**Comment by JZ-LIANG** [comment]
栈信息没看到出特别问题，能给一下能复现这个问题的代码吗？我们本地跑一下。   

V100和 CPU 硬件差异，感觉速度差距大很应该正常的，但没对齐硬件环境前不能完全断定速度慢不是其他问题导致的

**Comment by tucker666** [comment]
> 栈信息没看到出特别问题，能给一下能复现这个问题的代码吗？我们本地跑一下。
> 
> V100和 CPU 硬件差异，感觉速度差距大很应该正常的，但没对齐硬件环境前不能完全断定速度慢不是其他问题导致的

代码就是https://github.com/PaddlePaddle/PaddleDetection/tree/release/2.0-beta/tools/infer.py  
模型是
https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.0-beta/docs/featured_model/LARGE_SCALE_DET_MODEL.md

下的第二个模型
![image](https://user-images.githubusercontent.com/53161743/105288429-d5ac8a80-5bf2-11eb-9151-97c3c7376236.png)

**Comment by JZ-LIANG** [comment]
本地运行正常，没有复现你指的问题。 本地环境 cuda-10.0， 相同whl 包。

可能是你那边环境细节没有对齐， 建议在你当前环境直接编译paddle。可以参考：https://www.paddlepaddle.org.cn/documentation/docs/zh/install/compile/linux-compile.html

**Comment by tucker666** [comment]
> 本地运行正常，没有复现你指的问题。 本地环境 cuda-10.0， 相同whl 包。
> 
> 可能是你那边环境细节没有对齐， 建议在你当前环境直接编译paddle。可以参考：https://www.paddlepaddle.org.cn/documentation/docs/zh/install/compile/linux-compile.html

谢谢，在其他服务器上也没有以上问题，应该是服务器环境配置的问题
