### ISSUE TITLE
ppaddle support intel gpu or not?

### ISSUE THREAD

**Issue by tingggggg** [PaddlePaddle/Paddle#30629]
想詢問 paddle paddle 是否支持 intel gpu （UHD Graphics 630 ... ）加速？

**Comment by luotao1** [comment]
目前并不支持，请问有什么需求么？

**Comment by tingggggg** [comment]
> 目前并不支持，请问有什么需求么？

了解，謝謝回覆
想確認手邊代碼是否能做擴充。像 openvino 支援 intel gpu
