### ISSUE TITLE
在nano上pip安装官网提供的whl包，调用报错

### ISSUE THREAD

**Issue by Fitz-Fitz** [PaddlePaddle/Paddle#30638]
官网提供的whl包：https://www.paddlepaddle.org.cn/documentation/docs/zh/2.0-rc1/install/Tables.html
在jetson nano上直接pip安装成功，Jetpack4.3与官网提供包版本相符，调用paddle时报错如下：

Python 3.6.9 (default, Oct  8 2020, 12:12:24)
[GCC 8.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import paddle.fluid
Illegal instruction (core dumped)

**Comment by Fitz-Fitz** [comment]
已解决，系numpy版本问题

**Comment by Irvingao** [comment]
请问我也遇到了相同的问题，请问numpy版本问题是指版本过低吗？
