### ISSUE TITLE
适配华为昇腾NPU

### ISSUE THREAD

**Issue by ponycloud235** [PaddlePaddle/Paddle#30635]
欢迎您对PaddlePaddle提出建议，非常感谢您对PaddlePaddle的贡献！
在留下您的建议时，辛苦您同步提供如下信息：
- 版本、环境信息
1）PaddlePaddle版本：1.8.5
2）CPU/GPU：华为昇腾环境适配
3）系统环境：centos7.6
- 建议描述：
在实际项目中，需要将算法部署至华为的盒子（Atlas），PaddlePaddle目前不支持，很难受，官方是否在后续版本中考虑适配？

**Comment by JZ-LIANG** [comment]
请关注： https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/install/compile/arm-compile.html

**Comment by nizhaoqiao** [comment]
> 欢迎您对PaddlePaddle提出建议，非常感谢您对PaddlePaddle的贡献！
> 在留下您的建议时，辛苦您同步提供如下信息：
> 
> * 版本、环境信息
>   1）PaddlePaddle版本：1.8.5
>   2）CPU/GPU：华为昇腾环境适配
>   3）系统环境：centos7.6
> * 建议描述：
>   在实际项目中，需要将算法部署至华为的盒子（Atlas），PaddlePaddle目前不支持，很难受，官方是否在后续版本中考虑适配？

如果您指的是昇腾310做推理，目前有两种方式，一种是通过paddle2onnx，用onnx的方式进行部署；另一种是我们进行当中的原生支持，这个在开发中，目前主要能支持一些图像类模型。如果您方便的话可以将您希望支持的模型文件提供给我们，我们会放在排期中。

**Comment by entropyfeng** [comment]
您好，我在官网上看到对Paddle对Lite昇腾310源码编译即将提供，这个即将，预计要多久？
