### ISSUE TITLE
在Agx Xavier上成功编译安装paddle2.0rc1，但生成的C++预测库中version.txt不包含tensorrt版本信息

### ISSUE THREAD

**Issue by kritohyh** [PaddlePaddle/Paddle#30643]
参考教程：https://zhuanlan.zhihu.com/p/326182912
我遇到的问题： 打包了本机上jetpack4.4.1含有的TensorRT文件，并在cmake时指定了tensorrt的路径， 成功编译了C++预测库和python whl文件， 但是没有在C++预测库中的version.txt看到tensorrt版本信息。 
并且通过pip 安装paddle以后，测试inference-demo yolov3  中的infer_yolov3.py   调用tensorrt报错：
ValueError：(InvalidArgument) pass tensorrt_subgraph has not been registered
我到底成功安装TensorRT了吗  没有成功的话为什么编译过程中没有报错？？

以下是环境信息和编译操作   
 1）PaddlePaddle版本：paddlepaddle2.0rc1
 2）Jetpack4.4.1： cuda10.2 cudnn8  ubuntu18 trt7 openncv4
 3）Agx Xavier平台
-预测库信息
    1）编译生成的C++预测库 version.txt文件：
      WITH_MKL: OFF
      WITH_MKLDNN :OFF
      WITH_GPU: ON
      CUDA version:10.2
      CUDNN version: v8.0
      CXX compiler version: 7.5.0
      只包含上述信息
    2）CMake包含路径的完整命令
    cmake .. \  
              -DWITH_CONTRIB=OFF \  
              -DWITH_MKL=OFF  \  
              -DWITH_MKLDNN=OFF \  
              -DWITH_TESTING=OFF \  
              -DCMAKE_BUILD_TYPE=Release \  
              -DON_INFER=ON \  
              -DWITH_PYTHON=ON \   
              -DWITH_XBYAK=OFF  \  
              -DWITH_NV_JETSON=ON \    
              -DPY_VERSION=3.6 \  
              -DTENSORRT_ROOT=/home/.../Paddle/TensorRT \   
              -DCUDA_ARCH_NAME=Auto

**Comment by shangzhizhou** [comment]
编译选项请增加-DWITH_TENSORRT=ON

**Comment by kritohyh** [comment]
> 编译选项请增加-DWITH_TENSORRT=ON

是的 加上这个选项已经成功编译集成tensorrt的paddle。
编译完成后的框架加上板子必须的软件包已经达到了23GB，  想问下编译过程中生成的文件有哪些是可以删除不影响的吗？
可以执行make clean清除后面用不到的文件么， 后续还需要分别测试C++与python版本的推理库

**Comment by OliverLPH** [comment]
@kritohyh 
build目录下产出的 `paddle_inference_install_dir` 目录是C++推理库，`python/dist/paddlepaddle_*.whl` 是产出的python whl包。如果您已经完成编译，可以只保留这两个

**Comment by kritohyh** [comment]
> @kritohyh
> build目录下产出的 `paddle_inference_install_dir` 目录是C++推理库，`python/dist/paddlepaddle_*.whl` 是产出的python whl包。如果您已经完成编译，可以只保留这两个

好 谢谢！  问题已经解决
