### ISSUE TITLE
Benchmark ernie mkldnn的文档是否还需要维护

### ISSUE THREAD

**Issue by lidanqing-vv** [PaddlePaddle/Paddle#30656]
请问Benchmark中关于ernie mkldnn的文档是否还需要维护？要不要删掉？
https://github.com/PaddlePaddle/benchmark/tree/master/Inference/c%2B%2B/ernie/mkldnn

因为ernie mkldnn的demo 和文档都在PaddleSlim 更新了
https://github.com/PaddlePaddle/PaddleSlim/tree/develop/demo/mkldnn_quant

@luotao1

**Comment by luotao1** [comment]
@lidanqing-intel 可以把`ernie/mkldnn/README.md`原来内容删了，放上`
https://github.com/PaddlePaddle/PaddleSlim/tree/develop/demo/mkldnn_quant`的链接和相应的说明即可。类似`https://github.com/PaddlePaddle/Paddle/tree/develop/doc`的说明

**Comment by juncaipeng** [comment]
@lidanqing-intel  You can add Ernie int8 demo and doc to  [PaddleInference](https://paddle-inference.readthedocs.io/en/latest/#).

![image](https://user-images.githubusercontent.com/52520497/105812212-b645a100-5fe8-11eb-8797-6df2551d9841.png)

**Comment by lidanqing-vv** [comment]
I have updated document in benchmark repo. The readme is at same location as before.
