### ISSUE TITLE
怎么知道返回的 MNIST数据集实例可以使用[ ]访问

### ISSUE THREAD

**Issue by A-Pai** [PaddlePaddle/Paddle#30657]
文档https://www.paddlepaddle.org.cn/documentation/docs/zh/2.0-rc1/api/paddle/vision/datasets/mnist/MNIST_cn.html

文档中只是说“返回 MNIST数据集实例”，“MNIST数据集实例”是什么对象？怎么知道返回的 MNIST数据集实例可以使用[ ]访问？
在何处可以查到？我感觉到其应该是pandas的dataframe的子类，但是找不到明确的说明

**Comment by 123malin** [comment]
MNIST数据实例继承Dataset类，代码见：https://github.com/PaddlePaddle/Paddle/blob/d82d59e6e731a3de4057249239c90b81360a0e01/python/paddle/fluid/dataloader/dataset.py
可以使用[]访问，是因为Dataset类实现了__getitem__方法。

**Comment by A-Pai** [comment]
明白了，谢谢
