### ISSUE TITLE
paddle.vision.datasets.MNIST，默认下载到何处？

### ISSUE THREAD

**Issue by A-Pai** [PaddlePaddle/Paddle#30651]
train_dataset = paddle.vision.datasets.MNIST(mode='train', transform=transform)，默认下载到何处？源代码中没查到
https://github.com/PaddlePaddle/Paddle/blob/release/2.0-rc1/python/paddle/vision/datasets/mnist.py#L30

**Comment by 123malin** [comment]
Paddle数据下载默认在~/.cache/paddle/dataset下，mnist数据集应该会在~/.cache/paddle/dataset/mnist下

**Comment by A-Pai** [comment]
>



> Paddle数据下载默认在~/.cache/paddle/dataset下，mnist数据集应该会在~/.cache/paddle/dataset/mnist下

1、“~”表示什么？
2、怎么知道在此路径下？源文件中似乎没有

**Comment by 123malin** [comment]
> > 
> 
> > Paddle数据下载默认在~/.cache/paddle/dataset下，mnist数据集应该会在~/.cache/paddle/dataset/mnist下
> 
> 1、“~”表示什么？
> 2、怎么知道在此路径下？源文件中似乎没有

1. ~就是用户根目录，你可以在你的机器上执行cd ~ && pwd看看根目录是什么，linux系统用户根目录一般是/home/user_name。
2. 这是框架内部规定的，一般用户不需要关心，download完会返回下载路径的。源码在https://github.com/PaddlePaddle/Paddle/blob/d82d59e6e731a3de4057249239c90b81360a0e01/python/paddle/dataset/common.py。

**Comment by A-Pai** [comment]
回答得真好！！感谢、感谢！
