### ISSUE TITLE
使用clip_by_norm接口出错

### ISSUE THREAD

**Issue by yeyupiaoling** [PaddlePaddle/Paddle#30664]
- PaddlePaddle 2.0.0rc
- Ubuntu 18

```python
paddle.nn.clip_by_norm(model.parameters(), 0.5)
```

错误如下：
```

  File "train.py", line 203, in train
    paddle.nn.clip_by_norm(model.parameters(), 0.5)
  File "/home/anaconda3/envs/PaddlePaddle2/lib/python3.7/site-packages/paddle/fluid/layers/nn.py", line 12404, in clip_by_norm
    return core.ops.clip_by_norm(x, 'max_norm', max_norm)
paddle.fluid.core_avx.EnforceNotMet: 

--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
0   paddle::platform::EnforceNotMet::EnforceNotMet(paddle::platform::ErrorSummary const&, char const*, int)
1   paddle::platform::GetCurrentTraceBackString()

----------------------
Error Message Summary:
----------------------
InvalidArgumentError: clip_by_norm(): argument 'X' (position 0) must be Tensor, but got list (at /paddle/paddle/fluid/pybind/op_function.h:50)

```

**Comment by vslyu** [comment]
传入的参数X必须为Tensor，建议使用paddle.to_tensor API接口将list转换为tensor再传入

**Comment by vslyu** [comment]
> * PaddlePaddle 2.0.0rc
> * Ubuntu 18
> 
> ```python
> paddle.nn.clip_by_norm(model.parameters(), 0.5)
> ```
> 
> 错误如下：
> 
> ```
> 
>   File "train.py", line 203, in train
>     paddle.nn.clip_by_norm(model.parameters(), 0.5)
>   File "/home/anaconda3/envs/PaddlePaddle2/lib/python3.7/site-packages/paddle/fluid/layers/nn.py", line 12404, in clip_by_norm
>     return core.ops.clip_by_norm(x, 'max_norm', max_norm)
> paddle.fluid.core_avx.EnforceNotMet: 
> 
> --------------------------------------
> C++ Traceback (most recent call last):
> --------------------------------------
> 0   paddle::platform::EnforceNotMet::EnforceNotMet(paddle::platform::ErrorSummary const&, char const*, int)
> 1   paddle::platform::GetCurrentTraceBackString()
> 
> ----------------------
> Error Message Summary:
> ----------------------
> InvalidArgumentError: clip_by_norm(): argument 'X' (position 0) must be Tensor, but got list (at /paddle/paddle/fluid/pybind/op_function.h:50)
> ```

传入的参数X必须为Tensor，建议使用paddle.to_tensor API接口将list转换为tensor再传入

**Comment by yeyupiaoling** [comment]
@vslyu 这个model.parameters()我用paddle.to_tensor接口转换不行，直接卡死。有其他方法吗？

**Comment by vslyu** [comment]
> @vslyu 这个model.parameters()我用paddle.to_tensor接口转换不行，直接卡死。有其他方法吗？

你的model.parameters()里面都有啥，print出来看看

**Comment by yeyupiaoling** [comment]
@vslyu 我们的model 就是一个普通的卷积网络，结构如下。print打印是一大堆Tensor。
```python
import paddle.nn as nn
import paddle.nn.functional as F


class Model(nn.Layer):
    def __init__(self, num_inputs, num_actions):
        super(Model, self).__init__()
        self.conv1 = nn.Conv2D(num_inputs, 32, 3, stride=2, padding=1)
        self.conv2 = nn.Conv2D(32, 32, 3, stride=2, padding=1)
        self.conv3 = nn.Conv2D(32, 32, 3, stride=2, padding=1)
        self.conv4 = nn.Conv2D(32, 32, 3, stride=2, padding=1)
        self.linear = nn.Linear(32 * 6 * 6, 512)
        self.flatten = nn.Flatten()
        self.critic_linear = nn.Linear(512, 1)
        self.actor_linear = nn.Linear(512, num_actions)

    def forward(self, x):
        x = F.relu(self.conv1(x))
        x = F.relu(self.conv2(x))
        x = F.relu(self.conv3(x))
        x = F.relu(self.conv4(x))
        x = self.flatten(x)
        x = self.linear(x)
        # 定义动作模型和评估模型
        return self.actor_linear(x), self.critic_linear(x)

```

**Comment by vslyu** [comment]
> @vslyu 我们的model 就是一个普通的卷积网络，结构如下。print打印是一大堆Tensor。
> 
> ```python
> import paddle.nn as nn
> import paddle.nn.functional as F
> 
> 
> class Model(nn.Layer):
>     def __init__(self, num_inputs, num_actions):
>         super(Model, self).__init__()
>         self.conv1 = nn.Conv2D(num_inputs, 32, 3, stride=2, padding=1)
>         self.conv2 = nn.Conv2D(32, 32, 3, stride=2, padding=1)
>         self.conv3 = nn.Conv2D(32, 32, 3, stride=2, padding=1)
>         self.conv4 = nn.Conv2D(32, 32, 3, stride=2, padding=1)
>         self.linear = nn.Linear(32 * 6 * 6, 512)
>         self.flatten = nn.Flatten()
>         self.critic_linear = nn.Linear(512, 1)
>         self.actor_linear = nn.Linear(512, num_actions)
> 
>     def forward(self, x):
>         x = F.relu(self.conv1(x))
>         x = F.relu(self.conv2(x))
>         x = F.relu(self.conv3(x))
>         x = F.relu(self.conv4(x))
>         x = self.flatten(x)
>         x = self.linear(x)
>         # 定义动作模型和评估模型
>         return self.actor_linear(x), self.critic_linear(x)
> ```
逐层归一化参数不行吗？

**Comment by yeyupiaoling** [comment]
@vslyu 归一化？不是不要归一化，我要的是使用这个函数clip_by_norm裁剪

**Comment by vslyu** [comment]
> @vslyu 归一化？不是不要归一化，我要的是使用这个函数clip_by_norm裁剪

逐层clip_by_norm裁剪不行吗？～
```
 for layer_parameters in model.parameters():
       paddle.nn.clip_by_norm(layer_parameters, 0.5)
```

**Comment by yeyupiaoling** [comment]
也可以。
