### ISSUE TITLE
关于fluid.data的shape的维度问题

### ISSUE THREAD

**Issue by btobab** [PaddlePaddle/Paddle#30669]
![QQ图片20210123201208](https://user-images.githubusercontent.com/66876429/105577964-e35f3d00-5db7-11eb-947e-0c20f5256de2.png)
这是NLP项目，这里的data的shape=[1]和label的shape=[1]有什么区别，data是词向量，label是一个int，分不清

**Comment by IamDestiny** [comment]
![QQ图片20210123201208](https://user-images.githubusercontent.com/66876429/105578055-726c5500-5db8-11eb-8591-d6eef6eb4112.png)

**Comment by vslyu** [comment]
公司代理挂了，我现在看不到你发的图片，可否用文字说下？~

**Comment by btobab** [comment]
data = fluid.layers.data(name="words", shape=[1], dtype="int64", lod_level=1)
label = fluid.layers.data(name="label", shape=[1], dtype="int64")
这里data和label的shape都是[1],有什么区别丫
这是个NLP项目，data表示一个词向量，label是一个int的标签

**Comment by vslyu** [comment]
参见 fluid.layers.data的API，你可以把data和label打印出来看看，https://www.paddlepaddle.org.cn/documentation/docs/zh/2.0-rc1/api/paddle/fluid/data_cn.html#data ，shape为[-1,1]，前面的-1表示为可变的batchsize。 data和label从模型角度来看，data是样本原始数据，label是人为标记的标签
```
In [6]: data = fluid.layers.data(name="words", shape=[1], dtype="int64", lod_level=1)
         label = fluid.layers.data(name="label", shape=[1], dtype="int64")
In [7]: data
Out[7]: var words : LOD_TENSOR.shape(-1, 1).dtype(INT64).stop_gradient(True)
In [8]: label
Out[8]: var label : LOD_TENSOR.shape(-1, 1).dtype(INT64).stop_gradient(True)
```

**Comment by btobab** [comment]
好的，明白了
