### ISSUE TITLE
训练时警告Cannot enable P2P access from 0 to 1

### ISSUE THREAD

**Issue by yeyupiaoling** [PaddlePaddle/Paddle#30665]
- PaddlePaddle 2.0.0rc
 - Ubuntu  18
 - 
```
W0123 12:53:34.584239 25480 init.cc:108] Cannot enable P2P access from 0 to 1
W0123 12:53:34.584255 25480 init.cc:108] Cannot enable P2P access from 1 to 0
```

这种经过是否会影响训练？

**Comment by vslyu** [comment]
> 这种经过是否会影响训练？

不会，P2P指的是gpu多卡使用nvlink 的互联，如果你是单卡训练的话，无需在意这些warining~

**Comment by yeyupiaoling** [comment]
好的。谢谢。

**Comment by wangzy0327** [comment]
i am also meet this problems. how could solve it?
parallel_executor.cc:596] Cannot enable P2P access from 0 to 1
parallel_executor.cc:596] Cannot enable P2P access from 1 to 0
