### ISSUE TITLE
2.0rc1中使用gpu，仅仅在开始的添加这句即可？device = paddle.set_device('gpu')

### ISSUE THREAD

**Issue by A-Pai** [PaddlePaddle/Paddle#30667]
2.0rc1中使用gpu，仅仅在开始的添加这句即可？
device = paddle.set_device('gpu')

数据会自动存在显存中？需不需要别的设置？怎样才能最大程度地提升gpu的利用率？最好有个完整的加以对比的例子

**Comment by vslyu** [comment]
> 2.0rc1中使用gpu，仅仅在开始的添加这句即可？
> device = paddle.set_device('gpu')
> 
> 数据会自动存在显存中？需不需要别的设置？怎样才能最大程度地提升gpu的利用率？最好有个完整的加以对比的例子

是的，指定device为gpu后，数据会自动存在显存，无需其他设置。至于如何最大程度地提升gpu的利用率, 推荐使用DataParallel数据并行的接口，https://www.paddlepaddle.org.cn/documentation/docs/zh/2.0-rc1/api/paddle/fluid/dygraph/parallel/DataParallel_cn.html#dataparallel；

数据reader可以调大DataLoader的num_workers参数，https://www.paddlepaddle.org.cn/documentation/docs/zh/2.0-rc1/api/paddle/io/DataLoader_cn.html

**Comment by A-Pai** [comment]
> > 2.0rc1中使用gpu，仅仅在开始的添加这句即可？
> > device = paddle.set_device('gpu')
> > 数据会自动存在显存中？需不需要别的设置？怎样才能最大程度地提升gpu的利用率？最好有个完整的加以对比的例子
> 
> 是的，指定device为gpu后，数据会自动存在显存，无需其他设置。至于如何最大程度地提升gpu的利用率, 推荐使用DataParallel数据并行的接口，[https://www.paddlepaddle.org.cn/documentation/docs/zh/2.0-rc1/api/paddle/fluid/dygraph/parallel/DataParallel_cn.html#dataparallel；](https://www.paddlepaddle.org.cn/documentation/docs/zh/2.0-rc1/api/paddle/fluid/dygraph/parallel/DataParallel_cn.html#dataparallel%EF%BC%9B)
> 
> 数据reader可以调大DataLoader的num_workers参数，https://www.paddlepaddle.org.cn/documentation/docs/zh/2.0-rc1/api/paddle/io/DataLoader_cn.html

我想在AI Studio中提供GPU的利用率，上述文档中的代码似乎不能在AI Studio中运行

**Comment by vslyu** [comment]
和AI Studio应该没有关系，这是paddlepaddle-2.0rc1暴露的接口，你需要修改代码适配这些接口。

**Comment by A-Pai** [comment]
> 和AI Studio应该没有关系，这是paddlepaddle-2.0rc1暴露的接口，你需要修改代码适配这些接口。

可否给个完整的示例--与不这样做有对比

**Comment by A-Pai** [comment]
请给个完整的例子，以后都可以参照使用

**Comment by vslyu** [comment]
参看dataloder的示例代码，DataParallel的接口是多卡加速用的，单卡使用可暂不考虑。可以考虑把from_generator里面的use_multiprocess置为True，可以达到加速的效果，另外，可根据实际情况设置capacity和use_double_buffer的布尔值。 https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/io/DataLoader_cn.html#dataloader；
```
'''
Example in dynamic graph mode.
'''
import numpy as np

import paddle
import paddle.nn as nn
import paddle.optimizer as opt
import paddle.distributed as dist

BATCH_SIZE = 16
BATCH_NUM = 4
EPOCH_NUM = 4

IMAGE_SIZE = 784
CLASS_NUM = 10

USE_GPU = False # whether to use GPU

def _get_random_images_and_labels(image_shape, label_shape):
        image = np.random.random(size=image_shape).astype('float32')
        label = np.random.random(size=label_shape).astype('int64')
        return image, label

def __reader__():
        for _ in range(BATCH_NUM):
            batch_image, batch_label = _get_random_images_and_labels(
                [BATCH_SIZE, IMAGE_SIZE], [BATCH_SIZE, CLASS_NUM])
            yield batch_image, batch_label

def random_batch_reader():
    return __reader__

class LinearNet(nn.Layer):
    def __init__(self):
        super(LinearNet, self).__init__()
        self._linear = nn.Linear(IMAGE_SIZE, CLASS_NUM)

    @paddle.jit.to_static
    def forward(self, x):
        return self._linear(x)

# set device
paddle.set_device('gpu' if USE_GPU else 'cpu')

# create network
layer = LinearNet()
dp_layer = paddle.DataParallel(layer)
loss_fn = nn.CrossEntropyLoss()
adam = opt.Adam(learning_rate=0.001, parameters=dp_layer.parameters())

# create data loader
loader = paddle.io.DataLoader.from_generator(capacity=5)
loader.set_batch_generator(random_batch_reader())

for epoch_id in range(EPOCH_NUM):
    for batch_id, (image, label) in enumerate(loader()):
        out = layer(image)
        loss = loss_fn(out, label)

        loss.backward()

        adam.step()
        adam.clear_grad()
        print("Epoch {} batch {}: loss = {}".format(
            epoch_id, batch_id, np.mean(loss.numpy())))

```

**Comment by A-Pai** [comment]
> 参看dataloder的示例代码，DataParallel的接口是多卡加速用的，单卡使用可暂不考虑。可以考虑把from_generator里面的use_multiprocess置为True，可以达到加速的效果，另外，可根据实际情况设置capacity和use_double_buffer的布尔值。 [https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/io/DataLoader_cn.html#dataloader；](https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/io/DataLoader_cn.html#dataloader%EF%BC%9B)
> 
> ```
> '''
> Example in dynamic graph mode.
> '''
> import numpy as np
> 
> import paddle
> import paddle.nn as nn
> import paddle.optimizer as opt
> import paddle.distributed as dist
> 
> BATCH_SIZE = 16
> BATCH_NUM = 4
> EPOCH_NUM = 4
> 
> IMAGE_SIZE = 784
> CLASS_NUM = 10
> 
> USE_GPU = False # whether to use GPU
> 
> def _get_random_images_and_labels(image_shape, label_shape):
>         image = np.random.random(size=image_shape).astype('float32')
>         label = np.random.random(size=label_shape).astype('int64')
>         return image, label
> 
> def __reader__():
>         for _ in range(BATCH_NUM):
>             batch_image, batch_label = _get_random_images_and_labels(
>                 [BATCH_SIZE, IMAGE_SIZE], [BATCH_SIZE, CLASS_NUM])
>             yield batch_image, batch_label
> 
> def random_batch_reader():
>     return __reader__
> 
> class LinearNet(nn.Layer):
>     def __init__(self):
>         super(LinearNet, self).__init__()
>         self._linear = nn.Linear(IMAGE_SIZE, CLASS_NUM)
> 
>     @paddle.jit.to_static
>     def forward(self, x):
>         return self._linear(x)
> 
> # set device
> paddle.set_device('gpu' if USE_GPU else 'cpu')
> 
> # create network
> layer = LinearNet()
> dp_layer = paddle.DataParallel(layer)
> loss_fn = nn.CrossEntropyLoss()
> adam = opt.Adam(learning_rate=0.001, parameters=dp_layer.parameters())
> 
> # create data loader
> loader = paddle.io.DataLoader.from_generator(capacity=5)
> loader.set_batch_generator(random_batch_reader())
> 
> for epoch_id in range(EPOCH_NUM):
>     for batch_id, (image, label) in enumerate(loader()):
>         out = layer(image)
>         loss = loss_fn(out, label)
> 
>         loss.backward()
> 
>         adam.step()
>         adam.clear_grad()
>         print("Epoch {} batch {}: loss = {}".format(
>             epoch_id, batch_id, np.mean(loss.numpy())))
> ```

这个代码可以在AI Studio的2.0rc1高级版中运行？有报错，我想在该环境中尝试，以后想充分利用AI Studio的2.0rc1高级版的gpu

**Comment by A-Pai** [comment]
可以提供**在AI Studio的2.0rc1高级版大幅度提升gpu利用率**的例子代码吗？

**Comment by A-Pai** [comment]
请指导，这对于推广使用AI Studio和吸引大家关注飞桨有重大意义，很多人是冲着AI Studio的强大免费算力使用飞桨的

**Comment by vslyu** [comment]
好的，可以同步下你的环境和demo吗？～

**Comment by A-Pai** [comment]
> 好的，可以同步下你的环境和demo吗？～

什么意思？飞桨2.0rc1、AI Studio的高级版

**Comment by A-Pai** [comment]
没有后话了？

**Comment by A-Pai** [comment]
> 好的，可以同步下你的环境和demo吗？～

没有后话了？
