### ISSUE TITLE
项目https://github.com/PaddlePaddle/book中的ipynb文件没有克隆到AI Studio，何故？

### ISSUE THREAD

**Issue by A-Pai** [PaddlePaddle/Paddle#30674]
我把项目：https://github.com/PaddlePaddle/book
folk到gitee，在AI Studio中克隆：!git clone https://gitee.com/lg21c/book.git
但是发现“paddle2.0_docs”子文件夹是空的--其中的ipynb文件没有克隆下来，何故？

**Comment by pangyoki** [comment]
我在开发机上 `git clone https://gitee.com/lg21c/book.git`是没有问题的，你在AI studio中clone时显示clone完成了吗？直接clone `https://github.com/PaddlePaddle/book`会有问题吗？

**Comment by A-Pai** [comment]
> 我在开发机上 `git clone https://gitee.com/lg21c/book.git`是没有问题的，你在AI studio中clone时显示clone完成了吗？直接clone `https://github.com/PaddlePaddle/book`会有问题吗？

1、在AI studio中clone时显示clone完成，https://gitee.com/lg21c/book.git中“paddle2.0_docs”子文件夹是有ipynb文件的
2、直接clone https://github.com/PaddlePaddle/book很慢
3、难道说AI studio会屏蔽掉ipynb文件？

**Comment by pangyoki** [comment]
> > 我在开发机上 `git clone https://gitee.com/lg21c/book.git`是没有问题的，你在AI studio中clone时显示clone完成了吗？直接clone `https://github.com/PaddlePaddle/book`会有问题吗？
> 
> 1、在AI studio中clone时显示clone完成，[https://gitee.com/lg21c/book.git中“paddle2.0_docs”子文件夹是有ipynb文件的](https://gitee.com/lg21c/book.git%E4%B8%AD%E2%80%9Cpaddle2.0_docs%E2%80%9D%E5%AD%90%E6%96%87%E4%BB%B6%E5%A4%B9%E6%98%AF%E6%9C%89ipynb%E6%96%87%E4%BB%B6%E7%9A%84)
> 2、直接clone [https://github.com/PaddlePaddle/book很慢](https://github.com/PaddlePaddle/book%E5%BE%88%E6%85%A2)
> 3、难道说AI studio会屏蔽掉ipynb文件？

会不会是网络问题？你是内网环境吗，设置一下代理试试？我挂代理clone PaddlePaddle下的book库也很快

**Comment by A-Pai** [comment]
我用的中国移动的网，你用AI Studio试了吗？

**Comment by pangyoki** [comment]
我问下AI Studio的同学哈，我这边用内网的开发机和电信网下载都是没问题的。

**Comment by pangyoki** [comment]
你也可以试下不用AI studio的环境，直接clone看会不会出现一样的问题哈？也有可能是网络问题

**Comment by A-Pai** [comment]
> 网络问题



> 你也可以试下不用AI studio的环境，直接clone看会不会出现一样的问题哈？也有可能是网络问题

网络的可能性低

**Comment by A-Pai** [comment]
> 你也可以试下不用AI studio的环境，直接clone看会不会出现一样的问题哈？也有可能是网络问题

在我的pc上clone是好的--paddle2.0_docs”子文件夹有ipynb文件的

**Comment by pangyoki** [comment]
> > 你也可以试下不用AI studio的环境，直接clone看会不会出现一样的问题哈？也有可能是网络问题
> 
> 在我的pc上clone是好的--paddle2.0_docs”子文件夹有ipynb文件的

好的 ，已经联系AI studio的同学了，有结论会尽快回复哈。

**Comment by pangyoki** [comment]
咨询了AI studio的同学，AI studio里的ipynb是被特殊保护的，以避免误删，因此ipynb都是被隐藏的。其实clone同步了，但是被隐藏起来了。

**Comment by A-Pai** [comment]
> 咨询了AI studio的同学，AI studio里的ipynb是被特殊保护的，以避免误删，因此ipynb都是被隐藏的。其实clone同步了，但是被隐藏起来了。

那怎么办？--想利用AI Studio跑github中的ipynb

**Comment by A-Pai** [comment]
没有办法了？只能这样用？--想利用AI Studio跑github中的ipynb，图谋不能实现？

**Comment by weiexcelpro** [comment]
> > 咨询了AI studio的同学，AI studio里的ipynb是被特殊保护的，以避免误删，因此ipynb都是被隐藏的。其实clone同步了，但是被隐藏起来了。
> 
> 那怎么办？--想利用AI Studio跑github中的ipynb

其他的部分正常同步, ipynb单独下载, 然后通过notebook菜单里面的"导入ipynb", 来上传, 即可

**Comment by A-Pai** [comment]
不是好办法
