### ISSUE TITLE
paddle.jit，其中的jit是什么意思？

### ISSUE THREAD

**Issue by A-Pai** [PaddlePaddle/Paddle#30672]
paddle.jit，其中的jit是什么意思？--是什么的缩写？

**Comment by pangyoki** [comment]
paddle.jit下主要是与动转静有关的功能，jit是 `just in time` 的缩写，即时编译技术。

**Comment by A-Pai** [comment]
> paddle.jit下主要是与动转静有关的功能，jit是 `just in time` 的缩写，即时编译技术。

好的，明白了
