### ISSUE TITLE
“暴漏”是什么意思？---给自定义的数据集类暴漏一个构造参数

### ISSUE THREAD

**Issue by A-Pai** [PaddlePaddle/Paddle#30683]
文档https://www.paddlepaddle.org.cn/documentation/docs/zh/2.0-rc1/guides/02_paddle2.0_develop/03_data_preprocessing_cn.html

“给自定义的数据集类暴漏一个构造参数”---“暴漏”是什么意思？是术语？

**Comment by heavengate** [comment]
感谢反馈，我们修改下~

**Comment by A-Pai** [comment]
> 感谢反馈，我们修改下~

有什么问题吗？是术语？
