### ISSUE TITLE
mkldnn_inplace_pass problem set

### ISSUE THREAD

**Issue by luotao1** [PaddlePaddle/Paddle#30681]
Currently, mkldnn_inplace_pass is disabled on both windows and linux:
- windows: ResNet50_vd, HRNet_W18_C, and SE_ResNeXt50_vd_32x4d report errors #29710 
- linux: SE_ResNeXt50_vd_32x4d report errors https://github.com/PaddlePaddle/Paddle/issues/29506#issuecomment-763451098
   - The models contain long sequences of elementwise_add and relu operators. The sequences are too long for the mkldnn_inplace_pass to handle them properly

We use this new issue to track the mkldnn_inplace_pass problem.

**Comment by lidanqing-vv** [comment]
@luotao1 目前的develop代码中，Jacek 已经注释掉了mkldnn_inplace_pass
我们打算以后打算像fc那样，默认关闭，有需要再打开，上面那两个问题应该不会出现了吧？

**Comment by luotao1** [comment]
> 默认关闭，有需要再打开，上面那两个问题应该不会出现了吧

可以默认关闭，这样上面几个问题就不会出现了。
