### ISSUE TITLE
Model.evaluate()返回格式是一个字典，看不懂

### ISSUE THREAD

**Issue by A-Pai** [PaddlePaddle/Paddle#30685]
文档https://www.paddlepaddle.org.cn/documentation/docs/zh/2.0-rc1/guides/02_paddle2.0_develop/05_train_eval_predict_cn.html
中的“1.3 用Model.evaluate()评估模型”讲到：
返回格式是一个字典： * 只包含loss，{'loss': xxx} * 包含loss和一个评估指标，{'loss': xxx, 'metric name': xxx} * 包含loss和多个评估指标，{'loss': xxx, 'metric name': xxx, 'metric name': xxx}

---这个返回的字典可以有三种？怎么设置选择？

关于该api的文档https://www.paddlepaddle.org.cn/documentation/docs/zh/2.0-rc1/api/paddle/hapi/model/Model_cn.html
中没有讲到这些

**Comment by wanghuancoder** [comment]
> 文档https://www.paddlepaddle.org.cn/documentation/docs/zh/2.0-rc1/guides/02_paddle2.0_develop/05_train_eval_predict_cn.html
> 中的“1.3 用Model.evaluate()评估模型”讲到：
> 返回格式是一个字典： * 只包含loss，{'loss': xxx} * 包含loss和一个评估指标，{'loss': xxx, 'metric name': xxx} * 包含loss和多个评估指标，{'loss': xxx, 'metric name': xxx, 'metric name': xxx}
> 
> ---这个返回的字典可以有三种？怎么设置选择？
> 
> 关于该api的文档https://www.paddlepaddle.org.cn/documentation/docs/zh/2.0-rc1/api/paddle/hapi/model/Model_cn.html
> 中没有讲到这些

返回的是个字典，字典里会有多个数据，具体有多少个，不同的模型返回的不一样，是动态的。

**Comment by A-Pai** [comment]
明白了，谢谢
