### ISSUE TITLE
[MKLDNN] Add MKLDNN hard_swish 

### ISSUE THREAD

**Issue by juncaipeng** [PaddlePaddle/Paddle#30684]
Add MKLDNN hard_swith to improve the performance of OCR detection and recognition model.

Download OCR detection demo(Link:https://dubox.com/s/1Z_63JJtzZS_1ghKYyeTtMQ Password:99vy) and refer to the readme.

OCR recognition demo can be downloaded from #28578 and only consider the fp32 model.

**Comment by lidanqing-vv** [comment]
PR #30211

**Comment by lidanqing-vv** [comment]
@juncaipeng   hard_swish in oneDNN is not merged yet. Usually oneDNN team have one update every two weeks.

**Comment by lidanqing-vv** [comment]
oneDNN team said hard swish is already merged on gitlab (internal oneDNN repo) , so it is matter of when they have next public release. We are still asking.

**Comment by jczaja** [comment]
oneDNN team just released hard-swish . So now we just need to modify our PR with hard-swish support to use newer oneDNN and test it. Hopefully we will be doing this within next few days.
