### ISSUE TITLE
RuntimeError: (PreconditionNotMet) Cannot load cudnn shared library. Cannot invoke method cudnnGetVersion.

### ISSUE THREAD

**Issue by w5688414** [PaddlePaddle/Paddle#30694]
为使您的问题得到快速解决，在建立Issues前，请您先通过如下方式搜索是否有相似问题:【搜索issue关键字】【使用labels筛选】【官方文档】

如果您没有查询到相似问题，为快速解决您的提问，建立issue时请提供如下细节信息：
- 标题：简洁、精准概括您的问题，例如“Insufficient Memory xxx" ”
- 版本、环境信息：
    1）PaddlePaddle版本：2.0 rc
    2）CPU：预测若用CPU，请提供CPU型号，MKL/OpenBlas/MKLDNN/等数学库使用情况
    3）GPU：Tesla V100-SXM2,cuda 10.2, driver 440.64.00 
    4）系统环境：centos 7
 注：您可以通过执行[summary_env.py](https://github.com/PaddlePaddle/Paddle/blob/develop/tools/summary_env.py)获取以上信息。
- 训练信息
    1）单机/多机，单卡/多卡
    2）显存信息
    3）Operator信息
- 复现信息：如为报错，请给出复现环境、复现步骤
- 问题描述：
代码：
```
import paddle
from paddle.vision.transforms import Compose, Normalize
from paddle.vision.datasets import MNIST
import paddle.nn as nn 

# 数据预处理，这里用到了随机调整亮度、对比度和饱和度
transform = Compose([Normalize(mean=[127.5],
                               std=[127.5],
                               data_format='CHW')])


# 数据加载，在训练集上应用数据预处理的操作
train_dataset = MNIST(mode='train', transform=transform)
test_dataset = MNIST(mode='test')

# 模型组网
mnist = nn.Sequential(
    nn.Flatten(),
    nn.Linear(784, 512),
    nn.ReLU(),
    nn.Dropout(0.2),
    nn.Linear(512, 10)
)

# 模型封装，用Model类封装
model = paddle.Model(mnist)

# 模型配置：为模型训练做准备，设置优化器，损失函数和精度计算方式
model.prepare(optimizer=paddle.optimizer.Adam(parameters=model.parameters()),
              loss=nn.CrossEntropyLoss(),
              metrics=paddle.metric.Accuracy())

# 模型训练，
model.fit(train_dataset,
          epochs=5,
          batch_size=64,
          verbose=1)

# 模型评估，
model.evaluate(test_dataset, verbose=1)
```
错误：
```
W0126 11:12:38.762002 46175 device_context.cc:320] Please NOTE: device: 0, GPU Compute Capability: 7.0, Driver API Version: 10.2, Runtime API Version: 10.2
W0126 11:12:38.762238 46175 dynamic_loader.cc:236] The third-party dynamic library (libcudnn.so) that Paddle depends on is not configured correctly. (error code is libcudnn.so: cannot open shared object file: No such file or directory)
  Suggestions:
  1. Check if the third-party dynamic library (e.g. CUDA, CUDNN) is installed correctly and its version is matched with paddlepaddle you installed.
  2. Configure third-party dynamic library environment variables as follows:
  - Linux: set LD_LIBRARY_PATH by `export LD_LIBRARY_PATH=...`
  - Windows: set PATH by `set PATH=XXX;
Traceback (most recent call last):
  File "paddle_demo.py", line 19, in <module>
    nn.Linear(784, 512),
  File "/home/wu/anaconda3/lib/python3.7/site-packages/paddle/nn/layer/common.py", line 131, in __init__
    is_bias=False)
  File "/home/wu/anaconda3/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 390, in create_parameter
    default_initializer)
  File "/home/wu/anaconda3/lib/python3.7/site-packages/paddle/fluid/layer_helper_base.py", line 372, in create_parameter
    **attr._to_kwargs(with_initializer=True))
  File "/home/wu/anaconda3/lib/python3.7/site-packages/paddle/fluid/framework.py", line 2807, in create_parameter
    initializer(param, self)
  File "/home/wu/anaconda3/lib/python3.7/site-packages/paddle/fluid/initializer.py", line 568, in __call__
    stop_gradient=True)
  File "/home/wu/anaconda3/lib/python3.7/site-packages/paddle/fluid/framework.py", line 2923, in _prepend_op
    kwargs.get("stop_gradient", False))
  File "/home/wu/anaconda3/lib/python3.7/site-packages/paddle/fluid/dygraph/tracer.py", line 45, in trace_op
    not stop_gradient)
RuntimeError: (PreconditionNotMet) Cannot load cudnn shared library. Cannot invoke method cudnnGetVersion.
  [Hint: cudnn_dso_handle should not be null.] (at /paddle/paddle/fluid/platform/dynload/cudnn.cc:76)
  [Hint: If you need C++ stacktraces for debugging, please set `FLAGS_call_stack_level=2`.]
  [operator < uniform_random > error]
```
Thank you for contributing to PaddlePaddle.
Before submitting the issue, you could search issue in the github in case that there was a similar issue submitted or resolved before.
If there is no solution,please make sure that this is a training issue including the following details:
**System information**
-PaddlePaddle version （eg.1.1）or CommitID
-CPU: including CPUMKL/OpenBlas/MKLDNN version
-GPU: including CUDA/CUDNN version
-OS Platform (eg.Mac OS 10.14)
-Other imformation: Distriuted training/informantion of operator/
Graphics card storage
Note: You can get most of the information by running [summary_env.py](https://github.com/PaddlePaddle/Paddle/blob/develop/tools/summary_env.py). 
**To Reproduce**
Steps to reproduce the behavior
**Describe your current behavior**
**Code to reproduce the issue**
**Other info / logs**

**Comment by Joejiong** [comment]
FLAGS_call_stack_level=2，可以把c++报错开启一下，在贴一些信息

**Comment by w5688414** [comment]
我把cuda 10.2的路径加入到bashrc文件里面之后就好了，谢谢了哈
```
export  PATH=/usr/local/cuda-10.2/bin:$PATH
export  LD_LIBRARY_PATH=/usr/local/cuda-10.2/lib64$LD_LIBRARY_PATH
```
应该是cuda啥的没有检测到的原因

**Comment by Joejiong** [comment]
done

**Comment by paulasquin** [comment]
Paddle v2.2.2 is having issues to find libraries if they are not ending with only ".so" and if they are not besides each other exactly. Expanding `LD_LIBRARY_PATH` was not a solution for me.

I had cudnn installed under
`/usr/lib/x86_64-linux-gnu` and cuda libraries installed under `/usr/local/cuda/lib64/`, this last path being indicated within `LD_LIBRARY_PATH`. Paths here are such as defined by cuda's docker images.

I needed to add to my docker the followings : 
```docker
RUN ln -s /usr/lib/x86_64-linux-gnu/libcudnn.so.8 /usr/local/cuda/lib64/libcudnn.so && \
    ln -s /usr/local/cuda/lib64/libcublas.so.11 /usr/local/cuda/lib64/libcublas.so && \
    ln -s /usr/local/cuda/lib64/libcusolver.so.11 /usr/local/cuda/lib64/libcusolver.so
```
    
You may need to adapt this if you are working with another version of cudnn.
Here I have cudnn v8.x / cuda v11.x.
I think this link creation fix is not only related to Docker.

Bests
