### ISSUE TITLE
cnn 模型输入数据如何修改

### ISSUE THREAD

**Issue by MsFive5** [PaddlePaddle/Paddle#3069]
使用本地版cnn模型的时候，想要使用自己准备的数据而不是paddle包里的数据。
想请问如何加载自己的数据。
我用的demo是book里面的06.understand sentiment  train.py

**Comment by qingqing01** [comment]
@MsFive5  可以参考问这篇文章自定义数据部分：https://github.com/PaddlePaddle/models/tree/develop/text_classification#使用自定义数据训练和预测

**Comment by guoshengCS** [comment]
这个Issue貌似已经解决，先行Closed，如果仍有需要还请Reopen
