### ISSUE TITLE
试图改ernie-1.0的代码做对话生成任务，但是运行过程中出core

### ISSUE THREAD

**Issue by lonelydancer** [PaddlePaddle/Paddle#30696]
你好，我试图改ernie-1.0的代码做对话生成任务，但是运行过程中出core。
大致判断是喂数据后，在finetune/chitchat.py的 enc_out = ernie.get_sequence_output()出错。
找不到具体原因，另外debug只会Print，不知道如何精确追查问题。

代码地址：https://github.com/lonelydancer/chitchat

- 版本、环境信息：
    1）PaddlePaddle版本：1.7.2
    2）GPU：teslak80、CUDA version: 10.1.243  cuDNN:8.0.2
    4）系统环境：OS: Ubuntu 18.04 Python version: 2.7.17
 注：您可以通过执行[summary_env.py](https://github.com/PaddlePaddle/Paddle/blob/develop/tools/summary_env.py)获取以上信息。
- 训练信息
    1）单机/单卡
 
- 复现信息：
下载ernie-1.0 中文版  https://ernie-github.cdn.bcebos.com/model-ernie1.0.1.tar.gz
更改 configs/base/chitchat中对应路径
运行 sh run_seq2seq.sh configs/base/chitchat

W0126 11:35:31.792047 23475 device_context.cc:237] Please NOTE: device: 0, CUDA Capability: 37, Driver API Version: 10.1, Runtime API Version: 10.0
W0126 11:35:31.793622 23475 device_context.cc:245] device: 0, cuDNN Version: 8.0.
I0126 11:35:32.076393 23475 rpc_client.h:107] init rpc client with trainer_id 0
I0126 11:35:33.019246 23475 parallel_executor.cc:440] The Program will be executed on CUDA using ParallelExecutor, 1 cards are used, so 1 programs are executed in parallel.
I0126 11:35:33.082650 23475 build_strategy.cc:365] SeqOnlyAllReduceOps:0, num_trainers:1
I0126 11:35:33.272051 23475 parallel_executor.cc:307] Inplace strategy is enabled, when build_strategy.enable_inplace = True
I0126 11:35:33.319128 23475 parallel_executor.cc:375] Garbage collection strategy is enabled, when FLAGS_eager_delete_tensor_gb = 1
W0126 11:35:33.440991 23584 init.cc:209] Warning: PaddlePaddle catches a failure signal, it may not work properly
W0126 11:35:33.441005 23584 init.cc:211] You could check whether you killed PaddlePaddle thread/process accidentally or report the case to PaddlePaddle
W0126 11:35:33.441009 23584 init.cc:214] The detail failure signal is:

W0126 11:35:33.441011 23584 init.cc:217] *** Aborted at 1611632133 (unix time) try "date -d @1611632133" if you are using GNU date ***
W0126 11:35:33.441879 23584 init.cc:217] PC: @                0x0 (unknown)
W0126 11:35:33.442001 23584 init.cc:217] *** SIGSEGV (@0x50) received by PID 23475 (TID 0x7f5fa57e7700) from PID 80; stack trace: ***
W0126 11:35:33.442634 23584 init.cc:217]     @     0x7f5fce38f040 (unknown)
W0126 11:35:33.443208 23584 init.cc:217]     @     0x7f5fce74dc98 (unknown)
W0126 11:35:33.443778 23584 init.cc:217]     @     0x7f5fce75627d (unknown)
W0126 11:35:33.444350 23584 init.cc:217]     @     0x7f5fce4b71ef _dl_catch_exception
W0126 11:35:33.444924 23584 init.cc:217]     @     0x7f5fce75598a (unknown)
W0126 11:35:33.445526 23584 init.cc:217]     @     0x7f5fce4b62bd (unknown)
W0126 11:35:33.446099 23584 init.cc:217]     @     0x7f5fce4b71ef _dl_catch_exception
W0126 11:35:33.446662 23584 init.cc:217]     @     0x7f5fce4b727f _dl_catch_error
W0126 11:35:33.447259 23584 init.cc:217]     @     0x7f5fce4b63e9 __libc_dlopen_mode
W0126 11:35:33.447863 23584 init.cc:217]     @     0x7f5fce480f05 (unknown)
W0126 11:35:33.448428 23584 init.cc:217]     @     0x7f5fce140907 __pthread_once_slow
W0126 11:35:33.449024 23584 init.cc:217]     @     0x7f5fce480fdf backtrace
W0126 11:35:33.451231 23584 init.cc:217]     @     0x7f5ed3d2fab5 paddle::platform::GetTraceBackString<>()
W0126 11:35:33.453219 23584 init.cc:217]     @     0x7f5ed3d2fe69 paddle::platform::EnforceNotMet::EnforceNotMet()
W0126 11:35:33.454890 23584 init.cc:217]     @     0x7f5ed69ff9e5 paddle::framework::OperatorWithKernel::ChooseKernel()
W0126 11:35:33.456895 23584 init.cc:217]     @     0x7f5ed6a01e2f paddle::framework::OperatorWithKernel::RunImpl()
W0126 11:35:33.459822 23584 init.cc:217]     @     0x7f5ed6a02281 paddle::framework::OperatorWithKernel::RunImpl()
W0126 11:35:33.461359 23584 init.cc:217]     @     0x7f5ed69fb3d0 paddle::framework::OperatorBase::Run()
W0126 11:35:33.463600 23584 init.cc:217]     @     0x7f5ed677fde6 paddle::framework::details::ComputationOpHandle::RunImpl()
W0126 11:35:33.465778 23584 init.cc:217]     @     0x7f5ed6736fa1 paddle::framework::details::FastThreadedSSAGraphExecutor::RunOpSync()
W0126 11:35:33.468096 23584 init.cc:217]     @     0x7f5ed6735d0f paddle::framework::details::FastThreadedSSAGraphExecutor::RunOp()
W0126 11:35:33.468775 23584 init.cc:217]     @     0x7f5ed6735fd4 _ZNSt17_Function_handlerIFvvESt17reference_wrapperISt12_Bind_simpleIFS1_ISt5_BindIFZN6paddle9framework7details28FastThreadedSSAGraphExecutor10RunOpAsyncEPSt13unordered_mapIPNS6_12OpHandleBaseESt6atomicIiESt4hashISA_ESt8equal_toISA_ESaISt4pairIKSA_SC_EEESA_RKSt10shared_ptrINS5_13BlockingQueueImEEEEUlvE_vEEEvEEEE9_M_invokeERKSt9_Any_data
W0126 11:35:33.471302 23584 init.cc:217]     @     0x7f5ed40a7fe3 std::_Function_handler<>::_M_invoke()
W0126 11:35:33.473825 23584 init.cc:217]     @     0x7f5ed3e311a7 std::__future_base::_State_base::_M_do_set()
W0126 11:35:33.474503 23584 init.cc:217]     @     0x7f5fce140907 __pthread_once_slow
W0126 11:35:33.475080 23584 init.cc:217]     @     0x7f5ed67314c2 _ZNSt13__future_base11_Task_stateISt5_BindIFZN6paddle9framework7details28FastThreadedSSAGraphExecutor10RunOpAsyncEPSt13unordered_mapIPNS4_12OpHandleBaseESt6atomicIiESt4hashIS8_ESt8equal_toIS8_ESaISt4pairIKS8_SA_EEES8_RKSt10shared_ptrINS3_13BlockingQueueImEEEEUlvE_vEESaIiEFvvEE6_M_runEv
W0126 11:35:33.477545 23584 init.cc:217]     @     0x7f5ed3e33424 _ZZN10ThreadPoolC1EmENKUlvE_clEv
W0126 11:35:33.478063 23584 init.cc:217]     @     0x7f5f094caa50 (unknown)
W0126 11:35:33.478652 23584 init.cc:217]     @     0x7f5fce1386db start_thread
W0126 11:35:33.479244 23584 init.cc:217]     @     0x7f5fce47171f clone
W0126 11:35:33.479825 23584 init.cc:217]     @                0x0 (unknown)
Traceback (most recent call last):
  File "./utils/finetune_launch.py", line 175, in <module>
    main(lanch_args)
  File "./utils/finetune_launch.py", line 166, in main
    start_procs(args)
  File "./utils/finetune_launch.py", line 137, in start_procs
    cmd=cmds[i])
subprocess.CalledProcessError: Command '['/home/xxx/py27/bin/python', '-u', './run_seq2seq.py', '--use_cuda', 'true', '--do_train', 'true', '--max_seq_len', '512', '--do_val', 'false', '--do_test', 'false', '--do_pred', 'true', '--train_set', '../ernie-gen/data//train.data', '--dev_set', '../ernie-gen/data//train.data', '--test_set', '../ernie-gen/data//', '--pred_set', '../ernie-gen/data//test.data', '--epoch', '2', '--tokenizer', 'FullTokenizer', '--tokenized_input', 'false', '--task_type', 'dialog', '--role_type_size', '2', '--turn_type_size', '10', '--max_src_len', '472', '--max_tgt_len', '40', '--max_dec_len', '32', '--hidden_dropout_prob', '0.1', '--attention_probs_dropout_prob', '-1', '--random_noise', 'false', '--noise_prob', '0.5', '--continuous_position', 'true', '--tgt_type_id', '1', '--batch_size', '2', '--learning_rate', '1e-4', '--lr_scheduler', 'linear_warmup_decay', '--warmup_proportion', '0.1', '--weight_decay', '0.01', '--weight_sharing', 'True', '--label_smooth', '0.0', '--do_decode', 'true', '--beam_size', '5', '--length_penalty', '1.3', '--init_pretraining_params', '../ernie-gen/ernie-1.0/params', '--vocab_path', '../ernie-gen/ernie-1.0/vocab.txt', '--ernie_config_path', '../ernie-gen/ernie-1.0/ernie_config.json', '--checkpoints', 'checkpoints_chitchat', '--save_and_valid_by_epoch', 'true', '--eval_script', 'sh', './eval/tasks/chitchat/eval.sh', '--eval_mertrics', 'bleu_1,bleu_2,distinct_1,distinct_2', '--random_seed', '83919']' returned non-zero exit status -11

**Comment by Joejiong** [comment]
你好，如果是厂内可以在ernie用户群提问，如果是外部，可以到ernie 套件 repo，提问。

**Comment by lonelydancer** [comment]
@Joejiong 最后发现是input_mask的类型不对，应该是fp32.请问如何从这个core信息看出来和这个相关呢。
