### ISSUE TITLE
多batchsize预测问题

### ISSUE THREAD

**Issue by githubchange** [PaddlePaddle/Paddle#30707]
在使用paddle c++预测库时，多batchsize预测遇到问题：
目前ppyolo预测代码：
  ....
  std::vector<float> val(4 * 3 * 608 * 608);
  auto input_names = predictor_->GetInputNames();
  for (const auto& tensor_name : input_names) {
    auto in_tensor = predictor_->GetInputTensor(tensor_name);
    if (tensor_name == "image") {
      int rh = inputs_.eval_im_size_f_[0];
      int rw = inputs_.eval_im_size_f_[1];
      in_tensor->Reshape({ 4, 3, rh, rw });
      in_tensor->copy_from_cpu(val.data());
    }
    else if (tensor_name == "im_size") {
      in_tensor->Reshape({ 4, 2 });
      in_tensor->copy_from_cpu(inputs_.ori_im_size_.data());
    }
    else if (tensor_name == "im_info") {
      in_tensor->Reshape({ 4, 3 });
      in_tensor->copy_from_cpu(inputs_.eval_im_size_f_.data());
    }
    else if (tensor_name == "im_shape") {
      in_tensor->Reshape({ 4, 3 });
      in_tensor->copy_from_cpu(inputs_.ori_im_size_f_.data());
    }
    else if (tensor_name == "scale_factor") {
      in_tensor->Reshape({ 4, 4 });
      in_tensor->copy_from_cpu(inputs_.scale_factor_f_.data());
    }
  }
  ....
  predictor_->ZeroCopyRun();
当执行到predictor_->ZeroCopyRun();时提示错误，"InvalidArgumentError: The 0-th dimension of input[0] and input[1] is expected to be equal.But received input[0]'s shape = [4, 2048, 19, 19], input[1]'s shape = [1, 1, 19, 19].
  [Hint: Expected inputs_dims[0][j] == inputs_dims[i][j], but received inputs_dims[0][j]:4 != inputs_dims[i][j]:1.] (at D:\local\Paddle\paddle/fluid/operators/concat_op.h:63)"，若将batchsize改为1则可以使用。请问还需要修改哪些地方？

**Comment by Joejiong** [comment]
好的，正在查看

**Comment by Joejiong** [comment]
你好，目前pp-yolo模型，还在对齐预测库，由@github.com/Leonardo-Ding 预测同学对接，谢谢

**Comment by githubchange** [comment]
好的，有支持计划表吗
