### ISSUE TITLE
使用高层API构建DNN、LSTM模型Loss跳动太厉害，tensorflow比较稳定，是否参数问题？

### ISSUE THREAD

**Issue by Sunny-wuhan** [PaddlePaddle/Paddle#30701]
- 版本、环境信息：
    1）PaddlePaddle版本：2.0
    2）GPU：AI studio 资源
项目：https://aistudio.baidu.com/aistudio/projectdetail/1467150
![微信截图_20210126164925](https://user-images.githubusercontent.com/53201500/105822024-7e455a80-5ff6-11eb-8015-e76ed5c711c6.png)
tensorflow模拟了LSTM模型，模型的Loss很稳定，每次Batch的loss差不多都是0.7~0.9
模型：
[Desktop.zip](https://github.com/PaddlePaddle/Paddle/files/5872191/Desktop.zip)
![微信截图_20210126165358](https://user-images.githubusercontent.com/53201500/105822498-1b07f800-5ff7-11eb-9e1d-480f43caa9ea.png)

希望大神帮忙看看，非常感谢！
图片显示不了，所以我放到压缩包里了。
[图片.zip](https://github.com/PaddlePaddle/Paddle/files/5872272/default.zip)

**Comment by Joejiong** [comment]
谢谢你的建议

**Comment by Joejiong** [comment]
@LielinJiang 可以帮忙看下吗高层api的问题。

**Comment by Sunny-wuhan** [comment]
开发团队能帮忙看看吗

**Comment by LielinJiang** [comment]
飞桨的loss显示是每个batch的。可以看看tf是不是也是每个batch的。同时也可以检查下超参数，数据，网络等是否又对齐。

**Comment by Sunny-wuhan** [comment]
> 飞桨的loss显示是每个batch的。可以看看tf是不是也是每个batch的。同时也可以检查下超参数，数据，网络等是否又对齐。
tf也是每个batch会显示结果，但是不确定是不是显示的当前batch的结果。

**Comment by Sunny-wuhan** [comment]
> 飞桨的loss显示是每个batch的。可以看看tf是不是也是每个batch的。同时也可以检查下超参数，数据，网络等是否又对齐。

飞桨的loss显示是每个batch的。可以看看tf是不是也是每个batch的。同时也可以检查下超参数，数据，网络等是否又对齐。
tf也是每个batch会在屏幕上更新一下结果，loss比较稳定，但是不确定是不是显示的当前batch的结果。我这边用飞桨和tf测试使用的是同一个数据，网络也基本一样。我这边发现飞桨每次跑的结果差别挺大的，这个是正常的吗？

**Comment by LielinJiang** [comment]
一种简单但不一定有效的方法就是看看结果？训练完后，看看模型的效果是否一致？另一种有难度，但比较可靠的方法是可以保持输入，网络结构以及权重完全一致，看看输出是否一致。如果网络中有随机层先固定住或先去掉。如果这个不一致就有问题。否则也没法很确定的判断。

**Comment by Sunny-wuhan** [comment]
结果不一样，训练完后，tf结果要好一点。第二种我试试，但是飞桨和tf的LSTM不太一样，后者的LSTM是单输出的，输出的数据维度也不一样。我用全连接试试两个模型
