### ISSUE TITLE
GraphPatternDetector intermediate nodes.

### ISSUE THREAD

**Issue by arogowie-intel** [PaddlePaddle/Paddle#30702]
Hi, 

I am detecting following subgraph with GraphPatterDetector:
```
 *            X  (Input)
 *           / \
 *          /   reduce_mean
 *          \   /
 *      elementwise_sub
 *      /           \    2 (input)
 *      |            \  /
 *      |      elementwise_pow 
 *      |             |
 *      |       reduce_mean
 *      |             |     eps (input)
 *      |             |     /
 *      |       elementwise_add
 *      \             |
 *       \           sqrt
 *        \          /
 *         \        /
 *       elementwise_div
 *              |
 (input) gamma  |
 *          \   |
 *       elementwise_mul  
 *              |
  (input) beta  |
 *          \   |
 *       elementwise_add
 *              |
 *            out
 */
```

All the nodes apart the ones marked as "(input)" in above sketch and the output of last `elementwise_add` will be removed from graph. So I thought that I can mark all of the inner nodes as `Role::kIntermediate`. However, this not valid situation as per [`GraphPatternDetector::ValidateByNodeRole`](https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/fluid/framework/ir/graph_pattern_detector.cc#L135-L167) function behavior, to my surprise. Following the logic of this function I see that any `Role::kIntermediate` node can't be adjacent to any other   `Role::kIntermediate` node, but has to be connected with `Role::kInput`, `Role::kOutput` or `Role::kUnknown` node. 

This behavior seem to me a bit nonintuitive. Why `Role::kIntermediate` node can't be next to other node also marked as intermediate? I think that such situation is in line with the comment to [`AsIntermediate`](https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/fluid/framework/ir/graph_pattern_detector.h#L99-L104) function:
https://github.com/PaddlePaddle/Paddle/blob/d834f4e6e86099e5a6d194e5b888ff03cc92d32c/paddle/fluid/framework/ir/graph_pattern_detector.h#L99-L100

**Comment by luotao1** [comment]
@wojtuss @jczaja Could you see this issue at first?
