### ISSUE TITLE
fleetrun不能正确判断fleet.is_first_worker?

### ISSUE THREAD

**Issue by starsblinking** [PaddlePaddle/Paddle#30712]
test_env.py源码如下：

import paddle
import paddle.distributed.fleet.base.role_maker as role_maker
from paddle.distributed.fleet import fleet

paddle.enable_static()
paddle_cloud_role_maker = role_maker.PaddleCloudRoleMaker()
fleet.init(paddle_cloud_role_maker)

if fleet.is_server():
    print("I'm server")
elif fleet.is_worker():
    print("I'm worker")
    if fleet.is_first_worker:
        print("I'm first worker")
    else:
        print("I'm not first worker")

命令行运行 fleetrun --server_num=1 --worker_num=2 test_env.py

日志log/workerlog.1和log/workerlog.0里的内容均为：
I'm worker
I'm first worker

- 版本、环境信息：
    1）PaddlePaddle版本：2.0.0或最新dev版
    2）CPU

**Comment by starsblinking** [comment]
不知道为啥，代码缩紧的空格展示不了，但编辑时又有，有人指导下如何显示空格吗...

**Comment by danleifeng** [comment]
> 不知道为啥，代码缩紧的空格展示不了，但编辑时又有，有人指导下如何显示空格吗...

**Comment by starsblinking** [comment]
多谢fleet同学～is_first_worker后面需要加上括号
