### ISSUE TITLE
两个仓库的docker images更新时间不同步

### ISSUE THREAD

**Issue by llxxxll** [PaddlePaddle/Paddle#3072]
| REPOSITORY | TAG | IMAGE ID | CREATED | SIZE |
| ------ | ------ | ------ | ------ | ------ |
| paddlepaddle/paddle | latest-gpu | 33976fa7c783 | 5 hours ago | 1.96GB |
| docker.paddlepaddle.org/paddle | latest-gpu | 23673bcd47a6 | 7 weeks ago | 1.6GB |

docker.paddlepaddle.org 下的镜像是 7 weeks ago，可能同步这里出了问题？

**Comment by helinwang** [comment]
@llxxxll 我刚刚设定好TeamCity CI，paddle和book都会自动推到docker.paddlepaddle.org和paddlepaddle。自己查了一下也一致了。请核实：）

**Comment by typhoonzero** [comment]
目前已经是同步更新了，关闭此issue。
