### ISSUE TITLE
linux 集群 安装错误：安装没有报错，导入模块出问题

### ISSUE THREAD

**Issue by FightingFighting** [PaddlePaddle/Paddle#30739]
- 版本、环境信息：
    1）PaddlePaddle版本：1.8.5
    3）GPU：CUDA：10.0.130， CUDNN：7.6.3
    4）系统环境：Linux、Python版本：2.7

- 安装方式信息：
1）pip安装

- 问题描述：请详细描述您的问题，同步贴出报错信息、日志/代码关键片段
安装的时候没有报错，但是在我验证安装的时候（import paddle.fluid as fluid）却无法导入。得到以下错误：

TensorRT dynamic library (libnvinfer.so) that Paddle depends on is not configured correctly. (error code is libnvinfer.so: cannot open shared object file: No such file or directory)
  Suggestions:
  1. Check if TensorRT is installed correctly and its version is matched with paddlepaddle you installed.
  2. Configure TensorRT dynamic library environment variables as follows:
  - Linux: set LD_LIBRARY_PATH by `export LD_LIBRARY_PATH=...`
  - Windows: set PATH by `set PATH=XXX;>>>

**Comment by zhwesky2010** [comment]
@FightingFighting 您好，麻烦用 `find / -name libnvinfer.so` 在根目录下查找下这个libnvinfer.so，报错是说找不到这个动态库文件

**Comment by zhouxiang93123** [comment]
请看这个https://github.com/PaddlePaddle/Paddle/issues/28218
应该是不影响使用的

**Comment by zhwesky2010** [comment]
@FightingFighting 你这个是warning信息吗？如果是warning信息就是没有影响的

**Comment by FightingFighting** [comment]
@zhouxiang93123 @zhouwei25 是我自己的锅，我没有手动导入cuda和cudnn，之前我以为安装成功了，就证明是有cudnn和cuda的，感谢了

**Comment by zhwesky2010** [comment]
@@FightingFighting 这个是warning信息吗

**Comment by FightingFighting** [comment]
@zhouwei25 不知道，得的就是我贴出来的东西，也没说是不是warning

**Comment by zhouxiang93123** [comment]
@zhouwei25 我也遇到这个问题了，确实看不出是error还是warning信息，但是目前不影响使用
