### ISSUE TITLE
c++预测API（AnalysisPredictor）预测时，如何指定使用VGG19推理模型中的conv5_4层？如果才能使预测结果维度为512（512个float）？

### ISSUE THREAD

**Issue by GreenValue** [PaddlePaddle/Paddle#30734]
- 版本、环境信息：

1）PaddlePaddle版本：1.8.5
2）系统环境：nvidia_docker 1.8.5-gpu-cuda10.0-cudnn7
3）C++预测库：fluid_inference_c_install_dir# cat version.txt
GIT COMMIT ID:
WITH_MKL: OFF
WITH_MKLDNN: OFF
WITH_GPU: ON
CUDA version: 10.0
CUDNN version: v7.6
CXX compiler version: 4.8.5
WITH_TENSORRT: ON
TensorRT version: v6
4）推理模型文件：https://paddle-lite.readthedocs.io/zh/latest/introduction/support_model_list.html
5）预测样列来源：https://paddle-inference-dist.bj.bcebos.com/tensorrt_test/paddle_inference_sample_v1.7.tar.gz
![image](https://user-images.githubusercontent.com/16701660/105989682-6cd67e00-60dc-11eb-912e-c58e698af3a8.png)
解压后有params,model，但看不懂里面的内容，记事本打开，显示乱码。

>   // get the output
  std::vector<float> out_data;
  auto output_names = predictor->GetOutputNames();
  auto output_t = predictor->GetOutputTensor(output_names[0]);
  std::vector<int> output_shape = output_t->shape();
  int out_num = std::accumulate(output_shape.begin(), output_shape.end(), 1, std::multiplies<int>());
  out_data.resize(out_num);
  output_t->copy_to_cpu(out_data.data());
  for (size_t j = 0; j < out_num; ++j) { 
    LOG(INFO) << "output[" << j << "]: " << out_data[j];
  }
 
![image](https://user-images.githubusercontent.com/16701660/105989286-ddc96600-60db-11eb-8bc0-2cd5f2470f88.png)
实际运行结果，output[999]说明out_num为1000，也就是维度时1000.
但用caffe预测的结果为512维。

**Comment by GreenValue** [comment]
- 运行的log如下
root@ppress-202012:/paddle/sample/inference/build# ./mobilenet_test 
WARNING: Logging before InitGoogleLogging() is written to STDERR
I0127 12:33:19.593107 25038 analysis_predictor.cc:138] Profiler is deactivated, and no profiling report will be generated.
I0127 12:33:19.627172 25038 op_compatible_info.cc:201] The default operator required version is missing. Please update the model version.
I0127 12:33:19.627538 25038 analysis_predictor.cc:902] MODEL VERSION: 0.0.0
I0127 12:33:19.627720 25038 analysis_predictor.cc:904] PREDICTOR VERSION: 0.0.0
W0127 12:33:19.627903 25038 analysis_predictor.cc:917]  - Version incompatible (1) conv2d
W0127 12:33:19.628079 25038 analysis_predictor.cc:917]  - Version incompatible (1) dropout
W0127 12:33:19.628266 25038 analysis_predictor.cc:917]  - Version incompatible (1) elementwise_add
W0127 12:33:19.628429 25038 analysis_predictor.cc:917]  - Version incompatible (1) feed
W0127 12:33:19.628603 25038 analysis_predictor.cc:917]  - Version incompatible (1) fetch
W0127 12:33:19.628770 25038 analysis_predictor.cc:917]  - Version incompatible (1) mul
W0127 12:33:19.628932 25038 analysis_predictor.cc:917]  - Version incompatible (1) pool2d
W0127 12:33:19.629099 25038 analysis_predictor.cc:917]  - Version incompatible (1) relu
W0127 12:33:19.629278 25038 analysis_predictor.cc:917]  - Version incompatible (1) scale
W0127 12:33:19.629443 25038 analysis_predictor.cc:917]  - Version incompatible (1) softmax
W0127 12:33:19.629611 25038 analysis_predictor.cc:194] WARNING: Results may be DIFF! Please use the corresponding version of the model and prediction library, and do not use the develop branch.
--- Running analysis [ir_graph_build_pass]
--- Running analysis [ir_graph_clean_pass]
--- Running analysis [ir_analysis_pass]
--- Running IR pass [simplify_with_basic_ops_pass]
--- Running IR pass [attention_lstm_fuse_pass]
--- Running IR pass [seqconv_eltadd_relu_fuse_pass]
--- Running IR pass [seqpool_cvm_concat_fuse_pass]
--- Running IR pass [fc_lstm_fuse_pass]
--- Running IR pass [mul_lstm_fuse_pass]
--- Running IR pass [fc_gru_fuse_pass]
--- Running IR pass [mul_gru_fuse_pass]
--- Running IR pass [seq_concat_fc_fuse_pass]
--- Running IR pass [fc_fuse_pass]
I0127 12:33:19.829233 25038 graph_pattern_detector.cc:101] ---  detected 2 subgraphs
I0127 12:33:20.144500 25038 graph_pattern_detector.cc:101] ---  detected 1 subgraphs
--- Running IR pass [repeated_fc_relu_fuse_pass]
--- Running IR pass [squared_mat_sub_fuse_pass]
--- Running IR pass [conv_bn_fuse_pass]
--- Running IR pass [conv_eltwiseadd_bn_fuse_pass]
--- Running IR pass [conv_transpose_bn_fuse_pass]
--- Running IR pass [conv_transpose_eltwiseadd_bn_fuse_pass]
--- Running IR pass [is_test_pass]
--- Running IR pass [runtime_context_cache_pass]
--- Running analysis [ir_params_sync_among_devices_pass]
--- Running analysis [adjust_cudnn_workspace_size_pass]
--- Running analysis [inference_op_replace_pass]
--- Running analysis [ir_graph_to_program_pass]
I0127 12:33:20.153321 25038 analysis_predictor.cc:508] ======= optimize end =======
I0127 12:33:20.153348 25038 naive_executor.cc:95] ---  skip [feed], feed -> image
I0127 12:33:20.153659 25038 naive_executor.cc:95] ---  skip [save_infer_model/scale_0], fetch -> fetch
WARNING: Logging before InitGoogleLogging() is written to STDERR
I0127 12:33:20.153698 25038 file_helper.hpp:1202] read_one_file_to_string start,  file:/paddle/test_img/1.floatdat
I0127 12:33:20.153879 25038 file_helper.hpp:1236] read_one_file_to_string finish, file:/paddle/test_img/1.floatdat
I0127 12:33:20.153887 25038 mobilenet_test.cc:64] test_map_cnn cost:0 milisec
I0127 12:33:20.153892 25038 mobilenet_test.cc:66] test_map_cnn cost:0 milisec
I0127 12:33:20.153896 25038 mobilenet_test.cc:68] test_map_cnn cost:0 milisec
I0127 12:33:20.154114 25038 mobilenet_test.cc:70] test_map_cnn cost:0 milisec
batch: 1 predict cost: 1524.87ms
I0127 12:33:21.679040 25038 mobilenet_test.cc:91] output[0]: 0
I0127 12:33:21.679054 25038 mobilenet_test.cc:91] output[1]: 8.91344e-25
... 省略996行...
I0127 12:33:21.682567 25038 mobilenet_test.cc:91] output[998]: 2.88156e-32
I0127 12:33:21.682570 25038 mobilenet_test.cc:91] output[999]: 4.30811e-30

**Comment by TeslaZhao** [comment]
您好，这个阶段是不能手动改组网中某一层维度，需要重新组网，训练模型才行。

**Comment by GreenValue** [comment]
我用caffe抽特征（预测）时，可以指定获取某个层（如conv5_4）的featuremap，然后从featuremap中获取预测结果值（float值）。
但是paddle-inference 的AnalysisPredictor，怎么获取featuremap？

**Comment by TeslaZhao** [comment]
了解，AnalysisPredictor是无法拿到featuremap的

**Comment by GreenValue** [comment]
训练模型，是参照这里吗？
[https://www.paddlepaddle.org.cn/modelbasedetail/vgg](url)
class_dim就是预测值的维度吗？
![image](https://user-images.githubusercontent.com/16701660/106133029-ad4b0000-619f-11eb-84ad-714be38598bb.png)

VGG19_pretrained，从这里下载[https://paddle-imagenet-models-name.bj.bcebos.com/VGG19_pretrained.tar](url) 
然后参数pretrained_model:设置为下载VGG19_pretrained的文件夹路径，就可训练了吗？

**Comment by GreenValue** [comment]
> 了解，AnalysisPredictor是无法拿到featuremap的

能拿到featuremap的predictor，有没有？

**Comment by GreenValue** [comment]
> 了解，AnalysisPredictor是无法拿到featuremap的

能拿到某个卷积层的featuremap的predictor，有没有？

**Comment by TeslaZhao** [comment]
> > 了解，AnalysisPredictor是无法拿到featuremap的
> 
> 能拿到某个卷积层的featuremap的predictor，有没有？

拿不到的

**Comment by TeslaZhao** [comment]
> 训练模型，是参照这里吗？
> [https://www.paddlepaddle.org.cn/modelbasedetail/vgg](url)
> class_dim就是预测值的维度吗？
> ![image](https://user-images.githubusercontent.com/16701660/106133029-ad4b0000-619f-11eb-84ad-714be38598bb.png)
> 
> VGG19_pretrained，从这里下载[https://paddle-imagenet-models-name.bj.bcebos.com/VGG19_pretrained.tar](url)
> 然后参数pretrained_model:设置为下载VGG19_pretrained的文件夹路径，就可训练了吗？

您先验证下这个模型和您之前的模型是不是一致的，如果是的话，改class_dim就好

**Comment by GreenValue** [comment]
> > > 了解，AnalysisPredictor是无法拿到featuremap的
> > 
> > 
> > 能拿到某个卷积层的featuremap的predictor，有没有？
> 
> 拿不到的

caffe可以拿到featuremap。 paddle inferenct predictor 却拿不到featuremap。
paddle处理中也有featuremap，只是没有拿featuremap的接口？
还是paddle处理中根本就没有featuremap，完全不一样的流程？

**Comment by TeslaZhao** [comment]
有featuremap，不对外暴露。和caffe的设计和流程不同

**Comment by GreenValue** [comment]
后续框架会升级能拿到featuremap吗？

**Comment by GreenValue** [comment]
因为featuremap是神经网络的核心部件。

**Comment by TeslaZhao** [comment]
好的，我向产品和研发同学反馈一下。

**Comment by GreenValue** [comment]
@TeslaZhao 
AnalysisPredictor现在能拿到featuremap吗？
paddle_clas的Python 预测推理 已经可提取特征了。[3. 特征提取模型推理](https://github.com/PaddlePaddle/PaddleClas/blob/release/2.3/docs/zh_CN/inference_deployment/python_deploy.md#3)
c++还不行吗？
