### ISSUE TITLE
Prepare GRU demo and doc

### ISSUE THREAD

**Issue by lidanqing-vv** [PaddlePaddle/Paddle#30731]
@lidanqing-intel  Prepare GRU doc and demo, and move BF16 and Ernie doc to Paddle-inference

**Comment by TeslaZhao** [comment]
@lidanqing-intel  Are you reminding yourself?

**Comment by lidanqing-vv** [comment]
Done. https://github.com/PaddlePaddle/Paddle-Inference-Demo/pull/148 is merged.
