### ISSUE TITLE
多机多卡问题https://www.paddlepaddle.org.cn/tutorials/projectdetail/479613

### ISSUE THREAD

**Issue by paulpaul91** [PaddlePaddle/Paddle#30737]
https://www.paddlepaddle.org.cn/tutorials/projectdetail/479613
使用多机多卡疑问，我现在单机上使用paddle.distributed.launch，被使用的每张卡都会单独开一个进程？
![image](https://user-images.githubusercontent.com/22076188/106025042-5abc0600-6103-11eb-9156-763af08479e4.png)

**Comment by zhwesky2010** [comment]
@paulpaul91   对的，每张卡都会对应一个python进程，各自计算梯度，最后把不同卡上的梯度进行聚合操作
