### ISSUE TITLE
Lower accuracy for the quantized mobilenetV1 and mobilenetV2 models.

### ISSUE THREAD

**Issue by pmajchrzak** [PaddlePaddle/Paddle#30735]
Lower accuracy for the quantized mobilenetV1 and mobilenetV2 models.
recorded decrease:
```
                WAS         IS
mobilenetV1     0.7078      0.7068
mobilenetV2     0.7225      0.7208

```
was caused by PR:       
```
        SHA: 8e3a294045e826994d1d88494d6dfeb5a916415e
descryption: skip quantizing ops in cpu inference
     author: cc <52520497+juncaipeng@users.noreply.github.com>

```
command used:
`OMP_NUM_THREADS=28 FLAGS_use_mkldnn=true  python /repos/paddle_paddle/python/paddle/fluid/contrib/slim/tests/quant2_int8_image_classification_comparison.py  --infer_data=/data/PaddlePaddle/1G/imagenet/val.bin --quant_model=/data/PaddlePaddle/trained_models/QAT_models/mobilenetv1/mobilenetv1_quant --batch_num=0  --acc_diff_threshold=0.02  --batch_size=50 `

**Comment by juncaipeng** [comment]
@lidanqing-intel  @pmajchrzak  The test model is generated by PaddleSlim a long time ago, and the PR skips quantizing all the conv and fc ops. For the new quantized model, the PR will not have the problem. In conclusion,  it is not necessary to consider the old quantized model and the quantized model doesn't have accuracy drop.
