### ISSUE TITLE
请问下 fluid.io.save_inference_model，fluid.load/save 和 训练过程中产生的checkpoints，pretrained model和inference model的关系.

### ISSUE THREAD

**Issue by rover5056** [PaddlePaddle/Paddle#30741]
运行环境:
centos
python2
cuda9
paddle1.8.1

我想要把原来的一个101的resnet的checkpoints加载然后去除最后的fc层训练新的模型。现在遇到了一些困惑。。
1.我看到从checkpoints恢复模型使用的  fluid.load 加载的 ppcls.pdparams。这个checkpoint和pretrained model的区别是啥
2.有没有api可以直接从checkpoint转成pretrain model，还是可以直接修剪checkpoints
3.如果要实现修改/剪裁原checkpoint的网络模型，比如最简单的吧最后的fc的class_num 改一下,官方有木有推荐的实现

**Comment by hbwx24** [comment]
1.ppcls.pdparams存储的是模型的参数信息，而不是完整模型。
2.fluid.load 可以直接从checkpoint转成pretrained model。
3.实现方法较多，此处只举一个例子：
    a) 删除pretrained model的fc；
    b) fluid.load 加载checkpoint；
    c) 创建新fc与主体模型进行组合，重训练等。
