### ISSUE TITLE
integer_value_sequence与sparse_binary_vector的区别

### ISSUE THREAD

**Issue by cszhou** [PaddlePaddle/Paddle#3075]
问题1
在05.recommender_system的train.py代码中category_id与movie_title的数据形式应该是一致的，都是有多个nominal的可能值。具体来说就是，category_id对应category_dict中的多个取值，movie_title类似。
但是这两个选择了不同的数据类型integer_value_sequence与sparse_binary_vector，这个有什么区别。如果没有区别的话，在实际中要怎么选择。

```Python
def get_mov_combined_features():
    movie_title_dict = paddle.dataset.movielens.get_movie_title_dict()
    mov_id = paddle.layer.data(
        name='movie_id',
        type=paddle.data_type.integer_value(
            paddle.dataset.movielens.max_movie_id() + 1))
    mov_emb = paddle.layer.embedding(input=mov_id, size=32)
    mov_fc = paddle.layer.fc(input=mov_emb, size=32)

    mov_categories = paddle.layer.data(
        name='category_id',
        type=paddle.data_type.sparse_binary_vector( #Datatype: sparse_binary_vector
            len(paddle.dataset.movielens.movie_categories())))
    mov_categories_hidden = paddle.layer.fc(input=mov_categories, size=32)

    mov_title_id = paddle.layer.data(
        name='movie_title',
        type=paddle.data_type.integer_value_sequence(len(movie_title_dict))) #Datatype: integer_value_sequence
    mov_title_emb = paddle.layer.embedding(input=mov_title_id, size=32)
    mov_title_conv = paddle.networks.sequence_conv_pool(
        input=mov_title_emb, hidden_size=32, context_len=3)
```

问题2
在代码中
```Python
global MOVIE_TITLE_DICT
MOVIE_TITLE_DICT = dict()
for i, w in enumerate(title_word_set):
   MOVIE_TITLE_DICT[w] = i

global CATEGORIES_DICT
CATEGORIES_DICT = dict()
for i, c in enumerate(categories_set):
     CATEGORIES_DICT[c] = i
```
在给出的例子中nominal类型的数据都先建立一个nominal特征的dict用来存储nominal特征的全部可能，假设全部可能为len = length(dict)全集。然后得到每个nomial特征唯一的index。index的取值为[1, index]。
问，是否可以使用简单的hash得到index，而不用经过建dict，找唯一index这个步骤？
再具体的，如果我的nominal特征是user_id，user_id共有100个取值可能，第一个user_id的取值为999，第二个user_id取值为888。这些user_id是否可以直接以下面的形式使用。
```Python
user_id = paddle.layer.data(
        name='user',
        type=paddle.data_type.integer_value(100)) #使用的数据类型是integer_value
```
问题3
在问题2的例子中，使用的数据类型是integer_value，能否使用sparse_binary_vector。区别是什么？

**Comment by jacquesqiao** [comment]
关于这几种数据类型的介绍，请参考： http://doc.paddlepaddle.org/develop/doc_cn/getstarted/concepts/use_concepts_cn.html

**Comment by cszhou** [comment]
你好，谢谢回复。在提issue之前，我看了这个文档。但是还是无法解答我的困惑。在我看来sparse_binary_vector和integer_value_sequence完全就是一样的啊。

**Comment by jacquesqiao** [comment]
关于推荐系统这一章的数据介绍，请参考：http://book.paddlepaddle.org/index.cn.html。稍后给出详细解释

**Comment by qingqing01** [comment]
@cszhou 

## 问题1：

> 在我看来sparse_binary_vector和integer_value_sequence完全就是一样的啊。

假如有2条样本；词典大小为100；第一条样本的词ID为：0 3 5， 第二条样本词ID为：0，10，19；隐层神经元个数为128。

 两者区别：

1.  `sparse_binary_vector` 没有序列信息， 接FC层，属于稀疏连接，
       - FC层的weight的大小为：100 * 128，
       - 经过FC层之后：为2 * 128的输出激活值，对于每一个样本，输入的多个神经元链接到一个神经元。

2. `integer_value_sequence`包含序列信息，一般用在RNN模型中。 后面一般接embedding层，
     - embedding层的weight大小为：100 * 128。
     - 经过embedding层之后为：6 * 128，每个词得到一个词向量。
    -  然后每个样本可以做各种各样的pooling，比如max, average, sum等，得到2 * 128的输出激活值。  而只有sum这种pooling类型和上述`sparse_binary_vector` + `Fc`层才等价。

在实际中如果需要RNN模型(简单的RNN，LSTM, GRU)，或序列卷积等，需要使用`integer_value_sequence`类型。

## 问题2： 

>  index的取值为[1, index]。

更正：index取值为[0, len - 1]

> 再具体的，如果我的nominal特征是user_id，user_id共有100个取值可能，第一个user_id的取值为999，第二个user_id取值为888。这些user_id是否可以直接以下面的形式使用。

这句不是很理解，为什么user_id共有100个取值，而第一个user_id取值为999，第二个为888，为啥要是这样的取值？

## 问题3：

`integer_value`:  一般用来表示label，是个整数值。每个样本的label只有一个整数，一般只作为label用，接入cost层，或者evalutor层。
`sparse_binary_vector`:  可以用来表示输入特征，在程序内部存储为稀疏矩阵，后面可以接入FC层，或者支持稀疏输入的层。

**Comment by cszhou** [comment]
@qingqing01 
感谢回复。这个回复解答了我很多困惑，但依然还有一些困惑不解。
## 问题2
我重新描述问题2。
我现有的数据的user_id并没有编码为从0开始递增到len-1的形式，所以user_id取值范围并不是[0, len-1]。所以问是否有必要进行重新编码为[0, len-1]，还是原始的编码顺序就是可以的。

## 追加一个问题
在推荐系统一章给出的demo中，对于user_id，认为user_id的输入类型是integer_value，后面跟了embedding层；对于movie_id层，做了同样操作。可是这里的user_id与user_id之间并没有构成序列信息，为什么可以使用embedding。
更具体的，在没有user_id与User_id的序列信息下，paddle内部中的embedding是如何实现的？

如果是我对embedding的理解有偏差，请指出。。

再次感谢耐心回复，Thanks。

**Comment by qingqing01** [comment]
@cszhou 

问题2：

```
user_id = paddle.layer.data(
        name='user',
        type=paddle.data_type.integer_value(100)) #使用的数据类型是integer_value
```

需要重新编码到[0, len-1]，上述词典大小为len(=100)，后面接embedding层，需要依据编码的ID，在table中选出对应词的向量。所以编码必须是 [0, len -1]

追加的问题：

注意integer_value只有一个整数值，所以`integer_value + embedding`和`sparse_binary_vector + FC`是等价的。

> 更具体的，在没有user_id与User_id的序列信息下，paddle内部中的embedding是如何实现的？

内部代码叫[`TableProjection`](https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/gserver/layers/TableProjection.cpp#L40)，可以参考实现代码，是从weight中选出若干行。

```
 out_->value->selectRows(*table_->getW(), *in_->ids);
```

**Comment by cszhou** [comment]
@qingqing01 
非常感谢，明白了。

**Comment by cszhou** [comment]
@qingqing01 
```Python
user_id = paddle.layer.data(
        name = "user_id",type=paddle.data_type.integer_value(21428336))
user_fc = paddle.layer.fc(input=user_id, size=32)
```
这种写法报错，Check failed: input.value The input of 'fc' layer must be matrix
Mon Aug  7 11:40:50 2017[1,0]<stderr>:*** Check failure stack trace: ***
原因是？必须要先将integer_value类型变成embedding类型，然后才能接fc？

**Comment by reyoung** [comment]
最开始的问题已经回答，如果有新的问题请开新的issue

> 必须要先将integer_value类型变成embedding类型，然后才能接fc？
是
