### ISSUE TITLE
源码请教

### ISSUE THREAD

**Issue by BelongAl** [PaddlePaddle/Paddle#30759]
在paddle/fluid/framework/ir/subgraph_detector.cc 这个目录下有这个函数，它在①，②处把所有的node都排除了；这个函数的是做什么用的呢？或着是我看错了？求助!

```
void FilterRedundantOutputOfSubGraph(Graph *graph) {
  std::vector<Node *> op_nodes;
  for (auto &node : TopologicalSort(*graph)) {
    if (node.IsVar() || Agent(&node).deleted()) { **①**
      continue;
    }
    op_nodes.push_back(&node); 
  }
  size_t op_num = op_nodes.size();
  for (size_t i = 0; i < op_num; i++) {
    if (op_nodes[i]->IsOp()) continue;  **②**
    std::unordered_set<std::string> follow_up_input_names;
    for (size_t j = i + 1; j < op_num; j++) {
      for (auto *in : op_nodes[j]->inputs) {
        follow_up_input_names.insert(in->Name());
      }
    }
    std::vector<Node *> filtered_subgraph_outlinks;
    for (auto *out : op_nodes[i]->outputs) {
      if (follow_up_input_names.count(out->Name())) {
        filtered_subgraph_outlinks.push_back(out);
      } else {
        Agent(out).set_deleted(true);
      }
    }
    // The filtered_subgraph_outlinks may be empty.
    op_nodes[i]->outputs = filtered_subgraph_outlinks;
  }
}
```

**Comment by Superjomn** [comment]
看起来的确可能之前写错了，这个filter没有生效

**Comment by marsbzp** [comment]
> 在paddle/fluid/framework/ir/subgraph_detector.cc 这个目录下有这个函数，它在①，②处把所有的node都排除了；这个函数的是做什么用的呢？或着是我看错了？求助!
> 
> ```
> void FilterRedundantOutputOfSubGraph(Graph *graph) {
>   std::vector<Node *> op_nodes;
>   for (auto &node : TopologicalSort(*graph)) {
>     if (node.IsVar() || Agent(&node).deleted()) { **①**
>       continue;
>     }
>     op_nodes.push_back(&node); 
>   }
>   size_t op_num = op_nodes.size();
>   for (size_t i = 0; i < op_num; i++) {
>     if (op_nodes[i]->IsOp()) continue;  **②**
>     std::unordered_set<std::string> follow_up_input_names;
>     for (size_t j = i + 1; j < op_num; j++) {
>       for (auto *in : op_nodes[j]->inputs) {
>         follow_up_input_names.insert(in->Name());
>       }
>     }
>     std::vector<Node *> filtered_subgraph_outlinks;
>     for (auto *out : op_nodes[i]->outputs) {
>       if (follow_up_input_names.count(out->Name())) {
>         filtered_subgraph_outlinks.push_back(out);
>       } else {
>         Agent(out).set_deleted(true);
>       }
>     }
>     // The filtered_subgraph_outlinks may be empty.
>     op_nodes[i]->outputs = filtered_subgraph_outlinks;
>   }
> }
> ```
我也在这个函数上卡了很久，才来翻issue
