### ISSUE TITLE
数据生成器里面有个莫名的问题

### ISSUE THREAD

**Issue by minhoooo1** [PaddlePaddle/Paddle#30764]
为使您的问题得到快速解决，在建立Issues前，请您先通过如下方式搜索是否有相似问题:【搜索issue关键字】【使用labels筛选】【官方文档】

如果您没有查询到相似问题，为快速解决您的提问，建立issue时请提供如下细节信息：
- 标题：简洁、精准概括您的问题
- 版本、环境信息：
    1）PaddlePaddle版本：2.0rc
    2）CPU/GPU：CUDA10.0
    3）系统环境：win10
    4）Python3.7.0

 
![微信截图_20210129105733](https://user-images.githubusercontent.com/61350752/106225788-cf389700-6220-11eb-9e57-fa6db7a68926.png) 
截图中代码如果
np.reshape(imgs[i],[1, IMG_ROWS, IMG_COLS])改为
np.reshape(imgs[i],[1, 28, 28]) 则
训练的loss会出现nan

**Comment by haozech** [comment]
你好，可以尝试在np.reshape后打印 img 结果，查看[1, IMG_ROWS, IMG_COLS]改为
[1, 28, 28] 后是否对img结果有影响，以排查问题出在哪一步。
