### ISSUE TITLE
windows10安装错误

### ISSUE THREAD

**Issue by thomas-yanxin** [PaddlePaddle/Paddle#30763]
- 版本、环境信息：
    1）PaddlePaddle版本：paddlepaddle1.8.5-CPU版本
    2）CPU：i5
    3）GPU：无
    4）系统环境：Windows10、Python 3.7
- 安装方式信息：
1）pip安装：执行    python -m pip install paddlepaddle==1.8.5 -i https://mirror.baidu.com/pypi/simple    

- 复现信息：准确按照流程进行安装
- 问题描述：在pip安装完毕后，查看pip list中有paddlepaddle，但使用检查代码检查时却出现如下报错：
- 报错截图：![9$C8A3AVX%C2CQQ599$UO`H](https://user-images.githubusercontent.com/58030051/106172273-97ecca80-61cd-11eb-9532-31f85137bdb3.png)
- 大致报错是：OSError: [WinError 193] %1 不是有效的 Win32 应用程序。

**Comment by haozech** [comment]
你好，可以检查下是否是win32环境？目前官方只支持win64

**Comment by thomas-yanxin** [comment]
您好，已经检查过了，是win64环境，依旧是这个错误。

**Comment by haozech** [comment]
好的，我们已经安排同学排查此问题

**Comment by zhwesky2010** [comment]
@thomas-yanxin 您好，这个问题可能是python是64位的，安装的python scipy是32位的，麻烦python 重装下scipy。再装下 https://www.microsoft.com/en-us/download/details.aspx?id=48145 这个试试

**Comment by thomas-yanxin** [comment]
好的，谢谢您。
