### ISSUE TITLE
使用Paddle2.0分支, 根据官网的cmake编译教程在生成解决方案时出现如下错误 

### ISSUE THREAD

**Issue by Costwen** [PaddlePaddle/Paddle#30786]
1）PaddlePaddle版本：2.0
    2）CPU：intel - i5 8300H
    3）系统环境：win10           

![image](https://user-images.githubusercontent.com/47916831/106311270-d2269c80-629f-11eb-9868-cd1132d78e91.png)

使用的是visual studio 2019

**Comment by chenjiaoAngel** [comment]
报错信息看不到额，图片加载不成功。
能将出错的地方copy贴上去吗

**Comment by Costwen** [comment]
> 报错信息看不到额，图片加载不成功。
> 能将出错的地方copy贴上去吗

正在创建库 D:/Paddle/build/third_party/install/mkldnn/bin/mkldnn.lib 和对象 D:/Paddle/build/third_party/install/mkldnn/bin/mkldnn.exp
    mkldnn.vcxproj -> D:\Paddle\build\Release\libmkldnn.lib
    stringpiece.vcxproj -> D:\Paddle\build\paddle\fluid\string\Release\libstringpiece.lib
    version.vcxproj -> D:\Paddle\build\paddle\fluid\framework\Release\libversion.lib
    imperative_flag.vcxproj -> D:\Paddle\build\paddle\fluid\imperative\Release\libimperative_flag.lib
    activation_functions.vcxproj -> D:\Paddle\build\paddle\fluid\operators\math\detail\Release\libactivation_functions.lib
    string_helper.vcxproj -> D:\Paddle\build\paddle\fluid\string\Release\libstring_helper.lib
    pretty_log.vcxproj -> D:\Paddle\build\paddle\fluid\string\Release\libpretty_log.lib
    monitor.vcxproj -> D:\Paddle\build\paddle\fluid\platform\Release\libmonitor.lib
    ps_gpu_wrapper.vcxproj -> D:\Paddle\build\paddle\fluid\framework\fleet\Release\libps_gpu_wrapper.lib
    timer.vcxproj -> D:\Paddle\build\paddle\fluid\platform\Release\libtimer.lib
    denormal.vcxproj -> D:\Paddle\build\paddle\fluid\platform\Release\libdenormal.lib
    paddle_pass_builder.vcxproj -> D:\Paddle\build\paddle\fluid\inference\api\Release\libpaddle_pass_builder.lib
    imperative_profiler.vcxproj -> D:\Paddle\build\paddle\fluid\imperative\Release\libimperative_profiler.lib
    zero_copy_tensor_dummy.vcxproj -> D:\Paddle\build\paddle\fluid\inference\api\details\Release\libzero_copy_tensor_dummy.lib

全部生成 失败。

**Comment by Costwen** [comment]
> 报错信息看不到额，图片加载不成功。
> 能将出错的地方copy贴上去吗

好像是因为在给build  third party 时 git clone  太慢了 下载不下来

**Comment by chenjiaoAngel** [comment]
建议remove third-party，重新编译试试；
或者下载paddlepaddle 的docker 环境进行编译，https://www.paddlepaddle.org.cn
