### ISSUE TITLE
v2.0.0推理报错

### ISSUE THREAD

**Issue by fassqiu** [PaddlePaddle/Paddle#30782]
环境：
docker:paddlepaddle/paddle:2.0.0-gpu-cuda10.2-cudnn7
opencv4.4
go1.13
paddle版本：origin/release/2.0
[dnnl_lnx_1.8.0_cpu_iomp.tgz](https://github.com/oneapi-src/oneDNN/releases/tag/v1.8.1)
[mklml_lnx_2019.0.5.20190502.tgz](https://github.com/oneapi-src/oneDNN/releases/tag/v0.21)
编译参数：
`
  -DWITH_CONTRIB=OFF \
  -DWITH_MKL=ON  \
  -DWITH_MKLDNN=ON \
  -DWITH_TESTING=OFF \
  -DCMAKE_BUILD_TYPE=Release \
  -DON_INFER=ON \
  -DWITH_PYTHON=OFF \
  -DWITH_XBYAK=ON  \
  -DWITH_AVX=ON  \
  -DWITH_NV_JETSON=OFF  \
  -DWITH_GPU=ON 
`

报错：
`
W0129 19:21:11.812410    60 analysis_predictor.cc:1059] Deprecated. Please use CreatePredictor instead.
terminate called after throwing an instance of 'paddle::platform::EnforceNotMet'
  what():  

--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
0   runtime.asmcgocall
1   _cgo_0f477b794d0b_Cfunc_PD_NewPredictor
2   PD_NewPredictor
3   std::unique_ptr<paddle::PaddlePredictor, std::default_delete<paddle::PaddlePredictor> > paddle::CreatePaddlePredictor<paddle::AnalysisConfig>(paddle::AnalysisConfig const&)
4   std::unique_ptr<paddle::PaddlePredictor, std::default_delete<paddle::PaddlePredictor> > paddle::CreatePaddlePredictor<paddle::AnalysisConfig, (paddle::PaddleEngineKind)2>(paddle::AnalysisConfig const&)
5   paddle::AnalysisPredictor::MkldnnQuantizer::Quantize()
6   paddle::AnalysisPredictor::MkldnnQuantizer::RunWarmup() const
7   paddle::platform::EnforceNotMet::EnforceNotMet(paddle::platform::ErrorSummary const&, char const*, int)
8   paddle::platform::GetCurrentTraceBackString[abi:cxx11]()

----------------------
Error Message Summary:
----------------------
PreconditionNotMetError: Warmup data cannot be NULL in the config.
  [Hint: warmup_data should not be null.] (at /paddle/paddle/fluid/inference/api/mkldnn_quantizer.cc:477)

SIGABRT: abort
PC=0x7fb8215cc438 m=0 sigcode=18446744073709551610

goroutine 0 [idle]:
runtime: unknown pc 0x7fb8215cc438
stack: frame={sp:0x7ffefd3a1228, fp:0x0} stack=[0x7ffefcba28a8,0x7ffefd3a18e0)
00007ffefd3a1128:  0000002100000003  00007ffefd3a0ae8 
00007ffefd3a1138:  0000000000000000  0000000000000000 
00007ffefd3a1148:  0000000000000000  3a3a656c64646170 
00007ffefd3a1158:  6d726f6674616c70  63726f666e453a3a 
00007ffefd3a1168:  0074654d746f4e65  00007ffefd3a1868 
00007ffefd3a1178:  0000000000000000  00007ffefd3a1870 
00007ffefd3a1188:  00007fb7f4346948 <runtime.asmcgocall+104>  0000000000000000 
00007ffefd3a1198:  0000000000000000  0000000000000000 
00007ffefd3a11a8:  00007fb7f43e4430  4000000000000000 
00007ffefd3a11b8:  0000000000000000  0000000000000000 
00007ffefd3a11c8:  0000000000000000  0000000000000000 
00007ffefd3a11d8:  0000000000000000  0000000000000000 
00007ffefd3a11e8:  0000000000000000  0000000000000000 
00007ffefd3a11f8:  00000000034eec70  00007fb82195c700 
00007ffefd3a1208:  0000000003ebb1a0  00007ffefd3a1410 
00007ffefd3a1218:  00007ffefd3a1420  0000000003eb2090 
00007ffefd3a1228: <00007fb8215ce03a  0000000000000020 
00007ffefd3a1238:  0000000000000000  0000000000000000 
00007ffefd3a1248:  0000000000000000  0000000000000000 
00007ffefd3a1258:  0000000000000000  0000000000000000 
00007ffefd3a1268:  0000000000000000  0000000000000000 
00007ffefd3a1278:  0000000000000000  0000000000000000 
00007ffefd3a1288:  0000000000000000  0000000000000000 
00007ffefd3a1298:  0000000000000000  0000000000000000 
00007ffefd3a12a8:  0000000000000000  0000000000000000 
00007ffefd3a12b8:  00007fb82168e3a9  0000000000000000 
00007ffefd3a12c8:  00007fb82160fc0f  00007fb82195c540 
00007ffefd3a12d8:  0000000000000001  0000000000000000 
00007ffefd3a12e8:  00007ffefd3a1410  00007ffefd3a1420 
00007ffefd3a12f8:  00007fb80d02df48  00007fb82195c700 
00007ffefd3a1308:  0000000003ebb1a0  00007ffefd3a1410 
00007ffefd3a1318:  00007ffefd3a1420  0000000003eb2090 
runtime: unknown pc 0x7fb8215cc438
stack: frame={sp:0x7ffefd3a1228, fp:0x0} stack=[0x7ffefcba28a8,0x7ffefd3a18e0)
00007ffefd3a1128:  0000002100000003  00007ffefd3a0ae8 
00007ffefd3a1138:  0000000000000000  0000000000000000 
00007ffefd3a1148:  0000000000000000  3a3a656c64646170 
00007ffefd3a1158:  6d726f6674616c70  63726f666e453a3a 
00007ffefd3a1168:  0074654d746f4e65  00007ffefd3a1868 
00007ffefd3a1178:  0000000000000000  00007ffefd3a1870 
00007ffefd3a1188:  00007fb7f4346948 <runtime.asmcgocall+104>  0000000000000000 
00007ffefd3a1198:  0000000000000000  0000000000000000 
00007ffefd3a11a8:  00007fb7f43e4430  4000000000000000 
00007ffefd3a11b8:  0000000000000000  0000000000000000 
00007ffefd3a11c8:  0000000000000000  0000000000000000 
00007ffefd3a11d8:  0000000000000000  0000000000000000 
00007ffefd3a11e8:  0000000000000000  0000000000000000 
00007ffefd3a11f8:  00000000034eec70  00007fb82195c700 
00007ffefd3a1208:  0000000003ebb1a0  00007ffefd3a1410 
00007ffefd3a1218:  00007ffefd3a1420  0000000003eb2090 
00007ffefd3a1228: <00007fb8215ce03a  0000000000000020 
00007ffefd3a1238:  0000000000000000  0000000000000000 
00007ffefd3a1248:  0000000000000000  0000000000000000 
00007ffefd3a1258:  0000000000000000  0000000000000000 
00007ffefd3a1268:  0000000000000000  0000000000000000 
00007ffefd3a1278:  0000000000000000  0000000000000000 
00007ffefd3a1288:  0000000000000000  0000000000000000 
00007ffefd3a1298:  0000000000000000  0000000000000000 
00007ffefd3a12a8:  0000000000000000  0000000000000000 
00007ffefd3a12b8:  00007fb82168e3a9  0000000000000000 
00007ffefd3a12c8:  00007fb82160fc0f  00007fb82195c540 
00007ffefd3a12d8:  0000000000000001  0000000000000000 
00007ffefd3a12e8:  00007ffefd3a1410  00007ffefd3a1420 
00007ffefd3a12f8:  00007fb80d02df48  00007fb82195c700 
00007ffefd3a1308:  0000000003ebb1a0  00007ffefd3a1410 
00007ffefd3a1318:  00007ffefd3a1420  0000000003eb2090 

goroutine 1 [syscall]:
runtime.cgocall(0x7fb7f43e4430, 0xc0002c7610, 0xf03b00)
	/usr/local/go/src/runtime/cgocall.go:128 +0x61 fp=0xc0002c75e0 sp=0xc0002c75a8 pc=0x7fb7f42f8811
iw_infer/deps/paddle/v2.0.0/gpu/paddle._Cfunc_PD_NewPredictor(0x2dda5d0, 0x0)
	_cgo_gotypes.go:527 +0x4f fp=0xc0002c7610 sp=0xc0002c75e0 pc=0x7fb7f43dc24f
iw_infer/deps/paddle/v2.0.0/gpu/paddle.NewPredictor.func1(0xc00041e008, 0x0)
	/work/deps/paddle/v2.0.0/gpu/paddle/predictor.go:32 +0x60 fp=0xc0002c7650 sp=0xc0002c7610 pc=0x7fb7f43e10b0
iw_infer/deps/paddle/v2.0.0/gpu/paddle.NewPredictor(0xc00041e008, 0xc000422001)
	/work/deps/paddle/v2.0.0/gpu/paddle/predictor.go:32 +0x31 fp=0xc0002c7690 sp=0xc0002c7650 pc=0x7fb7f43ddcb1
plugin/unnamed-684f7a45889020c4b212d268727def61eab69bf6.(*PaddleEngine).Init(0xc0002ec2a0, 0x0, 0x0, 0x0, 0x9601e0, 0xffffffffffffffff)
	/work/infer/modules/paddle/v2.0.0/gpu/paddleEngine.go:57 +0x23c fp=0xc0002c7720 sp=0xc0002c7690 pc=0x7fb7f43e335c
plugin/unnamed-684f7a45889020c4b212d268727def61eab69bf6.(*PaddleEngine).Create(0xc000012510, 0xc000174f50, 0x1, 0x1, 0xc000012510, 0x1, 0x12, 0x60)
	/work/infer/modules/paddle/v2.0.0/gpu/paddleEngine.go:27 +0x71 fp=0xc0002c7768 sp=0xc0002c7720 pc=0x7fb7f43e30a1
plugin/unnamed-48b5258657811c230893fc6484a244b16de5894c.(*CommonInfer).Create(0xc0000b61c0, 0xc0001747a0, 0x1, 0x1, 0x7fb7b52fe3c0, 0xc00000e780, 0xc0000f5850, 0x7fb7b4e10175)
	/work/infer/modules/infer/plaininfer.go:52 +0x17e fp=0xc0002c77e8 sp=0xc0002c7768 pc=0x7fb7b4fbd0ae
iw_infer/infer/core.NewPredictor(0x2, 0x7fb7b5390580, 0xc0000b61c0, 0x0, 0x0, 0x0, 0x979ec0, 0x7fb7b534aa60, 0x8edf01, 0x7fb821f10378)
	/work/infer/core/infer.go:53 +0x144 fp=0xc0002c7860 sp=0xc0002c77e8 pc=0x7fb7b4fbba04
plugin/unnamed-48b5258657811c230893fc6484a244b16de5894c.(*CommonInfer).Init(0xc0000b61c0, 0xc000162000, 0xc0000b61c0, 0x7fb821f10378)
	/work/infer/modules/infer/plaininfer.go:33 +0x114 fp=0xc0002c78c0 sp=0xc0002c7860 pc=0x7fb7b4fbce94
iw_infer/infer/core.registerInfer(0x7fb7b534aa60, 0xc0000b61c0, 0xc000162000, 0x5)
	/work/infer/core/module.go:193 +0xa7 fp=0xc0002c7920 sp=0xc0002c78c0 pc=0x8eed57
iw_infer/infer/core.Register(0xc000162000, 0xc000162000, 0x0)
	/work/infer/core/module.go:390 +0x4d5 fp=0xc0002c7b68 sp=0xc0002c7920 pc=0x8f0a15
iw_infer/infer/core.Register(0xc0000e1de8, 0x94c180, 0xa645e0)
	/work/infer/core/module.go:347 +0x10b fp=0xc0002c7db0 sp=0xc0002c7b68 pc=0x8f064b
main.main()
	/work/infer/main.go:50 +0x2d2 fp=0xc0002c7f60 sp=0xc0002c7db0 pc=0x8fef32
runtime.main()
	/usr/local/go/src/runtime/proc.go:203 +0x206 fp=0xc0002c7fe0 sp=0xc0002c7f60 pc=0x5aed46
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1357 +0x1 fp=0xc0002c7fe8 sp=0xc0002c7fe0 pc=0x5da471

goroutine 6 [chan receive]:
github.com/alecthomas/log4go.(*ConsoleLogWriter).run(0xc00000e3c0, 0xa6d320, 0xc000010018)
	/go/pkg/mod/github.com/alecthomas/log4go@v0.0.0-20180109082532-d146e6b86faa/termlog.go:33 +0xef
created by github.com/alecthomas/log4go.NewConsoleLogWriter
	/go/pkg/mod/github.com/alecthomas/log4go@v0.0.0-20180109082532-d146e6b86faa/termlog.go:26 +0xba

goroutine 7 [chan receive]:
github.com/alecthomas/log4go.(*ConsoleLogWriter).run(0xc00000f8e0, 0xa6d320, 0xc000010018)
	/go/pkg/mod/github.com/alecthomas/log4go@v0.0.0-20180109082532-d146e6b86faa/termlog.go:33 +0xef
created by github.com/alecthomas/log4go.NewConsoleLogWriter
	/go/pkg/mod/github.com/alecthomas/log4go@v0.0.0-20180109082532-d146e6b86faa/termlog.go:26 +0xba

goroutine 72 [chan receive]:
github.com/alecthomas/log4go.(*ConsoleLogWriter).run(0xc00000f240, 0xa6d320, 0xc000010018)
	/go/pkg/mod/github.com/alecthomas/log4go@v0.0.0-20180109082532-d146e6b86faa/termlog.go:33 +0xef
created by github.com/alecthomas/log4go.NewConsoleLogWriter
	/go/pkg/mod/github.com/alecthomas/log4go@v0.0.0-20180109082532-d146e6b86faa/termlog.go:26 +0xca

goroutine 73 [select]:
github.com/alecthomas/log4go.NewFileLogWriter.func1(0xc0000fa000)
	/go/pkg/mod/github.com/alecthomas/log4go@v0.0.0-20180109082532-d146e6b86faa/filelog.go:87 +0x10d
created by github.com/alecthomas/log4go.NewFileLogWriter
	/go/pkg/mod/github.com/alecthomas/log4go@v0.0.0-20180109082532-d146e6b86faa/filelog.go:78 +0x23a

rax    0x0
rbx    0x34eec70
rcx    0x7fb8215cc438
rdx    0x6
rdi    0x3c
rsi    0x3c
rbp    0x7fb82195c700
rsp    0x7ffefd3a1228
r8     0x41
r9     0x7fb821f93700
r10    0x8
r11    0x206
r12    0x3ebb1a0
r13    0x7ffefd3a1410
r14    0x7ffefd3a1420
r15    0x3eb2090
rip    0x7fb8215cc438
rflags 0x206
cs     0x33
fs     0x0
gs     0x0

`

**Comment by haozech** [comment]
你好 能否提供可复现问题的代码呢？

**Comment by fassqiu** [comment]
项目结构：
iw-infer
----deps
--------paddle
------------v2.0.0
----------------gpu
--------------------paddle(common.go,config.go,predictor.go,tensor.go)
--------------------deps(incluide,lib) 都是用paddle origin/release/2.0分支编译出来的，编译参数上面给出来了。

其中common.go,config.go,predictor.go,tensor.go里面改成这样：
`
// #cgo CFLAGS: -I../deps/include

// #cgo LDFLAGS: -L../deps/lib -lpaddle_fluid_c -ldl
`
Init的时候报的错，golang推理代码：
[paddleEngine.txt](https://github.com/PaddlePaddle/Paddle/files/5903564/paddleEngine.txt)
