### ISSUE TITLE
nn.layer.Pool2D

### ISSUE THREAD

**Issue by TWLemontree** [PaddlePaddle/Paddle#30787]
麻烦你们不要随意修改已有的接口otz，求你们了

前天还能跑的代码，今天突然报错说没有 nn.layer.Pool2D，我去查了查文档，发现 Pool2D 只剩下 paddle.fluid.dygraph.Pool2D 了。但是问题来了，文档上明确表示，fluid 未来会移除，我是用它？还是不用它？

给导师展示代码，突然来这一出，孩子人都要被导师骂傻了。

**Comment by chenjiaoAngel** [comment]
请问是哪个版本呢？
另外，fluid.layers.Pool2D 还是支持的，paddle2.0之后主推动态图，建议用nn.Maxpool2D, nn.AvgPool2D这样的API了
