### ISSUE TITLE
paddle1.8.5加载多个模型，相互影响，inputname被改变，pointer err。

### ISSUE THREAD

**Issue by vic-93** [PaddlePaddle/Paddle#30790]
paddle版本：1.8.5
golang：1.14.12
模型A：esmm
模型B：deepfm
case1：加载模型A，再加载模型B ，模型B的inputname被改变   input names: [feat_idx feat_val] >> input names: [field_0 field_0_1] 

case2:加载模型B，再加载模型A，出现error
![image](https://user-images.githubusercontent.com/13634356/106351785-51a48200-6319-11eb-915b-b504f14bcca9.png)

code
```
func GetNewPredictor(model string, flag int) (*PaddlePredictor) {
	PredictorLock.Lock()
	defer PredictorLock.Unlock()
	config := paddle.NewAnalysisConfig()
	path := conf.Conf.Get("path", "model")
	modelPath := util.PlusStr(path, "paddle/", model)
	config.SetModel(modelPath, "")
	// 输出模型路径
	config.DisableGlogInfo()
	config.SwitchUseFeedFetchOps(false)
	config.SwitchSpecifyInputNames(true)
	//config.EnableMemoryOptim()
	predictor := paddle.NewPredictor(config)
	//config.SetInValid()

	fmt.Printf("modelPath: %+v \n", modelPath)
	fmt.Printf("input names: %+v \n", predictor.GetInputNames())

	//inputs := predictor.GetInputTensors()
	//for _, input := range inputs {
	//	fmt.Printf("input.Name() = %+v \n", input.Name())
	//}

	return &PaddlePredictor{predictor: predictor, flag: flag}
}

```

**Comment by chenjiaoAngel** [comment]
理论上，加载多个模型不会出现相互影响的情况；在OCR 里面加载三个模型都没有冲突。可以让他参考下代码。https://github.com/PaddlePaddle/PaddleOCR/tree/develop/deploy/cpp_infer/src

**Comment by chenjiaoAngel** [comment]
加载多个模型不会出现相互影响的情况，在OCR 里面加载三个模型是没有冲突。请参考如下代码：https://github.com/PaddlePaddle/PaddleOCR/tree/develop/deploy/cpp_infer/src进行更正下

**Comment by vic-93** [comment]
@chenjiaoAngel 尝试下Glang的预测库，这边使用的是golang的api  1.8.5

**Comment by Shixiaowei02** [comment]
您好，有关 Golang 的问题我们已经收集，并会在 2.1.0 统一处理。谢谢！

**Comment by vic-93** [comment]
@Shixiaowei02  2.1.0大概会在什么时间发布
