### ISSUE TITLE
基于PaddlePaddle 2.0rc1的自定义数据集的训练得到的模型，应如何保存模型，以被Paddle Lite的opt工具使用。

### ISSUE THREAD

**Issue by liumengbjut** [PaddlePaddle/Paddle#30791]
- 版本、环境信息：
    1）PaddlePaddle版本：2.0 (AI studio导入环境)
    2）Paddle Lite版本：v2.8 (现阶段AI studio导入环境，必要的话源码编译)
实验是基于自定义数据集开展（paddlepaddle开发），希望能够保存模型，进而可以被paddle lite进行压缩量化并完成端侧部署。
问题：
PaddlePaddle的2.0版本的文档关于模型导出描述在https://www.paddlepaddle.org.cn/documentation/docs/zh/guides/02_paddle2.0_develop/08_model_save_load_cn.html
<img width="773" alt="截屏2021-01-30 下午4 30 13" src="https://user-images.githubusercontent.com/18281699/106351712-b14e5d80-6318-11eb-8096-c82d41c6095a.png">

看上去该版本推荐的保存方式为动态图方式，例如
# save
paddle.save(layer.state_dict(), "linear_net.pdparams")
paddle.save(adam.state_dict(), "adam.pdopt")

但是，通过查阅paddle lite的opt工具文档，
<img width="1174" alt="截屏2021-01-30 下午4 51 17" src="https://user-images.githubusercontent.com/18281699/106352081-6aae3280-631b-11eb-814c-16b82dadbf7e.png">
<img width="932" alt="截屏2021-01-30 下午4 52 35" src="https://user-images.githubusercontent.com/18281699/106352103-94675980-631b-11eb-9277-a34cbe850e9c.png">
看上去还是静态图存储方式的模型文件。

请问，针对我的使用场景，推荐哪种模型存储方式呢（在paddlepaddle那边）？

**Comment by chenjiaoAngel** [comment]
Paddle-lite 2.8版本是支持动态图，它会将动态图转为的静态图进行预测
Paddle-lite 2.7版本不支持动态图预测
