### ISSUE TITLE
训练时报错——找不到图片文件

### ISSUE THREAD

**Issue by pinkDOUDOU** [PaddlePaddle/Paddle#30792]
我在ai studio上已经将数据集导入，但是在训练时提示FileNotFoundError: [Errno 2] No such file or directory: './strawberry_3_train/45.jpg

**Comment by CAU-tractor** [comment]
https://aistudio.baidu.com/aistudio/projectdetail/1287222

**Comment by pinkDOUDOU** [comment]
https://aistudio.baidu.com/bjcpu/user/538387/1287222/notebooks/1287222.ipynb

**Comment by chenjiaoAngel** [comment]
这个图片有一并下载下来吗？

**Comment by chenjiaoAngel** [comment]
另外可以在工程目录下看看：'./strawberry_3_train/45.jpg 是否存在这个文件

**Comment by pinkDOUDOU** [comment]
> 另外可以在工程目录下看看：'./strawberry_3_train/45.jpg 是否存在这个文件

你好，我将项目公开了，希望您可以帮忙看一下好吗，问题还是没有解决
项目地址是：https://aistudio.baidu.com/aistudio/projectdetail/1287222

**Comment by chenjiaoAngel** [comment]
<img width="706" alt="image" src="https://user-images.githubusercontent.com/38650344/107001279-53ac8c00-67c4-11eb-8365-73b584ba1e37.png">
路径解压后，是否在目录下能找到这个文件呢？我担心解压不对
报错地方显示，reader 读取时，找不到文件
