### ISSUE TITLE
静态图模型内部增加py_func写的op,  C++预测的时候是不是不能加载？ 求指教

### ISSUE THREAD

**Issue by wangsiji** [PaddlePaddle/Paddle#30803]
会报错
----------------------
Error Message Summary:
----------------------
Error: Operator py_func has not been registered
  [Hint: op_info_ptr should not be null.] at (/home/scmbuild/workspaces_cluster.dev/baidu.lib.paddlepaddle/baidu/lib/paddlepaddle/Paddle/paddle/fluid/framework/op_info.h:113)

**Comment by qili93** [comment]
请问这个py_func的OP是你自己自定义的OP吗？

**Comment by wangsiji** [comment]
> 请问这个py_func的OP是你自己自定义的OP吗？



> 请问这个py_func的OP是你自己自定义的OP吗？
是的，我自己定义的python端的op , 参考的这个文档 https://www.paddlepaddle.org.cn/documentation/docs/zh/1.8/advanced_guide/addon_development/new_op/new_python_op.html 

模型训练没有问题

**Comment by qili93** [comment]
当前C++预测没有办法识别自定义的python op。
