### ISSUE TITLE
严重内存泄漏：PaddlePaddle2.0，CUDA 版本11.0

### ISSUE THREAD

**Issue by HerbertLi2020** [PaddlePaddle/Paddle#30805]
1）PaddlePaddle版本：2.0.0.post110
2）CPU：i7
3）GPU：GTX2070 / CUDA11.0
4）系统环境：Windows, Python版本3.8

PaddlePaddle2.0，CUDA 版本11.0，使用预训练模型deeplabv3p_xception65_humanseg进行抠图操作，有CPU内存泄漏，扣一张图看不出来，扣多图(例如视频的帧)时，占用内存一直在增加，直到本崩溃。
原因应该是paddlepaddle-gpu==2.0.0.post110，的某一模块没有释放内存。
CUDA10.2等低版本都是好的。
麻烦开发团队解决。如想复现问题可以联系我。

测试代码如下：
import os, cv2
import paddlehub as hub
os.environ['CUDA_VISIBLE_DEVICES'] = '0'
humanseg = hub.Module(name = 'deeplabv3p_xception65_humanseg')
jpg_path = "c:\\kt\\jpg\\"  # 文件目录
files = [jpg_path + i for i in os.listdir(jpg_path)]  # 获取文件列表
img_list=list()
for file in files:
    img=cv2.imread(file)
    img_list.append(img)
for i in range(300):
    results = humanseg.segmentation(images = img_list,
                                batch_size = 1,
                                use_gpu = True,
                                visualization = False,
                                output_dir = "")

**Comment by phlrain** [comment]
请问下是机器内存爆掉了，还是gpu的显存爆掉了

**Comment by HerbertLi2020** [comment]
是CPU内存，每抠图一次，就增加占用，没有释放，不断累加，直至爆掉。
看windows的资源管理器就能看出来。

**Comment by jiweibo** [comment]
<img width="998" alt="95e97c747c90b13922ee044954623783" src="https://user-images.githubusercontent.com/26377421/106423961-5e9dae80-649c-11eb-922d-42890351e09b.png">

**Comment by phlrain** [comment]
目前我们的测试的发现，cudnn 8 本身存在一些memory leak，我们先排查下是否是由 cudnn8这个问题引起的， 排查完在这里同步下这个问题，能否帮忙提供下复现流程和步骤，主要是使用的图片数据如何构建

如果着急使用，建议先使用下cudnn 7版本

**Comment by raindrops2sea** [comment]
> 目前我们的测试的发现，cudnn 8 本身存在一些memory leak，我们先排查下是否是由 cudnn8这个问题引起的， 排查完在这里同步下这个问题，能否帮忙提供下复现流程和步骤，主要是使用的图片数据如何构建
> 
> 如果着急使用，建议先使用下cudnn 7版本

是的。
@HerbertLi2020 我们初步分析来看，很可能是命中了之前发现的CUDA11下cudnn 8.0.x的已知问题（具体见[release Note ](https://github.com/PaddlePaddle/Paddle/releases/tag/v2.0.0)已知问题部分的说明），在预测阶段触发内存泄露。对于此问题，我们计划在下一个小版本想办法做一下规避处理。同时也在等待cudnn本身最终的修复。
我们会进一步具体复现分析下您遇到的这个问题，确认一下前面的判断。
对此给您带来的不便表示歉意。非常感谢您的反馈！

**Comment by HerbertLi2020** [comment]
cudnn 7是好用的，一直在用。
复现问题很容易：
1、用CUDA11.0/CUDNN8.04的几个DLL；
2、使用paddlepaddle-gpu==2.0.0.post110，Puddlehub最新版本；
3、图片随便用哪个都行，循环执行抠图即可；
4、用上面的测试代码就可以复现。查看Windows任务管理器的Python的CPU内存占用，就能发现。

**Comment by haoyuying** [comment]
同学您好，根据我们对该问题的复现和排查，确定该问题是CUDA11下cudnn 8.0.x自身存在bug，会导致部分模型在预测阶段触发内存泄漏。我们已经通过禁用部分算子融合的方式，对该问题进行了规避，并在paddlehub上更新了deeplabv3p_xception65_humanseg 1.1.2版本，修复了您出现的问题，请更新deeplabv3p_xception65_humanseg模型。更新方式：
```
hub install deeplabv3p_xception65_humanseg==1.1.2
```

**Comment by HerbertLi2020** [comment]
测试了一下，内存没有任何泄露了，完美解决了问题。
非常感谢百度Paddle团队的敬业、高效！

祝你们春节快乐、万事如意。

**Comment by HerbertLi2020** [comment]
Sorry，忘了说了，humanseg_mobile模型也有同样的问题，能否也更新一下？
https://www.paddlepaddle.org.cn/hubdetail?name=humanseg_mobile&en_category=ImageSegmentation

humanseg_mobile轻量级，扣视频很好用。

**Comment by HerbertLi2020** [comment]
模型humanseg_mobile的CuDNN8.0.4内存泄漏问题，我自己解决了。
---------------------------------------------------------------------
参考：deeplabv3p_xception65_humanseg 1.1.2，改了一下humanseg_mobile的module.py, 内存泄漏规避了：
修改之处：
if paddle.get_cudnn_version() == 8004:
    gpu_config.delete_pass('conv_elementwise_add_act_fuse_pass')
    gpu_config.delete_pass('conv_elementwise_add2_act_fuse_pass')

**Comment by haoyuying** [comment]
同学您好，人像分割模型humanseg_server, humanseg_lite, humanseg_mobile及deeplabv3p_xception65_humanseg的内存泄露问题均已在最新版本修复。感谢您将问题及时准确的反馈给我们，欢迎体验更多hub模型。
