### ISSUE TITLE
Unknown CMake command "add_style_check_target".

### ISSUE THREAD

**Issue by fty8788** [PaddlePaddle/Paddle#3081]
在Paddle/paddle/capi下cmake . 出错：
CMake Error at CMakeLists.txt:26 (add_style_check_target):
  Unknown CMake command "add_style_check_target".

CMake Warning (dev) in CMakeLists.txt:
  No cmake_minimum_required command is present.  A line of code such as

    cmake_minimum_required(VERSION 3.2)

  should be added at the top of the file.  The version specified may be lower
  if you wish to support older CMake versions for this project.  For more
  information run "cmake --help-policy CMP0000".
This warning is for project developers.  Use -Wno-dev to suppress it.

**Comment by kuke** [comment]
This problem has been solved by following the suggestion that build Paddle with option ```WITH_C_API=ON```
