### ISSUE TITLE
 使用多卡训练模型报错 Paddle internal Check failed.

### ISSUE THREAD

**Issue by topxxuki** [PaddlePaddle/Paddle#30816]
paddle版本1.6
T4卡：
CUDA Capability: 75, Driver API Version: 10.1, Runtime API Version: 10.0
cuDNN Version: 7.6.
python 3.6
使用的模型：PaddleDetection
报错信息
![image](https://user-images.githubusercontent.com/18697846/106453471-58bbc380-64c4-11eb-8433-201524c95e17.png)

![image](https://user-images.githubusercontent.com/18697846/106453378-3164f680-64c4-11eb-9c6d-41caa17308cd.png)

**Comment by qili93** [comment]
请问您使用的PaddleDetection的版本是什么呢？Paddle 1.6是如何安装的，运行以下命令是否有问题？
python -c "import paddle.fluid as fluid;fluid.install_check.run_check()"

**Comment by topxxuki** [comment]
![image](https://user-images.githubusercontent.com/18697846/106569560-a93c2b00-656f-11eb-8736-8c4fab85053f.png)


> 请问您使用的PaddleDetection的版本是什么呢？Paddle 1.6是如何安装的，运行以下命令是否有问题？
> python -c "import paddle.fluid as fluid;fluid.install_check.run_check()"

执行起来有问题

下载方式  $CONDA_DIR/bin/pip install --no-cache-dir -i https://pypi.tuna.tsinghua.edu.cn/simple/ paddlepaddle_gpu==1.6.3.post97 \

**Comment by topxxuki** [comment]
![image](https://user-images.githubusercontent.com/18697846/106571215-d8539c00-6571-11eb-9af5-9de1957591b0.png) 报错提示只有看起来有3块卡，但实际上只分配了2张卡;分配4张卡时，报错信息也是一致的

**Comment by T8T9** [comment]
看起来是 nccl 库加载失败了，请按照
![image](https://user-images.githubusercontent.com/62922815/106575262-db04c000-6576-11eb-8b61-1a13c47d1120.png)

排查一下先。确认一下是不是主机环境问题导致的。
