### ISSUE TITLE
nightly build版本的安装BUG

### ISSUE THREAD

**Issue by starsblinking** [PaddlePaddle/Paddle#30826]
按照 https://www.paddlepaddle.org.cn/install/quick?docurl=/documentation/docs/zh/develop/install/pip/linux-pip.html 中的命令来按照: python -m pip install --pre paddlepaddle -f https://paddlepaddle.org.cn/whl/develop.html 则感觉实际安装的版本好像有点滞后，缺少了昨天的很多commit
查了下 https://paddlepaddle.org.cn/whl/develop.html 里有四个链接的标题均为“paddlepaddle-2.1.0.dev0-cp38-cp38-linux_x86_64.whl”，但指向的地址不同，请问他们是否有版本的差异? https://paddle-wheel.bj.bcebos.com/0.0.0-cpu-openblas/paddlepaddle-2.1.0.dev0-cp38-cp38-linux_x86_64.whl 与 https://paddle-wheel.bj.bcebos.com/develop-cpu-openblas/paddlepaddle-2.1.0.dev0-cp38-cp38-linux_x86_64.whl 有什么不同？这个安装包是每天啥时候生成的啊

**Comment by starsblinking** [comment]
看起来， 地址形如 0.0.0-cpu-openblas 的链接是错误的旧版本,  develop-cpu-openblas 这样的才是隔夜版本，而 pip install --pre paddlepaddle -f https://paddlepaddle.org.cn/whl/develop.html 有可能定向到旧版本上，也有可能定向到新版上。
目前只能手动下载whl到本地再安装了。
早点修复吧～

**Comment by swtkiwi** [comment]
您好。
1、nightly build包是每天0点开始编包的，理论上是包含昨天24点前所有的commit。您可能是安装了0.0.0文件夹下的包。安装develop-cpu-openblas下的包不会有问题的。如果还有问题辛苦提交badcase
2、0.0.0文件夹下的包是之前的develop版本，刚刚已经更新将其删除，您以后直接使用官网推荐的安装命令即可，不需要到https://paddlepaddle.org.cn/whl/develop.html 进行查看。

**Comment by starsblinking** [comment]
好的，辛苦～
