### ISSUE TITLE
安装问题：关于官网paddle docker gpu版本，下载后是否需要安装CUDA，Cudnn以及版本号问题？

### ISSUE THREAD

**Issue by GhostDino** [PaddlePaddle/Paddle#30820]
本地环境Ubuntu20.04LTS，docker20.0，nvidia-docker2，2080Ti*2；
使用官网下载容器版本paddle 2.0.0-gpu-cuda10.1-cudnn7。
启动容器后，通过了fluid run_check()
使用hub serving start -m chinese_ocr_db_cmn_server --use_gpu
始终报错，直接访问网址，可以正确显示200，提示该网站不能直接访问，需要使用脚本上传文件。
想请问下：
1、如果使用nvidia-docker2，并且是paddle gpu镜像，还是否需要在容器里面安装cuda和cudnn？
2、官网镜像里面有很多python版本，在使用pip安装相关包，以及安装paddl hub该用哪个安装比较合适？

**Comment by qili93** [comment]
如果您使用的是paddle提供的官方镜像，镜像中以及包含了CUDA和CUDNN，不需要再次安装。

**Comment by GhostDino** [comment]
谢谢！
