### ISSUE TITLE
请教一下？在静态图里面可以通过组合op的方式实现 这种逻辑吗？

### ISSUE THREAD

**Issue by wangsiji** [PaddlePaddle/Paddle#30823]
`
def city_encode(cityId):

    cityId = np.array(cityId)

    cityId = np.where(cityId > 373, 242, cityId)

    cityId = np.where(cityId < 33, 0, cityId)

    cityId = np.where((373 >= cityId) & (cityId >= 33), cityId - 32, cityId)

    return cityId`

**Comment by T8T9** [comment]
应该可以，麻烦参考 [paddle.where(condition, x, y, name=None)](https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/tensor/search/where_cn.html#where)
