### ISSUE TITLE
阿里云centos  安装错误

### ISSUE THREAD

**Issue by gaofushuai12138** [PaddlePaddle/Paddle#30837]
import paddle 后 报module obj has no attribute 'BOX'

**Comment by T8T9** [comment]
请提供一下信息：
- paddle 版本
- centos 版本
- python 版本

**Comment by gaofushuai12138** [comment]
Python&nbsp;2.7.5&nbsp; &nbsp; centos 7.8&nbsp; &nbsp; &nbsp;paddlepaddle 2.0&nbsp; 谢谢!




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Shibo Tao"<notifications@github.com&gt;; 
发送时间: 2021年2月2日(星期二) 下午4:47
收件人: "PaddlePaddle/Paddle"<Paddle@noreply.github.com&gt;; 
抄送: "白夜行"<3499606002@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [PaddlePaddle/Paddle] 阿里云centos  安装错误 (#30837)





 
请提供一下信息：
  
paddle 版本
 
centos 版本
 
python 版本

**Comment by T8T9** [comment]
麻烦先升级到最新的pip试一下哈 @gaofushuai12138  @pangyoki
