### ISSUE TITLE
jetson nano源码编译padlepaddle错误：一直卡在build taget malloc

### ISSUE THREAD

**Issue by GZHUZhao** [PaddlePaddle/Paddle#30848]
paddlepaddle版本：1.7.0
硬件：英伟达jetson nano b01，ARM Cortex-A57，Nvidia GPU
系统：ubuntu18.04
cuda=10.0
cudnn=7.6
安装方式：源码编译安装，按照下面链接提供的方法安装：
https://www.jianshu.com/p/09a0fd569247
编译命令：
cmake .. \
          -DWITH_CONTRIB=OFF \
          -DWITH_MKL=OFF  \
          -DWITH_MKLDNN=OFF \
          -DWITH_TESTING=OFF \
          -DCMAKE_BUILD_TYPE=Release \
          -DON_INFER=ON \
          -DWITH_PYTHON=ON \
              -DWITH_XBYAK=OFF  \
              -DWITH_NV_JETSON=ON \
              -DPY_VERSION=3.6
这里没有问题。

make -j4

一直卡在[10%]built taget malloc
错误：fatal: unable to access 'https:gitlab.com/libeigen/eigen.git/':Operation timed out after 300015 milliseconds with 0 out of 0 bytes received
![image](https://user-images.githubusercontent.com/78419361/106597518-815dbf00-6591-11eb-8576-d15407a07d60.png)

使用wifi进行上网。
请教各位大佬怎么办？
我主要想使用paddle inference的python api，如果有whl文件的麻烦提供下，谢谢！

**Comment by T8T9** [comment]
安装whl包，请参考 https://www.paddlepaddle.org.cn/install/quick?docurl=/documentation/docs/zh/2.0/install/pip/windows-pip.html

**Comment by GZHUZhao** [comment]
> 安装whl包，请参考 https://www.paddlepaddle.org.cn/install/quick?docurl=/documentation/docs/zh/2.0/install/pip/windows-pip.html

jetson nano 上没有办法直接通过pip安装whl的啊

**Comment by GZHUZhao** [comment]
> > 安装whl包，请参考 https://www.paddlepaddle.org.cn/install/quick?docurl=/documentation/docs/zh/2.0/install/pip/windows-pip.html
> 
> jetson nano 上没有办法直接通过pip安装wh
