### ISSUE TITLE
请教一下paddle 模型预测完如何释放资源或者删除模型之后自动释放资源的指令

### ISSUE THREAD

**Issue by cgq0816** [PaddlePaddle/Paddle#30853]
1、有没有像torch指令一样，使用torch.cuda.empty_cache() 方法，预测完清空gpu或者cpu内存？
2、使用GC的方式删除模型，来达到释放资源
     以paddleocr为例
     import gc
     from paddleocr import PaddleOCR, draw_ocr
     ocr = PaddleOCR(use_angle_cls=True, lang="ch")
     ......
     ......
     del ocr
     gc.collect() 
第一种方法没有在paddle官网找到，如果没有，也希望paddle开发人员能够支持这种类似的指令，每次预测完，通过指令释放资源，这样用户不用担心内存泄露的相关问题或者因为资源紧张导致预测失败等等的问题
第二种方法我也试过，删除模型之后，资源也没有释放

**Comment by yinhaofeng** [comment]
您好，预测的话此功能我们已经有类似的实现，可以参考下这个接口  ：https://paddleinference.paddlepaddle.org.cn/api_reference/cxx_api_doc/Predictor.html#id2
有问题随时提出，谢谢。

**Comment by cgq0816** [comment]
> 您好，预测的话此功能我们已经有类似的实现，可以参考下这个接口 ：https://paddleinference.paddlepaddle.org.cn/api_reference/cxx_api_doc/Predictor.html#id2
> 有问题随时提出，谢谢。

谢谢，看到了，请问一下paddleocr有类似的功能吗？

**Comment by MissPenguin** [comment]
> > 您好，预测的话此功能我们已经有类似的实现，可以参考下这个接口 ：https://paddleinference.paddlepaddle.org.cn/api_reference/cxx_api_doc/Predictor.html#id2
> > 有问题随时提出，谢谢。
> 
> 谢谢，看到了，请问一下paddleocr有类似的功能吗？

paddleocr尚未添加相关代码，如果显存溢出可以按照示例自行添加，但是会影响预测速度，如果很长时间都不溢出，就不推荐使用
