### ISSUE TITLE
tx2上开启TRT预测，卡在Sync params from CPU to GPU

### ISSUE THREAD

**Issue by lleesg** [PaddlePaddle/Paddle#30866]
环境：TX2、Ubuntu18.04、CUDA10.2、cudnn 8.0.0、jetpack 4.4、python3.6、Paddle-release-2.0

代码：
def init_predictor(args):
    if args.model_dir is not "":
        config = Config(args.model_dir)
    else:
        config = Config(args.model_file, args.params_file)

    config.enable_memory_optim()
    if args.use_gpu:
        config.enable_use_gpu(1000, 0)
    else:
        # If not specific mkldnn, you can set the blas thread.
        # The thread num should not be greater than the number of cores in the CPU.
        config.set_cpu_math_library_num_threads(4)
        config.enable_mkldnn()

    config.enable_tensorrt_engine(  \
         1 << 30,  
         1,    
         3,       
        Config.Precision.Float32, 
        False,
        False
    )

    predictor = create_predictor(config)
    return predictor

错误信息：
dji@manifold2:~/Desktop/Paddle-Inference-Demo-master 20210111_lisg$ /usr/bin/python3 "/home/dji/Desktop/Paddle-Inference-Demo-master/python/yolov3/infer_yolov3.py"
WARNING: AVX is not support on your machine. Hence, no_avx core will be imported, It has much worse preformance than avx core.
W0203 16:43:40.363271 13150 analysis_predictor.cc:614] The one-time configuration of analysis predictor failed, which may be due to native predictor called first and its configurations taken effect.
I0203 16:43:40.363487 13150 analysis_predictor.cc:139] Profiler is deactivated, and no profiling report will be generated.
I0203 16:43:40.440719 13150 analysis_predictor.cc:474] TensorRT subgraph engine is enabled
--- Running analysis [ir_graph_build_pass]
--- Running analysis [ir_graph_clean_pass]
--- Running analysis [ir_analysis_pass]
--- Running IR pass [conv_affine_channel_fuse_pass]
--- Running IR pass [adaptive_pool2d_convert_global_pass]
--- Running IR pass [conv_eltwiseadd_affine_channel_fuse_pass]
--- Running IR pass [shuffle_channel_detect_pass]
--- Running IR pass [quant_conv2d_dequant_fuse_pass]
--- Running IR pass [delete_quant_dequant_op_pass]
--- Running IR pass [delete_quant_dequant_filter_op_pass]
--- Running IR pass [simplify_with_basic_ops_pass]
--- Running IR pass [embedding_eltwise_layernorm_fuse_pass]
--- Running IR pass [multihead_matmul_fuse_pass_v2]
--- Running IR pass [skip_layernorm_fuse_pass]
--- Running IR pass [unsqueeze2_eltwise_fuse_pass]
--- Running IR pass [conv_bn_fuse_pass]
I0203 16:43:41.903551 13150 graph_pattern_detector.cc:101] ---  detected 73 subgraphs
--- Running IR pass [squeeze2_matmul_fuse_pass]
--- Running IR pass [reshape2_matmul_fuse_pass]
--- Running IR pass [flatten2_matmul_fuse_pass]
--- Running IR pass [map_matmul_to_mul_pass]
--- Running IR pass [fc_fuse_pass]
--- Running IR pass [conv_elementwise_add_fuse_pass]
I0203 16:43:42.086125 13150 graph_pattern_detector.cc:101] ---  detected 79 subgraphs
--- Running IR pass [tensorrt_subgraph_pass]
I0203 16:43:42.253644 13150 tensorrt_subgraph_pass.cc:126] ---  detect a sub-graph with 4 nodes
I0203 16:43:42.274510 13150 tensorrt_subgraph_pass.cc:345] Prepare TRT engine (Optimize model structure, Select OP kernel etc). This process may cost a lot of time.
I0203 16:43:49.012262 13150 tensorrt_subgraph_pass.cc:126] ---  detect a sub-graph with 32 nodes
I0203 16:43:49.019671 13150 tensorrt_subgraph_pass.cc:345] Prepare TRT engine (Optimize model structure, Select OP kernel etc). This process may cost a lot of time.
I0203 16:44:15.630620 13150 tensorrt_subgraph_pass.cc:126] ---  detect a sub-graph with 110 nodes
I0203 16:44:15.653692 13150 tensorrt_subgraph_pass.cc:345] Prepare TRT engine (Optimize model structure, Select OP kernel etc). This process may cost a lot of time.
I0203 16:44:32.010673 13150 tensorrt_subgraph_pass.cc:126] ---  detect a sub-graph with 8 nodes
I0203 16:44:32.013402 13150 tensorrt_subgraph_pass.cc:345] Prepare TRT engine (Optimize model structure, Select OP kernel etc). This process may cost a lot of time.
I0203 16:44:33.793197 13150 tensorrt_subgraph_pass.cc:126] ---  detect a sub-graph with 10 nodes
I0203 16:44:33.796995 13150 tensorrt_subgraph_pass.cc:345] Prepare TRT engine (Optimize model structure, Select OP kernel etc). This process may cost a lot of time.
I0203 16:44:39.216840 13150 tensorrt_subgraph_pass.cc:126] ---  detect a sub-graph with 48 nodes
I0203 16:44:39.227145 13150 tensorrt_subgraph_pass.cc:345] Prepare TRT engine (Optimize model structure, Select OP kernel etc). This process may cost a lot of time.
I0203 16:44:54.498896 13150 tensorrt_subgraph_pass.cc:126] ---  detect a sub-graph with 33 nodes
I0203 16:44:54.506799 13150 tensorrt_subgraph_pass.cc:345] Prepare TRT engine (Optimize model structure, Select OP kernel etc). This process may cost a lot of time.
I0203 16:45:03.023609 13150 tensorrt_subgraph_pass.cc:126] ---  detect a sub-graph with 9 nodes
I0203 16:45:03.026404 13150 tensorrt_subgraph_pass.cc:345] Prepare TRT engine (Optimize model structure, Select OP kernel etc). This process may cost a lot of time.
I0203 16:45:04.704521 13150 tensorrt_subgraph_pass.cc:126] ---  detect a sub-graph with 10 nodes
I0203 16:45:04.708173 13150 tensorrt_subgraph_pass.cc:345] Prepare TRT engine (Optimize model structure, Select OP kernel etc). This process may cost a lot of time.
--- Running IR pass [conv_bn_fuse_pass]
--- Running IR pass [conv_elementwise_add_act_fuse_pass]
--- Running IR pass [conv_elementwise_add2_act_fuse_pass]
--- Running IR pass [transpose_flatten_concat_fuse_pass]
--- Running analysis [ir_params_sync_among_devices_pass]
I0203 16:45:10.277199 13150 ir_params_sync_among_devices_pass.cc:45] Sync params from CPU to GPU

问题：
tx2上运行TRT预测，卡在Sync params from CPU to GPU。若关闭TRT，则不报错。
PS：由于编译2.0正式版过程中报错，我把third_party中的pybind文件夹给删除了，不知跟这个有关系不？谢谢~~

**Comment by cryoco** [comment]
您好，可以尝试下把`config.enable_tensorrt_engine`的第三个参数`min_subgraph_size`改为100试试

**Comment by lleesg** [comment]
> 您好，可以尝试下把`config.enable_tensorrt_engine`的第三个参数`min_subgraph_size`改为100试试

您好。
1. 将min_subgraph_size改为100问题未能解决；
2. 将enable_use_gpu(1000, 0)改为enable_use_gpu(500, 0)问题解决，请问：这里设置的显存是否是初始化期间还是运行期间所允许使用的最大显存？TX2显存和内存共享8G主存，应该是OK的，为何这里改小了倒还能运行了？

**Comment by cryoco** [comment]
> > 您好，可以尝试下把`config.enable_tensorrt_engine`的第三个参数`min_subgraph_size`改为100试试
> 
> 您好。
> 
> 1. 将min_subgraph_size改为100问题未能解决；
> 2. 将enable_use_gpu(1000, 0)改为enable_use_gpu(500, 0)问题解决，请问：这里设置的显存是否是初始化期间还是运行期间所允许使用的最大显存？TX2显存和内存共享8G主存，应该是OK的，为何这里改小了倒还能运行了？

是初始化的显存，不够会继续申请。
降低初始化的显存就不会hang住这个情况不太符合预期，我们记录并后续尝试复现一下，请问您是否方便提供下模型和复现单测？我们后续有进展会更新在这里。

**Comment by lleesg** [comment]
> > > 您好，可以尝试下把`config.enable_tensorrt_engine`的第三个参数`min_subgraph_size`改为100试试
> > 
> > 
> > 您好。
> > 
> > 1. 将min_subgraph_size改为100问题未能解决；
> > 2. 将enable_use_gpu(1000, 0)改为enable_use_gpu(500, 0)问题解决，请问：这里设置的显存是否是初始化期间还是运行期间所允许使用的最大显存？TX2显存和内存共享8G主存，应该是OK的，为何这里改小了倒还能运行了？
> 
> 是初始化的显存，不够会继续申请。
> 降低初始化的显存就不会hang住这个情况不太符合预期，我们记录并后续尝试复现一下，请问您是否方便提供下模型和复现单测？我们后续有进展会更新在这里。

模型用的官方DarknetYOLOv3
代码用的官方Paddle-Inference-Demo-master\python\yolov3\infer_yolov3.py
谢谢~

**Comment by lleesg** [comment]
> > > 您好，可以尝试下把`config.enable_tensorrt_engine`的第三个参数`min_subgraph_size`改为100试试
> > 
> > 
> > 您好。
> > 
> > 1. 将min_subgraph_size改为100问题未能解决；
> > 2. 将enable_use_gpu(1000, 0)改为enable_use_gpu(500, 0)问题解决，请问：这里设置的显存是否是初始化期间还是运行期间所允许使用的最大显存？TX2显存和内存共享8G主存，应该是OK的，为何这里改小了倒还能运行了？
> 
> 是初始化的显存，不够会继续申请。
> 降低初始化的显存就不会hang住这个情况不太符合预期，我们记录并后续尝试复现一下，请问您是否方便提供下模型和复现单测？我们后续有进展会更新在这里。

还有个问题，我用2.0rc0预测正常，同样的代码、权重，用2.0就预测不到任何目标了，请问能提供点排查思路么？谢谢

**Comment by jiamingming-004** [comment]
> 

请问你解决了嘛？

**Comment by lleesg** [comment]
> > 
> 
> 请问你解决了嘛？

将enable_use_gpu(1000, 0)改为enable_use_gpu(500, 0)问题解决
