### ISSUE TITLE
使用官方配置文件训练路标训练集时，训练到评估阶段训练终止，无法继续训练

### ISSUE THREAD

**Issue by wexin-c** [PaddlePaddle/Paddle#30865]
为使您的问题得到快速解决，在建立Issues前，请您先通过如下方式搜索是否有相似问题:【搜索issue关键字】【使用labels筛选】【官方文档】

如果您没有查询到相似问题，为快速解决您的提问，建立issue时请提供如下细节信息：
- 标题：简洁、精准概括您的问题，例如“Insufficient Memory xxx" ”
- 版本、环境信息：
    1）PaddlePaddle版本：2.0
    2）CPU：预测若用CPU，请提供CPU型号，MKL/OpenBlas/MKLDNN/等数学库使用情况
    3）GPU：预测若用GPU，1080ti、CUDA11.0和CUDNN8
    4）系统环境：windows 10
 注：您可以通过执行[summary_env.py](https://github.com/PaddlePaddle/Paddle/blob/develop/tools/summary_env.py)获取以上信息。
- 训练信息
    1）单机，单卡
    2）显存信息
    3）Operator信息
- 复现信息：如为报错，请给出复现环境、复现步骤
- 问题描述：请详细描述您的问题，同步贴出报错信息、日志、可复现的代码片段
![image](https://user-images.githubusercontent.com/78461277/106718277-cdfdd480-663b-11eb-840f-e6cd6f4aa910.png)

**Comment by yinhaofeng** [comment]
看报错应该是目前还不支持windows下运行，可以更换成linux环境试试看。

**Comment by wexin-c** [comment]
> 看报错应该是目前还不支持windows下运行，可以更换成linux环境试试看。

新版的2.0框架不支持在windows下运行吗？我一开始是用自己的数据集不行 ，然后用官网的教程来也是卡在这不训练了。

**Comment by yinhaofeng** [comment]
新版的2.0框架是支持在windows下运行的，您的报错显示fusion_group不支持windows，应该是环境和配置出了问题。如果方便的话可以提供一下您参考的是哪个教程和官方配置吗？
