### ISSUE TITLE
Paddle编译问题报错

### ISSUE THREAD

**Issue by wksuixin** [PaddlePaddle/Paddle#30870]
Linux Ubuntu18.04；cuda 10.2; cudnn 7.6; gcc 7.5编译时avx报错 如下： 
/usr/lib/gcc/x86_64-linux-gnu/7/include/avx512fintrin.h(1761): error: identifier "__builtin_ia32_sqrtsd_round" is undefined

/usr/lib/gcc/x86_64-linux-gnu/7/include/avx512fintrin.h(1770): error: identifier "__builtin_ia32_sqrtss_round" is undefined

/usr/lib/gcc/x86_64-linux-gnu/7/include/avx512fintrin.h(2728): error: identifier "__builtin_ia32_scalefsd_round" is undefined

/usr/lib/gcc/x86_64-linux-gnu/7/include/avx512fintrin.h(2737): error: identifier "__builtin_ia32_scalefss_round" is undefined

/usr/lib/gcc/x86_64-linux-gnu/7/include/avx512fintrin.h(11265): error: identifier "__builtin_ia32_scalefsd_round" is undefined

/usr/lib/gcc/x86_64-linux-gnu/7/include/avx512fintrin.h(11274): error: identifier "__builtin_ia32_scalefss_round" is undefined

/usr/lib/gcc/x86_64-linux-gnu/7/include/avx512dqintrin.h(1163): error: identifier "__builtin_ia32_reducesd" is undefined

换gcc8.4也报错，是必须gcc8.2么？

**Comment by yinhaofeng** [comment]
gcc建议使用8.2.0

**Comment by wksuixin** [comment]
> gcc建议使用8.2.0
使用gcc8.2.0 报boost的错误，累了。。。

/data/nlp/wangkuan/code/Paddle/build/third_party/boost/src/extern_boost/boost/mpl/assert.hpp:154:21: error: unnecessary parentheses in declaration of ‘assert_arg’ [-Werror=parentheses]
 failed ************ (Pred::************
                     ^
/data/nlp/wangkuan/code/Paddle/build/third_party/boost/src/extern_boost/boost/mpl/assert.hpp:159:21: error: unnecessary parentheses in declaration of ‘assert_not_arg’ [-Werror=parentheses]
 failed ************ (boost::mpl::not_<Pred>::************

**Comment by yinhaofeng** [comment]
建议清理一下build目录，再试一次看看。可能是build目录中之前遗留的问题。如果还有报错麻烦给一下比较详细的报错，我们会第一时间帮您分析

**Comment by wksuixin** [comment]
> 建议清理一下build目录，再试一次看看。可能是build目录中之前遗留的问题。如果还有报错麻烦给一下比较详细的报错，我们会第一时间帮您分析

把build目录删除后，没再编译1.8版本，编译2.0版本成功了！！！

**Comment by shengzhe8688** [comment]
官方能不能  把SIMD和AVX的指令集做成开关或者禁用一下？
另外gcc 8.2.0 编译的能给gcc7.5.0的程序用么？

**Comment by shengzhe8688** [comment]
![image](https://user-images.githubusercontent.com/16428236/160836927-42272fa0-6a51-45ee-8f47-2f047833ef70.png)
这行干掉即可
