### ISSUE TITLE
paddle优化器于pytorch优化器对应问题

### ISSUE THREAD

**Issue by GuoQuanhao** [PaddlePaddle/Paddle#30876]
paddle2.0的SGD优化器没有momentum参数，但是新增了一个momentum优化器，所以我想知道paddle的momentum优化器等价于pytorch的SGD优化器吗
![image](https://user-images.githubusercontent.com/49911294/106752683-b3405580-6665-11eb-8106-2e55fd018d9b.png)

![image](https://user-images.githubusercontent.com/49911294/106752653-ab80b100-6665-11eb-9aad-2bf583e66e74.png)

**Comment by MrChengmo** [comment]
momentum优化器 是 paddle框架之前既有的，如果希望在优化过程中加入动量，可以直接使用momentum这个OP，和打开动量开关的pytorch sgd优化器对齐

**Comment by GuoQuanhao** [comment]
> momentum优化器 是 paddle框架之前既有的，如果希望在优化过程中加入动量，可以直接使用momentum这个OP，和打开动量开关的pytorch sgd优化器对齐

那他是等价于pytorch
