### ISSUE TITLE
多机多卡报错

### ISSUE THREAD

**Issue by KingCSer** [PaddlePaddle/Paddle#30874]
版本：paddle-cudnn7-cuda10.0
用多机多卡封装optimizer时报错：Traceback (most recent call last):
  File "train.py", line 327, in <module>
    main()
  File "train.py", line 320, in main
    train(args)
  File "train.py", line 179, in train
    args=args)
  File "train.py", line 80, in build_program
    global_lr = optimizer._global_learning_rate()
AttributeError: 'CollectiveOptimizer' object has no attribute '_global_learning_rate'
源代码如图所示
应该怎么修改？
![image](https://user-images.githubusercontent.com/48956659/106746653-ca7b4500-665d-11eb-92d6-13c3595bd466.png)

**Comment by KingCSer** [comment]
with fluid.unique_name.guard():
            data_loader, loss_out = create_model(model, args, is_train)
            # add backward op in program
            if is_train:
                optimizer = create_optimizer(args)
                # M3
                optimizer = fleet.distributed_optimizer(optimizer, strategy=DistributedStrategy())
                avg_cost = loss_out[0]
                #XXX: fetch learning rate now, better implement is required here. 
                global_lr = optimizer._global_learning_rate()

                global_lr.persistable = True
                loss_out.append(global_lr)

                if args.use_fp16:
                    optimizer = fluid.contrib.mixed_precision.decorate(
                        optimizer,
                        init_loss_scaling=args.scale_loss,
                        use_dynamic_loss_scaling=args.use_dynamic_loss_scaling)
                #M3
                #optimizer.minimize(avg_cost)
                optimizer.minimize(avg_cost, fluid.default_startup_program())

**Comment by KingCSer** [comment]
上述问题来源于将此程序：https://github.com/PaddlePaddle/models/blob/develop/PaddleCV/image_classification/train.py修改为多机多卡训练时的错误

**Comment by wangxicoding** [comment]
试一下这个，不过不建议通过_global_learning_rate()获取lr，create_optimizer时应该可以获取相应的lr。另外你现在用的哪个Paddle版本，建议升级到paddle2.0。paddle分布式fleet接口进行了相关的升级，可以查阅相关文档https://fleet-x.readthedocs.io/en/latest/ （最近文档在重构升级，可能尚不完善，敬请谅解）
```
   with fluid.unique_name.guard():
        data_loader, loss_out = create_model(model, args, is_train)
        # add backward op in program
        if is_train:
            optimizer = create_optimizer(args)
            original_optimizer = optimizer
            avg_cost = loss_out[0]

            if args.use_fp16:
                optimizer = fluid.contrib.mixed_precision.decorate(
                    optimizer,
                    init_loss_scaling=args.scale_loss,
                    use_dynamic_loss_scaling=args.use_dynamic_loss_scaling)

            # M3
            optimizer = fleet.distributed_optimizer(optimizer, strategy=DistributedStrategy())

            #M3
            #optimizer.minimize(avg_cost)
            optimizer.minimize(avg_cost, fluid.default_startup_program())

            #XXX: fetch learning rate now, better implement is required here. 
            global_lr = original_optimizer._global_learning_rate()
            loss_out.append(global_lr)
```
