### ISSUE TITLE
paddle2.0 windows c++推理初始化模型问题

### ISSUE THREAD

**Issue by williamlzw** [PaddlePaddle/Paddle#30882]
版本、环境信息：
    1）PaddlePaddle版本：请提供您的PaddlePaddle版本号:2.0
    2）CPU：预测若用CPU，因特尔，OpenBlas版本windows推理包
    4）系统环境：win10
-预测信息
    1）C++预测：2.0 Windows openblas c++推理包
    4）预测库来源：paddleocr dbnet 检测轻量级推理模型
- 复现信息：如为报错，请给出复现环境、复现步骤
- 问题描述：请详细描述您的问题，同步贴出报错信息、日志/代码关键片段

paddle_infer::Config config;
config.SetModel("inference.pdmodel","inference.pdiparams"）这一句我用c++例子跑可以通过。但我用一款中文语言编写运行就崩溃了.
截图见https://ai.baidu.com/forum/topic/show/982685

**Comment by littletomatodonkey** [comment]
你好，在你这个环境里，使用vs2019可以正常运行cpp inference的demo嘛？目前windows上cpp inference的demo代码部分应该还太支持中文编程语言哈~inference model路径也不能使用中文路径，否则也会报错

**Comment by williamlzw** [comment]
我没有用中文路径，那个IDE其实是嵌入c++原生代码，但就是不能运行，只是把运行代码封装到一个c++ class里面。

**Comment by littletomatodonkey** [comment]
嗯嗯，要不使用VS等ide呢？之前没有在这种中文ide上测试过~

**Comment by williamlzw** [comment]
确定了visual studio2019也不能跑。见下面issues
https://github.com/PaddlePaddle/PaddleOCR/issues/1961
