### ISSUE TITLE
安装paddle报错磁盘空间不够

### ISSUE THREAD

**Issue by DDDLIN** [PaddlePaddle/Paddle#30885]
使用命令python3 -m pip install paddlepaddle-gpu==2.0.0 -i https://mirror.baidu.com/pypi/simple --trusted-host mirror.baidu.com安装paddle时报错。
错误信息：
ERROR: Could not install packages due to an EnvironmentError: [Errno 28] No space left on device
磁盘空间：6.5G Available
请问是paddle安装过程中会超过6.5G吗？还是别的问题？

**Comment by littletomatodonkey** [comment]
你好，这可能是/tmp中空间不够导致的哈，
1. 可以清空下/tmp文件夹
2. 在pip install的时候，可以指定下面`--cache-dir`与`--build`的目录， `--cache-dir=/folder/address/here/ --build /folder/address/here/`，这两个目录下有足够的空间即可，比如

```
python3 -m pip install --cache-dir=/your_folder/ --build=/your_folder/  paddlepaddle-gpu==2.0.0 -i https://mirror.baidu.com/pypi/simple --trusted-host mirror.baidu.com
```
