### ISSUE TITLE
单机多卡并行训练出错

### ISSUE THREAD

**Issue by qdd1234** [PaddlePaddle/Paddle#30887]
我通过单机多卡的程序完成训练后保存模型想进行验证以及继续训练，但是使用paddle.load()导入模型时却报如下的错误
请问该如何解决
![image](https://user-images.githubusercontent.com/68497831/106857451-10d2b180-66fb-11eb-8424-2028f700e2c2.png)

**Comment by qdd1234** [comment]
我是用的是paddle2.0 在四张Tesla T4上进行训练

**Comment by littletomatodonkey** [comment]
你好，模型保存的时候，建议只在0号卡上保存哈，否则的话，多个trainer同时写到一个文件的话，保存的模型文件可能无法读取，可以参考这里~：

https://github.com/PaddlePaddle/PaddleClas/blob/e16b79530c90a745e5015df6b09513379db9f5fd/ppcls/utils/save_load.py#L149

**Comment by qdd1234** [comment]
如果只在0号卡上保存参数，那其余三张卡上保存的模型参数是会被怎么处理？

**Comment by littletomatodonkey** [comment]
所有trainer的参数都是完全一样的，所以只需保存一份即可哈

**Comment by qdd1234** [comment]
还有一个问题:我使用四张卡进行训练，一张卡上batchsize = 20 ，按道理来说总的batch_size = 80 ,那为何每张卡上训练的轮数还是等于总的数据集图片数量/batchsize？

**Comment by qdd1234** [comment]
其中 计算轮数的batchsize = 20，这是什么原因，我看论文上提到多卡是可以实现更大batchsize效果的

**Comment by littletomatodonkey** [comment]
你的DistributedBatchSampler中传入的是20吗？这里需要设置单卡的bs


https://github.com/PaddlePaddle/PaddleClas/blob/e16b79530c90a745e5015df6b09513379db9f5fd/ppcls/data/reader.py#L248

**Comment by qdd1234** [comment]
![image](https://user-images.githubusercontent.com/68497831/106872494-5482e680-670e-11eb-99fe-de9af246b0f3.png)
那我直接使用DataLoader是无法实现的？

**Comment by littletomatodonkey** [comment]
多卡训练的话，是需要使用DistributedBatchSampler的哈，会对数据在不同trainer上面做切分~

**Comment by moneyQyh** [comment]
接这个问题请问一下，如果不通过Distributedbatchsampler组batch，该如何实现多卡数据并行呢
