### ISSUE TITLE
【30系列机器用户的福音】第三方贡献wheel包集合点

### ISSUE THREAD

**Issue by swtkiwi** [PaddlePaddle/Paddle#30909]
Hi，各位飞桨用户～
非常开心的告诉大家：飞桨很荣幸的有了第一个适配3090的wheel包，并且是社区贡献的～这代表更多人荡起手中的桨，为飞桨助力，双桨合璧～
飞桨其实可以适配更多的环境和硬件，但是官方核心团队的机器、人力很难进行全面覆盖，故我们希望能够召集更多的第三方贡献者共同来建设更加完整的飞桨安装生态，用飞桨、划时代！
当然官方也在快马加鞭的进行着适配30系列机器的准备，敬请期待～
以下为第三方贡献wheel包，供大家学习使用，如有任何问题欢迎大家随时在此issue下沟通交流，也欢迎大家来一起贡献哦：
-贡献者：zhang.xuan；github主页：https://github.com/daassh
- wheel包适配环境：
python: 3.8.5
gcc: 9.3.0
cuda 11.1
显卡型号: RTX3090
系统: Ubuntu20.04
- wheel包下载地址：https://paddle-wheel.bj.bcebos.com/paddle-wheel-thirdparty/zhangxuan-2.0.0-cuda11.1-linux-3090-py38/paddlepaddle_gpu-0.0.0-cp38-cp38-linux_x86_64.whl
- 下载后使用安装命令：python3 -m pip install paddlepaddle_gpu-0.0.0-cp38-cp38-linux_x86_64.whl
- 验证：安装完成后您可以使用 python 或 python3 进入python解释器，输入import paddle ，再输入 paddle.utils.run_check() 如果出现PaddlePaddle is installed successfully!，说明您已成功安装。

欢迎更多同学前来贡献～
Paddle Installation SIG
这里是硬件极客、源码编译需求者的乐园，在这里你可以互和小伙伴们一起分享深度学习框架的环境适配经验，共同适配最新最前沿硬件，提供你的安装优化idea，和技术大牛一起coding～
有意向的同学可以加群哦～
![image](https://user-images.githubusercontent.com/27208573/106985577-b130e080-67a4-11eb-9fad-ec435506a5e4.png)

**Comment by SivanLaai** [comment]
很感谢你的付出，请问rtx3090 已经可以完美使用了吗，这个包适合在ubuntu下使用不。

**Comment by chccc1994** [comment]
请问win10  3080 cuda 11.0 cudnn8.0.5 有编译的吗？或者教程？

**Comment by YanFuHai06** [comment]
请问Ubuntu20.04_64位 RTX3060TI cuda 11.1 cudnn8 有编译的或者教程吗？
