### ISSUE TITLE
CPU Inference gets incorrect results

### ISSUE THREAD

**Issue by juncaipeng** [PaddlePaddle/Paddle#30905]
Thank you for contributing to PaddlePaddle.
Before submitting the issue, you could search issue in the github in case that th
If there is no solution,please make sure that this is an inference issue including the following details :
**System information**
-PaddlePaddle version: 2.0
-CPU:  disable mkldnn
-OS Platform: ubuntu 16.04
-Python version: 3.7
Note: You can get most of the information by running [summary_env.py](https://github.com/PaddlePaddle/Paddle/blob/develop/tools/summary_env.py). 
**To Reproduce**

1. Download demo(Link:https://dubox.com/s/1g0S0Wzmmr0xmXYegBRLSKg Password:s7s5)

2. Install Paddle 2.0

3. Modify `freeze_model/deploy.yaml` file to set `USE_GPU` as 1, run `python infer.py --conf=freeze_model/deploy.yaml --input_dir=imgs` will get right result in `imgs` file.

![image](https://user-images.githubusercontent.com/52520497/106908538-595d8f80-673a-11eb-998e-5f7661a09a89.png)

4. Modify `freeze_model/deploy.yaml` file to set `USE_GPU` as 0, run `python infer.py --conf=freeze_model/deploy.yaml --input_dir=imgs`(cpu, open ir optimization, not enable mkldnn, enable memory optim) will get wrong result in `imgs` file, the segmentation img is blank. So I think the error is in Paddle Native kernels or framework.

![image](https://user-images.githubusercontent.com/52520497/106908452-49de4680-673a-11eb-87b1-3efc58f95887.png)

5. `run_fetch_infer_imgs.py` can load input, run and fetch output.
    Modify `run_fetch_infer_imgs.py` to set cpu or gpu. 
    Run `python run_fetch_infer_imgs.py freeze_model image conv2d_0.tmp_0 _generated_var_2 relu_0.tmp_0 relu_1.tmp_0 tmp_0 tmp_1 tmp_2 tmp_3 tmp_4` to fetch target tensor info.

    If run `run_fetch_infer_imgs.py` on gpu, the target tensor fetched is right.

![image](https://user-images.githubusercontent.com/52520497/106908251-1b606b80-673a-11eb-8777-cf48de288aa2.png)

    If run `run_fetch_infer_imgs.py` on cpu, the target tensor fetched is nan.
![image](https://user-images.githubusercontent.com/52520497/106908672-75f9c780-673a-11eb-83fe-79cae9f1b03f.png)

**Comment by juncaipeng** [comment]
The weights of first conv2d op have nan, just as follows.
![image](https://user-images.githubusercontent.com/52520497/106984159-04556400-67a2-11eb-93fa-00a3adeb5672.png)

**Comment by wojtuss** [comment]
@juncaipeng ,
I have verified quickly that enabling/disabling oneDNN `relu` kernel makes the difference. With oneDNN `relu` the output is correct. With native `relu` the output is incorrect. All fuses are turned off. I am still looking at it.

**Comment by wojtuss** [comment]
The first native `relu` produces correct output, all other `relu`s give `nan`s.

**Comment by wojtuss** [comment]
@juncaipeng ,
Yes, it looks like the `nan`s in `conv2d`'s weights are the culprit. For some reason oneDNN `relu` kernel copes with the `nan`s, like the GPU kernel does.

**Comment by juncaipeng** [comment]
@wojtuss Thank you for your investigation.

**Comment by wojtuss** [comment]
@juncaipeng , I have submitted a PR with a proposal of a fix: https://github.com/PaddlePaddle/Paddle/pull/30980

**Comment by wojtuss** [comment]
@juncaipeng , I have submitted an alternative fix which keeps the original (faster) GPU `relu` implementation.

**Comment by juncaipeng** [comment]
> @juncaipeng , I have submitted an alternative fix which keeps the original (faster) GPU `relu` implementation.

@wojtuss , I find #30996 and #30980 cann't pass the above demo test on develop and release 2.0. Do you verify the results?

**Comment by wojtuss** [comment]
> @wojtuss , I find #30996 and #30980 cann't pass the above demo test on develop and release 2.0. Do you verify the results?

@juncaipeng 
Let me check

**Comment by wojtuss** [comment]
@juncaipeng 
I have just verified again the `develop` branch (with python 2.7) and the results look correct, both picture and the output:
```
/data/issues/30905/0204_ditu_model /data/issues/30905
('model_path:', 'freeze_model')
('arg_names:', ['conv2d_0.tmp_0', '_generated_var_2', 'relu_0.tmp_0', 'relu_1.tmp_0', 'tmp_0', 'tmp_1', 'tmp_2', 'tmp_3', 'tmp_4'])
('is_feed_ones:', 'False')
('is_save_result:', 'False', '\n')
load model succeed
('input  shape:', (1, 3, 1536, 1536))
input[0:10]:
[0.27058828 0.27058828 0.27058828 0.27058828 0.27058828 0.27843142
 0.27843142 0.28627455 0.28627455 0.2941177 ]
read and save img succeed
fetch target succeed
run model succeed
('name:', u'save_infer_model/scale_0.tmp_0', ', size:', (96731136,), ', avg:', 0.024390275, ', min:', 2.5132043e-32, ', max:', 0.9999963, ', arg_max:', 233985)
('name:', u'conv2d_0.tmp_0', ', size:', (18874368,), ', avg:', nan, ', min:', nan, ', max:', nan, ', arg_max:', 2359296)
('name:', u'_generated_var_2', ', size:', (18874368,), ', avg:', nan, ', min:', nan, ', max:', nan, ', arg_max:', 2359296)
('name:', u'relu_0.tmp_0', ', size:', (18874368,), ', avg:', 1.2095162, ', min:', 0.0, ', max:', 24.884415, ', arg_max:', 4366442)
('name:', u'relu_1.tmp_0', ', size:', (37748736,), ', avg:', 1.3527343, ', min:', 0.0, ', max:', 79.08749, ', arg_max:', 27369578)
('name:', u'tmp_0', ', size:', (18874368,), ', avg:', 0.21603376, ', min:', -128.07526, ', max:', 76.56509, ', arg_max:', 3455118)
('name:', u'tmp_1', ', size:', (9437184,), ', avg:', 0.8190439, ', min:', -59.188972, ', max:', 40.304626, ', arg_max:', 6355674)
('name:', u'tmp_2', ', size:', (6709248,), ', avg:', -0.61468214, ', min:', -123.34226, ', max:', 149.43623, ', arg_max:', 6620896)
('name:', u'tmp_3', ', size:', (6709248,), ', avg:', -0.82035685, ', min:', -123.57993, ', max:', 149.6315, ', arg_max:', 6620896)
('name:', u'tmp_4', ', size:', (6709248,), ', avg:', -0.97218025, ', min:', -162.77437, ', max:', 149.95789, ', arg_max:', 6620896)
output data:
[0.02479137 0.02600279 0.02722274 0.02844735 0.02967271 0.03191238
 0.03427749 0.0367609  0.03936233 0.04083817]
/data/issues/30905
```
I am double checking the `release/2.0` branch and python 3.6.

**Comment by wojtuss** [comment]
With `release/2.0` branch and both python 2.7 and 3.6 it also works.

**Comment by juncaipeng** [comment]
@wojtuss  Sorry for the mistake. I also get the right results on release 2.0 with python 3.7.
