### ISSUE TITLE
apt-get install git 出现问题

### ISSUE THREAD

**Issue by liucide** [PaddlePaddle/Paddle#3090]
首先我基础比较差，可能问题很没有水平，但是确实困扰了我很久了。请各位帮忙
运行一个demo
apt-get install git  出现错误
![qq 20170728084356](https://user-images.githubusercontent.com/30512814/28697802-22b596f0-7371-11e7-8743-475caa6dd323.png)

请协助解决，不慎感激

**Comment by Yancey1989** [comment]
@liucide 看起来是网络原因呀，先试下`apt-get update` 不行的话换一个国内源试试？
例如http://mirrors.163.com/.help/ubuntu.html
