### ISSUE TITLE
分布式训练支持Horovod

### ISSUE THREAD

**Issue by MrChengmo** [PaddlePaddle/Paddle#30915]
希望Paddle分布式训练可以支持horovod，并且有各种模式的Benchmark对比，参考链接：https://zhuanlan.zhihu.com/p/63191159

**Comment by MissPenguin** [comment]
您好，Paddle推荐使用Fleet API进行分布式训练，具体操作可参考文档：https://www.paddlepaddle.org.cn/documentation/docs/zh/guides/06_distributed_training/index_cn.html

**Comment by kuizhiqing** [comment]
感谢您的关注，horovod 支持正在开发中，请关注我们的最新进展。

**Comment by tianlinzx** [comment]
> 感谢您的关注，horovod 支持正在开发中，请关注我们的最新进展。

horovod 支持有新进展吗?

**Comment by forYounge** [comment]
> 感谢您的关注，horovod 支持正在开发中，请关注我们的最新进展。

horovod现在还会支持么
