### ISSUE TITLE
源码编译成功没有dist目录

### ISSUE THREAD

**Issue by caozongpeng** [PaddlePaddle/Paddle#30923]
- 标题：源码编译成功没有dist目录
- 版本、环境信息：
    1）PaddlePaddle版本：release/2.0
    2）CPU：麒麟 V10 aarch64
    4）系统环境：Python 3.7.0 

2）本地编译：cmake .. -DPY_VERSION=3 -DPYTHON_EXECUTABLE=`which python3` -DWITH_ARM=ON -DWITH_TESTING=OFF -DCMAKE_BUILD_TYPE=Release -DON_INFER=ON -DWITH_XBYAK=OFF

![image](https://user-images.githubusercontent.com/30362467/107021088-adba4b00-67de-11eb-9602-9843d1e237e2.png)

![image](https://user-images.githubusercontent.com/30362467/107021146-c0cd1b00-67de-11eb-82d0-53a3f767acac.png)

**Comment by MissPenguin** [comment]
/opt/software/python/Paddle/build/ 下有啥呢

**Comment by MissPenguin** [comment]
编译的时候加上这个参数试试：-DWITH_PYTHON=ON

**Comment by caozongpeng** [comment]
@MissPenguin 好像也没有用

**Comment by caozongpeng** [comment]
@MissPenguin 还有其它办法吗

**Comment by MissPenguin** [comment]
换别的paddle版本或者在GPU上也是这样吗

**Comment by caozongpeng** [comment]
@MissPenguin 试了别的版本也是这样，GPU的没有试，服务器是CPU的不能用GPU的吧。

**Comment by zhwesky2010** [comment]
@caozongpeng make了吗

**Comment by caozongpeng** [comment]
@zhouwei25 make了，都是按照官网的步骤来的。
