### ISSUE TITLE
ERNIE application stop build 

### ISSUE THREAD

**Issue by pmajchrzak** [PaddlePaddle/Paddle#30926]
branch: PaddlePaddle:develop
commit: 715d862868aca6ae4c865dc3db1cde6818e4ad1a
caused the ERNIE application to stop building

build command:
```
cd /root/models/benchmark/Inference/c++/ernie/
mkdir build
cd build
cmake .. -DPADDLE_ROOT=/repos/paddle_paddle/build/paddle_inference_install_dir -DUSE_GPU=OFF
make -j 20
```

Error message:
```
Scanning dependencies of target inference
[ 50%] Building CXX object CMakeFiles/inference.dir/inference.cc.o
/root/models/benchmark/Inference/c++/ernie/inference.cc: In function 'void InitFLAGS(int, char**)':
/root/models/benchmark/Inference/c++/ernie/inference.cc:61:3: error: 'gflags' has not been declared
   gflags::ParseCommandLineFlags(&argc, &argv, true);
   ^
CMakeFiles/inference.dir/build.make:62: recipe for target 'CMakeFiles/inference.dir/inference.cc.o' failed
make[2]: *** [CMakeFiles/inference.dir/inference.cc.o] Error 1
CMakeFiles/Makefile2:72: recipe for target 'CMakeFiles/inference.dir/all' failed
make[1]: *** [CMakeFiles/inference.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by OliverLPH** [comment]
@pmajchrzak 
Hi, PR https://github.com/PaddlePaddle/Paddle/pull/30623 has revert commit https://github.com/PaddlePaddle/Paddle/commit/715d862868aca6ae4c865dc3db1cde6818e4ad1a
You can test commit after this revert PR.

Or there is another way to avoid this issue, you can change source code of ERNIE application

change `gflags::ParseCommandLineFlags(&argc, &argv, true)` to `::GFLAGS_NAMESPACE::ParseCommandLineFlags(&argc, &argv, true)`

here is a sample:
https://github.com/PaddlePaddle/continuous_integration/blob/develop/inference/inference_benchmark/cc/Paddle/src/bert_benchmark.cc#L160

**Comment by lidanqing-vv** [comment]
@pmajchrzak  Hi, Could you please check if this problem still exists with newest develop ?

**Comment by lidanqing-vv** [comment]
Hi use please use updated command https://github.com/PaddlePaddle/benchmark/pull/896

**Comment by lidanqing-vv** [comment]
PR has been merged. If you have any problem, contact me.
