### ISSUE TITLE
【AIStudio】OSError: (External)  Cuda error(35), CUDA driver version is insufficient for CUDA runtime version.

### ISSUE THREAD

**Issue by lyl120117** [PaddlePaddle/Paddle#30933]
- 版本、环境信息：
    1）PaddlePaddle版本：paddlepaddle-gpu==2.0.0

Traceback (most recent call last):
  File "tools/main.py", line 56, in <module>
    main(args, cfg)
  File "tools/main.py", line 30, in main
    setup(args, cfg)
  File "/home/aistudio/stargan-v2.paddle/PaddleGAN/ppgan/utils/setup.py", line 39, in setup
    paddle.set_device('gpu')
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/device.py", line 134, in set_device
    place = core.CUDAPlace(ParallelEnv().dev_id)
OSError: (External)  Cuda error(35), CUDA driver version is insufficient for CUDA runtime version.
  [Advise: This indicates that the installed NVIDIA CUDA driver is older than the CUDA runtime library. This is not a supported configuration.Users should install an updated NVIDIA display driver to allow the application to run.] (at /paddle/paddle/fluid/platform/gpu_info.cc:78)

项目链接：
https://aistudio.baidu.com/aistudio/projectdetail/750895
https://aistudio.baidu.com/bdvgpu32g/user/324886/750895/notebooks/750895.ipynb

**Comment by tink2123** [comment]
链接项目未公开，我这边无法查看。从报错信息来看，应该是cuda版本太低导致的，可以尝试重开项目，或指定CUDA_VISIBLE_DEVICES 试试。

**Comment by lyl120117** [comment]
谢谢，重装了paddlepaddle-gpu==2.0.0.post101这个版本可以运行了，之前安装命令用的是这个paddlepaddle-gpu==2.0.0，默认装的是10.2的，奇怪的是这个项目前面几次用这个命令paddlepaddle-gpu==2.0.0安装是可以训练的，后面再怎么重启都训练不了。

**Comment by Lanme** [comment]
paddlepaddle-gpu=2.0.2，cuda=10.1同报错，不知是否有像tensorflow-gpu那样可以看paddle版本号和cuda版本号的对应？
