### ISSUE TITLE
两个神经网络，A只进行预测，B进行训练，B设置B.eval报错

### ISSUE THREAD

**Issue by frankINdf** [PaddlePaddle/Paddle#30938]
如果您没有查询到相似问题，为快速解决您的提问，建立issue时请提供如下细节信息：
- 标题：简洁、精准概括您的问题，例如“Insufficient Memory xxx" ”
- 版本、环境信息：
    1）2.0.0
    4）centos
 想要复现一篇论文，用到两个神经网络，A只进行预测，B进行训练，但是A要放在B之中，当作一层，这个时候用了A.eval()
但是训练时提示

ValueError: (InvalidArgument) GradOp is only callable when is_test is false
  [Hint: Expected ctx->Attrs().Get<bool>("is_test") == false, but received ctx->Attrs().Get<bool>("is_test"):1 != false:0.] (at /paddle/paddle/fluid/operators/dropout_op.cc:122)
  [Hint: If you need C++ stacktraces for debugging, please set `FLAGS_call_stack_level=2`.]

使用torch是可以一个网络当作一层，且模式为eval的

**Comment by ZHUI** [comment]
您好！感谢您的提问。
1. 建议您使用`@paddle.no_grad()`装饰器对 A 网络进行装饰，看是否能满足您的需求。
文档可参考 https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/fluid/dygraph/base/no_grad_cn.html#no-grad
2. 这个场景理论上，paddle 2.0.0 版本应该支持。请确保您使用的是2.0.0正式版或者最新的develop版本 。
develop下载链接： https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/install/Tables.html#whl-linux-gcc8-2-develop
3. 如果2不行的话，麻烦您提供个最小可复现的代码，我们继续会跟进解决。

**Comment by frankINdf** [comment]
感谢解答，加了no_grad可以解决，如果不加no_grad，就不能用model.eval
paddle 版本 2.0.0 rc1 .post101
