### ISSUE TITLE
使用conda安装时下载paddlepaddle-gpu-2.0进度条不动，一直0%，更换清华镜像后也一样。

### ISSUE THREAD

**Issue by DDDLIN** [PaddlePaddle/Paddle#30934]
使用conda安装paddle-gpu2.0，下载不动

conda install paddlepaddle-gpu==2.0.0 cudatoolkit=9.0 -c paddle

问题：
Downloading and Extracting Packages
mkl-service-2.3.0    | 62 KB     | ######################################################################################################################################### | 100% 
libtiff-4.1.0        | 449 KB    | ######################################################################################################################################### | 100% 
cudnn-7.6.5          | 143.3 MB  | ######################################################################################################################################### | 100% 
blas-1.0             | 6 KB      | ######################################################################################################################################### | 100% 
numpy-base-1.19.2    | 4.2 MB    | ######################################################################################################################################### | 100% 
libprotobuf-3.14.0   | 2.0 MB    | ######################################################################################################################################### | 100% 
openssl-1.1.1i       | 2.5 MB    | ######################################################################################################################################### | 100% 
lcms2-2.11           | 307 KB    | ######################################################################################################################################### | 100% 
freetype-2.10.4      | 596 KB    | ######################################################################################################################################### | 100% 
ca-certificates-2021 | 121 KB    | ######################################################################################################################################### | 100% 
astor-0.8.1          | 47 KB     | ######################################################################################################################################### | 100% 
pillow-8.1.0         | 626 KB    | ######################################################################################################################################### | 100% 
protobuf-3.14.0      | 309 KB    | ######################################################################################################################################### | 100% 
mkl_fft-1.2.0        | 157 KB    | ######################################################################################################################################### | 100% 
mkl_random-1.1.1     | 341 KB    | ######################################################################################################################################### | 100% 
olefile-0.46         | 33 KB     | ######################################################################################################################################### | 100% 
jpeg-9b              | 214 KB    | ######################################################################################################################################### | 100% 
zstd-1.4.5           | 619 KB    | ######################################################################################################################################### | 100% 
intel-openmp-2020.2  | 786 KB    | ######################################################################################################################################### | 100% 
libpng-1.6.37        | 278 KB    | ######################################################################################################################################### | 100% 
gast-0.3.3           | 14 KB     | ######################################################################################################################################### | 100% 
paddlepaddle-gpu-2.0 | 490.3 MB  |                                                                                                                                           |   0%

**Comment by GT-ZhangAcer** [comment]
可以先试试把安装命令里的-c paddle去掉

**Comment by tink2123** [comment]
可以尝试在这个路径下，手动下载whl包再安装：https://www.paddlepaddle.org.cn/whl/stable.html

**Comment by DDDLIN** [comment]
> 可以尝试在这个路径下，手动下载whl包再安装：https://www.paddlepaddle.org.cn/whl/stable.html

感谢，完美解决了我的问题！
