### ISSUE TITLE
squeeze_方法报错

### ISSUE THREAD

**Issue by GuoQuanhao** [PaddlePaddle/Paddle#30935]
platform: aistudio
version: 2.0.0
在使用paddle的`squeeze_`方法时，我出现了以下错误：
![image](https://user-images.githubusercontent.com/49911294/107117467-82565f80-68b5-11eb-9c0e-2463d44397ee.png)
但在pytorch中这能正常使用
![image](https://user-images.githubusercontent.com/49911294/107117501-9f8b2e00-68b5-11eb-80a1-f12ec27d6b7c.png)

**Comment by GuoQuanhao** [comment]
![image](https://user-images.githubusercontent.com/49911294/107117701-18d75080-68b7-11eb-8909-6140a8de6439.png)
但是我使用squeeze，它能够工作，当然我需要对它重新赋值，我认为这是`squeeze_`的bug，希望确认

**Comment by tink2123** [comment]
抱歉，我这边无法看到报错图片，可以麻烦您重新上传一下吗？

**Comment by pangyoki** [comment]
您好，图片显示不出来，看不了报错和pytorch的效果，麻烦看下能不能通过其它方式展示？
`squeeze_`是inplace方法，会修改输入Tensor直接作为输出，这样可能导致反向梯度计算错误。所以有些情况`squeeze`能用但是`squeeze_`不能用。
请检查做inplace的变量是否是`stop_gradient=False`的叶子节点，或者报了类似`Expected tensor_version == wrapper_version_snapshot`的错误？

**Comment by pangyoki** [comment]
另外，2.0.0版本paddle的`squeeze`方法采用了`View`机制，输入和输出已经是共享数据的了，与`squeeze_`方法功能相同，直接用`squeeze`也是可以的。

**Comment by pangyoki** [comment]
另外，2.0.0版本paddle的squeeze方法采用了View机制，输入和输出已经是共享数据的了，与squeeze_方法效果相同（都没有新建输出的底层数据），直接用squeeze也是可以的。

**Comment by pangyoki** [comment]
> ![image](https://user-images.githubusercontent.com/49911294/107117701-18d75080-68b7-11eb-8909-6140a8de6439.png)
> 但是我使用squeeze，它能够工作，当然我需要对它重新赋值，我认为这是`squeeze_`的bug，希望确认

看到报错图片了，是`squeeze_`的bug，近期会修复这个问题，感谢反馈！

**Comment by GuoQuanhao** [comment]
好的谢谢
