### ISSUE TITLE
only support yaml files for now

### ISSUE THREAD

**Issue by xinliyangguang** [PaddlePaddle/Paddle#30944]
为使您的问题得到快速解决，在建立Issues前，请您先通过如下方式搜索是否有相似问题:【搜索issue关键字】【使用labels筛选】【官方文档】

如果您没有查询到相似问题，为快速解决您的提问，建立issue时请提供如下细节信息：
- 标题：简洁、精准概括您的问题，例如“Insufficient Memory xxx" ”
- 版本、环境信息：
    1）PaddlePaddle版本：paddle 1.8.4
    2）CPU：预测若用CPU，请提供CPU型号，MKL/OpenBlas/MKLDNN/等数学库使用情况
    3）GPU：tesla K40 cuda 9 cudnn 7.6
    4）系统环境：linux  python 2.7.14
 注：您可以通过执行[summary_env.py](https://github.com/PaddlePaddle/Paddle/blob/develop/tools/summary_env.py)获取以上信息。
- 训练信息
    1）单机多卡
    2）显存信息
    3）Operator信息
- 复现信息：如为报错，请给出复现环境、复现步骤
- 问题描述：请详细描述您的问题，同步贴出报错信息、日志、可复现的代码片段
使用的是PaddleDetection-release-2.0beta，训练ppyolo在服务器上训练时报错：
Traceback (most recent call last):
  File "tools/train.py", line 399, in <module>
    main()
  File "tools/train.py", line 71, in main
    cfg = load_config(FLAGS.config)
  File "/home/map/zhaoxin34/baidu/detection/PaddleDetection-release-2.0-beta/ppdet/core/workspace.py", line 87, in load_config
    assert ext in ['.yml', '.yaml'], "only support yaml files for now"
AssertionError: only support yaml files for now

**Comment by qingqing01** [comment]
@xinliyangguang  是否可以贴下运行命令。 报错信息是说配置文件格式或后缀不对。
