### ISSUE TITLE
能否提供交叉编译Cross Compiling的工具链 ToolChain或者手册？新的jetson-Nano的cuda版本已经升级但是老的Inference_API环境不匹配了

### ISSUE THREAD

**Issue by Wall-ee** [PaddlePaddle/Paddle#30948]
能否提供交叉编译Cross Compiling的工具链 ToolChain或者手册？

新的jetson-Nano的cuda版本已经升级但是老的Inference_API环境不匹配了

Jetson-Nano 版本 :B01 2021年新版。
现在jetson Nano的默认  development kit 是  jetson pack 4.5  已经是 cuda10.2 tensorrt的版本也升级了， 所以 inference 的编译好的接口已经无法使用。

使用jetson nano 自行编译接口的话，速度有点太慢了…………编译了8个小时 才16%的进度。

所以能否提供一下 交叉编译的环境变量配置，或者交叉编译的手册和指南，不胜感激。

**Comment by shangzhizhou** [comment]
交叉编译工具我们正在调研，当前版本辛苦自行编译。预计paddle2.0.1开始发布jetpack4.4和jetpack4.5的预编译预测库
编译可以参考 https://github.com/PaddlePaddle/Paddle/issues/27402
