### ISSUE TITLE
关于run_check的一系列问题和建议

### ISSUE THREAD

**Issue by houj04** [PaddlePaddle/Paddle#30953]
以下都是针对这个文件：https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/utils/install_check.py

## 对纯cpu的不友好

代码中用了`assert len(paddle.static.cuda_places()) > 0`来判断当前cuda是否可用，如果不可用就会报错说`You are using GPU version PaddlePaddle, but there is no GPU`。

问题来了，在纯cpu环境下，或者纯xpu环境下，这个逻辑显然是有问题的，即`You are using GPU version PaddlePaddle`这句应该通过`fluid.core.is_compiled_with_cuda()`来获得，而不是直接扔出去。

建议：增加更多判断逻辑，先检查当前的core是否开了cuda，是否开了xpu。如果编译的时候就没开cuda，那环境检查不到cuda就是正常的，无需报错。或者说，即使报错，也是报“编译的时候没开gpu”。

现在这样的报错，是矛盾的，一会儿说编译的时候开了gpu，一会儿又没说。如下：

> WARNING:root:You are using GPU version PaddlePaddle, but there is no GPU detected on your machine. Maybe CUDA devices is not set properly.
>  Original Error is Not compiled with CUDA

## 缺少计算结果的检查

看了一下组网和代码，似乎只有一个forward计算，并没有计算结果的检查，也就是说没有检查“计算结果是否正确”。这样的话报`PaddlePaddle works well`可能不太合适。其实各种单测里面有一堆关于计算正确性的，可以拿过来跑跑。

（不确定是否我看漏掉了，如果实际是有计算结果检查的话，请指出，我学习一下……）

## 缺少对昆仑卡的检查

目前看到的版本中只有gpu和cpu两种，希望能增加针对xpu的检查。比如增加（1）编译的时候开了xpu，但是当前系统中检测不到xpu（2）xpu上跑一个简单的前向网络并验证计算结果正确，等等。

**Comment by joey12300** [comment]
@houj04 您好，感谢您的反馈。目前来看run_check主要是用来验证设备是否能运行，后续会考虑添加计算结果检查，力求保证`PaddlePaddle works well` 。后续也会考虑对xpu进行检测。

**Comment by luotao1** [comment]
对纯CPU的确实不友好。如果我在CPU机器上装了一个GPU版本的包跑CPU程序，应该也是要能跑起来，或者提示我去装CPU的包，而不是报现在的错。
