### ISSUE TITLE
layers.lstm文档问题

### ISSUE THREAD

**Issue by AshburnLee** [PaddlePaddle/Paddle#30956]
#### 环境

paddlepaddle-gpu, develop, cuda10.1, cudnn7, gcc82, python3.7

#### 问题描述
示例代码跑不通：https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/fluid/layers/lstm_cn.html#lstm
添加`paddle.enable_static()`后返回报错如下：

[Hint: Expected in_dims[1] == init_h_dims[1], but received in_dims[1]:100 != init_h_dims[1]:20.]

应该是batch_size和input.shape[1]不一致。

**Comment by joey12300** [comment]
@AshburnLee 感谢您的反馈。经测试确实无法正确运行。建议使用2.0版本的LSTM：https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/nn/layer/rnn/LSTM_cn.html#lstm

**Comment by AshburnLee** [comment]
> @AshburnLee 感谢您的反馈。经测试确实无法正确运行。建议使用2.0版本的LSTM：https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/nn/layer/rnn/LSTM_cn.html#lstm

谢谢解答！
