### ISSUE TITLE
index_fill

### ISSUE THREAD

**Issue by GuoQuanhao** [PaddlePaddle/Paddle#30952]
【论文复现】请问paddle有类似于torch的index_fill方法吗

**Comment by joey12300** [comment]
> 【论文复现】请问paddle有类似于torch的index_fill方法吗

您好，目前还没有完全一样的api可以完成torch的index_fill，会把您的需求提给相关的工作人员评审。目前有两种可以替代的方案：1. 如果不考虑动静统一和预测部署，可以尝试直接用下标的方式对指定的维度、指定的index填充值。2. 使用scatter api。用法：https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/tensor/manipulation/scatter_cn.html#scatter。

**Comment by GuoQuanhao** [comment]
好的谢谢
