### ISSUE TITLE
windows10编译paddle2.0源码报错

### ISSUE THREAD

**Issue by HuangLonghao** [PaddlePaddle/Paddle#30964]
- 标题：windows10下vs2015编译paddle2.0源码报错
- 版本、环境信息：
    1）PaddlePaddle版本：paddle2.0
    2）CPU：i7 7820x
    3）GPU：1070ti+cuda10+cudnn8.0.5+tensorRT7.0
    4）系统环境：windows10+python3.7
- 安装方式信息：
     cmake .. -G "Visual Studio 14 2015 Win64" -DWITH_GPU=ON -DWITH_TESTING=OFF -DCMAKE_BUILD_TYPE=Release -DCUDA_TOOLKIT_ROOT_DIR="C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v11.0" -DON_INFER=ON DTENSORRT_ROOT=“C:\\Program Files\\TensorRT-7.0.0.11”
- 复现信息：使用cmake完成generate之后，用vs2015编译paddle.sln解决方案中的ALL_BUILD
- 问题描述：Severity	Code	Description	Project	File	Line	Suppression State
Error	MSB3721	The command ""C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.0\bin\nvcc.exe" -gencode=arch=compute_52,code=\"sm_52,compute_52\" -gencode=arch=compute_60,code=\"sm_60,compute_60\" -gencode=arch=compute_61,code=\"sm_61,compute_61\" -gencode=arch=compute_70,code=\"sm_70,compute_70\" -gencode=arch=compute_75,code=\"sm_75,compute_75\" -gencode=arch=compute_80,code=\"sm_80,compute_80\" --use-local-env --cl-version 2015 -ccbin "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\x86_amd64" -x cu  -I"F:\paddle-2.0\Paddle\build" -I"F:\paddle-2.0\Paddle\paddle\fluid\framework\io" -I"F:\paddle-2.0\Paddle\build\third_party\install\zlib\include" -I"F:\paddle-2.0\Paddle\build\third_party\install" -I"F:\paddle-2.0\Paddle\build\third_party\install\gflags\include" -I"F:\paddle-2.0\Paddle\build\third_party\install\glog\include" -I"F:\paddle-2.0\Paddle\build\third_party\boost\src\extern_boost" -I"F:\paddle-2.0\Paddle\build\third_party\eigen3\src\extern_eigen3" -I"F:\paddle-2.0\Paddle\build\third_party\threadpool\src\extern_threadpool" -I"F:\paddle-2.0\Paddle\build\third_party\dlpack\src\extern_dlpack\include" -I"F:\paddle-2.0\Paddle\build\third_party\install\xxhash\include" -I"F:\paddle-2.0\Paddle\build\third_party\install\warpctc\include" -I"F:\paddle-2.0\Paddle\build\third_party\install\mklml\include" -I"F:\paddle-2.0\Paddle\build\third_party\install\mkldnn\include" -I"F:\paddle-2.0\Paddle\build\third_party\install\protobuf\include" -IC:\Users\pc\AppData\Local\Programs\Python\Python37\include -I"C:\Users\pc\AppData\Local\Programs\Python\Python37\Lib\site-packages\numpy\core\include" -I"F:\paddle-2.0\Paddle\build\third_party\pybind\src\extern_pybind\include" -I"F:\paddle-2.0\Paddle\build\third_party\install\cryptopp\include" -I"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.0\include" -I"F:\paddle-2.0\Paddle" -I"F:\paddle-2.0\Paddle\build\..\paddle\fluid\framework\io" -I"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.0\include"     --keep-dir x64\Release -maxrregcount=0  --machine 64 --compile -cudart static -w --expt-relaxed-constexpr -O3 -Xcompiler="/EHsc /wd4244 /wd4267 /wd4819 /bigobj /arch:AVX"    -D_WINDOWS -D_MWAITXINTRIN_H_INCLUDED -D__STRICT_ANSI__ -DNDEBUG -DGOOGLE_GLOG_DLL_DECL= -D"CUDA_VERSION_MAJOR=\"11\"" -D"CUDA_VERSION_MINOR=\"0\"" -D"CUDA_TOOLKIT_ROOT_DIR=\"C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v11.0\"" -D"CUDNN_MAJOR_VERSION=\"8\"" -DPADDLE_WITH_MKLML -DLAPACK_FOUND -DPADDLE_WITH_MKLDNN -DPADDLE_VERSION=0.0.0 -DPADDLE_VERSION_INTEGER=0 -DPADDLE_DISABLE_PROFILER -DPADDLE_WITH_AVX -D_XKEYCHECK_H -DPADDLE_DLL_INFERENCE -DPADDLE_WITH_CUDA -DEIGEN_USE_GPU -DPADDLE_ON_INFERENCE -DPADDLE_WITH_CRYPTO -D"CMAKE_INTDIR=\"Release\"" -DWIN32 -D_WINDOWS -DNDEBUG -DGOOGLE_GLOG_DLL_DECL= -D"CUDA_VERSION_MAJOR=\"11\"" -D"CUDA_VERSION_MINOR=\"0\"" -D"CUDA_TOOLKIT_ROOT_DIR=\"C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v11.0\"" -D"CUDNN_MAJOR_VERSION=\"8\"" -DPADDLE_WITH_MKLML -DLAPACK_FOUND -DPADDLE_WITH_MKLDNN -DPADDLE_VERSION=0.0.0 -DPADDLE_VERSION_INTEGER=0 -DPADDLE_DISABLE_PROFILER -DPADDLE_WITH_AVX -D_XKEYCHECK_H -DPADDLE_DLL_INFERENCE -DPADDLE_WITH_CUDA -DEIGEN_USE_GPU -DPADDLE_ON_INFERENCE -DPADDLE_WITH_CRYPTO -D"CMAKE_INTDIR=\"Release\"" -D_MBCS -Xcompiler "/EHsc /W0 /nologo /O2 /FS  /MT /GR" -o fc.dir\Release\/fc.cu.obj "F:\paddle-2.0\Paddle\paddle\fluid\operators\math\fc.cu"" exited with code 2.	fc	C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\BuildCustomizations\CUDA 11.0.targets	772

**Comment by wawltor** [comment]
稍等，我们这边的同学会跟进这个问题

**Comment by HanGaaaaa** [comment]
同问，vs2015build时候出错

**Comment by zhwesky2010** [comment]
@HuangLonghao 您好，请问不使用TRT也会报错吗，电脑上装了多少个CUDA呢？

**Comment by zhwesky2010** [comment]
@HuangLonghao 您好，这里的GPU配置是1070ti+cuda10+cudnn8.0.5+tensorRT7.0，但是实际编译的是cuda11.0，请问本机安装的是cuda10.0还是cuda11.0呢
