### ISSUE TITLE
【论文复现】gather方法

### ISSUE THREAD

**Issue by GuoQuanhao** [PaddlePaddle/Paddle#30967]
platform: aistudio
version:2.0.0

在复现pytorch代码时，我发现paddle的`gather`方法与pytorch的差异较大，想寻求一个解决方法，如下所示，paddle的`gather`方法对于index的输入维度只能在一个轴上，如果输入纬度为二维则会报错
<img width="334" alt="image" src="https://user-images.githubusercontent.com/49911294/107333180-10b62580-6af0-11eb-8d08-aabd19092007.png">
<img width="611" alt="image" src="https://user-images.githubusercontent.com/49911294/107333279-33483e80-6af0-11eb-85af-042a35fdcde7.png">

**Comment by wawltor** [comment]
目前padddle和pytorch的区别挺大的，我们有计划开发一版对齐的版本。目前的解决方案可以尝试使用gather_nd或者transpose+gather的方式

**Comment by sjhsjn1017** [comment]
> 目前padddle和pytorch的区别挺大的，我们有计划开发一版对齐的版本。目前的解决方案可以尝试使用gather_nd或者transpose+gather的方式

transpose+gather怎么实现上面pytorch的gather那样的操作？

**Comment by chenjiaoAngel** [comment]
现在，gather增加了一个新的属性axis 可以指定维度来进行gather 之前的没有这个维度
