### ISSUE TITLE
安装paddle 2.0和NCCL后，报错： 不能使用多个GPU

### ISSUE THREAD

**Issue by dawangda** [PaddlePaddle/Paddle#30978]
请问，机器有4张卡，安装paddle 2.0和NCCL后，验证安装，却报 不能使用多个ＧＰＵ，咋回事？

Python 3.8.0 (default, Jan 27 2021, 07:38:48)
[GCC 8.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import paddle.fluid
grep: warning: GREP_OPTIONS is deprecated; please use an alias or script
>>> paddle.fluid.install_check.run_check()
Running Verify Fluid Program ...
W0209 13:39:54.051972   359 device_context.cc:362] Please NOTE: device: 0, GPU Compute Capability: 7.5, Driver API Version: 10.2, Runtime API Version: 10.2
W0209 13:39:54.055487   359 device_context.cc:372] device: 0, cuDNN Version: 7.6.
Your Paddle Fluid works well on SINGLE GPU or CPU.
W0209 13:40:01.296370   359 parallel_executor.cc:596] Cannot enable P2P access from 0 to 1
W0209 13:40:01.296407   359 parallel_executor.cc:596] Cannot enable P2P access from 0 to 2
W0209 13:40:01.296437   359 parallel_executor.cc:596] Cannot enable P2P access from 0 to 3
W0209 13:40:01.296452   359 parallel_executor.cc:596] Cannot enable P2P access from 1 to 0
W0209 13:40:01.296478   359 parallel_executor.cc:596] Cannot enable P2P access from 1 to 2
W0209 13:40:01.296496   359 parallel_executor.cc:596] Cannot enable P2P access from 1 to 3
W0209 13:40:01.296511   359 parallel_executor.cc:596] Cannot enable P2P access from 2 to 0
W0209 13:40:01.296528   359 parallel_executor.cc:596] Cannot enable P2P access from 2 to 1
W0209 13:40:01.296557   359 parallel_executor.cc:596] Cannot enable P2P access from 2 to 3
W0209 13:40:01.296573   359 parallel_executor.cc:596] Cannot enable P2P access from 3 to 0
W0209 13:40:01.296591   359 parallel_executor.cc:596] Cannot enable P2P access from 3 to 1
W0209 13:40:01.296608   359 parallel_executor.cc:596] Cannot enable P2P access from 3 to 2
WARNING:root:Your Paddle Fluid has some problem with multiple GPU. This may be caused by:
 1. There is only 1 or 0 GPU visible on your Device;
 2. No.1 or No.2 GPU or both of them are occupied now
 3. Wrong installation of NVIDIA-NCCL2, please follow instruction on https://github.com/NVIDIA/nccl-tests
 to test your NCCL, or reinstall it following https://docs.nvidia.com/deeplearning/sdk/nccl-install-guide/index.html

 Original Error is: (External)  Nccl error, unhandled system error  (at /paddle/paddle/fluid/platform/nccl_helper.h:118)

Your Paddle Fluid is installed successfully ONLY for SINGLE GPU or CPU!
 Let's start deep Learning with Paddle Fluid now

**Comment by wawltor** [comment]
看起来是NCCL安装失败了，麻烦根据链接重新安装一次 https://docs.nvidia.com/deeplearning/sdk/nccl-install-guide/index.html

**Comment by wawltor** [comment]
如果还是安装有问题，可以尝试使用docker使用镜像的方式来使用paddle

**Comment by dawangda** [comment]
> 如果还是安装有问题，可以尝试使用docker使用镜像的方式来使用paddle

我就是用如下docker方式安装安装的。然后报错。

拉取预安装 PaddlePaddle 的镜像：
nvidia-docker pull registry.baidubce.com/paddlepaddle/paddle:2.0.0-gpu-cuda10.2-cudnn7
用镜像构建并进入Docker容器：
nvidia-docker run --name paddle -it -v $PWD:/paddle registry.baidubce.com/paddlepaddle/paddle:2.0.0-gpu-cuda10.2-cudnn7 /bin/bash

**Comment by KyrieHee** [comment]
system:

ubuntu 20.04 server
NV T4 * 4
paddlepaddle-gpu  2.0.2.post110

after download  nccl_2.7.8-1+cuda11.0_x86_64.txz

just run it:
```
tar -zxvf nccl_2.7.8-1+cuda11.0_x86_64.txz
mv nccl_2.7.8-1+cuda11.0_x86_64/include/* /usr/local/cuda/include/
mv nccl_2.7.8-1+cuda11.0_x86_64/lib/* /usr/local/cuda/lib64/

```

It works!

**Comment by rocketbear** [comment]
这个问题我必须回答。
参考：https://zhuanlan.zhihu.com/p/396564352

docker run创建容器时加入选项 --ipc=host，即：
docker run --ipc=host [其他选项...]
