### ISSUE TITLE
  请问Paddle中怎么实现对训练参数手动修改梯度值的功能？

### ISSUE THREAD

**Issue by eepgxxy** [PaddlePaddle/Paddle#30979]
目前没有在Paddle中找到该实现的方法。直接对grad或gradient属性赋值报错。求指教。

**Comment by gongweibao** [comment]
目前还没有，我们记录一下。有了进展我们及时release出来。

**Comment by Wongziseoi** [comment]
来催一催

**Comment by gongweibao** [comment]
^_^

**Comment by lyuwenyu** [comment]
> 目前没有在Paddle中找到该实现的方法。直接对grad或gradient属性赋值报错。求指教。

1.  Tensor.grad.set_value
2. 给需要修改grad的Tensor注册一个反向的hook
