### ISSUE TITLE
您好，我在多卡训练过程中，想要载入之前的模型，laod的过程没有报错

### ISSUE THREAD

**Issue by moneyQyh** [PaddlePaddle/Paddle#30983]
为使您的问题得到快速解决，在建立Issue前，请您先通过如下方式搜索是否有相似问题:【搜索issue关键字】【使用labels筛选】【官方文档】

建立issue时，为快速解决问题，请您根据使用情况给出如下信息：
- 标题：简洁、精准描述您的问题，例如“ssd 模型前置lstm报错  ”
- 版本、环境信息：
    1）PaddlePaddle版本：请提供PaddlePaddle版本号，例如1.1或CommitID
    2）CPU：请提供CPU型号，MKL/OpenBlas/MKLDNN/等数学库的使用情况
    3）GPU：请提供GPU型号，CUDA和CUDNN版本号
    4）系统环境：请说明系统类型、版本（例如Mac OS 10.14），Python版本
 注：您可以通过执行[summary_env.py](https://github.com/PaddlePaddle/Paddle/blob/develop/tools/summary_env.py)获取以上信息。
- 模型信息
    1）模型名称 2）使用数据集名称 3）使用算法名称 4）模型链接
- 复现信息：如为报错，请给出复现环境、复现步骤
- 问题描述：请详细描述您的问题，同步贴出报错信息、日志/代码关键片段

Thank you for contributing to PaddlePaddle.
Before submitting the issue, you could search issue in the github.Probably there was a similar issue submitted or resolved before.
If there is no solution,please make sure that this is a issue of models including the following details:
**System information**
-PaddlePaddle version （eg.1.1）or CommitID
-CPU: including CPUMKL/OpenBlas/MKLDNN version
-GPU: including CUDA/CUDNN version
-OS Platform (eg.Mac OS 10.14)
-Python version
-Name of Models&Dataset/details of operator
Note: You can get most of the information by running [summary_env.py](https://github.com/PaddlePaddle/Paddle/blob/develop/tools/summary_env.py). 
**To Reproduce**
Steps to reproduce the behavior
**Describe your current behavior**
**Code to reproduce the issue**
**Other info / logs**

**Comment by moneyQyh** [comment]
但是在load之后，就卡住了，查看了显卡，发现程序也没有被kill

**Comment by gongweibao** [comment]
咱们这边还有问题吗？

**Comment by moneyQyh** [comment]
这个问题我已经解决了，谢谢回复

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: gongweibao <notifications@github.com>
发送时间: Saturday, February 13, 2021 5:13:19 PM
收件人: PaddlePaddle/Paddle <Paddle@noreply.github.com>
抄送: moneyQyh <CheinYucci@outlook.com>; State change <state_change@noreply.github.com>
主题: Re: [PaddlePaddle/Paddle] 您好，我在多卡训练过程中，想要载入之前的模型，laod的过程没有报错 (#30983)


能否把可实现的环境贴一下？

―
