### ISSUE TITLE
我建了一个公开项目“黄金价格预测”，运行这里报错，不知道怎么解决，求帮忙

### ISSUE THREAD

**Issue by guojiahuiEmily** [PaddlePaddle/Paddle#30988]
公开项目地址
https://aistudio.baidu.com/aistudio/projectdetail/1525691

报错信息（v2版本）：
ValueError: (InvalidArgument) input and filter data type should be consistent [Hint: Expected input_data_type == filter_data_type, but received input_data_type:6 != filter_data_type:5.] (at

您可以切换到covid版本，人家是ok的，我的版本就报错

**Comment by gongweibao** [comment]
我这里总显示找不到对应的文件。你是如何处理这个问题的？
![image](https://user-images.githubusercontent.com/10721757/107846858-1d08ee00-6e22-11eb-98ab-05eb7fbf0592.png)

**Comment by gongweibao** [comment]
```[Hint: Expected input_data_type == filter_data_type, but received input_data_type:6 != filter_data_type:5.] (at /paddle/paddle/fluid/operators/conv_op.cc:175)```

这个的意思是说类型不匹配， fp64!=fp32。

**Comment by guojiahuiEmily** [comment]
> 我这里总显示找不到对应的文件。你是如何处理这个问题的？
> ![image](https://user-images.githubusercontent.com/10721757/107846858-1d08ee00-6e22-11eb-98ab-05eb7fbf0592.png)

您看一下，您那csv文件夹下面有那个文件吗

**Comment by guojiahuiEmily** [comment]
> `[Hint: Expected input_data_type == filter_data_type, but received input_data_type:6 != filter_data_type:5.] (at /paddle/paddle/fluid/operators/conv_op.cc:175)`
> 
> 这个的意思是说类型不匹配， fp64!=fp32。

那么，该怎么解决呢，可否把您解决后的项目网址发一下

**Comment by skywalk163** [comment]
在项目的数据预处理部分，加上转换函数，把float64类型转换为float32即可。如下：

`


        train_data = daily_cases[:-TEST_DATA_SIZE]
        # 加上下面这句转换函数
        train_data = train_data.astype('float32')
        test_data = daily_cases[-TEST_DATA_SIZE:]

        print("The number of the samples in train set is : %i"%train_data.shape[0])
`


ps ：数据预处理里有两句print语句报错，我直接注释掉就能运行了 。

**Comment by guojiahuiEmily** [comment]
非常感谢。我已运行成功。 预测效果还不错。
<img width="641" alt="hj" src="https://user-images.githubusercontent.com/74049862/108582971-5802a880-7371-11eb-803e-367df02be7fc.png">
