### ISSUE TITLE
wutai01 MPI的paddle v1 训练时save model出现的问题？

### ISSUE THREAD

**Issue by guozhizou** [PaddlePaddle/Paddle#3099]
```
I0727 09:40:11.928058  8975 TrainerInternal.cpp:165]  Batch=145700 samples=18649600 AvgCost=0 CurrentCost=0 Eval:  CurrentEval: 
```
1. 训练全程中，cost都是0这个问题出现了有段时间了；
2. 在wutai01的MPI V1训练的模型，因为网络中用到cosine计算两个生成向量的相似度```cos_sim(a=user_dim, b=view_dim, scale=1)```，当把成功训练结束的model在本地做test计算的时候，出现生成的那两个向量都是0向量（训练的数据也测试了，情况一样），导致做cosine时失败。而模型在训练的时候计算相似度都是正常，只能推断是不是集群在save模型的时候的bug。（此外，这个网络在local模式下一切都是正常的，且在前段时间在MPI上也是正常的）

MPI任务的链接：http://10.87.137.36:8920/fileview.html?path=/home/disk1/normandy/maybach/40968/

**Comment by lcy-seso** [comment]
从配置看，网络的激活全部是relu，我怀疑是relu的问题。模型存储没有这么脆弱。

- 在训练的时候，ReLU单元比较脆弱并且可能“死掉”。举例来说，当一个很大的梯度流过ReLU的神经元的时候，可能会导致梯度更新到一种特别的状态，在这种状态下神经元将无法被其他任何数据点再次激活。如果这种情况发生，那么从此所以流过这个神经元的梯度将都变成0。

**Comment by guozhizou** [comment]
嗯，还在验证是不是relu导致的dead unit问题。
但是， 
1. 能成功训练，在测试时出现了问题； 
2. 跑了三次都是同样的问题； 
3. 之前一直采用这样的网络是没有问题的（数据处理逻辑都是一样的，本地运行也部分印证了）

**Comment by lcy-seso** [comment]
请还原会之前一样的数据，一样的配置，一样的设置，确认是paddle的问题。否则我们无从查起。

**Comment by CDDB** [comment]
AvgCost=0 CurrentCost=0   这个问题有trace么？  会干扰判断。

**Comment by lcy-seso** [comment]
AvgCost=0 CurrentCost=0 的啥问题？

**Comment by guozhizou** [comment]
参数都没有变化，但之前的数据字典更新了，训练数据无法恢复到原样。 出现这样的情况，貌似和训练时出现avgcost=0 currentcost= 这个问题是同时出现的，具体还待tanh的结果出来，看是否是一样的情况来判断。

**Comment by lcy-seso** [comment]
1. 怎么排除数据的问题？
2. 不可能怎么改变都不能改变 `avgcost=0 currentcost= 0`，什么条件不出现 `avgcost=0 currentcost=0` ？

**Comment by lcy-seso** [comment]
数据处理逻辑都是一样的，不能排除数据无异常。

**Comment by guozhizou** [comment]
```
I0728 17:24:47.582365 25615 TrainerInternal.cpp:165]  Batch=110 samples=56320 AvgCost=0.161602 CurrentCost=0.0999691 Eval:  CurrentEval:

I0728 17:24:48.212803 25615 TrainerInternal.cpp:165]  Batch=120 samples=61440 AvgCost=0.15781 CurrentCost=0.1161 Eval:  CurrentEval:

I0728 17:24:49.328068 25615 TrainerInternal.cpp:165]  Batch=130 samples=66560 AvgCost=0.156435 CurrentCost=0.139936 Eval:  CurrentEval:

I0728 17:24:50.238536 25615 TrainerInternal.cpp:165]  Batch=140 samples=71680 AvgCost=0.155359 CurrentCost=0.141367 Eval:  CurrentEval:

I0728 17:24:51.023105 25615 TrainerInternal.cpp:165]  Batch=150 samples=76800 AvgCost=0.153028 CurrentCost=0.120404 Eval:  CurrentEval:

I0728 17:24:51.955370 25615 TrainerInternal.cpp:165]  Batch=160 samples=81920 AvgCost=0.151533 CurrentCost=0.129097 Eval:  CurrentEval:

I0728 17:24:52.876628 25615 TrainerInternal.cpp:165]  Batch=170 samples=87040 AvgCost=0.150316 CurrentCost=0.130859 Eval:  CurrentEval:

I0728 17:24:53.815397 25615 TrainerInternal.cpp:165]  Batch=180 samples=92160 AvgCost=0.149469 CurrentCost=0.135065 Eval:  CurrentEval:

I0728 17:24:54.696384 25615 TrainerInternal.cpp:165]  Batch=190 samples=97280 AvgCost=0.147974 CurrentCost=0.121052 Eval:  CurrentEval:
```
这是脚本本地跑part的日志。
MPI的当把sparse_update关闭，cost好像就正常了。
其实，问题是怀疑是不是wutai01的paddle环境问题。所以也尝试了提交到wutai02，wutai的集群，一直报错connet的问题。

**Comment by lcy-seso** [comment]
sparse_update 一般只对 embeding层用。其它层已经不再是sparse的了。

**Comment by guozhizou** [comment]
嗯，就是关闭稀疏层的

**Comment by CDDB** [comment]
sparse_update 一般只对 embeding层用。其它层已经不再是sparse的了。
--
尝试下来就是这样。另外一个任务数据量小，所以一样的配置和数据，用单节点训练， cost的log就正常。可以看这个issue的说明 https://github.com/PaddlePaddle/Paddle/issues/2987

**Comment by typhoonzero** [comment]
I'm closing this due to low activity, feel free to reopen.
