### ISSUE TITLE
在做硕士论文的时候经常用到混淆矩阵，希望大佬们能开发一个高层API导入混淆矩阵的接口

### ISSUE THREAD

**Issue by gaorui999** [PaddlePaddle/Paddle#30991]
欢迎您对PaddlePaddle提出建议，非常感谢您对PaddlePaddle的贡献！
在留下您的建议时，辛苦您同步提供如下信息：
- 版本、环境信息
1）PaddlePaddle版本：2.0
2）CPU/GPU：ai STUDIO训练
3）系统环境：WINDOWS10

- 建议描述：请您详细描述，您认为需优化的功能
在做硕士论文的时候经常用到混淆矩阵，希望大佬们能开发一个高层API导入混淆矩阵的接口，类似于PaddleX客户端里预测模型部分的那种

**Comment by Superjomn** [comment]
可以直接给tensor 设置值，具混淆矩阵的值可以 numpy 生成之后，再设置到具体的tensor里
