### ISSUE TITLE
<paddle.fluid.dataloader.dataloader_iter._DataLoaderIterMultiProcess at 0x7f2bb39ed850> ERROR:root:DataLoader reader thread raised an exception!

### ISSUE THREAD

**Issue by liu824** [PaddlePaddle/Paddle#30995]
自定义数据读取时出现问题
报错：
ERROR:root:DataLoader reader thread raised an exception!
---------------------------------------------------------------------------SystemError                               Traceback (most recent call last)<ipython-input-12-e0d0f598d06c> in <module>
    130 
    131 
--> 132     for index, data in enumerate(data()):
    133         if index == 20:
    134             break
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dataloader/dataloader_iter.py in __next__(self)
    786 
    787             if in_dygraph_mode():
--> 788                 data = self._reader.read_next_var_list()
    789             else:
    790                 if self._return_list:
SystemError: (Fatal) Blocking queue is killed because the data reader raises an exception.
  [Hint: Expected killed_ != true, but received killed_:1 == true:1.] (at /paddle/paddle/fluid/operators/reader/blocking_queue.h:158)

**Comment by seiriosPlus** [comment]
信息量比较少，坏疑是用户的Reader的编写有异常，能否提供下更详细的demo？
