### ISSUE TITLE
内存消耗随pass数增长，可能存在内存管理问题

### ISSUE THREAD

**Issue by jueljust** [PaddlePaddle/Paddle#310]
demo/image_classification

pass=0 mem%=24.4% mapped: 8370660K    writeable/private: 8036476K    shared: 0K
pass=6 mem%=37.4% 

如果不是，请提供内存消耗与pass配置数据的关系，方便计算需要的资源

测试运行在local模式下

**Comment by reyoung** [comment]
@jueljust 麻烦问下，这个mem%是怎么计算出来的呢？

**Comment by jueljust** [comment]
@reyoung top时的进程MEM%

**Comment by gangliao** [comment]
#311

**Comment by reyoung** [comment]
@jueljust Are you using CACHE_PASS_IN_MEM in your dataprovider?

**Comment by jueljust** [comment]
@reyoung 我用的就是demo的image_classification 没有修改任何代码和配置
搜代码没搜到cache，应该就是用默认配置

**Comment by reyoung** [comment]
@jueljust 那你是使用的GPU `--use_gpu=1`?

**Comment by jueljust** [comment]
--use_gpu=0
--use_cpu
机器上没有独立显卡

**Comment by qingqing01** [comment]
close via #https://github.com/PaddlePaddle/Paddle/pull/323
