### ISSUE TITLE
使用paddle.Model完成模型的封装，将网络结构组合成一个可快速使用高层API进行训练和预测的“类”？--是类还是对象

### ISSUE THREAD

**Issue by A-Pai** [PaddlePaddle/Paddle#31002]
https://www.paddlepaddle.org.cn/documentation/docs/zh/guides/02_paddle2.0_develop/05_train_eval_predict_cn.html
![image](https://user-images.githubusercontent.com/5112397/107866707-73237300-6eae-11eb-8f8b-92c3e4cfffcd.png)

**Comment by A-Pai** [comment]
https://www.paddlepaddle.org.cn/documentation/docs/zh/guides/02_paddle2.0_develop/01_quick_start_cn.html

这里说生成“实例”
![image](https://user-images.githubusercontent.com/5112397/107866782-31df9300-6eaf-11eb-833b-93eeb5ed541d.png)

**Comment by A-Pai** [comment]
再看这里
https://www.paddlepaddle.org.cn/documentation/docs/zh/guides/01_paddle2.0_introduction/upgrade_guide_cn.html
![image](https://user-images.githubusercontent.com/5112397/107867763-6c99f900-6eb8-11eb-8a10-83e021ec6dce.png)

**Comment by TCChenlong** [comment]
第一个应该是对象，后面那一句表意有些不清楚，我们修改下，感谢反馈~

**Comment by TCChenlong** [comment]
已经更新了相关的说明，感谢反馈；

**Comment by A-Pai** [comment]
> 已经更新了相关的说明，感谢反馈；

动作迅速，很有活力，对飞桨更有信心
