### ISSUE TITLE
[Windows, python 2.7] Error message with long-type numbers do not match the pattern.

### ISSUE THREAD

**Issue by wojtuss** [PaddlePaddle/Paddle#31007]
System information
-PaddlePaddle version （eg.1.1）or CommitID: b08ae36 (develop)
-CPU: including CPUMKL/OpenBlas/MKLDNN version: Intel(R) Core(TM) i9-9940X CPU, no MKLDNN
-GPU: including CUDA/cuDNN version: none
-OS Platform and Distribution(eg.Mac OS 10.14): Windows Server 2019 Standard Evaluation
-Python version: 2.7.17
Note: You can get most of the information by running summary_env.py.
To Reproduce
Execute:

ctest -C Release -V -R "test_feed_data_check_shape_type"
Describe your current behavior
The following error occurs
```
test_feed_data_check_shape_type failed
 F
======================================================================
FAIL: test (test_feed_data_check_shape_type.TestFeedData)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "D:\wojtuss\PP\Paddle\b\python\paddle\fluid\tests\unittests\test_feed_data_check_shape_type.py", line 100, in test
    error_shape_list))
AssertionError: "The fed Variable u'data' should have dimensions = 4, shape = (-1L, 3L, 4L, 8L), but received fed shape [10L, 3L, 4L, 5L] on each device" != "The fed Variable u'data' should have dimensions = 4, shape = (-1, 3, 4, 8), but received fed shape [10, 3, 4, 5] on each device"

----------------------------------------------------------------------
```
Long-type numbers are printed with `L` suffix here and do not match the pattern (without `L`).

**Comment by lidanqing-vv** [comment]
This is the only test that failed in our local Windows CI. If there are any suggestions, please let us know.

**Comment by lidanqing-vv** [comment]
Nobody fix it locally
