### ISSUE TITLE
提问：paddlehub2.0使用mobilenetV2模型报错

### ISSUE THREAD

**Issue by Fitz-Fitz** [PaddlePaddle/Paddle#31003]
AttributeError: 'ModuleV1_9b84d0ff5bc6072a0db18dc325eb9873' object has no attribute 'parameters'

请问这是因为hub里的mobilenetV2没有更新到paddle2.0导致的吗

**Comment by chunzhang-hub** [comment]
@Fitz-Fitz 请问您这边的paddlehub和paddle版本是多少呢，建议可以先更新到2.0的paddle和hub，在试试看

**Comment by Fitz-Fitz** [comment]
> @Fitz-Fitz 请问您这边的paddlehub和paddle版本是多少呢，建议可以先更新到2.0的paddle和hub，在试试看

嗯嗯已确定，paddle和paddlehub都是2.0的

**Comment by Fitz-Fitz** [comment]
同时2.0装载模型时：
model = hub.Module(name="mobilenet_v2_imagenet",label_list=label)
也会报错:
__init__() got an unexpected keyword argument 'label_list'

**Comment by Fitz-Fitz** [comment]
hub里很多CV模型都存在这个问题，只有resnet50_vd_imagenet_ssld模型支持5分类的label_list。所以check一下，是因为这些模型没有升级到paddle2.0.0所以不和paddlehub2.0兼容吗

**Comment by Fitz-Fitz** [comment]
hub里很多CV模型都存在这个问题，只有resnet50_vd_imagenet_ssld模型支持5分类的label_list。所以想确定一下，是因为这些模型没有升级到paddle2.0.0所以不和paddlehub2.0兼容吗

**Comment by D-DanielYang** [comment]
> hub里很多CV模型都存在这个问题，只有resnet50_vd_imagenet_ssld模型支持5分类的label_list。所以想确定一下，是因为这些模型没有升级到paddle2.0.0所以不和paddlehub2.0兼容吗


您好，能提供下您使用的核心代码片段和系统环境么？目前的信息没有办法完全复现您的问题，期待您的回复

**Comment by Fitz-Fitz** [comment]
> > hub里很多CV模型都存在这个问题，只有resnet50_vd_imagenet_ssld模型支持5分类的label_list。所以想确定一下，是因为这些模型没有升级到paddle2.0.0所以不和paddlehub2.0兼容吗
> 
> 您好，能提供下您使用的核心代码片段和系统环境么？目前的信息没有办法完全复现您的问题，期待您的回复

感谢您的重视，复现代码如下：
import paddlehub as hub

model = hub.Module(name="mobilenet_v2_imagenet",label_list=["1","2","3","4"])

报错信息：
__init__() got an unexpected keyword argument 'label_list'

运行环境为python 3.7、paddle2.0.0，paddlehub2.0.0

**Comment by Fitz-Fitz** [comment]
> > hub里很多CV模型都存在这个问题，只有resnet50_vd_imagenet_ssld模型支持5分类的label_list。所以想确定一下，是因为这些模型没有升级到paddle2.0.0所以不和paddlehub2.0兼容吗
> 
> 您好，能提供下您使用的核心代码片段和系统环境么？目前的信息没有办法完全复现您的问题，期待您的回复

您也可以查看这个项目的[PaddleHub2.0]版本进行查看复现

**Comment by Fitz-Fitz** [comment]
> > hub里很多CV模型都存在这个问题，只有resnet50_vd_imagenet_ssld模型支持5分类的label_list。所以想确定一下，是因为这些模型没有升级到paddle2.0.0所以不和paddlehub2.0兼容吗
> 
> 您好，能提供下您使用的核心代码片段和系统环境么？目前的信息没有办法完全复现您的问题，期待您的回复

https://aistudio.baidu.com/aistudio/projectdetail/782743
您也可以查看这个项目的[PaddleHub2.0.0]版本进行查看复现
