### ISSUE TITLE
paddle2.0 预测库出现调用时报错Load symbol getPluginRegistry failed

### ISSUE THREAD

**Issue by LiangYongAI** [PaddlePaddle/Paddle#31033]
- 版本、环境信息：
    1）PaddlePaddle版本：release 2.0
    2）GPU：RTX2060、CUDA 10.2和CUDNN7.6.5 TensorRT 7.2.2.3
  
首先编译paddle库：
按照官方文档，但因为要用tensorrt，特意加上了-DWITH_TENSORRT=ON -DTENSORRT_ROOT="D:/github/TensorRT-7.2.2.3"
完整的编译命令是：cmake .. -G "Visual Studio 15 2017" -A x64 -T host=x64 -DCMAKE_BUILD_TYPE=Release -DWITH_MKL=ON -DWITH_GPU=ON -DON_INFER=ON -DWITH_PYTHON=OFF -DWITH_TENSORRT=ON -DCUDA_TOOLKIT_ROOT_DIR="C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.2" -DTENSORRT_ROOT="D:/github/TensorRT-7.2.2.3"

编译后生成的version.txt 如下：
GIT COMMIT ID: 
WITH_MKL: ON
WITH_MKLDNN: ON
WITH_GPU: ON
CUDA version: 10.2
CUDNN version: v7.6
CXX compiler version: 19.16.27045.0
WITH_TENSORRT: ON
TensorRT version: v7

这里有一个问题，我之前用的paddle1.6编译的时候，编译完成后，在paddle_inference_install_dir\third_party\install下会有tensorrt目录，但用Paddle2.0编译时没有这个目录了，于是我把TensorRT-7.2.2.3里的include和lib目录复制过来了。

然后把Paddle推断库用在自己的C++工程里，出现
You are using Paddle compiled with TensorRT, but TensorRT dynamic library is not found. Ignore this if TensorRT is not needed.
WARNING: Logging before InitGoogleLogging() is written to STDERR
E0218 22:17:37.719820 10536 port.h:50] Load symbol getPluginRegistry failed.

值得注意的是，这个工程在paddle1.6的推断库里可以正常运行。

另外我要用tensorRT.

请百度的同学帮忙看看，谢谢！

**Comment by cryoco** [comment]
您好，可能是依赖库版本不匹配的原因，cuda、cudnn、trt版本需要满足nvidia官方的依赖关系，可以在nvidia官网下载页面查到：

trt7.2.2.3:
cuda11.1 + cudnn8.0
cuda11.0 + cudnn8.0
cuda10.2 + cudnn8.0

trt7.2.1.6:
cuda11.1 + cudnn8.0
cuda11.0 + cudnn8.0
cuda10.2 + cudnn8.0

trt7.1.3.4:
cuda11.0 + cudnn8.0

trt7.0.0.11:
cuda10.2 + cudnn7.6
cuda10.0 + cudnn7.6
cuda9.0 + cudnn7.6

**Comment by LiangYongAI** [comment]
@cryoco 问题解决，谢谢

**Comment by Yaoxingtian** [comment]
> @cryoco 问题解决，谢谢

您好，可以分享下是怎么解决的吗？ 我也遇到这个问题了，谢谢

**Comment by LiangYongAI** [comment]
软件换对应版本就可以了发自我的荣耀手机-------- 原始邮件 --------发件人： Yaoxingtian ***@***.***>日期： 2021年3月23日周二 上午10:53收件人： PaddlePaddle/Paddle ***@***.***>抄送： liangyong ***@***.***>, Author ***@***.***>主    题： Re: [PaddlePaddle/Paddle] paddle2.0 预测库出现调用时报错Load symbol getPluginRegistry failed (#31033)



@cryoco 问题解决，谢谢



您好，可以分享下是怎么解决的吗？ 我也遇到这个问题了，谢谢

**Comment by Yaoxingtian** [comment]
> 软件换对应版本就可以了发自我的荣耀手机-------- 原始邮件 --------发件人： Yaoxingtian ***@***.***>日期： 2021年3月23日周二 上午10:53收件人： PaddlePaddle/Paddle ***@***.***>抄送： liangyong ***@***.***>, Author ***@***.***>主 题： Re: [PaddlePaddle/Paddle] paddle2.0 预测库出现调用时报错Load symbol getPluginRegistry failed (#31033) @cryoco 问题解决，谢谢 您好，可以分享下是怎么解决的吗？ 我也遇到这个问题了，谢谢 —You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

你改了什么？ 我的cuda10.1 cudnn7.6的没错啊

**Comment by Liudyan** [comment]
> > 软件换对应版本就可以了发自我的荣耀手机-------- 原始邮件 --------发件人： Yaoxingtian _**@**_._**>日期： 2021年3月23日周二 上午10:53收件人： PaddlePaddle/Paddle _**@**_.**_>抄送： liangyong _**@**_._**>, Author _**@**_.**_>主 题： Re: [PaddlePaddle/Paddle] paddle2.0 预测库出现调用时报错Load symbol getPluginRegistry failed (#31033) @cryoco 问题解决，谢谢 您好，可以分享下是怎么解决的吗？ 我也遇到这个问题了，谢谢 —You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
> 
> 你改了什么？ 我的cuda10.1 cudnn7.6的没错啊

我是将对应的TensorRT-6.0.1.5.Windows10.x86_64.cuda-10.1.cudnn7.6配置好，也就是手动在vs里面配置lib,include,将lib中的dll放到项目文件中，或者放到环境变量中，提示缺少动态库TensorRT中的dll,在lib中。
