### ISSUE TITLE
如果要修改bi-lstm中forget gate的初始bias，应该如何修改？

### ISSUE THREAD

**Issue by cbtpkzm** [PaddlePaddle/Paddle#3104]
现阶段只知道似乎可以在paddle/cuda/include/hl_cpu_lstm.cuh中暴力修改然后重编译，如果需要在python中传参需要修改哪些接口？

**Comment by lcy-seso** [comment]
想精确控制 LSTM 每个计算单元，比如状态，门的初始化，bias等等，请使用 trainer_config_helper/networks 下面的lstmemory_group.
