### ISSUE TITLE
运行退出机制

### ISSUE THREAD

**Issue by kuizhiqing** [PaddlePaddle/Paddle#31053]
ps 模式下，训练完成 worker 主动退出，但是 pserver 会持续运行，且不处理系统退出 signal，需要修复。

* 自动退出，或者
* 处理系统退出 signal

collective 模式下，有可能由于数据不均匀导致不退出，需要完善退出机制和处理系统 signal。

**Comment by ceci3** [comment]
我反馈一下，感谢~
