### ISSUE TITLE
是否像pytorch一样包含了经典模型？

### ISSUE THREAD

**Issue by A-Pai** [PaddlePaddle/Paddle#31089]
是否像pytorch一样包含了经典模型？--pytorch中有torchvision.models模块，包含了大量CV经典模型，不仅包含了标准的实现代码，同时还提供了与训练权重。
paddle也是这样？何处有介绍？怎么用？

**Comment by A-Pai** [comment]
已经发现了，https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/vision/models/lenet/LeNet_cn.html

**Comment by ysh329** [comment]
此外还有相关的仓库如 https://github.com/PaddlePaddle/models ，PaddleCV，PaddleOCR等等，都在PaddlePaddle下面：
https://github.com/PaddlePaddle/Paddle/issues/31089

**Comment by A-Pai** [comment]
好的，谢谢
