### ISSUE TITLE
linux docker方式安装paddle2，多卡，始终报错

### ISSUE THREAD

**Issue by dawangda** [PaddlePaddle/Paddle#31088]
用linux docker方式安装paddle2，机器4卡，nccl是安装在native 的Linux主机上，而不是安装在docker里，对吧？

nccl安装在native 的Linux主机上了，安装完后，验证安装，始终报错。

Python 3.8.0 (default, Jan 27 2021, 07:38:48)
[GCC 8.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.

import paddle.fluid
grep: warning: GREP_OPTIONS is deprecated; please use an alias or script
paddle.fluid.install_check.run_check()
Running Verify Fluid Program ...
W0209 13:39:54.051972 359 device_context.cc:362] Please NOTE: device: 0, GPU Compute Capability: 7.5, Driver API Version: 10.2, Runtime API Version: 10.2
W0209 13:39:54.055487 359 device_context.cc:372] device: 0, cuDNN Version: 7.6.
Your Paddle Fluid works well on SINGLE GPU or CPU.
W0209 13:40:01.296370 359 parallel_executor.cc:596] Cannot enable P2P access from 0 to 1
W0209 13:40:01.296407 359 parallel_executor.cc:596] Cannot enable P2P access from 0 to 2
W0209 13:40:01.296437 359 parallel_executor.cc:596] Cannot enable P2P access from 0 to 3
W0209 13:40:01.296452 359 parallel_executor.cc:596] Cannot enable P2P access from 1 to 0
W0209 13:40:01.296478 359 parallel_executor.cc:596] Cannot enable P2P access from 1 to 2
W0209 13:40:01.296496 359 parallel_executor.cc:596] Cannot enable P2P access from 1 to 3
W0209 13:40:01.296511 359 parallel_executor.cc:596] Cannot enable P2P access from 2 to 0
W0209 13:40:01.296528 359 parallel_executor.cc:596] Cannot enable P2P access from 2 to 1
W0209 13:40:01.296557 359 parallel_executor.cc:596] Cannot enable P2P access from 2 to 3
W0209 13:40:01.296573 359 parallel_executor.cc:596] Cannot enable P2P access from 3 to 0
W0209 13:40:01.296591 359 parallel_executor.cc:596] Cannot enable P2P access from 3 to 1
W0209 13:40:01.296608 359 parallel_executor.cc:596] Cannot enable P2P access from 3 to 2
WARNING:root:Your Paddle Fluid has some problem with multiple GPU. This may be caused by:

There is only 1 or 0 GPU visible on your Device;
No.1 or No.2 GPU or both of them are occupied now
Wrong installation of NVIDIA-NCCL2, please follow instruction on https://github.com/NVIDIA/nccl-tests
to test your NCCL, or reinstall it following https://docs.nvidia.com/deeplearning/sdk/nccl-install-guide/index.html
Original Error is: (External) Nccl error, unhandled system error (at /paddle/paddle/fluid/platform/nccl_helper.h:118)

Your Paddle Fluid is installed successfully ONLY for SINGLE GPU or CPU!
Let's start deep Learning with Paddle Fluid now

**Comment by ysh329** [comment]
根据你的描述，你的机器有4卡，但是paddle只能识别出0号GPU。而且根据最后的log显示，当前机器仅识别单卡。

可以尝试：

1. 根据报错，可能你的安装存在问题，如果需要多卡的NCCL支持，可能需要重新安装根据log里的地址；
2. 单机多卡的使用文档：https://www.paddlepaddle.org.cn/documentation/docs/zh/guides/01_paddle2.0_introduction/upgrade_guide_cn.html#id14
3. 根据官网默认的文档，目前找不到cudnn7.6，默认最低的cudnn版本是9.0，可以尝试升级：https://www.paddlepaddle.org.cn/install/quick?docurl=/documentation/docs/zh/2.0/install/pip/linux-pip.html

**Comment by ysh329** [comment]
nccl需要装到docker里，试试是否行（根据内部同学反馈）

**Comment by wadefelix** [comment]
您好，不知道您基于nvidia/cuda的哪个镜像作为基础镜像的。
有一些nvidia/cuda的镜像内，cuda安装后没有为其so建立短名字的软链接，导致无法找到它。

你可以看看是不是这个情况，可以使用如下指令予以更正
```Dockerfile
WORKDIR /usr/local/cuda/lib64
RUN find lib*.so.* -type f | awk '{short=$1; sub(/\.so.*/,".so",short) ; print $1,short}' |sort -r |uniq -f 1 | xargs -n2 ln -s -f \
 && find /usr/lib/x86_64-linux-gnu  -name 'libcud*' -type f | awk '{short=$1; sub(/\.so.*/,".so",short); sub(/.*\//,"",short) ; print $1,short}'|sort -r |uniq -f 1 | xargs -n2 ln -s -f
```
