### ISSUE TITLE
@paddle.jit.to_static的文档是不是矛盾了？有些看不明白

### ISSUE THREAD

**Issue by A-Pai** [PaddlePaddle/Paddle#31094]
https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/fluid/dygraph/jit/declarative_cn.html

![图片1](https://user-images.githubusercontent.com/5112397/108648026-21559b00-74f5-11eb-9645-3885b3dbb125.png)

装饰器应该返回的是函数啊？

**Comment by Aurelius84** [comment]
1. `to_static`装饰器支持装饰普通function、类method，以及用户定义的模型Net实例（默认会在forward函数上进行装饰）。被装饰的函数会被返回一个StaticFunction对象，重写了`__call__`，以实现静态图执行
2. 被`to_static` 装饰的函数，内部会以静态图方式执行。比如 FuncA &rarr; FuncB &rarr; FuncC，如果只有中间的FuncB被装饰了，考虑到A和B依旧是动态图执行，所以被装饰后的FuncB内部以静态图运行，结果返回的是动态图Tensor，以支持“局部装饰”的功能
