### ISSUE TITLE
“paddle.jit.save”中“@paddle.jit.to_static”的作用是？

### ISSUE THREAD

**Issue by A-Pai** [PaddlePaddle/Paddle#31096]
https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/fluid/dygraph/jit/save_cn.html

![image](https://user-images.githubusercontent.com/5112397/108648749-fc622780-74f6-11eb-88b0-f69bb772ed1c.png)

其中“@paddle.jit.to_static”的作用是？
没有这一句，后边的paddle.jit.save就会报错

**Comment by lijianshe02** [comment]
to_static是paddle模型动态图转为静态图的接口，具体请参考https://www.paddlepaddle.org.cn/documentation/docs/zh/guides/04_dygraph_to_static/index_cn.html
