### ISSUE TITLE
这个例子前后不一致，不便于读者理解和学习

### ISSUE THREAD

**Issue by A-Pai** [PaddlePaddle/Paddle#31091]
https://www.paddlepaddle.org.cn/tutorials/projectdetail/1516124
前边讲到的网络结构和输入数据的维度是32*32，也分析了各层之后的数据维度变化：
![image](https://user-images.githubusercontent.com/5112397/108600438-2c63da80-73d2-11eb-9149-cd0bf5777623.png)

但是后边代码中输入数据的维度是28*28，各层各层之后的数据维度变化就和上边的不一致了，为何要这样编排例子？前后不一致，不便于读者理解和学习
![image](https://user-images.githubusercontent.com/5112397/108600274-3f29df80-73d1-11eb-9516-daa438337072.png)

**Comment by ysh329** [comment]
确实在输入上，文档和实际代码已经图片不一致。我们后续会改进
