### ISSUE TITLE
writer.add_scalar形成的文件的编号是什么意思？

### ISSUE THREAD

**Issue by A-Pai** [PaddlePaddle/Paddle#31106]
writer.add_scalar形成的文件的编号是什么意思？如下，应该有含义

![QQ截图20210222142418](https://user-images.githubusercontent.com/5112397/108670717-52949200-751a-11eb-9990-6aa4e307c19a.png)

**Comment by ShenYuhan** [comment]
您好，组成形式为 vdlrecords.${TIMESTAMP}.log，数字为生成日志时的时间戳。
