### ISSUE TITLE
源码相关问题

### ISSUE THREAD

**Issue by chengruichang** [PaddlePaddle/Paddle#31112]
为使您的问题得到快速解决，在建立Issues前，请您先通过如下方式搜索是否有相似问题:【搜索issue关键字】【使用labels筛选】【官方文档】

如果您没有查询到相似问题，为快速解决您的提问，建立issue时请提供如下细节信息：
- 标题：简洁、精准概括您的问题
- 版本、环境信息：
    1）PaddlePaddle版本：2.0.0rc1
    2）CPU/GPU：GPU
    pass注册的部分paddle/fluid/framework/ir/pass.h，Touch貌似就是一个空函数
![image](https://user-images.githubusercontent.com/52920110/108681686-67792180-752a-11eb-90fd-7a14d7c8eea6.png)
所以图中Touch()部分的调用是什么作用

**Comment by lijianshe02** [comment]
好的，我们这边会有专业的同学进行答复

**Comment by zhhsplendid** [comment]
嗨，@chengruichang ， 不知道你能否搜索到我们Touch的源代码，这里的注释有解释为什么这个函数是空的：

![image](https://user-images.githubusercontent.com/7913861/108937707-b8ebf280-7689-11eb-9ca2-809f180046cc.png)

主要原因是如果部分代码没有被使用，C++的linker会删除生成的二进制文件。这时候如果我们不想要被删除，那么调用一个空函数，C++ linker不会删除。

**Comment by zhhsplendid** [comment]
本issue提问者没有更多追问，我将关闭此issue，如果有更多问题可以再打开和提问
