### ISSUE TITLE
MKLDNN error for continuous image prediction

### ISSUE THREAD

**Issue by juncaipeng** [PaddlePaddle/Paddle#31111]
Info：
* Paddle develop latest commit
* Ubuntu 16.04
* Python 3

Demo（Link:https://dubox.com/s/1lk60OPH4GPj-BrdZ4lSbJA Password:e8ec）：

1. Install Paddle

2. Disable MKLDNN

`python test.py model/__model__ model/__params__ 0`

The results are correct as follows:

```
1 boxes are detected for image 1
1 boxes are detected for image 2
1 boxes are detected for image 3
1 boxes are detected for image 4
1 boxes are detected for image 5
1 boxes are detected for image 6
1 boxes are detected for image 7
1 boxes are detected for image 8
1 boxes are detected for image 9
1 boxes are detected for image 10
```

2. Enable MKLDNN

`python test.py model/__model__ model/__params__ 1`

The results of image 6 and 9 are incorrect as follows:

```
1 boxes are detected for image 1
1 boxes are detected for image 2
1 boxes are detected for image 3
1 boxes are detected for image 4
1 boxes are detected for image 5
9 boxes are detected for image 6
1 boxes are detected for image 7
1 boxes are detected for image 8
5 boxes are detected for image 9
1 boxes are detected for image 10

**Comment by wojtuss** [comment]
@juncaipeng ,
A fix is submitted: https://github.com/PaddlePaddle/Paddle/pull/31820.

**Comment by juncaipeng** [comment]
@wojtuss 
The problem has been fixed. Please cherry-pick #31820 to release 2.0.
