### ISSUE TITLE
“paddle.Model”作何用？

### ISSUE THREAD

**Issue by A-Pai** [PaddlePaddle/Paddle#31118]
“paddle.Model”作何用？文档中怎么查找到更为详细的说明？代码如下：
```
import paddle
import paddle.vision.models as M
model = paddle.Model(M.LeNet())   # 用Model封装模型
```

**Comment by A-Pai** [comment]
找到了：
https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/hapi/model/Model_cn.html#model

![QQ截图20210222194505](https://user-images.githubusercontent.com/5112397/108704242-b46af100-7546-11eb-8212-d982b1c50985.png)

**Comment by lijianshe02** [comment]
好的，谢谢反馈
