### ISSUE TITLE
前后的说法不一致，到底是怎样的？

### ISSUE THREAD

**Issue by A-Pai** [PaddlePaddle/Paddle#31129]
https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/hapi/model/Model_cn.html#model

![QQ截图20210222222635](https://user-images.githubusercontent.com/5112397/108721632-30703380-755d-11eb-9b1f-69901fe1b46c.png)

**Comment by lijianshe02** [comment]
文档错误，谢谢指正
