### ISSUE TITLE
Resize函数中参数size为int，这样处理的目的是？

### ISSUE THREAD

**Issue by A-Pai** [PaddlePaddle/Paddle#31133]
https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/vision/transforms/transforms/Resize_cn.html

“如果size为int，图像的较小边缘将与此数字匹配，即如果 height > width，则图像将重新缩放为(size * height / width, size)。”，这样做的用意何在？

![QQ截图20210223104610](https://user-images.githubusercontent.com/5112397/108796746-6d234580-75c4-11eb-9b3c-f62b587bdeed.png)

**Comment by parap1uie-s** [comment]
很好理解吧，就是你可以给resize()输入一个数字，也可以输入一组数字。

**Comment by A-Pai** [comment]
> 很好理解吧，就是你可以给resize()输入一个数字，也可以输入一组数字。

如果size是一个序列，例如（h，w），输出大小将与此匹配
如果size为int，图像的较小边缘将与此数字匹配，即如果 height > width，则图像将重新缩放为(size * height / width, size)

我说的是“size为int，图像的较小边缘将与此数字匹配，即如果 height > width，则图像将重新缩放为(size * height / width, size)”，这样做的意义是？不理解其实际作用

**Comment by bjjwwang** [comment]
这个我请教下CV的同学。

**Comment by parap1uie-s** [comment]
> > 很好理解吧，就是你可以给resize()输入一个数字，也可以输入一组数字。
> 
> 如果size是一个序列，例如（h，w），输出大小将与此匹配
> 如果size为int，图像的较小边缘将与此数字匹配，即如果 height > width，则图像将重新缩放为(size * height / width, size)
> 
> 我说的是“size为int，图像的较小边缘将与此数字匹配，即如果 height > width，则图像将重新缩放为(size * height / width, size)”，这样做的意义是？不理解其实际作用

维持长宽比

**Comment by A-Pai** [comment]
明白了，谢谢
