### ISSUE TITLE
图像增强(Data augmentation)是扩大了数据量？

### ISSUE THREAD

**Issue by A-Pai** [PaddlePaddle/Paddle#31131]
图像增强(Data augmentation)是扩大了数据量？还是仅仅对原有图像进行更改，数量保持不变？
我的理解是应该扩大了数据量--一张图片从各个角度，改变光线明暗等，模仿在各种条件下看这个物体
是paddle.vision.transforms模块？

**Comment by bjjwwang** [comment]
收到，在请教相关开发者提供解答

**Comment by A-Pai** [comment]
> 收到，在请教相关开发者提供解答

请帮忙解答
