### ISSUE TITLE
adjust_saturation的文档是adjust_hue的

### ISSUE THREAD

**Issue by A-Pai** [PaddlePaddle/Paddle#31145]
https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/vision/transforms/functional/adjust_saturation_cn.html
是adjust_saturation的文档网址，但是打开后是adjust_hue的（先点击adjust_hue，再点击adjust_saturation）。
或者说，先点击别的函数，再点击adjust_saturation，页面不变（网址变成了adjust_saturation的）。

--虽然版本迭代要快，但也要保证基本质量，不然就没意义了。用户不便用，也不敢用。

![QQ截图20210223162235](https://user-images.githubusercontent.com/5112397/108817783-62cc7000-75f3-11eb-8885-35a93985d220.png)

**Comment by bjjwwang** [comment]
好 实在不好意思 感谢指出错误 后续立刻改正
