### ISSUE TITLE
觉得这个导包的写法有些不习惯

### ISSUE THREAD

**Issue by A-Pai** [PaddlePaddle/Paddle#31147]
https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/vision/transforms/functional/adjust_brightness_cn.html

觉得红线部分的写法有些不习惯：
![image](https://user-images.githubusercontent.com/5112397/108820588-5cd88e00-75f7-11eb-9e1a-9d41b359e415.png)

这样写是不是自然些，或者说上边的写法有什么特别的用意？
![image](https://user-images.githubusercontent.com/5112397/108820519-416d8300-75f7-11eb-8767-06422d08bb9a.png)

**Comment by bjjwwang** [comment]
这个我和组员们讨论看看，应该是源于不少先例就这么用下来了。
