### ISSUE TITLE
adjust_brightness和adjust_contrast 返回的都是“裁剪后的图像”

### ISSUE THREAD

**Issue by A-Pai** [PaddlePaddle/Paddle#31153]
https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/vision/transforms/functional/adjust_brightness_cn.html
https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/vision/transforms/functional/adjust_contrast_cn.html

adjust_brightness和adjust_contrast 返回的都是“裁剪后的图像”
本来就不是做裁剪的，怎么返回的是“裁剪后的图像”？

**Comment by bjjwwang** [comment]
好 感谢指教 我反馈下立刻改正
