### ISSUE TITLE
adjust_brightness的文档不能表明其功能

### ISSUE THREAD

**Issue by A-Pai** [PaddlePaddle/Paddle#31152]
https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/vision/transforms/functional/adjust_brightness_cn.html
文档代码如下，该代码输出了转变之后的size，而adjust_brightness的功能是调整亮度，代码不能表明其功能
--理想的代码应该是输出图像，对比转变前后的亮度
![image](https://user-images.githubusercontent.com/5112397/108826018-c1e3b200-75fe-11eb-9ef5-247b95d89884.png)

**Comment by A-Pai** [comment]
https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/vision/transforms/functional/adjust_hue_cn.html
adjust_hue的文档也有类似的问题

**Comment by bjjwwang** [comment]
好 感谢指教

**Comment by A-Pai** [comment]
类似的问题：
![image](https://user-images.githubusercontent.com/5112397/109003425-64289600-76e2-11eb-8830-6fdacaab8f3d.png)
