### ISSUE TITLE
crop的文档有些看不明白

### ISSUE THREAD

**Issue by A-Pai** [PaddlePaddle/Paddle#31168]
https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/vision/transforms/functional/crop_cn.html
文档代码如下：
![image](https://user-images.githubusercontent.com/5112397/108923897-97344080-7674-11eb-87b6-33903a106c3c.png)

**Comment by hong19860320** [comment]
你文档地址贴错了 https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/vision/transforms/functional/center_crop_cn.html#center-crop

centor_crop参数是按照height,width，你最后一句打印的是PIL Image对象cropped_image的尺寸，是按照width,height打印的，你可以尝试打印下fake_image的尺寸，能得到300,256。

**Comment by A-Pai** [comment]
> 你文档地址贴错了 https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/vision/transforms/functional/center_crop_cn.html#center-crop
> 
> centor_crop参数是按照height,width，你最后一句打印的是PIL Image对象cropped_image的尺寸，是按照width,height打印的，你可以尝试打印下fake_image的尺寸，能得到300,256。

地址是搞错了
文档中说返回这个，没说尺寸是按照width,height，有必要说一下
![QQ截图20210224113356](https://user-images.githubusercontent.com/5112397/108943708-55b38d80-7694-11eb-9231-2db8a9c2aaef.png)

**Comment by hong19860320** [comment]
> https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/vision/transforms/functional/center_crop_cn.html#center-crop

好的，我反馈一下

**Comment by hong19860320** [comment]
@TCChenlong 麻烦在示例里面把输出结果打印出来，然后说明下PIL.Image.size打印的顺序是width,height
