### ISSUE TITLE
Pad返回的是填充后的图像？

### ISSUE THREAD

**Issue by A-Pai** [PaddlePaddle/Paddle#31169]
https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/vision/transforms/transforms/Pad_cn.html

![image](https://user-images.githubusercontent.com/5112397/108931752-26e0eb80-7683-11eb-8589-aaa73897b328.png)

**Comment by A-Pai** [comment]
我的理解是“transform ”是继承基类“BaseTransform”得到的一个Pad类
所以说返回的不是直接的“填充后的图像”，而是将其处理成“填充后的图像”的工具

**Comment by hong19860320** [comment]
> 我的理解是“transform ”是继承基类“BaseTransform”得到的一个Pad类
> 所以说返回的不是直接的“填充后的图像”，而是将其处理成“填充后的图像”的工具

是的，你的理解是正确的，但一般不会在返回值说它返回了一个工具类，大部分用户关心的是在使用这个工具类后的结果是什么，所以文档的返回结果一般代表transform()调用后的结果。
