### ISSUE TITLE
pip install paddlepaddle或pip install paddlepaddle-gpu与官网提供的方式有什么不一样？

### ISSUE THREAD

**Issue by A-Pai** [PaddlePaddle/Paddle#31164]
pip install paddlepaddle或pip install paddlepaddle-gpu与https://www.paddlepaddle.org.cn/install/quick?docurl=/documentation/docs/zh/2.0/install/pip/windows-pip.html
上的安装方式，有什么区别吗？

**Comment by bjjwwang** [comment]
没有区别，pypi可能会有网速慢的问题， 以及多平台的问题，因此写的多一点。
