### ISSUE TITLE
adjust_contrast与ContrastTransform的区别是？

### ISSUE THREAD

**Issue by A-Pai** [PaddlePaddle/Paddle#31167]
https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/vision/transforms/functional/adjust_contrast_cn.html
https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/vision/transforms/transforms/ContrastTransform_cn.html
adjust_contrast与ContrastTransform的区别是？

类似的问题还有：
adjust_hue与HueTransform
Normalize与normalize

**Comment by hong19860320** [comment]
都是功能函数和类的关系，ContrastTransform  内部调用的是adjust_hue 
https://github.com/PaddlePaddle/Paddle/blob/ec2fad4d5157ca0c5687a2dfd7c7ebec274e4df1/python/paddle/vision/transforms/transforms.py#L771

**Comment by A-Pai** [comment]
> 都是功能函数和类的关系，ContrastTransform 内部调用的是adjust_hue
> https://github.com/PaddlePaddle/Paddle/blob/ec2fad4d5157ca0c5687a2dfd7c7ebec274e4df1/python/paddle/vision/transforms/transforms.py#L771

提供“类”，有何作用？

**Comment by hong19860320** [comment]
> > 都是功能函数和类的关系，ContrastTransform 内部调用的是adjust_hue
> > https://github.com/PaddlePaddle/Paddle/blob/ec2fad4d5157ca0c5687a2dfd7c7ebec274e4df1/python/paddle/vision/transforms/transforms.py#L771
> 
> 提供“类”，有何作用？

这篇文章可以帮助你理解下两者的区别 https://www.zhihu.com/question/66782101
