### ISSUE TITLE
CenterCrop与center_crop的区别是？

### ISSUE THREAD

**Issue by A-Pai** [PaddlePaddle/Paddle#31166]
https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/vision/transforms/functional/center_crop_cn.html
https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/vision/transforms/transforms/CenterCrop_cn.html
CenterCrop与center_crop的区别是？
二者文档的代码都不能充分表明其功能--返回的都是“fake_img.size”，应该展示实际效果图片

**Comment by hong19860320** [comment]
功能一致，CenterCrop是类，可以继承修改，center_crop是功能函数

**Comment by A-Pai** [comment]
> 功能一致，CenterCrop是类，可以继承修改，center_crop是功能函数

为何仅仅是少数的api，有这二个版本的，其他的，例如RandomCrop，只有一种

**Comment by hong19860320** [comment]
小写的api都是比较lowlevel的功能函数，不一定每个类都有对应的功能函数，你可以看下RandomCrop其实使用pad的功能函数组的。https://github.com/PaddlePaddle/Paddle/blob/ec2fad4d5157ca0c5687a2dfd7c7ebec274e4df1/python/paddle/vision/transforms/transforms.py#L1011
