### ISSUE TITLE
按照官网推荐的按照方式安装，不成功

### ISSUE THREAD

**Issue by A-Pai** [PaddlePaddle/Paddle#31165]
按照官网推荐的按照方式：python -m pip install paddlepaddle==2.0.0 -i https://mirror.baidu.com/pypi/simple
安装：Successfully installed paddlepaddle-2.0.0
import paddle 竟然提示：
ModuleNotFoundError: No module named 'paddle.fluid.core_noavx'

**Comment by bjjwwang** [comment]
比较奇怪，我猜测会不会多个python版本之间串了。

**Comment by A-Pai** [comment]
> 比较奇怪，我猜测会不会多个python版本之间串了。

我的python只有一个版本

**Comment by pangyoki** [comment]
请问能给出完整的报错信息吗？麻烦也提供下系统、python版本等信息

**Comment by A-Pai** [comment]
> 请问能给出完整的报错信息吗？麻烦也提供下系统、python版本等信息

![image](https://user-images.githubusercontent.com/5112397/108996960-06904b80-76da-11eb-8ea7-9d683ea81249.png)

![image](https://user-images.githubusercontent.com/5112397/108996521-72be7f80-76d9-11eb-9414-3b8e166674fa.png)
![image](https://user-images.githubusercontent.com/5112397/108996800-d21c8f80-76d9-11eb-808d-99853273f2b6.png)

**Comment by A-Pai** [comment]
觉得pytorch安装最顺利：
![image](https://user-images.githubusercontent.com/5112397/108997693-df864980-76da-11eb-92cb-3d13c7998aa6.png)

**Comment by pangyoki** [comment]
报错里提示了，你的机器不支持avx，你现在下的是avx版本的包，可以用`python -m pip install -U paddlepaddle-gpu[==version] -f https://paddlepaddle.org.cn/whl/stable_noavx.html`这个指令来下noavx的paddle

**Comment by A-Pai** [comment]
> 报错里提示了，你的机器不支持avx，你现在下的是avx版本的包，可以用`python -m pip install -U paddlepaddle-gpu[==version] -f https://paddlepaddle.org.cn/whl/stable_noavx.html`这个指令来下noavx的paddle

一般看得是这个，这个地方应该说到avx的问题：
![image](https://user-images.githubusercontent.com/5112397/109012079-8de6ba80-76ec-11eb-8ff0-1a53ec9234dd.png)

**Comment by A-Pai** [comment]
按照上边给的方式，安装：
![image](https://user-images.githubusercontent.com/5112397/109013552-46612e00-76ee-11eb-834b-047282c720c9.png)
还是不成功：
![image](https://user-images.githubusercontent.com/5112397/109013678-65f85680-76ee-11eb-89da-3923fc5475ab.png)

**Comment by A-Pai** [comment]
上边的这次安装，提前卸载了之前安装的版本，这是安装之后的pip list：
![image](https://user-images.githubusercontent.com/5112397/109015256-e7041d80-76ef-11eb-8736-27317ee6bbe9.png)

**Comment by pangyoki** [comment]
noavx包只有python2.7支持，可以尝试这个安装指令：`python2.7 -m pip install paddlepaddle-gpu==2.0.0 -f https://paddlepaddle.org.cn/whl/stable/noavx.html`

**Comment by A-Pai** [comment]
看样子，安装飞桨真的不容易
---形成了一道障碍

**Comment by A-Pai** [comment]
> noavx包只有python2.7支持，可以尝试这个安装指令：`python2.7 -m pip install paddlepaddle-gpu==2.0.0 -f https://paddlepaddle.org.cn/whl/stable/noavx.html`

![image](https://user-images.githubusercontent.com/5112397/109139470-85e35500-7796-11eb-8a4a-86e1064f0e2e.png)

**Comment by zhwesky2010** [comment]
@A-Pai  您好，这个问题主要由于机器不支持avx，该类型只发布了python2.7版本。而avx类型，则发布了2.7~3.8 五个版本，后续我们会增加no_avx机器的python版本个数，感谢反馈

**Comment by swtkiwi** [comment]
您好，最后您的这个问题是因为您没有安装python27导致的哦～请您先安装python，再安装paddle包哈～

**Comment by A-Pai** [comment]
> 您好，最后您的这个问题是因为您没有安装导致的哦～请您先安装python，再安装paddle包哈～

是没装python还是没装python27，python27是？
上边反馈过，我的是：
![108996521-72be7f80-76d9-11eb-9414-3b8e166674fa](https://user-images.githubusercontent.com/5112397/109268525-2ba1cd00-7846-11eb-9b85-8626bd67b46e.png)

**Comment by ZGSLZL** [comment]
遇到同样的问题Window, 先安装了cpu版本，报如下错误，提升安装gpu版本：
WARNING: AVX is not support on your machine. Hence, no_avx core will be imported, It has much worse preformance than avx core.
Error: AVX is not support on your machine, but you have installed paddlepaddle with avx core, you should reinstall paddlepaddle by 'python -m pip install -U paddlepaddle-gpu[==version] -f https://paddlepaddle.
org.cn/whl/stable_noavx.html'
Traceback (most recent call last):
  File "demo.py", line 2, in <module>
    import paddle
  File "D:\Program Files\Anaconda3\envs\paddle\lib\site-packages\paddle\__init__.py", line 29, in <module>
    from .fluid import monkey_patch_variable
  File "D:\Program Files\Anaconda3\envs\paddle\lib\site-packages\paddle\fluid\__init__.py", line 35, in <module>
    from . import framework
  File "D:\Program Files\Anaconda3\envs\paddle\lib\site-packages\paddle\fluid\framework.py", line 36, in <module>
    from . import core
  File "D:\Program Files\Anaconda3\envs\paddle\lib\site-packages\paddle\fluid\core.py", line 349, in <module>
    raise e
  File "D:\Program Files\Anaconda3\envs\paddle\lib\site-packages\paddle\fluid\core.py", line 308, in <module>
    from .core_noavx import *
ModuleNotFoundError: No module named 'paddle.fluid.core_noavx'
按照提示按照gpu版本，依然报同样错误，希望能得到解决

**Comment by swtkiwi** [comment]
> > 您好，最后您的这个问题是因为您没有安装导致的哦～请您先安装python，再安装paddle包哈～
> 
> 是没装python还是没装python27，python27是？
> 上边反馈过，我的是：
> ![108996521-72be7f80-76d9-11eb-9414-3b8e166674fa](https://user-images.githubusercontent.com/5112397/109268525-2ba1cd00-7846-11eb-9b85-8626bd67b46e.png)

是的，上面有说过，因为noavx的机器很少了，所以对noavx支持的python版本也很少，只有python2.7支持，可以尝试这个安装指令：python2.7 -m pip install paddlepaddle-gpu==2.0.0 -f https://paddlepaddle.org.cn/whl/stable/noavx.html 。所以您的python38装不上哈。所以您用这个python27的命令就会报错，python版本都没对上哈。

**Comment by A-Pai** [comment]
> > > 您好，最后您的这个问题是因为您没有安装导致的哦～请您先安装python，再安装paddle包哈～
> > 
> > 
> > 是没装python还是没装python27，python27是？
> > 上边反馈过，我的是：
> > ![108996521-72be7f80-76d9-11eb-9414-3b8e166674fa](https://user-images.githubusercontent.com/5112397/109268525-2ba1cd00-7846-11eb-9b85-8626bd67b46e.png)
> 
> 是的，上面有说过，因为noavx的机器很少了，所以对noavx支持的python版本也很少，只有python2.7支持，可以尝试这个安装指令：python2.7 -m pip install paddlepaddle-gpu==2.0.0 -f https://paddlepaddle.org.cn/whl/stable/noavx.html 。所以您的python38装不上哈。所以您用这个python27的命令就会报错，python版本都没对上哈。

难道要我退回去用python2.7？
paddle的发展应该适应python的发展，还是python的发展应该适应paddle的发展？

**Comment by zhwesky2010** [comment]
> > > 您好，最后您的这个问题是因为您没有安装导致的哦～请您先安装python，再安装paddle包哈～
> > 
> > 
> > 是没装python还是没装python27，python27是？
> > 上边反馈过，我的是：
> > ![108996521-72be7f80-76d9-11eb-9414-3b8e166674fa](https://user-images.githubusercontent.com/5112397/109268525-2ba1cd00-7846-11eb-9b85-8626bd67b46e.png)
> 
> 是的，上面有说过，因为noavx的机器很少了，所以对noavx支持的python版本也很少，只有python2.7支持，可以尝试这个安装指令：python2.7 -m pip install paddlepaddle-gpu==2.0.0 -f https://paddlepaddle.org.cn/whl/stable/noavx.html 。所以您的python38装不上哈。所以您用这个python27的命令就会报错，python版本都没对上哈。

要不还是no_avx发一个或几个 用户量最高的python版本，比如3.7、3.8，发python2.7看起来没什么意义，目前no_avx的厂外机器看来还是有的

**Comment by A-Pai** [comment]
> > > > 您好，最后您的这个问题是因为您没有安装导致的哦～请您先安装python，再安装paddle包哈～
> > > 
> > > 
> > > 是没装python还是没装python27，python27是？
> > > 上边反馈过，我的是：
> > > ![108996521-72be7f80-76d9-11eb-9414-3b8e166674fa](https://user-images.githubusercontent.com/5112397/109268525-2ba1cd00-7846-11eb-9b85-8626bd67b46e.png)
> > 
> > 
> > 是的，上面有说过，因为noavx的机器很少了，所以对noavx支持的python版本也很少，只有python2.7支持，可以尝试这个安装指令：python2.7 -m pip install paddlepaddle-gpu==2.0.0 -f https://paddlepaddle.org.cn/whl/stable/noavx.html 。所以您的python38装不上哈。所以您用这个python27的命令就会报错，python版本都没对上哈。
> 
> 要不还是no_avx发一个或几个 用户量最高的python版本，比如3.7、3.8，发python2.7看起来没什么意义，目前no_avx的厂外机器看来还是有的

越搞越复杂了，我就是python3.8.5，要装飞桨2.0的gpu版，要让用户容易装
pytorch的安装就没有这么多的麻烦

**Comment by zhwesky2010** [comment]
@A-Pai 嗯我是在对PM说应该要增加下 你对应机器配置的包

**Comment by swtkiwi** [comment]
> > > > 您好，最后您的这个问题是因为您没有安装导致的哦～请您先安装python，再安装paddle包哈～
> > > 
> > > 
> > > 是没装python还是没装python27，python27是？
> > > 上边反馈过，我的是：
> > > ![108996521-72be7f80-76d9-11eb-9414-3b8e166674fa](https://user-images.githubusercontent.com/5112397/109268525-2ba1cd00-7846-11eb-9b85-8626bd67b46e.png)
> > 
> > 
> > 是的，上面有说过，因为noavx的机器很少了，所以对noavx支持的python版本也很少，只有python2.7支持，可以尝试这个安装指令：python2.7 -m pip install paddlepaddle-gpu==2.0.0 -f https://paddlepaddle.org.cn/whl/stable/noavx.html 。所以您的python38装不上哈。所以您用这个python27的命令就会报错，python版本都没对上哈。
> 
> 难道要我退回去用python2.7？
> paddle的发展应该适应python的发展，还是python的发展应该适应paddle的发展？

是的，我是在解决您目前的问题，目前的解决方案就是这两种。源码编译和py27。
我们是在不断跟进python进行升级的，下个版本也会适配python39。但主要针对的也是avx机器，没有avx的机器很少有用户用高版本python，我们无法满足所有用户需求，只能满足大多数用户需求。我们也已经在尽量满足更多用户的需求，所以看到您的这种情况，我们已经在分析考虑以后是否发布高版本python的noavx的wheel包了。但也是在未来版本。您如果着急使用的话，目前解决方案就是源码编译，或使用下py27。

**Comment by wadefelix** [comment]
看来奔腾赛扬处理器用户还是不少的，特别是学生和初学者。

**Comment by swtkiwi** [comment]
目前2.0.1也支持py38的noavx了，可以使用python3 -m pip install paddlepaddle-gpu==2.0.1 -f https://paddlepaddle.org.cn/whl/stable/noavx.html 安装

**Comment by A-Pai** [comment]
> 目前2.0.1也支持py38的noavx了，可以使用python3 -m pip install paddlepaddle-gpu==2.0.1 -f https://paddlepaddle.org.cn/whl/stable/noavx.html 安装

按照上边的安装了，还是报错：
![image](https://user-images.githubusercontent.com/5112397/110442816-30903780-80f6-11eb-8ea8-07eb0afde83e.png)

**Comment by zhwesky2010** [comment]
@A-Pai 您好，麻烦看下下面的完整报错截图，这个可能是CUDA设备的问题

**Comment by A-Pai** [comment]
我使用pytorch的gpu版正常
![image](https://user-images.githubusercontent.com/5112397/110444791-620a0280-80f8-11eb-9188-478f80984b87.png)

**Comment by jtyoui** [comment]
我也遇到这个问题，我的电脑只有CPU。安装的是CPU版本 
`python -m pip install paddlepaddle -i https://mirror.baidu.com/pypi/simple`
报错情况：
```
ModuleNotFoundError: No module named 'paddle.fluid.core_noavx'
```

**Comment by fanfq** [comment]
> 目前2.0.1也支持py38的noavx了，可以使用python3 -m pip install paddlepaddle-gpu==2.0.1 -f https://paddlepaddle.org.cn/whl/stable/noavx.html 安装

插眼，可用！！！

**Comment by 1765251858** [comment]
太感谢了

> 目前2.0.1也支持py38的noavx了，可以使用python3 -m pip install paddlepaddle-gpu==2.0.1 -f https://paddlepaddle.org.cn/whl/stable/noavx.html 安装

太感谢了，问题已解决

**Comment by applepieiris** [comment]
> 目前2.0.1也支持py38的noavx了，可以使用python3 -m pip install paddlepaddle-gpu==2.0.1 -f https://paddlepaddle.org.cn/whl/stable/noavx.html 安装

对于cpu版本的去掉-gpu，之后就可以安装了
python3 -m pip install paddlepaddle==2.0.1 -f https://paddlepaddle.org.cn/whl/stable/noavx.html
