### ISSUE TITLE
请给一个装有paddle的docker镜像地址

### ISSUE THREAD

**Issue by guojiahuiEmily** [PaddlePaddle/Paddle#31160]
我自己做的镜像都在2G。
能否给一个1G内的paddle的docker镜像，这样才能在阿里云上用。

为使您的问题得到快速解决，在建立Issue前，请您先通过如下方式搜索是否有相似问题:【搜索issue关键字】【使用labels筛选】【官方文档】

建立issue时，为快速解决问题，请您根据使用情况给出如下信息：
- 标题：请包含关键词“安装错误”/“编译错误”，例如“Mac编译错误”
- 版本、环境信息：
    1）PaddlePaddle版本：请提供您的PaddlePaddle版本号（如1.1）或CommitID
    2）CPU：请提供CPU型号，MKL/OpenBlas/MKLDNN/等数学库的使用情况
    3）GPU：请提供GPU型号，CUDA和CUDNN版本号
    4）系统环境：请说明系统类型、版本（如Mac OS 10.14）、Python版本
注：您可以通过执行[summary_env.py](https://github.com/PaddlePaddle/Paddle/blob/develop/tools/summary_env.py)获取以上信息。
- 安装方式信息：
1）pip安装/docker安装
2）本地编译：请提供cmake命令，编译命令
3）docker编译：请提供docker镜像，编译命令            
  特殊环境请注明：如离线安装等
- 复现信息：如为报错，请给出复现环境、复现步骤
- 问题描述：请详细描述您的问题，同步贴出报错信息、日志/代码关键片段

Thank you for contributing to PaddlePaddle.
Before submitting the issue, you could search issue in Github in case that there was a similar issue submitted or resolved before.
If there is no solution,please make sure that this is an installation issue including the following details:
**System information**
-PaddlePaddle version （eg.1.1）or CommitID
-CPU: including CPUMKL/OpenBlas/MKLDNN version
-GPU: including CUDA/CUDNN version
-OS Platform (eg. Mac OS 10.14)
-Python version
- Install method: pip install/install with docker/build from source(without docker)/build within docker
- Other special cases that you think may be related to this problem, eg. offline install, special internet condition 
Note: You can get most of the information by running [summary_env.py](https://github.com/PaddlePaddle/Paddle/blob/develop/tools/summary_env.py).   

**To Reproduce**
Steps to reproduce the behavior
**Describe your current behavior**
**Code to reproduce the issue**
**Other info / logs**

**Comment by bjjwwang** [comment]
我觉得镜像应该不会很难，难的是用到的不只有Paddle，我们发布镜像主要是会考量易用性和可扩展性，所以打入了很多Python版本以及其他依赖只为了用户便于开发。
您可以参考下 tools/dockerfile里面的写法，删除掉大多数细节。
我也会和组员讨论下应该如何给出精简镜像。

**Comment by guojiahuiEmily** [comment]
还是比较难的。对于大多数人来说。
docker build时老报一些错误
E: Unable to locate package python-qt4
E: Package 'module-init-tools' has no installation candidate
T

**Comment by wadefelix** [comment]
mark

**Comment by wadefelix** [comment]
您可以使用这个Dockerfile来做paddle基础镜像, 做完的镜像大小约为1.06G左右，镜像仓库中压缩存放大小为260M左右。
```Dockerfile
ARG BASEIMAGE=ubuntu:20.04
FROM ${BASEIMAGE}

RUN sed -i "s#archive.ubuntu.com#mirrors.tuna.tsinghua.edu.cn#g" /etc/apt/sources.list && \
    sed -i "s#security.ubuntu.com#mirrors.tuna.tsinghua.edu.cn#g" /etc/apt/sources.list

ENV DEBIAN_FRONTEND noninteractive
RUN apt-get update \
 && apt-get install -yq --no-install-recommends \
    python3 \
    python3-pip \
    libgomp1 \
 && apt-get clean \
 && rm -rf /var/lib/apt/lists/*

RUN echo 'Pillow\n\
numpy\n\
gast==0.3.3\n\
six\n\
protobuf\n\
urllib3\n\
certifi\n\
chardet\n\
requests\n\
decorator\n\
astor' >paddle.requirements && \
    pip3 install --no-cache-dir -i https://mirror.baidu.com/pypi/simple -r paddle.requirements && \
    rm paddle.requirements

ARG PADDLE_WHL=https://paddle-wheel.bj.bcebos.com/2.0.0-cpu-mkl/paddlepaddle-2.0.0-cp38-cp38-linux_x86_64.whl
RUN pip3 install --no-cache-dir -i https://mirror.baidu.com/pypi/simple ${PADDLE_WHL}
```

**Comment by guojiahuiEmily** [comment]
谢谢。 我做了一个镜像：
registry.cn-hangzhou.aliyuncs.com/myie9/paddle: latest
