### ISSUE TITLE
利用jetson nano编译安装paddle后，推理出错

### ISSUE THREAD

**Issue by Huihuihh** [PaddlePaddle/Paddle#31172]
在jetson nano上面编译安装paddle，编译指令
```
cmake .. \
  -DWITH_CONTRIB=OFF \
  -DWITH_MKL=OFF  \
  -DWITH_MKLDNN=OFF \
  -DWITH_TESTING=OFF \
  -DCMAKE_BUILD_TYPE=Release \
  -DON_INFER=ON \
  -DWITH_PYTHON=ON \
  -DWITH_XBYAK=OFF  \
  -DWITH_AVX=OFF \
  -DWITH_NV_JETSON=ON \
  -DPY_VERSION=3.6 \
  -DTENSORRT_ROOT=/usr/lib/aarch64-linux-gnu/ \
  -DWITH_TENSORRT=ON \
  -DCUDA_ARCH_NAME=Auto
```
安装paddle后利用Paddle-Inference-Demo里面的yolov3进行推理，发现使用gpu推理会出错，不使用gpu能够正常推理
```
Traceback (most recent call last):
  File "infer_yolov3.py", line 104, in <module>
    draw_bbox(img, result[0], save_name=save_img_name)
  File "/home/jetson-nano/Desktop/demo/Paddle-Inference-Demo/python/yolov3/utils.py", line 42, in draw_bbox
    cat_id, score, bbox = res[0], res[1], res[2:]
IndexError: index 1 is out of bounds for axis 0 with size 1
```

**Comment by hong19860320** [comment]
看起来没有输出结果，建议按照官网的编译方法https://www.paddlepaddle.org.cn/documentation/docs/zh/guides/05_inference_deployment/inference/build_and_install_lib_cn.html重新编译试试
![image](https://user-images.githubusercontent.com/9973393/109016662-56c6d800-76f1-11eb-813b-d719d0039f6d.png)

或者直接用编译好的库进行测试
![image](https://user-images.githubusercontent.com/9973393/109016739-6cd49880-76f1-11eb-8c34-203f6c50b137.png)
