### ISSUE TITLE
Specialize PADDLE_ENFORCE and throw_on_error for pointer types

### ISSUE THREAD

**Issue by wangkuiyi** [PaddlePaddle/Paddle#3117]
By adding the specialization of `throw_on_error` for pointer types, we can write

```cpp
PADDLE_ENFORCE(GlobalScope()->FindVar("variable_name"), 
    "variable_name not defined.");
```

without wrting the checking of nullptr

```cpp
PADDLE_ENFORCE(GlobalScope()->FindVar("variable_name") != nullptr, 
    "variable_name not defined.");
```

**Comment by gangliao** [comment]
Add this template specialization, developers might misuse `PADDLE_ENFORCE`. For instance, if there is a function `test` and its return type is not `void*`, then `PADDLE_ENFORCE(test(a, b))` might cause non-deterministic problem. @wangkuiyi

**Comment by wangkuiyi** [comment]
Sorry but why is this case non-deterministic? Which throw_on_error specialization would this case match?

**Comment by gangliao** [comment]
@wangkuiyi 

For this case, it's definitely ok. We can support this. 

```c++
PADDLE_ENFORCE(GlobalScope()->FindVar("variable_name"), 
    "variable_name not defined.");
```

 I mean it might give people some kind of feeling that every function in Paddle could use `PADDLE_ENFORCE ` directly. 

```c++
int test(int a, int b) {...};
PADDLE_ENFORCE(test(1,  2)); // return value > 0, success or fail ?
PADDLE_ENFORCE(test(2,  1)); // return value < 0, success or fail ?
PADDLE_ENFORCE(test(2,  2)); // return value == 0, success or fail ?
```

But it's  seldom happen, we can ignore this.

**Comment by gangliao** [comment]
Also, I want to make it clear that when we need to use `PADDLE_ENFORCE` or `PADDLE_ASSERT`.

check the legality of input and output: `PADDLE_ASSERT`
check the correctness of function execution:  `PADDLE_ENFORCE`

or only use `PADDLE_ENFORCE`.

**Comment by wangkuiyi** [comment]
Got it. Yes, let's remove the added specialization in PR #3116.
