### ISSUE TITLE
同时提供“Resize”和“resize”的目的是？

### ISSUE THREAD

**Issue by A-Pai** [PaddlePaddle/Paddle#31176]
https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/vision/transforms/transforms/Resize_cn.html
https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/vision/transforms/functional/resize_cn.html

文档中说二者的功能都是“将输入数据调整为指定大小”

但用法不同，Resize要先转化一下，是曲线救国，resize是直接用，同时提供“Resize”和“resize”的目的是？

![QQ截图20210224103046](https://user-images.githubusercontent.com/5112397/108938922-dcb03800-768b-11eb-8f4a-49facd17c4fb.png)

**Comment by hong19860320** [comment]
和之前你提的issue问题类似，可以看下这篇文章https://www.zhihu.com/question/66782101

**Comment by A-Pai** [comment]
好的，谢谢，这个解释得可能透彻
