### ISSUE TITLE
RandomRotate没有“随机”参数？

### ISSUE THREAD

**Issue by A-Pai** [PaddlePaddle/Paddle#31173]
https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/vision/transforms/transforms/RandomRotation_cn.html

![QQ截图20210224101242](https://user-images.githubusercontent.com/5112397/108935558-e1272180-7688-11eb-9ff0-30f89653c6dd.png)

**Comment by hong19860320** [comment]
可以参照这个代码理解下
https://github.com/PaddlePaddle/Paddle/blob/0f1fde51021e1c9deae099ee0c875c53128687b4/python/paddle/vision/transforms/transforms.py#L1156

是基于输入degrees参数为(min_degree, max_degree)，按照均匀分布随机产生一个角度

**Comment by A-Pai** [comment]
我仅仅说的是文档可能有问题，不是指的实际功能
![image](https://user-images.githubusercontent.com/5112397/109019469-fe450a00-76f3-11eb-906d-bab8ba90e25c.png)

**Comment by hong19860320** [comment]
degrees是一个范围，然后按照均匀分布随机产生一个degree

**Comment by A-Pai** [comment]
> degrees是一个范围，然后按照均匀分布随机产生一个degree

我似乎明白了：
degree需要指定
随机是均匀分布，不需要指定--均匀分布随机最好在文档中说一下

**Comment by hong19860320** [comment]
> > degrees是一个范围，然后按照均匀分布随机产生一个degree
> 
> 我似乎明白了：
> degree需要指定
> 随机是均匀分布，不需要指定--均匀分布随机最好在文档中说一下

是degrees，就是最小，最大的角度，然后框架会在它们间随机产生一个角度进行旋转

**Comment by hong19860320** [comment]
@TCChenlong 建议文档API的说明详细点，例如改成『依据'degrees'指定的角度范围和按照均匀分布随机产生一个角度对图像进行旋转』

**Comment by TCChenlong** [comment]
已修复，PR见：[#3308](https://github.com/PaddlePaddle/FluidDoc/pull/3308)，感谢反馈
