### ISSUE TITLE
PaddleRec/models/recall/gnn/  教程执行过程中报错

### ISSUE THREAD

**Issue by lucifer726** [PaddlePaddle/Paddle#31171]
****************************************
Paddle version: 2.0.0
Paddle With CUDA: False
OS: Windows 10
Python version: 3.7.0
CUDA version: None
cuDNN version: None
Nvidia driver version: None
****************************************
- 训练信息
    1）单机cpu
    2）显存信息
    3）Operator信息
- 复现信息：如为报错，请给出复现环境、复现步骤

按照gnn教程，执行到python -m paddlerec.run -m models/recall/gnn/config.yaml时报错

- 问题描述：请详细描述您的问题，同步贴出报错信息、日志、可复现的代码片段
之前的数据处理做完了，然后进行快速开始的时候，运行教程中的代码报错
config.yaml中的信息没有改动

(paddlepaddle) D:\python项目\PaddleRec-release-1.8.5>python -m paddlerec.run -m models/recall/gnn/config.yaml

====================================================================================================
                Runtime Envs                      Value
----------------------------------------------------------------------------------------------------
====================================================================================================

============================================================================================================
                paddlerec Global Envs                     Value
------------------------------------------------------------------------------------------------------------
workspace                                                 models\recall\gnn
dataset.dataset_train.name                                dataset_train
dataset.dataset_train.batch_size                          10
dataset.dataset_train.type                                DataLoader
dataset.dataset_train.data_path                           models\recall\gnn\data\train
dataset.dataset_train.data_converter                      models\recall\gnn\reader.py
dataset.dataset_infer.name                                dataset_infer
dataset.dataset_infer.batch_size                          50
dataset.dataset_infer.type                                DataLoader
dataset.dataset_infer.data_path                           models\recall\gnn\data\test
dataset.dataset_infer.data_converter                      models\recall\gnn\evaluate_reader.py
hyper_parameters.optimizer.class                          Adam
hyper_parameters.optimizer.learning_rate                  0.001
hyper_parameters.optimizer.decay_steps                    3
hyper_parameters.optimizer.decay_rate                     0.1
hyper_parameters.optimizer.l2                             1e-05
hyper_parameters.sparse_feature_number                    43098
hyper_parameters.sparse_feature_dim                       100
hyper_parameters.corpus_size                              719470
hyper_parameters.gnn_propogation_steps                    1
mode                                                      ['single_cpu_train', 'single_cpu_infer']
runner.single_cpu_train.name                              single_cpu_train
runner.single_cpu_train.class                             train
runner.single_cpu_train.epochs                            5
runner.single_cpu_train.device                            cpu
runner.single_cpu_train.save_checkpoint_interval          1
runner.single_cpu_train.save_inference_interval           1
runner.single_cpu_train.save_checkpoint_path              increment_gnn
runner.single_cpu_train.save_inference_path               inference_gnn
runner.single_cpu_train.save_inference_feed_varnames      []
runner.single_cpu_train.save_inference_fetch_varnames     []
runner.single_cpu_train.init_model_path
runner.single_cpu_train.print_interval                    1
runner.single_cpu_train.phases                            ['phase1']
runner.single_cpu_infer.name                              single_cpu_infer
runner.single_cpu_infer.class                             infer
runner.single_cpu_infer.device                            cpu
runner.single_cpu_infer.print_interval                    1
runner.single_cpu_infer.init_model_path                   increment_gnn
runner.single_cpu_infer.phases                            ['phase2']
phase.phase1.name                                         phase1
phase.phase1.model                                        models\recall\gnn\model.py
phase.phase1.dataset_name                                 dataset_train
phase.phase1.thread_num                                   1
phase.phase2.name                                         phase2
phase.phase2.model                                        models\recall\gnn\model.py
phase.phase2.dataset_name                                 dataset_infer
phase.phase2.thread_num                                   1
============================================================================================================

PaddleRec: Runner single_cpu_train Begin
Executor Mode: train
processor_register begin
Running SingleInstance.
Running SingleNetwork.
Warning:please make sure there are no hidden files in the dataset folder and check these hidden files:[]
need_split_files: False
Running SingleStartup.
C:\Users\lucifer\paddlepaddle\lib\site-packages\paddle\fluid\executor.py:1150: UserWarning: There are no operators in the program to be executed. If you pass Program manually, please
 use fluid.program_guard to ensure the current Program is being used.
  warnings.warn(error_info)
Running SingleRunner.
!!! The CPU_NUM is not specified, you should set CPU_NUM in the environment variable list.
CPU_NUM indicates that how many CPUPlace are used in the current task.
And if this parameter are set as N (equal to the number of physical CPU core) the program may be faster.

export CPU_NUM=8 # for example, set CPU_NUM as number of physical CPU core which is 8.

!!! The default number of CPU_NUM=1.
W0224 09:46:15.386087  6492 build_strategy.cc:171] fusion_group is not enabled for Windows/MacOS now, and only effective when running with CUDA GPU.
W0224 09:46:15.387085  6492 build_strategy.cc:430] fuse_bn_add_act_pass is only supported on GPU, skipped.
Traceback (most recent call last):
  File "C:\Users\lucifer\paddlepaddle\lib\site-packages\paddle_rec-1.8.5-py3.7.egg\paddlerec\core\trainer.py", line 255, in run
    self.context_process(self._context)
  File "C:\Users\lucifer\paddlepaddle\lib\site-packages\paddle_rec-1.8.5-py3.7.egg\paddlerec\core\trainer.py", line 216, in context_process
    self._status_processor[context['status']](context)
  File "C:\Users\lucifer\paddlepaddle\lib\site-packages\paddle_rec-1.8.5-py3.7.egg\paddlerec\core\trainers\general_trainer.py", line 137, in runner
    runner_class.run(context)
  File "C:\Users\lucifer\paddlepaddle\lib\site-packages\paddle_rec-1.8.5-py3.7.egg\paddlerec\core\trainers\framework\runner.py", line 481, in run
    result = self._run(context, model_dict)
  File "C:\Users\lucifer\paddlepaddle\lib\site-packages\paddle_rec-1.8.5-py3.7.egg\paddlerec\core\trainers\framework\runner.py", line 89, in _run
    return self._executor_dataloader_train(model_dict, context)
  File "C:\Users\lucifer\paddlepaddle\lib\site-packages\paddle_rec-1.8.5-py3.7.egg\paddlerec\core\trainers\framework\runner.py", line 187, in _executor_dataloader_train
    return_numpy=False)
  File "C:\Users\lucifer\paddlepaddle\lib\site-packages\paddle\fluid\executor.py", line 1110, in run
    six.reraise(*sys.exc_info())
  File "C:\Users\lucifer\paddlepaddle\lib\site-packages\six.py", line 703, in reraise
    raise value
  File "C:\Users\lucifer\paddlepaddle\lib\site-packages\paddle\fluid\executor.py", line 1108, in run
    return_merged=return_merged)
  File "C:\Users\lucifer\paddlepaddle\lib\site-packages\paddle\fluid\executor.py", line 1240, in _run_impl
    program._compile(scope, self.place)
  File "C:\Users\lucifer\paddlepaddle\lib\site-packages\paddle\fluid\compiler.py", line 471, in _compile
    use_device=use_device, scope=self._scope, places=self._places)
  File "C:\Users\lucifer\paddlepaddle\lib\site-packages\paddle\fluid\compiler.py", line 421, in _compile_data_parallel
    self._exec_strategy, self._build_strategy, self._graph)
RuntimeError: (PreconditionNotMet) The graph doesn't have operators.
  [Hint: Expected op_deps_.size() > 0, but received op_deps_.size():0 <= 0:0.] (at D:\v2.0.0\paddle\paddle\fluid\framework\details\fast_threaded_ssa_graph_executor.cc:55)

Catch Exception:(PreconditionNotMet) The graph doesn't have operators.

                                              Exit PaddleRec. catch exception in precoss status: [train_pass], except: (PreconditionNotMet) The graph doesn't have operators.
  [Hint: Expected op_deps_.size() > 0, but received op_deps_.size():0 <= 0:0.] (at D:\v2.0.0\paddle\paddle\fluid\framework\details\fast_threaded_ssa_graph_executor.cc:55)

RuntimeError

**Comment by frankwhzhang** [comment]
gnn需要使用1.8.5的版本
