### ISSUE TITLE
RandomHorizontalFlip的文档有些看不明白

### ISSUE THREAD

**Issue by A-Pai** [PaddlePaddle/Paddle#31170]
https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/vision/transforms/transforms/RandomHorizontalFlip_cn.html

![image](https://user-images.githubusercontent.com/5112397/108932414-49bfcf80-7684-11eb-83b1-9494729744d9.png)

**Comment by hong19860320** [comment]
可以结合这个代码看 https://github.com/PaddlePaddle/Paddle/blob/ec2fad4d5157ca0c5687a2dfd7c7ebec274e4df1/python/paddle/vision/transforms/transforms.py#L564
224就是一个阈值，随机数小于这个阈值就做flip，由于随机数都是小于1.0的，所以如果设置为224，就代表一直进行flip，所以说，这个示例代码中的224取得不具代表意义、

**Comment by A-Pai** [comment]
> 可以结合这个代码看
> 
> https://github.com/PaddlePaddle/Paddle/blob/ec2fad4d5157ca0c5687a2dfd7c7ebec274e4df1/python/paddle/vision/transforms/transforms.py#L564
> 
> 
> 224就是一个阈值，随机数小于这个阈值就做flip，由于随机数都是小于1.0的，所以如果设置为224，就代表一直进行flip，所以说，这个示例代码中的224取得不具代表意义、

我的想法是文档中怎么讲的，就严格怎么用，不然用户就无所适从了
这里的例子搞个概率为“224”，让人费解，改为“1”，不是更清晰
文档中的例子是有代表性的，是最典型的用法，是用户的模板

**Comment by hong19860320** [comment]
> > 可以结合这个代码看
> > https://github.com/PaddlePaddle/Paddle/blob/ec2fad4d5157ca0c5687a2dfd7c7ebec274e4df1/python/paddle/vision/transforms/transforms.py#L564
> > 
> > 224就是一个阈值，随机数小于这个阈值就做flip，由于随机数都是小于1.0的，所以如果设置为224，就代表一直进行flip，所以说，这个示例代码中的224取得不具代表意义、
> 
> 我的想法是文档中怎么讲的，就严格怎么用，不然用户就无所适从了
> 这里的例子搞个概率为“224”，让人费解，改为“1”，不是更清晰
> 文档中的例子是有代表性的，是最典型的用法，是用户的模板

嗯嗯，好的，我让相关同学改下，谢谢你的建议。
