### ISSUE TITLE
paddle2.0多进程数据加载报错

### ISSUE THREAD

**Issue by hefeng1995** [PaddlePaddle/Paddle#31181]
paddle2.0多进程数据加载，相同代码num_workers设置为0没有错误，设置为>0的值则捕捉到：
![image](https://user-images.githubusercontent.com/7439017/108949550-9369e380-769f-11eb-846a-96ab2cfe4ab7.png)

**Comment by hefeng1995** [comment]
paddle2.0多进程数据加载，相同代码num_workers设置为0没有错误，设置为>0的值则捕捉到：
![image](https://user-images.githubusercontent.com/7439017/108949368-3f5eff00-769f-11eb-90d2-40aefbae132a.png)

**Comment by hong19860320** [comment]
这个在用户群回复了，麻烦在创建的icafe卡片里面贴上能简单复现的代码哦
