### ISSUE TITLE
CentOS编译linux预测库时能否跳过git下载第三方源码

### ISSUE THREAD

**Issue by tustz** [PaddlePaddle/Paddle#31185]
- 版本、环境信息：
    1）PaddlePaddle2.0.0
    2）CPU：Intel(R) Xeon(R) CPU-E5-2680
    3）系统环境：CentOS 7.6

2）本地编译：cmake指令为
cmake -DFLUID_INFERENCE_INSTALL_DIR=$PADDLE_ROOT \
      -DCMAKE_BUILD_TYPE=Release \
      -DWITH_PYTHON=OFF \
      -DWITH_MKL=OFF \
      -DWITH_GPU=OFF  \
      -DON_INFER=ON \
      -DWITH_NCCL=OFF \
      -DWITH_XBYAK=ON \
      -DWITH_TENSORRT=OFF \
      ..
 make

- 问题描述：
由于服务器无法联网，编译linux预测库源码时无法通过git下载第三方库源码，请问有其他途径可以跳过该步骤吗，或者说我能否通过现有ubuntu编译的库中拷贝第三方库到源码并跳过git clone阶段

报错截图：
![error](https://user-images.githubusercontent.com/20158642/108962116-3ed06380-76b3-11eb-99ee-0874148e3852.PNG)

**Comment by tustz** [comment]
sorry, 找到可访问的yum镜像地址了

**Comment by Crystalxd** [comment]
请问你最后是怎么解决的？我将别人下载好的三方库（环境相同）拷贝到我的build/third_party目录里，结果在make的时候还是慢慢git下载
![image](https://user-images.githubusercontent.com/34636084/109926190-a44cd180-7cfd-11eb-839e-66f3618f02b0.png)
