### ISSUE TITLE
Jetson nano pip install paddlepaddle-gpu==2.0.0报错

### ISSUE THREAD

**Issue by Irvingao** [PaddlePaddle/Paddle#31183]
安装报错：`python3 -m pip install paddlepaddle-gpu==2.0.0 -i https://mirror.baidu.com/pypi/simple`
### JePack：4.4.1

![image](https://user-images.githubusercontent.com/58903762/108952856-32450e80-76a5-11eb-9235-88de1e0fda44.png)

**Comment by hong19860320** [comment]
paddlepaddle-gpu只针对服务器端的nv gpu，jetson目前只支持推理部署，可以看下这个文档 https://www.paddlepaddle.org.cn/documentation/docs/zh/guides/05_inference_deployment/inference/build_and_install_lib_cn.html#id2

**Comment by Irvingao** [comment]
### nano环境：
JetPack：4.3

### 我下载了官方编译好的nano的whl包：
![image](https://user-images.githubusercontent.com/58903762/109288816-54cf5700-7860-11eb-94e9-da0121d0d74f.png)
### 在jetson nano上也安装成功了：
![image](https://user-images.githubusercontent.com/58903762/109288985-8811e600-7860-11eb-8f43-8902cce0545a.png)
### 但是在import paddle的时候会崩溃：
![image](https://user-images.githubusercontent.com/58903762/109289071-a1b32d80-7860-11eb-8dae-ab2e4549b5b7.png)
### 请问是什么原因？

**Comment by wangye707** [comment]
@Irvingao  你好，你下载上面2.0.0-nv-jetson-jetpack4.3-all 这个版本的试下

**Comment by Irvingao** [comment]
> @Irvingao 你好，你下载上面2.0.0-nv-jetson-jetpack4.3-all 这个版本的试下

依然报相同的错误，我都重刷了镜像。。。。我看有其他人操作都成功了。。。就我报这个错。。

**Comment by Irvingao** [comment]
完全按照这个步骤来，依然报错：https://aistudio.baidu.com/aistudio/projectdetail/1591846?channelType=0&channel=0
