### ISSUE TITLE
2.0 CUDAPlace, set_device() 区别

### ISSUE THREAD

**Issue by QingquanBao** [PaddlePaddle/Paddle#31194]
我能否这样理解：在使用`paddle.to_tensor()`创建tensor时，要对参数`place=CUDAPlace(0)` 指定；而在对于一般的e.g. `paddle.zeros()` 之类的api，我只能使用`paddle.set_device(string)`来全局设定。而对于一般的tensor，我要改变，又只能用`tensor.cuda(0)` 才能改。
所以说，对于修改设备，我分别得用三种数据类型`paddle.place` ,` string` (e.g. "gpu:0") ,and `int`(e.g. device_id=0)。这明显没有torch一个device方便啊，还是说有统一的方法？

**Comment by hong19860320** [comment]
谢谢，我们会作为一个需求向PM反馈的哈。
