### ISSUE TITLE
一个开源软件被提issue多了，是好还是坏？

### ISSUE THREAD

**Issue by A-Pai** [PaddlePaddle/Paddle#31199]
一个开源软件被提issue多了，是好还是坏？

多了说明被关注的多，有用户追捧，在蓬勃发展中，同时也表明问题较多？
少了说明被关注的少，无人问津，发展迟缓，同时也表明问题较少？

我关注到以下三个深度学习框架的情况，能说明什么？
pytorch
![image](https://user-images.githubusercontent.com/5112397/109001177-9684c400-76df-11eb-9247-22948810d187.png)
tensorflow
![image](https://user-images.githubusercontent.com/5112397/109001250-aef4de80-76df-11eb-9b70-f9d46d3ef216.png)
paddle
![image](https://user-images.githubusercontent.com/5112397/109001353-cdf37080-76df-11eb-9c40-20e4a804f65d.png)

**Comment by wadefelix** [comment]
mark

**Comment by dingjiaweiww** [comment]
paddle 的github issue 定位是对框架的bugfix 和接受用户的新功能请求或优化等，使用咨询问题请转移到AI论坛（https://ai.baidu.com/forum/topic/list/168）, 大家可以在那里讨论

**Comment by A-Pai** [comment]
> paddle 的github issue 定位是对框架的bugfix 和接受用户的新功能请求或优化等，使用咨询问题请转移到AI论坛（[https://ai.baidu.com/forum/topic/list/168）](https://ai.baidu.com/forum/topic/list/168%EF%BC%89), 大家可以在那里讨论

这个地方不是针对AI Studio的？
