### ISSUE TITLE
建议文档中对于合集之类的条目也给出相应页面加以说明

### ISSUE THREAD

**Issue by A-Pai** [PaddlePaddle/Paddle#31198]
建议文档中对于合集之类的条目也给出相应页面加以说明--这些api是做哪方面使用的，比如以下，文档是软件最权威和最源头的说明，对于用户要尽量友好，方便使用，这对于软件的发展至关重要。

比如我现在就想知道，ops这个条目下的api做哪方面使用的。

![QQ截图20210224201953](https://user-images.githubusercontent.com/5112397/108999952-01350000-76de-11eb-93bd-574e57bf49aa.jpg)

**Comment by hong19860320** [comment]
这个API文档的首页有的哦 https://www.paddlepaddle.org.cn/documentation/docs/zh/api/index_cn.html
![image](https://user-images.githubusercontent.com/9973393/109021620-04d48100-76f6-11eb-925a-9f6f51ac5c78.png)

**Comment by A-Pai** [comment]
> 这个API文档的首页有的哦 https://www.paddlepaddle.org.cn/documentation/docs/zh/api/index_cn.html
> ![image](https://user-images.githubusercontent.com/9973393/109021620-04d48100-76f6-11eb-925a-9f6f51ac5c78.png)

说的不是这些总条目，而是下边的二级条目，比如上边截图的ops这个条目
并且这些总条目页面也不是左右联动的，最好是左右联动，便于查询

**Comment by TCChenlong** [comment]
二级条目我们正在添加中，比如 paddle.nn 中已经添加了对应的说明；paddle.vision相关的内容已经书写完毕了，预计今晚就会上线，感谢反馈~

**Comment by wadefelix** [comment]
mark

**Comment by TCChenlong** [comment]
目前大部分package的说明页已上线，可以在 [API文档](https://www.paddlepaddle.org.cn/documentation/docs/zh/api/index_cn.html) 每个栏目下的Overview页面下查看，如有优化的建议，可以新开一个ISSUE反馈 感谢反馈~
