### ISSUE TITLE
文档中前边的“class”表示什么

### ISSUE THREAD

**Issue by A-Pai** [PaddlePaddle/Paddle#31203]
https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/hapi/model/Model_cn.html#paddle.Model

![image](https://user-images.githubusercontent.com/5112397/109087801-21e66f80-7749-11eb-8ee3-f976751cc8f6.png)

**Comment by wangchaochaohu** [comment]
python 中的Class 类 代表是一个Class 类
