### ISSUE TITLE
如何选择concat拼接的axis？

### ISSUE THREAD

**Issue by foxgaga** [PaddlePaddle/Paddle#3120]
```
paddle.init(use_gpu=False, trainer_count=3)
word_dict = paddle.dataset.imikolov.build_dict()
dict_size = len(word_dict)
# Every layer takes integer value of range [0, dict_size)
firstword = paddle.layer.data(
    name="firstw", type=paddle.data_type.integer_value(dict_size))
secondword = paddle.layer.data(
    name="secondw", type=paddle.data_type.integer_value(dict_size))
thirdword = paddle.layer.data(
    name="thirdw", type=paddle.data_type.integer_value(dict_size))
fourthword = paddle.layer.data(
    name="fourthw", type=paddle.data_type.integer_value(dict_size))
nextword = paddle.layer.data(
    name="fifthw", type=paddle.data_type.integer_value(dict_size))

Efirst = wordemb(firstword)
Esecond = wordemb(secondword)
Ethird = wordemb(thirdword)
Efourth = wordemb(fourthword)

contextemb = paddle.layer.concat(input=[Efirst, Esecond, Ethird, Efourth])
```

[词向量book](https://github.com/PaddlePaddle/book/tree/develop/04.word2vec
)中对词进行了concat拼接（4x(32x1)->1x128x1），想问下如何拼接得到（4x32x1)来复现word2vec源码进行sum pooling。
`paddle.layer.pooling(input= contextemb, pooling_type=paddle.pooling.Sum())
`
谢谢。

**Comment by reyoung** [comment]
实现词向量的sum pooling，可以参考这个[源码](https://github.com/reyoung/ChineseWordVectors/blob/master/cbow.py#L36).

**Comment by foxgaga** [comment]
1、词向量的sum pooling是不是也可以类似这个[issue](https://github.com/PaddlePaddle/Paddle/issues/3121)
一次输入一个数组，使用paddle.pooling.Sum完成。
如下
```
mov_title_id = paddle.layer.data(
    name='movie_title',
    type=paddle.data_type.integer_value_sequence(len(movie_title_dict)))
mov_title_emb = paddle.layer.embedding(input=mov_title_id, size=32)
paddle.layer.pooling(input= mov_title_emb, pooling_type=paddle.pooling.Sum())得到
1*embsize

```
2、如果要纵向连接类似这个[issue]中的layers：mov_fc和mov_title_conv，请问怎么完成？

谢谢

**Comment by foxgaga** [comment]
类似[Youtube recommender system(https://raw.githubusercontent.com/PaddlePaddle/book/develop/05.recommender_system/image/Deep_candidate_generation_model_architecture.en.png)
中的video watches or video search tokens 的数量会存在小于固定值（50）的情况，而不是像word2vec的数量是固定的[window size](https://github.com/reyoung/ChineseWordVectors/blob/master/cbow.py#L25)这部分应该怎么处理啊


谢谢

**Comment by reyoung** [comment]
> 词向量的sum pooling是不是也可以类似这个issue
一次输入一个数组，使用paddle.pooling.Sum完成。

是的。

> 如果要纵向连接类似这个issue中的layers：mov_fc和mov_title_conv，请问怎么完成

不是特别清楚纵向连接指的是什么？

> 而不是像word2vec的数量是固定的window size这部分应该怎么处理啊

使用pooling即可。

类似于下面的代码，这里movie_title的长度可以是任意长度。
```python
mov_title_id = paddle.layer.data(
    name='movie_title',
    type=paddle.data_type.integer_value_sequence(len(movie_title_dict)))
mov_title_emb = paddle.layer.embedding(input=mov_title_id, size=32)
paddle.layer.pooling(input= mov_title_emb, pooling_type=paddle.pooling.Sum())
```

**Comment by foxgaga** [comment]
纵向连接就是将四个embeding 拼接4x(1*32)为一个layer（4x32)，而不是拼接为1*128
谢谢

**Comment by reyoung** [comment]
可以分别做 sum_pooling, 得到两个 `1*32`的向量，然后再使用concat layer进行拼接。

**Comment by foxgaga** [comment]
> 可以分别做 sum_pooling, 得到两个 1*32的向量，然后再使用concat layer进行拼接。
concat layer进行拼接后向量变成1*64了
我是想如何得到一个1*32向量.

谢谢
