### ISSUE TITLE
为何paddle.vision.models中的模型有的没有pretrained参数

### ISSUE THREAD

**Issue by A-Pai** [PaddlePaddle/Paddle#31204]
https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/vision/models/resnet/resnet18_cn.html
https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/vision/models/resnet/ResNet_cn.html

为何paddle.vision.models中的模型有的没有pretrained参数？比如：
![image](https://user-images.githubusercontent.com/5112397/109088347-3840fb00-774a-11eb-8a07-fa4654ea015e.png)
![image](https://user-images.githubusercontent.com/5112397/109088426-53136f80-774a-11eb-90bc-551115def3bd.png)

**Comment by LielinJiang** [comment]
预训练模型是配合特定的参数的。resnet50是通过传入特定参数给ResNet来构造的。而ResNet这个类可以构造出像resnet18，resnet34等网络结构，也可以通过自定义block来改变对应的参数。不一定能有对应的预训练模型。总而言之，使用场景不一样。
