### ISSUE TITLE
如何实现内置数据集的提取或重组？

### ISSUE THREAD

**Issue by zshxn1985** [PaddlePaddle/Paddle#31206]
如下面的训练数据集：
train_dataset=paddle.vision.datasets.MNIST(mode='train',transform=transform)
现需从里面提取一部分作为新的评估数据集，该如何处理。
或按照现有的一个list来提取，应该怎么实现，如list如下：
list=[1,100,1000]
谢谢。

**Comment by wangchaochaohu** [comment]
查看了源码 只能通过__get_item__也就是[]去获取单个元素 然后进行重组 @LielinJiang  不知道是否有其他比较好的方法

**Comment by zshxn1985** [comment]
@wangchaochaohu 谢谢，已解决。
