### ISSUE TITLE
昆仑小型机上源码编译paddle2.0release版本出错

### ISSUE THREAD

**Issue by gpsherry** [PaddlePaddle/Paddle#31216]
![image](https://user-images.githubusercontent.com/73693444/109128260-46af0700-778a-11eb-80a2-3178b0cb326d.png)

**Comment by wangchaochaohu** [comment]
可以查看下GCC版本 可以参考这个回答？ https://stackoverflow.com/questions/45347838/c-undefined-reference-to-stdthread-while-compiling-opencv-and-tensorflow-wi
