### ISSUE TITLE
请问masked_fill 如何实现？

### ISSUE THREAD

**Issue by gongel** [PaddlePaddle/Paddle#31214]
为True的位置填充指定的value

**Comment by wangchaochaohu** [comment]
可以参考 https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/tensor/search/masked_select_cn.html#masked-select

**Comment by gongel** [comment]
> 可以参考 https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/tensor/search/masked_select_cn.html#masked-select

感觉实现不了。[masked_fill](https://pytorch.org/docs/master/tensors.html?highlight=masked_fill#torch.Tensor.masked_fill)是填充指定的值

**Comment by gongel** [comment]
解决了，多谢。paddle.where可以。
