### ISSUE TITLE
embedding layer 的输入层和连接层

### ISSUE THREAD

**Issue by foxgaga** [PaddlePaddle/Paddle#3121]
[recommender_system book](https://github.com/PaddlePaddle/book/tree/develop/05.recommender_system)
里可以看到embeding layer可以输入integer_value和integer_value_sequence。

```
mov_id = paddle.layer.data(
    name='movie_id',
    type=paddle.data_type.integer_value(
        paddle.dataset.movielens.max_movie_id() + 1))
mov_emb = paddle.layer.embedding(input=mov_id, size=32)
mov_fc = paddle.layer.fc(input=mov_emb, size=32)

movie_title_dict = paddle.dataset.movielens.get_movie_title_dict()
mov_title_id = paddle.layer.data(
    name='movie_title',
    type=paddle.data_type.integer_value_sequence(len(movie_title_dict)))
mov_title_emb = paddle.layer.embedding(input=mov_title_id, size=32)
mov_title_conv = paddle.networks.sequence_conv_pool(
    input=mov_title_emb, hidden_size=32, context_len=3)
```
integer_value可以连接为一个1\*embsize的layer，integer_value_sequence是否可以理解为n\*embsize的layer，是否可以连接paddle.layer.pooling(input= contextemb, pooling_type=paddle.pooling.Sum())得到
1*embsize

ps:如何输出各个层的大小或者输出计算图

**Comment by reyoung** [comment]
> integer_value可以连接为一个1\*embsize的layer，integer_value_sequence是否可以理解为n\*embsize的layer

`integer_value+emb_layer`可以理解为输出是`dense_vector`, `integer_value_sequence+emb_layer`可以理解为输出是`dense_vector_sequence`。

> 连接paddle.layer.pooling(input= contextemb, pooling_type=paddle.pooling.Sum())。

`integer_value_sequence + emb_layer + pooling` => `integer_value_sequence => dense_vector_sequence + pooling` => `dense_vector`

**Comment by lcy-seso** [comment]
长时间未活动，遂关闭此issue，如有问题，请在新的issue中继续提问。谢谢啦。
