### ISSUE TITLE
关于cnn进行文本训练时，paddle如果指定的序列长度问题求助

### ISSUE THREAD

**Issue by HugoLian** [PaddlePaddle/Paddle#3122]
我看了一下paddle的代码，sequence_conv_pool层的介绍是这样的：
Text input => Context Projection => FC Layer => Pooling => Output.
参考：
sequence_conv_pool中Context_projection（）的定义，如果context_len = 3
原始输入是：
[A B C D E F G]
那么卷积 后的结果：
[ 0AB ABC BCD CDE DEF EFG FG0 ]
我理解上述过程完成的应该是从 input 到 FC Layer的操作

在fc layer之后要做pooling，也就是对每次卷积结果0AB, ABC ... 做默认的max pooling
输出应该是：
[ m0, m1, m2, m3, m4, m5, m6 ]
然后pooling之后的结果，再通过一个全链接层做softmax得到分类结果，即下图中红框的部分：
![image](https://user-images.githubusercontent.com/22980558/28765899-99878302-75ff-11e7-8342-146c0e8bf0c8.png)

但是paddle中并没有参数对pooling层的节点数量做设置，请问这个设置在paddle中是如何实现的呢？
如果context_len都是：3 
当输入是[ A B C ]时，卷积是[ 0AB ABC BC0] pooling后是 [ m0, m1, m2]
当输入是[ A B C D E ]时，卷积是[ 0AB ABC BCD CDE DE0] pooling后是 [ m0, m1, m2, m3, m4] 这个参数肯定是要固定吧？

**Comment by livc** [comment]
>那么卷积 后的结果：
>[ 0AB ABC BCD CDE DEF EFG FG0 ]
你理解的不对，中间卷积层的结果有四个vector对应四个卷积核计算的结果，以第一个为例，这个vector有四个值，其中每一个值都是诸如（0AB）这种子序列与卷积核计算的结果，窗口全部滑动结束后构成一个feature map。

论文请参考 http://cslt.riit.tsinghua.edu.cn/mediawiki/images/f/fe/Convolutional_Neural_Networks_for_Sentence_Classiﬁcation.pdf
PaddlePaddle的视频课程请参考 http://bit.baidu.com/course/detail/id/176/column/117.html

**Comment by HugoLian** [comment]
那可以这么理解么？
conv_2 = sequence_conv_pool(input=emb, context_len=2, hidden_size=128)
上面的网络结构表明：一个序列中支持的最长的卷积个数是128个，如果不到就补0，如果超出就截断，或者报错？ @livc

**Comment by livc** [comment]
hidden_size可以理解为卷积核的个数，`sequence_conv_pool` 中的`fc_layer`的大小是，x为词向量纬度\*词窗口大小（来自于[ContextProjection](https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/gserver/layers/ContextProjection.h)），y为hidden_size这样一个二维矩阵，可以理解为y个大小为x*1的卷积核，作用是一样的。

**Comment by HugoLian** [comment]
可以理解成sequence_conv_pool 一次卷积+pooling的操作，生成的是一个maxpooling的数值，hidden_size表明了用多少个卷积核去卷积，最后max pooling输出的就是hidden_size个结果，即维度是hidden_size的一个向量？ @livc

**Comment by livc** [comment]
> hidden_size表明了用多少个卷积核去卷积，最后max pooling输出的就是hidden_size个结果，即维度是hidden_size的一个向量

这样理解是正确的。

**Comment by HugoLian** [comment]
非常感谢！ @livc
