### ISSUE TITLE
使用paddle.jit.save()保存模型以后，使用paddle.inference()加载无法使用

### ISSUE THREAD

**Issue by geekChinaMaster** [PaddlePaddle/Paddle#31222]
#### 在ai studio上面使用paddle2.0来运行项目：“使用PaddleNLP语义预训练模型ERNIE完成快递单信息抽取”，使用了自定义的数据集训练已经收敛好，由于预测速度非常慢，所以用paddle.jit.save()保存模型，之后尝试使用paddle.inference()来加载模型进行使用，参照了官方文档里面的示例加载，出现了错误，麻烦解答一下

代码如下：
﻿﻿
![图片](https://user-images.githubusercontent.com/44657953/109142427-d4462300-7799-11eb-8c6e-bcc90c621c76.png)

![图片](https://user-images.githubusercontent.com/44657953/109142582-0061a400-779a-11eb-99ff-583f1af75d20.png)

Ps: 关于paddle.inference()部署模型这块官方文档看不太明白，尤其是有关nlp这块好像示例很少，不知道该怎么用，麻烦指点一二

**Comment by hong19860320** [comment]
![image](https://user-images.githubusercontent.com/9973393/109145029-e8d7ea80-779c-11eb-8e7f-f900ebc0f70a.png)
首先需要调用paddle.jit.to_static动转静后，然后调用paddle.jit.save保存预测模型。

**Comment by geekChinaMaster** [comment]
> ![image](https://user-images.githubusercontent.com/9973393/109145029-e8d7ea80-779c-11eb-8e7f-f900ebc0f70a.png)
> 首先需要调用paddle.jit.to_static动转静后，然后调用paddle.jit.save保存预测模型。

ok按照您的方法保存模型以后，使用paddle.jit.load()可以加载模型并正确返回了，但是使用paddle.inference()加载模型时候还是报错，麻烦看下

![图片](https://user-images.githubusercontent.com/44657953/109159682-dd41ef00-77af-11eb-94dc-4d7196d62286.png)
![图片](https://user-images.githubusercontent.com/44657953/109159749-f3e84600-77af-11eb-80a9-bac646184b78.png)
![图片](https://user-images.githubusercontent.com/44657953/109159869-14180500-77b0-11eb-9ec8-a4e31febbaa2.png)

**Comment by geekChinaMaster** [comment]
> 
> 
> ![image](https://user-images.githubusercontent.com/9973393/109145029-e8d7ea80-779c-11eb-8e7f-f900ebc0f70a.png)
> 首先需要调用paddle.jit.to_static动转静后，然后调用paddle.jit.save保存预测模型。
您好，这块使用paddle.inference()部署时候的输入是怎么样的，按照官网文档给出的示例来操作会显示我截图中的报错，请问这个该如何去做才能正确部署

**Comment by jiamingming-004** [comment]
你出来没

**Comment by geekChinaMaster** [comment]
> 你出来没

出来了，后来是我推理的时候自己没有把输入的维度搞对，所以出现了错误

**Comment by diandian11** [comment]
> > 你出来没
> 
> 出来了，后来是我推理的时候自己没有把输入的维度搞对，所以出现了错误

这个输入的维度怎么确定？哪儿可以看，还有如果输入多个值怎么用？
