### ISSUE TITLE
multinomial的性能问题

### ISSUE THREAD

**Issue by duyiqi17** [PaddlePaddle/Paddle#31233]
如题，paddle2.0版本，cuda10.1，使用multinomial从一个概率分布上抽样，CPU和GPU版本性能有较大diff
GPU：
![image](https://user-images.githubusercontent.com/12961597/109164550-8b03cc80-77b5-11eb-99c2-7e0727eb70a3.png)
CPU:
![image](https://user-images.githubusercontent.com/12961597/109164587-948d3480-77b5-11eb-845b-67e23fe1de90.png)

pytorch没有这个问题
![image](https://user-images.githubusercontent.com/12961597/109164914-edf56380-77b5-11eb-940f-6651b8298c27.png)

**Comment by wangchaochaohu** [comment]
感谢反馈 关于此性能问题我们会及时验证并进行优化
