### ISSUE TITLE
报错except: 'NoneType' object is not callable

### ISSUE THREAD

**Issue by lucifer726** [PaddlePaddle/Paddle#31235]
- 标题：运行python -m paddlerec.run -m models/recall/gnn/config.yaml时报错，except: 'NoneType' object is not callable
****************************************
Paddle version: 1.8.5
Paddle With CUDA: False
OS: Windows 10
Python version: 3.7.0
CUDA version: None
cuDNN version: None
Nvidia driver version: None
****************************************
- 训练信息
    1）单机，单卡/多卡
    2）显存信息
    3）Operator信息
- 复现信息：如为报错，请给出复现环境、复现步骤
按照官网gnn教程运行时，报错except: 'NoneType' object is not callable

- 问题描述：请详细描述您的问题，同步贴出报错信息、日志、可复现的代码片段
====================================================================================================
                Runtime Envs                      Value
----------------------------------------------------------------------------------------------------
====================================================================================================

============================================================================================================
                paddlerec Global Envs                     Value
------------------------------------------------------------------------------------------------------------
workspace                                                 models\recall\gnn
dataset.dataset_train.name                                dataset_train
dataset.dataset_train.batch_size                          10
dataset.dataset_train.type                                DataLoader
dataset.dataset_train.data_path                           models\recall\gnn\data\train
dataset.dataset_train.data_converter                      models\recall\gnn\reader.py
dataset.dataset_infer.name                                dataset_infer
dataset.dataset_infer.batch_size                          50
dataset.dataset_infer.type                                DataLoader
dataset.dataset_infer.data_path                           models\recall\gnn\data\test
dataset.dataset_infer.data_converter                      models\recall\gnn\evaluate_reader.py
hyper_parameters.optimizer.class                          Adam
hyper_parameters.optimizer.learning_rate                  0.001
hyper_parameters.optimizer.decay_steps                    3
hyper_parameters.optimizer.decay_rate                     0.1
hyper_parameters.optimizer.l2                             1e-05
hyper_parameters.sparse_feature_number                    43098
hyper_parameters.sparse_feature_dim                       100
hyper_parameters.corpus_size                              719470
hyper_parameters.gnn_propogation_steps                    1
mode                                                      ['single_cpu_train', 'single_cpu_infer']
runner.single_cpu_train.name                              single_cpu_train
runner.single_cpu_train.class                             train
runner.single_cpu_train.epochs                            5
runner.single_cpu_train.device                            cpu
runner.single_cpu_train.save_checkpoint_interval          1
runner.single_cpu_train.save_inference_interval           1
runner.single_cpu_train.save_checkpoint_path              increment_gnn
runner.single_cpu_train.save_inference_path               inference_gnn
runner.single_cpu_train.save_inference_feed_varnames      []
runner.single_cpu_train.save_inference_fetch_varnames     []
runner.single_cpu_train.init_model_path
runner.single_cpu_train.print_interval                    1
runner.single_cpu_train.phases                            ['phase1']
runner.single_cpu_infer.name                              single_cpu_infer
runner.single_cpu_infer.class                             infer
runner.single_cpu_infer.device                            cpu
runner.single_cpu_infer.print_interval                    1
runner.single_cpu_infer.init_model_path                   increment_gnn
runner.single_cpu_infer.phases                            ['phase2']
phase.phase1.name                                         phase1
phase.phase1.model                                        models\recall\gnn\model.py
phase.phase1.dataset_name                                 dataset_train
phase.phase1.thread_num                                   1
phase.phase2.name                                         phase2
phase.phase2.model                                        models\recall\gnn\model.py
phase.phase2.dataset_name                                 dataset_infer
phase.phase2.thread_num                                   1
============================================================================================================

PaddleRec: Runner single_cpu_train Begin
Executor Mode: train
processor_register begin
Running SingleInstance.
Running SingleNetwork.
Traceback (most recent call last):
  File "C:\Users\lucifer\paddlepaddle\lib\site-packages\paddle_rec-1.8.5-py3.7.egg\paddlerec\core\utils\envs.py", line 240, in lazy_instance_by_fliename
    globals(), locals(), package.split("."))
  File "models\recall\gnn\model.py", line 18, in <module>
    paddle.enable_static()
AttributeError: module 'paddle' has no attribute 'enable_static'
Catch Exception:module 'paddle' has no attribute 'enable_static'
Traceback (most recent call last):
  File "C:\Users\lucifer\paddlepaddle\lib\site-packages\paddle_rec-1.8.5-py3.7.egg\paddlerec\core\trainer.py", line 255, in run
    self.context_process(self._context)
  File "C:\Users\lucifer\paddlepaddle\lib\site-packages\paddle_rec-1.8.5-py3.7.egg\paddlerec\core\trainer.py", line 216, in context_process
    self._status_processor[context['status']](context)
  File "C:\Users\lucifer\paddlepaddle\lib\site-packages\paddle_rec-1.8.5-py3.7.egg\paddlerec\core\trainers\general_trainer.py", line 90, in network
    network_class.build_network(context)
  File "C:\Users\lucifer\paddlepaddle\lib\site-packages\paddle_rec-1.8.5-py3.7.egg\paddlerec\core\trainers\framework\network.py", line 64, in build_network
    model_path, "Model")(context["env"])
TypeError: 'NoneType' object is not callable
Catch Exception:'NoneType' object is not callable

--------------------------------
PaddleRec Error Message Summary:
--------------------------------

Exit PaddleRec. catch exception in precoss status: [network_pass], except: 'NoneType' object is not callable
TypeError

**Comment by yongqiangma** [comment]
paddlerec应该已经全面升级到2.0了 会有不兼容的地方，建议升级到paddle2.0

**Comment by lucifer726** [comment]
您好，之前我用的就是2.0的版本，遇到类似的问题，你们回复我说gnn需要1.8.5的版本。所以我想问一下，运行gnn，到底需要什么版本？

**Comment by frankwhzhang** [comment]
> 您好，之前我用的就是2.0的版本，遇到类似的问题，你们回复我说gnn需要1.8.5的版本。所以我想问一下，运行gnn，到底需要什么版本？

目前gnn这个模型暂时未升级到2.0，可以切换1.8.5的分支 并使用1.8.5的whl包安装paddlerec并运行。预计下个月gnn会升级到2.0
