### ISSUE TITLE
pip安装包有问题请尽快check

### ISSUE THREAD

**Issue by starsblinking** [PaddlePaddle/Paddle#31242]
https://www.paddlepaddle.org.cn/whl/develop.html 里有两个 paddlepaddle-2.1.0.dev0-cp38-cp38-linux_x86_64.whl
其中，https://paddle-wheel.bj.bcebos.com/develop-cpu-openblas/paddlepaddle-2.1.0.dev0-cp38-cp38-linux_x86_64.whl 的版本严重落后于 https://paddle-wheel.bj.bcebos.com/develop-cpu-mkl/paddlepaddle-2.1.0.dev0-cp38-cp38-linux_x86_64.whl

使用 pip install --pre paddlepaddle -f https://paddlepaddle.org.cn/whl/develop.html 来安装的话，有可能下载的是develop-cpu-openblas下的旧版本

**Comment by yongqiangma** [comment]
好的，我转相关同学，进行check下。

**Comment by yongqiangma** [comment]
多谢反馈，目前已经在修复了。

**Comment by starsblinking** [comment]
Now it looks OK
