### ISSUE TITLE
在windows上通过pythonw运行无法加载paddle

### ISSUE THREAD

**Issue by thunder95** [PaddlePaddle/Paddle#31251]
在普通的pc上， 已安装cpu版本的paddlepaddle 2.0，希望后台运行训练程序， 但是无法通过pythonw运行

简单的代码test.py：
try:
    import paddle
    print("hello world!")
except Exception as e:
    print(str(e))
    sys.exit(13)

通过cmd命令， python test.py >> a.log, 日志文件会输出hello world
通过cmd命令， pythonw test.py >> a.log, 日志文件会报错[WinError 6] 句柄无效。

**Comment by thunder95** [comment]
同样的代码，我注释掉import paddle， 换成import tensorflow之后是没有问题的， 正常输出为hello world。 但是我更喜欢用paddle

**Comment by zhwesky2010** [comment]
@thunder95 您好，请问使用pythonw的场景是什么样呢，目前Paddle发版时没有检测pythonw，可能存在bug

**Comment by thunder95** [comment]
> @thunder95 您好，请问使用pythonw的场景是什么样呢，目前Paddle发版时没有检测pythonw，可能存在bug

我需要在windows下后台运行python程序，该程序包含了paddle包， 有什么替代方案么？ 
不是使用http服务的方式，而是cmd一次性的命令调用

**Comment by zhwesky2010** [comment]
@thunder95 您好，我这边进行了一些尝试：

![infoflow 2021-08-03 16-31-57](https://user-images.githubusercontent.com/52485244/127984515-95dcf320-19ab-42c7-bff4-9a1a3f2fec96.png)

通过pythonw运行上述脚本，没有复现您说的问题，日志可以正常打印：

![infoflow 2021-08-03 16-32-18](https://user-images.githubusercontent.com/52485244/127984631-b61490af-50c9-4461-9825-07cc29c5e27a.png)
