### ISSUE TITLE
linux pip安装错误

### ISSUE THREAD

**Issue by Wzh1997** [PaddlePaddle/Paddle#31273]
cuda：10.2
cudnn：8.0.3
python：3.6
![image](https://user-images.githubusercontent.com/40290961/109295243-5f421e80-7869-11eb-8518-00f6611753be.png)
这是系统信息

![image](https://user-images.githubusercontent.com/40290961/109295096-1ee2a080-7869-11eb-8e68-c228a74113c0.png)
linux下pip安装完后去测试出现错误，这个是什么原因呢

**Comment by yongqiangma** [comment]
系统版本是多少呢？
https://www.paddlepaddle.org.cn/install/quick?docurl=/documentation/docs/zh/2.0/install/pip/linux-pip.html
可以参考这个说明，check一下。
