### ISSUE TITLE
C++ 部署预测库 setModel报错

### ISSUE THREAD

**Issue by 72min** [PaddlePaddle/Paddle#31289]
预测库版本 cpu_avx_mkl 预测库(2.0.0)
![QQ截图20210228151125](https://user-images.githubusercontent.com/60537262/109412060-d9e17a00-79e0-11eb-9b9a-c6f86f401816.png)

```
#include <iostream>
#include"paddle_inference_api.h"
using namespace paddle;


int main()
{
    
    AnalysisConfig config;
    config.SwitchUseFeedFetchOps(false);
    config.SetModel("D:\\DM\\cppdm\\cpptest\\ConsoleApplication1\\x64\\Debug\\model\\model_12000.pdmodel", "D:\\DM\\cppdm\\cpptest\\ConsoleApplication1\\x64\\Debug\\model\\model_12000.pdparams");

    std::cout << "Hello World!\n";
  
   

}
```

**Comment by willthefrog** [comment]
好的，会反馈相关同学跟进

**Comment by 72min** [comment]
环境：VS2019 官网下载的2.0预测库 CPU版本https://paddle-wheel.bj.bcebos.com/2.0.0/win-infer/mkl/cpu/paddle_inference_install_dir.zip
----------------------------------------
希望官网能增加一下C++打包DLL 给C#调用的 完整教程，有的小伙伴基础不好 又没有C++开发经验 部署过程挺痛苦的。

**Comment by willthefrog** [comment]
能否请 @Superjomn 跟进下？

**Comment by jiweibo** [comment]
您好，目前官网发布的预测库均是在vs2015上编译得到的，能否使用vs2015测试下呢？
config.SetModel接口只是设置模型的存储路径，内部不包含复杂逻辑，所以推测该问题应该是环境原因导致。

关于C++打包DLL给C#调用，这个网上能搜到较多教程可以参考下，我们内部也评估下是否需要增加相关文档。

**Comment by 72min** [comment]
VS 2015测试过  #[设置目录一样报错。但是从内存读入是可以正常使用的。
![vs2015成功](https://user-images.githubusercontent.com/60537262/109512267-e1874880-7ade-11eb-89b7-22d85e88576b.png)
-----------------------------成功
![vs2015失败目录](https://user-images.githubusercontent.com/60537262/109512295-ec41dd80-7ade-11eb-8619-19df36f2ddc3.png)
-----------------------------失败

**Comment by 72min** [comment]
关于CPP部署官网文档描述的不够细致 网上搜的 大多是PaddleX 还有PaddleOcr 等集合项目源码用MK去编译，，但是我的模型是用Paddle CV 里面的官方模型库。

**Comment by Superjomn** [comment]
内存可以读取，但设置路径不行，看看是不是相对路径出错了（bin 执行路径跟源码路径不一样），绝对路径试试。

@jiweibo 关注下，windows为啥没有报错信息，是不是异常打不出信息

**Comment by qingchunnianshao** [comment]
请问有解决吗，本地重新编译了paddle的库，用VS2019 编译的，直接SetModel也不行但是SetModelBuffer是可以的
