### ISSUE TITLE
invalid poly

### ISSUE THREAD

**Issue by jey07** [PaddlePaddle/Paddle#31285]
While training using **det_r50_vd_sast_icdar15.yml** config file on my personal dataset, I am getting `invalid poly` during epochs.
I think it has to do with image size ?. I am using **ResNet50_vd**  as backbone model Could you tell me how to correct it or resolve it ?

But when i run the same set of images through "det_mv3_db.yml" config, I don't encounter invalid poly issues.  

Is there some kind of FLAG or minimum dimension of image that resnet50 expects ?

**Comment by MissPenguin** [comment]
This error is because a few training data format is incorrect, which does not affect the overall training.
