### ISSUE TITLE
to_grayscale的命名为何和别的不同

### ISSUE THREAD

**Issue by A-Pai** [PaddlePaddle/Paddle#31284]
https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/vision/transforms/functional/to_grayscale_cn.html

本模块的命名大多是类似“Resize”和“resize”--仅仅是首字母大小写之分

为何to_grayscale、Grayscale的命名为何和别的不同？

**Comment by zhupengyang** [comment]
命名上只是遵循一般规范而已，和仅仅区分首字母没什么关系。一个函数它的作用是resize，那他的名称就叫resize。一个函数它的作用是 "to grayscale"，那他的名称就叫to_scale。

**Comment by A-Pai** [comment]
> 命名上只是遵循一般规范而已，和仅仅区分首字母没什么关系。一个函数它的作用是resize，那他的名称就叫resize。一个函数它的作用是 "to grayscale"，那他的名称就叫to_scale。

我不这样认为，按照约定的规范命名更好，本模块的命名是类似“Resize”和“resize”，便于使用和记忆。
--既然有了“Grayscale”，其对应的就应该命名为grayscale，命名为grayscale难道不能很好地反映它的作用？
