### ISSUE TITLE
感觉到文档中“Resize”返回“ numpy ndarray，调整大小后的图像”，说的有问题

### ISSUE THREAD

**Issue by A-Pai** [PaddlePaddle/Paddle#31287]
先看前边的说明，二者的说法不一致，我觉得文档中说“Resize”返回“ numpy ndarray，调整大小后的图像”，应该是形成一个“Resize”对象

![QQ截图20210227205649](https://user-images.githubusercontent.com/5112397/109389915-8e2fc180-7949-11eb-9ed8-0ef7fc165856.jpg)

再看实际代码运行；
![QQ截图20210227205828](https://user-images.githubusercontent.com/5112397/109389885-6cced580-7949-11eb-8a4f-859f2fb4e13b.jpg)

“transform”实际上是一个“Resize”类型的对象

![QQ截图20210227222503](https://user-images.githubusercontent.com/5112397/109390232-545fba80-794b-11eb-80cf-962877a6bc1d.jpg)

**Comment by zhupengyang** [comment]
已经收到您的建议。文档表述有些不清晰，后续会进行相应调整。

**Comment by A-Pai** [comment]
计算机是特别要求严谨和准确的
