### ISSUE TITLE
RandomResizedCrop文档中“scale”讲解不清

### ISSUE THREAD

**Issue by A-Pai** [PaddlePaddle/Paddle#31298]
RandomResizedCrop文档中“scale”讲解不清
https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/vision/transforms/transforms/RandomResizedCrop_cn.html
![QQ截图20210301092915](https://user-images.githubusercontent.com/5112397/109441606-a2baa980-7a70-11eb-866b-114e3bf5f27c.jpg)

**Comment by LielinJiang** [comment]
好的，我们优化一下
