### ISSUE TITLE
有没有很方便的加载硬盘数据并且拆分训练集测试集的函数？谢谢

### ISSUE THREAD

**Issue by JimXu1989** [PaddlePaddle/Paddle#31296]
请问有相关的例程吗？我加载图片训练总是失败，而且
train_loader = paddle.batch(paddle.dataset.mnist.train(), batch_size=10)
和
train_loader = DataLoader(dataset,batch_size=BATCH_SIZE, shuffle=True, drop_last=True, num_workers=2)
这两种方法产生的loader并不是一种类型

还有，有没有能自动把数据集拆分成训练集和测试集的函数？

感谢

**Comment by JimXu1989** [comment]
这是我的代码：

import paddle
import numpy as np
from paddle.nn import Conv2D, MaxPool2D, Linear
import os
import random
import numpy as np
from imutils import paths
import imutils
## 组网
import paddle.nn.functional as F
from paddle.io import Dataset
from paddle.io import DataLoader
import cv2


BATCH_NUM = 20
BATCH_SIZE = 16
EPOCH_NUM = 4

IMAGE_SIZE = 784
CLASS_NUM = 10


class Animals_dataset(Dataset):
    def __init__(self, num_samples):
        self.img_files = list(paths.list_images('./animals'))
        self.num_samples = len(self.img_files)

    def __getitem__(self, idx):
        image = cv2.imread(self.img_files[idx])
        label = self.img_files[idx].split('/')[-2]
        return image, label

    def __len__(self):
        return self.num_samples


class LeNet(paddle.nn.Layer):
    def __init__(self, num_classes=1):
        super(LeNet, self).__init__()
        self.conv1 = Conv2D(in_channels=1, out_channels=6, kernel_size=5)
        self.max_pool1 = MaxPool2D(kernel_size=2, stride=2)
        self.conv2 = Conv2D(in_channels=6, out_channels=16, kernel_size=5)
        self.max_pool2 = MaxPool2D(kernel_size=2, stride=2)
        self.conv3 = Conv2D(in_channels=16, out_channels=120, kernel_size=4)

        self.fc1 = Linear(in_features=120, out_features=64)
        self.fc2 = Linear(in_features=64, out_features=num_classes)

    # 网络的前向计算过程
    def forward(self, x):
        x = self.conv1(x)
        x = F.sigmoid(x)
        x = self.max_pool1(x)
        x = F.sigmoid(x)
        x = self.conv2(x)
        x = self.max_pool2(x)
        x = self.conv3(x)
        x = paddle.reshape(x, [x.shape[0], -1])
        x = self.fc1(x)
        x = F.sigmoid(x)
        x = self.fc2(x)
        return x


x = np.random.randn(*[3, 1, 28, 28])
x = x.astype('float32')

m = LeNet(num_classes=10)
print(m.sublayers())
x = paddle.to_tensor(x)
for item in m.sublayers():
    try:
        x = item(x)
    except:
        x = paddle.reshape(x, [x.shape[0], -1])
        x = item(x)
    if len(item.parameters()) == 2:
        print(item.full_name(), x.shape, item.parameters()[0].shape, item.parameters()[1].shape)
    else:
        print(item.full_name(), x.shape)

dataset = Animals_dataset(BATCH_NUM * BATCH_SIZE)

def train(model):
    # 开启0号GPU训练
    use_gpu = True
    paddle.set_device('gpu:0') if use_gpu else paddle.set_device('cpu')
    print('start training ... ')
    model.train()
    epoch_num = 5
    opt = paddle.optimizer.Momentum(learning_rate=0.001, momentum=0.9, parameters=model.parameters())

    train_loader = DataLoader(dataset,batch_size=BATCH_SIZE, shuffle=True, drop_last=True, num_workers=2)
    train_loader2 = paddle.batch(paddle.dataset.mnist.train(), batch_size=10)
    for epoch in range(epoch_num):
        for batch_id, data in enumerate(train_loader()):
            x_data = np.array([item[0] for item in data], dtype='float32').reshape(-1, 1, 28, 28)
            y_data = np.array([item[1] for item in data], dtype='int64').reshape(-1, 1)
            img = paddle.to_tensor(x_data)
            label = paddle.to_tensor(y_data)
            logits = model(img)
            loss = F.softmax_with_cross_entropy(logits, label)
            avg_loss = paddle.mean(loss)

            if batch_id % 1000 == 0:
                print("epoch: {}, batch_id: {}, loss is: {}".format(epoch, batch_id, avg_loss.numpy()))
            avg_loss.backward()
            opt.step()
            opt.clear_grad()

        model.eval()
        accuracies = []
        losses = []

        model.train()


    paddle.save(model.state_dict(), 'animals.pdparams')


# 创建模型
model = LeNet(num_classes=10)
# 启动训练过程
train(model)
这是报的错误：
[<paddle.nn.layer.conv.Conv2D object at 0x7fb2d1729900>, <paddle.nn.layer.pooling.MaxPool2D object at 0x7fb20b5dbc20>, <paddle.nn.layer.conv.Conv2D object at 0x7fb20b5dbea0>, <paddle.nn.layer.pooling.MaxPool2D object at 0x7fb20b5dbef0>, <paddle.nn.layer.conv.Conv2D object at 0x7fb20b5ed040>, <paddle.nn.layer.common.Linear object at 0x7fb20b5ed090>, <paddle.nn.layer.common.Linear object at 0x7fb20b5ed220>]
conv2d_0 [3, 6, 24, 24] [6, 1, 5, 5] [6]
max_pool2d_0 [3, 6, 12, 12]
conv2d_1 [3, 16, 8, 8] [16, 6, 5, 5] [16]
max_pool2d_1 [3, 16, 4, 4]
conv2d_2 [3, 120, 1, 1] [120, 16, 4, 4] [120]
linear_0 [3, 64] [120, 64] [64]
linear_1 [3, 10] [64, 10] [10]
start training ... 
ERROR:root:DataLoader reader thread raised an exception!
/usr/lib/python3/dist-packages/apport/report.py:13: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import fnmatch, glob, traceback, errno, sys, atexit, locale, imp, stat
Traceback (most recent call last):
  File "/home/jim/paddlepaddle/img_classfication2.py", line 152, in <module>
    train(model)
  File "/home/jim/paddlepaddle/img_classfication2.py", line 120, in train
    for batch_id, data in enumerate(train_loader()):
  File "/home/jim/.local/lib/python3.8/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 788, in __next__
    data = self._reader.read_next_var_list()
SystemError: (Fatal) Blocking queue is killed because the data reader raises an exception.
  [Hint: Expected killed_ != true, but received killed_:1 == true:1.] (at /paddle/paddle/fluid/operators/reader/blocking_queue.h:158)


Process finished with exit code 1
谢谢！

**Comment by LielinJiang** [comment]
可以通过如下方式划分
```
class Animals_dataset(Dataset):
def init(self, num_samples,is_train):
    self.img_files = list(paths.list_images('./animals'))
    self.num_samples = len(self.img_files)
    self.is_train = is_train
    if is_train:
         self.img_files = self.img_files[0:100]
    else:
         self.img_files = self.img_files[100:120]

def __getitem__(self, idx):
    image = cv2.imread(self.img_files[idx])
    label = self.img_files[idx].split('/')[-2]
    return image, label

def __len__(self):
```

**Comment by JimXu1989** [comment]
> 可以通过如下方式划分
> 
> ```
> class Animals_dataset(Dataset):
> def init(self, num_samples,is_train):
>     self.img_files = list(paths.list_images('./animals'))
>     self.num_samples = len(self.img_files)
>     self.is_train = is_train
>     if is_train:
>          self.img_files = self.img_files[0:100]
>     else:
>          self.img_files = self.img_files[100:120]
> 
> def __getitem__(self, idx):
>     image = cv2.imread(self.img_files[idx])
>     label = self.img_files[idx].split('/')[-2]
>     return image, label
> 
> def __len__(self):
> ```

请问is_train是什么呀？这段代码的意思是那些图片作为训练集那些作为测试集呀？如果我想 20%的图片作为测试集其余作为训练集我应该怎么写呀？而且我想打乱图片的顺序，毕竟如果找最后20%作为训练集的话很有可能都是同一类别的。

**Comment by LielinJiang** [comment]
1. is_train表示你定义的是训练集，还是测试集，一个bool变量。
2. 打算顺序可以使用np.random.shuffle
3. 你可以更加实际的图片数量来找到20%是多少。比如图片100张，那百分20就是20张。那划分方法及时img_files = image_file[:80]这个是训练，测试时img_files=img_files[80:]
