### ISSUE TITLE
构建了Model实例后，怎么查看其指定的“损失函数、优化算法、评估指标”？

### ISSUE THREAD

**Issue by A-Pai** [PaddlePaddle/Paddle#31293]
https://www.paddlepaddle.org.cn/documentation/docs/zh/guides/01_paddle2.0_introduction/upgrade_guide_cn.html
“Net是指继承paddle.nn.Layer的网络结构；而Model是指持有一个Net对象，同时指定损失函数、优化算法、评估指标的可训练、评估、预测的实例”
那么，构建了Model实例后，怎么查看其指定的“损失函数、优化算法、评估指标”？model.summary只能看到net的结构信息
![image](https://user-images.githubusercontent.com/5112397/109417604-5420f700-79ff-11eb-9230-c6a01431a62d.png)

**Comment by willthefrog** [comment]
损失函数、优化算法、评估指标通过`model.prepare`设置， 参考[这里](https://github.com/PaddlePaddle/hapi/blob/master/handwritten_number_recognition/mnist.py#L45)

**Comment by A-Pai** [comment]
> 损失函数、优化算法、评估指标通过`model.prepare`设置， 参考[这里](https://github.com/PaddlePaddle/hapi/blob/master/handwritten_number_recognition/mnist.py#L45)

不是去设置，而是已经有了model后，总览性地了解model

**Comment by willthefrog** [comment]
可以使用`model._loss`， `model._optimizer` ，`model._metrics`访问

**Comment by A-Pai** [comment]
> 可以使用`model._loss`， `model._optimizer` ，`model._metrics`访问

有没有试过？
![QQ截图20210301105720](https://user-images.githubusercontent.com/5112397/109446726-2a0e1a00-7a7d-11eb-8d69-97654068ef67.jpg)
summary可以正常运行，下边的“print(model._loss)”报错：
![QQ截图20210301105751](https://user-images.githubusercontent.com/5112397/109446796-4f9b2380-7a7d-11eb-82e5-ffd9db2efa65.jpg)

**Comment by A-Pai** [comment]
> 可以使用`model._loss`， `model._optimizer` ，`model._metrics`访问

我的想法是可以对“model.summary”进行改造，既然是summary，就要包含各个方面，而不仅仅是网络的结构

**Comment by willthefrog** [comment]
这些属性需要运行过`model.prepare`后才存在。

**Comment by A-Pai** [comment]
明白了，谢谢
