### ISSUE TITLE
官方文档中v100赠送时间的问题

### ISSUE THREAD

**Issue by jhcgt4869** [PaddlePaddle/Paddle#31290]
![image](https://user-images.githubusercontent.com/61859193/109413868-9855cc80-79ea-11eb-98f4-15d344346b24.png)

https://github.com/PaddlePaddle/Paddle/blob/develop/README_cn.md

v100赠送时间早就修改成10小时了【瑟瑟发抖】

**Comment by willthefrog** [comment]
好的，会反馈相关同学更新文档

**Comment by TCChenlong** [comment]
已更新 感谢反馈
