### ISSUE TITLE
DoubleBuffer::asyncLoader_ 未初始化

### ISSUE THREAD

**Issue by lernanto** [PaddlePaddle/Paddle#313]
DoubleBuffer::asyncLoader_ 成员变量由函数 DoubleBuffer::startAsyncLoad() (DataProvider.cpp:149) 赋初值。但在析构函数 DoubleBuffer::~DoubleBuffer() 中会调用 DoubleBuffer::finishAsyncLoad()，该函数又调用 DoubleBuffer::asyncLoader_->join() (DataProvider.h:273)。由于 DoubleBuffer::asyncLoader_ 不是随 DoubleBuffer 的构造函数初始化，析构时可能存在该成员变量未初始化的情况，此时会引发段错误。

该问题可能在 paddle test 时触发。具体地，在 Trainer::init() (Trainer.cpp:197) 通过 DataProvider::create() 创建了 DataProvider 对象，该对象的构造函数会创建 DoubleBuffer 对象。但后续并没有调用 DoubleBuffer::startAsyncLoad() 初始化。当程序结束时，连串析构函数最终会调用 DoubleBuffer::~DoubleBuffer()，从而调用 DoubleBuffer::finishAsyncLoad() 结束不存在的线程，导致崩溃。

paddle train 因为会调用 DataProvider::reset() (Trainer.cpp:273) 初始化 DoubleBuffer::asyncLoader_，因此没有这个问题。

**Comment by reyoung** [comment]
Related PR #291 

这个析构错误目前如果使用`PyDataProvider2`应该不会出现，原理的话test也会在某些时候调用reset。

不清楚 @lernanto 您使用的是什么Provider。

同时，这块code也足够恶心了，正在考虑完全重构掉。直接使用装饰者模式，写一个 BufferedDataProvider比较好。

@lernanto 有兴趣一起搞一下么？

**Comment by lernanto** [comment]
我是在试用的时候遇到这个崩溃才稍稍 debug 了一下代码，发现这个问题。用的是 paddle.trainer.PyDataProvider2，gdb 显示确实存在未初始化的 asyncLoader_，不清楚问题出在哪里。

重构的话，我接触才不久，代码很不熟悉。而且当前确实也没有精力。

**Comment by qingqing01** [comment]
close via #https://github.com/PaddlePaddle/Paddle/pull/291
