### ISSUE TITLE
怎样才能提升gpu的利用率？

### ISSUE THREAD

**Issue by A-Pai** [PaddlePaddle/Paddle#31311]
gpu资源是非常宝贵的，要尽量充分利用，怎样才能提升gpu的利用率？以以下项目为例，当前的利用率如图，怎么设置提升？
https://aistudio.baidu.com/aistudio/projectdetail/1592130
![QQ截图20210301144030](https://user-images.githubusercontent.com/5112397/109460812-2ccc3780-7a9c-11eb-9682-6a4ee6d533c5.jpg)

**Comment by A-Pai** [comment]
将batch_size改为200(原来为128）后，显存利用率显著提升，gpu利用率还有所下降，但是每epoch的时间下降为250s，原来为360s


![QQ截图20210301155646](https://user-images.githubusercontent.com/5112397/109467879-cac4ff80-7aa6-11eb-8b2c-f92ed768e815.jpg)

**Comment by A-Pai** [comment]
似乎再没有别的地方可调

**Comment by A-Pai** [comment]
batch_size改为50，每epoch的时间和batch_size为128的，同为360s，但是基本上不占用gpu和显存了，这又是何故？

![image](https://user-images.githubusercontent.com/5112397/109474798-d668f400-7aaf-11eb-916e-53fb556eab30.png)

**Comment by A-Pai** [comment]
看样子batch_size为200是最优的，再高就Out of memory了----AI Studio的高级版

**Comment by A-Pai** [comment]
题外--与AI studio基本版（cpu）比较：
batch_size为50(再高就溢出了)，每epoch的时间为36000s，耗时是高级版batch_size为200的144倍，资源占用情况为：

![image](https://user-images.githubusercontent.com/5112397/109483943-c99dcd80-7aba-11eb-9f0d-56795ea029b7.png)

**Comment by A-Pai** [comment]
高级版一方面内存大，另一方面有gpu，效率大大提升

**Comment by LielinJiang** [comment]
总体上的策略是通过优化reader，减少数据读取的时间。来提高gpu利用率。

**Comment by A-Pai** [comment]
> 总体上的策略是通过优化reader，减少数据读取的时间。来提高gpu利用率。

这个项目没有用到reader？
可否请你试着改写一些？做个项目，大家学习、模仿

**Comment by LielinJiang** [comment]
paddle.vision.datasets.Cifar100 这个是项目用到的dataset，在高层API中你可以简单的通过传入num_works的数量来看看能否加速。或者通过dataset+sampler+dataloader的方式，来自定义dataloader（reader）。至于示例，分类任务可以参考PaddleClas，检测可以参考PaddleDetection，分割可以参考PaddleSeg

**Comment by gaorui999** [comment]
> 将batch_size改为200(原来为128）后，显存利用率显著提升，gpu利用率还有所下降，但是每epoch的时间下降为250s，原来为360s
> 
> ![QQ截图20210301155646](https://user-images.githubusercontent.com/5112397/109467879-cac4ff80-7aa6-11eb-8b2c-f92ed768e815.jpg)

有时候环境就是这么奇怪，我今天开启训练后直接停在训练第一行不动了
