### ISSUE TITLE
有没有返回混淆矩阵(confusion matrix)的函数？

### ISSUE THREAD

**Issue by A-Pai** [PaddlePaddle/Paddle#31314]
分类学习结束后，观察其混淆矩阵(confusion matrix)是重要的，可以知道各个类别的分类准确率
飞桨2.0有没有返回混淆矩阵(confusion matrix)的函数？

**Comment by LielinJiang** [comment]
暂时没有

**Comment by A-Pai** [comment]
> 暂时没有

有必要有吗？

**Comment by LielinJiang** [comment]
我们评估一下。这个代码也比较好写。你可以找一找已有的实现，参考一下

**Comment by gaorui999** [comment]
> 我们评估一下。这个代码也比较好写。你可以找一找已有的实现，参考一下

我也很需要这个代码，如果有这个接口的话分析会方便很多
