### ISSUE TITLE
normalize的均值和标准差怎么确定？

### ISSUE THREAD

**Issue by A-Pai** [PaddlePaddle/Paddle#31349]
normalize的均值和标准差怎么确定？比如以下文档是怎么确定出来的？
https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/vision/transforms/functional/normalize_cn.html

![QQ截图20210302090519](https://user-images.githubusercontent.com/5112397/109580974-82edb900-7b36-11eb-98ab-9ca4c3cbacba.jpg)

**Comment by zhiqiu** [comment]
这个均值和标准差应该是根据模型数据特点设置的，我感觉图中的127.5应该是255/2吧，int8最大是255.

**Comment by A-Pai** [comment]
> 这个均值和标准差应该是根据模型数据特点设置的，我感觉图中的127.5应该是255/2吧，int8最大是255.

--不要“感觉”啊！开发团队是权威

**Comment by starsblinking** [comment]
路过说一句，示例应该有问题。0-255的连续值均匀分布的均值为 255/2 标准差为 255/sqrt(12)；case中的数据是离散均匀分布，均值相同，标准差相似，可以自己算一下。

**Comment by A-Pai** [comment]
> 路过说一句，示例应该有问题。0-255的连续值均匀分布的均值为 255/2 标准差为 255/sqrt(12)；case中的数据是离散均匀分布，均值相同，标准差相似，可以自己算一下。

均匀分布，上边是正解

**Comment by WenmuZhou** [comment]
不是什么均匀分布，就是255/2,并且这只是个示例，具体还需要根据自己的数据集来做修改
