### ISSUE TITLE
多卡训练报错

### ISSUE THREAD

**Issue by qdd1234** [PaddlePaddle/Paddle#31340]
您好，我是用paddle2.0进行多卡并行训练报如下的错误
![image](https://user-images.githubusercontent.com/68497831/109490348-108fc100-7ac3-11eb-852c-9b04b5b527e2.png)
我想问一下这是什么原因
CUDA:11.0 cuDNN:8.1
显卡:Tesla T4 显存15GB 一共四张卡

**Comment by LielinJiang** [comment]
看提示，像是创建好的网络中有参数，没有被用到导致的。可以看看哪些layer没有回传loss，将这些layer中的参数，设置.stop_gradient=True
