### ISSUE TITLE
paddle2.0 api文档问题，paddle.nn.Upsample 示例程序参数不对

### ISSUE THREAD

**Issue by spockmars** [PaddlePaddle/Paddle#31355]
#### 示例程序参数写错了，本来应该为size，文档中写的是out_shape，如下所示：
import paddle
import numpy as np

upsample_op = paddle.nn.Upsample(out_shape=[12,12])
input_data = paddle.rand(shape=(2,3,6,10))

output = upsample_op(input_data)
print(output.shape)
# [2L, 3L, 12L, 12L]

**Comment by tink2123** [comment]
感谢反馈，示例代码有误，我们会尽快修复。
