### ISSUE TITLE
如何自定义数据集，文档中讲的不清楚

### ISSUE THREAD

**Issue by A-Pai** [PaddlePaddle/Paddle#31354]
https://www.paddlepaddle.org.cn/documentation/docs/zh/guides/02_paddle2.0_develop/02_data_load_cn.html

如何自定义数据集，文档中讲的不清楚

比如自己采集了若干类别的图像，想基于这些数据做分类识别，应该怎样打包这些数据（相同类别的图像放在同一文件夹），然后怎么定义

**Comment by TCChenlong** [comment]
这篇文档中给出的是最基本的定义方式，在第二部分 【二、自定义数据集】中有讲到，即如何设置每一条数据 的data与 label；针对从文件夹中读取图片，因为每种场景不一样，所以可以参考官网[应用实践](https://www.paddlepaddle.org.cn/documentation/docs/zh/tutorial/index_cn.html)的部分，里面会有类似场景的数据加载的说明~
然后，我们近期也计划更新这篇文档，补充更多的场景说明，感谢您的反馈

**Comment by TCChenlong** [comment]
AI Studio上有一篇官方提供的数据处理文档，链接见[详解飞桨框架数据管道](https://aistudio.baidu.com/aistudio/projectdetail/1299687)，也可以作为参考哈~

**Comment by A-Pai** [comment]
> AI Studio上有一篇官方提供的数据处理文档，链接见[详解飞桨框架数据管道](https://aistudio.baidu.com/aistudio/projectdetail/1299687)，也可以作为参考哈~

这个项目较为详细，但是使用的是打包数据
![QQ截图20210302224729](https://user-images.githubusercontent.com/5112397/109736301-0ffc4500-7bff-11eb-8ddf-3cf04c8cf4d9.jpg)
这是什么格式的数据？
该项目是直接使用的这种打包数据，而自己的原始数据是一张张图片，还需要处理成这种格式？不能直接定义？

**Comment by TCChenlong** [comment]
那是 ubyte的格式； 不需要将原始的图片转为这种格式，只需要将各种格式的数据，在Dataset中，转为 numpy格式即可；具体一点，如果是图片数据，可以参考这一篇案例中关于Dataset的定义，链接为 [3.4 数据集类定义](https://www.paddlepaddle.org.cn/documentation/docs/zh/tutorial/cv_case/image_segmentation/image_segmentation.html#shujujileidingyi)

**Comment by A-Pai** [comment]
> 那是 ubyte的格式； 不需要将原始的图片转为这种格式，只需要将各种格式的数据，在Dataset中，转为 numpy格式即可；具体一点，如果是图片数据，可以参考这一篇案例中关于Dataset的定义，链接为 [3.4 数据集类定义](https://www.paddlepaddle.org.cn/documentation/docs/zh/tutorial/cv_case/image_segmentation/image_segmentation.html#shujujileidingyi)
上边的处理方式还是比较抽象
项目https://www.paddlepaddle.org.cn/tutorials/projectdetail/1516124
中的“LeNet在眼疾识别数据集iChallenge-PM上的应用”使用的是原始图像，但其只适合于类别少的情形--在文件名上区分类别
有没有这样的处理方式：不同类别的图片放在不同的文件夹---我似乎在哪里见到过

**Comment by TCChenlong** [comment]
应该是 [DatasetFolder](https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/vision/datasets/folder/DatasetFolder_cn.html) 这个API，可以这样读取
