### ISSUE TITLE
paddle.summary源码 计算前向反向传播参数量错误！！！

### ISSUE THREAD

**Issue by qxcnwu** [PaddlePaddle/Paddle#31350]
- 版本、环境信息
1）PaddlePaddle版本：paddle 2.0
2）CPU/GPU：__all__
3）系统环境：__all__
- paddle.summary函数
在model_summary.py  line 343~349中
![image](https://user-images.githubusercontent.com/55339411/109586391-18da1180-7b40-11eb-86f8-5c3dd56a2ad8.png)
在计算输出为list或者是多维输出时 没有在np.prod()函数中加入axis=1 导致计算数值超过np上限计算成为负数
因该改为
![image](https://user-images.githubusercontent.com/55339411/109587117-7c187380-7b41-11eb-95ad-67236066c365.png)
这样计算结果正确

**Comment by LielinJiang** [comment]
请问可以提供个例子嘛？我们复现一下。

**Comment by qxcnwu** [comment]
您 from paddleseg import HRNET

**Comment by qxcnwu** [comment]
获取模型后用paddle.summary打印一下

**Comment by qxcnwu** [comment]
![Inked屏幕截图 2021-02-27 221109_LI](https://user-images.githubusercontent.com/55339411/109764069-ff16f800-7c2d-11eb-8788-602259523aa6.jpg)
![Inked屏幕截图 2021-02-27 221033_LI](https://user-images.githubusercontent.com/55339411/109764078-0211e880-7c2e-11eb-9e49-25a0de1beab7.jpg)
