### ISSUE TITLE
使用教程>模型开发>训练与预测 中对model.fit()函数的拆解与model.evaluate()函数拆解疑问

### ISSUE THREAD

**Issue by qxcnwu** [PaddlePaddle/Paddle#31353]
paddle 2.0文档
### 文档问题描述：
model.fit()函数的拆解与model.evaluate()函数拆解疑问
model.fit()中包含traindata，evaluatedata参数说明在model.fit()函数拆解中应该包含 训练/预测 两个步骤而下方拆解文档只有训练应该为
![image](https://user-images.githubusercontent.com/55339411/109588569-eb8f6280-7b43-11eb-8d81-ac8bf19d8fb4.png)

**Comment by zhiqiu** [comment]
model.fit()中如果传eval_data会执行evalute，如果不传，则不会。图中的“拆解”，应该针对的是不传eval_data的情况。
