### ISSUE TITLE
觉得数据增强(Data augmentation)应该具有扩充数据的功能

### ISSUE THREAD

**Issue by A-Pai** [PaddlePaddle/Paddle#31351]
觉得数据增强(Data augmentation)应该具有扩充数据的功能--在原式图像的基础上，模拟以不同的角度，不同的光照、采集工具获取该物体的照片，一可以变出十，或者更多
现在的(2.0)似乎没有这样的功能

**Comment by LielinJiang** [comment]
不同的角度可以试试rotate，光照等可以试试ColorJitter。还有一些定制化的数据增广也可以看看是否可以通过paddle.vision.transforms.functional下面的函数来组合

**Comment by A-Pai** [comment]
> 不同的角度可以试试rotate，光照等可以试试ColorJitter。还有一些定制化的数据增广也可以看看是否可以通过paddle.vision.transforms.functional下面的函数来组合

没懂我的意思？我的意思是用不同的方式扩充数据(1-->N)，而当前是加工数据(1-->1)

**Comment by LielinJiang** [comment]
你可以通过Compose将你想要的变换组合在一起。或者写一个随机调用的方法，随机调用其中几个函数，同时这些函数又具有随机性（角度，大小等），调用N次，就能达到1->N的效果

**Comment by A-Pai** [comment]
我的想法是这个扩充数据的需求应该在图像识别中是共同的，不是吗？同样一个物体，从不同的方式去看，也要能够准确地识别出
我认为框架中应该包含这样融合处理的自动工具，而不是用户手工来组合

看了不少项目，似乎都是1-->1地在处理，为何不1-->N地处理？不需要这样做？
