### ISSUE TITLE
内置数据集可视化

### ISSUE THREAD

**Issue by A-Pai** [PaddlePaddle/Paddle#31380]
如项目
https://aistudio.baidu.com/aistudio/projectdetail/1601610?forkThirdPart=1
![QQ截图20210302210421](https://user-images.githubusercontent.com/5112397/109652577-ed384500-7b9a-11eb-9236-17ff69721e54.jpg)
需要提前知道数据的size，通过什么方法知道应该reshape成什么样的？
有没有别的好办法，直接展示？

**Comment by zhiqiu** [comment]
h，这个链接好像无法访问。数据的size一般是已知的吧，通常数据集的提供者会告诉数据的大小和组织形式。

**Comment by A-Pai** [comment]
> h，这个链接好像无法访问。数据的size一般是已知的吧，通常数据集的提供者会告诉数据的大小和组织形式。

就是这个https://aistudio.baidu.com/aistudio/projectdetail/1299687

**Comment by A-Pai** [comment]
项目https://aistudio.baidu.com/aistudio/projectdetail/1562200?channelType=0&channel=0
中的可视化做法就很直接，不像上边绕了一个弯：
![QQ截图20210303114239](https://user-images.githubusercontent.com/5112397/109749446-a176b180-7c15-11eb-86c6-29ec3e89dc7b.jpg)

**Comment by saxon-zh** [comment]
@A-Pai 这个reshape操作可以去掉，之前增加这个操作是因为2.0正式版之前有一个版本的数据返回格式不是(28, 28)，后面我们修改下这个项目的代码。
