### ISSUE TITLE
spawn多卡训练使用VisualDL生成一大堆log文件

### ISSUE THREAD

**Issue by yeyupiaoling** [PaddlePaddle/Paddle#31383]
- PaddlePaddle
 - VisualDL 2.1.1

spawn多卡训练，VisualDL会不断生成log文件，这是咋回事？

```
            if batch_id % 100 == 0 and dist.get_rank() == 0:
                print('[%s] Train epoch %d, batch %d, loss: %f' % (datetime.now(), epoch, batch_id, loss))
                writer.add_scalar('Train loss', loss, train_step)
                train_step += 1
```
具体代码在：https://github.com/yeyupiaoling/PPASR/blob/master/train.py

**Comment by zhiqiu** [comment]
hi，log文件能看下吗

**Comment by yeyupiaoling** [comment]
@zhiqiu 在这里，里面包含了很多文件

[log.zip](https://github.com/PaddlePaddle/Paddle/files/6073907/log.zip)

**Comment by yeyupiaoling** [comment]
@zhiqiu 请问怎么解决呢？

**Comment by ShenYuhan** [comment]
确保https://github.com/yeyupiaoling/PPASR/blob/8273925f8c50ea05233cf8d96013871cc6c243e4/train.py#L33
这一句在每个任务中只执行了一次，每次执行这一句都会新生成一个文件

**Comment by yeyupiaoling** [comment]
@ShenYuhan 是只有一行呐，你看我都放在train()外面了

**Comment by ShenYuhan** [comment]
试下加下print看下是不是只执行一次，另外在add_scalar的时候要看下writer 的id是不是一个

**Comment by yeyupiaoling** [comment]
@ShenYuhan 这行的确是执行多次了：https://github.com/yeyupiaoling/PPASR/blob/02f88a9b5002bfe8b120a0c29305ed9273d62cd5/train.py#L35
spawn多卡训练的逻辑是啥，你看我都放在train()外面了，怎么还会执行多次呢？

**Comment by yeyupiaoling** [comment]
只能这样做了。https://github.com/yeyupiaoling/PPASR/blob/94f1e7a8c877d37019889a2f798f7b7c0fad192c/train.py#L55-L57
