### ISSUE TITLE
安装paddlepaddle-gpu2.0.0之后，导入paddle报‘No module named 'paddle.fluid.core_noavx’错误

### ISSUE THREAD

**Issue by Fighter-zzp** [PaddlePaddle/Paddle#31387]
安装paddlepaddle-gpu2.0.0之后，导入paddle报‘No module named 'paddle.fluid.core_noavx’错误，
通过 python -m pip install paddlepaddle-gpu==2.0.0 -f https://paddlepaddle.org.cn/whl/stable/noavx.html安装的模块，电脑不支持avx指令

建立issue时，为快速解决问题，请您根据使用情况给出如下信息：
- 版本、环境信息：
    1）PaddlePaddle版本：paddlepaddle-gpu==2.0.0
    2）CPU：G4600
    3）GPU：GTX 1060  cuDNN Version: 7.6、 CUDA Version: 10.0
    4）系统环境：win10、Python3.8.8
注：您可以通过执行[summary_env.py](https://github.com/PaddlePaddle/Paddle/blob/develop/tools/summary_env.py)获取以上信息。
- 安装方式信息：
1）pip安装安装

**Comment by zhwesky2010** [comment]
@Fighter-zzp 您好，这个是由于电脑不支持avx指令集问题导致的，目前暂时只发布了python2.7的no_avx包发布，目前的解决方式是使用python2.7，然后 python -m pip install paddlepaddle-gpu==2.0.0 -f https://paddlepaddle.org.cn/whl/stable/noavx.html

 @swtkiwi 下个版本会增加no avx类型机器更主流的python版本支持

**Comment by swtkiwi** [comment]
目前2.0.1也支持py38的noavx了，可以使用python3 -m pip install paddlepaddle-gpu==2.0.1 -f https://paddlepaddle.org.cn/whl/stable/noavx.html 安装

**Comment by LeoMax-Xiong** [comment]
python3.8 的 no avx 版本只支持 windows, 什么时候能支持 centos 等 linux 平台。
唉。
