### ISSUE TITLE
paddle多卡训练时配置cudnn的路径问题

### ISSUE THREAD

**Issue by wdhxek** [PaddlePaddle/Paddle#31398]
paddle-gpu=2.0.0
cudatoolkit=11.0
采用多卡训练时候，发现paddle好像永远是从系统的/usr/local/cuda这个目录下读取cudnn的信息，由于修改这个目录一般需要管理员权限，因此Paddle是否可以自定义cudatoolkit的根目录或者自定义cudnn的目录？是否有对应的环境变量或者接口设置对应的目录？

**Comment by GaoWei8** [comment]
暂时没有支持自定义cudnn的目录，可以尝试修改安装目录

**Comment by wdhxek** [comment]
谢谢回复！
我大概查了一下代码，里面 
[代码](https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/fluid/platform/dynload/dynamic_loader.cc)

这里好像提到了修改$LD_LIBRARY_PATH 可以进行配置？

**Comment by GaoWei8** [comment]
可以尝试修改环境变量的方式，修改路径。

**Comment by wdhxek** [comment]
在个人用户下的.bashrc中修改LD_LIBRARY_PATH,  但是不起作用，确定修改在系统中是生效的。但是paddle检测到的始终是/usr/local/cuda这个目录下所安装的cudnn版本。
paddle现在是否支持cudatoolkit+cudnn一起打包安装的方式？

还有一个问题，nccl的库目录是否可以用LD_LIBRARY_PATH单独设置呢？

**Comment by GaoWei8** [comment]
支持直接打包安装，或者直接使用docker配置好的环境

**Comment by duohappy** [comment]
这个问题太让人困扰了，居然不支持 `LD_LIBRARY_PATH`, 😞
