### ISSUE TITLE
PySequence_Check(seq_) 检测失败问题

### ISSUE THREAD

**Issue by Damon-wyg** [PaddlePaddle/Paddle#3139]
Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
F0801 17:12:41.648218 24026 PythonUtil.h:197] Check failed: PySequence_Check(seq_) 
被这个PySequence_Check困扰很久了，问题情况是，**完全一样的配置在本地跑没有任何问题**，但是放到mpi集群跑，有时候就会挂，报检测失败的问题。
最头痛的是，这并不是每次都可以复现，像是**随机**的。
我的数据输出格式是一个字典：比如{‘input1‘:[]，’input2’:[], 'label':0} (其中label是integer，所以不是sequence)
另外一个情况是，在使用dropout或l1/l2正则系数的时候，这种问题出现就更频繁了
查看代码和之前的issue，也并没有得到实质性的解决，请帮忙解释这个检测的原理，及出现随机现象的原因，谢谢

ps：在集群上paddle因为这种原因挂了的任务，也不会自己kill，而且还占用资源，这个是不是也可以优化下

**Comment by reyoung** [comment]
应该还是某几条数据错误。

可以配置
```python
@provider(
    check=True,
    check_fail_continue=True,
)
....
```

可以参考单测:
 https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/gserver/tests/test_PyDataProvider2.py#L102

**Comment by Damon-wyg** [comment]
那这个检测的原理是什么呢？是会从训练数据里随机抽一些样本下来check，还是说mock了一些数据来跑data_provider，然后对data_provider的结果做检测？

**Comment by Damon-wyg** [comment]
前面提到的方法在v1下会报错。。
F0801 19:12:05.298818 13010 PyDataProvider2.cpp:265] Check failed: (instance_) != nullptr Current PYTHONPATH: ['/home/disk1/normandy/maybach/41450/workspace', '/home/disk1/normandy/maybach/41450/workspace/python27-gcc482/lib/python2.7/site-packages/setuptools-18.2-py2.7.egg', '/home/disk1/normandy/maybach/41450/workspace/paddle', '/home/disk1/normandy/maybach/41450/workspace', '/home/disk1/normandy/maybach/41450/workspace/thirdparty/thirdparty', '/home/disk1/normandy/maybach/41450/workspace/python27-gcc482/lib/python27.zip', '/home/disk1/normandy/maybach/41450/workspace/python27-gcc482/lib/python2.7', '/home/disk1/normandy/maybach/41450/workspace/python27-gcc482/lib/python2.7/plat-linux2', '/home/disk1/normandy/maybach/41450/workspace/python27-gcc482/lib/python2.7/lib-tk', '/home/disk1/normandy/maybach/41450/workspace/python27-gcc482/lib/python2.7/lib-old', '/home/disk1/normandy/maybach/41450/workspace/python27-gcc482/lib/python2.7/lib-dynload', '/home/disk1/normandy/maybach/41450/workspace/python27-gcc482/lib/python2.7/site-packages']
Python Error: <type 'exceptions.AttributeError'> : 'DataProvider' object has no attribute 'slots'
Python Callstack: 
            /home/disk1/normandy/maybach/41450/workspace/python27-gcc482/lib/python2.7/site-packages/paddle/trainer/PyDataProvider2.py : 460
Cannot Create instance

**Comment by reyoung** [comment]
`PySequence_Check(seq_)`报错是因为Paddle读入数据的时候，用户给的数据类型和Paddle期待的数据类型不匹配。即您给Paddle的数据中应该有几项是非法的数据。

如果不想查出来哪几项数据是错的，可以使用如上配置将错误数据跳过。

**Comment by lcy-seso** [comment]
I close this issue due to inactivity. please feel free to reopen it if more information is available.
