### ISSUE TITLE
paddle.nn.LSTM中参数time_major不起作用

### ISSUE THREAD

**Issue by fiyen** [PaddlePaddle/Paddle#31392]
如题，time_major=True或者False,返回的output的shape都是[batch_size, time_steps, hidden_size]

`input = paddle.tensor.full((10, 100, 128), 1.0, 'float32')
lstm = LSTM(128, 256, time_major=True)
out, final_s = lstm(input)
out.shape
Out[12]: [10, 100, 256]`

**Comment by iclementine** [comment]
time_major 参数会影响输出的形状的语义，输出和输入语义保持一致。
如果你的输入是 (B, T, C), 那么应该设置 time_major=False, 输出也是 (B, T, C).
如果你的输入是 (T, B, C), 那么应该设置 time_major=True, 输出也是 (T, B, C).

模型并不真正知道什么是 batch_size, 什么是 time_steps, 它只是根据协议来决定把那个当作 batch_size, 哪个当作 time_steps.
因为你的输入就是 (10, 100, 128), 设置 time_major=True 的情况下，它会认为 batch_size 是 100, time_steps 是 10.

**Comment by fiyen** [comment]
理解了，多谢！
