### ISSUE TITLE
paddle 2.0 动态图模型保存、加载不正常

### ISSUE THREAD

**Issue by AoZhang** [PaddlePaddle/Paddle#31397]
- 版本、环境信息：
    1）PaddlePaddle版本：paddle 2.0 
    2）CPU：-
    3）GPU：v100，cuda 10.0
    4）系统环境：CentOS 7.5，Python 3.7.9

- 问题描述：
训练阶段调用 paddle.save(model.state_dict(), path) 保存模型后，在预测或训练热启时调用 model.set_dict(paddle.load(path)) 加载保存的模型，发现预测结果或训练loss 跟保存前存在较大差异。
怀疑是模型的部分参数在 save 阶段未能正常保存，但不知道如何排除，求助！

**Comment by phlrain** [comment]
一个简单的方式就是遍历model.state_dict() ，打印name  和 对应的参数， 然后load之后 在输出一下，看看值是不是能对上。。

**Comment by AoZhang** [comment]
> 一个简单的方式就是遍历model.state_dict() ，打印name 和 对应的参数， 然后load之后 在输出一下，看看值是不是能对上。。

是否可能存在个别参数在save的时候根本没保存？

**Comment by phlrain** [comment]
> > 一个简单的方式就是遍历model.state_dict() ，打印name 和 对应的参数， 然后load之后 在输出一下，看看值是不是能对上。。
> 
> 是否可能存在个别参数在save的时候根本没保存？

paddle.save(model.state_dict(), path) 这种方式是不会的。。 即使存在，刚才建议的方式，也是能够排除出来的

**Comment by AoZhang** [comment]
> 一个简单的方式就是遍历model.state_dict() ，打印name 和 对应的参数， 然后load之后 在输出一下，看看值是不是能对上。。

已经验证了save之前的state_dict 和load 之后的state_dict是完全一致的。还有其它思路排查是哪里的问题吗？

**Comment by AoZhang** [comment]
找到原因了：是 save 的时候部分参数没有保存下来。

原因是我定义模型时使用了类似这样的方法：
```
class MyModel(nn.Layer):
    def __init__(self):
        self.op_dict = {"op1":  som paddle op,
                           "op2": some paddle op}
```
导致了 op_dict 中的参数没有被 save() 函数识别并保存。

--------
建议：类似的写法在 PyTorch 中是可以正常使用的，希望 Paddle 也能支持。
