### ISSUE TITLE
Tensor 索引？

### ISSUE THREAD

**Issue by huochf** [PaddlePaddle/Paddle#31416]
请问Paddle中Tensor不支持列表索引或者bool数组索引吗？有相关可替代的API吗？

**Comment by GaoWei8** [comment]
可以尝试mask_select，index_select这两个api是否满足要求

**Comment by huochf** [comment]
> 可以尝试mask_select，index_select这两个api是否满足要求

谢谢回复，似乎有些地方不可以，

我把Tensor的操作全部转成numpy数组，然后再转回Tensor，似乎可以解决了这个问题
