### ISSUE TITLE
在训练过程中数据类型int64_t没有

### ISSUE THREAD

**Issue by ddgetget** [PaddlePaddle/Paddle#31413]
PaddlePaddle版本：paddle:2.0
   
我在跑官网的[用N-Gram模型在莎士比亚文集中训练word embedding]出现一下错误,不知道怎么回事,针对高阶API和基础API进行模型的训练均是改情况

```
ValueError: (InvalidArgument) Tensor holds the wrong type, it holds int, but desires to be int64_t.
  [Hint: Expected valid == true, but received valid:0 != true:1.] (at D:\v2.0.0\paddle\paddle/fluid/framework/tensor_impl.h:33)
  [operator < softmax_with_cross_entropy > error]
```

**Comment by GaoWei8** [comment]
初步分析是softmax_with_cross_entropy op的Tensor的类型错误，请问是使用的官方例子运行吗？有相关链接吗

**Comment by TCChenlong** [comment]
是这篇文档么：https://www.paddlepaddle.org.cn/documentation/docs/zh/tutorial/nlp_case/n_gram_model/n_gram_model.html ；请问下您的具体环境 和 报错的详细信息，方便我们排查问题

**Comment by ddgetget** [comment]
嗯嗯，是的，window10,paddle2.0 cpu，直接运行官方代码，即出现
```
ValueError: (InvalidArgument) Tensor holds the wrong type, it holds int, but desires to be int64_t.
  [Hint: Expected valid == true, but received valid:0 != true:1.] (at D:\v2.0.0\paddle\paddle/fluid/framework/tensor_impl.h:33)
  [operator < softmax_with_cross_entropy > error]
```

**Comment by TCChenlong** [comment]
可以在 [3.2 构建Dataset类 加载数据](https://www.paddlepaddle.org.cn/documentation/docs/zh/tutorial/nlp_case/n_gram_model/n_gram_model.html#dataset)这一部分的代码里，显示的加上  `lable.dtype = 'int64' ` 试一下，具体如下：


    import numpy as np
    class TrainDataset(paddle.io.Dataset):
        def __init__(self, tuple_data):
            self.tuple_data = tuple_data

        def __getitem__(self, idx):
            data = self.tuple_data[idx][0]
            label = self.tuple_data[idx][1]
            data = np.array(list(map(lambda word: word_to_idx.get(word, 0), data)))
            label = np.array(word_to_idx.get(label, 0))
            label.dtype = 'int64'
            return data, label
        
        def __len__(self):
            return len(self.tuple_data)

**Comment by ddgetget** [comment]
好的,多谢
