### ISSUE TITLE
102Flowers数据集读取数据异常缓慢

### ISSUE THREAD

**Issue by GT-ZhangAcer** [PaddlePaddle/Paddle#31423]
PaddlePaddle版本：2.0
GPU：AI Studio上的V100
系统环境：MAC、Windows、Ubuntu均可复现
 
在MacBook Pro (Retina, 13-inch, Early 2015)上测试，纯数据读取大概需要5000秒一轮，读取32条数据也需要等待将近3分钟。已经提PR优化了，但显示代码覆盖率不够...大佬方便看看么  
https://github.com/PaddlePaddle/Paddle/pull/31408

**Comment by gfwm2013** [comment]
@GT-ZhangAcer CI中显示，您添加的代码基本都没有运行，所以才会报覆盖率不够，显示的覆盖率是0

**Comment by GT-ZhangAcer** [comment]
> @GT-ZhangAcer CI中显示，您添加的代码基本都没有运行，所以才会报覆盖率不够，显示的覆盖率是0

但大部分代码是我在原基础之上调整了顺序和变量名，调整变量名这部分我看也是显示没有运行的，那么之前是怎么提交的呢？

**Comment by gfwm2013** [comment]
@GT-ZhangAcer 你可以本地先加入一些log输出，确认一下是否运行了您修改的代码。

**Comment by GT-ZhangAcer** [comment]
如果我没有运行这些代码的话，那是得不出新代码与旧代码性能差别的。而且很多代码是在__init__里的，调用这个class就会被用上，出现0就很怪异...

**Comment by gfwm2013** [comment]
@GT-ZhangAcer 有可能是覆盖率统计有问题，我可以帮你重新re-run一下，如果还是同样的问题，我去帮你问一下负责的同学，你看这样可以吗？

**Comment by GT-AcerZhang** [comment]
感谢大佬啦~[送花]

**Comment by GT-ZhangAcer** [comment]
感谢大佬啦~[送花]

**Comment by gfwm2013** [comment]
@GT-ZhangAcer 这个应该是没有跑对应的单测，可以这么再提交一个commit，然后加上test=allcase 关键字，应该就可以了

**Comment by GT-ZhangAcer** [comment]
@gfwm2013 大佬~现在昆仑的过不了了...

**Comment by gfwm2013** [comment]
@GT-ZhangAcer 这个CI不是Required，所以没过也是没有问题的，现在你可以找人帮你merge了～
