### ISSUE TITLE
训练后ctr，如何得到训练好的embedding表

### ISSUE THREAD

**Issue by pengyuange** [PaddlePaddle/Paddle#31421]
PaddlePaddle 2.0，CPU，Linux，python3.8
ctr训练，一部分cate_feature 想要做embedding，怎样得到训练好的embedding表，以及如何查询，
这样在线上部署的时候可以省去embedding的训练过程
比如说，职业，消费水平等 多个类别特征，输入模型的时候，定义一个embedding
self.embedding = paddle.nn.Embedding(
            self.sparse_feature_number,
            self.sparse_feature_dim,
            sparse=True,
            weight_attr=paddle.ParamAttr(
                name="SparseFeatFactors",
                initializer=paddle.nn.initializer.Uniform()))
label是点击

在训练后，想要得到一个embedding 的查询表
当输入类别特征时，直接得到一个向量。需要怎样做？

**Comment by seiriosPlus** [comment]
1. 使用`paddle.nn.Embedding`接口，在训练后会得到一个名为`SparseFeatFactors `（跟用户配置有关）的文件， 可以参考https://www.paddlepaddle.org.cn/documentation/docs/zh/guides/02_paddle2.0_develop/08_model_save_load_cn.html#canshuzairu 进行模型加载。
2. 可将加载后的参数通过numpy转换为numpy自行使用。
3. 关于查询：
    1. 使用`paddle.nn.Embedding`接口保存的embedding是一个（词表*维度）的一个矩阵，ID为[0, N-1)。 用户可以自行采用ID映射行的方式，获取到指定ID的embedding.
