### ISSUE TITLE
安装1.6.3版本  的paddle后无法访问fluid.core.get_cuda_device_count

### ISSUE THREAD

**Issue by topxxuki** [PaddlePaddle/Paddle#31430]
环境：ubuntu16.04
python3.6.4
参考官网文档安装后
https://www.paddlepaddle.org.cn/install/old?docurl=/documentation/docs/zh/2.0/install/pip/windows-pip.html#anchor-24
![image](https://user-images.githubusercontent.com/18697846/109929728-c3e5f900-7d01-11eb-9bb4-90d2d6baa4b1.png)

官网文档中gpu版本安装也是paddlepaddle，不是paddlepaddle-gpu；安装完成后检查 fluid.install_check.run_check()显示可以在多GPU/CPU环境上运行，但是无法调用fluid.core.get_cuda_device_count()方法。是否是官网文档出错，实际安装了CPU版本？
![image](https://user-images.githubusercontent.com/18697846/109929667-b03a9280-7d01-11eb-8830-6accd6f03cd7.png)

**Comment by topxxuki** [comment]
尝试使用paddlepaddle-gpu       1.6.3.post107 版本，可以检查到gpu，但是安装检查报错如下：
![image](https://user-images.githubusercontent.com/18697846/109934167-2db4d180-7d07-11eb-99a6-e31fd897bf5d.png)
![image](https://user-images.githubusercontent.com/18697846/109934190-34434900-7d07-11eb-9cbb-dc2f5e8a1383.png)

nccl版本从2.4.6升级到2.8.4均报错如上

**Comment by topxxuki** [comment]
python3 -m pip install paddlepaddle-gpu==1.8.5.post107 -f https://paddlepaddle.org.cn/whl/stable.html 1.8.5版本也有一样的问题

**Comment by gfwm2013** [comment]
@topxxuki 正在咨询负责安装的同学，等下回复给您结果

**Comment by topxxuki** [comment]
更换nccl为2.4.7+cuda10.0版本，问题已解决
