### ISSUE TITLE
关于模型保存和读取的几个疑问

### ISSUE THREAD

**Issue by yeyupiaoling** [PaddlePaddle/Paddle#31439]
- PaddlePaddle 2.0.0
 - Python 3.7
 - 只考虑动态图

1、下面的API是只保留的模型的结构和参数，并没有保存优化方法的参数，如果要保存优化方法的参数是否还要执行`paddle.save(optimizer.state_dict(), 'optimizer.pdopt')`？
```python 
path = "example.dy_model/linear"
paddle.jit.save(
    layer=layer,
    path=path,
    input_spec=[InputSpec(shape=[None, 784], dtype='float32')])
```

2、我的数据输入是变长的，如shape为`(batch size, 128, 数据实际长度)`，这种情况下如果设置`input_spec`参数？

3、如果是使用`paddle.jit.save()`API保存的模型，在使用`paddle.load()`读取模型继续训练中，`use_structured_name`参数必须是False吗？
```python
path = "example.model/linear"
state_dict = paddle.load(path)
layer.set_state_dict(state_dict, use_structured_name=False)
```

**Comment by chenwhql** [comment]
1. jit.save的定位是仅用于推理模型保存，会对模型进行裁剪，不会保留优化器参数，设计上就是这样的，这里您为什么要用jit.save存呢？是为了推理吗？如果不是，不推理在训练的时候用这个接口存
2. 如果您后面是变长维度，并且您的模型实际执行时能够适应变长，可以将变长维度设置为`None`
3. 这种情况，不需要设置`use_structured_name `这个参数，jit.save保存了structured_name信息，会自动适配，仅在您兼容载入1.x接口或静态图接口保存的结果时才需要设置这个参数
![image](https://user-images.githubusercontent.com/22561442/110081323-bba3c180-7dc6-11eb-8d96-afba6d662021.png)

**Comment by yeyupiaoling** [comment]
@chenwhql 谢谢。
>jit.save的定位是仅用于推理模型保存，会对模型进行裁剪，不会保留优化器参数，设计上就是这样的，这里您为什么要用jit.save存呢？是为了推理吗？如果不是，不推理在训练的时候用这个接口存

因为我需要保存模型，用于之后继续训练。也可以用于推理。我需要保存一套既可用于训练，也可以用于预测的。最好是推理不需要模型代码，

**Comment by chenwhql** [comment]
因为这两种方式本质就有些差别：
- 训练模型：完整模型，含优化器
- 预测模型：精简模型，是完整模型的子图，仅完成接收特定输入，得到特定预测结果的功能

所以，他们俩的存储目标不太一样

**Comment by chenwhql** [comment]
> 最好是推理不需要模型代码，

推理确实不需要模型代码

**Comment by yeyupiaoling** [comment]
@chenwhql 明白了，谢谢，如果是需要训练的话，就必须用paddle.save()。想要无模型代码推理，只能用paddle.jit.save()。

那我干脆这两个接口都用上。但保存自定义变量还是个问题。
