### ISSUE TITLE
python3.7，paddlegpu2.0 在本地训练时，出现 TypeError: __init__() got an unexpected keyword argument 'label_list'

### ISSUE THREAD

**Issue by dhao-island** [PaddlePaddle/Paddle#31444]
为使您的问题得到快速解决，在建立Issues前，请您先通过如下方式搜索是否有相似问题:【搜索issue关键字】【使用labels筛选】【官方文档】

如果您没有查询到相似问题，为快速解决您的提问，建立issue时请提供如下细节信息：
- 标题：简洁、精准概括您的问题，例如“Insufficient Memory xxx" ”
- 版本、环境信息：
    1）PaddlePaddle版本：请提供您的PaddlePaddle版本号，例如1.1或CommitID
    2）CPU：预测若用CPU，请提供CPU型号，MKL/OpenBlas/MKLDNN/等数学库使用情况
    3）GPU：预测若用GPU，请提供GPU型号、CUDA和CUDNN版本号
    4）系统环境：请您描述系统类型、版本，例如Mac OS 10.14，Python版本
 注：您可以通过执行[summary_env.py](https://github.com/PaddlePaddle/Paddle/blob/develop/tools/summary_env.py)获取以上信息。
- 训练信息
    1）单机/多机，单卡/多卡
    2）显存信息
    3）Operator信息
- 复现信息：如为报错，请给出复现环境、复现步骤
- 问题描述：请详细描述您的问题，同步贴出报错信息、日志、可复现的代码片段

Thank you for contributing to PaddlePaddle.
Before submitting the issue, you could search issue in the github in case that there was a similar issue submitted or resolved before.
If there is no solution,please make sure that this is a training issue including the following details:
**System information**
-PaddlePaddle version （eg.1.1）or CommitID
-CPU: including CPUMKL/OpenBlas/MKLDNN version
-GPU: including CUDA/CUDNN version
-OS Platform (eg.Mac OS 10.14)
-Other imformation: Distriuted training/informantion of operator/
Graphics card storage
Note: You can get most of the information by running [summary_env.py](https://github.com/PaddlePaddle/Paddle/blob/develop/tools/summary_env.py). 
**To Reproduce**
Steps to reproduce the behavior
**Describe your current behavior**
**Code to reproduce the issue**
**Other info / logs**

**Comment by DannyIsFunny** [comment]
请问可以详细描述一下错误场景吗：
- 机器环境
- 具体代码片段
- 错误日志

**Comment by dhao-island** [comment]
不好意思，来晚了点，我又跑了两遍，也不知道为什么没有这个问题了。现在出现了另一个问题，OSError: (External)  Cuda error(35), CUDA driver version is insufficient for CUDA runtime version. 请问在paddle架构下怎么升级cudac驱动啊？可以在pycharm里输入交互命令升级吗？

**Comment by DannyIsFunny** [comment]
你好。可以直接升级显卡驱动，paddle架构下可以按照一般方法升级显卡驱动，没有特殊要求。
可以参考一些一般教程实现：
Windows ： https://jingyan.baidu.com/article/2c8c281da97bab0008252af3.html
Linux: https://blog.csdn.net/u010420283/article/details/104020531
