### ISSUE TITLE
安装后不能用

### ISSUE THREAD

**Issue by aishangmaxiaoming** [PaddlePaddle/Paddle#31445]
为使您的问题得到快速解决，在建立Issues前，请您先通过如下方式搜索是否有相似问题:【搜索issue关键字】【使用labels筛选】【官方文档】

如果您没有查询到相似问题，为快速解决您的提问，建立issue时请提供如下细节信息：
- 标题：简洁、精准概括您的问题
- 版本、环境信息：
    1）PaddlePaddle版本：请提供您的PaddlePaddle版本号，例如1.1或CommitID
    2）CPU/GPU：如果您使用GPU训练，请提供GPU驱动版本、CUDA和cuDNN版本号
    3）系统环境：请您描述系统类型、版本，例如Mac OS 10.14

    4）Python版本号
    5）显存信息
 注：您可以通过执行[summary_env.py](https://github.com/PaddlePaddle/Paddle/blob/develop/tools/summary_env.py)获取以上信息。
- 复现信息：如为报错，请给出复现环境、复现步骤
- 问题描述：请详细描述您的问题，同步贴出报错信息、日志/代码关键片段

Thank you for contributing to PaddlePaddle.
Before submitting the issue, you could search issue in the github in case that there was a similar issue submitted or resolved before.
If there is no solution,please provide us with the following details :
**System information**
-PaddlePaddle version （eg.1.1）or CommitID
-CPU: including CPUMKL/OpenBlas/MKLDNN version
-GPU: including CUDA/cuDNN version
-OS Platform and Distribution(eg.Mac OS 10.14)
-Python version 
Note: You can get most of the information by running [summary_env.py](https://github.com/PaddlePaddle/Paddle/blob/develop/tools/summary_env.py). 
**To Reproduce**
Steps to reproduce the behavior
**Describe your current behavior**
**Code to reproduce the issue**
**Other info / logs**
<img width="302" alt="d897489fac314a6e7c0403508972ad62" src="https://user-images.githubusercontent.com/67897601/110082690-a6c82d80-7dc8-11eb-9e3f-d3b6da391030.png">
<img width="456" alt="b5c07dd0d31a336b0f2421c0b1b688b5" src="https://user-images.githubusercontent.com/67897601/110082701-adef3b80-7dc8-11eb-86b5-61e8102af852.png">

**Comment by DannyIsFunny** [comment]
请问你是安装Paddle/Serving失败吗，PaddleServing的安装可以参考 `Serving` repo里的说明：https://github.com/PaddlePaddle/Serving/blob/v0.5.0/README.md#installation

**Comment by DannyIsFunny** [comment]
Paddle/Serving安装相关issue建议移动到 https://github.com/PaddlePaddle/Serving/issues
Serving repo中

**Comment by HexToString** [comment]
该问题已解决。
