### ISSUE TITLE
三方库下载编译仍git下载且编译错误

### ISSUE THREAD

**Issue by Crystalxd** [PaddlePaddle/Paddle#31448]
- 版本、环境信息：
    1）PaddlePaddle版本：release/2.0
    2）CPU：Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz
    3）GPU：Tesla T4，CUDA：10.0 CUDNN：7.6.5
    4）系统环境：CentOS7.5.1804、Python版本：python3.7

三方库下载版本：https://github.com/PaddlePaddle/PaddleOCR/issues/439

- 安装方式信息：
本地编译：~/cmake-3.18.4-Linux-x86_64/bin/cmake 
-DWITH_CONTRIB=OFF
-DWITH_MKL=ON 
-DWITH_MKLDNN=ON 
-DWITH_NCCL=OFF 
-DCMAKE_BUILD_TYPE=Release 
-DON_INFER=ON 
-DWITH_PYTHON=OFF 
-DWITH_GPU=ON 
-DTHIRD_PARTY_PATH=./third_party
..
 
GCC：5.4.0

问题：因为下载三方库过慢，所以按照此方法手动导入5.4.0的三方库，在make的时候依然自行下载三方库，有些链接失效，倒是下载失败，make失败 
![image](https://user-images.githubusercontent.com/34636084/110090475-4d64fc00-7dd2-11eb-86a2-1cb8a0ecc545.png)
![image](https://user-images.githubusercontent.com/34636084/110091193-2824bd80-7dd3-11eb-8918-7da34309de3b.png)

**Comment by DannyIsFunny** [comment]
你好，请问你是想源码编译Paddle还是需要源码编译出cmake呢

**Comment by DannyIsFunny** [comment]
从错误信息上看是gflag 下载失败的问题

**Comment by Crystalxd** [comment]
源码编译出Paddle，但是我已经拷贝了third_party到build目录了，按理应该会检测到有文件存在不会再继续下载了啊

**Comment by Crystalxd** [comment]
下载的速度又太慢，另外很多链接还不可用。。不知道是怎么回事

**Comment by Crystalxd** [comment]
@DannyIsFunny

**Comment by jiweibo** [comment]
可以换修改对应gflags.cmake中的url，改成gitee的链接，这样从国内下载就会很快

**Comment by Crystalxd** [comment]
@jiweibo Thanks.
