### ISSUE TITLE
C++ 调用Python导入Paddle 包会导致当前程序反复启动直到崩溃

### ISSUE THREAD

**Issue by snuabar** [PaddlePaddle/Paddle#31459]
1）PaddlePaddle版本：2.0.0
    2）CPU/GPU：Intel gen8 Core i5，无GPU，内存8G
    3）系统环境：Windows 10 20H2
    4）Python版本号：3.7
    5）显存信息 无

- 复现信息：PyRun_SimpleString("import paddle") 
- 问题描述：执行时间很长，并且后台在反复运行当前程序直到崩溃，无论是直接引用带Import paddle 的py文件，还是直接在c++ 中使用PyRun_SimpleString("import paddle") ，都会复现，请看下图。
- 运行时的状态
![1](https://user-images.githubusercontent.com/19286389/110217495-38ca5600-7eef-11eb-88e5-51a8076e27cf.png)
- 崩溃后的状态
![2](https://user-images.githubusercontent.com/19286389/110217498-3a941980-7eef-11eb-8a31-93c56eb38021.png)

**Comment by liym27** [comment]
感谢反馈！已将该问题反馈给相关同事进行排查，同时我们也会继续跟进该问题，及时与您同步进展，谢谢。

**Comment by zhwesky2010** [comment]
@snuabar 您好，请问这个问题在Linux下是否也会出现呢？
另外，目前这样使用的场景是什么样呢

**Comment by snuabar** [comment]
> 
> 
> @snuabar 您好，请问这个问题在Linux下是否也会出现呢？
> 另外，目前这样使用的场景是什么样呢，我们还没有进行过相关使用场景的测试，可能是存在bug.

你好，目前没有Linux环境，我的项目要求C#程序调用C++的dll，这个dll刚好需要使用到paddle包，也会导致c#程序反复启动。

我们是希望使用贵公司开源模块PaddleOCR，目前使用的是python的版本，执行 from paddle import PaddleOCR 这句代码时，在python集成环境下是可行的，但是在c++无论调用包含这句代码的py文件或者运行PyRun_SimpleString("from paddle import PaddleOCR")，都会导致当前程序反复启动。目前，反复启动的问题在c++端可以通过代码控制，但是PyImport_ImportModule导入py文件时，出现上述的问题，等所有被反复启动的程序关闭后，该函数返回了空值，没有办法进一步操作。

附件为示例代码
[PaddleOCRDemo.zip](https://github.com/PaddlePaddle/Paddle/files/6114415/PaddleOCRDemo.zip)

**Comment by srforever** [comment]
请问这个问题是否已解决？我司在利用某些平台桌面端软件内置的python环境进行paddle调用，希望可以在该桌面端软件中集成paddle的深度学习能力，遇到了重复弹窗的相似问题。另在paddle开发者论坛上也有人遇到[相似问题](https://aistudio.baidu.com/paddle/forum/topic/show/964945)

**Comment by srforever** [comment]
请问这个问题是否已解决？我司在利用某些平台桌面端软件内置的python环境进行paddle调用，希望可以在该桌面端软件中集成paddle的深度学习能力，遇到了重复弹窗的相似问题。另在paddle开发者论坛上也有人遇到[相似问题](https://aistudio.baidu.com/paddle/forum/topic/show/964945)

**Comment by zhwesky2010** [comment]
@snuabar @srforever https://github.com/PaddlePaddle/Paddle/pull/34312 已经修复了这个问题

**Comment by zhwesky2010** [comment]
@srforever @snuabar 你好，请问一下 通过这种应用场景，是用于Paddle的训练还是预测功能呢，如果只是纯预测的话 也可以使用我们的C++预测库哈
