### ISSUE TITLE
希望支持自定义指定多GPU卡

### ISSUE THREAD

**Issue by xiangqingcs** [PaddlePaddle/Paddle#31450]
欢迎您对PaddlePaddle提出建议，非常感谢您对PaddlePaddle的贡献！
在留下您的建议时，辛苦您同步提供如下信息：
- 版本、环境信息
1）PaddlePaddle版本：请提供您的PaddlePaddle版本号，例如1.1
2）CPU/GPU：您是否使用GPU进行训练，如是，请提供您的CUDA和cuDNN版本号
3）系统环境：请您描述系统类型、版本，例如Mac OS 10.14
注：您可以通过执行[summary_env.py](https://github.com/PaddlePaddle/Paddle/blob/develop/tools/summary_env.py)获取以上信息。
- 复现信息：如为报错，请给出复现环境、复现步骤
- 建议描述：请您详细描述，您认为需优化的功能

Thank you for contributing to PaddlePaddle.
Before submitting the issue, you could search issue in the github in case that there was a similar issue submitted or resolved before.
Please make sure that this is a feature request. 
**System information**
-PaddlePaddle version （eg.1.1）or CommitID
-CPU: including CPUMKL/OpenBlas/MKLDNN version
-GPU: including CUDA/CUDNN version
-OS Platform (eg.Mac OS 10.14)
Note: You can get most of the information by running [summary_env.py](https://github.com/PaddlePaddle/Paddle/blob/develop/tools/summary_env.py). 
**To Reproduce**
Steps to reproduce the behavior
**Describe the feature and the current behavior/state.**
**Any Other info.**

现在服务器上面有４个Ｖ100的GPU网卡，不同的卡使用不同的任务，相关的信息如下：
C:\Users\Administrator>nvidia-smi
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 431.02       Driver Version: 431.02       CUDA Version: 10.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name            TCC/WDDM | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla V100-PCIE...  TCC  | 00000000:3B:00.0 Off |                    0 |
| N/A   34C    P0    36W / 250W |  15851MiB / 16224MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   1  Tesla V100-PCIE...  TCC  | 00000000:86:00.0 Off |                    0 |
| N/A   31C    P0    25W / 250W |    523MiB / 16224MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   2  Tesla V100-PCIE...  TCC  | 00000000:AF:00.0 Off |                    0 |
| N/A   35C    P0    38W / 250W |  15851MiB / 16224MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   3  Tesla V100-PCIE...  TCC  | 00000000:D8:00.0 Off |                    0 |
| N/A   36C    P0    51W / 250W |   1702MiB / 16224MiB |      7%      Default |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0    144652      C   C:\Program Files\Python36\python3.exe      15327MiB |
|    2    220112      C   C:\Program Files\Python36\python3.exe      15327MiB |
+-----------------------------------------------------------------------------+

训练的时候，发现空闲的网卡为1卡和3卡，想用1卡和3卡来训练相关的任务，来提高程序运行的效率，之后通过分析代码，发现代码如下：paddle.set_device("gpu:3" if use_gpu else "cpu")
分析代码发现，在GPU带卡编号的代码如下：
`avaliable_gpu_device = re.match(r'gpu:\d+', lower_device)
        avaliable_xpu_device = re.match(r'xpu:\d+', lower_device)
...
        if avaliable_gpu_device:
            if not core.is_compiled_with_cuda():
                raise ValueError(
                    "The device should not be {}, since PaddlePaddle is " \
                    "not compiled with CUDA".format(avaliable_gpu_device))
            device_info_list = device.split(':', 1)
            device_id = device_info_list[1]
            device_id = int(device_id)
            place = core.CUDAPlace(device_id)
`
上面代码位置：\Lib\site-packages\paddle\device.py    方法def set_device(device)， L104--L167
这个代码不支持多卡的模式

环境相关的信息
Python为：3.7.10
paddlepaddle的版本为：
paddlenlp          2.0.0rc1
paddlepaddle-gpu   2.0.0rc1

看是否能想Pytorch一样，支持自定义多卡的模式，比如类似这样的模式：device = paddle.set_device("gpu:1,gpu:3" if use_gpu else "cpu")

**Comment by skywalk163** [comment]
可以直接用这条命令指定显卡启动程序，文档源代码不用改（原文档里也不要用set_device手工指定卡）：
python3 -m paddle.distributed.launch  --gpus="1, 3" train.py

对程序的要求是：
是飞桨自己写的模块或套件，比如paddleclas，paddleseg 等
或者是自己用高层api写的代码，如果不是，需要在程序中修改三处：

使用基础API场景

#第1处改动，import库
import paddle.distributed as dist

#第2处改动，初始化并行环境
dist.init_parallel_env()

#第3处改动，对模型增加paddle.DataParallel封装
net = paddle.DataParallel(paddle.vision.models.LeNet())

修改完毕就可以使用 python3 -m paddle.distributed.launch  --gpus="1, 3"  xxx 来启动了。


具体参加这个项目：https://aistudio.baidu.com/aistudio/projectdetail/1222066

**Comment by gaorui999** [comment]
> 可以直接用这条命令指定显卡启动程序，文档源代码不用改（原文档里也不要用set_device手工指定卡）：
> python3 -m paddle.distributed.launch --gpus="1, 3" train.py
> 
> 对程序的要求是：
> 是飞桨自己写的模块或套件，比如paddleclas，paddleseg 等
> 或者是自己用高层api写的代码，如果不是，需要在程序中修改三处：
> 
> 使用基础API场景
> 
> #第1处改动，import库
> import paddle.distributed as dist
> 
> #第2处改动，初始化并行环境
> dist.init_parallel_env()
> 
> #第3处改动，对模型增加paddle.DataParallel封装
> net = paddle.DataParallel(paddle.vision.models.LeNet())
> 
> 修改完毕就可以使用 python3 -m paddle.distributed.launch --gpus="1, 3" xxx 来启动了。
> 
> 具体参加这个项目：https://aistudio.baidu.com/aistudio/projectdetail/1222066

高层API无法启动脚本文件
