### ISSUE TITLE
怎样得到由“DatasetFolder”构建的数据集的类别的个数

### ISSUE THREAD

**Issue by A-Pai** [PaddlePaddle/Paddle#31456]
怎样得到由“DatasetFolder”构建的数据集的类别的个数

**Comment by jiweibo** [comment]
可以参考相关文档https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/vision/datasets/folder/DatasetFolder_cn.html#datasetfolder

在目录中对不同的class进行分类就行了
```
# temp_dir is root dir
# temp_dir/class_1/img1_1.jpg
# temp_dir/class_2/img2_1.jpg
```
