### ISSUE TITLE
十二生肖分类中的数据集定义

### ISSUE THREAD

**Issue by JJYjackson** [PaddlePaddle/Paddle#31462]
- 标题：十二生肖分类中的数据集定义
- 版本、环境信息：
    1）PaddlePaddle版本：2.0.0
    2）CPU/GPU：CPU
    3）系统环境：notebook
    4）Python版本号：3.7
    5）显存信息
- 问题描述：请问normalize(mean=[], std=[])中的均值和标准差数值是怎么得到的？

![提问](https://user-images.githubusercontent.com/65533171/110239155-8f33a500-7f80-11eb-9e3e-c0098674a26d.PNG)

**Comment by liym27** [comment]
您好，请问所贴代码是来自哪里，是否方便给出相关链接？

**Comment by JJYjackson** [comment]
您好！
项目链接：https://aistudio.baidu.com/aistudio/projectdetail/1588738

AI studio中的十二生肖分类项目中dataset.py中的。














在 2021-03-07 20:55:10，"liym27" <notifications@github.com> 写道：

您好，请问所贴代码是来自哪里，是否方便给出相关链接？

**Comment by TCChenlong** [comment]
这个应该是根据数据集的标准差和方差计算得来的，更详细的内容可以看一下AI Studio的这门课程：[高层API助你快速上手深度学习](https://aistudio.baidu.com/aistudio/education/group/info/6771)，课节3里包含了这个项目的详细的说明~

**Comment by JJYjackson** [comment]
抱歉，这个项目的课程中对该问题没有做详细解答，“这个应该是根据数据集的标准差和方差计算得来的”您能说的更详细些吗？如果是自己的数据集又改怎样来计算？非常感谢。


















在 2021-03-08 09:50:02，"Chen Long" ***@***.***> 写道：

这个应该是根据数据集的标准差和方差计算得来的，更详细的内容可以看一下AI Studio的这门课程：高层API助你快速上手深度学习，课节3里包含了这个项目的详细的说明~

**Comment by JJYjackson** [comment]
抱歉，这个项目的课程中对该问题没有做详细解答，“这个应该是根据数据集的标准差和方差计算得来的”您能说的更详细些吗？如果是自己的数据集又该怎样来计算？非常感谢。
















在 2021-03-08 09:50:02，"Chen Long" ***@***.***> 写道：

这个应该是根据数据集的标准差和方差计算得来的，更详细的内容可以看一下AI Studio的这门课程：高层API助你快速上手深度学习，课节3里包含了这个项目的详细的说明~

**Comment by JJYjackson** [comment]
抱歉，这个项目的课程中对该问题没有做详细解答，“这个应该是根据数据集的标准差和方差计算得来的”您能说的更详细些吗？如果是自己的数据集又改怎样来计算？
非常感谢。
















在 2021-03-08 09:50:02，"Chen Long" ***@***.***> 写道：

这个应该是根据数据集的标准差和方差计算得来的，更详细的内容可以看一下AI Studio的这门课程：高层API助你快速上手深度学习，课节3里包含了这个项目的详细的说明~

**Comment by JJYjackson** [comment]
抱歉，这个项目的课程中对该问题没有做详细解答，“这个应该是根据数据集的标准差和方差计算得来的”您能说的更详细些吗？如果是自己的数据集又该怎样来计算？
非常感谢。
