### ISSUE TITLE
请问 RandomHorizontalFlip 官方文档中设置 224 也是概率吗？

### ISSUE THREAD

**Issue by starlightme** [PaddlePaddle/Paddle#31464]
https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/vision/transforms/transforms/RandomHorizontalFlip_cn.html#randomhorizontalflip

**Comment by starlightme** [comment]
和0.5相比感觉有些奇怪

**Comment by TCChenlong** [comment]
已经改为0.5了哈，下次上线后就会更新了，感谢您的反馈~

**Comment by TCChenlong** [comment]
已更新 感谢反馈：https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/vision/transforms/transforms/RandomHorizontalFlip_cn.html#randomhorizontalflip
