### ISSUE TITLE
nn.Bilinear文档的一点建议

### ISSUE THREAD

**Issue by Maybewuss** [PaddlePaddle/Paddle#31461]
<a href="https://www.codecogs.com/eqnedit.php?latex=\text&space;{&space;out&space;}_{i}=x&space;1&space;*&space;W_{i}&space;*&space;x&space;2^{\mathrm{T}}" target="_blank"><img src="https://latex.codecogs.com/gif.latex?\text&space;{&space;out&space;}_{i}=x&space;1&space;*&space;W_{i}&space;*&space;x&space;2^{\mathrm{T}}" title="\text { out }_{i}=x 1 * W_{i} * x 2^{\mathrm{T}}" /></a>

- x1: 第一个输入，包含 :in1_features个元素，形状为 [batch_size, in1_features]。

- x2: 第二个输入，包含 :in2_features个元素，形状为 [batch_size, in2_features]。

- Wi: 第 :i个被学习的权重，形状是 [in1_features, in2_features]。

- outi: 输出的第 :i个元素，形状是 [batch_size, out_features]。

- b: 被学习的偏置参数，形状是 [1, out_features]。

文档中介绍的参数维度与写的公式对不上，建议把x1和x2分别加上下标i，代表batch中的第i个**行向量**，另外建议把w的整体维度也介绍一下，就像在nn.functional.bilinear中介绍的weight那样。

**Comment by liym27** [comment]
非常感谢您的建议！已将您的建议反馈给 `nn.Bilinear` 的接口负责人，我们将及时对文档进行改进。
