### ISSUE TITLE
model.fit有自适应终止训练的功能吗？

### ISSUE THREAD

**Issue by A-Pai** [PaddlePaddle/Paddle#31466]
https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/hapi/model/Model_cn.html#fit-train-data-none-eval-data-none-batch-size-1-epochs-1-eval-freq-1-log-freq-10-save-dir-none-save-freq-1-verbose-2-drop-last-false-shuffle-true-num-workers-0-callbacks-none
model.fit有自适应终止训练的功能吗？
model.fit的参数epochs设定了训练迭代的次数，总的来说，epochs越大，train_data的loss越小，但是eval_data的loss是先下降，再上升，如下图所示，**eval_data的loss最小的点对应的应该是最优模型**。用户往往不知道epochs应该为多大，实际上可以自动检测eval_data的loss，若是其总体进入了上升阶段，就应该终止训练了。由于eval_data的loss往往呈为锯齿状(不是单调上升或下降)，可以设定一个停滞值(迭代的代数,比如10)，若继续迭代这么多代，loss没有下降，就终止顺利。
这种方法是自适应的，遗传算法等多有应用。
![QQ截图20210308112005](https://user-images.githubusercontent.com/5112397/110270213-50ddca80-8000-11eb-901d-4086341a836a.jpg)

**Comment by FrostML** [comment]
现在 hapi 有个回调函数 EarlyStopping，可以支持传入比较简单的参数，比如多少 epoch eval 的某个指标不下降/上升就停止训练。可以参考具体文档：https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/hapi/callbacks/EarlyStopping_cn.html#earlystopping

**Comment by A-Pai** [comment]
正是需要这个功能，谢谢
