### ISSUE TITLE
2.0 paddle文档有错误

### ISSUE THREAD

**Issue by a2824256** [PaddlePaddle/Paddle#31476]
页面地址：https://www.paddlepaddle.org.cn/tutorials/projectdetail/1516124#anchor-10
ConvBNLayer的forward部分，下图用蓝色标注起来的代码，上下文不存在out这个变量，x=out应该是x=y。
![image](https://user-images.githubusercontent.com/7108023/110304781-f1e77800-8036-11eb-9362-24bb9cd3aacc.png)

**Comment by TCChenlong** [comment]
好的，收到，我们尽快更正一下，感谢您的反馈~

**Comment by TCChenlong** [comment]
已修复 再次感谢您的反馈 如有其他问题欢迎随时沟通~
