### ISSUE TITLE
在英伟达的jetson NX上安装Paddlepaddle遇到的问题

### ISSUE THREAD

**Issue by dengxinlong** [PaddlePaddle/Paddle#31472]
问题图片描述：(pip 安装)
![image](https://user-images.githubusercontent.com/32217129/110300191-9070da80-8031-11eb-9dbe-e3dea371512e.png)

PaddlePaddle：最新
CPU：NVIDIA Carmel ARM v8.2
GPU：NVIDIA Volta GPU
cuda：10.2
python: 3.6.9
操作系统：ubuntu 18.04

**Comment by pangyoki** [comment]
您好，可以尝试加一下`sudo`看看？

**Comment by dengxinlong** [comment]
刚刚加了，还是一样的问题。

**Comment by wangye707** [comment]
jetson上需要下载whl包安装，下载地址：https://www.paddlepaddle.org.cn/documentation/docs/zh/install/Tables.html

**Comment by wangye707** [comment]
jetson上需要手动下载whl包来安装，下载地址：https://www.paddlepaddle.org.cn/documentation/docs/zh/install/Tables.html

**Comment by wangye707** [comment]
jetson上需要手动下载whl包来安装：下载地址：https://www.paddlepaddle.org.cn/documentation/docs/zh/install/Tables.html
![image](https://user-images.githubusercontent.com/39162106/110625173-0e6fe580-81da-11eb-9c89-949f28668eac.png)
