### ISSUE TITLE
可否对modle.fit中的shuffle设置随机种子？

### ISSUE THREAD

**Issue by A-Pai** [PaddlePaddle/Paddle#31475]
https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/hapi/model/Model_cn.html#fit-train-data-none-eval-data-none-batch-size-1-epochs-1-eval-freq-1-log-freq-10-save-dir-none-save-freq-1-verbose-2-drop-last-false-shuffle-true-num-workers-0-callbacks-none

![QQ截图20210308173715](https://user-images.githubusercontent.com/5112397/110303106-f6129600-8034-11eb-89ba-2622b60d3878.jpg)

**Comment by LielinJiang** [comment]
可以通过在外部设置random.seed，np.random.seed，paddle.seed来设置随机种子

**Comment by A-Pai** [comment]
哪一种设置对shuffle起作用？

**Comment by LielinJiang** [comment]
https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/io/DistributedBatchSampler_cn.html#set_epoch，您可以通过在外部手动创建dataloader（datset, sampler），并把创建好的dataloader传给fit。这时候可以通过上面的set_epoch固定随机种子。这个时候fit中的shuffle就会失效。而使用您自己定义好的种子

**Comment by A-Pai** [comment]
> [https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/io/DistributedBatchSampler_cn.html#set_epoch，您可以通过在外部手动创建dataloader（datset](https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/io/DistributedBatchSampler_cn.html#set_epoch%EF%BC%8C%E6%82%A8%E5%8F%AF%E4%BB%A5%E9%80%9A%E8%BF%87%E5%9C%A8%E5%A4%96%E9%83%A8%E6%89%8B%E5%8A%A8%E5%88%9B%E5%BB%BAdataloader%EF%BC%88datset), sampler），并把创建好的dataloader传给fit。这时候可以通过上面的set_epoch固定随机种子。这个时候fit中的shuffle就会失效。而使用您自己定义好的种子

这似乎要绕一个大圈子，不是一个好办法
