### ISSUE TITLE
因为尝试了在线安装paddlepaddle不行，就尝试离线安装，硬件环境如下所示，错误如下图：

### ISSUE THREAD

**Issue by dengxinlong** [PaddlePaddle/Paddle#31489]
![image](https://user-images.githubusercontent.com/32217129/110415976-de3b2080-80cd-11eb-8b9a-d8fd10f4ddde.png)

应该是下载的whl不对，但是我没有找到相应的whl，不知道官方能否告知下面这种环境下应该使用哪个whl，非常感谢！！！

PaddlePaddle：最新
CPU：NVIDIA Carmel ARM v8.2
GPU：NVIDIA Volta GPU
cuda：10.2
python: 3.6.9
操作系统：ubuntu 18.04

**Comment by swtkiwi** [comment]
python3 -m pip install paddlepaddle-gpu==2.0.0 -i https://mirror.baidu.com/pypi/simple

**Comment by dengxinlong** [comment]
不不，您理解错了，我可能，没有表达清楚，在标题中说明了我想要的是离线安装，您提供的链接仍然是在线安装。因为我这边网络有问题，所以才尝试离线安装。想知道的是在我上面说明的软硬件情况下，离线应该下载哪个版本的whl来安装？？？

**Comment by cryoco** [comment]
请问您的硬件是nvidia jetson xavier nx么？

**Comment by swtkiwi** [comment]
在这里下载：https://paddle-wheel.bj.bcebos.com/2.0.1-gpu-cuda10.2-cudnn7-mkl_gcc8.2/paddlepaddle_gpu-2.0.1-cp37-cp37m-linux_x86_64.whl

**Comment by dengxinlong** [comment]
您好，是的。

**Comment by cryoco** [comment]
https://www.paddlepaddle.org.cn/documentation/docs/zh/install/Tables.html#whl-release
可以在这个表格里，根据python 版本，下载2.0.0-nv-jetson-jetpack4.3-xavier的whl包

**Comment by dengxinlong** [comment]
嗯嗯，好的，明白了，非常感谢

**Comment by lemon9707** [comment]
我离线安装paddlepaddle.whl文件时报错UnicodeDecodeError：utf-8 codec can't decode byte 0xb5 in position4:invalid start byte
这是什么原因呢
