### ISSUE TITLE
强烈建议保留lodtensor接口

### ISSUE THREAD

**Issue by nfmmm** [PaddlePaddle/Paddle#31516]
看到最版本的paddle在处理NLP问题是推荐使用padding方式，并且文档中提到paddle.fluid接口将逐步被替换，但针对lodtensor没有找到新的替代接口。
在我看来，lodtensor结构是我选择paddle框架的一个重要原因，而且我自己正在做的NLP项目在处理篇章级文本问题，构建字-句-段-篇的模型时使用lodtensor非常方便，强烈建议后续的版本依然能够继续看到paddle框架的这一优点。请开发的小哥哥，小姐姐关注。

**Comment by GT-ZhangAcer** [comment]
这玩意虽然理解起来不太容易，但挺有意思的，如果能保留也挺好

**Comment by juncaipeng** [comment]
感谢，我们会反馈相关同学知晓。

**Comment by juncaipeng** [comment]
目前依旧可用，只是不推荐。后续版本，规划同学会讨论决定。

**Comment by nfmmm** [comment]
我认为这是paddle的一大优势，在一些特定的NLP任务需要保留所有重要信息时候，比如引入某些外生注意力信息需要便利整个文本时 lod模型具有很大的便利性

**Comment by GT-ZhangAcer** [comment]
> 我认为这是paddle的一大优势，在一些特定的NLP任务需要保留所有重要信息时候，比如引入某些外生注意力信息需要便利整个文本时 lod模型具有很大的便利性

有这种感觉，哈哈哈
