### ISSUE TITLE
Does Paddle implement elastic-scaling in parameter server training mode?

### ISSUE THREAD

**Issue by zpcalan** [PaddlePaddle/Paddle#31514]
### This is a question about distributed training feature, not a bug report. So most of the items below are not involved.

> Thank you for contributing to PaddlePaddle.
> Before submitting the issue, you could search issue in the github in case that there was a similar issue submitted or resolved before.
> If there is no solution,please provide us with the following details :
> **System information**
> -PaddlePaddle version （eg.1.1）or CommitID
> Develop branch
> -CPU: including CPUMKL/OpenBlas/MKLDNN version
> not involved
> -GPU: including CUDA/cuDNN version
> not involved
> -OS Platform and Distribution(eg.Mac OS 10.14)
> not involved
> -Python version 
> not involved
> Note: You can get most of the information by running [summary_env.py](https://github.com/PaddlePaddle/Paddle/blob/develop/tools/summary_env.py). 
> **To Reproduce**
> Steps to reproduce the behavior: not involved
> **Describe your current behavior**
>  not involved
> **Code to reproduce the issue**
> not involved
> **Other info / logs**

I notice that the [paddlepaddle edl](https://github.com/elasticdeeplearning/edl) is mainly python code and focus on making jobs efficient using container cluster managers like k8s.(I haven't dug into the code yet)
But the parameter server training [code in Paddle](https://github.com/PaddlePaddle/Paddle/tree/develop/paddle/fluid/distributed) doesn't have any description or method about elastic scaling. I wonder how parameter server cluster gets scaled if one user wants to add a server for his training job. I suppose that the parameter server must be aware of the elastic scaling event so that it can rebuild the network, rearrage rank id and rank size, etc.
This is just my personal thought based on the parameter server framework. Correct me if I'm wrong. Thank you very much.

**Comment by juncaipeng** [comment]
Paddle distributed training does not support the feature for now. The feature maybe work in process.

**Comment by zpcalan** [comment]
> Paddle distributed training does not support the feature for now. The feature maybe work in process.

Thanks, it's good to be clarified.
Issue closed.
