### ISSUE TITLE
离线安装paddle

### ISSUE THREAD

**Issue by dengxinlong** [PaddlePaddle/Paddle#31522]
Paddle: 最新
CPU：32  Intel(R) Xeon(R) Silver 4110 CPU @ 2.10GHz
GPU：1080，cuda: 10.0, cudnn: 7.6.3
系统：Ubuntu 18.04 (x86_64)
问题如下：
![image](https://user-images.githubusercontent.com/32217129/110594655-0bfc9400-81b8-11eb-9a47-48689f0b03de.png)

**Comment by dengxinlong** [comment]
就是想问一下，这种环境下应该下载哪个包？？，我在这个网址下找的下面这个包还是同样的问题，应该是包不对。
![Uploading image.png…]()

**Comment by juncaipeng** [comment]
可以参考这个文档，根据环境不同来选择特定的包：https://www.paddlepaddle.org.cn/install/quick?docurl=/documentation/docs/zh/install/pip/windows-pip.html

如果目标机器没有网络，可以在其他机器上执行在线安装命令，可以从log看到下载whl包的链接，直接wget这个路径就可以下载whl包，然后拷贝到目标机器上离线安装。

**Comment by dengxinlong** [comment]
您的想法的确可行，但是有个问题，想要找到匹配的包，得先要和我现在的机器的环境一致啊，我机器的环境就这一台，且因为是在学校，导致网络不行，不然也不会选择离线安装了。

**Comment by dengxinlong** [comment]
其实我就是想知道，我目前的环境下，使用哪个安装包合适，环境提问的时候我给出了，但是找了几个我认为匹配的，但是都失败了。

**Comment by juncaipeng** [comment]
你给出的log显示安装过程中还是需要联网，所以导致错误，可能不是版本不匹配的问题。

我会再去确认是否支持离线安装。

**Comment by XieYunshen** [comment]
应该下载cuda10.0的包，
![image](https://user-images.githubusercontent.com/32428676/110759844-04f18680-8289-11eb-90bc-3049be15213f.png)
