### ISSUE TITLE
paddle一键部署服务器时，web用户端无响应

### ISSUE THREAD

**Issue by CVMLL** [PaddlePaddle/Paddle#31537]
环境情况：
系统：win10专业版；
环境：conda和pycharm2020.1.2
           paddlepaddle=1.7.2
           paddlehub=1.7.0

所调用的模型：
       1."face_landmark_localization"
       2."deeplabv3p_xception65_humanseg"

部署代码错误：
Warning: Windows cannot use multiprocess working mode, PaddleHub Serving will switch to single process mode
face_landmark_localization == 1.0.2
deeplabv3p_xception65_humanseg==1.0.0
* Serving Flask app "paddlehub.serving.app_single" (lazy loading)
* Environment: production
WARNING: This is a development server. Do not use it in a production deployment.
Use a production WSGI server instead.
* Debug mode: off
2021-03-10 12:00:00，600-INFO： * Running on http://0.0.0.0:8866/(Press CTRL+C to quit) 
![微信图片_20210310221537](https://user-images.githubusercontent.com/57761343/110642699-38cb9e00-81ee-11eb-8f99-72091db69ab6.png)

然后web客户端没有数据，报108为止错误：
![微信图片_20210310221545](https://user-images.githubusercontent.com/57761343/110642862-6add0000-81ee-11eb-8244-502dbb66e658.png)

但是电脑的端口并没有被占用，而用户端却没有数据，这点表示很疑惑，麻烦各位大佬解决一二！
![微信图片_20210310221552](https://user-images.githubusercontent.com/57761343/110643028-9a8c0800-81ee-11eb-91e6-eb91c9ec848a.png)

**Comment by ShenYuhan** [comment]
您好，如果是windows机器，看下是不是防火墙问题，可以通过python的http.server模块快速检查服务是否可以被访问到
