### ISSUE TITLE
The dtype of left and right variables are not the same？

### ISSUE THREAD

**Issue by BeyondYourself** [PaddlePaddle/Paddle#31548]
Paddle版本，最新稳定版本
训练环境AIStudio
出现的警告或者异常：
`/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/math_op_patch.py:238: UserWarning: The dtype of left and right variables are not the same, left dtype is VarType.FP32, but right dtype is VarType.INT32, the right dtype will convert to VarType.FP32
  format(lhs_dtype, rhs_dtype, lhs_dtype))
<class 'paddle.nn.layer.conv.Conv2D'>'s flops has been counted
Customize Function has been applied to <class 'paddle.nn.layer.norm.SyncBatchNorm'>
Cannot find suitable count function for <class 'paddle.nn.layer.pooling.MaxPool2D'>. Treat it as zero FLOPs.
Total Flops: 124757737472     Total Params: 13406085
124757737472
terminate called without an active exception

--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
0   paddle::framework::SignalHandle(char const*, int)
1   paddle::platform::GetCurrentTraceBackString[abi:cxx11]()

----------------------
Error Message Summary:
----------------------
FatalError: `Process abort signal` is detected by the operating system.
  [TimeInfo: *** Aborted at 1615444854 (unix time) try "date -d @1615444854" if you are using GNU date ***]
  [SignalInfo: *** SIGABRT (@0x3e800004c02) received by PID 19458 (TID 0x7f1ec9fff700) from PID 19458 ***]`

上面有一个警告，这个警告是什么原因呢，没弄明白
另外最后总是会出现个FatalError,这个是什么意思呢，谢谢解答

**Comment by zhangting2020** [comment]
（1）上面提到的warning
`
 left dtype is VarType.FP32, but right dtype is VarType.INT32, the right dtype will convert to VarType.FP32
`

比如当我们执行这样的一段代码：
```
import paddle

x1 = paddle.to_tensor(([[1, 1], [1, 1]]), dtype="float32")
x2 = paddle.to_tensor(([[0, 0], [0, 0]]), dtype="int32")

x = x1 + x2
```
x1是float32的，x2是int32，x2会被cast为float32。这个warning就是提醒这个转换操作，需要注意下是不是符合预期的，这个warning主要是在调用elementwise的二元计算，比如add、sub等，或者是compare相关的API时出现。

（2）最后的这个fatal error看上去是非正常退出导致的，可以具体描述下上面这个错误发生的场景吗？
