### ISSUE TITLE
Unit test for `lookup_table` OP with SelectedRows in grad.

### ISSUE THREAD

**Issue by arogowie-intel** [PaddlePaddle/Paddle#31559]
I've added support for BF16 data type in [PR](https://github.com/PaddlePaddle/Paddle/pull/31558), however I can't find a way to test the grad calculations with "W" input as `SelectedRows`. Does [this part of code](https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/fluid/tests/unittests/test_lookup_table_op.py#L87-L137) checks also grad? Could you advise how to test grad calculations with "W" input as `SelectedRows` ?

**Comment by zhangting2020** [comment]
The code you refer to only checks the forward result and it does not check the grad.  There is no function to automatically calculate the theoretical gradient in our unit test framework.

You can try to implement the theoretical gradient calculation yourself in the unit test, and compare it with the actual value calculated by the operator.

**Comment by arogowie-intel** [comment]
@zhangting2020 

> There is no function to automatically calculate the theoretical gradient in our unit test framework.

I'm not sure I understand you. There is already a function [`check_grad`](https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/fluid/tests/unittests/op_test.py#L1358) which calculates grads and checks it's correctness. However it seems to me that it uses only `LoDTensor`s.

I see then that `LookupTable` operator has untested scenario: The gradient values are not tested when the input `W` is a `SelectedRows`. And my question is how I can run grad with `W` as `SelectedRows`. All that I see in the unittests code are the cases running only inference (like `Operator().run()`) with `W` as `SelectedRows`. 

I can (and already did in some UTs) calculate reference values for LookupTable grad, but could you advise me how to run the backward computations for LookupTable such that the `W` input is set to `SelectedRows`?

**Comment by lidanqing-vv** [comment]
@arogowie-intel I saw that PR is finished and reviewed, should this issue be closed ?

**Comment by arogowie-intel** [comment]
@lidanqing-intel Although the PR already received some reviews I think that the issue noted above still have to be addressed. It would be best to have it already in that PR, however even adding such a test in a later PR would be valuable.

This thing seems to be important since this is a control-flow path (backward: [lookup_table_op.h#L154-L156](https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/fluid/operators/lookup_table_op.h#L154-L156) and [lookup_table_op.h#L167-L198](https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/fluid/operators/lookup_table_op.h#L167-L198) , which is not tested or at least I couldn't find examples of such tests. Note that in second link this code is under branch testing attribute `is_sparse` which is present in "word2vec" model.
