### ISSUE TITLE
Executor in C++ side has strange behavior different from one in the python side

### ISSUE THREAD

**Issue by yiakwy** [PaddlePaddle/Paddle#31554]
## Cannot train model in C++ side for Released 2.0

![train_cplusplus_debug1](https://user-images.githubusercontent.com/8510840/110757840-cbb81700-8286-11eb-910d-30b02ea66555.png)

We noticed that there is simple demo for training models in c++ side (mimicking paddle::inference) :

> https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/fluid/train/demo/demo_trainer.cc:109

After digging into the source code we found strange behavior exposed by C++ Executor:

![train_cplusplus_debug4](https://user-images.githubusercontent.com/8510840/110758377-6ca6d200-8287-11eb-9cd0-c386edd0a489.png)

This prevents us moving forward in training a module in c++ so that we can easily learn more about paddle backends.

The issue is when we execute c++ Executor, the _holder inside the tensor will be cleared out. We want to understand how c++ executor works and try to find quick though dirty solution to go ahead.

**Comment by yiakwy** [comment]
I have resolved the problem by muting GC options defined in CPP executor and allocate memory for loss_tensor every epoch

```
 for (int i = 0; i < 10; ++i) {
    /*
     * see reference source code in
     * /home/yiakwy/anaconda3/envs/py36/lib/python3.6/site-packages/paddle/fluid/executor.py:1327
     * When to use program_cache by setting `create_local_scope` and `create_vars` values
     */
    auto loss_tensor = loss_var->GetMutable<paddle::framework::LoDTensor>();
    loss_tensor->Resize({1, 1});
    auto loss_data = loss_tensor->mutable_data<float>(cpu_place);
    // it is also possible to set FLAGS_eager_delete_tensor_gb to -1 to produce equal effects
    executor.Run(*train_program, &scope, 0, false, true, std::vector<std::basic_string<char>>(), true);

    // fetch output tensor value
    std::cout << "step: " << i << " loss: "
              << loss_var->Get<paddle::framework::LoDTensor>().data<float>()[0]
              // << loss_data[0]
              << std::endl;
  }
```
![train_cxx_debug5](https://user-images.githubusercontent.com/8510840/110794078-4fd2c480-82b0-11eb-8e4a-7b242e061ac3.png)

But more technical analysis is needed

**Comment by zhangting2020** [comment]
- The loss does not seem to change. Refer to the [Readme](https://github.com/PaddlePaddle/Paddle/tree/develop/paddle/fluid/train/demo) of this demo, the above results are correct because there is no optimizer op.
-  In order to reduce memory usage, the loss  tensor is freed when an iteration ends because it is unused. This may be the reason why the original demo does not work.
