### ISSUE TITLE
paddle有类似pytorch-lightning那样的接口吗？

### ISSUE THREAD

**Issue by Maybewuss** [PaddlePaddle/Paddle#31552]

**Comment by zhangting2020** [comment]
您好，可以参考下高阶API使用指南https://www.paddlepaddle.org.cn/documentation/docs/zh/tutorial/quick_start/high_level_api/high_level_api.html

**Comment by zhangting2020** [comment]
您好，目前Paddle暂时还没有这样的接口，我们会评估需求，考虑在未来版本中支持。
