### ISSUE TITLE
可变形卷积

### ISSUE THREAD

**Issue by dhao-island** [PaddlePaddle/Paddle#31565]
文件模型中dcn_v2_stages: 这里的v2是表示dcnv2版嘛？如果想改成v1版，该怎么改呢？

**Comment by MrChengmo** [comment]
> 文件模型中dcn_v2_stages: 这里的v2是表示dcnv2版嘛？如果想改成v1版，该怎么改呢？

请问这个`dcn_v2_stages`是哪个模型或者工具中的呢，可以提供下链接吗？

**Comment by dhao-island** [comment]
是paddle目标识别项目里，配置配件中一个选项。https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.0-rc/configs/dcn/yolov3_r50vd_dcn_obj365_pretrained_coco.yml  在resnet配置中的dcn_v2_stages.

**Comment by dinghao19960829** [comment]
> > 文件模型中dcn_v2_stages: 这里的v2是表示dcnv2版嘛？如果想改成v1版，该怎么改呢？
> 
> 请问这个`dcn_v2_stages`是哪个模型或者工具中的呢，可以提供下链接吗？

**Comment by dhao-island** [comment]
> > 文件模型中dcn_v2_stages: 这里的v2是表示dcnv2版嘛？如果想改成v1版，该怎么改呢？
> 
> 请问这个`dcn_v2_stages`是哪个模型或者工具中的呢，可以提供下链接吗？

您好，之前误操作关闭了论题，不好意思。您若知道相关的配置设置信息，在这先感谢您的回复！

**Comment by MrChengmo** [comment]
> > > 文件模型中dcn_v2_stages: 这里的v2是表示dcnv2版嘛？如果想改成v1版，该怎么改呢？
> > 
> > 
> > 请问这个`dcn_v2_stages`是哪个模型或者工具中的呢，可以提供下链接吗？
> 
> 您好，之前误操作关闭了论题，不好意思。您若知道相关的配置设置信息，在这先感谢您的回复！

检测相关的问题可以在https://github.com/PaddlePaddle/PaddleDetection/issues 这里提issue，相关同学会跟进
