### ISSUE TITLE
https://hub.docker.com/r/paddledev/paddle/ English docs url error

### ISSUE THREAD

**Issue by llxxxll** [PaddlePaddle/Paddle#3159]
![07478c506d769b4a2f9a258f4](https://user-images.githubusercontent.com/1908992/28860283-89259892-778e-11e7-8be6-271c2ace99ce.jpg)

![61381ca2edbc762183a538397](https://user-images.githubusercontent.com/1908992/28860284-8d00cdc4-778e-11e7-85ba-ef37b2b69a58.jpg)

**Comment by Yancey1989** [comment]
Fixed, the new link is http://doc.paddlepaddle.org/doc/ and Chinese for http://doc.paddlepaddle.org/doc_cn/.
