### ISSUE TITLE
使用 TorchText 时出现C++ 依赖问题

### ISSUE THREAD

**Issue by LeoMax-Xiong** [PaddlePaddle/Paddle#31597]
我在使用 TorchText & Paddle 时，出现了下面的问题。后来发现这个就是 Paddle 安装时会出现的问题：
![image](https://user-images.githubusercontent.com/11361692/110924341-e52b9280-835c-11eb-8f3d-5bfe5e292ba9.png)

**Comment by MrChengmo** [comment]
请问有没有尝试过在Paddle提供的官方docker中进行安装？

比较推荐在docker中运行，可以排除很多底层环境依赖问题。

**Comment by LeoMax-Xiong** [comment]
@MrChengmo 没有在 docker 中运行，我尝试一下。

**Comment by LeoMax-Xiong** [comment]
1. 这个镜像也太大了。基本上把所有的 python 的 paddle 都安装了。
2. 但是只有 python3.5的 python 有 pip，其他的都没有 pip
3. 其他的 python 都是直接给出的python源码编译的路径，不能把源码编译出来的 python 给 install 到一个地方么。
4. 用其他的 python3 源码安装的 setuptool 和 pip 都是在/usr/bin/下，都没有到对应的 python3
5. 鸡肋呀。这就导致只能跑别的地方调试好的 Paddle 代码，一点想安装其他开始扩展都不行。

**Comment by MrChengmo** [comment]
> * 这个镜像也太大了。基本上把所有的 python 的 paddle 都安装了。
> * 但是只有 python3.5的 python 有 pip，其他的都没有 pip
> * 其他的 python 都是直接给出的python源码编译的路径，不能把源码编译出来的 python 给 install 到一个地方么。
> * 用其他的 python3 源码安装的 setuptool 和 pip 都是在/usr/bin/下，都没有到对应的 python3
> * 鸡肋呀。这就导致只能跑别的地方调试好的 Paddle 代码，一点想安装其他开始扩展都不行。

您使用的是哪个镜像呢？

**Comment by LeoMax-Xiong** [comment]
这个镜像：
``` shell
paddlepaddle/paddle:2.0.1-gpu-cuda10.1-cudnn7
```

**Comment by MrChengmo** [comment]
> 这个镜像：
> 
> ```shell
> paddlepaddle/paddle:2.0.1-gpu-cuda10.1-cudnn7
> ```

好的，我会反馈给负责镜像的开发者，之后优化这里。

**Comment by LeoMax-Xiong** [comment]
@MrChengmo 如果更新镜像的话，可以再这里回复一下。
