### ISSUE TITLE
静态图matmul使用问题

### ISSUE THREAD

**Issue by zhangyimi** [PaddlePaddle/Paddle#31590]
paddle1.8 静态图

我想在静态图对两个tensor进行矩阵乘法，在引入下面这段代码导致显存占用急剧上升(应该是q和p维度过大导致的)，使得模型仅能使用很小batch，想请教下有没有优化的方法？
有其他同学验证过类似的操作在静态图会导致显存上升很多，但动态图会好很多。

```
# q = [batch, heads, len, hidden]
# p = [batch, heads, len, len, hidden]

reshape_q = fluid.layers.unsqueeze(input=q, axes=[3])
product = layers.matmul(x=reshape_q, y=p, transpose_y=True)
product = fluid.layers.squeeze(product, axes=[3])

```

**Comment by MrChengmo** [comment]
> paddle1.8 静态图
> 
> 我想在静态图对两个tensor进行矩阵乘法，在引入下面这段代码导致显存占用急剧上升(应该是q和p维度过大导致的)，使得模型仅能使用很小batch，想请教下有没有优化的方法？
> 有其他同学验证过类似的操作在静态图会导致显存上升很多，但动态图会好很多。
> 
> ```
> # q = [batch, heads, len, hidden]
> # p = [batch, heads, len, len, hidden]
> 
> reshape_q = fluid.layers.unsqueeze(input=q, axes=[3])
> product = layers.matmul(x=reshape_q, y=p, transpose_y=True)
> product = fluid.layers.squeeze(product, axes=[3])
> ```

需要看一下上升的显存是不是符合预期，估算一下输入相乘的矩阵大小，如果差很多，也许有bug。

另外有用paddle 2.0的最新版本进行过类似的实验吗

**Comment by zhangyimi** [comment]
这个操作该怎么估算显存， 调用matmul会申请额外显存的么 还是整个过程只申请了 product和 reshape_q的显存？
模型是基于transformer，每个block操作相同，所以以上操作会执行多次，因为q和p都不是模型参数，有办法当前层执行完后就把显存释放么

**Comment by MrChengmo** [comment]
> 这个操作该怎么估算显存， 调用matmul会申请额外显存的么 还是整个过程只申请了 product和 reshape_q的显存？
> 模型是基于transformer，每个block操作相同，所以以上操作会执行多次，因为q和p都不是模型参数，有办法当前层执行完后就把显存释放么

- matmul结果会占用显存，squeeze的结果也会占显存，后续梯度的计算会用到这些中间结果
- 维度之积 * 数据类型占用的大小 可以快速估算显存占用
- 释放显存可以试试用recompute 策略: https://fleet-x.readthedocs.io/en/latest/paddle_fleet_rst/collective/collective_mp/index.html
