### ISSUE TITLE
AssertionError: When Variable is used as the condition of if/while , Variable can only contain one element.

### ISSUE THREAD

**Issue by gongel** [PaddlePaddle/Paddle#31598]
```
tensor=paddle.to_tensor([[1,2,3]])
print(1 in tensor)
```
最后一行代码会报错，PyTorch如此操作没问题。只能转成numpy或者降维吗？
麻烦解决一下，谢谢。

**Comment by MrChengmo** [comment]
Tensor 不支持 `in` 的操作符，实现类似功能，可以试下下面的方法：

```python
import paddle
tensor=paddle.to_tensor([1,2,3])
zero=paddle.to_tensor([0,0,0])
where=paddle.where(tensor==1,tensor,zero)
print("where: {}".format(where))
res=paddle.sum(where)
print("cotain 1? :{}".format(res==1))
```

**Comment by gongel** [comment]
> Tensor 不支持 `in` 的操作符，实现类似功能，可以试下下面的方法：
> 
> ```python
> import paddle
> tensor=paddle.to_tensor([1,2,3])
> zero=paddle.to_tensor([0,0,0])
> where=paddle.where(tensor==1,tensor,zero)
> print("where: {}".format(where))
> res=paddle.sum(where)
> print("cotain 1? :{}".format(res==1))
> ```

感谢回复。但是一维Tensor貌似支持`in`操作符：
```python
>>> tensor=paddle.to_tensor([1,2,3])
>>> print(1 in tensor)
True
```

**Comment by MrChengmo** [comment]
> > Tensor 不支持 `in` 的操作符，实现类似功能，可以试下下面的方法：
> > ```python
> > import paddle
> > tensor=paddle.to_tensor([1,2,3])
> > zero=paddle.to_tensor([0,0,0])
> > where=paddle.where(tensor==1,tensor,zero)
> > print("where: {}".format(where))
> > res=paddle.sum(where)
> > print("cotain 1? :{}".format(res==1))
> > ```
> 
> 感谢回复。但是一维Tensor貌似支持`in`操作符：
> 
> ```python
> >>> tensor=paddle.to_tensor([1,2,3])
> >>> print(1 in tensor)
> True
> ```

好的，看起来这应该是一个待优化的地方，我会反馈给对应的开发者。
