### ISSUE TITLE
恢复训练时过去visualdl数据丢失

### ISSUE THREAD

**Issue by kyrios-sam** [PaddlePaddle/Paddle#31609]
恢复训练可以在visualdl上查看之前的数据记录吗？我每次恢复训练后打开visualdl之前的记录都没了

**Comment by YixinKristy** [comment]
VisualDL支持日志续写，对于恢复训练的日志续写，可以使用file_name这个参数，指定同一个logfile name，即可实现训练记录续写，详情参考：https://github.com/PaddlePaddle/VisualDL/blob/develop/README_CN.md#%E4%BD%BF%E7%94%A8%E6%96%B9%E5%BC%8F
<img width="1017" alt="截屏2021-03-15 下午12 06 16" src="https://user-images.githubusercontent.com/48054808/111102438-0cfe3e80-8587-11eb-845a-3986869bb95a.png">
