### ISSUE TITLE
Missing tensor.h file when generating coverage report with genthml

### ISSUE THREAD

**Issue by arlesniak** [PaddlePaddle/Paddle#31606]
**System information**
-PaddlePaddle version 0205e9f84ecb74ab0bcb3e06ba45779440da4c75
-CPU: including CPUMKL/OpenBlas/MKLDNN version
-GPU: no GPU
-OS Platform and Distribution Ubuntu 16.04.6 LTS
-Python version 3.6.10
**To Reproduce**
cmake .. -DWITH_AVX=ON -DWITH_GPU=OFF -DWITH_MKLDNN=ON -DCMAKE_EXPORT_COMPILE_COMMANDS=OFF -DWITH_PROFILER=ON -DON_INFER=ON -DCMAKE_BUILD_TYPE=Release -DWITH_TESTING=ON -DWITH_INFERENCE_API_TEST=ON -DWITH_NCCL=OFF -DWITH_COVERAGE=ON -DCMAKE_C_COMPILER="/usr/bin/gcc-5" -DCMAKE_CXX_COMPILER="/usr/bin/g++-5" -DWITH_LITE=OFF  -DPY_VERSION=3.6 -DWITH_PYTHON=ON -DWITH_DISTRIBUTE=ON -DWITH_STYLE_CHECK=OFF 
make -j 12
ctest -R mkldnn
lcov --capture --directory . --output-file coverage.info 
genhtml --demangle-cpp coverage.info --output-directory out

**Describe your current behavior**
I want to generate coverage report for the code. I'm using command like above.

During **genhtml** step, the following error shows up:
```
Processing file extension/include/tensor.h
genhtml: ERROR: cannot read paddle/fluid/extension/include/tensor.h
```

However the folder has only the following files **(not tensor.h)**:
```
paddle/fluid/extension/include$
total 56
drwxrwxr-x 2 paddle paddle  4096 mar 10 08:02 ./
drwxrwxr-x 4 paddle paddle  4096 mar  3 15:06 ../
-rw-rw-r-- 1 paddle paddle  1092 mar  3 15:06 ext_all.h
-rw-rw-r-- 1 paddle paddle  5476 mar  3 15:06 ext_dispatch.h
-rw-rw-r-- 1 paddle paddle   889 mar  3 15:06 ext_dll_decl.h
-rw-rw-r-- 1 paddle paddle  2141 mar  3 15:06 ext_dtype.h
-rw-rw-r-- 1 paddle paddle  3414 mar 10 08:02 ext_exception.h
-rw-rw-r-- 1 paddle paddle 13513 mar  3 15:06 ext_op_meta_info.h
-rw-rw-r-- 1 paddle paddle   756 mar  3 15:06 ext_place.h
-rw-rw-r-- 1 paddle paddle  3734 mar 10 08:02 ext_tensor.h

```
Could you advice on that, please?

**Comment by luotao1** [comment]
@lelelelelez Please help see this issue.

**Comment by lelelelelez** [comment]
@arlesniak  Please see if the code is updated. I used your command  and found `extension/include/ext_tensor.h` not  `extension/include/tensor.h`
![image](https://user-images.githubusercontent.com/22937122/111288580-474b0700-867f-11eb-9143-f3d46bdfc765.png)
And `extension/include/tensor.h` has been changed to `extension/include/ext_tensor.h` in https://github.com/PaddlePaddle/Paddle/commit/8c94d8cb4c4800fc159d0146856c15aa5ebbaeb9#diff-8fef4cc933774931bb1f578f8cec9c32b3429de37f5b5d72634b6ed7445c2eed

**Comment by lidanqing-vv** [comment]
@arlesniak  Hi, I saw your PR is merged, can I close this issue

**Comment by arlesniak** [comment]
@lelelelelez  @lidanqing-intel Thank you for the info. The issue didn't show up after I rebuilt my Paddle locally from starting from empty build folder. Therefore I close the issue. Thank you for you time.
