### ISSUE TITLE
paddle.fluid.layers.LSTMCell 的 gate_activation 和 activation 参数不生效

### ISSUE THREAD

**Issue by ShaneTian** [PaddlePaddle/Paddle#31605]
`paddle.fluid.layers.LSTMCell` 的 `gate_activation` 和 `activation` 参数未生效
- `paddle.fluid.layers.LSTMCell` 代码：https://github.com/PaddlePaddle/Paddle/blob/ffa88c31c2da5090c6f70e8e9b523356d7cd5e7f/python/paddle/fluid/layers/rnn.py#L390
- 实际调用的 `BasicLSTMUnit` 代码中未使用相关参数：https://github.com/PaddlePaddle/Paddle/blob/ffa88c31c2da5090c6f70e8e9b523356d7cd5e7f/python/paddle/fluid/contrib/layers/rnn_impl.py#L789 https://github.com/PaddlePaddle/Paddle/blob/ffa88c31c2da5090c6f70e8e9b523356d7cd5e7f/python/paddle/fluid/contrib/layers/rnn_impl.py#L820

**Comment by MrChengmo** [comment]
paddle 2.0 中动态图的LSTM修复了该问题：

<img width="846" alt="image" src="https://user-images.githubusercontent.com/29789135/111055639-18803580-84b3-11eb-99ba-f3039cb721e0.png">

静态图代码确实没有看到activation的使用

**Comment by ShaneTian** [comment]
了解。但有一些老代码依赖于 1.x 接口。烦请修复后同步一下 issue，谢谢~

**Comment by MrChengmo** [comment]
> 了解。但有一些老代码依赖于 1.x 接口。烦请修复后同步一下 issue，谢谢~

收到，我会反馈给对应的开发者跟进

**Comment by joey12300** [comment]
> 了解。但有一些老代码依赖于 1.x 接口。烦请修复后同步一下 issue，谢谢~

您好，RNN类API推荐使用2.0接口。1.x接口存在易用性等各方面问题，暂时不会维护了。

**Comment by ShaneTian** [comment]
> > 了解。但有一些老代码依赖于 1.x 接口。烦请修复后同步一下 issue，谢谢~
> 
> 您好，RNN类API推荐使用2.0接口。1.x接口存在易用性等各方面问题，暂时不会维护了。

那对于使用 1.x 接口开发中使用过该接口的用户来说，这个问题没发现的话，岂不一直用的是错的？
这是 BUG，还是得修复下吧。。。
