### ISSUE TITLE
这里的判断，无法正确处理安装多个版本CUDA的状态

### ISSUE THREAD

**Issue by mikeshi80** [PaddlePaddle/Paddle#31618]
https://github.com/PaddlePaddle/Paddle/blob/30a627aaf3af775620cda524058a4baccf7b109b/python/paddle/utils/cpp_extension/extension_utils.py#L445

当安装了多个版本的CUDA时，系统的PATH路径会指向多个CUDA版本，具体用哪个，是安装出现在Path中的前后顺序决定的，但是在Windows下，`where`语句会返回所有版本的路径，所以这里单纯使用去除默认换行符的作法是无法正确应对这种情况的。

要正确应对这种情况，应该使用如下方式

```python
nvcc_path = nvcc_path.split('\r\n')[0]
```

**Comment by zhwesky2010** [comment]
@mikeshi80 由于Linux下只有一个CUDA，Windows可以安装多个CUDA，这个没处理多CUDA情况。我们会修复问题。多谢指正

**Comment by wadefelix** [comment]
> @mikeshi80 由于Linux下只有一个CUDA，Windows可以安装多个CUDA，这个没处理多CUDA情况。我们会修复问题。多谢指正

linux也可以安装多份CUDA的，只不过一般不这么干。通过软件管理器安装的只能一份，但确实可以多份。
