### ISSUE TITLE
调用config->SetModel报Segmentation fault (core dumped)错误

### ISSUE THREAD

**Issue by xj160** [PaddlePaddle/Paddle#31616]
**代码：**
```
void CreateConfig(Config* config, const std::string& model_dirname) {
	// 模型从磁盘进行加载
	std::cout<<model_dirname + "/inference.pdmodel"<<std::endl;
	std::cout<<model_dirname + "/inference.pdiparams"<<std::endl;
	if(config)
	config->SetModel(model_dirname + "/inference",model_dirname + "/inference");
      
}
int main(){
        Config config;
	CreateConfig(&config, argv[1]);
}
```
centos系统，so是通过docker编译的，版本是release/2.0，so:libpaddle_inference.so
这里把代码精简了，错误就在`config->SetModel(model_dirname + "/inference",model_dirname + "/inference");`已经调试过的，模型也是存在的，config也不为空，报的错误Segmentation fault (core dumped)

**Comment by winter-wang** [comment]
SetModel函数的前两个参数，第一个代表着模型文件路径，一般是 *.pdmodel，第二个是参数文件，一般是 *.pdiparams。楼主忘了加后缀名。

**Comment by xj160** [comment]
> SetModel函数的前两个参数，第一个代表模型文件路径，一般是* .pdmodel，第二个是参数文件，一般是* .pdiparams。

不好意思，我这里代码贴的有点错误，我有试过改成绝对地址的，也是这个错误，测试用的代码是没有这个问题的
