### ISSUE TITLE
mkldnn加速ocr预测导致识别结果错误

### ISSUE THREAD

**Issue by xiejiang0133** [PaddlePaddle/Paddle#31617]
- 版本、环境信息：
    1）PaddlePaddle版本：2.0-rc1-0
    2）CPU：Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz  + MKLDNN
    4）系统环境：
- 复现信息：如为报错，请给出复现环境、复现步骤
- 问题描述：请详细描述您的问题，同步贴出报错信息、日志/代码关键片段
做OCR识别时，使用mkldnn加速出错。
未使用mkldnn时识别结果为：
![image](https://user-images.githubusercontent.com/76021403/111094069-5d6ca080-8575-11eb-9c99-dc7bfddec8fb.png)
使用mkldnn时结果为：
![image](https://user-images.githubusercontent.com/76021403/111094188-ade3fe00-8575-11eb-9b9c-fb42e8eae6c0.png)

**Comment by littletomatodonkey** [comment]
你好，建议使用2.0.1的whl包或者预测库哈
