### ISSUE TITLE
训练时出现关于数据类型的报错问题

### ISSUE THREAD

**Issue by JJYjackson** [PaddlePaddle/Paddle#31611]
### - 标题：训练模型时因数据类型不一致导致报错
- 版本、环境信息：
    1）PaddlePaddle版本：PaddlePaddle 2.0.1
    2）CPU：CPU 4  RAM 32GB
    3）GPU：GPU v100  显存 16GB  磁盘 100GB
    4）系统环境：Notebook,  python==3.7

- 训练信息
    1）单机，多卡
    2）显存信息  
![image](https://user-images.githubusercontent.com/65533171/111057066-5c793780-84bf-11eb-8edf-583695873962.png)
- 复现信息：
-     复现原项目链接：https://aistudio.baidu.com/aistudio/projectdetail/1589847?channelType=0&channel=0
- 问题描述：
-     FORK别人项目的基础上更换了自己的数字调制信号数据集，结果训练的时候报错.大概是因为输入和过滤器数据类型不一致。然后我将nlnet.py中159行self.conv1 = nn.Conv2D(1, self.inplanes, kernel_size=7, stride=2, padding=3, bias_attr=False)中的卷积层输入图像的通道数从3改为了1，307行的img = paddle.zeros([1, 3, 224, 224])  改为  img = paddle.zeros([1, 1, 2, 100])。结果还是报一样的错。
-     我自己的项目链接：https://aistudio.baidu.com/aistudio/projectdetail/1651677
- 报错信息：/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/setuptools/depends.py:2: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp
Reshape后的训练集标签的shape为：(800000,)
训练集的shape为：(800000, 2, 100, 1)
shuffle后的训练集前十个标签为：[2 6 4 1 3 5 4 7 3 4]
训练集每条数据的shape为：[1, 2, 100]
训练集第一条数据的label为：2 训练集大小为：800000
训练集第一条数据为：Tensor(shape=[1, 2, 100], dtype=float64, place=CUDAPlace(0), stop_gradient=True,
       [[[ 0.52265768,  1.85526290,  0.26033424,  0.92373452,  0.64890149, -1.28841186,  0.92083595,  0.57356467, -0.98522068,  1.23007937,  0.00490602,  1.91180346,  0.23345427, -0.32129037, -1.73350339,  1.33870054, -0.53091192,  0.83336470, -0.92840547,  0.69543402, -0.38791033,  0.57012490, -0.57608741, -0.17003753, -1.03513572, -1.22654907, -0.95948311, -0.39231686, -1.77318148, -1.57718326, -0.22785725,  2.62740663,  1.50292970,  0.31014393, -0.20409202, -0.08242928,  0.23135445, -0.70389011,  2.19812323,  0.38775654,  0.54594174,  0.21373631,  0.45125847, -0.43162987, -0.27916925,  0.62470537, -1.56414932, -1.09727153,  0.48518060,  1.55361418,  1.46507658, -0.41156137, -0.98640901,  0.20726308, -1.49038311,  1.13956694,  0.82609434,  0.23162843,  0.44346071,  0.16330126,  0.19152505, -0.00964151, -0.38682797, -1.52762103, -0.72609560,  0.55692926, -0.04720561, -0.87138353,  1.96523037,  0.01156579, -0.11731041,  0.86178972, -0.97590651, -0.98539902,  0.46941064, -0.24027714,  0.81940114, -0.61830673,  1.08762417, -1.09486788, -0.96859757, -0.86190586, -0.53363464,  0.29396153, -1.47085321,  0.50977269,  0.90777008,  0.35054033,  1.12957322,  0.34453894,  0.52050110,  0.70355194, -2.34697298, -1.10957321,  1.04547353,  0.52559765, -0.97470955,  0.70001589,  0.35095418,  0.58692784],
         [-0.89537190, -0.35951970, -0.01289189,  0.50627669,  0.21076062, -0.28433713,  0.82396937, -0.83081013, -2.29874491,  0.16945597, -0.02282148, -1.29406667,  0.15438910,  0.03986762, -0.29872119, -0.45431160, -0.51165073,  0.13364704,  1.74178988, -0.20819033,  1.48265908,  0.03528936,  0.43012910, -0.40709839,  0.58216647, -0.90850135,  0.23535500, -1.33048979,  1.18743086,  1.05290946,  1.09064760, -1.66765824, -0.03637247, -0.70932437,  0.54009474,  0.36060018, -0.06716483, -0.63022091,  0.88658390,  0.28062549,  1.33663894,  0.84665713, -0.61350545,  0.93568360,  0.88732395, -0.15680584, -0.02735751,  0.73543362,  0.08723535, -1.51230650,  0.27189185, -1.01484809,  0.18179689, -0.72272559, -0.25093465, -0.27997029, -1.01139352,  0.71529968, -1.36095368, -0.46065512, -0.51857369, -0.77992230, -0.00247596,  0.71321807,  0.28122194,  1.09122620,  0.40454757, -0.31219096,  1.24237062,  0.17485892, -0.92302395,  0.56106667, -0.97288312, -0.43370930,  0.86564787,  0.24608362,  1.42733253,  0.36994988,  1.34804681, -0.17187742, -0.52006481,  0.19765598, -0.42166253,  0.77911719,  0.16120164,  0.11648746,  0.82008874,  0.76505540, -1.34000172,  0.85840214, -1.13456060, -0.08944665,  0.75710948, -1.20221771, -0.02678714,  0.38242754,  0.39744101,  1.18395684, -0.56526418,  0.43462329]]])

验证集每条数据的shape为：[1, 2, 100]
验证集第一条数据的label为：0 验证集大小为：128000
W0314 12:39:10.162840 18420 device_context.cc:362] Please NOTE: device: 0, GPU Compute Capability: 7.0, Driver API Version: 10.1, Runtime API Version: 10.1
W0314 12:39:10.167623 18420 device_context.cc:372] device: 0, cuDNN Version: 7.6.
add nl after block 1 with 512 planes.
add nl after block 3 with 512 planes.
add nl after block 1 with 1024 planes.
add nl after block 3 with 1024 planes.
add nl after block 5 with 1024 planes.
The loss value printed in the log is the current step, and the metric is the average value of previous step.
Epoch 1/50
Traceback (most recent call last):
  File "code/train.py", line 126, in <module>
    verbose=1)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/hapi/model.py", line 1495, in fit
    logs = self._run_one_epoch(train_loader, cbks, 'train')
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/hapi/model.py", line 1802, in _run_one_epoch
    data[len(self._inputs):])
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/hapi/model.py", line 941, in train_batch
    loss = self._adapter.train_batch(inputs, labels)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/hapi/model.py", line 656, in train_batch
    * [to_variable(x) for x in inputs])
  File "/home/aistudio/code/nlnet.py", line 238, in forward
    x = self.conv1(x)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 902, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/nn/layer/conv.py", line 660, in forward
    use_cudnn=self._use_cudnn)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/nn/functional/conv.py", line 119, in _conv_nd
    pre_bias = getattr(core.ops, op_type)(x, weight, *attrs)
ValueError: (InvalidArgument) input and filter data type should be consistent
  [Hint: Expected input_data_type == filter_data_type, but received input_data_type:6 != filter_data_type:5.] (at /paddle/paddle/fluid/operators/conv_op.cc:175)
  [operator < conv2d > error]
![image](https://user-images.githubusercontent.com/65533171/111057563-83d20380-84c3-11eb-90ba-714bc9572c59.png)

**Comment by ForFishes** [comment]
您好，这里看报错信息，是由于cov的两个输入数据类型不一致。其中input_data 是float64，而filter_data是float32。这里看你的输入数据的tensor类型是 float64，所以导致后续类型不一致。这里有两种方法解决：
1、将输入数据x，强制转换成float32类型。x = paddle.cast(x, 'float32')
2、设置全局的参数类型为float64（即改变fileter的数据类型）。在最开始的位置，paddle.set_default_dtype(‘float64’).
