### ISSUE TITLE
config.enable_mkldnn() 启用加速后，结果出现了不明事物 

### ISSUE THREAD

**Issue by sunhufei** [PaddlePaddle/Paddle#31636]
欢迎您对PaddlePaddle提出建议，非常感谢您对PaddlePaddle的贡献！
在留下您的建议时，辛苦您同步提供如下信息：
- 版本、环境信息
1）PaddlePaddle版本：请提供您的PaddlePaddle版本号，例如1.1
2）CPU/GPU：您是否使用GPU进行训练，如是，请提供您的CUDA和cuDNN版本号
3）系统环境：请您描述系统类型、版本，例如Mac OS 10.14
注：您可以通过执行[summary_env.py](https://github.com/PaddlePaddle/Paddle/blob/develop/tools/summary_env.py)获取以上信息。
- 复现信息：如为报错，请给出复现环境、复现步骤
- 建议描述：请您详细描述，您认为需优化的功能

Thank you for contributing to PaddlePaddle.
Before submitting the issue, you could search issue in the github in case that there was a similar issue submitted or resolved before.
Please make sure that this is a feature request. 
**System information**
-PaddlePaddle version （eg.1.1）or CommitID
-CPU: including CPUMKL/OpenBlas/MKLDNN version
-GPU: including CUDA/CUDNN version
-OS Platform (eg.Mac OS 10.14)
Note: You can get most of the information by running [summary_env.py](https://github.com/PaddlePaddle/Paddle/blob/develop/tools/summary_env.py). 
**To Reproduce**
Steps to reproduce the behavior
**Describe the feature and the current behavior/state.**
**Any Other info.**

paddle 2.0.0 paddlehub 1.7.1

e[37m--- fused 0 scale with matmule[0m
e[37m--- Fused 0 ReshapeTransposeMatmulMkldnn patternse[0m
e[37m--- Fused 0 ReshapeTransposeMatmulMkldnn patterns with transpose's xshapee[0m
e[37m--- Fused 0 ReshapeTransposeMatmulMkldnn patterns with reshape's xshapee[0m
e[37m--- Fused 0 ReshapeTransposeMatmulMkldnn patterns with reshape's xshape with transpose's xshapee[0m
e[37m--- Fused 0 MatmulTransposeReshape patternse[0m
e[37m--- fused 0 batch norm with relu activatione[0m

这个东西怎么消去

**Comment by Shixiaowei02** [comment]
您好，Paddle 在运行时目前有一些日志；我们将考虑您的建议，将这部分日志在用户设定等级后才开启，默认关闭

**Comment by sunhufei** [comment]
怎么设定呀，官方并没有给出详解呀

**Comment by Shixiaowei02** [comment]
> 怎么设定呀，官方并没有给出详解呀

我们的日志是通过 google log 生成的，这是很多开源代码的通行做法。可以通过 `GLOG_v` 环境变量控制日志开启等级。

**Comment by lifw555** [comment]
这个怎么设置呢？ 使用 python的环境变量设置不生效呢
> os.environ['GLOG_v']='3'

环境：
os：windows 10
python：3.9
paddlepaddle：2.3.2
