### ISSUE TITLE
安装验证报错

### ISSUE THREAD

**Issue by knightdby** [PaddlePaddle/Paddle#31637]
paddle版本：1.8.5-gpu
系统环境：winserver2012
![image](https://user-images.githubusercontent.com/75298418/111122344-e4873c00-85a8-11eb-9e0c-5356f8db752e.png)

安装命令：pip install paddlepaddle-gpu==1.8.5.post107 -f https://paddlepaddle.org.cn/whl/stable.html
![image](https://user-images.githubusercontent.com/75298418/111122138-907c5780-85a8-11eb-9c04-04d4aba18d31.png)

**Comment by zhwesky2010** [comment]
@knightdby 您好，这个错误是驱动版本太低的原因，麻烦升级下显卡的硬件驱动。

**Comment by knightdby** [comment]
@zhouwei25 好的，谢谢您！已解决。
