### ISSUE TITLE
nn.Linear 的 name 参数没有作为 weight 和 bias 的 prefix

### ISSUE THREAD

**Issue by ShaneTian** [PaddlePaddle/Paddle#31643]
[`nn.Linear`](https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/nn/layer/common/Linear_cn.html) 中传入的 `name` 参数不生效，和[文档](https://www.paddlepaddle.org.cn/documentation/docs/zh/api_guides/low_level/program.html#api-guide-name)描述不符
https://github.com/PaddlePaddle/Paddle/blob/ffa88c31c2da5090c6f70e8e9b523356d7cd5e7f/python/paddle/nn/layer/common.py#L133
涉及到的是否还有其他 Layer?

**Comment by TCChenlong** [comment]
您好，请问下不生效是指？可否提供下具体复现的代码？谢谢~

**Comment by ShaneTian** [comment]
```py
import paddle
import paddle.nn as nn

print(paddle.__version__)
# '2.0.0'

net = nn.Linear(10, 10, name="test_fc")
for name, param in net.named_parameters():
    print(name, "<==>", param.name)
# weight <==> linear_1.w_0
# bias <==> linear_1.b_0
```

也就是，参数的名称必须从 `paddle.ParamAttr` 去传入：
```py
net = nn.Linear(10, 10, weight_attr=paddle.ParamAttr(name="test_fc.weight"),
                bias_attr=paddle.ParamAttr(name="test_fc.bias"))
for name, param in net.named_parameters():
    print(name, "<==>", param.name)
# weight <==> test_fc.weight
# bias <==> test_fc.bias
```

**Comment by TCChenlong** [comment]
您好，paddle 2.0以后，只能用 ``paddle.ParamAttr`` 传入参数名称，``name`` 只能设置该层的名字了，[name](https://www.paddlepaddle.org.cn/documentation/docs/zh/api_guides/low_level/program.html#api-guide-name) 这个文档我们及时更新，感谢您的反馈，我们尽快更新一下~

**Comment by ShaneTian** [comment]
了解，多谢~
