### ISSUE TITLE
请问Paddle对寒武纪MLU270的适配情况怎么样？有没有相关的文档或者指引？

### ISSUE THREAD

**Issue by jingruhou** [PaddlePaddle/Paddle#31648]
请问Paddle对寒武纪MLU270的适配情况怎么样？有没有相关的文档或者指引？

**Comment by yongqiangma** [comment]
MLU270是在paddle-lite中支持的，目前支持Resnet50（int8）、Senet101（int8）模型。
可以 用以下脚本进行编译
https://github.com/PaddlePaddle/Paddle-Lite/blob/develop/lite/tools/build_mlu.sh

**Comment by jingruhou** [comment]
您好，请问后续是否还会有检测、分割等网络模型适配MLU270？

**Comment by jingruhou** [comment]
您好，请问后续是否还会有检测、分割等网络模型适配MLU270？

**Comment by xwdreamer** [comment]
有没有寒武纪的案例，就像下图这样，有比特大陆tpu，有昆仑xpu。想要一个寒武纪的
![image](https://user-images.githubusercontent.com/1173919/147195752-2bc10c7a-4338-4fd3-aed1-1814ae0af916.png)
