### ISSUE TITLE
Add docs and benchmark of BF16 Inference

### ISSUE THREAD

**Issue by juncaipeng** [PaddlePaddle/Paddle#31645]
@lidanqing-intel  丹青，请将“BF16预测的文档和Benchmark数据”加到预测文档的“性能调优”章节，可以参考“X86 CPU 上部署量化模型”文档，主要介绍背景、使用方法、对机器要求、Benchmark数据。请注明是否支持任意模型，是否有特别的使用注意事项。具体时间请自行安排。

预测文档：https://github.com/PaddlePaddle/Paddle-Inference-Demo/tree/master/docs
阅览效果：https://paddle-inference.readthedocs.io/en/latest/index.html

**Comment by lidanqing-vv** [comment]
[BF16_test_reproduction.md](https://github.com/PaddlePaddle/Paddle/files/6573686/BF16_test_reproduction.md)

**Comment by lidanqing-vv** [comment]
PR #161 has been merged into Paddle-Inference-Demo
