### ISSUE TITLE
您好，环境安装报错

### ISSUE THREAD

**Issue by zcswdt** [PaddlePaddle/Paddle#31651]
我使用安装的是paddle-gpu-1.8.5,使用pip3 list能够查看gpu安装成功，但是使用如下命令却报错。
![image](https://user-images.githubusercontent.com/43515926/111248616-3bdaea00-8645-11eb-8b48-751526bb8544.png)
![image](https://user-images.githubusercontent.com/43515926/111248664-5319d780-8645-11eb-96b9-8320c4b71319.png)

**Comment by pangyoki** [comment]
您好，看报错是Cudnn的问题，请检查下Cudnn是否正确安装。

**Comment by zcswdt** [comment]
> 您好，看报错是Cudnn的问题，请检查下Cudnn是否正确安装

您好，cudnn的检测安装成功的命令是什么，我使用如下命令能检测到cudnn，不知道正不正确。
![image](https://user-images.githubusercontent.com/43515926/111407970-7c069f00-870f-11eb-81fa-04a22ce8d637.png)

**Comment by zcswdt** [comment]
> 您好，看报错是Cudnn的问题，请检查下Cudnn是否正确安装。

您好，可以看一下我这个问题么，目前还没解决、谢谢了

**Comment by wadefelix** [comment]
> > 您好，看报错是Cudnn的问题，请检查下Cudnn是否正确安装。
> 
> 您好，可以看一下我这个问题么，目前还没解决、谢谢了

可看下是不是这个没有短名软链接的缘故？https://github.com/PaddlePaddle/Paddle/issues/31715#issuecomment-801817733
