### ISSUE TITLE
FLuid版本如何输出学习率

### ISSUE THREAD

**Issue by yeyupiaoling** [PaddlePaddle/Paddle#31650]
- PaddlePaddle 1.8.5
 - FLuid

如下，怎么让它输出学习率
```python 
import paddle.fluid as fluid

place = fluid.CPUPlace()
exe = fluid.Executor(place)
exe.run(fluid.default_startup_program())

optimizer = fluid.optimizer.AdamOptimizer(
                    learning_rate=fluid.layers.exponential_decay(
                        learning_rate=0.1,
                        decay_steps=100,
                        decay_rate=0.83,
                        staircase=True))

for i in range(1000):
    lr = exe.run(program=fluid.default_main_program(),
                 fetch_list=[])
    print(lr)
```

**Comment by yaoxuefeng6** [comment]
可以通过fetch_list来获取
for i in range(1000):
    lr = exe.run(program=fluid.default_main_program(),
                 fetch_list=[optimizer.name])
    print(lr)

**Comment by yeyupiaoling** [comment]
@yaoxuefeng6 我现在要的就是fetch_list中应该填什么，optimizer.name这个属性不存在。
```
    fetch_list=[optimizer.name])
AttributeError: 'AdamOptimizer' object has no attribute 'name'
```

**Comment by yaoxuefeng6** [comment]
试试learning_rate.name

**Comment by yeyupiaoling** [comment]
@yaoxuefeng6 没有learning_rate，这个对象哪里来？

**Comment by yaoxuefeng6** [comment]
learning_rate=fluid.layers.exponential_decay(
                        learning_rate=0.1,
                        decay_steps=100,
                        decay_rate=0.83,
                        staircase=True)
optimizer = fluid.optimizer.AdamOptimizer(
                    learning_rate=learning_rate)

**Comment by yeyupiaoling** [comment]
好的，谢谢
