### ISSUE TITLE
在安装完paddle之后，使用fluid.install_check.run_check() 出现了错误

### ISSUE THREAD

**Issue by dengxinlong** [PaddlePaddle/Paddle#31663]
环境：jetson xavier nx，cuda：10.2 cuDNN: 8, jetpack: 4.5.1(最新)
下面截图是 import paddle.fluid as fluid 的结果：
image
下面截图是 运行 fluid.install_check.run_check() 的结果：
image
下面截图是运行 python ppdet/modeling/tests/test_architectures.py的结果：
image
从最后的结果上 来看，是通过了测试最后的 test_architectures.py的测试用例，但是前面run_check出现的问题，还是通过了，我就不太确定了。

**Comment by yaoxuefeng6** [comment]
我好看不到图片

**Comment by dengxinlong** [comment]
不好意思，问题已经解决了，感谢官方的耐心回复。说一下：
1. numpy包之前安装的是 1.19，如果直接使用 pip3 install numpy，后面导入numpy包的时候会发生非法指令错误，我安装的是numpy 1.17
2. 记得源码编译安装 nccl，https://blog.csdn.net/fuck_hang/article/details/108704045 这个链接中有怎么源码编译安装paddle，里面也有源码编译安装nccl，还有就是使用虚拟环境来使用。官方的教程中的源码安装paddle中有提到安装 virtualenvwrapper，但是就是提到了，如果不会的，就直接百度相关的教程，然后就是直接使用官方的包：
![image](https://user-images.githubusercontent.com/32217129/111564211-51324e80-87d4-11eb-9ab3-8b5cb5351050.png)
我安装的 是 箭头指向的。画 x 的我也测试了一下，发现不符合我目前的环境。这里的话只是我的环境，你的环境可能不太一样，针对 jetson xavier nx。

**Comment by dengxinlong** [comment]
我的环境是：
jetson xavier nx
安装的镜像是官方的：jetpack 4.5.1
其余的cuda，cudnn之类的都是这个镜像自带的了。
