### ISSUE TITLE
使用ai studio训练模型报错，问题如正文

### ISSUE THREAD

**Issue by gaorui999** [PaddlePaddle/Paddle#31679]
The loss value printed in the log is the current step, and the metric is the average value of previous step.
Epoch 1/100
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/layers/utils.py:77: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
  return (isinstance(seq, collections.Sequence) and
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/nn/layer/norm.py:648: UserWarning: When training, we now always track global mean and variance.
  "When training, we now always track global mean and variance.")
step  60/229 [======>.......................] - loss: 3.1190 - acc_top1: 0.0799 - acc_top5: 0.2940 - ETA: 20:21 - 7s/ste
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/PIL/TiffImagePlugin.py:770: UserWarning: Possibly corrupt EXIF data.  Expecting to read 23836229632 bytes but only got 0. Skipping tag 0
  " Skipping tag %s" % (size, len(data), tag)
step 160/229 [===================>..........] - loss: 3.1060 - acc_top1: 0.0918 - acc_top5: 0.3353 - ETA: 8:15 - 7s/ste

**Comment by iclementine** [comment]
看起来是 数据的问题？

/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/PIL/TiffImagePlugin.py:770: UserWarning: Possibly corrupt EXIF data. Expecting to read 23836229632 bytes but only got 0. Skipping tag 0

否则有什么问题吗？

**Comment by gaorui999** [comment]
> 看起来是 数据的问题？
> 
> /opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/PIL/TiffImagePlugin.py:770: UserWarning: Possibly corrupt EXIF data. Expecting to read 23836229632 bytes but only got 0. Skipping tag 0
> 
> 否则有什么问题吗？
我用了这个代码把数据集里的图片都跑了一遍，然后启动程序后还会报错，请支支招。我的数据集文件夹是这样的

总文件夹---a类

                 -b类

                 -c类
import os
import cv2
import shutil
 
dirName = '/home/aistudio/work/dataset'
# 将dirName路径下的所有文件路径全部存入all_path列表
all_path = []
for root, dirs, files in os.walk(dirName):
        for file in files:
            if "jpeg" in file:
                    all_path.append(os.path.join(root, file))
all_path.sort()
 
bad = []
# 坏图片存放路径
badpath = '/home/aistudio/bad'
 
for i in range(len(all_path)):
    org = all_path[i]
    # print(all_path[i].split('/')[-1])
    try:
        img = cv2.imread(org)
        ss = img.shape
    except:
        bad.append(all_path[i])
        shutil.move(all_path[i],badpath)
        continue
 
print('共有%s张坏图'%(len(bad)))
print(bad)
