### ISSUE TITLE
 多卡训练报错 Socket connect worker 127.0.0.1:52239 failed

### ISSUE THREAD

**Issue by thunder95** [PaddlePaddle/Paddle#31673]
ubuntu1804, 安装最新paddlepaddle-gpu：

安装检查时报： W0316 20:57:03.412691  3827 parallel_executor.cc:596] Cannot enable P2P access from 0 to 1

运行多卡训练时，报:  Socket connect worker 127.0.0.1:52239 failed

**Comment by yaoxuefeng6** [comment]
有更详细的报错信息吗

**Comment by thunder95** [comment]
@yaoxuefeng6 
Python 3.7.10 (default, Feb 26 2021, 18:47:35) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import paddle
/home/server/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/fluid/layers/utils.py:26: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  def convert_to_list(value, n, name, dtype=np.int):
>>> paddle.utils.run_check()
Running verify PaddlePaddle program ... 
W0317 11:00:04.860584 22243 device_context.cc:362] Please NOTE: device: 0, GPU Compute Capability: 7.5, Driver API Version: 11.2, Runtime API Version: 10.2
W0317 11:00:04.865039 22243 device_context.cc:372] device: 0, cuDNN Version: 7.6.
PaddlePaddle works well on 1 GPU.
W0317 11:00:08.012472 22243 parallel_executor.cc:596] Cannot enable P2P access from 0 to 1
W0317 11:00:08.012506 22243 parallel_executor.cc:596] Cannot enable P2P access from 0 to 2
W0317 11:00:08.012514 22243 parallel_executor.cc:596] Cannot enable P2P access from 0 to 3
W0317 11:00:08.012521 22243 parallel_executor.cc:596] Cannot enable P2P access from 1 to 0
W0317 11:00:08.012526 22243 parallel_executor.cc:596] Cannot enable P2P access from 1 to 2
W0317 11:00:08.012531 22243 parallel_executor.cc:596] Cannot enable P2P access from 1 to 3
W0317 11:00:08.012537 22243 parallel_executor.cc:596] Cannot enable P2P access from 2 to 0
W0317 11:00:08.012542 22243 parallel_executor.cc:596] Cannot enable P2P access from 2 to 1
W0317 11:00:08.012545 22243 parallel_executor.cc:596] Cannot enable P2P access from 2 to 3
W0317 11:00:08.012549 22243 parallel_executor.cc:596] Cannot enable P2P access from 3 to 0
W0317 11:00:08.012553 22243 parallel_executor.cc:596] Cannot enable P2P access from 3 to 1
W0317 11:00:08.012557 22243 parallel_executor.cc:596] Cannot enable P2P access from 3 to 2
W0317 11:00:16.603580 22243 fuse_all_reduce_op_pass.cc:79] Find all_reduce operators: 2. To make the speed faster, some all_reduce ops are fused during training, after fusion, the number of all_reduce ops is 2.
PaddlePaddle works well on 4 GPUs.
PaddlePaddle is installed successfully! Let's start deep learning with PaddlePaddle now.

**Comment by thunder95** [comment]
@yaoxuefeng6 我使用的是RTX2080TI， 尝试过重装各种版本的NCCL， CUDNN， PADDLE， 也参照其他issue, export了一些参数，仍旧无法解决多卡使用的问题。网上有说这种显卡不支持p2p access, 麻烦请看一下:

(paddle) server@server:/d/pd_match$ nvidia-smi topo -p2p n
 	GPU0	GPU1	GPU2	GPU3	
 GPU0	X	NS	NS	NS	
 GPU1	NS	X	NS	NS	
 GPU2	NS	NS	X	NS	
 GPU3	NS	NS	NS	X	

Legend:

  X    = Self
  OK   = Status Ok
  CNS  = Chipset not supported
  GNS  = GPU not supported
  TNS  = Topology not supported
  NS   = Not supported
  U    = Unknown

**Comment by Costwen** [comment]
> @yaoxuefeng6 我使用的是RTX2080TI， 尝试过重装各种版本的NCCL， CUDNN， PADDLE， 也参照其他issue, export了一些参数，仍旧无法解决多卡使用的问题。网上有说这种显卡不支持p2p access, 麻烦请看一下:
> 
> (paddle) server@server:/d/pd_match$ nvidia-smi topo -p2p n
> GPU0 GPU1 GPU2 GPU3
> GPU0 X NS NS NS
> GPU1 NS X NS NS
> GPU2 NS NS X NS
> GPU3 NS NS NS X
> 
> Legend:
> 
> X = Self
> OK = Status Ok
> CNS = Chipset not supported
> GNS = GPU not supported
> TNS = Topology not supported
> NS = Not supported
> U = Unknown

想问问题主解决了吗？ 我也遇到了同样的问题
