### ISSUE TITLE
JetsonTX2 paddle-trt无法工作

### ISSUE THREAD

**Issue by tianhechao** [PaddlePaddle/Paddle#31687]
我使用官方提供的Je t s o nTX2 Paddle-inference（c++）库进行测试，测试了Je tPack4.3及Je tPack4.4的版本，

在进行推理时，如果不使用cpu，那么推理可正确输出结果（使用yolov3及ppyolo预训练模型)，如果启用

GPU或同时启用tensorrt，则无法正确输出结果，只启用GPU时，输出错误结果，启用tensorrt时，输出为0。

同时我自行编译了Je tPack4.4版本的paddlepaddle，测试结果与官方提供的库结果相同。

**Comment by iclementine** [comment]
我转问一下预测库的同学

**Comment by wangye707** [comment]
@tianhechao 你好，目前我们排查了一下，tx2的jetpack4.3和4.4系统确实存在问题，在开启GPU后会出现程序直接终止且不报错的情况，经过我们测试，agx xavier, nx，nano设备下，该模型可以正常预测。如果您有其他jetson设备，可以暂时先用其他的设备，我们会尽快定位修复这个问题。

**Comment by wangye707** [comment]
@tianhechao 你好，目前我们排查了一下，tx2的jetpack4.3和4.4系统确实存在问题，在开启GPU后会出现程序直接终止且不报错的情况，经过我们测试，agx xavier, nx设备下，该模型可以正常预测。如果您有其他jetson设备，可以暂时先用其他的设备，我们会尽快定位修复这个问题。

**Comment by LJunius** [comment]
TX2遇到了同样问题，Paddle-Inference-Demo中yolov3例程使用GPU预测无结果

**Comment by tianhechao** [comment]
官方回复的TX2上确实存在问题



***@***.***
 
发件人： LJunius
发送时间： 2021-03-19 16:17
收件人： PaddlePaddle/Paddle
抄送： tianhechao; Mention
主题： Re: [PaddlePaddle/Paddle] JetsonTX2 paddle-trt无法工作 (#31687)
TX2遇到了同样问题，Paddle-Inference-Demo中yolov3例程使用GPU预测无结果

**Comment by lleesg** [comment]
遇到同样问题，请问更新解决了么？

**Comment by shangzhizhou** [comment]
您好，预计2.1.1版本修复（6月底发布）。
预计本周合入develop分支。
