### ISSUE TITLE
CUDA CUDNN自定义安装路径的疑问

### ISSUE THREAD

**Issue by duohappy** [PaddlePaddle/Paddle#31683]
在issue中，讨论CUDA CUDNN安装的问题足够多了，我最近也遇到了这个问题，建议官方梳理一下

系统：Ubuntu 16.04

+ 现实需求

前提：系统中已经有了cuda9.0
目标：不改变原来系统的正常运行，安装cuda10.2 cudnn 7.6.5  nccl 2.7.8到自己的home目录
实现：安装完成后，然后在`.bashrc`中修改 `LD_LIBRARY_PATH`

**结果是，`LD_LIBRARY_PATH`无法生效**

+ 安装路径

其实这个非常让人费解，搜索了大量的issue，发现有些issue中讲了一个原因
**paddle要求，cuda的安装路径必须是 `/usr/local/cuda`**

+ 问题
    + 安装路径必须一定，现阶段有什么改变方法？
    + cuda cudnn nccl都必须安装到  `/usr/local/cuda`？
    + 如果现阶段安装路径不能改变，将来有计划改进么？

+ 相关issue
https://github.com/PaddlePaddle/Paddle/issues/19457
https://github.com/PaddlePaddle/Paddle/issues/21917
https://github.com/PaddlePaddle/Paddle/issues/26954
https://github.com/PaddlePaddle/Paddle/issues/31398
https://github.com/PaddlePaddle/Paddle/issues/31618

**Comment by iclementine** [comment]
是在多卡的训练的情形遇到问题吗？还是说单卡也遇到同样的问题。

其实还真不是在必须在 /usr/local/cuda, 比如说我的机器上
<img width="792" alt="图片" src="https://user-images.githubusercontent.com/16222986/111471054-70dd5e80-8763-11eb-9809-609d118f915f.png">
<img width="890" alt="图片" src="https://user-images.githubusercontent.com/16222986/111471092-7b97f380-8763-11eb-852d-723977b45b47.png">

如果是多卡情况下才会这样，那么可能的原因是环境变量没有传达到各个子进程里。

**Comment by duohappy** [comment]
> 
> 
> 是在多卡的训练的情形遇到问题吗？还是说单卡也遇到同样的问题。
> 
> 其实还真不是在必须在 /usr/local/cuda, 比如说我的机器上
> <img alt="图片" width="792" src="https://user-images.githubusercontent.com/16222986/111471054-70dd5e80-8763-11eb-9809-609d118f915f.png">
> <img alt="图片" width="890" src="https://user-images.githubusercontent.com/16222986/111471092-7b97f380-8763-11eb-852d-723977b45b47.png">
> 
> 如果是多卡情况下才会这样，那么可能的原因是环境变量没有传达到各个子进程里。

单卡训练
paddle版本：2.0.1

paddle在寻找cuda cudnn路径有哪些？
请问你是在哪个路径下？而且`/usr/lib/x86_64-linux-gnu`，好像就是系统的搜索路径吧

**Comment by iclementine** [comment]
/usr/lib/x86_64-linux-gnu 是系统的搜索路径。我的 cudnn 也在这个路径。

cuda cudnn 的 lib 或者 lib64 我也是加入到 LD_LIBRARY_PATH 下的。

**Comment by duohappy** [comment]
> 
> 
> /usr/lib/x86_64-linux-gnu 是系统的搜索路径。我的 cudnn 也在这个路径。
> 
> cuda cudnn 的 lib 或者 lib64 我也是加入到 LD_LIBRARY_PATH 下的。

将cuda cudnn安装到自己的home目录，并加到 LD_LIBRARY_PATH下，paddle无法识别

**Comment by iclementine** [comment]
了解，我们做一个详细测试再给你结论~

**Comment by iclementine** [comment]
另外，你用于配合 cuda 10.2 使用的 paddle 也是最新的用于 10.2 版本的 paddle ?
还有一个做法是，把要加入 LD_LIBRARY_PATH 的路径加入在 PATH 环境变量的最前面，看看是否生效。

**Comment by duohappy** [comment]
> 
> 
> 另外，你用于配合 cuda 10.2 使用的 paddle 也是最新的用于 10.2 版本的 paddle ?

是的 ，通过官方命令安装 `python -m pip install paddlepaddle-gpu==2.0.1 -i https://mirror.baidu.com/pypi/simple`

**Comment by duohappy** [comment]
> 
> 
> 还有一个做法是，把要加入 LD_LIBRARY_PATH 的路径加入在 PATH 环境变量的最前面，看看是否生效。

刚刚我完成了一下测试，请知悉

由于我的系统中存在已经安装的cuda，安装位置 `/usr/local/cuda`，这个是cuda9.0
如果删除，那么将cuda cudnn安装到自己的home目录，并加到 LD_LIBRARY_PATH下，**paddle可以识别**
如果没有删除，将cuda cudnn安装到自己的home目录，并加到 LD_LIBRARY_PATH下，**paddle无法识别**

我得出一个结论：
paddle搜索cuda cudnn的路径应该是优先从`/usr/local/cuda`中搜索，其次是从 `LD_LIBRARY_PATH`搜索

你们测试后，是否有这样的结论？
如果也是这个结论，那么能否从`LD_LIBRARY_PATH`先搜索呢？

**Comment by duohappy** [comment]
@iclementine 请问有测试结果么？

**Comment by duohappy** [comment]
长时间无人回复这个问题，关闭这个issue，如果有人遇到同样的问题，建议重新开一个issue

**Comment by zhhezhhe** [comment]
遇到了同样的问题，怎么解决呢？

**Comment by jacobdang** [comment]
遇到了同样的问题，怎么解决呢？
