### ISSUE TITLE
paddle tensor对numpy floatxx数据类型的支持问题

### ISSUE THREAD

**Issue by lyuwenyu** [PaddlePaddle/Paddle#31693]
- paddle 2.0.x
- cpu / gpu
- ps pytorch 

```
In [103]: x = np.random.choice([1, 2])

In [105]: b[:, :] = x
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-105-a3545eedbfe4> in <module>
----> 1 b[:, :] = x

RuntimeError: Unable to cast Python instance to C++ type (compile in debug mode for details)


In [106]: b[:, :] = 0

In [107]: b
Out[107]: 
Tensor(shape=[2, 3], dtype=float32, place=CPUPlace, stop_gradient=True,
       [[0., 0., 0.],
        [0., 0., 0.]])



In [117]: t = torch.rand(2, 3)

In [118]: t[:, :] = x

In [119]: t
Out[119]: 
tensor([[1., 1., 1.],
        [1., 1., 1.]])


```

**Comment by iclementine** [comment]
目前是不支持

Tensor[:] = ...

这样的方式来将一个 numpy array 赋值给 Tensor 的。你可以先把右侧的 numpy array 转成 paddle 的 tensor. paddle.to_tensor

而且 inplace 赋值的方式目前也会破坏梯度回传，仅在不需要梯度回传的情况下可以这么用(at your own risk)

**Comment by lyuwenyu** [comment]
> 目前是不支持
> 
> Tensor[:] = ...
> 
> 这样的方式来将一个 numpy array 赋值给 Tensor 的。你可以先把右侧的 numpy array 转成 paddle 的 tensor. paddle.to_tensor
> 
> 而且 inplace 赋值的方式目前也会破坏梯度回传，仅在不需要梯度回传的情况下可以这么用(at your own risk)

**Comment by lyuwenyu** [comment]
```
RuntimeError: Unable to cast Python instance to C++ type (compile in debug mode for details)
```

1. b[:, :] = 0 这种方式是可以赋值的， 

2. 上面发生错误 提示信息不太准确吧

**Comment by iclementine** [comment]
>     1. b[:, :] = 0 直接用一个 python 的数值类型这种方式是可以赋值的，

这是一个比较新的 feature. 目前是支持的。

一般情况下，不同的数组库之间也不能互相赋值的。numpy 的 fancy indexing 是一个 numpy 库内部的特征，torch 做了一些特别的处理。tensorflow 甚至不能 inplace assign.

P.S. 了解了，你说的是 numpy 的 scalar 类型和 python native 的数据类型处理方式不同。这个问题确实是目前确认的问题。

**Comment by liym27** [comment]
@lyuwenyu 目前不支持给 Tensor 赋 numpy float 类型的数据。当前支持的类型有：numpy.array, int, float, paddle.Tensor.

**Comment by lyuwenyu** [comment]
@iclementine  @liym27   好的 多谢
