### ISSUE TITLE
Not found CUDA runtime

### ISSUE THREAD

**Issue by Abris-087** [PaddlePaddle/Paddle#31715]
你好，我在公用服务器上安装paddlepaddle-gpu=2.0.1，cuda=10.1时出现了问题。

由于无root权限，所以我在用户目录下安装了cuda和cudnn，路径是/home/xxx/cuda10.1，

并且已在~/.profile中设置了环境变量，用nvcc -V指令也能看出当前cuda的版本号为10.1。

为什么import paddle时一直报错Not found CUDA runtime？
![image](https://user-images.githubusercontent.com/61613537/111592875-50b1ac00-8804-11eb-87b1-6fb6631e55cd.png)

![image](https://user-images.githubusercontent.com/61613537/111593351-ce75b780-8804-11eb-83eb-795a90f9e6be.png)

![image](https://user-images.githubusercontent.com/61613537/111593031-78a10f80-8804-11eb-8c12-e9a72ace5a10.png)

**Comment by Yaoxingtian** [comment]
> 你好，我在公用服务器上安装paddlepaddle-gpu=2.0.1，cuda=10.1时出现了问题。
> 
> 由于无root权限，所以我在用户目录下安装了cuda和cudnn，路径是/home/xxx/cuda10.1，
> 
> 并且已在~/.profile中设置了环境变量，用nvcc -V指令也能看出当前cuda的版本号为10.1。
> 
> 为什么import paddle时一直报错Not found CUDA runtime？
> ![image](https://user-images.githubusercontent.com/61613537/111592875-50b1ac00-8804-11eb-87b1-6fb6631e55cd.png)
> 
> ![image](https://user-images.githubusercontent.com/61613537/111593351-ce75b780-8804-11eb-83eb-795a90f9e6be.png)
> 
> ![image](https://user-images.githubusercontent.com/61613537/111593031-78a10f80-8804-11eb-8c12-e9a72ace5a10.png)

我今天也遇到跟您一樣的問題，我是cuda11.0，paddle2.0.1 的，環境變量也都配置了還是出現這個問題，搞了一天還是不知道怎麼回事。。。

**Comment by AN-ZE** [comment]
import paddle的时候，同样的提示。
使用paddle.utils.run_check()是没有问题的。

**Comment by Abris-087** [comment]
> import paddle的时候，同样的提示。
> 使用paddle.utils.run_check()是没有问题的。

和您不一样，我在测试run_check()时候仍然报错。。
![image](https://user-images.githubusercontent.com/61613537/111598162-e13ebb00-8809-11eb-902a-0ae13dbb0c07.png)

**Comment by wadefelix** [comment]
检查下cuda安装文件夹，cuda安装程序可能没有为其so文件建立短名字软链接。
比如`libcublas.so.11.2.0.252`动态库只建立了`libcublas.so.11`的软链接，而没有建立`libcublas.so`到它的软连接。如
```console
lrwxrwxrwx 1 root root   23 Feb 28 15:03 libcublas.so -> libcublas.so.11.2.0.252
lrwxrwxrwx 1 root root   23 Aug  4  2020 libcublas.so.11 -> libcublas.so.11.2.0.252
-rw-r--r-- 1 root root  93M Aug  4  2020 libcublas.so.11.2.0.252
```

可以使用下面的命令建立这个软链接。如果安装目录为别的目录，请自行修改
```shell
cd /usr/local/cuda/lib64
find lib*.so.* -type f | awk '{short=$1; sub(/\.so.*/,".so",short) ; print $1,short}' |sort -r |uniq -f 1 | xargs -n2 ln -s -f
# 把另外目录的libcdunn的so文件也链接过来
find /usr/lib/x86_64-linux-gnu  -name 'libcud*' -type f | awk '{short=$1; sub(/\.so.*/,".so",short); sub(/.*\//,"",short) ; print $1,short}'|sort -r |uniq -f 1 | xargs -n2 ln -s -f
```

**Comment by Abris-087** [comment]
> 检查下cuda安装文件夹，cuda安装程序可能没有为其so文件建立短名字软链接。
> 比如`libcublas.so.11.2.0.252`动态库只建立了`libcublas.so.11`的软链接，而没有建立`libcublas.so`到它的软连接。如
> 
> ```
> lrwxrwxrwx 1 root root   23 Feb 28 15:03 libcublas.so -> libcublas.so.11.2.0.252
> lrwxrwxrwx 1 root root   23 Aug  4  2020 libcublas.so.11 -> libcublas.so.11.2.0.252
> -rw-r--r-- 1 root root  93M Aug  4  2020 libcublas.so.11.2.0.252
> ```
> 
> 可以使用下面的命令建立这个软链接。如果安装目录为别的目录，请自行修改
> 
> ```shell
> cd /usr/local/cuda/lib64
> find lib*.so.* -type f | awk '{short=$1; sub(/\.so.*/,".so",short) ; print $1,short}' |sort -r |uniq -f 1 | xargs -n2 ln -s -f
> # 把另外目录的libcdunn的so文件也链接过来
> find /usr/lib/x86_64-linux-gnu  -name 'libcud*' -type f | awk '{short=$1; sub(/\.so.*/,".so",short); sub(/.*\//,"",short) ; print $1,short}'|sort -r |uniq -f 1 | xargs -n2 ln -s -f
> ```

这个方法也没有用。

**Comment by Yaoxingtian** [comment]
> > 检查下cuda安装文件夹，cuda安装程序可能没有为其so文件建立短名字软链接。
> > 比如`libcublas.so.11.2.0.252`动态库只建立了`libcublas.so.11`的软链接，而没有建立`libcublas.so`到它的软连接。如
> > ```
> > lrwxrwxrwx 1 root root   23 Feb 28 15:03 libcublas.so -> libcublas.so.11.2.0.252
> > lrwxrwxrwx 1 root root   23 Aug  4  2020 libcublas.so.11 -> libcublas.so.11.2.0.252
> > -rw-r--r-- 1 root root  93M Aug  4  2020 libcublas.so.11.2.0.252
> > ```
> > 
> > 
> > 可以使用下面的命令建立这个软链接。如果安装目录为别的目录，请自行修改
> > ```shell
> > cd /usr/local/cuda/lib64
> > find lib*.so.* -type f | awk '{short=$1; sub(/\.so.*/,".so",short) ; print $1,short}' |sort -r |uniq -f 1 | xargs -n2 ln -s -f
> > # 把另外目录的libcdunn的so文件也链接过来
> > find /usr/lib/x86_64-linux-gnu  -name 'libcud*' -type f | awk '{short=$1; sub(/\.so.*/,".so",short); sub(/.*\//,"",short) ; print $1,short}'|sort -r |uniq -f 1 | xargs -n2 ln -s -f
> > ```
> 
> 这个方法也没有用。

你有問多顯卡嗎 ？

**Comment by Abris-087** [comment]
是多显卡环境，需要更新显卡驱动，配置环境变量到正确的CUDA版本下，并且安装nccl2.x。
