### ISSUE TITLE
编译错误glog中有未定义的引用

### ISSUE THREAD

**Issue by wangleilei001** [PaddlePaddle/Paddle#31724]
- 版本、环境信息：
    1）PaddlePaddle版本：develop分支 
    2）CPU：国产cpu申威，无mkl，使用的cblas
 
    3）系统环境：deepin

有未定义的引用：
../../../../third_party/install/glog/lib/libglog.a(utilities.cc.o)：在函数‘google::DumpStackTraceAndExit()’中：
(.text+0xa4c)：对‘google::glog_internal_namespace_::IsFailureSignalHandlerInstalled()’未定义的引用

查找发现https://github.com/google/glog/blob/master/src/utilities.cc#L145 这里是有个IsFailureSignalHandlerInstalled()函数的引用，这个库关于这个函数应该在这里https://github.com/google/glog/blob/b30a009faa6581b530c5a43779b7ad44d948222a/src/signalhandler.cc#L358 不确定是不是哪里有问题，没有引用到

![image](https://user-images.githubusercontent.com/13131672/111614607-bc9f0f00-881a-11eb-80be-1f88e91f9b9a.png)

**Comment by tianshuo78520a** [comment]
重新make可以解决问题么？
麻烦把gcc版本、cmake命令发下

**Comment by wangleilei001** [comment]
> 重新make可以解决问题么？
> 麻烦把gcc版本、cmake命令发下

gcc是一个国产的版本
Thread model: posix
Version: SWREACH GCC5.3.0-54 (20181101) by xxxxx

cmake 版本
cmake version 3.7.2

CMake suite maintained and supported by Kitware (kitware.com/cmake).

**Comment by wangleilei001** [comment]
已解决

> 重新make可以解决问题么？
> 麻烦把gcc版本、cmake命令发下

**Comment by tianshuo78520a** [comment]
问下 怎么解决的？

**Comment by lijzeng** [comment]
借楼问一下楼主， 我在申威下编译始终都跳转到下载 https://github.com/xianyi/OpenBLAS.git 呢？ 你那里有这个问题么
