### ISSUE TITLE
请问现在paddle有实现MS-SSIM吗？

### ISSUE THREAD

**Issue by a2824256** [PaddlePaddle/Paddle#31720]
请问现在paddle有实现MS-SSIM(多尺度结构相似)的loss吗？因为在文档没有找到。

**Comment by huangjun12** [comment]
目前没有api实现，组合op实现可以参考: https://github.com/PaddlePaddle/PaddleGAN/blob/95e5f4f3f70b734daabb7e94d4dd0c5496fc209c/ppgan/metrics/psnr_ssim.py#L155

**Comment by a2824256** [comment]
已解决
