### ISSUE TITLE
import paddle issues

### ISSUE THREAD

**Issue by Yaoxingtian** [PaddlePaddle/Paddle#31740]
hi, after I installed paddle2.0.1-gpu , and checked it by 'import paddle', problem showed as below : 
envs/paddle/lib/python3.6/site-packages/paddle/utils/cpp_extension/extension_utils.py:461: UserWarning: Not found CUDA runtime, please use `export CUDA_HOME= XXX` to specific it.
  "Not found CUDA runtime, please use `export CUDA_HOME= XXX` to specific it."
>>> 

env: cuda11.0 , ubuntu18 , paddle2.0.1-gpu ,
but I have configured environment of cuda ,  this problem exists still , so confused about this.
could you kindly help to solve it , thanks so much !

**Comment by Aurelius84** [comment]
This is just a warning and `cpp_extension ` is only used for adding custom operator. Do not worry and this has no influence on training. 
Could you run `which nvcc` in your terminal and paste the result for us? We will refine this warning immediately.

**Comment by Aurelius84** [comment]
We fixed this in https://github.com/PaddlePaddle/Paddle/pull/31804

**Comment by Yaoxingtian** [comment]
> This is just a warning and `cpp_extension ` is only used for adding custom operator. Do not worry and this has no influence on training.
> Could you run `which nvcc` in your terminal and paste the result for us? We will refine this warning immediately.

THANK YOU ! nvcc info as below.  Yes, it's just a warning, can be trained successfully . I thought it was a problem before and tried to solve it ... it's ok now!

nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2020 NVIDIA Corporation
Built on Thu_Jun_11_22:26:38_PDT_2020
Cuda compilation tools, release 11.0, V11.0.194
Build cuda_11.0_bu.TC445_37.28540450_0
