### ISSUE TITLE
设置置系统环境变量路径问题

### ISSUE THREAD

**Issue by 60999** [PaddlePaddle/Paddle#31765]
环境:jetson nano jp4.3
请问在源码编译文档中
找到Python lib的路径
$ find `dirname $(dirname $(which python3))` -name "libpython3.6m.so"
/usr/lib/python3.6/config-3.6m-aarch64-linux-gnu/libpython3.6m.so
/usr/lib/aarch64-linux-gnu/libpython3.6m.so
设置系统环境变量路径：
```
export PATH=[python-lib-path]:$PATH
```
然后说 （这里将[python-lib-path]的最后两级目录替换为/bin/)
这是要怎么改，能给个例子吗？

**Comment by 60999** [comment]
Python lib的路径 python-lib-path
$ find `dirname $(dirname $(which python3))` -name "libpython3.6m.so"
/usr/lib/python3.6/config-3.6m-aarch64-linux-gnu/libpython3.6m.so
/usr/lib/aarch64-linux-gnu/libpython3.6m.so

Python Include的路径 python-include-path
$ find `dirname $(dirname $(which python3))`/include -name "python3.6m"
/usr/include/python3.6m
/usr/include/aarch64-linux-gnu/python3.6m

1.设置为如下是否正确呢？
export PYTHON_INCLUDE_DIRS=/usr/include/python3.6m

export PYTHON_LIBRARY=/usr/lib/python3.6/config-3.6m-aarch64-linux-gnu/libpython3.6m.so

export PATH=/usr/lib/python3.6/bin/:$PATH

2.能否源码中自动判断路径

**Comment by cryoco** [comment]
请问您看的是哪个文档呢
