### ISSUE TITLE
raspberrypi 树莓派4B上编译 2.0错误，请问如何处理

### ISSUE THREAD

**Issue by 60999** [PaddlePaddle/Paddle#31764]
为使您的问题得到快速解决，在建立Issue前，请您先通过如下方式搜索是否有相似问题:【搜索issue关键字】【使用labels筛选】【官方文档】

建立issue时，为快速解决问题，请您根据使用情况给出如下信息：
- 标题：请包含关键词“安装错误”/“编译错误”，例如“Mac编译错误”
- 版本、环境信息：
    1）PaddlePaddle版本：请提供您的PaddlePaddle版本号（如1.1）或CommitID
PaddlePaddle 2.0
    2）CPU：请提供CPU型号，MKL/OpenBlas/MKLDNN/等数学库的使用情况
cat /proc/version 
Linux version 5.10.17-v7l+ (dom@buildbot) (arm-linux-gnueabihf-gcc-8 (Ubuntu/Linaro 8.4.0-3ubuntu1) 8.4.0, GNU ld (GNU Binutils for Ubuntu) 2.34) #1403 SMP Mon Feb 22 11:33:35 GMT 2021

$ uname -m && cat /etc/*release
armv7l
PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"
NAME="Raspbian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"

    3）GPU：请提供GPU型号，CUDA和CUDNN版本号
无
    4）系统环境：请说明系统类型、版本（如Mac OS 10.14）、Python版本
注：您可以通过执行[summary_env.py](https://github.com/PaddlePaddle/Paddle/blob/develop/tools/summary_env.py)获取以上信息。
python3 summary_env.py 
summary_env.py:50: DeprecationWarning: dist() and linux_distribution() functions are deprecated in Python 3.5
  plat = platform.linux_distribution()[0]
summary_env.py:51: DeprecationWarning: dist() and linux_distribution() functions are deprecated in Python 3.5
  ver = platform.linux_distribution()[1]
****************************************
Paddle version: None
Paddle With CUDA: None

OS: debian 10.8
Python version: 3.7.3

CUDA version: None
cuDNN version: None.None.None
Nvidia driver version: None
****************************************

- 安装方式信息：
1）pip安装/docker安装
2）本地编译：请提供cmake命令，编译命令
参考 https://www.paddlepaddle.org.cn/install/quick?docurl=/documentation/docs/zh/install/compile/linux-compile.html#anchor-5
版本 2.0.1 linux系统 源码编译 cpu版本
3）docker编译：请提供docker镜像，编译命令            
  特殊环境请注明：如离线安装等
- 复现信息：如为报错，请给出复现环境、复现步骤
- 问题描述：请详细描述您的问题，同步贴出报错信息、日志/代码关键片段

$ cmake .. -DPY_VERSION=3.7  -DWITH_GPU=OFF  -DWITH_TESTING=OFF -DCMAKE_BUILD_TYPE=Release -DCMAKE_SYSTEM_NAME=RPi -DRPI_ARM_NEON=ON -DWITH_C_API=ON -DWITH_PYTHON=ON 
-- Found Paddle host system: RPi, version: 
-- Found Paddle host system's CPU: 4 cores
-- CXX compiler: /usr/bin/c++, version: GNU 8.3.0
-- C compiler: /usr/bin/cc, version: GNU 8.3.0
-- AR tools: /usr/bin/ar
-- Do not have AVX2 intrinsics and disabled MKL-DNN
-- BOOST_VERSION: 1.41.0, BOOST_URL: http://paddlepaddledeps.bj.bcebos.com/boost_1_41_0.tar.gz
-- warp-ctc library: /home/pi/Paddle/build/third_party/install/warpctc/lib/libwarpctc.so
-- Build OpenBLAS by External Project (include: /home/pi/Paddle/build/third_party/install/openblas/include, library: /home/pi/Paddle/build/third_party/install/openblas/lib/libopenblas.a)
-- Protobuf protoc executable: /home/pi/Paddle/build/third_party/install/protobuf/bin/protoc
-- Protobuf-lite library: /home/pi/Paddle/build/third_party/install/protobuf/lib/libprotobuf-lite.a
-- Protobuf library: /home/pi/Paddle/build/third_party/install/protobuf/lib/libprotobuf.a
-- Protoc library: /home/pi/Paddle/build/third_party/install/protobuf/lib/libprotoc.a
-- Protobuf version: 3.1.0
CMake Warning at cmake/flags.cmake:12 (message):
  Found GCC 8.3.0 which is too high, recommended to use GCC 8.2
Call Stack (most recent call first):
  cmake/flags.cmake:30 (CheckCompilerCXX11Flag)
  CMakeLists.txt:276 (include)

-- Paddle version is 0.0.0
CMake Warning at CMakeLists.txt:358 (message):
  On inference mode, will take place some specific optimization.  Turn on the
  ON_INFER flag when building inference_lib only.

-- commit: 25fc2a1fdb
-- branch: develop
-- Configuring done
-- Generating done
-- Build files have been written to: /home/pi/Paddle/build

pi@raspberrypi:~/Paddle/build $ make -j4 
[  0%] Built target extern_openblas
[  0%] Performing build step for 'extern_gloo'
[  1%] Built target extern_cryptopp
[  1%] Performing update step for 'extern_xbyak'
CMake Error at CMakeLists.txt:13 (message):
  Gloo can only be built on 64-bit systems.

-- Configuring incomplete, errors occurred!
See also "/home/pi/Paddle/build/third_party/gloo/src/extern_gloo/gloo/build/CMakeFiles/CMakeOutput.log".
make[2]: *** [CMakeFiles/extern_gloo.dir/build.make:113: third_party/gloo/src/extern_gloo-stamp/extern_gloo-build] Error 1
[  1%] copy_if_different /home/pi/Paddle/build/paddle/fluid/operators/jit/kernels.h
make[1]: *** [CMakeFiles/Makefile2:2523: CMakeFiles/extern_gloo.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[  2%] Performing update step for 'extern_gflags'
-- extern_xbyak update command succeeded.  See also /home/pi/Paddle/build/third_party/xbyak/src/extern_xbyak-stamp/extern_xbyak-update-*.log
[  2%] Built target copy_kernels_command
[  2%] Performing configure step for 'extern_xbyak'
-- extern_gflags update command succeeded.  See also /home/pi/Paddle/build/third_party/gflags/src/extern_gflags-stamp/extern_gflags-update-*.log
[  2%] Performing configure step for 'extern_gflags'
-- extern_xbyak configure command succeeded.  See also /home/pi/Paddle/build/third_party/xbyak/src/extern_xbyak-stamp/extern_xbyak-configure-*.log
[  2%] Performing build step for 'extern_xbyak'
-- extern_gflags configure command succeeded.  See also /home/pi/Paddle/build/third_party/gflags/src/extern_gflags-stamp/extern_gflags-configure-*.log
[  2%] Performing build step for 'extern_gflags'
[  2%] Performing install step for 'extern_xbyak'
[100%] Built target gflags_nothreads_static
[100%] Built target gflags_static
[  2%] Performing install step for 'extern_gflags'
-- extern_xbyak install command succeeded.  See also /home/pi/Paddle/build/third_party/xbyak/src/extern_xbyak-stamp/extern_xbyak-install-*.log
[  2%] Completed 'extern_xbyak'
[  2%] Built target extern_xbyak
-- extern_gflags install command succeeded.  See also /home/pi/Paddle/build/third_party/gflags/src/extern_gflags-stamp/extern_gflags-install-*.log
[  2%] Completed 'extern_gflags'
[  2%] Built target extern_gflags
make: *** [Makefile:130: all] Error 2

make 出错，怎么才能继续编译呢？

**Comment by TronYY** [comment]
怎么都没人回答啊  还说推荐飞桨，别用了得了

**Comment by Shixiaowei02** [comment]
您好，飞桨只支持 64 位操作系统。请在源码编译前阅读文档，谢谢！
https://www.paddlepaddle.org.cn/documentation/docs/zh/install/compile/linux-compile.html
