### ISSUE TITLE
paddlepaddle2.0.0版本PD_PredictorZeroCopyRun函数疑似存在内存泄漏

### ISSUE THREAD

**Issue by weihyemail** [PaddlePaddle/Paddle#31769]
ocr接口调用paddlepaddle时疑似存在内存泄漏，请看一下问题出现在什么地方，谢谢。

1、版本：
paddlepaddle2.0.0、
paddlehub2.0.0
运行的为cpu版本
服务器内存16G
Python版本号3.7
操作系统版本：redhat-7

2、问题现象
a、python单进程调用ocr.recognize_text接口读取指定目录下的100张不同图片进行图片文字识别，每识别一张图片，占用内存增加200M以上，随着识别图片数的增加，内存持续增长，直到内存被耗尽被操作系统kill掉
b、如果只是反复识别同一张图片的话，内存增长的一定数后不再增长

3、疑似内存泄漏的代码
通过代码调用链的分析最终定位到c++库中的PD_PredictorZeroCopyRun函数疑似存在内存泄漏，内存泄漏语句
output_i.shape = new int[output_shape.size()];
此处new分配的内存没有释放
包含PD_PredictorZeroCopyRun函数的源码文件：Paddle/paddle/fluid/inference/capi/pd_predictor.cc

函数调用链:ocr.recognize_text->self._recognize_text->self.rec_predictor.zero_copy_run()->PD_PredictorRun
ocr.recognize_text函数所在文件：.paddlehub/modules/chinese_ocr_db_crnn_server/module.py
self._recognize_text函数所在文件：.paddlehub/modules/chinese_ocr_db_crnn_server/module.py
zero_copy_run函数所在文件：Paddle/paddle/fluid/inference/tests/api/analyzer_capi_tester.cc
PD_PredictorZeroCopyRun函数所在文件：Paddle/paddle/fluid/inference/capi/pd_predictor.cc

4、出现问题的测试代码
import paddlehub as hub
import cv2
import os, sys

ocr = hub.Module(name="chinese_ocr_db_crnn_server")
for i in range(100):
rootdir = '/home/test/img'
list = os.listdir(rootdir)
for i in range(0, len(list)):
f = os.path.join(rootdir, list[i])
res = ocr.recognize_text(images=[cv2.imread(f)])

**Comment by T8T9** [comment]
您好，这个问题正在修复，预计在2.1版本中修复。
@weihyemail

**Comment by weihyemail** [comment]
感谢你的及时解答。2.1版本估计什么时间发布？

**Comment by weihyemail** [comment]
> 感谢你的及时解答。2.1版本估计什么时间发布？



> 您好，这个问题正在修复，预计在2.1版本中修复。
> @weihyemail



> 您好，这个问题正在修复，预计在2.1版本中修复。
> @weihyemail

感谢你的及时解答。2.1版本估计什么时间发布？

**Comment by weihyemail** [comment]
> 您好，这个问题正在修复，预计在2.1版本中修复。
> @weihyemail

感谢你的及时解答。2.1版本估计什么时间发布？

**Comment by T8T9** [comment]
不太确定，可以关注下paddle 官网的通知 https://www.paddlepaddle.org.cn/

**Comment by weihyemail** [comment]
> 不太确定，可以关注下paddle 官网的通知 https://www.paddlepaddle.org.cn/

paddle1.8版本有这个问题吗

**Comment by T8T9** [comment]
> > 不太确定，可以关注下paddle 官网的通知 https://www.paddlepaddle.org.cn/
> 
> paddle1.8版本有这个问题吗

1.8.5 也是稳定版，paddle1.x和paddle2.x的区别参考：https://www.paddlepaddle.org.cn/documentation/docs/zh/guides/01_paddle2.0_introduction/update_cn.html

**Comment by zhanbaohnag** [comment]
请问，我在paddleocr1.1.1，paddlepaddle1.8.5也遇到内存泄漏的问题，现在有解决办法了吗
