### ISSUE TITLE
Why

### ISSUE THREAD

**Issue by airzip** [PaddlePaddle/Paddle#31761]
>>> model.fit(train_loader, test_loader, epochs=1, batch_size=8, verbose=1)
The loss value printed in the log is the current step, and the metric is the average value of previous step.
Epoch 1/1
Traceback (most recent call last):
File "", line 1, in
File "/home/its/.local/lib/python3.7/site-packages/paddle/hapi/model.py", line 1495, in fit
logs = self._run_one_epoch(train_loader, cbks, 'train')
File "/home/its/.local/lib/python3.7/site-packages/paddle/hapi/model.py", line 1802, in _run_one_epoch
data[len(self._inputs):])
File "/home/its/.local/lib/python3.7/site-packages/paddle/hapi/model.py", line 941, in train_batch
loss = self._adapter.train_batch(inputs, labels)
File "/home/its/.local/lib/python3.7/site-packages/paddle/hapi/model.py", line 656, in train_batch
* [to_variable(x) for x in inputs])
File "", line 6, in forward
File "/home/its/.local/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 902, in __call__
outputs = self.forward(*inputs, **kwargs)
File "/home/its/.local/lib/python3.7/site-packages/paddle/nn/layer/common.py", line 137, in forward
x=input, weight=self.weight, bias=self.bias, name=self.name)
File "/home/its/.local/lib/python3.7/site-packages/paddle/nn/functional/common.py", line 1473, in linear
'transpose_Y', False, "alpha", 1)
RuntimeError: (NotFound) Operator matmul does not have kernel for data_type[int]:data_layout[ANY_LAYOUT]:place[CPUPlace]:library_type[PLAIN].
[Hint: Expected kernel_iter != kernels.end(), but received kernel_iter == kernels.end().] (at /paddle/paddle/fluid/imperative/prepared_operator.cc:128)
[operator < matmul > error]

**Comment by LDOUBLEV** [comment]
> (NotFound) Operator matmul does not have kernel for data_type[int]:

Please check your input data type, an error prompts that the input type is int type.  You can try float type input data.

**Comment by airzip** [comment]
> > (NotFound) Operator matmul does not have kernel for data_type[int]:
> 
> Please check your input data type, an error prompts that the input type is int type. You can try float type input data.

features = df[['SEASON','HOLIDAY','WORKINGDAY','WEATHER','TEMP','ATEMP','HUMIDITY','WINDSPEED']].to_numpy(dtype=np.int32)
labels = df[['COUNT']].to_numpy(dtype=np.int16)

ratio = 0.8
train_features,train_labels,test_features,test_labels = (
    features[:int(ratio * df.shape[0])],
    labels[:int(ratio * df.shape[0])],
    features[int(ratio * df.shape[0]):],
    labels[int(ratio * df.shape[0]):],
)


# 定义数据
class BikeSharingDataset(Dataset):
    def __init__(self, data_x, data_y, mode = 'train'):
        super(BikeSharingDataset, self).__init__()
        self.data_x = data_x
        self.data_y = data_y
        self.mode = mode
    def __getitem__(self, idx):
        if self.mode == 'predict':
            return self.data_x[idx]
        else:
            return self.data_x[idx], self.data_y[idx]
    def __len__(self):
        return len(self.data_x)

train_dataset = BikeSharingDataset(train_features, train_labels)

train_dataset.__len__()
for feature, label in train_dataset:
    print(feature.shape, label.shape)
    print(feature, label)
    break
train_loader = paddle.io.DataLoader(train_dataset, batch_size = 128)
for batch_id, data in enumerate(train_loader()):
    x_data = data[0]
    y_data = data[1]

    print(x_data.shape)
    print(y_data.shape)
    break

test_dataset = BikeSharingDataset(test_features, test_labels)
test_dataset.__len__()
test_loader = paddle.io.DataLoader(test_dataset, batch_size = 128)
for batch_id, data in enumerate(test_loader()):
    x_data = data[0]
    y_data = data[1]

    print(x_data.shape)
    print(y_data.shape)
    break

# 模型组网
class LinearRegressorNet(paddle.nn.Layer):
    def __init__(self):
        super(LinearRegressorNet, self).__init__()
        self.fc = paddle.nn.Linear(8, 1, None)

    def forward(self, input):
        pred = self.fc(input)
        return pred

# 训练模型
model = paddle.Model(LinearRegressorNet())
model.prepare(paddle.optimizer.Adam(parameters=model.parameters()),
              paddle.nn.MSELoss())
model.fit(train_loader, test_loader, epochs=1, batch_size=8, verbose=1)

**Comment by LDOUBLEV** [comment]
try:
```
features = df[['SEASON','HOLIDAY','WORKINGDAY','WEATHER','TEMP','ATEMP','HUMIDITY','WINDSPEED']].to_numpy(dtype=np.float32)
```
