### ISSUE TITLE
Jetson nano基于Paddle-Inference-Demo GPU预测`Sync params from CPU to GPU`程序卡住不执行

### ISSUE THREAD

**Issue by Irvingao** [PaddlePaddle/Paddle#31767]
## 
- 版本、环境信息：
    1）PaddlePaddle版本：PaddlePaddle-gpu2.0.0
    2）系统环境：Jetson nano Ubuntu18.04，python3.6.9

- 复现信息：如为报错，请给出复现环境、复现步骤

- 问题描述：请详细描述您的问题，同步贴出报错信息、日志/代码关键片段
### （1）GPU预测程序卡住不执行
![image](https://user-images.githubusercontent.com/58903762/111900822-9e7e1c80-8a6f-11eb-8c1f-f0b65a976e5f.png)
### （2）CPU预测正常
![image](https://user-images.githubusercontent.com/58903762/111900933-25cb9000-8a70-11eb-8a43-0eb33deea3bc.png)

尝试了多个demo，均是这样。

**Comment by cryoco** [comment]
您好，感谢您的反馈，我们复现看下这个问题

**Comment by Irvingao** [comment]
yolov3执行也相同，cuda_linux使用GPU预测正常。

**Comment by wangye707** [comment]
@Irvingao 你好，目前发现jetson在nano和tx2两款设备在开启GPU预测时会出现预测问题，经过我们测试，agx xavier, nx设备下，该模型可以正常预测，其中nx设备需要手动设置 config.enable_use_gpu(500, 0)。如果您有其他jetson设备，可以暂时先用其他的设备，我们会尽快定位修复这个问题。

**Comment by Irvingao** [comment]
@wangye707 你好，请问是否修复该问题？修复后能否在这里通知一下，感谢！

**Comment by wangye707** [comment]
@Irvingao 暂时还没修复，修复后我来回复你

**Comment by Irvingao** [comment]
我在JetPack 4.4.1的版本上，agx xavier报错Segmentation fault：
![image](https://user-images.githubusercontent.com/58903762/112293585-43e1fc00-8ccd-11eb-8538-338449949a05.png)

**Comment by Irvingao** [comment]
@wangye707 请问修复了吗？

**Comment by QQ39272490** [comment]
楼上的你的问题解决了吗？我也一直卡在这里用不了GPU

**Comment by wangye707** [comment]
@Irvingao @QQ39272490 最新的V2.1.1版本已经修复了此问题。

**Comment by QQ39272490** [comment]
@Irvingao 方便加你个QQ或微信吗？

**Comment by QQ39272490** [comment]
@wangye707 有试过mobileNet吗？我用的MobileNewV1跟你以上的情况一样
https://github.com/PaddlePaddle/Paddle/issues/33910

**Comment by wangye707** [comment]
@QQ39272490  我这边复现了一下，MobileNetV1、MobileNetV2、MobileNetV3系列均可以正常推理。jetson nano因为性能原因，可能需要swap内存。我这边swap了10G，官网链接：https://paddleinference.paddlepaddle.org.cn/user_guides/source_compile.html
![image](https://user-images.githubusercontent.com/39162106/124411756-bb6d0000-dd7f-11eb-985c-8c3043185d18.png)

**Comment by QQ39272490** [comment]
@wangye707 感谢解答，可能是内存原因，一执行GPU我的GUI界面就提示内存低。

**Comment by QQ39272490** [comment]
我用的是nano 2G 版本

**Comment by Irvingao** [comment]
> @Irvingao @QQ39272490 最新的V2.1.1版本已经修复了此问题。
我在安装成功了paddlepaddle2.1.1版本的whl后，
python3`import paddle`报错：

![image](https://user-images.githubusercontent.com/58903762/125055589-f356a900-e0d9-11eb-8595-289304e20a3f.png)

**Comment by QQ39272490** [comment]
你这安装的版本是不是不对呀

**Comment by QQ39272490** [comment]
我用mobileNetV1跑起来了，GPU比CPU差不多提速6倍

**Comment by Irvingao** [comment]
这是我安装的版本：
请问有什么问题呢？
![image](https://user-images.githubusercontent.com/58903762/125056251-a0c9bc80-e0da-11eb-952c-81a88801618c.png)

**Comment by Irvingao** [comment]
@QQ39272490 
我的nano 版本型号如下：
![image](https://user-images.githubusercontent.com/58903762/125056397-c656c600-e0da-11eb-87d5-dd1a2934ba84.png)

**Comment by QQ39272490** [comment]
这版本也应该 没有问题，我后面装的maxwell

**Comment by Irvingao** [comment]
@wangye707 

### Jetson nano环境配置和whl如上，请问这是什么问题呢？
![image](https://user-images.githubusercontent.com/58903762/125091092-b18e2880-e102-11eb-8270-e059ee48f4e9.png)

**Comment by Irvingao** [comment]
上述问题已解决，同时完整部署流程和问题解决方式已记录为博客：https://blog.csdn.net/qq_45779334/article/details/118611953
