### ISSUE TITLE
发现paddle.to_tensor的一个bug

### ISSUE THREAD

**Issue by btobab** [PaddlePaddle/Paddle#31760]
1）PaddlePaddle版本：2.0.1
2）系统环境：aistudio
我在复现经典gan的时候发现，程序卡死在paddle.to_tensor(x) 这一句，并造成aistudio网页崩溃。仔细观察发现x是[  tensor()  ]，也就是列表加tensor，但是无法转换成tensor，并且无报错，只是卡死，不管是aistudio还是本地都是卡死，无报错，望修改此bug

**Comment by LDOUBLEV** [comment]
我这边测试是有报错信息的：
paddlepaddle-gpu==2.0.1版本
![image](https://user-images.githubusercontent.com/26592129/111932501-80a8ca00-8af8-11eb-9b7d-0b0c84a6a461.png)


```
    import paddle
    import numpy as np 
    a = np.array([1,2,3])
    print(paddle.__version__)
    b = paddle.to_tensor(a)
    c = paddle.to_tensor([b])
```
不过报错信息不是很对，会反馈问题进一步优化

**Comment by btobab** [comment]
好的，谢谢
