### ISSUE TITLE
paddle2.0如何自定义反向传播算法(backward)?

### ISSUE THREAD

**Issue by youlingforever0328** [PaddlePaddle/Paddle#31778]
paddle2.0(或以前版本) 如何自定义反向传播算法(backward)?
具体地说，如何自定义flatten层的backward?

**Comment by wangxicoding** [comment]
请问是需要自定义算子，还是说针对已有前向，自定义特殊反向。
如果是自定义算子，可以查看文档https://www.paddlepaddle.org.cn/documentation/docs/zh/guides/07_new_op/new_custom_op.html
https://www.paddlepaddle.org.cn/documentation/docs/zh/guides/07_new_op/new_python_op.html
