### ISSUE TITLE
paddle.load 和 paddle.save 支持更多的类型

### ISSUE THREAD

**Issue by ShaneTian** [PaddlePaddle/Paddle#31772]
- 版本、环境信息
1）PaddlePaddle版本：2.0
2）CPU/GPU：N/A
3）系统环境：N/A
- 复现信息：N/A
- 建议描述：目前仅支持存储 Layer 或者 Optimizer 的 state_dict。建议类似于 PyTorch 一样支持多种格式，比如 `paddle.io.Dataset` 等

**Comment by hbwx24** [comment]
感谢您宝贵的建议，我们将逐步丰富paddle.load和paddle.save的功能。
