### ISSUE TITLE
paddle.fluid.profiler.profiler使用问题

### ISSUE THREAD

**Issue by wsy1991** [PaddlePaddle/Paddle#31787]
https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/fluid/profiler/profiler_cn.html#profiler
此链接中的例子中：

data为啥不是四维数组，没有batch_size啊

**Comment by wangxicoding** [comment]
里面的例子只是用于性能profile的示例，写例子时可能没有按照具体模型来写，只是按照简单原则写的。data三维或者四维，对于profile的api使用没有影响。
另外性能优化profile可以参考timeline工具https://www.paddlepaddle.org.cn/documentation/docs/zh/1.8/advanced_guide/performance_improving/analysis_tools/timeline_cn.html#timeline

**Comment by wsy1991** [comment]
@wangxicoding 有影响的，四维的话，会报如下错:
Error Message Summary:
----------------------
InvalidArgumentError: The input's dimension and filter's dimension of Op(Conv) should be equal. But received: the input's shape is [-1, 300, 3, 28, 28], the input's dimension is 5; the filter's shape is [20, 300, 3, 3],  the filter's dimension is 4.
  [Hint: Expected in_dims.size() == filter_dims.size(), but received in_dims.size():5 != filter_dims.size():4.] at (/home/teamcity/work/ef54dc8a5b211854/paddle/fluid/operators/conv_op.cc:68)
  [operator < conv2d > error]

**Comment by wangxicoding** [comment]
fluid.layer.data这个接口如果shape首位未设置为None或者-1，会自动给shape首位插入-1。
所以`data = fluid.layers.data(name='data', shape=[3, 28, 28], dtype='float32')`与`data = fluid.layers.data(name='data', shape=[-1, 3, 28, 28], dtype='float32')`是等价的。
目前静态图上不建议用fluid.layers.data的接口，1.8建议用`fluid.data`的接口https://www.paddlepaddle.org.cn/documentation/docs/zh/1.8/api_cn/fluid_cn/data_cn.html#data
2.0建议用`paddle.static.data`的接口https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/static/input/data_cn.html#data
```python
import paddle.fluid as fluid
import paddle.fluid.profiler as profiler
import numpy as np

epoc = 8
dshape = [4, 3, 28, 28]
data = fluid.layers.data(name='data', shape=[-1, 3, 28, 28], dtype='float32')
conv = fluid.layers.conv2d(data, 20, 3, stride=[1, 1], padding=[1, 1])

place = fluid.CPUPlace()
exe = fluid.Executor(place)
exe.run(fluid.default_startup_program())

with profiler.profiler('CPU', 'total', '/tmp/profile') as prof:
    for i in range(epoc):
        input = np.random.random(dshape).astype('float32')
        exe.run(fluid.default_main_program(), feed={'data': input})
```

**Comment by wsy1991** [comment]
@wangxicoding 好滴谢谢了，问题解决了。
可是这个性能分析工具是按照每个op操作进行归类的啊

**Comment by wangxicoding** [comment]
> @wangxicoding 好滴谢谢了，问题解决了。
> 可是这个性能分析工具是按照每个op操作进行归类的啊

是的，在python层的layer实际上是由各个op组成的，最终在C++执行的是各个op，所以在性能profile时，也是对op的profile

**Comment by wsy1991** [comment]
@wangxicoding 好的吧，感谢了，我看了下timeline工具，也没看出来从哪里能提升性能啊，感觉就是一个简单的分析工具

**Comment by wsy1991** [comment]
> > @wangxicoding 好滴谢谢了，问题解决了。
> > 可是这个性能分析工具是按照每个op操作进行归类的啊
> 
> 是的，在python层的layer实际上是由各个op组成的，最终在C++执行的是各个op，所以在性能profile时，也是对op的profile

**Comment by wangxicoding** [comment]
> @wangxicoding 好的吧，感谢了，我看了下timeline工具，也没看出来从哪里能提升性能啊，感觉就是一个简单的分析工具

单纯一个简单的网络模型可能很难看出来，瓶颈都在计算里面，这个很难优化。
但如果reader性能存在瓶颈，就可以看到每个step间有一个较大的空白gap，这是通过timeline就可以很容易看出来，需要优化reader的速度。
另外跑分布式，如果通信时间很长，也可以通过timeline看出来，需要考虑使用某些优化手段。比如如果本身带宽低，可以使用dgc、local sgd或者gradient merge这样的策略，或者使用amp也可以带来加速。
