### ISSUE TITLE
model.predict()预测报错

### ISSUE THREAD

**Issue by jiushinakecai** [PaddlePaddle/Paddle#31785]
预测数据不管有多少条，预测到最后两条的时候，就报错：AttributeError: 'Model' object has no attribute '_metrics'
_注_：训练的时候，metric未设置（model.prepare(optimizer, loss)），跟这个有关系吗
**环境信息：**paddle2.0.1  python3.7
![image](https://user-images.githubusercontent.com/60872522/111983630-503b4d00-8b45-11eb-9cc5-2f716d874115.png)

**Comment by jiushinakecai** [comment]
我是提交后台任务进行训练的，完成后导入notebook，加载训练好的模型进行预测就会出现这样的情况，同样的代码，如果不放后台任务，notebook中直接跑就没事

**Comment by wangxicoding** [comment]
看了下代码，如果没有调用prepare()接口不会初始化_metrics。你可以试一下先调用model.prepare()，不用加参数，把这个问题绕过一下。

**Comment by jiushinakecai** [comment]
> 看了下代码，如果没有调用prepare()接口不会初始化_metrics。你可以试一下先调用model.prepare()，不用加参数，把这个问题绕过一下。

好的

**Comment by jiushinakecai** [comment]
> 看了下代码，如果没有调用prepare()接口不会初始化_metrics。你可以试一下先调用model.prepare()，不用加参数，把这个问题绕过一下。

是的，先model.prepare()再model.load()就不报错了，谢谢
