### ISSUE TITLE
Load symbol getPluginRegistry failed 

### ISSUE THREAD

**Issue by Yaoxingtian** [PaddlePaddle/Paddle#31795]
您好！
我在执行预测的时候报错：Load symbol getPluginRegistry failed

paddlepaddle2.0  cuda10.1 cudnn7.6 没用trt

请问能定位是什么问题吗？ 谢谢

**Comment by JZ-LIANG** [comment]
请贴 复现环境 和 具体报错信息
并使用如下 env 打开c++ 报错栈信息：
export FLAGS_call_stack_level=2

**Comment by Yaoxingtian** [comment]
我的环境是：win10， cuda10.1，cudnn7.6， paddlepaddle 2.0 .1release， paddleDetection2.0

我在部署ppyolo的时候，用vs2017，cmake3.17.5，成功编译生成可执行文件main.exe后，运行main.exe报错：Load symbol getPluginRegistry failed
并弹出：应用程序无法正常启动0xc0000142。 我在cmake编译的时候并没有用cuda和cudnn，也没用tensorrt。
搞了很久，不知道是什么问题，麻烦了！


[cid:d7042feb-22bb-42c4-a9ba-9e7e1ed3937c]


发送自 Outlook<http://aka.ms/weboutlook>

________________________________
发件人: JZ-LIANG ***@***.***>
发送时间: 2021年3月23日 3:54
收件人: PaddlePaddle/Paddle ***@***.***>
抄送: Yaoxingtian ***@***.***>; Author ***@***.***>
主题: Re: [PaddlePaddle/Paddle] Load symbol getPluginRegistry failed (#31795)


请贴 复现环境 和 具体报错信息

―

**Comment by Yaoxingtian** [comment]
> 请贴 复现环境 和 具体报错信息
> 并使用如下 env 打开c++ 报错栈信息：
> export FLAGS_call_stack_level=2

麻烦帮忙解答一下，谢谢

**Comment by Bazenr** [comment]
我也有同样的问题，我的环境是：win10， cuda11.0/11.1，cudnn8.0， paddlepaddle 2.0 .1release
用Cmake编译完后运行main.exe报错：Load symbol getPluginRegistry failed
弹出：应用程序无法正常启动0xc0000142。请点击"确定"关闭应用程序。

输出代码如下：
You are using Paddle compiled with TensorRT, but TensorRT dynamic library is not found. Ignore this if TensorRT is not needed.
WARNING: Logging before InitGoogleLogging() is written to STDERR
E0405 11:46:05.512908 24584 port.h:50] Load symbol getPluginRegistry failed.

**Comment by Bazenr** [comment]
> 我也有同样的问题，我的环境是：win10， cuda11.0/11.1，cudnn8.0， paddlepaddle 2.0 .1release
> 用Cmake编译完后运行main.exe报错：Load symbol getPluginRegistry failed
> 弹出：应用程序无法正常启动0xc0000142。请点击"确定"关闭应用程序。
> 
> 输出代码如下：
> You are using Paddle compiled with TensorRT, but TensorRT dynamic library is not found. Ignore this if TensorRT is not needed.
> WARNING: Logging before InitGoogleLogging() is written to STDERR
> E0405 11:46:05.512908 24584 port.h:50] Load symbol getPluginRegistry failed.

我的问题解决了，装好对应的TensorRT就可以预测了

**Comment by davidten0921** [comment]
> > 我也有同样的问题，我的环境是：win10， cuda11.0/11.1，cudnn8.0， paddlepaddle 2.0 .1release
> > 用Cmake编译完后运行main.exe报错：Load symbol getPluginRegistry failed
> > 弹出：应用程序无法正常启动0xc0000142。请点击"确定"关闭应用程序。
> > 输出代码如下：
> > You are using Paddle compiled with TensorRT, but TensorRT dynamic library is not found. Ignore this if TensorRT is not needed.
> > WARNING: Logging before InitGoogleLogging() is written to STDERR
> > E0405 11:46:05.512908 24584 port.h:50] Load symbol getPluginRegistry failed.
> 
> 我的问题解决了，装好对应的TensorRT就可以预测了

請問一下該怎安裝TensorRT呢?

**Comment by Bazenr** [comment]
直接搜索引擎里搜TensorRT安装，就有教程，然后TensorRT需要去NVIDIA官网注册账号然后下载，注意下载的TensorRT要对应自己的CUDA和CUDNN版本

**Comment by Bazenr** [comment]
> > > 我也有同样的问题，我的环境是：win10， cuda11.0/11.1，cudnn8.0， paddlepaddle 2.0 .1release
> > > 用Cmake编译完后运行main.exe报错：Load symbol getPluginRegistry failed
> > > 弹出：应用程序无法正常启动0xc0000142。请点击"确定"关闭应用程序。
> > > 输出代码如下：
> > > You are using Paddle compiled with TensorRT, but TensorRT dynamic library is not found. Ignore this if TensorRT is not needed.
> > > WARNING: Logging before InitGoogleLogging() is written to STDERR
> > > E0405 11:46:05.512908 24584 port.h:50] Load symbol getPluginRegistry failed.
> > 
> > 
> > 我的问题解决了，装好对应的TensorRT就可以预测了
> 
> 請問一下該怎安裝TensorRT呢?

直接搜索引擎里搜TensorRT安装，就有教程，然后TensorRT需要去NVIDIA官网注册账号然后下载，注意下载的TensorRT要对应自己的CUDA和CUDNN版本
