### ISSUE TITLE
车牌识别案例，如果换一张车牌图片测试，图片预处理那里会报错

### ISSUE THREAD

**Issue by gzwzzu** [PaddlePaddle/Paddle#31799]
环境：直接在aistudio上使用paddle 1.7版本，python 3.7
项目地址：https://aistudio.baidu.com/aistudio/projectdetail/879784?channelType=0&channel=0

第5部分，5.1那里。用cv2进行预处理。
当换一张测试图片，像素尺寸完全一样，却会报错。
Traceback (most recent call last)<ipython-input-24-d3665a3e6616> in <module>
     20     else:
     21         index = i + 1
---> 22         while result[index] != 0:
     23             index += 1
     24         character_dict[num] = [i, index-1]
IndexError: list index out of range

所用图片如下。
<img width="361" alt="chepai1" src="https://user-images.githubusercontent.com/76900535/112095635-cd170700-8bd7-11eb-9c8d-214eada90f91.png">

**Comment by JZ-LIANG** [comment]
贴一下复现代码 和 具体报错信息

**Comment by gzwzzu** [comment]
> 贴一下复现代码 和 具体报错信息

代码是：

#对车牌图片进行处理，分割出车牌中的每一个字符并保存
license_plate = cv2.imread('work/车牌.png')
gray_plate = cv2.cvtColor(license_plate, cv2.COLOR_RGB2GRAY) 
ret, binary_plate = cv2.threshold(gray_plate, 175, 255, cv2.THRESH_BINARY) #ret：阈值，binary_plate：根据阈值处理后的图像数据
#按列统计像素分布
result = []
for col in range(binary_plate.shape[1]):
    result.append(0)
    for row in range(binary_plate.shape[0]):
        result[col] = result[col] + binary_plate[row][col]/255
#print(result)
#记录车牌中字符的位置
character_dict = {}
num = 0
i = 0
while i < len(result):
    if result[i] == 0:
        i += 1
    else:
        index = i + 1
        while result[index] != 0:
            index += 1
        character_dict[num] = [i, index-1]
        num += 1
        i = index
#print(character_dict)        
#将每个字符填充，并存储
characters = []
for i in range(8):
    if i==2:
        continue
    padding = (170 - (character_dict[i][1] - character_dict[i][0])) / 2
    #将单个字符图像填充为170*170
    ndarray = np.pad(binary_plate[:,character_dict[i][0]:character_dict[i][1]], ((0,0), (int(padding), int(padding))), 'constant', constant_values=(0,0))
    ndarray = cv2.resize(ndarray, (20,20))
    cv2.imwrite('work/' + str(i) + '.png', ndarray)
    characters.append(ndarray)
    
def load_image(path):
    img = paddle.dataset.image.load_image(file=path, is_color=False)
    img = img.astype('float32')
    img = img[np.newaxis, ] / 255.0
    return img

报错信息是：
Traceback (most recent call last) in
20 else:
21 index = i + 1
---> 22 while result[index] != 0:
23 index += 1
24 character_dict[num] = [i, index-1]
IndexError: list index out of range
