### ISSUE TITLE
我看了下timeline工具，感觉对性能提升并没有帮助啊

### ISSUE THREAD

**Issue by wsy1991** [PaddlePaddle/Paddle#31809]

**Comment by wsy1991** [comment]
profile了模型，也知道模型所有op的耗时情况，可我现在如何调优呢

**Comment by JZ-LIANG** [comment]
可以自己找一下nv 相关教程

**Comment by wsy1991** [comment]
> 可以自己找一下nv 相关教程

不是，我是cpu端

**Comment by JZ-LIANG** [comment]
timeline 并结合如下参考：
https://www.paddlepaddle.org.cn/documentation/docs/zh/1.8/advanced_guide/performance_improving/multinode_training_improving/cpu_train_best_practice.html

**Comment by wsy1991** [comment]
> https://www.paddlepaddle.org.cn/documentation/docs/zh/1.8/advanced_guide/performance_improving/multinode_training_improving/cpu_train_best_practice.html

这是训练啊，我是想提升推理阶段的性能

**Comment by AIpioneer** [comment]
profile是用来进行分析的，如果你已经知道那一部分耗时比较严重，就要考虑从网络设计上进行设计，尝试做一些改进，这个不是通过proflie或者和timeline能够做的。
