### ISSUE TITLE
Question about L2regularizer and L1regularizer implementations

### ISSUE THREAD

**Issue by andreazanetti** [PaddlePaddle/Paddle#31825]
Hi, I am trying to understand the implementation related to L2regularization as I would like to contribute with a different form of regularization suitable for QAT-training. Please see [#28522](https://github.com/PaddlePaddle/Paddle/issues/28522) 

Let's consider L2 regularization: according to documentation L2 regularization for a param is computed like L2reg = 0.5 * reg_coeff * reduce_sum(param^2 <-el_wise). 
Here is the relevant [documentation](https://www.paddlepaddle.org.cn/documentation/docs/en/api/paddle/regularizer/L2Decay_en.html)
 
However, when I look at the code and related comments I find: https://github.com/PaddlePaddle/Paddle/blob/f3b0f8db0a8f95c8e268cf8a041419a0acba8a3b/python/paddle/fluid/regularizer.py#L147 I see that it is computed  using something that reminds me kind of the derivative of the expected formula for it.

A similar doubt I have also for L1Decay/Regularizer at https://github.com/PaddlePaddle/Paddle/blob/f3b0f8db0a8f95c8e268cf8a041419a0acba8a3b/python/paddle/fluid/regularizer.py#L254
I assume I am missing something simple here but could you clarify this doubt?
thanks!!

**Comment by lidanqing-vv** [comment]
@juncaipeng Hi, Please help check this issue

**Comment by lidanqing-vv** [comment]
Hi @juncaipeng , Andrea的意思是

**文档描述的L1Decay公式和实现不一样。** 代码实现的L1Decay是简单的计算，没有square和reduce_mean。**现在他的regularizer需要square和reduce_mean，他不知道是要自己实现新op还是怎么样。**

**1. Paddle文档中描述了L1Decay 会实现公式如下：**

![image](https://user-images.githubusercontent.com/47151829/114554884-75fcd300-9c67-11eb-9ac2-1b77f63d2247.png)

**2. 而代码中的实际计算是**
![image](https://user-images.githubusercontent.com/47151829/114647158-eabe2480-9cdc-11eb-83d8-1815a5adf3fc.png)

**Comment by juncaipeng** [comment]
@lidanqing-intel @andreazanetti 

我理解是：

L2正则的损失函数是 
![image](https://user-images.githubusercontent.com/52520497/114710005-d3744b00-9d5f-11eb-9bfc-cfbc0acc6e08.png)

对损失函数求导后
![image](https://user-images.githubusercontent.com/52520497/114710065-e424c100-9d5f-11eb-8ce7-43bee28608fa.png)

梯度更新是
![image](https://user-images.githubusercontent.com/52520497/114710108-edae2900-9d5f-11eb-9ff2-883c9e891819.png)

在paddle中应该已经对n求均值了，所以正则带来的梯度更新是`coff*w`。

可以看下 https://github.com/PaddlePaddle/Paddle/blob/f3b0f8db0a8f95c8e268cf8a041419a0acba8a3b/python/paddle/fluid/regularizer.py#L68

**Comment by andreazanetti** [comment]
Thank you Juncai, this is what I imagined but I could not found confirmation. Apologies for not seeing the comment [here](https://github.com/PaddlePaddle/Paddle/blob/87852616aaf2517567a68d6b7dd5a61ab3857380/python/paddle/fluid/regularizer.py#L113) which actually explains this well. My bad.
All this, however, also implies that any reguliarzier that is more complex than L1/L2, and for which the derivative of it wrt the weigths is more complex than just a multiplication for a factor, cannot be easily implemented in the same way L1/L2 regularizers are implemented in Paddle. So I guess we need to devise a different route for supporting Kurtosis regularizer ([ref.](https://github.com/PaddlePaddle/Paddle/issues/28522) )
