### ISSUE TITLE
NVIDIA Jetson AGX Xavier JetPack4.3安装paddle gpu whl报错：Illegal instruction (core dumped)

### ISSUE THREAD

**Issue by Irvingao** [PaddlePaddle/Paddle#31856]
- 版本、环境信息：
    1）PaddlePaddle版本：Paddlepaddle2.0.0-gpu（直接安装官方编译好的whl）
    2）系统环境：NVIDIA Jetson AGX Xavier JetPack4.3 Ubuntu18.04、Python3.6.9

- 安装方式信息：
1）pip安装官方whl
![image](https://user-images.githubusercontent.com/58903762/112402413-7597a900-8d47-11eb-8a47-84d17820b598.png)

- 复现信息：如为报错，请给出复现环境、复现步骤
![image](https://user-images.githubusercontent.com/58903762/112401910-77ad3800-8d46-11eb-833a-e130465d27a2.png)

**Comment by Irvingao** [comment]
在 JetPack4.4.1中安装Paddlepaddle2.0.0-gpu成功，但是运行Paddle-Inference-Demo/python/run_demo.sh，到yolov3处报错如下：
![image](https://user-images.githubusercontent.com/58903762/112402535-ae378280-8d47-11eb-9e4d-76906dd98604.png)

**Comment by wangye707** [comment]
> * 版本、环境信息：
>      1）PaddlePaddle版本：Paddlepaddle2.0.0-gpu（直接安装官方编译好的whl）
>      2）系统环境：NVIDIA Jetson AGX Xavier JetPack4.3 Ubuntu18.04、Python3.6.9
> * 安装方式信息：
>   1）pip安装官方whl
>   ![image](https://user-images.githubusercontent.com/58903762/112402413-7597a900-8d47-11eb-8a47-84d17820b598.png)
> * 复现信息：如为报错，请给出复现环境、复现步骤
>   ![image](https://user-images.githubusercontent.com/58903762/112401910-77ad3800-8d46-11eb-833a-e130465d27a2.png)

Jetpack4.3系统的第三方依赖库numpy是有点问题的，你试下 import numpy会不会出问题？

**Comment by wangye707** [comment]
@Irvingao 上面Jetpack4.3系统的numpy问题解决方法：
python3 -m pip  install numpy==1.18.3 -i https://mirror.baidu.com/pypi/simple，或者用其他方法安装1.18.3版本的numpy,1.18.5

**Comment by Irvingao** [comment]
@wangye707 我现在已经将板子刷成了4.4.4版本。
我依然使用官方编译好的whl。
请问JetPack 4.4.1 GPU预测 Segement fault这个是因为CUDA、cudnn版本问题无法正常使用？

**Comment by pangyoki** [comment]
请问执行`paddle.utils.run_check()`有问题吗？

**Comment by Irvingao** [comment]
@pangyoki 执行`import paddle`就会崩溃，还没到`paddle.utils.run_check()`这一步呢。

**Comment by wangye707** [comment]
@Irvingao  你import  numpy呢？

**Comment by Irvingao** [comment]
@wangye707
### `import numpy`报错：

![image](https://user-images.githubusercontent.com/58903762/112455397-a3efa580-8d94-11eb-84e8-1d2aa4a4d7c6.png)

### `python3 -m pip install numpy==1.18.3 -i https://mirror.baidu.com/pypi/simple`后，安装paddle-gpu成功，`import paddle`无报错。

![image](https://user-images.githubusercontent.com/58903762/112459037-5bd28200-8d98-11eb-8a71-6a5ab7716f98.png)

**Comment by Irvingao** [comment]
我可否重装一个python3.6.9再下载numpy呢？

**Comment by Irvingao** [comment]
问题解决，安装numpy==1.18.3即可。
