### ISSUE TITLE
持续打印warning信息，疑似包冲突

### ISSUE THREAD

**Issue by chenwthu** [PaddlePaddle/Paddle#31862]
ubuntu 18.04.1
paddlepaddle-gpu 2.0.1
python 3.8.0

同时导入paddle和ray时，终端每隔1秒打印一条log，如图
![image](https://user-images.githubusercontent.com/16147671/112423034-d84f6b80-8d6c-11eb-8394-377a147d35f0.png)

复现代码
```py
import paddle, ray
while True:
    pass
```

**Comment by pangyoki** [comment]
收到，已复现该问题，感谢你的反馈，我们排查下具体原因。
请问这个问题对你使用paddle有什么影响吗？

**Comment by chenwthu** [comment]
出现过一次程序卡住的情况，不确定是否是该问题引起的

**Comment by chenwthu** [comment]
另外，在断点调试时也会持续打印log，这个影响比较大
