### ISSUE TITLE
windows下编译推测库文档问题

### ISSUE THREAD

**Issue by duohappy** [PaddlePaddle/Paddle#31880]
参考[安装与编译 Windows 预测库](https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/guides/05_inference_deployment/inference/windows_cpp_inference.html)

这份文档里，我发现有1个问题，提出来大家一起讨论下

文档中有一句话
 `# Windows默认使用 /MT 模式进行编译，如果想使用 /MD 模式，请使用以下命令。如不清楚两者的区别，请使用上面的命令`

现在的windows下，很少用/MT模型进行编译了，一般的开源库，都是默认用/MD模式进行编译的。
官方是不是应该推荐使用/MD，而不是/MT呢？

``` bash
cmake .. -G "Visual Studio 14 2015" -A x64 -T host=x64 -DCMAKE_BUILD_TYPE=Release -DWITH_MKL=ON -DWITH_GPU=OFF -DON_INFER=ON -DWITH_PYTHON=OFF

# Windows默认使用 /MT 模式进行编译，如果想使用 /MD 模式，请使用以下命令。如不清楚两者的区别，请使用上面的命令
cmake .. -G "Visual Studio 14 2015" -A x64 -T host=x64 -DCMAKE_BUILD_TYPE=Release -DWITH_MKL=ON -DWITH_GPU=OFF -DON_INFER=ON -DWITH_PYTHON=OFF -DMSVC_STATIC_CRT=OFF
```

**Comment by wanghuancoder** [comment]
Paddle作为深度学习框架，需要考虑多种环境下的运行兼容性问题。/MT 模式不依赖系统中是否有相应的DLL文件。否则，使用/MD 可能会出现因缺少DLL，Paddle在部分机器上无法正常运行的问题。

**Comment by duohappy** [comment]
> 
> 
> Paddle作为深度学习框架，需要考虑多种环境下的运行兼容性问题。/MT 模式不依赖系统中是否有相应的DLL文件。否则，使用/MD 可能会出现因缺少DLL，Paddle在部分机器上无法正常运行的问题。

好吧，对于现代的机器，个人观点推荐使用 /MD，如果无法运行，再推荐使用/MT

在使用其他开源库时，基本都是使用/MD编译，如果paddle库只用/MT编译，如果混用的话，很可能报错，而且难以排查。

**Comment by BaofengZan** [comment]
@duohappy @wanghuancoder  你好，我在win10下编译了MD的dll，但是再demo中使用MD生成exe时，一直报错。反而使用MT模式就可以编译生成exe。 是不是应为MD的dll没有真正编译成功呢？

**Comment by duohappy** [comment]
> 
> 
> @duohappy @wanghuancoder 你好，我在win10下编译了MD的dll，但是再demo中使用MD生成exe时，一直报错。反而使用MT模式就可以编译生成exe。 是不是应为MD的dll没有真正编译成功呢？

由于我的网络状况不好，所以没有编译成功过paddlepaddle推断库，这个问题我无法准确的回答你。还是等官方给出答复吧。建议把编译的系统环境，编译命令，也贴出来，官方人员容易分析

现在用官方编译好的DLL，但是也没有运行起来一个demo，很遗憾。
