### ISSUE TITLE
跟踪一下”关于LD_LIBRARY_PATH"的问题

### ISSUE THREAD

**Issue by duohappy** [PaddlePaddle/Paddle#31881]
你好，我上上周提出了一个issue，不知道你们测试的结果是否出来了？

@iclementine 

https://github.com/PaddlePaddle/Paddle/issues/31683

**Comment by Goghzki** [comment]
同样遇到这个问题，因为无root权限，机器默认安装的是11.2的cuda，8.1.1的cudnn，使用paddle时报错。在自己的home目录下安装cuda和cudnn后，无法通过更改环境变量的方式使paddle切换到自己的cuda和cudnn。
此外，想了解一下RTX30系列的显卡是否安装上10.2的cuda和7.6.5的cudnn就可以正常使用paddle？
蹲一个答案。

**Comment by duohappy** [comment]
> 
> 
> 同样遇到这个问题，因为无root权限，机器默认安装的是11.2的cuda，8.1.1的cudnn，使用paddle时报错。在自己的home目录下安装cuda和cudnn后，无法通过更改环境变量的方式使paddle切换到自己的cuda和cudnn。
> 此外，想了解一下RTX30系列的显卡是否安装上10.2的cuda和7.6.5的cudnn就可以正常使用paddle？
> 蹲一个答案。

理论上支持cuda的显卡，装上cuda10.2, cudnn 7.6.5，用paddle是没有问题的
但是对于`LD_LIBRARY_PATH`的问题，不知道官方为什么没有人跟进，仅仅只是回复了，不代表解决了，已经过去16天了

**Comment by W2Q3Q1** [comment]
我在4卡机器上测试的结果是：无论系统/usr/local/cuda是否存在，无论是否有LD_LIBRARY_PATH，在conda虚拟环境中安装的cuda都是可以被调用的，但是CUDNN不行，只要系统中存在/usr/local/cuda且里面正常安装了cudnn7.3，无论是否有LD_LIBRARY_PATH环境变量，无论conda是否安装了cudnn，都会自动使用/usr/local/cuda下的cudnn，即使这个cudnn不能适配

**Comment by duohappy** [comment]
> 
> 
> 我在4卡机器上测试的结果是：无论系统/usr/local/cuda是否存在，无论是否有LD_LIBRARY_PATH，在conda虚拟环境中安装的cuda都是可以被调用的，但是CUDNN不行，只要系统中存在/usr/local/cuda且里面正常安装了cudnn7.3，无论是否有LD_LIBRARY_PATH环境变量，无论conda是否安装了cudnn，都会自动使用/usr/local/cuda下的cudnn，即使这个cudnn不能适配

我打算关闭这个issue，应该不会有人跟踪这个问题了。如果实在觉得困扰，可以重提一个issue吧，引起重视。
