### ISSUE TITLE
`paddle.io.Dataset` 与 `paddle.io.DataLoader` 数据加载设备问题

### ISSUE THREAD

**Issue by ShaneTian** [PaddlePaddle/Paddle#31898]
- 标题：`paddle.io.Dataset` 与 `paddle.io.DataLoader` 数据加载设备问题
- 文档版本信息：2.0

- 问题描述：
1. 现状：
    1. 整个模型代码全局使用了 `fleet`，意味着使用了全局 `CUDAPlace`
    2. 在加载数据集的时候，复写了 `paddle.io.Dataset`，并且 `paddle.io.DataLoader` 中未指定 `place`
2. 问题：
    1. 发现随着数据集的增大，占用的显存越来越大，很容易 OOM
    2. 按照如上方式，是否将数据集加载到了显存而不是内存中
    3. 如何将数据集加载到 CPU 中，每次 forward 的时候再转到 cuda 中，可以节省显存
3. 示例代码：
```py
dataset = MyDataset(args)

batch_sampler = DistributedBatchSampler(dataset, batch_size=args.batch_size, shuffle=True)

data_loader = DataLoader(dataset, batch_sampler=batch_sampler,
                         collate_fn=dataset.collate_fn(args.pad_idx), num_workers=8)
```

**Comment by Joejiong** [comment]
您好，感谢你的问题，这是一个不错的问题，请问您环境配置的share memory的大小是多少呢

**Comment by ShaneTian** [comment]
> 您好，感谢你的问题，这是一个不错的问题，请问您环境配置的share memory的大小是多少呢

`DataLoader` 的 `use_shared_memory` 未做配置，使用默认值 `False`

**Comment by Joejiong** [comment]
可以尝试配置一下shm到128G，如果是docker环境，可以通过docker参数设置：`--shm-size="128g"`, 同时设置，use_shared_memory=True

**Comment by ShaneTian** [comment]
读取 Dataset 到 CPU 还是 GPU 有设置的方式吗？默认的行为是什么呢？

**Comment by Joejiong** [comment]
> 读取 Dataset 到 CPU 还是 GPU 有设置的方式吗？默认的行为是什么呢？

默认DataLoader是读到CUDAPinnedMemory。

**Comment by ShaneTian** [comment]
> > 读取 Dataset 到 CPU 还是 GPU 有设置的方式吗？默认的行为是什么呢？
> 
> 默认DataLoader是读到CUDAPinnedMemory。

那如何把 Dataset 读取到 CPU 中呢？因为数据集本身还蛮大的

**Comment by mengxiangqiqin** [comment]
确实，这个问题也困扰着我，希望官方尽快解答
