### ISSUE TITLE
C++ windows 推断报错paddle::platform::EnforceNotMet

### ISSUE THREAD

**Issue by duohappy** [PaddlePaddle/Paddle#31909]
### 系统信息
windows 10
cuda 10.2
cudnn 7.6.5
tensorrt TensorRT-7.0.0.11.Windows10.x86_64.cuda-10.2.cudnn7.6
paddle预测库：cuda10.2_cudnn7_avx_mkl_trt7
测试模型：http://paddle-inference-dist.cdn.bcebos.com/tensorrt_test/mobilenet.tar.gz

### 代码
``` C++
#include <algorithm>
#include <numeric>

#include "paddle_inference_api.h"


void CreateConfig(paddle_infer::Config* config, const std::string& model_dirname) {
	config->EnableUseGpu(1000, 0);

	config->SetModel(model_dirname + "/__model__");

	config->SwitchUseFeedFetchOps(false);

	config->SwitchIrDebug(true);
	config->EnableMemoryOptim();

}

void RunAnalysis(int batch_size, std::string model_dirname) {
	paddle_infer::Config config;
	CreateConfig(&config, model_dirname);

	auto predictor = paddle_infer::CreatePredictor(config);

	int channels = 3;
	int height = 224;
	int width = 224;

	int nums = batch_size * channels * height * width;
	float *input = new float[nums];
	for (int i = 0; i < nums; ++i) input[i] = 0;
        
        // std::memset(input, 0, nums);   // memset不能这么使用

	auto input_names = predictor->GetInputNames();
	auto input_t = predictor->GetInputHandle(input_names[0]);
	input_t->Reshape({ batch_size, channels, height, width });
	input_t->CopyFromCpu(input);

	predictor->Run();

	std::vector<float> out_data;
	auto output_names = predictor->GetOutputNames();
	auto output_t = predictor->GetOutputHandle(output_names[0]);
	std::vector<int> output_shape = output_t->shape();
	int out_num = std::accumulate(output_shape.begin(), output_shape.end(), 1,
		std::multiplies<int>());

	out_data.resize(out_num);
	output_t->CopyToCpu(out_data.data());

	delete[] input;
}



int main()
{
	RunAnalysis(1, "D:/mobilenet");

	return 0;
}
```

### 输出信息

``` html
WARNING: Logging before InitGoogleLogging() is written to STDERR
I0329 12:21:18.294168  4876 analysis_predictor.cc:155] Profiler is deactivated, and no profiling report will be generated.

E:\seafileSync\Seafile\allCode\computerVision\baiduPaddle\paddleClasEx01\x64\Release\paddleClasEx01.exe (进程 11160)已退出，返回代码为: -1073740791。
按任意键关闭此窗口...
```

断点调试在`auto predictor = paddle_infer::CreatePredictor(config);`报错
``` html
0x00007FF8FC92D759 处(位于 paddleClasEx01.exe 中)有未经处理的异常: Microsoft C++ 异常: paddle::platform::EnforceNotMet，位于内存位置 0x000000396C6FEE80 处。 出现了 
```

**Comment by zhwesky2010** [comment]
@duohappy 您好，是否是路径问题，``config->SetModel(model_dirname + "\\__model__");``  会报错吗

**Comment by duohappy** [comment]
> 
> 
> @duohappy 您好，是否是路径问题，`config->SetModel(model_dirname + "\\__model__");` 会报错吗

刚试过了，不是路径问题

**`/`** 是linux和windows下通用的，我在编程中，windows下一般也是用 **`/`**

**Comment by zhwesky2010** [comment]
@jiweibo @OliverLPH  麻烦看下预测库问题

**Comment by jiweibo** [comment]
您好，感觉config设置预测模型路径有点问题

如果加载combined形式模型
void SetModel(const std::string& prog_file_path,
              const std::string& params_file_path);

如果加载非combined形式模型
void SetModel(const std::string& model_dir);

可参考文档 https://paddleinference.paddlepaddle.org.cn/api_reference/cxx_api_doc/Config/ModelConfig.html

**Comment by duohappy** [comment]
> 
> 
> 您好，感觉config设置预测模型路径有点问题
> 
> 如果加载combined形式模型
> void SetModel(const std::string& prog_file_path,
> const std::string& params_file_path);
> 
> 如果加载非combined形式模型
> void SetModel(const std::string& model_dir);
> 
> 可参考文档 https://paddleinference.paddlepaddle.org.cn/api_reference/cxx_api_doc/Config/ModelConfig.html

@jiweibo 感谢

好吧，我又仔细看了下文档，强烈建议好好更新下 **服务端部署C++** 的文档吧[https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/guides/05_inference_deployment/inference/index_cn.html](https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/guides/05_inference_deployment/inference/index_cn.html)，简直太乱了，根据文档不可能部署成功的。

# 模型问题
根据这篇文档， https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/guides/05_inference_deployment/inference/native_infer.html
下载了测试模型：http://paddle-inference-dist.cdn.bcebos.com/tensorrt_test/mobilenet.tar.gz

这个测试模型是不是可以正常运行的呢？有测试过么？
我刚换成了`config->SetModel(model_dirname);`，但是依然报错，报错信息相同

# 文档错误1

这个测试模型，应该是非combined形式模型，但是这篇文档中的代码，容易让人误解的
``` C++
#include "paddle_inference_api.h"

namespace paddle_infer {
void CreateConfig(Config* config, const std::string& model_dirname) {
  // 模型从磁盘进行加载
  config->SetModel(model_dirname + "/model",
                   model_dirname + "/params");
}


int main() {
  // 模型下载地址 http://paddle-inference-dist.cdn.bcebos.com/tensorrt_test/mobilenet.tar.gz
  paddle_infer::RunAnalysis(1, "./mobilenet");
  return 0;
}
```

# 文档错误2

根据文档https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/guides/05_inference_deployment/inference/windows_cpp_inference.html

> 非combined形式：模型文件夹model_dir下存在一个模型文件和多个参数文件时，传入模型文件夹路径，模型文件名默认为__model__。
``` C++
config->SetModel("path\\model_dir\\__model__")   // 这段代码就是错的！
```

**Comment by zhwesky2010** [comment]
这个主要是Windows预测库的文档，对应的是比较早期的Paddle版本了，很久没更新了，也需要更新维护、测试下 @AIpioneer @jiweibo @TCChenlong

**Comment by duohappy** [comment]
> 
> 
> 这个主要是Windows预测库的文档，对应的是比较早期的Paddle版本了，很久没更新了，也需要更新维护、测试下 @AIpioneer @jiweibo @TCChenlong

不仅仅是windows预测库文档，而是整个预测库文档，最好全面审查一下。感觉这些代码没有经过测试就直接手敲上去的，不然也不会有这么明显的错误

https://github.com/PaddlePaddle/Paddle/issues/31955
