### ISSUE TITLE
C++ API预测库文档的问题

### ISSUE THREAD

**Issue by duohappy** [PaddlePaddle/Paddle#31907]
[C++ 预测 API介绍](https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/guides/05_inference_deployment/inference/native_infer.html)

``` C++
// 2. 根据config 创建predictor，并准备输入数据，此处以全0数据为例
auto predictor = CreatePredictor(config);
int channels = 3;
int height = 224;
int width = 224;
float input[batch_size * channels * height * width] = {0};
```

`input`是数组，不能用变量定义数组长度，这是明显的错误

**Comment by zhwesky2010** [comment]
@TCChenlong  您好，文档问题，麻烦给每个 int 加一个 const修饰下，谢谢 @duohappy 指正

**Comment by duohappy** [comment]
> 
> 
> @TCChenlong 您好，文档问题，麻烦给每个 int 加一个 const修饰下，谢谢 @duohappy 指正

@zhouwei25 @TCChenlong 

虽然g++用变长数组不会报错，但是并不是所有的C++编译器都是这样的

我建议不是加 `const`，就目前流行的C++ 11标准来说，加const也是不行的

建议不要用变长的数组，这样容易引起不兼容。
``` C++
int nums = batch_size * channels * height * width;
float *input  = new float[nums];
.......
.......
.......

delete[] input;
```

https://stackoverflow.com/questions/15013077/arrayn-vs-array10-initializing-array-with-variable-vs-real-number

**Comment by wadefelix** [comment]
> > @TCChenlong 您好，文档问题，麻烦给每个 int 加一个 const修饰下，谢谢 @duohappy 指正
> 
> @zhouwei25 @TCChenlong
> 
> 虽然g++用变长数组不会报错，但是并不是所有的C++编译器都是这样的
> 
> 我建议不是加 `const`，就目前流行的C++ 11标准来说，加const也是不行的
> 
> 建议不要用变长的数组，这样容易引起不兼容。
> 
> ```c++
> int nums = batch_size * channels * height * width;
> float *input  = new float[nums];
> .......
> .......
> .......
> 
> delete[] input;
> ```
> 
> https://stackoverflow.com/questions/15013077/arrayn-vs-array10-initializing-array-with-variable-vs-real-number

附议。C++并不完全支持此类用变量来定义临时数组，特别是这样定义的数组还可能真的爆栈。如您所说，使用`new`从堆区分配是推荐用法。
@TCChenlong
