### ISSUE TITLE
运行太慢了！一秒两张图片

### ISSUE THREAD

**Issue by johnenvpath** [PaddlePaddle/Paddle#31938]
1）PaddlePaddle V2.0
2）CPU/GPU：AMD Ryzen 3600, RTX3060, CUDA 11.1, CUDNN 8.1.1.33
3）系统环境：Ubuntu 20.10

运行faster_rcnn_r50_1x。
太慢了！每秒只有两张图片！显存使用一开始是10000MB+，后面降到5000MB+。

**Comment by zhwesky2010** [comment]
@jerrywgz 麻烦看下faster_rcnn_r50_1x的这个速度符合预期吗

**Comment by jerrywgz** [comment]
您好，检测问题可以到PaddleDetection repo下提issue https://github.com/PaddlePaddle/PaddleDetection ；并且说明下PaddleDetection版本以及运行命令
