### ISSUE TITLE
关于给网络层赋值的方法

### ISSUE THREAD

**Issue by SeanInfinity** [PaddlePaddle/Paddle#31942]
paddle版本：v2.0.1
我想问一下，如果我想将一个训练好的网络的某层的参数进行一些处理后，再赋值给另一个网络的层，有哪些方法可以做到？我查到的就只有在网络定义时用paddle.ParamAttr，或者使用set_state_dict()，是否有更方便的方法？只能用.parameters()或named_parameters()或state_dict()获得参数后，再一个个处理好放入collection.OrderedDict对象，最后用.set_state_dict()赋值吗？
还请赐教。

**Comment by chenwhql** [comment]
据我了解，您说的就是目前可行的办法，也没有别的更好的办法了

**Comment by SeanInfinity** [comment]
哎，好吧。
谢谢你的回答。
