### ISSUE TITLE
单机多卡 inference 预测

### ISSUE THREAD

**Issue by Jeffrey98-AI** [PaddlePaddle/Paddle#31943]
1）PaddlePaddle 2.0：
    3）GPU：单机四卡 nvidia GPU，
    4）系统环境：ubuntu

    如何使用 python 实现单机多卡的 inference 调用，是直接使用 python 的多进程吗？每个卡独立初始化一个模型，还是 paddle 有自己的处理方式？

**Comment by haozech** [comment]
你好，预测api介绍可以参考此文档。如果要使用单机多卡训练，可以建立多个predictor，同时在enable_use_gpu时，将每个predictor设置不同的gpu device id，这样在运行时每个predictor即可使用不同的gpu资源。

**Comment by Jeffrey98-AI** [comment]
我是这么处理的，每张卡独立初始化一个predictor，然后用python的多进程去调用，传入数据，后面会报这个错误 OSError: (External)  Cuda error(3), initialization error. Advise: The API call failed because the CUDA driver and runtime could not be initialized.  
具体指向这里 input_tensor.copy_from_cpu(img)

**Comment by haozech** [comment]
> 我是这么处理的，每张卡独立初始化一个predictor，然后用python的多进程去调用，传入数据，后面会报这个错误 OSError: (External) Cuda error(3), initialization error. Advise: The API call failed because the CUDA driver and runtime could not be initialized.
> 具体指向这里 input_tensor.copy_from_cpu(img)

请使用nvidia-smi指令查看cuda driver是否正确安装和初始化

**Comment by cryoco** [comment]
https://stackoverflow.com/questions/22950047/cuda-initialization-error-after-fork
cuda使用fork方式多进程有一些问题，可以使用多线程，每个predictor绑定一个线程，不同predictor的config中，通过enable_use_gpu(init_mem_size, gpu_id)设置不同的gpu_id在不同卡上预测

**Comment by Jeffrey98-AI** [comment]
感谢解答，采用多线程可以解决，另外再请教一个问题 os.environ["FLAGS_allocator_strategy"] = 'auto_growth' 这样设置paddle会自动实现 GPU 显存管理 (如清理缓存) 吗？实际预测的时候batch size 并不是很大，但是显存占用越来越大，到后面几乎占满了全部显存。

**Comment by cryoco** [comment]
> 感谢解答，采用多线程可以解决，另外再请教一个问题 os.environ["FLAGS_allocator_strategy"] = 'auto_growth' 这样设置paddle会自动实现 GPU 显存管理 (如清理缓存) 吗？实际预测的时候batch size 并不是很大，但是显存占用越来越大，到后面几乎占满了全部显存。

除非predictor所在进程结束，否则不会主动释放所占用的显存。您可以使用
```c++
config.EnableMemoryOptim();
```
开启显存复用，降低总显存占用，或使用
```c++
predictor->TryShrinkMemory();
```
在完成一轮预测后尝试通过释放中间Tensor来降低显存占用
