### ISSUE TITLE
C++ api文档问题

### ISSUE THREAD

**Issue by duohappy** [PaddlePaddle/Paddle#31955]
https://paddleinference.paddlepaddle.org.cn/api_reference/cxx_api_doc/Config/ModelConfig.html

官方C++ api文档中
``` C++
// 创建默认 Config 对象
paddle_infer::Config config();
```
`paddle_infer::Config`的数据类型是 `Struct`，`config()`这个什么?

一般不是如下代码就行么？
``` C++
paddle_infer::Config config;
```

文档中的代码全部经过测试了么？`paddle_infer::Config config();`明显报错

**Comment by haozech** [comment]
感谢反馈！相关同学已经在排查此文档问题

**Comment by Superjomn** [comment]
config 和 config() 语义上是一样的吧。  都是直接调用无参的构造函数。

这个应该没有问题

**Comment by Superjomn** [comment]
貌似的确有一些问题

http://spalatnik.com/blog/2011/01/20/parenthesis-confusion-in-c-plus-plus/

我们改下文档，谢谢！
