### ISSUE TITLE
龙芯处理器平台编译错误

### ISSUE THREAD

**Issue by cheungxi** [PaddlePaddle/Paddle#31964]
- 标题：龙芯处理器平台编译错误
- 版本、环境信息：
    1）PaddlePaddle版本：commit 6dca7a1de70a85b16e2fa8d7f1affd5c632ca10c
    2）CPU：Loongson 3A4000
    3）GPU：
    4）系统环境：Loongnix 1.0 kernel 3.10.84-23.fc21.loongson.8.mips64el、Python版本 3.7
。
- 安装方式信息：
- 本地编译：`cmake .. -DPY_VERSION=3 -DPYTHON_EXECUTABLE=`which python3` -DWITH_MIPS=ON -DWITH_TESTING=OFF -DCMAKE_BUILD_TYPE=Release -DON_INFER=ON -DWITH_XBYAK=OFF -DWITH_MKL=OFF`
- 复现信息：复现步骤和安装文档一致 https://www.paddlepaddle.org.cn/install/quick?docurl=/documentation/docs/zh/install/compile/mips-compile.html#anchor-0
- 问题描述：请详细描述您的问题，同步贴出报错信息、日志/代码关键片段
cmake时出现如下错误
Error evaluating generator expression:

    $<FILTER:,EXCLUDE,/Zc:inline>
![image](https://user-images.githubusercontent.com/11963792/112984594-aa658f00-9191-11eb-91eb-400a26b92291.png)

**Comment by jiweibo** [comment]
您好，看样子是依赖的最低cmake版本发生了变化，请升级cmake到3.16试下

**Comment by cheungxi** [comment]
> 您好，看样子是依赖的最低cmake版本发生了变化，请升级cmake到3.16试下

但是我看安装手册上说3.9就可以
> Paddle依赖cmake进行编译构建，需要cmake版本>=3.10，龙芯操作系统源提供cmake的版本是3.9，且尝试源码编译cmake失败，此处临时的处理方式是修改Paddle主目录的CMakeLists.txt, cmake_minimum_required(VERSION 3.10) 修改为 cmake_minimum_required(VERSION 3.9)。等到龙芯系统支持cmake >= 3.10后则不需要其它操作。

**Comment by cheungxi** [comment]
> 您好，看样子是依赖的最低cmake版本发生了变化，请升级cmake到3.16试下

确实升级之后，成功安装。
但是为什么会提示使用的是GPU version
![image](https://user-images.githubusercontent.com/11963792/113129332-5a4c0280-924d-11eb-949a-9b03e7bcd620.png)

**Comment by jiweibo** [comment]
> > 您好，看样子是依赖的最低cmake版本发生了变化，请升级cmake到3.16试下
> 
> 确实升级之后，成功安装。
> 但是为什么会提示使用的是GPU version
> ![image](https://user-images.githubusercontent.com/11963792/113129332-5a4c0280-924d-11eb-949a-9b03e7bcd620.png)

这个log可能有点误导，应该是run_check在检测的时候先以cuda place去测试demo能否正常运行，这个过程中报的log。

看最后的works well on 2 CPUs就可以

**Comment by haozech** [comment]
> > 您好，看样子是依赖的最低cmake版本发生了变化，请升级cmake到3.16试下
> 
> 确实升级之后，成功安装。
> 但是为什么会提示使用的是GPU version
> ![image](https://user-images.githubusercontent.com/11963792/113129332-5a4c0280-924d-11eb-949a-9b03e7bcd620.png)

您好，如果问题已解决请关闭issue~

**Comment by cheungxi** [comment]
谢谢
