### ISSUE TITLE
多轮对话中单轮和多轮分支不一致会出现NAN

### ISSUE THREAD

**Issue by yujiate** [PaddlePaddle/Paddle#31967]
- 版本、环境信息：
    1）PaddlePaddle版本：2.0.0
    3）GPU：V100，cuda10.0
    4）系统环境：python3.7

在多轮对话的训练过程中需要使用之前对话的信息，在第一轮之后获取之前的对话编码信息，而第一轮因为前面没有对话不需要获取，因此训练时会进入两个分支，此时如果不进行特殊处理会在训练过程中出现无法解释的NAN(该部分的参数变为NAN，同时loss受该部分数据影响，随之变NAN)。当预设一个虚拟变量为第一轮的之前的对话信息，将第一轮和之后的训练步骤对齐（此时不论第一轮还是之后都会获取之前的对话信息，第一轮获取的是预设的虚拟变量的信息），训练可以顺利进行，该现象无法解释。

**Comment by haozech** [comment]
您好，能否提供简单的可复现代码？方便我们定位问题
