### ISSUE TITLE
paddle模型转onnx模型时能否对输出层的名称重命名？

### ISSUE THREAD

**Issue by fan-chao** [PaddlePaddle/Paddle#31975]
使用paddle2.0转onnx时，可以看到下面的input有一个字段name对输入进行重命名。
现在因为有个需求，想在运行时，获取输出的名字，但是当前的名字一般为save_infer_model/scale_0.tmp_0，有点长，想重新命名，不知道是否有这个功能？如果有，如何命名？

`
def main():
    global_config = config['Global']

    # build model
    model = build_model(config['Architecture'])

    init_model(config, model, logger)

    model.eval()
	
	#定义输入数据
    input_spec = paddle.static.InputSpec(shape=[1, 3, 640, 640], dtype='float32', name='data')

    #ONNX模型导出
    paddle.onnx.export(model, "ocr_det", input_spec=[input_spec], opset_version=10])`

![image](https://user-images.githubusercontent.com/10006853/113085721-ee4ca880-9212-11eb-8692-7b2ae81242f2.png)

**Comment by chenjiaoAngel** [comment]
目前不能支持修改输出层名称，建议查阅下onnx的相关api，看是否能对转换后的onnx模型输出进行重命名
