### ISSUE TITLE
部署时，运行预测器输出空列表

### ISSUE THREAD

**Issue by jiamingming-004** [PaddlePaddle/Paddle#31974]
在AIstudio中训练yolov3模型，将其保存为推理预测部署所需要的模型、参数文件，版本为1.8，部署预测时，j将输入数据转为paddletensor，是有结果输出的，在执行预测引擎时，输出为空。

在人脸检测中（模型是paddlehub导出的），不存在如下问题，而换了自己训练（Aistudio中）的模型yolov3，就出现错误如下错误

#  以下是出现错误的部分：
batch_image = np.array([data['image'] for data in batch_data])
print(47, batch_image)              #  输出：   [[[[-0.015625 -0.1015625 -0.2109375 ... -0.3046875 -0.234375 -0.1015625] [-0.1328125 -0.21875 -0.3046875 ... -0.1796875 -0.171875 -0.015625 ]  
batch_image = PaddleTensor(batch_image.astype('float32'))
print(48, batch_image)                 #   （打印的结果）：paddle.fluid.core_avx.PaddleTensor object at 0x00000010B8FE5C38>
data_out = self.predictor.run([batch_image])
print(56, data_out)                #  输出：  为空 [ ]
confidences = data_out[0].as_ndarray()

以下是项目的链接：
https://aistudio.baidu.com/studio/project/partial/verify/1719294/4f815971f0e14770b46a84c3b4456bdb

https://aistudio.baidu.com/bdcpu2/user/262171/1719294/notebooks/1719294.ipynb

**Comment by jiamingming-004** [comment]
如果是训练模型的问题，我可以提供原模型链接

**Comment by chenjiaoAngel** [comment]
这个输出为空，是可以正常运行，输出tensor shape为0 名？

**Comment by chenjiaoAngel** [comment]
yolov3模型的预处理、输入shape、后处理是不是和人脸检测模型不一样额。如果是，这个需要修改预处理/后处理代码；你也可以尝试用全一数据处理，直接调用预测库API（https://paddle-lite.readthedocs.io/zh/latest/api_reference/python_api_doc.html），看是否有输出；

**Comment by jiamingming-004** [comment]
好的，这方面我还没有想到，我去看看

**Comment by jiamingming-004** [comment]
你好，我试了试你的建议，但还是同样的问题，预测输出为空。


> yolov3模型的预，输入形状，后处理是不是和人脸检测模型不一样额。如果是，这个需要修改预/后处理代码；你也可以尝试用全一数据处理，直接调用预测库API （[https://paddle-lite.readthedocs.io/zh/latest/api_reference/python_api_doc.html），看是否有输出；](https://paddle-lite.readthedocs.io/zh/latest/api_reference/python_api_doc.html%EF%BC%89%EF%BC%8C%E7%9C%8B%E6%98%AF%E5%90%A6%E6%9C%89%E8%BE%93%E5%87%BA%EF%BC%9B)

你好，我试了你的建议，但还是同样的错误输出为空，希望你可以帮我解答一下
