### ISSUE TITLE
参数更新

### ISSUE THREAD

**Issue by songsong-L** [PaddlePaddle/Paddle#31984]
**System information**
-PaddlePaddle version 2.0
-CPU: including CPUMKL/OpenBlas/MKLDNN version
-GPU: including CUDA/cuDNN version
-OS Platform and Distribution Ubuntu18.0.4
-Python version 3.6

**Describe your current behavior**
在paddlepaddle2中，如何修改计算出的梯度（方案需要），然后执行梯度下降的时候用我修改的梯度？类似的实现在TensorFlow1中是使用apply_gradients()来实现的。
**Other info / logs**
执行梯度下降的step()函数似乎没有对应文档说明，可否实现apply_gradients()这个功能。

**Comment by chenwhql** [comment]
是说指定反向的起始梯度吗？目前，默认使用的是全1.0的起始梯度，是说要改这个吗

**Comment by songsong-L** [comment]
w = w - a*G ,每一层上都有计算出的偏导，需要对这些梯度（G）重构（修改），开发文档说是保存在grad这个属性中，是不能改属性的。

**Comment by songsong-L** [comment]
> 是说指定反向的起始梯度吗？目前，默认使用的是全1.0的起始梯度，是说要改这个吗
w = w - a*G ,每一层上都有计算出的偏导，需要对这些梯度（G）重构（修改），开发文档说是保存在grad这个属性中，是不能改属性的。

**Comment by songsong-L** [comment]
backward()反向计算出每一层上的梯度，需要重构（要改的）就是每一层上的这些梯度，改完之后再执行梯度下降更新参数。

**Comment by chenwhql** [comment]
嗯嗯，明白了，您现在用的是2.0动态图吗？

tensorflow里面，您使用的是这个方法吗？
https://www.tensorflow.org/api_docs/python/tf/keras/optimizers/Optimizer#apply_gradients

**Comment by songsong-L** [comment]
> 嗯嗯，明白了，您现在用的是2.0动态图吗？
> 
> tensorflow里面，您使用的是这个方法吗？
> https://www.tensorflow.org/api_docs/python/tf/keras/optimizers/Optimizer#apply_gradients

是的，2.0动态图。对，用TensorFlow1实现的时候用的是apply_gradients(),并且改变梯度张量是通过自定义op实现的，将自定义op的返回值（也就是已经重构过的值）apply进去。TensorFlow1里的apply_gradients应该是静态图的，没用过TensorFlow的动态图

**Comment by songsong-L** [comment]
TensorFlow1实现流程是这样的：
computer_gradients()计算梯度=>自定义op修改梯度=>apply_gradients()
但是，现在用paddle2不知道如何实现这种玩法了！

**Comment by chenwhql** [comment]
2.0静态图也可以使用类似你之前的方法去做，用apply_gradients去实现，静态图也有这个API

但2.0的动态图还没有比较方便的方法能做这件事，在动态图里我理解可以用Tensor.register_hook+自定义op的方式去实现这个目的，但Tensor.register_hook目前仅在develop中支持了，会随2.1发版，2.0目前还不能使用这个功能

或者就是用一些比较硬的做法，比如可以写一个特殊的自定义op，这个op的前向就直接返回输入tensor，反向的时候按照你的处理规则对梯度进行处理，然后把这个op接到网络中

**Comment by songsong-L** [comment]
> 2.0静态图也可以使用类似你之前的方法去做，用apply_gradients去实现，静态图也有这个API
> 
> 但2.0的动态图还没有比较方便的方法能做这件事，在动态图里我理解可以用Tensor.register_hook+自定义op的方式去实现这个目的，但Tensor.register_hook目前仅在develop中支持了，会随2.1发版，2.0目前还不能使用这个功能
> 
> 或者就是用一些比较硬的做法，比如可以写一个特殊的自定义op，这个op的前向就直接返回输入tensor，反向的时候按照你的处理规则对梯度进行处理，然后把这个op接到网络中

好的，多谢！我觉得框架都注重正向计算，然后自动微分，正常就很方便，够用了。但是对于研究的人，在反向阶段也希望做一些处理，希望对梯度的处理部分也有比较好的API。再次感谢！

**Comment by chenwhql** [comment]
您客气了，刚刚说在动态图下的方案已经有了，只是还没正式发布，您也可以提前了解下：

- hook（2.1发版）， 代码与示例如下：https://github.com/PaddlePaddle/Paddle/blob/4acc87beb2110e9966327dbd427e0cdc17e05841/python/paddle/fluid/dygraph/varbase_patch_methods.py#L245 
- 自定义Op（2.0已有），教程文档：https://www.paddlepaddle.org.cn/documentation/docs/zh/guides/07_new_op/new_custom_op.html
