### ISSUE TITLE
文档错误

### ISSUE THREAD

**Issue by mapingshuo** [PaddlePaddle/Paddle#31983]
https://www.paddlepaddle.org.cn/documentation/docs/zh/1.8/api_cn/dygraph_cn/LayerNorm_cn.html#canshu

![image](https://user-images.githubusercontent.com/23031310/113107219-3e893200-9236-11eb-882b-f287efe9d7f7.png)

**Comment by duohappy** [comment]
我打开后，没有错误，这个应该和网络有关，加载了与latex语法相关的库

**Comment by wadefelix** [comment]
我是用safari和edge for mac打开网页，公式均正确渲染出来了，但是需要点儿时间。
请问您使用的浏览器版本是？

**Comment by wadefelix** [comment]
针对渲染慢的问题，我们已修复并更新。
感谢您的反馈。

请问公式渲染不出来的问题还在么？

**Comment by mapingshuo** [comment]
已没有问题了，谢谢
