### ISSUE TITLE
Don't map operator name to Python functions

### ISSUE THREAD

**Issue by wangkuiyi** [PaddlePaddle/Paddle#3198]
```python
def __bootstrap__():
    """
    Bootstrap function for this module. It will dynamic create all op creation
    methods in runtime.
    """
    for op_proto in get_all_op_protos():
        func = create_op_creation_method(op_proto)
        func.__name__ = str(op_proto.type)
        setattr(op_creations, func.__name__, func)
```

This introduces extra complexity compared with

```python
core.operator("ReLU", input={...}, output={...})
```

The former approach would create confusion for our users -- users might see a call in an example program like `fc(...)` but s/he cannot grep the codebase to find the definition of function `fc`.

**Comment by reyoung** [comment]
What argument should `core.operator()` method take?

Should it be 

```python
core.operator("Mul", input={
  "A": "var_a",
  "B": "var_b"
}, output={
  "Out": "var_out"
}, attr={
  "some_attr": 1.0f,
  "other_attr": [1,2,3,4]
})
```
or

```python
core.operator("Mul", A="var_a", B="var_b", Out="var_out", some_attr=1.0f, other_attr=[1,2,3,4])
```

Also, what reference documentation of operator should be? Currently, op_creations.xxx generate the docstring from Paddle C++ core. Like

```python
>> help(op_creations.add_two)

Help on function add_two in module paddle.v2.framework.create_op_creation_methods:

add_two(*args, **kwargs)
    Two Element Add Operator.

    The equation is: Out = X + Y

    :param X: The first input of add op
    :type X: basestr
    :param Y: The second input of add op
    :type Y: basestr
    :param Out: The output of add op
    :type Out: basestr
```

**Comment by wangkuiyi** [comment]
Either API call in your case @reyoung looks good to me.

I don't see it's super valuable using Python's `help` to retrieve documentation. The most straightforward document is the code itself. The most intuitive ways is a documentation HTML page, which can be generated from C++ source code.

**Comment by reyoung** [comment]
> Either API call in your case @reyoung looks good to me.

OK. I will choose the second API in implementation because it seems that less code for the user.

> I don't see it's super valuable using Python's help to retrieve documentation. The most straightforward document is the code itself. The most intuitive ways is a documentation HTML page, which can be generated from C++ source code.

Python docstring can generate `HTML` pages, i.e., API reference page by `Sphinx`. It is a common way for Python code/API.

I agree that the most straight-forward document is code itself. But for end-user, a HTML pages is necessary. In this way we do not generate function to each operator, we must figure out how to generate a HTML file from C++ operator.

Maybe to generate an markdown file for each operator is OK? I will add other issue for operator documentation generating when the second API is done.

**Comment by wangkuiyi** [comment]
I think we need documents for two levels of API

1. Operators.  Because operators are defined as C++ classes, we should generate its documentation from C++ source code.  This level of documentation is for layer developers, and doesn't have to be visitable through Pythons' `help` function.

2. Layers. Because layers are Python functions, we should generate their documentation from the Python source code.  This documentation is for application developers, and should be exposed via Python's `help` function.

**Comment by reyoung** [comment]
@wangkuiyi I am working on this issue #3169 today. I will change the Python API tomorrow.
