### ISSUE TITLE
paddle2.0 c++ setmodel 预测崩溃

### ISSUE THREAD

**Issue by vived** [PaddlePaddle/Paddle#31981]
![微信截图_20210331145541](https://user-images.githubusercontent.com/8553649/113102903-31b60f80-9231-11eb-9d7d-883176b5c585.png)

下载使用了两个版本的预测库都这样

![微信截图_20210331145749](https://user-images.githubusercontent.com/8553649/113103154-7cd02280-9231-11eb-8bdf-9aff307155fe.png)

用的是VS2017,win10系统

使用Python paddle2.0.1用这model是可以预测的

**Comment by duohappy** [comment]
根据官方的文档，我同样也没有运行成功过

https://github.com/PaddlePaddle/Paddle/issues/31909

**Comment by jiweibo** [comment]
> ![微信截图_20210331145541](https://user-images.githubusercontent.com/8553649/113102903-31b60f80-9231-11eb-9d7d-883176b5c585.png)
> 
> 下载使用了两个版本的预测库都这样
> 
> ![微信截图_20210331145749](https://user-images.githubusercontent.com/8553649/113103154-7cd02280-9231-11eb-8bdf-9aff307155fe.png)
> 
> 用的是VS2017,win10系统
> 
> 使用Python paddle2.0.1用这model是可以预测的

您好，请确认下模型的名称正确吗？corangle.pdmodell 还是 corangle.pdmodel，如果没问题的话，可以使用VS2015测试下，库是在VS2015上编的，不太清楚直接换用2017会不会有问题

**Comment by vived** [comment]
> > ![微信截图_20210331145541](https://user-images.githubusercontent.com/8553649/113102903-31b60f80-9231-11eb-9d7d-883176b5c585.png)
> > 下载使用了两个版本的预测库都这样
> > ![微信截图_20210331145749](https://user-images.githubusercontent.com/8553649/113103154-7cd02280-9231-11eb-8bdf-9aff307155fe.png)
> > 用的是VS2017,win10系统
> > 使用Python paddle2.0.1用这model是可以预测的
> 
> 您好，请确认下模型的名称正确吗？corangle.pdmodell 还是 corangle.pdmodel，如果没问题的话，可以使用VS2015测试下，库是在VS2015上编的，不太清楚直接换用2017会不会有问题

我为了尝试错误，任何对的错的字符串都试了，都是这错误。

**Comment by jiweibo** [comment]
@vived 您好，如果模型可以公开的话，可以share下模型，我本地复现下问题，或者您换一个开源模型测下，看是否是环境的问题。

**Comment by vived** [comment]
> @vived 您好，如果模型可以公开的话，可以share下模型，我本地复现下问题，或者您换一个开源模型测下，看是否是环境的问题。

![image](https://user-images.githubusercontent.com/8553649/113375188-75c82200-93a1-11eb-8fa4-7cfb613f010f.png)

算了，我已不用paddlec++版本了，通过注释掉上边的代码，我通过pythonet在c#中可以使用模型预测。

**Comment by duohappy** [comment]
> 
> 
> > @vived 您好，如果模型可以公开的话，可以share下模型，我本地复现下问题，或者您换一个开源模型测下，看是否是环境的问题。
> 
> ![image](https://user-images.githubusercontent.com/8553649/113375188-75c82200-93a1-11eb-8fa4-7cfb613f010f.png)
> 
> 算了，我已不用paddlec++版本了，通过注释掉上边的代码，我通过pythonet在c#中可以使用模型预测。

不知道官方的C++版本和C++版本的文档经过测试没有，我真心搞不懂，C++版本必须是最重要且最稳定的，我却一直运行不起来
