### ISSUE TITLE
使用Paddle2.0做模型预测，预测结束后Predictor析构过程耗时明显

### ISSUE THREAD

**Issue by ljayx** [PaddlePaddle/Paddle#31997]
- 版本、环境信息：
    1）PaddlePaddle版本：2.0.1
    2）CPU：Intel(R) Xeon(R) Gold 5117 CPU @ 2.00GHz
    3）GPU：Tesla P4, CUDA10.0 + CUDNN7
    4）系统环境：Ubuntu 16.04

- 预测信息
    1）C++预测：使用的官方预编译库：ubuntu14.04_cuda10.0_cudnn7_avx_mkl_gcc54
    2）预测库来源：官网下载

- 复现信息：使用的官方[预测库](https://www.paddlepaddle.org.cn/documentation/docs/zh/guides/05_inference_deployment/inference/build_and_install_lib_cn.html#zhijiexiazaianzhuang)+[官方demo](https://www.paddlepaddle.org.cn/documentation/docs/zh/guides/05_inference_deployment/inference/native_infer.html#a-name-predictor-predictor-a)

- 问题描述：预测结束后，应该就是Predictor的析构了，但是这个过程很耗时，大约在5s左右。

**Comment by Shixiaowei02** [comment]
您好，请确认在程序中不会频繁创建析构 Predictor 对象；因为此对象涉及内存和显存资源的申请释放，所以构造析构相对耗时较长。

**Comment by ljayx** [comment]
@Shixiaowei02 没有频繁创建，用的推理代码就是上面贴出来的官方给出的demo，只有一次推理。
![image](https://user-images.githubusercontent.com/29032384/113234083-2c110600-92d3-11eb-8eb5-71cfbe43c2e2.png)

paddle1.8版本没有这个问题。

**Comment by Shixiaowei02** [comment]
@jiweibo 麻烦看下是否和 ShrinkMemory 相关吧，谢谢

**Comment by jiweibo** [comment]
2.0之后Predictor析构的过程会对全局的内/显存池进行处理，相对于1.8会增加一定的耗时，我profile下这个数据。

**Comment by ljayx** [comment]
@jiweibo 你好，请问有进展吗？

**Comment by ljayx** [comment]
any update?

**Comment by jiweibo** [comment]
您好，析构问题已经部分修复了，在析构过程中去除了针对权重的显存池释放部分，已合入2.1哈
