### ISSUE TITLE
Deploying multiple models at the same time will raise MKLDNN error

### ISSUE THREAD

**Issue by juncaipeng** [PaddlePaddle/Paddle#31992]
* Info

C++ API
Ubuntu 16.04
CPU MKLDNN
GCC 8.2.0

* Prepare

Please contact danqing to download the demo. The demo only has two group models for test.

Download [model_test.cc.zip](https://github.com/PaddlePaddle/Paddle/files/6248677/model_test.cc.zip), unzip model_test.cc.zip, use the new model_test.cc to update the old model_test.cc file in the demo.

Make and install paddle release2.0 (commit id: `c7a6a1f9610a9ee018c19d89950d76b38f33aed1`).
```
cmake -DCMAKE_BUILD_TYPE=Release -DWITH_PYTHON=OFF -DWITH_MKL=ON -DWITH_GPU=OFF -DON_INFER=ON .. && make -j && make inference_lib_dist -j
```

Set LIB_DIR as the path of PaddleInference in build.sh.

Run `sh build.sh`.

Run `ulimit -c unlimited` enable save core file.

* The first test 

Run `./build/model_test --test_groups=0 --single_instance=true` , it does not raise error.
If set `single_instance` as true, every model only has one predictor. Otherwise, some models will have several predictors by calling predictor.clone().

Run `./build/model_test --test_groups=0 --single_instance=false`, it raises segmentation fault error.  
Run `gdb ./build/model_test core_file` get the following error.

![image](https://user-images.githubusercontent.com/52520497/113134005-e4e33080-9252-11eb-9f79-71e4e31e2253.png)

* The second test 

Run `./build/model_test --test_groups=1 --single_instance=true` , it does not raise error.

Run `./build/model_test --test_groups=1 --single_instance=false`, it also raises segmentation fault error.  

![image](https://user-images.githubusercontent.com/52520497/113134330-3c819c00-9253-11eb-9a34-2128656f5bbd.png)

Sometimes, the above demo raises different error, such as

![image](https://user-images.githubusercontent.com/52520497/113137943-c469a500-9257-11eb-93a1-5f5e911a39d4.png)

* The third test

Run `./build/model_test --test_groups="4 5 6" --single_instance=true`. The demo loads several group models and every model has one predictor, and it also raises error as following. The demo only has  two group models for now, we will provide other models later.

![image](https://user-images.githubusercontent.com/52520497/113283388-d06a6b00-931a-11eb-8ed4-6ec80a1f4147.png)

![image](https://user-images.githubusercontent.com/52520497/113283241-9c8f4580-931a-11eb-98bf-955b83618da2.png)
![image](https://user-images.githubusercontent.com/52520497/113283613-13c4d980-931b-11eb-8991-c57700bbb1d5.png)

**Comment by jczaja** [comment]
@lidanqing-intel , @juncaipeng  We are investigating that issue. Currently We reproduced it on develop branch. Candidate fix was made (#32136) and we are testing it now.

**Comment by jczaja** [comment]
@juncaipeng
1. Could you please test this PR https://github.com/PaddlePaddle/Paddle/pull/32136 (develop) if this solves problem for you? 
2.  We miss some multi-instance unit tests (#32087) , would it be possible to turn this issue's test into UT ?

**Comment by juncaipeng** [comment]
@jczaja  
For the latest develop branch, the demo still raises error when run the following command:
`./build/model_test --test_groups="0 1" --single_instance=false`
Sometimes,  the demo also raises error when run the following command:
`./build/model_test --test_groups="0" --single_instance=false` 
`./build/model_test --test_groups="1" --single_instance=false` 

Should I use the inference library of release/2.0?

These models can not be used in UT, so you should find some other models.

**Comment by jczaja** [comment]
@juncaipeng This is cherry-pick for release/2.0 https://github.com/PaddlePaddle/Paddle/pull/32163 . It works fine on my setup but @lidanqing-intel that every other run there is some crash on her setup so I will test it further.

**Comment by jczaja** [comment]
@juncaipeng  I have made some more changes (develop PR: #32309). Could you please test them and report problems if any?

**Comment by juncaipeng** [comment]
@jczaja  I have tested all the models in the demo and don't have problems. The customer will use the new inference library to test in their project. If there's any news, I'll give it back.

**Comment by juncaipeng** [comment]
@jczaja  The customers reported that there is no problem with the new inference library  (develop PR: #32309) for now.

**Comment by jczaja** [comment]
@juncaipeng I have implemented alternative fix : https://github.com/PaddlePaddle/Paddle/pull/32499 . That is the one I would like to merge. Could you please test it against this issue

**Comment by juncaipeng** [comment]
@jczaja  The inference library (develop PR: #32499)  also passed all tests.

**Comment by lidanqing-vv** [comment]
@juncaipeng  Could this issue be closed
