### ISSUE TITLE
设置日志等级问题

### ISSUE THREAD

**Issue by ljayx** [PaddlePaddle/Paddle#32002]
- 版本、环境信息：
    1）PaddlePaddle版本：2.0.1
    2）CPU：Intel(R) Xeon(R) Gold 5117 CPU @ 2.00GHz
    3）GPU：Tesla P4 + CUDA10
    4）系统环境：Ubuntu16.04

- 预测信息
    1）C++预测：使用的官方预编译库和官方demo （C++）。
    4）预测库来源：官网下载

- 复现信息：`export GLOG_V=10` 后，执行官方demo，并没有更多log打印。

- 问题描述：请问如何设置log等级，我试了`export GLOG_V=10`，然后再执行官方提供的C++ demo，但是日志打印并没有变化，还是很少。因为要排查问题，需要多打点log，希望告知如何正确设置log等级。谢谢。

**Comment by Leonardo-Ding** [comment]
您好，设置log等级应该是export GLOG_v=10 您的大小写拼写有误，谢谢。

**Comment by ljayx** [comment]
@Leonardo-Ding 你好，`export GLOG_v=10`后也还是没有更多log。

**Comment by ljayx** [comment]
@Leonardo-Ding 你好，`export GLOG_v=10`后，跑官方的预测库有log，但是我自己编译的预测库没有，编译paddle预测库的时候需要开启什么选项吗？

**Comment by Leonardo-Ding** [comment]
你自己编译的预测库确定编译GLOG了吗，paddle预测库编译默认是编译GLOG的
