### ISSUE TITLE
训练报错predict_data:-nan

### ISSUE THREAD

**Issue by lps683** [PaddlePaddle/Paddle#32024]
稳定复现以下错误，是啥原因
Traceback (most recent call last):
  File "script/local_train.py", line 17, in <module>
    model_output_back="./output"
  File "/home/disk2/work/liupeisen/look_like/model/train_env/multi_task_model/script/train.py", line 653, in train
    train_loop(fluid.default_main_program())
  File "/home/disk2/work/liupeisen/look_like/model/train_env/multi_task_model/script/train.py", line 592, in train_loop
    auc_var_bes.name, cur_auc_bes.name])
  File "/home/disk2/work/liupeisen/look_like/model/train_env/multi_task_model/python27-gcc482/lib/python2.7/site-packages/paddle/fluid/parallel_executor.py", line 297, in run
    self.executor.run(fetch_list, fetch_var_name)
paddle.fluid.core.EnforceNotMet: Enforce failed. Expected predict_data <= 1, but received predict_data:-nan > 1:1.
The predict data must less or equal 1. at [/home/paddle/qiaolongfei/Paddle/paddle/fluid/operators/metrics/auc_op.h:80]
PaddlePaddle Call Stacks:
0       0x7fd68c4d111dp void paddle::platform::EnforceNotMet::Init<std::string>(std::string, char const*, int) + 365
1       0x7fd68c4d2230p paddle::platform::EnforceNotMet::EnforceNotMet<char const*, char const*, char const*, char const*, std::string, char const*, std::string, std::string>(char const*, int, char const*, char const*, char const*, char const*, std::string, char const*, std::string, std::string) + 144
2       0x7fd68cd2f195p paddle::operators::AucKernel<paddle::platform::CPUPlace, float>::statAuc(paddle::framework::Tensor const*, paddle::framework::Tensor const*, int, int, int, long*, long*, long**, long**) + 1253
3       0x7fd68cd2f80ap paddle::operators::AucKernel<paddle::platform::CPUPlace, float>::Compute(paddle::framework::ExecutionContext const&) const + 954
4       0x7fd68cd2fbb3p std::_Function_handler<void (paddle::framework::ExecutionContext const&), paddle::framework::OpKernelRegistrarFunctor<paddle::platform::CPUPlace, false, 0ul, paddle::operators::AucKernel<paddle::platform::CPUPlace, float> >::operator()(char const*, char const*, int) const::{lambda(paddle::framework::ExecutionContext const&)#1}>::_M_invoke(std::_Any_data const&, paddle::framework::ExecutionContext const&) + 35
5       0x7fd68d23a8abp paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&) const + 795
6       0x7fd68d236f75p paddle::framework::OperatorBase::Run(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&) + 229
7       0x7fd68d1cf4e0p
8       0x7fd68d1cf1b0p paddle::framework::details::ComputationOpHandle::RunImpl() + 112
9       0x7fd68d1e130cp paddle::framework::details::OpHandleBase::Run(bool) + 28
10      0x7fd68d15e69dp
11      0x7fd68cbd4a03p std::_Function_handler<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> (), std::__future_base::_Task_setter<std::unique_ptr<std::__future_base::_Result<void>, std::__future_base::_Result_base::_Deleter>, void> >::_M_invoke(std::_Any_data const&) + 35
12      0x7fd68cb9ccd7p std::__future_base::_State_base::_M_do_set(std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> ()>&, bool&) + 39
13      0x7fd72746a973p pthread_once + 83
14      0x7fd68d15d382p
15      0x7fd68cb9df64p ThreadPool::ThreadPool(unsigned long)::{lambda()#1}::operator()() const + 404
16      0x7fd69b7d98a0p
17      0x7fd7274651c3p
18      0x7fd726a8d12dp clone + 109

**Comment by minhozhou** [comment]
同出现，是啥原因呢，数据问题吗，我发现小数据没问题，提交集群训练一会儿就会出现，但又没定位
