### ISSUE TITLE
您好，这是关于Paddle.nn.Conv2D问题

### ISSUE THREAD

**Issue by lmk123568** [PaddlePaddle/Paddle#32028]
- 版本、环境信息
1）PaddlePaddle版本：2.0
2）CPU/GPU：GPU
3）系统环境：linux

您好，我是一名飞桨使用者，目前工作是论文的复现

```
class Net(nn.Conv2D):
    def __init__(self, channels, groups=1):
        super().__init__(in_channels=channels, out_channels=channels, kernel_size=1, stride=1, padding=0, groups=groups, bias_attr=False)

    def out(self):
        print(self.dilation)

a=Net(10)
a.out()
```
该输出会报错，查看源代码时候，发现conv2d类没有增加相应类变量，比如self.in_channels=in_channels，而上面的代码在torch可以运行，请问是否考虑增加类变量，让调用更加方便呢

**Comment by Leonardo-Ding** [comment]
您好，您提的问题我们会反馈给开发团队，技术讨论后看是否酌情合理增加，谢谢。

**Comment by lmk123568** [comment]
> 您好，您提的问题我们会反馈给开发团队，技术讨论后看是否酌情合理增加，谢谢。

已解决，需要加一个'_'，谢谢
