### ISSUE TITLE
Paddle大模型训练的demo与复现

### ISSUE THREAD

**Issue by reyoung** [PaddlePaddle/Paddle#3202]
Paddle can train a model without memory limitation in one Node. It should be added to our demo and make sure it can be run now.

**Comment by typhoonzero** [comment]
Related: https://github.com/PaddlePaddle/Paddle/issues/3199

**Comment by gongweibao** [comment]
Model CE should do this?

**Comment by Superjomn** [comment]
If this evaluation should be triggered periodically, then it's OK for CE to include it.

And it's feasible:

1. add another project to CE TeamCity which periodically run every day.
2. Start a service on an exclusive internal machine
3. Include this model in the CE-tasks, which has following `run.xsh`
```python
def execute_remote(server):
    send model to remote server
    trigger the evaluation
    get kpis(in JSON) when the task finished(timeout need to considered)

kpis = execute_remote(server_address)
persist(kpis) # follow class Kpi ...
```

4. Add some logics to CE framework

main.xsh:

```python
# task large_model
for task in tasks:
    if mode == "large_model":
        if task.mode == "large_model":
            ./task/run.xsh
    else:
        # same logics as before
```
