### ISSUE TITLE
不能加载so文件？

### ISSUE THREAD

**Issue by songsong-L** [PaddlePaddle/Paddle#32033]
![image](https://user-images.githubusercontent.com/54927708/113320673-57ccd400-9345-11eb-9c29-2d8aff93c6bb.png)
自定义op生成了so文件，加载时报错，提示设置环境变量，设置了之后还是报错？？

**Comment by Leonardo-Ding** [comment]
您好，看报错信息如果LD_LIBRARY_PATH设置.so的path没有问题，那么有可能是您自定义op时的方法有问题，请确认使用paddle 2.0官方推荐的方式添加自定义op（https://www.paddlepaddle.org.cn/documentation/docs/zh/guides/07_new_op/new_custom_op.html）

**Comment by songsong-L** [comment]
> 您好，看报错信息如果LD_LIBRARY_PATH设置.so的path没有问题，那么有可能是您自定义op时的方法有问题，请确认使用paddle 2.0官方推荐的方式添加自定义op（[https://www.paddlepaddle.org.cn/documentation/docs/zh/guides/07_new_op/new_custom_op.html）](https://www.paddlepaddle.org.cn/documentation/docs/zh/guides/07_new_op/new_custom_op.html%EF%BC%89)

用的是paddle1.8 。我有考虑这种情况，用教程中的relu2_op也报同样的错？如果定义有问题也能生成so？

**Comment by songsong-L** [comment]
会不会是aistudio上的gcc版本的问题，paddle是1.8，gcc我看了是7.5的

**Comment by songsong-L** [comment]
用paddle2也试了，有毒啊。。。
![image](https://user-images.githubusercontent.com/54927708/113412978-3d016a80-93ec-11eb-90fa-b50eb02562de.png)
