### ISSUE TITLE
制作PaddlePaddle开发镜像出现问题

### ISSUE THREAD

**Issue by liucide** [PaddlePaddle/Paddle#3204]
我是新手，就是最近在学习PaddlePaddle的时候,按照文档操作，在制作PaddlePaddle 输入docker build -t paddle：dev . 的时候出现的问题，不知道怎么解决，请给位帮忙，不胜感激。
![2017-08-03 13-58-18](https://user-images.githubusercontent.com/30512814/28908195-d7ce11ec-7854-11e7-86f7-9c2955ec2515.png)

**Comment by wangkuiyi** [comment]
```
ReadTimeoutError: HTTPSConnectionPool(host='pypi.python.org', port=443): Read timed out.
```

看上去是从上述server读数据超时了。是网络问题，不是PaddlePaddle的问题。

**Comment by wangkuiyi** [comment]
```
ReadTimeoutError: HTTPSConnectionPool(host='pypi.python.org', port=443):
Read timed out.
```

看上去是从上述server读数据超时了。是网络问题，不是PaddlePaddle的问题。

2017-08-02 23:08 GMT-07:00 liucide <notifications@github.com>:

**Comment by liucide** [comment]
收到，谢谢，请问我应该怎么处理呢？

在 2017-08-03 14:13:19，"Yi Wang" <notifications@github.com> 写道：
```
ReadTimeoutError: HTTPSConnectionPool(host='pypi.python.org', port=443):
Read timed out.
```

看上去是从上述server读数据超时了。是网络问题，不是PaddlePaddle的问题。

2017-08-02 23:08 GMT-07:00 liucide <notifications@github.com>:
