### ISSUE TITLE
AIstudio上不能使用自定义op？

### ISSUE THREAD

**Issue by songsong-L** [PaddlePaddle/Paddle#32058]
分别用paddlepaddle1.8.0和2.0.1在AIstudio上按各自的自定义op教程进行使用，直接使用教程上的自定义relu_op的案例，1.8.0的报错为设置环境变量LD_LIBRARY_PATH，设置之后还是报错找不到so文件。2.0.1的报错为
_gcc: error trying to exec 'cc1plus': execvp: No such file or directory
error: command 'gcc' failed with exit status 1_
aistudio的环境不让自定义op吗？？

**Comment by yinhaofeng** [comment]
aistudio上应该是不支持自定义op的，自定义op需要在op编写完成后重新编译，安装paddle才能生效。但是在aistudio中我们没有给您sudo权限，您是无法编译的，所以会找不到so文件。

**Comment by songsong-L** [comment]
> aistudio上应该是不支持自定义op的，自定义op需要在op编写完成后重新编译，安装paddle才能生效。但是在aistudio中我们没有给您sudo权限，您是无法编译的，所以会找不到so文件。

不是，我用的是外部定义。
1.8的版本的开发文档里
**_# custom_op.py
import paddle.fluid as fluid
# 调用load_op_library加载动态库
fluid.load_op_library('relu2_op.so')_**
确实加载不了so文件
==============================
2.0给的文档可以加载so文件，
**_# custom_op.py
import paddle.incubate as incubate
# 调用load_op_library加载动态库
incubate.load_op_library('relu2_op.so')_**
单个测试时能用，用在自己项目时又报错：
![image](https://user-images.githubusercontent.com/54927708/113651722-1762b280-96c5-11eb-998d-39f02f741b10.png)

**Comment by Aurelius84** [comment]
您好，若使用自定义op的旧方案，推荐您使用1.8.5稳定版本；若使用自定义op新的方案，从上面您描述的自定义OP的报错信息来看，应该是gcc/g++未正确配置，可以通过如下命令查看下配置信息：
```bash
which gcc
gcc --version

which g++
g++ --version
```
