### ISSUE TITLE
paddle如何清空gpu缓存

### ISSUE THREAD

**Issue by bbbxixixixi** [PaddlePaddle/Paddle#32057]
在aistudio上运行模型，一旦model.train调用后，就不让再次调用了
试着把pdx.model_built = False，但是前面占用的缓存不会被清除，而且运行会越来越慢
如果python接口不行，是否能通过其他调用方式清空？

**Comment by yinhaofeng** [comment]
1. 在aistudio中可以尝试直接使用高级版，并不需要付费只要完成一些简单的新手任务，即可每天登录获得时长。高级版拥有更大的内存供您使用。
2. 开启以下三个选项：
#一旦不再使用即释放内存垃圾，=1.0 垃圾占用内存大小达到10G时，释放内存垃圾
export FLAGS_eager_delete_tensor_gb=0.0
#启用快速垃圾回收策略，不等待cuda kernel 结束，直接释放显存
export FLAGS_fast_eager_deletion_mode=1
#该环境变量设置只占用0%的显存
export FLAGS_fraction_of_gpu_memory_to_use=0
3. 尝试减小batchsize以减少显存的使用
4. 详细可以参考https://www.paddlepaddle.org.cn/documentation/docs/zh/advanced_guide/performance_improving/singlenode_training_improving/memory_optimize.html
