### ISSUE TITLE
2.0动态图只用cpu训练，有办法多线程吗

### ISSUE THREAD

**Issue by Fzldq** [PaddlePaddle/Paddle#32054]
2.0动态图，CPU占用一直是130~150%，环境变量设置CPU_NUM=24了也没用。
看到文档里写着：spawn 目前仅支持 GPU collective模式.

请问有办法提高CPU利用率吗。

- 版本、环境信息：
    1）PaddlePaddle版本：2.0.2cpu版
    2）CPU：锐龙3900x
    3）GPU：我只想用CPU
    4）系统环境：20.04.1-Ubuntu，Python3.8.8

- 模型信息
    1）LeNet 2）手写数字识别 4) https://www.paddlepaddle.org.cn/tutorials/projectdetail/1630501 （官方教程，use_gpu设置成False, export CPU_NUM=12, FLAGS_paddle_num_threads=24）

**Comment by qili93** [comment]
可以尝试一下在环境变量中输出

```bash
export FLAGS_paddle_num_threads=24
```

**Comment by Fzldq** [comment]
> 可以尝试一下在环境变量中输出
> 
> ```shell
> export FLAGS_paddle_num_threads=24
> ```

你好，改了之后cpu利用率还是只有140%。
一楼更新了一下系统信息。
