### ISSUE TITLE
我使用paddleX预测，paddle报了个异常

### ISSUE THREAD

**Issue by Reatris** [PaddlePaddle/Paddle#32067]
虽然没啥影响，还是来说下 

`paddlepaddle-gpu==2.0.1`

`paddlex ==1.37`

异常内容：

`(PreconditionNotMet) The variable named im_info is not found in the scope of the exector.
  [Hint: executor_->scope()->FindVar(name) should not be null.] (at D:\v2.0.1\paddle\paddle\fluid\inference\api\analysis_predictor.cc:791)`

此段异常内容在paddlex使用`segmenter-HRNet`预测的时候会出现

**Comment by littletomatodonkey** [comment]
你好，看着是im_info这个var没有被获取到，可以先查看下该变量是否被正确创建并赋值

**Comment by FlyingQianMM** [comment]
分割网络里面没有im_info这个输入tensor，请问您是直接使用的paddlex c++部署代码进行预测的吗？是否有做一些修改呢？

**Comment by dwSun** [comment]
我也碰到了这个问题，只在windows上出现了，同样的代码，在 linux/mac 下面没有出现。
我用的 unet，试了gpu/cpu 打开或者关闭mkl，都会出现这个问题，unet的模型是用 paddlex客户端训练的

**Comment by heliqi** [comment]
paddlepaddle 使用2.0+， 对应paddlex 需要升级到2.0。 如果paddlex 想使用1.x版本， paddle版本需要降到1.x(比如1.8.5)

**Comment by dwSun** [comment]
> paddlepaddle 使用2.0+， 对应paddlex 需要升级到2.0。 如果paddlex 想使用1.x版本， paddle版本需要降到1.x(比如1.8.5)

我的问题，通过安装1.8.5 版本的 paddlepaddle 可以解决。

我的 paddlex 版本为 1.3.10

我使用的是 windows 的 GPU 版本
