### ISSUE TITLE
使用官方预测库报错

### ISSUE THREAD

**Issue by wenjiett** [PaddlePaddle/Paddle#32060]
我在使用官网提供的预测库时遇到报错

相关信息：
    vs版本-vs2019
    cuda-10.0
    cudnn-7.6.5
    c++预测库版本-cuda10.0_cudnn7_avx_mkl_trt6
    预测库version.txt文件内容：
    GIT COMMIT ID: ffa88c31c2da5090c6f70e8e9b523356d7cd5e7f
    WITH_MKL: ON
    WITH_MKLDNN: ON
    WITH_GPU: ON
    CUDA version: 10.0
    CUDNN version: v7.4
    CXX compiler version: 19.0.24215.1
    WITH_TENSORRT: ON
    TensorRT version: v6

代码信息：
#include "paddle/include/paddle_inference_api.h"
#include <chrono>
#include <iostream>
#include <memory>
#include <numeric>
#include <gflags/gflags.h>
#include <glog/logging.h>

using paddle_infer::Config;
using paddle_infer::Predictor;
using paddle_infer::CreatePredictor;

DEFINE_string(model_file, "", "Directory of the inference model.");
DEFINE_string(params_file, "", "Directory of the inference model.");
DEFINE_string(model_dir, "", "Directory of the inference model.");
DEFINE_int32(batch_size, 1, "Directory of the inference model.");
DEFINE_bool(use_gpu, false, "enable gpu");
DEFINE_bool(use_mkldnn, false, "enable mkldnn");
DEFINE_bool(mem_optim, false, "enable memory optimize");

using Time = decltype(std::chrono::high_resolution_clock::now());
Time time() { return std::chrono::high_resolution_clock::now(); };
double time_diff(Time t1, Time t2) {
    typedef std::chrono::microseconds ms;
    auto diff = t2 - t1;
    ms counter = std::chrono::duration_cast<ms>(diff);
    return counter.count();
}

std::shared_ptr<Predictor> InitPredictor() {
    Config config;
    if (FLAGS_model_dir != "") {
        config.SetModel(FLAGS_model_dir);
    }
    else {
        config.SetModel(FLAGS_model_file, FLAGS_params_file);
    }
    if (FLAGS_use_gpu) {
        config.EnableUseGpu(100, 0);
    }
    if (FLAGS_use_mkldnn) {
        config.EnableMKLDNN();
    }
    // Open the memory optim.
    if (FLAGS_mem_optim) {
        config.EnableMemoryOptim();
    }
    return CreatePredictor(config);
}

void run(Predictor* predictor, const std::vector<float>& input,
    const std::vector<int>& input_shape, const std::vector<float>& input_im,
    const std::vector<int>& input_im_shape, std::vector<float>* out_data) {
    auto input_names = predictor->GetInputNames();
    auto im_shape_handle = predictor->GetInputHandle(input_names[0]);
    im_shape_handle->Reshape(input_im_shape);
    im_shape_handle->CopyFromCpu(input_im.data());

    auto image_handle = predictor->GetInputHandle(input_names[1]);
    image_handle->Reshape(input_shape);
    image_handle->CopyFromCpu(input_im.data());

    auto scale_factor_handle = predictor->GetInputHandle(input_names[2]);
    scale_factor_handle->Reshape(input_im_shape);
    scale_factor_handle->CopyFromCpu(input_im.data());

    CHECK(predictor->Run());

    auto output_names = predictor->GetOutputNames();
    auto output_t = predictor->GetOutputHandle(output_names[0]);
    std::vector<int> output_shape = output_t->shape();
    int out_num = std::accumulate(output_shape.begin(), output_shape.end(), 1,
        std::multiplies<int>());

    out_data->resize(out_num);
    output_t->CopyToCpu(out_data->data());
}

int main(int argc, char* argv[]) {
    google::ParseCommandLineFlags(&argc, &argv, true);
    auto predictor = InitPredictor();

    const int height = 608;
    const int width = 608;
    const int channels = 3;
    std::vector<int> input_shape = { FLAGS_batch_size, channels, height, width };
    std::vector<float> input_data(FLAGS_batch_size * channels * height * width);
    for (size_t i = 0; i < input_data.size(); ++i) {
        input_data[i] = i % 255 * 0.13f;
    }
    std::vector<int> input_im_shape = { FLAGS_batch_size, 2 };
    std::vector<float> input_im_data(FLAGS_batch_size * 2, 608);

    std::vector<float> out_data;
    run(predictor.get(), input_data, input_shape, input_im_data, input_im_shape,
        &out_data);
    LOG(INFO) << "output num is " << out_data.size();
    return 0;
}

报错信息：
严重性	代码	说明	项目	文件	行	禁止显示状态
错误	LNK2001	无法解析的外部符号 "__declspec(dllimport) public: __cdecl google::LogMessageFatal::~LogMessageFatal(void)" (__imp_??1LogMessageFatal@google@@QEAA@XZ)	paddle_test	H:\OpenCV_C++_code\paddle_test\paddle_test\main.obj	1	
警告	C26495	未初始化变量 paddle::AnalysisConfig::lite_precision_mode_。始终初始化成员变量(type.6)。	paddle_test	G:\paddle_inference_install_dir\paddle\include\paddle_analysis_config.h	64	
警告	C26495	未初始化变量 paddle::AnalysisConfig::lite_zero_copy_。始终初始化成员变量(type.6)。	paddle_test	G:\paddle_inference_install_dir\paddle\include\paddle_analysis_config.h	64	
警告	C26495	未初始化变量 paddle::AnalysisConfig::xpu_l3_workspace_size_。始终初始化成员变量(type.6)。	paddle_test	G:\paddle_inference_install_dir\paddle\include\paddle_analysis_config.h	64	
警告	C26495	未初始化变量 paddle::ZeroCopyTensor::device_。始终初始化成员变量(type.6)。	paddle_test	G:\paddle_inference_install_dir\paddle\include\paddle_api.h	232	
警告	C26495	未初始化变量 paddle::ZeroCopyTensor::dtype_。始终初始化成员变量(type.6)。	paddle_test	G:\paddle_inference_install_dir\paddle\include\paddle_api.h	232	
警告	C26495	未初始化变量 paddle::ZeroCopyTensor::input_or_output_。始终初始化成员变量(type.6)。	paddle_test	G:\paddle_inference_install_dir\paddle\include\paddle_api.h	232	
警告	C26495	未初始化变量 paddle::ZeroCopyTensor::place_。始终初始化成员变量(type.6)。	paddle_test	G:\paddle_inference_install_dir\paddle\include\paddle_api.h	232	
警告	C26439	可能不会 throw 此类型的函数。将其声明为 "noexcept" (f.6)。	paddle_test	G:\paddle_inference_install_dir\third_party\install\glog\include\glog\logging.h	1631	
警告	C26451	算术溢出: 使用 4 字节值上的运算符 * ，然后将结果转换到 8 字节值。在调用运算符 * 之前将值强制转换为宽类型可避免溢出(io.2)。	paddle_test	H:\OpenCV_C++_code\paddle_test\paddle_test\main.cpp	89	
警告	C26451	算术溢出: 使用 4 字节值上的运算符 * ，然后将结果转换到 8 字节值。在调用运算符 * 之前将值强制转换为宽类型可避免溢出(io.2)。	paddle_test	H:\OpenCV_C++_code\paddle_test\paddle_test\main.cpp	94	
警告	C4251	“paddle::PaddleTensor::name”: class“std::basic_string<char,std::char_traits<char>,std::allocator<char>>”需要有 dll 接口由 struct“paddle::PaddleTensor”的客户端使用	paddle_test	G:\paddle_inference_install_dir\paddle\include\paddle_api.h	157	
警告	C4251	“paddle::PaddleTensor::shape”: class“std::vector<int,std::allocator<int>>”需要有 dll 接口由 struct“paddle::PaddleTensor”的客户端使用	paddle_test	G:\paddle_inference_install_dir\paddle\include\paddle_api.h	158	
警告	C4251	“paddle::PaddleTensor::lod”: class“std::vector<std::vector<size_t,std::allocator<size_t>>,std::allocator<std::vector<size_t,std::allocator<size_t>>>>”需要有 dll 接口由 struct“paddle::PaddleTensor”的客户端使用	paddle_test	G:\paddle_inference_install_dir\paddle\include\paddle_api.h	161	
警告	C4251	“paddle::ZeroCopyTensor::name_”: class“std::basic_string<char,std::char_traits<char>,std::allocator<char>>”需要有 dll 接口由 class“paddle::ZeroCopyTensor”的客户端使用	paddle_test	G:\paddle_inference_install_dir\paddle\include\paddle_api.h	237	
警告	C4251	“paddle::NativeConfig::prog_file”: class“std::basic_string<char,std::char_traits<char>,std::allocator<char>>”需要有 dll 接口由 struct“paddle::NativeConfig”的客户端使用	paddle_test	G:\paddle_inference_install_dir\paddle\include\paddle_api.h	369	
警告	C4251	“paddle::NativeConfig::param_file”: class“std::basic_string<char,std::char_traits<char>,std::allocator<char>>”需要有 dll 接口由 struct“paddle::NativeConfig”的客户端使用	paddle_test	G:\paddle_inference_install_dir\paddle\include\paddle_api.h	371	
警告	C4251	“paddle::PaddlePassBuilder::analysis_passes_”: class“std::vector<std::string,std::allocator<std::string>>”需要有 dll 接口由 class“paddle::PaddlePassBuilder”的客户端使用	paddle_test	G:\paddle_inference_install_dir\paddle\include\paddle_pass_builder.h	110	
警告	C4251	“paddle::PaddlePassBuilder::passes_”: class“std::vector<std::string,std::allocator<std::string>>”需要有 dll 接口由 class“paddle::PaddlePassBuilder”的客户端使用	paddle_test	G:\paddle_inference_install_dir\paddle\include\paddle_pass_builder.h	111	
警告	C4251	“paddle::AnalysisConfig::model_dir_”: class“std::basic_string<char,std::char_traits<char>,std::allocator<char>>”需要有 dll 接口由 struct“paddle::AnalysisConfig”的客户端使用	paddle_test	G:\paddle_inference_install_dir\paddle\include\paddle_analysis_config.h	588	
警告	C4251	“paddle::AnalysisConfig::prog_file_”: class“std::basic_string<char,std::char_traits<char>,std::allocator<char>>”需要有 dll 接口由 struct“paddle::AnalysisConfig”的客户端使用	paddle_test	G:\paddle_inference_install_dir\paddle\include\paddle_analysis_config.h	589	
警告	C4251	“paddle::AnalysisConfig::params_file_”: class“std::basic_string<char,std::char_traits<char>,std::allocator<char>>”需要有 dll 接口由 struct“paddle::AnalysisConfig”的客户端使用	paddle_test	G:\paddle_inference_install_dir\paddle\include\paddle_analysis_config.h	590	
警告	C4251	“paddle::AnalysisConfig::min_input_shape_”: class“std::map<std::string,std::vector<int,std::allocator<int>>,std::less<std::string>,std::allocator<std::pair<const std::string,std::vector<int,std::allocator<int>>>>>”需要有 dll 接口由 struct“paddle::AnalysisConfig”的客户端使用	paddle_test	G:\paddle_inference_install_dir\paddle\include\paddle_analysis_config.h	624	
警告	C4251	“paddle::AnalysisConfig::max_input_shape_”: class“std::map<std::string,std::vector<int,std::allocator<int>>,std::less<std::string>,std::allocator<std::pair<const std::string,std::vector<int,std::allocator<int>>>>>”需要有 dll 接口由 struct“paddle::AnalysisConfig”的客户端使用	paddle_test	G:\paddle_inference_install_dir\paddle\include\paddle_analysis_config.h	625	
警告	C4251	“paddle::AnalysisConfig::optim_input_shape_”: class“std::map<std::string,std::vector<int,std::allocator<int>>,std::less<std::string>,std::allocator<std::pair<const std::string,std::vector<int,std::allocator<int>>>>>”需要有 dll 接口由 struct“paddle::AnalysisConfig”的客户端使用	paddle_test	G:\paddle_inference_install_dir\paddle\include\paddle_analysis_config.h	626	
警告	C4251	“paddle::AnalysisConfig::trt_disabled_ops_”: class“std::vector<std::string,std::allocator<std::string>>”需要有 dll 接口由 struct“paddle::AnalysisConfig”的客户端使用	paddle_test	G:\paddle_inference_install_dir\paddle\include\paddle_analysis_config.h	627	
警告	C4251	“paddle::AnalysisConfig::mkldnn_enabled_op_types_”: class“std::unordered_set<std::string,std::hash<std::string>,std::equal_to<std::string>,std::allocator<std::string>>”需要有 dll 接口由 struct“paddle::AnalysisConfig”的客户端使用	paddle_test	G:\paddle_inference_install_dir\paddle\include\paddle_analysis_config.h	634	
警告	C4251	“paddle::AnalysisConfig::serialized_info_cache_”: class“std::basic_string<char,std::char_traits<char>,std::allocator<char>>”需要有 dll 接口由 struct“paddle::AnalysisConfig”的客户端使用	paddle_test	G:\paddle_inference_install_dir\paddle\include\paddle_analysis_config.h	651	
警告	C4251	“paddle::AnalysisConfig::pass_builder_”: class“std::unique_ptr<paddle::PassStrategy,std::default_delete<paddle::PassStrategy>>”需要有 dll 接口由 struct“paddle::AnalysisConfig”的客户端使用	paddle_test	G:\paddle_inference_install_dir\paddle\include\paddle_analysis_config.h	653	
警告	C4251	“paddle::AnalysisConfig::lite_passes_filter_”: class“std::vector<std::string,std::allocator<std::string>>”需要有 dll 接口由 struct“paddle::AnalysisConfig”的客户端使用	paddle_test	G:\paddle_inference_install_dir\paddle\include\paddle_analysis_config.h	656	
警告	C4251	“paddle::AnalysisConfig::lite_ops_filter_”: class“std::vector<std::string,std::allocator<std::string>>”需要有 dll 接口由 struct“paddle::AnalysisConfig”的客户端使用	paddle_test	G:\paddle_inference_install_dir\paddle\include\paddle_analysis_config.h	657	
警告	C4251	“paddle::AnalysisConfig::mkldnn_quantizer_config_”: class“std::shared_ptr<paddle::MkldnnQuantizerConfig>”需要有 dll 接口由 struct“paddle::AnalysisConfig”的客户端使用	paddle_test	G:\paddle_inference_install_dir\paddle\include\paddle_analysis_config.h	668	
警告	C4251	“paddle::AnalysisConfig::bfloat16_enabled_op_types_”: class“std::unordered_set<std::string,std::hash<std::string>,std::equal_to<std::string>,std::allocator<std::string>>”需要有 dll 接口由 struct“paddle::AnalysisConfig”的客户端使用	paddle_test	G:\paddle_inference_install_dir\paddle\include\paddle_analysis_config.h	670	
警告	C4251	“paddle::AnalysisConfig::opt_cache_dir_”: class“std::basic_string<char,std::char_traits<char>,std::allocator<char>>”需要有 dll 接口由 struct“paddle::AnalysisConfig”的客户端使用	paddle_test	G:\paddle_inference_install_dir\paddle\include\paddle_analysis_config.h	677	
警告	C4244	“return”: 从“const uint64_t”转换到“int”，可能丢失数据	paddle_test	G:\paddle_inference_install_dir\paddle\include\paddle_analysis_config.h	210	
警告	C4251	“paddle_infer::Tensor::tensor_”: class“std::unique_ptr<paddle::ZeroCopyTensor,std::default_delete<paddle::ZeroCopyTensor>>”需要有 dll 接口由 class“paddle_infer::Tensor”的客户端使用	paddle_test	G:\paddle_inference_install_dir\paddle\include\paddle_inference_api.h	133	
警告	C4251	“paddle_infer::Predictor::predictor_”: class“std::unique_ptr<paddle::PaddlePredictor,std::default_delete<paddle::PaddlePredictor>>”需要有 dll 接口由 class“paddle_infer::Predictor”的客户端使用	paddle_test	G:\paddle_inference_install_dir\paddle\include\paddle_inference_api.h	239	
警告	C4251	“paddle_infer::services::PredictorPool::main_pred_”: class“std::shared_ptr<paddle_infer::Predictor>”需要有 dll 接口由 class“paddle_infer::services::PredictorPool”的客户端使用	paddle_test	G:\paddle_inference_install_dir\paddle\include\paddle_inference_api.h	307	
警告	C4251	“paddle_infer::services::PredictorPool::preds_”: class“std::vector<std::unique_ptr<paddle_infer::Predictor,std::default_delete<paddle_infer::Predictor>>,std::allocator<std::unique_ptr<paddle_infer::Predictor,std::default_delete<paddle_infer::Predictor>>>>”需要有 dll 接口由 class“paddle_infer::services::PredictorPool”的客户端使用	paddle_test	G:\paddle_inference_install_dir\paddle\include\paddle_inference_api.h	308	
警告	C4244	“return”: 从“_Rep”转换到“double”，可能丢失数据	paddle_test	H:\OpenCV_C++_code\paddle_test\paddle_test\main.cpp	29	
错误	LNK2001	无法解析的外部符号 "unsigned int __cdecl google::ParseCommandLineFlags(int *,char * * *,bool)" (?ParseCommandLineFlags@google@@YAIPEAHPEAPEAPEAD_N@Z)	paddle_test	H:\OpenCV_C++_code\paddle_test\paddle_test\main.obj	1	
错误	LNK2001	无法解析的外部符号 "__declspec(dllimport) public: __cdecl google::LogMessageFatal::LogMessageFatal(char const *,int)" (__imp_??0LogMessageFatal@google@@QEAA@PEBDH@Z)	paddle_test	H:\OpenCV_C++_code\paddle_test\paddle_test\main.obj	1	
错误	LNK2001	无法解析的外部符号 "public: __cdecl google::FlagRegisterer::FlagRegisterer<bool>(char const *,char const *,char const *,bool *,bool *)" (??$?0_N@FlagRegisterer@google@@QEAA@PEBD00PEA_N1@Z)	paddle_test	H:\OpenCV_C++_code\paddle_test\paddle_test\main.obj	1	
错误	LNK2001	无法解析的外部符号 "public: __cdecl google::FlagRegisterer::FlagRegisterer<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > >(char const *,char const *,char const *,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > *,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > *)" (??$?0V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@FlagRegisterer@google@@QEAA@PEBD00PEAV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@1@Z)	paddle_test	H:\OpenCV_C++_code\paddle_test\paddle_test\main.obj	1	
错误	LNK2001	无法解析的外部符号 "public: __cdecl google::FlagRegisterer::FlagRegisterer<int>(char const *,char const *,char const *,int *,int *)" (??$?0H@FlagRegisterer@google@@QEAA@PEBD00PEAH1@Z)	paddle_test	H:\OpenCV_C++_code\paddle_test\paddle_test\main.obj	1	
错误	LNK2001	无法解析的外部符号 "__declspec(dllimport) public: class std::basic_ostream<char,struct std::char_traits<char> > & __cdecl google::LogMessage::stream(void)" (__imp_?stream@LogMessage@google@@QEAAAEAV?$basic_ostream@DU?$char_traits@D@std@@@std@@XZ)	paddle_test	H:\OpenCV_C++_code\paddle_test\paddle_test\main.obj	1	
错误	LNK2001	无法解析的外部符号 "__declspec(dllimport) public: __cdecl google::LogMessage::~LogMessage(void)" (__imp_??1LogMessage@google@@QEAA@XZ)	paddle_test	H:\OpenCV_C++_code\paddle_test\paddle_test\main.obj	1	
错误	LNK2001	无法解析的外部符号 "__declspec(dllimport) public: __cdecl google::LogMessage::LogMessage(char const *,int)" (__imp_??0LogMessage@google@@QEAA@PEBDH@Z)	paddle_test	H:\OpenCV_C++_code\paddle_test\paddle_test\main.obj	1	
错误	LNK2001	无法解析的外部符号 "__declspec(dllimport) public: void __cdecl google::LogMessageVoidify::operator&(class std::basic_ostream<char,struct std::char_traits<char> > &)" (__imp_??ILogMessageVoidify@google@@QEAAXAEAV?$basic_ostream@DU?$char_traits@D@std@@@std@@@Z)	paddle_test	H:\OpenCV_C++_code\paddle_test\paddle_test\main.obj	1	
错误	LNK2001	无法解析的外部符号 "__declspec(dllimport) public: __cdecl google::LogMessageVoidify::LogMessageVoidify(void)" (__imp_??0LogMessageVoidify@google@@QEAA@XZ)	paddle_test	H:\OpenCV_C++_code\paddle_test\paddle_test\main.obj	1	
错误	LNK1120	11 个无法解析的外部命令	paddle_test	H:\OpenCV_C++_code\paddle_test\x64\Release\paddle_test.exe	1	

请问一下该如何解决呢？

**Comment by yinhaofeng** [comment]
看报错是glog的符号没有定义，您是不是没有链接glog？

**Comment by T8T9** [comment]
请确认 LD_LIBRARY_PATH 设置正确，参考： https://paddleinference.paddlepaddle.org.cn/quick_start/cpp_demo.html#id5

**Comment by wenjiett** [comment]
> 看报错是glog的符号没有定义，您是不是没有链接glog？

我在包含目录里有添加glog的目录，后来我在附加依赖项里添加了paddle_inference.dll文件后，又出现了新的错误，dll文件无效或损坏
报错信息：
严重性	代码	说明	项目	文件	行	禁止显示状态
警告	C4251	“paddle::AnalysisConfig::bfloat16_enabled_op_types_”: class“std::unordered_set<std::string,std::hash<std::string>,std::equal_to<std::string>,std::allocator<std::string>>”需要有 dll 接口由 struct“paddle::AnalysisConfig”的客户端使用	paddle_test	G:\paddle_inference_install_dir\paddle\include\paddle_analysis_config.h	670	
警告	C26495	未初始化变量 paddle::AnalysisConfig::lite_precision_mode_。始终初始化成员变量(type.6)。	paddle_test	G:\paddle_inference_install_dir\paddle\include\paddle_analysis_config.h	64	
警告	C26495	未初始化变量 paddle::AnalysisConfig::lite_zero_copy_。始终初始化成员变量(type.6)。	paddle_test	G:\paddle_inference_install_dir\paddle\include\paddle_analysis_config.h	64	
警告	C26495	未初始化变量 paddle::AnalysisConfig::xpu_l3_workspace_size_。始终初始化成员变量(type.6)。	paddle_test	G:\paddle_inference_install_dir\paddle\include\paddle_analysis_config.h	64	
警告	C26495	未初始化变量 paddle::ZeroCopyTensor::device_。始终初始化成员变量(type.6)。	paddle_test	G:\paddle_inference_install_dir\paddle\include\paddle_api.h	232	
警告	C26495	未初始化变量 paddle::ZeroCopyTensor::dtype_。始终初始化成员变量(type.6)。	paddle_test	G:\paddle_inference_install_dir\paddle\include\paddle_api.h	232	
警告	C26495	未初始化变量 paddle::ZeroCopyTensor::input_or_output_。始终初始化成员变量(type.6)。	paddle_test	G:\paddle_inference_install_dir\paddle\include\paddle_api.h	232	
警告	C26495	未初始化变量 paddle::ZeroCopyTensor::place_。始终初始化成员变量(type.6)。	paddle_test	G:\paddle_inference_install_dir\paddle\include\paddle_api.h	232	
警告	C26439	可能不会 throw 此类型的函数。将其声明为 "noexcept" (f.6)。	paddle_test	G:\paddle_inference_install_dir\third_party\install\glog\include\glog\logging.h	1631	
警告	C26451	算术溢出: 使用 4 字节值上的运算符 * ，然后将结果转换到 8 字节值。在调用运算符 * 之前将值强制转换为宽类型可避免溢出(io.2)。	paddle_test	H:\OpenCV_C++_code\paddle_test\paddle_test\main.cpp	89	
警告	C26451	算术溢出: 使用 4 字节值上的运算符 * ，然后将结果转换到 8 字节值。在调用运算符 * 之前将值强制转换为宽类型可避免溢出(io.2)。	paddle_test	H:\OpenCV_C++_code\paddle_test\paddle_test\main.cpp	94	
警告	C4251	“paddle::PaddleTensor::name”: class“std::basic_string<char,std::char_traits<char>,std::allocator<char>>”需要有 dll 接口由 struct“paddle::PaddleTensor”的客户端使用	paddle_test	G:\paddle_inference_install_dir\paddle\include\paddle_api.h	157	
警告	C4251	“paddle::PaddleTensor::shape”: class“std::vector<int,std::allocator<int>>”需要有 dll 接口由 struct“paddle::PaddleTensor”的客户端使用	paddle_test	G:\paddle_inference_install_dir\paddle\include\paddle_api.h	158	
警告	C4251	“paddle::PaddleTensor::lod”: class“std::vector<std::vector<size_t,std::allocator<size_t>>,std::allocator<std::vector<size_t,std::allocator<size_t>>>>”需要有 dll 接口由 struct“paddle::PaddleTensor”的客户端使用	paddle_test	G:\paddle_inference_install_dir\paddle\include\paddle_api.h	161	
警告	C4251	“paddle::ZeroCopyTensor::name_”: class“std::basic_string<char,std::char_traits<char>,std::allocator<char>>”需要有 dll 接口由 class“paddle::ZeroCopyTensor”的客户端使用	paddle_test	G:\paddle_inference_install_dir\paddle\include\paddle_api.h	237	
警告	C4251	“paddle::NativeConfig::prog_file”: class“std::basic_string<char,std::char_traits<char>,std::allocator<char>>”需要有 dll 接口由 struct“paddle::NativeConfig”的客户端使用	paddle_test	G:\paddle_inference_install_dir\paddle\include\paddle_api.h	369	
警告	C4251	“paddle::NativeConfig::param_file”: class“std::basic_string<char,std::char_traits<char>,std::allocator<char>>”需要有 dll 接口由 struct“paddle::NativeConfig”的客户端使用	paddle_test	G:\paddle_inference_install_dir\paddle\include\paddle_api.h	371	
警告	C4251	“paddle::PaddlePassBuilder::analysis_passes_”: class“std::vector<std::string,std::allocator<std::string>>”需要有 dll 接口由 class“paddle::PaddlePassBuilder”的客户端使用	paddle_test	G:\paddle_inference_install_dir\paddle\include\paddle_pass_builder.h	110	
警告	C4251	“paddle::PaddlePassBuilder::passes_”: class“std::vector<std::string,std::allocator<std::string>>”需要有 dll 接口由 class“paddle::PaddlePassBuilder”的客户端使用	paddle_test	G:\paddle_inference_install_dir\paddle\include\paddle_pass_builder.h	111	
警告	C4251	“paddle::AnalysisConfig::model_dir_”: class“std::basic_string<char,std::char_traits<char>,std::allocator<char>>”需要有 dll 接口由 struct“paddle::AnalysisConfig”的客户端使用	paddle_test	G:\paddle_inference_install_dir\paddle\include\paddle_analysis_config.h	588	
警告	C4251	“paddle::AnalysisConfig::prog_file_”: class“std::basic_string<char,std::char_traits<char>,std::allocator<char>>”需要有 dll 接口由 struct“paddle::AnalysisConfig”的客户端使用	paddle_test	G:\paddle_inference_install_dir\paddle\include\paddle_analysis_config.h	589	
警告	C4251	“paddle::AnalysisConfig::params_file_”: class“std::basic_string<char,std::char_traits<char>,std::allocator<char>>”需要有 dll 接口由 struct“paddle::AnalysisConfig”的客户端使用	paddle_test	G:\paddle_inference_install_dir\paddle\include\paddle_analysis_config.h	590	
警告	C4251	“paddle::AnalysisConfig::min_input_shape_”: class“std::map<std::string,std::vector<int,std::allocator<int>>,std::less<std::string>,std::allocator<std::pair<const std::string,std::vector<int,std::allocator<int>>>>>”需要有 dll 接口由 struct“paddle::AnalysisConfig”的客户端使用	paddle_test	G:\paddle_inference_install_dir\paddle\include\paddle_analysis_config.h	624	
警告	C4251	“paddle::AnalysisConfig::max_input_shape_”: class“std::map<std::string,std::vector<int,std::allocator<int>>,std::less<std::string>,std::allocator<std::pair<const std::string,std::vector<int,std::allocator<int>>>>>”需要有 dll 接口由 struct“paddle::AnalysisConfig”的客户端使用	paddle_test	G:\paddle_inference_install_dir\paddle\include\paddle_analysis_config.h	625	
警告	C4251	“paddle::AnalysisConfig::optim_input_shape_”: class“std::map<std::string,std::vector<int,std::allocator<int>>,std::less<std::string>,std::allocator<std::pair<const std::string,std::vector<int,std::allocator<int>>>>>”需要有 dll 接口由 struct“paddle::AnalysisConfig”的客户端使用	paddle_test	G:\paddle_inference_install_dir\paddle\include\paddle_analysis_config.h	626	
警告	C4251	“paddle::AnalysisConfig::trt_disabled_ops_”: class“std::vector<std::string,std::allocator<std::string>>”需要有 dll 接口由 struct“paddle::AnalysisConfig”的客户端使用	paddle_test	G:\paddle_inference_install_dir\paddle\include\paddle_analysis_config.h	627	
警告	C4251	“paddle::AnalysisConfig::mkldnn_enabled_op_types_”: class“std::unordered_set<std::string,std::hash<std::string>,std::equal_to<std::string>,std::allocator<std::string>>”需要有 dll 接口由 struct“paddle::AnalysisConfig”的客户端使用	paddle_test	G:\paddle_inference_install_dir\paddle\include\paddle_analysis_config.h	634	
警告	C4251	“paddle::AnalysisConfig::serialized_info_cache_”: class“std::basic_string<char,std::char_traits<char>,std::allocator<char>>”需要有 dll 接口由 struct“paddle::AnalysisConfig”的客户端使用	paddle_test	G:\paddle_inference_install_dir\paddle\include\paddle_analysis_config.h	651	
警告	C4251	“paddle::AnalysisConfig::pass_builder_”: class“std::unique_ptr<paddle::PassStrategy,std::default_delete<paddle::PassStrategy>>”需要有 dll 接口由 struct“paddle::AnalysisConfig”的客户端使用	paddle_test	G:\paddle_inference_install_dir\paddle\include\paddle_analysis_config.h	653	
警告	C4251	“paddle::AnalysisConfig::lite_passes_filter_”: class“std::vector<std::string,std::allocator<std::string>>”需要有 dll 接口由 struct“paddle::AnalysisConfig”的客户端使用	paddle_test	G:\paddle_inference_install_dir\paddle\include\paddle_analysis_config.h	656	
警告	C4251	“paddle::AnalysisConfig::lite_ops_filter_”: class“std::vector<std::string,std::allocator<std::string>>”需要有 dll 接口由 struct“paddle::AnalysisConfig”的客户端使用	paddle_test	G:\paddle_inference_install_dir\paddle\include\paddle_analysis_config.h	657	
警告	C4251	“paddle::AnalysisConfig::mkldnn_quantizer_config_”: class“std::shared_ptr<paddle::MkldnnQuantizerConfig>”需要有 dll 接口由 struct“paddle::AnalysisConfig”的客户端使用	paddle_test	G:\paddle_inference_install_dir\paddle\include\paddle_analysis_config.h	668	
警告	C4251	“paddle::AnalysisConfig::opt_cache_dir_”: class“std::basic_string<char,std::char_traits<char>,std::allocator<char>>”需要有 dll 接口由 struct“paddle::AnalysisConfig”的客户端使用	paddle_test	G:\paddle_inference_install_dir\paddle\include\paddle_analysis_config.h	677	
警告	C4244	“return”: 从“const uint64_t”转换到“int”，可能丢失数据	paddle_test	G:\paddle_inference_install_dir\paddle\include\paddle_analysis_config.h	210	
警告	C4251	“paddle_infer::Tensor::tensor_”: class“std::unique_ptr<paddle::ZeroCopyTensor,std::default_delete<paddle::ZeroCopyTensor>>”需要有 dll 接口由 class“paddle_infer::Tensor”的客户端使用	paddle_test	G:\paddle_inference_install_dir\paddle\include\paddle_inference_api.h	133	
警告	C4251	“paddle_infer::Predictor::predictor_”: class“std::unique_ptr<paddle::PaddlePredictor,std::default_delete<paddle::PaddlePredictor>>”需要有 dll 接口由 class“paddle_infer::Predictor”的客户端使用	paddle_test	G:\paddle_inference_install_dir\paddle\include\paddle_inference_api.h	239	
警告	C4251	“paddle_infer::services::PredictorPool::main_pred_”: class“std::shared_ptr<paddle_infer::Predictor>”需要有 dll 接口由 class“paddle_infer::services::PredictorPool”的客户端使用	paddle_test	G:\paddle_inference_install_dir\paddle\include\paddle_inference_api.h	307	
警告	C4251	“paddle_infer::services::PredictorPool::preds_”: class“std::vector<std::unique_ptr<paddle_infer::Predictor,std::default_delete<paddle_infer::Predictor>>,std::allocator<std::unique_ptr<paddle_infer::Predictor,std::default_delete<paddle_infer::Predictor>>>>”需要有 dll 接口由 class“paddle_infer::services::PredictorPool”的客户端使用	paddle_test	G:\paddle_inference_install_dir\paddle\include\paddle_inference_api.h	308	
警告	C4244	“return”: 从“_Rep”转换到“double”，可能丢失数据	paddle_test	H:\OpenCV_C++_code\paddle_test\paddle_test\main.cpp	29	
错误	LNK1107	文件无效或损坏: 无法在 0x3F8 处读取	paddle_test	G:\paddle_inference_install_dir\paddle\lib\paddle_inference.dll	1
