### ISSUE TITLE
请问paddle中如何实现稀疏向量的操作

### ISSUE THREAD

**Issue by BlackHorseQ** [PaddlePaddle/Paddle#32066]
请问paddle2.0中如何实现稀疏向量的操作

**Comment by littletomatodonkey** [comment]
你好，以embedding为例，可以使用sparse这个参数，实现稀疏更新

https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/nn/functional/input/embedding_cn.html#embedding

**Comment by BlackHorseQ** [comment]
> 你好，以embedding为例，可以使用sparse这个参数，实现稀疏更新
> 
> https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/nn/functional/input/embedding_cn.html#embedding

你好，paddle。只有这一个函数里有sparse，其他都没有怎么办。

**Comment by dingjiaweiww** [comment]
@BlackHorseQ 请问你是在什么场景中想用到稀疏矩阵呢？

**Comment by BlackHorseQ** [comment]
图神经网络> @BlackHorseQ 请问你是在什么场景中想用到稀疏矩阵呢？
> 
>

**Comment by dingjiaweiww** [comment]
您可以联系下我嘛，想和您讨论下稀疏训练的一些应用，wx：xwzbj0808

**Comment by dingjiaweiww** [comment]
@BlackHorseQ 您可以联系下我嘛，想和您讨论下稀疏训练的一些应用，wx：xwzbj0808
