### ISSUE TITLE
输出q

### ISSUE THREAD

**Issue by lixiangjie01** [PaddlePaddle/Paddle#32069]
请问在DDPG算法中如何输出q的值，无法直接print

**Comment by littletomatodonkey** [comment]
你好，静态图中可以使用paddle.static.Print() 打印tensor的值( 文档：https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/fluid/layers/control_flow/Print_cn.html#print )；
动态图中，在forward函数中可以直接打印的，也可以使用xx.numpy()，将tensor转为numpy变量。

**Comment by lixiangjie01** [comment]
收到了！谢谢这么晚还在回复！明天试试，辛苦啦，谢谢！



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: littletomatodonkey ***@***.***&gt;
发送时间: 2021年4月6日 00:11
收件人: PaddlePaddle/Paddle ***@***.***&gt;
抄送: lixiangjie01 ***@***.***&gt;, Author ***@***.***&gt;
主题: 回复：[PaddlePaddle/Paddle] 输出q (#32069)





 
你好，静态图中可以使用paddle.static.Print() 打印tensor的值( 文档：https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/fluid/layers/control_flow/Print_cn.html#print )；
 动态图中，在forward函数中可以直接打印的，也可以使用xx.numpy()，将tensor转为numpy变量。
