### ISSUE TITLE
paddle2.0.1文档中函数random_split不存在

### ISSUE THREAD

**Issue by xmy0916** [PaddlePaddle/Paddle#32071]
paddle版本：2.0.1
执行：
from paddle.io import random_split
报错：
ImportError: cannot import name 'random_split' from 'paddle.io'
paddle文档2.0显示有该函数：
https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/fluid/dataloader/dataset/random_split_cn.html#random-split

**Comment by littletomatodonkey** [comment]
你好，该函数在paddle-dev中有，没有包含进paddle2.0，我们也记录更新下文档，感谢反馈，可以参考下面的链接 安装devlop的paddle～

https://www.paddlepaddle.org.cn/install/quick?docurl=/documentation/docs/zh/develop/install/pip/linux-pip.html

**Comment by littletomatodonkey** [comment]
你好，感谢反馈，该api已经cherry-pick到2.0分支，[PR链接](https://github.com/PaddlePaddle/Paddle/pull/32090)，我们在4月中旬会发布Paddle2.0.2，届时会包含该api~
