### ISSUE TITLE
梯度处理

### ISSUE THREAD

**Issue by songsong-L** [PaddlePaddle/Paddle#32075]
能否实现这样一个功能：
现在是这样的：
backward()计算出梯度=>minimize() / step()更新参数
上面这个过程没有提供对梯度的处理api
希望可以这样：
backward()计算出梯度=>处理梯度的api=>minimize(grad_param) / step(grad_param)更新参数可以接受梯度参数，默认可以是backward()计算的梯度，如果有参数传入，则用自己处理过的梯度来更新参数。
您们写框架可能主要考虑自动微分、方便，但是上面所说的功能对于学术人员还是很有用的。
我试图用自定义op实现上述功能，动态图模式下，没有apply_grad()把处理过的梯度放进去。静态图模式下总是报错，还没解决。

**Comment by phlrain** [comment]
有一种办法可以尝试下，就是参考下 paddle.nn.ClipGradByNorm(clip_norm=1.0) 的实现，把对于梯度的处理 参考 [ClipByGloablNorm](https://github.com/PaddlePaddle/Paddle/blob/release/2.0/python/paddle/fluid/clip.py#L345)的实现 , norm clip 会在backward之后，在step(grad_param)中自动调用
