### ISSUE TITLE
安装报错

### ISSUE THREAD

**Issue by codeWang-J** [PaddlePaddle/Paddle#32070]
在安装paddle_Inference后，
在import paddle的时候     -----报 "核心转储" 该怎么解决呢？
是在jetson_nano 上进行安装报的错。

具体报错信息：
yws@yws-desktop:~$ python3 
Python 3.6.9 (default, Jan 26 2021, 15:33:00) 
[GCC 8.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import paddle
非法指令 (核心已转储)

**Comment by littletomatodonkey** [comment]
你好，在jetson_nano平台上，建议下载安装官网提供的预测库：https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/guides/05_inference_deployment/inference/build_and_install_lib_cn.html

此外，建议在该平台上使用c++进行inference，如果希望使用python，需要自己重新基于该平台编译paddle

**Comment by codeWang-J** [comment]
解决了  原来是numpy版本不对

**Comment by codeWang-J** [comment]
> 你好，在jetson_nano平台上，建议下载安装官网提供的预测库：https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/guides/05_inference_deployment/inference/build_and_install_lib_cn.html
> 
> 此外，建议在该平台上使用c++进行inference，如果希望使用python，需要自己重新基于该平台编译paddle

解决了 原来是numpy版本不对   不管怎么说谢谢大佬！！

**Comment by littletomatodonkey** [comment]
好的~替你开心！感谢使用paddle！
