### ISSUE TITLE
PaddlePaddle是否支持TLS connection between parameter servers and workers

### ISSUE THREAD

**Issue by YueWang1996** [PaddlePaddle/Paddle#32076]
- 标题：PaddlePaddle是否支持TLS connection between parameter servers and workers
- PaddlePaddle版本：2.0

在官网上没有找到关于TLS连接的相关文档介绍，想问PaddlePaddle是否支持TLS connection between parameter servers and workers。如果支持，是否有官方文档和API介绍？有的话方便贴一下链接吗，谢谢！

**Comment by MissPenguin** [comment]
请问是想做服务部署吗

**Comment by YueWang1996** [comment]
> 请问是想做服务部署吗

对，可能需要，想了解一下

**Comment by MissPenguin** [comment]
服务部署的话，可以看下Paddle Serving：https://github.com/PaddlePaddle/Serving/blob/develop/README_CN.md

**Comment by YueWang1996** [comment]
> 服务部署的话，可以看下Paddle Serving：https://github.com/PaddlePaddle/Serving/blob/develop/README_CN.md

你好，顺便想问下，https://github.com/PaddlePaddle/FluidDoc/blob/develop/doc/paddle/design/dist_train/distributed_architecture.md 这个分布式架构文档介绍同样适用于PaddlePaddle2.0版本吗？

**Comment by MissPenguin** [comment]
> > 服务部署的话，可以看下Paddle Serving：https://github.com/PaddlePaddle/Serving/blob/develop/README_CN.md
> 
> 你好，顺便想问下，https://github.com/PaddlePaddle/FluidDoc/blob/develop/doc/paddle/design/dist_train/distributed_architecture.md 这个分布式架构文档介绍同样适用于PaddlePaddle2.0版本吗？

适用的
