### ISSUE TITLE
paddle有多分类的例子和mlogloss的实现吗？

### ISSUE THREAD

**Issue by bbbxixixixi** [PaddlePaddle/Paddle#32072]
比如给一段文本，判断属于哪几个类别

**Comment by LiuChiachi** [comment]
GLUE中的MNLI是个三分类数据集，可以参考PaddleNLP这个[GLUE](https://github.com/PaddlePaddle/PaddleNLP/tree/develop/examples/benchmark/glue)的例子。这里损失函数用的是`CrossEntropyLoss`，可以支持多分类。我理解你问的mlogloss应该就是Paddle里的`CrossEntropyLoss`或者`NLLLoss`吧，可以看下官方文档，[NLLLoss](https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/nn/layer/loss/NLLLoss_cn.html#nllloss), [CrossEntropyLoss](https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/nn/layer/loss/CrossEntropyLoss_cn.html#crossentropyloss)
