### ISSUE TITLE
你好，静态图中可以使用paddle.static.Print() 打印tensor的值( 文档：https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/fluid/layers/control_flow/Print_cn.html#print )；

### ISSUE THREAD

**Issue by lixiangjie01** [PaddlePaddle/Paddle#32077]
您好！q是作为神经网络的输出，代码如下，打印数组的Q值
～～～
    def _actor_learn(self, obs):
        action = self.model.policy(obs)
        Q = self.model.value(obs, action)
        cost = layers.reduce_mean(-1.0 * Q)
        optimizer = fluid.optimizer.AdamOptimizer(self.actor_lr)
        optimizer.minimize(cost, parameter_list=self.model.get_actor_params())
        return cost
～～～
我想将其作为数组打印，使用paddle.static.Print需要将paddle升级到2.0.1,升级后报错
Error: Can not import avx core while this file exists: /home/fox/PycharmProjects/Python-3.7.9/env/lib/python3.7/site-packages/paddle/fluid/core_avx.so
是ubuntu的系统，请问怎么解决呀

**Comment by lixiangjie01** [comment]
我的原有paddlepaddle版本是1.6.3，能不能在1.6.3来将Q转为Numpy输出呢？

**Comment by MissPenguin** [comment]
用paddle.fluid.layers.Print呢：https://www.paddlepaddle.org.cn/documentation/docs/zh/1.6/api_cn/layers_cn/Print_cn.html#print

**Comment by lixiangjie01** [comment]
成功啦！谢谢！辛苦啦！



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: MissPenguin ***@***.***&gt;
发送时间: 2021年4月6日 13:29
收件人: PaddlePaddle/Paddle ***@***.***&gt;
抄送: lixiangjie01 ***@***.***&gt;, Author ***@***.***&gt;
主题: 回复：[PaddlePaddle/Paddle] 你好，静态图中可以使用paddle.static.Print() 打印tensor的值( 文档：https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/fluid/layers/control_flow/Print_cn.html#print )； (#32077)





 
用paddle.fluid.layers.Print呢：https://www.paddlepaddle.org.cn/documentation/docs/zh/1.6/api_cn/layers_cn/Print_cn.html#print

**Comment by lixiangjie01** [comment]
您好，请问32*18的张量中的data显示只有1*20，是因为输出不完全吗？怎么样才能全部显示呀，用的是paddle.fluid.layers.Print



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: MissPenguin ***@***.***&gt;
发送时间: 2021年4月6日 13:29
收件人: PaddlePaddle/Paddle ***@***.***&gt;
抄送: lixiangjie01 ***@***.***&gt;, Author ***@***.***&gt;
主题: 回复：[PaddlePaddle/Paddle] 你好，静态图中可以使用paddle.static.Print() 打印tensor的值( 文档：https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/fluid/layers/control_flow/Print_cn.html#print )； (#32077)





 
用paddle.fluid.layers.Print呢：https://www.paddlepaddle.org.cn/documentation/docs/zh/1.6/api_cn/layers_cn/Print_cn.html#print

**Comment by MissPenguin** [comment]
> 您好，请问32*18的张量中的data显示只有1*20，是因为输出不完全吗？怎么样才能全部显示呀，用的是paddle.fluid.layers.Print 发自我的iPhone
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: MissPenguin ***@***.***&gt; 发送时间: 2021年4月6日 13:29 收件人: PaddlePaddle/Paddle ***@***.***&gt; 抄送: lixiangjie01 ***@***.***&gt;, Author ***@***.***&gt; 主题: 回复：[PaddlePaddle/Paddle] 你好，静态图中可以使用paddle.static.Print() 打印tensor的值( 文档：https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/fluid/layers/control_flow/Print_cn.html#print )； (#32077) 用paddle.fluid.layers.Print呢：https://www.paddlepaddle.org.cn/documentation/docs/zh/1.6/api_cn/layers_cn/Print_cn.html#print — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

默认只打印20个，可以加上summarize参数自定义打印输出长度，summarize=-1表示打印全部：
![image](https://user-images.githubusercontent.com/25809855/113805857-de454380-9793-11eb-9da1-2365b83cee41.png)
