### ISSUE TITLE
paddle fintune 实现方式

### ISSUE THREAD

**Issue by AWSWXY** [PaddlePaddle/Paddle#32094]
咨询paddle fintune实现方式，有无参考

**Comment by MissPenguin** [comment]
您好，可以具体描述下您的问题吗

**Comment by AWSWXY** [comment]
想初始化底层embedding，但是不想初始化整个模型的所有param

**Comment by MissPenguin** [comment]
> 想初始化底层embedding，但是不想初始化整个模型的所有param

如果是冻结某些层，可以将变量的stop_gradient属性设置为True，这样计算这个变量之前的所有参数都不会更新了，参考：https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/faq/train_cn.html#id4

**Comment by AWSWXY** [comment]
不是冻结某些层，是初始化只想初始化某一个param

**Comment by MissPenguin** [comment]
一般加载预训练模型的操作：
param_state_dict = paddle.load(path + ".pdparams")
model.set_dict(param_state_dict)
预训练模型其实是个dict（可以load模型然后打印出来看看），如果想指定初始化部分param，可以把不想初始化的keys过滤掉，只保留需要的，然后再执行load操作。
