### ISSUE TITLE
Dataloader exception 报错不详细

### ISSUE THREAD

**Issue by QingquanBao** [PaddlePaddle/Paddle#32104]
## 版本、环境信息
- paddlepaddle           2.0.1  
- paddlepaddle-gpu       2.0.1
- GPU：cuda 10.2
- python 3.7.9
- Ubuntu 16.04.7 LTS (GNU/Linux 4.15.0-129-generic x86_64)
 
## 描述
https://github.com/QingquanBao/PCA-GM/tree/torch2paddle
正在将原来是作为torch的项目改用paddlepaddle复现（torch版可以正常运行。跑`python3 train_eval_pdl.py --cfg experiments/vgg16_pca_voc.yaml`时，抛出关于**dataloader**的异常。由于这个报错简直太短，根本不知道从何找起bug，求教,谢谢

试过https://github.com/PaddlePaddle/Paddle/issues/31250 提到的将`self._thread.daemon = true` 注释掉，也没用。

// 这里是仅把dataloader一块代码单独拿出来跑了，但报错一样。

2021-04-06 20:53:40,083 - ERROR - DataLoader reader thread raised an exception!
[ERROR 2021-04-06 20:53:40,083 dataloader_iter.py:605] DataLoader reader thread raised an exception!
Traceback (most recent call last):
  File "dataset_test_dpl.py", line 47, in <module>
    for i, inputs in enumerate(dataloader['train']):
  File "/home/baoqingquan/anaconda3/envs/pca-gm/lib/python3.7/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 779, in __next__
    data = self._reader.read_next_var_list()
SystemError: (Fatal) Blocking queue is killed because the data reader raises an exception.
  [Hint: Expected killed_ != true, but received killed_:1 == true:1.] (at /paddle/paddle/fluid/operators/reader/blocking_queue.h:158)

**Comment by parap1uie-s** [comment]
相同的问题

**Comment by heavengate** [comment]
`num_workers=0`看下具体报什么错呢，另外如果`/dev/shm`下的共享内存不够的话建议设置`use_shared_memory=True`

**Comment by gaorui999** [comment]
我也遇到了

**Comment by QingquanBao** [comment]
> `num_workers=0`看下具体报什么错呢，另外如果`/dev/shm`下的共享内存不够的话建议设置`use_shared_memory=True`

设置num_workers:  0 之后，也开了共享内存，报错一样，没有区别QAQ

**Comment by heavengate** [comment]
> > `num_workers=0`看下具体报什么错呢，另外如果`/dev/shm`下的共享内存不够的话建议设置`use_shared_memory=True`
> 
> 设置num_workers: 0 之后，也开了共享内存，报错一样，没有区别QAQ

`num_worker=0`的话前面应该有python段的报错信息的

**Comment by QingquanBao** [comment]
> `num_worker=0`的话前面应该有python段的报错信息的

试过了，也是一样的报错。一点都没有变

**Comment by ZHUI** [comment]
试试 `export FLAGS_call_stack_level=2`，看看会不会有多一些错误日志？

**Comment by QingquanBao** [comment]
> 试试 `export FLAGS_call_stack_level=2`，看看会不会有多一些错误日志？

多了C++ 的报错信息，不过python段依然没有什么报错信息

W0412 19:42:07.862713 36149 device_context.cc:362] Please NOTE: device: 0, GPU Compute Capability: 7.5, Driver API Version: 11.0, Runtime API Version: 10.2
W0412 19:42:07.920146 36149 device_context.cc:372] device: 0, cuDNN Version: 7.6.
2021-04-12 19:42:14,360 - WARNING - DataLoader reader thread raised an exception.
[WARNING 2021-04-12 19:42:14,360 dataloader_iter.py:345] DataLoader reader thread raised an exception.
Traceback (most recent call last):
  File "dataset_test_dpl.py", line 50, in <module>
    for i, inputs in enumerate(dataloader['train']):
  File "/home/baoqingquan/anaconda3/envs/pca-gm/lib/python3.7/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 351, in __next__
    return self._reader.read_next_var_list()
SystemError: 

--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
0   std::thread::_State_impl<std::thread::_Invoker<std::tuple<ThreadPool::ThreadPool(unsigned long)::{lambda()#1}> > >::_M_run()
1   std::__future_base::_State_baseV2::_M_do_set(std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> ()>*, bool*)
2   paddle::operators::reader::PyReader::ReadNext(std::vector<paddle::framework::LoDTensor, std::allocator<paddle::framework::LoDTensor> >*)
3   paddle::operators::reader::BlockingQueue<std::vector<paddle::framework::LoDTensor, std::allocator<paddle::framework::LoDTensor> > >::Receive(std::vector<paddle::framework::LoDTensor, std::allocator<paddle::framework::LoDTensor> >*)
4   paddle::platform::EnforceNotMet::EnforceNotMet(paddle::platform::ErrorSummary const&, char const*, int)
5   paddle::platform::GetCurrentTraceBackString[abi:cxx11]()

----------------------
Error Message Summary:
----------------------
FatalError: Blocking queue is killed because the data reader raises an exception.
  [Hint: Expected killed_ != true, but received killed_:1 == true:1.] (at /paddle/paddle/fluid/operators/reader/blocking_queue.h:158)

**Comment by lazyn1997** [comment]
同样会遇到这样的问题

**Comment by QingquanBao** [comment]
paddle 2.1 不再出现这种状况，所以关了
