### ISSUE TITLE
paddle.scatter_ 的grad 问题在v2.0.1 修复了吗？

### ISSUE THREAD

**Issue by zzz2010** [PaddlePaddle/Paddle#32108]
你好， 我看到这个PR， 
https://github.com/PaddlePaddle/Paddle/pull/30604

我发现paddle.scatter_ 好像在v2.0.1  也存在这个问题， 所以想确认下是否v2.0.1 不能用paddle.scatter_
如果是的话， 有其他替代的方法吗？ 我不想用scatter_nd_add ，因为我希望是in-place 的

谢谢

**Comment by ForFishes** [comment]
您好，这里查了一下v2.0.1，这个版本确实没有修复这个bug。建议使用最新的develop分支修复过后的代码。
