### ISSUE TITLE
无

### ISSUE THREAD

**Issue by BlackHorseQ** [PaddlePaddle/Paddle#32107]
无

**Comment by tink2123** [comment]
您代码里的方式就可以索引，请问遇到什么报错了吗？
运行您提供的代码，out_z1 和 out_z2 的输出如下：
![image](https://user-images.githubusercontent.com/31891223/113813485-937ef800-97a2-11eb-9cdf-b37d563eb1f4.png)

**Comment by BlackHorseQ** [comment]
> 您代码里的方式就可以索引，请问遇到什么报错了吗？
> 运行您提供的代码，out_z1 和 out_z2 的输出如下：
> ![image](https://user-images.githubusercontent.com/31891223/113813485-937ef800-97a2-11eb-9cdf-b37d563eb1f4.png)

已经解决了，请问什么时候可以增加下面这个功能
`A = tensor([1,2,3,4])
B = A[[2,3,1]]`

**Comment by tink2123** [comment]
暂时还不支持这样索引，可以先使用 index_select 的操作，或者转成 numpy 索引之后再转换回tensor

**Comment by BlackHorseQ** [comment]
> 先使用 index_select 的操作，或者转成 numpy 索引之后再转换回tensor

转成numpy之后再索引梯度传不过来，我最开始这样做的但是梯度传不过来，找了很久才发现可以index_select操作
