### ISSUE TITLE
梯度裁剪

### ISSUE THREAD

**Issue by songsong-L** [PaddlePaddle/Paddle#32100]
想要实现一个类似梯度裁剪的功能，只是梯度处理办法不一样。
看了一下源码，总的来说是这样：

`params_grads=>clip这个op=>return  params_grads`

不过没整明白params_grads怎么传进去的，以及怎么被应用到step()的。
之前就尝试过自定义op来实现，发现没有什么api把处理过的梯度放进去，突然想起来梯度裁剪的思路，请教一下！

**Comment by MissPenguin** [comment]
可以贴一下源码的位置吗

**Comment by songsong-L** [comment]
> 可以贴一下源码的位置吗

源码就是梯度裁剪的源码

https://github.com/PaddlePaddle/Paddle/blob/release/2.0/python/paddle/fluid/clip.py#L152

**Comment by songsong-L** [comment]
> 可以贴一下源码的位置吗

后面又研究了一下，optimizer优化器有个属性是存clip的，会判断这个属性，如果要裁剪，然后调用梯度裁剪的op，然后apply_minimize()。还是回归到了自定义op的问题上去了。
