### ISSUE TITLE
ImportError: libmklml_intel.so: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by helinwang** [PaddlePaddle/Paddle#3213]
Just tried our latest production docker image, and got this error. I think we need to include the generated `libmklml_intel.so` and `libiomp5.so` into the Python package (or link into paddle statically).

```
Traceback (most recent call last):
  File "go/pserver/client/c/test/test_train.py", line 77, in <module>
    main()
  File "go/pserver/client/c/test/test_train.py", line 15, in main
    paddle.init(use_gpu=False, trainer_count=1)
  File "/usr/local/lib/python2.7/dist-packages/paddle/v2/__init__.py", line 66, in init
    import py_paddle.swig_paddle as api
  File "/usr/local/lib/python2.7/dist-packages/py_paddle/__init__.py", line 15, in <module>
    from util import DataProviderWrapperConverter
  File "/usr/local/lib/python2.7/dist-packages/py_paddle/util.py", line 18, in <module>
    import swig_paddle
  File "/usr/local/lib/python2.7/dist-packages/py_paddle/swig_paddle.py", line 28, in <module>
    _swig_paddle = swig_import_helper()
  File "/usr/local/lib/python2.7/dist-packages/py_paddle/swig_paddle.py", line 24, in swig_import_helper
    _mod = imp.load_module('_swig_paddle', fp, pathname, description)
ImportError: libmklml_intel.so: cannot open shared object file: No such file or directory
```
...
```
ImportError: libiomp5.so: cannot open shared object file: No such file or directory
```

**Comment by gangliao** [comment]
It looks Intel's PR default enabled MKL_DNN feature. But they didn't package the corresponding libraries `libmklml_intel  and libiomp5` into setup.py.in

**Comment by gangliao** [comment]
@helinwang @luotao1

**Comment by tensor-tang** [comment]
@gangliao Yes, It should be the problem about the dynamic libraries.

Actually we found the `setup.py.in` before, but did not found an appropriate way to add `libmklml_intel` and `libiomp5`. 

Like `cudnn` and `mkl`, which are supposed installed on local machine, `MKLML` are kind of like the same level as them. So we should found a better way to include `MKLML `and `MKLDNN` as third party.

I think you can comment in the issue #3162, since they are the same issue.
Any method is very appreciated.

**Comment by Yancey1989** [comment]
I have the same problem with the latest Docker image, maybe #3162 does not fix this error?

**Comment by luotao1** [comment]
Since -WITH_MKLML and -WITH_MKLDNN are opened later, I will set off again. @Yancey1989

**Comment by Joseph996** [comment]
So, any solutions to this problem?
