### ISSUE TITLE
recompute 功能对于resnet101 如何设置checkpoints 

### ISSUE THREAD

**Issue by paulpaul91** [PaddlePaddle/Paddle#32139]
https://fleet-x.readthedocs.io/en/latest/paddle_fleet_rst/collective/collective_mp/recomputation.html?highlight=checkpoints#recomputation
参看链接中的resnet50,对于resnet101 也是采用同样的值吗

**Comment by ZHUI** [comment]
> https://fleet-x.readthedocs.io/en/latest/paddle_fleet_rst/collective/collective_mp/recomputation.html?highlight=checkpoints#recomputation
> 参看链接中的resnet50,对于resnet101 也是采用同样的值吗

应该是采用相似的策略，即：以两个子模块中间的变量作为切分点就是一个很好的选择

**Comment by JZ-LIANG** [comment]
> > https://fleet-x.readthedocs.io/en/latest/paddle_fleet_rst/collective/collective_mp/recomputation.html?highlight=checkpoints#recomputation
> > 参看链接中的resnet50,对于resnet101 也是采用同样的值吗
> 
> 应该是采用相似的策略，即：以两个子模块中间的变量作为切分点就是一个很好的选择

是的，50 和 101 对于recompute只是层数不同，checkpoint选取策略是一样。 对应resnet-like 网络，每个 repeat block 的output 即可。
