### ISSUE TITLE
paddle.summary中参数forward/backward pass size在AI studio上和本机结果差距很大

### ISSUE THREAD

**Issue by RyanPeking** [PaddlePaddle/Paddle#32140]
paddle版本：2.0.1
代码如下：
```
import paddle


class Encoder(paddle.nn.Layer):
    def __init__(self, vocab_size, embed_dim, hidden_size,rate=0.2):
        super(Encoder, self).__init__()
        self.embedder = paddle.nn.Embedding(vocab_size, embed_dim)
        self.gru = paddle.nn.GRU(input_size=embed_dim,hidden_size=hidden_size,dropout=rate)

    def forward(self, sequence):
        inputs = self.embedder(sequence)
        encoder_output, encoder_state = self.gru(inputs)
        return encoder_output, encoder_state

encoder=Encoder(vocab_size=30000,embed_dim=256,hidden_size=256)
paddle.summary(encoder,(128,200),dtypes='int64')
```

在本机结果如下：
![QQ图片20210408111806](https://user-images.githubusercontent.com/46998598/113964395-fed9d000-985d-11eb-95fb-77170e6a5cb1.jpg)
在百度平台ai studio运行结果如下：
![QQ图片20210408111822](https://user-images.githubusercontent.com/46998598/113964529-406a7b00-985e-11eb-84a9-18238e8c30c5.png)

ai studio上结果不对，怎么会占到那么大内存呢
后来又放到colab上，发现结果和ai studio一样，所以很疑惑这是什么问题导致的，求解答

**Comment by ZHUI** [comment]
我这边复现的结果，跟ai studio一样。paddle 2.0.1 版本。辛苦 @LielinJiang 帮忙看一下。

**Comment by GT-ZhangAcer** [comment]
> 我这边复现的结果，跟ai studio一样。paddle 2.0.1 版本。辛苦 @LielinJiang 帮忙看一下。

我猜是在Notebook中已经执行过一次Emb+GRU的代码了，但执行完毕之后没有重启执行器就立即执行了新的组网代码，旧的网络仍在内存当中而且造成了冲突。  
图中显示的Emb应该是从1开始的，而这个是3，正常情况下仍应从1开始
<img width="918" alt="图片" src="https://user-images.githubusercontent.com/46156734/114160104-22ce0c00-9959-11eb-8ecd-1e40851f5dcd.png">

**Comment by RyanPeking** [comment]
> > 我这边复现的结果，跟ai studio一样。paddle 2.0.1 版本。辛苦 @LielinJiang 帮忙看一下。
> 
> 我猜是在Notebook中已经执行过一次Emb+GRU的代码了，但执行完毕之后没有重启执行器就立即执行了新的组网代码，旧的网络仍在内存当中而且造成了冲突。
> 图中显示的Emb应该是从1开始的，而这个是3，正常情况下仍应从1开始
> <img alt="图片" width="918" src="https://user-images.githubusercontent.com/46156734/114160104-22ce0c00-9959-11eb-8ecd-1e40851f5dcd.png">

和这个没有关系，即使是1也是同样情况
<img width="301" alt="Snipaste_2021-04-12_09-50-51" src="https://user-images.githubusercontent.com/46998598/114330630-b4659580-9b74-11eb-882a-cb15dd0b7d79.png">

**Comment by LielinJiang** [comment]
这个问题已经在最新的develop修复哈，如果急需的话，可以试一下develop 版本的paddle：
https://www.paddlepaddle.org.cn/install/quick?docurl=/documentation/docs/zh/develop/install/pip/linux-pip.html

![image](https://user-images.githubusercontent.com/50691816/114348655-67e08100-9b99-11eb-97c0-fdb504e6b2de.png)
