### ISSUE TITLE
GPU跑DeOldify跑不出结果

### ISSUE THREAD

**Issue by melisa81** [PaddlePaddle/Paddle#32154]
- 版本、环境信息：
    1）PaddlePaddle版本：paddlepaddle-gpu-2.0.0rc1.post110
    2）GPU：Nivdia Quadro P3200，CUDA 11.0,cudnn 8.0.4
    4）系统环境：Windows10 ,python36 

问题：
跑下面代码，CPU正常出结果，GPU的话就不出结果，跑不出上色图。pycharm报Process finished with exit code -1073741819 (0xC0000005)，这如何处理？
from ppgan.apps import DeOldifyPredictor
deoldify = DeOldifyPredictor()
deoldify.run("docs/imgs/test_old.jpg")

**Comment by LielinJiang** [comment]
请问有什么提示嘛

**Comment by melisa81** [comment]
就是跑不出上色图。pycharm报Process finished with exit code -1073741819 (0xC0000005)
