### ISSUE TITLE
请问PaddlePaddle有没有类似tf sample softmax loss这样的函数

### ISSUE THREAD

**Issue by hlzonWang** [PaddlePaddle/Paddle#32168]
fluid.layer里面有个名字类似的，但输入输出都不一样

**Comment by wawltor** [comment]
抱歉，查找了一下paddle的api，看起来没有这样的API，我们会记录下这个需求。

**Comment by wawltor** [comment]
您好， sample softmax loss这个api可能是没有对齐tensorflow，我们找一下相应的同学来跟进一下，谢谢反馈该问题！
