### ISSUE TITLE
在用c++ 版本的Paddle Inference 做部署，能否给一个由opencv的mat转到你们input_tensor结构的示例？

### ISSUE THREAD

**Issue by lixueling-gh** [PaddlePaddle/Paddle#32167]
在用c++ 版本的Paddle Inference 做部署，能否给一个由opencv的mat转到你们input_tensor结构的示例？

**Comment by wawltor** [comment]
您好，你可以参考一下这块的代码 https://github.com/PaddlePaddle/PaddleX/blob/bc1e6a09af7eeb48b2ac7d0b6f73926b85a5c5da/deploy/cpp/src/paddlex.cpp#L244

**Comment by TTgogogo** [comment]
找到解决方法了吗？

**Comment by TTgogogo** [comment]
> 在用c++ 版本的Paddle Inference 做部署，能否给一个由opencv的mat转到你们input_tensor结构的示例？

找到方法了吗？
