### ISSUE TITLE
docker 启动paddlepaddle-GPU报错， /bin/sh: 1: source: not found

### ISSUE THREAD

**Issue by zhiyongLiu1114** [PaddlePaddle/Paddle#32164]
为使您的问题得到快速解决，在建立Issue前，请您先通过如下方式搜索是否有相似问题:【搜索issue关键字】【使用labels筛选】【官方文档】

建立issue时，为快速解决问题，请您根据使用情况给出如下信息：
- 标题：启动容器错误
- 版本、环境信息：
   
- 安装方式信息：
1）docker安装

- 复现信息：使用docker 拉取镜像，启动容器时报错，拉取的镜像如下图
- 
![image](https://user-images.githubusercontent.com/47651345/114116672-ab2bbd00-9917-11eb-9b0c-106f6fe44512.png)

- 问题描述：docker run 启动容器报错，错误内容为 /bin/sh: 1: source: not found。用docker inspect 看这个镜像，里面有这个cmd，如下图
- 
![image](https://user-images.githubusercontent.com/47651345/114116745-c7c7f500-9917-11eb-8d1f-697c8c4b748e.png)

**Comment by zhiyongLiu1114** [comment]
第二张图贴错了，是这个
![image](https://user-images.githubusercontent.com/47651345/114116792-e3330000-9917-11eb-89ab-2b0ce8f81824.png)

**Comment by wawltor** [comment]
您好，想问一下，是否安装了docker了了？

**Comment by zhiyongLiu1114** [comment]
> 是否安装了docker

安装了，没有docker 镜像都没法pull。。。

**Comment by wadefelix** [comment]
> 第二张图贴错了，是这个
> ![image](https://user-images.githubusercontent.com/47651345/114116792-e3330000-9917-11eb-89ab-2b0ce8f81824.png)

您好，这条`CMD`已被后续的`CMD`覆盖了，此镜像中的`sh`版本没有内置`source`指令。
不需要执行这个`source ~/.bashrc`的，您本意是想做？
另，能从`docker history`翻出来这些指令👍🏻。

这个镜像是ubuntu 16.04的，有bash，请使用bash这个shell。

**Comment by zhiyongLiu1114** [comment]
> > 第二张图贴错了，是这个
> > ![image](https://user-images.githubusercontent.com/47651345/114116792-e3330000-9917-11eb-89ab-2b0ce8f81824.png)
> 
> 您好，这条`CMD`已被后续的`CMD`覆盖了，此镜像中的`sh`版本没有内置`source`指令。
> 不需要执行这个`source ~/.bashrc`的，您本意是想做？
> 另，能从`docker history`翻出来这些指令👍🏻。
> 
> 这个镜像是ubuntu 16.04的，有bash，请使用bash这个shell。

您好，我的问题是我pull下来这个镜像后，用docker run 起容器起不来，报错信息是 /bin/sh: 1: source: not found
看了一下我的系统是Centos，是因为这个原因吗？

**Comment by zhiyongLiu1114** [comment]
> > 第二张图贴错了，是这个
> > ![image](https://user-images.githubusercontent.com/47651345/114116792-e3330000-9917-11eb-89ab-2b0ce8f81824.png)
> 
> 您好，这条`CMD`已被后续的`CMD`覆盖了，此镜像中的`sh`版本没有内置`source`指令。
> 不需要执行这个`source ~/.bashrc`的，您本意是想做？
> 另，能从`docker history`翻出来这些指令👍🏻。
> 
> 这个镜像是ubuntu 16.04的，有bash，请使用bash这个shell。

您好，我的问题是我pull下来这个镜像后，用docker run 起容器起不来，报错信息是 /bin/sh: 1: source: not found
看了一下我的系统是Centos，是因为这个原因吗？

**Comment by wadefelix** [comment]
> > > 第二张图贴错了，是这个
> > > ![image](https://user-images.githubusercontent.com/47651345/114116792-e3330000-9917-11eb-89ab-2b0ce8f81824.png)
> > 
> > 
> > 您好，这条`CMD`已被后续的`CMD`覆盖了，此镜像中的`sh`版本没有内置`source`指令。
> > 不需要执行这个`source ~/.bashrc`的，您本意是想做？
> > 另，能从`docker history`翻出来这些指令👍🏻。
> > 这个镜像是ubuntu 16.04的，有bash，请使用bash这个shell。
> 
> 您好，我的问题是我pull下来这个镜像后，用docker run 起容器起不来，报错信息是 /bin/sh: 1: source: not found
> 看了一下我的系统是Centos，是因为这个原因吗？

您启动容器的命令是什么呢？
![image](https://user-images.githubusercontent.com/1306724/115507773-2180d580-a2af-11eb-835a-c7df4b6f82bf.png)

是使用类似这样的命令么？
```bash
docker run --name paddle -it registry.baidubce.com/paddlepaddle/paddle:2.0.1 /bin/bash
```

**Comment by zhiyongLiu1114** [comment]
> > > > 第二张图贴错了，是这个
> > > > ![image](https://user-images.githubusercontent.com/47651345/114116792-e3330000-9917-11eb-89ab-2b0ce8f81824.png)
> > > 
> > > 
> > > 您好，这条`CMD`已被后续的`CMD`覆盖了，此镜像中的`sh`版本没有内置`source`指令。
> > > 不需要执行这个`source ~/.bashrc`的，您本意是想做？
> > > 另，能从`docker history`翻出来这些指令👍🏻。
> > > 这个镜像是ubuntu 16.04的，有bash，请使用bash这个shell。
> > 
> > 
> > 您好，我的问题是我pull下来这个镜像后，用docker run 起容器起不来，报错信息是 /bin/sh: 1: source: not found
> > 看了一下我的系统是Centos，是因为这个原因吗？
> 
> 您启动容器的命令是什么呢？
> ![image](https://user-images.githubusercontent.com/1306724/115507773-2180d580-a2af-11eb-835a-c7df4b6f82bf.png)
> 
> 是使用类似这样的命令么？
> 
> ```shell
> docker run --name paddle -it registry.baidubce.com/paddlepaddle/paddle:2.0.1 /bin/bash
> ```
您好，启动镜像命令如下：
docker run \
-itd \
-p 33070-33075:33070-33075 \
--name xxx\
-v /xxx:/xxx \
--gpus all 282b0317c261(这个是镜像id)

我在最后加上/bin/bash 后启动成功了，谢谢
