### ISSUE TITLE
model.summary()后出现KeyError: 'output_shape'错误

### ISSUE THREAD

**Issue by JJYjackson** [PaddlePaddle/Paddle#32179]
- 标题：自主搭建resnet模型报错 
- 版本、环境信息：
    1）PaddlePaddle版本：2.0.1
    2）系统环境：Paddle version: 2.0.1
        Paddle With CUDA: False
        OS: debian stretch/sid
        Python version: 3.7.4
        CUDA version: None
        cuDNN version: None.None.None
         Nvidia driver version: None
- 模型信息
    1）模型名称    图一 
![image](https://user-images.githubusercontent.com/65533171/114192591-40629c00-9980-11eb-9ac7-6f17cc86299d.png)

keras复现版本（图二）
![image](https://user-images.githubusercontent.com/65533171/114192794-7869df00-9980-11eb-8dc7-c5aaf7275194.png)

     2）使用数据集名称   （matlab生成数字信号调制识别数据集_8class  shape=(800000, 1,  2, 100)） https://aistudio.baidu.com/aistudio/datasetdetail/73835
    3）模型代码 如下.zip文件

[net_resnet_stack.zip](https://github.com/PaddlePaddle/Paddle/files/6286343/net_resnet_stack.zip)

- 问题描述：运行model.summary((None, 1, 2, 100))后出现如下报错信息
- 报错信息：
---------------------------------------------------------------------------AttributeError                            Traceback (most recent call last)/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/hapi/model_summary.py in hook(layer, input, output)
    215             try:
--> 216                 summary[m_key]["output_shape"] = _get_output_shape(output)
    217             except:
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/hapi/model_summary.py in _get_output_shape(output)
    193         else:
--> 194             output_shape = list(output.shape)
    195         return output_shape
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py in __getattr__(self, name)
   1049                 return _buffers[name]
-> 1050         return object.__getattribute__(self, name)
   1051 
AttributeError: 'MaxPool2D' object has no attribute 'shape'
During handling of the above exception, another exception occurred:
KeyError                                  Traceback (most recent call last)<ipython-input-6-6c680bc1eda0> in <module>
     31 # model_resstack
     32 model_resstack = paddle.Model(model_resstack)
---> 33 model_resstack.summary((None, 1, 2, 100))
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/hapi/model.py in summary(self, input_size, dtype)
   1879         else:
   1880             _input_size = self._inputs
-> 1881         return summary(self.network, _input_size, dtype)
   1882 
   1883     def _verify_spec(self, specs, shapes=None, dtypes=None, is_input=False):
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/hapi/model_summary.py in summary(net, input_size, dtypes)
    147 
    148     _input_size = _check_input(_input_size)
--> 149     result, params_info = summary_string(net, _input_size, dtypes)
    150     print(result)
    151 
</opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/decorator.py:decorator-gen-343> in summary_string(model, input_size, dtypes)
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/base.py in _decorate_function(func, *args, **kwargs)
    313         def _decorate_function(func, *args, **kwargs):
    314             with self:
--> 315                 return func(*args, **kwargs)
    316 
    317         @decorator.decorator
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/hapi/model_summary.py in summary_string(model, input_size, dtypes)
    274 
    275     # make a forward pass
--> 276     model(*x)
    277 
    278     # remove these hooks
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py in __call__(self, *inputs, **kwargs)
    900                 self._built = True
    901 
--> 902             outputs = self.forward(*inputs, **kwargs)
    903 
    904             for forward_post_hook in self._forward_post_hooks.values():
~/net_resnet_stack.py in forward(self, x)
    215         # x = self.maxpool(x)
    216         #Residual Srack 2
--> 217         x = self.layer2(x)  #####
    218         #Residual Srack 3,4,5
    219         x = self.layer3(x)
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py in __call__(self, *inputs, **kwargs)
    900                 self._built = True
    901 
--> 902             outputs = self.forward(*inputs, **kwargs)
    903 
    904             for forward_post_hook in self._forward_post_hooks.values():
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/container.py in forward(self, input)
     93     def forward(self, input):
     94         for layer in self._sub_layers.values():
---> 95             input = layer(input)
     96         return input
     97 
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py in __call__(self, *inputs, **kwargs)
    903 
    904             for forward_post_hook in self._forward_post_hooks.values():
--> 905                 hook_result = forward_post_hook(self, inputs, outputs)
    906                 if hook_result is not None:
    907                     outputs = hook_result
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/hapi/model_summary.py in hook(layer, input, output)
    217             except:
    218                 warnings.warn('Get layer {} output shape failed!')
--> 219                 summary[m_key]["output_shape"]
    220 
    221             params = 0
KeyError: 'output_shape'

**Comment by joey12300** [comment]
@JJYjackson 你好，方便把paddle版本调用summary的详细代码贴出来吗？

**Comment by JJYjackson** [comment]
您好，这样可以吗？

在 2021-04-10 12:26:48，"Jack Zhou" ***@***.***> 写道：

@JJYjackson 你好，方便把paddle版本调用summary的详细代码贴出来吗？

**Comment by JJYjackson** [comment]
![image](https://user-images.githubusercontent.com/65533171/114265773-48c0e280-9a25-11eb-8e27-3a885b6f89b3.png)
![image](https://user-images.githubusercontent.com/65533171/114265783-51b1b400-9a25-11eb-8504-3afdc1085cfd.png)
您好，这样可以吗？

**Comment by joey12300** [comment]
@JJYjackson MaxPool2D返回的是一个可调用对象，并不是一个Tensor。 所以你代码中引用`MaxPool2D`可以改为：
```python
if self.maxpool:
    self.maxpool = nn.MaxPool2D(kernel_size=(2,1), stride=(2,1), padding='VALID')
    out = self.maxpool(out)
```
可参考MaxPool2D的官方示例。
https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/nn/layer/pooling/MaxPool2D_cn.html#daimashili
