### ISSUE TITLE
运行first-order-demo.py 报找不到face_detector参数？

### ISSUE THREAD

**Issue by melisa81** [PaddlePaddle/Paddle#32175]
版本、环境信息：
   1）PaddlePaddle版本：paddlepaddle-gpu-2.0.0rc1.post110
   2）GPU：Nivdia Quadro P3200，CUDA 11.0,cudnn 8.0.4
   4）系统环境：Windows10 ,python36
问题：
运行first-order-demo.py 代码的时候，报TypeError: __init__() got an unexpected keyword argument 'face_detector'，请问如何处理啊？

**Comment by joey12300** [comment]
@keyi 您好，可以提供一下源码

**Comment by melisa81** [comment]
就是运行https://github.com/PaddlePaddle/PaddleGAN/tree/develop/applications/tools 下面的first-order-demo.py，里面的代码报无法初始化：
parser.add_argument(
    "--face_detector",
    dest="face_detector",
    type=str,
    default='sfd',
    help="face detector to be used, can choose s3fd or blazeface")

**Comment by melisa81** [comment]
我把face_detector=args.face_detector删掉就可以运行了。
但目前报  input image is not divisible by macro_block_size=16, resizing from (500, 375) to (512, 384) to ensure video compatibility with most codecs and players. To prevent resizing, make your input image divisible by the macro_block_size or set the macro_block_size to 1 (risking incompatibility)    

动作迁移视频脸型失真了…………
