### ISSUE TITLE
 Ernie 1.0模型 inference cpu切换gpu 报错

### ISSUE THREAD

**Issue by bluestinger** [PaddlePaddle/Paddle#32189]
环境是paddle 提供的docker的环境
hub.baidubce.com/paddlepaddle/paddle:1.8.0-gpu-cuda10.0-cudnn7-trt6
官方的Paddle-Inference-Demo可以正常使用

我自己训练的模型 Ernie 1.0 的pretrain模型，cpu下能正确输出结果。切换gpu后，报错如下

grep: warning: GREP_OPTIONS is deprecated; please use an alias or script
E0411 03:34:51.655264    84 analysis_config.cc:180] Please compile with MKLDNN first to use MKLDNN
I0411 03:34:52.433706    84 analysis_predictor.cc:138] Profiler is deactivated, and no profiling report will be generated.
I0411 03:34:52.446473    84 analysis_predictor.cc:872] MODEL VERSION: 1.8.3
I0411 03:34:52.446512    84 analysis_predictor.cc:874] PREDICTOR VERSION: 1.8.0
I0411 03:34:52.446916    84 analysis_predictor.cc:432] TensorRT subgraph engine is enabled
--- Running analysis [ir_graph_build_pass]
--- Running analysis [ir_graph_clean_pass]
--- Running analysis [ir_analysis_pass]
--- Running IR pass [conv_affine_channel_fuse_pass]
--- Running IR pass [conv_eltwiseadd_affine_channel_fuse_pass]
--- Running IR pass [shuffle_channel_detect_pass]
--- Running IR pass [quant_conv2d_dequant_fuse_pass]
--- Running IR pass [delete_quant_dequant_op_pass]
--- Running IR pass [simplify_with_basic_ops_pass]
--- Running IR pass [embedding_eltwise_layernorm_fuse_pass]
I0411 03:34:52.755502    84 graph_pattern_detector.cc:101] ---  detected 1 subgraphs
I0411 03:34:52.756510    84 graph_pattern_detector.cc:101] ---  detected 1 subgraphs
I0411 03:34:52.761987    84 graph_pattern_detector.cc:101] ---  detected 25 subgraphs
--- Running IR pass [multihead_matmul_fuse_pass_v2]
I0411 03:34:54.146399    84 graph_pattern_detector.cc:101] ---  detected 12 subgraphs
--- Running IR pass [skip_layernorm_fuse_pass]
I0411 03:34:54.173033    84 graph_pattern_detector.cc:101] ---  detected 24 subgraphs
--- Running IR pass [conv_bn_fuse_pass]
--- Running IR pass [fc_fuse_pass]
I0411 03:34:54.181416    84 graph_pattern_detector.cc:101] ---  detected 12 subgraphs
I0411 03:34:54.185427    84 graph_pattern_detector.cc:101] ---  detected 25 subgraphs
--- Running IR pass [tensorrt_subgraph_pass]
I0411 03:34:54.195298    84 tensorrt_subgraph_pass.cc:115] ---  detect a sub-graph with 77 nodes
W0411 03:34:54.197585    84 tensorrt_subgraph_pass.cc:285] The Paddle lib links the 6015 version TensorRT, make sure the runtime TensorRT you are using is no less than this version, otherwise, there might be Segfault!
I0411 03:34:54.197618    84 tensorrt_subgraph_pass.cc:321] Prepare TRT engine (Optimize model structure, Select OP kernel etc). This process may cost a lot of time.
Traceback (most recent call last):
  File "Demo_pre5.py", line 119, in <module>
    pred=create_predictor()
  File "Demo_pre5.py", line 68, in create_predictor
    predictor=create_paddle_predictor(config)
paddle.fluid.core_avx.EnforceNotMet: 

--------------------------------------------
C++ Call Stacks (More useful to developers):
--------------------------------------------
0   std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > paddle::platform::GetTraceBackString<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&&, char const*, int)
1   paddle::platform::EnforceNotMet::EnforceNotMet(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, char const*, int)
2   paddle::inference::tensorrt::OpConverter::ConvertBlockToTRTEngine(paddle::framework::BlockDesc*, paddle::framework::Scope const&, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, std::unordered_set<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::hash<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::equal_to<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, paddle::inference::tensorrt::TensorRTEngine*)
3   paddle::inference::analysis::TensorRtSubgraphPass::CreateTensorRTOp(paddle::framework::ir::Node*, paddle::framework::ir::Graph*, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >*) const
4   paddle::inference::analysis::TensorRtSubgraphPass::ApplyImpl(paddle::framework::ir::Graph*) const
5   paddle::framework::ir::Pass::Apply(paddle::framework::ir::Graph*) const
6   paddle::inference::analysis::IRPassManager::Apply(std::unique_ptr<paddle::framework::ir::Graph, std::default_delete<paddle::framework::ir::Graph> >)
7   paddle::inference::analysis::IrAnalysisPass::RunImpl(paddle::inference::analysis::Argument*)
8   paddle::inference::analysis::Analyzer::RunAnalysis(paddle::inference::analysis::Argument*)
9   paddle::AnalysisPredictor::OptimizeInferenceProgram()
10  paddle::AnalysisPredictor::PrepareProgram(std::shared_ptr<paddle::framework::ProgramDesc> const&)
11  paddle::AnalysisPredictor::Init(std::shared_ptr<paddle::framework::Scope> const&, std::shared_ptr<paddle::framework::ProgramDesc> const&)
12  std::unique_ptr<paddle::PaddlePredictor, std::default_delete<paddle::PaddlePredictor> > paddle::CreatePaddlePredictor<paddle::AnalysisConfig, (paddle::PaddleEngineKind)2>(paddle::AnalysisConfig const&)
13  std::unique_ptr<paddle::PaddlePredictor, std::default_delete<paddle::PaddlePredictor> > paddle::CreatePaddlePredictor<paddle::AnalysisConfig>(paddle::AnalysisConfig const&)

----------------------
Error Message Summary:
----------------------
InvalidArgumentError: TensorRT's tensor input requires at least 2 dimensions, but input 1 has 1 dims.
  [Hint: Expected shape.size() > 1UL, but received shape.size():1 <= 1UL:1.] at (/paddle /trt_refine_int8/paddle/fluid/inference/tensorrt/engine.h:67)

**Comment by shangzhizhou** [comment]
您好，请附一下单测代码和模型（模型结构一致即可，可以是随机初始化参数），方便定位问题。

**Comment by bluestinger** [comment]
[
[Demo_pre5.py.txt](https://github.com/PaddlePaddle/Paddle/files/6293740/Demo_pre5.py.txt)
[input.txt](https://github.com/PaddlePaddle/Paddle/files/6293742/input.txt)



](url)模型400M太大了，怎么传？

**Comment by shangzhizhou** [comment]
1, 动态shape配置请修改一下
config.set_trt_dynamic_shape_info(
      {
       names[0]:min_input_shape,
       names[1]:min_input_shape,
       names[2]:min_input_shape,
       names[3]:min_input_shape,
       names[4]:[-1,1], #minshape不能有-1，这个改成1试试？
      },
      {
       names[0]:max_input_shape,
       names[1]:max_input_shape,
       names[2]:max_input_shape,
       names[3]:max_input_shape,
       names[3]:max_input_shape,
       names[4]:[512, 1],
       },
      {
       names[0]:opt_input_shape,
       names[1]:opt_input_shape,
       names[2]:opt_input_shape,
       names[3]:opt_input_shape,
       names[4]:[128, 1],
      });

2，模型可以先上传一下model文件（或__model__）

**Comment by bluestinger** [comment]
试过1，还是不行
[__model__.txt](https://github.com/PaddlePaddle/Paddle/files/6294454/__model__.txt)

**Comment by shangzhizhou** [comment]
I0411 03:34:52.446473 84 analysis_predictor.cc:872] MODEL VERSION: 1.8.3
I0411 03:34:52.446512 84 analysis_predictor.cc:874] PREDICTOR VERSION: 1.8.0
从日志看，训练的版本更高一些。
推理是否可以测试下1.8.3之后的版本，比如1.8.5和2.0.1

**Comment by bluestinger** [comment]
1.8.5试了一下，还是报错。我是用1.8训练的，2.0.1的还需要陪环境，不方便试。
我看我的报错和下面这个一样，有其他解决的方式吗
https://github.com/PaddlePaddle/Paddle/issues/25107

**Comment by shangzhizhou** [comment]
1.8.5之后也升级了ernie相关的不少功能，如果环境不方便，可以提供一下完整的模型我们这边安排在新版本复现一下。模型文件可以提供网盘链接

**Comment by bluestinger** [comment]
链接: https://pan.baidu.com/s/1p8Ph5OLvZvz42b-yf_G5-Q  密码: jv77

**Comment by bluestinger** [comment]
我用1.8.3报错如下
--------------------------------------------
C++ Call Stacks (More useful to developers):
--------------------------------------------
0   std::string paddle::platform::GetTraceBackString<char const*>(char const*&&, char const*, int)
1   paddle::platform::EnforceNotMet::EnforceNotMet(std::__exception_ptr::exception_ptr, char const*, int)
2   paddle::framework::ir::PassRegistry::Get(std::string const&) const
3   paddle::inference::analysis::IRPassManager::CreatePasses(paddle::inference::analysis::Argument*, std::vector<std::string, std::allocator<std::string> > const&)
4   paddle::inference::analysis::IRPassManager::IRPassManager(paddle::inference::analysis::Argument*)
5   paddle::inference::analysis::IrAnalysisPass::RunImpl(paddle::inference::analysis::Argument*)
6   paddle::inference::analysis::Analyzer::RunAnalysis(paddle::inference::analysis::Argument*)
7   paddle::AnalysisPredictor::OptimizeInferenceProgram()
8   paddle::AnalysisPredictor::PrepareProgram(std::shared_ptr<paddle::framework::ProgramDesc> const&)
9   paddle::AnalysisPredictor::Init(std::shared_ptr<paddle::framework::Scope> const&, std::shared_ptr<paddle::framework::ProgramDesc> const&)
10  std::unique_ptr<paddle::PaddlePredictor, std::default_delete<paddle::PaddlePredictor> > paddle::CreatePaddlePredictor<paddle::AnalysisConfig, (paddle::PaddleEngineKind)2>(paddle::AnalysisConfig const&)
11  std::unique_ptr<paddle::PaddlePredictor, std::default_delete<paddle::PaddlePredictor> > paddle::CreatePaddlePredictor<paddle::AnalysisConfig>(paddle::AnalysisConfig const&)

----------------------
Error Message Summary:
----------------------
Error: Pass tensorrt_subgraph_pass has not been registered at (/paddle/paddle/fluid/framework/ir/pass.h:201)

**Comment by shangzhizhou** [comment]
> ## 我用1.8.3报错如下
> ## C++ Call Stacks (More useful to developers):
> 0 std::string paddle::platform::GetTraceBackString<char const*>(char const*&&, char const*, int)
> 1 paddle::platform::EnforceNotMet::EnforceNotMet(std::__exception_ptr::exception_ptr, char const*, int)
> 2 paddle::framework::ir::PassRegistry::Get(std::string const&) const
> 3 paddle::inference::analysis::IRPassManager::CreatePasses(paddle::inference::analysis::Argument*, std::vector<std::string, std::allocatorstd::string > const&)
> 4 paddle::inference::analysis::IRPassManager::IRPassManager(paddle::inference::analysis::Argument*)
> 5 paddle::inference::analysis::IrAnalysisPass::RunImpl(paddle::inference::analysis::Argument*)
> 6 paddle::inference::analysis::Analyzer::RunAnalysis(paddle::inference::analysis::Argument*)
> 7 paddle::AnalysisPredictor::OptimizeInferenceProgram()
> 8 paddle::AnalysisPredictor::PrepareProgram(std::shared_ptrpaddle::framework::ProgramDesc const&)
> 9 paddle::AnalysisPredictor::Init(std::shared_ptrpaddle::framework::Scope const&, std::shared_ptrpaddle::framework::ProgramDesc const&)
> 10 std::unique_ptr<paddle::PaddlePredictor, std::default_deletepaddle::PaddlePredictor > paddle::CreatePaddlePredictor<paddle::AnalysisConfig, (paddle::PaddleEngineKind)2>(paddle::AnalysisConfig const&)
> 11 std::unique_ptr<paddle::PaddlePredictor, std::default_deletepaddle::PaddlePredictor > paddle::CreatePaddlePredictorpaddle::AnalysisConfig(paddle::AnalysisConfig const&)
> 
> ## Error Message Summary:
> Error: Pass tensorrt_subgraph_pass has not been registered at (/paddle/paddle/fluid/framework/ir/pass.h:201)

您好，报这个错是因为编译的时候没有开启GPU或者没有找到TensorRT，辛苦检查一下重新试下。
1.8.5测试的时候报错是什么，也是这个么

**Comment by bluestinger** [comment]
1.8.5的是

**Comment by bluestinger** [comment]
InvalidArgumentError: TensorRT's tensor input requires at least 2 dimensions, but input 1 has 1 dims.
[Hint: Expected shape.size() > 1UL, but received shape.size():1 <= 1UL:1.] at (/paddle /trt_refine_int8/paddle/fluid/inference/tensorrt/engine.h:67)

**Comment by shangzhizhou** [comment]
您好，您的模型我在2.0.1下测试是可以推理的，辛苦更新下版本测试下。

**Comment by bluestinger** [comment]
没有修改config.set_trt_dynamic_shape_info，就能直接运行吗？
我用2.0.2，报错

**Comment by bluestinger** [comment]
E0420 08:23:30.523020  9505 paddle_pass_builder.cc:159] GPU not support MKLDNN yet
W0420 08:23:30.523105  9505 analysis_predictor.cc:1145] Deprecated. Please use CreatePredictor instead.
W0420 08:23:32.316156  9505 analysis_predictor.cc:677] The one-time configuration of analysis predictor failed, which may be due to native predictor called first and its configurations taken effect.
E0420 08:23:32.316365  9505 paddle_pass_builder.cc:159] GPU not support MKLDNN yet
I0420 08:23:32.316488  9505 analysis_predictor.cc:155] Profiler is deactivated, and no profiling report will be generated.
I0420 08:23:32.440538  9505 analysis_predictor.cc:522] TensorRT subgraph engine is enabled
I0420 08:23:32.440606  9505 analysis_predictor.cc:553] MKLDNN is enabled
--- Running analysis [ir_graph_build_pass]
--- Running analysis [ir_graph_clean_pass]
--- Running analysis [ir_analysis_pass]
--- Running IR pass [conv_affine_channel_fuse_pass]
--- Running IR pass [adaptive_pool2d_convert_global_pass]
--- Running IR pass [conv_eltwiseadd_affine_channel_fuse_pass]
--- Running IR pass [shuffle_channel_detect_pass]
--- Running IR pass [quant_conv2d_dequant_fuse_pass]
--- Running IR pass [delete_quant_dequant_op_pass]
--- Running IR pass [delete_quant_dequant_filter_op_pass]
--- Running IR pass [simplify_with_basic_ops_pass]
--- Running IR pass [embedding_eltwise_layernorm_fuse_pass]
I0420 08:23:33.657507  9505 graph_pattern_detector.cc:101] ---  detected 1 subgraphs
I0420 08:23:33.658574  9505 graph_pattern_detector.cc:101] ---  detected 1 subgraphs
I0420 08:23:33.663038  9505 graph_pattern_detector.cc:101] ---  detected 25 subgraphs
--- Running IR pass [multihead_matmul_fuse_pass_v2]
I0420 08:23:33.769415  9505 graph_pattern_detector.cc:101] ---  detected 12 subgraphs
--- Running IR pass [multihead_matmul_fuse_pass_v3]
--- Running IR pass [skip_layernorm_fuse_pass]
I0420 08:23:33.841665  9505 graph_pattern_detector.cc:101] ---  detected 24 subgraphs
--- Running IR pass [unsqueeze2_eltwise_fuse_pass]
--- Running IR pass [conv_bn_fuse_pass]
--- Running IR pass [squeeze2_matmul_fuse_pass]
--- Running IR pass [reshape2_matmul_fuse_pass]
--- Running IR pass [flatten2_matmul_fuse_pass]
--- Running IR pass [map_matmul_to_mul_pass]
--- Running IR pass [fc_fuse_pass]
I0420 08:23:33.851949  9505 graph_pattern_detector.cc:101] ---  detected 12 subgraphs
I0420 08:23:33.855298  9505 graph_pattern_detector.cc:101] ---  detected 25 subgraphs
--- Running IR pass [conv_elementwise_add_fuse_pass]
--- Running IR pass [tensorrt_subgraph_pass]
I0420 08:23:33.866433  9505 tensorrt_subgraph_pass.cc:126] ---  detect a sub-graph with 80 nodes
W0420 08:23:33.868973  9505 tensorrt_subgraph_pass.cc:304] The Paddle lib links the 6015 version TensorRT, make sure the runtime TensorRT you are using is no less than this version, otherwise, there might be Segfault!
I0420 08:23:33.871428  9505 tensorrt_subgraph_pass.cc:347] Prepare TRT engine (Optimize model structure, Select OP kernel etc). This process may cost a lot of time.
I0420 08:23:35.120455  9505 engine.cc:204] Run Paddle-TRT Dynamic Shape mode.
E0420 08:23:35.120579  9505 helper.h:78] Parameter check failed at: optimizationProfile.cpp::setDimensions::119, condition: std::all_of(dims.d, dims.d + dims.nbDims, [](int x) { return x > 0; })
E0420 08:23:35.137423  9505 helper.h:78] Parameter check failed at: ../builder/BuilderConfig.cpp::addOptimizationProfile::150, condition: profile->isValid()
E0420 08:23:35.137697  9505 helper.h:78] Network has dynamic or shape inputs, but no optimization profile has been defined.
Traceback (most recent call last):
  File "Demo_pre5.py", line 119, in <module>
    pred=create_predictor()
  File "Demo_pre5.py", line 68, in create_predictor
    predictor=create_paddle_predictor(config)
SystemError: (Fatal) Build TensorRT cuda engine failed! Please recheck you configurations related to paddle-TensorRT.
  [Hint: infer_engine_ should not be null.] (at /paddle/paddle/fluid/inference/tensorrt/engine.cc:244)

**Comment by bluestinger** [comment]
config.set_trt_dynamic_shape_info

**Comment by bluestinger** [comment]
config.set_trt_dynamic_shape_info 设置的输入name，shape是怎么确定的，__model__里吗？

**Comment by shangzhizhou** [comment]
name如果配置错了，日志中会有提示。shape是实际运行时输入的shape范围，不能有负数。

**Comment by bluestinger** [comment]
> 您好，您的模型我在2.0.1下测试是可以推理的，辛苦更新下版本测试下。

没有修改config.set_trt_dynamic_shape_info，就能直接运行吗？
我用2.0.2报错,这个错误呢？

**Comment by shangzhizhou** [comment]
这个报错应该因为您的动态shape设置了负数
names[4]:[-1,1], #minshape不能有-1，这个改成1试试？

**Comment by bluestinger** [comment]
确实能运行了，谢谢～
