### ISSUE TITLE
服务器离线部署报错

### ISSUE THREAD

**Issue by gaogaoxingxing2010** [PaddlePaddle/Paddle#32183]
服务器离线anaconda安装paddle后输入import paddle.fluid as fluid报错：
OSError: [WinError 127] 找不到指定的程序      d:\\ProgramData\\Anaconda3\\Lib\\site-packages\\numpy\\.libs
以上路径是真实存在的，路径下也有dll文件
可是我笔记本上同为win7系统离线就没出问题啊，请帮忙看下？
附图安装paddle包时报错，尽管报错笔记本上import paddle.fluid as
![IMG_20210409_192509](https://user-images.githubusercontent.com/62227361/114265444-60976700-9a23-11eb-8eee-534670f3a84f.jpg)

**Comment by joey12300** [comment]
您好，请试试重新安装 `numpy`。

**Comment by gaogaoxingxing2010** [comment]
> 您好，请试试重新安装 `numpy`。

感谢回复，尝试过卸载原anaconda自带numpy，再装paddle中适配的numpy，报winerror127；尝试过保留anaconda自带numpy，paddlepaddle就winerror127错误；重新安装需要先卸载吧？我再试试
另外，服务器是win7，外网我用win10生成requirement.txt并下载离线安装包拷贝至离线服务器，anaconda版本相同。不同操作系统会有问题吗？

**Comment by joey12300** [comment]
> > 您好，请试试重新安装 `numpy`。
> 
> 感谢回复，尝试过卸载原anaconda自带numpy，再装paddle中适配的numpy，报winerror127；尝试过保留anaconda自带numpy，paddlepaddle就winerror127错误；重新安装需要先卸载吧？我再试试
> 另外，服务器是win7，外网我用win10生成requirement.txt并下载离线安装包拷贝至离线服务器，anaconda版本相同。不同操作系统会有问题吗？

应该问题不大，对numpy版本有一定要求，windows的numpy版本>=1.13, <=1.19.3，看看是否满足版本要求

**Comment by gaogaoxingxing2010** [comment]
> > > 您好，请试试重新安装 `numpy`。
> > 
> > 
> > 感谢回复，尝试过卸载原anaconda自带numpy，再装paddle中适配的numpy，报winerror127；尝试过保留anaconda自带numpy，paddlepaddle就winerror127错误；重新安装需要先卸载吧？我再试试
> > 另外，服务器是win7，外网我用win10生成requirement.txt并下载离线安装包拷贝至离线服务器，anaconda版本相同。不同操作系统会有问题吗？
> 
> 应该问题不大，对numpy版本有一定要求，windows的numpy版本>=1.13, <=1.19.3，看看是否满足版本要求

感谢回复！paddlepaddle在win系统的版本范围是？

**Comment by Superjomn** [comment]
总的大概率是 pip 安装包的版本不对应

两个方面：

1. 上图 
![image](https://user-images.githubusercontent.com/328693/114331668-14f5d200-9b77-11eb-8103-36d93501c5c1.png) 可以试试，是不是pip匹配包的逻辑策略失败

2. 尝试用 virtualenv 来从零安装 paddle 需要的包；因为直接在全局python里安装，已安装的包的版本可能版本更高，从而让paddle的依赖变乱；注意 python3 之后调用安装包的方式： `python3 -m virtualenv <env_name>`

参考 https://pythonbasics.org/virtualenv/

**Comment by gaogaoxingxing2010** [comment]
已解决，感谢！

**Comment by cumtqiangqiang** [comment]
> 已解决，感谢！

hi 你怎么解决的啊，我也遇到了同样的问题
