### ISSUE TITLE
安装paddlepaddle成功但导入报错：name 'batch' is not defined ,请问怎么解决？

### ISSUE THREAD

**Issue by thepolarex** [PaddlePaddle/Paddle#32187]
> 为使您的问题得到快速解决，在建立Issue前，请您先通过如下方式搜索是否有相似问题:【搜索issue关键字】【使用labels筛选】【官方文档】

建立issue时，为快速解决问题，请您根据使用情况给出如下信息：
- 标题：请包含关键词“安装错误”/“编译错误”，例如“Mac编译错误”
- 版本、环境信息：
    1）PaddlePaddle版本：请提供您的PaddlePaddle版本号（如1.1）或CommitID
    2）CPU：请提供CPU型号，MKL/OpenBlas/MKLDNN/等数学库的使用情况
    3）GPU：请提供GPU型号，CUDA和CUDNN版本号
    4）系统环境：请说明系统类型、版本（如Mac OS 10.14）、Python版本
注：您可以通过执行[summary_env.py](https://github.com/PaddlePaddle/Paddle/blob/develop/tools/summary_env.py)获取以上信息。
- 安装方式信息：
1）pip安装/docker安装
2）本地编译：请提供cmake命令，编译命令
3）docker编译：请提供docker镜像，编译命令            
  特殊环境请注明：如离线安装等
- 复现信息：如为报错，请给出复现环境、复现步骤
- 问题描述：请详细描述您的问题，同步贴出报错信息、日志/代码关键片段

Thank you for contributing to PaddlePaddle.
Before submitting the issue, you could search issue in Github in case that there was a similar issue submitted or resolved before.
If there is no solution,please make sure that this is an installation issue including the following details:
**System information**
-PaddlePaddle version （eg.1.1）or CommitID
-CPU: including CPUMKL/OpenBlas/MKLDNN version
-GPU: including CUDA/CUDNN version
-OS Platform (eg. Mac OS 10.14)
-Python version
- Install method: pip install/install with docker/build from source(without docker)/build within docker
- Other special cases that you think may be related to this problem, eg. offline install, special internet condition 
Note: You can get most of the information by running [summary_env.py](https://github.com/PaddlePaddle/Paddle/blob/develop/tools/summary_env.py).   

**To Reproduce**
Steps to reproduce the behavior
**Describe your current behavior**
**Code to reproduce the issue**
**Other info / logs**

**Comment by gongweibao** [comment]
能否贴一下详细点的日志？

**Comment by thepolarex** [comment]
> 能否贴一下详细点的日志？

**Comment by thepolarex** [comment]
![Uploading IMG_20210412_102342.jpg…]()

**Comment by thepolarex** [comment]
![Uploading IMG_20210412_102342.jpg…]()

**Comment by thepolarex** [comment]
> 能否贴一下详细点的日志？

你好 能看到我上传的图片吗

**Comment by thepolarex** [comment]
![IMG_20210412_102342](https://user-images.githubusercontent.com/82299502/114334367-027e9700-9b7d-11eb-8408-7f889d265686.jpg)

**Comment by thepolarex** [comment]
![IMG_20210412_105333](https://user-images.githubusercontent.com/82299502/114334580-6bfea580-9b7d-11eb-8662-2cf7357d2285.jpg)
这个是按照paddle首页指令安装后导入报错，然后按框出来的指令重新安装后继续报错'batch'的那个

**Comment by gongweibao** [comment]
看这个能否帮到你？https://github.com/PaddlePaddle/Paddle/issues/25609
如果还不行，请帖一下你的安装命令。

**Comment by thepolarex** [comment]
> 看这个能否帮到你？#25609
> 如果还不行，请帖一下你的安装命令。

一开始是：python -m pip install paddlepaddle==2.0.1 -i https://mirror.baidu.com/pypi/simple
然后改成：    python -m pip install -U paddlepaddle==2.0.1 -f https://paddlepaddle.org.cn/whl/stable_noavx.html

原来两个指令都是出现同样的以下错误：

首先import paddle报错： ModuleNotFoundError: No module named 'paddle.fluid.core_noavx'
不关闭编译器再尝试import paddle就会报错： NameError: name 'batch' is not defined

请问你发的链接 缺的三个包要怎样安装？ win10系统的，直接用pip安装吗

**Comment by myailab** [comment]
我也遇到相同的问题了，不过我只在使用jupyter时报这个错误，但使用Pycharm里远程调试时，没有报错。jupyter和pycharm连接的都是同一个服务器。
下面是我的服务器信息：
****************************************
Paddle version: 2.0.1
Paddle With CUDA: False
OS: CentOS Linux 7.6.1810
Python version: 3.6.8
CUDA version: None
cuDNN version: None.None.None
Nvidia driver version: None
****************************************

这个是jupyter里的报错信息：
![微信图片_20210430151420](https://user-images.githubusercontent.com/23287865/116661279-c34aa580-a9c6-11eb-8a71-e69f8294edb5.png)


这个是pycharm里运行的结果：
![微信图片_20210430151610](https://user-images.githubusercontent.com/23287865/116661436-060c7d80-a9c7-11eb-97a7-c4a6f71d2dc3.png)


现在还不清楚为什么jupyter不能正常执行，希望相关技术人员能排查一下。

**Comment by rancheng** [comment]
装好了之后试试重启一下kernel
