### ISSUE TITLE
安装报错：ERROR: No matching distribution found for paddlepaddle-gpu==2.0.1.post101

### ISSUE THREAD

**Issue by wht0948** [PaddlePaddle/Paddle#32182]
![image](https://user-images.githubusercontent.com/32132519/114263137-6c306100-9a16-11eb-85b5-e970ca320cbc.png)

cuda版本10.1

**Comment by joey12300** [comment]
您好，请试试是否能`ping https://paddlepaddle.org.cn/whl/mkl/stable.html`，可能是网络原因无法下载。

**Comment by wht0948** [comment]
> 您好，请试试是否能`ping https://paddlepaddle.org.cn/whl/mkl/stable.html`，可能是网络原因无法下载。

我如果不加post101，直接用pip3 install paddlepaddle-gpu==2.0.1 -f https://paddlepaddle.org.cn/whl/mkl/stable.html安装是可以的，但是我的cuda是10.1而且不太好改，所以有没有别的办法

**Comment by joey12300** [comment]
@wanghaotian233 可以试试用wget下载，再用pip install（可以根据你的python版本修改下面的37）。 https://paddle-wheel.bj.bcebos.com/2.0.1-gpu-cuda10.1-cudnn7-mkl_gcc8.2/paddlepaddle_gpu-2.0.1.post101-cp37-cp37m-linux_x86_64.whl

**Comment by wht0948** [comment]
> @wanghaotian233 可以试试用wget下载，再用pip install（可以根据你的python版本修改下面的37）。 https://paddle-wheel.bj.bcebos.com/2.0.1-gpu-cuda10.1-cudnn7-mkl_gcc8.2/paddlepaddle_gpu-2.0.1.post101-cp37-cp37m-linux_x86_64.whl

您好，我现在想在一台cuda11的机器上用安装包，请问下载链接是什么呀？感谢🙏
