### ISSUE TITLE
创造predictor后连续预测[Error] terminate called after throwing an instance of 'paddle::platform::EnforceNotMet'

### ISSUE THREAD

**Issue by RenyanDiao** [PaddlePaddle/Paddle#32195]
create predictor后连续喂图单张预测，都是在第36张图的时候报错，但这张图单拎出来预测结果正确，也没报错退出 paddle版本2.0

**Comment by Superjomn** [comment]
你好， `paddle::platform::EnforceNotMet` 里面一般都会一并输出错误信息，可以给完整错误信息截个图吗

**Comment by RenyanDiao** [comment]
> 你好， `paddle::platform::EnforceNotMet` 里面一般都会一并输出错误信息，可以给完整错误信息截个图吗

如流给你。。

**Comment by Xingyu-Romantic** [comment]
![image](https://user-images.githubusercontent.com/22713115/155445656-fce020de-ccfa-4bbc-a7cc-7bd2f4424789.png)

**Comment by Xingyu-Romantic** [comment]
我也遇到同样的问题了，是FastRCNN+SlowFast模型  时空动作定位

**Comment by Xingyu-Romantic** [comment]
I0224 10:26:17.922376  3303 operator.cc:191] CUDAPlace(0) Op(write_to_array), inputs:{I[array_length_0.tmp_0:int64_t[1]({})(CPUPlace)], X[_generated_var_4:float[5, 2304, 8, 8]({})(CUDAPlace(0))]}, outputs:{Out[array_0.out:[-1]({{}})()]}.
I0224 10:26:17.922395  3303 device_context.cc:81] DeviceContextPool Get: CUDAPlace(0)
I0224 10:26:17.922415  3303 array_operator.h:59]  Offset = 0
I0224 10:26:17.922431  3303 tensor_array_read_write_op.cc:47] Resize array_0.out from 0 to 1
I0224 10:26:17.922443  3303 device_context.cc:81] DeviceContextPool Get: CUDAPlace(0)
I0224 10:26:17.922454  3303 tensor_util.cu:40] TensorCopy 5, 2304, 8, 8 from CUDAPlace(0) to CUDAPlace(0)
I0224 10:26:17.922468  3303 memcpy.cc:400] memory::Copy 2949120 Bytes from CUDAPlace(0) to CUDAPlace(0) by stream(0x23140fc0)
I0224 10:26:17.922508  3303 operator.cc:235] CUDAPlace(0) Op(write_to_array), inputs:{I[array_length_0.tmp_0:int64_t[1]({})(CPUPlace)], X[_generated_var_4:float[5, 2304, 8, 8]({})(CUDAPlace(0))]}, outputs:{Out[array_0.out:[-1]({{}})()]}.
I0224 10:26:17.922528  3303 executor_gc_helper.cc:165] Erase variable array_length_0.tmp_0
I0224 10:26:17.922539  3303 executor_gc_helper.cc:165] Erase variable _generated_var_4
I0224 10:26:17.922554  3303 naive_best_fit_allocator.cc:102] Free pointer=0x7fa7c48a1040 on CPUPlace
I0224 10:26:17.922566  3303 buddy_allocator.cc:107] Free from address 0x7fa7c48a1000
I0224 10:26:17.922578  3303 meta_cache.cc:38] Load MemoryBlock::Desc type=1
I0224 10:26:17.922593  3303 meta_cache.cc:38] Load MemoryBlock::Desc type=1
I0224 10:26:17.922603  3303 meta_cache.cc:38] Load MemoryBlock::Desc type=0
I0224 10:26:17.922616  3303 buddy_allocator.cc:128] Merging this block 0x7fa7c48a1000 with its right buddy 0x7fa7c48a2000
I0224 10:26:17.922626  3303 meta_cache.cc:38] Load MemoryBlock::Desc type=0
I0224 10:26:17.922637  3303 meta_cache.cc:38] Load MemoryBlock::Desc type=0
I0224 10:26:17.922646  3303 meta_cache.cc:38] Load MemoryBlock::Desc type=0
I0224 10:26:17.922657  3303 meta_cache.cc:38] Load MemoryBlock::Desc type=0
I0224 10:26:17.922667  3303 buddy_allocator.cc:145] Merging this block 0x7fa7c48a1000 with its left buddy 0x7fa7c48a0000
I0224 10:26:17.922678  3303 meta_cache.cc:38] Load MemoryBlock::Desc type=1
I0224 10:26:17.922688  3303 buddy_allocator.cc:163] Inserting free block (0x7fa7c48a1000, 462241792)
I0224 10:26:17.922709  3303 operator.cc:191] CUDAPlace(0) Op(scale), inputs:{ScaleTensor[], X[fill_constant_1.tmp_0:int64_t[1]({})(CUDAPlace(0))]}, outputs:{Out[tmp_6:[0]({})()]}.
I0224 10:26:17.922729  3303 device_context.cc:81] DeviceContextPool Get: CUDAPlace(0)
I0224 10:26:17.922742  3303 device_context.cc:81] DeviceContextPool Get: CUDAPlace(0)
I0224 10:26:17.922767  3303 operator.cc:1239] op type:scale, expected_kernel_key:data_type[int64_t]:data_layout[ANY_LAYOUT]:place[CUDAPlace(0)]:library_type[PLAIN]
I0224 10:26:17.922819  3303 operator.cc:235] CUDAPlace(0) Op(scale), inputs:{ScaleTensor[], X[fill_constant_1.tmp_0:int64_t[1]({})(CUDAPlace(0))]}, outputs:{Out[tmp_6:int64_t[1]({})(CUDAPlace(0))]}.
I0224 10:26:17.922842  3303 operator.cc:191] CUDAPlace(0) Op(shape), inputs:{Input[concat_4.tmp_0:float[1, 2304, 1, 16, 29]({})(CUDAPlace(0))]}, outputs:{Out[shape_4.tmp_0:[0]({})()]}.
I0224 10:26:17.922856  3303 device_context.cc:81] DeviceContextPool Get: CUDAPlace(0)
I0224 10:26:17.922871  3303 device_context.cc:81] DeviceContextPool Get: CUDAPlace(0)
I0224 10:26:17.922885  3303 operator.cc:1239] op type:shape, expected_kernel_key:data_type[float]:data_layout[ANY_LAYOUT]:place[CUDAPlace(0)]:library_type[PLAIN]
I0224 10:26:17.922901  3303 naive_best_fit_allocator.cc:90] Allocate 20 bytes on CPUPlace
I0224 10:26:17.922917  3303 buddy_allocator.cc:68] Allocate 20 bytes from chunk size 4096
I0224 10:26:17.922938  3303 buddy_allocator.cc:88] Allocation from existing memory block 0x7fa7c48a1000 at address 0x7fa7c48a1040
I0224 10:26:17.922948  3303 meta_cache.cc:38] Load MemoryBlock::Desc type=0
I0224 10:26:17.922958  3303 buddy_allocator.cc:305] Split block (0x7fa7c48a1000, 462241792) into
I0224 10:26:17.922971  3303 meta_cache.cc:38] Load MemoryBlock::Desc type=0
I0224 10:26:17.922986  3303 buddy_allocator.cc:309] Left block (0x7fa7c48a1000, 4096)
I0224 10:26:17.922997  3303 meta_cache.cc:38] Load MemoryBlock::Desc type=1
I0224 10:26:17.923009  3303 meta_cache.cc:38] Load MemoryBlock::Desc type=0
I0224 10:26:17.923020  3303 buddy_allocator.cc:317] Insert right block (0x7fa7c48a2000, 462237696)
I0224 10:26:17.923029  3303 naive_best_fit_allocator.cc:95]   pointer=0x7fa7c48a1040
I0224 10:26:17.923046  3303 operator.cc:235] CUDAPlace(0) Op(shape), inputs:{Input[concat_4.tmp_0:float[1, 2304, 1, 16, 29]({})(CUDAPlace(0))]}, outputs:{Out[shape_4.tmp_0:int[5]({})(CPUPlace)]}.
I0224 10:26:17.923063  3303 operator.cc:191] CUDAPlace(0) Op(slice), inputs:{EndsTensor[], EndsTensorList[], Input[shape_4.tmp_0:int[5]({})(CPUPlace)], StartsTensor[], StartsTensorList[]}, outputs:{Out[shape_4.tmp_0_slice_0:[0]({})()]}.
I0224 10:26:17.923077  3303 device_context.cc:81] DeviceContextPool Get: CUDAPlace(0)
I0224 10:26:17.923089  3303 device_context.cc:81] DeviceContextPool Get: CUDAPlace(0)
I0224 10:26:17.923103  3303 operator.cc:1239] op type:slice, expected_kernel_key:data_type[int]:data_layout[ANY_LAYOUT]:place[CPUPlace]:library_type[PLAIN]
I0224 10:26:17.923116  3303 device_context.cc:81] DeviceContextPool Get: CPUPlace
I0224 10:26:17.923138  3303 naive_best_fit_allocator.cc:90] Allocate 4 bytes on CPUPlace
I0224 10:26:17.923149  3303 buddy_allocator.cc:68] Allocate 4 bytes from chunk size 4096
I0224 10:26:17.923205  3303 buddy_allocator.cc:88] Allocation from existing memory block 0x7fa7c48a2000 at address 0x7fa7c48a2040
I0224 10:26:17.923224  3303 meta_cache.cc:38] Load MemoryBlock::Desc type=0
I0224 10:26:17.923234  3303 buddy_allocator.cc:305] Split block (0x7fa7c48a2000, 462237696) into
I0224 10:26:17.923246  3303 meta_cache.cc:38] Load MemoryBlock::Desc type=0
I0224 10:26:17.923259  3303 buddy_allocator.cc:309] Left block (0x7fa7c48a2000, 4096)
I0224 10:26:17.923269  3303 meta_cache.cc:38] Load MemoryBlock::Desc type=1
I0224 10:26:17.923277  3303 meta_cache.cc:38] Load MemoryBlock::Desc type=0
I0224 10:26:17.923287  3303 buddy_allocator.cc:317] Insert right block (0x7fa7c48a3000, 462233600)
I0224 10:26:17.923303  3303 naive_best_fit_allocator.cc:95]   pointer=0x7fa7c48a2040
I0224 10:26:17.923326  3303 operator.cc:235] CPUPlace Op(slice), inputs:{EndsTensor[], EndsTensorList[], Input[shape_4.tmp_0:int[5]({})(CPUPlace)], StartsTensor[], StartsTensorList[]}, outputs:{Out[shape_4.tmp_0_slice_0:int[1]({})(CPUPlace)]}.
I0224 10:26:17.923347  3303 executor_gc_helper.cc:165] Erase variable shape_4.tmp_0
I0224 10:26:17.923358  3303 naive_best_fit_allocator.cc:102] Free pointer=0x7fa7c48a1040 on CPUPlace
I0224 10:26:17.923368  3303 buddy_allocator.cc:107] Free from address 0x7fa7c48a1000
I0224 10:26:17.923379  3303 meta_cache.cc:38] Load MemoryBlock::Desc type=1
I0224 10:26:17.923388  3303 meta_cache.cc:38] Load MemoryBlock::Desc type=1
I0224 10:26:17.923400  3303 meta_cache.cc:38] Load MemoryBlock::Desc type=0
I0224 10:26:17.923413  3303 buddy_allocator.cc:128] Merging this block 0x7fa7c48a1000 with its right buddy 0x7fa7c48a2000
I0224 10:26:17.923429  3303 meta_cache.cc:38] Load MemoryBlock::Desc type=1
I0224 10:26:17.923442  3303 meta_cache.cc:38] Load MemoryBlock::Desc type=0
I0224 10:26:17.923457  3303 buddy_allocator.cc:145] Merging this block 0x7fa7c48a1000 with its left buddy 0x7fa7c48a0000
I0224 10:26:17.923475  3303 meta_cache.cc:38] Load MemoryBlock::Desc type=1
I0224 10:26:17.923483  3303 buddy_allocator.cc:163] Inserting free block (0x7fa7c48a1000, 4096)
I0224 10:26:17.923502  3303 operator.cc:191] CUDAPlace(0) Op(cast), inputs:{X[shape_4.tmp_0_slice_0:int[1]({})(CPUPlace)]}, outputs:{Out[tmp_7:[0]({})()]}.
I0224 10:26:17.923516  3303 device_context.cc:81] DeviceContextPool Get: CUDAPlace(0)
I0224 10:26:17.923530  3303 device_context.cc:81] DeviceContextPool Get: CUDAPlace(0)
I0224 10:26:17.923542  3303 operator.cc:1239] op type:cast, expected_kernel_key:data_type[int]:data_layout[ANY_LAYOUT]:place[CPUPlace]:library_type[PLAIN]
I0224 10:26:17.923557  3303 device_context.cc:81] DeviceContextPool Get: CPUPlace
I0224 10:26:17.923571  3303 naive_best_fit_allocator.cc:90] Allocate 8 bytes on CPUPlace
I0224 10:26:17.923584  3303 buddy_allocator.cc:68] Allocate 8 bytes from chunk size 4096
I0224 10:26:17.923595  3303 buddy_allocator.cc:88] Allocation from existing memory block 0x7fa7c48a1000 at address 0x7fa7c48a1040
I0224 10:26:17.923610  3303 meta_cache.cc:38] Load MemoryBlock::Desc type=0
I0224 10:26:17.923619  3303 buddy_allocator.cc:305] Split block (0x7fa7c48a1000, 4096) into
I0224 10:26:17.923629  3303 meta_cache.cc:38] Load MemoryBlock::Desc type=0
I0224 10:26:17.923640  3303 buddy_allocator.cc:309] Left block (0x7fa7c48a1000, 4096)
I0224 10:26:17.923655  3303 meta_cache.cc:38] Load MemoryBlock::Desc type=1
I0224 10:26:17.923666  3303 meta_cache.cc:38] Load MemoryBlock::Desc type=1
I0224 10:26:17.923676  3303 naive_best_fit_allocator.cc:95]   pointer=0x7fa7c48a1040
I0224 10:26:17.923705  3303 operator.cc:235] CPUPlace Op(cast), inputs:{X[shape_4.tmp_0_slice_0:int[1]({})(CPUPlace)]}, outputs:{Out[tmp_7:int64_t[1]({})(CPUPlace)]}.
I0224 10:26:17.923720  3303 executor_gc_helper.cc:165] Erase variable shape_4.tmp_0_slice_0
I0224 10:26:17.923730  3303 naive_best_fit_allocator.cc:102] Free pointer=0x7fa7c48a2040 on CPUPlace
I0224 10:26:17.923740  3303 buddy_allocator.cc:107] Free from address 0x7fa7c48a2000
I0224 10:26:17.923771  3303 meta_cache.cc:38] Load MemoryBlock::Desc type=1
I0224 10:26:17.923797  3303 meta_cache.cc:38] Load MemoryBlock::Desc type=1
I0224 10:26:17.923807  3303 meta_cache.cc:38] Load MemoryBlock::Desc type=0
I0224 10:26:17.923820  3303 buddy_allocator.cc:128] Merging this block 0x7fa7c48a2000 with its right buddy 0x7fa7c48a3000
I0224 10:26:17.923830  3303 meta_cache.cc:38] Load MemoryBlock::Desc type=0
I0224 10:26:17.923840  3303 meta_cache.cc:38] Load MemoryBlock::Desc type=0
I0224 10:26:17.923851  3303 meta_cache.cc:38] Load MemoryBlock::Desc type=0
I0224 10:26:17.923868  3303 meta_cache.cc:38] Load MemoryBlock::Desc type=0
I0224 10:26:17.923879  3303 buddy_allocator.cc:145] Merging this block 0x7fa7c48a2000 with its left buddy 0x7fa7c48a1000
I0224 10:26:17.923889  3303 meta_cache.cc:38] Load MemoryBlock::Desc type=1
I0224 10:26:17.923900  3303 buddy_allocator.cc:163] Inserting free block (0x7fa7c48a2000, 462237696)
I0224 10:26:17.923924  3303 operator.cc:191] CUDAPlace(0) Op(less_than), inputs:{X[tmp_6:int64_t[1]({})(CUDAPlace(0))], Y[tmp_7:int64_t[1]({})(CPUPlace)]}, outputs:{Out[tmp_8:[0]({})()]}.
I0224 10:26:17.923941  3303 device_context.cc:81] DeviceContextPool Get: CUDAPlace(0)
I0224 10:26:17.923950  3303 device_context.cc:81] DeviceContextPool Get: CUDAPlace(0)
I0224 10:26:17.923964  3303 operator.cc:1239] op type:less_than, expected_kernel_key:data_type[int64_t]:data_layout[ANY_LAYOUT]:place[CUDAPlace(0)]:library_type[PLAIN]
I0224 10:26:17.923977  3303 operator.cc:1454] Transform Variable tmp_7 from data_type[int64_t]:data_layout[NCHW]:place[CPUPlace]:library_type[PLAIN] to data_type[int64_t]:data_layout[ANY_LAYOUT]:place[CUDAPlace(0)]:library_type[PLAIN]
I0224 10:26:17.924005  3303 scope.cc:172] Create variable tmp_7
I0224 10:26:17.924019  3303 data_device_transform.cc:21] DeviceTransform in, src_place CPUPlace dst_place: CUDAPlace(0)
I0224 10:26:17.924029  3303 device_context.cc:81] DeviceContextPool Get: CPUPlace
I0224 10:26:17.924041  3303 device_context.cc:81] DeviceContextPool Get: CUDAPlace(0)
I0224 10:26:17.989987  3303 op_call_stack.cc:61] ExternalError:  Cuda error(700), an illegal memory access was encountered.
  [Advise: Please search for the error code(700) on website( https://docs.nvidia.com/cuda/archive/10.0/cuda-runtime-api/group__CUDART__TYPES.html#group__CUDART__TYPES_1g3f51e3575c2178246db0a94a430e0038 ) to get Nvidia's official solution about CUDA Error.] (at /paddle/paddle/fluid/platform/stream/cuda_stream.cc:95)
I0224 10:26:17.990190  3303 executor.cc:66] destroy ExecutorPrepareContext
Traceback (most recent call last):
  File "ji.py", line 93, in <module>
    print(process_image(init(), '/home/data/607/fall_recognition_20210816_1210.mp4'))
  File "ji.py", line 79, in process_image
    predictor.run()
OSError: In user code:

    File "tools/export_model.py", line 208, in <module>
      main()
    File "tools/export_model.py", line 202, in main
      paddle.jit.save(model, osp.join(args.output_path, model_name))
    File "<decorator-gen-101>", line 2, in save
      
    File "/usr/local/lib/python3.6/dist-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
      return wrapped_func(*args, **kwargs)
    File "/usr/local/lib/python3.6/dist-packages/paddle/fluid/dygraph/base.py", line 51, in __impl__
      return func(*args, **kwargs)
    File "/usr/local/lib/python3.6/dist-packages/paddle/fluid/dygraph/jit.py", line 744, in save
      inner_input_spec)
    File "/usr/local/lib/python3.6/dist-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 517, in concrete_program_specify_input_spec
      *desired_input_spec)
    File "/usr/local/lib/python3.6/dist-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 427, in get_concrete_program
      concrete_program, partial_program_layer = self._program_cache[cache_key]
    File "/usr/local/lib/python3.6/dist-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 723, in __getitem__
      self._caches[item] = self._build_once(item)
    File "/usr/local/lib/python3.6/dist-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 714, in _build_once
      **cache_key.kwargs)
    File "<decorator-gen-99>", line 2, in from_func_spec
      
    File "/usr/local/lib/python3.6/dist-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
      return wrapped_func(*args, **kwargs)
    File "/usr/local/lib/python3.6/dist-packages/paddle/fluid/dygraph/base.py", line 51, in __impl__
      return func(*args, **kwargs)
    File "/usr/local/lib/python3.6/dist-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 662, in from_func_spec
      outputs = static_func(*inputs)
    File "/tmp/tmp6yo3yncr.py", line 63, in forward
      __return_value_0, data_batch, mode), (__return_value_0,))
    File "/usr/local/lib/python3.6/dist-packages/paddle/fluid/dygraph/dygraph_to_static/convert_operators.py", line 211, in convert_ifelse
      out = _run_py_ifelse(pred, true_fn, false_fn, true_args, false_args)
    File "/usr/local/lib/python3.6/dist-packages/paddle/fluid/dygraph/dygraph_to_static/convert_operators.py", line 257, in _run_py_ifelse
      return true_fn(*true_args) if pred else false_fn(*false_args)
    File "/tmp/tmp6yo3yncr.py", line 59, in false_fn_3
      mode), (__return_value_0, data_batch, mode), (__return_value_0,))
    File "/usr/local/lib/python3.6/dist-packages/paddle/fluid/dygraph/dygraph_to_static/convert_operators.py", line 211, in convert_ifelse
      out = _run_py_ifelse(pred, true_fn, false_fn, true_args, false_args)
    File "/usr/local/lib/python3.6/dist-packages/paddle/fluid/dygraph/dygraph_to_static/convert_operators.py", line 257, in _run_py_ifelse
      return true_fn(*true_args) if pred else false_fn(*false_args)
    File "/tmp/tmp6yo3yncr.py", line 55, in false_fn_2
      __return_value_0,))
    File "/usr/local/lib/python3.6/dist-packages/paddle/fluid/dygraph/dygraph_to_static/convert_operators.py", line 211, in convert_ifelse
      out = _run_py_ifelse(pred, true_fn, false_fn, true_args, false_args)
    File "/usr/local/lib/python3.6/dist-packages/paddle/fluid/dygraph/dygraph_to_static/convert_operators.py", line 257, in _run_py_ifelse
      return true_fn(*true_args) if pred else false_fn(*false_args)
    File "/tmp/tmp6yo3yncr.py", line 49, in false_fn_1
      data_batch, mode), (__return_value_0,), (__return_value_0,)
    File "/usr/local/lib/python3.6/dist-packages/paddle/fluid/dygraph/dygraph_to_static/convert_operators.py", line 211, in convert_ifelse
      out = _run_py_ifelse(pred, true_fn, false_fn, true_args, false_args)
    File "/usr/local/lib/python3.6/dist-packages/paddle/fluid/dygraph/dygraph_to_static/convert_operators.py", line 257, in _run_py_ifelse
      return true_fn(*true_args) if pred else false_fn(*false_args)
    File "/project/train/src_repo/PaddleVideo/paddlevideo/modeling/framework/detectors/base.py", line 31, in forward
      return self.infer_step(data_batch)
    File "/project/train/src_repo/PaddleVideo/paddlevideo/modeling/framework/detectors/two_stage.py", line 126, in infer_step
      img_shape,
    File "/project/train/src_repo/PaddleVideo/paddlevideo/modeling/heads/roi_head.py", line 149, in simple_test
      self.action_thr,
    File "/project/train/src_repo/PaddleVideo/paddlevideo/modeling/heads/roi_head.py", line 166, in simple_test_bboxes
      bbox_results = self._bbox_forward(x, rois, rois_num)
    File "/project/train/src_repo/PaddleVideo/paddlevideo/modeling/heads/roi_head.py", line 100, in _bbox_forward
      bbox_feat = self.bbox_roi_extractor(x, rois, rois_num)
    File "/usr/local/lib/python3.6/dist-packages/paddle/fluid/dygraph/layers.py", line 917, in __call__
      return self._dygraph_call_func(*inputs, **kwargs)
    File "/usr/local/lib/python3.6/dist-packages/paddle/fluid/dygraph/layers.py", line 907, in _dygraph_call_func
      outputs = self.forward(*inputs, **kwargs)
    File "/tmp/tmpnrywzzc_.py", line 73, in forward
      for_loop_body_5, [t, rois_num, roi_feats, feat, rois])
    File "/usr/local/lib/python3.6/dist-packages/paddle/fluid/dygraph/dygraph_to_static/convert_operators.py", line 43, in convert_while_loop
      loop_vars = _run_paddle_while_loop(cond, body, loop_vars)
    File "/usr/local/lib/python3.6/dist-packages/paddle/fluid/dygraph/dygraph_to_static/convert_operators.py", line 53, in _run_paddle_while_loop
      loop_vars = control_flow.while_loop(cond, body, loop_vars)
    File "/usr/local/lib/python3.6/dist-packages/paddle/fluid/layers/control_flow.py", line 1250, in while_loop
      now_cond = cond(*output_vars)
    File "/tmp/tmpnrywzzc_.py", line 46, in for_loop_condition_5
      in_control_flow=True)
    File "/usr/local/lib/python3.6/dist-packages/paddle/fluid/layers/math_op_patch.py", line 347, in __impl__
      attrs={'axis': axis})
    File "/usr/local/lib/python3.6/dist-packages/paddle/fluid/framework.py", line 3184, in append_op
      attrs=kwargs.get("attrs", None))
    File "/usr/local/lib/python3.6/dist-packages/paddle/fluid/framework.py", line 2224, in __init__
      for frame in traceback.extract_stack():

    ExternalError:  Cuda error(700), an illegal memory access was encountered.
      [Advise: Please search for the error code(700) on website( https://docs.nvidia.com/cuda/archive/10.0/cuda-runtime-api/group__CUDART__TYPES.html#group__CUDART__TYPES_1g3f51e3575c2178246db0a94a430e0038 ) to get Nvidia's official solution about CUDA Error.] (at /paddle/paddle/fluid/platform/stream/cuda_stream.cc:95)
      [operator < less_than > error]
I0224 10:26:17.991129  3303 imperative.cc:1511] Tracer(0x3e346a0) set expected place CUDAPlace(0)
I0224 10:26:17.991204  3303 tracer.cc:39] Set current tracer: 0
I0224 10:26:17.991307  3303 mmap_allocator.cc:122] PID: 3303, MemoryMapFdSet: set size - 0
I0224 10:26:18.066112  3303 naive_best_fit_allocator.cc:102] Free pointer=0x7fa7c48a0040 on CPUPlace
I0224 10:26:18.066188  3303 buddy_allocator.cc:107] Free from address 0x7fa7c48a0000
I0224 10:26:18.066200  3303 meta_cache.cc:38] Load MemoryBlock::Desc type=1
I0224 10:26:18.066210  3303 meta_cache.cc:38] Load MemoryBlock::Desc type=1
I0224 10:26:18.066217  3303 meta_cache.cc:38] Load MemoryBlock::Desc type=0
I0224 10:26:18.066226  3303 buddy_allocator.cc:128] Merging this block 0x7fa7c48a0000 with its right buddy 0x7fa7c48a1000
I0224 10:26:18.066233  3303 meta_cache.cc:38] Load MemoryBlock::Desc type=1
I0224 10:26:18.066242  3303 meta_cache.cc:38] Load MemoryBlock::Desc type=0
I0224 10:26:18.066251  3303 buddy_allocator.cc:145] Merging this block 0x7fa7c48a0000 with its left buddy 0x7fa7c489f000
I0224 10:26:18.066258  3303 meta_cache.cc:38] Load MemoryBlock::Desc type=1
I0224 10:26:18.066274  3303 buddy_allocator.cc:163] Inserting free block (0x7fa7c48a0000, 4096)
I0224 10:26:18.066323  3303 naive_best_fit_allocator.cc:102] Free pointer=0x7fa7c48a1040 on CPUPlace
I0224 10:26:18.066334  3303 buddy_allocator.cc:107] Free from address 0x7fa7c48a1000
I0224 10:26:18.066341  3303 meta_cache.cc:38] Load MemoryBlock::Desc type=1
I0224 10:26:18.066350  3303 meta_cache.cc:38] Load MemoryBlock::Desc type=1
I0224 10:26:18.066359  3303 meta_cache.cc:38] Load MemoryBlock::Desc type=0
I0224 10:26:18.066366  3303 buddy_allocator.cc:128] Merging this block 0x7fa7c48a1000 with its right buddy 0x7fa7c48a2000
I0224 10:26:18.066375  3303 meta_cache.cc:38] Load MemoryBlock::Desc type=0
I0224 10:26:18.066383  3303 meta_cache.cc:38] Load MemoryBlock::Desc type=0
I0224 10:26:18.066398  3303 meta_cache.cc:38] Load MemoryBlock::Desc type=0
I0224 10:26:18.066406  3303 meta_cache.cc:38] Load MemoryBlock::Desc type=0
I0224 10:26:18.066414  3303 buddy_allocator.cc:145] Merging this block 0x7fa7c48a1000 with its left buddy 0x7fa7c48a0000
I0224 10:26:18.066422  3303 meta_cache.cc:38] Load MemoryBlock::Desc type=0
I0224 10:26:18.066429  3303 meta_cache.cc:38] Load MemoryBlock::Desc type=0
I0224 10:26:18.066437  3303 meta_cache.cc:38] Load MemoryBlock::Desc type=0
I0224 10:26:18.066444  3303 buddy_allocator.cc:163] Inserting free block (0x7fa7c48a0000, 462245888)
I0224 10:26:18.066498  3303 naive_best_fit_allocator.cc:102] Free pointer=0x7fa7c489f040 on CPUPlace
I0224 10:26:18.066510  3303 buddy_allocator.cc:107] Free from address 0x7fa7c489f000
I0224 10:26:18.066524  3303 meta_cache.cc:38] Load MemoryBlock::Desc type=1
I0224 10:26:18.066534  3303 meta_cache.cc:38] Load MemoryBlock::Desc type=1
I0224 10:26:18.066541  3303 meta_cache.cc:38] Load MemoryBlock::Desc type=0
I0224 10:26:18.066550  3303 buddy_allocator.cc:128] Merging this block 0x7fa7c489f000 with its right buddy 0x7fa7c48a0000
I0224 10:26:18.066561  3303 meta_cache.cc:38] Load MemoryBlock::Desc type=0
I0224 10:26:18.066570  3303 meta_cache.cc:38] Load MemoryBlock::Desc type=0
I0224 10:26:18.066593  3303 meta_cache.cc:38] Load MemoryBlock::Desc type=0
I0224 10:26:18.066604  3303 meta_cache.cc:38] Load MemoryBlock::Desc type=0
I0224 10:26:18.066612  3303 buddy_allocator.cc:145] Merging this block 0x7fa7c489f000 with its left buddy 0x7fa7c489e000
I0224 10:26:18.066620  3303 meta_cache.cc:38] Load MemoryBlock::Desc type=1
I0224 10:26:18.066632  3303 buddy_allocator.cc:163] Inserting free block (0x7fa7c489f000, 462249984)
I0224 10:26:18.066643  3303 naive_best_fit_allocator.cc:102] Free pointer=0x7fa7c489e040 on CPUPlace
I0224 10:26:18.066651  3303 buddy_allocator.cc:107] Free from address 0x7fa7c489e000
I0224 10:26:18.066659  3303 meta_cache.cc:38] Load MemoryBlock::Desc type=1
I0224 10:26:18.066668  3303 meta_cache.cc:38] Load MemoryBlock::Desc type=1
I0224 10:26:18.066679  3303 meta_cache.cc:38] Load MemoryBlock::Desc type=0
I0224 10:26:18.066694  3303 buddy_allocator.cc:128] Merging this block 0x7fa7c489e000 with its right buddy 0x7fa7c489f000
I0224 10:26:18.066704  3303 meta_cache.cc:38] Load MemoryBlock::Desc type=0
I0224 10:26:18.066712  3303 meta_cache.cc:38] Load MemoryBlock::Desc type=0
I0224 10:26:18.066720  3303 meta_cache.cc:38] Load MemoryBlock::Desc type=0
I0224 10:26:18.066746  3303 meta_cache.cc:38] Load MemoryBlock::Desc type=0
I0224 10:26:18.066754  3303 buddy_allocator.cc:145] Merging this block 0x7fa7c489e000 with its left buddy 0x7fa7c489d000
I0224 10:26:18.066763  3303 meta_cache.cc:38] Load MemoryBlock::Desc type=1
I0224 10:26:18.066772  3303 buddy_allocator.cc:163] Inserting free block (0x7fa7c489e000, 462254080)
I0224 10:26:18.066849  3303 auto_growth_best_fit_allocator.cc:144] Free chunk with size 37888
terminate called after throwing an instance of 'paddle::platform::EnforceNotMet'
  what():  (External)  Cuda error(700), an illegal memory access was encountered.
  [Advise: Please search for the error code(700) on website( https://docs.nvidia.com/cuda/archive/10.0/cuda-runtime-api/group__CUDART__TYPES.html#group__CUDART__TYPES_1g3f51e3575c2178246db0a94a430e0038 ) to get Nvidia's official solution about CUDA Error.] (at /paddle/paddle/fluid/platform/gpu_info.cc:553)



--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
0   paddle::AnalysisPredictor::~AnalysisPredictor()
1   paddle::AnalysisPredictor::~AnalysisPredictor()
2   paddle::memory::allocation::AutoGrowthBestFitAllocator::FreeIdleChunks()
3   paddle::memory::allocation::AlignedAllocation::~AlignedAllocation()
4   paddle::memory::allocation::CUDAAllocator::FreeImpl(paddle::memory::allocation::Allocation*)
5   paddle::platform::RecordedCudaFree(void*, unsigned long, int)
6   paddle::framework::SignalHandle(char const*, int)
7   paddle::platform::GetCurrentTraceBackString[abi:cxx11]()

----------------------
Error Message Summary:
----------------------
FatalError: `Process abort signal` is detected by the operating system.
  [TimeInfo: *** Aborted at 1645669578 (unix time) try "date -d @1645669578" if you are using GNU date ***]
  [SignalInfo: *** SIGABRT (@0xce7) received by PID 3303 (TID 0x7fa8d9fbc740) from PID 3303 ***]

**Comment by Xingyu-Romantic** [comment]
@Superjomn

**Comment by TinyQi** [comment]
同问该问题，+在批量推理的时候出现了该问题。从多次测试结果来看都是发生在最后一张，是不是释放与predictor对象的时候出问题了
