### ISSUE TITLE
获取路径失败

### ISSUE THREAD

**Issue by yqxqls** [PaddlePaddle/Paddle#3220]
如图
![image](https://user-images.githubusercontent.com/26181201/28947682-c252523a-78e3-11e7-8eac-c38a3d61e7d5.png)

**Comment by hedaoyuan** [comment]
Follow https://stackoverflow.com/questions/16771894/python-nameerror-global-name-file-is-not-defined.
Try to modified to `os.path.realpath('__file__')`.

**Comment by typhoonzero** [comment]
I'm closing this due to low activity, feel free to reopen.
