### ISSUE TITLE
编译出错：jetson nano编译带有tensorrt的paddle-gpu

### ISSUE THREAD

**Issue by GZHUZhao** [PaddlePaddle/Paddle#32237]
cmake命令：
sudo cmake ..  \
-DWITH_CONTRIB=OFF \
 -DWITH_MKL=OFF \
 -DWITH_MKLDNN=OFF \
 -DWITH_TESTING=OFF \
 -DCMAKE_BUILD_TYPE=Release  \
 -DON_INFER=ON  \
-DWITH_PYTHON=ON \
 -DWITH_XBYAK=OFF \
 -DWITH_NV_JETSON=ON \
 -DPY_VERSION=3.6 \
-DCUDA_ARCH_NAME=Auto \
-TENSORRT_ROOT=/usr/src/tensorrt

硬件：jetson nano jetpack4.3
paddlepaddle-gpu2.0-rc1

![trt](https://user-images.githubusercontent.com/78419361/114520136-b2363080-9c73-11eb-9916-4ad83f78594b.png)

**Comment by wangye707** [comment]
那个是-DTENSORRT_ROOT，你少个D，你改成这样cmake ..   -DWITH_CONTRIB=OFF   -DWITH_MKL=OFF    -DWITH_MKLDNN=OFF   -DWITH_TESTING=OFF   -DCMAKE_BUILD_TYPE=Release   -DON_INFER=ON   -DWITH_PYTHON=ON -DPY_VERSION=3.6  -DWITH_XBYAK=OFF  -DWITH_NV_JETSON=ON -DWITH_TENSORRT=ON -DTENSORRT_ROOT=/usr -DCMAKE_CUDA_COMPILER=/usr/local/cuda-10.0/bin/nvcc  -DWITH_NCCL=OFF -DCUDA_ARCH_NAME=All

**Comment by GZHUZhao** [comment]
> 那个是-DTENSORRT_ROOT，你少个D，你改成这样cmake .. -DWITH_CONTRIB=OFF -DWITH_MKL=OFF -DWITH_MKLDNN=OFF -DWITH_TESTING=OFF -DCMAKE_BUILD_TYPE=Release -DON_INFER=ON -DWITH_PYTHON=ON -DPY_VERSION=3.6 -DWITH_XBYAK=OFF -DWITH_NV_JETSON=ON -DWITH_TENSORRT=ON -DTENSORRT_ROOT=/usr -DCMAKE_CUDA_COMPILER=/usr/local/cuda-10.0/bin/nvcc -DWITH_NCCL=OFF -DCUDA_ARCH_NAME=All

谢谢您的解答！
