### ISSUE TITLE
训练过程中有时会突增显存，一定步之后 OOM

### ISSUE THREAD

**Issue by ShaneTian** [PaddlePaddle/Paddle#32234]
- 版本、环境信息：
    1）PaddlePaddle版本：2.0.1
    2）CPU：N/A
    3）GPU：V100 32G 4 cards
    4）系统环境：Python 3.7
- 训练信息
    1）单机，4卡
    2）32G 每卡
- 问题描述：如图，在训练到第  300 步到 400 步的过程中，其中一张卡 OOM。但是在任务最开始，显存是完全够用的，而且在监控显存的过程中，没有发现显存的连续增长，而是隔一段时间突增的，没有明显规律。考虑是否为某个地方出现了泄露？
![image](https://user-images.githubusercontent.com/42370681/114509391-05a28180-9c68-11eb-9080-a4555d237b92.png)

**Comment by seiriosPlus** [comment]
你好，能提供下复现的demo吗？ 目前这些信息无法定位到具体问题.
