### ISSUE TITLE
【论文复现】torch的SGD中的momentum_buffer参数对应关系

### ISSUE THREAD

**Issue by GuoQuanhao** [PaddlePaddle/Paddle#32256]
paltform : AIStudio
version: 2.0.1
```python
optimizer.state[self.sub_weight]['momentum_buffer'] = self.sub_weight_mom
```
torch中的SGD具有momentum参数，并且其具有momentum_buffer，paddle优化器只有Momentum具有momentum参数，paddle中利用`dir(opt_pfc)`查询如下：
```python
module_partial_fc = PartialFC(
        rank=rank, resume=0,
        batch_size=cfg.batch_size, margin_softmax=margin_softmax, num_classes=cfg.num_classes,
        sample_rate=cfg.sample_rate, embedding_size=cfg.embedding_size, prefix=cfg.output)
opt_pfc = paddle.optimizer.Momentum(parameters=module_partial_fc.parameters(), learning_rate=0.1, momentum=0.9)
dir(opt_pfc)
```
```
['__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_accumulators',
 '_accumulators_holder',
 '_add_accumulator',
 '_append_dgc_ops',
 '_append_optimize_op',
 '_apply_optimize',
 '_create_accumulators',
 '_create_global_learning_rate',
 '_create_master_weight',
 '_create_optimization_pass',
 '_create_param_lr',
 '_dtype',
 '_finish_update',
 '_get_accumulator',
 '_get_device_for_param',
 '_get_no_grad_set',
 '_global_learning_rate',
 '_grad_clip',
 '_learning_rate',
 '_learning_rate_map',
 '_master_weights',
 '_momentum',
 '_multi_precision',
 '_name',
 '_opti_name_list',
 '_param_device_map',
 '_parameter_list',
 '_regularization_coeff',
 '_regularization_method',
 '_rescale_grad',
 '_update_param_device_map',
 '_use_nesterov',
 '_velocity_acc_str',
 'apply_gradients',
 'backward',
 'clear_grad',
 'clear_gradients',
 'get_lr',
 'get_opti_var_name_list',
 'helper',
 'minimize',
 'regularization',
 'set_lr',
 'set_state_dict',
 'state_dict',
 'step',
 'type']
```
我想知道`_accumulators`的作用，它对应于torch中的`momentum_buffer`吗

**Comment by MrChengmo** [comment]
> paltform : AIStudio
> version: 2.0.1
> 
> ```python
> optimizer.state[self.sub_weight]['momentum_buffer'] = self.sub_weight_mom
> ```
> 
> torch中的SGD具有momentum参数，并且其具有momentum_buffer，paddle优化器只有Momentum具有momentum参数，paddle中利用`dir(opt_pfc)`查询如下：
> 
> ```python
> module_partial_fc = PartialFC(
>         rank=rank, resume=0,
>         batch_size=cfg.batch_size, margin_softmax=margin_softmax, num_classes=cfg.num_classes,
>         sample_rate=cfg.sample_rate, embedding_size=cfg.embedding_size, prefix=cfg.output)
> opt_pfc = paddle.optimizer.Momentum(parameters=module_partial_fc.parameters(), learning_rate=0.1, momentum=0.9)
> dir(opt_pfc)
> ```
> 
> ```
> ['__class__',
>  '__delattr__',
>  '__dict__',
>  '__dir__',
>  '__doc__',
>  '__eq__',
>  '__format__',
>  '__ge__',
>  '__getattribute__',
>  '__gt__',
>  '__hash__',
>  '__init__',
>  '__init_subclass__',
>  '__le__',
>  '__lt__',
>  '__module__',
>  '__ne__',
>  '__new__',
>  '__reduce__',
>  '__reduce_ex__',
>  '__repr__',
>  '__setattr__',
>  '__sizeof__',
>  '__str__',
>  '__subclasshook__',
>  '__weakref__',
>  '_accumulators',
>  '_accumulators_holder',
>  '_add_accumulator',
>  '_append_dgc_ops',
>  '_append_optimize_op',
>  '_apply_optimize',
>  '_create_accumulators',
>  '_create_global_learning_rate',
>  '_create_master_weight',
>  '_create_optimization_pass',
>  '_create_param_lr',
>  '_dtype',
>  '_finish_update',
>  '_get_accumulator',
>  '_get_device_for_param',
>  '_get_no_grad_set',
>  '_global_learning_rate',
>  '_grad_clip',
>  '_learning_rate',
>  '_learning_rate_map',
>  '_master_weights',
>  '_momentum',
>  '_multi_precision',
>  '_name',
>  '_opti_name_list',
>  '_param_device_map',
>  '_parameter_list',
>  '_regularization_coeff',
>  '_regularization_method',
>  '_rescale_grad',
>  '_update_param_device_map',
>  '_use_nesterov',
>  '_velocity_acc_str',
>  'apply_gradients',
>  'backward',
>  'clear_grad',
>  'clear_gradients',
>  'get_lr',
>  'get_opti_var_name_list',
>  'helper',
>  'minimize',
>  'regularization',
>  'set_lr',
>  'set_state_dict',
>  'state_dict',
>  'step',
>  'type']
> ```
> 
> 我想知道`_accumulators`的作用，它对应于torch中的`momentum_buffer`吗

_accumulators 与 momentum_buffer 没有关系，_accumulators是用于训练加速的配置选项，与FP16训练相关，在源码中，是这样提现的：

```
def _create_accumulators(self, block, parameters):
        assert isinstance(block, framework.Block)

        for p in parameters:
            if self._multi_precision and p.dtype == core.VarDesc.VarType.FP16:
                master_p = self._create_master_weight(p)
                self._add_accumulator(self._velocity_acc_str, master_p)
                continue
            if p.dtype == core.VarDesc.VarType.FP16 and not self._multi_precision:
                warnings.warn(
                    "Accumulating with FP16 in optimizer can lead to poor accuracy or slow convergence."
                    "Consider using multi_precision=True option of the Momentum optimizer."
                )
            self._add_accumulator(self._velocity_acc_str, p)
```

**Comment by GuoQuanhao** [comment]
那有与momentum_buffer对应的参数吗

**Comment by MrChengmo** [comment]
> 那有与momentum_buffer对应的参数吗

目前还没有与momentum_buffer对应的可配参数
