### ISSUE TITLE
Lod-tensor有按照shape的reduce_sum方法吗

### ISSUE THREAD

**Issue by qiaofeiw** [PaddlePaddle/Paddle#32268]
例如
lod = [0.2,0.4,0.6,0.1,0.4,0.3]
shape = [[3,1,2]]
reduce_sum = [1.2, 0.1, 0.7]

**Comment by jerrywgz** [comment]
如果是reduce sum的话可以尝试先使用sequence_pad https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/fluid/layers/sequence_pad_cn.html  将每个batch pad到相同纬度，然后可以做reshape + reduce_sum

**Comment by qiaofeiw** [comment]
nice

**Comment by qiaofeiw** [comment]
> 如果是reduce sum的话可以尝试先使用sequence_pad https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/fluid/layers/sequence_pad_cn.html 将每个batch pad到相同纬度，然后可以做reshape + reduce_sum

![image](https://user-images.githubusercontent.com/2361236/114703759-4974b400-9d58-11eb-8ab7-630da9da1c83.png)
![image](https://user-images.githubusercontent.com/2361236/114703803-5d201a80-9d58-11eb-8a05-dfc0926cc73e.png)
