### ISSUE TITLE
您好，我从官网拉取了1.85的镜像，创建完docker以后，运行检查GPU会卡死。

### ISSUE THREAD

**Issue by zcswdt** [PaddlePaddle/Paddle#32269]
![image](https://user-images.githubusercontent.com/43515926/114677029-7c10b380-9d3c-11eb-9751-c93cd4ddf3a3.png)

**Comment by jerrywgz** [comment]
https://www.paddlepaddle.org.cn/documentation/docs/zh/1.8/install/docker/docker.html#anzhuangbuzhou 可以确认下docker镜像是否是从上面的文档中下载的

**Comment by zcswdt** [comment]
> https://www.paddlepaddle.org.cn/documentation/docs/zh/1.8/install/docker/docker.html#anzhuangbuzhou 可以确认下docker镜像是否是从上面的文档中下载的

我的镜像下载命令是`docker pull hub.baidubce.com/paddlepaddle/paddle:1.8.5-gpu-cuda10.0-cudnn7`，和您提供的文档下载别无二致。请问这是什么原因造成的嗯？

**Comment by pangyoki** [comment]
请使用`nvidia-smi`看下相关信息。目前paddle还不支持3090等显卡，请问下您的显卡型号？

**Comment by zcswdt** [comment]
> 请使用`nvidia-smi`看下相关信息。目前paddle还不支持3090等显卡，请问下您的显卡型号？

谢谢回复，我的显卡是T4的，很纳闷
![image](https://user-images.githubusercontent.com/43515926/114685837-cb5ae200-9d44-11eb-94c0-b7604912f0f5.png)

**Comment by jerrywgz** [comment]
看你这边是cuda10.2的版本，可以拉下cuda10.2的镜像看看

**Comment by zcswdt** [comment]
> 看你这边是cuda10.2的版本，可以拉下cuda10.2的镜像看看

已经解决，是要启容器的加上--shm这个参数，好奇怪
