### ISSUE TITLE
[oneDNN] More ops need oneDNN  enabling

### ISSUE THREAD

**Issue by lidanqing-vv** [PaddlePaddle/Paddle#32282]
**Will the performance be influenced or not depends on if the blocked format are used. If there is no blocked format used, then there should not be reorder, the performance drop maybe other reasons.**

**We need to check the models first to decide if there is benefit to enable these ops.**

# 说明

由于模型中有op支持mkldnn，有的op不支持mkldnn，导致需要数据reorder转换，影响模型性能。

下面统计了一些常见模型中不支持mkldnn的op，统计方法比较简单，是基于未优化fuse的模型结构，所以结果可能不准确，仅做参考。

下面统计结果的格式是 ”op名字【模型中该op出现的次数】“。

请丹青安排同学基于我们统计的初步结果：

1）分析mkldnn库已经支持的op，后续可以直接在paddle中集成这些op

2）分析mkldnn库不支持的op，需要首先同步mkldnn团队进行开发支持，然后在paddle中集成这些op

# OCR 模型中MKLDNN不支持的op

- [x]  elementwise_add 【65】
- [x] nearest_interp_v2 【6】
- [x] elementwise_mul 【9】
- [x] squeeze2 【2】
- [ ] rnn 【2】

# Clas 模型中MKLDNN不支持的op

- [x] elementwise_add【463】
- [x] split【90】
- [x] elementwise_mul【45】
- [x] reshape2【28】
- [x] squeeze2【11】
- [x] flatten_contiguous_range【6】
- [x] slice【5】

# Det（只测试了Yolo） 模型中MKLDNN不支持的op
- [x] elementwise_add 【38】
- [x] expand_v2 【32】
- [x] elementwise_mul 【8】
- [x] nearest_interp_v2 【10】
- [ ] yolo_box 【10】
- [x] split 【3】
- [x] reshape2 【3】
- [x] slice 【9】
- [x] scale 【3】

# 汇总MKLDNN不支持的op

- [x] elementwise_add 【65】+ elementwise_add【463】+ elementwise_add 【38】
- [x] nearest_interp_v2 【6】+ nearest_interp_v2 【10】doable
- [x] elementwise_mul 【9】+ elementwise_mul【45】+ elementwise_mul 【8】
- [ ] squeeze2 【2】+ squeeze2【11】 doable
- [ ] rnn 【2】Need to look into doc
- [x] split【90】+ split 【3】Need investigation. 
- [ ] reshape2【28】+ reshape2 【3】It does not make sense to make for oneDNN. it does not work with block format. It only make sense to make oneDNN support when block format is supported
- [x] flatten_contiguous_range【6】
- [x] slice【5】+ slice 【9】
- [x] expand_v2 【32】
- [ ] yolo_box 【10】
- [x] scale 【3】Need investigation.

**Comment by juncaipeng** [comment]
@lidanqing-intel  The new Mobilenetv3 model in (Link:https://dubox.com/s/1KqlagBkwPJssm2HPIfnbLw Password:unxr).

For Mobilenetv3,  there are some naive kernels and MKLDNN kernels:

```
Naive kernels:
fc (1)
flatten_contiguous_range (1)
hard_sigmoid (8)
scale (1)


MKLDNN kernels:
conv2d (64)
elementwise_mul (8)
pool2d (9)
softmax (1)
```

**Comment by juncaipeng** [comment]
The results of the latest analysis are as follows：

![image](https://user-images.githubusercontent.com/52520497/119756266-e38e5700-bed5-11eb-97be-51980cbbe70a.png)
![image](https://user-images.githubusercontent.com/52520497/119756301-ef7a1900-bed5-11eb-8860-47e03bdf2a34.png)
![image](https://user-images.githubusercontent.com/52520497/119756325-f9038100-bed5-11eb-9203-564e2942287b.png)

**Comment by lidanqing-vv** [comment]
**Note:**
- fusion_rnn_mkldnn_op.cc exists, but it is only for code refactoring of GRU and LSTM. real vanillia rnn is not supported yet.
- fc_mkldnn_op is implemented but by default disabled in pass. Since fc oneDNN for some models caused perf drop. Need to enable it by adding AppendPass("fc_mkldnn_pass")

**Comment by jakpiase** [comment]
Flatten op is doable and will be done when reshape and squeeze will be re-enabled(after adding memory descriptor to tensor)

**Comment by lidanqing-vv** [comment]
Paddle model zoo FP32/BF16/INT8 MKLDNN Generalization
Need Baidu's input: models priority, business value, real business
Intel execution: Intel do Feasibility Analysis, planed delivery date and then Implementation.

### PaddleClas
* Download link (static picture + dynamic and static) ：https://sys-p0.bj.bcebos.com/Paddle-UnitTestModel/PaddleClas.tgz
* Static+dygraph models including following models. Currently crashing models are `SE_ResNeXt50_vd_32x4d`
```
AlexNet DPN68 GoogLeNet MobileNetV1 RegNetX_4GF ResNet50
ShuffleNetV2 Xception41
DarkNet53 EfficientNetB0 HRNet_W18_C MobileNetV2 Res2Net50_26w_4s
ResNet50_vd SqueezeNet1_0
DenseNet121 GhostNet_x1_3 InceptionV4 MobileNetV3_large_x1_0 ResNeSt50_fast_1s1x64d
SE_ResNeXt50_vd_32x4d VGG11
```

### PaddleDetection
* models link： https://sys-p0.bj.bcebos.com/Paddle-UnitTestModel/PaddleDetection.tgz
* Currently including following models，all fine. 
```
faster_rcnn_dcn_r50_vd_fpn_3x_server_side ppyolo_mobilenet_v3_large ssd_mobilenet_v1_voc
yolov3_r50vd_dcn
faster_rcnn_r50_1x solov2_r50_fpn_1x yolov3_darknet
yolov4_cspdarknet
mask_rcnn_r50_1x ssdlite_mobilenet_v3_large yolov3_mobilenet_v3
```

### PaddleSeg 
* models link： https://sys-p0.bj.bcebos.com/Paddle-UnitTest-Model/PaddleSeg.tgz
* Including following models. Currently unfixed issues are `fastscnn, hrnet, pspnet`
```
deeplabv3p fastscnn hrnet icnet pspnet unet
```

### PaddleOCR
* models link： https://sys-p0.bj.bcebos.com/Paddle-UnitTest-Model/PaddleOCR.tgz
* Currently including following models，all fine. Continuously adding more ocr models from ocr repo
```
ch_ppocr_mobile_v1.1_cls_infer ch_ppocr_mobile_v1.1_det_infer ch_ppocr_mobile_v1.1_rec_infer
```

### Paddle competitor testing models：
* models link https://sys-p0.bj.bcebos.com/infer_benchmark/PaddleModel.tgz
* Currently including following models，all fine
```
bert_emb_v1-paddle faster_rcnn_r50_1x-paddle mobilenet_v2-paddle unet-paddle
X2paddle_mobilenetv2
deeplabv3p_xception_769_fp32-paddle mobilenet_ssd-paddle resnet101-paddle
X2paddle_mobilenetv1 X2paddle_resnet50
```

**Comment by baoachun** [comment]
**PaddleDetection models are sorted by priority from high to low as follows:**

- ppyolov2_r50vd_dcn_365e_coco, 
- yolov3_darknet, 
- faster_rcnn_r50_fpn_1x_coco, 
- mask_rcnn_r50_fpn_1x_coco, 
- ssd_mobilenet_v1_300_120e_voc, 
- solov2_r50_fpn_1x_coco,

**Comment by lidanqing-vv** [comment]
Hi, @baoachun  Thank you very much! 
@jczaja @wozna @jakpiase

**Comment by jakpiase** [comment]
Hi @baoachun, there are multiple "yolov3_darknet" models in PaddleDetection. Could you please tell me which one should we focus on?
- PaddleDetection/configs/yolov3/yolov3_darknet53_270e_coco.yml
- PaddleDetection/configs/yolov3/yolov3_darknet53_270e_voc.yml
- PaddleDetection/configs/yolov3/yolov3_darknet53_original_270e_coco.yml

**Comment by lidanqing-vv** [comment]
@jakpiase coco and voc are two different dataset for object detection tasks, that means the data loader will differ. From the name it does not show real difference of model, maybe check model graph or do profiling ?

**Comment by lidanqing-vv** [comment]
Moved to new issue "oneDNN int8 ops generation" #37005

**Comment by lidanqing-vv** [comment]
Need to add bicubic_interp , etc fp32 oneDNN support oneDNN support. Not necessarily in Q4, long term work.
For video detection model (I haven't get model yet), only op lists
- [ ]   bicubic_interp 
- [ ]   pixel_shuffle
- [ ]   fill_constant
- [ ]   while_loop
- [ ]   range
- [ ]   grid_sampler
- [ ]   zeros_like

**Comment by jakpiase** [comment]
@lidanqing-intel I have done some of these ops for the video detection model a few days ago, but I need a model to check the performance. Please let me know as soon as you will know one
