### ISSUE TITLE
图像捕捉设备部署安装问题

### ISSUE THREAD

**Issue by gaogaoxingxing2010** [PaddlePaddle/Paddle#32295]
您好！
图像分类中，针对厂房视频捕捉设备安装部署有以下疑问
顶棚高度4米，作业范围面积11*10米，范围面积内三个长方形工作台，其长11*宽1.5*高1.2米。识别目标不超出工作台。目前仅支持usb摄像头设备。

采用屋顶部署摄像头采集和支架（高2米）部署摄像头采集图像两种方案，如果采用支架采集图像对后期会造成影响吗？是否可行呢？感谢！

**Comment by weisy11** [comment]
具体生产场景中的问题，我们恐怕没法做特别精准的回答，很多问题受限于现场的实际条件和您选择的设备情况，仅提供一些建议供参考。如果您的支架架在工作区域的一侧，并且摄像头不能转动和调焦，那么距离近的物体与距离较远的，大小会相差很多，也会由于透视效应产生变形，效果可能不如顶棚架设。如果有条件，您可以在固定架设设备之前尝试拍摄一些样张图片，进行初步的测试。

**Comment by gaogaoxingxing2010** [comment]
![mmexport1618480978818](https://user-images.githubusercontent.com/62227361/114851936-e5fc8c00-9e14-11eb-9b8a-6a23a41dc1ab.jpg)
补充下信息，我想识别下上图中场景中材料是否已揭膜(材料只有一种颜色，膜有有限几种颜色），也就是确定下该识别是图像分类的范畴吗？
最后还是那个问题，支架采集图像会对后续有影响吗？

**Comment by yzl19940819** [comment]
@gaogaoxingxing2010 您好，我这边是PaddleClas的产品经理：余志良。方便加一下微信，我们具体看一下这个问题场景  17854262968
