### ISSUE TITLE
请问fit方法中第一个参数必须是Dataset或者Dataloader吗？

### ISSUE THREAD

**Issue by wangyexiang** [PaddlePaddle/Paddle#32308]
- 版本、环境信息：
    1）PaddlePaddle版本：2.0.1
    2）CPU：i7
    3）系统环境：win10
 
请问一下，fit方法中，第一个参数必须是Dataset或者Dataloader吗？
是这样的，假如要做多元非线性回归问题(实际上，也不一定是回归问题，其他小数据集也一样)，数据来自csv或者txt等文件中，数据量不大，如果直接从文件中读取数据，然后喂入模型中，不用转换为Dataset或者Dataloader，这样不是更简单吗？
[我记得之前用tensorflow的时候，它的fit方法中可以喂入多维np数组也可以直接喂入generator可迭代对象[https://tensorflow.google.cn/api_docs/python/tf/keras/Sequential?hl=zh_cn](url)。我在网上搜索了一下，好像paddle的fit方法不能直接喂入多维数组，要转换为Dataset或者Dataloader才行，如果是这样的话，那也太不灵活了。]
最后，麻烦解答一下。多谢。

**Comment by heavengate** [comment]
是的，多维数据支持我们评估一下

**Comment by wangyexiang** [comment]
> 是的，多维数据支持我们评估一下

哦，感觉还是挺有必要的。祝paddle越来越好。
