### ISSUE TITLE
YOLOv3 ResNet50_vd DCN模型C++服务端测试数据异常

### ISSUE THREAD

**Issue by thzyyx** [PaddlePaddle/Paddle#32307]
- 版本、环境信息：
    1）PaddlePaddle版本：2.0.1发布板
    2）CPU：使用https://www.paddlepaddle.org.cn/documentation/docs/zh/guides/05_inference_deployment/inference/build_and_install_lib_cn.html链接中下载的ubuntu14.04_cuda11_cudnn8_avx_mkl_trt7_gcc82（预测库(2.0.2版本)）自带的数学库
    3）GPU：P4卡，cudnn-8.0, cuda11, TensorRT7.2.2.3
    4）系统环境：gcc version 7.5.0 (Ubuntu 7.5.0-3ubuntu1~18.04)
-预测信息
    1）C++预测：使用已经编译好的离线包
     https://www.paddlepaddle.org.cn/documentation/docs/zh/guides/05_inference_deployment/inference/build_and_install_lib_cn.html
ubuntu14.04_cuda11_cudnn8_avx_mkl_trt7_gcc82（预测库(2.0.2版本)）
    2）使用测试demo为PaddleDetection-release-2.0-rc/deploy/cpp
    3)  cmake参数信息
             WITH_GPU=ON
             WITH_MKL=ON
             USE_PADDLE_20RC1=OFF(打开或关闭对结果无影响)
             WITH_STATIC_LIB=OFF
             其余路径信息均按照系统中位置填写
       说明：1.opencv自动下载的无法正常编译通过，通过apt-get 安装opencv4，手动修改cmakelist文件通过编译
                  2.原始cmake文件中会引用fluid_inference库，会导致错误（下载包中没），手动修改为paddle_inferenc库
  -具体错误描述
   第一步：在官方网站（https://www.paddlepaddle.org.cn/modelbasedetail/yolov3）下载了YOLOv3 ResNet50_vd DCN模型
   第二步：使用tools/export_model.py导出模型
   第三步：编译cpp下的测试demo，执行./build/main 测试benchmark
测试结果：耗时60ms，这比官方的给的P4平台上的35.2ms都慢，请具体告知异常原因。
```
root@1aeca2c06129:/data/tianhz/PaddleDetection-release-2.0-rc/deploy/cpp# ./build/main --model_dir=/data/tianhz/PaddleDetection-release-2.0-rc/output1/yolov3_r50vd_dcn_db_iouloss_obj365_pretrained_coco --image_path=/data/tianhz/000000000139.jpg  --use_gpu=1  --run_benchmark=1
WARNING: Logging before InitGoogleLogging() is written to STDERR
W0415 20:48:03.580025 29627 analysis_predictor.cc:1145] Deprecated. Please use CreatePredictor instead.
Inference: 61.850891 ms per batch image
root@1aeca2c06129:/data/tianhz/PaddleDetection-release-2.0-rc/deploy/cpp# 
```

补充：增加--run_mode=trt_fp32参数后，测试数据为28.6ms，虽然初步达到预期，但是与P4平台上的加速比差别较大，请分析下这组数据是否合理：
P4平台：原始数据/tensorRT-FP32 74.4/35.2 = 2.11
T4平台：原始数据/tensorRT-FP32 39.5/28.6 = 1.38
T平台上fluid模式60ms，trt_fp32模式下28.6毫秒
问题：
  1. fluid模式比原始模型慢是什么原因？
  2. trt_fp32模式是不是调用TensorRT的模式？

**Comment by thzyyx** [comment]
补充：增加--run_mode=trt_fp32参数后，测试数据为28.6ms，虽然初步达到预期，但是与P4平台上的加速比差别较大，请分析下这组数据是否合理：
P4平台：原始数据/tensorRT-FP32    74.4/35.2 = 2.11
T4平台：原始数据/tensorRT-FP32    39.5/28.6 = 1.38

**Comment by frankwhzhang** [comment]
可以在https://github.com/PaddlePaddle/PaddleDetection 这里提问

**Comment by thzyyx** [comment]
好的
