### ISSUE TITLE
不能从paddle.callbacks 导入EarlyStopping。

### ISSUE THREAD

**Issue by wangyexiang** [PaddlePaddle/Paddle#32315]
- 版本、环境信息：
    1）PaddlePaddle版本：2.0.2
    2）CPU：i7-cpu
    3）系统环境：win10
    4)python版本：python3.8.6
 执行下面代码：
`from paddle.callbacks import EarlyStopping`
报错：
`ModuleNotFoundError: No module named 'paddle.callbacks'`

但是能够这样使用：
```
import paddle
callbacks=paddle.callbacks.EarlyStopping(...)
```
请问一下，这是什么原因？

**Comment by heavengate** [comment]
需要先`import paddle` 之后再做`from paddle.callbacks import EarlyStopping`

**Comment by wangyexiang** [comment]
> 需要先`import paddle` 之后再做`from paddle.callbacks import EarlyStopping`

明白了，好像其他有几个模块也是这样的。感谢解答。
