### ISSUE TITLE
propeller的作用和功能是什么,有propeller的参考资料吗？

### ISSUE THREAD

**Issue by dickobe** [PaddlePaddle/Paddle#32310]
1、propeller的作用和功能是什么样的?有相关的使用说明吗
2、ernie动态图训练保存模型保存的是.pbparams的格式，这个和checkpoint模型有什么区别，或者说动态图如何保存称为checkpoint格式的模型？

**Comment by Meiyim** [comment]
propeller主要是辅助ERNIE完成训练的一个高级训练框架，主要是服务于paddle静态图组网模型的，类似tensorlfow.estimator。相关的文档建设不是很充分，目前只能依赖代码中的注释。

**Comment by dickobe** [comment]
> propeller主要是辅助ERNIE完成训练的一个高级训练框架，主要是服务于paddle静态图组网模型的，类似tensorlfow.estimator。相关的文档建设不是很充分，目前只能依赖代码中的注释。
@Meiyim  再帮看下这个问题：
ernie动态图训练保存模型保存的是.pbparams的格式，这个和checkpoint模型有什么区别，或者说动态图如何保存称为checkpoint格式的模型？

**Comment by Meiyim** [comment]
checkpoint 为老式paddle的存储格式，目前动态图无法存储为checkpoint
