### ISSUE TITLE
yolov3 使用自己的训练模型预测输出为0

### ISSUE THREAD

**Issue by jiamingming-004** [PaddlePaddle/Paddle#32326]
在Jeston TX2 中部署yolov3,使用自己训练的模型，版本为1.8，在AIstudio中用训练的模型预测，有结果。将其放到Jeston TX2中进行部署，调用模型进行预测的时候（版本为2.02），并没有结果，输出为0的一些矩阵，请问可能会是哪里的原因，这中错误，与版本有没有关系。

**Comment by shangzhizhou** [comment]
请提供模型及单元测试的代码、测试的输入，我们同学看下。

**Comment by jiamingming-004** [comment]
> 请提供模型及单元测试的代码、测试的输入，我们同学看下。
> 
> Please provide the model and unit test code, test input, our students look at.

项目“Jeston预测部署”共享链接(有效期三天)：https://aistudio.baidu.com/studio/project/partial/verify/1827046/9145ffb784004dafb2dad18218b9ff29

完整内容在里面，您可以看看，如果打不开，请联系我，谢谢

**Comment by shangzhizhou** [comment]
您好，内部问了一下，这个是已知问题，目前yolov3在nano和tx2上使用GPU推理结果不正确，CPU上可以。
另外，在NX和AGX是可以正常推理的。
此问题我们会在后续的版本迭代中，视人力情况进行排查和修复。

**Comment by jiamingming-004** [comment]
> 您好，内部问了一下，这个是已知问题，目前yolov3在nano和tx2上使用GPU推理结果不正确，CPU上可以。
> 另外，在NX和AGX是可以正常推理的。
> 

你好，本次的问题，我目前在AIstudio 中运行，出现这种情况，希望你可以给点解答

**Comment by shangzhizhou** [comment]
看您的问题，是在aistudio的环境可以正常运行，但是在tx2上无法正常运行，对么？

**Comment by jiamingming-004** [comment]
我的问题在于，在aistudio中，预测是可以的，但在Aistudio 中使用部署预测代码预测时，预测为0的数组，



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Shang ***@***.***&gt;; 
发送时间: 2021年4月19日(星期一) 下午5:26
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [PaddlePaddle/Paddle] yolov3 使用自己的训练模型预测输出为0 (#32326)





 
看您的问题，是在aistudio的环境可以正常运行，但是在tx2上无法正常运行，对么？

**Comment by jiamingming-004** [comment]
> 看您的问题，是在aistudio的环境可以正常运行，但是在tx2上无法正常运行，对么？

我想将它在Aistudio中做出来之后，在放入JestonTx2上运行文件，
目前，使用官方给的yolov3模型,在Aistudio中也是可以运行出结果的，但换了自己的模型就不可以了。找不到原因，希望可以给些建议 。

**Comment by jiamingming-004** [comment]
可以留个联系方式嘛，方便请教一下




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Shang ***@***.***&gt;; 
发送时间: 2021年4月19日(星期一) 下午5:26
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [PaddlePaddle/Paddle] yolov3 使用自己的训练模型预测输出为0 (#32326)





 
看您的问题，是在aistudio的环境可以正常运行，但是在tx2上无法正常运行，对么？

**Comment by shangzhizhou** [comment]
目前的阶段是跟tx2没关系，在aistudio里换了模型就结果不正确对么
可以加入paddle推理部署QQ群959308808，方便沟通。

> > 看您的问题，是在aistudio的环境可以正常运行，但是在tx2上无法正常运行，对么？
> 
> 我想将它在Aistudio中做出来之后，在放入JestonTx2上运行文件，
> 目前，使用官方给的yolov3模型,在Aistudio中也是可以运行出结果的，但换了自己的模型就不可以了。找不到原因，希望可以给些建议 。

**Comment by jiamingming-004** [comment]
> 目前的阶段是跟tx2没关系，在aistudio里换了模型就结果不正确对么
> 可以加入paddle推理部署QQ群959308808，方便沟通。
> 
> > > 看您的问题，是在aistudio的环境可以正常运行，但是在tx2上无法正常运行，对么？
> > 
> > 
> > 我想将它在Aistudio中做出来之后，在放入JestonTx2上运行文件，
> > 目前，使用官方给的yolov3模型,在Aistudio中也是可以运行出结果的，但换了自己的模型就不可以了。找不到原因，希望可以给些建议 。

对，是这样的，我在训练时数据集用的是VOC类型的，这个有没有影响？  好的，我添加群。

**Comment by jesen8** [comment]
@shangzhizhou 您好，请问在nano上使用gpu跑yolov3模型无法正确推理而cpu可以正确推理的问题有解决方案了吗，目前我的测试也是这样的结论

**Comment by shangzhizhou** [comment]
2.1.1版本会修复该问题，预计6月底发布。
当前修复代码已经合入，可以编译release/2.1分支代码验证，或等待版本发布。

**Comment by jesen8** [comment]
@shangzhizhou 感谢回复，目前测试我用的是下面这个版本(git tag 显示出来的v2.1.0版本)，我尽快试试最新版
```bash
xunchang@xunchang-smartbox:~/work/lib/Paddle$ git branch
* (HEAD detached at v2.1.0)
  develop
xunchang@xunchang-smartbox:~/work/lib/Paddle$ git log
commit 4ccd9a0a86ad550a861c954d70e28ef15741b310 (HEAD, tag: v2.1.0)
Author: Kaipeng Deng <dengkaipeng@baidu.com>
Date:   Wed May 12 23:09:32 2021 +0800

    fix dataloader exit hang when join re-enter (#32835)
    
    * fix dataloader exit hang when join re-enter. test=develop
    
    * double check _shutdown. test=develop

```

**Comment by jesen8** [comment]
@shangzhizhou 还有一个问题，
Paddle 2.1.0版本在nano上编译的cpp推理库，在使用paddle-inference的cpp接口时，在intel cpu + gpu 环境下可以同时初始化多个模型，并且反复交叉调用，但是在nano上测试的时候，只初始化了1个模型，而且只能跑第一次，第二次推理的时候就会出现下面的错误，测试就是简单的初始化，然后拿5张图片循环推理，推理到第二张就会显示 资源不够的 错误。开启trt fp32子图优化后仍然一样，请问知道是什么原因吗，有解决办法吗？ 难道是因为nano只有1G的显存，cuda核心数太少的原因吗，感谢回答
```bash
terminate called after throwing an instance of 'thrust::system::system_error'
  what():  parallel_for failed: cudaErrorLaunchOutOfResources: too many resources requested for launch
Aborted (core dumped)
```

**Comment by shangzhizhou** [comment]
> 难道是因为nano只有1G的显存，cuda核心数太少的原因吗，

这个报错应该不是显存的问题，更大的可能是cuda的线程数、sharedmemory等资源限制不足引起的。可以把模型的测试用例附一下，我们后续查一下

**Comment by jesen8** [comment]
@shangzhizhou 感谢支持，昨天升级到develop，编译后，今天测试了，没有报 `cudaErrorLaunchOutOfResources` 这个错了，模型推理结果也正常了

**Comment by jesen8** [comment]
@shangzhizhou  你好，目前v2.1.0版本，在jetson nano上跑yolo是可以得到正确结果的，但是单独跑PaddleSeg项目下的轻量分割网络bisenet时，能顺利推理，但是无法获得正确的分割结果. 而且同时调用上面的yolo和bisenet网络时，先调用yolo正常推理一次后，调用bisenet推理仍然会出现如下错误：
`parallel_for failed: cudaErrorLaunchOutOfResources: too many resources requested for launch`
请问最新版本解决这个问题了吗 
或者目前已知的有支持在nano上跑的分割网络吗
