### ISSUE TITLE
飞腾麒麟v10源码编译安装paddle为什么结果是安装了paddlepaddle-0.0.0

### ISSUE THREAD

**Issue by yunchangxiaoguan** [PaddlePaddle/Paddle#32321]
Package         Version  
--------------- ---------
astor           0.8.1    
certifi         2020.12.5
chardet         4.0.0    
decorator       4.4.2    
fros            1.1      
gast            0.4.0    
gpg             1.13.1   
idna            2.10     
iniparse        0.4      
numpy           1.20.2   
paddlepaddle    0.0.0    
Pillow          6.2.0    
pip             18.0     
protobuf        3.15.8   
pycairo         1.18.2   
PyGObject       3.30.1   
pyparsing       2.2.0    
python-dateutil 2.7.0    
requests        2.25.1   
rpm             4.15.1   
setuptools      40.4.3   
six             1.12.0   
urllib3         1.26.4   
wheel           0.36.2

**Comment by heavengate** [comment]
看报错信息是OpenSSL的问题，更新一下OpenSSL试下呢，或者是不是你的网络连不到`https://github.com/noloader/cryptopp-cmake/` 这个库
```
fatal: unable to access 'https://github.com/noloader/cryptopp-cmake/': OpenSSL SSL_read: SSL_ERROR_SYSCALL, errno 104
make[2]: *** [CMakeFiles/extern_cryptopp.dir/build.make:121: third_party/cryptopp/src/extern_cryptopp-
```

**Comment by yunchangxiaoguan** [comment]
> 看报错信息是OpenSSL的问题，更新一下OpenSSL试下呢，或者是不是你的网络连不到`https://github.com/noloader/cryptopp-cmake/` 这个库
> 
> ```
> fatal: unable to access 'https://github.com/noloader/cryptopp-cmake/': OpenSSL SSL_read: SSL_ERROR_SYSCALL, errno 104
> make[2]: *** [CMakeFiles/extern_cryptopp.dir/build.make:121: third_party/cryptopp/src/extern_cryptopp-
> ```

好的，谢谢了，我后来改了个地址就好了，现在安装成功了但是版本居然是0.0.0

**Comment by heavengate** [comment]
> > 看报错信息是OpenSSL的问题，更新一下OpenSSL试下呢，或者是不是你的网络连不到`https://github.com/noloader/cryptopp-cmake/` 这个库
> > ```
> > fatal: unable to access 'https://github.com/noloader/cryptopp-cmake/': OpenSSL SSL_read: SSL_ERROR_SYSCALL, errno 104
> > make[2]: *** [CMakeFiles/extern_cryptopp.dir/build.make:121: third_party/cryptopp/src/extern_cryptopp-
> > ```
> 
> 好的，谢谢了，我后来改了个地址就好了，现在安装成功了但是版本居然是0.0.0

develop编译安装的版本都是0.0.0，如果问题解决当前issue就先关闭了~

**Comment by imsotable** [comment]
> 

你好，那么怎么才能编译得到比较高版本的paddlepaddle呢？
