### ISSUE TITLE
IOError

### ISSUE THREAD

**Issue by yolearn** [PaddlePaddle/Paddle#32334]
- 标题：简洁、精准概括您的问题
- 版本、环境信息：
    1）PaddlePaddle版本：1.1
    2）CPU/GPU：CPU
    3）系统环境：LINUX
    4）Python 2.7
    5）显存信息

/workspace/python/lib/python2.7/site-packages/paddle/fluid/incubate/data_generator/__init__.py", line 135, in run_from_stdin
sys.stdout.write(self._gen_str(sample))
sys.stdout.write(self._gen_str(sample))
sys.stdout.write(self._gen_str(sample))
sys.stdout.write(self._gen_str(sample))
 IOErrorsys.stdout.write(self._gen_str(sample))
IOErrorIOErrorIOErrorIOError    IOError:     IOError: : : sys.stdout.write(self._gen_str(sample))

多机 cpu 一直遇到这个问题，但是本地跑 generator 都没有问题

**Comment by hutuxian** [comment]
请提供一个可复现的最小代码，我们复现一下看看？

**Comment by yolearn** [comment]
我用如流发你可以？你如流 id 多少？

**Comment by hutuxian** [comment]
内部用户的话请在用户群里先提问吧，我看到会联系你

**Comment by yolearn** [comment]
我在 Paddle用户2群 | Paddle Users 好像没人联系我
