### ISSUE TITLE
Scatter方法

### ISSUE THREAD

**Issue by GuoQuanhao** [PaddlePaddle/Paddle#32332]
如何使用paddle的scatter实现torch的scatter方法？paddle的scatter没有维度这一个变量

**Comment by hutuxian** [comment]
试一下scatter_nd呢，一般通过构造index，可以实现torch里dim的功能。如果您觉得无法实现，可以贴一下具体代码我们再一起讨论。

**Comment by GuoQuanhao** [comment]
已解决，原始代码的目的是使用torch.scatter转成onehot，我使用了paddle.nn.functional.one_hot完美替代
