### ISSUE TITLE
关于paddle.summary

### ISSUE THREAD

**Issue by HandsomeAIccx** [PaddlePaddle/Paddle#32335]
文档中说   input_size,如果模型有多个输入。那么该值需要设定为list[tuple|InputSpec]，包含每个输入的shape。
文档中只有单输入的示例，能否增加一个多输入的示例。
我自己的网络是多输入，想用summary看看，但是一直失败。

**Comment by sandyhouse** [comment]
问题已收到，我们会尽快完善文档。另外，多输入时只需要传入一个list结构即可，例如list[(1, 28, 28, 28), (1, 256, 256, 256)],表明每个输入的shape。

**Comment by HandsomeAIccx** [comment]
> 问题已收到，我们会尽快完善文档。另外，多输入时只需要传入一个list结构即可，例如list[(1, 28, 28, 28), (1, 256, 256, 256)],表明每个输入的shape。
这个问题您知道是什么情况吗：
我输入如下代码
paddle.summary(atten_decoder, [(10, 1), (10, 1, 256), (10, 11, 256), (10, 11,256)], dtypes='int64')
atten_decoder是[教程](https://www.paddlepaddle.org.cn/documentation/docs/zh/tutorial/nlp_case/seq2seq_with_attention/seq2seq_with_attention.html)中所定义的AttentionDecoder,我也print了forward中输入的shape，确实应该是(10, 1), (10, 1, 256), (10, 11, 256), (10, 11,256)，不知道是为什么summary会报这个错误。
![image](https://user-images.githubusercontent.com/25932765/115176093-f5beed80-a0fe-11eb-8744-f0d11dbffc04.png)
![image](https://user-images.githubusercontent.com/25932765/115176098-f9eb0b00-a0fe-11eb-800d-7996cb32818b.png)


RuntimeError: (NotFound) Operator matmul does not have kernel for data_type[int64_t]:data_layout[ANY_LAYOUT]:place[CUDAPlace(0)]:library_type[PLAIN].
  [Hint: Expected kernel_iter != kernels.end(), but received kernel_iter == kernels.end().] (at D:\v2.0.1\paddle\paddle\fluid\imperative\prepared_operator.cc:128)
  [operator < matmul > error]

**Comment by sandyhouse** [comment]
从报错信息看是数据类型不匹配，没有正确设置数据类型。
