### ISSUE TITLE
paddle.sum()函数能不能支持对bool变量的求和呀

### ISSUE THREAD

**Issue by XianrenYty** [PaddlePaddle/Paddle#32341]
paddle.sum()函数能不能支持对bool变量的求和呀 paddle版本2.0.2

**Comment by ceci3** [comment]
您好，sum不支持对bool变量求和

**Comment by wadefelix** [comment]
从布尔语义上来讲，直接支持数学运算不甚合理。
您可以使用  `paddle.to_tensor`做个类型转换后使用 [to_tensor-API文档-PaddlePaddle深度学习平台](https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/tensor/creation/to_tensor_cn.html)

**Comment by XianrenYty** [comment]
我是把torch代码移植过来的时候发现。torch支持paddle不行



---原始邮件---
发件人: "Ren Wei ***@***.***&gt;
发送时间: 2021年4月21日(周三) 上午9:22
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [PaddlePaddle/Paddle] paddle.sum()函数能不能支持对bool变量的求和呀 (#32341)




 
从布尔语义上来讲，直接支持数学运算不甚合理。
 您可以使用  paddle.to_tensor做个类型转换后使用 to_tensor-API文档-PaddlePaddle深度学习平台
