### ISSUE TITLE
paddle函数问题

### ISSUE THREAD

**Issue by dickobe** [PaddlePaddle/Paddle#32361]
paddle中padded_batch这个函数的作用是什么，在哪里可以查到函数说明？

**Comment by ceci3** [comment]
这好像不是paddle的官方函数，请问您在哪里看到的这个函数

**Comment by j-shao** [comment]
from propeller.paddle.data.functional import Dataset
Dataset.from_generator_func(
            PointwiseGenerator(
                #os.path.join(data_dir, "part.0"),
                os.path.join(data_dir, "path.0"),
                vocab,
                max_seqlen)
        ).chunk(num_replica) \
        .shard(num_replica, replica_id) \
        .map(append_label_func(before)) \
        .padded_batch(batch_size, (0, 0, 0, 0), max_seqlen=max_seqlen) \
        .map(append_label_func(after, after2))
