### ISSUE TITLE
飞桨有没有“注意力机制”方面的网络实现

### ISSUE THREAD

**Issue by A-Pai** [PaddlePaddle/Paddle#32371]
飞桨有没有“注意力机制”方面的网络实现，是哪些？

**Comment by TCChenlong** [comment]
hi，关于注意力机制方面的网络实现，目前飞桨官网文档中有这篇案例：
[使用注意力机制的LSTM的机器翻译](https://www.paddlepaddle.org.cn/documentation/docs/zh/tutorial/nlp_case/seq2seq_with_attention/seq2seq_with_attention.html)
此外，在AI Studio 中，也有 PaddleNLP 官方账号提供的案例：
[『NLP经典项目集』05：新年到，飞桨带你对对联](https://aistudio.baidu.com/aistudio/projectdetail/1321118)
如果想了解更多关于Paddle NLP的案例，可以参考：
[自然语言处理](https://www.paddlepaddle.org.cn/documentation/docs/zh/tutorial/nlp_case/index_cn.html)
[『NLP经典项目集』项目合集](https://aistudio.baidu.com/aistudio/projectdetail/1535371)
