### ISSUE TITLE
源码编译问题报错

### ISSUE THREAD

**Issue by thomas-yanxin** [PaddlePaddle/Paddle#32372]
- 版本、环境信息：
    1）PaddlePaddle版本：paddlepaddle2.0.2-gpu
    2）CPU：AMD5800H
    3）GPU：NVIDIA 3060
    4）系统环境：windows   python3.7.9
- 安装方式信息：
本地编译：cmake .. -G "Visual Studio 15 2017 Win64" -T host=x64 -DCMAKE_BUILD_TYPE=Release -DWITH_GPU=ON -DWITH_TESTING=OFF -DPYTHON_EXECUTABLE=D:\\programme\\Anaconda\\envs\\paddle\\python.exe -DCUDA_TOOLKIT_ROOT_DIR="C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v11.2"
报错如下：
 Computing Toolkit\\CUDA\\v11.2"
-- Found Paddle host system: win32, version:
-- Found Paddle host system's CPU: 16 cores
-- Selecting Windows SDK version 10.0.17763.0 to target Windows 10.0.19042.
CMake Error at C:/Program Files/CMake/share/cmake-3.16/Modules/FindCUDA.cmake:749 (find_program):
  Syntax error in cmake code at

    C:/Program Files/CMake/share/cmake-3.16/Modules/FindCUDA.cmake:749

  when parsing string

    CUDA_NVCC_EXECUTABLE;NAMES;nvcc;PATHS;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.2;ENV;CUDA_PATH;ENV;CUDA_BIN_PATH;PATH_SUFFIXES;bin;bin64;NO_DEFAULT_PATH

  Invalid character escape '\P'.
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.16/Modules/FindCUDA.cmake:759 (cuda_find_host_program)
  CMakeLists.txt:29 (find_package)

-- Configuring incomplete, errors occurred!
See also "D:/programme/Anaconda/envs/paddle/Lib/Paddle/build/CMakeFiles/CMakeOutput.log".
See also "D:/programme/Anaconda/envs/paddle/Lib/Paddle/build/CMakeFiles/CMakeError.log".

**Comment by makaspacex** [comment]
官网提供的编译版本3060下无法通过编译，Centos7试了好多个cuda版本 都不太行

**Comment by thomas-yanxin** [comment]
听说五月上旬出支持cuda11.2的版本，要不耐心等等趴……这源码编译也挺麻烦的（主要是懒）
| |
颜鑫
|
|
***@***.***
|
签名由网易邮箱大师定制
在2021年4月20日 19:32，百变魔君 ***@***.***> 写道：

官网提供的编译版本3060下无法通过编译，Centos7试了好多个cuda版本 都不太行

**Comment by thomas-yanxin** [comment]
30系显卡好像只支持>=cuda11.1


| |
颜鑫
|
|
***@***.***
|
签名由网易邮箱大师定制
在2021年4月20日 19:32，百变魔君 ***@***.***> 写道：

官网提供的编译版本3060下无法通过编译，Centos7试了好多个cuda版本 都不太行

**Comment by makaspacex** [comment]
30系 显卡使用cuda11.1的话 虽然不`nvcc fatal   : Unsupported gpu architecture 'compute_86'`，但也编译不通过

**Comment by Shixiaowei02** [comment]
请在win10环境下，把python和cuda路径里的`/`改为`\`
