### ISSUE TITLE
请问支持cuda11.2的.whl啥时候发布呀

### ISSUE THREAD

**Issue by thomas-yanxin** [PaddlePaddle/Paddle#32370]

**Comment by mikeshi80** [comment]
据飞桨内部人员说是计划在5月中上旬发布的2.1版本全面支持CUDA 11系列。我也在等待，现在只能靠自己编译，具体可以参考 https://my.oschina.net/mikeshi/blog/4981664

**Comment by thomas-yanxin** [comment]
哈哈哈懒得自己编译（其实是嫌麻烦……）还是等几天吧，反正也没多久了
| |
左右
|
|
***@***.***
|
签名由网易邮箱大师定制
在2021年4月20日 10:33，Mike ***@***.***> 写道：

据飞桨内部人员说是计划在5月中上旬发布的2.1版本全面支持CUDA 11系列。我也在等待，现在只能靠自己编译，具体可以参考 https://my.oschina.net/mikeshi/blog/4981664

**Comment by makaspacex** [comment]
编译3060 cuda11.1 已经疯了

**Comment by mikeshi80** [comment]
> 编译3060 cuda11.1 已经疯了

你试试我编译的版本，是python 3.7 + CUDA 11.2 + cuDNN 8+Win10环境下编译的，如果你也是用Win10，那么还可能可以就救你

链接：https://pan.baidu.com/s/1uvSuq_SO2cM-6OXaS4ULSg 
提取码：o7yf

**Comment by makaspacex** [comment]
@mikeshi80 谢谢🙏 我是Centos7

**Comment by mikeshi80** [comment]
> @mikeshi80 谢谢🙏 我是Centos7

Linux的话，官方就有非正式安装包的，不过在一个微信群里，他们今天刚发了最新版的，我把原文贴出来

> 
> 官方适配30系列的wheel包（实验版）--Windows最新鲜的出炉啦～～
> 正式版的包会在4月底在飞桨官网正式上线
> windows:飞桨版本：develop
> 链接: https://pan.baidu.com/s/17Dnt3LXWplQ1ClqRWSb-9Q 
> 密码: l658
> linux:飞桨版本：2.0.1:
> 链接: https://pan.baidu.com/s/19cstmTf8gFHWqcNMrBdmCg 
> 提取码: 9xwp 
> 复制这段内容后打开百度网盘手机App，操作更方便哦
> 【关于此wheel包说明】python37、cuda11.2、cudnn 8.1、该包编译用的是3090，但应该30系列都可以用。
> 因为此包为试用版，所以遇到问题请多多包含，问题可以在群里截图沟通哦，我们会高优解答和处理的～

**Comment by dingjiaweiww** [comment]
飞桨官网已经上线cuda11.2 了，可以参考：https://www.paddlepaddle.org.cn/install/quick?docurl=/documentation/docs/zh/install/pip/windows-pip.html
