### ISSUE TITLE
paddle.vision.transforms.Normalize

### ISSUE THREAD

**Issue by GuoQuanhao** [PaddlePaddle/Paddle#32376]
paddle.vision.transforms.Normalize会将所有输出变成3通道，我不知道是这样设计的还是一个bug
![image](https://user-images.githubusercontent.com/49911294/115336422-cb8a3000-a1d1-11eb-9b78-adfce05b183c.png)
这花费了很多时间寻找维度报错信息，发现这种问题

**Comment by Shixiaowei02** [comment]
请检查 `data_format` 参数的配置：https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/vision/transforms/functional/normalize_cn.html

**Comment by GuoQuanhao** [comment]
已使用paddle自带的灰度转换解决
