### ISSUE TITLE
 Paddle V2怎么支持drop out 

### ISSUE THREAD

**Issue by youan1** [PaddlePaddle/Paddle#3239]
如题，请问paddle V2怎么支持drop out层

paddle.networks.dropout_layer(input=concat_layer, dropout_rate=0.5)这么写会失败，错误为
Fri Aug  4 15:03:41 2017[1,36]<stderr>:  File "conf/trainer_config.conf", line 672, in <module>
Fri Aug  4 15:03:41 2017[1,36]<stderr>:    dropout_layer0=paddle.networks.dropout_layer(input=concat_layer, dropout_rate=0.5)
Fri Aug  4 15:03:41 2017[1,36]<stderr>:AttributeError: 'module' object has no attribute 'dropout_layer'

**Comment by gongweibao** [comment]
参考一下：https://github.com/PaddlePaddle/Paddle/issues/2502

**Comment by typhoonzero** [comment]
`paddle.layer.dropout_layer`试下，这个挪到layers下了
