### ISSUE TITLE
模型训练网络在Paddle上不收敛，但是在Pytorch可以收敛

### ISSUE THREAD

**Issue by zhijiejia** [PaddlePaddle/Paddle#32394]
我将Pytorch的变化检测网络迁移到Paddle上，发现在Paddle上不收敛，或者不如Pytorch上收敛的快。不知道有没有人有相似的情况，我也不好公开我的代码，因为我还在毕设。

**Comment by zhijiejia** [comment]
像GCNet、CBAM中的这类图像的注意力机制，好像收敛的不如Pytorch好

**Comment by Shixiaowei02** [comment]
请 @littletomatodonkey 回答一下这个问题，谢谢

**Comment by littletomatodonkey** [comment]
你好，可以看下两者的初始化是否完全一致，此外，关于和torch的对比，可以先使用同一份权重进行初始化，使用相同的输入，看下forward的输出是否一致，确保二者前向和结构完全可以对上再进行实验

**Comment by zhijiejia** [comment]
感谢您的建议，确实是我在实现上有点问题，权重文件也有问题，现在两者实验结果已经没有区别了。

**Comment by littletomatodonkey** [comment]
好的，感谢使用Paddle，有什么问题咱们再随时交流~
