### ISSUE TITLE
用paddle复现经典CNN报错

### ISSUE THREAD

**Issue by JJYjackson** [PaddlePaddle/Paddle#32391]
- 标题：“用paddle复现经典CNN报错 ”
- 版本、环境信息：
    Paddle version: 2.0.2
Paddle With CUDA: False
OS: debian stretch/sid
Python version: 3.7.4
CUDA version: None
cuDNN version: None.None.None
Nvidia driver version: None
- 模型信息
    1）模型名称   :cnn1
2）使用数据集名称:
RML2016.10a-调制识别数据集
https://aistudio.baidu.com/aistudio/datasetdetail/80473
- 复现信息：
![微信截图_20210420173241](https://user-images.githubusercontent.com/65533171/115373537-91835300-a1fe-11eb-841b-deb8b5b5370f.png)
上图是想要用paddle复现的CNN模型，其中的dropout为0.5.
我使用SubClass组网方式构造cnn1。
代码如下图所示：
![微信截图_20210420173758](https://user-images.githubusercontent.com/65533171/115374288-43bb1a80-a1ff-11eb-9746-f8eb4464ca78.png)
模型搭建代码和训练代码如下图：
![微信截图_20210420175004](https://user-images.githubusercontent.com/65533171/115376228-1a9b8980-a201-11eb-9c64-2ca342e15c34.png)
![微信截图_20210420175017](https://user-images.githubusercontent.com/65533171/115376320-2dae5980-a201-11eb-867c-efad29751898.png)
整个项目在AIStudio上的链接：https://aistudio.baidu.com/aistudio/projectdetail/1790907。

- 问题描述：运行训练段代码时出现下图的报错信息
![微信截图_20210420175104](https://user-images.githubusercontent.com/65533171/115377291-0efc9280-a202-11eb-8a2a-f6a69a86af60.png)
详细报错信息为：
The loss value printed in the log is the current step, and the metric is the average value of previous step.
Epoch 1/50
---------------------------------------------------------------------------ValueError                                Traceback (most recent call last)<ipython-input-9-bc5de1dee941> in <module>
     30                      batch_size=1024,
     31                      callbacks=callbacks,
---> 32                      verbose=1)
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/hapi/model.py in fit(self, train_data, eval_data, batch_size, epochs, eval_freq, log_freq, save_dir, save_freq, verbose, drop_last, shuffle, num_workers, callbacks)
   1493         for epoch in range(epochs):
   1494             cbks.on_epoch_begin(epoch)
-> 1495             logs = self._run_one_epoch(train_loader, cbks, 'train')
   1496             cbks.on_epoch_end(epoch, logs)
   1497 
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/hapi/model.py in _run_one_epoch(self, data_loader, callbacks, mode, logs)
   1800             if mode != 'predict':
   1801                 outs = getattr(self, mode + '_batch')(data[:len(self._inputs)],
-> 1802                                                       data[len(self._inputs):])
   1803                 if self._metrics and self._loss:
   1804                     metrics = [[l[0] for l in outs[0]]]
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/hapi/model.py in train_batch(self, inputs, labels)
    939               print(loss)
    940         """
--> 941         loss = self._adapter.train_batch(inputs, labels)
    942         if fluid.in_dygraph_mode() and self._input_info is None:
    943             self._update_inputs()
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/hapi/model.py in train_batch(self, inputs, labels)
    654         else:
    655             outputs = self.model.network.forward(
--> 656                 * [to_variable(x) for x in inputs])
    657 
    658         losses = self.model._loss(*(to_list(outputs) + labels))
~/cnn1_cnn2.py in forward(self, x)
     26         x = self.dropout(x)
     27         x = paddle.flatten(x, start_axis=0, stop_axis=-1)
---> 28         x = self.linear1(x)
     29         x = self.relu(x)
     30         x = self.dropout(x)
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py in __call__(self, *inputs, **kwargs)
    900                 self._built = True
    901 
--> 902             outputs = self.forward(*inputs, **kwargs)
    903 
    904             for forward_post_hook in self._forward_post_hooks.values():
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/nn/layer/common.py in forward(self, input)
    135     def forward(self, input):
    136         out = F.linear(
--> 137             x=input, weight=self.weight, bias=self.bias, name=self.name)
    138         return out
    139 
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/nn/functional/common.py in linear(x, weight, bias, name)
   1471         pre_bias = _varbase_creator(dtype=x.dtype)
   1472         core.ops.matmul(x, weight, pre_bias, 'transpose_X', False,
-> 1473                         'transpose_Y', False, "alpha", 1)
   1474         return dygraph_utils._append_bias_in_dygraph(
   1475             pre_bias, bias, axis=len(x.shape) - 1)
ValueError: (InvalidArgument) The fisrt matrix width should be same as second matrix height,but received fisrt matrix width 2097152, second matrix height 2048
  [Hint: Expected dim_a.width_ == dim_b.height_, but received dim_a.width_:2097152 != dim_b.height_:2048.] (at /paddle/paddle/fluid/operators/math/blas_impl.h:1170)
  [operator < matmul > error]
把训练代码中的bachsize=1024改成bachsize=1就可以正常训练了，这是什么原因？怎样改能让batch_size=1024时也可以正常训练？请大佬指点。

**Comment by Shixiaowei02** [comment]
看起来是 `Linear-1` 层的尺寸出错了，请检查一下

**Comment by JJYjackson** [comment]
> 看起来是 `Linear-1` 层的尺寸出错了，请检查一下
您说的这个我之前改过，矛盾的是Linear-1层的尺寸按照报错改为"nn.Linear(2097152, 128)"然后运行下图中的代码就又会报Linear-1层的错。
![微信截图_20210422](https://user-images.githubusercontent.com/65533171/115670683-455e1d00-a37c-11eb-804b-e1e472d9ca69.png)
然后我将model_cnn1.summary((None, 1, 2, 128)) 注释掉，再运行训练段的代码又会报如下图的错误：   
希望大佬看一下。
![微信截图_202104221](https://user-images.githubusercontent.com/65533171/115673027-bdc5dd80-a37e-11eb-94cf-575a0a5c53ed.png)
![image](https://user-images.githubusercontent.com/65533171/115673242-febdf200-a37e-11eb-9811-8fdf89743317.png)
![image](https://user-images.githubusercontent.com/65533171/115673287-0b424a80-a37f-11eb-9c1e-aabc44fef79d.png)


具体报错信息如下：
The loss value printed in the log is the current step, and the metric is the average value of previous step.
Epoch 1/50
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/layers/utils.py:77: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
  return (isinstance(seq, collections.Sequence) and
---------------------------------------------------------------------------ValueError                                Traceback (most recent call last)<ipython-input-13-bc5de1dee941> in <module>
     30                      batch_size=1024,
     31                      callbacks=callbacks,
---> 32                      verbose=1)
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/hapi/model.py in fit(self, train_data, eval_data, batch_size, epochs, eval_freq, log_freq, save_dir, save_freq, verbose, drop_last, shuffle, num_workers, callbacks)
   1493         for epoch in range(epochs):
   1494             cbks.on_epoch_begin(epoch)
-> 1495             logs = self._run_one_epoch(train_loader, cbks, 'train')
   1496             cbks.on_epoch_end(epoch, logs)
   1497 
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/hapi/model.py in _run_one_epoch(self, data_loader, callbacks, mode, logs)
   1800             if mode != 'predict':
   1801                 outs = getattr(self, mode + '_batch')(data[:len(self._inputs)],
-> 1802                                                       data[len(self._inputs):])
   1803                 if self._metrics and self._loss:
   1804                     metrics = [[l[0] for l in outs[0]]]
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/hapi/model.py in train_batch(self, inputs, labels)
    939               print(loss)
    940         """
--> 941         loss = self._adapter.train_batch(inputs, labels)
    942         if fluid.in_dygraph_mode() and self._input_info is None:
    943             self._update_inputs()
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/hapi/model.py in train_batch(self, inputs, labels)
    656                 * [to_variable(x) for x in inputs])
    657 
--> 658         losses = self.model._loss(*(to_list(outputs) + labels))
    659         losses = to_list(losses)
    660         final_loss = fluid.layers.sum(losses)
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py in __call__(self, *inputs, **kwargs)
    900                 self._built = True
    901 
--> 902             outputs = self.forward(*inputs, **kwargs)
    903 
    904             for forward_post_hook in self._forward_post_hooks.values():
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/nn/layer/loss.py in forward(self, input, label)
    415             axis=self.axis,
    416             use_softmax=self.use_softmax,
--> 417             name=self.name)
    418 
    419         return ret
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/nn/functional/loss.py in cross_entropy(input, label, weight, ignore_index, reduction, soft_label, axis, use_softmax, name)
   1401             input, label, 'soft_label', soft_label, 'ignore_index',
   1402             ignore_index, 'numeric_stable_mode', True, 'axis', axis,
-> 1403             'use_softmax', use_softmax)
   1404 
   1405         if weight is not None:
ValueError: (InvalidArgument) If Attr(soft_label) == false, the axis dimension of Input(Label) should be 1.
  [Hint: Expected labels_dims[axis] == 1UL, but received labels_dims[axis]:1024 != 1UL:1.] (at /paddle/paddle/fluid/operators/softmax_with_cross_entropy_op.cc:179)
  [operator < softmax_with_cross_entropy > error]

**Comment by Shixiaowei02** [comment]
您好，怀疑模型组网有问题，请问能提供原始文献我们看下吗

**Comment by JJYjackson** [comment]
[Convolutional Radio Modulation Recognition Networks.pdf](https://github.com/PaddlePaddle/Paddle/files/6362487/Convolutional.Radio.Modulation.Recognition.Networks.pdf)
您好，这是复现的原始文献。

**Comment by littletomatodonkey** [comment]
维度需要对应上

```
x = paddle.flatten(x, start_axis=0, stop_axis=-1)
```

改为

```
x = paddle.reshape(x, [x.shape[0],-1])
```
