### ISSUE TITLE
如何在model.eval的情况下进行梯度回传backward

### ISSUE THREAD

**Issue by WhiteFireFox** [PaddlePaddle/Paddle#32399]
如何在model.eval的情况下进行梯度回传backward

**Comment by Leonardo-Ding** [comment]
同学你好，model.eval只做前向计算，不会进行梯度回传

**Comment by WhiteFireFox** [comment]
> 同学你好，model.eval只做前向计算，不会进行梯度回传

您好，很高兴收到了您的回复，刚刚实验了下发现是加了bn情况下会导致model.eval下不能backward，要是全卷积是可以backward的

**Comment by WhiteFireFox** [comment]
<img width="602" alt="594c013c810082584386a4d54d57812" src="https://user-images.githubusercontent.com/57762833/115987897-a4749980-a5e9-11eb-8d30-43a9c6c55cee.png">
也就是这个情况下是可以eval下back的

**Comment by WhiteFireFox** [comment]
<img width="454" alt="f196276637ddda1801b2ba1af052eae" src="https://user-images.githubusercontent.com/57762833/115987916-bc4c1d80-a5e9-11eb-8f0d-a1841bf2df9e.png">

这样加了bn后就不行

**Comment by WhiteFireFox** [comment]
报错信息是：
<img width="828" alt="d0a099276f899a04f8d2bd83987d76f" src="https://user-images.githubusercontent.com/57762833/115987919-c66e1c00-a5e9-11eb-90d5-1d4ce875a889.png">

**Comment by WhiteFireFox** [comment]
感觉bn是eval下不能back的内鬼（狗头保命）
