### ISSUE TITLE
怎样把训练好的模型打包成一个api工具，而不暴露模型配置和源码文件？

### ISSUE THREAD

**Issue by zishuaiz** [PaddlePaddle/Paddle#3240]
predict依赖模型的配置文件和训练好的参数，怎样才能不暴露模型配置文件向使用者提供可调用的api？

**Comment by typhoonzero** [comment]
参考：https://github.com/PaddlePaddle/Paddle/tree/develop/paddle/capi/examples/model_inference

用capi 编译一个静态库分发即可。其中模型配置可以转换成一个protobin

**Comment by zishuaiz** [comment]
thanks @typhoonzero
