### ISSUE TITLE
paddle2.0 tracedLayer.save_inference_model保存的是旧格式的文件，非*pdiparams、*pdmodel。

### ISSUE THREAD

**Issue by lonelydancer** [PaddlePaddle/Paddle#32402]
- 版本、环境信息：
    1）PaddlePaddle版本：2.0.2
    2）GPU：GPU T4、CUDA10.1 和CUDNN  7.6.
    4）系统环境：Ubuntu 16.04.7 LTS，Python版本 3.6

-预测信息
    1）python3.6 test_tracelayer.py  
   https://github.com/lonelydancer/algorithm/blob/master/test_tracelayer.py

- 复现信息：

   报错
   No such file or directory: '/home/infer_demo/Paddle-Inference-Demo/python/paddle_trt/saved_infer_model2.pdmodel

   out_dygraph, static_layer = paddle.jit.TracedLayer.trace(layer, inputs=[in_var])
  static_layer.save_inference_model(save_dirname, feed=[0], fetch=[0])
  发现保存的model格式是旧版的
   linear_0.b_0  linear_0.w_0  __model__
  与文档不符合
 https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/fluid/dygraph/jit/TracedLayer_cn.html#tracedlayer
- 问题描述：请详细描述您的问题，同步贴出报错信息、日志/代码关键片段

**Comment by Shixiaowei02** [comment]
您好，我们检查一下这个问题。您生成的这个模型依然可以正常加载，请您先暂时使用这种格式。

**Comment by zhhsplendid** [comment]
嗨，您好，您的反馈是对的，这个问题我们内部也发现了，并且在develop上已经修复，将随2.1发布该修复。如果您来不及等待新版本，当下需要该功能，使用旧版载入接口？或者使用ProgramTranslator也能做动转静功能。

**Comment by lonelydancer** [comment]
@Shixiaowei02 @Shixiaowei02  paddle inference demo 中paddle_trt的例子是不是也要同步升级。我看他们用的还是1.8格式的ernie model..

**Comment by Shixiaowei02** [comment]
> @Shixiaowei02 @Shixiaowei02 paddle inference demo 中paddle_trt的例子是不是也要同步升级。我看他们用的还是1.8格式的ernie model..

请 @winter-wang 关注一下吧。

**Comment by winter-wang** [comment]
> > @Shixiaowei02 @Shixiaowei02 paddle inference demo 中paddle_trt的例子是不是也要同步升级。我看他们用的还是1.8格式的ernie model..
> 
> 请 @winter-wang 关注一下吧。

已升级

**Comment by lonelydancer** [comment]
@winter-wang 对应的ernie Classification paddle 2.0的model在哪里发布呢?
