### ISSUE TITLE
paddle_inference关于int8推理的部分疑惑

### ISSUE THREAD

**Issue by thzyyx** [PaddlePaddle/Paddle#32403]
版本：paddle-2.0.1
模型：YOLOv3 ResNet50_vd DCN
环境：T4显卡  cudnn-8.0, cuda11, TensorRT7.2.2.3
问题描述：测试yolov3模型在paddle-TensorRT下的性能，在paddle-2.0的文档描述中未描述如何进行int8的推理，阅读1.8.0的文档，对于paddle-TensorRT有如下说明：
`precision，类型：enum class Precision {kFloat32 = 0, kHalf, kInt8,};, 默认值为AnalysisConfig::Precision::kFloat32。指定使用TRT的精度，支持FP32（kFloat32），FP16（kHalf），Int8（kInt8）。若需要使用Paddle-TRT int8离线量化校准，需设定precision为 AnalysisConfig::Precision::kInt8, 且设置use_calib_mode 为true。`
问题一：这段说明表达的含义是不是用户可以输入fp32的模型，通过设置Int8模式和use_calib_mode为True的方法，实现fp32到int8的量化，并进行推理？1.8的文档描述是否适用于2.0版本的paddle？
问题二：使用问题一中描述的方法，使用python接口（2.0文档中的说明）进行推理，发现可以得到结果，但没有传入或者导入校准图集的方法，paddle内部存在校准表？python接口生成校准表有无示例？
问题三：同一张图分别使用fp32、fp16、int8推理耗时如下，由fp16到int8的推理速度几乎没变化，这种现象是否正常?
不同模式python接口推理耗时：
 Float32: 29.14ms  注：use_calib_mode = False
 Half:  13.2ms         注：use_calib_mode = False
 Int8: 12.7ms          注：use_calib_mode = True
Float32: 29.29       注：use_calib_mode = True，这个设置是按照2.0的文档中“python预测API介绍”一节中描述操作的，但是从结果和推理速度上分析，跟Float32完全一致，不知道是不是文档描述问题？

**Comment by shangzhizhou** [comment]
use_calib_mode = True只有在精度设置为int8时才会生效，此时走的是trt的离线量化。
当其他精度下，会忽略该配置项。
