### ISSUE TITLE
TX2编译报错reduce_sum_op.cu.o failed

### ISSUE THREAD

**Issue by github4529** [PaddlePaddle/Paddle#32400]
1）PaddlePaddle版本：release2.0
    2）CPU：Jeston TX2
    3）GPU：CUDA 9.0.252 和CUDNN 7.1.5
    4）系统环境：Jeston TX2  版本Ubuntu16.04、Python 3.5.2

- 安装方式信息：
本地编译：cmake .. -DWITH_CONTRIB=OFF -DWITH_MKL=OFF -DWITH_MKLDNN=OFF -DWITH_TESTING=OFF -DCMAKE_BUILD_TYPE=Release -DON_INFER=ON -DWITH_PYTHON=OFF -DWITH_XBYAK=OFF -DWITH_NV_JETSON=ON
make -j 4

- 复现信息：如为报错，请给出复现环境、复现步骤
- 问题描述：请详细描述您的问题，同步贴出报错信息、日志/代码关键片段
[ 24%] Built target sgd_op
[ 24%] Building CUDA object paddle/fluid/operators/reduce_ops/CMakeFiles/reduce_sum_op.dir/reduce_sum_op.cu.o
[ 24%] Built target logsumexp_op
[ 24%] Built target frobenius_norm_op
[ 24%] Built target reduce_all_op
Scanning dependencies of target reduce_any_op
[ 24%] Building CXX object paddle/fluid/operators/reduce_ops/CMakeFiles/reduce_any_op.dir/reduce_any_op.cc.o
[ 24%] Linking CUDA device code CMakeFiles/paddle_custom_op_shared.dir/cmake_device_link.o
[ 24%] Linking CXX shared library libpaddle_custom_op.so
[ 24%] Linking CXX static library libfused_broadcast_op_handle.a
[ 24%] Built target fused_broadcast_op_handle
[ 24%] Building CUDA object paddle/fluid/operators/reduce_ops/CMakeFiles/reduce_any_op.dir/reduce_any_op.cu.o
[ 24%] Built target paddle_custom_op_shared
Scanning dependencies of target reduce_min_op
[ 24%] Building CXX object paddle/fluid/operators/reduce_ops/CMakeFiles/reduce_min_op.dir/reduce_min_op.cc.o
[ 24%] Building CUDA object paddle/fluid/operators/reduce_ops/CMakeFiles/reduce_min_op.dir/reduce_min_op.cu.o
[ 24%] Linking CXX static library libreduce_any_op.a
[ 24%] Built target reduce_any_op
[ 24%] Building CUDA object paddle/fluid/operators/reduce_ops/CMakeFiles/reduce_min_op.dir/reduce_min_op.part.cu.o
Killed
paddle/fluid/operators/reduce_ops/CMakeFiles/reduce_sum_op.dir/build.make:86: recipe for target 'paddle/fluid/operators/reduce_ops/CMakeFiles/reduce_sum_op.dir/reduce_sum_op.cu.o' failed
make[2]: *** [paddle/fluid/operators/reduce_ops/CMakeFiles/reduce_sum_op.dir/reduce_sum_op.cu.o] Error 137
CMakeFiles/Makefile2:81310: recipe for target 'paddle/fluid/operators/reduce_ops/CMakeFiles/reduce_sum_op.dir/all' failed
make[1]: *** [paddle/fluid/operators/reduce_ops/CMakeFiles/reduce_sum_op.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....

**Comment by Leonardo-Ding** [comment]
同学你好，能否把TX2上编译reduce_sum_op.cu.o报错具体信息发一下，从你发的报错信息片段来看，暂时看不出具体的原因
