### ISSUE TITLE
got attribute error for this line

### ISSUE THREAD

**Issue by FeixLiu** [PaddlePaddle/Paddle#32411]
https://github.com/PaddlePaddle/Paddle/blob/2194ad1566464eb7bc8eb4d5bf6b791379a3a145/tools/timeline.py#L243
在nvidia gpu开发机上获得profile文件后运行 `python timeline.py --profile_path=profile --timeline_path=timeline` 时在这一行会报Attribute Error。注释该行后可正常运行并获得timeline文件。

**Comment by Leonardo-Ding** [comment]
同学你好，paddle的timeline工具现在还有一些问题，相关同学还在完善修复一些功能，不太建议现在使用，谢谢
