### ISSUE TITLE
使用paddle inference推理时候开启GPU支持，分配了1000m显存，但是实际使用了大量的显存

### ISSUE THREAD

**Issue by geekChinaMaster** [PaddlePaddle/Paddle#32412]
- 版本、环境信息：
    1）PaddlePaddle版本：paddlepaddle-gpu2.0.0
    2）GPU：nvidia T4，CUDA10.2和CUDNN7.6.5
    4）系统环境：centos7.9，Python3.7
具体描述：
在推理时候，设置使用GPU进行推理，显存分配1000m，共一块GPU：nvidia T4，显存共16G，功率70w
具体设置为：
<img width="853" alt="8B0DE940-48EB-41ED-A0AE-6FB758008100" src="https://user-images.githubusercontent.com/44657953/115514988-411bfc00-a2b7-11eb-8d97-c5a54c55f629.png">
我们将推理程序封装成api接口，开启了4个进程4个线程以供调用，在有程序调用接口时候通过GPU监控发现显存接近满载（15G+）

1. 请问是什么原因造成的？
2. 请问是否单进程单线程时候占用显存是1000m，而多进程多线程时候显存占用是怎么样计算的
3. 但是启用了单线程和单进程进行测试时候发现实际占用的显存也是大于1000m的，是2000m-3000m，这个究竟是怎么定义的
**麻烦解答一下，谢谢~**

**Comment by Leonardo-Ding** [comment]
同学你好，paddle inference里面有设计的显存池，你代码里只是把显存池的空间初始化为1000M，实际inference时cuda程序运行占用的显存可能不止1000M，这时会通过cudaMalloc()重新申请额外的显存，所以你看到的是2000M～3000M之间，多进程占用gpu的情况比较复杂，需要具体情况具体分析。

**Comment by geekChinaMaster** [comment]
> 同学你好，paddle inference里面有设计的显存池，你代码里只是把显存池的空间初始化为1000M，实际inference时cuda程序运行占用的显存可能不止1000M，这时会通过cudaMalloc()重新申请额外的显存，所以你看到的是2000M～3000M之间，多进程占用gpu的情况比较复杂，需要具体情况具体分析。

ok那我明白了，那么就是说我不能给他们分配实际使用的显存是吗，本来是计算资源有限，如果能控制一点就好了
