### ISSUE TITLE
官网的这段 beam_search 代码示例报错

### ISSUE THREAD

**Issue by 312shan** [PaddlePaddle/Paddle#32422]
开发环境是官方百度云，版本一致的，代码在下方链接里面
https://www.paddlepaddle.org.cn/documentation/docs/zh/1.7/api_cn/layers_cn/beam_search_cn.html

错误信息如下：
```
----------------------
Error Message Summary:
----------------------
InvalidArgumentError: The Tensor in the top_k Op's Input Variable X(probs) is not initialized.
  [Hint: Expected t->IsInitialized() == true, but received t->IsInitialized():0 != true:1.] at (/paddle/paddle/fluid/framework/operator.cc:1264)
```

**Comment by FrostML** [comment]
我这里使用 Paddle 1.7.2 跑官网这段示例代码没有问题。
这段代码具体是怎么用的？
具体模型中使用方法可以参考 [transformer 1.7](https://github.com/PaddlePaddle/models/blob/release/1.7/PaddleNLP/machine_translation/transformer/transformer.py#L831)
