### ISSUE TITLE
多目标任务不同任务loss对应权重更新

### ISSUE THREAD

**Issue by DTDXG** [PaddlePaddle/Paddle#32425]
在使用torch的时候 可以通过model.parameters的方法来获取模型的参数并把子任务loss的权重参数添加进去，这样模型就能够优化子任务loss的权重参数
使用paddle的话 是否也有同样的方法获取所有参数然后把loss的权重参数添加进去呢，好像没有找到这样的方法

**Comment by Leonardo-Ding** [comment]
同学你好，我们动态图应该也可以用model.parameters()来获取参数的。
