### ISSUE TITLE
使用多卡训练的时候报错

### ISSUE THREAD

**Issue by Costwen** [PaddlePaddle/Paddle#32434]
如果使用dist.spawn(train)则会报如下错误

![image](https://user-images.githubusercontent.com/47916831/115590353-70f0f100-a303-11eb-8670-6b8aaaa9461c.png)

如果shi'y使用 fleetrun train.py 则在第二张卡的log中输出

![image](https://user-images.githubusercontent.com/47916831/115590448-8cf49280-a303-11eb-9f97-a3aab1f94f10.png)

是因为我在处理图片的时候在compose中使用了to_tensor 吗， 如果是那么to_tensor应该如何写呢？

似乎是只能检测到一块gpu的问题？ 两个进程中的device id 都是 0

**Comment by bjjwwang** [comment]
好的 收到 我请教下专业开发者

**Comment by Costwen** [comment]
看起来感觉像是 数据都被丢到了第一张卡上面 没有使用第二张卡
