### ISSUE TITLE
有些模型多线程预测存在内存泄露

### ISSUE THREAD

**Issue by gp1322719830** [PaddlePaddle/Paddle#32442]
为使您的问题得到快速解决，在建立Issue前，请您先通过如下方式搜索是否有相似问题:【搜索issue关键字】【使用labels筛选】【官方文档】

如果您没有查询到相似问题，为快速解决您的提问，建立issue时请提供如下细节信息：
- 标题：简洁、精准描述您的问题，例如“最新预测库的API文档在哪儿 ”
- 版本、环境信息：
    1）PaddlePaddle版本：1.6 C++
    3）GPU：cuda10.1，cudnn7.5
    4）系统环境：
-预测信息
    1）C++预测：请您提供预测库安装包的版本信息，及其中的version.txt文件
- 复现信息：如为报错，请给出复现环境、复现步骤
- 问题描述：请详细描述您的问题，同步贴出报错信息、日志/代码关键片段
#include <iostream>
#include <paddle_inference_api.h>
#include <thread>
#include <vector>
#include <functional>
#include <algorithm>
#include <unistd.h>
#include <sys/time.h>
#include <cstring>
#include <memory>
#include <numeric>

using namespace std;
using paddle::AnalysisConfig;

typedef std::vector<std::thread*> Threads;

static inline unsigned long get_cur_time(void)
{
    struct timespec tm;

    clock_gettime(CLOCK_MONOTONIC, &tm);

    return (tm.tv_sec * 1000000 + tm.tv_nsec / 1000);
}

int channels = 3;
int height = 224;
int width = 224;
int input_num = channels * height * width * 1;
float *input = new float[input_num];

int mobilenetv1(std::unique_ptr<paddle::PaddlePredictor>& pdl_predictor) 
{
    unsigned long start_time = get_cur_time();

    auto input_names = pdl_predictor->GetInputNames();
    auto input_t = pdl_predictor->GetInputTensor(input_names[0]);
    input_t->Reshape({1, channels, height, width});
    input_t->copy_from_cpu(input);

    pdl_predictor->ZeroCopyRun();

    std::vector<float> out_data;
    auto output_names = pdl_predictor->GetOutputNames();
    auto output_t = pdl_predictor->GetOutputTensor(output_names[0]);
    std::vector<int> output_shape = output_t->shape();
    int out_num = std::accumulate(output_shape.begin(), output_shape.end(), 1, std::multiplies<int>());

    out_data.resize(out_num);
    output_t->copy_to_cpu(out_data.data());
    
    std::cout << "<<<<<<<<<<<<mobilenetv1<<<<<<<<<<<<<<<<\n";
    unsigned long end_time = get_cur_time();
    unsigned long off_time = end_time - start_time;
    std::cout << "used " << 1.0f * off_time/1000000/100 << "s" << std::endl;
    
    return 0;
}

int get_pdl_predictor(std::string& model_dir, std::unique_ptr<paddle::PaddlePredictor>& pdl_predictor)
{
    paddle::AnalysisConfig pdl_config;
    pdl_config.SetModel(model_dir + "/model", model_dir + "/params");
    pdl_config.EnableUseGpu(100, 0);
    pdl_config.SwitchUseFeedFetchOps(false);
    pdl_config.EnableMemoryOptim();
    pdl_config.SwitchIrOptim(false);
    pdl_predictor = paddle::CreatePaddlePredictor(pdl_config);

    return 0;
}

int main(int argc, char** argv)
{
    std::unique_ptr<paddle::PaddlePredictor> pdl_predictor;
    std::string model_dir = "../mobilenetv1";
    get_pdl_predictor(model_dir, pdl_predictor);
    memset(input, 0, input_num * sizeof(float));

    for(int i = 0; i < 2000000; i++)
    {
        std::thread task(mobilenetv1, std::ref(pdl_predictor));
        task.join();
    }

    pdl_predictor.release();

    return 0;
}

**Comment by shangzhizhou** [comment]
您好，PaddlePredictor不是线程安全的，不能同时被多个线程调用

**Comment by gp1322719830** [comment]
我这边是一个线程反复调用，不是多个线程同时调用。demo中mobilenetv1是不存在内存泄露的，我这边遇到了内存泄露很严重的模型。

**Comment by gp1322719830** [comment]
图片流场景，循环处理图片数据，循环中模型A对应的PaddlePredictorA被线程A调用，模型B对应的PaddlePredictorB被线程B调用，完全按照官方demo来的，循环中内存不断增长，出现严重泄露
