### ISSUE TITLE
Dataloader加载缓慢问题

### ISSUE THREAD

**Issue by sjhsjn1017** [PaddlePaddle/Paddle#32454]
- 版本、环境信息：
    1）PaddlePaddle版本：2.02paddle_gpu
    3）GPU：GPU:Tesla T4 ，CUDA Version 11.0.2  CUDNN版本号:7.6
    4）系统环境：ubuntu18.04
- 模型信息
- 问题描述：在使用paddle进行论文复现时发现训练速度比pytorch版本代码慢了2倍左右,
                    通过对问题的分析和定位,发现原因极可是paddle的**Dataloader**这里对数据集的处理很慢,
                    请问有什么办法能使Dataloader的速度快一些吗?
                    下面给出在相同的环境(google colab的虚拟环境)下, 相同的数据集处理操作的速度对比:

paddle版本代码:

```
import paddle
from paddle.io import Dataset
import numpy as np

class TSP(object):

    # 创建数据集
    @staticmethod
    def make_dataset(*args, **kwargs):
        return TSPDataset(*args, **kwargs)

## TSPDataset
class TSPDataset(Dataset):

    def __init__(self, size=20, num_samples=10000, offset=0, filename=None, distribution=None):
        super(TSPDataset, self).__init__()
        
        self.num_samples = num_samples

        # 随机生成[0, 1]均匀分布的采样
        self.data = [np.random.uniform(0.0, 1.0, (size, 2)) for i in range(num_samples)]
        self.size = len(self.data)
    def __len__(self):
        return self.size
    
    def __getitem__(self, idx):
        return self.data[idx]

# 加载数据集
dataset = TSP.make_dataset(size=20, num_samples=10000)
print(len(dataset))

dataloader = DataLoader(dataset, batch_size=1024)

for bat in tqdm(dataloader, disable=False):
    pass
```
paddle版本运行速度:
![image](https://user-images.githubusercontent.com/50991400/115672354-0e890680-a37e-11eb-84be-69b97e882ced.png)

pytroch版本代码:
```
from torch.utils.data import Dataset
import torch
import os
import pickle
from problems.tsp.state_tsp import StateTSP
from utils.beam_search import beam_search


class TSP(object):

    @staticmethod
    def make_dataset(*args, **kwargs):
        return TSPDataset(*args, **kwargs)

class TSPDataset(Dataset):
    
    def __init__(self, filename=None, size=50, num_samples=1000000, offset=0, distribution=None):
        super(TSPDataset, self).__init__()

        # Sample points randomly in [0, 1] square
        self.data = [torch.FloatTensor(size, 2).uniform_(0, 1) for i in range(num_samples)]

        self.size = len(self.data)

    def __len__(self):
        return self.size

    def __getitem__(self, idx):
        return self.data[idx]

# 加载数据集
dataset = TSP.make_dataset(size=20, num_samples=10000)
print(len(dataset))

dataloader = DataLoader(dataset, batch_size=1024)
for bat in tqdm(dataloader, disable=False):
    pass

```
pytoch版本运行速度:
![image](https://user-images.githubusercontent.com/50991400/115672811-80f9e680-a37e-11eb-9e33-fc2279f5d0c0.png)

如上, 运行多次, 结果都是paddle的dataloader的速度比pytoch慢2倍左右, 后面也测试了官网给的数据集的例子, 得到的结果是一样的, 而且还有一个问题, 就是如果生成的数据集是用**paddle的tensor, 速度会更慢**, 因此上面paddle版本的代码的数据集里我用的是**numpy**生成的.

请问这是paddle框架的原因吗?有什么办法可以提升Dataloader的速度吗?

**Comment by bjjwwang** [comment]
收到

**Comment by sjhsjn1017** [comment]
> 收到

大佬您好,
今天我折腾了半天, 对比了下paddle和pytorch的在Dataloader这块的源码,  当然并不是所有的代码都看懂了, 但是我自己尝试把dataloader组装成batch的主要代码给扣了出来测试分析了一下, 我在同样的环境下把抽出来的dataloader的代码(这里抽出来的只涉及组装batch的操作,不涉及转换成Tensor)
1.  首先我只用numpy生成了数据,  不做tensor的操作, 这个时候速度当然是一样的
2.  然后我在dataloder里分别加上了转换为Tensor的操作,  这个时候paddle就比pytorch慢很多了, 于是我大胆假设, 影响速度的就是Tensor, 不管是做什么操作,然后我做了下面的简单实验
![image](https://user-images.githubusercontent.com/50991400/115856669-5c297000-a45f-11eb-9839-7b0b374c55b5.png)
同样功能的操作, 速度居然差这么多....

这应该是框架实现的问题吧...
麻烦大佬给我指点迷津,  最近在准备做小论文的实验, 想用paddle做

**Comment by sjhsjn1017** [comment]
@bjjwwang 

大佬您好,
今天我折腾了半天, 对比了下paddle和pytorch的在Dataloader这块的源码, 当然并不是所有的代码都看懂了, 但是我自己尝试把dataloader组装成batch的主要代码给扣了出来测试分析了一下, 我在同样的环境下把抽出来的dataloader的代码(这里抽出来的只涉及组装batch的操作,不涉及转换成Tensor)

首先我只用numpy生成了数据, 不做tensor的操作, 这个时候速度当然是一样的
然后我在dataloder里分别加上了转换为Tensor的操作, 这个时候paddle就比pytorch慢很多了, 于是我大胆假设, 影响速度的就是Tensor, 不管是做什么操作,然后我做了下面的简单实验
image
同样功能的操作, 速度居然差这么多....
这应该是框架实现的问题吧...
麻烦大佬给我指点迷津, 最近在准备做小论文的实验, 想用paddle做

**Comment by bjjwwang** [comment]
好的 我问到相关开发者的解释是  可以调大num_of_workers试下，不过根源问题是numpy转tensor慢，会先内部讨论是否作为需求。

**Comment by sjhsjn1017** [comment]
感谢大佬!!!
       num_workers我之前就已经试过了,  调大了之后反而更慢了, 这块没有看源码分析是什么原因,目前来看num_workers=0的时候最快而且不会出问题(我记得之前我测试过num_worker>0时如果Dataloader加载的Dataset数据预处理部分已经有了Tensor相关的操作, 就会报错, 好像有人也提了类似的issue, devleop版本好像也解决了这个问题),  不过我估计就像你说的, 根源问题还是numpy转tensor太慢了,  我觉得这是一个亟待解决的问题呀, 希望后续版本能有所优化,  不然浪费了Telsa V100这么好的显卡呀,哈哈

**Comment by zhwesky2010** [comment]
@sjhsjn1017 您好，请问做的简单实验是什么例子呢，图片这里显示没加载出来

**Comment by sjhsjn1017** [comment]
> @sjhsjn1017 您好，请问做的简单实验是什么例子呢，图片这里显示没加载出来

@zhouwei25 这几天没有登陆，回晚了不好意思。我做的简单的例子入下图：
![image](https://user-images.githubusercontent.com/50991400/119503003-17199600-bd9d-11eb-867f-5e28ef30ffd8.png)
就是在循环里分别做torch和paddle的操作，上面用的是生成tensor数据的操作，可以替换成任意其他操作，基本上速度都是相差一个数量级，也就是说并不是Dataloader的问题，问题的关键可能还是paddle和torch的Tensor的内部实现机制的问题。

**Comment by zhwesky2010** [comment]
@sjhsjn1017 您好，可否在torch.tensor加一下device=torch.device('cuda')，确认下torch是GPU Tensor，因为paddle的to_tensor实现机制是将CPU上的数据拷贝到GPU设备上，这涉及到一个较大的开销，如果torch不是GPU Tensor，则会少很大一部分拷贝开线。目前这边测试了  暂时没有发现paddle的性能问题

<img width="450" alt="infoflow 2021-08-10 19-16-43" src="https://user-images.githubusercontent.com/52485244/128858531-cc9e8f0b-f487-4c8f-9de3-de615ada5532.png">


结果为：
<img width="567" alt="infoflow 2021-08-10 19-16-25" src="https://user-images.githubusercontent.com/52485244/128858586-0e5ff412-ed83-4649-9c79-a8561077c4e6.png">

**Comment by shuzizihemu** [comment]
就是有问题。我最近复现模型也遇到这个问题了。
加载一样的数据，6W张的256*256的图像，对两个模型设置相同的参数。
发现两个模型训练的速度相差很多，pytorch版本的要5个小时左右，而Paddle的竟然要13个小时！！！
这是我不能忍受的。
我注意到，paddle默认使用gpu加载数据的。而torch是用cpu，传入model时，才送入cpu。
于是我在paddle改写的工程开头就加入set_device("cpu")，将训练验证什么的全部注释掉。结果发现根本没有性能上的提升。
torch加载图像速度300-400it/s之间，而paddle是120-160it/s之间。。。
