### ISSUE TITLE
飞桨2.0API文档中Sequential示例代码运行报错

### ISSUE THREAD

**Issue by yinyimoshushi** [PaddlePaddle/Paddle#32453]
在aistudio中运行API文档中paddle.nn.Sequential下面的示例代码报错

代码如下：
import paddle
import numpy as np
data = np.random.uniform(-1, 1, [30, 10]).astype('float32')
data = paddle.to_tensor(data)
# create Sequential with iterable Layers
model1 = paddle.nn.Sequential(
    paddle.nn.Linear(10, 1), paddle.nn.Linear(1, 2)
)
model1[0]  # access the first layer
res1 = model1(data)  # sequential execution
# create Sequential with name Layer pairs
model2 = paddle.nn.Sequential(
    ('l1', paddle.nn.Linear(10, 2)),
    ('l2', paddle.nn.Linear(2, 3))
)
model2['l1']  # access l1 layer
model2.add_sublayer('l3', paddle.nn.Linear(3, 3))  # add sublayer
res2 = model2(data)  # sequential execution

错误如下：

<ipython-input-1-afe699788b11> in <module>
     14     ('l2', paddle.nn.Linear(2, 3))
     15 )
---> 16 model2['l1']  # access l1 layer
     17 model2.add_sublayer('l3', paddle.nn.Linear(3, 3))  # add sublayer
     18 res2 = model2(data)  # sequential execution
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/container.py in __getitem__(self, name)
     71             return self.__class__(*(list(self._sub_layers.values())[name]))
     72         else:
---> 73             if name >= len(self._sub_layers):
     74                 raise IndexError('index {} is out of range'.format(name))
     75             elif name < 0 and name >= -len(self._sub_layers):
TypeError: '>=' not supported between instances of 'str' and 'int'

**Comment by bjjwwang** [comment]
好的 收到

**Comment by yinyimoshushi** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
