### ISSUE TITLE
Add interface to convert all dataset into recordio files

### ISSUE THREAD

**Issue by Yancey1989** [PaddlePaddle/Paddle#3246]
Related issue: https://github.com/PaddlePaddle/cloud/issues/268

**Comment by gongweibao** [comment]
已经有了这些？https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/v2/dataset/mnist.py#L118

**Comment by Yancey1989** [comment]
@gongweibao , I just add an interface in `paddle.v2.dataset.common', so that we can convert all dataset into RecordIO files with one line code, such as `paddle.v2.dataset.common.fetch_all_recordio(path="./dataset")`
