### ISSUE TITLE
Word Embedding这个工作应该是某种语言共同的基础工作

### ISSUE THREAD

**Issue by A-Pai** [PaddlePaddle/Paddle#32467]
Word Embedding这个工作应该是某种语言共同的基础工作，比如汉语，应该是用非常广泛、丰富的语料做出来的，形成一个库来共同使用，每个项目都来做Word Embedding，有意义吗？

**Comment by bjjwwang** [comment]
这个可能要请教模型团队了。
我问问看他们的意见

**Comment by A-Pai** [comment]
> 这个可能要请教模型团队了。
> 我问问看他们的意见

---还没有回复，一直关注中

**Comment by TCChenlong** [comment]
并不是每个场景都需要做word embedding。一些场景用广泛、丰富的语料训练出来的word embedding就可以了；但是对于一些特定的场景（医学、经济学等场景）来说，单独做word embedding，是有意义的，可以提升效果；因为这些特定场景包含了大量的专业词汇，而那份语料很可能覆盖不到，那么word embedding就不会很准确，从而影响到最终的效果；因此，针对这部分场景，做word embedding是有意义的。
