### ISSUE TITLE
SyncBatchNorm在多卡，每个卡BatchSize不一致时候，统计值有问题

### ISSUE THREAD

**Issue by Yelrose** [PaddlePaddle/Paddle#32464]
我看代码实现上，sync_batch_norm_op里面是会每台机，算局部均值，然后最终在机器之间取均值。如果每张卡BatchSize不同，统计量应该是有问题的。
https://github.com/PaddlePaddle/Paddle/blob/c48157075bb392661d9e1539ec8d37ec423efe95/paddle/fluid/operators/sync_batch_norm_op.cu.h#L93

附上Pytorch的SyncBatchNorm
https://github.com/pytorch/pytorch/blob/75024e228ca441290b6a1c2e564300ad507d7af6/torch/nn/modules/_functions.py#L38

Pytorch的实现会按照每张卡的BatchSize来统计真实的均值

**Comment by bjjwwang** [comment]
收到 谢谢 我们讨论下
