### ISSUE TITLE
“词向量Word Embedding”教程中未讲二种算法是怎样训练的？

### ISSUE THREAD

**Issue by A-Pai** [PaddlePaddle/Paddle#32461]
“词向量Word Embedding”教程中未讲二种算法是怎样训练的？
https://www.paddlepaddle.org.cn/tutorials/projectdetail/1516149
如下，没有讲训练的过程？是无指导的学习？训练到怎样算是训练好了？判别的标准是？

![QQ截图20210422174143](https://user-images.githubusercontent.com/5112397/115693407-79443d00-a392-11eb-9f1a-faefcba381f3.jpg)
![QQ截图20210422174224](https://user-images.githubusercontent.com/5112397/115693415-7b0e0080-a392-11eb-92d3-fa65d9faf2b6.jpg)

**Comment by bjjwwang** [comment]
收到 我会请教模型团队看看

**Comment by TCChenlong** [comment]
hi，使用飞桨训练Skip-gram的方法在这里有描述的：[网络训练](https://www.paddlepaddle.org.cn/tutorials/projectdetail/1516149#anchor-8)

**Comment by A-Pai** [comment]
没有讲清楚

**Comment by A-Pai** [comment]
> hi，使用飞桨训练Skip-gram的方法在这里有描述的：[网络训练](https://www.paddlepaddle.org.cn/tutorials/projectdetail/1516149#anchor-8)

训练到怎样算是训练好了？判别的标准是？
