### ISSUE TITLE
“词向量Word Embedding”教程中这句话是不是前后矛盾

### ISSUE THREAD

**Issue by A-Pai** [PaddlePaddle/Paddle#32475]
https://www.paddlepaddle.org.cn/tutorials/projectdetail/1516149
![QQ截图20210422204010](https://user-images.githubusercontent.com/5112397/115715708-ff6c7d80-a3aa-11eb-82c1-67694c29a6c1.jpg)

**Comment by bjjwwang** [comment]
好 谢谢指导 我询问下相关开发者

**Comment by wulei123456789** [comment]
您好，感谢您学习本课程。关于

> https://www.paddlepaddle.org.cn/tutorials/projectdetail/1516149
> ![QQ截图20210422204010](https://user-images.githubusercontent.com/5112397/115715708-ff6c7d80-a3aa-11eb-82c1-67694c29a6c1.jpg)


您好，感谢您使用本教程。关于您反馈的问题回复如下：

原文中：“使用上下文的词向量推理中心词，这样中心词的语义就被传递到上下文的词向量中。”这句话是不矛盾的， 以这句话为例：Pineapples are spiked and yellow.

中心词为spiked， 上下文就是：Pineapples、 are、 and、 yellow这4个词。
CBOW是使用上下文的这4个词去预测中心词，但是起初预测的时候很可能是错误的，比如使用上下文这4个单词预测出了split这个单词，这个时候肯定是预测错了的，但是后边会通过使用正确的词Spiked和split这个单词计算损失，然后反向迭代，期望后续能预测出正确的单词spiked。
计算完这个损失（损失的计算有spiked的参与）后，然后根据这个损失进行反向迭代，在这个过程中相当于是将spiked的信息传递到了上下文的词向量中。
