### ISSUE TITLE
“词向量Word Embedding”教程中“稠密张量”从何而来？

### ISSUE THREAD

**Issue by A-Pai** [PaddlePaddle/Paddle#32473]
“词向量Word Embedding”教程中“稠密张量”从何而来？
![QQ截图20210422203335](https://user-images.githubusercontent.com/5112397/115714896-342c0500-a3aa-11eb-9755-123bbea6ed8b.jpg)
https://www.paddlepaddle.org.cn/tutorials/projectdetail/1516149

**Comment by bjjwwang** [comment]
这个就是模型的权重

**Comment by wulei123456789** [comment]
> “词向量Word Embedding”教程中“稠密张量”从何而来？
> ![QQ截图20210422203335](https://user-images.githubusercontent.com/5112397/115714896-342c0500-a3aa-11eb-9755-123bbea6ed8b.jpg)
> https://www.paddlepaddle.org.cn/tutorials/projectdetail/1516149

您好，感谢您使用本教程。

稠密向量就是Embedding lookup table， 教程中图3，每个单词对应一行，每一行有若干元素。 

稠密向量通常有两种方式获取：
	0.	使用word2vec等词向量训练算法，提前训练出来词表中对应的所有词的词向量，然后用这训练后的结果，组装出词表对应的词向量矩阵，就是这个稠密矩阵。
	0.	假设在模型训练之前，你有n个单词，每个单词你想设定为d维度，那你可以自行初始化一个shape为[n, d]的矩阵，这个矩阵是一个可学习的参数，随着你训练过程进行，这个矩阵会不断更新。
