### ISSUE TITLE
参数相关

### ISSUE THREAD

**Issue by songsong-L** [PaddlePaddle/Paddle#32489]
源码中梯度裁剪是这样的：
根据**self._grad_clip(params_grads)**
然后用**layers.clip**这个**op**完成裁剪
这些操作都是封装在优化器内部的。

那么问题来了，现在实现一个类似梯度裁剪的功能（**op**），处理后的数据我怎么放到优化器里面去完成后续的操作？

**Comment by hong19860320** [comment]
是不是可以参照https://github.com/PaddlePaddle/Paddle/blob/78eff52136ec9d840fc015f41534915fadeb5349/python/paddle/fluid/clip.py#L152  设计自定义的clip，然后设置到optimizer里面？

**Comment by songsong-L** [comment]
> 是不是可以参照
> 
> https://github.com/PaddlePaddle/Paddle/blob/78eff52136ec9d840fc015f41534915fadeb5349/python/paddle/fluid/clip.py#L152
> 
> 设计自定义的clip，然后设置到optimizer里面？

这不是废话吗，问的就是怎么放到里面去？

**Comment by hong19860320** [comment]
> Paddle/python/paddle/fluid/clip.py

你需要的是这个吗？https://github.com/PaddlePaddle/Paddle/blob/78eff52136ec9d840fc015f41534915fadeb5349/python/paddle/fluid/clip.py#L214
https://github.com/PaddlePaddle/Paddle/blob/78eff52136ec9d840fc015f41534915fadeb5349/python/paddle/fluid/clip.py#L231

在optimizer的grad_clip参数设置 https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/optimizer/optimizer/Optimizer_cn.html#optimizer
https://github.com/PaddlePaddle/Paddle/blob/78eff52136ec9d840fc015f41534915fadeb5349/python/paddle/fluid/tests/unittests/test_dist_fleet_base.py#L141
