### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by www516717402** [PaddlePaddle/Paddle#32502]
Issue里面结束的问题能关闭不？稍微管理一下

**Comment by hong19860320** [comment]
一般是用户完全没有问题后自己关闭的，或者对于用户长时间没有回复的issue也会定期自动关闭的哈~

**Comment by www516717402** [comment]
个人只是建议，采不采纳看你们。2017年的issue（BUG）居然还open，不像一个大的repo.
