### ISSUE TITLE
“THUNews文本分类比赛”是不是没写完？

### ISSUE THREAD

**Issue by A-Pai** [PaddlePaddle/Paddle#32508]
“THUNews文本分类比赛”是不是没写完？不能运行 啊
https://www.paddlepaddle.org.cn/tutorials/projectdetail/1515749

**Comment by wulei123456789** [comment]
同学您好，感谢您学习《零基础实践》深度学习，您看到的THUnews文本分类是本课程的一节比赛，需要开发者基于已经学习到的内容自行补全代码，因为无法直接跑通。
