### ISSUE TITLE
无法运行，libstdc++错误

### ISSUE THREAD

**Issue by cole-dda** [PaddlePaddle/Paddle#32518]
最新版本安装后，无法运行。

ubuntu14.04

<img width="1213" alt="screenshot_4234" src="https://user-images.githubusercontent.com/1077830/115980354-bbea5d00-a5be-11eb-9c7f-3f6e52c6af5e.png">

但是机器上是安装有的
<img width="489" alt="screenshot_4235" src="https://user-images.githubusercontent.com/1077830/115980383-e3412a00-a5be-11eb-936c-36884f393b37.png">

**Comment by zhupengyang** [comment]
尝试下修改 LD_LIBRARY_PATH 指向正确的库路径。

或者按照[文档](https://www.paddlepaddle.org.cn/install/quick?docurl=/documentation/docs/zh/install/compile/linux-compile.html)在机器上直接编译paddle。

**Comment by cole-dda** [comment]
不行，直接使用ubuntu18.04了。paddle的安装确实太耗费时间了，是否可以在多一些环境下测试，每次部署都非常头疼。
