### ISSUE TITLE
报错Cannot open .\model_dir/steps1_133.ckpt to write at (D:\1.6.3\paddle\paddle/fluid/operators/save_combine_op.h:51)   [operator < save_combine > error]

### ISSUE THREAD

**Issue by HUI587** [PaddlePaddle/Paddle#32514]
paddlepaddle 1.6.3
CPU
python版本：anaconda3（python3.7）
问题说明：《世界冠军带你从零实践强化学习》课程中实现四轴飞行器悬停控制中使用pycharm运行代码报错。
**代码：**
import os
import numpy as np

import parl
from parl import layers
from paddle import fluid
from parl.utils import logger
from parl.utils import action_mapping # 将神经网络输出映射到对应的 实际动作取值范围 内
from parl.utils import ReplayMemory # 经验回放

from rlschool import make_env  # 使用 RLSchool 创建飞行器环境

######################################################################
######################################################################
#
# 1. 请设定 learning rate，尝试增减查看效果
#
######################################################################
######################################################################
ACTOR_LR = 0.0002   # Actor网络更新的 learning rate
CRITIC_LR = 0.001   # Critic网络更新的 learning rate

GAMMA = 0.99        # reward 的衰减因子，一般取 0.9 到 0.999 不等
TAU = 0.001         # target_model 跟 model 同步参数 的 软更新参数
MEMORY_SIZE = 1e6   # replay memory的大小，越大越占用内存
MEMORY_WARMUP_SIZE = 1e4      # replay_memory 里需要预存一些经验数据，再从里面sample一个batch的经验让agent去learn
REWARD_SCALE = 0.01       # reward 的缩放因子
BATCH_SIZE = 256          # 每次给agent learn的数据数量，从replay memory随机里sample一批数据出来
TRAIN_TOTAL_STEPS = 1e6   # 总训练步数
TEST_EVERY_STEPS = 1e4    # 每个N步评估一下算法效果，每次评估5个episode求平均reward

class ActorModel(parl.Model):
    def __init__(self, act_dim):
        ######################################################################
        ######################################################################
        #
        # 2. 请配置model结构
        #
        hid_size = 100
        self.fc1 = layers.fc(size=hid_size, act='relu')
        self.fc2 = layers.fc(size=act_dim, act='tanh')
        ######################################################################
        ######################################################################

    def policy(self, obs):
        ######################################################################
        ######################################################################
        #
        # 3. 请组装policy网络
        #
        hid = self.fc1(obs)
        logits = self.fc2(hid)
        ###########################

**报错信息：**

D:\ProgramData\Anaconda3\python.exe D:/PycharmProjects/DDPG/DDPG.py
[04-25 10:08:21 MainThread @logger.py:224] Argv: D:/PycharmProjects/DDPG/DDPG.py
D:\ProgramData\Anaconda3\lib\importlib\_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)
[04-25 10:08:22 MainThread @machine_info.py:88] Cannot find available GPU devices, using CPU now.
[04-25 10:08:22 MainThread @machine_info.py:88] Cannot find available GPU devices, using CPU now.
[04-25 10:08:22 MainThread @machine_info.py:88] Cannot find available GPU devices, using CPU now.
['fc.b_0', 'fc.w_0', 'fc.b_1', 'fc.w_1']
[04-25 10:08:34 MainThread @DDPG.py:255] Steps 133, Test reward: -774.2192315052373
D:\ProgramData\Anaconda3\lib\site-packages\paddle\fluid\executor.py:779: UserWarning: The following exception is not an EOF exception.
  "The following exception is not an EOF exception.")
Traceback (most recent call last):
  File "D:/PycharmProjects/DDPG/DDPG.py", line 259, in <module>
    agent.save(ckpt)
  File "D:\ProgramData\Anaconda3\lib\site-packages\parl\core\fluid\agent.py", line 162, in save
    filename=filename)
  File "D:\ProgramData\Anaconda3\lib\site-packages\paddle\fluid\io.py", line 339, in save_params
    filename=filename)
 File "D:\ProgramData\Anaconda3\lib\site-packages\paddle\fluid\io.py", line 230, in save_vars
    filename=filename)
  File "D:\ProgramData\Anaconda3\lib\site-packages\paddle\fluid\io.py", line 270, in save_vars
    executor.run(save_program)
  File "D:\ProgramData\Anaconda3\lib\site-packages\paddle\fluid\executor.py", line 780, in run
    six.reraise(*sys.exc_info())
  File "D:\ProgramData\Anaconda3\lib\site-packages\six.py", line 703, in reraise
    raise value
  File "D:\ProgramData\Anaconda3\lib\site-packages\paddle\fluid\executor.py", line 775, in run
    use_program_cache=use_program_cache)
  File "D:\ProgramData\Anaconda3\lib\site-packages\paddle\fluid\executor.py", line 822, in _run_impl
    use_program_cache=use_program_cache)
  File "D:\ProgramData\Anaconda3\lib\site-packages\paddle\fluid\executor.py", line 899, in _run_program
    fetch_var_name)
paddle.fluid.core_avx.EnforceNotMet: 

--------------------------------------------
C++ Call Stacks (More useful to developers):
--------------------------------------------
Windows not support stack backtrace yet.

------------------------------------------
Python Call Stacks (More useful to users):
------------------------------------------
  File "D:\ProgramData\Anaconda3\lib\site-packages\paddle\fluid\framework.py", line 2488, in append_op
    attrs=kwargs.get("attrs", None))
  File "D:\ProgramData\Anaconda3\lib\site-packages\paddle\fluid\io.py", line 268, in save_vars
    attrs={'file_path': os.path.join(save_dirname, filename)})
  File "D:\ProgramData\Anaconda3\lib\site-packages\paddle\fluid\io.py", line 230, in save_vars
    filename=filename)
  File "D:\ProgramData\Anaconda3\lib\site-packages\paddle\fluid\io.py", line 339, in save_params
    filename=filename)
  File "D:\ProgramData\Anaconda3\lib\site-packages\parl\core\fluid\agent.py", line 162, in save
    filename=filename)
  File "D:/PycharmProjects/DDPG/DDPG.py", line 259, in <module>
    agent.save(ckpt)
----------------------
Error Message Summary:
----------------------
Error: Cannot open .\model_dir/steps1_133.ckpt to write at (D:\1.6.3\paddle\paddle/fluid/operators/save_combine_op.h:51)
  [operator < save_combine > error]

Process finished with exit code 1

**Comment by zhupengyang** [comment]
保存前请删除原来的文件

**Comment by HUI587** [comment]
您好，可以具体点吗（保存前删除原来的文件），我第一次运行的时候也是这样的错误

**Comment by zhupengyang** [comment]
```.\model_dir``` 这个路径确认是存在的么

**Comment by HUI587** [comment]
这个路径不存在的，找不到这个路径




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/Paddle"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年4月25日(星期天) 下午4:15
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PaddlePaddle/Paddle] 报错Cannot open .\model_dir/steps1_133.ckpt to write at (D:\1.6.3\paddle\paddle/fluid/operators/save_combine_op.h:51)   [operator < save_combine &gt; error] (#32514)





 
.\model_dir 这个路径确认是存在的么

**Comment by zhupengyang** [comment]
请提前创建该路径

> 这个路径不存在的，找不到这个路径
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "PaddlePaddle/Paddle" ***@***.***&gt;; 发送时间:&nbsp;2021年4月25日(星期天) 下午4:15 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [PaddlePaddle/Paddle] 报错Cannot open .\model_dir/steps1_133.ckpt to write at (D:\1.6.3\paddle\paddle/fluid/operators/save_combine_op.h:51) [operator < save_combine &gt; error] (#32514) .\model_dir 这个路径确认是存在的么 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by HUI587** [comment]
是在Anaconda3\Lib\site-packages\paddle\fluid这个文件夹里面创建.\model_dir吗



------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/Paddle"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年4月25日(星期天) 下午4:22
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PaddlePaddle/Paddle] 报错Cannot open .\model_dir/steps1_133.ckpt to write at (D:\1.6.3\paddle\paddle/fluid/operators/save_combine_op.h:51)   [operator < save_combine &gt; error] (#32514)





 
请提前创建该路径
  
这个路径不存在的，找不到这个路径
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "PaddlePaddle/Paddle" @.&gt;; 发送时间:&nbsp;2021年4月25日(星期天) 下午4:15 @.&gt;; @.@.&gt;; 主题:&nbsp;Re: [PaddlePaddle/Paddle] 报错Cannot open .\model_dir/steps1_133.ckpt to write at (D:\1.6.3\paddle\paddle/fluid/operators/save_combine_op.h:51) [operator < save_combine &gt; error] (#32514) .\model_dir 这个路径确认是存在的么 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by zhupengyang** [comment]
> 是在Anaconda3\Lib\site-packages\paddle\fluid这个文件夹里面创建.\model_dir吗

这个需要看你代码是怎么写的了，应该是你代码里面指定的
