### ISSUE TITLE
运行单机多卡demo报错

### ISSUE THREAD

**Issue by Brin333** [PaddlePaddle/Paddle#32534]
运行
 https://www.paddlepaddle.org.cn/documentation/docs/zh/guides/02_paddle2.0_develop/06_device_cn.html
中的demo
![image](https://user-images.githubusercontent.com/77146304/115992169-d6dcc180-a5fe-11eb-8057-cad4028589dc.png)
----------------------------------
![image](https://user-images.githubusercontent.com/77146304/115992177-dfcd9300-a5fe-11eb-860b-361c3742789c.png)

**Comment by sandyhouse** [comment]
请贴一下各个卡的日志吧，类似/log/workerlog.0

**Comment by Brin333** [comment]
已经解决，dist.init_parallel_env放在网络定义前面。
谢谢
