### ISSUE TITLE
编译版本始终为0.0.0

### ISSUE THREAD

**Issue by dibaozhongwei** [PaddlePaddle/Paddle#32586]
我已经在windows和Unbutu按照文档所述步骤进行编译，但编译后Paddle版本始终为0.0.0是怎么回事？

**Comment by LielinJiang** [comment]
develop的paddle的版本就是0.0.0

**Comment by dibaozhongwei** [comment]
release/2.0版本
我只有第一次2.0rc1编译成功了，develop，2.0都是0.0.0
cmake ..后提示的版本号就是0.0.0
paddle自己无所谓，使用上是正常的，但使用paddlehub的时候提示paddle必须是2.0以上版本

**Comment by LielinJiang** [comment]
export PADDLE_VERSION=你想要的版本号 试试。
或者修改https://github.com/PaddlePaddle/Paddle/blob/develop/cmake/version.cmake 这个文件试试

**Comment by chccc1994** [comment]
能不能出个编译博客，编译一直出问题。
