### ISSUE TITLE
GPU，EnforceNotMet崩溃问题，麻烦给解决一下呢，一直没法使用gpu做推理，很严重的问题，没法gpu部署。

### ISSUE THREAD

**Issue by xinsuinizhuan** [PaddlePaddle/Paddle#32602]
为使您的问题得到快速解决，在建立Issue前，请您先通过如下方式搜索是否有相似问题:【搜索issue关键字】【使用labels筛选】【官方文档】

如果您没有查询到相似问题，为快速解决您的提问，建立issue时请提供如下细节信息：
- 标题：简洁、精准描述您的问题，例如“最新预测库的API文档在哪儿 ”
- 版本、环境信息：
    1）PaddlePaddle版本：2.0.2和2.0.1 cuda10.1_cudnn7_avx_mkl_trt6官网预测库
    2）GPU：cuda_10.1.243_426.00_win10 cudnn-10.1-windows10-x64-v7.6.2.24
    3）系统环境：window10专业版
-预测信息
    1）C++预测：2.0.2和2.0.1 cuda10.1_cudnn7_avx_mkl_trt6官网预测库 
              GIT COMMIT ID: ffa88c31c2da5090c6f70e8e9b523356d7cd5e7f
              WITH_MKL: ON
              WITH_MKLDNN: ON
              WITH_GPU: ON
              CUDA version: 10.1
              CUDNN version: v7.6
              CXX compiler version: 19.0.24215.1
              WITH_TENSORRT: ON
              TensorRT version: v6
    2）预测库来源：官网下载
- 复现信息：cpp里面下载cpp文件，然后封装为dll，使用gpu的库进行编译
- 问题描述：使用MFC的demo调用封装好的dll，启动时，即崩溃。（使用cpu版本预测库，正常）
![图片](https://user-images.githubusercontent.com/40679769/116178186-ace2e680-a747-11eb-8925-464e6cba651e.png)

**Comment by jiweibo** [comment]
预测API文档可以在这里查看：https://paddle-inference.readthedocs.io/en/latest/api_reference/cxx_api_index.html

windows上的报错，目前没有给出具体哪句话挂掉了，排查方法

1、cpu版本正常，gpu挂掉，确认下不是gpu环境问题。
2、确认下环境的cuda cudnn trt版本和下载预测库对应的依赖版本一致。
3、调试下demo，看下挂到了哪句话上，是不是因为输入设置等问题导致。
4、demo bin文件运行的时候需要相关dll的依赖，可以把需要的dll都拷贝到demo bin文件的当前目录

如果还有问题，请随时留言

**Comment by zhaop-l** [comment]
mark 一下，我也是这个问题。同样的环境，同样的cuda10.1。
![image](https://user-images.githubusercontent.com/50993924/116250552-65d50f80-a7a0-11eb-98ab-fbafd2799346.png)

**Comment by xinsuinizhuan** [comment]
> 
> 
> 预测API文档可以在这里查看：https://paddle-inference.readthedocs.io/en/latest/api_reference/cxx_api_index.html
> 
> windows上的报错，目前没有给出具体哪句话挂掉了，排查方法
> 
> 1、cpu版本正常，gpu挂掉，确认下不是gpu环境问题。
> 2、确认下环境的cuda cudnn trt版本和下载预测库对应的依赖版本一致。
> 3、调试下demo，看下挂到了哪句话上，是不是因为输入设置等问题导致。
> 4、demo bin文件运行的时候需要相关dll的依赖，可以把需要的dll都拷贝到demo bin文件的当前目录
> 
> 如果还有问题，请随时留言

更换了，cuda11.0版本的库和cudnn版本库，同样更换了预测库版本为11.0，问题依然存在。应该是依赖问题，但是，我已经把预测库下面的所有dll，放到了我的可执行目录下面了，还是崩溃，因为我的程序貌似还没启动就出问题了，在程序入口处打了断点，直接不进，就崩溃。 楼上这位同学也出现了同样的问题。
![图片](https://user-images.githubusercontent.com/40679769/116635299-fd995000-a990-11eb-9243-9757acc444de.png)

**Comment by xinsuinizhuan** [comment]
> 
> 
> 预测API文档可以在这里查看：https://paddle-inference.readthedocs.io/en/latest/api_reference/cxx_api_index.html
> 
> windows上的报错，目前没有给出具体哪句话挂掉了，排查方法
> 
> 1、cpu版本正常，gpu挂掉，确认下不是gpu环境问题。
> 2、确认下环境的cuda cudnn trt版本和下载预测库对应的依赖版本一致。
> 3、调试下demo，看下挂到了哪句话上，是不是因为输入设置等问题导致。
> 4、demo bin文件运行的时候需要相关dll的依赖，可以把需要的dll都拷贝到demo bin文件的当前目录
> 
> 如果还有问题，请随时留言

感觉是gpu库内存分配的问题，我使用方式是：
typedef struct _XXXTask {
	DBDetector*						pOcrDetect;					//ocr检测网络
	Classifier*						pangleclassifier;			//方向检测
	CRNNRecognizer*					pOcrRecog;					//ocr识别网络	
	_PPDypraghOcrTask() {
		pOcrDetect = NULL;
		pangleclassifier = NULL;
		pOcrRecog = NULL;
	}
}XXXTask;
OCR三个检测类，申明了类指针，然后new的每个类，初始化的模型。

**Comment by xinsuinizhuan** [comment]
![图片](https://user-images.githubusercontent.com/40679769/116638334-bb740c80-a998-11eb-8bef-14d3e1872460.png)
这些事例运行，都是正常的

**Comment by xinsuinizhuan** [comment]
同样的，我使用gpu的预测库，只是简单的demo测试，同样的问题（cpu版本没有问题）：
![图片](https://user-images.githubusercontent.com/40679769/116642143-c0d55500-a9a0-11eb-900c-d637010eb38c.png)
![图片](https://user-images.githubusercontent.com/40679769/116642223-e4989b00-a9a0-11eb-8a94-88e5d518c0a8.png)

**Comment by zhaop-l** [comment]
我安装了TensorRT 解决了问题

**Comment by xinsuinizhuan** [comment]
> 
> 
> 我安装了TensorRT 解决了问题

怎么安装的？我怎么安装后，推理的时候，还报错？
![图片](https://user-images.githubusercontent.com/40679769/116646297-46113780-a9aa-11eb-8941-92770db8117d.png)

**Comment by xinsuinizhuan** [comment]
> 
> 
> 我安装了TensorRT 解决了
我也是安装后，启动没问题，但是推理的时候，有崩溃，您那边有这问题吗？可否加个微信，xinsuinizhuan

**Comment by xinsuinizhuan** [comment]
使用GPU，EnforceNotMet崩溃问题，麻烦给解决一下呢，一直没法使用gpu做推理，很严重的问题，没法gpu部署。

**Comment by littletomatodonkey** [comment]
要不先试下下面的demo，看下能否正常运行吧，先排除下环境问题

https://github.com/PaddlePaddle/PaddleClas/blob/release%2F2.1/deploy/cpp_infer/readme.md

**Comment by xinsuinizhuan** [comment]
> 
> 
> 要不先试下下面的demo，看下能否正常运行吧，先排除下环境问题
> 
> https://github.com/PaddlePaddle/PaddleClas/blob/release%2F2.1/deploy/cpp_infer/readme.md

opencv是自己编译的。剩下的就是按照这个demo走的，就是cpu可以，gpu在EnforceNotMet崩溃。

**Comment by jiweibo** [comment]
> > 要不先试下下面的demo，看下能否正常运行吧，先排除下环境问题
> > https://github.com/PaddlePaddle/PaddleClas/blob/release%2F2.1/deploy/cpp_infer/readme.md
> 
> opencv是自己编译的。剩下的就是按照这个demo走的，就是cpu可以，gpu在EnforceNotMet崩溃。

您要不先试一下，使用不带trt的windows gpu库，从跑下demo呢，怀疑是没找到对应版本的trt挂了出来

**Comment by xinsuinizhuan** [comment]
> 
> 
> > > 要不先试下下面的demo，看下能否正常运行吧，先排除下环境问题
> > > https://github.com/PaddleP10.0addle/PaddleClas/blob/release%2F2.1/deploy/cpp_infer/readme.md
> > 
> > 
> > opencv是自己编译的。剩下的就是按照这个demo走的，就是cpu可以，gpu在EnforceNotMet崩溃。
> 
> 您要不先试一下，使用不带trt的windows gpu库，从跑下demo呢，怀疑是没找到对应版本的trt挂了出来

试过的。刚开始使用的是10.1带trt的，后面后换成了10.0不带trt的，仍然不行。就在在这个EnforceNotMet崩溃。

**Comment by xinsuinizhuan** [comment]
> 
> 
> > > 要不先试下下面的demo，看下能否正常运行吧，先排除下环境问题
> > > https://github.com/PaddlePaddle/PaddleClas/blob/release%2F2.1/deploy/cpp_infer/readme.md
> > 
> > 
> > opencv是自己编译的。剩下的就是按照这个demo走的，就是cpu可以，gpu在EnforceNotMet崩溃。
> 
> 您要不先试一下，使用不带trt的windows gpu库，从跑下demo呢，怀疑是没找到对应版本的trt挂了出来.
刚是了cuda10 不带trt版本，现在又换成了cuda10.1 带rt的，崩溃后，继续执行，报这个错，堆栈溢出：
![图片](https://user-images.githubusercontent.com/40679769/120212458-99ee9500-c264-11eb-9f21-f00eb0654bb1.png)

**Comment by xinsuinizhuan** [comment]
https://www.cnblogs.com/dzqiu/p/9518190.html

**Comment by xinsuinizhuan** [comment]
https://blog.csdn.net/PaddlePaddle/article/details/86739880

**Comment by xinsuinizhuan** [comment]
0x00007FFA0CAB62D1 (paddle_inference.dll)处(位于 xxx.exe 中)引发的异常: 0xC0000005: 读取位置 0x0000000000000000 时发生访问冲突。

**Comment by xinsuinizhuan** [comment]
PaddlePaddle运行时出现EnforceNotMet: Enforce failed错误:


    问题解决
    PaddlePaddle的label要从0开始递增。

def getdata():
    def reader():
        for i in range(len(data_y)):
            yield np.array(data_X[i]).astype('float32'), np.array(data_y[i]- 3).astype('int64')
    return reader
 这是在哪里改？
