### ISSUE TITLE
paddle1.8训练的模型 2.0如何加载 ?

### ISSUE THREAD

**Issue by lonelydancer** [PaddlePaddle/Paddle#32609]
1.8的格式和2.0的格式不一样，看了api没有发现便捷的转换方式。

**Comment by hbwx24** [comment]
您好，请问1.8使用了哪个API，怎么保存的呢，方便的话可以提供一下保存模型的代码吗？

**Comment by hbwx24** [comment]
> 1.8的格式和2.0的格式不一样，看了api没有发现便捷的转换方式。

您好，请问1.8使用了哪个API，怎么保存的呢，方便的话可以提供一下保存模型的代码吗？

**Comment by lonelydancer** [comment]
1.8使用的paddle.fluid.io.save_inference_model，保存格式是__model__,很多参数文件格式的；
2.0对应的是paddle.static.load_inference_model，要求model结构是*.pdmodel和*.pdiparams

**Comment by hbwx24** [comment]
这里有个教程：https://www.paddlepaddle.org.cn/documentation/docs/zh/guides/02_paddle2.0_develop/08_model_save_load_cn.html#paddle-fluid-io-save-inference-model
如果不能解决的话，不知道是否方便上传模型，或者保存模型的示例代码，我这边可以写一个加载模型的示例代码。

**Comment by lonelydancer** [comment]
好的，谢谢。我研究一下。
