### ISSUE TITLE
关于torch的安装

### ISSUE THREAD

**Issue by zcswdt** [PaddlePaddle/Paddle#32618]
您好，我拉取了官方1.85版本的镜像，在容器里面安装torch安装报错，请问这个怎么解决呢？
报错如下
![image](https://user-images.githubusercontent.com/43515926/116227042-44672a00-a786-11eb-875c-fe60f4fe0de3.png)
报错信息
`Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/python3.5.1/lib/python3.5/site-packages/torch/__init__.py", line 136, in <module>
    from torch._C import *
ImportError: /usr/local/python3.5.1/lib/python3.5/site-packages/torch/lib/libtorch_python.so: undefined symbol: _PyThreadState_UncheckedGet`

**Comment by zhiqiu** [comment]
hi，可能是python-3.5版本过低，你可以试下python3.6。参考pytroch的issue：https://github.com/pytorch/pytorch/issues/24883

**Comment by zcswdt** [comment]
> 本过低，你可以试下python3.6。参考pytr

好的，谢谢，我安装了torch1.4版本的，可以了。
