### ISSUE TITLE
使用单机多卡训练时 多卡的显存占用比单卡还高 调大batch size会超显存

### ISSUE THREAD

**Issue by sean0xiao** [PaddlePaddle/Paddle#32623]
如果您没有查询到相似问题，为快速解决您的提问，建立issue时请提供如下细节信息：
- 版本、环境信息：
    1）PaddlePaddle版本：2.0
    2）CPU：
    3）GPU：cuda10+cudnn7+nccl2.7.8
    4）系统环境：python3.7

- 训练信息
    1）单机，多卡
    2）显存信息
    3）Operator信息

- 问题描述：
   使用单机多卡训练时，增大卡数，在batchsize不变的情况下，每张卡上的显存占用反而比之前高
   是参照demo/finetune_classifier_distributed.py用法写的 求帮忙看看
   具体表现与 http://ai.baidu.com/forum/topic/show/983415一样，但是按照demo里的写法batch_sampler需要设置为None 请问该怎么解决呢
![image](https://user-images.githubusercontent.com/50003582/116238611-27395800-a794-11eb-954d-09394eda2f41.png)

**Comment by zhiqiu** [comment]
我看你给的链接里面是说 https://ai.baidu.com/forum/topic/show/983415 用DistributedBatchSampler可以解决，请问你用的是这个吗？

**Comment by TCChenlong** [comment]
你好，请问可以提供一下全部的代码，方便我们进行问题的定位么？谢谢~

**Comment by sean0xiao** [comment]
使用的是自定义的batchsampler 所以似乎不能用这种方法解决




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/Paddle"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年4月27日(星期二) 晚上8:42
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PaddlePaddle/Paddle] 使用单机多卡训练时 多卡的显存占用比单卡还高 调大batch size会超显存 (#32623)





 
我看你给的链接里面是说 https://ai.baidu.com/forum/topic/show/983415 用DistributedBatchSampler可以解决，请问你用的是这个吗？
