### ISSUE TITLE
关于paddle中的Tensor在GPU和CPU之间相互拷贝的API

### ISSUE THREAD

**Issue by hrdwsong** [PaddlePaddle/Paddle#32649]
欢迎您对PaddlePaddle提出建议，非常感谢您对PaddlePaddle的贡献！
在留下您的建议时，辛苦您同步提供如下信息：
- 版本、环境信息
1）PaddlePaddle版本：2.0.2
2）CPU/GPU：是，CUDA版本号11.1，CUDNN版本号8.1.0
3）系统环境：WIN10 20H2版
- 复现信息：无
- 建议描述：根据我的项目需要，模型参数会在计算过程中产生若干个更新梯度，这些梯度不会立刻用于更新模型，而是等待其他计算过程完成后才对这若干个梯度求和，再完成模型更新。这样就会有相当多的模型参数滞留在显存中，导致显存溢出。我希望有API能够将这些暂时不用的Tensor拷贝回CPU内存，但查阅了API文档，没找到有类似功能的函数。建议像pytorch一样，能够增加API实现tensor在CPU内存和GPU显存之间的高效拷贝，从而使算法能够更灵活地进行实现。

**Comment by DannyIsFunny** [comment]
copy_from_cpu和copy_to_cpu
相关文档：https://www.paddlepaddle.org.cn/documentation/docs/zh/guides/05_inference_deployment/inference/python_infer_cn.html#zhichifangfaliebiao
