### ISSUE TITLE
将parameters list放入Momentum 提示list没有shape的异常

### ISSUE THREAD

**Issue by Reatris** [PaddlePaddle/Paddle#32675]
我在给优化器配置parameters的时候如果使用将parameters list放入Momentum
就会提示list没有shape的异常，如果使用Adam就不会
   1）PaddlePaddle版本：paddlepaddle-gpu 2.0.2

* 异常代码段

`OPTIMIZER = optim.Momentum(parameters=[backbone_paras_wo_bn + head_paras_wo_bn,backbone_paras_only_bn],
                               learning_rate=LR)`

* 异常提示
`shape = param.shape
AttributeError: 'list' object has no attribute 'shape'`

**Comment by DDDivano** [comment]
这里面传入的parameter的内容本身是不是包括list？

**Comment by Reatris** [comment]
包括了
