### ISSUE TITLE
test_framework fails

### ISSUE THREAD

**Issue by wangkuiyi** [PaddlePaddle/Paddle#3268]
In https://paddleci.ngrok.io/viewLog.html?buildId=4618&buildTypeId=Paddle_PrCi&tab=buildLog

```
[21:26:17]	test test_protobuf.py
[21:26:17]	Traceback (most recent call last):
[21:26:17]	File "test_protobuf.py", line 2, in <module>
[21:26:17]	import paddle.v2.framework.proto.attr_type_pb2
[21:26:17]	ImportError: No module named attr_type_pb2
```

**Comment by wangkuiyi** [comment]
I merged https://github.com/PaddlePaddle/Paddle/pull/3225, which renamed attr_type.proto into attribute.proto.  I think this could be the reason of this failure.

**Comment by wangkuiyi** [comment]
I think this is because the under-testing PR https://github.com/PaddlePaddle/Paddle/pull/3249 was not merged with upstream/develop and is not in the most recent status.

**Comment by reyoung** [comment]
This has been fixed in develop branch

**Comment by wangkuiyi** [comment]
Yeah. Thanks for that fix.

But @lcy-seso 's #3249 was not merged with upstream/develop. I didn't it and pushed. Let's wait for the new CI result.
