### ISSUE TITLE
使用paddle模型推理时开启了TensorRT，但是提示：You tried to enable the lite subgraph but did not have the option -DWITH_LITE compiled，并且效果没有提升

### ISSUE THREAD

**Issue by geekChinaMaster** [PaddlePaddle/Paddle#32690]
- 版本、环境信息：
    1）PaddlePaddle版本：paddlepaddle-gpu2.0.0
    2）GPU：Nvidia 的3090
    3）系统环境：centos7
在使用paddleinference进行推理时候，开启了TensorRT，但是没有发现速度的提升，麻烦看下，谢谢~
代码配置和日志如下：
![图片](https://user-images.githubusercontent.com/44657953/116545581-34d11800-a923-11eb-859a-211a3f9202e6.png)
![图片](https://user-images.githubusercontent.com/44657953/116546230-f425ce80-a923-11eb-9e17-ba2349e17ec2.png)

W0429 07:36:49.161710 199702 analysis_config.cc:392] You tried to enable the lite subgraph but did not have the option -DWITH_LITE compiled.
W0429 07:36:49.161751 199702 analysis_config.cc:392] You tried to enable the lite subgraph but did not have the option -DWITH_LITE compiled.
Enable TensorRT is: True
Enable TensorRT OSS is: True
Lite Engine is: True
W0429 07:36:49.161870 199702 analysis_config.cc:392] You tried to enable the lite subgraph but did not have the option -DWITH_LITE compiled.
I0429 07:36:49.161890 199702 analysis_predictor.cc:139] Profiler is deactivated, and no profiling report will be generated.
I0429 07:36:49.181090 199702 analysis_predictor.cc:474] TensorRT subgraph engine is enabled
I0429 07:36:49.181124 199702 analysis_predictor.cc:498] Lite subgraph engine is enabled
--- Running analysis [ir_graph_build_pass]
--- Running analysis [ir_graph_clean_pass]
--- Running analysis [ir_analysis_pass]
I0429 07:36:49.330741 199702 ir_analysis_pass.cc:46] argument has no fuse statis
--- Running analysis [ir_params_sync_among_devices_pass]
I0429 07:36:49.338034 199702 ir_params_sync_among_devices_pass.cc:45] Sync params from CPU to GPU
--- Running analysis [adjust_cudnn_workspace_size_pass]
--- Running analysis [inference_op_replace_pass]
--- Running analysis [memory_optimize_pass]
I0429 07:36:49.526427 199702 memory_optimize_pass.cc:198] Cluster name : unsqueeze2_0.tmp_0  size: 4
I0429 07:36:49.526449 199702 memory_optimize_pass.cc:198] Cluster name : fill_constant_9.tmp_0  size: 8
I0429 07:36:49.526454 199702 memory_optimize_pass.cc:198] Cluster name : fill_constant_7.tmp_0  size: 8
I0429 07:36:49.526459 199702 memory_optimize_pass.cc:198] Cluster name : dropout_119.tmp_0  size: 12288
I0429 07:36:49.526464 199702 memory_optimize_pass.cc:198] Cluster name : transpose_29.tmp_0  size: 3072
I0429 07:36:49.526470 199702 memory_optimize_pass.cc:198] Cluster name : dropout_95.tmp_0  size: 12288
I0429 07:36:49.526475 199702 memory_optimize_pass.cc:198] Cluster name : relu_7.tmp_0  size: 12288
I0429 07:36:49.526480 199702 memory_optimize_pass.cc:198] Cluster name : dropout_76.tmp_0  size: 3072
I0429 07:36:49.526485 199702 memory_optimize_pass.cc:198] Cluster name : layer_norm_65.tmp_2  size: 3072
--- Running analysis [ir_graph_to_program_pass]
I0429 07:36:49.617156 199702 analysis_predictor.cc:547] ======= optimize end =======
I0429 07:36:49.617259 199702 naive_executor.cc:105] ---  skip [feed], feed -> input_ids
I0429 07:36:49.621824 199702 naive_executor.cc:105] ---  skip [dropout_95.tmp_0], fetch -> fetch
I0429 07:36:49.621846 199702 naive_executor.cc:105] ---  skip [dropout_119.tmp_0], fetch -> fetch
I0429 07:36:49.621853 199702 naive_executor.cc:105] ---  skip [relu_7.tmp_0], fetch -> fetch

**Comment by DannyIsFunny** [comment]
你好，你的推理代码中使用了Lite子图

Lite 子图的作用，是将部分图结构使用子图的形式使用Lite加载，可以降低推理耗时
但是使用Lite子图加载TensorRt模型必须使用带有编译时带有子图库的推理库
综上所述：
需要更换推理库或者手动编译（打开`-DWITH_LITE`编译选项）带有子图功能的tui推理库

**Comment by geekChinaMaster** [comment]
> 你好，你的推理代码中使用了Lite子图
> 
> Lite 子图的作用，是将部分图结构使用子图的形式使用Lite加载，可以降低推理耗时
> 但是使用Lite子图加载TensorRt模型必须使用带有编译时带有子图库的推理库
> 综上所述：
> 需要更换推理库或者手动编译（打开`-DWITH_LITE`编译选项）带有子图功能的tui推理库

是需要重新安装TensorRT吗，这里说的推理库和带有子图功能的推理库是指哪个
如何更换推理库呢
之前安装的是tensorrt7.2.3和8.0

**Comment by geekChinaMaster** [comment]
> > 你好，你的推理代码中使用了Lite子图
> > Lite 子图的作用，是将部分图结构使用子图的形式使用Lite加载，可以降低推理耗时
> > 但是使用Lite子图加载TensorRt模型必须使用带有编译时带有子图库的推理库
> > 综上所述：
> > 需要更换推理库或者手动编译（打开`-DWITH_LITE`编译选项）带有子图功能的tui推理库
> 
> 是需要重新安装TensorRT吗，这里说的推理库和带有子图功能的推理库是指哪个
> 如何更换推理库呢

之前使用

**Comment by geekChinaMaster** [comment]
> 你好，你的推理代码中使用了Lite子图
> 
> Lite 子图的作用，是将部分图结构使用子图的形式使用Lite加载，可以降低推理耗时
> 但是使用Lite子图加载TensorRt模型必须使用带有编译时带有子图库的推理库
> 综上所述：
> 需要更换推理库或者手动编译（打开`-DWITH_LITE`编译选项）带有子图功能的tui推理库

> 是需要重新安装TensorRT吗，这里说的推理库和带有子图功能的推理库是指哪个
> 如何更换推理库呢

之前使用的是7.2.3和8.0都试了不行

**Comment by geekChinaMaster** [comment]
> 子图

麻烦您解答一下
