### ISSUE TITLE
单机多卡训练失败

### ISSUE THREAD

**Issue by RoseSakurai** [PaddlePaddle/Paddle#32694]
版本、环境信息：
   1）PaddlePaddle版本：2.0.2
   2）GPU型号：1080Ti
CUDA版本：10.2
CUDNN版本号： 7.6
   3）系统环境：
Ubuntu 18.04
gcc 7.5.0
python 3.8.8

训练命令
```
export CUDA_VISIBLE_DEVICES=0,1
python -m paddle.distributed.launch train.py
```
报错信息
![image](https://user-images.githubusercontent.com/30227024/116563312-7e772e00-a936-11eb-9608-d25280ea831b.png)

日志报错信息
![image](https://user-images.githubusercontent.com/30227024/116562959-3526de80-a936-11eb-8de6-4725bae1edce.png)

**Comment by Liys0558** [comment]
同样的问题

**Comment by RoseSakurai** [comment]
#32693

**Comment by DannyIsFunny** [comment]
你好，从报错信息看。
你的训练代码中使用GPU进行模型训练，但是使用的Paddle 版本是CPU版本的库，通过Paddle调用GPU需要使用GPU版本的库，
![image](https://user-images.githubusercontent.com/45189361/116852637-436f4600-ac27-11eb-8193-0215fd6ae7d1.png)
建议安装GPU版本的Paddle库，重新训练

**Comment by RoseSakurai** [comment]
你们能用心写api，好好回复issue解决问题吗？我装的就是gpu版本的。------------------&nbsp;原始邮件&nbsp;------------------
***@***.***&gt;
发送时间:&nbsp;2021年5月3日(星期一) 下午3:50
***@***.***&gt;;
***@***.***&gt;;&quot;State ***@***.***&gt;;
主题:&nbsp;Re: [PaddlePaddle/Paddle] 单机多卡训练失败 (#32694)
