### ISSUE TITLE
Prevent Paddle from using all cuda cores

### ISSUE THREAD

**Issue by xxxpsyduck** [PaddlePaddle/Paddle#32734]
My GPU has 24GB of memory. When training I rarely used all the memory but cuda cores were all busy so I couldn't do another job on gpu. Do you have a solution for this?

**Comment by juncaipeng** [comment]
Use `export CUDA_VISIBLE_DEVICES=**` to set the GPU.

What is the version of the Paddle?
If you use paddle 1.6 ~ 1.8, please use [FLAGS_fraction_of_cpu_memory_to_use](https://www.paddlepaddle.org.cn/documentation/docs/zh/1.8/advanced_guide/flags/memory_cn.html#flags-fraction-of-cpu-memory-to-use) to set the memory.
