### ISSUE TITLE
动态图如何加载裁枝模型？

### ISSUE THREAD

**Issue by wzy-99** [PaddlePaddle/Paddle#32739]
在动态图模式下，我通过paddleslim对模型进行裁枝，并通过Paddle.Model.save()接口保存模型参数；但是在部署加载模型参数的时候，会出现裁枝后卷积的shape与模型定义卷积的shape不匹配的问题。如下：

blocks.0.conv_bn1.conv.weight receives a shape [31, 3, 3, 3], but the expected shape is [64, 3, 3, 3].

# [31, 3, 3, 3] 是裁枝后的shape，[64, 3, 3, 3]是原shape。

请问有什么方法可以加载裁枝模型参数？（不用skip_mismatch ）

**Comment by juncaipeng** [comment]
我理解你裁剪通道后，需要修改组网代码，再加载裁剪后的权重。

**Comment by wzy-99** [comment]
我现在是通过先加载一个完整的模型参数，然后根据灵敏度文件剪枝，再重新加载剪枝后的模型实现。
但这种方法比较麻烦。
我之前尝试过先剪枝，再加载模型，但是由于剪枝时模型缺少参数导致报错。
因此，我想问一下有没有什么API可以用于初始化paddle.Model模型参数？
另外，我发现通过paddle. Model. save保存剪枝后的模型的参数，文件体积并没有变小，100MB，但是通过summay查看网络，模型的大小只有3MB

**Comment by juncaipeng** [comment]
> API可以用于初始化paddle.Model模型参数？

通过[set_dict](https://www.paddlepaddle.org.cn/documentation/docs/zh/1.8/api_cn/dygraph_cn/Layer_cn.html#set-dict-stat-dict-include-sublayers-true)可以实现。

>另外，我发现通过paddle. Model. save保存剪枝后的模型的参数，文件体积并没有变小，100MB，但是通过summay查看网络，模型的大小只有3MB

这个问题需要裁剪同学 @wanghaoshuang  看下
