### ISSUE TITLE
载入模型、优化器报错

### ISSUE THREAD

**Issue by crazyxiaoj** [PaddlePaddle/Paddle#32738]
- 版本、环境信息：
    1）PaddlePaddle版本：2.0
    2）系统环境：AIstudio 高级版
- 模型信息
1）模型名称：all_CNN_C(自定义) 
    2）cifar-10 
    3）paddle.optimizer.Adagrad(learning_rate=schedular,parameters=model.parameters(),weight_decay=0.001)
- 复现信息：解压后的py文件，代码完全复制即可
[issue.zip](https://github.com/PaddlePaddle/Paddle/files/6420136/issue.zip)
- 问题描述：储存模型后，读取模型时优化器报错AssertionError: optimizer Tensor conv2d_0.w_0_velocity_0 not found
- 详情：
---------------------------------------------------------------------------AssertionError                            Traceback (most recent call last)<ipython-input-7-c3c70ef87055> in <module>
      4 
      5 model = all_CNN_C()
----> 6 start_train(model)
      7 
      8 print(1)
<ipython-input-5-d41f46cb467e> in start_train(model)
     37             acc = paddle.static.accuracy(predict, label)
     38             avg_loss.backward()
---> 39             opt.step()
     40             opt.clear_grad()
     41 
</opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/decorator.py:decorator-gen-319> in step(self)
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/wrapped_decorator.py in __impl__(func, *args, **kwargs)
     23     def __impl__(func, *args, **kwargs):
     24         wrapped_func = decorator_func(func)
---> 25         return wrapped_func(*args, **kwargs)
     26 
     27     return __impl__
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/framework.py in __impl__(*args, **kwargs)
    223         assert in_dygraph_mode(
    224         ), "We only support '%s()' in dynamic graph mode, please call 'paddle.disable_static()' to enter dynamic graph mode." % func.__name__
--> 225         return func(*args, **kwargs)
    226 
    227     return __impl__
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/optimizer/optimizer.py in step(self)
    921 
    922         self._apply_optimize(
--> 923             loss=None, startup_program=None, params_grads=params_grads)
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/optimizer/optimizer.py in _apply_optimize(self, loss, startup_program, params_grads)
    773                 params_grads = append_regularization_ops(params_grads,
    774                                                          self.regularization)
--> 775                 optimize_ops = self._create_optimization_pass(params_grads)
    776         else:
    777             program = loss.block.program
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/optimizer/optimizer.py in _create_optimization_pass(self, parameters_and_grads)
    595         self._create_accumulators(
    596             target_block,
--> 597             [p[0] for p in parameters_and_grads if p[0].trainable])
    598         self._create_global_learning_rate()
    599 
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/optimizer/adagrad.py in _create_accumulators(self, block, parameters)
    112                 self._moment_acc_str,
    113                 p,
--> 114                 fill_value=self.initial_accumulator_value)
    115 
    116     def _append_optimize_op(self, block, param_and_grad):
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/optimizer/optimizer.py in _add_accumulator(self, name, param, dtype, fill_value, shape, type, device)
    513             if len(self._accumulators_holder) > 0:
    514                 assert var_name in self._accumulators_holder, \
--> 515                         "Optimizer set error, {} should in state dict".format( var_name )
    516                 var.set_value(self._accumulators_holder[var_name])
    517 
AssertionError: Optimizer set error, conv2d_27.w_0_moment_0 should in state dict

**Comment by juncaipeng** [comment]
收到，我们复现一下问题。

**Comment by juncaipeng** [comment]
看了你的训练代码，逻辑是组网、训练、保存、加载、再训练，会出错。

但是一般重训练的用法是：组网、训练、保存，重新组网、加载、再训练。这样修改后，你的代码就不会出错，具体如下。

![image](https://user-images.githubusercontent.com/52520497/117257300-516ad400-ae7e-11eb-9346-74b9043d78ff.png)

第一次执行脚本时，应该只执行`start_train(model)`，训练保存。第二次执行脚本时，应该只执行`start_train2(model)`，加载训练的权重，再训练。

**Comment by crazyxiaoj** [comment]
我该如何在AIStudio中实现重新组网？我以前尝试过关闭再重新打开项目，就不会报错；但是我现在发现关闭再重新打开项目也会报错了

**Comment by crazyxiaoj** [comment]
![image](https://user-images.githubusercontent.com/50630515/117540701-fb935900-b042-11eb-9b16-3a3088b4ada9.png)
我在重启项目后仍旧出现该问题！
我应该如何进行重新组网？？
期待大家的回复！

**Comment by crazyxiaoj** [comment]
可能由于上传代码、操作说明不完整，致使问题分析错误，我将会关闭这个issue，重新进行提问
