### ISSUE TITLE
训练错误

### ISSUE THREAD

**Issue by jiamingming-004** [PaddlePaddle/Paddle#32743]
环境： AI studio  python3.7  paddle1.8
运行中： 以下代码片段的最后一行提示出现错误。
for pass_id in range(EPOCH_NUM):
        # 进行训练
        for batch_id, data in enumerate(train_loader()):  # 遍历train_reader
            feed_data= []
            for i in range(len(data[0])):
                feed_gtscores = np.ones([50]).astype("float32")
                feed_data.append([data[0][i], data[1][i], data[2][i], data[3][i], feed_gtscores])
            train_cost,train_pred_scores = exe.run(program=fluid.default_main_program(),  # 运行主程序
                                 feed=feeder.feed(feed_data),  # 给模型喂入数据
                                 fetch_list=[loss,pred_scores])  # 该变量表示模型运行之后需要返回的变量   此处出现错误

错误提示： 
 #主程序部分用运行train就是训练，运行test_and_predict就是预测
   1151 if __name__=="__main__":
-> 1152     train()   # 仅传入训练函数
   1153     # test_and_predict()
<ipython-input-3-13d6ada009c2> in train()
    923             train_cost,train_pred_scores = exe.run(program=fluid.default_main_program(),  # 运行主程序
    924                                  feed=feeder.feed(feed_data),  # 给模型喂入数据
--> 925                                  fetch_list=[loss,pred_scores])  # fetch 误差
    926             # if batch_id%10==0:print(train_pred_scores)#######################
    927             # 每1个batch打印一次信息  误差、准确率
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/executor.py in run(self, program, feed, fetch_list, feed_var_name, fetch_var_name, scope, return_numpy, use_program_cache, return_merged, use_prune)
   1069                 warnings.warn(
   1070                     "The following exception is not an EOF exception.")
-> 1071             six.reraise(*sys.exc_info())
   1072 
   1073     def _run_impl(self, program, feed, fetch_list, feed_var_name,
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/six.py in reraise(tp, value, tb)
    701             if value.__traceback__ is not tb:
    702                 raise value.with_traceback(tb)
--> 703             raise value
    704         finally:
    705             value = None
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/executor.py in run(self, program, feed, fetch_list, feed_var_name, fetch_var_name, scope, return_numpy, use_program_cache, return_merged, use_prune)
   1064                 use_program_cache=use_program_cache,
   1065                 use_prune=use_prune,
-> 1066                 return_merged=return_merged)
   1067         except Exception as e:
   1068             if not isinstance(e, core.EOFException):
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/executor.py in _run_impl(self, program, feed, fetch_list, feed_var_name, fetch_var_name, scope, return_numpy, use_program_cache, return_merged, use_prune)
   1152                 scope=scope,
   1153                 return_numpy=return_numpy,
-> 1154                 use_program_cache=use_program_cache)
   1155 
   1156         program._compile(scope, self.place)
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/executor.py in _run_program(self, program, feed, fetch_list, feed_var_name, fetch_var_name, scope, return_numpy, use_program_cache)
   1227         if not use_program_cache:
   1228             self._default_executor.run(program.desc, scope, 0, True, True,
-> 1229                                        fetch_var_name)
   1230         else:
   1231             self._default_executor.run_prepared_ctx(ctx, scope, False, False,

Error Message Summary:
----------------------
InvalidArgumentError: The 2-th dimension of input[0] and input[1] is expected to be equal.But received input[0]'s shape = [10, 256, 24, 24], input[1]'s shape = [10, 256, 48, 48].
  [Hint: Expected inputs_dims[0][j] == inputs_dims[i][j], but received inputs_dims[0][j]:24 != inputs_dims[i][j]:48.] at (/paddle/paddle/fluid/operators/concat_op.h:56)
  [operator < concat > error]

**Comment by iclementine** [comment]
形状不对。concat 的两个 Tensor 在指定的维度的 size 不等。
