### ISSUE TITLE
UserWarning: The following exception is not an EOF exception

### ISSUE THREAD

**Issue by Liushuaixin** [PaddlePaddle/Paddle#32746]
为使您的问题得到快速解决，在建立Issues前，请您先通过如下方式搜索是否有相似问题:【搜索issue关键字】【使用labels筛选】【官方文档】

如果您没有查询到相似问题，为快速解决您的提问，建立issue时请提供如下细节信息：
- 标题：简洁、精准概括您的问题，例如“Insufficient Memory xxx" ”
- 版本、环境信息：paddle-fluid-v1.6.1、python3
- 问题描述
I0429 14:24:48.579789  1108 parallel_executor.cc:421] The number of CUDAPlace, which is used in ParallelExecutor, is 4. And the Program will be copied 4 copies
W0429 14:24:54.821188  1108 fuse_all_reduce_op_pass.cc:72] Find all_reduce operators: 50. To make the speed faster, some all_reduce ops are fused during training, after fusion, the number of all_reduce ops is 31.
I0429 14:24:54.826529  1108 build_strategy.cc:363] SeqOnlyAllReduceOps:0, num_trainers:1
I0429 14:24:54.884377  1108 parallel_executor.cc:285] Inplace strategy is enabled, when build_strategy.enable_inplace = True
I0429 14:24:54.916266  1108 parallel_executor.cc:368] Garbage collection strategy is enabled, when FLAGS_eager_delete_tensor_gb = 0
/root/paddlejob/workspace/env_run/thirdparty/python36_paddlepost107/lib/python3.6/site-packages/paddle/fluid/executor.py:774: UserWarning: The following exception is not an EOF exception.
  "The following exception is not an EOF exception.")
Traceback (most recent call last):
  File "local_train.py", line 16, in <module>
    use_parallel_executor=1
  File "/root/paddlejob/workspace/env_run/train.py", line 721, in train
    train_loop(fluid.default_main_program())
  File "/root/paddlejob/workspace/env_run/train.py", line 678, in train_loop
    fetch_list=[predict.name, avg_cost.name, label.name, auc_var.name])
  File "/root/paddlejob/workspace/env_run/thirdparty/python36_paddlepost107/lib/python3.6/site-packages/paddle/fluid/parallel_executor.py", line 311, in run
    return_numpy=return_numpy)
  File "/root/paddlejob/workspace/env_run/thirdparty/python36_paddlepost107/lib/python3.6/site-packages/paddle/fluid/executor.py", line 775, in run
    six.reraise(*sys.exc_info())
  File "/root/paddlejob/workspace/env_run/thirdparty/python36_paddlepost107/lib/python3.6/site-packages/six.py", line 693, in reraise
    raise value
  File "/root/paddlejob/workspace/env_run/thirdparty/python36_paddlepost107/lib/python3.6/site-packages/paddle/fluid/executor.py", line 770, in run
    use_program_cache=use_program_cache)
  File "/root/paddlejob/workspace/env_run/thirdparty/python36_paddlepost107/lib/python3.6/site-packages/paddle/fluid/executor.py", line 829, in _run_impl
    return_numpy=return_numpy)
  File "/root/paddlejob/workspace/env_run/thirdparty/python36_paddlepost107/lib/python3.6/site-packages/paddle/fluid/executor.py", line 669, in _run_parallel
    tensors = exe.run(fetch_var_names)._move_to_list()
paddle.fluid.core_avx.EnforceNotMet: 

--------------------------------------------
C++ Call Stacks (More useful to developers):
--------------------------------------------
0   std::string paddle::platform::GetTraceBackString<char const*>(char const*&&, char const*, int)
1   paddle::platform::EnforceNotMet::EnforceNotMet(std::__exception_ptr::exception_ptr, char const*, int)
2   paddle::framework::details::OpHandleBase::InitCUDA()
3   paddle::framework::details::OpHandleBase::Run(bool)
4   paddle::framework::details::FastThreadedSSAGraphExecutor::RunOpSync(paddle::framework::details::OpHandleBase*)
5   paddle::framework::details::FastThreadedSSAGraphExecutor::RunOp(paddle::framework::details::OpHandleBase*, std::shared_ptr<paddle::framework::BlockingQueue<unsigned long> > const&, unsigned long*)
6   std::_Function_handler<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> (), std::__future_base::_Task_setter<std::unique_ptr<std::__future_base::_Result<void>, std::__future_base::_Result_base::_Deleter>, void> >::_M_invoke(std::_Any_data const&)
7   std::__future_base::_State_base::_M_do_set(std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> ()>&, bool&)
8   ThreadPool::ThreadPool(unsigned long)::{lambda()#1}::operator()() const

----------------------
Error Message Summary:
----------------------
PaddleCheckError: unspecified launch failure at [/paddle/paddle/fluid/framework/details/op_handle_base.cc:51]

terminate called after throwing an instance of 'paddle::platform::EnforceNotMet'
  what():  

--------------------------------------------
C++ Call Stacks (More useful to developers):
--------------------------------------------
0   std::string paddle::platform::GetTraceBackString<char const*>(char const*&&, char const*, int)
1   paddle::platform::EnforceNotMet::EnforceNotMet(std::__exception_ptr::exception_ptr, char const*, int)
2   paddle::framework::details::OpHandleBase::~OpHandleBase()
3   paddle::framework::details::ComputationOpHandle::~ComputationOpHandle()
4   paddle::framework::ir::Node::~Node()
5   paddle::framework::ir::Node::~Node()
6   std::_Rb_tree<paddle::framework::ir::Node*, std::pair<paddle::framework::ir::Node* const, std::unique_ptr<paddle::framework::ir::Node, std::default_delete<paddle::framework::ir::Node> > >, std::_Select1st<std::pair<paddle::framework::ir::Node* const, std::unique_ptr<paddle::framework::ir::Node, std::default_delete<paddle::framework::ir::Node> > > >, std::less<paddle::framework::ir::Node*>, std::allocator<std::pair<paddle::framework::ir::Node* const, std::unique_ptr<paddle::framework::ir::Node, std::default_delete<paddle::framework::ir::Node> > > > >::_M_erase(std::_Rb_tree_node<std::pair<paddle::framework::ir::Node* const, std::unique_ptr<paddle::framework::ir::Node, std::default_delete<paddle::framework::ir::Node> > > >*)
7   std::_Rb_tree<paddle::framework::ir::Node*, std::pair<paddle::framework::ir::Node* const, std::unique_ptr<paddle::framework::ir::Node, std::default_delete<paddle::framework::ir::Node> > >, std::_Select1st<std::pair<paddle::framework::ir::Node* const, std::unique_ptr<paddle::framework::ir::Node, std::default_delete<paddle::framework::ir::Node> > > >, std::less<paddle::framework::ir::Node*>, std::allocator<std::pair<paddle::framework::ir::Node* const, std::unique_ptr<paddle::framework::ir::Node, std::default_delete<paddle::framework::ir::Node> > > > >::_M_erase(std::_Rb_tree_node<std::pair<paddle::framework::ir::Node* const, std::unique_ptr<paddle::framework::ir::Node, std::default_delete<paddle::framework::ir::Node> > > >*)
8   std::_Rb_tree<paddle::framework::ir::Node*, std::pair<paddle::framework::ir::Node* const, std::unique_ptr<paddle::framework::ir::Node, std::default_delete<paddle::framework::ir::Node> > >, std::_Select1st<std::pair<paddle::framework::ir::Node* const, std::unique_ptr<paddle::framework::ir::Node, std::default_delete<paddle::framework::ir::Node> > > >, std::less<paddle::framework::ir::Node*>, std::allocator<std::pair<paddle::framework::ir::Node* const, std::unique_ptr<paddle::framework::ir::Node, std::default_delete<paddle::framework::ir::Node> > > > >::_M_erase(std::_Rb_tree_node<std::pair<paddle::framework::ir::Node* const, std::unique_ptr<paddle::framework::ir::Node, std::default_delete<paddle::framework::ir::Node> > > >*)
9   std::_Rb_tree<paddle::framework::ir::Node*, std::pair<paddle::framework::ir::Node* const, std::unique_ptr<paddle::framework::ir::Node, std::default_delete<paddle::framework::ir::Node> > >, std::_Select1st<std::pair<paddle::framework::ir::Node* const, std::unique_ptr<paddle::framework::ir::Node, std::default_delete<paddle::framework::ir::Node> > > >, std::less<paddle::framework::ir::Node*>, std::allocator<std::pair<paddle::framework::ir::Node* const, std::unique_ptr<paddle::framework::ir::Node, std::default_delete<paddle::framework::ir::Node> > > > >::_M_erase(std::_Rb_tree_node<std::pair<paddle::framework::ir::Node* const, std::unique_ptr<paddle::framework::ir::Node, std::default_delete<paddle::framework::ir::Node> > > >*)
10  std::_Rb_tree<paddle::framework::ir::Node*, std::pair<paddle::framework::ir::Node* const, std::unique_ptr<paddle::framework::ir::Node, std::default_delete<paddle::framework::ir::Node> > >, std::_Select1st<std::pair<paddle::framework::ir::Node* const, std::unique_ptr<paddle::framework::ir::Node, std::default_delete<paddle::framework::ir::Node> > > >, std::less<paddle::framework::ir::Node*>, std::allocator<std::pair<paddle::framework::ir::Node* const, std::unique_ptr<paddle::framework::ir::Node, std::default_delete<paddle::framework::ir::Node> > > > >::_M_erase(std::_Rb_tree_node<std::pair<paddle::framework::ir::Node* const, std::unique_ptr<paddle::framework::ir::Node, std::default_delete<paddle::framework::ir::Node> > > >*)
11  std::_Rb_tree<paddle::framework::ir::Node*, std::pair<paddle::framework::ir::Node* const, std::unique_ptr<paddle::framework::ir::Node, std::default_delete<paddle::framework::ir::Node> > >, std::_Select1st<std::pair<paddle::framework::ir::Node* const, std::unique_ptr<paddle::framework::ir::Node, std::default_delete<paddle::framework::ir::Node> > > >, std::less<paddle::framework::ir::Node*>, std::allocator<std::pair<paddle::framework::ir::Node* const, std::unique_ptr<paddle::framework::ir::Node, std::default_delete<paddle::framework::ir::Node> > > > >::_M_erase(std::_Rb_tree_node<std::pair<paddle::framework::ir::Node* const, std::unique_ptr<paddle::framework::ir::Node, std::default_delete<paddle::framework::ir::Node> > > >*)
12  std::_Rb_tree<paddle::framework::ir::Node*, std::pair<paddle::framework::ir::Node* const, std::unique_ptr<paddle::framework::ir::Node, std::default_delete<paddle::framework::ir::Node> > >, std::_Select1st<std::pair<paddle::framework::ir::Node* const, std::unique_ptr<paddle::framework::ir::Node, std::default_delete<paddle::framework::ir::Node> > > >, std::less<paddle::framework::ir::Node*>, std::allocator<std::pair<paddle::framework::ir::Node* const, std::unique_ptr<paddle::framework::ir::Node, std::default_delete<paddle::framework::ir::Node> > > > >::_M_erase(std::_Rb_tree_node<std::pair<paddle::framework::ir::Node* const, std::unique_ptr<paddle::framework::ir::Node, std::default_delete<paddle::framework::ir::Node> > > >*)
13  std::_Rb_tree<paddle::framework::ir::Node*, std::pair<paddle::framework::ir::Node* const, std::unique_ptr<paddle::framework::ir::Node, std::default_delete<paddle::framework::ir::Node> > >, std::_Select1st<std::pair<paddle::framework::ir::Node* const, std::unique_ptr<paddle::framework::ir::Node, std::default_delete<paddle::framework::ir::Node> > > >, std::less<paddle::framework::ir::Node*>, std::allocator<std::pair<paddle::framework::ir::Node* const, std::unique_ptr<paddle::framework::ir::Node, std::default_delete<paddle::framework::ir::Node> > > > >::_M_erase(std::_Rb_tree_node<std::pair<paddle::framework::ir::Node* const, std::unique_ptr<paddle::framework::ir::Node, std::default_delete<paddle::framework::ir::Node> > > >*)
14  std::_Rb_tree<paddle::framework::ir::Node*, std::pair<paddle::framework::ir::Node* const, std::unique_ptr<paddle::framework::ir::Node, std::default_delete<paddle::framework::ir::Node> > >, std::_Select1st<std::pair<paddle::framework::ir::Node* const, std::unique_ptr<paddle::framework::ir::Node, std::default_delete<paddle::framework::ir::Node> > > >, std::less<paddle::framework::ir::Node*>, std::allocator<std::pair<paddle::framework::ir::Node* const, std::unique_ptr<paddle::framework::ir::Node, std::default_delete<paddle::framework::ir::Node> > > > >::_M_erase(std::_Rb_tree_node<std::pair<paddle::framework::ir::Node* const, std::unique_ptr<paddle::framework::ir::Node, std::default_delete<paddle::framework::ir::Node> > > >*)
15  std::_Rb_tree<paddle::framework::ir::Node*, std::pair<paddle::framework::ir::Node* const, std::unique_ptr<paddle::framework::ir::Node, std::default_delete<paddle::framework::ir::Node> > >, std::_Select1st<std::pair<paddle::framework::ir::Node* const, std::unique_ptr<paddle::framework::ir::Node, std::default_delete<paddle::framework::ir::Node> > > >, std::less<paddle::framework::ir::Node*>, std::allocator<std::pair<paddle::framework::ir::Node* const, std::unique_ptr<paddle::framework::ir::Node, std::default_delete<paddle::framework::ir::Node> > > > >::_M_erase(std::_Rb_tree_node<std::pair<paddle::framework::ir::Node* const, std::unique_ptr<paddle::framework::ir::Node, std::default_delete<paddle::framework::ir::Node> > > >*)
16  std::_Rb_tree<paddle::framework::ir::Node*, std::pair<paddle::framework::ir::Node* const, std::unique_ptr<paddle::framework::ir::Node, std::default_delete<paddle::framework::ir::Node> > >, std::_Select1st<std::pair<paddle::framework::ir::Node* const, std::unique_ptr<paddle::framework::ir::Node, std::default_delete<paddle::framework::ir::Node> > > >, std::less<paddle::framework::ir::Node*>, std::allocator<std::pair<paddle::framework::ir::Node* const, std::unique_ptr<paddle::framework::ir::Node, std::default_delete<paddle::framework::ir::Node> > > > >::_M_erase(std::_Rb_tree_node<std::pair<paddle::framework::ir::Node* const, std::unique_ptr<paddle::framework::ir::Node, std::default_delete<paddle::framework::ir::Node> > > >*)
17  std::_Rb_tree<paddle::framework::ir::Node*, std::pair<paddle::framework::ir::Node* const, std::unique_ptr<paddle::framework::ir::Node, std::default_delete<paddle::framework::ir::Node> > >, std::_Select1st<std::pair<paddle::framework::ir::Node* const, std::unique_ptr<paddle::framework::ir::Node, std::default_delete<paddle::framework::ir::Node> > > >, std::less<paddle::framework::ir::Node*>, std::allocator<std::pair<paddle::framework::ir::Node* const, std::unique_ptr<paddle::framework::ir::Node, std::default_delete<paddle::framework::ir::Node> > > > >::_M_erase(std::_Rb_tree_node<std::pair<paddle::framework::ir::Node* const, std::unique_ptr<paddle::framework::ir::Node, std::default_delete<paddle::framework::ir::Node> > > >*)
18  std::_Rb_tree<paddle::framework::ir::Node*, std::pair<paddle::framework::ir::Node* const, std::unique_ptr<paddle::framework::ir::Node, std::default_delete<paddle::framework::ir::Node> > >, std::_Select1st<std::pair<paddle::framework::ir::Node* const, std::unique_ptr<paddle::framework::ir::Node, std::default_delete<paddle::framework::ir::Node> > > >, std::less<paddle::framework::ir::Node*>, std::allocator<std::pair<paddle::framework::ir::Node* const, std::unique_ptr<paddle::framework::ir::Node, std::default_delete<paddle::framework::ir::Node> > > > >::_M_erase(std::_Rb_tree_node<std::pair<paddle::framework::ir::Node* const, std::unique_ptr<paddle::framework::ir::Node, std::default_delete<paddle::framework::ir::Node> > > >*)
19  paddle::framework::ir::Graph::~Graph()
20  paddle::framework::ir::Graph::~Graph()
21  std::_Sp_counted_base<(__gnu_cxx::_Lock_policy)2>::_M_release()

----------------------
Error Message Summary:
----------------------
PaddleCheckError: unspecified launch failure at [/paddle/paddle/fluid/framework/details/op_handle_base.cc:39]

W0429 14:25:02.941488  1108 init.cc:205] *** Aborted at 1619677502 (unix time) try "date -d @1619677502" if you are using GNU date ***
W0429 14:25:02.943408  1108 init.cc:205] PC: @                0x0 (unknown)
W0429 14:25:02.943500  1108 init.cc:205] *** SIGABRT (@0x454) received by PID 1108 (TID 0x7f560d30f700) from PID 1108; stack trace: ***
W0429 14:25:02.945039  1108 init.cc:205]     @     0x7f560c7ab160 (unknown)
W0429 14:25:02.946671  1108 init.cc:205]     @     0x7f560bd193f7 __GI_raise
W0429 14:25:02.948252  1108 init.cc:205]     @     0x7f560bd1a7d8 __GI_abort
W0429 14:25:02.951503  1108 init.cc:205]     @     0x7f55c0463c65 __gnu_cxx::__verbose_terminate_handler()
W0429 14:25:02.952579  1108 init.cc:205]     @     0x7f55c0461e06 __cxxabiv1::__terminate()
W0429 14:25:02.953605  1108 init.cc:205]     @     0x7f55c0460ec9 __cxa_call_terminate
W0429 14:25:02.954670  1108 init.cc:205]     @     0x7f55c0461a7a __gxx_personality_v0
W0429 14:25:02.955698  1108 init.cc:205]     @     0x7f55c0934853 _Unwind_RaiseException_Phase2
W0429 14:25:02.956717  1108 init.cc:205]     @     0x7f55c0934beb _Unwind_RaiseException
W0429 14:25:02.957783  1108 init.cc:205]     @     0x7f55c0462045 __cxa_throw
W0429 14:25:02.960541  1108 init.cc:205]     @     0x7f5592b22666 paddle::framework::details::OpHandleBase::~OpHandleBase()
W0429 14:25:02.962682  1108 init.cc:205]     @     0x7f5592b24eef paddle::framework::details::ComputationOpHandle::~ComputationOpHandle()
W0429 14:25:02.964934  1108 init.cc:205]     @     0x7f559058d669 paddle::framework::ir::Node::~Node()
W0429 14:25:02.968152  1108 init.cc:205]     @     0x7f559058d811 paddle::framework::ir::Node::~Node()
W0429 14:25:02.971350  1108 init.cc:205]     @     0x7f55905787d2 std::_Rb_tree<>::_M_erase()
W0429 14:25:02.974537  1108 init.cc:205]     @     0x7f55905787bf std::_Rb_tree<>::_M_erase()
W0429 14:25:02.977712  1108 init.cc:205]     @     0x7f55905787bf std::_Rb_tree<>::_M_erase()
W0429 14:25:02.980934  1108 init.cc:205]     @     0x7f55905787bf std::_Rb_tree<>::_M_erase()
W0429 14:25:02.984112  1108 init.cc:205]     @     0x7f55905787bf std::_Rb_tree<>::_M_erase()
W0429 14:25:02.987313  1108 init.cc:205]     @     0x7f55905787bf std::_Rb_tree<>::_M_erase()
W0429 14:25:02.990494  1108 init.cc:205]     @     0x7f55905787bf std::_Rb_tree<>::_M_erase()
W0429 14:25:02.993677  1108 init.cc:205]     @     0x7f55905787bf std::_Rb_tree<>::_M_erase()
W0429 14:25:02.996871  1108 init.cc:205]     @     0x7f55905787bf std::_Rb_tree<>::_M_erase()
W0429 14:25:03.000074  1108 init.cc:205]     @     0x7f55905787bf std::_Rb_tree<>::_M_erase()
W0429 14:25:03.003275  1108 init.cc:205]     @     0x7f55905787bf std::_Rb_tree<>::_M_erase()
W0429 14:25:03.006453  1108 init.cc:205]     @     0x7f55905787bf std::_Rb_tree<>::_M_erase()
W0429 14:25:03.009642  1108 init.cc:205]     @     0x7f55905787bf std::_Rb_tree<>::_M_erase()
W0429 14:25:03.011104  1108 init.cc:205]     @     0x7f5592d34b31 paddle::framework::ir::Graph::~Graph()
W0429 14:25:03.014082  1108 init.cc:205]     @     0x7f5592d34bc1 paddle::framework::ir::Graph::~Graph()
W0429 14:25:03.015673  1108 init.cc:205]     @     0x7f55904691a9 std::_Sp_counted_base<>::_M_release()
W0429 14:25:03.016917  1108 init.cc:205]     @     0x7f5590578388 _ZN8pybind116class_IN6paddle9framework2ir5GraphEJSt10shared_ptrIS4_EEE7deallocERNS_6detail16value_and_holderE
W0429 14:25:03.018220  1108 init.cc:205]     @     0x7f559049de3a pybind11::detail::clear_instance()
run.sh: line 16:  1108 Aborted                 (core dumped) python3 local_train.py

**Comment by iclementine** [comment]
https://github.com/PaddlePaddle/Paddle/blob/89daf8e645a490763b52a260845197e7c8d7680d/paddle/fluid/framework/details/op_handle_base.cc#L51 有关

那么是 cuda 初始化失败了

看起来是环境的问题，可以给详细的环境配置以便诊断？
