### ISSUE TITLE
请问PaddleSeg 的模型deeplabv3，是否支持CUDA-11.0推理？

### ISSUE THREAD

**Issue by molyswu** [PaddlePaddle/Paddle#32741]
我想问一下PaddleSeg 的模型deeplabv3 的推理问题，在CUDA-11.0环境下推理deeplabv3，目的是win10在RTX3070,RTX3080上使用。
 如果deeplabv3 支持CUDA-11.0，我搭建模型推理，编译的时候出现很多错误？deeplabv3 支持CUDA-11.0的指引吗？
deeplabv3 支持CUDA-10.2，我搭建模型推理，编译是OK的。

**Comment by juncaipeng** [comment]
window上，可以下载cuda11的paddle预测库：https://paddleinference.paddlepaddle.org.cn/user_guides/download_lib.html#windows

你这个编译是预测库编译错误，还是编译应用程序时错误？

**Comment by molyswu** [comment]
编译是预测库编译错误

**Comment by molyswu** [comment]
uilding Custom Rule D:/projects/PaddleSeg/legacy/deploy/cpp/CMakeLists.txt
4>demo.cpp
4>D:\projects\PaddleSeg\legacy\deploy\cpp\utils/utils.h(106): warning C4244: “=”: 从“double”转换到“float”，可能丢失数据
4>d:\projects\fluid_inference\paddle\include\paddle_api.h(157): warning C4251: “paddle::PaddleTensor::name”: class“std::basic_string<char,std::char_traits<char>,std::allocator<char>>”需要有 dll 接口由 struct“paddle::PaddleTensor”的客户端使用
4>C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\VC\Tools\MSVC\14.16.27023\include\xstring(4373): note: 参见“std::basic_string<char,std::char_traits<char>,std::allocator<char>>”的声明
4>d:\projects\fluid_inference\paddle\include\paddle_api.h(158): warning C4251: “paddle::PaddleTensor::shape”: class“std::vector<int,std::allocator<_Ty>>”需要有 dll 接口由 struct“paddle::PaddleTensor”的客户端使用
4>        with
4>        [
4>            _Ty=int
4>        ]
4>D:\projects\opencv\build\include\opencv2/core/types.hpp(737): note: 参见“std::vector<int,std::allocator<_Ty>>”的声明
4>        with
4>        [
4>            _Ty=int
4>        ]
4>d:\projects\fluid_inference\paddle\include\paddle_api.h(161): warning C4251: “paddle::PaddleTensor::lod”: class“std::vector<std::vector<size_t,std::allocator<_Ty>>,std::allocator<std::vector<_Ty,std::allocator<_Ty>>>>”需要有 dll 接口由 struct“paddle::PaddleTensor”的客户端使用
4>        with
4>        [
4>            _Ty=size_t
4>        ]
4>d:\projects\fluid_inference\paddle\include\paddle_api.h(161): note: 参见“std::vector<std::vector<size_t,std::allocator<_Ty>>,std::allocator<std::vector<_Ty,std::allocator<_Ty>>>>”的声明
4>        with
4>        [
4>            _Ty=size_t
4>        ]
4>d:\projects\fluid_inference\paddle\include\paddle_api.h(237): warning C4251: “paddle::ZeroCopyTensor::name_”: class“std::basic_string<char,std::char_traits<char>,std::allocator<char>>”需要有 dll 接口由 class“paddle::ZeroCopyTensor”的客户端使用
4>C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\VC\Tools\MSVC\14.16.27023\include\xstring(4373): note: 参见“std::basic_string<char,std::char_traits<char>,std::allocator<char>>”的声明
4>d:\projects\fluid_inference\paddle\include\paddle_api.h(369): warning C4251: “paddle::NativeConfig::prog_file”: class“std::basic_string<char,std::char_traits<char>,std::allocator<char>>”需要有 dll 接口由 struct“paddle::NativeConfig”的客户端使用
4>C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\VC\Tools\MSVC\14.16.27023\include\xstring(4373): note: 参见“std::basic_string<char,std::char_traits<char>,std::allocator<char>>”的声明
4>d:\projects\fluid_inference\paddle\include\paddle_api.h(371): warning C4251: “paddle::NativeConfig::param_file”: class“std::basic_string<char,std::char_traits<char>,std::allocator<char>>”需要有 dll 接口由 struct“paddle::NativeConfig”的客户端使用
4>C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\VC\Tools\MSVC\14.16.27023\include\xstring(4373): note: 参见“std::basic_string<char,std::char_traits<char>,std::allocator<char>>”的声明
4>d:\projects\fluid_inference\paddle\include\paddle_pass_builder.h(110): warning C4251: “paddle::PaddlePassBuilder::analysis_passes_”: class“std::vector<std::string,std::allocator<_Ty>>”需要有 dll 接口由 class“paddle::PaddlePassBuilder”的客户端使用
4>        with
4>        [
4>            _Ty=std::string
4>        ]
4>D:\projects\fluid_inference\third_party\install\gflags\include\gflags/gflags.h(188): note: 参见“std::vector<std::string,std::allocator<_Ty>>”的声明
4>        with
4>        [
4>            _Ty=std::string
4>        ]
4>d:\projects\fluid_inference\paddle\include\paddle_pass_builder.h(111): warning C4251: “paddle::PaddlePassBuilder::passes_”: class“std::vector<std::string,std::allocator<_Ty>>”需要有 dll 接口由 class“paddle::PaddlePassBuilder”的客户端使用
4>        with
4>        [
4>            _Ty=std::string
4>        ]
4>D:\projects\fluid_inference\third_party\install\gflags\include\gflags/gflags.h(188): note: 参见“std::vector<std::string,std::allocator<_Ty>>”的声明
4>        with
4>        [
4>            _Ty=std::string
4>        ]
4>d:\projects\fluid_inference\paddle\include\paddle_analysis_config.h(588): warning C4251: “paddle::AnalysisConfig::model_dir_”: class“std::basic_string<char,std::char_traits<char>,std::allocator<char>>”需要有 dll 接口由 struct“paddle::AnalysisConfig”的客户端使用
4>C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\VC\Tools\MSVC\14.16.27023\include\xstring(4373): note: 参见“std::basic_string<char,std::char_traits<char>,std::allocator<char>>”的声明
4>d:\projects\fluid_inference\paddle\include\paddle_analysis_config.h(589): warning C4251: “paddle::AnalysisConfig::prog_file_”: class“std::basic_string<char,std::char_traits<char>,std::allocator<char>>”需要有 dll 接口由 struct“paddle::AnalysisConfig”的客户端使用
4>C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\VC\Tools\MSVC\14.16.27023\include\xstring(4373): note: 参见“std::basic_string<char,std::char_traits<char>,std::allocator<char>>”的声明
4>d:\projects\fluid_inference\paddle\include\paddle_analysis_config.h(590): warning C4251: “paddle::AnalysisConfig::params_file_”: class“std::basic_string<char,std::char_traits<char>,std::allocator<char>>”需要有 dll 接口由 struct“paddle::AnalysisConfig”的客户端使用
4>C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\VC\Tools\MSVC\14.16.27023\include\xstring(4373): note: 参见“std::basic_string<char,std::char_traits<char>,std::allocator<char>>”的声明
4>d:\projects\fluid_inference\paddle\include\paddle_analysis_config.h(624): warning C4251: “paddle::AnalysisConfig::min_input_shape_”: class“std::map<std::string,std::vector<int,std::allocator<_Ty>>,std::less<_Kty>,std::allocator<std::pair<const _Kty,std::vector<_Ty,std::allocator<_Ty>>>>>”需要有 dll 接口由 struct“paddle::AnalysisConfig”的客户端使用
4>        with
4>        [
4>            _Ty=int,
4>            _Kty=std::string
4>        ]
4>d:\projects\fluid_inference\paddle\include\paddle_analysis_config.h(323): note: 参见“std::map<std::string,std::vector<int,std::allocator<_Ty>>,std::less<_Kty>,std::allocator<std::pair<const _Kty,std::vector<_Ty,std::allocator<_Ty>>>>>”的声明
4>        with
4>        [
4>            _Ty=int,
4>            _Kty=std::string
4>        ]
4>d:\projects\fluid_inference\paddle\include\paddle_analysis_config.h(625): warning C4251: “paddle::AnalysisConfig::max_input_shape_”: class“std::map<std::string,std::vector<int,std::allocator<_Ty>>,std::less<_Kty>,std::allocator<std::pair<const _Kty,std::vector<_Ty,std::allocator<_Ty>>>>>”需要有 dll 接口由 struct“paddle::AnalysisConfig”的客户端使用
4>        with
4>        [
4>            _Ty=int,
4>            _Kty=std::string
4>        ]
4>d:\projects\fluid_inference\paddle\include\paddle_analysis_config.h(323): note: 参见“std::map<std::string,std::vector<int,std::allocator<_Ty>>,std::less<_Kty>,std::allocator<std::pair<const _Kty,std::vector<_Ty,std::allocator<_Ty>>>>>”的声明
4>        with
4>        [
4>            _Ty=int,
4>            _Kty=std::string
4>        ]
4>d:\projects\fluid_inference\paddle\include\paddle_analysis_config.h(626): warning C4251: “paddle::AnalysisConfig::optim_input_shape_”: class“std::map<std::string,std::vector<int,std::allocator<_Ty>>,std::less<_Kty>,std::allocator<std::pair<const _Kty,std::vector<_Ty,std::allocator<_Ty>>>>>”需要有 dll 接口由 struct“paddle::AnalysisConfig”的客户端使用
4>        with
4>        [
4>            _Ty=int,
4>            _Kty=std::string
4>        ]
4>d:\projects\fluid_inference\paddle\include\paddle_analysis_config.h(323): note: 参见“std::map<std::string,std::vector<int,std::allocator<_Ty>>,std::less<_Kty>,std::allocator<std::pair<const _Kty,std::vector<_Ty,std::allocator<_Ty>>>>>”的声明
4>        with
4>        [
4>            _Ty=int,
4>            _Kty=std::string
4>        ]
4>d:\projects\fluid_inference\paddle\include\paddle_analysis_config.h(627): warning C4251: “paddle::AnalysisConfig::trt_disabled_ops_”: class“std::vector<std::string,std::allocator<_Ty>>”需要有 dll 接口由 struct“paddle::AnalysisConfig”的客户端使用
4>        with
4>        [
4>            _Ty=std::string
4>        ]
4>D:\projects\fluid_inference\third_party\install\gflags\include\gflags/gflags.h(188): note: 参见“std::vector<std::string,std::allocator<_Ty>>”的声明
4>        with
4>        [
4>            _Ty=std::string
4>        ]
4>d:\projects\fluid_inference\paddle\include\paddle_analysis_config.h(634): warning C4251: “paddle::AnalysisConfig::mkldnn_enabled_op_types_”: class“std::unordered_set<std::string,std::hash<_Kty>,std::equal_to<_Kty>,std::allocator<_Ty>>”需要有 dll 接口由 struct“paddle::AnalysisConfig”的客户端使用
4>        with
4>        [
4>            _Kty=std::string,
4>            _Ty=std::string
4>        ]
4>d:\projects\fluid_inference\paddle\include\paddle_analysis_config.h(442): note: 参见“std::unordered_set<std::string,std::hash<_Kty>,std::equal_to<_Kty>,std::allocator<_Ty>>”的声明
4>        with
4>        [
4>            _Kty=std::string,
4>            _Ty=std::string
4>        ]
4>d:\projects\fluid_inference\paddle\include\paddle_analysis_config.h(651): warning C4251: “paddle::AnalysisConfig::serialized_info_cache_”: class“std::basic_string<char,std::char_traits<char>,std::allocator<char>>”需要有 dll 接口由 struct“paddle::AnalysisConfig”的客户端使用
4>C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\VC\Tools\MSVC\14.16.27023\include\xstring(4373): note: 参见“std::basic_string<char,std::char_traits<char>,std::allocator<char>>”的声明
4>d:\projects\fluid_inference\paddle\include\paddle_analysis_config.h(653): warning C4251: “paddle::AnalysisConfig::pass_builder_”: class“std::unique_ptr<paddle::PassStrategy,std::default_delete<_Ty>>”需要有 dll 接口由 struct“paddle::AnalysisConfig”的客户端使用
4>        with
4>        [
4>            _Ty=paddle::PassStrategy
4>        ]
4>d:\projects\fluid_inference\paddle\include\paddle_analysis_config.h(653): note: 参见“std::unique_ptr<paddle::PassStrategy,std::default_delete<_Ty>>”的声明
4>        with
4>        [
4>            _Ty=paddle::PassStrategy
4>        ]
4>d:\projects\fluid_inference\paddle\include\paddle_analysis_config.h(656): warning C4251: “paddle::AnalysisConfig::lite_passes_filter_”: class“std::vector<std::string,std::allocator<_Ty>>”需要有 dll 接口由 struct“paddle::AnalysisConfig”的客户端使用
4>        with
4>        [
4>            _Ty=std::string
4>        ]
4>D:\projects\fluid_inference\third_party\install\gflags\include\gflags/gflags.h(188): note: 参见“std::vector<std::string,std::allocator<_Ty>>”的声明
4>        with
4>        [
4>            _Ty=std::string
4>        ]
4>d:\projects\fluid_inference\paddle\include\paddle_analysis_config.h(657): warning C4251: “paddle::AnalysisConfig::lite_ops_filter_”: class“std::vector<std::string,std::allocator<_Ty>>”需要有 dll 接口由 struct“paddle::AnalysisConfig”的客户端使用
4>        with
4>        [
4>            _Ty=std::string
4>        ]
4>D:\projects\fluid_inference\third_party\install\gflags\include\gflags/gflags.h(188): note: 参见“std::vector<std::string,std::allocator<_Ty>>”的声明
4>        with
4>        [
4>            _Ty=std::string
4>        ]
4>d:\projects\fluid_inference\paddle\include\paddle_analysis_config.h(668): warning C4251: “paddle::AnalysisConfig::mkldnn_quantizer_config_”: class“std::shared_ptr<paddle::MkldnnQuantizerConfig>”需要有 dll 接口由 struct“paddle::AnalysisConfig”的客户端使用
4>d:\projects\fluid_inference\paddle\include\paddle_analysis_config.h(668): note: 参见“std::shared_ptr<paddle::MkldnnQuantizerConfig>”的声明
4>d:\projects\fluid_inference\paddle\include\paddle_analysis_config.h(670): warning C4251: “paddle::AnalysisConfig::bfloat16_enabled_op_types_”: class“std::unordered_set<std::string,std::hash<_Kty>,std::equal_to<_Kty>,std::allocator<_Ty>>”需要有 dll 接口由 struct“paddle::AnalysisConfig”的客户端使用
4>        with
4>        [
4>            _Kty=std::string,
4>            _Ty=std::string
4>        ]
4>d:\projects\fluid_inference\paddle\include\paddle_analysis_config.h(442): note: 参见“std::unordered_set<std::string,std::hash<_Kty>,std::equal_to<_Kty>,std::allocator<_Ty>>”的声明
4>        with
4>        [
4>            _Kty=std::string,
4>            _Ty=std::string
4>        ]
4>d:\projects\fluid_inference\paddle\include\paddle_analysis_config.h(677): warning C4251: “paddle::AnalysisConfig::opt_cache_dir_”: class“std::basic_string<char,std::char_traits<char>,std::allocator<char>>”需要有 dll 接口由 struct“paddle::AnalysisConfig”的客户端使用
4>C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\VC\Tools\MSVC\14.16.27023\include\xstring(4373): note: 参见“std::basic_string<char,std::char_traits<char>,std::allocator<char>>”的声明
4>d:\projects\fluid_inference\paddle\include\paddle_analysis_config.h(210): warning C4244: “return”: 从“const uint64_t”转换到“int”，可能丢失数据
4>D:\projects\fluid_inference\paddle\include\paddle_inference_api.h(133): warning C4251: “paddle_infer::Tensor::tensor_”: class“std::unique_ptr<paddle::ZeroCopyTensor,std::default_delete<_Ty>>”需要有 dll 接口由 class“paddle_infer::Tensor”的客户端使用
4>        with
4>        [
4>            _Ty=paddle::ZeroCopyTensor
4>        ]
4>d:\projects\fluid_inference\paddle\include\paddle_api.h(291): note: 参见“std::unique_ptr<paddle::ZeroCopyTensor,std::default_delete<_Ty>>”的声明
4>        with
4>        [
4>            _Ty=paddle::ZeroCopyTensor
4>        ]
4>D:\projects\fluid_inference\paddle\include\paddle_inference_api.h(239): warning C4251: “paddle_infer::Predictor::predictor_”: class“std::unique_ptr<paddle::PaddlePredictor,std::default_delete<_Ty>>”需要有 dll 接口由 class“paddle_infer::Predictor”的客户端使用
4>        with
4>        [
4>            _Ty=paddle::PaddlePredictor
4>        ]
4>d:\projects\fluid_inference\paddle\include\paddle_api.h(337): note: 参见“std::unique_ptr<paddle::PaddlePredictor,std::default_delete<_Ty>>”的声明
4>        with
4>        [
4>            _Ty=paddle::PaddlePredictor
4>        ]
4>D:\projects\fluid_inference\paddle\include\paddle_inference_api.h(307): warning C4251: “paddle_infer::services::PredictorPool::main_pred_”: class“std::shared_ptr<paddle_infer::Predictor>”需要有 dll 接口由 class“paddle_infer::services::PredictorPool”的客户端使用
4>D:\projects\fluid_inference\paddle\include\paddle_inference_api.h(253): note: 参见“std::shared_ptr<paddle_infer::Predictor>”的声明
4>D:\projects\fluid_inference\paddle\include\paddle_inference_api.h(308): warning C4251: “paddle_infer::services::PredictorPool::preds_”: class“std::vector<std::unique_ptr<paddle_infer::Predictor,std::default_delete<_Ty>>,std::allocator<std::unique_ptr<_Ty,std::default_delete<_Ty>>>>”需要有 dll 接口由 class“paddle_infer::services::PredictorPool”的客户端使用
4>        with
4>        [
4>            _Ty=paddle_infer::Predictor
4>        ]
4>D:\projects\fluid_inference\paddle\include\paddle_inference_api.h(308): note: 参见“std::vector<std::unique_ptr<paddle_infer::Predictor,std::default_delete<_Ty>>,std::allocator<std::unique_ptr<_Ty,std::default_delete<_Ty>>>>”的声明
4>        with
4>        [
4>            _Ty=paddle_infer::Predictor
4>        ]
4>d:\projects\opencv\build\include\opencv2\flann\result_set.h(306): warning C4003: 类函数宏的调用“max”参数不足
4>d:\projects\opencv\build\include\opencv2\flann\result_set.h(428): warning C4003: 类函数宏的调用“max”参数不足
4>d:\projects\opencv\build\include\opencv2\flann\lsh_index.h(203): warning C4003: 类函数宏的调用“max”参数不足
4>d:\projects\opencv\build\include\opencv2\flann\lsh_index.h(269): warning C4003: 类函数宏的调用“max”参数不足
4>LINK : fatal error LNK1181: 无法打开输入文件“D:\projects\fluid_inference\paddle\lib\libpaddle_fluid.lib”
4>已完成生成项目“demo.vcxproj”的操作 - 失败。
5>------ 已启动全部重新生成: 项目: ALL_BUILD, 配置: Release x64 ------
5>Building Custom Rule D:/projects/PaddleSeg/legacy/deploy/cpp/CMakeLists.txt
========== 全部重新生成: 成功 4 个，失败 1 个，跳过 0 个 ==========
