### ISSUE TITLE
用cuda11.0推理模型,在win10环境，cuda11.0_cudnn8_avx_mkl_trt7，如下问题。

### ISSUE THREAD

**Issue by molyswu** [PaddlePaddle/Paddle#32767]
用cuda11.0推理模型,在win10环境下RTX3070 gpu，cuda11.0_cudnn8_avx_mkl_trt7，如下问题。
用cuda11.0_cudnn8_avx_mkl_trt7   https://paddleinference.paddlepaddle.org.cn/user_guides/download_lib.html#windows
如下错误：
uilding Custom Rule D:/projects/PaddleSeg/legacy/deploy/cpp/CMakeLists.txt
4>demo.cpp
4>D:\projects\PaddleSeg\legacy\deploy\cpp\utils/utils.h(106): warning C4244: “=”: 从“double”转换到“float”，可能丢失数据
4>d:\projects\fluid_inference\paddle\include\paddle_api.h(157): warning C4251: “paddle::PaddleTensor::name”: class“std::basic_string<char,std::char_traits,std::allocator>”需要有 dll 接口由 struct“paddle::PaddleTensor”的客户端使用
4>C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\VC\Tools\MSVC\14.16.27023\include\xstring(4373): note: 参见“std::basic_string<char,std::char_traits,std::allocator>”的声明
4>d:\projects\fluid_inference\paddle\include\paddle_api.h(158): warning C4251: “paddle::PaddleTensor::shape”: class“std::vector<int,std::allocator<_Ty>>”需要有 dll 接口由 struct“paddle::PaddleTensor”的客户端使用
4> with
4> [
4> _Ty=int
4> ]
4>D:\projects\opencv\build\include\opencv2/core/types.hpp(737): note: 参见“std::vector<int,std::allocator<_Ty>>”的声明
4> with
4> [
4> _Ty=int
4> ]
4>d:\projects\fluid_inference\paddle\include\paddle_api.h(161): warning C4251: “paddle::PaddleTensor::lod”: class“std::vector<std::vector<size_t,std::allocator<_Ty>>,std::allocator<std::vector<_Ty,std::allocator<_Ty>>>>”需要有 dll 接口由 struct“paddle::PaddleTensor”的客户端使用
4> with
4> [
4> _Ty=size_t
4> ]
4>d:\projects\fluid_inference\paddle\include\paddle_api.h(161): note: 参见“std::vector<std::vector<size_t,std::allocator<_Ty>>,std::allocator<std::vector<_Ty,std::allocator<Ty>>>>”的声明
4> with
4> [
4> Ty=size_t
4> ]
4>d:\projects\fluid_inference\paddle\include\paddle_api.h(237): warning C4251: “paddle::ZeroCopyTensor::name”: class“std::basic_string<char,std::char_traits,std::allocator>”需要有 dll 接口由 class“paddle::ZeroCopyTensor”的客户端使用
4>C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\VC\Tools\MSVC\14.16.27023\include\xstring(4373): note: 参见“std::basic_string<char,std::char_traits,std::allocator>”的声明
4>d:\projects\fluid_inference\paddle\include\paddle_api.h(369): warning C4251: “paddle::NativeConfig::prog_file”: class“std::basic_string<char,std::char_traits,std::allocator>”需要有 dll 接口由 struct“paddle::NativeConfig”的客户端使用
4>C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\VC\Tools\MSVC\14.16.27023\include\xstring(4373): note: 参见“std::basic_string<char,std::char_traits,std::allocator>”的声明
4>d:\projects\fluid_inference\paddle\include\paddle_api.h(371): warning C4251: “paddle::NativeConfig::param_file”: class“std::basic_string<char,std::char_traits,std::allocator>”需要有 dll 接口由 struct“paddle::NativeConfig”的客户端使用
4>C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\VC\Tools\MSVC\14.16.27023\include\xstring(4373): note: 参见“std::basic_string<char,std::char_traits,std::allocator>”的声明
4>d:\projects\fluid_inference\paddle\include\paddle_pass_builder.h(110): warning C4251: “paddle::PaddlePassBuilder::analysis_passes”: class“std::vector<std::string,std::allocator<_Ty>>”需要有 dll 接口由 class“paddle::PaddlePassBuilder”的客户端使用
4> with
4> [
4> _Ty=std::string
4> ]
4>D:\projects\fluid_inference\third_party\install\gflags\include\gflags/gflags.h(188): note: 参见“std::vector<std::string,std::allocator<_Ty>>”的声明
4> with
4> [
4> Ty=std::string
4> ]
4>d:\projects\fluid_inference\paddle\include\paddle_pass_builder.h(111): warning C4251: “paddle::PaddlePassBuilder::passes”: class“std::vector<std::string,std::allocator<Ty>>”需要有 dll 接口由 class“paddle::PaddlePassBuilder”的客户端使用
4> with
4> [
4> Ty=std::string
4> ]
4>D:\projects\fluid_inference\third_party\install\gflags\include\gflags/gflags.h(188): note: 参见“std::vector<std::string,std::allocator<Ty>>”的声明
4> with
4> [
4> Ty=std::string
4> ]
4>d:\projects\fluid_inference\paddle\include\paddle_analysis_config.h(588): warning C4251: “paddle::AnalysisConfig::model_dir”: class“std::basic_string<char,std::char_traits,std::allocator>”需要有 dll 接口由 struct“paddle::AnalysisConfig”的客户端使用
4>C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\VC\Tools\MSVC\14.16.27023\include\xstring(4373): note: 参见“std::basic_string<char,std::char_traits,std::allocator>”的声明
4>d:\projects\fluid_inference\paddle\include\paddle_analysis_config.h(589): warning C4251: “paddle::AnalysisConfig::prog_file”: class“std::basic_string<char,std::char_traits,std::allocator>”需要有 dll 接口由 struct“paddle::AnalysisConfig”的客户端使用
4>C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\VC\Tools\MSVC\14.16.27023\include\xstring(4373): note: 参见“std::basic_string<char,std::char_traits,std::allocator>”的声明
4>d:\projects\fluid_inference\paddle\include\paddle_analysis_config.h(590): warning C4251: “paddle::AnalysisConfig::params_file”: class“std::basic_string<char,std::char_traits,std::allocator>”需要有 dll 接口由 struct“paddle::AnalysisConfig”的客户端使用
4>C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\VC\Tools\MSVC\14.16.27023\include\xstring(4373): note: 参见“std::basic_string<char,std::char_traits,std::allocator>”的声明
4>d:\projects\fluid_inference\paddle\include\paddle_analysis_config.h(624): warning C4251: “paddle::AnalysisConfig::min_input_shape”: class“std::map<std::string,std::vector<int,std::allocator<_Ty>>,std::less<_Kty>,std::allocator<std::pair<const _Kty,std::vector<_Ty,std::allocator<_Ty>>>>>”需要有 dll 接口由 struct“paddle::AnalysisConfig”的客户端使用
4> with
4> [
4> _Ty=int,
4> _Kty=std::string
4> ]
4>d:\projects\fluid_inference\paddle\include\paddle_analysis_config.h(323): note: 参见“std::map<std::string,std::vector<int,std::allocator<_Ty>>,std::less<_Kty>,std::allocator<std::pair<const _Kty,std::vector<_Ty,std::allocator<_Ty>>>>>”的声明
4> with
4> [
4> _Ty=int,
4> Kty=std::string
4> ]
4>d:\projects\fluid_inference\paddle\include\paddle_analysis_config.h(625): warning C4251: “paddle::AnalysisConfig::max_input_shape”: class“std::map<std::string,std::vector<int,std::allocator<_Ty>>,std::less<_Kty>,std::allocator<std::pair<const _Kty,std::vector<_Ty,std::allocator<_Ty>>>>>”需要有 dll 接口由 struct“paddle::AnalysisConfig”的客户端使用
4> with
4> [
4> _Ty=int,
4> _Kty=std::string
4> ]
4>d:\projects\fluid_inference\paddle\include\paddle_analysis_config.h(323): note: 参见“std::map<std::string,std::vector<int,std::allocator<_Ty>>,std::less<_Kty>,std::allocator<std::pair<const _Kty,std::vector<_Ty,std::allocator<_Ty>>>>>”的声明
4> with
4> [
4> _Ty=int,
4> Kty=std::string
4> ]
4>d:\projects\fluid_inference\paddle\include\paddle_analysis_config.h(626): warning C4251: “paddle::AnalysisConfig::optim_input_shape”: class“std::map<std::string,std::vector<int,std::allocator<_Ty>>,std::less<_Kty>,std::allocator<std::pair<const _Kty,std::vector<_Ty,std::allocator<_Ty>>>>>”需要有 dll 接口由 struct“paddle::AnalysisConfig”的客户端使用
4> with
4> [
4> _Ty=int,
4> _Kty=std::string
4> ]
4>d:\projects\fluid_inference\paddle\include\paddle_analysis_config.h(323): note: 参见“std::map<std::string,std::vector<int,std::allocator<_Ty>>,std::less<_Kty>,std::allocator<std::pair<const _Kty,std::vector<_Ty,std::allocator<_Ty>>>>>”的声明
4> with
4> [
4> _Ty=int,
4> Kty=std::string
4> ]
4>d:\projects\fluid_inference\paddle\include\paddle_analysis_config.h(627): warning C4251: “paddle::AnalysisConfig::trt_disabled_ops”: class“std::vector<std::string,std::allocator<_Ty>>”需要有 dll 接口由 struct“paddle::AnalysisConfig”的客户端使用
4> with
4> [
4> _Ty=std::string
4> ]
4>D:\projects\fluid_inference\third_party\install\gflags\include\gflags/gflags.h(188): note: 参见“std::vector<std::string,std::allocator<_Ty>>”的声明
4> with
4> [
4> Ty=std::string
4> ]
4>d:\projects\fluid_inference\paddle\include\paddle_analysis_config.h(634): warning C4251: “paddle::AnalysisConfig::mkldnn_enabled_op_types”: class“std::unordered_set<std::string,std::hash<_Kty>,std::equal_to<_Kty>,std::allocator<_Ty>>”需要有 dll 接口由 struct“paddle::AnalysisConfig”的客户端使用
4> with
4> [
4> _Kty=std::string,
4> _Ty=std::string
4> ]
4>d:\projects\fluid_inference\paddle\include\paddle_analysis_config.h(442): note: 参见“std::unordered_set<std::string,std::hash<_Kty>,std::equal_to<_Kty>,std::allocator<_Ty>>”的声明
4> with
4> [
4> Kty=std::string,
4> Ty=std::string
4> ]
4>d:\projects\fluid_inference\paddle\include\paddle_analysis_config.h(651): warning C4251: “paddle::AnalysisConfig::serialized_info_cache”: class“std::basic_string<char,std::char_traits,std::allocator>”需要有 dll 接口由 struct“paddle::AnalysisConfig”的客户端使用
4>C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\VC\Tools\MSVC\14.16.27023\include\xstring(4373): note: 参见“std::basic_string<char,std::char_traits,std::allocator>”的声明
4>d:\projects\fluid_inference\paddle\include\paddle_analysis_config.h(653): warning C4251: “paddle::AnalysisConfig::pass_builder”: class“std::unique_ptr<paddle::PassStrategy,std::default_delete<_Ty>>”需要有 dll 接口由 struct“paddle::AnalysisConfig”的客户端使用
4> with
4> [
4> _Ty=paddle::PassStrategy
4> ]
4>d:\projects\fluid_inference\paddle\include\paddle_analysis_config.h(653): note: 参见“std::unique_ptr<paddle::PassStrategy,std::default_delete<_Ty>>”的声明
4> with
4> [
4> Ty=paddle::PassStrategy
4> ]
4>d:\projects\fluid_inference\paddle\include\paddle_analysis_config.h(656): warning C4251: “paddle::AnalysisConfig::lite_passes_filter”: class“std::vector<std::string,std::allocator<_Ty>>”需要有 dll 接口由 struct“paddle::AnalysisConfig”的客户端使用
4> with
4> [
4> _Ty=std::string
4> ]
4>D:\projects\fluid_inference\third_party\install\gflags\include\gflags/gflags.h(188): note: 参见“std::vector<std::string,std::allocator<_Ty>>”的声明
4> with
4> [
4> Ty=std::string
4> ]
4>d:\projects\fluid_inference\paddle\include\paddle_analysis_config.h(657): warning C4251: “paddle::AnalysisConfig::lite_ops_filter”: class“std::vector<std::string,std::allocator<_Ty>>”需要有 dll 接口由 struct“paddle::AnalysisConfig”的客户端使用
4> with
4> [
4> _Ty=std::string
4> ]
4>D:\projects\fluid_inference\third_party\install\gflags\include\gflags/gflags.h(188): note: 参见“std::vector<std::string,std::allocator<Ty>>”的声明
4> with
4> [
4> Ty=std::string
4> ]
4>d:\projects\fluid_inference\paddle\include\paddle_analysis_config.h(668): warning C4251: “paddle::AnalysisConfig::mkldnn_quantizer_config”: class“std::shared_ptrpaddle::MkldnnQuantizerConfig”需要有 dll 接口由 struct“paddle::AnalysisConfig”的客户端使用
4>d:\projects\fluid_inference\paddle\include\paddle_analysis_config.h(668): note: 参见“std::shared_ptrpaddle::MkldnnQuantizerConfig”的声明
4>d:\projects\fluid_inference\paddle\include\paddle_analysis_config.h(670): warning C4251: “paddle::AnalysisConfig::bfloat16_enabled_op_types”: class“std::unordered_set<std::string,std::hash<_Kty>,std::equal_to<_Kty>,std::allocator<_Ty>>”需要有 dll 接口由 struct“paddle::AnalysisConfig”的客户端使用
4> with
4> [
4> _Kty=std::string,
4> _Ty=std::string
4> ]
4>d:\projects\fluid_inference\paddle\include\paddle_analysis_config.h(442): note: 参见“std::unordered_set<std::string,std::hash<_Kty>,std::equal_to<_Kty>,std::allocator<_Ty>>”的声明
4> with
4> [
4> Kty=std::string,
4> Ty=std::string
4> ]
4>d:\projects\fluid_inference\paddle\include\paddle_analysis_config.h(677): warning C4251: “paddle::AnalysisConfig::opt_cache_dir”: class“std::basic_string<char,std::char_traits,std::allocator>”需要有 dll 接口由 struct“paddle::AnalysisConfig”的客户端使用
4>C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\VC\Tools\MSVC\14.16.27023\include\xstring(4373): note: 参见“std::basic_string<char,std::char_traits,std::allocator>”的声明
4>d:\projects\fluid_inference\paddle\include\paddle_analysis_config.h(210): warning C4244: “return”: 从“const uint64_t”转换到“int”，可能丢失数据
4>D:\projects\fluid_inference\paddle\include\paddle_inference_api.h(133): warning C4251: “paddle_infer::Tensor::tensor”: class“std::unique_ptr<paddle::ZeroCopyTensor,std::default_delete<_Ty>>”需要有 dll 接口由 class“paddle_infer::Tensor”的客户端使用
4> with
4> [
4> _Ty=paddle::ZeroCopyTensor
4> ]
4>d:\projects\fluid_inference\paddle\include\paddle_api.h(291): note: 参见“std::unique_ptr<paddle::ZeroCopyTensor,std::default_delete<_Ty>>”的声明
4> with
4> [
4> Ty=paddle::ZeroCopyTensor
4> ]
4>D:\projects\fluid_inference\paddle\include\paddle_inference_api.h(239): warning C4251: “paddle_infer::Predictor::predictor”: class“std::unique_ptr<paddle::PaddlePredictor,std::default_delete<_Ty>>”需要有 dll 接口由 class“paddle_infer::Predictor”的客户端使用
4> with
4> [
4> _Ty=paddle::PaddlePredictor
4> ]
4>d:\projects\fluid_inference\paddle\include\paddle_api.h(337): note: 参见“std::unique_ptr<paddle::PaddlePredictor,std::default_delete<Ty>>”的声明
4> with
4> [
4> Ty=paddle::PaddlePredictor
4> ]
4>D:\projects\fluid_inference\paddle\include\paddle_inference_api.h(307): warning C4251: “paddle_infer::services::PredictorPool::main_pred”: class“std::shared_ptr<paddle_infer::Predictor>”需要有 dll 接口由 class“paddle_infer::services::PredictorPool”的客户端使用
4>D:\projects\fluid_inference\paddle\include\paddle_inference_api.h(253): note: 参见“std::shared_ptr<paddle_infer::Predictor>”的声明
4>D:\projects\fluid_inference\paddle\include\paddle_inference_api.h(308): warning C4251: “paddle_infer::services::PredictorPool::preds”: class“std::vector<std::unique_ptr<paddle_infer::Predictor,std::default_delete<_Ty>>,std::allocator<std::unique_ptr<_Ty,std::default_delete<_Ty>>>>”需要有 dll 接口由 class“paddle_infer::services::PredictorPool”的客户端使用
4> with
4> [
4> _Ty=paddle_infer::Predictor
4> ]
4>D:\projects\fluid_inference\paddle\include\paddle_inference_api.h(308): note: 参见“std::vector<std::unique_ptr<paddle_infer::Predictor,std::default_delete<_Ty>>,std::allocator<std::unique_ptr<_Ty,std::default_delete<_Ty>>>>”的声明
4> with
4> [
4> _Ty=paddle_infer::Predictor
4> ]
4>d:\projects\opencv\build\include\opencv2\flann\result_set.h(306): warning C4003: 类函数宏的调用“max”参数不足
4>d:\projects\opencv\build\include\opencv2\flann\result_set.h(428): warning C4003: 类函数宏的调用“max”参数不足
4>d:\projects\opencv\build\include\opencv2\flann\lsh_index.h(203): warning C4003: 类函数宏的调用“max”参数不足
4>d:\projects\opencv\build\include\opencv2\flann\lsh_index.h(269): warning C4003: 类函数宏的调用“max”参数不足
4>LINK : fatal error LNK1181: 无法打开输入文件“D:\projects\fluid_inference\paddle\lib\libpaddle_fluid.lib”
4>已完成生成项目“demo.vcxproj”的操作 - 失败。
5>------ 已启动全部重新生成: 项目: ALL_BUILD, 配置: Release x64 ------
5>Building Custom Rule D:/projects/PaddleSeg/legacy/deploy/cpp/CMakeLists.txt
========== 全部重新生成: 成功 4 个，失败 1 个，跳过 0 个 ==========

**Comment by zhaoyang-star** [comment]
请提供使用的Paddle分支和commit id、编译命令，我们先尝试复现下。
从上面log中暂时看不到有效定位错误的信息。

**Comment by molyswu** [comment]
Paddle2.0分支的legacy编译C++命令是与readme是相同的：https://github.com/PaddlePaddle/PaddleSeg/tree/release/v2.0/legacy/deploy/cpp
只是将cuda10.0换成cuda11.0
cuda10.0或cuda10.2是ok的,用cuda11.0_cudnn8_avx_mkl_trt7 https://paddleinference.paddlepaddle.org.cn/user_guides/download_lib.html#windows，cuda11.0就有错误。

**Comment by molyswu** [comment]
Paddle2.0推理deeplabv3还是不兼容cuda11

**Comment by molyswu** [comment]
只有自己问自己答。
