### ISSUE TITLE
飞浆平台有RBF接口吗？在平台怎么实现RBF和其他网络的融合

### ISSUE THREAD

**Issue by Annie-mm** [PaddlePaddle/Paddle#32783]
我想做一个LSTM和RBF网络融合。飞浆平台上找不到RBF接口。不知道可以在paddle上实现这种网络融合，希望得到帮助，谢谢。

**Comment by danleifeng** [comment]
您好，目前飞桨没有RBF网络实现，您可以借助paddle的api复现，有任何问题欢迎联系我们。

**Comment by Annie-mm** [comment]
@danleifeng 如果只是把RBF的隐藏层当成激活函数进行复现不知道是否可行，如果用高级API 优化和训练是否能对这个激活函数进行训练？复现好难，没有一点头绪。

**Comment by Annie-mm** [comment]
@danleifeng 有没有复现API的文档可以参考？

**Comment by danleifeng** [comment]
您好，可参考API文档：https://www.paddlepaddle.org.cn/documentation/docs/zh/guides/index_cn.html
如果需要实现激活函数，可以参考下已有激活函数的实现：https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/nn/layer/activation.py
