### ISSUE TITLE
关于动态图的senet

### ISSUE THREAD

**Issue by cristicmf** [PaddlePaddle/Paddle#32795]
1. 什么时候出动态图的senet，很期待你们这个功能
2. 如果最近没有出的计划，那如果我写好了senet模块，然后要怎么去调用静态图训练好的权重

**Comment by danleifeng** [comment]
您好，在PaddleClas repo里有SENET的动态图训练，不知道是否是您需要的，可参考：
https://github.com/PaddlePaddle/PaddleClas
https://github.com/PaddlePaddle/PaddleClas/tree/release/2.1/configs/SENet

**Comment by cristicmf** [comment]
@danleifeng  感谢你的回复，paddledetection的senet权重怎么调用？
