### ISSUE TITLE
GPU预测 Cuda error(700), an illegal memory access was encountered.使用CPU正常

### ISSUE THREAD

**Issue by shawnLang** [PaddlePaddle/Paddle#32797]
1）PaddlePaddle版本：paddlepaddle-gpu:2.0.2
    2）CPU：预测正常
    3）GPU：cuda：10.2 cudnn：7.6.5
    4）系统环境：centos7 python3.7.9
![QQ截图20210508110937](https://user-images.githubusercontent.com/22512533/117523990-eb9d5a00-afed-11eb-95e6-820059cdd319.png)

**Comment by ForFishes** [comment]
您好，这个可以提供提供简单可复现的代码吗，这边复现一下。

**Comment by shawnLang** [comment]
> 您好，这个可以提供提供简单可复现的代码吗，这边复现一下。

链接：https://pan.baidu.com/s/1sONXcM_4D7vf-pgNHetQ3A 
提取码：owdf 
使用paddleServing 部署这个模型
python3 -m paddle_serving_server_gpu.serve --model serving_server --port 9601 --gpu_ids 0 --use_multilang
多测试图片后就报这个错


import os

from paddle_serving_app.reader import *
from paddle_serving_client import MultiLangClient as Client

import numpy as np

preprocess = Sequential([
    File2Image(), BGR2RGB(), Div(255.0),
    Normalize([0.485, 0.456, 0.406], [0.229, 0.224, 0.225], False),
    Resize((640, 640)), Transpose((2, 0, 1))
])
client = Client()
client.connect(['192.168.1.210:9601'])
fetch_name = "save_infer_model/scale_0.tmp_1"

postprocess = RCNNPostprocess("label_list.txt", "output")

path = r'E:\Model\1'
for file in os.listdir(path):
    img_url = os.path.join(path, file)
    im = preprocess(img_url)
    fetch_map = client.predict(
        feed={
            "image": im,
            "im_shape": np.array(list(im.shape[1:])).reshape(-1),
            "scale_factor": np.array([1.0, 1.0]).reshape(-1),
        },
        fetch=[fetch_name],
        batch=False)
    fetch_map["image"] = img_url
    fetch_map.pop('serving_status_code')
    postprocess(fetch_map)

**Comment by TeslaZhao** [comment]
您好，你使用paddle Serving的版本是？
看您帖的代码中path = r'E:\Model\1'，这个路径是正确的吗，看起来像windows系统上路径名称？

**Comment by shawnLang** [comment]
> 您好，你使用paddle Serving的版本是？
> 看您帖的代码中path = r'E:\Model\1'，这个路径是正确的吗，看起来像windows系统上路径名称？
抱歉，现在才看到
使用的是 paddle-serving-server-gpu: 0.5.0, 在centos7上面部署运行的 这个代码是在本地windows下面运行 ，这个路径下面放的图片

**Comment by TeslaZhao** [comment]
您好，在您指定的环境下，使用您的代码并没有复现Bug。运行结果打印fetch_map，没有报错。

fetch_map : {'save_infer_model/scale_0.tmp_1': array([[2.70000000e+01, 7.69133270e-01, 2.14062469e+02, 4.35239624e+02,
        2.60595398e+02, 6.29475464e+02],
       [2.70000000e+01, 5.70183158e-01, 4.05497681e+02, 4.64471985e+02,
        4.45250061e+02, 6.39000000e+02],
       [2.70000000e+01, 5.60365498e-01, 2.60222168e+02, 4.56239410e+02,
        3.03686218e+02, 6.21883179e+02],
       ........
       [2.70000000e+01, 1.09752258e-02, 4.38363098e+02, 5.57994995e+02,
        4.74973938e+02, 6.39000000e+02]], dtype=float32), 'save_infer_model/scale_0.tmp_1.lod': array([  0, 100]), 'serving_status_code': 0, 'image': './imgs/000000570688.jpg'}
}

pip3.7 list | grep paddle : 
paddle-serving-app        0.3.0
paddle-serving-client     0.5.0
paddle-serving-server-gpu 0.5.0.post102
paddlepaddle-gpu          2.0.2

nvidia-smi:
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 418.67       Driver Version: 418.67       CUDA Version: 10.2     |
+-------------------------------+----------------------+----------------------+

建议：您排查一下，运行Serving的Detection示例是否出现类似问题。

**Comment by xingjing1** [comment]
infer 的 handle，我reshape的时候出了一些差错。  也报了同样错误，供参考

**Comment by MrTsien** [comment]
刚开始不会报错，连续预测，过一段时间就这个错误了，我也是cpu正常，gpu问题
