### ISSUE TITLE
安装错误:执行脚本安装PaddlePaddle但是下载失败

### ISSUE THREAD

**Issue by qing-1999** [PaddlePaddle/Paddle#32806]
为使您的问题得到快速解决，在建立Issue前，请您先通过如下方式搜索是否有相似问题:【搜索issue关键字】【使用labels筛选】【官方文档】

建立issue时，为快速解决问题，请您根据使用情况给出如下信息：
- 标题：请包含关键词“安装错误”/“编译错误”，例如“Mac编译错误”
- 版本、环境信息：
    1）PaddlePaddle版本：未安装
    2）CPU：请提供CPU型号: AMD Ryzen 7 4800H with Radeon Graphics，MKL/OpenBlas/MKLDNN/等数学库未安装
    3）GPU：请提供GPU型号: 00:0f.0 VGA compatible controller: VMware SVGA II Adapter  ，CUDA和CUDNN未安装
    4）系统环境：liunx系统: Linux centos7 3.10.0-1160.24.1.el7.x86_64 #1 SMP Thu Apr 8 19:51:47 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
、Python版本3.7.5
- 安装方式信息：
1）pip安装 pip版本21.1.1
执行脚本后下载飞浆失败: http://paddle-wheel.bj.bcebos.com/paddlepaddle-cpu-mkl/paddlepaddle-paddlepaddle-cp37-cp37m-linux_x86_64.whl
paddlepaddle whl包下载失败
wget err: http://paddle-wheel.bj.bcebos.com/paddlepaddle-cpu-mkl/paddlepaddle-paddlepaddle-cp37-cp37m-linux_x86_64.whl

**Comment by pangyoki** [comment]
> 为使您的问题得到快速解决，在建立Issue前，请您先通过如下方式搜索是否有相似问题:【搜索issue关键字】【使用labels筛选】【官方文档】
> 
> 建立issue时，为快速解决问题，请您根据使用情况给出如下信息：
> 
>     * 标题：请包含关键词“安装错误”/“编译错误”，例如“Mac编译错误”
> 
>     * 版本、环境信息：
>          1）PaddlePaddle版本：未安装
>          2）CPU：请提供CPU型号: AMD Ryzen 7 4800H with Radeon Graphics，MKL/OpenBlas/MKLDNN/等数学库未安装
>          3）GPU：请提供GPU型号: 00:0f.0 VGA compatible controller: VMware SVGA II Adapter  ，CUDA和CUDNN未安装
>          4）系统环境：liunx系统: Linux centos7 3.10.0-1160.24.1.el7.x86_64 #1 SMP Thu Apr 8 19:51:47 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
>       、Python版本3.7.5
> 
>     * 安装方式信息：
>       1）pip安装 pip版本21.1.1
>       执行脚本后下载飞浆失败: http://paddle-wheel.bj.bcebos.com/paddlepaddle-cpu-mkl/paddlepaddle-paddlepaddle-cp37-cp37m-linux_x86_64.whl
>       paddlepaddle whl包下载失败
>       wget err: http://paddle-wheel.bj.bcebos.com/paddlepaddle-cpu-mkl/paddlepaddle-paddlepaddle-cp37-cp37m-linux_x86_64.whl

请问这个安装包的链接是哪儿来的呢？看起来的确访问不到安装包。
你需要安装哪个版本的paddle呢？可以帮你找下相应的包。

**Comment by hhxdestiny** [comment]
> > 为使您的问题得到快速解决，在建立Issue前，请您先通过如下方式搜索是否有相似问题:【搜索issue关键字】【使用labels筛选】【官方文档】
> > 建立issue时，为快速解决问题，请您根据使用情况给出如下信息：
> > ```
> > * 标题：请包含关键词“安装错误”/“编译错误”，例如“Mac编译错误”
> > 
> > * 版本、环境信息：
> >      1）PaddlePaddle版本：未安装
> >      2）CPU：请提供CPU型号: AMD Ryzen 7 4800H with Radeon Graphics，MKL/OpenBlas/MKLDNN/等数学库未安装
> >      3）GPU：请提供GPU型号: 00:0f.0 VGA compatible controller: VMware SVGA II Adapter  ，CUDA和CUDNN未安装
> >      4）系统环境：liunx系统: Linux centos7 3.10.0-1160.24.1.el7.x86_64 #1 SMP Thu Apr 8 19:51:47 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
> >   、Python版本3.7.5
> > 
> > * 安装方式信息：
> >   1）pip安装 pip版本21.1.1
> >   执行脚本后下载飞浆失败: http://paddle-wheel.bj.bcebos.com/paddlepaddle-cpu-mkl/paddlepaddle-paddlepaddle-cp37-cp37m-linux_x86_64.whl
> >   paddlepaddle whl包下载失败
> >   wget err: http://paddle-wheel.bj.bcebos.com/paddlepaddle-cpu-mkl/paddlepaddle-paddlepaddle-cp37-cp37m-linux_x86_64.whl
> > ```
> 
> 请问这个安装包的链接是哪儿来的呢？看起来的确访问不到安装包。
> 你需要安装哪个版本的paddle呢？可以帮你找下相应的包。

貌似使用conda安装paddlepaddle-gpu-2.1大概率失败呢，能否换一下源，[清华](https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/Paddle/win-64/paddlepaddle-gpu-2.1.0-py38_gpu_cuda11.2_windows.tar.bz2)
的也太卡了
```bash
Downloading and Extracting Packages
paddlepaddle-gpu-2.1 | 344.3 MB  | ##1                                                             |   3% WARNING conda.gateways.disk.delete:unlink_or_rename_to_trash(143): Could not remove or rename C:\Users\destiny\anaconda3\pkgs\paddlepaddle-gpu-2.1.0-py38_gpu_cuda11.2_windows\Lib\site-packages\paddle\fluid\core_avx.pyd.  Please remove this file manually (you may need to reboot to free file handles)
paddlepaddle-gpu-2.1 | 344.3 MB  | ##1                                                             |   3%

CondaHTTPError: HTTP 000 CONNECTION FAILED for url <https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/Paddle/win-64/paddlepaddle-gpu-2.1.0-py38_gpu_cuda11.2_windows.tar.bz2>
Elapsed: -

An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.
```

**Comment by ycliu96** [comment]
> > > 为使您的问题得到快速解决，在建立Issue前，请您先通过如下方式搜索是否有相似问题:【搜索issue关键字】【使用labels筛选】【官方文档】
> > > 建立issue时，为快速解决问题，请您根据使用情况给出如下信息：
> > > ```
> > > * 标题：请包含关键词“安装错误”/“编译错误”，例如“Mac编译错误”
> > > 
> > > * 版本、环境信息：
> > >      1）PaddlePaddle版本：未安装
> > >      2）CPU：请提供CPU型号: AMD Ryzen 7 4800H with Radeon Graphics，MKL/OpenBlas/MKLDNN/等数学库未安装
> > >      3）GPU：请提供GPU型号: 00:0f.0 VGA compatible controller: VMware SVGA II Adapter  ，CUDA和CUDNN未安装
> > >      4）系统环境：liunx系统: Linux centos7 3.10.0-1160.24.1.el7.x86_64 #1 SMP Thu Apr 8 19:51:47 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
> > >   、Python版本3.7.5
> > > 
> > > * 安装方式信息：
> > >   1）pip安装 pip版本21.1.1
> > >   执行脚本后下载飞浆失败: http://paddle-wheel.bj.bcebos.com/paddlepaddle-cpu-mkl/paddlepaddle-paddlepaddle-cp37-cp37m-linux_x86_64.whl
> > >   paddlepaddle whl包下载失败
> > >   wget err: http://paddle-wheel.bj.bcebos.com/paddlepaddle-cpu-mkl/paddlepaddle-paddlepaddle-cp37-cp37m-linux_x86_64.whl
> > > ```
> > 
> > 
> > 请问这个安装包的链接是哪儿来的呢？看起来的确访问不到安装包。
> > 你需要安装哪个版本的paddle呢？可以帮你找下相应的包。
> 
> 貌似使用conda安装paddlepaddle-gpu-2.1大概率失败呢，能否换一下源，[清华](https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/Paddle/win-64/paddlepaddle-gpu-2.1.0-py38_gpu_cuda11.2_windows.tar.bz2)
> 的也太卡了
> 
> ```shell
> Downloading and Extracting Packages
> paddlepaddle-gpu-2.1 | 344.3 MB  | ##1                                                             |   3% WARNING conda.gateways.disk.delete:unlink_or_rename_to_trash(143): Could not remove or rename C:\Users\destiny\anaconda3\pkgs\paddlepaddle-gpu-2.1.0-py38_gpu_cuda11.2_windows\Lib\site-packages\paddle\fluid\core_avx.pyd.  Please remove this file manually (you may need to reboot to free file handles)
> paddlepaddle-gpu-2.1 | 344.3 MB  | ##1                                                             |   3%
> 
> CondaHTTPError: HTTP 000 CONNECTION FAILED for url <https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/Paddle/win-64/paddlepaddle-gpu-2.1.0-py38_gpu_cuda11.2_windows.tar.bz2>
> Elapsed: -
> 
> An HTTP error occurred when trying to retrieve this URL.
> HTTP errors are often intermittent, and a simple retry will get you on your way.
> ```也是这个问题
