### ISSUE TITLE
win10 源码编译错误

### ISSUE THREAD

**Issue by chccc1994** [PaddlePaddle/Paddle#32805]
-PaddlePaddle 版本:2.0
-GPU版本:显卡3080 CUDA 11.0 CUDNN 8.0.5
-Python版本 : 3.7.10方式信息：
本地编译：请提供cmake命令，编译命令
```python
cmake .. -G "Visual Studio 16 2019" -DWITH_GPU=ON -DWITH_TESTING=OFF -DCMAKE_BUILD_TYPE=Release -DPY_VERSION=3.7 -DCUDA_TOOLKIT_ROOT_DIR="C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\v11.0"
```
cmake 后在VS2019 生成解决方法时，一直提示 `无法打开包括文件: “paddle/fluid/framework/framework.pb.h”: No such file or directory`,` 无法打开包括文件: “paddle/fluid/platform/cuda_error.pb.h”: No such file or directory ` 等源码中都不包含这几个文件，怎么解决？？？？

![image](https://user-images.githubusercontent.com/68001817/117556839-bea97f80-b09f-11eb-92b8-4b7051d1330f.png)

**Comment by zhwesky2010** [comment]
@chccc5 您好，应该是前面编的时候挂了，这个pb.h是编译时生成的，生成失败了。cmake .. -G "Visual Studio 16 2019" -A x64 -DWITH_GPU=ON -DWITH_TESTING=OFF -DCMAKE_BUILD_TYPE=Release -DPY_VERSION=3.7，用这个试一下
