### ISSUE TITLE
请问以下ai studio平台的在线部署功能无法使用了吗

### ISSUE THREAD

**Issue by wkzqn** [PaddlePaddle/Paddle#32802]
![image](https://user-images.githubusercontent.com/44158381/117533540-f7097900-b01f-11eb-84fd-e27a9aefc0c4.png)

**Comment by ForFishes** [comment]
是服务问题。教程可以临时参考，https://ai.baidu.com/ai-doc/AISTUDIO/bk3e382cq#%E5%88%9B%E5%BB%BA%E4%B8%80%E4%B8%AA%E5%9C%A8%E7%BA%BF%E6%9C%8D%E5%8A%A1

**Comment by wkzqn** [comment]
谢谢。您的邮件已收到，我会尽快处理。
