### ISSUE TITLE
ERROR: No matching distribution found for paddlepaddle==2.0.2

### ISSUE THREAD

**Issue by htw2012** [PaddlePaddle/Paddle#32828]
ERROR: No matching distribution found for paddlepaddle==2.0.2

安装方式以及机器信息如下：

my9095@my9095:$ python -m pip install paddlepaddle==2.0.2 -i https://mirror.baidu.com/pypi/simple
Defaulting to user installation because normal site-packages is not writeable
Looking in indexes: https://mirror.baidu.com/pypi/simple
ERROR: Could not find a version that satisfies the requirement paddlepaddle==2.0.2 (from versions: none)
ERROR: No matching distribution found for paddlepaddle==2.0.2
my9095@my9095:$ uname -a
Linux my9095 4.9.140-tegra #1 SMP PREEMPT Tue Oct 27 21:02:37 PDT 2020 aarch64 aarch64 aarch64 GNU/Linux

**Comment by yaoxuefeng6** [comment]
可以试下清华源： python3 -m pip install paddlepaddle-gpu==[版本号] -i https://pypi.tuna.tsinghua.edu.cn/simple
或者尝试升级下pip

**Comment by wadefelix** [comment]
arm机器

**Comment by htw2012** [comment]
没有解决

**Comment by arzakmiftakhul** [comment]
I have the same problem on NVIDIA AGX Xavier, Ubuntu 18. Have you solved it?
