### ISSUE TITLE
添加gru及crf层后，训练过程中出现异常

### ISSUE THREAD

**Issue by zhoulei163** [PaddlePaddle/Paddle#32822]
Thank you for contributing to PaddlePaddle. Submitting an issue is a great help for us.
Both Chinese and English issues are welcome.

It's hard to solve a problem when important details are missing.
Before submitting the issue, look over the following criteria before handing your request in.

- [ ] Was there a similar issue submitted or resolved before ? You could search issue in the github.
- [ ] Did you retrieve your issue from widespread search engines ?
- [ ] Is my description of the issue clear enough to reproduce this problem?
   * If some errors occurred, we need details about `how do you run your code?`, `what system do you use?`, `Are you using GPU or not?`, etc.
   * If you use an recording [asciinema](https://asciinema.org/) to show what you are doing to make it happen, that's awesome! We could help you solve the problem more quickly.
- [ ] Is my description of the issue use the github markdown correctly?
   * Please use the proper markdown syntaxes for styling all forms of writing, e.g, source code, error information, etc.
   * Check out [this page](https://guides.github.com/features/mastering-markdown/) to find out much more about markdown.
Traceback (most recent call last):
  File "sequence_labeling.py", line 426, in <module>
    do_train()
  File "sequence_labeling.py", line 334, in do_train
    loss.backward()
  File "</opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/decorator.py:decorator-gen-114>", line 2, in backward
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
    return wrapped_func(*args, **kwargs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/framework.py", line 225, in __impl__
    return func(*args, **kwargs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/varbase_patch_methods.py", line 177, in backward
    self._run_backward(framework._dygraph_tracer(), retain_graph)
OSError: (External)  Cublas error, `CUBLAS_STATUS_INTERNAL_ERROR`. An internal cuBLAS operation failed. This error is usually caused by a cudaMemcpyAsync() failure.  (at /paddle/paddle/fluid/operators/math/blas_impl.cu.h:35)

**Comment by zhoulei163** [comment]
`
class Model_ernie(ErnieForTokenClassification):
    def __init__(self, ernie, num_classes, dropout=None, gru_hidden_size=128):
        super(Model_ernie, self).__init__(ernie, num_classes)
        self.num_classes = num_classes
        self.ernie = ernie
        self.dropout = nn.Dropout(dropout if dropout is not None else
                                  self.ernie.config["hidden_dropout_prob"])
        # add bi-gru
        self.gru = nn.GRU(
            input_size=self.ernie.config["hidden_size"],
            hidden_size=gru_hidden_size,
            direction='bidirect')
        self.fc = nn.Linear(
            in_features=gru_hidden_size * 2,
            out_features=num_classes)
        # add crf
        self.crf = LinearChainCrf(
            num_classes,
            with_start_stop_tag=False)
        self.crf_loss = LinearChainCrfLoss(self.crf)
        self.viterbi_decoder = ViterbiDecoder(
            self.crf.transitions,
            with_start_stop_tag=False)


    def forward(self,
                input_ids,
                token_type_ids=None,
                position_ids=None,    # sequence lengths
                attention_mask=None  # labels
                ):
        
        sequence_output, _ = self.ernie(
            input_ids,
            token_type_ids=token_type_ids
        )
        # print('attention_mask', type(attention_mask), attention_mask)
        sequence_output = self.dropout(sequence_output)
        bigru_output, _ = self.gru(sequence_output)
        emission = self.fc(bigru_output)
        _, prediction = self.viterbi_decoder(emission, position_ids)
        if attention_mask is not None:
            loss = self.crf_loss(emission, position_ids, prediction, attention_mask)
            # return loss.mean(), position_ids, prediction, attention_mask
            return loss.mean(), emission, prediction
        else:
            # return position_ids, prediction
            return emission, prediction
`

loss, emission, prediction = model(input_ids=input_ids, token_type_ids=token_type_ids, position_ids=seq_lens, attention_mask=labels)
loss.backward()
添加gru及crf层，计算loss时，
train epoch: 0 - step: 360 (total: 29900) - loss: 0.000000
train epoch: 0 - step: 370 (total: 29900) - loss: 0.000000
train epoch: 0 - step: 380 (total: 29900) - loss: 0.000000
train epoch: 0 - step: 390 (total: 29900) - loss: 0.000000
train epoch: 0 - step: 400 (total: 29900) - loss: 0.000000

**Comment by allurelzh** [comment]
我遇到了同样的问题，请问最后是如何解决的呢？
