### ISSUE TITLE
Error: cannot import name 'build_slim_model'

### ISSUE THREAD

**Issue by johnhansheng** [PaddlePaddle/Paddle#32849]
执行命令：python infers/infer.py -c configs/blazeface_1000e.yml  -o weights=weights/blazeface_1000e.pdparams  --infer_img=test/16pic_8594349_b.jpg --save_txt=True
报错，from ppdet.slim import build_slim_model ImportError: cannot import name 'build_slim_model'。

**Comment by yghstill** [comment]
@johnhansheng PaddleDetection版本是多少？使用release/2.0版本再试下呢？https://github.com/PaddlePaddle/PaddleDetection/tree/release/2.0

**Comment by johnhansheng** [comment]
v2.0.2版本，目前我们的模型只支持v2.0.2版本
