### ISSUE TITLE
动态图训练出现loss inf

### ISSUE THREAD

**Issue by tangzhiyi11** [PaddlePaddle/Paddle#32862]
动态图训练出现loss inf，静态图是有个  FLAGS_check_nan_inf 的环境变量来辅助调试，动态图貌似给去掉了？请问动态图有类似的调试方法么？

**Comment by huangjun12** [comment]
动态图调试更加简单，可以直接打印各层的输出，定位出loss为Inf的原因

**Comment by tangzhiyi11** [comment]
> 动态图调试更加简单，可以直接打印各层的输出，定位出loss为Inf的原因

@huangjun12 每层打印还是有点不方便吧，因为我大多数使用的是套件里的训练脚本，已经封装好了模型，是否可以提供类似之前的环境变量，来方便定位具体出现inf的算子
