### ISSUE TITLE
paddle2.0支持华为昇腾910加速吗？

### ISSUE THREAD

**Issue by zyl112334** [PaddlePaddle/Paddle#32873]
- 版本、环境信息：
    1）PaddlePaddle版本：2.0+
    2）GPU：昇腾910
    3）系统环境：Linux version 4.14.0-115.el7a.0.1.aarch64
    
请问，目前paddle能否支持在华为的昇腾910上加速推理运算呢？

**Comment by zhiqiu** [comment]
目前Paddle+Ascend910正在适配中，我们会在2.1版本发布一个experimental版本的支持。
