### ISSUE TITLE
训练一轮之后执行评估，显存增加一倍？

### ISSUE THREAD

**Issue by yeyupiaoling** [PaddlePaddle/Paddle#32888]
- PaddlePaddle 2.0.2
 - Ubuntu 18.04
 - Python 3.7

以前的Fluid版本无论是训练还是训练完之后评估，前后的显存都差别不大。
但是2.0版本的，执行评估是，显存会增加一倍，而且评估结束之后并没有释放。
例如：在训练时只占3.8G，之后执行执行评估后就占用了6.0G，这种情况怎么解决
![image](https://user-images.githubusercontent.com/26297768/118085693-60f59a00-b3f5-11eb-90e1-cf7748653a21.png)

**Comment by Aurelius84** [comment]
方便问下之前使用的paddle版本是哪个？也是动态图下训练么？

另外，执行评估时显存占用上升到6G，评估函数执行完，显存会回落到3.8G么？

**Comment by yeyupiaoling** [comment]
说就是举个例，不是同一个项目。全部的Fluid版本的显存在训练阶段基本不会变的。

>另外，执行评估时显存占用上升到6G，评估函数执行完，显存会回落到3.8G么？

不会，反而慢慢增加。

**Comment by Aurelius84** [comment]
咨询了下组内同学，eval时上升是符合预期的，如果你eval阶段不需要计算反向，可以在评估的函数上加上`@paddle.no_grad`

**Comment by yeyupiaoling** [comment]
@好的，谢谢。我先试试。
