### ISSUE TITLE
加权BCELoss()如何实现

### ISSUE THREAD

**Issue by HXia-XXL** [PaddlePaddle/Paddle#32882]
`class paddle.nn.BCELoss(weight=None, reduction='mean', name=None)`

BCELoss函数没有axis参数，在底层调用 elementwise_mul() 默认按axis=-1

`out = core.ops.elementwise_mul(out, weight, 'axis', -1)`

但是，Input数据一般为 [B,C,H,W]格式。请问如何指定 axis = 1 呢？

还有一个疑问，BCELoss() 函数需要 weight 和 channel 相同维度，Input的channel通常为1。

现在设 weight = [ 0.3, 0.7 ]，维度是2，无法对 Input计算加权损失。

请问，如何只用 1 维的weight 对 二分类进行加权？

感谢您的帮助！

**Comment by HXia-XXL** [comment]
![image](https://user-images.githubusercontent.com/44633898/118070192-0863d400-b3d8-11eb-8e81-09a8176e5c40.png)

**Comment by Steffy-zxf** [comment]
@HXia-XXL  你好！如果你想对输入`input`的channel进行加权平均的话，可以在BCELoss运算之前直接对`input`进行channel加权。[BCELoss](https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/nn/layer/loss/BCELoss_cn.html#bceloss)参数`weight`是对batch中的每个sample进行加权，所以`weight`的shape应该是(batch_size)。

**Comment by HXia-XXL** [comment]
好的，感谢解答
