### ISSUE TITLE
PaddlePaddle是否支持rocm

### ISSUE THREAD

**Issue by zhangjia3** [PaddlePaddle/Paddle#32895]
PaddlePaddle是否支持AMD显卡？

**Comment by Aurelius84** [comment]
您好，已经支持了。

**Comment by zhangjia3** [comment]
非常感谢您的回复！请问如何在AMD显卡上安装paddlepaddle，是否有相关教程或者镜像。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年5月13日(周四) 晚上7:45
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [PaddlePaddle/Paddle] PaddlePaddle是否支持rocm (#32895)




 
您好，已经支持了。

**Comment by Aurelius84** [comment]
支持ROCM的whl 包将随2.1.0版本发布，安装教程参考：https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/guides/rocm_docs/index_cn.html
