### ISSUE TITLE
Mac M1芯片在这个位置会有一个错误提示，需要修改成兼容的

### ISSUE THREAD

**Issue by DDDivano** [PaddlePaddle/Paddle#32894]
https://github.com/PaddlePaddle/Paddle/blob/7610c2b4aaa2addccc100728794c5f00078f687f/python/paddle/fluid/core.py#L96
import paddle就可以复现，不影响正常使用，m1芯片没有这个命令。
![image](https://user-images.githubusercontent.com/10734244/118098737-d9188b80-b406-11eb-997b-5827f08b0d38.png)

**Comment by Aurelius84** [comment]
非常感谢您的反馈，我们会优化一下。另外，Mac M1芯片的会逐步适配。

**Comment by tianshuo78520a** [comment]
这个[PR](https://github.com/PaddlePaddle/Paddle/pull/34309)解决了问题
