### ISSUE TITLE
dynamic_lstm 迁移到 tensorflow

### ISSUE THREAD

**Issue by rphao1995** [PaddlePaddle/Paddle#32893]
PaddlePaddle 版本 1.8.5
tensorflow 版本 1.8
使用的是 paddle.fluid.layers.dynamic_lstm。文档中说，在使用dynamic_lstm前需要进行 线性映射(fc)。
这样涉及到4个权重，分别是，lstm_kernel, lstm_bias, fc_kernel, fc_bias(我需要迁移的模型的fc使用了偏置)
假设 输入特征维度是 8 ，输出维度是 128，则这四个权重的 shape 分别为 lstm_kernel（128, 512）、lstm_bias(512)、fc_kernel(8, 512)、fc_bias(512)

tensorflow 里，BasicLSTM的只有两个权重 lstm_kernel(136, 512)，lstm_bias(512)
我应该怎么操作 PaddlePaddle 里的权重使得它和 tensorflow 的权重等效呢？

我尝试过 
tf_lstm_kernel = concat(paddle_fc_kernel, paddle_lstm_kernel)
tf_lstm_bias = add(paddle_fc_bias, paddle_lstm_bias)
但结果不对，没有这么简单

**Comment by rphao1995** [comment]
# i = input_gate, j = new_input, f = forget_gate, o = output_gate

**Comment by rphao1995** [comment]
Tensorflow 的 BasicLSTMCell 
https://github.com/tensorflow/tensorflow/blob/23c218785eac5bfe737eec4f8081fd0ef8e0684d/tensorflow/python/ops/rnn_cell_impl.py#L519
在内部矩阵乘后，把 136,512 的矩阵分为了四份，分别是 输入门，状态更新，遗忘门，输出门。
怀疑和这个有关，把权重的顺序换成 输入门，遗忘门，输出门，状态更新 的顺序，但没用。paddle的顺序是怎样的？

**Comment by Aurelius84** [comment]
Paddle中dynamic_lstm接口会自动进行门接口相关的权重设置，只需要输入hidden_size即可。

参考接口样例：
```python
import paddle.fluid as fluid
emb_dim = 256
vocab_size = 10000
hidden_dim = 512

data = fluid.layers.data(name='x', shape=[1], dtype='int32', lod_level=1)
emb = fluid.layers.embedding(input=data, size=[vocab_size, emb_dim], is_sparse=True)

forward_proj = fluid.layers.fc(input=emb, size=hidden_dim * 4, bias_attr=False)
forward, cell = fluid.layers.dynamic_lstm(input=forward_proj, size=hidden_dim * 4, use_peepholes=False)
forward.shape  # (-1, 512)
cell.shape  # (-1, 512)
```

**Comment by rphao1995** [comment]
Paddle 的 lstm 实现确实是这样，但这不符合我的需求。
我需要把  paddle 的lstm权重迁移到tensorflow里。我应该对 Paddle 的权重做怎样的变换，使得它和 tensorflow 的等效呢？

**Comment by rphao1995** [comment]
或者 paddle 的 dynamic_lstm 源码在哪呢？
https://github.com/PaddlePaddle/Paddle/blob/af5bb2a3d98cba4733e98b57c5bd34a7edce9767/python/paddle/fluid/layers/nn.py#L691
从这份代码里，我完全看不出  dynamic_lstm  是如何计算的

**Comment by rphao1995** [comment]
我试出来了，Paddle 的 dynamic_lstm 的顺序是  状态更新，输入门，遗忘门，输出门，把权重的变换顺序后可以复现BasicLSTM的结果。如果输入特征维度是 8 ，输出维度是 128的话，具体操作是这样：
tf_lstm_kernel = concat(paddle_fc_kernel, paddle_lstm_kernel)
tf_lstm_kernel = concat(tf_lstm_kernel[:, 128:256], tf_lstm_kernel[:, :128],  tf_lstm_kernel[:, 256:512], axis=-1)

tf_lstm_bias = add(paddle_fc_bias, paddle_lstm_bias)
tf_lstm_bias = concat(tf_lstm_bias[128:256], tf_lstm_bias[:128],  tf_lstm_bias[256:512], axis=-1)

但是不知道是精度问题还是lstm的具体实现问题，只有 step1 的结果误差很小，step2 的误差就无法接受了。
