### ISSUE TITLE
index_select改变元素的cpu的device

### ISSUE THREAD

**Issue by BlackHorseQ** [PaddlePaddle/Paddle#32909]
x = paddle.to_tensor([[1.0, 2.0, 3.0, 4.0],
                     [5.0, 6.0, 7.0, 8.0],
                     [9.0, 10.0, 11.0, 12.0]], place='cpu')
print(x.place)
index = paddle.to_tensor([0, 1, 1], dtype='int32', place='cpu')
print(index.place)
paddle.index_select(x=x, index=index)
print(x.place)
![image](https://user-images.githubusercontent.com/71745501/118243431-07629d80-b4d1-11eb-90ca-79836cbf9b01.png)
如何让index_select使元素的device保持一致。

**Comment by LDOUBLEV** [comment]
在代码开始之前，加一行代码： paddle.set_device("cpu")，设置代码运行在CPU上

https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/device/set_device_cn.html#set-device
