### ISSUE TITLE
模型太大，单卡放不下，paddle有好的解决方案嘛

### ISSUE THREAD

**Issue by BlackHorseQ** [PaddlePaddle/Paddle#32905]
就是模型太大，怎么办啊？
主要是6个embedding太大了，现在只能放下五个，剩余一个放不下，放在另一个卡会报错

**Comment by LDOUBLEV** [comment]
主要是减少显存占用，试试这个方法：https://www.paddlepaddle.org.cn/documentation/docs/zh/faq/train_cn.html#wenti-xunlianshibaocuotishixiancunbuzu-ruhejiejue
