### ISSUE TITLE
这个代码在部分操作系统下会报乱码

### ISSUE THREAD

**Issue by DDDivano** [PaddlePaddle/Paddle#32919]
https://github.com/PaddlePaddle/Paddle/blob/51b39a94e436d5c09b26efce38da81391c184e46/python/paddle/utils/deprecated.py#L101
不影响使用，需要修改兼容性。
![image](https://user-images.githubusercontent.com/10734244/118268501-09882480-b4f0-11eb-997a-10f6474c9231.png)
![image](https://user-images.githubusercontent.com/10734244/118268576-1d338b00-b4f0-11eb-9781-2b0ab7ef876a.png)

非bash都可能报乱码

**Comment by LDOUBLEV** [comment]
确实，非bash的可能出现乱码，感谢反馈
