### ISSUE TITLE
AssertionError: optimizer Tensor conv2d_53.w_0_velocity_0 not found

### ISSUE THREAD

**Issue by crazyxiaoj** [PaddlePaddle/Paddle#32926]
- 版本、环境信息：
    1）PaddlePaddle版本：2.0
    2）系统环境：AIStudio 高级版
- 训练信息
    1）单机，单卡
- 复现信息：

[issue.md](https://github.com/PaddlePaddle/Paddle/files/6488768/issue.md)

按文件中的代码运行后，把最后一个cell的代码修改一下：
![image](https://user-images.githubusercontent.com/50630515/118387639-1f155f80-b652-11eb-9ae9-1bcd4a238019.png)
把框中的代码取消注释，即可复现问题

- 问题描述：

报错信息：
Epoch 0: PiecewiseDecay set learning rate to 0.1.
---------------------------------------------------------------------------AssertionError                            Traceback (most recent call last)<ipython-input-7-bd53896a480e> in <module>
     40 opt_dict = paddle.load(params_path + '.pdopt')
     41 model.set_state_dict(params_dict)
---> 42 opt.set_state_dict(opt_dict)
     43 # *******************************************
     44 for epoch in range(epochs_num):
</opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/decorator.py:decorator-gen-314> in set_state_dict(self, state_dict)
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/wrapped_decorator.py in __impl__(func, *args, **kwargs)
     23     def __impl__(func, *args, **kwargs):
     24         wrapped_func = decorator_func(func)
---> 25         return wrapped_func(*args, **kwargs)
     26 
     27     return __impl__
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/framework.py in __impl__(*args, **kwargs)
    223         assert in_dygraph_mode(
    224         ), "We only support '%s()' in dynamic graph mode, please call 'paddle.disable_static()' to enter dynamic graph mode." % func.__name__
--> 225         return func(*args, **kwargs)
    226 
    227     return __impl__
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/optimizer/optimizer.py in set_state_dict(self, state_dict)
    222             for para_name, var_tmp in v.items():
    223                 assert var_tmp.name in state_dict, \
--> 224                         "optimizer Tensor {} not found".format( var_tmp.name )
    225                 var = var_tmp.value()
    226                 tensor = var.get_tensor()
AssertionError: optimizer Tensor conv2d_53.w_0_velocity_0 not found

**Comment by JZ-LIANG** [comment]
报错原因是：load 模型时， 指定目录下没有找到对应var 的文件 （conv2d_53.w_0_velocity_0）
请确认按注释修改后的目录中有完整的 模型训练文件（param + opt state）:
 
- 对于 Layer.state_dict ，推荐使用后缀 .pdparams ； 
- 对于 Optimizer.state_dict ，推荐使用后缀 .pdopt


并需要确认模型save 时是 save for training：https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/hapi/model/Model_cn.html#save-path-training-true

**Comment by crazyxiaoj** [comment]
> 报错原因是：load 模型时， 指定目录下没有找到对应var 的文件 （conv2d_53.w_0_velocity_0）
> 请确认按注释修改后的目录中有完整的 模型训练文件（param + opt state）:
> 
> * 对于 Layer.state_dict ，推荐使用后缀 .pdparams ；
> * 对于 Optimizer.state_dict ，推荐使用后缀 .pdopt
> 
> 并需要确认模型save 时是 save for training：https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/hapi/model/Model_cn.html#save-path-training-true

好的，我看了您提供的链接，同时注意到，您所给链接中的paddle.save方法是应用于静态图的，那么有没有适用于动态图的解决方案呢？
此外：
![image](https://user-images.githubusercontent.com/50630515/118425705-4e80a680-b6fc-11eb-91ec-f7905b8ffbb6.png)
指定目录下含有.pdparams和.pdopt两个文件，您可以通过运行“复现代码”来再次进行验证。

**Comment by JZ-LIANG** [comment]
我运行了你.md 文件里的代码， 注释前 和注释后都能跑通。 不能复现你遇到的bug。
教程里 save load 的接口使用应该没有问题。

感觉像是opt state 没有保存成功？ 我checkpoint 路径下的文件和大小如下， 你可以核对一下

```shell
λ /mlperf/work/somecode ll checkpoint/
total 811M
drwxr-xr-x 2 root root 4.0K May 17 20:09 ./
drwxr-xr-x 4 root root 4.0K May 17 20:05 ../
-rw-r--r-- 1 root root 135M May 17 20:05 mnist_epoch0.pdopt
-rw-r--r-- 1 root root 135M May 17 20:05 mnist_epoch0.pdparams
-rw-r--r-- 1 root root 136M May 17 20:08 mnist_epoch1.pdopt
-rw-r--r-- 1 root root 135M May 17 20:08 mnist_epoch1.pdparams
-rw-r--r-- 1 root root 136M May 17 20:09 mnist_epoch2.pdopt
-rw-r--r-- 1 root root 135M May 17 20:09 mnist_epoch2.pdparams
```

**Comment by crazyxiaoj** [comment]
> 我运行了你.md 文件里的代码， 注释前 和注释后都能跑通。 不能复现你遇到的bug。
> 教程里 save load 的接口使用应该没有问题。
> 
> 感觉像是opt state 没有保存成功？ 我checkpoint 路径下的文件和大小如下， 你可以核对一下
> 
> ```shell
> λ /mlperf/work/somecode ll checkpoint/
> total 811M
> drwxr-xr-x 2 root root 4.0K May 17 20:09 ./
> drwxr-xr-x 4 root root 4.0K May 17 20:05 ../
> -rw-r--r-- 1 root root 135M May 17 20:05 mnist_epoch0.pdopt
> -rw-r--r-- 1 root root 135M May 17 20:05 mnist_epoch0.pdparams
> -rw-r--r-- 1 root root 136M May 17 20:08 mnist_epoch1.pdopt
> -rw-r--r-- 1 root root 135M May 17 20:08 mnist_epoch1.pdparams
> -rw-r--r-- 1 root root 136M May 17 20:09 mnist_epoch2.pdopt
> -rw-r--r-- 1 root root 135M May 17 20:09 mnist_epoch2.pdparams
> ```

您好，您再尝试使用AIStudio，notebook环境试一下？我觉得可能与notebook有关

**Comment by JZ-LIANG** [comment]
我们本地没有 AIstudio 环境 lol， 你是说网页端吗？ 能不能发一个链接

**Comment by crazyxiaoj** [comment]
> 我们本地没有 AIstudio 环境 lol， 你是说网页端吗？ 能不能发一个链接

项目“issue”共享链接(有效期三天)：https://aistudio.baidu.com/studio/project/partial/verify/1925918/c637cce11c8347359fcb8e2f6c82ca4d

**Comment by crazyxiaoj** [comment]
> 我们本地没有 AIstudio 环境 lol， 你是说网页端吗？ 能不能发一个链接

您好，距离我提供临时链接已经过去两天了，我注意到这个链接的有效期仅有3天，如果您已经fork代码或发现链接已经失效及其他问题，请回复我，我将试着解决

**Comment by chenxiaozeng** [comment]
> > 我们本地没有 AIstudio 环境 lol， 你是说网页端吗？ 能不能发一个链接
> 
> 您好，距离我提供临时链接已经过去两天了，我注意到这个链接的有效期仅有3天，如果您已经fork代码或发现链接已经失效及其他问题，请回复我，我将试着解决

您好，我们check官方提供的项目是没问题的，辛苦您再分享下项目链接，我们可帮您排查下

**Comment by crazyxiaoj** [comment]
> > > 我们本地没有 AIstudio 环境 lol， 你是说网页端吗？ 能不能发一个链接
> > 
> > 
> > 您好，距离我提供临时链接已经过去两天了，我注意到这个链接的有效期仅有3天，如果您已经fork代码或发现链接已经失效及其他问题，请回复我，我将试着解决
> 
> 您好，我们check官方提供的项目是没问题的，辛苦您再分享下项目链接，我们可帮您排查下

项目“issue”共享链接(有效期三天)：https://aistudio.baidu.com/studio/project/partial/verify/1925918/b7d2320369b14f29ad907f69191c6512

**Comment by crazyxiaoj** [comment]
Is anybody there?
