### ISSUE TITLE
【论文复现】DataLoader  RuntimeError

### ISSUE THREAD

**Issue by cisco08** [PaddlePaddle/Paddle#32923]
1）PaddlePaddle版本：2.0.2
    2）系统环境： AIstudio
    3）报错如下: 动态图的dataloader  调用next时queue变成空的时候会异常
 RuntimeError: DataLoader 1 workers exit unexpectedly, pids: 2149

---------------------------------------------------------------------------SystemError                               Traceback (most recent call last)<ipython-input-155-da60038f3a63> in <module>
      1 # 读取数据
      2 reader = paddle.io.DataLoader(train_dataset, batch_size=2, shuffle=True, num_workers=1, drop_last=True)
----> 3 img, gt_boxes, gt_labels, im_shape = next(reader())
      4 img, gt_boxes, gt_labels, im_shape = img.numpy(), gt_boxes.numpy(), gt_labels.numpy(), im_shape.numpy()
      5 # 计算出锚框对应的标签
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dataloader/dataloader_iter.py in __next__(self)
    777 
    778             if in_dygraph_mode():
--> 779                 data = self._reader.read_next_var_list()
    780             else:
    781                 if self._return_list:
SystemError: (Fatal) Blocking queue is killed because the data reader raises an exception.
  [Hint: Expected killed_ != true, but received killed_:1 == true:1.] (at /paddle/paddle/fluid/operators/reader/blocking_queue.h:158)

**Comment by wangxicoding** [comment]
看起来是数据读取出问题了，每次运行都会复现吗

**Comment by lazyn1997** [comment]
work_num按默认设置为2，每次跑完第一次迭代后都会出现上述的错误，将work_num改为0后速度变慢很多，大约为原来的四分之一。

> 看起来是数据读取出问题了，每次运行都会复现吗

**Comment by cisco08** [comment]
是的，只要设置大于1的都会报错



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: lazyn1997 ***@***.***&gt;
发送时间: 2021年5月21日 22:23
收件人: PaddlePaddle/Paddle ***@***.***&gt;
抄送: cisco08 ***@***.***&gt;, Author ***@***.***&gt;
主题: 回复：[PaddlePaddle/Paddle] 【论文复现】DataLoader  RuntimeError (#32923)





 
work_num按默认设置为2，每次跑完第一次迭代后都会出现上述的错误，将work_num改为0后速度变慢很多，大约为原来的四分之一。
  
看起来是数据读取出问题了，每次运行都会复现吗

**Comment by wangxicoding** [comment]
@cisco08 有复现代码吗

**Comment by wangxicoding** [comment]
> 是的，只要设置大于1的都会报错 发自我的iPhone
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: lazyn1997 ***@***.***&gt; 发送时间: 2021年5月21日 22:23 收件人: PaddlePaddle/Paddle ***@***.***&gt; 抄送: cisco08 ***@***.***&gt;, Author ***@***.***&gt; 主题: 回复：[PaddlePaddle/Paddle] 【论文复现】DataLoader RuntimeError (#32923) work_num按默认设置为2，每次跑完第一次迭代后都会出现上述的错误，将work_num改为0后速度变慢很多，大约为原来的四分之一。 看起来是数据读取出问题了，每次运行都会复现吗 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

`df -h` 看一下shm的大小，我怀疑是shm太小，设置work_num > 1时超过了shm大小，导致的出错
![image](https://user-images.githubusercontent.com/10208305/119510000-b8a3e600-bda3-11eb-8d63-e21ea477092a.png)

**Comment by lazyn1997** [comment]
> > 是的，只要设置大于1的都会报错 发自我的iPhone
> > […](#)
> > ------------------ 原始邮件 ------------------ 发件人: lazyn1997 _**@**_._**> 发送时间: 2021年5月21日 22:23 收件人: PaddlePaddle/Paddle _**@**_.**_> 抄送: cisco08 _**@**_._**>, Author _**@**_.**_> 主题: 回复：[PaddlePaddle/Paddle] 【论文复现】DataLoader RuntimeError (#32923) work_num按默认设置为2，每次跑完第一次迭代后都会出现上述的错误，将work_num改为0后速度变慢很多，大约为原来的四分之一。 看起来是数据读取出问题了，每次运行都会复现吗 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.
> 
> `df -h` 看一下shm的大小，我怀疑是shm太小，设置work_num > 1时超过了shm大小，导致的出错
> ![image](https://user-images.githubusercontent.com/10208305/119510000-b8a3e600-bda3-11eb-8d63-e21ea477092a.png)

应该不是shm的问题，我把大小设为0后跑完一次迭代依然报错，把--eval去掉就可以正常训练了。

**Comment by wangxicoding** [comment]
> 应该不是shm的问题，我把大小设为0后跑完一次迭代依然报错，把--eval去掉就可以正常训练了。

理一下，目前的问题是不管如何设置worker_num，跑完第一次迭代后eval时会报错，如果将eval去掉，那么设置worker_num为任意值都不会出错？那么这个错误应该是eval造成的?
