### ISSUE TITLE
尝试自定义算子，怎么得到头文件？

### ISSUE THREAD

**Issue by thunder95** [PaddlePaddle/Paddle#32945]
参考： https://www.paddlepaddle.org.cn/documentation/docs/zh/guides/07_new_op/new_custom_op.html
"paddle/extension.h" 这样的头文件哪里获得

必须要源码编译安装paddlepaddle吗，能否不安装? 我只是python安装了paddle

文档中没有提及到前面如何操作，建议补上。

**Comment by chenwhql** [comment]
不需要，python安装paddle之后，头文件会在python库目录下，直接include使用即可，这个头文件基本没什么内容，需要看的话到python安装目录下的paddle/include中查看

头文件目录也有说明
![image](https://user-images.githubusercontent.com/22561442/118617744-80296880-b7f5-11eb-9206-093094699211.png)


至于是否需要编译安装paddle，文档里面写的已经很清楚了
![image](https://user-images.githubusercontent.com/22561442/118617489-45273500-b7f5-11eb-9023-96dcb38dd279.png)

**Comment by thunder95** [comment]
ok, 谢谢
