### ISSUE TITLE
fatal: unable to access 'https://gitlab.com/libeigen/eigen.git/': gnutls_handshake() failed: Error in the pull function.

### ISSUE THREAD

**Issue by johnhansheng** [PaddlePaddle/Paddle#32944]
jetson nano（系统参数：Linux my9095 4.9.140-tegra #1 SMP PREEMPT Tue Oct 27 21:02:37 PDT 2020 aarch64 aarch64 aarch64 GNU/Linux），编译paddle v2.0.2版本，出现了这个问题，请问怎么解决
![WechatIMG25](https://user-images.githubusercontent.com/26408135/118560697-7a536900-b79c-11eb-94c5-72a5c25d9616.png)

**Comment by pangyoki** [comment]
你好，这个看起来是网络问题，你这边可以访问到gitlab吗？

**Comment by johnhansheng** [comment]
仓库地址改变了，导致无法clone

**Comment by pangyoki** [comment]
好的

**Comment by johnhansheng** [comment]
怎么修改仓库地址，继续编译？？

**Comment by johnhansheng** [comment]
我尝试修改了仓库地址，出现了新的错误
![WX20210518-201314](https://user-images.githubusercontent.com/26408135/118648894-74e63500-b815-11eb-910c-3c672cb418ba.png)

**Comment by pangyoki** [comment]
有尝试`git clone https://gitlab.com/libeigen/eigen.git`吗？我这编clone这个库是没问题的

**Comment by johnhansheng** [comment]
我用的是 nano的主板，你用的是什么主板？

**Comment by pangyoki** [comment]
这个感觉跟nano主板没关系，看着还是网络问题，国内网络git clone比较困难。
建议使用我们官方发的包哈。

https://www.paddlepaddle.org.cn/documentation/docs/zh/install/Tables.html
![图片](https://user-images.githubusercontent.com/26408901/118753107-d8647700-b896-11eb-90d0-b39f98d5d8f3.png)

预测库
https://paddleinference.paddlepaddle.org.cn/user_guides/download_lib.html

![图片](https://user-images.githubusercontent.com/26408901/118753120-e2867580-b896-11eb-99fe-93322d49f125.png)

**Comment by johnhansheng** [comment]
![WX20210519-162038](https://user-images.githubusercontent.com/26408135/118779882-13c66c00-b8be-11eb-82de-ba8a246595cc.png)
系统配置如下，安装官方推荐的2.1.0whl文件想，显示不支持该机器。

**Comment by pangyoki** [comment]
用的是上面链接里jetpack的包吗？

**Comment by johnhansheng** [comment]
是的  安装这个paddlepaddle_gpu-2.1.0-cp36-cp36m-linux_aarch64.whl

**Comment by johnhansheng** [comment]
![3](https://user-images.githubusercontent.com/26408135/118781194-5d638680-b8bf-11eb-84de-0ae8a08ac635.png)
安装后的结果如下：

**Comment by pangyoki** [comment]
这个是warning，应该不影响的。run_check执行也成功了

**Comment by pangyoki** [comment]
这个“AVX not support”是warning，不影响的。run_check也成功了

**Comment by johnhansheng** [comment]
但是检测速度 非常慢，达到几十秒

**Comment by johnhansheng** [comment]
安装没有问题，但是和机器不适配，同时耗时较长，这个是什么原因？

**Comment by pangyoki** [comment]
这个warning只是提示你的机器里没有AVX，安装的包是适配的，也支持noavx。不然`import paddle`直接会报错的。
检测慢，是因为run_check的逻辑里会执行一个小网络，使用GPU确实比较慢一点，这个是正常的，对使用没有影响。

**Comment by johnhansheng** [comment]
可否配置 avx指令集，提升运行速度。

**Comment by johnhansheng** [comment]
![4](https://user-images.githubusercontent.com/26408135/118799832-c94eea80-b8d1-11eb-90b9-c74b30d17e47.png)
测试模型，运行时间如下：    比较长
