### ISSUE TITLE
请问，如何在 enable_static() 模式下，在组网阶段，用numpy array 去初始化一个变量呢？ 

### ISSUE THREAD

**Issue by OleNet** [PaddlePaddle/Paddle#32943]
请问，如何在 enable_static() 模式下，在组网阶段，用numpy array 去初始化一个变量呢？ 我写了如下的函数，但是var_t变量的值仍然是随机值

```
def get_global_mask(seqlen, n_local, n_global):
    var_name = "_global_mask"
    var = fluid.global_scope().find_var(var_name)
    if var is not None:
        print('var is not None')
        return var

    global_mask_np = np.tri(seqlen, seqlen).astype('float32')

    place = fluid.CUDAPlace(0)

    var = L.create_parameter(name=var_name,
                             shape=[seqlen, seqlen],
                             dtype='float32')
    var.stop_gradient = True
    vat_t = var.get_tensor()
    var_t.set(global_mask_np, place)
```

**Comment by vslyu** [comment]
> 请问，如何在 enable_static() 模式下，在组网阶段，用numpy array 去初始化一个变量呢？ 我写了如下的函数，但是var_t变量的值仍然是随机值
> 
> ```
> def get_global_mask(seqlen, n_local, n_global):
>     var_name = "_global_mask"
>     var = fluid.global_scope().find_var(var_name)
>     if var is not None:
>         print('var is not None')
>         return var
> 
>     global_mask_np = np.tri(seqlen, seqlen).astype('float32')
> 
>     place = fluid.CUDAPlace(0)
> 
>     var = L.create_parameter(name=var_name,
>                              shape=[seqlen, seqlen],
>                              dtype='float32')
>     var.stop_gradient = True
>     vat_t = var.get_tensor()
>     var_t.set(global_mask_np, place)
> ```

paddle.assign()不知是否符合你的需求～ https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/tensor/creation/assign_cn.html#assign
