### ISSUE TITLE
应用实践-使用序列到序列模型完成数字加法 2.0示例代码运行不了

### ISSUE THREAD

**Issue by pughua** [PaddlePaddle/Paddle#32950]
在飞桨 2.0 应用实践中示例 “使用序列到序列模型完成数字加法” 中的示例代码在 2.0.2 和 2.1 运行错误

在 aistudio 上的错误信息：
paddle version: 2.1.0
generating datas..
making the dataset...
finish
train epoch:0 step: 0 loss:2.492597 acc:0.052083
eval epoch:0 step: 0 loss:2.492597 acc:0.052083
saving the best_model...
---------------------------------------------------------------------------RuntimeError                              Traceback (most recent call last)<ipython-input-8-7bc71420937a> in <module>
    276 
    277         # 反向传播
--> 278         loss.backward()
    279 
    280         # 使用优化器进行参数优化
<decorator-gen-248> in backward(self, grad_tensor, retain_graph)
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/wrapped_decorator.py in __impl__(func, *args, **kwargs)
     23     def __impl__(func, *args, **kwargs):
     24         wrapped_func = decorator_func(func)
---> 25         return wrapped_func(*args, **kwargs)
     26 
     27     return __impl__
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/framework.py in __impl__(*args, **kwargs)
    223         assert in_dygraph_mode(
    224         ), "We only support '%s()' in dynamic graph mode, please call 'paddle.disable_static()' to enter dynamic graph mode." % func.__name__
--> 225         return func(*args, **kwargs)
    226 
    227     return __impl__
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/varbase_patch_methods.py in backward(self, grad_tensor, retain_graph)
    234             else:
    235                 core.dygraph_run_backward([self], [grad_tensor], retain_graph,
--> 236                                           framework._dygraph_tracer())
    237         else:
    238             raise ValueError(
RuntimeError: (PreconditionNotMet) Tensor holds no memory. Call Tensor::mutable_data firstly.
  [Hint: holder_ should not be null.] (at /paddle/paddle/fluid/framework/tensor.cc:31)

**Comment by pangyoki** [comment]
你好，2.1的文档在更新中哈，马上会上线，麻烦上线后再尝试。

**Comment by pughua** [comment]
经过测试，示例代码已经能够正常运行。
