### ISSUE TITLE
2.1.0 没有cuda11的Linux的whl文件 

### ISSUE THREAD

**Issue by Darki-luo** [PaddlePaddle/Paddle#32959]
paddle2.1.0没有找到cuda11.0对应的linux版本的whl文件
https://www.paddlepaddle.org.cn/whl/mkl/stable.html cuda 11.0相关的安装包只有下面四个，全是win下的
paddlepaddle_gpu-2.1.0.post110-cp39-cp39-win_amd64.whl
paddlepaddle_gpu-2.1.0.post110-cp38-cp38-win_amd64.whl
paddlepaddle_gpu-2.1.0.post110-cp37-cp37m-win_amd64.whl
paddlepaddle_gpu-2.1.0.post110-cp36-cp36m-win_amd64.whl

**Comment by pangyoki** [comment]
收到，感谢反馈。这个下载链接确实没有cuda110版本的，目前2.1.0的安装方式正在更新中，马上官方文档会正式上线，上线后会给出正确的下载链接。
