### ISSUE TITLE
希望可以出针对win32环境的部署服务

### ISSUE THREAD

**Issue by spiderpigpig** [PaddlePaddle/Paddle#32963]
当前很多工业场景用的是老电脑windows 32位系统，软件也都是32位软件，希望能在保证运行稳定不重装系统的前提下，使用paddle，所以希望能出一版支持win32的部署库

**Comment by zhwesky2010** [comment]
@jiweibo Windows预测库32位能编过吗

**Comment by wadefelix** [comment]
纯32位的老电脑 性能一般也比较捉急了吧。
个人建议，可以考虑部署单独的服务器，然后由这些工控电脑转发请求由服务器来统一处理。

**Comment by jiweibo** [comment]
> @jiweibo Windows预测库32位能编过吗

目前develop分支，编译的时候，会挂到eigen里面，还没有解决

**Comment by AIpioneer** [comment]
你用的是什么模型呢，目前可以考虑使用paddle lite。lite是支持32位windows的
