### ISSUE TITLE
设置cuda和paddle的随机种子

### ISSUE THREAD

**Issue by severous** [PaddlePaddle/Paddle#32973]
pytorch中有如下的代码，用于论文可复现，paddle2.0中是否有类似操作

```python
    random.seed(config['seed'])
    np.random.seed(config['seed'])
    torch.manual_seed(config['seed']) # 是否有对应的paddle操作
    torch.cuda.manual_seed(config['seed']) # 是否有对应的paddle操作
    torch.cuda.manual_seed_all(config['seed']) # 是否有对应的paddle操作
    torch.backends.cudnn.benchmark = False # 是否有对应的paddle操作
    torch.backends.cudnn.deterministic = True # 是否有对应的paddle操作
    os.environ['PYTHONHASHSEED'] = str(config['seed'])
```

**Comment by pangyoki** [comment]
你好。

`torch.manual_seed`、`torch.cuda.manual_seed`、`torch.cuda.manual_seed_all`都可以使用`paddle.seed()`实现，可以参考https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/seed_cn.html#seed

`torch.backends.cudnn.deterministic = True`可使用`export FLAGS_cudnn_deterministic=True`实现。
`torch.backends.cudnn.benchmark = False`没有对应的操作。

`random.seed`、`np.random.seed`、`os.environ['PYTHONHASHSEED']`与paddle操作无关，正常设置就可以了。

**Comment by severous** [comment]
好的，感谢您的解答
