### ISSUE TITLE
关于2.0.1 中的 roi_align

### ISSUE THREAD

**Issue by FL77N** [PaddlePaddle/Paddle#32977]
文档的 ReleaseNote 写到“为提高性能，roi_align 新增 aligned 参数”，可是为什么使用 aligned 参数依然会报错？

**Comment by jerrywgz** [comment]
请问具体是什么报错呢

**Comment by FL77N** [comment]
> 请问具体是什么报错呢

报错翻译过来就是，得到了一个unexpected的参数 aligned，而且文档里面也没改过来，表明可以使用 aligned 参数了
`.roi_align(input, rois, pooled_height=1, pooled_width=1, spatial_scale=1.0, sampling_ratio=- 1, name=None)`

**Comment by jerrywgz** [comment]
https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.0/ppdet/modeling/ops.py#L171 这个api属于检测专用的api，我们已经迁移至PaddleDetection中，可以参考这个里面的api

**Comment by FL77N** [comment]
> https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.0/ppdet/modeling/ops.py#L171 这个api属于检测专用的api，我们已经迁移至PaddleDetection中，可以参考这个里面的api

谢谢，了解了
