### ISSUE TITLE
模型加载报错：AttributeError: 'Model' object has no attribute '_place'

### ISSUE THREAD

**Issue by l976308589** [PaddlePaddle/Paddle#32983]
- 标题：模型加载报错：AttributeError: 'Model' object has no attribute '_place'
- 版本、环境信息：
    1）PaddlePaddle版本：PaddlePaddle-gpu 2.1.0-post110
    2）系统环境：win10+python3.7.6

- 模型信息
    1）模型名称 
class TimeSeriesNetwork(nn.Layer):

    def __init__(self, input_size, next_k=1, num_channels=[64, 128, 256]):
        super(TimeSeriesNetwork, self).__init__()

        self.last_num_channel = num_channels[-1]

        self.tcn = TCNEncoder(
            input_size=input_size,
            num_channels=num_channels,
            kernel_size=2,
            dropout=0.2
        )

        self.linear = nn.Linear(in_features=self.last_num_channel, out_features=next_k)

    def forward(self, x):
        tcn_out = self.tcn(x)
        y_pred = self.linear(tcn_out)
        return y_pred

network = TimeSeriesNetwork(input_size=1)
model = paddle.Model(network)

存储
model.save('./model_save/1')

加载
model = paddle.Model(network)
model.load('./model_save/1')

使用时报错
model.predict(test_data=test_dataset)
报错内容
AttributeError: 'Model' object has no attribute '_place'

**Comment by wanghuancoder** [comment]
您好，您issue标题中的问题，和正文中提供的报错对不上。您遇到的是哪个问题：？
A): AttributeError: 'Model' object has no attribute '_place'
B): AssertionError: Failed to load parameters, please check path.

**Comment by l976308589** [comment]
> 您好，您issue标题中的问题，和正文中提供的报错对不上。您遇到的是哪个问题：？
> A): AttributeError: 'Model' object has no attribute '_place'
> B): AssertionError: Failed to load parameters, please check path.

不好意思老师，我贴错了，是AttributeError: 'Model' object has no attribute '_place'

**Comment by wanghuancoder** [comment]
训练的时候是没问题的吗？
能否给一下完成的代码，以及崩溃时候的报错堆栈？

**Comment by thunder95** [comment]
大佬解决没，遇到了同样的问题我

**Comment by hhxdestiny** [comment]
> 训练的时候是没问题的吗？ 能否给一下完成的代码，以及崩溃时候的报错堆栈？

File "C:\Users\destiny\anaconda3\envs\paddle\lib\site-packages\paddle\hapi\model.py", line 1913, in predict
    places=self._place,
AttributeError: 'Model' object has no attribute '_place'

**Comment by hhxdestiny** [comment]
@wanghuancoder 我猜@thunder95和@l976308589和我一样犯了同样的错误:
```python
net = xxNet()
model = Model(net)
model.load('params')
rslts = model.predict(test_data)
```
跟了一下self._place赋值的位置
```python
def prepare(self, optimizer=None, loss=None, metrics=None,
                amp_configs=None):
    self._place = _get_device()
```
因此预测还需加入prepare方法：
```python
net = xxNet()
model = Model(net)
model.load('params')
optim = optimizer.XXX(learning_rate=0.001, parameters=model.parameters())
model.prepare(optim, nn.XXLoss())
rslts = model.predict(test_data)
```
至此可得到正常结果，这里加载的应该是预训练模型并非导出的模型，所以需要这个操作吧
