### ISSUE TITLE
Gather axis=1 问题

### ISSUE THREAD

**Issue by swag1ong** [PaddlePaddle/Paddle#32982]
Paddle version: 2.0.2
Paddle With CUDA: True
OS: CentOS 6.3
Python version: 3.6.1
CUDA version: None
cuDNN version: None.None.None
Nvidia driver version: 440.33.01

您好，
我在复现论文时发现当使用 paddle.gather(axis=1)并无法获取axis=1上对应的数值 例子：

![image](https://user-images.githubusercontent.com/68997378/118753304-4872fd00-b897-11eb-9641-c58396afe8c5.png)

请问有什么解决方案吗？

**Comment by ForFishes** [comment]
您好，这里看gather的输出维度是正确的，请问您是要实现什么功能吗还是？

**Comment by swag1ong** [comment]
您好，我想通过actions的数值提取data每行对应的column，比如：
```python
actions = [[0], [1], [2]] 
data = [[1, 2, 3], 
        [2, 3, 4], 
        [5, 6, 7]]
```
那么则提取第一行的 第一个column：1，第二行的第二个column：3，第三行第三个column: 7
该操作在torch中可以使用torch.gather(axis=1) 请问在paddle中该如何实现？

**Comment by ForFishes** [comment]
您好，这个可以通过gather_nd 来做。在您的这个case中，可以设置index = [[0,0],[1,1],[2,2]],然后调用paddle.gather_nd(index)
具体的可以参考gather_nd的文档。https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/fluid/layers/gather_nd_cn.html#gather-nd

**Comment by swag1ong** [comment]
了解了谢谢🙏
