### ISSUE TITLE
paddle和numpy之间转换慢的性能问题

### ISSUE THREAD

**Issue by sjhsjn1017** [PaddlePaddle/Paddle#32980]
- 标题：paddle和numpy之间转换慢的性能问题
- 问题描述：
之前提的issue的链接：https://github.com/PaddlePaddle/Paddle/issues/32454#issue-864634432
之前提了一个dataloader加载缓慢的问题，大佬定位到根源性问题是tensor和numpy之间转换慢，
试了下新发布的paddle2.1版本，发现还是存在这个问题，同样的环境，同样的操作下，paddle还是比pytorch慢很多，
因此我在用paddle复现论文的代码依然比原版pytorch慢很多，请问这个性能问题会在后续版本解决吗？

**Comment by wanghuancoder** [comment]
你好，这个问题是会解决的。但具体放到哪个小版本中还不确定。

**Comment by sjhsjn1017** [comment]
> 你好，这个问题是会解决的。但具体放到哪个小版本中还不确定。

好的，谢谢，支持paddle，支持国产框架！

**Comment by wanghuancoder** [comment]
> > 你好，这个问题是会解决的。但具体放到哪个小版本中还不确定。
> 
> 好的，谢谢，支持paddle，支持国产框架！

嗯嗯！咱们共同努力做好！谢谢支持！
