### ISSUE TITLE
Paddle Lite v2.7版本OCR模型，在Android 11上打开相机预览功能后，预测速度特别慢（约慢10-100倍）。

### ISSUE THREAD

**Issue by bravelywangexocr** [PaddlePaddle/Paddle#32992]
1）PaddlePaddle版本：V2.7
    2）CPU：晓龙888
    3）GPU：NA
    4）系统环境：Android 11

- 问题描述：
在Android 11上打开相机预览功能后，预测速度特别慢，约慢10-100倍。
但是，Android 10上相同的模型和代码，速度正常。

麻烦帮看看有没有碰到类似问题，谢谢！

**Comment by jiweibo** [comment]
您可以先在shell下，运行单测，看性能是否有异常；另外这两个手机的处理器分别是？会不会是Android11 处理器比Android10 处理器要差，导致性能差异

还有一个方法：关闭照相机功能，直接跑预测看耗时是否有差异，排除前后预处理耗时差异

**Comment by bravelywangexocr** [comment]
谢谢答复！

我们尝试过静态图片输入测试，性能是正常的。a11手机试了小米11和oppo a92s都有问题。
另外从logs看，就是调用paddle lite模型预测的接口慢，预处理和后处理时间都是正常的。
也尝试过build的时候打开Paddle lite的logs功能，但是模型运行时也没有看到错误的logs信息。

**Comment by chenjiaoAngel** [comment]
a11手机试了小米11和oppo a92s 两部手机都是打开摄像头处理，预测性能就会下降是吗？请问跑的多线程还是单线程呢？有固定绑核吗？

**Comment by chenjiaoAngel** [comment]
这个是用CPU还是GPU预测呢？打开摄像头后，辛苦打印下前后处理+预测的耗时，还有打印下预测时，使用的核数（大核0-3， 小核4-7），怀疑打开摄像头时，大核被抢占，跑到小核了；你也可以在shell下验证，跑小核时的预测性能是否和打开摄像头时，预测性能一致
