### ISSUE TITLE
paddle2.0.2 tensorrt 部署报错

### ISSUE THREAD

**Issue by a123b12cd** [PaddlePaddle/Paddle#32998]
paddleseg2.0.2 导出的模型，部署中使用tensorrt。
Q1:export.py导出的模型中存在多个动态shape（已经设置了输入，并转成了静态图。 同样的模型，基于paddle2.0之前的版本export.py导出来的就不是动态shape的  eg:unet + bilinear_interp  ）
Q2: 由于Q1,会导致在使用tensorrt时，需要为每个动态shape的op通过SetTRTDynamicShapeInfo来进行设置,在设置时，min_input_shape，max_input_shape，opt_input_shape设置规则不太明确。设置成功后，仍存在如下问题：
![image](https://user-images.githubusercontent.com/49675099/118811639-d4107c00-b8df-11eb-9ca5-32aa5b85acd3.png)

**Comment by cryoco** [comment]
min_input_shape，max_input_shape指定了所有TRT子图输入变量的最小和最大shape，opt_input_shape为在min和max之间的一个最优shape，TRT会根据opt_input_shape来做内部优化。在运行时，实际输入shape不能超出[min_input_shape，max_input_shape]的范围，否则会报您上面的错误。您可以检查下。在刚发布的2.1.0版本中，这个报错信息得到了增强，您可以明确看到是哪个输入超出了min和max的限制。

**Comment by a123b12cd** [comment]
> min_input_shape，max_input_shape指定了所有TRT子图输入变量的最小和最大shape，opt_input_shape为在min和max之间的一个最优shape，TRT会根据opt_input_shape来做内部优化。在运行时，实际输入shape不能超出[min_input_shape，max_input_shape]的范围，否则会报您上面的错误。您可以检查下。在刚发布的2.1.0版本中，这个报错信息得到了增强，您可以明确看到是哪个输入超出了min和max的限制。



按照这种说法，我如果把min设置的足够小，max设置的足够大，就不会报错才对，但是实际上很难找到一组能够不报错的max min opt 的组合。  比如下面两组结果，min改小后，反而无法运行
![image](https://user-images.githubusercontent.com/49675099/118930453-53ea2500-b978-11eb-8681-fa574523eacd.png)
![image](https://user-images.githubusercontent.com/49675099/118930847-d4a92100-b978-11eb-9b59-c7801e5063ac.png)



 ------------------------------------
而且，貌似还找不到2.1.0版本的预测库（我用的时windows）
![image](https://user-images.githubusercontent.com/49675099/118931181-42554d00-b979-11eb-88c7-a57f55fa59cc.png)

**Comment by jiweibo** [comment]
您好，windows 2.1的预测库已发布，https://paddle-inference.readthedocs.io/en/release-v2.1/user_guides/download_lib.html#windows

关于trt动态shape问题，由于模型中间节点的shape不太好判断，交由用户完成难度较大，我们后续计划会解决这个问题

**Comment by Superjomn** [comment]
这个版本只能一点一点人工对齐。

我们预计下个版本会有自动推导动态 shape 的功能进去，到时候只需要用数据离线 tune 下，相关信息会自动加进去。
