### ISSUE TITLE
Use soft-link for libdnnl.so.x

### ISSUE THREAD

**Issue by luotao1** [PaddlePaddle/Paddle#33005]
![图片](https://user-images.githubusercontent.com/6836917/118914020-17f59680-b95d-11eb-8eda-7b5b5d377d11.png)
![图片](https://user-images.githubusercontent.com/6836917/118914044-1f1ca480-b95d-11eb-9aa3-c107295c7298.png)
我们想减少库体积大小，而libdnnl.so.1和libdnnl.so.2的md5值是一样的，能否使用软连接？
We want to decrease the lib size, and since the md5 of libdnnl.so.1 and libdnnl.so.2 are the same, could you use soft-link for one of them?

**Comment by luotao1** [comment]
@Avin0323 @wanghuancoder @lelelelelez Please follow this issue.

**Comment by lidanqing-intel** [comment]
@jczaja  Could you please check this issue? Is it ok to not call MKLDNN_SHARED_LIB_1 and MKLDNN_SHARED_LIB_2 and use one unified ?

**Comment by lidanqing-vv** [comment]
@luotao1 
![image](https://user-images.githubusercontent.com/47151829/120274639-b3362680-c2e2-11eb-83f1-7a2c098e14f4.png)

Paddle 里面下载的这三个库都是一样的，其实只要保留so.2就可以了，这个三个库一样的。当时是因为要兼容性吗？那其他的名字的话链接过去就可以了

胡英建议这样就可以：
```
(base) yhu5@clx02:/opt/intel/oneapi/dnnl/2021.2.0/cpu_gomp/lib$ ls -l
total 50136
lrwxrwxrwx 1 root root       12 3月  25 14:04 libdnnl.so -> libdnnl.so.2
lrwxrwxrwx 1 root root       14 3月  25 14:04 libdnnl.so.2 -> libdnnl.so.2.2
-rwxr-xr-x 1 root root 51337320 3月  12 06:55 libdnnl.so.2.2
lrwxrwxrwx 1 root root       10 3月  25 14:04 libmkldnn.so -> libdnnl.so
lrwxrwxrwx 1 root root       12 3月  25 14:04 libmkldnn.so.2 -> libdnnl.so.2
lrwxrwxrwx 1 root root       14 3月  25 14:04 libmkldnn.so.2.2 -> libdnnl.so.2.2
(base) yhu5@clx02:/opt/intel/oneapi/dnnl/2021.2.0/cpu_gomp/lib$ 
```

**Comment by lidanqing-vv** [comment]
因为最新oneDNN 版本是oneDNN v2.2.2 了,过几天会升级到v2.3
现在你们先改一下，等过几天我们升级的时候连库包的名字也升级。这样可以吗？

**Comment by luotao1** [comment]
> 当时是因为要兼容性吗？那其他的名字的话链接过去就可以了

当时确实是考虑到兼容性的原因

> 等过几天我们升级的时候连库包的名字也升级。这样可以吗？

可以等你们升级的时候一起改了。

**Comment by lidanqing-vv** [comment]
Hi, because before Baidu customer applications link directly to oneDNN, that is why this copies remain, although client should only link to Paddle not to oneDNN libs.
If we use softlinks, will it influence customer applications and windows side usage? windows side have to be fully tested while we do not have experience on windows and customer cases. We think this issue need more discussion or Baidu will do it basing on more investigation on customer usage and windows usage, because Intel are not able to test.

**Comment by luotao1** [comment]
> If we use softlinks, will it influence customer applications and windows side usage? windows side have to be fully tested while we do not have experience on windows and customer cases. 

https://github.com/PaddlePaddle/Paddle/blob/e20234094c5857a12438228608260a2058ef201f/paddle/fluid/inference/api/demo_ci/CMakeLists.txt#L117-L125

We have demo_ci in CI pipeline, if you could pass the CI, then there is no influence for applications.

**Comment by lidanqing-vv** [comment]
![image](https://user-images.githubusercontent.com/47151829/126693443-fc0bdfad-c259-44cc-b8e8-9230454916dc.png)

![image](https://user-images.githubusercontent.com/47151829/126693547-f9fa84b6-365c-4162-8a6b-125281cced27.png)

@wzzju

**Comment by luotao1** [comment]
从发布包侧看，这个优化点已经完成了，C++发布包(tar.gz)已经改成软链方式，发布包降低30M左右，python发布包，由于whl打包方式限制，软链文件会被处理为普通文件，所以优化点无效。
