### ISSUE TITLE
Your Paddle Fluid is installed successfully ONLY for SINGLE GPU or CPU

### ISSUE THREAD

**Issue by ZZHHogan** [PaddlePaddle/Paddle#33018]
运行paddleocr失败，报错：

![image](https://user-images.githubusercontent.com/40531744/118938038-c19a4f00-b980-11eb-9cef-cf96271a3e07.png)

以及使用paddle.fluid.install_check.run_check() 检查paddle是否正确安装时报错：

Your Paddle Fluid is installed successfully ONLY for SINGLE GPU or CPU
- 版本、环境信息：
    1）PaddlePaddle版本：请提供您的PaddlePaddle版本号（如1.1）或CommitID
    2）CPU：请提供CPU型号，MKL/OpenBlas/MKLDNN/等数学库的使用情况
    3）GPU：cuda11.2，显卡3090 ,cudnn 8005
    4）系统环境：linux操作系统
Linux version 3.10.0-1160.el7.x86_64 (mockbuild@kbuilder.bsys.centos.org) (gcc version 4.8.5 20150623 (Red Hat 4.8.5-44) (GCC)

- 安装方式信息：
1）pip安装

**Comment by Joejiong** [comment]
你好，感谢你的问题，目前正在查看你的问题, 初步看下来，你的cuda version11.2 需要和相应的paddlepaddle-gpu版本配合，可以问一下，ocr的同学，@zhoujun或者可以到paddleocr模型库里面提问。通是可以按照提示，提供一下你的环境信息，还有你的执行命令与执行的model具体是哪一个，谢谢

**Comment by WenmuZhou** [comment]
@hhhhhhogan 在这里提问吧 https://github.com/PaddlePaddle/PaddleOCR
