### ISSUE TITLE
单机多卡训练时加载预训练模型出错

### ISSUE THREAD

**Issue by junfeizhu** [PaddlePaddle/Paddle#33012]
PaddlePaddle版本：2.0.2
GPU：GTX 1080 Ti *4
系统环境：centos 7, python 3.7

在使用 python -m paddle.distributed.launch normaltrain.py 进行单机多卡训练时出错。经过试验发现是在载入预训练模型时出了问题。在载入ERNIE模型时报如下错误：

![image](https://user-images.githubusercontent.com/32788240/118927506-767a3f00-b974-11eb-9ec1-623f7356ba71.png)

在载入Lenet模型时报如下错误：
![image](https://user-images.githubusercontent.com/32788240/118927551-87c34b80-b974-11eb-8b89-039a21c0b8f4.png)

但是在不加载任何预训练模型，只使用基础API搭建自己的模型时可以用单机多卡训练。

**Comment by Joejiong** [comment]
你好已经收到你的问题，正在查看, 建议到ernie 模型repo提一下这个issue， 根据提示，可以pip list一下你的系统，上面看到，gpu 找不到上下文。

**Comment by junfeizhu** [comment]
> 你好已经收到你的问题，正在查看, 建议到ernie 模型repo提一下这个issue， 根据提示，可以pip list一下你的系统，上面看到，gpu 找不到上下文。

这是我pip list后的部分结果，应该不会是ernie安装的问题。因为我在使用单机单卡微调ernie的时候完全没有问题。另外我在加载Lenet的时候也遇到同样的问题。


olefile             0.46
opencv-python       4.5.2.52
openpyxl            3.0.7
packaging           20.9
paddle-ernie        0.1.0.dev1
paddle2onnx         0.5.1
paddlehub           2.1.0
paddlenlp           2.0.0rc22
paddlepaddle-gpu    2.0.2
pandas              1.0.3
pandocfilters       1.4.3
parso               0.8.2
pathlib2            2.3.5
