### ISSUE TITLE
python 3.9.5环境下从百度镜像无法安装paddlepaddle 2.0.0

### ISSUE THREAD

**Issue by LangDaoAI** [PaddlePaddle/Paddle#33017]
- 标题：安装错误
- 版本、环境信息：
    1）PaddlePaddle版本：2.0.0
    2）CPU：x64 64位操作系统
    4）系统环境：win10、Python 3.9.5

- 安装方式信息：
   pip安装

- 问题以及复现信息：
   安装python 3.9.5, 然后在终端执行以下命令，
   d:\Python\Python39>python -m pip install paddlepaddle==2.0.0 -i https://mirror.baidu.com/pypi/simple
Looking in indexes: https://mirror.baidu.com/pypi/simple
ERROR: Could not find a version that satisfies the requirement paddlepaddle==2.0.0 (from versions: 2.1.0)
ERROR: No matching distribution found for paddlepaddle==2.0.0

也确认了python 3.8.10没有出现上述问题。

推测：paddlepaddle安装依赖了python版本的信息。

**Comment by LangDaoAI** [comment]
上传一下画面如下：

![paddlehub导入—2 0 0-1](https://user-images.githubusercontent.com/83859417/118936660-50a66780-b97f-11eb-8e26-456f22d6ef85.png)

**Comment by Joejiong** [comment]
可以申请一下代理

**Comment by DDDivano** [comment]
paddlepaddle 从2.1.0开始支持python39，之前没有相关的支持，所以无法下载

**Comment by LangDaoAI** [comment]
> paddlepaddle 从2.1.0开始支持python39，之前没有相关的支持，所以无法下载

好的，明白了
