### ISSUE TITLE
config. SetMkldnnCacheCapacity is useless 

### ISSUE THREAD

**Issue by juncaipeng** [PaddlePaddle/Paddle#33021]
Ubuntu
C++
MKLDNN

Download the demo (Link:https://dubox.com/s/1RVo80hVAC0zr5iZ2EuG0xQ Password:3v5m ) and refer to the readme.

**Comment by lidanqing-vv** [comment]
Reproduced

**Comment by lidanqing-intel** [comment]
Not Jacek's commit caused the problem. I m using bisect to find which commit caused memory rising.

**Comment by lidanqing-intel** [comment]
a5627df331b913c047f78789c4c9b3ee5edfe65c caused thie memory rising.

**Comment by lidanqing-vv** [comment]
I just tested again, From #32664 there are memory leak @jczaja Please fix this issue, thank you very much!

**Comment by jczaja** [comment]
@luotao1 ,
While working on this issue I had remove(#33174, still testing) some code you added at https://github.com/PaddlePaddle/Paddle/pull/18580 . My question is do you remember why restoring oneDNN caching was needed as done here:
https://github.com/PaddlePaddle/Paddle/blob/481ee79fc92304f33165f7ed0679f16c36862cea/paddle/fluid/inference/api/analysis_predictor.cc#L332-L335

**Comment by luotao1** [comment]
I remember it is used to fix a detect model https://github.com/PaddlePaddle/Paddle/pull/18081#issuecomment-502101243 which input dims are dynamic, the model is in `paddle/fluid/inference/tests/api/analyzer_detect_tester.cc`

`config. SetMkldnnCacheCapacity` is used to balance the memory and speed. You can see the following data from the detect model. (#18372) 

 | speed(ms) | memory | CacheCapacity | 
|---|---|---|
| 26.1437 | 1.5G | CacheCapacity=10 | 
| 24.0129 | 3.5G | CacheCapacity=50 |

**Comment by jczaja** [comment]
@juncaipeng Just to post status of work on that one. There are at least three sources of memory leaks. We understand two of them. Fix to first one is https://github.com/PaddlePaddle/Paddle/pull/33174.

**Comment by jczaja** [comment]
@juncaipeng Two PRs with fixes to this issue were merged. Please test.

**Comment by lidanqing-vv** [comment]
@OliverLPH  Hi I talked with Juncai, please test this issue, since two PRs are merged and should fix this.
