### ISSUE TITLE
学习率和正则项的设置

### ISSUE THREAD

**Issue by cszhou** [PaddlePaddle/Paddle#3302]
## 问题1 
通过下面的代码设置的`learning_rate`是所有层的lr都是这个值么。而且这个值对weight和bias的都是一样的，对么？
```Python
 # create optimizer
    optimizer = paddle.optimizer.Momentum(
        momentum=0,
        learning_rate=2e-2,
        regularization=paddle.optimizer.L2Regularization(rate=8e-4),
        model_average=paddle.optimizer.ModelAverage(
            average_window=0.5, max_average_window=10000), )
```
## 问题2 
使用下面的代码，`l2_rate=0.`时，fc1层的bias是否就不计算其`regularization`的值？
结合问题1和问题2的代码，在问题1中有 `regularization=paddle.optimizer.L2Regularization(rate=8e-4)`,，现在加上此处的`l2_rate=0.1`时，所以fc1层就有了新的`regularization`的值`8e-4`乘以`0.1`？
```Python
bias_attr = paddle.attr.Param(initial_std=0., l2_rate=0.)
fc1 = paddle.layer.fc(
        input=emb, size=hid_dim, act=linear, bias_attr=bias_attr)
```
## 问题3
请结合问题1，如果同时使用了问题1和问题3的代码。那么fc1层参数（含weight和bias）的学习率是否是`2e-2`乘以`1e-3`？？？
[官网上学习率的说明](http://doc.paddlepaddle.org/develop/doc/api/v2/config/attr.html)
```Python
fc_para_attr = paddle.attr.Param(learning_rate=1e-3)
fc1 = paddle.layer.fc(
            input=inputs,
            size=hid_dim,
            act=linear,
            param_attr=fc_para_attr,
            )
```

**Comment by kuke** [comment]
这三个问题的答案都为是，真实learning rate
 =全局learning rate * 局部learning rate
