### ISSUE TITLE
[论文复现] 自定义算子出现 Python object is not type of St10shared_ptrIN6paddle10imperative7VarBaseEE

### ISSUE THREAD

**Issue by thunder95** [PaddlePaddle/Paddle#33020]
尝试复现deformable detr模型时， setup和jit运行都能顺利加载自定义算子， 但是都出现了同样的错误，不清楚问题出在哪，该怎么debug

Traceback (most recent call last):
  File "ms_deform_attn_test.py", line 29, in <module>
    output_cuda = custom_ops.custom_ms_deform_attn(value, shapes, level_start_index, sampling_locations, attention_weights, im2col_step)
  File "/home/hl/.cache/paddle_extensions/custom_jit_ops/custom_jit_ops.py", line 16, in custom_ms_deform_attn
    helper.append_op(type="custom_ms_deform_attn", inputs=ins, outputs=outs, attrs=attrs)
  File "/f/soft/Anaconda/lib/python3.7/site-packages/paddle/fluid/layer_helper.py", line 43, in append_op
    return self.main_program.current_block().append_op(*args, **kwargs)
  File "/f/soft/Anaconda/lib/python3.7/site-packages/paddle/fluid/framework.py", line 3018, in append_op
    kwargs.get("stop_gradient", False))
  File "/f/soft/Anaconda/lib/python3.7/site-packages/paddle/fluid/dygraph/tracer.py", line 45, in trace_op
    not stop_gradient)
ValueError: (InvalidArgument) Python object is not type of St10shared_ptrIN6paddle10imperative7VarBaseEE (at /paddle/paddle/fluid/pybind/imperative.cc:221)

**Comment by chenwhql** [comment]
这个是输入类型不对，可以检查下是不是参数传错了
```
output_cuda = custom_ops.custom_ms_deform_attn(value, shapes, level_start_index, sampling_locations, attention_weights, im2col_step)
```
检查下这个里面的参数有没有需要是Tensor的，但实际传入的不是Tensor类型的情况

**Comment by thunder95** [comment]
@chenwhql 您好，感谢回复， 我输入的参数打印如下：

```
value type <class 'paddle.VarBase'>
shapes type <class 'paddle.VarBase'>
level_start_index type <class 'paddle.VarBase'>
sampling_locations type <class 'paddle.VarBase'>
attention_weights type <class 'paddle.VarBase'>
im2col_step type <class 'int'>
```

只有最后一个才是int类型，其他参数都是通过paddle.to_tensor将numpy转过来的， c++接收参数如下：

```
std::vector<paddle::Tensor> MsDeformAttnCUDAForward(
    const paddle::Tensor& value,
    const paddle::Tensor& spatial_shapes,
    const paddle::Tensor& level_start_index,
    const paddle::Tensor& sampling_loc,
    const paddle::Tensor& attn_weight,
    const int im2col_step)
```

**Comment by chenwhql** [comment]
那PD_BUILD_OP的声明怎么写的方便贴一下吗

**Comment by thunder95** [comment]
> 那PD_BUILD_OP的声明怎么写的方便贴一下吗

@chenwhql 

```
PD_BUILD_OP(custom_ms_deform_attn)
    .Inputs({"value", "spatial_shapes", "level_start_index", "sampling_loc", "attn_weight", "im2col_step"})
    .Outputs({"out"})
    .SetKernelFn(PD_KERNEL(MsDeformAttnCUDAForward));

PD_BUILD_GRAD_OP(custom_ms_deform_attn)
    .Inputs({"value", "spatial_shapes", "level_start_index", "sampling_loc", "attn_weight", paddle::Grad("out"), "im2col_step"})
    .Outputs({paddle::Grad("value"), paddle::Grad("sampling_loc"), paddle::Grad("attn_weight")})
    .SetKernelFn(PD_KERNEL(MsDeformAttnCUDABackward));
```

**Comment by chenwhql** [comment]
嗯嗯，就是这里的问题，im2col_step这个要用Attribute去声明下，可以看看下面这段文档
https://www.paddlepaddle.org.cn/documentation/docs/zh/guides/07_new_op/new_custom_op_cn.html#attribute

**Comment by thunder95** [comment]
@chenwhql 嗯 对的 是我看文档的时候疏忽，没有注意到。 接着报了这个错:
RuntimeError: (Unavailable) Your custom operator contains multiple inputs. We only allow a custom operator that contains only one input and only one output without setting the InferDtypeFn. At this time, the input dtype will be directly set to the output dtype.

请帮我看一下，我的修改是否正确:

```
PD_BUILD_OP(custom_ms_deform_attn)
    .Inputs({"value", "spatial_shapes", "level_start_index", "sampling_loc", "attn_weight"})
    .Outputs({"out"})
    .Attrs({"im2col_step: int"})
    .SetKernelFn(PD_KERNEL(MsDeformAttnCUDAForward))
    .SetInferShapeFn(PD_INFER_SHAPE(ReluInferShape))
    .SetInferDtypeFn(PD_INFER_DTYPE(ReluInferDtype));

PD_BUILD_GRAD_OP(custom_ms_deform_attn)
    .Inputs({"value", "spatial_shapes", "level_start_index", "sampling_loc", "attn_weight", paddle::Grad("out")})
    .Outputs({paddle::Grad("value"), paddle::Grad("sampling_loc"), paddle::Grad("attn_weight")})
    .Attrs({"im2col_step: int"})
    .SetKernelFn(PD_KERNEL(MsDeformAttnCUDABackward));
```
```

// 维度推导
std::vector<std::vector<int64_t>> ReluInferShape(
    std::vector<int64_t> value_shape,
    std::vector<int64_t> spatial_shapes_shape,
    std::vector<int64_t> level_start_index_shape,
    std::vector<int64_t> sampling_loc_shape,
    std::vector<int64_t> grad_output_shape
) {
  return {value_shape, spatial_shapes_shape, level_start_index_shape, sampling_loc_shape, grad_output_shape};
}

// 类型推导
std::vector<paddle::DataType> ReluInferDtype(
    paddle::DataType value_dtype,
    paddle::DataType spatial_shapes_dtype,
    paddle::DataType level_start_index_dtype,
    paddle::DataType sampling_loc_dtype,
    paddle::DataType attn_weight_dtype
) {
  return {value_dtype, spatial_shapes_dtype, level_start_index_dtype, sampling_loc_dtype, attn_weight_dtype};
}

```

**最终还是会报段错误， 这个错误应该是在算子实现层了吧？自定义算子接口方面是不是就没问题了。** 

--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
0   paddle::imperative::Tracer::TraceOp(std::string const&, paddle::imperative::NameVarBaseMap const&, paddle::imperative::NameVarBaseMap const&, paddle::framework::AttributeMap, paddle::platform::Place const&, bool, std::map<std::string, std::string, std::less<std::string >, std::allocator<std::pair<std::string const, std::string > > > const&)
1   paddle::imperative::PreparedOp::Run(paddle::imperative::NameVarBaseMap const&, paddle::imperative::NameVarBaseMap const&, paddle::framework::AttributeMap const&)
2   paddle::KernelFuncImpl<std::vector<paddle::Tensor, std::allocator<paddle::Tensor> > (*)(paddle::Tensor const&, paddle::Tensor const&, paddle::Tensor const&, paddle::Tensor const&, paddle::Tensor const&, int), &(MsDeformAttnCUDAForward(paddle::Tensor const&, paddle::Tensor const&, paddle::Tensor const&, paddle::Tensor const&, paddle::Tensor const&, int))>::Compute(std::vector<paddle::Tensor, std::allocator<paddle::Tensor> >, std::vector<boost::any, std::allocator<boost::any> >)
3   std::vector<paddle::Tensor, std::allocator<paddle::Tensor> > paddle::KernelFuncImpl<std::vector<paddle::Tensor, std::allocator<paddle::Tensor> > (*)(paddle::Tensor const&, paddle::Tensor const&, paddle::Tensor const&, paddle::Tensor const&, paddle::Tensor const&, int), &(MsDeformAttnCUDAForward(paddle::Tensor const&, paddle::Tensor const&, paddle::Tensor const&, paddle::Tensor const&, paddle::Tensor const&, int))>::ComputeCallHelper<int, paddle::TypeTag<int> >::Compute<5, 0, paddle::Tensor, paddle::Tensor, paddle::Tensor, paddle::Tensor, paddle::Tensor>(std::vector<paddle::Tensor, std::allocator<paddle::Tensor> >, std::vector<boost::any, std::allocator<boost::any> >, paddle::Tensor const&, paddle::Tensor const&, paddle::Tensor const&, paddle::Tensor const&, paddle::Tensor const&)
4   MsDeformAttnCUDAForward(paddle::Tensor const&, paddle::Tensor const&, paddle::Tensor const&, paddle::Tensor const&, paddle::Tensor const&, int)
5   ms_deform_attn_cuda_forward(paddle::Tensor const&, paddle::Tensor const&, paddle::Tensor const&, paddle::Tensor const&, paddle::Tensor const&, int)
6   paddle::framework::SignalHandle(char const*, int)
7   paddle::platform::GetCurrentTraceBackString[abi:cxx11]()

----------------------
Error Message Summary:
----------------------
FatalError: `Segmentation fault` is detected by the operating system.
  [TimeInfo: *** Aborted at 1621580870 (unix time) try "date -d @1621580870" if you are using GNU date ***]
  [SignalInfo: *** SIGSEGV (@0x7f52a5aeab00) received by PID 26901 (TID 0x7f535a6e9740) from PID 18446744072194272000 ***]

**Comment by chenwhql** [comment]
![image](https://user-images.githubusercontent.com/22561442/119097500-62534200-ba47-11eb-8dce-8a3939ff4203.png)
这里有问题，这里并不是直接返回你输入的shape，而是要推断你输出的shape和dtype，根据你前面BUILD_OP的配置，你的输出应该只有一个out才对，这两个函数的返回值也只有一个

**Comment by chenwhql** [comment]
要确保根据输入的shape或者dtype，推断出out需要的正确的shape和dtype哈，不能随便返回一个

**Comment by thunder95** [comment]
@chenwhql 改成这样可以吗， 虽然还是报同样的错，且这个错跟RuleInfer可能没关系。

```
// 维度推导
std::vector<std::vector<int64_t>> ReluInferShape(
    std::vector<int64_t> value_shape,
    std::vector<int64_t> spatial_shapes_shape,
    std::vector<int64_t> level_start_index_shape,
    std::vector<int64_t> sampling_loc_shape,
    std::vector<int64_t> grad_output_shape
) {
    const int batch = value_shape[0];
    const int num_heads = value_shape[2];
    const int channels = value_shape[3];
    const int num_query = sampling_loc_shape[1];
    std::vector<int64_t> out_shape{batch, num_query, num_heads*channels};
    return {out_shape};
}

// 类型推导
std::vector<paddle::DataType> ReluInferDtype(
    paddle::DataType value_dtype,
    paddle::DataType spatial_shapes_dtype,
    paddle::DataType level_start_index_dtype,
    paddle::DataType sampling_loc_dtype,
    paddle::DataType attn_weight_dtype
) {
    return {value_dtype};
}
```

这个写起来有些难，哪里可以找到更多例子吗？

**Comment by chenwhql** [comment]
看起来可以的，如果还是报这个错的话，像你说的，可以查一下实现上是不是有问题？

**Comment by chenwhql** [comment]
或者看看tensor设备有没有问题，看起来你这个是CUDA算子，有没有检查输入Tensor是否是CUDA的呢

**Comment by chenwhql** [comment]
FatalError: Segmentation fault is detected by the operating system.

这个一般就是代码写错了，非法内存访问，越界啥的，可以仔细查一下代码

**Comment by thunder95** [comment]
@chenwhql 

使用的paddle 2.0.2， 申请out的内存：
```
    std::vector<int64_t> out_shape{batch/im2col_step_, batch_n, num_query, num_heads, channels};
    auto out = paddle::Tensor(paddle::PlaceType::kGPU);
    out.reshape(out_shape);
```

将out的指针传入cuda普通的device函数, 
`out.mutable_data<data_t>(value.place())`

然后参照relu的示例，我需要对它进行0值初始化：
```
  for (int k=0; k<batch_step; k++) {
      out[k] = static_cast<data_t>(0.);
  }
```
在out[k]时发生内存越界，进而段错误。 按照官方示例来的，不明白哪里错了？另外在这个场景下有python tensor的zeros_like这种api吗？

**Comment by chenwhql** [comment]
目前还没有，麻烦贴一下完整代码吧

**Comment by zizizihua** [comment]
> @chenwhql
> 
> 使用的paddle 2.0.2， 申请out的内存：
> 
> ```
>     std::vector<int64_t> out_shape{batch/im2col_step_, batch_n, num_query, num_heads, channels};
>     auto out = paddle::Tensor(paddle::PlaceType::kGPU);
>     out.reshape(out_shape);
> ```
> 
> 将out的指针传入cuda普通的device函数,
> `out.mutable_data<data_t>(value.place())`
> 
> 然后参照relu的示例，我需要对它进行0值初始化：
> 
> ```
>   for (int k=0; k<batch_step; k++) {
>       out[k] = static_cast<data_t>(0.);
>   }
> ```
> 
> 在out[k]时发生内存越界，进而段错误。 按照官方示例来的，不明白哪里错了？另外在这个场景下有python tensor的zeros_like这种api吗？

`out.mutable_data<data_t>(value.place())`会返回指向out数据起始地址的指针
out并不能直接赋值，赋值操作应该基于返回的指针上
可改为:
```
auto out_data = out.mutable_data<data_t>(value.place());
for (...) {
    out_data[k] = static_cast<data_t>(0.);
}
```

**Comment by thunder95** [comment]
@chenwhql @zizizihua 感谢两位大佬，目前forward跑通了，结果也验证了。但是算子中的backward怎么测试比较好？ 因为在paddle中没有找到类似torch.gradcheck()这样的api

**Comment by thunder95** [comment]
我将torch和paddle的backward简单构造如下，但是有不小的差异， 核心的kernel代码几乎没动， 前向输出结果一致，请问我这么做比较backward结果的方式靠谱吗？ @chenwhql 


```
output_cuda = custom_ops.custom_ms_deform_attn(value, shapes, level_start_index, sampling_locations, attention_weights, im2col_step)
print("paddle output", output_cuda.numpy())
print("torch output: ", saved["output_cuda"])

np.testing.assert_allclose(output_cuda.numpy(), saved["output_cuda"], rtol=1e-5, atol=0)
dummy_output = paddle.ones_like(output_cuda)
mse = mse_loss(output_cuda, dummy_output)
mse.backward()
print(np.testing.assert_allclose(value.grad, saved["value_grad"], rtol=1e-5, atol=0)) #有较明显的差异：0.0005
```
打印结果如下：
```
paddle output [[[0.00189938 0.00460283 0.00467118 0.0043844 ]
  [0.0037951  0.00251276 0.00184443 0.00363468]]]
torch output:  [[[0.00189938 0.00460283 0.00467118 0.0043844 ]
  [0.0037951  0.00251276 0.00184443 0.00363468]]]
Traceback (most recent call last):
  File "ms_deform_attn_test.py", line 45, in <module>
    print(np.testing.assert_allclose(value.grad, saved["value_grad"], rtol=1e-5, atol=0)) #有较明显的差异：0.0005
  File "/f/soft/Anaconda/lib/python3.7/site-packages/numpy/testing/_private/utils.py", line 1529, in assert_allclose
    verbose=verbose, header=header, equal_nan=equal_nan)
  File "/f/soft/Anaconda/lib/python3.7/site-packages/numpy/testing/_private/utils.py", line 842, in assert_array_compare
    raise AssertionError(msg)
AssertionError: 
Not equal to tolerance rtol=1e-05, atol=0

Mismatched elements: 60 / 120 (50%)
Max absolute difference: 0.00055517
Max relative difference: 0.00687033
 x: array([[[[ 0.000000e+00,  0.000000e+00],
         [ 0.000000e+00,  0.000000e+00]],
...
 y: array([[[[ 0.000000e+00,  0.000000e+00],
         [ 0.000000e+00,  0.000000e+00]],
```
...

**Comment by chenwhql** [comment]
不知道你torch的代码怎么写的，可以贴一下

如果只是对比反向值也可以更简单一点，直接求个平均值，求backward就行

```
output_cuda = custom_ops.custom_ms_deform_attn(value, shapes, level_start_index, sampling_locations, attention_weights, im2col_step)
output_mean = paddle.mean(output_cuda)
output_mean.backward()
# compare value.grad
```

**Comment by thunder95** [comment]
> 不知道你torch的代码怎么写的，可以贴一下
> 
> 如果只是对比反向值也可以更简单一点，直接求个平均值，求backward就行
> 
> ```
> output_cuda = custom_ops.custom_ms_deform_attn(value, shapes, level_start_index, sampling_locations, attention_weights, im2col_step)
> output_mean = paddle.mean(output_cuda)
> output_mean.backward()
> # compare value.grad
> ```

@chenwhql 
```
    value.requires_grad = True
    output_cuda = MSDeformAttnFunction.apply(value, shapes, level_start_index, sampling_locations, attention_weights, im2col_step)
    output_mean = torch.mean(output_cuda)
    output_mean.backward()
    print(value.grad.detach().cpu().numpy())
```
```
value = paddle.to_tensor(saved["value"], stop_gradient=False)
output_cuda = custom_ops.custom_ms_deform_attn(value, shapes, level_start_index, sampling_locations, attention_weights, im2col_step)
output_mean = paddle.mean(output_cuda)
output_cuda.backward()
print(value.grad)
```
最终还是有非常明显的差异， 请帮忙看看， 这样对比有没有什么问题，如果ok的话，我就只能区kernel里debug了

**Comment by chenwhql** [comment]
下面写错了吧

![image](https://user-images.githubusercontent.com/22561442/119287459-1e478380-bc79-11eb-8f58-2c8f74ae61e6.png)

应该是mean吧，如果这个改了还是不对，那确实可以去kernel里看看了
