### ISSUE TITLE
Segmentation fault when start training

### ISSUE THREAD

**Issue by qingchunnianshao** [PaddlePaddle/Paddle#33022]
- 版本、环境信息：
    1）PaddlePaddle版本：paddlepaddle-gpu2.1.0.post101
   2) Ubuntu18.04 单显卡RTX2070  CUDA10.1

SYS-4028GR-TR:~$ nvcc -V
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2019 NVIDIA Corporation
Built on Fri_Feb__8_19:08:17_PST_2019
Cuda compilation tools, release 10.1, V10.1.105

>>> paddle.utils.run_check()
Running verify PaddlePaddle program ... 
W0520 16:00:33.821033 10371 device_context.cc:404] Please NOTE: device: 0, GPU Compute Capability: 7.5, Driver API Version: 11.1, Runtime API Version: 10.1
W0520 16:00:33.826331 10371 device_context.cc:422] device: 0, cuDNN Version: 7.6.
PaddlePaddle works well on 1 GPU.
PaddlePaddle works well on 1 GPUs.
PaddlePaddle is installed successfully! Let's start deep learning with PaddlePaddle now.

代码比较简单，贴出完整代码如下：
import paddle
from paddle.vision.transforms import ToTensor

train_dataset = paddle.vision.datasets.MNIST(mode='train',transform=ToTensor())
val_dataset = paddle.vision.datasets.MNIST(mode='test',transform=ToTensor())

mnist = paddle.nn.Sequential(
    paddle.nn.Flatten(),
    paddle.nn.Linear(784,512),
    paddle.nn.ReLU(),
    paddle.nn.Dropout(0.2),
    paddle.nn.Linear(512,10)
)

model = paddle.Model(mnist)
train_loader = paddle.io.DataLoader(train_dataset,batch_size=64,shuffle=True)
loss_fn = paddle.nn.CrossEntropyLoss()
def train():
    epochs=2
    adam = paddle.optimizer.Adam(learning_rate=0.001,parameters=model.parameters())

    for epoch in range(epochs):
        for batch_id,data in enumerate(train_loader()):
            x_data=data[0]
            y_data=data[1]
            predicts = model(x_data)
            acc = paddle.metric.accuracy(predicts,y_data)
            loss = loss_fn(predicts,y_data)
            loss.backward()
            if batch_id%100==0:
                print("epoch{},batch_di:{},loss is:{},acc is:{}".format(epoch,batch_id,loss.numpy(),acc.numpy()))
            adam.step()
            adam.clear_grad()
train()

提示错误信息如下：
W0520 16:54:35.789089 11369 device_context.cc:404] Please NOTE: device: 0, GPU Compute Capability: 7.5, Driver API Version: 11.1, Runtime API Version: 10.1
W0520 16:54:35.792407 11369 device_context.cc:422] device: 0, cuDNN Version: 7.6.

--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
0   paddle::framework::SignalHandle(char const*, int)
1   paddle::platform::GetCurrentTraceBackString[abi:cxx11]()

----------------------
Error Message Summary:
----------------------
FatalError: `Segmentation fault` is detected by the operating system.
  [TimeInfo: *** Aborted at 1621500886 (unix time) try "date -d @1621500886" if you are using GNU date ***]
  [SignalInfo: *** SIGSEGV (@0xb4) received by PID 11369 (TID 0x7f5f40e73740) from PID 180 ***]

这个问题怎么解决，看论坛很多这个问题更换cuda版本等都已经尝试过了，解决不了，

**Comment by Joejiong** [comment]
你好，你的cuda Driver API Version: 是 11.1，需要安装相应的paddlepaddle-gpu version

**Comment by qingchunnianshao** [comment]
能直接说明是哪个版本吗这个11.1对应哪个版本，安装包后缀不是指定的是CUDA版本吗

**Comment by qingchunnianshao** [comment]
> 你好，你的cuda Driver API Version: 是 11.1，需要安装相应的paddlepaddle-gpu version

能直接说明是哪个版本吗这个11.1对应哪个版本，安装包后缀不是指定的是CUDA版本吗
