### ISSUE TITLE
建议增加Python调用加密模型

### ISSUE THREAD

**Issue by monkeycc** [PaddlePaddle/Paddle#33038]
模型加密 已经完成 也有key了

问题是 怎么用Python 调用 加密模型

所以请官方 增加一个 python 能调用加密模型的方法

因为我不会C++

对于python源码的加密 总是有办法的
但是起码paddle 也要有一个python怎么调用加密的说明
毕竟不是所有使用者 都会用C++给客户 去部署环境

**Comment by TeslaZhao** [comment]
用户您好！python代码加密一直是python语言弱项，通过反汇编工具很轻松地反解出python源码，使用python代码做解密，无法保护模型的安全。因此我们强烈建议您使用C/C++方式做模型解密和加载。在没有安全的python代码防护方案之前，暂不提供python的解密示例。

**Comment by monkeycc** [comment]
@TeslaZhao 

python 的 pyd 加密
你能轻松反汇编出来？

exe反编译一堆软件
pyd的反编译 一个都没
