### ISSUE TITLE
使用别人训练出来的模型进行目标检测，其中yml文件和模型权重weights通过解压得到，然后在预测的时候报错'architecture' not specified in config file. Please set it in config file,预测代码为!python -u PaddleDetection-release-2.0-rc/tools/infer.py --config ppyolov2_yml/ppyolo_r50vd_dcn_voc.yml -o weights=my_best_model --infer_img MOT20/test/MOT20-04/img1/000015.jpg --draw_threshold 0.1

### ISSUE THREAD

**Issue by RussellCandy** [PaddlePaddle/Paddle#33033]
报错如下:
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  def convert_to_list(value, n, name, dtype=np.int):
2021-05-20 23:27:11,700 - ERROR - 'architecture' not specified in config file. Please set it in config file.

麻烦大家了，谢谢大家

**Comment by Joejiong** [comment]
你好，感谢你的问题，可以提供更详细的可以复现的代码吗，谢谢
可以问一下，ppyolo的同学 @heavengate

**Comment by yanyide123** [comment]
执行命令 python tools/export_model.py -c deploy/pipeline/config/infer_cfg_pphuman.yml --output_dir=./inference_model -o weights=F:/PaddleDetection-releas

下面是一些警告
e-2.6/deploy/pipeline/weights/ppyoloe_crn_s_80e_smoking_visdrone/model.pdiparams
D:\miniconda3\envs\paddle\lib\site-packages\paddle\vision\transforms\functional_pil.py:36: DeprecationWarning: NEAREST is deprecated and will be removed in Pillow 10 (2023-07-01). Use
Resampling.NEAREST or Dither.NONE instead.
  'nearest': Image.NEAREST,
D:\miniconda3\envs\paddle\lib\site-packages\paddle\vision\transforms\functional_pil.py:37: DeprecationWarning: BILINEAR is deprecated and will be removed in Pillow 10 (2023-07-01). Use
 Resampling.BILINEAR instead.
  'bilinear': Image.BILINEAR,
D:\miniconda3\envs\paddle\lib\site-packages\paddle\vision\transforms\functional_pil.py:38: DeprecationWarning: BICUBIC is deprecated and will be removed in Pillow 10 (2023-07-01). Use
Resampling.BICUBIC instead.
  'bicubic': Image.BICUBIC,
D:\miniconda3\envs\paddle\lib\site-packages\paddle\vision\transforms\functional_pil.py:39: DeprecationWarning: BOX is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resa
mpling.BOX instead.
  'box': Image.BOX,
D:\miniconda3\envs\paddle\lib\site-packages\paddle\vision\transforms\functional_pil.py:40: DeprecationWarning: LANCZOS is deprecated and will be removed in Pillow 10 (2023-07-01). Use
Resampling.LANCZOS instead.
  'lanczos': Image.LANCZOS,
D:\miniconda3\envs\paddle\lib\site-packages\paddle\vision\transforms\functional_pil.py:41: DeprecationWarning: HAMMING is deprecated and will be removed in Pillow 10 (2023-07-01). Use
Resampling.HAMMING instead.
  'hamming': Image.HAMMING

只有这一条报错信息，按照使用paddledetection 2.5，只有下面一条报错信息，没有其他的
[10/09 18:12:15] ppdet.utils.check ERROR: 'architecture' not specified in config file. Please set it in config file.
