### ISSUE TITLE
[论文复现] 图片尺寸较大时报错cudaErrorInvalidConfiguration: invalid configuration argument

### ISSUE THREAD

**Issue by zizizihua** [PaddlePaddle/Paddle#33057]
- 版本、环境信息：
    1）PaddlePaddle 2.1
    2）GPU：v100 32G, cuda10.1
    3）系统环境：aistudio Ubuntu 16.04.6 LTS，Python3.7

复现deformable detr论文，在模型前向推理阶段，batchsize设置为1，若图片尺寸设置比较大(800, 1333)，执行paddle.cusum()和其他一些op会报这个错误：
```
SystemError: (Fatal) Operator set_value raises an thrust::system::system_error exception.
The exception content is
:parallel_for failed: cudaErrorInvalidConfiguration: invalid configuration argument. (at  /paddle/paddle/fluid/imperative/tracer.cc:192)
```
将图片尺寸设置小一些，如（608, 1024）则能正常运行。

**Comment by haozech** [comment]
你好，是在运行paddle.fluid.cumsum()这个api的时候，大图片尺寸会报错吧？能否提供简单的可复现代码呢？

**Comment by zizizihua** [comment]
@haozech 复现代码已发你邮箱，chenhaoze94@gmail.com

**Comment by wawltor** [comment]
您好，复现了一下代码，排查了一下问题，主要的原因是cumsum和linspace op都是用了了cuda官方的thrust库，当元素的个数超过了int32的就会触发thrust的bug，目前cuda官方已经修复了这个问题，但是这个修复是随着cuda版本修复的，因此需要更新cuda版本。cuda 11版本可以尝试一下，PaddlePaddle也会尝试出一个兜底方案。

**Comment by zizizihua** [comment]
好的，谢谢！
