### ISSUE TITLE
Paddle的分布式模型更新机制

### ISSUE THREAD

**Issue by cszhou** [PaddlePaddle/Paddle#3305]
在MPI环境下，paddle是如何在多个node之间做分布式环境下的参数同步的？
假设node数为n，是n个node算完一个batch后，将各自更新后网络的参数传到node 0上，对各个node的参数取平均，然后node 0再分发给其他node？

**Comment by Xreki** [comment]
Paddle采用的不是这种集中式的同步机制，具体实现机制请参考文档：
- https://github.com/PaddlePaddle/Paddle/tree/develop/doc/design/cluster_train#training-job
- http://doc.paddlepaddle.org/release/0.10.0/doc/howto/usage/k8s/k8s_aws_en.html#parameter-servers-and-trainers

谢谢@qingqing01 @typhoonzero 提供的资料。

**Comment by cszhou** [comment]
@Xreki 
谢谢。发现没看懂，我再使劲看看。。不懂再问。

**Comment by cszhou** [comment]
Thanks. @Xreki 
我的理解是隔几个batch做同步，隔的batch数量应该隔多少比较合理。这个paddle是否有提供接口让我们设置？
如果没有提供的话，隔几个batch做更新跟batchsize是否有关，batchsize应该设置多大比较合理？

现在我的数据跑出来的时间是这样子的，
bs=128，经过15个batch要24秒。每个batch 要1.6秒。每秒单个node处理80条样本
bs=512，经过50个batch要77秒。每个batch要1.54秒。每秒单个node处理332条样本
bs=1024，经过20个batch要32秒。每个batch要1.6秒。每秒单个node处理640条样本
bs=4096，经过20个batch要34秒。每个batch要1.7秒。每秒单个node处理2409条样本
bs=16384，经过20个batch要42秒。每个batch要2.1秒。每秒单个node处理7801条样本

我希望每秒处理的样本数能够达到4w条每秒。

**Comment by luotao1** [comment]
> 我的理解是隔几个batch做同步，隔的batch数量应该隔多少比较合理。

这个对不同的任务设置的数目都是不一样的，paddle没有这样的接口可以做判断，其他的平台也没有这样的接口。

> 隔几个batch做更新跟batchsize是否有关，batchsize应该设置多大比较合理

这个要看你收敛的精度，如果batchsize过大，一个pass内更新的次数肯定会少，可能会影响收敛的精度。batchsize设置多大和任务、数据都有关，无法给出一个具体的数值。

> 我希望每秒处理的样本数能够达到4w条每秒。

可以通过再增加机器来获得。可以看下每个节点的GPU或者CPU是不是跑满了，如果跑满了，就要增加机器来获得更快的速度。

**Comment by cszhou** [comment]
@luotao1 
辛苦paddle的同学们，明白了。

**Comment by pkuyym** [comment]
Close it due to problem solved. Please feel free to reopen it.
