### ISSUE TITLE
[Transformer CV]论文复现

### ISSUE THREAD

**Issue by Zhaobo19** [PaddlePaddle/Paddle#33054]
在下图的那个文件中没有对应的paddleAPI,请问是否还与别的API，这个作用应该是与GPU分配内存有关的吧
# detr-master/util/misc.py
原文:https://github.com/facebookresearch/detr
![image](https://user-images.githubusercontent.com/68489388/119213046-03490800-baef-11eb-89f8-f82b407f2956.png)

**Comment by zhwesky2010** [comment]
@Zhaobo19 这个是：step1：将data 转为序列化，并将Python序列化内容先转化为torch的内存结构；
step2：将torch的内存结构转化为Tensor；Paddle目前没有第一步的API，不过data可以直接通过Paddle.to_tensor转化为Tensor，请问data是什么类型的数据呢。
