### ISSUE TITLE
用YOLOV3进行昆虫目标检测的案例，在训练过程中会报system error

### ISSUE THREAD

**Issue by gzwzzu** [PaddlePaddle/Paddle#33068]
Paddlepaddle版本：2.0
环境：aistudio上的GPU版本

https://aistudio.baidu.com/aistudio/projectdetail/1557835?channelType=0&channel=0

用YOLOV3进行昆虫目标检测的案例，在训练过程中会报system error，信息如下：

---------------------------------------------------------------------------SystemError                               Traceback (most recent call last)<ipython-input-61-4fa909203cbd> in <module>
     43     MAX_EPOCH = 1
     44     for epoch in range(MAX_EPOCH):
---> 45         for i, data in enumerate(train_loader()):
     46             img, gt_boxes, gt_labels, img_scale = data
     47             gt_scores = np.ones(gt_labels.shape).astype('float32')
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dataloader/dataloader_iter.py in __next__(self)
    349         try:
    350             if in_dygraph_mode():
--> 351                 return self._reader.read_next_var_list()
    352             else:
    353                 if self._return_list:
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/multiprocess_utils.py in __handler__(signum, frame)
    132         # this handler will be called whenever the child process exits
    133         # normally or abnormally.
--> 134         core._throw_error_if_process_failed()
    135         if current_handler is not None:
    136             current_handler(signum, frame)
SystemError: (Fatal) DataLoader process (pid   1. If run DataLoader by DataLoader.from_generator(...), queue capacity is set by from_generator(..., capacity=xx, ...).
  2. If run DataLoader by DataLoader(dataset, ...), queue capacity is set as 2 times of the max value of num_workers and len(places).
  3. If run by DataLoader(dataset, ..., use_shared_memory=True), set use_shared_memory=False for not using shared memory.) exited is killed by signal: 301.
  It may be caused by insufficient shared storage space. This problem usually occurs when using docker as a development environment.
  Please use command `df -h` to check the storage space of `/dev/shm`. Shared storage space needs to be greater than (DataLoader Num * DataLoader queue capacity * 1 batch data size).
  You can solve this problem by increasing the shared storage space or reducing the queue capacity appropriately.
Bus error (at /paddle/paddle/fluid/imperative/data_loader.cc:161)

**Comment by chenjiaoAngel** [comment]
<img width="820" alt="image" src="https://user-images.githubusercontent.com/38650344/119301174-a4bd8e80-bc94-11eb-9fa5-f110fb8f99d7.png">
根据这个错误信息提示：使用的docker 镜像空间不够引起的，需要清理该空间，留有足够空间运行程序
