### ISSUE TITLE
语法怎么写同一个embedding空间为两个slot所用

### ISSUE THREAD

**Issue by youan1** [PaddlePaddle/Paddle#3306]
如题:

比方说我有两个slot，分别为用户过去浏览的新闻类型和目前正在曝光的新闻类型，那么我写的语法就如下了：
emb1_1 = paddle.layer.embedding(input=data1, size=128, param_attr=paddle.attr.Param(
                                 initial_std=emb_layer_init_std[0]))
emb1_1 = paddle.layer.pooling(input=emb1_1,
                              pooling_type=AvgPooling())

emb1_2 = paddle.layer.embedding(input=data2, size=128, param_attr=paddle.attr.Param(
                                 initial_std=emb_layer_init_std[0]))
emb1_2 = paddle.layer.pooling(input=emb1_2,
                              pooling_type=AvgPooling())

这样data1和data2就没有共享同一个embedding空间了，换句话说，对于同一个ID，它出现在data1和data2，得到的 embedding值是不一样的，请问有什么办法写语法共享么

**Comment by Xreki** [comment]
可以尝试设置Param为相同的`name`，这样将会更新同一个参数，如：
```python
emb1_1 = paddle.layer.embedding(input=data1, size=128,
                                param_attr=paddle.attr.Param(name='_emb1_',
                                                             initial_std=emb_layer_init_std[0]))
emb1_1 = paddle.layer.pooling(input=emb1_1, pooling_type=AvgPooling())

emb1_2 = paddle.layer.embedding(input=data2, size=128,
                                param_attr=paddle.attr.Param(name='_emb1_',
                                                             initial_std=emb_layer_init_std[0]))
emb1_2 = paddle.layer.pooling(input=emb1_2, pooling_type=AvgPooling())
```

**Comment by youan1** [comment]
好的，谢谢

**Comment by Master-Luman** [comment]
两个 slot embedding共享之后，其中一个 stop_gradient 设为 True，另一个 还会更新吗？
