### ISSUE TITLE
[论文复现]OSError: (External)  Cuda error(9)

### ISSUE THREAD

**Issue by jonny4929** [PaddlePaddle/Paddle#33063]
version: paddlepaddle 2.1.0

Traceback (most recent call last):
  File "tools/train.py", line 118, in <module>
    main(args)
  File "tools/train.py", line 90, in main
    epoch_id, 'train')
  File "/home/aistudio/PaddleClas/tools/program.py", line 309, in run
    fetchs = create_fetchs(feeds, net, config, mode)
  File "/home/aistudio/PaddleClas/tools/program.py", line 189, in create_fetchs
    epsilon, use_mix, use_distillation)
  File "/home/aistudio/PaddleClas/tools/program.py", line 103, in create_loss
    return loss(out, feeds["label"])
  File "/home/aistudio/PaddleClas/ppcls/modeling/loss.py", line 85, in __call__
    cost = self._crossentropy(input, target, use_pure_fp16)
  File "/home/aistudio/PaddleClas/ppcls/modeling/loss.py", line 51, in _crossentropy
    cost = F.cross_entropy(input=input, label=target) 
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/nn/functional/loss.py", line 1464, in cross_entropy
    return core.ops.mean(out)
OSError: (External)  Cuda error(9), invalid configuration argument.
  [Advise: This indicates that a kernel launch is requesting resources that can never be satisfied by the current device. Requestingmore shared memory per block than the device supports will trigger this error, as will requesting too many threads or blocks.See cudaDeviceProp for more device limitations.] (at /paddle/paddle/fluid/operators/mean_op.cu:75)
  [operator < mean > error]

aistudio link: https://aistudio.baidu.com/aistudio/projectdetail/1753843
该项目代码基于paddleclas，改动部分为PaddleClas/ppcls/modeling/architectures/coat.py, PaddleClas/ppcls/modeling/architectures/__init__.py，在自己的训练脚本上也出现了相同的错误，应该与paddleclas无关。

训练时batch_size设置为16时，可以正常训练，设置为32时就会出现如上错误。
验证时，即使batch_size设置为32时仍可以正常运行，且已完成前向验证。

**Comment by chenjiaoAngel** [comment]
请问GPU 版本是？根据错误信息提示，batch_size=32 时，训练时资源好像不足，需要分配更多的内存资源or线程数去满足？ Requestingmore shared memory per block than the device supports will trigger this error, as will requesting too many threads or blocks

**Comment by jonny4929** [comment]
在aistudio的v100,paddle2.1.0版本以及我自己的2070super上都出现了相同的错误，batch_size=16时显存占用在3G多一些，batch_size=32时显存占用应该在8G以内。

**Comment by jiweibo** [comment]
您好，看报错信息像是mean_op的cuda kernel需要share memory超限制了，这个问题我们找负责人看一下，感谢反馈

**Comment by zhangpu1211** [comment]
> 您好，看报错信息像是mean_op的cuda kernel需要share memory超限制了，这个问题我们找负责人看一下，感谢反馈

您好，我也遇到这个问题了，https://github.com/PaddlePaddle/Paddle/issues/34561，请问这个问题现在解决了么

**Comment by shangzhizhou** [comment]
您好，目前版本的aistudio(paddle2.1.2)已经不再复现次问题，请尝试。
