### ISSUE TITLE
fusion hard_swish in int8 caused accuracy drop

### ISSUE THREAD

**Issue by lidanqing-vv** [PaddlePaddle/Paddle#33069]
1）PaddlePaddle版本：2.1

**Comment by sfraczek** [comment]
~~Hi,~~
~~I found some divergence between OneDNN and PaddlePaddle hard swish implementations. The paper describes hard_swish as having **threshold** equal 3. Documentations for both projects PaddlePaddle and OneDNN have the same value 3. However, in PaddlePaddle code, the default value for **threshold** is 6.~~
## OneDNN
![image](https://user-images.githubusercontent.com/17185347/146429002-a3ee5e28-c71f-44ae-a5cd-4f7a24af3b17.png) 
## Paddle
![image](https://user-images.githubusercontent.com/17185347/146429419-ba0d6a5b-1fc9-45d8-b5d9-de9a403ab1c6.png)
https://www.paddlepaddle.org.cn/documentation/docs/en/api/paddle/nn/functional/hardswish_en.html#hardswish

https://github.com/PaddlePaddle/Paddle/blob/a37be82fddff46235267961c462b48451d3b729e/paddle/fluid/operators/activation_op.cc#L809-L837

~~@huangjun12 please take a look. Does it have to be 6 not 3? I wonder if this could be causing change in accuracy?~~

**Comment by lidanqing-vv** [comment]
@lidanqing-intel  @baoachun

**Comment by sfraczek** [comment]
I found that actually paddle's hard_swish is same as oneDNN's just using different equation and thus different meaning for threshold.

**Comment by baoachun** [comment]
这个现在是int8精度下降吗？问题是什么呢？

**Comment by lidanqing-vv** [comment]
The fix PR https://github.com/PaddlePaddle/Paddle/pull/38331 has been merged hence I close this issue.
