### ISSUE TITLE
slice op头文件的文档描述和实际代码实现的不一致

### ISSUE THREAD

**Issue by BillDior** [PaddlePaddle/Paddle#33079]
https://github.com/PaddlePaddle/Paddle/blob/66c514ce83eb9af3c5e8b583c45dc90a4a50ed3d/paddle/fluid/operators/slice_op.cc#L230

这里StartsTensorList 和EndTensorList的类型是int32

https://github.com/PaddlePaddle/Paddle/blob/66c514ce83eb9af3c5e8b583c45dc90a4a50ed3d/paddle/fluid/operators/slice_op.h#L94
实际实现的时候数据类型用的是int64

**Comment by chenjiaoAngel** [comment]
收到，稍后会找相关负责人进行修正

**Comment by liym27** [comment]
@BillDior 感谢建议。
但文档描述是没有问题的，` starts = GetDataFromTensorList<int64_t>(list_new_starts_tensor); ` 这里的 int64_t 对应的是 vector `start` 的元素数据类型，而非 `StartsTensorList` 的数据类型。

**Comment by BillDior** [comment]
> @BillDior 感谢建议。
> 但文档描述是没有问题的，`starts = GetDataFromTensorList<int64_t>(list_new_starts_tensor);` 这里的 int64_t 对应的是 vector `start` 的元素数据类型，而非 `StartsTensorList` 的数据类型。

所以StartTensorList是int32类型，在GetDataFromTensorList会做一次类型转换？ 为什么要这样设计呢

**Comment by liym27** [comment]
> 所以StartTensorList是int32类型，在GetDataFromTensorList会做一次类型转换？ 为什么要这样设计呢

这里是为了兼容 int32 与 int64，提高接口易用性。 了解更多细节，也可以阅读相关源码。
请问是在使用过程中有什么问题吗？
