### ISSUE TITLE
特征增量更新

### ISSUE THREAD

**Issue by yinyunfeng** [PaddlePaddle/Paddle#3307]
我们组目前在训练的模型后续上线后会遇到特征增量更新的问题，即特征size会变大、引入一些新的特征id，所以想知道：

1. paddle是否可以帮忙支持一下，大概需要多久；
2. 如果不支持的话，是否可以提供方案，我们自己实现？
    了解到一种方案是：保存一个新模型，参数随机初始化，除最后一层的参数外，都用原来的模型参数代替。这种方案中涉及的改模型参数paddle是否支持？
    除这种外是否还有更优方案？

**Comment by Xreki** [comment]
Similar to #1720

**Comment by luotao1** [comment]
1. paddle目前没有人力来支持增量更新的问题。
2. 存一个新模型，参数随机初始化，除最后一层的参数外，都用原来的模型参数代替。这种方案中涉及的改模型参数paddle是否支持？ @lcy-seso 能帮忙回答一下么？

**Comment by yinyunfeng** [comment]
举个具体例子：旧模型输入层大小是10000，参数已经训练好了；    现在新模型的输入层大小增加了5，   那么能否用之前的一个 10000*10 的参数矩阵 更新 现在的 10005*10 的矩阵，这个新矩阵，只有5*10部分需要随机初始化，其他部分还用之前训好的参数

**Comment by yinyunfeng** [comment]
https://github.com/PaddlePaddle/book/blob/develop/01.fit_a_line/train.py#L36

**Comment by wanghaoshuang** [comment]
close this issue due to inactivity.
