### ISSUE TITLE
Windows编译预测库错误

### ISSUE THREAD

**Issue by siqiaof** [PaddlePaddle/Paddle#33073]
PaddlePaddle 版本：v2.0.0-rc1
使用 cmake 3.20.0-rc2 + VS2019 编译带 GPU 的预测库

在构建 cryptopp 和 eigen 时报错，更换了 gitee 上的源依然报错
![image](https://user-images.githubusercontent.com/67352303/119310361-37185f00-bca2-11eb-9406-cb7fc3c9ec81.png)

**Comment by chenjiaoAngel** [comment]
这个看起来是网络问题，有些第三方库没有下载成功。辛苦重新拉取代码和编译试试

**Comment by siqiaof** [comment]
> 这个看起来是网络问题，有些第三方库没有下载成功。辛苦重新拉取代码和编译试试

但是我把源码下载的路径改成gitee了，按理说不应该再有网络问题，看了下对应的src文件夹下源码好像也已经下下来了。

使用的是这两个源码
https://gitee.com/tianjianhe/cryptopp
https://gitee.com/hsia_ray/eigen-git-mirror

这两张图是下载后的源码文件夹，可以帮忙看下是不是下全了吗？
![image](https://user-images.githubusercontent.com/67352303/119332440-2cb68f00-bcbb-11eb-9339-edb950cbc580.png)
![image](https://user-images.githubusercontent.com/67352303/119332477-37712400-bcbb-11eb-84c0-f458949b6c89.png)

**Comment by xinsuinizhuan** [comment]
建议支持，我们手动下载后，放到指定目录也可以编译。
