### ISSUE TITLE
分布式单机多卡训练出现错误

### ISSUE THREAD

**Issue by FL77N** [PaddlePaddle/Paddle#33074]
使用 paddledetection 2.0.2 源码，在aistudio 脚本任务进行单机四卡训练出现以下错误

ABORT!!! Out of all 4 trainers, the trainer process with rank=[3] was aborted

**Comment by wangxicoding** [comment]
看一下log/workerlog.3里有没有啥报错

**Comment by FL77N** [comment]
> 看一下log/workerlog.3里有没有啥报错

应该怎么看呢？因为报错了，没有输出文件呀

**Comment by wangxicoding** [comment]
使用python -m paddle.distributed.launch启动的吗，应该会有一个log文件夹，或者没有指定会直接将所有卡的log输出到终端，应该也可以看到出错的log。

**Comment by FL77N** [comment]
> 使用python -m paddle.distributed.launch启动的吗，应该会有一个log文件夹，或者没有指定会直接将所有卡的log输出到终端，应该也可以看到出错的log。

对的是这样启动的，可下载输出那是灰色的。只能查看运行日志，日志是这样写的：
INFO 2021-05-24 17:17:14,611 launch_utils.py:307] terminate all the procs
ERROR 2021-05-24 17:17:14,611 launch_utils.py:545] ABORT!!! Out of all 4 trainers, the trainer process with rank=[3] was aborted. Please check its log.
INFO 2021-05-24 17:17:17,615 launch_utils.py:307] terminate all the procs
[INFO]: train job failed! train_ret: 1
