### ISSUE TITLE
算子问题

### ISSUE THREAD

**Issue by btobab** [PaddlePaddle/Paddle#33082]
1）PaddlePaddle版本：2.0.2
    2）系统环境：本地
`def make_trg_mask(self, trg):
        
        #trg = [batch size, trg len]
        
        trg_pad_mask = (trg != self.trg_pad_idx).unsqueeze(1).unsqueeze(2)
        
        #trg_pad_mask = [batch size, 1, 1, trg len]
        
        trg_len = trg.shape[1]
        
        trg_sub_mask = torch.tril(torch.ones((trg_len, trg_len), device = self.device)).bool()
        
        #trg_sub_mask = [trg len, trg len]
            
        trg_mask = trg_pad_mask & trg_sub_mask
        
        #trg_mask = [batch size, 1, trg len, trg len]
        
        return trg_mask`
有人在上述pytorch代码中使用了&运算符，我在paddle环境下运行类似代码：
`import paddle
x=paddle.ones([128,30]).astype("int64")
y=paddle.zeros([128,30]).astype("int64")
x,y=x.cast(bool),y.cast(bool)
print(x&y)`
却报错说tensor不支持&运算符

**Comment by chenjiaoAngel** [comment]
逻辑&运算是支持的，请参考文档，用logic_and函数进行实现，https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/logical_and_cn.html#logical-and

**Comment by btobab** [comment]
好哒，谢谢大佬
