### ISSUE TITLE
v2新手入门程序运行出问题

### ISSUE THREAD

**Issue by Ericva** [PaddlePaddle/Paddle#3308]
rt，把链接中的代码拷贝出来运行不了，链接为：http://doc.paddlepaddle.org/doc_cn/getstarted/concepts/use_concepts_cn.html
是dataprovider出现问题，麻烦帮忙看下

**Comment by Xreki** [comment]
http://doc.paddlepaddle.org/doc_cn/getstarted/concepts/use_concepts_cn.html 页面只是在展示Paddle基本的用法，完整的示例代码见https://github.com/PaddlePaddle/book/blob/develop/01.fit_a_line/train.py ，若还有问题，请贴出具体的错误

**Comment by Ericva** [comment]
对比了下两个demo，问题基本定位在trainer.train的reader参数位置。后面贴的demo这个地方是个黑盒，不便学习。能否帮忙指出第一个出现问题的reader函数的问题在哪里？根据wiki https://github.com/PaddlePaddle/Paddle/tree/develop/doc/design/reader的描述，没能发现第一个demo这个地方的问题，麻烦帮忙定位下?

**Comment by Ericva** [comment]
已经定位问题，麻烦修改下网页代码中对label的定义，这个地方需要标量的label也是在list里面，即
train_y = np.array([[-2], [-3], [-7], [-7]])。多谢服务。

**Comment by Xreki** [comment]
@Ericva 多谢反馈。我们会尽快修正。
