### ISSUE TITLE
ImportError after import in python3

### ISSUE THREAD

**Issue by GlennLoveZhen0124** [PaddlePaddle/Paddle#33088]
我python3安装后，在命令行python3中， import paddle报错如下：
ImportError: /opt/compiler/gcc-4.8.2/lib/libstdc++.so.6: version `CXXABI_1.3.8' not found
请问怎么解决？

**Comment by chenjiaoAngel** [comment]
请先查看当前目录下是否安装libstdc++.so.6，指令： strings /usr/lib64/libstdc++.so.6|grep CXXABI ；如果有话，将相关SO移植到当前目录。具体细节可参考：https://blog.csdn.net/zerow__/article/details/88845192；如果没有话，辛苦先下载相关SO，重新链接，具体细节可参考：https://blog.csdn.net/u012811841/article/details/77854581
