### ISSUE TITLE
paddle.vision.ImageFolder 没有返回标签，导致整个函数无用

### ISSUE THREAD

**Issue by voidvelocity** [PaddlePaddle/Paddle#33090]
paddle.vision.ImageFolder 没有返回标签，导致整个函数无用

**Comment by heavengate** [comment]
你好，`paddle.vision.ImageFolder`这个是用于预测的时候读取目录下全部图像定义的数据集，不是针对训练或者评估的设计场景，如果是训练或者评估的时候需要标签数据，可以使用`paddle.vision.DatasetFolder`，逻辑和`paddle.vision.ImageFolder`基本一致的，并且包含标签
