### ISSUE TITLE
多卡训练保存模型问题

### ISSUE THREAD

**Issue by yeyupiaoling** [PaddlePaddle/Paddle#33095]
- PaddlePaddle 2.0.2
 - Python

在PaddlePaddle 2.0之后多卡训练输出的是多次。是不是说每个GPU都是单独训练的？他们的模型参数会实时同步吗？如果我需要在每一轮结束后保存模型，需要过滤掉其他的GPU执行吗？例如这：
```python 
        if dist.get_rank() == 0:
            save_model(args, model, optimizer)
```

**Comment by qili93** [comment]
请问是是用“python -m paddle.distributed.launch ”的方式来启动多卡训练的吗？如果是的话，多卡之间会自动进行参数同步，保存模型或者checkpoint的时候保存rank 0的结果就可以，可以参考这里的代码
https://github.com/PaddlePaddle/PaddleNLP/blob/develop/examples/language_model/bert/run_glue.py#L387

```python
if paddle.distributed.get_rank() == 0:  
    # save checkpoint
```

**Comment by yeyupiaoling** [comment]
@qili93 我看你给的代码中，如果是多卡训练，为啥要`model._layers`，而不是直接`model`呢？

https://github.com/PaddlePaddle/PaddleNLP/blob/7955b9302c2655aa4d4e10795113f27306dfaa70/examples/language_model/bert/run_glue.py#L394-L396

**Comment by yeyupiaoling** [comment]
@qili93 我看你给的代码中，如果是多卡训练，为啥要`model._layers`，而不是直接`model`呢？

https://github.com/PaddlePaddle/PaddleNLP/blob/7955b9302c2655aa4d4e10795113f27306dfaa70/examples/language_model/bert/run_glue.py#L394-L396
