### ISSUE TITLE
在jupyter中第二次定义model时报错

### ISSUE THREAD

**Issue by voidvelocity** [PaddlePaddle/Paddle#33091]
例如 model = Net() ；Net为自定义的类。在jupyterlab中第二次运行时就报错，每次都要重启jupyter！！！
报错如下：
ValueError: parameter name [conv1_weights] have be been used. In dygraph mode, the name of parameter can't be same.Please check the parameter attr value passed to self.create_parameter or constructor of dygraph Layers

**Comment by wadefelix** [comment]
jupyterlab会自动spawn执行进程出来，而且这个执行进程是不退出的以保留执行上下文。
您可以在kernel菜单下shutdown掉kernel，或者在Running这个页查看和管理执行进程，可以结束它，然后再运行ipynb代码块就可以了，这样可以避免重启jupyter了。
