### ISSUE TITLE
[复现营] parralel_for failed

### ISSUE THREAD

**Issue by Fan-Zhixuan** [PaddlePaddle/Paddle#33107]
![QQ图片20210525163645](https://user-images.githubusercontent.com/55394653/119466863-998f5f00-bd77-11eb-91f9-bcd02fb9bef8.png)

**Comment by qili93** [comment]
能提供一下环境信息吗？包括Paddle版本这里是2.0.2，GPU型号，CUDA和CUDNN/NCCL版本号，系统环境和Python版本。 注：您可以通过执行[summary_env.py](https://github.com/PaddlePaddle/Paddle/blob/develop/tools/summary_env.py)获取以上信息。

还有包括训练信息，你的模型代码，和复现步骤。

**Comment by Fan-Zhixuan** [comment]
paddle:2.0.2
GPu:1080
CUDA:10.2
CUDNN:7.6
系统：Win10
python:3.8
我是用swintransformer为基础搭建的unet，问题出在drop_path上，如果将drop_path_rate设为零，则不会出现这个问题

**Comment by qili93** [comment]
这个问题为已知问题，目前正在修复中，具体见 https://github.com/PaddlePaddle/PaddleClas/pull/685 已有icafe卡片跟进这个问题，需要等待修复。

**Comment by Fan-Zhixuan** [comment]
在GPU环境里生成维度过大的随机数会报错，但是在CPU环境下就不会
