### ISSUE TITLE
在显存容量没有问题的情况下，batchsize过大会报错

### ISSUE THREAD

**Issue by Fan-Zhixuan** [PaddlePaddle/Paddle#33101]
为使您的问题得到快速解决，在建立Issues前，请您先通过如下方式搜索是否有相似问题:【搜索issue关键字】【使用labels筛选】【官方文档】

如果您没有查询到相似问题，为快速解决您的提问，建立issue时请提供如下细节信息：
- 标题：简洁、精准概括您的问题，例如“Insufficient Memory xxx" ”
- 版本、环境信息：
    1）PaddlePaddle版本：gpu——2.0.2
    2）CPU：预测若用CPU，请提供CPU型号，MKL/OpenBlas/MKLDNN/等数学库使用情况
    3）GPU：1080 cuda10.2 cuDNN7.6
    4）系统环境：win10 python3.8

    1）单机，单卡
    2）8gb
    
![QQ图片20210525145228](https://user-images.githubusercontent.com/55394653/119452362-d9027f00-bd68-11eb-8ff6-e448b288bb63.png)

**Comment by qili93** [comment]
可以提供一下复现代码或者模型吗？这里需要复现一下才能定位是哪里出的问题，看情况是core dump了。或者您可以提供一下gdb core dump文件的信息吗？看看有没有什么线索。
