### ISSUE TITLE
paddle2.1.0版本GPU显存溢出问题

### ISSUE THREAD

**Issue by sjhsjn1017** [PaddlePaddle/Paddle#33118]
paddle2.1.0版本GPU显存溢出：

用paddle2.1.0版本训练的过程中出现GPU显存溢出的报错，用的环境是aistudio的16G V100环境。报错的截图如下：
图1
![image](https://user-images.githubusercontent.com/50991400/119507761-b0e34200-bda1-11eb-9dc3-e2242f1582c0.png)

这里显存溢出的问题是在我用了下面的tensor切片索引操作后出现的：
图2：
![image](https://user-images.githubusercontent.com/50991400/119508415-51396680-bda2-11eb-82ca-74435971d69a.png)
在paddle2.0.2版本中上面的操作是不支持的，所以在2.0.2版本中我做了一个numpy的转换，如下图3，这种方式是可以的，而且不会出现显存溢出问题。
图3：
![image](https://user-images.githubusercontent.com/50991400/119508766-98275c00-bda2-11eb-85b3-fb9ea49ae0e4.png)

发布了2.1.0版本后我抱着试一试的态度，试了下图2的写法，发现2.1.0版本支持了这种操作，但是就出现了如图1所示的显存溢出操作，而且看报错信息好像是在反向传播过程中出现的，不清楚到底是什么原因，希望有大佬能帮忙分析一下

**Comment by qili93** [comment]
请问能否提供一下复现代码呢，这里需要在16G V100上复现一下，定位一下问题在哪里，谢谢！
