### ISSUE TITLE
upgrade paddle.v2.plot to enable users to savefig

### ISSUE THREAD

**Issue by daiwk** [PaddlePaddle/Paddle#3312]
I think this line should be commented, 
https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/v2/plot/plot.py#L73

so that, we can
```
cost_ploter = Ploter(train_title, test_title)
cost_ploter.plt.savefig('xx.png')
```

**Comment by gongweibao** [comment]
Close it because of not activity.
