### ISSUE TITLE
[论文复现] MultiheadAttention在相同输入条件下torch和paddle输出有较明显差异

### ISSUE THREAD

**Issue by thunder95** [PaddlePaddle/Paddle#33124]
加载同样的权重， debug检查输入也是一致，但是输出结果就是差异明显。 请问二者接口上或实现上有什么差异么

**Comment by thunder95** [comment]
代码基本是按照torch复现的

```
self.self_attn = MultiHeadAttention(d_model, n_heads, dropout=dropout)
q = k = self.with_pos_embed(tgt, query_pos)
tgt2 = self.self_attn(q.transpose(0, 1), k.transpose(0, 1), tgt.transpose(0, 1))[0].transpose(0, 1)
```

```
self.self_attn = MultiHeadAttention(d_model, n_heads, dropout=dropout)
q = k = self.with_pos_embed(tgt, query_pos)
tgt2 = self.self_attn(q.transpose((1, 0, 2)), k.transpose((1, 0, 2)), tgt.transpose((1, 0, 2))).transpose((1, 0, 2))
```

**Comment by FrostML** [comment]
这两个 API 应该是能对齐的，需要确认下 `加载同样的权重` 转参数的时候，是否经过了 transpose？

**Comment by thunder95** [comment]
> 这两个 API 应该是能对齐的，需要确认下 `加载同样的权重` 转参数的时候，是否经过了 transpose？

转换权重过程中，我筛选了所有的torch.nn.Linear, 并进行转置。

等会我尝试下在网络结构中打印权重比较下。 @FrostML

**Comment by FrostML** [comment]
还有一点需要确认下的是，torch 的输入的维度，默认是 `[sequence length, batch size, embedding dimension]`.
Paddle 这里是 `[batch size, sequence length, embedding dimension]`.

我这里有一个早期时候对比两者精度的脚本，代码比较早了，不过 paddle 2.1 应该也还能跑，可以参考下：
``` python
import numpy as np
import paddle
import paddle.fluid as fluid
from paddle.nn.layer.transformer import Transformer
import torch


batch_size, d_model, n_head = 3, 8, 2
dim_feedforward = 16
dropout = 0.0
source_length, target_length = 5, 5 # 3, 3
num_encoder_layers, num_decoder_layers = 1, 1
np.random.seed(123)
paddle.seed(123)
torch.manual_seed(123)
torch.cuda.manual_seed(123)

with fluid.dygraph.guard(fluid.CUDAPlace(0)):
    transformer = Transformer(
        d_model,
        n_head,
        num_encoder_layers=num_encoder_layers,
        num_decoder_layers=num_decoder_layers,
        dim_feedforward=dim_feedforward,
        dropout=dropout,
        attn_dropout=dropout,
        act_dropout=dropout)

    transformer_torch = torch.nn.Transformer(
            d_model=d_model,
            nhead=n_head,
            num_encoder_layers=num_encoder_layers,
            num_decoder_layers=num_decoder_layers,
            dim_feedforward=dim_feedforward,
            dropout=dropout)

    name_param_dict = {}
    for i, param in enumerate(transformer.named_parameters()):
        pname = param[0]
        if 'cross_attn' in pname:
            pname = pname.replace("cross_attn", "multihead_attn")
        elif 'q' not in pname and 'k' not in pname and 'v' not in pname:
            continue
        param_np = param[1].numpy()
        pname = pname.replace('q_proj.', 'in_proj_')
        pname = pname.replace('k_proj.', 'in_proj_')
        pname = pname.replace('v_proj.', 'in_proj_')
        if pname not in name_param_dict:
            name_param_dict[pname] = param_np
        elif '_weight' in pname:
            name_param_dict[pname] = np.concatenate((name_param_dict[pname], param_np), axis=1)
        else:
            name_param_dict[pname] = np.concatenate((name_param_dict[pname], param_np), axis=0)

    device = torch.device('cuda:0')
    for i, param in enumerate(transformer_torch.named_parameters()):
        pname, pa = param[0], param[1]
        if 'in_proj' in pname or 'multihead_attn' in pname:
            param_np = name_param_dict[pname]
        else:
            param_np = transformer.state_dict()[pname].numpy()
        if pname.endswith('weight'):
            param_np = np.transpose(param_np)

        param[1].data = torch.from_numpy(param_np)


    # generate input
    src = np.random.rand(batch_size, source_length, d_model).astype(
            "float32")
    tgt = np.random.rand(batch_size, target_length, d_model).astype(
            "float32")
    # run paddle
    trans_output = transformer(paddle.to_tensor(src),
                                paddle.to_tensor(tgt)).numpy()

    # run torch
    src_torch = src.transpose(1,0,2)
    tgt_torch = tgt.transpose(1,0,2)
    trans_torch = transformer_torch(torch.from_numpy(src_torch), torch.from_numpy(tgt_torch))
    trans_torch_np = trans_torch.detach().numpy().transpose(1,0,2)

    np.testing.assert_allclose(trans_output, trans_torch_np, 1e-5, 1e-6)
```

**Comment by thunder95** [comment]
> 还有一点需要确认下的是，torch 的输入的维度，默认是 `[sequence length, batch size, embedding dimension]`.
> Paddle 这里是 `[batch size, sequence length, embedding dimension]`.
> 
> 我这里有一个早期时候对比两者精度的脚本，代码比较早了，不过 paddle 2.1 应该也还能跑，可以参考下：
> 
> ```python
> import numpy as np
> import paddle
> import paddle.fluid as fluid
> from paddle.nn.layer.transformer import Transformer
> import torch
> 
> 
> batch_size, d_model, n_head = 3, 8, 2
> dim_feedforward = 16
> dropout = 0.0
> source_length, target_length = 5, 5 # 3, 3
> num_encoder_layers, num_decoder_layers = 1, 1
> np.random.seed(123)
> paddle.seed(123)
> torch.manual_seed(123)
> torch.cuda.manual_seed(123)
> 
> with fluid.dygraph.guard(fluid.CUDAPlace(0)):
>     transformer = Transformer(
>         d_model,
>         n_head,
>         num_encoder_layers=num_encoder_layers,
>         num_decoder_layers=num_decoder_layers,
>         dim_feedforward=dim_feedforward,
>         dropout=dropout,
>         attn_dropout=dropout,
>         act_dropout=dropout)
> 
>     transformer_torch = torch.nn.Transformer(
>             d_model=d_model,
>             nhead=n_head,
>             num_encoder_layers=num_encoder_layers,
>             num_decoder_layers=num_decoder_layers,
>             dim_feedforward=dim_feedforward,
>             dropout=dropout)
> 
>     name_param_dict = {}
>     for i, param in enumerate(transformer.named_parameters()):
>         pname = param[0]
>         if 'cross_attn' in pname:
>             pname = pname.replace("cross_attn", "multihead_attn")
>         elif 'q' not in pname and 'k' not in pname and 'v' not in pname:
>             continue
>         param_np = param[1].numpy()
>         pname = pname.replace('q_proj.', 'in_proj_')
>         pname = pname.replace('k_proj.', 'in_proj_')
>         pname = pname.replace('v_proj.', 'in_proj_')
>         if pname not in name_param_dict:
>             name_param_dict[pname] = param_np
>         elif '_weight' in pname:
>             name_param_dict[pname] = np.concatenate((name_param_dict[pname], param_np), axis=1)
>         else:
>             name_param_dict[pname] = np.concatenate((name_param_dict[pname], param_np), axis=0)
> 
>     device = torch.device('cuda:0')
>     for i, param in enumerate(transformer_torch.named_parameters()):
>         pname, pa = param[0], param[1]
>         if 'in_proj' in pname or 'multihead_attn' in pname:
>             param_np = name_param_dict[pname]
>         else:
>             param_np = transformer.state_dict()[pname].numpy()
>         if pname.endswith('weight'):
>             param_np = np.transpose(param_np)
> 
>         param[1].data = torch.from_numpy(param_np)
> 
> 
>     # generate input
>     src = np.random.rand(batch_size, source_length, d_model).astype(
>             "float32")
>     tgt = np.random.rand(batch_size, target_length, d_model).astype(
>             "float32")
>     # run paddle
>     trans_output = transformer(paddle.to_tensor(src),
>                                 paddle.to_tensor(tgt)).numpy()
> 
>     # run torch
>     src_torch = src.transpose(1,0,2)
>     tgt_torch = tgt.transpose(1,0,2)
>     trans_torch = transformer_torch(torch.from_numpy(src_torch), torch.from_numpy(tgt_torch))
>     trans_torch_np = trans_torch.detach().numpy().transpose(1,0,2)
> 
>     np.testing.assert_allclose(trans_output, trans_torch_np, 1e-5, 1e-6)
> ```

非常感谢提供的帮助， 我这边按照你给的思路再自己研究一下 @FrostML

**Comment by thunder95** [comment]
@FrostML 按照你说的[batch size, sequence length, embedding dimension]输入格式， 我去掉了transpose， 然后输出结果就对齐了。非常感谢！
