### ISSUE TITLE
Cannot find available GPU devices, using CPU or other devices now

### ISSUE THREAD

**Issue by roshanthink** [PaddlePaddle/Paddle#33136]
- 版本、环境信息：
    1）PaddlePaddle版本：2.1 GPU
    2）CPU：9700K
    3）GPU：RTX3090
    4）系统环境：WIN10，python3.8，PARL 1.4.3
- 训练信息
    1）单机，单卡

- 问题描述：
- （1）paddle.utils.run_check()，返回成功
- （2）使用PARL 1.4.3 及develop ，训练过程返回信息如下：

> W0526 17:14:31.400776 21148 device_context.cc:404] Please NOTE: device: 0, GPU Compute Capability: 8.6, Driver API Version: 11.2, Runtime API Version: 11.2
> W0526 17:14:31.417778 21148 device_context.cc:422] device: 0, cuDNN Version: 8.1.
> [05-26 17:14:35 MainThread @machine_info.py:90] Cannot find available GPU devices, using CPU or other devices now.

**Comment by T8T9** [comment]
run_check 通过的话，说明gpu应该没什么问题。
您有没有改gpu的环境变量啥的？
@roshanthink @pangyoki

**Comment by roshanthink** [comment]
> run_check 通过的话，说明gpu应该没什么问题。
> 您有没有改gpu的环境变量啥的？
> @roshanthink @pangyoki


您好，问题已经解决。
PARL框架有额外的GPU检测，而系统缺少一个所需的环境变量，导致问题的出现。
