### ISSUE TITLE
paddle如何获取网络层的成员变量

### ISSUE THREAD

**Issue by 978326187** [PaddlePaddle/Paddle#33134]
比如pytorch可以使用fc.in_features获取resnet的全连接层的输入通道数，paddle如何做呢？

**Comment by 978326187** [comment]
目前找到的方法是获得网络层的权重信息，通过权重的shape获得通道数，请问paddle官方有没有实现这种功能呢？就像pytorch中那样使用。

**Comment by T8T9** [comment]
这个in_features就是输入tensor的shape吧，paddle用shape就可以得到。https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/Tensor_cn.html#shape

**Comment by 978326187** [comment]
不是这个意思，定义网络的时候没有tensor啊，只有定义的网络层

**Comment by T8T9** [comment]
哦，那paddle应该还没有这个api

**Comment by 978326187** [comment]
嗯呢，那就只能曲线救国了，希望可以考虑加一下这个功能
