### ISSUE TITLE
是否有离线版本的学习文档可以提供下载

### ISSUE THREAD

**Issue by qiuming-93** [PaddlePaddle/Paddle#33158]
公司网络受限，无法访问飞浆学习教程文档页面
https://www.paddlepaddle.org.cn/documentation/docs/zh/guides/index_cn.html

是否有离线版本的学习文档可以提供下载，类似w3school那种

**Comment by wadefelix** [comment]
您好，此文档来源于 https://github.com/PaddlePaddle/docs 项目，欢迎star关注此文档项目。

另外，还有https://github.com/PaddlePaddle/book 和 https://github.com/PaddlePaddle/tutorials 项目，也欢迎关注。
