### ISSUE TITLE
编译错误：requirements.txt建议加一个wheel

### ISSUE THREAD

**Issue by houj04** [PaddlePaddle/Paddle#33154]
## 环境

我用的是国产化的linux操作系统，比如麒麟和华为的euler，不过这个问题感觉是个通用问题。

## 问题描述

在`python/requirements.txt`里面，缺少`wheel`。

## 如何复现

找个干净的环境（注意`python`和`pip`也要干净），先`pip3 install -r python/requirements.txt`，然后尝试编译，在`cmake`阶段就会挂掉，报下面的信息。

```
-- Could NOT find PY_wheel (missing: PY_WHEEL)
CMake Error at cmake/python_module.cmake:27 (message):
  python module wheel is not found
Call Stack (most recent call first):
  cmake/external/python.cmake:70 (find_python_module)
  cmake/third_party.cmake:231 (include)
  CMakeLists.txt:287 (include)
```

## 供参考的解决方案

在`python/requirements.txt`里面加一行`wheel`。

**Comment by dingjiaweiww** [comment]
请问处理器和操作系统是什么？

**Comment by dingjiaweiww** [comment]
麒麟操作系统源码编译方式请参考：https://www.paddlepaddle.org.cn/documentation/docs/zh/install/compile/arm-compile.html

**Comment by houj04** [comment]
和处理器以及操作系统关系不大。
重点是这个：
在这里 https://github.com/PaddlePaddle/Paddle/blob/develop/python/requirements.txt 没有写需要wheel，但是这里 
https://github.com/PaddlePaddle/Paddle/blob/develop/cmake/external/python.cmake#L70 却检查了wheel。

**Comment by pangyoki** [comment]
> ## 环境
> 
> 我用的是国产化的linux操作系统，比如麒麟和华为的euler，不过这个问题感觉是个通用问题。
> ## 问题描述
> 
> 在`python/requirements.txt`里面，缺少`wheel`。
> ## 如何复现
> 
> 找个干净的环境（注意`python`和`pip`也要干净），先`pip3 install -r python/requirements.txt`，然后尝试编译，在`cmake`阶段就会挂掉，报下面的信息。
> 
> ```
> -- Could NOT find PY_wheel (missing: PY_WHEEL)
> CMake Error at cmake/python_module.cmake:27 (message):
>   python module wheel is not found
> Call Stack (most recent call first):
>   cmake/external/python.cmake:70 (find_python_module)
>   cmake/third_party.cmake:231 (include)
>   CMakeLists.txt:287 (include)
> ```
> 
> ## 供参考的解决方案
> 
> 在`python/requirements.txt`里面加一行`wheel`。

感谢反馈。复现了这个问题，如果把环境中的wheel卸载，确实会出现上面编译出错的情况。感觉解决方案可行。

**Comment by pangyoki** [comment]
`python/requirements.txt`里的软件，是会在编译完paddle后，安装whl包时检查版本并安装。
如果编译的环境里没有`wheel`，即使在`python/requirements.txt`中添加`wheel`，编译仍然会报错。
建议编译出错时，直接pip安装`wheel`。

**Comment by pangyoki** [comment]
感谢反馈。复现了这个问题，会在`python/requirements.txt`里添加`wheel`。

**Comment by wadefelix** [comment]
> 感谢反馈。复现了这个问题，会在`python/requirements.txt`里添加`wheel`。

貌似还是与操作系统或python什么组件有关系。我ubuntu20上不需要单独安装wheel，但在ubuntu18上需要单独安装下wheel包，另外还有setuptools。
