### ISSUE TITLE
 C++ demo预估启动报错出core：Device id must be less than GPU count, but received id is: 0. GPU count is: 0

### ISSUE THREAD

**Issue by yangge-ai** [PaddlePaddle/Paddle#33165]
为使您的问题得到快速解决，在建立Issue前，请您先通过如下方式搜索是否有相似问题:【搜索issue关键字】【使用labels筛选】【官方文档】

如果您没有查询到相似问题，为快速解决您的提问，建立issue时请提供如下细节信息：
- 标题：简洁、精准描述您的问题，例如“最新预测库的API文档在哪儿 ”
- 版本、环境信息：
    1）PaddlePaddle版本：公司内部baidu/lib/paddlepaddle  v2.0.1-gcc82-cuda10.1-cudnn7.6-trt6.0-all_PD_BL
    2）GPU：P4、cuda-10.1和cudnn-7.6版本号
    4）系统环境：公司centos 6.3 内核3.10

-预测信息
    1）C++预测：v2.0.1-gcc82-cuda10.1-cudnn7.6-trt6.0-all_PD_BL
GIT COMMIT ID: ffa88c31c2da5090c6f70e8e9b523356d7cd5e7f
WITH_MKL: ON
WITH_MKLDNN: OFF
WITH_GPU: ON
CUDA version: 10.1
CUDNN version: v7.6
CXX compiler version: 8.2.0
WITH_TENSORRT: ON
TensorRT version: v6
    2）CMake包含路径的完整命令：
cmake .. -DPADDLE_LIB=${LIB_DIR} \
  -DWITH_MKL=${WITH_MKL} \
  -DDEMO_NAME=${DEMO_NAME} \
  -DWITH_GPU=${WITH_GPU} \
  -DWITH_STATIC_LIB=OFF \
  -DUSE_TENSORRT=${USE_TENSORRT} \
  -DCUDNN_LIB=${CUDNN_LIB} \
  -DCUDA_LIB=${CUDA_LIB} \
  -DTENSORRT_ROOT=${TENSORRT_ROOT}
    3）API信息
![image](https://user-images.githubusercontent.com/84904895/119805461-d85a1c00-bf13-11eb-830c-545929184a66.png)
启动执行到EnableUseGpu就报错。
    4）预测库来源：icode
- 复现信息：
编译后启动报错
- 问题描述：
 terminate called after throwing an instance of 'paddle::platform::EnforceNotMet'
  what():

--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
0   paddle_infer::CreatePredictor(paddle::AnalysisConfig const&)
1   paddle_infer::Predictor::Predictor(paddle::AnalysisConfig const&)
2   std::unique_ptr<paddle::PaddlePredictor, std::default_delete<paddle::PaddlePredictor> > paddle::CreatePaddlePredictor<paddle::AnalysisConfig, (paddle::PaddleEngineKind)2>(paddle::AnalysisConfig const&)
3   paddle::AnalysisConfig::fraction_of_gpu_memory_for_pool() const
4   paddle::platform::SetDeviceId(int)
5   paddle::platform::EnforceNotMet::EnforceNotMet(paddle::platform::ErrorSummary const&, char const*, int)
6   paddle::platform::GetCurrentTraceBackString()

----------------------
Error Message Summary:
----------------------
InvalidArgumentError: Device id must be less than GPU count, but received id is: 0. GPU count is: 0.
  [Hint: Expected id < GetCUDADeviceCount(), but received id:0 >= GetCUDADeviceCount():0.] (at /home/ferry2/ONLINE_SERVICE/other/ferry/task_workspace/1c7b59476caed5807596a54744517a0e/baidu/lib/paddlepaddle/Paddle/paddle/fluid/platform/gpu_info.cc:228)

run.sh: line 21: 12498 Aborted                 (core dumped) ./build/ernie_test --model_file=./new_quant_post_model_kl/__model__ --params_file=./new_quant_post_model_kl/__params__

Thank you for contributing to PaddlePaddle.
Before submitting the issue, you could search issue in the github in case that th
If there is no solution,please make sure that this is an inference issue including the following details :
**System information**
-PaddlePaddle version （eg.1.1）or CommitID
-CPU: including CPUMKL/OpenBlas/MKLDNN version
-GPU: including CUDA/CUDNN version
-OS Platform (eg.Mac OS 10.14)
-Python version
-Cmake orders
-C++version.txt
-API information
Note: You can get most of the information by running [summary_env.py](https://github.com/PaddlePaddle/Paddle/blob/develop/tools/summary_env.py). 
**To Reproduce**
Steps to reproduce the behavior
**Describe your current behavior**
**Code to reproduce the issue**
**Other info / logs**

**Comment by juncaipeng** [comment]
![image](https://user-images.githubusercontent.com/52520497/119817433-8f5c9480-bf20-11eb-886f-abc8add0c512.png)

**Comment by yangge-ai** [comment]
解决了，多谢！
