### ISSUE TITLE
bias 如何指定命名

### ISSUE THREAD

**Issue by paulpaul91** [PaddlePaddle/Paddle#33175]
原pytroch 接口
self.q_bias = nn.Parameter(torch.zeros(1, 1, self.all_head_size)) 
self.v_bias = nn.Parameter(torch.zeros(1, 1, self.all_head_size))

paddle 中实现
v_bias = fluid.layers.create_parameter(shape=[d_key * n_head], dtype="float32", name=name + "_value_fc.b_0", attr=fluid.ParamAttr(name=name + "_value_fc.b_0", initializer=fluid.initializer.Constant(0.0)), is_bias=False)
不知为何这个变量的名字未符合预期，使用的系统默认名字，fc_21.b_0  不是我需要的name + "_value_fc.b_0"

**Comment by yinhaofeng** [comment]
create_parameter这个op本身就有default_initializer参数，可以直接将这个参数设置为default_initializer=paddle.nn.initializer.Constant(value=0)
op相关可以参考：https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/static/create_parameter_cn.html#create-parameter
