### ISSUE TITLE
编译，可否提供一版本直接编译时下载国内镜像版的3方库，windows vs2019 vs2017？

### ISSUE THREAD

**Issue by xinsuinizhuan** [PaddlePaddle/Paddle#33178]
欢迎您对PaddlePaddle提出建议，非常感谢您对PaddlePaddle的贡献！
在留下您的建议时，辛苦您同步提供如下信息：
- 版本、环境信息
1）PaddlePaddle版本：请提供您的PaddlePaddle版本号，例如1.1
2）CPU/GPU：您是否使用GPU进行训练，如是，请提供您的CUDA和cuDNN版本号
3）系统环境：请您描述系统类型、版本，例如Mac OS 10.14
注：您可以通过执行[summary_env.py](https://github.com/PaddlePaddle/Paddle/blob/develop/tools/summary_env.py)获取以上信息。
- 复现信息：如为报错，请给出复现环境、复现步骤
- 建议描述：请您详细描述，您认为需优化的功能

Thank you for contributing to PaddlePaddle.
Before submitting the issue, you could search issue in the github in case that there was a similar issue submitted or resolved before.
Please make sure that this is a feature request. 
**System information**
-PaddlePaddle version （eg.1.1）or CommitID
-CPU: including CPUMKL/OpenBlas/MKLDNN version
-GPU: including CUDA/CUDNN version
-OS Platform (eg.Mac OS 10.14)
Note: You can get most of the information by running [summary_env.py](https://github.com/PaddlePaddle/Paddle/blob/develop/tools/summary_env.py). 
**To Reproduce**
Steps to reproduce the behavior
**Describe the feature and the current behavior/state.**
**Any Other info.**

**Comment by littletomatodonkey** [comment]
你好，感谢你的建议，我们记录下哈，有些库确实下载速度很慢

**Comment by xinsuinizhuan** [comment]
> 
> 
> 你好，感谢你的建议，我们记录下哈，有些库确实下载速度很慢

是非常的慢。尝试过很多很多次，都没下载成功过。更更换成了码云的，也不行。建议是可以提供一个第三方库的镜像，或者我们手动下载下来后，放到某个目录下面，也可以编译。

**Comment by littletomatodonkey** [comment]
嗯嗯 暂时的解决方案是需要什么库的话，就手动下载并解压到到thirdpqrty目录下，第三方镜像的问题我们记录下～

**Comment by wadefelix** [comment]
第三方库也可以建立本地mirror镜像，不在paddle目录内方便随时清理paddle build目录。然后修改相应库的地址为本地地址即可。

比如可以把所有第三方库提前clone到 `/path/to/gitmirror/` 目录下。如果您有nas之类的服务器设备，在其上建立git仓库mirror是非常合适的，参考 https://github.com/wadefelix/Paddle/commit/b4c03bbb1450424a069813511639686b6b36fa67

**Comment by xinsuinizhuan** [comment]
能否把第三方库给出类似PaddleX里面的链接这样的：
![图片](https://user-images.githubusercontent.com/40679769/148144259-d2721b9c-8fa4-4f41-9fd8-0aac1e60d0be.png)
这样，我使用git下载的时候，就都下载下来了，翻墙即可。但是现在的模式，翻墙什么的，统统不管用，手动下载下下来，不知道往哪里放，然后版本也不匹配。然后，官方提供的库，又不全，自己编译又编译不了，实在没法用。我要使用tesnorrt8，但是目前官方提供的C++ windows库，最高是cuda11.0,匹配的是trt7,cudnn8.0.

**Comment by wadefelix** [comment]
> 能否把第三方库给出类似PaddleX里面的链接这样的： ![图片](https://user-images.githubusercontent.com/40679769/148144259-d2721b9c-8fa4-4f41-9fd8-0aac1e60d0be.png) 这样，我使用git下载的时候，就都下载下来了，翻墙即可。但是现在的模式，翻墙什么的，统统不管用，手动下载下下来，不知道往哪里放，然后版本也不匹配。然后，官方提供的库，又不全，自己编译又编译不了，实在没法用。我要使用tesnorrt8，但是目前官方提供的C++ windows库，最高是cuda11.0,匹配的是trt7,cudnn8.0.

`git submodule` 对新手其实不友好，克隆和更新子模块时需要使用`git submodule` 相关命令，一般新手可能不熟悉这些git指令。较好的方法就是使用便捷的方法能指定这些依赖库的mirror仓库地址，若能自行本地建mirror则更佳。

**Comment by xinsuinizhuan** [comment]
22>fatal: unable to access 'https://github.com/protocolbuffers/protobuf.git/': Failed to connect to github.com port 443: Timed out
22>Cloning into 'extern_protobuf'...
23>fatal: unable to access 'https://github.com/google/glog.git/': Failed to connect to github.com port 443: Timed out
23>Cloning into 'extern_glog'...
22>fatal: unable to access 'https://github.com/protocolbuffers/protobuf.git/': Failed to connect to github.com port 443: Timed out
22>Cloning into 'extern_protobuf'...
23>fatal: unable to access 'https://github.com/google/glog.git/': Failed to connect to github.com port 443: Timed out
23>Cloning into 'extern_glog'...
22>fatal: unable to access 'https://github.com/protocolbuffers/protobuf.git/': Failed to connect to github.com port 443: Timed out

第三方库，一直下载不下来，强烈建议使用这种链接方式：
![图片](https://user-images.githubusercontent.com/40679769/152731903-0b6a47b4-a1d5-4a20-92e9-94b929ad801e.png)

因为很多库涉及到版本问题，我们自己下载的版本不匹配，这种链接方式，很方便。

**Comment by xinsuinizhuan** [comment]
就是我这些库都手动下载下载了，怎么放到对应目录下？
![图片](https://user-images.githubusercontent.com/40679769/152733488-b8882f28-73cf-4132-91a3-fe2370228c9c.png)

**Comment by wadefelix** [comment]
> 就是我这些库都手动下载下载了，怎么放到对应目录下？ ![图片](https://user-images.githubusercontent.com/40679769/152733488-b8882f28-73cf-4132-91a3-fe2370228c9c.png)

参考我的这个方法 https://github.com/wadefelix/Paddle/commit/12175221b29dee64e92b562340908e2896054214

我的地址是 在自己的nas上建立了这些仓库的mirror的，自动定期同步的。 
对于只在自己的一台电脑上工作的， 你可以把仓库克隆到另外一个文件夹，git url是可以写本地文件系统路径的。 比如你把pybind11给克隆到了 `/Project/github.com/pybind11` 目录了，那么在这个cmake文件里就把地址改为`/Project/github.com/pybind11`即可，git会从那个目录再clone到这个cmake系统指定的目录。
这样只用改地址，而不需要更改别的代码脚本。

**Comment by xinsuinizhuan** [comment]
> > 就是我这些库都手动下载下载了，怎么放到对应目录下？ ![图片](https://user-images.githubusercontent.com/40679769/152733488-b8882f28-73cf-4132-91a3-fe2370228c9c.png)
> 
> 参考我的这个方法 [wadefelix@1217522](https://github.com/wadefelix/Paddle/commit/12175221b29dee64e92b562340908e2896054214)
> 
> 我的地址是 在自己的nas上建立了这些仓库的mirror的，自动定期同步的。 对于只在自己的一台电脑上工作的， 你可以把仓库克隆到另外一个文件夹，git url是可以写本地文件系统路径的。 比如你把pybind11给克隆到了 `/Project/github.com/pybind11` 目录了，那么在这个cmake文件里就把地址改为`/Project/github.com/pybind11`即可，git会从那个目录再clone到这个cmake系统指定的目录。 这样只用改地址，而不需要更改别的代码脚本。

![图片](https://user-images.githubusercontent.com/40679769/152928487-0c674a42-25fb-4808-b440-f49822099382.png)
我都指定了，它还是去下载。

**Comment by wadefelix** [comment]
> > > 就是我这些库都手动下载下载了，怎么放到对应目录下？ ![图片](https://user-images.githubusercontent.com/40679769/152733488-b8882f28-73cf-4132-91a3-fe2370228c9c.png)
> > 
> > 
> > 参考我的这个方法 [wadefelix@1217522](https://github.com/wadefelix/Paddle/commit/12175221b29dee64e92b562340908e2896054214)
> > 我的地址是 在自己的nas上建立了这些仓库的mirror的，自动定期同步的。 对于只在自己的一台电脑上工作的， 你可以把仓库克隆到另外一个文件夹，git url是可以写本地文件系统路径的。 比如你把pybind11给克隆到了 `/Project/github.com/pybind11` 目录了，那么在这个cmake文件里就把地址改为`/Project/github.com/pybind11`即可，git会从那个目录再clone到这个cmake系统指定的目录。 这样只用改地址，而不需要更改别的代码脚本。
> 
> ![图片](https://user-images.githubusercontent.com/40679769/152928487-0c674a42-25fb-4808-b440-f49822099382.png) 我都指定了，它还是去下载。

做个cmake clean呢
