### ISSUE TITLE
paddle 2.1 在windows10 Anaconda3-2021.05的环境下,一执行model.fit就退出

### ISSUE THREAD

**Issue by KwpGitHub** [PaddlePaddle/Paddle#33177]
paddle 2.1 在windows10 Anaconda3-2021.05的环境下,一执行model.fit就退出，cuda 11.2 cudnn 8.1, vs code 和jupyterlab都一样
试了一下 cuda10.2 的环境也一样，
是什么情况呢？
[I 2021-05-27 23:53:58.281 ServerApp] AsyncIOLoopKernelRestarter: restarting kernel (1/5), keep random ports

无论是2080super的机子，还是3090的机子都出现同样的问题，
是在win10环境下有有什么要配置的，还是什么其实原因，不然你们这bug也太离谱了呀！

看了一个你们2.0和2.1的介绍，本来感觉API之类的好像是够用了，结果........................................

**Comment by yinhaofeng** [comment]
能给一下代码吗？以及具体的报错。目前给的信息上看不出来具体的问题

**Comment by KwpGitHub** [comment]
> 能给一下代码吗？以及具体的报错。目前给的信息上看不出来具体的问题

代码？一就完全你们文档里的《10分钟快速上手飞桨（PaddlePaddle）》
https://www.paddlepaddle.org.cn/documentation/docs/zh/guides/02_paddle2.0_develop/01_quick_start_cn.html

错误提示也就是下面一句 ，然后jupyterlab的kernel就停下来了呀！
[I 2021-05-27 23:53:58.281 ServerApp] AsyncIOLoopKernelRestarter: restarting kernel (1/5), keep random ports

**Comment by LielinJiang** [comment]
你可以把代码放到.py文件里运行下，看下报错信息。或者看jupyter 运行的终端里面的信息也行

**Comment by KwpGitHub** [comment]
> 你可以把代码放到.py文件里运行下，看下报错信息。或者看jupyter 运行的终端里面的信息也行

因为你们前面的paddle不能用所以就卸载了，还是继续用tensorflow了！本来看了你们的套件和介绍，感觉paddle 2.1在工业上用应该在目前几个AI框架里是最优的选择，结果几个电脑几个不同的配置运行你们自己教程示例都出错，所以感觉还是比较遗憾的。今天把手上的项目弄完才有空重新装一下paddle 2.1给重现一下你们错误信息,不过现在paddle是能正常运行了，现在配置的2台电脑正常运行，你们应该更新过文件吧？不过短期内还是不敢用在自己项目中了，因为对你们的稳定性还是有疑虑的了
