### ISSUE TITLE
Paddle2.0 SetModel出现错误

### ISSUE THREAD

**Issue by qingchunnianshao** [PaddlePaddle/Paddle#33187]
目前使用Win7系统CUDA10.2，下载的预测库是：
cuda10.2_cudnn7_avx_mkl_trt7
由于下载预测库SetModel出现下图1std::bad_alloc错误，自己在电脑上重新编译了预测库但是出现std::length_error错误
但是两个库SetModelBuffer都是能够加载成功的。请问是什么原因？使用的VS2019，VS2015等都测试了都会有这个问题，请问该问题如何解决

<img width="3044" alt="WeChata9034ac32678109cb7c7d396a5b52b09" src="https://user-images.githubusercontent.com/16200499/119944789-4875aa00-bfc7-11eb-906e-9c76d86e4b07.png">
<img width="3026" alt="WeChat3b00c58841e758c737664e35df0df18a" src="https://user-images.githubusercontent.com/16200499/119944907-6a6f2c80-bfc7-11eb-9e1b-2cab9a534494.png">

**Comment by littletomatodonkey** [comment]
看使用的是分类模型，要不试下这个repo里的cpp预测部署呢？基于vs2019的话，cpu/gpu/trt应该都是可以的，可以直接下载官网的预测库哈

https://github.com/PaddlePaddle/PaddleClas/blob/release%2F2.1/deploy/cpp_infer/readme.md

**Comment by qingchunnianshao** [comment]
> 看使用的是分类模型，要不试下这个repo里的cpp预测部署呢？基于vs2019的话，cpu/gpu/trt应该都是可以的，可以直接下载官网的预测库哈
> 
> https://github.com/PaddlePaddle/PaddleClas/blob/release%2F2.1/deploy/cpp_infer/readme.md

想问下创建工程的时候必须使用你们 这种make 方式吗？我上面的工程是自己创建工程然后配置的需要的链接库的，这样按理说也不应该有问题吧

**Comment by littletomatodonkey** [comment]
不是必须的，只是建议，不过建议先跑下demo 排除环境问题

**Comment by qingchunnianshao** [comment]
> 不是必须的，只是建议，不过建议先跑下demo 排除环境问题

OK，我先尝试下谢谢

**Comment by qingchunnianshao** [comment]
> 不是必须的，只是建议，不过建议先跑下demo 排除环境问题

<img width="1980" alt="WeChat87ed421fe38585dad76442cfaee9c872" src="https://user-images.githubusercontent.com/16200499/119976525-c6e34380-bfe9-11eb-9b3b-aee98bfcf33c.png">
有点疑惑了，跑这个demo是可以成功的

**Comment by littletomatodonkey** [comment]
嗯嗯，那可能是你导入paddle的时候有点问题，可以参考这个demo中的链接方式修改一下哈

**Comment by WillisXue** [comment]
![image](https://user-images.githubusercontent.com/9125768/134275056-0aeda76b-b04b-46fa-814c-344741b8d8cd.png)debug模式下把基本运行时检查改为默认值就不会报错了

**Comment by LeeRainFish** [comment]
https://blog.csdn.net/qq_41961619/article/details/113791429 这篇博客里说“此程序仅支持64位Release版本”，
我在Qt里移植使用Debug模式版本，切换到release版本后就没问题了
