### ISSUE TITLE
静态图： embedding.sparse=True会报错，改成False就能跑

### ISSUE THREAD

**Issue by zhujindi** [PaddlePaddle/Paddle#33182]
动态图 embedding.sparse=True可以跑， 使用paddle.jit.to_static转静态图就会报错，但改成 embedding.sparse=False就能正常跑 

环境：
PaddlePaddle版本：2.1
CPU  单机训练
系统环境: win10 python3.8

错误信息：
ValueError: (InvalidArgument) The output variable SparseFeatFactors@GRAD get from RunProgram(Grad)Op's internal scope holds wrong type. Expect type is LoDTensor, but receive type is class paddle::framework::SelectedRows.
  [Hint: Expected src_var.IsType<LoDTensor>() == true, but received src_var.IsType<LoDTensor>():0 != true:1.] (at C:\home\workspace\Paddle_release\paddle/fluid/operators/run_program_op.h:82)

**Comment by littletomatodonkey** [comment]
你好，能提供一个可以复现的代码片吗

**Comment by zhujindi** [comment]
[import math
import paddle
import paddle.nn as nn
import paddle.nn.functional as F
from paddle.static import InputSpec


class DNNLayer(nn.Layer):
    def __init__(self):
        super(DNNLayer, self).__init__()
        self.sparse_feature_number = 1000
        self.sparse_feature_dim = 32
        self.fc_sizes = [512, 256, 128, 32]

        self.embedding = paddle.nn.Embedding(
            self.sparse_feature_number,
            self.sparse_feature_dim,
            padding_idx=0,
            sparse=True,
            weight_attr=paddle.ParamAttr(
                name="SparseFeatFactors",
                initializer=paddle.nn.initializer.Uniform()))

        user_sizes = [1 * 32] + self.fc_sizes
        acts = ["relu" for _ in range(len(self.fc_sizes))]
        self._user_layers = []
        for i in range(len(self.fc_sizes)):
            linear = paddle.nn.Linear(
                in_features=user_sizes[i],
                out_features=user_sizes[i + 1],
                weight_attr=paddle.ParamAttr(
                    initializer=paddle.nn.initializer.Normal(
                        std=1.0 / math.sqrt(user_sizes[i]))))
            self.add_sublayer('linear_user_%d' % i, linear)
            self._user_layers.append(linear)
            if acts[i] == 'relu':
                act = paddle.nn.ReLU()
                self.add_sublayer('user_act_%d' % i, act)
                self._user_layers.append(act)

    @paddle.jit.to_static(input_spec=[
        InputSpec(shape=[None, 1], name='user_id_tensor', dtype='int64')
    ])
    def forward(self,user_id_tensor):
        user_sparse_embed_seq = []
        emb = self.embedding(user_id_tensor)
        emb = paddle.reshape(emb, shape=[-1, self.sparse_feature_dim])
        user_sparse_embed_seq.append(emb)

        user_features = paddle.concat(user_sparse_embed_seq, axis=1)

        for n_layer in self._user_layers:
            user_features = n_layer(user_features)

        sim = F.cosine_similarity(
            user_features, user_features, axis=1).reshape([-1, 1])
        predict = paddle.scale(sim, scale=5)
        return predict


# define loss function by predicts and label
def create_loss(predict, label_input):
    cost = F.square_error_cost(
        predict, paddle.cast(
            x=label_input, dtype='float32'))
    avg_cost = paddle.mean(cost)
    return avg_cost


# define optimizer
def create_optimizer(model):
    lr = 0.001
    optimizer = paddle.optimizer.Adam(
        learning_rate=lr, parameters=model.parameters())
    return optimizer


def create_metrics():
    metrics_list_name = []
    metrics_list = []
    return metrics_list, metrics_list_name


def train_forward(net2, metrics_list):
    id_tensor = paddle.to_tensor([[1]])
    label_input = paddle.to_tensor([[5]])
    predict = net2.forward(id_tensor)
    loss = create_loss(predict, label_input)
    # update metrics
    print_dict = {"loss": loss}
    return loss, metrics_list, print_dict


def main():
    net2 = DNNLayer()
    op = create_optimizer(net2);
    net2.train();

    op.clear_grad()
    loss, metric_list, tensor_print_dict = train_forward(net2, create_metrics())
    loss.backward()
    op.step()

    paddle.jit.save(net2, "inference2/emall")


if __name__ == '__main__':
    main()

**Comment by zhujindi** [comment]
`import math
import paddle
import paddle.nn as nn
import paddle.nn.functional as F
from paddle.static import InputSpec


class DNNLayer(nn.Layer):
    def __init__(self):
        super(DNNLayer, self).__init__()
        self.sparse_feature_number = 1000
        self.sparse_feature_dim = 32
        self.fc_sizes = [512, 256, 128, 32]

        self.embedding = paddle.nn.Embedding(
            self.sparse_feature_number,
            self.sparse_feature_dim,
            padding_idx=0,
            sparse=True,
            weight_attr=paddle.ParamAttr(
                name="SparseFeatFactors",
                initializer=paddle.nn.initializer.Uniform()))

        user_sizes = [1 * 32] + self.fc_sizes
        acts = ["relu" for _ in range(len(self.fc_sizes))]
        self._user_layers = []
        for i in range(len(self.fc_sizes)):
            linear = paddle.nn.Linear(
                in_features=user_sizes[i],
                out_features=user_sizes[i + 1],
                weight_attr=paddle.ParamAttr(
                    initializer=paddle.nn.initializer.Normal(
                        std=1.0 / math.sqrt(user_sizes[i]))))
            self.add_sublayer('linear_user_%d' % i, linear)
            self._user_layers.append(linear)
            if acts[i] == 'relu':
                act = paddle.nn.ReLU()
                self.add_sublayer('user_act_%d' % i, act)
                self._user_layers.append(act)

    @paddle.jit.to_static(input_spec=[
        InputSpec(shape=[None, 1], name='user_id_tensor', dtype='int64')
    ])
    def forward(self,user_id_tensor):
        user_sparse_embed_seq = []
        emb = self.embedding(user_id_tensor)
        emb = paddle.reshape(emb, shape=[-1, self.sparse_feature_dim])
        user_sparse_embed_seq.append(emb)

        user_features = paddle.concat(user_sparse_embed_seq, axis=1)

        for n_layer in self._user_layers:
            user_features = n_layer(user_features)

        sim = F.cosine_similarity(
            user_features, user_features, axis=1).reshape([-1, 1])
        predict = paddle.scale(sim, scale=5)
        return predict


# define loss function by predicts and label
def create_loss(predict, label_input):
    cost = F.square_error_cost(
        predict, paddle.cast(
            x=label_input, dtype='float32'))
    avg_cost = paddle.mean(cost)
    return avg_cost


# define optimizer
def create_optimizer(model):
    lr = 0.001
    optimizer = paddle.optimizer.Adam(
        learning_rate=lr, parameters=model.parameters())
    return optimizer


def create_metrics():
    metrics_list_name = []
    metrics_list = []
    return metrics_list, metrics_list_name


def train_forward(net2, metrics_list):
    id_tensor = paddle.to_tensor([[1]])
    label_input = paddle.to_tensor([[5]])
    predict = net2.forward(id_tensor)
    loss = create_loss(predict, label_input)
    # update metrics
    print_dict = {"loss": loss}
    return loss, metrics_list, print_dict


def main():
    net2 = DNNLayer()
    op = create_optimizer(net2);
    net2.train();

    op.clear_grad()
    loss, metric_list, tensor_print_dict = train_forward(net2, create_metrics())
    loss.backward()
    op.step()

    paddle.jit.save(net2, "inference2/emall")


if __name__ == '__main__':
    main()
`

**Comment by littletomatodonkey** [comment]
这块要不上传一个文件？我这边拷贝下来格式都是乱的~

**Comment by zhujindi** [comment]
[net2.zip](https://github.com/PaddlePaddle/Paddle/files/6565839/net2.zip)

**Comment by Aurelius84** [comment]
如果只是想导出预测模型的话，@zhujindi 可以将模型的 forward 函数上的 to_static代码移动到 `jit.save` 那里：
```python

# to_static()       <---- 此处注释掉
def forward(self, user_id_tensor):
    # ....(略)
   

op.step()

paddle.jit.save(net2, input_spec=[InputSpec(shape=[None, 1], name='user_id_tensor', dtype='int64')], "inference2/emall")
```

尝试下是否可以解决你的问题。

另外，关于上面的训练报错，看起来是 `run_program_op` 不支持 SelectedRows 类型，这个我们会确认下并尽快支持。

**Comment by zhujindi** [comment]
这种写法可以工作，我先这样用，谢谢
