### ISSUE TITLE
GPU，EnforceNotMet崩溃问题，麻烦给解决一下呢，一直没法使用gpu做推理，很严重的问题，没法gpu部署

### ISSUE THREAD

**Issue by xinsuinizhuan** [PaddlePaddle/Paddle#33193]
关联这个：https://github.com/PaddlePaddle/Paddle/issues/32602

**Comment by littletomatodonkey** [comment]
要不先试一下paddle的python推理呢？先确认下是否为环境问题

**Comment by xinsuinizhuan** [comment]
> 
> 
> 要不先试一下paddle的python推理呢？先确认下是否为环境问题

这个问题，https://github.com/PaddlePaddle/Paddle/issues/33171这个也是同样这个函数崩溃了，我觉得跟环境有关系，但是也是共性问题，应该还是库的问题。我就全新的一台机器，在我本机上编译好的C++推理，下载的官方的预测库，gpu的推理，放过去，就崩溃，cuda10.1,cuda10.0,cuda10.2都试过，都不行，又另外换了一台机器，依然是这个崩溃。应该是库的问题。

**Comment by xinsuinizhuan** [comment]
![图片](https://user-images.githubusercontent.com/40679769/120251623-b1ee0500-c2b4-11eb-943f-c6b16f274490.png)
应该是内存访问导致的问题，是库的问题，您看看，百度一下，导出都是这个问题：
0x00007FFA0CAB62D1 (paddle_inference.dll)处(位于 xxx.exe 中)引发的异常: 0xC0000005: 读取位置 0x0000000000000000 时发生访问冲突。
https://www.cnblogs.com/dzqiu/p/9518190.html
https://blog.csdn.net/PaddlePaddle/article/details/86739880
PaddlePaddle运行时出现EnforceNotMet: Enforce failed错误:

问题解决
PaddlePaddle的label要从0开始递增。

def getdata():
def reader():
for i in range(len(data_y)):
yield np.array(data_X[i]).astype('float32'), np.array(data_y[i]- 3).astype('int64')
return reader
这是在哪里改？

**Comment by xinsuinizhuan** [comment]
麻烦帮忙解决一下，很着急。现场部署，没法用。

**Comment by leihuan925** [comment]
> 您好，我们已经收到了您的问题，会安排技术人员尽快解答您的问题，请耐心等待。请您再次检查是否提供了清晰的问题描述、复现代码、环境&版本、报错信息等。同时，您也可以通过查看[官网API文档](https://www.paddlepaddle.org.cn/documentation/docs/zh/api_cn/index_cn.html)、[常见问题](https://www.paddlepaddle.org.cn/documentation/docs/zh/faq/index_cn.html)、[历史Issue](https://github.com/PaddlePaddle/Paddle/issues)、[AI社区](https://ai.baidu.com/forum/topic/list/168)来寻求解答。祝您生活愉快～
> 
> Hi! We've received your issue and please be patient to get responded. We will arrange technicians to answer your questions as soon as possible. Please make sure that you have posted enough message to demo your request. You may also check out the [API](https://www.paddlepaddle.org.cn/documentation/docs/zh/api_cn/index_cn.html)，[FAQ](https://www.paddlepaddle.org.cn/documentation/docs/zh/faq/index_cn.html)，[Github Issue](https://github.com/PaddlePaddle/Paddle/issues) and [AI community](https://ai.baidu.com/forum/topic/list/168) to get the answer.Have a nice day!

请问这个问题解决了吗？我同样遇到这个问题了，谢谢啦！
