### ISSUE TITLE
[论文复现] 请问怎么基于参数名称设定学习率

### ISSUE THREAD

**Issue by thunder95** [PaddlePaddle/Paddle#33190]
torch代码是这样的

```
    param_dicts = [
        {
            "params":
                [p for n, p in model_without_ddp.named_parameters()
                 if not match_name_keywords(n, args.lr_backbone_names) and not match_name_keywords(n, args.lr_linear_proj_names) and p.requires_grad],
            "lr": args.lr,
        },
        {
            "params": [p for n, p in model_without_ddp.named_parameters() if match_name_keywords(n, args.lr_backbone_names) and p.requires_grad],
            "lr": args.lr_backbone,
        },
        {
            "params": [p for n, p in model_without_ddp.named_parameters() if match_name_keywords(n, args.lr_linear_proj_names) and p.requires_grad],
            "lr": args.lr * args.lr_linear_proj_mult,
        }
    ]

optimizer = torch.optim.AdamW(param_dicts, lr=args.lr,
                                      weight_decay=args.weight_decay)

```
貌似paddle不支持这样的写法， 可以怎么改呢？

**Comment by littletomatodonkey** [comment]
创建ParamAttr的时候，可以指定`learning_rate `的参数

https://github.com/PaddlePaddle/PaddleClas/blob/c471929c18969273936c8b8893e1a4d0645fed7b/ppcls/modeling/architectures/resnet_vd.py#L58

**Comment by thunder95** [comment]
> 创建ParamAttr的时候，可以指定`learning_rate `的参数
> 
> https://github.com/PaddlePaddle/PaddleClas/blob/c471929c18969273936c8b8893e1a4d0645fed7b/ppcls/modeling/architectures/resnet_vd.py#L58

@littletomatodonkey 这样设置有点麻烦， 能不能对已创建好的网络结构直接循环遍历批量设置？像设置属性那样？

**Comment by thunder95** [comment]
@littletomatodonkey 另外， 在网络层里设置了学习率， 会跟外面optimizer设置的学习率冲突吗？

**Comment by littletomatodonkey** [comment]
1. 如果批量修改的话，需要在初始化对所有的Conv2D，Linear等sublayer做create_parameter的操作，在这里面初始化lr
2. 这里面设置的是相对学习率，最终真实的学习率是全局的学习率与该值相乘
