### ISSUE TITLE
notebook中无法屏蔽报警

### ISSUE THREAD

**Issue by wuxianshen** [PaddlePaddle/Paddle#33204]
使用如下代码无法在notebook中屏蔽报警：
import warnings
warnings.filterwarnings('ignore', category=Warning)

持续输出numpy的Deprecation报警：
![image](https://user-images.githubusercontent.com/21985528/120090872-880fd380-c138-11eb-9510-7d68294dfad3.png)

**Comment by tink2123** [comment]
可以用这个方法尝试屏蔽所有的warning输出
```
import warnings
 
warnings.filterwarnings('ignore')
```

**Comment by wuxianshen** [comment]
您好，确实加了，python文件、notebook命令行中都加了：
![image](https://user-images.githubusercontent.com/21985528/120091354-fd7da300-c13c-11eb-856f-96bb77b434d5.png)

![image](https://user-images.githubusercontent.com/21985528/120091362-053d4780-c13d-11eb-921a-3890a7f94824.png)


项目地址：https://aistudio.baidu.com/aistudio/projectdetail/2012026

**Comment by tink2123** [comment]
在终端里运行的时候可以屏蔽掉吗？

**Comment by tink2123** [comment]
在dataloader文件中添加 ignore 可以屏蔽掉：
vim /opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dataloader/dataloader_iter.py
![image](https://user-images.githubusercontent.com/31891223/120098645-b2c65000-c169-11eb-9c1c-4f8cb317c3f2.png)
 
![image](https://user-images.githubusercontent.com/31891223/120098618-84487500-c169-11eb-9ede-54f68549bfb0.png)

**Comment by wuxianshen** [comment]
好的，确实在这里修改后就不会报错了，谢谢！
