### ISSUE TITLE
DataLoader多进程加载数据报错

### ISSUE THREAD

**Issue by wuxianshen** [PaddlePaddle/Paddle#33205]
设置DataLoader的num_workers=4，执行训练过程，退出时报错：

![image](https://user-images.githubusercontent.com/21985528/120091434-aa582000-c13d-11eb-9164-9e41dc57ea8b.png)

如果训练epoch数较少（例如epoches=2），退出时不报错，epoches较多时报错；

项目地址：
https://aistudio.baidu.com/aistudio/projectdetail/2012026

**Comment by tink2123** [comment]
建议先把num_worker设置成0，看下具体报错信息。




发自网易邮箱大师
在2021年05月30日 11:55，wuxianshen 写道：

设置DataLoader的num_workers=4，执行训练过程，退出时报错：

如果训练epoch数较少（例如epoches=2），退出时不报错，epoches较多时报错；

项目地址：
https://aistudio.baidu.com/aistudio/projectdetail/2012026

**Comment by wuxianshen** [comment]
您好，现在问题是num_worker=0，不出现这个问题，能运行完成...
但是num_worker=0太慢了...
num_worker=4的时候就会出现！

**Comment by tink2123** [comment]
在aistudio中，因为共享内存小的原因，暂时没有办法设置num_worker > 0

**Comment by wuxianshen** [comment]
找到原因了，只要在主进程中调用过time.perf_counter()函数，num_worker>0时程序退出时就会报DataLoader的错误，大佬知道为啥吗

**Comment by wuxianshen** [comment]
还有要把use_shared_memory设置成False

**Comment by tink2123** [comment]
主要是 aistudio 共享内存小，不建议把 num_worker 设置大于0。同理 use_shared_memory 不建议设成True
