### ISSUE TITLE
python code suggestion: there should be linting tools to keep code align with great rules

### ISSUE THREAD

**Issue by wj-Mcat** [PaddlePaddle/Paddle#33203]
After review the python api code, I found that there are some features which can be improved:

* **Function Annotations**

    Python is a dynamic program language which can determine the data type during runtime. But it will weak the intelligent code intelligence tips. This is not a pleasant programming experience, right？But python has supported the function annotations which can make code more readable & intelligence tips in ide.  

    reference:
    * [PEP 3107 -- Function Annotations](https://www.python.org/dev/peps/pep-3107/)
    * [typing -- Support for type hints](https://docs.python.org/3/library/typing.html)
    * [all of pytorch module code](https://github.com/pytorch/pytorch/blob/master/torch/nn/modules/conv.py#L267)

* **Unittest**

    The importance of unit testing goes without saying, there is little unittest case existing in repo. And it's a sub dir in modules. For SRP：Single responsibility principle, it should be the single tests dir for storing all of unittest case. This is my cons.

    reference:
    * [pytest](https://docs.pytest.org/en/6.2.x/)
    * [pytorch test](https://github.com/pytorch/pytorch/tree/master/test)

* **No Hard Code**

    After review the code, there are many hard code which will make code difficult to extend. 

    reference:
    * [Fixed Environment Name](https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/distributed/cloud_utils.py#L102)

* **Not all of code has function docstring**

    I understand that's understandable, but maintainability of open source projects is very important, and it must be done with a long-term way.

    Maybe, difference module is coded by different developer, but they are a team which should keep the same code style. If it's possible, use the same ide which can use the same plugins to keep things align with each other.

So that's part of my thinking, hope that can help you.  And if it's possible, I can help in the way.  Thanks for review this issue.

**Comment by YixinKristy** [comment]
Thanks so much for offering such insightful suggestions.

PaddlePaddle team appreciate all of your ideas and will take your suggestions into consideration. Additionally, we are very welcomed contributions in any kind of formats, so if you want, you could join our [SIG (Special Interest Group) ](https://www.paddlepaddle.org.cn/sig)to contribute for PaddlePaddle along with other excellent developers all over the world.

**Thank you again for your suggestions that encourage PaddlePaddle to explore the possibility for the future!**

**Comment by wj-Mcat** [comment]
@YixinKristy Ok, I will try to fix the exisiting issue to become the sig member. Thanks for your reply.

**Comment by wj-Mcat** [comment]
I have implemented the type hint feature for paddle:
![types-paddle-mini](https://user-images.githubusercontent.com/10242208/183284234-a608cf6f-16a0-4e5b-bc76-4e88aa988630.gif)


to get details, you can refer to:  https://wj-mcat.github.io/2022/08/07/python/types-paddle/

Hope that it can help you.
