### ISSUE TITLE
Paddle2.1 set_device("gpu") 并使用Dataloader 出现 Segmentation fault 错误

### ISSUE THREAD

**Issue by dercaft** [PaddlePaddle/Paddle#33200]
**set_device("cpu") 则正常运行，不设置或者 set_device("gpu") 就会出现Segmentation fault**

我在aistudio和自己的服务器上都出现了同样的问题
环境：
- aistudio
  - OS: Ubuntu 16.04
  - Python version: 3.7.4
  - CUDA version: 10.1.243
  - cuDNN version: 7.3.1
  - Nvidia driver version: 418.67
  - Paddle version: 2.1.0
  - Paddle With CUDA: True

- 本地服务器
  - OS: Ubuntu 18.04
  - Python version: 3.6.9
  - CUDA version: 10.2.89
  - cuDNN version: 7.6.5
  - Nvidia driver version: 450.80.02
  - Paddle version: 2.1.0
  - Paddle With CUDA: True

测试代码如下：

```python
import paddle
from paddle.vision.transforms import ToTensor
print(paddle.__version__)
paddle.set_device("gpu")

BATCH_SIZE=128
epochs=2

train_dataset = paddle.vision.datasets.MNIST(mode='train', transform=ToTensor())
train_loader = paddle.io.DataLoader(train_dataset, batch_size=BATCH_SIZE, shuffle=True)
print(len(train_loader))
print(type(train_loader))
for epoch in range(epochs):
    print("EPOCH:",epoch)
    for data in train_loader:
        print(data)
```
这里输出dataloader的类型为<class 'paddle.fluid.reader.DataLoader'>
**set_device("cpu") 则正常运行，不设置或者 set_device("gpu") 就会出现Segmentation fault**

部分输出如下
``` bash
<class 'paddle.fluid.reader.DataLoader'>
EPOCH: 0
W0529 14:49:26.324715 29174 device_context.cc:404] Please NOTE: device: 0, GPU Compute Capability: 7.0, Driver API Version: 10.1, Runtime API Version: 10.1
W0529 14:49:26.329295 29174 device_context.cc:422] device: 0, cuDNN Version: 7.6.

--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
0   std::thread::_Impl<std::_Bind_simple<ThreadPool::ThreadPool(unsigned long)::{lambda()#1} ()> >::_M_run()
1   std::__future_base::_State_baseV2::_M_do_set(std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> ()>*, bool*)
2   paddle::framework::SignalHandle(char const*, int)
3   paddle::platform::GetCurrentTraceBackString[abi:cxx11]()

----------------------
Error Message Summary:
----------------------
FatalError: `Segmentation fault` is detected by the operating system.
  [TimeInfo: *** Aborted at 1622270969 (unix time) try "date -d @1622270969" if you are using GNU date ***]
  [SignalInfo: *** SIGSEGV (@0x20) received by PID 29134 (TID 0x7fc2fcc74700) from PID 32 ***]

Segmentation fault (core dumped)
```

**Comment by MissPenguin** [comment]
您好，先验证下paddle是否正确安装吧，参考如下方式：
![image](https://user-images.githubusercontent.com/25809855/120093292-d7abca80-c14b-11eb-832d-2f3eb7365434.png)

如果验证发现没有成功安装，那么一般是环境版本问题，确认下环境的cuda cudnn trt版本和下载预测库对应的依赖版本一致。

**Comment by xinsuinizhuan** [comment]
> 
> 
> 您好，先验证下paddle是否正确安装吧，参考如下方式：
> ![image](https://user-images.githubusercontent.com/25809855/120093292-d7abca80-c14b-11eb-832d-2f3eb7365434.png)
> 
> 如果验证发现没有成功安装，那么一般是环境版本问题，确认下环境的cuda cudnn trt版本和下载预测库对应的依赖版本一致。

https://my.oschina.net/u/4067628/blog/4767067看看这个博客，不是环境问题，是内存越界问题，大家都遇到了这个问题，一直让我们测试环境，所有可能的环境都测试过了，cuda10 cuda10.1，带trt的，不带的，都测试过。就是内存访问越界。

**Comment by dercaft** [comment]
> 您好，先验证下paddle是否正确安装吧，参考如下方式：
> ![image](https://user-images.githubusercontent.com/25809855/120093292-d7abca80-c14b-11eb-832d-2f3eb7365434.png)
> 
> 如果验证发现没有成功安装，那么一般是环境版本问题，确认下环境的cuda cudnn trt版本和下载预测库对应的依赖版本一致。

你好我检查过了，paddle是正确安装的，paddle.utils.run_check() 输出也是正确的：
```
PaddlePaddle works well on 2 GPUs.
PaddlePaddle is installed successfully! Let's start deep learning with PaddlePaddle now.
```
现在的新观察是：
使用高层API的文件可以正常运行：
```python
model = paddle.Model(net, inputs, labels)
model.fit(train_dataset, epochs=200, batch_size=256, verbose=1)
model.evaluate(val_dataset, batch_size=128, verbose=1)
```
直接使用paddle.io.Dataloader()的文件运行会报上述段错误：
```python
import paddle
transform = paddle.vision.transforms.ToTensor()
cifar10_test = paddle.vision.datasets.Cifar10(mode='test', transform=transform)
valid_loader = paddle.io.DataLoader(cifar10_test, batch_size=batch_size)

for batch_id, data in enumerate(valid_loader()):
    x_data = data[0]
    y_data = paddle.to_tensor(data[1])
    y_data = paddle.unsqueeze(y_data, 1)
    print(x_data.shape,y_data)
```
