### ISSUE TITLE
安装问题：Compiled with WITH_GPU, but no GPU found in runtime.

### ISSUE THREAD

**Issue by ZiQiangXie** [PaddlePaddle/Paddle#33209]
安装环境信息：ubuntu16.04，cuda10.0，cudnn7.6.5，显卡驱动版本410.18，安装的paddle版本2.0.2或2.1.0，显卡是2080ti，多卡，pip离线安装，python版本3.8.5，anaconda环境；
进入python环境后，import　paddle，出现警告信息：
W0531 10:12:09.354604  8224 init.cc:136]　Compiled with WITH_GPU, but no GPU found in runtime.
path/site-packages/paddle/fluid/framework.py:298:　UserWarning:　You are using GPU version Paddle, but your CUDA device is not set properly. CPU device will be used by default.

看过其他issue以及网上其他方法，重启过／设置过CUDA_VISILBE_DEVICES/等等都尝试了还是不行；
但是之前在同一个机器上安装过1.8.1版本的没有问题；在使用的其他框架正常使用；

nvcc -V输出：
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2018 NVIDIA Corporation
Built on Sat_Aug_25_21:08:01_CDT_2018
Cuda compilation tools, release 10.0, V10.0.130

附执行summary_env.py的输出信息：
W0531 13:49:16.473908 50067 init.cc:136] Compiled with WITH_GPU, but no GPU found in runtime.
path/site-packages/paddle/fluid/framework.py:298: UserWarning: You are using GPU version Paddle, but your CUDA device is not set properly. CPU device will be used by default.
  warnings.warn(
****************************************
Paddle version: 2.0.2
Paddle With CUDA: True

OS: Ubuntu 16.04
Python version: 3.8.5

CUDA version: 10.0.130
cuDNN version: 7.6.5
Nvidia driver version: 410.48
****************************************

**Comment by ZHUI** [comment]
建议
1. 先 pip 重装一下 https://www.paddlepaddle.org.cn/install/quick?docurl=/documentation/docs/zh/install/pip/linux-pip.html
2. 查看系统环境变量是否设置正确。
3. 使用conda 的cuda环境重装，conda install paddlepaddle-gpu==2.1.0 cudatoolkit=10.1 --channel https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/Paddle/

**Comment by ZiQiangXie** [comment]
非常感谢！第一种方法，在安装命令后面那个网址找到了安装包，解决了。之前也想找到paddle带cuda版本的安装包，一直没找到。
顺便问一下，在那个网址里面，没有找到2.1.0的paddle对应的cuda 10.0版本的安装包，paddle后面的版本是不再支持cuda 10.0了吗？还是后续会更新支持cuda10.0的安装包？

**Comment by ZiQiangXie** [comment]
非常感谢！第一种方法，在安装命令后面那个网址找到了安装包，解决了。之前也想找到paddle带cuda版本的安装包，一直没找到。
顺便问一下，在那个网址里面，没有找到2.1.0的paddle对应的cuda 10.0版本的安装包，paddle后面的版本是不再支持cuda 10.0了吗？还是后续会更新支持cuda10.0的安装包？

**Comment by ZHUI** [comment]
> 非常感谢！第一种方法，在安装命令后面那个网址找到了安装包，解决了。之前也想找到paddle带cuda版本的安装包，一直没找到。
> 顺便问一下，在那个网址里面，没有找到2.1.0的paddle对应的cuda 10.0版本的安装包，paddle后面的版本是不再支持cuda 10.0了吗？还是后续会更新支持cuda10.0的安装包？

后续 cuda 10.0 将不在发包了，但没有放弃cuda 10.0 支持，用户可以自己编译10.0的安装包。

**Comment by ZiQiangXie** [comment]
感谢！
追问的原因是我们的环境不方便联网，只能离线安装，而且已有的硬件环境不能轻易变更，所以是希望有安装包会比较方便。
后续希望能继续使用paddle的新版本，如果不再提供安装包，有没有离线编译的教程？谢谢！

**Comment by ZHUI** [comment]
> 感谢！
> 追问的原因是我们的环境不方便联网，只能离线安装，而且已有的硬件环境不能轻易变更，所以是希望有安装包会比较方便。
> 后续希望能继续使用paddle的新版本，如果不再提供安装包，有没有离线编译的教程？谢谢！

https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/install/compile/linux-compile.html#compile_from_docker
推荐使用docker进行编译，如有编译问题，欢迎提issue再次询问。

**Comment by ZiQiangXie** [comment]
好的，谢谢！ @ZHUI
