### ISSUE TITLE
你好，感谢反馈。根据信息，初步怀疑是显存溢出的错误，调试思路：（1）请先尝试一下别的模型，看是否同样出现问题；（2）换一张尺寸较小的图像试试。

### ISSUE THREAD

**Issue by liwang54321** [PaddlePaddle/Paddle#33201]
你好，感谢反馈。根据信息，初步怀疑是显存溢出的错误，调试思路：（1）请先尝试一下别的模型，看是否同样出现问题；（2）换一张尺寸较小的图像试试。

_Originally posted by @liuhuiCNN in https://github.com/PaddlePaddle/Paddle/issues/33171#issuecomment-850243700_

我换了成了在jetson tx2上能够用gpu正常运行的模型，然后在jetson nx 上运行，还是报错了，然后这个错误发生在cpu copy 到gpu的时候，就一直卡死，然后就报错了 cureslove 报错返回值为 7

**Comment by MissPenguin** [comment]
您好，看了您之前提的那个issue，可以尝试换成cudnn7.6试试

**Comment by heavengate** [comment]
您好，jetson nx上Paddl'e版本，CUDA版本和cuDNN版本是否匹配呢

**Comment by xinsuinizhuan** [comment]
图片
应该是内存访问导致的问题，是库的问题，您看看，百度一下，导出都是这个问题：
0x00007FFA0CAB62D1 (paddle_inference.dll)处(位于 xxx.exe 中)引发的异常: 0xC0000005: 读取位置 0x0000000000000000 时发生访问冲突。
https://www.cnblogs.com/dzqiu/p/9518190.html
https://blog.csdn.net/PaddlePaddle/article/details/86739880
PaddlePaddle运行时出现EnforceNotMet: Enforce failed错误:

问题解决
PaddlePaddle的label要从0开始递增。

def getdata():
def reader():
for i in range(len(data_y)):
yield np.array(data_X[i]).astype('float32'), np.array(data_y[i]- 3).astype('int64')
return reader
您看看，百度上搜一下，都是这个问题，明显的访问内存越界问题，应该是官方库的问题，请帮忙改一下。不是环境问题。
