### ISSUE TITLE
grid_sample的gpu和cpu版本结果不一致

### ISSUE THREAD

**Issue by rfdeng** [PaddlePaddle/Paddle#33216]
背景：torch模型转paddle，发现grid_sample在cpu上跑和torch的api能对齐，但是gpu版本结果全0。

- 版本、环境信息：
PaddlePaddle版本：2.0.2 
torch版本：1.4和1.8都试过

使用的api：
torch.nn.functional.grid_sample(input, grid, mode='bilinear', padding_mode='zeros', align_corners=None)
paddle.nn.function.grid_sample(x, grid, mode='bilinear', padding_mode='zeros', align_corners=True, name=None)

问题：
同样的输入时，使用gpu时，执行torch.nn.functional.grid_sample(input, grid, align_corners=False) 和paddle.nn.functional.grid_sample(brush, grid, align_corners=False) 的结果对不齐。paddle的输出是全0。但是使用cpu时，这两者的结果是能对齐的。

**Comment by wanghaoshuang** [comment]
### cudnn

在align_corners=True, mode == 'bilinear' and padding_mode == 'zeros'情况下，paddle底层调用的是cudnn的实现，如果没有安装cudnn，则走的是非cudnn实现。
非cudnn实现目前有已知的bug，在input size比较大时，计算结果不符合预期，该问题正在修复中：https://github.com/PaddlePaddle/Paddle/pull/33100


### align_corners
在torch中， align_corners默认为False : https://pytorch.org/docs/master/generated/torch.nn.functional.grid_sample.html#torch.nn.functional.grid_sample
而你在paddle里用的是 align_corners=True

**Comment by rfdeng** [comment]
感谢回复：
1. 关于cudnn，我想我这边应该是成功使用了cudnn的，代码运行的时候有这么两行输出：
W0531 14:46:55.090055 15767 device_context.cc:362] Please NOTE: device: 0, GPU Compute Capability: 6.1, Driver API Version: 10.2, Runtime API Version: 10.1
W0531 14:46:55.096124 15767 device_context.cc:372] device: 0, cuDNN Version: 7.6.

2. paddle和torch的align_corners默认值不一样，我是在做模型转换，得保持输出一致，所以特地在运行的时候，把align_corners都取False了。

所以我的case应该是align_corners=False, mode == 'bilinear' and padding_mode == 'zeros'，起用了cudnn。但是gpu版本的输出为全0，与torch的输出不一致。

**Comment by wanghaoshuang** [comment]
>所以我的case应该是align_corners=False, mode == 'bilinear' and padding_mode == 'zeros'，起用了cudnn。但是gpu版本的输出为全0，与torch的输出不一致。

因为`align_corners=False`，所以底层应该是非cudnn的版本。你方便确认下`grid_sample(input, grid, mode='bilinear', padding_mode='zeros', align_corners=None)`中`input`和`grid`的shape么？如果~grid.shape[0]*grid.shape[1]*grid.shape[3]/512 > 1024~ `grid.shape[0]*grid.shape[1]*grid.shape[2]/512 > 1024`就会触发bug： https://github.com/PaddlePaddle/Paddle/pull/33100

如果触发了bug就需要等Paddle2.1.1版本中的修复，或者等我merge了PR  https://github.com/PaddlePaddle/Paddle/pull/33100 后安装paddle develop分支。

另外，可以确认下能否将pytorch和paddle的align_corners都设置为True, 然后走cudnn的计算。

**Comment by rfdeng** [comment]
> > 所以我的case应该是align_corners=False, mode == 'bilinear' and padding_mode == 'zeros'，起用了cudnn。但是gpu版本的输出为全0，与torch的输出不一致。
> 
> 因为`align_corners=False`，所以底层应该是非cudnn的版本。你方便确认下`grid_sample(input, grid, mode='bilinear', padding_mode='zeros', align_corners=None)`中`input`和`grid`的shape么？如果`grid.shape[0]*grid.shape[1]*grid.shape[3]/512 > 1024`就会触发bug： #33100
> 
> 如果触发了bug就需要等Paddle2.1.1版本中的修复，或者等我merge了PR #33100 后安装paddle develop分支。
> 
> 另外，可以确认下能否将pytorch和paddle的align_corners都设置为True, 然后走cudnn的计算。

谢谢大佬，我刚才看了下grid.shape[0]*grid.shape[1]*grid.shape[3]/512是20，没有超过1024，但是input的维度是超过了1024的，input shape过大也会触发bug么？

将pytorch和paddle的align_corners都设置为True是一个解决方案，但是我这边torch模型已经训好了，如果能直接align_corners=False的情况对齐是更好的。

**Comment by wanghaoshuang** [comment]
>谢谢大佬，我刚才看了下grid.shape[0]*grid.shape[1]*grid.shape[3]/512是20，没有超过1024，但是input的维度是超过了1024的，input shape过大也会触发bug么？

抱歉，应该是 grid.shape[0]*grid.shape[1]*grid.shape[2]/512

**Comment by rfdeng** [comment]
> > 谢谢大佬，我刚才看了下grid.shape[0]*grid.shape[1]*grid.shape[3]/512是20，没有超过1024，但是input的维度是超过了1024的，input shape过大也会触发bug么？
> 
> 抱歉，应该是 grid.shape[0]*grid.shape[1]*grid.shape[2]/512

好的好的，那确实超了
