### ISSUE TITLE
torch.repeat_interleave对应的Paddle 函数

### ISSUE THREAD

**Issue by severous** [PaddlePaddle/Paddle#33210]
paddle是否提供了如torch.repeat_interleave和numpy.repeat这样的api。实现的功能如下所示：
```python
y = torch.tensor([[1, 2], [3, 4]])
torch.repeat_interleave(y, 3, dim=1)
# tensor([[1, 1, 1, 2, 2, 2],[3, 3, 3, 4, 4, 4]])
```

如果没有，在前向传播过程中，是否可以将其转换成numpy，使用numpy的repeat,然后转换成tensor，这样会影响反向传播吗
如a -> b -> c，现在变成a -> b -->b_numpy-->b_tensor->c,这样会影响反向传播吗

**Comment by ZHUI** [comment]
> paddle是否提供了如torch.repeat_interleave和numpy.repeat这样的api。实现的功能如下所示：
> 
> ```python
> y = torch.tensor([[1, 2], [3, 4]])
> torch.repeat_interleave(y, 3, dim=1)
> # tensor([[1, 1, 1, 2, 2, 2],[3, 3, 3, 4, 4, 4]])
> ```
> 
> 如果没有，在前向传播过程中，是否可以将其转换成numpy，使用numpy的repeat,然后转换成tensor，这样会影响反向传播吗
> 如a -> b -> c，现在变成a -> b -->b_numpy-->b_tensor->c,这样会影响反向传播吗
1. 应该没有对应的，可以尝试通过 reshape 和 tile 组合实现 https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/tile_cn.html#tile
2. 转numpy是不可行的，没有梯度回传。

**Comment by severous** [comment]
好的，谢谢解答
