### ISSUE TITLE
No CUDA toolset found

### ISSUE THREAD

**Issue by Zhangts98** [PaddlePaddle/Paddle#33222]
gpu:  GeForce RTX 2080
cuda: 10.0
cmake : 3.16
cmake 命令： cmake .. -G "Visual Studio 14 2015" -A x64 -T host=x64 -DCMAKE_BUILD_TYPE=Release -DWITH_MKL=ON -DWITH_GPU=ON -DON_INFER=ON -DWITH_PYTHON=OFF -DCUDA_TOOLKIT_ROOT_DIR='C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v10.0'

问题： 1. 如何解决 No CUDA toolset found
             2. 支持编译debug版本的预测库么

使用上述cmake命令能够成功编译release/1.8 的预测库， 但是在编译release/2.0的预测库时，会出现下面的错误
-- Detecting C compile features - done
-- Looking for pthread.h
-- Looking for pthread.h - not found
-- Found Threads: TRUE
CMake Error at C:/Program Files/CMake/share/cmake-3.16/Modules/CMakeDetermineCompilerId.cmake:351 (message):
  No CUDA toolset found.
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.16/Modules/CMakeDetermineCompilerId.cmake:32 (CMAKE_DETERMINE_COMPILER_ID_BUILD)
  C:/Program Files/CMake/share/cmake-3.16/Modules/CMakeDetermineCUDACompiler.cmake:72 (CMAKE_DETERMINE_COMPILER_ID)
  CMakeLists.txt:48 (enable_language)

-- Configuring incomplete, errors occurred!
See also "F:/bianyi/Paddle_compie/Paddle/build/CMakeFiles/CMakeOutput.log".
See also "F:/bianyi/Paddle_compie/Paddle/build/CMakeFiles/CMakeError.log".

---------------------------------------   CMakeOutput.log --------------------------------------------------------
The system is: Windows - 10.0.16299 - AMD64
Compiling the CXX compiler identification source file "CMakeCXXCompilerId.cpp" succeeded.
Compiler:  
Build flags: 
Id flags:  

The output was:
0
Microsoft (R) 生成引擎版本 14.0.25420.1
版权所有(C) Microsoft Corporation。保留所有权利。

生成启动时间为 2021/5/31 15:00:10。
项目中不存在 BeforeTargets 特性中的“C:\Program Files (x86)\MSBuild\14.0\Microsoft.Common.targets\ImportAfter\Xamarin.Common.targets (34,37)”位置列出的目标“_ConvertPdbFiles”，将忽略该目标。
项目中不存在 AfterTargets 特性中的“C:\Program Files (x86)\MSBuild\14.0\Microsoft.Common.targets\ImportAfter\Xamarin.Common.targets (34,70)”位置列出的目标“_CollectPdbFiles”，将忽略该目标。
项目中不存在 BeforeTargets 特性中的“C:\Program Files (x86)\MSBuild\14.0\Microsoft.Common.targets\ImportAfter\Xamarin.Common.targets (41,38)”位置列出的目标“_CollectMdbFiles”，将忽略该目标。
项目中不存在 AfterTargets 特性中的“C:\Program Files (x86)\MSBuild\14.0\Microsoft.Common.targets\ImportAfter\Xamarin.Common.targets (41,71)”位置列出的目标“_CopyMdbFiles”，将忽略该目标。
节点 1 上的项目“F:\bianyi\Paddle_compie\Paddle\build\CMakeFiles\3.16.0\CompilerIdCXX\CompilerIdCXX.vcxproj”(默认目标)。
PrepareForBuild:
  正在创建目录“Debug\”。
  正在创建目录“Debug\CompilerIdCXX.tlog\”。
InitializeBuildStatus:
  正在创建“Debug\CompilerIdCXX.tlog\unsuccessfulbuild”，因为已指定“AlwaysCreate”。
ClCompile:
  D:\my_download\VS2015\VC\bin\amd64\CL.exe /c /nologo /W0 /WX- /Od /D _MBCS /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"Debug\\" /Fd"Debug\vc140.pdb" /Gd /TP /errorReport:queue CMakeCXXCompilerId.cpp
  CMakeCXXCompilerId.cpp
Link:
  D:\my_download\VS2015\VC\bin\amd64\link.exe /ERRORREPORT:QUEUE /OUT:".\CompilerIdCXX.exe" /INCREMENTAL:NO /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib comdlg32.lib advapi32.lib shell32.lib ole32.lib oleaut32.lib uuid.lib odbc32.lib odbccp32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /PDB:".\CompilerIdCXX.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:".\CompilerIdCXX.lib" /MACHINE:X64 Debug\CMakeCXXCompilerId.obj
  CompilerIdCXX.vcxproj -> F:\bianyi\Paddle_compie\Paddle\build\CMakeFiles\3.16.0\CompilerIdCXX\.\CompilerIdCXX.exe
PostBuildEvent:
  for %%i in (cl.exe) do @echo CMAKE_CXX_COMPILER=%%~$PATH:i
  :VCEnd
  CMAKE_CXX_COMPILER=D:\my_download\VS2015\VC\bin\amd64\cl.exe
FinalizeBuildStatus:
  正在删除文件“Debug\CompilerIdCXX.tlog\unsuccessfulbuild”。
  正在对“Debug\CompilerIdCXX.tlog\CompilerIdCXX.lastbuildstate”执行 Touch 任务。
已完成生成项目“F:\bianyi\Paddle_compie\Paddle\build\CMakeFiles\3.16.0\CompilerIdCXX\CompilerIdCXX.vcxproj”(默认目标)的操作。

已成功生成。
    0 个警告
    0 个错误

已用时间 00:00:00.82

Compilation of the CXX compiler identification source "CMakeCXXCompilerId.cpp" produced "CompilerIdCXX.exe"

Compilation of the CXX compiler identification source "CMakeCXXCompilerId.cpp" produced "CompilerIdCXX.vcxproj"

The CXX compiler identification is MSVC, found in "F:/bianyi/Paddle_compie/Paddle/build/CMakeFiles/3.16.0/CompilerIdCXX/CompilerIdCXX.exe"

Compiling the C compiler identification source file "CMakeCCompilerId.c" succeeded.
Compiler:  
Build flags: 
Id flags:  

The output was:
0
Microsoft (R) 生成引擎版本 14.0.25420.1
版权所有(C) Microsoft Corporation。保留所有权利。

生成启动时间为 2021/5/31 15:00:11。
项目中不存在 BeforeTargets 特性中的“C:\Program Files (x86)\MSBuild\14.0\Microsoft.Common.targets\ImportAfter\Xamarin.Common.targets (34,37)”位置列出的目标“_ConvertPdbFiles”，将忽略该目标。
项目中不存在 AfterTargets 特性中的“C:\Program Files (x86)\MSBuild\14.0\Microsoft.Common.targets\ImportAfter\Xamarin.Common.targets (34,70)”位置列出的目标“_CollectPdbFiles”，将忽略该目标。
项目中不存在 BeforeTargets 特性中的“C:\Program Files (x86)\MSBuild\14.0\Microsoft.Common.targets\ImportAfter\Xamarin.Common.targets (41,38)”位置列出的目标“_CollectMdbFiles”，将忽略该目标。
项目中不存在 AfterTargets 特性中的“C:\Program Files (x86)\MSBuild\14.0\Microsoft.Common.targets\ImportAfter\Xamarin.Common.targets (41,71)”位置列出的目标“_CopyMdbFiles”，将忽略该目标。
节点 1 上的项目“F:\bianyi\Paddle_compie\Paddle\build\CMakeFiles\3.16.0\CompilerIdC\CompilerIdC.vcxproj”(默认目标)。
PrepareForBuild:
  正在创建目录“Debug\”。
  正在创建目录“Debug\CompilerIdC.tlog\”。
InitializeBuildStatus:
  正在创建“Debug\CompilerIdC.tlog\unsuccessfulbuild”，因为已指定“AlwaysCreate”。
ClCompile:
  D:\my_download\VS2015\VC\bin\amd64\CL.exe /c /nologo /W0 /WX- /Od /D _MBCS /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"Debug\\" /Fd"Debug\vc140.pdb" /Gd /TC /errorReport:queue CMakeCCompilerId.c
  CMakeCCompilerId.c
Link:
  D:\my_download\VS2015\VC\bin\amd64\link.exe /ERRORREPORT:QUEUE /OUT:".\CompilerIdC.exe" /INCREMENTAL:NO /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib comdlg32.lib advapi32.lib shell32.lib ole32.lib oleaut32.lib uuid.lib odbc32.lib odbccp32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /PDB:".\CompilerIdC.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:".\CompilerIdC.lib" /MACHINE:X64 Debug\CMakeCCompilerId.obj
  CompilerIdC.vcxproj -> F:\bianyi\Paddle_compie\Paddle\build\CMakeFiles\3.16.0\CompilerIdC\.\CompilerIdC.exe
PostBuildEvent:
  for %%i in (cl.exe) do @echo CMAKE_C_COMPILER=%%~$PATH:i
  :VCEnd
  CMAKE_C_COMPILER=D:\my_download\VS2015\VC\bin\amd64\cl.exe
FinalizeBuildStatus:
  正在删除文件“Debug\CompilerIdC.tlog\unsuccessfulbuild”。
  正在对“Debug\CompilerIdC.tlog\CompilerIdC.lastbuildstate”执行 Touch 任务。
已完成生成项目“F:\bianyi\Paddle_compie\Paddle\build\CMakeFiles\3.16.0\CompilerIdC\CompilerIdC.vcxproj”(默认目标)的操作。

已成功生成。
    0 个警告
    0 个错误

已用时间 00:00:00.73

Compilation of the C compiler identification source "CMakeCCompilerId.c" produced "CompilerIdC.exe"

Compilation of the C compiler identification source "CMakeCCompilerId.c" produced "CompilerIdC.vcxproj"

The C compiler identification is MSVC, found in "F:/bianyi/Paddle_compie/Paddle/build/CMakeFiles/3.16.0/CompilerIdC/CompilerIdC.exe"

Determining if the CXX compiler works passed with the following output:
Change Dir: F:/bianyi/Paddle_compie/Paddle/build/CMakeFiles/CMakeTmp

Run Build Command(s):C:/Program Files (x86)/MSBuild/14.0/bin/MSBuild.exe cmTC_0fce0.vcxproj /p:Configuration=Debug /p:Platform=x64 /p:VisualStudioVersion=14.0 /v:m && Microsoft (R) 生成引擎版本 14.0.25420.1

版权所有(C) Microsoft Corporation。保留所有权利。

  用于 x64 的 Microsoft (R) C/C++ 优化编译器 19.00.24215.1 版

  版权所有(C) Microsoft Corporation。保留所有权利。

  

  cl /c /Zi /W3 /WX- /Od /Ob0 /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\"Debug\"" /D _MBCS /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /GR /Fo"cmTC_0fce0.dir\Debug\\" /Fd"cmTC_0fce0.dir\Debug\vc140.pdb" /Gd /TP /errorReport:queue F:\bianyi\Paddle_compie\Paddle\build\CMakeFiles\CMakeTmp\testCXXCompiler.cxx

  

  testCXXCompiler.cxx

  cmTC_0fce0.vcxproj -> F:\bianyi\Paddle_compie\Paddle\build\CMakeFiles\CMakeTmp\Debug\cmTC_0fce0.exe

  cmTC_0fce0.vcxproj -> F:/bianyi/Paddle_compie/Paddle/build/CMakeFiles/CMakeTmp/Debug/cmTC_0fce0.pdb (Full PDB)

Detecting CXX compiler ABI info compiled with the following output:
Change Dir: F:/bianyi/Paddle_compie/Paddle/build/CMakeFiles/CMakeTmp

Run Build Command(s):C:/Program Files (x86)/MSBuild/14.0/bin/MSBuild.exe cmTC_695ab.vcxproj /p:Configuration=Debug /p:Platform=x64 /p:VisualStudioVersion=14.0 /v:m && Microsoft (R) 生成引擎版本 14.0.25420.1

版权所有(C) Microsoft Corporation。保留所有权利。

  用于 x64 的 Microsoft (R) C/C++ 优化编译器 19.00.24215.1 版

  版权所有(C) Microsoft Corporation。保留所有权利。

  

  cl /c /Zi /W3 /WX- /Od /Ob0 /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\"Debug\"" /D _MBCS /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /GR /Fo"cmTC_695ab.dir\Debug\\" /Fd"cmTC_695ab.dir\Debug\vc140.pdb" /Gd /TP /errorReport:queue "C:\Program Files\CMake\share\cmake-3.16\Modules\CMakeCXXCompilerABI.cpp"

  

  CMakeCXXCompilerABI.cpp

  cmTC_695ab.vcxproj -> F:\bianyi\Paddle_compie\Paddle\build\CMakeFiles\CMakeTmp\Debug\cmTC_695ab.exe

  cmTC_695ab.vcxproj -> F:/bianyi/Paddle_compie/Paddle/build/CMakeFiles/CMakeTmp/Debug/cmTC_695ab.pdb (Full PDB)

Detecting CXX [-std:c++14] compiler features compiled with the following output:
Change Dir: F:/bianyi/Paddle_compie/Paddle/build/CMakeFiles/CMakeTmp

Run Build Command(s):C:/Program Files (x86)/MSBuild/14.0/bin/MSBuild.exe cmTC_c402d.vcxproj /p:Configuration=Debug /p:Platform=x64 /p:VisualStudioVersion=14.0 /v:m && Microsoft (R) 生成引擎版本 14.0.25420.1

版权所有(C) Microsoft Corporation。保留所有权利。

  用于 x64 的 Microsoft (R) C/C++ 优化编译器 19.00.24215.1 版

  版权所有(C) Microsoft Corporation。保留所有权利。

  

  cl /c /Zi /W3 /WX- /Od /Ob0 /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\"Debug\"" /D _MBCS /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /GR /Fo"cmTC_c402d.dir\Debug\\" /Fd"cmTC_c402d.dir\Debug\vc140.pdb" /Gd /TP /errorReport:queue  -std:c++14 F:\bianyi\Paddle_compie\Paddle\build\CMakeFiles\feature_tests.cxx

  

  feature_tests.cxx

  cmTC_c402d.vcxproj -> F:\bianyi\Paddle_compie\Paddle\build\CMakeFiles\CMakeTmp\Debug\cmTC_c402d.exe

  cmTC_c402d.vcxproj -> F:/bianyi/Paddle_compie/Paddle/build/CMakeFiles/CMakeTmp/Debug/cmTC_c402d.pdb (Full PDB)

    Feature record: CXX_FEATURE:1cxx_template_template_parameters
    Feature record: CXX_FEATURE:1cxx_alias_templates
    Feature record: CXX_FEATURE:1cxx_alignas
    Feature record: CXX_FEATURE:1cxx_alignof
    Feature record: CXX_FEATURE:1cxx_attributes
    Feature record: CXX_FEATURE:1cxx_auto_type
    Feature record: CXX_FEATURE:1cxx_constexpr
    Feature record: CXX_FEATURE:1cxx_decltype
    Feature record: CXX_FEATURE:0cxx_decltype_incomplete_return_types
    Feature record: CXX_FEATURE:1cxx_default_function_template_args
    Feature record: CXX_FEATURE:1cxx_defaulted_functions
    Feature record: CXX_FEATURE:1cxx_defaulted_move_initializers
    Feature record: CXX_FEATURE:1cxx_delegating_constructors
    Feature record: CXX_FEATURE:1cxx_deleted_functions
    Feature record: CXX_FEATURE:1cxx_enum_forward_declarations
    Feature record: CXX_FEATURE:1cxx_explicit_conversions
    Feature record: CXX_FEATURE:1cxx_extended_friend_declarations
    Feature record: CXX_FEATURE:1cxx_extern_templates
    Feature record: CXX_FEATURE:1cxx_final
    Feature record: CXX_FEATURE:1cxx_func_identifier
    Feature record: CXX_FEATURE:1cxx_generalized_initializers
    Feature record: CXX_FEATURE:1cxx_inheriting_constructors
    Feature record: CXX_FEATURE:1cxx_inline_namespaces
    Feature record: CXX_FEATURE:1cxx_lambdas
    Feature record: CXX_FEATURE:1cxx_local_type_template_args
    Feature record: CXX_FEATURE:1cxx_long_long_type
    Feature record: CXX_FEATURE:1cxx_noexcept
    Feature record: CXX_FEATURE:1cxx_nonstatic_member_init
    Feature record: CXX_FEATURE:1cxx_nullptr
    Feature record: CXX_FEATURE:1cxx_override
    Feature record: CXX_FEATURE:1cxx_range_for
    Feature record: CXX_FEATURE:1cxx_raw_string_literals
    Feature record: CXX_FEATURE:1cxx_reference_qualified_functions
    Feature record: CXX_FEATURE:1cxx_right_angle_brackets
    Feature record: CXX_FEATURE:1cxx_rvalue_references
    Feature record: CXX_FEATURE:1cxx_sizeof_member
    Feature record: CXX_FEATURE:1cxx_static_assert
    Feature record: CXX_FEATURE:1cxx_strong_enums
    Feature record: CXX_FEATURE:1cxx_thread_local
    Feature record: CXX_FEATURE:1cxx_trailing_return_types
    Feature record: CXX_FEATURE:1cxx_unicode_literals
    Feature record: CXX_FEATURE:1cxx_uniform_initialization
    Feature record: CXX_FEATURE:1cxx_unrestricted_unions
    Feature record: CXX_FEATURE:1cxx_user_literals
    Feature record: CXX_FEATURE:1cxx_variadic_macros
    Feature record: CXX_FEATURE:1cxx_variadic_templates
    Feature record: CXX_FEATURE:0cxx_aggregate_default_initializers
    Feature record: CXX_FEATURE:1cxx_attribute_deprecated
    Feature record: CXX_FEATURE:1cxx_binary_literals
    Feature record: CXX_FEATURE:1cxx_contextual_conversions
    Feature record: CXX_FEATURE:1cxx_decltype_auto
    Feature record: CXX_FEATURE:1cxx_digit_separators
    Feature record: CXX_FEATURE:1cxx_generic_lambdas
    Feature record: CXX_FEATURE:1cxx_lambda_init_captures
    Feature record: CXX_FEATURE:0cxx_relaxed_constexpr
    Feature record: CXX_FEATURE:1cxx_return_type_deduction
    Feature record: CXX_FEATURE:1cxx_variable_templates

Detecting CXX [] compiler features compiled with the following output:
Change Dir: F:/bianyi/Paddle_compie/Paddle/build/CMakeFiles/CMakeTmp

Run Build Command(s):C:/Program Files (x86)/MSBuild/14.0/bin/MSBuild.exe cmTC_d4bca.vcxproj /p:Configuration=Debug /p:Platform=x64 /p:VisualStudioVersion=14.0 /v:m && Microsoft (R) 生成引擎版本 14.0.25420.1

版权所有(C) Microsoft Corporation。保留所有权利。

  用于 x64 的 Microsoft (R) C/C++ 优化编译器 19.00.24215.1 版

  版权所有(C) Microsoft Corporation。保留所有权利。

  

  cl /c /Zi /W3 /WX- /Od /Ob0 /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\"Debug\"" /D _MBCS /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /GR /Fo"cmTC_d4bca.dir\Debug\\" /Fd"cmTC_d4bca.dir\Debug\vc140.pdb" /Gd /TP /errorReport:queue F:\bianyi\Paddle_compie\Paddle\build\CMakeFiles\feature_tests.cxx

  

  feature_tests.cxx

  cmTC_d4bca.vcxproj -> F:\bianyi\Paddle_compie\Paddle\build\CMakeFiles\CMakeTmp\Debug\cmTC_d4bca.exe

  cmTC_d4bca.vcxproj -> F:/bianyi/Paddle_compie/Paddle/build/CMakeFiles/CMakeTmp/Debug/cmTC_d4bca.pdb (Full PDB)

    Feature record: CXX_FEATURE:1cxx_template_template_parameters
    Feature record: CXX_FEATURE:1cxx_alias_templates
    Feature record: CXX_FEATURE:1cxx_alignas
    Feature record: CXX_FEATURE:1cxx_alignof
    Feature record: CXX_FEATURE:1cxx_attributes
    Feature record: CXX_FEATURE:1cxx_auto_type
    Feature record: CXX_FEATURE:1cxx_constexpr
    Feature record: CXX_FEATURE:1cxx_decltype
    Feature record: CXX_FEATURE:0cxx_decltype_incomplete_return_types
    Feature record: CXX_FEATURE:1cxx_default_function_template_args
    Feature record: CXX_FEATURE:1cxx_defaulted_functions
    Feature record: CXX_FEATURE:1cxx_defaulted_move_initializers
    Feature record: CXX_FEATURE:1cxx_delegating_constructors
    Feature record: CXX_FEATURE:1cxx_deleted_functions
    Feature record: CXX_FEATURE:1cxx_enum_forward_declarations
    Feature record: CXX_FEATURE:1cxx_explicit_conversions
    Feature record: CXX_FEATURE:1cxx_extended_friend_declarations
    Feature record: CXX_FEATURE:1cxx_extern_templates
    Feature record: CXX_FEATURE:1cxx_final
    Feature record: CXX_FEATURE:1cxx_func_identifier
    Feature record: CXX_FEATURE:1cxx_generalized_initializers
    Feature record: CXX_FEATURE:1cxx_inheriting_constructors
    Feature record: CXX_FEATURE:1cxx_inline_namespaces
    Feature record: CXX_FEATURE:1cxx_lambdas
    Feature record: CXX_FEATURE:1cxx_local_type_template_args
    Feature record: CXX_FEATURE:1cxx_long_long_type
    Feature record: CXX_FEATURE:1cxx_noexcept
    Feature record: CXX_FEATURE:1cxx_nonstatic_member_init
    Feature record: CXX_FEATURE:1cxx_nullptr
    Feature record: CXX_FEATURE:1cxx_override
    Feature record: CXX_FEATURE:1cxx_range_for
    Feature record: CXX_FEATURE:1cxx_raw_string_literals
    Feature record: CXX_FEATURE:1cxx_reference_qualified_functions
    Feature record: CXX_FEATURE:1cxx_right_angle_brackets
    Feature record: CXX_FEATURE:1cxx_rvalue_references
    Feature record: CXX_FEATURE:1cxx_sizeof_member
    Feature record: CXX_FEATURE:1cxx_static_assert
    Feature record: CXX_FEATURE:1cxx_strong_enums
    Feature record: CXX_FEATURE:1cxx_thread_local
    Feature record: CXX_FEATURE:1cxx_trailing_return_types
    Feature record: CXX_FEATURE:1cxx_unicode_literals
    Feature record: CXX_FEATURE:1cxx_uniform_initialization
    Feature record: CXX_FEATURE:1cxx_unrestricted_unions
    Feature record: CXX_FEATURE:1cxx_user_literals
    Feature record: CXX_FEATURE:1cxx_variadic_macros
    Feature record: CXX_FEATURE:1cxx_variadic_templates
    Feature record: CXX_FEATURE:0cxx_aggregate_default_initializers
    Feature record: CXX_FEATURE:1cxx_attribute_deprecated
    Feature record: CXX_FEATURE:1cxx_binary_literals
    Feature record: CXX_FEATURE:1cxx_contextual_conversions
    Feature record: CXX_FEATURE:1cxx_decltype_auto
    Feature record: CXX_FEATURE:1cxx_digit_separators
    Feature record: CXX_FEATURE:1cxx_generic_lambdas
    Feature record: CXX_FEATURE:1cxx_lambda_init_captures
    Feature record: CXX_FEATURE:0cxx_relaxed_constexpr
    Feature record: CXX_FEATURE:1cxx_return_type_deduction
    Feature record: CXX_FEATURE:1cxx_variable_templates
Determining if the C compiler works passed with the following output:
Change Dir: F:/bianyi/Paddle_compie/Paddle/build/CMakeFiles/CMakeTmp

Run Build Command(s):C:/Program Files (x86)/MSBuild/14.0/bin/MSBuild.exe cmTC_850b7.vcxproj /p:Configuration=Debug /p:Platform=x64 /p:VisualStudioVersion=14.0 /v:m && Microsoft (R) 生成引擎版本 14.0.25420.1

版权所有(C) Microsoft Corporation。保留所有权利。

  用于 x64 的 Microsoft (R) C/C++ 优化编译器 19.00.24215.1 版

  版权所有(C) Microsoft Corporation。保留所有权利。

  

  cl /c /Zi /W3 /WX- /Od /Ob0 /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\"Debug\"" /D _MBCS /Gm- /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"cmTC_850b7.dir\Debug\\" /Fd"cmTC_850b7.dir\Debug\vc140.pdb" /Gd /TC /errorReport:queue F:\bianyi\Paddle_compie\Paddle\build\CMakeFiles\CMakeTmp\testCCompiler.c

  

  testCCompiler.c

  cmTC_850b7.vcxproj -> F:\bianyi\Paddle_compie\Paddle\build\CMakeFiles\CMakeTmp\Debug\cmTC_850b7.exe

  cmTC_850b7.vcxproj -> F:/bianyi/Paddle_compie/Paddle/build/CMakeFiles/CMakeTmp/Debug/cmTC_850b7.pdb (Full PDB)

Detecting C compiler ABI info compiled with the following output:
Change Dir: F:/bianyi/Paddle_compie/Paddle/build/CMakeFiles/CMakeTmp

Run Build Command(s):C:/Program Files (x86)/MSBuild/14.0/bin/MSBuild.exe cmTC_e5fbc.vcxproj /p:Configuration=Debug /p:Platform=x64 /p:VisualStudioVersion=14.0 /v:m && Microsoft (R) 生成引擎版本 14.0.25420.1

版权所有(C) Microsoft Corporation。保留所有权利。

  用于 x64 的 Microsoft (R) C/C++ 优化编译器 19.00.24215.1 版

  版权所有(C) Microsoft Corporation。保留所有权利。

  

  cl /c /Zi /W3 /WX- /Od /Ob0 /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\"Debug\"" /D _MBCS /Gm- /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"cmTC_e5fbc.dir\Debug\\" /Fd"cmTC_e5fbc.dir\Debug\vc140.pdb" /Gd /TC /errorReport:queue "C:\Program Files\CMake\share\cmake-3.16\Modules\CMakeCCompilerABI.c"

  

  CMakeCCompilerABI.c

  cmTC_e5fbc.vcxproj -> F:\bianyi\Paddle_compie\Paddle\build\CMakeFiles\CMakeTmp\Debug\cmTC_e5fbc.exe

  cmTC_e5fbc.vcxproj -> F:/bianyi/Paddle_compie/Paddle/build/CMakeFiles/CMakeTmp/Debug/cmTC_e5fbc.pdb (Full PDB)

------------------------------------------------------ CMakeError.log ----------------------------------------------------
Determining if the include file pthread.h exists failed with the following output:
Change Dir: F:/bianyi/Paddle_compie/Paddle/build/CMakeFiles/CMakeTmp

Run Build Command(s):C:/Program Files (x86)/MSBuild/14.0/bin/MSBuild.exe cmTC_1b4cd.vcxproj /p:Configuration=Debug /p:Platform=x64 /p:VisualStudioVersion=14.0 /v:m && Microsoft (R) 生成引擎版本 14.0.25420.1

版权所有(C) Microsoft Corporation。保留所有权利。

  用于 x64 的 Microsoft (R) C/C++ 优化编译器 19.00.24215.1 版

  版权所有(C) Microsoft Corporation。保留所有权利。

  

  cl /c /Zi /W3 /WX- /Od /Ob0 /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\"Debug\"" /D _MBCS /Gm- /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"cmTC_1b4cd.dir\Debug\\" /Fd"cmTC_1b4cd.dir\Debug\vc140.pdb" /Gd /TC /errorReport:queue F:\bianyi\Paddle_compie\Paddle\build\CMakeFiles\CMakeTmp\CheckIncludeFile.c

  

  CheckIncludeFile.c

F:\bianyi\Paddle_compie\Paddle\build\CMakeFiles\CMakeTmp\CheckIncludeFile.c(1): fatal error C1083: 无法打开包括文件: “pthread.h”: No such file or directory [F:\bianyi\Paddle_compie\Paddle\build\CMakeFiles\CMakeTmp\cmTC_1b4cd.vcxproj]

**Comment by jiweibo** [comment]
1. 如何解决 No CUDA toolset found
您好，怀疑您的cuda环境被改了，方便重装下cuda吗，或者装个高版本的cuda比如cuda10.2，cuda的 Visual studio integration也要装下。这个问题的原因比较多，一般是环境问题，不太好debug，最好的方式就是卸载重装吧。
2. 支持编译debug版本的预测库么
目前还不太建议编译debug版本的库，一方面会导致库体积过大，另一方面有一些第三方库都是直接下载的release版本，使用起来可能有冲突

**Comment by Zhangts98** [comment]
> 1. 如何解决 No CUDA toolset found
>    您好，怀疑您的cuda环境被改了，方便重装下cuda吗，或者装个高版本的cuda比如cuda10.2，cuda的 Visual studio integration也要装下。这个问题的原因比较多，一般是环境问题，不太好debug，最好的方式就是卸载重装吧。
> 2. 支持编译debug版本的预测库么
>    目前还不太建议编译debug版本的库，一方面会导致库体积过大，另一方面有一些第三方库都是直接下载的release版本，使用起来可能有冲突

1. 可是我现在还是能正常编译1.8版本的。我再找找其他方法， 如果都不行的话就只好重装一下了。
2. 因为一些原因，需要我编译debug版本的， 如果要编译debug版的话， 除了需要把cmake命令的 -DCMAKE_BUILD_TYPE为Debug，那些第三方库下载debug版本的，还有其他地方要修改和注意的么？
3. 然后就是，例如这个gflags.cmake，set(GFLAGS_TAG .....) 那行是控制下载版本的么？
![企业微信截图_16224483833846](https://user-images.githubusercontent.com/61573829/120161933-73ac0380-c22a-11eb-8c13-4d5dbfa2eb47.png)
