### ISSUE TITLE
想知道训练chinese_ocr_db_crnn_server模型的训练数据集是什么

### ISSUE THREAD

**Issue by xishanhan** [PaddlePaddle/Paddle#33220]
请告诉我可公开的部分训练数据就可以了，谢谢。

**Comment by MissPenguin** [comment]
您好，chinese_ocr_db_crnn_server模型来源于[PaddleOCR](https://github.com/PaddlePaddle/PaddleOCR)，所使用的训练数据可参考这条[FAQ](https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.1/doc/doc_ch/FAQ.md#q324%E5%BC%80%E6%BA%90%E6%A8%A1%E5%9E%8B%E4%BD%BF%E7%94%A8%E7%9A%84%E8%AE%AD%E7%BB%83%E6%95%B0%E6%8D%AE%E6%98%AF%E4%BB%80%E4%B9%88%E8%83%BD%E5%90%A6%E5%BC%80%E6%BA%90)：

![image](https://user-images.githubusercontent.com/25809855/120158721-0480e000-c227-11eb-88b0-dd8870d274b5.png)

**Comment by xishanhan** [comment]
感谢回复。
