### ISSUE TITLE
windows下2.1版预测库启动报错，无法定位程序输入点dnnl_reduction_desc_init于动态链接库paddle_inference.dll上 

### ISSUE THREAD

**Issue by yoyao1** [PaddlePaddle/Paddle#33239]
无法定位程序输入点dnnl_reduction_desc_init于动态链接库paddle_inference.dll上 
2.0版没有问题

GIT COMMIT ID: 4ccd9a0a86ad550a861c954d70e28ef15741b310
WITH_MKL: ON
WITH_MKLDNN: ON
WITH_GPU: ON
CUDA version: 10.2
CUDNN version: v7.6
CXX compiler version: 19.16.27045.0
WITH_TENSORRT: ON
TensorRT version: v7

**Comment by joey12300** [comment]
您好，请问是跑什么模型呢？

**Comment by yoyao1** [comment]
跑分割的模型，不过这个是启动程序时就报错，还没到加载模型的地方

**Comment by joey12300** [comment]
嗯嗯，辛苦提供一下脚本代码以及详细的报错信息

**Comment by yoyao1** [comment]
是c++的程序，代码类类似于官方的预测demo

**Comment by joey12300** [comment]
> 是c++的程序，代码类类似于官方的预测demo

嗯嗯，这边是跑的PaddleSeg的demo吗？麻烦提供一下可复现的代码以及详细的报错信息，有助于快速定位问题

**Comment by yoyao1** [comment]
'''
int main(int argc, char** argv) {
	//::GFLAGS_NAMESPACE::ParseCommandLineFlags(&argc, &argv, true);
	//paddle_infer::demo::RunAnalysis();
	paddle_infer::Config config;
	std::cout << "=========================Runs successfully===================="
		<< std::endl;
	return 0;
}
'''
代码就这一句也会报错

**Comment by yoyao1** [comment]
![paddle2 1报错](https://user-images.githubusercontent.com/40195730/120290209-a3eab500-c2b1-11eb-8f38-c70e3e7fc399.jpg)

**Comment by yoyao1** [comment]
找到问题了 2.0和2.1用的 mkldnn.dll 不一致，2.1是2.2.1.0 ，2.0是1.6.0.0

**Comment by yoyao1** [comment]
close #33239

**Comment by yoyao1** [comment]
close

**Comment by yoyao1** [comment]
这个自己不能关闭吗？
