### ISSUE TITLE
windows GPU PaddlePaddle运行时出现EnforceNotMet: Enforce failed错误:

### ISSUE THREAD

**Issue by xinsuinizhuan** [PaddlePaddle/Paddle#33233]
我cuda10 不带trt, cuda10.1 带trt， cuda10.2带trt都试过了，都是这个问题，应该是读取某个空地址了，库的内存访问越界问题：
0x00007FFA0CAB62D1 (paddle_inference.dll)处(位于 xxx.exe 中)引发的异常: 0xC0000005: 读取位置 0x0000000000000000 时发生访问冲突。
百度了一下，很多同学遇到了，我的问题，应该跟如下这各同学遇到的一样，但是不知道怎么改：
https://my.oschina.net/u/4067628/blog/4767067

**Comment by joey12300** [comment]
您好，请问你的预测库版本是多少，跑什么模型，方便提供代码吗？

**Comment by xinsuinizhuan** [comment]
版本库代码我试过2.0.1版本，试过2.1.0版本，都是同样的问题，模型的话，跑过官方的中英文通用OCR模型（143.4M），也跑过自己使用server版训练转换的库，使用的是，动态图版本里面的cpp下面的C++代码跑的

**Comment by xinsuinizhuan** [comment]
> 
> 
> 您好，请问你的预测库版本是多少，跑什么模型，方便提供代码吗？

我这边有环境，可以远程帮忙排查吗？向日葵

**Comment by xinsuinizhuan** [comment]
> 
> 
> 您好，请问你的预测库版本是多少，跑什么模型，方便提供代码吗？

代码的话，是使用的官方https://github.com/PaddlePaddle/PaddleOCR/tree/release/2.1/deploy/cpp_infer下的代码，然后封装的。

**Comment by yingshengBD** [comment]
您好，能否提供完整的stack信息

**Comment by xinsuinizhuan** [comment]
> 
> 
> 您好，能否提供完整的stack信息

怎么查看stack信息？
![图片](https://user-images.githubusercontent.com/40679769/120287563-ed5af480-c2f1-11eb-9db1-779e7312386d.png)

**Comment by xinsuinizhuan** [comment]
![Uploading 图片.png…]()

**Comment by xinsuinizhuan** [comment]
![图片](https://user-images.githubusercontent.com/40679769/120289945-6bb89600-c2f4-11eb-9612-ff2d4d9d7ab3.png)

**Comment by xinsuinizhuan** [comment]
![图片](https://user-images.githubusercontent.com/40679769/120298019-4465c700-c2fc-11eb-9b5a-ec26adf9e8a3.png)

完全官方代码，控制台程序：
![图片](https://user-images.githubusercontent.com/40679769/120297948-30ba6080-c2fc-11eb-9aa3-6f1f061501b6.png)

就配置了下库和opencv，然后main里面改了路径，依然报错

**Comment by xinsuinizhuan** [comment]
模型：使用的ppocr的server版本模型进行推理
paddle版本 2.1.0, 2021.5.30晚上10点多下载。
[version.txt](https://github.com/PaddlePaddle/Paddle/files/6575118/version.txt)
错误：
gpu_mem为4000时，不管开启不开启use_tensorrt 都崩溃；
gpu_mem为1000时，开启use_tensorrt崩溃，不开启不崩溃。

**Comment by xinsuinizhuan** [comment]
当配置文件中gpu_mem为1000时，关闭use_tensorrt后，可以正常运行软件，但是识别和检测乱码，都不是检测的位置和识别的结果，而同样模型，cpu识别正常。使用的gpu为k2000
