### ISSUE TITLE
[QA test request] BF16 training test document

### ISSUE THREAD

**Issue by lidanqing-vv** [PaddlePaddle/Paddle#33240]
BF16 word2vec training testing and bug fixing is on going. Could you please according following documents, test and generate word2vec benchmark model FP32 training logs. So that we could use it as reference for word2vec BF16 training accuracy comparison. Thank you very much !

**Comment by lidanqing-intel** [comment]
Procedure to run word2vec training fp32 CPU version:

 
First clone the repo https://github.com/PaddlePaddle/PaddleRec.git
cd models/recall/word2vec/benchmark

 

Download the test data
./benchmark_data.sh

 

Run FP32 training
python -u ../../../../tools/static_ps_trainer.py -m benchmark.yaml

**Comment by lidanqing-vv** [comment]
[QA_word2vec_FP32_naive_training_reproduction.md](https://github.com/PaddlePaddle/Paddle/files/6595485/QA_word2vec_FP32_naive_training_reproduction.md)
@wzzju @OliverLPH Hi I upload the QA test doc for word2vec benchmark model FP32 training. We did same steps on our 6271 and the training is WIP. Please Baidu QA start the training, so if any issues we could find it earlier and solve them earlier. Thank you very much!

If anything unclear in this doc, let me know. But there should not be, because I started our training following it too. Thanks !

**Comment by Zeref996** [comment]
hello,
https://dubox.com/s/16ZOljv34Q_gKJuRHyP7XhA 
You can get partly log at this link.

![image](https://user-images.githubusercontent.com/53218160/121526225-c1dfb480-ca2b-11eb-9850-25f3967d561b.png)

**Comment by Zeref996** [comment]
hello,

https://pan.baidu.com/s/1okdqNOFT4M4ZQrvJFyE4zg  
Code: f7pt 

You can get epoch_8 log at the link.

**Comment by lidanqing-vv** [comment]
Hi
 收到，非常感谢！可以停止训练了，这些对我们来说对比够用了。

Best regards,
Danqing
