### ISSUE TITLE
paddle和torch的对齐问题

### ISSUE THREAD

**Issue by Leiyi-HU** [PaddlePaddle/Paddle#33254]
paddlepaddle:2.02;
env:gpu;
cuda:10.1;

paddle里的CE函数要将labels和inputs转换成int_64t有点麻烦，可以还有其他地方的数据类型有些混乱，可以基本统一成float32吗？
然后，torch.tensor.contiguous应该替换成paddlde的哪个函数呢？

**Comment by joey12300** [comment]
1. CE函数里 inputs的类型为float32或float64，不需要转换。labels应该是必须要int_64t类型的。`其他地方的数据类型有些混乱`是指？可以使用set-default-dtype设置默认数据类型。 （https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/set_default_dtype_cn.html#set-default-dtype）
2. paddle的tensor都是连续分布的内存方式，所以不需要contiguous函数。目前不存在paddle版本的contiguous函数。
