### ISSUE TITLE
请问paddle中有关于InplaceABNSync 的复现吗

### ISSUE THREAD

**Issue by DongChenwei2000** [PaddlePaddle/Paddle#33266]
我在复现pytorch的论文时，pytorch中使用了InplaceABNSync 这个模块，paddle中是否有其替代呢？

**Comment by joey12300** [comment]
你好，目前paddle只支持静态图版本的inplace abn接口，可以参考https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/fluid/layers/inplace_abn_cn.html#inplace-abn

**Comment by DongChenwei2000** [comment]
> 你好，目前paddle只支持静态图版本的inplace abn接口，可以参考https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/fluid/layers/inplace_abn_cn.html#inplace-abn

在动态图中是否有其替代呢？

**Comment by joey12300** [comment]
@553548793 目前暂时还没有。
