### ISSUE TITLE
在预测的时候出现training警告

### ISSUE THREAD

**Issue by yeyupiaoling** [PaddlePaddle/Paddle#33263]
- PaddlePaddle 2.1.0

预测代码：https://github.com/yeyupiaoling/PPASR/blob/master/infer.py

我已经设置`model.eval()`了，怎还是有这个警告？

然后我也已经加载模型了，但是模型输出的每次都不一样，输入数据完全一致的。
```
E:\ProgramData\Anaconda3\envs\PaddlePaddle2.0\lib\site-packages\paddle\nn\layer\norm.py:641: UserWarning: When training, we now always track global mean and variance.
  "When training, we now always track global mean and variance.")
```

**Comment by joey12300** [comment]
您好，试试把model.eval()放到infer函数里

**Comment by yeyupiaoling** [comment]
@joey12300 谢谢回答，解决了，是模型结构的问题，我只用的是lis存储模型，在forward中循环拿出来，这是错误的。我用nn.LayerList(conv_stacks)封装一下就好了。

**Comment by Jaimefight** [comment]
可以看看你具体是怎么改的么

**Comment by yeyupiaoling** [comment]
就是上面回复的那样，nn.LayerList(conv_stacks)封装list模型

**Comment by Jaimefight** [comment]
nn.LayerList(conv_stacks)封装list模型具体是怎么操作呀，小白不是很懂，谢谢大佬指点

**Comment by yeyupiaoling** [comment]
就是这样，我一开始是`self.rnn = list()`，改成下面这样就可以了。每个项目情况不一样，不知道是不是你的也是因为这个原因。
```
        self.rnn = nn.LayerList()
        self.output_dim = h_size
        self.use_gru = use_gru
        self.num_rnn_layers = num_rnn_layers
        self.rnn.append(RNNForward(rnn_input_size=i_size, h_size=h_size, use_gru=use_gru))
```
