### ISSUE TITLE
在docker中运行分布式训练出错

### ISSUE THREAD

**Issue by amenua** [PaddlePaddle/Paddle#33270]
- 训练信息
    1）多机，多卡
    2）GPU：一台T4一台P4
- 问题描述：两台机器不使用docker，多机多卡分布式运行能够正常训练，两台机器使用同样镜像，在docker里面使用单机多卡paddle.distributed.launch启动能够正常运行，但是当两台机器联合起来均在docker中运行就会报nccl的错误，报错信息如下
![图片](https://user-images.githubusercontent.com/20007401/120327151-07113180-c31c-11eb-8f5f-c7deae61bb2e.png)

**Comment by joey12300** [comment]
可能是启动的docker容器没有打开通信？先保证docker容器之间能互相ping通，再看看多机训练能否运行

**Comment by amenua** [comment]
> 可能是启动的docker容器没有打开通信？先保证docker容器之间能互相ping通，再看看多机训练能否运行

容器应该是通的，我启动容器的时候加了--net=host指令，如果不通会显示一直在等待节点ready的

**Comment by sandyhouse** [comment]
运行前 export NCCL_DEBUG=INFO看看，报错的尽量贴全一点报错信息。

**Comment by amenua** [comment]
> 运行前 export NCCL_DEBUG=INFO看看，报错的尽量贴全一点报错信息。
@sandyhouse 
![111](https://user-images.githubusercontent.com/20007401/120437628-e2b46400-c3b2-11eb-8691-a86ab24f9dd7.png)
看着是访问被拒绝了，我使用的是nvidia-docker run --security-opt seccomp:unconfined --net=host的配置启动的docker，跟启动命令有关系么？

**Comment by sandyhouse** [comment]
可以ping一下相应的地址，看看网络是否互通。

**Comment by amenua** [comment]
> 可以ping一下相应的地址，看看网络是否互通。

是通的

**Comment by sandyhouse** [comment]
是否存在端口占用呢？即warning信息中需要连接的端口被别的进程占用？

**Comment by amenua** [comment]
> 是否存在端口占用呢？即warning信息中需要连接的端口被别的进程占用？

确认过了，端口也没有占用，我这里试了下有的机器可以，有的不行，怀疑跟防火墙之类的设置有关
