### ISSUE TITLE
训练的时候报错SystemError: (Fatal) Blocking queue ...

### ISSUE THREAD

**Issue by Jeremy-lf** [PaddlePaddle/Paddle#33272]
SystemError: (Fatal) Blocking queue is killed because the data reader raises an exception.
  [Hint: Expected killed_ != true, but received killed_:1 == true:1.] (at D:\v2.0.2\paddle\paddle/fluid/operators/reader/blocking_queue.h:158)

完全按照官网的实例来学习的，却跑不通
![image](https://user-images.githubusercontent.com/45171399/120340177-58bfb900-c328-11eb-9e3e-259ed0441781.png)

![image](https://user-images.githubusercontent.com/45171399/120340033-3b8aea80-c328-11eb-8900-9d6b59340114.png)

===============================================

更新，我把标签弄成一个整数了，没有办法再astype更改类型了

**Comment by joey12300** [comment]
请问你的paddle版本环境多少？详细的测试代码是怎样的？
