### ISSUE TITLE
explicit memory efficient tensor reshaping (`View`)

### ISSUE THREAD

**Issue by Pzoom522** [PaddlePaddle/Paddle#33306]
Hi Team,

I'm using Paddle v2.1. According to your [changelog](https://www.paddlepaddle.org.cn/documentation/docs/en/release_note_en.html),

> Inplace Operation: Add the inplace operation to reduce the memory consumption and improve performance, including View strategy, and 12 inplace APIs.

It would be great to know how to **explicitly** use the Paddle equivalent of `torch.view`!

**Comment by wawltor** [comment]
You could use the reshape api will the same the view  in the version of  paddlepaddle 2.1 https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/reshape_cn.html#reshape

**Comment by Pzoom522** [comment]
Thanks for your reply. But it's unclear on the doc whether the operation is **inplace** or will make a Tensor copy in the static graph mode.

**Comment by wawltor** [comment]
> Thanks for your reply. But it's unclear on the doc whether the operation is **inplace** or will make a Tensor copy in the static graph mode.

In the static mode，will not use the **inplace** mode， just work in dygrpah mode

**Comment by Pzoom522** [comment]
Do we have equivalent of `torch.view` (inplace) in the static mode?

**Comment by wawltor** [comment]
> Do we have equivalent of `torch.view` (inplace) in the static mode?
I'm sorry，we will not have the api in the static mode. In the PaddlePaddle 2.0 version，we just  recommend user to use the dygraph mode，and we will not upgrade the static mode .

**Comment by Pzoom522** [comment]
That's fine. Just one more thing: is it possible to briefly explain why you "just recommend user to use the dygraph mode"? Thanks.

**Comment by Pzoom522** [comment]
> That's fine. Just one more thing: is it possible to briefly explain why you "just recommend user to use the dygraph mode"? Thanks.

I believe `dygraph` is more efficient, so this recommendation seems weird...

**Comment by wawltor** [comment]
> > That's fine. Just one more thing: is it possible to briefly explain why you "just recommend user to use the dygraph mode"? Thanks.
> 
> I believe `dygraph` is more efficient, so this recommendation seems weird...
_^^_  This is my personal advise，my reason as follows
1. Just as you have said，the efficient is the most import reason，we except to improve the experience in the process of coding.
2. In the PaddlePaddle 2.0 version，we designed the DL framework under the dygraph mode,  we design the new apis, the new models, the new inferences framework, and the new features，those just worked better in the dygraph mode.
3. As the NLP developer, I used the dygraph mode in my work,  it is cool.

**Comment by wawltor** [comment]
> > That's fine. Just one more thing: is it possible to briefly explain why you "just recommend user to use the dygraph mode"? Thanks.
> 
> I believe `dygraph` is more efficient, so this recommendation seems weird...



_^^_  This is my personal advise，my reason as follows
1. Just as you have said，the efficient is the most import reason，we except to improve the experience in the process of coding.
2. In the PaddlePaddle 2.0 version，we designed the DL framework under the dygraph mode,  we design the new apis, the new models, the new inferences framework, and the new features，those just worked better in the dygraph mode.
3. As the NLP developer, I used the dygraph mode in my work,  it is cool.

**Comment by Pzoom522** [comment]
My apologies for the typo. I wanted to say "the static graph mode" is more efficient in terms of computational speed (or not?)

**Comment by wawltor** [comment]
In the 2.0 version, we test the speed between dygraph mode and static mode in some models, there's little difference. Of course, the static mode had the advantage in the speed，and we have  many challenges in the dygraph mode， but we have some plans to speed up.

**Comment by Pzoom522** [comment]
Thanks a lot for your help & info
