### ISSUE TITLE
训练过程中无法自动回收显存

### ISSUE THREAD

**Issue by wuxianshen** [PaddlePaddle/Paddle#33309]
将每一轮训练、验证的过程分别封装到函数中，但是训练使用的显存在训练结束后不释放：
![image](https://user-images.githubusercontent.com/21985528/120498416-c71c7e00-c3f1-11eb-94ee-a7aadb056ba4.png)

第一次执行完train_epoch后，显存占用7.5G，执行valid_epoch后显存占用12G，感觉是train_epoch的显存没有释放？
![image](https://user-images.githubusercontent.com/21985528/120498637-f4692c00-c3f1-11eb-83bc-8250714dbc93.png)

![image](https://user-images.githubusercontent.com/21985528/120498616-f03d0e80-c3f1-11eb-85e1-251e80a7350b.png)

类似的代码在Pytorch中的实现没有这个问题，执行valid_epoch时不会多分配显存

**Comment by wawltor** [comment]
在validation的过程中，按照上述的代码也会生成反向的过程，显存不会释放，如果想在validation的过程中释放显存，需要加一个no_grad操作，这样就不会生成反向过程, 具体的api如下
https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/no_grad_cn.html#no-grad

**Comment by wuxianshen** [comment]
哦哦明白了，您这个解答了我另一个问题；
还有就是，我其实想问的是，train的过程封装到函数里，函数结束了，里面变量生命周期结束后，会自动释放吗，能否通过某种方式，使得这样写train的过程时，调用完一次这个函数，GPU就释放掉，下个epoch调用train时再分配？

**Comment by wawltor** [comment]
> 哦哦明白了，您这个解答了我另一个问题；
> 还有就是，我其实想问的是，train的过程封装到函数里，函数结束了，里面变量生命周期结束后，会自动释放吗，能否通过某种方式，使得这样写train的过程时，调用完一次这个函数，GPU就释放掉，下个epoch调用train时再分配？

这里的显存主要是包括了三个方面的显存开销
1.  parameter
2. 前向变量
3. 反向变量

parameter是全局的变量，因此是在整个程序结束后才释放；前向变量是反向执行完的时候会释放，反向变量是在下一轮前向开始的时候才会释放

**Comment by wuxianshen** [comment]
好的明白了，谢谢您哈

**Comment by infrontofme** [comment]
你好，最近刚开始使用paddlepaddle，也遇到这样的问题，使用paddle训练结束发现显卡显存还被占用着，并未释放，请问是什么原因导致，怎样解决？

**Comment by wawltor** [comment]
> 你好，最近刚开始使用paddlepaddle，也遇到这样的问题，使用paddle训练结束发现显卡显存还被占用着，并未释放，请问是什么原因导致，怎样解决？

有可能是任务异常退出，显存没有来得及释放
