### ISSUE TITLE
L1Decay报错问题

### ISSUE THREAD

**Issue by btobab** [PaddlePaddle/Paddle#33349]
1）PaddlePaddle版本：2.0.2
    4）系统环境：aistudio
![1](https://user-images.githubusercontent.com/66876429/120760499-c2b5a980-c546-11eb-8ac3-c352efe50318.jpg)
![2](https://user-images.githubusercontent.com/66876429/120760375-9f8afa00-c546-11eb-80ae-343e91dbfd50.jpg)

**Comment by btobab** [comment]
设置L1Decay没法运行，但改成L2Decay就可以跑

**Comment by btobab** [comment]
如果要看具体的代码，[这是项目地址](https://aistudio.baidu.com/aistudio/projectdetail/1542163)

**Comment by pangyoki** [comment]
你好，paddle 2.0.2确实会有这个问题。是因为 L1Decay方法里的scale方法的输入“X”和输出“Out”相同，但是缺少对inplace的相关处理导致的。
这个问题现在已经修复了，可以使用2.1版本的paddle试试看。

**Comment by btobab** [comment]
好哒好哒，谢谢大佬，但是目前2.1好像也有不少bug~
大佬加油修一下2.1的bug~

**Comment by pangyoki** [comment]
好的，还有问题可以反馈出来，谢谢。

**Comment by btobab** [comment]
好的~
