### ISSUE TITLE
Windows使用DataLoader在完成最后一个batch之后，并没有跳出循环，而是直接卡死

### ISSUE THREAD

**Issue by yeyupiaoling** [PaddlePaddle/Paddle#33341]
- PaddlePaddle 2.1.0
 - Windows 10

Windows使用DataLoader在完成最后一个batch之后，并没有跳出循环，而是直接卡死。没有保存信息，只有下面这个条信息。在Ubuntu是正常的，并不会出现这个的错误。

```
进程已结束，退出代码为 -1073741819 (0xC0000005)
```

代码：https://github.com/yeyupiaoling/PPASR/blob/248b60a82db71d134c5cf113859dcb9ef7c9e4d5/eval.py#L41-L46

**Comment by heavengate** [comment]
没太理解，`进程已结束，退出代码为 -1073741819 (0xC0000005)` 这个信息看着是进程已经退出了？还是进程卡死了呢

**Comment by yeyupiaoling** [comment]
@heavengate 就卡死退出的。例如下面这个循环，理论来说循环结束之后，应该要跳出循环，但是它没有，执行最后一个循环之后，就卡死了。Windows才会，Ubuntu不会。

```
@paddle.no_grad()
def evaluate(model, test_loader, vocabulary):
    c = []
    for inputs, labels, input_lens, _ in tqdm(test_loader()):
        # 执行识别
        outs, _ = model(inputs, input_lens)
        outs = paddle.nn.functional.softmax(outs, 2)
        # 解码获取识别结果
        out_strings = greedy_decoder_batch(outs.numpy(), vocabulary)
        labels_str = labels_to_string(labels.numpy(), vocabulary)
        for out_string, label in zip(*(out_strings, labels_str)):
            # 计算字错率
            c.append(cer(out_string, label) / float(len(label)))
    c = float(sum(c) / len(c))
    return c
```

**Comment by zhwesky2010** [comment]
@yeyupiaoling 你好，请问 dataset/manifest.test是如何创建的，是训练的dataloader也会出问题还是评估时的dataset/manifest.test对应dataloader也会出问题呢？

**Comment by zhwesky2010** [comment]
@yeyupiaoling 你好，我这边复现时是最后一个batch时会出现计算错误，你这边会出现这个吗？ ![image](https://user-images.githubusercontent.com/52485244/121282398-02e0a780-c90c-11eb-860d-c3f5642e35a0.png)

**Comment by yeyupiaoling** [comment]
@zhouwei25 不会呀，我在本地再测一下

**Comment by yeyupiaoling** [comment]
@zhouwei25 哦哦，明白了，因为max_prob_list识别长度为零，导致除0错误。我改一下
```
    score = 0
    if len(max_prob_list) > 0:
        score = float(sum(max_prob_list) / len(max_prob_list)) * 100.0
```

**Comment by yeyupiaoling** [comment]
@zhouwei25 我推了新代码。

**Comment by zhwesky2010** [comment]
@yeyupiaoling 只有评估时会出问题吗

**Comment by yeyupiaoling** [comment]
@zhouwei25 在windows上，只要是一个循环获取数据的，都会在最后一个循环结束之后，卡死。不管是评估还是训练。

**Comment by yeyupiaoling** [comment]
@zhouwei25 您可以在直接执行评估eval()，因为评估数据少，可以快速复现问题。

**Comment by yeyupiaoling** [comment]
@zhouwei25 有没有复现问题？

**Comment by yeyupiaoling** [comment]
@zhouwei25 循环完成之后，硬盘的写入突然增大，一段时间后就挂掉了。硬盘的空间是足够的。

```
[2021-06-21 11:28:50.276859] Train epoch 0, batch 0, loss: 36768.140625
100%|██████████| 9/9 [00:31<00:00,  2.85s/it]
进程已结束，退出代码为 -1073741819 (0xC0000005)
```

![微信截图_20210621113005](https://user-images.githubusercontent.com/26297768/122703428-213b9100-d284-11eb-96b2-0160db574d77.png)

**Comment by zhwesky2010** [comment]
@yeyupiaoling 请问显卡类型、CUDA、Python版本是多少

**Comment by yeyupiaoling** [comment]
@zhouwei25 显卡2080ti，CUDA 10.2， Python 3.7

**Comment by zhwesky2010** [comment]
@yeyupiaoling 您好，这个问题可能和 https://github.com/PaddlePaddle/PaddleDetection/issues/3558 类似，在最后一个batch退出，目前定位到问题是：``在某些Windows机器上，Dataloader在C++端，抛出任何类型的异常，都会直接退出，无法被pybind捕获并处理。这个问题只在部分Windows机器上出现，而且必须是dataloader这个地方，其他地方抛出的异常，可以被正常处理，这个问题 在我们内部的机器无法测出来，因此推测是环境上某些差异的问题。``

**Comment by yeyupiaoling** [comment]
哦哦，好的。

**Comment by minhoooo1** [comment]
请问这个问题解决了嘛？
