### ISSUE TITLE
onnx2paddle inference with FP16

### ISSUE THREAD

**Issue by tingggggg** [PaddlePaddle/Paddle#33348]
目前把手邊的onnx模型轉換成paddle後可以使用 paddle-TensorRT 進行(FP32 F16 INT8)的預測

想詢問不使用 paddle-TensorRT 的情況下，要如何做FP16的預測

**Comment by Superjomn** [comment]
你好，目前预测上，NV GPU 的 FP16 只有 Paddle-TensorRT 支持，其他模式下暂时还不支持

**Comment by tingggggg** [comment]
感謝解答
