### ISSUE TITLE
打包问题

### ISSUE THREAD

**Issue by ANewAnonymous** [PaddlePaddle/Paddle#33367]
使用pyinstaller打包后发现程序目录下生成了paddle/fluid/core_avx.pyd文件，发现该文件大小为1.23GB。这实在是太大了 是否有缩减的方法

**Comment by zhwesky2010** [comment]
@ANewAnonymous 这个是Paddle所有C++文件对应生成的动态库，这个大小是正常的

**Comment by tianshuo78520a** [comment]
Paddle暂时没有办法减少这个体积，可以试试用nvprune工具减少
