### ISSUE TITLE
这里做了一个不合理的假设，认为所有的HOME目录都是可读写的

### ISSUE THREAD

**Issue by mikeshi80** [PaddlePaddle/Paddle#33364]
https://github.com/PaddlePaddle/Paddle/blob/1315e3a1e412cb9c02df84dae1c85771ffd49a7c/python/paddle/dataset/common.py#L32-L33

这里是设定了之后创建cache目录的路径，并在之后会强行创建。

实际上，在某些环境，比如AWS的 Lambda环境中（因为现在Lambda支持容器镜像了，所以可以以容器的形式创建Lambda函数），用户目录是只读的，它额外提供了`/tmp`目录作为临时读写目录。

我为了能在Lambda中使用，只能在Dockerfile中使用sed将`HOME`改为了`/tmp`。

修改方案：

1. 可以加入环境变量，使得用户有机会在不修改代码的情况下，指定`DATA_HOME`目录。
2. 实际上，很多时候我们只是单纯的进行推理，这个时候，即使整个环境都是只读的应该也不影响使用才对。所以将必须创建DATA目录的逻辑进行适当修改才更通用。

**Comment by mikeshi80** [comment]
没人鸟的吗？

**Comment by frankwhzhang** [comment]
您好 感谢您的建议 会联系相关的同学进行修改~

**Comment by saicoco** [comment]
今天依旧存在这样的问题

**Comment by dc-cheny** [comment]
2022年依然存在这个问题

**Comment by luotao1** [comment]
close by #45229, thanks for @dc-cheny

**Comment by yier2333** [comment]
2023年了依旧存在这个问题，这么简单的问题，居然不允许用户使用os.environ设置缓存目录也是醉了，为啥不愿意修复这个bug不理解
