### ISSUE TITLE
 Cannot enable P2P access from 0 to 1

### ISSUE THREAD

**Issue by GuoQuanhao** [PaddlePaddle/Paddle#33362]
![image](https://user-images.githubusercontent.com/49911294/120898631-40200d80-c65e-11eb-8ce7-7eea0128856e.png)
这是正确安装的吗，`Cannot enable P2P access from 0 to 1`是什么意思

**Comment by jerrywgz** [comment]
这个信息只是warning，不会对训练造成影响
