### ISSUE TITLE
status of DLPack support

### ISSUE THREAD

**Issue by Pzoom522** [PaddlePaddle/Paddle#33361]
Dear developers, 

In https://github.com/PaddlePaddle/Paddle/pull/20025, https://github.com/PaddlePaddle/Paddle/pull/20039, and https://github.com/PaddlePaddle/Paddle/pull/20611 and  I notice the team has been working on the interoperability with DLPack tensor structures. See also (relevant discussions): https://github.com/PaddlePaddle/Paddle/pull/22021, https://github.com/PaddlePaddle/Paddle/issues/32765.

Nevertheless, on the doc I cannot find any info on the status of this line of effort, e.g., __can__ we now perform (bidirectional) on-GPU conversions between Paddle and DLPack tensors (and __how__)?

Many thanks!

**Comment by jzhang533** [comment]
We have this functionality in early versions: [1.2 release](https://github.com/PaddlePaddle/Paddle/releases/tag/v1.2.0).
Although these APIs are [still available](https://aistudio.baidu.com/aistudio/projectdetail/1969224), but these are now considered as unofficial APIs. We will review this functionality and provide these functionality through official APIs, may be in our next release. 😃

**Comment by Pzoom522** [comment]
Thanks a lot for your reply. These APIs will be super useful. Looking forward to them!

Also, is it possible to get some updates on https://github.com/PaddlePaddle/Paddle/issues/32765? If the bidirectional conversion between `Tensor` and `Lod_tensor` can be achieved, then we can easily hack the old-but-unofficial `DLPack` APIs for `Tensor`.
