### ISSUE TITLE
Paddle多卡训练机制

### ISSUE THREAD

**Issue by GuoQuanhao** [PaddlePaddle/Paddle#33389]
我在训练模型时，利用单卡训练的batch_size=16（再大会爆显存，单卡显存占用7G/11G），当我调整为多卡训练时，我的batch_size还是只能设置为16，但我的四张显卡都占用7G/11G，这表明我一次训练的batchsize是64吗

**Comment by frankwhzhang** [comment]
可以贴一下详细代码和相关信息嘛

**Comment by ForFishes** [comment]
您好，你所说的是正确的，数据并行的global_batch_size = local_batch_size * cards。但是这里需要注意的是，每张卡输入的数据应该是不一样的，才能保证数据并行，推荐使用Dataset, DistributedBatchSampler 来保证数据在每张卡的输入不同。

https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/io/DistributedBatchSampler_cn.html#distributedbatchsampler

**Comment by GuoQuanhao** [comment]
你好，DistributedBatchSampler需要与DataLoader一起用吗
```python
train_loader = DistributedBatchSampler(
            train_dataset, batch_size=micro_batch_size, shuffle=True
)
```
```python
 train_loader = DataLoader(
            DistributedBatchSampler(train_dataset, batch_size=micro_batch_size, shuffle=True), batch_size=micro_batch_size, shuffle=True,
            num_workers=args.workers, drop_last=False)
```
我想知道`DistributedBatchSampler`具体用法示例，文档给的信息太少了

**Comment by GuoQuanhao** [comment]
> 你好，DistributedBatchSampler需要与DataLoader一起用吗
> 
> ```python
> train_loader = DistributedBatchSampler(
>             train_dataset, batch_size=micro_batch_size, shuffle=True
> )
> ```
> 
> ```python
>  train_loader = DataLoader(
>             DistributedBatchSampler(train_dataset, batch_size=micro_batch_size, shuffle=True), batch_size=micro_batch_size, shuffle=True,
>             num_workers=args.workers, drop_last=False)
> ```
> 
> 我想知道`DistributedBatchSampler`具体用法示例，文档给的信息太少了

具体应该咋写呀

**Comment by GuoQuanhao** [comment]
> > 你好，DistributedBatchSampler需要与DataLoader一起用吗
> > ```python
> > train_loader = DistributedBatchSampler(
> >             train_dataset, batch_size=micro_batch_size, shuffle=True
> > )
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ```python
> >  train_loader = DataLoader(
> >             DistributedBatchSampler(train_dataset, batch_size=micro_batch_size, shuffle=True), batch_size=micro_batch_size, shuffle=True,
> >             num_workers=args.workers, drop_last=False)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 我想知道`DistributedBatchSampler`具体用法示例，文档给的信息太少了
> 
> 具体应该咋写呀

train_loader = DataLoader(dataset, batch_sampler=DistributedBatchSampler(dataset, batch_size=64), num_workers=0)这样？？

**Comment by ForFishes** [comment]
类似这种 dataset + DistributedBatchSampler + dataloader 的组合方式

```python
    train_data = GPT2Dataset(
        file_path=input_path,
        worker_index=worker_index,
        num_samples=args.batch_size * args.max_steps * worker_num,
        eod_id=eod_id,
        seed=args.seed)
        # max_seq_len=args.max_seq_len)
    train_batch_sampler = paddle.io.DistributedBatchSampler(
        train_data,
        batch_size=args.batch_size,
        shuffle=True,
        drop_last=True,
        num_replicas=args.dp_degree,
        rank=worker_index)

    train_data_loader = DataLoader(
        dataset=train_data,
        batch_sampler=train_batch_sampler,
        num_workers=0,
        worker_init_fn=worker_init,
        collate_fn=Tuple(Stack(), Stack(), Stack(), Stack(), Stack()))
```
