### ISSUE TITLE
自定义C++外部算子 创建的tensor是随机初始化的吗？

### ISSUE THREAD

**Issue by kk125678** [PaddlePaddle/Paddle#33380]
如题，如果是随机初始化能不能加个初始化为常量API

**Comment by frankwhzhang** [comment]
有具体的信息和需求可以贴一下嘛

**Comment by chenwhql** [comment]
1. 首先，创建Tensor的时候是没有初始化的，需要调用mutable_data<T>申请数据区，而这个申请出来的数据区是没有去初始化的，就是裸内存，一定得赋值之后再使用！否则可能会有问题
2. 目前paddle没有C++的Tensor API，我们正在统一规划C++ Tensor计算库及其API的工作，也内部讨论过，短期之内不会再增加临时的C++初始化API了，意义不大。这个有待于统一规划，新的体系成型后，会包含初始化API在内的丰富计算API，届时自定义Op的编写会更加方便，敬请期待
