### ISSUE TITLE
Do we need class `InferShapeContext` ?

### ISSUE THREAD

**Issue by wangkuiyi** [PaddlePaddle/Paddle#3342]
At https://github.com/PaddlePaddle/Paddle/blob/e31a469ee09e8ab5f6048eb69f71ca89e9dbbf97/paddle/framework/operator.h#L237, class `InferShapeContext` is derived from `OperatorContext` but adds nothing.  Do we really need `InferShapeContext`, or should we use `OperatorContext` with `OperatorBase::InferShape`?

**Comment by jacquesqiao** [comment]
I will merge them today,  use infercontext
