### ISSUE TITLE
paddle 2.1 文档问题。paddle.nn.Linear 对其参数初始化的文档描述 与其实际使用的初始化方法 不一致

### ISSUE THREAD

**Issue by 15814** [PaddlePaddle/Paddle#33421]
[我查看的文档链接](https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/nn/Linear_cn.html)

<img width="837" alt="image" src="https://user-images.githubusercontent.com/13784723/121139667-94e4a380-c86b-11eb-8bfe-63e180884aef.png">

文档里说  Linear 这个类 采用的默认参数初始化方式是全零初始化，但实际效果并不是。同时我查看了相关的源码，似乎其现在采用的是 Xavier 初始化方式。希望开发者能帮忙确认，提升文档。

**Comment by heavengate** [comment]
好的，感谢反馈，这是个文档错误，我们修复一下~

**Comment by jzhang533** [comment]
@heavengate 英文的也有这个问题。
