### ISSUE TITLE
avx_supported function in fluid core fails on linux when called from systemd context

### ISSUE THREAD

**Issue by kyoussef** [PaddlePaddle/Paddle#33433]
I had paddleocr example served from a Flask application on Ubuntu 18.04. The Flask application was hosted on Gunicorn and added as a systemd service. 
When starting the service, it was failing due to issue "modulenotfounderror: no module named 'paddle.fluid.core_noavx'". After analyzing the issue, it turned out that paddle was not detecting the support of AVX on the machine, when it is actually supported. 

It turned out that paddle.fluid.core avx_supported function is reading the avx support using this method. 

has_avx = os.popen('cat /proc/cpuinfo | grep -i avx').read() != ''

When running from the systemd context, the above function is failing, when looked at the syslog I found. "/bin/sh 1: cat not found" same for grep. I had to change the line above to use absolute path to the command instead. 

has_avx = os.popen('/bin/cat /proc/cpuinfo | /bin/grep -i avx').read() != ''

Wanted to share my finding, not sure if others faced the same issue. Not sure if there is another way to solve this when setting up the paddle or the systemd service.

**Comment by heavengate** [comment]
你好，应该是你机器不支持avx指令集但是安装的是带avx的paddle版本，可以卸载之后重新安装一下paddle试下，或者使用https://www.paddlepaddle.org.cn/documentation/docs/zh/install/Tables.html#whl-release 这里的版本试下

**Comment by kyoussef** [comment]
The machine does support the AVX, as I mentioned above it worked when I fixed the function that checks for the avx on the machine. Please double check my original post.

**Comment by zengzheng1** [comment]
Your environment variable is are set incorrectly. Please print "os.environ['PATH']",  "/usr/bin" should be in the output. 
环境变量PATH被设置错误，"/usr/bin" 应该被包含在 "os.environ['PATH']"的执行结果中。
