### ISSUE TITLE
源码编译

### ISSUE THREAD

**Issue by butterniu** [PaddlePaddle/Paddle#33449]
系        统：openeuler  arm64
编译命令：make TARGET=ARMV8 -j4
错误     ：
c++: error: unrecognized command line option ‘-m64’
make[2]: *** [paddle/fluid/platform/CMakeFiles/flags.dir/build.make:63: paddle/fluid/platform/CMakeFiles/flags.dir/flags.cc.o] Error 1
make[2]: Leaving directory '/root/tools/Paddle/build'
make[1]: *** [CMakeFiles/Makefile2:4024: paddle/fluid/platform/CMakeFiles/flags.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
make[2]: Leaving directory '/root/tools/Paddle/build'
make[2]: Entering directory '/root/tools/Paddle/build'
[  3%] Performing build step for 'extern_warpctc'
[  3%] Building CXX object paddle/fluid/platform/CMakeFiles/cudnn_workspace_helper.dir/cudnn_workspace_helper.cc.o
make[3]: Entering directory '/root/tools/Paddle/build/third_party/warpctc/src/extern_warpctc-build'
c++: error: unrecognized command line option ‘-m64’
make[2]: *** [paddle/fluid/platform/CMakeFiles/cudnn_workspace_helper.dir/build.make:63: paddle/fluid/platform/CMakeFiles/cudnn_workspace_helper.dir/cudnn_workspace_helper.cc.o] Error 1

请问我该如何解决或避免这种问题的发生呢

**Comment by butterniu** [comment]
系        统：openeuler  arm64
编译命令：make TARGET=ARMV8 -j4
错误     ：
c++: error: unrecognized command line option ‘-m64’
make[2]: *** [paddle/fluid/platform/CMakeFiles/flags.dir/build.make:63: paddle/fluid/platform/CMakeFiles/flags.dir/flags.cc.o] Error 1
make[2]: Leaving directory '/root/tools/Paddle/build'
make[1]: *** [CMakeFiles/Makefile2:4024: paddle/fluid/platform/CMakeFiles/flags.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
make[2]: Leaving directory '/root/tools/Paddle/build'
make[2]: Entering directory '/root/tools/Paddle/build'
[  3%] Performing build step for 'extern_warpctc'
[  3%] Building CXX object paddle/fluid/platform/CMakeFiles/cudnn_workspace_helper.dir/cudnn_workspace_helper.cc.o
make[3]: Entering directory '/root/tools/Paddle/build/third_party/warpctc/src/extern_warpctc-build'
c++: error: unrecognized command line option ‘-m64’
make[2]: *** [paddle/fluid/platform/CMakeFiles/cudnn_workspace_helper.dir/build.make:63: paddle/fluid/platform/CMakeFiles/cudnn_workspace_helper.dir/cudnn_workspace_helper.cc.o] Error 1


请问我该如何解决或避免这种问题的发生呢

**Comment by sandyhouse** [comment]
有运行cmake命令吗？另外源码可参考https://www.paddlepaddle.org.cn/install/quick?docurl=/documentation/docs/zh/install/compile/linux-compile.html#anchor-0
