### ISSUE TITLE
加载预训练的embedding layer，和神经网络迭代过程中更新得到的embedding layer，我该如何单独对比两份embedding 结果的好坏呢？

### ISSUE THREAD

**Issue by chaihua483** [PaddlePaddle/Paddle#3346]
- rt

**Comment by Superjom** [comment]
可以通过t-SNE 这类可视化方法，或者用 word2vec里的简单方法：

女人 - 女孩 的词向量， 与 男人 - 男孩的词向量的cosim

找几个这样的pair，算平均分。

当然这个方法非常主观（宏观），具体评估还是按照你的任务走
