### ISSUE TITLE
paddle tensor transforms不支持超过3个维度的

### ISSUE THREAD

**Issue by pkuCactus** [PaddlePaddle/Paddle#33474]
为使您的问题得到快速解决，在建立Issues前，请您先通过如下方式搜索是否有相似问题:【搜索issue关键字】【使用labels筛选】【官方文档】

如果您没有查询到相似问题，为快速解决您的提问，建立issue时请提供如下细节信息：
- 标题：简洁、精准概括您的问题
- 版本、环境信息：
    1）PaddlePaddle版本：2.0.1
    2）CPU/GPU：NVIDIA V100
    3）系统环境：ubuntu16.04
    4）Python版本号 3.7

 a = paddle.rand((2,3,4,4))
b = a.transpose(3,2,1,0)
这只是一个示例的情况，在实际中我们可能有更高的维度的tensor需要交换其中的某两维，那么在paddle中就很难实现
请问有什么好的解决方案或者替代API吗
    a.transpose(3,2,1,0)
TypeError: transpose() takes from 2 to 3 positional arguments but 5 were given

**Comment by sandyhouse** [comment]
将参数作为列表或元组传入，参考https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/transpose_cn.html#transpose

**Comment by pkuCactus** [comment]
谢谢
