### ISSUE TITLE
Nvidia A100 bert 训练，安装paddle2.1后，bert qps问题

### ISSUE THREAD

**Issue by ykkk2333** [PaddlePaddle/Paddle#33485]
升级到paddle 2.1之后，Bert base 在A100上的qps从810上升到了1180，想了解下paddle2.1有对bert或相关的算子有特别的优化么

设备信息：
Nvidia A100-PCIE-40GB
CUDA Version：11.2
cudnn：8.04

**Comment by ceci3** [comment]
请问下是静态图还是动态图模型？训练还是预测呢？

**Comment by ykkk2333** [comment]
> 请问下是静态图还是动态图模型？训练还是预测呢？

静态图训练
