### ISSUE TITLE
机器翻译预测

### ISSUE THREAD

**Issue by q178** [PaddlePaddle/Paddle#33496]
paddle版本1.1
  InvalidArgumentError: Broadcast dimension mismatch. Operands could not be broadcast together with the shape of X = [2, 21, 1024] and the shape of Y = [2, 21, 512]. Received [1024] in X is not equal to [512] in Y at i:2.
      [Hint: Expected x_dims_array[i] == y_dims_array[i] || x_dims_array[i] <= 1 || y_dims_array[i] <= 1 == true, but received x_dims_array[i] == y_dims_array[i] || x_dims_array[i] <= 1 || y_dims_array[i] <= 1:0 != true:1.] (at /paddle/paddle/fluid/operators/elementwise/elementwise_op_function.h:169)

**Comment by ceci3** [comment]
看起来是要进行elementwise 操作的时候维度对不上，paddle版本用的是1.1嘛？

**Comment by q178** [comment]
感谢您的回复，我已经找到问题所在，是yaml文件里的参数被其他人改掉了



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: ceci3 ***@***.***&gt;
发送时间: 2021年6月10日 16:11
收件人: PaddlePaddle/Paddle ***@***.***&gt;
抄送: q178 ***@***.***&gt;, Author ***@***.***&gt;
主题: 回复：[PaddlePaddle/Paddle] 机器翻译预测 (#33496)





 
看起来是要进行elementwise 操作的时候维度对不上，paddle版本用的是1.1嘛？
