### ISSUE TITLE
使用PyInstalle打包paddle

### ISSUE THREAD

**Issue by ANewAnonymous** [PaddlePaddle/Paddle#33523]
打包后在本机cuda10.2下正常使用，cpu和gpu均可调用，在GTX 1650显卡下的cuda11.1上无法使用GPU，请问我应该这么做
paddle版本2.0

**Comment by ANewAnonymous** [comment]
我看到了他的报错信息:
RuntimeError: (PreconditionNotMet) The third-party dynamic library (cudnn64_7.dll) that Paddle depends on is not configured correctly. (error code is 126)
  Suggestions:
  1. Check if the third-party dynamic library (e.g. CUDA, CUDNN) is installed correctly and its version is matched with paddlepaddle you installed.
  2. Configure third-party dynamic library environment variables as follows:
  - Linux: set LD_LIBRARY_PATH by `export LD_LIBRARY_PATH=...`
  - Windows: set PATH by `set PATH=XXX; (at C:\home\workspace\Paddle_release\paddle\fluid\platform\dynload\dynamic_loader.cc:265)

**Comment by ANewAnonymous** [comment]
当我把cudnn64_7.dll加到环境里面后又出现报错:
RuntimeError: (PreconditionNotMet) The third-party dynamic library (cublas64_102.dll;cublas64_10.dll) that Paddle depends on is not configured correctly. (error code is 126)
  Suggestions:
  1. Check if the third-party dynamic library (e.g. CUDA, CUDNN) is installed correctly and its version is matched with paddlepaddle you installed.
  2. Configure third-party dynamic library environment variables as follows:
  - Linux: set LD_LIBRARY_PATH by `export LD_LIBRARY_PATH=...`
  - Windows: set PATH by `set PATH=XXX; (at C:\home\workspace\Paddle_release\paddle\fluid\platform\dynload\dynamic_loader.cc:265)

**Comment by ANewAnonymous** [comment]
cublas64_102.dll无法找到这个动态库，仅将cublas64_10.dll添加到了环境中 报错依旧，没有发生改变

**Comment by Shixiaowei02** [comment]
您好，怀疑 CUDA 安装不正确导致问题，请参考此问题的步骤尝试解决：
https://stackoverflow.com/questions/51111954/tensorflow-cant-find-cudart64-90-dll-even-though-it-is-installed-with-path-va
