### ISSUE TITLE
官网的paddle serving Docker安装方式下的docker 无法使用

### ISSUE THREAD

**Issue by heimao63531** [PaddlePaddle/Paddle#33525]
官网的paddle serving https://www.paddlepaddle.org.cn/tutorials/projectdetail/1555945 ，跟这上面的docker 安装，拉取镜像的时候报not found

 sudo docker pull hub.baidubce.com/paddlepaddle/serving:0.5.0-devel
Error response from daemon: manifest for hub.baidubce.com/paddlepaddle/serving:0.5.0-devel not found

![image](https://user-images.githubusercontent.com/11887111/121635981-cb176280-cab9-11eb-81e9-f61ff1578939.png)

**Comment by Shixiaowei02** [comment]
您好，此问题我们已发现，并正在修复。请换用 `registry.baidubce.com`
