### ISSUE TITLE
windows10 cpu python 本地部署报错

### ISSUE THREAD

**Issue by GaiHaoBeibei** [PaddlePaddle/Paddle#33520]
电脑相关配置
Paddle version: 2.1.0
Paddle With CUDA: False
OS: Windows 10
Python version: 3.7.0
CUDA version: None
cuDNN version: None
Nvidia driver version:  
CPU：英特尔 Core i7—6820HQ @2.70GHz 四核

该程序在ai studio cup 环境下可以正常运行
在本地python3.7编译器上运行python部署报错
报错内容如下
![image](https://user-images.githubusercontent.com/71703793/121633304-1d09b980-cab5-11eb-99e2-fbd4f2cfd5ca.png)

源代码

[手写数字识别.zip](https://github.com/PaddlePaddle/Paddle/files/6635906/default.zip)

模型文件
[手写数字模型.zip](https://github.com/PaddlePaddle/Paddle/files/6635908/default.zip)

测试图片
![0](https://user-images.githubusercontent.com/71703793/121633294-18450580-cab5-11eb-8b37-46339fbc1dbc.jpg)

**Comment by GaiHaoBeibei** [comment]
jhg

**Comment by winter-wang** [comment]
经和 GaiHaoBeibei 沟通，已确定是由于中文路径的问题，关闭该issue.
