### ISSUE TITLE
docker镜像中，使用执行paddle.fluid.install_check.run_check()时，出现错误

### ISSUE THREAD

**Issue by jucaowei** [PaddlePaddle/Paddle#33545]
为使您的问题得到快速解决，在建立Issue前，请您先通过如下方式搜索是否有相似问题:【搜索issue关键字】【使用labels筛选】【官方文档】

建立issue时，为快速解决问题，请您根据使用情况给出如下信息：
- 标题：请包含关键词“安装错误”/“编译错误”，例如“Mac编译错误”
- 版本、环境信息：
    1）PaddlePaddle版本：请提供您的PaddlePaddle版本号（如1.1）或CommitID
    2）CPU：请提供CPU型号，MKL/OpenBlas/MKLDNN/等数学库的使用情况
    3）GPU：请提供GPU型号，CUDA和CUDNN版本号
    4）系统环境：请说明系统类型、版本（如Mac OS 10.14）、Python版本
注：您可以通过执行[summary_env.py](https://github.com/PaddlePaddle/Paddle/blob/develop/tools/summary_env.py)获取以上信息。
- 安装方式信息：
1）pip安装/docker安装
2）本地编译：请提供cmake命令，编译命令
3）docker编译：请提供docker镜像，编译命令            
  特殊环境请注明：如离线安装等
- 复现信息：如为报错，请给出复现环境、复现步骤
- 问题描述：请详细描述您的问题，同步贴出报错信息、日志/代码关键片段

Thank you for contributing to PaddlePaddle.
Before submitting the issue, you could search issue in Github in case that there was a similar issue submitted or resolved before.
If there is no solution,please make sure that this is an installation issue including the following details:
**System information**
-PaddlePaddle version （eg.1.1）or CommitID
-CPU: including CPUMKL/OpenBlas/MKLDNN version
-GPU: including CUDA/CUDNN version
-OS Platform (eg. Mac OS 10.14)
-Python version
- Install method: pip install/install with docker/build from source(without docker)/build within docker
- Other special cases that you think may be related to this problem, eg. offline install, special internet condition 
Note: You can get most of the information by running [summary_env.py](https://github.com/PaddlePaddle/Paddle/blob/develop/tools/summary_env.py).   

**To Reproduce**
Steps to reproduce the behavior
**Describe your current behavior**
**Code to reproduce the issue**
**Other info / logs**

在registry.baidubce.com/paddlepaddle/paddle:2.1.0-gpu-cuda10.2-cudnn7镜像中，交互式命令下，paddle.fluid.install_check.run_check()出现

OSError: (External)  Cublas error, `CUBLAS_STATUS_NOT_INITIALIZED`. The cuBLAS library was not initialized.  (at /paddle/paddle/fluid/platform/cuda_helper.h:98)错误

**Comment by hong19860320** [comment]
麻烦分别执行下如下命令，把结果贴上来哈~

`
$ nvidia-smi

$ nvcc -V

$ echo $PATH

$ echo $LD_LIBRARY_PATH
`

**Comment by jucaowei** [comment]
![企业微信截图_2021061511
![企业微信截图_20210615112406](https://user-images.githubusercontent.com/20838823/121988049-459ef580-cdcc-11eb-945b-a0f38dd8215d.png)
2356](https://user-images.githubusercontent.com/20838823/121988033-39b33380-cdcc-11eb-895c-4202c9c007e7.png)
###

**Comment by jucaowei** [comment]
![企业微信截图_20210615112406](https://user-images.githubusercontent.com/20838823/121988196-7848ee00-cdcc-11eb-8bb1-b54209a5db8a.png)

**Comment by jucaowei** [comment]
即使实在driver api     runtime api   还有paddle版本都保持11.2    依然出现这样的报错

**Comment by weiluonika** [comment]
我和你遇到一样的问题了，请问你 解决了吗？

**Comment by jucaowei** [comment]
没有



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年7月1日(周四) 中午1:41
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [PaddlePaddle/Paddle] docker镜像中，使用执行paddle.fluid.install_check.run_check()时，出现错误 (#33545)




 
我和你遇到一样的问题了，请问你 解决了吗？
