### ISSUE TITLE
CUDA device is not set properly

### ISSUE THREAD

**Issue by mrlihellohorld** [PaddlePaddle/Paddle#33540]
cuda:  Driver Version: 430.64       CUDA Version: 10.1
docker中安装：sudo docker run --name ppocr -v $PWD:/paddle --network=host -it paddlepaddle/paddle:latest-dev-cuda10.1-cudnn7-gcc82 /bin/bash
import paddle报错：
/usr/local/python3.5.1/lib/python3.5/site-packages/paddle/fluid/framework.py:298: UserWarning: You are using GPU version Paddle, but your CUDA device is not set properly. CPU device will be used by default.
  "You are using GPU version Paddle, but your CUDA device is not set properly. CPU device will be used by default."

**Comment by Shixiaowei02** [comment]
您好，此报错的原因是 Paddle 借助 CUDA 发现机器中显卡个数为零。请确认 CUDA 版本和运行正常，谢谢！

**Comment by wadefelix** [comment]
`sudo docker run` ，如若docker已将默认运行时设置为了nvidia-docker 则没有问题，容器内应能正常使用gpu；
但是若docker的默认运行时`runc`而不是nvidia-docker，则这个命令不能将显卡设备映射到容器内的，应使用`nvidia-docker run` 或`docker run --runtime=nvidia`等来启动容器。

**Comment by mrlihellohorld** [comment]
您好，感谢您的回复。我是使用nvidia-docker run 来启动容器的，参考的是”快速安装”中的命令：

“如果使用CUDA10，请运行以下命令创建容器，设置docker容器共享内存shm-size为64G，建议设置32G以上 sudo nvidia-docker run --name ppocr -v $PWD:/paddle --shm-size=64G --network=host -it paddlepaddle/paddle:latest-dev-cuda10.1-cudnn7-gcc82 /bin/bash” 



------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/Paddle"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年6月18日(星期五) 晚上7:23
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PaddlePaddle/Paddle] CUDA device is not set properly (#33540)





 
sudo docker run ，如若docker已将默认运行时设置为了nvidia-docker 则没有问题，容器内应能正常使用gpu；
 但是若docker的默认运行时runc而不是nvidia-docker，则这个命令不能将显卡设备映射到容器内的，应使用nvidia-docker run 或docker run --runtime=nvidia等来启动容器。

**Comment by rfdeng** [comment]
借楼，遇到了同样的问题，paddle版本：paddlepaddle_gpu-2.0.2.post101-cp38-cp38-linux_x86_64.whl
![image](https://user-images.githubusercontent.com/24435688/122918939-41597600-d392-11eb-901d-b6d3c2794cf6.png)

cuda版本应该没问题的：
![image](https://user-images.githubusercontent.com/24435688/122918978-4ae2de00-d392-11eb-84e8-33a97f643385.png)

**Comment by rfdeng** [comment]
> 借楼，遇到了同样的问题，paddle版本：paddlepaddle_gpu-2.0.2.post101-cp38-cp38-linux_x86_64.whl
> ![image](https://user-images.githubusercontent.com/24435688/122918939-41597600-d392-11eb-901d-b6d3c2794cf6.png)
> 
> cuda版本应该没问题的：
> ![image](https://user-images.githubusercontent.com/24435688/122918978-4ae2de00-d392-11eb-84e8-33a97f643385.png)

@Shixiaowei02 求解答

**Comment by pangyoki** [comment]
你好，docker中执行`export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/lib64:/usr/local/lib`这个指令试试

**Comment by XieYunshen** [comment]
是不是在镜像中装的cuda10.2的包呢？换成`python -m pip install paddlepaddle-gpu==2.1.1.post101 -f https://paddlepaddle.org.cn/whl/mkl/stable.html`试试？
