### ISSUE TITLE
Pycharm配置paddle环境出错

### ISSUE THREAD

**Issue by TLTLHILL** [PaddlePaddle/Paddle#33542]
![%0XQ{)0GQLD`KQ53%$OX(_N](https://user-images.githubusercontent.com/85716726/121681002-d5068900-caec-11eb-9e03-aebc5cab6068.png)
cudnn64_7.dll下载了，环境变量也设置了还是没有解决

**Comment by Shixiaowei02** [comment]
您好，请问您设置的是 `PATH` 环境变量吗？

**Comment by TLTLHILL** [comment]
> 您好，请问您设置的是 `PATH` 环境变量吗？

是不是就是系统的Path环境呀，我设置了这个。
