### ISSUE TITLE
PaddleOCR检测模型，模型使用的是MobileNetV3_large_x0_5_pretrained，训练次数1200次，使用训练模型测试图片检测结果很准确，但是对于同一张图使用推理模型基本上啥也检测不出来

### ISSUE THREAD

**Issue by QIANXUNZDL123** [PaddlePaddle/Paddle#33557]
版本、环境信息：
   1）PaddlePaddle版本：PaddlePaddle-GPU 2.1.0.post
   2）CPU：
   3）GPU：Tesla V100 CUDA:11.2 CuDNN8.1
   4）系统环境：python:3.8 CentOS Linux release 7.9.2009 (Core)

**Comment by MissPenguin** [comment]
您好，请问用的哪个算法，自己有做哪些修改呢，另外，训练模型导出为推理模型、以及用推理模型进行预测的命令可以发一下吗
