### ISSUE TITLE
GetKernelTypeForVar disables oneDNN split kernel

### ISSUE THREAD

**Issue by jakpiase** [PaddlePaddle/Paddle#33583]
Hi, I am currently implementing oneDNN split op kernel. When testing I saw that oneDNN kernel is not being used when AxisTensor or SectionsTensorList are given as input. From what I can see GetKernelTypeForVar function forces choosing native kernel when AxisTensor or SectionsTensorList are given. Can you give me any advice how can I change that behavior to choosing between oneDNN and native kernels while keeping old behavior for native kernel? 

https://github.com/liym27/Paddle/blob/4f24e47bf20546fd600c87f2e98ba91723929f47/paddle/fluid/operators/split_op.cc#L77-L86

**Comment by lidanqing-vv** [comment]
@jakpiase  Can I close this issue ?
