### ISSUE TITLE
请问paddle如何实现batch内的随机负采样？

### ISSUE THREAD

**Issue by costume24** [PaddlePaddle/Paddle#33599]
对于一个batch内的负样本，我希望随机采样一部分样本计算loss，请问有对应的api吗？使用的paddle版本是1.8，静态图

**Comment by zhiqiu** [comment]
hi，可以看下这个RandomSampler是不你需要的 https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/io/RandomSampler_cn.html#fanhui

**Comment by costume24** [comment]
> hi，可以看下这个RandomSampler是不你需要的 https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/io/RandomSampler_cn.html#fanhui

好的，使用方法就是直接代替dataset吗？

**Comment by heavengate** [comment]
`DataLoader`里可以指定`batch_sampler` https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/io/DataLoader_cn.html#paddle.io.DataLoader
BatchSampler里面可以值定sampler https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/io/BatchSampler_cn.html#paddle.io.BatchSampler
指定成`RandomSampler`就可以了
