### ISSUE TITLE
关于使用array来索引tensor

### ISSUE THREAD

**Issue by geoyee** [PaddlePaddle/Paddle#33605]
这是UCN的pytorch版本，x和y是特征点的坐标，源码就是这样索引的。然后在paddle下还没有这样的语法，请问paddle有没有增加这个功能的准备，多久可以支持使用array来索引tensor。
![SKQ6 A$M0P)T2F}40SMV X5](https://user-images.githubusercontent.com/71769312/122190483-719da200-cec4-11eb-8d1f-ae5aaf389db9.png)

**Comment by zhiqiu** [comment]
hi, paddle最近也在支持比较丰富的slice index类型，以array作为index的，可以参考这个PR: https://github.com/PaddlePaddle/Paddle/pull/33000

**Comment by geoyee** [comment]
> hi, paddle最近也在支持比较丰富的slice index类型，以array作为index的，可以参考这个PR: #33000

收到，谢谢，查看一下^_^

**Comment by geoyee** [comment]
看到这个pr已经合并了，在as上使用`! python -m pip install paddlepaddle-gpu==0.0.0.post101 -f https://paddlepaddle.org.cn/whl/cu101/mkl/develop.html`装了最新的develop版本，但是使用还是有点问题。请问这个是我使用的问题还是不能支持这样使用。
```
IndexError: When index contains a Tensor, its length must be 1, but received 3
```
具体的代码中如下
```
F0[:, y0, x0]
```
其中
```
F0.shape: [64, 640, 480]
x0.shape: [14181] x0: Tensor(shape=[14181], dtype=int16, place=CUDAPlace(0), stop_gradient=True,
       [2  , 2  , 2  , ..., 476, 476, 477])
y0.shape: [14181] y0: Tensor(shape=[14181], dtype=int16, place=CUDAPlace(0), stop_gradient=True,
       [428, 142, 68 , ..., 227, 110, 398])
```

**Comment by zhiqiu** [comment]
> 看到这个pr已经合并了，在as上使用`! python -m pip install paddlepaddle-gpu==0.0.0.post101 -f https://paddlepaddle.org.cn/whl/cu101/mkl/develop.html`装了最新的develop版本，但是使用还是有点问题。请问这个是我使用的问题还是不能支持这样使用。
> 
> ```
> IndexError: When index contains a Tensor, its length must be 1, but received 3
> ```
> 
> 具体的代码中如下
> 
> ```
> F0[:, y0, x0]
> ```
> 
> 其中
> 
> ```
> F0.shape: [64, 640, 480]
> x0.shape: [14181] x0: Tensor(shape=[14181], dtype=int16, place=CUDAPlace(0), stop_gradient=True,
>        [2  , 2  , 2  , ..., 476, 476, 477])
> y0.shape: [14181] y0: Tensor(shape=[14181], dtype=int16, place=CUDAPlace(0), stop_gradient=True,
>        [428, 142, 68 , ..., 227, 110, 398])
> ```

hi，我验证了一下，这个case下确实是还有一些问题。我会和相关负责的同学反馈下，看排期支持下这个用法。

**Comment by geoyee** [comment]
> > 看到这个pr已经合并了，在as上使用`! python -m pip install paddlepaddle-gpu==0.0.0.post101 -f https://paddlepaddle.org.cn/whl/cu101/mkl/develop.html`装了最新的develop版本，但是使用还是有点问题。请问这个是我使用的问题还是不能支持这样使用。
> > ```
> > IndexError: When index contains a Tensor, its length must be 1, but received 3
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 具体的代码中如下
> > ```
> > F0[:, y0, x0]
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 其中
> > ```
> > F0.shape: [64, 640, 480]
> > x0.shape: [14181] x0: Tensor(shape=[14181], dtype=int16, place=CUDAPlace(0), stop_gradient=True,
> >        [2  , 2  , 2  , ..., 476, 476, 477])
> > y0.shape: [14181] y0: Tensor(shape=[14181], dtype=int16, place=CUDAPlace(0), stop_gradient=True,
> >        [428, 142, 68 , ..., 227, 110, 398])
> > ```
> 
> hi，我验证了一下，这个case下确实是还有一些问题。我会和相关负责的同学反馈下，看排期支持下这个用法。

收到，感谢，待支持后马上体验进行反馈。

**Comment by hbwx24** [comment]
> > 看到这个pr已经合并了，在as上使用`! python -m pip install paddlepaddle-gpu==0.0.0.post101 -f https://paddlepaddle.org.cn/whl/cu101/mkl/develop.html`装了最新的develop版本，但是使用还是有点问题。请问这个是我使用的问题还是不能支持这样使用。
> > ```
> > IndexError: When index contains a Tensor, its length must be 1, but received 3
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 具体的代码中如下
> > ```
> > F0[:, y0, x0]
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 其中
> > ```
> > F0.shape: [64, 640, 480]
> > x0.shape: [14181] x0: Tensor(shape=[14181], dtype=int16, place=CUDAPlace(0), stop_gradient=True,
> >        [2  , 2  , 2  , ..., 476, 476, 477])
> > y0.shape: [14181] y0: Tensor(shape=[14181], dtype=int16, place=CUDAPlace(0), stop_gradient=True,
> >        [428, 142, 68 , ..., 227, 110, 398])
> > ```
> 
> hi，我验证了一下，这个case下确实是还有一些问题。我会和相关负责的同学反馈下，看排期支持下这个用法。

根据issues创建了任务卡片

**Comment by kk125678** [comment]
xy = paddle.stack([x1,y1],axis=-1)
F1 = paddle.transpose(F0,[1,2,0])
F2 = paddle.gather_nd(F1,xy)
F3 = paddle.transpose(F2,[1,0])
感觉可以这样写

**Comment by geoyee** [comment]
> xy = paddle.stack([y1,x1],axis=-1)
> F1 = paddle.transpose(F0,[1,2,0])
> F2 = paddle.gather_nd(F1,xy)
> F3 = paddle.transpose(F2,[1,0])
> 感觉可以这样写

感谢，空下来后试一试！
