### ISSUE TITLE
编译错误！PaddlePaddle2.1.0 CUDA11.3 CUDNN11.3 

### ISSUE THREAD

**Issue by TLTLHILL** [PaddlePaddle/Paddle#33604]
![XU~G@ KU9T`AZ4WSTH)01JJ](https://user-images.githubusercontent.com/85716726/122185315-96434b00-cebf-11eb-996f-4530ca843f31.png)

**Comment by zhiqiu** [comment]
这可能是安装的cpu版本的paddle吧？
