### ISSUE TITLE
ubuntu 16.04  docker 安装失败

### ISSUE THREAD

**Issue by xmuyong** [PaddlePaddle/Paddle#3362]
###执行如下命令
sudo docker run -d -p 3333:22 -p 11111:8888 docker.paddlepaddle.org/paddle:0.10.0-dev
Unable to find image 'docker.paddlepaddle.org/paddle:0.10.0-dev' locally
0.10.0-dev: Pulling from paddle
8f229c550c2e: Pull complete
8e1fb71e8df6: Pull complete
f75a34586856: Pull complete
8744e322b832: Pull complete
d5165bfce78f: Pull complete
c350e060f1db: Pull complete
ccabcb470eb7: Pull complete
8324d9bfba85: Pull complete
6c1fd41d1688: Pull complete
af86b8b1415a: Pull complete
533ede042dd1: Pull complete
aa427fe59157: Pull complete
c31a1fcce111: Pull complete
58adae1ed11f: Pull complete
afb366c49a8c: Pull complete
5d37668cede0: Pull complete
5b695de39932: Pull complete
7f0ab2bc4560: Pull complete
cbf3e74d759c: Pull complete
530f1fcaf731: Pull complete
0d1f487575a3: Pull complete
c682a22f9118: Pull complete
5e98db544738: Pull complete
Digest: sha256:0a0620e6896906701c1fe120637337aecaf8fc3fbae86250dccc19d0d8051b2c
Status: Downloaded newer image for docker.paddlepaddle.org/paddle:0.10.0-dev
f2e33cc6003f823f8aec95654ed95518758fdee16bf4ac3d5337a1b3fb49e46d

###执行 docker logs 命令，给出如下提示
bash: /paddle/paddle/scripts/docker/build.sh: No such file or directory

**Comment by xmuyong** [comment]
用

**Comment by xmuyong** [comment]
用  docker run -d -p 3333:22 -p 11111:8888 paddlepaddle/paddle:0.10.0-dev /usr/sbin/sshd -D  可以

**Comment by xmuyong** [comment]
ssh -p 3333 root@localhost

**Comment by xmuyong** [comment]
密码 root

**Comment by helinwang** [comment]
您好，

用
```
$ sudo docker run -it docker.paddlepaddle.org/paddle:0.10.0-dev bash
``` 
或者像您说的
```
$ 
```
$ sudo docker run -d -p 3333:22 -p 11111:8888 docker.paddlepaddle.org/paddle:0.10.0-dev /usr/sbin/sshd -D
```
都可以。
