### ISSUE TITLE
使用paddlehub经过finetune过的模型如何部署 

### ISSUE THREAD

**Issue by helen88** [PaddlePaddle/Paddle#33620]
https://github.com/PaddlePaddle/PaddleHub/tree/release/v2.1/demo/image_classification 这里介绍的一键部署，是预训练模型，我想部署我自己微调过的模型。想请问改怎么操作呢？

**Comment by haoyuying** [comment]
您好，如果您想了解如何使用已经提供的部署代码，请参考这里https://github.com/PaddlePaddle/PaddleHub/blob/release/v2.1/docs/docs_ch/tutorial/serving.md
如果您想自己写一个serving任务，可以参考分类代码中关于serving部分https://github.com/PaddlePaddle/PaddleHub/blob/release/v2.1/paddlehub/module/cv_module.py#L123
serving部分在123-135行之间。
