### ISSUE TITLE
显存在删除变量后并没有被释放

### ISSUE THREAD

**Issue by lfxx** [PaddlePaddle/Paddle#33625]
- 版本、环境信息：
```
    ****************************************
Paddle version: 2.1.0
Paddle With CUDA: True

OS: Ubuntu 20.04
Python version: 3.6.13

CUDA version: 11.0.194
Build cuda_11.0_bu.TC445_37.28540450_0
cuDNN version: None.None.None
Nvidia driver version: 460.80
****************************************
```
- 复现信息：
使用以下代码复现
```
import paddle
import time
paddle.set_device('gpu:0')
x = paddle.ones(shape=[4000, 4000])
time.sleep(10)
del x
time.sleep(1000)
```
- 问题描述：
1.当使用```x = paddle.ones(shape=[4000, 4000])```在GPU上创建变量后，此时使用nvidia-smi查看显存信息如下：

![before1](https://user-images.githubusercontent.com/27956643/122345603-9fddb900-cf7a-11eb-936e-3627fd53b5fe.png)
2.然后删除x变量，此时使用nvidia-smi查看显存信息如下，GPU上的显存并未被完全释放：
![after1](https://user-images.githubusercontent.com/27956643/122345748-c7348600-cf7a-11eb-8979-600518f15ace.png)
这是为什么？Pytorch貌似也有这个问题。想知道如何在不结束程序的情况下完全清除显存占用。急求官方解惑。

**Comment by DannyIsFunny** [comment]
你好，你这里删的应该只是创建出的layer实例
tensor管理的data应该没有被释放

**Comment by DannyIsFunny** [comment]
你好，因为Paddle 里这一部分显存管理是采用“显存池”方法实现的.  Tensor删除后占用的内存归还到显存池了、但仍然被进程占用着、除非进程结束、程序实际占用内存不会降低
```
// 创建Tensor 、显存池申请 4000*4000*data_size 大小的显存、 并分配给 X
x = paddle.ones(shape=[4000, 4000])
// 删除Tensor X、X占用的内存归还显存池 [进程实际占用物理内存没有降低]
del x
// 如果再创建新的Tensor 将优先从已有显存池取内存、实际占用物理内存不变
y = paddle.ones(shape=[2000, 4000])
```

**Comment by lfxx** [comment]
好的，非常感谢
