### ISSUE TITLE
Can not import avx core while this file exists

### ISSUE THREAD

**Issue by kaixin-bai** [PaddlePaddle/Paddle#33635]
安装方式：`pip install paddle-gpu`
安装成功了，但是在import paddle时报错
报错信息：
```bash
import paddle
Error: Can not import avx core while this file exists: /home/kb/anaconda3/envs/python36/lib/python3.6/site-packages/paddle/fluid/core_avx.so
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/kb/anaconda3/envs/python36/lib/python3.6/site-packages/paddle/__init__.py", line 26, in <module>
    from .fluid import monkey_patch_variable
  File "/home/kb/anaconda3/envs/python36/lib/python3.6/site-packages/paddle/fluid/__init__.py", line 36, in <module>
    from . import framework
  File "/home/kb/anaconda3/envs/python36/lib/python3.6/site-packages/paddle/fluid/framework.py", line 37, in <module>
    from . import core
  File "/home/kb/anaconda3/envs/python36/lib/python3.6/site-packages/paddle/fluid/core.py", line 297, in <module>
    raise e
  File "/home/kb/anaconda3/envs/python36/lib/python3.6/site-packages/paddle/fluid/core.py", line 257, in <module>
    from .core_avx import *
ImportError: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.22' not found (required by /home/kb/anaconda3/envs/python36/lib/python3.6/site-packages/paddle/fluid/core_avx.so)
```

**Comment by DannyIsFunny** [comment]
请问安装的Paddle版本是多少呢

**Comment by DannyIsFunny** [comment]
从报错信息看，可以参考这个解决方法：https://ai.baidu.com/forum/topic/show/983545

**Comment by wadefelix** [comment]
glibc ABI对不上。能详述下安装环境么？操作系统和glibc/glibcxx的版本。
盲猜需要升级

**Comment by kaixin-bai** [comment]
> 请问安装的Paddle版本是多少呢

安装的版本是paddlepaddle-gpu-2.1.0

**Comment by kaixin-bai** [comment]
> 从报错信息看，可以参考这个解决方法：https://ai.baidu.com/forum/topic/show/983545

在paddle/fluid文件夹中是有那个动态库的

**Comment by kaixin-bai** [comment]
> glibc ABI对不上。能详述下安装环境么？操作系统和glibc/glibcxx的版本。
> 盲猜需要升级

服务器上我木有升级权限

**Comment by wadefelix** [comment]
> > glibc ABI对不上。能详述下安装环境么？操作系统和glibc/glibcxx的版本。
> > 盲猜需要升级
> 
> 服务器上我木有升级权限

https://www.baidu.com/s?wd=%E6%9F%A5%E7%9C%8B%20GLIBC%20%E7%89%88%E6%9C%AC&rsv_spt=1&rsv_iqid=0xe455c0f7000490e6&issp=1&f=8&rsv_bp=1&rsv_idx=2&ie=utf-8&tn=baiduhome_pg&rsv_enter=1&rsv_dl=ib&rsv_sug3=2&rsv_sug1=1&rsv_sug7=001

可以先看看是不是这个版本问题导致的。
若是，可以要求相关运维人员升级嘛。

或者，若机器已支持docker的话，非常建议使用docker版本， 各种依赖已全部封装在镜像内了。

**Comment by Hukongtao** [comment]
大佬们 这一波报错就直接劝退一堆用户了啊 能否直接像pytorch那样pip install之后就可以立即使用呢？

**Comment by Hukongtao** [comment]
> > > glibc ABI对不上。能详述下安装环境么？操作系统和glibc/glibcxx的版本。
> > > 盲猜需要升级
> > 
> > 
> > 服务器上我木有升级权限
> 
> https://www.baidu.com/s?wd=%E6%9F%A5%E7%9C%8B%20GLIBC%20%E7%89%88%E6%9C%AC&rsv_spt=1&rsv_iqid=0xe455c0f7000490e6&issp=1&f=8&rsv_bp=1&rsv_idx=2&ie=utf-8&tn=baiduhome_pg&rsv_enter=1&rsv_dl=ib&rsv_sug3=2&rsv_sug1=1&rsv_sug7=001
> 
> 可以先看看是不是这个版本问题导致的。 若是，可以要求相关运维人员升级嘛。
> 
> 或者，若机器已支持docker的话，非常建议使用docker版本， 各种依赖已全部封装在镜像内了。

运维人员升级没那么简单吧，一台开发机其他人也在用，很多库的版本都是固定的。docker的话是不是不太利于调试呢。这个问题你们没办法解决么？第一步安装就有问题真的很影响用户体验啊
