### ISSUE TITLE
paddle中使用自定义数据集，设置shuffle为False，显存溢出

### ISSUE THREAD

**Issue by zhude233** [PaddlePaddle/Paddle#33646]
版本、环境信息：
    1）PaddlePaddle版本：2.0
    2）CPU：i5-9300H
    3）GPU：GTX1660Ti、cudatoolkit=10.2和CUDNN=7.6.5
    4）系统环境：系统Windows 10 企业版、版本21H1，Python3.7

在shuffle设置为True时，显存占用约1.4g，下图为设置为True时

![image](https://user-images.githubusercontent.com/60126992/122499878-4631c900-d024-11eb-8265-33557901f66a.png)
在shuffle设置为False时，显存会溢出，下图为设置为False时
![image](https://user-images.githubusercontent.com/60126992/122499914-577ad580-d024-11eb-85f2-4c69ea39ec64.png)
两者均在同一环境下测试，以下为dataset定义
![image](https://user-images.githubusercontent.com/60126992/122499927-5ea1e380-d024-11eb-89cb-3ca41eb61177.png)
![image](https://user-images.githubusercontent.com/60126992/122499937-63669780-d024-11eb-8749-f51b22ae708e.png)
最长的data返回仅为[3000+,800]

**Comment by heavengate** [comment]
你好，DataLoader是不占用显存的，除了DataLoader还有其他模块么，或者单独测下DataLoader输入输出试下呢

**Comment by zhude233** [comment]
> 你好，DataLoader是不占用显存的，除了DataLoader还有其他模块么，或者单独测下DataLoader输入输出试下呢

好的，我进行测试一下

**Comment by zhude233** [comment]
> 你好，DataLoader是不占用显存的，除了DataLoader还有其他模块么，或者单独测下DataLoader输入输出试下呢

仅有DataLoader模块设置为shuffle=False，并进行以下数据取出操作
![image](https://user-images.githubusercontent.com/60126992/122513055-6e2d2680-d03c-11eb-9ab4-4f2c18d07522.png)
会造成显存持续上涨
