### ISSUE TITLE
编译win10平台源码没找到libpaddle_inference.lib

### ISSUE THREAD

**Issue by a2824256** [PaddlePaddle/Paddle#33644]
根据源码编译教程编译win10平台源码，文档说明编译成功的项目结构如下：
```
build/paddle_inference_install_dir
├── CMakeCache.txt
├── paddle
│   ├── include
│   │   ├── paddle_anakin_config.h
│   │   ├── paddle_analysis_config.h
│   │   ├── paddle_api.h
│   │   ├── paddle_inference_api.h
│   │   ├── paddle_mkldnn_quantizer_config.h
│   │   └── paddle_pass_builder.h
│   └── lib
│       ├── libpaddle_inference.a (Linux)
│       ├── libpaddle_inference.so (Linux)
│       └── libpaddle_inference.lib (Windows)
├── third_party
│   ├── boost
│   │   └── boost
│   ├── eigen3
│   │   ├── Eigen
│   │   └── unsupported
│   └── install
│       ├── gflags
│       ├── glog
│       ├── mkldnn
│       ├── mklml
│       ├── protobuf
│       ├── xxhash
│       └── zlib
└── version.txt
```
问题1：但是我编译出来的paddle/lib文件夹中没有这个文件libpaddle_inference.lib (Windows)，但是有一个叫paddle_fluid.dll和.lib的文件，这个paddle_fluid就是libpaddle_inference吗？

编译指令如下：
```
cmake .. -G "Visual Studio 14 2015" -A x64 -T host=x64 -DWITH_GPU=ON -DWITH_TESTING=OFF -DON_INFER=ON -DCMAKE_BUILD_TYPE=Release -DPY_VERSION=3  -DWITH_TENSORRT=ON -DTENSORRT_ROOT="E:\\TensorRT-7.0.0.11" -DWITH_NCCL=OFF -DCUDA_ARCH_NAME=Turing
```

问题2：还有编译Paddle-Inference-Demo的paddle_infer_demo项目提示如下，使用的是自己编译出来的预测库。libmklml_intel这个文件在预测库里没有找到。编译出来实则是叫mklml吗？
![image](https://user-images.githubusercontent.com/7108023/122321351-4ebbce00-cf56-11eb-86a5-280646363180.png)

**Comment by jiweibo** [comment]
> 问题1：但是我编译出来的paddle/lib文件夹中没有这个文件libpaddle_inference.lib (Windows)，但是有一个叫paddle_fluid.dll和.lib的文件，这个paddle_fluid就是libpaddle_inference吗？

这个目前看起来是文档没有更新，您得到的编译产物是正确的哈，windows下的动态库(.dll+.lib)

> 问题2：还有编译Paddle-Inference-Demo的paddle_infer_demo项目提示如下，使用的是自己编译出来的预测库。libmklml_intel这个文件在预测库里没有找到。编译出来实则是叫mklml吗？

看起来您用的demo CMakeLists.txt没有对windows做区分，请问您是用的和这个吗？ https://github.com/PaddlePaddle/Paddle-Inference-Demo/blob/master/c%2B%2B/lib/CMakeLists.txt

**Comment by a2824256** [comment]
> 看起来您用的demo CMakeLists.txt没有对windows做区分，请问您是用的和这个吗？ https://github.com/PaddlePaddle/Paddle-Inference-Demo/blob/master/c%2B%2B/lib/CMakeLists.txt

不是，我是用项目里面的，所以我改回用这个就可以了？

**Comment by jiweibo** [comment]
> > 看起来您用的demo CMakeLists.txt没有对windows做区分，请问您是用的和这个吗？ https://github.com/PaddlePaddle/Paddle-Inference-Demo/blob/master/c%2B%2B/lib/CMakeLists.txt
> 
> 不是，我是用项目里面的，所以我改回用这个就可以了？

您可以试下哈，应该是ok的。我看了下CMakeLists.txt中windows的mkl库名字是 mklml

**Comment by Piney-Huang** [comment]
![image](https://user-images.githubusercontent.com/70417898/122516208-11803a80-d041-11eb-8a57-7895a072fec2.png)

**Comment by Piney-Huang** [comment]
更改CMakeLists.txt里面CUDA_LIB的路径为C:\\Program\ Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v10.2\\lib\\x64"，编译完成后提示无法打开\cudart.lib

**Comment by jiweibo** [comment]
> 更改CMakeLists.txt里面CUDA_LIB的路径为C:\Program\ Files\NVIDIA GPU Computing Toolkit\CUDA\v10.2\lib\x64"，编译完成后提示无法打开\cudart.lib

是不是路径没有设置成功啊，报错显示\cudart.lib，前面的Prefix都没加进去

**Comment by Piney-Huang** [comment]
![image](https://user-images.githubusercontent.com/70417898/122852083-9b324f80-d342-11eb-95a7-48013c0d7856.png)

**Comment by Piney-Huang** [comment]
路径设置完成之后编译存在如上问题，请问该如何解决

**Comment by Piney-Huang** [comment]
附加库目录路径如下
![image](https://user-images.githubusercontent.com/70417898/122852612-80aca600-d343-11eb-8afd-18826982af41.png)

**Comment by a2824256** [comment]
![image](https://user-images.githubusercontent.com/7108023/122896787-03515780-d37c-11eb-9921-d1fc5b5436fe.png)
paddle现在没问题，现在问题来自gflags @jiweibo

**Comment by a2824256** [comment]
已解决，改成Release就行了
