### ISSUE TITLE
PaddlePaddlle官网API文档有错误

### ISSUE THREAD

**Issue by DeepGeGe** [PaddlePaddle/Paddle#33651]
PaddlePaddle官网API文档：paddle.nn.functional.cross_entropy有个参数说明错了：label参数传入数据的类型只支持int64。但是官网上说的支持int32,int64,float32,float64；（见第一、二张图）
此外，官网应用实践部分：自然语言处理>IMDB数据集使用BOW网络的文本分类，这个例子中按照官网给的代码是跑不起来的，因为后面交叉熵用的是cross_entropy，但是数据处理时候标签没有转int64。（见第三张图）
![1](https://user-images.githubusercontent.com/51083814/122506245-839c5380-d030-11eb-9187-3c674ad223c8.png)
![2](https://user-images.githubusercontent.com/51083814/122506255-88f99e00-d030-11eb-87ad-2e6f870167c0.png)
![3](https://user-images.githubusercontent.com/51083814/122506267-8bf48e80-d030-11eb-9436-6b77c5053f58.png)

**Comment by jiweibo** [comment]
非常感谢您的反馈，我们修复下文档！

**Comment by HydrogenSulfate** [comment]
感谢反馈，文档描述的确存在问题，接下来会跟进修复
