### ISSUE TITLE
paddle.distribution.Normal 报错

### ISSUE THREAD

**Issue by swag1ong** [PaddlePaddle/Paddle#33652]
****************************************
Paddle version: 2.0.2
Paddle With CUDA: True
OS: Ubuntu 16.04
Python version: 3.7.10
CUDA version: None
cuDNN version: None.None.None
Nvidia driver version: 430.26
****************************************

您好，我在使用paddle.distribution.Normal的过程中，发现如果 mean 和 std为不同的type，在创建该class instance的时候并不会报错，运行该instance的一些methods的时候也不会报错，但是使用log_prob()的时候会报错，比如:

```python
mean = paddle.to_tensor([1.0, 1.0, 1.0], dtype='float32')
std = paddle.to_tensor([1.0, 1.0, 1.0], dtype='float64')
dist = paddle.distribution.Normal(mean, std) # 不会报错
action = dist.sample([1]) #不会报错
dist.log_prob(action) # 报错 
```
报错信息为
> ValueError: (InvalidArgument) Tensor holds the wrong type, it holds double, but desires to be float.
  [Hint: Expected valid == true, but received valid:0 != true:1.] (at /paddle/paddle/fluid/framework/tensor_impl.h:33)
  [operator < elementwise_sub > error]

如果不同类型的mean 和std是不被允许的，是否在创建Normal类instance的时候报错会更为妥当

**Comment by pangyoki** [comment]
好的，感谢反馈。我们后面优化下，预期效果是，如果输入的mean和std的数据类型不同，给用户一个warning提示类型不同，并将std的类型转化成与mean一致。
