### ISSUE TITLE
为什么Embedding层输入int32类型数据比输入int64类型数据计算速度慢的多？

### ISSUE THREAD

**Issue by DeepGeGe** [PaddlePaddle/Paddle#33679]
- 版本、环境信息：
    1）PaddlePaddle版本：2.1.0（GPU版本）
    2）CPU：
    3）GPU：gtx 1050 max-Q，CUDA和CUDNN版本号：10.1和7.6
    4）系统环境：Win10，Python 3.7
- 模型信息
    1）模型名称：Embedding+Linear+softmax
    2）使用数据集名称: IMDB
    3）使用算法名称
    4）模型链接

问题“
同一个模型（简单的Embedding层+softmax分类器），同样的数据，在同一台机器在GPU环境上，Embedding层输入数据类型int64比int32快了16倍。
![1](https://user-images.githubusercontent.com/51083814/122664864-77ea9180-d1d6-11eb-96cf-cec01a875001.png)
![2](https://user-images.githubusercontent.com/51083814/122664867-7d47dc00-d1d6-11eb-9288-2815d0091bc3.png)
![3](https://user-images.githubusercontent.com/51083814/122664869-8042cc80-d1d6-11eb-8715-53e4b5502a30.png)
我用低阶另一种方式搭建了同样的网络，查看了经过Embedding层之后，输出的数据格式：第一张图是输入格式为int64，输出为paddle.float32；第二张图输入为int32，输出也为paddle.float32。所以经过Embedding层之后，就完全一样了。时间应该是耗在Embedding层对不同数据类型的处理上，这里对int32类型数据处理耗费了比较多的时间。
在我机器上慢了60ms/step。关键是我把全部数据从int32一次赚int64也用不了60ms。
![4](https://user-images.githubusercontent.com/51083814/122664934-ec253500-d1d6-11eb-87a5-8db93a680208.png)
![5](https://user-images.githubusercontent.com/51083814/122664939-efb8bc00-d1d6-11eb-80e9-3a333519ff62.png)
![6](https://user-images.githubusercontent.com/51083814/122664941-f21b1600-d1d6-11eb-999e-d919213752e5.png)

**Comment by FrostML** [comment]
咨询了 @seiriosPlus ，当输入类型是 `int32` 的时候，会有一个 convert，转回 `int64`，所以会比较耗时。
