### ISSUE TITLE
训练过程中出现内存泄漏

### ISSUE THREAD

**Issue by btobab** [PaddlePaddle/Paddle#33676]
1）PaddlePaddle版本：2.1.0
    2）系统环境：aistudio
在训练前500轮都没有问题，但是在之后的某一时刻就突然停止，出现内存泄漏问题。不清楚是哪方面的问题
在paddle2.0.2版本中没有出现这个问题

**Comment by zhiqiu** [comment]
hi，请提供下具体的模型和环境，以便于复现问题。

**Comment by btobab** [comment]
好的，[项目链接](https://aistudio.baidu.com/aistudio/projectdetail/1542163)

**Comment by zhiqiu** [comment]
推测与eval阶段没有使用no_grad有关，我找相关同学check下模型代码写法。

**Comment by btobab** [comment]
好的，谢谢哥哥

**Comment by zhiqiu** [comment]
看了下，这个模型是你在AIstudio写的吗？

**Comment by btobab** [comment]
是的

**Comment by zhiqiu** [comment]
你可以试下将eval阶段的代码单独拿出来，然后在eval中除了设置model.eval()外，再加上no_grad()：

<img width="664" alt="6c2244e3698c8162ae9b9d776f976957" src="https://user-images.githubusercontent.com/6888866/124448248-ce4df780-ddb4-11eb-9514-9863c91c780f.png">

**Comment by btobab** [comment]
好的，我试一下
