### ISSUE TITLE
使用paddlehub finetune得到的模型进行预测，为什么还要先加载预训练模型，导致很占用显存

### ISSUE THREAD

**Issue by helen88** [PaddlePaddle/Paddle#33684]
paddle.2 我通过预训练模型，进行finetune已经得到了自己的模型，进行预测的时候，为何还要去加载原来的预训练模型，这样会很占用显存，求助能不加载原预训练模型，只加载我训练得到的模型，可以吗？

import paddle
import paddlehub as hub

if __name__ == '__main__':

    model = hub.Module(name='resnet50_vd_imagenet_ssld', label_list=["roses", "tulips", "daisy", "sunflowers", "dandelion"], load_checkpoint='/PATH/TO/CHECKPOINT')
    result = model.predict(['flower.jpg'])

from：https://github.com/PaddlePaddle/PaddleHub/tree/release/v2.1/demo/image_classification   

136M	model.pdparams 我自己训练好的模型只有136M，但实际占用了1081
![image](https://user-images.githubusercontent.com/4593091/122702969-251ae380-d283-11eb-8f14-f494cc0b30e3.png)

**Comment by cryoco** [comment]
![image](https://user-images.githubusercontent.com/12407750/122706340-53e88800-d28a-11eb-8687-b32b55d5de24.png)
看您发的文档里，应该是只需要加载finetune得到的模型进行预测就可以了

**Comment by cryoco** [comment]
另外，预测时实际占用的显存大小，并不会与参数文件大小一致的哈，因为预测时很多显存占用会用于存储中间计算结果Tensor，并且cuda、cudnn等第三方依赖库句柄也会占用不小显存。
