### ISSUE TITLE
【Windows编译错误】2.0版本Windows下/MD编译GPU预测库出错

### ISSUE THREAD

**Issue by yoyao1** [PaddlePaddle/Paddle#33687]
编译错误和这个issue现象基本一样 release正常，debug报错 vs2015
【Windows编译错误】1.8版本Windows下/MD编译GPU预测库出错 #24677

libprofiler.lib(profiler.cu.obj) : error LNK2038: 检测到“_ITERATOR_DEBUG_LEVEL”的不匹配项: 值“0”不匹配值“2”(io.obj 中)
libprofiler.lib(profiler.cu.obj) : error LNK2038: 检测到“RuntimeLibrary”的不匹配项: 值“MT_StaticRelease”不匹配值“MTd_StaticDebug”(io.obj 中)
libtensor.lib(.tensor_util.obj) : error LNK2038: 检测到“_ITERATOR_DEBUG_LEVEL”的不匹配项: 值“0”不匹配值“2”(io.obj 中)
libtensor.lib(.tensor_util.obj) : error LNK2038: 检测到“RuntimeLibrary”的不匹配项: 值“MT_StaticRelease”不匹配值“MTd_StaticDebug”(io.obj 中)
libmath_function.lib(math_function.cu.obj) : error LNK2038: 检测到“_ITERATOR_DEBUG_LEVEL”的不匹配项: 值“0”不匹配值“2”(io.obj 中)
libmath_function.lib(math_function.cu.obj) : error LNK2038: 检测到“RuntimeLibrary”的不匹配项: 值“MT_StaticRelease”不匹配值“MTd_StaticDebug”(io.obj 中)
libcompare_all_op.lib(compare_all_op.cu.obj) : error LNK2038: 检测到“_ITERATOR_DEBUG_LEVEL”的不匹配项: 值“0”不匹配值“2”(io.obj 中)
libcompare_all_op.lib(compare_all_op.cu.obj) : error LNK2038: 检测到“RuntimeLibrary”的不匹配项: 值“MT_StaticRelease”不匹配值“MTd_StaticDebug”(io.obj 中)
libcompare_op.lib(compare_op.cu.obj) : error LNK2038: 检测到“_ITERATOR_DEBUG_LEVEL”的不匹配项: 值“0”不匹配值“2”(io.obj 中)
libcompare_op.lib(compare_op.cu.obj) : error LNK2038: 检测到“RuntimeLibrary”的不匹配项: 值“MT_StaticRelease”不匹配值“MTd_StaticDebug”(io.obj 中)
liblogical_op.lib(logical_op.cu.obj) : error LNK2038: 检测到“_ITERATOR_DEBUG_LEVEL”的不匹配项: 值“0”不匹配值“2”(io.obj 中)
liblogical_op.lib(logical_op.cu.obj) : error LNK2038: 检测到“RuntimeLibrary”的不匹配项: 值“MT_StaticRelease”不匹配值“MTd_StaticDebug”(io.obj 中)
libbox_coder_op.lib(box_coder_op.cu.obj) : error LNK2038: 检测到“_ITERATOR_DEBUG_LEVEL”的不匹配项: 值“0”不匹配值“2”(io.obj 中)
libbox_coder_op.lib(box_coder_op.cu.obj) : error LNK2038: 检测到“RuntimeLibrary”的不匹配项: 值“MT_StaticRelease”不匹配值“MTd_StaticDebug”(io.obj 中)
libiou_similarity_op.lib(iou_similarity_op.cu.obj) : error LNK2038: 检测到“_ITERATOR_DEBUG_LEVEL”的不匹配项: 值“0”不匹配值“2”(io.obj 中)
libiou_similarity_op.lib(iou_similarity_op.cu.obj) : error LNK2038: 检测到“RuntimeLibrary”的不匹配项: 值“MT_StaticRelease”不匹配值“MTd_StaticDebug”(io.obj 中)
libprior_box_op.lib(prior_box_op.cu.obj) : error LNK2038: 检测到“_ITERATOR_DEBUG_LEVEL”的不匹配项: 值“0”不匹配值“2”(io.obj 中)
libprior_box_op.lib(prior_box_op.cu.obj) : error LNK2038: 检测到“RuntimeLibrary”的不匹配项: 值“MT_StaticRelease”不匹配值“MTd_StaticDebug”(io.obj 中)
libdensity_prior_box_op.lib(density_prior_box_op.cu.obj) : error LNK2038: 检测到“_ITERATOR_DEBUG_LEVEL”的不匹配项: 值“0”不匹配值“2”(io.obj 中)
libdensity_prior_box_op.lib(density_prior_box_op.cu.obj) : error LNK2038: 检测到“RuntimeLibrary”的不匹配项: 值“MT_StaticRelease”不匹配值“MTd_StaticDebug”(io.obj 中)
libanchor_generator_op.lib(anchor_generator_op.cu.obj) : error LNK2038: 检测到“_ITERATOR_DEBUG_LEVEL”的不匹配项: 值“0”不匹配值“2”(io.obj 中)

建立issue时，为快速解决问题，请您根据使用情况给出如下信息：
- 标题：请包含关键词“安装错误”/“编译错误”，例如“Mac编译错误”
- 版本、环境信息：
    1）PaddlePaddle版本：请提供您的PaddlePaddle版本号（如1.1）或CommitID
    2）CPU：i7 4790
    3）GPU：RTX2060s，CUDA 10.2和CUDNN7
    4）系统环境：Win10
注：您可以通过执行[summary_env.py](https://github.com/PaddlePaddle/Paddle/blob/develop/tools/summary_env.py)获取以上信息。
- 安装方式信息：
1）pip安装/docker安装
2）本地编译：请提供cmake命令，编译命令
3）docker编译：请提供docker镜像，编译命令            
  特殊环境请注明：如离线安装等
- 复现信息：如为报错，请给出复现环境、复现步骤
- 问题描述：请详细描述您的问题，同步贴出报错信息、日志/代码关键片段

Thank you for contributing to PaddlePaddle.
Before submitting the issue, you could search issue in Github in case that there was a similar issue submitted or resolved before.
If there is no solution,please make sure that this is an installation issue including the following details:
**System information**
-PaddlePaddle version （eg.1.1）or CommitID
-CPU: including CPUMKL/OpenBlas/MKLDNN version
-GPU: including CUDA/CUDNN version
-OS Platform (eg. Mac OS 10.14)
-Python version
- Install method: pip install/install with docker/build from source(without docker)/build within docker
- Other special cases that you think may be related to this problem, eg. offline install, special internet condition 
Note: You can get most of the information by running [summary_env.py](https://github.com/PaddlePaddle/Paddle/blob/develop/tools/summary_env.py).   

**To Reproduce**
Steps to reproduce the behavior
**Describe your current behavior**
**Code to reproduce the issue**
**Other info / logs**

**Comment by cryoco** [comment]
您好，请问是有使用debug信息的需求嘛

**Comment by yoyao1** [comment]
我的预测程序直接加载gpu模型会失败，先加载cpu模型再加载gpu模型正常。想跟踪一下是什么原因

**Comment by cryoco** [comment]
> 我的预测程序直接加载gpu模型会失败，先加载cpu模型再加载gpu模型正常。想跟踪一下是什么原因

您好，可以发一下失败报错信息和推理代码，我们看下

**Comment by yoyao1** [comment]
input_t->CopyFromCpu(m_pdataInput);这句报的错。 先加载cpu模型再加载gpu模型正常。
我的是mfc的程序 
只报了
0x00007FFCE0143A16 (paddle_inference.dll)处(位于 InspectionSystem.exe 中)引发的异常: 0xC0000005: 读取位置 0x0000000000000000 时发生访问冲突。
没有控制台的错误提示。 mfc可以显示控制台程序的信息吗？

**Comment by cryoco** [comment]
应该是内存相关错误，m_pdataInput应为一个cpu数据的指针，数据大小和类型与模型输入一致。可以自查下是否为指针为空、数据长度不对、数据类型不对等问题

**Comment by yoyao1** [comment]
这些都没有问题，里边的数据都是正常的shape也对。直接加载cpu模型，或先加载cpu模型再加载gpu模型也正常。
cpu gpu就差这一句
if (m_bUseGPU)
{
	config.EnableUseGpu(100, 0);
}

**Comment by cryoco** [comment]
能否提供下您的预测代码，我们复现看下，可以参考https://github.com/PaddlePaddle/Paddle-Inference-Demo/tree/master/c%2B%2B/cuda_linux_demo 的形式提供

**Comment by yoyao1** [comment]
我也写了一个demo，代码和这个差不多。但是没这个问题。加到现有的工程里就有问题，所有想调试一下试试

**Comment by yoyao1** [comment]
感觉是异步处理的问题，但是demo里测试也没问题
	Concurrency::task<int> LoadMissionTask = Concurrency::task<int>(([this]
	{
		Sleep(3000);
		PaddleInferFunc();
		return 0;
	})).then([this](Concurrency::task<int> tk) {
		try
		{
			tk.get();
		}
		catch (const std::exception& e)
		{
			const char* pstr = e.what();
			
		}
		return 0;
	});
