### ISSUE TITLE
paddle.fluid.layers.ssd_loss 文档问题（2.0RC）

### ISSUE THREAD

**Issue by 0x2e1** [PaddlePaddle/Paddle#33682]
2.0RC无与paddle.fluid.layers.ssd_loss对应的API，在学习的时候不是很方便

**Comment by FrostML** [comment]
可以先用原 API，我们反馈一下。

**Comment by 0x2e1** [comment]
那2.0 的tensor 与1.x的 Variable 是通用的吗？
如果可以那么就可以继续学习了，不过之前在映射表上有一个paddle.nn.functional.ssd_loss（好像是）
