### ISSUE TITLE
部署的时候报错了

### ISSUE THREAD

**Issue by JianJingGao** [PaddlePaddle/Paddle#33698]
![image](https://user-images.githubusercontent.com/51236891/122730219-91f6a380-d2ac-11eb-9aad-84165e79ac4c.png)

set了cuda路径还是不行。。。

**Comment by cryoco** [comment]
您好，请问您使用是Paddle模型套件库还是自己写的部署脚本呢？是在什么设备上部署呢？
麻烦提供下paddle版本，依赖的cuda cudnn版本

**Comment by JianJingGao** [comment]
Paddle 2.1，cuda10.2和cudnn7.6.5
是在deploy/python/infer.py的基础上编写的，在windows系统部署

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

发件人: Pei ***@***.***>
发送时间: 2021年6月21日 16:23
收件人: ***@***.***>
抄送: ***@***.***>; ***@***.***>
主题: Re: [PaddlePaddle/Paddle] 部署的时候报错了 (#33698)


您好，请问您使用是Paddle模型套件库还是自己写的部署脚本呢？是在什么设备上部署呢？
麻烦提供下paddle版本，依赖的cuda cudnn版本

―

**Comment by JianJingGao** [comment]
打算打包成exe文件发布

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

发件人: Pei ***@***.***>
发送时间: 2021年6月21日 16:23
收件人: ***@***.***>
抄送: ***@***.***>; ***@***.***>
主题: Re: [PaddlePaddle/Paddle] 部署的时候报错了 (#33698)


您好，请问您使用是Paddle模型套件库还是自己写的部署脚本呢？是在什么设备上部署呢？
麻烦提供下paddle版本，依赖的cuda cudnn版本

―

**Comment by cryoco** [comment]
您好，看报错信息是缺少mklml.dll，您可以安装下mkl，如果已安装的话设置下路径

**Comment by JianJingGao** [comment]
可以啦，我把这个dll拷贝进去就行了。
对了，solov2能否C++部署你能回答吗 #3449
谢谢~

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

发件人: Pei ***@***.***>
发送时间: 2021年6月21日 16:30
收件人: ***@***.***>
抄送: ***@***.***>; ***@***.***>
主题: Re: [PaddlePaddle/Paddle] 部署的时候报错了 (#33698)


您好，看报错信息是缺少mklml.dll，您可以安装下mkl，如果已安装的话设置下路径

―
