### ISSUE TITLE
如何查看模型中哪些op使用了CPU计算?

### ISSUE THREAD

**Issue by yeyupiaoling** [PaddlePaddle/Paddle#33703]
- PaddlePaddle 2.1.0
 - Ubuntu 18.04

我的模型在训练时GPU占用率经常很低，PaddlePaddle同学说可能模型中的某个OP使用了CPU计算，导致整体训练速度很慢，以下是我的模型代码，请问怎么查看哪该模型中哪些op使用了CPU计算？
https://github.com/yeyupiaoling/PPASR/tree/%E8%BF%9B%E9%98%B6%E7%BA%A7/model_utils

**Comment by cryoco** [comment]
您好，可以使用profiling工具查看op跑在cpu或gpu上，使用方法可以参考https://www.paddlepaddle.org.cn/documentation/docs/zh/1.8/advanced_guide/performance_improving/analysis_tools/timeline_cn.html

**Comment by yeyupiaoling** [comment]
@cryoco 是不是这个工具不支持动态图，报这个错误。
```
/paddle/paddle/fluid/platform/device_tracer.cc:131: error: function dynload::cuptiActivityEnable(CUPTI_ACTIVITY_KIND_MEMCPY) failed with error CUPTI_ERROR_INSUFFICIENT_PRIVILEGES.
```

**Comment by yeyupiaoling** [comment]
@cryoco 请问这个问题如何解决呢？
