### ISSUE TITLE
TypeError: 'Model' object is not callable

### ISSUE THREAD

**Issue by shingstone-lu** [PaddlePaddle/Paddle#33713]
配置：
win10
python-3.7.0-amd64
cuda_10.2.89_441.22_win10
cudnn-10.2-windows10-x64-v7.6.5.32
paddlepaddle_gpu-2.0.2-cp37-cp37m-win_amd64

代码：
import paddle
from paddle import nn
from paddle.io import Dataset,DataLoader
from paddle.nn import functional as F
from paddle.nn import Layer
import paddle.fluid as fluid
import numpy as np
from PIL import Image

class ImageSet(Dataset):
    '''
    加载数据集
    对图像进行2项预处理：
        1. 减去均值[127.5,127.5,127.5]
        2. HWC->CHW
    '''
    def __init__(self):
        super().__init__()
        self.trainfile='E:\\luqinghua\\ICNet\\train.txt'
        self.trainimagefiles=[]
        self.trainlabelfiles=[]
        self.imagenum=0
        self.mean=[127.5,127.5,127.5]
        with open(self.trainfile) as file:
            lines=file.readlines()
            for line in lines:
                trainsource,trainlabel=line.split('\t')
                trainlabel=trainlabel.replace('\n','')  #替换掉每行的回车换行符
                self.trainimagefiles.append(trainsource)
                self.trainlabelfiles.append(trainlabel)
        self.imagenum=len(self.trainimagefiles)         #数据集数量 图像个数
    
    def __len__(self):
        return self.imagenum

    def __getitem__(self, idx):
        #准备图像
        img=Image.open(self.trainimagefiles[idx])
        img=np.array(img,dtype='float32')
        img=img-self.mean
        img=img.transpose((2,0,1))  # HWC -> CHW
        #img=paddle.to_tensor(img)
        #准备标签
        lab=Image.open(self.trainlabelfiles[idx])
        lab=np.array(lab,dtype='float32')
        #lab=paddle.to_tensor(lab)
        #lab=lab*20  #以下两行代码可以方便的查看标签图像
        #lab=Image.fromarray(lab)

        return img,lab

class Conv_BN_Relu(Layer):
    def __init__(self,in_channels,out_channels,
            kernel_size=3,
            stride=1,
            padding=1,
            name_scope=None,
            dtype='float32'):
        super().__init__(name_scope=name_scope, dtype=dtype)
        self.op_Conv=nn.Conv2D(
            in_channels=in_channels,
            out_channels=out_channels,
            kernel_size=kernel_size,
            stride=stride,
            padding=padding,
            bias_attr=None
        )
        self.op_BN=nn.BatchNorm2D(out_channels)
        self.op_Relu=nn.ReLU()
    
    def forward(self,*inputs, **kwargs):
        conv=self.op_Conv(inputs[0])
        bn=self.op_BN(conv)
        relu=self.op_Relu(bn)
        return relu

class Conv_BN(Layer):
    def __init__(self,in_channels,out_channels,
            kernel_size=3,
            stride=1,
            padding=1,
            name_scope=None,
            dtype='float32'):
        super().__init__(name_scope=name_scope, dtype=dtype)
        self.op_Conv=nn.Conv2D(
            in_channels=in_channels,
            out_channels=out_channels,
            kernel_size=kernel_size,
            stride=stride,
            padding=padding,
            bias_attr=None
        )
        self.op_BN=nn.BatchNorm2D(out_channels)
    
    def forward(self,*inputs, **kwargs):
        conv=self.op_Conv(inputs[0])
        bn=self.op_BN(conv)
        return bn

class Connect1(Layer):
    def __init__(self, in_channels, out_channels, name_scope=None, dtype='float32'):
        super().__init__(name_scope=name_scope, dtype=dtype)
        self.op_conv1=Conv_BN(
            in_channels,
            out_channels*4,
            kernel_size=1,
            padding=0
        )
        self.op_conv2=Conv_BN_Relu(
            in_channels,
            out_channels,
            kernel_size=1,
            padding=0
        )
        self.op_conv3=Conv_BN_Relu(
            out_channels,
            out_channels
        )
        self.op_conv4=Conv_BN(
            out_channels,
            out_channels*4,
            kernel_size=1,
            padding=0
        )

    def forward(self,*inputs, **kwargs):
        conv1=self.op_conv1(inputs[0])
        conv2=self.op_conv2(inputs[0])
        conv3=self.op_conv3(conv2)
        conv4=self.op_conv4(conv3)
        conv5=paddle.add(conv1,conv4)
        conv6=F.relu(conv5)
        return conv6

class Connect2(Layer):
    def __init__(self, in_channels, out_channels, name_scope=None, dtype='float32'):
        super().__init__(name_scope=name_scope, dtype=dtype)
        self.op_conv2=Conv_BN_Relu(
            in_channels,
            out_channels,
            kernel_size=1,
            padding=0
        )
        self.op_conv3=Conv_BN_Relu(
            out_channels,
            out_channels
        )
        self.op_conv4=Conv_BN(
            out_channels,
            out_channels*4,
            kernel_size=1,
            padding=0
        )

    def forward(self,*inputs, **kwargs):
        conv2=self.op_conv2(inputs[0])
        conv3=self.op_conv3(conv2)
        conv4=self.op_conv4(conv3)
        conv5=paddle.add(inputs[0],conv4)
        conv6=F.relu(conv5)
        return conv5,conv6

class ICNet(Layer):
    def __init__(self, classnum, name_scope='icnet', dtype='float32'):
        super().__init__(name_scope=name_scope, dtype=dtype)
        self.op_conv1=nn.AvgPool2D(2,stride=2)
        self.op_conv2_1=Conv_BN_Relu(3,16)
        self.op_conv2_33=Conv_BN(16,16)
        self.op_conv2_3=Conv_BN_Relu(16,16)
        self.op_conv2_5=Conv_BN_Relu(16,32)
        self.op_conv2_13=Connect1(32,16)
        self.op_conv2_17=Connect2(64,16)
        self.op_conv2_25=Connect2(64,16)
        self.op_conv3_1=nn.AvgPool2D(2,stride=2)
        self.op_conv4_7=Connect1(64,32)
        self.op_conv4_11=Connect2(128,32)
        self.op_conv4_19=Connect2(128,32)
        self.op_conv4_27=Connect2(128,32)
        self.op_conv5_2=Conv_BN(128,64)
        self.op_conv5_6=Conv_BN(64,16)
        self.op_sub1_out=nn.Conv2D(16,classnum,1,bias_attr=None)
        self.op_sub2_out=nn.Conv2D(64,classnum,1,bias_attr=None)
        self.op_sub3_out=nn.Conv2D(128,classnum,1,bias_attr=None)
        self.op_conv5_out=nn.Conv2D(16,classnum,1,bias_attr=None)

    def forward(self,*inputs, **kwargs):
        #获得输入数据
        #网络第一层
        conv1=self.op_conv1(inputs[0])
        #网络第二层
        conv2_2=self.op_conv2_1(conv1)
        conv2_34=self.op_conv2_33(conv2_2)
        conv2_35=F.relu(conv2_34)
        conv2_4=self.op_conv2_3(conv2_2)
        conv2_6=self.op_conv2_5(conv2_4)
        conv2_16=self.op_conv2_13(conv2_6)
        conv2_23,conv2_24=self.op_conv2_17(conv2_16)
        conv2_31,conv2_32=self.op_conv2_25(conv2_24)
        #网络第三层
        conv3_1=self.op_conv3_1(conv2_32)
        #网络第四层
        conv4_10=self.op_conv4_7(conv3_1)
        conv4_17,conv4_18=self.op_conv4_11(conv4_10)
        conv4_25,conv4_26=self.op_conv4_19(conv4_18)
        conv4_33,conv4_34=self.op_conv4_27(conv4_26)
        #网络第五层
        conv5_1=F.interpolate(conv4_34,scale_factor=2,mode='bilinear')
        conv5_3=self.op_conv5_2(conv5_1)
        conv5_4=paddle.add(conv5_3,conv2_31)
        conv5_5=F.relu(conv5_4)
        conv5_7=self.op_conv5_6(conv5_5)
        conv5_8=paddle.add(conv5_7,conv2_34)
        conv5_9=F.relu(conv5_8)
        conv5_10=F.interpolate(conv5_9,scale_factor=2,mode='bilinear')
        #输出层
        sub1_out=self.op_sub1_out(conv2_35)
        sub2_out=self.op_sub2_out(conv2_32)
        sub3_out=self.op_sub3_out(conv4_34)
        conv5_out=self.op_conv5_out(conv5_10)
        return sub1_out,sub2_out,sub3_out,conv5_out

#准备数据集
imageset=ImageSet()
dataloader=DataLoader(imageset,batch_size=2,shuffle=True,drop_last=True)
#准备模型
icnet=ICNet(2)  #分2类
model=paddle.Model(icnet)  #,inputs=input,labels=label)
#准备优化器
optimizer=fluid.optimizer.Adam(learning_rate=0.0001,parameter_list=model.parameters())
#开始训练
epoch=10  #训练10代
for i in range(epoch):
    for batch_id,data in enumerate(dataloader()):
        print('第{0}/{1}代，{2}次训练。'.format((i+1),epoch,batch_id))
        x_data=data[0]
        y_data=data[1]
        sub1_out,sub2_out,sub3_out,conv5_out=model(x_data)
        loss_sub1=F.cross_entropy(conv5_out,y_data)
        #loss_sub2=F.cross_entropy(sub2_out,y_data)
        #loss_sub3=F.cross_entropy(sub3_out,y_data)
        #loss_conv5=F.cross_entropy(conv5_out,y_data)
        #loss=paddle.mean([loss_sub1,loss_sub2,loss_sub3,loss_conv5])
        optimizer.minimize(loss_sub1)
        optimizer.clear_gradients()

问题：
File "e:/luqinghua/ICNet/ICNet.py", line 237, in <module>
    sub1_out,sub2_out,sub3_out,conv5_out=model(x_data)
TypeError: 'Model' object is not callable

**Comment by juncaipeng** [comment]
paddle.Model是对模型的封装，只支持fit和evaluate等函数，具体参考：https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/Model_cn.html#model

如果使用model(input)，就不需要paddle.Model对model进行封装。

**Comment by shingstone-lu** [comment]
> paddle.Model是对模型的封装，只支持fit和evaluate等函数，具体参考：https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/Model_cn.html#model
> 
> 如果使用model(input)，就不需要paddle.Model对model进行封装。

非常感谢您的建议。
有一个问题想追问一下，我将paddle升级到2.1.0之后参考：
https://www.paddlepaddle.org.cn/documentation/docs/zh/tutorial/cv_case/convnet_image_classification/convnet_image_classification.html
上面的例子，为什么找不到paddle.optimizer？

**Comment by juncaipeng** [comment]
应该不会啊，可以搜到的api都是可以找到的。你可以再检查一下，如果还有问题可以贴出来错误信息。

**Comment by shingstone-lu** [comment]
我用VS code编辑的.py文件，就是简单的：
import paddle
paddle.optimizer
VS code不能提示optimizer，强行输入的话也无法导航到定义。

**Comment by shingstone-lu** [comment]
我发现需要这样引用：
import paddle
paddle.paddle.optimizer.Adam(parameters=mynet.parameters())
