### ISSUE TITLE
验证paddle安装是否成功，输入paddle.utils.run_check()时命令行长时间没有信息返回

### ISSUE THREAD

**Issue by dahuacai** [PaddlePaddle/Paddle#33725]
**安装**paddle后，为了验证paddle安装是否成功，输入paddle.utils.run_check()时命令行长时间却没有信息返回，为什么？

- 版本、环境信息：
    1）**PaddlePaddle**版本：2.1.0
    3）**GPU**：cuda10.1,cudnn7.6.5
    4）**系统环境**：win7下虚拟机ubuntu16.04、Python版本3.8.0

- 安装方式信息：
pip安装

**Comment by juncaipeng** [comment]
官方没有验证虚拟机支持安装的情况，请根据实际情况排查。

估计是虚拟机的特殊情况导致。windows也是可以支持安装的。

**Comment by nicolas-echo** [comment]
> 您好，我们已经收到了您的问题，会安排技术人员尽快解答您的问题，请耐心等待。请您再次检查是否提供了清晰的问题描述、复现代码、环境&版本、报错信息等。同时，您也可以通过查看[官网API文档](https://www.paddlepaddle.org.cn/documentation/docs/zh/api_cn/index_cn.html)、[常见问题](https://www.paddlepaddle.org.cn/documentation/docs/zh/faq/index_cn.html)、[历史Issue](https://github.com/PaddlePaddle/Paddle/issues)、[AI社区](https://ai.baidu.com/forum/topic/list/168)来寻求解答。祝您生活愉快～
> 
> Hi! We've received your issue and please be patient to get responded. We will arrange technicians to answer your questions as soon as possible. Please make sure that you have posted enough message to demo your request. You may also check out the [API](https://www.paddlepaddle.org.cn/documentation/docs/zh/api_cn/index_cn.html)，[FAQ](https://www.paddlepaddle.org.cn/documentation/docs/zh/faq/index_cn.html)，[Github Issue](https://github.com/PaddlePaddle/Paddle/issues) and [AI community](https://ai.baidu.com/forum/topic/list/168) to get the answer.Have a nice day!

您好，我遇见了同样的问题，paddle.utils.run_check()能返回正确安装的信息，但是用时很久，请问是什么原因呢？import paddle要执行很久。
版本、环境信息：
   1）PaddlePaddle版本：2.1.0
   3）GPU：cuda10.2,cudnn7.6.5
   4）系统环境：win10、Python版本3.7.0

安装方式信息：
pip安装

**Comment by tianmenggong666** [comment]
我也是
