### ISSUE TITLE
paddle-TRT 不支持FP16

### ISSUE THREAD

**Issue by sdnusqy-art** [PaddlePaddle/Paddle#33740]
PaddlePaddle版本：1.8.5
GPU：1080Ti    cuda：9.0   cudnn：7.6.5   TensorRT:6.0.1.5

使用TensorRT加速，  FP32可以执行，  FP16提示以下问题：
I0623 15:40:04.192951 25583 engine.cc:80] You specify FP16 mode, but the hardware do not support FP16 speed up, use FP32 instead.

**Comment by jiweibo** [comment]
您好，1080Ti应该是sm6x吧，应该是没有tensor core计算单元的，不支持fp16计算的哈
