### ISSUE TITLE
What is the difference between PROJ_ROOT and CMAKE_SOURCE_DIR

### ISSUE THREAD

**Issue by wangkuiyi** [PaddlePaddle/Paddle#3374]
I noticed that in [`/CMakeLists.txt`](https://github.com/PaddlePaddle/Paddle/blob/develop/CMakeLists.txt#L17), there defines

```cmake
set(PROJ_ROOT ${CMAKE_CURRENT_SOURCE_DIR})
```

Does this mean that `PROJ_ROOT` is exactly `CMAKE_SOURCE_DIR`?

**Comment by gangliao** [comment]
no difference, but it's necessary in some special case. For instance, @emailweixu might use `PaddlePaddle` as a sub-project of his project, then `${CMAKE_SOURCE_DIR}` is not PaddlePaddle root directory. @wangkuiyi

**Comment by gangliao** [comment]
I also think `PROJ_ROOT` is not a good name, at least `PADDLE_xxxx`.

**Comment by wangkuiyi** [comment]
Got the reason. Thanks!  I agree PROJ_ROOT should be renamed somehow. How about `PADDLE_SOURCE_DIR`?

**Comment by gangliao** [comment]
sure
