### ISSUE TITLE
从源码安装的连接死链

### ISSUE THREAD

**Issue by xmuyong** [PaddlePaddle/Paddle#3375]
https://github.com/PaddlePaddle/Paddle/releases

在这个连接下面下载了 Source code (tar.gz)    
README.md 
中连接死链，死链连接如下
[build from source guide](http://www.paddlepaddle.org/develop/doc/getstarted/build_and_install/build_from_source_en.html)

**Comment by NHZlX** [comment]
http://doc.paddlepaddle.org/doc/getstarted/build_and_install/build_from_source_en.html
