### ISSUE TITLE
【比赛】自动化测试环境原生无飞桨框架，应如何在目标系统上实现预测？

### ISSUE THREAD

**Issue by hrdwsong** [PaddlePaddle/Paddle#33765]
您好！我参加了一个深度学习相关的比赛。比赛的平台环境如下：
显卡： NVIDIA Tesla P4×1
Matlab： R2019a (9.6.0.1072779) 64-bit (glnxa64)；
Cuda： 10.1.243；
Cudnn： 7.6.5；
Pytorch： 1.4.0
Python： 3.6.10
操作系统： ubuntu18.04
平台本身不包含paddlepaddle框架。我的参赛工程使用paddlepaddle编写，本地运行OK。比赛的自动化测试平台只能通过上传工程的压缩文件，系统会自动执行main.py文件启动预测脚本。python环境相关的库，也只能通过requirements.txt文件进行自动配置。
现有以下问题亟待解决：
1、对于这种自动化测试平台，应如何通过requirements.txt配置飞桨环境？直接用pip freeze > requirements.txt生成所需的文件，似乎会报错。
2、自动化测试平台还支持编译好的可执行文件进行上传，请问飞桨写的工程可以编译生成可执行文件吗？

**Comment by hrdwsong** [comment]
通过requirements.txt自动安装的方法，系统运行失败，返回的LOG文件如下：
.0.post107, 1.5.1.post87, 1.5.1.post97, 1.5.1.post107, 1.5.2.post87, 1.5.2.post97, 1.5.2.post107, 1.6.0rc0.post107, 1.6.0.post97, 1.6.0.post107, 1.6.1.post97, 1.6.1.post107, 1.6.2.post97, 1.6.2.post107, 1.6.3.post97, 1.6.3.post107, 1.7.0.post97, 1.7.0.post107, 1.7.1.post97, 1.7.1.post107, 1.7.2.post97, 1.7.2.post107, 1.8.0.post97, 1.8.0.post107, 1.8.1.post97, 1.8.1.post107, 1.8.2.post97, 1.8.2.post107, 1.8.3.post97, 1.8.3.post107, 1.8.4.post97, 1.8.4.post107, 1.8.5.post97, 1.8.5.post107, 2.0.0a0, 2.0.0b0, 2.0.0rc0, 2.0.0rc1, 2.0.0, 2.0.1, 2.0.2, 2.1.0)
ERROR: No matching distribution found for paddlepaddle_gpu==2.1.0.post112 (from -r /usr/src/app/requirements.txt (line 3))
WARNING: You are using pip version 20.1; however, version 21.1.2 is available.
You should consider upgrading via the '/usr/bin/python3 -m pip install --upgrade pip' command.
Traceback (most recent call last):
  File "/usr/src/app/main.py", line 1, in <module>
    import cv2
ModuleNotFoundError: No module named 'cv2'

**Comment by danleifeng** [comment]
请问您requirements.txt文件是哪儿来的吗
有试着改一下requirements.txt里 paddle安装的版本吗，比如paddlepaddle_gpu==2.0.0 或者paddlepaddle_gpu==2.0.2？

**Comment by hrdwsong** [comment]
解决了。是找不到paddle的下载源，我在requirements文件里加入了链接，就可以了。

opencv_python==4.5.1.48
--find-links https://paddlepaddle.org.cn/whl/mkl/stable.html
paddlepaddle-gpu==2.1.0.post101
PyYAML==5.4.1
