### ISSUE TITLE
打包paddle项目后进行预测

### ISSUE THREAD

**Issue by DongChenwei2000** [PaddlePaddle/Paddle#33789]
在打包paddle项目后进行预测，出现了一个错误：
![HCCSNO(IMA5}D}9{EKA5)}7](https://user-images.githubusercontent.com/71364549/123515334-987c8500-d6c9-11eb-954b-7e77f50ce207.jpg)
出错的函数是paddle.inference.create_predictor,输入参数加载模型预测器失败。打包前是可以正常使用的。

**Comment by jiweibo** [comment]
您好，请确保使用的模型是预测格式的模型。

可以参考下这篇文档：https://paddleinference.paddlepaddle.org.cn/introduction/training_to_deployment.html
