### ISSUE TITLE
交叉验证

### ISSUE THREAD

**Issue by Yelin1506** [PaddlePaddle/Paddle#33787]
- 版本、环境信息：
    1）PaddlePaddle版本：1.7
    2）CPU/GPU：GPU驱动版本：GTX 960M、CUDA:11.2.66
    3）系统环境：Win10
    4）Python版本号:3.8
 问题：在进行二分类的时候，由于数据样本少，如何进行交叉验证。

**Comment by Thunderbrook** [comment]
辛苦再完善下背景信息吧

**Comment by Yelin1506** [comment]
那个已经解决了，我想问一下怎么查看训练的具体结果而不是准确率呢？
