### ISSUE TITLE
段错误

### ISSUE THREAD

**Issue by wjj871125** [PaddlePaddle/Paddle#33788]
- 安装方式信息：
pip安装
- 问题描述：安装完之后，执行：
>>> import paddle
段错误

补充：
开始的gcc版本：4.8.5
后升级为：gcc 版本 9.1.0

**Comment by pangyoki** [comment]
报错信息可以截图看下吗？
麻烦提供下cuda版本、安装指令。
paddle使用的gcc版本一般是gcc8.2

**Comment by wjj871125** [comment]
安装paddle提示成功了，在python3交互模式执行：import paddle，回车出现：段错误，退出交互模式，就结束了。

**Comment by pangyoki** [comment]
看你的描述判断不出来是什么问题。
操作系统、gpu显卡型号，cuda版本，cudnn版本，安装包版本与安装方式，麻烦提供下吧
