### ISSUE TITLE
吐槽分布式文档示例

### ISSUE THREAD

**Issue by OleNet** [PaddlePaddle/Paddle#33791]
我仅仅是想跑一个分布式示例而已，为什么又要装opencv，又要联网，又要手动下载 resnet_static.py.
可不可以再简单一点，给个hello world级别的，不要有那么多外部依赖。

https://www.paddlepaddle.org.cn/documentation/docs/zh/guides/06_distributed_training/cluster_quick_start_cn.html#jingtaituwanzhengdaima

**Comment by yaoxuefeng6** [comment]
感谢反馈 我们会评估下这个需求

**Comment by skywalk163** [comment]
呵呵，我当时看的时候也是一头雾水，吐槽+1

**Comment by skywalk163** [comment]
呵呵，我当时看的时候也是一头雾水，吐槽+1

**Comment by gongweibao** [comment]
感谢指出，我们尽快修正
谢谢！
