### ISSUE TITLE
paddle2.1.0 windows cpu 无法训练paddleocr项目的dbnet网络

### ISSUE THREAD

**Issue by williamlzw** [PaddlePaddle/Paddle#33795]
paddle2.1.0 windows cpu 无法训练paddleocr项目的dbnet网络.
builddataloader卡住了，不知道是不是速度慢卡住了还是什么原因。

**Comment by iclementine** [comment]
这个能给一些具体的信息吗？运行的是什么文件？我请 OCR 的同学来回答一下

**Comment by LDOUBLEV** [comment]
不建议CPU训练，可以在AiStudio上用免费的V100GPU

另外，dbnet网络用的是resnet模型还是mobile net 模型，CPU计算能力有限，尝试
- 更轻量backbone的网络
- 减小batchsize
- use_shared_memory 设置为False， window上num_workers需要设置为0
- 减小输入图像大小

看能否训练起来

**Comment by williamlzw** [comment]
应该是cpu太慢了，以为卡死
