### ISSUE TITLE
AIStudio下飞桨2.1版本训练异常

### ISSUE THREAD

**Issue by skywalk163** [PaddlePaddle/Paddle#33816]
环境为AIstudio notebook 飞桨2.1版本
高级版
运行手册中的例程，出现异常，表现为：
1 执行组网这句指令耗时过长，在mac本机为133ms，而在aistudio下耗时3-13秒不等。

`mnist = paddle.nn.Sequential(
    paddle.nn.Flatten(),
    paddle.nn.Linear(784, 512),
    paddle.nn.ReLU(),
    paddle.nn.Dropout(0.2),
    paddle.nn.Linear(512, 10)
)

`

2 整个程序执行，在notebook下输出 `Epoch 1/5` 后程序就异常终止，但没有任何报错信息。
使用python xx.py执行，有报错信息：

`W0628 19:57:30.066193  2828 device_context.cc:404] Please NOTE: device: 0, GPU Compute Capability: 7.0, Driver API Version: 10.1, Runtime API Version: 10.1
W0628 19:57:30.070677  2828 device_context.cc:422] device: 0, cuDNN Version: 7.6.
The loss value printed in the log is the current step, and the metric is the average value of previous steps.
Epoch 1/5

--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
0   std::thread::_Impl<std::_Bind_simple<ThreadPool::ThreadPool(unsigned long)::{lambda()#1} ()> >::_M_run()
1   std::__future_base::_State_baseV2::_M_do_set(std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> ()>*, bool*)
2   paddle::framework::SignalHandle(char const*, int)
3   paddle::platform::GetCurrentTraceBackString[abi:cxx11]()

----------------------
Error Message Summary:
----------------------
FatalError: `Segmentation fault` is detected by the operating system.
  [TimeInfo: *** Aborted at 1624881458 (unix time) try "date -d @1624881458" if you are using GNU date ***]
  [SignalInfo: *** SIGSEGV (@0x20) received by PID 2828 (TID 0x7fc5c7cb3700) from PID 32 ***]

Segmentation fault (core dumped)`

整体测试程序代码为：

`import paddle
import paddle.vision as vision
import paddle.text as text

paddle.__version__
# Sequential形式组网
mnist = paddle.nn.Sequential(
    paddle.nn.Flatten(),
    paddle.nn.Linear(784, 512),
    paddle.nn.ReLU(),
    paddle.nn.Dropout(0.2),
    paddle.nn.Linear(512, 10)
)

from paddle.vision.transforms import ToTensor
# 训练数据集
train_dataset = vision.datasets.MNIST(mode='train', transform=ToTensor())

# 验证数据集
val_dataset = vision.datasets.MNIST(mode='test', transform=ToTensor())

# 构建模型训练用的Model，告知需要训练哪个模型
model = paddle.Model(mnist)

# 为模型训练做准备，设置优化器，损失函数和精度计算方式
model.prepare(paddle.optimizer.Adam(parameters=model.parameters()), 
              paddle.nn.CrossEntropyLoss(),
              paddle.metric.Accuracy())

# 启动模型训练，指定训练数据集，设置训练轮次，设置每次数据集计算的批次大小，设置日志格式
model.fit(train_dataset, 
          epochs=5, 
          batch_size=64,
          verbose=1)`

代码来自手册：https://www.paddlepaddle.org.cn/documentation/docs/zh/tutorial/quick_start/high_level_api/high_level_api.html

**Comment by TCChenlong** [comment]
您好，这个问题是由于加载数据集时，调用了ToTensor这个导致的，即如下这部分代码：
```
train_dataset = vision.datasets.MNIST(mode='train', transform=ToTensor())
val_dataset = vision.datasets.MNIST(mode='test', transform=ToTensor())
```
您可以换一种处理的方式，使用如下的方式来加载；
```
import paddle.vision.transforms as T
transform = T.Normalize(mean=[127.5], std=[127.5], data_format='CHW')

# 下载数据集
train_dataset = paddle.vision.datasets.MNIST(mode='train', transform=transform)
val_dataset =  paddle.vision.datasets.MNIST(mode='test', transform=transform)
```

这个问题是由于 `ToTensor` 这个API在GPU环境下有些问题，我们已经修复了这个问题，在下一个版本(2.1.1)就会解决；
我们也会尽快更新文档到正确的版本，感谢您的反馈

**Comment by skywalk163** [comment]
确实换到2.1.1就好了，真棒！

**Comment by skywalk163** [comment]
确实换到2.1.1就好了，真棒！

**Comment by chenruhai** [comment]
> 你好，这个问题是由于加载数据集时，调用了ToTensor这个导致的，即如下这部分代码：
> 
> ```
> train_dataset = vision.datasets.MNIST(mode='train', transform=ToTensor())
> val_dataset = vision.datasets.MNIST(mode='test', transform=ToTensor())
> ```
> 
> 你可以换一种处理的方式，使用如下的方式来加载；
> 
> ```
> import paddle.vision.transforms as T
> transform = T.Normalize(mean=[127.5], std=[127.5], data_format='CHW')
> 
> # 下载数据集
> train_dataset = paddle.vision.datasets.MNIST(mode='train', transform=transform)
> val_dataset =  paddle.vision.datasets.MNIST(mode='test', transform=transform)
> ```
> 
> 这个问题是因为`ToTensor`这个在 GPU 环境下的问题，我们已经修复了这个问题，在下一个版本（2.1.1）会解决； 我们很快就会更新文档到正确的版本，感谢您的反馈

我是在2.1.2下运行的，也报错了。看了日志，一样的错误。
