### ISSUE TITLE
AIStudio飞桨2.1单机多卡以及多机多卡并行计算报错

### ISSUE THREAD

**Issue by skywalk163** [PaddlePaddle/Paddle#33822]
在将AIStudio项目升级到2.1版本后，发现以前2.02版本下运行正常的项目无法正常运行。项目地址：https://aistudio.baidu.com/aistudio/projectdetail/1222066

具体表现为3点：

- 1 普通的程序就无法正常运行

，已报issue https://github.com/PaddlePaddle/Paddle/issues/33816

- 2 spawn多卡时，有如下报错：

`W0628 21:36:07.498749  6173 device_context.cc:404] Please NOTE: device: 0, GPU Compute Capability: 7.0, Driver API Version: 10.1, Runtime API Version: 10.1
W0628 21:36:07.502328  6173 device_context.cc:422] device: 0, cuDNN Version: 7.6.
Traceback (most recent call last):
  File "hapispawn.py", line 25, in <module>
    dist.spawn(train)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/distributed/spawn.py", line 458, in spawn
    format(device))
ValueError: `device` should be a string of `cpu`, 'gpu' or 'xpu', but got gpu:0
`

源代码为：
`import paddle
import paddle.distributed as dist

train_dataset = paddle.vision.datasets.MNIST(mode='train')
test_dataset = paddle.vision.datasets.MNIST(mode='test')
lenet = paddle.vision.models.LeNet()

# Mnist继承paddle.nn.Layer属于Net，model包含了训练功能
model = paddle.Model(lenet)

# 设置训练模型所需的optimizer, loss, metric
model.prepare(
    paddle.optimizer.Adam(learning_rate=0.001, parameters=model.parameters()),
    paddle.nn.CrossEntropyLoss(),
    paddle.metric.Accuracy(topk=(1, 2))
    )
def train():
    # 启动训练
    model.fit(train_dataset, epochs=1, batch_size=64, log_freq=400)

    # 启动评估
#     model.evaluate(test_dataset, log_freq=20, batch_size=64)
    
if __name__ == '__main__':
    dist.spawn(train)`

- 3 Fleet多机多卡时，报错：

`launch train in GPU mode!
INFO 2021-06-28 21:51:22,211 launch_utils.py:510] Local start 1 processes. First process distributed environment info (Only For Debug): 
    +=======================================================================================+
    |                        Distributed Envs                      Value                    |
    +---------------------------------------------------------------------------------------+
    |                       PADDLE_TRAINER_ID                        0                      |
    |                 PADDLE_CURRENT_ENDPOINT                 127.0.0.1:38971               |
    |                     PADDLE_TRAINERS_NUM                        1                      |
    |                PADDLE_TRAINER_ENDPOINTS                 127.0.0.1:38971               |
    |                     PADDLE_RANK_IN_NODE                        0                      |
    |                 PADDLE_LOCAL_DEVICE_IDS                        0                      |
    |                 PADDLE_WORLD_DEVICE_IDS                        0                      |
    |                     FLAGS_selected_gpus                        0                      |
    |             FLAGS_selected_accelerators                        0                      |
    +=======================================================================================+

INFO 2021-06-28 21:51:22,211 launch_utils.py:514] details abouts PADDLE_TRAINER_ENDPOINTS can be found in log/endpoints.log, and detail running logs maybe found in log/workerlog.0
launch proc_id:3114 idx:0
2021-06-28 21:51:27,161-INFO: [topology.py:152:__init__] HybridParallelInfo: rank_id: 0, dp_degree: 1, mp_degree: 1, pp_degree: 1, dp_group: [0], mp_group: [0], pp_group: [0], check/clip group: [0]
W0628 21:51:27.163012  3114 device_context.cc:404] Please NOTE: device: 0, GPU Compute Capability: 7.0, Driver API Version: 10.1, Runtime API Version: 10.1
W0628 21:51:27.166529  3114 device_context.cc:422] device: 0, cuDNN Version: 7.6.
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/distributed/fleet/base/fleet_base.py:696: UserWarning: It is recommended to use DistributedStrategy in fleet.init(). The strategy here is only for compatibility. If the strategy in fleet.distributed_optimizer() is not None, then it will overwrite the DistributedStrategy in fleet.init(), which will take effect in distributed training.
  "It is recommended to use DistributedStrategy "

--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
0   std::thread::_Impl<std::_Bind_simple<ThreadPool::ThreadPool(unsigned long)::{lambda()#1} ()> >::_M_run()
1   std::__future_base::_State_baseV2::_M_do_set(std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> ()>*, bool*)
2   paddle::framework::SignalHandle(char const*, int)
3   paddle::platform::GetCurrentTraceBackString[abi:cxx11]()

----------------------
Error Message Summary:
----------------------
FatalError: `Segmentation fault` is detected by the operating system.
  [TimeInfo: *** Aborted at 1624888296 (unix time) try "date -d @1624888296" if you are using GNU date ***]
  [SignalInfo: *** SIGSEGV (@0x20) received by PID 3114 (TID 0x7feed0b3a700) from PID 32 ***]

INFO 2021-06-28 21:51:40,245 launch_utils.py:327] terminate all the procs
ERROR 2021-06-28 21:51:40,245 launch_utils.py:584] ABORT!!! Out of all 1 trainers, the trainer process with rank=[0] was aborted. Please check its log.
INFO 2021-06-28 21:51:43,248 launch_utils.py:327] terminate all the procs`

源代码：
` 
import paddle #这是有3处改动的版本
from paddle.vision.transforms import ToTensor
#分布式step 1: 导入paddle.distributed.fleet包
from paddle.distributed import fleet

train_dataset = paddle.vision.datasets.MNIST(mode='train', transform=ToTensor())
test_dataset = paddle.vision.datasets.MNIST(mode='test', transform=ToTensor())

# 加载训练集 batch_size 设为 64
train_loader = paddle.io.DataLoader(train_dataset, batch_size=64, shuffle=True)

# 分布式step 2: 初始化fleet
fleet.init(is_collective=True)

def train():
    

    epochs = 1
    net = paddle.vision.models.LeNet()
    adam = paddle.optimizer.Adam(learning_rate=0.001, parameters=net.parameters())

    # 分布式step 3: 通过fleet获取分布式优化器和分布式模型
    strategy = fleet.DistributedStrategy()
    adam = fleet.distributed_optimizer(adam, strategy=strategy)
    net = fleet.distributed_model(net)

    # 用Adam作为优化函数
    for epoch in range(epochs):
        for batch_id, data in enumerate(train_loader()):
            x_data = data[0]
            y_data = data[1]
            predicts = net(x_data)  
            acc = paddle.metric.accuracy(predicts, y_data, k=2)
            avg_acc = paddle.mean(acc)
            loss = paddle.nn.functional.cross_entropy(predicts, y_data, reduction='mean') 
            loss.backward() #这里手册误写成了avg_loss
            if batch_id % 400 == 0:
                print("epoch: {}, batch_id: {}, loss is: {}, acc is: {}".format(epoch, batch_id, loss.numpy(), avg_acc.numpy())) #这里手册误写成了avg_loss
            adam.step()
            adam.clear_grad()

if __name__ == '__main__':
    train()`

执行命令为：fleetrun --gpus=0 normal_fleet.py

**Comment by iclementine** [comment]
能否给一下你的 paddle 版本号，甚至 commit 号。因为我查找 spawn 那一行的报错的时候发现和 2.0 分支的不同，和 2.1 分支的也不同。

>File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/distributed/spawn.py", line 458, in spawn format(device)) ValueError: deviceshould be a string ofcpu, 'gpu' or 'xpu', but got gpu:0 

这里看起来应该是设备的字符串检查机制发生了变化，比如说由 "gpu" 变成了  "gpu:0" 之类的，你可能需要报一下 commit id 才能定位问题。如果确实出现了不兼容，那么可能代码需要升级。

通过这个方式可以得到 commit id
<img width="556" alt="图片" src="https://user-images.githubusercontent.com/16222986/123768768-35723480-d8fb-11eb-8055-2acf96225a59.png">

第二个问题应该也和 ToTensor 的使用有关。可以尝试把 ToTensor 去掉。目前 dataset 出来的数据可以是 numpy.ndarray, dataloader 会把最后的处理结果转成 Tensor.

**Comment by skywalk163** [comment]
使用的AIStudio里面默认的2.1版本
commit号为：4ccd9a0a86ad550a861c954d70e28ef15741b310
经比对commit号，跟官网这条安装命令装上的版本一样
python -m pip install paddlepaddle-gpu==2.1.0.post101 -f https://paddlepaddle.org.cn/whl/mkl/stable.html

升级到最新的2.1.1版本，报错问题`deviceshould be a string ofcpu, 'gpu' or 'xpu', but got gpu:0`解决
python -m pip install paddlepaddle-gpu==2.1.1.post101 -f https://paddlepaddle.org.cn/whl/mkl/stable.html

**Comment by skywalk163** [comment]
升级到2.1.1版本，前面3个问题解决！
