### ISSUE TITLE
[Q] 如何通过布尔值进行slice？

### ISSUE THREAD

**Issue by gongel** [PaddlePaddle/Paddle#33827]
Hi，

  a 是shape为3x4的tensor，类型为bool，值为True或者False；
  b是shape为3x4x128的tensor，类型为float32，目前想通过a去slice b，取出b中前两维是True的元素；
  请问有啥方法可以完成吗？masked_select由于shape不一致无法完成。

感谢

**Comment by huangjun12** [comment]
试下先expand_as再masked_select

**Comment by gongel** [comment]
expand_as扩展的维度必须为1，不可以。最终通过 先tile后masked_select解决了，感谢提供思路～
