### ISSUE TITLE
如何为gru网络自定义激活函数

### ISSUE THREAD

**Issue by JayFu** [PaddlePaddle/Paddle#33830]
欢迎您对PaddlePaddle提出建议，非常感谢您对PaddlePaddle的贡献！
在留下您的建议时，辛苦您同步提供如下信息：
- 版本、环境信息
1）PaddlePaddle版本：2.1
2）CPU/GPU：CPU
3）系统环境：osx 11.4

使用动态图搭建了一个简单的LSTM网络完成训练任务后，将LSTM层改为GRU层，训练出现Loss nan问题。
想把激活函数修改为relu6，如何修改？

另：在DCU环境安装paddle2.1时，包版本标明miopen2.11，运行时提示miopen版本为3.1。是否2.11=3.1？
`WARNING: device: 0. The installed Paddle is compiled with MIOPEN 3.1, but MIOPEN version in your machine is 2.9, which may cause serious incompatible bug. Please recompile or reinstall Paddle with compatible MIOPEN version.`

**Comment by huangjun12** [comment]
改一下源码吧 https://github.com/PaddlePaddle/Paddle/blob/89fdd6c8f569fe20b7699ca20488f603ca2636ba/python/paddle/nn/layer/rnn.py#L653
