### ISSUE TITLE
paddle英文版主页

### ISSUE THREAD

**Issue by kaixin-bai** [PaddlePaddle/Paddle#33837]
paddlepaddle是否有英文版主页？

**Comment by huangjun12** [comment]
https://www.paddlepaddle.org.cn/documentation/docs/en/guides/index_en.html 目前文档页面有英文版

**Comment by kaixin-bai** [comment]
> https://www.paddlepaddle.org.cn/documentation/docs/en/guides/index_en.html 目前文档页面有英文版

不会中文的人打开主页找不到英文文档的入口，同时希望官网主页上提供英文的介绍视频，要不在公司里推广paddle的时候我好难哦呜呜
