### ISSUE TITLE
Paddle Fluid 开发者指南 5多设备支持问题

### ISSUE THREAD

**Issue by crispyberry** [PaddlePaddle/Paddle#33833]
在根据文档模拟在相应位置添加一个新硬件后，重新编译后调用core.newPlace()，显示没有这个attribute。后续更改了pybind的部分内容后依然前端识别不出来新加的硬件。请问怎么解决？

**Comment by TCChenlong** [comment]
请问您参考的文档具体是哪一篇呢？

**Comment by crispyberry** [comment]
您好！
参考的是：
https://github.com/PaddlePaddle/docs/blob/release/1.2/doc/fluid/getstarted/Developer%27s_Guide_to_Paddle_Fluid.md
第五部分

Chen Long ***@***.***> 于2021年6月30日周三 上午9:06写道：

**Comment by qili93** [comment]
@ssslvky 根据这个文档，添加一个新的硬件需要执行三步，其中：

第一步：要在Paddle源码中添加新的设备

文档这里只是一个简单描述，实际需要在paddle/fluid/platform下修改大量代码来接入新硬件的driver/runtime api，不仅仅是devicecontext，还有包括设备的stream/event/memory等管理，使得新的硬件能作为一个计算资源被Paddle进行识别和调度，以CUDA为例，Paddle需要CUDA的dirver/runtime API来对训练作业进行调度，仅在API层面添加一个新的newPlace是无法实现Paddle支持一个新的硬件设备的。

第二步 & 第三步：开发对应硬件的算子Kernel

这里也需要针对新的硬件开发对应的算子kernel，例如通过CUDA Kernel写GPU的算子，才能运行在CUDAPlace上。否则就会出现kernel not found的错误。

请问您是想要支持什么类型的新型硬件设备呢？
