### ISSUE TITLE
训练fc网络效率不高

### ISSUE THREAD

**Issue by yudan02** [PaddlePaddle/Paddle#3385]
利用paddle训练一个5层的神经网络，训练速度比之前用caffe慢了3-4倍，这是什么原因？
以下是我的网络结构
![default](https://user-images.githubusercontent.com/30890157/29157284-cce438fe-7dd8-11e7-9b1e-e0b5a23e97ab.png)
这是我的训练代码
![default](https://user-images.githubusercontent.com/30890157/29157354-2795de7e-7dd9-11e7-98ab-752a6fb27c9b.png)
![default](https://user-images.githubusercontent.com/30890157/29157362-32f1cd78-7dd9-11e7-9a92-e5cd33c7d9d3.png)

**Comment by luotao1** [comment]
@yudan02 的测试结果是：caffe需要10s，paddle需要30s，其中30s内10s是花在数据读入上面。
