### ISSUE TITLE
fleet分布式训练中，如何全局同步某个variable

### ISSUE THREAD

**Issue by minghaoBD** [PaddlePaddle/Paddle#33855]
为使您的问题得到快速解决，在建立Issues前，请您先通过如下方式搜索是否有相似问题:【搜索issue关键字】【使用labels筛选】【官方文档】

- 版本、环境信息：
    1）PaddlePaddle版本：paddlepaddle-gpu==2.1.1
    2）CPU：-
    3）GPU：V100, CUDA10.1 
    4）系统环境：-

- 训练信息
    1）单机，多卡
    2）显存信息 -
    3）Operator信息 -

- 问题描述：请详细描述您的问题，同步贴出报错信息、日志、可复现的代码片段

在静态图中，我在参照fleet的[教程](https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/guides/06_distributed_training/cluster_quick_start_cn.html)进行单机多卡训练，现在想在各个GPU卡片上同步某一个variable，强制他们相同。想这么做是观测到在fleet训练时，不同GPU上的参数是会有差异的（不是很大），但是我们现在在做的项目对于某一个variable比较严格，要控制他在across-GPU level完全相同。 所以请问可以有类似的broadcast机制供使用吗？

**Comment by Aurelius84** [comment]
可以参考这里的文档：https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/distributed/broadcast_cn.html#broadcast

**Comment by minghaoBD** [comment]
> 可以参考这里的文档：https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/distributed/broadcast_cn.html#broadcast

谢谢。我调用后，报错如下：
![image](https://user-images.githubusercontent.com/79566150/123931935-8c434100-d9c3-11eb-8c65-398192ebd513.png)
请问要做什么转换吗？

**Comment by minghaoBD** [comment]
> 可以参考这里的文档：https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/distributed/broadcast_cn.html#broadcast

我现在用program.global_block().var(var_name)拿到了framework.Variable。但是broadcast没有起作用，这个variable依然没有同步。请问还有其他方法吗？

**Comment by sandyhouse** [comment]
没起作用是什么意思，调用没有效果？请贴一下相关代码吧，谢谢。
