### ISSUE TITLE
nvidia/cuda:11.2.0 container paddlepaddle 報錯

### ISSUE THREAD

**Issue by jeremyevith** [PaddlePaddle/Paddle#33889]
我先透過以下方式產生Docker映像

```
FROM nvidia/cuda:11.2.0-runtime-ubuntu20.04

ENV CUDNN_VERSION 8.1.1.33

LABEL com.nvidia.cudnn.version="${CUDNN_VERSION}"

RUN apt-get update && apt-get install -y --no-install-recommends \
    libcudnn8=$CUDNN_VERSION-1+cuda11.2 \
    && apt-mark hold libcudnn8 && \
    rm -rf /var/lib/apt/lists/*

ENV  LD_LIBRARY_PATH="/usr/local/cuda-11.2/lib64:/usr/local/cuda-11.2/targets/x86_64-linux/lib:$LD_LIBRARY_PATH"

```

並在映像內安裝 PaddleOCR 以及 PaddlePaddle cuda 11.2 版本

```
pip3 install paddlepaddle-gpu==2.1.0.post112 -f https://paddlepaddle.org.cn/whl/mkl/stable.html
pip3 install paddleocr
```

PaddleOCR進行推理時會報錯

**(PreconditionNotMet) Cannot load cudnn shared library. Cannot invoke method cudnnGetVersion.
  [Hint: cudnn_dso_handle should not be null.] (at /paddle/paddle/fluid/platform/dynload/cudnn.cc:59)**

研究了三天了都還沒解決... 有人可以幫忙的嗎?

**Comment by LDOUBLEV** [comment]
看报错是找不到cudnn 库

推荐用Paddle官方镜像
registry.baidubce.com/paddlepaddle/paddle:2.1.0-gpu-cuda11.2-cudnn8

**Comment by jeremyevith** [comment]
我是用nvidia官方的，cudnn是有安裝的但Paddle找不到

https://gitlab.com/nvidia/container-images/cuda/blob/master/dist/11.2.0/ubuntu20.04-x86_64/runtime/cudnn8/Dockerfile

**Comment by LDOUBLEV** [comment]
设置下CUDNN的环境变量，paddle的docker，cudnn默认安装在
/usr/lib/x86_64-linux-gnu/

可以对比下你cudnn的安装目录，

**Comment by jeremyevith** [comment]
ln -s /usr/lib/x86_64-linux-gnu/libcudnn.so.8 libcudnn.so
ln -s /usr/local/cuda-11.2/targets/x86_64-linux/lib/libcublas.so.11 libcublas.so
ln -s /usr/local/cuda-11.2/targets/x86_64-linux/lib/libcusolver.so.11 libcusolver.so

添加這三行解決了 謝謝
