### ISSUE TITLE
使用 config.enable_tensorrt_engine接口量化失败

### ISSUE THREAD

**Issue by zsffuture** [PaddlePaddle/Paddle#33880]
发生异常: ValueError
(InvalidArgument) Pass tensorrt_subgraph_pass has not been registered. Please use the paddle inference library compiled with tensorrt or disable the tensorrt engine in inference configuration! 
  [Hint: Expected Has(pass_type) == true, but received Has(pass_type):0 != true:1.] (at C:\home\workspace\Paddle_release\paddle/fluid/framework/ir/pass.h:216)
  File "D:\paddle_envtest\PaddleDetection-release-2.1\PaddleSlim-release-2.1.0\test.py", line 21, in create_predictor
    predictor = paddle_infer.create_predictor(config)
  File "D:\paddle_envtest\PaddleDetection-release-2.1\PaddleSlim-release-2.1.0\test.py", line 43, in <module>
    pred = create_predictor()

![image](https://user-images.githubusercontent.com/39027951/124047880-a58dd100-da47-11eb-9baa-006b2cf9bccc.png)

**Comment by LDOUBLEV** [comment]
报错提示你的预测库不支持TRT：
```
(InvalidArgument) Pass tensorrt_subgraph_pass has not been registered. Please use the paddle inference library compiled with tensorrt or disable the tensorrt engine in inference configuration!
```

建议使用支持TRT版本的预测库，https://paddle-inference.readthedocs.io/en/latest/user_guides/download_lib.html#linux
