### ISSUE TITLE
Does Paddle support Ninja for building?

### ISSUE THREAD

**Issue by gglin001** [PaddlePaddle/Paddle#33892]
Error raised when using Ninja as cmake generator. Using make is ok. Is my configuration wrong?

**Comment by gglin001** [comment]
I am using `release/2.1` branch

**Comment by LDOUBLEV** [comment]
It is supported to build paddle using Ninja. 
Try:
```
pip install ninja 
cmake  
    -build params
    -GNinja

ninja
```
We will provide documents about build Paddle using Ninja in the future.

**Comment by zhwesky2010** [comment]
please run  ```pip install ninja```    ```cmake .. -GNinja```    ```ninja``` ,
and now Linux system may have bug, Windows system must be fine. 
If there is a bug on linux, we will fixed it later.

**Comment by gglin001** [comment]
thanks for replying!

but I still can't successfully build using Ninja

following

> pip install ninja cmake .. -GNinja ninja

I got error

```
[build] ninja: error: build.ninja:1019: bad $-escape (literal $ must be written as $$)
```

after replacing `$` with `$$` in `build/build.ninja`

start to build

got error

```
[build] ninja: error: 'third_party/install/protobuf/bin/protoc', needed by 'paddle/fluid/platform/profiler_pb2.py', missing and no known rule to make it
```

I tested under a docker environment

```
> docker images

REPOSITORY               TAG       IMAGE ID       CREATED        SIZE
paddlepaddle/paddle      2.1.0     f93cb624a914   7 weeks ago    8.57GB

```

**Comment by gglin001** [comment]
I also test ninja under a Mac, still got error like

> [build] ninja: error: 'SOMETHING', needed by 'SOMETHING_ELSE', missing and no known rule to make it

**Comment by LDOUBLEV** [comment]
It is supported that build paddle using cmake.  The way ninja compiles paddle is still in the testing phase. 
We will support the use of ninja to compile paddle soonly.

**Comment by gglin001** [comment]
还有一个 build 相关的问题, 在构建 debug 项目时, 有一些库 linking 很慢(rebuild 时也会消耗很多时间), 请问有什么办法改进吗? 我注意到 cmake 函数 [`cc_library`](https://github.com/PaddlePaddle/Paddle/blob/develop/cmake/generic.cmake#L296) 默认是创建静态库, 改成默认动态库会遇到一些错误, 请问有对动态库的支持计划吗?

**Comment by zhwesky2010** [comment]
@gglin001 ninja编译在Windows上支持，Linux、Mac还未支持。

**Comment by gglin001** [comment]
hi, 请问目前 Linux  上支持使用 ninja 编译了吗?

**Comment by tiancaishaonvjituizi** [comment]
+1，低效率的基础设施会损耗所有开发者的时间

**Comment by gglin001** [comment]
相关的PR
https://github.com/PaddlePaddle/Paddle/pull/42283

部分第三方库在cmake配置中 hard code使用了 `make`  构建, 将这些修改后应该就能够基本支持 ninja构建(同时兼容正在使用的 make 工具)

希望官方能够重视这个问题, 尽早提供支持
