### ISSUE TITLE
paddle.optimizer.Adam和paddle.paddle.nn.optimizer.Adam

### ISSUE THREAD

**Issue by shingstone-lu** [PaddlePaddle/Paddle#33899]
paddle版本2.1.0
win10操作系统

看了很多2.1.0的例程，发现我这边没有paddle.optimizer.Adam，只能通过paddle.paddle.nn.optimizer.Adam访问，不知道有什么区别？

**Comment by LDOUBLEV** [comment]
API本身没有区别，主要是方便管理和维护，optimizer API移动到了统一的目录下，可以放心使用

**Comment by shingstone-lu** [comment]
> API本身没有区别，主要是方便管理和维护，optimizer API移动到了统一的目录下，可以放心使用

paddle版本什么的也都一致，为什么我这边不能通过paddle直接访问到optimizer呢，是有什么专门的设置吗？

**Comment by LDOUBLEV** [comment]
我这边测试 paddle2.1.0 可以直接找到paddle.optimizer，你重新安装paddle 试下，或者检查下paddle版本
![image](https://user-images.githubusercontent.com/26592129/124123174-8fb0f800-daa9-11eb-892e-efbe7b967658.png)

**Comment by shingstone-lu** [comment]
> 我这边测试 paddle2.1.0 可以直接找到paddle.optimizer，你重新安装paddle 试下，或者检查下paddle版本
> ![image](https://user-images.githubusercontent.com/26592129/124123174-8fb0f800-daa9-11eb-892e-efbe7b967658.png)

![捕获](https://user-images.githubusercontent.com/84372742/124124016-85432e00-daaa-11eb-80ff-03d4b62b119c.PNG)
我使用命令行也可以向你展示的一样。平常编辑代码我使用的是VS Code，可能是VS Code的原因吧。
非常感谢您的回复。
