### ISSUE TITLE
assign 操作巨大bug!!!!!!!!!!!!

### ISSUE THREAD

**Issue by sys1874** [PaddlePaddle/Paddle#33907]
paddle版本：paddlepaddle-gpu    2.1.0
问题：使用assign操作后，被赋值的tensor 直接丢失grad!!!!!!
```
##paddle 代码
import paddle
import numpy as np
ori_a = paddle.to_tensor(np.array([0,0], dtype='float32'), stop_gradient=False)
a = ori_a + 1
b = paddle.to_tensor(np.array([0], dtype='float32'), stop_gradient=False)
a[0] = b
loss = paddle.sum(a*2)
loss.backward()
print(ori_a.grad)
print(b.grad)
```
结果：ori_a的grad = None了。
![image](https://user-images.githubusercontent.com/19858774/124096865-93368600-da8d-11eb-843a-0faf4a5d1ecf.png)

```
##torch 代码
import torch
import numpy as np

ori_a = torch.tensor(np.array([0,0], dtype='float32'))
ori_a.requires_grad = True
a = ori_a + 1
b = torch.tensor(np.array([0], dtype='float32'))
b.requires_grad = True
a[0] = b
loss = torch.sum(a*2)
loss.backward()
print(ori_a.grad)
print(b.grad)
```
结果：ori_a 的grad 依然存在。
![image](https://user-images.githubusercontent.com/19858774/124097205-ea3c5b00-da8d-11eb-99c9-6387be2c38b8.png)

请fix！！！！！！！！！！

**Comment by LDOUBLEV** [comment]
感谢反馈，问题已复现，会尽快修复

**Comment by sys1874** [comment]
同学，这个bug 导致这个assign op之前的所有模型的参数的grad全没了。  :)

**Comment by firestonelib** [comment]
最新develop和2.2分支已经修复了 @sys1874
