### ISSUE TITLE
win10安装paddle2.1.0后无法正常import paddle

### ISSUE THREAD

**Issue by hi-bigcat** [PaddlePaddle/Paddle#33904]

**Comment by hi-bigcat** [comment]
环境：64位win10系统，GPU 1060 6G，python3.6.5，CUDA 10.1
安装命令 python -m pip install paddlepaddle-gpu==2.1.0.post101 -f https://paddlepaddle.org.cn/whl/mkl/stable.html
安装过程无异常，安装后import paddle出现以下错误：
from six.moves import collections_abc ImportError cannot import name 'collections_abc'，详细错误信息如下
![paddle_import](https://user-images.githubusercontent.com/46183033/124091697-aeeb5d80-da88-11eb-8e80-02745f73dbe2.jpeg)
卸载six并重新安装后依旧出现上述错误

**Comment by hi-bigcat** [comment]
全部重新安装了cuda和cudnn，卸载并重新安装了paddle，升级了pip，six，重启shell后，paddle安装和调试成功，已经解决

**Comment by LDOUBLEV** [comment]
大佬牛皮，问题应该是six版本问题，以后遇到类似问题可以先调整第三方库的版本，这个问题和cuda cudnn关系不大
