### ISSUE TITLE
自述文件

### ISSUE THREAD

**Issue by jhcgt4869** [PaddlePaddle/Paddle#33908]
![image](https://user-images.githubusercontent.com/61859193/124101146-a51a2800-da91-11eb-8688-aade8ee87ece.png)
关于自述文件不符的内容，自述文件中最新版本2.0,5月就已经发布了2.1，就在1小时前发布了2.1.1.第二5月就已经修改了AIstudio算力模式，为8算力卡，8-16小时模式，但是文章还是处于滞后状态，希望及时修改，你们也辛苦了~~~

**Comment by LDOUBLEV** [comment]
感谢反馈，可以发一下这个文章链接吗

**Comment by GT-ZhangAcer** [comment]
> 感谢反馈，可以发一下这个文章链接吗

https://github.com/PaddlePaddle/Paddle/blob/develop/README_cn.md

链接应该是这个了 哈哈哈

**Comment by jhcgt4869** [comment]
https://github.com/PaddlePaddle/Paddle/blob/develop/README_cn.md
这个还要地址有点惊讶，嘎嘎嘎嘎

**Comment by LDOUBLEV** [comment]
好的，收到
