### ISSUE TITLE
jetson nano部署CPU推理正常 GPU推理报错

### ISSUE THREAD

**Issue by QQ39272490** [PaddlePaddle/Paddle#33910]
问题类型：模型部署
问题描述
部署环境：Jetson nano，Jetpack 4.5 python3.6+nv_jetson-cuda10.2-cudnn8-trt7
安装官方提供的库 paddlepaddle_gpu-2.1.0-cp36-cp36m-linux_aarch64.whl
代码步骤如：https://paddleinference.paddlepaddle.org.cn/demo_tutorial/cuda_jetson_demo.html
config.EnableUseGpu(500, 0);
[使用GPU报错，停用GPU正常。报错代码如下图
![QQ图片20210701173757](https://user-images.githubusercontent.com/2766645/124103552-f88d7580-da93-11eb-83f2-53de9313301d.png)

**Comment by LDOUBLEV** [comment]
关闭TensorRT 是否能正常预测，你的模型是哪个

**Comment by QQ39272490** [comment]
用的mobileNetV1 关闭TensorRT也一样

**Comment by LDOUBLEV** [comment]
我在Nano上测试了一下，可以运行GPU版本的预测

Nano 环境：
![image](https://user-images.githubusercontent.com/26592129/124124695-57aab480-daab-11eb-9b5f-b0e2f6f68d72.png)

使用的模型是：
[MobileNetV1_infer.tar.zip](https://github.com/PaddlePaddle/Paddle/files/6748060/MobileNetV1_infer.tar.zip)


执行预测的逻辑是：python3 infer.py --model_file ./MobileNetV1_infer/inference.pdmodel  --params_file ./MobileNetV1_infer/inference.pdiparams
代码是：
```
import paddle
import argparse
import numpy as np
import paddle.inference as inference
from paddle.inference import Config
from paddle.inference import create_predictor
import cv2
import os

def parse_args():
    parser = argparse.ArgumentParser()
    parser.add_argument("--model_file", type=str, help="model filename")
    parser.add_argument("--params_file", type=str, help="parameter filename")
    parser.add_argument("--batch_size", type=int, default=1, help="batch size")

    return parser.parse_args()


def set_config(args):
    config = Config(args.model_file, args.params_file)
    config.disable_gpu()
    config.switch_use_feed_fetch_ops(False)
    config.switch_specify_input_names(True)
    return config


def main():
    args = parse_args()

    # 设置AnalysisConfig
    config = set_config(args)
    config.enable_use_gpu(200, 0) # use_gpu
    config.enable_memory_optim()
    config.enable_tensorrt_engine(
                precision_mode=inference.PrecisionType.Float32,
                max_batch_size=2)
    predictor = create_predictor(config)
    input_names = predictor.get_input_names()
    input_handle = predictor.get_input_handle(input_names[0])

    fake_input = np.random.randn(1, 3, 224, 224).astype("float32")
    print("fake_input:",fake_input.shape)
    input_handle.copy_from_cpu(fake_input)
    # 运行predictor
    predictor.run()
    # 获取输出
    output_names = predictor.get_output_names()
    output_handle = predictor.get_output_handle(output_names[0])
    out = output_handle.copy_to_cpu()   # numpy.ndarray类型

    print("out: ",out.shape)

main()
```

**Comment by LDOUBLEV** [comment]
[MobileNetV1_infer.tar.zip](https://github.com/PaddlePaddle/Paddle/files/6748060/MobileNetV1_infer.tar.zip)

**Comment by QQ39272490** [comment]
我手中版本是nano 2G版本，运行至这个地方一直没动静了
![image](https://user-images.githubusercontent.com/2766645/124207900-0802d200-db19-11eb-8728-59d44e1a9f87.png)

**Comment by QQ39272490** [comment]
![image](https://user-images.githubusercontent.com/2766645/124208106-76e02b00-db19-11eb-9c78-025c11cace19.png)

**Comment by QQ39272490** [comment]
![image](https://user-images.githubusercontent.com/2766645/124208182-9c6d3480-db19-11eb-8490-8491904b0782.png)

**Comment by LDOUBLEV** [comment]
你关闭TRT预测吧，把这一行屏蔽掉

```
config.enable_tensorrt_engine(
                precision_mode=inference.PrecisionType.Float32,
                max_batch_size=2)
```

**Comment by QQ39272490** [comment]
![QQ图片20210701173629](https://user-images.githubusercontent.com/2766645/124210246-ab55e600-db1d-11eb-883f-2a3f52f45ee2.png)
还是一样没动静。。。

**Comment by QQ39272490** [comment]
关闭GPU就正常了

**Comment by QQ39272490** [comment]
![image](https://user-images.githubusercontent.com/2766645/124221602-abacac00-db32-11eb-8b33-d9862b224a91.png)

**Comment by LDOUBLEV** [comment]
测试其他模型是否能GPU预测，如果也不行，那应该是环境问题，可以尝试
- 检查cuda、cudnn是否都安装好了
- 更换其他paddle版本

**Comment by QQ39272490** [comment]
![image](https://user-images.githubusercontent.com/2766645/124228939-7bb7d580-db3f-11eb-8fff-d56edd2c39c5.png)
![image](https://user-images.githubusercontent.com/2766645/124229023-92f6c300-db3f-11eb-90d0-e87bcfb83413.png)
cuda cudnn 都没问题 
paddle发布了2.1.1在哪可下载适合的whl库文件？

**Comment by LDOUBLEV** [comment]
下载链接： 
预测库：
https://paddle-inference-lib.bj.bcebos.com/2.1.1-nv-jetson-jetpack4.4-nano/paddle_inference_install_dir.tgz
whl包
https://paddle-inference-lib.bj.bcebos.com/2.1.1-nv-jetson-jetpack4.4-nano/paddlepaddle_gpu-2.1.1-cp36-cp36m-linux_aarch64.whl

**Comment by QQ39272490** [comment]
我看到桌面出现System throttled due to over-current，会不会是过流受限制了？

**Comment by LDOUBLEV** [comment]
没有限制的，检查下网络吧

**Comment by QQ39272490** [comment]
网络肯定是没有问题，我烧了4.4没出现System throttled due to over-current，也下载了2.0的paddle-gpu版本，还是一样的问题，没有解决

**Comment by LDOUBLEV** [comment]
> whl包
https://paddle-inference-lib.bj.bcebos.com/2.1.1-nv-jetson-jetpack4.4-nano/paddlepaddle_gpu-2.1.1-cp36-cp36m-linux_aarch64.whl

尝试下提供的这个paddle  whl包，我的机器上测试是可以的。

**Comment by QQ39272490** [comment]
@LDOUBLEV 方便加个微信或QQ吗？我是nano 2G版本，你是测试的哪种模型呢？

**Comment by wangye707** [comment]
https://github.com/PaddlePaddle/Paddle/issues/31767

**Comment by wangye707** [comment]
这里回复了问题，https://github.com/PaddlePaddle/Paddle/issues/31767

**Comment by QQ39272490** [comment]
@wangye707 方便回你个QQ吗？

**Comment by QQ39272490** [comment]
感谢百度的兄弟回复，我是用的2G版本内存有点少，估计内存问题 用GPU时 config.enable_use_gpu(0, 0) 可以了

**Comment by QQ39272490** [comment]
用GPU时 config.enable_use_gpu(0)最大显存

**Comment by QQ39272490** [comment]
还有2G版本最好别连接VNC内存资源不够用

**Comment by QQ39272490** [comment]
还有2G版本最好别连接VNC内存资源不够用
