### ISSUE TITLE
MKLDNN error for ppyolov2 model

### ISSUE THREAD

**Issue by xiegegege** [PaddlePaddle/Paddle#33918]
Paddle Test Environment
****************************************
Paddle version: 0.0.0
Paddle With CUDA: True

OS: Ubuntu 16.04
Python version: 3.7.0

CUDA version: 10.1.243
cuDNN version: 7.6
Nvidia driver version: None
CPU: Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz
****************************************

install paddle develop (commit id:1e62c239d323354eccfc974d4e2e6496f93d848e)
```shell
git clone https://github.com/PaddlePaddle/PaddleDetection.git 
cd PaddleDetection
git checkout develop

python -m pip install -r requirments.txt
python tools/export_model.py -c configs/ppyolo/ppyolov2_r50vd_dcn_365e_coco.yml --output_dir=inference_model -o weights=https://paddledet.bj.bcebos.com/models/ppyolov2_r50vd_dcn_365e_coco.pdparams
python deploy/python/infer.py --model_dir=./inference_model/ppyolov2_r50vd_dcn_365e_coco/ --image_file=demo/000000570688.jpg --device=CPU --enable_mkldnn=True
```

<img width="877" alt="767953fbf406aa18918dda343fd810c0" src="https://user-images.githubusercontent.com/46314656/124121722-d0a80d00-daa7-11eb-8530-e0badc8c1152.png">
I have tested this case and it works well in paddle2.1.0 and paddle2.1.1， so this should be  the new problem caused by paddle develop.
The model ttfnet_darknet53_1x_coco has the same problem.

[ppyolov2_cpu_mkldnnn_log.txt](https://github.com/PaddlePaddle/Paddle/files/6748005/ppyolov2_cpu_mkldnnn_log.txt)

**Comment by lidanqing-vv** [comment]
1. 6148 is capable with AVX512, You had this issue because you used some virtual machine ? @xiegegege

**Comment by xiegegege** [comment]
@lidanqing-intel Yes, it's a virtual machine. I tested in some other physical machine, and it works well.

**Comment by jakpiase** [comment]
Hi @xiegegege
#33944 will fix your issue. Your virtual machine probably uses AVX2 and we recommend switching to AVX512, because our performance improvements with oneDNN library are made mainly for that instruction set.

**Comment by xiegegege** [comment]
@jakpiase OK, got it, thank you.

**Comment by lidanqing-vv** [comment]
@xiegegege 
#33944 will solve this error on AVX2 (your virtual machine). But if you test this model on AVX2 environment, it may not be speedup as well as on AVX512 (6148 itself suppots AVX512). Because oneDNN improve well on AVX512.  But in AVX2, some oneDNN op will call reference version (slower).

Anyway, to achieve expected performance, please use avx512. This fix will only guarantee no error on AVX2, but could not guarantee performance on AVX2.

**Comment by xiegegege** [comment]
@lidanqing-intel OK，I will use avx512 in subsequent test.

**Comment by lidanqing-vv** [comment]
@xiegegege @OliverLPH Since the PR has been merged, if you have have verified ok, let me know, I will close this issue.

**Comment by OliverLPH** [comment]
@lidanqing-intel @jakpiase 
@xiegegege verified https://github.com/PaddlePaddle/Paddle/pull/33944 can solve the bug, so this issue will be close, thx~
