### ISSUE TITLE
部署python端infer 推断时候显示out of memory

### ISSUE THREAD

**Issue by xliu79** [PaddlePaddle/Paddle#33926]
分割任务中:
部署python端infer 推断时测试了三张图片 ，其中有一张显示out of memory

Paddle 2.0.0 版本

![1](https://user-images.githubusercontent.com/31554245/124216692-646ded80-db29-11eb-9e38-cd70655def6f.png)
驱动信息：
![image](https://user-images.githubusercontent.com/31554245/124216774-8c5d5100-db29-11eb-94d6-68bab0d209f3.png)
相关代码:

![image](https://user-images.githubusercontent.com/31554245/124216852-b747a500-db29-11eb-939a-fe5dadfb778f.png)

**Comment by wangye707** [comment]
@xliu79 麻烦提供一下图片

**Comment by xliu79** [comment]
链接：https://pan.baidu.com/s/1wcoqld7qNHG5DDXr-gwORg 
提取码：0b7v
放网盘了

**Comment by xliu79** [comment]
链接：https://pan.baidu.com/s/110Yy8s4AfvlqnmAev8yAvQ 
提取码：kjjz
模型地址
