### ISSUE TITLE
WITH_GPU编译后的paddle_inference.dll文件过大，并且开启GPU时不能识别出图片中的文字

### ISSUE THREAD

**Issue by weixing19** [PaddlePaddle/Paddle#33925]
运行summary_env.py获取到环境信息如下：
****************************************
Paddle version: 2.1.0
Paddle With CUDA: False   实际我在CMakeUI中已设置WITH_CUDA

OS: Windows 10
Python version: 3.7.9

CUDA version: 11.0.194
Build cuda_11.0_bu.relgpu_drvr445TC445_37.28540450_0
cuDNN version: None.None.None
Nvidia driver version: None
****************************************
机器为MSI GE602QE笔记本，CPUi7-4720HQ 、内存16G、显卡GTX960M（2G显存）
本地编译，环境为CMake3.17.0 、VS2019、OpenCV4.5.0
编译生成程序后出现两个问题：
1）paddle_inference.dll过大，我第一次编译是1.5G，后来我改了几个参数再次编译为1.2G，仍然太大（我不使用GPU编译出的才41M），怎么能优化变小？
2）用paddle_inference.dll和库文件生成PaddleOCR，使用时开启GPU无法识别出图片中的文字，关闭GPU则识别正常，这如何解决？
![paddle_inference dll](https://user-images.githubusercontent.com/86036510/124213570-69c83980-db23-11eb-89f3-e801a0a8aab0.jpg)

开启GPU进行OCR识别的执行结果如下：
D:\tesseract\PaddleOCR_GPU\win64\Release>ocr_system.exe config.txt ticket.jpg 1
=======Paddle OCR inference config======
char_list_file : ./ppocr_keys_v1.txt
cls_model_dir : ./inference/ch_ppocr_mobile_v2.0_cls_infer/
cls_thresh : 0.9
cpu_math_library_num_threads : 5
det_db_box_thresh : 0.5
det_db_thresh : 0.3
det_db_unclip_ratio : 1.6
det_model_dir : ./inference/ch_ppocr_mobile_v2.0_det_infer/
gpu_id : 0
gpu_mem : 1000
max_side_len : 960
rec_model_dir : ./inference/ch_ppocr_mobile_v2.0_rec_infer/
use_angle_cls : 1
use_fp16 : 0
use_gpu : 1
use_mkldnn : 1
use_polygon_score : 1
use_tensorrt : 0
visualize : 1
=======End of Paddle OCR inference config======
WARNING: Logging before InitGoogleLogging() is written to STDERR
I0702 10:23:51.808200 17516 analysis_config.cc:424] use_dlnne_:0
I0702 10:23:51.813199 17516 analysis_config.cc:424] use_dlnne_:0
I0702 10:23:51.814198 17516 analysis_config.cc:424] use_dlnne_:0
I0702 10:23:51.815196 17516 analysis_config.cc:424] use_dlnne_:0
The detection visualized image saved in ./ocr_vis.png
The predicted text is (0):
准材代段就河海模折／请阁折皖摩d材

Cost  2.40306s
可以看到结果乱码，并且内容不对，如果设置use_gpu : 0则识别结果正常，但是性能较低感觉是paddle_inference.dll文件过大造成的性能下降。

**Comment by weixing19** [comment]
更换为CUDA10.1后识别正常，但是编译后1.8G，也就是问题1文件太大了，如何**缩小**呢？
_1）paddle_inference.dll过大，我第一次编译是1.5G，后来我改了几个参数再次编译为1.2G，仍然太大（我不使用GPU编译出的才41M），怎么能优化变小？_

**Comment by shangzhizhou** [comment]
编译选项CUDA_ARCH_NAME=Auto试下呢
