### ISSUE TITLE
使用paddle.jit.save时，报错~/anaconda3/lib/python3.7/site-packages/gast/gast.py

### ISSUE THREAD

**Issue by yuandanfei** [PaddlePaddle/Paddle#33939]
1）PaddlePaddle版本：2.0.2
    3）GPU：1060，CUDA：10.1和CUDNN：7.6.5
    4）系统环境：Ubuntu18.04、Python3.7
1.使用python -m pip install paddlepaddle-gpu==2.0.2.post101 -f https://paddlepaddle.org.cn/whl/mkl/stable.html时，提示
```
Collecting gast>=0.3.3; platform_system != "Windows"
  Downloading gast-0.5.0-py3-none-any.whl (10 kB)
```
2.在使用paddle.jit.save时，报错~/anaconda3/lib/python3.7/site-packages/gast/gast.py，AssertionError: Bad argument number for Assign: 2, expecting 3

3.卸载gast 0.5.0，然后安装gast 0.3.3后恢复paddle.jit.save正常
```
pip uninstall gast
pip install gast==0.3.3
```

**Comment by wangxicoding** [comment]
感谢反馈，这个问题在最新的develop已经修复了，见PR: https://github.com/PaddlePaddle/Paddle/pull/33850
