### ISSUE TITLE
ctc_greedy_decoder输入为tensor模式训练报错

### ISSUE THREAD

**Issue by zchengquan** [PaddlePaddle/Paddle#33943]
- 版本、环境信息：
    1）PaddlePaddle版本：1.8
    3）GPU：CUDA 10.2, cundnn 7.6
    4）系统环境：Linux python 3.7

- 训练信息
    1）单机单卡
    2）12G
    3）Operator信息

- 复现信息：
采用fluid.layer.ctc_greedy_decoder的tensor输入模式，模型能够顺利setup，但是只要开始run就会爆异常；若改为lodtensor的输入方式则是顺利的，现在业务需要tensor模式的输入。

- 问题描述：请详细描述您的问题，同步贴出报错信息、日志、可复现的代码片段
code配置：
161         predict_pad = fluid.layers.ctc_greedy_decoder(input=decoder_feats, blank=self.char_num, padding_value=0, #decoder_feats是个三维的Tensor, Nx100x30
162         print("predict_pad: {}".format(predict_pad.shape))

日志：
 47 
 48 W0702 15:52:45.114964 14585 init.cc:224] *** Aborted at 1625212365 (unix time) try "date -d @1625212365" if you are using GNU date ***
 49 W0702 15:52:45.117309 14585 init.cc:224] PC: @                0x0 (unknown)
 50 W0702 15:52:45.117658 14585 init.cc:224] *** SIGSEGV (@0x8) received by PID 13016 (TID 0x7f8b12bfd700) from PID 8; stack trace: ***
 51 W0702 15:52:45.119630 14585 init.cc:224]     @     0x7f8bdceb4500 (unknown)
 52 W0702 15:52:45.124258 14585 init.cc:224]     @     0x7f8b7a37ebdb paddle::framework::Tensor::check_memory_size()
 53 W0702 15:52:45.128921 14585 init.cc:224]     @     0x7f8b76c19ec0 paddle::framework::Tensor::data<>()
 54 W0702 15:52:45.133767 14585 init.cc:224]     @     0x7f8b782de018 paddle::operators::CTCAlignOpCUDAKernel<>::Compute()
 55 W0702 15:52:45.136289 14585 init.cc:224]     @     0x7f8b782de623 _ZNSt17_Function_handlerIFvRKN6paddle9framework16ExecutionContextEEZNKS1_24OpKernelRegistrarFunctorINS0_8platform9CUDAPlaceELb0ELm1EINS0_9o    perators20CTCAlignOpCUDAKernelIiEENSA_IlEEEEclEPKcSF_iEUlS4_E_E9_M_invokeERKSt9_Any_dataS4_
 56 W0702 15:52:45.140524 14585 init.cc:224]     @     0x7f8b7a2fa450 paddle::framework::OperatorWithKernel::RunImpl()
 57 W0702 15:52:45.146486 14585 init.cc:224]     @     0x7f8b7a2fac41 paddle::framework::OperatorWithKernel::RunImpl()
 58 W0702 15:52:45.149740 14585 init.cc:224]     @     0x7f8b7a2f3bf1 paddle::framework::OperatorBase::Run()
 59 W0702 15:52:45.154506 14585 init.cc:224]     @     0x7f8b7a0018a6 paddle::framework::details::ComputationOpHandle::RunImpl()
 60 W0702 15:52:45.158820 14585 init.cc:224]     @     0x7f8b79fa8ee1 paddle::framework::details::FastThreadedSSAGraphExecutor::RunOpSync()
 61 W0702 15:52:45.163673 14585 init.cc:224]     @     0x7f8b79fa69df paddle::framework::details::FastThreadedSSAGraphExecutor::RunOp()
 62 W0702 15:52:45.165419 14585 init.cc:224]     @     0x7f8b79fa6ca4 _ZNSt17_Function_handlerIFvvESt17reference_wrapperISt12_Bind_simpleIFS1_ISt5_BindIFZN6paddle9framework7details28FastThreadedSSAGraphExecuto    r10RunOpAsyncEPSt13unordered_mapIPNS6_12OpHandleBaseESt6atomicIiESt4hashISA_ESt8equal_toISA_ESaISt4pairIKSA_SC_EEESA_RKSt10shared_ptrINS5_13BlockingQueueImEEEEUlvE_vEEEvEEEE9_M_invokeERKSt9_Any_data
 63 W0702 15:52:45.170866 14585 init.cc:224]     @     0x7f8b76f1d353 std::_Function_handler<>::_M_invoke()
 64 W0702 15:52:45.176384 14585 init.cc:224]     @     0x7f8b76d18af7 std::__future_base::_State_base::_M_do_set()
 65 W0702 15:52:45.179415 14585 init.cc:224]     @     0x7f8bdceb1b23 __pthread_once_internal
 66 W0702 15:52:45.181140 14585 init.cc:224]     @     0x7f8b79fa2e72 _ZNSt13__future_base11_Task_stateISt5_BindIFZN6paddle9framework7details28FastThreadedSSAGraphExecutor10RunOpAsyncEPSt13unordered_mapIPNS4_1    2OpHandleBaseESt6atomicIiESt4hashIS8_ESt8equal_toIS8_ESaISt4pairIKS8_SA_EEES8_RKSt10shared_ptrINS3_13BlockingQueueImEEEEUlvE_vEESaIiEFvvEE6_M_runEv
 67 W0702 15:52:45.187652 14585 init.cc:224]     @     0x7f8b76d1af54 _ZZN10ThreadPoolC1EmENKUlvE_clEv
 68 W0702 15:52:45.189965 14585 init.cc:224]     @     0x7f8bd032b678 execute_native_thread_routine_compat
 69 W0702 15:52:45.192129 14585 init.cc:224]     @     0x7f8bdceac851 start_thread
 70 W0702 15:52:45.194875 14585 init.cc:224]     @     0x7f8bdcbfa67d clone
 71 W0702 15:52:45.197022 14585 init.cc:224]     @                0x0 (unknown)

**Comment by LDOUBLEV** [comment]
> 采用fluid.layer.ctc_greedy_decoder的tensor输入模式

输入为tensor的时候，可以把输入的长度信息给input_length参数，
参考文档中：
https://www.paddlepaddle.org.cn/documentation/docs/en/1.8/api/layers/ctc_greedy_decoder.html

![image](https://user-images.githubusercontent.com/26592129/124446867-677c0e80-ddb3-11eb-8d2f-7b15f718ff87.png)

**Comment by zchengquan** [comment]
点赞，尝试了下能work了，tensor模式下的length信息是必须配套使用的！
