### ISSUE TITLE
如何实现pytorch 中的fold

### ISSUE THREAD

**Issue by shengkelong** [PaddlePaddle/Paddle#33947]
在复现模型的时候遇到torch.nn.functional.fold函数不知道在paddle中如何实现

**Comment by JZ-LIANG** [comment]
paddle 目前只有 unfold op 没有对应 的flod op, 可以在issue 上提需求
https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/nn/Unfold_cn.html#unfold
