### ISSUE TITLE
paddle serving 构造输入如果有lod变量，应该如何构造。

### ISSUE THREAD

**Issue by lonelydancer** [PaddlePaddle/Paddle#33940]
背景是plato model，如下：
https://github.com/PaddlePaddle/Serving/issues/1202

其中有几个输入是lod tensor，比如tgt_pos、init_score。
我想咨询的是，构造这个输入的时候，直接用np.array还是要构造一个tgt_pos.lod的东西。跟以下例子类似。
https://hub.fastgit.org/PaddlePaddle/Serving/blob/05373909e109a38f37b3654e8872b2791c80b0be/python/examples/lac/lac_client.py

**Comment by bjjwwang** [comment]
> https://hub.fastgit.org/PaddlePaddle/Serving/blob/05373909e109a38f37b3654e8872b2791c80b0be/python/examples/lac/lac_client.py

可以在训练那一测看一下有没有lod，如果有的话 是需要组件 lod的， 列表就可以

**Comment by lonelydancer** [comment]
训练测是有lod的

**Comment by bjjwwang** [comment]
> 训练测是有lod的

可以直接搬过来

**Comment by lonelydancer** [comment]
https://hub.fastgit.org/PaddlePaddle/Serving/blob/05373909e109a38f37b3654e8872b2791c80b0be/python/examples/lac/lac_client.py
这个我是看不到训练代码的，我只能从下载的model生成的client的config看出来inference的输入是有lod的。

而我在处理的问题，plato的代码，只是在训练的时候定义了几个feed是LOD类型的。目前我在serving的输入的feed_dict补充了几个.lod的变量，不知道这个方向对不对。

目前报这个错误。
![image](https://user-images.githubusercontent.com/548443/124371136-737fa780-dcb1-11eb-8d22-9e067218156c.png)
检查了一下是
int_lod_slot_batch和float_lod_slot_batch的问题，
![image](https://user-images.githubusercontent.com/548443/124372766-6f5a8680-dcbf-11eb-990b-3c574935d382.png)

我把里面的元素转成一维数组，会出core

**Comment by lonelydancer** [comment]
![image](https://user-images.githubusercontent.com/548443/124374894-6bcffb00-dcd1-11eb-8085-d273157be9e6.png)
训练端的lod 是level-2的，我看文档中说serving只支持lod是level-1的。是不是意味着这个问题暂时无解了。
或者说plato实现就不能用level-2的LOD了。
