### ISSUE TITLE
fluid的基础命令run运行出错

### ISSUE THREAD

**Issue by paniclp** [PaddlePaddle/Paddle#33952]
import paddle.fluid as fluid
import numpy as np
# 定义两个张量的常量x1和x2
# 定义两个张量
x1 = fluid.layers.fill_constant(shape=[1], value=1, dtype='int64')
x2 = fluid.layers.fill_constant(shape=[1], value=1, dtype='int64')

# 接着定义一个操作，该计算是将上面两个张量进行加法计算，并返回一个求和的算子。PaddlePaddle提供了大量的操作，比如加减乘除、三角函数等，读者可以在fluid.layers找到。
# 将两个张量求和
y1 = x1+x2

# 然后创建一个解释器，可以在这里指定计算使用CPU或GPU。
# 当使用CPUPlace()时使用的是CPU，
# 如果是CUDAPlace()使用的是GPU。
# 解析器是之后使用它来进行计算过的，
# 比如在执行计算之前我们要先执行参数初始化的program也是要使用到解析器的，
# 因为只有解析器才能执行program。

# # 创建一个使用CPU的解释器
place = fluid.CPUPlace()
exe = fluid.Executor(place)
# # 进行参数初始化
exe.run(fluid.default_startup_program(),fetch_list=[y1])

运行最后的run出错
提示：
D:\tools\Anaconda3\lib\site-packages\win32\lib\pywintypes.py:2: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp, sys, os
D:\tools\Anaconda3\lib\site-packages\paddle\fluid\executor.py:1150: UserWarning: There are no operators in the program to be executed. If you pass Program manually, please use fluid.program_guard to ensure the current Program is being used.
  warnings.warn(error_info)
Traceback (most recent call last):
  File "G:/Python/Projects/GetInfo/Machine Learning/lesson1.py", line 29, in <module>
    exe.run(fluid.default_startup_program(),fetch_list=[y1])
  File "D:\tools\Anaconda3\lib\site-packages\paddle\fluid\executor.py", line 1110, in run
    six.reraise(*sys.exc_info())
  File "D:\tools\Anaconda3\lib\site-packages\six.py", line 719, in reraise
    raise value
  File "D:\tools\Anaconda3\lib\site-packages\paddle\fluid\executor.py", line 1108, in run
    return_merged=return_merged)
  File "D:\tools\Anaconda3\lib\site-packages\paddle\fluid\executor.py", line 1239, in _run_impl
    use_program_cache=use_program_cache)
  File "D:\tools\Anaconda3\lib\site-packages\paddle\fluid\executor.py", line 1314, in _run_program
    fetch_var_name=fetch_var_name)
  File "D:\tools\Anaconda3\lib\site-packages\paddle\fluid\executor.py", line 647, in _add_feed_fetch_ops
    attrs={'col': i})
  File "D:\tools\Anaconda3\lib\site-packages\paddle\fluid\framework.py", line 3223, in append_op
    kwargs.get("stop_gradient", False))
  File "D:\tools\Anaconda3\lib\site-packages\paddle\fluid\dygraph\tracer.py", line 45, in trace_op
    not stop_gradient)
RuntimeError: (PermissionDenied) Only support operator with kernel in Dygraph mode.
  [Hint: op_kernel should not be null.] (at C:\home\workspace\Paddle_release\paddle\fluid\imperative\layer.cc:336)
  [operator < fetch > error]

好几天都不知道怎么回事，请高手指导一下
qq：64924930

**Comment by pangyoki** [comment]
你好，请问你用的paddle版本是什么？
看报错，是因为你用的是动态图环境，但是运行的代码是静态图的执行方式。
paddle 2.0以后默认使用动态图，如果你想使用静态图功能，可以使用`paddle.enable_static()`切换到静态图模式。
（by the way，paddle.fluid是paddle 1.x版本使用的方法，paddle 2.0以后不推荐用fluid下的方法了）

**Comment by paniclp** [comment]
你好，我都是按照网上的官方教程操作的，搞了半天也没弄明白，能不能加你个qq，后面跟你请教一下
QQ64924930


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/Paddle"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年7月4日(星期天) 晚上10:57
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PaddlePaddle/Paddle] fluid的基础命令run运行出错 (#33952)





 
你好，请问你用的paddle版本是什么？
 看报错，是因为你用的是动态图环境，但是运行的代码是静态图的执行方式。
 paddle 2.0以后默认使用动态图，如果你想使用静态图功能，可以使用paddle.enable_static()切换到静态图模式。
 （by the way，paddle.fluid是paddle 1.x版本使用的方法，paddle 2.0以后不推荐用fluid下的方法了）
