### ISSUE TITLE
如何打印inference网络结构?

### ISSUE THREAD

**Issue by eadst** [PaddlePaddle/Paddle#33965]
请问如何打印inference的网络结构?

**Comment by b3602sss** [comment]
> 请问如何打印inference的网络结构?

inference没有提供这种接口，请使用训练相关的接口。可视化的话可以使用visualdl 或则netron

**Comment by eadst** [comment]
> > 请问如何打印inference的网络结构?
> 
> inference没有提供这种接口，请使用训练相关的接口。可视化的话可以使用visualdl 或则netron

谢谢！
