### ISSUE TITLE
paddle2.0+ 如何修改参数值，例如 torch中是通过 param.data 改变

### ISSUE THREAD

**Issue by loujie0822** [PaddlePaddle/Paddle#33971]
paddle2.0+ 如何修改参数值，例如 torch中是通过 param.data 改变

**Comment by zhwesky2010** [comment]
@loujie0822 如果想inplace改变该Tensor的值，可以通过切片进行，例如  ```x=paddle.to_tensor(1.)``` 、```x[:]=2.``` 可以改变Tensor的值

**Comment by loujie0822** [comment]
不是，现在是想尝试对抗训练，参数类型是ParamBase，如何改变这个ParamBase的值呢？但它的梯度grad仍然不变。

**Comment by loujie0822** [comment]
@zhouwei25 还有，ParamBase值和梯度能不能改变呢？怎么改变？

**Comment by zhwesky2010** [comment]
> @zhouwei25 还有，ParamBase值和梯度能不能改变呢？怎么改变？

ParamBase就是Tensor，可训练的Tensor，继承了Tensor所有方法。你可以试试 可能有报错

**Comment by loujie0822** [comment]
> > @zhouwei25 还有，ParamBase值和梯度能不能改变呢？怎么改变？
> 
> ParamBase就是Tensor，可训练的Tensor，继承了Tensor所有方法。但是可训练的Tensor是不能中途改变的，你可以试试 框架应该会报错

那这就涉及到一个很现实的问题，在做对抗训练时需要改变参数的值或者grad。可训练的参数无法进行inplace操作，唯一的办法就是到ernie内部去改变，而ernie内部已经封装好了，改动十分麻烦。

对抗训练需要能够改变参数值或grad，这种功能在torch中很常见，就是用param.data进行。
希望paddle能够实现该功能，类似的issue已经提了很多了：

- https://github.com/PaddlePaddle/Paddle/issues/32500
- https://github.com/PaddlePaddle/Paddle/issues/32317
- https://github.com/PaddlePaddle/Paddle/issues/27032

**Comment by zhwesky2010** [comment]
请问目前的报错信息截图看一下

**Comment by zhwesky2010** [comment]
麻烦看下这里的inplace是符合预期吗，能改吗 @pangyoki

**Comment by luckysheep861** [comment]
请问这个问题解决了吗？我也需要实现paddle版本的FGM

**Comment by wawltor** [comment]
https://github.com/PaddlePaddle/PaddleNLP/blob/147a943383efe23593c20d1d104a6c3591bd628b/paddlenlp/transformers/bert/modeling.py#L310 通过set_value方式来进行parameter的赋值，具体使用方式可以见链接
