### ISSUE TITLE
安装paddle出现问题

### ISSUE THREAD

**Issue by 827346462** [PaddlePaddle/Paddle#33975]
ubuntu18.04安装paddle=2.1.0 cpu版本

![QQ图片20210705230745](https://user-images.githubusercontent.com/50097546/124491614-0de10780-dde6-11eb-9c20-1b03dfb17d12.png)
出现

**Comment by 827346462** [comment]
按照解决方法操作没效果

**Comment by pangyoki** [comment]
你好，麻烦确认下重装noavx paddle时，下载链接里显示的是noavx的包。避免安装的仍然是avx的包。

可以尝试添加`--no-index`试试，例如`python -m pip install --force-reinstall paddlepaddle==2.1.1 -f https://www.paddlepaddle.org.cn/whl/mkl/stable/noavx.html --no-index`

**Comment by pangyoki** [comment]
如果安装paddle时遇到依赖包报错的问题，可以自己手动安装依赖包，安装命令中加上`--no-deps`。
例如 `python -m pip install --force-reinstall paddlepaddle==2.1.1 -f https://www.paddlepaddle.org.cn/whl/mkl/stable/noavx.html --no-index --no-deps`
