### ISSUE TITLE
如何对静态图Tensor进行切片

### ISSUE THREAD

**Issue by wofeichangaiwoai** [PaddlePaddle/Paddle#33972]
想要对logits进行切片操作，但是说logits是lod_Tensor，于是把lod_Tensor转成Tensor，报错
AttributeError: 'Variable' object has no attribute 'lod()'，怎么解决？或者说怎么对logits进行切片操作获取奇数列和偶数列？

代码如下：

        def LodTensor_to_Tensor(logits):
            # 获取 LoD-Tensor 的 lod 信息
            lod = logits.lod()
            # 转换成 array
            array = np.array(logits)
            new_array = []
            # 依照原LoD-Tensor的层级信息，转换成Tensor
            for i in range(len(lod[0]) - 1):
                new_array.append(array[lod[0][i]:lod[0][i + 1]])
            return new_array

        def to_lodtensor(data, place):
            # 存储Tensor的长度作为LoD信息
            seq_lens = [len(seq) for seq in data]
            cur_len = 0
            lod = [cur_len]
            for l in seq_lens:
                cur_len += l
                lod.append(cur_len)
            # 对待转换的 Tensor 降维
            flattened_data = np.concatenate(data, axis=0).astype("int64")
            flattened_data = flattened_data.reshape([len(flattened_data), 1])
            # 为 Tensor 数据添加lod信息
            res = fluid.LoDTensor()
            res.set(flattened_data, place)
            res.set_lod([lod])
            return res
        
        def computer_loss(logits, label):
            alpha = 4
            logging.debug("logits:{}".format(logits))
            ce_loss1 = fluid.layers.sigmoid_cross_entropy_with_logits(x=logits, label=label)
            logits_ten = LodTensor_to_Tensor(logits)
            logging.debug("logits_ten:{}".format(logits_ten))
            logits_odd_ten = logits_ten[1::2]
            logits_even_ten = logits_ten[::2]
            logits_odd_lod = to_lodtensor(logits_odd_ten, fluid.CPUPlace())
            logits_even_lod = to_lodtensor(logits_even_ten, fluid.CPUPlace())
            loss2 = fluid.layers.kldiv_loss(x=logits_even_lod, target=logits_odd_lod, reduction='none') + fluid.layers.kldiv_loss(x=logits_odd_lod, target=logits_even_lod, reduction='none')  
            return ce_loss1 + loss2 / 4 * alpha

        ce_loss = computer_loss(logits, label)

**Comment by zhwesky2010** [comment]
@wofeichangaiwoai 请问logits直接进行切片  使用下标[1,:] [3,:] 会出错吗？需要用Variable.lod_level来看lod信息
