### ISSUE TITLE
ubuntu18.0.4 安装错误

### ISSUE THREAD

**Issue by 827346462** [PaddlePaddle/Paddle#33979]
1）PaddlePaddle版本：2.1.0 cpu版本
    2）CPU：
 
    4）系统环境：ubuntu 18.04  64位
- 安装方式信息：
anconda 安装      
![QQ图片20210706101717](https://user-images.githubusercontent.com/50097546/124532548-5c70bf00-de43-11eb-8bbc-359d7feb812f.png)
 通过下图命令再次安装
![QQ图片20210706101803](https://user-images.githubusercontent.com/50097546/124532622-80340500-de43-11eb-96eb-adb983cb848b.png)
问题还是没有解决

**Comment by TeslaZhao** [comment]
您好，先卸载paddlepaddle

再下载whl包安装
https://www.paddlepaddle.org.cn/documentation/docs/en/install/Tables_en.html#multi-version-whl-package-list-release

![image](https://user-images.githubusercontent.com/6309021/124564573-c7d28500-de73-11eb-8006-ecdee9cbb8fa.png)
