### ISSUE TITLE
chinese_ocr_db_crnn_server需要连网吗？

### ISSUE THREAD

**Issue by gaogaoxingxing2010** [PaddlePaddle/Paddle#33974]
chinese_ocr_db_crnn_server运行报错如附件图片，目前我是离线状态下，不可上网，是否可用呢？一定需要联网吗？
![IMG_20210705_200615](https://user-images.githubusercontent.com/62227361/124490822-269ced80-dde5-11eb-8464-db8d55a756ef.jpg)

**Comment by wanghuancoder** [comment]
您好！OCR的问题可以直接到PaddleOCR repo 的issue中提问。
https://github.com/PaddlePaddle/PaddleOCR/issues

**Comment by littletomatodonkey** [comment]
你好使用hub调用的话，是需要联网下载模型的
