### ISSUE TITLE
win10下cmake编译出错

### ISSUE THREAD

**Issue by wxf764571829** [PaddlePaddle/Paddle#33995]
F:\code\Paddle\build>cmake .. -G "Visual Studio 14 2015 Win64" -A x64 -DWITH_TESTING=OFF -DON_INFER=ON -DCMAKE_BUILD_TYPE=Release -DPY_VERSION=3
-- Found Paddle host system: win32, version:
-- Found Paddle host system's CPU: 8 cores
-- Selecting Windows SDK version  to target Windows 10.0.19042.
CMake Error at CMakeLists.txt:23 (project):
  Generator

    Visual Studio 14 2015 Win64
  does not support platform specification, but platform
    x64
  was specified.

-- Configuring incomplete, errors occurred!
See also "F:/code/Paddle/build/CMakeFiles/CMakeOutput.log".

![image](https://user-images.githubusercontent.com/46362180/124687690-f601a480-df07-11eb-84f0-c2144c622ec5.png)

**Comment by tink2123** [comment]
请问有更多的报错信息吗？

**Comment by tink2123** [comment]
可以参考这篇编译文档的步骤再试一下：https://paddle-inference.readthedocs.io/en/latest/user_guides/source_compile.html#windows-10

**Comment by wxf764571829** [comment]
> 请问有更多的报错信息吗？

没有更多报错信息了 这就是全部信息，我参照的就是这篇文档步骤编译的

**Comment by wxf764571829** [comment]
> 可以参考这篇编译文档的步骤再试一下：https://paddle-inference.readthedocs.io/en/latest/user_guides/source_compile.html#windows-10
![image](https://user-images.githubusercontent.com/46362180/124703493-01af9400-df25-11eb-8f47-3c2839e07991.png)

**Comment by zhwesky2010** [comment]
@wxf764571829 你好，上面这篇预测的编译文档有错，请参看Paddle官网文档编译，https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/install/compile/windows-compile.html#windows ``cmake .. -G "Visual Studio 14 2015 Win64" -DWITH_GPU=ON -DWITH_TESTING=OFF -DCMAKE_BUILD_TYPE=Release``  你这边需要删除 -A x64

**Comment by wxf764571829** [comment]
> @wxf764571829 你好，上面这篇预测的编译文档有错，请参看Paddle官网文档编译，https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/install/compile/windows-compile.html#windows `cmake .. -G "Visual Studio 14 2015 Win64" -DWITH_GPU=ON -DWITH_TESTING=OFF -DCMAKE_BUILD_TYPE=Release` 你这边需要删除 -A x64

非常感谢
