### ISSUE TITLE
找不到“paddle_inference.dll”

### ISSUE THREAD

**Issue by shingstone-lu** [PaddlePaddle/Paddle#34002]
系统配置：
win10+VS2015
paddle2.1.0

从https://paddleinference.paddlepaddle.org.cn/user_guides/download_lib.html#windows
下载了cuda10.2_cudnn7_avx_mkl_trt7对应的paddle_inference.zip
并将其解压拷贝到C:\Program Files\
参考https://aistudio.baidu.com/aistudio/education/group/info/19084
我新建了一个C++ Windows控制台应用程序。
其中，VC++目录的包含目录增加了：C:\Program Files\paddle_inference\paddle\include
          VC++目录的库目录增加了：C:\Program Files\paddle_inference\paddle\lib
链接器的输入的附加依赖项增加了：paddle_inference.lib;libpaddle_inference.lib

源代码如下：
// ConsoleApplication1.cpp : 此文件包含 "main" 函数。程序执行将在此处开始并结束。
//

#include <iostream>
#include "paddle_inference_api.h"
#include <vector>

bool InitPredictor(const char* model_dir, const char* model_file,
	const char* params_file, bool use_gpu, bool use_trt)
{
	std::shared_ptr<paddle_infer::Predictor> predictor;

	paddle_infer::Config config;
	if (strlen(model_dir) == 0)
	{
		//Load combined model.
		config.SetModel(model_file, params_file);
	}
	else
	{
		//Load uncombined model.
		config.SetModel(model_dir);
	}
	if (use_gpu)
	{
		config.EnableUseGpu(500, 0);
		if (use_trt)
		{
			int batch_size = 1;
			int min_subgraph_size = 3;
			auto precision = paddle_infer::Config::Precision::kFloat32;
			config.EnableTensorRtEngine(1 << 30, batch_size, min_subgraph_size, precision, false, false);
		}
	}
	else
	{
		config.EnableMKLDNN();
		config.SetCpuMathLibraryNumThreads(4);
	}
	predictor = std::move(paddle_infer::CreatePredictor(config));
	return true;
}

int main()
{
    std::cout << "Hello World!\n";
}

程序能够正常生成，但是运行的时候报找不到“paddle_inference.dll”的错误。

**Comment by zhangjun** [comment]
> 系统配置：
> win10+VS2015
> paddle2.1.0
> 
> 从https://paddleinference.paddlepaddle.org.cn/user_guides/download_lib.html#windows
> 下载了cuda10.2_cudnn7_avx_mkl_trt7对应的paddle_inference.zip
> 并将其解压拷贝到C:\Program Files
> 参考https://aistudio.baidu.com/aistudio/education/group/info/19084
> 我新建了一个C++ Windows控制台应用程序。
> 其中，VC++目录的包含目录增加了：C:\Program Files\paddle_inference\paddle\include
> VC++目录的库目录增加了：C:\Program Files\paddle_inference\paddle\lib
> 链接器的输入的附加依赖项增加了：paddle_inference.lib;libpaddle_inference.lib
> 
> 源代码如下：
> // ConsoleApplication1.cpp : 此文件包含 "main" 函数。程序执行将在此处开始并结束。
> //
> 
> #include
> #include "paddle_inference_api.h"
> #include
> 
> bool InitPredictor(const char* model_dir, const char* model_file,
> const char* params_file, bool use_gpu, bool use_trt)
> {
> std::shared_ptr<paddle_infer::Predictor> predictor;
> 
> ```
> paddle_infer::Config config;
> if (strlen(model_dir) == 0)
> {
> 	//Load combined model.
> 	config.SetModel(model_file, params_file);
> }
> else
> {
> 	//Load uncombined model.
> 	config.SetModel(model_dir);
> }
> if (use_gpu)
> {
> 	config.EnableUseGpu(500, 0);
> 	if (use_trt)
> 	{
> 		int batch_size = 1;
> 		int min_subgraph_size = 3;
> 		auto precision = paddle_infer::Config::Precision::kFloat32;
> 		config.EnableTensorRtEngine(1 << 30, batch_size, min_subgraph_size, precision, false, false);
> 	}
> }
> else
> {
> 	config.EnableMKLDNN();
> 	config.SetCpuMathLibraryNumThreads(4);
> }
> predictor = std::move(paddle_infer::CreatePredictor(config));
> return true;
> ```
> 
> }
> 
> int main()
> {
> std::cout << "Hello World!\n";
> }
> 
> 程序能够正常生成，但是运行的时候报找不到“paddle_inference.dll”的错误。

您好，可以尝试把paddle_inference.dll放置在可执行程序exe目录。

**Comment by shingstone-lu** [comment]
> > 系统配置：
> > win10+VS2015
> > paddle2.1.0
> > 从https://paddleinference.paddlepaddle.org.cn/user_guides/download_lib.html#windows
> > 下载了cuda10.2_cudnn7_avx_mkl_trt7对应的paddle_inference.zip
> > 并将其解压拷贝到C:\Program Files
> > 参考https://aistudio.baidu.com/aistudio/education/group/info/19084
> > 我新建了一个C++ Windows控制台应用程序。
> > 其中，VC++目录的包含目录增加了：C:\Program Files\paddle_inference\paddle\include
> > VC++目录的库目录增加了：C:\Program Files\paddle_inference\paddle\lib
> > 链接器的输入的附加依赖项增加了：paddle_inference.lib;libpaddle_inference.lib
> > 源代码如下：
> > // ConsoleApplication1.cpp : 此文件包含 "main" 函数。程序执行将在此处开始并结束。
> > //
> > #include
> > #include "paddle_inference_api.h"
> > #include
> > bool InitPredictor(const char* model_dir, const char* model_file,
> > const char* params_file, bool use_gpu, bool use_trt)
> > {
> > std::shared_ptr<paddle_infer::Predictor> predictor;
> > ```
> > paddle_infer::Config config;
> > if (strlen(model_dir) == 0)
> > {
> > 	//Load combined model.
> > 	config.SetModel(model_file, params_file);
> > }
> > else
> > {
> > 	//Load uncombined model.
> > 	config.SetModel(model_dir);
> > }
> > if (use_gpu)
> > {
> > 	config.EnableUseGpu(500, 0);
> > 	if (use_trt)
> > 	{
> > 		int batch_size = 1;
> > 		int min_subgraph_size = 3;
> > 		auto precision = paddle_infer::Config::Precision::kFloat32;
> > 		config.EnableTensorRtEngine(1 << 30, batch_size, min_subgraph_size, precision, false, false);
> > 	}
> > }
> > else
> > {
> > 	config.EnableMKLDNN();
> > 	config.SetCpuMathLibraryNumThreads(4);
> > }
> > predictor = std::move(paddle_infer::CreatePredictor(config));
> > return true;
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > }
> > int main()
> > {
> > std::cout << "Hello World!\n";
> > }
> > 程序能够正常生成，但是运行的时候报找不到“paddle_inference.dll”的错误。
> 
> 您好，可以尝试把paddle_inference.dll放置在可执行程序exe目录。

我把mkldnn.dll和paddle_inference.dll拷贝到exe目录后，这个错误没有了。
之前的配置按说我将所需要的的目录都配置好了但就是找不到dll，不知道什么原因。

**Comment by zhangjun** [comment]
> > > 系统配置：
> > > win10+VS2015
> > > paddle2.1.0
> > > 从https://paddleinference.paddlepaddle.org.cn/user_guides/download_lib.html#windows
> > > 下载了cuda10.2_cudnn7_avx_mkl_trt7对应的paddle_inference.zip
> > > 并将其解压拷贝到C:\Program Files
> > > 参考https://aistudio.baidu.com/aistudio/education/group/info/19084
> > > 我新建了一个C++ Windows控制台应用程序。
> > > 其中，VC++目录的包含目录增加了：C:\Program Files\paddle_inference\paddle\include
> > > VC++目录的库目录增加了：C:\Program Files\paddle_inference\paddle\lib
> > > 链接器的输入的附加依赖项增加了：paddle_inference.lib;libpaddle_inference.lib
> > > 源代码如下：
> > > // ConsoleApplication1.cpp : 此文件包含 "main" 函数。程序执行将在此处开始并结束。
> > > //
> > > #include
> > > #include "paddle_inference_api.h"
> > > #include
> > > bool InitPredictor(const char* model_dir, const char* model_file,
> > > const char* params_file, bool use_gpu, bool use_trt)
> > > {
> > > std::shared_ptr<paddle_infer::Predictor> predictor;
> > > ```
> > > paddle_infer::Config config;
> > > if (strlen(model_dir) == 0)
> > > {
> > > 	//Load combined model.
> > > 	config.SetModel(model_file, params_file);
> > > }
> > > else
> > > {
> > > 	//Load uncombined model.
> > > 	config.SetModel(model_dir);
> > > }
> > > if (use_gpu)
> > > {
> > > 	config.EnableUseGpu(500, 0);
> > > 	if (use_trt)
> > > 	{
> > > 		int batch_size = 1;
> > > 		int min_subgraph_size = 3;
> > > 		auto precision = paddle_infer::Config::Precision::kFloat32;
> > > 		config.EnableTensorRtEngine(1 << 30, batch_size, min_subgraph_size, precision, false, false);
> > > 	}
> > > }
> > > else
> > > {
> > > 	config.EnableMKLDNN();
> > > 	config.SetCpuMathLibraryNumThreads(4);
> > > }
> > > predictor = std::move(paddle_infer::CreatePredictor(config));
> > > return true;
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > }
> > > int main()
> > > {
> > > std::cout << "Hello World!\n";
> > > }
> > > 程序能够正常生成，但是运行的时候报找不到“paddle_inference.dll”的错误。
> > 
> > 
> > 您好，可以尝试把paddle_inference.dll放置在可执行程序exe目录。
> 
> 我把mkldnn.dll和paddle_inference.dll拷贝到exe目录后，这个错误没有了。
> 之前的配置按说我将所需要的的目录都配置好了但就是找不到dll，不知道什么原因。

windows程序一般会在system目录或者可执行程序目录中查找，否则就会找不到。

**Comment by shingstone-lu** [comment]
> > > > 系统配置：
> > > > win10+VS2015
> > > > paddle2.1.0
> > > > 从https://paddleinference.paddlepaddle.org.cn/user_guides/download_lib.html#windows
> > > > 下载了cuda10.2_cudnn7_avx_mkl_trt7对应的paddle_inference.zip
> > > > 并将其解压拷贝到C:\Program Files
> > > > 参考https://aistudio.baidu.com/aistudio/education/group/info/19084
> > > > 我新建了一个C++ Windows控制台应用程序。
> > > > 其中，VC++目录的包含目录增加了：C:\Program Files\paddle_inference\paddle\include
> > > > VC++目录的库目录增加了：C:\Program Files\paddle_inference\paddle\lib
> > > > 链接器的输入的附加依赖项增加了：paddle_inference.lib;libpaddle_inference.lib
> > > > 源代码如下：
> > > > // ConsoleApplication1.cpp : 此文件包含 "main" 函数。程序执行将在此处开始并结束。
> > > > //
> > > > #include
> > > > #include "paddle_inference_api.h"
> > > > #include
> > > > bool InitPredictor(const char* model_dir, const char* model_file,
> > > > const char* params_file, bool use_gpu, bool use_trt)
> > > > {
> > > > std::shared_ptr<paddle_infer::Predictor> predictor;
> > > > ```
> > > > paddle_infer::Config config;
> > > > if (strlen(model_dir) == 0)
> > > > {
> > > > 	//Load combined model.
> > > > 	config.SetModel(model_file, params_file);
> > > > }
> > > > else
> > > > {
> > > > 	//Load uncombined model.
> > > > 	config.SetModel(model_dir);
> > > > }
> > > > if (use_gpu)
> > > > {
> > > > 	config.EnableUseGpu(500, 0);
> > > > 	if (use_trt)
> > > > 	{
> > > > 		int batch_size = 1;
> > > > 		int min_subgraph_size = 3;
> > > > 		auto precision = paddle_infer::Config::Precision::kFloat32;
> > > > 		config.EnableTensorRtEngine(1 << 30, batch_size, min_subgraph_size, precision, false, false);
> > > > 	}
> > > > }
> > > > else
> > > > {
> > > > 	config.EnableMKLDNN();
> > > > 	config.SetCpuMathLibraryNumThreads(4);
> > > > }
> > > > predictor = std::move(paddle_infer::CreatePredictor(config));
> > > > return true;
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > }
> > > > int main()
> > > > {
> > > > std::cout << "Hello World!\n";
> > > > }
> > > > 程序能够正常生成，但是运行的时候报找不到“paddle_inference.dll”的错误。
> > > 
> > > 
> > > 您好，可以尝试把paddle_inference.dll放置在可执行程序exe目录。
> > 
> > 
> > 我把mkldnn.dll和paddle_inference.dll拷贝到exe目录后，这个错误没有了。
> > 之前的配置按说我将所需要的的目录都配置好了但就是找不到dll，不知道什么原因。
> 
> windows程序一般会在system目录或者可执行程序目录中查找，否则就会找不到。

非常感谢。
