### ISSUE TITLE
paddle里如何修改Variable(Tensor)某行或几行的赋值

### ISSUE THREAD

**Issue by markmaomao** [PaddlePaddle/Paddle#34010]
我现在想对tensor部分的值修改，就是修改某些行的值
目前有已训练好的模型，在预测中enc_out_pos = ernie_pos.get_sequence_output()得到一个Tensor(Variable类型)，就是一个（-1，128，768）的tensor。
如果用fluid.global_scope().var("print_dropout_19.tmp_0_0.tmp_0").get_tensor().set(xxx, fluid.CPUPlace())的话如何修改这个tensor的第三维度的值而不是全部赋值？我想修改这个tensor的768维的1到64维的值为0
我写了一个 a = fluid.layers.zeros([-1, 128, 64], 'float32')这样一个矩阵，但是怎么部分替换enc_out_pos的768维度里从1-64维的值呢？
name: "print_dropout_19.tmp_0_0.tmp_0"
type {
    type: LOD_TENSOR
    lod_tensor {
       tensor {
          data_type: FP32
          dims: -1
          dims: 128
          dims: 768
        }
        lod_level: 0
    }
}
type是<class 'paddle.fluid.framework.Variable'>
尝试了矩阵相乘和切片等方法修改某一行的值
均报错 "TypeError: 'Variable' object does not support item assignment"
谢谢

**Comment by tink2123** [comment]
当前变量是variable类型，不能直接取index来赋值
可以先把需要修改值的维度通过paddle.fluid.layers.slice切片出来，进行赋值之后再concat回去

**Comment by markmaomao** [comment]
> 当前变量是variable类型，不能直接取index来赋值
> 可以先把需要修改值的维度通过paddle.fluid.layers.slice切片出来，进行赋值之后再concat回去
我现在做了个split, 平均分成了12份，然后写了一个数值均为0的numpy数组a, 将x0用a数组重新赋值，但是打印出来x0前后的值是一样的，赋值后的数组并不是一个均为0的数组，就是d_和e_是一模一样的，请问是什么原因？以下是代码：

x0, x1, x2, x3, x4, x5, x6, x7, x8, x9, x10, x11 = fluid.layers.split(enc_out_pos, num_or_sections=12, dim=2)
d_ = fluid.layers.Print(x0)
print(d_)
print(type(d_))
paddle.fluid.layers.Print(d_,summarize=-1, message="The content of some_layer: ")
a = np.zeros([128, 64], 'float32')
fluid.global_scope().var(x0.name).get_tensor().set(a, fluid.CPUPlace())
e_ = fluid.layers.Print(x0)
print(e_)
print(type(e_))
paddle.fluid.layers.Print(e_,summarize=-1, message="The content of some_layer: ")

**Comment by markmaomao** [comment]
> 当前变量是variable类型，不能直接取index来赋值
> 可以先把需要修改值的维度通过paddle.fluid.layers.slice切片出来，进行赋值之后再concat回去


我现在做了个split, 平均分成了12份，然后写了一个数值均为0的numpy数组a, 将x0用a数组重新赋值，但是打印出来x0前后的值是1之前的，并不是一个均为0的数组，就是赋值前后d_和e_是一模一样的，但是打印print(fluid.global_scope().var("print_split_0.tmp_0_0.tmp_0").get_tensor()) 却显示是0矩阵，请问是什么原因？后面再concat的时候x0是还是赋值以前的，并没有变化。
如果concat的时候如果我建立一个b = fluid.global_scope().var("print_split_0.tmp_0_0.tmp_0").get_tensor()
然后用b去concat的其他的x，会报错TypeError: The type of 'input[0]' in concat must be (<class 'paddle.fluid.framework.Variable'>, <class 'paddle.fluid.core_avx.VarBase'>), but received <class 'paddle.fluid.core_avx.LoDTensor'>，所以如何将LoDtensor转为Variable, 达到concat的目的？
 以下是代码：
x0, x1, x2, x3, x4, x5, x6, x7, x8, x9, x10, x11 = fluid.layers.split(enc_out_pos, num_or_sections=12, dim=2)
d_ = fluid.layers.Print(x0)
print(d_)
print(type(d_))
paddle.fluid.layers.Print(d_,summarize=-1, message="The content of some_layer: ")
a = np.zeros([128, 64], 'float32')
fluid.global_scope().var("print_split_0.tmp_0_0.tmp_0").get_tensor().set(a, fluid.CPUPlace())
e_ = fluid.layers.Print(x0)
print(e_)
print(type(e_))
paddle.fluid.layers.Print(e_,summarize=-1, message="The content of some_layer: ")
print(fluid.global_scope().var("print_split_0.tmp_0_0.tmp_0").get_tensor())
b = fluid.global_scope().var("print_split_0.tmp_0_0.tmp_0").get_tensor()
out1 = fluid.layers.concat(input=[b,x1,x2,x3,x4,x5,x6,x7,x8,x9,x10,x11], axis=-1)
enc_out_pos = out1

**Comment by tink2123** [comment]
这样去修改x0的值就可以了：

```
    import paddle.fluid as fluid
    import paddle
    import numpy as np
    paddle.enable_static()
    enc_out_pos = fluid.layers.range(start=0,end=24,step=1,dtype="int64")
    enc_out_pos = fluid.layers.reshape(enc_out_pos, (4,6))
    x0, x1, x2, x3 = fluid.layers.split(enc_out_pos, num_or_sections=4, dim=0)
    fluid.layers.Print(x0)
    a = np.zeros([1,6], 'int64')
    x0 = x0 * 0
    out1 = fluid.layers.concat(input=[x0,x1,x2,x3], axis=0)
    main_program = paddle.static.default_main_program()
    exe = paddle.static.Executor(place=paddle.CPUPlace())
    res = exe.run(main_program, fetch_list=[out1])
    print(res)
```
