### ISSUE TITLE
paddle 训练的模型，怎么保存成非combined？

### ISSUE THREAD

**Issue by guoxixiao** [PaddlePaddle/Paddle#34031]
paddlex1.1.7，cpu训练的目标检测模型，想要在rknpu上跑。好像是需要使用非combined才能转成rknpu。
paddlex好像只能生成combined形式，请问怎么生成非combined？
谢谢

**Comment by haozech** [comment]
https://www.paddlepaddle.org.cn/documentation/docs/zh/1.7/api_cn/io_cn/save_inference_model_cn.html
将params_filename参数设为None，可以生成单独的参数文件
