### ISSUE TITLE
Mac M1芯片 本地训练不适配

### ISSUE THREAD

**Issue by btobab** [PaddlePaddle/Paddle#34037]
环境：本地IDE
配置：Mac OS 11.4 M1
运行报错，但在AI Studio上可以运行
![image](https://user-images.githubusercontent.com/66876429/124946481-a32c0800-e041-11eb-9da6-11eda27ac9c8.png)

**Comment by haozech** [comment]
你好，从报错上看似乎是paddle版本不一致导致的错误

**Comment by haozech** [comment]
Mac对M1芯片做进行了适配：”Rosetta 2动态二进制转译技术使得搭载M1芯片的设备仍然能够运行原有为x86架构处理器设计的软件”，所以如果你是M1 芯片也可以用paddle 2.1的安装包

**Comment by tianshuo78520a** [comment]
v2.7.16, v3.8.2, and v3.9 开始支持M1的，以前的python版本在获取Mac框架时，会获取到x86架构

**Comment by btobab** [comment]
好的，谢谢大佬们的解答，俺试一下

**Comment by tianshuo78520a** [comment]
有一个网址，可以查看M1支持的软件版本：https://doesitarm.com/

**Comment by btobab** [comment]
好的，谢谢大佬

**Comment by btobab** [comment]
![image](https://user-images.githubusercontent.com/66876429/125302697-c4049e00-e35e-11eb-85ca-9a22941f9120.png)
我不明白版本不一致什么意思，我的IDE显示版本是2.1.1

**Comment by dingjiaweiww** [comment]
可是能用的mac 自带的 python版本的问题，可以去python官网下载一个正式版本的python，如果要下载python3.9，需要下载3.9 intel 版本，不要下载3.9 universal 版本
