### ISSUE TITLE
Mac編譯universal binary沒有包含arm64

### ISSUE THREAD

**Issue by a29813287** [PaddlePaddle/Paddle#34036]
- 版本、环境信息：
    PaddlePaddle版本：2.1
    系统环境：Mac OS 11.2

- 安装方式信息：
    cmake \\
      -DCMAKE_OSX_ARCHITECTURES='x86_64;arm64' \\
      -DWITH_GPU=OFF \\
      -DWITH_MKL=OFF \\
      -DCMAKE_BUILD_TYPE=Release \\
      '..'
    make -j
    make inference_lib_dist

- 问题描述：
    可以編譯成功，但用lipo libpaddle_inference.dylib -archs，只有x86_64，要怎麼修改才好？

**Comment by haozech** [comment]
mac上的源码编译可以参考官网教程 https://www.paddlepaddle.org.cn/install/quick?docurl=/documentation/docs/zh/install/compile/macos-compile.html

**Comment by a29813287** [comment]
看到了，目前不支持arm64

**Comment by pangyoki** [comment]
paddle暂不支持arm64，不过Mac M1芯片可能能用，应该是apple做了兼容

**Comment by dingjiaweiww** [comment]
请问你是Mac M1 芯片吗，M1 是arm64 架构的，Mac 进行了适配：”Rosetta 2动态二进制转译技术使得搭载M1芯片的设备仍然能够运行原有为x86架构处理器设计的软件”，所以如果你是M1 芯片也可以用paddle 2.1的安装包

**Comment by trK54Ylmz** [comment]
Here `.whl` files Apple Silicon (m1) devices,

[paddlepaddle-0.0.0-cp39-cp39-macosx_11_0_arm64.whl](https://github.com/trK54Ylmz/Paddle/releases/download/v2.1.3/paddlepaddle-0.0.0-cp39-cp39-macosx_11_0_arm64.whl)
[paddleocr-2.2.1-py3-none-any.whl](https://github.com/trK54Ylmz/Paddle/releases/download/v2.1.3/paddleocr-2.2.1-py3-none-any.whl)
