### ISSUE TITLE
启动训练时提示Warn Detect dataset only contains single fileds

### ISSUE THREAD

**Issue by 15162162323** [PaddlePaddle/Paddle#34038]
WARNING: Detect dataset only contains single fileds, return format changed since Paddle 2.1. In Paddle <= 2.0, DataLoader add a list surround output data(e.g. return [data]), and in Paddle >= 2.1, DataLoader return the single filed directly (e.g. return data). For example, in following code: 

import numpy as np
from paddle.io import DataLoader, Dataset

class RandomDataset(Dataset):
    def __getitem__(self, idx):
        data = np.random.random((2, 3)).astype('float32')

        return data

    def __len__(self):
        return 10

dataset = RandomDataset()
loader = DataLoader(dataset, batch_size=1)
data = next(loader())

In Paddle <= 2.0, data is in format '[Tensor(shape=(1, 2, 3), dtype=float32)]', and in Paddle >= 2.1, data is in format 'Tensor(shape=(1, 2, 3), dtype=float32)'

**Comment by chenjiaoAngel** [comment]
这个是warning不会影响正常使用，如果想去掉可以这个提示，用develop 的whl包或者等2.1.2新版本哦～

**Comment by 15162162323** [comment]
> 这个是warning不会影响正常使用，如果想去掉可以这个提示，用develop 的whl包或者等2.1.2新版本哦～

多谢了

**Comment by fangxiang00** [comment]
> 这个是warning不会影响正常使用，如果想去掉可以这个提示，用develop 的whl包或者等2.1.2新版本哦～

2.1.2版本仍存在该问题

**Comment by lleesg** [comment]
2.1.1还报这个warning，2.1.2就解决了
