### ISSUE TITLE
go (C API)调用paddleocr，nvidia TU104GL T4 gpu计算结果错误

### ISSUE THREAD

**Issue by CheQiXiao** [PaddlePaddle/Paddle#34042]
环境: linux ubuntu 18.04

gpu : nvidia TU104GL T4  腾讯云上买的gpu服务器

识别模型: 官网下载的ch_ppocr_server_v2.0_rec  通用模型，支持中英文、数字识别  rec_chinese_common_train_v2.0.yml  94.8M

paddle Inference : 2.0

使用的NVIDIA-Linux-x86_64-450.119.04.run驱动,cuda 10.0

在使用cpu处理时，识别结果正确,换成gpu后结果异常.  

不清楚是检测模型检测错误,还是识别模型识别错误。

如果有幸让相关技术团队看到，希望可以去测试一下。

希望paddle做的越来越好

论坛帖子链接：https://ai.baidu.com/forum/topic/show/989192

**Comment by jiweibo** [comment]
收到，后续复现并且在 https://github.com/PaddlePaddle/Paddle-Inference-Demo/tree/master/go 增加这个OCR对应的DEMO
