### ISSUE TITLE
paddlepaddle-gpu的版本问题

### ISSUE THREAD

**Issue by suntao2015005848** [PaddlePaddle/Paddle#34049]
为什么pip install paddlepaddle-gpu==2.1.0post101安装不上，
报错  ERROR: Could not find a version that satisfies the requirement paddlepaddle-gpu==2.1.0.post101
而aistudio的里的环境是2.1.0post101
只能安装paddlepaddle-gpu==2.1.0，这两版本一样吗？

**Comment by pangyoki** [comment]
你好，paddlepaddle-gpu==2.1.0 与 paddlepaddle-gpu==2.1.0.post101 不一样，paddlepaddle-gpu==2.1.0 是cuda10.2版本的。

你的安装命令是 `python -m pip install paddlepaddle-gpu==2.1.0.post101 -f https://paddlepaddle.org.cn/whl/mkl/stable.html` 吗？需要用 -f 指定下载链接。
