### ISSUE TITLE
提供2.1.1 cuda11.2 带tensorRT的编译whl包或者docker镜像

### ISSUE THREAD

**Issue by jackiezzq** [PaddlePaddle/Paddle#34062]
#33794  
自己用paddlepaddle/paddle:2.1.1-gpu-cuda11.2-cudnn8 docker镜像 编译的带trt的paddle在预测时报错
希望官方能提供编译好的whl包

**Comment by chenjiaoAngel** [comment]
cuda11.2没有带trt的，因为nv官方提供的trt库，不支持cuda11.2， 只有cuda11.1的
https://paddle-inference.readthedocs.io/en/latest/user_guides/download_lib.html#python
