### ISSUE TITLE
打印大维度Variable(tensor)完全的问题

### ISSUE THREAD

**Issue by markmaomao** [PaddlePaddle/Paddle#34061]
我有一个list叫at_all，其中at_all[0][0]是一个(41，768)的tensor，我想打印出这个tensor的数据
当我用paddle.fluid.layers.Print(at_all[0][0],summarize=-1, message="The content of some_layer: ")打印时，有数据但并不能打印全，而且数据是连续的不能体现每行的分隔（维度）
尝试转换成numpy打印
t = fluid.global_scope().var(at_all[0][0].name).get_tensor()
t_np = np.array(t)
print(t_np.shape)
但体现出的结果是(0,)
请问如何解决？谢谢

**Comment by chenjiaoAngel** [comment]
这个API的输出是类似这个样子的，数据就是一个连续内存的数据，不会根据shape换行的，这个是API的设置；
<img width="1123" alt="image" src="https://user-images.githubusercontent.com/38650344/125072184-d4addd80-e0ec-11eb-890a-50bc04913604.png">

打印不全的话，应该是数据量太大，会导致后续数据自动折叠的
如果想换行看数据/显示所有数据，需要自行书写打印方法

**Comment by chenjiaoAngel** [comment]
最新的paddle 2.0 版本已解决此类问题，请更新下版本～
