### ISSUE TITLE
训练时内存泄漏

### ISSUE THREAD

**Issue by whjdark** [PaddlePaddle/Paddle#34073]
- 版本、环境信息：
    1）PaddlePaddle版本：2.1.0
    2）aistudio V100 32G

训练时内存占用线性增长，BATCHSIZE无论大小都会发生，直到aistudio报错终止，初识paddle很多东西不太了解。
![242I2$PB$8@F110B6{A)C8](https://user-images.githubusercontent.com/44253501/125098621-c15d3b00-e109-11eb-9eaf-cb915c0bc4b6.png)

https://aistudio.baidu.com/studio/project/partial/verify/2158525/0bcf29c39eba4acba469a42eeb9cf57e

**Comment by zhiqiu** [comment]
hi，在AIstudio运行lan链接中的代码失败了，报错如下：

> Traceback (most recent call last):
>   File "src/main.py", line 58, in <module>
>     num_workers=0, drop_last=True, use_shared_memory=False)
>   File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/reader.py", line 404, in __init__
>     drop_last=drop_last)
>   File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dataloader/batch_sampler.py", line 125, in __init__
>     self.sampler = RandomSampler(dataset)
>   File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dataloader/sampler.py", line 211, in __init__
>     "but got num_samples={}".format(self.num_samples))
> ValueError: num_samples should be a positive integer, but got num_samples=0

请问您是否有本地可运行的代码呢？

**Comment by whjdark** [comment]
> 
> 
> hi，在AIstudio运行lan链接中的代码失败了，报错如下：
> 
> > Traceback (most recent call last):
> > File "src/main.py", line 58, in 
> > num_workers=0, drop_last=True, use_shared_memory=False)
> > File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/reader.py", line 404, in **init**
> > drop_last=drop_last)
> > File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dataloader/batch_sampler.py", line 125, in **init**
> > self.sampler = RandomSampler(dataset)
> > File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dataloader/sampler.py", line 211, in **init**
> > "but got num_samples={}".format(self.num_samples))
> > ValueError: num_samples should be a positive integer, but got num_samples=0
> 
> 请问您是否有本地可运行的代码呢？

第二段添加了解压数据集的代码
项目“pcb缺陷”共享链接(有效期三天)：https://aistudio.baidu.com/studio/project/partial/verify/2158525/6bea9bcdb9f942a8804f066a9c2de37d

**Comment by whjdark** [comment]
`
epoch in range(EPOCHS):
        #train stage
        pcbNet.train()
        for batch_id, data in enumerate(train_loader()):
            start_time = time.time()
            # 先转成paddle tensor
            img = paddle.to_tensor(data[0]) # 训练images
            labels = paddle.to_tensor(data[1]) # 训练数据标签
            preds = pcbNet(img)    # 预测结果

            # 计算损失 等价于 prepare 中loss的设置
            total_loss, cls_loss, reg_loss, loc_x_loss, loc_y_loss, theta_loss = compute_loss(preds, labels)

            # 计算准确率 等价于 prepare 中metrics的设置
            acc = compute_acc(preds, labels)

            total_loss.backward()# 反向传播
            optim.step() # 更新参数
            optim.clear_grad()# 梯度清零

            spent_time = time.time() - start_time
            # reg_loss = loc_x_loss + loc_y_loss + theta_loss 泄露？
            # log
            # if (batch_id+1) % log_freq == 0:
            #     print("[train]Epoch: {}/{}, step: {}/{}, batch cost: {:.2f}s, loss: {:.5f}, "
            #           "cls loss: {:.5f}, reg loss: {:.5f}, acc: {:.5f}, cls acc: {:.5f}, reg acc: {:.5f}".format(epoch,
            #                                                                                                  EPOCHS,
            #                                                                                                  batch_id,
            #                                                                                                  len(train_loader()),
            #                                                                                                  spent_time,
            #                                                                                                  total_loss.numpy()[0],
            #                                                                                                  cls_loss.numpy()[0],
            #                                                                                                  reg_loss.numpy()[0],
            #                                                                                                  acc.numpy()[0],
            #                                                                                                  acc.numpy()[0],
            #                                                                                                  reg_loss.numpy()[0]))
`

泄露貌似出现在print训练信息这一段，注释掉后不再出现，原因不明。

**Comment by Water2style** [comment]
和log frequency有关吗>
