### ISSUE TITLE
有关模型存储的问题

### ISSUE THREAD

**Issue by dockiHan** [PaddlePaddle/Paddle#3407]
各位老师好，我最近刚刚开始学习paddlepaddle，对于模型存储方面有一些疑惑。
1. 请问在模型存储时新一轮pass的参数值会不会覆盖上一次存储的值？
2. 如果新的参数值不会覆盖之前的值，那在加载模型时是自动选择cost最小的模型还是选择最近一次存储的模型？
3. 如何保证存储的模型一定是当前效果最好的模型（或者说cost最小的），又或者如何保证加载的模型一定是效果最好的模型？

**Comment by reyoung** [comment]
> 请问在模型存储时新一轮pass的参数值会不会覆盖上一次存储的值？

使用Python驱动Paddle训练，用户保存模型的时候，可以选择保存的文件名。用户可以配置是否覆盖。
使用paddle train二进制训练Paddle，每一次保存都是新的文件

> 如果新的参数值不会覆盖之前的值，那在加载模型时是自动选择cost最小的模型还是选择最近一次存储的模型？

如果使用Python驱动Paddle训练，用户可以在写程序时，记录下一个cost最小的模型队列。进而选择cost最小的模型
如果使用paddle train二进制训练Paddle，需要用户自己解析配置文件，选择cost最小的模型。

> 如何保证存储的模型一定是当前效果最好的模型（或者说cost最小的），又或者如何保证加载的模型一定是效果最好的模型？

和问题2一致。
