### ISSUE TITLE
显示：ABORT!!! Out of all 1 trainers, the trainer process with rank=[0] was aborted. Please check its log.terminate all the procs

### ISSUE THREAD

**Issue by LISIJIA0629** [PaddlePaddle/Paddle#34072]
[work@jupyter-3a4484a84599fe0d-0 dygraph]$ python -m paddle.distributed.launch --log_dir faster_rcnn_r101 --gpus 0 tools/train.py -c configs/faster_rcnn/faster_rcnn_r101_vd_fpn_2x_coco.yml
-----------  Configuration Arguments -----------
gpus: 0
heter_worker_num: None
heter_workers: 
http_port: None
ips: 127.0.0.1
log_dir: faster_rcnn_r101
nproc_per_node: None
run_mode: None
server_num: None
servers: 
training_script: tools/train.py
training_script_args: ['-c', 'configs/faster_rcnn/faster_rcnn_r101_vd_fpn_2x_coco.yml']
worker_num: None
workers: 
------------------------------------------------
WARNING 2021-07-09 20:42:11,441 launch.py:357] Not found distinct arguments and compiled with cuda or xpu. Default use collective mode
launch train in GPU mode!
INFO 2021-07-09 20:42:11,442 launch_utils.py:510] Local start 1 processes. First process distributed environment info (Only For Debug): 
    +=======================================================================================+
    |                        Distributed Envs                      Value                    |
    +---------------------------------------------------------------------------------------+
    |                       PADDLE_TRAINER_ID                        0                      |
    |                 PADDLE_CURRENT_ENDPOINT                 127.0.0.1:60064               |
    |                     PADDLE_TRAINERS_NUM                        1                      |
    |                PADDLE_TRAINER_ENDPOINTS                 127.0.0.1:60064               |
    |                     PADDLE_RANK_IN_NODE                        0                      |
    |                 PADDLE_LOCAL_DEVICE_IDS                        0                      |
    |                 PADDLE_WORLD_DEVICE_IDS                        0                      |
    |                     FLAGS_selected_gpus                        0                      |
    |             FLAGS_selected_accelerators                        0                      |
    +=======================================================================================+

INFO 2021-07-09 20:42:11,442 launch_utils.py:514] details abouts PADDLE_TRAINER_ENDPOINTS can be found in faster_rcnn_r101/endpoints.log, and detail running logs maybe found in faster_rcnn_r101/workerlog.0
launch proc_id:123755 idx:0
W0709 20:42:13.269433 123755 device_context.cc:404] Please NOTE: device: 0, GPU Compute Capability: 90.0, Driver API Version: 321.0, Runtime API Version: 3.1
W0709 20:42:13.273900 123755 device_context.cc:417] device: 0, MIOpen Version: 2.11.0
Traceback (most recent call last):
  File "tools/train.py", line 117, in <module>
    main()
  File "tools/train.py", line 113, in main
    run(FLAGS, cfg)
  File "tools/train.py", line 85, in run
    trainer = Trainer(cfg, mode='train')
  File "/home/work/mnt/project/PaddleDetection/dygraph/ppdet/engine/trainer.py", line 67, in __init__
    self.dataset, cfg.worker_num)
  File "/home/work/mnt/project/PaddleDetection/dygraph/ppdet/data/reader.py", line 143, in __call__
    self.dataset.parse_dataset()
  File "/home/work/mnt/project/PaddleDetection/dygraph/ppdet/data/source/coco.py", line 44, in parse_dataset
    from pycocotools.coco import COCO
  File "/home/work/.local/lib/python3.7/site-packages/pycocotools/coco.py", line 55, in <module>
    from . import mask as maskUtils
  File "/home/work/.local/lib/python3.7/site-packages/pycocotools/mask.py", line 3, in <module>
    import pycocotools._mask as _mask
  File "pycocotools/_mask.pyx", line 1, in init pycocotools._mask
ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 88 from C header, got 80 from PyObject
INFO 2021-07-09 20:42:17,473 launch_utils.py:327] terminate all the procs
ERROR 2021-07-09 20:42:17,473 launch_utils.py:584] ABORT!!! Out of all 1 trainers, the trainer process with rank=[0] was aborted. Please check its log.
INFO 2021-07-09 20:42:20,475 launch_utils.py:327] terminate all the procs

**Comment by chenjiaoAngel** [comment]
<img width="793" alt="image" src="https://user-images.githubusercontent.com/38650344/125245345-08724880-e323-11eb-822c-ac6a84ed5800.png">
这个看起来是dataset 不太正确，错误如上
