### ISSUE TITLE
paddle安装问题

### ISSUE THREAD

**Issue by 827346462** [PaddlePaddle/Paddle#34080]
![image](https://user-images.githubusercontent.com/50097546/125188815-cfc16900-e267-11eb-8c69-327565c0f284.png)
这是我重现安装paddle,当我进行验证的时候会卡在这个地方。。需要很久才能验证成功。甚至一直卡住

**Comment by qili93** [comment]
@827346462 run_check() 会简单跑一些OP的验证，因此是需要花一点时间的，但正常不会超过2-3分钟，如果卡很久都不动，可能是环境问题。请问您的测试环境是什么？请提供以下信息供分析复现，谢谢！

- 版本、环境信息：
    1）PaddlePaddle版本：请提供您的PaddlePaddle版本号（如1.1）或CommitID
    2）CPU：请提供CPU型号，MKL/OpenBlas/MKLDNN/等数学库的使用情况
    3）GPU：请提供GPU型号，CUDA和CUDNN版本号
    4）系统环境：请说明系统类型、版本（如Mac OS 10.14）、Python版本

- 安装方式信息：
1）pip安装/docker安装
2）本地编译：请提供cmake命令，编译命令
3）docker编译：请提供docker镜像，编译命令            

同时提供一下nvidia-smi的输出结果，谢谢！

**Comment by 827346462** [comment]
版本、环境信息：
   1）PaddlePaddle版本：2.1.1 paddlepaddle-gpu
   2）CPU： i7-11800H
   3）GPU：rtx3060 cuda 10.2 cudnn 7.6.5
   4）系统环境：win10 pyhon=3.6

安装方式信息：
pip安装
![image](https://user-images.githubusercontent.com/50097546/125193705-66018900-e280-11eb-82d2-3f9e2967525d.png)
之前我安装过paddle-gpu是使用十分好的。但是再次安装就出现这次的问题

**Comment by qili93** [comment]
@827346462 看你的GPU的nvidia-smi的输出，环境下已经有运行的GPU进程了？如果可以的话杀掉这个进程再跑试试看？

**Comment by 827346462** [comment]
![image](https://user-images.githubusercontent.com/50097546/125198130-38720b00-e293-11eb-83c2-b6087ba58e3b.png)
我将其他的进程杀死后重新启动 他还是卡在这个地方。它好像根本没有启动我的gpu进行计算

**Comment by 827346462** [comment]
![image](https://user-images.githubusercontent.com/50097546/125198573-efbb5180-e294-11eb-9f78-a8f409ea2492.png)
我pip安装出了问题 所以我在安装一些库是用conda进行安装的。会是这个原因么？

**Comment by qili93** [comment]
@827346462 应该问题不大呢，都能在python site-packages下面找到的话。不过最好都是统一安装方式。另一个debug的方法是，你输出`export GLOG_v=10`的环境变量，然后重跑一次，会输出一堆debug日志，把日志记录一下，日志上会有执行时间，看下时间差异特别大的2条log，看具体是卡在哪里了。

**Comment by DDDivano** [comment]
30系列的显卡应该是用不了cuda10.2，可以升级cuda库用cuda11+试试？
