### ISSUE TITLE
win10 paddlepaddle-gpu 安装成功后验证结果一直显示不出来（十几分钟后显示成功）

### ISSUE THREAD

**Issue by 827346462** [PaddlePaddle/Paddle#34087]
1）PaddlePaddle版本：paddlepaddle-gpu2.1.1 py3.6
    2）CPU：i7-11800H
    3）GPU：RTX3060 CUDA = 10.2 CUDNN = 7.6.5
    4）系统环境：win 10

- 安装方式信息：
1）pip安装
     
![image](https://user-images.githubusercontent.com/50097546/125226302-6858f700-e303-11eb-91e9-e7785ddd596a.png)

过了十几分钟才显示出来
![image](https://user-images.githubusercontent.com/50097546/125226423-a48c5780-e303-11eb-94d2-350a71f148b2.png)

杀死全部进程也是一样

**Comment by 827346462** [comment]
好像已经解决了 ，重启后

**Comment by T8T9** [comment]
👍🏻
