### ISSUE TITLE
change filed of OperatorBase to protected, use Constructor instead of Init()

### ISSUE THREAD

**Issue by jacquesqiao** [PaddlePaddle/Paddle#3408]
- Now we set all filed in OperatorBase `public` so we can access these filed very easy. But this is not so good, so we decide to change them into protected and use getter/setter to get their value. 

- After changing fields to `protected `, the `Init()` function should be removed and move the related code into OperatorBase's Constructor.

**Comment by reyoung** [comment]
The fields should be `protected` not `private`.
