### ISSUE TITLE
Better type consistency check for LayerOutput

### ISSUE THREAD

**Issue by emailweixu** [PaddlePaddle/Paddle#341]
Currently, trainer_config_helper/layers.py does a very loose of job of enforcing consistency of input arguments for layers.

We should add more type information such as dimensions, data types(e.g. Integer, DenseVector, etc), sequence info(e.g. sequence, hierachical sequence) and have an mechanism to enforce the type consistency.

**Comment by reyoung** [comment]
这个类型一致性的检查，个人感觉可以分为两个部分进行。

* 输入数据的格式(DataProvider)是不是正确
* 每一个Layer的输入是不是正确

做法分别简述如下
## DataProvider数据是否正确

目前`PyDataProvider2`支持这个检查，可以在声明`PyDataProvider2`时，将`check`设置成`True`。同时，也可以忽略掉错误的数据直接训练，即将`check`设置成`True`, 同时将`check_fail_continue`设置成True即可。

## 每一个Layer的输入是不是正确

每一个Layer可以看做是一些输入到一些输出的映射(map)。对于输入类型，我们是可以穷举的。比如 Paddle支持的数据类型包括Dense、SparseBinary、Sparse、Int，序列类型包括sequence, hierarchical sequence等，还有输入的dimension等等。

我们在每个Layer中，将这个Layer可以处理的输入类型，和他对应每个输入映射产生成的输出类型，全部标记好。在神经网络初始化完毕后，调用这个类型检查即可。所谓类型检查，就和神经网络的前向传递类似，只是我们不传递实际的数据，而是传递数据类型给每一个Layer。如果哪个Layer不能处理某个类型的输入就报错。


例如，全连接层，fc_layer的类型映射就是

```
dense, no_seq => dense, no_seq
dense, seq => dense, seq
dense, sub_seq => dense, sub_seq
sparse_binary, no_seq => sparse_binary, no_seq
sparse_binary, seq => sparse_binary,seq
sparse_binary, sub_seq => sparse_binary, sub_seq
sparse, ... => sparse, ...
other=> fail
```

所以，如果我们给一个fc layer直接传一个integer value就会报错。

这个实现点，可以有几个讨论的地方\:

* 我们可以将dense/sparse_binary/sparse统一起来看，因为他们对于Paddle都是Matrix，只是不同Matrix的子类
* 我们可以在第一次foward的时候，同时做这个check。而不是在神经网络初始化之后立即做。因为第一次forward的时候，我们是有真是数据的，这样比较好写。
   * 如果我们在第一次forward的时候，做这个check，那其实就是写一个更好的`getInput`函数，让其能够完成一些类型检查工作即可。

@emailweixu @luotao1 @hedaoyuan @qingqing01 @gangliao @backyes 来看一眼这个的实现思路上，有什么明显的问题么？

如果没有的话，我可能准备在第一次forward这个时机，在getInput里面，写一下这个类型检查了。这样实现代价最小。

**Comment by backyes** [comment]
@reyoung 
```我们可以在第一次foward的时候，同时做这个check。而不是在神经网络初始化之后立即做。因为第一次forward的时候，我们是有真是数据的，这样比较好写```
从要检查几种类型上看， 应该都能做到static check吧， 还有哪些check必须要在forward的时候检查呢? 如果能static 检查，是否在初始化阶段比较好？

**Comment by reyoung** [comment]
static是指？

* 编译时检查？
* 运行时检查一遍？

如果是指后面的话，运行时检查一遍在forward时候也可以做到。

**Comment by backyes** [comment]
@reyoung 我说的static是指在模型各个layer初始化的时候做check，相对于每个forward都做check。

**Comment by reyoung** [comment]
1、我说的实现里面没有任何一种实现是**每次forward**都会check。
> 我们可以在第一次foward的时候，同时做这个check。而不是在神经网络初始化之后立即做。因为第一次forward的时候，我们是有真是数据的，这样比较好写。

2、static_assert或者static_check这东西很容易误解，其实大部分人说static check是指编译期检查。

3、什么是`每个forward`？是每个Layer的第一次forward还是指的每个Layer的每次forward？

**Comment by backyes** [comment]
@reyoung  看来我没有什么问题了， 原句措辞已经update。

**Comment by qingqing01** [comment]
close this issue due to the refactoring
