### ISSUE TITLE
Notebook环境下用cloudpickle序列化Paddle 2.0模型，不能在其他进程被反序列化

### ISSUE THREAD

**Issue by zenghsh3** [PaddlePaddle/Paddle#34105]
- Paddle静态图和Torch都支持该使用场景
- 可复现的AIStudio环境：
  - paddle 2.0 + cloudpickle: https://aistudio.baidu.com/aistudio/projectdetail/2181066?shared=1
  - paddle 2.0 + PARL: https://aistudio.baidu.com/aistudio/projectdetail/2178599?shared=1

**Comment by T8T9** [comment]
这个问题报错是"metaclass conflict", 没有发生在paddle中, 看起来是parl 或 cloudpickle 或 其他环境导致的, 您可以继续深入定位一下问题.

**Comment by chenwhql** [comment]
有两个问题确认下：
1. 您给出的两个例子之间有关联吗？如果有的话是什么，PARL内部使用的是cloudpickle吗？
2. Paddle静态图在这个场景下pickle的是什么对象？Program？

**Comment by zenghsh3** [comment]
1. PARL内部使用的是cloudpickle，第一个例子是为了不引入PARL的情况下复现这个问题
2. Paddle静态图或者动态图在这个场景下都只是pickle了继承nn.Layers的类（不是实例化后的对象），具体可以参考cloudpickle[文档](https://github.com/cloudpipe/cloudpickle)

**Comment by chenwhql** [comment]
关于2，没太明白，意思是静态图这么写就可以吗？好像我试了下也没过，能否给个demo

**Comment by zenghsh3** [comment]
表述可能有点问题，静态图下+parl/cloudpickle是可以正常进行的，但静态图下用法不是继承nn.Layers的类；
torch下类似的继承nn.Module也是可以正常运行的

**Comment by chenwhql** [comment]
现在比较困惑的是，Layer并没有metaclass，不知道为啥会报这个，以及这个报错栈里也没有paddle，这个您还有什么线索吗

**Comment by zenghsh3** [comment]
我在types.py文件里加入了打印引起异常的base class，https://aistudio.baidu.com/aistudio/projectdetail/2206966?shared=1
![image](https://user-images.githubusercontent.com/5762635/126310192-0b5e249c-a4d3-45e9-963f-b9fe0a0587c0.png)
我猜测可能跟这个类（paddle.fluid.dygraph.layers.Layer）的父类（core.Layer）相关：
https://github.com/PaddlePaddle/Paddle/blob/b5aab4f0dde82c0d6290f1708cc4bf402c15d103/python/paddle/fluid/dygraph/layers.py#L81
core.Layer是C++封装的类，是否是封装方式这类的问题？

**Comment by chenwhql** [comment]
好，我查下pybind在这块有没有什么坑

**Comment by chenwhql** [comment]
![image](https://user-images.githubusercontent.com/22561442/126993884-ae1654d9-87da-4043-847a-b4aab1c49ba1.png)
pybind官网这里有个注意事项，我们Layer竟然没有这个调用init，但加上了也还是这个错

**Comment by chenwhql** [comment]
我们再接着看看

**Comment by hbwx24** [comment]
把PaddleObject单独定义在一个模块里面，然后在包含test_cloudpickle的文件中import这个类。

model2021.py 内容：
```python
import paddle

class PaddleObject(paddle.nn.Layer):
    def __init__(self):
        super(PaddleObject, self).__init__()
        self.linear_1 = paddle.nn.Linear(784, 512)
```

main.py 内容：
```python
from model2021 import PaddleObject

def test_cloudpickle(cls):
    ...

test_cloudpickle(PaddleObject)
```
这样可以吗？

**Comment by zenghsh3** [comment]
还是希望可以支持Notebook环境哈

**Comment by hbwx24** [comment]
我们再接着看看

**Comment by zenghsh3** [comment]
fixed in #35538
