### ISSUE TITLE
只是安装在annaconda虚拟环境中的cudnn能支持paddle的安装吗

### ISSUE THREAD

**Issue by deadkany** [PaddlePaddle/Paddle#34117]
为使您的问题得到快速解决，在建立Issue前，请您先通过如下方式搜索是否有相似问题:【搜索issue关键字】【使用labels筛选】【官方文档】

建立issue时，为快速解决问题，请您根据使用情况给出如下信息：
- 标题：请包含关键词“安装错误”/“编译错误”，例如“Mac编译错误”
- 版本、环境信息：
    1）PaddlePaddle版本：请提供您的PaddlePaddle版本号（如1.1）或CommitID
    2）CPU：请提供CPU型号，MKL/OpenBlas/MKLDNN/等数学库的使用情况
    3）GPU：请提供GPU型号，CUDA和CUDNN版本号
    4）系统环境：请说明系统类型、版本（如Mac OS 10.14）、Python版本
注：您可以通过执行[summary_env.py](https://github.com/PaddlePaddle/Paddle/blob/develop/tools/summary_env.py)获取以上信息。
- 安装方式信息：
1）pip安装/docker安装
2）本地编译：请提供cmake命令，编译命令
3）docker编译：请提供docker镜像，编译命令            
  特殊环境请注明：如离线安装等
- 复现信息：如为报错，请给出复现环境、复现步骤
- 问题描述：请详细描述您的问题，同步贴出报错信息、日志/代码关键片段

Thank you for contributing to PaddlePaddle.
Before submitting the issue, you could search issue in Github in case that there was a similar issue submitted or resolved before.
If there is no solution,please make sure that this is an installation issue including the following details:
**System information**
-PaddlePaddle version （eg.1.1）or CommitID
-CPU: including CPUMKL/OpenBlas/MKLDNN version
-GPU: including CUDA/CUDNN version
-OS Platform (eg. Mac OS 10.14)
-Python version
- Install method: pip install/install with docker/build from source(without docker)/build within docker
- Other special cases that you think may be related to this problem, eg. offline install, special internet condition 
Note: You can get most of the information by running [summary_env.py](https://github.com/PaddlePaddle/Paddle/blob/develop/tools/summary_env.py).   

**To Reproduce**
Steps to reproduce the behavior
**Describe your current behavior**
**Code to reproduce the issue**
**Other info / logs**

**Comment by yinhaofeng** [comment]
您的物理机上是有显卡的吗？

**Comment by deadkany** [comment]
> 您的物理机上是有显卡的吗？

有的，但是只装了cuda，没有安装cudnn，由于权限原因无法安装cudnn，所以想在conda的虚拟环境中安装cudnn，但是paddle.utils.run_check()会报错

**Comment by yinhaofeng** [comment]
conda环境里应该是可以安装paddle的，但是注意安装的版本要和cudnn对应。如果已经是对应的，可以把报错内容贴一下

**Comment by deadkany** [comment]
> conda环境里应该是可以安装paddle的，但是注意安装的版本要和cudnn对应。如果已经是对应的，可以把报错内容贴一下

已经是对应的
Running verify PaddlePaddle program ... 
W0713 14:52:58.419963 34071 device_context.cc:404] Please NOTE: device: 0, GPU Compute Capability: 6.1, Driver API Version: 10.1, Runtime API Version: 10.1
W0713 14:52:58.420265 34071 dynamic_loader.cc:267] The third-party dynamic library (libcudnn.so) that Paddle depends on is not configured correctly. (error code is libcudnn.so: cannot open shared object file: No such file or directory)
  Suggestions:
  1. Check if the third-party dynamic library (e.g. CUDA, CUDNN) is installed correctly and its version is matched with paddlepaddle you installed.
  2. Configure third-party dynamic library environment variables as follows:
  - Linux: set LD_LIBRARY_PATH by `export LD_LIBRARY_PATH=...`
  - Windows: set PATH by `set PATH=XXX;
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/export/home/yaopu/anaconda3/envs/ylx/lib/python3.7/site-packages/paddle/utils/install_check.py", line 196, in run_check
    _run_static_single(use_cuda)
  File "/export/home/yaopu/anaconda3/envs/ylx/lib/python3.7/site-packages/paddle/utils/install_check.py", line 124, in _run_static_single
    exe.run(startup_prog)
  File "/export/home/yaopu/anaconda3/envs/ylx/lib/python3.7/site-packages/paddle/fluid/executor.py", line 1110, in run
    six.reraise(*sys.exc_info())
  File "/export/home/yaopu/anaconda3/envs/ylx/lib/python3.7/site-packages/six.py", line 703, in reraise
    raise value
  File "/export/home/yaopu/anaconda3/envs/ylx/lib/python3.7/site-packages/paddle/fluid/executor.py", line 1108, in run
    return_merged=return_merged)
  File "/export/home/yaopu/anaconda3/envs/ylx/lib/python3.7/site-packages/paddle/fluid/executor.py", line 1239, in _run_impl
    use_program_cache=use_program_cache)
  File "/export/home/yaopu/anaconda3/envs/ylx/lib/python3.7/site-packages/paddle/fluid/executor.py", line 1329, in _run_program
    [fetch_var_name])
RuntimeError: (PreconditionNotMet) Cannot load cudnn shared library. Cannot invoke method cudnnGetVersion.
  [Hint: cudnn_dso_handle should not be null.] (at /paddle/paddle/fluid/platform/dynload/cudnn.cc:59)

**Comment by deadkany** [comment]
> conda环境里应该是可以安装paddle的，但是注意安装的版本要和cudnn对应。如果已经是对应的，可以把报错内容贴一下

设置了变量路径到anaconda里就好了，问题已解决

**Comment by Peng-ss** [comment]
你好，请问如何设置变量路径到anaconda?

**Comment by deadkany** [comment]
> 你好，请问如何设置变量路径到anaconda?

export LD_LIBRARY_PATH='你的虚拟环境位置/lib'

**Comment by Peng-ss** [comment]
> > 你好，请问如何设置变量路径到anaconda?
> 
> export LD_LIBRARY_PATH='你的虚拟环境位置/lib'

感激大佬

**Comment by 301122** [comment]
> 

感谢大佬，终于解决了
