### ISSUE TITLE
Compiling error on RedHat

### ISSUE THREAD

**Issue by buptxiaofeng** [PaddlePaddle/Paddle#34125]
**System information**
-PaddlePaddle version:  2.1.1
-CPU: including CPUMKL/OpenBlas/MKLDNN version: openblas/0.3.15
-GPU: including CUDA/CUDNN version : cudnn/8.0.5 gcc/8.5.0 nccl/2.9.9 cuda-11.0.3
-OS Platform (eg. Mac OS 10.14)

ppc64le
NAME="Red Hat Enterprise Linux"
VERSION="8.2 (Ootpa)"
ID="rhel"
ID_LIKE="fedora"
VERSION_ID="8.2"
PLATFORM_ID="platform:el8"
PRETTY_NAME="Red Hat Enterprise Linux 8.2 (Ootpa)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:8.2:GA"
HOME_URL="https://www.redhat.com/"
BUG_REPORT_URL="https://bugzilla.redhat.com/

-Python version: 3.8
- Install method: build from source(without docker)

Compile command:
cmake .. -DPY_VERSION=3.5 -DWITH_FLUID_ONLY=ON -DWITH_GPU=ON -DWITH_TESTING=OFF -DCMAKE_BUILD_TYPE=Release -DNO_WARN_X86_INTRINSICS

make

Error Message:

In file included from ../kernel/power/sscal.c:39:
../kernel/power/sscal_microk_power8.c:136:8: error: unknown register name 'vs32' in asm
       "vs32","vs33","vs34","vs35","vs36","vs37","vs38","vs39",
       ^
...
In file included from ../kernel/power/scopy.c:39:
../kernel/power/scopy_microk_power8.c:110:8: error: unknown register name 'vs40' in asm
       "vs40","vs41","vs42","vs43","vs44","vs45","vs46","vs47"
4 warnings and 1 error generated
...

**Comment by yinhaofeng** [comment]
您的环境是x86架构的吗？
目前我们还没有验证过在redhat上的编译，建议您可以再我们paddle的官网上直接使用docker安装。

**Comment by buptxiaofeng** [comment]
> 您的环境是x86架构的吗？
> 目前我们还没有验证过在redhat上的编译，建议您可以再我们paddle的官网上直接使用docker安装。

不是x86, 是PPC
