### ISSUE TITLE
请问有没有在Jetson平台编译好的paddle-1.8的.whl包

### ISSUE THREAD

**Issue by PhilCuriosity** [PaddlePaddle/Paddle#34131]
系统环境：jetpack4.4或者jetpack4.5
目前使用的paddle-2.0存在一些问题，如[#33807](https://github.com/PaddlePaddle/Paddle/issues/33807)

**Comment by yinhaofeng** [comment]
你好，Jeston版本我们推荐直接使用2.1的，新版本有较多的同学维护，bug也更少。可以根据您的需要在这里找到对应的版本：https://paddleinference.paddlepaddle.org.cn/master/user_guides/download_lib.html
1.8的版本比较老，官网上已经没有了，如果需要只能参考官网jeston的编译流程自行编译
如果遇到兼容问题也欢迎反馈

**Comment by PhilCuriosity** [comment]
> 你好，Jeston版本我们推荐直接使用2.1的，新版本有较多的同学维护，bug也更少。可以根据您的需要在这里找到对应的版本：https://paddleinference.paddlepaddle.org.cn/master/user_guides/download_lib.html
> 1.8的版本比较老，官网上已经没有了，如果需要只能参考官网jeston的编译流程自行编译
> 如果遇到兼容问题也欢迎反馈

好的，谢谢
