### ISSUE TITLE
ExternalError:  Cudnn error, CUDNN_STATUS_BAD_PARAM  at (/paddle/paddle/fluid/operators/batch_norm_op.cu:198)

### ISSUE THREAD

**Issue by wj51** [PaddlePaddle/Paddle#34166]
- 标题：请包含关键词“安装错误”/“编译错误”，例如“Mac编译错误”
- 版本、环境信息：
    1）PaddlePaddle版本：paddlepaddle-gpu   1.8.4.post107
    2）CPU：请提供CPU型号，MKL/OpenBlas/MKLDNN/等数学库的使用情况
    3）GPU：请提供GPU型号，CUDA：10.0和CUDNN7.4
    4）系统环境：请说明系统类型、版本（如Mac OS 10.14）、Python版本
注：您可以通过执行[summary_env.py](https://github.com/PaddlePaddle/Paddle/blob/develop/tools/summary_env.py)获取以上信息。
- 安装方式信息：
1） CUDA_VISIBLE_DEVICES=0 python tools/infer.py -c configs/ppyolo/ppyolo.yml -o weights=https://paddlemodels.bj.bcebos.com/object_detection/ppyolo.pdparams --infer_dir=demo
     

- 复现信息：如为报错，请给出复现环境、复现步骤
- 问题描述：请详细描述您的问题，同步贴出报错信息、日志/代码关键片段

**Comment by MissPenguin** [comment]
您好，看样子是CUDNN7.4版本过低，建议换CUDNN7.6哈

**Comment by lucky0604** [comment]
@MissPenguin 解决这个问题只能通过修改cudnn版本吗？由于训练环境的原因，无法进行更换，只能使用cuda10.2和cudnn 7.4，是不是没有办法
