### ISSUE TITLE
windows 找不到libyaml-cppmt.lib

### ISSUE THREAD

**Issue by carol510** [PaddlePaddle/Paddle#34163]
为使您的问题得到快速解决，在建立Issue前，请您先通过如下方式搜索是否有相似问题:【搜索issue关键字】【使用labels筛选】【官方文档】

建立issue时，为快速解决问题，请您根据使用情况给出如下信息：
- 标题：请包含关键词“安装错误”/“编译错误”，例如“Mac编译错误”
- 版本、环境信息：
    1）PaddlePaddle版本：请提供您的PaddlePaddle版本号 ppdet 2.1 
<img width="266" alt="f1dec08e4ae15d58e179e6292249d8ae" src="https://user-images.githubusercontent.com/22268236/125631409-5654279b-e6dc-4a83-94d7-6a9e023273b6.png">
https://paddleinference.paddlepaddle.org.cn/user_guides/download_lib.html#windows 用的cuda 10.2的库
    3）GPU：请提供GPU型号 3070。CUDA10.2 和CUDNN版本号 8.0
    4）系统环境：请说明系统类型、版本 win10  c++预测
 找不到libyaml-cppmt.lib
下载源码https://github.com/jbeder/yaml-cpp编译，无法生成库生成库libyaml-cppmt.lib 生成名字为yaml-cpp.lib
直接依赖yaml-cpp.lib 报错
![D4D1C2D6FE204F52C1DF7A19A3A660C7](https://user-images.githubusercontent.com/22268236/125632411-10c8d390-d49e-4a10-9b6a-6a8f1ce849f2.jpg)

**Comment by MissPenguin** [comment]
你的cudnn版本是8.0，但是安装包是7.6，版本不匹配，可以把本地换成cudnn7.6试试

**Comment by carol510** [comment]
> 你的cudnn版本是8.0，但是安装包是7.6，版本不匹配，可以把本地换成cudnn7.6试试
我写错了 cundnn 确实是7.6

**Comment by MissPenguin** [comment]
您好，libyaml-cppmt.lib编译问题可以网上找下有没有解决方案哈，另外，win系统下使用Paddle建议先安装docker，不然win系统确实比较容易出环境问题，也不太好查。

**Comment by 1329844541** [comment]
1.更改项目为Release

2.找到libyaml-cppmt.lib文件，将其添加lib文件： 配置属性-->链接器-->输入-->附加依赖项加入库名（×××.lib）；

**Comment by pcycccccc** [comment]
解决了吗，我也遇到了这个问题。编译没有生成该文件的lib

**Comment by 1314520gu** [comment]
请问有人解决了吗
