### ISSUE TITLE
paddle 对昇腾310支持的文档问题

### ISSUE THREAD

**Issue by entropyfeng** [PaddlePaddle/Paddle#34167]
非常感谢您提交关于飞桨文档的Issue，我们会认真听取您的意见，并进行改进。

建立issue时，为快速解决问题，请您根据情况给出如下信息：
- 标题：请包含关键词“XXX文档问题”，例如“add 文档问题” 或 ”paddle.add 文档问题“
- 文档版本信息：请提供有问题的文档的版本号，例如 develop，1.8，2.0RC；

### 文档问题描述：
您好，我在[官网](https://www.paddlepaddle.org.cn/documentation/docs/zh/guides/09_hardware_support/hardware_info_cn.h)上看到对Paddle Lite昇腾310源码编译即将提供，这个即将，预计要多久？
paddle文档2.1

**Comment by littletomatodonkey** [comment]
你好，要不看下这个是否符合你的要求呢？https://www.paddlepaddle.org.cn/documentation/docs/zh/guides/09_hardware_support/npu_docs/paddle_install_cn.html

**Comment by entropyfeng** [comment]
> 你好，要不看下这个是否符合你的要求呢？https://www.paddlepaddle.org.cn/documentation/docs/zh/guides/09_hardware_support/npu_docs/paddle_install_cn.html

您好昇腾310是针对边缘设备的而不是服务器吧？这个链接是paddle编译，我们需要的是paddleLite，谢谢！

**Comment by littletomatodonkey** [comment]
哦哦，看这个PaddleLite的文档，应该是已经支持了哈

https://paddle-lite.readthedocs.io/zh/latest/introduction/support_hardware.html

![image](https://user-images.githubusercontent.com/14270174/125793087-43a10f4a-d98b-4ab8-8774-684fee4c2bc5.png)

**Comment by entropyfeng** [comment]
> 哦哦，看这个PaddleLite的文档，应该是已经支持了哈
> 
> https://paddle-lite.readthedocs.io/zh/latest/introduction/support_hardware.html
> 
> ![image](https://user-images.githubusercontent.com/14270174/125793087-43a10f4a-d98b-4ab8-8774-684fee4c2bc5.png)

但是PaddleLite的部署文档和源码编译文档中仍没有对昇腾310的描述？Android和ARM Linux都没有。。

**Comment by littletomatodonkey** [comment]
你好，刚才问了下，最近正在做，预计两周内会把代码和文档提交到develop分支哈，到时候可以用develop分支进行开发哈

**Comment by entropyfeng** [comment]
好的，非常感谢！

**Comment by littletomatodonkey** [comment]
这个是针对atlas300的，如果是atlas200dk或者其他硬件的话，可能还要再等等哈

**Comment by entropyfeng** [comment]
> 这个是针对atlas300的，如果是atlas200dk或者其他硬件的话，可能还要再等等哈

预计要等多久啊？

**Comment by littletomatodonkey** [comment]
这个最早可能得下个月

**Comment by entropyfeng** [comment]
> 这个最早可能得下个月

好的谢谢！

**Comment by IT-Xue** [comment]
> 这个最早可能得下个月

您好，这个现在咋样了，针对华为atlas300的这个适配。

**Comment by littletomatodonkey** [comment]
你好，已经上线了，可以看下
https://paddle-lite.readthedocs.io/zh/develop/demo_guides/huawei_ascend_npu.html

**Comment by IT-Xue** [comment]
> 你好，已经上线了，可以看下
> https://paddle-lite.readthedocs.io/zh/develop/demo_guides/huawei_ascend_npu.html

感谢您的回复，请问paddlepaddle有计划支持吗？
