### ISSUE TITLE
安装paddle报错

### ISSUE THREAD

**Issue by ZZHHogan** [PaddlePaddle/Paddle#34180]
为使您的问题得到快速解决，在建立Issue前，请您先通过如下方式搜索是否有相似问题:【搜索issue关键字】【使用labels筛选】【官方文档】

建立issue时，为快速解决问题，请您根据使用情况给出如下信息：
- 标题：请包含关键词“安装错误”/“编译错误”，例如“Mac编译错误”
- 版本、环境信息：
    1）PaddlePaddle版本：2.0.0
    2）CPU：---
    3）GPU：3090显卡 GPU版本11.2
    4）系统环境：centos、Python版本 3.8

- 安装方式信息：
1）pip安装  pip install paddlepaddle-gpu==2.0.0 -i https://mirror.baidu.com/pypi/simple
安装paddle gpu版本后运行paddle.utils.run_check()命令报错

报错日志：
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-3-afc005eaa74e> in <module>
----> 1 paddle.utils.run_check()

~/.jupyter/Paddlepaddle-2.0.0/lib/python3.8/site-packages/paddle/utils/install_check.py in run_check()
    162     device_count = len(device_list)
    163 
--> 164     _run_static_single(use_cuda)
    165     print("PaddlePaddle works well on 1 {}.".format(device_str))
    166 

~/.jupyter/Paddlepaddle-2.0.0/lib/python3.8/site-packages/paddle/utils/install_check.py in _run_static_single(use_cuda)
     94         exe = paddle.static.Executor(
     95             paddle.CUDAPlace(0) if use_cuda else paddle.CPUPlace())
---> 96         exe.run(startup_prog)
     97         exe.run(train_prog,
     98                 feed={input.name: _prepare_data(1)},

~/.jupyter/Paddlepaddle-2.0.0/lib/python3.8/site-packages/paddle/fluid/executor.py in run(self, program, feed, fetch_list, feed_var_name, fetch_var_name, scope, return_numpy, use_program_cache, return_merged, use_prune)
   1108                 return_merged=return_merged)
   1109         except Exception as e:
-> 1110             six.reraise(*sys.exc_info())
   1111 
   1112     def _run_impl(self, program, feed, fetch_list, feed_var_name,

~/.jupyter/Paddlepaddle-2.0.0/lib/python3.8/site-packages/six.py in reraise(tp, value, tb)
    701             if value.__traceback__ is not tb:
    702                 raise value.with_traceback(tb)
--> 703             raise value
    704         finally:
    705             value = None

~/.jupyter/Paddlepaddle-2.0.0/lib/python3.8/site-packages/paddle/fluid/executor.py in run(self, program, feed, fetch_list, feed_var_name, fetch_var_name, scope, return_numpy, use_program_cache, return_merged, use_prune)
   1096         """
   1097         try:
-> 1098             return self._run_impl(
   1099                 program=program,
   1100                 feed=feed,

~/.jupyter/Paddlepaddle-2.0.0/lib/python3.8/site-packages/paddle/fluid/executor.py in _run_impl(self, program, feed, fetch_list, feed_var_name, fetch_var_name, scope, return_numpy, use_program_cache, return_merged, use_prune)
   1228                     return_merged=return_merged)
   1229 
-> 1230             return self._run_program(
   1231                 program,
   1232                 feed=feed,

~/.jupyter/Paddlepaddle-2.0.0/lib/python3.8/site-packages/paddle/fluid/executor.py in _run_program(self, program, feed, fetch_list, feed_var_name, fetch_var_name, scope, return_numpy, use_program_cache)
   1325 
   1326         if not use_program_cache:
-> 1327             self._default_executor.run(program.desc, scope, 0, True, True,
   1328                                        [fetch_var_name])
   1329         else:

RuntimeError: parallel_for failed: cudaErrorNoKernelImageForDevice: no kernel image is available for execution on the device

**Comment by littletomatodonkey** [comment]
试下升级paddle呢？pip install -U paddlepaddle-gpu==2.0.2

**Comment by ZZHHogan** [comment]
可以的，我通过更改版本就能成功安装和测试了

**Comment by littletomatodonkey** [comment]
嗯嗯好的~
