### ISSUE TITLE
dropout_rate的实际意义

### ISSUE THREAD

**Issue by youan1** [PaddlePaddle/Paddle#3420]
如题，dropout_layer2=paddle.layer.dropout(input=hd2, dropout_rate=0.2)，dropout_rate=0.2,是丢掉20%的输入，还是保留20%的输入

 model_average=paddle.optimizer.ModelAverage(average_window=0.5)， model_average是momentum么，哪里能找到文档

谢谢！

**Comment by reyoung** [comment]
> dropout_layer2=paddle.layer.dropout(input=hd2, dropout_rate=0.2)，dropout_rate=0.2,是丢掉20%的输入，还是保留20%的输入

扔掉20%

> model_average=paddle.optimizer.ModelAverage(average_window=0.5)， model_average是momentum么，哪里能找到文档

Moving Average不是momentum，他是指神经网络训练的参数并不是最终模型使用的参数，模型使用的参数是训练时参数的滑动平均，0.5指滑动窗口大小。

https://www.reddit.com/r/tensorflow/comments/5zsc5g/what_does_moving_average_do_when_training_a/
