### ISSUE TITLE
paddle 源码安装报错 Segmentation fault

### ISSUE THREAD

**Issue by hjx3325** [PaddlePaddle/Paddle#34203]
系统环境：Centos 7.9 + cuda10.2

按照官方流程用源码方式安装

https://www.paddlepaddle.org.cn/install/quick?docurl=/documentation/docs/zh/install/compile/linux-compile.html#anchor-5

最后 cmake 后执行 make -j$(nproc) 编译，到最后报错，如下：

[ 99%] Built target paddle_inference_c
[ 99%] Generating .check_symbol
[ 99%] Building CXX object paddle/fluid/pybind/CMakeFiles/paddle_pybind.dir/pybind.cc.o
[ 99%] Built target check_symbol
c++: internal compiler error: Segmentation fault signal terminated program cc1plus
Please submit a full bug report,
with preprocessed source if appropriate.
See for instructions.
make[2]: *** [paddle/fluid/pybind/CMakeFiles/paddle_pybind.dir/pybind.cc.o] Error 4
make[1]: *** [paddle/fluid/pybind/CMakeFiles/paddle_pybind.dir/all] Error 2
make: *** [all] Error 2

似乎像是编译崩溃了，编译的同时 top 观察资源占用情况，发现 cc1plus 内存使用一直涨到 2G左右后崩溃

大概定位了下，应该是编译下面这个地方的时候崩溃的，手动编译同样还是会报错，不清楚是什么问题导致

/usr/bin/c++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -o CMakeFiles/paddle_pybind.dir/pybind.cc.o -c /home/paddle/Paddle/paddle/fluid/pybind/pybind.cc

**Comment by zhwesky2010** [comment]
@hjx3325 你好，请问是否内存被其他地方占用了呢，paddle我们每天都在进行集成编译，编译是没有语法问题的，可能是内存不够的原因，建议make -j1降低并发编译
