### ISSUE TITLE
手动修改梯度

### ISSUE THREAD

**Issue by ziyaxuanyi** [PaddlePaddle/Paddle#34211]
请问如何修改一个model在训练过程中训练参数tensor的梯度grad？
因为要消除loss权重的影响，需要手动修改grad，但是报错can't set attribute

**Comment by zhwesky2010** [comment]
@ziyaxuanyi tensor.grad只是会返回tensor的梯度，只有get_attr，没有写set_attr。如果要inplace修改Tensor，可以试试 `x[:]=1`

**Comment by docoter** [comment]
Tensor(要修改梯度的数据).grad.set_value(Tensor(要赋予的值))
