### ISSUE TITLE
【单机多卡训练】Fail to open /proc/self/io: Permission denied

### ISSUE THREAD

**Issue by lytning98** [PaddlePaddle/Paddle#34215]
单机多卡训练时出现 warning
```
W0716 21:58:58.758108 37226 default_variables.cpp:429] Fail to open /proc/self/io: Permission denied [13] 
```
随后程序卡死不再有任何运行进展。
**复现情况**：一段时间以来一直可以正常训练，某次训练时突然报错，自此之后每次运行都会复现，**大部分情况下重启机器也无法恢复正常**，单卡训练无此问题
请问这会是什么原因导致的？在本 repo 的源码中没有找到这个cpp文件（似乎是 CUDA 相关的源文件），也没有查询到相关资料。
训练代码中与单机多卡训练有关的[代码](https://github.com/lytning98/taming-paddle/blob/3f40f57b36fec56501127fec5c2c4a0aaa439636/train.py#L218-L219)

#### 附：环境信息
ubuntu 16.04
单卡训练
来自 conda 的环境信息：
```
cudatoolkit               10.1.243             h6bb024c_0    https://mirrors.bfsu.edu.cn/anaconda/pkgs/main
cudnn                     7.6.5                cuda10.1_0    https://mirrors.bfsu.edu.cn/anaconda/pkgs/main
paddlepaddle-gpu          2.1.0           py39_gpu_cuda10.1_many_linux    https://mirrors.bfsu.edu.cn/anaconda/cloud/Paddle
python                    3.9.5                hdb3f193_3    https://mirrors.bfsu.edu.cn/anaconda/pkgs/main 
```
Paddle says,
```
W0707 19:37:50.479267 29830 device_context.cc:404] Please NOTE: device: 0, GPU Compute Capability: 7.5, Driver API Version: 11.2, Runtime API Version: 10
.1                               
W0707 19:37:50.481541 29830 device_context.cc:422] device: 0, cuDNN Version: 7.6.
```

**Comment by lytning98** [comment]
`GLOG_v=3` 时的 [stderr log](https://gist.github.com/lytning98/2231433c39f68b9a1e1570c3e92f5b13)

**Comment by lytning98** [comment]
UPDATE: 再重启一次机器就恢复正常了，但估计还是会偶尔复现

**Comment by lytning98** [comment]
似乎是由于其他原因导致进程崩溃，暂时关闭issue

**Comment by zhwesky2010** [comment]
@lytning98 看起来是操作系统的问题，无法打开这个文件 /proc/self/io，应该是没有管理员权限，sudo试下

**Comment by Yikunzhang** [comment]
请问这个问题解决了吗，我也碰到同样的问题

**Comment by lytning98** [comment]
> @Yikunzhang: 请问这个问题解决了吗，我也碰到同样的问题

解决了，出现这个问题是因为训练程序由于 exception 或者其他问题导致某个进程 crash 掉了，crash 之后自然没法读写 `/proc/self` 目录。但在多卡多进程训练的情况下 paddle 没有输出任何错误信息，让我误以为这行 warning 是报错信息。
可以先尝试单卡训练看是否报错，如果错误仅能在多卡的时候复现的话可以尝试使用 debug 工具调试，我是用 vscode 在 debug 状态下找到的问题，vscode 的 debugger 可以正确展示真正的报错信息。

@zhouwei25 FYI，感觉没有报错信息应该是 bug，有时间我详细看下再提新的 issue
