### ISSUE TITLE
paddle带capi编译dense demo报错

### ISSUE THREAD

**Issue by bushidonggua** [PaddlePaddle/Paddle#3422]
跑capi/examples/model_inference/dense
paddle带capi用的这个版本：
![image](https://user-images.githubusercontent.com/5506467/29209571-dc895714-7ec1-11e7-8087-d3b4e4f4e961.png)

报错：
/usr/bin/make64 MAC=64
Scanning dependencies of target dense
[100%] Building C object CMakeFiles/dense.dir/main.c.o
Linking C executable dense
/opt/compiler/gcc-4.8.2/lib/libpthread.so.0: undefined reference to `__mktemp@GLIBC_PRIVATE'
/opt/compiler/gcc-4.8.2/lib/libpthread.so.0: undefined reference to `__madvise@GLIBC_PRIVATE'
/home/work/chenlimin/paddlepaddle/usr/local/lib/libpaddle_capi_shared.so: undefined reference to `memcpy@GLIBC_2.14'
/opt/compiler/gcc-4.8.2/lib/libpthread.so.0: undefined reference to `__ctype_init@GLIBC_PRIVATE'
/opt/compiler/gcc-4.8.2/lib/libpthread.so.0: undefined reference to `__call_tls_dtors@GLIBC_PRIVATE'
/opt/compiler/gcc-4.8.2/lib/libstdc++.so.6: undefined reference to `clock_gettime@GLIBC_2.17'
collect2: ld returned 1 exit status
make64[2]: *** [dense] Error 1
make64[1]: *** [CMakeFiles/dense.dir/all] Error 2
make64: *** [all] Error 2

**Comment by gongweibao** [comment]
请用公司内部的编译器，路径在`/opt/compiler`下。

**Comment by zds9204** [comment]
提问者用的就是公司的编译器吧。。我也遇到了这个问题，如果你用的是CMakeList，最后加入一行target_link_libraries (appName Threads::Threads)，如果直接用命令行编译，可以在后面加入-lpthread

**Comment by luotao1** [comment]
提问者用的就是公司的编译器吧。。我也遇到了这个问题，如果你用的是CMakeList，最后加入一行target_link_libraries (appName Threads::Threads)，如果直接用命令行编译，可以在后面加入-lpthread
(copy by 风鱼的歌)
