### ISSUE TITLE
Segfault on trivial transpose

### ISSUE THREAD

**Issue by arogozhnikov** [PaddlePaddle/Paddle#34220]
**System information**
-PaddlePaddle version 2.1.1
-CPU: including CPUMKL/OpenBlas/MKLDNN version
-GPU: not used
-OS Platform and Distribution: Mac OS 10.15
-Python version: 3.9.0
Note: You can get most of the information by running [summary_env.py](https://github.com/PaddlePaddle/Paddle/blob/develop/tools/summary_env.py). 

**To Reproduce**
See code below. Paddlepaddle doesn't handle zero-dimensional tensors (same issue as in mxnet v1, now fixed)

**Describe your current behavior**

Code segfaults.
```
[1]    71657 segmentation fault  ipython
```
**Code to reproduce the issue**
```python
import paddle

paddle.zeros([]).transpose([]) # should return 0-dimensional tensor with 1 element, basically transpose should do nothing

paddle.zeros([]).reshape([]) # should return 0-dimensional tensor with 1 element, basically reshape should do nothing
```
**Other info / logs**

Support for zero-dimensional tensor is a hard requirement for inclusion for [einops](https://github.com/arogozhnikov/einops) support. 

Currently paddlepaddle can't pass the tests due to this issue

**Comment by joey12300** [comment]
@arogozhnikov thanks for providing details about processing zero-dimensional tensor in transpose (reshape). We will upgrade the ability of processing zero-dimensional tensor in future. :)

**Comment by IcarusWizard** [comment]
Hi, @joey12300. I am also very interested in intergrade `paddle` to `einops`. `paddle.zeros([]).transpose([])` seems fixed in `paddlepaddle==2.2.0`, but `paddle.zeros([]).reshape([])` still get error:

```
ValueError: (InvalidArgument) The parameter 'shape' in ReshapeOp must be set. But received 'shape' is empty.
  [Hint: Expected !shape.empty() == true, but received !shape.empty():0 != true:1.] (at /paddle/paddle/fluid/operators/reshape_op.cc:135)
  [operator < reshape2 > error]
```

**Comment by luotao1** [comment]
@IcarusWizard 
> I am also very interested in intergrade paddle to einops.

Thanks very much for your interest. We try to intergrade `paddle` to `einops` in https://github.com/arogozhnikov/einops/pull/122 by @jm12138 before, but since paddle doesn't support zero-dimensional tensor, this PR could not pass the `einops` CI.

@zhouwei25 is doing zero-dimensional tensor related work now. Since it may cause incompatibility, related work is still under discussion and pending review. https://github.com/PaddlePaddle/Paddle/issues/45627#issuecomment-1233687559

**Comment by zhwesky2010** [comment]
@arogozhnikov Thanks for asking questions. Plan 0D tensor has passed the Internal review and is under development. We will support `transpose` and `reshape` 0D  before 2022/10/20

**Comment by zhwesky2010** [comment]
@arogozhnikov Thanks, Are you interested in supporting paddle as the backend for einops, we have fixed the prolem mentioned above in https://github.com/PaddlePaddle/Paddle/pull/46555 . And are there any other problem?
