### ISSUE TITLE
TensorRT+多batch+非对称分辨率下的推断问题

### ISSUE THREAD

**Issue by TimZhang001** [PaddlePaddle/Paddle#34244]
我这边在测试的时候发现一个问题，针对TensorRT版本的infer，在输入网络尺寸宽度不等于高度的时候，存在一些问题
1. 不开启TenorRT ，多batch下一切正常
2. 开启TensorRT，提示长度和宽度设置错误。按照提示进行宽度高度互换，所有的推断结果异常

![image](https://user-images.githubusercontent.com/7878012/126159627-eed0315e-eeee-4e94-8db6-b7a77b8247c2.png)

**Comment by shangzhizhou** [comment]
1.使用TensorRT推理需要实际推理输入的shape和模型结构定义时使用的输入shape一致（可视化看到的模型输入shape）。
2.如果需要改变输入shape，可以使用config.SetTRTDynamicShapeInfo设置动态shape, api参考 https://paddleinference.paddlepaddle.org.cn/api_reference/cxx_api_doc/Config/GPUConfig.html#tensorrt
3.实际使用示例可参考https://github.com/PaddlePaddle/Paddle-Inference-Demo/blob/release/v2.1/c%2B%2B/ernie-varlen/ernie_varlen_test.cc#L37

**Comment by TimZhang001** [comment]
> 1.使用TensorRT推理需要实际推理输入的shape和模型结构定义时使用的输入shape一致（可视化看到的模型输入shape）。
> 2.如果需要改变输入shape，可以使用config.SetTRTDynamicShapeInfo设置动态shape, api参考 https://paddleinference.paddlepaddle.org.cn/api_reference/cxx_api_doc/Config/GPUConfig.html#tensorrt
> 3.实际使用示例可参考https://github.com/PaddlePaddle/Paddle-Inference-Demo/blob/release/v2.1/c%2B%2B/ernie-varlen/ernie_varlen_test.cc#L37

你好，我这边有确认的，网络的设置的时候就是1*78*110的，shape是一致的。我这边用summary也确认了的。我这边测试了宽度=高度的情况，是没有问题的，但是宽度~=高度的时候存在问题，但是我这边由于应用不希望增加resize的时间

**Comment by shangzhizhou** [comment]
> 你好，我这边有确认的，网络的设置的时候就是1_78_110的，shape是一致的。我这边用summary也确认了的。我这边测试了宽度=高度的情况，是没有问题的，但是宽度~=高度的时候存在问题，但是我这边由于应用不希望增加resize的时间

从报错日志看，网络定义是1 x 78 x 110，但是您推理输入的shape是1 x 110 x 78，请检查输入数据是否正常
如果输入shape不对，除了改shape，数据的排布也需要做对应的改动

**Comment by TimZhang001** [comment]
<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:dt="uuid:C2F41010-65B3-11d1-A29F-00AA00C14882"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=OneNote.File>
<meta name=Generator content="Microsoft OneNote 15">
</head>

<body lang=zh-CN style='font-family:Calibri;font-size:11.0pt'>


<p style='margin:0in;font-family:"Microsoft YaHei";font-size:11.0pt'>实例程序：</p>

<img src="file:///C:/Users/zhangss/AppData/Local/Temp/msohtmlclip1/01/clip_image001.png"
width=728 height=167>

<p style='margin:0in;font-family:"Microsoft YaHei";font-size:11.0pt'>&nbsp;</p>

<p style='margin:0in;font-family:Calibri;font-size:11.0pt'>&nbsp;</p>

<p style='margin:0in;font-family:Calibri;font-size:11.0pt'>&nbsp;</p>

<p style='margin:0in;font-family:"Microsoft YaHei";font-size:11.0pt'><span
lang=zh-CN>开启</span><span lang=en-US>TensorRT</span></p>

<div style='direction:ltr'>



输入参数 | 输出结果 |   |   |  
-- | -- | -- | -- | --
  |   |   |   |  
  |   |   |   |  
输入参数 |   |   |   |  
  |   |   |   |  
  |   |   |   |  



</div>


</body>

</html>
