### ISSUE TITLE
conv_operator CPU support

### ISSUE THREAD

**Issue by yu239** [PaddlePaddle/Paddle#3424]
Is there any possibility of supporting conv_operator on CPU? Currently, the constructor of ConvBaseOperator always CHECK(useGpu).

**Comment by wangkuiyi** [comment]
It seems from Git blame that this layer was contributed by @wangyang59 , who might be the best one to give suggestions on the CPU-version of this layer.

**Comment by wangkuiyi** [comment]
@wangyang59 told me that the code was separated from ConvOperator.cpp as shown in above history.  The history of ConvOperator.cpp shows that it was created before the open source of PaddlePaddle -- which means we cannot trace the original author.

I noticed that @luotao1 had made many changes to ConvOperator.cpp.  Could @luotao1 please have to look at this issue and see if we can add CPU-version of this layer? Thanks!

**Comment by qingqing01** [comment]
The `ConvOperator` used the `cuDNN` to calculate, so it only supports GPU now. We can support CPU later. @yu239

**Comment by yu239** [comment]
@qingqing01 Do you have an estimate on when the CPU support will be implemented?

**Comment by luotao1** [comment]
ConvOperator supports CPU in fluid now.
