### ISSUE TITLE
Remove OperatorBase::Init

### ISSUE THREAD

**Issue by wangkuiyi** [PaddlePaddle/Paddle#3425]
OperatorBase::Init duplicates with the C++ constructor mechanism. We should remove it.

It seems that people wrote this duplicated mechanism because the constructor of OperatorBase is over-simplified to take no parameters, and OpRegistry::CreateOp would new an operator instance and set OperatorBase::<properties> directly -- the core problem is that OperatorBase's properties are declared `public` instead of `protected`.

So, to fix this issue we need to

1. Make OperatorBase's properties `protected`

so that we need to

1. Add property accessors to OpeatorBase https://github.com/PaddlePaddle/Paddle/issues/3426
1. Make OperatorBase and all its sub-classes' constructors able to set property values. https://github.com/PaddlePaddle/Paddle/issues/3429
1. Make grad_op_builder.cc reads from OperatorBase::<property> via the accessors https://github.com/PaddlePaddle/Paddle/issues/3427
1. Make op_registry.{h,cc} call new constructor of OperatorBase. https://github.com/PaddlePaddle/Paddle/issues/3438
1. Make all writes to OperatorBase::<property> through constructors.
1. Remove set OperatorBase properties directly.
1. Make properties protected. https://github.com/PaddlePaddle/Paddle/pull/3460

**Comment by reyoung** [comment]
Done
