### ISSUE TITLE
升级paddle 2.0版本后报错 Cuda error(9)

### ISSUE THREAD

**Issue by quyingqi** [PaddlePaddle/Paddle#34250]
1）PaddlePaddle版本：2.0.0 / 2.1.0
2）GPU：V100、CUDA 10.1，显存32g
3）系统环境：paddlecloud V100集群，默认环境

训练信息：单机多卡，代码中使用了fleet、recompute、amp
问题描述：基于ERNIE2.0代码训练双塔模型（静态图），在同样的代码下和环境下，使用paddle1.8 batch size可以开到256，使用paddle2.0+后同样的batch size会报错（Cuda error(9)，如下图），batch size降至128才能正常运行（观察运行时显存占用约16g）。
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/6824077/126169830-15efffa8-56cf-4582-abc5-47392991a077.png">

**Comment by wawltor** [comment]
您好，看结果是显存溢出了。在2.0的时候我们对很多op操作进行了加速操作，部分Op的显存占用有升高，因此出现了这个问题。

**Comment by FeixLiu** [comment]
2.0升级后recompute的config关键字有变化，参考[link](https://www.paddlepaddle.org.cn/documentation/docs/zh/faq/distributed_cn.html#distributedstrategy)

**Comment by FeixLiu** [comment]
设置export FLAGS_allocator_strategy=auto_growth试一下？
