### ISSUE TITLE
nn.NLLLoss使用报错信息看不懂

### ISSUE THREAD

**Issue by btobab** [PaddlePaddle/Paddle#34253]
paddle版本：2.1.1
环境：mac11.4 本地CPU
![本地代码](https://user-images.githubusercontent.com/66876429/126174373-ce99eef2-7d8f-4cf1-a98b-5bc467df0a54.png)
![image](https://user-images.githubusercontent.com/66876429/126174277-7407dfbd-755e-4ce7-99cc-ffc4ee7f422e.png)

**Comment by wawltor** [comment]
这里的意思是说label的范围应该小于class的数目，所以报错。不过看报错确实不太清晰，我反馈一下。

**Comment by btobab** [comment]
好哒好哒，谢谢大佬
