### ISSUE TITLE
使用pip和conda安装paddle2.1版本报错，报错信息如下：

### ISSUE THREAD

**Issue by Fly-hub** [PaddlePaddle/Paddle#34268]
W0720 15:10:57.600003 10080 device_context.cc:404] Please NOTE: device: 0, GPU Compute Capability: 5.0, Driver API Version: 11.3, Runtime API Version: 10.2
W0720 15:10:57.650135 10080 dynamic_loader.cc:238] Note: [Recommend] copy cudnn into CUDA installation directory. 
 For instance, download cudnn-10.0-windows10-x64-v7.6.5.32.zip from NVIDIA's official website, 
then, unzip it and copy it into C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.0
You should do this according to your CUDA installation directory and CUDNN version.
Traceback (most recent call last):
  File "E:/workspace/source/fuxi/source/nlp/ernie/1.0/ernie-1.0.py", line 2, in <module>
    paddle.utils.run_check()
  File "E:\workspace\source\fuxi\venv\lib\site-packages\paddle\utils\install_check.py", line 196, in run_check
    _run_static_single(use_cuda)
  File "E:\workspace\source\fuxi\venv\lib\site-packages\paddle\utils\install_check.py", line 124, in _run_static_single
    exe.run(startup_prog)
  File "E:\workspace\source\fuxi\venv\lib\site-packages\paddle\fluid\executor.py", line 1110, in run
    six.reraise(*sys.exc_info())
  File "E:\workspace\source\fuxi\venv\lib\site-packages\six.py", line 719, in reraise
    raise value
  File "E:\workspace\source\fuxi\venv\lib\site-packages\paddle\fluid\executor.py", line 1098, in run
    return self._run_impl(
  File "E:\workspace\source\fuxi\venv\lib\site-packages\paddle\fluid\executor.py", line 1231, in _run_impl
    return self._run_program(
  File "E:\workspace\source\fuxi\venv\lib\site-packages\paddle\fluid\executor.py", line 1328, in _run_program
    self._default_executor.run(program.desc, scope, 0, True, True,
RuntimeError: (PreconditionNotMet) The third-party dynamic library (cudnn64_7.dll) that Paddle depends on is not configured correctly. (error code is 126)
  Suggestions:
  1. Check if the third-party dynamic library (e.g. CUDA, CUDNN) is installed correctly and its version is matched with paddlepaddle you installed.
  2. Configure third-party dynamic library environment variables as follows:
  - Linux: set LD_LIBRARY_PATH by `export LD_LIBRARY_PATH=...`
  - Windows: set PATH by `set PATH=XXX; (at C:\home\workspace\Paddle_release3\paddle\fluid\platform\dynload\dynamic_loader.cc:265)

Process finished with exit code 1

cuda和cudnn都安装了，还是报错，系统环境是win10，cuda10、11都试过了，还是不行。

**Comment by gongweibao** [comment]
`cudnn64_7.dll`这个文件所在的路径在不在PATH中？

**Comment by xiao9284** [comment]
> `cudnn64_7.dll`这个文件所在的路径在不在PATH中？

配置了依旧不行

**Comment by xiao9284** [comment]
由于我的工作特殊性，数据不能出现在网上，我必须使用win10单机版。。所以必须得在内网中搭建环境。这边我显卡用了个GTX 850M ，驱动用的466版本，cuda11+cudnn11 和cuda10.2+cudnn10.2都组合过了，VS也两个版本都安过了，使用pip下载了11.0和10.2的paddle都试过，报错都是爆同样的错。实在不知道怎么搞了
![1](https://user-images.githubusercontent.com/23395456/126297744-dcb3feaf-2dea-4ea6-8bd8-bdaf55ca40ca.png)
![2](https://user-images.githubusercontent.com/23395456/126297757-688e95d0-b0fc-4125-8f96-8b0b4199b754.png)
![3](https://user-images.githubusercontent.com/23395456/126297761-1bfd974f-e280-42ba-84c6-86196dc28c3a.png)
![4](https://user-images.githubusercontent.com/23395456/126297764-8a15613a-ab7a-4f20-8968-a7d20bca94a7.png)
![5](https://user-images.githubusercontent.com/23395456/126297771-6b05ec60-85b0-454e-829f-d458b35c038c.png)

>

**Comment by xiao9284** [comment]
由于我的工作特殊性，数据不能出现在网上，我必须使用win10单机版，python3.8.8。。所以必须得在内网中搭建环境。这边我显卡用了个GTX 850M ，驱动用的466版本，cuda11+cudnn11 和cuda10.2+cudnn10.2都组合过了，VS也两个版本都安过了，使用pip下载了11.0和10.2的paddle都试过，报错都是报同样的错。实在不知道怎么搞了
![1](https://user-images.githubusercontent.com/23395456/126298651-d1ae270c-1b20-42e4-bc6e-5675aba06081.png)
![2](https://user-images.githubusercontent.com/23395456/126298652-0d790fcd-74b8-4e2b-8e9b-2b207590216e.png)
![3](https://user-images.githubusercontent.com/23395456/126298662-49201def-358f-4bfc-9713-962a37193069.png)
![3](https://user-images.githubusercontent.com/23395456/126298666-55b4cf32-9050-400a-b0f6-4b2c9742d78d.png)
![4](https://user-images.githubusercontent.com/23395456/126298667-a3919fa7-26d2-4aaf-a7ac-8bed3932e5aa.png)
![4](https://user-images.githubusercontent.com/23395456/126298671-356382e8-dad8-4d1a-a67f-997721b4d3f7.png)
![5](https://user-images.githubusercontent.com/23395456/126298672-6c6cb67a-d45b-4196-9288-a5cac467f526.png)
![5](https://user-images.githubusercontent.com/23395456/126298673-e99a0829-d946-405f-8975-ba140d645a8f.png)
![6](https://user-images.githubusercontent.com/23395456/126298675-b245b2fd-9db2-48a3-9c60-157098197e16.png)
![6](https://user-images.githubusercontent.com/23395456/126298680-631d0a39-a366-44dd-9eed-33d0980c37a4.png)
![7](https://user-images.githubusercontent.com/23395456/126298682-1ee7321d-3770-46b6-aebc-d53aa94b80c7.png)
![7](https://user-images.githubusercontent.com/23395456/126298685-0875b4af-557a-42d6-8516-ace5ec8a4eed.png)
![8](https://user-images.githubusercontent.com/23395456/126298686-03bb2c4f-6e03-4065-a4d6-9302c98d3f17.png)
![8](https://user-images.githubusercontent.com/23395456/126298687-71684643-1fec-4578-bb08-0f0f923e9197.png)

**Comment by xiao9284** [comment]
由于我的工作特殊性，数据不能出现在网上，我必须使用win10单机版，python3.8.8。。所以必须得在内网中搭建环境。这边我显卡用了个GTX 850M ，驱动用的466版本，cuda11+cudnn11 和cuda10.2+cudnn10.2都组合过了，VS也两个版本都安过了，使用pip下载了11.0和10.2的paddle都试过，报错都是报同样的错。实在不知道怎么搞了
![1](https://user-images.githubusercontent.com/23395456/126298883-7ee7e219-c3f5-4a5e-b44b-e5521140c862.png)
![2](https://user-images.githubusercontent.com/23395456/126298886-92238741-42fe-479a-ae22-8fcf55580f1e.png)
![3](https://user-images.githubusercontent.com/23395456/126298890-44416fbd-3680-4bdb-9a60-86fbbdf47db7.png)
![4](https://user-images.githubusercontent.com/23395456/126298895-cf1183e0-aa13-4c99-ab32-c414126c4bb8.png)
![5](https://user-images.githubusercontent.com/23395456/126298900-1eac4cf9-af7b-4983-a22f-cb4315981acc.png)
![6](https://user-images.githubusercontent.com/23395456/126298904-ea168dc1-01f5-4786-a3e7-27bfd840cbc2.png)
![7](https://user-images.githubusercontent.com/23395456/126298909-85ee765d-2e8a-40f7-af3a-c23ec20fcc82.png)
![8](https://user-images.githubusercontent.com/23395456/126298914-080be63e-21e0-46eb-95d4-60bb18ac6bef.png)

**Comment by zhwesky2010** [comment]
@Fly-hub 你好，cudnn安装有些问题，需要解压后是把三个子文件夹直接拷贝到v10.2下面，这里拷贝多了一层v10.2/cuda，所以没有加载到动态库。麻烦重装下cudnn

**Comment by Fly-hub** [comment]
> @Fly-hub 你好，cudnn安装有些问题，需要解压后是把三个子文件夹直接拷贝到v10.2下面，这里拷贝多了一层v10.2/cuda，所以没有加载到动态库。麻烦重装下cudnn

确实是这个问题，重装cudnn去掉多的那层文件夹就可以了。

**Comment by xiao9284** [comment]
您好，谢谢您的答疑，我这边按照您的方法重装了cudnn，问题已经解决了，非常感谢您的帮助




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/Paddle"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年7月20日(星期二) 晚上6:31
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PaddlePaddle/Paddle] 使用pip和conda安装paddle2.1版本报错，报错信息如下： (#34268)





  
@Fly-hub 你好，cudnn安装有些问题，需要解压后是把三个子文件夹直接拷贝到v10.2下面，这里拷贝多了一层v10.2/cuda，所以没有加载到动态库。麻烦重装下cudnn
  
确实是这个问题，重装cudnn去掉多的那层文件夹就可以了。
