### ISSUE TITLE
windows系统pthon3.8安装不了paddlelite

### ISSUE THREAD

**Issue by lvyaoyu** [PaddlePaddle/Paddle#34291]
ERROR: Could not find a version that satisfies the requirement paddlelite (from versions: none)

**Comment by DannyIsFunny** [comment]
你好、当前Lite 在pip源上发布的库 支持 python版本为2.7 \3.5\3.6\3.7

我们 将尽快提供一个 3.8 installer

**Comment by DannyIsFunny** [comment]
你好，我们提供了以3.8版本的离线安装包：
[下载链接](https://bj.bcebos.com/v1/xly-paddle-whl-online/d7653424-ab8a-4260-809c-374f1f18d322/paddlelite-2.9-cp38-cp38-win_amd64.whl?authorization=bce-auth-v1%2F8ee0f5987f634992a1cb9257ff1c8413%2F2021-07-23T12%3A27%3A41Z%2F3600%2F%2F1b81b8686814877c9cf0a33ac0c8c671545cdbd7aba535c8ed0693cf93545da1)
