### ISSUE TITLE
Dropout has no gradient in eval mode

### ISSUE THREAD

**Issue by holyseven** [PaddlePaddle/Paddle#34293]
为使您的问题得到快速解决，在建立Issue前，请您先通过如下方式搜索是否有相似问题:【搜索issue关键字】【使用labels筛选】【官方文档】

建立issue时，为快速解决问题，请您根据使用情况给出如下信息：
- 标题：简洁、精准描述您的问题，例如“ssd 模型前置lstm报错  ”
- 版本、环境信息：
    1）PaddlePaddle版本：2.0.1
    2）CPU：请提供CPU型号，MKL/OpenBlas/MKLDNN/等数学库的使用情况
    3）GPU：10.2
    4）系统环境：Ubuntu
 
---

有时在eval模式下也想得到gradient。

好像大部分operations都可以，但是`dropout`不行。以下是一个MWE，可以正常运行。但是加上`y = self.dropout(y)`就会报错：

>ValueError: (InvalidArgument) GradOp is only callable when is_test is false
  [Hint: Expected ctx->Attrs().Get<bool>("is_test") == false, but received ctx->Attrs().Get<bool>("is_test"):1 != false:0.] (at >/paddle/paddle/fluid/operators/dropout_op.cc:122)

```python

import paddle
import paddle.nn as nn
import numpy as np

class CustomModle(nn.Layer):
    def __init__(self):
        super(CustomModle, self).__init__()

        self.flatten = paddle.nn.Flatten()
        self.linear_1 = paddle.nn.Linear(784, 512)
        self.bn1 = nn.BatchNorm1D(512)
        self.linear_2 = paddle.nn.Linear(512, 10)
        self.relu = paddle.nn.ReLU()
        self.dropout = paddle.nn.Dropout(0.2)

    def forward(self, inputs):
        y = self.flatten(inputs)
        y = self.linear_1(y)
        y = self.bn1(y)
        y = self.relu(y)
#         y = self.dropout(y)
        y = self.linear_2(y)

        return y

model_instance = CustomModle()
model_instance.eval()
data = np.random.rand(1, 1, 28, 28).astype(np.float32)
data = paddle.to_tensor(data)
data.stop_gradient = False
logits = model_instance(data)
model_instance.clear_gradients()

logits.backward()
print(data.grad.shape)

```

**Comment by huangjun12** [comment]
paddle 2.1跑示例代码，不开dropout也会报错的，目前不允许eval时跑反向

```txt
ValueError: (InvalidArgument) `is_test = True` CANNOT be used in train program. If you want to use global status in pre_train model, please set `use_global_stats = True`
  [Hint: Expected is_test == false, but received is_test:1 != false:0.] (at /workspace/huangjun12/PaddleProject/Paddle/Paddle.21/paddle/fluid/operators/batch_norm_op.cu:858)
```

**Comment by holyseven** [comment]
这是为什么呢？之后的版本是所有的层eval时都不允许反向吗？`paddle.grad`也是同样的道理吗？

**Comment by huangjun12** [comment]
model.eval主要对网络中的batch norm和dropout层起作用

**Comment by holyseven** [comment]
> 目前不允许eval时跑反向

为什么不允许呢？之后会允许吗？2.0允许bn反向、2.1就不允许了。

> model.eval主要对网络中的batch norm和dropout层起作用

我明白这两个层training和eval的时候是不一样的，但是也是可以在不同模式下计算梯度。除了这俩，其它层允许eval跑反向吗？有些特定的场景下，对模型进行分析的时候，是需要在eval下得到梯度。

**Comment by ceci3** [comment]
最新的paddle的bn已经支持了 eval模式下得到grad，可以安装最新版试下~

**Comment by holyseven** [comment]
棒！测试了一下，发现dropout貌似还是不行。请问之后开发的趋势是尽量都支持eval模式下可以得到grad，还是禁止eval得到grad？

**Comment by ceci3** [comment]
趋势是尽量都支持eval模式下拿到grad～ 现在也只有dropout不支持了，计划应该是2.2dropout会支持



发自我的iPhone


------------------ Original ------------------
From: LI Xuhong ***@***.***&gt;
Date: Thu,Jul 29,2021 1:09 PM
To: PaddlePaddle/Paddle ***@***.***&gt;
Cc: ceci3 ***@***.***&gt;, Comment ***@***.***&gt;
Subject: Re: [PaddlePaddle/Paddle] Dropout has no gradient in eval mode (#34293)





 
棒！测试了一下，发现dropout貌似还是不行。请问之后开发的趋势是尽量都支持eval模式下可以得到grad，还是禁止eval得到grad？

**Comment by holyseven** [comment]
```python
import paddle
print(paddle.__version__)  # 2.2.0-rc0
import paddle.nn as nn
import numpy as np

class CustomModle(nn.Layer):
    def __init__(self):
        super(CustomModle, self).__init__()

        self.flatten = paddle.nn.Flatten()
        self.linear_1 = paddle.nn.Linear(784, 512)
        self.bn1 = nn.BatchNorm1D(512)
        self.linear_2 = paddle.nn.Linear(512, 10)
        self.relu = paddle.nn.ReLU()
        self.dropout = paddle.nn.Dropout(0.2)

    def forward(self, inputs):
        y = self.flatten(inputs)
        y = self.linear_1(y)
        y = self.bn1(y)
        y = self.relu(y)
        y = self.dropout(y)
        y = self.linear_2(y)

        return y

model_instance = CustomModle()
model_instance.eval()
data = np.random.rand(1, 1, 28, 28).astype(np.float32)
data = paddle.to_tensor(data)
data.stop_gradient = False
logits = model_instance(data)
model_instance.clear_gradients()

logits.backward()
print(data.grad.shape)
```

> RuntimeError: (PreconditionNotMet) GradOp is only callable when is_test is false
  [Hint: Expected !context.Attr<bool>("is_test") == true, but received !context.Attr<bool>("is_test"):0 != true:1.] (at /paddle/paddle/fluid/operators/dropout_op.cu:63)

`Dropout` still has no gradients in `2.2.0-rc0`. When will this feature be supported?

**Comment by holyseven** [comment]
This is supported from 2.2.1. Closed.
