### ISSUE TITLE
gather没有修改lod信息

### ISSUE THREAD

**Issue by miraclebiu** [PaddlePaddle/Paddle#34325]
<img width="804" alt="49782386ca6e7b42b36934563a3cb16b" src="https://user-images.githubusercontent.com/16793970/126612641-52bdeb35-bb3a-40cf-a4bc-35652da9db03.png">

我有4张图，原来有378个bbox，通过score进行对bbox进行了过滤，然后gather之后只有130个了，但是lod信息不对，没有对应修改

**Comment by jerrywgz** [comment]
目前gather操作对lod不支持，我这边先记个需求，看后续怎么处理

**Comment by miraclebiu** [comment]
> 目前gather操作对lod不支持，我这边先记个需求，看后续怎么处理

那目前有什么方式能够处理这样的行为？我需要处理lod信息过roi-align

**Comment by jerrywgz** [comment]
这个目前确实还不支持，可以先使用batch_size=1来训练吗
