### ISSUE TITLE
2021年7月23日 VS2019编译错误

### ISSUE THREAD

**Issue by BuLuoPiaoYu** [PaddlePaddle/Paddle#34336]
**VS2019生成解决方案失败，如下图所示错误**

![image](https://user-images.githubusercontent.com/54087448/126734681-1794799f-4d72-4521-98a0-f3999bb36a47.png)
=============================================================================

**以下为CMake编译过程**

=============================================================================
PS D:\Training_Project\PaddleX Source\Paddle\build>  cmake .. -G "Visual Studio 16 2019" -A x64 -DWITH_GPU=OFF -DWITH_TESTING=OFF -DCMAKE_BUILD_TYPE=Release -DPYTHON_EXECUTABLE="C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\python.exe"
-- Found Paddle host system: win32, version:
-- Found Paddle host system's CPU: 8 cores
-- Selecting Windows SDK version 10.0.19041.0 to target Windows 10.0.22000.
-- The CXX compiler identification is MSVC 19.29.30040.0
-- The C compiler identification is MSVC 19.29.30040.0
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.29.30037/bin/Hostx64/x64/cl.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.29.30037/bin/Hostx64/x64/cl.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.29.30037/bin/Hostx64/x64/cl.exe, version: MSVC 19.29.30040.0
-- C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.29.30037/bin/Hostx64/x64/cl.exe, version: MSVC 19.29.30040.0
-- AR tools: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.29.30037/bin/Hostx64/x64/lib.exe
-- Use static C runtime time, refer to https://docs.microsoft.com/en-us/cpp/c-runtime-library/crt-library-features?view=vs-2019
-- Found Git: C:/Program Files/Git/cmd/git.exe (found version "2.32.0.windows.2")
-- Looking for pthread.h
-- Looking for pthread.h - not found
-- Found Threads: TRUE
-- Performing Test MMX_FOUND
-- Performing Test MMX_FOUND - Failed
-- Performing Test SSE2_FOUND
-- Performing Test SSE2_FOUND - Success
-- Performing Test SSE3_FOUND
-- Performing Test SSE3_FOUND - Success
-- Performing Test AVX_FOUND
-- Performing Test AVX_FOUND - Success
-- Performing Test AVX2_FOUND
-- Performing Test AVX2_FOUND - Success
-- Performing Test AVX512F_FOUND
-- Performing Test AVX512F_FOUND - Success
CMake Warning at CMakeLists.txt:247 (MESSAGE):
  Disable NCCL when compiling for Windows.  Force WITH_NCCL=OFF.

CMake Warning at CMakeLists.txt:302 (MESSAGE):
  Disable RCCL when compiling without ROCM.  Force WITH_RCCL=OFF.

-- Disable XBYAK in Windows and MacOS
-- Looking for C++ include shlwapi.h
-- Looking for C++ include shlwapi.h - found
-- BOOST_VERSION: 1.41.0, BOOST_URL: http://paddlepaddledeps.bj.bcebos.com/boost_1_41_0.tar.gz
-- warp-ctc library: D:/Training_Project/PaddleX Source/Paddle/build/third_party/install/warpctc/bin/warpctc.dll
-- MKLML_VER: mklml_win_2019.0.5.20190502, MKLML_URL: https://paddlepaddledeps.bj.bcebos.com/mklml_win_2019.0.5.20190502.zip
-- Found cblas and lapack in MKLML (include: D:/Training_Project/PaddleX Source/Paddle/build/third_party/install/mklml/include, library: D:/Training_Project/PaddleX Source/Paddle/build/third_party/install/mklml/lib/mklml.lib)
-- CBLAS_PROVIDER: MKLML
-- Set D:/Training_Project/PaddleX Source/Paddle/build/third_party/install/mkldnn/lib to runtime path
-- MKLDNN library: D:/Training_Project/PaddleX Source/Paddle/build/third_party/install/mkldnn/bin/mkldnn.lib
-- Protobuf protoc executable: D:/Training_Project/PaddleX Source/Paddle/build/third_party/install/protobuf/bin/protoc.exe
-- Protobuf-lite library: D:/Training_Project/PaddleX Source/Paddle/build/third_party/install/protobuf/lib/libprotobuf-lite.lib
-- Protobuf library: D:/Training_Project/PaddleX Source/Paddle/build/third_party/install/protobuf/lib/libprotobuf.lib
-- Protoc library: D:/Training_Project/PaddleX Source/Paddle/build/third_party/install/protobuf/lib/libprotoc.lib
-- Protobuf version: 3.1.0
-- Found PythonInterp: C:/Program Files (x86)/Microsoft Visual Studio/Shared/Python37_64/python.exe (found suitable version "3.7.8", minimum required is "3.6")
-- Found PythonLibs: C:/Program Files (x86)/Microsoft Visual Studio/Shared/Python37_64/libs/python37.lib (found suitable version "3.7.8", minimum required is "3.6")
-- Found PY_pip: C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\site-packages\pip\__init__.py
-- Found PY_numpy: C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\site-packages\numpy\__init__.py

-- Found PY_wheel: C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\site-packages\wheel\__init__.py

-- Found PY_google.protobuf: C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\site-packages\google\protobuf\__init__.py
CMake Deprecation Warning at cmake/FindNumPy.cmake:6 (cmake_minimum_required):
  Compatibility with CMake < 2.8.12 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.
Call Stack (most recent call first):
  cmake/external/python.cmake:72 (FIND_PACKAGE)
  cmake/third_party.cmake:238 (include)
  CMakeLists.txt:328 (include)

-- Found NumPy: C:/Program Files (x86)/Microsoft Visual Studio/Shared/Python37_64/Lib/site-packages/numpy/core/include
-- Looking for UINT64_MAX
-- Looking for UINT64_MAX - found
-- Looking for sys/types.h
-- Looking for sys/types.h - found
-- Looking for stdint.h
-- Looking for stdint.h - found
-- Looking for stddef.h
-- Looking for stddef.h - found
-- Check size of pthread_spinlock_t
-- Check size of pthread_spinlock_t - failed
-- Check size of pthread_barrier_t
-- Check size of pthread_barrier_t - failed
-- Paddle version is 0.0.0
-- Enable Intel OpenMP with D:/Training_Project/PaddleX Source/Paddle/build/third_party/install/mklml/lib/libiomp5md.lib
CMake Warning at CMakeLists.txt:392 (message):
  On inference mode, will take place some specific optimization.  Turn on the
  ON_INFER flag when building inference_lib only.

-- commit: 781f402825
-- branch: develop
WITH_DLNNE:
-- MESSAGE: This is just a message for publishing release.
      You are building AVX version without NOAVX core.
      So the wheel package may fail on NOAVX machine.
      You can add -DNOAVX_CORE_FILE=/path/to/your/core_noavx.* in cmake command
      to get a full wheel package to resolve this warning.
      While, this version will still work on local machine.
-- Configuring done
-- Generating done
-- Build files have been written to: D:/Training_Project/PaddleX Source/Paddle/build
==================================================================================

**Comment by ceci3** [comment]
You can add -DNOAVX_CORE_FILE=/path/to/your/core_noavx.*  请问下试了这个指令了嘛？
