### ISSUE TITLE
PaddleDetection剪枝前的敏感度分析

### ISSUE THREAD

**Issue by zmdcs** [PaddlePaddle/Paddle#34333]
- 模型信息
    1）模型名称
yolo3-mobilev1
 2）使用数据集名称 
fire

如何对自己的模型进行敏感度分析，实例中只有自己随手建立的手写数字识别的模型

**Comment by ceci3** [comment]
https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.1/static/slim/sensitive/README.md 可以参考这个~
