### ISSUE TITLE
关于使用paddle教程和用法的一些疑问、建议和意见

### ISSUE THREAD

**Issue by betterpig** [PaddlePaddle/Paddle#34335]
### 以下文档和运行代码均是基于paddle release/2.1版本
1. 位置：飞桨paddlepaddle.org.cn/文档/使用教程/模型开发/训练与预测/3.2拆解model.evaluate()
评估模型应该是评价模型在测试集上的整体性能，在paddle中是每一个batch数据输出该次数据的损失和精度，感觉挺别扭的，是否有整体算，不需要再自己做平均的方法？
2. 位置：飞桨paddlepaddle.org.cn/教程/零基础/第二章上/3手写数字识别之数据处理/异步数据获取
把一长串dataset都打印出来，占了网页大部分篇幅，影响阅读，建议只列出前几行就行，打个省略号或者说明一下没有全部展示。其他有一大串打印的亦是如此。
3. 建议所有教程中的较长一段的代码都加上行号显示和隐藏功能，代码复制功能
4. 位置：飞桨paddlepaddle.org.cn/ 
教程栏和文档栏中的教程略有重叠
5. 位置：飞桨paddlepaddle.org.cn/教程/零基础/第二章上/3手写数字识别之数据处理
没有给出本地minst数据集的获取方式
6. 位置：git   PaddlePaddle/PaddleOCR/doc/doc_ch/recognition.md
 ocr_recognition教程中数据集需要在官网注册后下载，如果复制下载链接在开发机下载，会提示无法通过安全认证
7. 位置：git   PaddlePaddle/PaddleOCR/doc/doc_ch/datasets.md
数据集不方便下载，都是给个官网，复制到Linux下载只是下载到网页，对新人很不友好，最好给个下载链接后者直接提供Linux下下载命令。
8. 位置：git   PaddlePaddle/PaddleOCR/模型训练和评估/文本识别
Icdar2015数据下载后，训练集的文件名和存放路径按教程设置的话会报错，与代码的默认设置不一致。
根据报错信息，两个标签文件应该叫做train_list.txt和val_list.txt。并且要把它们放在train_data下。而训练集名称要分别改称train和test，根据标签文件中图片的路径。

**Comment by TCChenlong** [comment]
1、整体算可以看同文档中的2.3部分，直接用model.evaluate()就是整体算；
2、收到，我们优化一下这部分的输出；
3、收到，我们评估一下这个需求；
4、我们正在考虑优化文档部分的内容；
5、收到，我们补充一下文档的内容
感谢您的反馈，6-8的内容会有其他的同学来进行回复~

**Comment by Evezerest** [comment]
8.由于数据来源比较多，配置文件中的‘train_list.txt’是一个示例名，需要用户手动修改名称，我们稍后会对文档进行补充。

**Comment by betterpig** [comment]
> 1、整体算可以看同文档中的2.3部分，直接用model.evaluate()就是整体算；
> 2、收到，我们优化一下这部分的输出；
> 3、收到，我们评估一下这个需求；
> 4、我们正在考虑优化文档部分的内容；
> 5、收到，我们补充一下文档的内容
> 感谢您的反馈，6-8的内容会有其他的同学来进行回复~

nice

**Comment by betterpig** [comment]
> 8.由于数据来源比较多，配置文件中的‘train_list.txt’是一个示例名，需要用户手动修改名称，我们稍后会对文档进行补充。

好的
