### ISSUE TITLE
删除这个贼没用的warning

### ISSUE THREAD

**Issue by Stave604671** [PaddlePaddle/Paddle#34331]
D:\Anaconda\envs\book-develop\Lib\site-packages\paddle\fluid\dataloader\dataloader_iter.py
AIStudio跑的
paddle2.1的这个库，第198行，这个warning删了吧，啥用也没有净占控制台地方，影响孩子debug了。要么解释清楚错误在哪儿，要么别解释。筛了半天才发现数据集里面的某张图片有问题。下次遇上这个问题要不代替我们解决一下，把问题图片删了？

**Comment by jerrywgz** [comment]
这个warning目前已经在最新的develop版本中去除了，后续发布的paddle版本中将不会再出现
