### ISSUE TITLE
下载paddleslim成功但文件列表中没有显示slim文件夹

### ISSUE THREAD

**Issue by zmdcs** [PaddlePaddle/Paddle#34361]
下载paddleslim成功但文件列表中没有显示slim文件夹，并且使用paddleDetection中的PaddleDetection/static/slim/sensitive/sensitive.py这个分析敏感度的文件时，报错ImportError: cannot import name 'create_reader' from 'ppdet.data.reader' 该如何解决呢？

**Comment by heavengate** [comment]
> 下载paddleslim成功但文件列表中没有显示slim文件夹，并且使用paddleDetection中的PaddleDetection/static/slim/sensitive/sensitive.py这个分析敏感度的文件时，报错ImportError: cannot import name 'create_reader' from 'ppdet.data.reader' 该如何解决呢？

你好，下载paddleslim的话文件夹名称是PaddleSlim，另外如果你使用PaddleDetection静态图代码的话需要`cd static`到静态图里运行

**Comment by zeromasterfire** [comment]
你好，我也遇到了 'create_reader' from 'ppdet.data.reader'  的错误，我已经cd到static运行了还是没用

**Comment by zeromasterfire** [comment]
> 你好，我也遇到了 'create_reader' from 'ppdet.data.reader' 的错误，我已经cd到static运行了还是没用，请问你们是怎么解决的
