### ISSUE TITLE
飞桨平台个人信息编辑，有个错别字

### ISSUE THREAD

**Issue by zhl1bug** [PaddlePaddle/Paddle#34364]
欢迎您对PaddlePaddle提出建议，非常感谢您对PaddlePaddle的贡献！

飞桨平台个人信息编辑，有个错别字如下帖子，
AI studio 首席技术馆cto 字打错问题反馈
https://aistudio.baidu.com/paddle/forum/topic/show/989460

**Comment by heavengate** [comment]
收到，感谢反馈，我们修复一下~
