### ISSUE TITLE
centos 预测库编译出错

### ISSUE THREAD

**Issue by jinchen-chuyang** [PaddlePaddle/Paddle#34363]
为使您的问题得到快速解决，在建立Issue前，请您先通过如下方式搜索是否有相似问题:【搜索issue关键字】【使用labels筛选】【官方文档】

建立issue时，为快速解决问题，请您根据使用情况给出如下信息：
- 标题：请包含关键词“安装错误”/“编译错误”，例如“Mac编译错误”
- 版本、环境信息：
    1）PaddlePaddle版本：请提供您的PaddlePaddle版本号（如1.1）或CommitID
    2）CPU：请提供CPU型号，MKL/OpenBlas/MKLDNN/等数学库的使用情况
    3）GPU：请提供GPU型号，CUDA和CUDNN版本号
    4）系统环境：请说明系统类型、版本（如Mac OS 10.14）、Python版本
注：您可以通过执行[summary_env.py](https://github.com/PaddlePaddle/Paddle/blob/develop/tools/summary_env.py)获取以上信息。
- 安装方式信息：
1）pip安装/docker安装
2）本地编译：请提供cmake命令，编译命令
3）docker编译：请提供docker镜像，编译命令            
  特殊环境请注明：如离线安装等
- 复现信息：如为报错，请给出复现环境、复现步骤
- 问题描述：请详细描述您的问题，同步贴出报错信息、日志/代码关键片段

Thank you for contributing to PaddlePaddle.
Before submitting the issue, you could search issue in Github in case that there was a similar issue submitted or resolved before.
If there is no solution,please make sure that this is an installation issue including the following details:
**System information**
-PaddlePaddle version （eg.1.1）or CommitID
-CPU: including CPUMKL/OpenBlas/MKLDNN version
-GPU: including CUDA/CUDNN version
-OS Platform (eg. Mac OS 10.14)
-Python version
- Install method: pip install/install with docker/build from source(without docker)/build within docker
- Other special cases that you think may be related to this problem, eg. offline install, special internet condition 
Note: You can get most of the information by running [summary_env.py](https://github.com/PaddlePaddle/Paddle/blob/develop/tools/summary_env.py).   

**To Reproduce**
Steps to reproduce the behavior
**Describe your current behavior**
**Code to reproduce the issue**
**Other info / logs**

**Comment by jinchen-chuyang** [comment]
[root@hecs-x-large-2-linux-20210723100922 cpp_infer]# lscpu
Architecture:        x86_64
CPU op-mode(s):      32-bit, 64-bit
Byte Order:          Little Endian
CPU(s):              2
On-line CPU(s) list: 0,1
Thread(s) per core:  2
Core(s) per socket:  1
Socket(s):           1
NUMA node(s):        1
Vendor ID:           GenuineIntel
BIOS Vendor ID:      QEMU
CPU family:          6
Model:               85
Model name:          Intel(R) Xeon(R) Gold 6278C CPU @ 2.60GHz
BIOS Model name:     pc-i440fx-2.8
Stepping:            7
CPU MHz:             2600.000
BogoMIPS:            5200.00
Hypervisor vendor:   KVM
Virtualization type: full
L1d cache:           32K
L1i cache:           32K
L2 cache:            1024K
L3 cache:            36608K
NUMA node0 CPU(s):   0,1

[root@hecs-x-large-2-linux-20210723100922 cpp_infer]# gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/opt/rh/gcc-toolset-10/root/usr/libexec/gcc/x86_64-redhat-linux/10/lto-wrapper
Target: x86_64-redhat-linux
Configured with: ../configure --enable-bootstrap --enable-languages=c,c++,fortran,lto --prefix=/opt/rh/gcc-toolset-10/root/usr --mandir=/opt/rh/gcc-toolset-10/root/usr/share/man --infodir=/opt/rh/gcc-toolset-10/root/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-shared --enable-threads=posix --enable-checking=release --enable-multilib --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-linker-build-id --with-gcc-major-version-only --with-linker-hash-style=gnu --enable-plugin --enable-initfini-array --with-isl=/builddir/build/BUILD/gcc-10.2.1-20201112/obj-x86_64-redhat-linux/isl-install --disable-libmpx --enable-gnu-indirect-function --with-tune=generic --with-arch_32=x86-64 --build=x86_64-redhat-linux
Thread model: posix
Supported LTO compression algorithms: zlib zstd
gcc version 10.2.1 20201112 (Red Hat 10.2.1-8) (GCC) 

opencv
3.4.8

**Comment by jinchen-chuyang** [comment]
[root@hecs-x-large-2-linux-20210723100922 cpp_infer]# ll
total 64
drwxr-xr-x 3 root root 4096 Jul 24 16:46 __build
-rwxr-xr-x 1 root root  444 Jul 24 16:46 build.sh
-rw-r--r-- 1 root root 8708 Jul 24 16:33 CMakeLists.txt
drwxr-xr-x 2 root root 4096 Jul 24 14:05 docs
drwxr-xr-x 2 root root 4096 Jul 24 14:05 imgs
drwxr-xr-x 2 root root 4096 Jul 24 14:05 include
-rw-r--r-- 1 root root 9243 Jul 24 14:05 readme_en.md
-rw-r--r-- 1 root root 8316 Jul 24 15:42 readme.md
drwxr-xr-x 2 root root 4096 Jul 24 14:05 src
drwxr-xr-x 3 root root 4096 Jul 24 15:40 tools
[root@hecs-x-large-2-linux-20210723100922 cpp_infer]# cat build.sh 
OPENCV_DIR=/usr/local/opencv
LIB_DIR=/root/sft/paddle_inference
CUDA_LIB_DIR=your_cuda_lib_dir
CUDNN_LIB_DIR=your_cudnn_lib_dir

BUILD_DIR=__build
rm -rf ${BUILD_DIR}
mkdir ${BUILD_DIR}
cd ${BUILD_DIR}
cmake .. \
    -DPADDLE_LIB=${LIB_DIR} \
    -DWITH_MKL=ON \
    -DWITH_GPU=OFF \
    -DWITH_STATIC_LIB=OFF \
    -DUSE_TENSORRT=OFF \
    -DOPENCV_DIR=${OPENCV_DIR} \
    -DCUDNN_LIB=${CUDNN_LIB_DIR} \
    -DCUDA_LIB=${CUDA_LIB_DIR} \

make
[root@hecs-x-large-2-linux-20210723100922 cpp_infer]# ./build.sh 
-- The CXX compiler identification is GNU 10.2.1
-- The C compiler identification is GNU 10.2.1
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /opt/rh/gcc-toolset-10/root/usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /opt/rh/gcc-toolset-10/root/usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Found OpenCV: /usr/local/opencv (found version "3.4.8") 
cmake cxx flags -g -o3 -fopenmp -std=c++11
-- Configuring done
-- Generating done
CMake Warning:
  Manually-specified variables were not used by the project:

    USE_TENSORRT


-- Build files have been written to: /root/git/PaddleOCR/deploy/cpp_infer/__build
[ 10%] Building CXX object CMakeFiles/ocr_system.dir/src/clipper.cpp.o
cc1plus: error: too many filenames given; type [01mcc1plus --helpfor usage
cc1plus: fatal error: CMakeFiles/ocr_system.dir/src/clipper.cpp.d: No such file or directory
compilation terminated.
make[2]: *** [CMakeFiles/ocr_system.dir/build.make:76: CMakeFiles/ocr_system.dir/src/clipper.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:83: CMakeFiles/ocr_system.dir/all] Error 2
make: *** [Makefile:91: all] Error 2

**Comment by heavengate** [comment]
你好，看你报错信息使用的是PaddleOCR的预测部署的demo代码，可以到PaddleOCR库里问一下https://github.com/PaddlePaddle/PaddleOCR/issues
