### ISSUE TITLE
PaddleDetection敏感度分析存下来的demo.data文件有什么用？

### ISSUE THREAD

**Issue by zmdcs** [PaddlePaddle/Paddle#34382]
官方文件中说，可以使用python画图，是通过输出的数据，自己一条条取下来，画出剪枝比例和acc loss的关系图吗？还是demo.data中有储存呢？剪枝是剪掉对mAP值影响不大的卷积层，还是所有的卷积层按比例剪呢？许多官方文档中的链接都已经访问不到了，希望你们能恢复，比如sensitive里的那些方法的教程，谢谢。
主要是想问demo.data文件有什么用？

**Comment by heavengate** [comment]
https://paddleslim.readthedocs.io/zh_CN/latest/tutorials/pruning/static/image_classification_sensitivity_analysis_tutorial.html
静态图剪裁的敏感度分析可以参考这个，demo.data主要存储各卷积层不同裁剪率对精度影响的数据，用于分析得出各个卷积层的裁剪率。
PaddleDetection文档网站我们正在修复，可以先参考下`slim`目录下的README  https://github.com/PaddlePaddle/PaddleDetection/tree/release/2.1/static/slim
