### ISSUE TITLE
反传梯度部分消失

### ISSUE THREAD

**Issue by QingquanBao** [PaddlePaddle/Paddle#34419]
Ubuntu 16.04.7
python == 3.7.9
paddle== 2.1.0

Paddle相关代码见 https://github.com/QingquanBao/PCA-GM/blob/thinkmatch/utils_pdl/sinkhorn.py
Torch 版本的对照代码： https://github.com/QingquanBao/PCA-GM/blob/thinkmatch/utils/sinkhorn_new.py

## 算法简介
正在实现的是Sinkhorn算法，简单来说就是对矩阵进行_行归一化_和_列归一化_的处理。
由于原来的模型是在 Graph上跑的，所以每个Batch里会有一些dummy node， 我们在归一化时将 非dummy挑选出来。(在具体例子中没有使用dummy，故而可以忽略本行和相关代码）

## 问题描述
目前也和torch版本的做了对照，前传是对的。但在反传中，仅仅输入变量的最后一个batch的梯度是获得的，其他batch均为$0$，**我想可能问题出在Paddle 的 69-85 行的写法上（对应PyTorch版本里的93-108行）**。另外，反传的结果在本例里也是不同的。（有些例子中能相同，如`main2()`）

### Paddle 输出
运行`utils_pdl/sinkhorn.py`, 得到 反传的梯度是
```
Tensor(shape=[2, 4, 3], dtype=float32, place=CUDAPlace(0), stop_gradient=False,
​    [[[ 0.     , 0.     , 0.     ],

​     [ 0.     , 0.     , 0.     ],

​     [ 0.     , 0.     , 0.     ],

​     [ 0.     , 0.     , 0.     ]],
​    [[-51.75344086, 24.31637573, 27.79878235],

​     [-8.41525173 , 5.74985170 , 4.48717356 ],

​     [ 95.84911346, -46.58929062, -49.17062759],

​     [-35.68041992, 16.52306557, 16.88466835]]])
```
### Torch 输出（期望输出）
运行`utils/sinkhorn_new.py`，得到反传梯度
```
[[[0.17291827, 0.56604785, 0.26103380],

​     [0.06481776, 0.21218100, 0.72300124],

​     [0.36237180, 0.43638751, 0.20124075],

​     [0.73138046, 0.11919893, 0.14942062]],

[[0.17291827, 0.56604785, 0.26103380],

​     [0.06481776, 0.21218100, 0.72300124],

​     [0.36237180, 0.43638751, 0.20124075],

​     [0.73138046, 0.11919893, 0.14942062]]])
```
## 其他
其中 测试代码里 `main2()` and `ori_main()`测试了一些真实数据，但 `simple_main()` 业已能说明问题

**Comment by phlrain** [comment]
经过我们得分析，这种写法 ret_log_s[b, row_slice, col_slice] = log_s，会导致梯度回传中断，这个问题，我们在高优修复中

**Comment by QingquanBao** [comment]
> 经过我们得分析，这种写法 ret_log_s[b, row_slice, col_slice] = log_s，会导致梯度回传中断，这个问题，我们在高优修复中

您好，请问这个bug修复的如何了？ 非常感谢！！
同时请问另一个[bug](https://github.com/PaddlePaddle/Paddle/issues/34633) 是否同时修复了,谢谢 ！
