### ISSUE TITLE
[QA] oneDNN BF16 training Test doc

### ISSUE THREAD

**Issue by lidanqing-vv** [PaddlePaddle/Paddle#34414]
BF16 word2vec training memory consumption test
[paddlerec_bf16_benchmark_reproduction - public.md](https://github.com/PaddlePaddle/Paddle/files/6882981/paddlerec_bf16_benchmark_reproduction.-.public.md)

**Comment by OliverLPH** [comment]
we will start testing this week.

**Comment by yanmeng1019** [comment]
The paddle.fluid.tests function is no longer included in the whl package of paddlepaddle
So the code in https://github.com/PaddlePaddle/PaddleRec/blob/master/tools/static_ps_trainer.py
https://github.com/PaddlePaddle/PaddleRec/blob/master/tools/static_ps_trainer.py#L202
https://github.com/PaddlePaddle/PaddleRec/blob/master/tools/static_ps_trainer.py#L250
will trigger an error:
```shell
ModuleNotFoundError: No module named 'paddle.fluid.tests'
```

**Comment by lidanqing-vv** [comment]
Doc sent by email
