### ISSUE TITLE
When MKLDNN is turned on, frcnn predicts the same picture multiple times, and the prediction results are inconsistent before and after.

### ISSUE THREAD

**Issue by baoachun** [PaddlePaddle/Paddle#34415]
When MKLDNN is turned on, frcnn predicts the same picture multiple times, and the prediction results are inconsistent before and after.
- Version and environmental information:
     1) PaddlePaddle version: 1.8.5
     2) CPU: Intel(R) Xeon(R) Gold 6271C CPU, 6148 CPU
     3) Linux Ubuntu 16.04, Python2.7
- In the same process, after using different pictures to predict for a period of time, the same picture, the prediction results before and after are inconsistent, the first result is correct, and the following is wrong.
- ![图片](https://user-images.githubusercontent.com/22114318/127107308-ca843843-1c03-4ffb-91ef-709db01e13b2.png)
- The code and model are temporarily unavailable due to confidentiality. Personally, after closing the ```mkldnn_placement_pass``` this pass, the prediction result returned to normal.

**Comment by Shixiaowei02** [comment]
您好，请提供更详细的代码环境以便问题复现，谢谢

**Comment by lidanqing-vv** [comment]
Hi, @jczaja Same picture prediction results are different in same run different iteration, maybe something in cache?  I m still asking for models if possible.

**Comment by lidanqing-vv** [comment]
@baoachun  display log with `DNNL_VEBOSE=1` such as
```
DNNL_VERBOSE=1 python deploy/python/infer.py --model_dir /home/li/issue/blazeface_ori --image_file ./demo/road
554.png --use_gpu False --enable_mkldnn True > log_sub.txt 2>&1
```

**Comment by baoachun** [comment]
@lidanqing-intel  You can get the result by running this two lines code, where the number 1 indicates enable to use mkldnn and the number 10 indicates running 10 round inferences.
~~~
cd test_frcnn_new
python test_fluid.py model/ 1 10
~~~

**Comment by jczaja** [comment]
@baoachun I cannot reproduce this issue e.g. diff mechanism does not report differences for rounds 1..10. It is likely because some of problems were fixed when working on issue #34554 . So could you please retest this problem using recent develop (at least f1c1d9e00260c5eb0187702d3e10b60e9d60a942) ?

**Comment by lidanqing-vv** [comment]
@baoachun  is asking the user the sequence of running to reproduce this error. He will reply here once he got from the customer.

**Comment by lidanqing-vv** [comment]
@baoachun which version this error exist ? Could you please clarify more if it exist on newest develop and the testing sequence.
Jacek could not reproduce this issue. And from the description, users are just using 1.8.4, I think user should use newest develop to see if this issue still exist.
