### ISSUE TITLE
Cuda error(98), invalid device function

### ISSUE THREAD

**Issue by xiao9284** [PaddlePaddle/Paddle#34412]
- 版本、环境信息：
    1）PaddlePaddle版本：paddlepaddle-gpu2.1.1
    2）CPU：---
    3）GPU：GTX850m,6G显存、CUDA11.0和CUDNN8.0.4.30版本号
    4）系统环境：win 10，Python3.8

使用enrnie-2.0做训练时，报错Cuda error(98), invalid device function

**Comment by Shixiaowei02** [comment]
您好！从错误信息来看，可能是运行时库和环境不匹配造成。请您提供更完整的复现环境以便我们排查问题，谢谢！

**Comment by xiao9284** [comment]
您好：
&nbsp; &nbsp; 这边根据群友回答，说是不兼容11.0版本的cuda，我这边重新装了11.2cuda以及配套的cudnn，结果依旧不正确，但报错信息变了。我将环境截图以及报错信息截图通过邮件附件发给您，请查收。


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/Paddle"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年7月28日(星期三) 上午10:38
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PaddlePaddle/Paddle] Cuda error(98), invalid device function (#34412)





 
您好！从错误信息来看，可能是运行时库和环境不匹配造成。请您提供更完整的复现环境以便我们排查问题，谢谢！

**Comment by xiao9284** [comment]
您好，你还在么？我昨天给您发送的邮件有收到么？






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/Paddle"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年7月28日(星期三) 上午10:38
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PaddlePaddle/Paddle] Cuda error(98), invalid device function (#34412)





 
您好！从错误信息来看，可能是运行时库和环境不匹配造成。请您提供更完整的复现环境以便我们排查问题，谢谢！

**Comment by Shixiaowei02** [comment]
您好，我没有收到邮件，您可以直接贴到 issue 回复中，谢谢

**Comment by xiao9284** [comment]
------------------ 原始邮件 ------------------
发件人:                                                                                                                        "PaddlePaddle/Paddle"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年7月28日(星期三) 上午10:38
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PaddlePaddle/Paddle] Cuda error(98), invalid device function (#34412)





 
您好！从错误信息来看，可能是运行时库和环境不匹配造成。请您提供更完整的复现环境以便我们排查问题，谢谢！

**Comment by xiao9284** [comment]
![850M显卡](https://user-images.githubusercontent.com/23395456/127970155-2f05af62-0635-4a63-8edd-15bd1b629de2.png)
![cuda11 2](https://user-images.githubusercontent.com/23395456/127970158-50788df3-1265-407b-bb51-b05e8c652fe9.png)
![cudnn](https://user-images.githubusercontent.com/23395456/127970161-97f79943-51c9-47ae-b120-c64ce50f5725.png)
![paddle版本](https://user-images.githubusercontent.com/23395456/127970164-96473a79-1863-408c-9027-14b4c0dbfe61.png)
![python版本](https://user-images.githubusercontent.com/23395456/127970169-37964975-c9e3-4bcc-89fb-d510fcd8c00e.png)
![报错信息](https://user-images.githubusercontent.com/23395456/127970170-d922bb11-eb49-4fbc-b552-aa07c2d4f956.png)
![驱动版本](https://user-images.githubusercontent.com/23395456/127970172-6fe8c90f-e84a-4414-bef0-f23637203c3d.png)

**Comment by yingyibiao** [comment]
mark

**Comment by dingsiyu** [comment]
paddle的版本与当前机器上的基础环境（例如cuda、cudnn、gcc等）不适配，如果更新了底层的基础环境，建议把paddle也同步更新

**Comment by GT-ZhangAcer** [comment]
850M显卡是一款移动端显卡，由于架构过久，对新版本的CUDA支持也有很多问题，建议10系以上N卡进行深度学习。
同样，该显卡在显存和算力等方面也落后很多，即使使用了合适CUDA版本，也未必见得可以跑基础的深度学习模型，建议更换显卡或在AI Studio等平台完成训练。
