### ISSUE TITLE
用python ppdet/modeling/tests/test_architectures.py测试时报错，RuntimeError: (PreconditionNotMet) The third-party dynamic library (cudnn64_7.dll) that Paddle depends on is not configured correctly. (error code is 126)

### ISSUE THREAD

**Issue by lihui669** [PaddlePaddle/Paddle#34428]
![image](https://user-images.githubusercontent.com/40649829/127135108-0a6c31c0-2bfa-425d-ac73-9df11cb7dd73.png)
我使用的时cuda10.2 ，cudnn64_7.dll已经在lib下，但是还是报错，请问是什么原因呢

**Comment by Shixiaowei02** [comment]
您好，此报错可能因为 cuda/cudnn 版本不对应引起，请下载对应的 gpu 库进行测试。谢谢

**Comment by zhwesky2010** [comment]
@lihui669 需要检查下CUDA安装路径是否在环境变量中，否则无法找到正确的dll
