### ISSUE TITLE
申威平台编译错误

### ISSUE THREAD

**Issue by liam1985** [PaddlePaddle/Paddle#34437]
- 版本、环境信息：
    1）PaddlePaddle版本：v2.1.1
    2）CPU：申威SW6A，
    3）GPU：无
    4）系统环境：Uniontech OS Server 20 Enterprise 20、Python版本 3.7.3

- 安装方式信息：
本地编译：请提供cmake命令，编译命令
cmake .. -DPY_VERSION=3 -DPYTHON_EXECUTABLE=`which python3` -DWITH_MKL=OFF -DWITH_TESTING=OFF -DCMAKE_BUILD_TYPE=Release -DON_INFER=ON -DWITH_PYTHON=ON -DREFERENCE_CBLAS_ROOT=${CBLAS_ROOT} -DWITH_CRYPTO=OFF -DWITH_XBYAK=OFF -DWITH_SW=ON -DCMAKE_CXX_FLAGS="-Wno-error -w"
make
  
- 问题描述：
在构建过程中，
Performing build step for 'extern-openblas'
getarch.c:1193:2: error: #error "This arch/CPU is not supported by OpenBLAS"

构建完全安装教程的步骤进行，也使用blas + cblas的方式，并源码编译blas和cblas。不知道为什么构建过程中仍然使用了openblas。

**Comment by qili93** [comment]
@liam1985 需要同时打开 WITH_SYSTEM_BLAS，参考
https://github.com/PaddlePaddle/Paddle/blob/develop/cmake/cblas.cmake#L91

确保最后cmake可以成功输出
https://github.com/PaddlePaddle/Paddle/blob/develop/cmake/cblas.cmake#L118
message(STATUS "Found reference-cblas (include: ${CBLAS_INC_DIR}, library: ${CBLAS_LIBRARIES})")

如果以上步骤不成功才会去编译 external/openblas
https://github.com/PaddlePaddle/Paddle/blob/develop/cmake/cblas.cmake#L123

**Comment by moye111** [comment]
这个问题解决没有，解决方案是？
