### ISSUE TITLE
工业PC部署无法在GPU上做推理

### ISSUE THREAD

**Issue by kaixin-bai** [PaddlePaddle/Paddle#34434]
## 测试环境
python版本：python3.6
CPU：AMD Ryzen 5 5600X 6-Core Processor
GPU：RTX3070Ti

paddle安装方式：
```
1.    pip3 install paddlepaddle-gpu==2.1.0
2.    python3 -m pip install paddlepaddle-gpu==2.0.2.post100 -f https://paddlepaddle.org.cn/whl/mkl/stable.html
```

## 问题：
无论是上面两个版本中的哪个，问题都是一样的。
1. 在运行下面命令时，在打印完`device: 0, cuDNN Version: 7.6`后就卡住了。
```python
>>> import paddle
>>> paddle.utils.run_check()
```
2.在进行推理时，会卡在`input_tensor.copy_from_cpu(inputs[input_names[i]])`这一行

## 补充说明：
不使用GPU，只使用CPU是可以完成推理的。

**Comment by kaixin-bai** [comment]
@baoyufuyou issue我发在这了

**Comment by Shixiaowei02** [comment]
您好，请先运行 nvidia-driver 和 cuda 的自验证程序，确认问题是单纯由 cuda 还是 paddle 引起。谢谢

**Comment by baoyufuyou** [comment]
cuda test
![image](https://user-images.githubusercontent.com/39621208/127295326-268544fd-1fee-4870-bb8a-62f72b0a3c82.png)
cudnn version
![image](https://user-images.githubusercontent.com/39621208/127295365-cb6cf525-0b52-4309-a116-b9359973edf4.png)
installed pytorch and tested.
![image](https://user-images.githubusercontent.com/39621208/127295266-30652d8e-1c88-4a2f-8dfe-cdf9ff3d1d33.png)

**Comment by baoyufuyou** [comment]
![image](https://user-images.githubusercontent.com/39621208/127295498-50592c4b-8f6e-4ed5-b281-e93dffc78e27.png)
nvidia-smi

**Comment by baoyufuyou** [comment]
![image](https://user-images.githubusercontent.com/39621208/127295980-db9f9aa6-3b2e-4aea-8bd6-f5a87f9fd84c.png)
test paddlepaddle:
卡住了的截图

**Comment by baoyufuyou** [comment]
fixed after updating the cuda10 to cuda11 and cudnn8
