### ISSUE TITLE
请问如何进行冻结层的训练呢？

### ISSUE THREAD

**Issue by ZZHHogan** [PaddlePaddle/Paddle#34472]
目前我使用的是paddleocr，想通过冻结层进行少数据集的训练，但是设置冻结后好像没有生效，不知是哪里设置错误了？
- 版本、环境信息：
    1）PaddlePaddle版本：paddlepaddle-gpu        2.1.1.post112
    3）GPU：预测若用GPU，rtx3090，cuda11.2
    4）系统环境：centos、python3.8

- 训练信息
    1）单机，单卡
    2）显存信息
    3）Operator：使用冻结训练，可是发现好像没有生效，不清楚应该如何正确设置？
![image](https://user-images.githubusercontent.com/40531744/127419043-e78d2f15-9a46-4b88-9667-cd88e0591a02.png)

**Comment by LDOUBLEV** [comment]
冻结参数不训练的方法参考：
```
if freeze_params:
    for param in model.parameters():
        param.trainable = False
```
