### ISSUE TITLE
paddledetection2.0训练的pp_yolo_tiny部署在paddlelite2.8,2.9报错

### ISSUE THREAD

**Issue by nbh2021** [PaddlePaddle/Paddle#34471]
- 版本、环境信息：
    1）PaddlePaddle版本：2.1.0
    4）系统环境：python3.7
- 模型信息
    1）pp_yolo_yiny 

[/root/Paddle-Lite/lite/api/light_api.cc CheckInputValid:312]  Error input tensor   
precision type . Input index(1) Tensor name{image} Require Precision type(float) Input Precision type (int32_t).
[/root/Paddle-Lite/lite/core/program.cc Run:619] Check failed: op_->CheckShape():
./run.sh: line19 :3341 Aborted    (core dumped)

paddledetection 2.0训练的ppyolo_tiny和ssd我都试过，报的是同样的错，但是pp_yolo_tiny官网给的模型转换成nb可以运行。

**Comment by hong19860320** [comment]
在写yolo的paddlelite demo时需要注意yolo模型不同于ssd，它有两个输入，其中一个输入是图像的尺寸，是一个int32的数据类型，在mutable_data的时候记得mutable_data<int32_t>
建议在部署前把paddle模型中的__mode__文件拖到https://netron.app查看下输入个数以及相应的数据类型。
