### ISSUE TITLE
Yolov5模型后处理层不支持

### ISSUE THREAD

**Issue by youngstu** [PaddlePaddle/Paddle#34479]
问题描述：
1、pytorch训练模型，导出onnx，再转到paddle，paddle模型没有实现yolov5后处理部分（解码+nms），请问怎么实现呢？

**Comment by b3602sss** [comment]
可以尝试自己增加op https://www.paddlepaddle.org.cn/documentation/docs/zh/guides/07_new_op/index_cn.html

**Comment by jiangjiajun** [comment]
Duplicate of https://github.com/PaddlePaddle/X2Paddle/issues/651
