### ISSUE TITLE
Win10+VS2019编译PaddleOCR错误

### ISSUE THREAD

**Issue by CheQiXiao** [PaddlePaddle/Paddle#34482]
部署环境：

按教程 https://github.com/PaddlePaddle/PaddleOCR/tree/release/2.1/deploy/cpp_infer操作。

win10家庭版、    VS2019企业版    

源码：PaddleOCR-release-2.1

预测库：https://paddle-wheel.bj.bcebos.com/2.0.2/win-infer/mkl/cpu/paddle_inference.zip

推理模型：轻量版

问题：

按官方教程操作老是报错【'/paddle/lib/paddle_inference.lib', needed by 'ocr_system.exe', missing and no known rule to】，再参考其他教程增加了尝试调整opencv和预测库的版本和路径，还是报同样错误

报错：
![image](https://user-images.githubusercontent.com/50894398/127448864-5fafd928-bd8d-4dd4-a93a-0be6ed545b8b.png)
配置：
![image](https://user-images.githubusercontent.com/50894398/127448953-cd358bb8-2970-4838-adde-cf79bd309713.png)

![image](https://user-images.githubusercontent.com/50894398/127448971-055c4e08-96be-4aa4-898a-34e796cd9931.png)

来自帖子：https://aistudio.baidu.com/paddle/forum/topic/show/989644

**Comment by hong19860320** [comment]
看起来是路径设置问题，估计/paddle/lib/paddle_inference.lib是linux docker下的路径，看起来是PADDLE_LIB这个参数没有传到cmake脚本
你修改下cmake脚本强制把D:\projects\paddle_inference_install_dir路径设置到PADDLE_LIB变量试试，就和你设置OpenCV_DIR一样

**Comment by CUI-XUAN** [comment]
我也遇到这个问题，请问如何解决了？
