### ISSUE TITLE
paddle 2.1版本快速上手文档描述错误

### ISSUE THREAD

**Issue by meii11** [PaddlePaddle/Paddle#34481]
https://www.paddlepaddle.org.cn/documentation/docs/zh/tutorial/quick_start/high_level_api/high_level_api.html
快速上手文档中的高层API使用指南部分，5.4部分中最后的描述：“这里面有一个注意的点，有些读者可能会疑惑为什么要传递(1, 28, 28)这个input_size参数，因为在动态图中，网络定义阶段是还没有得到输入数据的形状信息，想要做网络结构的呈现就无从下手，那么通过告知接口网络结构的输入数据形状，这样网络可以通过逐层的计算推导得到完整的网络结构信息进行呈现。如果是动态图运行模式，那么就不需要给summary接口传递输入数据形状这个值了，因为在Model封装的时候已经定义好了InputSpec，其中包含了输入数据的形状格式。”
最后一句我认为应该是“如果是**静态图**运行模式，那么就不需要给summary接口传递输入数据形状这个值了”

**Comment by TCChenlong** [comment]
好的，是有这个问题，我们改一下，感谢反馈~
