### ISSUE TITLE
paddle2.1.1安装后出现Illegal instruction

### ISSUE THREAD

**Issue by davidwkx** [PaddlePaddle/Paddle#34494]
环境：centos7  python3.8.11 gcc8.2.0 安装paddlepaddle2.1.1 cpu版  机器支持 avx2指令集

问题：

1、根据官网指导: python -m pip install paddlepaddle -i https://mirror.baidu.com/pypi/simple 安装后：

运行python，import paddle出现：Illegal instruction 错误

2、改安装no-avx版本，
安装说明中的python -m pip install paddlepaddle==2.1.1 -f https://www.paddlepaddle.org.cn/whl/mkl/stable/noavx.html --no-index直接用报错，改用：
wget https://paddle-wheel.bj.bcebos.com/2.1.1-cpu-noavx-mkl/paddlepaddle-2.1.1.noavx-cp38-cp38-linux_x86_64.whl 安装，运行python，import paddle出现：
WARNING: AVX is supported on local machine, but you have installed paddlepaddle without avx core. Hence, no_avx core which has worse preformance will be imported. You could reinstall paddlepaddle by 'python -m pip install --force-reinstall paddlepaddle-gpu[==version]' or rebuild paddlepaddle WITH_AVX=ON to get better performance. The original error is: No module named 'paddle.fluid.core_avx'

再用'python -m pip install --force-reinstall 又回到第一种错误
3、最后安装no-avx版本，运行paddleClas体验出错信息如下：
---    Fused 0 subgraphs into layer_norm op.
---    Fused 0 subgraphs into layer_norm op.
Inference: 6854.187726974487 ms per batch image

--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
0   _ctypes_callproc
1   search_mobius_index
2   paddle::framework::SignalHandle(char const*, int)
3   paddle::platform::GetCurrentTraceBackString[abi:cxx11]()

----------------------
Error Message Summary:
----------------------
FatalError: `Illegal instruction` is detected by the operating system.
  [TimeInfo: *** Aborted at 1627606120 (unix time) try "date -d @1627606120" if you are using GNU date ***]
  [SignalInfo: *** SIGILL (@0x7f7a48647152) received by PID 8582 (TID 0x7f7a780c5840) from PID 1214542162 ***]

Illegal instruction

**Comment by pangyoki** [comment]
你好，是装avx的包会报`Illegal instruction`的问题？装no-avx的包`import paddle`没问题，跑模型有问题？

麻烦试下在docker里装paddle试试？排除下环境问题。

可以装这个镜像：`docker pull paddlepaddle/paddle:latest-gpu-cuda10.2-cudnn7-dev`

**Comment by davidwkx** [comment]
我这个机器暂时不支持GPU，只能用 CPU版本的。
装avx的包，import paddle时，直接就是错误退出：Illegal instruction
装no-avx的包，import paddle时出现警告错误：
WARNING: AVX is supported on local machine, but you have installed paddlepaddle without avx core. Hence, no_avx core which has worse preformance will be imported. You could reinstall paddlepaddle by 'python -m pip install --force-reinstall paddlepaddle-gpu[==version]' or rebuild paddlepaddle WITH_AVX=ON to get better performance. The original error is: No module named 'paddle.fluid.core_avx'

之前也用docker（docker pull registry.baidubce.com/paddlepaddle/paddle:2.1.1）试了，发现同样问题

用你提供的镜像（docker pull registry.baidubce.com/paddlepaddle/paddle:latest-gpu-cuda10.2-cudnn7-dev）下载过程中出如下错误：
failed to register layer: Error processing tar file(exit status 1): write /usr/local/TensorRT-7.1.3.4/targets/x86_64-linux-gnu/lib/libnvinfer.so.7.1.3: no space left on device

**Comment by pangyoki** [comment]
> 我这个机器暂时不支持GPU，只能用 CPU版本的。
> 装avx的包，import paddle时，直接就是错误退出：Illegal instruction
> 装no-avx的包，import paddle时出现警告错误：
> WARNING: AVX is supported on local machine, but you have installed paddlepaddle without avx core. Hence, no_avx core which has worse preformance will be imported. You could reinstall paddlepaddle by 'python -m pip install --force-reinstall paddlepaddle-gpu[==version]' or rebuild paddlepaddle WITH_AVX=ON to get better performance. The original error is: No module named 'paddle.fluid.core_avx'
> 
> 之前也用docker（docker pull registry.baidubce.com/paddlepaddle/paddle:2.1.1）试了，发现同样问题
> 
> 用你提供的镜像（docker pull registry.baidubce.com/paddlepaddle/paddle:latest-gpu-cuda10.2-cudnn7-dev）下载过程中出如下错误：
> failed to register layer: Error processing tar file(exit status 1): write /usr/local/TensorRT-7.1.3.4/targets/x86_64-linux-gnu/lib/libnvinfer.so.7.1.3: no space left on device


你可以先用 no-avx 的包吧，no-avx那个只是warning，不影响使用的。
avx包的问题有点奇怪，也没有报错提示，麻烦提供下你机器的配置，cpu的信息等。

下docker时的报错，是因为磁盘空间不够吧。机器不支持gpu也可以使用cuda镜像，装cpu版的paddle就可以。
不过你已经尝试过 registry.baidubce.com/paddlepaddle/paddle:2.1.1 这个镜像报错了，还报错的话应该还是机器的基础配置有问题。

**Comment by davidwkx** [comment]
用docker版本运行出错信息如下：
(ve3.8) [root@localhost paddle]# docker run --name paddle -it -v $PWD:/paddle registry.baidubce.com/paddlepaddle/paddle:2.1.1 /bin/bash
λ 158387b7d698 /home python
Python 3.7.0 (default, May  9 2021, 21:14:18) 
[GCC 8.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import paddle
grep: warning: GREP_OPTIONS is deprecated; please use an alias or script
Illegal instruction (core dumped)

用no-avx，仅import paddle是只是WARNING信息，但运行paddleCas出错信息如下：
(ve3.8) [root@localhost deploy]# python python/predict_system.py -c configs/inference_product.yaml -o Global.use_gpu=False
WARNING: AVX is supported on local machine, but you have installed paddlepaddle without avx core. Hence, no_avx core which has worse preformance will be imported.
You could reinstall paddlepaddle by 'python -m pip install --force-reinstall paddlepaddle-gpu[==version]' or rebuild paddlepaddle WITH_AVX=ON to get better performance.
The original error is: No module named 'paddle.fluid.core_avx'
2021-07-30 15:01:58 INFO: 
===========================================================
==        PaddleClas is powered by PaddlePaddle !        ==
===========================================================
==                                                       ==
==   For more info please go to the following website.   ==
==                                                       ==
==       https://github.com/PaddlePaddle/PaddleClas      ==
===========================================================
。。。
---    Fused 0 subgraphs into layer_norm op.
Inference: 7312.743425369263 ms per batch image
--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
0   _ctypes_callproc
1   search_mobius_index
2   paddle::framework::SignalHandle(char const*, int)
3   paddle::platform::GetCurrentTraceBackString[abi:cxx11]()
----------------------
Error Message Summary:
----------------------
FatalError: `Illegal instruction` is detected by the operating system.
  [TimeInfo: *** Aborted at 1627628531 (unix time) try "date -d @1627628531" if you are using GNU date ***]
  [SignalInfo: *** SIGILL (@0x7fba9cebf152) received by PID 10058 (TID 0x7fbacc93f840) from PID 18446744072047292754 ***]

Illegal instruction

机器配置信息：
(ve3.8) [root@localhost paddle]# uname -a
Linux localhost.localdomain 3.10.0-514.el7.x86_64 #1 SMP Tue Nov 22 16:42:41 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
(ve3.8) [root@localhost paddle]# cat /proc/cpuinfo
processor	: 0
vendor_id	: GenuineIntel
cpu family	: 6
model		: 63
model name	: Intel(R) Xeon(R) CPU E5-2603 v3 @ 1.60GHz
stepping	: 2
microcode	: 0x36
cpu MHz		: 1598.330
cache size	: 15360 KB
physical id	: 0
siblings	: 1
core id		: 0
cpu cores	: 1
apicid		: 0
initial apicid	: 0
fpu		: yes
fpu_exception	: yes
cpuid level	: 13
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx rdtscp lm constant_tsc rep_good nopl pni pclmulqdq ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes f16c rdrand hypervisor lahf_lm abm fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid
bogomips	: 3196.38
clflush size	: 64
cache_alignment	: 64
address sizes	: 46 bits physical, 48 bits virtual
power management:

**Comment by davidwkx** [comment]
用docker pull registry.baidubce.com/paddlepaddle/paddle:latest-gpu-cuda10.2-cudnn7-dev 安装运行后，执行过程及错误信息如下：
[root@localhost paddle]# docker ps -a
CONTAINER ID        IMAGE                                                                      COMMAND                  CREATED             STATUS              PORTS               NAMES
d90c64a6f8a5        registry.baidubce.com/paddlepaddle/paddle:latest-gpu-cuda10.2-cudnn7-dev   "/bin/bash"              6 minutes ago       Up 9 seconds        22/tcp              paddle
fa0714efdc95        bd3989d14a6a                                                               "/bin/bash -c 'sh /u…"   3 months ago        Up 2 months                             ccps
[root@localhost paddle]# docker exec -it paddle /bin/bash
λ d90c64a6f8a5 /home python3
Python 3.7.0 (default, Apr 20 2021, 10:55:23) 
[GCC 8.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import paddle
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
**ModuleNotFoundError: No module named 'paddle'**
>>>

**Comment by pangyoki** [comment]
> 用docker pull registry.baidubce.com/paddlepaddle/paddle:latest-gpu-cuda10.2-cudnn7-dev 安装运行后，执行过程及错误信息如下：
> [root@localhost paddle]# docker ps -a
> CONTAINER ID IMAGE COMMAND CREATED STATUS PORTS NAMES
> d90c64a6f8a5 registry.baidubce.com/paddlepaddle/paddle:latest-gpu-cuda10.2-cudnn7-dev "/bin/bash" 6 minutes ago Up 9 seconds 22/tcp paddle
> fa0714efdc95 bd3989d14a6a "/bin/bash -c 'sh /u…" 3 months ago Up 2 months ccps
> [root@localhost paddle]# docker exec -it paddle /bin/bash
> λ d90c64a6f8a5 /home python3
> Python 3.7.0 (default, Apr 20 2021, 10:55:23)
> [GCC 8.2.0] on linux
> Type "help", "copyright", "credits" or "license" for more information.
> 
> > > > import paddle
> > > > Traceback (most recent call last):
> > > > File "", line 1, in 
> > > > **ModuleNotFoundError: No module named 'paddle'**

这个docker里没有预装paddle，需要手动安装下paddle

**Comment by pangyoki** [comment]
> 用docker版本运行出错信息如下：
> (ve3.8) [root@localhost paddle]# docker run --name paddle -it -v $PWD:/paddle registry.baidubce.com/paddlepaddle/paddle:2.1.1 /bin/bash
> λ 158387b7d698 /home python
> Python 3.7.0 (default, May 9 2021, 21:14:18)
> [GCC 8.2.0] on linux
> Type "help", "copyright", "credits" or "license" for more information.
> 
> > > > import paddle
> > > > grep: warning: GREP_OPTIONS is deprecated; please use an alias or script
> > > > Illegal instruction (core dumped)
> 
> # 用no-avx，仅import paddle是只是WARNING信息，但运行paddleCas出错信息如下：
> (ve3.8) [root@localhost deploy]# python python/predict_system.py -c configs/inference_product.yaml -o Global.use_gpu=False
> WARNING: AVX is supported on local machine, but you have installed paddlepaddle without avx core. Hence, no_avx core which has worse preformance will be imported.
> You could reinstall paddlepaddle by 'python -m pip install --force-reinstall paddlepaddle-gpu[==version]' or rebuild paddlepaddle WITH_AVX=ON to get better performance.
> The original error is: No module named 'paddle.fluid.core_avx'
> 2021-07-30 15:01:58 INFO:
> # == PaddleClas is powered by PaddlePaddle ! ==
> # == ==
> == For more info please go to the following website. ==
> == ==
> == https://github.com/PaddlePaddle/PaddleClas ==
> ## 。。。
> --- Fused 0 subgraphs into layer_norm op.
> Inference: 7312.743425369263 ms per batch image
> ## C++ Traceback (most recent call last):
> ## 0 _ctypes_callproc
> 1 search_mobius_index
> 2 paddle::framework::SignalHandle(char const*, int)
> 3 paddle::platform::GetCurrentTraceBackStringabi:cxx11
> ## Error Message Summary:
> 
> FatalError: `Illegal instruction` is detected by the operating system.
> [TimeInfo: *** Aborted at 1627628531 (unix time) try "date -d @1627628531" if you are using GNU date ***]
> [SignalInfo: *** SIGILL (@0x7fba9cebf152) received by PID 10058 (TID 0x7fbacc93f840) from PID 18446744072047292754 ***]
> 
> Illegal instruction
> 
> 机器配置信息：
> (ve3.8) [root@localhost paddle]# uname -a
> Linux localhost.localdomain 3.10.0-514.el7.x86_64 #1 SMP Tue Nov 22 16:42:41 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
> (ve3.8) [root@localhost paddle]# cat /proc/cpuinfo
> processor : 0
> vendor_id : GenuineIntel
> cpu family : 6
> model : 63
> model name : Intel(R) Xeon(R) CPU E5-2603 v3 @ 1.60GHz
> stepping : 2
> microcode : 0x36
> cpu MHz : 1598.330
> cache size : 15360 KB
> physical id : 0
> siblings : 1
> core id : 0
> cpu cores : 1
> apicid : 0
> initial apicid : 0
> fpu : yes
> fpu_exception : yes
> cpuid level : 13
> wp : yes
> flags : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx rdtscp lm constant_tsc rep_good nopl pni pclmulqdq ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes f16c rdrand hypervisor lahf_lm abm fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid
> bogomips : 3196.38
> clflush size : 64
> cache_alignment : 64
> address sizes : 46 bits physical, 48 bits virtual
> power management:

这些报错是用noavx包，执行PaddleClas时的报错吗？用noavx包，执行`paddle.utils.run_check()`会报错吗？

**Comment by tengda100** [comment]
楼主解决了吗  我这边和的情况一样  也是  Xeon E5 CPU
