### ISSUE TITLE
jetson nano 预测报错

### ISSUE THREAD

**Issue by QQ39272490** [PaddlePaddle/Paddle#34493]
问题类型：模型部署
问题描述: 我用paddlex 1.8训练模型 mobile v2，时间久了就报错
部署环境：Jetson nano，Jetpack 4.5 python3.6+nv_jetson-cuda10.2-cudnn8-trt7
安装官方提供的库 paddlepaddle_gpu-2.1.1-cp36-cp36m-linux_aarch64.whl

![infer](https://user-images.githubusercontent.com/2766645/127584735-46de5417-c9d2-4be9-bd2c-1e85e1dca610.jpg)

**Comment by fengxiaoshuai** [comment]
时间久了出问题，一般都是资源不够用，jetson-nano的显存和内存共用4G,  建议增加swap后再尝试，此外可以试试Paddle训练的mobilenet模型看看会不会出现同样问题。

**Comment by QQ39272490** [comment]
swap本身设置的8G

**Comment by fengxiaoshuai** [comment]
该报错信息无法看出原因，最好提供单测代码和相应模型

**Comment by 007cod** [comment]
我也遇到了相同的问题， 请问解决了吗？
