### ISSUE TITLE
fleet ps 模式 inference 问题

### ISSUE THREAD

**Issue by Liwb5** [PaddlePaddle/Paddle#34496]
https://github.com/PaddlePaddle/Paddle/blob/423ea9782ab7ae76501e6acc7ec92b2cecd8633e/python/paddle/distributed/fleet/utils/ps_util.py#L53

代码这个地方直接写SGD作为fake optimizer，但是如果用户的保存的模型是用其它优化器（如adam），那么这里就会报错。建议这里留个接口给用户指定优化器。

**Comment by zhupengyang** [comment]
感谢您的建议，后续会进行修复
