### ISSUE TITLE
2.1.1版本安装后import出错 ImportError: /lib64/libstdc++.so.6: version `CXXABI_1.3.8' not found 

### ISSUE THREAD

**Issue by wxf764571829** [PaddlePaddle/Paddle#34504]
服务器centos7下
python3.8 使用pip安装 因为服务器不支持AVX 所以采用cpu、mkl版本noavx机器安装：
安装命令为 ：pip3 install paddlepaddle==2.1.1 -f https://www.paddlepaddle.org.cn/whl/mkl/stable/noavx.html --no-index

WARNING: AVX is not support on your machine. Hence, no_avx core will be imported, It has much worse preformance than avx core.
Error: Can not import noavx core while this file exists: /home/ai_zfsw/Python-3.8/lib/python3.8/site-packages/paddle/fluid/core_noavx.so
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ai_zfsw/Python-3.8/lib/python3.8/site-packages/paddle/__init__.py", line 25, in <module>
    from .fluid import monkey_patch_variable
  File "/home/ai_zfsw/Python-3.8/lib/python3.8/site-packages/paddle/fluid/__init__.py", line 36, in <module>
    from . import framework
  File "/home/ai_zfsw/Python-3.8/lib/python3.8/site-packages/paddle/fluid/framework.py", line 37, in <module>
    from . import core
  File "/home/ai_zfsw/Python-3.8/lib/python3.8/site-packages/paddle/fluid/core.py", line 369, in <module>
    raise e
  File "/home/ai_zfsw/Python-3.8/lib/python3.8/site-packages/paddle/fluid/core.py", line 316, in <module>
    from .core_noavx import *
ImportError: /lib64/libstdc++.so.6: version `CXXABI_1.3.8' not found (required by /home/ai_zfsw/Python-3.8/lib/python3.8/site-packages/paddle/fluid/core_noavx.so)

**Comment by pangyoki** [comment]
> 服务器centos7下
> python3.8 使用pip安装 因为服务器不支持AVX 所以采用cpu、mkl版本noavx机器安装：
> 安装命令为 ：pip3 install paddlepaddle==2.1.1 -f https://www.paddlepaddle.org.cn/whl/mkl/stable/noavx.html --no-index
> 
> WARNING: AVX is not support on your machine. Hence, no_avx core will be imported, It has much worse preformance than avx core.
> Error: Can not import noavx core while this file exists: /home/ai_zfsw/Python-3.8/lib/python3.8/site-packages/paddle/fluid/core_noavx.so
> Traceback (most recent call last):
> File "", line 1, in
> File "/home/ai_zfsw/Python-3.8/lib/python3.8/site-packages/paddle/**init**.py", line 25, in
> from .fluid import monkey_patch_variable
> File "/home/ai_zfsw/Python-3.8/lib/python3.8/site-packages/paddle/fluid/**init**.py", line 36, in
> from . import framework
> File "/home/ai_zfsw/Python-3.8/lib/python3.8/site-packages/paddle/fluid/framework.py", line 37, in
> from . import core
> File "/home/ai_zfsw/Python-3.8/lib/python3.8/site-packages/paddle/fluid/core.py", line 369, in
> raise e
> File "/home/ai_zfsw/Python-3.8/lib/python3.8/site-packages/paddle/fluid/core.py", line 316, in
> from .core_noavx import *
> ImportError: /lib64/libstdc++.so.6: version `CXXABI_1.3.8' not found (required by /home/ai_zfsw/Python-3.8/lib/python3.8/site-packages/paddle/fluid/core_noavx.so)

你好，看起来是gcc版本太低的问题，需要是用gcc8.2，请确认下

**Comment by pangyoki** [comment]
> 服务器centos7下
> python3.8 使用pip安装 因为服务器不支持AVX 所以采用cpu、mkl版本noavx机器安装：
> 安装命令为 ：pip3 install paddlepaddle==2.1.1 -f https://www.paddlepaddle.org.cn/whl/mkl/stable/noavx.html --no-index
> 
> WARNING: AVX is not support on your machine. Hence, no_avx core will be imported, It has much worse preformance than avx core.
> Error: Can not import noavx core while this file exists: /home/ai_zfsw/Python-3.8/lib/python3.8/site-packages/paddle/fluid/core_noavx.so
> Traceback (most recent call last):
> File "", line 1, in
> File "/home/ai_zfsw/Python-3.8/lib/python3.8/site-packages/paddle/**init**.py", line 25, in
> from .fluid import monkey_patch_variable
> File "/home/ai_zfsw/Python-3.8/lib/python3.8/site-packages/paddle/fluid/**init**.py", line 36, in
> from . import framework
> File "/home/ai_zfsw/Python-3.8/lib/python3.8/site-packages/paddle/fluid/framework.py", line 37, in
> from . import core
> File "/home/ai_zfsw/Python-3.8/lib/python3.8/site-packages/paddle/fluid/core.py", line 369, in
> raise e
> File "/home/ai_zfsw/Python-3.8/lib/python3.8/site-packages/paddle/fluid/core.py", line 316, in
> from .core_noavx import *
> ImportError: /lib64/libstdc++.so.6: version `CXXABI_1.3.8' not found (required by /home/ai_zfsw/Python-3.8/lib/python3.8/site-packages/paddle/fluid/core_noavx.so)

你好，看起来是gcc版本太低的问题，需要使用gcc8.2，请确认下
