### ISSUE TITLE
After updated to 2.1.1,this method dose not support any more.

### ISSUE THREAD

**Issue by nsCosine** [PaddlePaddle/Paddle#34514]
In AIStudio platform, pp version is 2.1.0，
this method is fine，
```python
def sgd(params, lr, batch_size):  
    with paddle.no_grad():
        for param in params:
            param[:] = param - lr * param.grad / batch_size
            param.clear_grad()
```
after updated to 2.1.1，this method would raise an error
`
ValueError: (InvalidArgument) Leaf Tensor (dygraph_tmp_19) that doesn't stop gradient can't use inplace strategy.
  [Hint: Expected self->IsLeaf() && !self->OverridedStopGradient() == false, but received self->IsLeaf() && !self->OverridedStopGradient():1 != false:0.] (at /paddle/paddle/fluid/pybind/imperative.cc:718)
`
After function sgd changed, this error disappear.
```python
def sgd(params, lr, batch_size):  
    """mini-batch SGD。"""
    for param in params:
        param.stop_gradient = True
        param[:] = param - lr * param.grad / batch_size

        param.clear_grad()
        param.stop_gradient = False
```

**Comment by hbwx24** [comment]
When a leaf tensor(`param`) is the input of inplace op, its `stop_gradient` must be `True,` otherwise it may cause gradient calculation errors. `param[:] = xxx` is inplace, so `param.stop_gradient` should be `True` . This mechanism was updated in a recent version.
