### ISSUE TITLE
输入变量未初始化问题

### ISSUE THREAD

**Issue by GraceGay** [PaddlePaddle/Paddle#34534]
- 版本、环境信息：
    1）PaddlePaddle版本：1.8.5
    2）CPU/GPU：CPU
    3）系统环境：CentOS release 4.3 (Final)
    4）Python版本号： Python 2.7.13 
    5）显存信息

- 复现信息：

```def test12():
    import paddle.fluid as fluid
    import numpy as np
    from paddle.fluid.layer_helper import LayerHelper
    from paddle.fluid.initializer import Constant
    
    helper = LayerHelper("Test", **{})

    global_ins_cnt, _ = helper.create_or_get_global_variable(
            name="ins_cnt", persistable=False, dtype='int64', shape=[1])
    helper.set_variable_initializer(
            global_ins_cnt, Constant(
                value=7, force_cpu=True))

    label = fluid.data(
            name="label", shape=[10], dtype="int64")
    batch_ins = fluid.layers.reduce_sum(label)

    helper.append_op(
        type="elementwise_add",
        inputs={"X": [global_ins_cnt],
                "Y": [batch_ins]},
        outputs={"Out": [global_ins_cnt]})
   
    place = fluid.CPUPlace()
    exe = fluid.Executor(place)
    exe.run(program=fluid.default_startup_program())
    
    for _ in range(10):
        # ret=exe.run(feed={"label":np.array([1,1,1,1,1,1,0,0,0,0]),"ins_cnt":np.array([7])},fetch_list=[global_ins_cnt])
        ret=exe.run(feed={"label":np.array([1,1,1,1,1,1,0,0,0,0])},fetch_list=[global_ins_cnt])
        print("ret",ret)
    # print("ret",ret)
test12()
```

报错：
/home/disk6/hjz/gru4rec_single/python/lib/python2.7/site-packages/paddle/fluid/executor.py:1070: UserWarning: The following exception is not an EOF exception.
  "The following exception is not an EOF exception.")
Traceback (most recent call last):
  File "test.py", line 457, in <module>
    test12()
  File "test.py", line 454, in test12
    ret=exe.run(feed={"label":np.array([1,1,1,1,1,1,0,0,0,0])},fetch_list=[global_ins_cnt])
  File "/home/disk6/hjz/gru4rec_single/python/lib/python2.7/site-packages/paddle/fluid/executor.py", line 1071, in run
    six.reraise(*sys.exc_info())
  File "/home/disk6/hjz/gru4rec_single/python/lib/python2.7/site-packages/paddle/fluid/executor.py", line 1066, in run
    return_merged=return_merged)
  File "/home/disk6/hjz/gru4rec_single/python/lib/python2.7/site-packages/paddle/fluid/executor.py", line 1154, in _run_impl
    use_program_cache=use_program_cache)
  File "/home/disk6/hjz/gru4rec_single/python/lib/python2.7/site-packages/paddle/fluid/executor.py", line 1229, in _run_program
    fetch_var_name)
paddle.fluid.core_avx.EnforceNotMet: 

--------------------------------------------
C++ Call Stacks (More useful to developers):
--------------------------------------------
0   std::string paddle::platform::GetTraceBackString<std::string const&>(std::string const&, char const*, int)
1   paddle::platform::EnforceNotMet::EnforceNotMet(std::string const&, char const*, int)
2   paddle::framework::OperatorWithKernel::ParseInputDataType(paddle::framework::ExecutionContext const&, std::string const&, paddle::framework::proto::VarType_Type*) const
3   paddle::framework::OperatorWithKernel::IndicateVarDataType(paddle::framework::ExecutionContext const&, std::string const&) const
4   paddle::operators::ElementwiseOp::GetExpectedKernelType(paddle::framework::ExecutionContext const&) const
5   paddle::framework::OperatorWithKernel::ChooseKernel(paddle::framework::RuntimeContext const&, paddle::framework::Scope const&, paddle::platform::Place const&) const
6   paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, paddle::platform::Place const&, paddle::framework::RuntimeContext*) const
7   paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, paddle::platform::Place const&) const
8   paddle::framework::OperatorBase::Run(paddle::framework::Scope const&, paddle::platform::Place const&)
9   paddle::framework::Executor::RunPartialPreparedContext(paddle::framework::ExecutorPrepareContext*, paddle::framework::Scope*, long, long, bool, bool, bool)
10  paddle::framework::Executor::RunPreparedContext(paddle::framework::ExecutorPrepareContext*, paddle::framework::Scope*, bool, bool, bool)
11  paddle::framework::Executor::Run(paddle::framework::ProgramDesc const&, paddle::framework::Scope*, int, bool, bool, std::vector<std::string, std::allocator<std::string> > const&, bool, bool)

------------------------------------------
Python Call Stacks (More useful to users):
------------------------------------------
  File "/home/disk6/hjz/gru4rec_single/python/lib/python2.7/site-packages/paddle/fluid/framework.py", line 2610, in append_op
    attrs=kwargs.get("attrs", None))
  File "/home/disk6/hjz/gru4rec_single/python/lib/python2.7/site-packages/paddle/fluid/layer_helper.py", line 43, in append_op
    return self.main_program.current_block().append_op(*args, **kwargs)
  File "test.py", line 446, in test12
    outputs={"Out": [global_ins_cnt]})
  File "test.py", line 457, in <module>
    test12()

----------------------
Error Message Summary:
----------------------
InvalidArgumentError: The Tensor in the elementwise_add Op's Input Variable X(ins_cnt) is not initialized.
  [Hint: Expected t->IsInitialized() == true, but received t->IsInitialized():0 != true:1.] at (/paddle/paddle/fluid/framework/operator.cc:1289)
  [operator < elementwise_add > error]

**Comment by DannyIsFunny** [comment]
你好，`layer_helper ` 接口不是我们对外开放的正式接口、该API属于内部DEBUG接口、主要用于 OP注册时的信息调试
如果只是想组一个网络并执行前向推理，可以参考以下DEMO：
https://www.paddlepaddle.org.cn/documentation/docs/zh/1.8/api_cn/layers_cn/elementwise_add_cn.html#daimashili-1

**Comment by braid123** [comment]
> 你好，`layer_helper ` 接口不是我们对外开放的正式接口、该API属于内部DEBUG接口、主要用于 OP注册时的信息调试 如果只是想组一个网络并执行前向推理，可以参考以下DEMO： https://www.paddlepaddle.org.cn/documentation/docs/zh/1.8/api_cn/layers_cn/elementwise_add_cn.html#daimashili-1

你好，我也遇到类似的问题。模型其余地方没问题，我没有使用到layer_helper，只是用paddle.fluid.layers进行reshape操作时候显示`InvalidArgumentError: The Tensor in the reshape2 Op's Input Variable X(label) is not initialized`
而我根据已有方案，进行了exe = fluid.Executor(fluid.default_startup_program())操作，但还是报同样的错误消息，请问现在官方有解决方案了吗？
