### ISSUE TITLE
pycharm为apple M1芯片适配的版本上无法安装paddlepaddle，求助如何解决

### ISSUE THREAD

**Issue by Utopialjp** [PaddlePaddle/Paddle#34532]
公司发的macbook pro，是苹果m1的芯片。
在pycharm intel版本下，环境信息如下，该环境下能正常安装
`python -c "import platform;print(platform.architecture()[0]);print(platform.machine())"`
`64bit`
`x86_64`

但是在pycharm专门为m1芯片适配的pycharm Apple Silicon版本下，无法安装，提示错误ERROR: Could not find a version that satisfies the requirement paddlepaddle (from versions: none)。环境信息如下：
`python -c "import platform;print(platform.architecture()[0]);print(platform.machine())"`
`64bit`
`arm64`

python版本都是：
`python --version`
`Python 3.8.2`

安装的都是paddlepaddle cpu版本，怀疑是pycharm Apple Silicon版本下，因为是arm64 paddlepaddle不支持导致的，请问有啥办法吗？

**Comment by DannyIsFunny** [comment]
你好。mac M1 上通过 pip 直接安装是验证过没有问题，建议使用pip 直接在macOS M1 机型上安装paddlePaddle

**Comment by DannyIsFunny** [comment]
关于pycharm上有更详细的错误信息吗

**Comment by Utopialjp** [comment]
> 关于pycharm上有更详细的错误信息吗

![image](https://user-images.githubusercontent.com/23400855/127869104-6af23359-4ae3-4535-b941-85f8191031a4.png)
pycharm里就是pip安装的，错误信息如上。

**Comment by pangyoki** [comment]
你好，直接下载whl包到本地安装可以吗？
https://paddle-wheel.bj.bcebos.com/2.1.2/macos/macos-cpu-openblas/paddlepaddle-2.1.2-cp38-cp38-macosx_10_14_x86_64.whl

**Comment by Utopialjp** [comment]
> 你好，直接下载whl包到本地安装可以吗？
> https://paddle-wheel.bj.bcebos.com/2.1.2/macos/macos-cpu-openblas/paddlepaddle-2.1.2-cp38-cp38-macosx_10_14_x86_64.whl

![image](https://user-images.githubusercontent.com/23400855/128147311-6b5908ef-8510-47c2-a212-b4b36d0d2763.png)
无法安装呢

**Comment by huangbin2005** [comment]
好像还不支持arm芯片吧

**Comment by dingjiaweiww** [comment]
@Utopialjp 如果用的mac 电脑自带的python版本可能会有问题，建议从python官网重新下载python，paddle 2.1.2支持python 3.6-python3.9；python 官网上的3.9 版本有两个型号，目前paddle 只支持inter 版的python3.9, 不支持universal 版的python3.9

**Comment by dingjiaweiww** [comment]
@huangbin2005 paddle 目前没有统一对arm 芯片进行支持，但支持是arm芯片的 mac M1系统

**Comment by wyq977** [comment]
@huangbin2005 好像这个[build](https://paddle-wheel.bj.bcebos.com/2.1.2/macos/macos-cpu-openblas/paddlepaddle-2.1.2-cp38-cp38-macosx_10_14_x86_64.whl) 无法支持mac M1

 > paddle 目前没有统一对arm 芯片进行支持，但支持是arm芯片的 mac M1系统

我猜你说的支持 “arm芯片的 mac M1” 是指paddle在rostta帮助下可以跑 但是还没有native build (for os-arm64), 想numpy就有https://anaconda.org/conda-forge/numpy/1.21.2/download/osx-arm64/numpy-1.21.2-py38hbf7bb01_0.tar.bz2
