### ISSUE TITLE
AssertionError can’t find your local ip {127.0.0.1} in args.servers and args.workers ips: {[‘192.168.xx.xx,192.168.xx.xx ’]}

### ISSUE THREAD

**Issue by xinyi-code** [PaddlePaddle/Paddle#34533]
Sorry to bother, I feeled confused when I tried to run my code on multi-cpus on different machines, but it occurred the problem.
my launch command is followed the file python/paddle/distributed/fleet/launch.py Same as below
fleetrun --servers="192.168.0.16:6170,192.168.0.17:6170" \
                --workers="192.168.0.16,192.168.0.17,192.168.0.16,192.168.0.17" \
                your_training_py (arg1 arg2 and all others)

**Comment by kuizhiqing** [comment]
It seems that your local ip did not auto detect correctly, to fix it, 

1. run with
`fleetrun --servers="192.168.0.16:6170,192.168.0.17:6170"
--workers="192.168.0.16,192.168.0.17,192.168.0.16,192.168.0.17"  --host=192.168.0.16` 
at machine 192.168.0.16 and similar for 192.168.0.17.

2. `export POD_IP=192.168.0.16` before command, the same for 192.168.0.17.

To understand why, please run the following script and show me the result,

import socket
socket.gethostbyname(socket.getfqdn(socket.gethostname()))

**Comment by xinyi-code** [comment]
> It seems that your local ip did not auto detect correctly, to fix it,
> 
> 1. run with
>    `fleetrun --servers="192.168.0.16:6170,192.168.0.17:6170" --workers="192.168.0.16,192.168.0.17,192.168.0.16,192.168.0.17"  --host=192.168.0.16`
>    at machine 192.168.0.16 and similar for 192.168.0.17.
> 2. `export POD_IP=192.168.0.16` before command, the same for 192.168.0.17.
> 
> To understand why, please run the following script and show me the result,
> 
> import socket
> socket.gethostbyname(socket.getfqdn(socket.gethostname()))

thank You for your reply. It helped a lot.
The output of the script is showed as blow

import socket
socket.gethostbyname(socket.getfqdn(socket.gethostname()))
127.0.0.1

**Comment by kuizhiqing** [comment]
Well, that's the problem, please use solution 1 or 2 above to fix it.

Further, please provide more information for us to fix it internally,
1. your os/platform version: ubuntu/centos or others
2. the result of *ifconfig*
3. the result of script below
 `import socket`
 `host_name = socket.gethostname()`
 `host_ip = socket.gethostbyname(host_name)`
 `host_name, host_ip`

thx

**Comment by xinyi-code** [comment]
1. ubuntu 18.04.1  LTS  
2.ifconfig
eth0: inet 192.168.130.xxx. netmask 255.255.248.xxx, broadcast:182.168.135.xxx
3. hostname:vm192-168-130-xxx.cloud.local. hostip:127.0.0.1
The machine is a server machine applied from jinshanyun, this information may be of some help.

**Comment by kuizhiqing** [comment]
Thank you, we will take it into consideration.
