### ISSUE TITLE
从paddle.fluid迁移到paddle.static有什么教程文档吗？

### ISSUE THREAD

**Issue by yeyupiaoling** [PaddlePaddle/Paddle#34550]
- PaddlePaddle 2.1.1

从paddle.fluid迁移到paddle.static有什么教程文档吗？

**Comment by DannyIsFunny** [comment]
你好，是有教学文档的
https://www.paddlepaddle.org.cn/documentation/docs/zh/2.0/guides/01_paddle2.0_introduction/migration_cn.html#banbenqianyigongju

**Comment by yeyupiaoling** [comment]
谢谢
