### ISSUE TITLE
ros中使用paddle

### ISSUE THREAD

**Issue by june12536** [PaddlePaddle/Paddle#34553]
就是那个我要是想在ros系统里面用paddle，以节点的形式启动paddleOCR文字识别的话，请问有什么推荐方案嘛
ros自带python版本为python2.7.12

**Comment by DannyIsFunny** [comment]
https://github.com/PaddlePaddle/PaddleOCR/blob/release%2F2.2/doc/doc_ch/whl.md
如果是ros python的话可以直接安装whl包，使用paddleocr

**Comment by june12536** [comment]
> https://github.com/PaddlePaddle/PaddleOCR/blob/release%2F2.2/doc/doc_ch/whl.md
> 如果是ros python的话可以直接安装whl包，使用paddleocr

thank you
