### ISSUE TITLE
Deploying models with multi-thread will raise MKLDNN error

### ISSUE THREAD

**Issue by OliverLPH** [PaddlePaddle/Paddle#34554]
**System information**
-PaddlePaddle version: develop(393a0b166a380e85550a639e603a7ff44c0a440e) or release/2.1 
-CPU: MKLDNN v2.2.1
-GPU: None
-OS Platform: ubuntu1604
-Python version: None
-Cmake orders
-C++version.txt
-API information
Note: You can get most of the information by running [summary_env.py](https://github.com/PaddlePaddle/Paddle/blob/develop/tools/summary_env.py). 
**To Reproduce**
reproduce procedure is same as https://github.com/PaddlePaddle/Paddle/issues/31992

cmake commands
```shell
cmake .. -DWITH_FLUID_ONLY=ON -DWITH_GPU=OFF -DWITH_TESTING=OFF -DCMAKE_BUILD_TYPE=Release -DON_INFER=ON -DWITH_INFERENCE_API_TEST=OFF -DWITH_MKL=ON -DWITH_MKLDNN=ON -DWITH_AVX=ON -DWITH_DISTRIBUTE=OFF -DWITH_STRIP=ON -DWITH_PYTHON=OFF
```

**Describe your current behavior**

* The first test
Run `./build/model_test --single_thread=true --single_instance=false --test_groups="1"`,  it does not case error.

* The second test
Run `./build/model_test --single_thread=true --single_instance=true --test_groups="1"`,  it does not case error.

* The third test
Run `./build/model_test --single_thread=false --single_instance=true --test_groups="1"`,  it will raise an error as followed
![image](https://user-images.githubusercontent.com/14963836/127851259-243345e0-2315-4fea-bb5c-9839c0072911.png)

this error might caused by https://github.com/PaddlePaddle/Paddle/pull/33549/files#diff-3363ff47a1f22a111386eeff77a8572f6618d7d0602ffe71e92ecf8682faa84eR2343

**Code to reproduce the issue**
**Other info / logs**

**Comment by lidanqing-vv** [comment]
Hi, @OliverLPH 可以汇总一下这个测试里的全部模型然后发到 dubox 吗？因为上次军才提这个issue的时候，只给了两个模型，其他的代码里注释掉了。Jacek只有两个模型，没法测test_group 3~9。
因为有好几个模型，估计size较大，可以直接发到dubox，然后分享链接，波兰团队方便直接下载，就不用我先下载再上传再转移了。非常感谢！

**Comment by baoachun** [comment]
@jczaja @lidanqing-intel Hi, I have re-executed the test program, and I found that there will be dnnl errors when config.mkldnn_enabled() is 0. 
<img width="591" alt="图片" src="https://user-images.githubusercontent.com/22114318/129690209-0909e15f-7351-4994-b78e-9100421b34d1.png">
<img width="1337" alt="图片" src="https://user-images.githubusercontent.com/22114318/129690088-7fbf544f-21bc-4f62-8847-f5927c4d7ce8.png">
Here is the log [without_mkldnn.log](https://github.com/PaddlePaddle/Paddle/files/6998254/without_mkldnn.log).

**Comment by lidanqing-vv** [comment]
Baoachun: Turn on MKLDNN, some models still crash, core dump.. but no dnnl::error such kind of errors show up
Jacek: Turn on MKLDNN, all models work well and no crash. Only when mkldnn OFF, some int8 models fail because int8 should not run with mkldnn OFF.
@lidanqing-intel  Investigate the gap

**Comment by baoachun** [comment]
> Baoachun: Turn on MKLDNN, some models still crash, core dump.. but no dnnl::error such kind of errors show up
> Jacek: Turn on MKLDNN, all models work well and no crash. Only when mkldnn OFF, some int8 models fail because int8 should not run with mkldnn OFF.
> @lidanqing-intel Investigate the gap

This is the crash log when mkldnn is turned on.
Link:https://dubox.com/s/1-I4LjktKo2n1r0ieS91Skg  Password:cbak

**Comment by lidanqing-vv** [comment]
Hi, I have tested with newest develop `f609ca379173de0be1e288a1832fd074b6c61587`,

Note 1, if you turn on mkldnn, you should also turn on IR optim as noted in the running log. So for enable mkldnn, all 10 models, last two params should be both 1, 1

Note 2, there is a bug in Test source code, `<` is wrongly writtent to `,` You need to change line 318
**From:**
```
 for (int i = 0; i , test_model_params.size(); i++) {
```
**To:**
```
 for (int i = 0; i < test_model_params.size(); i++) {
```

**Following command all passed.**
`./build/model_test --single_thread=true --single_instance=false --test_groups="1"`

**Following command all passed**
`./build/model_test --single_thread=false --single_instance=true --test_groups="1"`


**Following command also all passed**
`./build/model_test --single_thread=false --single_instance=true --test_groups="-1"`

@baoachun  你可以测了，谢谢！

**Comment by lidanqing-intel** [comment]
@baoachun  There is a bug in source code of the test. Change in line 318 to 
```
    for (int i = 0; i < test_model_params.size(); i++) {
```
Then test it again. I do not have the error anymore

**Comment by lidanqing-vv** [comment]
@OliverLPH  我这边测这个issue不存在了。
there is a bug in Test source code, `<` is wrongly writtent to `,` You need to change in model_test.cc line 318
**From:**
```
 for (int i = 0; i , test_model_params.size(); i++) {
```
**To:**
```
 for (int i = 0; i < test_model_params.size(); i++) {
```

**Following command all passed.**
`./build/model_test --single_thread=true --single_instance=false --test_groups="1"`

**Following command all passed**
`./build/model_test --single_thread=false --single_instance=true --test_groups="1"`


**Following command also all passed**
`./build/model_test --single_thread=false --single_instance=true --test_groups="-1"`

**Comment by jczaja** [comment]
@OliverLPH  I got a core dump from you . To use it I need to know SHA (identification of commit) and exact cmake flags and compiler version .

Please also tell me if core dump is for enabled mkldnn ( enable_mkldnn()  0 or 1 ) ?

**Comment by OliverLPH** [comment]
@jczaja hi, the core dump was created by following version, and the core dump is for enabled mkldnn=1 
commit: https://github.com/PaddlePaddle/Paddle/commit/0043fa8c2b36f63152797fe08fcfe8684f1448e0
version.txt is
```shell
GIT COMMIT ID: 0043fa8c2b36f63152797fe08fcfe8684f1448e0
WITH_MKL: ON
WITH_MKLDNN: ON
WITH_GPU: OFF
WITH_ROCM: OFF
CXX compiler version: 8.2.0
```
I used docker image to build paddle: paddlepaddle/paddle:latest-dev-cuda10.1-cudnn7-gcc82
cmake flags:
```
cmake .. -DPYTHON_EXECUTABLE:FILEPATH=/usr/local/bin/python3.7 -DPYTHON_INCLUDE_DIR:PATH=/usr/local/include/python3.7m -DPYTHON_LIBRARIES:FILEPATH=/usr/local/lib/libpython3.7m.so -DWITH_FLUID_ONLY=ON -DWITH_GPU=OFF -DWITH_TESTING=OFF -DCMAKE_BUILD_TYPE=Release -DON_INFER=ON -DWITH_INFERENCE_API_TEST=OFF -DWITH_MKL=ON -DWITH_MKLDNN=ON -DWITH_AVX=ON -DWITH_DISTRIBUTE=OFF -DWITH_STRIP=ON
```
And I upload my test paddle lib to baidu-bos, you may download from this link
```shell
https://paddle-qa.bj.bcebos.com/paddle-pipeline/Master_Cpu_Avx512_LinuxUbuntu_Gcc82_Mkl_Py37_Compile_H/0043fa8c2b36f63152797fe08fcfe8684f1448e0/paddle_inference.tgz
```

**Comment by lidanqing-vv** [comment]
Reproduce with docker Peihan suggested
```
log onto shanghai 6271 with sudo
service docker start
# You may need to do `docker rm paddle-test`
docker run --name paddle-test -v $PWD:/paddle --network=host -it registry.baidubce.com/paddlepaddle/paddle:latest-dev-cuda10.1-cudnn7-gcc82 /bin/bash
cd ../paddle/Isse_31992/ocr_demo_1/
bash build.sh
./build/model_test --single_thread=false --single_instance=false --test_groups=-1
```

@OliverLPH Hi, using the docker image and paddle inference lib you provided, I met this error. Is it the same error as you have ?

![image](https://user-images.githubusercontent.com/47151829/133645201-dd0314de-24c6-4c8d-b317-06706c31c6b0.png)

**Comment by OliverLPH** [comment]
@lidanqing-intel the problem I met is segmentation fault
you log looks like test data were corrupts?
<img width="933" alt="3bef61accb796cd063a33c88b3126cd2" src="https://user-images.githubusercontent.com/14963836/133732988-c56ae231-c460-47d5-9bde-cb783570a0dc.png">

**Comment by jczaja** [comment]
@OliverLPH Using SHA you gave I was able to reproduce a problem (occasionally) and it is Segmentation Fault. So I'm trying to fix it

**Comment by baoachun** [comment]
@jczaja 
Hi, this issue requires to be fixed until 21th evening, all the PRs since 22th will not be able to merge to the 2.2 branch.

**Comment by jczaja** [comment]
@baoachun Just want to write that I'm still working on this issue so it is not solved yet.

**Comment by baoachun** [comment]
@jczaja @lidanqing-intel 
Hi, this problem may be left to version 2.2,  is there an approximate time that this issue could be solved?

**Comment by jczaja** [comment]
@baoachun No estimation known (I'm discovering new problems and fixing them one by one).

**Comment by jczaja** [comment]
@baoachun  I just got fix that fixes this issue (tested on my local set up) . Please test if this resolved this issue : https://github.com/PaddlePaddle/Paddle/pull/35884/

**Comment by baoachun** [comment]
> @baoachun I just got fix that fixes this issue (tested on my local set up) . Please test if this resolved this issue : #35884

@OliverLPH  沛含，能帮忙测下吗？

**Comment by OliverLPH** [comment]
@jczaja 
Hi, I have verified https://github.com/PaddlePaddle/Paddle/pull/35884 pr with develop branch, the issue still exists.
But I found some new situation:

for model group 4, when enable mkldnn, multi-thread and multi-instance, if you change `line  188`
![image](https://user-images.githubusercontent.com/14963836/134631756-96bebd47-f003-4326-88a3-ba3901937460.png)

1. if one sample only predict once, it won't crash and works well
2. if one sample repeat predict 10 times, it will encounter 
![14040f75f01a1b7c3d3dbd6d60e47666](https://user-images.githubusercontent.com/14963836/134632771-7ae2c658-5204-49fb-9849-e2db1ce68f2c.png)
3. if one sample repeat predict 100 times, it will get segmentation fault


but for model group 5, 6
no matter `repeat times` set to 1 or 10, it will still get segmentation fault



here is my test commit log
![image](https://user-images.githubusercontent.com/14963836/134633034-cd6f44ba-dab6-4ec9-84f5-8cb94bd30370.png)

**Comment by jczaja** [comment]
@OliverLPH  I wasn't able to reproduce you new findings **so** far. I'm using 485b387d0db2b7f4592a2b13f9c68acba5fe7a60 (Merged PR mentioned earlier). So Please write:
1) What is the platform (CPU) you are using where issue occurs?
2) Please attach your model_test.cc file , so I can compare if no differences is there.

**Comment by OliverLPH** [comment]
@jczaja 
Hi, I will also try https://github.com/PaddlePaddle/Paddle/commit/485b387d0db2b7f4592a2b13f9c68acba5fe7a60 on my environment, since my last test is by merge https://github.com/PaddlePaddle/Paddle/pull/35884 locally.
1. cpu info: Intel(R) Xeon(R) Gold 6271C CPU @ 2.60GHz
2. here is the model_test.cc [model_test.txt](https://github.com/PaddlePaddle/Paddle/files/7230837/model_test.txt) I used

**Comment by lidanqing-vv** [comment]
@baoachun Hi since reproducing it once take a lot of time, there is no timeline for this issue dicided now.

**Comment by jczaja** [comment]
@baoachun , @lidanqing-intel  To be on the same page. I do not have reproduction on my setups after 485b387 (fixes done so far for this issue) , so timeline will be provided once I reproduce a problem.

**Comment by jczaja** [comment]
@OliverLPH I understand that you use mainly Release build of PaddlePaddle. Do you have issue reproduced when using Debug build?

**Comment by OliverLPH** [comment]
@jczaja 
I think Paddle didn't support debug mode before? I will try build it on debug and reproduce this issue

**Comment by jczaja** [comment]
@OliverLPH  By debug mode I mean -DCMAKE_BUILD_TYPE=Debug in cmake command line and **removed** -DWITH_STRIP=ON

**Comment by OliverLPH** [comment]
> @OliverLPH By debug mode I mean -DCMAKE_BUILD_TYPE=Debug in cmake command line and **removed** -DWITH_STRIP=ON

OK, I will try this cmake command

**Comment by jczaja** [comment]
@OliverLPH  I just want to let you know that I got stable reproduction of issue when test_groups="4" , so I can investigate the problem. Thanks for hints

**Comment by jczaja** [comment]
@OliverLPH Just to let you know where We are with this. Problem was diagnosed and I'm implementing solution(WIP). To temporarily avoid problem you can increase PaddlePaddle cache capacity by adding(inside CreatePredictor, ~110):
config.SetMkldnnCacheCapacity(10);

**Comment by OliverLPH** [comment]
@jczaja 
Many thanks for your suggestions.
I tried to set `config.SetMkldnnCacheCapacity(110)` and it works fine in all models with no core dumped.
looking forward to your new solution

**Comment by yaomichael** [comment]
notes from 5/20 meeting

need to monitor any potential side effects of large cache. so keep it open for a while.
