### ISSUE TITLE
安装时出现RuntimeError

### ISSUE THREAD

**Issue by lizhipeng-bit** [PaddlePaddle/Paddle#34566]
RuntimeError: (PreconditionNotMet) The third-party dynamic library (cudnn64_7.dll) that Paddle depends on is not configured correctly. (error code is 126)
  Suggestions:
  1. Check if the third-party dynamic library (e.g. CUDA, CUDNN) is installed correctly and its version is matched with paddlepaddle you installed.
  2. Configure third-party dynamic library environment variables as follows:
  - Linux: set LD_LIBRARY_PATH by `export LD_LIBRARY_PATH=...`
  - Windows: set PATH by `set PATH=XXX; (at C:\home\workspace\Paddle_release2\paddle\fluid\platform\dynload\dynamic_loader.cc:265)

**Comment by jiweibo** [comment]
您好，您的环境中需要安装cudnn哈，请从nvidia官网下载对应的cudnn版本， 并将其解压到cuda安装的目录哈

**Comment by lizhipeng-bit** [comment]
> 您好，您的环境中需要安装cudnn哈，请从nvidia官网下载对应的cudnn版本， 并将其解压到cuda安装的目录哈
按照官网   python -m pip install paddlepaddle-gpu -i https://mirror.baidu.com/pypi/simple    这种方式安装的；下载了cudnn，应该解压到哪里，没有找到对应的cuda的安装目录；环境变量要怎么配置。

**Comment by jiweibo** [comment]
windows环境下，您首先需要安装nvidia driver（默认您应该已经装了的），之后需要安装cuda。

cuda安装完后，需要安装cudnn。 cudnn默认是安装到cuda的目录下的，您可以去NV官网看下安装教程

**Comment by lizhipeng-bit** [comment]
Cuda 和 cudnn 都已经按照要求装好，
装paddle的时候也没有出现警告信息
但是，验证时还是出现错误

应该怎么解决

发送自 Windows 10 版邮件应用

发件人: Wilber
发送时间: 2021年8月4日 13:51
收件人: PaddlePaddle/Paddle
抄送: xinnian-max-eng; Author
主题: Re: [PaddlePaddle/Paddle] 安装时出现RuntimeError (#34566)

windows环境下，您首先需要安装nvidia driver（默认您应该已经装了的），之后需要安装cuda。
cuda安装完后，需要安装cudnn。 cudnn默认是安装到cuda的目录下的，您可以去NV官网看下安装教程
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by dingjiaweiww** [comment]
验证的时候报什么错误呢
