### ISSUE TITLE
[论文复现赛-第四期]windows下进行dataloader调用时，报错退出

### ISSUE THREAD

**Issue by hrdwsong** [PaddlePaddle/Paddle#34581]
- 版本、环境信息：
Paddle version: 2.1.0
Paddle With CUDA: True
OS: Windows 10
Python version: 3.7.10
CUDA version: 11.1.74
Build cuda_11.1.relgpu_drvr455TC455_06.29069683_0
cuDNN version: None.None.None
Nvidia driver version: 461.72
- 训练信息
    1）单机，单卡
    2）显存信息 8GB
    3）Operator信息
使用CIFAR数据集，用dataloader调用时，报以下错误：
W0803 18:14:36.035079 16012 device_context.cc:404] Please NOTE: device: 0, GPU Compute Capability: 8.6, Driver API Version: 11.2, Runtime API Version: 11.2
W0803 18:14:36.043030 16012 device_context.cc:422] device: 0, cuDNN Version: 8.1.

Process finished with exit code -1073741819 (0xC0000005)

我试了下paddle官方教程（https://www.paddlepaddle.org.cn/documentation/docs/zh/tutorial/cv_case/image_search/image_search.html）
进行训练，在windows下仍然报以上错误。
该报错在linux下不存在，使用cpu运行代码也可以正常运行。应该与windows环境下，使用GPU导致了某处BUG。
烦请协助解决下，感谢！

**Comment by heavengate** [comment]
看你日志里并没有报错，有详细日志么
