### ISSUE TITLE
导入paddle报‘No module named 'paddle.fluid.core_noavx’错误

### ISSUE THREAD

**Issue by yeyupiaoling** [PaddlePaddle/Paddle#34591]
- PaddlePaddle CPU 2.1.1
 - Python 3.7
 - Windows 10

错误日志：
```
  File "C:\Anaconda3\envs\PaddlePaddle\lib\site-packages\paddle\fluid\core.py", line 316, in <module>
    from .core_noavx import *
ModuleNotFoundError: No module named 'paddle.fluid.core_noavx'
```

**Comment by zhwesky2010** [comment]
@yeyupiaoling 您好，请问有其他报错信息吗？这里的报错内容是加载core_noavx失败了，可能是机器的CPU不支持avx指令集，但需要更多的报错内容才能详细定位

**Comment by yeyupiaoling** [comment]
@zhouwei25 没有了，导入paddle的是就报这个错误了，有2.1.1，Python 3.7 的noavx安装包吗？

**Comment by zhwesky2010** [comment]
@yeyupiaoling conda的没拆分avx，PIP的有no avx的介绍，https://www.paddlepaddle.org.cn/documentation/docs/zh/install/pip/windows-pip.html

**Comment by yeyupiaoling** [comment]
@zhouwei25 我的就是anaconda的，这么也会这样呢？

**Comment by zhwesky2010** [comment]
> @zhouwei25 我的就是anaconda的，这么也会这样呢？

可以看看 `C:\Anaconda3\envs\PaddlePaddle\lib\site-packages\paddle\fluid\` 里面是不是没有core_noavx这个文件，或者重新安装下

**Comment by yeyupiaoling** [comment]
好的。我试试

**Comment by zhwesky2010** [comment]
> @zhouwei25 我的就是anaconda的，这么也会这样呢？

conda的包里只有core_avx，编译时没有发布no avx版本，所以只能用PIP的版本

**Comment by yeyupiaoling** [comment]
原来是这样，好的，谢谢。

**Comment by sellinaxmj** [comment]
@PaddlePM 
paddlepaddle 2.3.0 python3.6.2 windows7环境下
运行没有问题，请问各位用pyinstaller打包后运行打包后的exe,也是类似的错误关于paddle.fluid.core_noavx’错误

paddle\fluid\core.py 365 
paddle\fluid\core.py 313
ImportError:cannot import name core_noavx
