### ISSUE TITLE
do not use awk grep etc. to get env infomation

### ISSUE THREAD

**Issue by melyseengit** [PaddlePaddle/Paddle#34597]
paddlepaddle 2.1.1
$PYTHON_HOME/lib/python3.6/site-packages/paddle/fluid/core.py

```
# line 71
def avx_supported():
```

```
# line 211
def get_libc_ver()
```

sometimes python itself is linked with higher glibc (not using the system glibc), so use subprocess to call these elf (eg. awk/grep) may not work properly, it might cause segv fault so paddle would complain that avx is not supported when it did support in cpu.

**Comment by zhiqiu** [comment]
T

> paddlepaddle 2.1.1
> $PYTHON_HOME/lib/python3.6/site-packages/paddle/fluid/core.py
> 
> ```
> # line 71
> def avx_supported():
> ```
> 
> ```
> # line 211
> def get_libc_ver()
> ```
> 
> sometimes python itself is linked with higher glibc (not using the system glibc), so use subprocess to call these elf (eg. awk/grep) may not work properly, it might cause segv fault so paddle would complain that avx is not supported when it did support in cpu.

Thanks for your advise, would you please give us an example of  the`segv` mentioned above to check it ?

**Comment by melyseengit** [comment]
Cool. try `export LD_LIBRARY_PATH=path/glibc2.18/lib:$LD_LIBRARY_PATH; /bin/bash`  where the elf `/bin/bash` is compiled with `glibc2.17 or anything not glibc2.18`. you could get the segv.
`/opt/compiler/gcc-8.2/lib64/ld-2.18.so /bin/bash` could get the `/bin/bash` run as expected. yet in paddle it's impossible to write such code to specify the ld.so when calling the elf.
so it's a problem related with global env var LD_LIBRARY_PATH.

why I care this so much? let's say I got a python compiled with `glibc2.18` when my system has `glibc2.17`, so for some reason like I need to call some dynamic library compiled also by `glibc2.18` in python, anyway  I need to `export LD_LIBRARY_PATH to include glibc2.18`, after which paddle would complain things like `avx not supported` when it is well supported in my machine. calling elf is not a nice way to detect the env anyway. 

another problem related with the same issue is https://github.com/NVIDIA/libnvidia-container/issues/142
