### ISSUE TITLE
jetsno nano 多进程预测 copy_from_cpu报错

### ISSUE THREAD

**Issue by QQ39272490** [PaddlePaddle/Paddle#34604]
jetson nano 2G 版本，想把预测独立进程。写了一个TPaddlex 进程类，我把全部代码放出来了直接运行python multipro.py
[program.zip](https://github.com/PaddlePaddle/Paddle/files/6929688/program.zip)

![5JQ}9FBM_ ~R~YYK~$HF71V](https://user-images.githubusercontent.com/2766645/128146322-4aab56c0-cbc1-4fd9-b79f-86c9bebba67d.png)
![@06{Q3IT}$OS N_J91%WNR2](https://user-images.githubusercontent.com/2766645/128146353-43dd6fb2-77af-471e-bc8a-2b15ed40a06b.png)

**Comment by fengxiaoshuai** [comment]
由于cuda不支持fork形式生成新进程，所以paddle框架也不支持，如果必须使用多进程的话，可以考虑直接利用shell脚本起多个进程。
