### ISSUE TITLE
NPU编译后执行加载预训练模型(ernie)报错：'PosixPath' object has no attribute 'tell'

### ISSUE THREAD

**Issue by ABAPPLO** [PaddlePaddle/Paddle#34614]
- 版本、环境信息：
    1）PaddlePaddle版本：2.1.2 在昇腾编译后安装
          编译doc：https://www.paddlepaddle.org.cn/documentation/docs/zh/guides/09_hardware_support/npu_docs/paddle_install_cn.html
    2）处理器：鲲鹏920
    3）NPU：ascent 310
    4）系统环境：
          操作系统：：4.14.0-115.el7a.0.1.aarch64
          python： 3.7.5
          CANN： 20.3（3.3.0）
- 训练信息
    1）单机多卡
    2）显存信息： 2703 / 8192 *4
- 复现信息：
   编译后的paddle用于ernie的文本编码
   `pip install paddle-ernie`
   ```
   import numpy as np
   import paddle as P
   from ernie.tokenizing_ernie import ErnieTokenizer
   from ernie.modeling_ernie import ErnieModel
   model = ErnieModel.from_pretrained('ernie-1.0')   
   model.eval()
   tokenizer = ErnieTokenizer.from_pretrained('ernie-1.0')

   ids, _ = tokenizer.encode('hello world')
   ids = P.to_tensor(np.expand_dims(ids, 0))  # insert extra `batch` dimension
   pooled, encoded = model(ids)                 # eager execution
   print(pooled.numpy())                        # convert  results to numpy

- 报错信息如下
  ```
    import imp
    Traceback (most recent call last):
    File "aete.py", line 5, in <module>
    model = ErnieModel.from_pretrained('ernie-1.0')   
    File "/usr/local/python3.7.5/lib/python3.7/site-packages/ernie/modeling_ernie.py", line 293, in from_pretrained
    m = P.load(state_dict_path)
    File "/usr/local/python3.7.5/lib/python3.7/site-packages/paddle/framework/io.py", line 925, in load
    with _open_file_buffer(path, 'rb') as f:
    File "/usr/local/python3.7.5/lib/python3.7/site-packages/paddle/fluid/io.py", line 111, in _open_file_buffer
    return _buffer_reader(path_or_buffer)
    File "/usr/local/python3.7.5/lib/python3.7/site-packages/paddle/fluid/io.py", line 86, in __init__
    self.initial_tell = self.buffer.tell()
    AttributeError: 'PosixPath' object has no attribute 'tell'

**Comment by hbwx24** [comment]
目前初步定位是由于save/load使用PosixPath的问题，建议用普通字符串路径代替`PosixPath `，后续会视情况支持PosixPath。

**Comment by ABAPPLO** [comment]
好的

**Comment by junfeizhu** [comment]
> 目前初步定位是由于save/load使用PosixPath的问题，建议用普通字符串路径代替`PosixPath `，后续会视情况支持PosixPath。

你好，我遇到了同样的问题，请问能说说具体怎么代替吗？不是很懂

**Comment by Smpests** [comment]
版本2.2.0遇到相同问题，修改该版本ernie\modeling_ernie.py的293行：m = P.load(state_dict_path)改为m = P.load(str(state_dict_path))可解决。参考链接 #https://github.com/PaddlePaddle/ERNIE/issues/765

**Comment by mavisyyc** [comment]
> 

仍旧报那个错 没有解决啊

**Comment by mavisyyc** [comment]
> 版本2.2.0遇到相同问题，修改该版本ernie\modeling_ernie.py的293行：m = P.load(state_dict_path)改为m = P.load(str(state_dict_path))可解决。参考链接 #[PaddlePaddle/ERNIE#765](https://github.com/PaddlePaddle/ERNIE/issues/765)

仍旧报那个错 没有解决啊
