### ISSUE TITLE
version2.1.1 反传失败；Leaf node that doesn't stop gradient can't use inplace operator

### ISSUE THREAD

**Issue by QingquanBao** [PaddlePaddle/Paddle#34633]
版本 2.1.1

## Demo
这展示了一种使用场景： 先开出一些内存，然后逐步填入tensor，但在2.1.1的版本中无法回传梯度。
<img width="1015" alt="截屏2021-08-05 下午2 45 42" src="https://user-images.githubusercontent.com/58896895/128305040-1c60206a-7687-4fb4-94ee-9b2acc90f293.png">
<img width="994" alt="截屏2021-08-05 下午2 45 51" src="https://user-images.githubusercontent.com/58896895/128305078-ea83537b-339f-4e58-aefe-a8d9079312c0.png">

## 原型
https://github.com/QingquanBao/PCA-GM/blob/thinkmatch/utils_pdl/sinkhorn.py 
第69-70行的操作，在2.1.1的版本中此行便无法运行。

我暂时唯一想到的替代方案就是不断concat，但是这样明显比开内存要更耗时，不知有无别的解决方案？或者说框架内需要想办法支持一下这种操作？

**Comment by chenwhql** [comment]
感谢反馈，这里是个bug，我们修复一下

**Comment by QingquanBao** [comment]
> 感谢反馈，这里是个bug，我们修复一下

您好，请问这个bug修复的如何了？ 非常感谢！！
同时请问另一个[bug](https://github.com/PaddlePaddle/Paddle/issues/34419) 是否同时修复了,谢谢 ！
