### ISSUE TITLE
单机多卡训练报错：NotImplementedError: (Unimplemented) Place CUDAPlace(0) is not supported

### ISSUE THREAD

**Issue by helen88** [PaddlePaddle/Paddle#34639]
环境：cpu和gpu版本的paddle都有：
paddlepaddle                  2.0.0rc1                 pypi_0    pypi
paddlepaddle-gpu          2.1.0.post101            pypi_0    pypi

报错信息：
Traceback (most recent call last):
  File "mnist_cnn_bapi.py", line 118, in <module>
    model = CNNModel()
  File "/mnt/zhanghuan05/pp2/fleetx/mnist_cnn_model.py", line 18, in __init__
    self.conv1 = paddle.nn.Conv2D(in_channels=1, out_channels=20, kernel_size=5, stride=1, padding=0)
  File "/mnt/opt/anaconda2/envs/pp2/lib/python3.6/site-packages/paddle/nn/layer/conv.py", line 646, in __init__
    data_format=data_format)
  File "/mnt/opt/anaconda2/envs/pp2/lib/python3.6/site-packages/paddle/nn/layer/conv.py", line 135, in __init__
    default_initializer=_get_default_param_initializer())
  File "/mnt/opt/anaconda2/envs/pp2/lib/python3.6/site-packages/paddle/fluid/dygraph/layers.py", line 412, in create_parameter
    default_initializer)
  File "/mnt/opt/anaconda2/envs/pp2/lib/python3.6/site-packages/paddle/fluid/layer_helper_base.py", line 374, in create_parameter
    **attr._to_kwargs(with_initializer=True))
  File "/mnt/opt/anaconda2/envs/pp2/lib/python3.6/site-packages/paddle/fluid/framework.py", line 3193, in create_parameter
    initializer(param, self)
  File "/mnt/opt/anaconda2/envs/pp2/lib/python3.6/site-packages/paddle/fluid/initializer.py", line 364, in __call__
    stop_gradient=True)
  File "/mnt/opt/anaconda2/envs/pp2/lib/python3.6/site-packages/paddle/fluid/framework.py", line 3223, in append_op
    kwargs.get("stop_gradient", False))
  File "/mnt/opt/anaconda2/envs/pp2/lib/python3.6/site-packages/paddle/fluid/dygraph/tracer.py", line 45, in trace_op
    not stop_gradient)
NotImplementedError: (Unimplemented) Place CUDAPlace(0) is not supported. Please check that your paddle compiles with WITH_GPU, WITH_XPU or WITH_ASCEND_CL option or check that your train process set the correct device id if you use Executor. (at /paddle/paddle/fluid/platform/device_context.cc:88)
  [operator < gaussian_random > error]

自定义的网络：
class CNNModel(paddle.nn.Layer):
    """
    paddle CNN model
    """

    def __init__(self):
   
        super(CNNModel, self).__init__()
        self.conv1 = paddle.nn.Conv2D(in_channels=1, out_channels=20, kernel_size=5, stride=1, padding=0)
        self.max_pool1 = paddle.nn.MaxPool2D(kernel_size=2, stride=2)
        self.conv2 = paddle.nn.Conv2D(in_channels=20, out_channels=50, kernel_size=5, stride=1)
        self.max_pool2 = paddle.nn.MaxPool2D(kernel_size=2, stride=2)
        self.linear1 = paddle.nn.Linear(in_features=800, out_features=50)
        self.linear2 = paddle.nn.Linear(in_features=50, out_features=10)

    def forward(self, x):
 
        x = self.conv1(x)
        x = F.relu(x)
        x = self.max_pool1(x)

        x = self.conv2(x)
        x = F.relu(x)
        x = self.max_pool2(x)

        x = paddle.flatten(x, start_axis=1, stop_axis=-1)
        x = self.linear1(x)
        x = F.relu(x)
        x = self.linear2(x)
        return x

**Comment by cryoco** [comment]
您好，可以检查下gpu驱动和cuda是否正确安装

**Comment by johnyanccer** [comment]
碰到同样的错误提示
NotImplementedError: (Unimplemented) Place CUDAPlace(0) is not supported. Please check that your paddle compiles with WITH_GPU, WITH_XPU or WITH_ASCEND_CL option or check that your train process set the correct device id if you use Executor. (at /paddle/paddle/fluid/platform/device_context.cc:88)
[operator < uniform_random > error]
单机单卡训练正常，安装完成后测试，import paddle ， paddle.utils.run_check()

Running verify PaddlePaddle program ...
W0821 14:49:41.777092 2595 device_context.cc:404] Please NOTE: device: 0, GPU Compute Capability: 8.6, Driver API Version: 11.4, Runtime API Version: 11.2
W0821 14:49:41.779155 2595 device_context.cc:422] device: 0, cuDNN Version: 8.1 .
PaddlePaddle works well on 1 GPU.
W0821 14:49:43.047895 2595 parallel_executor.cc:601] Cannot enable 'P2P' access from 0 to 1
W0821 14:49:43.047909 2595 parallel_executor.cc:601] Cannot enable 'P2P' access from 1 to 0
W0821 14:49:44.378496 2595 fuse_all_reduce_op_pass.cc:76] Find all_reduce operators: 2.
To make the speed faster, some all_reduce ops are fused during training, after fusion, the number of all_reduce ops is 2.
PaddlePaddle works well on 2 GPUs.
PaddlePaddle is installed successfully! Let's start deep learning with PaddlePaddle now.

**Comment by johnyanccer** [comment]
> 您好，可以检查下gpu驱动和cuda是否正确安装

碰到同样的错误提示
NotImplementedError: (Unimplemented) Place CUDAPlace(0) is not supported. Please check that your paddle compiles with WITH_GPU, WITH_XPU or WITH_ASCEND_CL option or check that your train process set the correct device id if you use Executor. (at /paddle/paddle/fluid/platform/device_context.cc:88)
[operator < uniform_random > error]
单机单卡训练正常，安装完成后测试，import paddle ， paddle.utils.run_check()

Running verify PaddlePaddle program ...
W0821 14:49:41.777092 2595 device_context.cc:404] Please NOTE: device: 0, GPU Compute Capability: 8.6, Driver API Version: 11.4, Runtime API Version: 11.2
W0821 14:49:41.779155 2595 device_context.cc:422] device: 0, cuDNN Version: 8.1 .
PaddlePaddle works well on 1 GPU.
W0821 14:49:43.047895 2595 parallel_executor.cc:601] Cannot enable 'P2P' access from 0 to 1
W0821 14:49:43.047909 2595 parallel_executor.cc:601] Cannot enable 'P2P' access from 1 to 0
W0821 14:49:44.378496 2595 fuse_all_reduce_op_pass.cc:76] Find all_reduce operators: 2.
To make the speed faster, some all_reduce ops are fused during training, after fusion, the number of all_reduce ops is 2.
PaddlePaddle works well on 2 GPUs.
PaddlePaddle is installed successfully! Let's start deep learning with PaddlePaddle now.

**Comment by dingjiaweiww** [comment]
@johnyanccer 打印结果显示PaddlePaddle is installed successfully! Let's start deep learning with PaddlePaddle now.，说明paddle已经安装成功，检查下cuda 是否安装正确吧

**Comment by Avalon244** [comment]
请问一下后续解决了么？我也是参考官方文档自建了网络模型，也是在模型建立时报了这个错误 @helen88

**Comment by Avalon244** [comment]
> 请问一下后续解决了么？我也是参考官方文档自建了网络模型，也是在模型建立时报了这个错误 @helen88
试了下按照#35054里的方法可以正常运行了
