### ISSUE TITLE
core dump when making inference

### ISSUE THREAD

**Issue by MsFive5** [PaddlePaddle/Paddle#3464]
Got this error when making an inference using paddle

```
WARNING: Logging before InitGoogleLogging() is written to STDERR
F0814 16:02:02.693090 32322 ClassRegistrar.h:65] Check failed: mapGet(type, creatorMap_, &creator) Unknown class type: data
*** Check failure stack trace: ***
Aborted (core dumped)
```

Here is how I write reader and inference

```python
def reader(query_seg, word_dict):
    UNK_ID = word_dict["<UNK>"]
    for line in f:
        word_ids = [
            word_dict.get(w, UNK_ID)
            for w in query_seg.split()
        ]
        yield word_ids

def infer(query_seg, model_path, label_dict_path, word_dict_path):
    word_dict = load_dict(word_dict_path)
    label_reverse_dict = load_reverse_dict(label_dict_path)
    dict_dim = len(word_dict)
    class_num = len(label_reverse_dict)
    topology = stacked_lstm_net
    prob_layer = topology(dict_dim, class_num, is_infer=True)
    parameters = paddle.parameters.Parameters.from_tar(
        gzip.open(model_path, "r"))
   inferer = paddle.inference.Inference(
        output_layer=prob_layer, parameters=parameters)
    test_vector = reader(query_seg, word_dict)
    probs = inferer.infer(input=test_vector, field=["value"])
    label = label_reverse_dict[prob.argmax()]
    return label
```

Found out that core dumped happens here
```
 inferer = paddle.inference.Inference(
        output_layer=prob_layer, parameters=parameters)
```

I write this inferer the same as the demo. Please help!

**Comment by typhoonzero** [comment]
Try change your reader implementation to:

```
def reader(query_seg, word_dict):
    def reader_generator():
        UNK_ID = word_dict["<UNK>"]
        for line in f:
            word_ids = [
                word_dict.get(w, UNK_ID)
                for w in query_seg.split()
            ]
            yield word_ids
    return reader_generator
```

**Comment by typhoonzero** [comment]
Well it seems that we should check the type of `input` at https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/v2/inference.py#L48  for better debugging this kind of errors.

**Comment by MsFive5** [comment]
I tried as suggested. But the same problem persists.

def reader(query_seg, word_dict):
    def reader_generator(query_seg, word_dict):
        UNK_ID = word_dict["<UNK>"]
        for line in f:
            word_ids = [
                word_dict.get(w, UNK_ID)
                for w in query_seg.split()
            ]
        yield word_ids
    return reader_generator

def infer(query_seg, model_path, label_dict_path, word_dict_path):
    word_dict = load_dict(word_dict_path)
    label_reverse_dict = load_reverse_dict(label_dict_path)
    dict_dim = len(word_dict)
    class_num = len(label_reverse_dict)
    prob_layer = stacked_lstm_net(dict_dim, class_num, is_infer=True)
    parameters = paddle.parameters.Parameters.from_tar(
        gzip.open(model_path, "r"))
    inferer = paddle.inference.Inference(
        output_layer=prob_layer, parameters=parameters)
    test_vector = reader(query_seg, word_dict)
    probs = inferer.infer(input=test_vector, field=["value"])
    label = label_reverse_dict[prob.argmax()]
    return label

**Comment by typhoonzero** [comment]
Sorry，forgot in `probs = inferer.infer(input=test_vector, field=["value"])` input should be an iteratable object and each value itered must be a batch of data. `test_vector` must be a vector of input data. In your case [test_vector] would be fine.

**Comment by MsFive5** [comment]
changed as suggested. but the problem persists.
def reader(query_seg, word_dict):
    def reader_generator(query_seg, word_dict):
        UNK_ID = word_dict["<UNK>"]
        word_ids = [
            word_dict.get(w, UNK_ID)
            for w in query_seg.split()
            ]
        yield word_ids
    return reader_generator

def infer(query_seg, model_path, label_dict_path, word_dict_path):
    word_dict = load_dict(word_dict_path)
    label_reverse_dict = load_reverse_dict(label_dict_path)
    dict_dim = len(word_dict)
    class_num = len(label_reverse_dict)
    prob_layer = stacked_lstm_net(dict_dim, class_num, is_infer=True)
    parameters = paddle.parameters.Parameters.from_tar(
        gzip.open(model_path, "r"))
    inferer = paddle.inference.Inference(
        output_layer=prob_layer, parameters=parameters)
    test_vector = reader(query_seg, word_dict)
    probs = inferer.infer(input = [test_vector], field=["value"])
    label = label_reverse_dict[prob.argmax()]
    return label
Please help!! Thanks a lot!

**Comment by typhoonzero** [comment]
@MsFive5 which version are you using? Are you using the latest develop branch? This seems like a recent bug.

**Comment by MsFive5** [comment]
I installed paddle.v2 about two weeks ago.
How can I get the latest version?

**Comment by typhoonzero** [comment]
Found out you need to do `paddle.init()` at the beginning.
