### ISSUE TITLE
请问python如何后台运行notebook文件

### ISSUE THREAD

**Issue by guojiahuiEmily** [PaddlePaddle/Paddle#34657]
aistudio.baidu.com导出的notebook文件，后缀为ipynb，请问如何用python运行此文件，直至文件代码全部自动运行完毕。

类似于aistudio中的后台运行任务功能。

**Comment by juncaipeng** [comment]
此非paddle相关issue，运行ipynb文件请参考：https://blog.csdn.net/laobai1015/article/details/99570447
