### ISSUE TITLE
主页折叠疑似有问题

### ISSUE THREAD

**Issue by jhcgt4869** [PaddlePaddle/Paddle#34650]
地址：https://www.paddlepaddle.org.cn/ppde
浏览器：edge
情况
![e0192cf8747d44c2c8bf96bbdbbfab8](https://user-images.githubusercontent.com/61859193/128349951-c28f89b5-0f45-4ecb-94bf-51723f9c9125.png)
相关学习群提供的希望验证一下然后处理一下

**Comment by qiceng** [comment]
感谢，您的反馈，已经在处理中
