### ISSUE TITLE
【论文复现】在训练中出现OSError: [Errno 24]  Too many open files

### ISSUE THREAD

**Issue by skingorz** [PaddlePaddle/Paddle#34679]
- 版本、环境信息：
    1）PaddlePaddle版本：2.1.1
    2）GPU：3090，CUDA11.2，cudnn8.2
    3）Ubuntu 18.04.4 LTS, python 3.7

- 训练信息
    1）单机，单卡
    2）24G
    3）训练到一定的epoch会出现这个问题，使用python3.9训练到第14个epoch结束后出现，使用python3.7训练到第28个epoch结束后出现，修改增大ulimit -n可以解决这个问题，但是paddle应该需要一个内置的这种功能吧
![2e2653fff9daf469cc71bcadbb7b59c](https://user-images.githubusercontent.com/36142776/128505357-9229cf8b-51d8-49f1-a50d-cf42916c42b4.png)

**Comment by juncaipeng** [comment]
你是使用paddle哪个版本？如果是在reader中打开了文件，建议尽量用完就关闭。

**Comment by skingorz** [comment]
> 你是使用哪个版本？如果是在阅读器中打开了文件，建议尽量用完就关闭。

paddle2.1.1，应该没有用reader打开文件， 而且训练过程中只有Dataset初始化时候读取过一次数据文件

**Comment by juncaipeng** [comment]
是否方便将代码贴上来看下具体问题。

**Comment by skingorz** [comment]
> 是否方便将代码贴上来看下具体问题。

具体是要哪部分代码呢，分散在不同的文件里了，等之后我把代码上传到GitHub然后贴一下链接吧

**Comment by skingorz** [comment]
> 是否方便将代码贴上来看下具体问题。

https://github.com/skingorz/prototypeNet-paddle/blob/main/tools/train.py
在90行会报错

**Comment by juncaipeng** [comment]
好的，我看下你的代码。

**Comment by juncaipeng** [comment]
@skingorz   这个问题可能是多线程操作一个文件导致，你也试了可以通过ulimit -n 解决。从paddle来看，可以尝试train_loader的线程数设置小点？我再找专门负责这块的同学来分析一下。

**Comment by heavengate** [comment]
可以试下Paddle 2.1.2版本，2.1.1版本之前有个内存泄漏问题
