### ISSUE TITLE
【论文复现】 bug: TypeError：can't pickle Tensor objects

### ISSUE THREAD

**Issue by skingorz** [PaddlePaddle/Paddle#34688]
版本、环境信息：
   1）PaddlePaddle版本：2.1.2
   2）GPU：3090，CUDA11.2，cudnn8.2
   3）Ubuntu 18.04.4 LTS, python 3.7

训练信息
   1）单机，单卡
   2）24G
   3）当DataLoader中的use_shared_memory设置成False时，当DataLoader生成的子进程调用paddle.vision.transforms.ToTensor会触发TypeError：can't pickle Tensor objects

![670c27df2bff80251edf39dd674630a](https://user-images.githubusercontent.com/36142776/128600151-d1bfce52-de97-44e5-ad40-e375c12f1213.png)

**Comment by zhangting2020** [comment]
这个问题是aistudio上出现的吗？我看到一个类似的问题 #34451

**Comment by skingorz** [comment]
> 这个问题是aistudio上出现的吗？我看到一个类似的问题 #34451

没有，在本地服务器出现的问题，不过之前在aistudio上好像也遇到了但是没太注意

**Comment by zhangting2020** [comment]
> > 这个问题是aistudio上出现的吗？我看到一个类似的问题 #34451
> 
> 没有，在本地服务器出现的问题，不过之前在aistudio上好像也遇到了但是没太注意

是否是稳定复现呢？以及能否提供可以复现该报错的脚本

**Comment by skingorz** [comment]
> > > 这个问题是aistudio上出现的吗？我看到一个类似的问题 #34451
> > 
> > 
> > 没有，在本地服务器出现的问题，不过之前在aistudio上好像也遇到了但是没太注意
> 
> 是否是稳定复现呢？以及能否提供可以复现该报错的脚本

https://github.com/skingorz/prototypeNet-paddle/blob/main/tools/train.py
这个代码的第53行改成False应该可以稳定复现

**Comment by heavengate** [comment]
目前只有share memory的Tensor可以跨子进程传输，调用ToTensor的话是GPU Tensor，不使用share memory是不能进行进程间传输的，调用ToTensor必须用share memory
