### ISSUE TITLE
静态图缺少对应fluid.layers.brelu的接口

### ISSUE THREAD

**Issue by yeyupiaoling** [PaddlePaddle/Paddle#34682]
- PaddlePaddle 2.1.0

paddle.static.nn 缺少这个接口：
```
fluid.layers.brelu
```

**Comment by juncaipeng** [comment]
是的，2.0版本后主推动态图模式，不过你依旧可以使用此前版本的api，比如使用`paddle.fluid.layers.brelu(x, t_min=0.0, t_max=24.0, name=None)`

**Comment by yeyupiaoling** [comment]
我用`nn.Hardtanh(min=0.0, max=24.0)`代替了，还是静态图，能正常使用。
