### ISSUE TITLE
VGG19 预训练模型无法使用

### ISSUE THREAD

**Issue by fox2049** [PaddlePaddle/Paddle#34684]
AssertionError: vgg19 model do not have a pretrained model now, you should set pretrained=False

**Comment by zhangting2020** [comment]
看这个报错是说vgg19模型目前没有预训练模型。麻烦确认下：
- 你是需要使用预训练模型的吗？使用的是paddle哪个repo，提供下链接，我可以帮忙确认下paddle是否有提供预训练模型
- 如果不需要使用预训练的话，可以将pretrained设置为False

**Comment by fox2049** [comment]
您好，在很多图像任务中经常需要使用预训练模型提升效果。我是在使用 “vgg = paddle.vision.vgg19(pretrained=True)”时发现的这个问题，Pytorch的话会自动下载预训练模型，而paddle却说pretrained不能设置为True。
[Paddle/python/paddle/vision/models/vgg.py](https://github.com/PaddlePaddle/Paddle/blob/release/2.0/python/paddle/vision/models/vgg.py)

[Paddle API文档](https://www.paddlepaddle.org.cn/documentation/docs/zh/2.0/api/paddle/vision/models/vgg/vgg19_cn.html)

**Comment by zhangting2020** [comment]
经过确认，是需要支持vgg19这个接口下载预训练模型的，我们将在新版本中修复。
