### ISSUE TITLE
报名

### ISSUE THREAD

**Issue by VV-DL-JUMP** [PaddlePaddle/Paddle#34685]
【队名】：知之围不知

【序号】：12

【论文】：YOLOv4: Optimal Speed and Accuracy of Object Detection

【状态】：报名

【repo链接】：https://github.com/VV-DL-JUMP/YOLOv4-Paddle

**Comment by TCChenlong** [comment]
你好，报名论文复现活动是回复这个ISSUE哈：https://github.com/PaddlePaddle/Paddle/issues/34526 不用新建个ISSUE~

**Comment by VV-DL-JUMP** [comment]
> 你好，报名论文复现活动是回复这个ISSUE哈：#34526 不用新建个ISSUE~

哈哈，谢谢，明白了
