### ISSUE TITLE
paddle 2.1 cuda 10 ,tensorrt 推理报错

### ISSUE THREAD

**Issue by aishangmaxiaoming** [PaddlePaddle/Paddle#34689]
(InvalidArgument) Pass tensorrt_subgraph_pass has not been registered. Please use the paddle inference library compiled with tensorrt or disable the tensorrt engine in inference configuration! 
<img width="899" alt="image" src="https://user-images.githubusercontent.com/67897601/128600630-bc48b63d-43b2-4f58-8827-4eb067e9d740.png">

**Comment by zhangting2020** [comment]
这个报错看起来是说你使用的预测库应该不是tensorrt编译的？能否说明下你是如何使用的。

**Comment by zhangting2020** [comment]
@hong19860320 预测问题麻烦帮忙看看

**Comment by aishangmaxiaoming** [comment]
> 这个报错看起来是说你使用的预测库应该不是tensorrt编译的？能否说明下你是如何使用的。

ppdet 使用deploy/python/infer ，run_mode=trt_int8进行测试

**Comment by hong19860320** [comment]
你使用的预测库没有把trt编译进去，可以从这里下载带trt的预编译的预测库，需要注意下cudnn和trt的版本
https://paddleinference.paddlepaddle.org.cn/user_guides/download_lib.html
![image](https://user-images.githubusercontent.com/9973393/128653826-d55b0d32-954d-4d63-ba43-f18b2338d2b9.png)

**Comment by 77h2l** [comment]
请问在安装了trt-paddle后，还是出现如下报错：

    predictor = inference.create_predictor(config)
RuntimeError: (Unavailable) Load tensorrt api getInferLibVersion failed
  [Hint: p_getInferLibVersion should not be null.] (at /paddle/paddle/fluid/platform/dynload/tensorrt.h:114)
