### ISSUE TITLE
静态图使用paddle.save保存的模型很大

### ISSUE THREAD

**Issue by yeyupiaoling** [PaddlePaddle/Paddle#34683]
- PaddlePaddle 2.1.0

使用下面的方式保存模型有3.5G，如果使用paddle.static.save三个文件加起来也不到1G，保存的模型太大了，经常会被kill掉。

如果使用use_binary_format=True直接保存失败。
```
paddle.save(program.state_dict(), model_path)
````

**Comment by juncaipeng** [comment]
paddle.statuc.save是保存预测模型，模型中无用信息会被裁剪。
paddle.save是保存后续用于finetune的模型，理论上是会保存更多数据。
