### ISSUE TITLE
机器翻译预测的译文开头和结尾都出现<unk>

### ISSUE THREAD

**Issue by q178** [PaddlePaddle/Paddle#34687]
为使您的问题得到快速解决，在建立Issue前，请您先通过如下方式搜索是否有相似问题:【搜索issue关键字】【使用labels筛选】【官方文档】

如果您没有查询到相似问题，为快速解决您的提问，建立issue时请提供如下细节信息：
- 标题：简洁、精准描述您的问题，例如“最新预测库的API文档在哪儿 ”
- 版本、环境信息：
    1）PaddlePaddle版本：请提供您的PaddlePaddle版本号（如1.1）或CommitID
    2）CPU：预测若用CPU，请提供CPU型号，MKL/OpenBlas/MKLDNN/等数学库使用情况
    3）GPU：预测若用GPU，请提供GPU型号、CUDA和CUDNN版本号
    4）系统环境：请您描述系统类型、版本（如Mac OS 10.14），Python版本
注：您可以通过执行[summary_env.py](https://github.com/PaddlePaddle/Paddle/blob/develop/tools/summary_env.py)获取以上信息。
-预测信息
    1）C++预测：请您提供预测库安装包的版本信息，及其中的version.txt文件
    2）CMake包含路径的完整命令
    3）API信息（如调用请提供）
    4）预测库来源：官网下载/特殊环境（如BCLOUD编译）
- 复现信息：如为报错，请给出复现环境、复现步骤
- 问题描述：请详细描述您的问题，同步贴出报错信息、日志/代码关键片段

Thank you for contributing to PaddlePaddle.
Before submitting the issue, you could search issue in the github in case that th
If there is no solution,please make sure that this is an inference issue including the following details :
**System information**
-PaddlePaddle version （eg.1.1）or CommitID
-CPU: including CPUMKL/OpenBlas/MKLDNN version
-GPU: including CUDA/CUDNN version
-OS Platform (eg.Mac OS 10.14)
-Python version
-Cmake orders
-C++version.txt
-API information
Note: You can get most of the information by running [summary_env.py](https://github.com/PaddlePaddle/Paddle/blob/develop/tools/summary_env.py). 
**To Reproduce**
Steps to reproduce the behavior
**Describe your current behavior**
**Code to reproduce the issue**
**Other info / logs**

**Comment by zhangting2020** [comment]
unk是不是表示单词没有出现在词表中，我只是猜测，稍后请NLP的同学帮忙解答下。
在此之前，麻烦能否提供一些更详细的信息，比如你用的什么模型，什么数据集等，方便我们获得更多线索帮你分析

**Comment by q178** [comment]
模型用的是paddle1的机器翻译框架，unk本身是未登录词的意思，包含在词表中，但是之前大部分在句子之中出现，而不是像现在这样每句开头和结尾出现



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Zhang Ting ***@***.***&gt;
发送时间: 2021年8月7日 22:05
收件人: PaddlePaddle/Paddle ***@***.***&gt;
抄送: q178 ***@***.***&gt;, Author ***@***.***&gt;
主题: 回复：[PaddlePaddle/Paddle] 机器翻译预测的译文开头和结尾都出现<unk&gt; (#34687)

**Comment by zhangting2020** [comment]
> 模型用的是paddle1的机器翻译框架，unk本身是未登录词的意思，包含在词表中，但是之前大部分在句子之中出现，而不是像现在这样每句开头和结尾出现 发自我的iPhone
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: Zhang Ting ***@***.***&gt; 发送时间: 2021年8月7日 22:05 收件人: PaddlePaddle/Paddle ***@***.***&gt; 抄送: q178 ***@***.***&gt;, Author ***@***.***&gt; 主题: 回复：[PaddlePaddle/Paddle] 机器翻译预测的译文开头和结尾都出现<unk&gt; (#34687)

抱歉，没太明白paddle1的机器翻译框架具体指的是哪个。你是用的Paddle提供的开源模型？能否贴一下链接呢？

**Comment by q178** [comment]
https://github.com/PaddlePaddle/PaddleNLP/tree/develop/examples/machine_translation/transformer

**Comment by FrostML** [comment]
`unk` 作为 special token 放在词表里面，表示在词表中未出现的 token。
这里的 Transformer 只是对 attention is all you need 做的一个基本的实现，没有对生成的结果做额外的处理，比如 `ignore_unk` 之类的策略，所以按照 beam search 每次选择概率最高的结果是有可能出现 unk 的。这个和实际使用的时候具体的训练策略和生成策略有关。
另外问下  `paddle 1` 是什么意思？是指的 Paddle 版本么？PaddleNLP 这里的 Transformer 需要使用 Paddle 2.1 以上的版本哈。
