### ISSUE TITLE
非对称网络的TensorRT预测问题

### ISSUE THREAD

**Issue by TimZhang001** [PaddlePaddle/Paddle#34686]
**1. 测试环境：**
windows 10 + cuda11.0 + Paddle2.1

**2. 推断库的版本**
GIT COMMIT ID: 1e62c239d323354eccfc974d4e2e6496f93d848e
WITH_MKL: ON
WITH_MKLDNN: ON
WITH_GPU: ON
WITH_ROCM: OFF
CUDA version: 11.0
CUDNN version: v8.0
CXX compiler version: 19.16.27045.0
WITH_TENSORRT: ON
TensorRT version: v7

**我这边网络的大小是1 78 110，**

可视化也可以看到：
![image](https://user-images.githubusercontent.com/7878012/128590202-c0a47a30-9741-4e56-81f5-59d69af6e4b3.png)
summary下的结果：
![企业微信截图_1628316784655](https://user-images.githubusercontent.com/7878012/128590258-f0434fe1-6999-40cb-b5c8-167efa330b59.png)

但是我在C++预测的时候出现以下问题：
1. 实例程序给的参考如下，其中  input_t->Reshape({1, 3, resize_img.rows, resize_img.cols});  先row 后col
![image](https://user-images.githubusercontent.com/7878012/128590275-01b69981-3f57-4046-94e4-56b2b2ecd583.png)

2. 我参考实例程序不开启tensorRT, 没有任何问题
![image](https://user-images.githubusercontent.com/7878012/128590335-0e1e4aff-3d33-4cd3-8dad-5ca13b7d2df3.png)
![image](https://user-images.githubusercontent.com/7878012/128590342-bcbd7683-2a68-4f9d-b371-cc8f4e5a3063.png)
![image](https://user-images.githubusercontent.com/7878012/128590347-b3f46503-5076-474d-a645-d10d6c8475cb.png)

3. 我参考实例程序，不开启tensorRT, 但是  input_t->Reshape({1, 3, resize_img.cols， resize_img.rows});  先col 后row，结果就不对了。
![image](https://user-images.githubusercontent.com/7878012/128590373-563012de-157d-4a54-9a80-3f5f33b0ea43.png)
![image](https://user-images.githubusercontent.com/7878012/128590379-14ba9078-5da7-48e8-a706-663512eca06d.png)

4. 我参考实例程序，开启TensorRT，返回错误的是 网络是1@78@110，但是输入的是1@110@78
![image](https://user-images.githubusercontent.com/7878012/128590399-439b121c-4d4c-4a90-a0eb-0b4c348cadf6.png)
![image](https://user-images.githubusercontent.com/7878012/128590403-37575c08-f63c-40f1-9db7-b86e3bfb8c5d.png)
![image](https://user-images.githubusercontent.com/7878012/128590406-aca84eb6-73cb-4504-b472-0fa28004016b.png)

5. 在4的基础上更改输入，强行把输入更改为input_t->Reshape({1, 3, resize_img.cols， resize_img.rows});  先col 后row，但是结果就不对了。
![image](https://user-images.githubusercontent.com/7878012/128590429-17a8bccd-db0a-4a79-8da5-268605fe629e.png)
![image](https://user-images.githubusercontent.com/7878012/128590433-c592b3ff-d53a-4c59-b956-72d056ed936d.png)

6. 在5的基础上，我这边对输入图像进行了resize和transpose都不行。麻烦帮忙看看什么原因好吗？

**Comment by zhangting2020** [comment]
@hong19860320 麻烦帮忙看看这个预测的问题

**Comment by hong19860320** [comment]
首先，请问下你这个网络最终推理的时候，要求输入的图片尺寸是可变的吗？

**Comment by TimZhang001** [comment]
> 首先，请问下你这个网络最终推理的时候，要求输入的图片尺寸是可变的吗？

不变的，输入的图片默认都是1*78*110 （C*W*H）

**Comment by hong19860320** [comment]
> > 首先，请问下你这个网络最终推理的时候，要求输入的图片尺寸是可变的吗？
> 
> 不变的，输入的图片默认都是1_78_110 （C_W_H）

![image](https://user-images.githubusercontent.com/9973393/128656360-e45cb1ec-5579-431b-af7c-f2319b90524f.png)

但是这个网络里面W=110, H=78啊，和你要求的不匹配

**Comment by TimZhang001** [comment]
> > > 首先，请问下你这个网络最终推理的时候，要求输入的图片尺寸是可变的吗？
> > 
> > 
> > 不变的，输入的图片默认都是1_78_110 （C_W_H）
> 
> ![image](https://user-images.githubusercontent.com/9973393/128656360-e45cb1ec-5579-431b-af7c-f2319b90524f.png)
> 
> 但是这个网络里面W=110, H=78啊，和你要求的不匹配

好吧，我错了。shape的地方要求输入时H*W，其他的地方和其他图像处理的地方都是要求W*H。给你们添麻烦了。

**Comment by hong19860320** [comment]
> > > > 首先，请问下你这个网络最终推理的时候，要求输入的图片尺寸是可变的吗？
> > > 
> > > 
> > > 不变的，输入的图片默认都是1_78_110 （C_W_H）
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/9973393/128656360-e45cb1ec-5579-431b-af7c-f2319b90524f.png)
> > 但是这个网络里面W=110, H=78啊，和你要求的不匹配
> 
> 好吧，我错了。shape的地方要求输入时H_W，其他的地方和其他图像处理的地方都是要求W_H。给你们添麻烦了。

一般 tensor的维度是NCHW格式的哦
