### ISSUE TITLE
dist.spawn单机多卡训练的原理是什么

### ISSUE THREAD

**Issue by KinvenW** [PaddlePaddle/Paddle#34690]
请问使用dist.spawn单机多卡的原理是什么？能详细介绍一下吗？
我用dist.spawn启动单机多卡训练时，虽然每张卡都确实在运行计算过程，但是跑一遍测试集的时间仍然跟单机单卡一样长。文档中说是多进程的方式训练，是不是每张卡都启动了一个训练进程，各进程独立地进行读取数据、模型前向反向传播，再将所有卡的梯度值汇总进行更新呢？这样我跑一遍测试集其实是相当于每张卡都独立地跑了一遍测试集？
希望您能详细介绍一下paddle单机多卡的原理，感谢

**Comment by zhangting2020** [comment]
关于原理部分，我会找相关同学帮忙解答，请稍等。

另外，我注意到你一直说的是测试集，我想确认下你观察到的现象是说：
训练过程中，会进行测试集的评估，单机单卡和单机多卡训练时，每次测试集的评估用的时间是一样的？

**Comment by sljlp** [comment]
每张卡都启动了一个训练进程，各进程独立地进行读取数据、模型前向反向传播，再将所有卡的梯度值汇总进行更新
关于读取数据集的问题，需要结合不同的BatcSampler才能具体看数据集是怎么加载的
采用数据并行训练，DistributedBatchSampler为例，无论训练数据集还是测试数据集，默认是每张卡使用总数据集的1/N (N是卡的数目)，而且各个卡上的数据没有交集；在一轮测试之后，可以在每张卡上读取测试集的不同部分，最后评估结果可以汇总到一张卡上进行输出。请你检查一下你使用的数据的sample策略，确定是不是这样的。
关于分布式数据读取策略的问题，建议参考https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/io/DistributedBatchSampler_cn.html
，如果使用了distributedbatchsampler， 理论上多卡会比单卡完成一轮的测试速度更快

**Comment by KinvenW** [comment]
@sljlp @zhangting2020   谢谢你们的解答，我的数据读取没有采用paddle的Sampler，而是自己写了一个生成器函数来读取数据，发现跑训练集每个epoch的时间，以及训练过程中跑验证集或测试集的时间跟单卡是差不多的。这种情况下是不是跟我猜想的一样，每个进程的数据读取是独立的？

**Comment by sljlp** [comment]
是的，每个进程是独立读取数据的
但是多卡和单卡训练速度差不多的原因，应该是数据的读取逻辑和单卡的一样，多卡训练可以使用分布式读取的逻辑（可以参考https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/io/DistributedBatchSampler_cn.html ），每张卡实际上只读取部分数据。
自定义生成器，也可以实现DistributedBatchSampler的作用， 具体实现可以参考着DistributedBatchSampler的实现

**Comment by KinvenW** [comment]
> 是的，每个进程是独立读取数据的 但是多卡和单卡训练速度差不多的原因，应该是数据的读取逻辑和单卡的一样，多卡训练可以使用分布式读取的逻辑（可以参考https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/io/DistributedBatchSampler_cn.html ），每张卡实际上只读取部分数据。 自定义生成器，也可以实现DistributedBatchSampler的作用， 具体实现可以参考着DistributedBatchSampler的实现

请问paddle2有类似pytorch的数据并行训练方式么？就是加载一个batch的数据，然后将其划分到不同卡

**Comment by skywalk163** [comment]
spawn和 python -m paddle.distirbuted.launch XX.py 都是数据并行训练方式。

> 
> 请问paddle2有类似pytorch的数据并行训练方式么？就是加载一个batch的数据，然后将其划分到不同卡

**Comment by sljlp** [comment]
https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/io/DistributedBatchSampler_cn.html 中的方法跟你的需求结果是一样的，你可以参考一下
