### ISSUE TITLE
jetson nano gpu预测时卡死 I0807 22:32:28.869706 11902 ir_params_sync_among_devices_pass.cc:45] Sync params from CPU to GPU

### ISSUE THREAD

**Issue by hicodo** [PaddlePaddle/Paddle#34691]
![1628343203(1)](https://user-images.githubusercontent.com/23546114/128602031-429aee89-856f-4c93-8923-2d7954e43e54.png)

环境：nano 、Ubuntu18.04、CUDA10.2、cudnn 8.0.0、jetpack 4.4、python3.6、paddlepaddle-gpu -2.1.1
关闭tensorrt_engine 仍然卡住
![1628347101(1)](https://user-images.githubusercontent.com/23546114/128603804-402ce999-3d2c-488f-a5c3-ee2e15ae67c2.png)

**Comment by fengxiaoshuai** [comment]
看样子是显存不足导致的
1. 首先建议打开config.enable_memory_optim()
2. 尝试修改显存池的预分配值 config.enable_use_gpu(100,0)

**Comment by hicodo** [comment]
经过测试，发现是配置了switch_use_feed_fetch_ops(False)，去掉就可以了。
![1628588933(1)](https://user-images.githubusercontent.com/23546114/128846139-c68d8089-eed7-453c-a815-14d4d3f8afb8.png)
看文档说使用ZeroCopyTensor 更高效，创建时用predictor = create_paddle_predictor(config)，由于没找到此函数，所以使用了predictor = create_paddle_predictor(config)创建，但是配置switch_use_feed_fetch_ops(False)此项被保留了，造成卡住。这里有个问题就是cpu配置它可能被忽略了没卡住，gpu卡住了。谢谢fengxiaoshuai 。祝飞桨越来越好
