### ISSUE TITLE
能不能 直接出一个包，win10 64 vs2019 的工程，第三方依赖都有的工程，？不然编译很麻烦

### ISSUE THREAD

**Issue by zouwen198317** [PaddlePaddle/Paddle#34698]
为使您的问题得到快速解决，在建立Issue前，请您先通过如下方式搜索是否有相似问题:【搜索issue关键字】【使用labels筛选】【官方文档】

建立issue时，为快速解决问题，请您根据使用情况给出如下信息：
- 标题：请包含关键词“安装错误”/“编译错误”，例如“Mac编译错误”
- 版本、环境信息：
    1）PaddlePaddle版本：请提供您的PaddlePaddle版本号（如1.1）或CommitID
    2）CPU：请提供CPU型号，MKL/OpenBlas/MKLDNN/等数学库的使用情况
    3）GPU：请提供GPU型号，CUDA和CUDNN版本号
    4）系统环境：请说明系统类型、版本（如Mac OS 10.14）、Python版本
注：您可以通过执行[summary_env.py](https://github.com/PaddlePaddle/Paddle/blob/develop/tools/summary_env.py)获取以上信息。
- 安装方式信息：
1）pip安装/docker安装
2）本地编译：请提供cmake命令，编译命令
3）docker编译：请提供docker镜像，编译命令            
  特殊环境请注明：如离线安装等
- 复现信息：如为报错，请给出复现环境、复现步骤
- 问题描述：请详细描述您的问题，同步贴出报错信息、日志/代码关键片段

Thank you for contributing to PaddlePaddle.
Before submitting the issue, you could search issue in Github in case that there was a similar issue submitted or resolved before.
If there is no solution,please make sure that this is an installation issue including the following details:
**System information**
-PaddlePaddle version （eg.1.1）or CommitID
-CPU: including CPUMKL/OpenBlas/MKLDNN version
-GPU: including CUDA/CUDNN version
-OS Platform (eg. Mac OS 10.14)
-Python version
- Install method: pip install/install with docker/build from source(without docker)/build within docker
- Other special cases that you think may be related to this problem, eg. offline install, special internet condition 
Note: You can get most of the information by running [summary_env.py](https://github.com/PaddlePaddle/Paddle/blob/develop/tools/summary_env.py).   

**To Reproduce**
Steps to reproduce the behavior
**Describe your current behavior**
**Code to reproduce the issue**
**Other info / logs**

**Comment by zhwesky2010** [comment]
@zouwen198317 您好，请问是说提供所有第三方的依赖，每次能够离线编译吗？目前大概有十几个第三方，您这边的需求是能够下载一个包，编译时无需下载编译第三方吗

![infoflow 2021-08-09 11-53-11](https://user-images.githubusercontent.com/52485244/128658743-0684b193-d937-4688-9c8b-affe4fa2806e.png)

**Comment by zouwen198317** [comment]
是的

发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Zhou Wei ***@***.***&gt;
发送时间: 2021年8月9日 11:55
收件人: PaddlePaddle/Paddle ***@***.***&gt;
抄送: zouwen198317 ***@***.***&gt;, Mention ***@***.***&gt;
主题: 回复：[PaddlePaddle/Paddle] 能不能 直接出一个包，win10 64 vs2019 的工程，第三方依赖都有的工程，？不然编译很麻烦 (#34698)

**Comment by wadefelix** [comment]
这些第三方依赖在gitee上均可找到mirror仓库，可以直接修改替换下即可。

**Comment by zhwesky2010** [comment]
@zouwen198317 因为在paddle源码里会指定第三方源码的tag，所以预先编的包是有时效性的，可能过一些时间就对不上 导致编不过，所以预先编好的意义不大

**Comment by zouwen198317** [comment]
> @zouwen198317 您好，请问是说提供所有第三方的依赖，每次能够离线编译吗？目前大概有十几个第三方，您这边的需求是能够下载一个包，编译时无需下载编译第三方吗
> 
> ![infoflow 2021-08-09 11-53-11](https://user-images.githubusercontent.com/52485244/128658743-0684b193-d937-4688-9c8b-affe4fa2806e.png)

是的,

**Comment by zouwen198317** [comment]
> 这些第三方依赖在gitee上均可找到mirror仓库，可以直接修改替换下即可。

太多了,一个个找 太麻烦了,而且还有版本兼容的问题. 还是直接提供一个工程,包含第三方的, 第三方如果很多,可以百度云盘
