### ISSUE TITLE
2.1.2 GPU CUDA10.1版本仓库没同步

### ISSUE THREAD

**Issue by JiehangXie** [PaddlePaddle/Paddle#34702]
![image](https://user-images.githubusercontent.com/51190264/128658011-81b84eb7-d377-4f43-a720-0cdf5a306ac2.png)

**Comment by ForFishes** [comment]
您好，感谢您的反馈，这边尝试之后，2.1.2 版本，cuda10.1确实还没有上传仓库。这边会反馈给相应同学，您暂时可以先用较低的版本安装。

**Comment by ForFishes** [comment]
https://www.paddlepaddle.org.cn/whl/windows/mkl/avx/stable.html
您好，从这个链表看是有的。
![image](https://user-images.githubusercontent.com/19485646/128682677-491d14ae-3146-4978-bb48-5e652d93fadb.png)
看看时候可以直接从这个网页上下载下来，然后安装whl的方式安装。如果不行，在看一下你的其他环境是否符合要求。

**Comment by JiehangXie** [comment]
> https://www.paddlepaddle.org.cn/whl/windows/mkl/avx/stable.html
> 您好，从这个链表看是有的。
> ![image](https://user-images.githubusercontent.com/19485646/128682677-491d14ae-3146-4978-bb48-5e652d93fadb.png)
> 看看时候可以直接从这个网页上下载下来，然后安装whl的方式安装。如果不行，在看一下你的其他环境是否符合要求。

好的，已临时解决，感谢，希望尽快同步在线仓库，方便在线环境运行。
