### ISSUE TITLE
【论文复现】cross_entropy 在使用权重和 ignore_index > C(通道数目)时报错

### ISSUE THREAD

**Issue by shiyutang** [PaddlePaddle/Paddle#34718]
为使您的问题得到快速解决，在建立Issue前，请您先通过如下方式搜索是否有相似问题:【搜索issue关键字】【使用labels筛选】【官方文档】

建立issue时，为快速解决问题，请您根据使用情况给出如下信息：
- 标题：简洁、精准描述您的问题，例如“ssd 模型前置lstm报错  ”
- 版本、环境信息：
    1）PaddlePaddle版本：2.1.2

- 模型信息
    1）模型名称 2）使用数据集名称 3）使用算法名称 4）模型链接
     1. Espnetv2 2.Cityscapes 3.cross_entropy 

- 复现信息：如为报错，请给出复现环境、复现步骤
在 cross_entropy 函数中同时传入 ignore_index=255 和 weight 报错
Expected 0 <= label_value < class_dimension(19), but got 0 <= label_value <= 255

- 问题描述：请详细描述您的问题，同步贴出报错信息、日志/代码关键片段
原本应当忽略 ignore_index，但是没有忽略成功。

**Comment by ForFishes** [comment]
您好，这个看报错是说，您输入的标签的范围，和你的ignore_index不匹配。label范围是0～19，而ignore_index 是255，ignore_index的应该在0～19才是合理的。
