### ISSUE TITLE
请问如何使用Paddle查看设备上可使用的GPU个数？

### ISSUE THREAD

**Issue by weekstudy** [PaddlePaddle/Paddle#34716]

**Comment by ForFishes** [comment]
您好，可以通过``paddle.distributed.get_world_size()``拿到全局的卡数，从而知道使用的GPU个数。

**Comment by weekstudy** [comment]
> 您好，可以通过`paddle.distributed.get_world_size()`拿到全局的卡数，从而知道使用的GPU个数。

好的，感谢！
