### ISSUE TITLE
如何截取静态图中的tensor参数

### ISSUE THREAD

**Issue by songyuwen0808** [PaddlePaddle/Paddle#34726]
如题，现在有一个tensor的值为[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
想截取一个新tensor，值为[3, 4, 5, 8, 9, 10]
即每5个值截取后3个，该怎么实现呢

**Comment by songyuwen0808** [comment]
原先的Variable为[-1, 3591]维度的，想截取成[-1, 2986]维度的

**Comment by ForFishes** [comment]
进沟通，用户通过slice的方式解决。
