### ISSUE TITLE
aistudio shm-size

### ISSUE THREAD

**Issue by one-matrix** [PaddlePaddle/Paddle#34725]
1）PaddlePaddle版本：2.1.1
    2）GPU：32GB
    3）系统环境：aistudio 
- Error:
Unexpected BUS error encountered in DataLoader worker. This might be caused by insufficient shared memory (shm), please check whether use_shared_memory is set and storage space in /dev/shm is enough

**Comment by weiexcelpro** [comment]
Shared memory 问题, 
解决中, 预计需要一个月左右. 应该是偶发. 可以通过重启环境来临时解决.
