### ISSUE TITLE
Save_quant_model does not work correctly after adding the skip_quant attribute

### ISSUE THREAD

**Issue by wozna** [PaddlePaddle/Paddle#34732]
I just tested `test_quant2_int8_resnet50_mkldnn` and `test_quant2_int8_mobilenetv1_mkldnn`. It turned out that after the changes related to the `skip_quant` attribute, which were added, among others, in PR https://github.com/PaddlePaddle/Paddle/pull/30342, such operators as `conv2d` and `matmul`  are not quantized in the aforementioned tests. After removing the `label_skip_quantized_op`  in `quant2_int8_mkldnn_pass.py`, all models work fine.

In the static mode in the quantization process, the pattern where we have dequantize-quantize is already detected on the last quantization pass `cpu_quantize_squash_pass`. Therefore, we do not need an attribute like skip_quant. Unfortunately, I was not familiar with the problem that was related to the dygraph models. 
@juncaipeng Could you please explain this problem to me better? And could you please explain why it was necessary to do this? Is it still needed and in what cases?

**Comment by lidanqing-vv** [comment]
@wozna Last time we discussed why skip_quant attribute is added. Is this still an issue?
