### ISSUE TITLE
动态图2.1.2版本，dataload报错，但在pytorch里面是支持的，测试代码如下

### ISSUE THREAD

**Issue by fxwfzsxyq** [PaddlePaddle/Paddle#34748]
```
import numpy as np
import paddle
import cv2
from paddle.io import DataLoader
from paddle.io import Dataset
import torch.utils.data as data
import torch


class testdata1(data.Dataset):
    def __init__(self):
        super(testdata1,self).__init__()
        self.img_list = [1,2,3,4,5,6,7]
        self.img = [np.ones((45,45,3)),np.ones((60,60,3)),np.ones((60,60,3)),
                    np.ones((60,60,3)),np.ones((60,60,3)),np.ones((60,60,3)),np.ones((60,60,3))]
        self.size = 1200
        self.shapesize = [200,2400]
    def get_rand(self,):
        self.size = np.random.choice(self.shapesize,1)[0]
    def __len__(self):
        return len(self.img_list)
    def __getitem__(self, index):
        x = cv2.resize(self.img[index],(self.size,self.size))
        x = torch.Tensor(x).permute((2,0,1))
        return x

data_loader = testdata1()
dataload =data.DataLoader(data_loader,
                batch_size=2,
                shuffle=True,
                num_workers=0,
                drop_last=True)

for _,x in enumerate(dataload):
    data_loader.get_rand()
    print(x.shape)



class testdata(Dataset):
    def __init__(self):
        super(testdata,self).__init__()
        self.img_list = [1,2,3,4,5,6,7]
        self.img = [np.ones((45,45,3)),np.ones((60,60,3)),np.ones((60,60,3)),
                    np.ones((60,60,3)),np.ones((60,60,3)),np.ones((60,60,3)),np.ones((60,60,3))]
        self.size = 1200
        self.shapesize = [200,2400]
    def get_rand(self,):
        self.size = np.random.choice(self.shapesize,1)[0]
    def __len__(self):
        return len(self.img_list)
    def __getitem__(self, index):
        x = cv2.resize(self.img[index],(self.size,self.size))
        x = paddle.to_tensor(x).transpose((2,0,1))
        return x

data_loader = testdata()
dataload =DataLoader(data_loader,
                batch_size=2,
                shuffle=True,
                num_workers=0,
                drop_last=True)

for _,x in enumerate(dataload):
    data_loader.get_rand()
    print(x.shape)
```

**Comment by heavengate** [comment]
报啥错呢

**Comment by fxwfzsxyq** [comment]
建议跑下我给的代码，应该是batch的时候出错了，我是想每一个batch都改变一下图片的尺寸




Traceback (most recent call last):
&nbsp; File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/threading.py", line 926, in _bootstrap_inner
&nbsp; &nbsp; self.run()
&nbsp; File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/threading.py", line 870, in run
&nbsp; &nbsp; self._target(*self._args, **self._kwargs)
&nbsp; File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 192, in _thread_loop
&nbsp; &nbsp; six.reraise(*sys.exc_info())
&nbsp; File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/six.py", line 703, in reraise
&nbsp; &nbsp; raise value
&nbsp; File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 160, in _thread_loop
&nbsp; &nbsp; batch = self._dataset_fetcher.fetch(indices)
&nbsp; File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dataloader/fetcher.py", line 117, in fetch
&nbsp; &nbsp; data = self.collate_fn(data)
&nbsp; File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dataloader/collate.py", line 77, in default_collate_fn
&nbsp; &nbsp; return [default_collate_fn(fields) for fields in zip(*batch)]
&nbsp; File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dataloader/collate.py", line 77, in <listcomp&gt;
&nbsp; &nbsp; return [default_collate_fn(fields) for fields in zip(*batch)]
&nbsp; File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dataloader/collate.py", line 61, in default_collate_fn
&nbsp; &nbsp; return layers.stack(batch, axis=0)
&nbsp; File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/layers/nn.py", line 10067, in stack
&nbsp; &nbsp; return core.ops.stack(x, 'axis', axis)
ValueError: (InvalidArgument) Dims of all Inputs(X) must be the same, but received input 1 dim is:3, 624, 1104 not equal to input 0 dim:3, 688, 1216.
&nbsp; [Hint: Expected input_dims[i] == input_dims[0], but received input_dims[i]:3, 624, 1104 != input_dims[0]:3, 688, 1216.] (at /paddle/paddle/fluid/operators/stack_op.cc:46)
&nbsp; [operator < stack &gt; error]









------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年8月10日(星期二) 下午4:35
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [PaddlePaddle/Paddle] 动态图2.1.2版本，dataload报错，但在pytorch里面是支持的，测试代码如下 (#34748)





 
报啥错呢
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by tughv** [comment]
我也遇到了，搞得我快不想用paddle了
