### ISSUE TITLE
【论文复现】动态图自定义Python算子疑似显存泄露

### ISSUE THREAD

**Issue by txyugood** [PaddlePaddle/Paddle#34752]
1）PaddlePaddle版本：2.1.0
    2）CPU：AI Studio环境
    3）GPU：AI Studio环境
    4）系统环境：AI Studio环境
在网络中如果使用了自定义的Python算子，在forward中会使用save_for_backward保存Tensor供backward使用。先发现
如果只是推理预测，没有调用backward获取save_for_backward保存的Tensor。显存会不断的增加，直到程序崩溃。

**Comment by Thunderbrook** [comment]
辛苦提供下复现代码吧

**Comment by txyugood** [comment]
抱歉，之前一直没提交，所以没开源代码，现在提交了，开源代码。

项目地址：https://github.com/txyugood/tabnet

问题描述在最后总结，一共有两个显存问题。这里我也简单描述下。

在paddle_tabnet/sparsemax.py文件里66-67行我加了tranning开关，这样在eval阶段就不会显存暴涨了。不知道这样处理是否合理，但是看训练和预测情况，应该是没问题的。
```
if trainning:
    ctx.save_for_backward(supp_size, output)
```

还有就是提到的第二个显存缓慢增长的问题，在paddle_tabnet/sparsemax.py文件75-80行，使用这行代码就会显存缓慢增长，最后程序就会崩溃。
```
grad_input[output == 0] = 0
```
修改为以下代码，功能一致，显存不会缓慢增长，程序不会崩溃。

```
idx = paddle.fluid.layers.where(output == 0)
grad_input_gather = paddle.gather_nd(grad_input, idx)
grad_input_gather = 0 - grad_input_gather
grad_input = paddle.scatter_nd_add(grad_input, idx, grad_input_gather)

```

**Comment by zhiqiu** [comment]
> 抱歉，之前一直没提交，所以没开源代码，现在提交了，开源代码。
> 
> 项目地址：https://github.com/txyugood/tabnet
> 
> 问题描述在最后总结，一共有两个显存问题。这里我也简单描述下。
> 
> 在paddle_tabnet/sparsemax.py文件里66-67行我加了tranning开关，这样在eval阶段就不会显存暴涨了。不知道这样处理是否合理，但是看训练和预测情况，应该是没问题的。
> 
> ```
> if trainning:
>     ctx.save_for_backward(supp_size, output)
> ```
> 
> 还有就是提到的第二个显存缓慢增长的问题，在paddle_tabnet/sparsemax.py文件75-80行，使用这行代码就会显存缓慢增长，最后程序就会崩溃。
> 
> ```
> grad_input[output == 0] = 0
> ```
> 
> 修改为以下代码，功能一致，显存不会缓慢增长，程序不会崩溃。
> 
> ```
> idx = paddle.fluid.layers.where(output == 0)
> grad_input_gather = paddle.gather_nd(grad_input, idx)
> grad_input_gather = 0 - grad_input_gather
> grad_input = paddle.scatter_nd_add(grad_input, idx, grad_input_gather)
> ```

第一个问题，你在predict函数上加一个@paddle.no_grad()试下。https://github.com/txyugood/tabnet/blob/91fb4b5f6b8cb4127d46ea996af6d857b15b7614/paddle_tabnet/abstract_model.py#L275

**Comment by txyugood** [comment]
> > 抱歉，之前一直没提交，所以没开源代码，现在提交了，开源代码。
> > 项目地址：https://github.com/txyugood/tabnet
> > 问题描述在最后总结，一共有两个显存问题。这里我也简单描述下。
> > 在paddle_tabnet/sparsemax.py文件里66-67行我加了tranning开关，这样在eval阶段就不会显存暴涨了。不知道这样处理是否合理，但是看训练和预测情况，应该是没问题的。
> > ```
> > if trainning:
> >     ctx.save_for_backward(supp_size, output)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 还有就是提到的第二个显存缓慢增长的问题，在paddle_tabnet/sparsemax.py文件75-80行，使用这行代码就会显存缓慢增长，最后程序就会崩溃。
> > ```
> > grad_input[output == 0] = 0
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 修改为以下代码，功能一致，显存不会缓慢增长，程序不会崩溃。
> > ```
> > idx = paddle.fluid.layers.where(output == 0)
> > grad_input_gather = paddle.gather_nd(grad_input, idx)
> > grad_input_gather = 0 - grad_input_gather
> > grad_input = paddle.scatter_nd_add(grad_input, idx, grad_input_gather)
> > ```
> 
> 第一个问题，你在predict函数上加一个@paddle.no_grad()试下。https://github.com/txyugood/tabnet/blob/91fb4b5f6b8cb4127d46ea996af6d857b15b7614/paddle_tabnet/abstract_model.py#L275

加上确实好用，多谢！

**Comment by zhiqiu** [comment]
thanks 

> > > 抱歉，之前一直没提交，所以没开源代码，现在提交了，开源代码。
> > > 项目地址：https://github.com/txyugood/tabnet
> > > 问题描述在最后总结，一共有两个显存问题。这里我也简单描述下。
> > > 在paddle_tabnet/sparsemax.py文件里66-67行我加了tranning开关，这样在eval阶段就不会显存暴涨了。不知道这样处理是否合理，但是看训练和预测情况，应该是没问题的。
> > > ```
> > > if trainning:
> > >     ctx.save_for_backward(supp_size, output)
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > 还有就是提到的第二个显存缓慢增长的问题，在paddle_tabnet/sparsemax.py文件75-80行，使用这行代码就会显存缓慢增长，最后程序就会崩溃。
> > > ```
> > > grad_input[output == 0] = 0
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > 修改为以下代码，功能一致，显存不会缓慢增长，程序不会崩溃。
> > > ```
> > > idx = paddle.fluid.layers.where(output == 0)
> > > grad_input_gather = paddle.gather_nd(grad_input, idx)
> > > grad_input_gather = 0 - grad_input_gather
> > > grad_input = paddle.scatter_nd_add(grad_input, idx, grad_input_gather)
> > > ```
> > 
> > 
> > 第一个问题，你在predict函数上加一个@paddle.no_grad()试下。https://github.com/txyugood/tabnet/blob/91fb4b5f6b8cb4127d46ea996af6d857b15b7614/paddle_tabnet/abstract_model.py#L275
> 
> 加上确实好用，多谢！

**Comment by zhiqiu** [comment]
> 抱歉，之前一直没提交，所以没开源代码，现在提交了，开源代码。
> 
> 项目地址：https://github.com/txyugood/tabnet
> 
> 问题描述在最后总结，一共有两个显存问题。这里我也简单描述下。
> 
> 在paddle_tabnet/sparsemax.py文件里66-67行我加了tranning开关，这样在eval阶段就不会显存暴涨了。不知道这样处理是否合理，但是看训练和预测情况，应该是没问题的。
> 
> ```
> if trainning:
>     ctx.save_for_backward(supp_size, output)
> ```
> 
> 还有就是提到的第二个显存缓慢增长的问题，在paddle_tabnet/sparsemax.py文件75-80行，使用这行代码就会显存缓慢增长，最后程序就会崩溃。
> 
> ```
> grad_input[output == 0] = 0
> ```
> 
> 修改为以下代码，功能一致，显存不会缓慢增长，程序不会崩溃。
> 
> ```
> idx = paddle.fluid.layers.where(output == 0)
> grad_input_gather = paddle.gather_nd(grad_input, idx)
> grad_input_gather = 0 - grad_input_gather
> grad_input = paddle.scatter_nd_add(grad_input, idx, grad_input_gather)
> ```

问题2，初步认为是slice左值的bug，详见：https://github.com/PaddlePaddle/Paddle/pull/35013
你可以先按你后面功能一致的代码写。

**Comment by txyugood** [comment]
> > 抱歉，之前一直没提交，所以没开源代码，现在提交了，开源代码。
> > 项目地址：https://github.com/txyugood/tabnet
> > 问题描述在最后总结，一共有两个显存问题。这里我也简单描述下。
> > 在paddle_tabnet/sparsemax.py文件里66-67行我加了tranning开关，这样在eval阶段就不会显存暴涨了。不知道这样处理是否合理，但是看训练和预测情况，应该是没问题的。
> > ```
> > if trainning:
> >     ctx.save_for_backward(supp_size, output)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 还有就是提到的第二个显存缓慢增长的问题，在paddle_tabnet/sparsemax.py文件75-80行，使用这行代码就会显存缓慢增长，最后程序就会崩溃。
> > ```
> > grad_input[output == 0] = 0
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 修改为以下代码，功能一致，显存不会缓慢增长，程序不会崩溃。
> > ```
> > idx = paddle.fluid.layers.where(output == 0)
> > grad_input_gather = paddle.gather_nd(grad_input, idx)
> > grad_input_gather = 0 - grad_input_gather
> > grad_input = paddle.scatter_nd_add(grad_input, idx, grad_input_gather)
> > ```
> 
> 问题2，初步认为是slice左值的bug，详见：#35013
> 你可以先按你后面功能一致的代码写。

好的，谢谢！
