### ISSUE TITLE
ReXNet动态图中的set_value函数同api中的解释有出入

### ISSUE THREAD

**Issue by CheQiXiao** [PaddlePaddle/Paddle#34756]
在tvm上实现set_value这个函数时，发现动态图中的set_value是有两个输入，这同api上的解释似乎有出入，请问这里两个输入的set_value是如何选择的？
![image](https://user-images.githubusercontent.com/50894398/128822443-3800af3f-223a-498b-8721-59168a8400c5.png)

问题来自论坛：https://aistudio.baidu.com/paddle/forum/topic/show/990192

**Comment by zhiqiu** [comment]
hi，set_value是Tensor类的方法，其中第一个参数self参数不需要传递，使用方式如`tensor.set_value(var)`。

**Comment by Sunrise723** [comment]
> hi，set_value是Tensor类的方法，其中第一个参数self参数不需要传递，使用方式如`tensor.set_value(var)`。

Hi，两个输入的意思是在动态图中的set_vaue是有两个输入的，而api中只有一个输入，我现在想做的是实现这个op，但没有理解动态图中的set_value的两个输入是如何选择的，是否要经过处理

**Comment by zhiqiu** [comment]
> set_vaue

sorry，我不太理解你的意思？
“set_vaue是有两个输入的”，是指self和value吗？
“而api中只有一个输入”是指哪个API？
