### ISSUE TITLE
cudaErrorLaunchOutOfResources on Jetson nano

### ISSUE THREAD

**Issue by jesen8** [PaddlePaddle/Paddle#34759]
- 版本、环境信息：
    1）PaddlePaddle版本：v2.1.2
    2）CPU：
    3）GPU：Jetson Nano
    4）系统环境：cuda 10.2  cudnn 8.0.0  tensorrt 7.1.3
-预测信息
    1）C++预测：
```text
GIT COMMIT ID: 800925760890d896b73ea3b2e2e5fa18c02fd5b0
WITH_MKL: OFF
WITH_MKLDNN: OFF
WITH_GPU: ON
WITH_ROCM: OFF
CUDA version: 10.2
CUDNN version: v8.0
CXX compiler version: 8.2.0
WITH_TENSORRT: ON
TensorRT version: v7.1.3.0
```

目前使用v2.1.2版本编译的c++推理库，在jetson nano上跑ppyolo_tiny是可以得到正确结果的，但是单独跑PaddleSeg项目下的轻量分割网络bisenet时，能顺利推理，但是无法获得正确的分割结果. 而且同时调用上面的yolo和bisenet网络时，先调用yolo正常推理一次后，调用bisenet推理仍然会出现如下错误：
`parallel_for failed: cudaErrorLaunchOutOfResources: too many resources requested for launch`
单独推理bisenet结果不正确 应该是某一个算子没有做优化处理吧？ 在2080上推理结果正确
目前已知的有支持在nano上跑的分割网络吗

**Comment by jesen8** [comment]
相关链接
https://github.com/PaddlePaddle/Paddle/issues/32326
希望能及时回复，谢谢

**Comment by fengxiaoshuai** [comment]
这个问题是由于模型中的某些op在GPU上运行的时候寄存器不足导致的，原因是nano的寄存器太少了，解决方案的话是首先查出这个具体op, 然后修改其对应的cuda kernel 的thread数，编译后再使用就可以了，参考代码：https://github.com/PaddlePaddle/Paddle/blob/ed2641cb035f3e136c202ae3b407fc226934ffe9/paddle/fluid/operators/detection/yolo_box_op.cu#L124

**Comment by jesen8** [comment]
@fengxiaoshuai 你好，那分割网络bisenet推理结果错误怎么解决呢

**Comment by fengxiaoshuai** [comment]
一样的问题，应该是里面有个op kernel在GPU运行的时候没调用起来，输出为0，进而导致整个结果是错误的

**Comment by jesen8** [comment]
@fengxiaoshuai 你好，那你们官方有计划修复这个问题吗

**Comment by fengxiaoshuai** [comment]
有的，已经修复了一批，但是有的op只有在输入很大的情况下才会报出该错误，所以不一定全面覆盖，后续还会检测修复，您可以把你遇到的op反馈过来，后续的发布版本会修复的。如果着急使用的话按我给你的链接自己修复后编译也是可以的。

**Comment by jesen8** [comment]
@fengxiaoshuai 你好，如何获取模型的所有op呢，准备反馈给你们

**Comment by fengxiaoshuai** [comment]
只反馈问题op就行了，不需要所有的op, 具体方式是设置环境变量：export FLAGS_benchmark=1， export GLOG_v=4, 运行代码看看卡在哪个op, 那么这个op就是问题op.

**Comment by jesen8** [comment]
```text
I0816 09:37:03.943217  6631 main.cpp:38] smartbox init model ok: 0
I0816 09:37:03.943625  6631 main.cpp:61] c++ service for xc smartbox start ok!
I0816 09:37:05.912954  6639 smart_box.cpp:76] VideoCapture open ok...
I0816 09:37:07.948635  6639 smart_box.cpp:96] grab img fps: 37.8298
I0816 09:37:10.025470  6639 smart_box.cpp:96] grab img fps: 25.4528
I0816 09:37:12.082342  6639 smart_box.cpp:96] grab img fps: 25.4364
I0816 09:37:13.740095  6638 vihicle_detection.cpp:401] 拥堵检测 cur_car_cnt: 0
terminate called after throwing an instance of 'thrust::system::system_error'
  what():  parallel_for failed: cudaErrorLaunchOutOfResources: too many resources requested for launch
Aborted (core dumped)
xunchang@xunchang-smartbox:~/work/code/smart_box_cpp/build/src$ echo $FLAGS_benchmark
1
xunchang@xunchang-smartbox:~/work/code/smart_box_cpp/build/src$ echo $GLOG_v
4
xunchang@xunchang-smartbox:~/work/code/smart_box_cpp/build/src$ 

```

@fengxiaoshuai  你好，似乎设置环境变量后没有效果...

**Comment by wangye707** [comment]
@jesen8  你好，设定上面的环境变量后执行可以看到卡在bilinear_interp_v2这个op，可以按照上面提供的方法修改后编译一个新的paddle包便可以，或者采用cpu预测。下个版本我们将修复该问题，预计9月初发版。感谢~

**Comment by jesen8** [comment]
@wangye707 您好，十分感谢， 还有bisenet分割网络推理结果不正确问题也会一起解决吗

**Comment by wangye707** [comment]
@jesen8  结果误差很大吗？这是我这边的测试结果
![image](https://user-images.githubusercontent.com/39162106/129534416-a0c8f814-de15-4525-8fca-85d42c9c16ea.png)

**Comment by jesen8** [comment]
误差特别大， 无法使用，而且所有图片推理结果都是一样的，类似于椒盐噪声，在2080上正常结果就是像上面图中的，应该是这个原因吧...

> 一样的问题，应该是里面有个op kernel在GPU运行的时候没调用起来，输出为0，进而导致整个结果是错误的

**Comment by jesen8** [comment]
@wangye707 推理错误是在v2.1.3版本，jetson nano上的, 2080上结果正常

**Comment by wangye707** [comment]
v2.1.3？没有这个版本吧，2.1.2吧？

**Comment by jesen8** [comment]
@wangye707  不好意思，编译的版本是2.1.1 ，如果你那边能跑出结果的话，我看看代码吧，有可能是我代码的有bug，但是同样的代码在2080上的结果是正确的，你跑的这个cityscape是在jetson nano上用gpu跑的吗

**Comment by wangye707** [comment]
@jesen8  你好，bisenet分割网络推理结果不正确在develop分支这个bug已经修复了，我上面发的图片是develop分支编译的paddle预测的结果，2.1.1版本的预测跑不出结果。这是最新的天级别编译产物：https://paddle-qa.bj.bcebos.com/paddle-pipeline/Master_JetsonXavier_Trton_Jetpack4.5_Py36_Compile_D/latest/paddlepaddle_gpu-0.0.0-cp36-cp36m-linux_aarch64.whl。  你可以先试下，正式稳定版发布在9月初。
