### ISSUE TITLE
【论文复现】paddle.gather 和 torch.gather 的差异

### ISSUE THREAD

**Issue by TCChenlong** [PaddlePaddle/Paddle#34761]
PaddlePaddle 的 gather：索引(index)的秩有且只能等于1。
具体对比见：https://github.com/PaddlePaddle/X2Paddle/blob/develop/docs/pytorch_project_convertor/API_docs/ops/torch.gather.md
具体信息见：[JunnYu/paddle_reformer/例子](https://github.com/JunnYu/paddle_reformer/blob/main/%E5%9D%91/%E4%BE%8B%E5%AD%90.ipynb)

**Comment by yufei2933** [comment]
paddlepaddle目前还没同步torch的gather... ...
