### ISSUE TITLE
nlp

### ISSUE THREAD

**Issue by ssyeats** [PaddlePaddle/Paddle#34777]
【队名】：ssssss

【序号】：83

【论文】：PEGASUS: Pre-training with Extracted Gap-sentences for Abstractive Summarization

【状态】：报名

【repo链接】：https://github.com/ssyeats/paddle-first-nlp

**Comment by TCChenlong** [comment]
是在这个ISSUE中回复，完成报名哦：https://github.com/PaddlePaddle/Paddle/issues/34526
