### ISSUE TITLE
paddle预测库编译cmake后出 core

### ISSUE THREAD

**Issue by barry2025** [PaddlePaddle/Paddle#34775]
问题描述：
cmake 后出现 core 文件，cmake 过程未报错，有一个 warning:
![image](https://user-images.githubusercontent.com/20043808/128870372-2363aa00-3bad-414c-84dc-7760d5126df9.png)

环境和版本：
commitID: e04b66f2d2
branch: release/2.1
编译环境：ubuntu18.04，cuda10.2，cmake3.18.4
cmake 命令：
cmake ..  -DCUDA_ARCH_NAME=All  -DWITH_PYTHON=OFF  -DWITH_MKL=ON -DWITH_MKLDNN=ON -DWITH_GPU=ON -DON_INFER=ON

**Comment by BillDior** [comment]
-DCUDA_ARCH_NAME=All 应该写成-DCUDA_ARCH_NAME="All"

**Comment by barry2025** [comment]
修改后仍然有 core，这是 cmake 输出log：https://bj.bcebos.com/v1/acg-algo/user/tangxin/tmp/build_log.txt
这是 build 目录生成的文件：https://bj.bcebos.com/v1/acg-algo/user/tangxin/tmp/build_cuda.tar.gz

**Comment by Shixiaowei02** [comment]
已通过您的日志确认 -DCUDA_ARCH_NAME=All 设置正确。
请尝试：
1、确认您的机器上是否有显卡；
2、单独运行 nvcc 观察行为是否正常；
3、尝试升级 cmake。
