### ISSUE TITLE
paddle2.0.1 加载数据集时内存占满 cpu占用率100%

### ISSUE THREAD

**Issue by sean0xiao** [PaddlePaddle/Paddle#34778]
- 标题：gpu训练：使用paddle加载数据集时 cpu占用率达到100% 内存使用30多g
- 版本、环境信息
    1）PaddlePaddle版本：2.0.1
    2）CPU：
    3）GPU：CUDA 11.2  
    4）系统环境：unbuntu

- 训练信息
    1）单机/多卡
    2）显存信息 
    3）Operator信息
- 复现信息：
- 问题描述：加载训练数据集时（多文件） cpu、内存占用非常大 加载速度非常慢

**Comment by Thunderbrook** [comment]
辛苦提供下复现代码吧

**Comment by sean0xiao** [comment]
代码地址 wget ***@***.***:8029/pimp_ernie.tar.gz
可以如流上沟通下么 比较方便 感谢
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/Paddle"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年8月11日(星期三) 下午4:57
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PaddlePaddle/Paddle] paddle2.0.1 加载数据集时内存占满 cpu占用率100% (#34778)





 
辛苦提供下复现代码吧
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
