### ISSUE TITLE
【队名】：队名叫啥

### ISSUE THREAD

**Issue by gouqi666** [PaddlePaddle/Paddle#34779]
【队名】：对名叫啥

【序号】：90

【论文】：ChineseBERT: Chinese Pretraining Enhanced by Glyph and Pinyin Information

【状态】：报名

【repo链接】：https://github.com/gq15760172077/ChineseBERT-paddle

**Comment by TCChenlong** [comment]
是在这个ISSUE中回复，完成报名哦：#34526
