### ISSUE TITLE
报名

### ISSUE THREAD

**Issue by Zhangzhixiang-laugh** [PaddlePaddle/Paddle#34776]
【队名】：Mr.xiaozhu的团队

【序号】：84

【论文】：ProphetNet: Predicting Future N-gram for Sequence-to-Sequence Pre-training

【状态】：报名

【repo链接】：https://github.com/Zhangzhixiang-laugh/best_prohetnet

**Comment by TCChenlong** [comment]
是在这个ISSUE中回复完成报名哦：https://github.com/PaddlePaddle/Paddle/issues/34526
