### ISSUE TITLE
paddle android capi 加载模型太慢

### ISSUE THREAD

**Issue by bushidonggua** [PaddlePaddle/Paddle#3477]
两个接口在我的安卓机上耗时：
paddle_init= 1660ms
paddle_gradient_machine_create_for_inference_with_parameters time=146978ms
再加上一些模型资源拷贝，加解密，处理等，整个预测开始工作的时间要上3分钟了，在移动端无法忍受！

安卓机型号：三星Note4
模型尺寸：31M
模型配置：v1版本的small_vgg网络
![image](https://user-images.githubusercontent.com/5506467/29272996-0106da1a-8135-11e7-88af-09151da605f5.png)

**Comment by hedaoyuan** [comment]
@Xreki Please check the time-consuming issue of the `paddle_gradient_machine_create_for_inference_with_parameters api`. I think the time(146978ms) is not right.
@bushidonggua Can you share your code, about how did you test the time of these two interfaces?

**Comment by bushidonggua** [comment]
@hedaoyuan 不好意思，找到原因了，模型放在assert里面会导致加载巨慢

**Comment by Xreki** [comment]
@bushidonggua 你的意思是从`assets`里面读取模型，这个过程比较耗时？

**Comment by bushidonggua** [comment]
@Xreki 是的，我换了一种方式就好了
