### ISSUE TITLE
paddle-v2.1.1 编译错误 cmake编译mkl或者openblas时出错 

### ISSUE THREAD

**Issue by xiatian1355** [PaddlePaddle/Paddle#34782]
paddle-v2.1.1 编译错误 cmake编译mkl或者openblas时出错 

编译环境 vs2017 cmake3.17.0 
这是mkldnn的错误
1>Performing install step for 'extern_mkldnn'
1>CMake Error at D:/Paddle Inference/Paddle/build/third_party/mkldnn/src/extern_mkldnn-stamp/extern_mkldnn-install-Release.cmake:49 (message):
1>  Command failed: 1
1>
1>   'C:/Program Files/CMake/bin/cmake.exe' '--build' '.' '--config' 'Release' '--target' 'install'
1>
1>  See also
1>
1>    D:/Paddle Inference/Paddle/build/third_party/mkldnn/src/extern_mkldnn-stamp/extern_mkldnn-install-*.log
1>
1>
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(209,5): error MSB6006: “cmd.exe”已退出，代码为 1。
1>已完成生成项目“extern_mkldnn.vcxproj”的操作 - 失败。

openblas错误
Performing configure step for 'extern_openblas'
8>CMake Error at D:/Paddle Inference/Paddle-2.1.1/build/third_party/openblas/src/extern_openblas-stamp/extern_openblas-configure-Release.cmake:49 (message):
8>  Command failed: 1
8>
8>   'C:/Program Files/CMake/bin/cmake.exe' '-DCMAKE_C_COMPILER=C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.16.27023/bin/Hostx64/x64/cl.exe' '-DCMAKE_CXX_COMPILER=C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.16.27023/bin/Hostx64/x64/cl.exe' '-DCMAKE_C_FLAGS=/DWIN32 /D_WINDOWS  /W0  /w /wd4068 /wd4129 /wd4244 /wd4267 /wd4297 /wd4530 /wd4577 /wd4819 /wd4838' '-DCMAKE_CXX_FLAGS=/DWIN32 /D_WINDOWS  /W0  /GR /EHsc /w /wd4068 /wd4129 /wd4244 /wd4267 /wd4297 /wd4530 /wd4577 /wd4819 /wd4838' '-DCMAKE_INSTALL_PREFIX=D:/Paddle Inference/Paddle-2.1.1/build/third_party/install/openblas' '-DCMAKE_POSITION_INDEPENDENT_CODE=ON' '-DCMAKE_BUILD_TYPE=Release' '-DBUILD_SHARED_LIBS=ON' '-DMSVC_STATIC_CRT=ON' '-GVisual Studio 15 2017' '-Ax64' '-Thost=x64' '-DCMAKE_GENERATOR_INSTANCE:INTERNAL=C:/Program Files (x86)/Microsoft Visual Studio/2017/Community' '-CD:/Paddle Inference/Paddle-2.1.1/build/third_party/openblas/tmp/extern_openblas-cache-Release.cmake' 'D:/Paddle Inference/Paddle-2.1.1/build/third_party/openblas/src/extern_openblas'
8>
8>  See also
8>
8>    D:/Paddle Inference/Paddle-2.1.1/build/third_party/openblas/src/extern_openblas-stamp/extern_openblas-configure-*.log
8>
8>
8>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(209,5): error MSB6006: “cmd.exe”已退出，代码为 1。
8>已完成生成项目“extern_openblas.vcxproj”的操作 - 失败。
附log文件↓↓↓
[extern_openblas-configure-err.log](https://github.com/PaddlePaddle/Paddle/files/6964550/extern_openblas-configure-err.log)

**Comment by zhwesky2010** [comment]
@xiatian1355 请问Paddle根目录下的cmake命令是什么？麻烦看一下

**Comment by xiatian1355** [comment]
> @xiatian1355 请问Paddle根目录下的cmake命令是什么？麻烦看一下

我好像找到原因了 根目录名字加了空格  D:/Paddle Inference  现在我改成了 D:/Paddle_Inference   MKL_DNN编译安装通过了

**Comment by zhwesky2010** [comment]
> > @xiatian1355 请问Paddle根目录下的cmake命令是什么？麻烦看一下
> 
> 我好像找到原因了 根目录名字加了空格 D:/Paddle Inference 现在我改成了 D:/Paddle_Inference MKL_DNN编译安装通过了

对 空格会导致目录识别出错
