### ISSUE TITLE
数据类型错误

### ISSUE THREAD

**Issue by ziyaxuanyi** [PaddlePaddle/Paddle#34786]
使用推理模型，执行.run()函数后获取的输出PaddleInferTensor，在使用copy_to_cpu()时报错：
Tensor数据类型错误，it holds double,but desires to be float，
请问PaddleInferTensor如何转换数据类型？

**Comment by jiweibo** [comment]
您好，输出tensor的精度是由模型决定的哈，你可以可视化下模型，看下输出的数据类型是float还是double。

相应的，copy_to_cpu的接收指针请设置成对应的类型。
