### ISSUE TITLE
【论文复现】MaxUnpool2d方法的组合实现代码有bug

### ISSUE THREAD

**Issue by Star-Learning** [PaddlePaddle/Paddle#34785]
#### MaxUnpool2d示例代码跑不通
[MaxUnpool2d方法链接](https://github.com/PaddlePaddle/X2Paddle/blob/develop/docs/pytorch_project_convertor/API_docs/nn/torch.nn.MaxUnpool2d.md)
采用示例测试反池化时会报错

> AttributeError: 'Tensor' object has no attribute 'tolist'

经过调试将forward函数中最后一个for循环进行修改可以跑通：
原始：
```
        for i in range(flatten_indices.shape[0]):
            flatten_out[flatten_indices[i].tolist()] = flatten_input[i].tolist()
```
修改后：
```
        for i in range(flatten_indices.shape[0]):
            index = int(flatten_indices[i])
            flatten_out[index] = flatten_input[i]
```

#### code for MaxUnpool2d cannot work well.
[MaxUnpool2d method link](https://github.com/PaddlePaddle/X2Paddle/blob/develop/docs/pytorch_project_convertor/API_docs/nn/torch.nn.MaxUnpool2d.md)
There is a bug as follows when running the test.

> AttributeError: 'Tensor' object has no attribute 'tolist'

Modify the last for loop in the forward function to run through:
Original：
```
        for i in range(flatten_indices.shape[0]):
            flatten_out[flatten_indices[i].tolist()] = flatten_input[i].tolist()
```
Modified：
```
        for i in range(flatten_indices.shape[0]):
            index = int(flatten_indices[i])
            flatten_out[index] = flatten_input[i]
```

**Comment by wjj19950828** [comment]
您好，感谢您的反馈，目前相关问题已经修复～，相关PR:https://github.com/PaddlePaddle/X2Paddle/pull/662
