### ISSUE TITLE
使用paddle inference推理ppyolov2 输入和输出的问题

### ISSUE THREAD

**Issue by wyh669** [PaddlePaddle/Paddle#34795]
在使用inference推理的时候，打印出input_tensor的name是['im_shape','image','scale_factor']，请问这三个tensor的维度该如何设定以及数据该如何进行输入。另外，使用tensorrt加速，输出的tensor名称是[‘nearest_interp_v2_1.tmp_0','concat_4.tmp_0']，这两个tensor又分别是什么意义？

**Comment by BillDior** [comment]
tensor维度的设置可以用netron打开以后看到模型训练时的维度，数据的输入的话可以参考Inference的文档https://paddleinference.paddlepaddle.org.cn/quick_start/cpp_demo.html
![image](https://user-images.githubusercontent.com/41277577/128982804-9282726e-caea-40fd-a946-f9b57cba8f16.png)
输出tensor的名称也是在训练时框架决定的，只能表示是nearest_interp_v2和concat这两个op的输出，具体意义得看模型是怎么设计的了

**Comment by wangxinxin08** [comment]
input_tensor:
1. image代表图像，维度为[b, 3, h, w]
2. im_shape为图像在resize之后的大小，维度为[b, 2]，表示每一个图像resize之后的[h, w]
3. scale_factor为resize的ratio，维度为[b, 2]，表示每一个图像resize的[scale_y, scale_x]

输入tensor可以参考PaddleDetection的预处理代码进行设置：https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.1/deploy/python/preprocess.py
输出tensor由于经过了fuse，其名字不能表达其含义，
1. output_names[0]为bbox输出，维度为[N, 6]，表示[label, confidence, xmin, ymin, xmax, ymax]，该batch中每一个图像检测到的框concat到了一起
2. output_names[1]为rois_num，维度为[b]，表示该batch中每一个图像检测到的框的数量

**Comment by smallhaozigithub** [comment]
![27f90875d0f15e2dee054ea594c7e9e](https://user-images.githubusercontent.com/72907766/167780643-5f0b317a-7365-4e6a-ba04-0facc294df20.png)
@wangxinxin08 
我想问下这个模型里面im_shape  一般维度都是[?,2] ，这种[?,3]的情况该怎么传入参数 ？
还有就是 im_info 的参数是和 scale_factor 一样的么？ 如果是一样，[?,3]的情况该怎么传入参数 ？
