### ISSUE TITLE
dataloader导致程序崩溃

### ISSUE THREAD

**Issue by zhusy09** [PaddlePaddle/Paddle#34794]
windows，paddle版本是2.1.0，cudnn7.6，driver10.2，在用paddle.io.dataloader，跑完所有的step后，程序突然就崩溃了。跟踪程序发现是数据集里都没有数据了，它却还在取数据，导致程序崩溃。我不得已只能设置跑到最后一个step，让循环break。
请问这个是咋回事？
还有paddle动不动遇到点错误就崩溃，譬如int类型不对等等，连个错误提示都没有，很影响调试程序。

**Comment by mookixiao** [comment]
我和你一样也是Dataloader最后一个batch处理完就会崩溃，我现在判断是因为引入了sklearn
#34781

**Comment by heavengate** [comment]
你用的Paddle那个版本，2.1.1版本里DataLoader有内存泄漏的bug，可以更新到2.1.2版本试一下

**Comment by stack-heap-overflow** [comment]
paddle2.1.2版本在windows下(CUDA 11.4+CUDNN 8.2)遇到同样问题，dataloader迭代结束后不停止，无报错直接崩溃退出。是个很影响使用的严重bug，希望开发者能重视下这个issue。
