### ISSUE TITLE
剪枝的效果在哪里体现？

### ISSUE THREAD

**Issue by zmdcs** [PaddlePaddle/Paddle#34791]
剪枝应该是对效率的影响，是影响训练时间还是预测时间呢？

**Comment by wanghaoshuang** [comment]
剪枝主要用于减少预测的时间。

**Comment by zmdcs** [comment]
预测时间在infer.py文件中并没有实现输出是吗？我该如何输出预测的时间呢？




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/Paddle"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年8月11日(星期三) 中午1:08
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PaddlePaddle/Paddle] 剪枝的效果在哪里体现？ (#34791)





 
剪枝主要用于减少预测的时间。
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by wanghaoshuang** [comment]
请问您用的哪个repo的infer.py? 可以再infer.py里加一些代码来统计infer的耗时，具体怎么加，需要咨询具体repo的维护者。
可以用python的time API: https://docs.python.org/3/library/time.html

**Comment by zmdcs** [comment]
用的PaddleDetection/static/tool里的，请问flops是跟时间效率有关的吗？如果使用paddle Detection里的yml文件训练，该如何输出flops呢？




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年8月16日(星期一) 中午11:52
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [PaddlePaddle/Paddle] 剪枝的效果在哪里体现？ (#34791)





 
请问您用的哪个repo的infer.py? 可以再infer.py里加一些代码来统计infer的耗时，具体怎么加，需要咨询具体repo的维护者。
 可以用python的time API: https://docs.python.org/3/library/time.html
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by wanghaoshuang** [comment]
可以参考：FAQ- https://github.com/PaddlePaddle/PaddleDetection/blob/defba316ce5fa8b2e36941fbba9c5b29a220084c/docs/tutorials/FAQ/FAQ第一期.md#faq第一期

>Q： 在tools/infer.py加入如下函数，得到FLOPs值为-1,请问原因？
A： 更新PaddleDetection到release/2.2或者develop分支，print_flops设为True即可打印FLOPs。

**Comment by zmdcs** [comment]
好的，谢谢------------------&nbsp;原始邮件&nbsp;------------------
***@***.***&gt;
发送时间:&nbsp;2021年8月17日(星期二) 晚上8:13
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PaddlePaddle/Paddle] 剪枝的效果在哪里体现？ (#34791)

**Comment by zmdcs** [comment]
infer.py中也没有print_flops选项呀？有输出flops的教程吗？





------------------ 原始邮件 ------------------
发件人:                                                                                                                        "PaddlePaddle/Paddle"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年8月17日(星期二) 晚上8:13
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PaddlePaddle/Paddle] 剪枝的效果在哪里体现？ (#34791)





 
可以参考：FAQ- https://github.com/PaddlePaddle/PaddleDetection/blob/defba316ce5fa8b2e36941fbba9c5b29a220084c/docs/tutorials/FAQ/FAQ第一期.md#faq第一期
  
Q： 在tools/infer.py加入如下函数，得到FLOPs值为-1,请问原因？
 A： 更新PaddleDetection到release/2.2或者develop分支，print_flops设为True即可打印FLOPs。
  
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
