### ISSUE TITLE
剪枝的比例对精度影响的图如何画？

### ISSUE THREAD

**Issue by zmdcs** [PaddlePaddle/Paddle#34792]
PaddleSlim模型压缩实践教学中，有一张剪裁的比例对精度影响的图，请问这张图是如何化出来的呢？

**Comment by wanghaoshuang** [comment]
PaddleSlim提供的接口可以产出一组数据，用于表示剪裁率和精度损失的对应关系，当前PaddleSlim没有提供对该数据进行可视化的接口，需要用户自己用Matplotlib或其它工具进行可视化。

**Comment by zmdcs** [comment]
在AIstudio中用Matplotlib画图不显示吗？




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年8月11日(星期三) 中午1:12
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [PaddlePaddle/Paddle] 剪枝的比例对精度影响的图如何画？ (#34792)





 
PaddleSlim提供的接口可以产出一组数据，用于表示剪裁率和精度损失的对应关系，当前PaddleSlim没有提供对该数据进行可视化的接口，需要用户自己用Matplotlib或其它工具进行可视化。
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by wanghaoshuang** [comment]
AIstudio应该是和notebook一样的，这个显式的问题再notebook中也有，可以再搜索引擎搜索关键字『notebook Matplotlib画图不显示』来排查下问题。

一个建议，在代码首行添加：
```%matplotlib inline```

**Comment by zmdcs** [comment]
嗯，已经解决了，确实是那行代码的原因，谢谢



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年8月16日(星期一) 中午11:49
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [PaddlePaddle/Paddle] 剪枝的比例对精度影响的图如何画？ (#34792)





 
AIstudio应该是和notebook一样的，这个显式的问题再notebook中也有，可以再搜索引擎搜索关键字『notebook Matplotlib画图不显示』来排查下问题。
 
一个建议，在代码首行添加：
 %matplotlib inline
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
