### ISSUE TITLE
用trt加速没效果tensorrt

### ISSUE THREAD

**Issue by CheQiXiao** [PaddlePaddle/Paddle#34797]
我想测试paddle + tensorrt 的加速效果，用官网上的例子测试，没看到效果，用不用trt几乎没有差异，我确信trt开启的时候，屏幕上已经明确打印用到了tensorrt。我的环境是 ubuntu18, cuda10.2, tensorrt 6.0, paddlepaddle-gpu 2.1.2.post101 (post102没找到）。例子就是官网上的 resnet50例子，代码如下

 

import numpy as np
import paddle.inference as paddle_infer
import time

 

def create_predictor():
config = paddle_infer.Config("./resnet50/inference.pdmodel", "./resnet50/inference.pdiparams")
config.enable_memory_optim()
config.enable_use_gpu(1000, 0)

# 打开TensorRT。此接口的详细介绍请见下文

# 把这行配置注释掉就没有trt了
config.enable_tensorrt_engine(workspace_size = 1 << 30,
max_batch_size = 1,
min_subgraph_size = 3,
precision_mode=paddle_infer.PrecisionType.Half,
use_static = False, use_calib_mode = False)

predictor = paddle_infer.create_predictor(config)
return predictor

def run(predictor, img):
# 准备输入
input_names = predictor.get_input_names()
for i, name in enumerate(input_names):
input_tensor = predictor.get_input_handle(name)
input_tensor.reshape(img[i].shape)
input_tensor.copy_from_cpu(img[i].copy())
# 预测

st=time.time()
predictor.run()
elapse=time.time()-st

**Comment by BillDior** [comment]
已经转给inference相关负责同学

**Comment by JianJingGao** [comment]
我这边也是 发现没变化

**Comment by magicly** [comment]
测试这个不对的， 因为gpu推理是异步的， 你应该发现这个时间非常短吧， 因为只是发送了“gpu，你给我推理吧“的命令， gpu并没有完成真的工作。 你把get output也放进去一起测试， 就会发现tensorrt快了。
> 
> # 预测
> st=time.time() predictor.run() elapse=time.time()-st
