### ISSUE TITLE
paddleDetection中statics里的模型用的iter和epoch+batch的有什么区别？

### ISSUE THREAD

**Issue by zmdcs** [PaddlePaddle/Paddle#34793]

**Comment by jerrywgz** [comment]
PaddleDetection静态图中是以iter的方式进行迭代，比如数据12w张图，单卡batch_size=2，iter=48w的话，相当于跑了48w个batch，也就是8个epoch

**Comment by zmdcs** [comment]
意思是，iter*batch_size/图片数量=epoch吗？




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年8月12日(星期四) 下午2:05
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [PaddlePaddle/Paddle] paddleDetection中statics里的模型用的iter和epoch+batch的有什么区别？ (#34793)





 
PaddleDetection静态图中是以iter的方式进行迭代，比如数据12w张图，单卡batch_size=2，iter=48w的话，相当于跑了48w个batch，也就是8个epoch
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by jerrywgz** [comment]
嗯是的

**Comment by zmdcs** [comment]
谢谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年8月12日(星期四) 晚上7:28
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [PaddlePaddle/Paddle] paddleDetection中statics里的模型用的iter和epoch+batch的有什么区别？ (#34793)





 
嗯是的
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
