### ISSUE TITLE
paddle2.1.2版本还是import paddle报错

### ISSUE THREAD

**Issue by ImComingyo** [PaddlePaddle/Paddle#34805]
试了最新的几个PaddlePaddle版本，都是from .core_avx import * 报错
ImportError: /lib64/libstdc++.so.6: version `CXXABI_1.3.11' not found

由于是在服务器上跑，没有权限更新gcc。。。
请问还有其他办法解决吗？

**Comment by yaoxuefeng6** [comment]
可以试试用下docker  没有权限更新gcc确实没啥别的办法
