### ISSUE TITLE
【NPU】ascend 310 遇到MemoryError

### ISSUE THREAD

**Issue by ABAPPLO** [PaddlePaddle/Paddle#34802]
昇腾NPU编译完成，测试通过，但是实际调用遇到MemoryError
- 版本、环境信息：
  1）PaddlePaddle版本：2.1.2   使用昇腾NPU编译。
  2）处理器： 鲲鹏920
  3）GPU：ascend 310
  4）系统环境：4.14.0-115.el7a.0.1.aarch64   centos 7.6

  5）CANN:20.3

- 编译文档：https://www.paddlepaddle.org.cn/documentation/docs/zh/guides/09_hardware_support/npu_docs/paddle_install_cn.html

- -验证代码：```python3 -c "import paddle; paddle.utils.run_check()"```

- -验证结果：

  ```bash
  XXX/python3.7.5/lib/python3.7/site-packages/setuptools/depends.py:2: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp
  Running verify PaddlePaddle program ... 
  PaddlePaddle works well on 1 CPU.
  W0811 14:58:44.160678 18852 fuse_all_reduce_op_pass.cc:76] Find all_reduce operators: 2. To make the speed faster, some all_reduce ops are fused during training, after fusion, the number of all_reduce ops is 2.
  I0811 14:58:44.161551 18852 parallel_executor.cc:476] Cross op memory reuse strategy is enabled, when build_strategy.memory_optimize = True or garbage collection strategy is disabled, which is not recommended
  PaddlePaddle works well on 2 CPUs.
  PaddlePaddle is installed successfully! Let's start deep learning with PaddlePaddle now.
  ```

- 测试信息

  ​    1）单机，单卡多卡

  ​    2）显存信息： 2703 / 8192  *4

  ​    3）代码：

  ```
  import paddle
  paddle.set_device('npu:0')
  a = paddle.rand([3,10], dtype='float32')
  print(a)
  ```

  ​    3）报错信息：

  ```basn
  Traceback (most recent call last):
    File "<stdin>", line 1, in <module>
    File "/usr/local/python3.7.5/lib/python3.7/site-packages/paddle/tensor/random.py", line 726, in rand
      return uniform(shape, dtype, min=0.0, max=1.0, name=name)
    File "/usr/local/python3.7.5/lib/python3.7/site-packages/paddle/tensor/random.py", line 504, in uniform
      float(max), 'seed', seed, 'dtype', dtype)
  MemoryError: 
  
  --------------------------------------
  C++ Traceback (most recent call last):
  --------------------------------------
  0   paddle::imperative::Tracer::TraceOp(std::string const&, paddle::imperative::NameVarBaseMap const&, paddle::imperative::NameVarBaseMap const&, paddle::framework::AttributeMap, std::map<std::string, std::string, std::less<std::string>, std::allocator<std::pair<std::string const, std::string> > > const&)
  1   paddle::imperative::Tracer::TraceOp(std::string const&, paddle::imperative::NameVarBaseMap const&, paddle::imperative::NameVarBaseMap const&, paddle::framework::AttributeMap, paddle::platform::Place const&, bool, std::map<std::string, std::string, std::less<std::string>, std::allocator<std::pair<std::string const, std::string> > > const&)
  2   paddle::imperative::PreparedOp::Run(paddle::imperative::NameVarBaseMap const&, paddle::imperative::NameVarBaseMap const&, paddle::framework::AttributeMap const&, paddle::framework::AttributeMap const&)
  3   paddle::framework::Tensor::mutable_data(paddle::platform::Place const&, paddle::framework::proto::VarType_Type, unsigned long)
  4   paddle::memory::AllocShared(paddle::platform::Place const&, unsigned long)
  5   paddle::memory::allocation::AllocatorFacade::AllocShared(paddle::platform::Place const&, unsigned long)
  6   paddle::memory::allocation::AllocatorFacade::Alloc(paddle::platform::Place const&, unsigned long)
  7   paddle::memory::allocation::NaiveBestFitAllocator::AllocateImpl(unsigned long)
  8   void* paddle::memory::legacy::Alloc<paddle::platform::NPUPlace>(paddle::platform::NPUPlace const&, unsigned long)
  9   paddle::memory::legacy::GetNPUBuddyAllocator(int)
  10  paddle::memory::legacy::NPUBuddyAllocatorList::Get(int)
  11  std::call_once<paddle::memory::legacy::NPUBuddyAllocatorList::Get(int)::{lambda()#1}>(std::once_flag&, paddle::memory::legacy::NPUBuddyAllocatorList::Get(int)::{lambda()#1}&&)::{lambda()#2}::_FUN()
  12  paddle::platform::NPUMaxChunkSize()
  13  paddle::platform::NPUMaxAllocSize()
  14  paddle::platform::EnforceNotMet::EnforceNotMet(paddle::platform::ErrorSummary const&, char const*, int)
  15  paddle::platform::GetCurrentTraceBackString()
  
  ----------------------
  Error Message Summary:
  ----------------------
  ResourceExhaustedError: Not enough available NPU memory.
    [Hint: Expected available_to_alloc > 0, but received available_to_alloc:0 <= 0:0.] (at /root/Paddle/paddle/fluid/platform/npu_info.cc:146)
    [operator < uniform_random > error]
  ```

麻烦你们测试一下，若测试没有问题，能否给一下测试结果（我这边目前不能确认是框架还是CANN的问题，ascend反馈是接口调用错误），感谢！

**Comment by baigang666** [comment]
> 昇腾NPU编译完成，测试通过，但是实际调用遇到MemoryError
> 
> * 版本、环境信息：
>   1）PaddlePaddle版本：2.1.2   使用昇腾NPU编译。
>   2）处理器： 鲲鹏920
>   3）GPU：ascend 310
>   4）系统环境：4.14.0-115.el7a.0.1.aarch64   centos 7.6
>   5）CANN:20.3
> * 编译文档：https://www.paddlepaddle.org.cn/documentation/docs/zh/guides/09_hardware_support/npu_docs/paddle_install_cn.html
> * -验证代码：`python3 -c "import paddle; paddle.utils.run_check()"`
> * -验证结果：
>   ```shell
>   XXX/python3.7.5/lib/python3.7/site-packages/setuptools/depends.py:2: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
>   import imp
>   Running verify PaddlePaddle program ... 
>   PaddlePaddle works well on 1 CPU.
>   W0811 14:58:44.160678 18852 fuse_all_reduce_op_pass.cc:76] Find all_reduce operators: 2. To make the speed faster, some all_reduce ops are fused during training, after fusion, the number of all_reduce ops is 2.
>   I0811 14:58:44.161551 18852 parallel_executor.cc:476] Cross op memory reuse strategy is enabled, when build_strategy.memory_optimize = True or garbage collection strategy is disabled, which is not recommended
>   PaddlePaddle works well on 2 CPUs.
>   PaddlePaddle is installed successfully! Let's start deep learning with PaddlePaddle now.
>   ```
> * 测试信息
>   ​    1）单机，单卡多卡
>   ​    2）显存信息： 2703 / 8192  *4
>   ​    3）代码：
>   ```
>   import paddle
>   paddle.set_device('npu:0')
>   a = paddle.rand([3,10], dtype='float32')
>   print(a)
>   ```
>   
>   
>       
>         
>       
>   
>         
>       
>   
>       
>     
>   ​    3）报错信息：
>   ```
>   Traceback (most recent call last):
>     File "<stdin>", line 1, in <module>
>     File "/usr/local/python3.7.5/lib/python3.7/site-packages/paddle/tensor/random.py", line 726, in rand
>       return uniform(shape, dtype, min=0.0, max=1.0, name=name)
>     File "/usr/local/python3.7.5/lib/python3.7/site-packages/paddle/tensor/random.py", line 504, in uniform
>       float(max), 'seed', seed, 'dtype', dtype)
>   MemoryError: 
>   
>   --------------------------------------
>   C++ Traceback (most recent call last):
>   --------------------------------------
>   0   paddle::imperative::Tracer::TraceOp(std::string const&, paddle::imperative::NameVarBaseMap const&, paddle::imperative::NameVarBaseMap const&, paddle::framework::AttributeMap, std::map<std::string, std::string, std::less<std::string>, std::allocator<std::pair<std::string const, std::string> > > const&)
>   1   paddle::imperative::Tracer::TraceOp(std::string const&, paddle::imperative::NameVarBaseMap const&, paddle::imperative::NameVarBaseMap const&, paddle::framework::AttributeMap, paddle::platform::Place const&, bool, std::map<std::string, std::string, std::less<std::string>, std::allocator<std::pair<std::string const, std::string> > > const&)
>   2   paddle::imperative::PreparedOp::Run(paddle::imperative::NameVarBaseMap const&, paddle::imperative::NameVarBaseMap const&, paddle::framework::AttributeMap const&, paddle::framework::AttributeMap const&)
>   3   paddle::framework::Tensor::mutable_data(paddle::platform::Place const&, paddle::framework::proto::VarType_Type, unsigned long)
>   4   paddle::memory::AllocShared(paddle::platform::Place const&, unsigned long)
>   5   paddle::memory::allocation::AllocatorFacade::AllocShared(paddle::platform::Place const&, unsigned long)
>   6   paddle::memory::allocation::AllocatorFacade::Alloc(paddle::platform::Place const&, unsigned long)
>   7   paddle::memory::allocation::NaiveBestFitAllocator::AllocateImpl(unsigned long)
>   8   void* paddle::memory::legacy::Alloc<paddle::platform::NPUPlace>(paddle::platform::NPUPlace const&, unsigned long)
>   9   paddle::memory::legacy::GetNPUBuddyAllocator(int)
>   10  paddle::memory::legacy::NPUBuddyAllocatorList::Get(int)
>   11  std::call_once<paddle::memory::legacy::NPUBuddyAllocatorList::Get(int)::{lambda()#1}>(std::once_flag&, paddle::memory::legacy::NPUBuddyAllocatorList::Get(int)::{lambda()#1}&&)::{lambda()#2}::_FUN()
>   12  paddle::platform::NPUMaxChunkSize()
>   13  paddle::platform::NPUMaxAllocSize()
>   14  paddle::platform::EnforceNotMet::EnforceNotMet(paddle::platform::ErrorSummary const&, char const*, int)
>   15  paddle::platform::GetCurrentTraceBackString()
>   
>   ----------------------
>   Error Message Summary:
>   ----------------------
>   ResourceExhaustedError: Not enough available NPU memory.
>     [Hint: Expected available_to_alloc > 0, but received available_to_alloc:0 <= 0:0.] (at /root/Paddle/paddle/fluid/platform/npu_info.cc:146)
>     [operator < uniform_random > error]
>   ```
> 
> 麻烦你们测试一下，若测试没有问题，能否给一下测试结果（我这边目前不能确认是框架还是CANN的问题，ascend反馈是接口调用错误），感谢！
您好  我最近也是和你一样在同样的平台编译paddle。
cmake：3.16
gcc：7.3.0
g++：7.3.0
但是遇到以下错误：
/home/SrcCode/Paddle2.1/Paddle/paddle/fluid/operators/math/blas_impl.h:653:26: 错误：‘CBLAS_LAYOUT’ does not name a type; did you mean ‘CBLAS_UPLO’?
   static void GEMV(const CBLAS_LAYOUT layout, const CBLAS_TRANSPOSE TransA,
                          ^~~~~~~~~~~~
                          CBLAS_UPLO
/home/SrcCode/Paddle2.1/Paddle/paddle/fluid/operators/math/blas_impl.h:664:26: 错误：‘CBLAS_LAYOUT’ does not name a type; did you mean ‘CBLAS_UPLO’?
   static void GEMM(const CBLAS_LAYOUT layout, const CBLAS_TRANSPOSE TransA,
                          ^~~~~~~~~~~~
                          CBLAS_UPLO
/home/SrcCode/Paddle2.1/Paddle/paddle/fluid/operators/math/blas_impl.h:691:26: 错误：‘CBLAS_LAYOUT’ does not name a type; did you mean ‘CBLAS_UPLO’?
   static void GEMV(const CBLAS_LAYOUT layout, const CBLAS_TRANSPOSE TransA,
                          ^~~~~~~~~~~~
                          CBLAS_UPLO
/home/SrcCode/Paddle2.1/Paddle/paddle/fluid/operators/math/blas_impl.h:702:26: 错误：‘CBLAS_LAYOUT’ does not name a type; did you mean ‘CBLAS_UPLO’?
   static void GEMM(const CBLAS_LAYOUT layout, const CBLAS_TRANSPOSE TransA,
                          ^~~~~~~~~~~~
                          CBLAS_UPLO
/home/SrcCode/Paddle2.1/Paddle/paddle/fluid/operators/math/blas_impl.h:1397:62: 错误：‘CBLAS_LAYOUT’未声明
 void Blas<platform::CPUDeviceContext>::TRSM(CBLAS_SIDE side, CBLAS_LAYOUT uplo,
                                                              ^~~~~~~~~~~~
/home/SrcCode/Paddle2.1/Paddle/paddle/fluid/operators/math/blas_impl.h:1397:6: 错误：‘void paddle::operators::math::Blas<paddle::platform::CPUDeviceContext>::TRSM(CBLAS_SIDE, int, CBLAS_TRANSPOSE, CBLAS_DIAG, int, int, T, const T*, int, T*, int) const’的模板标识符‘TRSM<>’不匹配任何模板声明
 void Blas<platform::CPUDeviceContext>::TRSM(CBLAS_SIDE side, CBLAS_LAYOUT uplo,
      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /home/SrcCode/Paddle2.1/Paddle/paddle/fluid/operators/math/blas.cc:15:0

可以帮忙看一下么？

**Comment by ABAPPLO** [comment]
@baigang666  你可以尝试按照这个来：https://www.paddlepaddle.org.cn/documentation/docs/zh/guides/09_hardware_support/npu_docs/paddle_install_cn.html，其中：gcc/g++ 版本与CANN版本和说明中的环境保持一致
