### ISSUE TITLE
【论文复现】单机多卡文档不清楚

### ISSUE THREAD

**Issue by frankwhzhang** [PaddlePaddle/Paddle#34808]
https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/guides/01_paddle2.0_introduction/update_cn.html#danjiduokaqidong

单机多卡的介绍中不清楚。按照文档中的实现，其实是每个卡都会训练一遍数据，但是和数据并行常见的每个卡只训练一部分数据是有矛盾的，希望文档在这里能说清楚。同时贴上每个卡只训练一部分的正确实现方法。

**Comment by thinkall** [comment]
> https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/guides/01_paddle2.0_introduction/update_cn.html#danjiduokaqidong
> 
> 单机多卡的介绍中不清楚。按照文档中的实现，其实是每个卡都会训练一遍数据，但是和数据并行常见的每个卡只训练一部分数据是有矛盾的，希望文档在这里能说清楚。同时贴上每个卡只训练一部分的正确实现方法。

得用 DistributedBatchSampler 吧

**Comment by littletomatodonkey** [comment]
你好，文档已经修复，感谢反馈~

https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/guides/02_paddle2.0_develop/06_device_cn.html
