### ISSUE TITLE
AssertionError: Can not find [conv2d_51.w_0] in model file [./output/det_db/best_accuracy.pdparams]

### ISSUE THREAD

**Issue by liuvvss** [PaddlePaddle/Paddle#34818]
为使您的问题得到快速解决，在建立Issue前，请您先通过如下方式搜索是否有相似问题:【搜索issue关键字】【使用labels筛选】【官方文档】

建立issue时，为快速解决问题，请您根据使用情况给出如下信息：
- 标题：请包含关键词“安装错误”/“编译错误”，例如“Mac编译错误”
- 版本、环境信息：
    1）PaddlePaddle版本：pp版本=2.1.2

    3）GPU：显卡2080ti，cuda 10.5，libcudnn.so.7.5.0
    4）系统环境：linux，python 3.7
- 安装方式信息：
1）pip安装
AssertionError: Can not find [conv2d_51.w_0] in model file [./output/det_db/best_accuracy.pdparams]
![image](https://user-images.githubusercontent.com/88772225/129008234-f8ee6790-fcdb-4032-a61a-8bb83682490e.png)
AssertionError: Can not find [conv2d_51.w_0] in model file [/home/igi/temTest/PaddleOCR-develop/output/det_db/best_accuracy.pdparams]
已经是绝对路径了

**Comment by yaoxuefeng6** [comment]
看起来是加载的模型没有其中一个变量，保存的模型和期望加载的模型是同一个吗？

**Comment by liuvvss** [comment]
> 嗎

是的啊
