### ISSUE TITLE
希望能实现gumbel_softmax

### ISSUE THREAD

**Issue by KinvenW** [PaddlePaddle/Paddle#34825]
[gumbel_softmax](https://pytorch.org/docs/stable/generated/torch.nn.functional.gumbel_softmax.html?highlight=gumbel_softmax#torch.nn.functional.gumbel_softmax)在决策相关的任务中还是很有用的，希望未来能增加对它的实现

**Comment by yaoxuefeng6** [comment]
收到，我们会评估添加下
