### ISSUE TITLE
训练加载数据报错

### ISSUE THREAD

**Issue by ziyaxuanyi** [PaddlePaddle/Paddle#34827]
开始训练正常，但经过几个tier以后，报错
DataLoader reader thread raised an exception.
all input arrays must have the same shape.

检查过，所有的数据加载的时候，都统一到了同一个尺寸。

**Comment by yaoxuefeng6** [comment]
有可复现得简易代码吗

**Comment by ziyaxuanyi** [comment]
解决了，不是paddle的问题。

**Comment by Shawn-fd** [comment]
> 解决了，不是paddle的问题。

请问是如何解决的呢？

**Comment by anidiatm41** [comment]
how the issue was fixed? I too getting same issue

**Comment by ziyaxuanyi** [comment]
> > 解决了，不是paddle的问题。
> 
> 请问是如何解决的呢？

仔细检查代码，一定是某个位置数据加载一个batch里面的某些数据，没有统一到相同的尺寸

**Comment by ziyaxuanyi** [comment]
> how the issue was fixed? I too getting same issue

Double-check the code, it must be somewhere the data loaded inside a batch of data, not unified to the same size

**Comment by jingmingtao** [comment]
请问是如何解决的
