### ISSUE TITLE
论文复现赛报名

### ISSUE THREAD

**Issue by xcs633018** [PaddlePaddle/Paddle#34831]
【队名】：好好学paddle

【序号】：100

【论文】： Deep Session Interest Network for Click-Through Rate Prediction

【状态】：报名

【repo链接】：[https://github.com/xcs633018/DSIN_paddle](https://github.com/xcs633018/DSIN_paddle)

**Comment by TCChenlong** [comment]
hi，你好，报名是回复这个ISSUE哦：https://github.com/PaddlePaddle/Paddle/issues/34526
