### ISSUE TITLE
敏感度分析跟所用数据集的分类和种类有关系吗？

### ISSUE THREAD

**Issue by zmdcs** [PaddlePaddle/Paddle#34858]
比如固定的80个种类，我换成一类；原先的猫猫狗狗的图片换成车的图片之类的会不会对敏感度分析产生影响？还是说只要是voc格式的数据，以及模型是yolo_mobile卷积层敏感度就是固定的，与数据毫无关系？

**Comment by wanghaoshuang** [comment]
敏感度分析是和数据强相关的，最好使用接近真实分布的数据集。

>原先的猫猫狗狗的图片换成车的图片之类的会不会对敏感度分析产生影响？
会产生影响

**Comment by iclementine** [comment]
图像分类的问题，我转一下相关的同学。
