### ISSUE TITLE
Building PaddlePaddle from Emacs as an IDE

### ISSUE THREAD

**Issue by wangkuiyi** [PaddlePaddle/Paddle#3485]
Here are the steps that I build PaddlePaddle from source code in Emacs as an IDE.  I don't need to install any building tools on my computer; instead, my Emacs calls Docker image to build PaddlePaddle.

### Install Tools

1. Emacs
1. Docker

### Get the Source Code

```bash
cd ~/somewhere
git clone https://github.com/PaddlePaddle/Paddle
```

### Build the Docker image

```bash
cd ~/somewhere/Paddle
docker build -t paddle:dev .
```

### Build PaddlePaddle

```bash
mkdir ~/somewhere/Paddle/build
docker run --rm -it -v $PWD:/paddle paddle:dev /bin/bash
$ cd /paddle/build
$ cmake -DCUDNN_ROOT=/usr ..
$ make -j8 # Build PaddlePaddle from source code.
$ ctest # Run all unit tests.
```

### Build from IDE

I am using Emacs as my IDE.  

1. Add the following two lines to `~/.emacs`:

   ```elisp
   (global-set-key "\C-cc" 'compile)
   (setq compile-command "docker run --rm -it -v $(git rev-parse --show-toplevel):/paddle paddle:dev")
   ```
1. Open a file in `~/somewhere/Paddle` and type `C-c C-c`, Emacs would run the `docker run` command to build PaddlePaddle. A screenshot for your reference:

   <img width="994" alt="screen shot 2017-08-14 at 6 03 00 pm" src="https://user-images.githubusercontent.com/1548775/29298331-c94d91c2-811b-11e7-9380-2f2ee63b5eaa.png">

**Comment by wangkuiyi** [comment]
We should add above comment somewhere as a document.

**Comment by luotao1** [comment]
How about place this document in 
- 中文版本放在：[进阶指南/开发标准](http://doc.paddlepaddle.org/develop/doc_cn/howto/index_cn.html#id3)
- English version: [Howto/develop](http://doc.paddlepaddle.org/develop/doc/howto/index_en.html#development)

**Comment by putcn** [comment]
should we document it as `C-c c` other than `C-c C-c`?
