### ISSUE TITLE
【论文复现】paddle.sum() 算子对待 bool 类型的态度应该向 numpy 和 pytorch 看齐

### ISSUE THREAD

**Issue by S-HuaBomb** [PaddlePaddle/Paddle#34863]
如题，建议 bool 类型的 `paddle.Tensor` 输入 `paddle.sum()` 应该看成 `0/1` 计算，像 numpy 和 pytorch 一样。

- 版本、环境信息
1）PaddlePaddle版本：2.1.2
2）CPU/GPU：CPUPlace
3）系统环境：Windows 10

- 复现信息：`paddle.sum()` 在计算由 bool 类型组成的 Tensor 时似乎是逻辑或操作，只要有元素为 True 则输出 `True`，否则输出 `False`：

  ![e581478a880936fbf0ad0771beb599c](https://user-images.githubusercontent.com/39048551/129211579-ada16d41-f5ea-4e85-8824-b81ce856cf6b.png)

  同样的算子，numpy 和 pytorch 的输出都是元素为 True 的总数：
  
  ![image](https://user-images.githubusercontent.com/39048551/129212359-066a6dcc-feb0-48fd-833b-d21280e411af.png)

 
- 建议描述：建议 `paddle.sum()` 在计算由 bool 类型组成的 Tensor 时应该输出跟 numpy（`np.sum()`） 和 pytorch（`torch.sum()`） 一样的结果。

**Comment by iclementine** [comment]
谢谢反馈。目前 paddle 的 sum 使用的是和 eigen 一致的语义。 bool sum 的结果仍然是 bool, 所以值是 true, 是否提升成 int 来计算目前正在讨论中。
