### ISSUE TITLE
剪枝后yml文件变化了吗？

### ISSUE THREAD

**Issue by zmdcs** [PaddlePaddle/Paddle#34872]
进行剪枝操作后，再次进行敏感度分析时，剪枝时被剪掉的卷积层显示没有了，这是不是意味着进行剪枝操作时修改了yml，还是修改了原本的网络结构？

**Comment by wanghaoshuang** [comment]
剪枝不会修改yml文件，只会修改原本的网络结构。

**Comment by zmdcs** [comment]
那他修改的是哪个后缀名的文件，修改的网络结构呢？我剪枝后再去打印网络结构确实网络结构发生了改变，但是传参数的时候只传了yml文件和网络结构有点关系呀？



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年8月16日(星期一) 中午11:37
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [PaddlePaddle/Paddle] 剪枝后yml文件变化了吗？ (#34872)





 
剪枝不会修改yml文件，只会修改原本的网络结构。
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
