### ISSUE TITLE
【论文复现】关于pytorch中对rnn数据处理操作utils.rnn.pack_padded_sequence

### ISSUE THREAD

**Issue by Ming-360** [PaddlePaddle/Paddle#34898]
您好，我在代码复现过程中遇到pytorch中对rnn数据处理操作rnn.pack_padded_sequence
该方法全名为: torch.nn.utils.rnn.pack_padded_sequence()
其功能为对输入rnn中的数据进行压缩处理，现未在paddle Api中找到相关实现
希望老师能针对此问题给予指导，谢谢！

**Comment by ZiMo-Chen** [comment]
是否已解决？我也碰到相同的问题

**Comment by Ming-360** [comment]
> 是否已解决？我也碰到相同的问题

还没解决

**Comment by Aurelius84** [comment]
感谢您的反馈，推荐您先padding成等长batch的数据进行处理。目前paddle暂无类似的接口，我们会尽快评估和支持。

**Comment by Aurelius84** [comment]
另外，paddle提供了对RNN cell的封装类：https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/nn/RNN_cn.html#rnn，可以基于此cell进行自定义的mask操作。

**Comment by Ming-360** [comment]
> 另外，paddle提供了对RNN cell的封装类：[https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/nn/RNN_cn.html#rnn，可以基于此cell进行自定义的mask操作。](https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/nn/RNN_cn.html#rnn%EF%BC%8C%E5%8F%AF%E4%BB%A5%E5%9F%BA%E4%BA%8E%E6%AD%A4cell%E8%BF%9B%E8%A1%8C%E8%87%AA%E5%AE%9A%E4%B9%89%E7%9A%84mask%E6%93%8D%E4%BD%9C%E3%80%82)

好的，感谢您的反馈
