### ISSUE TITLE
【论文复现】paddle实现模型学习率剪枝问题

### ISSUE THREAD

**Issue by Lieberk** [PaddlePaddle/Paddle#34896]
在论文复现过程中，遇到了模型学习率剪枝问题，pytorch的源代码如下：
`def clip_gradient(optimizer, grad_clip):
    for group in optimizer.param_groups:
        for param in group['params']:
            param.grad.data.clamp_(-grad_clip, grad_clip)`

paddle里面没有param_groups这个属性，那么如何用paddle复现上述的pytorch代码，希望能得到老师的指点。

**Comment by wanghaoshuang** [comment]
可以参考这个API获取所有parameters： https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/nn/Layer_cn.html#parameters

另外，不建议将『clip』翻译为『剪枝』。
