### ISSUE TITLE
paddle中如何实现torch的repeat操作

### ISSUE THREAD

**Issue by huilin16** [PaddlePaddle/Paddle#34903]
paddle中如何实现torch的repeat操作

**Comment by JunnYu** [comment]
https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/tile_cn.html#tile

**Comment by Aurelius84** [comment]
> https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/tile_cn.html#tile

感谢回答，在paddle中可以通过 `paddle.tile(x, repeat_times, name=None)`可以实现repeat功能
