### ISSUE TITLE
max_iters和snapshot_iter可以不设置吗？

### ISSUE THREAD

**Issue by zmdcs** [PaddlePaddle/Paddle#34904]
只想保存最优的模型，以及不确定多少代才是最优，有什么办法吗？不设置最大训练代数可以一直训练到内存满吗？不设置中途保存可以只保存最终模型和最优模型吗？

**Comment by LDOUBLEV** [comment]
可以加一个保存模型的逻辑，在训练中做评估，比较每次的评估指标，保存最优评估指标的模型即可

**Comment by zmdcs** [comment]
这个似乎是train.py函数自带的，我是希望中途能不存不要的模型，这样不会导致程序过大




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年8月16日(星期一) 上午10:08
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [PaddlePaddle/Paddle] max_iters和snapshot_iter可以不设置吗？ (#34904)





 
可以加一个保存模型的逻辑，在训练中做评估，比较每次的评估指标，保存最优评估指标的模型即可
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by LDOUBLEV** [comment]
> 这个似乎是train.py函数自带的，我是希望中途能不存不要的模型，这样不会导致程序过大
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: ***@***.***&gt;; 发送时间: 2021年8月16日(星期一) 上午10:08 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; ***@***.***&gt;; 主题: Re: [PaddlePaddle/Paddle] max_iters和snapshot_iter可以不设置吗？ (#34904) 可以加一个保存模型的逻辑，在训练中做评估，比较每次的评估指标，保存最优评估指标的模型即可 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.


train.py函数里的逻辑是可以修改的，如果你当前保存的模型和上次保存的模型名字是一样的，会覆盖掉之前的；
或者每次保存最新模型的时候删除掉之前保存的模型也可以

你用的是哪个模型和算法，我看下保存模型的逻辑
