### ISSUE TITLE
【论文复现】bool 型Tensor 不支持取反操作

### ISSUE THREAD

**Issue by TCChenlong** [PaddlePaddle/Paddle#34905]
paddle 版本：2.1.2
需求：bool 型 Tensor 支持取反操作
复现如图：
![image](https://user-images.githubusercontent.com/11935832/129468858-38af0ded-d018-4244-9d4d-9191820b3009.png)

**Comment by LDOUBLEV** [comment]
可以用其他方法实现，代码如下：
```
import paddle 

def negate(t):
    t = paddle.cast(t, int)
    tmp = paddle.ones_like(t) - t
    return paddle.cast(tmp, bool)


a = paddle.to_tensor([False, True])
print(f"a: {a}")
b = negate(a)
print(f"b: {b}")
```
![image](https://user-images.githubusercontent.com/26592129/129502737-6e398050-5593-4251-a91b-382f76917422.png)
