### ISSUE TITLE
from paddle.autograd import PyLayer报错:No module named 'paddle.autograd'

### ISSUE THREAD

**Issue by youlingforever0328** [PaddlePaddle/Paddle#34919]
在自定义Python算子时:
from paddle.autograd import PyLayer 报错:No module named 'paddle.autograd'

PaddlePaddle版本：2.0.2
Python3.7

**Comment by wangxicoding** [comment]
![image](https://user-images.githubusercontent.com/10208305/129524863-d0f4ab07-54ab-4a4e-b134-e4c8eba2dcef.png)
https://www.paddlepaddle.org.cn/documentation/docs/zh/release_note_cn.html
您好，该API是2.1.2新增的API，需要使用最新的Paddle版本
