### ISSUE TITLE
split出错

### ISSUE THREAD

**Issue by maydaygmail** [PaddlePaddle/Paddle#34914]
paddle 版本：1.5.2
问题：
prob = layers.softmax(predict, use_cudnn=True)
prob_tec = layers.log(prob) 

p, q = layers.split(prob, num_or_sections=2, dim=0)
p_tec, q_tec = layers.split(prob_tec, num_or_sections=2, dim=0)

其中，prob shape是[batch, len, dim]，目的是要把prob和prob_tec按照batch都平分，
p, q = layers.split(prob, num_or_sections=2, dim=0) 正常
p_tec, q_tec = layers.split(prob_tec, num_or_sections=2, dim=0)  报错：
in split
    'axis': dim
  File "src/model.py", line 589, in transformer
    p_tec, q_tec = layers.split(prob_tec, num_or_sections=2, dim=0)
  File "src/train.py", line 641, in train
    is_test=False)
  File "src/train.py", line 745, in <module>
    train(args)
C++ Call stacks:
Cannot find variable split_1.tmp_0@GRAD at [/paddle/paddle/fluid/framework/op_desc.cc:195]

**Comment by wangxicoding** [comment]
需要固定1.5.2版本吗，之后的一些版本或者最新的版本试试？

**Comment by maydaygmail** [comment]
程序主体都是基于1.5.2的，升级的成本太大了

**Comment by maydaygmail** [comment]
> 需要固定1.5.2版本吗，之后的一些版本或者最新的版本试试？

程序主体都是基于1.5.2的，升级的成本太大了
