### ISSUE TITLE
'NoneType' object has no attribute 'copy'

### ISSUE THREAD

**Issue by NabilahMazlan** [PaddlePaddle/Paddle#34923]
I have a problem with extracting the details for the image. I am just copying and pasting codes from the Installation guide and it gave me this error. 
![image](https://user-images.githubusercontent.com/41096961/129520053-09ad479d-bf24-4f97-8506-1f8f2c8f32c7.png)

**Comment by wangxicoding** [comment]
Wrong information should be caused by `img` is None. You should check the `img`
