### ISSUE TITLE
非SGD优化器在回传时(optimizer.minimize(loss))报错：InvalidArgumentError: Tensor holds the wrong type, it holds float, but desires to be double.

### ISSUE THREAD

**Issue by gongchenting** [PaddlePaddle/Paddle#34920]
使用Adam或者Momentum等优化器时，在optimizer.minimize(loss)这一步会报如下错误：
InvalidArgumentError: Tensor holds the wrong type, it holds float, but desires to be double.
[Hint: Expected valid == true, but received valid:0 != true:1.] at (/paddle/paddle/fluid/framework/tensor_impl.h:33)
  [operator < adam > error]
我把loss转换成float64后，它又报错：
InvalidArgumentError: Tensor holds the wrong type, it holds double, but desires to be float.

但是，当我把优化器换成SGD后就没问题了，请问这是为什么呢？

环境：paddlepaddle1.7.1，k40

**Comment by wangxicoding** [comment]
网络中有使用到double的地方吗？
可以开一下环境变量 export GLOG_v=3， 看看是执行到具体哪个adam op出的问题
另外再把program打印出来，对照一下
``` python
        with open("main_prog.txt", "w") as fout:
            try:
                # compatible with paddle version <= 1.8
                from paddle.fluid.transpiler.details import program_to_code
                program_to_code(fluid.default_main_program(), fout=fout)
            except ImportError:
                fout.write(str(fluid.default_main_program()))
```
