### ISSUE TITLE
log_softmax

### ISSUE THREAD

**Issue by maydaygmail** [PaddlePaddle/Paddle#34921]
log_softmax 不同版本的实现方式也不同？

1.8
https://www.paddlepaddle.org.cn/documentation/docs/zh/1.8/api_cn/layers_cn/log_softmax_cn.html#log-softmax
2.0
https://www.paddlepaddle.org.cn/documentation/docs/zh/2.0/api/paddle/nn/functional/activation/log_softmax_cn.html#log-softmax

看上面的公式，1.8对应的log_softmax应该是错误的，2.0的才是正确的？

**Comment by wangxicoding** [comment]
是的，2.0中是正确的，1.8中是错误的，里面的公式是Sigmoid的公式
