### ISSUE TITLE
SetNumThreads崩溃

### ISSUE THREAD

**Issue by todaysky1234** [PaddlePaddle/Paddle#34932]
为使您的问题得到快速解决，在建立Issue前，请您先通过如下方式搜索是否有相似问题:【搜索issue关键字】【使用labels筛选】【官方文档】
调用推理过程异常；本地编译的paddle 2.0.2 GPU版本。

跟踪到错误处：
  // no matter with or without MKLDNN
  paddle::platform::SetNumThreads(config_.cpu_math_library_num_threads());

错误内容：
0x00007FFB5FA34ED9 处(位于 Lesson02.exe 中)有未经处理的异常: Microsoft C++ 异常: paddle::platform::EnforceNotMet，位于内存位置 0x000000633B6FF2F0 处。

- 版本、环境信息：
    1）PaddlePaddle版本：请提供您的PaddlePaddle版本号（如1.1）或CommitID
paddle 2.0.2 
    2）CPU：预测若用CPU，请提供CPU型号，MKL/OpenBlas/MKLDNN/等数学库使用情况
intel i7 7700k

mkldnn？编译时github自动下的，未查到版本信息

    3）GPU：预测若用GPU，请提供GPU型号、CUDA和CUDNN版本号
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2019 NVIDIA Corporation
Built on Wed_Oct_23_19:32:27_Pacific_Daylight_Time_2019
Cuda compilation tools, release 10.2, V10.2.89
cudnn 7.5

    4）系统环境：windows10  vs2017

**Comment by wangxicoding** [comment]
您好，有没有更详细的报错信息

**Comment by todaysky1234** [comment]
1、推理使用的代码： https://github.com/PaddlePaddle/Paddle-Inference-Demo/blob/release%2Fv1.8/c%2B%2B/resnet50/resnet50_test.cc 
2、paddle 2.0.2 ：https://github.com/PaddlePaddle/Paddle/tree/v2.0.2

3、win10+ vs2017 +cmake 3.19.5 + cuda  V10.2.89 + cudnn 7.6.5 

cmake .. -G "Visual Studio 15 2017 Win64" -DCMAKE_BUILD_TYPE=Release -DWITH_GPU=ON -DWITH_TESTING=OFF -DWITH_FLUID_ONLY=ON -DCUDA_TOOLKIT_ROOT_DIR="C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v10.2"  -DWITH_PYTHON=NO 

4、编译可得到dll 和lib；

使用resnet50的示例代码，执行时如上所述的错误出现。

不知这些信息是否充分，还需要哪些信息请直接告诉我

控制台显示的信息：
WARNING: Logging before InitGoogleLogging() is written to STDERR
E0816 18:02:33.570703 28376 paddle_pass_builder.cc:159] GPU not support MKLDNN yet
E0816 18:02:33.592643 28376 paddle_pass_builder.cc:159] GPU not support MKLDNN yet
E0816 18:02:33.592643 28376 paddle_pass_builder.cc:159] GPU not support MKLDNN yet
W0816 18:02:33.592643 28376 analysis_predictor.cc:1152] Deprecated. Please use CreatePredictor instead.
E0816 18:03:06.407681 28376 paddle_pass_builder.cc:159] GPU not support MKLDNN yet
I0816 18:03:06.409677 28376 analysis_predictor.cc:155] Profiler is deactivated, and no profiling report will be generated.

**Comment by jiweibo** [comment]
从您的描述中目前不太能发现是什么导致的问题，您可以使用官网下载的预测库试下呢，https://paddleinference.paddlepaddle.org.cn/user_guides/download_lib.html#id2
