### ISSUE TITLE
 Cudnn error, CUDNN_STATUS_NOT_INITIALIZED

### ISSUE THREAD

**Issue by jinxing94** [PaddlePaddle/Paddle#34938]
版本信息：
python3.6， paddle2.1,  cuda 10.2,  cudnn8.2,  driver 440.33.01 。

>>> paddle.set_device("cpu")
CPUPlace
>>> emb = paddle.create_parameter([3, 3], dtype="float32")
>>> prnit(emb)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'prnit' is not defined
>>> print(emb)
Parameter containing:
Tensor(shape=[3, 3], dtype=float32, place=CPUPlace, stop_gradient=False,
       [[-0.80931914, -0.00134873,  0.93233860],
        [-0.05148190, -0.27370077, -0.58787775],
        [ 0.20014048, -0.99166054,  0.60008991]])
>>> paddle.set_device("gpu")
CUDAPlace(0)
>>> import numpy as np
>>> a = np.zeros([3])
>>> pd_a = paddle.to_tensor(a)
>>> print(pd_a)
Tensor(shape=[3], dtype=float64, place=CUDAPlace(0), stop_gradient=True,
       [0., 0., 0.])
>>> emb = paddle.create_parameter([3, 3], dtype="float32")
W0816 10:46:37.607583 16306 device_context.cc:404] Please NOTE: device: 0, GPU Compute Capability: 3.5, Driver API Version: 10.2, Runtime API Version: 10.2
W0816 10:46:37.613322 16306 device_context.cc:422] device: 0, cuDNN Version: 8.2.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/root/Projects/.envs/kge/lib/python3.6/site-packages/paddle/fluid/layers/tensor.py", line 138, in create_parameter
    default_initializer)
  File "/root/Projects/.envs/kge/lib/python3.6/site-packages/paddle/fluid/layer_helper_base.py", line 374, in create_parameter
    **attr._to_kwargs(with_initializer=True))
  File "/root/Projects/.envs/kge/lib/python3.6/site-packages/paddle/fluid/framework.py", line 2895, in create_parameter
    initializer(param, self)
  File "/root/Projects/.envs/kge/lib/python3.6/site-packages/paddle/fluid/initializer.py", line 572, in __call__
    stop_gradient=True)
  File "/root/Projects/.envs/kge/lib/python3.6/site-packages/paddle/fluid/framework.py", line 2925, in append_op
    kwargs.get("stop_gradient", False))
  File "/root/Projects/.envs/kge/lib/python3.6/site-packages/paddle/fluid/dygraph/tracer.py", line 45, in trace_op
    not stop_gradient)
OSError: (External)  Cudnn error, CUDNN_STATUS_NOT_INITIALIZED  (at /paddle/paddle/fluid/platform/device_context.h:371)
  [operator < uniform_random > error]

**Comment by wangxicoding** [comment]
是不是cudnn没有安装对，可以检查一下cudnn的版本，`paddle.device.get_cudnn_version()
 ` https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/device/get_cudnn_version_cn.html#get-cudnn-version
如果没有安装对，可以参考一下官网里的安装。
https://www.paddlepaddle.org.cn/install/quick?docurl=/documentation/docs/zh/develop/install/pip/linux-pip.html
![image](https://user-images.githubusercontent.com/10208305/129557615-72b6bc7f-7e39-4718-8462-5048a89e1fa7.png)

**Comment by jinxing94** [comment]
paddle.device.get_cudnn_version()
8202,  请问CUDNN v7.6+ 包括cudnn 8.2吗？

**Comment by jinxing94** [comment]
跑pytorch是没问题的

**Comment by jinxing94** [comment]
类似issue别人也提过，https://github.com/PaddlePaddle/Paddle/issues/34557

**Comment by wangxicoding** [comment]
> paddle.device.get_cudnn_version()
> 8202, 请问CUDNN v7.6+ 包括cudnn 8.2吗？

应该是包括的

**Comment by wangxicoding** [comment]
我本地测试没有问题。
![image](https://user-images.githubusercontent.com/10208305/129559117-4bf9109e-5d7a-4609-b690-e9141e821970.png)

之前的whl包都是有cuda、cudnn版本号的，最新的都给取消了，不知道是不是和这个有关系。
![image](https://user-images.githubusercontent.com/10208305/129559534-ae318d16-c726-4087-9c74-325209f5d2a8.png)
你那边方便升级驱动吗，试试升级一下cuda的驱动到cuda11

**Comment by jinxing94** [comment]
pip安装的版本是2.1.2

**Comment by wangxicoding** [comment]
![image](https://user-images.githubusercontent.com/10208305/129561996-2edd8c99-6af1-4271-9299-1b1443f8788d.png)
试一下 python -m pip install paddlepaddle-gpu==2.1.2.post102 -f https://www.paddlepaddle.org.cn/whl/linux/mkl/avx/stable.html

**Comment by jinxing94** [comment]
找不到102, 101试了下，也不行

**Comment by wangxicoding** [comment]
cudnn版本切成7.6的看看行不行🤣

**Comment by wangxicoding** [comment]
或者可以直接使用docker，看看行不行，https://www.paddlepaddle.org.cn/install/quick?docurl=/documentation/docs/zh/install/docker/linux-docker.html
![image](https://user-images.githubusercontent.com/10208305/129725053-f01e69be-9718-4de8-a3c0-47bcb99d98b2.png)

**Comment by jinxing94** [comment]
cudnn版本切成7.6可以
