### ISSUE TITLE
crash when disable WITH_SWIG_PY

### ISSUE THREAD

**Issue by tensor-tang** [PaddlePaddle/Paddle#3494]
My command is 

> cmake .. -DWITH_GPU=OFF -DWITH_SWIG_PY=OFF -DWITH_STYLE_CHECK=OFF -DWITH_TESTING=OFF  -DWITH_DSO=OFF
make all -j `nproc`
make install

Then got 

> make[2]: *** No rule to make target `../python/python_api_wheel', needed by `python/CMakeFiles/paddle_python'.  Stop.
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [python/CMakeFiles/paddle_python.dir/all] Error 2
make: *** [all] Error 2

Maybe forgot some conditions in `python/CMakeFiles.txt`?

**Comment by luotao1** [comment]
WITH_SWIG_PY: 是否编译PYTHON的SWIG接口，该接口可用于预测和定制化训练,取决于是否寻找到SWIG

**Comment by tensor-tang** [comment]
嗯，是的。
既然是一个可以供选择的开关，那么关掉应该也是可以过的才对。

**Comment by luotao1** [comment]
我能复现这个bug。
