### ISSUE TITLE
如何将tensorflow的tensor数据转化为paddle的输入数据

### ISSUE THREAD

**Issue by ImComingyo** [PaddlePaddle/Paddle#34944]
ernie = ErnieModel.from_pretrained('ernie-1.0')

char_id_sequences、mask_sequences都是tensorflow版本模型的输入数据，
1）使用paddle.to_tensor
ernie_output_layer, ernie_pooled_output = ernie(input_ids=paddle.to_tensor(char_id_sequences),
										attention_mask=paddle.to_tensor(mask_sequences),
										token_type_ids=None)
Error：paddle.to_tensor不支持tf.tensor 转paddle.tensor

2）直接输入
ernie_output_layer, ernie_pooled_output = ernie(input_ids=char_id_sequences,
										attention_mask=mask_sequences,
										token_type_ids=None)
Error：ErnieEmbeddings中的ones = paddle.ones_like(input_ids, dtype="int64") 处报错，说input_ids不是paddle.tensor

请问有什么方法能将tensorflow版tensor转成paddle版的tensor，以至paddle.ones_like不会报错吗？

**Comment by wangxicoding** [comment]
可以先将tensorflow的tensor转为numpy，再使用to_tensor转为paddle的tensor。
如何转换tensorflow的tensor为numpy，可参考 https://stackoverflow.com/questions/34097281/convert-a-tensor-to-numpy-array-in-tensorflow

**Comment by ImComingyo** [comment]
> 可以先将tensorflow的tensor转为numpy，再使用to_tensor转为paddle的tensor。
> 如何转换tensorflow的tensor为numpy，可参考 https://stackoverflow.com/questions/34097281/convert-a-tensor-to-numpy-array-in-tensorflow

哎，链接里的方式也都试过了，都无法解决'Tensor' object has no attribute 'numpy'的问题（我是tensorflow 2.6版）

**Comment by wangxicoding** [comment]
![image](https://user-images.githubusercontent.com/10208305/130232349-4bbabefa-c19d-46e6-962a-924f0c237f89.png)
可以吧，我用的也是tf2.6版本
