### ISSUE TITLE
paddle gpu版本加载paddlenlp模型报错,cpu版本无问题

### ISSUE THREAD

**Issue by fangxiang00** [PaddlePaddle/Paddle#34958]
1）PaddlePaddle版本：2.1.1
  2）GPU：CUDA10.2  CUDNN7.6.5
  3）系统环境：linux18.04，Python3.8
  4)  paddlenlp版本: 2.0.7

- 代码：
import paddle
import paddlenlp
model = paddlenlp.transformers.EernieGramModel.from_pretrained("ernie-gram-zh")

----------------------------
paddle cpu运行没有问题
---------------------------
- 报错：

W0817 13:38:57.406621 39757 device_context.cc:404] Please NOTE: device: 0, GPU Compute Capability:5.2, Driver API Version:10.2, Runtime API Version: 10.2

-----------------------------------------
C++ Traceback (most recent call last):
-----------------------------------------
0  paddle::framework::SignalHandle(char const*, int)
1  paddle::platform::GetCurrentTraceBackString[abi:cxx11]()

---------------------------
Error Message Summary:
---------------------------
FatalError: 'Segmentation fault' is detected by the operating system.
     [TimeInfo: *** Aborted at 1629178737 (unix time) try "data -d @1629178737" if you are using GNU date ***]
     [SignalInfo: *** SIGSEGV (@0x0) received by PID 39757 (TID 0x7f94ba663740) from PID 0 ***]
段错误（吐核）

![image](https://user-images.githubusercontent.com/28780268/129670117-a6b7fcbc-6fef-41c9-b898-ab675d37c7ee.png)

**Comment by JZ-LIANG** [comment]
是单机单卡还是单机多卡？

**Comment by JZ-LIANG** [comment]
请使用环境变量： export GLOG_v=5 提供更多信息的log

**Comment by fangxiang00** [comment]
> 是单机单卡还是单机多卡？

单机单卡

**Comment by fangxiang00** [comment]
> 请使用环境变量： export GLOG_v=5 提供更多信息的log

完整报错信息如下
![image](https://user-images.githubusercontent.com/28780268/129833042-dc4a45c7-fe34-4cde-80d9-857a1ee92a97.png)

**Comment by JZ-LIANG** [comment]
从报错栈无法找到明显错误原因， 只能看到运行到模型参数初始化阶段（uniform_random）.
并且本地使用你提供的代码能够正常跑通，无法复现你指出的问题
（除了你提供的代码里有一个拼写错误外： EernieGramModel --> ErnieGramModel）
![image](https://user-images.githubusercontent.com/38102074/129855825-1197edf5-2b16-4a1b-859d-6f750389dae1.png)

![image](https://user-images.githubusercontent.com/38102074/129856197-de6182b2-3a05-4150-a92d-abac4d450a2f.png)

![image](https://user-images.githubusercontent.com/38102074/129856289-c7eaf628-3cd1-4f68-8ad0-67518bb48c0b.png)

程序正常运行到结束

**Comment by JZ-LIANG** [comment]
建议尝试核对环境问题： gpu 显存是否OOM， 模型下载路径等

**Comment by fangxiang00** [comment]
> 建议尝试核对环境问题： gpu 显存是否OOM， 模型下载路径等

你好，排查问题发现是cudnn版本没对上，请问有7.0对应的安装包吗
![image](https://user-images.githubusercontent.com/28780268/130192211-beab9edc-6cc8-4cdf-91e8-a9a57d5d2880.png)

**Comment by jerry90** [comment]
一样出现这个问题

**Comment by fangxiang00** [comment]
> 建议尝试核对环境问题： gpu 显存是否OOM， 模型下载路径等

问题已解决，是服务器与paddle环境cudnn版本冲突导致，感谢回复
