### ISSUE TITLE
如何在paddlenlp机器翻译框架中导入已训练好的预训练语言模型？

### ISSUE THREAD

**Issue by q178** [PaddlePaddle/Paddle#34960]
使用init_from_pretrain_model: ""# path of trained parameter, to make prediction参数要求的是.pdparams文件

**Comment by q178** [comment]
参数说明是这个：# path of the pretrain model, to better solve the current task

**Comment by JZ-LIANG** [comment]
预测模型保存时有两个文件：
pdparams： 参数信息文件
pdopt： 组网信息文件

模型的saveload可以参考这个文档：
https://www.paddlepaddle.org.cn/documentation/docs/zh/guides/02_paddle2.0_develop/08_model_save_load_cn.html

**Comment by q178** [comment]
不是，我的意思是模型能否导入预训练模型，如bert之类，如果可以，使用什么命令或参数？
