### ISSUE TITLE
官网paddle 2.1分支的文档附录没有jetpack4.4

### ISSUE THREAD

**Issue by PhilCuriosity** [PaddlePaddle/Paddle#34971]
官网paddle 2.1分支的文档附录没有jetpack4.4，请问是下架去重新编译了吗

**Comment by wangye707** [comment]
这里https://paddleinference.paddlepaddle.org.cn/user_guides/download_lib.html

**Comment by PhilCuriosity** [comment]
> 这里https://paddleinference.paddlepaddle.org.cn/user_guides/download_lib.html

好的，谢谢
