### ISSUE TITLE
不支持LD_LIBRARY_PATH指定cudnn版本？

### ISSUE THREAD

**Issue by Eleanor456** [PaddlePaddle/Paddle#34987]
虽然在issues中存在很多关于CUDA CUDNN的问题，但都没有解决方案，想再试一次

系统：centos 7
cuda 版本：系统中有cuda 8.0，cuda 9.0 和cuda 10.2
同样存在多个不同版本的cudnn，其中/usr/local/cuda默认的为cudnn 5.1.0

问题：当使用LD_LIBRARY_PATH指定cuda和cudnn版本时，cudnn不起作用，仍然使用的默认cudnn，请问当没有sudo权限时，这个问题怎么解决？

**Comment by pangyoki** [comment]
你好，这个问题在develop版本修复了，可以使用LD_LIBRARY_PATH指定cuda版本，修复PR会进2.2-rc版本。
目前建议你使用docker，或者编译develop版本的包。
