### ISSUE TITLE
jetson agx xavier预测报错

### ISSUE THREAD

**Issue by isLiuHao** [PaddlePaddle/Paddle#34983]
- 版本、环境信息：
    1）PaddlePaddle版本：PaddlePaddle2.0.0beta
    2）GPU：CUDA 10.2和CUDNN 8.0
    3）系统环境：jetpack4.5，Python版本3.6.9
    4)   paddleocr：develop分支
在docker容器中运行时，有时能预测，有时会报以下错误Error Message Summary
![129653847-139fc479-bb06-41c9-9538-a1c9b9894a1e](https://user-images.githubusercontent.com/74350741/129828642-2b83dc5a-0b4a-4108-bf18-b0f3a72def09.png)

**Comment by fengxiaoshuai** [comment]
换用最新的v2.1.2去试试吧，如果还是同样的的问题，请提供复现的单测代码和模型

**Comment by isLiuHao** [comment]
> 换用最新的v2.1.2去试试吧，如果还是同样的的问题，请提供复现的单测代码和模型
v2.1.2不知道怎么编译，paddlepaddle暂时换了v2.1.1还是这样，paddleocr也换了最新的
![1629276749(1)](https://user-images.githubusercontent.com/74350741/129868973-b05dd380-648c-4dab-b39b-927a46bd185a.png)

**Comment by fengxiaoshuai** [comment]
怀疑是环境问题，OCR在nano和agx裸机上都是测试正常的，所以应该不是框架的问题，你可以在裸机上运行测试或者刷机后试试，查问题的话建议看看docker，显存这方面是否有问题。

**Comment by isLiuHao** [comment]
> 怀疑是环境问题，OCR在nano和agx裸机上都是测试正常的，所以应该不是框架的问题，你可以在裸机上运行测试或者刷机后试试，查问题的话建议看看docker，显存这方面是否有问题。

谢谢，之前裸机上也是没有问题，我考虑一下docker这方面
