### ISSUE TITLE
paddlepaddle安装旧版本：1.7.1版本，无法安装成功，-i https://mirror.baidu.com/pypi/simple源中并没有此版本的安装。请问该如何安装呢？

### ISSUE THREAD

**Issue by The-Sun-Kernel** [PaddlePaddle/Paddle#34982]
- 版本、环境信息：
    1）PaddlePaddle版本：1.7.1.post97，无法安装
    2）CPU：Intel(R) Core(TM) i5-10400F CPU @ 2.90GHz   2.90 GHz
    3）GPU：NVIDIA GeForce RTX 2080Ti，CUDA==11.2，CUDNN==8.2.1
    4）系统环境：win10、Python==3.8.5

- 安装方式信息：
1）pip安装/docker安装

请问paddlepaddle==1.7.1.post97环境如何安装？

**Comment by wangye707** [comment]
paddle1.7版本中python3系类只有python3.5、3.6和3.7

**Comment by pangyoki** [comment]
你好，我看了下，paddle 1.7.1没有支持python3.8，最高版本是python3.7。下面是python 3.7的安装包：
先把这个安装包下载到本地：`wget https://paddle-wheel.bj.bcebos.com/1.7.1/win-mkl/paddlepaddle_gpu-1.7.1.post97-cp37-cp37m-win_amd64.whl`，然后pip install 。

**Comment by The-Sun-Kernel** [comment]
> 你好，我看了下，paddle 1.7.1没有支持python3.8，最高版本是python3.7。下面是python 3.7的安装包：
> 先把这个安装包下载到本地：`wget https://paddle-wheel.bj.bcebos.com/1.7.1/win-mkl/paddlepaddle_gpu-1.7.1.post97-cp37-cp37m-win_amd64.whl`，然后pip install 。

好哒，谢谢您！

**Comment by Bobwang-tech** [comment]
版本、环境信息：
   1）PaddlePaddle版本：1.7.1.post97，无法安装
   2）CPU：Intel(R) Core(TM) i7-8700 CPU @ 2.90GHz 2.90 GHz
   3）GPU：NVIDIA GeForce RTX 2080，CUDA==10.0，CUDNN==7.6.5
   4）系统环境：ubuntu、Python==3.6

安装方式信息：
1）pip安装/docker安装
请问paddlepaddle==1.7.1.post97环境如何安装？
