### ISSUE TITLE
v2 optimizer API arguments lack document

### ISSUE THREAD

**Issue by dzhwinter** [PaddlePaddle/Paddle#3499]
in our current stage of document. V2 optimizer API only port some part of  V1 document. The common parameter settings in V1 is missing. 
[optimizer V2](http://doc.paddlepaddle.org/doc/api/v2/config/optimizer.html)
[optimizer V1](http://doc.paddlepaddle.org/release_doc/0.9.0/doc/ui/api/trainer_config_helpers/optimizers.html#settings)
e.g. `learning_rate`, `L2Regularization` in V1 settting config is missing in V2.

**Comment by luotao1** [comment]
As there is no `optimizers.settings` in optimizer V2, it is confused where to put the related annotations.

**Comment by dzhwinter** [comment]
another problem, the `Momentum Optimizer` document refer to the SGD Optimizer [momentum](http://doc.paddlepaddle.org/release/0.10.0/doc/api/v2/config/optimizer.html#momentum). 
It seems that there is a lot of improvement work to do with our document online.

**Comment by dzhwinter** [comment]
This issue is a proposal, which has been implemented in the latest develop branch. Please check it, please feel free to open it.
