### ISSUE TITLE
【论文复现】关于torch.multiprocessing.cpu_count()

### ISSUE THREAD

**Issue by ZiMo-Chen** [PaddlePaddle/Paddle#35003]
关于torch.multiprocessing.cpu_count()这个 paddle里面有对应的吗
以及from torch.utils.data.dataset import ConcatDataset这个 paddle里面有对应的吗

**Comment by wanghuancoder** [comment]
抱歉，这两个API都没有。

**Comment by ZiMo-Chen** [comment]
> 抱歉，这两个API都没有。
有没有什么办法
![1629365530(1)](https://user-images.githubusercontent.com/35260648/130045407-a3f9cf97-cd24-40a4-8a35-44ea6e536d9b.png)

**Comment by wanghuancoder** [comment]
ConcatDataset我们后续将开发，伴随新的版本发布。
您先看看ChainDataset和ComposeDataset是否能够满足您的需求。

**Comment by ZiMo-Chen** [comment]
> ConcatDataset我们后续将开发，伴随新的版本发布。
> 您先看看ChainDataset和ComposeDataset是否能够满足您的需求。

torch.BoolTensor() 这个 paddle里面要怎么实现 torch.multiprocessing.cpu_count()这个有没其他可以参考

**Comment by wanghuancoder** [comment]
> > ConcatDataset我们后续将开发，伴随新的版本发布。
> > 您先看看ChainDataset和ComposeDataset是否能够满足您的需求。
> 
> torch.BoolTensor() 这个 paddle里面要怎么实现 torch.multiprocessing.cpu_count()这个有没其他可以参考

这两个paddle都没有对应的实现
