### ISSUE TITLE
Makefile:139: *** OpenBLAS: Detecting CPU failed. Please set TARGET explicitly, e.g. make TARGET=your_cpu_target. Please read README for the detail..  Stop.

### ISSUE THREAD

**Issue by XYZ-916** [PaddlePaddle/Paddle#35023]
HEAD is now at 5f36f181 Update with 0.3.7 changes
[  1%] No update step for 'extern_openblas'
[  2%] No patch step for 'extern_openblas'
[  2%] No configure step for 'extern_openblas'
[  2%] Performing build step for 'extern_openblas'
Makefile:139: *** OpenBLAS: Detecting CPU failed. Please set TARGET explicitly, e.g. make TARGET=your_cpu_target. Please read README for the detail..  Stop.
make[2]: *** [third_party/openblas/src/extern_openblas-stamp/extern_openblas-build] Error 2
make[1]: *** [CMakeFiles/extern_openblas.dir/all] Error 2
make: *** [all] Error 2

OS: macOs 10.16
Python version: 3.8.8
openblas: stable 0.3.17 (bottled), HEAD [keg-only]

**Comment by wanghuancoder** [comment]
你好，你的问题是什么？编译失败吗？
你的Paddle源码版本是什么，比如commitid。
你的编译cmake配置是什么，都打开了哪些开关？

**Comment by XYZ-916** [comment]
make install failed

the version of paddle is develop

The content of cmake config is not changed.

**Comment by wanghuancoder** [comment]
您是想编译develop版本的paddle吗？为啥会make install呢？
以下是如何从源码编译并安装Paddle的文档：
https://www.paddlepaddle.org.cn/documentation/docs/zh/1.5/beginners_guide/install/compile/compile_Ubuntu.html

**Comment by XYZ-916** [comment]
请问paddle支持python3.8版本吗？

**Comment by wanghuancoder** [comment]
支持~

**Comment by wanghuancoder** [comment]
> 请问paddle支持python3.8版本吗？

支持
