### ISSUE TITLE
【安装错误】验证安装时执行 `paddle.utils.run_check()` 报错

### ISSUE THREAD

**Issue by yishibakaien** [PaddlePaddle/Paddle#35028]
按照 [官方文档](https://www.paddlepaddle.org.cn/install/quick?docurl=/documentation/docs/zh/install/pip/windows-pip.html) 安装完毕，验证安装时 `paddle.utils.run_check()` 报错 

- 版本、环境信息：
    - GPU：GTX1660 SUPER
    - platform：windows10
    - Paddle version: 2.1.2
    - Paddle With CUDA: True
    - OS: Windows 10
    - Python version: 3.9.6
    - CUDA version: 10.2.89
    - cuDNN version: 7.6.5
    - Nvidia driver version: 441.22
- 安装方式信息：pip安装
- 问题描述：
执行 `paddle.utils.run_check()` 时发生报错，目前无法解决此问题
```shell
Python 3.9.6 (tags/v3.9.6:db3ff76, Jun 28 2021, 15:26:21) [MSC v.1929 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import paddle
>>> paddle.utils.run_check()
Running verify PaddlePaddle program ...
W0819 17:41:20.890090  5104 device_context.cc:404] Please NOTE: device: 0, GPU Compute Capability: 7.5, Driver API Version: 10.2, Runtime API Version: 10.2
W0819 17:41:20.897076  5104 device_context.cc:422] device: 0, cuDNN Version: 7.6.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\a\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\paddle\utils\install_check.py", line 196, in run_check
    _run_static_single(use_cuda)
  File "C:\Users\a\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\paddle\utils\install_check.py", line 124, in _run_static_single
    exe.run(startup_prog)
  File "C:\Users\a\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\paddle\fluid\executor.py", line 1110, in run
    six.reraise(*sys.exc_info())
  File "C:\Users\a\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\six.py", line 719, in reraise
    raise value
  File "C:\Users\a\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\paddle\fluid\executor.py", line 1098, in run
    return self._run_impl(
  File "C:\Users\a\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\paddle\fluid\executor.py", line 1231, in _run_impl
    return self._run_program(
  File "C:\Users\a\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\paddle\fluid\executor.py", line 1328, in _run_program
    self._default_executor.run(program.desc, scope, 0, True, True,
RuntimeError: (PreconditionNotMet) The third-party dynamic library (cublas64_102.dll;cublas64_10.dll) that Paddle depends on is not configured correctly. (error code is 126)
  Suggestions:
  1. Check if the third-party dynamic library (e.g. CUDA, CUDNN) is installed correctly and its version is matched with paddlepaddle you installed.
  2. Configure third-party dynamic library environment variables as follows:
  - Linux: set LD_LIBRARY_PATH by `export LD_LIBRARY_PATH=...`
  - Windows: set PATH by `set PATH=XXX; (at C:\home\workspace\Paddle_release4\paddle\fluid\platform\dynload\dynamic_loader.cc:265)

>>>
```

1. `cuda` 和 `cudnn` 应该都没有问题，版本是对的上的，执行 `C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.2\extras\demo_suite` 下的测试工具 `deviceQuery.exe`  和 `bandwidthTest.exe` 结果都是 `Result = PASS`
2. 环境变量配置
![image](https://user-images.githubusercontent.com/17696228/130048309-ca48f7fa-fcfa-4d26-ac2c-7637cfc3c0cb.png)
![image](https://user-images.githubusercontent.com/17696228/130048978-7624565a-9e3a-48c2-8f5c-3778c8cdabde.png)

3. cuda 10.2 官网上的两个补丁也打了  `https://developer.nvidia.com/cuda-10.2-download-archive?target_os=Windows&target_arch=x86_64&target_version=10&target_type=exelocal`
![image](https://user-images.githubusercontent.com/17696228/130048577-1567a36e-30c8-4d7d-9a73-017480740cab.png)

4. 安装的 cuda 文件夹 以及 解压的 cudnn 文件夹
![image](https://user-images.githubusercontent.com/17696228/130049207-0a6c5d2a-4c36-4ad4-80e7-060c49648b88.png)
![image](https://user-images.githubusercontent.com/17696228/130049271-337ed08e-42a4-4131-aede-f095e0525660.png)
![image](https://user-images.githubusercontent.com/17696228/130049346-da0b9c37-d1f3-4059-9288-1d49f148b703.png)

![image](https://user-images.githubusercontent.com/17696228/130049480-33c87c95-0749-4db4-82f9-f81835d7a11d.png)

各种方法都试了，也重装了好多次 paddle 和 cuda cudnn 实在没有办法了，一直报这个错

**Comment by zhwesky2010** [comment]
@yishibakaien 您好，运行时动态库加载失败，环境变量是否生效了呢

**Comment by yishibakaien** [comment]
> @yishibakaien 您好，运行时动态库加载失败，环境变量是否生效了呢

我如何判断 环境变量是否生效了

**Comment by yishibakaien** [comment]
@zhouwei25   你好，看得见我的回复吗？我要如何判断环境变量是否配置正确（生效），有没有什么办法可以检查，issue 中的 `deviceQuery.exe` 和 `bandwidthTest.exe`  两项 测试可否作为环境变量正确的判断依据

**Comment by zhwesky2010** [comment]
@yishibakaien 你用 `set PATH` 看一下有哪些目录，然后看下cublas64_102.dll;cublas64_10.dll是否在里面

**Comment by MAGICSCIENTIST** [comment]
有解决了的么？同样的情况，同样的问题已经卡了很久了

**Comment by betterpig** [comment]
您好，根据已给出的信息，可以确定cublas64_10.dll 与 cublasLt64_10.dll 文件是存在于C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.2\bin（CUDA10.2）中的。按照报错截图，Python是Python software foundation版本的，我推测是该渠道安装的Python无法查找到上述dll文件。请进行以下操作：
1. 从[官网](https://www.python.org/downloads/)安装Python，再通过pip安装paddle，运行 paddle.utils.run_check()验证。
2. 如果仍出现该问题，将cublas64_10.dll 与 cublasLt64_10.dll 文件复制到 C:\Windows\System32 中，再运行 paddle.utils.run_check()

**Comment by wonderfuer** [comment]
+1

**Comment by wonderfuer** [comment]
按照 betterpig的方法已解决：
我只把cublasLt64_10.dll复制到C:\Windows\System32 就可以了。

`Running verify PaddlePaddle program ... 
W1224 17:55:22.302059 15552 device_context.cc:447] Please NOTE: device: 0, GPU Compute Capability: 6.1, Driver API Version: 11.4, Runtime API Version: 10.2
W1224 17:55:22.331984 15552 device_context.cc:465] device: 0, cuDNN Version: 7.6.
PaddlePaddle works well on 1 GPU.
PaddlePaddle works well on 1 GPUs.
PaddlePaddle is installed successfully! Let's start deep learning with PaddlePaddle now.`

**Comment by YinGuiWang** [comment]
类似的问题，我的也解决了

> 按照 betterpig的方法已解决： 我只把cublasLt64_10.dll复制到C:\Windows\System32 就可以了。
> 
> `Running verify PaddlePaddle program ... W1224 17:55:22.302059 15552 device_context.cc:447] Please NOTE: device: 0, GPU Compute Capability: 6.1, Driver API Version: 11.4, Runtime API Version: 10.2 W1224 17:55:22.331984 15552 device_context.cc:465] device: 0, cuDNN Version: 7.6. PaddlePaddle works well on 1 GPU. PaddlePaddle works well on 1 GPUs. PaddlePaddle is installed successfully! Let's start deep learning with PaddlePaddle now.`

**Comment by YinGuiWang** [comment]
谢谢，我类似的问题也解决了，
   将cublas64_10.dll 与 cublasLt64_10.dll 文件复制到 C:\Windows\System32 中，再运行 paddle.utils.run_check()


> 您好，根据已给出的信息，可以确定cublas64_10.dll 与 cublasLt64_10.dll 文件是存在于C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.2\bin（CUDA10.2）中的。按照报错截图，Python是Python software foundation版本的，我推测是该渠道安装的Python无法查找到上述dll文件。请进行以下操作：
> 
> 1. 从[官网](https://www.python.org/downloads/)安装Python，再通过pip安装paddle，运行 paddle.utils.run_check()验证。
> 2. 如果仍出现该问题，将cublas64_10.dll 与 cublasLt64_10.dll 文件复制到 C:\Windows\System32 中，再运行 paddle.utils.run_check()
