### ISSUE TITLE
模型导出出错

### ISSUE THREAD

**Issue by ziyaxuanyi** [PaddlePaddle/Paddle#35037]
使用paddle.jit.save()导出动态模型出错：
Only one dimension value of 'shape' in reshape can be -1.But received shape[2] is alse -1.

检查发现是如下代码问题：
B,C,H,W = inputs.shape
enc_out = inputs.reshape([B,C,-1]).transpose([0,2,1])

导出时设置的输入形状为infer_shape=[3,32,-1]

应该是inputs.reshape([B,C,-1])中第一项B是batch size为-1，而第三项也是-1，需要自行推断维度。

请问这种情况应该怎么处理？

**Comment by TeslaZhao** [comment]
首先reshape传入多个-1时，有多种case满足情况，无法准确推断，因此，目标上说要把2个-1变成1个-1，在模型的处理逻辑上保证一个是确定的。因此，在拿到B,C,H,W = inputs.shape 检查B，如果B为-1，考虑能否做固定Batch『如果B为-1做if else判断』。对于变长数据，一般会用LodTensor，是否可以有Lod信息来对数据做变长做补充?

**Comment by ziyaxuanyi** [comment]
"如果B为-1做if else判断"

这是什么意思，做if else判断，不太明白

**Comment by TeslaZhao** [comment]
您好，还是要根据您使用场景出发，在reshape操作的时候把多个-1减少到不多于1个-1.
