### ISSUE TITLE
from .core_avx import * ImportError: DLL load failed with error code 3221225501

### ISSUE THREAD

**Issue by crrongyan** [PaddlePaddle/Paddle#35033]
PaddlePaddle版本：paddlepaddle 2.1.2
    CPU：Intel(R) UHD Graphics 630
    系统环境：Windows 7 专业版
    Python版本：3.7.4

    您好，我想要在 windows 7 操作系统中安装paddle，通过 anaconda 安装 python 环境，pip 安装 paddlepaddle。
    安装过程十分顺利，但是安装完成之后，导入 paddle 时发生了错误，具体报错信息如下：

    I want to install paddlePaddle in Windows 7, python environment via Anaconda, and PIP to install PaddlePaddle.  
    The installation process was quite smooth, but after the installation was completed, an error occurred when the paddle was imported. The specific error information is as follows:

Error: Can not import avx core while this file exists: C:\ProgramData\Anaconda3\envs\ocr\lib\site-packages\paddle\fluid\core_avx.pyd
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\ProgramData\Anaconda3\envs\ocr\lib\site-packages\paddle\__init__.py", line 25, in <module>
    from .fluid import monkey_patch_variable
  File "C:\ProgramData\Anaconda3\envs\ocr\lib\site-packages\paddle\fluid\__init__.py", line 36, in <module>
    from . import framework
  File "C:\ProgramData\Anaconda3\envs\ocr\lib\site-packages\paddle\fluid\framework.py", line 37, in <module>
    from . import core
  File "C:\ProgramData\Anaconda3\envs\ocr\lib\site-packages\paddle\fluid\core.py", line 297, in <module>
    raise e
  File "C:\ProgramData\Anaconda3\envs\ocr\lib\site-packages\paddle\fluid\core.py", line 257, in <module>
    from .core_avx import *
ImportError: DLL load failed with error code 3221225501

**Comment by TeslaZhao** [comment]
您好，您的windows环境下有安装Microsoft Visual C++吗？

参考之前一个PR，和您报错的信息比较接近，可以参考：https://github.com/PaddlePaddle/Paddle/issues/28205

**Comment by crrongyan** [comment]
我已经解决了这个问题，但是我仍然不知道根本的原因。
我安装了 windows6.1-KB976932-X64(SP1补丁) 把 Windows 7 专业版 更新为 Service Pack 1 版，报错就消失了。

**Comment by crrongyan** [comment]
> 您好，您的windows环境下有安装Microsoft Visual C++吗？
> 
> 先参考一个，和你报错的信息比较接近，可以参考：#28205

**Comment by crrongyan** [comment]
> 您好，您的windows环境下有安装Microsoft Visual C++吗？
> 
> 先参考一个，你报错的信息比较，可以参考：#28205

我已经解决了问题，但还不知道根本原因。 
安装了Windows 6.1-KB976932-X64(SP1补丁)，并将Windows 7 Professional升级为Service Pack 1。错误消失了。

**Comment by zhwesky2010** [comment]
> > 您好，您的windows环境下有安装Microsoft Visual C++吗？
> > 先参考一个，你报错的信息比较，可以参考：#28205
> 
> 我已经解决了问题，但还不知道根本原因。
> 安装了Windows 6.1-KB976932-X64(SP1补丁)，并将Windows 7 Professional升级为Service Pack 1。错误消失了。

windows版本可能会少一些Visual C++的一些库，比如某些精简版、纯净版、绿色版系统，会少一些运行时的动态库，在加载时dll时就会出错。更新系统补丁或者安装新的windows系统时，可能将缺失的动态库安上了。
