### ISSUE TITLE
paddle升级到最新2.1.2后导入失败

### ISSUE THREAD

**Issue by LangDaoAI** [PaddlePaddle/Paddle#35048]
paddle升级到最新2.1.2后导入失败， 2.1.1没有这个问题

版本：python 3.7

![image](https://user-images.githubusercontent.com/83859417/130218351-c8db21f4-9828-4db7-a180-542636d31a08.png)

请帮忙看一下

**Comment by TeslaZhao** [comment]
您好，报错信息能发一下吗？

**Comment by LangDaoAI** [comment]
2.1.1也再现了

![image](https://user-images.githubusercontent.com/83859417/130219990-3c427ba5-57d5-4b7e-8be0-b4dff82517c0.png)

**Comment by LangDaoAI** [comment]
是不是six版本太低了

**Comment by LangDaoAI** [comment]
![image](https://user-images.githubusercontent.com/83859417/130220332-8af76de3-627d-4408-aca2-31fbf84594b4.png)

更新了six后OK了

**Comment by LangDaoAI** [comment]
关闭这个issue
