### ISSUE TITLE
报名

### ISSUE THREAD

**Issue by WY130090** [PaddlePaddle/Paddle#35046]
【队名】：菜菜

【序号】：6

【论文】：Scaled-YOLOv4: Scaling Cross Stage Partial Network

【状态】：报名

【repo链接】：https://github.com/WY130090/Scaled-YOLOv4

**Comment by TCChenlong** [comment]
报名是在这个ISSUE回复哈：https://github.com/PaddlePaddle/Paddle/issues/34526
