### ISSUE TITLE
【论文复现】AIStduio脚本多卡训练总是报"ABORT!!!" 错误

### ISSUE THREAD

**Issue by CuberrChen** [PaddlePaddle/Paddle#35047]
- 标题：AIStduio中使用脚本多卡训练总是报"ABORT!!!" 错误。
- 版本、环境信息：
    1）PaddlePaddle版本：2.1.2
    3）GPU：AIStudio V100*4
    4）系统环境：ubuntu
- 训练信息
    1）单卡/多卡
    2）显存信息 ：32G*4
    3）操作：
- 复现信息：
执行paddlleseg下的train.py进行多卡训练报错。
run.sh文件：
```
export CUDA_VISIBLE_DEVICES=0,1,2,3 
python -m paddle.distributed.launch train.py --config configs/xxx/yyy.yml --num_workers 16 --use_vdl --do_eval --save_interval 1000 --save_dir output
```
- 问题描述：

INFO 2021-08-20 16:31:43,169 launch_utils.py:510] Local start 4 processes. First process distributed environment info (Only For Debug): 
    +=======================================================================================+
    |                        Distributed Envs                      Value                    |
    +---------------------------------------------------------------------------------------+
    |                       PADDLE_TRAINER_ID                        0                      |
    |                 PADDLE_CURRENT_ENDPOINT                 127.0.0.1:55825               |
    |                     PADDLE_TRAINERS_NUM                        4                      |
    |                PADDLE_TRAINER_ENDPOINTS  ... 0.1:53635,127.0.0.1:56773,127.0.0.1:43063|
    |                     PADDLE_RANK_IN_NODE                        0                      |
    |                 PADDLE_LOCAL_DEVICE_IDS                        0                      |
    |                 PADDLE_WORLD_DEVICE_IDS                     0,1,2,3                   |
    |                     FLAGS_selected_gpus                        0                      |
    |             FLAGS_selected_accelerators                        0                      |
    +=======================================================================================+

INFO 2021-08-20 16:31:43,169 launch_utils.py:514] details abouts PADDLE_TRAINER_ENDPOINTS can be found in log/endpoints.log, and detail running logs maybe found in log/workerlog.0
INFO 2021-08-20 16:31:55,247 launch_utils.py:327] terminate all the procs
ERROR 2021-08-20 16:31:55,248 launch_utils.py:584] ABORT!!! Out of all 4 trainers, the trainer process with rank=[2] was aborted. Please check its log.
INFO 2021-08-20 16:31:58,251 launch_utils.py:327] terminate all the procs
-----------  Configuration Arguments -----------
gpus: None
heter_worker_num: None
heter_workers: 
http_port: None
ips: 127.0.0.1
log_dir: log
nproc_per_node: None
run_mode: None
server_num: None
servers: 
training_script: train.py
training_script_args: ['--config', 'configs/xxx/yyy.yml', '--num_workers', '16', '--use_vdl', '--do_eval', '--save_interval', '1000', '--save_dir', 'output']
worker_num: None
workers: 
------------------------------------------------
launch train in GPU mode!
launch proc_id:1365 idx:0
launch proc_id:1368 idx:1
launch proc_id:1371 idx:2
launch proc_id:1374 idx:3
/mnt
[INFO]: train job failed! train_ret: 1

**Comment by nihao2012** [comment]
@CuberrChen Hi, please provide the error log in log/workerlog.0

**Comment by michaelowenliu** [comment]
@CuberrChen hi, please provide the error log in log/workerlog.0

**Comment by CuberrChen** [comment]
@michaelowenliu 输出output没有文件，只有这个日志记录！ 我也不知道问题出在哪里 因为我直接使用paddleseg的多卡训练方式，未做修改？可能是脚本环境版本不支持吗？

**Comment by michaelowenliu** [comment]
@CuberrChen log/workerlog.0

**Comment by CuberrChen** [comment]
@michaelowenliu 
[INFO]: current net device: eth0, ip: 172.28.0.106
[INFO]: paddle job envs:
POD_IP=job-480851a94dc4045fa9280ff45ceff0f9-trainer-0.job-480851a94dc4045fa9280ff45ceff0f9
PADDLE_PORT=12345
PADDLE_TRAINER_ID=0
PADDLE_TRAINERS_NUM=1
PADDLE_USE_CUDA=1
NCCL_SOCKET_IFNAME=eth0
PADDLE_IS_LOCAL=1
OUTPUT_PATH=/root/paddlejob/workspace/output
LOCAL_LOG_PATH=/root/paddlejob/workspace/log
LOCAL_MOUNT_PATH=/mnt/code_20210820191333,/mnt/datasets_20210820191333
JOB_ID=job-480851a94dc4045fa9280ff45ceff0f9
TRAINING_ROLE=TRAINER
[INFO]: user command: bash run.sh
[INFO]: start trainer
~/paddlejob/workspace/code /mnt
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple, https://pypi.tuna.tsinghua.edu.cn/simple
Requirement already satisfied: paddlepaddle-gpu in /opt/_internal/cpython-3.7.0/lib/python3.7/site-packages (2.1.2.post101)
Requirement already satisfied: Pillow in /opt/_internal/cpython-3.7.0/lib/python3.7/site-packages (from paddlepaddle-gpu) (5.2.0)
Requirement already satisfied: requests>=2.20.0 in /opt/_internal/cpython-3.7.0/lib/python3.7/site-packages (from paddlepaddle-gpu) (2.22.0)
Requirement already satisfied: gast<=0.4.0,>=0.3.3 in /opt/_internal/cpython-3.7.0/lib/python3.7/site-packages (from paddlepaddle-gpu) (0.3.3)
Requirement already satisfied: six in /opt/_internal/cpython-3.7.0/lib/python3.7/site-packages (from paddlepaddle-gpu) (1.16.0)
Requirement already satisfied: protobuf>=3.1.0 in /opt/_internal/cpython-3.7.0/lib/python3.7/site-packages (from paddlepaddle-gpu) (3.10.0)
Requirement already satisfied: decorator in /opt/_internal/cpython-3.7.0/lib/python3.7/site-packages (from paddlepaddle-gpu) (4.3.0)
Requirement already satisfied: astor in /opt/_internal/cpython-3.7.0/lib/python3.7/site-packages (from paddlepaddle-gpu) (0.8.1)
Requirement already satisfied: numpy>=1.13 in /opt/_internal/cpython-3.7.0/lib/python3.7/site-packages (from paddlepaddle-gpu) (1.19.5)
Requirement already satisfied: setuptools in /opt/_internal/cpython-3.7.0/lib/python3.7/site-packages (from protobuf>=3.1.0->paddlepaddle-gpu) (49.2.0)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /opt/_internal/cpython-3.7.0/lib/python3.7/site-packages (from requests>=2.20.0->paddlepaddle-gpu) (1.25.6)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /opt/_internal/cpython-3.7.0/lib/python3.7/site-packages (from requests>=2.20.0->paddlepaddle-gpu) (3.0.4)
Requirement already satisfied: certifi>=2017.4.17 in /opt/_internal/cpython-3.7.0/lib/python3.7/site-packages (from requests>=2.20.0->paddlepaddle-gpu) (2019.9.11)
Requirement already satisfied: idna<2.9,>=2.5 in /opt/_internal/cpython-3.7.0/lib/python3.7/site-packages (from requests>=2.20.0->paddlepaddle-gpu) (2.8)
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
WARNING: You are using pip version 21.2.3; however, version 21.2.4 is available.
You should consider upgrading via the '/opt/_internal/cpython-3.7.0/bin/python -m pip install --upgrade pip' command.
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple, https://pypi.tuna.tsinghua.edu.cn/simple
Requirement already satisfied: pre-commit in /opt/_internal/cpython-3.7.0/lib/python3.7/site-packages (from -r requirements.txt (line 1)) (1.21.0)
Collecting cityscapesScripts
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/0d/3f/46aba88cf145984e8cf03017059abc327fa52b48060abcfc099132548aac/cityscapesScripts-2.2.0-py3-none-any.whl (472 kB)
Requirement already satisfied: yapf==0.26.0 in /opt/_internal/cpython-3.7.0/lib/python3.7/site-packages (from -r requirements.txt (line 3)) (0.26.0)
Requirement already satisfied: flake8 in /opt/_internal/cpython-3.7.0/lib/python3.7/site-packages (from -r requirements.txt (line 4)) (3.7.9)
Requirement already satisfied: pyyaml>=5.1 in /opt/_internal/cpython-3.7.0/lib/python3.7/site-packages (from -r requirements.txt (line 5)) (5.1)
Collecting visualdl>=2.0.0
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/31/99/f5f50d035006b0d9304700facd9e1c843af8e02569474996d1b6a79529f6/visualdl-2.2.0-py3-none-any.whl (2.7 MB)
Requirement already satisfied: opencv-python in /opt/_internal/cpython-3.7.0/lib/python3.7/site-packages (from -r requirements.txt (line 7)) (4.1.1.26)
Requirement already satisfied: tqdm in /opt/_internal/cpython-3.7.0/lib/python3.7/site-packages (from -r requirements.txt (line 8)) (4.36.1)
Collecting filelock
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/93/83/71a2ee6158bb9f39a90c0dea1637f81d5eef866e188e1971a1b1ab01a35a/filelock-3.0.12-py3-none-any.whl (7.6 kB)
Requirement already satisfied: scipy in /opt/_internal/cpython-3.7.0/lib/python3.7/site-packages (from -r requirements.txt (line 10)) (1.1.0)
Requirement already satisfied: prettytable in /opt/_internal/cpython-3.7.0/lib/python3.7/site-packages (from -r requirements.txt (line 11)) (0.7.2)
Requirement already satisfied: aspy.yaml in /opt/_internal/cpython-3.7.0/lib/python3.7/site-packages (from pre-commit->-r requirements.txt (line 1)) (1.3.0)
Requirement already satisfied: virtualenv>=15.2 in /opt/_internal/cpython-3.7.0/lib/python3.7/site-packages (from pre-commit->-r requirements.txt (line 1)) (16.7.9)
Requirement already satisfied: six in /opt/_internal/cpython-3.7.0/lib/python3.7/site-packages (from pre-commit->-r requirements.txt (line 1)) (1.16.0)
Requirement already satisfied: importlib-metadata in /opt/_internal/cpython-3.7.0/lib/python3.7/site-packages (from pre-commit->-r requirements.txt (line 1)) (0.23)
Requirement already satisfied: nodeenv>=0.11.1 in /opt/_internal/cpython-3.7.0/lib/python3.7/site-packages (from pre-commit->-r requirements.txt (line 1)) (1.3.4)
Requirement already satisfied: identify>=1.0.0 in /opt/_internal/cpython-3.7.0/lib/python3.7/site-packages (from pre-commit->-r requirements.txt (line 1)) (1.4.10)
Requirement already satisfied: toml in /opt/_internal/cpython-3.7.0/lib/python3.7/site-packages (from pre-commit->-r requirements.txt (line 1)) (0.10.0)
Requirement already satisfied: cfgv>=2.0.0 in /opt/_internal/cpython-3.7.0/lib/python3.7/site-packages (from pre-commit->-r requirements.txt (line 1)) (2.0.1)
Collecting typing
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/05/d9/6eebe19d46bd05360c9a9aae822e67a80f9242aabbfc58b641b957546607/typing-3.7.4.3.tar.gz (78 kB)
Requirement already satisfied: matplotlib in /opt/_internal/cpython-3.7.0/lib/python3.7/site-packages (from cityscapesScripts->-r requirements.txt (line 2)) (2.2.2)
Collecting pyquaternion
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/49/b3/d8482e8cacc8ea15a356efea13d22ce1c5914a9ee36622ba250523240bf2/pyquaternion-0.9.9-py3-none-any.whl (14 kB)
Requirement already satisfied: pillow in /opt/_internal/cpython-3.7.0/lib/python3.7/site-packages (from cityscapesScripts->-r requirements.txt (line 2)) (5.2.0)
Requirement already satisfied: numpy in /opt/_internal/cpython-3.7.0/lib/python3.7/site-packages (from cityscapesScripts->-r requirements.txt (line 2)) (1.19.5)
Collecting coloredlogs
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/a7/06/3d6badcf13db419e25b07041d9c7b4a2c331d3f4e7134445ec5df57714cd/coloredlogs-15.0.1-py2.py3-none-any.whl (46 kB)
Collecting appdirs
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/3b/00/2344469e2084fb287c2e0b57b72910309874c3245463acd6cf5e3db69324/appdirs-1.4.4-py2.py3-none-any.whl (9.6 kB)
Requirement already satisfied: pyflakes<2.2.0,>=2.1.0 in /opt/_internal/cpython-3.7.0/lib/python3.7/site-packages (from flake8->-r requirements.txt (line 4)) (2.1.1)
Requirement already satisfied: pycodestyle<2.6.0,>=2.5.0 in /opt/_internal/cpython-3.7.0/lib/python3.7/site-packages (from flake8->-r requirements.txt (line 4)) (2.5.0)
Requirement already satisfied: mccabe<0.7.0,>=0.6.0 in /opt/_internal/cpython-3.7.0/lib/python3.7/site-packages (from flake8->-r requirements.txt (line 4)) (0.6.1)
Requirement already satisfied: entrypoints<0.4.0,>=0.3.0 in /opt/_internal/cpython-3.7.0/lib/python3.7/site-packages (from flake8->-r requirements.txt (line 4)) (0.3)
Requirement already satisfied: requests in /opt/_internal/cpython-3.7.0/lib/python3.7/site-packages (from visualdl>=2.0.0->-r requirements.txt (line 6)) (2.22.0)
Requirement already satisfied: flask>=1.1.1 in /opt/_internal/cpython-3.7.0/lib/python3.7/site-packages (from visualdl>=2.0.0->-r requirements.txt (line 6)) (1.1.1)
Collecting pillow
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/8e/7a/b047f6f80fdb02c0cca1d3761d71e9800bcf6d4874b71c9e6548ec59e156/Pillow-8.3.1-cp37-cp37m-manylinux_2_5_x86_64.manylinux1_x86_64.whl (3.0 MB)
Requirement already satisfied: Flask-Babel>=1.0.0 in /opt/_internal/cpython-3.7.0/lib/python3.7/site-packages (from visualdl>=2.0.0->-r requirements.txt (line 6)) (1.0.0)
Collecting protobuf>=3.11.0
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/4c/53/ddcef00219f2a3c863b24288e24a20c3070bd086a1e77706f22994a7f6db/protobuf-3.17.3-cp37-cp37m-manylinux_2_5_x86_64.manylinux1_x86_64.whl (1.0 MB)
Requirement already satisfied: pandas in /opt/_internal/cpython-3.7.0/lib/python3.7/site-packages (from visualdl>=2.0.0->-r requirements.txt (line 6)) (1.1.5)
Collecting bce-python-sdk
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/3f/3e/d7a44d8f43aba0de52d56600fce8ab9ce107fe074dffc36515402bf8983c/bce_python_sdk-0.8.62-py3-none-any.whl (197 kB)
Collecting shellcheck-py
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/77/c9/6f84db444de69e1bdbfd168ae6f3d5af72107c16cd9db3c0a1f8e41204d1/shellcheck_py-0.7.2.1-py2.py3-none-manylinux1_x86_64.whl (2.0 MB)
Requirement already satisfied: Werkzeug>=0.15 in /opt/_internal/cpython-3.7.0/lib/python3.7/site-packages (from flask>=1.1.1->visualdl>=2.0.0->-r requirements.txt (line 6)) (0.16.0)
Requirement already satisfied: click>=5.1 in /opt/_internal/cpython-3.7.0/lib/python3.7/site-packages (from flask>=1.1.1->visualdl>=2.0.0->-r requirements.txt (line 6)) (7.0)
Requirement already satisfied: Jinja2>=2.10.1 in /opt/_internal/cpython-3.7.0/lib/python3.7/site-packages (from flask>=1.1.1->visualdl>=2.0.0->-r requirements.txt (line 6)) (2.10.3)
Requirement already satisfied: itsdangerous>=0.24 in /opt/_internal/cpython-3.7.0/lib/python3.7/site-packages (from flask>=1.1.1->visualdl>=2.0.0->-r requirements.txt (line 6)) (1.1.0)
Requirement already satisfied: pytz in /opt/_internal/cpython-3.7.0/lib/python3.7/site-packages (from Flask-Babel>=1.0.0->visualdl>=2.0.0->-r requirements.txt (line 6)) (2018.5)
Requirement already satisfied: Babel>=2.3 in /opt/_internal/cpython-3.7.0/lib/python3.7/site-packages (from Flask-Babel>=1.0.0->visualdl>=2.0.0->-r requirements.txt (line 6)) (2.8.0)
Requirement already satisfied: MarkupSafe>=0.23 in /opt/_internal/cpython-3.7.0/lib/python3.7/site-packages (from Jinja2>=2.10.1->flask>=1.1.1->visualdl>=2.0.0->-r requirements.txt (line 6)) (1.1.1)
Collecting pycryptodome>=3.8.0
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/ad/16/9627ab0493894a11c68e46000dbcc82f578c8ff06bc2980dcd016aea9bd3/pycryptodome-3.10.1-cp35-abi3-manylinux2010_x86_64.whl (1.9 MB)
Requirement already satisfied: future>=0.6.0 in /opt/_internal/cpython-3.7.0/lib/python3.7/site-packages (from bce-python-sdk->visualdl>=2.0.0->-r requirements.txt (line 6)) (0.18.0)
Collecting humanfriendly>=9.1
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/92/7e/a06472f484fa589933f39bfb41a7b849ca49f6d8e4fdfe978e27f0e3075c/humanfriendly-9.2-py2.py3-none-any.whl (86 kB)
Requirement already satisfied: zipp>=0.5 in /opt/_internal/cpython-3.7.0/lib/python3.7/site-packages (from importlib-metadata->pre-commit->-r requirements.txt (line 1)) (0.6.0)
Requirement already satisfied: more-itertools in /opt/_internal/cpython-3.7.0/lib/python3.7/site-packages (from zipp>=0.5->importlib-metadata->pre-commit->-r requirements.txt (line 1)) (7.2.0)
Requirement already satisfied: cycler>=0.10 in /opt/_internal/cpython-3.7.0/lib/python3.7/site-packages (from matplotlib->cityscapesScripts->-r requirements.txt (line 2)) (0.10.0)
Requirement already satisfied: kiwisolver>=1.0.1 in /opt/_internal/cpython-3.7.0/lib/python3.7/site-packages (from matplotlib->cityscapesScripts->-r requirements.txt (line 2)) (1.0.1)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 in /opt/_internal/cpython-3.7.0/lib/python3.7/site-packages (from matplotlib->cityscapesScripts->-r requirements.txt (line 2)) (2.2.0)
Requirement already satisfied: python-dateutil>=2.1 in /opt/_internal/cpython-3.7.0/lib/python3.7/site-packages (from matplotlib->cityscapesScripts->-r requirements.txt (line 2)) (2.7.3)
Requirement already satisfied: setuptools in /opt/_internal/cpython-3.7.0/lib/python3.7/site-packages (from kiwisolver>=1.0.1->matplotlib->cityscapesScripts->-r requirements.txt (line 2)) (49.2.0)
Requirement already satisfied: certifi>=2017.4.17 in /opt/_internal/cpython-3.7.0/lib/python3.7/site-packages (from requests->visualdl>=2.0.0->-r requirements.txt (line 6)) (2019.9.11)
Requirement already satisfied: idna<2.9,>=2.5 in /opt/_internal/cpython-3.7.0/lib/python3.7/site-packages (from requests->visualdl>=2.0.0->-r requirements.txt (line 6)) (2.8)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /opt/_internal/cpython-3.7.0/lib/python3.7/site-packages (from requests->visualdl>=2.0.0->-r requirements.txt (line 6)) (1.25.6)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /opt/_internal/cpython-3.7.0/lib/python3.7/site-packages (from requests->visualdl>=2.0.0->-r requirements.txt (line 6)) (3.0.4)
Building wheels for collected packages: typing
  Building wheel for typing (setup.py): started
  Building wheel for typing (setup.py): finished with status 'done'
  Created wheel for typing: filename=typing-3.7.4.3-py3-none-any.whl size=26311 sha256=aec1f5440b0ab50c0b6b34530da10b62a10aa2d7e670c22ac91d8534842d4acf
  Stored in directory: /root/.cache/pip/wheels/a6/bc/ae/ca8252038d59e257c5f9891b34c579c83bc54e27fd5558d78e
Successfully built typing
Installing collected packages: pycryptodome, humanfriendly, typing, shellcheck-py, pyquaternion, protobuf, pillow, coloredlogs, bce-python-sdk, appdirs, visualdl, filelock, cityscapesScripts
  Attempting uninstall: protobuf
    Found existing installation: protobuf 3.10.0
    Uninstalling protobuf-3.10.0:
      Successfully uninstalled protobuf-3.10.0
  Attempting uninstall: pillow
    Found existing installation: Pillow 5.2.0
    Uninstalling Pillow-5.2.0:
      Successfully uninstalled Pillow-5.2.0
  Attempting uninstall: visualdl
    Found existing installation: visualdl 2.0.0b4
    Uninstalling visualdl-2.0.0b4:
      Successfully uninstalled visualdl-2.0.0b4
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
parl 1.3.2 requires cloudpickle==1.2.1, but you have cloudpickle 0.5.3 which is incompatible.
parl 1.3.2 requires pyarrow==0.13.0, but you have pyarrow 5.0.0 which is incompatible.
Successfully installed appdirs-1.4.4 bce-python-sdk-0.8.62 cityscapesScripts-2.2.0 coloredlogs-15.0.1 filelock-3.0.12 humanfriendly-9.2 pillow-8.3.1 protobuf-3.17.3 pycryptodome-3.10.1 pyquaternion-0.9.9 shellcheck-py-0.7.2.1 typing-3.7.4.3 visualdl-2.2.0
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
WARNING: You are using pip version 21.2.3; however, version 21.2.4 is available.
You should consider upgrading via the '/opt/_internal/cpython-3.7.0/bin/python -m pip install --upgrade pip' command.
WARNING 2021-08-20 19:16:03,899 launch.py:359] Not found distinct arguments and compiled with cuda or xpu. Default use collective mode
INFO 2021-08-20 19:16:03,901 launch_utils.py:510] Local start 4 processes. First process distributed environment info (Only For Debug): 
    +=======================================================================================+
    |                        Distributed Envs                      Value                    |
    +---------------------------------------------------------------------------------------+
    |                       PADDLE_TRAINER_ID                        0                      |
    |                 PADDLE_CURRENT_ENDPOINT                 127.0.0.1:60752               |
    |                     PADDLE_TRAINERS_NUM                        4                      |
    |                PADDLE_TRAINER_ENDPOINTS  ... 0.1:45897,127.0.0.1:40307,127.0.0.1:56245|
    |                     PADDLE_RANK_IN_NODE                        0                      |
    |                 PADDLE_LOCAL_DEVICE_IDS                        0                      |
    |                 PADDLE_WORLD_DEVICE_IDS                     0,1,2,3                   |
    |                     FLAGS_selected_gpus                        0                      |
    |             FLAGS_selected_accelerators                        0                      |
    +=======================================================================================+

INFO 2021-08-20 19:16:03,901 launch_utils.py:514] details abouts PADDLE_TRAINER_ENDPOINTS can be found in log/endpoints.log, and detail running logs maybe found in log/workerlog.0
INFO 2021-08-20 19:16:27,985 launch_utils.py:327] terminate all the procs
ERROR 2021-08-20 19:16:27,986 launch_utils.py:584] ABORT!!! Out of all 4 trainers, the trainer process with rank=[0, 1, 2, 3] was aborted. Please check its log.
INFO 2021-08-20 19:16:30,989 launch_utils.py:327] terminate all the procs
-----------  Configuration Arguments -----------
gpus: None
heter_worker_num: None
heter_workers: 
http_port: None
ips: 127.0.0.1
log_dir: log
nproc_per_node: None
run_mode: None
server_num: None
servers: 
training_script: train.py
training_script_args: ['--config', 'configs/cpseg/cpseg_resnet101_os8_cityscapes_768×768_60k.yml', '--num_workers', '16', '--use_vdl', '--do_eval', '--save_interval', '1000', '--save_dir', 'cpseg101_cityscapes_b16']
worker_num: None
workers: 
------------------------------------------------
launch train in GPU mode!
launch proc_id:1247 idx:0
launch proc_id:1250 idx:1
launch proc_id:1253 idx:2
launch proc_id:1257 idx:3
/mnt
[INFO]: train job failed! train_ret: 1

**Comment by CuberrChen** [comment]
已经解决.一个小bug. 十分感谢！

**Comment by michaelowenliu** [comment]
@CuberrChen Hi, glad to hear that. If you have any more questions about PaddleSeg, please go to the page, https://github.com/PaddlePaddle/PaddleSeg/issues.

**Comment by johnyanccer** [comment]
> 已经解决.一个小bug. 十分感谢！

请问是什么bug？也碰到同样的报错信息，不知道怎么处理
