### ISSUE TITLE
【论文复现】PEGASUS: Pre-training with Extracted Gap-sentences for Abstractive Summarization

### ISSUE THREAD

**Issue by myboyliu** [PaddlePaddle/Paddle#35042]
在复现标题论文时候，能把vocab和权重先放到： https://paddlenlp.bj.bcebos.com/models/transformers

**Comment by myboyliu** [comment]
验收标准： 1. 复现PEGASUS模型（参考论文和实现链接）
2. 完成模型权重从pytorch到paddle的转换代码，转换2个预训练权重（“google/pegasus-large”，
“tuner007/pegasus_paraphrase”，“google/pegasus-xsum”，“google/pegasus-cnn_dailymail”）
---------------------------------------------------------------------------------------------------------
写的是2个，可是列了4个权重名称，到底是哪2个？

**Comment by yingyibiao** [comment]
> ## 验收标准： 1. 复现PEGASUS模型（参考论文和实现链接）
> 2. 完成模型权重从pytorch到paddle的转换代码，转换2个预训练权重（“google/pegasus-large”，
> “tuner007/pegasus_paraphrase”，“google/pegasus-xsum”，“google/pegasus-cnn_dailymail”）
> 写的是2个，可是列了4个权重名称，到底是哪2个？

这里写错了，是要求4个权重

**Comment by yingyibiao** [comment]
> 在复现标题论文时候，能把vocab和权重先放到： https://paddlenlp.bj.bcebos.com/models/transformers

在通过验收之前，暂时不支持。
