### ISSUE TITLE
导出模型时paddle.fluid.layers.where返回的tensor.shape[0]第一维为-1

### ISSUE THREAD

**Issue by songrui2009** [PaddlePaddle/Paddle#35055]
- 标题：paddle.where->paddle.fluid.layers.where返回的tensor.shape[0]第一维度为-1
- 版本、环境信息：
****************************************
Paddle version: 2.1.2
Paddle With CUDA: True

OS: Deepin 20.2
Python version: 3.7.3

CUDA version: 9.2.148
cuDNN version: None.None.None
Nvidia driver version: 460.39
****************************************
- 复现信息：paddle.where->paddle.fluid.layers.where返回的tensor.shape[0]第一维度为-1
- 问题描述：
    heat_nms = paddle.jit.dy2static.convert_call(_nms)(heat)
    heat_nms = paddle.squeeze(heat_nms, axis=0)#shape=[1,50,20]
    heat_nms = paddle.jit.dy2static.convert_call(heat_nms.transpose)(perm=[1, 2, 0])#shape=[50,20,1]
    zero = paddle.zeros(shape=paddle.jit.dy2static.convert_var_shape(heat_nms, in_control_flow=False), dtype=heat_nms.dtype)
    inds = paddle.where(heat_nms > thr, heat_nms, zero)#[50,20,1]
    inds = paddle.nonzero(inds)##返回inds.shape[-1,3],nonzero内部直接走的分支outs = layers.where(x)
    inds_end = paddle.assign(paddle.jit.dy2static.convert_call(np.array)([[0, 0, -2]]))
    inds_ = paddle.concat([inds, inds_end])##强制加入一行失败,返回inds_.shape[-1,3]

**Comment by zhwesky2010** [comment]
@songrui2009 您好，看代码是在静态图下跑的，静态图下Tensor的shape可能是有-1的，表示batch_size，只有在executor跑起来的时候 根据feed进来的数据才能-1的具体值，因为batch_size是可以改变的

**Comment by songrui2009** [comment]
可以固定batch size吗？动态下，是否不会返还-1？
