### ISSUE TITLE
Jetson AGX Xavier：Paddle/paddle/fluid/platform/dynload/nvjpeg.h:14:10: fatal error: nvjpeg.h: No such file or directory

### ISSUE THREAD

**Issue by jiafuzeng** [PaddlePaddle/Paddle#35059]
- 版本、环境信息：
    1）PaddlePaddle版本：2.1
    4）系统环境：Jetson AGX Xavier

- 安装方式信息：
2）本地编译：请提供cmake命令，编译命令
           cmake .. -DPYTHON_EXECUTABLE:FILEPATH=/usr/bin/python3 \
         -DPYTHON_INCLUDE_DIR:PATH=$PYTHON_INCLUDE_DIRS -DPYTHON_LIBRARY:FILEPATH=$PYTHON_LIBRARY\
         -DWITH_GPU=ON \
         -DWITH_TESTING=OFF \
         -DCMAKE_BUILD_TYPE=Release \
                -DWITH_ARM=ON \
                 -DON_INFER=ON \
                -DWITH_XBYAK=OFF  \
                -DWITH_NV_JETSON=ON \
                -DWITH_TENSORRT=ON \
                -DTENSORRT_ROOT=/data/Paddle/tensorrt \

make TARGET=ARMV8 -j8

![image](https://user-images.githubusercontent.com/39875080/130338494-26a77b7e-05fc-463a-9804-2ca1dde3ddd9.png)

**Comment by veerarudran** [comment]
I have bash with no such file or directory 
![Uploading IMG_20210822_062552.jpg…]()

**Comment by fengxiaoshuai** [comment]
请描述一下jetpack的版本

**Comment by jiafuzeng** [comment]
![image](https://user-images.githubusercontent.com/39875080/130385815-2872afa2-632a-4d18-aded-223ce8bde33c.png)

**Comment by fengxiaoshuai** [comment]
那估计就是你的cuda或者trt的配置出问题了，如果你没有动系统自带的cuda, cudnn, trt你可以试试这个：cmake ..   -DWITH_CONTRIB=OFF   -DWITH_MKL=OFF    -DWITH_MKLDNN=OFF   -DWITH_TESTING=OFF   -DCMAKE_BUILD_TYPE=Release   -DON_INFER=ON   -DWITH_PYTHON=ON -DPY_VERSION=3.6  -DWITH_XBYAK=OFF  -DWITH_NV_JETSON=ON -DWITH_TENSORRT=ON -DTENSORRT_ROOT=/usr -DCMAKE_CUDA_COMPILER=/usr/local/cuda-10.2/bin/nvcc  -DWITH_NCCL=OFF -DCUDA_ARCH_NAME=All -DCMAKE_CXX_FLAGS="-Wno-error -w"

**Comment by jiafuzeng** [comment]
![image](https://user-images.githubusercontent.com/39875080/130391130-7d6c0746-fb53-4843-bce7-e9049012a503.png)

**Comment by fengxiaoshuai** [comment]
jetson自带的cmake版本太低，升级到3.16.6吧, 需要先删除本地的cmake，不过在arm架构上安装新的cmake需要自己编译，试试下面的命令：
wget https://cmake.org/files/v3.16/cmake-3.16.6.tar.gz
tar zxvf cmake-3.16.6.tar.gz
./config
如果你想用paddle库的话可以直接去官网下载已经编译好的

**Comment by wangye707** [comment]
@jiafuzeng  你好，这bug是之前的一个遗留问题，现在已经修复了，请切换到tag下试试，最新的是V2.1.2。
![image](https://user-images.githubusercontent.com/39162106/130400620-fa328ed4-79a4-4541-a988-50191212558b.png)

**Comment by jiafuzeng** [comment]
官网下载已经编译好的好用

**Comment by wangye707** [comment]
好的~

**Comment by cherishTMYY** [comment]
请问您下载的是哪个啊？能否给个地址？
