### ISSUE TITLE
【论文复现】检查网络层的stop_gradient, 发现全部的且只是bn层为true

### ISSUE THREAD

**Issue by thunder95** [PaddlePaddle/Paddle#35066]
梯度反向传播过程没有了， 经过stop_gradient排查，发现只有bn层为true， 导致训练时没有梯度，请给下debug建议，应该怎么解决这个问题

**Comment by chenjiaoAngel** [comment]
请问是哪个网络呢？

**Comment by chenjiaoAngel** [comment]
是手动把stop_gradient设为true了吗，参数的stop_gradient默认是false？

**Comment by thunder95** [comment]
> 是手动把stop_gradient设为true了吗，参数的stop_gradient默认是false？

yolox的网络， 论文复现作业restnet50里也是这样， 是不是paddle里本身bn层就是false。
我现在遇到了反向传播梯度为0的情况， 请问哪种方式debug比较高效？

**Comment by zhwesky2010** [comment]
@thunder95  Tensor的stop_gradient可以直接查看，如果是动态图，可以直接print(Tensor.gradient)就行。所有参数 weight 和 bias默认在创建时都是false

**Comment by thunder95** [comment]
> @thunder95 Tensor的stop_gradient可以直接查看，如果是动态图，可以直接print(Tensor.gradient)就行。所有参数 weight 和 bias默认在创建时都是false

嗯 多谢 以定位到时切片赋值的问题，目前恢复正常了
