### ISSUE TITLE
paddle运行onnx导入的模型运行第二次就报错

### ISSUE THREAD

**Issue by tughv** [PaddlePaddle/Paddle#35068]
为使您的问题得到快速解决，在建立Issues前，请您先通过如下方式搜索是否有相似问题:【搜索issue关键字】【使用labels筛选】【官方文档】

如果您没有查询到相似问题，为快速解决您的提问，建立issue时请提供如下细节信息：
- 标题：简洁、精准概括您的问题，例如“Insufficient Memory xxx" ”
- 版本、环境信息：
    1）PaddlePaddle版本：请提供您的PaddlePaddle版本号，例如1.1或CommitID
    2）CPU：预测若用CPU，请提供CPU型号，MKL/OpenBlas/MKLDNN/等数学库使用情况
    3）GPU：预测若用GPU，请提供GPU型号、CUDA和CUDNN版本号
    4）系统环境：请您描述系统类型、版本，例如Mac OS 10.14，Python版本
 注：您可以通过执行[summary_env.py](https://github.com/PaddlePaddle/Paddle/blob/develop/tools/summary_env.py)获取以上信息。
- 训练信息
    1）单机/多机，单卡/多卡
    2）显存信息
    3）Operator信息
- 复现信息：如为报错，请给出复现环境、复现步骤
- 问题描述：请详细描述您的问题，同步贴出报错信息、日志、可复现的代码片段

我使用的是torch模型转换成onnx，再在aistudio里面转换成paddle模型，模型在两次加载的话就会抛出如下错误
[
![image](https://user-images.githubusercontent.com/40344969/130382535-288ea269-d321-4eb4-9b66-c4b1388c3dad.png)
](url)
运行环境 ：
paddle2.1.2
aistudio最高配置
单卡

**Comment by chenjiaoAngel** [comment]
这个错误提示，模型里某个参数的名字重复使用，导致运行出错；后面也有提示告诉您怎么操作，请按照这个操作，看能否解决问题
<img width="813" alt="image" src="https://user-images.githubusercontent.com/38650344/130383364-b1199e5d-f6a1-4fd5-a7fb-478b3cc2b715.png">

**Comment by tughv** [comment]
并不是啊，第一运行没有报错，后面在运行就会报错，我查了下，不止我一个人遇到这个问题，这个模型我在torch里面能跑，然后用转换工具转成paddle，我都没改

**Comment by zhiqiu** [comment]
请问下方便给出复现方式吗，另外为啥需要加载两次模型？

**Comment by tughv** [comment]
我是在aistudio里面的notebook里面运行的，这不是复现，是自己的程序，第一次运行报出其他错误，修改后运行就报这个错误
