### ISSUE TITLE
【论文复现】没有Adafactor优化器

### ISSUE THREAD

**Issue by JunnYu** [PaddlePaddle/Paddle#35060]
参考实现：https://huggingface.co/transformers/_modules/transformers/optimization.html#Adafactor
论文：https://arxiv.org/pdf/1804.04235.pdf

**Comment by haozech** [comment]
您好，您提出的新增Adafactor优化器API的需求已收到，我们会尽快评估并安排~

**Comment by TCChenlong** [comment]
可以使用其他的优化器

**Comment by dongfangyixi** [comment]
Adafactor 更新 有进展了吗？
