### ISSUE TITLE
paddle v2api merge_model报错

### ISSUE THREAD

**Issue by bushidonggua** [PaddlePaddle/Paddle#3506]
paddle merge_model --model-dir=. --model-file=alexnet_params_pass_0.model

报错：
I0815 21:27:52.719660 13596 Util.cpp:166] commandline: /home/work/chenlimin/paddlepaddle/usr/local/bin/../opt/paddle/bin/paddle_merge_model --model-dir=. --model-file=alexnet_params_pass_0.model 
ERROR: something wrong with flag 'check_sparse_distribution_in_pserver' in file '/home/yuyang/BuildAgent3/work/d55918cf60d51073/paddle/pserver/SparseParameterDistribution.cpp'.  One possibility: file '/home/yuyang/BuildAgent3/work/d55918cf60d51073/paddle/pserver/SparseParameterDistribution.cpp' is being linked both statically and dynamically into this executable.

**Comment by Xreki** [comment]
你的配置文件是怎样的？

**Comment by bushidonggua** [comment]
解决了，我用的厂内2进制安装0.9.0版本，升级到10.0就好了
