### ISSUE TITLE
[论文复现] KaimingNormal 初始化接口

### ISSUE THREAD

**Issue by jerrywgz** [PaddlePaddle/Paddle#35074]
Paddle在KaimingNormal中，如果希望使用fan_out模式，必须手动修改fan_in的值
而Pytorch中可以在kaiming_normal中直接设置mode为‘fan_out’.
这里是否可以优化KaimingNormal的接口

**Comment by chenjiaoAngel** [comment]
请问这个是在什么场景使用呢？
