### ISSUE TITLE
v2 api demo训练过程中报错

### ISSUE THREAD

**Issue by bushidonggua** [PaddlePaddle/Paddle#3507]
报错如下：我的图片应该都是正常的，我用v1 api训练过应该没有太大问题。
[INFO 2017-08-15 23:15:30,010 layers.py:2255] output for __conv_20__: c = 512, h = 14, w = 14, size = 100352
[INFO 2017-08-15 23:15:30,011 layers.py:2255] output for __conv_21__: c = 512, h = 14, w = 14, size = 100352
[INFO 2017-08-15 23:15:30,013 layers.py:2255] output for __conv_22__: c = 512, h = 14, w = 14, size = 100352
[INFO 2017-08-15 23:15:30,014 layers.py:2255] output for __conv_23__: c = 512, h = 7, w = 7, size = 25088
[INFO 2017-08-15 23:15:30,016 layers.py:2255] output for __conv_24__: c = 1024, h = 7, w = 7, size = 50176
[INFO 2017-08-15 23:15:30,018 layers.py:2255] output for __conv_25__: c = 1024, h = 7, w = 7, size = 50176
[INFO 2017-08-15 23:15:30,021 layers.py:2255] output for __conv_26__: c = 1024, h = 7, w = 7, size = 50176
[INFO 2017-08-15 23:15:30,022 layers.py:2380] output for __pool_0__: c = 1024, h = 1, w = 1, size = 1024
I0815 23:15:33.664355 20868 GradientMachine.cpp:85] Initing parameters..
I0815 23:15:33.890722 20868 GradientMachine.cpp:92] Init parameters done.
Exception in thread Thread-33:
Traceback (most recent call last):
  File "/home/work/chenlimin/paddlepaddle/python27/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/home/work/chenlimin/paddlepaddle/python27/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/work/chenlimin/paddlepaddle/python27/lib/python2.7/site-packages/paddle/v2/reader/decorator.py", line 280, in handle_worker
    r = mapper(sample)
  File "/home/work/chenlimin/paddlepaddle/demo/Mobile/flowers102/mobilenet/reader.py", line 16, in train_mapper
    img = paddle.image.simple_transform(img, 256, 224, True)
  File "/home/work/chenlimin/paddlepaddle/python27/lib/python2.7/site-packages/paddle/v2/image.py", line 284, in simple_transform
    im = resize_short(im, resize_size)
  File "/home/work/chenlimin/paddlepaddle/python27/lib/python2.7/site-packages/paddle/v2/image.py", line 158, in resize_short
    assert im.shape[-1] == 1 or im.shape[-1] == 3
AttributeError: 'NoneType' object has no attribute 'shape'

**Comment by dzhwinter** [comment]
这个是预处理时候就出错了，输出一下im，是否为空？

**Comment by dzhwinter** [comment]
I found that he use mobilenet. can you follow this issue  @NHZlX ?

**Comment by bushidonggua** [comment]
找到原因了，我在生成train.list的时候偷懒了下用的另一个模型训练的数据，这个项目有些图片缺失，感谢！

**Comment by bushidonggua** [comment]
对了，我还发现提供的demo有个bug，就是在发生这种报错时进程不会退出，也不会生成模型

**Comment by NHZlX** [comment]
@bushidonggua 出现bug的时候不会保存模型，程序都有bug了，那生成模型有什么用呢。不过用户ctr+c的时候paddle目前也不保存模型，这个需要进行改进。进程不会退出具体指的是？

**Comment by bushidonggua** [comment]
@NHZlX 我是用nohup起的，跑v1时失败了是会退出的，但是这个失败了以后不退出也不会跳过继续训练，用ps会看到好几个先前失败的进程，连前几天的都有，如果直接在终端启动，你会看到一直停留在那个异常日志那，除非你ctr+c，不过一般我都不会直接在终端启动，万一断网了不都白跑了，所以像这种异常不退出的，我必须一个个手动kill掉

**Comment by bushidonggua** [comment]
还有个问题，我把这个问题修好了，dansh但是这个跑完了直接退出了，也没保存模型，啥日志都没有，不明白怎么回事：
![image](https://user-images.githubusercontent.com/5506467/29346497-55f231ac-8278-11e7-85c5-4bc9eac1c902.png)

代码：
    def event_handler(event):
        if isinstance(event, paddle.event.EndIteration):
            if event.batch_id % 1 == 0:
                print "\nPass %d, Batch %d, Cost %f, %s" % (
                    event.pass_id, event.batch_id, event.cost, event.metrics)
            else:
                sys.stdout.write('.')
                sys.stdout.flush()
        if isinstance(event, paddle.event.EndPass):
            # save parameters
            with gzip.open('mobilenet_params_pass_%d.tar.gz' % event.pass_id, 'w') as f:
                parameters.to_tar(f)

            result = trainer.test(
                    reader=test_reader,
                feeding={'image': 0,
                         'label': 1})
            print "\nTest with Pass %d, %s" % (event.pass_id, result.metrics)

    trainer.train(
            reader=train_reader,
            num_passes=200,
            event_handler=event_handler,
            feeding={'image': 0,
                     'label': 1})

**Comment by NHZlX** [comment]
@bushidonggua  看你的代码应该是一个forward backward 会打印一次信息，一个pass之后会保存一次模型，由于数据直接读的图片，所以可能存在io性能问题， 可以用padde.reader.shffle来设置buffer
```
trainer.train(
        reader=paddle.batch(
            paddle.reader.shuffle(
                paddle.dataset.flowers.train(), buf_size=50000),
            batch_size=BATCH),
        num_passes=200,
        event_handler=event_handler,
        feeding={'image': 0,
```

**Comment by NHZlX** [comment]
贴一下完整的train.py

**Comment by bushidonggua** [comment]
@NHZlX   就是mobilenet源码，我只是改了下数据集
import sys
import gzip
from paddle.trainer_config_helpers import *
import paddle.v2 as paddle
from mobilenet import mobile_net
import reader

BATCH = 128
def main():
    datadim = 3 * 224 * 224
    classdim = 6

    # PaddlePaddle init
    paddle.init(use_gpu=False, trainer_count=1, gpu_id = 1)

    momentum_optimizer = paddle.optimizer.Momentum(
        momentum=0.9,
        regularization=paddle.optimizer.L2Regularization(rate=0.0005 * BATCH),
        learning_rate=0.005/ BATCH,
        #learning_rate_decay_a=0.1,
        #learning_rate_decay_b=50000 * 50,
        learning_rate_schedule='constant')

    image = paddle.layer.data(
        name="image", type=paddle.data_type.dense_vector(datadim))

    net = mobile_net(image)
    out = paddle.layer.fc(
        input=net, size=classdim, act=paddle.activation.Softmax())
    lbl = paddle.layer.data(
        name="label", type=paddle.data_type.integer_value(classdim))
    cost = paddle.layer.classification_cost(input=out, label=lbl)

    # Create parameters
    parameters = paddle.parameters.create(cost)
    with gzip.open('imagenet_pretrained_mobilenet.tar.gz', 'r') as f:
        fparameters = paddle.parameters.Parameters.from_tar(f)
    for param_name in fparameters.names():
        if param_name in parameters.names():
            parameters.set(param_name, fparameters.get(param_name))

    train_reader = paddle.batch(
        paddle.reader.shuffle(
            reader.train_reader('train.list'),
            buf_size=50000),
        batch_size=BATCH)
    test_reader = paddle.batch(
        reader.test_reader('val.list'),
        batch_size=BATCH)

    # End batch and end pass event handler
    def event_handler(event):
        if isinstance(event, paddle.event.EndIteration):
            if event.batch_id % 1 == 0:
                print "\nPass %d, Batch %d, Cost %f, %s" % (
                    event.pass_id, event.batch_id, event.cost, event.metrics)
            else:
                sys.stdout.write('.')
                sys.stdout.flush()
        if isinstance(event, paddle.event.EndPass):
            # save parameters
            with gzip.open('mobilenet_params_pass_%d.tar.gz' % event.pass_id, 'w') as f:
                parameters.to_tar(f)

            result = trainer.test(
                    reader=test_reader,
                feeding={'image': 0,
                         'label': 1})
            print "\nTest with Pass %d, %s" % (event.pass_id, result.metrics)
    # Create trainer
    trainer = paddle.trainer.SGD(
        cost=cost, parameters=parameters, update_equation=momentum_optimizer)
    trainer.train(
            reader=train_reader,
            num_passes=200,
            event_handler=event_handler,
            feeding={'image': 0,
                     'label': 1})

**Comment by gongweibao** [comment]
Feel free to reopen it!
