### ISSUE TITLE
paddle android  capi加载模型预测结果与v1 api demo的预测结果不一致

### ISSUE THREAD

**Issue by bushidonggua** [PaddlePaddle/Paddle#3508]
在android平台用capi的预测结果和服务端不一致，是否是跟这个meta_path  mean_path 文件做的事有关？这个是做什么的？

训练配置文件：
from paddle.trainer_config_helpers import *
is_predict = get_config_arg("is_predict", bool, False)
####################Data Configuration ##################
if not is_predict:
    data_dir = 'data/gesture_image/batches/'
    meta_path = data_dir + 'batches.meta'

    args = {
        'meta': meta_path,
        'mean_img_size': 32,
        'img_size': 32,
        'num_classes': 6,
        'use_jpeg': 1,
        'color': "color"
    }

    define_py_data_sources2(
        train_list="train.list",
        test_list="train.list",
        module='image_provider',
        obj='processData',
        args=args)
服务端预测：
    obj = ImageClassifier(
        train_conf=config,
        model_dir=model_path,
        resize_dim=image_size,
        crop_dim=crop_size,
        mean_file=mean_path,
        use_gpu=use_gpu,
        oversample=multi_crop)
    obj.predict(image, output_layer)

**Comment by dzhwinter** [comment]
对你用的模型不了解。在图像里mean file常用来做均值减法，把图像里的每个值都减去一个该通道的 mean value(在数据集上对应通道像素值的平均值)。目的是让模型更加稳健，和normalize 是同一个思路。meta_path就不清楚了。mean file这个会影响预测结果，如果训练时候有减去，预测时候也必须减去 mean value.   如果是Android相关问题请问一下 @Xreki

**Comment by bushidonggua** [comment]
meta_path是否就是存放每个通道均值的文件？如果是的话我可以知道这个文件的存储格式么？由于capi并没有提供相应的加载这个文件的接口，所以我需要自己去解析这个文件来减去每个通道的均值是吧？
