### ISSUE TITLE
paddle静态图如何在数据流动的过程中打印模型接收到的dict数据

### ISSUE THREAD

**Issue by longtaizi13579** [PaddlePaddle/Paddle#35080]
1）PaddlePaddle版本：2.1.2
    2）CPU：28  Intel(R) Xeon(R) Gold 5117 CPU @ 2.00GHz
    3）GPU：Tesla P40
    4）系统环境：Linux version 3.10.0_3-0-0-29(gcc version 4.8.2 20140120 (Red Hat 4.8.2-16) (GCC) ),python3.7
我是想在静态图构图的时候，像动态图一样，打印一下输入信息，但直接使用logging.info打印出来的是placeholder的结构，用fluid.layers.Print又会曝出如下错误：TypeError: The type of 'input' in fluid.layers.Print must be <class 'paddle.fluid.framework.Variable'>, but received <class 'dict'>. 
可能是由于这个函数只能打印静态图中的Variable格式的数据，dict数据是我输入静态图的数据格式，它没法在run的部分查看，因此希望在静态图中插入节点以至于能够看到我的输入类型为dict的数据

**Comment by chenjiaoAngel** [comment]
这样使用可以的，fluid.layers.Print(info["key"])
