### ISSUE TITLE
Sorry, your code style check failed.

### ISSUE THREAD

**Issue by XYZ-916** [PaddlePaddle/Paddle#35097]
请问有没有什么自动化的方式把代码style进行优化？

**Comment by chenjiaoAngel** [comment]
可以安装pre-commit 和 clang-format 工具进行格式检查和代码格式优化

**Comment by XYZ-916** [comment]
![log](https://user-images.githubusercontent.com/14884056/130717604-11447bcd-2d12-468f-a8a0-bceaf197ed3b.png)
![change](https://user-images.githubusercontent.com/14884056/130717610-1e8b4ea7-35b8-4978-986c-cb89d54642eb.png)
请问我提交的代码的格式为什么跟流水报错的格式不一致？这个code style问题要怎么解决？我明明已经按照规范空格了。

**Comment by chenjiaoAngel** [comment]
<img width="620" alt="image" src="https://user-images.githubusercontent.com/38650344/131276627-a0bc0a95-e290-43ae-9dd7-0643cde06698.png">
这个axis_dim处对齐是空四个空格,和PADDLE的L对齐
PADDLE_ENFORCE_GT(
          axis_dim, 0,
          platform::errors::InvalidArgument(
                 "");
