### ISSUE TITLE
【论文复现】paddle没有pool的二次梯度算子

### ISSUE THREAD

**Issue by wangna11BD** [PaddlePaddle/Paddle#35119]
StyleGAN复现需要一些算子的二次梯度https://github.com/tomguluson92/StyleGAN_PyTorch/blob/4fd0711f560b9b080fca3df2448822835226ba02/loss/loss.py#L14
其中pool算子无二次梯度

**Comment by Leonardo-Ding** [comment]
同学你好，你的问题会反馈到开发人员进行评估，评估后如果需要会考虑在后续版本中添加这一feature，谢谢

**Comment by Leonardo-Ding** [comment]
同学你好，你反馈的问题会进一步反馈给开发同学进行评估，评估后如果需要会考虑在后续版本中进行添加，谢谢。
