### ISSUE TITLE
使用docker编译paddle+xpu环境，https的github资源下载不来，Operation timed out

### ISSUE THREAD

**Issue by helen88** [PaddlePaddle/Paddle#35110]
docker编译：
1）镜像：registry.baidubce.com/paddlepaddle/paddle   2.1.0
        
 2）编译命令：

cmake .. -DPY_VERSION=3.7        -DCMAKE_BUILD_TYPE=Release         -DWITH_GPU=OFF       -DWITH_XPU=ON       -DON_INFER=ON  -DWITH_PYTHON=ON        -DWITH_MKL=OFF       -DWITH_XPU_BKCL=ON       -DWITH_TESTING=ON
![image](https://user-images.githubusercontent.com/4593091/130570805-8f9a9f39-a3d0-48d0-9e0d-784f5bb05b26.png)
有很多https://github的资源都下不下来

**Comment by Leonardo-Ding** [comment]
同学你好，尝试用一下厂内的代理服务器
