### ISSUE TITLE
fill_constant corner case踩坑报错

### ISSUE THREAD

**Issue by Yelrose** [PaddlePaddle/Paddle#35142]
https://github.com/PaddlePaddle/Paddle/blob/086540ccb4e8cde02176f3134adf09e92ac9d3fc/python/paddle/fluid/layers/utils.py#L366

这个地方在某种corner case上会出问题，建议改成下面代码

```
map(lambda x: x.numpy().flat[0] if isinstance(x, Variable) else x, shape))
```

触发条件
```
import paddle
import numpy as np
size_a = paddle.tensor(np.array(1))
paddle.zeros(shape=[size_a, 100], dtype="float32")

```

**Comment by qili93** [comment]
收到，感谢反馈，会联系API负责人进行相关API的修复。
