### ISSUE TITLE
pip install 失败

### ISSUE THREAD

**Issue by zongming256** [PaddlePaddle/Paddle#3515]
公司内部使用，机器可以连外网
按照wiki的方法：pip install paddlepaddle-gpu
提示信息如下：
Collecting paddlepaddle-gpu
  Downloading paddlepaddle_gpu-0.10.1-cp27-cp27mu-manylinux1_x86_64.whl (42.2MB)
    2% |                                | 1.0MB 1.2kB/s eta 9:11:44
.........
ReadTimeoutError: HTTPSConnectionPool(host='pypi.python.org', port=443): Read timed out.

若设置镜像地址：pip install paddlepaddle-gpu --trusted-host pip.baidu.com -i  http://pip.baidu.com 
提示信息如下：
Collecting paddlepaddle-gpu
  Could not find a version that satisfies the requirement paddlepaddle-gpu (from versions: )
No matching distribution found for paddlepaddle-gpu

**Comment by pkuyym** [comment]
@zongming256 你可以试试
```pip install --index-url http://pip.baidu.com/pypi/simple --trusted-host pip.baidu.com paddlepaddle-gpu```

**Comment by zongming256** [comment]
安装完了以后，运行book中的例子报错：
Traceback (most recent call last):
  File "train.py", line 234, in <module>
    main()
  File "train.py", line 138, in main
    paddle.init(use_gpu=False, trainer_count=1)
  File "/home/img/chenjianfeng/anaconda2/lib/python2.7/site-packages/paddle/v2/__init__.py", line 66, in init
    import py_paddle.swig_paddle as api
  File "/home/img/chenjianfeng/anaconda2/lib/python2.7/site-packages/py_paddle/__init__.py", line 15, in <module>
    from util import DataProviderWrapperConverter
  File "/home/img/chenjianfeng/anaconda2/lib/python2.7/site-packages/py_paddle/util.py", line 18, in <module>
    import swig_paddle
  File "/home/img/chenjianfeng/anaconda2/lib/python2.7/site-packages/py_paddle/swig_paddle.py", line 28, in <module>
    _swig_paddle = swig_import_helper()
  File "/home/img/chenjianfeng/anaconda2/lib/python2.7/site-packages/py_paddle/swig_paddle.py", line 24, in swig_import_helper
    _mod = imp.load_module('_swig_paddle', fp, pathname, description)
ImportError: /home/img/chenjianfeng/anaconda2/lib/python2.7/site-packages/scipy/special/../../../../libstdc++.so.6: version `CXXABI_1.3.8' not found (required by /home/img/chenjianfeng/anaconda2/lib/python2.7/site-packages/py_paddle/_swig_paddle.so)

**Comment by pkuyym** [comment]
建议你把gcc48的lib64添加到LD_LIBRARY_PATH里面

**Comment by zongming256** [comment]
下载源失效了吗？
pip install --index-url http://pip.baidu.com/pypi/simple --trusted-host pip.baidu.com paddlepaddle-gpu

提示信息：
Could not find a version that satisfies the requirement paddlepaddle-gpu (from versions: )
No matching distribution found for paddlepaddle-gpu

**Comment by typhoonzero** [comment]
@zongming256 seems that your python doesn't support python "cp27mu" type, will upload a corresponding "cp27m" package so that you can install.

**Comment by typhoonzero** [comment]
Uploaded `cp27m` package for some platforms, which version is `0.10.1`. If you encountered numpy errors when `paddle.init()` try upgrading numpy to `1.13.1`.

**Comment by Apollo2Mars** [comment]
The problems as follow:

$ pip install paddlepaddle_gpu
Collecting paddlepaddle_gpu
  Could not find a version that satisfies the requirement paddlepaddle_gpu (from versions: )
No matching distribution found for paddlepaddle_gpu
