### ISSUE TITLE
保存模型时，多了scale 1？

### ISSUE THREAD

**Issue by xiebaiyuan** [PaddlePaddle/Paddle#35164]
- 标题：保存模型时，多了scale 1？
- 版本、环境信息：
    1）PaddlePaddle版本：请2.1
    2）CPU/GPU：CPU
    3）系统环境：Ubuntu
    4）Python版本号:3.7
    5）显存信息
 注：您可以通过执行[summary_env.py](https://github.com/PaddlePaddle/Paddle/blob/develop/tools/summary_env.py)获取以上信息。
- 复现信息：如为报错，请给出复现环境、复现步骤
- 问题描述：
保存模型时发现后面多了 scale 这是为什么呢

**Comment by T8T9** [comment]
这个scale是框架自动加上去的, 不是错误哈. 这个是为了解决框架问题, 后续我们把具体原因加在文档中.

**Comment by xiebaiyuan** [comment]
> 这个scale是框架自动加上去的, 不是错误哈. 这个是为了解决框架问题, 后续我们把具体原因加在文档中.

OK 到时候也quote我下吧

**Comment by zxxxxxxxin** [comment]
> 这个scale是框架自动加上去的, 不是错误哈. 这个是为了解决框架问题, 后续我们把具体原因加在文档中.

请问这个加载了文档哪部分
