### ISSUE TITLE
avx警告

### ISSUE THREAD

**Issue by isLiuHao** [PaddlePaddle/Paddle#35163]
源码编译完，出现以下avx警告，会影响使用吗？会影响性能吗？
![1629950389(1)](https://user-images.githubusercontent.com/74350741/130898495-cfe5a0f5-d78b-4b8e-a4c0-23f051752233.png)

**Comment by isLiuHao** [comment]
有人可以帮忙解释一下吗

**Comment by isLiuHao** [comment]
请问有人能解答一下吗

**Comment by T8T9** [comment]
没有影响的, 可能你的cpu比较老, 不支持avx加速, 不影响使用, 就是性能可能低一些
