### ISSUE TITLE
pytorch转换为paddle中可视化方面问题

### ISSUE THREAD

**Issue by 978326187** [PaddlePaddle/Paddle#35189]
`from torch.utils.tensorboard import SummaryWriter`
这一段代码在paddle中有对应的用法吗

**Comment by ShenYuhan** [comment]
如果是使用标量记录点数据，可以参考paddle中visualdl接口，文档在 https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/callbacks/VisualDL_cn.html#visualdl

如果是对可视化有更多的需求，可以直接使用visualdl，参考文档在
https://github.com/PaddlePaddle/VisualDL/blob/develop/README_CN.md

**Comment by 978326187** [comment]
https://github.com/PaddlePaddle/Paddle/issues/1746
这个issue里有说会发布PaddleBoard，现在还有这个计划吗？

**Comment by yinhaofeng** [comment]
这个是2017年的issue了，可视化方面的问题现在可以直接使用visualdl

**Comment by 978326187** [comment]
好的，感谢回复

**Comment by 978326187** [comment]
另外，我在AIstudio上的项目一直显示“ 正在停止 ”，可以帮忙反馈一下吗？

**Comment by yinhaofeng** [comment]
这个需要几分钟停止是正常的，需要保存文件等进行操作，如果停止时间过长（比如几十分钟到几个小时）可能是后台机器出问题了，你可以将项目链接发送到aistudio相关部门的邮箱中， 邮箱在产品网页底部有哈

**Comment by 978326187** [comment]
我的从10点半开始关的。。。

**Comment by 978326187** [comment]
项目终于停止了。。。。
