### ISSUE TITLE
paddle2.1如何手动释放计算图？

### ISSUE THREAD

**Issue by KinvenW** [PaddlePaddle/Paddle#35182]
paddle2.1的动态图模型，我想在某些情况下在执行forward之后手动释放计算图，不调用loss.backward()，要怎么做呢？clear_grad似乎不能释放前向计算图

**Comment by T8T9** [comment]
不是很清楚你这个问题, 如果不想生成计算图可以用no_grad
@KinvenW @JiabinYang
