### ISSUE TITLE
Remove std::shared_ptr for OperatorBase

### ISSUE THREAD

**Issue by reyoung** [PaddlePaddle/Paddle#3520]
As we discussed before, shared_ptr is preferred to avoid in our refactoring code for simplifying our design and making lifecycle management clearer.

The shared_ptr of OperatorBase should be removed. We design our operator lifecycle like below:

* all Python API will return an `OperatorBase*` or `NetOp*`. We let Python side to destroy operators.
* If we destroy a `NetOp` or `RnnOp` (which contains step_net), all operator belongs to that net will be destroyed, too.
* If two `NetOp` want to share same `Operator`, or `NetOp` add an `Operator*` but that `Operator*` is held by Python, too. We use `Operator::Clone()` to create a new Operator pointer. i.e. One operator instance is avoided to be shared by multiple NetOp.
  * Since our operator design is very lightweight(only variable names and attrs are stored), and topology is constructed before whole training started, `Clone` an operator will simplify our design without costing too much in time and space.

The whole things come to following steps:

1. [x] Add `Clone` method to OperatorBase
2. [x]  Remove shared_ptr inside C++ and Python
3. [ ] Expose `CreateOpAndAddItToSelf` method for `NetOp` in Python(to avoid `Clone` every time).

**Comment by Canpio** [comment]
I'm wondering whether we really need to destroy operators. Operators' life cycle seems as long as the whole training program. Can we just leave them there and wait they being recycled by the OS after program exit?

**Comment by reyoung** [comment]
> I'm wondering whether we really need to destroy operators. Operators' life cycle seems as long as the whole training program.

1. Not really for the dynamic network. i.e. the topology could be flux in each mini-batch. Operators need be able to destroy.
2. For unit-tests, each test case should destroy its operators inside.
