### ISSUE TITLE
pytorch代码转paddle相关问题

### ISSUE THREAD

**Issue by 978326187** [PaddlePaddle/Paddle#35210]
`torchvision.utils.make_grid`
Torchvision里面的make_grid接口在paddle里面有对应的吗

**Comment by yinhaofeng** [comment]
PyTorch（v1.8.1)常用API与PaddlePaddle 2.0.0 API对应关系与差异分析文档
https://www.paddlepaddle.org.cn/documentation/docs/zh/guides/08_api_mapping/pytorch_api_mapping_cn.html

**Comment by 978326187** [comment]
好的我去看一下，感谢！

**Comment by HighCWu** [comment]
为什么关闭issue，paddle目前并没有make_grid的操作

**Comment by 978326187** [comment]
我在那个AI studio的论坛上交了个反馈，所以就关了

**Comment by HighCWu** [comment]
> 我在那个AI studio的论坛上交了个反馈，所以就关了

明白了。不过一般是等到问题解决了才关闭issue，我建议再次打开。我在搜索issue时看到关闭了以为问题已经解决了。
