### ISSUE TITLE
Add `Clone` method for OperatorBase

### ISSUE THREAD

**Issue by reyoung** [PaddlePaddle/Paddle#3521]
This is the first step of removing `shared_ptr` of OperatorBase. The parent issue is #3520

**Comment by wangkuiyi** [comment]
Why this step is necessary to remove shared_ptr?  I noticed that Operator::Clone returns a unique_ptr now, but our goal is to remove the unnecessary use of smart pointers.

**Comment by reyoung** [comment]
> Why this step is necessary to remove shared_ptr? 

因为事实上同样的Operator实例会被不同的网络共享(两个不同的拓扑结构，但是共享了一个子拓扑结构)。如果我们要删掉shared_ptr，我们必须让Operator支持拷贝功能。让每一个NetOp去持有他自己的所有Operator。不同网络需要共享子网络的时候，调用子网络的复制就好。

因为OperatorBase是一个基类，它并不能实现多态的复制构造函数。所以，使用`Clone`方法。

> I noticed that Operator::Clone returns a unique_ptr now, but our goal is to remove the unnecessary use of smart pointers.

Quote from google C++ style

> If dynamic allocation is necessary, prefer to keep ownership with the code that allocated it. If other code needs access to the object, consider passing it a copy, or passing a pointer or reference without transferring ownership. Prefer to use std::unique_ptr to make ownership transfer explicit.

Google C++ style首先应该避免转交指针的ownership，即从哪里申请就从哪里释放。但是`Clone`函数和构造函数类似，就是要新建一个指针。

在其C++ Style中说明，如果要转交指针的ownership，最好用unique_ptr让ownership的转交更明确。

```cpp
// it is user's responsibility to free returned instance.
OperatorBase* Clone() const;
```

如果接口如此的话，调用者需要阅读.h中的函数注释，才能知道是否需要自己释放这段内存。并且调用者得是合格的C++编程人员，有意识去释放申请的内存。

而使用

```cpp
std::unique_ptr<OperatorBase> Clone() const;
```

调用者明显就能知道这个OpBase的释放会自己负责。而且unique_ptr会释放这个内存。

这正如Google C++ Style中给出的样例代码原理一致:

```cpp
std::unique_ptr<Foo> FooFactory();
void FooConsumer(std::unique_ptr<Foo> ptr);
```


总结Google C++ Style中的一些说明，我们是不是可以将如下标准作为我们的代码标准:

除内存申请模块`paddle::memory`外:

1. 优先不动态申请内存。
2. 第一条不满足，则 哪个类申请动态内存，哪个释放动态内存。
   * 约定，对于这种情况外部对象需要访问这个动态内存时，可以使用裸指针。所有返回裸指针的接口都不需要用户释放内存。譬如 [`Scope::NewVar`](https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/framework/scope.h#L52).
3. 如果第二条不满足，即需要在一个类型申请动态内存，在另一个类型中释放动态内存。
   * 譬如`Registry`中的Create函数，Op的Clone函数
   * 约定，返回 [`unique_ptr<T>`](https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/framework/op_registry.h#L80)。来明确ownership的转移。
   * 对于这个指针的使用方，如果想要接手这个指针的ownership，则使用`std::unique_ptr`做为函数参数。
4. 如果第三条不满足，这通常说明我们的设计有问题，应该避免。
