### ISSUE TITLE
text_classification demo使用自己的训练数据集，auc为0

### ISSUE THREAD

**Issue by zhangyuzhen1990** [PaddlePaddle/Paddle#3523]
使用文本分类demo：https://github.com/PaddlePaddle/models/tree/develop/text_classification 拿自己的数据集训练，auc为0
训练数据如下：
schema: label \t char char char ....
0	~ 一 个 简 单 的 方 法 感 觉 自 己 得 了 抑 郁 怎 . .
0	状 风 湿 的 各 期 症 状 ? 分 期 针 对 治 . .
1	「 公 立 」 皮 肤 红 过 敏 怎 么 治 皮 肤 红 过 敏 原 因
1	「 皮 肤 专 科 」 过 敏 的 症 状 有 哪 . .
1	「 六 项 」 内 分 泌 六 项 检 查 时 间 ? 6 项 检 查 1 8 0 元
利用6万+正例，6万+负例作为输入，run demo，auc为0

**Comment by hedaoyuan** [comment]
有个相似的 #3031 
样本有shuffle吗？
