### ISSUE TITLE
导出自定义模型报错：The Tensor of Variable(dygraph_tmp_240) to be saved is not initialized.

### ISSUE THREAD

**Issue by songrui2009** [PaddlePaddle/Paddle#35238]
- 标题：导出自定义模型报错：The Tensor of Variable(dygraph_tmp_240) to be saved is not initialized.
- 版本、环境信息：
Paddle version: 2.1.2
Paddle With CUDA: True

OS: Deepin 20.2
Python version: 3.7.3

CUDA version: 9.2.148
cuDNN version: None.None.None
Nvidia driver version: 460.39
- 问题描述：
    InvalidArgumentError: The Tensor of Variable(dygraph_tmp_240) to be saved is not initialized.
      [Hint: Expected tensor.IsInitialized() == true, but received tensor.IsInitialized():0 != true:1.] (at /paddle/paddle/fluid/operators/save_combine_op.h:80)

找不到dygraph_tmp_240定义在哪，/tmp/中生成的.py文件也没有；给出的堆栈无法定位，基本都是paddle和python内部的函数；
看了下save_combine_op.h:80，也没什么可用信息；注释掉所有forward的内部代码，也会报同样的错误；

**Comment by songrui2009** [comment]
有什么方法可以帮忙定位问题未知？

**Comment by songrui2009** [comment]
找到问题所在了，单不知道什么原因，问题如下：在模型的__init__预先算了一些Tensor，并保存在list中；导出的时候会先构造模型，也就是Tensor被创建了出来；然后再进行导出操作，导出时被保存的Tensor没有被转换成LodTensor，导致错误发生；不放在List中是能够被自动转换成LodTensor的，也不会有这个问题；具体原因不行，希望能够得到解释~~~~
同时这种错误，不好查，提示的堆栈基本没用.

**Comment by Aurelius84** [comment]
> 在模型的__init__预先算了一些Tensor，并保存在list中

我们不支持将定义在python原生list中的Tensor保存下来，可以通过如下两种方式来实现：

+ 方式一：将Tensor注册为Buffer
```python
class MyNet(nn.Layer):
    def __init__(self):
        self.tensors = [self.register_buffer(name='buffer_%s'%i, x) for i, x in enumerate(tensor_list)]
```
+ 方式二：将 list 替换为 ParamList，用法见[官方文档](https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/nn/ParameterList_cn.html#parameterlist)

**Comment by songrui2009** [comment]
感谢

**Comment by TinyQi** [comment]
> 感谢

如果变量特别多，怎么排查哪个变量存在未初始化的问题呢?
我也遇到这个问题了，https://github.com/PaddlePaddle/Paddle/issues/56998

**Comment by TinyQi** [comment]
> 如果变量特别多，怎么排查哪个变量存在未初始化的问题呢?
> 我也遇到这个问题了，#56998

如果变量特别多，怎么排查哪个变量存在未初始化的问题呢?
我也遇到这个问题了，https://github.com/PaddlePaddle/Paddle/issues/56998

**Comment by TinyQi** [comment]
> 如果变量特别多，怎么排查哪个变量存在未初始化的问题呢?
> 我也遇到这个问题了，#56998

如果变量特别多，怎么排查哪个变量存在未初始化的问题呢?
我也遇到这个问题了，https://github.com/PaddlePaddle/Paddle/issues/56998
