### ISSUE TITLE
编译报错

### ISSUE THREAD

**Issue by isLiuHao** [PaddlePaddle/Paddle#35234]
jetson agx xavier，jetpack4.5，paddle2.0.2,，cmake3.21
请问一下，编译遇到extern_cryptopp一直编译不通过，怎么解决？
![捕获](https://user-images.githubusercontent.com/74350741/131202000-2622c5f7-524e-4041-a165-d3b3fec09df8.PNG)

**Comment by isLiuHao** [comment]
cmake .. \
          -DWITH_CONTRIB=OFF \
          -DWITH_MKL=OFF  \
          -DWITH_MKLDNN=OFF \
          -DWITH_TESTING=OFF \
          -DCMAKE_BUILD_TYPE=Release \
          -DON_INFER=ON \
          -DWITH_PYTHON=ON \
          -DWITH_XBYAK=OFF  \
          -DWITH_NV_JETSON=ON \
          -DPY_VERSION=3.6 \
          -DCUDA_ARCH_NAME=Auto
make TARGET=ARMV8 -j4

**Comment by littletomatodonkey** [comment]
你好，是要编译预测库吗？可以参考这个文档：https://paddleinference.paddlepaddle.org.cn/user_guides/source_compile.html
