### ISSUE TITLE
[论文复现]多级索引方式不能修改tensor

### ISSUE THREAD

**Issue by jesse01** [PaddlePaddle/Paddle#35242]
1）PaddlePaddle版本：2.1.2及开发版本
2）GPU：任意版本
4）系统环境：任意环境

训练信息
   1）无论单机、多机
   2）显存多少无关
复现信息：100%复现
问题描述：多级索引方式不能修改tensor
如果以这种多级索引方式修改tensor, 代码可以正常执行，但是数据不会改变
data[i][j][k] = 1.0
改成：
data[i, j, k] = 1.0 
则正常

![image](https://user-images.githubusercontent.com/6436061/131238633-a2587356-26d4-48d6-ae2b-4f808908cb80.png)

**Comment by MissPenguin** [comment]
是的，修改tensor的话需要用data[i, j, k] = 1.0这种方式的。读取用两种方式都可以。

**Comment by jesse01** [comment]
data[i][j]这种方式赋值允许调用，但是赋值不成功，这应该作为BUG进行修复。无论哪个软件data[i][j]与data[i, j]表示都是等价且行为一致，请看以下例子：
1.numpy
![image](https://user-images.githubusercontent.com/6436061/131870643-95298a1f-740f-4d15-9805-d8b804a0b5e9.png)

2.pytorch
![image](https://user-images.githubusercontent.com/6436061/131870863-d9f2fdc2-4cff-4bb7-b057-37215b76084f.png)

3.tensorflow
![image](https://user-images.githubusercontent.com/6436061/131871321-9badc60b-be2b-4896-95a7-18a339568d43.png)
