### ISSUE TITLE
[论文复现]YOLOX单机多卡训练过程中报paddle.logical_not报错

### ISSUE THREAD

**Issue by jesse01** [PaddlePaddle/Paddle#35240]
1）PaddlePaddle版本：2.1.2
    2）GPU：CUDA 10.1 和CUDNN 7.6， 单机四卡
    4）系统环境：Python 3.7,  aistudio脚本任务环境

- 训练信息
    1）单机4卡
    2）显存每卡32 G
+=======================================================================================+
    |                        Distributed Envs                      Value                    |
    +---------------------------------------------------------------------------------------+
    |                       PADDLE_TRAINER_ID                        0                      |
    |                 PADDLE_CURRENT_ENDPOINT                 127.0.0.1:55001               |
    |                     PADDLE_TRAINERS_NUM                        4                      |
    |                PADDLE_TRAINER_ENDPOINTS  ... 0.1:41722,127.0.0.1:43990,127.0.0.1:49511|
    |                     PADDLE_RANK_IN_NODE                        0                      |
    |                 PADDLE_LOCAL_DEVICE_IDS                        0                      |
    |                 PADDLE_WORLD_DEVICE_IDS                     0,1,2,3                   |
    |                     FLAGS_selected_gpus                        0                      |
    |             FLAGS_selected_accelerators                        0                      |
    +=======================================================================================+

- 问题描述：YOLOX论文第8个epoch报错
在第8个epoch约90%迭代位置，运行paddle.logical_not报错，具体出错信息如下：
2021-08-29 10:01:09 | INFO     | yolox.core.trainer:219 - epoch: 8/300, iter: 3280/3697, iter_time: 1.654s, data_time: 0.007s, total_loss: 8.3, iou_loss: 2.6, l1_loss: 0.0, conf_loss: 3.6, cls_loss: 2.1, lr: 6.248e-04, size: 608, ETA: 18 days, 9:44:49
Error: /paddle/paddle/fluid/operators/bce_loss_op.cu:38 Assertion `(x >= static_cast<T>(0)) && (x <= one)` failed. Input is expected to be within the interval [0, 1], but recieved nan.
Error: /paddle/paddle/fluid/operators/bce_loss_op.cu:38 Assertion `(x >= static_cast<T>(0)) && (x <= one)` failed. Input is expected to be within the interval [0, 1], but recieved nan.
Error: /paddle/paddle/fluid/operators/bce_loss_op.cu:38 Assertion `(x >= static_cast<T>(0)) && (x <= one)` failed. Input is expected to be within the interval [0, 1], but recieved nan.
Error: /paddle/paddle/fluid/operators/bce_loss_op.cu:38 Assertion `(x >= static_cast<T>(0)) && (x <= one)` failed. Input is expected to be within the interval [0, 1], but recieved nan.
Error: /paddle/paddle/fluid/operators/bce_loss_op.cu:38 Assertion `(x >= static_cast<T>(0)) && (x <= one)` failed. Input is expected to be within the interval [0, 1], but recieved nan.
Error: /paddle/paddle/fluid/operators/bce_loss_op.cu:38 Assertion `(x >= static_cast<T>(0)) && (x <= one)` failed. Input is expected to be within the interval [0, 1], but recieved nan.
Error: /paddle/paddle/fluid/operators/bce_loss_op.cu:38 Assertion `(x >= static_cast<T>(0)) && (x <= one)` failed. Input is expected to be within the interval [0, 1], but recieved nan.
Error: /paddle/paddle/fluid/operators/bce_loss_op.cu:38 Assertion `(x >= static_cast<T>(0)) && (x <= one)` failed. Input is expected to be within the interval [0, 1], but recieved nan.
Error: /paddle/paddle/fluid/operators/bce_loss_op.cu:38 Assertion `(x >= static_cast<T>(0)) && (x <= one)` failed. Input is expected to be within the interval [0, 1], but recieved nan.
Error: /paddle/paddle/fluid/operators/bce_loss_op.cu:38 Assertion `(x >= static_cast<T>(0)) && (x <= one)` failed. Input is expected to be within the interval [0, 1], but recieved nan.
Error: /paddle/paddle/fluid/operators/bce_loss_op.cu:38 Assertion `(x >= static_cast<T>(0)) && (x <= one)` failed. Input is expected to be within the interval [0, 1], but recieved nan.
Error: /paddle/paddle/fluid/operators/bce_loss_op.cu:38 Assertion `(x >= static_cast<T>(0)) && (x <= one)` failed. Input is expected to be within the interval [0, 1], but recieved nan.
Error: /paddle/paddle/fluid/operators/bce_loss_op.cu:38 Assertion `(x >= static_cast<T>(0)) && (x <= one)` failed. Input is expected to be within the interval [0, 1], but recieved nan.
Error: /paddle/paddle/fluid/operators/bce_loss_op.cu:38 Assertion `(x >= static_cast<T>(0)) && (x <= one)` failed. Input is expected to be within the interval [0, 1], but recieved nan.
Error: /paddle/paddle/fluid/operators/bce_loss_op.cu:38 Assertion `(x >= static_cast<T>(0)) && (x <= one)` failed. Input is expected to be within the interval [0, 1], but recieved nan.
Error: /paddle/paddle/fluid/operators/bce_loss_op.cu:38 Assertion `(x >= static_cast<T>(0)) && (x <= one)` failed. Input is expected to be within the interval [0, 1], but recieved nan.
Error: /paddle/paddle/fluid/operators/bce_loss_op.cu:38 Assertion `(x >= static_cast<T>(0)) && (x <= one)` failed. Input is expected to be within the interval [0, 1], but recieved nan.
Error: /paddle/paddle/fluid/operators/bce_loss_op.cu:38 Assertion `(x >= static_cast<T>(0)) && (x <= one)` failed. Input is expected to be within the interval [0, 1], but recieved nan.
Error: /paddle/paddle/fluid/operators/bce_loss_op.cu:38 Assertion `(x >= static_cast<T>(0)) && (x <= one)` failed. Input is expected to be within the interval [0, 1], but recieved nan.
Error: /paddle/paddle/fluid/operators/bce_loss_op.cu:38 Assertion `(x >= static_cast<T>(0)) && (x <= one)` failed. Input is expected to be within the interval [0, 1], but recieved nan.
Error: /paddle/paddle/fluid/operators/bce_loss_op.cu:38 Assertion `(x >= static_cast<T>(0)) && (x <= one)` failed. Input is expected to be within the interval [0, 1], but recieved nan.
Error: /paddle/paddle/fluid/operators/bce_loss_op.cu:38 Assertion `(x >= static_cast<T>(0)) && (x <= one)` failed. Input is expected to be within the interval [0, 1], but recieved nan.
Error: /paddle/paddle/fluid/operators/bce_loss_op.cu:38 Assertion `(x >= static_cast<T>(0)) && (x <= one)` failed. Input is expected to be within the interval [0, 1], but recieved nan.
Error: /paddle/paddle/fluid/operators/bce_loss_op.cu:38 Assertion `(x >= static_cast<T>(0)) && (x <= one)` failed. Input is expected to be within the interval [0, 1], but recieved nan.
Error: /paddle/paddle/fluid/operators/bce_loss_op.cu:38 Assertion `(x >= static_cast<T>(0)) && (x <= one)` failed. Input is expected to be within the interval [0, 1], but recieved nan.
Error: /paddle/paddle/fluid/operators/bce_loss_op.cu:38 Assertion `(x >= static_cast<T>(0)) && (x <= one)` failed. Input is expected to be within the interval [0, 1], but recieved nan.
Error: /paddle/paddle/fluid/operators/bce_loss_op.cu:38 Assertion `(x >= static_cast<T>(0)) && (x <= one)` failed. Input is expected to be within the interval [0, 1], but recieved nan.
Error: /paddle/paddle/fluid/operators/bce_loss_op.cu:38 Assertion `(x >= static_cast<T>(0)) && (x <= one)` failed. Input is expected to be within the interval [0, 1], but recieved nan.
Error: /paddle/paddle/fluid/operators/bce_loss_op.cu:38 Assertion `(x >= static_cast<T>(0)) && (x <= one)` failed. Input is expected to be within the interval [0, 1], but recieved nan.
Error: /paddle/paddle/fluid/operators/bce_loss_op.cu:38 Assertion `(x >= static_cast<T>(0)) && (x <= one)` failed. Input is expected to be within the interval [0, 1], but recieved nan.
Error: /paddle/paddle/fluid/operators/bce_loss_op.cu:38 Assertion `(x >= static_cast<T>(0)) && (x <= one)` failed. Input is expected to be within the interval [0, 1], but recieved nan.
Error: /paddle/paddle/fluid/operators/bce_loss_op.cu:38 Assertion `(x >= static_cast<T>(0)) && (x <= one)` failed. Input is expected to be within the interval [0, 1], but recieved nan.
Error: /paddle/paddle/fluid/operators/bce_loss_op.cu:38 Assertion `(x >= static_cast<T>(0)) && (x <= one)` failed. Input is expected to be within the interval [0, 1], but recieved nan.
Error: /paddle/paddle/fluid/operators/bce_loss_op.cu:38 Assertion `(x >= static_cast<T>(0)) && (x <= one)` failed. Input is expected to be within the interval [0, 1], but recieved nan.
Error: /paddle/paddle/fluid/operators/bce_loss_op.cu:38 Assertion `(x >= static_cast<T>(0)) && (x <= one)` failed. Input is expected to be within the interval [0, 1], but recieved nan.
Error: /paddle/paddle/fluid/operators/bce_loss_op.cu:38 Assertion `(x >= static_cast<T>(0)) && (x <= one)` failed. Input is expected to be within the interval [0, 1], but recieved nan.
Error: /paddle/paddle/fluid/operators/bce_loss_op.cu:38 Assertion `(x >= static_cast<T>(0)) && (x <= one)` failed. Input is expected to be within the interval [0, 1], but recieved nan.
Error: /paddle/paddle/fluid/operators/bce_loss_op.cu:38 Assertion `(x >= static_cast<T>(0)) && (x <= one)` failed. Input is expected to be within the interval [0, 1], but recieved nan.
Error: /paddle/paddle/fluid/operators/bce_loss_op.cu:38 Assertion `(x >= static_cast<T>(0)) && (x <= one)` failed. Input is expected to be within the interval [0, 1], but recieved nan.
Error: /paddle/paddle/fluid/operators/bce_loss_op.cu:38 Assertion `(x >= static_cast<T>(0)) && (x <= one)` failed. Input is expected to be within the interval [0, 1], but recieved nan.
Error: /paddle/paddle/fluid/operators/bce_loss_op.cu:38 Assertion `(x >= static_cast<T>(0)) && (x <= one)` failed. Input is expected to be within the interval [0, 1], but recieved nan.
Error: /paddle/paddle/fluid/operators/bce_loss_op.cu:38 Assertion `(x >= static_cast<T>(0)) && (x <= one)` failed. Input is expected to be within the interval [0, 1], but recieved nan.
Error: /paddle/paddle/fluid/operators/bce_loss_op.cu:38 Assertion `(x >= static_cast<T>(0)) && (x <= one)` failed. Input is expected to be within the interval [0, 1], but recieved nan.
Error: /paddle/paddle/fluid/operators/bce_loss_op.cu:38 Assertion `(x >= static_cast<T>(0)) && (x <= one)` failed. Input is expected to be within the interval [0, 1], but recieved nan.
Error: /paddle/paddle/fluid/operators/bce_loss_op.cu:38 Assertion `(x >= static_cast<T>(0)) && (x <= one)` failed. Input is expected to be within the interval [0, 1], but recieved nan.
Error: /paddle/paddle/fluid/operators/bce_loss_op.cu:38 Assertion `(x >= static_cast<T>(0)) && (x <= one)` failed. Input is expected to be within the interval [0, 1], but recieved nan.
Error: /paddle/paddle/fluid/operators/bce_loss_op.cu:38 Assertion `(x >= static_cast<T>(0)) && (x <= one)` failed. Input is expected to be within the interval [0, 1], but recieved nan.
Error: /paddle/paddle/fluid/operators/bce_loss_op.cu:38 Assertion `(x >= static_cast<T>(0)) && (x <= one)` failed. Input is expected to be within the interval [0, 1], but recieved nan.
Error: /paddle/paddle/fluid/operators/bce_loss_op.cu:38 Assertion `(x >= static_cast<T>(0)) && (x <= one)` failed. Input is expected to be within the interval [0, 1], but recieved nan.
Error: /paddle/paddle/fluid/operators/bce_loss_op.cu:38 Assertion `(x >= static_cast<T>(0)) && (x <= one)` failed. Input is expected to be within the interval [0, 1], but recieved nan.
Error: /paddle/paddle/fluid/operators/bce_loss_op.cu:38 Assertion `(x >= static_cast<T>(0)) && (x <= one)` failed. Input is expected to be within the interval [0, 1], but recieved nan.
Error: /paddle/paddle/fluid/operators/bce_loss_op.cu:38 Assertion `(x >= static_cast<T>(0)) && (x <= one)` failed. Input is expected to be within the interval [0, 1], but recieved nan.
Error: /paddle/paddle/fluid/operators/bce_loss_op.cu:38 Assertion `(x >= static_cast<T>(0)) && (x <= one)` failed. Input is expected to be within the interval [0, 1], but recieved nan.
Error: /paddle/paddle/fluid/operators/bce_loss_op.cu:38 Assertion `(x >= static_cast<T>(0)) && (x <= one)` failed. Input is expected to be within the interval [0, 1], but recieved nan.
Error: /paddle/paddle/fluid/operators/bce_loss_op.cu:38 Assertion `(x >= static_cast<T>(0)) && (x <= one)` failed. Input is expected to be within the interval [0, 1], but recieved nan.
Error: /paddle/paddle/fluid/operators/bce_loss_op.cu:38 Assertion `(x >= static_cast<T>(0)) && (x <= one)` failed. Input is expected to be within the interval [0, 1], but recieved nan.
Error: /paddle/paddle/fluid/operators/bce_loss_op.cu:38 Assertion `(x >= static_cast<T>(0)) && (x <= one)` failed. Input is expected to be within the interval [0, 1], but recieved nan.
Error: /paddle/paddle/fluid/operators/bce_loss_op.cu:38 Assertion `(x >= static_cast<T>(0)) && (x <= one)` failed. Input is expected to be within the interval [0, 1], but recieved nan.
Error: /paddle/paddle/fluid/operators/bce_loss_op.cu:38 Assertion `(x >= static_cast<T>(0)) && (x <= one)` failed. Input is expected to be within the interval [0, 1], but recieved nan.
Error: /paddle/paddle/fluid/operators/bce_loss_op.cu:38 Assertion `(x >= static_cast<T>(0)) && (x <= one)` failed. Input is expected to be within the interval [0, 1], but recieved nan.
Error: /paddle/paddle/fluid/operators/bce_loss_op.cu:38 Assertion `(x >= static_cast<T>(0)) && (x <= one)` failed. Input is expected to be within the interval [0, 1], but recieved nan.
Error: /paddle/paddle/fluid/operators/bce_loss_op.cu:38 Assertion `(x >= static_cast<T>(0)) && (x <= one)` failed. Input is expected to be within the interval [0, 1], but recieved nan.
Error: /paddle/paddle/fluid/operators/bce_loss_op.cu:38 Assertion `(x >= static_cast<T>(0)) && (x <= one)` failed. Input is expected to be within the interval [0, 1], but recieved nan.
Error: /paddle/paddle/fluid/operators/bce_loss_op.cu:38 Assertion `(x >= static_cast<T>(0)) && (x <= one)` failed. Input is expected to be within the interval [0, 1], but recieved nan.
2021-08-29 10:01:15 | INFO     | yolox.core.trainer:160 - Training of experiment is done and the best AP is 0.00
2021-08-29 10:01:15 | ERROR    | __main__:80 - An error has been caught in function '<module>', process 'MainProcess' (2251), thread 'MainThread' (139919071340288):
Traceback (most recent call last):

> File "tools/train.py", line 80, in <module>
    main()
    └ <function main at 0x7f410094d2f0>

  File "tools/train.py", line 76, in main
    trainer.train()
    │       └ <function Trainer.train at 0x7f4100a11268>
    └ <yolox.core.trainer.Trainer object at 0x7f4116bb8da0>

  File "/root/paddlejob/workspace/code/yolox/core/trainer.py", line 57, in train
    self.train_in_epoch()
    │    └ <function Trainer.train_in_epoch at 0x7f4100a111e0>
    └ <yolox.core.trainer.Trainer object at 0x7f4116bb8da0>

  File "/root/paddlejob/workspace/code/yolox/core/trainer.py", line 66, in train_in_epoch
    self.train_in_iter()
    │    └ <function Trainer.train_in_iter at 0x7f4100a110d0>
    └ <yolox.core.trainer.Trainer object at 0x7f4116bb8da0>

  File "/root/paddlejob/workspace/code/yolox/core/trainer.py", line 72, in train_in_iter
    self.train_one_iter(data)
    │    │              └ <unprintable list object>
    │    └ <function Trainer.train_one_iter at 0x7f4100964268>
    └ <yolox.core.trainer.Trainer object at 0x7f4116bb8da0>

  File "/root/paddlejob/workspace/code/yolox/core/trainer.py", line 85, in train_one_iter
    outputs = self.model(inps, targets)
              │    │     │     └ <unprintable Tensor object>
              │    │     └ <unprintable Tensor object>
              │    └ DataParallel(
              │        (_layers): YOLOX(
              │          (backbone): YOLOPAFPN(
              │            (backbone): CSPDarknet(
              │              (stem): Focus(
              │                (...
              └ <yolox.core.trainer.Trainer object at 0x7f4116bb8da0>

  File "/opt/_internal/cpython-3.7.0/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 902, in __call__
    outputs = self.forward(*inputs, **kwargs)
              │    │        │         └ {}
              │    │        └ <unprintable tuple object>
              │    └ <function DataParallel.forward at 0x7f4115101840>
              └ DataParallel(
                  (_layers): YOLOX(
                    (backbone): YOLOPAFPN(
                      (backbone): CSPDarknet(
                        (stem): Focus(
                          (...
  File "/opt/_internal/cpython-3.7.0/lib/python3.7/site-packages/paddle/fluid/dygraph/parallel.py", line 578, in forward
    outputs = self._layers(*inputs, **kwargs)
              │             │         └ {}
              │             └ <unprintable tuple object>
              └ DataParallel(
                  (_layers): YOLOX(
                    (backbone): YOLOPAFPN(
                      (backbone): CSPDarknet(
                        (stem): Focus(
                          (...
  File "/opt/_internal/cpython-3.7.0/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 902, in __call__
    outputs = self.forward(*inputs, **kwargs)
              │    │        │         └ {}
              │    │        └ <unprintable tuple object>
              │    └ <function YOLOX.forward at 0x7f4116b8ca60>
              └ YOLOX(
                  (backbone): YOLOPAFPN(
                    (backbone): CSPDarknet(
                      (stem): Focus(
                        (conv): BaseConv(
                          (conv): ...

  File "/root/paddlejob/workspace/code/yolox/models/yolox.py", line 35, in forward
    fpn_outs, targets, x
    │         │        └ <unprintable Tensor object>
    │         └ <unprintable Tensor object>
    └ <unprintable tuple object>

  File "/opt/_internal/cpython-3.7.0/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 902, in __call__
    outputs = self.forward(*inputs, **kwargs)
              │    │        │         └ {}
              │    │        └ <unprintable tuple object>
              │    └ <function YOLOXHead.forward at 0x7f4116b8c1e0>
              └ YOLOXHead(
                  (cls_convs): ModuleList(
                    (0): Sequential(
                      (0): BaseConv(
                        (conv): Conv2D(320, 320, kernel_size=...

  File "/root/paddlejob/workspace/code/yolox/models/yolo_head.py", line 229, in forward
    dtype=xin[0].dtype,
          └ <unprintable tuple object>

  File "/root/paddlejob/workspace/code/yolox/models/yolo_head.py", line 354, in get_losses
    imgs,
    └ <unprintable Tensor object>

  File "<decorator-gen-269>", line 2, in get_assignments
  File "/opt/_internal/cpython-3.7.0/lib/python3.7/site-packages/paddle/fluid/dygraph/base.py", line 331, in _decorate_function
    return func(*args, **kwargs)
           │     │       └ {}
           │     └ <unprintable tuple object>
           └ <function YOLOXHead.get_assignments at 0x7f4116b8c488>

  File "/root/paddlejob/workspace/code/yolox/models/yolo_head.py", line 483, in get_assignments
    + 100000.0 * (paddle.cast(paddle.logical_not(is_in_boxes_and_center), paddle.float32))
                  │      │    │      │           │                        │      └ paddle.float32
                  │      │    │      │           │                        └ <module 'paddle' from '/opt/_internal/cpython-3.7.0/lib/python3.7/site-packages/paddle/__init__.py'>
                  │      │    │      │           └ <unprintable Tensor object>
                  │      │    │      └ <function logical_not at 0x7f4115152950>
                  │      │    └ <module 'paddle' from '/opt/_internal/cpython-3.7.0/lib/python3.7/site-packages/paddle/__init__.py'>
                  │      └ <function cast at 0x7f4115148598>
                  └ <module 'paddle' from '/opt/_internal/cpython-3.7.0/lib/python3.7/site-packages/paddle/__init__.py'>

  File "/opt/_internal/cpython-3.7.0/lib/python3.7/site-packages/paddle/fluid/layers/nn.py", line 12290, in logical_not
    op_name="logical_not", x=x, y=None, name=name, out=out, binary_op=False)
                             │               │         └ None
                             │               └ None
                             └ <unprintable Tensor object>
  File "/opt/_internal/cpython-3.7.0/lib/python3.7/site-packages/paddle/fluid/layers/nn.py", line 12120, in _logical_op
    return op(x)
           │  └ <unprintable Tensor object>
           └ <built-in method logical_not of PyCapsule object at 0x7f4161365390>

SystemError: (Fatal) Operator logical_not raises an thrust::system::system_error exception.
The exception content is
:transform: failed to synchronize: cudaErrorLaunchFailure: unspecified launch failure. (at /paddle/paddle/fluid/imperative/tracer.cc:192)

--------------------------------------
C++ Traceback (most recent call last):
INFO 2021-08-29 10:01:35,007 launch_utils.py:327] terminate all the procs
ERROR 2021-08-29 10:01:35,008 launch_utils.py:584] ABORT!!! Out of all 4 trainers, the trainer process with rank=[0] was aborted. Please check its log.
INFO 2021-08-29 10:01:38,011 launch_utils.py:327] terminate all the procs
--------------------------------------
0   paddle::memory::allocation::CUDADeviceContextAllocatorPool::~CUDADeviceContextAllocatorPool()
1   std::_Sp_counted_ptr<paddle::memory::allocation::CUDADeviceContextAllocator*, (__gnu_cxx::_Lock_policy)2>::_M_dispose()
2   paddle::memory::allocation::CUDADeviceContextAllocator::~CUDADeviceContextAllocator()
3   paddle::platform::build_nvidia_error_msg[abi:cxx11](cudaError)
4   paddle::platform::proto::cudaerrorDesc::ByteSizeLong() const
5   paddle::platform::proto::AllMessageDesc::ByteSizeLong() const
6   paddle::platform::proto::MessageDesc::ByteSizeLong() const
7   paddle::framework::SignalHandle(char const*, int)
8   paddle::platform::GetCurrentTraceBackString[abi:cxx11]()

----------------------
Error Message Summary:
----------------------
FatalError: `Segmentation fault` is detected by the operating system.
  [TimeInfo: *** Aborted at 1630202490 (unix time) try "date -d @1630202490" if you are using GNU date ***]
  [SignalInfo: *** SIGSEGV (@0x8) received by PID 2251 (TID 0x7f41728b6700) from PID 8 ***]

/mnt
[INFO]: train job failed! train_ret: 1

**Comment by thunder95** [comment]
相似问题， 只有等百度专家来看看了 @jerrywgz @yinhaofeng

**Comment by MissPenguin** [comment]
请问这个问题稳定复现吗，可以把报错时logical_not的输入打印出来看下吗

**Comment by jesse01** [comment]
应该是bce_loss_op报错的原因，出错提示位置误导，这个issue不用管了

**Comment by lx-cly** [comment]
@jesse01 我想问一下，yolox 训练coco数据集要花18天吗？

**Comment by mikeswf** [comment]
> 应该是bce_loss_op报错的原因，出错提示位置误导，这个issue不用管了

你好，请教一下，所以这个是怎么解决的？
