### ISSUE TITLE
[论文复现]索引切片只支持第0维问题

### ISSUE THREAD

**Issue by jesse01** [PaddlePaddle/Paddle#35243]
1）PaddlePaddle版本：2.1.2及开发版本
2）GPU：任意版本
4）系统环境：任意环境

训练信息
1）无论单机、多机
2）显存多少无关
复现信息：100%复现
问题描述：索引切片只支持第0维问题
见下图：
![image](https://user-images.githubusercontent.com/6436061/131238858-21442a21-6864-4bfe-9d65-c29ddffa2bb2.png)
![image](https://user-images.githubusercontent.com/6436061/131238875-c9797d46-82eb-4d78-9830-8004687ba6cb.png)

**Comment by MissPenguin** [comment]
您好，这个报错信息写的比较清楚了哈，这种用法就是错误的，你的idx是个tensor，那么只能传这一个参数，要么就直接用普通数值进行索引

**Comment by jesse01** [comment]
这种用法为什么是错误的，请看numpy的操作，这种处理在目标检测里很常用啊
![image](https://user-images.githubusercontent.com/6436061/131772756-c5f1cb70-89be-4e47-9d41-6ec720134839.png)
