### ISSUE TITLE
PaddlePaddle2.1训练好的模型，转静态图后在PaddlePaddle1.8推理报：Error: Operator flatten_contiguous_range has not been registered

### ISSUE THREAD

**Issue by OrangeAILab** [PaddlePaddle/Paddle#35253]
- 版本、环境信息：
    1）PaddlePaddle版本：PaddlePaddle1.8.5
    2）CPU：请提供CPU型号，MKL/OpenBlas/MKLDNN/等数学库的使用情况
    3）GPU：请提供GPU型号: 八卡P40，CUDA 10.0和CUDNN 7.6
    4）系统环境：linux centos，Python版本
   File "/home/heyue05/anaconda3/envs/PaddlePaddle1.8/lib/python3.6/site-packages/paddle/fluid/executor.py", line 1071, in run
    six.reraise(*sys.exc_info())
  File "/home/heyue05/anaconda3/envs/PaddlePaddle1.8/lib/python3.6/site-packages/six.py", line 719, in reraise
    raise value
  File "/home/heyue05/anaconda3/envs/PaddlePaddle1.8/lib/python3.6/site-packages/paddle/fluid/executor.py", line 1066, in run
    return_merged=return_merged)
  File "/home/heyue05/anaconda3/envs/PaddlePaddle1.8/lib/python3.6/site-packages/paddle/fluid/executor.py", line 1154, in _run_impl
    use_program_cache=use_program_cache)
  File "/home/heyue05/anaconda3/envs/PaddlePaddle1.8/lib/python3.6/site-packages/paddle/fluid/executor.py", line 1229, in _run_program
    fetch_var_name)
paddle.fluid.core_avx.EnforceNotMet: 

--------------------------------------------
C++ Call Stacks (More useful to developers):
--------------------------------------------
0   std::string paddle::platform::GetTraceBackString<std::string const&>(std::string const&, char const*, int)
1   paddle::platform::EnforceNotMet::EnforceNotMet(std::string const&, char const*, int)
2   paddle::framework::OpRegistry::CreateOp(std::string const&, std::map<std::string, std::vector<std::string, std::allocator<std::string> >, std::less<std::string>, std::allocator<std::pair<std::string const, std::vector<std::string, std::allocator<std::string> > > > > const&, std::map<std::string, std::vector<std::string, std::allocator<std::string> >, std::less<std::string>, std::allocator<std::pair<std::string const, std::vector<std::string, std::allocator<std::string> > > > > const&, paddle::framework::AttributeMap, bool)
3   paddle::framework::OpRegistry::CreateOp(paddle::framework::OpDesc const&)
4   paddle::framework::Executor::Prepare(paddle::framework::ProgramDesc const&, int, std::vector<std::string, std::allocator<std::string> > const&, bool)
5   paddle::framework::Executor::Run(paddle::framework::ProgramDesc const&, paddle::framework::Scope*, int, bool, bool, std::vector<std::string, std::allocator<std::string> > const&, bool, bool)

----------------------
Error Message Summary:
----------------------
Error: Operator flatten_contiguous_range has not been registered
  [Hint: op_info_ptr should not be null.] at (/paddle/paddle/fluid/framework/op_info.h:140)

**Comment by tink2123** [comment]
这个kernel是在Paddle2.1之后才注册的，1.8的时候没有这个kernel。
高版本Paddle训练好的模型不建议在低版本Paddle上预测。

**Comment by OrangeAILab** [comment]
非常感谢~  我这边是2.1版本的模型转静态图，以前的推理代码库版本是1.8的，想把2.1的模型部署有没有好的解决方案呢

**Comment by tink2123** [comment]
建议升级一下推理库，和Paddle版本保持一致。
