### ISSUE TITLE
make -j$(nproc) 卡在了[100%] Built target paddle_python后面

### ISSUE THREAD

**Issue by XYZ-916** [PaddlePaddle/Paddle#35269]
cmake .. -DPY_VERSION=3.8 -DWITH_GPU=OFF -DWITH_TESTING=ON -DCMAKE_BUILD_TYPE=Develop -WITH_DISTRIBUTE=ON
make -j$(nproc)
卡在了“Built target paddle_python”后面，许久没有log输出。

**Comment by tink2123** [comment]
多用几个核来编译试试呢？

**Comment by XYZ-916** [comment]
make -j$(nproc) 是不是最大化利用？

**Comment by tink2123** [comment]
是的，这样是用了全部的核来编译。卡了多久呢，退出重新编译一次试下？

**Comment by XYZ-916** [comment]
卡了半个多小时了，重试了一次还是卡在了同样的地方。

**Comment by tink2123** [comment]
-DWITH_TESTING=OFF 
 -DCMAKE_BUILD_TYPE=Release 

试下修改这两个值呢？

**Comment by XYZ-916** [comment]
我需要做TESTING,代码分支是Develop，不能改吧。

**Comment by tink2123** [comment]
-DCMAKE_BUILD_TYPE=Release
这个与代码分支无关，只有 Release 和 Debug 两个选项，没有Develop这个选项的。需要Testing的话，就只改下build_type试试吧.

另外你是在什么系统上编译的呢？

**Comment by XYZ-916** [comment]
![QQ20210830-174027](https://user-images.githubusercontent.com/14884056/131320196-86bf0077-e5f5-47ff-ade7-d1b9c32e2126.png)
Linux系统编译。

**Comment by tianshuo78520a** [comment]
应该是在打whl包，看下是否有足够空间？

**Comment by tianshuo78520a** [comment]
或者可以试试改成-DCMAKE_BUILD_TYPE=Release

**Comment by XYZ-916** [comment]
-DCMAKE_BUILD_TYPE=Release，已解决，谢谢。
