### ISSUE TITLE
请问一下，paddle有清理显存的api吗？

### ISSUE THREAD

**Issue by w5688414** [PaddlePaddle/Paddle#35266]
为使您的问题得到快速解决，在建立Issues前，请您先通过如下方式搜索是否有相似问题:【搜索issue关键字】【使用labels筛选】【官方文档】

如果您没有查询到相似问题，为快速解决您的提问，建立issue时请提供如下细节信息：
- 标题：简洁、精准概括您的问题
- 版本、环境信息：
    1）PaddlePaddle版本：paddlepaddle2.1
    2）CPU/GPU：v100
    3）系统环境：linux，aistudio环境
    4）Python版本号 python3.7
    5）显存信息
 注：您可以通过执行[summary_env.py](https://github.com/PaddlePaddle/Paddle/blob/develop/tools/summary_env.py)获取以上信息。
- 复现信息：如为报错，请给出复现环境、复现步骤
- 问题描述：请详细描述您的问题，同步贴出报错信息、日志/代码关键片段

Thank you for contributing to PaddlePaddle.
Before submitting the issue, you could search issue in the github in case that there was a similar issue submitted or resolved before.
If there is no solution,please provide us with the following details :
**System information**
-PaddlePaddle version （eg.1.1）or CommitID
-CPU: including CPUMKL/OpenBlas/MKLDNN version
-GPU: including CUDA/cuDNN version
-OS Platform and Distribution(eg.Mac OS 10.14)
-Python version 
Note: You can get most of the information by running [summary_env.py](https://github.com/PaddlePaddle/Paddle/blob/develop/tools/summary_env.py). 
**To Reproduce**
Steps to reproduce the behavior
**Describe your current behavior**
**Code to reproduce the issue**
**Other info / logs**
paddle有类似torch的torch.cuda.empty_cache() 的api吗？最近使用aistudio模型，跑模型显存占用很大，想清理一下显存，发现没有找到相应的api，请问怎么解决？

**Comment by tink2123** [comment]
暂时没有这个api
训练之前可以尝试设置环境变量：
```
export FLAGS_fraction_of_gpu_memory_to_use=0.1
export FLAGS_allocator_strategy=auto_growth
```
让显存按需增长试试
