### ISSUE TITLE
训练问题

### ISSUE THREAD

**Issue by ziyaxuanyi** [PaddlePaddle/Paddle#35319]
使用rtx3090显卡训练一直没问题。但手动停止训练后，测试模型效果，然后继续训练会报错

cuda error(2).out of memory.
[Advise:The API call failed because it was unable to allocate enough memory to perform the requested operation.](at /paddle/paddle/fluid/platform/stream/cuda_stream.cc:49)
[operator <gaussian_random> error]

检查过GPU没有任何其他进程在运行，内存充足。好像就是这个显卡上有其他进程占用显存，但nvidia-smi就是看不到任何进程在上面，显卡内存使用率一直为0，很奇怪。

换用其他同样规格的rtx3090显卡，训练正常，代码没有任何改动，都在同一个机器上的同一个docker容器内，环境都一致。

paddle使用的是2.1版本，测试模型的时候使用了tensorRT推理,cuda出现错误，手动非正常关闭了测试程序之后，就出现了上述错误。

查阅资料，唯一可参考的就是pytorch出现这种相同情况下，在dataloder里设置pin_memory=False可避免。和锁页内存有关。

请问paddle这种情况该怎么处理？

**Comment by ZHUI** [comment]
如果是 linux 系统的话，可以 `fuser -v /dev/nvidia*` 查看占用设备进程。 `fuser -kv /dev/nvidia*` 可以全部kill掉。

**Comment by ynxu15** [comment]
可以试一下下面的方法

在程序运行的前面添加如下代码

os.environ[‘FLAGS_eager_delete_tensor_gb’] = “0.0”

主要作用是 GPU memory garbage collection optimization flags
