### ISSUE TITLE
connection refused by pserver, maybe pserver failed!

### ISSUE THREAD

**Issue by JayEworld** [PaddlePaddle/Paddle#3532]
Wed Aug 16 18:23:10 2017[1,90]<stderr>:+ python27-gcc482/bin/python conf/trainer_config.conf
Wed Aug 16 18:24:36 2017[1,90]<stderr>:F0816 18:24:36.837287 30629 LightNetwork.cpp:395] connection refused by pserver, maybe pserver failed!
Wed Aug 16 18:24:36 2017[1,90]<stderr>:*** Check failure stack trace: ***
Wed Aug 16 18:24:36 2017[1,90]<stderr>:    @     0x7f130b15527d  google::LogMessage::Fail()
Wed Aug 16 18:24:36 2017[1,90]<stderr>:    @     0x7f130b158d2c  google::LogMessage::SendToLog()
Wed Aug 16 18:24:36 2017[1,90]<stderr>:    @     0x7f130b154da3  google::LogMessage::Flush()
Wed Aug 16 18:24:36 2017[1,90]<stderr>:    @     0x7f130b15a23e  google::LogMessageFatal::~LogMessageFatal()
Wed Aug 16 18:24:36 2017[1,90]<stderr>:    @     0x7f130afb23c1  paddle::SocketClient::TcpClient()
Wed Aug 16 18:24:36 2017[1,90]<stderr>:    @     0x7f130afb25a1  paddle::SocketClient::SocketClient()
Wed Aug 16 18:24:36 2017[1,90]<stderr>:    @     0x7f130bc359b0  paddle::ParameterClient2::init()
Wed Aug 16 18:24:36 2017[1,90]<stderr>:    @     0x7f130b7c209d  paddle::RemoteParameterUpdater::init()
Wed Aug 16 18:24:36 2017[1,90]<stderr>:    @     0x7f130b1351ea  ParameterUpdater::init()
Wed Aug 16 18:24:36 2017[1,90]<stderr>:    @     0x7f130addef7b  _wrap_ParameterUpdater_init
Wed Aug 16 18:24:36 2017[1,90]<stderr>:    @           0x4b4cb9  PyEval_EvalFrameEx
Wed Aug 16 18:24:36 2017[1,90]<stderr>:    @           0x4b6b28  PyEval_EvalCodeEx
Wed Aug 16 18:24:36 2017[1,90]<stderr>:    @           0x4b5d10  PyEval_EvalFrameEx
Wed Aug 16 18:24:36 2017[1,90]<stderr>:    @           0x4b6b28  PyEval_EvalCodeEx
Wed Aug 16 18:24:36 2017[1,90]<stderr>:    @           0x4b5d10  PyEval_EvalFrameEx
Wed Aug 16 18:24:36 2017[1,90]<stderr>:    @           0x4b6b28  PyEval_EvalCodeEx
Wed Aug 16 18:24:36 2017[1,90]<stderr>:    @           0x4b5d10  PyEval_EvalFrameEx
Wed Aug 16 18:24:36 2017[1,90]<stderr>:    @           0x4b6b28  PyEval_EvalCodeEx
Wed Aug 16 18:24:36 2017[1,90]<stderr>:    @           0x4b6c52  PyEval_EvalCode
Wed Aug 16 18:24:36 2017[1,90]<stderr>:    @           0x4e1c7d  PyRun_FileExFlags
Wed Aug 16 18:24:36 2017[1,90]<stderr>:    @           0x4e3501  PyRun_SimpleFileExFlags
Wed Aug 16 18:24:36 2017[1,90]<stderr>:    @           0x4159dd  Py_Main
Wed Aug 16 18:24:36 2017[1,90]<stderr>:    @     0x7f1310c53bd5  __libc_start_main
Wed Aug 16 18:24:36 2017[1,90]<stderr>:    @           0x414b71  (unknown)
Wed Aug 16 18:24:36 2017[1,90]<stderr>:    @              (nil)  (unknown)
Wed Aug 16 18:24:38 2017[1,90]<stderr>:./train.sh: line 239: 30629 Aborted                 python27-gcc482/bin/python conf/trainer_config.conf
Wed Aug 16 18:24:38 2017[1,90]<stderr>:+ '[' 134 -ne 0 ']'
Wed Aug 16 18:24:38 2017[1,90]<stderr>:+ kill_pserver2_exit
Wed Aug 16 18:24:38 2017[1,90]<stderr>:+ ps aux
Wed Aug 16 18:24:38 2017[1,90]<stderr>:+ grep paddle_pserver2
Wed Aug 16 18:24:38 2017[1,90]<stderr>:+ grep paddle_cluster_job
Wed Aug 16 18:24:38 2017[1,90]<stderr>:+ grep -v grep
Wed Aug 16 18:24:38 2017[1,90]<stderr>:+ cut -c10-14
Wed Aug 16 18:24:38 2017[1,90]<stderr>:+ xargs kill -9
Wed Aug 16 18:24:38 2017[1,90]<stderr>:usage: kill [ -s signal | -p ] [ -a ] pid ...
Wed Aug 16 18:24:38 2017[1,90]<stderr>:       kill -l [ signal ]
Wed Aug 16 18:24:38 2017[1,90]<stderr>:+ log_fatal 'paddle_trainer failed kill paddle_pserver2 and exit'
Wed Aug 16 18:24:38 2017[1,90]<stderr>:+ echo '[./common.sh : 399] [kill_pserver2_exit]'
Wed Aug 16 18:24:38 2017[1,90]<stderr>:[./common.sh : 399] [kill_pserver2_exit]
Wed Aug 16 18:24:38 2017[1,90]<stderr>:+ echo '[FATAL]: paddle_trainer failed kill paddle_pserver2 and exit'
Wed Aug 16 18:24:38 2017[1,90]<stderr>:[FATAL]: paddle_trainer failed kill paddle_pserver2 and exit
Wed Aug 16 18:24:38 2017[1,90]<stderr>:+ get_stack
Wed Aug 16 18:24:38 2017[1,90]<stderr>:+ set +x
Wed Aug 16 18:24:38 2017[1,90]<stderr>:
Wed Aug 16 18:24:38 2017[1,90]<stderr>:*********************Shell Script Stack Trace********************
Wed Aug 16 18:24:38 2017[1,90]<stderr>: @: [./log.sh: 41] log_fatal
Wed Aug 16 18:24:38 2017[1,90]<stderr>: @: [./common.sh: 399] kill_pserver2_exit
Wed Aug 16 18:24:38 2017[1,90]<stderr>: @: [./train.sh: 242] main
Wed Aug 16 18:24:38 2017[1,90]<stderr>:
Wed Aug 16 18:24:38 2017[1,90]<stderr>:+ exit 1

**Comment by hedaoyuan** [comment]
`connection refused by pserver, maybe pserver failed!` 查看paddle_pserver2.INFO，可以排查是哪个节点挂了。

**Comment by JayEworld** [comment]
感谢，已经解决，原因是0节点要启动的线程太多，超过了集群的限制，修改集群限制ulimit，问题得到解决

**Comment by typhoonzero** [comment]
补充0号节点报错的日志
```
Wed Aug 16 19:39:03 2017[1,0]<stderr>:+ python27-gcc482/bin/python conf/trainer_config.conf
Wed Aug 16 19:40:35 2017[1,0]<stderr>:terminate called without an active exception
Wed Aug 16 19:40:35 2017[1,0]<stderr>:*** Aborted at 1502883635 (unix time) try "date -d @1502883635" if you are using GNU date ***
Wed Aug 16 19:40:35 2017[1,0]<stderr>:PC: @                0x0 (unknown)
Wed Aug 16 19:40:35 2017[1,0]<stderr>:*** SIGABRT (@0x1f800002f69) received by PID 12137 (TID 0x7f086af77700) from PID 12137; stack trace: ***
Wed Aug 16 19:40:35 2017[1,0]<stderr>:    @     0x7f11231a3160 (unknown)
Wed Aug 16 19:40:35 2017[1,0]<stderr>:    @     0x7f11227113f7 __GI_raise
Wed Aug 16 19:40:35 2017[1,0]<stderr>:    @     0x7f11227127d8 __GI_abort
Wed Aug 16 19:40:35 2017[1,0]<stderr>:    @     0x7f111bb64c65 __gnu_cxx::__verbose_terminate_handler()
Wed Aug 16 19:40:35 2017[1,0]<stderr>:    @     0x7f111bb62e06 __cxxabiv1::__terminate()
Wed Aug 16 19:40:35 2017[1,0]<stderr>:    @     0x7f111bb62e33 std::terminate()
Wed Aug 16 19:40:35 2017[1,0]<stderr>:    @     0x7f111ca09f15 std::vector<>::~vector()
Wed Aug 16 19:40:35 2017[1,0]<stderr>:    @     0x7f111d6dedf2 paddle::ParameterClient2::initThreads()
Wed Aug 16 19:40:35 2017[1,0]<stderr>:    @     0x7f111d6dfa5f paddle::ParameterClient2::init()
Wed Aug 16 19:40:35 2017[1,0]<stderr>:    @     0x7f111d26c3d3 paddle::RemoteParameterUpdater::controller()
Wed Aug 16 19:40:35 2017[1,0]<stderr>:    @     0x7f111bbb58a0 execute_native_thread_routine
Wed Aug 16 19:40:35 2017[1,0]<stderr>:    @     0x7f112319b1c3 start_thread
Wed Aug 16 19:40:35 2017[1,0]<stderr>:    @     0x7f11227c312d __clone
Wed Aug 16 19:40:35 2017[1,0]<stderr>:    @                0x0 (unknown)
```

**Comment by luotao1** [comment]
补充说明：
- 可以减少trainer_count个数和pserver个数，从而减少每个节点上paddle程序用到的线程数。
- `ulimit -a`不需要root权限，只要能访问就行了，可咨询对应集群的OP。

**Comment by yinyunfeng** [comment]
想问一下ulimit表示什么，在哪修改，应该不是paddle命令行参数

**Comment by shenchong721** [comment]
@JayEworld @yinyunfeng ,请问一下ulimit怎么设置？
