### ISSUE TITLE
NEXTVLAD.pdopt not exits

### ISSUE THREAD

**Issue by yuxulingche** [PaddlePaddle/Paddle#35325]
I am finetune the nextvlad on my dataset, but occur error: AssertionError: Optimizer file [./nextvlad/model_weights/NEXTVLAD.pdopt] not exits！need to help!

**Comment by yuxulingche** [comment]
能下载的预训练模型只有NEXTVLAD.pdparams，为什么还要加载一个NEXTVLAD.pdopt

**Comment by ZHUI** [comment]
> 能下载的预训练模型只有NEXTVLAD.pdparams，为什么还要加载一个NEXTVLAD.pdopt

方便的话，可以贴一下你 load的代码。.pdopt 是存储optimizer的一些动量之类的变量，.pdparams 是参数变量。

**Comment by yuxulingche** [comment]
感谢回复，load代码如下：
fluid.load(train_prog, model_path=args.resume, executor=exe)

版本是2.1.2，调用到的是io.py中的load(program, model_path, executor=None, var_list=None)方法，报错的是2081行

**Comment by ZHUI** [comment]
此处指定model_path，可以单独加载NEXTVLAD.pdparams

`model_path=./nextvlad/model_weights/NEXTVLAD.pdparams`

如果不指定文件名后缀，会尝试加载`.pdparams, pdopt `
