### ISSUE TITLE
paddle v2 infer 接口调用出错

### ISSUE THREAD

**Issue by xinrenax** [PaddlePaddle/Paddle#3533]
调用方式
probs = paddle.infer(
                output_layer=predict,
                parameters=parameters,
                input=test_data,
                feeding=FIELDS_ID)
报错
ClassRegistrar.h:65] Check failed: mapGet(type, creatorMap_, &creator) Unknown class type: data
*** Check failure stack trace: ***

**Comment by xinrenax** [comment]
已解决，机器上没有GPU，需要加上paddle.init(use_gpu=False, trainer_count=1)

**Comment by zhangweijiqn** [comment]
是GPU的问题，初始化的时候添加如下代码可解：
`char* argv[] = {"--use_gpu=False"};
paddle_init(0, (char**)argv);`
