### ISSUE TITLE
vs2019 编译2.1.2 release版，出现错误 C2672“elementwise_add_to”: 未找到匹配的重载函数

### ISSUE THREAD

**Issue by jurafish** [PaddlePaddle/Paddle#35333]
错误	C2672	“elementwise_add_to”: 未找到匹配的重载函数	selected_rows_functor	I:\Paddle-2.1.2\paddle\fluid\operators\math\selected_rows_functor.cc	428	
错误	C2893	未能使函数模板“std::enable_if<std::is_floating_point<_Ty>::value,void>::type paddle::operators::math::scatter::elementwise_add_to(paddle::operators::math::BlasT<paddle::platform::CPUDeviceContext,T> *,size_t,const T *,T *)”专用化	selected_rows_functor	I:\Paddle-2.1.2\paddle\fluid\operators\math\selected_rows_functor.cc	431

**Comment by zhwesky2010** [comment]
@jurafish 你好，目前还只支持了VS2017的编译，VS2019可能有bug。我们后面会进行修复。

**Comment by jurafish** [comment]
知道问题原因了

**Comment by CnybTseng** [comment]
> 知道问题原因了

请问您是怎么解决的？我遇到了同样的问题。

**Comment by betterpig** [comment]
- 您好，该问题出现的原因为：在实例化类模板 
`template struct MergeAdd<platform::CPUDeviceContext, paddle::platform::bfloat16>;`
时，std::is_floating_point<T>::value不支持bfloat16类型，因而找不到匹配的重载函数。
目前paddle只支持VS2017的编译，VS2019的支持仍在开发中。

- 临时做法为：将Paddle\paddle\fluid\operators\math\selected_rows_functor.cc中第300行的
`typename std::enable_if<std::is_floating_point<T>::value>::type`
替换为
`typename std::enable_if<!std::is_integral<T>::value>::type`

**Comment by betterpig** [comment]
> @jurafish 你好，目前还只支持了VS2017的编译，VS2019可能有bug。我们后面会进行修复。

已经针对paddle使用VS2019编译时存在的问题进行了修复，目前paddle的最新develop分支已经支持VS2019编译。
