### ISSUE TITLE
官网paddleX的文档及代码,运行时报错!

### ISSUE THREAD

**Issue by wuxiaodong1014** [PaddlePaddle/Paddle#35344]
您好! 

我在运行官网上paddleX的代码时报错,

代码网址https://www.paddlepaddle.org.cn/tutorials/projectdetail/1991056

我把环境的版本换成 paddle2.0 或者paddle2.1 也还是报错的;

但是,在大约两周前,我在paddle2.1上运行这些paddleX的代码,是正常的;

是不是这几天 paddleX做了升级? 

因为,现在,我在paddle2.1环境下,用这个安装命令pip install paddlex==1.3.11  ,再运行官网上的代码,就不报错了.

**Comment by FlyingQianMM** [comment]
你好，这个教程需要使用paddlex==1.3.11才能正常运行。paddlex升级了2.0.0动态图版本，pip install paddlex会默认安装2.0.0版本的。我们会尽快修复该教程文档，在安装时指定版本号为1.3.11。

可至PaddleX github repo https://github.com/PaddlePaddle/PaddleX 查阅2.0版本的tutorials，API文档，和案例介绍等内容。
