### ISSUE TITLE
How to serve the trained model 

### ISSUE THREAD

**Issue by lightsailpro** [PaddlePaddle/Paddle#3535]
Does paddle provide model serving framework similar to tensorflow serving? I could not find any serving related in the document. Ideally a generic REST API interface will be great.

**Comment by pkuyym** [comment]
You can use third party tools to wrap such a interface like ```flask```.

**Comment by lightsailpro** [comment]
Could someone share some sample python code for serving Paddle model using flask or falcon?

**Comment by wanghaoshuang** [comment]
close this issue due to inactivity.
