### ISSUE TITLE
不同类型的tensor数值计算之后类型不符合编程常识

### ISSUE THREAD

**Issue by HuangLK** [PaddlePaddle/Paddle#35362]
欢迎您对PaddlePaddle提出建议，非常感谢您对PaddlePaddle的贡献！
在留下您的建议时，辛苦您同步提供如下信息：
- 版本、环境信息
1）PaddlePaddle版本：2.1
2）CPU/GPU：CPU
3）系统环境：任意

问题：不同类型的tensor数值计算之后类型不符合编程常识。
![image](https://user-images.githubusercontent.com/3390197/131647257-26312e37-de7b-4893-aee6-b51d75fbc36c.png)

对比Pytorch的结果：
![image](https://user-images.githubusercontent.com/3390197/131646634-fec558e3-5cee-4408-bc36-ff6b1f542589.png)

**Comment by chenwhql** [comment]
感谢反馈，这个属于运算的类型提升问题，是paddle预期内的问题，paddle现在不支持类型提升，且短期内也没有计划去支持

由于历史原因，这里的策略是向左操作数对齐，实际上应该是直接报错，如果你用API的话会报错的，考虑到改变这个行为可能会造成不兼容问题，所以这里暂时不能改动，为了让用户能够感知到这一点，我们暂时加了警告提示

类型提升padle也可以支持，之前也开发过类似的功能，但决策上没有合入，可以参考 https://github.com/PaddlePaddle/Paddle/pull/29265

之前决策的理由如下，供参考

![image](https://user-images.githubusercontent.com/22561442/131802078-4818e347-3191-47cf-8084-8a40b9c37dac.png)
