### ISSUE TITLE
[论文复现]权重tensor直接运算赋值无效

### ISSUE THREAD

**Issue by jesse01** [PaddlePaddle/Paddle#35384]
- 版本、环境信息：
    1）PaddlePaddle版本：2.1.2
    2）CPU：任意
    3）GPU：任意
    4）系统环境：任意
- 复现信息：100%重现
- 问题描述：使用ema方法训练模型时，直接对权重tensor运算赋值后，权重tensor的内容不变。
方法如下：
![image](https://user-images.githubusercontent.com/6436061/131773866-5e91597f-dc41-46ca-81ae-395deae66fe6.png)

改成如下方法，则可以赋值成功：
![image](https://user-images.githubusercontent.com/6436061/131774521-818f62ae-2c67-411a-ac60-c35e485c68fd.png)

建议：
作为BUG进行修复 或者 不允许对权重tensor进行运算赋值（抛异常）

**Comment by jesse01** [comment]
第二张图截错了，更正：
![image](https://user-images.githubusercontent.com/6436061/131774812-7690e150-2f94-420d-8aa4-9f81ad7c8bc5.png)

**Comment by wawltor** [comment]
这个是paddle的tensor的操作不是一个inplace操作，第一张图的操作都会产出一个新的变量，通过set_value才能对tensor进行inplace操作
