### ISSUE TITLE
set_global_initializer

### ISSUE THREAD

**Issue by yt605155624** [PaddlePaddle/Paddle#35397]
你好 ，根据文档 https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/nn/initializer/set_global_initializer_cn.html#set-global-initializer ，set_global_initializer 对其后的代码生效，文档的示例代码在最后一行添加了 nn.initializer.set_global_initializer(None) ，请问这个作用是在其后的代码块中并不使用之前的 set_global_initializer 的设置，但是在 set_global_initializer 到 nn.initializer.set_global_initializer(None) 之前使用 set_global_initializer 的设置嘛？ 如果不是，如果我想在某一个局部区域使用 set_global_initializer，在某个位置之后的初始化不想被 set_global_initializer 影响，应该怎么做呢？

**Comment by yt605155624** [comment]
另外今天踩了一个坑，create_parameter 会被 set_global_initializer 影响，如果 nn.initializer.set_global_initializer(None) 的作用不是上面所说的话，能否让 set_global_initializer 也不影响 create_parameter 呢，因为文档中说明 对通过 create_global_var 、 create_tensor 等API创建的变量不会生效，请问不加入 create_parameter 是有什么设计在里面嘛¿？

**Comment by zhwesky2010** [comment]
@yt605155624  set_global_initializer(weight_init, bias_init=None)可以针对weight和bias进行设置，set_global_initializer(None)会取消这个全局设置，set_global_initializer目前只影响paddle的Layer类型，例如paddle.nn.Linear类型，其他创建参数的方法是不受影响的。

**Comment by yt605155624** [comment]
> @yt605155624 set_global_initializer(weight_init, bias_init=None)可以针对weight和bias进行设置，set_global_initializer(None)会取消这个全局设置，set_global_initializer目前只影响paddle的Layer类型，例如paddle.nn.Linear类型，其他创建参数的方法是不受影响的。

那么 如果我是 

set_global_initializer() 
... 一堆新建模型的操作
set_global_initializer(None)
一个参数设置

此时 "... 一堆新建模型的操作" 里面的参数们会被 第一个 set_global_initializer() 影响嘛？

**Comment by zhwesky2010** [comment]
@yt605155624 会的，set_global_initializer之后会一直生效，除非set_global_initializer(None)之后

**Comment by zhwesky2010** [comment]
【**Paddle参数初始化的特别说明**】目前的优先级顺序是：
---
1. param_attr中的initializer参数 ->
2. set_global_initializer ->
3. creat_parameter的default_initializer参数 ->
4. 如上面都没有设置，则会对weight进行Xavier初始化，对bias进行Constant(0.0)初始化

改动可能会造成一些其他模型的不兼容现象。

**Comment by yt605155624** [comment]
> ## 【**Paddle参数初始化的特别说明**】目前的优先级顺序是：
> 1. set_global_initializer ->
> 2. creat_parameter的default_initializer参数 ->
> 3. param_attr中的initializer参数 ->
> 4. 如上面都没有设置，则会对weigeth进行Xavier初始化，对bias进行Constant(0.0)初始化
> 
> 该优先级顺序会保持不变，请根据需要进行配置，set_global_initializer(None)可以取消全局初始化的设置。

我们认为这样的优先级的顺序应该是不对的，至少用户已经明确指定了初始化方式的不应该被 set_global_initializer 覆盖掉，set_global_initializer 更应该是对 4 的补充，默认的是 Xavier 和 Constant，set_global_initializer 改变了默认的方式，所以优先级 应该是 2->3->1->4, set_global_initializer(None) 从使用上来说非常不灵活，目前的优先级感觉也不太符合使用习惯，关于优先级的确定，在我们提出 issue 和 icafe 卡片之后是否有相应的讨论，可以发出如此设计优先级的文档嘛？

**Comment by yingyibiao** [comment]
> > ## 【**Paddle参数初始化的特别说明**】目前的优先级顺序是：
> > 
> > 1. set_global_initializer ->
> > 2. creat_parameter的default_initializer参数 ->
> > 3. param_attr中的initializer参数 ->
> > 4. 如上面都没有设置，则会对weigeth进行Xavier初始化，对bias进行Constant(0.0)初始化
> > 
> > 该优先级顺序会保持不变，请根据需要进行配置，set_global_initializer(None)可以取消全局初始化的设置。
> 
> 我们认为这样的优先级的顺序应该是不对的，至少用户已经明确指定了初始化方式的不应该被 set_global_initializer 覆盖掉，set_global_initializer 更应该是对 4 的补充，默认的是 Xavier 和 Constant，set_global_initializer 改变了默认的方式，所以优先级 应该是 2->3->1->4, set_global_initializer(None) 从使用上来说非常不灵活，目前的优先级感觉也不太符合使用习惯，关于优先级的确定，在我们提出 issue 和 icafe 卡片之后是否有相应的讨论，可以发出如此设计优先级的文档嘛？

mark

**Comment by zhwesky2010** [comment]
优先级的顺序是 1. param_attr中的initializer参数 -> 2.set_global_initializer -> 3. creat_parameter的default_initializer参数 -> 4. 如上面都没有设置，则会执行Xavier初始化和Constant初始化  上面写错了点，后面我们会对初始化进行整体调研设计，看看有什么建议

**Comment by zhwesky2010** [comment]
> > > ## 【**Paddle参数初始化的特别说明**】目前的优先级顺序是：
> > > 
> > > 1. set_global_initializer ->
> > > 2. creat_parameter的default_initializer参数 ->
> > > 3. param_attr中的initializer参数 ->
> > > 4. 如上面都没有设置，则会对weigeth进行Xavier初始化，对bias进行Constant(0.0)初始化
> > > 
> > > 该优先级顺序会保持不变，请根据需要进行配置，set_global_initializer(None)可以取消全局初始化的设置。
> > 
> > 
> > 我们认为这样的优先级的顺序应该是不对的，至少用户已经明确指定了初始化方式的不应该被 set_global_initializer 覆盖掉，set_global_initializer 更应该是对 4 的补充，默认的是 Xavier 和 Constant，set_global_initializer 改变了默认的方式，所以优先级 应该是 2->3->1->4, set_global_initializer(None) 从使用上来说非常不灵活，目前的优先级感觉也不太符合使用习惯，关于优先级的确定，在我们提出 issue 和 icafe 卡片之后是否有相应的讨论，可以发出如此设计优先级的文档嘛？
> 
> mark

后面会对初始化进行再次调研，看看有什么建议
