### ISSUE TITLE
c-api examples编译后运行出core

### ISSUE THREAD

**Issue by fty8788** [PaddlePaddle/Paddle#3543]
http://wiki.baidu.com/pages/viewpage.action?pageId=333193833
采用预编译好的二进制库文件，加入examples/model_inference/dense项目
link_directories("/home/work/yitengfei/Paddle/paddle/capi/examples/usr/local/lib")
编译完后，运行出core，加-g后gdb栈是乱码：
![image](https://user-images.githubusercontent.com/7581590/29393552-fd672870-8336-11e7-9294-89d34eaaa2f7.png)

**Comment by qingqing01** [comment]
@fty8788  首先提Issue请尽量贴文字信息，方便其他同学检索到~

能否提供更多的log，以及运行机器信息？ 看看存不存在用的是AVX编译的版本，而机器不支持AVX？

**Comment by fty8788** [comment]
@qingqing01 嗯嗯，我编译的过程是：
1. 从http://yq01-idl-gpu-jpaas-let00.yq01.baidu.com:8111/下载库文件
2.在paddle/capi/examples下解压缩
3.在paddle/capi/examples/model_inference/dense目录下，CMakeLists.txt第4行加：
link_directories("/home/work/yitengfei/Paddle/paddle/capi/examples/usr/local/lib")
然后cmake .  && make
4.运行dense，出core，core信息无法看
机器信息：
Linux cq01-pl27.cq01.baidu.com 2.6.32_1-15-0-0 #1 SMP Fri Jan 16 10:20:19 CST 2015 x86_64 GNU/Linux
CentOS release 4.3 (Final)

**Comment by qingqing01** [comment]
@fty8788  运行下面命令确认下，你使用的机器是否支持AVX~

```
cat /proc/cpuinfo | grep avx
```

**Comment by fty8788** [comment]
@qingqing01 结果为空

**Comment by qingqing01** [comment]
@fty8788 那就你使用的机器不支持AVX，而你使用的C-API是AVX编译的，出的core。 解决办法，需要更换C-API库~

**Comment by fty8788** [comment]
@qingqing01 通过换机器解决了，多谢

**Comment by zsrem** [comment]
同样问题
我是从paddleci.ngrok.io下载的capi
但是这上面没有区分所下载版本是否支持avx
请问从哪能下到自动检测avx的capi？

**Comment by beancoder** [comment]
请问哪个版本是非avx
