### ISSUE TITLE
PaddleClas如何在导出模型时导出infer_cfg.yaml?

### ISSUE THREAD

**Issue by CheQiXiao** [PaddlePaddle/Paddle#35441]
请问PaddleClas（版本2.2.1）如何在导出模型时导出inference_cfg.yaml文件呢？
PaddleDetection的export.py是可以同步导出这个文件的。Paddle Inference的C++ Windows编译部署需要这个文件，但是下面提供的yaml模板似乎用不了。

deploy/cpp/docs/models/paddleclas.md · PaddlePaddle/PaddleX - Gitee.com

deploy/cpp/docs/compile/paddle/windows.md · PaddlePaddle/PaddleX - Gitee.com

![image](https://user-images.githubusercontent.com/50894398/131975548-a2f288e1-da49-49c8-b23f-cb69c2e8b251.png)

问题来自论坛：https://aistudio.baidu.com/paddle/forum/topic/show/990548

**Comment by heliqi** [comment]
PaddleClass导出模型是没有inference_cfg.yaml文件的，需要基于上图中的yaml模版进行自己想要的修改。

使用提供的模版部署分类模型，是有什么报错呢？能贴下具体报错吗？
