### ISSUE TITLE
PaddleDetection中的剪枝用的什么剪枝方法呢？

### ISSUE THREAD

**Issue by zmdcs** [PaddlePaddle/Paddle#35444]
有没有文档具体写了呢？是根据参数裁剪对loss的影响来剪枝的吗？还是别的方法呢？

**Comment by wanghaoshuang** [comment]
PaddleDetection用的是敏感度分析方法：https://paddleslim.readthedocs.io/zh_CN/latest/tutorials/pruning/static/image_classification_sensitivity_analysis_tutorial.html

**Comment by zmdcs** [comment]
所以这个敏感度，就是修剪卷积层对mAP值的影响大小吧？




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年9月6日(星期一) 上午9:53
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [PaddlePaddle/Paddle] PaddleDetection中的剪枝用的什么剪枝方法呢？ (#35444)





 
PaddleDetection用的是敏感度分析方法：https://paddleslim.readthedocs.io/zh_CN/latest/tutorials/pruning/static/image_classification_sensitivity_analysis_tutorial.html
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
