### ISSUE TITLE
PaddleDetection中slim剪枝下的eval.py文件的输出中有pruned FLOPS，请问这个是剪枝后节省的flops吗？

### ISSUE THREAD

**Issue by zmdcs** [PaddlePaddle/Paddle#35456]
还有这个指标是eval.py中哪一行代码输出的呢？我没有找到print（pruned FLOPS）这种字样。

**Comment by zmdcs** [comment]
对不起，打开错eval.py文件了，只需要问第一个问题

**Comment by yghstill** [comment]
@zmdcs https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.2/static/slim/prune/eval.py#L134-L135  这里打印的是裁剪掉的flops的百分比，如果想打印剪裁后的flops，打印pruned_flops字段即可
