### ISSUE TITLE
【论文复现】RuntimeError: (PreconditionNotMet) A serious error has occurred here

### ISSUE THREAD

**Issue by CuberrChen** [PaddlePaddle/Paddle#35452]
版本、环境信息：
   1）PaddlePaddle版本：2.1.2
   2）CPU：Intel Xeon32
   3）GPU：TeslaV100*4
   4）系统环境：AIStudio单机多卡脚本环境；

- 训练信息
    1）单卡/多卡
    2）32G
    3）
- 复现信息：多卡训练时出现错误。模型的所有输出都用作了loss计算。我不知道问题出在哪里？是在前向推理过程中就出现了问题吗？还是梯度反向传播的时候？模型中所有参数都未设置过，backbone是直接调用，加一个Function Head。loss是自己编写的。但是在单卡环境训练时没有问题。
- 问题描述：
File "train.py", line 190, in <module>
    main(args)
  File "train.py", line 185, in main
    fp16=args.fp16)
  File "/mnt/code_20210903205917/paddleseg/core/train.py", line 178, in train
    logits_list = ddp_model(images)
  File "/opt/_internal/cpython-3.7.0/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 902, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/opt/_internal/cpython-3.7.0/lib/python3.7/site-packages/paddle/fluid/dygraph/parallel.py", line 581, in forward
    list(self._find_varbase(outputs)))

RuntimeError: (PreconditionNotMet) A serious error has occurred here. Please set find_unused_parameters=True to traverse backward graph in each step to prepare reduce in advance. If you have set, There may be several reasons for this error: 1) Please note that all forward outputs derived from the module parameters must participate in the calculation of losses and subsequent gradient calculations. If not, the wrapper will hang, waiting for autograd to generate gradients for these parameters. you can use detach or stop_gradient to make the unused parameters detached from the autograd graph. 2) Used multiple forwards and one backward. You may be able to wrap multiple forwards in a model.
  [Hint: Expected groups_need_finalize_ == false, but received groups_need_finalize_:1 != false:0.] (at /paddle/paddle/fluid/imperative/reducer.cc:554)

**Comment by WorldEditors** [comment]
Same problem met here. The two reasons for this error seems rather unreasonable. Any solution?

**Comment by ForFishes** [comment]
There are several reasons for this error:
1. There may be complex control flow in the model. If it exists, then you need to set ``find_unused_parameters=True``.
2. Not all the output of the model is used for backward calculation, which is the most common situation. At this time, you need to set ``detach()``/``stop_gradient`` to avoid this output.
3. Some parameters in the model communicate across nodes and are shared by other losses.
4. The network uses ``pylayer.``
