### ISSUE TITLE
多维输入CrossEntropyLoss报错

### ISSUE THREAD

**Issue by songrui2009** [PaddlePaddle/Paddle#35466]
- 标题：多维输入CrossEntropyLoss报错
- 版本、环境信息：
Paddle version: 2.1.2
Paddle With CUDA: True

OS: Deepin 20.2
Python version: 3.7.3

CUDA version: 9.2.148
cuDNN version: None.None.None
Nvidia driver version: 460.39
- 复现信息：
- 按照文档：https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/nn/CrossEntropyLoss_cn.html 
- 做一个[5,2,100]的input;再做一个[5,100]的label;即N=5,C=2,d1=100,调用默认loss=paddle.nn.CrossEntropyLoss()
- loss(input, label)报错：ValueError: (InvalidArgument) Input(Logits) and Input(Label) should in same shape in dimensions except axis.
  [Hint: Expected logits_dims[i] == labels_dims[i], but received logits_dims[i]:2 != labels_dims[i]:100.] (at /paddle/paddle/fluid/operators/softmax_with_cross_entropy_op.cc:150)
  [operator < softmax_with_cross_entropy > error]
- 问题描述：应该是要求logits和label所有对应周必须相等，也就是input的C要等于label的d1；但用paddle.nn.LogSoftmax(axis=1)+paddle.nn.loss.NLLLoss()没这个错误

**Comment by HydrogenSulfate** [comment]
你好目前CrossEntropyLoss的文档说明确实存在问题，最近已经在develop分支中对其进行了[修复](https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/nn/CrossEntropyLoss_cn.html#xingzhuang)
![image](https://user-images.githubusercontent.com/23737287/132218006-26108133-6123-470f-a6ff-83da2ecc9a51.png)
**input的形状中通道需要放在最后**，将input的形状变为[5,100,2]应该能正常运行了
![image](https://user-images.githubusercontent.com/23737287/132218375-3501bbce-2f51-414a-be01-33d776323be1.png)
![image](https://user-images.githubusercontent.com/23737287/132218426-54242d08-79cb-414d-abd5-f2c914a09a47.png)
