### ISSUE TITLE
关于手动设置ParamsBase的梯度的方法

### ISSUE THREAD

**Issue by LibrarristShalinward** [PaddlePaddle/Paddle#35468]
- 版本、环境信息：
    1）PaddlePaddle版本：2.1
    2）CPU/GPU：CPU
    3）系统环境：Win10
    4）Python版本号：Python 3.8.1

- 复现论文：[Cream of the Crop: Distilling Prioritized Paths For One-Shot Neural Architecture Search](https://proceedings.neurips.cc//paper/2020/file/d072677d210ac4c03ba046120f0802ec-Paper.pdf)
- 问题描述：我需要在用paddle.grad()计算模型参数的梯度后进行计算，并将结果强行设置为原模型参数的梯度。目前我尝试通过直接设置的语句来解决，但代码会出现如下报错：
![image](https://user-images.githubusercontent.com/72915245/132113504-dc4fb737-0c3d-433d-88ac-fe20bba3e72b.png)
同时，由于需要使用grad中的grad_ouputs参数，导致上述计算过程无法通过backward方法替代
因此，我希望获得一个尽可能简便的、能够手动强行设置模型参数grad的代码实现方案

**Comment by jerrywgz** [comment]
可以试下set_value的方式  https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/Tensor_cn.html#set-value-value
