### ISSUE TITLE
visualDL工具在脚本任务中如何使用？

### ISSUE THREAD

**Issue by zmdcs** [PaddlePaddle/Paddle#35460]
按照教程在命令行输入了visualdl --logdir ~/PaddleDetection/static/vdl_dir/scalar --port 8080指令，但运行后访问http://localhost:8080/显示无法访问，为什么呢？

**Comment by rainyfly** [comment]
请问您运行visualdl的主机和您的浏览器的主机是同一台主机吗，如果不是同一台主机，您可以试试加上 --host 0.0.0.0，然后根据运行visualdl的主机的ip来进行访问。如果还是报错，您可以截取一些图以便让我们更好地分析错误产生的原因。

**Comment by zmdcs** [comment]
是一台电脑，就应该是一台主机吧？



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年9月6日(星期一) 晚上7:22
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [PaddlePaddle/Paddle] visualDL工具在脚本任务中如何使用？ (#35460)





 
请问您运行visualdl的主机和您的浏览器的主机是同一台主机吗，如果不是同一台主机，您可以试试加上 --host 0.0.0.0，然后根据运行visualdl的主机的ip来进行访问。如果还是报错，您可以截取一些图以便让我们更好地分析错误产生的原因。
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by rainyfly** [comment]
是的，您可以把运行 'visualdl --logdir ~/PaddleDetection/static/vdl_dir/scalar --port 8080'指令时候终端的输出，以及~/PaddleDetection/static/vdl_dir/scala这个目录，还有浏览器的显示页面截屏给我们看一下

**Comment by zmdcs** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年9月6日(星期一) 晚上7:51
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [PaddlePaddle/Paddle] visualDL工具在脚本任务中如何使用？ (#35460)





 
是的，您可以把运行 'visualdl --logdir /PaddleDetection/static/vdl_dir/scalar --port 8080'指令时候终端的输出，以及/PaddleDetection/static/vdl_dir/scala这个目录，还有浏览器的显示页面截屏给我们看一下
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by zmdcs** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/Paddle"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年9月6日(星期一) 晚上7:51
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PaddlePaddle/Paddle] visualDL工具在脚本任务中如何使用？ (#35460)





 
是的，您可以把运行 'visualdl --logdir /PaddleDetection/static/vdl_dir/scalar --port 8080'指令时候终端的输出，以及/PaddleDetection/static/vdl_dir/scala这个目录，还有浏览器的显示页面截屏给我们看一下
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by tanshuai555** [comment]
我也是启动visualdl后，无法访问，我是在服务器上启动的
![image](https://github.com/PaddlePaddle/Paddle/assets/48782961/e7edaf8c-e626-4ebd-9e1c-1e9eef92d35f)
![image](https://github.com/PaddlePaddle/Paddle/assets/48782961/d03dcc13-2ba8-4dfe-94f5-2d13c7bb5f25)
