### ISSUE TITLE
jetpack 4.5   paddle 2.1.2 无法cmake通过，2.0.x可以

### ISSUE THREAD

**Issue by helloyan** [PaddlePaddle/Paddle#35477]
参数
cmake .. \
          -DWITH_CONTRIB=OFF \
          -DWITH_MKL=OFF  \
          -DWITH_MKLDNN=OFF \
          -DWITH_TESTING=OFF \
          -DCMAKE_BUILD_TYPE=Release \
          -DON_INFER=ON \
          -DWITH_PYTHON=ON \
              -DWITH_XBYAK=OFF  \
              -DWITH_NV_JETSON=ON \
              -DPY_VERSION=3.6

错误
CMake Error at cmake/operators.cmake:48 (list):
  list sub-command REMOVE_ITEM requires list to be present.
Call Stack (most recent call first):
  paddle/fluid/operators/CMakeLists.txt:98 (op_library)

**Comment by jerrywgz** [comment]
您好，目前我们正在确认问题～

**Comment by jerrywgz** [comment]
这个应该是cmake版本低了，jetson自带的比较低，要去下载一个3.16以上的版本就行

**Comment by helloyan** [comment]
已经升级，不过仍然有一堆错误，是否可以编译一个2.1.2的jetson whl包以供下载？

**Comment by wangye707** [comment]
@helloyan  https://paddle-inference-lib.bj.bcebos.com/2.1.2/nv-jetson-jetpack4.4-all/paddlepaddle_gpu-2.1.2-cp36-cp36m-linux_aarch64.whl

**Comment by helloyan** [comment]
已下载，可以运行了，正在测试，谢谢
