### ISSUE TITLE
paddleX可视化端 训练报错：AttributeError: 'NoneType' object has no attribute 'strip'

### ISSUE THREAD

**Issue by wuxiaodong1014** [PaddlePaddle/Paddle#35503]
老师您好！

在用docker中安装好的paddleX可视化端 ，进行训练时报错，错误提示：

AttributeError: 'NoneType' object has no attribute 'strip'

请问老师，这是什么原因呢？

**Comment by will-jl944** [comment]
请问运行的是什么任务，什么模型，什么格式的数据集？

可能是数据集的txt文件某一行读取不成功，建议检查一下，不要包含中文以及特殊字符。
