### ISSUE TITLE
请问paddle的预训练模型如何fine tune

### ISSUE THREAD

**Issue by huilin16** [PaddlePaddle/Paddle#35515]
我使用paddle.vision.models.resnet50(pretrained=True)加载了预训练模型，我想对最后的fc层进行训练，其余参数不变，请问应该如何操作

**Comment by heavengate** [comment]
`paddle.vision.models.resnet50(pretrained=True, num_classes=-1)`这样网络里面就不会加fc层，可以自行添加fc层，在网络里对resnet50的输出设置`x.stop_gradient=True`

**Comment by huilin16** [comment]
好的谢谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Kaipeng ***@***.***&gt;; 
发送时间: 2021年9月7日(星期二) 中午12:27
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [PaddlePaddle/Paddle] 请问paddle的预训练模型如何fine tune (#35515)





 
paddle.vision.models.resnet50(pretrained=True, num_classes=-1)这样网络里面就不会加fc层，可以自行添加fc层，在网络里对resnet50的输出设置x.stop_gradient=True
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
