### ISSUE TITLE
paddle 2.1 版本支持稀疏矩阵运算吗？

### ISSUE THREAD

**Issue by hailong23-jin** [PaddlePaddle/Paddle#35511]
最近在实现图神经网络相关的内容，但是没有找到对应的稀疏矩阵的处理API。请问有相关的功能吗？

**Comment by frankwhzhang** [comment]
具体指的是什么操作呢

**Comment by hailong23-jin** [comment]
例如我现在要在一张包含一百万个节点的图上训练，那么我现在就需要申请一个 1,000,000 x 1,000,000 的矩阵去表示图结构，也就是邻接矩阵，但实际上这个矩阵上大部分位置都是0，如果能有一种方法只存储有效数据，就可以大大压缩所使用的内存空间。除此之外，一般还需要针对稀疏矩阵做一些矩阵乘法运算，如果完全使用 n x n 的矩阵计算的话，计算量无疑也是很大的。

针对类似这种情况，像pytorch还有numpy都有类似的针对稀疏矩阵的支持方案。所以想问下paddle有没有类似的API接口支持呢？

**Comment by frankwhzhang** [comment]
可以参考https://github.com/PaddlePaddle/PGL 有图相关的支持

**Comment by hailong23-jin** [comment]
PGL之前使用过，但是这个模型仅提供了有限的模型实现，并且没有对外提供类似稀疏矩阵运算的接口。如果自己想要实现一个图神经网络的模型的话，PGL作用十分有限。

请问paddle有计划单独开发稀疏矩阵运算相关的接口吗？还是比较期待paddle能够开发出相关的API的。
