### ISSUE TITLE
paddle中是否有pack_padded_sequence相关的api

### ISSUE THREAD

**Issue by huilin16** [PaddlePaddle/Paddle#35519]
paddle如果实现torch.nn.utils.rnn.pack_padded_sequence的功能

**Comment by heavengate** [comment]
可以试下 `paddle.nn.layer.rnn.pack_sequence_as`

**Comment by huilin16** [comment]
好的，谢谢



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Kaipeng ***@***.***&gt;; 
发送时间: 2021年9月7日(星期二) 中午12:30
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [PaddlePaddle/Paddle] paddle中是否有pack_padded_sequence相关的api (#35519)





 
可以试下 paddle.nn.layer.rnn.pack_sequence_as
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by huilin16** [comment]
您好，请问是否有相关的例子文档呢，
我在飞桨官网的paddle文档、python函数源码中，都没有找到相关的例子，
使用torch中pack_padded_sequence的参数直接作为pack_sequence_as会报错&nbsp;ValueError: Structure is a scalar but len(flat_sequence) == 4 &gt; 1




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/Paddle"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年9月7日(星期二) 中午12:30
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PaddlePaddle/Paddle] paddle中是否有pack_padded_sequence相关的api (#35519)





 
可以试下 paddle.nn.layer.rnn.pack_sequence_as
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by LinJayan** [comment]
> 可以试下 `paddle.nn.layer.rnn.pack_sequence_as`

您好，这个API操作与torch.nn.utils.rnn.pack_padded_sequence的供能完全不一样，可以跟进实现下吗

**Comment by heavengate** [comment]
好的，我们评估一下这个API需求

**Comment by Ligoml** [comment]
你好，由于框架设计的原因，pack_padded_sequence暂时不会增加，你可以参考这条 FAQ实现相同的功能：https://www.paddlepaddle.org.cn/documentation/docs/zh/faq/train_cn.html#paddletorch-nn-utils-rnn-pack-padded-sequencetorch-nn-utils-rnn-pad-packed-sequenceapi
