### ISSUE TITLE
【论文复现赛】grad不允许直接赋值修改

### ISSUE THREAD

**Issue by Ligoml** [PaddlePaddle/Paddle#35520]
在论文复现赛中遇到的问题，目前已经根据历史issue解决，但希望飞桨后续考虑加上
- 赛题信息
赛题序号：39 Cream of the Crop: Distilling Prioritized Paths For One-Shot Neural Architecture Search
赛题类型：图像分类
- 需求描述
希望飞桨有类似torch.autograd.grad的函数，在复现赛题时牵扯到把上一步得到的梯度赋给变量进行梯度下降，需要拿到grad_outputs参数并修改，但是飞桨的grad不允许直接赋值修改，会报错 can't set attribute
- 解决方式
参考了两个issue，目前可以绕过去继续复现
https://github.com/PaddlePaddle/Paddle/issues/30979
https://github.com/PaddlePaddle/Paddle/issues/34211
- 建议描述
希望飞桨考虑后期把模型的参数和梯度设置为可修改的，可以提升paddle对于不同需求的适配性和灵活性

**Comment by heavengate** [comment]
感谢反馈，我们排一下这个需求~
