### ISSUE TITLE
训练时模型保存问题

### ISSUE THREAD

**Issue by luyunfighting** [PaddlePaddle/Paddle#35534]
paddle高阶API提供了model.fit训练，也可以边训练边验证，但是目前模型保存只支持按save_freq保存，如果我只想保存准确率最高的模型和最后一个该怎样做呢？如果边训练边验证，又如何分别保存训练时准确率最高的模型和验证时准确率最高的模型呢？
我的想法是解析log文件，有没有什么指教呢

**Comment by heavengate** [comment]
想保存精度最高的模型只能职级实现了，需要做训练中评估，然后比较评估模型的精度
