### ISSUE TITLE
ExternalError:  Cuda error(700), an illegal memory access was encountered.

### ISSUE THREAD

**Issue by leeyy2020** [PaddlePaddle/Paddle#35543]
- 版本、环境信息：
    1）PaddlePaddle版本：2.1.2
    2）CPU：无
    3）GPU：Tesla V100-SXM2 CUDA Version: 11.2  
    4）系统环境：Linux，Python3.7
 以上信息。
- 训练信息
    1）单机 单卡
    2）显存信息
    3）Operator信息
- 复现信息：如为报错，请给出复现环境、复现步骤
执行https://github.com/leeyy2020/EFL_en_baseline
 中的rdrop分支训练脚本即会报错
- 问题描述：请详细描述您的问题，同步贴出报错信息、日志、可复现的代码片段
<img width="1530" alt="截屏2021-09-07 下午6 21 40" src="https://user-images.githubusercontent.com/48672338/132328977-db8f134f-f321-44ae-a37b-e43855c80f1d.png">

**Comment by heavengate** [comment]
是否是预处理里的data augment把哪个数据的shape踩到0了

**Comment by leeyy2020** [comment]
> 是否是预处理里的data augment把哪个数据的shape踩到0了
不能吧，它第一个batch的loss都计算完了

**Comment by leeyy2020** [comment]
bug出现之后gpu会呈现这样的状态
<img width="571" alt="截屏2021-09-07 下午6 55 10" src="https://user-images.githubusercontent.com/48672338/132333383-a1c8c1f6-04bc-4d2c-b6e8-37238577ea5c.png">

**Comment by heavengate** [comment]
看报错是踩显存了，一般是因为tensor的shape不合法，可以打印一下tensor的shape看下

**Comment by leeyy2020** [comment]
> 看报错是踩显存了，一般是因为tensor的shape不合法，可以打印一下tensor的shape看下

<img width="1008" alt="截屏2021-09-07 下午8 31 45" src="https://user-images.githubusercontent.com/48672338/132344956-abf62b46-5759-4580-960b-d2a9708c5591.png">

**Comment by blurmemo** [comment]
请问楼主是怎么解决的吗
