### ISSUE TITLE
集群收敛问题

### ISSUE THREAD

**Issue by yinyunfeng** [PaddlePaddle/Paddle#3555]
同样的任务，提交单节点、两节点都能收敛，cost 0.4且在下降；  但是100节点就不能收敛，cost一直7. ，

**Comment by qingqing01** [comment]
@yinyunfeng 厂内用户问题，贴文字、链接时注意保密。

集群是同步SGD，节点数增多时，我理解是用了非常大的batch size，但pserver并没有多多节点梯度做平均，所以可能导致收敛变化。 建议，增加节点数时，调小batch size，或者换成adagrad/adadelt/adam等优化方法试下，同时加上 `show_parameter_stats_period` 参数，可以观察下weight、梯度的分布情况。

```
--show_parameter_stats_period=100 # 间隔可改变 
```

**Comment by yinyunfeng** [comment]
为什么节点数增多是用了非常大的batch size，每个节点不是自己计算自己的cost吗，每个节点的batch_size是一样的呀

**Comment by qingqing01** [comment]
@yinyunfeng  pserver(parameter server)需要聚合多个节点之间的梯度，节点数增加，对于pserver聚合的是一个非常大batch size样本的梯度，梯度进而影响weight~

**Comment by yinyunfeng** [comment]
ok，我调小一点batch_size再试试

**Comment by yinyunfeng** [comment]
pserver(parameter server)需要聚合多个节点之间的梯度，这个聚合是怎么实现的 ？ 我不同节点的数据是同分布的，计算出来的梯度按理也是同方向的，不应该抵消呀 @qingqing01

**Comment by wanghaoshuang** [comment]
close this issue due to inactivity.
