### ISSUE TITLE
[NVIDIA] Memory pool issue

### ISSUE THREAD

**Issue by JanuszL** [PaddlePaddle/Paddle#35555]
为使您的问题得到快速解决，在建立Issues前，请您先通过如下方式搜索是否有相似问题:【搜索issue关键字】【使用labels筛选】【官方文档】

如果您没有查询到相似问题，为快速解决您的提问，建立issue时请提供如下细节信息：
- 标题：简洁、精准概括您的问题
- 版本、环境信息：
    1）PaddlePaddle版本：请提供您的PaddlePaddle版本号，例如1.1或CommitID
    2）CPU/GPU：如果您使用GPU训练，请提供GPU驱动版本、CUDA和cuDNN版本号
    3）系统环境：请您描述系统类型、版本，例如Mac OS 10.14
    4）Python版本号
    5）显存信息
 注：您可以通过执行[summary_env.py](https://github.com/PaddlePaddle/Paddle/blob/develop/tools/summary_env.py)获取以上信息。
- 复现信息：如为报错，请给出复现环境、复现步骤
- 问题描述：请详细描述您的问题，同步贴出报错信息、日志/代码关键片段

Thank you for contributing to PaddlePaddle.
Before submitting the issue, you could search issue in the github in case that there was a similar issue submitted or resolved before.
If there is no solution,please provide us with the following details :
**System information**
-PaddlePaddle version: **2.1.2**
-CPU: including CPUMKL/OpenBlas/MKLDNN version: **NA**
-GPU: including CUDA/cuDNN version: **cuDNN Version: 8.1,  CUDA version: 11.1.105, Nvidia driver version: 450.51.06**
-OS Platform and Distribution(eg.Mac OS 10.14) - **Ubuntu 20.04**
-Python version: `Python 3.8.10`
Note: You can get most of the information by running [summary_env.py](https://github.com/PaddlePaddle/Paddle/blob/develop/tools/summary_env.py). 
**To Reproduce**
Steps to reproduce the behavior
Install DALI build from https://github.com/JanuszL/DALI/tree/non_owning_dl_tensors (it is the upstream DALI + changes in plugin/paddle.py).
Remove `fluid.core._cuda_synchronize(pd_gpu_place)` call.
Run Rn50 DALI example https://github.com/NVIDIA/DALI/tree/main/docs/examples/use_cases/paddle/resnet50 with 8GPUs
**Describe your current behavior**
Once for hundreds iterations, we get:
```Error: /paddle/paddle/fluid/operators/softmax_with_cross_entropy_op.cu:536 Assertion `labels_[idx_lbl] >= 0 && labels_[idx_lbl] < d_ || labels_[idx_lbl] == ignore_idx_` failed. The value of label[70] expected >= 0 and < 1000, or == -100,but got -5252642118288355952. Please check input value```
What indicates that the data with labels copied from DALI to the PaddlePaddle tensor is corrupted.
The mentioned DALI change (https://github.com/NVIDIA/DALI/pull/3305) removes ownership of FW tensors from DALI. Now the tensors that DALI FW iterator returns are no longer reused every iteration by DALI, but a new tensor is allocated and the user can do whatever he wants with the previously returned without a fear that DALI will overwrite the data.
I guess it used to work as the tensor had always valid data from the previous iteration and even a corruption during copy happened it was not detected. Now every time a fresh tensor is used and the issue is visible. Adding `fluid.core._cuda_synchronize(pd_gpu_place)` call after PaddlePaddle tensors are allocated seems to solve the issue.

**Code to reproduce the issue**
**Other info / logs**

@willthefrog - you did the original integration between DALI and PaddlePaddle. Maybe there is something obviously wrong with the approach proposed in https://github.com/NVIDIA/DALI/pull/3305.

**Comment by jeng1220** [comment]
add PIC for Paddle with DALI integration - @zhiqiu

**Comment by zhiqiu** [comment]
Hi, @jeng1220 @JanuszL I tried to compile your PR3305 but failed these days. Could you give me a built wheel package for debug?

And after reading your PR, I suggest that you can try to use `cudaEventRecord on compute stream +cudaStreamWaitEvent on dali stream` instead of `fluid.core._cuda_synchronize` (which sync all the paddle compute streams) between `mutable_data and feed_ndarray`.

pesudo code: 
```
ptr = lod_tensor._mutable_data(category_place[cat],
                                               category_pd_type[cat])
event = cudaCreateEvent()
cudaEventRecord(event, paddle.device.cuda.current_stream(device_id))
cudaStreamWaitEvent(copy_stream, event)
feed_ndarray(tensor, ptr, copy_stream)
```


Just like paddle's dataloder doing:

https://github.com/PaddlePaddle/Paddle/blob/97a73e1dc5f13d8fcd3b4af8895df85548f67091/paddle/fluid/operators/reader/buffered_reader.cc#L158-L198

**Comment by JanuszL** [comment]
Hi @zhiqiu,

Thank you for looking into that issue. To repro it, you don't have to build DALI, the changes from the mentioned PR relate only to the python part, so you can install the latest DALI and just update the relevant python files in the location where your wheel is installed (in my case `/usr/local/lib/python3.6/dist-packages/nvidia/dali/plugin/`).

Just to be sure, do I need to call cudaEventRecord->cudaStreamWaitEvent or can I just `feed_ndarray(tensor, ptr, paddle.device.cuda.current_stream(device_id))`. This way DALI would do the copy on the same stream as PaddlePaddle ops operate on so it should be safe.

Another question - when the python API that exposes CUDA streams is going to be available (I see that is available only on the development branch).

**Comment by zhiqiu** [comment]
> Hi @zhiqiu,
> Thank you for looking into that issue. To repro it, you don't have to build DALI, the changes from the mentioned PR relate only to the python part, so you can install the latest DALI and just update the relevant python files in the location where your wheel is installed (in my case `/usr/local/lib/python3.6/dist-packages/nvidia/dali/plugin/`).

Thanks. I will try your method. 

> Just to be sure, do I need to call cudaEventRecord->cudaStreamWaitEvent or can I just `feed_ndarray(tensor, ptr, paddle.device.cuda.current_stream(device_id))`. This way DALI would do the copy on the same stream as PaddlePaddle ops operate on so it should be safe.

I think the better way is to use two stream and use event to sync them, in that case, the data copy stream and compute stream can overlap to improve performance.

> Another question - when the python API that exposes CUDA streams is going to be available (I see that is available only on the development branch).

The `paddle.device.cuda.current_stream(device_id))` will be released in Paddle-2.2rc (next month). If you need to use it, you can install the nightly-build version. Here is the command for cuda-11.2 version:
`python -m pip install paddlepaddle-gpu==0.0.0.post112 -f https://www.paddlepaddle.org.cn/whl/linux/gpu/develop.html`

**Comment by JanuszL** [comment]
@zhiqiu,

>The paddle.device.cuda.current_stream(device_id)) will be released in Paddle-2.2rc (next month). If you need to use it, you can install the nightly-build version. Here is the command for cuda-11.2 version:
python -m pip install paddlepaddle-gpu==0.0.0.post112 -f https://www.paddlepaddle.org.cn/whl/linux/gpu/develop.html

I'll give it a try. Thanks for the help.

**Comment by JanuszL** [comment]
Hi @zhiqiu,

I tested the method by creating and recording the event. It seems to work fine.

> I think the better way is to use two stream and use event to sync them, in that case, the data copy stream and compute stream can overlap to improve performance.

In the case of DALI device2device copy is performed and it cannot overlap with other kernels. However I cannot do `feed_ndarray(tensor, ptr, paddle.device.cuda.current_stream(device_id))` as `current_stream` call returns PaddlePaddle object and it is not possible to extract a raw cuda stream that DALI expects. I checked the API and I was not able to find way, even `raw_stream` method from cuda_stream.h is not exposed in the binary so I cannot call it indirectly (using ctypes.CDLL).
Do you plan to expose streams and events raw pointer so other libraries can use them?

**Comment by zhiqiu** [comment]
> and it cannot overlap with other kernels.

OK, I got it. I will find how to expose the raw pointer of `current_stream`.

**Comment by zhiqiu** [comment]
> > and it cannot overlap with other kernels.
> 
> OK, I got it. I will find how to expose the raw pointer of `current_stream`.

Hi, @JanuszL Please refer to: https://github.com/PaddlePaddle/Paddle/pull/35813

**Comment by JanuszL** [comment]
Hi @zhiqiu,

That should do. I will check the nightly build as soon as it is merged. Thanks a lot.
