### ISSUE TITLE
PaddleX的加载预测模型GitHub网页丢失

### ISSUE THREAD

**Issue by Sun-Shun** [PaddlePaddle/Paddle#35558]
非常感谢您提交关于飞桨文档的Issue，我们会认真听取您的意见，并进行改进。

建立issue时，为快速解决问题，请您根据情况给出如下信息：
- 标题：请包含关键词“XXX文档问题”，例如“add 文档问题” 或 ”paddle.add 文档问题“
- 文档版本信息：请提供有问题的文档的版本号，例如 develop，1.8，2.0RC；

#### API文档描述是否清晰？
如：无

#### 参数说明是否清晰
如：无

#### 返回/形状说明是否清晰
如：无

#### 示例代码是否有效？
如：无

#### 中英文内容是否一致？
如：无

#### 其他
如：文档页面打不开；文档缺失；
PaddleX文档，3. 模型训练/评估/预测目录下的 “加载训好的模型完成预测及预测结果可视化”链接，打开网页，发现 “predict接口说明文档”的链接丢失！！！

Thanks for opening a document issue. We will listen to your opinions carefully and make improvements.

In order to quickly solve your problem, when creating an issue, please provide the following information:
**Document Information**
- Title：Please include the keyword "XXX document issue", such as "add document issue" or "paddle.add document issue"
- Doc Version：Please provide the version of the document, such as develop, 1.8, 2.0RC;

#### Document description is clear?
For example: I don’t understand this document, I don’t know how to use this API; The formula in this doc is unclear;

#### Parameter description is clear?
For example: The parameters are confusing, including usage, scenarios, default values, etc.

#### Return/Shape description is clear
For example: Data returned this doc is error, shape returned is not clear.

#### The sample code is clear?
For example: no sample code; The sample code is not helpful; The sample code not run well; Format of the sample is not reasonable; The sample code has no comments.

#### Chinese content and English content is consistent?
For example:Chinese API in this doc is inconsistent with English API, including params, description, sample code, formula, etc.

#### Other
For example: The doc link is broken; The doc page is missing; Dead link in docs.

**Comment by heavengate** [comment]
你好，可以到PaddleX里面提issue反馈一下，会有专人处理的 https://github.com/PaddlePaddle/PaddleX/issues
