### ISSUE TITLE
报名

### ISSUE THREAD

**Issue by Abaiyu** [PaddlePaddle/Paddle#35559]
【队名】：白鱼向前冲

【序号】：9

【论文】：YOLOX: Exceeding YOLO Series in 2021
 
【状态】：报名

【repo链接】： https://github.com/Abaiyu/Paddle_YOLOX

**Comment by TCChenlong** [comment]
报名是回复这个ISSUE哈：https://github.com/PaddlePaddle/Paddle/issues/34526
