### ISSUE TITLE
当我尝试复现VoxelNet时，当模型前传至Conv3D时报错cudann error CUDNN_STATUS_EXECUTION_FAILED 

### ISSUE THREAD

**Issue by EmiyaNing** [PaddlePaddle/Paddle#35562]
1）PaddlePaddle版本：2.1.2
    2）CPU：intel i1900
    3）GPU：RTX 3090，conda中paddle环境下 cudatoolkit 11.2.2 cudnn 8.1.0.77
    4）系统环境：ubuntu 20.04, 系统中 cudatoolkit 11.1 cudnn 8.2.1.32
- 训练信息
    1) 单卡
    2）显存信息
    3）Operator信息
- 复现信息：如为报错，请给出复现环境、复现步骤
- 问题描述：请详细描述您的问题，同步贴出报错信息、日志、可复现的代码片段

Thank you for contributing to PaddlePaddle.
Before submitting the issue, you could search issue in the github in case that there was a similar issue submitted or resolved before.
If there is no solution,please make sure that this is a training issue including the following details:
**System information**
-PaddlePaddle version （eg.1.1）or CommitID
-CPU: including CPUMKL/OpenBlas/MKLDNN version
-GPU: including CUDA/CUDNN version
-OS Platform (eg.Mac OS 10.14)
-Other imformation: Distriuted training/informantion of operator/
Graphics card storage
Note: You can get most of the information by running [summary_env.py](https://github.com/PaddlePaddle/Paddle/blob/develop/tools/summary_env.py). 
**To Reproduce**
Steps to reproduce the behavior
**Describe your current behavior**
**Code to reproduce the issue**
**Other info / logs**

**Comment by EmiyaNing** [comment]
在今天测试代码的时候我发现bug的问题不是来自paddle.nn.Conv3D,而是来自函数paddle.scatter_nd。在我自己重写了scatter_nd部分的代码之后，该bug消失了。

**Comment by heavengate** [comment]
是否是你在用scatter_nd的时候有非法的输入或者有类似于下标越界的情况
