### ISSUE TITLE
CUDA driver version is insufficient for CUDA runtime version

### ISSUE THREAD

**Issue by zssty2010** [PaddlePaddle/Paddle#35564]
****************************************
Paddle version: 2.0.0-rc0
Paddle With CUDA: True

OS: CentOS Linux 7
Python version: 3.6.5

CUDA version: 10.1.243
cuDNN version: None.None.None
Nvidia driver version: 418.165.02
****************************************
使用paddleOCR时遇到的问题，感觉应该是paddle fluid这边的issue。

异常信息：
ExternalError:  Cuda error(35), CUDA driver version is insufficient for CUDA runtime version.
  [Advise: This indicates that the installed NVIDIA CUDA driver is older than the CUDA runtime library. This is not a supported configuration.Users should install an updated NVIDIA display driver to allow the application to run.] (at [/paddle/paddle/fluid/platform/gpu_info.cc:68](https://github.com/PaddlePaddle/Paddle/blob/530deb144e25be52adc16999cdcab67cfe39f092/paddle/fluid/platform/gpu_info.cc#L68))

---

奇怪的是，我在相同的环境下编译运行了调试代码，正常通过。
```c++
#include <cuda.h>
#include <stdio.h>
int main(int argc, char* argv[]) {

  int dev_cnt = -1;
  cudaGetDeviceCount(&dev_cnt);
  auto err = cudaGetLastError();
  if(err != cudaSuccess) {
    printf("cudaGetDeviceCount Error: %s\n",  cudaGetErrorString(err));
    exit(-1);
  }
  printf("device count: %d", dev_cnt);
  return 0;
}
```
然后，我换了2.0~2.1.2之间的版本都不行，只有1.8.0.post97可以。

**Comment by sandyhouse** [comment]
根据信息升级下driver版本吧。
请参考cuda版本和driver版本对应关系：
![image](https://user-images.githubusercontent.com/6737864/132435902-5d959b03-37b6-4c19-a2b0-829d3ae13a14.png)

**Comment by Essence9999** [comment]
> 根据信息升级下driver版本吧。
> 请参考cuda版本和driver版本对应关系：
> ![image](https://user-images.githubusercontent.com/6737864/132435902-5d959b03-37b6-4c19-a2b0-829d3ae13a14.png)
cuda11.2
这个跟版本，驱动应该没有关系吧~
单进程跑，没有问题
多进程跑，也会提示这个问题

难道是高版本的cuda支持多进程？

**Comment by sandyhouse** [comment]
按照nvidia官方推荐的驱动版本配置吧。版本不匹配的话很容易出现各种兼容性问题。

**Comment by Essence9999** [comment]
> 按照nvidia官方推荐的驱动版本配置吧。版本不匹配的话很容易出现各种兼容性问题。

用的是百度官方的paddlepaddle/paddle:2.1.2-gpu-cuda11.2-cudnn8部署的，而且单任务gpu执行没问题啊，不应该是配置的问题啊

**Comment by sandyhouse** [comment]
驱动是依赖于物理机的驱动版本的。docker里面只是固定了cuda和cudnn版本。

**Comment by Essence9999** [comment]
> 驱动是依赖于物理机的驱动版本的。docker里面只是固定了cuda和cudnn版本。

同环境，我之前已训练了检测模型，GPU利用率90%，而且单任务预测，gpu使用没问题，怎么可能还是驱动版本问题呢？
（GeForce RTX 3070；NVIDIA-SMI 460.39       Driver Version: 460.39       CUDA Version: 11.2   ）

**Comment by Essence9999** [comment]
> 驱动是依赖于物理机的驱动版本的。docker里面只是固定了cuda和cudnn版本。

刚查了最新的驱动版本是470.63.01，有必要更新到最新版本驱动吗？

**Comment by sandyhouse** [comment]
> Paddle version: 2.0.0-rc0
> Paddle With CUDA: True
> 
> OS: CentOS Linux 7
> Python version: 3.6.5
> 
> CUDA version: 10.1.243
> cuDNN version: None.None.None
> Nvidia driver version: 418.165.02
> 
> 使用paddleOCR时遇到的问题，感觉应该是paddle fluid这边的issue。
> 
> 异常信息：
> ExternalError: Cuda error(35), CUDA driver version is insufficient for CUDA runtime version.
> [Advise: This indicates that the installed NVIDIA CUDA driver is older than the CUDA runtime library. This is not a supported configuration.Users should install an updated NVIDIA display driver to allow the application to run.] (at /paddle/paddle/fluid/platform/gpu_info.cc:68)

你的问题不是这个问题？那麻烦把你的报错信息贴下吧。我一直以为你问的还是这个问题。

**Comment by Essence9999** [comment]
> > Paddle version: 2.0.0-rc0
> > Paddle With CUDA: True
> > OS: CentOS Linux 7
> > Python version: 3.6.5
> > CUDA version: 10.1.243
> > cuDNN version: None.None.None
> > Nvidia driver version: 418.165.02
> > 使用paddleOCR时遇到的问题，感觉应该是paddle fluid这边的issue。
> > 异常信息：
> > ExternalError: Cuda error(35), CUDA driver version is insufficient for CUDA runtime version.
> > [Advise: This indicates that the installed NVIDIA CUDA driver is older than the CUDA runtime library. This is not a supported configuration.Users should install an updated NVIDIA display driver to allow the application to run.] (at /paddle/paddle/fluid/platform/gpu_info.cc:68)
> 
> 你的问题不是这个问题？那麻烦把你的报错信息贴下吧。我一直以为你问的还是这个问题。

![image](https://user-images.githubusercontent.com/66725845/133715787-67fddb7d-3bdc-41f5-bc33-9b7a4d44d8d9.png)
开一个进程，没错
开了两个进程，报如下的错：
ERROR:predict_system_flask:Exception on / [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "predict_system_flask.py", line 137, in main
    text_sys = TextSystem(args)
  File "predict_system_flask.py", line 45, in __init__
    self.text_detector = predict_det.TextDetector(args)
  File "/home/PaddleOCR/tools/infer/predict_det.py", line 99, in __init__
    args, 'det', logger)
  File "/home/PaddleOCR/tools/infer/utility.py", line 250, in create_predictor
    predictor = inference.create_predictor(config)
OSError: (External)  Cuda error(3), initialization error.
  [Advise: The API call failed because the CUDA driver and runtime could not be initialized. ] (at /paddle/paddle/fluid/platform/gpu_info.cc:308)

ERROR:tornado.access:500 POST / (127.0.0.1) 40050.60ms

**Comment by WenmuZhou** [comment]
麻烦提供一个可复现的脚本

**Comment by Essence9999** [comment]
> 麻烦提供一个可复现的脚本

#! -*- coding: utf-8 -*-
from tornado.wsgi import WSGIContainer
from tornado.httpserver import HTTPServer
from tornado.ioloop import IOLoop

import os
import sys
import subprocess

__dir__ = os.path.dirname(os.path.abspath(__file__))
sys.path.append(__dir__)
sys.path.append(os.path.abspath(os.path.join(__dir__, '../..')))

os.environ["FLAGS_allocator_strategy"] = 'auto_growth'
os.environ["KMP_DUPLICATE_LIB_OK"]="TRUE"

import re
import cv2
import copy
import numpy as np
import time
import logging
from PIL import Image
import tools.infer.utility as utility
import tools.infer.predict_rec as predict_rec
import tools.infer.predict_det as predict_det
import tools.infer.predict_cls as predict_cls
from ppocr.utils.utility import get_image_file_list, check_and_read_gif
from ppocr.utils.logging import get_logger
from tools.infer.utility import draw_ocr_box_txt, get_rotate_crop_image
logger = get_logger()
from flask import Flask, request
import json
import base64
import random




class TextSystem(object):
    def __init__(self, args):
        if not args.show_log:
            logger.setLevel(logging.INFO)

        self.text_detector = predict_det.TextDetector(args)
        self.text_recognizer = predict_rec.TextRecognizer(args)
        self.use_angle_cls = args.use_angle_cls
        self.drop_score = args.drop_score
        if self.use_angle_cls:
            self.text_classifier = predict_cls.TextClassifier(args)

    def print_draw_crop_rec_res(self, img_crop_list, rec_res):
        bbox_num = len(img_crop_list)
        for bno in range(bbox_num):
            cv2.imwrite("./output/img_crop_%d.jpg" % bno, img_crop_list[bno])
            # logger.info(bno, rec_res[bno])

    def __call__(self, img, cls=True):
        ori_im = img.copy()
        dt_boxes, elapse = self.text_detector(img)
        # logger.debug("dt_boxes num : {}, elapse : {}".format(
        if dt_boxes is None:
            return None, None
        img_crop_list = []

        dt_boxes = sorted_boxes(dt_boxes)

        for bno in range(len(dt_boxes)):
            tmp_box = copy.deepcopy(dt_boxes[bno])
            img_crop = get_rotate_crop_image(ori_im, tmp_box)
            img_crop_list.append(img_crop)
        if self.use_angle_cls and cls:
            img_crop_list, angle_list, elapse = self.text_classifier(
                img_crop_list)
            # logger.debug("cls num  : {}, elapse : {}".format(
            #     len(img_crop_list), elapse))

        rec_res, elapse = self.text_recognizer(img_crop_list)
        # logger.debug("rec_res num  : {}, elapse : {}".format(
        #     len(rec_res), elapse))
        # self.print_draw_crop_rec_res(img_crop_list, rec_res)
        filter_boxes, filter_rec_res = [], []
        for box, rec_reuslt in zip(dt_boxes, rec_res):
            text, score = rec_reuslt
            if score >= self.drop_score:
                filter_boxes.append(box)
                filter_rec_res.append(rec_reuslt)
        return filter_boxes, filter_rec_res

def sorted_boxes(dt_boxes):
    num_boxes = dt_boxes.shape[0]
    sorted_boxes = sorted(dt_boxes, key=lambda x: (x[0][1], x[0][0]))
    _boxes = list(sorted_boxes)

    for i in range(num_boxes - 1):
        if abs(_boxes[i + 1][0][1] - _boxes[i][0][1]) < 10 and \
                (_boxes[i + 1][0][0] < _boxes[i][0][0]):
            tmp = _boxes[i]
            _boxes[i] = _boxes[i + 1]
            _boxes[i + 1] = tmp
    return _boxes

app = Flask(__name__)

@app.route('/', methods=['POST'])
def main():
    res_data = {}
    path = '/home/PaddleOCR'
    image_file = request.files.get('image')
    if not image_file:  #没有上传文件
        res_data['key'] = '110'
        return json.dumps(res_data)
    base64_data = base64.b64encode(image_file.read())
    b64 = str(base64_data, encoding='utf-8')
    b64 = bytes(b64, encoding="utf-8")
    inputdata = base64.b64decode(b64)
    fileName = str(random.randint(0, 1000))
    try:
        file = open(path + "/doc/imgs/" + fileName + ".jpg", 'wb')
        file.write(inputdata)
        file.close()
    except:
        if os.path.exists(path + "/doc/imgs" + fileName + ".jpg"):
            os.remove(path + "/doc/imgs" + fileName + ".jpg")
        # print('图片缓存报错')

    args = utility.parse_args()
    # args.image_dir = './doc/imgs/id/'
    args.image_dir = path + "/doc/imgs/" + fileName + ".jpg"
    args.det_model_dir = path + '/inference/ch_ppocr_mobile_v2.0_det_infer/'
    args.rec_model_dir = path + '/inference/ch_ppocr_mobile_v2.0_rec_infer/'
    args.rec_char_dict_path = path + '/ppocr/utils/ppocr_keys_v1.txt'

    image_file_list = get_image_file_list(args.image_dir)
    image_file_list = image_file_list[args.process_id::args.total_process_num]
    text_sys = TextSystem(args)
    is_visualize = True
    font_path = args.vis_font_path
    drop_score = args.drop_score

    # total_time = 0
    # cpu_mem, gpu_mem, gpu_util = 0, 0, 0
    # _st = time.time()
    # count = 0
    # avg_score = 0
    # num = len(image_file_list)
    for idx, image_file in enumerate(image_file_list):
        img, flag = check_and_read_gif(image_file)
        if not flag:
            img = cv2.imread(image_file)
        if img is None:
            logger.info("error in loading image:{}".format(image_file))
            continue
        # starttime = time.time()
        dt_boxes, rec_res = text_sys(img)
        # elapse = time.time() - starttime
        # total_time += elapse
        score1 = 0
        text1 = []
        for text, score in rec_res:
            # logger.info("{}, {:.3f}".format(text, score))
            text1.append(text)
            score1 += score
        # print(''.join(text1))
        str_text = ''.join(text1)
        res_data['key'] = '666'
        return json.dumps(res_data)
        # print(str_text)
if __name__ == "__main__":
    http_server = HTTPServer(WSGIContainer(app))
    #http_server.listen(6666)

    http_server.bind(6666)
    http_server.start(2)

    print('run...')
    IOLoop.current().start()

**Comment by Essence9999** [comment]
> 麻烦提供一个可复现的脚本

`#! -*- coding: utf-8 -*-
from tornado.wsgi import WSGIContainer
from tornado.httpserver import HTTPServer
from tornado.ioloop import IOLoop

import os
import sys
import subprocess

__dir__ = os.path.dirname(os.path.abspath(__file__))
sys.path.append(__dir__)
sys.path.append(os.path.abspath(os.path.join(__dir__, '../..')))

os.environ["FLAGS_allocator_strategy"] = 'auto_growth'
os.environ["KMP_DUPLICATE_LIB_OK"]="TRUE"

import re
import cv2
import copy
import numpy as np
import time
import logging
from PIL import Image
import tools.infer.utility as utility
import tools.infer.predict_rec as predict_rec
import tools.infer.predict_det as predict_det
import tools.infer.predict_cls as predict_cls
from ppocr.utils.utility import get_image_file_list, check_and_read_gif
from ppocr.utils.logging import get_logger
from tools.infer.utility import draw_ocr_box_txt, get_rotate_crop_image
logger = get_logger()
from flask import Flask, request
import json
import base64
import random




class TextSystem(object):
    def __init__(self, args):
        if not args.show_log:
            logger.setLevel(logging.INFO)

        self.text_detector = predict_det.TextDetector(args)
        self.text_recognizer = predict_rec.TextRecognizer(args)
        self.use_angle_cls = args.use_angle_cls
        self.drop_score = args.drop_score
        if self.use_angle_cls:
            self.text_classifier = predict_cls.TextClassifier(args)

    def print_draw_crop_rec_res(self, img_crop_list, rec_res):
        bbox_num = len(img_crop_list)
        for bno in range(bbox_num):
            cv2.imwrite("./output/img_crop_%d.jpg" % bno, img_crop_list[bno])
            # logger.info(bno, rec_res[bno])

    def __call__(self, img, cls=True):
        ori_im = img.copy()
        dt_boxes, elapse = self.text_detector(img)
        # logger.debug("dt_boxes num : {}, elapse : {}".format(
        if dt_boxes is None:
            return None, None
        img_crop_list = []

        dt_boxes = sorted_boxes(dt_boxes)

        for bno in range(len(dt_boxes)):
            tmp_box = copy.deepcopy(dt_boxes[bno])
            img_crop = get_rotate_crop_image(ori_im, tmp_box)
            img_crop_list.append(img_crop)
        if self.use_angle_cls and cls:
            img_crop_list, angle_list, elapse = self.text_classifier(
                img_crop_list)
            # logger.debug("cls num  : {}, elapse : {}".format(
            #     len(img_crop_list), elapse))

        rec_res, elapse = self.text_recognizer(img_crop_list)
        # logger.debug("rec_res num  : {}, elapse : {}".format(
        #     len(rec_res), elapse))
        # self.print_draw_crop_rec_res(img_crop_list, rec_res)
        filter_boxes, filter_rec_res = [], []
        for box, rec_reuslt in zip(dt_boxes, rec_res):
            text, score = rec_reuslt
            if score >= self.drop_score:
                filter_boxes.append(box)
                filter_rec_res.append(rec_reuslt)
        return filter_boxes, filter_rec_res

def sorted_boxes(dt_boxes):
    num_boxes = dt_boxes.shape[0]
    sorted_boxes = sorted(dt_boxes, key=lambda x: (x[0][1], x[0][0]))
    _boxes = list(sorted_boxes)

    for i in range(num_boxes - 1):
        if abs(_boxes[i + 1][0][1] - _boxes[i][0][1]) < 10 and \
                (_boxes[i + 1][0][0] < _boxes[i][0][0]):
            tmp = _boxes[i]
            _boxes[i] = _boxes[i + 1]
            _boxes[i + 1] = tmp
    return _boxes

app = Flask(__name__)

@app.route('/', methods=['POST'])
def main():
    res_data = {}
    path = '/home/PaddleOCR'
    image_file = request.files.get('image')
    if not image_file:  #没有上传文件
        res_data['key'] = '110'
        return json.dumps(res_data)
    base64_data = base64.b64encode(image_file.read())
    b64 = str(base64_data, encoding='utf-8')
    b64 = bytes(b64, encoding="utf-8")
    inputdata = base64.b64decode(b64)
    fileName = str(random.randint(0, 1000))
    try:
        file = open(path + "/doc/imgs/" + fileName + ".jpg", 'wb')
        file.write(inputdata)
        file.close()
    except:
        if os.path.exists(path + "/doc/imgs" + fileName + ".jpg"):
            os.remove(path + "/doc/imgs" + fileName + ".jpg")
        # print('图片缓存报错')

    args = utility.parse_args()
    # args.image_dir = './doc/imgs/id/'
    args.image_dir = path + "/doc/imgs/" + fileName + ".jpg"
    args.det_model_dir = path + '/inference/ch_ppocr_mobile_v2.0_det_infer/'
    args.rec_model_dir = path + '/inference/ch_ppocr_mobile_v2.0_rec_infer/'
    args.rec_char_dict_path = path + '/ppocr/utils/ppocr_keys_v1.txt'

    image_file_list = get_image_file_list(args.image_dir)
    image_file_list = image_file_list[args.process_id::args.total_process_num]
    text_sys = TextSystem(args)
    is_visualize = True
    font_path = args.vis_font_path
    drop_score = args.drop_score

    # total_time = 0
    # cpu_mem, gpu_mem, gpu_util = 0, 0, 0
    # _st = time.time()
    # count = 0
    # avg_score = 0
    # num = len(image_file_list)
    for idx, image_file in enumerate(image_file_list):
        img, flag = check_and_read_gif(image_file)
        if not flag:
            img = cv2.imread(image_file)
        if img is None:
            logger.info("error in loading image:{}".format(image_file))
            continue
        # starttime = time.time()
        dt_boxes, rec_res = text_sys(img)
        # elapse = time.time() - starttime
        # total_time += elapse
        score1 = 0
        text1 = []
        for text, score in rec_res:
            # logger.info("{}, {:.3f}".format(text, score))
            text1.append(text)
            score1 += score
        # print(''.join(text1))
        str_text = ''.join(text1)
        res_data['key'] = '666'
        return json.dumps(res_data)
        # print(str_text)
if __name__ == "__main__":
    http_server = HTTPServer(WSGIContainer(app))
    #http_server.listen(6666)

    http_server.bind(6666)
    http_server.start(2)

    print('run...')
    IOLoop.current().start()
`

**Comment by Essence9999** [comment]
> 麻烦提供一个可复现的脚本


#! -*- coding: utf-8 -*-
from tornado.wsgi import WSGIContainer
from tornado.httpserver import HTTPServer
from tornado.ioloop import IOLoop

import os
import sys
import subprocess

__dir__ = os.path.dirname(os.path.abspath(__file__))
sys.path.append(__dir__)
sys.path.append(os.path.abspath(os.path.join(__dir__, '../..')))

os.environ["FLAGS_allocator_strategy"] = 'auto_growth'
os.environ["KMP_DUPLICATE_LIB_OK"]="TRUE"

import re
import cv2
import copy
import numpy as np
import time
import logging
from PIL import Image
import tools.infer.utility as utility
import tools.infer.predict_rec as predict_rec
import tools.infer.predict_det as predict_det
import tools.infer.predict_cls as predict_cls
from ppocr.utils.utility import get_image_file_list, check_and_read_gif
from ppocr.utils.logging import get_logger
from tools.infer.utility import draw_ocr_box_txt, get_rotate_crop_image
logger = get_logger()
from flask import Flask, request
import json
import base64
import random




class TextSystem(object):
    def __init__(self, args):
        if not args.show_log:
            logger.setLevel(logging.INFO)

        self.text_detector = predict_det.TextDetector(args)
        self.text_recognizer = predict_rec.TextRecognizer(args)
        self.use_angle_cls = args.use_angle_cls
        self.drop_score = args.drop_score
        if self.use_angle_cls:
            self.text_classifier = predict_cls.TextClassifier(args)

    def print_draw_crop_rec_res(self, img_crop_list, rec_res):
        bbox_num = len(img_crop_list)
        for bno in range(bbox_num):
            cv2.imwrite("./output/img_crop_%d.jpg" % bno, img_crop_list[bno])
            # logger.info(bno, rec_res[bno])

    def __call__(self, img, cls=True):
        ori_im = img.copy()
        dt_boxes, elapse = self.text_detector(img)
        # logger.debug("dt_boxes num : {}, elapse : {}".format(
        if dt_boxes is None:
            return None, None
        img_crop_list = []

        dt_boxes = sorted_boxes(dt_boxes)

        for bno in range(len(dt_boxes)):
            tmp_box = copy.deepcopy(dt_boxes[bno])
            img_crop = get_rotate_crop_image(ori_im, tmp_box)
            img_crop_list.append(img_crop)
        if self.use_angle_cls and cls:
            img_crop_list, angle_list, elapse = self.text_classifier(
                img_crop_list)
            # logger.debug("cls num  : {}, elapse : {}".format(
            #     len(img_crop_list), elapse))

        rec_res, elapse = self.text_recognizer(img_crop_list)
        # logger.debug("rec_res num  : {}, elapse : {}".format(
        #     len(rec_res), elapse))
        # self.print_draw_crop_rec_res(img_crop_list, rec_res)
        filter_boxes, filter_rec_res = [], []
        for box, rec_reuslt in zip(dt_boxes, rec_res):
            text, score = rec_reuslt
            if score >= self.drop_score:
                filter_boxes.append(box)
                filter_rec_res.append(rec_reuslt)
        return filter_boxes, filter_rec_res

def sorted_boxes(dt_boxes):
    num_boxes = dt_boxes.shape[0]
    sorted_boxes = sorted(dt_boxes, key=lambda x: (x[0][1], x[0][0]))
    _boxes = list(sorted_boxes)

    for i in range(num_boxes - 1):
        if abs(_boxes[i + 1][0][1] - _boxes[i][0][1]) < 10 and \
                (_boxes[i + 1][0][0] < _boxes[i][0][0]):
            tmp = _boxes[i]
            _boxes[i] = _boxes[i + 1]
            _boxes[i + 1] = tmp
    return _boxes

app = Flask(__name__)

@app.route('/', methods=['POST'])
def main():
    res_data = {}
    path = '/home/PaddleOCR'
    image_file = request.files.get('image')
    if not image_file:  #没有上传文件
        res_data['key'] = '110'
        return json.dumps(res_data)
    base64_data = base64.b64encode(image_file.read())
    b64 = str(base64_data, encoding='utf-8')
    b64 = bytes(b64, encoding="utf-8")
    inputdata = base64.b64decode(b64)
    fileName = str(random.randint(0, 1000))
    try:
        file = open(path + "/doc/imgs/" + fileName + ".jpg", 'wb')
        file.write(inputdata)
        file.close()
    except:
        if os.path.exists(path + "/doc/imgs" + fileName + ".jpg"):
            os.remove(path + "/doc/imgs" + fileName + ".jpg")
        # print('图片缓存报错')

    args = utility.parse_args()
    # args.image_dir = './doc/imgs/id/'
    args.image_dir = path + "/doc/imgs/" + fileName + ".jpg"
    args.det_model_dir = path + '/inference/ch_ppocr_mobile_v2.0_det_infer/'
    args.rec_model_dir = path + '/inference/ch_ppocr_mobile_v2.0_rec_infer/'
    args.rec_char_dict_path = path + '/ppocr/utils/ppocr_keys_v1.txt'

    image_file_list = get_image_file_list(args.image_dir)
    image_file_list = image_file_list[args.process_id::args.total_process_num]
    text_sys = TextSystem(args)
    is_visualize = True
    font_path = args.vis_font_path
    drop_score = args.drop_score

    # total_time = 0
    # cpu_mem, gpu_mem, gpu_util = 0, 0, 0
    # _st = time.time()
    # count = 0
    # avg_score = 0
    # num = len(image_file_list)
    for idx, image_file in enumerate(image_file_list):
        img, flag = check_and_read_gif(image_file)
        if not flag:
            img = cv2.imread(image_file)
        if img is None:
            logger.info("error in loading image:{}".format(image_file))
            continue
        # starttime = time.time()
        dt_boxes, rec_res = text_sys(img)
        # elapse = time.time() - starttime
        # total_time += elapse
        score1 = 0
        text1 = []
        for text, score in rec_res:
            # logger.info("{}, {:.3f}".format(text, score))
            text1.append(text)
            score1 += score
        # print(''.join(text1))
        str_text = ''.join(text1)
        res_data['key'] = '666'
        return json.dumps(res_data)
        # print(str_text)
if __name__ == "__main__":
    http_server = HTTPServer(WSGIContainer(app))
    #http_server.listen(6666)

    http_server.bind(6666)
    http_server.start(2)

    print('run...')
    IOLoop.current().start()

**Comment by zssty2010** [comment]
不纠结，我发完贴给服务器升了cuda_11.1.1_455.32.00_linux.run和驱动，然后各版paddle均畅通。不过值的一掉的是，我升级paddle的原因是1.8版本有内存泄露问题，在2.0.0以上没有了。
