### ISSUE TITLE
AI studio上faster RCNN只有coco格式的配置文件，能改成VOC格式的吗？

### ISSUE THREAD

**Issue by zmdcs** [PaddlePaddle/Paddle#35575]
很多配置文件都只有coco格式的，能改成voc格式的吗？怎么改呢？

**Comment by sandyhouse** [comment]
aistudio应该都是notebook访问的吧，都可以修改吧。

**Comment by sandyhouse** [comment]
Closing this issue. Reopen it if you have any further question.
