### ISSUE TITLE
安装完之后, 运行错误 "Error: Can not import avx core while this file exists: D:\......\Python39\lib\site-packages\paddle\fluid\core_avx.pyd"

### ISSUE THREAD

**Issue by N0I0C0K** [PaddlePaddle/Paddle#35570]
# Error: Can not import avx core
在我完全安装完, 安装没有报错的情况下, 运行paddle 验证安装时运行错误.
尝试了在百度上找到的方法 : 将libs下的dll文件放入fluid文件中. 
报错信息不变
- **paddle 版本**: 2.1
- CUDA : 11.2
- cuDNN : 8.1.1
- 环境 : windows10 64位
报错信息:
```
>>> import paddle
Error: Can not import avx core while this file exists: D:\..........\Python39\lib\site-packages\paddle\fluid\core_avx.pyd
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\...........\Python39\lib\site-packages\paddle\__init__.py", line 25, in <module>
    from .fluid import monkey_patch_variable
  File "D:\..........t\Python39\lib\site-packages\paddle\fluid\__init__.py", line 36, in <module>
    from . import framework
  File "D:\..........\Python39\lib\site-packages\paddle\fluid\framework.py", line 37, in <module>
    from . import core
  File "D:\..........\Python39\lib\site-packages\paddle\fluid\core.py", line 297, in <module>
    raise e
  File "D:\..........\Python39\lib\site-packages\paddle\fluid\core.py", line 257, in <module>
    from .core_avx import *
ImportError: DLL load failed while importing core_avx: 找不到指定的模块。
```

**Comment by sandyhouse** [comment]
可以安装非avx版本的：python -m pip download paddlepaddle-gpu==2.1.2.post101 -f https://www.paddlepaddle.org.cn/whl/windows/mkl/noavx/stable.html --no-index --no-deps

或参考https://www.paddlepaddle.org.cn/install/quick?docurl=/documentation/docs/zh/install/pip/windows-pip.html

**Comment by N0I0C0K** [comment]
> 可以安装非avx版本的：python -m pip download paddlepaddle-gpu==2.1.2.post101 -f https://www.paddlepaddle.org.cn/whl/windows/mkl/noavx/stable.html --no-index --no-deps
> 
> 或参考https://www.paddlepaddle.org.cn/install/quick?docurl=/documentation/docs/zh/install/pip/windows-pip.html

但是我看了我CPU支持 AVX所以就很奇怪🥶

**Comment by sandyhouse** [comment]
https://blog.csdn.net/fuck_hang/article/details/114578986 参考这个试试？

**Comment by N0I0C0K** [comment]
> https://blog.csdn.net/fuck_hang/article/details/114578986 参考这个试试？

谢谢大佬，问题成功解决了🐮

**Comment by fhqsuhpv** [comment]
1. 查看系统版本
strings /usr/lib64/libstdc++.so.6 | grep GLIBCXX
GLIBCXX_3.4
GLIBCXX_3.4.1
GLIBCXX_3.4.2
GLIBCXX_3.4.3
GLIBCXX_3.4.4
GLIBCXX_3.4.5
GLIBCXX_3.4.6
GLIBCXX_3.4.7
GLIBCXX_3.4.8
GLIBCXX_3.4.9
GLIBCXX_3.4.10
GLIBCXX_3.4.11
GLIBCXX_3.4.12
GLIBCXX_3.4.13
GLIBCXX_3.4.14
GLIBCXX_3.4.15
GLIBCXX_3.4.16
GLIBCXX_3.4.17
GLIBCXX_3.4.18
GLIBCXX_3.4.19
GLIBCXX_DEBUG_MESSAGE_LENGTH

发现少了GLIBCXX_3.4.20，解决方法是升级libstdc++.

2. 
sudo yum provides libstdc++.so.6
Loaded plugins: fastestmirror, langpacks
Determining fastest mirrors
libstdc++-4.8.5-39.el7.i686 : GNU Standard C++ Library
Repo        : base
Matched from:
Provides    : libstdc++.so.6

3. 
cd /usr/local/lib64
# 下载最新版本的libstdc.so_.6.0.26
sudo wget http://www.vuln.cn/wp-content/uploads/2019/08/libstdc.so_.6.0.26.zip
unzip libstdc.so_.6.0.26.zip
# 将下载的最新版本拷贝到 /usr/lib64
cp libstdc++.so.6.0.26 /usr/lib64
cd  /usr/lib64
# 查看 /usr/lib64下libstdc++.so.6链接的版本
ls -l | grep libstdc++
libstdc++.so.6 ->libstdc++.so.6.0.19
# 删除/usr/lib64原来的软连接libstdc++.so.6，删除之前先备份一份
sudo rm libstdc++.so.6
# 链接新的版本
sudo ln -s libstdc++.so.6.0.26 libstdc++.so.6
# 查看新版本，成功
strings /usr/lib64/libstdc++.so.6 | grep GLIBCXX
...
GLIBCXX_3.4.18
GLIBCXX_3.4.19
GLIBCXX_3.4.20
GLIBCXX_3.4.21
GLIBCXX_3.4.22
GLIBCXX_3.4.23
GLIBCXX_3.4.24
GLIBCXX_3.4.25
GLIBCXX_3.4.26
GLIBCXX_DEBUG_MESSAGE_LENGTH
...

**Comment by lovely-fafa** [comment]
> > https://blog.csdn.net/fuck_hang/article/details/114578986 参考这个试试？
> 
> 谢谢大佬，问题成功解决了🐮

解决了，感激不尽
