### ISSUE TITLE
paddle.infer调用报错

### ISSUE THREAD

**Issue by bushidonggua** [PaddlePaddle/Paddle#3558]
调用paddle.infer的时候报：
F0817 19:56:11.205682  5200 ClassRegistrar.h:65] Check failed: mapGet(type, creatorMap_, &creator) Unknown class type: data
*** Check failure stack trace: ***  

没有更多信息的，请问下大概是什么地方异常呢？

**Comment by zhangweijiqn** [comment]
遇到了同样的问题，有人来帮忙解决一下吗？

**Comment by wanghaox** [comment]
https://github.com/PaddlePaddle/Paddle/issues/3533
请参考，检查机器环境

**Comment by zhangweijiqn** [comment]
已解，GPU设置问题，初始化添加如下代码：
`char* argv[] = {"--use_gpu=False"};
paddle_init(0, (char**)argv);`
