### ISSUE TITLE
Cannot load cudnn shared library. Cannot invoke method cudnnGetVersion.

### ISSUE THREAD

**Issue by aishangmaxiaoming** [PaddlePaddle/Paddle#35608]
<img width="874" alt="f34c0df21b0b2ea55d21d50268d96171" src="https://user-images.githubusercontent.com/67897601/132619197-4e5607df-02e1-43b3-93b6-929eb2273ccd.png">

**Comment by ceci3** [comment]
看起来是cudnn路径加载有问题，可以看下环境变量，是否cudnn路径指定有问题。以及cuda cudnn版本和paddle依赖的是否对应
