### ISSUE TITLE
【论文复现】稳定训练一段时间后突然显存溢出

### ISSUE THREAD

**Issue by CuberrChen** [PaddlePaddle/Paddle#35603]
- 标题：训练过程中存在不稳定现象，多次不确定时机显存突然上升造成溢出报错。
- 版本、环境信息：
    1）PaddlePaddle版本：2.1.2
    2）CPU：AiStudio 32G
    3）GPU：AiStudio Tesla 16G
    4）系统环境：ubuntu python3.7

- 训练信息
    1）单机，单卡
    2）显存信息 16G
    3）Operator信息
- 复现信息：已经稳定训练了一段时间之后，显存会在不确定的时机（分别在训练1个小时和4个小时以后）突然上升造成内存溢出。
- 问题描述：
SystemError('(Fatal) **Operator cast raises an paddle::memory::allocation::BadAlloc exception.**\nThe exception content is\n:ResourceExhaustedError: \n\nOut of memory error on GPU 0. Cannot allocate 1.342774GB memory on GPU 0, 15.198869GB memory has been allocated and available memory is only 820.357651MB.\n\nPlease check whether there is any other process using GPU 0.\n1. If yes, please stop them, or start PaddlePaddle on another GPU.\n2. If no, please decrease the batch size of your model. \n\n (at /paddle/paddle/fluid/memory/allocation/cuda_allocator.cc:79)\n. (at /paddle/paddle/fluid/imperative/tracer.cc:192)\n')
rpn error

Operator cast raises 看起来像是类型转换造成的错误？我在模型的前向推理过程中有类型转换的操作，.astype('int64')。 另外这里用了3D卷积。没有其他操作了。

**Comment by CuberrChen** [comment]
再一次训练，通过try捕获到异常位置代码：

`    result = paddle.zeros(x).astype(y.dtype) 
`
其中x就是一个list。y.dtype就是tensor float32数值类型。

**该代码位于model forward函数中调用的自定义函数中。x和y都是传入的参数。**

本次报错：
```

  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/math_op_patch.py", line 106, in astype
    return core.ops.cast(self, 'in_dtype', self.dtype, 'out_dtype', dtype)
SystemError: (Fatal) Operator cast raises an paddle::memory::allocation::BadAlloc exception.
The exception content is
:ResourceExhaustedError: 

Out of memory error on GPU 0. Cannot allocate 1.342774GB memory on GPU 0, 15.718506GB memory has been allocated and available memory is only 64.750000MB.
```

**Comment by CuberrChen** [comment]
通过将该行代码修改为'
`result = paddle.zeros(x,dtype=y.dtype) `
该错误消失。但是在同一小段代码内出现了其他错误，同样是内存溢出的错误。
也是在稳定一段时间后突然出现。
报错为pad3d造成的内存溢出。

**Comment by EnHuiPug** [comment]
好像没有解决啊
