### ISSUE TITLE
使用ernie_tiny进行下游任务推理时，从GPU设备拷贝tensor到CPU设备（.cpu()）速度很慢

### ISSUE THREAD

**Issue by pandaominggz** [PaddlePaddle/Paddle#35614]
- 版本、环境信息：
    1）PaddlePaddle版本：2.1.2
    2）CPU：Intel(R) Core(TM) i7-10700 CPU @ 2.90GHz   2.90 GHz
    3）GPU：NVIDIA GeForce RTX 2060 SUPER
    4）系统环境：Win10，Python 3.8.5

- 问题描述：请详细描述您的问题，同步贴出报错信息、日志/代码关键片段
使用ernie_tiny进行NER任务，当模型推理完毕，使用.cpu()从GPU设备拷贝tensor到CPU设备, batch_size=512, 句子length=30, num_label=9时，.cpu()花费的时间约为0.17秒，拷贝速度比pytorch .cpu()要慢很多
- 关键代码片段：
![企业微信截图_16311693686205](https://user-images.githubusercontent.com/57218399/132635248-0d50272b-5199-47dd-8c9e-cb0d4c01292b.png)

- 输出信息片段：
![企业微信截图_16311697786365](https://user-images.githubusercontent.com/57218399/132636007-9736eae0-7db1-4d5b-b8be-0c6ce9219979.png)

**Comment by zhiqiu** [comment]
hi, 调用`.cpu`的时候，前面的cuda kernel计算可能没有完成，所以你统计的时间是model计算+copy时间。
