### ISSUE TITLE
自己建的模型配置文件没有预训练权重怎么办？

### ISSUE THREAD

**Issue by zmdcs** [PaddlePaddle/Paddle#35622]
yolov4的主干网络替换成mobilenetv3，可是官网没有这个的预训练权重，我用yolo4的或者yolo3_mobilenetv3的预训练权重都不行，请问怎么能不设置预训练权重呢？

**Comment by ceci3** [comment]
不填的话应该就不设置了

**Comment by zmdcs** [comment]
可是会报错，必须有预训练权重



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年9月10日(星期五) 中午1:57
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [PaddlePaddle/Paddle] 自己建的模型配置文件没有预训练权重怎么办？ (#35622)





 
不填的话应该就不设置了
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by wangxinxin08** [comment]
没有pretrain_weights的话可以填成空字符串，即''，或者python tools/train.py -c configs/my_config.yml -o pretrain_weights=''
