### ISSUE TITLE
A100 运行错误

### ISSUE THREAD

**Issue by kuizhiqing** [PaddlePaddle/Paddle#35632]
运行环境：
Nvidia A100 

错误信息：
The exception content is
:parallel_for failed: cudaErrorNoKernelImageForDevice: no kernel image is available for execution on the device. (at /paddle/paddle/fluid/imperative/tracer.cc:192)

基础镜像：
nvidia/cuda：11.0-cudnn8-devel-ubuntu18.04 

paddle 版本：
pip3 install paddlepaddle_gpu-2.1.2-cp36-cp36m-manylinux1_x86_64.whl

**Comment by LielinJiang** [comment]
先检查下安装是否有问题：https://www.paddlepaddle.org.cn/install/quick?docurl=/documentation/docs/zh/install/pip/linux-pip.html
![image](https://user-images.githubusercontent.com/50691816/132806295-76fea1cb-03eb-4fd3-b268-b85467d06388.png)
我看用的cuda11.0的镜像，试试对应的版本。安装后，验证一下：
![image](https://user-images.githubusercontent.com/50691816/132806379-7f1221e3-4fea-4979-8dbf-84c722107ec9.png)

**Comment by kuizhiqing** [comment]
done, thx
