### ISSUE TITLE
develop版本动态修改tensor报错

### ISSUE THREAD

**Issue by HuimengZhang** [PaddlePaddle/Paddle#35638]
对模型中的 tensor 使用条件筛选出tensor中的一部分，对其值进行修改，
self._iou_classifier 和 self._iou_gamma 为常值参数
尝试了两种方法修改new_iou 中的部分值：
new_iou[new_iou<self._iou_classifier].set_value(paddle.pow(1 - new_iou[new_iou<self._iou_classifier], self._iou_gamma))
new_iou[new_iou>=self._iou_classifier].set_value(paddle.pow(new_iou[new_iou>=self._iou_classifier], self._iou_gamma))

forward过程中不会报错，但想修改的值不会改变

new_iou[new_iou<self._iou_classifier] = paddle.pow(1 - new_iou[new_iou<self._iou_classifier], self._iou_gamma)
new_iou[new_iou>=self._iou_classifier] = paddle.pow(new_iou[new_iou>=self._iou_classifier], self._iou_gamma)

可以成功修改值，但在backward()过程中报错：
![image](https://user-images.githubusercontent.com/30888016/132809512-1399ed77-69eb-46dc-b857-13cde3629bdd.png)

**Comment by LielinJiang** [comment]
new_iou<self._iou_classifier 这个可以先试一下转为(new_iou<self._iou_classifier).numpy() 行不行

**Comment by HuimengZhang** [comment]
这一步可以操作 在 develop版本里 new_iou[new_iou<self._iou_classifier] 这一步可以取到值 问题是无法赋值 即便在forward里赋值成功了 回退算梯度的过程中也会报错

**Comment by LielinJiang** [comment]
我知道可以赋值，我的意思是：你试试上面那个，看看会不会backward中报错

**Comment by hbwx24** [comment]
目前`new_iou[new_iou<self._iou_classifier]`这种getitem操作会创建一个新tensor，而非inplace操作。建议把 `new_iou[new_iou<self._iou_classifier].set_value(paddle.pow(1 - new_iou[new_iou<self._iou_classifier], self._iou_gamma))`改为 `new_iou.set_value(new_iou[new_iou<self._iou_classifier].set_value(paddle.pow(1 - new_iou[new_iou<self._iou_classifier], self._iou_gamma)))`试一下。

**Comment by HuimengZhang** [comment]
我把tensor 转成numpy 修改后再用set_value() 赋值回去 这样操作解决了上述问题，这么操作，现在看没有什么问题，不知道可不可以？
