### ISSUE TITLE
在模型定义中使用Sequential会出现模型结构一致但是训练效果不同的问题

### ISSUE THREAD

**Issue by BaiEJi** [PaddlePaddle/Paddle#35630]
- 版本、环境信息：
    1）PaddlePaddle版本：2.1.2
    4）系统环境：Aistudio

- 模型信息
    1）模型名称  Mnist
    2）使用数据集名称  paddle中的MNIST

当在class定义的模型中使用Sequential时，会发生模型结构一致，但是训练效果完全不同的情形
两个模型的定义如下图
![1](https://user-images.githubusercontent.com/54018278/132787070-85db498a-2dcc-4055-9805-06829530bf3e.png)
![2](https://user-images.githubusercontent.com/54018278/132787078-150eb7f6-7b84-4a84-b5b3-3eedb86e2e7d.png)
两个模型的结构打印：
![1-1](https://user-images.githubusercontent.com/54018278/132787090-f08d45f5-77f8-4775-bee6-a7abb8b089dd.png)
![2-1](https://user-images.githubusercontent.com/54018278/132787096-1f4c2b26-e49b-4200-90e8-761f7ef96e82.png)
第一个模型的训练结果
![image](https://user-images.githubusercontent.com/54018278/132787164-c09af8d9-fc21-4752-a738-7b366078c5e4.png)
第二个模型的训练结果
![image](https://user-images.githubusercontent.com/54018278/132787215-afab9009-40cb-492d-b75f-7be2c4324dc7.png)

请问为什么会导致这种问题，是因为不可以在模型定义中使用Sequential吗？如果是这样的话，请问有可以代替pytorch中ModuleList的工具吗

**Comment by LielinJiang** [comment]
按道理结果应该差不多，可以去掉dropout看看是不是随机引起的。torch中的ModuleList对应paddle中的nn.LayerList
