### ISSUE TITLE
开发机安装paddle之后，使用时出现`GLIBC_2.14' not found错误

### ISSUE THREAD

**Issue by DankoZhang** [PaddlePaddle/Paddle#35657]
您好，开发机上通过pip安装了cpu版本的paddle之后，import时出现了图片中的错误，请问怎么解决呢？
https://user-images.githubusercontent.com/40423569/132843659-282e0619-db1a-4aca-8c5d-26a0645bdb52.png

**Comment by LielinJiang** [comment]
应该是gcc版本的问题，推荐您使用gcc8.2的版本

**Comment by DankoZhang** [comment]
> 应该是gcc版本的问题，推荐您使用gcc8.2的版本

这个是什么意思，安装过程中没有涉及到gcc的问题，这个的安装流程是什么

**Comment by LielinJiang** [comment]
编译c代码用的编译器版本。你可以gcc --version看看
