### ISSUE TITLE
求问paddle v2怎么在训练时固定某些节点的参数使之不被更新

### ISSUE THREAD

**Issue by JayEworld** [PaddlePaddle/Paddle#3565]
我大概有这样的需求：
跑第一个pass的时候，只更新稀疏特征的参数，学习这部分特征的规律
跑第二个pass的时候，加入稠密特征，之前学习到的稀疏特征的参数不再被更新
求问应该怎么搞呢

**Comment by Xreki** [comment]
每个`layer`的参数可以设置自己的`learning_rate`，可将不希望更新的`layer`的参数的学习率设置成`0`，比如：
```python
fc_para_attr = paddle.attr.Param(learning_rate=0.)
fc1 = paddle.layer.fc(
            input=inputs,
            size=hid_dim,
            act=linear,
            param_attr=fc_para_attr,
            )
```

关于学习率设置的详情，可参考[#3302](https://github.com/PaddlePaddle/Paddle/issues/3302)

**Comment by JayEworld** [comment]
@Xreki 感谢回答。我现在清楚怎么设置不同层的learning rate了。
但是，**# 貌似还是不能根据不同pass设置不同的学习率**。
我其实是想：
跑第一个pass的时候，只更新稀疏特征的参数，学习这部分特征的规律
跑第二个pass的时候，加入稠密特征，之前学习到的稀疏特征的参数不再被更新
请问这有什么方法吗？

**Comment by luotao1** [comment]
学习过的参数不再更新，可以使用`param_attr = ParamAttr(is_static=True)`来设置。
那么只要控制is_static在第二个Pass变成True即可。

**Comment by JayEworld** [comment]
@luotao1 还是没太明白，网络结构包括param_attr，学习率，不是在训练之前就定义好的吗？怎么根据不同的pass设置不同的param_attr呢?

**Comment by typhoonzero** [comment]
暂时关闭此Issue了，如果仍存在问题，可以reopen
