### ISSUE TITLE
import paddle时，出现sysctl: unknown oid 'machdep.cpu.leaf7_features'

### ISSUE THREAD

**Issue by DankoZhang** [PaddlePaddle/Paddle#35658]
在本地运行paddle时，出现如下信息，这个是什么原因呢？
![image](https://user-images.githubusercontent.com/40423569/132844543-a8c59ba6-2277-48d9-9b48-1e011b9eb3d3.png)

**Comment by aizls** [comment]
I have the same problem with apple m1 chip.

```
❯ sysctl -n machdep.cpu.leaf7_features                    
sysctl: unknown oid 'machdep.cpu.leaf7_features'
```

```
❯ sysctl -a | grep machdep.cpu
machdep.cpu.brand_string: Apple M1
machdep.cpu.core_count: 8
machdep.cpu.cores_per_package: 8
machdep.cpu.logical_per_package: 8
machdep.cpu.thread_count: 8
```

**Comment by pangyoki** [comment]
你好，我们正在分析这个问题，有结论了反馈给你。目前看mac m1报的这个信息不影响paddle使用。

**Comment by pangyoki** [comment]
你好，这个PR已经解决了该问题：PR https://github.com/PaddlePaddle/Paddle/pull/34309
可以使用最新的paddle试试。
