### ISSUE TITLE
python训练配置脚本本地运行通过，MPI集群报错SIGFPE

### ISSUE THREAD

**Issue by youan1** [PaddlePaddle/Paddle#3567]
如题：相应的paddle脚本本地运行通过，MPI集群报错， job 链接为 
http://10.86.102.41:8900/fileview.html?path=/home/disk1/normandy/maybach/329760/
相应的脚本见附件

具体错误如下：

r>:+ python27-gcc482/bin/python conf/trainer_config.conf
Fri Aug 18 12:44:11 2017[1,93]<stderr>:Thread [140666704901888] Forwarding __fc_layer_4__, 
Fri Aug 18 12:44:11 2017[1,93]<stderr>:*** Aborted at 1503031451 (unix time) try "date -d @1503031451" if you are using GNU date ***
Fri Aug 18 12:44:11 2017[1,93]<stderr>:PC: @                0x0 (unknown)
Fri Aug 18 12:44:11 2017[1,93]<stderr>:*** SIGFPE (@0x7fef7e79ba90) received by PID 2986 (TID 0x7fef84fa3700) from PID 2121906832; stack trace: ***
Fri Aug 18 12:44:11 2017[1,93]<stderr>:    @     0x7fef84b7a160 (unknown)
Fri Aug 18 12:44:11 2017[1,93]<stderr>:    @     0x7fef7e79ba90 paddle::CpuMatrix::mul<>()
Fri Aug 18 12:44:11 2017[1,93]<stderr>:    @     0x7fef7e797ed3 paddle::CpuMatrix::mul()
Fri Aug 18 12:44:11 2017[1,93]<stderr>:    @     0x7fef7e5ae59a paddle::FullyConnectedLayer::forward()
Fri Aug 18 12:44:11 2017[1,93]<stderr>:    @     0x7fef7e61c562 paddle::NeuralNetwork::forward()
Fri Aug 18 12:44:11 2017[1,93]<stderr>:    @     0x7fef7e6104c3 paddle::GradientMachine::forwardBackward()
Fri Aug 18 12:44:12 2017[1,93]<stderr>:    @     0x7fef7e8381c4 GradientMachine::forwardBackward()
Fri Aug 18 12:44:12 2017[1,93]<stderr>:    @     0x7fef7e4e51d9 _wrap_GradientMachine_forwardBackward
Fri Aug 18 12:44:12 2017[1,93]<stderr>:    @           0x4b4cb9 PyEval_EvalFrameEx
Fri Aug 18 12:44:12 2017[1,93]<stderr>:    @           0x4b6b28 PyEval_EvalCodeEx
Fri Aug 18 12:44:12 2017[1,93]<stderr>:    @           0x4b5d10 PyEval_EvalFrameEx
Fri Aug 18 12:44:12 2017[1,93]<stderr>:    @           0x4b6b28 PyEval_EvalCodeEx
Fri Aug 18 12:44:12 2017[1,93]<stderr>:    @           0x4b5d10 PyEval_EvalFrameEx
Fri Aug 18 12:44:12 2017[1,93]<stderr>:    @           0x4b6b28 PyEval_EvalCodeEx
Fri Aug 18 12:44:12 2017[1,93]<stderr>:    @           0x4b5d10 PyEval_EvalFrameEx
Fri Aug 18 12:44:12 2017[1,93]<stderr>:    @           0x4b6b28 PyEval_EvalCodeEx
Fri Aug 18 12:44:12 2017[1,93]<stderr>:    @           0x4b5d10 PyEval_EvalFrameEx
Fri Aug 18 12:44:12 2017[1,93]<stderr>:    @           0x4b6b28 PyEval_EvalCodeEx
Fri Aug 18 12:44:12 2017[1,93]<stderr>:    @           0x4b6c52 PyEval_EvalCode
Fri Aug 18 12:44:12 2017[1,93]<stderr>:    @           0x4e1c7d PyRun_FileExFlags
Fri Aug 18 12:44:12 2017[1,93]<stderr>:    @           0x4e3501 PyRun_SimpleFileExFlags
Fri Aug 18 12:44:12 2017[1,93]<stderr>:    @           0x4159dd Py_Main
Fri Aug 18 12:44:12 2017[1,93]<stderr>:    @     0x7fef840d4bd5 __libc_start_main
Fri Aug 18 12:44:12 2017[1,93]<stderr>:    @           0x414b71 (unknown)
Fri Aug 18 12:44:12 2017[1,93]<stderr>:    @                0x0 (unknown)
Fri Aug 18 12:44:13 2017[1,93]<stderr>:./train.sh: line 239:  2986 Floating point exceptionpython27-gcc482/bin/python conf/trainer_config.conf
Fri Aug 18 12:44:13 2017[1,93]<stderr>:+ '[' 136 -ne 0 ']'
Fri Aug 18 12:44:13 2017[1,93]<stderr>:+ kill_pserver2_exit
Fri Aug 18 12:44:13 2017[1,93]<stderr>:+ grep -v grep
Fri Aug 18 12:44:13 2017[1,93]<stderr>:+ xargs kill -9

**Comment by youan1** [comment]
[config.zip](https://github.com/PaddlePaddle/Paddle/files/1233402/config.zip)
错误附件脚本

**Comment by Xreki** [comment]
请看看是否与#3047 中的问题类似。
另外，过往的issue中有很多`floating point exception`相关的，可先通过在issue中搜索，看是否能找到答案。
