### ISSUE TITLE
paddle2.1.2  ubuntu20.04 源码编译错误 undefined reference to `pthread_detach'

### ISSUE THREAD

**Issue by zgq91** [PaddlePaddle/Paddle#35689]
系统:ubuntu20.04  cuda11.0  cudnn8.0   paddle2.1.2 

执行命令 cmake .. -DPY_VERSION=3 \
        -DWITH_TESTING=OFF \
        -DWITH_MKL=ON \
        -DWITH_GPU=ON \
        -DON_INFER=ON

源码编译报错 "src.c:(.text+0x46): undefined reference to `pthread_create'
/usr/bin/ld: src.c:(.text+0x52): undefined reference to `pthread_detach'
/usr/bin/ld: src.c:(.text+0x63): undefined reference to `pthread_join'
collect2: error: ld returned 1 exit status
make[1]: *** [CMakeFiles/cmTC_a7bc8.dir/build.make:87: cmTC_a7bc8] Error 1
make[1]: Leaving directory '/home/gpu/Paddle/build/CMakeFiles/CMakeTmp'
make: *** [Makefile:121: cmTC_a7bc8/fast] Error 2"

**Comment by zhangting2020** [comment]
我使用你的编译命令，能够编译成功的。

pthread 库不是 Linux 系统默认的库，可能和你的环境有关系。请确认：
- 如果使用的是Paddle提供的编译镜像，提供一下使用的镜像
- 如果不是用的镜像，建议参考这篇文档，使用docker编译：https://www.paddlepaddle.org.cn/documentation/docs/zh/install/compile/linux-compile.html#span-id-compile-from-docker-docker-span
- 你还可以尝试自己安装pthread 库

**建议最好是参考官网提供的使用docker编译的文档，因为编译环境是准备好的**
