### ISSUE TITLE
Build error ::isnan and ::isinf has not been declared

### ISSUE THREAD

**Issue by pmajchrzak** [PaddlePaddle/Paddle#35687]
commit: 662230487cdaac10891d5e272175a81a4e234cb3
introduced a series of errors:
```
'::isinf' has not been declared
'::isnan' has not been declared
```
### OS
Ubuntu 18.04
### GCC
5.5.0-12ubuntu1
### CMAKE
cmake version 3.10.2
### CMAKE FLAGS
```
-DCMAKE_BUILD_TYPE=Release -DWITH_GPU=OFF -DWITH_MKLDNN=ON -DWITH_TESTING=ON -DWITH_PROFILER=OFF -DWITH_STYLE_CHECK=OFF -DON_INFER=ON -DWITH_INFERENCE_API_TEST=ON -DPY_VERSION=3.6
```

**Comment by zhangting2020** [comment]
I tried the latest develop, but I did not reproduce this error.

- commit: `5f31737`
- command: `cmake .. -DCMAKE_BUILD_TYPE=Release -DWITH_GPU=OFF -DWITH_MKLDNN=ON -DWITH_TESTING=ON -DWITH_PROFILER=OFF -DWITH_STYLE_CHECK=OFF -DON_INFER=ON -DWITH_INFERENCE_API_TEST=ON -DPY_VERSION=3.6`
- gcc: 8.2.0
- cmake: 3.10.2

**Comment by pmajchrzak** [comment]
But on gcc 5.5.0 still doesn't work after commit 662230487cdaac10891d5e272175a81a4e234cb3
previous commits build but next after mentioned one doesn't.
Should I assumed that paddle paddle is not supported for previous versions of gcc?

**Comment by zhangting2020** [comment]
Currently we recommend gcc 8.2.0. It has not been fully tested to show that it can work on gcc 5.5.0.
