### ISSUE TITLE
单张图像无法进行推理（已加上第一维度1），多张图片却可以

### ISSUE THREAD

**Issue by AIHHU** [PaddlePaddle/Paddle#35705]
用的AI studio，版本从1.8到2.1都用过了，预测单张图像时都会报错，强调：已经添加第一维度，多个图片（2个以上）图片预测没有问题
![L3FA1M$E$HV Y9NN~`{ ~NT](https://user-images.githubusercontent.com/66868438/133119734-82ce109b-5e2d-4a99-b846-8f1a3d93e194.png)

**Comment by danleifeng** [comment]
请问有可复现代码吗

**Comment by danleifeng** [comment]
如果还有任何问题，欢迎issue区提问
