### ISSUE TITLE
训练过程中断

### ISSUE THREAD

**Issue by Zhangts98** [PaddlePaddle/Paddle#35707]
系统： centos7
CUDA: 10.0
cudnn: 7.6.5
cpu: 支持avx
gpu: 4个1080 ti
![企业微信截图_16315845741829](https://user-images.githubusercontent.com/61573829/133182355-49f420dc-5951-4937-92ee-db8462a706fe.png)
![企业微信截图_16315849471253](https://user-images.githubusercontent.com/61573829/133182428-c0bf764e-9051-4fdf-be52-b778e1d2e817.png)
（gpu被占用可能是因为训练异常中断后，显存没有被释放）

conda 环境
  python: 3.7
  paddlepaddle:  paddlepaddle-gpu==2.0.0
  安装方式: pip install paddlepaddle-gpu==2.0.0 
![image](https://user-images.githubusercontent.com/61573829/133183822-5a1a0335-c4f5-4228-aa4e-9c324394162f.png)

4个gpu都被占满，但paddleocr代码并没有特地指定使用哪一个gpu。
训练一段时间后，出现错误：
![error](https://user-images.githubusercontent.com/61573829/133182338-7104473b-1e3a-4f77-9925-7acd38fab6d3.png)

请问这个错误是什么原因导致的？该如何解决啊？

**Comment by Zhangts98** [comment]
训练了将近一天才中断的。之前总是训练 1epoch + 几十iters 就卡住，验证数据读取器和数据没有问题后，卸载原来所有cuda，重新安装cuda10.0 和 paddlepaddle 后，这次训练了 2epoch + 几十iters 多， 又出现的这个错误。

**Comment by danleifeng** [comment]
看paddle安装完check_run的截图，只能识别到1个GPU，请参考提示，检查下，是不是nccl有问题，或者别的任务占用

**Comment by Zhangts98** [comment]
> 看paddle安装完check_run的截图，只能识别到1个GPU，请参考提示，检查下，是不是nccl有问题，或者别的任务占用

那个是因为训练中断后，显存没有释放，我就执行了run_check()，释放显存后run_check()是这样的。
![企业微信截图_16315886824270](https://user-images.githubusercontent.com/61573829/133210794-260e6832-0e51-4a69-aa52-dc36a9f3ec6e.png)

**Comment by tink2123** [comment]
数据读取有问题，再检测一下数据路径的配置吧，可以先跑一下单卡训练，跑通后再执行多卡。
