### ISSUE TITLE
The prediction results of ppyolo are all wrong when using mkldnn.

### ISSUE THREAD

**Issue by baoachun** [PaddlePaddle/Paddle#35717]
PR：https://github.com/PaddlePaddle/Paddle/pull/34332

**Comment by lidanqing-vv** [comment]
@jakpiase Hi, please look at this issue. slice caused ppyolo results wrong

**Comment by jakpiase** [comment]
Hi @baoachun, by "ppyolo" you mean ppyolo_r50vd_dcn_1x_coco or some other model?

**Comment by baoachun** [comment]
> Hi @baoachun, by "ppyolo" you mean ppyolo_r50vd_dcn_1x_coco or some other model?

Yes，ppyolo_r50vd_dcn_1x_coco.

**Comment by jakpiase** [comment]
Hi @baoachun my fix to this issue has been merged. Could you please tell me if this issue still exist?

**Comment by baoachun** [comment]
@jakpiase This problem has been solved.
