### ISSUE TITLE
Deploying swin_transformer will raise reshape2 mkldnn error.

### ISSUE THREAD

**Issue by baoachun** [PaddlePaddle/Paddle#35719]
![图片](https://user-images.githubusercontent.com/22114318/133208275-99503c1c-254e-439b-8902-12129c4c6baf.png)

![图片](https://user-images.githubusercontent.com/22114318/133208316-5a49ce5b-7181-44bb-b1e2-b26faeeb5fcf.png)

**Comment by lidanqing-vv** [comment]
@baoachun 
Hi, #35719, #35717 and #34723 three issues will be take care be @jakpiase

**Comment by jakpiase** [comment]
Hi @baoachun, could you please advise me how can I run swin_transformer?

**Comment by jakpiase** [comment]
I have reproduced this error, working on it now

**Comment by jakpiase** [comment]
Hi @baoachun my fix to this issue has been merged. Could you please tell me if this issue still exist?

**Comment by baoachun** [comment]
@jakpiase 
This problem has been solved.
