### ISSUE TITLE
为什么我按照官方教程里将voc格式数据转换成coco格式去训练，运行训练还是会下载官方的那个数据集？

### ISSUE THREAD

**Issue by zmdcs** [PaddlePaddle/Paddle#35723]
运行时甚至告诉我找不到dataset/coco这个文件夹，我是在static文件夹下运行的，coco文件夹下也按照教程在annotations底下放两个.json文件，imags文件夹下放.jpg文件。为什么还是会下数据集呢？

**Comment by danleifeng** [comment]
请问你跑的是paddleclas还是paddleocr还是paddledetection呢？请提供下训练代码的链接

**Comment by zmdcs** [comment]
paddle detection您想要的是训练语句还是配置yml文件，我只修改了num_classes为1，以及修改学习率为0.005




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年9月14日(星期二) 下午5:43
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [PaddlePaddle/Paddle] 为什么我按照官方教程里将voc格式数据转换成coco格式去训练，运行训练还是会下载官方的那个数据集？ (#35723)





 
请问你跑的是paddleclas还是paddleocr还是paddledetection呢？请提供下训练代码的链接
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by heavengate** [comment]
PaddleDetection的问题到PaddleDetection的库里提吧，https://github.com/PaddlePaddle/PaddleDetection/issues

**Comment by zmdcs** [comment]
我去了，压根没人回，你居心何在



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Kaipeng ***@***.***&gt;; 
发送时间: 2021年9月15日(星期三) 中午11:14
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [PaddlePaddle/Paddle] 为什么我按照官方教程里将voc格式数据转换成coco格式去训练，运行训练还是会下载官方的那个数据集？ (#35723)





 
PaddleDetection的问题到PaddleDetection的库里提吧，https://github.com/PaddlePaddle/PaddleDetection/issues
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
