### ISSUE TITLE
有没有模型编辑/裁剪工具？

### ISSUE THREAD

**Issue by my777777** [PaddlePaddle/Paddle#35731]
场景是这样：有个__model__模型文件包含了1000个op，现在想把前500个Op摘出来形成一个新的__model__文件，有没有类似的编辑工具可以让我直接把后500个Op从网络结构中删掉？或者有没有方法可以达到上述目的？

**Comment by hong19860320** [comment]
[split_model.tar.gz](https://github.com/PaddlePaddle/Paddle/files/7166678/split_model.tar.gz)
可以用这个工具，对预测模型进行分割

**Comment by my777777** [comment]
thx
