### ISSUE TITLE
paddle 2.1.0 golang demo编译出错，无法找到paddle_c_api.h

### ISSUE THREAD

**Issue by xox9001** [PaddlePaddle/Paddle#35744]
OS： ubuntu 20.04

paddle: 2.1.0

golang: 1.15

安装参数：按照cpp部署编译方式进行编译，已经成功生成paddle_inference_c_install_dir 等目录，但是无法找到paddle_c_api.h

代码目录： https://github.com/PaddlePaddle/Paddle/tree/release/2.1/go

按文档执行命令：go run demo/mobilenet.go

提示：

paddle/common.go :20 

 // #include <pd_inference_api.h>  :  no such file

======================================
我find了paddle_c_api.h，放入 demo/paddle_c/paddle/include 后，提示：

# github.com/paddlepaddle/paddle
cgo-gcc-prolog:53: 错误: 对‘PD_CpuMathLibraryNumThreads’未定义的引用
cgo-gcc-prolog:72: 错误: 对‘PD_CudnnEnabled’未定义的引用
cgo-gcc-prolog:215: 错误: 对‘PD_EnableTensorRtEngine’未定义的引用
cgo-gcc-prolog:245: 错误: 对‘PD_FractionOfGpuMemoryForPool’未定义的引用
cgo-gcc-prolog:264: 错误: 对‘PD_GpuDeviceId’未定义的引用
cgo-gcc-prolog:283: 错误: 对‘PD_IrOptim’未定义的引用
cgo-gcc-prolog:302: 错误: 对‘PD_IsValid’未定义的引用
cgo-gcc-prolog:321: 错误: 对‘PD_MemoryOptimEnabled’未定义的引用
cgo-gcc-prolog:340: 错误: 对‘PD_MemoryPoolInitSizeMb’未定义的引用
cgo-gcc-prolog:359: 错误: 对‘PD_MkldnnBfloat16Enabled’未定义的引用
cgo-gcc-prolog:378: 错误: 对‘PD_MkldnnEnabled’未定义的引用
cgo-gcc-prolog:397: 错误: 对‘PD_MkldnnQuantizerEnabled’未定义的引用
cgo-gcc-prolog:415: 错误: 对‘PD_ModelDir’未定义的引用
cgo-gcc-prolog:432: 错误: 对‘PD_NewAnalysisConfig’未定义的引用
cgo-gcc-prolog:450: 错误: 对‘PD_ParamsFile’未定义的引用
cgo-gcc-prolog:469: 错误: 对‘PD_ProfileEnabled’未定义的引用
cgo-gcc-prolog:487: 错误: 对‘PD_ProgFile’未定义的引用
cgo-gcc-prolog:546: 错误: 对‘PD_SpecifyInputName’未定义的引用
cgo-gcc-prolog:621: 错误: 对‘PD_TensorrtEngineEnabled’未定义的引用
cgo-gcc-prolog:640: 错误: 对‘PD_UseFeedFetchOpsEnabled’未定义的引用
cgo-gcc-prolog:659: 错误: 对‘PD_UseGpu’未定义的引用
cgo-gcc-prolog:87: 错误: 对‘PD_DeleteAnalysisConfig’未定义的引用
cgo-gcc-prolog:100: 错误: 对‘PD_DeletePass’未定义的引用
cgo-gcc-prolog:112: 错误: 对‘PD_DisableGlogInfo’未定义的引用
cgo-gcc-prolog:124: 错误: 对‘PD_DisableGpu’未定义的引用
cgo-gcc-prolog:136: 错误: 对‘PD_EnableCUDNN’未定义的引用
cgo-gcc-prolog:148: 错误: 对‘PD_EnableMKLDNN’未定义的引用
cgo-gcc-prolog:160: 错误: 对‘PD_EnableMemoryOptim’未定义的引用
cgo-gcc-prolog:172: 错误: 对‘PD_EnableMkldnnBfloat16’未定义的引用
cgo-gcc-prolog:184: 错误: 对‘PD_EnableMkldnnQuantizer’未定义的引用
cgo-gcc-prolog:196: 错误: 对‘PD_EnableProfile’未定义的引用
cgo-gcc-prolog:229: 错误: 对‘PD_EnableUseGpu’未定义的引用
cgo-gcc-prolog:504: 错误: 对‘PD_SetCpuMathLibraryNumThreads’未定义的引用
cgo-gcc-prolog:516: 错误: 对‘PD_SetInValid’未定义的引用
cgo-gcc-prolog:530: 错误: 对‘PD_SetModel’未定义的引用
cgo-gcc-prolog:563: 错误: 对‘PD_SwitchIrDebug’未定义的引用
cgo-gcc-prolog:577: 错误: 对‘PD_SwitchIrOptim’未定义的引用
cgo-gcc-prolog:591: 错误: 对‘PD_SwitchSpecifyInputNames’未定义的引用
cgo-gcc-prolog:605: 错误: 对‘PD_SwitchUseFeedFetchOps’未定义的引用
cgo-gcc-prolog:66: 错误: 对‘PD_GetInputName’未定义的引用
cgo-gcc-prolog:85: 错误: 对‘PD_GetInputNum’未定义的引用
cgo-gcc-prolog:105: 错误: 对‘PD_GetOutputName’未定义的引用
cgo-gcc-prolog:124: 错误: 对‘PD_GetOutputNum’未定义的引用
cgo-gcc-prolog:155: 错误: 对‘PD_NewPredictor’未定义的引用
cgo-gcc-prolog:49: 错误: 对‘PD_DeletePredictor’未定义的引用
cgo-gcc-prolog:140: 错误: 对‘PD_GetZeroCopyOutput’未定义的引用
cgo-gcc-prolog:171: 错误: 对‘PD_SetZeroCopyInput’未定义的引用
cgo-gcc-prolog:183: 错误: 对‘PD_ZeroCopyRun’未定义的引用
cgo-gcc-prolog:63: 错误: 对‘PD_NewZeroCopyTensor’未定义的引用
cgo-gcc-prolog:49: 错误: 对‘PD_DeleteZeroCopyTensor’未定义的引用
collect2: error: ld returned 1 exit status

**Comment by ForFishes** [comment]
您好，预测库编译问题。后续会找预测同学帮忙看看该问题。
