### ISSUE TITLE
paddle android capi 偶尔会出现这种异常

### ISSUE THREAD

**Issue by bushidonggua** [PaddlePaddle/Paddle#3575]
大概是什么原因造成的呢？
04-06 20:39:13.947 16286-16598/D /PaddlePaddle: F0406 20:39:13.959295 16286 utilities.cc:324] Check failed: !IsGoogleLoggingInitialized() You called InitGoogleLogging() twice!
04-06 20:39:13.947 16286-16394/ D /PaddlePaddle: *** Check failure stack trace: ***
04-06 20:39:13.947 16286-16394/ D /PaddlePaddle: *** Aborted at 1491482353 (unix time) try "date -d @1491482353" if you are using GNU date ***
04-06 20:39:13.957 16286-16394/ D/PaddlePaddle: PC: @        0x0 (unknown)

**Comment by Xreki** [comment]
是不是调用可`paddle_init`两次？或者是你其他的模块也有用到了`glog`？

**Comment by bushidonggua** [comment]
@Xreki  并没有用glog，init只在最开始进行了一次，有时候跑着跑着就挂了，就报的这个错

**Comment by peterzhang2029** [comment]
Similar to https://github.com/PaddlePaddle/Paddle/issues/4297
