### ISSUE TITLE
flask部署paddleocr，单GPU，单进程正常，多进程报错

### ISSUE THREAD

**Issue by Essence9999** [PaddlePaddle/Paddle#35758]
开启多进程代码：
![image](https://user-images.githubusercontent.com/66725845/133393753-e7977adb-f976-4a13-9bb4-c40d54b3dab8.png)

报错信息：
OSError: (External)  Cuda error(3), initialization error.
  [Advise: The API call failed because the CUDA driver and runtime could not be initialized. ] (at /paddle/paddle/fluid/platform/gpu_info.cc:308)

**Comment by ForFishes** [comment]
您好。请问你是多进程跑的是分布式吗？看报错是cuda驱动不匹配。

**Comment by Essence9999** [comment]
> 您好。请问你是多进程跑的是分布式吗？看报错是cuda驱动不匹配。

我想多个进程同时执行，所以用了多进程，GPU环境是没有问题的。单进程执行，gpu只用了8%，高并发就会任务阻塞。想尽可能多的同时执行任务，求指导（部署成了flask服务）
