### ISSUE TITLE
目前哪些算子支持在cpu上使用bf16推理

### ISSUE THREAD

**Issue by zhuguiqian** [PaddlePaddle/Paddle#35756]
目前哪些算子支持在cpu上使用bf16推理，推理的精度会有多少损失

**Comment by lidanqing-vv** [comment]
@zhuguiqian  https://github.com/PaddlePaddle/docs/blob/develop/doc/fluid/design/mkldnn/bfloat16/bfloat16.md
Please refer to bottom of this page.

**Comment by zhuguiqian** [comment]
thanks
