### ISSUE TITLE
xpu多卡训练报错

### ISSUE THREAD

**Issue by Avalon244** [PaddlePaddle/Paddle#35752]
paddlepaddle2.1.1
python3.7.4
按照官网模板写的mnist手写图片识别算法，跑单卡xpu可以训练，跑多卡时分别尝试了fleet的collective模式和paddle.distributed.nit_parallel_env()，前者报错no cuda device，后者报错Operator is not registered。请问如何解决？是xpu不支持多卡么？
![IMG_20210915_112811](https://user-images.githubusercontent.com/54314261/133379931-d37da1ef-451b-4092-bd7f-d3757a16f964.jpg)
![IMG_20210915_112900](https://user-images.githubusercontent.com/54314261/133379943-9e4ab5dd-a92e-420f-bfcd-f8fc10a5ad0d.jpg)
![IMG_20210915_112928](https://user-images.githubusercontent.com/54314261/133379952-fa583f87-222b-4934-befd-562507467bbc.jpg)

**Comment by wangxicoding** [comment]
跑的都是动态图吧，先设置一下device，`paddle.set_device('xpu')`

**Comment by Avalon244** [comment]
> 跑的都是动态图吧，先设置一下device，`paddle.set_device('xpu')`
已经设置过了

**Comment by wangxicoding** [comment]
这个代码吧https://www.paddlepaddle.org.cn/tutorials/projectdetail/2203224
![image](https://user-images.githubusercontent.com/10208305/133385222-c1f2bff7-a607-4c68-8b59-dd67309faec4.png)
我这边测试可以跑的呢

**Comment by wangxicoding** [comment]
你那边XPU的安装包是怎么安装的

**Comment by Avalon244** [comment]
> 
> 
> 这个代码吧https://www.paddlepaddle.org.cn/tutorials/projectdetail/2203224
> ![image](https://user-images.githubusercontent.com/10208305/133385222-c1f2bff7-a607-4c68-8b59-dd67309faec4.png)
> 我这边测试可以跑的呢

是这个代码，但是我改了一部分模型，把原来的多层卷积改成了两层Linear层去做一维数据分类，报错是报在了模型的第一层Linear。xpu版本是3.2，环境是别人提供的，xpu单卡可以跑，是xpu安装的错误导致的么？有查询的方法么？谢谢

> 
> 
> 这个代码吧https://www.paddlepaddle.org.cn/tutorials/projectdetail/2203224
> ![image](https://user-images.githubusercontent.com/10208305/133385222-c1f2bff7-a607-4c68-8b59-dd67309faec4.png)
> 我这边测试可以跑的呢

是这个代码，但是我改了一部分模型，把原来的多层卷积改成了两层Linear层去做一维数据分类，报错是报在了模型的第一层Linear。xpu版本是3.2，环境是别人提供的，xpu单卡可以跑，是xpu安装的错误导致的么？有查询的方法么？谢谢

**Comment by wangxicoding** [comment]
https://github.com/PaddlePaddle/Paddle/pull/30671
按照我这个PR里面的example跑一下试试

**Comment by wangxicoding** [comment]
我怀疑是xpu的paddle包有问题，编译的时候没有开distributed选项
