### ISSUE TITLE
在parameters model中是否保存了关于learning rate的相关信息

### ISSUE THREAD

**Issue by cbtpkzm** [PaddlePaddle/Paddle#3576]
在parameters model中会保存关于learning rate的相关信息吗？
比如当前的学习率矩阵，已经训练的样本个数这些信息等

以及假设我在一个实验中的某个pass后中断了，中断时候的learning rate假设是0.0004，重起的时候通过parameters.from_tar重新获得参数，以及通过paddle.optimizer.Adam(learning_rate=0.0004, ...)设置断点时候的learning rate，在实验接着train的时候是否会当作现在的sample数是0，从而导致重起的实验learning rate变化与之前的不一致？

**Comment by lcy-seso** [comment]
1.  保存下来的model中不含有学习率信息。对自适应学习率算法，想做到无损训练需要保存的不仅仅有学习率矩阵，还有momentum，以及各个学习算法各自有一些需要计算的历史现象，存储量会是模型参数的 2 ~ 3 倍，目前不知此。
2. 使用自适应学习率算法中断后重启，由于丢失了历史信息，学习率会出现差异。

**Comment by cbtpkzm** [comment]
清楚了，感谢回答
