### ISSUE TITLE
GPU能否像CPU那样开启多进程预测，提高GPU利用率；批量预测，每次执行，GPU利用率最多10%

### ISSUE THREAD

**Issue by Essence9999** [PaddlePaddle/Paddle#35786]
执行predict_system.py时，批量图片ocr识别，但GPU的利用率最高不超过10%；
![image](https://user-images.githubusercontent.com/66725845/133538966-b1ae9891-d8b9-4d89-af38-1271607f7d40.png)
如何提高GPU使用率？
单张图片测试0.3s；50个进程同时访问，平均耗时7s
![image](https://user-images.githubusercontent.com/66725845/133539167-bf5abeb8-d419-4c01-82cb-12e3ef10cf07.png)
GPU能否像CPU那样，开启多进程，充分利用GPU，降低平均耗时？请问有没有什么好的解决方案？

**Comment by ShiningZhang** [comment]
您好，可以参考示例进行预测部署，有多种形式可供选择
https://paddle-inference.readthedocs.io/en/latest/quick_start/cpp_demo.html

**Comment by tanzhen-byte** [comment]
GPU到底能不像CPU那样开启多进程预测？老哥你解决了么？
