### ISSUE TITLE
paddle预测库在windows10 系统下总是出现错误提示

### ISSUE THREAD

**Issue by dlkht** [PaddlePaddle/Paddle#35796]
欲将transformer c++ demo 于windows系统下运行，做如下操作
1.下载或源码编译(vs2017)paddle预测库（paddle_inference.lib）
2.将https://github.com/PaddlePaddle/PaddleNLP/tree/develop/examples/machine_translation/transformer/deploy/cpp的demo移植到vs2017下
3.做了所有设置之后，执行生成命令，提示如下

错误	LNK1120	4 个无法解析的外部命令	transformer_e2e	D:\paddle\PaddleNLP\cxx_server2\build\Release\transformer_e2e.exe	1	

错误	LNK2019	无法解析的外部符号 "__declspec(dllimport) public: class std::basic_ostream<char,struct std::char_traits<char> > & __cdecl std::basic_ostream<char,struct std::char_traits<char> >::flush(void)" (__imp_?flush@?$basic_ostream@DU?$char_traits@D@std@@@std@@QEAAAEAV12@XZ)，该符号在函数 "class std::basic_ostream<char,struct std::char_traits<char> > & __cdecl std::operator<<<struct std::char_traits<char> >(class std::basic_ostream<char,struct std::char_traits<char> > &,char const *)" (??$?6U?$char_traits@D@std@@@std@@YAAEAV?$basic_ostream@DU?$char_traits@D@std@@@0@AEAV10@PEBD@Z) 中被引用	transformer_e2e	D:\paddle\PaddleNLP\cxx_server2\build\transformer_e2e.obj	1	

错误	LNK2019	无法解析的外部符号 "__declspec(dllimport) public: class std::locale __cdecl std::basic_streambuf<char,struct std::char_traits<char> >::getloc(void)const " (__imp_?getloc@?$basic_streambuf@DU?$char_traits@D@std@@@std@@QEBA?AVlocale@2@XZ)，该符号在函数 "public: class std::basic_filebuf<char,struct std::char_traits<char> > * __cdecl std::basic_filebuf<char,struct std::char_traits<char> >::open(char const *,int,int)" (?open@?$basic_filebuf@DU?$char_traits@D@std@@@std@@QEAAPEAV12@PEBDHH@Z) 中被引用	transformer_e2e	D:\paddle\PaddleNLP\cxx_server2\build\transformer_e2e.obj	1	

错误	LNK2019	无法解析的外部符号 "__declspec(dllimport) public: int __cdecl std::basic_streambuf<char,struct std::char_traits<char> >::snextc(void)" (__imp_?snextc@?$basic_streambuf@DU?$char_traits@D@std@@@std@@QEAAHXZ)，该符号在函数 "class std::basic_istream<char,struct std::char_traits<char> > & __cdecl std::getline<char,struct std::char_traits<char>,class std::allocator<char> >(class std::basic_istream<char,struct std::char_traits<char> > &&,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > &,char)" (??$getline@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@YAAEAV?$basic_istream@DU?$char_traits@D@std@@@0@$$QEAV10@AEAV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@0@D@Z) 中被引用	transformer_e2e	D:\paddle\PaddleNLP\cxx_server2\build\transformer_e2e.obj	1	

错误	LNK2019	无法解析的外部符号 "__declspec(dllimport) public: __int64 __cdecl std::basic_streambuf<char,struct std::char_traits<char> >::sputn(char const *,__int64)" (__imp_?sputn@?$basic_streambuf@DU?$char_traits@D@std@@@std@@QEAA_JPEBD_J@Z)，该符号在函数 "class std::basic_ostream<char,struct std::char_traits<char> > & __cdecl std::operator<<<struct std::char_traits<char> >(class std::basic_ostream<char,struct std::char_traits<char> > &,char const *)" (??$?6U?$char_traits@D@std@@@std@@YAAEAV?$basic_ostream@DU?$char_traits@D@std@@@0@AEAV10@PEBD@Z) 中被引用	transformer_e2e	D:\paddle\PaddleNLP\cxx_server2\build\transformer_e2e.obj	1	

请问怎么解决呢？谢谢！

**Comment by ShiningZhang** [comment]
您好，请参考windows预测部署示例进行设置，文档如下
https://paddle-inference.readthedocs.io/en/latest/demo_tutorial/x86_windows_demo.html
另可以检查下载文档：https://paddle-inference.readthedocs.io/en/latest/user_guides/download_lib.html#windows
查看下载库版本与下载的transformer c++ demo代码版本是否一致
