### ISSUE TITLE
The prediction result of OCR model is wrong by using mkldnn.

### ISSUE THREAD

**Issue by baoachun** [PaddlePaddle/Paddle#35794]
![图片](https://user-images.githubusercontent.com/22114318/133555612-fe3e9c56-5e71-4f0c-b532-5670c5a0a1df.png)

Download `ch_PP-OCRv2_rec`, `ch_ppocr_mobile_v2.0_rec` and `ch_ppocr_server_v2.0_rec` from https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.3/doc/doc_en/models_list_en.md.

Then
`git clone https://github.com/PaddlePaddle/PaddleOCR.git`
`cd PaddleOCR`
`git checkout develop`
`python3 tools/infer/predict_rec.py --image_dir=doc/imgs_words/ch/word_1.jpg --rec_model_dir=./rec_models_ch/ch_PP-OCRv2_rec_infer --rec_image_shape="3, 32, 100" --rec_char_type="ch" --rec_char_dict_path="./ppocr/utils/ppocr_keys_v1.txt" --rec_algorithm=CRNN --use_gpu=False --use_tensorrt=False --enable_mkldnn=True --rec_batch_num=1`

**Comment by jakpiase** [comment]
Hi @baoachun, I have downloaded ch_PP-OCRv2_rec_infer.tar, I have also changed filenames from "inference..pdiparams" to "params" and from "inference.pdmodel" to "model" and I am getting "list index out of range" error when I run 
 `python tools/infer/predict_rec.py --image_dir=doc/imgs_words/ch/word_1.jpg --rec_model_dir=./rec_models_ch/ch_PP-OCRv2_rec_infer --rec_image_shape="3, 32, 100" --rec_char_type="ch" --rec_char_dict_path="./ppocr/utils/ppocr_keys_v1.txt" --rec_algorithm=CRNN --use_gpu=False --use_tensorrt=False --enable_mkldnn=True --rec_batch_num=1`
Could you please give me more detailed steps how to reproduce this issue?

**Comment by jakpiase** [comment]
Hi @baoachun, @JiaXiao243 sent a screenshot in #35781 that disabling reshape and squeeze ops fixes both ch_PP-OCRv2_rec_infer and shufflenetv2, can I close these two issues?

**Comment by baoachun** [comment]
@jakpiase 
Yep，thank you.
