### ISSUE TITLE
some changes affect the v2 training accuracy

### ISSUE THREAD

**Issue by dzhwinter** [PaddlePaddle/Paddle#3580]
the change is introduced between July 20 and the current develop branch  in Aug.18 [ac6635](https://github.com/PaddlePaddle/Paddle/commit/ac663353e2909d9d88166bb88f5bcaf8b6fbdd10)  the model training accuracy cannot reach the expectation.
@emailweixu  reported this bug.

**Comment by wangkuiyi** [comment]
Is this issue about a bug?

Is it about random failure of a unit test?

**Comment by emailweixu** [comment]
I have some local change to train my model. I am git-bisecting to locate the problem.

**Comment by dzhwinter** [comment]
sure. @wangkuiyi I will follow this issue. 
 @emailweixu  `git bisect` is a useful command to find changed file. And also `git whatchanged --since="4 day ago" -p`, `git diff HEAD 'HEAD@{4 weeks ago}' -- some/file/path/file.ext`  to find the potential changed file. Not very accurate, we can use them to find some clues.

**Comment by emailweixu** [comment]
It turns out that this is most likely because of the randomness of the training. There are some chance (25%) that my model cannot train successfully. So I will close this issue.

**Comment by dzhwinter** [comment]
that's weird.  It seems we need to improve the stability of randomness. Did you set the same random seed manually? if so, we need more stable randomness method.

**Comment by emailweixu** [comment]
Yes, I set a fixed random seed.
