### ISSUE TITLE
scale_sparse_gradient_with_batch_size_

### ISSUE THREAD

**Issue by Buptguozijun** [PaddlePaddle/Paddle#35810]
为使您的问题得到快速解决，在建立Issues前，请您先通过如下方式搜索是否有相似问题:【搜索issue关键字】【使用labels筛选】【官方文档】
麻烦问下，训练更新梯度的代码里https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/fluid/framework/fleet/fleet_wrapper.cc#L283
这一行的代码含义为：所有的梯度都会和batchsize相乘，请问下这样做的含义是什么呢？

**Comment by Thunderbrook** [comment]
这是一个相对定制化的功能，可以通过config关闭
