### ISSUE TITLE
【论文复现】 paddle.matmul 与 torch.matmul在不同环境下误差不一样。

### ISSUE THREAD

**Issue by JunnYu** [PaddlePaddle/Paddle#35819]
- 版本、环境信息：
- 环境1
    1）RTX3090     PaddlePaddle版本：2.1.2+cu11.2       Pytorch版本1.9.0+cu11.1
- 环境2
    2）V100-32G     PaddlePaddle版本：2.1.2+cu10.2       Pytorch版本1.9.0+cu10.2

# paddle.matmul 与 torch.matmul在上述环境下，对于`特定的输入`产生误差！
代码链接：链接：https://pan.baidu.com/s/1dIKVz2DIIEOzeeOH4QL1AQ 
提取码：1iex
## compare1.ipynb 例子（从模型1中抽取到的特定输入和权重）
```python
# 3090条件下：
平均误差：tensor(4.2843e-06)
最大误差：tensor(3.6240e-05)
# V100条件下：
平均误差：tensor(0)
最大误差：tensor(0)
```
## compare2.ipynb 例子（从模型2中抽取到的特定输入和权重）
```python
# 3090条件下：
平均误差：tensor(0)
最大误差：tensor(0)
# V100条件下：
平均误差：tensor(2.2502307e-07)
最大误差：tensor(3.33786e-06)
```
# 问题：
- 对于compare1.ipynb，同样的输入和权重，3090条件存在很大误差，而v100却没有误差。
- 对于compare2.ipynb，同样的输入和权重，3090条件没有误差，而v100却存在误差。
- 最开始是只在3090条件下测试，然后为了消除30系列显卡和不同cuda版本带来的影响。才在V100的相同cuda版本下进行测试，最终发现了这么奇怪的现象，很困惑。
- 我的理解在V100相同cuda的配置下，matmul的结果应该完全一致！！！！！但是他的计算结果误差竟然跟输入相关。
- 不要看当前这误差只有这么点，经过好多次的matmul后，误差会变得越来越大！

**Comment by yingyibiao** [comment]
mark

**Comment by yingyibiao** [comment]
@ZeyuChen 这个matmul我们需要彻底理清楚到底有哪些问题
