### ISSUE TITLE
paddle.grad求三阶导报错

### ISSUE THREAD

**Issue by ZhangFengshun** [PaddlePaddle/Paddle#35844]
代码如下：
<img width="838" alt="屏幕截图 2021-09-17 203007" src="https://user-images.githubusercontent.com/89072581/133783616-59222de0-6ab0-4ed7-935c-33e076b887bd.png">
报错信息如下：
<img width="842" alt="屏幕截图 2021-09-17 203108" src="https://user-images.githubusercontent.com/89072581/133783653-57a71d48-9218-4f8b-8d7a-02089ace0094.png">
相似代码用torch不报错，如何使用paddle的自动微分求解三阶导数？

**Comment by yaoxuefeng6** [comment]
你好 这个错误是因为使用的elementwise_mul op没有对应的三阶导数op，paddle暂时还没有实现， 我们评估下这个需求哈

**Comment by veyron95** [comment]
您好 elementwise_mul op 三阶导数已支持，将在后续版本中发布，或者您可以使用 develop 分支体验此功能
