### ISSUE TITLE
建议增加 paddle.transpose 对 bool 类型数据的支持

### ISSUE THREAD

**Issue by morgan-bc** [PaddlePaddle/Paddle#35855]
欢迎您对PaddlePaddle提出建议，非常感谢您对PaddlePaddle的贡献！
在留下您的建议时，辛苦您同步提供如下信息：
- 版本、环境信息
1）PaddlePaddle版本：2.1.2
2）CPU/GPU：
3）系统环境：请您描述系统类型、版本，例如Mac OS 10.14
注：您可以通过执行[summary_env.py](https://github.com/PaddlePaddle/Paddle/blob/develop/tools/summary_env.py)获取以上信息。
- 复现信息：目前 paddle.transpose 不持支对 bool 类型数据操作，例如
```python
a = paddle.rand([1, 5, 100, 100])
m = a > 0.6
m1 = np.transpose(m, (0, 2, 3, 1))
```
上面的代码会出现如下错误
```
RuntimeError: (NotFound) Operator transpose2 does not have kernel for data_type[bool]:data_layout[ANY_LAYOUT]:place[CPUPlace]
```

- 建议描述：建议增加 paddle.transpose 对 bool 类型数据的支持

**Comment by iclementine** [comment]
已经收到反馈，我们近期就加一下。谢谢！
