### ISSUE TITLE
CosSimOp.cpp:54] Check failed: square_sum_x > 0 && square_sum_y > 0

### ISSUE THREAD

**Issue by JayEworld** [PaddlePaddle/Paddle#3586]
报这个错，请问是为什么呢？该怎么解决呢
```text
I0820 15:06:07.562870 12349 Util.cpp:166] commandline:  --use_gpu=False 
I0820 15:06:08.136152 12349 GradientMachine.cpp:85] Initing parameters..
I0820 15:06:12.327430 12349 GradientMachine.cpp:92] Init parameters done.
F0820 15:06:13.919644 12349 CosSimOp.cpp:54] Check failed: square_sum_x > 0 && square_sum_y > 0 
*** Check failure stack trace: ***
    @     0x7ff500468e6d  google::LogMessage::Fail()
    @     0x7ff50046c91c  google::LogMessage::SendToLog()
    @     0x7ff500468993  google::LogMessage::Flush()
    @     0x7ff50046de2e  google::LogMessageFatal::~LogMessageFatal()
    @     0x7ff5002e3380  paddle::CosSimForward<>()
    @     0x7ff5002e79e1  paddle::CosSimForwardFunc<>::calc()
    @     0x7ff500210a86  paddle::CosSimLayer::forward()
    @     0x7ff5002cf690  paddle::NeuralNetwork::forward()
    @     0x7ff5002ab883  paddle::GradientMachine::forwardBackward()
    @     0x7ff5004447ab  GradientMachine::forwardBackward()
    @     0x7ff50013b38e  _wrap_GradientMachine_forwardBackward
    @           0x4a9e33  PyEval_EvalFrameEx
    @           0x4ad70d  PyEval_EvalCodeEx
    @           0x4aa88c  PyEval_EvalFrameEx
    @           0x4ad70d  PyEval_EvalCodeEx
    @           0x4aa88c  PyEval_EvalFrameEx
    @           0x4ad70d  PyEval_EvalCodeEx
    @           0x4aa88c  PyEval_EvalFrameEx
    @           0x4ad70d  PyEval_EvalCodeEx
    @           0x4aa88c  PyEval_EvalFrameEx
    @           0x4ad70d  PyEval_EvalCodeEx
    @           0x4ad842  PyEval_EvalCode
    @           0x4d64c2  PyRun_FileExFlags
    @           0x4d7839  PyRun_SimpleFileExFlags
    @           0x416edd  Py_Main
    @     0x7ff5082f6bd5  __libc_start_main
    @           0x415f91  (unknown)
    @              (nil)  (unknown)
Aborted
```

**Comment by JayEworld** [comment]
模型代码
197     hidden_layer_user_size = 512
198     hidden_layer_user = paddle.layer.fc(input=[user_prefer_emb, user_forum_emb, user_fdir_emb, user_sdir_emb, user_kw_emb, user_cls_emb, user_fcate_emb, user_scate_emb,     user_tag_emb], \
199             size=hidden_layer_user_size, \
200             act=paddle.activation.Tanh(), \
201             param_attr=paddle.attr.Param(initial_std=(1.0/math.sqrt(hidden_layer_user_size))))
202     vector_layer_user_size = 256
203     vector_layer_user = paddle.layer.fc(name="vector_layer_user", \
204             input=hidden_layer_user, size=vector_layer_user_size, \
205             act=paddle.activation.Tanh(), \
206             param_attr=paddle.attr.Param(initial_std=(1.0/math.sqrt(vector_layer_user_size))))
207 
208     hidden_layer_video_size = 512
209     hidden_layer_video = paddle.layer.fc(input=[video_forum_emb, video_fdir_emb, video_sdir_emb, video_kw_emb, video_cls_emb, video_fcate_emb, video_scate_emb, video_tag    _emb], \
210             size=hidden_layer_video_size, \
211             act=paddle.activation.Tanh(), \
212             param_attr=paddle.attr.Param(initial_std=(1.0/math.sqrt(hidden_layer_video_size))))
213     vector_layer_video_size = 256
214     vector_layer_video = paddle.layer.fc(name="vector_layer_video", \
215             input=hidden_layer_video, size=vector_layer_video_size, \
216             act=paddle.activation.Tanh(), \
217             param_attr=paddle.attr.Param(initial_std=(1.0/math.sqrt(vector_layer_video_size))))
218     
219     output = paddle.layer.cos_sim(a=vector_layer_user, b=vector_layer_video, size=1, scale=1)    
220     cost = paddle.layer.mse_cost(input=output, label=lbl)

**Comment by lcy-seso** [comment]
请在贴代码的时候去掉行号，使用markdown 的代码块标记 format 一下。现在这样贴出来的代码，令人非常难以阅读。

**Comment by lcy-seso** [comment]
请确保data_layer输入的向量中没有全0。

**Comment by peterzhang2029** [comment]
Closing due to low activity. Feel free to reopen it.
