### ISSUE TITLE
如何动量更新模型参数

### ISSUE THREAD

**Issue by FesianXu** [PaddlePaddle/Paddle#35860]
paddle 2.0 中的静态图是否可以动量更新参数，比如假设时刻t时的网络A的参数为W_{t}，网络B的参数为C_{t}, 那么下一个时刻的参数更新为：  W_{t+1} = mC_{t} + (1-m)W_{t}。

**Comment by iclementine** [comment]
静态图需要实现这个功能有点麻烦。

因为参数只是对 optimizer 而言 mutable 的，而且参数更新是自动操作的。torch 实现这个功能的时候，也是直接对参数的 data 进行操作。

如果需要实现这样的功能，你或许可以构建一个独立的 program， 在其中产生一个 loss, 使得其更新公式是如上所述的方式
