### ISSUE TITLE
安装完成后，执行paddle.utils.run_check()一直无反应

### ISSUE THREAD

**Issue by DejaYang** [PaddlePaddle/Paddle#35865]

**Comment by iclementine** [comment]
是使用最新的版本吗？

正常执行的话会检测单卡和多卡上的运行是否正常，输出结果类似如此。
<img width="1000" alt="图片" src="https://user-images.githubusercontent.com/16222986/134276248-7ad5c239-8357-4c0c-aa67-c370f5a3e0f2.png">

可以试试先观察一下本地 cuda 版本和所安装的 paddle 对应的 cuda 版本是否一致。
