### ISSUE TITLE
Paddle中预测accuracy的计算中是否有类似于keras中的categorical_accuracy函数API的功能可以直接进行标签为独热编码的计算

### ISSUE THREAD

**Issue by RabbitBoiling** [PaddlePaddle/Paddle#35880]
目前我在使用Paddle的低阶API进行模型训练时，训练过程中需要计算accuracy，但是我的数据标签是独热编码形式的，而paddle提供的paddle.metric.accuracy要求数据标签为具体值（input的shape为 [sample_number,class_dim]，label的shape为[sample_number, 1] ），我无法直接计算accuracy，在keras中提供了categorical_accuracy函数可以直接对数据标签为独热编码形式的计算accuracy，此外还提供了sparse_categorical_accuracy，top_k_categorical_accuracy，sparse_top_k_categorical_accuracy等大量计算accuracy的函数，我在Paddle的API中均未找到。
请帮忙看下是我未找到的原因还是Paddle目前暂时不支持这些功能，谢谢！

**Comment by huangjun12** [comment]
目前还没有类似API，建议可以根据index将独热标签转换为具体标签值。

**Comment by RabbitBoiling** [comment]
我目前计算独热码标签的accuracy，采用的方法为：返回预测值、数据标签值得独热码的向量中的最大元素的索引值，以此来确定类别，并计算accuracy，虽然也能实现计算accuracy的效果，但使用起来不是很方便，希望Paddle能够在后续的版本中多加入一些相关的accuracy计算函数API。
