### ISSUE TITLE
visualdl 多个 log 文件如何合成一个展示

### ISSUE THREAD

**Issue by yt605155624** [PaddlePaddle/Paddle#35899]
训练中途断掉了，重新训练之后生成了新的 visualdl log , 之前的 log 和新生成的 log 还是在一个文件夹里面的，运行 visualdl 之后只展示后半段的 loss，请问如何同时展示多个 log，把曲线接起来呢？（是现在训练 log 已经写完的前提下，不是重新训练的时候指定 logfile）

**Comment by JZ-LIANG** [comment]
这种情况只能自己写个parser 读取每个log 中的loss 成多个 numpy array，再把narray concate起来了。。。。。
