### ISSUE TITLE
acc预测时报错

### ISSUE THREAD

**Issue by Sunyingbin** [PaddlePaddle/Paddle#35902]
1）PaddlePaddle版本：请提供您的PaddlePaddle版本号（如1.1）或CommitID
    2）CPU：paddle2.1 python 3.7
    3）系统环境：mac os
    预测模型，输入为[1, 72] 输出[1, 24] batchsize：10
        for batch_id, data in enumerate(test_loader()):
            x_data = data[0]
            y_data = data[1]
            predicts = model(x_data)
            # 获取acc
            acc = paddle.metric.accuracy(predicts, y_data)

报错如下：
ValueError: (InvalidArgument) ShapeError: label's second dimension of AccuracyOp must be 1. But received label's second dimension is = 24, label's shape = [10, 24]
  [Hint: Expected label_dim[1] == 1, but received label_dim[1]:24 != 1:1.] (at /home/Paddle/paddle/fluid/operators/metrics/accuracy_op.cc:69)
  [operator < accuracy > error]

为什么当输出dim[1]不是1，而是24的时候，怎么处理？只能自己修改y_data维度吗？paddle.metric.accuracy这个方法为啥不行啊，他为啥不能自动处理？

**Comment by JZ-LIANG** [comment]
输入数据格式是根据用户业务变的，框架侧无法提前预知并做假设，需要用户根据自身数据先处理好

**Comment by JZ-LIANG** [comment]
可以参考https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/io/DataLoader_cn.html#dataloader
