### ISSUE TITLE
在jetson nx上部署paddleseg下的用自己的数据集训练好的bisenetV2模型，部署后预测一张图需要几秒，怎么提高预测速度。

### ISSUE THREAD

**Issue by huangwan-jiayi** [PaddlePaddle/Paddle#35901]
我最近成功把我自己训练的paddleseg框架下的模型 用paddle inference c++ 部署到了jetson nx 上了 可是预测的时间需要几秒，完全达不到实时的要求 ，请问一下，你有部署这方面的经验吗，是我需要修改一下代码的什么部分，预测速度才会达到网上说的那么高呢？开启tensorrt后预测速度还会更慢。
![image](https://user-images.githubusercontent.com/71338215/134280613-fcabe162-3350-4420-abb8-4e9ca65285c6.png)
![image](https://user-images.githubusercontent.com/71338215/134280614-f902d254-b3d1-4073-89ee-eebdbed0fced.png)
![image](https://user-images.githubusercontent.com/71338215/134280624-0d0ca2aa-2bd0-4854-bd8c-82e675067764.png)
![image](https://user-images.githubusercontent.com/71338215/134280631-75b0bb30-2594-41a5-a8d0-929d37ad6e23.png)

以上是全部c++代码，输入预测图像大小为1920*1080.

**Comment by huangwan-jiayi** [comment]
这是我的环境信息，
![image](https://user-images.githubusercontent.com/71338215/134445560-3883d0e9-b4b1-4d70-9e78-3132e1694b6d.png)
![image](https://user-images.githubusercontent.com/71338215/134445766-7aa9af44-435f-4959-aaa4-bcde7d34276f.png)

**Comment by wangye707** [comment]
@huangwan-jiayi  trt精度改为fp16模式(PrecisionType::kHalf)，然后最好加上warm up预热。
