### ISSUE TITLE
为什么我进去文本分类时模型 1个epoch 的最后一个BATCH就 异常结束了

### ISSUE THREAD

**Issue by wym888** [PaddlePaddle/Paddle#35911]
为使您的问题得到快速解决，在建立Issues前，请您先通过如下方式搜索是否有相似问题:【搜索issue关键字】【使用labels筛选】【官方文档】

如果您没有查询到相似问题，为快速解决您的提问，建立issue时请提供如下细节信息：
- 标题：简洁、精准概括您的问题，例如“Insufficient Memory xxx" ”
- 版本、环境信息：
    1）PaddlePaddle版本：2.1
    2）CPU：预测若用CPU，请提供CPU型号，MKL/OpenBlas/MKLDNN/等数学库使用情况
    3）GPU：预测若用GPU，3080 cudn 8.1
    4）系统环境：请您描述系统类型、版本，例如Mac OS 10.14，Python版本
 注：您可以通过执行[summary_env.py](https://github.com/PaddlePaddle/Paddle/blob/develop/tools/summary_env.py)获取以上信息。
- 训练信息
    1）单机/多机，单卡/多卡
    2）显存信息
    3）Operator信息
- 复现信息：如为报错，请给出复现环境、复现步骤
- 问题描述：请详细描述您的问题，同步贴出报错信息、日志、可复现的代码片段

Thank you for contributing to PaddlePaddle.
Before submitting the issue, you could search issue in the github in case that there was a similar issue submitted or resolved before.
If there is no solution,please make sure that this is a training issue including the following details:
**System information**
-PaddlePaddle version （eg.1.1）or CommitID
-CPU: including CPUMKL/OpenBlas/MKLDNN version
-GPU: including CUDA/CUDNN version
-OS Platform (eg.Mac OS 10.14)
-Other imformation: Distriuted training/informantion of operator/
Graphics card storage
Note: You can get most of the information by running [summary_env.py](https://github.com/PaddlePaddle/Paddle/blob/develop/tools/summary_env.py). 
**To Reproduce**
Steps to reproduce the behavior
**Describe your current behavior**
**Code to reproduce the issue**
**Other info / logs**

**Comment by JZ-LIANG** [comment]
请提供复现代码，但感觉大概率是数据读取完了但reader 没有按预期抛出异常。。。。建议检查一下reader 实现

**Comment by wym888** [comment]
报错语句  
File "F:\conda\envs\paddle\lib\site-packages\paddlenlp\datasets\dataset.py", line 110, in load_dataset
    return reader_instance.read(**custom_kwargs)
  File "F:\conda\envs\paddle\lib\site-packages\paddlenlp\datasets\dataset.py", line 715, in read
    return MapDataset(list(examples))
  File "F:/text_classification/rnn/mydataload.py", line 8, in read
    words, label = line.split('\t')
ValueError: too many values to unpack (expected 2)


在2021年9月22日 ***@***.***> 写道：

请提供复现代码，但感觉大概率是数据读取完了但reader 没有按预期抛出异常。。。。建议检查一下reader 实现

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by JZ-LIANG** [comment]
words, label = line.split('\t')
ValueError: too many values to unpack (expected 2)

这两句很明显是输入数据和reader 不匹配造成的，paddlenlp 的dataset reader 要求每行只有两个元素（words, label ）， 你的dataset 不符合。 
 请查看你的mydataload.py的实现。

**Comment by wym888** [comment]
请帮忙看看 13个epoch 就挂了
在2021年9月23日 ***@***.***> 写道：

words, label = line.split('\t')



ValueError: too many values to unpack (expected 2)

这两句很明显是输入数据和reader 不匹配造成的，paddlenlp 的dataset reader 要求每行只有两个元素（words, label ）， 你的dataset 不符合。
请查看你的mydataload.py的实现。

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
