### ISSUE TITLE
为什么一直不支持cuda11.1啊

### ISSUE THREAD

**Issue by x745667479** [PaddlePaddle/Paddle#35929]
欢迎您对PaddlePaddle提出建议，非常感谢您对PaddlePaddle的贡献！
在留下您的建议时，辛苦您同步提供如下信息：
- 版本、环境信息
1）PaddlePaddle版本：请提供您的PaddlePaddle版本号，例如1.1
2）CPU/GPU：您是否使用GPU进行训练，如是，请提供您的CUDA和cuDNN版本号
3）系统环境：请您描述系统类型、版本，例如Mac OS 10.14
注：您可以通过执行[summary_env.py](https://github.com/PaddlePaddle/Paddle/blob/develop/tools/summary_env.py)获取以上信息。
- 复现信息：如为报错，请给出复现环境、复现步骤
- 建议描述：请您详细描述，您认为需优化的功能

Thank you for contributing to PaddlePaddle.
Before submitting the issue, you could search issue in the github in case that there was a similar issue submitted or resolved before.
Please make sure that this is a feature request. 
**System information**
-PaddlePaddle version （eg.1.1）or CommitID
-CPU: including CPUMKL/OpenBlas/MKLDNN version
-GPU: including CUDA/CUDNN version
-OS Platform (eg.Mac OS 10.14)
Note: You can get most of the information by running [summary_env.py](https://github.com/PaddlePaddle/Paddle/blob/develop/tools/summary_env.py). 
**To Reproduce**
Steps to reproduce the behavior
**Describe the feature and the current behavior/state.**
**Any Other info.**

**Comment by wangxicoding** [comment]
支持的呀，11.2都支持的呢，安装可以参考 https://www.paddlepaddle.org.cn/install/quick?docurl=/documentation/docs/zh/install/pip/linux-pip.html

**Comment by x745667479** [comment]
> 支持的呀，11.2都支持的呢，安装可以参考 https://www.paddlepaddle.org.cn/install/quick?docurl=/documentation/docs/zh/install/pip/linux-pip.html

似乎没有11.1的选项，只有11.2和11.0？请问具体选择哪一个？

**Comment by wangxicoding** [comment]
可以先试试使用11.0

**Comment by x745667479** [comment]
> 可以先试试使用11.0

11.0并不能用.......

**Comment by wangxicoding** [comment]
> > 可以先试试使用11.0
> 
> 11.0并不能用.......

报啥错了吗，cudnn环境的问题？

**Comment by x745667479** [comment]
> > > 可以先试试使用11.0
> > 
> > 
> > 11.0并不能用.......
> 
> 报啥错了吗，cudnn环境的问题？
Running verify PaddlePaddle program ... 
W0923 12:10:50.246201    62 device_context.cc:404] Please NOTE: device: 0, GPU Compute Capability: 8.6, Driver API Version: 11.1, Runtime API Version: 11.0
W0923 12:10:50.246647    62 dynamic_loader.cc:267] The third-party dynamic library (libcudnn.so) that Paddle depends on is not configured correctly. (error code is libcudnn.so: cannot open shared object file: No such file or directory)
  Suggestions:
  1. Check if the third-party dynamic library (e.g. CUDA, CUDNN) is installed correctly and its version is matched with paddlepaddle you installed.
  2. Configure third-party dynamic library environment variables as follows:
  - Linux: set LD_LIBRARY_PATH by `export LD_LIBRARY_PATH=...`
  - Windows: set PATH by `set PATH=XXX;
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/root/xsc/conda_envs/exp/lib/python3.7/site-packages/paddle/utils/install_check.py", line 196, in run_check
    _run_static_single(use_cuda)
  File "/root/xsc/conda_envs/exp/lib/python3.7/site-packages/paddle/utils/install_check.py", line 124, in _run_static_single
    exe.run(startup_prog)
  File "/root/xsc/conda_envs/exp/lib/python3.7/site-packages/paddle/fluid/executor.py", line 1110, in run
    six.reraise(*sys.exc_info())
  File "/root/xsc/conda_envs/exp/lib/python3.7/site-packages/six.py", line 719, in reraise
    raise value
  File "/root/xsc/conda_envs/exp/lib/python3.7/site-packages/paddle/fluid/executor.py", line 1108, in run
    return_merged=return_merged)
  File "/root/xsc/conda_envs/exp/lib/python3.7/site-packages/paddle/fluid/executor.py", line 1239, in _run_impl
    use_program_cache=use_program_cache)
  File "/root/xsc/conda_envs/exp/lib/python3.7/site-packages/paddle/fluid/executor.py", line 1329, in _run_program
    [fetch_var_name])
RuntimeError: (PreconditionNotMet) Cannot load cudnn shared library. Cannot invoke method cudnnGetVersion.
  [Hint: cudnn_dso_handle should not be null.] (at /paddle/paddle/fluid/platform/dynload/cudnn.cc:59)

**Comment by wangxicoding** [comment]
![image](https://user-images.githubusercontent.com/10208305/134473219-6e326fa4-258b-47ae-8dc9-71c04e4481f2.png)
cudnn没有安装，或者路径不太对，可以参考这里面把cudnn安装一下~
https://www.paddlepaddle.org.cn/install/quick?docurl=/documentation/docs/zh/install/pip/linux-pip.html

**Comment by wangxicoding** [comment]
或者使用docker可能会更方便些 https://www.paddlepaddle.org.cn/install/quick?docurl=/documentation/docs/zh/install/docker/linux-docker.html
