### ISSUE TITLE
使用gpu训练报错Compiled with WITH_GPU, but no GPU found in runtime.

### ISSUE THREAD

**Issue by Karenlyw** [PaddlePaddle/Paddle#35921]
1）PaddlePaddle版本：1.8.5.post107
paddlehub：1.6.2
    2）GPU：
 NVIDIA-SMI 418.87.00    Driver Version: 418.87.00    CUDA Version: 10.1  cudnn：7.6

    4）系统环境：linux
 注：您可以通过执行[summary_env.py](https://github.com/PaddlePaddle/Paddle/blob/develop/tools/summary_env.py)获取以上信息。
- 训练信息
    1）单机单卡

报错：
ExternalError:  Cuda error(30), unknown error.
  [Advise: This indicates that an unknown internal error has occurred. ] at (/paddle/paddle/fluid/platform/gpu_info.cc:65)
  [operator < load > error]
 其他cuda程序测试正常

**Comment by JZ-LIANG** [comment]
可以用一下命令验证安装，
import paddle.fluid as fluid
fluid.install_check.run_check()
看一下是否有 Multiple gpu check successful 字样

另外建议检查：
编译时的环境和当前运行环境是否一致？ 
编译时 nccl 的路径是否被成功找到（在 LD_LIBRARY_PATH中）？

**Comment by Karenlyw** [comment]
> 可以用一下命令验证安装，
> import paddle.fluid as fluid
> fluid.install_check.run_check()
> 看一下是否有 Multiple gpu check successful 字样
> 
> 另外建议检查：
> 编译时的环境和当前运行环境是否一致？
> 编译时 nccl 的路径是否被成功找到（在 LD_LIBRARY_PATH中）？

验证安装报错：root:You are using GPU version Paddle Fluid, But Your CUDA Device is not set properly

**Comment by Karenlyw** [comment]
> LD_LIBRARY_PATH

另外请问单卡也需要nccl吗
