### ISSUE TITLE
Convolution层group操作是否存在内存泄漏

### ISSUE THREAD

**Issue by Noplz** [PaddlePaddle/Paddle#3593]
在自己的几个paddle实验中分别在P40集群和本地K40机器发现了在convolution层的group较大的时候会出现内存泄漏的问题。

**Comment by NHZlX** [comment]
###1 
the tests which ware did on my develop machine with the up-2-data paddle version:

| Model     | train counter |Leak？|
| -------------|------- |:-------------:|
| vgg ssd| 1 | no|
| mobilenet ssd | 1 | no|
|mobilenet ssd| 3| no|
|mobilenet cls on flower102| 1|no|  
|mobilenet  cls on flower102| 3| no |

**Comment by NHZlX** [comment]
像openblas, protobuf 这样的第三方库尽量不用自己环境中的
