### ISSUE TITLE
need to refine random related operators

### ISSUE THREAD

**Issue by QiJune** [PaddlePaddle/Paddle#3598]
- Random is a basic operation of Tensor. And we should add random functions.
- And random seed is device related, we have to ensure seeds in different GPU device is different. So, I just add seed as a member of DeviceContext. 
- implement gaussian random operator correctly

**Comment by reyoung** [comment]
random seed should be an attribute of the random operator, it should not be a field in DeviceContext, because it is not `Context` or `Device` related.
