### ISSUE TITLE
ValueError: Input(perm) is the permutation of dimensions of Input(x), its length should be equal to dimensions of Input(x), but received dimension of Input(x) is 2, the length of Input(perm) is 3.

### ISSUE THREAD

**Issue by Sunyingbin** [PaddlePaddle/Paddle#35983]
paddlepaddle 2.1 负荷预测任务，新建一个lstm模型，在读取数据时报错如下：
ValueError: Input(perm) is the permutation of dimensions of Input(x), its length should be equal to dimensions of Input(x), but received dimension of Input(x) is 2, the length of Input(perm) is 3.

模型如下：
class MyLSTM(paddle.nn.Layer):
    def __init__(self, input_size=72, hidden_size=24 * 3):
        super().__init__()
        self.linear1 = paddle.nn.Linear(24 * 3, 24 * 2)
        self.rnn = paddle.nn.LSTM(input_size=24 * 2, hidden_size=24, num_layers=1)
        self.linear2 = paddle.nn.Linear(24 * 2, 1)

    @paddle.jit.to_static
    def forward(self, x):
        # 双向LSTM - [0]代表取双向结果，[1][0]代表forward结果,[1][1]代表backward结果，详细说明可在官方文档中搜索'LSTM'
        y, (h, c) = self.rnn(x)
        output = self.linear2(y)

        return output

训练代码如下：
# DataLoader返回一个迭代器，该迭代器根据 batch_sampler 给定的顺序迭代一次给定的 dataset
    trainer_loader = paddle.io.DataLoader(trainer_dataset, batch_size=BATCH_SIZE)
    model = MyLSTM()
    # 训练模式
    model.train()
    optim = paddle.optimizer.Adam(learning_rate=learning_rate, parameters=model.parameters())
    start = time.time()

    Losses = []
    for epoch in range(EPOCH_NUM):
        for batch_id, data in enumerate(trainer_loader()):
            x_data = data[0]
            y_data = data[1][:, 12]

问题在哪？

**Comment by Sunyingbin** [comment]
x_data.shape为[10, 72]
y_data.shape为[10]

**Comment by wangxicoding** [comment]
rnn的inputs输入的shape应该是3，https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/nn/RNN_cn.html#rnn
![image](https://user-images.githubusercontent.com/10208305/134506144-dc4cfe9e-c967-4280-8309-03a98d1fe42f.png)

**Comment by Sunyingbin** [comment]
> rnn的inputs输入的shape应该是3，https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/nn/RNN_cn.html#rnn
> ![image](https://user-images.githubusercontent.com/10208305/134506144-dc4cfe9e-c967-4280-8309-03a98d1fe42f.png)

x_data.shape 我转成了[10, 72, 1]可以了，10：batch_size  72：入参个数 这样对吗

**Comment by wangxicoding** [comment]
> > rnn的inputs输入的shape应该是3，https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/nn/RNN_cn.html#rnn
> > ![image](https://user-images.githubusercontent.com/10208305/134506144-dc4cfe9e-c967-4280-8309-03a98d1fe42f.png)
> 
> x_data.shape 我转成了[10, 72, 1]可以了，10：batch_size 72：入参个数 这样对吗

![image](https://user-images.githubusercontent.com/10208305/134624785-9774ee8c-306c-4ba6-8aac-65cf742cfc8e.png)
根据文档[10, 72, 1]，10为batch_size，72为time_steps，1为input_size。

**Comment by Sunyingbin** [comment]
> > > rnn的inputs输入的shape应该是3，https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/nn/RNN_cn.html#rnn
> > > ![image](https://user-images.githubusercontent.com/10208305/134506144-dc4cfe9e-c967-4280-8309-03a98d1fe42f.png)
> > 
> > 
> > x_data.shape 我转成了[10, 72, 1]可以了，10：batch_size 72：入参个数 这样对吗
> 
> ![image](https://user-images.githubusercontent.com/10208305/134624785-9774ee8c-306c-4ba6-8aac-65cf742cfc8e.png)
> 根据文档[10, 72, 1]，10为batch_size，72为time_steps，1为input_size。

我用上一天的数据共72条，预测第二天某个时间点的负荷，所以在lstm中入参是1维，是这样吗？

**Comment by wangxicoding** [comment]
上面好像发成rnn的文档了，你代码里用的应该是LSTM，https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/nn/LSTM_cn.html#lstm

> 我用上一天的数据共72条，预测第二天某个时间点的负荷，所以在lstm中入参是1维，是这样吗？

这样是可以的。另外time_steps应该是一个超参，可以根据需要进行调节。72条，time_steps可以为72，一个特征、记忆传递72次；也可以是time_steps=24，三个特征、记忆传递24次。

**Comment by wangxicoding** [comment]
可以参考下知乎或者网络上其它关于LSTM time_steps的文章，https://www.zhihu.com/question/271774530

**Comment by Sunyingbin** [comment]
> time_steps应该是一个超参

想问一下time_steps应该是一个超参这个意思是不是我自己定这个值，比如根据过去5天数据去预测第六天的某一个值，这个5是我想定多少就是多少。

**Comment by wangxicoding** [comment]
> 想问一下time_steps应该是一个超参这个意思是不是我自己定这个值，比如根据过去5天数据去预测第六天的某一个值，这个5是我想定多少就是多少。

是的，不过也跟数据相关了
