### ISSUE TITLE
如何固定随机种子，保证网络训练过程可以复现

### ISSUE THREAD

**Issue by huilin16** [PaddlePaddle/Paddle#36029]
请问，应该如何固定随机种子，保证网络训练过程可以复现

我使用代码`paddle seed，似乎并没有作用

import paddle
paddle.seed(102)`

**Comment by wangxicoding** [comment]
是不是什么地方用到了numpy，把numpy的随机种子也固定一下
paddle.seed(123)
np.random.seed(2021)

**Comment by huilin16** [comment]
您好，好像并不起作用，


而且我的模型用的是何凯明初始化，
我的输入是固定的1张图片
用了paddle。seed每次输出的结果并不相同




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/Paddle"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年9月23日(星期四) 晚上10:10
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PaddlePaddle/Paddle] 如何固定随机种子，保证网络训练过程可以复现 (#36029)





 
是不是什么地方用到了numpy，把numpy的随机种子也固定一下
 paddle.seed(123)
 np.random.seed(2021)
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by wangxicoding** [comment]
跑的静态图还是动态图，再试试`paddle.static.default_main_program().random_seed = 102`

**Comment by huilin16** [comment]
是在aistudio&nbsp; &nbsp;paddle2.1.2中跑的动态图






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/Paddle"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年9月24日(星期五) 下午2:01
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PaddlePaddle/Paddle] 如何固定随机种子，保证网络训练过程可以复现 (#36029)





 
跑的静态图还是动态图，再试试paddle.static.default_main_program().random_seed = 102
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by wangxicoding** [comment]
是不是还有python的random随机种子需要固定`random.seed(123)`

**Comment by huilin16** [comment]
并没有效果




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/Paddle"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年9月24日(星期五) 晚上7:52
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PaddlePaddle/Paddle] 如何固定随机种子，保证网络训练过程可以复现 (#36029)





 
是不是还有python的random随机种子需要固定random.seed(123)
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by ForFishes** [comment]
能提供复现代码吗？是否代码里有修改随机状态。
