### ISSUE TITLE
jetson nx上部署paddleseg框架下biesenetV2算法训练自己的数据集产生的模型，推理速度太慢.预测程序用的是paddleseg中的C++部署示例

### ISSUE THREAD

**Issue by huangwan-jiayi** [PaddlePaddle/Paddle#36022]
这是我参考的例程：
![image](https://user-images.githubusercontent.com/71338215/134485561-06967654-2871-466f-8e38-7ecb2dfee17c.png)

这是我的推理时间：
![image](https://user-images.githubusercontent.com/71338215/134485581-5580467b-93dd-4d82-a4d3-42465a9037e8.png)

以下是全部代码：

#include <algorithm>
#include <chrono>
#include <iostream>
#include <fstream>
#include <numeric>
#include <time.h>
#include <gflags/gflags.h>
#include <glog/logging.h>
using namespace std;

#include "paddle/include/paddle_inference_api.h"
#include "yaml-cpp/yaml.h"
#include "opencv2/core.hpp"
#include "opencv2/imgproc.hpp"
#include "opencv2/highgui.hpp"

DEFINE_string(model_dir, "", "Directory of the inference model. "
"It constains deploy.yaml and infer models");
DEFINE_string(img_path, "", "Path of the test image.");
DEFINE_bool(use_cpu, false, "Wether use CPU. Default: use GPU.");
DEFINE_bool(use_trt, false, "Wether enable TensorRT when use GPU. Defualt: false.");
DEFINE_bool(use_mkldnn, false, "Wether enable MKLDNN when use CPU. Defualt: false.");
DEFINE_string(save_dir, "", "Directory of the output image.");

typedef struct YamlConfig {
std::string model_file;
std::string params_file;
bool is_normalize;
}YamlConfig;

YamlConfig load_yaml(const std::string& yaml_path) {
YAML::Node node = YAML::LoadFile(yaml_path);
std::string model_file = node["Deploy"]["model"].asstd::string();
std::string params_file = node["Deploy"]["params"].asstd::string();
bool is_normalize = false;
if (node["Deploy"]["transforms"] &&
node["Deploy"]["transforms"][0]["type"].asstd::string() == "Normalize") {
is_normalize = true;
}

YamlConfig yaml_config = {model_file, params_file, is_normalize};
return yaml_config;
}

std::shared_ptr<paddle_infer::Predictor> create_predictor(const YamlConfig& yaml_config) {
std::string& model_dir = FLAGS_model_dir;

paddle_infer::Config infer_config;
infer_config.SetModel(model_dir + "/" + yaml_config.model_file,
model_dir + "/" + yaml_config.params_file);
infer_config.EnableMemoryOptim();

if (FLAGS_use_cpu) {
LOG(INFO) << "Use CPU";
if (FLAGS_use_mkldnn) {
// TODO(jc): fix the bug
//infer_config.EnableMKLDNN();
infer_config.SetCpuMathLibraryNumThreads(5);
}
} else {
LOG(INFO) << "Use GPU";
infer_config.EnableUseGpu(500, 0);
if (FLAGS_use_trt) {
infer_config.EnableTensorRtEngine(1 << 30, 1, 1,
paddle_infer::PrecisionType::kFloat32, false, false);
}
}

auto predictor = paddle_infer::CreatePredictor(infer_config);
return predictor;
}

void hwc_img_2_chw_data(const cv::Mat& hwc_img, float* data) {
int rows = hwc_img.rows;
int cols = hwc_img.cols;
int chs = hwc_img.channels();
for (int i = 0; i < chs; ++i) {
cv::extractChannel(hwc_img, cv::Mat(rows, cols, CV_32FC1, data + i * rows * cols), i);
}
}

cv::Mat read_process_image(bool is_normalize) {
cv::Mat img = cv::imread(FLAGS_img_path, cv::IMREAD_COLOR);
cv::cvtColor(img, img, cv::COLOR_BGR2RGB);
if (is_normalize) {
img.convertTo(img, CV_32F, 1.0 / 255, 0);
img = (img - 0.5) / 0.5;
}
return img;
}

int main(int argc, char *argv[]) {
google::ParseCommandLineFlags(&argc, &argv, true);
if (FLAGS_model_dir == "") {
LOG(FATAL) << "The model_dir should not be empty.";
}

// Load yaml
std::string yaml_path = FLAGS_model_dir + "/deploy.yaml";
YamlConfig yaml_config = load_yaml(yaml_path);

// Prepare data
cv::Mat img = read_process_image(yaml_config.is_normalize);
int rows = img.rows;
int cols = img.cols;
int chs = img.channels();
std::vector input_data(1 * 3 * 1080 *1920, 0.0f);
hwc_img_2_chw_data(img, input_data.data());

// Create predictor
auto predictor = create_predictor(yaml_config);

// Set input
auto input_names = predictor->GetInputNames();
auto input_t = predictor->GetInputHandle(input_names[0]);
std::vector input_shape = {1, 3, 1080, 1920};
input_t->Reshape(input_shape);
input_t->CopyFromCpu(input_data.data());

// Run
clock_t start,end;
start=clock();
predictor->Run();
end=clock();
cout << "The run time is:" << (double)(end-start)/CLOCKS_PER_SEC << "s" << endl;
// Get output
auto output_names = predictor->GetOutputNames();
auto output_t = predictor->GetOutputHandle(output_names[0]);
std::vector output_shape = output_t->shape(); // n * h * w
int out_num = std::accumulate(output_shape.begin(), output_shape.end(), 1,
std::multiplies());
std::vector<int64_t> out_data(out_num);
output_t->CopyToCpu(out_data.data());

// Get pseudo image
std::vector<uint8_t> out_data_u8(out_num);
for (int i = 0; i < out_num; i++) {
out_data_u8[i] = static_cast<uint8_t>(out_data[i]);
}
cv::Mat out_gray_img(output_shape[1], output_shape[2], CV_8UC1, out_data_u8.data());
cv::Mat out_eq_img;
cv::equalizeHist(out_gray_img, out_eq_img);
cv::imwrite("out_img.jpg", out_eq_img);

LOG(INFO) << "Finish";
}
paddle 版本2.1.2：
![image](https://user-images.githubusercontent.com/71338215/134485764-7ddbe1b0-27d5-4c7f-adbc-fc4855f6430c.png)

nx 环境：
![image](https://user-images.githubusercontent.com/71338215/134485799-61a94ed2-f475-4740-8236-2b10f2dd6f49.png)

输入图像大小为1080*1920。

**Comment by wangxicoding** [comment]
预期速度是有多少。另外可以统计一下图像处理，预测，保存结果的时间吗，瓶颈瓶颈可能在图像处理和保存结果上

**Comment by wangxicoding** [comment]
github 支持markdown格式，c++代码可以用` ``` c++ ``` `给括起来，排版好看点。

**Comment by huangwan-jiayi** [comment]
预期速度几十ms，我不清楚我这个时间到底是不是预测一张图的时间，输出可视化就一张图。
![image](https://user-images.githubusercontent.com/71338215/134497241-a75b6a9a-ca0d-4c73-8fbd-ba8ecb422f54.png)

**Comment by huangwan-jiayi** [comment]
![image](https://user-images.githubusercontent.com/71338215/134501085-7cd7c4a7-595d-48d0-b822-54ae23e84e18.png)
jing精度改为fp16之后时间没有发生变化，另外您说的warm up 是怎么加呢？
![image](https://user-images.githubusercontent.com/71338215/134501252-71ca2215-d729-466c-b8ec-ce49a1a60bb6.png)

**Comment by wangxicoding** [comment]
for循环跑个大概25步，前面5步当warmup，后面20步求个平均？

**Comment by huangwan-jiayi** [comment]
![image](https://user-images.githubusercontent.com/71338215/134508886-8c9b90e4-ff7c-4779-ba4e-df45d1c403f8.png)
![image](https://user-images.githubusercontent.com/71338215/134508941-f9764b3d-e028-4ab5-b276-0d0bc02569ea.png)
这是5次花的时间，
![image](https://user-images.githubusercontent.com/71338215/134509498-0b73fe5d-5c98-4a08-bb4a-d386668ed1ac.png)
![image](https://user-images.githubusercontent.com/71338215/134509517-6fd52055-f797-4835-a3d0-de74ceaf5774.png)
这是24次花的时间算下来后20次平均一次还是需要146ms，时间还是有点慢啊

**Comment by huangwan-jiayi** [comment]
![image](https://user-images.githubusercontent.com/71338215/134510156-f77f4915-bcf8-48e6-b251-ed01b258e462.png)
每次编译的时候会有这个警告，会不会跟这个有关系呢？

**Comment by wangxicoding** [comment]
> ![image](https://user-images.githubusercontent.com/71338215/134510156-f77f4915-bcf8-48e6-b251-ed01b258e462.png)
> 每次编译的时候会有这个警告，会不会跟这个有关系呢？

编译警告是手工设置的cudnn_lib这个变量没有使用到，你编译使用到了cudnn了吧。 
另外性能可以用nvprof或者nsys给profile一下，看下瓶颈在哪儿

**Comment by huangwan-jiayi** [comment]
> 工设置的cudnn_lib这个变量没有使用到，你编译使用到了cudnn了吧。
> 另外性能可以用nvprof或者nsys给profile一下，看下瓶颈在哪儿

我在complie里修改了cudnn的路径为我自己的路径，所以是我没有用到cudnn吗。。。 还有您说的nvpro，nsys给profile一下我不太明白是啥意思。
这是我的路径：
![image](https://user-images.githubusercontent.com/71338215/134512165-97984e29-9abd-4aee-afe5-b221f2114bdf.png)

**Comment by wangxicoding** [comment]
> 所以是我没有用到cudnn吗。。。 还有您说的nvpro，nsys给profile一下我不太明白是啥意思。

看下编译log里面有没有找到cudnn路径之类的。
nvprof和nsys是nvidia提供的profile工具，可以查看https://docs.nvidia.com/nsight-systems/UserGuide/index.html
inference也提供了profile的接口，https://paddle-inference.readthedocs.io/en/latest/api_reference/cxx_api_doc/Config/OtherFunction.html#profile

**Comment by wangxicoding** [comment]
另外再试试把IR优化打开？
https://paddle-inference.readthedocs.io/en/latest/api_reference/go_api_doc/Config/OptimConfig.html?highlight=SwitchIrOptim#id1

**Comment by huangwan-jiayi** [comment]
您说的是这个吗，我看不太懂。...
![image](https://user-images.githubusercontent.com/71338215/134517048-6e7bb9f2-891c-418d-9d60-38e5f3e85137.png)
![image](https://user-images.githubusercontent.com/71338215/134517206-996aeeb3-23d5-49ff-a65c-0827712c103c.png)
![image](https://user-images.githubusercontent.com/71338215/134517265-34078806-7de4-471f-b337-c85735033792.png)
![image](https://user-images.githubusercontent.com/71338215/134517378-1fd7dcfd-28ae-4219-98d5-ab166a7dd0b5.png)
这个代表我已经打开了IR优化了吧？
![image](https://user-images.githubusercontent.com/71338215/134517453-a73a6401-73e5-43f6-9f3a-f71289cee943.png)

**Comment by wangxicoding** [comment]
> 这个代表我已经打开了IR优化了吧？

是的。

> 您说的是这个吗，我看不太懂。...

min和max的时间差距很大，试试从5个warmup之后在加上profile。里面都是一些具体cuda kernel的耗时及占比。可能还是用nsys profile然后可视化出来看起来明了一些

**Comment by huangwan-jiayi** [comment]
好的，我明天再看看，谢谢您的耐心解答，辛苦啦！



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: WangXi ***@***.***&gt;
发送时间: 2021年9月23日 22:01
收件人: PaddlePaddle/Paddle ***@***.***&gt;
抄送: huangwan-jiayi ***@***.***&gt;, State change ***@***.***&gt;
主题: 回复：[PaddlePaddle/Paddle] jetson nx上部署paddleseg框架下biesenetV2算法训练自己的数据集产生的模型，推理速度太慢.预测程序用的是paddleseg中的C++部署示例 (#36022)

**Comment by huangwan-jiayi** [comment]
你好，这是我用paddle官方的profile设置，run了10次，
![image](https://user-images.githubusercontent.com/71338215/134613962-04993216-6764-4be6-a47c-d87b5e38ceba.png)
![image](https://user-images.githubusercontent.com/71338215/134613981-87413a97-4eb0-43a2-a4fa-c79ff69570a3.png)
为啥GPU time是0呢？
![image](https://user-images.githubusercontent.com/71338215/134614008-1ee17adf-6f0d-4cc1-86cd-7568bccf1239.png)
还有您说的从5个warmup之后加上profile，是怎么操作呢？

**Comment by wangxicoding** [comment]
> 还有您说的从5个warmup之后加上profile，是怎么操作呢

好像不太行。。新建一个predictor不知道可不可以🤣

> 为啥GPU time是0呢

不太清楚，里面都有cpu<-->gpu的拷贝，理论应该是有GPU的time的。
要不还是试试nv的nsys profile工具。
``` bash
# 正常运行程序指令 python minst.py
nsys profile --stats=true -t cuda python minst.py
```
在运行目录中会得到两个文件：report1.sqlite以及report1.qdrep。其中report1.qdrep是我们需要的文件。Nsight System打开report1.qdrep就可以了。
通过profile可以进行性能分析，举个栗子，如下图中间的gap可能就是前后处理的时间过长导致的。
![image](https://user-images.githubusercontent.com/10208305/134617461-64e796a8-c913-4a23-b7c0-8b6eb23cc01d.png)
https://developer.nvidia.com/gameworksdownload#?dn=cuda-toolkit-developer-tools-for-macos-11-2-1
https://developer.nvidia.com/zh-cn/nsight-systems

**Comment by huangwan-jiayi** [comment]
nsys profile 还是没看懂怎么操作，
![image](https://user-images.githubusercontent.com/71338215/134626233-844500cf-4ddb-4ff6-9153-8deedd3cbbc6.png)这个命令是直接在命令行里使用吗，我显示找不到该命令。

GPU时间为0，是不是和这个有关系啊，
![image](https://user-images.githubusercontent.com/71338215/134625537-16020929-c8f4-4891-bbd1-443babed51bb.png)
是不是每run一次都应该有预处理的过程吧？我现在都不清楚到底那个时间是预测一张图片的时间了
![24EA2B68](https://user-images.githubusercontent.com/71338215/134626091-e6eb30b2-10ab-4011-a1e9-4b6980553d39.png)
另外我在CMakeOutput.log中没有发现cudnn路径。
![image](https://user-images.githubusercontent.com/71338215/134626433-2e013b18-07cc-432f-8952-dc63b36d5dc6.png)

**Comment by wangxicoding** [comment]
> 这个命令是直接在命令行里使用吗，我显示找不到该命令。

嗯，命令行里，需要先安装好nsys。nsys安装在前面的链接里给了，或者apt-get也可以，可以`apt-cache search cuda-nsight`搜一下，大概`apt-get install cuda-nsight-systems-11-2`


> GPU时间为0，是不是和这个有关系啊，

CUDA CUPTI is not enable这个吗


> 是不是每run一次都应该有预处理的过程吧

不太清楚。。是不是网络里有相关的预处理op



> 另外我在CMakeOutput.log中没有发现cudnn路径。

没cudnn理论会编译报错的呢🤣

**Comment by huangwan-jiayi** [comment]
> > 这个命令是直接在命令行里使用吗，我显示找不到该命令。
> 
> 嗯，命令行里，需要先安装好nsys。nsys安装在前面的链接里给了，或者apt-get也可以，可以`apt-cache search cuda-nsight`搜一下，大概`apt-get install cuda-nsight-systems-11-2`
> 
![image](https://user-images.githubusercontent.com/71338215/134762645-77ab9de1-6d3a-4e4f-9d6e-1b8a4a3b1804.png)
用apt安装不上。
下载了arm版本的deb，安装后还是不行。
![image](https://user-images.githubusercontent.com/71338215/134762895-41600e20-0cb2-408b-8366-f3c47cfd5f2b.png)
![image](https://user-images.githubusercontent.com/71338215/134762913-fa6bbf29-4dc9-479c-9edc-ea4531c7f6a5.png)

![image](https://user-images.githubusercontent.com/71338215/134762670-f526fafa-5650-47f8-ad5a-e4513072d87b.png)

> > GPU时间为0，是不是和这个有关系啊，
> 
> CUDA CUPTI is not enable这个吗

> 嗯嗯，就是这个。
> > 是不是每run一次都应该有预处理的过程吧
> 
> 不太清楚。。是不是网络里有相关的预处理op
> 
> > 另外我在CMakeOutput.log中没有发现cudnn路径。
> 
> 没cudnn理论会编译报错的呢🤣

**Comment by wangxicoding** [comment]
> 用apt安装不上。
> 下载了arm版本的deb，安装后还是不行。

忘了说，用apt的话得把cuda源给加上(注意修改ubuntu对应的版本和架构，https://developer.download.nvidia.cn/compute/cuda/repos/)，https://www.jianshu.com/p/31b00ec5bc74
![image](https://user-images.githubusercontent.com/10208305/134799843-a7158974-141c-4758-95d0-3734d5ee9d8a.png)

arm版本的deb是咋用不了

**Comment by huangwan-jiayi** [comment]
![image](https://user-images.githubusercontent.com/71338215/134807206-bb9cbb88-9393-4841-a4d8-711539328802.png)
下图 x86的
![image](https://user-images.githubusercontent.com/71338215/134807259-0dae2c42-5817-492e-9ae9-59529340cf1b.png)
arm版本没有nsys，不知道我可以在jetson nx上下x86的不？

**Comment by wangxicoding** [comment]
https://developer.download.nvidia.cn/compute/cuda/repos/ubuntu1804/sbsa/
这里是arm的

**Comment by huangwan-jiayi** [comment]
安装好了，谢谢。
![image](https://user-images.githubusercontent.com/71338215/134807883-1e120e53-c4fd-4a29-ae96-e7168c685a04.png)

可是我这个是一个run.shhi脚本文件，怎么使用呢？
![image](https://user-images.githubusercontent.com/71338215/134807876-943a8206-9a56-4911-8e12-07d0c9fab9ec.png)

**Comment by wangxicoding** [comment]
> 可是我这个是一个run.shhi脚本文件，怎么使用呢？

`bash run.sh`
nsys profile --stats=true -t cuda bash run.sh

**Comment by huangwan-jiayi** [comment]
![image](https://user-images.githubusercontent.com/71338215/134842831-743fe882-6164-42ab-ad01-830a1cf04e87.png)。生成了这个文件，可是不知道怎么用nsys打开这个文件。
另外我准备尝试用python端部署这个模型，按错官网步骤来，发现报错，
![image](https://user-images.githubusercontent.com/71338215/134842948-ef70e4f1-570a-4b86-9d46-3a94e465e1aa.png)
我自己编译的paddle 预测库，也手动pip安装写明的whl文件。
![image](https://user-images.githubusercontent.com/71338215/134843293-b1b773e4-7f38-46a5-a340-c583a8fb587a.png)

![image](https://user-images.githubusercontent.com/71338215/134843027-0ff21292-562d-465f-82df-61ea33d4f8ff.png)。
相应的import也有啊，
![image](https://user-images.githubusercontent.com/71338215/134843113-f0608570-5c00-4877-a986-1be48566c220.png)
不知道为什么还显示模块找不到的错误

**Comment by wangxicoding** [comment]
> 生成了这个文件，可是不知道怎么用nsys打开这个文件。

nsight system直接打开文件就行~
![image](https://user-images.githubusercontent.com/10208305/134843833-f993fad9-ede8-4977-82f8-bb9c81b6af2c.png)


> 我自己编译的paddle 预测库，也手动pip安装写明的whl文件。

是不是python用错了，python3? 先`import paddle`试下？

**Comment by huangwan-jiayi** [comment]
确实是应该用python3。。。。， 不过它又爆了一个错，
![image](https://user-images.githubusercontent.com/71338215/134844406-5a700d9a-affc-49e1-b3fe-fc98e90dcfab.png)
我现在的问题是，找不到NVIDIA Nsight Systems 的可执行文件，不知道怎么打开
![image](https://user-images.githubusercontent.com/71338215/134844640-f94720b4-d760-41cf-970b-a6b4c19ee5e1.png)
![image](https://user-images.githubusercontent.com/71338215/134844816-b0100ab1-fd25-48a9-ab99-3ff5b7bcf429.png)

**Comment by wangxicoding** [comment]
> 确实是应该用python3。。。。， 不过它又爆了一个错，

看报错，需要把trt的动态shape模式打开？


> 我现在的问题是，找不到NVIDIA Nsight Systems 的可执行文件，不知道怎么打开

https://docs.nvidia.com/nsight-systems/InstallationGuide/index.html
![image](https://user-images.githubusercontent.com/10208305/134849674-792eb6d5-aee9-41f7-b8a6-def53a25a2be.png)

**Comment by huangwan-jiayi** [comment]
![image](https://user-images.githubusercontent.com/71338215/134857993-ee33ea92-3d8b-4c66-a045-179827143947.png)
只在这个目录下有nsys的相关文件，并没有
![image](https://user-images.githubusercontent.com/71338215/134858909-e44d80c8-1ec9-486d-9f5e-a95b1efe1288.png)

![image](https://user-images.githubusercontent.com/71338215/134858033-7dccd3d6-c4be-49c5-8e93-5813b3e84a05.png)
![image](https://user-images.githubusercontent.com/71338215/134858095-811d537b-c56d-4ebc-9bf7-4a845c46780e.png)
在各种目录下都找不到该命令。。
动态图是开了的，还是报这个错
![image](https://user-images.githubusercontent.com/71338215/134858314-f0eb9176-6abd-4e42-ae88-a3dc81a7c353.png)
![image](https://user-images.githubusercontent.com/71338215/134858756-0b6bef3b-5b76-44e1-8cda-926814724af0.png)

**Comment by wangxicoding** [comment]
![image](https://user-images.githubusercontent.com/10208305/134860072-dbe777f9-9eca-4570-b532-d72e71e0de14.png)
https://docs.nvidia.com/nsight-systems/InstallationGuide/index.html#finding-right-package
额，arm不支持host GUI。。。看看有没有x86的电脑，专门拿来可视化。。



> 动态图是开了的，还是报这个错

TRT相关的问题不了解🤣，要不再提个issue，会有值班同学跟进

**Comment by huangwan-jiayi** [comment]
> ![image](https://user-images.githubusercontent.com/10208305/134860072-dbe777f9-9eca-4570-b532-d72e71e0de14.png)
> https://docs.nvidia.com/nsight-systems/InstallationGuide/index.html#finding-right-package
> 额，arm不支持host GUI。。。看看有没有x86的电脑，专门拿来可视化。。
> 
> > 动态图是开了的，还是报这个错
> 
> TRT相关的问题不了解🤣，要不再提个issue，会有值班同学跟进

好的，真的很感谢你了。
