### ISSUE TITLE
paddle fleet 如何根据ins label 设置不进行某些塔的更新？

### ISSUE THREAD

**Issue by 20130353** [PaddlePaddle/Paddle#36037]
paddle fleet 在训练多目标时，需要根据label 设置更新哪些塔，不更新哪些塔，具体的写法是什么？

**Comment by pangyoki** [comment]
你好，可以参考一下这个API：https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/fluid/layers/filter_by_instag_cn.html
