### ISSUE TITLE
使用paddleOCR训练时候报错，在paddleOCR上提了issue，答复说paddle没有安装好

### ISSUE THREAD

**Issue by RyanCCC** [PaddlePaddle/Paddle#36039]
请问训练的时候执行以下命令，报错了如下截图所示：

paddle.utils.run_check()
![](https://user-images.githubusercontent.com/27406337/134468916-e9fbb7b3-fffa-4a5a-b4cb-5678c0c6196a.png)

cuda版本：
![image](https://user-images.githubusercontent.com/27406337/134613547-d1e82f1e-d92b-407e-b78e-2bcbfac692db.png)

操作系统：
Linux Debain

**Comment by pangyoki** [comment]
你好，cuda11.2应该需要使用cudnn8，应该是你的cudnn版本太低了。建议使用docker，这个镜像：
docker pull paddlepaddle/paddle:latest-dev-cuda11.2-cudnn8-gcc82
