### ISSUE TITLE
Persistable buffers are not persistent

### ISSUE THREAD

**Issue by SamDM** [PaddlePaddle/Paddle#36049]
Registering a buffer to `paddle.nn.Layer` does not make it fully persistable, even with `persistable=True`.

This causes the conversion to `onnx` to fail, because the data of the buffer is not exported to the `onnx` graph.
(note that conversion to a static model with `paddle.jit.save` is still working fine)

You can see that non persitable data is skipped in the `paddle2onnx` code [here](https://github.com/PaddlePaddle/Paddle2ONNX/blob/dff43108f87b6d9a45c887ec427c0558928beea2/paddle2onnx/graph/paddle_graph.py#L207) and [here](https://github.com/PaddlePaddle/Paddle2ONNX/blob/dff43108f87b6d9a45c887ec427c0558928beea2/paddle2onnx/graph/paddle_graph.py#L232).
Unfortunately, there is another bug in `paddle2onnx` which prevents buffers from being included.
The problem is that only parameters are considered, and buffers are forgotten, see [here](https://github.com/PaddlePaddle/Paddle2ONNX/blob/dff43108f87b6d9a45c887ec427c0558928beea2/paddle2onnx/graph/paddle_graph.py#L228).
__Edit__: I made [PR](https://github.com/PaddlePaddle/Paddle2ONNX/pull/351) to fix the issue in `paddle2onnx`.

**To Reproduce**
Run the following script:
```python
import paddle
import onnx


class MyLayer(paddle.nn.Layer):
    def __init__(self):
        super().__init__()
        self.register_buffer(
            "my_buffer",
            paddle.to_tensor(42, dtype='float32'),
            persistable=True  # <- look here
        )

    def forward(self, x):
        return x + self.my_buffer

    def export_to_onnx(self):
        spec = paddle.static.InputSpec([1])
        paddle.onnx.export(self, "/tmp/my-model", [spec])
        onnx.checker.check_model('/tmp/my-model.onnx')


def main():
    my_layer = MyLayer()
    print(f"persistable: {my_layer.my_buffer.persistable}")

    x = paddle.to_tensor(1, dtype='float32')
    y = my_layer(x)
    print(y)

    my_layer.export_to_onnx()


if __name__ == '__main__':
    main()
```

Output (notice the first line: `persistable: False`):
```text
persistable: False
W0924 07:45:48.262135 19075 device_context.cc:404] Please NOTE: device: 0, GPU Compute Capability: 7.5, Driver API Version: 11.2, Runtime API Version: 11.2
W0924 07:45:48.263864 19075 device_context.cc:422] device: 0, cuDNN Version: 8.2.
Tensor(shape=[1], dtype=float32, place=CUDAPlace(0), stop_gradient=True,
       [43.])
2021-09-24 07:45:49 [INFO]	ONNX model saved in /tmp/my-model.onnx
Traceback (most recent call last):
  File "/tmp/scripts/paddle_buffer_bug.py", line 35, in <module>
    main()
  File "/tmp/scripts/paddle_buffer_bug.py", line 31, in main
    my_layer.export_to_onnx()
  File "/tmp/scripts/paddle_buffer_bug.py", line 20, in export_to_onnx
    onnx.checker.check_model('/tmp/my-model.onnx')
  File "/usr/local/lib/python3.6/dist-packages/onnx/checker.py", line 96, in check_model
    C.check_model_path(model)
onnx.onnx_cpp2py_export.checker.ValidationError: Nodes in a graph must be topologically sorted, however input 'generated_tensor_0' of node: 
name: Add_0 OpType: Add
 is not output of any previous nodes.

Process finished with exit code 1
```

I confirmed (with the [Netron](https://netron.app/) viewer) that topological sorting is not the problem, instead the buffer data is indeed absent.

**System information**
- PaddlePaddle version:
```
paddle2onnx              0.8
paddlepaddle-gpu         2.1.0.post112
```
- CPU: `Intel i7-9750H (12) @ 4.500GHz`
- GPU: `GeForce GTX 1650`
- OS Platform and Distribution: `Ubuntu 20.04.2 LTS x86_64`
- Python version: `3.6.14`

**Comment by pangyoki** [comment]
Thank you for your contribution :)
