### ISSUE TITLE
 Warning: PaddlePaddle catches a failure signal, it may not work properly

### ISSUE THREAD

**Issue by NSL-Wx** [PaddlePaddle/Paddle#36050]
第一次运行程序出现问题，重启后再次运行问题还是一样。
版本、环境信息：
1）	PaddlePaddle版本：1.7.2 （cpu）
2）	CPU：Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz   3.19 GHz
3）	系统环境：Ubuntu18.04（虚拟机）
4）	Python版本号 3.6.13
5）	问题描述：
W0923 16:54:47.450151  3006 init.cc:209] Warning: PaddlePaddle catches a failure signal, it may not work properly
W0923 16:54:47.452323  3006 init.cc:211] You could check whether you killed PaddlePaddle thread/process accidentally or report the case to PaddlePaddle
W0923 16:54:47.452795  3006 init.cc:214] The detail failure signal is:

W0923 16:54:47.455102  3006 init.cc:217] *** Aborted at 1632387287 (unix time) try "date -d @1632387287" if you are using GNU date ***
W0923 16:54:47.456691  3006 init.cc:217] PC: @                0x0 (unknown)
W0923 16:54:47.459455  3006 init.cc:217] *** SIGSEGV (@0x55c64a38f320) received by PID 3006 (TID 0x7fb8c3c090c0) from PID 1245246240; stack trace: ***
W0923 16:54:47.460755  3006 init.cc:217]     @     0x7fb8c3048980 (unknown)
W0923 16:54:47.461793  3006 init.cc:217]     @     0x55c64a38f320 (unknown)
Segmentation fault (core dumped)

**Comment by pangyoki** [comment]
你好，请问这是在哪个阶段报错的？`import paddle`就报错吗？

**Comment by NSL-Wx** [comment]
import paddle.fluid as fluid 时报错。

**Comment by pangyoki** [comment]
> import paddle.fluid as fluid 时报错。

麻烦设置GLOG环境变量打印log看看，使用 `GLOG_v=10`来执行。

**Comment by NSL-Wx** [comment]
请问如何设置GLOG环境变量？

**Comment by pangyoki** [comment]
> 请问如何设置GLOG环境变量？

`export GLOG_v=10` 或者 在执行python时带上GLOG：`GLOG_v=10 python`

**Comment by NSL-Wx** [comment]
$ python convert.py GLOG_v=10
W0927 15:34:38.893525  4598 init.cc:209] Warning: PaddlePaddle catches a failure signal, it may not work properly
W0927 15:34:38.894294  4598 init.cc:211] You could check whether you killed PaddlePaddle thread/process accidentally or report the case to PaddlePaddle
W0927 15:34:38.894704  4598 init.cc:214] The detail failure signal is:

W0927 15:34:38.898312  4598 init.cc:217] *** Aborted at 1632728078 (unix time) try "date -d @1632728078" if you are using GNU date ***
W0927 15:34:38.899888  4598 init.cc:217] PC: @                0x0 (unknown)
W0927 15:34:38.900696  4598 init.cc:217] *** SIGSEGV (@0x55f8fa0a0320) received by PID 4598 (TID 0x7f705ca410c0) from PID 18446744073609544480; stack trace: ***
W0927 15:34:38.902043  4598 init.cc:217]     @     0x7f705be80980 (unknown)
W0927 15:34:38.905182  4598 init.cc:217]     @     0x55f8fa0a0320 (unknown)
Segmentation fault (core dumped)
使用指令后报错还是和以前一样。

**Comment by pangyoki** [comment]
> $ python convert.py GLOG_v=10
> W0927 15:34:38.893525 4598 init.cc:209] Warning: PaddlePaddle catches a failure signal, it may not work properly
> W0927 15:34:38.894294 4598 init.cc:211] You could check whether you killed PaddlePaddle thread/process accidentally or report the case to PaddlePaddle
> W0927 15:34:38.894704 4598 init.cc:214] The detail failure signal is:
> 
> W0927 15:34:38.898312 4598 init.cc:217] *** Aborted at 1632728078 (unix time) try "date -d @1632728078" if you are using GNU date ***
> W0927 15:34:38.899888 4598 init.cc:217] PC: @ 0x0 (unknown)
> W0927 15:34:38.900696 4598 init.cc:217] *** SIGSEGV (@0x55f8fa0a0320) received by PID 4598 (TID 0x7f705ca410c0) from PID 18446744073609544480; stack trace: ***
> W0927 15:34:38.902043 4598 init.cc:217] @ 0x7f705be80980 (unknown)
> W0927 15:34:38.905182 4598 init.cc:217] @ 0x55f8fa0a0320 (unknown)
> Segmentation fault (core dumped)
> 使用指令后报错还是和以前一样。

GLOG_v=10 放在python前试试呢？

**Comment by pangyoki** [comment]
你是怎么安装的呢？安装命令发给我下，我安装看下有没有问题？

**Comment by NSL-Wx** [comment]
$ GLOG_v=10 python convert.py
WARNING: Logging before InitGoogleLogging() is written to STDERR
I0927 16:24:20.862963  4800 pybind.cc:299] py_func has no kernels, skip
I0927 16:24:20.866158  4800 pybind.cc:299] recurrent has no kernels, skip
I0927 16:24:20.866176  4800 pybind.cc:299] while has no kernels, skip
I0927 16:24:20.866185  4800 pybind.cc:299] conditional_block has no kernels, skip
I0927 16:24:20.878691  4800 dynamic_loader.cc:89] Set paddle lib path : /home/wei/anaconda3/envs/LGSC/lib/python3.6/site-packages/paddle/libs
I0927 16:24:20.975239  4800 init.cc:66] Init commandline: dummy convert.py --tryfromenv=check_nan_inf,fast_check_nan_inf,benchmark,eager_delete_scope,fraction_of_cpu_memory_to_use,initial_cpu_memory_in_mb,init_allocated_mem,paddle_num_threads,dist_threadpool_size,eager_delete_tensor_gb,fast_eager_deletion_mode,memory_fraction_of_eager_deletion,allocator_strategy,reader_queue_speed_test_mode,print_sub_graph_dir,pe_profile_fname,inner_op_parallelism,enable_parallel_graph,fuse_parameter_groups_size,multiple_of_cupti_buffer_size,fuse_parameter_memory_size,tracer_profile_fname,dygraph_debug,use_system_allocator,enable_unused_var_check,free_idle_chunk,free_when_no_cache_hit,use_pinned_memory,cpu_deterministic,use_mkldnn,rpc_deadline,rpc_retry_times,rpc_server_profile_path,enable_rpc_profiler,rpc_send_thread_num,rpc_get_thread_num,rpc_prefetch_thread_num,rpc_disable_reuse_port,rpc_retry_bind_port,worker_update_interval_secs 
W0927 16:24:21.070617  4800 init.cc:209] Warning: PaddlePaddle catches a failure signal, it may not work properly
W0927 16:24:21.070953  4800 init.cc:211] You could check whether you killed PaddlePaddle thread/process accidentally or report the case to PaddlePaddle
W0927 16:24:21.076946  4800 init.cc:214] The detail failure signal is:

W0927 16:24:21.076961  4800 init.cc:217] *** Aborted at 1632731061 (unix time) try "date -d @1632731061" if you are using GNU date ***
W0927 16:24:21.077800  4800 init.cc:217] PC: @                0x0 (unknown)
W0927 16:24:21.077929  4800 init.cc:217] *** SIGSEGV (@0x55aa603d0320) received by PID 4800 (TID 0x7eff4a3210c0) from PID 1614611232; stack trace: ***
W0927 16:24:21.078542  4800 init.cc:217]     @     0x7eff49760980 (unknown)
W0927 16:24:21.079104  4800 init.cc:217]     @     0x55aa603d0320 (unknown)
Segmentation fault (core dumped)
放在python前的结果

**Comment by NSL-Wx** [comment]
PaddlePaddle安装指令：
python3 -m pip install paddlepaddle==1.7.2 -i https://mirror.baidu.com/pypi/simple

**Comment by pangyoki** [comment]
> Segmentation fault

我先看看这个错误信息哈。
如果你方便的话，可以尝试下docker行不行，docker里的软件环境都没问题。
可以用这个镜像：docker pull paddlepaddle/paddle:latest-gpu-cuda10.2-cudnn7-dev
在镜像里装cpu版的paddle即可。

**Comment by NSL-Wx** [comment]
好的

**Comment by NSL-Wx** [comment]
使用Docker进行安装需要将原本下载好的版本卸载掉么？

**Comment by pangyoki** [comment]
> 使用Docker进行安装需要将原本下载好的版本卸载掉么？

不需要。Docker是独立的环境。
另外，除了docker安装外，你也可以先下载新版本的paddle试试，应该更方便一点。有可能最新版的paddle可以使用。

**Comment by NSL-Wx** [comment]
更新paddlepaddle为最新版本后，运行原程序出现如下问题：
torch parm fc.weight not exist in paddle modle
torch parm fc.bias not exist in paddle modle

**Comment by NSL-Wx** [comment]
更新paddlepaddle为最新版本后，运行程序出现如下问题：
torch parm fc.weight not exist in paddle modle
torch parm fc.bias not exist in paddle modle

**Comment by pangyoki** [comment]
> 更新paddlepaddle为最新版本后，运行原程序出现如下问题： torch parm fc.weight not exist in paddle modle torch parm fc.bias not exist in paddle modle

import paddle没问题了是吧？现在这个问题看起来是模型load参数的问题，麻烦另外开个issue看下这个问题。
