### ISSUE TITLE
C++预测报错

### ISSUE THREAD

**Issue by wenjiett** [PaddlePaddle/Paddle#36073]
我在使用C++进行预测时，程序出现报错：0x00007FFA0C5C8A9B (nvcuda64.dll)处(位于 VS2017_paddle.exe 中)引发的异常: 0xC0000005: 读取位置 0x0000023E9CFFA000 时发生访问冲突。

我使用的版本环境信息：
-C++预测库版本：cuda10.2_cudnn7.6_avx_mkl_trt7
-Cuda:10.2
-Cudnn:7.6.5
-VS2017

代码如下：
#include "paddle/include/paddle_inference_api.h"
#include <chrono>
#include <iostream>
#include <memory>
#include <numeric>

using paddle_infer::Config;
using paddle_infer::Predictor;
using paddle_infer::CreatePredictor;

using Time = decltype(std::chrono::high_resolution_clock::now());
Time time() { return std::chrono::high_resolution_clock::now(); };
double time_diff(Time t1, Time t2) {
	typedef std::chrono::microseconds ms;
	auto diff = t2 - t1;
	ms counter = std::chrono::duration_cast<ms>(diff);
	return counter.count();
}

std::shared_ptr<Predictor> InitPredictor() {
	Config config;

	config.SetModel("F:/yolov3_r50vd_dcn_270e_coco/model.pdmodel", "F:/yolov3_r50vd_dcn_270e_coco/model.pdiparams");
	config.EnableUseGpu(100, 0);
	config.EnableMKLDNN();
	config.EnableMemoryOptim();

	return CreatePredictor(config);
}

void run(Predictor* predictor, const std::vector<float>& input,
	const std::vector<int>& input_shape, const std::vector<float>& input_im,
	const std::vector<int>& input_im_shape, std::vector<float>* out_data) {
	auto input_names = predictor->GetInputNames();
	auto im_shape_handle = predictor->GetInputHandle(input_names[0]);
	im_shape_handle->Reshape(input_im_shape);
	im_shape_handle->CopyFromCpu(input_im.data());

	auto image_handle = predictor->GetInputHandle(input_names[1]);
	image_handle->Reshape(input_shape);
	image_handle->CopyFromCpu(input_im.data());

	auto scale_factor_handle = predictor->GetInputHandle(input_names[2]);
	scale_factor_handle->Reshape(input_im_shape);
	scale_factor_handle->CopyFromCpu(input_im.data());

	predictor->Run();

	auto output_names = predictor->GetOutputNames();
	auto output_t = predictor->GetOutputHandle(output_names[0]);
	std::vector<int> output_shape = output_t->shape();
	int out_num = std::accumulate(output_shape.begin(), output_shape.end(), 1,
		std::multiplies<int>());

	out_data->resize(out_num);
	output_t->CopyToCpu(out_data->data());
}

int main(int argc, char* argv[]) {
	//google::ParseCommandLineFlags(&argc, &argv, true);
	auto predictor = InitPredictor();

	const int height = 608;
	const int width = 608;
	const int channels = 3;
	std::vector<int> input_shape = { 1, channels, height, width };
	std::vector<float> input_data(1 * channels * height * width);
	for (size_t i = 0; i < input_data.size(); ++i) {
		input_data[i] = i % 255 * 0.13f;
	}
	std::vector<int> input_im_shape = { 1, 2 };
	std::vector<float> input_im_data(1 * 2, 608);

	std::vector<float> out_data;
	run(predictor.get(), input_data, input_shape, input_im_data, input_im_shape,
		&out_data);
	return 0;
}

报错信息截图：
![info1](https://user-images.githubusercontent.com/64730376/134760696-dc728b9b-dbd2-45f6-9338-1b178caedb99.png)
![info2](https://user-images.githubusercontent.com/64730376/134760700-cf398c53-091e-42b0-acfe-b9a944b5d8c3.png)
![info3](https://user-images.githubusercontent.com/64730376/134760705-7d13cea9-df57-4e89-87ba-b393171131a3.png)

**Comment by fengxiaoshuai** [comment]
看样子是数据导入时候的问题，考虑im_shape_handle->CopyFromCpu(input_im.data())三个输入都是同样的是不是写法有问题？建议参考inference-demo或者paddle官网提供的教学步骤进行操作。

**Comment by wenjiett** [comment]
> 看样子是数据导入时候的问题，考虑im_shape_handle->CopyFromCpu(input_im.data())三个输入都是同样的是不是写法有问题？建议参考inference-demo或者paddle官网提供的教学步骤进行操作。

我就是跑的c++版yolov3的inference-demo，只是自己添加了模型路径，batch_size设为了1

**Comment by fengxiaoshuai** [comment]
10.2的cuda有问题，需要打补丁，你可以看看自己的系统环境选择相应的补丁， 下面是官网链接：https://developer.nvidia.com/cuda-10.2-download-archive?target_os=Linux&target_arch=x86_64&target_distro=Ubuntu&target_version=1604&target_type=runfilelocal
