### ISSUE TITLE
some conclusion on python api design

### ISSUE THREAD

**Issue by jacquesqiao** [PaddlePaddle/Paddle#3607]
1. we need VarName
2. NetOp  ==> Block
  a. Run(target=[VarName])
  b. Run from the very beginning
  c. Layer change the current block(addOp)
3. Reader need a GPU Buffer.
  a. need data load Operator
  b. data loader support load data asynchronously into GPU buffer.
4. Block  should create its own local scope(RNN/IfElseThen)

### for GAN
1. use only one scope
2. should have some method to generate unique variable name
  a. such as [name scope] in tensorflow. Is good for visualization.
3. Optimizer to optimize a parameter in a var_list
4. Support combination of multiple loss

**Comment by jacquesqiao** [comment]
1，参数初始化如何做，每一层参数初始化方法可能不一样。
2，InferShape，每个Op直接做InferShape，(RNN step_net)。
3，Block.Run(targets=[var1, var2])，多个Op修改同一个var。

**Comment by reyoung** [comment]
我觉得Block替换NetOp是OK的，增加一个`Run(Expression[] targets)`是可以的。
但是，这个Run targets有几个问题:

* 肯定是targets而不是一个target
* target的类型是什么? 
	* 如果简单的Variable Name的话:
		* 那么我们的Block中必然不允许两个Op输出同一个Variable，否则会有歧义
		* 但是，这就要求用户去指定:
			* 各种临时变量名字，可能有X', X''
		* 也需要用户指定哪些变量是share同一段内存的。
			* 例如SGD是从 W和G更新到W'的。
			* 用户要在Python端指定 W'.memory.share(W)
			* 这种指定的API是什么样子的？

* 所以我在Model那个设计里，推荐一个Expression类型
	* 包含 Variable Name和 Op在Net里面的index
	* 原理是，执行到哪个Op，仅仅从输出名字来判断是不可行的。需要从index判断。

**Comment by gongweibao** [comment]
Feel free to reopen it.
