### ISSUE TITLE
怎么会出现ReLU导入错误呢

### ISSUE THREAD

**Issue by ForZYX** [PaddlePaddle/Paddle#36074]
我在aistudio运行时发现的错误
ModuleNotFoundError: No module named 'paddle.nn.ReLU'
![图片](https://user-images.githubusercontent.com/62179813/134761617-72bc36a9-320b-4dbc-a676-d422c3fa47f6.png)

**Comment by wanghuancoder** [comment]
你好，你的paddle是什么版本呢？
能否尝试一下import paddle是否会报错？

**Comment by ForZYX** [comment]
paddle不会出错，版本是2.1.2

**Comment by wanghuancoder** [comment]
from paddle.nn import ReLU
改成这么写吧

**Comment by ForZYX** [comment]
你敢信？昨天在aistudio导入不了的，今天又能导入了（原封不动的代码）

**Comment by ForZYX** [comment]
不过还是要感谢您的回复，谢谢！
