### ISSUE TITLE
paddle网络通信机制

### ISSUE THREAD

**Issue by yinyunfeng** [PaddlePaddle/Paddle#3608]
1.  同步sgd时，parameter server会等待拿到所有gradient server的参数后再聚合梯度计算新参数？  而后同时去更新所有gradient server的参数吗？

2. 这个图里标红的两条线，是否应该上线顺序调整一下，parameter server 接收到所有gradient server梯度后再更新参数？

![image](https://user-images.githubusercontent.com/4621025/29546902-76708afe-8729-11e7-80b3-a6e85d18cf38.png)

3. 同步sgd时，parameter server之间不需要通信。
4. 异步sgd时，parameter server收到一个gradient server的梯度后就更新参数而不是收到所有gradient server的梯度后才更新对吗？parameter server 更新完参数后会分发给所有gradient server吗？ gradient server 提交梯度后会阻塞等待吗？

**Comment by typhoonzero** [comment]
1. 同步SGD情况下，parameter server是会等待拿到所有gradient server的上传的梯度之后再更新参数。
2. 的确是的，这个图是哪里出现的呢？
3,4. 不论同步SGD还是异步，parameter server之间都是没有通信的。

**Comment by yinyunfeng** [comment]
1. 同步sgd时，parameter server聚合梯度计算完参数后， 会同时去更新所有gradient server的参数吗？gradient server提交梯度之后未被更新参数之前是不是不能使用老参数继续计算新的梯度？

**Comment by reyoung** [comment]
> 同步sgd时，parameter server会等待拿到所有gradient server的参数后再聚合梯度计算新参数？ 而后同时去更新所有gradient server的参数吗？

是的。

> 这个图里标红的两条线，是否应该上线顺序调整一下，parameter server 接收到所有gradient server梯度后再更新参数？

不是的，DoOperator是由Controller发送给服务器，告诉服务器要执行SGD。这时候，服务器才会等待所有的GradientServer参数聚合。如果DoOperator不是发送的不是SGD，而是ASGD或者OWLQN，实现是不同的。

> 同步sgd时，parameter server之间不需要通信。

PServer之间永远不需要通信。

> 异步sgd时，parameter server收到一个gradient server的梯度后就更新参数而不是收到所有gradient server的梯度后才更新对吗？

对

> parameter server 更新完参数后会分发给所有gradient server吗？ 

只发送回这次提交梯度的那个GServer

> gradient server 收到新的参数并且本地正在计算新的参数，这时候冲突了，怎么办？

ASGD和SGD算法对于GradientServer或者Trainer逻辑都是一致的。

1. forward/backward
2. 把梯度发送给PServer
3. 从PServer拿回参数

同步和异步是在PServer端是否等待其他GServer的梯度。

**Comment by yinyunfeng** [comment]
ASGD和SGD算法，GradientServer在等待Pserver的返回参数时都会阻塞不再继续计算梯度吗？@reyoung

**Comment by reyoung** [comment]
> GradientServer在等待Pserver的返回参数时都会阻塞不再继续计算梯度吗？

是
