### ISSUE TITLE
ltr/ranknet   label是dense_vector，auc计算一直为0

### ISSUE THREAD

**Issue by jcqu** [PaddlePaddle/Paddle#3609]
在使用ltr/ranknet demo模型的时候发现test集auc一直为0，在issue上查找到相关问题：
 https://github.com/PaddlePaddle/Paddle/issues/2921  

#模型定义： 其中half_ranknet是两层fc层，output的size＝1
```python
def ranknet(input_dim):
    # label layer
    label = paddle.layer.data("label", paddle.data_type.dense_vector(1))
    #label = paddle.layer.data("label", paddle.data_type.integet_value)

    # reuse the parameter in half_ranknet
    output_left = half_ranknet("left", input_dim)
    output_right = half_ranknet("right", input_dim)

    paddle.evaluator.auc(input=output_left, label=label)
    # rankcost layer
    cost = paddle.layer.rank_cost(
        name="cost", left=output_left, right=output_right, label=label)
    return cost
```
#测试代码
```python
result = trainer.test(reader=test_reader, feeding=feeding)
print "\nTest with Pass %d, Cost %.9f,  %s" % (event.pass_id, result.cost, result.metrics)
```
输出
```python
Pass 0 Batch 0 Cost 0.693061905
Pass 0 Batch 100 Cost 0.662540054
Pass 0 Batch 200 Cost 0.622232933
Pass 0 Batch 300 Cost 0.549111252
Pass 0 Batch 400 Cost 0.479979477
Pass 0 Batch 500 Cost 0.440936203
Pass 0 Batch 600 Cost 0.359341202
Pass 0 Batch 700 Cost 0.259916248
Pass 0 Batch 800 Cost 0.266684170
Pass 0 Batch 900 Cost 0.221040401
Pass 0 Batch 1000 Cost 0.163941765
Pass 0 Batch 1100 Cost 0.152777176
Pass 0 Batch 1200 Cost 0.103145971
Test with Pass 0, Cost 0.116896157,  {'__auc_evaluator_0__': 0.0}
```
在demo 中 label定义为dense_vector(1), 请问现在这个问题可以简单解决了吗？如果必须要先从test中提取结果又该如何做呢，谢谢。

**Comment by lcy-seso** [comment]
请问 `output_left` 这个层是什么层呢？

**Comment by jcqu** [comment]
我把代码更新在问题描述里了，这个是demo原始的代码并未修改。我也奇怪为什么直接使用output_left。需要问下 auc的计算应该需要什么样的输入格式，这里是否需要将label修正成相应的两维dense，rank_cost是否需要做出相应修改。

**Comment by dzhwinter** [comment]
ranknet是pairwise的模型，左边和右边对称，output_left是模型的一半。对一个pair中的(A, B)，rnaknet infer时候想得到A的得分，那么只需要output_left。

**Comment by dzhwinter** [comment]
auc的问题发个PR修复一下吧。因为auc evaluator需要至少两维dense，改一下rank_cost的label输入就可以了

**Comment by jcqu** [comment]
就是说把输入的label改成dense_vector(2)，对于输入的一个样本（label，A，B），label应该是（1，0）A>B或者（0，1）A<B？

**Comment by dzhwinter** [comment]
没错。相当于multiclass的one hot label，现在是binary classification.

**Comment by jcqu** [comment]
好吧，那我修改一下试试看。谢谢

**Comment by jcqu** [comment]
@dzhwinter  我看代码 rank_cost指定了label必须是1维的呀
```python
assert label.size == 1
```
也就是说我必须使用classification_error_cost吗？请问具体该如何修改，谢谢

**Comment by jcqu** [comment]
@dzhwinter  如果我自己写评价函数该如何从trainer.test中获取测试结果呢？

**Comment by dzhwinter** [comment]
得到取值请参考代码中的infer函数，得到的score列表后可以用metrics里的ndcg评价函数算一下。
从trainer.test中取值请教一下 @lcy-seso 这个怎么做？

**Comment by jcqu** [comment]
@dzhwinter "metrics里的ndcg评价函数" 这个在哪里呀？并没有查到。

**Comment by dzhwinter** [comment]
在ltr目前的目录下有metrics.py这个文件

**Comment by HugoLian** [comment]
我也遇到了相同的问题，我目前用的label只是integer_value，还不是1唯的dense_vector，所以直接把label为int()的1, 变成[1,0]的输入，可以使用么？

**Comment by HugoLian** [comment]
另外，我看rank_cost的输出只能是size = 1, 所以用dense_vector(2) [1 ,0] 这样的训练样本输入也不行。。。那如何才能计算AUC呢？
