### ISSUE TITLE
paddle.jit.save()内存泄漏

### ISSUE THREAD

**Issue by Shawn6688** [PaddlePaddle/Paddle#36115]
- 标题：paddle.jit.save()内存泄漏
- 版本、环境信息：
    1）PaddlePaddle版本：2.1.2
    3）GPU：v100, cuda11.2, cuDNN Version: 8.1
    4）系统环境：ubuntu16.04, python 3.9.6
官方示例代码，每个epoch save()一次模型，内存持续增长直到爆掉，将save()注释掉则内存占用维持稳定。为了使内存泄漏更明显，将数据维度设的比较高，并且并行跑了10个程序。

![image](https://user-images.githubusercontent.com/3920920/134805652-90785b77-78e2-437b-9e20-6825b4a6dae4.png)

```
import numpy as np
import paddle
import paddle.nn as nn
import paddle.optimizer as opt
from paddle.static import InputSpec

BATCH_SIZE = 64
BATCH_NUM = 64
EPOCH_NUM = 100000

IMAGE_SIZE = 78400
CLASS_NUM = 100

# define a random dataset
class RandomDataset(paddle.io.Dataset):
    def __init__(self, num_samples):
        self.num_samples = num_samples

    def __getitem__(self, idx):
        image = np.random.random([IMAGE_SIZE]).astype('float32')
        label = np.random.randint(0, CLASS_NUM - 1, (1, )).astype('int64')
        return image, label

    def __len__(self):
        return self.num_samples

class LinearNet(nn.Layer):
    def __init__(self):
        super(LinearNet, self).__init__()
        self._linear = nn.Linear(IMAGE_SIZE, CLASS_NUM)

    def forward(self, x):
        return self._linear(x)

def train(layer, loader, loss_fn, opt):
    for epoch_id in range(EPOCH_NUM):
        for batch_id, (image, label) in enumerate(loader()):
            out = layer(image)
            loss = loss_fn(out, label)
            loss.backward()
            opt.step()
            opt.clear_grad()
            print("Epoch {} batch {}: loss = {}".format(
                epoch_id, batch_id, np.mean(loss.numpy())))
        # save
        path = "linear" + str(epoch_id) + '_' + str(batch_id)
        paddle.jit.save(
            layer=layer,
            path=path,
            input_spec=[InputSpec(shape=[None, 78400], dtype='float32')])

# create network
layer = LinearNet()
loss_fn = nn.CrossEntropyLoss()
adam = opt.Adam(learning_rate=0.001, parameters=layer.parameters())

# create data loader
dataset = RandomDataset(BATCH_NUM * BATCH_SIZE)
loader = paddle.io.DataLoader(dataset,
    batch_size=BATCH_SIZE,
    shuffle=True,
    drop_last=True,
    num_workers=2)

# train
train(layer, loader, loss_fn, adam)
```

**Comment by zhwesky2010** [comment]
@Shawn6688 您好，你的forward函数里没有加上 `@paddle.jit.to_static` 装饰器

**Comment by zhwesky2010** [comment]
@Shawn6688 您好，我目前加上了 `@paddle.jit.to_static` ，内存占用比较稳定，怀疑是这个问题。

**Comment by Shawn6688** [comment]
> @Shawn6688 您好，我目前加上了 `@paddle.jit.to_static` ，内存占用比较稳定，怀疑是这个问题。

![image](https://user-images.githubusercontent.com/3920920/134896167-8df92561-bb80-40ee-ae33-96ca40f07961.png)
我加上之后还是泄漏。

**Comment by chenwhql** [comment]
@Shawn6688 您好，这个问题我在最新的paddle版本上复现了一下，主要通过以下两种方式：

1. objgraph数据结构增长分析

在每个epoch开始前调用`objgraph.show_growth()`，查看新增的Python数据结构

```
def train(layer, loader, loss_fn, opt):
    for epoch_id in range(EPOCH_NUM):
        objgraph.show_growth()
        for batch_id, (image, label) in enumerate(loader()):
```

实验显示，程序仅在第1，2个epoch开始时有Python数据结构的新增（属于预期内行为），后续epoch均没有数据结构新增，这可以说明首先Python端没有导致内存泄漏

2. 内存增长观察

持续执行程序，用top观察指定进程的内存变化情况，30分钟以上内存占用比例无增长，始终稳定

![image](https://user-images.githubusercontent.com/22561442/141996168-5cd2d2a9-a37f-4259-89e0-3174f2e1b467.png)

这里未复现您说的情况，但不排除可能是之前有隐藏的bug已经被修复了，所以能麻烦您使用最新的paddle 2.2版本复现一下这个问题吗？如果仍然能复现，也希望您提供更详细的复现流程和方式，感谢

**Comment by Water2style** [comment]
老哥解决了吗

**Comment by Shawn6688** [comment]
> 老哥解决了吗

目前看起来是paddle cloud的问题，不是jit函数的问题

**Comment by bingzant** [comment]
目前在paddlecloud上也遇到了这个问题，paddle2.2.2上内存占用逐渐增加，训练速度随着epoch变慢（每个epoch调用一次jit.save)，换用paddle2.3.0，内存占用问题仍然存在，但训练速度似乎已不下降。但最后还是出现了内存占用逐渐增大，导致dataloader Worker卡死的情况，导致任务失败。
（我不能确定是paddle还是paddlecloud上的问题）
可以定位到，是每个epoch,paddle.jit.save()调用后，出现的内存占用增加的问题。（paddlecloud上观察，本地未观察）

补充第二天想到的一个临时解决方案：
1、在每个epoch存储模型的时候采用paddle.save()去存储。
2、当模型收敛后，再使用paddle.load()加载模型，用paddle.jit.save()存储。
测试之后，这个方案work了。
