### ISSUE TITLE
大模型 data layer size限制

### ISSUE THREAD

**Issue by yinyunfeng** [PaddlePaddle/Paddle#3611]
配置大模型时，稀疏特征的data layer size是否仍然限制输入特征id应该小于size?  特征维度千亿级的情况下，单机不可能完成特征id映射。反而给特征一个int64的 sign签名 比较方便，但是这样会超过data layer size，paddle是否可以支持特征用sign，而不是id

**Comment by zhangyong15** [comment]
可以先将训练数据做ID映射处理，而非dataprovider截断再映射ID。

**Comment by yinyunfeng** [comment]
不管是对训练数据还是dataprovider映射，都需要把所有特征到id的映射关系放到内存吧，特征千亿级的时候，内存放不下，这就需要分布式的方案，很不方便          @zhangyong15

**Comment by reyoung** [comment]
> 配置大模型时，稀疏特征的data layer size是否仍然限制输入特征id应该小于size? 特征维度千亿级的情况下，单机不可能完成特征id映射。反而给特征一个int64的 sign签名 比较方便，但是这样会超过data layer size，paddle是否可以支持特征用sign，而不是id

限制，千亿级别下可以把data_layer的size设置成一个比较大的数字。

**Comment by yinyunfeng** [comment]
如果给data_layer size一个很大的值，比如亿亿级，那模型会变的非常非常大吧？ 还是paddle对大模型这方面有优化，不会增加模型大小  ？    @reyoung

**Comment by reyoung** [comment]
> 如果给data_layer size一个很大的值，比如亿亿级，那模型会变的非常非常大吧？ 还是paddle对大模型这方面有优化，不会增加模型大小 ？ @reyoung

模型会变大。Paddle这边没有这方面的优化。

Paddle这边需要预先设计一下模型最大的维度是多少。如果你的特征本身就有千亿级别，那就取特征的最大ID就好(假设特征ID是连续的)。
