### ISSUE TITLE
core_avx.so 不能动态链接 libcudart.so的问题

### ISSUE THREAD

**Issue by chensusu11** [PaddlePaddle/Paddle#36128]
1）PaddlePaddle版本：2.0
    2）GPU：RTX3070，CUDA 11.2
    3）系统环境：ubuntu18.04、Python3.6

- 安装方式信息：
1）docker安装
2）docker编译：cmake .. -DPY_VERSION=3.6 -DWITH_GPU=ON -DWITH_DSO=ON 
                           -DCUDA_USE_STATIC_CUDA_RUNTIME=OFF -DCMAKE_BUILD_TYPE=Release -DCUDA_ARCH_NAME=Auto

- 问题描述：请详细描述您的问题，同步贴出报错信息、日志/代码关键片段
core_avx.so 不能动态链接 libcudart.so,如下图：
![Uploading image.png…]()

但是按照前辈的方法：https://github.com/PaddlePaddle/Paddle/issues/20765   
libwarpctc.so 确实可以动态链接到 libcudart.so， 但是core_avx.so不知道怎么设置？

**Comment by chensusu11** [comment]
ms002-System-Product-Name /paddle {release/2.0} ldd ./build/python/build/lib.linux-x86_64-3.6/paddle/fluid/core_avx.so
        linux-vdso.so.1 (0x00007ffc44dde000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f42fa66b000)
        librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f42fa463000)
        libiomp5.so => /paddle/./build/python/build/lib.linux-x86_64-3.6/paddle/fluid/../libs/libiomp5.so (0x00007f42fa06e000)
        libdnnl.so.2 => /paddle/./build/python/build/lib.linux-x86_64-3.6/paddle/fluid/../libs/libdnnl.so.2 (0x00007f42f7e45000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f42f7c41000)
        libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f42f78b9000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f42f751b000)
        libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f42f7303000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f42f6f12000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f433ad40000)
        libgomp.so.1 => /usr/lib/x86_64-linux-gnu/libgomp.so.1 (0x00007f42f6ce3000)
发现core_avx.so 没有动态链接到 libcudart.so

**Comment by chensusu11** [comment]
CMakeList中这两个选项，不知道需不需要修改呢？  
 option(MSVC_STATIC_CRT "use static C Runtime library by default" ON) 
 set(CMAKE_SUPPRESS_REGENERATION ON)

**Comment by chensusu11** [comment]
``CUDA_SEPARABLE_COMPILATION`` (Default: ``OFF``)
  If set this will enable separable compilation for all CUDA runtime object
  files.  If used outside of ``cuda_add_executable()`` and ``cuda_add_library()``
  (e.g. calling ``cuda_wrap_srcs()`` directly),
  ``cuda_compute_separable_compilation_object_file_name()`` and
  ``cuda_link_separable_compilation_objects()`` should be called.

这个编译选项到底是设置为 ON 还是OFF 哇？默认是OFF,为什么还要额外指定呢？

**Comment by haozech** [comment]
您的问题已收到，可以尝试下更简单的https://www.paddlepaddle.org.cn/documentation/docs/zh/install/pip/linux-pip.html pip安装。core_avx.so的动态链接问题在处理哈

**Comment by chensusu11** [comment]
> 您的问题已收到，可以尝试下更简单的https://www.paddlepaddle.org.cn/documentation/docs/zh/install/pip/linux-pip.html pip安装。core_avx.so的动态链接问题在处理哈

hi，pip安装默认都是静态链接 libcudart文件，我的需求是动态链接 libcudart.so文件，谢谢！

**Comment by haozech** [comment]
> > 您的问题已收到，可以尝试下更简单的https://www.paddlepaddle.org.cn/documentation/docs/zh/install/pip/linux-pip.html pip安装。core_avx.so的动态链接问题在处理哈
> 
> hi，pip安装默认都是静态链接 libcudart文件，我的需求是动态链接 libcudart.so文件，谢谢！

您好，我们目前是动态链接的libcudart，只是没有通过ldd做，而是通过动态加载的方式进行的，所以ldd命令看不到动态库。

**Comment by chensusu11** [comment]
> > > 您的问题已收到，可以尝试下更简单的https://www.paddlepaddle.org.cn/documentation/docs/zh/install/pip/linux-pip.html pip安装。core_avx.so的动态链接问题在处理哈
> > 
> > 
> > hi，pip安装默认都是静态链接 libcudart文件，我的需求是动态链接 libcudart.so文件，谢谢！
> 
> 您好，我们目前是动态链接的libcudart，只是没有通过ldd做，而是通过动态加载的方式进行的，所以ldd命令看不到动态库。

您好，没太理解这个动态加载，但是我这边还是静态去找 libcudart了，您可以参考一下问题#20765 吗？我就是遇到和他相同的问题。 还有core_avx.so和 libwarpctc.so 不太一样，libwarpctc.so 通过ldd 就可以看到去找 libcudart.so 文件了，但是core_avx.so没有，谢谢了！
