### ISSUE TITLE
将abs算子保存为模型文件时报错

### ISSUE THREAD

**Issue by KhantiInNaraka** [PaddlePaddle/Paddle#36129]
- 版本、环境信息：
    1）PaddlePaddle版本：2.1
    2）CPU：Intel(R) Core(TM) i5-6600 CPU @ 3.30GHz
    4）系统环境：ubuntu16.04，Python3.8
 注：您可以通过执行[summary_env.py](https://github.com/PaddlePaddle/Paddle/blob/develop/tools/summary_env.py)获取以上信息。
只是把一个abs运算存储为模型文件，代码如下：

import paddle
import numpy as np

paddle.enable_static()

main_program = paddle.static.default_main_program()
startup_program = paddle.static.default_startup_program()
with paddle.static.program_guard(main_program, startup_program):
缩进a = paddle.static.data(name="x", shape=[3], dtype='float32')
缩进z = paddle.abs(a)
exe = paddle.static.Executor(paddle.CPUPlace())
exe.run(startup_program)
path_prefix = "./abs_model"
paddle.static.save_inference_model(path_prefix, [a], [z], exe)

/*******************/

报错信息如下:

/home/bitmain/anaconda3/envs/py38/lib/python3.8/site-packages/paddle/fluid/executor.py:1150: UserWarning: There are no operators in the program to be executed. If you pass Program manually, please use fluid.program_guard to ensure the current Program is being used.
  warnings.warn(error_info)
/home/bitmain/anaconda3/envs/py38/lib/python3.8/site-packages/paddle/static/io.py:378: UserWarning: no variable in your model, please ensure there are any variables in your model to save
  warnings.warn("no variable in your model, please ensure there are any "
Traceback (most recent call last):
  File "paddle_save_abs.py", line 20, in <module>
    paddle.static.save_inference_model(path_prefix, [a], [z], exe)
  File "<decorator-gen-238>", line 2, in save_inference_model
  File "/home/bitmain/anaconda3/envs/py38/lib/python3.8/site-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
    return wrapped_func(*args, **kwargs)
  File "/home/bitmain/anaconda3/envs/py38/lib/python3.8/site-packages/paddle/fluid/framework.py", line 234, in __impl__
    return func(*args, **kwargs)
  File "/home/bitmain/anaconda3/envs/py38/lib/python3.8/site-packages/paddle/static/io.py", line 517, in save_inference_model
    save_to_file(params_path, params_bytes)
  File "/home/bitmain/anaconda3/envs/py38/lib/python3.8/site-packages/paddle/static/io.py", line 426, in save_to_file
    raise ValueError("'content' type should be bytes.")
ValueError: 'content' type should be bytes.

**Comment by haozech** [comment]
你好，如果想这样做需要用之前的组网方式进行组网，请参考
`import paddle
import paddle.fluid as fluid

paddle.enable_static()

path = "./infer_model"

image = fluid.layers.data(name='img', shape=[1, 28, 28], dtype='float32')
label = fluid.layers.data(name='label', shape=[1], dtype='int64')
feeder = fluid.DataFeeder(feed_list=[image, label], place=fluid.CPUPlace())
predict = paddle.abs(image)

exe = fluid.Executor(fluid.CPUPlace())
exe.run(fluid.default_startup_program())

fluid.io.save_inference_model(dirname=path, feeded_var_names=['img'], target_vars=[predict], executor=exe)`

https://www.paddlepaddle.org.cn/documentation/docs/zh/1.8/api_cn/io_cn/save_inference_model_cn.html#save-inference-model

**Comment by KhantiInNaraka** [comment]
> 你好，如果想这样做需要用之前的组网方式进行组网，请参考 `import paddle import paddle.fluid as fluid
> 
> paddle.enable_static()
> 
> path = "./infer_model"
> 
> image = fluid.layers.data(name='img', shape=[1, 28, 28], dtype='float32') label = fluid.layers.data(name='label', shape=[1], dtype='int64') feeder = fluid.DataFeeder(feed_list=[image, label], place=fluid.CPUPlace()) predict = paddle.abs(image)
> 
> exe = fluid.Executor(fluid.CPUPlace()) exe.run(fluid.default_startup_program())
> 
> fluid.io.save_inference_model(dirname=path, feeded_var_names=['img'], target_vars=[predict], executor=exe)`
> 
> https://www.paddlepaddle.org.cn/documentation/docs/zh/1.8/api_cn/io_cn/save_inference_model_cn.html#save-inference-model

谢谢，但我试过，新的组网方式组一个加法是没问题的，z=a+b这样。

**Comment by peiwenYe** [comment]
> 
您好，请问这个问题您解决了吗？我也遇到一样的问题
