### ISSUE TITLE
V2集群客户端环境报错-"No module named poster"

### ISSUE THREAD

**Issue by nuttybamboo** [PaddlePaddle/Paddle#3612]
通过WIKI中提供的deploy.sh 和 paddle_platform_client_ff01840260d5a3607596a7e2b3cd4f705ff75e78.tgz安装集群客户端，运行demo时报错“No module named poster”
![error](https://user-images.githubusercontent.com/488737/29548528-2b280170-8734-11e7-86a5-cb3d896e7518.png)

当前python库为安装paddle-paddle
(curl -s http://gitlab.baidu.com/yuyang18/PaddleInstall/raw/master/install_paddle.sh | bash -s [GPU|CPU] [DIRECTORY])
时附带的python27

**Comment by typhoonzero** [comment]
请尝试手动安装下`poster`: `pip install poster`
