### ISSUE TITLE
训练错误信息 Aborted at 1632644219 (unix time) try date -d @1632644219

### ISSUE THREAD

**Issue by terminator314** [PaddlePaddle/Paddle#36130]
- 版本、环境信息：
PaddlePaddle版本：paddlepaddle-gpu==1.8.5.post107
GPU：Tesla T4
Driver Version: 418.211
CUDA Version: 10.1
cuDNN version: 8.0.5
python version: 3.6.8 (GCC 4.8.5)
CentOS Linux release 7.9.2009 (Core)
 
**但是通过执行**[summary_env.py](https://github.com/PaddlePaddle/Paddle/blob/develop/tools/summary_env.py)获取以上信息。
[root@ecs-baidu-x-gpu-test Downloads]# python3 summary_env.py
TensorRT dynamic library (libnvinfer.so) that Paddle depends on is not configured correctly. (error code is libnvinfer.so: cannot open shared object file: No such file or directory)
  Suggestions:
  1. Check if TensorRT is installed correctly and its version is matched with paddlepaddle you installed.
  2. Configure TensorRT dynamic library environment variables as follows:
  - Linux: set LD_LIBRARY_PATH by `export LD_LIBRARY_PATH=...`
  - Windows: set PATH by `set PATH=XXX;****************************************
Paddle version: 1.8.5
Paddle With CUDA: True
OS: CentOS Linux 7
Python version: 3.6.8
CUDA version: 10.1.168
cuDNN version: None.None.None
Nvidia driver version: 418.211.00
****************************************

- 训练信息
    1）单机，T4 单卡，云服务器8核16G
    2）显存信息：16G
    

- 复现信息：https://github.com/terminator314/mask_recognition
 
- 问题描述：代码在jupyter运行。调用CPU时模型可正常在静态图模式下训练，调用GPU进行静态图模式训练时jupyter内核会挂掉，操作系统报一个’检测到python3-3.6.8-18.el17软件包的一个问题‘。
具体报错信息：

W0926 16:16:56.865593 10933 device_context.cc:260] device: 0, cuDNN Version: 8.0.
W0926 16:16:59.773133 10933 init.cc:226] Warning: PaddlePaddle catches a failure signal, it may not work properly
W0926 16:16:59.773157 10933 init.cc:228] You could check whether you killed PaddlePaddle thread/process accidentally or report the case to PaddlePaddle
W0926 16:16:59.773160 10933 init.cc:231] The detail failure signal is:

W0926 16:16:59.773165 10933 init.cc:234] *** Aborted at 1632644219 (unix time) try "date -d @1632644219" if you are using GNU date ***
W0926 16:16:59.774632 10933 init.cc:234] PC: @ 0x0 (unknown)
W0926 16:16:59.774744 10933 init.cc:234] *** SIGSEGV (@0x0) received by PID 10933 (TID 0x7f5ce6b3f740) from PID 0; stack trace: ***
W0926 16:16:59.776057 10933 init.cc:234] @ 0x7f5ce6208630 (unknown)
W0926 16:16:59.777312 10933 init.cc:234] @ 0x0 (unknown)
[I 16:18:42.495 NotebookApp] Saving file at /x_program/program_6/xcv_lab6.ipynb
[I 16:23:41.826 NotebookApp] Kernel interrupted: 8a085c39-91e4-4f0a-a7b0-39001f15c252
![BCD5397D-1B2D-45e6-AED4-32299D9D46AD](https://user-images.githubusercontent.com/20129376/134836211-f0775623-d170-4356-9a7d-f9b7ee366dd4.png)

**Comment by haozech** [comment]
你好，从下面这个报错来看无法确定是否是paddle的问题，但从上面的信息来看，你的环境中TRT没有正确设置，建议检查下：
`
Check if TensorRT is installed correctly and its version is matched with paddlepaddle you installed.
Configure TensorRT dynamic library environment variables as follows:
Linux: set LD_LIBRARY_PATH by export LD_LIBRARY_PATH=...
`

**Comment by terminator314** [comment]
TensorRT是推理加速的，我是在云服务器上跑，跟这个没多大关系吧

**Comment by terminator314** [comment]
> 你好，从下面这个报错来看无法确定是否是paddle的问题，但从上面的信息来看，你的环境中TRT没有正确设置，建议检查下：
> `Check if TensorRT is installed correctly and its version is matched with paddlepaddle you installed. Configure TensorRT dynamic library environment variables as follows: Linux: set LD_LIBRARY_PATH by export LD_LIBRARY_PATH=...`

TensorRT是推理加速的，我是在云服务器上跑，跟这个没多大关系吧

**Comment by terminator314** [comment]
问题已经定位解决，是环境问题
