### ISSUE TITLE
使用预测库C#部署后，多线程调用对预测速度影响

### ISSUE THREAD

**Issue by sosan-nian** [PaddlePaddle/Paddle#36137]
为使您的问题得到快速解决，在建立Issue前，请您先通过如下方式搜索是否有相似问题:【搜索issue关键字】【使用labels筛选】【官方文档】

如果您没有查询到相似问题，为快速解决您的提问，建立issue时请提供如下细节信息：
- 标题：简洁、精准描述您的问题，例如“最新预测库的API文档在哪儿 ”
- 版本、环境信息：
    1）PaddlePaddle版本：2.1.2
    2）CPU：
    3）GPU：请提供GPU型号3070、CUDA 11.0和CUDNN 8.1版本号
    4）系统环境：win10
注：您可以通过执行[summary_env.py](https://github.com/PaddlePaddle/Paddle/blob/develop/tools/summary_env.py)获取以上信息。
-预测信息
    1）C#预测：请您提供预测库安装包的版本信息，及其中的version.txt文件
    2）CMake包含路径的完整命令
    3）API信息（如调用请提供）
    4）预测库来源：官网下载
- 复现信息：如为报错，请给出复现环境、复现步骤
- 问题描述：请详细描述您的问题，同步贴出报错信息、日志/代码关键片段

我使用paddle2.1.2，显卡2080，cuda10.2.c#部署完成后测试分割模型预测速度大概20ms，但是如果我使用多个线程同时加载多个模型进行预测（暂时测试了4个线程），每个线程的预测速度明显下降，到了100ms以上，感觉随着线程增加速度是逐渐下降的，请问是否跟预测库的资源分配有关系？

**Comment by jiweibo** [comment]
您好，如果是多个线程在一个GPU上预测的话，性能是会比较差的，因为多线程launch的开销以及launch到gpu stream上也要排队，可以考虑每个线程/进程选择一张卡去跑。

**Comment by huangwan-jiayi** [comment]
> 为使您的问题得到快速解决，在建立Issue前，请您先通过如下方式搜索是否有相似问题:【搜索issue关键字】【使用labels筛选】【官方文档】
> 
> 如果您没有查询到相似问题，为快速解决您的提问，建立issue时请提供如下细节信息：
> 
> * 标题：简洁、精准描述您的问题，例如“最新预测库的API文档在哪儿 ”
> * 版本、环境信息：
>   1）PaddlePaddle版本：2.1.2
>   2）CPU：
>   3）GPU：请提供GPU型号3070、CUDA 11.0和CUDNN 8.1版本号
>   4）系统环境：win10
>   注：您可以通过执行[summary_env.py](https://github.com/PaddlePaddle/Paddle/blob/develop/tools/summary_env.py)获取以上信息。
>   -预测信息
>   1）C#预测：请您提供预测库安装包的版本信息，及其中的version.txt文件
>   2）CMake包含路径的完整命令
>   3）API信息（如调用请提供）
>   4）预测库来源：官网下载
> * 复现信息：如为报错，请给出复现环境、复现步骤
> * 问题描述：请详细描述您的问题，同步贴出报错信息、日志/代码关键片段
> 
> 我使用paddle2.1.2，显卡2080，cuda10.2.c#部署完成后测试分割模型预测速度大概20ms，但是如果我使用多个线程同时加载多个模型进行预测（暂时测试了4个线程），每个线程的预测速度明显下降，到了100ms以上，感觉随着线程增加速度是逐渐下降的，请问是否跟预测库的资源分配有关系？

大佬，你这个20ms，是在PC上自己训练的模型然后用C++部署在PC上吗？
是哪个分割模型呢？是训练的自己的数据集吗？为啥我在PC上用自己的数据集训练了BisenetV2模型C++部署在jetson nx上 run一次下来平均要100多ms呢？大佬我们可以交流交流吗？方便的话可以加个联系方式吗？
