### ISSUE TITLE
用padddleseg自己训练的模型，用python部署在jetson nx 上失败 ，显示需要打开trt动态模式，预测代码中已打开还是报错。

### ISSUE THREAD

**Issue by huangwan-jiayi** [PaddlePaddle/Paddle#36156]
报错信息：
![image](https://user-images.githubusercontent.com/71338215/134861898-e11a0249-403e-414f-a583-2f01f8ac6ff1.png)
预测代码：
![image](https://user-images.githubusercontent.com/71338215/134862031-f12cb877-e500-41ce-a777-924f09125567.png)
自己在jetson nx上编译的预测库：
![image](https://user-images.githubusercontent.com/71338215/134862238-e5c46025-9c5a-4d58-ba24-32ad0bf458d6.png)

**Comment by haozech** [comment]
如果不需要int8离线量化的话可以关店use_calib_mode，然后用这个开trt动态shape
`
config.SetTRTDynamicShapeInfo(min_input_shape, max_input_shape,
                                opt_input_shape);
`
