### ISSUE TITLE
`paddle` doesn't respect `DATA_HOME` from `HUB_HOME` environment variable.

### ISSUE THREAD

**Issue by nihirv** [PaddlePaddle/Paddle#36170]
The issue is that `paddle` doesn't respect `DATA_HOME` from the `HUB_HOME` environment variable.

That is, if I write code like this:
```python
import os
os.environ["HUB_HOME"] = "paddlehome"
import paddlehub as hub

model = hub.Module(name='U2Net')
```

Then I get a local folder `paddlehome` which has some folders in it (this is used by the `paddlehub` library). Inside `paddlehub`, we use `DATA_HOME = HUB_HOME + "dataset"` (see `paddlehub.env` line 64)

However, in `paddle.dataset.common`, DATA_HOME is always coming from the root user (Line 31 and 32):
```python
HOME = os.path.expanduser('~')
DATA_HOME = os.path.join(HOME, '.cache', 'paddle', 'dataset')
```

I believe that `DATA_HOME` should come from `HUB_HOME + "dataset"` if `HUB_HOME` is in `os.environ`

Paddlepaddle version: 2.1.3
Paddlehub version: 2.1.0

**Comment by qili93** [comment]
Hi @nihirv ,

Yes, Paddle and PaddleHub as two individual repos, defined their own `DATA_HOME` in code. And this is expected, as other repos such as PaddleNLP, PaddleDetection will also defined their own `DATA_HOME` in their code. And we expect user to only use the datasets defined in specific repo when using the corresponding models in the repo.

That is, ideally if you use PaddleHub models, then you should use the datasets defined in PaddleHub only. The common datasets defined in Paddle maybe not suitable for PaddleHub. 

There is still an workaround if you would like to use common datasets of Paddle for PaddleHub models, is that you can softlink your HUB_HOME dir to `~/.cache/paddle/`, so you will be able to find the datasets in paddle common code.

Btw, just curious about your scenario of using Paddle common datasets for PaddleHub models. Please kindly help to share whether the datasets defined in PaddleHub is not enough or not work?

Thanks

**Comment by nihirv** [comment]
Thanks for the response!

I understand they're different repos, hence it would make sense for them to have their own different `DATA_HOME`. However, across the Paddle ecosystem, `HUB_HOME` seems to be the only way I can change a caching location. It could be worth allowing to change caching locations for the other paddle repos too.

Saying this, one of your points is interesting... I'm actually not explicitly using `Paddle`, so I'm unclear why datasets inside of `Paddle` is being called. This is the full code I'm running:
```python
import os
os.environ["HUB_HOME"] = "paddlehome"
import paddlehub as hub

model = hub.Module(name='U2Net')

def infer(images):
  results = []

  for img in images:
   result = model.Segmentation(
      images=[img],
      paths=None,
      batch_size=1,
      input_size=320,
      output_dir='output',
      visualization=True)
   results.append(result[0]['front'][:,:,::-1])
  return results
```

and `paddlehub` itself is calling `Paddle`, which is calling `DATA_HOME`.

The reason I have this issue is because I'm on a server which doesn't allow me to write to the home directory. The server will have a fresh install of `Paddle` and thus `Paddle` will need to redownload things into the cache every time. I imagine this is why datasets is being called (because it hasn't already been initialised). We will be looking into how to improve our workflow so that the redownloading doesn't happen - but this would require us to set the cache dir ourselves. Softlinking also wouldn't work in this usecase either (as we **don't** want to write to /home/).

**Comment by qili93** [comment]
Thanks @nihirv for your response, understand the scenario. 

And I think this maybe a problem in PaddleHub, as your code here is just an inference job and should not need to download datasets of Paddle. Let me try to reproduce your issue in my local environment and I will double confirm with our developers of PaddleHub and try to provide a solution/fix ASAP.

**Comment by qili93** [comment]
Hi @nihirv,

I tried to reproduce your case, while failed. What I observed is this line of code not take effect `os.environ["HUB_HOME"] = "paddlehome"`, which result in downloading UNet models to `~/.paddlehub/tmp/` always.

The following is my reproduce steps:

1. install 

```
pip install paddlepaddle-gpu==2.1.3.post101 -f https://www.paddlepaddle.org.cn/whl/linux/mkl/avx/stable.html
pip install --upgrade paddlehub==2.1.0 -i https://mirror.baidu.com/pypi/simple
```

2. remove all existing folders under home foler

```
rm -rf ~/.cache*
rm -rf ~/.paddlehub*
```

3. edit env.py in your install environment

```
pip show paddlehub
# It told me the installation location is:
# Location: /opt/conda/lib/python3.7/site-packages
```

```
# Then edit env.py to show HUB_HOME value
vim /opt/conda/lib/python3.7/site-packages/paddlehub/env.py
```

Add the following code at the end of `env.py` to print HUB_HOME

```
print("------------------------------")
print("HUB_HOME={}".format(HUB_HOME))
print("------------------------------")
```

4. run your demo code, got the following output, the HUB_HOME is still ~/.paddlehub  and it downloads U2Net.tar.gz

```
------------------------------
HUB_HOME=/root/.paddlehub
------------------------------
Download https://bj.bcebos.com/paddlehub/paddlehub_dev/U2Net.tar.gz
[##################################################] 100.00%
Decompress /root/.paddlehub/tmp/tmpfia2o16w/U2Net.tar.gz
[##################################################] 100.00%
[2021-09-29 10:09:13,191] [    INFO] - Successfully installed U2Net-1.0.0
```

5. run demo after export by command line again

```
export HUB_HOME=/workspace/tempcode/paddle/paddlehome
```

Got the following output:

```
------------------------------
HUB_HOME=/workspace/tempcode/paddle/paddlehome
------------------------------
Download https://bj.bcebos.com/paddlehub/paddlehub_dev/U2Net.tar.gz
[##################################################] 100.00%
Decompress /workspace/tempcode/paddle/paddlehome/tmp/tmpk7gr4knh/U2Net.tar.gz
[##################################################] 100.00%
[2021-09-29 10:17:04,753] [    INFO] - Successfully installed U2Net-1.0.0
W0929 10:17:04.886390 20828 device_context.cc:404] Please NOTE: device: 0, GPU Compute Capability: 7.0, Driver API Version: 11.2, Runtime API Version: 10.1
W0929 10:17:04.892668 20828 device_context.cc:422] device: 0, cuDNN Version: 7.6.
```

And after all the above steps, I found that `~/.cache/paddle/dataset/` is created but nothing is download to it.

```bash
$ ls -la ~/.cache/paddle/dataset/
total 8.0K
drwxr-xr-x 2 root root 4.0K Sep 29 10:16 ./
drwxr-xr-x 3 root root 4.0K Sep 29 10:16 ../
```

Please kindly help to confirm if the above is the same problem or not. If yes, propose to export HUB_HOME by command line explicitly instead of assign the value in your code.

**Comment by nihirv** [comment]
Hey man, thanks for the lengthy look into this.

I'll check this out on my laptop shortly and report back. Out of curiosity, where did you run the python command from?

If you ran it from your home dir (e.g. in `~` you ran `python /workspace/tempcode/paddle/demo.py` it'll create the .paddlehome folder in your `~` dir. But if you ran `python demo.py` from `/workspace/tempcode/paddle` then it should create .paddlehome folder in the paddle folder

**Comment by nihirv** [comment]
Hi @qili93. I'm not entirely sure what's going on in your setting. when I run your step 4, I get the `HUB_HOME` in the appropriate directory:

```
(paddletest) USER@SERVER:/data/USER/machine_drive/paddletest$ python paddletest.py
------------------------------
HUB_HOME=paddlehome
------------------------------
```

My above message from a few days ago isn't correct because even if you ran it from `~`, I'd expect to see `/root/.paddlehome`, not `/root/.paddlehub`

**Comment by qili93** [comment]
Hi @nihirv ,

Sorry for my late response, seems that I cannot reproduce your problem in my environment. And I think we need to figure out why some common datasets are downloaded into your  "~/.cache/paddle/dataset/".

Please help try to add some lines of code to your paddle code:
https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/dataset/common.py#L63

The same way to find the common.py in your installation code
vim /opt/conda/lib/python3.7/site-packages/paddle/dataset/common.py

Add some lines of code as following:

```python
def download(url, module_name, md5sum, save_name=None):
    print("save_name", save_name) # add code here
    import traceback # add code here
    traceback.print_stack() # add code here
    dirname = os.path.join(DATA_HOME, module_name)
```

And your demo will throw exception when try to download some common datasets when it try to call the download function. And the the traceback stack will told you why the download function is called.

Please attach the full python traceback stack code here, thanks!
