### ISSUE TITLE
导入inference model时报错

### ISSUE THREAD

**Issue by Sunyingbin** [PaddlePaddle/Paddle#36182]
paddlepaddle 2.1.0 python 3.7

我从网上爬取的数据做预测任务，部分代码如下：
    # list转成numpy array
    numpy_data_tmp = np.array(data)
    # 上下翻转
    numpy_data = np.flipud(numpy_data_tmp)
    pred = loaded_layer(numpy_data)

报错如下：
Traceback (most recent call last):
  File "/Users/sunyingbin/Documents/workspace/loadforecast/ssq/ssq.py", line 69, in <module>
    inference_predict(inference_path, 21110, test_x)
  File "/Users/sunyingbin/Documents/workspace/loadforecast/ssq/dnn_ssq.py", line 287, in inference_predict
    pred2 = loaded_layer(test_x[0])
  File "/opt/anaconda3/envs/paddleocr/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 902, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/opt/anaconda3/envs/paddleocr/lib/python3.7/site-packages/paddle/fluid/dygraph/io.py", line 1191, in __i_m_p_l__
    return _run_dygraph(self, input, program_holder)
  File "/opt/anaconda3/envs/paddleocr/lib/python3.7/site-packages/paddle/fluid/dygraph/io.py", line 754, in _run_dygraph
    'is_test': instance._is_test
  File "/opt/anaconda3/envs/paddleocr/lib/python3.7/site-packages/paddle/fluid/dygraph/tracer.py", line 45, in trace_op
    not stop_gradient)
RuntimeError: (NotFound) Operator (matmul) does not have kernel for data_type[int64_t]:data_layout[ANY_LAYOUT]:place[CPUPlace]:library_type[PLAIN].
  [Hint: Expected kernel_iter != kernels.end(), but received kernel_iter == kernels.end().] (at /home/Paddle/paddle/fluid/framework/operator.cc:1276)
  [operator < matmul > error]  [operator < run_program > error]

大致意思应该是我的数据集的数据格式有问题？我是将list的字符串转成int类型，然后转成numpy再进行预测。

**Comment by qili93** [comment]
您好，根据这个错误提示，是由于您这里转化之后的numpy的数据格式为int64_t

```bash
RuntimeError: (NotFound) Operator (matmul) does not have kernel for data_type[int64_t]:data_layout[ANY_LAYOUT]:place[CPUPlace]:library_type[PLAIN].
```

但是目前Paddle的matmul算子不支持int64_t的数据类似，您可以用以下代码跑一下能看到每个算子具体支持的数据类型，比如matmul的输出是：

```
python -c "import paddle; print(paddle.fluid.core._get_all_register_op_kernels()['matmul'])"


# 输出如下：
data_type[uint8_t]:data_layout[MKLDNNLAYOUT]:place[CPUPlace]:library_type[MKLDNN]
data_type[float]:data_layout[ANY_LAYOUT]:place[CPUPlace]:library_type[PLAIN]
data_type[float]:data_layout[MKLDNNLAYOUT]:place[CPUPlace]:library_type[MKLDNN]
data_type[float]:data_layout[ANY_LAYOUT]:place[NPUPlace(0)]:library_type[PLAIN]
data_type[::paddle::platform::bfloat16]:data_layout[MKLDNNLAYOUT]:place[CPUPlace]:library_type[MKLDNN]
data_type[::paddle::platform::float16]:data_layout[ANY_LAYOUT]:place[NPUPlace(0)]:library_type[PLAIN]
data_type[double]:data_layout[ANY_LAYOUT]:place[CPUPlace]:library_type[PLAIN]
data_type[int8_t]:data_layout[MKLDNNLAYOUT]:place[CPUPlace]:library_type[MKLDNN]
```

建议您这里将numpy转化而来的数据改一下数据类型，比如 np.float32之类的是matmul可以支持的数据类型就可以。

**Comment by Sunyingbin** [comment]
> 您好，根据这个错误提示，是由于您这里转化之后的numpy的数据格式为int64_t
> 
> ```shell
> RuntimeError: (NotFound) Operator (matmul) does not have kernel for data_type[int64_t]:data_layout[ANY_LAYOUT]:place[CPUPlace]:library_type[PLAIN].
> ```
> 
> 但是目前Paddle的matmul算子不支持int64_t的数据类似，您可以用以下代码跑一下能看到每个算子具体支持的数据类型，比如matmul的输出是：
> 
> ```
> python -c "import paddle; print(paddle.fluid.core._get_all_register_op_kernels()['matmul'])"
> 
> 
> # 输出如下：
> data_type[uint8_t]:data_layout[MKLDNNLAYOUT]:place[CPUPlace]:library_type[MKLDNN]
> data_type[float]:data_layout[ANY_LAYOUT]:place[CPUPlace]:library_type[PLAIN]
> data_type[float]:data_layout[MKLDNNLAYOUT]:place[CPUPlace]:library_type[MKLDNN]
> data_type[float]:data_layout[ANY_LAYOUT]:place[NPUPlace(0)]:library_type[PLAIN]
> data_type[::paddle::platform::bfloat16]:data_layout[MKLDNNLAYOUT]:place[CPUPlace]:library_type[MKLDNN]
> data_type[::paddle::platform::float16]:data_layout[ANY_LAYOUT]:place[NPUPlace(0)]:library_type[PLAIN]
> data_type[double]:data_layout[ANY_LAYOUT]:place[CPUPlace]:library_type[PLAIN]
> data_type[int8_t]:data_layout[MKLDNNLAYOUT]:place[CPUPlace]:library_type[MKLDNN]
> ```
> 
> 建议您这里将numpy转化而来的数据改一下数据类型，比如 np.float32之类的是matmul可以支持的数据类型就可以。

好的，收到

**Comment by Sunyingbin** [comment]
> > 您好，根据这个错误提示，是由于您这里转化之后的numpy的数据格式为int64_t
> > ```shell
> > RuntimeError: (NotFound) Operator (matmul) does not have kernel for data_type[int64_t]:data_layout[ANY_LAYOUT]:place[CPUPlace]:library_type[PLAIN].
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 但是目前Paddle的matmul算子不支持int64_t的数据类似，您可以用以下代码跑一下能看到每个算子具体支持的数据类型，比如matmul的输出是：
> > ```
> > python -c "import paddle; print(paddle.fluid.core._get_all_register_op_kernels()['matmul'])"
> > 
> > 
> > # 输出如下：
> > data_type[uint8_t]:data_layout[MKLDNNLAYOUT]:place[CPUPlace]:library_type[MKLDNN]
> > data_type[float]:data_layout[ANY_LAYOUT]:place[CPUPlace]:library_type[PLAIN]
> > data_type[float]:data_layout[MKLDNNLAYOUT]:place[CPUPlace]:library_type[MKLDNN]
> > data_type[float]:data_layout[ANY_LAYOUT]:place[NPUPlace(0)]:library_type[PLAIN]
> > data_type[::paddle::platform::bfloat16]:data_layout[MKLDNNLAYOUT]:place[CPUPlace]:library_type[MKLDNN]
> > data_type[::paddle::platform::float16]:data_layout[ANY_LAYOUT]:place[NPUPlace(0)]:library_type[PLAIN]
> > data_type[double]:data_layout[ANY_LAYOUT]:place[CPUPlace]:library_type[PLAIN]
> > data_type[int8_t]:data_layout[MKLDNNLAYOUT]:place[CPUPlace]:library_type[MKLDNN]
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 建议您这里将numpy转化而来的数据改一下数据类型，比如 np.float32之类的是matmul可以支持的数据类型就可以。
> 
> 好的，收到

float64应该也不支持，我之前转成float64来着
