### ISSUE TITLE
'Tensor' object has no attribute 'to'

### ISSUE THREAD

**Issue by tsijeodhsjsh** [PaddlePaddle/Paddle#36196]
1、执行这一句指令cover = cover.to(device)# 将cover上传到Place时，遇到了这样的问题  “'Tensor' object has no attribute 'to'" 
2、执行N, _, H, W = cover.size()，遇到了 'numpy.int64' object is not callable 这样的错误
- 版本、环境信息：
    1）PaddlePaddle版本：paddlepaddle 2.1.2
    2）CPU：cpu 
    3）系统环境：python 3.7

 代码如下：
#　超参数准备包
import argparse
import time
import paddle
#　数据集准备包
import os
import gzip
import zipfile
from loader import TrainDatasetFromFolder, ValidDatasetFromFolder
from paddle.io import DataLoader
# 网络初始化类
from Critic import critic
from Decode import decode
from Encode import encode
#set device (GPU)
import paddle
# 损失函数准备包
from paddle.vision.models.vgg import vgg16
#from vgg_loss import VGGLoss
from paddle.fluid.layers import cross_entropy,mse_loss
from ssim import _ssim
#from paddle.nn.functional import binary_cross_entropy_with_logits, mse_loss
# 优化算法准备包
from paddle.optimizer import Adam
# 网络训练准备包
from tqdm import tqdm
import gc
import numpy as np
# 画数据图准备包
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
import pandas as pd
from ssim import _ssim_
# detailed 准备包
from PIL import Image
# 压缩准备包
from math import log10
# 结果存储路径包
from datetime import datetime
device=paddle.set_device('cuda:1'if paddle.fluid.is_compiled_with_cuda()else 'cpu')
    print("Using {} device".format(device))

#　训练critic
        for cover in tqdm(train):
            Critic.train()
            Encode.train()
            Decode.train()
            gc.collect()
            #cover = cover.to(device)# 将cover上传到Place
            payload = random_data(cover, args.data_depth, device)
            stego = Encode(cover, payload)
            stego = stego.clamp(-1.0, 1.0)
            # stego = tensors2tensors(stego).to(device)# loss4
            d_loss_ste = AdversaryLoss(stego, Critic).to(device)
            d_loss_cov = AdversaryLoss(cover, Critic).to(device)

            adver_optimizer.zero_grad()#　把模型中参数的梯度设为0
            # 损失函数
            d_loss = (d_loss_cov - d_loss_ste)
            d_loss.backward(retain_graph=False)#　通过反向传播得到每个参数的梯度值
            adver_optimizer.step()#　通过梯度下降执行一步参数更新

            for p in Critic.parameters():
                p.data.clamp_(-0.1, 0.1)

问题1
在执行 cover = cover.to(device)# 将cover上传到Place 时，出现'Tensor' object has no attribute 'to'的错误

代码：
def random_data(cover, data_depth, device):
    N, _, H, W = cover.size()
    payload = paddle.zeros((N, data_depth, H, W), device=device).random_(0, 2)
    return payload
payload = random_data(cover, args.data_depth, device)

问题2 运行时出现了 'numpy.int64' object is not callable 这样的错误

**Comment by qili93** [comment]
@tsijeodhsjsh

1. “cover = cover.to(device)#” 问题

Paddle的使用方式和Torch不同，不需要使用tensor.to(device)的API来选择设备，如果是动态图只需要设置 paddle.set_device("cpu")就可以设置你想要运行的设备了。


2.  'numpy.int64' object is not callable 问题

你这里的cover如果是一个tensor类型，需要通过 paddle.shape(input) 来获取形状，或者通过 cover = cover.numpy() 转化为numpy格式之后再调用size获取形状
