### ISSUE TITLE
单机多卡动转静 SyncBatchNorm op在训练中卡住

### ISSUE THREAD

**Issue by LihangLiu** [PaddlePaddle/Paddle#36202]
利用from paddle.distributed import fleet进行进行单机单卡训练，采取动转静的模式，在加入SyncBatchNorm2D op的时候，就会导致训练卡住，GPU利用100%。用BatchNorm2D op就可以正常训练。

- 版本、环境信息：
    1）PaddlePaddle版本：2.1.3
    2）GPU：P40 cuda10.1 nccl2.7.8
    3）系统环境：centos7
- 训练信息
    1）单机多卡

**Comment by LihangLiu** [comment]
麻烦看一下，感谢~

**Comment by ceci3** [comment]
请问下有可复现代码吗？

**Comment by LihangLiu** [comment]
工程比较复杂，不好抽取，且跟组网方式有关，有些会卡有些不会。
