### ISSUE TITLE
请问有实现 masked_fill 的计划吗？

### ISSUE THREAD

**Issue by yt605155624** [PaddlePaddle/Paddle#36206]
模型中需要用到 masked_fill，目前训练时是用 python 调用 numpy 实现的，但是动转静的时候就不行，导致模型不能部署，请问有实现 masked_fill 的计划吗？

**Comment by JunnYu** [comment]
我之前用paddle.where或者用mask矩阵乘输入都可以实现这个操作

**Comment by yt605155624** [comment]
> 我之前用paddle.where或者用mask矩阵乘输入都可以实现这个操作

你这种实现是可以动转静的嘛？

**Comment by JunnYu** [comment]
个人感觉应该可以的，之前我看过有人用乘法这样做过

**Comment by yinhaofeng** [comment]
https://github.com/PaddlePaddle/Paddle/issues/28238

**Comment by yinhaofeng** [comment]
https://github.com/PaddlePaddle/Paddle/issues/31214
感谢您的建议，我们已经注意到了这个问题，正在评审是否需要新增这个api。

**Comment by S-HuaBomb** [comment]
我使用 `paddle.where` 实现 masked_fill 的一个例子：
```python
p1 = paddle.ones([4, 3, 4, 4]
mask = paddle.tril(paddle.ones([4, 4]))  # 对角线以上的元素全为零
# mask = paddle.tril(paddle.ones([4, 1, 4, 4]))  # 对角线以上的元素全为零
p1_ = paddle.where(mask == 0, paddle.to_tensor(0.), p1)
print(p1_)
```
