### ISSUE TITLE
背景不同，识别结果有差异，如何提高识别模型的鲁棒性？

### ISSUE THREAD

**Issue by Essence9999** [PaddlePaddle/Paddle#36216]
![image](https://user-images.githubusercontent.com/66725845/135226789-3326032f-7db0-4a01-8a5a-cb94409517f5.png)
![image](https://user-images.githubusercontent.com/66725845/135226827-3670a1cc-6842-43bd-9ccd-63036e3ccd8c.png)

**Comment by yinhaofeng** [comment]
您这里展示的是模型训练出来的结果。影响结果的因素可能有很多。比如模型的组网结构，收敛程度等等
在组网中添加一些dropout可能会有帮助

**Comment by MissPenguin** [comment]
如果只是做银行卡这个垂类的识别，最好用充足的银行卡数据进行finetune，见的数据多了，模型自然就鲁棒了。
