### ISSUE TITLE
paddle 切片长度不能为 0 

### ISSUE THREAD

**Issue by yt605155624** [PaddlePaddle/Paddle#36223]
numpy 和 pytorch 切片都可以为 0 ，而 paddle 不可以，希望可以修一下

>>> a = np.array([1,2,3])
>>> b = paddle.to_tensor(a)
>>> b[0:0]
W0929 12:05:22.337487 37759 device_context.cc:447] Please NOTE: device: 0, GPU Compute Capability: 7.0, Driver API Version: 10.2, Runtime API Version: 10.2
W0929 12:05:22.346271 37759 device_context.cc:465] device: 0, cuDNN Version: 7.6.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/yuantian01/.local/lib/python3.7/site-packages/paddle/fluid/dygraph/varbase_patch_methods.py", line 588, in __getitem__
    return self._getitem_index_not_tensor(item)
ValueError: (InvalidArgument) When step > 0, end should be greater than start, but received end = 0, start = 0.
  [Hint: Expected end > start, but received end:0 <= start:0.] (at /paddle/paddle/fluid/operators/slice_utils.h:59)
  [operator < slice > error]

**Comment by yinhaofeng** [comment]
您好，您的反馈对产品非常有价值，我们内部会安排评估，未来有计划修复会尽快回复

**Comment by gavinfaimdata** [comment]
did you get a solution for this?

**Comment by zxcd** [comment]
I tried this in paddlepaddle-gpu=2.3.2 and 2.5.1, both can get the correct answer.  Think this issue already been fixed.
