### ISSUE TITLE
分布式保存模型教程（符号中英文问题）

### ISSUE THREAD

**Issue by 1084667371** [PaddlePaddle/Paddle#36230]
地址：https://www.paddlepaddle.org.cn/tutorials/projectdetail/2350263
问题描述：直接复制还要改，刚在脚本中跑报错了，可以改为英文的
![123](https://user-images.githubusercontent.com/50902619/135380409-af5557b4-75d3-47f9-a39a-d4899a337dff.png)

**Comment by littletomatodonkey** [comment]
好的，感谢反馈，我们修复下~
