### ISSUE TITLE
RuntimeError: (PreconditionNotMet) Cannot load cudnn shared library. Cannot invoke method cudnnGetVersion.

### ISSUE THREAD

**Issue by HuStanding** [PaddlePaddle/Paddle#36238]
Runtime environment:
  -PaddlePaddle version    2.0.2
  -GPU: including CUDA10.0
  -OS Platform Ubuntu 16.04.6 LTS
  -Python version 3.6

The following error occurred when I used the Paddle-GPU version of the prediction：
`RuntimeError: (PreconditionNotMet) Cannot load cudnn shared library. Cannot invoke method cudnnGetVersion.
  [Hint: cudnn_dso_handle should not be null.] (at /paddle/paddle/fluid/platform/dynload/cudnn.cc:76)`

What should I do？

**Comment by littletomatodonkey** [comment]
你好，看着是cudnn so没找到导致的，可以尝试将cudnn lib添加到系统环境变量中试下，此外，paddle官网文档中目前推荐cuda10.1，cuda10.2，cuda11.x，不建议使用cuda10.0了哈
