### ISSUE TITLE
paddle.addmm存在bug

### ISSUE THREAD

**Issue by ElieenAndBella** [PaddlePaddle/Paddle#36251]
out = alpha ∗ x ∗ y + beta ∗ input 此公式错误

应为 2 * alpha * x * y + beta * input

![image](https://user-images.githubusercontent.com/54427695/135601240-b2f71b9a-3476-4d56-818a-794eba89e0ab.png)

**Comment by MissPenguin** [comment]
没有吧，有参考来源吗？

**Comment by ElieenAndBella** [comment]
> 没有吧，有参考来源吗？

看截图呀

**Comment by MissPenguin** [comment]
截图里的结果是对的啊，有什么问题吗。

out = alpha ∗ x ∗ y + beta ∗ input 这个公式在paddle和torch的api文档中定义都是一致的哈，可以自己查阅下：
https://www.paddlepaddle.org.cn/documentation/docs/zh/2.0/api/paddle/tensor/math/addmm_cn.html#cn-api-tensor-addmm
https://pytorch.org/docs/master/generated/torch.addmm.html

**Comment by ElieenAndBella** [comment]
> 截图里的结果是对的啊，有什么问题吗。
> 
> out = alpha ∗ x ∗ y + beta ∗ input 这个公式在paddle和torch的api文档中定义都是一致的哈，可以自己查阅下： https://www.paddlepaddle.org.cn/documentation/docs/zh/2.0/api/paddle/tensor/math/addmm_cn.html#cn-api-tensor-addmm https://pytorch.org/docs/master/generated/torch.addmm.html

哦哦 我傻了。。。对不起对不起
