### ISSUE TITLE
paddle.vision.models.vgg19 (pretrained=True)  报错“vgg19 model do not have a pretrained model now, ...”

### ISSUE THREAD

**Issue by imheng** [PaddlePaddle/Paddle#36259]
调用paddle.vision.models.vgg19 (pretrained=True)  时，系统报错“vgg19 model do not have a pretrained model now, you should set pretrained=False”
    1）PaddlePaddle版本：2.1.2
    2）系统环境：aistudio.baidu.com,GPU环境
 注：您可以通过执行[summary_env.py](https://github.com/PaddlePaddle/Paddle/blob/develop/tools/summary_env.py)获取以上信息。

代码：
model = paddle.vision.models.vgg19 (pretrained=True)

**Comment by LielinJiang** [comment]
已经添加了该预训练权重，会在2.2rc版本发布。
