### ISSUE TITLE
给数据集标准化时，label什么情况下需要做标准化

### ISSUE THREAD

**Issue by Sunyingbin** [PaddlePaddle/Paddle#36276]
我在做预测任务时，对于一些任务当我给label做标准化后，loss会很快收敛，不做标准化loss大的离谱，权重初始化的值太小了？应该如何修改。理论上我觉得不应该给label做标准化啊

**Comment by RainFrost1** [comment]
您好，请问做的什么任务？能否提供一下最小复现代码及环境信息，我们复现后会尽快给您回复

**Comment by Sunyingbin** [comment]
> 您好，请问做的什么任务？能否提供一下最小复现代码及环境信息，我们复现后会尽快给您回复

回归任务，简单的全连接模型，数据时公司搜集的楼宇能源信息，根据AOH、AOT和负荷值预测第二天的负荷值，这样的
paddle2.1
python3.7
windows10
def normalization_zscore(train_x):
    print(train_x)
    print('--------------------------------')
    mean = np.mean(train_x, axis=0)
    std = np.std(train_x, axis=0)
    train_x = (train_x - mean) / std
    # 处理异常情况
    train_x[np.isnan(train_x)] = 0
    train_x[np.isinf(train_x)] = 0
    print(train_x)
    return train_x, mean, std


    # 对输入数据进行标准化处理
    train_x, mean_x, std_x = normalization_zscore(train_x)
    # test_x用train_x的均值和方差
    test_x = (test_x - mean_x) / std_x

    # 是否需要对输出数据做标准化处理？？？？？？不做标准化处理训练不好用？？？
    # 是不是因为当我的label为一个数字的时候我就不需要做标准化了？可以尝试一下.尝试了，结果非常糟糕，loss大的离谱
    # 对输出数据进行标准化处理
    train_y, mean_y, std_y = normalization_zscore(train_y)
    # test_y用train_y的均值和方差
    test_y = (test_y - mean_y) / std_y

**Comment by RainFrost1** [comment]
可以参考[此文档](https://www.zhihu.com/question/37069477/answer/132387124)

**Comment by Sunyingbin** [comment]
> 可以参考[此文档](https://www.zhihu.com/question/37069477/answer/132387124)

我的意思是label是不是不需要做标准化？

**Comment by Sunyingbin** [comment]
> > 可以参考[此文档](https://www.zhihu.com/question/37069477/answer/132387124)
> 
> 或者这么问，如果对于训练集和测试集的输入都做了标准化，输出没有做标准化（输出值数字比较大），导致loss特别大，不收敛，这种情况应该如何处理。

**Comment by RainFrost1** [comment]
label 一般来说是不需要标准化的。你这边的分类输出，是不是之间输出的label？分类的时候，是保证最后一层的输出，label对应的index位置元素最大。
