### ISSUE TITLE
AnalysisConfig 中有些field没有被初始化

### ISSUE THREAD

**Issue by felixhao28** [PaddlePaddle/Paddle#36277]
于是，在调用AnalysisConfig::AnalysisConfig(const std::string &prog_file, const std::string &params_file) 时，AnalysisConfig::Update->AnalysisConfig::SerializeInfoCache 会引用未初始化的变量，从而使得有些分析工具报错。

没有被初始化的field有四个：

```c++
int xpu_l3_workspace_size_; 
bool xpu_locked_; 
bool xpu_autotune_; 
bool xpu_adaptive_seqlen_; 
```

https://github.com/PaddlePaddle/Paddle/blob/10e5304403703b7d42a6aa076c8b4965fb0ca8c3/paddle/fluid/inference/api/paddle_analysis_config.h#L826-L831

**Comment by RainFrost1** [comment]
您好，此问题反映了产品性能需进一步优化，我们会尽快排期，感谢您提出的宝贵意见，谢谢。
