### ISSUE TITLE
如何导入已训练好的模型继续训练？

### ISSUE THREAD

**Issue by Sunyingbin** [PaddlePaddle/Paddle#36275]
我将best_accuracy.pdparams保存下来了，想继续导入这个文件继续调参训练，应该如何做？另外这时候可以修改优化器吗？有没有相关的说明文档。

**Comment by RainFrost1** [comment]
您好，此功能我们已经支持，可[参考链接](https://www.paddlepaddle.org.cn/documentation/docs/zh/guides/02_paddle2.0_develop/08_model_save_load_cn.html)中`2.1.2`参数载入部分。有问题随时提出，谢谢

**Comment by Sunyingbin** [comment]
> 您好，此功能我们已经支持，可[参考链接](https://www.paddlepaddle.org.cn/documentation/docs/zh/guides/02_paddle2.0_develop/08_model_save_load_cn.html)中`2.1.2`参数载入部分。有问题随时提出，谢谢

我已经将loss最小时候的模型和优化器参数保存了，下一次再训练的时候也导入了之前保存的参数，改小了学习率继续训练，但是第一次计算loss还是很大，是为什么，感觉就好像没导入一样，不应该基于之前最小loss开始吗？大致代码如下：

model = MyModel()
# optim = paddle.optimizer.Adagrad(learning_rate=learning_rate, parameters=model.parameters())
optim = paddle.optimizer.Adam(learning_rate=learning_rate, parameters=model.parameters())
# 如果有best_accuracy.pdopt就加载训练好的，不需要重头训练，此时我就不加载优化器了，我想尝试用不同的优化器来训练模型，得到最优
if if_best:
     best_model_state_dict = paddle.load(inference_path + "best_accuracy.pdparams")
     best_optim_state_dict = paddle.load(inference_path + "best_accuracy.pdopt")
     model.set_state_dict(best_model_state_dict)
     optim.set_state_dict(best_optim_state_dict)
model.train()
    for epoch in range(EPOCH_NUM):
        for batch_id, data in enumerate(trainer_loader()):

**Comment by RainFrost1** [comment]
'如果有best_accuracy.pdopt就加载训练好的，不需要重头训练，此时我就不加载优化器了，我想尝试用不同的优化器来训练模型，得到最优'，没太理解具体意思。加载中断训练的模型参数（.pdparams)，其实就是相当于加载了预训练模型。加载优化器参数（.pdopt)，就是从中间继续训练。如果只是加载中断的模型参数，但是新建了一个优化器，相当于完全不同的训练了，此时loss的大小会跟中断之前，确实会出现不一样的情况
