### ISSUE TITLE
傅里叶变换算子

### ISSUE THREAD

**Issue by qdd1234** [PaddlePaddle/Paddle#36270]
您好，目前的paddle是没有提供快速傅里叶变换这个算子是吗

**Comment by nemonameless** [comment]
你好，此功能我们已在develop版本中实现，可参考https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/tensor/fft.py#L154
官网API文档暂时未更新。

**Comment by qdd1234** [comment]
> 你好，此功能我们已在develop版本中实现，可参考https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/tensor/fft.py#L154 官网API文档暂时未更新。

具体会用的话 develop版本如何在正式版本中使用？
