### ISSUE TITLE
请问 FatalError: `Segmentation fault` is detected by the operating system. 是不是 paddle 的报错信息

### ISSUE THREAD

**Issue by yt605155624** [PaddlePaddle/Paddle#36281]
流水线上数据预处理的时候遇到下列问题 
![image](https://user-images.githubusercontent.com/24568452/136523341-6191109f-a1e8-4dff-a28b-2e726df01d43.png)
预处理的时候没有用到 paddle，看起来像是 numpy 的问题，同时数据预处理的时候是用 Python 的 from concurrent.futures import ThreadPoolExecutor，但是在网上搜索 “FatalError: `Segmentation fault` is detected by the operating system.” 字样的时候都是指路到 paddle，想问问这样字样的报错是不是 paddle 独有的。。https://github.com/PaddlePaddle/Paddle/issues/33807 同时在 这个 issue 里面看到重装 numpy 就好了，难道是 paddle numpy 多线程啥的有什么冲突？

**Comment by gongel** [comment]
@yt605155624 你好，麻烦提供一下code和报错完整截图哈

**Comment by yt605155624** [comment]
https://github.com/PaddlePaddle/Parakeet/blob/develop/examples/transformer_tts/ljspeech/preprocess.sh 中调用 https://github.com/PaddlePaddle/Parakeet/blob/develop/examples/transformer_tts/ljspeech/preprocess.py 的时候报错的，但是不是稳定复现，在实验机器上不报错，但是在 QA 的 CE 流水线上有时候会报错 , 完整截图 
![image](https://user-images.githubusercontent.com/24568452/136641189-e4d39f4f-2040-4ff4-8c28-a6a01b9ffdc4.png)

**Comment by chenwhql** [comment]
您好，这个是paddle的报错信息，但从C++栈来看，并不是paddle内部的错误。

这个跟您解释下，import paddle之后，paddle会注册全局的signal handler，捕获系统的signal错误，导致非paddle导致的错误也会被paddle捕获到，比如说在这样一段Python代码中

```
import paddle
import signal
import os

os.kill(os.getpid(), signal.SIGSEGV)
```

这里是我们主动制造了一个段错误，但因为导入了paddle，也会报这个错误，报错如下

```
python signal_handler_test.py                                          

--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
No stack trace in paddle, may be caused by external reasons.

----------------------
Error Message Summary:
----------------------
FatalError: `Segmentation fault` is detected by the operating system.
  [TimeInfo: *** Aborted at 1637725253 (unix time) try "date -d @1637725253" if you are using GNU date ***]
  [SignalInfo: *** SIGSEGV (@0x105e) received by PID 4190 (TID 0x7f583c5ea700) from PID 4190 ***]

[1]    4190 segmentation fault  python signal_handler_test.py
```

这样的机制，主要是为了在paddle自己出现此类错误的时候，能够捕获到一些函数栈用于解决paddle自身的问题，但缺点是，这干扰了其他场景的原生报错反馈，或者在其他组件中，这可能是预期内的行为，也被paddle捕获报错了。

为了解决这个问题，我们在2.2版本提供了disable_signal_handler接口，您可以使用这个接口关闭这一处理机制，从而得到更好的体验，文档见

https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/disable_signal_handler_cn.html#disable-signal-handler

示例如下：

```
import paddle
import signal
import os

paddle.disable_signal_handler()
os.kill(os.getpid(), signal.SIGSEGV)
```

关闭后，上述代码片段的报错如下：

```
python signal_handler_test.py
[1]    4280 segmentation fault  python signal_handler_test.py
```

**Comment by SolitaryManF** [comment]
> 您好，这个是paddle的报错信息，但从C++栈来看，并不是paddle内部的错误。
> 
> 这个跟您解释下，import paddle之后，paddle会注册全局的signal handler，捕获系统的signal错误，导致非paddle导致的错误也会被paddle捕获到，比如说在这样一段Python代码中
> 
> ```
> import paddle
> import signal
> import os
> 
> os.kill(os.getpid(), signal.SIGSEGV)
> ```
> 
> 这里是我们主动制造了一个段错误，但因为导入了paddle，也会报这个错误，报错如下
> 
> ```
> python signal_handler_test.py                                          
> 
> --------------------------------------
> C++ Traceback (most recent call last):
> --------------------------------------
> No stack trace in paddle, may be caused by external reasons.
> 
> ----------------------
> Error Message Summary:
> ----------------------
> FatalError: `Segmentation fault` is detected by the operating system.
>   [TimeInfo: *** Aborted at 1637725253 (unix time) try "date -d @1637725253" if you are using GNU date ***]
>   [SignalInfo: *** SIGSEGV (@0x105e) received by PID 4190 (TID 0x7f583c5ea700) from PID 4190 ***]
> 
> [1]    4190 segmentation fault  python signal_handler_test.py
> ```
> 
> 这样的机制，主要是为了在paddle自己出现此类错误的时候，能够捕获到一些函数栈用于解决paddle自身的问题，但缺点是，这干扰了其他场景的原生报错反馈，或者在其他组件中，这可能是预期内的行为，也被paddle捕获报错了。
> 
> 为了解决这个问题，我们在2.2版本提供了disable_signal_handler接口，您可以使用这个接口关闭这一处理机制，从而得到更好的体验，文档见
> 
> https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/disable_signal_handler_cn.html#disable-signal-handler
> 
> 示例如下：
> 
> ```
> import paddle
> import signal
> import os
> 
> paddle.disable_signal_handler()
> os.kill(os.getpid(), signal.SIGSEGV)
> ```
> 
> 关闭后，上述代码片段的报错如下：
> 
> ```
> python signal_handler_test.py
> [1]    4280 segmentation fault  python signal_handler_test.py
> ```

然后呢？不还是报错吗？
