### ISSUE TITLE
Is there need for log_softmax and shuffle_channel oneDNN kernels?

### ISSUE THREAD

**Issue by jakpiase** [PaddlePaddle/Paddle#36288]
Hi, I am from oneDNN integration team. I was curious if there is a need of implementing log_softmax and shuffle_channel oneDNN ops? If you could give me some model which uses these operators I can implement oneDNN kernel for them

**Comment by lidanqing-vv** [comment]
@baoachun

**Comment by lidanqing-vv** [comment]
Hi @jakpiase , ops priority depends on models priority that Baoachun already sent today. I close this issue now. If the priority models have these ops, we need to do it in Q4. Thanks !
