### ISSUE TITLE
python3.7 adamw  引入的 warning

### ISSUE THREAD

**Issue by yt605155624** [PaddlePaddle/Paddle#36286]
~/.local/lib/python3.7/site-packages/paddle/optimizer/adamw.py:21: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
  from collections import Callable

建议修改 from collections import Callable -> from collections.abc import Callable
之前用 paddle 2.1.2 没遇到过，用 develop 后开始见到这个 warning

**Comment by RainFrost1** [comment]
您好，此问题反映了产品兼容性需进一步优化，我们会尽快排期，感谢您提出的宝贵意见，谢谢。
