### ISSUE TITLE
编译生成exe后运行出现应用程序无法正常运行（0xc0000142）

### ISSUE THREAD

**Issue by zhongweidi993** [PaddlePaddle/Paddle#36293]
编译生成exe后运行出现应用程序无法正常运行（0xc0000142）
![image](https://user-images.githubusercontent.com/84389111/136641192-d059d3c5-899e-4c0b-ac82-e5f54166c56e.png)

**Comment by gongel** [comment]
你好，已看到您在PaddleOCR提过issue了：https://github.com/PaddlePaddle/PaddleOCR/issues/4269
麻烦等待PaddleOCR那边的回复哈。
