### ISSUE TITLE
paddle.fft.rfft的计算结果跟numpy的不一样

### ISSUE THREAD

**Issue by yeyupiaoling** [PaddlePaddle/Paddle#36309]
- PaddlePaddle develop（pip）

使用`paddle.fft.rfft`计算的结果跟numpy的`np.fft.rfft`计算结果输出的shape都不一样的，应该是作用axis不一样，但是改了axis也不起效果。
```python
import numpy as np

x = np.random.random((320, 838))
print(x.shape) # (320, 838)
fft = np.fft.rfft(x, n=None, axis=0)
print(fft.shape) # (161, 838)
```

```python
import paddle
import numpy as np

x = np.random.random((320, 838))
x = paddle.to_tensor(x)
print(x.shape) # [320, 838]
fft = paddle.fft.rfft(x, n=None, axis=0)
print(fft.shape) # [320, 420]
```

**Comment by gongel** [comment]
你好，你方便给一下你的硬件环境吗？

**Comment by gongel** [comment]
你好，已确认是bug，麻烦耐心等待后续的修复，感谢反馈。

**Comment by iclementine** [comment]
在 develop 中已经 fix https://github.com/PaddlePaddle/Paddle/pull/36321

**Comment by yeyupiaoling** [comment]
@iclementine 好的，那么是不是今晚更新pip（develop）的安装，听过这个是每晚更新的
![image](https://user-images.githubusercontent.com/26297768/136743584-97b86d58-60a0-49b3-a17c-9756e9bbcc69.png)

**Comment by iclementine** [comment]
一般情况下是的。不过安装之后也可以看看 commit 信息以确保更新了。

`paddle.__git_commit__` 即可查看。

**Comment by yeyupiaoling** [comment]
好的，谢谢
