### ISSUE TITLE
在安装lac 时，报错

### ISSUE THREAD

**Issue by songsh** [PaddlePaddle/Paddle#36307]
windows 2008,
安装lac,报错
 File "C:\python\lib\site-packages\LAC\__init__.py", line 23, in <module>
    from .lac import LAC
  File "C:\python\lib\site-packages\LAC\lac.py", line 28, in <module>
    import paddle.fluid as fluid
  File "C:\python\lib\site-packages\paddle\__init__.py", line 39, in <module>
    from . import incubate
  File "C:\python\lib\site-packages\paddle\incubate\__init__.py", line 15, in <module>
    from . import hapi
  File "C:\python\lib\site-packages\paddle\incubate\hapi\__init__.py", line 16, in <module>
    from . import vision
  File "C:\python\lib\site-packages\paddle\incubate\hapi\vision\__init__.py", line 15, in <module>
    from . import transforms
  File "C:\python\lib\site-packages\paddle\incubate\hapi\vision\transforms\__init__.py", line 15, in <module>
    from . import transforms
  File "C:\python\lib\site-packages\paddle\incubate\hapi\vision\transforms\transforms.py", line 18, in <module>
    import cv2
  File "C:\python\lib\site-packages\cv2\__init__.py", line 3, in <module>
    from .cv2 import *
ImportError: DLL load failed: 找不到指定的模块。

cv2 找不到，请问是什么原因 ？

**Comment by gongel** [comment]
你好，可尝试更换`opencv-python`的版本、下载更换动态库，同时升级到`PaddlePaddle`的最新版本。

**Comment by songsh** [comment]
更新了还报错：
Error: Your machine doesn't support AVX, but the installed PaddlePaddle is avx core, you should reinstall paddlepaddle with no-avx core.

**Comment by songsh** [comment]
我在centos 7.6 中安装，也报错：
Error: Can not import avx core while this file exists: /usr/local/python3/lib/python3.7/site-packages/paddle/fluid/core_avx.so

**Comment by gongel** [comment]
你好，你的机器不支持avx，需要安装noavx的版本哈：https://www.paddlepaddle.org.cn/documentation/docs/zh/install/pip/linux-pip.html
![image](https://user-images.githubusercontent.com/24390500/136775346-1c791d96-6961-403a-9244-f808cf3e1472.png)

**Comment by songsh** [comment]
请问，mkl,  openblas, 要如何选 ？

**Comment by gongel** [comment]
都可以安装的。

**Comment by songsh** [comment]
我在centos 7.6 中安装，也报错：
Error: Can not import avx core while this file exists: /usr/local/python3/lib/python3.7/site-packages/paddle/fluid/core_avx.so,  
ImportError: /lib64/libstdc++.so.6: version `CXXABI_1.3.8' not found (required by /usr/local/python3.8/lib/python3.8/site-packages/paddle/fluid/core_avx.so)
这问题，好象没回答，
有avx , 没有avx 两个版本，我都装了，都这个bug .

**Comment by songsh** [comment]
在window 2008 下，安装noavx,  报没合适版本 
python -m pip download paddlepaddle==2.1.3 -f https://www.paddlepaddle.org.cn/whl/windows/mkl/noavx/stable.html --no-index --no-deps

<img width="641" alt="屏幕快照 2021-10-12 下午3 40 39" src="https://user-images.githubusercontent.com/2272252/136913082-78db8dd5-77d6-4718-9de1-a5bebea02e1f.png">

**Comment by gongel** [comment]
> 我在centos 7.6 中安装，也报错： Error: Can not import avx core while this file exists: /usr/local/python3/lib/python3.7/site-packages/paddle/fluid/core_avx.so, ImportError: /lib64/libstdc++.so.6: version `CXXABI_1.3.8' not found (required by /usr/local/python3.8/lib/python3.8/site-packages/paddle/fluid/core_avx.so) 这问题，好象没回答， 有avx , 没有avx 两个版本，我都装了，都这个bug .

可能是gcc的问题，参考#4969 和#34504

**Comment by gongel** [comment]
> 在window 2008 下，安装noavx, 报没合适版本 python -m pip download paddlepaddle==2.1.3 -f https://www.paddlepaddle.org.cn/whl/windows/mkl/noavx/stable.html --no-index --no-deps
> 
> <img alt="屏幕快照 2021-10-12 下午3 40 39" width="641" src="https://user-images.githubusercontent.com/2272252/136913082-78db8dd5-77d6-4718-9de1-a5bebea02e1f.png">

windows参考这个哈：https://www.paddlepaddle.org.cn/documentation/docs/zh/install/pip/windows-pip.html

**Comment by songsh** [comment]
> > 在window 2008 下，安装noavx, 报没合适版本 python -m pip download paddlepaddle==2.1.3 -f https://www.paddlepaddle.org.cn/whl/windows/mkl/noavx/stable.html --no-index --no-deps
> > <img alt="屏幕快照 2021-10-12 下午3 40 39" width="641" src="https://user-images.githubusercontent.com/2272252/136913082-78db8dd5-77d6-4718-9de1-a5bebea02e1f.png">
> 
> windows参考这个哈：https://www.paddlepaddle.org.cn/documentation/docs/zh/install/pip/windows-pip.html

你好，我就是按文档来的，没合适版本，是在window 2008 下无法安装吗？
