### ISSUE TITLE
编译裁剪

### ISSUE THREAD

**Issue by songyuwen0808** [PaddlePaddle/Paddle#36306]
现在编译产出一次gpu版本的paddle的whl包大概需要30 ~ 40分钟左右
但是其实大量的op并没有用到，所以想问下如何对编译进行裁剪呢，想将不需要的op不进行编译，加快编译速度

**Comment by gongel** [comment]
你好，经反馈，暂时是不支持的。

**Comment by gongel** [comment]
你好，可以通过修改一下文件来移除不需要的OP：https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/fluid/operators/CMakeLists.txt 和 https://github.com/PaddlePaddle/Paddle/blob/develop/cmake/operators.cmake
