### ISSUE TITLE
docker编译安装make test无法通过

### ISSUE THREAD

**Issue by thunder95** [PaddlePaddle/Paddle#36319]
按照最新教程在docker环境下编译安装：  https://www.paddlepaddle.org.cn/install/quick?docurl=/documentation/docs/zh/install/compile/linux-compile.html#anchor-0

1. 出现问题， 翻阅了其他issue， 也没有解决，编译过程没有发现报错
fatal: no tag exactly matches 'f9591bb172e7274a77bfdcb6493579824aec8b47'
package init file '/paddle/build/python/paddle/libs/__init__.py' not found (or not a regular file)

2. make test时，部分算子始终不通过，例如test_unfold_op.py, 若单独运行又会有这样的错误：
======================================================================
ERROR: test_check_output (__main__.TestUnfoldOp)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_unfold_op.py", line 98, in test_check_output
    self.check_output()
  File "/paddle/build/python/paddle/fluid/tests/unittests/op_test.py", line 1357, in check_output
    inplace_atol)
  File "/paddle/build/python/paddle/fluid/tests/unittests/op_test.py", line 1110, in check_output_with_place
    outs, fetch_list = self._calc_output(place, no_check_set=no_check_set)
  File "/paddle/build/python/paddle/fluid/tests/unittests/op_test.py", line 680, in _calc_output
    op = self._append_ops(block)
  File "/paddle/build/python/paddle/fluid/tests/unittests/op_test.py", line 472, in _append_ops
    attrs=self.attrs if hasattr(self, "attrs") else dict())
  File "/paddle/build/python/paddle/fluid/framework.py", line 3163, in append_op
    kwargs.get("stop_gradient", False))
  File "/paddle/build/python/paddle/fluid/dygraph/tracer.py", line 45, in trace_op
    not stop_gradient)
ValueError: (InvalidArgument) The Tensor in the unfold Op's Input Variable X(X) is not initialized.
  [Hint: Expected t->IsInitialized() == true, but received t->IsInitialized():0 != true:1.] (at /paddle/paddle/fluid/framework/operator.cc:1590)
  [operator < unfold > error]

3. 如果只是针对某一项进行make test测试，有没有其他更高效方便的方式？make test毕竟有些慢

**Comment by minghaoBD** [comment]
谢谢您提出的问题。
请问您用到的docker镜像和编译的paddle版本是什么？我这边先复现一下。

另外，针对问题3，可以用这个命令只test某一个op：make test ARGS="-R test_unfold_op -V"

**Comment by thunder95** [comment]
> 谢谢您提出的问题。 请问您用到的docker镜像和编译的paddle版本是什么？我这边先复现一下。
> 
> 另外，针对问题3，可以用这个命令只test某一个op：make test ARGS="-R test_unfold_op -V"

@minghaoBD 感谢这么快回复。希望尝试下hackson上的任务fold， 我完全按照官方教程，只是分支不一样， 我从develop分支新建的一个分支my_test。

命令如下：
nvidia-docker run --name paddle-test -v $PWD:/paddle --network=host -it registry.baidubce.com/paddlepaddle/paddle:latest-gpu-cuda10.2-cudnn7-dev /bin/bash

cmake .. -DPY_VERSION=3.7 -DWITH_GPU=ON -DWITH_TESTING=ON -DCMAKE_BUILD_TYPE=Release

**Comment by thunder95** [comment]
@minghaoBD 按照您给的方式 只测试那一项是可以测试通过的， 暂不清楚为什么之前无法通过。单独运行python脚本，还是不行。

1/1 Test #247: test_unfold_op ...................   Passed    7.74 sec

The following tests passed:
	test_unfold_op

**Comment by minghaoBD** [comment]
> @minghaoBD 按照您给的方式 只测试那一项是可以测试通过的， 暂不清楚为什么之前无法通过。单独运行python脚本，还是不行。
> 
> 1/1 Test #247: test_unfold_op ................... Passed 7.74 sec
> 
> The following tests passed: test_unfold_op

现在支持make test的命令，python不行哈。
具体可以查看这个教程介绍，里面详细介绍了原生算子的开发和单测流程。https://www.paddlepaddle.org.cn/documentation/docs/zh/guides/07_new_op/new_op_cn.html

**Comment by thunder95** [comment]
@minghaoBD 老师， 我把fold的op写了， 用pip安装测试前向没有问题，跟torch输出一致。但是用命令测试，始终都报段错误，检查了很久也不知道什么原因，根据排查是在完成前向之后反向之前出现的。希望能给一些提示，应该怎么去debug。

580: --------------------------------------
580: C++ Traceback (most recent call last):
580: --------------------------------------
580: 0   paddle::framework::Executor::Run(paddle::framework::ProgramDesc const&, paddle::framework::Scope*, int, bool, bool, std::vector<std::string, std::allocator<std::string > > const&, bool, bool)
580: 1   paddle::framework::Executor::RunPreparedContext(paddle::framework::ExecutorPrepareContext*, paddle::framework::Scope*, bool, bool, bool)
580: 2   paddle::framework::Executor::RunPartialPreparedContext(paddle::framework::ExecutorPrepareContext*, paddle::framework::Scope*, long, long, bool, bool, bool)
580: 3   paddle::framework::OperatorBase::Run(paddle::framework::Scope const&, paddle::platform::Place const&)
580: 4   paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, paddle::platform::Place const&) const
580: 5   paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, paddle::platform::Place const&, paddle::framework::RuntimeContext*) const
580: 6   paddle::framework::Tensor::mutable_data(paddle::platform::Place const&, paddle::framework::proto::VarType_Type, unsigned long)
580: 
580: ----------------------
580: Error Message Summary:
580: ----------------------
580: FatalError: `Segmentation fault` is detected by the operating system.
580:   [TimeInfo: *** Aborted at 1633875349 (unix time) try "date -d @1633875349" if you are using GNU date ***]
580:   [SignalInfo: *** SIGSEGV (@0x18) received by PID 17830 (TID 0x7f5f7beb0700) from PID 24 ***]
580: 
580: Segmentation fault

**Comment by thunder95** [comment]
@minghaoBD 执行这一步报段错误 (*kernel_func_)(
        ExecutionContext(*this, exec_scope, *dev_ctx, *runtime_ctx));， 但是并么有进入到compute函数里面去

**Comment by minghaoBD** [comment]
> @minghaoBD 执行这一步报段错误 (*kernel_func_)( ExecutionContext(*this, exec_scope, *dev_ctx, *runtime_ctx));， 但是并么有进入到compute函数里面去

明白。seg-fault很可能是访问内存相关的错误。可以结合断点+参照其他op代码，具体看下是否有代码细节错误，指针引用、数据访问、存储之类的。

**Comment by minghaoBD** [comment]
> 按照最新教程在docker环境下编译安装： https://www.paddlepaddle.org.cn/install/quick?docurl=/documentation/docs/zh/install/compile/linux-compile.html#anchor-0
> 
> 1. 出现问题， 翻阅了其他issue， 也没有解决，编译过程没有发现报错
>    fatal: no tag exactly matches 'f9591bb172e7274a77bfdcb6493579824aec8b47'
>    package init file '/paddle/build/python/paddle/libs/**init**.py' not found (or not a regular file)
> 2. make test时，部分算子始终不通过，例如test_unfold_op.py, 若单独运行又会有这样的错误：
>    ======================================================================
>    ERROR: test_check_output (**main**.TestUnfoldOp)
> 
> Traceback (most recent call last): File "test_unfold_op.py", line 98, in test_check_output self.check_output() File "/paddle/build/python/paddle/fluid/tests/unittests/op_test.py", line 1357, in check_output inplace_atol) File "/paddle/build/python/paddle/fluid/tests/unittests/op_test.py", line 1110, in check_output_with_place outs, fetch_list = self._calc_output(place, no_check_set=no_check_set) File "/paddle/build/python/paddle/fluid/tests/unittests/op_test.py", line 680, in _calc_output op = self._append_ops(block) File "/paddle/build/python/paddle/fluid/tests/unittests/op_test.py", line 472, in _append_ops attrs=self.attrs if hasattr(self, "attrs") else dict()) File "/paddle/build/python/paddle/fluid/framework.py", line 3163, in append_op kwargs.get("stop_gradient", False)) File "/paddle/build/python/paddle/fluid/dygraph/tracer.py", line 45, in trace_op not stop_gradient) ValueError: (InvalidArgument) The Tensor in the unfold Op's Input Variable X(X) is not initialized. [Hint: Expected t->IsInitialized() == true, but received t->IsInitialized():0 != true:1.] (at /paddle/paddle/fluid/framework/operator.cc:1590) [operator < unfold > error]
> 
> 1. 如果只是针对某一项进行make test测试，有没有其他更高效方便的方式？make test毕竟有些慢

这里也遇到了和1一样的问题，https://github.com/PaddlePaddle/Paddle/issues/19717 ，可以参照。

**Comment by thunder95** [comment]
> > 按照最新教程在docker环境下编译安装： https://www.paddlepaddle.org.cn/install/quick?docurl=/documentation/docs/zh/install/compile/linux-compile.html#anchor-0
> > 
> > 1. 出现问题， 翻阅了其他issue， 也没有解决，编译过程没有发现报错
> >    fatal: no tag exactly matches 'f9591bb172e7274a77bfdcb6493579824aec8b47'
> >    package init file '/paddle/build/python/paddle/libs/**init**.py' not found (or not a regular file)
> > 2. # make test时，部分算子始终不通过，例如test_unfold_op.py, 若单独运行又会有这样的错误：
> >    ERROR: test_check_output (**main**.TestUnfoldOp)
> > 
> > Traceback (most recent call last): File "test_unfold_op.py", line 98, in test_check_output self.check_output() File "/paddle/build/python/paddle/fluid/tests/unittests/op_test.py", line 1357, in check_output inplace_atol) File "/paddle/build/python/paddle/fluid/tests/unittests/op_test.py", line 1110, in check_output_with_place outs, fetch_list = self._calc_output(place, no_check_set=no_check_set) File "/paddle/build/python/paddle/fluid/tests/unittests/op_test.py", line 680, in _calc_output op = self._append_ops(block) File "/paddle/build/python/paddle/fluid/tests/unittests/op_test.py", line 472, in _append_ops attrs=self.attrs if hasattr(self, "attrs") else dict()) File "/paddle/build/python/paddle/fluid/framework.py", line 3163, in append_op kwargs.get("stop_gradient", False)) File "/paddle/build/python/paddle/fluid/dygraph/tracer.py", line 45, in trace_op not stop_gradient) ValueError: (InvalidArgument) The Tensor in the unfold Op's Input Variable X(X) is not initialized. [Hint: Expected t->IsInitialized() == true, but received t->IsInitialized():0 != true:1.] (at /paddle/paddle/fluid/framework/operator.cc:1590) [operator < unfold > error]
> > 
> > 1. 如果只是针对某一项进行make test测试，有没有其他更高效方便的方式？make test毕竟有些慢
> 
> 这里也遇到了和1一样的问题，#19717 ，可以参照。

@minghaoBD 编译了多次 也没解决，参考其他类似issue也不行，貌似不影响程序运行，暂且没关注这个问题了。

**Comment by minghaoBD** [comment]
> 按照最新教程在docker环境下编译安装： https://www.paddlepaddle.org.cn/install/quick?docurl=/documentation/docs/zh/install/compile/linux-compile.html#anchor-0
> 
> 1. 出现问题， 翻阅了其他issue， 也没有解决，编译过程没有发现报错
>    fatal: no tag exactly matches 'f9591bb172e7274a77bfdcb6493579824aec8b47'
>    package init file '/paddle/build/python/paddle/libs/**init**.py' not found (or not a regular file)
> 2. make test时，部分算子始终不通过，例如test_unfold_op.py, 若单独运行又会有这样的错误：
>    ======================================================================
>    ERROR: test_check_output (**main**.TestUnfoldOp)
> 
> Traceback (most recent call last): File "test_unfold_op.py", line 98, in test_check_output self.check_output() File "/paddle/build/python/paddle/fluid/tests/unittests/op_test.py", line 1357, in check_output inplace_atol) File "/paddle/build/python/paddle/fluid/tests/unittests/op_test.py", line 1110, in check_output_with_place outs, fetch_list = self._calc_output(place, no_check_set=no_check_set) File "/paddle/build/python/paddle/fluid/tests/unittests/op_test.py", line 680, in _calc_output op = self._append_ops(block) File "/paddle/build/python/paddle/fluid/tests/unittests/op_test.py", line 472, in _append_ops attrs=self.attrs if hasattr(self, "attrs") else dict()) File "/paddle/build/python/paddle/fluid/framework.py", line 3163, in append_op kwargs.get("stop_gradient", False)) File "/paddle/build/python/paddle/fluid/dygraph/tracer.py", line 45, in trace_op not stop_gradient) ValueError: (InvalidArgument) The Tensor in the unfold Op's Input Variable X(X) is not initialized. [Hint: Expected t->IsInitialized() == true, but received t->IsInitialized():0 != true:1.] (at /paddle/paddle/fluid/framework/operator.cc:1590) [operator < unfold > error]
> 
> 1. 如果只是针对某一项进行make test测试，有没有其他更高效方便的方式？make test毕竟有些慢

关于问题2，我这边测试了下。直接make test确实有一部分会fail，原因主要是需要手动安装python依赖，例如：
1. test_callback_visualdl requires visualdl
2. test_erf_op requires scipy,
3. etc.

此外，如果要make test所有的单测，也请确保有足够的硬盘空间，且paddle-GPU安装好（有些单测要求 GPU）、等等个性原因。但其实，对于op开发，我们无需运行所有单测，指定测试您开发的那一个即可。希望对您有帮助。

**Comment by thunder95** [comment]
> > @minghaoBD 执行这一步报段错误 (*kernel_func_)( ExecutionContext(*this, exec_scope, *dev_ctx, *runtime_ctx));， 但是并么有进入到compute函数里面去
> 
> 明白。seg-fault很可能是访问内存相关的错误。可以结合断点+参照其他op代码，具体看下是否有代码细节错误，指针引用、数据访问、存储之类的。

@minghaoBD 麻烦老师讲一下，怎么debug和断点这种make test命令。 您一般是有用什么IDE么比如clion调试paddle源码么？或者这种make test也能用gdb调试么， 以前没调试过这种程序，clion加载CMakelist.txt会出现一大堆子模块。

**Comment by minghaoBD** [comment]
> > > @minghaoBD 执行这一步报段错误 (*kernel_func_)( ExecutionContext(*this, exec_scope, *dev_ctx, *runtime_ctx));， 但是并么有进入到compute函数里面去
> > 
> > 
> > 明白。seg-fault很可能是访问内存相关的错误。可以结合断点+参照其他op代码，具体看下是否有代码细节错误，指针引用、数据访问、存储之类的。
> 
> @minghaoBD 麻烦老师讲一下，怎么debug和断点这种make test命令。 您一般是有用什么IDE么比如clion调试paddle源码么？或者这种make test也能用gdb调试么， 以前没调试过这种程序，clion加载CMakelist.txt会出现一大堆子模块。

gdb也可以用，但不是很友好。还是建议打log直接看，更方便些。

**Comment by thunder95** [comment]
@minghaoBD 我直接用单独的脚本运行前向， cuda和cpu都能通过allclose， 但是用make test， 只有cuda能过， cpu不能过， 打印出来如下，发现cpu输出的数据虽然正确但是格式不对，请老师看下这是咋回事呢：

**cpu输出:**
```
 [[[[-8.76469553e-001  1.93706059e+000 -2.71777153e-001 -9.21560168e-001
580:      1.31471956e+000]
580:    [-2.87840270e+000  8.62048758e-001  3.58338845e+246  2.43826297e+000
580:     -1.25642425e+000]
580:    [-3.22030451e-001  1.01622640e+000  5.87132752e-001 -3.45322796e-001
580:     -6.80654895e-001]
580:    [-9.21838701e-001  3.09267581e-001  1.12520057e+000  6.45647894e-001
580:      6.32072210e-001]]
```

**cuda输出:**
```
 [[[[-0.87646955  1.93706059 -0.27177715 -0.92156017  1.31471956]
580:    [-2.8784027   0.86204876  0.01109229  2.43826297 -1.25642425]
580:    [-0.32203045  1.0162264   0.58713275 -0.3453228  -0.68065489]
580:    [-0.9218387   0.30926758  1.12520057  0.64564789  0.63207221]]
```
**torch的输出:**

```
 [[[[-0.87646955  1.93706059 -0.27177715 -0.92156017  1.31471956]
580:    [-2.8784027   0.86204876  0.01109229  2.43826297 -1.25642425]
580:    [-0.32203045  1.0162264   0.58713275 -0.3453228  -0.68065489]
580:    [-0.9218387   0.30926758  1.12520057  0.64564789  0.63207221]]
```

**Comment by minghaoBD** [comment]
@thunder95 感觉您的问题比较细节，而且我这边之前也没有遇到过。
方便提一个pull request吗？我这边跟进看下代码

**Comment by thunder95** [comment]
@minghaoBD make test命令后，仔细看cpu的输出确实不太一样，有的值非常夸张。问题只出在cpuplace时候， 

`580: AssertionError: 1.8207115622550432e+101 not less than or equal to 1e-07 : Operator fold error, Gradient Check On CPUPlace variable X (shape: (2, 12, 12), dtype: float64) max gradient diff 1.820712e+101 over limit 1.000000e-07, the first error element is 0, expected 0.000000e+00, but got 8.333333e-03.
`

已经提交[PR链接](https://github.com/PaddlePaddle/Paddle/pull/36416)

**Comment by thunder95** [comment]
@minghaoBD 请问老师有检查到哪里出问题了么， 这个挺奇怪的，矩阵里面忽然就数值变得很怪异 甚至达到e207， 始终不明白为啥会这样

**Comment by minghaoBD** [comment]
> @minghaoBD 请问老师有检查到哪里出问题了么， 这个挺奇怪的，矩阵里面忽然就数值变得很怪异 甚至达到e207， 始终不明白为啥会这样

抱歉，这两天比较忙，没来及的尝试。如果着急的话，可以先按照comment里面的描述，打印中间变量看看，narrow down一下问题。
