### ISSUE TITLE
帮忙解决一下报错

### ISSUE THREAD

**Issue by qdd1234** [PaddlePaddle/Paddle#36318]
您好，下图中报错如何解决？
![image](https://user-images.githubusercontent.com/68497831/136665052-f1024de0-2ca7-499a-8e73-9704d3231b15.png)
![image](https://user-images.githubusercontent.com/68497831/136665062-31f3d93e-7ad5-4a45-8cde-22c547d41b71.png)

**Comment by gongel** [comment]
你好，能给个简单的输入吗？我来进行复现和排查。
