### ISSUE TITLE
Fold

### ISSUE THREAD

**Issue by qdd1234** [PaddlePaddle/Paddle#36316]
您好，paddle中有没有类似nn.Fold和torch.view_as_complex这个两个API？

**Comment by gongel** [comment]
你好，暂时是没有的，我这边进行反馈，内部会安排评估，未来有计划尽快回复。

**Comment by Ligoml** [comment]
你好，paddle目前在develop版本中已具备 `paddle.nn.Fold` 和 `paddle.as_complex` 对应，预计会在下个版本中发布，敬请期待~
