### ISSUE TITLE
AssertionError: the type of architecture(None) should be dict报错

### ISSUE THREAD

**Issue by leezhao415** [PaddlePaddle/Paddle#36324]
问题出现过程描述：
https://aistudio.baidu.com/aistudio/projectdetail/2300718?channelType=0&channel=0
该项目按步骤执行到模型训练过程出现该问题
python tools/train.py -c ./ppcls/configs/quick_start/ResNet50_vd.yaml -o Arch.pretrained=True

系统环境：
****************************************
Paddle version: 2.1.3
Paddle With CUDA: True

OS: ubuntu 18.04
Python version: 3.6.13

CUDA version: 11.0.194
Build cuda_11.0_bu.TC445_37.28540450_0
cuDNN version: None.None.None
Nvidia driver version: 470.42.01
****************************************

报错信息：
Traceback (most recent call last):
  File "tools/train.py", line 118, in <module>
    main(args)
  File "tools/train.py", line 56, in main
    config = get_config(args.config, overrides=args.override, show=True)
  File "/home/shanshan/PaddleClas/ppcls/utils/config.py", line 196, in get_config
    check_config(config)
  File "/home/shanshan/PaddleClas/ppcls/utils/config.py", line 106, in check_config
    check.check_architecture(architecture)
  File "/home/shanshan/PaddleClas/ppcls/utils/check.py", line 65, in check_architecture
    ("the type of architecture({}) should be dict". format(architecture))
AssertionError: the type of architecture(None) should be dict

**Comment by lyuwenyu** [comment]
看报错信息是报在了paddle cls库里 

paddle cls repo的问题建议在提问 https://github.com/PaddlePaddle/PaddleClas/issues

**Comment by XieYunshen** [comment]
这里的路径有问题
![image](https://user-images.githubusercontent.com/32428676/136935250-39b9670c-2be6-4a71-8922-4bcbefdf5195.png)
改成下面的路径试试吧
![image](https://user-images.githubusercontent.com/32428676/136934995-e1ec7e02-174c-412c-9ad9-65ea4b979259.png)
