### ISSUE TITLE
 试图安装paddlepaddle的gpu版，出了问题。

### ISSUE THREAD

**Issue by FleetCommander004** [PaddlePaddle/Paddle#36323]
我最近在试图安装gpu版的paddle paddle。我安装的是最新的2.1.3版。我已经把cuda11.2和cuDNN8.1.1.33都下载下来了。
但是当我试图 import paddle的时候，系统确报出了如下错误：
C:\Users\karlf\Anaconda3\envs\paddle_env\lib\site-packages\paddle\fluid\framework.py:300: UserWarning: You are using GPU version Paddle, but your CUDA device is not set properly. CPU device will be used by default.
  warnings.warn(

所以我的环境设置出了哪些问题呢？
我运行conda install paddlepaddle-gpu的时候系统都跟我说# All requested packages already installed.
我的cudnn路径：
C:\Users\karlf\Downloads\cudnn-11.2-windows-x64-v8.1.1.33
我的cuda 11.2路径：
C:\ProgramData\NVIDIA Corporation\CUDA Samples\v11.2

**Comment by lyuwenyu** [comment]
确保你这边cuda安装并配置正确

可以在终端`ncnn -V `可以check一下

**Comment by FleetCommander004** [comment]
> 确保你这边cuda安装并配置正确
> 
> 可以在终端`ncnn -V `可以check一下

您好，我试了一下。话说ncnn -V的命令是在terminal里面打开吗？我在terminal里面打出这个命令，说‘ncnn' 不是内部或外部命令，也不是可运行的程序或批处理文件。

**Comment by lyuwenyu** [comment]
是的 也就是你cuda没配置对  建议按照教程再检查一下环境变量设置对没

**Comment by FleetCommander004** [comment]
最近我试图在阿里云gpu处理器上面安装paddlepaddle 的gpu版，结果还是说：
WARNING:root:You are using GPU version PaddlePaddle, but there is no GPU detected on your machine. Maybe CUDA devices is not set properly.
但是我已经配置好cuda相关的内容了。
我的机器上面是怎么写的：
[root@iZbp1iuo7tqytcq2z582p2Z ~]# ls
 2021实习资料  '=3.8'   auto_install   paddle_env
[root@iZbp1iuo7tqytcq2z582p2Z ~]# cd auto_install
[root@iZbp1iuo7tqytcq2z582p2Z auto_install]# ls
auto_install.log  cudnn-11.2-linux-x64-v8.1.1.tgz
auto_install.sh   ### **NVIDIA-Linux-x86_64-460.91.03.run**
### **cuda**              tmp
[root@iZbp1iuo7tqytcq2z582p2Z auto_install]# cd cuda
[root@iZbp1iuo7tqytcq2z582p2Z cuda]# ls
**### cuda_11.2.2_460.32.03_linux.run**
[root@iZbp1iuo7tqytcq2z582p2Z cuda]# 
但是系统还是说我没有配置好粗大，所以我需要怎么做呢？

**Comment by FleetCommander004** [comment]
> 是的 也就是你cuda没配置对 建议按照教程再检查一下环境变量设置对没

谢谢朋友，我最近安装好gpu版本的paddlepaddle了。
