### ISSUE TITLE
add with_refactoring cmake option

### ISSUE THREAD

**Issue by QiJune** [PaddlePaddle/Paddle#3633]
Now, paddle is under refactoring. And since refactoring codes have not meet large scale test, and may be unstable in some circumstance. It's better to add a with_refactoring cmake option to isolate the refactoring code compiling.

**Comment by wangkuiyi** [comment]
I don't quite get it -- as long as Paddle executable doesn't call new code generated by the Refactorization project, it should run well.  This doesn't seem a reason to add this option that prevents new code from getting built.

A rational reason to add this option is that some dependencies of our new code, e.g., Eigen, doesn't build with old toolchains. It seems that we need an additional Dockerfile of old toolchains, and this option?

**Comment by QiJune** [comment]
@wangkuiyi Got it! Docker is a really good tool to unify building environment, and we can hardly solve all different local building problems. 
I close this issue now.
