### ISSUE TITLE
paddle中ssim中有关create window的问题

### ISSUE THREAD

**Issue by tsijeodhsjsh** [PaddlePaddle/Paddle#36346]
def create_window(window_size, channel):
    _1D_window = gaussian(window_size, 1.5).unsqueeze(1)
    _2D_window = _1D_window.mm(_1D_window.t()).float().unsqueeze(0).unsqueeze(0)
    window = _2D_window.expand(channel, 1, window_size, window_size).contiguous()
return window

def _ssim_(img1, img2, window_size=11, size_average=True):
    #img1=img1.numpy()
    #(_, channel, _, _) = img1_size()
    channel=img1.shape[2]
    window = create_window(window_size, channel)

    if img1.is_cuda:
        window = window.cuda(img1.get_device())
    window = window.type_as(img1)

    return _ssim(img1, img2, window, window_size, channel, size_average)

问题1
在跑 _2D_window = _1D_window.mm(_1D_window.t()).float().unsqueeze(0).unsqueeze(0) 这一句代码时，出现了如下错误: 'Tensor' object has no attribute 'float'
问题2
 在跑 window = _2D_window.expand(channel, 1, window_size, window_size).contiguous() 这一句代码时，出现了如下错误 TypeError: expand() takes from 2 to 3 positional arguments but 5 were given

**Comment by lyuwenyu** [comment]
1.  `.float()` 改成  `.astype('float32')`
2. `expand` 参数出入的方式不对  参考 [expand](https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/expand_cn.html#cn-api-tensor-expand)
