### ISSUE TITLE
使用cache=CacheType.CACHE_PASS_IN_MEM优化过程中报错

### ISSUE THREAD

**Issue by xlhlhlx** [PaddlePaddle/Paddle#3635]
## 背景
预提交到mpi集群的paddle任务（预测用户对视频内容的阅读时长），本地单机调试的过程中，发现500条sample，batch_size=256，20个pass，每个pass要跑70秒左右，后续全量数据训练样本数量级大概在亿级别，因此先本地进行训练速度上的优化。
![5](https://user-images.githubusercontent.com/28750940/29609027-79d6456c-8828-11e7-936f-a3a2883296ce.png)
## 当前问题
使用cache=CacheType.CACHE_PASS_IN_MEM进行效率优化，增加了@provider(cache=CacheType.CACHE_PASS_IN_MEM) 这么一句后报错，具体报错信息如下：
![6](https://user-images.githubusercontent.com/28750940/29609118-c813b34a-8828-11e7-9e25-76bf560f0255.png)
## 相关代码如下：
![7](https://user-images.githubusercontent.com/28750940/29609177-ef808246-8828-11e7-94fc-8931071db2ed.png)
因为我这个任务后面是要提交mpi集群上跑的，所以会有一个node_id，难道这个参数在mpi集群上不能用的？求教如何修改？

**Comment by guoshengCS** [comment]
V2不支持这种`@provider`这种用法吧

**Comment by xlhlhlx** [comment]
那该怎么修改呢？或者说，我想提高当前模型的训练速度，该怎么做呢？

**Comment by xlhlhlx** [comment]
把每次reader的时间打印出来了，都在1，2ms左右，那就是说明绝大部分时间在计算上面？那该怎么优化呢？
![88](https://user-images.githubusercontent.com/28750940/29647502-ff6a1922-88bb-11e7-9c1a-0bb3ec492e42.png)

**Comment by typhoonzero** [comment]
暂时关闭此Issue了，如果仍存在问题，可以reopen
