### ISSUE TITLE
在k40上基于paddle2.1编译生成的服务部署包，可以在k40上起服务并进行推理预测，但把包拷在t4机器上后，可起服务但无法推理预测，报错信息如下：terminate called after throwing an instance of 'paddle::platform::EnforceNotMet'

### ISSUE THREAD

**Issue by gongchenting** [PaddlePaddle/Paddle#36387]
paddle版本：2.1
k40：cuda10.1 cudnn7.6
t4：cuda10.1 cudnn7.6

**Comment by gongchenting** [comment]
gdb调试信息如下
![image](https://user-images.githubusercontent.com/89002176/137061609-858e469b-df84-4284-8601-285a9f64d9fc.png)

**Comment by gongchenting** [comment]
![image](https://user-images.githubusercontent.com/89002176/137062503-4d7061f2-c3a4-4c64-baa3-c650fad7f0de.png)

**Comment by OliverLPH** [comment]
https://github.com/PaddlePaddle/Paddle/blob/d7858c997b88c73c4fb0bb94db378578fd7e7f07/cmake/cuda.cmake#L84
Paddle 编译的时候，如果不指定GPU架构，会编译当前自动检测的GPU架构
如果需要在K40上编译，T4上运行，需要手动指定 `-DCUDA_ARCH_NAME=All`
https://github.com/PaddlePaddle/Paddle/blob/d7858c997b88c73c4fb0bb94db378578fd7e7f07/cmake/cuda.cmake#L83

**Comment by gongchenting** [comment]
但是相同的代码下，我只将paddle2.1换成paddle1.8的话，k40上编译的包在k40和t4上是都可以起服务且预测的。

**Comment by zh794390558** [comment]
按 @OliverLPH 的方法可以work吗？

**Comment by gongchenting** [comment]
现在已经解决了，但是是因为在t4上需要cuda额外的几个so文件，拷过去后就可以了，谢谢～
