### ISSUE TITLE
Mac下用docker从源码编译PaddlePaddle报错

### ISSUE THREAD

**Issue by handyzeng** [PaddlePaddle/Paddle#36381]
按照[官方教程](https://www.paddlepaddle.org.cn/documentation/docs/zh/install/compile/linux-compile.html)在docker中从源码编译cpu版本PaddlePaddle, 编译到一定阶段后卡住很久，然后就报出如下错误。重试多次，都是同样错误。

[ 17%] Built target scale_matmul_fuse_pass
[ 17%] Built target conv_elementwise_add_mkldnn_fuse_pass
[ 17%] Built target conv_concat_relu_mkldnn_fuse_pass
[ 17%] Built target conv_activation_mkldnn_fuse_pass
[ 18%] Built target conv_bias_mkldnn_fuse_pass
[ 18%] Built target pass_test_util
[ 18%] Built target depthwise_conv_mkldnn_pass
[ 18%] Built target softmax_op
[ 18%] Built target gelu_op
[ 18%] Building CXX object paddle/fluid/operators/CMakeFiles/activation_op.dir/activation_op.cc.o
c++: fatal error: Killed signal terminated program cc1plus
compilation terminated.
paddle/fluid/operators/CMakeFiles/activation_op.dir/build.make:62: recipe for target 'paddle/fluid/operators/CMakeFiles/activation_op.dir/activation_op.cc.o' failed
make[2]: *** [paddle/fluid/operators/CMakeFiles/activation_op.dir/activation_op.cc.o] Error 1
CMakeFiles/Makefile2:45851: recipe for target 'paddle/fluid/operators/CMakeFiles/activation_op.dir/all' failed
make[1]: *** [paddle/fluid/operators/CMakeFiles/activation_op.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2
λ moby /paddle/build {develop}

**Comment by AndPuQing** [comment]
请问您已解决这个问题吗，我也遇到了同样问题
