### ISSUE TITLE
实现了C-LSTM网络结构，但是运行的时候报错了

### ISSUE THREAD

**Issue by tonyhu20116543** [PaddlePaddle/Paddle#3642]
我按照 A C-LSTM Neural Network for Text Classification 这篇paper中实现了网络结构，然后运行的时候就报错了，在处理输入的时候固定了句子的长度
![image](https://user-images.githubusercontent.com/6749361/29620109-95e4f812-884f-11e7-8088-627f6016c597.png)
![image](https://user-images.githubusercontent.com/6749361/29620416-74e46cc8-8850-11e7-8f77-ed11af069f80.png)
![image](https://user-images.githubusercontent.com/6749361/29620449-869ddc9c-8850-11e7-9f08-6ddf47116056.png)
![image](https://user-images.githubusercontent.com/6749361/29620542-cb7cd67e-8850-11e7-995d-76bab20485ec.png)

**Comment by guoshengCS** [comment]
感觉这个不需要加trans_layer，每一行就是一个window内hidden_size维度的特征，这里加上trans_layer会破坏序列信息，可能会导致后续的数据check failed。

**Comment by jmfu95** [comment]
Did you implement C-LSTM successfully?@tonyhu20116543

**Comment by peterzhang2029** [comment]
Closing due to low activity. Feel free to reopen it.
