### ISSUE TITLE
用.so库报错version `GLIBC_2.14' not found

### ISSUE THREAD

**Issue by Jarlonyan** [PaddlePaddle/Paddle#3643]
之前用.so库可以运行的，然后更改了网络结构，重新编译，报下面的错。
```
Traceback (most recent call last):
  File "***/.BCloud/bcloud/Client/bcloud", line 21, in <module>
    import socket
  File "***/paddle/python27/lib/python2.7/socket.py", line 47, in <module>
    import _socket
ImportError: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by ***/paddle/python27/lib/python2.7/lib-dynload/_socket.so)
```

**Comment by guoshengCS** [comment]
LD_LIBRARY_PATH前加上gcc48的lib试下

**Comment by Jarlonyan** [comment]
不行啊。我在~/.bashrc中，将LD_LIBRARY_PATH加上了gcc48的lib。但是现在连vim都不不能用了。
Segmentation fault

**Comment by guoshengCS** [comment]
可以只在任务脚本里启动任务前加下，另外如果在开发机上编译的时候用那个指定目录的gcc，是会设置rpath的，应该就不需要再设置LD_LIBRARY_PATH

**Comment by Jarlonyan** [comment]
加了没有用啊。重启了可以编译通过。但是改了代码之后，重新编译又报同样的错误。

**Comment by Jarlonyan** [comment]
问题解决了，升级一下GLIBC就行。遇到相似问题的同学按照下面的链接进行就行。
但是很奇怪，为什么之前没有升级的时候，也可以正常运行。也许是别的同学改了环境吧。

http://blog.csdn.net/cpplang/article/details/8462768  
http://wiki.baidu.com/pages/viewpage.action?pageId=267863806

**Comment by guoshengCS** [comment]
好的，那这个Issue就先close了
