### ISSUE TITLE
使用半精度训练时如何便捷转换 data_format 

### ISSUE THREAD

**Issue by Zhiy-Zhang** [PaddlePaddle/Paddle#36437]
我看到这里使用amp的例子：
https://github.com/PaddlePaddle/models/blob/58f2127380bce2cc29f7896ce8c2f18de36e4b7d/PaddleCV/image_classification/build_model.py#L46
是通过args传入data_format 进行手动的转换

是否有更加便捷方式来进行格式转换那？比如像pytorch一样：model.to(memory_format=torch.channels_last)
这样比较便捷的方式，或者是我们这边已经有相应的api接口了，但是在文档中没有说明嘛？

**Comment by zhiboniu** [comment]
您好，您的反馈对产品非常有价值，我们内部会安排评估，未来有计划尽快回复。
目前看暂时还不支持这样的功能。

**Comment by Zhiy-Zhang** [comment]
那就是其实还没有便捷开关nhwc的api接口是吧

**Comment by zhiboniu** [comment]
现在对nhwc的开关就是在API参数中设置的，还没有全局设置方式
