### ISSUE TITLE
请问paddle1.8.5是否可以支持cuda11？

### ISSUE THREAD

**Issue by zhangtiegang2014** [PaddlePaddle/Paddle#36440]
最近在使用paddleFL的过程中，发现paddleFL最新只支持到paddle1.8.5，而看安装说明paddle1.8.5只支持cuda9、cuda10，而我们的rtx3060显卡只支持cuda11以上。请问这种情况有办法解决吗？

**Comment by zhiboniu** [comment]
您好，1.8.5版本最高支持到cuda10，不能支持cuda11。参考：https://github.com/PaddlePaddle/Paddle/issues/27530
建议您咨询一下PaddleFL对paddle最新版本支持的计划。
