### ISSUE TITLE
无监督和自监督的repo增加

### ISSUE THREAD

**Issue by TimZhang001** [PaddlePaddle/Paddle#36456]
目前自监督和无监督发展非常快，其中一些方法我们已经在产品中应用，比如一些anormaly detection的方法。是否有考虑将该类问题增加一个repo呢？

**Comment by yingyibiao** [comment]
您好，非常感谢您的咨询，我们想进一步和您沟通下需求背景以及使用场景。自监督和无监督是一个非常宽泛的概念，想问一下您期望的产品形态以及相对应的使用场景（除了anormaly detection还有哪些），以便我们内部进行更好的评估。另外，如果有类似的开源repo，也欢迎列出来供我们参考～

**Comment by TimZhang001** [comment]
https://paperswithcode.com/sota/anomaly-detection-on-mvtec-ad
可以参考这些。

**Comment by yingyibiao** [comment]
> https://paperswithcode.com/sota/anomaly-detection-on-mvtec-ad
> 可以参考这些。

好的，我们内部进行一下调研。
