### ISSUE TITLE
[模型输入信息] 无法获取模型输入shape信息

### ISSUE THREAD

**Issue by spacegrass** [PaddlePaddle/Paddle#36455]
问题描述：
- PaddlePaddle训练的 动态图模型
- 导出为静态图模型，导出名字没有自定义，使用的PaddlePaddle默认值：
  
 model.pdmodel
model.pdiparams

- 发现导出的模型只能使用 paddle_inference_api.h里的函数创建 Predictor类进行预测
- 无法使用paddle_api.h里的 PaddlePredictor类，创建时会报错
- 但   Predictor类里无法获取到模型的输入shape信息，但 通过netron是可以获取到的
- 请问这个模型我们怎么获取输入和输出的shape信息？

**Comment by jiweibo** [comment]
您好，关于导出模型name问题，可以参考文档https://www.paddlepaddle.org.cn/documentation/docs/zh/guides/04_dygraph_to_static/export_model/case_analysis_cn.html#jit-save


目前预测推荐使用的就是paddle_inference_api.h中的Predictor，PaddlePredictor已不建议使用，会在某一版本中去除。

此外关于模型输入shape的问题，因为netron可视化查看到的shape都是标称shape，该值无法保证正确，所以您需要根据模型的训练信息，去设置输入的shape，也就是说输入shape是您在代码中设置的。

输出shape的获取，predictor.run() 运行完毕后，可以取得 out_handle = predictor.get_output_handle(output_names[0])
可以从out_handle.shape()获取输出shape

**Comment by spacegrass** [comment]
谢谢回答，看了DOC文档的内容，还无法得到我想要的答案。
- 我们动态图训练的模型，在导出时会做 动 -> 静 的转换，并且设置模型的shape信息，也就是我们的推断的时候，会使用固定的shape
- 所以我们想在解析Paddle模型时获取到模型的shape信息，这个使用新的paddle_inference_api.h中的Predictor怎么获取到这些信息呢？

**Comment by jiweibo** [comment]
目前不能获取输入的shape哈，只能通过Reshape接口哈

**Comment by spacegrass** [comment]
> 目前不能获取输入的shape哈，只能通过Reshape接口哈

OK
