### ISSUE TITLE
[CMakeFiles/extern_cryptopp.dir/build.make:128: third_party/cryptopp/src/extern_cryptopp-stamp/extern_cryptopp-update] Error 1

### ISSUE THREAD

**Issue by uniyushu** [PaddlePaddle/Paddle#36468]
我在尝试[源码编译](https://www.paddlepaddle.org.cn/tutorials/projectdetail/1499138)tensorrt版paddle-gpu没有成功，遇到了extern_cryptopp的BUG，有人能帮我看下么
![image](https://user-images.githubusercontent.com/20262193/137464435-ac274fb5-91ef-435a-8adb-feac60a25c83.png)

环境采用的是nvidia的官方镜像：nvcr.io/nvidia/tensorrt:21.02-py3
![image](https://user-images.githubusercontent.com/20262193/137466021-1586d9a4-c4a9-4b04-b313-b0ca3a913902.png)
![image](https://user-images.githubusercontent.com/20262193/137465632-93b91d1d-39c2-446c-9660-3bb72aceb35f.png)
![image](https://user-images.githubusercontent.com/20262193/137466175-33b1a54b-3642-44b0-872d-d71d5ca97079.png)
![image](https://user-images.githubusercontent.com/20262193/137465097-c8a361ec-17b5-4121-8f52-98cf395d6e54.png)
编译命令参考
![image](https://user-images.githubusercontent.com/20262193/137464884-e18a754a-87f8-4c67-adc0-19f8f1c32091.png)

这是我的cmake配置
cmake -DPY_VERSION=3 
-DCMAKE_CUDA_ARCHITECTURES=70 
-DWITH_TESTING=OFF 
-DWITH_MKL=ON 
-DWITH_GPU=ON 
-DWITH_TENSORRT=ON
-DTENSORRT_ROOT=/data/TensorRT 
-DON_INFER=ON 
-DCMAKE_BUILD_TYPE=RelWithDebInfo
 ..

**Comment by jiweibo** [comment]
您好，首先您可以尝试使用最新的tag 2.2rc源码编译哈

如果还遇到crypto的问题，可以cmake的时候把它给关掉，-DWITH_CRYPTO=OFF

CMAKE_BUILD_TYPE设置为Release会快一些哈
