### ISSUE TITLE
在使用backward函数时，报错The type of grad_tensot must be paddle.Tensor

### ISSUE THREAD

**Issue by Yywwwwwww** [PaddlePaddle/Paddle#36477]
源代码：
for cover in tqdm(train):
        #for cover, _ in train:
            #cover = cover.to(device)
            batch_size = args.train_batch_size
            Critic.train()
            Encode.train()
            Decode.train()
            #gc.collect()
            with paddle.set_grad_enabled(True):  （此处存疑？？？？？？？？？？？？？）
          
                # ---------------- Train the discriminator -----------------------------
                for i in range(1):
                    adver_optimizer.clear_grad()# 把模型中参数的梯度设为0

                    d_target_label_cover = paddle.full((batch_size, 1), cover_label)
                    d_target_label_stego = paddle.full((batch_size, 1), stego_label)

                    # train on cover
                    d_on_cover = Critic(cover)
                    d_loss_cov = AdversaryLoss(d_on_cover, d_target_label_cover)
                    d_loss_cov.backward(True)  #？？？？？？？？？？？？？？？？？？？？？？？？？？
    
报错为：
d_loss_cov.backward(True)
  File "<decorator-gen-122>", line 2, in backward
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
    return wrapped_func(*args, **kwargs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/framework.py", line 227, in __impl__
    return func(*args, **kwargs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/varbase_patch_methods.py", line 226, in backward
    Tensor), "The type of grad_tensot must be paddle.Tensor"
AssertionError: The type of grad_tensot must be paddle.Tensor

**Comment by Intsigstephon** [comment]
您好，报错信息需要复现代码，请提供代码和环境信息，我们复现后会尽快回复您~

**Comment by Yywwwwwww** [comment]
源代码如下：
# -*- coding: utf-8 -*-

from math import exp
import paddle
from paddle.nn.functional import conv2d
import numpy as np
from paddle.static import InputSpec

def gaussian(window_size, sigma):
    """Gaussian window.

    https://en.wikipedia.org/wiki/Window_function#Gaussian_window
    """
    _exp = [exp(-(x - window_size // 2) ** 2 / float(2 * sigma ** 2)) for x in range(window_size)]
    gauss = paddle.to_tensor(_exp)
    return gauss / gauss.sum()


def create_window(window_size, channel):
    _1D_window = gaussian(window_size, 1.5).unsqueeze(1)
    _2D_window = _1D_window.mm(_1D_window.t()).astype('float32').unsqueeze(0).unsqueeze(0)
    window=paddle.expand(_2D_window,shape=[channel,1,window_size,window_size])
    #_2D_window = _1D_window.mm(_1D_window.t()).unsqueeze(0).unsqueeze(0)
    #window = _2D_window.expand(channel, 1, window_size, window_size).contiguous()  
    return window


def _ssim(img1, img2, window, window_size, channel, size_average=True):

    padding_size = window_size // 2

    mu1 = conv2d(img1, window, padding=padding_size, groups=channel)
    mu2 = conv2d(img2, window, padding=padding_size, groups=channel)

    mu1_sq = mu1.pow(2)
    mu2_sq = mu2.pow(2)
    mu1_mu2 = mu1 * mu2

    sigma1_sq = conv2d(img1 * img1, window, padding=padding_size, groups=channel) - mu1_sq
    sigma2_sq = conv2d(img2 * img2, window, padding=padding_size, groups=channel) - mu2_sq
    sigma12 = conv2d(img1 * img2, window, padding=padding_size, groups=channel) - mu1_mu2

    C1 = 0.01**2
    C2 = 0.03**2

    _ssim_quotient = ((2 * mu1_mu2 + C1) * (2 * sigma12 + C2))
    _ssim_divident = ((mu1_sq + mu2_sq + C1) * (sigma1_sq + sigma2_sq + C2))

    ssim_map = _ssim_quotient / _ssim_divident

    if size_average:
        return ssim_map.mean()
    else:
        return ssim_map.mean(1).mean(1).mean(1)


def _ssim_(img1, img2, window_size=11, size_average=True):
    channel = img1.shape[2]
    window = create_window(window_size, channel)

    img1=np.array(img1)
    img1 = InputSpec.from_numpy(img1)

    if img1.is_cuda:
        window = window.cuda(img1.get_device())
    window = window.type_as(img1)

    return _ssim(img1, img2, window, window_size, channel, size_average)

**Comment by yingyibiao** [comment]
看了一下上述代码，这一行有误：
d_loss_cov.backward(True) -> d_loss_cov.backward()

**Comment by Yywwwwwww** [comment]
请问什么时候可以解答呢？


-----原始邮件-----
发件人:"叶雅雯" ***@***.***>
发送时间:2021-11-12 17:27:37 (星期五)
收件人: ***@***.***, PaddlePaddle/Paddle ***@***.***>
抄送:
主题: Re: Re: [PaddlePaddle/Paddle] 在使用backward函数时，报错The type of grad_tensot must be paddle.Tensor (#36477)




-----原始邮件-----
发件人:"Bin Lu" ***@***.***>
发送时间:2021-10-16 10:38:33 (星期六)
收件人: PaddlePaddle/Paddle ***@***.***>
抄送: Yywwwwwww ***@***.***>, Author ***@***.***>
主题: Re: [PaddlePaddle/Paddle] 在使用backward函数时，报错The type of grad_tensot must be paddle.Tensor (#36477)






您好，报错信息需要复现代码，请提供代码和环境信息，我们复现后会尽快回复您~

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
