### ISSUE TITLE
pytorch转paddle  遇到'Tensor' object has no attribute 'is_cuda'和module 'paddle.nn' has no attribute 'conv2D'的问题

### ISSUE THREAD

**Issue by tsijeodhsjsh** [PaddlePaddle/Paddle#36471]
def _ssim_(img1, img2, window_size=11, size_average=True):
    #img1=img1.numpy()
    #(_, channel, _, _) = img1_size()
    channel=img1.shape[2]
    window = create_window(window_size, channel)

    if img1.is_cuda:
        window = window.cuda(img1.get_device())
    window = window.type_as(img1)

    return _ssim(img1, img2, window, window_size, channel, size_average)

问题1：
  File "/home/aistudio/ssim.py", line 61, in _ssim_
    if img1.is_cuda:
AttributeError: 'Tensor' object has no attribute 'is_cuda'

from math import exp
import paddle
import paddle.nn as nn
from paddle.nn.functional import conv2d
import numpy as np
from paddle.optimizer import Adam
import paddle.fluid as fluid
def _ssim(img1, img2, window, window_size, channel, size_average=True):

    padding_size = window_size // 2

    mu1 = nn.conv2D(img1, window, padding=padding_size, groups=channel)
    mu2 = nn.conv2D(img2, window, padding=padding_size, groups=channel)

    mu1_sq = mu1.pow(2)
    mu2_sq = mu2.pow(2)
    mu1_mu2 = mu1 * mu2

    sigma1_sq = nn.conv2D(img1 * img1, window, padding=padding_size, groups=channel) - mu1_sq
    sigma2_sq = nn.conv2D(img2 * img2, window, padding=padding_size, groups=channel) - mu2_sq
    sigma12 = nn.conv2D(img1 * img2, window, padding=padding_size, groups=channel) - mu1_mu2

    C1 = 0.01**2
    C2 = 0.03**2

    _ssim_quotient = ((2 * mu1_mu2 + C1) * (2 * sigma12 + C2))
    _ssim_divident = ((mu1_sq + mu2_sq + C1) * (sigma1_sq + sigma2_sq + C2))

    ssim_map = _ssim_quotient / _ssim_divident

    if size_average:
        return ssim_map.mean()
    else:
        return ssim_map.mean(1).mean(1).mean(1)
问题2：
File "/home/aistudio/ssim.py", line 31, in _ssim
    mu1 = nn.conv2D(img1, window, padding=padding_size, groups=channel)
AttributeError: module 'paddle.nn' has no attribute 'conv2D'

**Comment by yingyibiao** [comment]
在Paddle框架中，可以使用 tensor.place 来查看一个tensor的设备，见 https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/Tensor_cn.html#place
二维卷积对应的API是 paddle.nn.Conv2D ，见https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/nn/Conv2D_cn.html#conv2d
