### ISSUE TITLE
请问paddle-lite android armv7的编译库 set_threads 没有速度提升？（多核cpu的 使用率一直是100%或者如何开启openmp）

### ISSUE THREAD

**Issue by yank666** [PaddlePaddle/Paddle#36472]
paddle-lite 版本v2.9.1  , android armv7的多核cpu执行推理过程
我编译paddle-lite 库使用下面的命令
./lite/tools/build_android.sh --arch=armv7 --toolchain=clang --android_stl=c++_shared --with_java=OFF --build_extra=ON --android_api_level=28
在cpu上跑时 设置多线程为4 和多线程设置为1 推理速度一样，没有性能的提升，cpu使用率最高也是100%（多核cpu），
请问如何提升推理速度，（如何开启openmp 或者多线程等手段加速推理）

**Comment by yingyibiao** [comment]
您好，看到您在Paddle-Lite的issue区也提问了，Paddle-Lite的相关问题在相应的issue区提问就OK了～

**Comment by mjp9527** [comment]
您好，--toolchain=gcc，clang armv7目前不支持openmp
