### ISSUE TITLE
deformable_conv在2.1版本中如何实现

### ISSUE THREAD

**Issue by Sunyingbin** [PaddlePaddle/Paddle#36470]
1.8版本的可变性卷积deformable_conv，在2.1的版本中是如何实现的？我看了paddleocr中搭建DBFPN的model，里面就是用传统的卷积核来实现的

**Comment by yingyibiao** [comment]
您好，2.1版本中deformable_convAPI可以参考 https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/vision/ops/DeformConv2D_cn.html
