### ISSUE TITLE
paddle.Tensor参数问题

### ISSUE THREAD

**Issue by ZiJINII** [PaddlePaddle/Paddle#36478]
<ipython-input-2-d771b26d09d8> in <module>
     79 # 准备网络 MSSNet
     80 print("Generate model")
---> 81 net = MSSNet()#?
     82 print(net)
     83 
~/work/MSSN.py in __init__(self, with_bn, threshold)
    197         super(MSSNet, self).__init__()
    198         self.with_bn = with_bn
--> 199         self.preprocessing = SRM_conv2d(1, 0)
    200         self.preprocessing = Res_conv2d()
    201         self.norm1 = nn.BatchNorm2d(30)
~/work/MSSN.py in __init__(self, stride, padding)
     28         self.output_padding = (0,)
     29         self.groups = 1
---> 30         self.weight = nn.Layer.parameters(paddle.Tensor(30,1,5,5),
     31                                 requires_grad=True)
     32         self.bias = nn.Layer.parameters(paddle.Tensor(30),
TypeError: __init__(): incompatible constructor arguments. The following argument types are supported:
    1. paddle.fluid.core_avx.VarBase()
    2. paddle.fluid.core_avx.VarBase(arg0: paddle::framework::proto::VarType_Type, arg1: List[int], arg2: handle, arg3: paddle::framework::proto::VarType_Type, arg4: bool)
    3. paddle.fluid.core_avx.VarBase(value: array, place: paddle::platform::CPUPlace, persistable: bool = False, zero_copy: bool = False, name: str = '', stop_gradient: int = -1)
    4. paddle.fluid.core_avx.VarBase(value: array, place: paddle::platform::XPUPlace, persistable: bool = False, zero_copy: bool = False, name: str = '', stop_gradient: int = -1)
    5. paddle.fluid.core_avx.VarBase(value: array, place: paddle::platform::CUDAPlace, persistable: bool = False, zero_copy: bool = False, name: str = '', stop_gradient: int = -1)
    6. paddle.fluid.core_avx.VarBase(value: array, place: paddle::platform::CUDAPinnedPlace, persistable: bool = False, zero_copy: bool = False, name: str = '', stop_gradient: int = -1)
    7. paddle.fluid.core_avx.VarBase(value: array)
    8. paddle.fluid.core_avx.VarBase(tensor: paddle::framework::LoDTensor)
    9. paddle.fluid.core_avx.VarBase(**kwargs)

Invoked with: 30, 1, 5, 5
**不知道是参数的问题还是torch转paddle接口错误**

**Comment by yingyibiao** [comment]
您好，报错信息需要复现代码，请提供代码和环境信息，我们复现后会尽快回复您~

**Comment by yingyibiao** [comment]
看了一下，可能是create_parameter接口使用有误，可以修改为self.weight = self.create_parameter([30,1,5,5])
接口具体文档可以参考： https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/nn/Layer_cn.html#create_parameter
