### ISSUE TITLE
jetson nano 预测报错

### ISSUE THREAD

**Issue by 007cod** [PaddlePaddle/Paddle#36496]
设备信息：
**CUDA 10.2
TensorRT 8.0.1
cuDNN 8.2.1**
报错信息：
--------------------------------------

C++ Traceback (most recent call last):

--------------------------------------

0   paddle::framework::SignalHandle(char const*, int)

1   paddle::platform::GetCurrentTraceBackString[abi:cxx11]()

----------------------

Error Message Summary:

----------------------

FatalError: `Process abort signal` is detected by the operating system.

  [TimeInfo: *** Aborted at 1634482316 (unix time) try "date -d @1634482316" if you are using GNU date ***]

  [SignalInfo: *** SIGABRT (@0x2cde) received by PID 11486 (TID 0x7fa35a3010) from PID 11486 ***]

Aborted

**Comment by weisy11** [comment]
你好，可以给出更详细的信息吗？比如你是在运行什么脚本的时候报错？在你的nano设备上有成功运行过paddle的程序吗？

**Comment by 007cod** [comment]
> 
> 
> 你好，可以给出更详细的信息吗？比如你是在运行什么脚本的时候报错？在你的nano设备上有成功运行过paddle的程序吗？


def predict_config(model_file, params_file):
    config = Config()
    config.set_prog_file(model_file)
    config.set_params_file(params_file)
    config.enable_use_gpu(500, 0)
    config.switch_ir_optim()
    config.enable_memory_optim()
    config.enable_tensorrt_engine(workspace_size=1 << 30, precision_mode=PrecisionType.Float32, max_batch_size=1,
                                  min_subgraph_size=5, use_static=False, use_calib_mode=False)
    predictor = create_predictor(config)
    return predictor
你好， 我是在创建predictor的时候报的错误。

**Comment by 007cod** [comment]
paddlepaddle_gpu的测试也是正常的

**Comment by weisy11** [comment]
这段程序看不出具体的问题。配置是你自己写的吗？还是基于paddle的开源脚本改的呢？在其他设备上可以正常运行吗？

**Comment by weisy11** [comment]
建议提供一个最小可复现问题的脚本

**Comment by 007cod** [comment]
以下是从借鉴一篇博客的预测代码（mypredict.py）
```
import cv2
import numpy as np
from paddle.inference import Config
from paddle.inference import PrecisionType
from paddle.inference import create_predictor
import yaml
import time


# ————————————————图像预处理函数———————————————— #

def resize(img, target_size):
    """resize to target size"""
    if not isinstance(img, np.ndarray):
        raise TypeError('image type is not numpy.')
    im_shape = img.shape
    im_size_min = np.min(im_shape[0:2])
    im_size_max = np.max(im_shape[0:2])
    im_scale_x = float(target_size) / float(im_shape[1])
    im_scale_y = float(target_size) / float(im_shape[0])
    img = cv2.resize(img, None, None, fx=im_scale_x, fy=im_scale_y)
    return img


def normalize(img, mean, std):
    img = img / 255.0
    mean = np.array(mean)[np.newaxis, np.newaxis, :]
    std = np.array(std)[np.newaxis, np.newaxis, :]
    img -= mean
    img /= std
    return img


def preprocess(img, img_size):
    mean = [0.485, 0.456, 0.406]
    std = [0.229, 0.224, 0.225]
    img = resize(img, img_size)
    img = img[:, :, ::-1].astype('float32')  # bgr -> rgb
    img = normalize(img, mean, std)
    img = img.transpose((2, 0, 1))  # hwc -> chw
    return img[np.newaxis, :]


# ——————————————————————模型配置、预测相关函数—————————————————————————— #
def predict_config(model_file, params_file):
    '''
    函数功能：初始化预测模型predictor
    函数输入：模型结构文件，模型参数文件
    函数输出：预测器predictor
    '''
    # 根据预测部署的实际情况，设置Config
    config = Config()
    # 读取模型文件
    config.set_prog_file(model_file)
    config.set_params_file(params_file)
    # Config默认是使用CPU预测，若要使用GPU预测，需要手动开启，设置运行的GPU卡号和分配的初始显存。
    config.enable_use_gpu(500, 0)
    # 可以设置开启IR优化、开启内存优化。
    config.switch_ir_optim()
    config.enable_memory_optim()
    config.enable_tensorrt_engine(workspace_size=1 << 30, precision_mode=PrecisionType.Float32, max_batch_size=1,
                                  min_subgraph_size=5, use_static=False, use_calib_mode=False)
    predictor = create_predictor(config)
    return predictor


def predict(predictor, img):
    '''
    函数功能：初始化预测模型predictor
    函数输入：模型结构文件，模型参数文件
    函数输出：预测器predictor
    '''
    input_names = predictor.get_input_names()
    for i, name in enumerate(input_names):
        input_tensor = predictor.get_input_handle(name)
        input_tensor.reshape(img[i].shape)
        input_tensor.copy_from_cpu(img[i].copy())
    # 执行Predictor
    predictor.run()
    # 获取输出
    results = []
    # 获取输出
    output_names = predictor.get_output_names()
    for i, name in enumerate(output_names):
        output_tensor = predictor.get_output_handle(name)
        output_data = output_tensor.copy_to_cpu()
        results.append(output_data)
    return results


# ——————————————————————后处理函数—————————————————————————— #
def draw_bbox_image(frame, result, label_list, threshold=0.5):
    for res in result:
        cat_id, score, bbox = res[0], res[1], res[2:]
        if score < threshold:
            continue
        for i in bbox:
            int(i)
        xmin, ymin, xmax, ymax = bbox
        cv2.rectangle(frame, (xmin, ymin), (xmax, ymax), (255, 0, 255), 2)
        print('category id is {}, bbox is {}'.format(cat_id, bbox))
        try:
            label_id = label_list[int(cat_id)]
            # #cv2.putText(图像, 文字, (x, y), 字体, 大小, (b, g, r), 宽度)
            cv2.putText(frame, label_id, (int(xmin), int(ymin - 2)), cv2.FONT_HERSHEY_SIMPLEX, 0.5, (255, 0, 0), 2)
            cv2.putText(frame, str(round(score, 2)), (int(xmin - 35), int(ymin - 2)), cv2.FONT_HERSHEY_SIMPLEX, 0.5,
                        (0, 255, 0), 2)
        except KeyError:
            pass


if __name__ == '__main__':

    # 从infer_cfg.yml中读出label
    infer_cfg = open('yolov3_r50vd_dcn_270e_coco/infer_cfg.yml')
    data = infer_cfg.read()
    yaml_reader = yaml.load(data)
    label_list = yaml_reader['label_list']
    print(label_list)

    # 配置模型参数
    model_file = "./yolov3_r50vd_dcn_270e_coco/model.pdmodel"
    params_file = "./yolov3_r50vd_dcn_270e_coco/model.pdiparams"
    # 初始化预测模型
    predictor = predict_config(model_file, params_file)

    cap = cv2.VideoCapture(0)
    # 图像尺寸相关参数初始化
    ret, img = cap.read()
    im_size = 224
    scale_factor = np.array([im_size * 1. / img.shape[0], im_size * 1. / img.shape[1]]).reshape((1, 2)).astype(
        np.float32)
    im_shape = np.array([im_size, im_size]).reshape((1, 2)).astype(np.float32)

    while True:
        ret, frame = cap.read()
        # 预处理
        data = preprocess(frame, im_size)

        time_start = time.time()
        # 预测
        result = predict(predictor, [im_shape, data, scale_factor])
        print('Time Cost：{}'.format(time.time() - time_start), "s")

        draw_bbox_image(frame, result[0], label_list, threshold=0.1)

        cv2.imshow("frame", frame)
        if cv2.waitKey(1) & 0xFF == ord('q'):
            break
```
以下是自己写的主程序调用了上述预测代码（import mypredict）
```
import imageio
import os
import mypredict as mp
import numpy as np
import time
import cv2 as cv
import yaml
os.environ['CUDA_VISIBLE_DIVICES']='1'
path = '1632099242618.mp4'
cap = imageio.get_reader(path, 'ffmpeg')
model_file = 'inference2_model/ppyolo/inference_model/model.pdmodel'
params_file = 'inference2_model/ppyolo/inference_model/model.pdiparams'
model_yml_path = 'inference2_model/ppyolo/inference_model/model.yml'
infer_cfg = open(model_yml_path)
data = infer_cfg.read()
yaml_reader = yaml.load(data)
label_list = yaml_reader['_Attributes']['labels']
num=0
times=0
im_size = 416
predictor = mp.predict_config(model_file, params_file)

for img in cap:
    num+=1
    if num % 10 != 0:
        continue
    img = cv.cvtColor(img, cv.COLOR_RGB2BGR)
    scale_factor = np.array([im_size * 1. / img.shape[0], im_size * 1. / img.shape[1]]).reshape((1, 2)).astype(
        np.float32)
    im_shape = np.array([im_size, im_size]).reshape((1, 2)).astype(np.float32)
    data = mp.preprocess(img, im_size)
    time_start=time.time()
    result = mp.predict(predictor, [im_shape, data, scale_factor])
    b=time.time()

    print('Time Cost：{}'.format(time.time() - time_start), "s")
    mp.draw_bbox_image(img, result[0], label_list, threshold=0.5)
    cv.imshow('feage', img)
    if cv.waitKey(10)& 0xFF == ord('q'):
            break
print('grsgrg%.10f',times/(num/10))
```
在运行到mypredict.py中predict_config函数中的predictor = create_predictor(config)语句时出现上述错误

**Comment by 007cod** [comment]
> 
> 
> 这段程序看不出具体的问题。配置是你自己写的吗？还是基于paddle的开源脚本改的呢？在其他设备上可以正常运行吗？

这个代码在windows上面是跑起来了，只不过在运行到predictor部分的时候会有警告

**Comment by weisy11** [comment]
好的，我复现一下这个问题

**Comment by weisy11** [comment]
>     config = Config()
>     # 读取模型文件
>     config.set_prog_file(model_file)
>     config.set_params_file(params_file)
>     # Config默认是使用CPU预测，若要使用GPU预测，需要手动开启，设置运行的GPU卡号和分配的初始显存。
>     config.enable_use_gpu(500, 0)
>     # 可以设置开启IR优化、开启内存优化。
>     config.switch_ir_optim()
>     config.enable_memory_optim()
>     config.enable_tensorrt_engine(workspace_size=1 << 30, precision_mode=PrecisionType.Float32, max_batch_size=1,
>                                   min_subgraph_size=5, use_static=False, use_calib_mode=False)
>     predictor = create_predictor(config)

这个代码有针对gpu做设置，这部分代码你了解吗？在迁移到jetson nano的时候是否有根据设备情况修改？
另外，如果需要使用目标检测算法，推荐你看看paddle官方的项目[PaddleDetection](https://github.com/PaddlePaddle/PaddleDetection)，也支持[python预测部署](https://github.com/PaddlePaddle/PaddleDetection/tree/release/2.2/deploy/python)
遇到问题可以更高效解决

**Comment by 007cod** [comment]
> > ```
> > config = Config()
> > # 读取模型文件
> > config.set_prog_file(model_file)
> > config.set_params_file(params_file)
> > # Config默认是使用CPU预测，若要使用GPU预测，需要手动开启，设置运行的GPU卡号和分配的初始显存。
> > config.enable_use_gpu(500, 0)
> > # 可以设置开启IR优化、开启内存优化。
> > config.switch_ir_optim()
> > config.enable_memory_optim()
> > config.enable_tensorrt_engine(workspace_size=1 << 30, precision_mode=PrecisionType.Float32, max_batch_size=1,
> >                               min_subgraph_size=5, use_static=False, use_calib_mode=False)
> > predictor = create_predictor(config)
> > ```
> 
> 这个代码有针对gpu做设置，这部分代码你了解吗？在迁移到jetson nano的时候是否有根据设备情况修改？ 另外，如果需要使用目标检测算法，推荐你看看paddle官方的项目[PaddleDetection](https://github.com/PaddlePaddle/PaddleDetection)，也支持[python预测部署](https://github.com/PaddlePaddle/PaddleDetection/tree/release/2.2/deploy/python) 遇到问题可以更高效解决

你好，这段代码部署在我的设备上应该是不会起冲突的。
我用的是paddlex2.0训练好的并导出的部署模型，并没有使用PaddleDetection
我们用的jetpack版本是4.6不知道官方有没有在这方面对jetson nano进行过测试

**Comment by wangye707** [comment]
@007cod 你好，飞桨在2.2.0-rc版本开始正式支持jetapck4.6(cuda10.2+cudnn8.2.1+trt8),你的版本是否正确？2.2.0-rc0下载链接：https://paddle-inference-lib.bj.bcebos.com/2.2.0-rc0/python/Jetson/jetpack4.6_gcc7.5/all/paddlepaddle_gpu-2.2.0rc0-cp36-cp36m-linux_aarch64.whl

**Comment by 007cod** [comment]
> 
> 
> @007cod 你好，飞桨在2.2.0-rc版本开始正式支持jetapck4.6(cuda10.2+cudnn8.2.1+trt8),你的版本是否正确？2.2.0-rc0下载链接：https://paddle-inference-lib.bj.bcebos.com/2.2.0-rc0/python/Jetson/jetpack4.6_gcc7.5/all/paddlepaddle_gpu-2.2.0rc0-cp36-cp36m-linux_aarch64.whl

太感谢了， 问题已经解决了
