### ISSUE TITLE
请问PaddlePaddle如何实现Gram-CTC

### ISSUE THREAD

**Issue by yeyupiaoling** [PaddlePaddle/Paddle#36491]
是这篇论文[《Gram-CTC: Automatic Unit Selection and Target Decomposition for Sequence Labelling》](https://arxiv.org/abs/1703.00096)

**Comment by smallv0221** [comment]
您可以参考这篇指南对论文内容进行复现
https://github.com/PaddlePaddle/models/blob/develop/docs/ThesisReproduction_CV.md

**Comment by yeyupiaoling** [comment]
PaddlePaddle没有现成的吗？

**Comment by smallv0221** [comment]
这边暂时是没有的哈，推荐您参考指南进行复现

**Comment by yeyupiaoling** [comment]
OK！OK！
