### ISSUE TITLE
Add prefetch method to PaddleAPI's GradientMachine.

### ISSUE THREAD

**Issue by reyoung** [PaddlePaddle/Paddle#365]
There is not [`prefetch` method](https://github.com/baidu/Paddle/blob/develop/paddle/gserver/gradientmachines/GradientMachine.h#L130) in class [GradientMachine](https://github.com/baidu/Paddle/blob/develop/paddle/api/PaddleAPI.h#L627) defined in PaddleAPI.h However, we need to add this method, which related to #364. In particular, we need to use it with sparse_udpate and sparse_remote_update.

When used with `sparse update`, `prefetch` is supposed to be invoked before `forward`/`backward`. `sparse_update` through SWIG cannot be performed without `prefetch`.

Also `prefetch` should be added to the monkey patch method [`forwardTest`](https://github.com/baidu/Paddle/blob/develop/paddle/py_paddle/util.py#L136)  when `sparse update` is enabled.

The whole architecture of multi-language support is described by issue #258 .

**Comment by reyoung** [comment]
Related #413

**Comment by 20092136** [comment]
请问这个问题大约什么时候能 fix？

**Comment by backyes** [comment]
@reyoung predict应该可以不需要prefetch，在layer wrapper里，确认是predict的话，就可以disable prefetch（等价于disable sparse_remote_update选项）

**Comment by backyes** [comment]
@20092136 临时解决方法： 预测的时候将模型配置里的所有关于稀疏的配置去掉，即可。

**Comment by qingqing01** [comment]
this feature had been supported in V2 API.
