### ISSUE TITLE
Operators that need to port to new framework

### ISSUE THREAD

**Issue by jacquesqiao** [PaddlePaddle/Paddle#3650]
* [paddle/paddle/gserver/layers](https://github.com/PaddlePaddle/Paddle/tree/develop/paddle/gserver/layers)
    - 108
* [paddle/paddle/gserver/activations](https://github.com/PaddlePaddle/Paddle/tree/develop/paddle/gserver/activations)
* [paddle/paddle/gserver/evaluators](https://github.com/PaddlePaddle/Paddle/tree/develop/paddle/gserver/evaluators)
    - need to redesign as Operators.

**Comment by qingqing01** [comment]
- Need a doc about tow to write new layers.

下面Op排除了operators里已经实现的：

- ElementWise:

```
power
tanh
exp
relu
brelu
softrelu
stanh
abs
square
log
sqrt
reciprocal
```

-  Base on dense tensor.

```
fc_layer
img_conv_layer (cudnn, gemm)
img_pool_layer (max, avg)
batch_norm_layer
img_cmrnorm_layer
concat_layer
maxout_layer
spp_layer (pooling组合)
cross_channel_norm_layer
bilinear_interp_layer
trans_layer
pad_layer
crop_layer
clip_layer
dropout_layer
dotmul_projection
interpolation_layer
sum_to_one_norm_layer
row_l2_norm_layer
conv_operator
prelu_layer
conv_shift_layer
tensor_layer
sampling_id_layer
convex_comb_layer
priorbox_layer
detection_output_layer
multiplex_layer
featuremap_expand
```
- base on sequence info

```
seq_reshape_layer
pooling_layer (sequence pooling，需增强支持window，stride，考虑可否与img_pool合并)
grumemory
lstmemory
gru_step_layer
lstm_step_layer
last_seq
first_seq
expand_layer
seq_concat_layer
context_projection
recurrent_layer
ctc_layer
warp_ctc_layer
crf_layer
crf_decoding_layer
block_expand_layer
out_prod_layer
row_conv_layer
multibox_loss_layer
eos_layer
```

- Cost
```
cos_sim
hsigmoid
mse_cost
nce_layer
cross_entropy_with_selfnorm
rank_cost
lambda_cost
huber_cost
smooth_l1_cost
```

**Comment by qingqing01** [comment]
Welcome to add new and necessary operators.

**Comment by qingqing01** [comment]
@Superjom 

感觉， elementmise 类似的应该是作为 helper function 好一些吧
elementwise_check() ... 
same_shape_check(inputs) ... 

@zchen0211 

大量被各处使用的功能会被定义为functor()

**Comment by chengduoZH** [comment]
还有 img_pool3D_layer (max, avg)
