### ISSUE TITLE
opencv dnn模块调用paddlepaddle模型进行预测问题

### ISSUE THREAD

**Issue by gxqnba** [PaddlePaddle/Paddle#36515]
刚在opencv官网上看到了opencv dnn模块可以直接调用paddle训练的模型（转换为onnx），相关连接如下，https://github.com/opencv/opencv/tree/master/samples/dnn/dnn_model_runner/dnn_conversion/paddlepaddle
请问opencv dnn模块是支持所有的paddle模型，还是只支持链接案例给的两种

**Comment by weisy11** [comment]
理论上，可以转成onnx的模型都是可以的，不过并非所有模型都可以转成onnx

**Comment by gxqnba** [comment]
好的，谢谢！


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/Paddle"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年10月18日(星期一) 晚上8:21
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PaddlePaddle/Paddle] opencv dnn模块调用paddlepaddle模型进行预测问题 (Issue #36515)





 
理论上，可以转成onnx的模型都是可以的，不过并非所有模型都可以转成onnx
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
