### ISSUE TITLE
Multi-GPU support

### ISSUE THREAD

**Issue by jacquesqiao** [PaddlePaddle/Paddle#3651]
see below in detail: 
Survey on Multi GPU Feature https://github.com/dzhwinter/Paddle/wiki/Survey-on-Multi-GPU-Feature

**Comment by dzhwinter** [comment]
1、survery NCCL library, tensorflow implement.
2、design the Interface of communicating with parameter server.

**Comment by dzhwinter** [comment]
## Caffe2 &NCCL library
   at present, it is NCCL2. the library implements the following collectives.
    * all-reduce
    * all-gather
    * reduce-scatter
    * reduce
    * broadcast
ring algorithm. Send TensorCUDA every for loop.
