### ISSUE TITLE
python平台的图像卷积搬移到paddle paddle平台

### ISSUE THREAD

**Issue by tsijeodhsjsh** [PaddlePaddle/Paddle#36516]
python源代码：
# -*- coding: utf-8 -*-

from math import exp
import torch
from torch.nn.functional import conv2d
from torch.optim.adam import Adam

def gaussian(window_size, sigma):
    """Gaussian window.

    https://en.wikipedia.org/wiki/Window_function#Gaussian_window
    """
    _exp = [exp(-(x - window_size // 2) ** 2 / float(2 * sigma ** 2)) for x in range(window_size)]
    gauss = torch.Tensor(_exp)
    return gauss / gauss.sum()

def create_window(window_size, channel):
    _1D_window = gaussian(window_size, 1.5).unsqueeze(1)
    _2D_window = _1D_window.mm(_1D_window.t()).float().unsqueeze(0).unsqueeze(0)
    window = _2D_window.expand(channel, 1, window_size, window_size).contiguous()
    return window

def _ssim(img1, img2, window, window_size, channel, size_average=True):

    padding_size = window_size // 2

    mu1 = conv2d(img1, window, padding=padding_size, groups=channel)           //!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    mu2 = conv2d(img2, window, padding=padding_size, groups=channel)

    mu1_sq = mu1.pow(2)
    mu2_sq = mu2.pow(2)
    mu1_mu2 = mu1 * mu2

    sigma1_sq = conv2d(img1 * img1, window, padding=padding_size, groups=channel) - mu1_sq
    sigma2_sq = conv2d(img2 * img2, window, padding=padding_size, groups=channel) - mu2_sq
    sigma12 = conv2d(img1 * img2, window, padding=padding_size, groups=channel) - mu1_mu2

    C1 = 0.01**2
    C2 = 0.03**2

    _ssim_quotient = ((2 * mu1_mu2 + C1) * (2 * sigma12 + C2))
    _ssim_divident = ((mu1_sq + mu2_sq + C1) * (sigma1_sq + sigma2_sq + C2))

    ssim_map = _ssim_quotient / _ssim_divident

    if size_average:
        return ssim_map.mean()
    else:
        return ssim_map.mean(1).mean(1).mean(1)

def _ssim_(img1, img2, window_size=11, size_average=True):
    (_, channel, _, _) = img1.size()
    window = create_window(window_size, channel)

    if img1.is_cuda:
        window = window.cuda(img1.get_device())
    window = window.type_as(img1)

    return _ssim(img1, img2, window, window_size, channel, size_average)

问题：mu1 = conv2d(img1, window, padding=padding_size, groups=channel)           
    mu2 = conv2d(img2, window, padding=padding_size, groups=channel)
目的：实现img1以window（符合高斯分布的随机变量）为卷积核的卷积

paddlepaddle上改为：
mu1 = Conv2D(img1, window, padding=padding_size, groups=channel)
    mu2 = Conv2D(img2, window, padding=padding_size, groups=channel)
后显示不正确，且Conv2D与conv2d实现的功能不同

！！！所以这里的conv2d在paddlepaddle平台上怎么实现？

**Comment by weisy11** [comment]
是的，paddle.nn.Conv2D主要用于深度学习。如果不需要训练，只需要做卷积运算，建议使用paddle.nn.functional.conv2d，参考：https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/nn/functional/conv2d_cn.html#conv2d

**Comment by tsijeodhsjsh** [comment]
可是怎么实现目的：img1以window（符合高斯分布的随机变量）为卷积核的卷积。用conv2d怎么实现高斯分布

**Comment by tsijeodhsjsh** [comment]
def _ssim(img1, img2, window, window_size, channel, size_average=True):

    padding_size = window_size // 2
    mu1 = F.conv2d(img1, window, padding=padding_size, groups=channel)
    mu2 = F.conv2d(img2, window, padding=padding_size, groups=channel)

    mu1_sq = mu1.pow(2)
    mu2_sq = mu2.pow(2)
    mu1_mu2 = mu1 * mu2

    sigma1_sq = F.conv2d(img1 * img1, window, padding=padding_size, groups=channel) - mu1_sq
    sigma2_sq = F.conv2d(img2 * img2, window, padding=padding_size, groups=channel) - mu2_sq
    sigma12 = F.conv2d(img1 * img2, window, padding=padding_size, groups=channel) - mu1_mu2

    C1 = 0.01**2
    C2 = 0.03**2

    _ssim_quotient = ((2 * mu1_mu2 + C1) * (2 * sigma12 + C2))
    _ssim_divident = ((mu1_sq + mu2_sq + C1) * (sigma1_sq + sigma2_sq + C2))

    ssim_map = _ssim_quotient / _ssim_divident

    if size_average:
        return ssim_map.mean()
    else:
        return ssim_map.mean(1).mean(1).mean(1)


def _ssim_(img1, img2, window_size=11, size_average=True):
    #img1=img1.numpy()
    #(_, channel, _, _) = img1_size()
    channel=img1.shape[2]
    window = create_window(window_size, channel)

    # if img1.is_cuda:
    #     window = window.cuda(img1.get_device())
    fluid.layers.cast(window,img1.dtype)

    return _ssim(img1, img2, window, window_size, channel, size_average)

问题：
  mu1 = F.conv2d(img1, window, padding=padding_size, groups=channel)
编译后出现如下错误：
ValueError: the channel of input must be divisible by groups,received: the channel of input is 3, the shape of input is [4, 3, 256, 256], the groups is 256

**Comment by tsijeodhsjsh** [comment]
已经解决了，谢谢
