### ISSUE TITLE
Python API

### ISSUE THREAD

**Issue by Superjomn** [PaddlePaddle/Paddle#3652]
- design:
  - namespace
  - pd.eval
  - Var/Variable
  - Op/Layer

design doc: 8/24 night
discussion and conclusion: 8/25 night
mnist implementation: 8/27 night

- milestones
  - [ ] design
  - [ ] support mnist
  - [ ] v2 compatible wrapper
  - [ ] document about how to write a layer in python

**Comment by jacquesqiao** [comment]
Better parameter sharing

**Comment by wangkuiyi** [comment]
Let us don't change much to the v2 API.
