### ISSUE TITLE
Distribute Support Design Doc

### ISSUE THREAD

**Issue by helinwang** [PaddlePaddle/Paddle#3656]
1. Survey 8/25 Friday EOD
    - Different frameworks
        - TensorFlow
            - architecture https://www.tensorflow.org/extend/architecture
            - [multi-GPU train example](https://github.com/tensorflow/models/blob/master/tutorials/image/cifar10/cifar10_multi_gpu_train.py)
     
        - Caffe2
        - PyTorch
        - MxNet http://mxnet.io/how_to/multi_devices.html#distributed-training-with-multiple-machines
    - Different styles
        - Single OP for all: single machine, multiple GPU on single machine, multiple machine.
        - Different OP for different purpose.
1. Design doc PR 8/29 Tuesday EOD

**Comment by typhoonzero** [comment]
Some old wiki: 
https://github.com/PaddlePaddle/Paddle/wiki/Comparison-of-Distributed-Training-Implementation

Thoughts:

- First implementation:
    - Add one op (like `remote_optimize_op`, `prefetch_op` etc.) to communicate with the new parameter server. Support only async-SGD.
    - Common optimizers port to op.

- Full function:
    - support sync-SGD
    - support sparse update

**Comment by dzhwinter** [comment]
For the distribute support, the mxnet mixed the sync interface of Multi-GPU and Multi-Machine of `dist_sync`,`dist_device_sync`.And same for the asynchronous `dist_async`. 
here is the detail.  http://mxnet.io/how_to/multi_devices.html#distributed-training-with-multiple-machines

**Comment by helinwang** [comment]
Related: https://github.com/PaddlePaddle/Paddle/issues/2306

**Comment by helinwang** [comment]
This issue is out-of-date, closing.
