### ISSUE TITLE
复现 parambase没有‘data’属性

### ISSUE THREAD

**Issue by ethelgriffin** [PaddlePaddle/Paddle#36560]
self.weight = fluid.layers.create_parameter(shape=[30, 1, 5, 5],
                                 dtype='float32')
        self.bias = fluid.layers.create_parameter(shape=(30),
                              dtype='float32')
        self.reset_parameters()

    def reset_parameters(self):
        self.weight.data.numpy()[:] = SRM_npy
        self.bias.data.zero_()

报错
---> 59         self.weight.data.numpy()[:] = SRM_npy
     60         self.bias.data.zero_()
     61 
AttributeError: 'ParamBase' object has no attribute 'data'

torch原代码：
        self.weight = Parameter(torch.Tensor(30, 1, 5, 5),
                                requires_grad=True)
        self.bias = Parameter(torch.Tensor(30),
                              requires_grad=True)
        self.reset_parameters()
        
    def reset_parameters(self):
        self.weight.data.numpy()[:] = SRM_npy
        self.bias.data.zero_()
请问要怎么修改

**Comment by WenmuZhou** [comment]
你好，paddle的Tensor没有data这个属性，可以使用default_initializer来对tensor进行初始化，参考下面的代码
weight = paddle.create_parameter(shape=[30],dtype='float32',default_initializer=paddle.nn.initializer.Assign(SRM_npy))
bias = paddle.create_parameter(shape=[30],dtype='float32',default_initializer=paddle.nn.initializer.Constant(0))
