### ISSUE TITLE
复现 遍历模块初始化问题

### ISSUE THREAD

**Issue by ethelgriffin** [PaddlePaddle/Paddle#36572]
class MSSNet(fluid.dygraph.Layer):
    ……
    def reset_parameters(self):
         for m in self.modules():
             if isinstance(m, SRM_conv2d):
                 m.reset_parameters()
             elif isinstance(m, Res_conv2d):
                 m.reset_parameters()
报错
--> 269         for m in self.modules():
    270             if isinstance(m, SRM_conv2d):
    271                 m.reset_parameters()
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py in __getattr__(self, name)
   1048             if name in _buffers:
   1049                 return _buffers[name]
-> 1050         return object.__getattribute__(self, name)
   1051 
   1052     def __setattr__(self, name, value):
AttributeError: 'MSSNet' object has no attribute 'modules'
请问怎样修改

**Comment by WenmuZhou** [comment]
改为self.sublayers()即可
