### ISSUE TITLE
optimizer.step() Error 

### ISSUE THREAD

**Issue by LoveNingBo** [PaddlePaddle/Paddle#36589]
Traceback (most recent call last):
  File "model.py", line 479, in <module>
    optimizer.step()
  File "<decorator-gen-198>", line 2, in step
  File "/mnt/huiyanfei/conda_env/hyf_py3/lib/python3.6/site-packages/paddle/fluid/dygraph/base.py", line 260, in __impl__
    return func(*args, **kwargs)
  File "<decorator-gen-196>", line 2, in step
  File "/mnt/huiyanfei/conda_env/hyf_py3/lib/python3.6/site-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
    return wrapped_func(*args, **kwargs)
  File "/mnt/huiyanfei/conda_env/hyf_py3/lib/python3.6/site-packages/paddle/fluid/framework.py", line 225, in __impl__
    return func(*args, **kwargs)
  File "/mnt/huiyanfei/conda_env/hyf_py3/lib/python3.6/site-packages/paddle/optimizer/adam.py", line 367, in step
    loss=None, startup_program=None, params_grads=params_grads)
  File "/mnt/huiyanfei/conda_env/hyf_py3/lib/python3.6/site-packages/paddle/optimizer/optimizer.py", line 774, in _apply_optimize
    self.regularization)
  File "/mnt/huiyanfei/conda_env/hyf_py3/lib/python3.6/site-packages/paddle/fluid/regularizer.py", line 90, in append_regularization_ops
    regularization)
  File "/mnt/huiyanfei/conda_env/hyf_py3/lib/python3.6/site-packages/paddle/fluid/regularizer.py", line 38, in _create_regularization_of_grad
    regularization_term = regularization(param, grad, grad.block)
TypeError: 'int' object is not callable

**Comment by LoveNingBo** [comment]
'''
    @Author: your name
    @Date: 2021-10-20 16:35:31
    @LastEditTime: 2021-10-20 20:04:39
    @LastEditors: Please set LastEditors
    @Description: In User Settings Edit
    @FilePath: /huiyanfei/work/re2_paddle_all/model.py
    '''
    import numpy
    from typing import Collection
    import math
    import paddle
    import paddle.nn as nn
    from paddle import fluid 
    import paddle.nn.functional as f
    from functools import partial 


    def register(name=None, registry=None):
        def decorator(fn, registration_name=None):
            module_name = registration_name or _default_name(fn)
            if module_name in registry:
                raise LookupError(f"module {module_name} already registered.")
            registry[module_name] = fn
            return fn
        return lambda fn: decorator(fn, name)


    def _default_name(obj_class):
        return obj_class.__name__

    registry = {}
    register = partial(register, registry=registry)


    class Module(paddle.nn.Layer):
        def __init__(self):
            super().__init__()
            self.summary = {}

        def add_summary(self, name, val):
            if self.training:
                self.summary[name] = val.clone().detach().cpu().numpy()

        def get_summary(self, base_name=''):
            summary = {}
            if base_name:
                base_name += '/'
            if self.summary:
                summary.update({base_name + name: val for name, val in self.summary.items()})
            for name, child in self.named_children():
                if hasattr(child, 'get_summary'):
                    name = base_name + name
                    summary.update(child.get_summary(name))
            return summary


    class GeLU(paddle.nn.Layer):
        def forward(self, x):
            return 0.5 * x * (1. + paddle.tanh(x * 0.7978845608 * (1. + 0.044715 * x * x)))


    class Linear(paddle.nn.Layer):
        def __init__(self, in_features, out_features, activations=False):
            super().__init__()
            weight_attr = paddle.framework.ParamAttr( 
                initializer=paddle.nn.initializer.Normal(mean=0.0, std=math.sqrt((2. if activations else 1.) / in_features)))
            bias_attr = paddle.framework.ParamAttr( 
                initializer=paddle.nn.initializer.Constant(value=0.0))
            linear = nn.Linear(in_features, out_features, weight_attr=weight_attr, bias_attr=bias_attr)
            # nn.init.normal_(linear.weight, std=math.sqrt((2. if activations else 1.) / in_features))
            # nn.init.zeros_(linear.bias)
            # linear.weight.normal_(0, math.sqrt((2. if activations else 1.) / in_features))
            # linear.bias.zero_()
            
            modules = [nn.utils.weight_norm(linear)]
            if activations:
                modules.append(GeLU())
            self.model = nn.Sequential(*modules)

        def forward(self, x):
            return self.model(x)

    class Conv1d(paddle.nn.Layer):
        def __init__(self, in_channels, out_channels, kernel_sizes: Collection[int]):
            super().__init__()
            assert all(k % 2 == 1 for k in kernel_sizes), 'only support odd kernel sizes'
            assert out_channels % len(kernel_sizes) == 0, 'out channels must be dividable by kernels'
            out_channels = out_channels // len(kernel_sizes)
            convs = []
            for kernel_size in kernel_sizes:
                conv = nn.Conv1D(in_channels, out_channels, kernel_size,
                                padding=(kernel_size - 1) // 2)
                # nn.init.normal_(conv.weight, std=math.sqrt(2. / (in_channels * kernel_size)))
                # nn.init.zeros_(conv.bias)
                # n = kernel_size * out_channels
                # conv.weight.set_value(numpy.array(math.sqrt(2. / n)))
                # conv.bias.set_value(0)
                convs.append(nn.Sequential(nn.utils.weight_norm(conv), GeLU()))
            self.model = convs

        def forward(self, x):
            return paddle.concat([encoder(x) for encoder in self.model], axis=-1)

    @register('identity')
    class Alignment(Module):
        def __init__(self, args, __):
            super().__init__()
            # self.temperature = nn.Parameter(paddle.tensor(1 / math.sqrt(args.hidden_size)))
            x = paddle.to_tensor(1 / math.sqrt(args.hidden_size))
            self.temperature = paddle.create_parameter(shape=x.shape,
                            dtype=str(x.numpy().dtype),
                            default_initializer=paddle.nn.initializer.Assign(x))
            
        def _attention(self, a, b):
            
            # return paddle.matmul(a, b.transpose(1, 2)) * self.temperature
            b = paddle.transpose(b, perm=[0, 2, 1])
            return paddle.matmul(a, b) * self.temperature
            
        def forward(self, a, b, mask_a, mask_b):
            attn = self._attention(a, b)
            
            # mask = paddle.matmul(mask_a.float(), mask_b.transpose(1, 2).float()).byte()
            mask_b = paddle.transpose(mask_b.astype("float32"), perm=[0, 2, 1])
            mask = paddle.matmul(mask_a.astype("float32"), mask_b)#.astype("bool")
            # attn.masked_fill_(~mask, -1e7)
            mask_ = paddle.full_like(mask, -1e7)
            attn = paddle.where(mask>0, attn, mask_)
            attn_a = f.softmax(attn, axis=1)
            attn_b = f.softmax(attn, axis=2)
            
            # feature_b = paddle.matmul(attn_a.transpose(1, 2), a)
            attn_a_trans = paddle.transpose(attn_a, perm=[0, 2, 1])
            feature_b = paddle.matmul(attn_a_trans, a)
            feature_a = paddle.matmul(attn_b, b)
            self.add_summary('temperature', self.temperature)
            self.add_summary('attention_a', attn_a)
            self.add_summary('attention_b', attn_b)
            return feature_a, feature_b


    # @register('linear')
    # class MappedAlignment(Alignment):
    #     def __init__(self, args, input_size):
    #         super().__init__(args, input_size)
    #         self.projection = nn.Sequential(
    #             nn.Dropout(args.dropout),
    #             Linear(input_size, args.hidden_size, activations=True),
    #         )

    #     def _attention(self, a, b):
    #         a = self.projection(a)
    #         b = self.projection(b)
    #         return super()._attention(a, b)

    @register('none')
    class NullConnection(paddle.nn.Layer):
        def forward(self, x, _, __):
            return x


    # @register('residual')
    # class Residual(paddle.nn.Layer):
    #     def __init__(self, args):
    #         super().__init__()
    #         self.linear = Linear(args.embedding_dim, args.hidden_size)

    #     def forward(self, x, res, i):
    #         if i == 1:
    #             res = self.linear(res)
    #         return (x + res) * math.sqrt(0.5)


    @register('aug')
    class AugmentedResidual(paddle.nn.Layer):
        def forward(self, x, res, i):
            if i == 1:
                return paddle.concat([x, res], axis=-1)  # res is embedding
            hidden_size = x.size(-1)
            x = (res[:, :, :hidden_size] + x) * math.sqrt(0.5)
            return paddle.concat([x, res[:, :, hidden_size:]], axis=-1)  # latter half of res is embedding



    class Embedding(paddle.nn.Layer):
        def __init__(self, args):
            super().__init__()
            self.fix_embeddings = args.fix_embeddings
            self.embedding = nn.Embedding(args.num_vocab, args.embedding_dim, padding_idx=0)
            self.dropout = args.dropout

        def set_(self, value):
            # self.embedding.weight.requires_grad = not self.fix_embeddings
            pretrained_attr = paddle.ParamAttr(name='embedding',
                                    initializer=paddle.nn.initializer.Assign(value),
                                    trainable=not self.fix_embeddings)
            self.embedding = paddle.nn.Embedding(num_embeddings=len(value),
                                        embedding_dim=300,
                                        padding_idx= 0 ,
                                        weight_attr=pretrained_attr)
            # self.embedding.load_state_dict({'weight': paddle.tensor(value)})

        def forward(self, x):
            x = self.embedding(x)
            x = f.dropout(x, self.dropout, self.training)
            return x

    class Encoder(paddle.nn.Layer):
        def __init__(self, args, input_size):
            super().__init__()
            self.dropout = args.dropout
            self.encoders = nn.LayerList([Conv1d(
                    in_channels=input_size if i == 0 else args.hidden_size,
                    out_channels=args.hidden_size,
                    kernel_sizes=args.kernel_sizes) for i in range(args.enc_layers)])

        def forward(self, x, mask):
            # x = x.transpose(1, 2)  # B x C x L
            x = paddle.transpose(x, perm=[0, 2, 1])
            # mask = mask.transpose(1, 2)
            mask = paddle.transpose(mask.astype("float32"), perm=[0, 2, 1])#.astype("bool")
            for i, encoder in enumerate(self.encoders):
                # x.masked_fill_(~mask, 0.)
                mask_ = paddle.full_like(mask, 0.)
                x = paddle.where(mask>0, x, mask_) 
                if i > 0:
                    x = f.dropout(x, self.dropout, self.training)
                x = encoder(x)
            x = f.dropout(x, self.dropout, self.training)
            # return x.transpose(1, 2)  # B x L x C
            return paddle.transpose(x, perm=[0, 2, 1])
    

    # @register('simple')
    # class Fusion(paddle.nn.Layer):
    #     def __init__(self, args, input_size):
    #         super().__init__()
    #         self.fusion = Linear(input_size * 2, args.hidden_size, activations=True)

    #     def forward(self, x, align):
    #         return self.fusion(paddle.concat([x, align], axis=-1))


    @register('full_fusion')
    class FullFusion(paddle.nn.Layer):
        def __init__(self, args, input_size):
            super().__init__()
            self.dropout = args.dropout
            self.fusion1 = Linear(input_size * 2, args.hidden_size, activations=True)
            self.fusion2 = Linear(input_size * 2, args.hidden_size, activations=True)
            self.fusion3 = Linear(input_size * 2, args.hidden_size, activations=True)
            self.fusion = Linear(args.hidden_size * 3, args.hidden_size, activations=True)

        def forward(self, x, align):
            x1 = self.fusion1(paddle.concat([x, align], axis=-1))
            x2 = self.fusion2(paddle.concat([x, x - align], axis=-1))
            x3 = self.fusion3(paddle.concat([x, x * align], axis=-1))
            x = paddle.concat([x1, x2, x3], axis=-1)
            x = f.dropout(x, self.dropout, self.training)
            return self.fusion(x)

    class Pooling(paddle.nn.Layer):
        def forward(self, x, mask):
            # print(x.shape,mask.shape)
            # return x.masked_fill_(~mask, -float('inf')).max(dim=1)[0]
            mask = mask.astype("float32")
            # mask_ = paddle.full_like(x, 0.0)
            # mask_ += float('-inf')
            # return paddle.where(mask>0, x, mask_).max(axis=1)[0]
            out = paddle.max(paddle.where(mask == 0, paddle.to_tensor(0.), x),axis=1)
            # print(out.shape)
            return out#[0]
        

    @register('simple')
    class Prediction(paddle.nn.Layer):
        def __init__(self, args, inp_features=2):
            super().__init__()
            self.dense = nn.Sequential(
                nn.Dropout(args.dropout),
                Linear(args.hidden_size * inp_features, args.hidden_size, activations=True),
                nn.Dropout(args.dropout),
                Linear(args.hidden_size, args.num_classes),
            )

        def forward(self, a, b):
            return self.dense(paddle.concat([a, b], axis=-1))


    @register('full')
    class AdvancedPrediction(Prediction):
        def __init__(self, args):
            super().__init__(args, inp_features=4)

        def forward(self, a, b):
            return self.dense(paddle.concat([a, b, a - b, a * b], axis=-1))


    ################################## 模型主网络 #################################

    class Network(Module):
        def __init__(self, args):
            super().__init__()
            # self.dropout = args.dropout
            self.embedding = Embedding(args)
            # self.blocks = [,
            # ) for i in range(args.blocks)]
            self.blocks = []
            for i in range(args.blocks):
                block = nn.Sequential(("encoder",Encoder(args, args.embedding_dim if i == 0 else args.embedding_dim + args.hidden_size)),
                ("alignment",Alignment(args, args.embedding_dim + args.hidden_size if i == 0 else args.embedding_dim + args.hidden_size * 2)),
                ("fusion",FullFusion(args, args.embedding_dim + args.hidden_size if i == 0 else args.embedding_dim + args.hidden_size * 2)))
                self.blocks.append(block)

            self.connection = AugmentedResidual()
            self.pooling = Pooling()
            self.prediction = AdvancedPrediction(args)

        # def forward(self, inputs):
            # a = inputs['text1']
            # b = inputs['text2']
            # mask_a = inputs['mask1']
            # mask_b = inputs['mask2']
        def forward(self, a,b,mask_a,mask_b):
            # print(type(a),type(b))
            a = self.embedding(a)
            b = self.embedding(b)
            # print(type(a),type(b))
            res_a, res_b = a, b

            for i, block in enumerate(self.blocks):
                if i > 0:
                    a = self.connection(a, res_a, i)
                    b = self.connection(b, res_b, i)
                    res_a, res_b = a, b 
                a_enc = block["encoder"](a, mask_a)
                b_enc = block["encoder"](b, mask_b)
                a = paddle.concat([a, a_enc], axis=-1)
                b = paddle.concat([b, b_enc], axis=-1)
                align_a, align_b = block["alignment"](a, b, mask_a, mask_b)
                a = block["fusion"](a, align_a)
                b = block["fusion"](b, align_b)
                # a,b = block(a,b,mask_a,mask_b)
                print(type(a),type(b))
            # a,b = self.blocks[0](a,b,mask_a,mask_b)
            a = self.pooling(a, mask_a)
            b = self.pooling(b, mask_b)
            print(type(a),type(b))
            return self.prediction(a, b)

    ############################## 损失函数 ##########################

    def get_loss(logits, target, soft_target):
        softlabel = False
        def SoftCrossEntropy(inputs, target,soft_target,reduction='sum'):  
            if reduction == 'average': 
                log_likelihood = inputs[:,1] 
                loss = paddle.sum(paddle.mul(log_likelihood, target)) / batch
            else:
                # log_likelihood = inputs[:,1]   
                soft_loss =  5 * paddle.nn.functional.mse_loss(inputs, soft_target)
                # target = paddle.tensor(target, dtype=paddle.long).to(DEVICE)
                hard_loss =  f.cross_entropy(logits, target)
            return hard_loss + soft_loss 
        if softlabel: 
            return SoftCrossEntropy(logits,target,soft_target)
        else: 
            return f.cross_entropy(logits, target)




    ##############################################   训练   ##########################
    args_dict = {'alignment': 'identity',
    'batch_size': 512,
    'beta1': 0.9,
    'beta2': 0.999,
    'blocks': 2,
    'connection': 'aug',
    'cuda': True,
    'data_dir': 'data/ddqa',
    'deterministic': True,
    'dropout': 0.2,
    'early_stopping': 1954,
    'embedding_dim': 300,
    'embedding_mode': 'freq',
    'enc_layers': 2,
    'encoder': 'cnn',
    'epochs': 30,
    'eval_epoch': True,
    'eval_file': 'dev',
    'eval_per_samples': 64000,
    'eval_per_samples_warmup': 40000,
    'eval_per_updates': 125,
    'eval_per_updates_warmup': 79,
    'eval_subset': None,
    'eval_warmup_samples': 0,
    'eval_warmup_steps': 0,
    'fix_embeddings': False,
    'fusion': 'full_fusion',
    'grad_clipping': 5,
    'hidden_size': 150,
    'kernel_sizes': [3],
    'log_file': 'log.txt',
    'log_per_samples': 32000,
    'log_per_updates': 63,
    'lower_case': True,
    'lr': 0.001,
    'lr_decay_rate': 1.0,
    'lr_decay_samples': 128000,
    'lr_decay_steps': 250,
    'lr_warmup_samples': 0,
    'lr_warmup_steps': 0,
    'max_len': 150,
    'max_loss': 999.0,
    'max_vocab': 999999,
    'metric': 'acc',
    'min_df': 5,
    'min_len': 1,
    'min_lr': 6e-05,
    'min_samples': 0,
    'min_steps': 0,
    'multi_gpu': False,
    'name': 'benchmark-0',
    'num_classes': 2,
    'num_vocab': 248827,
    'output_dir': 'models/ddqa_合并训练集_softlabel',
    'padding': 0,
    'prediction': 'full',
    'pretrained_embeddings': 'resources/sgns.target.word-character.char1-2.dynwin5.thr10.neg5.dim300.iter5',
    'resume': None,
    'save': True,
    'save_all': False,
    'seed': None,
    'sort_by_len': False,
    'summary_dir': 'models/ddqa_合并训练集_softlabel/benchmark-0',
    'summary_per_logs': 20,
    'summary_per_updates': 1260,
    'tensorboard': True,
    'tolerance_samples': 1000000,
    'watch_metrics': ['acc'],
    'weight_decay': 0
    }

    Args = type("Args",(),{})
    for  key,value in args_dict.items():
        setattr(Args,key,value)
    args = Args()
    model = Network(args)

    optimizer = paddle.optimizer.Adam(parameters = model.parameters(), learning_rate=args.lr, beta1=args.beta1,beta2= args.beta2,
                                        weight_decay=args.weight_decay)

    a= [[9414,   13,  156,  366, 2977, 3838]]

    b= [[    56,  63748,  27627,     54,      5,     49,   9831,      7,   7445,
                7,   5487,   1223,    734,   4722,     96,   8174,    644,   2977,
                283,      2,   4115,      3,      1,   3996, 230505,   9320,      7,
            3885,     13,   2393,     28,   1551,    562,    242,   1659,    823,
                27,      7,  83798,     45, 170219,     28,    196,  14642,   9944,
            3399,  69074,     27,      7,  29841,     31,   3909,   2393,     28,
            1551,      1,     10,    100,     93,      1,     29,    423,      7,
                45,   7060,   2977,    595,    205,      2,    783,   2619,      4]]

    mask_a = [[[1]]*len(a[0])]
    mask_b = [[[1]]*len(b[0])]

    a_t = paddle.to_tensor(a)
    mask_a_t = paddle.to_tensor(mask_a)
    b_t = paddle.to_tensor(b)
    mask_b_t = paddle.to_tensor(mask_b)

    output = model(a_t,b_t,mask_a_t,mask_b_t)
    target = paddle.to_tensor([1],dtype="int64")
    soft_target = paddle.to_tensor([0.84127417])
    loss =  get_loss(output, target, soft_target)
    loss.backward()
    optimizer.step()

**Comment by LoveNingBo** [comment]
这个代码是根据 torch 版本阿里RE2模型进行的复现，源代码地址：https://github.com/alibaba-edu/simple-effective-text-matching-pytorch

**Comment by WenmuZhou** [comment]
你好，优化器的weight_decay需要传float进去，改成这样就好了
```python
optimizer = paddle.optimizer.Adam(parameters=model.parameters(), learning_rate=args.lr, beta1=args.beta1,
                                  beta2=args.beta2,
                                  weight_decay=float(args.weight_decay))
```

**Comment by LoveNingBo** [comment]
十分感谢！问题已解决
