### ISSUE TITLE
复现 优化器接口问题

### ISSUE THREAD

**Issue by ethelgriffin** [PaddlePaddle/Paddle#36585]
import paddle.optimizer as optim
optimizer = optim.Adadelta(learning_rate=args.learning_rate,epsilon=1e-8,rho=0.95,parameters=net.parameters(), weight_decay=5e-4)

报错
AttributeError: 'Namespace' object has no attribute 'learning_rate'

pytorch代码
optimizer = optim.Adadelta(net.parameters(), lr=args.lr, rho=0.95, eps=1e-8, weight_decay=5e-4)

请问要怎样修改呀，谢谢

**Comment by WenmuZhou** [comment]
传入的参数改为和torch一致看看，下面这样optim.Adadelta(learning_rate=args.lr,epsilon=1e-8,rho=0.95,parameters=net.parameters(), weight_decay=5e-4)
