### ISSUE TITLE
crf_decoding不支持返回预测的概率

### ISSUE THREAD

**Issue by Cppowboy** [PaddlePaddle/Paddle#36586]
目前paddle.nn.static.crf_decoding只返回CRF的预测结果，不支持返回对应的概率，希望支持一下这个功能

**Comment by WenmuZhou** [comment]
您好，您的反馈对产品非常有价值，我们内部会安排评估，未来有计划尽快回复。

**Comment by WenmuZhou** [comment]
你好，crf_decoding 的概率支持在这个pr里已经支持了哈，会在2.2正式版里支持，目前可以先试一下最新的dev版本PaddlePaddle，https://github.com/PaddlePaddle/Paddle/pull/35778
