### ISSUE TITLE
paddle.distributed.launch 是可以中途增加资源？？？

### ISSUE THREAD

**Issue by Ramlinbird** [PaddlePaddle/Paddle#36597]
您好！我用```python -m paddle.distributed.launch --gpus "0"  xxx.py```启动了一个训练任务，后来修改了某些东西，然后执行命令```python -m paddle.distributed.launch --gpus "1"  xxx.py```，发现好像任务很快就run起来，而且损失是和先前0卡上正在执行的任务一致的？不太清楚paddle.distributed.launch的执行原理，我是再单击多卡上执行的，这个是自动和先前的训练一起进行训练吗？

**Comment by wenming2014** [comment]
您好，卡的配置和更换对loss和训练的结果不会有影响的，可以在原来的基础上继续训练。分布式的原理都是类似的
