### ISSUE TITLE
按照paddleseg官方文档下的剪枝说明，对自己训练的bisenetV2模型进行了剪枝和重新训练重新训练后的模型部署用c++部署在jetsonnx上时便报错

### ISSUE THREAD

**Issue by huangwan-jiayi** [PaddlePaddle/Paddle#36603]
c++ inference库信息：
![image](https://user-images.githubusercontent.com/71338215/138222016-80d41236-31d8-424c-90fb-1131b41601a5.png)
jetson nx环境信息：
![image](https://user-images.githubusercontent.com/71338215/138224272-cbb4a060-0399-4d5b-ae31-eeceae954890.png)

预测全部代码：

// #include <algorithm>
#include <chrono>
#include <iostream>
#include <fstream>
#include <numeric>
#include <time.h>
#include <gflags/gflags.h>
#include <glog/logging.h>
#include <opencv2/opencv.hpp>
#include <opencv2/core/core.hpp>
#include <opencv2/highgui/highgui.hpp>
#include <opencv2/imgproc/imgproc.hpp>

#include "paddle/include/paddle_inference_api.h"
#include "yaml-cpp/yaml.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <errno.h>

using namespace std;
using namespace cv;

DEFINE_string(model_dir, "/home/nvidia/Paddle-Inference-Demo/c++/bisenetV2-debug", "Directory of the inference model. "
"It constains deploy.yaml and infer models");
DEFINE_string(img_path, "/home/nvidia/Paddle-Inference-Demo/c++/bisenetV2/img251.png", "Path of the test image.");
DEFINE_bool(use_cpu, false, "Wether use CPU. Default: use GPU.");
DEFINE_bool(use_trt, false, "Wether enable TensorRT when use GPU. Defualt: false.");
DEFINE_bool(use_mkldnn, false, "Wether enable MKLDNN when use CPU. Defualt: false.");
DEFINE_string(save_dir, "", "Directory of the output image.");

using Time =decltype(std::chrono::high_resolution_clock::now());
Time time() {return std::chrono::high_resolution_clock::now();};
double time_diff(Time t1,Time t2){
  typedef std::chrono::microseconds ms;
  auto diff = t2-t1;
  ms counter = std::chrono::duration_cast<ms>(diff);
  return counter.count();
}

typedef struct YamlConfig {
  std::string model_file;
  std::string params_file;
  bool is_normalize;
}YamlConfig;

YamlConfig load_yaml(const std::string& yaml_path) {
  YAML::Node node = YAML::LoadFile(yaml_path);
  std::string model_file = node["Deploy"]["model"].as<std::string>();
  std::string params_file = node["Deploy"]["params"].as<std::string>();
  bool is_normalize = false;
  if (node["Deploy"]["transforms"] &&
    node["Deploy"]["transforms"][0]["type"].as<std::string>() == "Normalize") {
      is_normalize = true;
  }

  YamlConfig yaml_config = {model_file, params_file, is_normalize};
  return yaml_config;
}

std::shared_ptr<paddle_infer::Predictor> create_predictor(const YamlConfig& yaml_config) {
  std::string& model_dir = FLAGS_model_dir;

  paddle_infer::Config infer_config;
  infer_config.SetModel(model_dir + "/" + yaml_config.model_file,
                  model_dir + "/" + yaml_config.params_file);
  infer_config.EnableMemoryOptim();
  infer_config.EnableProfile();
  std::cout << "Profile is: " << infer_config.profile_enabled() << std::endl;

  if (FLAGS_use_cpu) {
    LOG(INFO) << "Use CPU";
    if (FLAGS_use_mkldnn) {
      // TODO(jc): fix the bug
      //infer_config.EnableMKLDNN();
      infer_config.SetCpuMathLibraryNumThreads(5);
    }
  } else {
    LOG(INFO) << "Use GPU";
    infer_config.EnableUseGpu(1000,0);
    if (FLAGS_use_trt) {
      infer_config.EnableTensorRtEngine(1 << 30, 1, 1,
        paddle_infer::PrecisionType::kInt8, false,false);
    }
  }

  auto predictor = paddle_infer::CreatePredictor(infer_config);
  return predictor;
}

void hwc_img_2_chw_data(const cv::Mat& hwc_img, float* data) {
  int rows = hwc_img.rows;
  int cols = hwc_img.cols;
  int chs = hwc_img.channels();
  for (int i = 0; i < chs; ++i) {
    cv::extractChannel(hwc_img, cv::Mat(rows, cols, CV_32FC1, data + i * rows * cols), i);
  }
}

cv::Mat read_process_image(bool is_normalize) {
  cv::Mat img = cv::imread(FLAGS_img_path, cv::IMREAD_COLOR);
  cv::cvtColor(img, img, cv::COLOR_BGR2RGB);
  if (is_normalize) {
    img.convertTo(img, CV_32F, 1.0 / 255, 0);
    img = (img - 0.5) / 0.5;
  }
  return img;
}

Mat convertTo3Channels(const Mat& binImg)
{
    Mat three_channel = Mat::zeros(binImg.rows,binImg.cols,CV_8UC3);
    vector<Mat> channels;
    for (int i=0;i<3;i++)
    {
        channels.push_back(binImg);
    }
    merge(channels,three_channel);
    return three_channel;
}

int main(int argc, char *argv[]) {
  google::ParseCommandLineFlags(&argc, &argv, true);
  if (FLAGS_model_dir == "") {
    LOG(FATAL) << "The model_dir should not be empty.";
  }
  
  // init color table
  Mat table(1, 256, CV_8UC3);
  for (int i = 0; i < 256; i++) {
      //img.at<cv::Vec3b>(row,col) 对各个通道的灰度映射如下
      if (i == 2) // warnning
      {
          table.at<cv::Vec3b>(0, i)[2] = 0; // red
          table.at<cv::Vec3b>(0,i)[1] =  255; // green
          table.at<cv::Vec3b>(0, i)[0] = 0; // blue
      } else if (i == 1)//railway
      {   
          table.at<cv::Vec3b>(0, i)[2] = 255;//red
          table.at<cv::Vec3b>(0,i)[1] =  0;//green
          table.at<cv::Vec3b>(0, i)[0] = 0;//blue
      } else {
          table.at<cv::Vec3b>(0, i)[2] = 0;
          table.at<cv::Vec3b>(0,i)[1] =  0;
          table.at<cv::Vec3b>(0, i)[0] = 0;
      }
  }

  int cntFrame = 0;
  std::string outFile;

  // Load yaml
  std::string yaml_path = FLAGS_model_dir + "/deploy.yaml";
  YamlConfig yaml_config = load_yaml(yaml_path);

  // Create predictor
  auto predictor = create_predictor(yaml_config);

  // 打开视频
  cv::VideoCapture capture;
  capture.open("/home/nvidia/Paddle-Inference-Demo/c++/bisenetV2-debug/5.mp4");
  if (!capture.isOpened())  
  {  
    std::cout << "Read video Failed !" << std::endl;  
    return -1;  
  }  
  long totalFrameNumber = capture.get(CV_CAP_PROP_FRAME_COUNT);
  std::cout << totalFrameNumber << endl;

  //namedWindow("input video",CV_WINDOW_AUTOSIZE);
  //vector<cv::Mat> result;
  VideoWriter writer("/home/nvidia/Paddle-Inference-Demo/c++/bisenetV2-debug/test.avi",CV_FOURCC('D','I','V','X'),30.02,Size(480,270),true);
  int num = 0;
  while(true)
  {
    cv::Mat img;
    capture.read(img);
  Mat src;
  img.copyTo(src);
    // Prepare data
    // cv::Mat img = read_process_image(yaml_config.is_normalize);
    cv::cvtColor(img, img, cv::COLOR_BGR2RGB);
    if (yaml_config.is_normalize) {
      img.convertTo(img, CV_32F, 1.0 / 255, 0);
      img = (img - 0.5) / 0.5;
    }

    int rows = img.rows;
    int cols = img.cols;
    int chs = img.channels();
    std::vector<float> input_data(1 * 3 * 270 *480, 0.0f);
    hwc_img_2_chw_data(img, input_data.data());

    // Set input
    auto input_names = predictor->GetInputNames();
    auto input_t = predictor->GetInputHandle(input_names[0]);
    std::vector<int> input_shape = {1, 3, 270, 480};
    input_t->Reshape(input_shape);
    input_t->CopyFromCpu(input_data.data()); //+++++

    // Run
   
      auto time1 = time();
      predictor->Run();
      auto time2 = time();
      double latency = time_diff(time1,time2)/1000;
      cout <<"the run time is:"<<latency<<"ms"<<std::endl;

    // Get output
    auto output_names = predictor->GetOutputNames();
    auto output_t = predictor->GetOutputHandle(output_names[0]);
    std::vector<int> output_shape = output_t->shape();  // n * h * w
    int out_num = std::accumulate(output_shape.begin(), output_shape.end(), 1,
                                  std::multiplies<int>());
    std::vector<int64_t> out_data(out_num);
    output_t->CopyToCpu(out_data.data());

    // Get pseudo image
    std::vector<uint8_t> out_data_u8(out_num);
    for (int i = 0; i < out_num; i++) {
      out_data_u8[i] = static_cast<uint8_t>(out_data[i]);
    }
   // double fps = capture.get(CV_CAP_PROP_FPS);
    //printf("FPS : %f",fps);

    cv::Mat out_gray_img(output_shape[1], output_shape[2], CV_8UC1, out_data_u8.data());
    //为了确定对应位置的像素
    // int hist[256];
    // for (int i = 0; i < 256; i++) {
    //     hist[i] = 0;
    // }
    // for (int j = 0; j < 480; j++)
    //   for (int k = 0; k < 270; k++)
    //       hist[(int)(out_gray_img.at<uchar>(k,j))] += 1;

    // cv::Mat out_eq_img;
    // cv::equalizeHist(out_gray_img, out_eq_img);
    
    cv::Mat im_color = convertTo3Channels(out_gray_img);
    cv::Mat img_add;
    LUT(im_color, table, im_color);
  //  cv::applyColorMap(out, im_color, COLORMAP_HOT);
    // imwrite("src.png",src);
    // imwrite("out.png",out);
    cv::addWeighted(im_color,0.3,src,0.7,0,img_add);
    // imwrite("img_add.png",img_add);

    writer.write(img_add);
    //imshow("input video",out_eq_img);
    num++;
    if(num==totalFrameNumber) break;
    cntFrame += 1;

    //writer.write(out_gray_img);
    //cv::waitKey(1000);
  }
  
  capture.release();
  LOG(INFO) << "Finish";
  return 0;
}
报错：
![JGDF(H(VXKWX7EFJ$ 49`ZE](https://user-images.githubusercontent.com/71338215/138223382-af79af39-2d43-4bbd-bb7d-0a639726389e.jpg)

模型文件：

[model20211021.zip](https://github.com/PaddlePaddle/Paddle/files/7386525/model20211021.zip)

推理所用视频文件：

https://user-images.githubusercontent.com/71338215/138223790-adfd42ba-adf1-473c-939c-b01395ca4317.mp4

**Comment by wenming2014** [comment]
您好，看着报类型问题，建议再check下

**Comment by huangwan-jiayi** [comment]
> 您好，看着报类型问题，建议再check下

您好，可以说得详细一点吗？我的推理程序可以推理未做剪枝的模型，剪枝后重训练的模型，为什么会报类型问题呢？

**Comment by wenming2014** [comment]
> > 您好，看着报类型问题，建议再check下
> 
> 您好，可以说得详细一点吗？我的推理程序可以推理未做剪枝的模型，剪枝后重训练的模型，为什么会报类型问题呢？

您好，看着是opencv报错了，应该不是推理的问题，建议再check下哪里用的不对或者改变了类型

**Comment by juncaipeng** [comment]
和下面issue重复，关闭该issue。
https://github.com/PaddlePaddle/PaddleSeg/issues/1460
