### ISSUE TITLE
Paddle分支源代码编译问题_cmake出core make提示o rule to make target `../third_party/install/glog/lib/libglog.a', needed by `paddle/function/MulOpTest'

### ISSUE THREAD

**Issue by xieshufu** [PaddlePaddle/Paddle#3662]
从某个分支上将PADDLE代码下载下来， https://github.com/zzsu/Paddle， 
然后执行cmake命令cmake .. -DCMAKE_INSTALL_PREFIX=../../../test_exe/ ，提示如下： 
-- The CXX compiler identification is GNU 4.8.3
-- The C compiler identification is GNU 4.8.3
-- Check for working CXX compiler: /home/vis/.jumbo/opt/gcc48/bin/g++
-- Check for working CXX compiler: /home/vis/.jumbo/opt/gcc48/bin/g++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Check for working C compiler: /home/vis/.jumbo/opt/gcc48/bin/gcc
-- Check for working C compiler: /home/vis/.jumbo/opt/gcc48/bin/gcc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Found Sphinx: /home/vis/.jumbo/bin/sphinx-build  
-- Found Git: /usr/bin/git (found version "1.7.1") 
-- Looking for include file pthread.h
-- Looking for include file pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Found Paddle host system: centos
-- Found Paddle host system's CPU: 12 cores
-- Performing Test MMX_FOUND
-- Performing Test MMX_FOUND - Success
-- Performing Test SSE2_FOUND
-- Performing Test SSE2_FOUND - Success
-- Performing Test SSE3_FOUND
-- Performing Test SSE3_FOUND - Success
-- Performing Test AVX_FOUND
-- Performing Test AVX_FOUND - Success
-- Performing Test AVX2_FOUND
-- Performing Test AVX2_FOUND - Failed
-- Found PythonInterp: /home/vis/.jumbo/bin/python2.7 (found suitable version "2.7.3", minimum required is "2.7") 
-- Found PythonLibs: /home/vis/.jumbo/lib/libpython2.7.so (found suitable version "2.7.3", minimum required is "2.7") 
-- Found PY_pip: /home/vis/.jumbo/lib/python2.7/site-packages/pip  
-- Found PY_numpy: /home/vis/.jumbo/lib/python2.7/site-packages/numpy  
-- Found PY_wheel: /home/vis/.jumbo/lib/python2.7/site-packages/wheel  
-- Found PY_google.protobuf: /home/vis/.jumbo/lib/python2.7/site-packages/google/protobuf  
-- Found NumPy: /home/vis/.jumbo/lib/python2.7/site-packages/numpy/core/include  
[Paddle] Python Executable: /home/vis/.jumbo/bin/python2.7
[Paddle] Python Include: /home/vis/.jumbo/include/python2.7
[Paddle] Python Libraries: /home/vis/.jumbo/lib/libpython2.7.so
-- Found MKL (include: /home/vis/mkl/include, library: /home/vis/mkl/lib/libmkl_intel_lp64.a;/home/vis/mkl/lib/libmkl_sequential.a;/home/vis/mkl/lib/libmkl_core.a)
-- Found SWIG: /home/vis/.jumbo/bin/swig (found version "3.0.0") 
-- Looking for UINT64_MAX
-- Looking for UINT64_MAX - found
-- Performing Test C_COMPILER_SUPPORT_FLAG__fPIC
-- Performing Test C_COMPILER_SUPPORT_FLAG__fPIC - Success
-- Performing Test CXX_COMPILER_SUPPORT_FLAG__fPIC
-- Performing Test CXX_COMPILER_SUPPORT_FLAG__fPIC - Success
-- Performing Test C_COMPILER_SUPPORT_FLAG__fno_omit_frame_pointer
-- Performing Test C_COMPILER_SUPPORT_FLAG__fno_omit_frame_pointer - Success
-- Performing Test CXX_COMPILER_SUPPORT_FLAG__fno_omit_frame_pointer
-- Performing Test CXX_COMPILER_SUPPORT_FLAG__fno_omit_frame_pointer - Success
-- Performing Test C_COMPILER_SUPPORT_FLAG__Wall
-- Performing Test C_COMPILER_SUPPORT_FLAG__Wall - Success
-- Performing Test CXX_COMPILER_SUPPORT_FLAG__Wall
-- Performing Test CXX_COMPILER_SUPPORT_FLAG__Wall - Success
-- Performing Test C_COMPILER_SUPPORT_FLAG__Wextra
-- Performing Test C_COMPILER_SUPPORT_FLAG__Wextra - Success
-- Performing Test CXX_COMPILER_SUPPORT_FLAG__Wextra
-- Performing Test CXX_COMPILER_SUPPORT_FLAG__Wextra - Success
-- Performing Test C_COMPILER_SUPPORT_FLAG__Werror
-- Performing Test C_COMPILER_SUPPORT_FLAG__Werror - Success
-- Performing Test CXX_COMPILER_SUPPORT_FLAG__Werror
-- Performing Test CXX_COMPILER_SUPPORT_FLAG__Werror - Success
-- Performing Test C_COMPILER_SUPPORT_FLAG__Wnon_virtual_dtor
-- Performing Test C_COMPILER_SUPPORT_FLAG__Wnon_virtual_dtor - Failed
-- Performing Test CXX_COMPILER_SUPPORT_FLAG__Wnon_virtual_dtor
-- Performing Test CXX_COMPILER_SUPPORT_FLAG__Wnon_virtual_dtor - Success
-- Performing Test C_COMPILER_SUPPORT_FLAG__Wdelete_non_virtual_dtor
-- Performing Test C_COMPILER_SUPPORT_FLAG__Wdelete_non_virtual_dtor - Failed
-- Performing Test CXX_COMPILER_SUPPORT_FLAG__Wdelete_non_virtual_dtor
-- Performing Test CXX_COMPILER_SUPPORT_FLAG__Wdelete_non_virtual_dtor - Success
-- Performing Test C_COMPILER_SUPPORT_FLAG__Wno_unused_parameter
-- Performing Test C_COMPILER_SUPPORT_FLAG__Wno_unused_parameter - Success
-- Performing Test CXX_COMPILER_SUPPORT_FLAG__Wno_unused_parameter
-- Performing Test CXX_COMPILER_SUPPORT_FLAG__Wno_unused_parameter - Success
-- Performing Test C_COMPILER_SUPPORT_FLAG__Wno_unused_function
-- Performing Test C_COMPILER_SUPPORT_FLAG__Wno_unused_function - Success
-- Performing Test CXX_COMPILER_SUPPORT_FLAG__Wno_unused_function
-- Performing Test CXX_COMPILER_SUPPORT_FLAG__Wno_unused_function - Success
-- Performing Test C_COMPILER_SUPPORT_FLAG__Wno_error_literal_suffix
-- Performing Test C_COMPILER_SUPPORT_FLAG__Wno_error_literal_suffix - Success
-- Performing Test CXX_COMPILER_SUPPORT_FLAG__Wno_error_literal_suffix
-- Performing Test CXX_COMPILER_SUPPORT_FLAG__Wno_error_literal_suffix - Success
-- Performing Test C_COMPILER_SUPPORT_FLAG__Wno_error_sign_compare
-- Performing Test C_COMPILER_SUPPORT_FLAG__Wno_error_sign_compare - Success
-- Performing Test CXX_COMPILER_SUPPORT_FLAG__Wno_error_sign_compare
-- Performing Test CXX_COMPILER_SUPPORT_FLAG__Wno_error_sign_compare - Success
-- Performing Test C_COMPILER_SUPPORT_FLAG__Wno_error_unused_local_typedefs
-- Performing Test C_COMPILER_SUPPORT_FLAG__Wno_error_unused_local_typedefs - Success
-- Performing Test CXX_COMPILER_SUPPORT_FLAG__Wno_error_unused_local_typedefs
-- Performing Test CXX_COMPILER_SUPPORT_FLAG__Wno_error_unused_local_typedefs - Success
-- Performing Test C_COMPILER_SUPPORT_FLAG__Wno_error_unused_function
-- Performing Test C_COMPILER_SUPPORT_FLAG__Wno_error_unused_function - Success
-- Current cuDNN header is /home/work/cudnn/cudnn_v5/cuda/include/cudnn.h. Current cuDNN version is v5. 
-- Paddle version is 0.9.0a0
-- Found CUDA: /home/work/cuda-7.5 (found version "7.5") 
-- Looking for clock_gettime in rt
-- Looking for clock_gettime in rt - found
-- Configuring done
-- Generating done
-- Build files have been written to: /home/vis/xieshufu/paddle/ocr/PaddleSRC/Paddle/build
从信息上看感觉是正常的，但在目录下会有一个core文件：core.31531
然后执行make -j 12命令，编译完成的提示如下：
make[2]: *** No rule to make target `../third_party/install/glog/lib/libglog.a', needed by `paddle/utils/tests/test_Error'.  Stop.
make[2]: *** Waiting for unfinished jobs....
[ 81%] Building CXX object paddle/utils/tests/CMakeFiles/test_Error.dir/test_Error.cpp.o
make[2]: *** No rule to make target `../third_party/install/glog/lib/libglog.a', needed by `paddle/function/TensorShapeTest'.  Stop.
make[2]: *** Waiting for unfinished jobs....
[ 82%] Building CXX object paddle/function/CMakeFiles/TensorShapeTest.dir/TensorShapeTest.cpp.o
make[2]: *** No rule to make target `../third_party/install/glog/lib/libglog.a', needed by `paddle/utils/tests/test_CustomStackTracePrint'.  Stop.
make[2]: *** Waiting for unfinished jobs....
[ 82%] Building CXX object paddle/utils/tests/CMakeFiles/test_CustomStackTracePrint.dir/test_CustomStackTracePrint.cpp.o
make[2]: *** No rule to make target `../third_party/install/glog/lib/libglog.a', needed by `paddle/utils/tests/test_CustomStackTrace'.  Stop.
make[2]: *** Waiting for unfinished jobs....
make[2]: *** No rule to make target `../third_party/install/glog/lib/libglog.a', needed by `paddle/function/CrossMapNormalOpTest'.  Stop.
make[2]: *** Waiting for unfinished jobs....
make[2]: *** No rule to make target `../third_party/install/glog/lib/libglog.a', needed by `paddle/function/PadOpTest'.  Stop.
make[2]: *** Waiting for unfinished jobs....
[ 82%] [ 83%] [ 83%] make[2]: *** No rule to make target `../third_party/install/glog/lib/libglog.a', needed by `paddle/function/BufferArgTest'.  Stop.
make[2]: *** Waiting for unfinished jobs....
Building CXX object paddle/utils/tests/CMakeFiles/test_CustomStackTrace.dir/test_CustomStackTrace.cpp.o
[ 83%] Building CXX object paddle/function/CMakeFiles/CrossMapNormalOpTest.dir/CrossMapNormalOpTest.cpp.o
Building CXX object paddle/function/CMakeFiles/PadOpTest.dir/PadOpTest.cpp.o
Building CXX object paddle/function/CMakeFiles/BufferArgTest.dir/BufferArgTest.cpp.o
make[2]: *** No rule to make target `../third_party/install/glog/lib/libglog.a', needed by `paddle/function/CosSimOpTest'.  Stop.
make[2]: *** Waiting for unfinished jobs....
[ 83%] make[2]: *** No rule to make target `../third_party/install/glog/lib/libglog.a', needed by `paddle/function/FunctionTest'.  Stop.
make[2]: *** Waiting for unfinished jobs....
make[2]: *** No rule to make target `../third_party/install/glog/lib/libglog.a', needed by `paddle/function/TensorTypeTest'.  Stop.
make[2]: *** Waiting for unfinished jobs....
[ 83%] [ 83%] Building CXX object paddle/function/CMakeFiles/FunctionTest.dir/FunctionTest.cpp.o
Building CXX object paddle/function/CMakeFiles/TensorTypeTest.dir/TensorTypeTest.cpp.o
Building CXX object paddle/function/CMakeFiles/CosSimOpTest.dir/CosSimOpTest.cpp.o
make[2]: *** No rule to make target `../third_party/install/glog/lib/libglog.a', needed by `paddle/function/MulOpTest'.  Stop.
make[2]: *** Waiting for unfinished jobs....
[ 83%] Building CXX object paddle/function/CMakeFiles/MulOpTest.dir/MulOpTest.cpp.o
make[2]: *** No rule to make target `../third_party/install/glog/lib/libglog.a', needed by `paddle/function/ContextProjectionOpTest'.  Stop.
make[2]: *** Waiting for unfinished jobs....
[ 83%] Building CXX object paddle/function/CMakeFiles/ContextProjectionOpTest.dir/ContextProjectionOpTest.cpp.o
make[1]: *** [paddle/utils/tests/CMakeFiles/test_Error.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
make[1]: *** [paddle/function/CMakeFiles/TensorShapeTest.dir/all] Error 2
make[1]: *** [paddle/utils/tests/CMakeFiles/test_CustomStackTracePrint.dir/all] Error 2
make[1]: *** [paddle/function/CMakeFiles/BufferArgTest.dir/all] Error 2
make[1]: *** [paddle/utils/tests/CMakeFiles/test_CustomStackTrace.dir/all] Error 2
make[1]: *** [paddle/function/CMakeFiles/TensorTypeTest.dir/all] Error 2
make[1]: *** [paddle/function/CMakeFiles/PadOpTest.dir/all] Error 2
make[1]: *** [paddle/function/CMakeFiles/CosSimOpTest.dir/all] Error 2
make[1]: *** [paddle/function/CMakeFiles/CrossMapNormalOpTest.dir/all] Error 2
make[1]: *** [paddle/function/CMakeFiles/FunctionTest.dir/all] Error 2
make[1]: *** [paddle/function/CMakeFiles/ContextProjectionOpTest.dir/all] Error 2
make[1]: *** [paddle/function/CMakeFiles/MulOpTest.dir/all] Error 2
make: *** [all] Error 2
试了好几遍，都是这个问题。

**Comment by QiJune** [comment]
建议先试试最新的develop分支，看能否编译通过

**Comment by xieshufu** [comment]
用github上最新的版本测试了一下，发现编译能通过，也能产生PADDLE程序,不过在用cmake的时候也会产生core。  难道是我的那个分支上的版本有一些问题？

**Comment by QiJune** [comment]
能贴一下你用的哪个分支吗 @xieshufu

**Comment by xieshufu** [comment]
https://github.com/zzsu/Paddle.git 这是以前的同学从PADDLE上拿到的分支版本，和目前PADDLE目录的不同， 时间大概在6个月之前。

**Comment by QiJune** [comment]
可以在CMakeLists.txt中加上这句命令试试
```
set(CMAKE_CXX_LINK_EXECUTABLE "${CMAKE_CXX_LINK_EXECUTABLE} -ldl -lrt")
```

**Comment by xieshufu** [comment]
编译的新版本运行，出这个错误：   
1 /home/vis/xieshufu/paddle/ocr/test_exe/bin/paddle: line 83: [: 0.9.0a0: binary operator expected
  2   File "<stdin>", line 3
  3     if LooseVersion("0.9.0a0
  4                            ^
  5 SyntaxError: EOL while scanning string literal
  6 /home/vis/xieshufu/paddle/ocr/test_exe/bin/paddle: line 98: /home/vis/xieshufu/paddle/ocr/test_exe/bin/paddle_trainer    : No such file or directory
~

**Comment by QiJune** [comment]
这个版本还是0.9.0a0吧，你把目录删除，重新编一下新版本

**Comment by xieshufu** [comment]
set(CMAKE_CXX_LINK_EXECUTABLE "${CMAKE_CXX_LINK_EXECUTABLE} -ldl -lrt")
添加这个也不行，那台机器以前是可以的，后来有同学重新安装了python环境以及一些包，导致编译的时候就有问题。 我也检查过python的版本，感觉都是可以的，但这个分支的版本(https://github.com/zzsu/Paddle.git )就是编译不出来。

**Comment by wangkuiyi** [comment]
@QiJune 是不是0.9.0还不支持用 Docker 编译？

**Comment by QiJune** [comment]
@wangkuiyi 0.9.0是去年11月的版本了，还没有docker相关的编译开发工具链

**Comment by xieshufu** [comment]
@QiJune 我从主干上下载PADDLE源代码，编译是成功了，版本是这个： PaddlePaddle 0.10.0, compiled with
    with_avx: ON
    with_gpu: ON
    with_mkldnn: @WITH_MKLDNN
    with_mklml: ON
    with_double: OFF
    with_python: ON
    with_rdma: OFF
    with_timer: OFF

在相同机器上，我尝试编译分支的那个代码，还是提示这个问题：
[ 84%] make64[2]: *** No rule to make target `../third_party/install/glog/lib/libglog.a', needed by `paddle/function/PadOpTest'.  Stop.
我看了一下本地库的glob目录信息，见下面： 
ll ../third_party/install/glog/
drwxrwxr-x 3 vis vis 4096 Aug 27 10:21 include
drwxrwxr-x 3 vis vis 4096 Aug 27 10:21 lib64

没有lib目录，但有lib64目录。 难道是有些库版本更改导致编译lib库的版本发生变化？

**Comment by xieshufu** [comment]
将lib64目录拷贝为lib目录，编译通过！
