### ISSUE TITLE
FM模型用于DNN，如何实现对特征的隐向量两两点积操作

### ISSUE THREAD

**Issue by duanxian** [PaddlePaddle/Paddle#3664]
论文地址： https://arxiv.org/pdf/1703.04247.pdf
![image](https://user-images.githubusercontent.com/2832303/29660474-0ad7473e-88f4-11e7-8c75-5bd8094914cd.png)
对应的公式：
![image](https://user-images.githubusercontent.com/2832303/29660570-3eaaadd0-88f4-11e7-8658-5ebb33e770d7.png)
怎么定义图中的FM layer？

**Comment by lcy-seso** [comment]
Paddle 目前没有这个layer，也没有办法通过基础运算组合出这个layer需要的计算。需要来写C++代码实现。

**Comment by duanxian** [comment]
如果自己写代码实现的话，主要是实现哪几个模块，有没有相关的demo？

**Comment by lcy-seso** [comment]
需要自己实现 FM 这个layer，可以参考此文档： http://doc.paddlepaddle.org/doc/howto/dev/new_layer_en.html
