### ISSUE TITLE
python进程和编译c++的进程不能共存？ 

### ISSUE THREAD

**Issue by Jarlonyan** [PaddlePaddle/Paddle#3665]
请教一个问题，同学A正在用paddle的 Python接口运行一个程序a。我同时编译另外一个程序b（链接了paddle.so），总是会编译失败(a,b在同一个机器上)。但是A同学的进程杀了，这边就可以编译了。请问，这是为什么呢？

**Comment by QiJune** [comment]
请问能给一个复现问题的最小环境吗，有助于进一步跟进

**Comment by Jarlonyan** [comment]
外网不方便给内网的路径链接吧。您可以试一下，在同一台机器上用paddle的python接口训练模型（run起来），同时编译另外一个链接了paddle.so的C++程序。
