### ISSUE TITLE
训练过程中报错

### ISSUE THREAD

**Issue by bushidonggua** [PaddlePaddle/Paddle#3666]
训练mobilenet过程中报如下错误：
[INFO 2017-08-24 22:01:31,008 layers.py:2481] output for __conv_22__: c = 512, h = 14, w = 14, size = 100352
[INFO 2017-08-24 22:01:31,010 layers.py:2481] output for __conv_23__: c = 512, h = 7, w = 7, size = 25088
[INFO 2017-08-24 22:01:31,011 layers.py:2481] output for __conv_24__: c = 1024, h = 7, w = 7, size = 50176
[INFO 2017-08-24 22:01:31,013 layers.py:2481] output for __conv_25__: c = 1024, h = 7, w = 7, size = 50176
[INFO 2017-08-24 22:01:31,015 layers.py:2481] output for __conv_26__: c = 1024, h = 7, w = 7, size = 50176
[INFO 2017-08-24 22:01:31,016 layers.py:2606] output for __pool_0__: c = 1024, h = 1, w = 1, size = 1024
I0824 22:01:34.513042  4071 GradientMachine.cpp:85] Initing parameters..
I0824 22:01:34.720615  4071 GradientMachine.cpp:92] Init parameters done.

Pass 0, Batch 0, Cost 2.251644, {'classification_error_evaluator': 0.8359375}
.......................................
Pass 0, Batch 40, Cost 0.577483, {'classification_error_evaluator': 0.203125}
....Invalid SOS parameters for sequential JPEG
Invalid SOS parameters for sequential JPEG
Invalid SOS parameters for sequential JPEG
Invalid SOS parameters for sequential JPEG
Invalid SOS parameters for sequential JPEG
Invalid SOS parameters for sequential JPEG
Invalid SOS parameters for sequential JPEG
Invalid SOS parameters for sequential JPEG
Invalid SOS parameters for sequential JPEG
Invalid SOS parameters for sequential JPEG
Invalid SOS parameters for sequential JPEG
Invalid SOS parameters for sequential JPEG
Invalid SOS parameters for sequential JPEG
Invalid SOS parameters for sequential JPEG
Invalid SOS parameters for sequential JPEG
Invalid SOS parameters for sequential JPEG

**Comment by QiJune** [comment]
这个错误看起来是读取JPEG的问题，跟libjpeg有关系，请检查一下相关库吧。
