### ISSUE TITLE
dataloader不能返回dict类型的数据

### ISSUE THREAD

**Issue by henryccl** [PaddlePaddle/Paddle#36687]
我在将torch项目转换为paddle时，发现在paddle中dataloader不能返回dict类型的数据，我该如何解决这个问题呢？

**Comment by henryccl** [comment]
![image](https://user-images.githubusercontent.com/44051761/138647954-0a405ee4-8ce0-4982-b078-a7af79e43a05.png)

**Comment by cxxly** [comment]
您好，自定义dataset不需要返回字典，继承Dataset基类，实现__getitem__， __len__方法，__getitem__返回指定索引的样本即可，参考https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/io/Dataset_cn.html  。 dataset由dataloader加载并进行迭代，参考https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/io/DataLoader_cn.html

**Comment by cxxly** [comment]
您好，请问问题是否解决，解决辛苦close issue
