### ISSUE TITLE
【菁英计划】构建稀疏张量(sparse)

### ISSUE THREAD

**Issue by Ziyiiii** [PaddlePaddle/Paddle#36697]
请问paddle中如何构建稀疏张量？类似于torch.sparse.FloatTensor

**Comment by cxxly** [comment]
您好，目前还不支持。目前已经在调研中了，支持后会尽快给您回复！

**Comment by dingjiaweiww** [comment]
飞桨有计划支持稀疏运算，请问您的邮箱是什么呀，想和您交流一下具体使用场景～

**Comment by chenjiyan2001** [comment]
同问, 我也需要此功能, 有相应的解决办法吗?
