### ISSUE TITLE
Paddleseg 导出预测量化模型时报错。AttributeError: 'NoneType' object has no attribute 'state_dict'

### ISSUE THREAD

**Issue by huangwan-jiayi** [PaddlePaddle/Paddle#36705]
paddlpaddle版本：paddlepaddle-gpu的nightly build版本
![image](https://user-images.githubusercontent.com/71338215/138692172-a82bb90b-500e-49cb-bbaa-35347f7eea2f.png)

报错：
![image](https://user-images.githubusercontent.com/71338215/138692267-a1a5d17a-b652-443d-9a7f-83ea19d4e436.png)

**Comment by cxxly** [comment]
您好，看异常栈像是在执行 `utils.load_entire_model`失败，导致model为NoneType，请检查model_path是否正确。另外，如果无法自行解决，建议用PDB或IDE Debuger工具初步定位错误代码位置后，提供个最小复现代码以方便我们调试。

**Comment by huangwan-jiayi** [comment]
![image](https://user-images.githubusercontent.com/71338215/138703212-8ca1d4fa-394f-4c94-aa79-0c4b52054cfe.png)
模型路径没问题，
报错的utils.py

import contextlib
import filelock
import os
import tempfile
import numpy as np
import random
from urllib.parse import urlparse, unquote

import paddle

from paddleseg.utils import logger, seg_env
from paddleseg.utils.download import download_file_and_uncompress


@contextlib.contextmanager
def generate_tempdir(directory: str = None, **kwargs):
    '''Generate a temporary directory'''
    directory = seg_env.TMP_HOME if not directory else directory
    with tempfile.TemporaryDirectory(dir=directory, **kwargs) as _dir:
        yield _dir


def load_entire_model(model, pretrained):
    if pretrained is not None:
        load_pretrained_model(model, pretrained)
    else:
        logger.warning('Not all pretrained params of {} are loaded, ' \
                       'training from scratch or a pretrained backbone.'.format(model.__class__.__name__))


def load_pretrained_model(model, pretrained_model):
    if pretrained_model is not None:
        logger.info('Loading pretrained model from {}'.format(pretrained_model))
        # download pretrained model from url
        if urlparse(pretrained_model).netloc:
            pretrained_model = unquote(pretrained_model)
            savename = pretrained_model.split('/')[-1]
            if not savename.endswith(('tgz', 'tar.gz', 'tar', 'zip')):
                savename = pretrained_model.split('/')[-2]
            else:
                savename = savename.split('.')[0]
            with generate_tempdir() as _dir:
                with filelock.FileLock(
                        os.path.join(seg_env.TMP_HOME, savename)):
                    pretrained_model = download_file_and_uncompress(
                        pretrained_model,
                        savepath=_dir,
                        extrapath=seg_env.PRETRAINED_MODEL_HOME,
                        extraname=savename)

                    pretrained_model = os.path.join(pretrained_model,
                                                    'model.pdparams')

        if os.path.exists(pretrained_model):
            para_state_dict = paddle.load(pretrained_model)

            model_state_dict = model.state_dict()
            keys = model_state_dict.keys()
            num_params_loaded = 0
            for k in keys:
                if k not in para_state_dict:
                    logger.warning("{} is not in pretrained model".format(k))
                elif list(para_state_dict[k].shape) != list(
                        model_state_dict[k].shape):
                    logger.warning(
                        "[SKIP] Shape of pretrained params {} doesn't match.(Pretrained: {}, Actual: {})"
                        .format(k, para_state_dict[k].shape,
                                model_state_dict[k].shape))
                else:
                    model_state_dict[k] = para_state_dict[k]
                    num_params_loaded += 1
            model.set_dict(model_state_dict)
            logger.info("There are {}/{} variables loaded into {}.".format(
                num_params_loaded, len(model_state_dict),
                model.__class__.__name__))

        else:
            raise ValueError(
                'The pretrained model directory is not Found: {}'.format(
                    pretrained_model))
    else:
        logger.info(
            'No pretrained model to load, {} will be trained from scratch.'.
            format(model.__class__.__name__))


def resume(model, optimizer, resume_model):
    if resume_model is not None:
        logger.info('Resume model from {}'.format(resume_model))
        if os.path.exists(resume_model):
            resume_model = os.path.normpath(resume_model)
            ckpt_path = os.path.join(resume_model, 'model.pdparams')
            para_state_dict = paddle.load(ckpt_path)
            ckpt_path = os.path.join(resume_model, 'model.pdopt')
            opti_state_dict = paddle.load(ckpt_path)
            model.set_state_dict(para_state_dict)
            optimizer.set_state_dict(opti_state_dict)

            iter = resume_model.split('_')[-1]
            iter = int(iter)
            return iter
        else:
            raise ValueError(
                'Directory of the model needed to resume is not Found: {}'.
                format(resume_model))
    else:
        logger.info('No model needed to resume.')


def worker_init_fn(worker_id):
    np.random.seed(random.randint(0, 100000))

**Comment by huangwan-jiayi** [comment]
另外 我测试量化模型的时候 python slim/quant/qat_val.py   报一样的错

**Comment by huangwan-jiayi** [comment]
> 您好，看异常栈像是在执行 `utils.load_entire_model`失败，导致model为NoneType，请检查model_path是否正确。另外，如果无法自行解决，建议用PDB或IDE Debuger工具初步定位错误代码位置后，提供个最小复现代码以方便我们调试。

hallo？

**Comment by yghstill** [comment]
@huangwan-jiayi 安装的PaddleSlim版本正确吗：https://github.com/PaddlePaddle/PaddleSeg/blob/release/2.3/docs/slim/quant/quant.md#31-%E7%8E%AF%E5%A2%83%E5%87%86%E5%A4%87

**Comment by huangwan-jiayi** [comment]
![image](https://user-images.githubusercontent.com/71338215/139011199-ca735898-9594-470a-9af6-4b81b54634f1.png)
![image](https://user-images.githubusercontent.com/71338215/139011312-0a90fe38-f91e-4aac-a9b3-b691bff9df53.png)
![image](https://user-images.githubusercontent.com/71338215/139011351-7f74bc4f-216f-4d05-b788-744380cefe51.png)
![image](https://user-images.githubusercontent.com/71338215/139011449-8f76b735-e335-4613-b6e8-3172ef69dd57.png)
按着文档一步一步执行来的，我把Paddlesim git到Paddleseg目录下的 还是报一样的错

**Comment by juncaipeng** [comment]
请尝试一下，将`PaddleSeg/slim/quant/qat_val.py`中的 `quant_model = quantizer.quantize(model)`修改为`quant_model = quantizer.quantize(model, inplace=False)`。
`PaddleSeg/slim/quant/qat_export.py`文件类似。

**Comment by huangwan-jiayi** [comment]
![image](https://user-images.githubusercontent.com/71338215/139043799-da57a222-362f-4fb2-b847-b77fb0747823.png)
![image](https://user-images.githubusercontent.com/71338215/139043840-d0ddcdb9-1363-421c-b162-d161ce4c722f.png)
![image](https://user-images.githubusercontent.com/71338215/139044192-57fe3bc2-3f0d-4568-964c-5ecd62e2d94b.png)
val.py改了报错，另外export.py文件中无quant_model = quantizer.quantize(model)

**Comment by juncaipeng** [comment]
这个问题本机没有复现，估计还是安装没正确。
PaddleSlim reset到那个commit id后，可以看到PaddleSlim/paddleslim/dygraph/quant/qat.py文件中的QAT如下，quantize函数有inplace参数。
![image](https://user-images.githubusercontent.com/52520497/139058860-8bb6b570-0ecb-4ea0-9230-2723660d452c.png)

你先卸载PaddleSlim，删掉PaddleSlim目录下的build 和dist目录，再次执行 python setup.py install，估计是安装了原先版本。

**Comment by huangwan-jiayi** [comment]
重新按着
![image](https://user-images.githubusercontent.com/71338215/139069257-1c6a2458-ccf5-4252-9b5a-e6a17bfabd7d.png)
安装了一下，还是报一样的错，会不会是paddleseg版本的问题？

**Comment by yghstill** [comment]
@huangwan-jiayi 再试下直接设置PaddleSlim路径即可，不用安装：
```shell
export PYTHONPATH=/path/to/PaddleSlim/:$PYTHONPATH
```

**Comment by huangwan-jiayi** [comment]
![image](https://user-images.githubusercontent.com/71338215/139092817-1984cda1-74ad-4b3c-903b-98c68e03e731.png)
还是不行，另外我可以用pip uninstall 来删除已安装的paddleslim吗，或者我怎么删除，我直接去paddleslim文件夹下把build 和dist 删除了 就算我把环境中的paddleslim删除了？

**Comment by yghstill** [comment]
@huangwan-jiayi /path/to/PaddleSlim/ 是你PaddleSlim的存放路径，需要改成真实的路径哈，不要直接粘贴过去

**Comment by huangwan-jiayi** [comment]
谢谢，成功导出了量化后的模型，可是量化后的模型C++部署在jetson nx上 推理速度反而慢了一点，之前试了裁剪，速度也是慢了
