### ISSUE TITLE
[菁英计划] KaiMIngUniform初始化

### ISSUE THREAD

**Issue by zhoucz97** [PaddlePaddle/Paddle#36717]
Kaiming初始化公式与pytorch的Kaiming初始化不一样，比如KaiMingUniform，pytorch版支持很多非线性函数操作，而paddle的一些参数都写死了。如paddle的KaiMingUniform初始化公式是$\sqrt(6) / fan_in$，对应torch的ReLU，而torch的KaiMingUniform初始化默认使用LeakyReLU。

paddle KaimingUniform: https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/nn/initializer/KaimingUniform_cn.html#kaiminguniform

torch KaimingUniform: https://pytorch.org/docs/stable/nn.init.html?highlight=kaiming#torch.nn.init.kaiming_uniform_

**Comment by tianxin1860** [comment]
您好，感谢您的积极反馈，KaiMIngUniform 的实现我们正在进行兼容性升级评估，欢迎关注~
