### ISSUE TITLE
Paddle中的Adamax优化器和PyTorch中对应的Adamax优化器计算逻辑有diff

### ISSUE THREAD

**Issue by yingyibiao** [PaddlePaddle/Paddle#36712]
Paddle 2.2rc版本，Pytorch 1.10.0版本
![image](https://user-images.githubusercontent.com/52000032/138723816-95b06f2c-c00b-4ae9-a8f5-b9ae55f0e262.png)
![image](https://user-images.githubusercontent.com/52000032/138723933-f5d76af0-2612-4b89-bf58-bf45517265d7.png)
主要的diff是epsilon加的地方不一致（BTW，原始论文中没有epsilon参数）

**Comment by cxxly** [comment]
@frankwhzhang ，辛苦协助跟进
