### ISSUE TITLE
使用CPU进行模型训练，如何利用多处理器进行加速

### ISSUE THREAD

**Issue by morgan-bc** [PaddlePaddle/Paddle#36718]
- 版本、环境信息：
    1）PaddlePaddle版本：2.1.3
    2）CPU：预测若用CPU，Intel(R) Xeon(R) Platinum 
    3）GPU：预测若用GPU，无
    4）系统环境：Ubuntu 20.04

目前服务器环境为 Intel Xeon 48 核 96线程，没有GPU。使用 cpu训练时只能使用一个线程计算，请问在 2.1 动态图版本如何使用多核并行加速训练，比如使用 cpu 全部 48核

**Comment by tianxin1860** [comment]
您好, 在2.0版本动态图模式下，CPU训练加速可以从以下两点进行配置：

使用多进程DataLoader加速数据读取：训练数据较多时，数据处理往往会成为训练速度的瓶颈，paddle提供了异步数据读取接口DataLoader，可以使用多进程进行数据加载，充分利用多处理器的优势，具体使用方法及示例请参考API文档：paddle.io.DataLoader。

推荐使用支持MKL（英特尔数学核心函数库）的paddle安装包，MKL相比Openblas等通用计算库在计算速度上有显著的优势，能够提升您的训练效率。

**Comment by morgan-bc** [comment]
我用的是 MKL 版的 paddle，问题是训练的时候查看 cpu 占用，显示只有一个核在做计算，环境变量中已经设置了 `export CPU_NUM=48`，但是没有什么效果。我看到文档中静态图有设置 `CPU_NUM` 的说明 (https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/static/BuildStrategy_cn.html) ，请问动态图有没有相同的功能

**Comment by YLyeliang** [comment]
> 我用的是 MKL 版的 paddle，问题是训练的时候查看 cpu 占用，显示只有一个核在做计算，环境变量中已经设置了 `export CPU_NUM=48`，但是没有什么效果。我看到文档中静态图有设置 `CPU_NUM` 的说明 (https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/static/BuildStrategy_cn.html) ，请问动态图有没有相同的功能

我这也是相同的情况，用pytorch的话就能支持多核训练，你解决了吗这个问题。

**Comment by morgan-bc** [comment]
@YLyeliang 没有

**Comment by tianxin1860** [comment]
两个方法可以开启动态图CPU单机多进程DataParallel训练：

1. 首先如果是PaddlePaddle-CPU版本，那么 python -m paddle.distributed.launch --nproc_per_node=4 train.py 方式启动默认是 CPU 并行。也可以与2类似使用backend参数。

2. 如果是PaddlePaddle-GPU版本，那么 python -m paddle.distributed.launch --backend=gloo --nproc_per_node=4 train.py 就可以开启CPU并行训练。

更加具体的描述可以见PR：https://github.com/PaddlePaddle/Paddle/pull/35745

**Comment by morgan-bc** [comment]
请问你这是哪个版本的 paddle . 在 PaddlePaddle-CPU(2.1.3) 中使用 `python -m paddle.distributed.launch --nproc_per_node=4 train.py` ，报错信息信息如下
```
WARNING 2021-11-02 18:29:05,512 launch.py:353] Not found distinct arguments and not compiled with cuda or xpu. Default use ps mode
Traceback (most recent call last):
  File "/root/anaconda3/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/root/anaconda3/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/root/anaconda3/lib/python3.8/site-packages/paddle/distributed/launch.py", line 16, in <module>
    launch.launch()
  File "/root/anaconda3/lib/python3.8/site-packages/paddle/distributed/fleet/launch.py", line 373, in launch
    launch_ps(args, distribute_mode)
  File "/root/anaconda3/lib/python3.8/site-packages/paddle/distributed/fleet/launch.py", line 291, in launch_ps
    ps_launcher = ParameterServerLauncher(args, distribute_mode)
  File "/root/anaconda3/lib/python3.8/site-packages/paddle/distributed/fleet/launch_utils.py", line 807, in __init__
    self.get_role_endpoints(args)
  File "/root/anaconda3/lib/python3.8/site-packages/paddle/distributed/fleet/launch_utils.py", line 824, in get_role_endpoints
    assert args.servers != "", "The setting of Parameter-Server must has server_num or servers."
AssertionError: The setting of Parameter-Server must has server_num or servers.

```

如果使用 ` python -m paddle.distributed.launch --backend=gloo --nproc_per_node=4 train.py` 指定后端，结果也报错
```
usage: launch.py [-h] [--log_dir LOG_DIR] [--nproc_per_node NPROC_PER_NODE] [--run_mode RUN_MODE] [--ips IPS] [--servers SERVERS] [--workers WORKERS] [--heter_workers HETER_WORKERS]
                 [--worker_num WORKER_NUM] [--server_num SERVER_NUM] [--heter_worker_num HETER_WORKER_NUM] [--http_port HTTP_PORT]
                 training_script ...
launch.py: error: unrecognized arguments: --backend=gloo

```

**Comment by tianxin1860** [comment]
使用 Paddle 2.2.0 最新版本试试呢？会复现同样的问题吗？

**Comment by zengweigit** [comment]
请问最后怎么解决的？电脑cpu4核，也是只有一个核在跑
