### ISSUE TITLE
训练输入与filter精度不对应

### ISSUE THREAD

**Issue by ranpeng-git** [PaddlePaddle/Paddle#36720]
ValueError: (InvalidArgument) input and filter data type should be consistent, but received input data type is double and filter type is float

**Comment by tianxin1860** [comment]
> ValueError: (InvalidArgument) input and filter data type should be consistent, but received input data type is double and filter type is float

您好，错误原因是由于输入数据类型和 Filter 数据类型不一致导致，请提供报错代码片段方便进一步定位问题。

**Comment by ranpeng-git** [comment]
问题是这样：我们需要输入的数据类型保持为float64，我们如何让模型在flaot64下训练，如果直接运行默认模型为float32的则直接报这个错误

**Comment by ranpeng-git** [comment]
用model.to(dtype = 'falot64')解决该问题
