### ISSUE TITLE
Add support to release Linux aarch64 wheels

### ISSUE THREAD

**Issue by odidev** [PaddlePaddle/Paddle#36742]
On aarch64, ‘pip install paddlepaddle-gpu’ gives the following error:

```
ERROR: Could not find a version that satisfies the requirement paddlepaddle-gpu (from versions: none)
ERROR: No matching distribution found for paddlepaddle-gpu
```

Please let me know your interest in releasing Linux aarch64 wheels. I can help with this.

**Comment by wangye707** [comment]
@odidev arm的paddlepaddle-gpu版本是指jetson系统的吗？在这里下载：https://github.com/PaddlePaddle/Paddle-Inference-Demo/blob/master/docs/user_guides/download_lib.md

**Comment by odidev** [comment]
Is there any plan for releasing AArch64 wheels on PyPI. It will be visible to pip then.

**Comment by odidev** [comment]
@wangye707, is there any plan for releasing AArch64 wheels on PyPI.

**Comment by wangye707** [comment]
@odidev 这个季度应该有计划，@ZihanDong

**Comment by ZihanDong** [comment]
我们预计会在下个正式版本(一个季度后)的官方文档中加入针对AArch64平台的wheel安装包下载链接，但是暂时不会发布到PyPI中

We are planning to add the download link of the wheel installation package for AArch64 in the official documentation in our next release (about 3 months later), but it will not be available on PyPI

**Comment by odidev** [comment]
@ZihanDong, May I know the reason for not uploading the wheels on PyPI? Are you facing any issues while uploading? Can I contribute in uploading the wheels on PyPI?
