### ISSUE TITLE
[飞桨菁英]paddle.scatter

### ISSUE THREAD

**Issue by ranpeng-git** [PaddlePaddle/Paddle#36743]
**如何解决scatter api在两个框架传参不一致的问题。**  
paddle.scatter中的参数必须为tensor，其中x和updates的shape必须完全一致并且index的维度只能为1，我们要如何实现torch.scatter中那样updats用标量输入且index维度可以不为1的问题。

**Comment by tianxin1860** [comment]
您好，对于 index 维度不为1 的情况支持，目前我们正在评估 paddle.scatter 进行兼容性功能升级的方案，欢迎关注~

**Comment by Ligoml** [comment]
你好，我们目前已经具备和`torch.scatter`功能等价的api`paddle.put_along_axis`，你可以在develop版本中体验，该api预计会在2.3rc版本中发布~
