### ISSUE TITLE
What does it mean WITH_STYLE_CHECK

### ISSUE THREAD

**Issue by wangkuiyi** [PaddlePaddle/Paddle#3674]
I noticed that in https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/scripts/docker/build.sh#L40 there is an environment variable WITH_STYLE_CHECK, which is OFF by default. Anyone know what does that mean?

**Comment by luotao1** [comment]
`WITH_STYLE_CHECK` means that check code style when building, which is ON by default now.
http://www.paddlepaddle.org/docs/develop/documentation/en/getstarted/build_and_install/build_from_source_en.html#bool-type-options
