### ISSUE TITLE
关于paddle.nn.Conv2DTranspose的参数'output_size'的问题

### ISSUE THREAD

**Issue by zbp-xxxp** [PaddlePaddle/Paddle#36754]
PaddlePaddle版本是2.1.2

文档'output_size'参数错误；这个output_size应该是可以指定的，但是文档里没有显示出来：
![](https://ai-studio-static-online.cdn.bcebos.com/7879aee408e444dda182be8dfdfb6ff916ac41e5e3084b32b0a6df10cf5fc155)

并且调用的时候出现了报错：
![](https://ai-studio-static-online.cdn.bcebos.com/3c0ed671f55a466782d8cd7d4dee15af8e376d3d851145fe8be90512293c7afa)

![](https://ai-studio-static-online.cdn.bcebos.com/f08385ef37a1473e81b6e052eface1ce98bac58cf61743de8f1b7a7499778975)

查看源码后发现该参数应该在forward时传入，但文档没有写清楚。

**Comment by GT-ZhangAcer** [comment]
提一下两个个人的建议给相关负责同学：  
1. 对于class的文档，感觉还是要列出method要好一些，至少要呈现出主要的参数使用方式。
2. Demo如果是只能跑最简的案例，那这个Demo意义并不大，大家想看的是特殊的用法而并非是大家都懂的用法。

**Comment by tianxin1860** [comment]
非常感谢您的积极反馈，我们会不断优化文档和案例，欢迎关注~
