### ISSUE TITLE
哪位大神能告诉我为啥2.0以后的版本要放弃lod_tensor

### ISSUE THREAD

**Issue by nfmmm** [PaddlePaddle/Paddle#36760]
![image](https://user-images.githubusercontent.com/66106874/138905416-7b6d59b2-a8bc-4b12-a9e6-d5c30a4b91e0.png)

为啥框架整体转为动态图后，要放弃lod_tensor，能给我一个让我不再纠结的答案吗。

**Comment by tianxin1860** [comment]
个人理解部分原因是由于 LodTensor 的概念和用法相对 Tensor 更复杂，会增加用户的学习成本和使用成本。
