### ISSUE TITLE
paddle源码建议增加类型提示

### ISSUE THREAD

**Issue by geekhch** [PaddlePaddle/Paddle#36774]
在使用paddle编程时，发现paddle2.1版本的函数没有类型提式（type hint），开发起来需要不断的查阅文档，无法利用IDE的索引支持。官网文档也不全面，导致开发效率很低。
建议利用Python3的类型提示，对paddle源码进行优化。

**Comment by esythan** [comment]
您好，您的反馈对产品非常有价值，我们内部会安排评估，未来有计划尽快回复。

**Comment by Ligoml** [comment]
可以参考这个项目：https://github.com/wj-Mcat/types-paddle
