### ISSUE TITLE
idl/paddle/sdk/sdk_1-0-4-765_PD_BL中的lib是否可以直接增加一个libpaddle_predictor_noavx_nothirdparty.a？

### ISSUE THREAD

**Issue by liuliuniu** [PaddlePaddle/Paddle#3677]
由于libpaddle_predictor_noavx.a中联编了部分protobuf文件，会导致主模块同时使用libpaddle_predictor_noavx.a和protobuf库时出现重定义，如果直接去掉protobuf库又会导致其中没有联编在libpaddle_predictor_noavx.a的类和函数出现未定义。
目前直接升级idl/paddle/sdk代价比价高，所以是否可以在idl/paddle/sdk/sdk_1-0-4-765_PD_BL中直接添加一个libpaddle_predictor_noavx_nothirdparty.a？

**Comment by typhoonzero** [comment]
这个库是比较老的版本了吧。Anyway，可以尝试用ar先把.a揭开，去掉其中protobuf的.o，然后再重新ar成.a。

参考：https://stackoverflow.com/questions/13942469/stripping-unneeded-symbols-from-a-static-library

**Comment by liuliuniu** [comment]
很悲剧，libpaddle_predictor_noavx_nothirdparty.a里只有一个目标文件paddle_predictor.o，protobuf也被包在一起了。貌似没法再继续了。。。

**Comment by qingqing01** [comment]
`idl/paddle/sdk` 同样的路径，较新的lib库里包含`libpaddle_predictor_noavx_nothirdparty.a`，可以更换下库吧。

**Comment by liuliuniu** [comment]
1.0.9有一个诡异的core，没太看懂。同时升级到1.0.9策略验证代价比较高。
还是希望能在1.0.4上直接发布一个libpaddle_predictor_noavx_nothirdparty.a

**Comment by typhoonzero** [comment]
暂时关闭此Issue了，如果仍存在问题，可以reopen
