### ISSUE TITLE
Paddle2.0 Dataset构建数据集 建议补充图像分割的数据增强方式示例

### ISSUE THREAD

**Issue by pokemonjs** [PaddlePaddle/Paddle#36789]
1）PaddlePaddle版本：请提供您的PaddlePaddle版本号，例如2.1.1
2）CPU/GPU：GPU
3）系统环境：Studio Notebook

用Paddle2.0 DataSet API构建数据集的时候，数据增强这块官方只给出了分类的示例，仅对图像进行增强，如果在分割任务中，需要对标签同步增强应该怎么做呢？（比如和图片同步水平竖直翻转），使用了
`self.transform=Compose([RandomVerticalFlip(0.25),RandomHorizontalFlip(0.25)])
image=self.transform(image)
label=self.transform(label).astype(np.int64)`
这种形式，发现有时候图像和标签的增强没有同步，即一个进行了翻转另一个没有翻转，能否补充这块的示例？谢谢！

**Comment by TCChenlong** [comment]
好的，非常感谢你的反馈，我们会尽快评估下需求~
