### ISSUE TITLE
【菁英计划】反向传播backword出现段错误

### ISSUE THREAD

**Issue by guguguzi** [PaddlePaddle/Paddle#36785]
- 版本、环境信息：
    PaddlePaddle版本：2.1.2

- 模型信息（题号46）
    1）模型名称：AttnGAN: Fine-Grained Text to Image Generation with Attentional Generative Adversarial Networks
    2）使用数据集名称：COCO2014
    3）使用算法名称：AttnGAN
    4）模型链接：https://github.com/taoxugit/AttnGAN
代码部分：github链接https://github.com/Paddle-Team-7/AttnGAN-Paddle
![image](https://user-images.githubusercontent.com/48168743/139039786-baccd750-618c-4742-bfc8-00e9a69e64af.png)

报错信息：
![image](https://user-images.githubusercontent.com/48168743/139039652-562a7aca-c78e-42e3-b071-6674fe192520.png)

**Comment by wangna11BD** [comment]
给一下BUG复现步骤吧
