### ISSUE TITLE
【菁英计划】torch.masked_fill函数

### ISSUE THREAD

**Issue by pooruss** [PaddlePaddle/Paddle#36806]
老师您好，请问paddle有对应torch.masked_fill函数api吗，还是需要自己实现

**Comment by WenmuZhou** [comment]
目前没有这个api，可以使用a[mask==1] = 1这种形式来实现

**Comment by Ligoml** [comment]
同学你好，建议用paddle.where替代哈，暂时不会列入我们的新增计划中~
