### ISSUE TITLE
有没有判断两个人体动作相似度的方法呢？

### ISSUE THREAD

**Issue by feelMySelfIsLouB** [PaddlePaddle/Paddle#36811]
判断出关键点计算欧式距离或者余弦相似度什么的。paddle有没有相关功能呢

**Comment by WorgenZhang** [comment]
您好，余弦相似度计算请参考 https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/nn/functional/cosine_similarity_cn.html#cosine-similarity；

关于计算人体动作相似度请您提供更详细的说明，谢谢

**Comment by feelMySelfIsLouB** [comment]
好得 ，谢谢
