### ISSUE TITLE
How to train model with bf16 data type

### ISSUE THREAD

**Issue by wuyunxiangwyx** [PaddlePaddle/Paddle#36810]
I want to train ocr model with bf16 data type in Intel Xeon Server, now paddle can support it?

**Comment by Intsigstephon** [comment]
Yes, Paddle provide amp function which can speed up the train process.  And in PaddleOCR, we also provide amp train. The document below may help you:  https://www.paddlepaddle.org.cn/documentation/docs/zh/guides/01_paddle2.0_introduction/basic_concept/amp_cn.html
