### ISSUE TITLE
【FT-2500编译错误】ARM架构编译安装时，make TARGET=ARMV8 -j$(nproc)步骤报错

### ISSUE THREAD

**Issue by oldpiao** [PaddlePaddle/Paddle#36817]
FT-2500编译错误，在执行make TARGET=ARMV8 -j$(nproc)步骤时，报错，报错原因貌似是访问GitHub连接超时，这样的问题该如何解决？
根据该连接提供的方法，在第9步时报错：https://www.paddlepaddle.org.cn/install/quick?docurl=/documentation/docs/zh/install/compile/arm-compile.html

报错信息：
“”“
Scanning dependencies of target extern_gflags
Scanning dependencies of target copy_pybind_command
Scanning dependencies of target copy_paddle_inference_pass_command
Scanning dependencies of target extern_zlib
Scanning dependencies of target copy_kernels_command
Scanning dependencies of target extern_dlpack
Scanning dependencies of target extern_boost
Scanning dependencies of target extern_eigen3
Scanning dependencies of target extern_threadpool
Scanning dependencies of target extern_openblas
Scanning dependencies of target extern_cryptopp
Scanning dependencies of target extern_warpctc
Scanning dependencies of target framework_py_proto_init
Scanning dependencies of target extern_pybind
Scanning dependencies of target profiler_py_proto_init
Scanning dependencies of target extern_gloo
[  1%] copy_if_different /opt/jiaming.bu/package/aaa/Paddle/build/paddle/fluid/pybind/pybind.h
[  1%] Creating directories for 'extern_gflags'
[  1%] Creating directories for 'extern_dlpack'
[  1%] copy_if_different /opt/jiaming.bu/package/aaa/Paddle/build/paddle/fluid/operators/jit/kernels.h
[  1%] copy_if_different /opt/jiaming.bu/package/aaa/Paddle/build/paddle/fluid/inference/api/paddle_inference_pass.h
[  1%] Creating directories for 'extern_boost'
[  1%] Creating directories for 'extern_threadpool'
[  1%] Creating directories for 'extern_zlib'
[  1%] Creating directories for 'extern_openblas'
[  1%] Creating directories for 'extern_eigen3'
[  1%] Creating directories for 'extern_cryptopp'
[  1%] Creating directories for 'extern_warpctc'
[  1%] Creating directories for 'extern_pybind'
[  1%] Creating directories for 'extern_gloo'
[  1%] Built target profiler_py_proto_init
[  1%] Built target copy_pybind_command
[  1%] Built target framework_py_proto_init
[  1%] Built target copy_paddle_inference_pass_command
[  1%] Built target copy_kernels_command
[  1%] Performing download step (git clone) for 'extern_gflags'
[  1%] Performing download step (git clone) for 'extern_dlpack'
[  1%] Performing download step (download, verify and extract) for 'extern_boost'
[  1%] Performing download step (git clone) for 'extern_openblas'
[  1%] Performing download step (git clone) for 'extern_threadpool'
[  1%] Performing download step (git clone) for 'extern_zlib'
[  1%] Performing download step (git clone) for 'extern_eigen3'
[  1%] Performing download step (git clone) for 'extern_cryptopp'
[  1%] Performing download step (git clone) for 'extern_warpctc'
[  1%] Performing download step (git clone) for 'extern_gloo'
[  1%] Performing download step (git clone) for 'extern_pybind'
-- Downloading...
   dst='/opt/jiaming.bu/package/aaa/Paddle/build/third_party/boost/src/extern_boost/boost_1_41_0.tar.gz'
   timeout='none'
-- Using src='http://paddlepaddledeps.bj.bcebos.com/boost_1_41_0.tar.gz'
正克隆到 'extern_gflags'...
正克隆到 'extern_eigen3'...
正克隆到 'extern_threadpool'...
正克隆到 'extern_dlpack'...
正克隆到 'extern_zlib'...
正克隆到 'extern_openblas'...
正克隆到 'extern_warpctc'...
正克隆到 'extern_cryptopp'...
正克隆到 'extern_pybind'...
正克隆到 'gloo'...
-- Downloading... done
-- extracting...
     src='/opt/jiaming.bu/package/aaa/Paddle/build/third_party/boost/src/extern_boost/boost_1_41_0.tar.gz'
     dst='/opt/jiaming.bu/package/aaa/Paddle/build/third_party/boost/src/extern_boost'
-- extracting... [tar xfz]
-- extracting... [analysis]
-- extracting... [rename]
-- extracting... [clean up]
-- extracting... done
[  1%] No update step for 'extern_boost'
[  1%] No patch step for 'extern_boost'
[  1%] No configure step for 'extern_boost'
[  2%] No build step for 'extern_boost'
[  2%] No install step for 'extern_boost'
[  2%] Completed 'extern_boost'
[  2%] Built target extern_boost
注意：正在切换到 '4da2c6b1974827b1999bab652a3d4703e1992d26'。

您正处于分离头指针状态。您可以查看、做试验性的修改及提交，并且您可以在切换
回一个分支时，丢弃在此状态下所做的提交而不对分支造成影响。

如果您想要通过创建分支来保留在此状态下所做的提交，您可以通过在 switch 命令
中添加参数 -c 来实现（现在或稍后）。例如：

  git switch -c <新分支名>

或者撤销此操作：

  git switch -

通过将配置变量 advice.detachedHead 设置为 false 来关闭此建议

HEAD 目前位于 4da2c6b19 Remove reference to non-existent unary_op_base class.
[  2%] Performing patch step for 'extern_eigen3'
[  2%] No update step for 'extern_eigen3'
[  2%] No configure step for 'extern_eigen3'
[  2%] No build step for 'extern_eigen3'
[  2%] No install step for 'extern_eigen3'
[  2%] No test step for 'extern_eigen3'
[  2%] Completed 'extern_eigen3'
[  2%] Built target extern_eigen3
fatal: 无法访问 'https://github.com/pybind/pybind11.git/'：Empty reply from server
fatal: 无法访问 'https://github.com/gflags/gflags.git/'：Empty reply from server
正克隆到 'extern_pybind'...
fatal: 无法访问 'https://github.com/baidu-research/warp-ctc.git/'：Empty reply from server
正克隆到 'extern_gflags'...
fatal: 无法访问 'https://github.com/progschj/ThreadPool.git/'：Empty reply from server
正克隆到 'extern_warpctc'...
fatal: 无法访问 'https://github.com/dmlc/dlpack.git/'：Empty reply from server
正克隆到 'extern_threadpool'...
fatal: 无法访问 'https://github.com/madler/zlib.git/'：Empty reply from server
正克隆到 'extern_dlpack'...
正克隆到 'extern_zlib'...
fatal: 无法访问 'https://github.com/dmlc/dlpack.git/'：Failed to connect to github.com port 443: 连接超时
fatal: 无法访问 'https://github.com/progschj/ThreadPool.git/'：Failed to connect to github.com port 443: 连接超时
fatal: 无法访问 'https://github.com/baidu-research/warp-ctc.git/'：Failed to connect to github.com port 443: 连接超时
fatal: 无法访问 'https://github.com/gflags/gflags.git/'：Failed to connect to github.com port 443: 连接超时
fatal: 无法访问 'https://github.com/madler/zlib.git/'：Failed to connect to github.com port 443: 连接超时
fatal: 无法访问 'https://github.com/pybind/pybind11.git/'：Failed to connect to github.com port 443: 连接超时
正克隆到 'extern_dlpack'...
正克隆到 'extern_warpctc'...
正克隆到 'extern_threadpool'...
正克隆到 'extern_gflags'...
正克隆到 'extern_pybind'...
正克隆到 'extern_zlib'...
fatal: 无法访问 'https://github.com/progschj/ThreadPool.git/'：Failed to connect to github.com port 443: 连接超时
fatal: 无法访问 'https://github.com/gflags/gflags.git/'：Failed to connect to github.com port 443: 连接超时
fatal: 无法访问 'https://github.com/pybind/pybind11.git/'：Failed to connect to github.com port 443: 连接超时
fatal: 无法访问 'https://github.com/dmlc/dlpack.git/'：Failed to connect to github.com port 443: 连接超时
fatal: 无法访问 'https://github.com/madler/zlib.git/'：Failed to connect to github.com port 443: 连接超时
fatal: 无法访问 'https://github.com/baidu-research/warp-ctc.git/'：Failed to connect to github.com port 443: 连接超时
-- Had to git clone more than once:
          3 times.
CMake Error at /opt/jiaming.bu/package/aaa/Paddle/build/third_party/gflags/tmp/extern_gflags-gitclone.cmake:31 (message):
  Failed to clone repository: 'https://github.com/gflags/gflags.git'

-- Had to git clone more than once:
          3 times.
-- Had to git clone more than once:
-- Had to git clone more than once:
          3 times.
          3 times.
CMake Error at /opt/jiaming.bu/package/aaa/Paddle/build/third_party/threadpool/tmp/extern_threadpool-gitclone.cmake:31 (message):
  Failed to clone repository: 'https://github.com/progschj/ThreadPool.git'

-- Had to git clone more than once:
-- Had to git clone more than once:
CMake Error at /opt/jiaming.bu/package/aaa/Paddle/build/third_party/zlib/tmp/extern_zlib-gitclone.cmake:31 (message):
  Failed to clone repository: 'https://github.com/madler/zlib.git'

          3 times.
CMake Error at /opt/jiaming.bu/package/aaa/Paddle/build/third_party/pybind/tmp/extern_pybind-gitclone.cmake:31 (message):
  Failed to clone repository: 'https://github.com/pybind/pybind11.git'

          3 times.

CMake Error at /opt/jiaming.bu/package/aaa/Paddle/build/third_party/dlpack/tmp/extern_dlpack-gitclone.cmake:31 (message):
  Failed to clone repository: 'https://github.com/dmlc/dlpack.git'

CMake Error at /opt/jiaming.bu/package/aaa/Paddle/build/third_party/warpctc/tmp/extern_warpctc-gitclone.cmake:31 (message):
  Failed to clone repository:
  'https://github.com/baidu-research/warp-ctc.git'

make[2]: *** [CMakeFiles/extern_gflags.dir/build.make:94：third_party/gflags/src/extern_gflags-stamp/extern_gflags-download] 错误 1
make[2]: *** [CMakeFiles/extern_threadpool.dir/build.make:95：third_party/threadpool/src/extern_threadpool-stamp/extern_threadpool-download] 错误 1
make[2]: *** [CMakeFiles/extern_pybind.dir/build.make:95：third_party/pybind/src/extern_pybind-stamp/extern_pybind-download] 错误 1
make[1]: *** [CMakeFiles/Makefile2:2685：CMakeFiles/extern_gflags.dir/all] 错误 2
make[2]: *** [CMakeFiles/extern_zlib.dir/build.make:94：third_party/zlib/src/extern_zlib-stamp/extern_zlib-download] 错误 1
make[1]: *** 正在等待未完成的任务....
make[2]: *** [CMakeFiles/extern_dlpack.dir/build.make:95：third_party/dlpack/src/extern_dlpack-stamp/extern_dlpack-download] 错误 1
make[1]: *** [CMakeFiles/Makefile2:2823：CMakeFiles/extern_threadpool.dir/all] 错误 2
make[2]: *** [CMakeFiles/extern_warpctc.dir/build.make:94：third_party/warpctc/src/extern_warpctc-stamp/extern_warpctc-download] 错误 1
make[1]: *** [CMakeFiles/Makefile2:2573：CMakeFiles/extern_pybind.dir/all] 错误 2
make[1]: *** [CMakeFiles/Makefile2:2850：CMakeFiles/extern_zlib.dir/all] 错误 2
make[1]: *** [CMakeFiles/Makefile2:2936：CMakeFiles/extern_warpctc.dir/all] 错误 2
make[1]: *** [CMakeFiles/Makefile2:2877：CMakeFiles/extern_dlpack.dir/all] 错误 2
fatal: 无法访问 'https://github.com/xianyi/OpenBLAS.git/'：OpenSSL SSL_read: SSL_ERROR_SYSCALL, errno 104
正克隆到 'extern_openblas'...
fatal: 无法访问 'https://github.com/sandyhouse/gloo.git/'：Operation timed out after 300033 milliseconds with 0 out of 0 bytes received
正克隆到 'gloo'...
-- Had to git clone more than once:
          2 times.
注意：正在切换到 'v0.0.2'。

您正处于分离头指针状态。您可以查看、做试验性的修改及提交，并且您可以在切换
回一个分支时，丢弃在此状态下所做的提交而不对分支造成影响。

如果您想要通过创建分支来保留在此状态下所做的提交，您可以通过在 switch 命令
中添加参数 -c 来实现（现在或稍后）。例如：

  git switch -c <新分支名>

或者撤销此操作：

  git switch -

通过将配置变量 advice.detachedHead 设置为 false 来关闭此建议

HEAD 目前位于 1da51bb replace auto with size_t
[  2%] No patch step for 'extern_gloo'
[  2%] No update step for 'extern_gloo'
[  2%] No configure step for 'extern_gloo'
[  2%] Performing build step for 'extern_gloo'
-- The CXX compiler identification is GNU 7.3.0
-- The C compiler identification is GNU 7.3.0
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Build type not set -- defaulting to Release
-- Configuring done
-- Generating done
-- Build files have been written to: /opt/jiaming.bu/package/aaa/Paddle/build/third_party/gloo/src/extern_gloo/gloo/build
make[3]: 警告: jobserver 不可用: 正使用 -j1。添加 “+” 到父 make 的规则。
Scanning dependencies of target gloo
[  2%] Building CXX object gloo/CMakeFiles/gloo.dir/algorithm.cc.o
[  5%] Building CXX object gloo/CMakeFiles/gloo.dir/allgather.cc.o
[  8%] Building CXX object gloo/CMakeFiles/gloo.dir/allgatherv.cc.o
[ 11%] Building CXX object gloo/CMakeFiles/gloo.dir/allreduce.cc.o
[ 14%] Building CXX object gloo/CMakeFiles/gloo.dir/allreduce_local.cc.o
[ 17%] Building CXX object gloo/CMakeFiles/gloo.dir/barrier.cc.o
[ 20%] Building CXX object gloo/CMakeFiles/gloo.dir/broadcast.cc.o
[ 22%] Building CXX object gloo/CMakeFiles/gloo.dir/context.cc.o
[ 25%] Building CXX object gloo/CMakeFiles/gloo.dir/gather.cc.o
[ 28%] Building CXX object gloo/CMakeFiles/gloo.dir/reduce.cc.o
[ 31%] Building CXX object gloo/CMakeFiles/gloo.dir/scatter.cc.o
[ 34%] Building CXX object gloo/CMakeFiles/gloo.dir/types.cc.o
[ 37%] Building CXX object gloo/CMakeFiles/gloo.dir/common/logging.cc.o
[ 40%] Building CXX object gloo/CMakeFiles/gloo.dir/common/print_logging.cc.o
[ 42%] Building CXX object gloo/CMakeFiles/gloo.dir/common/linux.cc.o
[ 45%] Building CXX object gloo/CMakeFiles/gloo.dir/rendezvous/context.cc.o
[ 48%] Building CXX object gloo/CMakeFiles/gloo.dir/rendezvous/file_store.cc.o
[ 51%] Building CXX object gloo/CMakeFiles/gloo.dir/rendezvous/hash_store.cc.o
[ 54%] Building CXX object gloo/CMakeFiles/gloo.dir/rendezvous/prefix_store.cc.o
[ 57%] Building CXX object gloo/CMakeFiles/gloo.dir/rendezvous/store.cc.o
[ 60%] Building CXX object gloo/CMakeFiles/gloo.dir/rendezvous/http_store.cc.o
[ 62%] Building CXX object gloo/CMakeFiles/gloo.dir/transport/address.cc.o
[ 65%] Building CXX object gloo/CMakeFiles/gloo.dir/transport/buffer.cc.o
[ 68%] Building CXX object gloo/CMakeFiles/gloo.dir/transport/context.cc.o
[ 71%] Building CXX object gloo/CMakeFiles/gloo.dir/transport/device.cc.o
[ 74%] Building CXX object gloo/CMakeFiles/gloo.dir/transport/pair.cc.o
[ 77%] Building CXX object gloo/CMakeFiles/gloo.dir/transport/unbound_buffer.cc.o
[ 80%] Building CXX object gloo/CMakeFiles/gloo.dir/transport/tcp/address.cc.o
[ 82%] Building CXX object gloo/CMakeFiles/gloo.dir/transport/tcp/buffer.cc.o
[ 85%] Building CXX object gloo/CMakeFiles/gloo.dir/transport/tcp/context.cc.o
[ 88%] Building CXX object gloo/CMakeFiles/gloo.dir/transport/tcp/device.cc.o
[ 91%] Building CXX object gloo/CMakeFiles/gloo.dir/transport/tcp/loop.cc.o
[ 94%] Building CXX object gloo/CMakeFiles/gloo.dir/transport/tcp/pair.cc.o
[ 97%] Building CXX object gloo/CMakeFiles/gloo.dir/transport/tcp/unbound_buffer.cc.o
[100%] Linking CXX static library libgloo.a
[100%] Built target gloo
[  2%] Performing install step for 'extern_gloo'
-- extern_gloo install command succeeded.  See also /opt/jiaming.bu/package/aaa/Paddle/build/third_party/gloo/src/extern_gloo-stamp/extern_gloo-install-*.log
[  2%] Completed 'extern_gloo'
[  2%] Built target extern_gloo
fatal: 远端意外挂断了
fatal: 过早的文件结束符（EOF）
fatal: index-pack 失败
正克隆到 'extern_openblas'...
fatal: 无法访问 'https://github.com/xianyi/OpenBLAS.git/'：Empty reply from server
-- Had to git clone more than once:
          3 times.
CMake Error at /opt/jiaming.bu/package/aaa/Paddle/build/third_party/openblas/tmp/extern_openblas-gitclone.cmake:31 (message):
  Failed to clone repository: 'https://github.com/xianyi/OpenBLAS.git'

make[2]: *** [CMakeFiles/extern_openblas.dir/build.make:94：third_party/openblas/src/extern_openblas-stamp/extern_openblas-download] 错误 1
make[1]: *** [CMakeFiles/Makefile2:2739：CMakeFiles/extern_openblas.dir/all] 错误 2
fatal: 无法访问 'https://github.com/weidai11/cryptopp.git/'：OpenSSL SSL_read: SSL_ERROR_SYSCALL, errno 110
正克隆到 'extern_cryptopp'...
-- Had to git clone more than once:
          2 times.
注意：正在切换到 'CRYPTOPP_8_2_0'。

您正处于分离头指针状态。您可以查看、做试验性的修改及提交，并且您可以在切换
回一个分支时，丢弃在此状态下所做的提交而不对分支造成影响。

如果您想要通过创建分支来保留在此状态下所做的提交，您可以通过在 switch 命令
中添加参数 -c 来实现（现在或稍后）。例如：

  git switch -c <新分支名>

或者撤销此操作：

  git switch -

通过将配置变量 advice.detachedHead 设置为 false 来关闭此建议

HEAD 目前位于 9dcc26c5 Prepare for Crypto++ 8.2 release Make ConstBytePtr return non-NULL pointer
[  2%] Performing patch step for 'extern_cryptopp'
[  2%] Performing update step for 'extern_cryptopp'
正克隆到 '/opt/jiaming.bu/package/aaa/Paddle/build/third_party/cryptopp/src/extern_cryptopp/cmake'...
-- extern_cryptopp update command succeeded.  See also /opt/jiaming.bu/package/aaa/Paddle/build/third_party/cryptopp/src/extern_cryptopp-stamp/extern_cryptopp-update-*.log
fatal: 无法访问 'https://github.com/noloader/cryptopp-cmake/'：Empty reply from server
make[2]: *** [CMakeFiles/extern_cryptopp.dir/build.make:104：third_party/cryptopp/src/extern_cryptopp-stamp/extern_cryptopp-patch] 错误 128
make[1]: *** [CMakeFiles/Makefile2:2600：CMakeFiles/extern_cryptopp.dir/all] 错误 2
make: *** [Makefile:133：all] 错误 2

“”“

**Comment by WorgenZhang** [comment]
您好，有两个排查思路，1) 请确认您的cmake版本，较低cmake版本可能会导致github无法访问的问题  2) 请确认网络环境是否能顺畅访问github
