### ISSUE TITLE
多机实验性能对齐相关问题

### ISSUE THREAD

**Issue by cbtpkzm** [PaddlePaddle/Paddle#3681]
多机训练的模型性能(使用sync SGD)能否与单机训练的模型性能相对齐
目前的理解是，多机在每个batch后都会更新一次梯度，那么在相同的参数下，双机与单机batch_size翻倍的模型性能应该是可以对齐的吗？是否还需要改动其他的参数？如果多机与单机的性能无法对齐会是什么原因导致的？

**Comment by gongweibao** [comment]
Fluid的多机正在进行中。
