### ISSUE TITLE
Add a CONTRIBUTING.md file

### ISSUE THREAD

**Issue by wangkuiyi** [PaddlePaddle/Paddle#3683]
Following the convention of most open source projects, in particular, the Universal Chater for LF Projects, we need a CONTRIBUTING.md file.  I noticed a good example as https://github.com/rkt/rkt/blob/master/CONTRIBUTING.md.

**Comment by luotao1** [comment]
We already have the CONTRIBUTING.md:
- English version: http://doc.paddlepaddle.org/develop/doc/howto/dev/contribute_to_paddle_en.html
- Chinese version: http://doc.paddlepaddle.org/develop/doc_cn/howto/dev/contribute_to_paddle_cn.html

And the Chinese version is newer than the English version.
