### ISSUE TITLE
FLAGS_gpu_memory_limit_mb not work

### ISSUE THREAD

**Issue by Brandonnogithub** [PaddlePaddle/Paddle#36848]
I am using paddleocr. Even if I set FLAGS_gpu_memory_limit_mb as 8000, the model will still use more than 8000 memory.

If I don't limit the memory, your model will cover more and more memory when doing predicting

I really hope you can provide a pytorch version. Paddle is hard to use.

**Comment by pollyyan** [comment]
您好，请问您使用的是ocr的哪个模型，使用的具体指令和配置文件可以贴一下吗～

**Comment by pollyyan** [comment]
Hello, which model of ocr are you using, can you post the specific instructions and configuration files used~

**Comment by Brandonnogithub** [comment]
> Hello, which model of ocr are you using, can you post the specific instructions and configuration files used~

@pollyyan Hi, thanks for your reply. 

This is my system info:

Paddle version: 2.1.3
Paddle With CUDA: True
OS: CentOS Linux 7
Python version: 3.8.10
CUDA version: 10.1.105
cuDNN version: None.None.None
Nvidia driver version: 440.95.01
****************************************

I am using V100-16G card.
The config is like:

```bash
export FLAGS_eager_delete_tensor_gb=0   
export FLAGS_fraction_of_gpu_memory_to_use=0.45 
export FLAGS_gpu_memory_limit_mb=8000   
```
****************************


The code is like:

```python
import paddlehub as hub
import os
import cv2

os.environ['CUDA_VISIBLE_DEVICES'] = '0'
model_module_name = f'chinese_ocr_db_crnn_server'
ocr_instance = hub.Module(name=model_module_name)

with open(image_path_list) as f:
    for line in f:
        image_path = line.strip()   # "xxx.jpg"
        image = cv2.imread(image_path)   # image shape is [height, width, channel]

        ret_samples = ocr_instance.recognize_text(
            images=[image],  
            use_gpu=True, 
            visualization=False,  
            box_thresh=0.5, 
            text_thresh=0.5 
        )
```
****************************************

all of the image's heigths are smaller than 1000
all of the image's width are smaller than 1000
all of the image's channels are 3

When I run this code, I got this info
```
[2021-11-01 17:12:36,837] [ WARNING] - The _initialize method in HubModule will soon be deprecated, you can use the __init__() to handle the initialization of the object
W1101 17:12:36.848394 144407 analysis_predictor.cc:1183] Deprecated. Please use CreatePredictor instead.
E1101 17:12:38.139657 144407 analysis_predictor.cc:679] Allocate too much memory for the GPU memory pool, assigned 8000 MB
E1101 17:12:38.139714 144407 analysis_predictor.cc:682] Try to shink the value by setting AnalysisConfig::EnableGpu(...)
[2021-11-01 17:12:38,886] [ WARNING] - The _initialize method in HubModule will soon be deprecated, you can use the __init__() to handle the initialization of the object
```
****************************************

Then gpu memory will jumb between 7000mb and 9000mb, where 9000mb is larger than the limitation(8000mb)

I wonder how can I limit the memory usage to 8000mb and let the model throw an OOM error when it needs more than 8000mb memory.

**Comment by Brandonnogithub** [comment]
Actually I want to run two ocr instances in one card, so I limit the memory to 8000mb.

The problem is if I don't limit the memory, the memory usage of one instance will keep increasing. Finally it will take up all the memory. It seems that existing code will cause memory leak. In this case I can't initail another instance on this card.

I also tried to predict a batch of imgas in recognize_text function, but it seems that this api just predict images one by one instead of batched. 

Now I am tring to limit the maximum memory of each instance so that I can run multi instances in one card.

Do you have any advice about how to predict images batched?

**Comment by haoyuying** [comment]
Could you  provide images to reproduce this problem? If you can provide an environment to reproduce this problem on aistudio, we will be easily solve this problem. I can not reproduce this problem  in my environment.  You can provide more information in https://github.com/PaddlePaddle/PaddleHub/ to get professional answer.
