### ISSUE TITLE
有没有 LoDTensor和SelectedRows 相互转换的接口吗

### ISSUE THREAD

**Issue by helen88** [PaddlePaddle/Paddle#36840]
场景：
    需要在自己的芯片上开发一个能支持sparse矩阵的adam。当grad_var是SelectedRows的时候，需要对param（传入是LoDTensor类型）进行转化，方便拿到里面的value，SelectedRows里的value是tensor的，然后转换下shape，就能复用我原来的算子。

想问下 paddle有提供了这样的api接口吗

**Comment by WorgenZhang** [comment]
您好，根据你提出的新需求，我们会进一步和您沟通下需求背景以及使用场景
