### ISSUE TITLE
loss反向传播出错

### ISSUE THREAD

**Issue by qdd1234** [PaddlePaddle/Paddle#36868]
您好，可以帮忙看一下报错吗，反向传播的时候出错了，这是什么原因导致的？
![$8%`T_}469((G3R_ONQIGBP](https://user-images.githubusercontent.com/68497831/139469588-fcb3d25e-c9b5-46f9-886f-29dbc774d133.png)

**Comment by seemingwang** [comment]
特别抱歉，由于疏忽遗漏了这个问题。 产生这个问题大概率是 backward连续调用2次产生的。一般调用下一次backward前需要跑一次前向计算，可以检查一下代码里是否有这个逻辑。

**Comment by seemingwang** [comment]
如果有特别需要，一定要连续跑2次backward，建议在跑backward的时候加上参数 retain_graph = True
