### ISSUE TITLE
【菁英计划】paddle 中有没有 torch.nn.HingeEmbeddingLoss 的实现或者替代品

### ISSUE THREAD

**Issue by S-HuaBomb** [PaddlePaddle/Paddle#36879]
- 标题：第 55 篇 Learning to Discover Cross-Domain Relations with Generative Adversarial Networks 
- 版本、环境信息：
    1）PaddlePaddle版本：2.1.2

- 复现信息：repo：https://github.com/ImportPaddle/DiscoGAN-Paddle
- 问题描述：paddle 没有 HingeEmbeddingLoss

torch 代码位置：[feat_criterion = nn.HingeEmbeddingLoss()](https://github.com/SKTBrain/DiscoGAN/blob/f0441787752c566dcc32642468f44d5e2f30b0a6/discogan/image_translation.py#L167)
paddle 代码位置：[feat_criterion = nn.HingeEmbeddingLoss()](https://github.com/ImportPaddle/DiscoGAN-Paddle/blob/71bc24c2e1b192bf818df758d50b5ea7940b8d99/discogan/image_translation.py#L179)

**Comment by wangna11BD** [comment]
paddle 中暂时没有nn.HingeEmbeddingLoss

**Comment by S-HuaBomb** [comment]
菁英计划中，我成功复现了第 55 篇 Learning to Discover Cross-Domain Relations with Generative Adversarial Networks。并且损失函数对齐成功。

repo：https://github.com/ImportPaddle/DiscoGAN-Paddle

调用地址：[feat_criterion = HingeEmbeddingLoss()](https://github.com/ImportPaddle/DiscoGAN-Paddle/blob/b494bfe2731c213a3e10e50d736da02aba80c3da/discogan/image_translation.py#L234)

paddle 实现：[class HingeEmbeddingLoss(nn.Layer)](https://github.com/ImportPaddle/DiscoGAN-Paddle/blob/b494bfe2731c213a3e10e50d736da02aba80c3da/discogan/loss_fn.py#L6)

参考：[torch.nn.HingeEmbeddingLoss](https://pytorch.org/docs/stable/generated/torch.nn.HingeEmbeddingLoss.html?highlight=hingeembeddingloss#torch.nn.HingeEmbeddingLoss)

**Comment by Ligoml** [comment]
感谢开发者 @S-HuaBomb 的贡献，为 paddle 补齐了 HingeEmbeddingLoss 的 API：https://github.com/PaddlePaddle/Paddle/pull/37540
欢迎更多的开发者为 paddle 提出 new feature，甚至直接贡献 PR~让我们共建国产第一深度学习框架！
