### ISSUE TITLE
[菁英计划]PyTorch-PaddlePaddle API映射表文档问题-所有版本

### ISSUE THREAD

**Issue by 27182812** [PaddlePaddle/Paddle#36872]
### 文档问题描述：
paddle.split和torch.split功能不一致
torch.split第二个参数split_size_or_sections为int时，指的是单个块的大小
paddle.split第二个参数num_or_sections 为int时，指的是Tensor平均划分为相同大小子Tensor的数量
功能并不一致，文档描述具有误导性质。

![image](https://user-images.githubusercontent.com/33630730/139518310-2da0e4e4-8b94-4ecc-bdea-51c78261f3c0.png)

**Comment by Ligoml** [comment]
感谢指出，文档团队会重新检查映射表并及时修改可能会引起误导的内容~

**Comment by wjj19950828** [comment]
感谢您的反馈～目前PaddlePaddle API映射表文档关于split相关问题已经更新，相关PR:https://github.com/PaddlePaddle/X2Paddle/pull/694
