### ISSUE TITLE
unit test stuck at memory test step

### ISSUE THREAD

**Issue by putcn** [PaddlePaddle/Paddle#3687]
https://github.com/PaddlePaddle/Paddle/pull/3676#issuecomment-325008051

I was trying to run through the unit tests with CPU build in my local dev docker env, and it stuck at the memory_test step for over 20min or so. my docker set to use 6cores and 5G of memory. docker version Version 17.06.0-ce-mac19 (18663), running in Macbook pro.

 74/134 Test  #74: stringpiece_test ....................   Passed    0.04 sec
        Start  75: stringprintf_test
 75/134 Test  #75: stringprintf_test ...................   Passed    0.04 sec
        Start  76: to_string_test
 76/134 Test  #76: to_string_test ......................   Passed    0.04 sec
        Start  77: memory_test

**Comment by wangkuiyi** [comment]
Could be related to 

```cpp
  for (auto size :
       {128, 256, 1024, 4096, 16384, 65536, 262144, 1048576, 4194304}) {
    ps[paddle::memory::Alloc(gpu, size)] = size;
```

in [`memory_test.cc`](https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/memory/memory_test.cc).

**Comment by putcn** [comment]
by default with_testing was set OFF
dockee WITH_GPU=OFF -v $PWD:/paddle paddle:dev ctest"
+ [[ OFF == \O\N ]]
+ BASE_IMAGE=ubuntu:16.04
+ DOCKERFILE_GPU_ENV=
+ DOCKERFILE_CUDNN_DSO=
+ [[ OFF == \O\N ]]
+ mkdir -p /paddle/build
+ cd /paddle/build
+ rm '*.deb'
+ true
+ rm -rf /paddle/paddle/dist
+ cat
========================================
Configuring cmake in /paddle/build ...
      -DCMAKE_BUILD_TYPE=Release
      -DWITH_DOC=OFF
      -DWITH_GPU=OFF
      -DWITH_AVX=ON
      -DWITH_GOLANG=ON
      -DWITH_SWIG_PY=ON
      -DWITH_C_API=OFF
      -DWITH_PYTHON=ON
      -DWITH_SWIG_PY=ON
      -DCUDNN_ROOT=/usr/
      -DWITH_STYLE_CHECK=OFF
      -DWITH_TESTING=OFF
      -DCMAKE_EXPORT_COMPILE_COMMANDS=ON
========================================
+ cmake .. -DCMAKE_BUILD_TYPE=Release -DWITH_DOC=OFF -DWITH_GPU=OFF -DWITH_AVX=ON -DWITH_GOLANG=ON -DWITH_SWIG_PY=ON -DWITH_C_API=OFF -DWITH_PYTHON=ON -DCUDNN_ROOT=/usr/ -DWITH_STYLE_CHECK=OFF -DWITH_TESTING=OFF -DCMAKE_EXPORT_COMPILE_COMMANDS=ON

**Comment by putcn** [comment]
turned out to be my code base tested against old testing code within old docker dev image. delete and recreate build dir and rebuild dev docker image fixes the issue.
