### ISSUE TITLE
【菁英计划】paddle有类似MultiplicativeLR的api吗？

### ISSUE THREAD

**Issue by guguguzi** [PaddlePaddle/Paddle#36870]
版本、环境信息：
   PaddlePaddle版本：2.1.2

paddle内没有找到torch.optim.lr_scheduler.MultiplicativeLR()功能api

**Comment by yingyibiao** [comment]
可以参考这里：https://github.com/PaddlePaddle/PaddleNLP/blob/develop/paddlenlp/ops/optimizer/adamwdl.py

**Comment by Ligoml** [comment]
感谢开发者 @guguguzi 的贡献，为 paddle 补齐了 MultiplicativeDecay  的 API：https://github.com/PaddlePaddle/Paddle/pull/38250 欢迎更多的开发者为 paddle 提出 new features，欢迎为 paddle 直接贡献 PR~让我们共建国产第一深度学习框架！
