### ISSUE TITLE
【菁英计划】Paddle的Tensor

### ISSUE THREAD

**Issue by JennyVanessa** [PaddlePaddle/Paddle#36883]
paddle的tensor不支持复杂的切片操作，什么时候优化呀，转成numpy操作后再转回paddle容易炸显存QAQ

**Comment by chenwhql** [comment]
2.2刚支持了一批切片操作，这里具体是什么操作呢？可以给个demo吗？

**Comment by JennyVanessa** [comment]
和索引相关的，e.g. a[a>0]=1

**Comment by JennyVanessa** [comment]
我们看看2.2 用的是2.0:)
