### ISSUE TITLE
请问如何进行值批量映射

### ISSUE THREAD

**Issue by huilin16** [PaddlePaddle/Paddle#36886]
我想修改onehot的编码方式，比如class=5时，将1编码为 1,0.5,0,0,0；将2编码为0.5,1,0.5,0,0。

我定义了从1到n的修改后的编码结果的字典，请问应该如何实现类似于paddle.nn.functional.one_hot一样的批量映射。我只会for循环，但这样太慢了，请问是否有快一些的方法，比如像np.vectorize之类

**Comment by sljlp** [comment]
你好，请看下embedding或者gather是否符合你的需求，如果还不行，那么目前还没有很好的解决办法
