### ISSUE TITLE
【菁英计划】pack_padded_sequence&pad_packed_sequence

### ISSUE THREAD

**Issue by JennyVanessa** [PaddlePaddle/Paddle#36882]
在复现nlp相关任务时，这两个基础算子pack_padded_sequence&pad_packed_sequence没有实现。

**Comment by yingyibiao** [comment]
关于pack_padded_sequence 和 pad_packed_sequence这两个算子缺失的问题，大家可以直接在rnn或者lstm的输入中传入sequence_length实现等价的功能。
