### ISSUE TITLE
【菁英计划】aistudio上传脚本任务显示不能够传递训练参数

### ISSUE THREAD

**Issue by buriedms** [PaddlePaddle/Paddle#36884]
在单机四卡是训练显示传递不了参数，但是在notebook终端当中可以正常运行，显示如下日志。
![image](https://user-images.githubusercontent.com/55041393/139579848-42951ff0-1aab-4061-845c-23e6e53d8cee.png)

**Comment by wangna11BD** [comment]
将run.sh中模型的相关参数放到一行后解决
