### ISSUE TITLE
【菁英计划】脚本任务unzip指令不能解压数据集显示con't find or open

### ISSUE THREAD

**Issue by buriedms** [PaddlePaddle/Paddle#36885]
日志显示问题：
unzip:  cannot find or open /root/paddlejob/workspace/train_data/datasets/data114496/old2life.zip
, /root/paddlejob/workspace/train_data/datasets/data114496/old2life.zip
.zip or /root/paddlejob/workspace/train_data/datasets/data114496/old2life.zip
.ZIP.

以下为我的代码指令：
SRC_DIR=/root/paddlejob/workspace/train_data/datasets/data114496/old2life.zip
TO_DIR=/root/paddlejob/workspace/train_data/datasets/
unzip $SRC_DIR -d $TO_DIR

**Comment by wangna11BD** [comment]
更换文件名，重新启动AIstudio脚本任务后解决
