### ISSUE TITLE
【菁英计划】 论文61 飞桨是否有类似pytorch的数据封装 _ntuple() 

### ISSUE THREAD

**Issue by zlwangustc** [PaddlePaddle/Paddle#36893]
### Describe the problem：
飞桨是否有类似pytorch的数据封装 _ntuple() 
_single = _ntuple(1) 
_pair = _ntuple(2) 
_triple = _ntuple(3) 
_quadruple = _ntuple(4) 

def _ntuple(n):
    def parse(x):
        if isinstance(x, container_abcs.Iterable):
            return x
        return tuple(repeat(x, n))
    return parse

**Comment by jerrywgz** [comment]
这个属于torch内部使用的函数，作用是将输入转换成指定长度的tuple，paddle中有类似的函数封装可以参考 https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/fluid/layers/utils.py#L26，也可以自己通过python进行封装～
