### ISSUE TITLE
背景占比大，导致银行卡检测识别；手动裁剪出单独的银行卡图片，识别成功

### ISSUE THREAD

**Issue by Essence9999** [PaddlePaddle/Paddle#36896]
自己Finetune的卡号检测模型，因为背景占比大，导致银行卡检测识别；手动裁剪出单独的银行卡图片，识别成功
剪裁前
![image](https://user-images.githubusercontent.com/66725845/139618943-b7e2f41b-0a64-4cd2-ae87-7bf0f966f3de.png)
剪裁后
![2](https://user-images.githubusercontent.com/66725845/139619444-45aca964-89dd-4128-b4db-47641819abe9.png)

有什么办法可以识别剪裁前的图片吗

**Comment by sljlp** [comment]
建议你设计一个更为鲁棒的算法，准备相应的数据集，训练一个更为鲁棒的模型

**Comment by sljlp** [comment]
请尝试下PaddleDetection 先对银行卡区域进行识别，然后将区域裁剪，最后再进行文字识别
