### ISSUE TITLE
图片尺寸小于736，但图片清晰，卡号识别失败

### ISSUE THREAD

**Issue by Essence9999** [PaddlePaddle/Paddle#36897]
![image](https://user-images.githubusercontent.com/66725845/139615886-93026ada-2112-40f3-8bbc-035af5a813ea.png)
268*201
自己finetune的检测模型，正常大小的图片是可以的
有没有类似det_max_side_len这样的参数，图片小于736，会自动同比例放大到736

**Comment by sljlp** [comment]
你好，不太清楚你的意思
据我理解，你可以使用图片的预处理接口，对图像进行缩放

**Comment by Essence9999** [comment]
> 你好，不太清楚你的意思 据我理解，你可以使用图片的预处理接口，对图像进行缩放

你好，能定位paddleocr那个程序吗？新手，谢谢大佬

**Comment by sljlp** [comment]
抱歉我对paddleocr不熟悉，你可以找一下检测程序的输入在哪里，在输入之前对图像进行缩放应该就可以
