### ISSUE TITLE
【菁英计划】实现库einops的类Rearrange报错

### ISSUE THREAD

**Issue by vcowwy** [PaddlePaddle/Paddle#36898]
论文复现，第62篇论文《CvT: Introducing Convolutions to Vision Transformers》

参考的github repo在models/cls_cvt.py中引入了einops库，使用了该库的函数rearrang进行数据重排，在模型的层里面使用了类Rearrange。使用paddle实现该类，前向报错。

![WechatIMG53](https://user-images.githubusercontent.com/38393385/139624573-a818a877-2deb-43f9-a009-8e08e193a006.png)

github项目链接：https://github.com/vcowwy/CvT_paddle

**Comment by littletomatodonkey** [comment]
看着不是rearrange模块的报错，可以再看下具体的python栈信息报错

```python
import paddle
import paddle.nn as nn

class Test(nn.Layer):
    def __init__(self, ):
        super().__init__()

    def forward(self, x):
        b, c, h, w = x.shape
        x = paddle.transpose(x, perm=[0, 2, 3, 1])
        x = paddle.reshape(x, shape=[b, h*w, c])
        return x



ra = Test()
x = paddle.ones([16, 32, 10, 10])
y = ra(x)
print(x.shape)
print(y.shape)
```
