### ISSUE TITLE
The performance of the quantized model is worse than that of the fp32 model, and the performance is worse after opening mkldnn

### ISSUE THREAD

**Issue by baoachun** [PaddlePaddle/Paddle#36905]
|  model       | mkldnn  | ir_optim  |  time(5117)  | time(6271)  |
|  ----  | ----  | ----  | ----  | ----  | 
| raw_fp32  | on | on | 6.9  | 6.3 |
| raw_fp32  | off | on | 4.8  | 2.7 |
| raw_fp32  | on | off | 4.9 | 3.2 |
| raw_fp32  | off | off | 4.8 | 2.6 |
|                   |      |       |   |       |
| ding_fp32  | on | on | 6.7 | 4.1 |
| ding_fp32  | off | on | 4.8 | 2.6 |
| ding_fp32  | on | off | 4.9 | 3.2 |
| ding_fp32  | off | off | 4.8 | 2.6 |
|                   |      |       |   |       |
| quant_int8  | on | on | 4.9 | 4.1 |
| quant_int8  | off | on | 4.6 | 2.8 |
| quant_int8  | on | off | 4.8 | 3.9 |
| quant_int8  | off | off | 4.6 | 3.1 |

**Comment by yaomichael** [comment]
@jiangjiajun can you share the model to reproduce this issue with us?

**Comment by jiangjiajun** [comment]
[pwg_tttest (1).zip](https://github.com/PaddlePaddle/Paddle/files/8842536/pwg_tttest.1.zip)
[test.zip](https://github.com/PaddlePaddle/Paddle/files/8842537/test.zip)

The quantized model and float model are compressed in pwg_tttest.1.zip

**Comment by zuzg** [comment]
Hi, I am investigating the case. Could you please share the qat model with fake_quant operators?

**Comment by yaomichael** [comment]
@jiangjiajun Is the quantized model you provided earlier in June saved model? Zuza is looking for QAT model...
