### ISSUE TITLE
飞腾S2500平台+K100加速卡编译paddlepaddle报错（cmake报错）

### ISSUE THREAD

**Issue by lansehuo** [PaddlePaddle/Paddle#36908]
为使您的问题得到快速解决，在建立Issue前，请您先通过如下方式搜索是否有相似问题:【搜索issue关键字】【使用labels筛选】【官方文档】
    1）PaddlePaddle版本：2.1
    2）CPU：S2500
    3）XPU：K100
    4）系统环境：银河麒麟服务器版操作系统，版本信息——release V10（U1）/(Tercel)-arm64-Build02/20210729-GFB
                                                                         内核——4.19.90-25.2.v2101.gfb01.ky10.aarch64。
进行本地编译paddlepaddle(release/2.1)，在cmake时，报错信息如下：
$cmake .. -DPY_VERSION=3.7          -DPYTHON_EXECUTABLE=$python_exe          -DWITH_ARM=ON          -DWITH_AARCH64=ON          -DWITH_TESTING=OFF          -DCMAKE_BUILD_TYPE=Release          -DON_INFER=ON          -DWITH_XBYAK=OFF          -DWITH_XPU=ON          -DWITH_GPU=OFF          -DWITH_LITE=ON          -DLITE_GIT_TAG=release/v2.9          -DXPU_SDK_ROOT=${XPU_SDK_ROOT}
-- Found Paddle host system: , version: 
-- Found Paddle host system's CPU: 128 cores
-- The CXX compiler identification is GNU 7.3.0
-- The C compiler identification is GNU 7.3.0
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- CXX compiler: /usr/bin/c++, version: GNU 7.3.0
-- C compiler: /usr/bin/cc, version: GNU 7.3.0
-- AR tools: /usr/bin/ar
-- Found Git: /usr/bin/git (found version "2.23.0") 
-- Performing Test MMX_FOUND
-- Performing Test MMX_FOUND - Failed
-- Performing Test SSE2_FOUND
-- Performing Test SSE2_FOUND - Failed
-- Performing Test SSE3_FOUND
-- Performing Test SSE3_FOUND - Failed
-- Performing Test AVX_FOUND
-- Performing Test AVX_FOUND - Failed
-- Performing Test AVX2_FOUND
-- Performing Test AVX2_FOUND - Failed
-- Performing Test AVX512F_FOUND
-- Performing Test AVX512F_FOUND - Failed
CMake Warning at CMakeLists.txt:245 (MESSAGE):
  Disable NCCL when compiling without GPU.  Force WITH_NCCL=OFF.

CMake Warning at CMakeLists.txt:292 (MESSAGE):
  Disable RCCL when compiling without ROCM.  Force WITH_RCCL=OFF.

-- Do not have AVX2 intrinsics and disabled MKL-DNN
-- BOOST_VERSION: 1.41.0, BOOST_URL: http://paddlepaddledeps.bj.bcebos.com/boost_1_41_0.tar.gz
-- warp-ctc library: /home/kylin/Paddle/build/third_party/install/warpctc/lib/libwarpctc.so
-- Found OpenBLAS (include: /usr/include/openblas, library: /usr/lib64/libopenblas.so)
-- Found lapack in OpenBLAS (include: /usr/include/openblas)
-- Protobuf protoc executable: /home/kylin/Paddle/build/third_party/install/protobuf/bin/protoc
-- Protobuf-lite library: /home/kylin/Paddle/build/third_party/install/protobuf/lib/libprotobuf-lite.a
-- Protobuf library: /home/kylin/Paddle/build/third_party/install/protobuf/lib/libprotobuf.a
-- Protoc library: /home/kylin/Paddle/build/third_party/install/protobuf/lib/libprotoc.a
-- Protobuf version: 3.1.0
-- Found PythonInterp: /usr/bin/python3.7 (found suitable version "3.7.4", minimum required is "3.7") 
-- Found PythonLibs: /usr/lib64/libpython3.7m.so (found suitable version "3.7.4", minimum required is "3.7") 
-- Found PY_pip: /usr/lib/python3.7/site-packages/pip  
-- Found PY_numpy: /home/kylin/.local/lib/python3.7/site-packages/numpy  
-- Found PY_wheel: /home/kylin/.local/lib/python3.7/site-packages/wheel  
-- Found PY_google.protobuf: /home/kylin/.local/lib/python3.7/site-packages/google/protobuf  
-- Found NumPy: /home/kylin/.local/lib/python3.7/site-packages/numpy/core/include  
CMake Error at cmake/external/xpu.cmake:101 (ADD_CUSTOM_TARGET):
  ADD_CUSTOM_TARGET cannot create target "extern_xpu" because another target
  with the same name already exists.  The existing target is a custom target
  created in source directory "/home/kylin/Paddle".  See documentation for
  policy CMP0002 for more details.
Call Stack (most recent call first):
  cmake/third_party.cmake:250 (include)
  CMakeLists.txt:307 (include)

-- Compile Paddle with Lite Engine.
CMake Warning at cmake/external/lite.cmake:55 (message):
  BUILD_COMMAND: $(MAKE);publish_inference;-j
Call Stack (most recent call first):
  cmake/third_party.cmake:320 (include)
  CMakeLists.txt:307 (include)

-- Paddle-lite BINARY_DIR: /home/kylin/Paddle/build/third_party/lite/src/extern_lite-build
-- Paddle-lite SOURCE_DIR: /home/kylin/Paddle/build/third_party/lite/src/extern_lite
-- Looking for UINT64_MAX
-- Looking for UINT64_MAX - found
-- Looking for sys/types.h
-- Looking for sys/types.h - found
-- Looking for stdint.h
-- Looking for stdint.h - found
-- Looking for stddef.h
-- Looking for stddef.h - found
-- Check size of pthread_spinlock_t
-- Check size of pthread_spinlock_t - done
-- Check size of pthread_barrier_t
-- Check size of pthread_barrier_t - done
-- Performing Test C_COMPILER_SUPPORT_FLAG__fPIC
-- Performing Test C_COMPILER_SUPPORT_FLAG__fPIC - Success
-- Performing Test CXX_COMPILER_SUPPORT_FLAG__fPIC
-- Performing Test CXX_COMPILER_SUPPORT_FLAG__fPIC - Success
-- Performing Test C_COMPILER_SUPPORT_FLAG__fno_omit_frame_pointer
-- Performing Test C_COMPILER_SUPPORT_FLAG__fno_omit_frame_pointer - Success
-- Performing Test CXX_COMPILER_SUPPORT_FLAG__fno_omit_frame_pointer
-- Performing Test CXX_COMPILER_SUPPORT_FLAG__fno_omit_frame_pointer - Success
-- Performing Test C_COMPILER_SUPPORT_FLAG__Werror
-- Performing Test C_COMPILER_SUPPORT_FLAG__Werror - Success
-- Performing Test CXX_COMPILER_SUPPORT_FLAG__Werror
-- Performing Test CXX_COMPILER_SUPPORT_FLAG__Werror - Success
-- Performing Test C_COMPILER_SUPPORT_FLAG__Wall
-- Performing Test C_COMPILER_SUPPORT_FLAG__Wall - Success
-- Performing Test CXX_COMPILER_SUPPORT_FLAG__Wall
-- Performing Test CXX_COMPILER_SUPPORT_FLAG__Wall - Success
-- Performing Test C_COMPILER_SUPPORT_FLAG__Wextra
-- Performing Test C_COMPILER_SUPPORT_FLAG__Wextra - Success
-- Performing Test CXX_COMPILER_SUPPORT_FLAG__Wextra
-- Performing Test CXX_COMPILER_SUPPORT_FLAG__Wextra - Success
-- Performing Test C_COMPILER_SUPPORT_FLAG__Wnon_virtual_dtor
-- Performing Test C_COMPILER_SUPPORT_FLAG__Wnon_virtual_dtor - Failed
-- Performing Test CXX_COMPILER_SUPPORT_FLAG__Wnon_virtual_dtor
-- Performing Test CXX_COMPILER_SUPPORT_FLAG__Wnon_virtual_dtor - Success
-- Performing Test C_COMPILER_SUPPORT_FLAG__Wdelete_non_virtual_dtor
-- Performing Test C_COMPILER_SUPPORT_FLAG__Wdelete_non_virtual_dtor - Failed
-- Performing Test CXX_COMPILER_SUPPORT_FLAG__Wdelete_non_virtual_dtor
-- Performing Test CXX_COMPILER_SUPPORT_FLAG__Wdelete_non_virtual_dtor - Success
-- Performing Test C_COMPILER_SUPPORT_FLAG__Wno_unused_parameter
-- Performing Test C_COMPILER_SUPPORT_FLAG__Wno_unused_parameter - Success
-- Performing Test CXX_COMPILER_SUPPORT_FLAG__Wno_unused_parameter
-- Performing Test CXX_COMPILER_SUPPORT_FLAG__Wno_unused_parameter - Success
-- Performing Test C_COMPILER_SUPPORT_FLAG__Wno_unused_function
-- Performing Test C_COMPILER_SUPPORT_FLAG__Wno_unused_function - Success
-- Performing Test CXX_COMPILER_SUPPORT_FLAG__Wno_unused_function
-- Performing Test CXX_COMPILER_SUPPORT_FLAG__Wno_unused_function - Success
-- Performing Test C_COMPILER_SUPPORT_FLAG__Wno_error_literal_suffix
-- Performing Test C_COMPILER_SUPPORT_FLAG__Wno_error_literal_suffix - Success
-- Performing Test CXX_COMPILER_SUPPORT_FLAG__Wno_error_literal_suffix
-- Performing Test CXX_COMPILER_SUPPORT_FLAG__Wno_error_literal_suffix - Success
-- Performing Test C_COMPILER_SUPPORT_FLAG__Wno_error_unused_local_typedefs
-- Performing Test C_COMPILER_SUPPORT_FLAG__Wno_error_unused_local_typedefs - Success
-- Performing Test CXX_COMPILER_SUPPORT_FLAG__Wno_error_unused_local_typedefs
-- Performing Test CXX_COMPILER_SUPPORT_FLAG__Wno_error_unused_local_typedefs - Success
-- Performing Test C_COMPILER_SUPPORT_FLAG__Wno_error_parentheses_equality
-- Performing Test C_COMPILER_SUPPORT_FLAG__Wno_error_parentheses_equality - Failed
-- Performing Test CXX_COMPILER_SUPPORT_FLAG__Wno_error_parentheses_equality
-- Performing Test CXX_COMPILER_SUPPORT_FLAG__Wno_error_parentheses_equality - Failed
-- Performing Test C_COMPILER_SUPPORT_FLAG__Wno_error_ignored_attributes
-- Performing Test C_COMPILER_SUPPORT_FLAG__Wno_error_ignored_attributes - Success
-- Performing Test CXX_COMPILER_SUPPORT_FLAG__Wno_error_ignored_attributes
-- Performing Test CXX_COMPILER_SUPPORT_FLAG__Wno_error_ignored_attributes - Success
-- Performing Test C_COMPILER_SUPPORT_FLAG__Wno_error_terminate
-- Performing Test C_COMPILER_SUPPORT_FLAG__Wno_error_terminate - Success
-- Performing Test CXX_COMPILER_SUPPORT_FLAG__Wno_error_terminate
-- Performing Test CXX_COMPILER_SUPPORT_FLAG__Wno_error_terminate - Success
-- Performing Test C_COMPILER_SUPPORT_FLAG__Wno_error_int_in_bool_context
-- Performing Test C_COMPILER_SUPPORT_FLAG__Wno_error_int_in_bool_context - Success
-- Performing Test CXX_COMPILER_SUPPORT_FLAG__Wno_error_int_in_bool_context
-- Performing Test CXX_COMPILER_SUPPORT_FLAG__Wno_error_int_in_bool_context - Success
-- Performing Test C_COMPILER_SUPPORT_FLAG__Wimplicit_fallthrough_0
-- Performing Test C_COMPILER_SUPPORT_FLAG__Wimplicit_fallthrough_0 - Success
-- Performing Test CXX_COMPILER_SUPPORT_FLAG__Wimplicit_fallthrough_0
-- Performing Test CXX_COMPILER_SUPPORT_FLAG__Wimplicit_fallthrough_0 - Success
-- Performing Test C_COMPILER_SUPPORT_FLAG__Wno_error_maybe_uninitialized
-- Performing Test C_COMPILER_SUPPORT_FLAG__Wno_error_maybe_uninitialized - Success
-- Performing Test CXX_COMPILER_SUPPORT_FLAG__Wno_error_maybe_uninitialized
-- Performing Test CXX_COMPILER_SUPPORT_FLAG__Wno_error_maybe_uninitialized - Success
-- Performing Test C_COMPILER_SUPPORT_FLAG__Wno_error_unused_function
-- Performing Test C_COMPILER_SUPPORT_FLAG__Wno_error_unused_function - Success
-- Performing Test C_COMPILER_SUPPORT_FLAG__Wno_error_array_bounds
-- Performing Test C_COMPILER_SUPPORT_FLAG__Wno_error_array_bounds - Success
-- Paddle version is 2.1.3
-- Compile with XPU!
-- On inference mode, will take place some specific optimization.
-- commit: 06d47ff7e2
-- branch: release/2.1
WITH_DLNNE:
-- Configuring incomplete, errors occurred!
See also "/home/kylin/Paddle/build/CMakeFiles/CMakeOutput.log".
See also "/home/kylin/Paddle/build/CMakeFiles/CMakeError.log".

**Comment by sljlp** [comment]
你好，请把build目录删掉重新执行cmake
如果还不行，请升级paddle到最新版本
