### ISSUE TITLE
GPU内存管理，我在用的时候确实有问题，而且也发现很多开发者也发现这个问题，你们的开发者应该用1000%的力量处理这个平台的GPU 管理

### ISSUE THREAD

**Issue by anthonyyuan** [PaddlePaddle/Paddle#36924]
欢迎您对PaddlePaddle提出建议，非常感谢您对PaddlePaddle的贡献！
在留下您的建议时，辛苦您同步提供如下信息：
- 版本、环境信息
1）PaddlePaddle版本：请提供您的PaddlePaddle版本号，例如1.1
2）CPU/GPU：您是否使用GPU进行训练，如是，请提供您的CUDA和cuDNN版本号
3）系统环境：请您描述系统类型、版本，例如Mac OS 10.14
注：您可以通过执行[summary_env.py](https://github.com/PaddlePaddle/Paddle/blob/develop/tools/summary_env.py)获取以上信息。
- 复现信息：如为报错，请给出复现环境、复现步骤
- 建议描述：请您详细描述，您认为需优化的功能

Thank you for contributing to PaddlePaddle.
Before submitting the issue, you could search issue in the github in case that there was a similar issue submitted or resolved before.
Please make sure that this is a feature request. 
**System information**
-PaddlePaddle version （eg.1.1）or CommitID
-CPU: including CPUMKL/OpenBlas/MKLDNN version
-GPU: including CUDA/CUDNN version
-OS Platform (eg.Mac OS 10.14)
Note: You can get most of the information by running [summary_env.py](https://github.com/PaddlePaddle/Paddle/blob/develop/tools/summary_env.py). 
**To Reproduce**
Steps to reproduce the behavior
**Describe the feature and the current behavior/state.**
**Any Other info.**

**Comment by anthonyyuan** [comment]
内存管理不可控制！！！！   PADDLE 2.1.3 。  用户无法控制预测循环后，内存的清除，内存一直缓慢上涨，

**Comment by FeixLiu** [comment]
您好，可以先搜索一下之前的issue，出现过相关的问题。比如 https://github.com/PaddlePaddle/Paddle/issues/26345 这个issue，您可以参考里面的解决办法。
如果还是无法解决，方便提供一下复现的代码环境吗

**Comment by Ligoml** [comment]
预测的时候，可以在预测代码前，加上 `with paddle.no_grad():` 然后进行预测试一下
