### ISSUE TITLE
AvgPool2D

### ISSUE THREAD

**Issue by HaitaoWuTJU** [PaddlePaddle/Paddle#36920]
paadle的AvgPool2D的exclusive参数默认与torch相反，对齐模型的坑
nn.AvgPool2D(exclusive=False,kernel_size=3, stride=2, padding=1)

**Comment by FeixLiu** [comment]
您好，您的反馈对产品非常有价值，我们内部会安排评估，未来有计划尽快回复。

**Comment by sljlp** [comment]
抱歉，这里的确是有所不同，我们正在调整
