### ISSUE TITLE
内存不断增大，爆掉显存

### ISSUE THREAD

**Issue by HaitaoWuTJU** [PaddlePaddle/Paddle#36921]
def extract_features(self,
                         input,
                         feature_layers=None):

        if feature_layers is None:
            feature_layers = ['14', '24', '34', '43']
        features = []
        result = input
        for (key, module) in self.feature_network.features._sub_layers.items():  # todo  _modules>_sub_layers
            result = module(result)
            if key in feature_layers:
                features.append(result)
        return features

**Comment by FeixLiu** [comment]
您好，麻烦您能提供一下更详细的问题描述么？

**Comment by sljlp** [comment]
你好，方便提供一下可复现问题的程序吗，我们排查一下问题
