### ISSUE TITLE
【菁英计划】paddle组合实现ToPILImage API的问题

### ISSUE THREAD

**Issue by yanchunyu71** [PaddlePaddle/Paddle#36928]
环境信息：paddlepaddle2.1.2
# 出错位置：super()函数
<img width="741" alt="截屏2021-11-02 下午2 48 17" src="https://user-images.githubusercontent.com/62750472/139799052-b4a82702-eb30-4cef-a58e-677fc43b8397.png">

**Comment by littletomatodonkey** [comment]
你好，感谢反馈，该问题已经在该pr中修复：https://github.com/PaddlePaddle/X2Paddle/pull/690
