### ISSUE TITLE
昇腾环境编译PaddlePaddle报错

### ISSUE THREAD

**Issue by zmh523262937** [PaddlePaddle/Paddle#36934]
为使您的问题得到快速解决，在建立Issue前，请您先通过如下方式搜索是否有相似问题:【搜索issue关键字】【使用labels筛选】【官方文档】

建立issue时，为快速解决问题，请您根据使用情况给出如下信息：
- 标题：请包含关键词“安装错误”/“编译错误”，例如“Mac编译错误”
- 版本、环境信息：
    1）PaddlePaddle版本：ascendrelease
    2）系统环境：昇腾 Centos7.4 , python 3.7

- 安装方式信息：
1）本地编译：
    cmake:cmake .. -DPY_VERSION=3 -DWITH_ASCEND=OFF -DPYTHON_EXECUTABLE=`which python3`  -DPYTHON_INCLUDE_DIR=`python3 -c "from distutils.sysconfig import get_python_inc; print(get_python_inc())"` -DWITH_ARM=ON -DWITH_ASCEND_CL=ON -DWITH_TESTING=ON -DCMAKE_BUILD_TYPE=Release -DON_INFER=ON -DWITH_XBYAK=OFF

  make : make TARGET=ARMV8 

问题：提示报错
![微信图片_20211102154635](https://user-images.githubusercontent.com/31687521/139806039-a8dbbce3-a80a-45c8-8561-325744cda84e.png)

**Comment by FeixLiu** [comment]
您好，方便提供一下报错信息么？

**Comment by FeixLiu** [comment]
您好，您可以尝试一下关闭编译选项中的`DWITH_ASCEND_CXX11`: `-DWITH_ASCEND_CXX11=OFF`。如未能解决还请继续反馈，谢谢。

**Comment by zmh523262937** [comment]
> 您好，您可以尝试一下关闭编译选项中的`DWITH_ASCEND_CXX11`: `-DWITH_ASCEND_CXX11=OFF`。如未能解决还请继续反馈，谢谢。

您好，谢谢答复，是需要重新cmake来指定选项吗

**Comment by FeixLiu** [comment]
> > 您好，您可以尝试一下关闭编译选项中的`DWITH_ASCEND_CXX11`: `-DWITH_ASCEND_CXX11=OFF`。如未能解决还请继续反馈，谢谢。
> 
> 您好，谢谢答复，是需要重新cmake来指定选项吗

是的

**Comment by zmh523262937** [comment]
> > > 您好，您可以尝试一下关闭编译选项中的`DWITH_ASCEND_CXX11`: `-DWITH_ASCEND_CXX11=OFF`。如未能解决还请继续反馈，谢谢。
> > 
> > 
> > 您好，谢谢答复，是需要重新cmake来指定选项吗
> 
> 是的

重新cmake之后，再重新make 依然提示这个报错

**Comment by FeixLiu** [comment]
您好，您可以尝试以下的编译选项：
```
cmake .. -DPY_VERSION=3 -DPYTHON_EXECUTABLE=`which python3` -DWITH_ARM=ON -DWITH_TESTING=ON -DCMAKE_BUILD_TYPE=release -DON_INFER=ON -DWITH_XBYAK=OFF -DWITH_ASCEND=OFF -DWITH_ASCEND_CL=ON -DWITH_PSCORE=OFF -DWITH_DISTRIBUTE=ON -DWITH_ASCEND_CXX11=OFF -DCMAKE_EXPORT_COMPILE_COMMANDS=ON
```

**Comment by FeixLiu** [comment]
另外，能麻烦提供一下具体的机器型号么。例如Ascend 的驱动版本，cann的版本，是x86的还是arm的，是centos的还是欧拉的系统？我们具体在定位一下问题。

**Comment by zmh523262937** [comment]
> 另外，能麻烦提供一下具体的机器型号么。例如Ascend 的驱动版本，cann的版本，是x86的还是arm的，是centos的还是欧拉的系统？我们具体在定位一下问题。

依然存在相同问题，运行脚本后输出的配置如下图
![image](https://user-images.githubusercontent.com/31687521/140845307-49a3fac8-395a-4156-a061-18ae227c6333.png)
是x86 centos7的机子  Ascend的驱动版本是21.0.2  cann版本是 5.0.2，机子用的是昇腾310

**Comment by zmh523262937** [comment]
方便加个微信实时通讯吗

**Comment by hong19860320** [comment]
想问下，你是需要用昇腾310进行推理部署吗？如果是，可以直接用paddle lite方式哈～ https://paddle-lite.readthedocs.io/zh/develop/demo_guides/huawei_ascend_npu.html#npu-paddle-lite

文档里面提供了预编译的demo，配置好环境后可以直接运行哦
