### ISSUE TITLE
question again on gradient_clipping_threshold

### ISSUE THREAD

**Issue by yu239** [PaddlePaddle/Paddle#3696]
In an old Issue #775 , there seemed to be some discussions on how the gradient clipping is triggered. Currently, on a single machine Paddle always uses SgdLocalUpdater. However, gradient clipping is only used in SgdThreadUpdater. Is there any plan to fix this issue? Or can we always use SgdThreadUpdater?

**Comment by lcy-seso** [comment]
I have the same problem. but it hasn't been solved yet ...

**Comment by lcy-seso** [comment]
Previously, I just changed ` SgdLocalUpdater` into `SgdThreadUpdater` and it worked, but I am not sure whether there may be certain problems.

**Comment by qingqing01** [comment]
@yu239  The v2 API always use `SgdThreadUpdater` and the `gradient_clipping` works well now. If you use `paddle_trainer` to run job, the `gradient_clipping` does work indeed.

**Comment by yu239** [comment]
@qingqing01 I use the class paddle::Trainer in the C++ code. It seems that SgdLocalUpdater is always used. So I can just change the Paddle source code (TrainerInternal.cpp) to use SgdThreadUpdater? Is there any potential issue by doing so?

**Comment by yu239** [comment]
@qingqing01 I can hack the source code so that SgdThreadUpdater is used in place of SgdLocalUpdater. But this does not seem like a final solution. If I use paddle::Trainer, is there any official way that I can specify SgdThreadUpdater without modifying the Paddle source code?
