### ISSUE TITLE
scatter

### ISSUE THREAD

**Issue by qdd1234** [PaddlePaddle/Paddle#36976]
torch中Tensor.scatter 和 paddle中的scatter功能是不是一样呢，我看二者参数不一样
![image](https://user-images.githubusercontent.com/68497831/140076457-f8b8960e-e165-4772-9b1d-46fae6af264e.png)
![image](https://user-images.githubusercontent.com/68497831/140076510-3b9ac3b9-4d7f-414d-8317-386d1d2a374d.png)

**Comment by zhaocaibei123** [comment]
功能类似，但实现不一样，参数也不一样，建议参考文档使用：
paddle：https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/scatter_cn.html
pytorch：https://pytorch.org/docs/stable/generated/torch.Tensor.scatter_.html#torch.Tensor.scatter_
