### ISSUE TITLE
Aistudio中的BML Codelab项目打包文件夹下载不下来

### ISSUE THREAD

**Issue by henryccl** [PaddlePaddle/Paddle#36983]
Aistudio中的BML Codelab模式创建的项目，在下载文件时，文件大于100M时就下载不下来了，总是下载失败，有什么办法可以解决吗？
![image](https://user-images.githubusercontent.com/44051761/140244955-0198c610-f9c4-43ff-9c61-348caf833174.png)
![image](https://user-images.githubusercontent.com/44051761/140245000-1c2e307a-0431-4e77-872b-1f4905cd366f.png)

**Comment by wuhuachaocoding** [comment]
您好，辛苦提供一下Aistudio的链接。

**Comment by henryccl** [comment]
emmm  是我自己写的项目，训练完后 想下载保存的权重（好几个模型一起打包下载），总是下载不下来，  也许是我的网路问题？ 我回头再试试，谢谢！

**Comment by zhgdglin** [comment]
你好我也是同样的问题，解决不了

**Comment by zhgdglin** [comment]
https://aistudio.baidu.com/bj-gpu-03/user/2721857/5313274/lab

**Comment by fengyanWang** [comment]
这个问题是不是没有解决？现在如何下载文件
