### ISSUE TITLE
paddle.where 与 torch.where, numpy.where 行为不一致

### ISSUE THREAD

**Issue by wgwang** [PaddlePaddle/Paddle#36992]
```python
# x is ndarray, shape=(m, n)
# torch
b = torch.tensor(x)
bnorm = torch.norm(b, p=2, dim=-1, keepdim=True)
bn = torch.where(bnorm>=1, b/bnorm, b)

# paddle报错，要求 condition 与 x、y 的 shape 一样。
a = paddle.to_tensor(x)
anorm = paddle.norm(a, p=2, axis=-1, keepdim=True)
an = paddle.where(anorm>=1, a/anorm, a)
```

不知道 paddle 能够有什么办法可以实现类似 torch.where 的效果？
另外，建议在下一个版本中，升级一下 where 函数，是的其行为与 numpy、torch 等一致。

**Comment by wgwang** [comment]
另外，paddle 的 tensor 不支持 bool tensor 的索引
比如：

```python

# x is ndarray, shape=(m, n)
# torch
b = torch.tensor(x)
bnorm = torch.norm(b, p=2, dim=-1, keepdim=True)
b[bnorm.flatten(), :] 


# paddle报错
a = paddle.to_tensor(x)
anorm = paddle.norm(a, p=2, axis=-1, keepdim=True)
a[anorm.flatten(), :] 


```

建议增加类似的 boolean tensor 索引的特性，以和 torch、numpy 相一致。
另：不知道 paddle 是否有类似的使用 boolean tensor 来索引的方法。

**Comment by windstamp** [comment]
> ```python
> # x is ndarray, shape=(m, n)
> # torch
> b = torch.tensor(x)
> bnorm = torch.norm(b, p=2, dim=-1, keepdim=True)
> bn = torch.where(bnorm>=1, b/bnorm, b)
> 
> # paddle报错，要求 condition 与 x、y 的 shape 一样。
> a = paddle.to_tensor(x)
> anorm = paddle.norm(a, p=2, axis=-1, keepdim=True)
> an = paddle.where(anorm>=1, a/anorm, a)
> ```
> 
> 不知道 paddle 能够有什么办法可以实现类似 torch.where 的效果？ 另外，建议在下一个版本中，升级一下 where 函数，是的其行为与 numpy、torch 等一致。

这个需求在 develop 分支和 2.2-rc 版本中已经支持了，可以参考 [PaddlePaddle 2.2.0-rc0 Release Note](https://github.com/PaddlePaddle/Paddle/releases/tag/v2.2.0-rc0)。

同时，2.2 正式版本将于近期发布，敬请关注。

本地基于 develop 分支复测了是可以的
<img width="707" alt="a7db43211dc91dfa2cff7163b8572eda" src="https://user-images.githubusercontent.com/34057289/140448025-82f2f18e-9a3c-4dbb-8a95-0793b8481f5a.png">

**Comment by windstamp** [comment]
> 另外，paddle 的 tensor 不支持 bool tensor 的索引 比如：
> 
> ```python
> # x is ndarray, shape=(m, n)
> # torch
> b = torch.tensor(x)
> bnorm = torch.norm(b, p=2, dim=-1, keepdim=True)
> b[bnorm.flatten(), :] 
> 
> 
> # paddle报错
> a = paddle.to_tensor(x)
> anorm = paddle.norm(a, p=2, axis=-1, keepdim=True)
> a[anorm.flatten(), :] 
> ```
> 
> 建议增加类似的 boolean tensor 索引的特性，以和 torch、numpy 相一致。 另：不知道 paddle 是否有类似的使用 boolean tensor 来索引的方法。

同上，这个需求在 develop 分支和 2.2-rc 版本中也已经支持了。

下列代码在 Paddle 上述版本和 Pytorch 功能一致
```
b = torch.tensor([[1,2],[3,4]])
print(b)
print(b[torch.tensor([[True,False],[False,True]])])

a = paddle.to_tensor([[1,2],[3,4]])
print(a)
print(a[paddle.to_tensor([[True,False],[False,True]])])
```

**Comment by HeQinWill** [comment]
+1🙋‍♂️
paddle 版本为: '2.2.2'
当原数组中有**空**数据时， paddle.where 对它不奏效，返回的结果仍为**空**，但是 np.where 和 torch.where 得到的结果均符合预期
```py
import numpy as np
import paddle
import torch

tmp_np = np.array([2.1, np.nan, 3.5, 4.9]).reshape([2, 2])
tmp_np
#[[2.1, nan       ],
# [3.5, 4.9]]

np.where(np.isnan(tmp_np), -1, tmp_np)
#[[2.1, -1.       ],
# [3.5, 4.9]]

tmp_paddle = paddle.to_tensor(tmp_np, dtype='float64')
paddle.where(paddle.isnan(tmp_paddle), paddle.to_tensor(-1, dtype='float64'), tmp_paddle)
#[[2.10000000, nan       ],
# [3.50000000, 4.90000000]]

tmp_torch = torch.from_numpy(tmp_np)
torch.where(torch.isnan(tmp_torch), torch.tensor(-1, dtype=torch.double), tmp_torch)
#[[ 2.1000, -1.0000],
# [ 3.5000,  4.9000]]
```
