### ISSUE TITLE
[Feature High priority] SPR 2+2+8 models AMX enabling and deployment

### ISSUE THREAD

**Issue by lidanqing-vv** [PaddlePaddle/Paddle#37005]
**Newest high priority model list from ligang, Green is highest priority.**

![image](https://user-images.githubusercontent.com/25713588/145352337-0f82036c-a5b3-45fc-96e9-27f349912656.png)

How to get the models：
**Detection model: Retinanet, faster-rcnn-r50-fpn**

#Clas
wget https://paddle-imagenet-models-name.bj.bcebos.com/dygraph/inference/PPLCNet_x1_0_infer.tar
wget https://paddle-imagenet-models-name.bj.bcebos.com/dygraph/inference/MobileNetV3_large_x1_0_infer.tar
wget https://paddle-imagenet-models-name.bj.bcebos.com/dygraph/inference/SwinTransformer_tiny_patch4_window7_224_infer.tar

# OCR
wget https://paddleocr.bj.bcebos.com/PP-OCRv2/chinese/ch_PP-OCRv2_det_infer.tar
wget https://paddleocr.bj.bcebos.com/PP-OCRv2/chinese/ch_PP-OCRv2_rec_infer.tar

# Seg
# Human Pose 512x512
wget https://paddleseg.bj.bcebos.com/dygraph/humanseg/export/deeplabv3p_resnet50_os8_humanseg_512x512_100k_with_softmax.zip
# Human Pose 192x192
https://paddleseg.bj.bcebos.com/dygraph/humanseg/export/fcn_hrnetw18_small_v1_humanseg_192x192_with_softmax.zip

# Matting model export
https://github.com/PaddlePaddle/PaddleSeg/blob/release/2.3/contrib/Matting/README_CN.md

# Detection
Need to set export resolution ratio (需要设置输出分辨率)
You can use these scripts and set exporting resolution ratio and export. (可以在PaddleDetection中用下面连接中的脚本，设置分辨率后导出)
 https://github.com/PaddlePaddle/PaddleDetection/blob/develop/deploy/EXPORT_MODEL_en.md

Picodet：https://github.com/PaddlePaddle/PaddleDetection/blob/develop/configs/picodet/README_cn.md
PP-YOLOv2：https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.3/configs/ppyolo/README_cn.md

**Comment by lidanqing-vv** [comment]
Related with https://github.com/PaddlePaddle/Paddle/issues/32282

**Comment by lidanqing-vv** [comment]
**Old models priority list from achun**

**PaddleDetection** repo models are sorted b**y priority from high to low** as follows:

ppyolov2_r50vd_dcn_365e_coco,
yolov3_darknet,
faster_rcnn_r50_fpn_1x_coco,
mask_rcnn_r50_fpn_1x_coco,
ssd_mobilenet_v1_300_120e_voc,
solov2_r50_fpn_1x_coco,


# OCR 模型中MKLDNN不支持的op

- [ ]  elementwise_add 【65】
- [x] nearest_interp_v2 【6】
- [x] elementwise_mul 【9】
- [x] squeeze2 【2】
- [ ] rnn 【2】

# Clas 模型中MKLDNN不支持的op

- [x] elementwise_add【463】
- [x] split【90】
- [x] elementwise_mul【45】
- [x] reshape2【28】
- [x] squeeze2【11】
- [x] flatten_contiguous_range【6】
- [x] slice【5】


# Det（只测试了Yolo） 模型中MKLDNN不支持的op
- [x] elementwise_add 【38】
- [x] expand_v2 【32】
- [x] elementwise_mul 【8】
- [x] nearest_interp_v2 【10】
- [ ] yolo_box 【10】
- [x] split 【3】
- [x] reshape2 【3】
- [x] slice 【9】
- [x] scale 【3】

# 汇总MKLDNN不支持的op

- [x] elementwise_add 【65】+ elementwise_add【463】+ elementwise_add 【38】
- [x] nearest_interp_v2 【6】+ nearest_interp_v2 【10】doable
- [x] elementwise_mul 【9】+ elementwise_mul【45】+ elementwise_mul 【8】
- [ ] squeeze2 【2】+ squeeze2【11】 doable
- [ ] rnn 【2】Need to look into doc
- [x] split【90】+ split 【3】Need investigation. 
- [ ] reshape2【28】+ reshape2 【3】It does not make sense to make for oneDNN. it does not work with block format. It only make sense to make oneDNN support when block format is supported
- [x] flatten_contiguous_range【6】
- [x] slice【5】+ slice 【9】
- [x] expand_v2 【32】
- [ ] yolo_box 【10】
- [x] scale 【3】Need investigation.

**Comment by lidanqing-vv** [comment]
@jczaja @wozna @sfraczek @jakpiase @zuzg Hi, I updated the int8 models that we need to generalize.
These models according to Ligang will be used by Baidu as SPR benchmark models. Need to start analysis from green labeled models.

**Comment by lidanqing-vv** [comment]
During generating quant-aware models, some conv ops surrounding head op should be skipped and not be quantized, as shown in following code
https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.3/ppdet/modeling/heads/mask_head.py#L145
If you received generated quant model, You can skip this comment and use quant model Baidu provided.

**Comment by lidanqing-vv** [comment]
Hi, I have important update. Recently we (mainly Tobin Guo) are asking baidu to list the priority levels of the models in the picture and we just got information from **Baidu PM Zihan that all these listed models in the picture and very high priority models** and Baidu would like to see performance boost of them on any Intel machines like SPR.

To deploy int8 models, here are quant models link
**ppyolov2_r50vd_dcn quant model**: https://paddledet.bj.bcebos.com/models/slim/ppyolov2_r50vd_dcn_qat.tar
**PP-Picodet picodet_m_416_coco**: https://jira.devtools.intel.com/browse/PADDLEQ-1719

**Comment by sfraczek** [comment]
> During generating quant-aware models, some conv ops surrounding head op should be skipped and not be quantized, as shown in following code https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.3/ppdet/modeling/heads/mask_head.py#L145 If you received generated quant model, just skip this comment.

Why do they have to be skipped?

**Comment by lidanqing-vv** [comment]
@sfraczek maybe I did not make it clear. Cause I thought training quant model with GPU and understand those changing instructions sometimes took a lot of time for us. Hence I feel if Baidu could provide us quant models directly, we can skip generating quant model ourselves that will save us a lot of time. But now it seems we need quant model with elementwise_mul or add quantized, so we may have to generate ourselves.
If you ask why some conv ops surrounding head op should be skipped, Baidu said if we quantize those conv ops, accuracy will get very bad even in quant models

**Comment by lidanqing-vv** [comment]
@yghstill Hi, guanghua, could you please generate following two quant models that has elementwise_mul quantized. Because we now support elemntwise_mul int8, and we found both following models have elementwise_mul and should both benefit from elementwise_mul int8 kernel in performance. Thank you very much !

**ppyolov2_r50vd_dcn quant model**: https://paddledet.bj.bcebos.com/models/slim/ppyolov2_r50vd_dcn_qat.tar
**PP-Picodet picodet_m_416_coco**: https://jira.devtools.intel.com/browse/PADDLEQ-1719 picodet_m_416_quant.tar

**Comment by yaomichael** [comment]
As agreed on 5/20 meeting, @baoachun and @jiangjiajun will arrange acceptance test on SPR, target to finish by end of May.

**Comment by lidanqing-vv** [comment]
@yaomichael Let's sync this table after we talked with Poland team and Baidu.

模型简称 | FP32 | BF16 | INT8 | Validation   reproduction sent? | Baidu Verified?
-- | -- | -- | -- | -- | --
PPLCNet_x1_0 | Y | Y |   | Y | N
MobileNetV3_large_x1_0 | Y |   | Y | Y | N
SwinTransformer_tiny_patch4_window7_224 |   |   |   |   |  
ch_PP-OCRv2_det | Y |   |   |   |  
ch_PP-OCRv2_rec | Y |   |   |   |  
ppyolov2_r50vd_dcn_365e_coco | Y |   | Y |   |  
PP-Picodet picodet_m_416_coco | Y |   | Y |   |  
PP-HumanSeg-Lite |   |   |   |   |  
PP-HumanMatting | Y |   |   |   |
