### ISSUE TITLE
关于 yolov3 loss 的实现

### ISSUE THREAD

**Issue by 670133189** [PaddlePaddle/Paddle#37014]
我参考了官方文档：https://www.paddlepaddle.org.cn/tutorials/projectdetail/2412195#anchor-31，文档建议我们使用【飞桨 paddle.vision.ops.yolo_loss API】，请教能否给全 yolov3 loss 的实现？因为文档提示【目前我们计算损失函数是在特征图 P0 的基础上进行的】、【因为有多尺度的检测，所以需要对上面的代码进行较大的修改，而且实现过程也略显繁琐，所以推荐大家直接使用飞桨 paddle.vision.ops.yolo_loss API】

**Comment by youth123** [comment]
您好，我帮您问下具体相关人员。

**Comment by youth123** [comment]
具体源码位置在paddle/fluid/operators/detection/yolov3_loss_op.h，这个文件实现了yolov3_loss的主体逻辑。

**Comment by 670133189** [comment]
> 具体源码位置在paddle/fluid/operators/detection/yolov3_loss_op.h，这个文件实现了yolov3_loss的主体逻辑。

有 python 版吗？paddle库yolov_loss函数**paddle/vision/ops.py**使用【helper.append_op】实现的，看不懂。

**Comment by youth123** [comment]
> > 具体源码位置在paddle/fluid/operators/detection/yolov3_loss_op.h，这个文件实现了yolov3_loss的主体逻辑。
> 
> 有 python 版吗？paddle库yolov_loss函数**paddle/vision/ops.py**使用【helper.append_op】实现的，看不懂。

python端只是实现了调用逻辑，具体算法逻辑还是由那个c++文件实现的。
