### ISSUE TITLE
使用AMP出现Found inf or nan, current scale is: 32768.0, decrease to: 32768.0*0.5的问题

### ISSUE THREAD

**Issue by henryccl** [PaddlePaddle/Paddle#37021]
当我使用自己魔改的Unet版本进行训练时出现了如下问题
Found inf or nan, current scale is: 32768.0, decrease to: 32768.0*0.5
![image](https://user-images.githubusercontent.com/44051761/140636875-31aba5cc-4d1d-4324-ab47-dc8db5f35517.png)

我检查之后发现，这句话不是我的代码打印的，我想这应该是我使用了AMP（自动混合精度）产生的打印结果。
同样的代码，当我使用正常的U-Net进行训练时，可以正常训练。
那么我想，这应该是由于我网络结构设计的不当导致的。
但是我想知道Found inf or nan, current scale is: 32768.0, decrease to: 32768.0*0.5这句话，到底意味着什么呢？他说的inf或者nan是指什么呢？是指我缩放后的损失吗？ 我检查了我的损失，发现损失一般在0.9附近（如上图所示），并没有nan，我检查了网络的输出，也没有nan。
做错了什么会导致Found inf or nan, current scale is: 32768.0, decrease to: 32768.0*0.5这类的问题出现呢？ 在设计网络结构时需要特别注意些什么吗？

**Comment by henryccl** [comment]
出现了Found inf or nan, current scale is: 32768.0, decrease to: 32768.0*0.5后，损失也不下降

**Comment by henryccl** [comment]
调用方式 如下
![image](https://user-images.githubusercontent.com/44051761/140637245-53fc8d2f-e80a-48dc-92e0-19055e294e76.png)

![image](https://user-images.githubusercontent.com/44051761/140637234-24d430be-48cc-4d61-8ec2-7fce17431ed1.png)

`

for i, batch in enumerate(data_loader):
    # measure data loading time
    data_time.update(time.perf_counter() - end)
    targets = batch["label"].cuda()
    inputs = batch["image"].cuda()
    patient_id = batch["patient_id"]
    
    with paddle.amp.auto_cast(enable=not no_fp16):
        # data augmentation step
        if mode == "train":
            inputs = data_aug(inputs)
        if deep_supervision:
            pass
        else:
            # 前向传播
            if mode == "train":
                segs = model(inputs)
                segs = data_aug.reverse(segs)
            loss_ = criterion(segs, targets)
    
    # compute gradient and do SGD step 更新参数
    if model.training:
        scaled = scaler.scale(loss_)  # scale the loss
        scaled.backward()  # do backward
        scaler.minimize(optimizer, scaled)  # update parameters
        optimizer.clear_grad()
        
`

**Comment by henryccl** [comment]
还是说paddle.amp.GradScaler的 init_loss_scaling 参数的设置有什么讲究吗？
![image](https://user-images.githubusercontent.com/44051761/140637615-4a3a6d5a-2cb4-473b-a567-5fd1fa618e95.png)

**Comment by GuoxiaWang** [comment]
@henryccl 

『Found inf or nan, current scale is: 32768.0, decrease to: 32768.00.5』

出现这个打印信息是因为使用了动态图 AMP 导致的，AMP的执行逻辑如下：
1）首先前向得到loss
2）对这个 loss 使用 scaler.scale(loss)，这在反向传播时会将梯度乘上一个 loss_scaling 的值
3）梯度做 allreduce 通信同步
4）梯度做 unscale and check nan/inf，具体是调用了 check_finite_and_unscale 函数
5）参数更新

出现打印信息，是因为在做 check_finite_and_unscale 时发现有 nan 或者 inf，此时说明当前的 loss_scaling 过大，然后会乘上预设的 decr_ratio，降低 loss_scaling 值，丢掉本轮step的梯度不进行更新，继续训练。

通常情况下，这个 loss_scaling 一直是动态调节的，以贪心策略尽量增大，直到遇到 有 nan 或者 inf 才会下降。如果持续下降，下降到0，进而导致 loss 出现nan，说明网络组网有不合适的地方，或者其他地方写错了，需要自己进一步排查。
