### ISSUE TITLE
编译paddle成功后，import paddle报错 Error: Can not import avx core while this file exists:/usr/local/python3.7.0/lib/python3.7/site-packages/paddle/fluid/core_avx.so

### ISSUE THREAD

**Issue by helen88** [PaddlePaddle/Paddle#37032]
>>> import paddle
grep: warning: GREP_OPTIONS is deprecated; please use an alias or script
Error: Can not import avx core while this file exists: /usr/local/python3.7.0/lib/python3.7/site-packages/paddle/fluid/core_avx.so
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/python3.7.0/lib/python3.7/site-packages/paddle/__init__.py", line 25, in <module>
    from .fluid import monkey_patch_variable
  File "/usr/local/python3.7.0/lib/python3.7/site-packages/paddle/fluid/__init__.py", line 36, in <module>
    from . import framework
  File "/usr/local/python3.7.0/lib/python3.7/site-packages/paddle/fluid/framework.py", line 37, in <module>
    from . import core
  File "/usr/local/python3.7.0/lib/python3.7/site-packages/paddle/fluid/core.py", line 294, in <module>
    raise e
  File "/usr/local/python3.7.0/lib/python3.7/site-packages/paddle/fluid/core.py", line 256, in <module>
    from .core_avx import *
ImportError: /usr/local/python3.7.0/lib/python3.7/site-packages/paddle/fluid/core_avx.so: ### undefined symbol: _ZN5baidu3xpu3api11sparse_adamIfEEiPNS1_7ContextEPKT_PKfS9_S7_S9_S9_S9_PfSA_PS5_fffiPKiiii

sparse_adam报错未定义，但so里都存在的呢：
libxpuapi.so是自己本地编译好的。
![image](https://user-images.githubusercontent.com/4593091/140704672-7866e13a-03f1-412b-84af-e3079cab57e7.png)

**Comment by helen88** [comment]
我的编译：
cmake .. -DPY_VERSION=3.7 \
         -DCMAKE_BUILD_TYPE=Release \
         -DWITH_GPU=OFF \
         -DWITH_XPU=ON \
         -DON_INFER=ON \
         -DWITH_PYTHON=ON \
         -DWITH_MKL=OFF \
         -DWITH_XPU_BKCL=ON \
         -DWITH_TESTING=ON
make -j40

**Comment by helen88** [comment]
![image](https://user-images.githubusercontent.com/4593091/140710998-dff18044-c1bc-44a2-90a9-86944cd33b8b.png)
nm -D -C /usr/local/python3.7.0/lib/python3.7/site-packages/paddle/fluid/core_avx.so  | grep " U " | grep sparse --col

**Comment by tongxin** [comment]
你这个可能是 xpu 相关 shared libraries 没有安装好，请参考下https://www.paddlepaddle.org.cn/documentation/docs/zh/guides/09_hardware_support/xpu_docs/paddle_install_cn.html

**Comment by tongxin** [comment]
先卸载一下安装的 paddlepaddle，再重新安装。
