### ISSUE TITLE
使用CPU训练时报错

### ISSUE THREAD

**Issue by yeguang1991** [PaddlePaddle/Paddle#37033]
![image](https://user-images.githubusercontent.com/66579493/140705842-e4e88a41-dfb5-4140-ae7a-4d1b72827179.png)
![image](https://user-images.githubusercontent.com/66579493/140705893-cd674e5b-3e38-42e7-a5d3-906799fa0d19.png)

**Comment by yeguang1991** [comment]
CPU训练中途报错 
Error: Tensor holds no memory. Call Tensor::mutable_data first.

**Comment by tongxin** [comment]
请提供复现方法，谢谢。

**Comment by yeguang1991** [comment]
> 请提供复现方法，谢谢。

我用的官方的PALM框架，跑的中文联合训练
https://github.com/PaddlePaddle/PALM/tree/master/examples/multi-task

**Comment by tongxin** [comment]
你好，我把问题转给负责的同学帮你看看。

**Comment by yeguang1991** [comment]
> 你好，我把问题转给负责的同学帮你看看。

她现在好像不负责这个了，我之前跟她联系过
