### ISSUE TITLE
paddle 是否支持 gpu + 同步训练 + 分布式的 embedding？

### ISSUE THREAD

**Issue by nrailg** [PaddlePaddle/Paddle#37038]
`paddle.fluid.layers.embedding` 可以分布式存储，但是支持 cpu：*is_distributed (bool) - 是否使用分布式的方式存储embedding矩阵，仅在多机分布式cpu训练中使用。*，而且这个 api 已经 deprecated。
https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/fluid/layers/embedding_cn.html

而 paddle 2 的 api `paddle.nn.embedding` 文档没 `is_distributed` 这个参数。请问是砍掉了这个 feature 么？
https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/nn/Embedding_cn.html

如果我需要分布式的 embedding + 同步训练 + gpu 应该怎么做呢？

**Comment by danleifeng** [comment]
paddle 2 的 api `paddle.static.nn.embedding` 中还包含 `is_distributed `这个参数哦，https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/static/nn/embedding_cn.html#embedding
你可以理解为`paddle.static.nn.embedding` 等价于`paddle.fluid.layers.embedding`这个旧接口。

**Comment by danleifeng** [comment]
如果需要分布式的 embedding + 同步训练 + gpu ，有两种场景：
1. 类似ernie/transformer模型中使用到的embedding，可参考https://github.com/PaddlePaddle/ERNIE/blob/ff89c2a6baef9fd662a5b847224ca39e67d6ad11/ernie/modeling_ernie.py#L327
2. 如果embedding的参数比较大，需要多卡存储，可以参考fleetx中的示例:https://fleet-x.readthedocs.io/en/latest/paddle_fleet_rst/parameter_server/performance/heterps.html#id6

**Comment by nrailg** [comment]
> 如果需要分布式的 embedding + 同步训练 + gpu ，有两种场景：
> 
> 1. 类似ernie/transformer模型中使用到的embedding，可参考https://github.com/PaddlePaddle/ERNIE/blob/ff89c2a6baef9fd662a5b847224ca39e67d6ad11/ernie/modeling_ernie.py#L327
> 2. 如果embedding的参数比较大，需要多卡存储，可以参考fleetx中的示例:https://fleet-x.readthedocs.io/en/latest/paddle_fleet_rst/parameter_server/performance/heterps.html#id6

感谢回复。

**Comment by nrailg** [comment]
> paddle 2 的 api `paddle.static.nn.embedding` 中还包含 `is_distributed `这个参数哦，https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/static/nn/embedding_cn.html#embedding 你可以理解为`paddle.static.nn.embedding` 等价于`paddle.fluid.layers.embedding`这个旧接口。

抱歉之前写错了，应该是 paddle.nn.embedding 没有 `is_distributed` 。
https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/nn/Embedding_cn.html

**Comment by tongxin** [comment]
> > paddle 2 的 api `paddle.static.nn.embedding` 中还包含 `is_distributed `这个参数哦，https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/static/nn/embedding_cn.html#embedding 你可以理解为`paddle.static.nn.embedding` 等价于`paddle.fluid.layers.embedding`这个旧接口。
> 
> 抱歉之前写错了，应该是 paddle.nn.embedding 没有 `is_distributed` 。 https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/nn/Embedding_cn.html

paddle.nn.embedding 的确没有 is_distributed 参数，请正确使用；）
