### ISSUE TITLE
单机多卡训练  相同代码相同batch-size，卡数增加以后速度反而变慢了

### ISSUE THREAD

**Issue by applezjm** [PaddlePaddle/Paddle#37045]
使用 paddle.distributed.launch 跑单机多卡的任务，都正常跑没问题。
但是在双卡时候，训练速度是1.6steps/sec，在8卡时，训练速度是0.3-0.4steps/sec
我理解同一套代码单机时候，速度应该一致啊，是什么导致了diff呢？

**Comment by tongxin** [comment]
请提供复现的代码和环境，谢谢。

**Comment by applezjm** [comment]
> 请提供复现的代码和环境，谢谢。

双卡：job-0bb617fae13b89a6
8卡：job-0bb61864febe02e9


<br class="Apple-interchange-newline">

<br class="Apple-interchange-newline">

**Comment by applezjm** [comment]
辛苦看下呢~

**Comment by sandyhouse** [comment]
如果分布式的话，本身会引入额外的通信开销（比如梯度同步），所以按照steps/s的速度计算，速度通常会小于单卡。但具体比当卡低多少是和通信/计算比相关的。

**Comment by sneaxiy** [comment]
@applezjm 能否提供下复现代码呢？我们这边测下。
