### ISSUE TITLE
ubuntu 编译Paddle2.2错误

### ISSUE THREAD

**Issue by Deo0330** [PaddlePaddle/Paddle#37058]
1）编译的PaddlePaddle版本：2.2
    2 ) 环境使用ai stuidio 项目提供的环境（PaddlePaddle 2.2.0rc, 32G V100GPU, ubuntu16.04, gcc 7.5.0, Python 3.7.4）
    参照官方提供的linux编译Paddle中的docker编译方法
    首先在第三方库的git clone时出现克隆失败，无法连接到github.com问题，通过更换githun源为gitee，不再跳出克隆失败的错误，但接着跳出了如下错误，编译停止。新手，请教可能是哪里出了问题？

`[ 15%] Building CUDA object paddle/fluid/operators/math/CMakeFiles/gru_compute.dir/gru_compute.cu.o
[ 15%] Built target sequence_pooling
/home/aistudio/Paddle/paddle/fluid/framework/tensor_util.cu(1): error: this declaration has no storage class or type specifier

/home/aistudio/Paddle/paddle/fluid/framework/tensor_util.cu(1): error: expected a ";"

2 errors detected in the compilation of "/tmp/tmpxft_0000156e_00000000-6_tensor_util.cpp1.ii".
paddle/fluid/framework/CMakeFiles/tensor.dir/build.make:75: recipe for target 'paddle/fluid/framework/CMakeFiles/tensor.dir/tensor_util.cu.o' failed
make[2]: *** [paddle/fluid/framework/CMakeFiles/tensor.dir/tensor_util.cu.o] Error 1
CMakeFiles/Makefile2:8355: recipe for target 'paddle/fluid/framework/CMakeFiles/tensor.dir/all' failed
make[1]: *** [paddle/fluid/framework/CMakeFiles/tensor.dir/all] Error 2
make[1]: *** 正在等待未完成的任务....
/usr/lib/gcc/x86_64-linux-gnu/7/include/avx512fintrin.h(1761): error: identifier "__builtin_ia32_sqrtsd_round" is undefined

/usr/lib/gcc/x86_64-linux-gnu/7/include/avx512fintrin.h(1770): error: identifier "__builtin_ia32_sqrtss_round" is undefined

/usr/lib/gcc/x86_64-linux-gnu/7/include/avx512fintrin.h(2728): error: identifier "__builtin_ia32_scalefsd_round" is undefined

/usr/lib/gcc/x86_64-linux-gnu/7/include/avx512fintrin.h(2737): error: identifier "__builtin_ia32_scalefss_round" is undefined

/usr/lib/gcc/x86_64-linux-gnu/7/include/avx512fintrin.h(11265): error: identifier "__builtin_ia32_scalefsd_round" is undefined

/usr/lib/gcc/x86_64-linux-gnu/7/include/avx512fintrin.h(11274): error: identifier "__builtin_ia32_scalefss_round" is undefined

/usr/lib/gcc/x86_64-linux-gnu/7/include/avx512dqintrin.h(1163): error: identifier "__builtin_ia32_reducesd" is undefined

/usr/lib/gcc/x86_64-linux-gnu/7/include/avx512dqintrin.h(1171): error: identifier "__builtin_ia32_reducess" is undefined

/usr/lib/gcc/x86_64-linux-gnu/7/include/avx512dqintrin.h(1179): error: identifier "__builtin_ia32_rangesd128_round" is undefined

/usr/lib/gcc/x86_64-linux-gnu/7/include/avx512dqintrin.h(1189): error: identifier "__builtin_ia32_rangess128_round" is undefined

/usr/lib/gcc/x86_64-linux-gnu/7/include/avx512dqintrin.h(1198): error: identifier "__builtin_ia32_rangesd128_round" is undefined

/usr/lib/gcc/x86_64-linux-gnu/7/include/avx512dqintrin.h(1207): error: identifier "__builtin_ia32_rangess128_round" is undefined

12 errors detected in the compilation of "/tmp/tmpxft_0000150e_00000000-6_lstm_compute.cpp1.ii".
paddle/fluid/operators/math/CMakeFiles/lstm_compute.dir/build.make:75: recipe for target 'paddle/fluid/operators/math/CMakeFiles/lstm_compute.dir/lstm_compute.cu.o' failed
make[2]: *** [paddle/fluid/operators/math/CMakeFiles/lstm_compute.dir/lstm_compute.cu.o] Error 1
CMakeFiles/Makefile2:85085: recipe for target 'paddle/fluid/operators/math/CMakeFiles/lstm_compute.dir/all' failed
make[1]: *** [paddle/fluid/operators/math/CMakeFiles/lstm_compute.dir/all] Error 2
/usr/lib/gcc/x86_64-linux-gnu/7/include/avx512fintrin.h(1761): error: identifier "__builtin_ia32_sqrtsd_round" is undefined

/usr/lib/gcc/x86_64-linux-gnu/7/include/avx512fintrin.h(1770): error: identifier "__builtin_ia32_sqrtss_round" is undefined

/usr/lib/gcc/x86_64-linux-gnu/7/include/avx512fintrin.h(2728): error: identifier "__builtin_ia32_scalefsd_round" is undefined

/usr/lib/gcc/x86_64-linux-gnu/7/include/avx512fintrin.h(2737): error: identifier "__builtin_ia32_scalefss_round" is undefined

/usr/lib/gcc/x86_64-linux-gnu/7/include/avx512fintrin.h(1761): error: identifier "__builtin_ia32_sqrtsd_round" is undefined

/usr/lib/gcc/x86_64-linux-gnu/7/include/avx512fintrin.h(1770): error: identifier "__builtin_ia32_sqrtss_round" is undefined

/usr/lib/gcc/x86_64-linux-gnu/7/include/avx512fintrin.h(2728): error: identifier "__builtin_ia32_scalefsd_round" is undefined

/usr/lib/gcc/x86_64-linux-gnu/7/include/avx512fintrin.h(2737): error: identifier "__builtin_ia32_scalefss_round" is undefined

/usr/lib/gcc/x86_64-linux-gnu/7/include/avx512fintrin.h(11265): error: identifier "__builtin_ia32_scalefsd_round" is undefined

/usr/lib/gcc/x86_64-linux-gnu/7/include/avx512fintrin.h(11274): error: identifier "__builtin_ia32_scalefss_round" is undefined

/usr/lib/gcc/x86_64-linux-gnu/7/include/avx512fintrin.h(11265): error: identifier "__builtin_ia32_scalefsd_round" is undefined

/usr/lib/gcc/x86_64-linux-gnu/7/include/avx512fintrin.h(11274): error: identifier "__builtin_ia32_scalefss_round" is undefined

/usr/lib/gcc/x86_64-linux-gnu/7/include/avx512dqintrin.h(1163): error: identifier "__builtin_ia32_reducesd" is undefined

/usr/lib/gcc/x86_64-linux-gnu/7/include/avx512dqintrin.h(1171): error: identifier "__builtin_ia32_reducess" is undefined

/usr/lib/gcc/x86_64-linux-gnu/7/include/avx512dqintrin.h(1179): error: identifier "__builtin_ia32_rangesd128_round" is undefined

/usr/lib/gcc/x86_64-linux-gnu/7/include/avx512dqintrin.h(1189): error: identifier "__builtin_ia32_rangess128_round" is undefined

/usr/lib/gcc/x86_64-linux-gnu/7/include/avx512dqintrin.h(1198): error: identifier "__builtin_ia32_rangesd128_round" is undefined

/usr/lib/gcc/x86_64-linux-gnu/7/include/avx512dqintrin.h(1207): error: identifier "__builtin_ia32_rangess128_round" is undefined

/usr/lib/gcc/x86_64-linux-gnu/7/include/avx512dqintrin.h(1163): error: identifier "__builtin_ia32_reducesd" is undefined

/usr/lib/gcc/x86_64-linux-gnu/7/include/avx512dqintrin.h(1171): error: identifier "__builtin_ia32_reducess" is undefined

/usr/lib/gcc/x86_64-linux-gnu/7/include/avx512dqintrin.h(1179): error: identifier "__builtin_ia32_rangesd128_round" is undefined

/usr/lib/gcc/x86_64-linux-gnu/7/include/avx512dqintrin.h(1189): error: identifier "__builtin_ia32_rangess128_round" is undefined

/usr/lib/gcc/x86_64-linux-gnu/7/include/avx512dqintrin.h(1198): error: identifier "__builtin_ia32_rangesd128_round" is undefined

/usr/lib/gcc/x86_64-linux-gnu/7/include/avx512dqintrin.h(1207): error: identifier "__builtin_ia32_rangess128_round" is undefined

12 errors detected in the compilation of "/tmp/tmpxft_000015a0_00000000-6_gru_compute.cpp1.ii".
paddle/fluid/operators/math/CMakeFiles/gru_compute.dir/build.make:75: recipe for target 'paddle/fluid/operators/math/CMakeFiles/gru_compute.dir/gru_compute.cu.o' failed
make[2]: *** [paddle/fluid/operators/math/CMakeFiles/gru_compute.dir/gru_compute.cu.o] Error 1
CMakeFiles/Makefile2:84904: recipe for target 'paddle/fluid/operators/math/CMakeFiles/gru_compute.dir/all' failed
make[1]: *** [paddle/fluid/operators/math/CMakeFiles/gru_compute.dir/all] Error 2
12 errors detected in the compilation of "/tmp/tmpxft_00001599_00000000-6_softmax.cpp1.ii".
paddle/fluid/operators/math/CMakeFiles/softmax.dir/build.make:75: recipe for target 'paddle/fluid/operators/math/CMakeFiles/softmax.dir/softmax.cu.o' failed
make[2]: *** [paddle/fluid/operators/math/CMakeFiles/softmax.dir/softmax.cu.o] Error 1
CMakeFiles/Makefile2:85184: recipe for target 'paddle/fluid/operators/math/CMakeFiles/softmax.dir/all' failed
make[1]: *** [paddle/fluid/operators/math/CMakeFiles/softmax.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2`

**Comment by liutiexing** [comment]
您好，找不到的文件是编译器（gcc）对SIMD（单指令多数据）指令集（AVX）的封装，这些头文件是gcc的一部分。Paddle使用这些文件支持CPU场景下的算子实现。
Paddle支持4.8.2以上，建议使用8.2.0。但没有用gcc7.5测试过。你可以在本机的gcc目录下使用find搜索这些文件，看能否找到。
另外，因为编译依赖众多，且github还有封锁问题，建议您使用官网的docker，docker已经把环境弄好了。
如果坚持使用源代码编译，建议使用GCC 8.2
