### ISSUE TITLE
建议Paddle.metric添加对于多标签分类的指标

### ISSUE THREAD

**Issue by skpig** [PaddlePaddle/Paddle#37057]
我注意到现在的Paddle.metric中Precision & Recall指标都只能进行二分类。多标签分类问题是相当普遍的，具体的接口样例可见sklearn（https://scikit-learn.org/stable/modules/generated/sklearn.metrics.precision_score.html#sklearn.metrics.precision_score ）。
社区是否有打算进行实现？如果有意愿的话，我愿意尝试提交PR实现该API。

**Comment by liutiexing** [comment]
我们收到了您的建议，我们内部评估一下，再给您回复

**Comment by TCChenlong** [comment]
你好，我们非常欢迎你提相关的功能PR，期间有任何问题都可以联系我~

**Comment by skpig** [comment]
@TCChenlong 您好，我现在考虑的是在metric中实现一个新类，维护一个混淆矩阵，根据用户的需要，在`compute()`中返回对应的指标或者返回全部的指标。过去的precision, recall的类相当于是分别维护混淆矩阵。至于具体的multi-labels的参数，我会基本按照sklearn中参数来写。您看这样可以吗？

**Comment by TCChenlong** [comment]
嗯嗯 可以的~
