### ISSUE TITLE
Build will fail using cmake version older than 3.5

### ISSUE THREAD

**Issue by typhoonzero** [PaddlePaddle/Paddle#3706]
I used cmake 3.2 to compile and then got an error with unpacking `libprotobuf.so` with `ar`. Using cmake 3.5 doesn't seems to have such problem.

**Comment by luotao1** [comment]
@typhoonzero 
Both @Xreki and I can use cmake 3.2.2 to build sucessfully. And why cmake should > 3.5 in  http://www.paddlepaddle.org/docs/develop/documentation/zh/getstarted/build_and_install/build_from_source_cn.html#compile-deps

**Comment by Xreki** [comment]
I think it is not a problem of the current version, because `libprotobuf.a` will be built always and no need to unpack `libprotobuf.so`. And I also use cmake 3.2.2 daily.

**Comment by luotao1** [comment]
Thus, shoud we update the build_from_source document?
