### ISSUE TITLE
BERT performance drop

### ISSUE THREAD

**Issue by pmajchrzak** [PaddlePaddle/Paddle#37075]
Commit https://github.com/PaddlePaddle/Paddle/commit/b9fdd3bc0f4f22af17a81bb8a50a337b563c876b seems to be responsible for the decline in the BERT's performance. Depending on the machine on which the tests were performed, the decrease ranges from 2.66% to 3.21%. Below are the screenshots of the sheets with the results of consecutive commits together with the fps results for three processors
### CLX processor:
```           Turbo: OFF
            Name: Intel(R) Xeon(R) Gold 6248 CPU @ 2.50GHz
           Model: 85
          Family: 6
         Sockets: 2
Cores per socket: 20
Threads per core: 2
     CPU MHx min: 1000.0000
     CPU MHx max: 3900.0000
       cache L1d: 32K
       cache L1i: 32K
        cache L2: 1024K
        cache L3: 28160K
```
#### results:
![CLX](https://user-images.githubusercontent.com/10847947/140922188-893a209b-f1da-4837-bfb5-9558466fed5e.png)
---
### CPX processor:
```
Turbo: OFF
            Name: Intel(R) d on(R) Gold 6348H CPU @ 2.30GHz
           Model: 85
          Family: 6
         Sockets: 4
Cores per socket: 24
Threads per core: 2
     CPU MHx min: 1000.0000
     CPU MHx max: 4200.0000
       cache L1d: 32K
       cache L1i: 32K
        cache L2: 1024K
        cache L3: 33792K
```
#### results:
![CPX](https://user-images.githubusercontent.com/10847947/140922195-27939040-d07a-495e-9b15-ca25def91365.png)
---
### SKX processor
```
Turbo: OFF
            Name: Intel(R) Xeon(R) Platinum 8180 CPU @ 2.50GHz
           Model: 85
          Family: 6
         Sockets: 2
Cores per socket: 28
Threads per core: 2
     CPU MHx min: 1000.0000
     CPU MHx max: 3800.0000
       cache L1d: 32K
       cache L1i: 32K
        cache L2: 1024K
        cache L3: 39424K
```
#### results:
![SKX](https://user-images.githubusercontent.com/10847947/140922199-45db2619-d315-41cf-96d8-be418e9ea95c.png)
---
### CMAKE parameters:
```
-DCMAKE_BUILD_TYPE=Release -DWITH_GPU=OFF -DWITH_MKLDNN=ON -DWITH_TESTING=ON -DWITH_PROFILER=OFF -DWITH_STYLE_CHECK=OFF -DON_INFER=ON -DWITH_INFERENCE_API_TEST=ON -DPY_VERSION=3.6
```
### Test run command:
```
/repos/paddle_paddle/build/paddle/fluid/inference/tests/api/test_analyzer_bert --gtest_filter=Analyzer_bert.profile --cpu_num_threads=1 --repeat=1000 -use_mkldnn=true --infer_data=/repos/paddle_paddle/build/third_party/inference_demo/bert_emb128/data.txt  --batch_size=1    --infer_model=/repos/paddle_paddle/build/third_party/inference_demo/bert_emb128/model
```

**Comment by pmajchrzak** [comment]
@baoachun , could you please take look at this?

**Comment by baoachun** [comment]
@pmajchrzak, Got it, I will follow up on the problem.

**Comment by baoachun** [comment]
@pmajchrzak Chould you please give me the most recent inference performance table?

**Comment by pmajchrzak** [comment]
## Of course,
I will present the data from only one machine - similar drops can be observed on the others.

The latest measurements show that there have been two consecutive performance drops.
1: https://github.com/PaddlePaddle/Paddle/commit/b9fdd3bc0f4f22af17a81bb8a50a337b563c876b
2: https://github.com/PaddlePaddle/Paddle/commit/b628c316148b072b73b38a6820c5328b4a782c79
3: https://github.com/PaddlePaddle/Paddle/commit/feda7c1d678c87562190db0b790d0eae02d3b98e

## All declines are marked with arrows in the attached tables and graphs


### 1
![image](https://user-images.githubusercontent.com/10847947/144583564-c060bc51-cd97-4e1b-915f-426635a814cf.png)

### 2
![image](https://user-images.githubusercontent.com/10847947/144584074-77373ef2-3590-46ea-9934-4c48eb6440fe.png)

### 3
![image](https://user-images.githubusercontent.com/10847947/144584521-6d85a636-2423-4547-84e8-9b850a09ff6b.png)


## Most recent values
![image](https://user-images.githubusercontent.com/10847947/144584704-718bfa16-f6d9-430e-89b9-c29790c65f16.png)

**Comment by lidanqing-vv** [comment]
Hi, @pmajchrzak thank you so much for so well marked picture ! The testing machine is CLX right? So that Baidu could reproduce it on CLX machine (Like 6271, 6248)

**Comment by pmajchrzak** [comment]
>The testing machine is CLX right? So that Baidu could reproduce it on CLX machine (Like 6271, 6248)

The most recent values presented were performed on the CLX machine, but such drop steps are observed on SKX and CPX also.

**Comment by yaomichael** [comment]
notes from 5/20 meeting (same as #40381 )

BERT may have been disabled accidently during a restructure. @jiangjiajun is confirming this and bring BERT back accordingly.
