### ISSUE TITLE
OSError: (External)  Cudnn error, CUDNN_STATUS_MAPPING_ERROR

### ISSUE THREAD

**Issue by henryccl** [PaddlePaddle/Paddle#37095]
我在使用aistiaistudio运行自己的项目时出现了如下问题（我事先是在win10上的环境测试过的， 前向传播没问题）
`!python -m src.train --devices 0 --width 48 --arch Unet_bicebce`
![image](https://user-images.githubusercontent.com/44051761/141081370-ff98090b-6231-450b-a663-ad5ef5c66152.png)
然后我把网络结构这部分代码单独拿出来跑 ， 发现也没问题， 可以正常运行
`!python -m src.test`
![image](https://user-images.githubusercontent.com/44051761/141081184-9630fd92-b8cd-4c33-8bc3-2135c665dd95.png)

**Comment by henryccl** [comment]
aistudio链接如下：
`项目“test”共享链接(有效期三天)：https://aistudio.baidu.com/studio/project/partial/verify/2604597/02f15b1544454d5498d109cf52337259`

**Comment by jim19930609** [comment]
目前已基本锁定问题来源于Conv3DTranspose在特定输入形状下会报错。
之前src.test能通过的原因是因为输入形状为[2, 128, 64, 64, 64]，改成和训练一致的[4, 128, 64, 64, 64]会出错。已联系相关同事跟进

Bug复现代码：

import paddle

x= paddle.randn([4, 128, 64, 64, 64])
layer = paddle.nn.Conv3DTranspose(128, 128, 2, 2, 0, 0, bias_attr=False)
out = layer(x)

**Comment by jerrywgz** [comment]
建议使用新版本paddle，目前验证在新版本paddle上复现代码是能正常运行的
