### ISSUE TITLE
复现 cuda问题

### ISSUE THREAD

**Issue by ethelgriffin** [PaddlePaddle/Paddle#37105]
torch原代码：
args.cuda = not args.no_cuda and torch.cuda.is_available()
torch.manual_seed(args.seed)
if args.cuda:
    torch.cuda.manual_seed(args.seed)
    torch.cuda.set_device(args.gpu)
else:
    args.gpu = None
kwargs = {'num_workers': 0, 'pin_memory': True} if args.cuda else {}

paddle复现：
paddle.seed(args.seed)
use_gpu = True
if use_gpu:
    paddle.seed(args.seed)
    paddle.set_device(use_gpu)
else:
    args.gpu = None
kwargs = {'num_workers': 0, 'pin_memory': True} if use_gpu else {}

报错：---------------------------------------------------------------------------AttributeError                            Traceback (most recent call last)/tmp/ipykernel_104/2624764942.py in <module>
     53 if use_gpu:
     54     paddle.seed(args.seed)
---> 55     paddle.set_device(use_gpu)
     56 else:
     57     args.gpu = None
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/device.py in set_device(device)
    184         data = paddle.stack([x1,x2], axis=1)
    185     """
--> 186     place = _convert_to_place(device)
    187     framework._set_expected_place(place)
    188     return place
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/device.py in _convert_to_place(device)
    119 
    120 def _convert_to_place(device):
--> 121     lower_device = device.lower()
    122     if lower_device == 'cpu':
    123         place = core.CPUPlace()
AttributeError: 'bool' object has no attribute 'lower'

请问怎样修改？

**Comment by jim19930609** [comment]
主要原因出在paddle.set_device()接口，需要传入字符串。可以参考：https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/device/set_device_cn.html#set-device

按照你的思路修改了一下Paddle部分，亲测可以跑通。看能不能解决你的问题：

import paddle
import numpy as np

class Args:
    def __init__(self):
        self.use_gpu = True
        self.seed = 2022

args = Args()

if __name__ == "__main__":
    paddle.seed(args.seed)
    use_gpu = True
    if use_gpu:
        paddle.seed(args.seed)
        paddle.set_device("gpu:0")
    else:
        args.gpu = None
        kwargs = {'num_workers': 0, 'pin_memory': True} if use_gpu else {}
