### ISSUE TITLE
复现 接口问题

### ISSUE THREAD

**Issue by ethelgriffin** [PaddlePaddle/Paddle#37108]
from torch.autograd import Variable
求问torch中的 torch.autograd.variable的paddle接口。

    images, labels = Variable(data[0]), Variable(data[1])

**Comment by ethelgriffin** [comment]
如果直接用 tensor代替Variable 

 images, labels = Variable(data[0]), Variable(data[1])
就会出现报错
/tmp/ipykernel_607/3071374129.py in train(epoch)
    111     for batch_idx, data in enumerate(train_loader):
    112 
--> 113         images, labels = Variable(data[0]), Variable(data[1])
    114         if args.cuda:
    115             images, labels = images.cuda(), labels.cuda()
TypeError: 'module' object is not callable

**Comment by chenjiyan2001** [comment]
同问
