### ISSUE TITLE
多机多卡无法运行任务，报错：AssertionError: Can't find your local ip {127.0.0.1} in node_ips: {['192.168.50.191', '192.168.50.190']}

### ISSUE THREAD

**Issue by poetryben88** [PaddlePaddle/Paddle#37116]
- 标题：2机4卡，运行示例程序train_fleet_static.py，报错。
- 版本、环境信息：
    1）PaddlePaddle版本：2.2.0
    2）CPU：
    3）GPU：RTX2080 *4*2
    4）系统环境：ubuntu 18.04，python 3.6
- 训练信息
    1）多机，多卡
    2）显存信息 12GB*4*2
    3）Operator信息
- 复现信息：如为报错，请给出复现环境、复现步骤
- 问题描述：运行示例程序train_fleet_static.py，报错。

$ **python3 -m paddle.distributed.launch --ips="192.168.50.191,192.168.50.190" --gpus=0,1,2,3,4,5,6,7  train_fleet_static.py**
-----------  Configuration Arguments -----------
backend: auto
elastic_server: None
force: False
gpus: 0,1,2,3,4,5,6,7
heter_worker_num: None
heter_workers:
host: None
http_port: None
ips: 192.168.50.191,192.168.50.190
job_id: None
log_dir: log
np: None
nproc_per_node: None
run_mode: None
scale: 0
server_num: None
servers:
training_script: train_fleet_static.py
training_script_args: []
worker_num: None
workers:
------------------------------------------------
INFO 2021-11-11 11:36:44,253 launch.py:402] Run collective mode. gpu arguments:['--ips'], cuda count:4
launch train in GPU mode!
Traceback (most recent call last):
  File "/home/xubaishuai/anaconda3/envs/paddle_env/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/xubaishuai/anaconda3/envs/paddle_env/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/xubaishuai/anaconda3/envs/paddle_env/lib/python3.6/site-packages/paddle/distributed/launch.py", line 16, in <module>
    launch.launch()
  File "/home/xubaishuai/anaconda3/envs/paddle_env/lib/python3.6/site-packages/paddle/distributed/fleet/launch.py", line 615, in launch
    launch_collective(args)
  File "/home/xubaishuai/anaconda3/envs/paddle_env/lib/python3.6/site-packages/paddle/distributed/fleet/launch.py", line 277, in launch_collective
    devices_per_proc)
  File "/home/xubaishuai/anaconda3/envs/paddle_env/lib/python3.6/site-packages/paddle/distributed/fleet/launch.py", line 210, in get_cluster_from_args
    % (node_ip, node_ips)
**AssertionError: Can't find your local ip {127.0.0.1} in node_ips: {['192.168.50.191', '192.168.50.190']}**

更改命令，IP地址改成127.0.0.1，依然报错：

$ python3 -m paddle.distributed.launch --ips="127.0.0.1,192.168.50.190" --gpus=0,1,2,3,4,5,6,7  train_fleet_static.py
-----------  Configuration Arguments -----------
backend: auto
elastic_server: None
force: False
gpus: 0,1,2,3,4,5,6,7
heter_worker_num: None
heter_workers:
host: None
http_port: None
ips: 127.0.0.1,192.168.50.190
job_id: None
log_dir: log
np: None
nproc_per_node: None
run_mode: None
scale: 0
server_num: None
servers:
training_script: train_fleet_static.py
training_script_args: []
worker_num: None
workers:
------------------------------------------------
INFO 2021-11-11 11:46:40,863 launch.py:402] Run collective mode. gpu arguments:['--ips'], cuda count:4
launch train in GPU mode!
INFO 2021-11-11 11:46:40,865 launch_utils.py:528] Local start 8 processes. First process distributed environment info (Only For Debug):
    +=======================================================================================+
    |                        Distributed Envs                      Value                    |
    +---------------------------------------------------------------------------------------+
    |                       PADDLE_TRAINER_ID                        0                      |
    |                 PADDLE_CURRENT_ENDPOINT                 127.0.0.1:6070                |
    |                     PADDLE_TRAINERS_NUM                       16                      |
    |                PADDLE_TRAINER_ENDPOINTS  ... 5,192.168.50.190:6076,192.168.50.190:6077|
    |                     PADDLE_RANK_IN_NODE                        0                      |
    |                 PADDLE_LOCAL_DEVICE_IDS                        0                      |
    |                 PADDLE_WORLD_DEVICE_IDS         0,1,2,3,4,5,6,7,0,1,2,3,4,5,6,7       |
    |                     FLAGS_selected_gpus                        0                      |
    |             FLAGS_selected_accelerators                        0                      |
    +=======================================================================================+

INFO 2021-11-11 11:46:40,865 launch_utils.py:531] details abouts PADDLE_TRAINER_ENDPOINTS can be found in log/endpoints.log, and detail running logs maybe found in log/workerlog.0
launch proc_id:4893 idx:0
launch proc_id:4898 idx:1
launch proc_id:4904 idx:2
launch proc_id:4909 idx:3
launch proc_id:4914 idx:4
launch proc_id:4919 idx:5
launch proc_id:4924 idx:6
launch proc_id:4929 idx:7
Start collective training example:
Run on CUDAPlace(0).
server not ready, wait 3 sec to retry...
not ready endpoints:['127.0.0.1:6071', '127.0.0.1:6072', '127.0.0.1:6073', '127.0.0.1:6074', '127.0.0.1:6075', '127.0.0.1:6076', '127.0.0.1:6077', '192.168.50.190:6070', '192.168.50.190:6071', '192.168.50.190:6072', '192.168.50.190:6073', '192.168.50.190:6074', '192.168.50.190:6075', '192.168.50.190:6076', '192.168.50.190:6077']
INFO 2021-11-11 11:46:43,978 launch_utils.py:319] terminate process group gid:4893
INFO 2021-11-11 11:46:43,978 launch_utils.py:319] terminate process group gid:4898
INFO 2021-11-11 11:46:43,978 launch_utils.py:319] terminate process group gid:4904
INFO 2021-11-11 11:46:43,978 launch_utils.py:319] terminate process group gid:4909
INFO 2021-11-11 11:46:47,983 launch_utils.py:340] terminate all the procs
ERROR 2021-11-11 11:46:47,983 launch_utils.py:603] ABORT!!! Out of all 16 trainers, the trainer process with rank=[4, 5, 6, 7] was aborted. Please check its log.
INFO 2021-11-11 11:46:51,987 launch_utils.py:340] terminate all the procs
INFO 2021-11-11 11:46:51,988 launch.py:304] Local processes completed.

**Comment by zhangbo9674** [comment]
问题已经收到，正在分析。

**Comment by zhangbo9674** [comment]
您好，报错信息需要复现代码，麻烦提供一下复现代码。
脚本参数--gpus换成”--gpus=0,1,2,3,4”尝试一下可以运行么？

**Comment by poetryben88** [comment]
INFO 2021-11-11 14:28:03,192 launch_utils.py:531] details abouts PADDLE_TRAINER_ENDPOINTS can be found in log/endpoints.log, and detail running logs maybe found in log/workerlog.0
launch proc_id:32410 idx:0
launch proc_id:32415 idx:1
launch proc_id:32420 idx:2
launch proc_id:32428 idx:3
launch proc_id:32433 idx:4
Start collective training example:
Run on CUDAPlace(0).
server not ready, wait 3 sec to retry...
not ready endpoints:['127.0.0.1:6071', '127.0.0.1:6072', '127.0.0.1:6073', '127.0.0.1:6074', '192.168.50.190:6070', '192.168.50.190:6071', '192.168.50.190:6072', '192.168.50.190:6073', '192.168.50.190:6074']
INFO 2021-11-11 14:28:06,261 launch_utils.py:319] terminate process group gid:32410
INFO 2021-11-11 14:28:06,262 launch_utils.py:319] terminate process group gid:32415
INFO 2021-11-11 14:28:06,262 launch_utils.py:319] terminate process group gid:32420
INFO 2021-11-11 14:28:06,262 launch_utils.py:319] terminate process group gid:32428
INFO 2021-11-11 14:28:10,266 launch_utils.py:340] terminate all the procs
ERROR 2021-11-11 14:28:10,267 launch_utils.py:603] ABORT!!! Out of all 10 trainers, the trainer process with rank=[4] was aborted. Please check its log.
INFO 2021-11-11 14:28:14,270 launch_utils.py:340] terminate all the procs
INFO 2021-11-11 14:28:14,271 launch.py:304] Local processes completed.


还是一样的结果。

**Comment by zhangbo9674** [comment]
您好，感谢反馈，需要麻烦提供一下对应卡的日志，比如workerlog.4[5,6,7]

**Comment by poetryben88** [comment]
launch proc_id:2411 idx:0
launch proc_id:2416 idx:1
launch proc_id:2421 idx:2
launch proc_id:2426 idx:3
Start collective training example:
Run on CUDAPlace(0).
server not ready, wait 3 sec to retry...
not ready endpoints:['127.0.0.1:40365', '127.0.0.1:59789', '127.0.0.1:55695']
Execute startup program.
W1111 14:29:25.490671  2411 device_context.cc:447] Please NOTE: device: 0, GPU Compute Capability: 7.5, Driver API Version: 11.4, Runtime API Version: 10.2
W1111 14:29:25.494096  2411 device_context.cc:465] device: 0, cuDNN Version: 7.6.
W1111 14:29:29.710743  2411 fuse_all_reduce_op_pass.cc:76] Find all_reduce operators: 161. To make the speed faster, some all_reduce ops are fused during training, after fusion, the number of all_reduce ops is 5.
[Epoch 0, batch 0] loss: 0.26929, acc1: 0.00000, acc5: 0.03125
[Epoch 0, batch 5] loss: 0.19178, acc1: 0.03125, acc5: 0.06250
[Epoch 0, batch 10] loss: 0.00000, acc1: 0.00000, acc5: 0.00000
[Epoch 0, batch 15] loss: 75.75318, acc1: 0.00000, acc5: 0.00000


python3 -m paddle.distributed.launch --gpus=0,1,2,3 train_fleet_static.py
可以运行，因为一台就是就4张 rtx2080 卡，--gpus=0,1,2,3,4 就不行了

是否需要export CUDA_VISIBLE_DEVICES=0,1,2,3,4  配置这个？

**Comment by zhangbo9674** [comment]
如果只有4张卡，那应该--gpus=0,1,2,3

**Comment by poetryben88** [comment]
1、我有两台机器，每台都有4张RTX2080卡，现在想要把飞浆的示例跑满这8张卡。
2、直接在其中一台上敲：python3 -m paddle.distributed.launch --ips="192.168.50.191,192.168.50.190" --gpus=0,1,2,3,4,5,6,7  train_fleet_static.py
会报错：AssertionError: Can't find your local ip {127.0.0.1} in node_ips: {['192.168.50.191', '192.168.50.190']}

3、直接在其中一台上敲：python3 -m paddle.distributed.launch --ips="127.0.0.1,192.168.50.190" --gpus=0,1,2,3,4,5,6,7  train_fleet_static.py
会报错：ERROR 2021-11-11 14:28:10,267 launch_utils.py:603] ABORT!!! Out of all 10 trainers, the trainer process with rank=[4] was aborted. Please check its log.
检查之前一个work7日志
(paddle_env) xubaishuai@pai-worker1: $   cat workerlog.7
Start collective training example:
E1110 19:58:42.528818  6904 pybind.cc:1571] Invalid CUDAPlace(7), must inside [0, 4), because GPU number on your machine is 4
Start collective training example:
E1111 11:46:41.972980  4929 pybind.cc:1571] Invalid CUDAPlace(7), must inside [0, 4), because GPU number on your machine is 4
(paddle_env) xubaishuai@pai-worker1:~/log$

似乎 是两台机器之间缺少安装或者配置什么桥接的组件。

**Comment by poetryben88** [comment]
![image](https://user-images.githubusercontent.com/15098245/141252815-932d5db6-5f2f-4a20-90f8-8fe54381210c.png)

https://www.paddlepaddle.org.cn/documentation/docs/zh/guides/06_distributed_training/cluster_quick_start_cn.html
飞浆使用教程的上的示例是这么写的。不知道漏了哪里配置。

**Comment by zhangbo9674** [comment]
看日志，是因为只有4张卡，所以卡号只能是0123，现在执行`python3 -m paddle.distributed.launch --ips="127.0.0.1,192.168.50.190" --gpus=0,1,2,3 train_fleet_static.py`可以正常训练么？

**Comment by poetryben88** [comment]
NFO 2021-11-11 15:06:14,626 launch_utils.py:531] details abouts PADDLE_TRAINER_ENDPOINTS can be found in log/endpoints.log, and detail running logs maybe found in log/workerlog.0
launch proc_id:3854 idx:0
launch proc_id:3859 idx:1
launch proc_id:3864 idx:2
launch proc_id:3870 idx:3
Start collective training example:
Run on CUDAPlace(0).
server not ready, wait 3 sec to retry...
not ready endpoints:['127.0.0.1:6071', '127.0.0.1:6072', '127.0.0.1:6073', '192.168.50.190:6070', '192.168.50.190:6071', '192.168.50.190:6072', '192.168.50.190:6073']
server not ready, wait 3 sec to retry...
not ready endpoints:['192.168.50.190:6070', '192.168.50.190:6071', '192.168.50.190:6072', '192.168.50.190:6073']
server not ready, wait 3 sec to retry...
not ready endpoints:['192.168.50.190:6070', '192.168.50.190:6071', '192.168.50.190:6072', '192.168.50.190:6073']
server not ready, wait 3 sec to retry...
not ready endpoints:['192.168.50.190:6070', '192.168.50.190:6071', '192.168.50.190:6072', '192.168.50.190:6073']
server not ready, wait 3 sec to retry...
not ready endpoints:['192.168.50.190:6070', '192.168.50.190:6071', '192.168.50.190:6072', '192.168.50.190:6073']
...


python3 -m paddle.distributed.launch --ips="127.0.0.1,192.168.50.190" --gpus=0,1,2,3 train_fleet_static.py 跑不了。
一直都是not ready endpoints

**Comment by poetryben88** [comment]
python3 -m paddle.distributed.launch  --gpus=0,1,2,3 train_fleet_static.py
只能这么跑。

**Comment by zhangbo9674** [comment]
麻烦问一下，能看到not ready endpoints对应的日志么？

**Comment by poetryben88** [comment]
cat endpoints.log
PADDLE_TRAINER_ENDPOINTS:
127.0.0.1:6070
127.0.0.1:6071
127.0.0.1:6072
127.0.0.1:6073
192.168.50.190:6070
192.168.50.190:6071
192.168.50.190:6072
192.168.50.190:6073

endpoints.log日志就这么多。

**Comment by zhangbo9674** [comment]
workerlog.xx的日志可以提供一下么？

**Comment by poetryben88** [comment]
![image](https://user-images.githubusercontent.com/15098245/141291850-d84f2998-1312-43af-ad6e-71a06a843ecd.png)
![image](https://user-images.githubusercontent.com/15098245/141291876-225fab7f-a9fc-4235-9141-fb6847ace433.png)

GPU 4，5，6，7 错误都一样，GPU 0，1，2，3 正常。

**Comment by zhangbo9674** [comment]
麻烦尝试设置python3 -m paddle.distributed.launch --ips="127.0.0.1,192.168.50.190" --gpus=0,1,2,3 train_fleet_static.py

**Comment by poetryben88** [comment]
(paddle_env) pai-worker1: python3 -m paddle.distributed.launch --ips="127.0.0.1,192.168.50.190" --gpus=0,1,2,3 train_fleet_static.py
-----------  Configuration Arguments -----------
backend: auto
elastic_server: None
force: False
gpus: 0,1,2,3
heter_worker_num: None
heter_workers:
host: None
http_port: None
ips: 127.0.0.1,192.168.50.190
job_id: None
log_dir: log
np: None
nproc_per_node: None
run_mode: None
scale: 0
server_num: None
servers:
training_script: train_fleet_static.py
training_script_args: []
worker_num: None
workers:
------------------------------------------------
INFO 2021-11-12 08:57:20,218 launch.py:402] Run collective mode. gpu arguments:['--ips'], cuda count:4
launch train in GPU mode!
INFO 2021-11-12 08:57:20,218 launch_utils.py:640] Change selected_gpus into reletive values. --ips:0,1,2,3 will change into relative_ips:[0, 1, 2, 3] according to your CUDA_VISIBLE_DEVICES:['0', '1', '2', '3']
INFO 2021-11-12 08:57:20,219 launch_utils.py:528] Local start 4 processes. First process distributed environment info (Only For Debug):
    +=======================================================================================+
    |                        Distributed Envs                      Value                    |
    +---------------------------------------------------------------------------------------+
    |                       PADDLE_TRAINER_ID                        0                      |
    |                 PADDLE_CURRENT_ENDPOINT                 127.0.0.1:6070                |
    |                     PADDLE_TRAINERS_NUM                        8                      |
    |                PADDLE_TRAINER_ENDPOINTS  ... 1,192.168.50.190:6072,192.168.50.190:6073|
    |                     PADDLE_RANK_IN_NODE                        0                      |
    |                 PADDLE_LOCAL_DEVICE_IDS                        0                      |
    |                 PADDLE_WORLD_DEVICE_IDS                 0,1,2,3,0,1,2,3               |
    |                     FLAGS_selected_gpus                        0                      |
    |             FLAGS_selected_accelerators                        0                      |
    +=======================================================================================+

INFO 2021-11-12 08:57:20,219 launch_utils.py:531] details abouts PADDLE_TRAINER_ENDPOINTS can be found in log/endpoints.log, and detail running logs maybe found in log/workerlog.0
launch proc_id:18550 idx:0
launch proc_id:18555 idx:1
launch proc_id:18560 idx:2
launch proc_id:18565 idx:3
Start collective training example:
Run on CUDAPlace(0).
server not ready, wait 3 sec to retry...
not ready endpoints:['127.0.0.1:6071', '127.0.0.1:6072', '127.0.0.1:6073', '192.168.50.190:6070', '192.168.50.190:6071', '192.168.50.190:6072', '192.168.50.190:6073']
server not ready, wait 3 sec to retry...
not ready endpoints:['192.168.50.190:6070', '192.168.50.190:6071', '192.168.50.190:6072', '192.168.50.190:6073']
server not ready, wait 3 sec to retry...
not ready endpoints:['192.168.50.190:6070', '192.168.50.190:6071', '192.168.50.190:6072', '192.168.50.190:6073']
server not ready, wait 3 sec to retry...
not ready endpoints:['192.168.50.190:6070', '192.168.50.190:6071', '192.168.50.190:6072', '192.168.50.190:6073']
server not ready, wait 3 sec to retry...
not ready endpoints:['192.168.50.190:6070', '192.168.50.190:6071', '192.168.50.190:6072', '192.168.50.190:6073']
server not ready, wait 3 sec to retry...
not ready endpoints:['192.168.50.190:6070', '192.168.50.190:6071', '192.168.50.190:6072', '192.168.50.190:6073']
server not ready, wait 3 sec to retry...
not ready endpoints:['192.168.50.190:6070', '192.168.50.190:6071', '192.168.50.190:6072', '192.168.50.190:6073']
server not ready, wait 3 sec to retry...
not ready endpoints:['192.168.50.190:6070', '192.168.50.190:6071', '192.168.50.190:6072', '192.168.50.190:6073']
server not ready, wait 3 sec to retry...
not ready endpoints:['192.168.50.190:6070', '192.168.50.190:6071', '192.168.50.190:6072', '192.168.50.190:6073']
server not ready, wait 3 sec to retry...
not ready endpoints:['192.168.50.190:6070', '192.168.50.190:6071', '192.168.50.190:6072', '192.168.50.190:6073']
server not ready, wait 3 sec to retry...
not ready endpoints:['192.168.50.190:6070', '192.168.50.190:6071', '192.168.50.190:6072', '192.168.50.190:6073']
server not ready, wait 3 sec to retry...
not ready endpoints:['192.168.50.190:6070', '192.168.50.190:6071', '192.168.50.190:6072', '192.168.50.190:6073']
server not ready, wait 3 sec to retry...
not ready endpoints:['192.168.50.190:6070', '192.168.50.190:6071', '192.168.50.190:6072', '192.168.50.190:6073']
server not ready, wait 3 sec to retry...
not ready endpoints:['192.168.50.190:6070', '192.168.50.190:6071', '192.168.50.190:6072', '192.168.50.190:6073']
server not ready, wait 3 sec to retry...
not ready endpoints:['192.168.50.190:6070', '192.168.50.190:6071', '192.168.50.190:6072', '192.168.50.190:6073']
server not ready, wait 3 sec to retry...
not ready endpoints:['192.168.50.190:6070', '192.168.50.190:6071', '192.168.50.190:6072', '192.168.50.190:6073']
server not ready, wait 3 sec to retry...
not ready endpoints:['192.168.50.190:6070', '192.168.50.190:6071', '192.168.50.190:6072', '192.168.50.190:6073']
server not ready, wait 3 sec to retry...
not ready endpoints:['192.168.50.190:6070', '192.168.50.190:6071', '192.168.50.190:6072', '192.168.50.190:6073']
server not ready, wait 3 sec to retry...
not ready endpoints:['192.168.50.190:6070', '192.168.50.190:6071', '192.168.50.190:6072', '192.168.50.190:6073']
server not ready, wait 3 sec to retry...
not ready endpoints:['192.168.50.190:6070', '192.168.50.190:6071', '192.168.50.190:6072', '192.168.50.190:6073']
server not ready, wait 3 sec to retry...
not ready endpoints:['192.168.50.190:6070', '192.168.50.190:6071', '192.168.50.190:6072', '192.168.50.190:6073']
server not ready, wait 3 sec to retry...
not ready endpoints:['192.168.50.190:6070', '192.168.50.190:6071', '192.168.50.190:6072', '192.168.50.190:6073']
server not ready, wait 3 sec to retry...
not ready endpoints:['192.168.50.190:6070', '192.168.50.190:6071', '192.168.50.190:6072', '192.168.50.190:6073']
...
...
..
最后一直重复
server not ready, wait 3 sec to retry...
not ready endpoints:['192.168.50.190:6070', '192.168.50.190:6071', '192.168.50.190:6072', '192.168.50.190:6073']
这个错误，似乎是先要校验 --ips='XXX'列表内的IP服务器 GPU节点状态。

**Comment by zhangbo9674** [comment]
麻烦在环境中执行：
import socket
socket.gethostbyname(socket.getfqdn(socket.gethostname()))
看一下返回的是什么结果。
此外，麻烦辛苦确认一下，python脚本是否是官网的train_fleet_static.py

**Comment by kuizhiqing** [comment]
解决方法参考 https://github.com/PaddlePaddle/Paddle/issues/34533，
能分享下你的网络配置看下为什么环境里面 
`socket.gethostbyname(socket.getfqdn(socket.gethostname())) `
解析不到对应的 ip 吗？

**Comment by poetryben88** [comment]
![image](https://user-images.githubusercontent.com/15098245/141415839-d07fa35d-2b47-4ab2-a42f-5becc9085ae9.png)

**Comment by poetryben88** [comment]
我的环境网络是anaconda 创建的，train_fleet_static.py 脚本是官网的，未做改动。

**Comment by zhangbo9674** [comment]
您好，请尝试使用下面1或2的方法：（相似问题issue：https://github.com/PaddlePaddle/Paddle/issues/34533）
<img width="653" alt="图片" src="https://user-images.githubusercontent.com/82555433/141420997-cfdb4441-71b7-4a2a-abf9-4adb55306fe4.png">

**Comment by poetryben88** [comment]
![image](https://user-images.githubusercontent.com/15098245/141422258-5e599592-dcd8-4108-858a-9997fbe5eafd.png)
![image](https://user-images.githubusercontent.com/15098245/141422292-8b7764a0-27ff-4dc8-8148-2d5f19344c9e.png)
还是不行啊

**Comment by zhangbo9674** [comment]
lanch使用示例可见：https://github.com/PaddlePaddle/Paddle/blob/742378f47f71083291dafd414c33e5b69d775f8b/python/paddle/distributed/fleet/launch.py#L456
![图片](https://user-images.githubusercontent.com/82555433/141423426-b155fdd1-e817-4834-8e10-d0b7716b7f3b.png)

**Comment by poetryben88** [comment]
![image](https://user-images.githubusercontent.com/15098245/141426321-4db385c0-a6f7-4c59-b5e9-c3a208fea159.png)

![image](https://user-images.githubusercontent.com/15098245/141426335-7787a9e5-6b0b-4427-8879-a280912a00b4.png)

兄弟们，不行啊。。

**Comment by poetryben88** [comment]
python3 -m paddle.distributed.launch --ips=192.168.50.191,192.168.50.190 --gpus=0,1,2,3  train_fleet_static.py
![image](https://user-images.githubusercontent.com/15098245/141428809-d6a30cd3-bb48-45c6-a941-179402fd289e.png)
python3 -m paddle.distributed.launch --ips="192.168.50.191,192.168.50.190" --gpus=0,1,2,3  train_fleet_static.py
![image](https://user-images.githubusercontent.com/15098245/141428959-00017191-6a2b-476a-8e84-5438281fe8b4.png)

我理解了，可能hosts 这里重复了。把两台机器的hosts编辑了一下，可以跑了。
但是跑了，无故终止了。

192.168.50.190  workerlog.0的最后几行日志。
----------------------
Error Message Summary:
----------------------
FatalError: `Termination signal` is detected by the operating system.
  [TimeInfo: *** Aborted at 1636702677 (unix time) try "date -d @1636702677" if you are using GNU date ***]
  [SignalInfo: *** SIGTERM (@0x3ef000facaf) received by PID 1027327 (TID 0x7f17df9e23c0) from PID 1027247 ***]


192.168.50.191  workerlog.0的最后几行日志。
----------------------
Error Message Summary:
----------------------
FatalError: `Termination signal` is detected by the operating system.
  [TimeInfo: *** Aborted at 1636702679 (unix time) try "date -d @1636702679" if you are using GNU date ***]
  [SignalInfo: *** SIGTERM (@0x3ef00007b3c) received by PID 31585 (TID 0x7f913b3383c0) from PID 31548 ***]

**Comment by zhangbo9674** [comment]
建议检查cuda版本及cudnn版本。

**Comment by poetryben88** [comment]
NVIDIA-SMI 470.57.02    Driver Version: 470.57.02    CUDA Version: 11.4
cuDNN Version: 7.6.1

**Comment by zhangbo9674** [comment]
你好，我了解到cuda和cudnn版本是存在对应关系的：
<img width="677" alt="图片" src="https://user-images.githubusercontent.com/82555433/141447288-bbf14542-717a-43a3-bd49-83b6dd2ecc5a.png">

**Comment by zhangbo9674** [comment]
https://developer.nvidia.com/rdp/cudnn-archive

**Comment by poetryben88** [comment]
![image](https://user-images.githubusercontent.com/15098245/141468120-db65025d-7ff4-4756-8f08-21bb1dd38fa6.png)

NVIDIA-SMI 470.57.02    Driver Version: 470.57.02    CUDA Version: 11.4
cuDNN Version: 8.2.2

我现在换成对应的版本也不行啊
