### ISSUE TITLE
多卡训练报错

### ISSUE THREAD

**Issue by Xuanfang1121** [PaddlePaddle/Paddle#37139]
为使您的问题得到快速解决，在建立Issues前，请您先通过如下方式搜索是否有相似问题:【搜索issue关键字】【使用labels筛选】【官方文档】

如果您没有查询到相似问题，为快速解决您的提问，建立issue时请提供如下细节信息：
- 标题：简洁、精准概括您的问题，例如“Insufficient Memory xxx" ”
- 版本、环境信息：
    1）PaddlePaddle版本：paddlepaddle-gpu==2.1.3.post112
    2）CPU：预测若用CPU，请提供CPU型号，MKL/OpenBlas/MKLDNN/等数学库使用情况
    3）GPU：3080Ti，2080Ti，CUDA==11.2 
    4）系统环境：Ubuntu 16.04.7 ，python==3.7
 注：您可以通过执行[summary_env.py](https://github.com/PaddlePaddle/Paddle/blob/develop/tools/summary_env.py)获取以上信息。
- 训练信息
    1）单机：多卡
    2）显存信息 11g
    3）Operator信息
- 复现信息：如为报错，请给出复现环境、复现步骤
- 

> 问题描述：请详细描述您的问题，同步贴出报错信息、日志、可复现的代码片段

使用paddlepaddle进行模型多卡训练：
代码：
          if config.train.use_data_parallel:
               model = paddle.DataParallel(model)

报错如下
![4088288C-85B9-41b6-92B6-52AA37476B5A](https://user-images.githubusercontent.com/33194029/141293931-8fa7be11-552b-42eb-99a3-957b3f7f7a67.png)
：

这个错误如何解决

**Comment by zhangbo9674** [comment]
您好，报错信息需要复现代码，请提供代码和环境信息，我们复现后会尽快回复您

**Comment by Xuanfang1121** [comment]
您好，代码是地址为https://github.com/PaddlePaddle/Research/tree/master/NLP/Text2SQL-BASELINE，在conf/text2sql_nl2sql.jsonnet中的use_data_parallel 设置为true,会报上述的错误，环境信息如下：paddle-ernie==0.2.0.dev1，
paddlenlp==2.1.0，paddlepaddle-gpu==2.1.3.post112， python=3.7.9,显卡信息如下：
![gpu](https://user-images.githubusercontent.com/33194029/141715168-f2492f53-276c-4f77-8d67-90835ded133b.jpg)

**Comment by Xuanfang1121** [comment]
> 您好，报错信息需要复现代码，请提供代码和环境信息，我们复现后会尽快回复您
您好，代码是地址为https://github.com/PaddlePaddle/Research/tree/master/NLP/Text2SQL-BASELINE，在conf/text2sql_nl2sql.jsonnet中的use_data_parallel 设置为true,会报上述的错误，环境信息如下：paddle-ernie==0.2.0.dev1，
paddlenlp==2.1.0，paddlepaddle-gpu==2.1.3.post112， python=3.7.9,显卡信息如下：
![gpu](https://user-images.githubusercontent.com/33194029/141715238-5bd74e93-65e9-44d5-b59e-a70421091726.jpg)

**Comment by zhangbo9674** [comment]
您好，初步分析可能是PaddlePaddle/Research的使用问题，建议您到“https://github.com/PaddlePaddle/Research/issues”下进行提问。

**Comment by Xuanfang1121** [comment]
> 您好，初步分析可能是PaddlePaddle/Research的使用问题，建议您到“[https://github.com/PaddlePaddle/Research/issues”下进行提问。](https://github.com/PaddlePaddle/Research/issues%E2%80%9D%E4%B8%8B%E8%BF%9B%E8%A1%8C%E6%8F%90%E9%97%AE%E3%80%82)

好的，收到，谢谢
