### ISSUE TITLE
torch和paddle模型对齐，paddle的lstm多了几个权重，但是torch里面未出现这个，

### ISSUE THREAD

**Issue by developWmark** [PaddlePaddle/Paddle#37132]
![Y2Y@5M) 4N6F`AOR$HLC% F](https://user-images.githubusercontent.com/93702453/141270350-729fac56-7881-4035-8660-81fd5554f47d.jpg)
转换的时候忽略了UserWarning: Skip loading for rnn.0.rnn.0.cell_bw.bias_hh. rnn.0.rnn.0.cell_bw.bias_hh is not found ，
但是模型对齐预测时，精度差别很大

**Comment by zhangbo9674** [comment]
你好，请问是用的paddle.nn.LSTM么？

**Comment by zhangbo9674** [comment]
您好，请提供代码和环境信息，我们复现后会尽快回复您

**Comment by developWmark** [comment]
是用的paddle.nn.LSTM，代码我是直接贴出来吗还是加微信发给你

**Comment by developWmark** [comment]
import torch.nn as nn
import torch.nn.functional as F
from opt_einsum.backends import torch
import torch
class BidirectionalLSTM(nn.Module):
    # Inputs hidden units Out
    def __init__(self, nIn, nHidden, nOut):
        super(BidirectionalLSTM, self).__init__()

        self.rnn = nn.LSTM(nIn, nHidden, bidirectional=True)
        self.embedding = nn.Linear(nHidden * 2, nOut)

    def forward(self, input):
        recurrent, _ = self.rnn(input)
        T, b, h = recurrent.size()
        t_rec = recurrent.view(T * b, h)

        output = self.embedding(t_rec)  # [T * b, nOut]
        output = output.view(T, b, -1)

        return output
======================================================
import paddle
import paddle.nn as nn
import paddle.nn.functional as F


class BidirectionalLSTM(nn.Layer):
    # Inputs hidden units Out
    def __init__(self, nIn, nHidden, nOut):
        super(BidirectionalLSTM, self).__init__()

        self.rnn = nn.LSTM(nIn, nHidden, direction="bidirectional")
        self.embedding = nn.Linear(nHidden * 2, nOut)

    def forward(self, input):
        recurrent, _ = self.rnn(input)
        T, b, h = recurrent.shape
        t_rec = paddle.reshape(recurrent, shape=(T * b, h))

        output = self.embedding(t_rec)  # [T * b, nOut]
        output = paddle.reshape(output, shape=(T, b, -1))

        return output

**Comment by developWmark** [comment]
你们复现好了吗

**Comment by joey12300** [comment]
你好，精度对不齐指的是多出来的参数精度无法对齐torch吗？由于paddle的LSTM支持direction为`backward`的训练，这需要使用LSTMCell，这时会多出蓝框所示的参数。如果`direction`设为`bidirect`或者`forward`的话，不会使用到该部分参数的

**Comment by developWmark** [comment]
> 你好，精度对不齐指的是多出来的参数精度无法对齐torch吗？由于paddle的LSTM支持direction为`backward`的训练，这需要使用LSTMCell，这时会多出蓝框所示的参数。如果`direction`设为`bidirect`或者`forward`的话，不会使用到该部分参数的

你好，我试了‘’bidirect'
![image](https://user-images.githubusercontent.com/93702453/141720767-7ecaa63f-3dab-4e12-9807-db4d612a2a5a.png)
但是打印出来的key还是包括cell的，然后我又尝试了模型权重前向对齐，依然提示
![image](https://user-images.githubusercontent.com/93702453/141720919-e995acdf-6c7c-4909-9198-37f4b7dd581d.png)
代码忽略字段包括
![image](https://user-images.githubusercontent.com/93702453/141720962-d8b6ad32-c109-4edd-bc21-4e94694376ea.png)
![image](https://user-images.githubusercontent.com/93702453/141721030-60760f59-709e-48c3-86b3-b6fbb4b77020.png)
打印后二者精度差别很大

**Comment by developWmark** [comment]
这个是paddle使用的版本号
![image](https://user-images.githubusercontent.com/93702453/141721119-6658ffc9-b42f-40d8-b8a7-75a94c0c874f.png)

**Comment by joey12300** [comment]
@developWmark 可以提供训练代码吗？我看你好像只提供了模型代码。你可以先对齐同名模型参数，包括embedding，rnn以及最后linear参数。
