### ISSUE TITLE
jetson上源码编译paddle

### ISSUE THREAD

**Issue by Xyj2020** [PaddlePaddle/Paddle#37137]
在jetson上源码编译paddle，make的时候需要连网下一些依赖，但是直接下载github会失败，请问要到哪里能将https://github.com修改为https://hub.fastgit.org/？

**Comment by zhangbo9674** [comment]
你好，这种问题通常是网络问题，如果一定要修改，在/cmake/externel/路径下的camke文件中有很多指定GIT_URL，建议考虑换一下网络。

**Comment by Xyj2020** [comment]
你好，感谢回答，我在CMakeLists.txt里面更换了，已经开始编译了，但是现在又遇到这个错误，请问应该怎么解决？感觉这个网络一直是个问题，或者你们有没有下载好的第三方库可以发我一份吗？我是编译的paddle2.0.0，错误如下：


CMakeFiles/extern_eigen3.dir/build.make:90: recipe for target 'third_party/eigen3/src/extern_eigen3-stamp/extern_eigen3-download' failed
make[2]: *** [third_party/eigen3/src/extern_eigen3-stamp/extern_eigen3-download] Error 1
CMakeFiles/Makefile2:309: recipe for target 'CMakeFiles/extern_eigen3.dir/all' failed
make[1]: *** [CMakeFiles/extern_eigen3.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....



------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/Paddle"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月11日(星期四) 晚上8:43
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PaddlePaddle/Paddle] jetson上源码编译paddle (Issue #37137)





 
你好，这种问题通常是网络问题，如果一定要修改，在/cmake/externel/路径下的camke文件中有很多指定GIT_URL，建议考虑换一下网络。
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by zhangbo9674** [comment]
您好，很抱歉，我们这没有下载好的第三方库，还是建议调试一下网络环境。此外，paddle提供了jetson各个版本的预测库，希望有所帮助：https://www.paddlepaddle.org.cn/documentation/docs/zh/guides/09_hardware_support/hardware_info_cn.html#paddle-inference

**Comment by Xyj2020** [comment]
你好，我的jetson现在不能科学上网，我想请问你们在编译的时候是如何调整网络环境的？我已经改了GIT_URL，可是在编译的时候还是会有一些地方需要连外网，比如说这个网址：https://gitlab.com/libeigen/eigen.git，就一直卡在这里报错，请问你们遇到这种问题是怎样解决的。（paddle提供的预测库我用不上，需要自己编译，不好意思我太菜了）




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/Paddle"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月11日(星期四) 晚上9:27
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PaddlePaddle/Paddle] jetson上源码编译paddle (Issue #37137)





 
您好，很抱歉，我们这没有下载好的第三方库，还是建议调试一下网络环境。此外，paddle提供了jetson各个版本的预测库，希望有所帮助：https://www.paddlepaddle.org.cn/documentation/docs/zh/guides/09_hardware_support/hardware_info_cn.html#paddle-inference
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by jiweibo** [comment]
您好，可以试下在https://gitee.com 上克隆下github的仓库哈，这个访问是不需要代理的。
