### ISSUE TITLE
多卡模型训练选择显卡

### ISSUE THREAD

**Issue by Xuanfang1121** [PaddlePaddle/Paddle#37140]
为使您的问题得到快速解决，在建立Issues前，请您先通过如下方式搜索是否有相似问题:【搜索issue关键字】【使用labels筛选】【官方文档】

如果您没有查询到相似问题，为快速解决您的提问，建立issue时请提供如下细节信息：
- 标题：简洁、精准概括您的问题，例如“Insufficient Memory xxx" ”
- 版本、环境信息：
    1）PaddlePaddle版本：paddlepaddle-gpu==2.1.3.post112
    2）CPU：
    3）GPU：2080Ti，3080Ti，cuda==11.2 
    4）系统环境：Ubuntu 16.04.7， python==3.7
 注：您可以通过执行[summary_env.py](https://github.com/PaddlePaddle/Paddle/blob/develop/tools/summary_env.py)获取以上信息。
- 训练信息
    1）单机：多卡
    2）显存信息  11g
    3）Operator信息
- 复现信息：如为报错，请给出复现环境、复现步骤
- 问题描述：请详细描述您的问题，同步贴出报错信息、日志、可复现的代码片段
服务器是多卡，进行模型训练的时候，指定使用第2张显卡，代码如下：
os.environ['FLAGS_eager_delete_tensor_gb'] = "0.0"
os.environ["CUDA_VISIBLE_DEVICES"] = '0'
使用3080这张显卡，paddlepaddle-gpu==2.1.3 使用2080Ti这张显卡，该如何设置？

**Comment by zhangbo9674** [comment]
您好，需要确定2080Ti显卡的卡号，而后通过paddle.set_device(device)指定：https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/device/set_device_cn.html#set-device

**Comment by Xuanfang1121** [comment]
好的，谢谢
