### ISSUE TITLE
Simple Tensor Comparison Error

### ISSUE THREAD

**Issue by wj-Mcat** [PaddlePaddle/Paddle#37165]
## Enviornment

* os info: ubuntu 20.04
* paddle-cpu: 2.2.0
* python: 3.9

## Reproduce

When I'm writing model unit testing code, there is magical error:

```python
assert paddle.to_tensor(2) == paddle.to_tensor([2.1])
```

The above code will pass the testing. Is there anything I have missed ?

**Comment by wj-Mcat** [comment]
## Get deep into this case
In order to find the reason, I have done some more testing code:

1.  get default tensor value

```python
a = paddle.to_tensor(2)
b = paddle.to_tensor([2.1])
print(a)
print(b)
assert a == b
```
the printed info is:
```shell
Tensor(shape=[1], dtype=int64, place=CPUPlace, stop_gradient=True,
       [2])
Tensor(shape=[1], dtype=float32, place=CPUPlace, stop_gradient=True,
       [2.09999990])
```

It seems that the dtype of tensor is correct.

2. set dtype manually when init tensor

```python
a = paddle.to_tensor(2, dtype=paddle.int32)
b = paddle.to_tensor([2.1], dtype=paddle.float32)
print(a)
print(b)
assert a == b
```

the above code is also can pass the test.

3. set the same dtype

```python
a = paddle.to_tensor(2, dtype=paddle.float32)
b = paddle.to_tensor([2.1], dtype=paddle.float32)
print(a)
print(b)
assert a == b
```

the above code can't pass the test. 

## Summary

I guess that the reason is comparison mechanism between different dtype tensors.  It's just my thinkings which may not be correct.

**Comment by xingfeng01** [comment]
Hi, please specify the data type as float with "dtype" parameter for the moment.
https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/to_tensor_cn.html#to-tensor 

We will check the comparison mechanism.

**Comment by wj-Mcat** [comment]
Ok, after seting the dtype of tensor, the below code can also pass the test.

```python
a = paddle.to_tensor(2, dtype=paddle.int32)
b = paddle.to_tensor([2.1], dtype=paddle.float32)
print(a)
print(b)
assert a == b
```

**Comment by xingfeng01** [comment]
Please both set as float32 as mentioned in your comments

a = paddle.to_tensor(2, dtype=paddle.float32)
b = paddle.to_tensor([2.1], dtype=paddle.float32)
print(a)
print(b)
assert a == b

**Comment by wj-Mcat** [comment]
Oh ~~~~, I think I have found some issues for you:

```python
import paddle

assert 2 == 2.0
assert paddle.to_tensor(2) == paddle.to_tensor(2.1)
assert paddle.equal(
    paddle.to_tensor(2), 
    paddle.to_tensor(2.1)
)
```

It will throw the exception:

```shell
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
/tmp/ipykernel_2763476/3140182946.py in <module>
      5 a = paddle.to_tensor(2)
      6 b = paddle.to_tensor(2.1)
----> 7 assert paddle.equal(
      8     paddle.to_tensor(2),
      9     paddle.to_tensor(2.1)

~/miniconda3/envs/paddle/lib/python3.9/site-packages/paddle/tensor/logic.py in equal(x, y, name)
    184 
    185     if in_dygraph_mode():
--> 186         return _C_ops.equal(x, y)
    187 
    188     check_variable_and_dtype(

ValueError: (InvalidArgument) The DataType of equal Op's duplicable Variable Y must be consistent. The current variable type is (float), but the previous variable type is (int64_t). (at /paddle/paddle/fluid/framework/operator.cc:1603)
  [operator < equal > error]
```

It will throw the exception when the dtype of tensors are different. But the `==` operator will not throw the exception.

**Comment by xingfeng01** [comment]
This should be some issue, we will check, thanks for exploration.

**Comment by wj-Mcat** [comment]
You're welcome. It's my pleasure to help you figure it out.
