### ISSUE TITLE
权重初始化self.weight.shape.numpy()[:] = SRM_npy报错，AI Studio 经典版，2.0.2，python3

### ISSUE THREAD

**Issue by ZiJINII** [PaddlePaddle/Paddle#37178]
![image](https://user-images.githubusercontent.com/92594026/141668889-630b48ad-def4-4040-a605-bc7502460e4f.png)
import os
import sys
import numpy as np

import paddle
import paddle.nn as nn
from paddle.nn import Layer
import paddle.nn.functional as F

SRM_npy = np.load('SRM_Kernels.npy')

#残差网络卷积2D卷积
class Res_conv2d(nn.Layer):
    def __init__(self):
        super(Res_conv2d, self).__init__()
        self.weight = paddle.create_parameter([30,1,5,5],dtype = "float32")
        self.bias = paddle.create_parameter([30],dtype = "float32")
        self.reset_parameters()
        
    def reset_parameters(self):
        self.weight.shape.numpy()[:] = SRM_npy#报错
        self.bias.shape.zero_()   #报错

    def forward(self, input):
        return F.conv2d(input, self.weight, self.bias)
问题：之前self.weight = Parameter(torch.Tensor(30, 1, 5, 5), requires_grad=True)
通过API文档用paddle.create_parameter([30,1,5,5],dtype = "float32")替换，但在替换之后不确定新生成的shape和原来的torch.Tensor(30, 1, 5, 5)是不是同一格式，也就是不确定shape是不是张量。
假如是张量，为什么在报错部分self.weight.shape.numpy()[:] = SRM_npy会显示没有numpy（）。

**Comment by ronny1996** [comment]
您好，self.weight.shape是list类型，没有numpy方法
