### ISSUE TITLE
使用模型训练的自定义数据集，导出模型识别度低

### ISSUE THREAD

**Issue by xiaofeixuan** [PaddlePaddle/Paddle#37171]
PaddleDetection-release-2.3，静态图片训练，自己的voc数据集，训练使用的模型：\static\configs\yolov3_mobilenet_v1_voc.yml,执行train.py 训练的。
平台识别使用infer.py，效果还可以。然后使用paddle_lite_opt 工具导出nb模型文件：目前有两个问题：
1：怎么减小体积，一共两个labels类型，导出的模型有92M
2：镜头贴近图片识别度达到80% 90%，效果很好，稍微远一点，不是识别不到就是相似度只有3%  10%等等特别低，两张图片放一起，识别度更低。
请教一下，因为一些参数不会设置，麻烦各位知道的解答一下。

**Comment by xingfeng01** [comment]
您好，您是希望更多的了解 YOLOv3 模型如何设置参数，从而体积更小以及得到更好的结果是吗？如果方便的话，可以提供一下具体代码和场景吗 ？

**Comment by xiaofeixuan** [comment]
代码就是github下载的PaddleDetection-release-2.3里面的static\configs\yolov3_mobilenet_v1_voc.yml   只更改了max_iters 跟实际的num_classes，以及下面的：
TrainReader:
  dataset:
    !VOCDataSet
    dataset_dir: dataset
    anno_path: trainval.txt
    use_default_label: false
    with_background: false

EvalReader:
  inputs_def:
    fields: ['image', 'im_size', 'im_id', 'gt_bbox', 'gt_class', 'is_difficult']
  dataset:
    !VOCDataSet
    dataset_dir: dataset
    anno_path: test.txt
    use_default_label: false
    with_background: false

TestReader:
  dataset:
    !ImageFolder
    dataset_dir: dataset
    anno_path: label_list.txt
    use_default_label: false
    with_background: false

**Comment by xiaofeixuan** [comment]
> 您好，您是希望更多的了解 YOLOv3 模型如何设置参数，从而体积更小以及得到更好的结果是吗？如果方便的话，可以提供一下具体代码和场景吗 ？
代码就是github下载的PaddleDetection-release-2.3里面的static\configs\yolov3_mobilenet_v1_voc.yml   只更改了max_iters 跟实际的num_classes，以及下面的：
TrainReader:
  dataset:
    !VOCDataSet
    dataset_dir: dataset
    anno_path: trainval.txt
    use_default_label: false
    with_background: false

EvalReader:
  inputs_def:
    fields: ['image', 'im_size', 'im_id', 'gt_bbox', 'gt_class', 'is_difficult']
  dataset:
    !VOCDataSet
    dataset_dir: dataset
    anno_path: test.txt
    use_default_label: false
    with_background: false

TestReader:
  dataset:
    !ImageFolder
    dataset_dir: dataset
    anno_path: label_list.txt
    use_default_label: false
    with_background: false

**Comment by Ligoml** [comment]
小模型推荐使用PaddleDetection里的PicoDet https://github.com/PaddlePaddle/PaddleDetection/tree/release/2.3/configs/picodet

或者PP-YOLO tiny https://github.com/PaddlePaddle/PaddleDetection/tree/release/2.3/configs/ppyolo
