### ISSUE TITLE
there is no Tensor class will reduce the coding experience

### ISSUE THREAD

**Issue by wj-Mcat** [PaddlePaddle/Paddle#37183]
## Description

When I'm writing net with paddle, there is no `Tensor` class which will let the IDE can predict the type of parameters & variables so that it will not output the method & attributes.  Is there any methods to improve the code completion ?

* paddle code

![image](https://user-images.githubusercontent.com/10242208/141682235-e39f6038-3b43-45b0-b53d-e63ea33f834b.png)

* pytorch code

![image](https://user-images.githubusercontent.com/10242208/141682262-510d41f7-3c3a-494c-a4bc-6c0e80f6bcf9.png)

## Envrionment
* paddlepaddle: 2.2.0
* cpu
* macos
* IDE: vscode

## Analysis

After checking the code, the `Tensor` object is the alias of `VarBase` from `fulid.core` module. But, I can't find the `VarBase` object in that module. I don't know how to improve code completion. Can you help me?

**Comment by ronny1996** [comment]
You can use IPython or Jupyter Notebook and use TAB for code completion.

The functions `help` and `dir` can obtain some information about the methods or attributes of an object.

**Comment by wj-Mcat** [comment]
## Thought about typing in paddle

After lightly review the source code, there are no type annotations in package. Do you have any plans to improve it? [Typing system](https://en.wikipedia.org/wiki/Type_system#:~:text=In%20programming%20languages%2C%20a%20type,%2C%20expressions%2C%20functions%20or%20modules.) will make code more readable and  testable. There are so many tools to make test under type annotations, eg:  [mypy](https://github.com/python/mypy), [pylint](https://github.com/PyCQA/pylint) and [pytype](https://github.com/google/pytype).  These tools will make sure the quality of project in some sense. 

you can refer to:

* https://www.python.org/dev/peps/pep-0561/
* https://www.python.org/dev/peps/pep-0526/
* https://www.python.org/dev/peps/pep-0484/

## Suggestions

* generate stubfile with mypy
* modify the stubfile to improve the code complete in IDE
* after fully annotations are set in source code, you can remove the stubfile and add `py.typed` (see (PEP 561)[https://www.python.org/dev/peps/pep-0561/]) to the project. 

I think this way will improve the typing experience when coding.  @ronny1996  @ZeyuChen  How do you think about it?

**Comment by wj-Mcat** [comment]
Closed by inactive.
