### ISSUE TITLE
出现这个问题是什么原因造成的呢？

### ISSUE THREAD

**Issue by mingrizhuhao** [PaddlePaddle/Paddle#37196]
paddlepaddle 2.0.2
![image](https://user-images.githubusercontent.com/92719714/141724199-9228b708-4bee-4f14-a80b-25249886e98e.png)

**Comment by thisjiang** [comment]
您好，从报错信息上看，错误是由于该python脚本不支持`-f`命令行参数导致的，建议按照下图中给定的命令行参数进行设置。如未能解决还请继续反馈，谢谢
![image](https://user-images.githubusercontent.com/31386411/141732479-9f5095f7-eec7-45eb-8c68-0e555e700a89.png)
