### ISSUE TITLE
device = torch.device('cuda')在paddlepaddle中应该改成什么

### ISSUE THREAD

**Issue by mingrizhuhao** [PaddlePaddle/Paddle#37207]
这个的功能应该是调用GPU，改成device = paddle.device.cuda.Stream()，出现错误
RuntimeError: (Unavailable) Class CUDAStream can only be initialized on the GPU platform. (at/paddle/paddle/fluid/pybind/cuda_streams_py.cc:281)
应该如何解决

**Comment by thisjiang** [comment]
您好，可以尝试`place = paddle.CUDAPlace(0)`，请https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/CUDAPlace_cn.html#cudaplace 实现，谢谢。

**Comment by thisjiang** [comment]
或者您可以尝试`paddle.device.set_device("gpu")`指定特定的运行设备，请参考https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/device/set_device_cn.html 实现，谢谢。
