### ISSUE TITLE
训练中途失败Check failed: len > 0  peer=10.73.227.36 curIov=33 iovCnt=93 iovs

### ISSUE THREAD

**Issue by lyp2github** [PaddlePaddle/Paddle#3720]
Check failed: len > 0  peer=10.73.227.36 curIov=33 iovCnt=93 iovs

**Comment by typhoonzero** [comment]
@lyp2github 请注意保密内网地址

**Comment by hedaoyuan** [comment]
@lyp2github 有两个相似的问题。#1503 和 #1451 
#1503 是由于混布导致的端口冲突，可以排查一下集群是否也是混布的。

**Comment by lyp2github** [comment]
master train.log:

**Comment by lyp2github** [comment]
**master train.log:**
Sun Aug 27 09:08:27 2017[1,8]<stderr>:F0827 09:08:27.095723 25428 SocketChannel.cpp:101] Check failed: len > 0  peer=10.73.227.35 curIov=62 iovCnt=93 iovs[curIov].base=F0827 09:08:27.101034 25438 SocketChannel.cpp:101] Check failed: len > 0  peer=10.73.217.31 curIov=62 iovCnt=93 iovs[curIov].base=F0827 09:08:27.102723 25434 SocketChannel.cpp:101] Check failed: len > 0  peer=10.73.217.39 curIov=62 iovCnt=93 iovs[curIov].base=F0827 09:08:27.105250 25430 SocketChannel.cpp:101] Check failed: len > 0  peer=10.73.227.36 curIov=61 iovCnt=93 iovs[curIov].base=F0827 09:08:27.106235 25423 SocketChannel.cpp:101] Check failed: len > 0  peer=10.73.227.34 curIov=62 iovCnt=93 iovs[curIov].base=0x7fe8df45f4a50x7fe8df51f6b780x7fe8df2ec22fiov_len= iovs[curIov].iov_len= iovs[curIov].iov_len=0x49880x7fe8df0dc3a3 iovs[curIov].iov_len=0x37e11 iovs[curIov].iov_len=0x7c9d: SuSucce [Succe [ [0]0]0]] Success [0]
Sun Aug 27 09:08:27 2017[1,8]<stderr>:

**对应节点【10.73.217.31】psever2.FATAL**
F0827 09:08:27.089238 15206 SocketChannel.cpp:101] Check failed: len > 0  peer=10.73.217.30 curIov=62 iovCnt=93 iovs[curIov].base=F0827 09:08:27.091019 15216 SocketChannel.cpp:101] Check failed: len > 0  peer=10.73.227.36 curIov=61 iovCnt=93 iovs[curIov].base=F0827 09:08:27.094491 15210 SocketChannel.cpp:101] Check failed: len > 0  peer=10.73.227.34 curIov=62 iovCnt=93 iovs[curIov].base=F0827 09:08:27.097599 15214 SocketChannel.cpp:101] Check failed: len > 0  peer=10.73.227.35 curIov=61 iovCnt=93 iovs[curIov].base=0x7f900751f6b7 iovs[curIov].iov_len=31897 iovs[curIov].iov_len=188250x7f900749f6b8 iovs[curIov].iov_len=188240x7f90070dc3a3 iovs[curIov].iov_len=31901: SuccessSuccess [ [0]]0827 09:08:27.110950 15220 SocketChannel.cpp:101] Check failed: len > 0  peer=10.73.217.39 curIov=62 iovCnt=93 iovs[curIov].base=0x7f90073df6b8 iovs[curIov].iov_len=18824: Success [0]
F0827 09:08:27.089238 15206 SocketChannel.cpp:101] Check failed: len > 0  peer=10.73.217.30 curIov=62 iovCnt=93 iovs[curIov].base=F0827 09:08:27.091019 15216 SocketChannel.cpp:101] Check failed: len > 0  peer=10.73.227.36 curIov=61 iovCnt=93 iovs[curIov].base=F0827 09:08:27.094491 15210 SocketChannel.cpp:101] Check failed: len > 0  peer=10.73.227.34 curIov=62 iovCnt=93 iovs[curIov].base=F0827 09:08:27.097599 15214 SocketChannel.cpp:101] Check failed: len > 0  peer=10.73.227.35 curIov=61 iovCnt=93 iovs[curIov].base=0x7f900751f6b7 iovs[curIov].iov_len=31897 iovs[curIov].iov_len=188250x7f900749f6b8 iovs[curIov].iov_len=188240x7f90070dc3a3 iovs[curIov].iov_len=31901: SuccessSuccess [ [0]]0827 09:08:27.110950 15220 SocketChannel.cpp:101] Check failed: len > 0  peer=10.73.217.39 curIov=62 iovCnt=93 iovs[curIov].base=0x7f90073df6b8 iovs[curIov].iov_len=18824: Success [0]

**peer节点【10.73.217.30 】psever2.FATAL**
F0827 09:08:27.095723 25428 SocketChannel.cpp:101] Check failed: len > 0  peer=10.73.227.35 curIov=62 iovCnt=93 iovs[curIov].base=F0827 09:08:27.101034 25438 SocketChannel.cpp:101] Check failed: len > 0  peer=10.73.217.31 curIov=62 iovCnt=93 iovs[curIov].base=F0827 09:08:27.102723 25434 SocketChannel.cpp:101] Check failed: len > 0  peer=10.73.217.39 curIov=62 iovCnt=93 iovs[curIov].base=F0827 09:08:27.105250 25430 SocketChannel.cpp:101] Check failed: len > 0  peer=10.73.227.36 curIov=61 iovCnt=93 iovs[curIov].base=F0827 09:08:27.106235 25423 SocketChannel.cpp:101] Check failed: len > 0  peer=10.73.227.34 curIov=62 iovCnt=93 iovs[curIov].base=0x7fe8df45f4a50x7fe8df51f6b780x7fe8df2ec22fiov_len= iovs[curIov].iov_len= iovs[curIov].iov_len=0x49880x7fe8df0dc3a3 iovs[curIov].iov_len=0x37e11 iovs[curIov].iov_len=0x7c9d: SuSucce [Succe [ [0]0]0]] Success [0]
F0827 09:08:36.042271 17928 SocketChannel.cpp:54] Check failed: len >= 0  peer=10.73.217.39: Connection reset by peer [104]
F0827 09:08:36.087374 23056 SocketChannel.cpp:54] Check failed: len >= 0  peer=10.73.217.37: Connection reset by peer [104]
F0827 09:08:36.087374 23056 SocketChannel.cpp:54] Check failed: len >= 0  peer=10.73.217.37: Connection reset by peer [104]F0827 09:08:36.127861 10753 SocketChannel.cpp:54] Check failed: len >= 0  peer=10.73.217.31: Connection reset by peer [104]

节点【10.73.217.37】=》【10.73.217.39】=》【10.73.227.35|10.73.217.38】=》【10.73.227.36】=》【10.73.217.38】=》【10.73.217.39】 ...

**Comment by lyp2github** [comment]
[paddle.log.tar.gz](https://github.com/PaddlePaddle/Paddle/files/1258942/paddle.log.tar.gz)

**Comment by typhoonzero** [comment]
昨天看了下job的日志，`train.log`和`server.log`最早的位置都显示了通信获得了错误的数据，很有可能是混部或者有其他程序使用了相同的端口。建议以集群独占方式提交任务。

**Comment by JessieMeng** [comment]
[movielens.txt](https://github.com/PaddlePaddle/Paddle/files/1262785/movielens.txt)

**Comment by lyp2github** [comment]
当前已经是集群独占方式运行，继续训练还是报错

**Comment by JessieMeng** [comment]
[train.txt](https://github.com/PaddlePaddle/Paddle/files/1262793/train.txt)

**Comment by LiuJiaqiang89** [comment]
@lyp2github 请问这个问题解决了吗？

**Comment by lyp2github** [comment]
没解决，换了个集群运行后，目前没出现该问题了
刘亚萍   商业平台研发部 | fc-opt
  Baidu    Fc-opt      Tel: 010-59928075  | Mobile:187-0152-4401  | Hi: hnlslyp

发件人: LiuJiaqiang89 <notifications@github.com<mailto:notifications@github.com>>
答复: PaddlePaddle/Paddle <reply@reply.github.com<mailto:reply@reply.github.com>>
日期: 2017年11月8日 星期三 18:59
至: PaddlePaddle/Paddle <Paddle@noreply.github.com<mailto:Paddle@noreply.github.com>>
抄送: baidu baidu <liuyaping@baidu.com<mailto:liuyaping@baidu.com>>, Mention <mention@noreply.github.com<mailto:mention@noreply.github.com>>
主题: Re: [PaddlePaddle/Paddle] 训练中途失败Check failed: len > 0 peer=10.73.227.36 curIov=33 iovCnt=93 iovs (#3720)


@lyp2github<https://github.com/lyp2github> 请问这个问题解决了吗？

―

**Comment by Yancey1989** [comment]
我先关闭这个不活跃的issue了，如果还有问题可以再打开它。
