### ISSUE TITLE
【NPU】ascend 310推理是否适配

### ISSUE THREAD

**Issue by ponycloud235** [PaddlePaddle/Paddle#37208]
RT，在官网中的文档，未看到已经坐适配，后续是否有适配计划？
https://www.paddlepaddle.org.cn/documentation/docs/zh/guides/09_hardware_support/npu_docs/paddle_install_cn.html
这里提供的是ARM环境，是否支持x86

目前的服务器环境 x86、ascend 310加速卡
![image](https://user-images.githubusercontent.com/2733701/141745121-032ca972-2f27-4e7a-946c-bcd93ad1609d.png)

**Comment by hong19860320** [comment]
目前已通过Paddle Lite 支持x86+atlas 300I/C(3010)、鲲鹏920+atlas 300I/C(3000)，atlas 200DK，具体可以看下Paddle Lite的文档 https://paddle-lite.readthedocs.io/zh/latest/demo_guides/huawei_ascend_npu.html
当然我们也提供了 Paddle Inference+Paddle Lite 支持的方式，具体可以看下 Paddle Inference 的demo https://github.com/PaddlePaddle/Paddle-Inference-Demo/tree/master/c%2B%2B/ascend310_lite_subgraph/image_classification_demo

推荐直接使用 Paddle Lite 支持昇腾310

**Comment by ponycloud235** [comment]
> 目前已通过Paddle Lite 支持x86+atlas 300I/C(3010)、鲲鹏920+atlas 300I/C(3000)，atlas 200DK，具体可以看下Paddle Lite的文档 https://paddle-lite.readthedocs.io/zh/latest/demo_guides/huawei_ascend_npu.html 当然我们也提供了 Paddle Inference+Paddle Lite 支持的方式，具体可以看下 Paddle Inference 的demo https://github.com/PaddlePaddle/Paddle-Inference-Demo/tree/master/c%2B%2B/ascend310_lite_subgraph/image_classification_demo
> 
> 推荐直接使用 Paddle Lite 支持昇腾310

好的 谢谢，我看看

**Comment by ponycloud235** [comment]
后续使用paddle-lite 实现了 升腾310的支持。 使用的是 yolov3-mobilenet 以及picodet
