### ISSUE TITLE
'Tensor' object has no attribute 'long'

### ISSUE THREAD

**Issue by tsijeodhsjsh** [PaddlePaddle/Paddle#37217]
问题：
在运行 stego_2 = (255.0 * (stego_1 + 1.0) / 2.0).long()  时
出现下面的报错
'Tensor' object has no attribute 'long'
这里long应该怎么改

**Comment by thisjiang** [comment]
您好，可以尝试`paddle.cast(x, 'int64')`，请参考https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/cast_cn.html#cn-api-fluid-layers-cast 实现，谢谢
