### ISSUE TITLE
Paddle.sln编译libpaddle_inference.dll Release版本没问题，Debug版本总是报错，是不是不支持Debug编译？

### ISSUE THREAD

**Issue by stq054188** [PaddlePaddle/Paddle#37243]
我使用的环境与版本：
Paddle-release-2.0，CMake 3.16，VS2017
Win10 64bit， NIVDIA GTC1070 8G，CPU i7 8750H

问题描述：
CMake编译Paddle-release-2.0后单独编译paddle.sln，可以生成Release版本libpaddle_inference.dll，并可以正常使用，但是同样的方法，去编译Debug版本一直报如下错误：
----------------------------------------------------------------------------------------------------------------------------
严重性	代码	说明	项目	文件	行	禁止显示状态
错误	LNK2038	检测到“_ITERATOR_DEBUG_LEVEL”的不匹配项: 值“0”不匹配值“2”(io.obj 中)	paddle_inference_shared	D:\PaddlePaddle\Paddle-release-2.0\build\paddle\fluid\inference\libcross_entropy_op.lib(cross_entropy_op.cu.obj)	1	

严重性	代码	说明	项目	文件	行	禁止显示状态
错误	LNK2038	检测到“RuntimeLibrary”的不匹配项: 值“MT_StaticRelease”不匹配值“MTd_StaticDebug”(io.obj 中)	paddle_inference_shared	D:\PaddlePaddle\Paddle-release-2.0\build\paddle\fluid\inference\libcross_entropy_op.lib(cross_entropy_op.cu.obj)	1	
-----------------------------------------------------------------------------------------------------------------------------
报错信息截图：
https://drive.google.com/file/d/1fSVoshcZ_PoxznaMP5ibmSF83m7NyDDE/view?usp=sharing

而且我这次是一直在Debug版本下生成的，根本没有Release版本的lib，为什么还是提示这些错误？是不是本来就不支持Debug版本，这样很不方便调试！请PaddlePaddle团队予以帮助！@ZzSean

**Comment by ZzSean** [comment]
您好，目前暂不支持debug版本的编译，未来有计划会及时回复，谢谢！

**Comment by stq054188** [comment]
> 您好，目前暂不支持debug版本的编译，未来有计划会及时回复，谢谢！

我真的裂开了，三天时间白花了。。。
