### ISSUE TITLE
执行 torch.cuda.empty_cache()，出现一下错误：name 'torch' is not defined

### ISSUE THREAD

**Issue by tsijeodhsjsh** [PaddlePaddle/Paddle#37241]
if paddle.fluid.is_compiled_with_cuda():
            torch.cuda.empty_cache()
        gc.collect()  # 强制进行垃圾回收
问题：在执行上面的语句时，出现这样的错误：name 'torch' is not defined
 torch.cuda.empty_cache()  的作用是释放内存，再paddle中是不是并不需要此语句

**Comment by EnHuiPug** [comment]
用paddle怎么会有torch呢。。。你改成 paddle.device.cuda.empty_cache() 试试，
不过好像只有paddle2.2才有empty_cache()

**Comment by ZzSean** [comment]
> ```
>     if paddle.fluid.is_compiled_with_cuda():
>         torch.cuda.empty_cache()
>     gc.collect()  # 强制进行垃圾回收
> ```
> 
> 问题：在执行上面的语句时，出现这样的错误：name 'torch' is not defined torch.cuda.empty_cache() 的作用是释放内存，再paddle中是不是并不需要此语句

在paddle2.2中可以使用paddle.device.cuda.empty_cache()来释放内存，具体可以参考API文档https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/device/cuda/empty_cache_cn.html
