### ISSUE TITLE
更换RTX 3090显卡后paddle启动后会卡几分钟

### ISSUE THREAD

**Issue by ouyangshixiong** [PaddlePaddle/Paddle#37250]
- 版本、环境信息：
    1）PaddlePaddle版本：paddlepaddle-gpu 2.2.0.post112
    2）CPU：5950x
    3）GPU：RTX3090
    4）系统环境：Ubuntu 18.04 LTS
- 安装方式信息：
1）pip安装         

paddle环境检查截图
![WechatIMG154](https://user-images.githubusercontent.com/2086862/141956428-892cedc7-a54f-42f8-ac83-87f90b677b35.jpeg)
:

跑PARL的demo中的QMIX算法和我自己写的算法都会卡，至少要卡3-5分钟。之前用N卡的1030都不会卡。
录屏可以微信联系我，谢谢帮忙

**Comment by ZzSean** [comment]
您好，请问您安装的cuda和cudnn版本是否匹配呢？据我了解3090应该是只支持CUDA11以上的版本

**Comment by ouyangshixiong** [comment]
> 您好，请问您安装的cuda和cudnn版本是否匹配呢？据我了解3090应该是只支持CUDA11以上的版本

@ZzSean 谢谢你的及时回复。我详细阅读过安装说明。屏幕截图中也有清晰显示。cuda版本11.2 cudnn版本8.1。我读过的文档在如下的截图中：
![企业微信20211117-091143](https://user-images.githubusercontent.com/2086862/142091186-f1959720-cf13-4691-9b9b-e414408e5157.png)
![企业微信20211117-091205](https://user-images.githubusercontent.com/2086862/142091200-15292c2c-51cc-4266-abb5-50dacd54c363.png)
<br/>
另外我修改一下issue的标题，并不是卡死，是会卡几分钟，程序最后还是可以继续运行。坦率的说，这个问题只是比较影响代码调试。

**Comment by ZzSean** [comment]
根据您的截图，您的CUDA应该是11.4，建议尝试下降级为11.2的CUDA
使用nvidia-smi指令可以看到具体的CUDA版本和驱动信息

**Comment by ouyangshixiong** [comment]
我的cuda安装的是11.2
你看到的11.4是显卡驱动nvidia-driver-470 默认带的。理论上它是向后兼容的。
cuda11.2默认的显卡驱动版本是nvidia-driver-460，遗憾的是在我的PC上是无法正常工作。请看下面截图

**Comment by ouyangshixiong** [comment]
Update: 我成功切换到了Driver 460.91.03 CUDA 11.2，如下图：

![企业微信20211118-140231](https://user-images.githubusercontent.com/2086862/142361253-b36d3313-8766-4258-96c8-b9284698e4ce.png)

paddle的运行环境检查，如下图：

![企业微信20211118-140319](https://user-images.githubusercontent.com/2086862/142361311-f1f0e82c-e8fd-4dbd-9bec-50749bdc7881.png)

程序还是卡在了nn.Sequencial

![企业微信20211118-140412](https://user-images.githubusercontent.com/2086862/142361355-adac4cc7-0d9d-4b78-adf2-4a9855b865c3.png)


其中有一个cpu一直100%

**Comment by ouyangshixiong** [comment]
@ZzSean

**Comment by ZzSean** [comment]
您好，能不能提供一下可以复现的简单的demo，我这边复现一下，如有进展会及时回复您～

**Comment by ouyangshixiong** [comment]
> 您好，能不能提供一下可以复现的简单的demo，我这边复现一下，如有进展会及时回复您～

贵司的PARL库 example目录中的QMIX算法就可以复现此问题。
您也可以联系贵司 睿思，他有我的微信。
@ZzSean

**Comment by ZzSean** [comment]
你好，请您使用最新的2.2.1或者使用python3.7以上版本再尝试下

**Comment by ouyangshixiong** [comment]
> 你好，请您使用最新的2.2.1或者使用python3.7以上版本再尝试下
好的，我试试看

**Comment by ouyangshixiong** [comment]
从python3.6升级到python3.8 解决了这个问题。 @ZzSean 谢谢
