### ISSUE TITLE
python pip包找不到

### ISSUE THREAD

**Issue by Darki-luo** [PaddlePaddle/Paddle#37268]
按照安装说明通过pip源安装paddlelite，但是试了好几次都找不到，ubuntu18.04-x86满足系统要求
python -m pip install paddlelite==2.10rc0 -i https://mirror.baidu.com/pypi/simple
Looking in indexes: https://mirror.baidu.com/pypi/simple
ERROR: Could not find a version that satisfies the requirement paddlelite==2.10rc0 (from versions: none)
ERROR: No matching distribution found for paddlelite==2.10rc0

 python -m pip install paddlelite -i https://mirror.baidu.com/pypi/simple
Looking in indexes: https://mirror.baidu.com/pypi/simple
ERROR: Could not find a version that satisfies the requirement paddlelite (from versions: none)

**Comment by ZzSean** [comment]
您好，已联系paddle-lite相关负责人查看该问题，会尽快给您回复！

**Comment by weishengying** [comment]
请问你用的python版本是多少

**Comment by Darki-luo** [comment]
> 请问你用的python版本是多少
3.8.5

**Comment by weishengying** [comment]
我们只提供了3.5 3.6 3.7 3.9的python 安转包。 你可以把python版本换一下，建议换成3.7

**Comment by wadefelix** [comment]
我们并没有2.10rc0版本。
可以直接浏览器打开https://www.paddlepaddle.org.cn/whl/linux/mkl/avx/stable.html 页面，复制其中具体版本文件的下载地址，然后把它传给`pip install`
3.8.5 python就是被支持的版本，可以使用。

**Comment by Darki-luo** [comment]
> 我们只提供了3.5 3.6 3.7 3.9的python 安转包。 你可以把python版本换一下，建议换成3.7
好的
