### ISSUE TITLE
[discussion]关于编译时和运行时的区别

### ISSUE THREAD

**Issue by jacquesqiao** [PaddlePaddle/Paddle#3726]
### 主题：
Paddle编译时和运行时的区别

### 参与人：
董志宏，严春伟，乔龙飞

#### 1. 如果VarDesc作为编译时，Scope/Variable作为运行时
**实现方法**
VarDesc创建的时候无需Scope，只需要在一个全局map中保存VarDesc，InferShape需要修改对应的VarDesc即可。

**优点**：
1. 切换Scope简单，只需在Op Run的时候传入一个新的Scope，框架根据全局的VarDesc Map在其中创建对应的Var即可运行。
2. 用VarDesc存储元信息，方便做优化。
3. InferShape就可以不需要传入Scope这个参数，因为修改的VarDesc都存在于全局的map中

**缺点**：
InferShape实现复杂，编译时Infer是基于VarDesc，但是考虑到运行时size可能会被用户修改(这点不知道是否合理)，运行时也需要做InferShape，这个InferShape是基于Scope中的Variable进行，代码上会有一定的重复。

#### 2. 不带内存的Tensor作为编译时，带内存的Tensor作为运行时。
**实现方法**
Var必须创建在某个已经存在的Scope中，切换Scope之前，需要clone某个创建过Var的Scope

**优点**
InferShape只需要实现一遍，配置时和运行时都调用同样的函数即可

**缺点**
Clone的实现可能并不简单，比如多种设备类型之间内存如何同步(Scope for CPU vs Scope for GPU)

**Comment by Canpio** [comment]
`Variable创建的时候无需Scope`  ==>  `VarDesc创建的时候无需Scope`

**Comment by jacquesqiao** [comment]
InferShape 在Run的里面调用，还是在Run之外调用。
根据讨论，Run调用的时候也需要调用一次InferShape，因为有些shape只有在看到数据的时候才能推断出来

而且如果在Run的调用InferShape改变了Output的size，那么下一个Op Run的时候也需要调用InferShape。

结论就是Run需要调用InferShape

**Comment by dzhwinter** [comment]
> 切换Scope简单，只需在Op Run的时候传入一个新的Scope，框架根据全局的VarDesc Map在其中创建对应的Var即可运行。

可以在任意地方New Scope，和命名空间的语义可以对应起来
> Var必须创建在某个已经存在的Scope中，切换Scope之前，需要clone某个创建过Var的Scope

补充一点，InferShape就可以不需要传入Scope这个参数，因为修改的VarDesc都存在于全局的map中。

**Comment by QiJune** [comment]
Please consider this by the way: https://github.com/PaddlePaddle/Paddle/issues/3717#issuecomment-325537606

**Comment by gongweibao** [comment]
Close it since not activated.
