### ISSUE TITLE
使用d_loss_cov.backward()时报错

### ISSUE THREAD

**Issue by Yywwwwwww** [PaddlePaddle/Paddle#37265]
- 标题：d_loss_cov.backward()报错为Cannot find gradient of variable dygraph_tmp_398@GRAD
- 版本、环境信息：
硬件信息
当前环境高级GPU
切换环境
CPU
2
RAM
16GB
GPU
v100
显存
16GB
磁盘
100GB
GPU资源信息
算力卡余额
8.0点(0.5点/小时)
本周可使用
8.0小时
环境配置
Python版本
python 3.7
框架版本
PaddlePaddle 2.1.2

源代码：
#!/usr/bin/env python3
#　超参数准备包
import argparse
import time
import paddle
import abc
import paddle
#　数据集准备包
import os
import paddle.fluid.layers as layers
from loader import TrainDatasetFromFolder, ValidDatasetFromFolder
from paddle.io import DataLoader

# 网络初始化类
from critic import critic
from decoder import decode
from encoder import encode
# 损失函数准备包
from paddle.vision.models.vgg import vgg16    #paddle.v2.networks.vgg_16_network
from vgg_loss import VGGLoss
from paddle.nn.functional import binary_cross_entropy_with_logits, mse_loss
from ssim import _ssim_
# 优化算法准备包
from paddle.optimizer import Adam
# 网络训练准备包
from tqdm import tqdm
import gc
import numpy as np
from paddle.autograd import backward
# 画数据图准备包
import matplotlib
matplotlib.use('Agg') 
import matplotlib.pyplot as plt
import pandas as pd
# detailed 准备包
from PIL import Image
# 压缩准备包
from math import log10
# 结果存储路径包
from datetime import datetime

cpu_tensor = paddle.to_tensor(1, place=paddle.CPUPlace())
print(cpu_tensor.place)

def GeneratorLoss(stego_images, cover_images, decoded, message):
    encoder_mse = mse_loss(stego_images, cover_images)
    decoder_mse = mse_loss(decoded, message)
    return encoder_mse, decoder_mse

def AdversaryLoss(input, label):
    bce_with_logits_loss = binary_cross_entropy_with_logits(input, label)
    return bce_with_logits_loss

def random_data(cover, data_depth):
    N, _, H, W = cover.shape[0], cover.shape[1], cover.shape[2], cover.shape[3]
    shape_message=[N,data_depth]
    message = paddle.rand(shape_message)
    shape_payload=[N,data_depth,H,W]
    payload = paddle.rand(shape_payload)
    for i in range(H):
        for j in range(W):
            payload[:, :, i, j] = message
    return payload, message

def main():
    paddle.seed(42)

    ''' 1.设置超参数 '''
    parser = argparse.ArgumentParser(description='End2end data hiding for HEVC')
    parser.add_argument('--epochs', default=10, type=int)
    parser.add_argument('--data_depth', default=30, type=int)
    parser.add_argument('--hidden_size', default=64, type=int)
    parser.add_argument('--dataset_val', default="val", type=str)
    parser.add_argument('--dataset_train', default="train", type=str)
    parser.add_argument('--output', default=False, type=str)
    parser.add_argument('--train_batch_size', default=12, type=int, help='train epoch number')
    parser.add_argument('--valid_batch_size', default=12, type=int, help='valid epoch number')
    parser.add_argument('--crop_size', default=128, type=int, help='training images crop size')
    parser.add_argument('--save_interval', default=200, type=int, help='save_interval')
    parser.add_argument('--learning_rate', default=1e-3, type=float, help='learning_rate')
    args = parser.parse_args()

    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S") + "_C11_1e-3_weight2"
    print(timestamp)
    dir_val = './{}_crop128_L30/'.format(args.dataset_val) + '/' + 'test'
    if not os.path.exists(dir_val):
        os.makedirs(dir_val)
    dir_train = './{}_crop128_L30/'.format(args.dataset_train) + '/' + 'test'
    if not os.path.exists(dir_train):
        os.makedirs(dir_train)

    ''' 2.设置数据集 '''
    root_dir_val = "/home/aistudio/data" 
    root_dir_train = "/home/aistudio/data" 
    #cd /home/aistudio/data/data110281/ && unzip -qo dataset_test.zip
    train_path = os.path.join(root_dir_train, args.dataset_train)
    #print(train_path)
    #print(args.dataset)
    valid_path = os.path.join(root_dir_val, args.dataset_val)
    # 数据集预处理
    train_set = TrainDatasetFromFolder(train_path, crop_size=args.crop_size)
    valid_set = ValidDatasetFromFolder(valid_path, crop_size=args.crop_size)
    train = DataLoader(dataset=train_set, num_workers=0, batch_size=args.train_batch_size, shuffle=False)
    valid = DataLoader(dataset=valid_set, num_workers=0, batch_size=args.valid_batch_size, shuffle=False)
    
    # 查看数据预处理的结果
    #cover_train = next(iter(train))
    #print('train: cover.size() = ', cover_train.size())
    #cover_valid = next(iter(valid))
    #print('valid: cover.size() = ', cover_valid.size())

    ''' 3.选择设备(CPU或者GPU(0/1)) '''
    #device = paddle.set_device('cuda:1' if paddle.fluid.is_compiled_with_cuda() else 'cpu')
    #print("Using {} device".format(device))

    ''' 4.准备训练 '''
    # 网络初始化
    Critic = critic(args.hidden_size)
    Encode = encode(args.data_depth, args.hidden_size)
    Decode = decode(args.data_depth, args.hidden_size)
      # 上传到设备
    # Critic = Critic.to(device)
    # Encode = Encode.to(device)
    # Decode = Decode.to(device)

      # 查看参数量
    print('Critic parameters:', sum(param.numel() for param in Critic.parameters()))
    print('Encode parameters:', sum(param.numel() for param in Encode.parameters()))
    print('Decode parameters:', sum(param.numel() for param in Decode.parameters()))

    # 准备好优化算法
    adver_optimizer = Adam(args.learning_rate, parameters = Critic.parameters())
    Parm_ED=list(Encode.parameters()) + list(Decode.parameters())
    gener_optimizer = Adam(args.learning_rate, parameters = Parm_ED )

    ''' 5.开始训练 '''
    # Defined the labels used for training the discriminator/adversarial loss
    cover_label = 1
    stego_label = 0
    #　保存数据所用的变量
    #　画图所用
    epos, train_losss, train_psnrs, train_accus, train_ssims = [], [], [], [], []
    valid_losss, valid_psnrs, valid_accus, valid_ssims = [], [], [], []
    # 　保存数据所用的变量
    train_results = {'tra_loss': [], 'loss_dec': [], 'loss_enc': [], 'loss_adv': [], 'steg_sco': [], 'cove_sco': [], 'tra_psnr': [], 'tra_accu': [], 'tra_ssim': []}
    valid_results = {'val_loss': [], 'loss_dec': [], 'loss_enc': [], 'loss_adv': [], 'steg_sco': [], 'cove_sco': [], 'val_psnr': [], 'val_accu': [], 'val_ssim': [], 'val_psn2': []}
    for epoch in range(1, args.epochs + 1):
        print('Epoch {}/{}'.format(epoch, args.epochs))

        train_number, train_g_loss= 0.001, 0
        train_d_loss_cov, train_d_loss_ste, train_g_loss_dec, train_g_loss_enc, train_g_loss_adv, train_psnr, train_accu, train_ssim = 0, 0, 0, 0, 0, 0, 0, 0
        training_results = {'train_g_loss': []}
        for cover in tqdm(train):
        #for cover, _ in train:
            #cover = cover.to(device)
            batch_size = args.train_batch_size
            Critic.train()
            Encode.train()
            Decode.train()
            #gc.collect()
            with paddle.set_grad_enabled(True):
          
                # ---------------- Train the discriminator -----------------------------
                for i in range(1):
                    adver_optimizer.clear_grad()# 把模型中参数的梯度设为0

                    d_target_label_cover = paddle.full((batch_size, 1), cover_label)
                    d_target_label_stego = paddle.full((batch_size, 1), stego_label)

                    # train on cover
                    d_on_cover = Critic(cover)
                    d_loss_cov = AdversaryLoss(d_on_cover, d_target_label_cover)
                    d_loss_cov.backward()
            
                    # train on stego
                    payload, message = random_data(cover, args.data_depth)
                    stego = Encode(cover, payload)

                    unload = Decode(stego)
                
                    d_on_stego = Critic(stego.detach())# detach的作用是阻断反向梯度传播
                    d_loss_ste = AdversaryLoss(d_on_stego, d_target_label_stego)
                    d_loss_ste.backward()

                    adver_optimizer.step()

                # --------------Train the generator (encoder-decoder) ---------------------
                gener_optimizer.clear_grad() # 把模型中参数的梯度设为0
                g_target_label_stego = paddle.full((batch_size, 1), cover_label)
                # target label for stego images should be 'cover', because we want to fool the discriminator
                g_on_stego = Critic(stego)
                g_loss_adv = AdversaryLoss(g_on_stego, g_target_label_stego)
                g_loss_enc, g_loss_dec = GeneratorLoss(stego, cover, unload, message)

                # g_loss = g_loss_dec + g_loss_enc + g_loss_adv
                g_loss = g_loss_dec + 0.7 * g_loss_enc + 0.001 * g_loss_adv
                # g_loss = g_loss_dec + g_loss_enc + 0.001 * g_loss_adv
                # g_loss = g_loss_dec + 5 * g_loss_enc + 0.001 * g_loss_adv
                # g_loss = g_loss_dec + 2 * g_loss_enc + 0.001 * g_loss_adv
                # g_loss = g_loss_dec + 1.2 * g_loss_enc + 0.001 * g_loss_adv
                # g_loss = g_loss_dec + 1.5 * g_loss_enc + 0.001 * g_loss_adv

                # g_loss = 0.5 * g_loss_dec + 1.2 * g_loss_enc + 0.001 * g_loss_adv
                # g_loss = 1.2 * g_loss_dec + 0.5 * g_loss_enc + 0.001 * g_loss_adv
                # g_loss = 0.5 * g_loss_dec + 0.1 * g_loss_enc + 0.001 * g_loss_adv
                # g_loss = 0.8 * g_loss_dec + 0.1 * g_loss_enc + 0.001 * g_loss_adv
                # g_loss = 1.0 * g_loss_dec + 0.1 * g_loss_enc + 0.001 * g_loss_adv
                # g_loss = 1.0 * g_loss_dec + 0.5 * g_loss_enc + 0.001 * g_loss_adv
                # g_loss = 1.0 * g_loss_dec + 0.3 * g_loss_enc + 0.001 * g_loss_adv

                g_loss.backward()

                gener_optimizer.step()  # 通过梯度下降执行一步参数更新

                # 改变psnr的计算方式
                cover0 = np.round(255 * ((cover.numpy() * 0.5) + 0.5))
                stego0 = np.round(255 * ((stego.numpy() * 0.5) + 0.5))
                cover0 = 	paddle.to_tensor(cover0)
                stego0 = 	paddle.to_tensor(stego0)
                mse = mse_loss(stego0, cover0)
                psnr = (10 * paddle.log10(255 * 255 / mse)).item()

                decoded = unload.detach().cpu().numpy().round().clip(0, 1)
                accu = 1 - np.sum(np.abs(decoded - message.detach().cpu().numpy())) / (batch_size * message.shape[1])
                ssim = _ssim_(cover, stego).item()

                train_number += batch_size
                train_g_loss += g_loss.item() * batch_size
                train_g_loss_dec += g_loss_dec.item() * batch_size
                train_g_loss_enc += g_loss_enc.item() * batch_size
                train_g_loss_adv += g_loss_adv.item() * batch_size
                train_d_loss_ste += d_loss_ste.item() * batch_size
                train_d_loss_cov += d_loss_cov.item() * batch_size
                train_psnr += psnr * batch_size
                train_accu += accu * batch_size
                train_ssim += ssim * batch_size

                training_results['train_g_loss'].append(train_g_loss/ train_number)

                data_frame = pd.DataFrame(data={'train_g_loss': training_results['train_g_loss']})
                data_frame.to_csv(dir + '/B_train_data_{}.csv'.format(epoch))

            # 保存训练过程的数据 save train_loss,画图用
            epos.append(epoch)
            train_losss.append(train_g_loss / train_number)
            train_psnrs.append(train_psnr / train_number)
            train_accus.append(train_accu / train_number)
            train_ssims.append(train_ssim / train_number)

            # 保存训练过程的数据 save train_loss
            train_results['tra_loss'].append(train_g_loss / train_number)
            train_results['loss_dec'].append(train_g_loss_dec / train_number)
            train_results['loss_enc'].append(train_g_loss_enc / train_number)
            train_results['loss_adv'].append(train_g_loss_adv / train_number)
            train_results['steg_sco'].append(train_d_loss_ste / train_number)
            train_results['cove_sco'].append(train_d_loss_cov / train_number)
            train_results['tra_psnr'].append(train_psnr / train_number)
            train_results['tra_accu'].append(train_accu / train_number)
            train_results['tra_ssim'].append(train_ssim / train_number)

            data_frame = pd.DataFrame(data={'     tra_loss     ': train_results['tra_loss'], '     loss_dec     ': train_results['loss_dec'],
                                            '     loss_enc     ': train_results['loss_enc'], '     loss_adv     ': train_results['loss_adv'],
                                            '     steg_sco     ': train_results['steg_sco'], '     cove_sco     ': train_results['cove_sco'],
                                            '     tra_psnr     ': train_results['tra_psnr'], '     tra_accu     ': train_results['tra_accu'],
                                            '     tra_ssim     ': train_results['tra_ssim']},
                                    index=range(1, epoch + 1))
            data_frame.to_csv(dir + '/A_train_data.csv', index_label='Epoch')

        # 保存模型参数，每训练save_interval个epoch 保存一次model
        if epoch % args.save_interval == 0:
            paddle.save(Critic.state_dict(), dir + '/Z%d_epoch_Critic.pth' % (epoch))
            paddle.save(Encode.state_dict(), dir + '/Z%d_epoch_Encode.pth' % (epoch))
            paddle.save(Decode.state_dict(), dir + '/Z%d_epoch_Decode.pth' % (epoch))

        valid_number, valid_g_loss = 0.001, 0
        valid_d_loss_cov, valid_d_loss_ste, valid_g_loss_dec, valid_g_loss_enc, valid_g_loss_adv, \
        valid_psnr, valid_accu, valid_ssim, valid_psn2, psn2 = 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
        BatchNumber = 0
        for cover in tqdm(valid):
            cover = cover.to(device)
            batch_size = cover.size(0)
            BatchNumber += 1
            Critic.eval()# 进入eval模式 （测试模式参数固定，只有前向传播）
            Encode.eval()
            Decode.eval()
            with paddle.clear_grad():
                d_target_label_cover = paddle.full((batch_size, 1), cover_label, device=device)
                d_target_label_stego = paddle.full((batch_size, 1), stego_label, device=device)
                g_target_label_stego = paddle.full((batch_size, 1), cover_label, device=device)

                d_on_cover = Critic(cover)
                d_loss_cov = AdversaryLoss(d_on_cover, d_target_label_cover)

                payload, message = random_data(cover, args.data_depth, device)
                stego = Encode(cover, payload)
                
                unload = Decode(stego)

                d_on_stego = Critic(stego)
                d_loss_ste = AdversaryLoss(d_on_stego, d_target_label_stego)

                g_on_stego = Critic(stego)
                g_loss_adv = AdversaryLoss(g_on_stego, g_target_label_stego)
                g_loss_enc, g_loss_dec = GeneratorLoss(stego, cover, unload, message)

                # g_loss = g_loss_dec + g_loss_enc + g_loss_adv
                g_loss = g_loss_dec + 0.7 * g_loss_enc + 0.001 * g_loss_adv
                # g_loss = g_loss_dec + g_loss_enc + 0.001 * g_loss_adv
                # g_loss = g_loss_dec + 5 * g_loss_enc + 0.001 * g_loss_adv
                # g_loss = g_loss_dec + 2 * g_loss_enc + 0.001 * g_loss_adv
                # g_loss = g_loss_dec + 1.2 * g_loss_enc + 0.001 * g_loss_adv
                # g_loss = g_loss_dec + 1.5 * g_loss_enc + 0.001 * g_loss_adv

                # g_loss = 0.5 * g_loss_dec + 1.2 * g_loss_enc + 0.001 * g_loss_adv
                # g_loss = 1.2 * g_loss_dec + 0.5 * g_loss_enc + 0.001 * g_loss_adv
                # g_loss = 0.5 * g_loss_dec + 0.1 * g_loss_enc + 0.001 * g_loss_adv
                # g_loss = 0.8 * g_loss_dec + 0.1 * g_loss_enc + 0.001 * g_loss_adv
                # g_loss = 1.0 * g_loss_dec + 0.1 * g_loss_enc + 0.001 * g_loss_adv
                # g_loss = 1.0 * g_loss_dec + 0.5 * g_loss_enc + 0.001 * g_loss_adv
                # g_loss = 1.0 * g_loss_dec + 0.3 * g_loss_enc + 0.001 * g_loss_adv

                # 改变psnr的计算方式
                cover1 = np.round(255 * ((cover.data.cpu().numpy() * 0.5) + 0.5))
                stego1 = np.round(255 * ((stego.data.cpu().numpy() * 0.5) + 0.5))
                cover1 = paddle.to_tensor(cover1)
                stego1 = paddle.to_tensor(stego1)
                mse = mse_loss(stego1, cover1)
                psnr = (10 * paddle.log10(255 * 255 / mse)).item()

                decoded = unload.detach().cpu().numpy().round().clip(0, 1)
                accu = 1 - np.sum(np.abs(decoded - message.detach().cpu().numpy())) / (batch_size * message.shape[1])
                ssim = _ssim_(cover, stego).item()

                valid_number += batch_size
                valid_g_loss += g_loss.item() * batch_size
                valid_g_loss_dec += g_loss_dec.item() * batch_size
                valid_g_loss_enc += g_loss_enc.item() * batch_size
                valid_g_loss_adv += g_loss_adv.item() * batch_size
                valid_d_loss_ste += d_loss_ste.item() * batch_size
                valid_d_loss_cov += d_loss_cov.item() * batch_size
                valid_psnr += psnr * batch_size
                valid_accu += accu * batch_size
                valid_ssim += ssim * batch_size
                valid_psn2 += psn2 * batch_size

                # 开始：将Valid_CoverImages进行可视化
                if epoch % 100 == 0:
                    cover_visual = cover.permute(0, 2, 3, 1).detach().cpu().data.numpy()
                    cover_visual_path = dir + "/Valid_CoverImages/"
                    os.makedirs(cover_visual_path, exist_ok=True)
                    count = 0
                    for i in range(cover_visual.shape[0]):
                        count += 1
                        cover_visual[i] = np.round((255 * ((cover_visual[i] + 1.0) / 2.0)))
                        image = cover_visual[i].astype(dtype='uint8')
                        # image = np.squeeze(image, axis=2)
                        # print("cover_visual_{}.shape = {}".format(i, cover_visual[i].shape))
                        # print("type = {}".format(cover_visual[0][0][0][0].dtype))
                        # print("np.max = {}, np.min = {}".format(np.max(cover_visual[i]), np.min(cover_visual[i])))
                        img = Image.fromarray(image)
                        img.save(cover_visual_path + "{}_{:0>4d}.bmp".format(epoch, (BatchNumber - 1) * 12 + count), 'bmp')
                # 结束：将Valid_CoverImages进行可视化

                # 开始：将Valid_StegoImages进行可视化
                if epoch % 100 == 0:
                    stego_visual_path = dir + "/Valid_StegoImages/"
                    os.makedirs(stego_visual_path, exist_ok=True)
                    count = 0
                    for i in range(stego.size(0)):
                        stego_visual = stego[i].permute(1, 2, 0).detach().cpu().data.numpy()
                        count += 1
                        stego_visual = np.round(255.0 * ((stego_visual + 1.0) / 2.0))
                        image = stego_visual.astype(dtype='uint8')
                        # image = np.squeeze(image, axis=2)
                        img = Image.fromarray(image)
                        img.save(stego_visual_path + "{}_{:0>4d}.bmp".format(epoch, (BatchNumber - 1) * 12 + count), 'bmp')
                # 结束：将Valid_StegoImages进行可视化

                # 开始：将valid上cover写入相应路径txt_path
                txt_path = dir + "/valid_cover_detailed/"
                os.makedirs(txt_path, exist_ok=True)
                for i in range(cover.shape[0]):
                    if epoch == 1 and BatchNumber == 1 and i == 0:
                        file = open(txt_path + "B_maxANDmin.txt", 'w')
                    else:
                        file = open(txt_path + "B_maxANDmin.txt", 'a')
                    f = cover[i].data.cpu().numpy()
                    file.write("epoch:{:0>3d}; image:{:0>4d}; np.max() = {:.8f}; np.min() = {:.8f}".format(epoch, (BatchNumber - 1) * 12 + 1 + i, np.max(f), np.min(f)) + "\n")
                    file.close()
                # 结束：将valid上cover写入相应路径txt_path

                # 开始：将valid上stego写入相应路径txt_path
                txt_path = dir + "/valid_stego_detailed/"
                os.makedirs(txt_path, exist_ok=True)
                for i in range(stego.shape[0]):
                    if epoch == 1 and BatchNumber == 1 and i == 0:
                        file = open(txt_path + "B_maxANDmin.txt", 'w')
                    else:
                        file = open(txt_path + "B_maxANDmin.txt", 'a')
                    f = stego[i].data.cpu().numpy()
                    file.write("epoch:{:0>3d}; image:{:0>4d}; np.max() = {:.8f}; np.min() = {:.8f}".format(epoch, (BatchNumber - 1) * 12 + 1 + i, np.max(f), np.min(f)) + "\n")
                    file.close()
                # 结束：将valid上stego写入相应路径txt_path

        # 保存验证过程的数据 save val_loss\val_psnr\val_acc, 画图用
        valid_losss.append(valid_g_loss / valid_number)
        valid_psnrs.append(valid_psnr / valid_number)
        valid_accus.append(valid_accu / valid_number)
        valid_ssims.append(valid_ssim / valid_number)

        # 保存验证过程的数据 save val_loss\val_psnr\val_acc
        valid_results['val_loss'].append(valid_g_loss / valid_number)
        valid_results['loss_dec'].append(valid_g_loss_dec / valid_number)
        valid_results['loss_enc'].append(valid_g_loss_enc / valid_number)
        valid_results['loss_adv'].append(valid_g_loss_adv / valid_number)
        valid_results['steg_sco'].append(valid_d_loss_ste / valid_number)
        valid_results['cove_sco'].append(valid_d_loss_cov / valid_number)
        valid_results['val_psnr'].append(valid_psnr / valid_number)
        valid_results['val_accu'].append(valid_accu / valid_number)
        valid_results['val_ssim'].append(valid_ssim / valid_number)
        valid_results['val_psn2'].append(valid_psn2 / valid_number)

        data_frame = pd.DataFrame(
            data={'     val_loss     ': valid_results['val_loss'], '     loss_dec     ': valid_results['loss_dec'],
                  '     loss_enc     ': valid_results['loss_enc'], '     loss_adv     ': valid_results['loss_adv'],
                  '     steg_sco     ': valid_results['steg_sco'], '     cove_sco     ': valid_results['cove_sco'],
                  '     val_psnr     ': valid_results['val_psnr'], '     val_accu     ': valid_results['val_accu'],
                  '     val_ssim     ': valid_results['val_ssim'], '     val_psn2     ': valid_results['val_psn2']},
            index=range(1, epoch + 1))
        data_frame.to_csv(dir + '/A_valid_data.csv', index_label='Epoch')

    print("Show resuls......Show one pictures")
    fig = plt.figure()

    b = plt.subplot(221)
    b.set_title("Loss", fontsize=18)
    b.set_xlabel("epoch", fontsize=14)
    b.set_ylabel("loss", fontsize=14)
    b.plot(epos, train_losss, color='green', label='train loss')
    b.plot(epos, valid_losss, color='red', label='valid loss')
    b.legend()  # 显示上面的label
    b.grid()
    plt.tight_layout()  # 设置间隔
    c = plt.subplot(222)
    c.set_title("valid PSNR", fontsize=18)
    c.set_xlabel("epoch", fontsize=14)
    c.set_ylabel("psnr", fontsize=14)
    c.plot(epos, train_psnrs, color='green', label='train psnr')
    c.plot(epos, valid_psnrs, color='red', label='valid psnr')
    c.legend()  # 显示上面的label
    c.grid()
    plt.tight_layout()  # 设置间隔
    d = plt.subplot(223)
    d.set_title("valid ACCU", fontsize=18)
    d.set_xlabel("epoch", fontsize=14)
    d.set_ylabel("accu", fontsize=14)
    d.plot(epos, train_accus, color='green', label='train accu')
    d.plot(epos, valid_accus, color='red', label='valid accu')
    d.legend()  # 显示上面的label
    d.grid()
    plt.tight_layout()  # 设置间隔
    e = plt.subplot(224)
    e.set_title("valid SSIM", fontsize=18)
    e.set_xlabel("epoch", fontsize=14)
    e.set_ylabel("ssim", fontsize=14)
    e.plot(epos, train_ssims, color='green', label='train ssim')
    e.plot(epos, valid_ssims, color='red', label='valid ssim')
    e.legend()  # 显示上面的label
    e.grid()
    fig.savefig(dir + "/A_result.png")

if __name__ == '__main__':
    start = time.perf_counter()
    
    main()
    end = time.perf_counter()
    print("time = {:.3f}h".format((end - start) / 3600))

报错：
Traceback (most recent call last):
  File "train.py", line 480, in <module>
    main()
  File "train.py", line 176, in main
    d_loss_cov.backward()
  File "<decorator-gen-122>", line 2, in backward
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
    return wrapped_func(*args, **kwargs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/framework.py", line 227, in __impl__
    return func(*args, **kwargs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/varbase_patch_methods.py", line 239, in backward
    framework._dygraph_tracer())
RuntimeError: (NotFound) Cannot find gradient of variable dygraph_tmp_398@GRAD
  [Hint: Expected iter != accumulators_.end() == true, but received iter != accumulators_.end():0 != true:1.] (at /paddle/paddle/fluid/imperative/basic_engine.cc:366)

**Comment by ZzSean** [comment]
您好，我这边正在尝试复现您的问题，有进展了会及时回复。也请您排查一下代码可能存在的问题，谢谢！

**Comment by ZzSean** [comment]
您好，我这边无法运行您上述提供的代码，能否提供一个可以复现的简单demo？

**Comment by Yywwwwwww** [comment]
这边有vscode上可以运行的代码，在paddlepaddle平台上没有可复现的，需要提供给你vscode上的代码吗？


-----原始邮件-----
发件人:"Zhang Zheng" ***@***.***>
发送时间:2021-11-17 16:05:09 (星期三)
收件人: PaddlePaddle/Paddle ***@***.***>
抄送: Yywwwwwww ***@***.***>, Author ***@***.***>
主题: Re: [PaddlePaddle/Paddle] 使用d_loss_cov.backward()时报错 (Issue #37265)






您好，我这边无法运行您上述提供的代码，能否提供一个可以复现的简单demo？

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by ZzSean** [comment]
您好，本地可以复现的代码就可以，V100上可以直接运行的

**Comment by CuberrChen** [comment]
遇到了相似问题。下午运行的时候没报错，晚上再进入AiStudio环境运行程序时就报错了。。。整懵了

**Comment by CuberrChen** [comment]
> 

将版本从2.2切换回2.1.2后可以正常运行了...看来是2.2更新后造成的bug？

**Comment by ZzSean** [comment]
> 这边有vscode上可以运行的代码，在paddlepaddle平台上没有可复现的，需要提供给你vscode上的代码吗？
> […](#)
> -----原始邮件----- 发件人:"Zhang Zheng" ***@***.***> 发送时间:2021-11-17 16:05:09 (星期三) 收件人: PaddlePaddle/Paddle ***@***.***> 抄送: Yywwwwwww ***@***.***>, Author ***@***.***> 主题: Re: [PaddlePaddle/Paddle] 使用d_loss_cov.backward()时报错 (Issue #37265) 您好，我这边无法运行您上述提供的代码，能否提供一个可以复现的简单demo？ — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.

您好，请问现在是否已恢复正常？若无请麻烦提供下复现代码
