### ISSUE TITLE
VisualDL的使用

### ISSUE THREAD

**Issue by zmdcs** [PaddlePaddle/Paddle#37271]
VisualDL每次都是指定的一整个文件夹，可是那个文件夹下有很多.log文件呀，它是按照文件夹第一个文件画的loss图吗？那如何指定其他文件呢？

**Comment by JamesLim-sy** [comment]
hi，这个问题应该不属于paddle框架的范畴，请提交issue至 https://github.com/PaddlePaddle/VisualDL  Repo中

**Comment by zmdcs** [comment]
嗯嗯，提了，谢谢
