### ISSUE TITLE
'Tensor' object has no attribute 'permute'

### ISSUE THREAD

**Issue by tsijeodhsjsh** [PaddlePaddle/Paddle#37291]
问题：
在执行cover_visual = cover.permute(0, 2, 3, 1).data.cpu().numpy()
出现的如下错误：'Tensor' object has no attribute 'permute'
应如何修改

**Comment by JamesLim-sy** [comment]
```python
# if  cover`s shape is   [3, 4, 5, 6], then  paddle.reshape works as permute.
cover_visual = paddle.reshape(x, [3, 5, 6, 4]).numpy()
```
需要注意的是: paddle.reshape(x, shape=[....]) api中只接受 shape值，而不接收axis值.
api具体用法见：https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/reshape_cn.html#reshape

**Comment by mywordwin** [comment]
> 问题： 在执行cover_visual = cover.permute(0, 2, 3, 1).data.cpu().numpy() 出现的如下错误：'Tensor' object has no attribute 'permute' 应如何修改

你好，我也遇到了同样的问题，请问解决了吗

**Comment by mywordwin** [comment]
> 问题： 在执行cover_visual = cover.permute(0, 2, 3, 1).data.cpu().numpy() 出现的如下错误：'Tensor' object has no attribute 'permute' 应如何修改

你好，我也遇到了同样的问题，请问解决了吗
