### ISSUE TITLE
添加文档，解释PyDataProvider中的input_types的dim是什么意思

### ISSUE THREAD

**Issue by reyoung** [PaddlePaddle/Paddle#373]
现在的PyDataProvider中，其实没有解释input_types的dimension究竟是什么意思。这导致用户会有一些迷惑。

现在文档的地址是 [中文](http://www.paddlepaddle.org/doc_cn/ui/data_provider/pydataprovider2.html#input-types) 和 [英文](http://www.paddlepaddle.org/doc/ui/data_provider/pydataprovider2.html#input-types)。
文档的代码地址是 [中文](https://github.com/baidu/Paddle/blob/develop/doc_cn/ui/data_provider/pydataprovider2.rst) 和 [英文](https://github.com/baidu/Paddle/blob/develop/doc/ui/data_provider/pydataprovider2.rst)。

相关的issue #369

**Comment by luotao1** [comment]
v2 api不使用PyDataProvider，对应的文档就不更新了。
