### ISSUE TITLE
预测分析任务的量化指标都有什么？

### ISSUE THREAD

**Issue by Sunyingbin** [PaddlePaddle/Paddle#37303]
预测分析任务的量化指标都有什么？怎么判断训练的模型可用？满足要求？

**Comment by JamesLim-sy** [comment]
请问有没有具体的预测分析任务案例?

**Comment by Sunyingbin** [comment]
> 请问有没有具体的预测分析任务案例?

最近做的是能源预测相关项目，预测能源负荷值

**Comment by JamesLim-sy** [comment]
这个主要看用户对于目标的算法设计的考量，用户可以调用已有的模型库和losss，或者设计定制化模型和loss 实现对于所关注目标的，找到了一篇能源预测任务的相关文章[Deep Learning for Time Series Forecasting: The Electric Load Case](https://arxiv.org/abs/1907.09207)，可供案例参考
