### ISSUE TITLE
新手入门-线性回归输入数据格式错误

### ISSUE THREAD

**Issue by buptwds** [PaddlePaddle/Paddle#3733]
PaddlePaddle新手入门例子（线性回归）：http://doc.paddlepaddle.org/doc_cn/getstarted/concepts/use_concepts_cn.html
提示输入数据格式有误，ValueError: The input should be a vector, please check your input data.

**Comment by luotao1** [comment]
在最新的develop分支文档：http://doc.paddlepaddle.org/develop/doc_cn/getstarted/concepts/use_concepts_cn.html 是正确的。
