### ISSUE TITLE
cudnn_status_internal_error

### ISSUE THREAD

**Issue by lgcy** [PaddlePaddle/Paddle#37342]
pip install paddlepaddle-gpu的v2.0.0, v.2.2.0版本都会出现这样的错误，
![Ir](https://user-images.githubusercontent.com/26407517/142402719-4f8d5457-a454-4290-ad27-6603a50f7084.jpg)

**Comment by thisjiang** [comment]
您好，从报错信息上看，错误可能是由于cudnn版本太低导致的，建议参考 https://www.paddlepaddle.org.cn/install/quick?docurl=/documentation/docs/zh/install/pip/linux-pip.html#old-version-anchor-4-%E4%BA%8C%E3%80%81%E5%BC%80%E5%A7%8B%E5%AE%89%E8%A3%85 ，如未能解决还请继续反馈，谢谢！
![image](https://user-images.githubusercontent.com/31386411/142406300-d453adff-78e4-48b8-bda3-cb18dc1eab8e.png)

**Comment by lgcy** [comment]
pip install paddlepaddle-gpu==2.2.0.post110 在cuda11.0, cudnn8.0.5上依旧存在问题，完成满足上述要求

**Comment by lgcy** [comment]
还有docker pull paddlepaddle/paddle:2.2.0-gpu-cuda10.2-cudnn7 这个镜像，然后docker run之后，会出现 Permission denied:'/root/.cache'

**Comment by lgcy** [comment]
paddlepaddle/paddle:2.2.0-gpu-cuda10.2-cudnn7 这个镜像中进行paddle.utils.run_check()，出现同样的错误 @thisjiang

**Comment by pangyoki** [comment]
> paddlepaddle/paddle:2.2.0-gpu-cuda10.2-cudnn7 这个镜像中进行paddle.utils.run_check()，出现同样的错误 @thisjiang

你好，麻烦打印下 nvidia-smi、nvcc -V看看

**Comment by lgcy** [comment]
![IMG_20211119_144846](https://user-images.githubusercontent.com/26407517/142578115-dadcaf80-16ea-4923-bc08-ee624f2dc9e1.jpg)
@pangyoki

**Comment by pangyoki** [comment]
> ![IMG_20211119_144846](https://user-images.githubusercontent.com/26407517/142578115-dadcaf80-16ea-4923-bc08-ee624f2dc9e1.jpg) @pangyoki

这个环境看起来没有问题，我刚刚测试了下这个镜像，也能正常使用。
麻烦再把镜像里 `paddle.utils.run_check()` 的报错截图发一下，我再看看。因为镜像里的cudnn版本应该是不会有问题的。

**Comment by lgcy** [comment]
> > ![IMG_20211119_144846](https://user-images.githubusercontent.com/26407517/142578115-dadcaf80-16ea-4923-bc08-ee624f2dc9e1.jpg) @pangyoki
> 
> 这个环境看起来没有问题，我刚刚测试了下这个镜像，也能正常使用。 麻烦再把镜像里 `paddle.utils.run_check()` 的报错截图发一下，我再看看。因为镜像里的cudnn版本应该是不会有问题的。

![IMG2](https://user-images.githubusercontent.com/26407517/142587772-e46fef85-5379-4525-8a8b-9f68861b9448.jpg)

**Comment by pangyoki** [comment]
麻烦再使用`echo $LD_LIBRARY_PATH`打印下环境变量。
使用`find / -name "libcudnn*"`打印下cudnn库所在路径。
确认下cudnn库所在路径是否在环境变量中。

**Comment by lgcy** [comment]
> 麻烦再使用`echo $LD_LIBRARY_PATH`打印下环境变量。 使用`find / -name "libcudnn*"`打印下cudnn库所在路径。 确认下cudnn库所在路径是否在环境变量中。

找到原因了，是第一块显卡有别人的程序在跑，但是为什么非要是一张空卡，才能成功呢？希望交代一下，省得后面的人踩坑

**Comment by pangyoki** [comment]
> > 麻烦再使用`echo $LD_LIBRARY_PATH`打印下环境变量。 使用`find / -name "libcudnn*"`打印下cudnn库所在路径。 确认下cudnn库所在路径是否在环境变量中。
> 
> 找到原因了，是第一块显卡有别人的程序在跑，但是为什么非要是一张空卡，才能成功呢？希望交代一下，省得后面的人踩坑

是的，我刚还准备回复这个。因为run_check里需要跑一个简单的网络来验证安装的正确性，单卡验证默认是在第0号卡上执行。
至少需要预留一些显存来验证网络的执行情况。

**Comment by lgcy** [comment]
> > > 麻烦再使用`echo $LD_LIBRARY_PATH`打印下环境变量。 使用`find / -name "libcudnn*"`打印下cudnn库所在路径。 确认下cudnn库所在路径是否在环境变量中。
> > 
> > 
> > 找到原因了，是第一块显卡有别人的程序在跑，但是为什么非要是一张空卡，才能成功呢？希望交代一下，省得后面的人踩坑
> 
> 是的，我刚还准备回复这个。因为run_check里需要跑一个简单的网络来验证安装的正确性，单卡验证默认是在第0号卡上执行。 至少需要预留一些显存来验证网络的执行情况。

我也测试了，第一张卡空着，其他卡有程序，还是会出错

**Comment by pangyoki** [comment]
> > > > 麻烦再使用`echo $LD_LIBRARY_PATH`打印下环境变量。 使用`find / -name "libcudnn*"`打印下cudnn库所在路径。 确认下cudnn库所在路径是否在环境变量中。
> > > 
> > > 
> > > 找到原因了，是第一块显卡有别人的程序在跑，但是为什么非要是一张空卡，才能成功呢？希望交代一下，省得后面的人踩坑
> > 
> > 
> > 是的，我刚还准备回复这个。因为run_check里需要跑一个简单的网络来验证安装的正确性，单卡验证默认是在第0号卡上执行。 至少需要预留一些显存来验证网络的执行情况。
> 
> 我也测试了，第一张卡空着，其他卡有程序，还是会出错

这是因为run_check还会检测多卡的执行，所以其他卡被占用会导致多卡执行报错。

run_check的流程是先检测单卡静态图、动态图的执行，然后验证多卡执行。单卡验证默认是0号卡。

平时验证的话就用`export CUDA_VISIBLE_DEVICES=3,4`这种形式来选择空闲卡哈。
