### ISSUE TITLE
PS异步训练模式下server出现core

### ISSUE THREAD

**Issue by Li-Jiajie** [PaddlePaddle/Paddle#37346]
当DistributedStrategy的a_sync=True时，server会core dump，a_sync=False时就正常
2server、3worker，CPU模式，Adam和SGD都会在如图位置core，请问是什么问题呢
![image](https://user-images.githubusercontent.com/35255760/142410218-810fafef-0882-4cd7-a099-7839d646d51a.png)

**Comment by thisjiang** [comment]
您好，报错信息需要复现代码，请提供代码和环境信息，我们复现后会尽快回复您～

**Comment by Li-Jiajie** [comment]
> 您好，报错信息需要复现代码，请提供代码和环境信息，我们复现后会尽快回复您～

昨天是我自己实现了一个DLRM发现core，今天下午正巧看到PaddleRec更新，提供了官方的DLRM示例：
https://github.com/PaddlePaddle/PaddleRec/tree/release/2.2.0/models/rank/dlrm

但是我用官方的代码，依然会core。clone PaddleRec之后，先去dataset里下载好数据集，然后运行以下命令：
fleetrun --worker_num=4 --server_num=3 tools/static_ps_trainer.py -m models/rank/dlrm/config_bigdata.yaml

报错和之前一样（我的代码在同步模式可以运行，PaddleRec这份代码在同步异步都会core）
Paddle版本：2.2.0（CPU）
Python: 3.6.8
CentOS Linux release 7.2 (Final)

**Comment by Li-Jiajie** [comment]
@sandyhouse
