### ISSUE TITLE
The installed Paddle is compiled with CUDNN 8.2, but CUDNN version in your machine is 8.1

### ISSUE THREAD

**Issue by wikithink** [PaddlePaddle/Paddle#37349]
paddle检查时，出现警告：
The installed Paddle is compiled with CUDNN 8.2, but CUDNN version in your machine is 8.1

我是参照官方推荐的安装方式：
python -m pip install paddlepaddle-gpu==2.2.0.post112 -f https://www.paddlepaddle.org.cn/whl/windows/mkl/avx/stable.html
官方推荐CUDA 11.2搭配8.1.1使用，为什么装了8.1.1反而有警告？
![image](https://user-images.githubusercontent.com/18325017/142420205-cdaf2e93-f2f9-417b-a804-d7c2f1318ccd.png)

我尝试安装了8.2的cudnn后，警告消失了。官方文档是不是需要更新一下？

环境如下：
win10 x64
RTX3060
CUDA 11.2.152
cudnn 8.1.1
python 3.8.8 x64

**Comment by thisjiang** [comment]
您好，您的反馈对产品非常有价值，我们会尽快改进，感谢您提出的宝贵意见，谢谢。

**Comment by pangyoki** [comment]
你好，麻烦使用`paddle.version.cudnn()` API查看一下这个安装包的cudnn版本信息。
windows版本的安装包可能使用的是cudnn8.2，我们这边也在确认。确认完毕后会更新文档。
谢谢反馈。

**Comment by betterpig** [comment]
你好，目前在Windows平台 CUDA 11.2对应的cudnn版本为8.2.1，已更新Windows安装文档。

**Comment by Laciniata** [comment]
> 你好，目前在Windows平台 CUDA 11.2对应的cudnn版本为8.2.1，已更新Windows安装文档。

我用conda安装遇到了相同的问题，而且用conda安装8.2版cudnn会出现环境冲突，请问是否对conda版进行了相同的修复？

我使用的安装指令为：`conda install paddlepaddle-gpu==2.2.2 cudatoolkit=11.2 -c https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/Paddle/ -c conda-forge`

**Comment by XieYunshen** [comment]
> 

直接使用这个命令会默认安装8.1版本的cudnn，但应该不会报错，能否贴一下报错信息呢？

**Comment by XieYunshen** [comment]
@Laciniata 能否贴一下报错截图呢？使用命令会默认安装8.1版本的cudnn，应该不会报错；可以使用`conda create -n env_name python=3.7`创建新的conda环境，然后执行安装命令试一下；

**Comment by Laciniata** [comment]
> @Laciniata 能否贴一下报错截图呢？使用命令会默认安装8.1版本的cudnn，应该不会报错；可以使用`conda create -n env_name python=3.7`创建新的conda环境，然后执行安装命令试一下；

之前用conda安装的环境中，检查时的Warning也是 “The installed Paddle is compiled with CUDNN 8.2, but CUDNN version in your machine is 8.1”。

后来我把虚拟环境删了，又新开了一个虚拟环境，并改用pip安装，就没有问题了。如果之后我在其他机器安装的话会尝试复现一下。

**Comment by HeyDavid633** [comment]
我在Linux上从源码编译`Paddle3.0.0b1`有同样的问题，但通过手动移动`cudnn`文件解决问题

基本环境所为拉取镜像中的原始配置 `registry.baidubce.com/paddlepaddle/paddle:latest-dev-cuda12.0-cudnn8.9-trt8.6-gcc12.2`。通过查询可知该容器的配置为:
+ ubuntu 20.04
+ Python 3.10.14 （默认是3.9 手动切过来的 --- pip一样要切过来）
+ gcc / cmake等的版本都符合可以直接编译的要求

成功编译并安装`.whl`以后，在运行时出现问题 --- `cudnn`版本不匹配
```shell
W0827 08:46:12.611279 70948 gpu_resources.cc:299] WARNING: device: 0. The installed Paddle is compiled with CUDNN 8.9, but CUDNN version in your machine is 8.8, which may cause serious incompatible bug. Please recompile or reinstall Paddle with compatible CUDNN version.
```
然而我实际输出 `print("paddle cudnn version: ", paddle.version.cudnn())`版本也是8.9.1
并且在容器中检查一般安装cudnn的位置 `/usr/local/cuda/include`， **根本没有cudnn文件**
所以此处并不知为何说为 `cudnn8.8` 与编译所使用的 `cudnn8.9.1` 不匹配

解决方案：
1. 重新`cmake`时发现了输出 `200001-- Current cuDNN header is /usr/include/cudnn_version.h Current cuDNN version is v8.9.1.` 记录下来这个路径`/usr/include/`。然后正常 `make`。
2. 到刚刚记录的这个目录下`/usr/include/`，手动把cudnn安装时对应的文件移动到 往常[从官网安装cudnn的位置](https://blog.csdn.net/h3c4lenovo/article/details/119003405)，即
`cp /usr/lib/libcudnn* /usr/local/cuda/lib64`
`cp /usr/include/cudnn* /usr/local/cuda/include`
3. 重新运行paddle，发现正确识别了cudnn版本为8.9.1

总结：使用官方给的容器，但其中的`cudnn`没有安装在官方推荐的位置，报错信息说8.8与8.9的版本不匹配属于无稽之谈，里面根本就没有安装`cudnn8.8`的版本。通过手动挪动cudnn的位置解决问题。

**Comment by zjykzj** [comment]
> 你好，麻烦使用`paddle.version.cudnn()` API查看一下这个安装包的cudnn版本信息。 windows版本的安装包可能使用的是cudnn8.2，我们这边也在确认。确认完毕后会更新文档。 谢谢反馈。

拉取最新release/2.8 7a4fc25，在容器2.6.2-gpu-cuda11.2-cudnn8.2-trt8.0内进行实验，上述错误日志仍旧存在，

```
W0120 02:50:19.464196 209718 gpu_resources.cc:299] WARNING: device: . The installed Paddle is compiled with CUDNN 8.2, but CUDNN version in your machine is 8.1, which may cause serious incompatible bug. Please recompile or reinstall Paddle with compatible CUDNN version.
```

查询容器内cudnn版本

```
>>> paddle.version.cudnn()
'8.2.1'
```

查询主机cudnn版本

```
# nvcc -V
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2020 NVIDIA Corporation
Built on Tue_Sep_15_19:10:02_PDT_2020
Cuda compilation tools, release 11.1, V11.1.74
Build cuda_11.1.TC455_06.29069683_0
```

我的问题是

1. 这条警告信息会不会对paddle的使用产生影响？
2. 如果要重新安装或者重新编译，应该怎么做？
