### ISSUE TITLE
aistudio安装albumentations时，总是停在Building wheel for opencv-python-headless (PEP 517) ... |

### ISSUE THREAD

**Issue by linuxonly801** [PaddlePaddle/Paddle#37353]
请问，aistudio安装albumentations时，总是停在Building wheel for opencv-python-headless (PEP 517) ... |步骤，是为什么呢？安装其他的库都正常。

**Comment by huangxu96** [comment]
您好～这个问题还请咨询aistudio平台的相关负责人哦～

**Comment by XieYunshen** [comment]
升级一下pip应该可以，`pip install --upgrade pip`

**Comment by linuxonly801** [comment]
你好，升级pip后，就可以正常安装albumentations了。
