### ISSUE TITLE
paddle自带的数据增强添加关键点，bbox，segmentation的增强。

### ISSUE THREAD

**Issue by linuxonly801** [PaddlePaddle/Paddle#37354]
目前在学习使用paddle进行关键点检测，发现paddle自带的API只能对图像进行增强，但与图像关联的关键点信息无法同时进行增强。希望可以添加相应的API，对关键点，bbox等的支持。

**Comment by huangxu96** [comment]
您好，您的反馈非常有价值，我们内部会安排评估，未来有计划会尽快回复您～
