### ISSUE TITLE
两个sigmoid后的数字相乘，得到了一个负数

### ISSUE THREAD

**Issue by songyuwen0808** [PaddlePaddle/Paddle#37359]
当前的部分组网如截图：
![image](https://user-images.githubusercontent.com/9607334/142558164-836dcb68-ce59-4d22-9e34-bbeac26d2b67.png)
![image](https://user-images.githubusercontent.com/9607334/142558179-a6d99420-3d35-4bd3-82d4-cc465ff0441c.png)
![image](https://user-images.githubusercontent.com/9607334/142558194-c975048b-15a5-481a-9eca-dc97b744bdb6.png)
在使用第三张图红框中的内容进行计算时，提示出现了负数：
![image](https://user-images.githubusercontent.com/9607334/142558253-c73edbc6-a671-485d-ae71-7eccd0ab0a18.png)

想问下，为什么2个sigmoid后的数相乘后，会出现负数呢

**Comment by huangxu96** [comment]
您好，请问方便提供代码和环境信息吗，我们复现后会尽快回复您～
