### ISSUE TITLE
paddle有early_stopping参数吗？

### ISSUE THREAD

**Issue by zhangyifei1** [PaddlePaddle/Paddle#37358]

**Comment by zhangyifei1** [comment]
a

**Comment by onecatcn** [comment]
您好，paddle高层API中提供了这一功能，详情请见：https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/callbacks/EarlyStopping_cn.html#earlystopping。
如果还有问题，欢迎继续询问。
