### ISSUE TITLE
MaxOut Operator. (TODO, Not Assigned. Welcome people to implement it.)

### ISSUE THREAD

**Issue by luotao1** [PaddlePaddle/Paddle#3737]
Reference:
- [MaxOutLayer.cpp](https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/gserver/layers/MaxOutLayer.cpp)
- [MaxOut api](http://doc.paddlepaddle.org/develop/doc/api/v2/config/layer.html#maxout)

This Op is TODO, welcome people to implement it.

**Comment by zhouxiao-coder** [comment]
I took a look at this layer and its related paper. 
I'm not sure if I misunderstood its formula, but it seems to me like it can be implemented by `reshape->maxPooling`. Something similar to the following numpy code:
```
import numpy as np
n, c, h, w, group = 2, 4, 4, 4, 2
x = np.random.normal(size=(n, c, h, w))
# maxout: reshape the channel dimension to 2 dimensions(group, channel/group), 
# then max pooling on the channel/group dimension
y = np.reshape(x, newshape=(n, group, c/group, h, w)).max(axis=2)
```

**Comment by qingqing01** [comment]
@zhouxiao-coder Good! You are right, `Reshape` + `reduce_max` can do this.  And the [maxout in TensorFlow](https://www.tensorflow.org/versions/master/api_docs/python/tf/contrib/layers/maxout) is more flexible than our implementation.

**Comment by chengduoZH** [comment]
@qingqing01 
This operation is easy to implement if our top-k op supports the axis property.
