### ISSUE TITLE
RTX3070上编译 nvcc fatal   : Unsupported gpu architecture 'compute_86'

### ISSUE THREAD

**Issue by bitterchange** [PaddlePaddle/Paddle#37374]
paddlepaddle 2.0
GPU RTX3070 
CUDA 10.2 cudnn 7.6.5
ubuntu 18.04
gcc 7.5
源码编译paddlepaddle
编译时出现，nvcc fatal   : Unsupported gpu architecture 'compute_86'
网上搜索说是 CUDA版本较低导致， pytorch有解决方案， paddlepaddle 有无较好的方案解决这个问题？

**Comment by huangxu96** [comment]
您好～Paddle里的解决方案同样是降低CUDA算力。具体的方法是：添加环境变量 export CUDA_ARCH_NAME=Ampere 。谢谢～
