### ISSUE TITLE
paddle1.8 batch_norm用在fc后时需设置data_layout='NHWC'，但训练时会报错Error: Tensor holds no memory. Call Tensor::mutable_data first.

### ISSUE THREAD

**Issue by gongchenting** [PaddlePaddle/Paddle#37375]
- 版本、环境信息：
    1）PaddlePaddle版本：1.8
    2）GPU：V100

----------------------
Error Message Summary:
----------------------
Error: Tensor holds no memory. Call Tensor::mutable_data first.
  [Hint: holder_ should not be null.] at (/Paddle/paddle/fluid/framework/tensor.cc:23)
  [operator < batch_norm > error]

**Comment by huangxu96** [comment]
您好，请问方便提供代码和环境信息吗，我们复现问题后会尽快回复您～

**Comment by huangxu96** [comment]
这边建议升级到paddle 2.0，您这里提到的功能在2.0版本是已经支持的。
