### ISSUE TITLE
【论文复现】torch预训练模型转paddle后出现模型不识别的情况

### ISSUE THREAD

**Issue by NSL-Wx** [PaddlePaddle/Paddle#37395]
- 版本、环境信息：
    1）PaddlePaddle版本：2.1.3
    2）CPU：CPU型号：Intel(R) Core(TM) i7-8700 
    3）系统环境：虚拟机 Ubuntu 18.04

    1）模型名称 ：resnet18-5c106cde.pth
    2）模型链接 ：'https://download.pytorch.org/models/resnet18-5c106cde.pth'
- 复现信息：第一次：torch parm fc.weight not exist in paddle modle
                                   torch parm fc.bias not exist in paddle modle
- 复现信息：第二次：can't find pretrained model
- 问题描述：第一次报错：在模型转换时无法对齐  在我尝试删除与训练中的fc层权重后，转换没有继续出错
- 问题描述：第二次报错：在后续模型训练过程的模型加载过程中系统报出找不到预训练模型
- 问题描述： ！另外我在删除fc层的信息时发现，预训练模型的参数文件似乎是不能直接进行读写的，我是通过将删除语句写进循环才成功运行转换的 ！我不知道这种写法有没有问题？
- 操作过程中使用的语句：用于删除的语句：del torch_weight["fc.weight"]
                                                                        del torch_weight["fc.bias"]
                                           用于加载模型的：fluid.dygraph.save_dygraph(paddle_model.state_dict(), './pretrained/resnet18-torch')
                                                                        paddle_weight, _ = fluid.dygraph.load_dygraph('./pretrained/resnet18-torch')
                                                                 及：paddle_model.set_dict(paddle_weight)
                                                                        fluid.dygraph.save_dygraph(paddle_model.state_dict(), './pretrained/resnet18-torch')
在检查问题的过程中，我确保路径信息没有问题，麻烦帮我看看这个问题该如何解决 ？谢谢 ！

**Comment by jiangjiajun** [comment]
Hi, @NSL-Wx 

目前看起来你是想将PyTorch的预训练权重转为Paddle进行加载，您可以使用X2Paddle，或者是如下文档中的接口，直接使用torch.vision中的resnet
https://github.com/PaddlePaddle/X2Paddle/blob/develop/docs/pytorch_project_convertor/API_docs/vision/torchvision.models.md

**Comment by NSL-Wx** [comment]
你好，我听从你的建议使用X2Paddle进行了模型转换，出现了如下问题：
F:/model\x2paddle_code.py:245: DeprecationWarning: invalid escape sequence \m
  params = paddle.load('F:\model\model.pdparams')
运行程序后，我去查看了用来存放模型的路径，该路径下存在如下文件：
![image](https://user-images.githubusercontent.com/88092471/143347337-89e08ced-da76-4bda-9a78-a6bb503223aa.png)
似乎模型转换已经完成了？是否之前出的warning并不影响模型的转换呢？
在inference_model文件夹下存在如下文件：
![image](https://user-images.githubusercontent.com/88092471/143348445-9f5280bd-e321-47b9-a27c-826a7a591b4b.png)
那么在后续的使用过程中，是用.pdiparams还是.pdparams文件呢？

**Comment by jiangjiajun** [comment]
如果是预测使用，用pdiparams，如果是训练使用，用pdparams

**Comment by NSL-Wx** [comment]
> 如果是预测使用，用pdiparams，如果是训练使用，用pdparams

你好，感谢你的回复。在等待的过程中我已经尝试使用两种文件进行训练。但不幸的是，程序运行后仍然没有识别到预训练模型。
结果如下所示：
No pretrained model for Resnet
源代码中的相关程序如下：
![图片](https://user-images.githubusercontent.com/88092471/143367527-0c700aa4-95dc-4380-bb00-e1ce8e1f573d.png)

**Comment by NSL-Wx** [comment]
令我困惑的是，最初在进行模型转换时报出过fc.weight和fc.bias无法对齐。我通过指令删除后，再运行已经可以成功生成.pdparams文件。再进行训练依旧找不到模型。之后，我尝试使用你提供的建议，用X2Paddle进行模型转化，同样也能生成.pdparams的文件，拖入程序进行参数替换，再进行训练，依旧识别不到模型。那么问题究竟出现在哪一个环节？

**Comment by jiangjiajun** [comment]
1. 自己组的Python代码，或者PaddleClas的Python代码能否直接加载PyTorch同模型结构参数
> 不能。因为每个权重都有命名，自己组的python代码或PaddleClas的Python代码，尽管模型结构可能与PyTorch相同，但其中各参数名不同，所以加载不了

2. X2Paddle转后的参数应该怎么用？
> X2Paddle目前支持转换模型后生成一个组网代码+模型参数，可直接用此组网代码+模型参数

**Comment by NSL-Wx** [comment]
> 1. 自己组的Python代码，或者PaddleClas的Python代码能否直接加载PyTorch同模型结构参数
> 
> 
> > 不能。因为每个权重都有命名，自己组的python代码或PaddleClas的Python代码，尽管模型结构可能与PyTorch相同，但其中各参数名不同，所以加载不了
> 
>     2. X2Paddle转后的参数应该怎么用？
> 
> 
> > X2Paddle目前支持转换模型后生成一个组网代码+模型参数，可直接用此组网代码+模型参数

感谢你的回复，但这并没有解决我的问题。我想知道的是为什么我完成了转换，但程序无法识别我转换的模型，显示没有预训练模型呢？

**Comment by jiangjiajun** [comment]
> 1. 自己组的Python代码，或者PaddleClas的Python代码能否直接加载PyTorch同模型结构参数
> 
> > 不能。因为每个权重都有命名，自己组的python代码或PaddleClas的Python代码，尽管模型结构可能与PyTorch相同，但其中各参数名不同，所以加载不了
> 
> 2. X2Paddle转后的参数应该怎么用？
> 
> > X2Paddle目前支持转换模型后生成一个组网代码+模型参数，可直接用此组网代码+模型参数

你这里指的程序是什么呢？ 我理解你说的程序即Python代码，所以你的Python代码是X2Paddle转出来的Python代码，还是你自己用Paddle写的或PaddleClas的代码呢，参考上面的第一点

**Comment by NSL-Wx** [comment]
> > 1. 自己组的Python代码，或者PaddleClas的Python代码能否直接加载PyTorch同模型结构参数
> > 
> > > 不能。因为每个权重都有命名，自己组的python代码或PaddleClas的Python代码，尽管模型结构可能与PyTorch相同，但其中各参数名不同，所以加载不了
> > 
> > 
> > 
> > 2. X2Paddle转后的参数应该怎么用？
> > 
> > > X2Paddle目前支持转换模型后生成一个组网代码+模型参数，可直接用此组网代码+模型参数
> 
> 你这里指的程序是什么呢？ 我理解你说的程序即Python代码，所以你的Python代码是X2Paddle转出来的Python代码，还是你自己用Paddle写的或PaddleClas的代码呢，参考上面的第一点

感谢你的回复，代码是通过开源渠道获得的代码，我是希望通过复现熟悉paddlepaddle这个框架。在代码中原作者通过convert将torch的预训练模型转换为paddle模型，进行权重的转换，再通过paddle进行加载和使用。我就是在加载模型时出现了问题。
以下是原程序中的convert.py
![图片](https://user-images.githubusercontent.com/88092471/143673820-70f2c758-932c-4cfa-9da9-87e47a8d4ba2.png)
以下是原程序中权重转换的部分代码：
![图片](https://user-images.githubusercontent.com/88092471/143673852-9e9f5c82-1cd4-43df-9b70-bb273671f545.png)
其中的两句 del 部分是我为了对齐添加的
以下是网络进行初始化加载最终报错的部分代码：
![图片](https://user-images.githubusercontent.com/88092471/143673917-c5c7d0dd-f9e9-4aa4-9ffd-fa268030ab14.png)

**Comment by jiangjiajun** [comment]
建议在此开源Repo下咨询下原作者
