### ISSUE TITLE
aistudio内存溢出

### ISSUE THREAD

**Issue by besttrying** [PaddlePaddle/Paddle#37393]
为使您的问题得到快速解决，在建立Issues前，请您先通过如下方式搜索是否有相似问题:【搜索issue关键字】【使用labels筛选】【官方文档】

如果您没有查询到相似问题，为快速解决您的提问，建立issue时请提供如下细节信息：
- 标题：简洁、精准概括您的问题，例如“Insufficient Memory xxx" ”
- 版本、环境信息：
    1）PaddlePaddle版本：请提供您的PaddlePaddle版本号，例如1.1或CommitID
    2）CPU：预测若用CPU，请提供CPU型号，MKL/OpenBlas/MKLDNN/等数学库使用情况
    3）GPU：预测若用GPU，请提供GPU型号、CUDA和CUDNN版本号
    4）系统环境：请您描述系统类型、版本，例如Mac OS 10.14，Python版本
 注：您可以通过执行[summary_env.py](https://github.com/PaddlePaddle/Paddle/blob/develop/tools/summary_env.py)获取以上信息。
- 训练信息
    1）单机/多机，单卡/多卡
    2）显存信息
    3）Operator信息
- 复现信息：如为报错，请给出复现环境、复现步骤
- 问题描述：请详细描述您的问题，同步贴出报错信息、日志、可复现的代码片段

Thank you for contributing to PaddlePaddle.
Before submitting the issue, you could search issue in the github in case that there was a similar issue submitted or resolved before.
If there is no solution,please make sure that this is a training issue including the following details:
**System information**
-PaddlePaddle version （eg.1.1）or CommitID
-CPU: including CPUMKL/OpenBlas/MKLDNN version
-GPU: including CUDA/CUDNN version
-OS Platform (eg.Mac OS 10.14)
-Other imformation: Distriuted training/informantion of operator/
Graphics card storage
Note: You can get most of the information by running [summary_env.py](https://github.com/PaddlePaddle/Paddle/blob/develop/tools/summary_env.py). 
**To Reproduce**
Steps to reproduce the behavior
**Describe your current behavior**
**Code to reproduce the issue**
**Other info / logs**
paddle2.1
环境aistudio 单卡
总是出现内存溢出问
![MMJI@UD134 %}9~~$}`EZED](https://user-images.githubusercontent.com/18502224/142717961-6fb29dcd-066e-49aa-b5ed-6ce252730e78.png)
题

**Comment by gongweibao** [comment]
看一下你的reader部分是不是占用内存太高？

**Comment by besttrying** [comment]
reader部分占的很少，每次epoch只读取八张图片，大小也只是48x48，这种情况往往会在运行了几百个epoch后出现。

**Comment by gongweibao** [comment]
不好意思，回复晚了。
我说的意思是reader部分的队列是不是太长了，导致内存占用太多？

**Comment by Water2style** [comment]
> 不好意思，回复晚了。 我说的意思是reader部分的队列是不是太长了，导致内存占用太多？

你好 怎么看reader部分的队列是否太长啊....
我也遇到相关问题，内存线性增加, 训完一个EPOCH 就增加，从0个EPOCH训到20多个的时候（每个epoch训一次，eval一次，存一次模型） ， 在save模型时，说 can not allocate memory

**Comment by gongweibao** [comment]
你提供一下具体的项目地址吧。我们来看一下！

**Comment by Water2style** [comment]
> 你提供一下具体的项目地址吧。我们来看一下！

你好，谢谢. 目前暂时解决了. 
我是调整了一下data_loader的 num_workers ，可能和这个有一定的关系. 内存也稳定了.
