### ISSUE TITLE
python3如不关闭./paddle/dataset/image.py中的cv2线程导入，编译生成exe后会开一堆.exe进程导致卡死

### ISSUE THREAD

**Issue by JixuH** [PaddlePaddle/Paddle#37408]
PaddlePaddle版本：2.1.3

**Comment by sandyhouse** [comment]
您好，请问是Window编译吗？能发一下具体的编译选项吗？

**Comment by JixuH** [comment]
我是使用pip直接下载安装的paddlepaddle==2.1.3版本，没有自己编译

**Comment by sandyhouse** [comment]
> 编译生成exe后会开一堆.exe进程导致卡死

没太懂这个地方的编译是什么意思？

**Comment by shoou** [comment]
> > 编译生成exe后会开一堆.exe进程导致卡死
> 
> 没太懂这个地方的编译是什么意思？

这里的编译应该是用pyinstaller打包的意思
