### ISSUE TITLE
ssh -p 2202 root@localhost 进不去

### ISSUE THREAD

**Issue by luotao1** [PaddlePaddle/Paddle#3740]
按照 http://doc.paddlepaddle.org/develop/doc_cn/getstarted/build_and_install/docker_install_cn.html
```
或者，可以以后台进程方式运行容器：
docker run -d -p 2202:22 -p 8888:8888 paddledev/paddle:0.10.0-dev
然后用密码 root SSH进入容器：
ssh -p 2202 root@localhost
```
ssh进不去，文档有错。

**Comment by Yancey1989** [comment]
Hi @luotao1 ,我看下develop 分支的rst文件是正确的，看起来是网站文档没有使用最新的rst文件，请问知道如何更新吗？

**Comment by luotao1** [comment]
已经提了 https://github.com/PaddlePaddle/Paddle/issues/3745 ，这个Issue先关闭。
