### ISSUE TITLE
cmake paddle : No CMAKE_Go_COMPILER could be found.

### ISSUE THREAD

**Issue by ssdyue** [PaddlePaddle/Paddle#3741]
ssd@yue:~/paddle/build$ cmake ..
-- Found Paddle host system: ubuntu
-- Found Paddle host system's CPU: 8 cores
-- The CXX compiler identification is GNU 5.4.1
-- The C compiler identification is GNU 5.4.1
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
CMake Error at CMakeLists.txt:22 (project):
  No CMAKE_Go_COMPILER could be found.

  Tell CMake where to find the compiler by setting either the environment
  variable "GO_COMPILER" or the CMake cache entry CMAKE_Go_COMPILER to the
  full path to the compiler, or to the compiler name if it is in the PATH.

-- Configuring incomplete, errors occurred!
See also "/home/ssd/paddle/build/CMakeFiles/CMakeOutput.log".

i can't find the reason!

**Comment by typhoonzero** [comment]
You need to install `Go` to build paddle, you can install it from here: https://golang.org/doc/install#install

I recommend building paddlepaddle using `docker`: http://doc.paddlepaddle.org/doc/getstarted/build_and_install/docker_install_en.html

**Comment by ssdyue** [comment]
@typhoonzero thank you！i find the problem. i have installed Go ,but don't set the path. 
i still try to finish the build, however, another problem is coming：

-- Paddle version is 0.10.0
-- Compile with MKLDNNLayers and MKLDNNActivations
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
Boost_INCLUDE_DIR (ADVANCED)
   used as include directory in directory /home/ssd/paddle
   used as include directory in directory /home/ssd/paddle
   used as include directory in directory /home/ssd/paddle
   used as include directory in directory /home/ssd/paddle
   used as include directory in directory /home/ssd/paddle
   used as include directory in directory /home/ssd/paddle
   used as include directory in directory /home/ssd/paddle
   used as include directory in directory /home/ssd/paddle
   used as include directory in directory /home/ssd/paddle

**Comment by typhoonzero** [comment]
Seems like you need to install boost and rerun `cmake` again. And you can add options `-DWITH_MKLML=OFF -DWITH_MKLDNN=OFF` to turn off mkl since it's still under heavy development.

**Comment by pkuyym** [comment]
Close due to inactivity, please feel free to reopen if necessary.
