### ISSUE TITLE
Operator unit test not convinient to build and test

### ISSUE THREAD

**Issue by typhoonzero** [PaddlePaddle/Paddle#3742]
We can run `make copy_paddle_pybind` to build operators and then run `ctest` to run one or more unit tests, `ctest` attempt to find `core.so` under `PYTHONPATH=/paddle/build/python/build/lib-python`, but after running `make copy_paddle_pybind` the `core.so` still seems not updated.

**Comment by gongweibao** [comment]
There's no problem now.
