### ISSUE TITLE
关于capi的paddle_gradient_machine_create_for_inference_with_parameters在加载异常模型时

### ISSUE THREAD

**Issue by bushidonggua** [PaddlePaddle/Paddle#3743]
报个bug：capi的paddle_gradient_machine_create_for_inference_with_parameters 这个函数在模型的格式有问题时不是返回异常而是卡住了

**Comment by shibing624** [comment]
我这边加载时出core了，使用方法参考使用文档及merge_v2_model.py ，出错信息：

F0421 00:21:09.081142 15079 ClassRegistrar.h:65] Check failed: mapGet(type, creatorMap_, &creator) Unknown class type: data
*** Check failure stack trace: ***
    @           0xe9927c  google::LogMessage::Fail()
    @           0xe991d4  google::LogMessage::SendToLog()
    @           0xe98c69  google::LogMessage::Flush()
    @           0xe9ba2a  google::LogMessageFatal::~LogMessageFatal()
    @          0x18102f4  paddle::Layer::create()
    @          0x16baca0  _ZZN6paddle13NeuralNetwork4initERKNS_11ModelConfigESt8functionIFviPNS_9ParameterEEERKSt6vectorINS_19enumeration_wrapper13ParameterTypeESaISB_EEbENKUlRKNS_11LayerConfigEE_clESI_
    @          0x16bc123  paddle::NeuralNetwork::init()
    @          0x16b839e  paddle::GradientMachine::create()
    @          0x16ab819  paddle_gradient_machine_create_for_inference_with_parameters
    @          0x109f525  paddle_classification::PaddleClassification::load_from_file()
    @           0x556599  draka::TestLstmSuite_test_model_load_init_Test::TestBody()
    @           0x741fc3  testing::internal::HandleExceptionsInMethodIfSupported<>()
    @           0x73995d  testing::Test::Run()
    @           0x7399f4  testing::TestInfo::Run()
    @           0x739af5  testing::TestCase::Run()
    @           0x73c4e7  testing::internal::UnitTestImpl::RunAllTests()
    @           0x73c794  testing::UnitTest::Run()
    @           0x55642f  main
    @     0x7fa77df53bd5  __libc_start_main
    @           0x5562e5  (unknown)

**Comment by shibing624** [comment]
![image](https://user-images.githubusercontent.com/10249622/46992060-04e21080-d13b-11e8-8ee1-57d1bce12c2e.png)
python 调用C++生成的.so时，如上图出错，请问怎么解决？
