### ISSUE TITLE
paddle提供的安装包有误

### ISSUE THREAD

**Issue by Darki-luo** [PaddlePaddle/Paddle#37443]
ubuntu18.04环境，nvidia 驱动 460 ,conda环境下cudatoolkit=10.2，cudnn=7.6 
硬件不支持avx，按照官网介绍安装了gpu版本cuda10.2 noavx版本，但是运行时 还是cuda10.1的
W1122 20:38:10.577867 11608 device_context.cc:447] Please NOTE: device: 0, GPU Compute Capability: 6.1, Driver API Version: 11.2, Runtime API Version: 10.1

python -m pip download paddlepaddle-gpu==2.2.0 -f https://www.paddlepaddle.org.cn/whl/linux/mkl/noavx/stable.html --no-index --no-deps

**Comment by sandyhouse** [comment]
> Runtime API Version: 10.1
这个信息指的是你机器上cuda版本为10.1。paddle自身不会安装cuda，只是获取机器上的信息予以输出。
可以通过nvcc --version确定机器上的cuda版本。（如果使用docker镜像的话，需要在镜像中运行上述命令）。

**Comment by Darki-luo** [comment]
> > Runtime API Version: 10.1
> > 这个信息指的是你机器上cuda版本为10.1。paddle自身不会安装cuda，只是获取机器上的信息予以输出。
> > 可以通过nvcc --version确定机器上的cuda版本。（如果使用docker镜像的话，需要在镜像中运行上述命令）。

我安装的驱动是460，cuda是11.2，conda环境里也配的是10.2 cudnn是7.6.5，就没有10.1，你的包传错了吧，下载noavx的cuda10.2和cuda10.1都显示的是10.1的。

nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2019 NVIDIA Corporation
Built on Wed_Oct_23_19:24:38_PDT_2019
Cuda compilation tools, release 10.2, V10.2.89

**Comment by sandyhouse** [comment]
python -m pip install paddlepaddle-gpu==2.2.0 -i https://mirror.baidu.com/pypi/simple
用上面这条安装命令试一下吧。

**Comment by Darki-luo** [comment]
> python -m pip install paddlepaddle-gpu==2.2.0 -i https://mirror.baidu.com/pypi/simple 用上面这条安装命令试一下吧。

这条指令安装运行不了，机器的cpu缺少AVX算子，直接安装会报错，就想让你们确认一下，官网提供的2.2 noavx的cuda10.2的whl文件是传错包了，还是没有基于cuda10.2，只有基于cuda10.1了呢，官网文档和你们提供的下载地址应该是有一个出错了。

**Comment by sandyhouse** [comment]
> https://www.paddlepaddle.org.cn/whl/linux/mkl/noavx/stable.html
这个网页里面没有10.2的包。

**Comment by Darki-luo** [comment]
> > https://www.paddlepaddle.org.cn/whl/linux/mkl/noavx/stable.html
> > 这个网页里面没有10.2的包。

那你们官方文档安装教程需要更新一下~：[https://www.paddlepaddle.org.cn/install/quick?docurl=/documentation/docs/zh/install/pip/linux-pip.html](https://www.paddlepaddle.org.cn/install/quick?docurl=/documentation/docs/zh/install/pip/linux-pip.html)

“_cpu、mkl版本noavx机器安装：

python -m pip download paddlepaddle==2.2.0 -f https://www.paddlepaddle.org.cn/whl/linux/mkl/noavx/stable.html --no-index --no-deps
cpu、openblas版本noavx机器安装：

python -m pip download paddlepaddle==2.2.0 -f https://www.paddlepaddle.org.cn/whl/linux/openblas/noavx/stable.html --no-index --no-deps
gpu版本cuda10.1 noavx机器安装：

python -m pip download paddlepaddle-gpu==2.2.0.post101 -f https://www.paddlepaddle.org.cn/whl/linux/mkl/noavx/stable.html --no-index --no-deps
gpu版本cuda10.2 noavx机器安装：

python -m pip download paddlepaddle-gpu==2.2.0 -f https://www.paddlepaddle.org.cn/whl/linux/mkl/noavx/stable.html --no-index --no-deps
判断你的机器是否支持avx，可以输入以下命令，如果输出中包含avx，则表示机器支持avx

cat /proc/cpuinfo | grep -i avx_”

**Comment by pangyoki** [comment]
> > > https://www.paddlepaddle.org.cn/whl/linux/mkl/noavx/stable.html
> > > 这个网页里面没有10.2的包。
> 
> 那你们官方文档安装教程需要更新一下~：https://www.paddlepaddle.org.cn/install/quick?docurl=/documentation/docs/zh/install/pip/linux-pip.html
> 
> “_cpu、mkl版本noavx机器安装：
> 
> python -m pip download paddlepaddle==2.2.0 -f https://www.paddlepaddle.org.cn/whl/linux/mkl/noavx/stable.html --no-index --no-deps cpu、openblas版本noavx机器安装：
> 
> python -m pip download paddlepaddle==2.2.0 -f https://www.paddlepaddle.org.cn/whl/linux/openblas/noavx/stable.html --no-index --no-deps gpu版本cuda10.1 noavx机器安装：
> 
> python -m pip download paddlepaddle-gpu==2.2.0.post101 -f https://www.paddlepaddle.org.cn/whl/linux/mkl/noavx/stable.html --no-index --no-deps gpu版本cuda10.2 noavx机器安装：
> 
> python -m pip download paddlepaddle-gpu==2.2.0 -f https://www.paddlepaddle.org.cn/whl/linux/mkl/noavx/stable.html --no-index --no-deps 判断你的机器是否支持avx，可以输入以下命令，如果输出中包含avx，则表示机器支持avx
> 
> cat /proc/cpuinfo | grep -i avx_”

你好，请问你的python版本是什么？cuda10.2的noavx包只支持python3.8，可以下载这个包：https://paddle-wheel.bj.bcebos.com/2.2.0/linux/linux-gpu-cuda10.2-cudnn7-mkl-gcc8.2-noavx/paddlepaddle_gpu-2.2.0-cp38-cp38-linux_x86_64.whl 。
另外，你复制的这段安装命令是pip安装，不是conda安装的。

**Comment by pangyoki** [comment]
> > https://www.paddlepaddle.org.cn/whl/linux/mkl/noavx/stable.html
> > 这个网页里面没有10.2的包。

你好，这个网页里https://paddle-wheel.bj.bcebos.com/2.2.0/linux/linux-gpu-cuda10.2-cudnn7-mkl-gcc8.2-noavx/paddlepaddle_gpu-2.2.0-cp38-cp38-linux_x86_64.whl 这个包是cuda10.2的，没有`.post`后缀

**Comment by Darki-luo** [comment]
> > > > https://www.paddlepaddle.org.cn/whl/linux/mkl/noavx/stable.html
> > > > 这个网页里面没有10.2的包。
> > 
> > 
> > 那你们官方文档安装教程需要更新一下~：https://www.paddlepaddle.org.cn/install/quick?docurl=/documentation/docs/zh/install/pip/linux-pip.html
> > “_cpu、mkl版本noavx机器安装：
> > python -m pip download paddlepaddle==2.2.0 -f https://www.paddlepaddle.org.cn/whl/linux/mkl/noavx/stable.html --no-index --no-deps cpu、openblas版本noavx机器安装：
> > python -m pip download paddlepaddle==2.2.0 -f https://www.paddlepaddle.org.cn/whl/linux/openblas/noavx/stable.html --no-index --no-deps gpu版本cuda10.1 noavx机器安装：
> > python -m pip download paddlepaddle-gpu==2.2.0.post101 -f https://www.paddlepaddle.org.cn/whl/linux/mkl/noavx/stable.html --no-index --no-deps gpu版本cuda10.2 noavx机器安装：
> > python -m pip download paddlepaddle-gpu==2.2.0 -f https://www.paddlepaddle.org.cn/whl/linux/mkl/noavx/stable.html --no-index --no-deps 判断你的机器是否支持avx，可以输入以下命令，如果输出中包含avx，则表示机器支持avx
> > cat /proc/cpuinfo | grep -i avx_”
> 
> 你好，请问你的python版本是什么？cuda10.2的noavx包只支持python3.8，可以下载这个包：https://paddle-wheel.bj.bcebos.com/2.2.0/linux/linux-gpu-cuda10.2-cudnn7-mkl-gcc8.2-noavx/paddlepaddle_gpu-2.2.0-cp38-cp38-linux_x86_64.whl 。 另外，你复制的这段安装命令是pip安装，不是conda安装的。


因为cpu不支持AVX，所以没法直接用conda和pypi源的安装，显卡驱动和cuda信息，python信息都显示了，用conda配的环境，并且也安装了conda的cudatoolkit和cudnn，paddle采用noavx的whl安装包，经过测试正常运行，但是我发现，搭配cuda10.2的whl包运行的cuda api是10.1，用官网文档和你提供的whl包都是这样。
****************************************
Paddle version: 2.2.0
Paddle With CUDA: True
OS: Ubuntu 18.04
Python version: 3.8.5
CUDA version: 10.2.89
cuDNN version: None.None.None
Nvidia driver version: 460.91.03
****************************************
conda list 环境：
cudatoolkit               10.2.89              hfd86e86_1   
cudnn                     7.6.5                cuda10.2_0    
decorator                 5.1.0                    pypi_0    pypi
distro                    1.5.0              pyhd3eb1b0_1    
idna                      3.2                      pypi_0    pypi
ld_impl_linux-64          2.35.1               h7274673_9   
libffi                    3.3                  he6710b0_2    
libgcc-ng                 9.3.0               h5101ec6_17    
libgomp                   9.3.0               h5101ec6_17    
libstdcxx-ng              9.3.0               hd4cf53a_17  
ncurses                   6.3                  h7f8727e_2   
numpy                     1.21.2                   pypi_0    pypi
openssl                   1.1.1l               h7f8727e_0    
paddlepaddle-gpu          2.2.0                    pypi_0    pypi
pillow                    8.3.2                    pypi_0   
________________________________________________________

运行过程：
Python 3.8.5 (default, Sep  4 2020, 07:30:14) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import paddle
>>> paddle.utils.run_check()
Running verify PaddlePaddle program ... 
W1123 20:15:52.573328 24918 device_context.cc:447] Please NOTE: device: 0, GPU Compute Capability: 6.1, Driver API Version: 11.2, Runtime API Version: 10.1
W1123 20:15:52.578675 24918 device_context.cc:465] device: 0, cuDNN Version: 8.3.
PaddlePaddle works well on 1 GPU.
W1123 20:15:55.033598 24918 parallel_executor.cc:611] Cannot enable P2P access from 0 to 1
W1123 20:15:55.033649 24918 parallel_executor.cc:611] Cannot enable P2P access from 1 to 0
W1123 20:15:58.117830 24918 fuse_all_reduce_op_pass.cc:76] Find all_reduce operators: 2. To make the speed faster, some all_reduce ops are fused during training, after fusion, the number of all_reduce ops is 2.
PaddlePaddle works well on 2 GPUs.
PaddlePaddle is installed successfully! Let's start deep learning with PaddlePaddle now.
>>> 

Runtime API Version: 10.1，运行时检测不到conda环境中的cudatoolkit，

**Comment by pangyoki** [comment]
> > > > > https://www.paddlepaddle.org.cn/whl/linux/mkl/noavx/stable.html
> > > > > 这个网页里面没有10.2的包。
> > > 
> > > 
> > > 那你们官方文档安装教程需要更新一下~：https://www.paddlepaddle.org.cn/install/quick?docurl=/documentation/docs/zh/install/pip/linux-pip.html
> > > “_cpu、mkl版本noavx机器安装：
> > > python -m pip download paddlepaddle==2.2.0 -f https://www.paddlepaddle.org.cn/whl/linux/mkl/noavx/stable.html --no-index --no-deps cpu、openblas版本noavx机器安装：
> > > python -m pip download paddlepaddle==2.2.0 -f https://www.paddlepaddle.org.cn/whl/linux/openblas/noavx/stable.html --no-index --no-deps gpu版本cuda10.1 noavx机器安装：
> > > python -m pip download paddlepaddle-gpu==2.2.0.post101 -f https://www.paddlepaddle.org.cn/whl/linux/mkl/noavx/stable.html --no-index --no-deps gpu版本cuda10.2 noavx机器安装：
> > > python -m pip download paddlepaddle-gpu==2.2.0 -f https://www.paddlepaddle.org.cn/whl/linux/mkl/noavx/stable.html --no-index --no-deps 判断你的机器是否支持avx，可以输入以下命令，如果输出中包含avx，则表示机器支持avx
> > > cat /proc/cpuinfo | grep -i avx_”
> > 
> > 
> > 你好，请问你的python版本是什么？cuda10.2的noavx包只支持python3.8，可以下载这个包：https://paddle-wheel.bj.bcebos.com/2.2.0/linux/linux-gpu-cuda10.2-cudnn7-mkl-gcc8.2-noavx/paddlepaddle_gpu-2.2.0-cp38-cp38-linux_x86_64.whl 。 另外，你复制的这段安装命令是pip安装，不是conda安装的。
> 
> 因为cpu不支持AVX，所以没法直接用conda和pypi源的安装，显卡驱动和cuda信息，python信息都显示了，用conda配的环境，并且也安装了conda的cudatoolkit和cudnn，paddle采用noavx的whl安装包，经过测试正常运行，但是我发现，搭配cuda10.2的whl包运行的cuda api是10.1，用官网文档和你提供的whl包都是这样。
> 
> Paddle version: 2.2.0 Paddle With CUDA: True OS: Ubuntu 18.04 Python version: 3.8.5 CUDA version: 10.2.89 cuDNN version: None.None.None Nvidia driver version: 460.91.03
> 
> conda list 环境： cudatoolkit 10.2.89 hfd86e86_1 cudnn 7.6.5 cuda10.2_0 decorator 5.1.0 pypi_0 pypi distro 1.5.0 pyhd3eb1b0_1 idna 3.2 pypi_0 pypi ld_impl_linux-64 2.35.1 h7274673_9 libffi 3.3 he6710b0_2 libgcc-ng 9.3.0 h5101ec6_17 libgomp 9.3.0 h5101ec6_17 libstdcxx-ng 9.3.0 hd4cf53a_17 ncurses 6.3 h7f8727e_2 numpy 1.21.2 pypi_0 pypi openssl 1.1.1l h7f8727e_0 paddlepaddle-gpu 2.2.0 pypi_0 pypi pillow 8.3.2 pypi_0
> 
> 运行过程： Python 3.8.5 (default, Sep 4 2020, 07:30:14) [GCC 7.3.0] :: Anaconda, Inc. on linux Type "help", "copyright", "credits" or "license" for more information.
> 
> > > > import paddle
> > > > paddle.utils.run_check()
> > > > Running verify PaddlePaddle program ...
> > > > W1123 20:15:52.573328 24918 device_context.cc:447] Please NOTE: device: 0, GPU Compute Capability: 6.1, Driver API Version: 11.2, Runtime API Version: 10.1
> > > > W1123 20:15:52.578675 24918 device_context.cc:465] device: 0, cuDNN Version: 8.3.
> > > > PaddlePaddle works well on 1 GPU.
> > > > W1123 20:15:55.033598 24918 parallel_executor.cc:611] Cannot enable P2P access from 0 to 1
> > > > W1123 20:15:55.033649 24918 parallel_executor.cc:611] Cannot enable P2P access from 1 to 0
> > > > W1123 20:15:58.117830 24918 fuse_all_reduce_op_pass.cc:76] Find all_reduce operators: 2. To make the speed faster, some all_reduce ops are fused during training, after fusion, the number of all_reduce ops is 2.
> > > > PaddlePaddle works well on 2 GPUs.
> > > > PaddlePaddle is installed successfully! Let's start deep learning with PaddlePaddle now.
> 
> Runtime API Version: 10.1，运行时检测不到conda环境中的cudatoolkit，

你好，我们验证了下，不好意思，原因的确是把cuda10.1的包上传到了cuda10.2的目录下，导致你安装的是cuda10.1的包。
这个问题现在已经修复了，可以正常安装cuda10.2的包了。感谢反馈！

**Comment by Darki-luo** [comment]
> > > > > > https://www.paddlepaddle.org.cn/whl/linux/mkl/noavx/stable.html
> > > > > > 这个网页里面没有10.2的包。
> > > > 
> > > > 
> > > > 那你们官方文档安装教程需要更新一下~：https://www.paddlepaddle.org.cn/install/quick?docurl=/documentation/docs/zh/install/pip/linux-pip.html
> > > > “_cpu、mkl版本noavx机器安装：
> > > > python -m pip download paddlepaddle==2.2.0 -f https://www.paddlepaddle.org.cn/whl/linux/mkl/noavx/stable.html --no-index --no-deps cpu、openblas版本noavx机器安装：
> > > > python -m pip download paddlepaddle==2.2.0 -f https://www.paddlepaddle.org.cn/whl/linux/openblas/noavx/stable.html --no-index --no-deps gpu版本cuda10.1 noavx机器安装：
> > > > python -m pip download paddlepaddle-gpu==2.2.0.post101 -f https://www.paddlepaddle.org.cn/whl/linux/mkl/noavx/stable.html --no-index --no-deps gpu版本cuda10.2 noavx机器安装：
> > > > python -m pip download paddlepaddle-gpu==2.2.0 -f https://www.paddlepaddle.org.cn/whl/linux/mkl/noavx/stable.html --no-index --no-deps 判断你的机器是否支持avx，可以输入以下命令，如果输出中包含avx，则表示机器支持avx
> > > > cat /proc/cpuinfo | grep -i avx_”
> > > 
> > > 
> > > 你好，请问你的python版本是什么？cuda10.2的noavx包只支持python3.8，可以下载这个包：https://paddle-wheel.bj.bcebos.com/2.2.0/linux/linux-gpu-cuda10.2-cudnn7-mkl-gcc8.2-noavx/paddlepaddle_gpu-2.2.0-cp38-cp38-linux_x86_64.whl 。 另外，你复制的这段安装命令是pip安装，不是conda安装的。
> > 
> > 
> > 因为cpu不支持AVX，所以没法直接用conda和pypi源的安装，显卡驱动和cuda信息，python信息都显示了，用conda配的环境，并且也安装了conda的cudatoolkit和cudnn，paddle采用noavx的whl安装包，经过测试正常运行，但是我发现，搭配cuda10.2的whl包运行的cuda api是10.1，用官网文档和你提供的whl包都是这样。
> > Paddle version: 2.2.0 Paddle With CUDA: True OS: Ubuntu 18.04 Python version: 3.8.5 CUDA version: 10.2.89 cuDNN version: None.None.None Nvidia driver version: 460.91.03
> > conda list 环境： cudatoolkit 10.2.89 hfd86e86_1 cudnn 7.6.5 cuda10.2_0 decorator 5.1.0 pypi_0 pypi distro 1.5.0 pyhd3eb1b0_1 idna 3.2 pypi_0 pypi ld_impl_linux-64 2.35.1 h7274673_9 libffi 3.3 he6710b0_2 libgcc-ng 9.3.0 h5101ec6_17 libgomp 9.3.0 h5101ec6_17 libstdcxx-ng 9.3.0 hd4cf53a_17 ncurses 6.3 h7f8727e_2 numpy 1.21.2 pypi_0 pypi openssl 1.1.1l h7f8727e_0 paddlepaddle-gpu 2.2.0 pypi_0 pypi pillow 8.3.2 pypi_0
> > 运行过程： Python 3.8.5 (default, Sep 4 2020, 07:30:14) [GCC 7.3.0] :: Anaconda, Inc. on linux Type "help", "copyright", "credits" or "license" for more information.
> > > > > import paddle
> > > > > paddle.utils.run_check()
> > > > > Running verify PaddlePaddle program ...
> > > > > W1123 20:15:52.573328 24918 device_context.cc:447] Please NOTE: device: 0, GPU Compute Capability: 6.1, Driver API Version: 11.2, Runtime API Version: 10.1
> > > > > W1123 20:15:52.578675 24918 device_context.cc:465] device: 0, cuDNN Version: 8.3.
> > > > > PaddlePaddle works well on 1 GPU.
> > > > > W1123 20:15:55.033598 24918 parallel_executor.cc:611] Cannot enable P2P access from 0 to 1
> > > > > W1123 20:15:55.033649 24918 parallel_executor.cc:611] Cannot enable P2P access from 1 to 0
> > > > > W1123 20:15:58.117830 24918 fuse_all_reduce_op_pass.cc:76] Find all_reduce operators: 2. To make the speed faster, some all_reduce ops are fused during training, after fusion, the number of all_reduce ops is 2.
> > > > > PaddlePaddle works well on 2 GPUs.
> > > > > PaddlePaddle is installed successfully! Let's start deep learning with PaddlePaddle now.
> > 
> > 
> > Runtime API Version: 10.1，运行时检测不到conda环境中的cudatoolkit，
> 
> 你好，我们验证了下，不好意思，原因的确是把cuda10.1的包上传到了cuda10.2的目录下，导致你安装的是cuda10.1的包。 这个问题现在已经修复了，可以正常安装cuda10.2的包了。感谢反馈！

现在正常了。有一个问题，使用conda可以正常安装使用paddlepaddle-gpu 2.0.2 的版本，对avx的算子检测是warning,但是2.1.x版本之后就是error了，需要单独使用pip安装noavx的版本，这个能优化一下吗
