### ISSUE TITLE
服务器端安装预编译c++cpu预测库 编译错误

### ISSUE THREAD

**Issue by snoopy1316** [PaddlePaddle/Paddle#37448]
PaddlePaddle版本：2.0
下载cpu预测库
cmake .. -G "Visual Studio 16 2019" -A x64 -T host=x64 -DCMAKE_BUILD_TYPE=Release -DWITH_MKL=ON -DWITH_GPU=OFF -DON_INFER=ON -DWITH_PYTHON=OFF 完成，
[再打开paddle.sln文件进行生成时，已选择release  X64出现错误：

![image](https://user-images.githubusercontent.com/94336500/142960916-70885d9f-3e08-40b6-a198-fbcf3cbf67cf.png)

**Comment by snoopy1316** [comment]
https://www.paddlepaddle.org.cn/documentation/docs/zh/2.0/guides/05_inference_deployment/inference/windows_cpp_inference.html

**Comment by fengxiaoshuai** [comment]
https://paddleinference.paddlepaddle.org.cn/master/user_guides/download_lib.html#windows
试试这个链接中的下载地址，不需要编译，可以直接使用
