### ISSUE TITLE
复选赛报名

### ISSUE THREAD

**Issue by leezhao415** [PaddlePaddle/Paddle#37452]
【队名】：东方幻翎

【序号】：3

【论文】：MnasNet: Platform-Aware Neural Architecture Search for Mobile

【状态】：报名

【repo链接】：https://github.com/leezhao415/Paddle_MnasNet

**Comment by TCChenlong** [comment]
开发者你好，报名是在这个ISSUE https://github.com/PaddlePaddle/Paddle/issues/37401 下回复哈~
