### ISSUE TITLE
http://doc.paddlepaddle.org/develop/ don't updated now

### ISSUE THREAD

**Issue by luotao1** [PaddlePaddle/Paddle#3745]
#3715 #3676 and etc, all update the document, but http://doc.paddlepaddle.org/develop/doc  don't show the latest update now.

**Comment by Superjom** [comment]
which repertory you updated?

**Comment by putcn** [comment]
looks like teamcity build stuck at step trying to download http://paddlepaddle.bj.bcebos.com/demo/srl_dict_and_embedding/emb
I'm restarting the build job to see if it goes through.

**Comment by putcn** [comment]
sorry, previous comment is irrelevant, thought it was paddle book build...

**Comment by putcn** [comment]
checked travis doc build, looks all good and the build successfully pushed content to gh-pages branch, not sure why it's not picked up by website. will do further inspection on this.

**Comment by luotao1** [comment]
Thx @Superjom help to update the doc repo.
