### ISSUE TITLE
win10 c++编译预测demo

### ISSUE THREAD

**Issue by snoopy1316** [PaddlePaddle/Paddle#37475]
预测库是下载gpu预测库（cuda10.1,cudnn7.6)
使用cmd编译：cmake .. -G "Visual Studio 16 2019" -A x64 -T host=x64 -DWITH_GPU=ON -DWITH_MKL=ON -DWITH_STATIC_LIB=ON ^
-DCMAKE_BUILD_TYPE=Release -DDEMO_NAME=simple_on_word2vec -DPADDLE_LIB=C:\Users\admin\Desktop\paddle_inference -DMSVC_STATIC_CRT=ON -DCUDA_LIB=C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.1\lib\x64
在编译demo部分选择使用脚本编译运行，官方使用的时vs2017，我使用的vs2019出现这样的问题：
![image](https://user-images.githubusercontent.com/94336500/142997472-c191d713-84c8-40c2-ac1f-3eddba15c5a3.png)

**Comment by snoopy1316** [comment]
https://www.paddlepaddle.org.cn/documentation/docs/zh/2.0/guides/05_inference_deployment/inference/windows_cpp_inference.html

**Comment by fengxiaoshuai** [comment]
按着提示使用对应版本的编译器
