### ISSUE TITLE
我的电脑不支持AVX指令集，能用装显卡使用GPU吗？

### ISSUE THREAD

**Issue by yeyupiaoling** [PaddlePaddle/Paddle#37480]
- PaddlePaddle 2.2.0
 - Windows 10

我的电脑不支持AVX指令集，想买个显卡装上，但不知道能不能使用GPU吗？

**Comment by ceci3** [comment]
可以用，paddle也支持cuda10.1、cuda10.2 GPU版本的noavx包

**Comment by yeyupiaoling** [comment]
@ceci3 能直接使用conda安装吗？

**Comment by ceci3** [comment]
可以的
