### ISSUE TITLE
infer debug  after installing

### ISSUE THREAD

**Issue by cqray1990** [PaddlePaddle/Paddle#37491]
cuda 10.2,cudnn 8.0.4,paddle:2.2.

安装完后跑推理代码出错，老是出错，难道paddle不能一次安装成功推理？环境依赖有那么苛刻？搞的XXX

--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
No stack trace in paddle, may be caused by external reasons.

----------------------
Error Message Summary:
----------------------
FatalError: `Segmentation fault` is detected by the operating system.
  [TimeInfo: *** Aborted at 1637680470 (unix time) try "date -d @1637680470" if you are using GNU date ***]
  [SignalInfo: *** SIGSEGV (@0x0) received by PID 4303 (TID 0x7f9e26ade740) from PID 0 ***]

段错误 (核心已转储)

**Comment by cqray1990** [comment]
@LielinJiang @jzhang533 @wanglun @lileding  self.predictor.run() 运行直接挂掉，

C++ Traceback (most recent call last):

No stack trace in paddle, may be caused by external reasons.
Error Message Summary:

FatalError: Segmentation fault is detected by the operating system.
[TimeInfo: *** Aborted at 1637680470 (unix time) try "date -d @1637680470" if you are using GNU date ***]
[SignalInfo: *** SIGSEGV (@0x0) received by PID 4303 (TID 0x7f9e26ade740) from PID 0 ***]

**Comment by LielinJiang** [comment]
麻烦贴一下具体的代码 self.predictor.run()，看不出是啥

**Comment by cqray1990** [comment]
cuda 10.2,和cudnn 8.0.4是不是两个版本不匹配？官网的安装解释：CUDA 工具包10.1/10.2配合cuDNN 7 (cuDNN版本>=7.6.5, 如需多卡支持，需配合NCCL2.7及更高)，不能超过8吧，我换成7.6.5没有问题
@LielinJiang

**Comment by baoachun** [comment]
可以先 export GLOG_v=3 并且 删掉 py脚本中的config.disable_glog_info()，然后运行查看打屏日志，会有更详细报错，如果没有请提供下模型和脚本。或者可以加下QQ群：959308808
