### ISSUE TITLE
单阶段训练中，双塔的 slot 在共享 embedding时，如何只让其中一个塔更新 embedding，另一个塔不更新 embedding？

### ISSUE THREAD

**Issue by Master-Luman** [PaddlePaddle/Paddle#37495]
如题:

比方模型由双塔组成，其中A塔的slot集合为slots_1，B塔的slot集合为slots_2，slots_2是slots_1的子集，两个塔的slot共享 embedding，那么写的语法就如下：
A塔：
        embs = []
        for data in slots_1:
            emb = fluid.layers.embedding(input=data, size=9, is_sparse = True, 
                    is_distributed=True, param_attr=fluid.ParamAttr(name='embedding'))
            bow = fluid.layers.sequence_pool(input=emb, pool_type='sum')
            embs.append(bow)
        return embs
B塔：
        embs = []
        for data in slots_2:
            emb = fluid.layers.embedding(input=data, size=9, is_sparse = True, 
                    is_distributed=True, param_attr=fluid.ParamAttr(name='embedding'))
            bow = fluid.layers.sequence_pool(input=emb, pool_type='sum')
            embs.append(bow)
        return embs

这样slots_1和slots_2就应该共享同一个embedding空间了，那该如何实现不让B塔更新 其slots_2的 embedding呢？

**Comment by LielinJiang** [comment]
对于slot2中的bow，设置bow.stop_gradient=True，试试

**Comment by Master-Luman** [comment]
> 对于slot2中的bow，设置bow.stop_gradient=True，试试

嗯嗯，是准备这么尝试的，但就是不确定，这样会不会导致另一个塔的 embedding 也不更新了？

**Comment by LielinJiang** [comment]
这个是不会的，这样的设置只是slot2中的bow之前相关的变量不再有梯度

**Comment by Master-Luman** [comment]
> 这个是不会的，这样的设置只是slot2中的bow之前相关的变量不再有梯度

好的，多谢！
