### ISSUE TITLE
关于模型的热加载

### ISSUE THREAD

**Issue by TimZhang001** [PaddlePaddle/Paddle#37494]
我这边期望能够快速的加载和释放模型，但是Paddle里面没有接口来进行模型的释放，除非对这个线程直接进行kill操作。不知道后续是否可以开放这样的模型释放接口，便于用户进行快速的加载和释放，而不需要对程序进行重启操作

**Comment by baoachun** [comment]
目前paddle inference是不支持的，你可以创建两个predictor来切换

**Comment by baoachun** [comment]
你好，能留个联系方式吗？

**Comment by TimZhang001** [comment]
什么时候可以考虑支持一下呢？

**Comment by baoachun** [comment]
可以按照我上面说的创建两个predictor来切换。

热加载以后也不会支持的
