### ISSUE TITLE
关于CosineEmbeddingLoss

### ISSUE THREAD

**Issue by safehumeng** [PaddlePaddle/Paddle#37505]
请问贵框架是否有实现CosineEmbeddingLoss，在文档里面没有找到
具体公式如下：
![image](https://user-images.githubusercontent.com/16226299/143190140-f4678cbc-b385-4606-ab2c-d6362e70584b.png)

1）PaddlePaddle版本：paddlepaddle-gpu:2.1.3.post112

**Comment by LielinJiang** [comment]
暂时没有，感谢您的反馈。我们评估下是否添加

**Comment by LielinJiang** [comment]
https://docs.qq.com/sheet/DWnhZS3N1WUhMUW5Z?tab=BB08J2，如果您有时间，麻烦填写一下这个需求表格。

**Comment by safehumeng** [comment]
已经填写到表格中

**Comment by Ligoml** [comment]
哈喽，该API已作为开发者社区任务发布在了飞桨黑客松中，详见https://github.com/PaddlePaddle/Paddle/issues/40316 ，飞桨团队非常感谢你的指出，也十分欢迎你参与进来，为飞桨框架补齐该API，共建更好用的深度学习框架~

**Comment by safehumeng** [comment]
> 哈喽，该API已作为开发者社区任务发布在了飞桨黑客松中，详见#40316 ，飞桨团队非常感谢你的指出，也十分欢迎你参与进来，为飞桨框架补齐该API，共建更好用的深度学习框架~
好的，谢谢提醒
