### ISSUE TITLE
论文复现报名vnet

### ISSUE THREAD

**Issue by YellowLight021** [PaddlePaddle/Paddle#37503]
【队名】：人工智障，医者仁心

【序号】：24

【论文】：V-Net: Fully Convolutional Neural Networks for Volumetric Medical Image Segmentation

【状态】：报名

【repo链接】：https://github.com/YellowLight021/Vnet

**Comment by TCChenlong** [comment]
开发者你好，报名是在这个ISSUE #37401 下回复哈~
