### ISSUE TITLE
【队名】：

### ISSUE THREAD

**Issue by YellowLight021** [PaddlePaddle/Paddle#37502]
【队名】：自动AC机

【序号】：84

【论文】：Convolutional Sequence to Sequence Learning

【状态】：报名

【repo链接】：https://github.com/robinbg/Paddle-ConvSeq2Seq

_Originally posted by @robinbg in https://github.com/PaddlePaddle/Paddle/issues/37401#issuecomment-975016223_

**Comment by TCChenlong** [comment]
开发者你好，报名是在这个ISSUE #37401 下回复哈~
