### ISSUE TITLE
gpu预测库cmake错误

### ISSUE THREAD

**Issue by snoopy1316** [PaddlePaddle/Paddle#37506]
win10从官网下载的gpu预测库，在vs2019上打开任何使用该预测库的项目的cmake设置进行编译时，都会显示CMake Error at D:\Paddle-Inference-Demo-master\Paddle-Inference-Demo-master\c++\paddle_infer_demo\CMakeLists.txt:27 (message):
  please set PADDLE_LIB with -DPADDLE_LIB=/path/paddle/lib应该怎么解决

**Comment by baoachun** [comment]
请参考该路径下的run.sh，cmake命令需要传入-DPADDLE_LIB=你的paddle预测库路径。https://github.com/PaddlePaddle/Paddle-Inference-Demo/blob/ab7307fc484da4d77169640e15604441c3a3d72b/c%2B%2B/paddle_infer_demo/run.sh#L19
