### ISSUE TITLE
 We only support 'to_tensor()' in dynamic graph mode, please call 'paddle.disable_static()' to enter dynamic graph mode.

### ISSUE THREAD

**Issue by aishangmaxiaoming** [PaddlePaddle/Paddle#37518]
<img width="1041" alt="8d5c8cd58a71c19a5fd7ef443a8b23a3" src="https://user-images.githubusercontent.com/67897601/143215823-a0191e50-282a-4bd8-a5af-4e8f75548bff.png">

**Comment by LielinJiang** [comment]
可以按照提示，进入到动态图模式中。

**Comment by Water2style** [comment]
> 可以按照提示，进入到动态图模式中。

可是我需求就是在 静态图模式啊。。。

**Comment by Reatris** [comment]
有可能是显存不够，训练退出了，所以feed也停止了
