### ISSUE TITLE
PaddleFL一轮训练后报错TypeError ‘numpy.float64’ object is not iterable

### ISSUE THREAD

**Issue by MaDanting** [PaddlePaddle/Paddle#37522]
你好，我基于paddlepaddle=1.8.0,paddlefl=1.1.2进行训练。
这是load_data：
```
def load_train_data(filename, feature_num=241):
    global SCS_TRAIN_DATA
    if SCS_TRAIN_DATA is not None:
        return

    data = np.loadtxt(filename, skiprows=1, delimiter=',',usecols=range(1,242))
    data = data.reshape(data.shape[0], feature_num)
    maximums, minimums, avgs = data.max(axis=0), data.min(axis=0), data.sum(
        axis=0) / data.shape[0]
    # if you want to print the distribution of input data, you could use function of feature_range
    #feature_range(maximums[:-1], minimums[:-1])
    for i in six.moves.range(feature_num - 1):
        data[:, i] = (data[:, i] - avgs[i]) / (maximums[i] - minimums[i])
    SCS_TRAIN_DATA = data
```
这是reader的封装
```
def train(file):
    global SCS_TRAIN_DATA
    load_train_data(file, 241)

    def reader():
        for d in SCS_TRAIN_DATA:
            yield d[:-1], d[-1:]

    return reader
```
这是我的网络结构

```
    def nn(self):
        self.inputs = fluid.layers.data(name='data', shape=[1, 240], dtype="float32")
        self.label = fluid.layers.data(name='label', shape=[1], dtype='int64')
        self.fc1 = fluid.layers.fc(input=self.inputs, size=240, act='relu')
        self.batch1 = fluid.layers.batch_norm(input=self.fc1)
        self.fc2 = fluid.layers.fc(input=self.batch1, size=256, act='relu')
        self.drop1 = fluid.layers.dropout(x=self.fc2, dropout_prob=0.8)
        self.batch2 = fluid.layers.batch_norm(input=self.drop1)
        self.fc3 = fluid.layers.fc(input=self.batch2, size=64, act='relu')      
        self.drop2 = fluid.layers.dropout(x=self.fc3, dropout_prob=0.8)
        self.batch3 = fluid.layers.batch_norm(input=self.drop2)
        self.predict = fluid.layers.fc(input=self.batch3, size=4, act='softmax')
        self.sum_cost = fluid.layers.cross_entropy(input=self.predict, label=self.label)
        self.accuracy = fluid.layers.accuracy(input=self.predict, label=self.label)
        self.loss = fluid.layers.reduce_mean(self.sum_cost)
        self.startup_program = fluid.default_startup_program()
```
在训练了一轮之后报错：
![image](https://user-images.githubusercontent.com/72608535/143230716-89974863-1772-4675-a4aa-8fab99d49c8a.png)

这是报错部分的相关代码：
```
def train_test(train_test_program, train_test_feed, train_test_reader):
    acc_set = []
    for test_data in train_test_reader():
        acc_np = trainer.exe.run(program=train_test_program,
                                 feed=train_test_feed.feed(test_data),
                                 fetch_list=["accuracy_0.tmp_0"])
        acc_set.append(float(acc_np[0])).np.astype
    acc_val_mean = np.array(acc_set).mean()
    return acc_val_mean

acc_val, avg_loss = train_test(
        train_test_program=test_program,
        train_test_reader=test_reader,
        train_test_feed=feeder)
```

**Comment by honshj** [comment]
> 你好，我基于paddlepaddle=1.8.0,paddlefl=1.1.2进行训练。 这是load_data：
> 
> ```
> def load_train_data(filename, feature_num=241):
>     global SCS_TRAIN_DATA
>     if SCS_TRAIN_DATA is not None:
>         return
> 
>     data = np.loadtxt(filename, skiprows=1, delimiter=',',usecols=range(1,242))
>     data = data.reshape(data.shape[0], feature_num)
>     maximums, minimums, avgs = data.max(axis=0), data.min(axis=0), data.sum(
>         axis=0) / data.shape[0]
>     # if you want to print the distribution of input data, you could use function of feature_range
>     #feature_range(maximums[:-1], minimums[:-1])
>     for i in six.moves.range(feature_num - 1):
>         data[:, i] = (data[:, i] - avgs[i]) / (maximums[i] - minimums[i])
>     SCS_TRAIN_DATA = data
> ```
> 
> 这是reader的封装
> 
> ```
> def train(file):
>     global SCS_TRAIN_DATA
>     load_train_data(file, 241)
> 
>     def reader():
>         for d in SCS_TRAIN_DATA:
>             yield d[:-1], d[-1:]
> 
>     return reader
> ```
> 
> 这是我的网络结构
> 
> ```
>     def nn(self):
>         self.inputs = fluid.layers.data(name='data', shape=[1, 240], dtype="float32")
>         self.label = fluid.layers.data(name='label', shape=[1], dtype='int64')
>         self.fc1 = fluid.layers.fc(input=self.inputs, size=240, act='relu')
>         self.batch1 = fluid.layers.batch_norm(input=self.fc1)
>         self.fc2 = fluid.layers.fc(input=self.batch1, size=256, act='relu')
>         self.drop1 = fluid.layers.dropout(x=self.fc2, dropout_prob=0.8)
>         self.batch2 = fluid.layers.batch_norm(input=self.drop1)
>         self.fc3 = fluid.layers.fc(input=self.batch2, size=64, act='relu')      
>         self.drop2 = fluid.layers.dropout(x=self.fc3, dropout_prob=0.8)
>         self.batch3 = fluid.layers.batch_norm(input=self.drop2)
>         self.predict = fluid.layers.fc(input=self.batch3, size=4, act='softmax')
>         self.sum_cost = fluid.layers.cross_entropy(input=self.predict, label=self.label)
>         self.accuracy = fluid.layers.accuracy(input=self.predict, label=self.label)
>         self.loss = fluid.layers.reduce_mean(self.sum_cost)
>         self.startup_program = fluid.default_startup_program()
> ```
> 
> 在训练了一轮之后报错： ![image](https://user-images.githubusercontent.com/72608535/143230716-89974863-1772-4675-a4aa-8fab99d49c8a.png)
> 
> 这是报错部分的相关代码：
> 
> ```
> def train_test(train_test_program, train_test_feed, train_test_reader):
>     acc_set = []
>     for test_data in train_test_reader():
>         acc_np = trainer.exe.run(program=train_test_program,
>                                  feed=train_test_feed.feed(test_data),
>                                  fetch_list=["accuracy_0.tmp_0"])
>         acc_set.append(float(acc_np[0])).np.astype
>     acc_val_mean = np.array(acc_set).mean()
>     return acc_val_mean
> 
> acc_val, avg_loss = train_test(
>         train_test_program=test_program,
>         train_test_reader=test_reader,
>         train_test_feed=feeder)
> ```

能否贴出你的fl_trainer.py的完整代码？

**Comment by MaDanting** [comment]
你好，这是fl_trainer的完整代码。
```
from paddle_fl.paddle_fl.core.trainer.fl_trainer import FLTrainerFactory
from paddle_fl.paddle_fl.core.master.fl_job import FLRunTimeJob
import paddle_fl.paddle_fl.dataset.femnist as femnist
import numpy
import sys
import paddle
import paddle.fluid as fluid
import logging
import math
import time
import scs_reader
logging.basicConfig(
    filename="test.log",
    filemode="w",
    format="%(asctime)s %(name)s:%(levelname)s:%(message)s",
    datefmt="%d-%M-%Y %H:%M:%S",
    level=logging.DEBUG)
trainer_id = int(sys.argv[1])  # trainer id for each guest
job_path = "fl_job_config"
job = FLRunTimeJob()
job.load_trainer_job(job_path, trainer_id)
job._scheduler_ep = "127.0.0.1:9091"  # Inform the scheduler IP to trainer
print(job._target_names)
trainer = FLTrainerFactory().create_fl_trainer(job)
trainer._current_ep = "127.0.0.1:{}".format(9000 + trainer_id)
place = fluid.CPUPlace()
trainer.start(place)
print(trainer._step)

test_program = trainer._main_program.clone(for_test=True)

file_name_train = 'RW_scs_dataset_4_clients/subset1_{}_train_RW.csv'.format (trainer_id)
file_name_test = 'RW_scs_dataset_4_clients/subset1_{}_test_RW.csv'.format (trainer_id)

data = fluid.layers.data(name='data', shape=[1, 240], dtype='float32')
label = fluid.layers.data(name='label', shape=[1], dtype='int64')
feeder = fluid.DataFeeder(feed_list=[data, label], place=fluid.CPUPlace())

def train_test(train_test_program, train_test_feed, train_test_reader):
    acc_set = []
    for test_data in train_test_reader():
        acc_np = trainer.exe.run(program=train_test_program,
                                 feed=train_test_feed.feed(test_data),
                                 fetch_list=["accuracy_0.tmp_0"])
        acc_set.append(float(acc_np[0]))
    acc_val_mean = numpy.array(acc_set).mean()
    return acc_val_mean

epoch_id = 0
step = 0
epoch = 10
output_folder = "models/model_node%d" % trainer_id
while not trainer.stop():
    count = 0
    epoch_id += 1
    if epoch_id > epoch:
        break
    print("{} Epoch {} start train".format(time.strftime('%Y-%m-%d %H:%M:%S',time.localtime(time.time())), epoch_id)
)
    #train_data,test_data= data_generater(trainer_id,inner_step=trainer._step,batch_size=64,count_by_step=count_by_s
tep)
    train_reader = paddle.batch(
        paddle.reader.shuffle(
            scs_reader.train(file_name_train),
            buf_size=100),
        batch_size=64)

        test_reader = paddle.batch(
        scs_reader.test(
            file_name_test),
        batch_size=64)
    acc_val = train_test(
        train_test_program=test_program,
        train_test_reader=test_reader,
        train_test_feed=feeder)
    print("Test with epoch %d, accuracy: %s" % (epoch_id, acc_val))
    if trainer_id == 0:
        save_dir = (output_folder + "/epoch_%d") % epoch_id
        trainer.save_inference_program(output_folder)
print("{} Train is ended".format(time.strftime('%Y-%m-%d %H:%M:%S',time.localtime(time.time()))))

```
另外，我在对fl_trainer的代码结构进行调整后，不再报错。但是当一轮训练结束后，一直都没有继续下一轮。也没有任何报错，同样也没有跳出训练。不知道是是第一轮还在eval阶段，test的数据读取仍然有问题。还是第二轮训练的数据读取有问题。

**Comment by qjing666** [comment]
报错应该在这一行：

**Comment by qjing666** [comment]
报错应该在这一行：
```
for test_data in train_test_reader():
```
可以看下train_test_reader函数的输出是否为可循环的格式。

报错信息看起来不是第二轮训练报错，而是第一轮测试集上的报错

**Comment by MaDanting** [comment]
> 报错应该在这一行：
> 
> ```
> for test_data in train_test_reader():
> ```
> 
> 可以看下train_test_reader函数的输出是否为可循环的格式。
> 
> 报错信息看起来不是第二轮训练报错，而是第一轮测试集上的报错

解决了，谢谢，是我的数据集封装还是存在一点问题。
还有一个问题想请教一下，在PaddleFL中进行横向联邦学习时，每个trainer必须使用相同的数据量进行训练吗？
我在使用dpsgd时，当4个trainer使用的数据量大小不同时，虽然报错，但是五个小时都没有获得第一轮训练的结果。
