### ISSUE TITLE
【论文复现赛】paddle.nn.functional.conv2d在转静态图时异常

### ISSUE THREAD

**Issue by justld** [PaddlePaddle/Paddle#37532]
版本：PaddlePaddle==2.2.0
环境：aistudio gpu至尊
异常信息：
在paddle.jit.to_static将模型转换为静态时，paddle.nn.functional.conv2d在以下情况会报错：

具体代码如下：

        import paddle
        import paddle.nn.functional as F
        
        class Model(paddle.nn.Layer):
            def __init__(self):
                super().__init__()
                self.weight = paddle.randn([1024, 1, 3, 3])
            
            def forward(self ,x):
                n, c, t, v = paddle.shape(x)
                groups = int((n * c).numpy())
                return F.conv2d(x, self.weight, groups=groups) # 这里换成1024就没问题
        
        x = paddle.randn([1, 1024, 224, 224])
        
        model = Model()
        y=model(x)
        print(x.shape, y.shape)
        shape = [None, 1024, None, None]
        new_model = paddle.jit.to_static(
                model,
                input_spec=[paddle.static.InputSpec(shape=shape, dtype='float32')])
        y = new_model(x)
        paddle.jit.save(new_model, 'model')
        print(x.shape, y.shape)

当groups参数不是以整数直接传入时，报错：
ValueError: The groups of conv2d should be greater than 0. Received groups: var cast_4.tmp_0 : LOD_TENSOR.shape(1,).dtype(int32).stop_gradient(False)

**Comment by FrostML** [comment]
您好，看报错信息是说，`group` 这个参数的输入需要是一个 `int`，但是传入了 `tensor`。动转静的时候，`paddle.shape` 的输出会被当做是 `tensor`，可以看看这里能否使用一个确定的 `int` 来表示。

**Comment by justld** [comment]
你好，我的group=batch_size * num_feature,batch_size不能保证每次训练都一样，group需要从输入的shape计算，请问有什么方法解决这个问题吗。

**Comment by wangxinxin08** [comment]
@justld 直接使用x.shape可以获取batch_size和channel的数值，而且动转静一般不用在训练上，你具体的需求可以说下吗？

**Comment by justld** [comment]
你好，是这样的，我用paddleseg复现了一个模型，下面是前向代码，模型已经训练好了，我需要把他转换成静态模型，在F.conv2d这里我需要得到一个tensor的维度(N,C,H,W)，把N*C作为F.conv2d的group值，因为我不能保证预测的时候batch_size不变，所以我传参的时候不能group固定值，请问有方法可以得到N*C并且把他作为F.conv2d的参数吗。

        def forward(self, x):
                generated_filter = self.filter_gen_conv(F.adaptive_avg_pool2d(x, self.filter_size))
                x = self.input_redu_conv(x)
                b, c, h, w = paddle.shape(x)
                x = x.reshape([1, b * c, h, w])
                generated_filter = generated_filter.reshape([b * c, 1, self.filter_size, self.filter_size])
                pad = (self.filter_size - 1) // 2
                if (self.filter_size - 1) % 2 == 0:
                    pad = (pad, pad, pad, pad)
                else:
                    pad = (pad + 1, pad, pad + 1, pad)
                x = F.pad(x, pad, mode='constant', value=0) # [1, b * c, h, w]
                output = F.conv2d(x, weight=generated_filter, groups=b.numpy() * c.numpy())  # 看这里
                output = output.reshape([b, c, h, w])
                output = self.norm(output)
                output = self.act(output)
                if self.fusion:
                    output = self.fusion_conv(output)
                return output

**Comment by wangxinxin08** [comment]
@justld groups的类型必须为int类型，使用x.shape而非paddle.shape可以获取数值型的batch size和channel，另外，对于你groups设置成batch_size * channel也感觉有点疑惑，可以看下这块是不是实现上有问题

**Comment by justld** [comment]
你好，了解了，groups设置没问题，减少参数用的。
