### ISSUE TITLE
ValueError: (InvalidArgument) Python object is not type of class std::shared_ptr<class paddle::imperative::VarBase> (at ..\paddle\fluid\pybind\imperative.cc:79)

### ISSUE THREAD

**Issue by DabeyHolmes** [PaddlePaddle/Paddle#37539]
- 标题：简洁、精准概括您的问题，例如“Insufficient Memory xxx" ”
- 版本、环境信息：
    1）PaddlePaddle版本：2.2
    2）GPU：RTX2080Ti，CUDA 11.2
    3）系统环境：WIN11 python3.8，3.7
- 训练信息
    1）单机/单卡
- 复现信息：如为报错，请给出复现环境、复现步骤
- 问题描述：请详细描述您的问题，同步贴出报错信息、日志、可复现的代码片段

我运行的是这个代码
https://github.com/PaddlePaddle/Research/tree/master/KG/ACL2021_GRAN
它原本的配置是
## Requirements
This project should work fine with the following environments:
- Python 2.7.15 for data preprocessing
- Python 3.6.5 for training & evaluation with:
    -  PaddlePaddle 1.5.0
    -  numpy 1.16.3
- GPU with CUDA 9.0, CuDNN v7, and NCCL 2.3.7
但是我是使用的最新的paddle2.2 python3.8
我运行这个代码会直接报错，windows linux都会报相同错
```
C:\ProgramData\Anaconda3\envs\tl\lib\site-packages\paddle\fluid\layers\io.py:721: DeprecationWarning: The 'warn' function is deprecated, use 'warning' instead
  'paddle.fluid.layers.py_reader() may be deprecated in the near future. '
WARNING:root:paddle.fluid.layers.py_reader() may be deprecated in the near future. Please use paddle.fluid.io.DataLoader.from_generator() instead.
Traceback (most recent call last):
  File "./src/run.py", line 453, in <module>
    main(args)
  File "./src/run.py", line 258, in main
    pyreader_name='train_reader', config=config)
  File "./src/run.py", line 125, in create_model
    use_double_buffer=True)
  File "C:\ProgramData\Anaconda3\envs\tl\lib\site-packages\paddle\fluid\layers\io.py", line 729, in py_reader
    use_double_buffer=use_double_buffer)
  File "C:\ProgramData\Anaconda3\envs\tl\lib\site-packages\paddle\fluid\layers\io.py", line 453, in _py_reader
    'ranks': ranks
  File "C:\ProgramData\Anaconda3\envs\tl\lib\site-packages\paddle\fluid\framework.py", line 3167, in append_op
    kwargs.get("stop_gradient", False))
  File "C:\ProgramData\Anaconda3\envs\tl\lib\site-packages\paddle\fluid\dygraph\tracer.py", line 45, in trace_op
    not stop_gradient)
ValueError: (InvalidArgument) Python object is not type of class std::shared_ptr<class paddle::imperative::VarBase> (at ..\paddle\fluid\pybind\imperative.cc:79)
```

**Comment by FrostML** [comment]
您好，Paddle 1.5.0 和 Paddle 2.2 差了好几个版本了，中间甚至可能会有些不兼容升级，用 2.2 直接跑 1.5 的模型大概率是不行的。可以在 PaddlePaddle/Research 这个 repo 下提一个 issue 问问这个作者是否后续有升级到新版 paddle 的计划

**Comment by DabeyHolmes** [comment]
我用了1.5.0.post97，cuda9.2，cudnn7.6.5
会报错parallel_for failed: no kernel image is available for execution on the device

**Comment by DabeyHolmes** [comment]
您好，我用了paddlepaddle-gpu==1.5.0.post97，cuda9.2，cudnn7.6.5
会报错parallel_for failed: no kernel image is available for execution on the device
![image](https://user-images.githubusercontent.com/49112179/143395416-cf7ba138-6ac2-4ae9-823a-bd5fc8d0e924.png)

**Comment by FrostML** [comment]
您的显卡是？可能是 paddle 1.5 在硬件层面的不支持。

**Comment by DabeyHolmes** [comment]
> 

您好，我的显卡是3070的，显存8G，是因为这个原因不支持么

**Comment by FrostML** [comment]
paddle 1.5 release 的时候，3070 好像还没出。可以在 [PaddlePaddle/Research](https://github.com/PaddlePaddle/Research/issues) 这个 repo 下提一个 issue @ 这个作者是否后续有升级到新版 paddle 上的计划吧

**Comment by Xinrj-encore** [comment]
> 您好，我用了paddlepaddle-gpu==1.5.0.post97，cuda9.2，cudnn7.6.5 会报错parallel_for failed: no kernel image is available for execution on the device ![image](https://user-images.githubusercontent.com/49112179/143395416-cf7ba138-6ac2-4ae9-823a-bd5fc8d0e924.png)
楼主您好，您这个问题解决了吗

**Comment by DabeyHolmes** [comment]
> > 您好，我用了paddlepaddle-gpu==1.5.0.post97，cuda9.2，cudnn7.6.5 会报错parallel_for failed: no kernel image is available for execution on the device ![image](https://user-images.githubusercontent.com/49112179/143395416-cf7ba138-6ac2-4ae9-823a-bd5fc8d0e924.png)
> > 楼主您好，您这个问题解决了吗

不好意思，我当时放弃了没有解决，如果您之后解决的话希望也可以分享一下= =
