### ISSUE TITLE
module 'paddle' has no attribute 'bool'

### ISSUE THREAD

**Issue by BossCrab-jyj** [PaddlePaddle/Paddle#37542]
为使您的问题得到快速解决，在建立Issues前，请您先通过如下方式搜索是否有相似问题:【搜索issue关键字】【使用labels筛选】【官方文档】

- 标题：module 'paddle' has no attribute 'bool'
- 版本、环境信息：
    1）PaddlePaddle版本：2.0.2
    2）CPU/GPU： CUDA==10.0
    3）系统环境：jetson nano jetpack2.0.2
    4）Python版本号 3.6
    5）显存信息

- 复现信息：from parakeet.models.lstm_speaker_encoder import LSTMSpeakerEncoder

-                     ~/notebooks/Parakeet/parakeet/modules/fastspeech2_transformer/mask.py in <module>
                     17 import torch
                     18 
                ---> 19 def subsequent_mask(size, dtype=paddle.bool):
                     20     """Create mask for subsequent steps (size, size).
                     21     Parameters

                AttributeError: module 'paddle' has no attribute 'bool'

**Comment by BossCrab-jyj** [comment]
将 def subsequent_mask(size, dtype=paddle.bool): 改为def subsequent_mask(size, dtype=torch.bool): 可以通过，但是不确定会不会有其他问题。

**Comment by yt605155624** [comment]
您好，我是 Parakeet 的研发，paddle.bool paddle.float32 这类用法在 paddle 2.1.2 之后可用，或者您直接改成 dtype = "bool", 我们是 paddle 的代码，您把中间的某个模块换成 torch 肯定是不可用的，另外, Parakeet 所有模型已经迁移到  https://github.com/PaddlePaddle/PaddleSpeech, Parakeet 将不再维护，Parakeet 中的 Vocoder 用到了 paddle 2.2.0 新开发的 stft 算子，如果要使用，您需要把 paddle 更新到 2.2.0，谢谢~！

**Comment by BossCrab-jyj** [comment]
目前正在部署Parakeet中语音合成这个demo，上面这个问题已经解决了，还差最后这一步，不知道这个问题能否解决，谢谢！
mel_input: Tensor(shape=[1, 80, 1000], dtype=float32, place=CUDAPlace(0), stop_gradient=True,
       [[[-3.66981173, -1.52852535, -1.50886941, ...,  nan       ,  nan       ,  nan       ],
         [-4.53145790, -2.15945172, -2.15585017, ...,  nan       ,  nan       ,  nan       ],
         [-4.92798853, -2.69236684, -2.59501100, ...,  nan       ,  nan       ,  nan       ],
         ...,
         [-7.74958944, -2.52022743, -0.99760777, ...,  nan       ,  nan       ,  nan       ],
         [-7.79844284, -2.66666746, -1.30523169, ...,  nan       ,  nan       ,  nan       ],
         [-7.91582775, -3.06956339, -1.73107386, ...,  nan       ,  nan       ,  nan       ]]])

with paddle.no_grad():
    wav = vocoder.infer(mel_input)
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-20-b70c2f607bc0> in <module>
      1 with paddle.no_grad():
----> 2     wav = vocoder.infer(mel_input)

</usr/local/lib/python3.6/dist-packages/decorator.py:decorator-gen-353> in infer(self, mel)

/usr/local/lib/python3.6/dist-packages/paddle/fluid/dygraph/base.py in _decorate_function(func, *args, **kwargs)
    313         def _decorate_function(func, *args, **kwargs):
    314             with self:
--> 315                 return func(*args, **kwargs)
    316 
    317         @decorator.decorator

~/notebooks/Parakeet/parakeet/models/waveflow.py in infer(self, mel)
    800         batch_size, _, time_steps = condition.shape
    801         z = paddle.randn([batch_size, time_steps], dtype="float32")
--> 802         x = self.decoder.inverse(z, condition)
    803         end = time.time()
    804         print("time: {}s".format(end - start))

~/notebooks/Parakeet/parakeet/models/waveflow.py in inverse(self, z, condition)
    702         # reverse it flow by flow
    703         for i in reversed(range(self.n_flows)):
--> 704             z = geo.shuffle_dim(z, 2, perm=self.perms[i])
    705             condition = geo.shuffle_dim(condition, 2, perm=self.perms[i])
    706             z = self[i].inverse(z, condition)

~/notebooks/Parakeet/parakeet/modules/geometry.py in shuffle_dim(x, axis, perm)
     46         perm = np.random.permutation(size)
     47     print(perm)
---> 48     perm = paddle.to_(perm)
     49     out = paddle.gather(x, perm, axis)
     50     return out

</usr/local/lib/python3.6/dist-packages/decorator.py:decorator-gen-234> in to_tensor(data, dtype, place, stop_gradient)

/usr/local/lib/python3.6/dist-packages/paddle/fluid/wrapped_decorator.py in __impl__(func, *args, **kwargs)
     23     def __impl__(func, *args, **kwargs):
     24         wrapped_func = decorator_func(func)
---> 25         return wrapped_func(*args, **kwargs)
     26 
     27     return __impl__

/usr/local/lib/python3.6/dist-packages/paddle/fluid/framework.py in __impl__(*args, **kwargs)
    223         assert in_dygraph_mode(
    224         ), "We only support '%s()' in dynamic graph mode, please call 'paddle.disable_static()' to enter dynamic graph mode." % func.__name__
--> 225         return func(*args, **kwargs)
    226 
    227     return __impl__

/usr/local/lib/python3.6/dist-packages/paddle/tensor/creation.py in to_tensor(data, dtype, place, stop_gradient)
    176         persistable=False,
    177         zero_copy=False,
--> 178         stop_gradient=stop_gradient)
    179 
    180 

ValueError: 

--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
0   paddle::platform::EnforceNotMet::EnforceNotMet(paddle::platform::ErrorSummary const&, char const*, int)
1   paddle::platform::GetCurrentTraceBackString[abi:cxx11]()

----------------------
Error Message Summary:
----------------------
InvalidArgumentError: Input object type error or incompatible array data type. tensor.set() supports array with bool, float16, float32, float64, int8, int16, int32, int64, uint8 or uint16, please check your input or input array data type. (at /media/paddle/a2a27488-590d-40c0-aec9-20efadb82b81/wangye19/Paddle/paddle/fluid/pybind/tensor_py.h:355)

**Comment by yt605155624** [comment]
你这个是在做动转静的过程中报错的嘛，如果是的话，可以根据官网动转静相关 issue 尝试解决，另外，看起来您像是想要用 ge2e + tacotron2 + waveflow 实现语音克隆？这套代码比较老了，我们也没有针对性的处理动转静问题，不过我们最近开源了 ge2e + fastspeech2 + pwgan 的语音克隆项目，欢迎关注 https://github.com/PaddlePaddle/PaddleSpeech/tree/develop/examples/aishell3/vc1

**Comment by yingjie-jiang** [comment]
好的，谢谢，不过我使用的是jetson nano jetpack4.3 cuda10.0，官方只提供了paddle2.0.2版本的安装包，看来在这个板子上面应该实现不了了

**Comment by BossCrab-jyj** [comment]
好的，谢谢，不过我使用的是jetson nano jetpack4.3 cuda10.0，官方只提供了paddle2.0.2版本的安装包，如果在服务器上部署应该会方便很多

**Comment by FrostML** [comment]
https://paddleinference.paddlepaddle.org.cn/master/user_guides/download_lib.html#python
新版的安装包可以在这里看到
