### ISSUE TITLE
在服务器centos7.9上推理模型时，报如下错。

### ISSUE THREAD

**Issue by liu1073811240** [PaddlePaddle/Paddle#37548]
OMP: Error #15: Initializing libiomp5.so, but found libiomp5.so already initialized.
OMP: Hint This means that multiple copies of the OpenMP runtime have been linked into the program. That is dangerous, since it can degrade performance or cause incorrect results. The best thing to do is to ensure that only a single OpenMP runtime is linked into the process, e.g. by avoiding static linking of the OpenMP runtime in any library. As an unsafe, unsupported, undocumented workaround you can set the environment variable KMP_DUPLICATE_LIB_OK=TRUE to allow the program to continue to execute, but that may cause crashes or silently produce incorrect results. For more information, please see http://www.intel.com/software/products/support/.

--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
0   paddle::AnalysisPredictor::ZeroCopyRun()
1   paddle::framework::NaiveExecutor::Run()
2   paddle::framework::OperatorBase::Run(paddle::framework::Scope const&, paddle::platform::Place const&)
3   paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, paddle::platform::Place const&) const
4   paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, paddle::platform::Place const&, paddle::framework::RuntimeContext*) const
5   std::_Function_handler<void (paddle::framework::ExecutionContext const&), paddle::framework::OpKernelRegistrarFunctor<paddle::platform::CPUPlace, false, 0ul, paddle::operators::GemmConvKernel<paddle::platform::CPUDeviceContext, float>, paddle::operators::GemmConvKernel<paddle::platform::CPUDeviceContext, double> >::operator()(char const*, char const*, int) const::{lambda(paddle::framework::ExecutionContext const&)#1}>::_M_invoke(std::_Any_data const&, paddle::framework::ExecutionContext const&)
6   paddle::operators::GemmConvKernel<paddle::platform::CPUDeviceContext, float>::Compute(paddle::framework::ExecutionContext const&) const
7   void paddle::operators::math::Blas<paddle::platform::CPUDeviceContext>::MatMul<float>(paddle::framework::Tensor const&, bool, paddle::framework::Tensor const&, bool, float, paddle::framework::Tensor*, float) const
8   cblas_sgemm
9   sgemm
10  mkl_blas_sgemm
11  mkl_serv_get_num_stripes
12  omp_get_num_procs

----------------------
Error Message Summary:
----------------------
FatalError: `Process abort signal` is detected by the operating system.
  [TimeInfo: *** Aborted at 1637825304 (unix time) try "date -d @1637825304" if you are using GNU date ***]
  [SignalInfo: *** SIGABRT (@0x32027) received by PID 204839 (TID 0x7f188c6d1740) from PID 204839 ***]

**Comment by shangzhizhou** [comment]
请问是否您的工程也依赖了OMP呢，可以把工程对OMP的依赖去掉试试？

**Comment by liu1073811240** [comment]
谢谢，昨天解决了，推理paddleocr的时候没有将GPU改为True。




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Shang ***@***.***&gt;; 
发送时间: 2021年11月26日(星期五) 上午9:33
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [PaddlePaddle/Paddle] 在服务器centos7.9上推理模型时，报如下错。 (Issue #37548)





 
请问是否您的工程也依赖了OMP呢，可以把工程对OMP的依赖去掉试试？
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by shangzhizhou** [comment]
了解。
