### ISSUE TITLE
win11的WSL2子系统支持飞桨的GPU运行么？

### ISSUE THREAD

**Issue by mijjjj** [PaddlePaddle/Paddle#37557]
因为工作原因，我手头上没有linux机器，然后使用了win11的WSL2 linux子系统，想使用飞桨的11.2 gpu运行模型。官方是否使用过这种方式

**Comment by FrostML** [comment]
咨询了 @zhouwei25 ，目前没测过 Windows 的 Linux 子系统，理论上可以用，可以先尝试下，如果有问题可以再提 issue。

**Comment by mijjjj** [comment]
可以帮忙测试下么，现在有很多用户跟我有一样的需求，我现在按照[NVIDIA的官方驱动](https://docs.nvidia.com/cuda/wsl-user-guide/index.html#abstract)安装了驱动，我是用的显卡是GTX 750TI，wsl2子系统中已经通过Conda安装了CUDA11.2，但是提示python命令提示 parallel_for failed: cudaErrorNoKernelImageForDevice: no kernel image is available for execution on the device

**Comment by FrostML** [comment]
麻烦 @zhouwei25 帮忙看看

**Comment by zhwesky2010** [comment]
> 可以帮忙测试下么，现在有很多用户跟我有一样的需求，我现在按照[NVIDIA的官方驱动](https://docs.nvidia.com/cuda/wsl-user-guide/index.html#abstract)安装了驱动，我是用的显卡是GTX 750TI，wsl2子系统中已经通过Conda安装了CUDA11.2，但是提示python命令提示 parallel_for failed: cudaErrorNoKernelImageForDevice: no kernel image is available for execution on the device

您好，这个原因不是WSL的原因，是由于目前CUDA11.2支持的显卡计算能力较高，不支持 5.0计算能力的显卡，可以安装Paddle 10.1或10.2版本的包

![image](https://user-images.githubusercontent.com/52485244/143521121-d1d6a4e0-0df5-4ed8-ace0-7e412f347677.png)
