### ISSUE TITLE
pooling layer 的输出使用 activation function 

### ISSUE THREAD

**Issue by hw810** [PaddlePaddle/Paddle#3755]
请问一下 pooling layer 的结果在不使用额外 fc 层的情况下可以使用activation 吗？

**Comment by lcy-seso** [comment]
- Paddle 的实现中 pooling layer 没有激活。
- 一般在pooling 的输入层加
- 如果确实需要对pooling之后的记过进行激活：可以增加一个（1） `paddle.layer.add_to`输入是pooling层的输出，（2）或者`paddle.layer.mixed_layer` 输入是 `indentity_projection`，而 `indentity_projection`的输入是 pooling 层的输出。最后再对`add_to` 或者 `mixed` 层激活，

**Comment by pkuyym** [comment]
Close due to solved, please feel free to reopen if necessary.
