### ISSUE TITLE
其他模型生成的protobuf文件如何转换成paddle可读取的格式

### ISSUE THREAD

**Issue by majiayuanyuan** [PaddlePaddle/Paddle#3756]
https://github.com/PaddlePaddle/Paddle/issues/964 这个里面解决了 参数转换的问题，但是paddle里面解析参数的时候，还需要protobuf文件 ，其他模型生成的protobuf文件如何转换成paddle可读取的格式呢

**Comment by qingqing01** [comment]
@majiayuanyuan  改了标题，实在太长~~~

**Comment by luotao1** [comment]
可以参考
- [convert Caffe model file to PaddlePaddle model file](https://github.com/PaddlePaddle/models/tree/develop/image_classification/caffe2paddle)
- [convert TensorFlow model file to PaddlePaddle model file](https://github.com/PaddlePaddle/models/tree/develop/image_classification/tf2paddle)
