### ISSUE TITLE
如何获取或者编译ARM C++接口库

### ISSUE THREAD

**Issue by se7enXF** [PaddlePaddle/Paddle#37567]
查看了安装说明，从源码的例子展示的是编译python包的流程，我现在想用推理的C++接口，但是编译选项中似乎找不到相关设置。
我的编译环境不能访问互联网，看到CMakeList中需要下载若干第三方文件，是否有方法手动下载到目录中进行编译。
我的环境：Arm 64 Ubuntu，支持ascend npu。

**Comment by DannyIsFunny** [comment]
Paddle-Lite 支持ascend npu 端推理
建议使用Paddle Lite ，[华为昇腾 NPU 部署示例](https://paddle-lite.readthedocs.io/zh/latest/demo_guides/huawei_ascend_npu.html)

**Comment by se7enXF** [comment]
> Paddle-Lite 支持ascend npu 端推理 建议使用Paddle Lite ，[华为昇腾 NPU 部署示例](https://paddle-lite.readthedocs.io/zh/latest/demo_guides/huawei_ascend_npu.html)

好的，非常感谢！有问题再沟通。
