### ISSUE TITLE
【论文复现】 关于基础链条测试

### ISSUE THREAD

**Issue by FL77N** [PaddlePaddle/Paddle#37572]
您好，我在做 infer 的时候，一直报一下错误：
test_tipc/test_train_inference_python.sh: line 29: [: =: unary operator expected
python3.7: can't open file 'gpu': [Errno 2] No such file or directory
 Run failed with command - python3.7 gpu|cpu --enable_mkldnn=False --cpu_threads=1 --batch_size=1 --image_dir=./test_tipc/output/norm_train_gpus_0_autocast_amp/fast_rcnn_r50_fpn_1x_coco   --save_log_path=./test_tipc/demo/     > ./test_tipc/output/infer_cpu_usemkldnn_1_threads_1_batchsize_null.log 2>&1 !

test_train_inference_python.sh: line 29:
function func_set_params(){
    key=$1
    value=$2
    if [ ${key} = "null" ];then
        echo " "
    elif [[ ${value} = "null" ]] || [[ ${value} = " " ]] || [ ${#value} -le 0 ];then
        echo " "
    else
        echo "${key}=${value}"
    fi
}

infer_model:model_final.pdparams
infer_model_dir:./test_tipc/weights
infer_quant:False
inference:deploy/python/infer.py
--device:gpu|cpu
--enable_mkldnn:False|True
--cpu_threads:1|4
--batch_size:1
--use_tensorrt:null
--run_mode:fluid|trt_fp32|trt_fp16|trt_int8
--model_dir:
--image_dir:./dataset/coco/val2017/
--save_log_path:null
--run_benchmark:True
null:null

但如果将 --device:gpu|cpu 删除就不会报错

**Comment by zhangting2020** [comment]
请问test_train_inference_python.sh是你自己实现的脚本，还是官方哪个模型库中提供的呢，可以提供下链接？

**Comment by jerrywgz** [comment]
可以是用PaddleDetection下提供的tipc脚本进行测试 https://github.com/PaddlePaddle/PaddleDetection/tree/develop/test_tipc

**Comment by FL77N** [comment]
> 请问test_train_inference_python.sh是你自己实现的脚本，还是官方哪个模型库中提供的呢，可以提供下链接？

链接为 https://github.com/deepinsight/insightface/tree/master/recognition/arcface_paddle/test_tipc

**Comment by FL77N** [comment]
> 可以是用PaddleDetection下提供的tipc脚本进行测试 https://github.com/PaddlePaddle/PaddleDetection/tree/develop/test_tipc

好的，谢谢

**Comment by zhangting2020** [comment]
@FL77N 问题是否已解决呢

**Comment by FL77N** [comment]
> @FL77N 问题是否已解决呢

解决了但没完全解决，已转移至 ppdet 提 issue 解决过程中^v^
