### ISSUE TITLE
关于对齐torch.nn.init.constant_方法

### ISSUE THREAD

**Issue by Y1YU** [PaddlePaddle/Paddle#37578]
在复现论文时，发现paddle中没有对torch.nn.init.constant_()方法的对齐

torch中，可以直接这么定义 nn.init.constant_(m.bias, 0)，但是paddle中只找到nn.initializer.Constant()方法，并且它的使用是这样的nn.Linear(m.bias = nn.initializer.Constant(value=0))，必须在方法中对参数进行赋值，但我的使用场景是先判断m是不是nn.Layer，如果是就直接赋值，m.bias = nn.initializer.Constant(value=0)，这样就会报错
> TypeError: assignment to parameter 'bias' should be of type Parameter or None, but got 'Constant'

可以修复一下这个问题吗

**Comment by zhangting2020** [comment]
（1）报错的原因：在Paddle中，m.bias是一个parameter对象，不允许直接用Constant对象赋值，报错本身没问题。

（2）目前我们暂时未提供constant_ 这样的API，这种属于inplace API，可以直接对Tensor赋值。我根据你的需求写了一段示例代码，你可以参考：

```
import paddle
import paddle.nn as nn
import numpy as np

# Define the linear layer.
m = paddle.nn.Linear(2, 4)
print(m.bias)
if isinstance(m, nn.Layer):
    print("set m.bias")
    m.bias.set_value(np.ones(shape=m.bias.shape, dtype="float32"))
    print(m.bias)
```

输出
```
Parameter containing:
Tensor(shape=[4], dtype=float32, place=CUDAPlace(0), stop_gradient=False,
       [0., 0., 0., 0.])
set m.bias
Parameter containing:
Tensor(shape=[4], dtype=float32, place=CUDAPlace(0), stop_gradient=False,
       [1., 1., 1., 1.])
```

**Comment by Y1YU** [comment]
好的感谢
