### ISSUE TITLE
模型训练，adam op的输入grad出现nan、inf。

### ISSUE THREAD

**Issue by helen88** [PaddlePaddle/Paddle#37587]
- 版本、环境信息：
    1）PaddlePaddle版本：develop版本，开启支持xpu编译产出
    2）XPU
- 训练信息
    1）单机,单卡
    
我是在训练推荐的deepfm模型：adam这个op的输入grad出现nan和inf，之前的op输入输出都没有nan和inf。

![image](https://user-images.githubusercontent.com/4593091/143532047-bfeedb9d-818c-4d50-bb9f-4ca4621525ae.png)

另外， 使用PaddleRec下的训练代码 ，log_loss会有nan的情况：
路径在 PaddleRec-release-2.1.0/models/rank/deepfm/dygraph_model.py
![image](https://user-images.githubusercontent.com/4593091/143532304-7b31c114-e60e-4a06-be3b-385278d6b229.png)

参考官网：https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/nn/functional/log_loss_cn.html#cn-api-fluid-layers-log-loss  
这里面的示例代码在cpu跑出来都有nan：
![image](https://user-images.githubusercontent.com/4593091/143532400-fa872bb7-551e-48e6-b7d4-3d36ed68742e.png)

![image](https://user-images.githubusercontent.com/4593091/143532415-c82a4b84-a592-406c-a559-ec69877beb23.png)

**Comment by helen88** [comment]
补充下信息：我是在KL2，昆仑2 上跑的训练，超参都没有做改动。

**Comment by zhangting2020** [comment]
我看了下log，是linear_1.w的梯度出现了nan。你的第二个测试，是说怀疑log_loss这个API导致的吗？

- 我测试了下官网文档的例子log_loss确实出现nan，在GPU/CPU上都出现nan
  - GPU
![image](https://user-images.githubusercontent.com/26615455/143534185-12534fb4-fba9-41ae-8c4e-e477d0995f28.png)
  - CPU
![image](https://user-images.githubusercontent.com/26615455/143534205-81b75626-9506-4851-9926-5b04ea39aeed.png)

- 是否方便换一个loss试试，确认下是不是log_loss引起的，因为XPU上和CPU并不是同一个kernel实现。

**Comment by helen88** [comment]
我已经换成了bce loss，
![image](https://user-images.githubusercontent.com/4593091/143534744-46a1943d-b4ff-4c75-8e5f-70ec2557d6ae.png)
还是有相同的问题。

**Comment by zhangting2020** [comment]
看上去并不一定是loss引起的，能尝试用这个检查nan的工具看看，最开始是在网络哪一层出现的nan吗？另外如果查到可以将输入保存下来，上传到这里。https://www.paddlepaddle.org.cn/documentation/docs/zh/guides/flags/check_nan_inf_cn.html#check-nan-inf

**Comment by zhangting2020** [comment]
经用户定位是，是matmul_v2_grad XPU算子的bug，并反馈check-nan-inf工具不支持XPU

**Comment by helen88** [comment]
Thank~
