### ISSUE TITLE
paddle中没有torch.tensor.erfinv()对应API

### ISSUE THREAD

**Issue by Y1YU** [PaddlePaddle/Paddle#37588]
如题，paddle中只有paddle.erf()，而没有paddle.erfinv()对应实现，请问怎么解决呢

**Comment by zhangting2020** [comment]
您好，目前Paddle暂时没有提供该API。请问是在什么任务中/场景中需要用到？我们会尽快评估，在后续版本中进行添加该API。

**Comment by Y1YU** [comment]
论文中使用到trunc_normal()对参数进行初始化，调用的是timm的trunc_normal_()，里面用到torch.tensorerfinv()，但是用paddle复现时paddle没有这个函数。原论文代码像这样`trunc_normal_(m.weight, std=0.02)`

**Comment by zhangting2020** [comment]
好的，另外确认下，这个是在做论文复现任务吗？

**Comment by Y1YU** [comment]
对

**Comment by Ligoml** [comment]
你好，请问你复现的赛题是哪一道？是否加入了微信答疑群？这个 api 会阻塞你的论文复现吗？如果阻塞我们会高优增加这个 api 的支持~
