### ISSUE TITLE
在RK3399+麒麟操作系统上编译paddle报错

### ISSUE THREAD

**Issue by thugbobby** [PaddlePaddle/Paddle#37594]
RK3399+麒麟V4操作系统编译Paddle2.1环境时，执行如下命令报错：
`cmake .. -DPY_VERSION=3 -DPYTHON_EXECUTABLE=`which python` -DWITH_ARM=ON -DWITH_TESTING=OFF -DCMAKE_BUILD_TYPE=Release -DON_INFER=ON -DWITH_XBYAK=OFF`
报错如下：
`CMake Error at paddle/fluid/operators/controlflow/CMakeLists.txt:6 (register_operators):
  Unknown CMake command "register_operators".

-- Configuring incomplete, errors occurred!
See also "/home/kylin/Paddle/build/CMakeFiles/CMakeOutput.log".
See also "/home/kylin/Paddle/build/CMakeFiles/CMakeError.log".`

**Comment by zhangting2020** [comment]
麻烦查看下编译log，将关键错误内容上传一下

**Comment by thugbobby** [comment]
> 麻烦查看下编译log，将关键错误内容上传一下

Source file was:
int main() { return 0; }
Performing C SOURCE FILE Test C_COMPILER_SUPPORT_FLAG__Wno_error_int_in_bool_context failed with the following output:
Change Dir: /home/kylin/Paddle/build/CMakeFiles/CMakeTmp

Run Build Command(s):/usr/bin/make cmTC_dc3ac/fast && /usr/bin/make  -f CMakeFiles/cmTC_dc3ac.dir/build.make CMakeFiles/cmTC_dc3ac.dir/build
make[1]: Entering directory '/home/kylin/Paddle/build/CMakeFiles/CMakeTmp'
Building C object CMakeFiles/cmTC_dc3ac.dir/src.c.o
/usr/bin/cc   -fPIC -fno-omit-frame-pointer -Werror -Wall -Wextra -Wno-unused-parameter -Wno-unused-function -Wno-error=literal-suffix -Wno-error=unused-local-typedefs -DC_COMPILER_SUPPORT_FLAG__Wno_error_int_in_bool_context   -Wno-error=int-in-bool-context -o CMakeFiles/cmTC_dc3ac.dir/src.c.o   -c /home/kylin/Paddle/build/CMakeFiles/CMakeTmp/src.c
cc1: error: -Werror=int-in-bool-context: no option -Wint-in-bool-context
CMakeFiles/cmTC_dc3ac.dir/build.make:68: recipe for target 'CMakeFiles/cmTC_dc3ac.dir/src.c.o' failed
make[1]: *** [CMakeFiles/cmTC_dc3ac.dir/src.c.o] Error 1
make[1]: Leaving directory '/home/kylin/Paddle/build/CMakeFiles/CMakeTmp'
Makefile:124: recipe for target 'cmTC_dc3ac/fast' failed
make: *** [cmTC_dc3ac/fast] Error 2


Source file was:
int main(void) { return 0; }
Performing C++ SOURCE FILE Test CXX_COMPILER_SUPPORT_FLAG__Wno_error_int_in_bool_context failed with the following output:
Change Dir: /home/kylin/Paddle/build/CMakeFiles/CMakeTmp

Run Build Command(s):/usr/bin/make cmTC_a59a2/fast && /usr/bin/make  -f CMakeFiles/cmTC_a59a2.dir/build.make CMakeFiles/cmTC_a59a2.dir/build
make[1]: Entering directory '/home/kylin/Paddle/build/CMakeFiles/CMakeTmp'
Building CXX object CMakeFiles/cmTC_a59a2.dir/src.cxx.o
/usr/bin/c++    -Wno-error=deprecated-declarations -Wno-deprecated-declarations -std=c++14 -fPIC -fno-omit-frame-pointer -Werror -Wall -Wextra -Wnon-virtual-dtor -Wdelete-non-virtual-dtor -Wno-unused-parameter -Wno-unused-function -Wno-error=literal-suffix -Wno-error=unused-local-typedefs -DCXX_COMPILER_SUPPORT_FLAG__Wno_error_int_in_bool_context   -Wno-error=int-in-bool-context -o CMakeFiles/cmTC_a59a2.dir/src.cxx.o -c /home/kylin/Paddle/build/CMakeFiles/CMakeTmp/src.cxx
cc1plus: error: -Werror=int-in-bool-context: no option -Wint-in-bool-context
CMakeFiles/cmTC_a59a2.dir/build.make:68: recipe for target 'CMakeFiles/cmTC_a59a2.dir/src.cxx.o' failed
make[1]: *** [CMakeFiles/cmTC_a59a2.dir/src.cxx.o] Error 1
make[1]: Leaving directory '/home/kylin/Paddle/build/CMakeFiles/CMakeTmp'
Makefile:124: recipe for target 'cmTC_a59a2/fast' failed
make: *** [cmTC_a59a2/fast] Error 2


Source file was:
int main() { return 0; }
Performing C SOURCE FILE Test C_COMPILER_SUPPORT_FLAG__Wimplicit_fallthrough_0 failed with the following output:
Change Dir: /home/kylin/Paddle/build/CMakeFiles/CMakeTmp

Run Build Command(s):/usr/bin/make cmTC_8b721/fast && /usr/bin/make  -f CMakeFiles/cmTC_8b721.dir/build.make CMakeFiles/cmTC_8b721.dir/build
make[1]: Entering directory '/home/kylin/Paddle/build/CMakeFiles/CMakeTmp'
Building C object CMakeFiles/cmTC_8b721.dir/src.c.o
/usr/bin/cc   -fPIC -fno-omit-frame-pointer -Werror -Wall -Wextra -Wno-unused-parameter -Wno-unused-function -Wno-error=literal-suffix -Wno-error=unused-local-typedefs -DC_COMPILER_SUPPORT_FLAG__Wimplicit_fallthrough_0   -Wimplicit-fallthrough=0 -o CMakeFiles/cmTC_8b721.dir/src.c.o   -c /home/kylin/Paddle/build/CMakeFiles/CMakeTmp/src.c
cc: error: unrecognized command line option '-Wimplicit-fallthrough=0'
CMakeFiles/cmTC_8b721.dir/build.make:68: recipe for target 'CMakeFiles/cmTC_8b721.dir/src.c.o' failed
make[1]: *** [CMakeFiles/cmTC_8b721.dir/src.c.o] Error 1
make[1]: Leaving directory '/home/kylin/Paddle/build/CMakeFiles/CMakeTmp'
Makefile:124: recipe for target 'cmTC_8b721/fast' failed
make: *** [cmTC_8b721/fast] Error 2


Source file was:
int main(void) { return 0; }
Performing C++ SOURCE FILE Test CXX_COMPILER_SUPPORT_FLAG__Wimplicit_fallthrough_0 failed with the following output:
Change Dir: /home/kylin/Paddle/build/CMakeFiles/CMakeTmp

Run Build Command(s):/usr/bin/make cmTC_c866a/fast && /usr/bin/make  -f CMakeFiles/cmTC_c866a.dir/build.make CMakeFiles/cmTC_c866a.dir/build
make[1]: Entering directory '/home/kylin/Paddle/build/CMakeFiles/CMakeTmp'
Building CXX object CMakeFiles/cmTC_c866a.dir/src.cxx.o
/usr/bin/c++    -Wno-error=deprecated-declarations -Wno-deprecated-declarations -std=c++14 -fPIC -fno-omit-frame-pointer -Werror -Wall -Wextra -Wnon-virtual-dtor -Wdelete-non-virtual-dtor -Wno-unused-parameter -Wno-unused-function -Wno-error=literal-suffix -Wno-error=unused-local-typedefs -DCXX_COMPILER_SUPPORT_FLAG__Wimplicit_fallthrough_0   -Wimplicit-fallthrough=0 -o CMakeFiles/cmTC_c866a.dir/src.cxx.o -c /home/kylin/Paddle/build/CMakeFiles/CMakeTmp/src.cxx
c++: error: unrecognized command line option '-Wimplicit-fallthrough=0'
CMakeFiles/cmTC_c866a.dir/build.make:68: recipe for target 'CMakeFiles/cmTC_c866a.dir/src.cxx.o' failed
make[1]: *** [CMakeFiles/cmTC_c866a.dir/src.cxx.o] Error 1
make[1]: Leaving directory '/home/kylin/Paddle/build/CMakeFiles/CMakeTmp'
Makefile:124: recipe for target 'cmTC_c866a/fast' failed
make: *** [cmTC_c866a/fast] Error 2

**Comment by hong19860320** [comment]
如果希望进行部署，建议使用Paddle Lite，可以直接使用 for armlinux armv8的 Paddle Lite 预编译库  https://paddle-lite.readthedocs.io/zh/latest/quick_start/release_lib.html

Paddle Lite repo: https://github.com/PaddlePaddle/Paddle-Lite
Paddle Lite Demo repo: https://github.com/PaddlePaddle/Paddle-Lite-Demo/tree/master/PaddleLite-armlinux-demo/image_classification_demo

**Comment by leiqing1** [comment]
RK3399使用Paddle Lite部署哈。https://paddle-lite.readthedocs.io/zh/release-v2.10_a/performance/benchmark.html#fp32 该链接下有关于RK3399的benchmark，可以作为参考。

**Comment by zhangting2020** [comment]
如果没有新的问题，我们将关闭issue。
