### ISSUE TITLE
动态转静态中出现数据未初始情况

### ISSUE THREAD

**Issue by Louis8582** [PaddlePaddle/Paddle#37609]
操作需求是在模型前面透过 paddle 加上 resize, normalize 等 transform 动作，并且导出成静态模型，在 paddlepaddle 2.1.3 的环境下针对 object detection 的输入(dic) 遇过初始化问题，原先代码如下:
x['image'] = x['image'].astype(paddle.float32)
系统汇报类似于找不到 x['image']的错误，我想应该是无法针对指定好记忆体空间的参数做变化，因此透过重新建构另一個空间就可解决，程式码如下:
outs = {}
outs['image'] = x['image'].astype(paddle.float32)
outs['im_shape'] = x['im_shape']
outs['scale_factor'] = x['scale_factor']

但问题就在于 paddlepaddle-gpu 2.2.0 下这个问题我无法解决，错误资讯如下:
 InvalidArgumentError: The Tensor in the assign Op's Input Variable X(i_0) is not initialized.
  [Hint: Expected t->IsInitialized() == true, but received t->IsInitialized():0 != true:1.] (at ..\paddle\fluid\framework\operator.cc:1594)
  [operator < assign > error]

如果有更好的将 transform 包入静态模型的方式也请告诉我，我目的就在于想要在 infer 下的基础 transform(resize padding normalize)等操作，能在导出的模型中一并交由GPU处理

**Comment by zhangting2020** [comment]
您好，请问是使用paddle.jit.to_static接口进行动转静的过程中，发现assign API报的这个错误吗？另外方便提供下一个最小可复现代码，帮您排查下使用方式有没有问题

**Comment by Louis8582** [comment]
我是在 paddlex 里面做 export_inference_model 遇到这个问题，但我看他底层也是做 jit.to_static 所以应该是一致的，报的错误如下。
![{E86EFB11-E974-4ED0-B9CD-90A82EB50C26} png](https://user-images.githubusercontent.com/23739360/143830063-b6c4764a-ff31-48bb-a5e8-ca1c30771158.jpg)

可复制我想你就如下操作应该就会遇到，只有针对object detection 或 instance 这种输入为字典的模型会有问题，导出的静态模型在实际运作时就会显示出上面截图的错误，或者你可以在转成program去执行有一样的问题。
```python
import paddlex as pdx
class NewNet(paddle.nn.Layer):
    def __init__(self, net):
        super().__init__()
        self.net = net
    def forward(self, x):
        out = {}
        out['image'] = x['image'].astype(paddle.float32)
        out['im_shape'] = x['im_shape']
        out['scale_factor'] = x['scale_factor']
        
        outs = self.net(out)
        return outs
model = pdx.load_model(model_path)
model.net = NewNet(model.net)
model._export_inference_model()
```

**Comment by zhangting2020** [comment]
我查看了下_export_inference_model的源码，PaddleX应该只支持给网络1个输入tensor，接口如下，通过image_shape参数指定网络输入tensor的shape。
`_export_inference_model(self, save_dir, image_shape=None)`

你的写法里：
- x['image']是网络输入tensor
- x['im_shape']是什么类型呢，是list？
- x['scale_factor']是tensor还是数值类型比如float？

先确认下你的使用是否正确呢？

**Comment by Louis8582** [comment]
我相信是没有错误的，因为我转换出来的不管在python 或者 C++都能使用。您可以往下一层去看，往下是呼叫 _get_test_inputs 来完成建构模型所需输入，我上面提供是已经转换完的所需输入，你只看到 Paddlex 层级是不够的。当然前提你可以假定model_path使固定的

**Comment by FlyingQianMM** [comment]
@Louis8582 您好，导出模型时在网络中插入normalize/resize等op，可以参考PaddleDetection目前的代码实现。目前PaddleDetection在导出时指定fuse_normalize即可：https://github.com/PaddlePaddle/PaddleDetection/blob/3167ecb6c58bf94122d5c5a4b65f28d0c6e73a40/configs/keypoint/tiny_pose/README.md
