### ISSUE TITLE
What is the mathematical formula format in operator's comments?

### ISSUE THREAD

**Issue by qingqing01** [PaddlePaddle/Paddle#3763]
Whether the doc comments will be converted to MarkDown? Should we use the mathematical formula format similar with Latex formula？

**Comment by reyoung** [comment]
> Whether the doc comments will be converted to MarkDown? Should we use the mathematical formula format similar with Latex formula？

I am not sure now. The easiest way is using Sphinx to generate documentation. However, it could be easily customized.

We could compile our comments to latex or markdown. So, I think for equations, just use Latex style.
