### ISSUE TITLE
import paddle失败

### ISSUE THREAD

**Issue by xuxuxuzy** [PaddlePaddle/Paddle#37640]
![image](https://user-images.githubusercontent.com/67948611/143684093-2096dd5f-ec14-48b5-a19f-c9c271ca1cc2.png)

**Comment by danleifeng** [comment]
请问你在什么环境下安装的什么版本的paddle whl包呢？可以先根据文档自查一下:
https://www.paddlepaddle.org.cn/install/quick?docurl=/documentation/docs/zh/develop/install/pip/windows-pip.html
，还遇到什么问题欢迎反馈。
