### ISSUE TITLE
[论文复现]paddle索引操作有点慢

### ISSUE THREAD

**Issue by jiaohuix** [PaddlePaddle/Paddle#37651]
- 标题：paddle索引操作慢，影响训练
- 版本、环境信息：
    1）PaddlePaddle版本：2.2.0
    2）CPU：
    3）GPU：3060，CUDA 11.1
    4）系统环境：win19，Python 3.6
 注：您可以运行test_slice.py运行得到torch、paddle、numpy的索引速度
- 模型信息
    1）模型名称 recurrent attention mdoel
    2）使用数据集名称 mnist

- 问题描述：改模型需要按照start和end 的位置对batch的图片进行截取patch，使用的是for循环对每张图片截取。目前看paddle的索引比其他的要慢，是不是我使用错了，或者有没有其他的操作可以完成这个op？谢谢
[test_slice.zip](https://github.com/PaddlePaddle/Paddle/files/7615632/test_slice.zip)
。

**Comment by zyfncg** [comment]
目前PaddlePaddle的索引切片相比于Pytorch和Numpy性能确实要稍低一些，但是常规的索引操作不会出现特别大的性能差异，我们对测试脚本做了简单的调试分析，初步的结果如下图所示：
![image](https://user-images.githubusercontent.com/13048366/143824374-fde09f1e-e4d5-489f-a92d-8410393d8f1e.png)

![image](https://user-images.githubusercontent.com/13048366/143824442-065ac9fb-4bdf-4d6a-a795-6ffc83670bb4.png)

图中红框里索引内部的几个tensor索引对性能影响比较大，如果不是必需的话建议这里的内部切片不用tensor去索引

关于索引性能优化的相关工作我们目前正在进行中，如果有遇到类似的索引性能问题欢迎反馈！

**Comment by jiaohuix** [comment]
意思是使用paddle.slice么？还有我训练用numpy，静态图用paddle的切片可以么？



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年11月29日(星期一) 下午3:44
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [PaddlePaddle/Paddle] [论文复现]paddle索引操作有点慢 (Issue #37651)





 
目前PaddlePaddle的索引切片相比于Pytorch和Numpy性能确实要稍低一些，但是常规的索引操作不会出现特别大的性能差异，我们对测试脚本做了简单的调试分析，初步的结果如下图所示：
 
 

 
图中红框里索引内部的几个tensor索引对性能影响比较大，如果不是必需的话建议这里的内部切片不用tensor去索引
 
关于索引性能优化的相关工作我们目前正在进行中，如果有遇到类似的索引性能问题欢迎反馈！
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by zyfncg** [comment]
上面的例子如果使用paddle.slice可能性能上会比原来要好一些，可以实验对比一下
表示下标信息的索引变量目前可以使用Numpy，动静态图是一样的

**Comment by jiaohuix** [comment]
![1638173821(1)](https://user-images.githubusercontent.com/68314259/143831605-b2c7c93d-f00c-494e-a6d2-6c6319fc026f.jpg)
这是啥原因呀

**Comment by zyfncg** [comment]
看上去像是动转静的时候数据有问题，如果动态图代码运行没问题的话可以再提交一个issue咨询一下相关的同学

**Comment by jiaohuix** [comment]
大佬你测的速度差不多，我训练时，paddle速度是250steps/s，torch的是900steps/s,然后用numpy替换了paddle索引后速度是1200steps/s。
paddle:
![1](https://user-images.githubusercontent.com/68314259/144165765-b29c4df5-ae12-477d-9ca8-a90386b0de08.png)
torch:
![2](https://user-images.githubusercontent.com/68314259/144165770-ebcccc57-a0bb-4915-873d-d87e5dc9633a.png)

numpy:
![3](https://user-images.githubusercontent.com/68314259/144165776-ddc0cc94-d2c2-4369-96dc-57561d89bc20.png)
后面我试了masked_select的，见附件，不知道哪里写的不好，速度奇慢，只有三四十steps/s。有没有什么更高效的方式，同时能转成静态图（主要是能转换为静态图，masked_select的to_tensor似乎不支持）。谢谢大佬。
[masked_select.zip](https://github.com/PaddlePaddle/Paddle/files/7630515/masked_select.zip)

**Comment by zyfncg** [comment]
![image](https://user-images.githubusercontent.com/13048366/144167461-c0d06f32-651a-435c-8a24-ae4b04ddfeb8.png)
这里面的mask用numpy来替换tensor，应该会对性能提升有帮助。因为目前对tensor进行操作会涉及到框架底层Operator调度的开销，在部分场景下（如Tensor不需要计算反向梯度，不会出现GPU与CPU之间数据的频繁同步等）像切片索引这种计算量不大的操作直接用numpy会比较高效

`to_tensor`是动态图的API，如果要支持静态图可以试试用`paddle.assign`

**Comment by jiaohuix** [comment]
可我看教程上动转静说不支持numpy呀






------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年12月1日(星期三) 中午11:49
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [PaddlePaddle/Paddle] [论文复现]paddle索引操作有点慢 (Issue #37651)





 

 这里面的mask用numpy来替换tensor，应该会对性能提升有帮助。因为目前对tensor进行操作会涉及到框架底层Operator调度的开销，在部分场景下（如Tensor不需要计算反向梯度，不会出现GPU与CPU之间数据的频繁同步等）像切片索引这种计算量不大的操作直接用numpy会比较高效
 
to_tensor是动态图的API，如果要支持静态图可以试试用paddle.assign
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by zyfncg** [comment]
不能用numpy主要是两个原因：
  1. 用了numpy就不能求反向梯度 
  2. 静态图编译期只进行组网没有数据，使用numpy的话拿不到数据会报错
 
这里我理解是在做一些图片预处理操作，不涉及模型的组网和训练，所以不需要计算反向梯度，而且batch_size和img_size是固定的，应该也可以不使用tensor，直接用numpy来把mask生成出来。你可以先用numpy试试，需要保证在numpy处理之前没有经过任何tensor的操作，比如像`paddle.randint`这样的tensor操作可以用numpy里的随机数生成代替

**Comment by jiaohuix** [comment]
额，这个模型会根据上一个时刻输出位置信息，截取小patch，然后再计算下一个时刻位置，就一边训练一边获取输入，不好保证numpy之前没有tensor操作呀，这模型确实有部分是不能求梯度的，接下来我该咋整orz

**Comment by zyfncg** [comment]
上一时刻输出的位置信息是个Tensor还是普通的numpy变量？

**Comment by jiaohuix** [comment]
tensor，就是rnn每个cell输出的state，过个mlp就得到了位置l[bsz,2]




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年12月1日(星期三) 下午3:48
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [PaddlePaddle/Paddle] [论文复现]paddle索引操作有点慢 (Issue #37651)





 
上一时刻输出的位置信息是个Tensor还是普通的numpy变量？
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by zyfncg** [comment]
> tensor，就是rnn每个cell输出的state，过个mlp就得到了位置l[bsz,2]
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: ***@***.***&gt;; 发送时间: 2021年12月1日(星期三) 下午3:48 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; ***@***.***&gt;; 主题: Re: [PaddlePaddle/Paddle] [论文复现]paddle索引操作有点慢 (Issue #37651) 上一时刻输出的位置信息是个Tensor还是普通的numpy变量？ — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.

那这个情况就不太好处理了，看能不能想办法压缩一些tensor的操作吧，或者试试把`masked_select`用`slice`代替看有没有作用

**Comment by jiaohuix** [comment]
由于静态图一开始输入的[-1,1,28,28]进行维度推导，导致拿不到数据，然后不能对每张图片切个patch，然后用stack就会报元素数<0错误。



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年12月1日(星期三) 下午4:03
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [PaddlePaddle/Paddle] [论文复现]paddle索引操作有点慢 (Issue #37651)





  
tensor，就是rnn每个cell输出的state，过个mlp就得到了位置l[bsz,2]
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: @.&gt;; 发送时间: 2021年12月1日(星期三) 下午3:48 收件人: @.&gt;; 抄送: @.&gt;; @.&gt;; 主题: Re: [PaddlePaddle/Paddle] [论文复现]paddle索引操作有点慢 (Issue #37651) 上一时刻输出的位置信息是个Tensor还是普通的numpy变量？ — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.
  
那这个情况就不太好处理了，看能不能想办法压缩一些tensor的操作吧，或者试试把masked_select用slice代替看有没有作用
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by zyfncg** [comment]
> 由于静态图一开始输入的[-1,1,28,28]进行维度推导，导致拿不到数据，然后不能对每张图片切个patch，然后用stack就会报元素数<0错误。
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: ***@***.***&gt;; 发送时间: 2021年12月1日(星期三) 下午4:03 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; ***@***.***&gt;; 主题: Re: [PaddlePaddle/Paddle] [论文复现]paddle索引操作有点慢 (Issue #37651) tensor，就是rnn每个cell输出的state，过个mlp就得到了位置l[bsz,2] … ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: @.&gt;; 发送时间: 2021年12月1日(星期三) 下午3:48 收件人: @.&gt;; 抄送: @.&gt;; @.&gt;; 主题: Re: [PaddlePaddle/Paddle] [论文复现]paddle索引操作有点慢 (Issue #37651) 上一时刻输出的位置信息是个Tensor还是普通的numpy变量？ — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. 那这个情况就不太好处理了，看能不能想办法压缩一些tensor的操作吧，或者试试把masked_select用slice代替看有没有作用 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.

这确实是动态图转静态图的一个问题，我觉得这个情况可以简单整理一下再提个issue给负责动转静的同学，看他们有没有好的解决办法
关于性能问题可以试着用profile工具分析一下看主要的性能热点在哪，然后再尝试做进一步的优化 https://www.paddlepaddle.org.cn/documentation/docs/zh/1.8/advanced_guide/performance_improving/analysis_tools/cpu_profiling_cn.html

**Comment by jiaohuix** [comment]
好的，谢谢大佬，辛苦您了




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年12月1日(星期三) 下午4:22
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [PaddlePaddle/Paddle] [论文复现]paddle索引操作有点慢 (Issue #37651)





  
由于静态图一开始输入的[-1,1,28,28]进行维度推导，导致拿不到数据，然后不能对每张图片切个patch，然后用stack就会报元素数<0错误。
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: @.&gt;; 发送时间: 2021年12月1日(星期三) 下午4:03 收件人: @.&gt;; 抄送: @.&gt;; @.&gt;; 主题: Re: [PaddlePaddle/Paddle] [论文复现]paddle索引操作有点慢 (Issue #37651) tensor，就是rnn每个cell输出的state，过个mlp就得到了位置l[bsz,2] … ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: @.&gt;; 发送时间: 2021年12月1日(星期三) 下午3:48 收件人: @.&gt;; 抄送: @.&gt;; @.&gt;; 主题: Re: [PaddlePaddle/Paddle] [论文复现]paddle索引操作有点慢 (Issue #37651) 上一时刻输出的位置信息是个Tensor还是普通的numpy变量？ — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. 那这个情况就不太好处理了，看能不能想办法压缩一些tensor的操作吧，或者试试把masked_select用slice代替看有没有作用 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.
  
这确实是动态图转静态图的一个问题，我觉得这个情况可以简单整理一下再提个issue给负责动转静的同学，看他们有没有好的解决办法
 关于性能问题可以试着用profile工具分析一下看主要的性能热点在哪，然后再尝试做进一步的优化 https://www.paddlepaddle.org.cn/documentation/docs/zh/1.8/advanced_guide/performance_improving/analysis_tools/cpu_profiling_cn.html
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by zyfncg** [comment]
希望提供的建议能对您有所帮助，这里面有些问题和框架的机制有关，短时间内不太好解决，可能得想一些办法绕过，像动转静这样的问题还需要时间去完善优化，还望理解

**Comment by jiaohuix** [comment]
嗯嗯，好的谢谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年12月1日(星期三) 下午4:29
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [PaddlePaddle/Paddle] [论文复现]paddle索引操作有点慢 (Issue #37651)





 
希望提供的建议能对您有所帮助，这里面有些问题和框架的机制有关，短时间内不太好解决，可能得想一些办法绕过，像动转静这样的问题还需要时间去完善优化，还望理解
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
