### ISSUE TITLE
报名

### ISSUE THREAD

**Issue by wangxiansheng999** [PaddlePaddle/Paddle#37657]
【队名】：zzuyjs
【序号】：100
【论文】：RemBERT: Rethinking embedding coupling in pre-trained language models
【状态】：报名
【repo链接】：https://github.com/wangxiansheng999/RemBERT

**Comment by Ligoml** [comment]
参赛选手你好，论文复现赛报名请在这条 issue 下回复https://github.com/PaddlePaddle/Paddle/issues/37401
