### ISSUE TITLE
less_than API

### ISSUE THREAD

**Issue by gloria111** [PaddlePaddle/Paddle#37665]
- 标题：“Less_than 文档问题”，”paddle.less_than文档问题“
- 文档版本信息：请提供有问题的文档的版本号2.1；

#### 其他
在训练模型时前几十个iter通过该语句都正常，但之后突然报错。报错信息如下：

![捕获](https://user-images.githubusercontent.com/26295563/143837722-a30c8bd3-0b8e-4426-b34d-2c498a6d616d.PNG)

现在尝试输出两个tensor的具体数值:
tl:Tensor(shape=[27, 1, 2], dtype=float32, place=CUDAPlace(0), stop_gradient=True,
       [[[131.21775818, 446.62957764]],

        [[160.67518616, 446.62957764]],

        [[147.40077209, 446.62957764]],

        [[131.21775818, 446.62957764]],

        [[624.82775879, 446.62957764]],

        [[574.62475586, 446.62957764]],

        [[295.74221802, 446.62957764]],

        [[131.21775818, 446.62957764]],

        [[161.50518799, 446.62957764]],

        [[247.31710815, 446.62957764]],

        [[131.21775818, 446.62957764]],

        [[182.50750732, 446.62957764]],

        [[413.12548828, 446.62957764]],

        [[131.21775818, 446.62957764]],

        [[389.96243286, 446.62957764]],

        [[319.84362793, 446.62957764]],

        [[400.24752808, 446.62957764]],

        [[254.21910095, 446.62957764]],

        [[247.20599365, 446.62957764]],

        [[147.29374695, 446.62957764]],

        [[354.77337646, 446.62957764]],

        [[131.21775818, 446.62957764]],

        [[292.51962280, 446.62957764]],

        [[580.48962402, 446.62957764]],

        [[131.21775818, 446.62957764]],

        [[431.26330566, 446.62957764]],

        [[209.96731567, 446.62957764]]])
br:Tensor(shape=[27, 1, 2], dtype=float32, place=CUDAPlace(0), stop_gradient=True,
       [[[161.36201477, 75.48600769 ]],

        [[161.36201477, 89.55841827 ]],

        [[161.36201477, 492.03436279]],

        [[161.36201477, 492.03436279]],

        [[161.36201477, 337.11337280]],

        [[161.36201477, 336.23675537]],

        [[161.36201477, 305.10986328]],

        [[70.82853699 , 366.72158813]],

        [[161.36201477, 363.47430420]],

        [[161.36201477, 309.85113525]],

        [[111.96886444, 364.04229736]],

        [[161.36201477, 346.70706177]],

        [[161.36201477, 33.73429871 ]],

        [[141.51533508, 156.68611145]],

        [[161.36201477, 245.68356323]],

        [[161.36201477, 202.77760315]],

        [[161.36201477, 205.88905334]],

        [[161.36201477, 142.36354065]],

        [[161.36201477, 57.47765350 ]],

        [[161.36201477, 60.21869659 ]],

        [[161.36201477, 90.49363708 ]],

        [[60.02487564 , 163.08187866]],

        [[161.36201477, 270.73571777]],

        [[161.36201477, 335.31072998]],

        [[98.59703064 , 365.25228882]],

        [[161.36201477, 306.81378174]],

        [[161.36201477, 263.26574707]]])

**Comment by gloria111** [comment]
标题：“Operator logical_not 文档问题”，”paddle.logical_not文档问题“
偶尔新出现问题如下：
![image](https://user-images.githubusercontent.com/26295563/143860960-f5986c3b-2c8f-4ebd-98c1-505589bacea2.png)

**Comment by yeliang2258** [comment]
用户你好，请提供具体可复现的python脚本，便于我这边快速解决问题，谢谢！

**Comment by gloria111** [comment]
你好，感谢你愿意帮我解决这个问题，具体代码链接已经通过邮件发给你。希望没有什么漏掉的，如果代码有问题请及时和我联系。

**Comment by yeliang2258** [comment]
请问发送的邮箱是？我没有收到哦

**Comment by gloria111** [comment]
没收到吗？可以看下这个：https://github.com/gloria111/YOLOX_paddle

**Comment by yeliang2258** [comment]
你上面的数据我测试是没有问题的，你还是发一个可以复现问题的python脚本给我吧，我的邮箱1047690002@qq.com
