### ISSUE TITLE
CUDA random op 集体报错

### ISSUE THREAD

**Issue by gsq7474741** [PaddlePaddle/Paddle#37663]
- 标题：CUDA random op 集体报错
- 版本、环境信息：
    1）PaddlePaddle版本：https://github.com/PaddlePaddle/Paddle/pull/37024
    2）CPU：PR-CI-Windows环境
    3）GPU：PR-CI-Windows环境
    4）系统环境：PR-CI-Windows环境
- 训练信息
    1）PR-CI-Windows环境
- 复现信息：PR-CI-Windows环境，cuda的uniform_random gaussian_random op如图报错，[日志链接](https://xly.bce.baidu.com/paddlepaddle/paddle/newipipe/detail/4154107/job/9572187)
- 
- <img width="826" alt="image" src="https://user-images.githubusercontent.com/38883252/143834122-7ecd5e82-88da-40ec-a382-ee9797facf89.png">

**Comment by Thunderbrook** [comment]
CI环境已修复
