### ISSUE TITLE
关于AVX算子的版本检测建议

### ISSUE THREAD

**Issue by Darki-luo** [PaddlePaddle/Paddle#37677]
之前反馈了一个关于noavx的paddlepaddle-gpu安装问题，已经得到解决，在反馈这个问题的过程中，我发现paddlepaddle gpu版本在2.0.2的版本对avx算子的检测是waring，但之后的版本一律都是报错error，需要单独使用pip安装noavx的版本，这个能优化一下吗？
——————————————————————————————————————————————————
conda install paddlepaddle-gpu=2.0.2 的运行是正常的,avx算子检测就是warning：
Python 3.8.5 (default, Sep  4 2020, 07:30:14)
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import paddle
WARNING: AVX is not support on your machine. Hence, no_avx core will be imported, It has much worse preformance than avx core.
/home/user309/miniconda3/lib/python3.8/site-packages/paddle/fluid/layers/utils.py:26: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  def convert_to_list(value, n, name, dtype=np.int):
>>> paddle.__version__
'2.0.2'

————————————————————————————————
现在2.2.0 用conda直接装就会报错：
Python 3.8.5 (default, Sep  4 2020, 07:30:14)
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import paddle
Error: Your machine doesn't support AVX, but the installed PaddlePaddle is avx core, you should reinstall paddlepaddle with no-avx core.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/user309/miniconda3/lib/python3.8/site-packages/paddle/__init__.py", line 25, in <module>
    from .fluid import monkey_patch_variable
  File "/home/user309/miniconda3/lib/python3.8/site-packages/paddle/fluid/__init__.py", line 36, in <module>
    from . import framework
  File "/home/user309/miniconda3/lib/python3.8/site-packages/paddle/fluid/framework.py", line 37, in <module>
    from . import core
  File "/home/user309/miniconda3/lib/python3.8/site-packages/paddle/fluid/core.py", line 357, in <module>
    raise e
  File "/home/user309/miniconda3/lib/python3.8/site-packages/paddle/fluid/core.py", line 309, in <module>
    from .core_noavx import *
ModuleNotFoundError: No module named 'paddle.fluid.core_noavx'
>>>

_Originally posted by @pangyoki in https://github.com/PaddlePaddle/Paddle/issues/37443#issuecomment-981400745_

**Comment by pangyoki** [comment]
你好，请问使用的是linux版本的paddle吗？

第一种情况，只报warning的原因是，你装的包是支持noavx的，所以只是提示noavx性能可能比较差。
第二种情况，报error的原因是，你装的包不支持noavx，但是机器只支持noavx，所以直接报错了。

确实在版本更新过程中，以前版本的linux包avx和noavx是合并成一个包的，所以以前的包支持noavx。但是因为包大小的限制，在更新的版本中，avx和noavx的包分开成了不同的包，所以你需要确定装的是不是noavx的包。

有问题可以再反馈，谢谢！

**Comment by Darki-luo** [comment]
> 你好，请问使用的是linux版本的paddle吗？
> 
> 第一种情况，只报warning的原因是，你装的包是支持noavx的，所以只是提示noavx性能可能比较差。 第二种情况，报error的原因是，你装的包不支持noavx，但是机器只支持noavx，所以直接报错了。
> 
> 确实在版本更新过程中，以前版本的linux包avx和noavx是合并成一个包的，所以以前的包支持noavx。但是因为包大小的限制，在更新的版本中，avx和noavx的包分开成了不同的包，所以你需要确定装的是不是noavx的包。
> 
> 有问题可以再反馈，谢谢！

是的 检测环境都是ubuntu18.04,cuda10.2 cudnn7.6 conda 配置的环境ptrhon=3.8.5 都是使用conda命令安装的，机器只支持noavx，如果是安装包大小限制的话可以理解，但是希望条件允许的情况尽量打包成一个吧，方便一点

**Comment by pangyoki** [comment]
> > 你好，请问使用的是linux版本的paddle吗？
> > 第一种情况，只报warning的原因是，你装的包是支持noavx的，所以只是提示noavx性能可能比较差。 第二种情况，报error的原因是，你装的包不支持noavx，但是机器只支持noavx，所以直接报错了。
> > 确实在版本更新过程中，以前版本的linux包avx和noavx是合并成一个包的，所以以前的包支持noavx。但是因为包大小的限制，在更新的版本中，avx和noavx的包分开成了不同的包，所以你需要确定装的是不是noavx的包。
> > 有问题可以再反馈，谢谢！
> 
> 是的 检测环境都是ubuntu18.04,cuda10.2 cudnn7.6 conda 配置的环境ptrhon=3.8.5 都是使用conda命令安装的，机器只支持noavx，如果是安装包大小限制的话可以理解，但是希望条件允许的情况尽量打包成一个吧，方便一点

好的，感谢反馈，我们正在开展缩小安装包大小的工作，后续也会再评估合并avx和noavx的需求。

**Comment by Gmgge** [comment]
@pangyoki 你好，如果自行编译包含avx和noavx的linux包应该如何设置呢？尝试了一些方法与建议，但是没有成功。
