### ISSUE TITLE
使用paddleclas中的PPLCNet模型计算backward时出现报错弹窗

### ISSUE THREAD

**Issue by qiuming-93** [PaddlePaddle/Paddle#37671]
- 标题：使用paddleclas中的PPLCNet模型计算backward时出现报错弹窗
- 版本、环境信息：
    1）PaddlePaddle版本：paddlepaddle-2.1.0,paddleclas-2.3
    2）CPU：intel i5-7500
    4）系统环境：win10，Python3.6

背景：
尝试基于paddleclas中的PPLCNet模型实现grad-cam展示特征热力图
在推理之前将模型的BatchNorm层的training属性设置为False，其它层不动，
然后在推理时参考https://aistudio.baidu.com/aistudio/projectdetail/3145483?forkThirdPart=1中的实现方式计算grap-cam，
推理结果与正常推理结果一致，但是在backward时报错0x00007FFC4821F5CB指令引用了0x0000000000000008内存，该内存不能为read。
如果不修改BatchNorm层的training属性设置为False，那么backward可以正常执行，但是推理的结果不对，原因应该是BN层在训练与推理时的计算方式不同导致

**Comment by jiangjiajun** [comment]
Hi，你好，BatchNorm确认是训练(training为True)和推理(training为False）不同。

当前如果想在训练过程中固定BatchNorm，可参考PaddleDetection中类似实现，在训练过程中不更新alpha和beta参数  https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.3/ppdet/modeling/ops.py#L75

**Comment by qiuming-93** [comment]
> Hi，你好，BatchNorm确认是训练(training为True)和推理(training为False）不同。
> 
> 当前如果想在训练过程中固定BatchNorm，可参考PaddleDetection中类似实现，在训练过程中不更新alpha和beta参数 https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.3/ppdet/modeling/ops.py#L75

freeze_norm参数实现的只是不更新alpha和beta参数吗，计算过程呢？还是使用该批次数据的均值方差进行计算吗？还是使用保存的均值方差进行计算

**Comment by jiangjiajun** [comment]
如果想固定均值和方差，在batch_norm中将use_global_stats设为True
