### ISSUE TITLE
LSTM bias_hh_attr=False 半精度下报错

### ISSUE THREAD

**Issue by liehu232** [PaddlePaddle/Paddle#37686]
LSTM bias_hh_attr=False 半精度下报错，禁用半精度正常
RuntimeError: (NotFound) Operator fill_constant_batch_size_like does not have kernel for data_type[::paddle::platform::float16]:data_layout[ANY_LAYOUT]:place[CUDAPlace(0)]:library_type[PLAIN].
  [Hint: Expected kernel_iter != kernels.end(), but received kernel_iter == kernels.end().] (at /paddle/paddle/fluid/imperative/prepared_operator.cc:159)
  [operator < fill_constant_batch_size_like > error]

**Comment by Thunderbrook** [comment]
fill_constant_batch_size_like暂时不支持fp16
