### ISSUE TITLE
报名

### ISSUE THREAD

**Issue by Darling-945** [PaddlePaddle/Paddle#37682]
【队名】：DearPuff
【序号】：22
【论文】：YOLOX: Exceeding YOLO Series in 2021
【状态】：报名
【repo链接】：https://github.com/Darling-945/paddle-yolox_repo

**Comment by Ligoml** [comment]
参赛选手你好，论文复现赛报名请在这条 issue 下回复https://github.com/PaddlePaddle/Paddle/issues/37401
