### ISSUE TITLE
【论文复现】slice操作截取patch，动态图速度较慢，静态图会报错

### ISSUE THREAD

**Issue by jiaohuix** [PaddlePaddle/Paddle#37695]
- 版本、环境信息：
    1）PaddlePaddle版本：2.2.0
    2）CPU：i5 10400f
    3）GPU：3060 cuda11.1
    4）系统环境：win10,python3.6.8

- 模型信息
    1）模型名称 recurrent attention mdoel
    2）使用数据集名称 mnsit
    3 ) aistudio地址（slice速度对比见6总结）：https://aistudio.baidu.com/aistudio/projectdetail/2884954
- 复现信息：您可以运行test_extrach后分别查看动态图前向，动转静，和静态图前向。
- 问题描述：模型需要根据输出的坐标信息l[bsz,2]和patch_size=8，从输入x[bsz,1,28,28]图片中截取[bsz,1,8,8]的patch，源码使用for对bsz做循环，每次截取一个patch，再做stack。然后动转静的时候报错：< tensor_array_to_tensor>Expected n > 0, but received n:0 <= 0:0. 我发现静态图bsz=-1,因此没走for，然后stack元素为0，导致报错，见test/test_extract.py。我的问题这个操作有没有更好的操作能批量完成，否则动转静完成不了，后面tipc也完成不了。（我后面试了masked_select,再test/masked_select.py，把x转为[bsz,1,784]，然后生成mask[bsz,1,784],用masked_select，动态图能运行，速度更慢了，用numpy1200steps/s,paddle slice 250steps/s,paddle masked_select 30steps/s），而静态图直接保存不了了。麻烦大佬帮我看一下，谢谢。
![LP14GCGKM7M7CG{6D{LP6{O](https://user-images.githubusercontent.com/68314259/143983289-606c56e8-db1d-4b81-8e6c-0db90215cdb7.png)
![W}81U1 IU}LRQ%B73L{CFAX](https://user-images.githubusercontent.

com/68314259/143983329-a66eb52d-6aa3-47a3-8172-47a6f88644f9.png)
[test.zip](https://github.com/PaddlePaddle/Paddle/files/7622780/test.zip)

**Comment by huangjun12** [comment]
静态图保存不了的报错方便贴一下吗

**Comment by jiaohuix** [comment]
这是用了masked_select的
![GA1I3Y$)VVOH6BH%1CLVU L](https://user-images.githubusercontent.com/68314259/144063891-97921152-8ed5-455a-9224-7fbee177dfa1.png)

**Comment by MiuGod0126** [comment]
![Uploading 8]HQEG}W9A_NOKVTAKHH_LG.png…]()

**Comment by jiaohuix** [comment]
等了半天抱内存溢出了qaq
![QMZJ850N@QFFXISPCBWDJZL](https://user-images.githubusercontent.com/68314259/144072441-2e2d2110-ce8f-4bf9-b4fd-19cc1c7de82f.png)

**Comment by huangjun12** [comment]
试一下paddle2.1.0版本呢

**Comment by Aurelius84** [comment]
修改为如下试下：
```python
b = paddle.shape(x)[0]
 _,c,h,w=x.shape
```

因为 x.shape 返回的是原生的python list,  静态图下 b = -1， 则for循环将不会被执行。如果使用`b = paddle.shape(x)[0]`，此时b 是一个静态图Tensor变量，会自动转化为静态图下 while_loop

**Comment by jiaohuix** [comment]
试过了，这个可以。除此之外静态图还有个问题，normal用了转不了静态图：
![image](https://user-images.githubusercontent.com/68314259/144536798-cbaa2ce4-6b63-4883-8bd1-da7f9dd8ae64.png)

**Comment by Aurelius84** [comment]
看了下 Normal() 的实现，动态图下 block参数可以为None，但静态图下调用此接口似乎需要指定block。

感谢您的反馈，我们这边进一步确认下是否可以移除这个静态图需指定block参数的限制

**Comment by jiaohuix** [comment]
好的，我先看别的




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年12月3日(星期五) 下午2:19
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [PaddlePaddle/Paddle] 【论文复现】slice操作截取patch，动态图速度较慢，静态图会报错 (Issue #37695)





 
看了下 Normal() 的实现，动态图下 block参数可以为None，但静态图下调用此接口似乎需要指定block。
 
感谢您的反馈，我们这边进一步确认下是否可以移除这个静态图需指定block参数的限制
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Aurelius84** [comment]
block 的问题，我们已经提PR修复了：https://github.com/PaddlePaddle/Paddle/pull/37827

**Comment by jiaohuix** [comment]
好的，我看看
