### ISSUE TITLE
SegFormer 模型加载错误

### ISSUE THREAD

**Issue by yangL-H** [PaddlePaddle/Paddle#37690]
为使您的问题得到快速解决，在建立Issue前，请您先通过如下方式搜索是否有相似问题:【搜索issue关键字】【使用labels筛选】【官方文档】

如果您没有查询到相似问题，为快速解决您的提问，建立issue时请提供如下细节信息：
- 标题：简洁、精准描述您的问题，例如“最新预测库的API文档在哪儿 ”
- 版本、环境信息：
   #引入包
import os
from google.colab import drive
#挂载函数，挂载方法，挂载到目录，会有一个连接点进去，然后复制一串东西进去

!lsb_release -a
!uname -r
!nvcc -V
!which python
!python --version
!python -m pip --version
!python -c "import platform;print(platform.architecture()[0]);print(platform.machine())"
!python -m pip install paddlepaddle-gpu==2.1.3.post112 -f https://www.paddlepaddle.org.cn/whl/linux/mkl/avx/stable.html

No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.5 LTS
Release:	18.04
Codename:	bionic
5.4.104+
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2020 NVIDIA Corporation
Built on Mon_Oct_12_20:09:46_PDT_2020
Cuda compilation tools, release 11.1, V11.1.105
Build cuda_11.1.TC455_06.29190527_0
/usr/local/bin/python
Python 3.7.12
pip 21.1.3 from /usr/local/lib/python3.7/dist-packages/pip (python 3.7)
64bit
x86_64

- 复现信息：如为报错，请给出复现环境、复现步骤
- 问题描述：请详细描述您的问题，同步贴出报错信息、日志/代码关键片段

#构建模型
from paddleseg.models import SegFormer
model = SegFormer(num_classes=4,
         backbone=manager.BACKBONES['MixVisionTransformer_B1'](),   #报错位置
         embedding_dim=256,
         align_corners=False,
         pretrained=None)

AttributeError                            Traceback (most recent call last)
<ipython-input-20-bde479116b55> in <module>()
     99 from paddleseg.models import SegFormer
    100 model = SegFormer(num_classes=4,
--> 101          backbone=manager.BACKBONES['MixVisionTransformer_B1'](),
    102          embedding_dim=256,
    103          align_corners=False,

2 frames
/usr/local/lib/python3.7/dist-packages/paddleseg/models/backbones/mix_transformer.py in MixVisionTransformer_B1(**kwargs)
    522         drop_rate=0.0,
    523         drop_path_rate=0.1,
--> 524         **kwargs)
    525 
    526 

/usr/local/lib/python3.7/dist-packages/paddleseg/models/backbones/mix_transformer.py in __init__(self, img_size, patch_size, in_chans, num_classes, embed_dims, num_heads, mlp_ratios, qkv_bias, qk_scale, drop_rate, attn_drop_rate, drop_path_rate, norm_layer, depths, sr_ratios, pretrained)
    309         # transformer encoder
    310         dpr = [
--> 311             x.item() for x in paddle.linspace(0, drop_path_rate, sum(depths))
    312         ]  # stochastic depth decay rule
    313         cur = 0

/usr/local/lib/python3.7/dist-packages/paddleseg/models/backbones/mix_transformer.py in <listcomp>(.0)
    309         # transformer encoder
    310         dpr = [
--> 311             x.item() for x in paddle.linspace(0, drop_path_rate, sum(depths))
    312         ]  # stochastic depth decay rule
    313         cur = 0

AttributeError: 'Tensor' object has no attribute 'item'

**Comment by juncaipeng** [comment]
请问你使用的paddle版本是？
这里提了一个[PR](https://github.com/PaddlePaddle/PaddleSeg/pull/1579)尝试修复，跑完CI后会尽快合入，你也可以参考PR修改一下你机器上安装的源码，即是/usr/local/lib/python3.7/dist-packages/paddleseg/models/backbones/mix_transformer.py文件中的311行。
