### ISSUE TITLE
复现报名

### ISSUE THREAD

**Issue by lhjthp** [PaddlePaddle/Paddle#37692]
【队名】：我要发CVPR

【序号】：13

【论文】：CvT: Introducing Convolutions to Vision Transformers

【状态】：报名

【repo链接】：https://github.com/lhjthp/CVT

**Comment by Ligoml** [comment]
参赛选手你好，论文复现赛报名请在这条 issue 下回复https://github.com/PaddlePaddle/Paddle/issues/37401
