### ISSUE TITLE
paddle.nn.layer.conv在训练模式和推理模式下相同权重，参数，输入下输出结果不一致

### ISSUE THREAD

**Issue by qiuming-93** [PaddlePaddle/Paddle#37718]
- 标题：paddle.nn.layer.conv在训练模式和推理模式下相同权重，参数，输入下输出结果不一致
- 版本、环境信息：
     1）PaddlePaddle版本：paddlepaddle-2.1.0,paddleclas-2.3
     2）CPU：intel i5-7500
     4）系统环境：win10，Python3.6
 
在模型推理时设置所有层（包含该conv层）的training属性为false和设置为true时相同权重，参数，输入下输出结果不一致。
通过debug查看了输入和权重的均值都是一样的，
但是输出结果的均值在小数点第8位处出现不一致，导致模型最终输出的置信度相差1%-5%。

**Comment by yaoxuefeng6** [comment]
有最小可复现的代码吗 我们进一步排查下

**Comment by qiuming-93** [comment]
> 有最小可复现的代码吗 我们进一步排查下

我是在paddleDetection-develop套件中使用的ppyolov2的模型发现的，可以通过注释掉paddleDetection中的ppdet/engine/trainer.py中的predict函数中的 self.model.eval()这行代码再修改bn层使用预训练权重中的均值方差计算实现在训练模式下进行推理。
