### ISSUE TITLE
【论文复现】静态图f.embedding报错

### ISSUE THREAD

**Issue by renmada** [PaddlePaddle/Paddle#37721]
paddle2.20， cuda101
![image](https://user-images.githubusercontent.com/43545086/144044199-5059597d-a692-457c-b8fc-8f114404bd03.png)

padding_idx没有传参数，报错提示这个参数有问题

**Comment by wangzhen38** [comment]
目前看起来是reader文件和static_model不适配所致，请参考ncf作修改https://github.com/PaddlePaddle/PaddleRec/tree/release/2.2.0/models/recall/ncf
