### ISSUE TITLE
【论文复现】张量的bool索引和切片直接赋值问题

### ISSUE THREAD

**Issue by lx-cly** [PaddlePaddle/Paddle#37733]
- 版本、环境信息：
    1）PaddlePaddle版本：devlop
    3）系统环境：linux
    4）Python 3.8
    5）显存信息
- 问题描述：我想对bool索引后的tensor 再重新赋值，可是出现了困难，详情请看一下代码。
- 代码：
    import paddle
    data = paddle.to_tensor([[1.0, 2.0, 3.0, 4.0],
                     [5.0, 6.0, 7.0, 8.0],
                     [9.0, 10.0, 11.0, 12.0]])
    index = paddle.to_tensor([1,3,0,1])
    data[2][index > 0] *= 0 #索引后 这样赋值 不行
    print(data[2][index > 0]) # 输出还是原来的值 

    data[2,3] =  0 #这样切片赋值是 可以修改的
    data[2,index > 0] *= 0  #可这样 bool 索引后赋值 就会报错

- 报错：
IndexError: Valid index accept int or slice or ellipsis or list, but received [2, Tensor(shape=[4], dtype=bool, place=CUDAPlace(0), stop_gradient=True,[True , True , False, True ])]

-这些 在pytorch 上操作都是对的。

**Comment by zyfncg** [comment]
您好，目前PaddlePaddle中可以使用bool索引，但是暂时不支持bool和其他类型的索引同时使用，像`data[2, index > 0]`这样普通integer索引和bool索引同时使用会报错。这个问题我们正在解决中，但正式支持预计还需要一段时间。
另外`data[2][index > 0] = 0`这样的用法属于多级索引赋值，可以理解为`tmp = data[2]`,`tmp[index > 0] = 0`两个语句的执行，`tmp = data[2]`会先执行并返回一个`Tensor`，这时的`Tensor`已经有了自己的独立的内存，再执行`tmp[index > 0] = 0`时便无法修改到最初的`data`。

这里可以暂时先想一些方法绕过这里的问题，比如用`tmp = data[2]`,`tmp[index > 0] = 0`,`data[2] = tmp`这样的方式进行赋值操作

**Comment by skywalk163** [comment]
哦哦，多级索引的问题。实际上最简单的多级索引，比如selfscores[0][0] ,也是无法直接赋值的，因为也是两个语句的执行。
截止到2.2版本还是这样，不知道2.3版本有没有考虑。
```
import paddle
configbeam_size = 4
selfscores = paddle.full(shape=(configbeam_size, 1), fill_value=\
    -30, dtype=paddle.float32)
print(selfscores)
selfscores[0][0] = 0
print(selfscores)

输出：
Tensor(shape=[4, 1], dtype=float32, place=CPUPlace, stop_gradient=True,
       [[-30.],
        [-30.],
        [-30.],
        [-30.]])
Tensor(shape=[4, 1], dtype=float32, place=CPUPlace, stop_gradient=True,
       [[-30.],
        [-30.],
        [-30.],
        [-30.]])
```

**Comment by zyfncg** [comment]
由于2.3版本底层算子体系更新较大，稳妥起见切片索引模块在这一版中基本没有做太多的改动，预计在2.3之后的版本中将会对切片索引模块进行一次重要的重构和升级，如果有相关需求的也欢迎跟我们反馈~

**Comment by stunback** [comment]
我在复现论文时也发现了这个问题：
```
    a = paddle.to_tensor([[[-1, -1, -1],
                           [0, 0, 0],
                           [-2, -2, -2],
                           [-1.5, -1.5, -1.5],
                           [-2.2, -2.2, -2.2]],
                          [[0, 0, 0],
                           [0.5, 0.5, 0.2],
                           [0.2, 0.2, 0.2],
                           [0.7, 0.7, 0.7],
                           [1, 1, 1]]]).transpose([0, 2, 1])

    i = paddle.to_tensor([0, 1, 0, 1], paddle.int32)
    # print(a[i, :])
    # print(a[i.numpy(), :])
    # print(a[[0, 1, 0, 1], :])
    print(a.numpy()[i, :])
```
上面这段程序，注释掉的二维切片索引会报`Valid index accept int or slice or ellipsis or list, but received [Tensor(shape=[4], dtype=int32, place=CUDAPlace(0), stop_gradient=True, [0, 1, 0, 1]), 0].`，这应该不只是bool索引的问题，只要包含list的二维索引都会出现这个问题。

**Comment by Tongfengyu** [comment]
+1，我想对 paddle的 tensor 切片赋值，发现赋值后原来的值不会变化

**Comment by Tongfengyu** [comment]
我这边是三维张量赋值无效，加个for循环变二维张量，才可以赋值

**Comment by zyfncg** [comment]
> 我这边是三维张量赋值无效，加个for循环变二维张量，才可以赋值

这个有具体的代码示例吗？

**Comment by gongel** [comment]
> 我在复现论文时也发现了这个问题：
> 
> ```
>     a = paddle.to_tensor([[[-1, -1, -1],
>                            [0, 0, 0],
>                            [-2, -2, -2],
>                            [-1.5, -1.5, -1.5],
>                            [-2.2, -2.2, -2.2]],
>                           [[0, 0, 0],
>                            [0.5, 0.5, 0.2],
>                            [0.2, 0.2, 0.2],
>                            [0.7, 0.7, 0.7],
>                            [1, 1, 1]]]).transpose([0, 2, 1])
> 
>     i = paddle.to_tensor([0, 1, 0, 1], paddle.int32)
>     # print(a[i, :])
>     # print(a[i.numpy(), :])
>     # print(a[[0, 1, 0, 1], :])
>     print(a.numpy()[i, :])
> ```
> 
> 上面这段程序，注释掉的二维切片索引会报`Valid index accept int or slice or ellipsis or list, but received [Tensor(shape=[4], dtype=int32, place=CUDAPlace(0), stop_gradient=True, [0, 1, 0, 1]), 0].`，这应该不只是bool索引的问题，只要包含list的二维索引都会出现这个问题。

期待后续的版本支持二维list切片

**Comment by cotyyang** [comment]
> 您好，目前PaddlePaddle中可以使用bool索引，但是暂时不支持bool和其他类型的索引同时使用，像`data[2, index > 0]`这样普通integer索引和bool索引同时使用会报错。这个问题我们正在解决中，但正式支持预计还需要一段时间。 另外`data[2][index > 0] = 0`这样的用法属于多级索引赋值，可以理解为`tmp = data[2]`,`tmp[index > 0] = 0`两个语句的执行，`tmp = data[2]`会先执行并返回一个`Tensor`，这时的`Tensor`已经有了自己的独立的内存，再执行`tmp[index > 0] = 0`时便无法修改到最初的`data`。
> 
> 这里可以暂时先想一些方法绕过这里的问题，比如用`tmp = data[2]`,`tmp[index > 0] = 0`,`data[2] = tmp`这样的方式进行赋值操作

哇，找了半天，pytorch也是这个问题，多级索引复制无效，哭了
