### ISSUE TITLE
安卓加载多模型

### ISSUE THREAD

**Issue by xiaofeixuan** [PaddlePaddle/Paddle#37739]
使用demo是PaddleLite-android-demo/yolo_detection_demo  ，目标检测功能，目前demo里面是加载单个模型nb文件，现在是想实现加载多个nb模型文件。自己训练的模型再加上自带的模型文件怎么可以同时调用，去检测这两个模型里面存在的所有分类？？

**Comment by iclementine** [comment]
目标检测模型相关的问题，可以到 https://github.com/PaddlePaddle/PaddleDetection 中提问，会得到更确切的回复哦
