### ISSUE TITLE
C++ API使用示例 ResNet50模型

### ISSUE THREAD

**Issue by snoopy1316** [PaddlePaddle/Paddle#37743]
在使用c++预测API时使用Linux上的vcsode进行编译，出现paddle_infer没有config和createrpredictor成员

项目参照：
https://www.paddlepaddle.org.cn/tutorials/projectdetail/1550309#anchor-15
![image](https://user-images.githubusercontent.com/94336500/144164745-56e253bd-cb5c-4e76-a05d-4fe8f3712de5.png)

**Comment by iclementine** [comment]
编译的时候真的遇到了问题吗。你可以查看一下 paddle/fluid/inference/api/paddle_inference_api.h 头文件，里面都是有的。可能是 vscode 的 lint 有什么问题。

<img width="397" alt="图片" src="https://user-images.githubusercontent.com/16222986/144165887-4e36d9ad-ceba-4f08-ba6f-42e265ca643a.png">


<img width="663" alt="图片" src="https://user-images.githubusercontent.com/16222986/144165862-cd477cb5-d102-4558-a9e7-63cdd6ae7788.png">

**Comment by Shixiaowei02** [comment]
您好，应该是没有包括正确的头文件导致的问题
