### ISSUE TITLE
动转静保存模型时报错

### ISSUE THREAD

**Issue by ColaFei** [PaddlePaddle/Paddle#37769]
paddle 2.1
python 3.7
P.jit.save(model, args.output_path) 报错截图：
![image](https://user-images.githubusercontent.com/37499167/144237464-d544e997-4437-42b6-9850-f11cc06ee05f.png)

为使您的问题得到快速解决，在建立Issue前，请您先通过如下方式搜索是否有相似问题:【搜索issue关键字】【使用labels筛选】【官方文档】

建立issue时，为快速解决问题，请您根据使用情况给出如下信息：
- 标题：简洁、精准描述您的问题，例如“ssd 模型前置lstm报错  ”
- 版本、环境信息：
    1）PaddlePaddle版本：请提供PaddlePaddle版本号，例如1.1或CommitID
    2）CPU：请提供CPU型号，MKL/OpenBlas/MKLDNN/等数学库的使用情况
    3）GPU：请提供GPU型号，CUDA和CUDNN版本号
    4）系统环境：请说明系统类型、版本（例如Mac OS 10.14），Python版本
 注：您可以通过执行[summary_env.py](https://github.com/PaddlePaddle/Paddle/blob/develop/tools/summary_env.py)获取以上信息。
- 模型信息
    1）模型名称 2）使用数据集名称 3）使用算法名称 4）模型链接
- 复现信息：如为报错，请给出复现环境、复现步骤
- 问题描述：请详细描述您的问题，同步贴出报错信息、日志/代码关键片段

Thank you for contributing to PaddlePaddle.
Before submitting the issue, you could search issue in the github.Probably there was a similar issue submitted or resolved before.
If there is no solution,please make sure that this is a issue of models including the following details:
**System information**
-PaddlePaddle version （eg.1.1）or CommitID
-CPU: including CPUMKL/OpenBlas/MKLDNN version
-GPU: including CUDA/CUDNN version
-OS Platform (eg.Mac OS 10.14)
-Python version
-Name of Models&Dataset/details of operator
Note: You can get most of the information by running [summary_env.py](https://github.com/PaddlePaddle/Paddle/blob/develop/tools/summary_env.py). 
**To Reproduce**
Steps to reproduce the behavior
**Describe your current behavior**
**Code to reproduce the issue**
**Other info / logs**

**Comment by huangjun12** [comment]
报错位置的代码方便贴一下吗

**Comment by ColaFei** [comment]
def main():

    model = ErnieModelForMultiLabel(args)
    state_dict = P.load(args.params_path)
    model.set_dict(state_dict)
    model.eval()

    model = P.jit.to_static(
        model,
        input_spec=[
            P.static.InputSpec(
                shape=[None, None], dtype="int64"),  # input_ids
            P.static.InputSpec(
                shape=[None, None], dtype="int64")  # segment_ids
        ])
    # Save in static graph model.
    P.jit.save(model, args.output_path)

**Comment by huangjun12** [comment]
`/tmp/tmp14t88o2i.py`里的50行前后哈

**Comment by iclementine** [comment]
这里要求 input_spec  是 Model 的 forward 方法的 tensor 输入，而且除了 tensor 之外的输入都需要有默认值。这个条件满足吗？

**Comment by Aurelius84** [comment]
模型中的 `if else` 分支里是否存在 return  string 类型变量的代码？
