### ISSUE TITLE
Unify Python and C++ InferShape for VarDesc and Tensor.

### ISSUE THREAD

**Issue by reyoung** [PaddlePaddle/Paddle#3776]
Since we want to separate compile phase and running phase in PaddlePaddle. We must give a proper way for operator developers to define a single C++ function and use it in both Python and C++.

For Python, `VarDesc`s are used. For C++, `Tensor`s are used. The inputs of them are different, but it should be implemented in same C++ function.

**Comment by jacquesqiao** [comment]
There will be several steps to solve this problem:

1. Add VarDesc proto message to describe Variable. https://github.com/PaddlePaddle/Paddle/pull/3835
2. Move InferShape to Op Maker class and make it a static function. Unify InferShape of compile time and runtime.
3. Expose Python API.
