### ISSUE TITLE
预测异常

### ISSUE THREAD

**Issue by BeyondYourself** [PaddlePaddle/Paddle#37793]
在linux的docker环境下，使用的paddle最新稳定版本，在预测服务的时候出现下面异常，这是什么原因，有大佬清楚吗，帮忙解释一下
![image](https://user-images.githubusercontent.com/12640462/144370129-63cc0e1a-3218-4179-87dd-c4a6fb4f174e.png)

**Comment by jiweibo** [comment]
您好，请问下这是自己封装的预测服务吗？能把Paddle相关的报错信息贴出来吗，目前看不到具体的报错

**Comment by BeyondYourself** [comment]
才用的paddleserving服务

**Comment by jiweibo** [comment]
> 才用的paddleserving服务

请问下可以在serving下帖个issue吗，目前log有限，看不出问题

**Comment by BeyondYourself** [comment]
好的，还是多谢

**Comment by BeyondYourself** [comment]
@jiweibo 
![image](https://user-images.githubusercontent.com/12640462/144975400-2cf70e82-8f4f-467e-bb11-f3bf7e7a7088.png)

这个错误是什么意思，可否解答一下

**Comment by jiweibo** [comment]
> @jiweibo ![image](https://user-images.githubusercontent.com/12640462/144975400-2cf70e82-8f4f-467e-bb11-f3bf7e7a7088.png)
> 
> 这个错误是什么意思，可否解答一下

看报错的意思是说，加载模型的时候，没有找到对应的权重文件，请问下模型是保存成预测格式的模型吗？
这里有一个关于模型格式的介绍哈
https://paddleinference.paddlepaddle.org.cn/introduction/training_to_deployment.html

**Comment by BeyondYourself** [comment]
> > @jiweibo ![image](https://user-images.githubusercontent.com/12640462/144975400-2cf70e82-8f4f-467e-bb11-f3bf7e7a7088.png)
> > 这个错误是什么意思，可否解答一下
> 
> 看报错的意思是说，加载模型的时候，没有找到对应的权重文件，请问下模型是保存成预测格式的模型吗？ 这里有一个关于模型格式的介绍哈 https://paddleinference.paddlepaddle.org.cn/introduction/training_to_deployment.html

是模型转换没有成功，生成个很大的core文件
