### ISSUE TITLE
如何实现使用两网络参数的加权和来更新网络，并且速度较快

### ISSUE THREAD

**Issue by shiningboy123** [PaddlePaddle/Paddle#3779]
使用paddle v1 api训练网络时，几个网络结构一样，每个batch需要用其中两个网络对应的参数加权和作为一个网络此次更新的结果。目前是将网络参数copy到numpy数组，做完计算再copy到网络，这种实现方式速度慢，不知道如何实现可以运行更快？

**Comment by guoshengCS** [comment]
应该可以不过numpy，参考下GAN的这个用法https://github.com/PaddlePaddle/Paddle/blob/develop/v1_api_demo/gan/gan_trainer.py#L50

**Comment by guoshengCS** [comment]
目前高层API好像确实没有这种计算的功能，但感觉慢应该是计算慢不是copy到numpy数组慢，这个可以再确认下。

**Comment by shiningboy123** [comment]
@guoshengCS 嗯嗯，修改底层或者写代码增加些功能都没关系，不知道有没有好的实现方式？

**Comment by guoshengCS** [comment]
其实我有个想法不知道可行不，可以试下把这些param作为input再用一个网络（进行需要的数值计算）forward一趟
