### ISSUE TITLE
tensor.sum() 对bool量list的结果与torch和numpy不一致

### ISSUE THREAD

**Issue by PeterJaq** [PaddlePaddle/Paddle#37794]
- 版本、环境信息
1）PaddlePaddle版本：请提供您的PaddlePaddle版本号，例如2.1
2）CPU/GPU：CUDA11
3）系统环境：Ubuntu 18.04 Nvidia-docker 
注：您可以通过执行[summary_env.py](https://github.com/PaddlePaddle/Paddle/blob/develop/tools/summary_env.py)获取以上信息。
- 复现信息：
问题：paddlepaddle tensor.sum() 对bool量list的结果与 torch和numpy不一致
复现 numpy：
![image](https://user-images.githubusercontent.com/15727924/144374541-abc5df5a-570b-4cc1-bbbf-323da95ca97d.png)
复现 pytorch:
![image](https://user-images.githubusercontent.com/15727924/144374625-d87fb8eb-e97b-4780-be7f-bc36b39e5fa8.png)
复现 paddlepaddle:
![image](https://user-images.githubusercontent.com/15727924/144374695-2236c199-be23-4b81-a2bb-a42e4d4f6fc2.png)
 如为报错，请给出复现环境、复现步骤

**Comment by huangjun12** [comment]
使用paddle 2.2.0，输出结果如下:

```txt
Tensor(shape=[1], dtype=int64, place=CUDAPlace(0), stop_gradient=True,
       [2])
```

可以更换一下paddle版本
