### ISSUE TITLE
报错：paddle.sin 函数并没有对应的梯度操作 

### ISSUE THREAD

**Issue by kft-upc** [PaddlePaddle/Paddle#37808]
在AIStUDIo中运行代码，paddle版本是2.2.0，运行环境是CPU，执行代码是：

inp = paddle.to_tensor([1], dtype='float32', stop_gradient=False)
y = paddle.sin(inp)
y_x = paddle.grad(y, inp, create_graph=True, retain_graph=True) 

报错：
 (NotFound) The Op sin_grad doesn't have any grad op. If you don't intend calculating higher order derivatives, please set `create_graph` to False.
  [Hint: double_grad_node should not be null.] (at /paddle/paddle/fluid/imperative/partial_grad_engine.cc:908)

**Comment by LDOUBLEV** [comment]
报错提示sin OP没有二阶梯度计算kernel
如果您只需要计算一阶梯度，可以设置create_graph=False
```
https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/grad_cn.html#grad
retain_graph (bool, 可选) - 是否保留计算梯度的前向图。*若值为True，则前向图会保留，用户可对同一张图求两次反向*。若值为False，则前向图会释放。默认值为None，表示值与 create_graph 相等。
```
