### ISSUE TITLE
关于train的event_handler

### ISSUE THREAD

**Issue by yifanfeng97** [PaddlePaddle/Paddle#3782]
在V2中，希望train的event_handler能提供更灵活数据处理接口，能让用户自己按自己的评判指标对训练结果进行处理，而不仅限于```event.pass_id, event.batch_id, event.cost, event.metrics```
比如我想打印出train的时候，每个样本的label和target。或者计算每个类别里面的accuracy，而不是总共的accuracy。

**Comment by gongweibao** [comment]
Since we upgrade to fluid, so I close it! Feel free to reopen it!
