### ISSUE TITLE
关于使用ernie

### ISSUE THREAD

**Issue by Fujiaoji** [PaddlePaddle/Paddle#37855]
当前一句话，已经用tokenizer变成下面的形式，那么在想用预训练的ernie 1.0 的时候，直接from pretrain('ernie 1.0), 然后在forward里输入ID， 输出的就是预训练对应的embedding了吗，已经封装好了是吗；
Tensor(shape=[3, 13], dtype=int64, place=CUDAPinnedPlace, stop_gradient=True)

**Comment by JZ-LIANG** [comment]
是的，数据预处理都是封装好dataloader 类里实现的， dataloader 输出的都是向量化的 tensor。可以参考https://www.paddlepaddle.org.cn/hubdetail?name=ernie&en_category=SemanticModel

具体tensor shape、dtype 和 place 等 还需要结合具体模型才能判断， 这个是模型侧问题，不是框架侧。 可以在https://github.com/PaddlePaddle/ERNIE 中找到具体模型判断或提问

**Comment by Fujiaoji** [comment]
ok, 多谢
