### ISSUE TITLE
TypeError: `value` should be `numpy.ndarray` or `LoDTensor`, but received <class 'paddle.fluid.framework.Variable'>.

### ISSUE THREAD

**Issue by theMLL** [PaddlePaddle/Paddle#37856]
使用    fluid.io.save_inference_model(dirname='./tcn_model', feeded_var_names=['img'],target_vars=[label], executor=exe) 对模型进行保存时，提示添加   paddle.enable_static()，  

之后报错 ：

TypeError: `value` should be `numpy.ndarray` or `LoDTensor`, but received <class 'paddle.fluid.framework.Variable'>.

**Comment by JZ-LIANG** [comment]
首先，这个api 实际静态图接口，只用使用静态图训练的模型才能使用。
静态图参考：
https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/static/save_inference_model_cn.html#save-inference-model
https://www.paddlepaddle.org.cn/documentation/docs/zh/faq/save_cn.html#savesave-inference-model
动态图参考：
https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/save_cn.html#save
