### ISSUE TITLE
中断训练程序，显存从来来没有有自动释放过，一直占用，kill 调进程也一样，真的是难受，每次都要注销

### ISSUE THREAD

**Issue by cqray1990** [PaddlePaddle/Paddle#37861]
为使您的问题得到快速解决，在建立Issues前，请您先通过如下方式搜索是否有相似问题:【搜索issue关键字】【使用labels筛选】【官方文档】

如果您没有查询到相似问题，为快速解决您的提问，建立issue时请提供如下细节信息：
- 标题：简洁、精准概括您的问题
- 版本、环境信息：
    1）PaddlePaddle版本：请提供您的PaddlePaddle版本号，例如1.1或CommitID
    2）CPU/GPU：如果您使用GPU训练，请提供GPU驱动版本、CUDA和cuDNN版本号
    3）系统环境：请您描述系统类型、版本，例如Mac OS 10.14
    4）Python版本号
    5）显存信息
 注：您可以通过执行[summary_env.py](https://github.com/PaddlePaddle/Paddle/blob/develop/tools/summary_env.py)获取以上信息。
- 复现信息：如为报错，请给出复现环境、复现步骤
- 问题描述：请详细描述您的问题，同步贴出报错信息、日志/代码关键片段

Thank you for contributing to PaddlePaddle.
Before submitting the issue, you could search issue in the github in case that there was a similar issue submitted or resolved before.
If there is no solution,please provide us with the following details :
**System information**
-PaddlePaddle version （eg.1.1）or CommitID
-CPU: including CPUMKL/OpenBlas/MKLDNN version
-GPU: including CUDA/cuDNN version
-OS Platform and Distribution(eg.Mac OS 10.14)
-Python version 
Note: You can get most of the information by running [summary_env.py](https://github.com/PaddlePaddle/Paddle/blob/develop/tools/summary_env.py). 
**To Reproduce**
Steps to reproduce the behavior
**Describe your current behavior**
**Code to reproduce the issue**
**Other info / logs**

**Comment by pangyoki** [comment]
请问你跑的啥模型？用的什么方法中断程序？

**Comment by cqray1990** [comment]
训练的paddleocr的，开始的时候直接ctr+c，然后发现不行，就找到python的进程 kill 掉还是不行，进程虽然kill掉了，但是现存还占着

**Comment by cqray1990** [comment]
@pangyoki ，pytorch多卡训练和单卡训练现存都不会一直占着阿

**Comment by pangyoki** [comment]
有可能是你的进程没删干净，nvidia-smi也可以看到占着卡的进程号，继续杀这个进程吧。

**Comment by linhandev** [comment]
killall -9 python 
一般好用
