### ISSUE TITLE
动转静报错

### ISSUE THREAD

**Issue by Fujiaoji** [PaddlePaddle/Paddle#37866]
Paddle version: 2.2.0
Paddle With CUDA: True
Python version: 3.7.10
CUDA version: 9.0.176
cuDNN version: None.None.None
Nvidia driver version: 418.39

动转静报错，用的是直接在save中保存的那种方法，没在forward加to static;
描述：可以正常训练一个epoch 并保存模型，但是到了第二epoch就开始出错；另外为啥会在backward报错呢。。。
INFO:root:Epoch 2 / 300:
Traceback (most recent call last):
  File "run.py", line 703, in <module>
    train(env)
  File "run.py", line 148, in train
    epoch_train(env, args, model, optimizer, train.loader, epoch, train_batch)
  File "/home/qu/rd/sunyibo/intern/jifujiao/ddparser_ernie/ddparser0/parser0/model.py", line 146, in epoch_train
    loss.backward()
  File "<decorator-gen-128>", line 2, in backward
  File "/home/map/tools/paddle_release_home/paddle_gpu220_py37_gcc82/lib/python3.7/site-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
    return wrapped_func(*args, **kwargs)
  File "/home/map/tools/paddle_release_home/paddle_gpu220_py37_gcc82/lib/python3.7/site-packages/paddle/fluid/framework.py", line 229, in __impl__
    return func(*args, **kwargs)
  File "/home/map/tools/paddle_release_home/paddle_gpu220_py37_gcc82/lib/python3.7/site-packages/paddle/fluid/dygraph/varbase_patch_methods.py", line 249, in backward
    framework._dygraph_tracer())
RuntimeError: (NotFound) Operator (sum) does not have kernel for data_type[bool]:data_layout[ANY_LAYOUT]:place[CUDAPlace(0)]:library_type[PLAIN].
  [Hint: Expected kernel_iter != kernels.end(), but received kernel_iter == kernels.end().] (at /paddle/paddle/fluid/framework/operator.cc:1296)
  [operator < sum > error]

其中epoch train与loss部分如下：
def epoch_train(env, args, model, optimizer, loader, epoch, train_batch):
    """Train in one epoch"""
    model.train()
    total_loss = 0
    pad_index = args.pad_index
    bos_index = args.bos_index
    eos_index = args.eos_index
    word_dict = env.WORD.vocab
    word2id_dict = {v: k for k, v in word_dict.items()}
    for batch, inputs in enumerate(loader(), start=1):
        model.clear_gradients()
        words, arcs, rels = inputs
        s_arc, s_rel, words = model(words)

        mask = layers.logical_and(
            layers.logical_and(words != pad_index, words != bos_index),
            words != eos_index,
        )

        loss = loss_function(s_arc, s_rel, arcs, rels, mask)
        loss.backward()

        optimizer.minimize(loss)
        total_loss += loss.numpy().item()
        if batch % 50 == 0:
            logging.info("epoch: {}, batch: {}/{}, batch_size: {}, loss: {:.4f}".format(
                epoch, batch, train_batch, len(words),
                loss.numpy().item()))
    total_loss /= train_batch

    return total_loss

def loss_function(s_arc, s_rel, arcs, rels, mask):
    arcs = nn.masked_select(arcs, mask)
    rels = nn.masked_select(rels, mask)

    s_arc = nn.masked_select(s_arc, mask)
    s_rel = nn.masked_select(s_rel, mask)
    s_rel = nn.index_sample(s_rel, layers.unsqueeze(arcs, 1))
    
    arc_loss = layers.cross_entropy(layers.softmax(s_arc), arcs)
    rel_loss = layers.cross_entropy(layers.softmax(s_rel), rels)

    loss = layers.reduce_mean(arc_loss + rel_loss)

    return loss

**Comment by Fujiaoji** [comment]
单纯拿了一个数据，只train是没有问题，加上dev就会出错了。。。是不能在train的时候加dev吗

**Comment by pangyoki** [comment]
你好，看报错，应该是`sum`这个op不支持`bool`类型导致报错。至于为什么是在backward里报错，因为动态图反向是自动构建的，可能跑前向网络没问题，跑反向op时才出问题。

麻烦使用`GLOG_v=4 python train.py`的形式打印日志，看下执行的op的情况，确定是哪个前向op出问题了，看下类型是否不对。

**Comment by pangyoki** [comment]
> 单纯拿了一个数据，只train是没有问题，加上dev就会出错了。。。是不能在train的时候加dev吗

dev里面加了什么逻辑？

**Comment by Fujiaoji** [comment]
不对，去掉dev也是会错，稍等我看下日志

**Comment by Fujiaoji** [comment]
还是报错，我没找到这个sum在哪里，决定直接转写静态图了，多谢

**Comment by Fujiaoji** [comment]
> 还是报错，我没找到这个sum在哪里，决定直接转写静态图了，多谢

哒哒哒，找到了！paddle好像对bool类型的有些些不一样，我把他转化成了int,多谢
