### ISSUE TITLE
如何实现对结果中的某几个通道进行反向传播

### ISSUE THREAD

**Issue by qiuming-93** [PaddlePaddle/Paddle#37875]
- 标题：如何实现对结果中的某几个通道进行反向传播
- 版本、环境信息：
    1）PaddlePaddle版本：paddlepaddle-cpu 2.1.0
    2）CPU/GPU：cpu
    4）Python3.7
    5）显存信息

最终输出结果为（b, c , h, w），想要实现对结果中的某几个通道进行反向传播，尝试过通过下标索引，类似（:, 0, : , :）这样，但是发现不管选择哪个通道进行反向传播的梯度都是一样的， 也尝试过构建index tensor，通过如下代码的方式，发现不同通道进行反向传播的梯度还是一样的，说明这两种方案其实都是完整输出结果反向传播的梯度，如何实现部分通道的反向传播的梯度
target_out_index = paddle.to_tensor(np.zeros(out.shape, dtype=np.float32))
target_out_index[:, 1, :, :] = 1
target_out = target_out_index * out

**Comment by pangyoki** [comment]
你好，可以尝试slice结束之后，使用`stop_gradient`属性控制slice出来的Tensor是否能够回传梯度。
例如，
```
slice_tensor = target_out_index[:, 1, :, :]
slice_tensor.stop_gradient = True   # slice_tensor部分不再回传梯度
```

**Comment by qiuming-93** [comment]
> 你好，可以尝试slice结束之后，使用`stop_gradient`属性控制slice出来的Tensor是否能够回传梯度。 例如，
> 
> ```
> slice_tensor = target_out_index[:, 1, :, :]
> slice_tensor.stop_gradient = True   # slice_tensor部分不再回传梯度
> ```

找到问题了，应该是backward之后使用对应层的梯度进行计算导致后续的bakward梯度不再变化

**Comment by qiuming-93** [comment]
复现代码：
x = paddle.to_tensor(np.zeros((2,3,4), dtype=np.float32)) + 1
    x.stop_gradient = False
    y = paddle.to_tensor(np.zeros((2,3,4), dtype=np.float32))
    y[:, 1, :] = 1
    z = x*y

    z[:, 2, :].backward(retain_graph=True)
    print(paddle.mean(x.grad))
    grad_map = x.grad
    grad = paddle.mean(paddle.to_tensor(grad_map), (2), keepdim=True)
    gradcam = paddle.sum(grad * x, axis=1)
    z.clear_grad()
    z[:,1,:].backward(retain_graph=True)
    print(paddle.mean(x.grad))

可以通过注释
 grad_map = x.grad
 grad = paddle.mean(paddle.to_tensor(grad_map), (2), keepdim=True)
 gradcam = paddle.sum(grad * x, axis=1)
这三行代码对比下控制台输出的结果
