### ISSUE TITLE
Paddle环境安装问题

### ISSUE THREAD

**Issue by lixiangMindSpore** [PaddlePaddle/Paddle#37874]
为使您的问题得到快速解决，在建立Issue前，请您先通过如下方式搜索是否有相似问题:【搜索issue关键字】【使用labels筛选】【官方文档】

建立issue时，为快速解决问题，请您根据使用情况给出如下信息：
- 标题：请包含关键词“安装错误”/“编译错误”，例如“Mac编译错误”
- 版本、环境信息：
    1）PaddlePaddle版本：2.2.0rc
    2）CPU：请提供CPU型号，MKL/OpenBlas/MKLDNN/等数学库的使用情况
    3）GPU：GeForce RTX 3090，CUDA和cuDNN如下所示
![image](https://user-images.githubusercontent.com/78945582/144794443-7255ffc0-f389-4d2f-a785-837fa67f1c67.png)
![image](https://user-images.githubusercontent.com/78945582/144794483-467566eb-1e2f-4178-b200-96ceddf00761.png)
![image](https://user-images.githubusercontent.com/78945582/144794528-9d5eba8f-10e5-4056-ae34-b08bac116c25.png)

    4）系统环境：请说明系统类型、版本（如Mac OS 10.14）、Python版本
注：Ubuntu 18.04  python=3.6
- 安装方式信息：
1）pip安装/docker安装
python -m pip install paddlepaddle-gpu==2.2.0.rc -f https://www.paddlepaddle.org.cn/whl/linux/mkl/avx/stable.html
2）本地编译：请提供cmake命令，编译命令
3）docker编译：请提供docker镜像，编译命令            
  特殊环境请注明：如离线安装等
- 复现信息：如为报错，请给出复现环境、复现步骤
- 问题描述：请详细描述您的问题，同步贴出报错信息、日志/代码关键片段
- 
![image](https://user-images.githubusercontent.com/78945582/144794675-9ca0aae7-8587-4cfe-a97d-363d61e78812.png)

Thank you for contributing to PaddlePaddle.
Before submitting the issue, you could search issue in Github in case that there was a similar issue submitted or resolved before.
If there is no solution,please make sure that this is an installation issue including the following details:
**System information**
-PaddlePaddle version （eg.1.1）or CommitID
-CPU: including CPUMKL/OpenBlas/MKLDNN version
-GPU: including CUDA/CUDNN version
-OS Platform (eg. Mac OS 10.14)
-Python version
- Install method: pip install/install with docker/build from source(without docker)/build within docker
- Other special cases that you think may be related to this problem, eg. offline install, special internet condition 
Note: You can get most of the information by running [summary_env.py](https://github.com/PaddlePaddle/Paddle/blob/develop/tools/summary_env.py).   

**To Reproduce**
Steps to reproduce the behavior
**Describe your current behavior**
**Code to reproduce the issue**
**Other info / logs**

**Comment by pangyoki** [comment]
看起来你环境里cuda是cuda10.1，但是安装的是cuda10.2的包？麻烦`nvcc -V`看下需要的cuda版本吧。
可使用`python -m pip install paddlepaddle-gpu==2.2.0.post101 -f https://www.paddlepaddle.org.cn/whl/linux/mkl/avx/stable.html`安装cuda10.1的包试试

**Comment by lixiangMindSpore** [comment]
> 看起来你环境里cuda是cuda10.1，但是安装的是cuda10.2的包？麻烦`nvcc -V`看下需要的cuda版本吧。 可使用`python -m pip install paddlepaddle-gpu==2.2.0.post101 -f https://www.paddlepaddle.org.cn/whl/linux/mkl/avx/stable.html`安装cuda10.1的包试试

这个也试过了，一样的错误

**Comment by pangyoki** [comment]
建议用docker安装试下吧，因为你的gcc版本太低也用不了paddle。
可以参考下这个文档：https://www.paddlepaddle.org.cn/documentation/docs/zh/install/docker/linux-docker.html

可以尝试下这两个镜像：
docker pull paddlepaddle/paddle:2.2.0-gpu-cuda10.2-cudnn7
docker pull paddlepaddle/paddle:2.2.0-gpu-cuda11.2-cudnn8

也有3090显卡没法用cuda10.x的可能。

**Comment by lixiangMindSpore** [comment]
> 建议用docker安装试下吧，因为你的gcc版本太低也用不了paddle。 可以参考下这个文档：https://www.paddlepaddle.org.cn/documentation/docs/zh/install/docker/linux-docker.html
> 
> 可以尝试下这两个镜像： docker pull paddlepaddle/paddle:2.2.0-gpu-cuda10.2-cudnn7 docker pull paddlepaddle/paddle:2.2.0-gpu-cuda11.2-cudnn8
> 
> 也有3090显卡没法用cuda10.x的可能。

我有一个2080显卡环境，gcc版本是6.5.0，这个能运行，但是3090显卡环境的gcc版本是7.5.0，按理说不应该是gcc版本的而原因吧？

**Comment by pangyoki** [comment]
> > 建议用docker安装试下吧，因为你的gcc版本太低也用不了paddle。 可以参考下这个文档：https://www.paddlepaddle.org.cn/documentation/docs/zh/install/docker/linux-docker.html
> > 可以尝试下这两个镜像： docker pull paddlepaddle/paddle:2.2.0-gpu-cuda10.2-cudnn7 docker pull paddlepaddle/paddle:2.2.0-gpu-cuda11.2-cudnn8
> > 也有3090显卡没法用cuda10.x的可能。
> 
> 我有一个2080显卡环境，gcc版本是6.5.0，这个能运行，但是3090显卡环境的gcc版本是7.5.0，按理说不应该是gcc版本的而原因吧？

嗯嗯，这个报错不是gcc版本引起的。我的意思是，即使你上面cuda的这个问题解决了，也还会遇到gcc版本太低的问题，需要再装gcc也比较麻烦。
最好先试下镜像能不能用，排除下CUDA环境的问题。
建议试下11.2的镜像。

**Comment by lixiangMindSpore** [comment]
> > > 建议用docker安装试下吧，因为你的gcc版本太低也用不了paddle。 可以参考下这个文档：https://www.paddlepaddle.org.cn/documentation/docs/zh/install/docker/linux-docker.html
> > > 可以尝试下这两个镜像： docker pull paddlepaddle/paddle:2.2.0-gpu-cuda10.2-cudnn7 docker pull paddlepaddle/paddle:2.2.0-gpu-cuda11.2-cudnn8
> > > 也有3090显卡没法用cuda10.x的可能。
> > 
> > 
> > 我有一个2080显卡环境，gcc版本是6.5.0，这个能运行，但是3090显卡环境的gcc版本是7.5.0，按理说不应该是gcc版本的而原因吧？
> 
> 嗯嗯，这个报错不是gcc版本引起的。我的意思是，即使你上面cuda的这个问题解决了，也还会遇到gcc版本太低的问题，需要再装gcc也比较麻烦。 最好先试下镜像能不能用，排除下CUDA环境的问题。 建议试下11.2的镜像。

感谢您，按照您发的指导，安装了容器，但是docker内安装nccl失败，我是下载https://gitee.com/devilmaycry812839668/nccl-tests然后make，还用了官网的https://developer.nvidia.com/nccl/nccl-legacy-downloads安装，都失败了，您这面有什么方法吗？谢谢您

![image](https://user-images.githubusercontent.com/78945582/144823657-af0b453e-5bca-401d-893b-b03206b6eb43.png)

**Comment by pangyoki** [comment]
docker里不需要重新装nccl，已经装好了，可以设置这两个配置试试：
```
export NCCL_SHM_DISABLE=1
export NCCL_P2P_LEVEL=SYS
```

**Comment by lixiangMindSpore** [comment]
> docker里不需要重新装nccl，已经装好了，可以设置这两个配置试试：
> 
> ```
> export NCCL_SHM_DISABLE=1
> export NCCL_P2P_LEVEL=SYS
> ```

非常感谢

**Comment by Verylight** [comment]
版本：paddlepaddle 2.2，
-----------------------------------------------------------------------------+
| NVIDIA-SMI 472.42       Driver Version: 472.42       CUDA Version: 11.4     |
|-------------------------------+----------------------+----------------------+
| GPU  Name            TCC/WDDM | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ... WDDM  | 00000000:01:00.0 Off |                  N/A |
| N/A   39C    P8    N/A /  N/A |    119MiB /  2048MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+ 
报错：The third-party dynamic library (cudnn64_7.dll) that Paddle depends on is not configured correctly. (error code is 126)

**Comment by pangyoki** [comment]
> 版本：paddlepaddle 2.2， -----------------------------------------------------------------------------+ | NVIDIA-SMI 472.42 Driver Version: 472.42 CUDA Version: 11.4 | |-------------------------------+----------------------+----------------------+ | GPU Name TCC/WDDM | Bus-Id Disp.A | Volatile Uncorr. ECC | | Fan Temp Perf Pwr:Usage/Cap| Memory-Usage | GPU-Util Compute M. | | | | MIG M. | |===============================+======================+======================| | 0 NVIDIA GeForce ... WDDM | 00000000:01:00.0 Off | N/A | | N/A 39C P8 N/A / N/A | 119MiB / 2048MiB | 0% Default | | | | N/A | +-------------------------------+----------------------+----------------------+
> 
> +-----------------------------------------------------------------------------+ | Processes: | | GPU GI CI PID Type Process name GPU Memory | | ID ID Usage | |=============================================================================| | No running processes found | +-----------------------------------------------------------------------------+ 报错：The third-party dynamic library (cudnn64_7.dll) that Paddle depends on is not configured correctly. (error code is 126)

可以检查下这个dll的路径是否被加到环境变量里？Windows安装的问题麻烦 @zhouwei25 看看。另外，建议重新建一个issue，谢谢。

**Comment by zhwesky2010** [comment]
您好，您的来信我已收到，我会尽快回复的。
——周威
