### ISSUE TITLE
TopKOP failed as could not launch cub::DeviceSegmentedRadixSort::SortPairsDescending to sort input, temp_storage_bytes: 767, status: invalid configuration argument

### ISSUE THREAD

**Issue by XYZ-916** [PaddlePaddle/Paddle#37915]
版本：paddle-gpu==2.0.1
训练的时候出现错误：
![image](https://user-images.githubusercontent.com/14884056/144986464-2a9f4fc6-cff2-4fd9-9fad-dbdc44c55f89.png)

求解决方案。

**Comment by wanghuancoder** [comment]
这个报错挺底层的。并不是Paddle框架出了问题，而是CUDA API `SortPairsDescending` 返回的错误。
我搜了一下"SortPairsDescending invalid configuration argument"，也有人在用TF时遇到过同样的问题，但没有人回答解决方案。
我怀疑还是在模型上，传入了错误的数据导致的。
我建议你打印一下传入TopK的数据和参数，看看是不是传入的数据有问题。

**Comment by XYZ-916** [comment]
> 

好的，感谢回复。

**Comment by wanghuancoder** [comment]
应该的

**Comment by XYZ-916** [comment]
请问有什么办法不显示这些log吗

**Comment by wangtianbao1999** [comment]
请问问题得到解决了吗

**Comment by XYZ-916** [comment]
> 

并没有。
