### ISSUE TITLE
paddle中有mask_LSTM

### ISSUE THREAD

**Issue by KiritoSSR** [PaddlePaddle/Paddle#37936]
我们在进行训练Lstm模型的时候可能会遇到这样的一个问题：特征的长度是不一样的，有的特征长度长，有的特征短，办法是补零同时用mask来告知数据哪里是真实的哪里是补零的，也就是更新LSTM状态时需要用mask来作为补充更新c值和h值，paddle中有对应的实现吗？

**Comment by zhwesky2010** [comment]
@KiritoSSR  您好，请问你们目前是如何实现呢？有竞品实现过吗

**Comment by KiritoSSR** [comment]
> @KiritoSSR你好 ，请问你们目前是如何实现呢？有竞品实现过吗？
keras里面有实现（https://blog.csdn.net/Jeaten/article/details/105011214），
allennlp中也有实现（https://docs.allennlp.org/v1.2.2/api/modules/seq2seq_encoders/pytorch_seq2seq_wrapper/）。

或者paddle.nn.LSTM中输入的sequence_length参数可以起到mask的作用吗？

**Comment by zhwesky2010** [comment]
@KiritoSSR 这个会把超过sequence_length的元素的mask设为0，小于sequence_length的元素的mask设为1，应该能满足你的需求

**Comment by KiritoSSR** [comment]
> @KiritoSSR这个可能超过sequence_length的元素的面具设为0，小于sequence_length的元素的面具设为1，应该能满足你的需求

好的
