### ISSUE TITLE
请问保存的checkpoint和动态图保存的.pdparams有什么区别吗？可以相互使用吗

### ISSUE THREAD

**Issue by dickobe** [PaddlePaddle/Paddle#37950]
checkpoint下保存参数数据如下：
![image](https://user-images.githubusercontent.com/9254170/145166574-f16e8458-0137-4ed9-a55d-9260f1c39032.png)

而使用F.save_dygraph保存的结果只有.pdparams

请问这二者的区别是什么，希望能详细解释下

**Comment by zhwesky2010** [comment]
@dickobe  不同API保存的形式不同，前者是把不同参数保存不同文件，后者是一整个文件，如果用save_dygraph保存的，需要用load_dygradph来加载。如果用save_vars保存，建议用load_vars加载；不过这些1.8系列的API不建议使用，建议用paddle最新的paddle.save/load这两个API就可以
