### ISSUE TITLE
ValueError: tmp_76 has no grad, Please set Variable.stop_gradient=False, or check if this is the first and only variable need grad

### ISSUE THREAD

**Issue by ppy-hellowd** [PaddlePaddle/Paddle#37953]
python3, paddle-fluid-1.7:

        class ActorLayer(D.Layer):
            """
            input: state features: cuid,entity,.., dense
            outout: actor_pred
            """
            def __init__(self, params=Params, name_scope="act", trainable=True):
                super(ActorLayer, self).__init__(name_scope=name_scope)
        
                self.state_embedding = StateEmbedding(params, name_scope+"_embed", trainable)
                self.actor = Actor(params, name_scope+"_actor", trainable)
                self.critic = CriticNet(params, name_scope+"_ctic", trainable)
        
            def forward(self, cuid_id_vec, entity_id_vec, trade1_id_vec, trade2_id_vec, attr_id_vec,
                    et1_id_vec, tt1_id_vec, dense_vec):
                self.state_embed = self.state_embedding(cuid_id_vec, entity_id_vec, trade1_id_vec, trade2_id_vec, attr_id_vec,
                    et1_id_vec, tt1_id_vec, dense_vec)
                self.actor_pred = self.actor(self.state_embed)
                self.q_pred = self.critic(self.state_embed, self.actor_pred)
                return self.actor_pred, self.q_pred
        
        
        class CriticLayer(D.Layer):
            """
            input: state, action
            output: Q pred
            """
            def __init__(self, params=Params, name_scope="critic", trainable=True):
                super(CriticLayer, self).__init__(name_scope=name_scope)
        
                self.state_embedding = StateEmbedding(params, name_scope+"_embed", trainable)
                self.critic = CriticNet(params, name_scope+"_ctic", trainable)
        
            def forward(self, cuid_id_vec, entity_id_vec, trade1_id_vec, trade2_id_vec, attr_id_vec,
                    et1_id_vec, tt1_id_vec, dense_vec, action_vec):
                self.state_embed = self.state_embedding(cuid_id_vec, entity_id_vec, trade1_id_vec, trade2_id_vec, attr_id_vec,
                    et1_id_vec, tt1_id_vec, dense_vec)
                self.q_pred = self.critic(self.state_embed, action_vec)
                return self.q_pred
        
        def main(params=Params, mode="test"):
        
            #place = F.CUDAPlace(5)
            place = F.CUDAPlace(5)
            D.guard(place).__enter__()
        
            data_reader = MyDataReader(FLIST, params)
        
            # parameters
            actor   = ActorLayer(params, name_scope="actor")
            actor_n = ActorLayer(params, name_scope="actor_n", trainable=False)
            critic   = CriticLayer(params, name_scope="critic")
            critic_n = CriticLayer(params, name_scope="critic_n", trainable=False)
            #assign_layer_weights(actor, actor_n, TAU=1.0)
            #assign_layer_weights(critic, critic_n, TAU=1.0)
        
            g_clip = F.dygraph_grad_clip.GradClipByGlobalNorm(10.0)
            actor_op  = OP.AdagradOptimizer(learning_rate=params['actor_learning_rate'], parameter_list=actor.parameters())
            critic_op = OP.AdagradOptimizer(learning_rate=params['critic_learning_rate'], parameter_list=critic.parameters())
        
            print_layer_info(actor)
            print_layer_info(actor_n)
            print_layer_info(critic)
            print_layer_info(critic_n)
        
            if mode == "test":
                limit = 5
            else:
                limit = params["max_steps"]
            T1 = time.time()
            nstart, nlimit = 0, 10
        
            for i in range(limit):
                if i % params["soft_replace_steps"] == 0:
                    assign_layer_weights(actor, actor_n, TAU=params["soft_replace_gamma"])
                    assign_layer_weights(critic, critic_n, TAU=params["soft_replace_gamma"])
                S1, A1, R1, S2 = data_reader.next_batch()
                s1, a1, r1, s2 = Get_variable(S1, A1, R1, S2)
        
                action_pred, q_pred = actor(s1[0], s1[1], s1[2], s1[3], s1[4], s1[5], s1[6], s1[7])
                q_pred_for_critic   = critic(s1[0], s1[1], s1[2], s1[3], s1[4], s1[5], s1[6], s1[7], a1) # predict Q value for critic to update
        
                action_next, next_q = actor_n(s2[0], s2[1], s2[2], s2[3], s2[4], s2[5], s2[6], s2[7])
                q_next  = critic_n(s2[0], s2[1], s2[2], s2[3], s2[4], s2[5], s2[6], s2[7], action_next)
                q_label = L.sums(input=[params['gamma'] * q_next, r1])
        
                critic_loss_vec = L.square_error_cost(input=q_pred_for_critic, label=q_label)
                actor_loss_vec  = params["actor_loss_scale"] * q_pred
                critic_loss     = L.reduce_mean(input=critic_loss_vec)
                actor_loss      = L.reduce_mean(input=actor_loss_vec)
                actor_loss.backward()
                critic_loss.backward()
        
                actor_op.minimize(actor_loss)
                #actor_op.minimize(actor_loss, grad_clip=g_clip)
                critic_op.minimize(critic_loss)
                #critic_op.minimize(critic_loss, grad_clip=g_clip)
                if i % params["evaluate_steps"] == 0:
                    # gradients
                    aa_grad = actor.state_embed.gradient()
                    ab_grad = actor.actor_pred.gradient()
                    ac_grad = actor.q_pred.gradient()
                    #ba_grad = actor_n.state_embed.gradient()
                    #bb_grad = actor_n.actor_pred.gradient()
                    #bc_grad = actor_n.q_pred.gradient()
        
                    ca_grad = critic.state_embed.gradient()
                    #cb_grad = critic.q_pred.gradient()
                    #da_grad = critic_n.state_embed.gradient()
                    #db_grad = critic_n.q_pred.gradient()
        
                    aa_g = aa_grad.ravel()[:10]
                    ab_g = ab_grad.ravel()[:10]
                    ac_g = ac_grad.ravel()[:10]
                    ca_g = ca_grad.ravel()[:10]
                    print("gradients state embed {}".format( aa_g))
                    print("gradients actor {} ".format( ab_g ))
                    print("gradients critic {} ".format( ac_g ))
                    print("gradients criticLayer {} ".format( ca_g ))
        
                actor.clear_gradients()
                critic.clear_gradients()

执行main 报错：
Traceback (most recent call last):
  File "train.py", line 580, in <module>
    main(mode="test")
  File "train.py", line 203, in main
    ca_grad = critic.state_embed.gradient()
  File "<decorator-gen-60>", line 2, in gradient
  File "/ssd2/pengpeiyan/tools/python36_v3/python36/lib/python3.6/site-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
    return wrapped_func(*args, **kwargs)
  File "/ssd2/pengpeiyan/tools/python36_v3/python36/lib/python3.6/site-packages/paddle/fluid/framework.py", line 207, in __impl__
    return func(*args, **kwargs)
  File "/ssd2/pengpeiyan/tools/python36_v3/python36/lib/python3.6/site-packages/paddle/fluid/dygraph/varbase_patch_methods.py", line 158, in gradient
    self.name)
ValueError: tmp_76 has no grad, Please set Variable.stop_gradient=False, or check if this is the first and only variable need grad, if so, please set its pre-Variable's stop_gradient=False, to make sure it has gradient

**Comment by zhwesky2010** [comment]
@ppy-hellowd 只有q_pred才有梯度，梯度是在执行loss.backward时从loss回传的，state_embed并没有参与loss的计算，所以没有梯度 
<img width="782" alt="3f8b19724a0f0b11b4c16873d38810d7" src="https://user-images.githubusercontent.com/52485244/145177271-7e83f647-df3e-4762-bd68-1e2b787269a3.png">

**Comment by ppy-hellowd** [comment]
tmp_xx的来源是什么？
ValueError: tmp_159 has no grad, Please set Variable.stop_gradient=False, or check if this is the first and only variable need grad, if so, please set its pre-Variable's stop_gradient=False, to make sure it has gradient 

        def main(params=Params, mode="test"):
            place = F.CUDAPlace(5)
            D.guard(place).__enter__()
        
            data_reader = MyDataReader(FLIST, params)
            # parameters
            actor    = ActorNN(params, name_scope="actor")
            #actor_n  = ActorNN(params, name_scope="actor_n")
            actor_n  = ActorNN(params, name_scope="actor_n", trainable=False)
            critic   = CriticNN(params, name_scope="critic")
            #critic_n = CriticNN(params, name_scope="critic_n")
            critic_n = CriticNN(params, name_scope="critic_n", trainable=False)
        
            #g_clip = F.dygraph_grad_clip.GradClipByGlobalNorm(10.0)
            actor_op  = OP.AdagradOptimizer(learning_rate=params['actor_learning_rate'], parameter_list=actor.parameters())
            critic_op = OP.AdagradOptimizer(learning_rate=params['critic_learning_rate'], parameter_list=critic.parameters())
        
            if mode == "test":
                limit = 5
            else:
                limit = params["max_steps"]
            T1 = time.time()
            nstart = 0
            for i in range(limit):
                if i % params["soft_replace_steps"] == 0:
                    assign_layer_weights(actor, actor_n, TAU=params["soft_replace_gamma"])
                    assign_layer_weights(critic, critic_n, TAU=params["soft_replace_gamma"])
        
                S1, A1, R1, S2 = data_reader.next_batch()
                s1, a1, r1, s2 = Get_variable(S1, A1, R1, S2)
                action_pred, q_pred = actor(s1[0], s1[1], s1[2], s1[3], s1[4], s1[5], s1[6], s1[7])
                q_pred_for_critic   = critic(s1[0], s1[1], s1[2], s1[3], s1[4], s1[5], s1[6], s1[7], a1) # predict Q value for critic to update
        
                action_next, q_next_x= actor_n(s2[0], s2[1], s2[2], s2[3], s2[4], s2[5], s2[6], s2[7])
                q_next  = critic_n(s2[0], s2[1], s2[2], s2[3], s2[4], s2[5], s2[6], s2[7], action_next)
                q_label = L.sums(input=[params['gamma'] * q_next, r1])
        
                critic_loss_vec = L.square_error_cost(input=q_pred_for_critic, label=q_label)
                actor_loss_vec  = params["actor_loss_scale"] * q_pred
                critic_loss     = L.reduce_mean(input=critic_loss_vec)
                actor_loss      = L.reduce_mean(input=actor_loss_vec)
                actor_loss.backward()
                critic_loss.backward()
        
                print(actor_loss.gradient())
                print(critic_loss.stop_gradient)
                print(critic_loss.gradient())
        
                actor_op.minimize(actor_loss)
                #actor_op.minimize(actor_loss, grad_clip=g_clip)
                critic_op.minimize(critic_loss)
                #critic_op.minimize(critic_loss, grad_clip=g_clip)

**Comment by ppy-hellowd** [comment]
仅仅是打印 loss.gradient，就出现了报错

**Comment by ppy-hellowd** [comment]
Traceback (most recent call last):
  File "train.py", line 175, in <module>
    main(mode="test")
  File "train.py", line 106, in main
    print(critic_loss.gradient())
  File "<decorator-gen-60>", line 2, in gradient
  File "/ssd2/pengpeiyan/tools/python36_v3/python36/lib/python3.6/site-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
    return wrapped_func(*args, **kwargs)
  File "/ssd2/pengpeiyan/tools/python36_v3/python36/lib/python3.6/site-packages/paddle/fluid/framework.py", line 207, in __impl__
    return func(*args, **kwargs)
  File "/ssd2/pengpeiyan/tools/python36_v3/python36/lib/python3.6/site-packages/paddle/fluid/dygraph/varbase_patch_methods.py", line 158, in gradient
    self.name)
ValueError: tmp_159 has no grad, Please set Variable.stop_gradient=False, or check if this is the first and only variable need grad, if so, please set its pre-Variable's stop_gradient=False, to make sure it has gradient

**Comment by zhwesky2010** [comment]
@ppy-hellowd tmp_x是网络计算过程中的临时节点，其如果未参与loss计算，是没有梯度的，没有梯度所以访问出错，你可以把它加到loss上：`loss=loss+tmp_x` 就能看到梯度
