### ISSUE TITLE
gloo出现connection refused

### ISSUE THREAD

**Issue by Li-Jiajie** [PaddlePaddle/Paddle#37951]
paddlepaddle 2.2.0，用fleetrun启动，如果所有节点都在一台机器上正常，如果节点分布在多台机器上就会报如下错误
![image](https://user-images.githubusercontent.com/35255760/145167000-9f20c0f7-a968-40da-8d1e-509038f8a1d9.png)

**Comment by Li-Jiajie** [comment]
猜测的问题来源是多网卡
在这台机器上，python中import socket运行socket.gethostbyname(socket.gethostname())得到的是127.0.0.1，正常应该得到自身IP
这里应该是多个网卡只得到到了lo的ip，用gethostbyname_ex就可以得到全部IP
猜测是gloo库中有利用这种操作

顺便一提，paddle自身的python代码里也有用到gethostbyname，拿到的也是127.0.0.1，不过可以通过POD_IP避免开

**Comment by zhwesky2010** [comment]
@wuhuachaocoding 辛苦看下分布式的问题

**Comment by wuhuachaocoding** [comment]
您好，你的程序获取本进程地址是127.0.01. 不对，所以connect fuse. 有两种方式获取本进程地址, 一是调第三方route模块自动获取,第二种是从配置里读, 你看些你是那种方法获取的。

**Comment by Li-Jiajie** [comment]
> 您好，你的程序获取本进程地址是127.0.01. 不对，所以connect fuse. 有两种方式获取本进程地址, 一是调第三方route模块自动获取,第二种是从配置里读, 你看些你是那种方法获取的。

嗯嗯，我后来修改了hosts文件，能够得到正确的ip了
顺便问下gloo在CPU模式下有用吗
![image](https://user-images.githubusercontent.com/35255760/145358313-8c725e7e-01fd-456f-a98e-75130601cfe8.png)

用fleetrun启动的时候，gloo port看起来是随机的，这样会导致多台机器间找不到其他的port，必须得用--http_port=xx来手动指定，这是正确的用法吗
