### ISSUE TITLE
can't build PaddlePaddle production image

### ISSUE THREAD

**Issue by ssdyue** [PaddlePaddle/Paddle#3795]
learn the tutorial [http://doc.paddlepaddle.org/doc/getstarted/build_and_install/docker_install_en.html](url)
i want to build PaddlePaddle production image. 

when i have finished building PaddlePaddle develop image, and run the first step of building PaddlePaddle production image: `docker run -v $(pwd):/paddle -e "WITH_GPU=OFF" -e "WITH_AVX=OFF" -e "WITH_TEST=ON" paddle:dev`, it occurs a error:

**[ 30%] Built target minus_op
[ERROR]	Failed to install: Cannot detect VCS
Cannot detect VCS
CMakeFiles/go_vendor.dir/build.make:60: recipe for target 'glide' failed
make[2]: *** [glide] Error 1
make[1]: *** [CMakeFiles/go_vendor.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
CMakeFiles/Makefile2:508: recipe for target 'CMakeFiles/go_vendor.dir/all' failed**

and stop here.

**Comment by QiJune** [comment]
I will try to reproduce it.

**Comment by wanghaoshuang** [comment]
close this issue due to inactivity.
