### ISSUE TITLE
ValueError: tmp_159 has no grad, Please set Variable.stop_gradient=False, or check if this is the first and only variable need grad

### ISSUE THREAD

**Issue by ppy-hellowd** [PaddlePaddle/Paddle#37989]
paddle 1.7.0 python3.6
动态图模式，两个自定义layer:
        
        class ActorNN(D.Layer):
            """"""
            def __init__(self, params=Params, name_scope="actor", trainable=True):
                super(ActorNN, self).__init__(name_scope=name_scope)
        
                # embedding
                p0 = F.ParamAttr(name=name_scope+"_cuid_embed_0", trainable=trainable)
                p1 = F.ParamAttr(name=name_scope+"_cuid_embed_1", trainable=trainable)
                p2 = F.ParamAttr(name=name_scope+"_cuid_embed_2", trainable=trainable)
                p3 = F.ParamAttr(name=name_scope+"_cuid_embed_3", trainable=trainable)
                p4 = F.ParamAttr(name=name_scope+"_entity_embed", trainable=trainable)
                p5 = F.ParamAttr(name=name_scope+"_trade1_embed", trainable=trainable)
                p6 = F.ParamAttr(name=name_scope+"_trade2_embed", trainable=trainable)
                p7 = F.ParamAttr(name=name_scope+"_attr_embed", trainable=trainable)
                p8 = F.ParamAttr(name=name_scope+"_et1_embed", trainable=trainable)
                p9 = F.ParamAttr(name=name_scope+"_tt1_embed", trainable=trainable)
                self.cuid_embed_0 = D.Embedding(size=(params["cuid_section_dim"], params["cuid_section_embed_dim"]), param_attr=p0)
                self.cuid_embed_1 = D.Embedding(size=(params["cuid_section_dim"], params["cuid_section_embed_dim"]), param_attr=p1)
                self.cuid_embed_2 = D.Embedding(size=(params["cuid_section_dim"], params["cuid_section_embed_dim"]), param_attr=p2)
                self.cuid_embed_3 = D.Embedding(size=(params["cuid_section_dim"], params["cuid_section_embed_dim"]), param_attr=p3)
                self.entity_embed = D.Embedding(size=(params["entity_dim"], params["entity_embed_dim"]), param_attr=p4)
                self.trade1_embed = D.Embedding(size=(params["trade1_dim"], params["trade1_embed_dim"]), param_attr=p5)
                self.trade2_embed = D.Embedding(size=(params["trade2_dim"], params["trade2_embed_dim"]), param_attr=p6)
                self.attr_embed   = D.Embedding(size=(params["attr_dim"], params["attr_embed_dim"]), param_attr=p7)
                self.et1_embed    = D.Embedding(size=(params["entity_trade1_dim"], params["et1_embed_dim"]), param_attr=p8)
                self.tt1_embed    = D.Embedding(size=(params["trade2_trade1_dim"], params["tt1_embed_dim"]), param_attr=p9)
                # actor part
                ap1 = F.ParamAttr(name=name_scope+"_h1", trainable=trainable)
                ap2 = F.ParamAttr(name=name_scope+"_ln1", trainable=trainable)
                ap3 = F.ParamAttr(name=name_scope+"_h2", trainable=trainable)
                ap4 = F.ParamAttr(name=name_scope+"_ln2", trainable=trainable)
                ap5 = F.ParamAttr(name=name_scope+"_fc", trainable=trainable)
                ab1 = F.ParamAttr(name=name_scope+"_b1", trainable=trainable)
                ab2 = F.ParamAttr(name=name_scope+"_lnb1", trainable=trainable)
                ab3 = F.ParamAttr(name=name_scope+"_b2", trainable=trainable)
                ab4 = F.ParamAttr(name=name_scope+"_lnb2", trainable=trainable)
                ab5 = F.ParamAttr(name=name_scope+"_fcb", trainable=trainable)
                state_embed_dim= params["cuid_section_embed_dim"] * 4 + params["entity_embed_dim"] + params["trade1_embed_dim"] +\
                            params["trade2_embed_dim"] + params["attr_embed_dim"] + params["et1_embed_dim"] + params["tt1_embed_dim"] +\
                            params["state_dense_dim"]
                self.l1          = D.Linear(input_dim=state_embed_dim, output_dim=params["a_h1_dim"], param_attr=ap1, bias_attr=ab1, act='relu')
                self.layer_norm1 = D.LayerNorm(normalized_shape=params["a_h1_dim"], param_attr=ap2, bias_attr=ab2)
                self.l2          = D.Linear(input_dim=params["a_h1_dim"], output_dim=params["a_h2_dim"], param_attr=ap3, bias_attr=ab3, act='relu')
                self.layer_norm2 = D.LayerNorm(normalized_shape=params["a_h2_dim"], param_attr=ap4, bias_attr=ab4)
                self.action_pred = D.Linear(input_dim=params["a_h2_dim"], output_dim=params["action_dim"], param_attr=ap5, bias_attr=ab5, act="softmax")
                # critic part
                cp1 = F.ParamAttr(name=name_scope+"_cs1", trainable=trainable)
                cp2 = F.ParamAttr(name=name_scope+"_ca1", trainable=trainable)
                cp3 = F.ParamAttr(name=name_scope+"_cn1", trainable=trainable)
                cp4 = F.ParamAttr(name=name_scope+"_cfc", trainable=trainable)
                cb1 = F.ParamAttr(name=name_scope+"_csb1", trainable=trainable)
                cb2 = F.ParamAttr(name=name_scope+"_cab1", trainable=trainable)
                cb3 = F.ParamAttr(name=name_scope+"_clb1", trainable=trainable)
                cb4 = F.ParamAttr(name=name_scope+"_cfcb", trainable=trainable)
                merge_dim = params["critic_s_h1"] + params["critic_a_h1"]
                self.s1   = D.Linear(input_dim=state_embed_dim, output_dim=params["critic_s_h1"], param_attr=cp1, bias_attr=cb1, act='relu')
                self.a1   = D.Linear(input_dim=params["action_dim"], output_dim=params["critic_a_h1"], param_attr=cp2, bias_attr=cb2, act='relu')
                self.s2   = D.LayerNorm(normalized_shape=params["critic_s_h1"], param_attr=cp3, bias_attr=cb3)
                self.pred = D.Linear(input_dim=merge_dim, output_dim=1, param_attr=cp4, bias_attr=cb4, act=None)
        
            def Tvec(self, var, enabled=False):
                if enabled:
                    return L.transpose(var, perm=[1, 0])
                return var
        
            def forward(self, cuid_id_vec, entity_id_vec, trade1_id_vec, trade2_id_vec, attr_id_vec,
                    et1_id_vec, tt1_id_vec, dense_vec):
                # embedding
                c0_emb = self.cuid_embed_0(self.Tvec(cuid_id_vec[:,0]))
                c1_emb = self.cuid_embed_1(self.Tvec(cuid_id_vec[:,1]))
                c2_emb = self.cuid_embed_2(self.Tvec(cuid_id_vec[:,2]))
                c3_emb = self.cuid_embed_3(self.Tvec(cuid_id_vec[:,3]))
                entity_emb = self.entity_embed(self.Tvec(entity_id_vec))
                trade1_emb = self.trade1_embed(self.Tvec(trade1_id_vec))
                trade2_emb = self.trade2_embed(self.Tvec(trade2_id_vec))
                attr_emb = self.attr_embed(self.Tvec(attr_id_vec))
                et1_emb = self.et1_embed(self.Tvec(et1_id_vec))
                tt1_emb = self.tt1_embed(self.Tvec(tt1_id_vec))
                # actor
                self.merge_output = L.concat([c0_emb, c1_emb, c2_emb, c3_emb, entity_emb, trade1_emb, \
                        trade2_emb, attr_emb, et1_emb, tt1_emb, dense_vec], axis=-1)
                h1            = self.l1(self.merge_output)
                layer_norm_h1 = self.layer_norm1(h1)
                h2            = self.l2(layer_norm_h1)
                layer_norm_h2 = self.layer_norm2(h2)
                merged_layer  = L.sums(input=[layer_norm_h1, layer_norm_h2])
                self.action_out = self.action_pred(merged_layer)
                # critic
                state_h1  = self.s1(self.merge_output)
                action_h1 = self.a1(self.action_out)
                lstate_h1 = self.s2(state_h1)
                merged_layer = L.concat(input=[lstate_h1, action_h1], axis=-1)
                self.q_pred = self.pred(merged_layer)
                return self.action_out, self.q_pred
        
        class CriticNN(D.Layer):
            """"""
            def __init__(self, params=Params, name_scope="critic", trainable=True):
                super(CriticNN, self).__init__(name_scope)
                # embedding
                p0 = F.ParamAttr(name=name_scope+"_cuid_embed_0", trainable=trainable)
                p1 = F.ParamAttr(name=name_scope+"_cuid_embed_1", trainable=trainable)
                p2 = F.ParamAttr(name=name_scope+"_cuid_embed_2", trainable=trainable)
                p3 = F.ParamAttr(name=name_scope+"_cuid_embed_3", trainable=trainable)
                p4 = F.ParamAttr(name=name_scope+"_entity_embed", trainable=trainable)
                p5 = F.ParamAttr(name=name_scope+"_trade1_embed", trainable=trainable)
                p6 = F.ParamAttr(name=name_scope+"_trade2_embed", trainable=trainable)
                p7 = F.ParamAttr(name=name_scope+"_attr_embed", trainable=trainable)
                p8 = F.ParamAttr(name=name_scope+"_et1_embed", trainable=trainable)
                p9 = F.ParamAttr(name=name_scope+"_tt1_embed", trainable=trainable)
                self.cuid_embed_0 = D.Embedding(size=(params["cuid_section_dim"], params["cuid_section_embed_dim"]), param_attr=p0)
                self.cuid_embed_1 = D.Embedding(size=(params["cuid_section_dim"], params["cuid_section_embed_dim"]), param_attr=p1)
                self.cuid_embed_2 = D.Embedding(size=(params["cuid_section_dim"], params["cuid_section_embed_dim"]), param_attr=p2)
                self.cuid_embed_3 = D.Embedding(size=(params["cuid_section_dim"], params["cuid_section_embed_dim"]), param_attr=p3)
                self.entity_embed = D.Embedding(size=(params["entity_dim"], params["entity_embed_dim"]), param_attr=p4)
                self.trade1_embed = D.Embedding(size=(params["trade1_dim"], params["trade1_embed_dim"]), param_attr=p5)
                self.trade2_embed = D.Embedding(size=(params["trade2_dim"], params["trade2_embed_dim"]), param_attr=p6)
                self.attr_embed   = D.Embedding(size=(params["attr_dim"], params["attr_embed_dim"]), param_attr=p7)
                self.et1_embed    = D.Embedding(size=(params["entity_trade1_dim"], params["et1_embed_dim"]), param_attr=p8)
                self.tt1_embed    = D.Embedding(size=(params["trade2_trade1_dim"], params["tt1_embed_dim"]), param_attr=p9)
                # critic part
                cp1 = F.ParamAttr(name=name_scope+"_cs1", trainable=trainable)
                cp2 = F.ParamAttr(name=name_scope+"_ca1", trainable=trainable)
                cp3 = F.ParamAttr(name=name_scope+"_cn1", trainable=trainable)
                cp4 = F.ParamAttr(name=name_scope+"_cfc", trainable=trainable)
                cb1 = F.ParamAttr(name=name_scope+"_csb1", trainable=trainable)
                cb2 = F.ParamAttr(name=name_scope+"_cab1", trainable=trainable)
                cb3 = F.ParamAttr(name=name_scope+"_clb1", trainable=trainable)
                cb4 = F.ParamAttr(name=name_scope+"_cfcb", trainable=trainable)
                state_embed_dim = params["cuid_section_embed_dim"] * 4 + params["entity_embed_dim"] + params["trade1_embed_dim"] +\
                            params["trade2_embed_dim"] + params["attr_embed_dim"] + params["et1_embed_dim"] + params["tt1_embed_dim"] +\
                            params["state_dense_dim"]
                merge_dim = params["critic_s_h1"] + params["critic_a_h1"]
                self.s1   = D.Linear(input_dim=state_embed_dim, output_dim=params["critic_s_h1"], param_attr=cp1, bias_attr=cb1, act='relu')
                self.a1   = D.Linear(input_dim=params["action_dim"], output_dim=params["critic_a_h1"], param_attr=cp2, bias_attr=cb2, act='relu')
                self.s2   = D.LayerNorm(normalized_shape=params["critic_s_h1"], param_attr=cp3, bias_attr=cb3)
                self.pred = D.Linear(input_dim=merge_dim, output_dim=1, param_attr=cp4, bias_attr=cb4, act=None)
        
            def Tvec(self, var, enabled=False):
                if enabled:
                    return L.transpose(var, perm=[1, 0])
                return var
        
            def forward(self, cuid_id_vec, entity_id_vec, trade1_id_vec, trade2_id_vec, attr_id_vec,
                    et1_id_vec, tt1_id_vec, dense_vec, action_vec):
                # embedding
                c0_emb = self.cuid_embed_0(self.Tvec(cuid_id_vec[:,0]))
                c1_emb = self.cuid_embed_1(self.Tvec(cuid_id_vec[:,1]))
                c2_emb = self.cuid_embed_2(self.Tvec(cuid_id_vec[:,2]))
                c3_emb = self.cuid_embed_3(self.Tvec(cuid_id_vec[:,3]))
                entity_emb = self.entity_embed(self.Tvec(entity_id_vec))
                trade1_emb = self.trade1_embed(self.Tvec(trade1_id_vec))
                trade2_emb = self.trade2_embed(self.Tvec(trade2_id_vec))
                attr_emb = self.attr_embed(self.Tvec(attr_id_vec))
                et1_emb = self.et1_embed(self.Tvec(et1_id_vec))
                tt1_emb = self.tt1_embed(self.Tvec(tt1_id_vec))
                self.merge_output = L.concat([c0_emb, c1_emb, c2_emb, c3_emb, entity_emb, trade1_emb, \
                        trade2_emb, attr_emb, et1_emb, tt1_emb, dense_vec], axis=-1)
                # critic
                state_h1  = self.s1(self.merge_output)
                action_h1 = self.a1(action_vec)
                lstate_h1 = self.s2(state_h1)
                merged_layer = L.concat(input=[lstate_h1, action_h1], axis=-1)
                self.q_pred = self.pred(merged_layer)
                #q_label = L.sums(input=[params['gamma'] * q_next_vec, reward_vec])
                #self.q_loss = L.square_error_cost(input=self.q_pred, label=q_label)
                return self.q_pred

构建训练：

        def main(params=Params, mode="test"):
            place = F.CUDAPlace(5)
            D.guard(place).__enter__()
        
            data_reader = MyDataReader(FLIST, params)
            # parameters
            actor    = ActorNN(params, name_scope="actor")
            #actor_n  = ActorNN(params, name_scope="actor_n")
            actor_n  = ActorNN(params, name_scope="actor_n", trainable=False)
            critic   = CriticNN(params, name_scope="critic")
            #critic_n = CriticNN(params, name_scope="critic_n")
            critic_n = CriticNN(params, name_scope="critic_n", trainable=False)
            #g_clip = F.dygraph_grad_clip.GradClipByGlobalNorm(10.0)
            actor_op  = OP.AdagradOptimizer(learning_rate=params['actor_learning_rate'], parameter_list=actor.parameters())
            critic_op = OP.AdagradOptimizer(learning_rate=params['critic_learning_rate'], parameter_list=critic.parameters())
            if mode == "test":
                limit = 3
            else:
                limit = params["max_steps"]
            T1 = time.time()
            nstart = 0
            for i in range(limit):
                if i % params["soft_replace_steps"] == 0:
                    assign_layer_weights(actor, actor_n, TAU=params["soft_replace_gamma"])
                    assign_layer_weights(critic, critic_n, TAU=params["soft_replace_gamma"])
        
                S1, A1, R1, S2 = data_reader.next_batch()
                s1, a1, r1, s2 = Get_variable(S1, A1, R1, S2)
                action_pred, q_pred = actor(s1[0], s1[1], s1[2], s1[3], s1[4], s1[5], s1[6], s1[7])
                q_pred_for_critic   = critic(s1[0], s1[1], s1[2], s1[3], s1[4], s1[5], s1[6], s1[7], a1) # predict Q value for critic to update
        
                action_next, q_next_x= actor_n(s2[0], s2[1], s2[2], s2[3], s2[4], s2[5], s2[6], s2[7])
                q_next  = critic_n(s2[0], s2[1], s2[2], s2[3], s2[4], s2[5], s2[6], s2[7], action_next)
                q_label = L.sums(input=[params['gamma'] * q_next, r1])
                q_label.stop_gradient = True
        
                critic_loss_vec = L.square_error_cost(input=q_pred_for_critic, label=q_label)
                actor_loss_vec  = params["actor_loss_scale"] * q_pred
                critic_loss     = L.reduce_mean(input=critic_loss_vec)
                actor_loss      = L.reduce_mean(input=actor_loss_vec)
        
                actor_loss.backward()
                critic_loss.backward()
                print(actor_loss.gradient())
                print(q_pred.gradient())
                print(critic_loss.gradient())
                print(q_pred_for_critic.gradient())
        
                actor_op.minimize(actor_loss)
                #actor_op.minimize(actor_loss, grad_clip=g_clip)
                critic_op.minimize(critic_loss)
                #critic_op.minimize(critic_loss, grad_clip=g_clip)
                if i % params["save_steps"] == 0:# [1]
                    D.save_dygraph(actor.state_dict(), "./data/actor_train")
                    D.save_dygraph(actor_n.state_dict(), "./data/actor_target")
                    D.save_dygraph(critic.state_dict(), "./data/critic_train")
                    D.save_dygraph(critic_n.state_dict(), "./data/critic_target")
        
                if i % (2**(nstart)) == 0:
                    nstart += 1
                    T2 = time.time()
                    tdiff = T2 - T1
                    print("step {} cost {:.2f} seconds".format(i, tdiff))
        
                if i % params["evaluate_steps"] == 0:
                    aloss = actor_loss.numpy()
                    closs = critic_loss.numpy()
                    print("step {} actor loss critic loss: {},{}".format(i, aloss, closs))
                    p1 = np.array(actor.parameters()[0].numpy()).ravel()[:10]
                    p2 = np.array(critic.parameters()[0].numpy()).ravel()[:10]
                    t1 = np.array(actor.parameters()[-2].numpy()).ravel()[-10:]
                    t2 = np.array(critic.parameters()[-2].numpy()).ravel()[-10:]
                    h1, h2 = has_nan(actor, "layer"), has_nan(critic, "layer")
                    print("actor weights: {}, {}, {}".format(h1, p1, t1))
                    print("critic weights: {}, {}, {}".format(h2, p2, t2))
        
            print("finish traning...")

报错：

        Traceback (most recent call last):
          File "train.py", line 170, in <module>
            main(mode="test")
          File "train.py", line 108, in main
            print(critic_loss.gradient())
          File "<decorator-gen-60>", line 2, in gradient
          File "/ssd2/pengpeiyan/tools/python36_v3/python36/lib/python3.6/site-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
            return wrapped_func(*args, **kwargs)
          File "/ssd2/pengpeiyan/tools/python36_v3/python36/lib/python3.6/site-packages/paddle/fluid/framework.py", line 207, in __impl__
            return func(*args, **kwargs)
          File "/ssd2/pengpeiyan/tools/python36_v3/python36/lib/python3.6/site-packages/paddle/fluid/dygraph/varbase_patch_methods.py", line 158, in gradient
            self.name)
        ValueError: tmp_159 has no grad, Please set Variable.stop_gradient=False, or check if this is the first and only variable need grad, if so, please set its pre-Variable's stop_gradient=False, to make sure it has gradient

**Comment by haozech** [comment]
你好，感谢使用paddle，问题已转给相应同学解答~

**Comment by haozech** [comment]
您好，这是由于网络结构中有交叉导致的。可以通过升级paddle版本到最新，或者在1.7版本下修改网络结构来解决。
