### ISSUE TITLE
paddle.utils.download  _uncompress_file_zip 的 rootpath 为空

### ISSUE THREAD

**Issue by yt605155624** [PaddlePaddle/Paddle#37997]
https://github.com/PaddlePaddle/Paddle/blob/cb636a48f8a17a23fa6ab753946252bec92ce940/python/paddle/utils/download.py#L318
![40f2c4bd2b7f05ddc250dbc3721730a9](https://user-images.githubusercontent.com/24568452/145340532-f84b692f-06b7-4b26-86a3-18bcbb142560.png)
应该把最后的 [-1] 变成 [0]

**Comment by haozech** [comment]
您好，问题已收到，相关同学会尽快处理。

**Comment by haozech** [comment]
目前在最新版本中此问题已修复~
