### ISSUE TITLE
sw_64无法进行编译

### ISSUE THREAD

**Issue by wzyforgit** [PaddlePaddle/Paddle#38002]
- 版本、环境信息：
    1）PaddlePaddle版本：release/2.0-rc1
    2）CPU：请提供CPU型号，arch：sw_64，CPU：sw421
    3）GPU：请提供GPU型号，AMD Oland亮机卡
    4）系统环境：UOS 1041 专业版
- 安装方式信息：
本地编译：cmake ..  -DWITH_MKL=OFF -DWITH_TESTING=OFF -DCMAKE_BUILD_TYPE=Release -DON_INFER=ON -DWITH_PYTHON=OFF -DREFERENCE_CBLAS_ROOT=${CBLAS_ROOT} -DWITH_CRYPTO=OFF -DWITH_XBYAK=OFF -DWITH_SW=ON -DCMAKE_CXX_FLAGS="-Wno-error -w"
  特殊环境请注明：无
- 复现信息：环境如上，系统预装libopencv-dev，cmake 3.13，g++ 8.3.0，git，配置网络代理保证git clone顺畅，然后完全按照 https://paddle-inference.readthedocs.io/en/latest/user_guides/compile_SW.html 所示步骤进行编译，其中仅仅是把python安装包禁用了
- 问题描述：cmake依然会去生成需要编译openblas的makefile，然后还报告REFERENCE_CBLAS_ROOT参数未生效；如果改为从UOS的源里安装blas或者openblas，然后添加参数-DWITH_SYSTEM_BLAS=ON，此时依然会去拉取openblas的代码然后尝试编译，最后接着编译不过报错

**Comment by haozech** [comment]
您好，您给的文档地址我这边打不开，是需要编译预测库还是paddle整体呢？如果是后者可以参考这里的文档 https://www.paddlepaddle.org.cn/documentation/docs/zh/install/compile/sw-compile.html#shenweixiacongyuanmabianyi

**Comment by wzyforgit** [comment]
> 您好，您给的文档地址我这边打不开，是需要编译预测库还是paddle整体呢？如果是后者可以参考这里的文档 https://www.paddlepaddle.org.cn/documentation/docs/zh/install/compile/sw-compile.html#shenweixiacongyuanmabianyi

谢谢回复，我目前是需要编译预测库进行部署。
然后我看您发的链接是推荐使用开发分支编译？这样会不会引入还不稳定的代码？

**Comment by wzyforgit** [comment]
> 您好，您给的文档地址我这边打不开，是需要编译预测库还是paddle整体呢？如果是后者可以参考这里的文档 https://www.paddlepaddle.org.cn/documentation/docs/zh/install/compile/sw-compile.html#shenweixiacongyuanmabianyi

好了我试过了，现象是一样的，编不了

**Comment by haozech** [comment]
> 

问题已转给相关同学哈

**Comment by wzyforgit** [comment]
> 

所以相关同学还解决吗？
我这边定位到明显是CMAKE里面写的有问题，导致它根本不会按照你发的教程里面写的那样去调用 CBLAS，但即便改了以后，正常调用CBLAS，最后依然会报告找不到 PaddlePaddle 自己定义的异常对象，就是那个什么 Paddle throw 还是啥。
我建议你们这边提供一个稳定点的CMAKE方案，让它可以去调系统内部的BLAS而不是一股劲地去下载BLAS源码来编译，因为 UOS 官方是往那上面移植了 blas dev 和 blas 两个包的，既然要兼容 UOS 就好好做到全平台兼容。
