### ISSUE TITLE
Running matmul_v2_transpose_reshape_fuse_pass will get MKLDNNDeviceContext error.

### ISSUE THREAD

**Issue by baoachun** [PaddlePaddle/Paddle#38038]
ref to https://github.com/PaddlePaddle/Paddle/pull/36481#issuecomment-984397795

**Comment by lidanqing-vv** [comment]
@jakpiase Hi, could you please check this issue ? Thanks !

**Comment by jakpiase** [comment]
Hi, @baoachun it will be fixed after merging #38411

**Comment by jakpiase** [comment]
Hi @baoachun, fix PR has been merged already, so could you please confirm that this problem is resolved?

**Comment by baoachun** [comment]
Hi @jakpiase, the problem has been solved, thanks!
