### ISSUE TITLE
How to deal with MultiInput in Python code

### ISSUE THREAD

**Issue by Yancey1989** [PaddlePaddle/Paddle#3805]
Hi, I'm implementing the `Concat` Operator, the input should be an array,  but maybe it does not support `MultiInput` in Python code, here is my error logs:
- Python code
```python
    x0 = np.random.random((3, 4)).astype('float32')
    x1 = np.random.random((4, 4)).astype('float32') 
    x2 = np.random.random((5, 4)).astype('float32')  
    self.inputs = {
       'X': np.asarray([x0, x1, x2])
    }
```
- Part of the error logs:
```bash
26: Traceback (most recent call last):
26:   File "/paddle/python/paddle/v2/framework/tests/op_test_util.py", line 36, in test_all
26:     var.set(arr, place)
26: TypeError: set(): incompatible function arguments. The following argument types are supported:
26:     1. (self: paddle.v2.framework.core.Tensor, arg0: numpy.ndarray[float32], arg1: paddle::platform::CPUPlace) -> None
26:     2. (self: paddle.v2.framework.core.Tensor, arg0: numpy.ndarray[int32], arg1: paddle::platform::CPUPlace) -> None
26:
```

**Comment by typhoonzero** [comment]
Thought you mean "dynamic number of inputs". Maybe you can iterate through ctx.Input to get all of the input tensors.

**Comment by Yancey1989** [comment]
@typhoonzero , I can get the inpus tensor in C++ code like:
```cpp
auto ins = ctx.MultiInput<framework::Tensor>("X");
```
But I don't know how to set the inputs in Python code.

**Comment by QiJune** [comment]
这里的问题是，concat op的输入源是多个variable(每个variable里面有一个tensor)；然后在这里使用一个[X](https://github.com/Yancey1989/Paddle/blob/63853cabe798bf000bcc7891156d35e61528e0f1/paddle/operators/concat_op.cc#L57)来与多个Variable关联。没太想明白[X](https://github.com/Yancey1989/Paddle/blob/63853cabe798bf000bcc7891156d35e61528e0f1/paddle/operators/concat_op.cc#L57)是啥？

**Comment by Yancey1989** [comment]
Hi @QiJune ，X就是使用`ConcatOp`时输入的多个数组。

**Comment by QiJune** [comment]
@Yancey1989  I am try to implement sum operator, #3813. The sum operator has multi-inputs too.

**Comment by Yancey1989** [comment]
Thanks @QiJune and some comments  at https://github.com/PaddlePaddle/Paddle/pull/3813#pullrequestreview-60299859.

**Comment by Yancey1989** [comment]
Close this inactivate issue.
