### ISSUE TITLE
SystemError

### ISSUE THREAD

**Issue by happyfox-dot** [PaddlePaddle/Paddle#38050]
为使您的问题得到快速解决，在建立Issues前，请您先通过如下方式搜索是否有相似问题:【搜索issue关键字】【使用labels筛选】【官方文档】

如果您没有查询到相似问题，为快速解决您的提问，建立issue时请提供如下细节信息：
- 标题：简洁、精准概括您的问题
- 版本、环境信息：
    1）PaddlePaddle版本：请提供您的PaddlePaddle2.2.1
    2）CPU/GPU：如果您使用GPU训练，请提供GPU驱动版本、CUDA和cuDNN版本号
Gpu：Tesla V100,CUDA：10.1,cuDnn
    3）系统环境：请您描述系统类型、版本，例如Mac OS 10.14
    4）Python版本号
python 3.8
    5）显存信息

 注：您可以通过执行[summary_env.py](https://github.com/PaddlePaddle/Paddle/blob/develop/tools/summary_env.py)获取以上信息。
- 复现信息：如为报错，请给出复现环境、复现步骤
- 问题描述：请详细描述您的问题，同步贴出报错信息、日志/代码关键片段
- SystemError                               Traceback (most recent call last)
/tmp/ipykernel_393/586262745.py in <module>
      1 #模型的训练
      2 # train_data ,train_labels = pointDatadLoader(file_path='./mytest/train.txt',model='train')
----> 3 model =PointNet()
      4 model.train()
      5 optim  = paddle.optimizer.Adam(parameters=model.parameters(),weight_decay=0.001)

/tmp/ipykernel_393/1718473380.py in __init__(self, name_scope, num_classes, num_point)
      5         super(PointNet,self).__init__()
      6         self.input_transform_net=nn.Sequential(
----> 7             nn.Conv2D(3,64,(1,1)),
      8             nn.BatchNorm(64),
      9             nn.ReLU(),

/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/nn/layer/conv.py in __init__(self, in_channels, out_channels, kernel_size, stride, padding, dilation, groups, padding_mode, weight_attr, bias_attr, data_format)
    654             weight_attr=weight_attr,
    655             bias_attr=bias_attr,
--> 656             data_format=data_format)
    657 
    658     def forward(self, x):

/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/nn/layer/conv.py in __init__(self, in_channels, out_channels, kernel_size, transposed, dims, stride, padding, padding_mode, output_padding, dilation, groups, weight_attr, bias_attr, data_format)
    133             shape=filter_shape,
    134             attr=self._param_attr,
--> 135             default_initializer=_get_default_param_initializer())
    136         self.bias = self.create_parameter(
    137             attr=self._bias_attr, shape=[self._out_channels], is_bias=True)

/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py in create_parameter(self, shape, attr, dtype, is_bias, default_initializer)
    422             temp_attr = None
    423         return self._helper.create_parameter(temp_attr, shape, dtype, is_bias,
--> 424                                              default_initializer)
    425 
    426     @deprecated(

/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/layer_helper_base.py in create_parameter(self, attr, shape, dtype, is_bias, default_initializer, stop_gradient, type)
    376                 type=type,
    377                 stop_gradient=stop_gradient,
--> 378                 **attr._to_kwargs(with_initializer=True))
    379         else:
    380             self.startup_program.global_block().create_parameter(

/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/framework.py in create_parameter(self, *args, **kwargs)
   3135                 pass
   3136             else:
-> 3137                 initializer(param, self)
   3138         return param
   3139 

/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/initializer.py in __call__(self, var, block)
    364                 "use_mkldnn": False
    365             },
--> 366             stop_gradient=True)
    367 
    368         if var.dtype in [VarDesc.VarType.FP16, VarDesc.VarType.BF16]:

/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/framework.py in append_op(self, *args, **kwargs)
   3165                                        kwargs.get("outputs", {}), attrs
   3166                                        if attrs else {},
-> 3167                                        kwargs.get("stop_gradient", False))
   3168         else:
   3169             from paddle.fluid.dygraph.base import param_guard

/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/tracer.py in trace_op(self, type, inputs, outputs, attrs, stop_gradient)
     43         self.trace(type, inputs, outputs, attrs,
     44                    framework._current_expected_place(), self._has_grad and
---> 45                    not stop_gradient)
     46 
     47     def train_mode(self):
SystemError: (Fatal) Operator gaussian_random raises an thrust::system::system_error exception.
The exception content is
:parallel_for failed: cudaErrorInvalidConfiguration: invalid configuration argument. (at /paddle/paddle/fluid/imperative/tracer.cc:221)
Thank you for contributing to PaddlePaddle.
Before submitting the issue, you could search issue in the github in case that there was a similar issue submitted or resolved before.
If there is no solution,please provide us with the following details :
**System information**
-PaddlePaddle version （eg.1.1）or CommitID
-CPU: including CPUMKL/OpenBlas/MKLDNN version
-GPU: including CUDA/cuDNN version
-OS Platform and Distribution(eg.Mac OS 10.14)
-Python version 
Note: You can get most of the information by running [summary_env.py](https://github.com/PaddlePaddle/Paddle/blob/develop/tools/summary_env.py). 
**To Reproduce**
Steps to reproduce the behavior
**Describe your current behavior**
**Code to reproduce the issue**
**Other info / logs**

**Comment by happyfox-dot** [comment]
Paddle version: 2.2.1
Paddle With CUDA: True

OS: Ubuntu 16.04
Python version: 3.7.4

CUDA version: 10.1.243
cuDNN version: 7.3.1
Nvidia driver version: 418.67

**Comment by happyfox-dot** [comment]
Its okey for I just only use CPU,however it doesn't work when I use GPU resource! :(

**Comment by qili93** [comment]
关于这个错误应该是由于环境中的cuDNN版本太低了，Nvidia官网对CUDA10.1支持的cuDNN版本最低也是7.5.0，同时Paddle官网支持的Cudnn版本是7.6.5，建议升级环境中的cudnn版本

```
SystemError: (Fatal) Operator gaussian_random raises an thrust::system::system_error exception.
The exception content is
:parallel_for failed: cudaErrorInvalidConfiguration: invalid configuration argument. (at /paddle/paddle/fluid/imperative/tracer.cc:221)”
```

**Comment by happyfox-dot** [comment]
好的好的，我回去尝试一下：）

**Comment by happyfox-dot** [comment]
> 关于这个错误应该是由于环境中的cuDNN版本太低了，Nvidia官网对CUDA10.1支持的cuDNN版本最低也是7.5.0，同时Paddle官网支持的Cudnn版本是7.6.5，建议升级环境中的cudnn版本
> 
> ```
> SystemError: (Fatal) Operator gaussian_random raises an thrust::system::system_error exception.
> The exception content is
> :parallel_for failed: cudaErrorInvalidConfiguration: invalid configuration argument. (at /paddle/paddle/fluid/imperative/tracer.cc:221)”
> ```

如何在paddle ai studio 中升级cudacnn 呢，有教程吗:)

**Comment by qili93** [comment]
@happyfox-xie 不好意思，才看到，是AI Studio环境的话，建议咨询一下AI Studio的同学，谢谢！

**Comment by happyfox-dot** [comment]
好的吧，还是谢谢啦:)




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/Paddle"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月13日(星期一) 上午10:41
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PaddlePaddle/Paddle] SystemError (Issue #38050)





 
@happyfox-xie 不好意思，才看到，是AI Studio环境的话，建议咨询一下AI Studio的同学，谢谢！
 
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
