### ISSUE TITLE
paddle是否有torch.overrides相关功能实现

### ISSUE THREAD

**Issue by huilin16** [PaddlePaddle/Paddle#38059]
请问paddle有torch.overrides.has_torch_function、handle_torch_function对应的函数吗

**Comment by windstamp** [comment]
您好，目前还没有相关的对应函数。

您的反馈对产品非常有价值，我们内部会安排评估，未来有计划尽快回复。

**Comment by Ligoml** [comment]
用户你好，请问是做什么任务需要用到相关 API 呢？是论文复现吗？这个 API 是否会阻塞你的复现工作呢？你可以填写以下表单提交需求，我们会尽快处理的：https://docs.qq.com/sheet/DWnhZS3N1WUhMUW5Z?tab=BB08J2

**Comment by huilin16** [comment]
是的，HRFormer复现遇到的
十分感谢，已提交






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/Paddle"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月13日(星期一) 中午11:08
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PaddlePaddle/Paddle] paddle是否有torch.overrides相关功能实现 (Issue #38059)





 
用户你好，请问是做什么任务需要用到相关 API 呢？是论文复现吗？这个 API 是否会阻塞你的复现工作呢？你可以填写以下表单提交需求，我们会尽快处理的：https://docs.qq.com/sheet/DWnhZS3N1WUhMUW5Z?tab=BB08J2
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by firestonelib** [comment]
@huilin16 你好，请问 HRFormer 里具体哪里用到 torch.overrides.has_torch_function (您描述的“自定义类作为tensor保存”)?  我们想进一步定位，看是否有等效的替代方案。

**Comment by huilin16** [comment]
您好，在HRFormer-main\cls\models\modules\multihead_attention.py文件MultiheadAttentionRPE类，multi_head_attention_forward方法下，







------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年12月17日(星期五) 下午2:40
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [PaddlePaddle/Paddle] paddle是否有torch.overrides相关功能实现 (Issue #38059)





 
@huilin16 你好，请问 HRFormer 里具体哪里用到 torch.overrides.has_torch_function (您描述的“自定义类作为tensor保存”)?  我们想进一步定位，看是否有等效的替代方案。
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by firestonelib** [comment]
@huilin16 你好，看了代码，这个本质上是 Multihead Attention的实现，可以参见 paddle 官方实现：https://github.com/PaddlePaddle/Paddle/blob/6d1b8c5261ca83bd59edf78d52a3362d32082dae/python/paddle/nn/layer/transformer.py#L109

**Comment by huilin16** [comment]
好的，多谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年12月17日(星期五) 下午4:17
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [PaddlePaddle/Paddle] paddle是否有torch.overrides相关功能实现 (Issue #38059)





 
@huilin16 你好，看了代码，这个本质上是 Multihead Attention的实现，可以参见 paddle 官方实现：https://github.com/PaddlePaddle/Paddle/blob/6d1b8c5261ca83bd59edf78d52a3362d32082dae/python/paddle/nn/layer/transformer.py#L109
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
