### ISSUE TITLE
【论文复现】希望增加 F.affine_grid 的 3D 支持

### ISSUE THREAD

**Issue by S-HuaBomb** [PaddlePaddle/Paddle#38061]
- 版本、环境信息
1）PaddlePaddle版本：2.2

- 复现信息：复现 VNet 需要使用 3D 图像变形做数据增强
- 建议描述：图像变形需要 F.affine_grid 生成位移网格，然后配合 F.grid_sample 使用。现在它们都不支持 3D，让我很难做。希望尽快支持 3D 网格变形。

**Comment by windstamp** [comment]
您好，您的反馈对产品非常有价值，我们内部会安排评估，未来有计划尽快回复。

**Comment by shiyutang** [comment]
您好，复现VNet的推荐repo里没有对这两个算子的需求，请问你是参考的哪个repo呢，我们的推荐repo是这个：https://github.com/mattmacy/vnet.pytorch

**Comment by luotao1** [comment]
https://github.com/PaddlePaddle/Paddle/pull/45015 实现了grid_sample()支持3D的功能
