### ISSUE TITLE
论文复现 loss.backward() RuntimeError

### ISSUE THREAD

**Issue by jordan2013** [PaddlePaddle/Paddle#38062]
- 标题： loss.backward() RuntimeError
- 版本、环境信息：
    1）PaddlePaddle版本：2.2.1
    2）CPU：无
    3）GPU：AIStudio平台上的GPU
    4）系统环境：python 3.7,AIStudio 环境

- 训练信息
    1）单机/单卡
    2）显存信息
    3） loss.backward()
- 复现信息：如为报错，请给出复现环境、复现步骤
- AiStudio：https://aistudio.baidu.com/aistudio/projectdetail/3204731?contributionType=1&shared=1
- 问题描述：
---> 37             loss.backward()
     38             print("loss.grad:{}".format(loss.grad))
     39             for name, param in model.named_parameters():

<decorator-gen-253> in backward(self, grad_tensor, retain_graph)

/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/wrapped_decorator.py in __impl__(func, *args, **kwargs)
     23     def __impl__(func, *args, **kwargs):
     24         wrapped_func = decorator_func(func)
---> 25         return wrapped_func(*args, **kwargs)
     26 
     27     return __impl__

/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/framework.py in __impl__(*args, **kwargs)
    227         assert in_dygraph_mode(
    228         ), "We only support '%s()' in dynamic graph mode, please call 'paddle.disable_static()' to enter dynamic graph mode." % func.__name__
--> 229         return func(*args, **kwargs)
    230 
    231     return __impl__

/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/varbase_patch_methods.py in backward(self, grad_tensor, retain_graph)
    247             else:
    248                 core.dygraph_run_backward([self], [grad_tensor], retain_graph,
--> 249                                           framework._dygraph_tracer())
    250         else:
    251             raise ValueError(

RuntimeError: (AlreadyExists) Accumulators are not empty before preparing it for backward network execution.
  [Hint: Expected accumulators_.empty() == true, but received accumulators_.empty():0 != true:1.] (at /paddle/paddle/fluid/imperative/basic_engine.cc:55)
Thank you for contributing to PaddlePaddle.
Before submitting the issue, you could search issue in the github in case that there was a similar issue submitted or resolved before.
If there is no solution,please make sure that this is a training issue including the following details:

**Comment by windstamp** [comment]
您好，AiStudio：https://aistudio.baidu.com/aistudio/projectdetail/3204731?contributionType=1&shared=1 这个链接没有权限打开。麻烦再提供一份有效的链接，或提供一份可复现问题的代码。

另外，请问是静态图还是动态图模式下报错？

**Comment by jordan2013** [comment]
是在动态图模式下出现的问题。https://aistudio.baidu.com/aistudio/projectdetail/3204731,试下这个链接，

**Comment by windstamp** [comment]
我测试后发现是首先报了如下错误 
```
RuntimeError: (NotFound) Inputs and outputs of reshape2_grad do not exist. This may be because:
1. You use some output variables of the previous batch as the inputs of the current batch. Please try to call "stop_gradient = True" or "detach()" for these variables.
2. You calculate backward twice for the same subgraph without setting retain_graph=True. Please set retain_graph=True in the first backward call.


  [Hint: Expected ins_.empty() && outs_.empty() != true, but received ins_.empty() && outs_.empty():1 == true:1.] (at /paddle/paddle/fluid/imperative/op_base.h:164)
```

然后，再次执行后才会报错
```
RuntimeError: (AlreadyExists) Accumulators are not empty before preparing it for backward network execution.
  [Hint: Expected accumulators_.empty() == true, but received accumulators_.empty():0 != true:1.] (at /paddle/paddle/fluid/imperative/basic_engine.cc:55)
```

后续的测试报错应该不是真正的报错，只是测试不是一个干净的 paddle 环境导致的。建议先排查一下模型，可以根据上述第一个报错，试着逐渐增加模型的复杂度试试。

我这边做了如下修改之后可以正常训练，但是不一定是您需要的。
```
loss.backward()
```

=>

```
loss.backward(retain_graph=True)
```

**Comment by jordan2013** [comment]
感谢，找到问题，这个语句出现问题：self.kernel = (self.kernel*self.it_weights).reshape([64,64,-1,1])，改为k = (self.kernel*self.it_weights).reshape([64,64,-1,1]),后续使用k的值就可以了
