### ISSUE TITLE
Simplify operator development by making build system more automatic

### ISSUE THREAD

**Issue by typhoonzero** [PaddlePaddle/Paddle#3807]
It's easier for developers to develop operators if we make our building system more "automatic".

As in https://github.com/PaddlePaddle/Paddle/pull/3801, we don't need to write lines in `pybind/CMakeLists.txt` and `operators/CMakeLists.txt`, further more, we can just let users to implemet `xxx_op.h`, `xxx_op.cc/cu`, `test_xxx_op.py` that's all!

**Comment by luotao1** [comment]
We should remove `USE_OP(XXX)` in [paddle/pybind/pybind.cc](https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/pybind/pybind.cc). We can auto generate `USE_OP(XXX)` into `pybind.h` file when building `paddle/operators/CMakeLists.txt`.

 Followings things should be done before:
- As `USE_OP(add_two)`，we should rename `add_op.cc/cu/h` to `add_two_op.cc/cu/h`.
- As `USE_CPU_ONLY_OP(gather)` and `USE_CPU_ONLY_OP(scatter)`, we should remove `gather_op.cu` and `scatter_op.cu`，thus, `paddle/operators/CMakeLists.txt` can auto set `USE_CPU_ONLY_OP` for ops that only has `.cc` file.
- As `USE_OP_ITSELF(identity)`, we can move `identiy_op` out from `scale_op`, and new `identity_op.cc/cu/h`. Thus, `USE_OP(identity)` is ok.
