### ISSUE TITLE
Evaluators need to store variable(tensor) in an op

### ISSUE THREAD

**Issue by typhoonzero** [PaddlePaddle/Paddle#3808]
When start writing an evaluator operator, I found that I have to store a global status like `total_samples` and `total_score` to calculate the error rate of current forward iteration, so that I can increase these values every forward, like `total_samples += batch_size` and `total_score += score`.

A simply thought is to add a member function `CreateOpVar` in `InferShapeContext`, and name the variable like `[operator_id]_var_name` to avoid variable name conflict.

Can we discuss about whether we need to add this to current framework?

**Comment by emailweixu** [comment]
I think evaluator will be divided into 2 parts. The first part follows the current op interface, and is responsible for calculating necessary statistics for one mini-batch. The second part is responsible for merging the mini-batch statistics to form the evaluation result for multiple mini-batches. The second part can be implemented in python.

**Comment by helinwang** [comment]
If everything is expressed in the graph, the distributed computation would much be easier (just upload the graph, not the Python program: if we only have the graph, we can do what every modification we want to the graph in order support distributed training, and run the modified graph in the cpp core. Things will be much more complicated if Python is involved.)
Note that we could support "express everything as a graph" and Python at the same time, for example, we can have a "for loop OP" for training data, but in the same time still support training using the Python "for loop", and user can still use Python "for loop" when experimenting locally.

We can do the following if we decided to express everything as a graph.

<img width="308" alt="screen shot 2017-09-01 at 11 11 09 am" src="https://user-images.githubusercontent.com/1724178/29982376-474cea94-8f06-11e7-9e2b-d678634b0006.png">

**Comment by helinwang** [comment]
Related: https://github.com/PaddlePaddle/Paddle/pull/3811

**Comment by emailweixu** [comment]
Yes, merge can also be based on OPs. So an evaluator will have two OPs (similar to forward and corresponding grad op): op for collecting statistics, op for merging statistics. The python code will be responsible for arranging them correctly.

**Comment by typhoonzero** [comment]
Seems the "merging" op still need some way to store some variables in the scope of the subgraph.

**Comment by qingqing01** [comment]
> op for merging statistics

The “merging” op needs to merge the results from the last mini-batch and the results saved in `Scope`.  Some evaluators, such as classification-error, only need one result from the last mini-batch. Some evaluators, such as auc evaluator, precision-recall evaluator, need more than one results from last mini-batch.

If this op is also a C++ op,  the "merging" op can take the results from the last mini-batch as the input, which can be initialized correctly in Python.  And the  “merging”  can update this "last mini-batch" results each mini-batch.

**Comment by helinwang** [comment]
> The second part can be implemented in python.

To clarify, I think the current refactor design have a clear separation between compile-time (Python) and runtime (cpp). So every OP needs to be implemented in cpp. @typhoonzero  @qingqing01 @emailweixu

**Comment by jacquesqiao** [comment]
In the current framework, all Variables are created by python outside Op itself, and then use the var's name to create some Ops to process it.  

Under this framework, the way to create evaluator should be:

1.  Python creates a var in scope to store the state.
1.  Python passes the var's name to evaluator Op and Ops to accumulate this var(such as Sum/Average).

All computation is run by Operator. The state Var and Op to processes it will all be stored in the groph.

**Comment by typhoonzero** [comment]
> Python creates a var in scope to store the state.

Maybe should create a sub-net and connect the forward net's output to this subnet.
