### ISSUE TITLE
RuntimeError: (PreconditionNotMet) The third-party dynamic library (libcublas.so) that Paddle dred correctly. (error code is libcublas.so: cannot open shared object file: No such file or dir   Suggestions:

### ISSUE THREAD

**Issue by xiaomujiang** [PaddlePaddle/Paddle#38106]
安装cuda10.2  cudnn7.6.5 和paddle，验证报错
RuntimeError: (PreconditionNotMet) The third-party dynamic library (libcublas.so) that Paddle dred correctly. (error code is libcublas.so: cannot open shared object file: No such file or dir   Suggestions:？？？？？？？？？？？？？？？？？
版本信息如下
(dogg) root@bigclata-PowerEdge-R740:/usr/local/cuda/lib64# pip list | grep paddle
paddle2onnx                       0.8.2
paddlefsl                         1.0.0
paddlehub                         2.1.1
paddlenlp                         2.1.1
paddlepaddle-gpu                  2.1.3
tb-paddle                         0.4.
版本查看
(dogg) root@bigclata-PowerEdge-R740:/usr/local/cuda/lib64# nvcc -V
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2019 NVIDIA Corporation
Built on Wed_Oct_23_19:24:38_PDT_2019
Cuda compilation tools, release 10.2, V10.2.89
(dogg) root@bigclata-PowerEdge-R740:~/videoai/xwj-videoai-dog-junlan/codes/Dog# cat /usr/local/cuda/include/cudnn.h | grep CUDNN_MAJOR -A 2
#define CUDNN_MAJOR 7
#define CUDNN_MINOR 6
#define CUDNN_PATCHLEVEL 5
--
#define CUDNN_VERSION (CUDNN_MAJOR * 1000 + CUDNN_MINOR * 100 + CUDNN_PATCHLEVEL)

#include "driver_types.h"
查找libcublas.so的位置
(dogg) root@bigclata-PowerEdge-R740:/usr/local/cuda/lib64# locate libcublas.so
/usr/lib/x86_64-linux-gnu/libcublas.so
/usr/lib/x86_64-linux-gnu/libcublas.so.10
/usr/lib/x86_64-linux-gnu/libcublas.so.10.2.2.89
/usr/lib/x86_64-linux-gnu/libcublas.so.9.1
/usr/lib/x86_64-linux-gnu/libcublas.so.9.1.85
/usr/lib/x86_64-linux-gnu/stubs/libcublas.so
/usr/local/cuda-10.2/doc/man/man7/libcublas.so.7
/usr/share/man/man7/libcublas.so.7
/usr/share/man/man7/libcublas.so.7.gz

export PATH=/usr/local/cuda-10.2/bin:$PATH
export LD_LIBRARY_PATH=/usr/local/cuda-10.2/lib64

**Comment by tink2123** [comment]
echo $LD_LIBRARY_PATH 看下你的libcublas.so 文件是否在这个环境变量中，不在的话添加进去试下
