### ISSUE TITLE
Paddle2.2.1-gpu 安装错误： cuda版本错误

### ISSUE THREAD

**Issue by ff12343** [PaddlePaddle/Paddle#38149]
- 版本环境信息：
1）PaddlePaddle版本：Paddle2.2.1-gpu
2）win10 系统， Intel i7-10750 处理器
3）GPU：GTX1660Ti，CUDA10.2.89，CUDNN8.3
4）环境：Python3.8

- 安装方式信息：
1）conda环境中使用pip安装

- 问题描述：

RuntimeError: (PreconditionNotMet) The third-party dynamic library (cudnn64_7.dll) that Paddle depends on is not configured correctly. (error code is 126)
  Suggestions:
  1. Check if the third-party dynamic library (e.g. CUDA, CUDNN) is installed correctly and its version is matched with paddlepaddle you installed.
  2. Configure third-party dynamic library environment variables as follows:
  - Linux: set LD_LIBRARY_PATH by `export LD_LIBRARY_PATH=...`
  - Windows: set PATH by `set PATH=XXX; (at ..\paddle\fluid\platform\dynload\dynamic_loader.cc:285)

**Comment by ff12343** [comment]
安装方式按照的是cuda10.2的安装方式，命令：python -m pip install paddlepaddle-gpu==2.2.1 -i https://mirror.baidu.com/pypi/simple。
然后安装paddleX，命令：pip install paddlex==2.0.0 -i https://mirror.baidu.com/pypi/simple

**Comment by ZHUI** [comment]
> 安装方式按照的是cuda10.2的安装方式，命令：python -m pip install paddlepaddle-gpu==2.2.1 -i [https://mirror.baidu.com/pypi/simple。](https://mirror.baidu.com/pypi/simple%E3%80%82) 然后安装paddleX，命令：pip install paddlex==2.0.0 -i https://mirror.baidu.com/pypi/simple

建议先check一下本地cuda环境。本地cuda是否是10.2？windows环境变量是否设置好了cuda的路径？

**Comment by ff12343** [comment]
> > 安装方式按照cuda10.2的安装方式，命令：python -m pip install paddlepaddle-gpu==2.2.1 -i [https://mirror.baidu.com/pypi/simple。](https://mirror.baidu.com/pypi/simple%E3%80%82)然后安装paddleX，命令：pip安装paddlex==2.0.0 -i https://mirror.baidu.com/pypi/simple
> 
> 建议先检查一下本地cuda环境。本地cuda是否是10.2？windows环境变量是否设置好了cuda的路径？

cuda环境没问题
![image](https://user-images.githubusercontent.com/42758082/146634343-2c6154eb-3144-4552-939a-78bc5e060cbd.png)
![image](https://user-images.githubusercontent.com/42758082/146634396-cb382870-6c00-41db-a381-9fe780952c80.png)

**Comment by ZHUI** [comment]
是已经解决了吗？看issue已经close了。

**Comment by lvyc1234** [comment]
> 是已经解决了吗？看问题已经关闭了。

C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.0\bin

在bin路径下将cublas64_100.dll重命名为cublas64_10.dll 
在bin路径下将cusolver64_100.dll重命名为cusolver64_102.dll

**Comment by ZHUI** [comment]
> C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.0\bin
> 
> 在bin路径下将cublas64_100.dll重命名为cublas64_10.dll 在bin路径下将cusolver64_100.dll重命名为cusolver64_102.dll

你本地的cuda是10.0的，所以造成了这个问题。
