### ISSUE TITLE
fluid.layers.linear_chain_crf输入参数纬度问题

### ISSUE THREAD

**Issue by smfhn163com** [PaddlePaddle/Paddle#38152]
paddle版本： 1.8.1 
在https://www.paddlepaddle.org.cn/documentation/docs/zh/1.8/api_cn/layers_cn/linear_chain_crf_cn.html#linear-chain-crf 中查看， 输入是支持[N x S x D]的Tensor，N是batch_size，S为序列的最大长度，D是维度， 在使用过程中，输入三维数据，提示错误： 
InvalidArgumentError: The Input(Emission) should be a 2-D tensor. But received: input rank 3, input shape [-1, 128, 239].

**Comment by ZHUI** [comment]
![image](https://user-images.githubusercontent.com/16911935/146120060-f4e6d462-1c86-4888-9559-bbe30ab3f825.png)
是否是输入为LodTensor了？

**Comment by ZHUI** [comment]
https://github.com/PaddlePaddle/Paddle/blob/release/1.8/paddle/fluid/operators/linear_chain_crf_op.cc#L182
看源码，需要 Length 变量才会走到3-D的分支。

**Comment by smfhn163com** [comment]
> 



> ![image](https://user-images.githubusercontent.com/16911935/146120060-f4e6d462-1c86-4888-9559-bbe30ab3f825.png) 是否是输入为LodTensor了？

不是LodTensor，数据数据为
name: "fc_73.tmp_1"
type {
  type: LOD_TENSOR
  lod_tensor {
    tensor {
      data_type: FP32
      dims: -1
      dims: 128
      dims: 239
    }
    lod_level: 0
  }
}

**Comment by smfhn163com** [comment]
> 



> https://github.com/PaddlePaddle/Paddle/blob/release/1.8/paddle/fluid/operators/linear_chain_crf_op.cc#L182 看源码，需要 Length 变量才会走到3-D的分支。

加了length变量，还是提示同样的问题 
InvalidArgumentError: The Input(Emission) should be a 2-D tensor. But received: input rank 3, input shape [-1, 128, 239].

**Comment by smfhn163com** [comment]
> https://github.com/PaddlePaddle/Paddle/blob/release/1.8/paddle/fluid/operators/linear_chain_crf_op.cc#L182 看源码，需要 Length 变量才会走到3-D的分支。

刚刚加入length有问题，修正之后，就OK了
