### ISSUE TITLE
confusion of apis for loading state_dict

### ISSUE THREAD

**Issue by caopulan** [PaddlePaddle/Paddle#38157]
Model (paddle.nn.Layer), optimizer (paddle.optimizer), grad_scaler (paddle.amp.grad_scaler) have different apis for loading state_dict, which may be confused:
- `model.load_dict()`
- `optimizer.set_state_dict()`
- `scaler.load_state_dict()`

Is it available to redefine some apis like this?
```
Class Optimizer():
    def load_dict(self, state_dict):
        self.set_state_dict(state_dict)
```

**Comment by ZHUI** [comment]
Thank for your advices.  Sorry for make you confused about the api usage.
The `Optimizer `, `Scaler ` would be batter to have the same api interface as `nn.Layer`. We will carefully consider your advices.

https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/fluid/dygraph/amp/loss_scaler.py
https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/optimizer/optimizer.py#L49

**Comment by ZHUI** [comment]
It should be `model.set_state_dict()` since model should be `nn.Layer`, and the  `Optimizer `  use `set_state_dict ` api,  the same  as `nn.Layer`.
