### ISSUE TITLE
在paddle中如何对模型进行显存占用分析？

### ISSUE THREAD

**Issue by geoexploring** [PaddlePaddle/Paddle#38193]
在Pytorch中可以利用[torch.cuda.memory_allocated()](https://pytorch.org/docs/stable/generated/torch.cuda.memory_allocated.html?highlight=torch%20cuda%20memory_allocated#torch.cuda.memory_allocated)、[torch.cuda.max_memory_allocated()](https://pytorch.org/docs/stable/generated/torch.cuda.max_memory_allocated.html?highlight=torch%20cuda%20memory_allocated#torch.cuda.max_memory_allocated)和[torch.cuda.memory_reserved()](https://pytorch.org/docs/stable/generated/torch.cuda.memory_reserved.html?highlight=torch%20cuda%20memory_reserved#torch.cuda.memory_reserved)对模型进行显存占用分析，具体可参看[PyTorch显存机制分析](https://zhuanlan.zhihu.com/p/424512257).

但是，我在paddle中没有找到对应的api，请问paddle中有相应的api吗？

谢谢！

**Comment by joey12300** [comment]
你好，paddle暂时没有这种动态的显存占用分析工具。可以使用paddle.summary获取模型显存占用的信息。 https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/summary_cn.html#summary

**Comment by geoexploring** [comment]
@joey12300 , 谢谢！

请问利用paddle实现该功能（动态的显存占用分析），是不是要用到cuda编程呢？

**Comment by joey12300** [comment]
> @joey12300 , 谢谢！
> 
> 请问利用paddle实现该功能（动态的显存占用分析），是不是要用到cuda编程呢？

嗯，可能要通过cuda的一些接口获取这些信息，都要改动底层框架的

**Comment by geoexploring** [comment]
@joey12300 ，谢谢，明白了！

**Comment by Ligoml** [comment]
用户你好，显存优化相关 api 我们已有研发计划，敬请关注~

**Comment by From00** [comment]
@geoexploring 你好，你提到的几个API，目前Paddle中均已进行了支持，将会在Paddle 2.3版本中发布，详见PR：https://github.com/PaddlePaddle/Paddle/pull/38657

感谢对Paddle的关注，若在使用中或自己实现相关功能过程中遇到问题，欢迎再次反馈。

**Comment by geoexploring** [comment]
@From00, @Ligoml,  谢谢两位的关注和持续改进！

也许该功能可以马上用到Paddle相关的下游任务模型库，比如PaddleClas、PaddleSeg等
