### ISSUE TITLE
建议，visualdl 可以自动读取同一个文件夹底下的两个 log 文件

### ISSUE THREAD

**Issue by yt605155624** [PaddlePaddle/Paddle#38205]
有时候训练断掉了，重新开始就会重新生成一个 visualdl 的 log, 但是可视化的时候只能看到后半段的 log，建议 visualdl 可以自动读取同一个文件夹底下的两个 log 文件，或者接着上次的 log 文件写入

**Comment by geoexploring** [comment]
paddleseg也有同样的问题，恢复训练后是重新计算best_model和vdl的log

**Comment by rainyfly** [comment]
您好，VisualDL是支持续写的，在LogWriter初始化的时候，file_name参数写要续写的文件名，会继续续写文件。
<img width="855" alt="infoflow 2021-12-17 14-03-01" src="https://user-images.githubusercontent.com/22424850/146497096-edc4d3f5-f9ec-400e-ade8-34f51242656f.png">
