### ISSUE TITLE
Type of gradient operator does not need to be registered.

### ISSUE THREAD

**Issue by reyoung** [PaddlePaddle/Paddle#3821]
In current code-base, the type of gradient operator does not need to be registered, since

* User should never create a gradient operator in Python by hand. A user should invoke `Backward` method with a forward operator to create gradient operators. So the `type` of gradient operator is not needed.
* If the gradient operator is composed of forwarding operators, we should use `NetOp`(or BlockOp in the future). The sample code is [here](https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/operators/minus_op.cc#L58).

**Comment by Canpio** [comment]
I agree. I will remove the `grad_op_type`.
