### ISSUE TITLE
Get a nullptr or empty for `Op::Input`, `Op::Output`, `ctx::Input` or `ctx::Output`

### ISSUE THREAD

**Issue by reyoung** [PaddlePaddle/Paddle#3822]
Our operators can have empty inputs or outputs, since

* Some input could be null, such as bias of FullyConnected operator.
* Some output could be null, especially for gradient operators. Because a gradient operator may not need to compute all gradients of inputs, e.g., some of the inputs are data.

So, `Op::Input`, `Op::Output`, `ctx::Input`, `ctx::Output` should return nullptr if they are empty.

### The problem is:
The current implementation of ctx::Input(name) supports return nullptr as a return value, **but the implementation is not right and it can not return nullptr rightly**.

take Operator::Input("X") as an example, the right logic is:

1. check if "X" is defined in OpProto as Input, if it's not defined, throw error. if It is defined:
1. check if the map of Op::inputs_ contains "X", if it's not defined, return nullptr.

but the current implementation is:

1. check the map of Op::inputs_ contains "X", if it's not defined, throw an error.

the problem of the current implementation is that, when calling CreateOp, the user may not prepare input for "X", then Op::inputs_ will not contain "X", the current implementation will throw an error but not return nullptr.

**Comment by jacquesqiao** [comment]
所以按我的理解这是一个bugfix，而不是一个feature，因为之前的实现意图和接口是支持返回nullptr的，但是因为实现的不对，导致在某个输入不存在时没有正确的返回nullptr，而是直接挂了。
