### ISSUE TITLE
paddle.jit.save相关问题求助。

### ISSUE THREAD

**Issue by shaitaiyangmie** [PaddlePaddle/Paddle#38234]
您好，请问动态图象保存成inference model，在使用jit.save时报错，想请您帮忙看下这是什么原因呢？感谢！

下图是我调用jit.save的语句。
<img width="724" alt="image" src="https://user-images.githubusercontent.com/73834112/146493374-778ed3b0-a275-4252-afd7-b78507ef95ed.png">

<img width="718" alt="image" src="https://user-images.githubusercontent.com/73834112/146493155-f229eeca-0ecc-4fde-b6b1-9edd6347e486.png">

下面是报错的图。
<img width="1059" alt="image" src="https://user-images.githubusercontent.com/73834112/146493260-5d55fb7c-0ff3-460e-8815-14b04b03a6e6.png">

请问我在定义网络的时候，init中的那些方法和传入的model实例需要做改变吗？

**Comment by ghostxsl** [comment]
你这个init里面的model是啥？感觉你这样写的话，动转静可能trace不到

**Comment by shaitaiyangmie** [comment]
> 你这个init里面的model是啥？感觉你这样写的话，动转静可能trace不到

model是paddlenlp调的ernie1.0，谢谢您，问题已经解决的，我把paddlepaddle更新了一下就ok了。看样子init的model和方法都不用变动。谢谢您。

**Comment by ghostxsl** [comment]
好的～
