### ISSUE TITLE
nvidia jetson编译安装paddle错误

### ISSUE THREAD

**Issue by zuocebianpingmao** [PaddlePaddle/Paddle#38246]
**编译PaddlePaddle版本：**2.2.1
**CPU信息:**
Architecture:        aarch64
Byte Order:          Little Endian
CPU(s):              6
On-line CPU(s) list: 0-5
Thread(s) per core:  1
Core(s) per socket:  2
Socket(s):           3
Vendor ID:           Nvidia
Model:               0
Model name:          ARMv8 Processor rev 0 (v8l)
Stepping:            0x0
CPU max MHz:         1907.2000
CPU min MHz:         115.2000
BogoMIPS:            62.50
L1d cache:           64K
L1i cache:           128K
L2 cache:            2048K
L3 cache:            4096K
Flags:               fp asimd evtstrm aes pmull sha1 sha2 crc32 atomics fphp asimdhp
**系统：**Ubuntu 18.04.4 LTS
**GPU：**cuda：v10.2.89，cudnn：v8.0.0
**python：**3.6.9
**编译命令：**
`cmake .. -DPY_VERSION=3 -DPYTHON_EXECUTABLE=`which python3` -DWITH_ARM=ON -DWITH_TESTING=OFF -DCMAKE_BUILD_TYPE=Release -DON_INFER=ON -DWITH_XBYAK=OFF`
`make TARGET=ARMV8 -j$(nproc)`
**错误信息：**
`[  1%] Built target extern_zlib
[  1%] Built target extern_protobuf
[  1%] Built target extern_gflags
[  1%] copy_if_different /home/econe/Downloads/Paddle/build/paddle/fluid/operators/jit/kernels.h
[  1%] Built target copy_kernels_command
[  1%] copy_if_different /home/econe/Downloads/Paddle/build/paddle/fluid/inference/api/paddle_inference_pass.h
[  1%] Built target copy_paddle_inference_pass_command
[  2%] copy_if_different /home/econe/Downloads/Paddle/build/paddle/fluid/pybind/pybind.h
[  2%] Built target copy_pybind_command
[  2%] Built target extern_glog
[  2%] Built target framework_proto
[  2%] Built target extern_boost
[  2%] Built target flags
[  2%] Built target stringpiece
[  3%] Built target extern_eigen3
[  4%] Built target extern_threadpool
[  4%] Built target extern_dlpack
[  4%] Built target shape_range_info_proto
[  4%] Built target profiler_proto
[  4%] Built target external_error_proto
[  5%] Built target error_codes_proto
[  6%] Built target data_feed_proto
[  6%] Built target trainer_desc_proto
[  6%] Built target pass_desc_proto
[  6%] Built target op_def_proto
[  6%] Built target heter_service_proto
[  6%] Built target extern_xxhash
[  6%] Built target extern_openblas
[  6%] Built target cblas
[  6%] Built target errors
[  6%] Built target enforce
[  6%] Built target dynamic_loader
Scanning dependencies of target dynload_cuda
[  6%] Building CXX object paddle/fluid/platform/dynload/CMakeFiles/dynload_cuda.dir/nvjpeg.cc.o
In file included from /home/econe/Downloads/Paddle/paddle/fluid/platform/dynload/nvjpeg.cc:12:0:
/home/econe/Downloads/Paddle/paddle/fluid/platform/dynload/nvjpeg.h:14:10: fatal error: nvjpeg.h: No such file or directory
 #include <nvjpeg.h>
          ^~~~~~~~~~
compilation terminated.
paddle/fluid/platform/dynload/CMakeFiles/dynload_cuda.dir/build.make:172: recipe for target 'paddle/fluid/platform/dynload/CMakeFiles/dynload_cuda.dir/nvjpeg.cc.o' failed
make[2]: *** [paddle/fluid/platform/dynload/CMakeFiles/dynload_cuda.dir/nvjpeg.cc.o] Error 1
CMakeFiles/Makefile2:5906: recipe for target 'paddle/fluid/platform/dynload/CMakeFiles/dynload_cuda.dir/all' failed
make[1]: *** [paddle/fluid/platform/dynload/CMakeFiles/dynload_cuda.dir/all] Error 2
Makefile:148: recipe for target 'all' failed
make: *** [all] Error 2
`
在nvidia jetson平台上编译的时候出现了这个错误，似乎是缺少了nvjpeg.h，有什么解决办法吗？

**Comment by wangye707** [comment]
@zuocebianpingmao  你好，cmake编译选项需要改下：

**Comment by wangye707** [comment]
@zuocebianpingmao   你好，cmake选项没有开 nv_jetson参数，可以参考这个：cmake .. -DCMAKE_CXX_FLAGS='-Wno-error -w'  -DWITH_CONTRIB=OFF   -DWITH_MKL=OFF    -DWITH_MKLDNN=OFF   -DWITH_TESTING=ON   -DCMAKE_BUILD_TYPE=Release   -DON_INFER=ON   -DWITH_PYTHON=ON -DPY_VERSION=3.6  -DWITH_XBYAK=OFF  -DWITH_NV_JETSON=ON -DWITH_TENSORRT=ON -DTENSORRT_ROOT=/usr -DCMAKE_CUDA_COMPILER=/usr/local/cuda-10.2/bin/nvcc  -DWITH_NCCL=OFF -DCUDA_ARCH_NAME=All

**Comment by zuocebianpingmao** [comment]
> @zuocebianpingmao 你好，cmake选项没有开 nv_jetson参数，可以参考这个：cmake .. -DCMAKE_CXX_FLAGS='-Wno-error -w' -DWITH_CONTRIB=OFF -DWITH_MKL=OFF -DWITH_MKLDNN=OFF -DWITH_TESTING=ON -DCMAKE_BUILD_TYPE=Release -DON_INFER=ON -DWITH_PYTHON=ON -DPY_VERSION=3.6 -DWITH_XBYAK=OFF -DWITH_NV_JETSON=ON -DWITH_TENSORRT=ON -DTENSORRT_ROOT=/usr -DCMAKE_CUDA_COMPILER=/usr/local/cuda-10.2/bin/nvcc -DWITH_NCCL=OFF -DCUDA_ARCH_NAME=All

谢谢

**Comment by jiguanglu** [comment]
mark！
