### ISSUE TITLE
下载VGG19预训练模型的出现 ERROR 404: Not Found

### ISSUE THREAD

**Issue by abcxq** [PaddlePaddle/Paddle#38254]
我在运行aistudio上的项目“GAN的应用 -- SRGAN图像超分辨率重构”的时候遇到一个问题（网址：https://aistudio.baidu.com/aistudio/projectdetail/3202351?contributionType=1）。项目中原来获取VGG19预训练模型的命令“wget  https://paddle-gan-models.bj.bcebos.com/vgg19_spade.tar.gz”运行后出现如下错误

--2021-12-17 19:29:56-- https://paddle-gan-models.bj.bcebos.com/vgg19_spade.tar.gz
Resolving paddle-gan-models.bj.bcebos.com (paddle-gan-models.bj.bcebos.com)... 182.61.200.229, 182.61.200.195, 2409:8c04:1001:1002:0:ff:b001:368a
Connecting to paddle-gan-models.bj.bcebos.com (paddle-gan-models.bj.bcebos.com)|182.61.200.229|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2021-12-17 19:29:56 ERROR 404: Not Found.

请问从哪里获取这个预训练模型呢？

**Comment by ghostxsl** [comment]
建议您去paddleGAN 咨询一下这个问题：https://github.com/PaddlePaddle/PaddleGAN/issues
