### ISSUE TITLE
【论文复现】张量超过两次复制会报张量没有梯度的问题

### ISSUE THREAD

**Issue by KiritoSSR** [PaddlePaddle/Paddle#38251]
PaddlePaddle版本：2.2.1
CUDA：10.2
我现在遇到赋值次数超过两次就会在反向传播的时候，就会报错说向量找不到梯度，代码如下：
            roi_aligned_feats = self.obj_downsample(feats_to_downsample) #[9,512]
            lengths = box_mask.sum(1).tolist() #[4,2,3]
            output = paddle.zeros([len(lengths), max(lengths), *roi_aligned_feats.shape[1:]], dtype=roi_aligned_feats.dtype) #[3,4,512]
            start = 0
            for i, diff in enumerate(lengths):
                     if diff > 0:
                         output[i, :diff] = roi_aligned_feats[start:(start + diff)].clone()
                    start += diff
作用是将roi_aligned_feats按行分成长度等于 lengths 中长度的张量，对于长度不足max(lengths)的为0。
但是在len(lengths)>2的时候会报错
RuntimeError: (NotFound) Cannot find gradient of variable generated_tensor_27@GRAD
  [Hint: Expected iter != accumulators_.end() == true, but received iter != accumulators_.end():0 != true:1.] (at/paddle/paddle/fluid/imperative/basic_engine.cc:445)

**Comment by ghostxsl** [comment]
你这么写是inplace的，计算图trace不到节点的，你可以用split实现你的想法，获取outputs

**Comment by KiritoSSR** [comment]
那为什么len(lengths)<=2的时候，程序可以正常进行反向传播？

**Comment by KiritoSSR** [comment]
> 你这么写是就地的，计算trace不到节点的，可以用split实现你的图，获取输出

那为什么当len(lengths)<=2的时候，可以正常进行反向传播？

**Comment by ghostxsl** [comment]
我是这么理解的，你new一个tensor，将一个图内的节点赋值给它，这个没啥问题，但是你通过[]操作去赋值，你下个节点的梯度信息会覆盖掉上个的信息，导致在反传的时候报错找不到梯度信息

**Comment by KiritoSSR** [comment]
> 我是这么理解的，你一个新的张量，但是将一个图内的这个节点交付给它，没有啥问题，你通过[操作]去启动，你下个节点的良好信息会覆盖掉上个，导致在反传的时候报错找不到信息

好的，谢谢！
