### ISSUE TITLE
ValueError: (InvalidArgument) shape should have the save dim with perm, but received shape size is:4, penm size is:3

### ISSUE THREAD

**Issue by geoyee** [PaddlePaddle/Paddle#38267]
- 标题：ValueError: (InvalidArgument) shape should have the save dim with perm, but received shape size is:4, penm size is:3

- 版本、环境信息：
    1）PaddlePaddle版本：PaddlePaddle-GPU 2.2.0
    2）CPU：/
    3）GPU：RTX 2060、CUDA版本号：10.2，CUDNN版本号：7.6
    4）系统环境：Win10，Python版本：3.8.10

- 训练信息
    1）单机单卡
    2）显存信息：/
    3）Operator信息：/

- 问题描述：
从pytorch复现了一个网络（非论文，另外的人搭的），前向顺利没有问题，但反向传播的时候报了这个错误，请问如何定位这个问题具体在哪儿，以及其的可能出现原因。
![image](https://user-images.githubusercontent.com/71769312/146675327-c46fdf2f-497f-417c-ad71-d90471551bf4.png)

**Comment by RainFrost1** [comment]
可以先试一下，将网络不断二分，确定出现问题的网络层。找到相应的网络层之后，检查是否是相应的网络层出了问题

**Comment by geoyee** [comment]
> 可以先试一下，将网络不断二分，确定出现问题的网络层。找到相应的网络层之后，检查是否是相应的网络层出了问题

收到，感谢，我先试试定位问题

**Comment by geoyee** [comment]
@RainFrost1 结合报错
```
ValueError: (InvalidArgument)  shape should have the save dim with perm, but received shape size is:4, perm size is:3.
  [Hint: Expected shape.size() == perm.size(), but received shape.size():4 != perm.size():3.] (at C:/home/workspace/Paddle_release/paddle/fluid/operators/transpose_op.cu:565)
```
经过检查确定问题出在`paddle.transpose`，我找到了所有有transpose的地方，确定了问题在这个ECA的代码（不使用就能正常反向传播）
``` python
class ECA(nn.Layer):
    """ ECA-Net: Efficient Channel Attention.
        https://arxiv.org/abs/1910.03151
    Args:
        in_channels: Number of channels of the input feature map
        k_size: Adaptive selection of kernel size
    """
    def __init__(self, in_channels, k_size=3):
        super(ECA, self).__init__()
        self.avg_pool = nn.AdaptiveAvgPool2D(1)
        self.conv = nn.Conv1D(1, 1, kernel_size=k_size, padding=(k_size - 1) // 2, bias_attr=False)
        self.sigmoid = nn.Sigmoid()

    def forward(self, x):
        # x: input features with shape [b, c, h, w]
        b, c, h, w = x.shape
        # feature descriptor on the global spatial information
        y = self.avg_pool(x)
        # Two different branches of ECA module
        y = paddle.squeeze(y, axis=-1)
        y = paddle.transpose(y, perm=[0, 2, 1])
        y = self.conv(y)
        y = paddle.transpose(y, perm=[0, 2, 1])
        paddle.unsqueeze_(y, axis=-1)
        # Multi-scale information fusion
        y = self.sigmoid(y)
        y = paddle.expand_as(y, x)
        return x * y
```
但是检查前向的结果我也看不出有什么问题，`perm.shape`和`y.shape`相同，不知道为什么在反向传播中报错`received shape.size():4 != perm.size():3`，这个我感觉与我看到这个这个相似[https://gitee.com/ascend/modelzoo/issues/I2CJGY](https://gitee.com/ascend/modelzoo/issues/I2CJGY)

**Comment by RainFrost1** [comment]
上面ECA这个代码也会因为transpose的问题，出现不能反向传播的问题，对吧？我定位一下

**Comment by RainFrost1** [comment]
我试了一下ECA net，将其插入到一个普通网络的层中，能够正常的计算loss，并反向传播。可能还需要再详细定位一下吧

**Comment by geoyee** [comment]
@RainFrost1  感谢，已解决，将这个里面的`paddle.unsqueeze_(y, axis=-1)`换成了`y = paddle.unsqueeze(y, axis=-1)`就可以了，前向反向就能跑了

**Comment by geoyee** [comment]
不知道是说没用`y=`进行保存，还是说`unsqueeze_`和`unsqueeze`有什么区别，总之解决了，感谢帮助，我想这个issue我可以关闭了
