### ISSUE TITLE
paddle安装错误 报numpy版本错误

### ISSUE THREAD

**Issue by ff12343** [PaddlePaddle/Paddle#38269]
- 版本、环境信息：
    1）PaddlePaddle版本：paddlepaddle-gpu==2.2.1
    2）python：3.7
    3）系统环境：win10 conda环境

- 安装方式信息：
1）conda环境中 conda 安装

- 报错信息
ImportError: 

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy c-extensions failed.
- Try uninstalling and reinstalling numpy.
- If you have already done that, then:
  1. Check that you expected to use Python3.7 from "D:\WorkSpace\Anaconda\envs\paddle_env_gpu\python.exe",
     and that you have no directories in your PATH or PYTHONPATH that can
     interfere with the Python and numpy version "1.18.1" you're trying to use.
  2. If (1) looks fine, you can open a new issue at
     https://github.com/numpy/numpy/issues.  Please include details on:
     - how you installed Python
     - how you installed numpy
     - your operating system
     - whether or not you have multiple versions of Python installed
     - if you built from source, your compiler versions and ideally a build log

- If you're working with a numpy git repository, try `git clean -xdf`
  (removes all files not under version control) and rebuild numpy.

Note: this error has many possible causes, so please don't comment on
an existing issue about this - open a new one instead.

Original error was: DLL load failed: 找不到指定的模块。

- 测试
按报错信息是numpy和python版本不合，测试过numpy==1.18.1，也更新过新版numpy==2.21，都报相同错

**Comment by ff12343** [comment]
python 版本不能变，因为py3.8和3.9会报cuda错误，只有py3.7的cuda才可以工作；请问要怎么该设置numpy版本合适呢

**Comment by ff12343** [comment]
提供一下完整报错信息：
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
D:\WorkSpace\Anaconda\envs\paddle_env_gpu\lib\site-packages\numpy\core\__init__.py in <module>
     23 try:
---> 24     from . import multiarray
     25 except ImportError as exc:

D:\WorkSpace\Anaconda\envs\paddle_env_gpu\lib\site-packages\numpy\core\multiarray.py in <module>
     13 
---> 14 from . import overrides
     15 from . import _multiarray_umath

D:\WorkSpace\Anaconda\envs\paddle_env_gpu\lib\site-packages\numpy\core\overrides.py in <module>
      6 
----> 7 from numpy.core._multiarray_umath import (
      8     add_docstring, implement_array_function, _get_implementing_args)

ImportError: DLL load failed: 找不到指定的模块。

During handling of the above exception, another exception occurred:

ImportError                               Traceback (most recent call last)
~\AppData\Local\Temp/ipykernel_4700/1391245030.py in <module>
----> 1 import paddlex as pdx
      2 import time
      3 import cv2
      4 im = cv2.imread('20210426_105748_img.jpg')
      5 left_img_name = 'C:\\Users\\28104\\jupyter_project\\opencv\\calib_result\\stereo_Imgs\\left3.jpg'

D:\WorkSpace\Anaconda\envs\paddle_env_gpu\lib\site-packages\paddlex\__init__.py in <module>
     15 __version__ = '2.0.0'
     16 
---> 17 from paddlex.utils.env import get_environ_info, init_parallel_env
     18 init_parallel_env()
     19 

D:\WorkSpace\Anaconda\envs\paddle_env_gpu\lib\site-packages\paddlex\utils\__init__.py in <module>
     13 # limitations under the License.
     14 
---> 15 from . import logging
     16 from . import utils
     17 from .utils import (seconds_to_hms, get_encoding, get_single_card_bs, dict2str,

D:\WorkSpace\Anaconda\envs\paddle_env_gpu\lib\site-packages\paddlex\utils\logging.py in <module>
     19 from colorama import init
     20 import paddlex
---> 21 import paddle
     22 
     23 init(autoreset=True)

D:\WorkSpace\Anaconda\envs\paddle_env_gpu\lib\site-packages\paddle\__init__.py in <module>
     23 
     24 from .batch import batch  # noqa: F401
---> 25 from .fluid import monkey_patch_variable
     26 from .fluid.dygraph import monkey_patch_math_varbase
     27 monkey_patch_variable()

D:\WorkSpace\Anaconda\envs\paddle_env_gpu\lib\site-packages\paddle\fluid\__init__.py in <module>
     34 
     35 # import all class inside framework into fluid module
---> 36 from . import framework
     37 from .framework import *
     38 # import all class inside executor into fluid module

D:\WorkSpace\Anaconda\envs\paddle_env_gpu\lib\site-packages\paddle\fluid\framework.py in <module>
     27 from types import MethodType, FunctionType
     28 
---> 29 import numpy as np
     30 import subprocess
     31 import multiprocessing

D:\WorkSpace\Anaconda\envs\paddle_env_gpu\lib\site-packages\numpy\__init__.py in <module>
    140     from . import _distributor_init
    141 
--> 142     from . import core
    143     from .core import *
    144     from . import compat

D:\WorkSpace\Anaconda\envs\paddle_env_gpu\lib\site-packages\numpy\core\__init__.py in <module>
     52 """ % (sys.version_info[0], sys.version_info[1], sys.executable,
     53         __version__, exc)
---> 54     raise ImportError(msg)
     55 finally:
     56     for envkey in env_added:

**Comment by RainFrost1** [comment]
请问这个具体是怎么解决的呢
