### ISSUE TITLE
Ubuntu下QGIS的Python环境使用PaddlePaddle报错

### ISSUE THREAD

**Issue by geoyee** [PaddlePaddle/Paddle#38268]
- 标题：Ubuntu下QGIS的Python环境使用paddlepaddle报错

- 版本、环境信息：
    1）PaddlePaddle版本：PaddlePaddle 2.2.1
    2）CPU：AMD A8-7410 apu，使用MKLDNN
    3）GPU：/
    4）系统环境：Ubuntu 20.04.3 LTS，Python版本：QGIS 2.22 自带的Pyhton 3.8.10

- 问题描述：
QGIS是最大的开源GIS平台，我们基于PaddlePaddle的深度学习能力制作了一个QGIS插件，使用分割模型提取遥感影像中的建筑区域【github链接：[https://github.com/deepbands/buildseg](https://github.com/deepbands/buildseg)】。该插件能够在Windows 10/11上正常使用，但在Ubuntu以及Big Sur上都无法使用，且报错显示均与PaddlePaddle的使用有关。
我们直接使用`pip3 install paddlepaddle`安装的paddlepaddle，使用同样的方法安装opencv-python，当在QGIS中的Python控制台导入时。`import cv2`工作正常，而`import paddle`出现错误如下图：
![~W{XA78R1%QNB3Q_JQCFOWG](https://user-images.githubusercontent.com/71769312/146676106-df236ac2-00f6-44e5-ab60-8a37674b8d22.jpg)
确定后再次尝试导入报错如下图：
![THG1$VU2M5J})G_$UVK{9J4](https://user-images.githubusercontent.com/71769312/146676113-0aa259f7-1e34-4dbf-9e23-0c6b618364d2.jpg)
但在终端使用paddle表明没有问题，如下图：
![V(6ZDKQ9AHRI0(_FEV8UFQ3](https://user-images.githubusercontent.com/71769312/146676127-0d0f46d1-a870-4875-aaab-0e696aa4c186.jpg)
希望官方能够帮助我们解决这个问题，这样才能使PaddlePaddle应用在更多的地方。

**Comment by RainFrost1** [comment]
看着报错是Protocol Buffer  版本不匹配。Paddle 用的是3.1.0，而安装的3.6.1。建议重新安装Protocol Buffer试一下

**Comment by geoyee** [comment]
> 看着报错是Protocol Buffer 版本不匹配。Paddle 用的是3.1.0，而安装的3.6.1。建议重新安装Protocol Buffer试一下

我尝试使用`pip3 install protocbuf==3.1.0`，然后再在QGIS中导入paddle。第一次使用`import paddle`界面会卡住，拖动界面后可以再次导入paddle，这时候导入报错，使用`paddle.__version__`可以查看版本，但`paddle.utils.run_check()`无法使用，图片如下：
![8f35b445754c03a33c3023de913a820](https://user-images.githubusercontent.com/71769312/146791018-2b198667-3e6d-46e8-a6fc-d25c8031b520.jpg)

**Comment by RainFrost1** [comment]
重新安装paddle，或者安装其他版本paddle试一下

**Comment by geoyee** [comment]
1. 先尝试卸载paddle和protobuf，然后先安装protobuf 3.1.0，再安装paddle 2.2.1，无效，如下图
![V$7O@I(N1YWDLK40_R9{813](https://user-images.githubusercontent.com/71769312/146866021-fe765295-e5c4-4707-bca2-84ca9ede741f.jpg)

2. 先尝试卸载paddle和protobuf，然后先安装protobuf 3.1.0，再安装paddle 2.1.0，无效，如下图
![5G39VLA{VLLK0H8@2{FMK~P](https://user-images.githubusercontent.com/71769312/146866064-31466466-0cfe-415f-b0a7-cbfd131f063b.jpg)

**并且目前状态都一样**
1. 第一次使用`import paddle`，界面卡住，enter一下后界面可以活动，再次导入paddle，如果不可以就是上图一报错
2. 如果这里没有报错，打印`paddle.__version__`，2.2.1或2.1.0版本都能正确打印，但使用`paddle.utils.run_check()`报错如上图二。`import paddle.nn as nn`也报错，报错信息如下图
![6AEZI$PEI)$7M69LK$ZF7N](https://user-images.githubusercontent.com/71769312/146866524-746b7456-6544-4c66-821b-4307b0299033.jpg)

目前那台机器上什么都没装，也没法科学上网，所以图片都是手机拍的，如果需要文字或截图的效果，我再重新弄一下

**Comment by RainFrost1** [comment]
之前确实没有碰到过这种情况。运行代码前，可以先设置环境变量export FLAGS_call_stack_level=2。看一下详细的报错信息

**Comment by geoyee** [comment]
谢谢，但我在终端设置后进入QGIS导入报错显示没有什么区别。并且在有protobuf 3.1.0的情况下有时还是会报那个3.6.1的错

**Comment by RainFrost1** [comment]
看着感觉应该是底层c++的protobuf版本不一致。不是在python中pip安装protobuf。试试[这个](https://blog.csdn.net/kdchxue/article/details/81046192)安装方法呢，3.1.0版本

**Comment by geoyee** [comment]
> 看着感觉应该是底层c++的protobuf版本不一致。不是在python中pip安装protobuf。试试[这个](https://blog.csdn.net/kdchxue/article/details/81046192)安装方法呢，3.1.0版本

感谢，我会尝试一下

**Comment by geoyee** [comment]
> > 看着感觉应该是底层c++的protobuf版本不一致。不是在python中pip安装protobuf。试试[这个](https://blog.csdn.net/kdchxue/article/details/81046192)安装方法呢，3.1.0版本
> 
> 感谢，我会尝试一下

我看了下我的windows下面是3.19.1的，我照着这个链接装了一个3.19.1的，现在没有显示任何报错，QGIS直接闪退了

**Comment by RainFrost1** [comment]
windows下没有报错，对吧？看ubuntu下报错，应该是装3.1.0版本，而不是3.19.1吧

**Comment by geoyee** [comment]
是的，windows10/11下都没问题，就是3.19.1的。在ubuntu下他自带一个3.6.1的卸载不掉，我使用pip安装的3.1.0的也没用，然后那个链接是装的最新的，我也试了下，就没有显示版本问题了，但是直接崩了



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2021年12月24日 10:29 |
| 收件人 | ***@***.***> |
| 抄送至 | Yizhou ***@***.******@***.***> |
| 主题 | Re: [PaddlePaddle/Paddle] Ubuntu下QGIS的Python环境使用PaddlePaddle报错 (Issue #38268) |

windows下没有报错，对吧？看ubuntu下报错，应该是装3.1.0版本，而不是3.19.1吧

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by linhandev** [comment]
Arch linux 下安装qgis，在命令行里 import paddle是下面这样的

![image](https://user-images.githubusercontent.com/29757093/147329341-7dbb6cd4-0045-43b1-b81b-8f571f624ae2.png)

**Comment by linhandev** [comment]
感觉这个问题貌似和qgis执行py的方式有关系，在qgis上发现了一个[有意思的issue](https://github.com/qgis/QGIS/issues/37289)。说是一个包在qgis里import不了，结果子进程里就能import

尝试了一下，Manjaro Linux下直接import paddle导致qgis崩溃
![image](https://user-images.githubusercontent.com/29757093/147331579-919373c0-b83a-4df0-9a0f-ad8316e6f633.png)

照着那个issue的样子写了两个文件

```python
import subprocess
import sys

sys.executable = "python"
args = [
    sys.executable,
    "/path/to/test_import.py",
]

child_proccess = subprocess.Popen(args, stdin=subprocess.PIPE, stdout=subprocess.PIPE)
print("opened")

child_process_output = child_proccess.communicate()

print(child_process_output)
```
test_import.py
```shell
print("before")

import paddle

print(paddle.__version__)
paddle.utils.run_check()

print("after")

```
执行结果

![image](https://user-images.githubusercontent.com/29757093/147331729-083f4b14-1b01-4d92-be3c-be35f31cb6a8.png)

ubuntu上测试也是类似的情况

![image](https://user-images.githubusercontent.com/29757093/147332849-2eae3282-78af-48bf-bf70-5de844554b08.png)

@geoyee

**Comment by yharby** [comment]
![paddle1](https://user-images.githubusercontent.com/13020265/147348575-dad8ee4b-b657-43a6-b73d-dedbd843a2a5.gif)

**Comment by yharby** [comment]
Full Crash Report
https://drive.google.com/drive/folders/1VwaeQfJoSZSKFpuAq3guk3XgsJrUHSSP?usp=sharing
