### ISSUE TITLE
安装错误: paddlepaddle pip 重新安装后会出现 --gpu unrecognised arguments

### ISSUE THREAD

**Issue by CunjunYin** [PaddlePaddle/Paddle#38265]
****************************************
Paddle version: 2.2.1
Paddle With CUDA: False

OS: Ubuntu 20.04
Python version: 3.8.10

CUDA version: 11.2.152
Build cuda_11.2.r11.2/compiler.29618528_0
cuDNN version: None.None.None
Nvidia driver version: 495.44
****************************************

- 安装方式信息：
1) pip3 install paddlepaddle | pip3 install paddlepaddle-gpu
2) pip3 uninstall paddlepaddle -y | pip3 uninstall paddlepaddle-gpu -y
3) pip3 install paddlepaddle | pip3 install paddlepaddle-gpu

Training script: from FleetX
python3 -m paddle.distributed.launch --gpus="..." --ips="........" --host=... train_fleet_static.py

**Comment by RainFrost1** [comment]
请问具体用了哪些版本的库及相应的训练代码呢？能否详细描述一下

**Comment by CunjunYin** [comment]
训练代码 
https://github.com/PaddlePaddle/FleetX
examples/resnet/train_fleet_static.py

$ pip3 list
Package                 Version             
paddlepaddle               2.2.1               
paddlepaddle-gpu        2.2.1

**Comment by RainFrost1** [comment]
用的paddle的cpu版本，还是gpu版本呢？看你的环境，`Paddle With CUDA: False`，应该是用的cpu版本，那么用gpus参数估计会报错

**Comment by CunjunYin** [comment]
那怎改变Paddle With CUDA: False => Paddle With CUDA: True， 只要卸载paddlepaddle, paddlepaddle-gpu后, 再重装就会出现这个问题.

**Comment by RainFrost1** [comment]
根据paddle[官网](https://www.paddlepaddle.org.cn/)安装对应版本的paddle，如你的CUDA版本是11.2，那么安装方式如下：python -m pip install paddlepaddle-gpu==2.2.1.post112 -f https://www.paddlepaddle.org.cn/whl/linux/mkl/avx/stable.html。如果还是出现问题的话，应该就是cuda、cudnn等环境出问题了，就不太好定位了，那么可直接使用官方docker镜像
