### ISSUE TITLE
bert

### ISSUE THREAD

**Issue by wangjiancheng-123** [PaddlePaddle/Paddle#38286]
为什么bert类论文的源码没有main函数，其他类型的就有，是需要自己写吗

**Comment by gongel** [comment]
你好，请问你指的是哪个代码呢？

**Comment by gongel** [comment]
可以这么使用哈：https://github.com/PaddlePaddle/PaddleNLP/blob/develop/paddlenlp/transformers/bert/modeling.py#L483
写法可以参考bert的写法

**Comment by wangjiancheng-123** [comment]
好的，谢谢
