### ISSUE TITLE
OpInfo should contain Input/Output name set

### ISSUE THREAD

**Issue by reyoung** [PaddlePaddle/Paddle#3829]
Currently, our operators use the parameter name of input/output to get the input/output variable names. For example, we are using `Input("X")`, `Input("W")`, and `Input("B")` in fully connected operator to get the data, weight matrix and bias. But using string is easy to get wrong, our framework should check whether that parameter name is registered in `OpInfo` or not. The parameter name is saved in [`OpProto.Var.name`](https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/framework/framework.proto#L43). 

We can do this by searching the parameter name in `OpProto` directly. However, this implementation has several issues:

1. The time complexity for validating a parameter name directly by `OpProto` is O(n), which n is the number of inputs/outputs since it is stored in a linear list.
1. Gradient operators do not have `OpProto`.

The simpler way is to add `input_params` and `output_params` sets to `OpInfo` as follow:

```cpp
struct OpInfo {
  set<string> input_params;
  set<string> output_params;
};
```

The `OpInfo` should be constructed while registering operator. It works well for both forwarding and backward operators.

**Comment by Canpio** [comment]
We have recorded operators' inputs/outputs information in `OpProto`, so I think it's not necessary to record it again in `OpInfo`. If users don't assign any variables to some inputs/outputs, just leave the corresponding name vector in Op object's inputs/outputs map empty.

**Comment by reyoung** [comment]
@Canpio That's right.
