### ISSUE TITLE
paddle2.0.2gpu版本出core

### ISSUE THREAD

**Issue by hohdiy** [PaddlePaddle/Paddle#38305]
![image](https://user-images.githubusercontent.com/20314800/146865464-fbab459d-2057-4e25-8eed-3b3d16cec471.png)
import paddle.nn as nn
a = nn.Linear(2,1)
a.

在jupyternotebook中，使用 点 命令触发自动列举对应可用函数时触发，必现。

paddle 2.1.2 和 paddle 2.2.1中均无复现。

**Comment by hohdiy** [comment]
可以登录aistudio， 任意启动一个notebook gpu版本的，paddle选2.0.2即可，很容易复现

**Comment by minghaoBD** [comment]
> import paddle.nn as nn
> a = nn.Linear(2,1)
> a.

您好，我这边在2.0.2环境下，已经复现您的问题，正在调试中。

**Comment by minghaoBD** [comment]
谢谢发现我们的问题！建议您使用别的paddle版本绕过这个问题。
我们在同步解决这个core的问题了 : )

**Comment by hohdiy** [comment]
收到感谢

**Comment by xinliyangguang** [comment]
在paddle cloud中使用PaddleSeg-releasev2.0的模型进行训练也会出这个问题

**Comment by Ligoml** [comment]
这个问题建议更新最新版 paddle 解决哈~在2.1 2.2中均不会出现这个问题了
