### ISSUE TITLE
mips 编译卡Built target analysis_predictor，无报错

### ISSUE THREAD

**Issue by Gmgge** [PaddlePaddle/Paddle#38300]
- 版本、环境信息：
    1）PaddlePaddle版本：2.0
    2）CPU：Loongson-3A4000
    3）GPU：无
    4）系统环境：Kylin Linux Advanced Server release V10 (Tercel)  localdomain 4.19.90-21.3.ky10.mips64el   内存8G
    5）python：3.6.8
- 安装方式信息： 
    1）本地编译：根据官网文档  cmake .. -DPY_VERSION=3 -DPYTHON_EXECUTABLE=`which python3` -DWITH_MIPS=ON -DWITH_TESTING=OFF -DCMAKE_BUILD_TYPE=Release -DON_INFER=ON -DWITH_XBYAK=OFF -DWITH_MKL=OFF 
     make -j4
    - 问题描述：无任何报错，卡在[ 52%] Built target analysis_predictor 尝试过最新的2.2版本，依然是卡在这个构建上。

**Comment by minghaoBD** [comment]
卡死可能是网络链接问题，导致一些依赖包的下载卡住了。

可以参照这里寻找对应的whl包安装（nightly built develop是每天编译的develop分支）https://www.paddlepaddle.org.cn/install/quick?docurl=/documentation/docs/zh/develop/install/pip/linux-pip.html

**Comment by Gmgge** [comment]
1.好像找不到mips的whl包；
2.我更改了第三方源的git地址，应该没有问题的；
3.我使用的cmake 3.12 gcc 8.3.1 是否是这个原因 ？提示gcc的版本可能过高了，cmake的话我看到最低3.10应该没有问题？但是我在别的问题下发现有人推荐cmake3.16.

**Comment by minghaoBD** [comment]
> 1.好像找不到mips的whl包； 2.我更改了第三方源的git地址，应该没有问题的； 3.我使用的cmake 3.12 gcc 8.3.1 是否是这个原因 ？提示gcc的版本可能过高了，cmake的话我看到最低3.10应该没有问题？但是我在别的问题下发现有人推荐cmake3.16.

看了下cmake3.16那个bug，应该跟卡死无关的。建议在卡住后kill，然后执行make -j1看看卡到哪一步了。再具体分析下

**Comment by Gmgge** [comment]
找到了，卡在pybind，它check了2.4.3版本，需要去找clang，我没有把他同步到gitee里面，同步过来就好了。

**Comment by GreenHandZhu** [comment]
> 找到了，卡在pybind，它check了2.4.3版本，需要去找clang，我没有把他同步到gitee里面，同步过来就好了。

请问这个具体是怎么操作的呢？我将third_party的下载源都转为国内镜像了，但是clang-cindex-python3这个一直默认使用 https://gitee.com/wjakob/clang-cindex-python3去下载，怎么修改 clang-cindex-python3 的下载源呢

**Comment by Gmgge** [comment]
@GreenHandZhu  gitee现在需要审核才能公开，可能该链接没有申请，你自己github上面同步一个过来吧。

**Comment by GreenHandZhu** [comment]
> @GreenHandZhu gitee现在需要审核才能公开，可能该链接没有申请，你自己github上面同步一个过来吧。

@Gmgge 我找了一个可以正常下载pybind的gitee源，但是pybind好像都依赖clang-cindex-python3这个，并且pybind默认使用 https://gitee.com/wjakob/clang-cindex-python3 这个链接去下载 clang-cindex-python3。在pybind找不到定义有关下载 clang-cindex-python3 的默认链接

**Comment by Gmgge** [comment]
@GreenHandZhu  很久没有搞这个，刚看了下
更具体的操作是原始的pybind里面
![image](https://user-images.githubusercontent.com/48548141/180745413-d1117e89-2d71-4427-8c9a-9ae1f09d2d4d.png)
clang是一个链接，你把这个链接下载下来，再上传到你的pybind库，把他变成文件
![image](https://user-images.githubusercontent.com/48548141/180745555-c3c81c6e-19e2-4225-baf7-7dcd6354495b.png)

ps 你需要自己在gitee上面同步一个pybind，这样就可以想怎么改就怎么改了，这个应该会把？

**Comment by GreenHandZhu** [comment]
> @GreenHandZhu 很久没有搞这个，刚看了下 更具体的操作是原始的pybind里面 ![image](https://user-images.githubusercontent.com/48548141/180745413-d1117e89-2d71-4427-8c9a-9ae1f09d2d4d.png) clang是一个链接，你把这个链接下载下来，再上传到你的pybind库，把他变成文件 ![image](https://user-images.githubusercontent.com/48548141/180745555-c3c81c6e-19e2-4225-baf7-7dcd6354495b.png)
> 
> ps 你需要自己在gitee上面同步一个pybind，这样就可以想怎么改就怎么改了，这个应该会把？

@Gmgge  感谢哈 后面发现clang-cindex-python3是pybind11的submodules,只要自己的镜像修改下pybind11中.gitsubmodules中clang的url应该就可以。和你给的方案一样。

**Comment by FlickerMi** [comment]
我修改了clang-cindex-python3的源为gitee了。
可以看看这个库的build_cn分支代码：https://gitee.com/FlickerMi/Paddle
