### ISSUE TITLE
自定义Dataloader使用enumerate函数时报错

### ISSUE THREAD

**Issue by Gray-OREO** [PaddlePaddle/Paddle#38333]
在使用paddle自定义Dataset之后通过Dataloader函数单进程单线程导入训练数据时，在dataloader_iter中报错，此时传入self._feed_list为batch_size整型数字，无法迭代。

/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dataloader/dataloader_iter.py in _init_thread(self)
      175 
      176     def _init_thread(self):
--> 177         self._var_names = [v.name for v in self._feed_list]
TypeError: 'int' object is not iterable

经本地调试及通过官网文档例子调试发现，在正常情况下，在进入reader中时，feed_list为None或[]，但是我自定义的Dataloader在进入时间，feed_list便被初始化为等于batch_size的整型数字，请问是什么地方出了问题呢？
十分感谢！

**Comment by minghaoBD** [comment]
能否提供下您的代码？我这边复现debug一下。

**Comment by Gray-OREO** [comment]
> 能否提供下您的代码？我这边复现debug一下。

`import paddle
from paddle.io import DataLoader
from paddle.io import Dataset
from paddle.io import BatchSampler
from paddle.vision import ToTensor
from paddle.vision import transforms
import paddle.nn as nn
from scipy import stats
import skvideo.io
from PIL import Image
import os
import h5py
import numpy as np
import random
import pandas as pd
import paddle.nn.functional as F
from argparse import ArgumentParser



class VQADataset(Dataset):
    """Read data from the original dataset for feature extraction"""

    def __init__(self, videos_dir, video_names, score, video_format='RGB', width=None, height=None):

        super(VQADataset, self).__init__()
        self.videos_dir = videos_dir
        self.video_names = video_names
        self.score = score
        self.format = video_format
        self.width = width
        self.height = height

    def __len__(self):
        return len(self.video_names)

    def __getitem__(self, idx):
        # video_name = self.video_names[idx]
        # assert self.format == 'YUV420' or self.format == 'RGB'
        # if self.format == 'YUV420':
        #     video_data = skvideo.io.vread(os.path.join(self.videos_dir, video_name), self.height, self.width,
        #                                   inputdict={'-pix_fmt': 'yuvj420p'})
        # else:
        #     video_data = skvideo.io.vread(os.path.join(self.videos_dir, video_name))
        # video_score = self.score[idx]

        video_data = np.random.randint(0,256,size=(199, 540, 960, 3))
        video_score = np.random.randint(0, 1)
        '''
        video_data : ndarray
        ndarray of dimension (T, M, N, C), where T
        is the number of frames, M is the height, N is
        width, and C is depth.
        '''

        transform = transforms.Compose([
            ToTensor(),
            transforms.Normalize(mean=[0.485, 0.456, 0.406],
                        std=[0.229, 0.224, 0.225])
        ])

        video_length = video_data.shape[0]
        video_channel = video_data.shape[3]
        video_height = video_data.shape[1]
        video_width = video_data.shape[2]
        transformed_video = paddle.zeros([video_length, video_channel, video_height, video_width])
        padding_video = paddle.zeros([3, 240, 540, 960])
        for frame_idx in range(video_length):
            frame = video_data[frame_idx]
            frame = Image.fromarray(frame)
            frame = transform(frame)
            transformed_video[frame_idx] = frame
        transformed_video = paddle.reshape(transformed_video, [video_channel, video_length, video_height, video_width])
        # padding_video = F.pad(transformed_video, pad=(0,960-video_width,0,540-video_height,0,240-video_length), mode="constant",value=0)
        padding_video[0:video_channel, 0:video_length, 0:video_height, 0:video_width] = transformed_video
        return padding_video, video_score


if __name__ == '__main__':
    parser = ArgumentParser(description='VQA-T')
    parser.add_argument("--seed", type=int, default=19980427)
    parser.add_argument('--database', default='KoNViD-1k', type=str,
                        help='database name (default: KoNViD-1k or CVD2014)')
    parser.add_argument('--batch_size', type=int, default=2,
                        help='frame batch size for feature extraction (default: 64)')
    parser.add_argument('--disable_gpu', action='store_true',
                        help='flag whether to disable GPU')
    args = parser.parse_args()

    if args.database == 'KoNViD-1k':
        videos_dir = 'E:/Projects/VQA/Database/KoNViD_1k/KoNViD_1k_videos/'  # videos dir
        # features_dir = 'CNN_features_KoNViD-1k/'  # features dir
        datainfo = 'data/KoNViD-1kinfo.mat'  # database info: video_names, scores; video format, width, height, index, ref_ids, max_len, etc.

        Info = h5py.File(datainfo, 'r')
        data = pd.read_csv('E:/Projects/VQA/DataBase/KoNViD_1k/KoNViD_1k_metadata/KoNViD_1k_attributes.csv')
        video_id = data['flickr_id'].tolist()
        video_names = [str(i) + ".mp4" for i in video_id]
        scores = Info['scores'][0, :]
        video_format = Info['video_format'][()].tobytes()[::2].decode()
        width = int(Info['width'][0])
        height = int(Info['height'][0])
        dataset = VQADataset(videos_dir, video_names, scores, video_format, width, height)



    # print('dataset大小为：', dataset.__len__())
    # print(dataset.__getitem__(0))
    # print(dataset[0]['video'].shape)
    train_dataset, val_dataset, test_dataset = paddle.io.random_split(
        dataset, [int(0.9*len(dataset)), int(0.05*len(dataset)), int(0.05*len(dataset))],
        generator=paddle.seed(args.seed))
    train_loader = DataLoader(test_dataset, args.batch_size, shuffle=False, num_workers=0)
    val_loader = DataLoader(test_dataset, args.batch_size, shuffle=False, num_workers=0)
    test_loader = DataLoader(test_dataset, args.batch_size, shuffle=False, num_workers=0)

    # for i in range(len(val_dataset)):
    #     print(dataset[i])

    # a,b = dataset[0]
    # a = np.array(a)
    # print(a)

    # print(type(dataset[0]))

    for i, (video, score) in enumerate(test_loader()):
        print('i:', i)
        print(video.shape)`
如上，十分感谢

**Comment by minghaoBD** [comment]
test_loader = DataLoader(test_dataset, args.batch_size, shuffle=False, num_workers=0)
-> test_loader = DataLoader(test_dataset, batch_size=args.batch_size, shuffle=False, num_workers=0)
![image](https://user-images.githubusercontent.com/79566150/147035305-338a91fb-a700-4392-86e0-3a4de08cd85c.png)
第二个参数不是batch_size，需要指定下

**Comment by Gray-OREO** [comment]
原来在这里！十分感谢！
