### ISSUE TITLE
集群预测时报___fc_layer_0__.w0 missing, not allowed

### ISSUE THREAD

**Issue by shenshuijing** [PaddlePaddle/Paddle#3834]
集群产出训练模型后， 在本机上用单机预测，是通过的， 提交脚本为：
```bash
paddle train \
  --job=test \
  --config=trainer_config.py \
  --use_gpu=false \
  --config_args=is_predict=1 \
  --init_model_path="model/$1" \
  --predict_output_dir="output/$1" \
  --trainer_count=1
```

由于预测的数据量较大， 所以提交了一个集群预测任务， 提交脚本为：
```bash
paddle cluster_train \
  --config=$SCRIPT_PATH/trainer_config_adagrad.conf \
  --use_gpu=cpu \
  --time_limit=10:00:00 \
  --submitter=zhouzhiyong03 \
  --num_nodes=10 \
  --job_priority=normal \
  --config_args=is_predict=1 \
  --init_model_path="模型到pass地址" \
  --trainer_count=4 \
  --job_name=zhouzhiyong03_dnn_predict \
  --where=mpi集群地址 \
  --thirdparty=$SCRIPT_PATH/thirdparty
```
一直报___fc_layer_0__.w0 missing, not allowed的错误， 但是我在模型产出目录中是能看到这个文件的

**Comment by typhoonzero** [comment]
可否看下提交后集群任务的workspace中是否存在init_model_path下载后的模型的路径，然后看下日志中启动参数指向的init_model_path是否对应workspace下的路径

**Comment by shenshuijing** [comment]
我看了下workspace中没有init_model_path下载后的模型的路径,，这个应该怎么修复， 我提交了好几次都是这样的

**Comment by typhoonzero** [comment]
提交集群任务init_model_path指的是HDFS的路径，任务会从HDFS下载模型到每个节点，然后开始infer。
`paddle cluster_train`需要指定`--fs_name`和`--fs_ugi`参数，为hadoop的集群地址和ugi。

**Comment by shenshuijing** [comment]
这个参数已经在trainer_config.conf中指定了，
![image](https://user-images.githubusercontent.com/24400858/30045285-dd489674-9235-11e7-83d5-d695b716adf8.png)
这个配置都是跟之前没有init model的配置是一样的

**Comment by typhoonzero** [comment]
可以Hi下job链接么？方便debug。

**Comment by typhoonzero** [comment]
排查后，原因是：`init_model_path` 参数如果在`paddle cluster_train`的时候加上，集群任务的`paddle_trainer` 启动就会直接使用这个参数的值，需要在`cluster_confit`中配置，这样才能在receiver中开始下载相关的操作。
