### ISSUE TITLE
编译Paddle后安装，提示ImportError: cannot import name 'CommContext' from 'paddle.fluid.core_noavx'

### ISSUE THREAD

**Issue by zpcalan** [PaddlePaddle/Paddle#38377]
- 版本、环境信息：
 Paddle version: 0.0.0
Paddle With CUDA: True

OS: Ubuntu 16.04
Python version: 3.7.4

CUDA version: 10.1.105
cuDNN version: None.None.None
Nvidia driver version: 450.36.06
- 安装方式信息：
 本地编译：
```
1.mkdir build && cd build
2.cmake .. -DPY_VERSION=3.7 -DWITH_GPU=ON -DWITH_TESTING=OFF -DCMAKE_BUILD_TYPE=Release -DWITH_AVX=OFF
3.make
4. pip install build/python/dist/paddlepaddle_gpu-0.0.0-cp37-cp37m-linux_x86_64.whl
```

执行[官网wide_and_deep用例](https://fleet-x.readthedocs.io/en/latest/paddle_fleet_rst/parameter_server/ps_quick_start.html)，提示
```
  from paddle.fluid.core import CommContext
ImportError: cannot import name 'CommContext' from 'paddle.fluid.core_noavx'
```
编译指令已经disable了avx但是依然报错，请问下该如何解决了。

**Comment by lzzyzlbb** [comment]
编译的时候，打开WITH_DISTRIBUTE=ON试试呢

**Comment by zpcalan** [comment]
多谢回复。
加了此选项后依然失败，相同的报错。
日志里有这一句：`W1223 15:29:44.242477 78409 init.cc:236] AVX is available, Please re-compile on local machine` @lzzyzlbb

**Comment by lzzyzlbb** [comment]
这里显示机器是支持avx的吖，为啥要设置成off呢

**Comment by zhaocaibei123** [comment]
wide&deep示例建议用release版本跑
如果想用develop编译，拉取官网2.0以上docker，在docker里编译
cmake .. -DCMAKE_INSTALL_PREFIX=./output/ -DCMAKE_BUILD_TYPE=Release -DWITH_PYTHON=ON -DWITH_MKL=OFF -DWITH_GPU=OFF -DWITH_INFERENCE_API_TEST=OFF -DWITH_FLUID_ONLY=ON -DPY_VERSION=3.7 -DPYTHON_INCLUDE_DIR=/usr/local/python3.7.0/include/python3.7m -DPYTHON_LIBRARY=/usr/local/python3.7.0/lib/libpython3.7m.so -DPYTHON_EXECUTABLE=/usr/local/python3.7.0/bin/python3.7 -DWITH_DISTRIBUTE=ON -DWITH_PSLIB=OFF -DWITH_PSLIB_BRPC=OFF -DWITH_PSCORE=ON -WITH_AVX=OFF -DWITH_TESTING=ON

**Comment by zpcalan** [comment]
> 这里显示机器是支持avx的吖，为啥要设置成off呢

因为之前试了，默认编译avx on的话也会报错：
```
    from paddle.fluid.core import CommContext
ImportError: cannot import name 'CommContext' from 'paddle.fluid.core_avx' 
```

**Comment by zpcalan** [comment]
> wide&deep示例建议用release版本跑 如果想用develop编译，拉取官网2.0以上docker，在docker里编译 cmake .. -DCMAKE_INSTALL_PREFIX=./output/ -DCMAKE_BUILD_TYPE=Release -DWITH_PYTHON=ON -DWITH_MKL=OFF -DWITH_GPU=OFF -DWITH_INFERENCE_API_TEST=OFF -DWITH_FLUID_ONLY=ON -DPY_VERSION=3.7 -DPYTHON_INCLUDE_DIR=/usr/local/python3.7.0/include/python3.7m -DPYTHON_LIBRARY=/usr/local/python3.7.0/lib/libpython3.7m.so -DPYTHON_EXECUTABLE=/usr/local/python3.7.0/bin/python3.7 -DWITH_DISTRIBUTE=ON -DWITH_PSLIB=OFF -DWITH_PSLIB_BRPC=OFF -DWITH_PSCORE=ON -WITH_AVX=OFF -DWITH_TESTING=ON

我有空试下，谢谢回复。
因为我们还是用物理机比较多，最好还是能解决以上的问题。：）

**Comment by SEU-zxj** [comment]
我也遇到这样的问题了，请问题主大大解决了吗？😭

**Comment by Gmgge** [comment]
@zhaocaibei123  你好，很感谢你的建议。
我根据你提供的命令编译paddlepaddle之后，该whl包安装到不支持avx的机器上时，仍不可成功运行，提示No module named 'paddle.fluid.core_noavx'
@SEU-zxj 你好，请问你尝试了上面的方法嘛？

**Comment by Gmgge** [comment]
其中的参数-WITH_AVX=OFF，修改为-DWITH_AVX=OFF

**Comment by ghost** [comment]
Because your paddleslim didn't installed with the same version of paddlepaddle.
My solution ( Cuda 11.4, cudnn 8.4.0):
- python3.6 -m venv env
- pip3 install paddlepaddle-gpu==2.2.0.post112 -f https://www.paddlepaddle.org.cn/whl/linux/mkl/avx/stable.html
- pip install paddleslim==2.2.0 -i https://pypi.tuna.tsinghua.edu.cn/simple ( chose version from repo https://github.com/PaddlePaddle/PaddleSlim) 
- python slim/quant/qat_train.py \
       --config configs/quick_start/bisenet_optic_disc_512x512_1k.yml \
       --model_path output_fp32/best_model/model.pdparams \
       --learning_rate 0.001 \
       --do_eval \
       --use_vdl \
       --save_interval 250 \
       --save_dir output_quant
