### ISSUE TITLE
建议增加对M1芯片Mac的原生支持

### ISSUE THREAD

**Issue by YangangCao** [PaddlePaddle/Paddle#38379]
截止到2021.12.23，包括tensorflow和pytorch在内的大多数深度学习的python包均已有原生M1版本（不需要Rosetta转译），可直接通过pip安装。建议paddle增加此支持

**Comment by dingjiaweiww** [comment]
您好，飞桨目前是支持M1 芯片的，也提供了pip 安装方式：python -m pip install paddlepaddle==2.2.1 -i https://mirror.baidu.com/pypi/simple
具体安装方法请参考文档：https://www.paddlepaddle.org.cn/documentation/docs/zh/install/pip/macos-pip.html

**Comment by hatimwen** [comment]
> 您好，飞桨目前是支持M1 芯片的，也提供了pip 安装方式：python -m pip install paddlepaddle==2.2.1 -i https://mirror.baidu.com/pypi/simple
> 具体安装方法请参考文档：https://www.paddlepaddle.org.cn/documentation/docs/zh/install/pip/macos-pip.html

您好，我参照您提供的安装方式及参考文档，仍无法安装。
具体信息：
```
>> python -c "import platform;print(platform.architecture()[0]);print(platform.machine())"
64bit
arm64

>> python -m pip --version
pip 21.3.1 from /Users/wenht/miniforge3/envs/paddle_wenht/lib/python3.9/site-packages/pip (python 3.9)

>> python -m pip install paddlepaddle==2.2.1 -i https://mirror.baidu.com/pypi/simple

Looking in indexes: https://mirror.baidu.com/pypi/simple
ERROR: Could not find a version that satisfies the requirement paddlepaddle==2.2.1 (from versions: none)
ERROR: No matching distribution found for paddlepaddle==2.2.1
```

**Comment by SigureMo** [comment]
+1+1，想要***原生***的！

**Comment by wantsor** [comment]
建议增加arm64原生版本python的支持， 目前装不了呀，得换回intel版的conda去安装

**Comment by Lumisilk** [comment]
M1 Pro 下同样提示找不到对应版本的包。请问 Paddle 团队说的支持 M1 是真的只支持 M1 芯片而不支持其他 arm64 的平台吗…？

**Comment by chenweiyj** [comment]
> 您好，飞桨目前是支持M1 芯片的，也提供了pip 安装方式：python -m pip install paddlepaddle==2.2.1 -i https://mirror.baidu.com/pypi/simple 具体安装方法请参考文档：https://www.paddlepaddle.org.cn/documentation/docs/zh/install/pip/macos-pip.html

![image](https://user-images.githubusercontent.com/1733948/149458970-9f4baa6f-b4be-4645-82e0-dc48c507674e.png)
文档说不支持python 3.9，那mac m1要安装哪个版本？ @dingjiaweiww

**Comment by johnson7788** [comment]
## 没搜到对应的版本
python -c "import platform;print(platform.architecture()[0]);print(platform.machine())"  
64bit
arm64

python -m pip install paddlepaddle==2.2.1 -i https://mirror.baidu.com/pypi/simple
Looking in indexes: https://mirror.baidu.com/pypi/simple
ERROR: Could not find a version that satisfies the requirement paddlepaddle==2.2.1
ERROR: No matching distribution found for paddlepaddle==2.2.1

python -m pip install paddlepaddle -i https://mirror.baidu.com/pypi/simple
Looking in indexes: https://mirror.baidu.com/pypi/simple
ERROR: Could not find a version that satisfies the requirement paddlepaddle
ERROR: No matching distribution found for paddlepaddle

**Comment by ziiip** [comment]
### 遇到了同样的问题

```
$ python -c "import platform;print(platform.architecture()[0]);print(platform.machine())"
64bit
arm64

$ python -m pip install paddlepaddle -i https://mirror.baidu.com/pypi/simple
Looking in indexes: https://mirror.baidu.com/pypi/simple
ERROR: Could not find a version that satisfies the requirement paddlepaddle (from versions: none)
ERROR: No matching distribution found for paddlepaddle

$  python --version
Python 3.8.11

$ which python
~/.pyenv/shims/python
```

@chenweiyj

**Comment by RickyLau** [comment]
相同的需求，用于LAC的编译 。

**Comment by betterlmy** [comment]
用这个命令安装x86版本的python才能安装paddle 害
CONDA_SUBDIR=osx-64 conda create -n pd_rosetta_env python=3.9

**Comment by betterlmy** [comment]
我对比了pytorch同一代码在不同架构下的执行时间，
在x86架构下 时间是45秒
<img width="575" alt="image" src="https://user-images.githubusercontent.com/44780287/156405966-cc2732f6-0ce4-4899-a8ca-a7271249f571.png">
在ARM架构下 时间是5秒
<img width="578" alt="image" src="https://user-images.githubusercontent.com/44780287/156406110-8a8ef9f6-f72f-462a-a8c5-2f153824c331.png">
差别很明显。还是尽快适配吧
代码
```python
a = torch.randn(30000, 1000)
b = torch.randn(1000, 30000)
print(a)
print(b)
t0 = time.time()
c = torch.matmul(a, b)
t1 = time.time()

print(a.device, t1 - t0, c.norm(2))
```

**Comment by xiebaiyuan** [comment]
> ## 没搜到对应的版本
> python -c "import platform;print(platform.architecture()[0]);print(platform.machine())" 64bit arm64
> 
> python -m pip install paddlepaddle==2.2.1 -i https://mirror.baidu.com/pypi/simple Looking in indexes: https://mirror.baidu.com/pypi/simple ERROR: Could not find a version that satisfies the requirement paddlepaddle==2.2.1 ERROR: No matching distribution found for paddlepaddle==2.2.1
> 
> python -m pip install paddlepaddle -i https://mirror.baidu.com/pypi/simple Looking in indexes: https://mirror.baidu.com/pypi/simple ERROR: Could not find a version that satisfies the requirement paddlepaddle ERROR: No matching distribution found for paddlepaddle

+1 一样的报错。  用x86的miniforge 才可以，等于还是转译。

**Comment by dingjiaweiww** [comment]
可以先检查一下自己的python 版本，Mac 自带的python 版本安装时可能有问题，建议下载python 官网的版本，具体请参考这个FAQ：https://www.paddlepaddle.org.cn/documentation/docs/zh/faq/install_cn.html#mac-m1paddle

**Comment by dingjiaweiww** [comment]
我们创建了一个QQ群：859544848，用来和大家讨论Paddle原生支持Mac M1芯片，大家可以入群和我们讨论～

**Comment by ltto** [comment]
> 您好，飞盘目前是具体M1芯片的，提供了pip安装方式：python -m pip install paddlepaddle==2.2.1 -i https://mirror.baidu.com/pypi/simple 请参考文档：https://www.paddlepaddle.org.cn/documentation/docs/zh/install/pip/macos-pip.html

CPU: m1  pro 
MacOS 12.3.1
python  3.10.4  arm

报错找不到飞桨的包
(ps) ➜  examples python -m pip install paddlepaddle==2.2.1 -i https://mirror.baidu.com/pypi/simple

Looking in indexes: https://mirror.baidu.com/pypi/simple
ERROR: Could not find a version that satisfies the requirement paddlepaddle==2.2.1 (from versions: none)
ERROR: No matching distribution found for paddlepaddle==2.2.1

**Comment by jzhang533** [comment]
我们在2.3版本中会原生支持M1芯片的CPU，以及python3.10，大家敬请期待。
cc: @dingjiaweiww @pangyoki

**Comment by ltto** [comment]
> 我们在2.3版本中会原生支持M1芯片的CPU，以及python3.10，大家敬请期待。 cc: @dingjiaweiww @pangyoki

请问当前的2.3rc版本支持M1吗

**Comment by jzhang533** [comment]
> > 我们在2.3版本中会原生支持M1芯片的CPU，以及python3.10，大家敬请期待。 cc: @dingjiaweiww @pangyoki
> 
> 请问当前的2.3rc版本支持M1吗

是可以编译出来M1上Arm架构的包的。
正式的官方编译出来的binary package，会在2.3版本编出来，并上传到pypi源。

**Comment by ltto** [comment]
我在我的MacBook 14寸 M1Pro芯片上编译失败 
 https://github.com/PaddlePaddle/Paddle/issues/42402

**Comment by gsq7474741** [comment]
不知道有没有适配metal，用M1的GPU加速的计划

**Comment by jzhang533** [comment]
2.3 版本已经可以下载安装了。
M1芯片的Mac上用`pip install paddlepaddle`命令应该能装上paddle啦。

**Comment by James4Ever0** [comment]
可以装cpu 目前还没有gpu呢

**Comment by peterzhangnull** [comment]
> 

是啊没用gpu

**Comment by wdm101** [comment]
> 相同的需求，用于LAC的编译 。

请问最后解决了吗

**Comment by TonyZhang-code** [comment]
> 我在我的MacBook 14寸 M1Pro芯片上编译失败 #42402

现在解决了吗，我能安装成功，但是运行时报错
>>> import paddle
Illegal instruction: 4
<img width="547" alt="image" src="https://github.com/PaddlePaddle/Paddle/assets/57514112/ff587583-9323-4a7d-8335-702953042d70">

**Comment by JIeJaitt** [comment]
> 我们创建了一个QQ群：859544848，用来和大家讨论Paddle原生支持Mac M1芯片，大家可以入群和我们讨论～

怎么搜索显示是和平精英群？
