### ISSUE TITLE
使用中遇到一个问题，需要支持一下yolo_box算子

### ISSUE THREAD

**Issue by shixibao** [PaddlePaddle/Paddle#38372]
![image](https://user-images.githubusercontent.com/23250892/147093224-b87e5cde-45e0-4115-98e3-f0477775717f.png)

**Comment by lyuwenyu** [comment]
支持的 https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/vision/ops/yolo_box_cn.html#yolo-box
