### ISSUE TITLE
API问题

### ISSUE THREAD

**Issue by wangjiancheng-123** [PaddlePaddle/Paddle#38381]
您好，可以问一下这两个关于paddle的api吗
from torch.autograd import Variable
from torch._utils import _flatten_dense_tensors, _unflatten_dense_tensors

**Comment by lzzyzlbb** [comment]
variable 可以参考下文档https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/static/Variable_cn.html#variable
_flatten_dense_tensors 可以参考一下flatten，paddle默认的就是dense_tensor
_unflatten_dense_tensors 可以参考一下reshape
