### ISSUE TITLE
训练集较大，LR无法收敛问题

### ISSUE THREAD

**Issue by buptwds** [PaddlePaddle/Paddle#3841]
我的原特征数据是稀疏矩阵格式，格式为label  featureid:value  featureid:value，这里的value表是有值且为1，为0的不显示，lable的值目前为-1和1，表示有点击和无点击（ctr问题）
我想用paddlepaddle跑一次LR，使用的激活函数为Relu和Sigmoid，但是一直跑不完（测试了小数据量的训练集就可以），event.pass_id一直稳定在0（num_passes指定的是30），event.batch_id已经跑到几十万，初学机器学习和paddlepaddle（以前使用过liblinear跑过该训练集），请问我的问题可能是出在哪里呢？

**Comment by buptwds** [comment]
补充：训练集有100多万行

**Comment by typhoonzero** [comment]
看您关闭了issue，最后的解决方案是什么呢？

**Comment by buptwds** [comment]
调整了batch_size，因为训练集较大，如果batch_size太小，会导致每次读取的训练集较小，因此出现上述batch_id很大，但任务一直跑不完的情况
