### ISSUE TITLE
ERNIE模型使用paddle.git.save存储报错

### ISSUE THREAD

**Issue by junfeizhu** [PaddlePaddle/Paddle#38422]
- 版本、环境信息：
    1）PaddlePaddle版本：2.1.2
    2）CPU/GPU：CUDA 10.2
    3）系统环境：CentOS 7
    4）Python版本号: 3.7
    5）显存信息

我使用ERNIE模型再加上若干全连接层构建了一个分类器，我需要保存推理模型后进行服务器部署，但是在使用paddle.git.save之后报错：
<img width="525" alt="cae0507c28be74f17d2b0b3cb22c7e6" src="https://user-images.githubusercontent.com/32788240/147320309-87cda8a4-9538-429e-8479-f8fbbe67fbdb.png">
<img width="438" alt="4231db92d21109d7ec7117c683b0345" src="https://user-images.githubusercontent.com/32788240/147320322-31c2e87d-2a28-4ea6-a665-0cc2a7780fa0.png">

参考：我感觉问题出在了ERNIE这个模型上，我如果只搭建全连接层，不使用ERNIE，保存部署都没有任何问题。比如以下代码就没有任何报错
<img width="607" alt="e89c4b4db559f41a871d13b380b0365" src="https://user-images.githubusercontent.com/32788240/147320360-a4d2cce4-5aed-428c-847c-36278dc3b55b.png">

**Comment by zh794390558** [comment]
确认下E_Model的输出个数

**Comment by Aurelius84** [comment]
`too many values to unpack` 表明 self.E_model 返回的变量个数不是两个。你可以在这行代码前面加入 import pdb;pdb.set_trace() 看下返回的值有几个。

pdb 使用方法见：https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/guides/04_dygraph_to_static/debugging_cn.html#ertiaoshifangfa

**Comment by junfeizhu** [comment]
> 
试了一下，确实是返回的变量个数不同。我发现不加@paddle.jit.to_static的时候返回2个变量，加了之后返回3个。所以所有的模型都是有这样的特性吗？加了@paddle.jit.to_static之后返回变量个数会不一样？

**Comment by junfeizhu** [comment]
> `too many values to unpack` 表明 self.E_model 返回的变量个数不是两个。你可以在这行代码前面加入 import pdb;pdb.set_trace() 看下返回的值有几个。
> 
> pdb 使用方法见：https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/guides/04_dygraph_to_static/debugging_cn.html#ertiaoshifangfa

**Comment by Aurelius84** [comment]
这个返回值个数问题已经在最近的版本修复了，推荐尝试下 paddle2.2。

若不想更换版本，可以在装饰jit.to_static后，调整下接受返回值的变量。
