### ISSUE TITLE
【论文复现】torch中BN层设置track_running_stats = False，paddle可以实现吗？

### ISSUE THREAD

**Issue by KiritoSSR** [PaddlePaddle/Paddle#38433]
现在复现的论文代码中将Resnet50中的BN层设置track_running_stats = False，在训练中只计算每个batch内的均值和方差，同时在测试的时候BN层的均值和方差也会改变。
但是paddle的BN文档中说：目前训练时设置track_running_stats为False是无效的，实际还是会按照True的方案保存全局均值和方差。之后的版本会修复此问题。
所以没有办法进行对应是吗？

**Comment by ceci3** [comment]
请问下你是想实现测试的时候BN的均值和方差也是使当前batch的均值和方差吗？可以设置model.eval()和use_global_stats=True就可以实现这个功能。

**Comment by KiritoSSR** [comment]
> 下你是想实现测试的时候BN的均值和同样也是使当前batch的均值和均值吗？可以设置model.eval()和use_global_stats=True就可以实现功能。
我想训练的时候也是这样使当前batch的均值和均值

**Comment by KiritoSSR** [comment]
> 下你是想实现测试的时候BN的均值和同样使当前batch的均值和均值吗？可以设置model.eval()和use_global_stats=True就可以实现功能。

我想训练的时候候BN的均值和方差同样使当前batch的均值和均值，可以实现吗？

**Comment by zh794390558** [comment]
当前batch的统计量可以用api的方式获取到。
