### ISSUE TITLE
如何 手动修改save_inference_model,即.pdiparams模型的参数?

### ISSUE THREAD

**Issue by Water2style** [PaddlePaddle/Paddle#38440]
想要手动修改.pdiparams模型的参数.并且重新save了拿来推理.

是否有方法直接把里面的二进制内容 转换并且拿到参数呢?

谢谢

**Comment by zh794390558** [comment]
laod后python解析就行。

**Comment by Water2style** [comment]
> laod后python解析就行。

dictxxx = paddle.load('./xx.pdiparams') 
这个dictxxx是一个 paddle.Tensor啊.  不是dict，怎么解析.
我感觉应该是一个类似于state_dict的东西啊。包括权重的名称和值。结果就一个tensor

**Comment by Water2style** [comment]
> laod后python解析就行。

你好,我load之后得到了一个dict.做了一些修改后, 然后再用paddle.save 下来一个新的 pdiparams.

然后用新的.pdiparams和旧的 .pdmodel 放一起.  但是我推理的时候,用 load_inference_model 会显示 反序列化失败...

错误如下:
ValueError: (InvalidArgument) Deserialize to tensor failed, maybe the loaded file is not a paddle model(expected file format: 0, but 4254401664 found).
[Hint: Expected version == 0U, but received version:4254401664 != 0U:0.] (at /paddle/paddle/fluid/framework/lod_tensor.cc:329)
[operator < load_combine > error]

后来排查了一下,不是修改的问题.
就算我刚用paddle.load读上来,然后paddle.save存下去.也会出现这个错误...这个该怎么办呢,谢谢

**Comment by Water2style** [comment]
> laod后python解析就行。

补充说明:

原版的，可以推理的.pdiparams模型，称为模型1.
Paddle.load起来，再用paddle.save后的模型，(中间没有任何改动，loadl后就save)称为模型2.

问题所在：
1. 用python的open和read()搭配，读出两个模型的二进制文件.
输出后发现两个模型的内容不同，并且使用 len()函数，发现len(模型1）比len(模型2）小，len（模型2）长了3000多.

2.load_inference_model出错主要在 反序列化参数这一步.即 deserialize_persistables(program, params_bytes, exe). 

3.更详细的错误报告：

"""
File "/home/xieyunyao/miniconda3/envs/PP22/lib/python3.8/site-packages/paddle/static/io.py", line 848, in load_inference_model
      deserialize_persistables(program, params_bytes, executor)
    File "/home/xieyunyao/miniconda3/envs/PP22/lib/python3.8/site-packages/decorator.py", line 232, in fun
      return caller(func, *(extras + args), **kw)
    File "/home/xieyunyao/miniconda3/envs/PP22/lib/python3.8/site-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
      return wrapped_func(*args, **kwargs)
    File "/home/xieyunyao/miniconda3/envs/PP22/lib/python3.8/site-packages/paddle/fluid/framework.py", line 238, in __impl__
      return func(*args, **kwargs)
    File "/home/xieyunyao/miniconda3/envs/PP22/lib/python3.8/site-packages/paddle/static/io.py", line 669, in deserialize_persistables
      load_block.append_op(
    File "/home/xieyunyao/miniconda3/envs/PP22/lib/python3.8/site-packages/paddle/fluid/framework.py", line 3178, in append_op
      op = Operator(
    File "/home/xieyunyao/miniconda3/envs/PP22/lib/python3.8/site-packages/paddle/fluid/framework.py", line 2224, in __init__
      for frame in traceback.extract_stack():
    InvalidArgumentError: Deserialize to tensor failed, maybe the loaded file is not a paddle model(expected file format: 0, but 4254401664 found).
      [Hint: Expected version == 0U, but received version:4254401664 != 0U:0.] (at /paddle/paddle/fluid/framework/lod_tensor.cc:329)
      [operator < load_combine > error]

"""

**Comment by AndyandViky** [comment]
> 

请问解决了么这个问题

**Comment by Water2style** [comment]
> > 
> 
> 请问解决了么这个问题

时间有点长了...记不起来当时的需求了。
贴一小段代码供参考，把量化后仍然为FP32格式的weights转为INT8格式：

#step1 读取原FP32模型
original_path_prefix = './quant_post_static_model/qpt'
[inference_program, feed_target_names,fetch_targets] = paddle.static.load_inference_model(
                                            path_prefix=original_path_prefix,
                                            executor=exe)

#step2, 用paddle.load读取原模型的dict
dict_qua = paddle.load(original_path_prefix)

def model_fp32_to_int8(model_dict):
    for weight_name in model_dict:
        #print(weight_name)
        if "conv" in weight_name:
            weight_data_fp32 = model_dict[weight_name]
            #print(weight_data)
            weight_data_int8 = weight_data_fp32.astype('int8')
            model_dict[weight_name] = weight_data_int8
            #print((model[weight_name]).dtype)
    return model_dict

#step3,把FP32的dict转成int8
dict_qua_int8 = model_fp32_to_int8(dict_qua)

#step4,克隆新的 program,并且把INT8的dict,传给这个新的Program
new_int8_prog = inference_program.clone(for_test=False)
new_int8_prog .set_state_dict(dict_qua_int8) 

#step5, 保存这个 新的INT8 Program
save_path = './new_int8_qua/'
#改用 fluid.io.save_inference_model,否则会在输出的时候添加一个op
fluid.io.save_inference_model(save_path, feed_target_names,
                                  fetch_targets, exe, new_int8_prog,
                                  model_filename="model.pdmodel",params_filename="model.pdiparams")
