### ISSUE TITLE
在 Paddle 中新增 LBFGS

### ISSUE THREAD

**Issue by fox2049** [PaddlePaddle/Paddle#38444]
黑客马拉松任务，未完成。请官方添加，谢谢。

https://github.com/PaddlePaddle/Paddle/issues/36002

**Comment by zh794390558** [comment]
需求已收到。

**Comment by zh794390558** [comment]
是和这个一样吗 https://pytorch.org/docs/1.9.1/generated/torch.optim.LBFGS.html？

**Comment by fox2049** [comment]
对的
