### ISSUE TITLE
【论文复现】显存泄露问题

### ISSUE THREAD

**Issue by CuberrChen** [PaddlePaddle/Paddle#38448]
再一次遇到显存泄露的问题，训练过程中显存稳定一段时间就突然上升，造成最终溢出程序终止。
请问有没有手动释放显存的方法，比如我每iter结束就手动将显存释放掉？
查找内存泄露问题点太难找了..

**Comment by zhiboniu** [comment]
可以试试del用完的数据+gc.collect()
