### ISSUE TITLE
在使用LRScheduler后的optimizer中，如何修改lr

### ISSUE THREAD

**Issue by BeyondYourself** [PaddlePaddle/Paddle#38477]
paddle版本2.2.1
环境Linux  GPU
目前遇到的问题是，在加载了预训练模型后，想要修改其中的lr,但是目前官网的optimizer中关于lr的set是有如下的说明：

![image](https://user-images.githubusercontent.com/12640462/147445403-ab44415e-38e7-4a6b-9b5b-bb77602ecc20.png)

这种情况下，我该如何设置lr呢，我用的llr_scheduler为官方的ReduceOnPlateau

**Comment by Intsigstephon** [comment]
您好，您的反馈对产品非常有价值，我们内部会安排评估，未来有计划尽快回复

**Comment by Intsigstephon** [comment]
> paddle版本2.2.1 环境Linux GPU 目前遇到的问题是，在加载了预训练模型后，想要修改其中的lr,但是目前官网的optimizer中关于lr的set是有如下的说明：
> 
> ![image](https://user-images.githubusercontent.com/12640462/147445403-ab44415e-38e7-4a6b-9b5b-bb77602ecc20.png)
> 
> 这种情况下，我该如何设置lr呢，我用的llr_scheduler为官方的ReduceOnPlateau

可以尝试按照这个链接的方式进行修改： https://github.com/PaddlePaddle/Paddle/blob/release/2.2/python/paddle/optimizer/optimizer.py#L182

**Comment by BeyondYourself** [comment]
@Intsigstephon 可否给个范例呢，这个是调用内部的变量进行赋值吧

**Comment by Intsigstephon** [comment]
是的。我可以加你个联系方式吗？ 好了解下实际的需求

**Comment by BeyondYourself** [comment]
@Intsigstephon   861937180   微信、QQ同号
