### ISSUE TITLE
trainer_count，deviceId和threadId的关系

### ISSUE THREAD

**Issue by shijiaxin** [PaddlePaddle/Paddle#3849]
在doc/howto/usage/cmd_parameter/use_case_cn.md里面，有描述如何在不同设备上指定层：
原文如下：
当device!=-1时设备ID号的分配：
```
(deviceId + gpu_id + threadId * numLogicalDevices_) % numDevices_
```
所以这里描述的`trainer_count`，`deviceId`和`threadId`分别该如何理解？

它们如何对应到具体的GPU卡和CPU线程上？
`parallel_nn`到底是数据并行还是模型并行还是两者都是？
这个设计是出于什么目的？

**Comment by lcy-seso** [comment]
- trainer_count 计算线程数目
- deviceId 是设备编号，-1 cpu，0 ~ N 是机器上GPU卡的编号，N = GPU 卡数 - 1
- threadId 是当前计算线程编号
- parallel_nn 只是自动在CPU和GPU之间拷贝数据

**Comment by Yancey1989** [comment]
- `trainer_count`: 每个trainer实例的线程数
- `deviceId`: GPU/CPU的设备号，例如`--use_gpu=1`, `fc=fc_layer(input=l, layer_attr=ExtraAttr(device=0), ...)`表示使用0号GPU卡。
- `threadId`: 当前线程Id,范围：`[0,trainer_count)`

> parallel_nn到底是数据并行还是模型并行还是两者都是？

我理解`parallel_nn`只是做了混合设备的计算。
- 数据并行：目前Paddle采用trainer/pserver的架构来实现的数据并行，原理参考：https://github.com/PaddlePaddle/Paddle/blob/develop/doc/design/cluster_train/README.md#training-job
- 模型并行：目前Paddle并没有特别友好的支持模型并行，一种支持大模型的方法参考：https://github.com/PaddlePaddle/Paddle/blob/develop/doc/design/cluster_train/large_model_dist_train.md
