### ISSUE TITLE
Making it easier to write unittest for  comparing gpu and cpu version of a function 

### ISSUE THREAD

**Issue by emailweixu** [PaddlePaddle/Paddle#385]
Currently, the unittest for comparison of the gpu and cpu version of a same function is quite tedious. An exmaple is https://github.com/baidu/Paddle/pull/358/files/3404bf1e85377a9f50008c95b74017f96bd28f36..f502b0c33ef770cd14c6aea1e6c429900d18d36e

Should add some utility function so that a developer only need to provide the function name for comparing the  two versions of function. The utility function will responsible for generating data, running through different size of matrix and comparing the results.

**Comment by hedaoyuan** [comment]
OK, I will refactor the `test_matrixCompare.cpp`.  The test case construct in pr #239 has been relatively simple.

**Comment by hedaoyuan** [comment]
A demo of auto compare.
https://github.com/hedaoyuan/Utility/tree/master/AutoCompare

**Comment by hedaoyuan** [comment]
`test_matrixCompare.cpp`里面的测试主要是比较CpuMatrix和GpuMatrix成员函数实现上是否一致，整个test文件看起来比较冗余，实际上每个test case主要包含四个步骤。
1. 初始化一个CPU和一个GPU对象；
2. 分别初始化CpuMatrix和GpuMatrix相应成员函数所用到的参数；
3. 用构造的参数分别调用一次CPU和GPU对象的成员函数；
4. 对CPU和GPU成员函数调用结果进行比较。

简化成员函数的test case的代码逻辑有两个方法：
1. 只需要知道成员函数类型，自动构造CPU和GPU对象，并自动构造所用参数，再各自调用相应的成员并CHECK结果是否一致；
2. 只构造CPU成员函数所用的参数，通过一个AutoCompare对象，自动生成GPU成员函数所需要的参数，并完成函数调用和结果CHECK。

方法一，可以将成员函数的比较简化成一条CHECK命令；
对于element wise函数的test case可以用`BaseMatrixCompare`来实现；比如
`BaseMatrix::add(real p);`的test case，原先实现如下，
```
void testMatrixAdd(int height, int width) {
  MatrixPtr cpuA = std::make_shared<CpuMatrix>(height, width);
  MatrixPtr gpuA = std::make_shared<GpuMatrix>(height, width);

  cpuA->randomizeUniform();
  gpuA->copyFrom(*cpuA);
  cpuA->add(2.5);
  gpuA->add(2.5);

  MatrixPtr outputCheck = std::make_shared<CpuMatrix>(height, width);
  outputCheck->copyFrom(*gpuA);
  MatrixCheckEqual(*cpuA, *outputCheck);
}
TEST(Matrix, unary) {
  for (auto height : {1, 3, 11, 73, 128, 200, 330}) {
    for (auto width : {1, 3, 32, 100, 512, 1000, 3210}) {
      VLOG(3) << " height=" << height << " width=" << width;
      testMatrixAdd(height, width);
    }
  }
}
```
使用`BaseMatrixCompare`可以用如下方式实现CHECK，只需要将成员函数作为参数输入即可。
```
BaseMatrixCompare<0>(&BaseMatrix::add);
```
如果add在BaseMatrix里面是有重载，则这里需要通过static_cast来显示的指定具体CHECK的是哪个add函数：
```
BaseMatrixCompare<0>(static_cast<void (BaseMatrix::*)(real)>(&BaseMatrix::add));
```
同样对于aggregate函数，可以用BaseMatrixAsColVector或BaseMatrixAsRowVector来CHECK。

方法二，节省一半代码来简化test case的构造，并且能够使test case的代码逻辑更清楚；
比如：


还有一些实现上比较奇怪的成员函数不能使用这两种方式，比如：
1. 成员函数参数中有输出值的，AutoCompare不会比较参数的结果。
2. 成员函数参数类型中有shared_ptr类型的，AutoCompare不支持shared_ptr类型的参数。

**Comment by hedaoyuan** [comment]
还有一些实现上比较奇怪的成员函数目前不能使用AutoCompare，比如：
1. 成员函数参数中有输出值的，AutoCompare不会比较参数的结果。
2. 成员函数参数类型中有shared_ptr类型的，AutoCompare不支持shared_ptr类型的参数。
3. Vector，SparseMatrix的成员函数比较，需要扩展AutoCompare支持这些类型。
