### ISSUE TITLE
MKL库是否会被正确使用 

### ISSUE THREAD

**Issue by Gmgge** [PaddlePaddle/Paddle#38515]
系统环境/System Environment：centos7.4 cpu：E7-4820 V4
版本号/Version：Paddle：2.2.1 PaddleOCR：2.3
mkl加速异常
1.使用单核心 mkl开启 其他参数默认 测试图像平均时间4s；
2.使用单核心 mkl关闭 其他参数默认 测试图像平均时间2s；

无报错，预测结果正常，开启mkl后字符检测变快，但是方向分类与字符识别变慢。

想请问下，mkl库是否需要进行一定的配置？有小伙伴有这种情况嘛？同样的代码在其他cpu上可以正常加速。

**Comment by Gmgge** [comment]
目前又测试到一台机器 i5 7500 cenos7.4和ubuntu16.04都测试过，paddle版本与上文相同，也出现开启mkl加速变慢的情况。

**Comment by smallv0221** [comment]
您好，报错信息需要复现代码，请提供下最小可复现代码，我们复现后会尽快回复您～

**Comment by bjjwwang** [comment]
https://www.paddlepaddle.org.cn/tutorials/projectdetail/2538248 可以看看这个文档 
```
config->EnableMKLDNN();	  	  		
// 可以设置CPU数学库线程数math_threads，可加速推理。
// 注意：math_threads * 外部线程数 需要小于总的CPU的核心数目，否则会影响预测性能。
config->SetCpuMathLibraryNumThreads(10); 
```
我认为应该是math thread调大一些，但需要注意内存的消耗。

**Comment by Gmgge** [comment]
你好，无任何报错，是性能相关的问题。
我查看了这些单核心开启mkl速度变慢的cpu都存在不支持avx512的情况 ，但是这些cpu在字符检测上面却表现出加速的效果，在方向分类与字符识别方向出现降速的情况。

**复现**
代码：https://github.com/PaddlePaddle/PaddleOCR/tree/release/2.3
修改：PaddleOCR/tools/infer/utility.py中的cpu_threads为1
测试代码：python tools/infer/predict_system.py --image_dir="./imgs" --det_model_dir="./inference/ch_ppocr_mobile_v2.0_det_infer/" --cls_model_dir="./inference/ch_ppocr_mobile_v2.0_cls_infer/" --rec_model_dir="./inference/ch_ppocr_mobile_v2.0_rec_infer/" --use_angle_cls=true --use_gpu=False  --enable_mkldnn True
运行该测试需要下载模型文件放入inference文件夹中，并放入图像在imgs；

**Comment by Gmgge** [comment]
@bjjwwang 我使用的是python版本的paddlepaddle，调大thread确实会带来收益，但是我在Inter Xeon Silver 4216 CPU @ 2.10GHz 的cpu上面测试的结果是单核就可以提高OCR的速度。该处理器扩展指令集支持Intel® SSE4.2, Intel® AVX, Intel® AVX2, Intel® AVX-512，当然还存在一定的内存频率提升等等。
不过，如果在E7-4820 V4和i5 7500中 ，开启单核mkl 甚至多核mkl速度还慢于不开启mkl的单核。

在windows上，i5 9500单核心开启mkl可以获取明显的收益，而i5 9500相对于i5 7500并为发现扩展指令集的不同，但是为何开启mkl时，指定一个thread，却调用了全部的核心，在linux上却只会占据单核的100。

**Comment by smallv0221** [comment]
您好，我们的技术人员正在复现您的问题，排查出结果会第一时间通知您。

**Comment by Gmgge** [comment]
你好，有任何消息嘛？

**Comment by bjjwwang** [comment]
sorry 久等，请教了下开发过mkl接口的同学

---
这个我理解和指令集有关系，AVX-512的话性能收益应该会明显一些。

关于他说的 俩老的CPU（都没有AVX-512）性能表现不一致，这个不太好说了，因为我们相当于直接用的mkldnn第三方库，应该是mkldnn这个库的行为是这样导致的

**Comment by Gmgge** [comment]
是否会因为mkldnn兼容模式引起的呢？有任何人复现到这种情况吗？因为我测试的机器通常来说都是离线机器，可能存在系统库版本较老问题？
