### ISSUE TITLE
Table Projection: Check failed: in_->ids

### ISSUE THREAD

**Issue by thomaslwang** [PaddlePaddle/Paddle#3854]
hidden_mix = mixed_layer(size=128, input=[table_projection(input=embedding)])

F0904 20:48:23.458169 22817 TableProjection.cpp:39] Check failed: in_->ids

What's this error means?

**Comment by lcy-seso** [comment]
这个错误是输入数据没有使用 `integer_value`，`integer_value_sequence` 这一系列。

**Comment by thomaslwang** [comment]
1. 这样是不是就对了？
data = data_layer(name="opidseq", size=input_dim)
hidden_mix = mixed_layer(size=128, bias=False, input=[table_projection(input=data,initial_smart=True)])
2. table_projection也是一种embedding layer吗？
3. 怎么理解projection? 我看到paddle里有table projection, full matrix projection， 我在网上没找到projection的定义。

**Comment by lcy-seso** [comment]
1. 你遇到的错误是因为输入数据有误引起的，贴的代码不涉及数据读取，看不出来是不是对的。请自行进一步调试。
2. projection 是一种轻量级layer，不能独立存在，只能作为`mixed_layer` 的输入。
3. http://doc.paddlepaddle.org/release_doc/0.9.0/doc/ui/api/trainer_config_helpers/layers.html#mixed-layer
