### ISSUE TITLE
数据预处理在GPU上完成了，如何进行推理，不想再拷贝回cpu调CopyFromCpu去做推理，有没有好的方式

### ISSUE THREAD

**Issue by marsbzp** [PaddlePaddle/Paddle#38557]
数据预处理在GPU上完成了，如何进行推理，不想再拷贝回cpu调CopyFromCpu去做推理，有没有好的方式

**Comment by weisy11** [comment]
请问是如何做的数据预处理呢？这里的问题可能主要是数据格式是否可以被paddle正确读取。比如采用dali读取和预处理的数据是可以直接使用的。可以参考：https://github.com/PaddlePaddle/PaddleClas/blob/release/2.3/ppcls/data/dataloader/dali.py

**Comment by marsbzp** [comment]
C++推理的时候也能使用dali吗，我用cuda实现了预处理实现分配了显存，如何把处理后的数据传给paddle进行推理

**Comment by jiweibo** [comment]
> C++推理的时候也能使用dali吗，我用cuda实现了预处理实现分配了显存，如何把处理后的数据传给paddle进行推理

目前应该还没有提供直接的方法，不过可以不调用copy_to_cpu，去取出gpu指针，做gpu间的拷贝
https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/fluid/inference/api/paddle_tensor.h#L79
