### ISSUE TITLE
paddle国产cpu编译问题

### ISSUE THREAD

**Issue by RUIJIE-Z** [PaddlePaddle/Paddle#38568]
1）PaddlePaddle版本：请提供您的PaddlePaddle版本号（如1.1）或CommitID
    2）CPU：ft2000+
    3）GPU：无
    4）系统环境：ubuntu16.04、Python3.7.2
注：您可以通过执行[summary_env.py](https://github.com/PaddlePaddle/Paddle/blob/develop/tools/summary_env.py)获取以上信息。
- 安装方式信息：
1）源码编译            
- 问题描述：编译以及安装paddle都没问题，但最后import paddle时出现如下错误
- root@Kylin-101:/opt/paddle-py352# python3
Python 3.7.2 (default, Dec 15 2021, 02:28:13)
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import paddle
Error: Can not import noavx core while this file exists: /usr/local/lib/python3.7/site-packages/paddle/fluid/core_noavx.so
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.7/site-packages/paddle/__init__.py", line 25, in <module>
    from .fluid import monkey_patch_variable
  File "/usr/local/lib/python3.7/site-packages/paddle/fluid/__init__.py", line 36, in <module>
    from . import framework
  File "/usr/local/lib/python3.7/site-packages/paddle/fluid/framework.py", line 37, in <module>
    from . import core
  File "/usr/local/lib/python3.7/site-packages/paddle/fluid/core.py", line 363, in <module>
    raise e
  File "/usr/local/lib/python3.7/site-packages/paddle/fluid/core.py", line 312, in <module>
    from .core_noavx import *
ImportError: /usr/local/lib/python3.7/site-packages/paddle/fluid/core_noavx.so: ELF load command alignment not page-aligned

**Comment by weisy11** [comment]
请问是按照这个教程的方法编译的吗？
https://www.paddlepaddle.org.cn/documentation/docs/zh/install/compile/arm-compile.html#anchor-0

**Comment by RUIJIE-Z** [comment]
是的，就是按照这个方法做的



---Original---
From: "Wei ***@***.***&gt;
Sent at: 2021年12月30日(Thu) Noon11:07
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [PaddlePaddle/Paddle] paddle国产cpu编译问题 (Issue #38568)




 
请问是按照这个教程的方法编译的吗？
 https://www.paddlepaddle.org.cn/documentation/docs/zh/install/compile/arm-compile.html#anchor-0
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by adaxiadaxi** [comment]
@RUIJIE-Z 同学你好，我是国产化环境适配paddle的产品经理，想更多了解咱们的适配情况和环境，如有需要可以添加我这边微信我们实时沟通更便捷：zxy8811666

**Comment by jiweibo** [comment]
> 1）PaddlePaddle版本：请提供您的PaddlePaddle版本号（如1.1）或CommitID    2）CPU：ft2000+    3）GPU：无    4）系统环境：ubuntu16.04、Python3.7.2 注：您可以通过执行[summary_env.py](https://github.com/PaddlePaddle/Paddle/blob/develop/tools/summary_env.py)获取以上信息。
> 
> * 安装方式信息：
>   1）源码编译
> * 问题描述：编译以及安装paddle都没问题，但最后import paddle时出现如下错误
> * root@Kylin-101:/opt/paddle-py352# python3
>   Python 3.7.2 (default, Dec 15 2021, 02:28:13)
>   [GCC 9.3.0] on linux
>   Type "help", "copyright", "credits" or "license" for more information.
> 
> > > > import paddle
> > > > Error: Can not import noavx core while this file exists: /usr/local/lib/python3.7/site-packages/paddle/fluid/core_noavx.so
> > > > Traceback (most recent call last):
> > > > File "", line 1, in 
> > > > File "/usr/local/lib/python3.7/site-packages/paddle/**init**.py", line 25, in 
> > > > from .fluid import monkey_patch_variable
> > > > File "/usr/local/lib/python3.7/site-packages/paddle/fluid/**init**.py", line 36, in 
> > > > from . import framework
> > > > File "/usr/local/lib/python3.7/site-packages/paddle/fluid/framework.py", line 37, in 
> > > > from . import core
> > > > File "/usr/local/lib/python3.7/site-packages/paddle/fluid/core.py", line 363, in 
> > > > raise e
> > > > File "/usr/local/lib/python3.7/site-packages/paddle/fluid/core.py", line 312, in 
> > > > from .core_noavx import *
> > > > ImportError: /usr/local/lib/python3.7/site-packages/paddle/fluid/core_noavx.so: ELF load command alignment not page-aligned

您好，可以尝试下换用最新的patchelf工具重新编译下？这个问题比较奇怪，可以先试下是否是patchelf版本过低导致的
