### ISSUE TITLE
[paddle UT] BUG

### ISSUE THREAD

**Issue by codecookinging** [PaddlePaddle/Paddle#38561]
为使您的问题得到快速解决，在建立Issue前，请您先通过如下方式搜索是否有相似问题:【搜索issue关键字】【使用labels筛选】【官方文档】

建立issue时，为快速解决问题，请您根据使用情况给出如下信息：
- 标题：简洁、精准描述您的问题，例如“ssd 模型前置lstm报错  ”
- 版本、环境信息：
    1）PaddlePaddle版本：2.0.2
    2）CPU：Intel(R) Xeon(R) Gold 6248R CPU @ 3.00GHz
    3）GPU：T4 ,cuda-10.0
    4）系统环境：linux Ubuntu 18.04.5 LTS python3.6
 这两个例子看起来都是 动态图 和静态图 训练结果不一致造成的。
(1)  test_imperative_qat_addquantdequant 例子报错
运行 "/home/cmake-3.16.0-Linux-x86_64/bin/cmake" "-E" "env" "PYTHONPATH=/root/Paddle/build/python" "CUDA_VISIBLE_DEVICES=0" "/usr/local/bin/python3.6" "/root/Paddle/tools/test_runner.py" "test_imperative_qat_addquantdequant"  
  ![image](https://user-images.githubusercontent.com/11263035/147622737-511b67c5-74eb-41e1-bb8d-8a9fae76ad43.png)
(2)    test_sentiment  例子报错
运行 "/home/cmake-3.16.0-Linux-x86_64/bin/cmake" "-E" "env" "PYTHONPATH=/root/Paddle/build/python" "/usr/local/bin/python3.6" "/root/Paddle/tools/test_runner.py" "test_sentiment"

 ![image](https://user-images.githubusercontent.com/11263035/147623278-91895b64-7480-4ec1-99e5-b9f6a134d37e.png)

Thank you for contributing to PaddlePaddle.
Before submitting the issue, you could search issue in the github.Probably there was a similar issue submitted or resolved before.
If there is no solution,please make sure that this is a issue of models including the following details:
**System information**
-PaddlePaddle version （eg.1.1）or CommitID
-CPU: including CPUMKL/OpenBlas/MKLDNN version
-GPU: including CUDA/CUDNN version
-OS Platform (eg.Mac OS 10.14)
-Python version
-Name of Models&Dataset/details of operator
Note: You can get most of the information by running [summary_env.py](https://github.com/PaddlePaddle/Paddle/blob/develop/tools/summary_env.py). 
**To Reproduce**
Steps to reproduce the behavior
**Describe your current behavior**
**Code to reproduce the issue**
**Other info / logs**

**Comment by weisy11** [comment]
好的，我们排查一下，感谢反馈

**Comment by yghstill** [comment]
@codecookinging 关于量化训练精度问题，请更新PaddlePaddle源码到2.2再测试下看是否还有问题。
