### ISSUE TITLE
关于训练的时候使用 融合的Conv-BN：CudnnNormConvolution 的问题

### ISSUE THREAD

**Issue by wxzylforever** [PaddlePaddle/Paddle#38575]
- 版本、环境信息：
   PaddlePaddle版本：develop分支，最新CommitID：fc0a50aa725de28f87640d3593ee23d062d49eef

- 训练信息
    训练时使用CudnnNormConvolution融合卷积和BN

- 问题描述：在训练过程中支持 Convolution 和BN做融合的功能非常好，但是输入数据和权重只能时float16吗？可以支持float32吗？不知道是不是我的用法有问题。
- 
相关 https://github.com/PaddlePaddle/Paddle/issues?q=CudnnNormConvolution

**Comment by weisy11** [comment]
你好，由于这个接口调用的cudnn的限制，目前只支持fp16

**Comment by Xreki** [comment]
@wxzylforever 请问您是什么场景需要使用该功能吗？

**Comment by wxzylforever** [comment]
>

**Comment by wxzylforever** [comment]
> @wxzylforever 请问您是什么场景需要使用该功能吗？
自己搭建了一个训练模型，训练太慢了，想通过融合conv和bn来加速训练。

**Comment by wxzylforever** [comment]
> 你好，由于这个接口调用的cudnn的限制，目前只支持fp16

感谢大佬，我不是很懂cudnn，我看cudnn文档 https://docs.nvidia.com/deeplearning/cudnn/developer-guide/index.html#op-fusion  ，backend API，这个可以支持float32 的conv-bn融合吗，paddle后续有支持这个的计划吗？

**Comment by weisy11** [comment]
> 

嗯，在这个页面中确实有说，输入需要是fp16的
![image](https://user-images.githubusercontent.com/19523330/147729563-8117f9d9-1562-4a48-a0e8-8cb737801f5b.png)
如果未来cudnn支持fp32，我们会跟进的

**Comment by wxzylforever** [comment]
> > 
> 
> 嗯，在这个页面中确实有说，输入需要是fp16的 ![image](https://user-images.githubusercontent.com/19523330/147729563-8117f9d9-1562-4a48-a0e8-8cb737801f5b.png) 如果未来cudnn支持fp32，我们会跟进的

感谢大佬们
