### ISSUE TITLE
make编译的时候出现了问题

### ISSUE THREAD

**Issue by Ray8716397** [PaddlePaddle/Paddle#38571]
我按照文档这样开始编译
cmake  ..     -DWITH_CONTRIB=OFF     -DWITH_MKL=OFF     -DWITH_MKLDNN=OFF      -DWITH_TESTING=OFF     -DCMAKE_BUILD_TYPE=Release     -DWITH_INFERENCE_API_TEST=OFF     -DON_INFER=ON  -DWITH_GPU=ON -DWITH_PYTHON=OFF

但是出错了:
[ 37%] Building CUDA object paddle/fluid/operators/CMakeFiles/spectral_op.dir/spectral_op.cu.o
/home/ray/Workspace/project/ocr/src/cpp_deployment/lib/Paddle/paddle/fluid/operators/spectral_op.cu(316): error: identifier "CUFFT_VERSION" is undefined
          detected during:
            instantiation of "void paddle::operators::FFTC2CFunctor<paddle::platform::CUDADeviceContext, Ti, To>::operator()(const paddle::platform::CUDADeviceContext &, const paddle::operators::Tensor *, paddle::operators::Tensor *, const std::vector<int64_t, std::allocator<int64_t>> &, paddle::operators::FFTNormMode, __nv_bool) [with Ti=paddle::platform::complex<float>, To=paddle::platform::complex<float>]" 
/home/ray/Workspace/project/ocr/src/cpp_deployment/lib/Paddle/paddle/fluid/operators/spectral_op.h(300): here
            instantiation of "void paddle::operators::FFTC2CKernel<DeviceContext, T>::Compute(const paddle::framework::ExecutionContext &) const [with DeviceContext=paddle::platform::CUDADeviceContext, T=float]" 
/home/ray/Workspace/project/ocr/src/cpp_deployment/lib/Paddle/paddle/fluid/framework/op_registry.h(182): here
            implicit generation of "paddle::operators::FFTC2CKernel<DeviceContext, T>::~FFTC2CKernel() [with DeviceContext=paddle::platform::CUDADeviceContext, T=float]" 
/home/ray/Workspace/project/ocr/src/cpp_deployment/lib/Paddle/paddle/fluid/framework/op_registry.h(182): here
            instantiation of class "paddle::operators::FFTC2CKernel<DeviceContext, T> [with DeviceContext=paddle::platform::CUDADeviceContext, T=float]" 
/home/ray/Workspace/project/ocr/src/cpp_deployment/lib/Paddle/paddle/fluid/framework/op_registry.h(182): here
            implicit generation of "paddle::operators::FFTC2CKernel<DeviceContext, T>::FFTC2CKernel() [with DeviceContext=paddle::platform::CUDADeviceContext, T=float]" 
/home/ray/Workspace/project/ocr/src/cpp_deployment/lib/Paddle/paddle/fluid/framework/op_registry.h(182): here
            instantiation of class "paddle::operators::FFTC2CKernel<DeviceContext, T> [with DeviceContext=paddle::platform::CUDADeviceContext, T=float]" 
/home/ray/Workspace/project/ocr/src/cpp_deployment/lib/Paddle/paddle/fluid/framework/op_registry.h(182): here
            instantiation of "void paddle::framework::OpKernelRegistrarFunctor<PlaceType, false, I, KernelTypes...>::operator()(const char *, const char *, int) const [with PlaceType=paddle::platform::CUDAPlace, I=0UL, KernelTypes=<paddle::operators::FFTC2CKernel<paddle::platform::CUDADeviceContext, float>, paddle::operators::FFTC2CKernel<paddle::platform::CUDADeviceContext, double>>]" 
/home/ray/Workspace/project/ocr/src/cpp_deployment/lib/Paddle/paddle/fluid/framework/op_registry.h(206): here
            instantiation of "paddle::framework::OpKernelRegistrar<PlaceType, KernelType...>::OpKernelRegistrar(const char *, const char *, int) [with PlaceType=paddle::platform::CUDAPlace, KernelType=<paddle::operators::FFTC2CKernel<paddle::platform::CUDADeviceContext, float>, paddle::operators::FFTC2CKernel<paddle::platform::CUDADeviceContext, double>>]" 
(498): here

1 error detected in the compilation of "/tmp/tmpxft_00005fe7_00000000-6_spectral_op.cpp1.ii".
paddle/fluid/operators/CMakeFiles/spectral_op.dir/build.make:94: recipe for target 'paddle/fluid/operators/CMakeFiles/spectral_op.dir/spectral_op.cu.o' failed
make[2]: *** [paddle/fluid/operators/CMakeFiles/spectral_op.dir/spectral_op.cu.o] Error 1
CMakeFiles/Makefile2:63014: recipe for target 'paddle/fluid/operators/CMakeFiles/spectral_op.dir/all' failed
make[1]: *** [paddle/fluid/operators/CMakeFiles/spectral_op.dir/all] Error 2
Makefile:148: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by codecookinging** [comment]
根据报错信息 error: identifier "CUFFT_VERSION" is undefined 感觉可能是cufft 动态库版本不对，你可以查查 
 find  /usr/ -name "*libcufft.so*"  这个库的版本是否准确。

**Comment by Ray8716397** [comment]
$ ls -al /usr/local/cuda-10.1/targets/x86_64-linux/lib/libcufft.so
lrwxrwxrwx 1 root root 14 5月   6  2021 /usr/local/cuda-10.1/targets/x86_64-linux/lib/libcufft.so -> libcufft.so.10
$ ls -al /usr/local/cuda-10.1/targets/x86_64-linux/lib/libcufft.so.10
lrwxrwxrwx 1 root root 20 5月   6  2021 /usr/local/cuda-10.1/targets/x86_64-linux/lib/libcufft.so.10 -> libcufft.so.10.1.105
$ ls -al /usr/local/cuda-10.1/targets/x86_64-linux/lib/libcufft.so.10.1.105
-rwxr-xr-x 1 root root 116778696 5月   6  2021 /usr/local/cuda-10.1/targets/x86_64-linux/lib/libcufft.so.10.1.105

**Comment by Ray8716397** [comment]
对的吧,我只装了一个cuda10.1

**Comment by Ray8716397** [comment]
我把这行改了编译通过了  Paddle/paddle/fluid/operators/spectral_op.cu(316):
if (CUFFT_VERSION < 10200) { -> if (true) {

**Comment by weisy11** [comment]
你好，这个问题我们已经修复过了，可以更新一下源码

**Comment by iclementine** [comment]
Some earlier versions of cufft.h does not have `CUFFT_VERSION` defined. This has been fixed. 

See Pr https://github.com/PaddlePaddle/Paddle/pull/37312
