### ISSUE TITLE
export_model时出现了TypeError: The type of 'x' in assign must be (<class 'paddle.fluid.framework.Variable'>, <class 'numpy.ndarray'>, <class 'paddle.VarBase'>), but received <class 'int'>.错误

### ISSUE THREAD

**Issue by XYZ-916** [PaddlePaddle/Paddle#38628]
![image](https://user-images.githubusercontent.com/14884056/147801306-08164fd0-64bc-4340-804c-f3a8f02b332c.png)

个人猜测是roi_x1 = paddle.index_select(roi, index=paddle.to_tensor(0), axis=1)中index=paddle.to_tensor(0)出现了错误。

辛苦看下，谢谢～

**Comment by WenmuZhou** [comment]
你好，`paddle.to_tensor(0)` 这种操作在~~2.2+~~ 2.0+ 的版本里都是支持的，可以升级PaddlePaddle到最新版2.2.1试一下

**Comment by XYZ-916** [comment]
> 你好，`paddle.to_tensor(0)` 这种操作在2.2+的版本里都是支持的，可以升级PaddlePaddle到最新版2.2.1试一下

我用的2.0.1版本，是不支持吗？

**Comment by WenmuZhou** [comment]
我刚刚试了一下2.0.0也是支持的

**Comment by XYZ-916** [comment]
> 我刚刚试了一下2.0.0也是支持的

我从2.0.1版本升级到2.2.1解决了该问题，但是原因不清楚。
