### ISSUE TITLE
请问paddle有图网络相关的api吗

### ISSUE THREAD

**Issue by huilin16** [PaddlePaddle/Paddle#38620]
请问是否有没有paddle.geometry这种包，或者GNN相关的api

复现GNN网络论文需要用到

**Comment by wangxinxin08** [comment]
感谢您的反馈，目前暂时没有paddle.geometry包，你可以参考我们的[PGL](https://github.com/PaddlePaddle/PGL/tree/main/pgl)中的代码，看是否能满足你的需求

**Comment by Ligoml** [comment]
这里有一个PGL聚类的样例可以参考下，这个demo的功能是用PGL 的node2vec（可以使用各种GNN），将图中节点转换成连续的向量表示，再用kmeans聚类：https://github.com/PaddlePaddle/PGL/tree/main/examples/graph_based_clustering_demo
