### ISSUE TITLE
Paddle推理库C API不应该要求用户使用C运行时API free函数去释放内存

### ISSUE THREAD

**Issue by sdcb** [PaddlePaddle/Paddle#38635]
这个API：
```c
// 返回config的配置信息
// 参数：pd_config - Config 对象指针
// 返回：const char* - config配置信息，注意用户需释放该指针。
const char* PD_ConfigSummary(PD_Config* pd_config);
```

返回了一个C风格内存地址，该内存是通过malloc分配的，文档要求用户通过C运行时的free函数释放：
https://paddle-inference.readthedocs.io/en/latest/api_reference/c_api_doc/Config/OtherFunction.html#config
![image](https://user-images.githubusercontent.com/1317141/147807007-46bd060d-205e-4652-90ad-547d925130f9.png)

这不符合库函数C API的需求，即内存分配管理的两种选项：
1、要求用户管理内存，即用户分配内存，用户传入指针表示返回值
2、如果库分配内存，库也应该提供释放内存的API

因为C运行时API free函数是C运行时依赖的，不同平台、不同编译器的C运行时可能完全不一样，可能会导致不一致性。

建议提供一个PD_Free接口，将该C API封装了：
```
void PD_Free(char * p){ free(p);}
```

**Comment by jiweibo** [comment]
> 这不符合库函数C API的需求，即内存分配管理的两种选项： 1、要求用户管理内存，即用户分配内存，用户传入指针表示返回值 2、如果库分配内存，库也应该提供释放内存的API
> 
> 因为C运行时API free函数是C运行时依赖的，不同平台、不同编译器的C运行时可能完全不一样，可能会导致不一致性。
> 
> 建议提供一个PD_Free接口，将该C API封装了：
> 
> ```
> void PD_Free(char * p){ free(p);}
> ```

感谢建议，C API中会增加对const char* 的处理，预计2.2.2 1月初修复。
