### ISSUE TITLE
GPU版本paddle编译完成无libpaddle_inference.so文件

### ISSUE THREAD

**Issue by blackhitomi** [PaddlePaddle/Paddle#38639]
- 版本、环境信息：
    1）PaddlePaddle版本：2.0.0-rc1
    2）CPU：
    3）GPU：1080ti cuda10.1 cudnn7.6
    4）系统环境：ubuntu c++

===============
cpu版本的动态库编译正常，但gpu版本编译完成仅有libpaddle_fluid相关库文件，没有libpaddle_inference的相关库文件，不知道是否哪里设置不对？
配置参数：
cmake -DCMAKE_BUILD_TYPE=Release \
      -DWITH_PYTHON=OFF \
      -DWITH_MKL=OFF \
      -DWITH_GPU=ON  \
      -DON_INFER=ON \
      -DWITH_NCCL=OFF \
      -DWITH_AVX=OFF \
      ..

**Comment by Shixiaowei02** [comment]
您好，请按文档操作，使用 `make inference_lib_dist` 进行产出，谢谢

**Comment by blackhitomi** [comment]
> 您好，请按文档操作，使用 `make inference_lib_dist` 进行产出，谢谢

您好，问题已经找到，2.0版本的可以 带rc的不行，应该是版本问题，感谢解答！
