### ISSUE TITLE
有没有封装好的hinge loss

### ISSUE THREAD

**Issue by applezjm** [PaddlePaddle/Paddle#38644]
有没有封装好的hinge loss，或者相关实现

**Comment by WenmuZhou** [comment]
您好，这个是你需要的吗  https://github.com/PaddlePaddle/PaddleNLP/blob/develop/examples/text_graph/erniesage/models/loss.py#L54

**Comment by Ligoml** [comment]
HingeEmbeddingLoss已经在 develop 版本中实现，如果这是你需要的 api，你可以安装 develop 版本 paddle 使用：https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/nn/HingeEmbeddingLoss_cn.html
