### ISSUE TITLE
怎么按照索引取出对应位置的张量？？

### ISSUE THREAD

**Issue by Chenfei-Kang** [PaddlePaddle/Paddle#38655]
比如一个张量x的shape是[4, 32, 48]，对应了一个RNN的输出(维度对应 batch_size = 4, sequence_length = 32, hidden_size = 48)，但是输入是不定长的，所以在sequence_length这个维度上，按照输入的句子长度index = [1,3,4,4] 来取张量，返回值output应该是[4, 1, 48]，也就是说batch里的每一条数据都需要取最后一个隐藏层的状态(不定长)，我看paddle.gather和index_selected都不是这种实现，所以有对应的API吗？
按照公式写就是:
output[i, 0,  k] = x[i, index[i], k]

**Comment by wenming2014** [comment]
其他框架有对应接口吗？

**Comment by Chenfei-Kang** [comment]
> 其他框架有对应接口吗？

有的，比如torch的gather函数就可按照一个输入长度取RNN的最后一个状态。具体看torch.gather用法，paddle.gather和这个区别很大。

**Comment by sneaxiy** [comment]
@Chenfei-Kang 目前暂时没有直接可用的API，您可以这么做：

```python
def paddle_gather(x, index):
    m, n, k = paddle.split(paddle.shape(x), 3)
    idx_mk = paddle.arange(end=m * k)
    idx_m = idx_mk / k
    idx_k = idx_mk % k
    idx_n = paddle.gather(index, idx_m)
    idx = idx_m * n * k + idx_n * k + idx_k
    x_flatten = paddle.flatten(x)
    y_flatten = paddle.gather(x_flatten, idx)
    ret = paddle.reshape(y_flatten, [m, 1, k])
    return ret
```
