### ISSUE TITLE
【论文复现赛】脚本任务提交一直失败

### ISSUE THREAD

**Issue by justld** [PaddlePaddle/Paddle#38666]
环境：
脚本任务
paddlepaddle==2.2.1
情况描述：
提交脚本任务后运行失败，且无任何日志信息。大概是从1月2号开始至1月4号期间一直失败。
任务id：
114826
114785
114784
114777
114736
114726

**Comment by cuicheng01** [comment]
您的反馈我们已经收到，我们跟进下哈~另外具体的失败信息可以补充下吗？

**Comment by cuicheng01** [comment]
之前应该是平台的问题，现在应该是可以了，麻烦您再check下~
