### ISSUE TITLE
error code is 126

### ISSUE THREAD

**Issue by Wu-Jiayang** [PaddlePaddle/Paddle#38663]
- 标题：error code is 126
- 版本、环境信息：
    1）PaddlePaddle版本：paddlepaddle-gpu-2.2.1.post112
    2）CPU：3600X
    3）GPU：3060
    4）系统环境：win10、python3.8
    5）cuda11.2.、cudnn8.2.1
    6）Driver API Version: 11.5, Runtime API Version: 11.2

- 复现信息：paddle.utils.run_check()
- 问题描述：The third-party dynamic library (cublas64_112.dll;cublas64_11.dll) that Paddle depends on is not configured correctly. (error code is 126) 
![image](https://user-images.githubusercontent.com/62842862/147904727-ac9ccbd8-c9f0-4bd5-b334-614f726f9e32.png)
![image](https://user-images.githubusercontent.com/62842862/147904802-3ea54a64-bc86-47b1-9176-9ff05265aee8.png)

**Comment by Wu-Jiayang** [comment]
![image](https://user-images.githubusercontent.com/62842862/147904884-9971ec0e-c19c-4cb3-bcc5-8b43d7959c79.png)
![image](https://user-images.githubusercontent.com/62842862/147904906-ed2e35aa-67c4-4400-8cec-ccaca8c61158.png)

**Comment by yghstill** [comment]
@Wu-Jiayang 检查一下本地CUDA环境及CUDNN正常吗？
可以通过下面指令看下版本：
```shell
nvcc --version
```
cudnn可进入 CUDA 的安装目录查看文件 cudnn.h

**Comment by Wu-Jiayang** [comment]
> 
通过这种方式检查cuda 11.2
cudnn 8.2.1

**Comment by Wu-Jiayang** [comment]
> @Wu-Jiayang 检查一下本地CUDA环境及CUDNN正常吗？ 可以通过下面指令看下版本：
> 
> ```shell
> nvcc --version
> ```
> 
> cudnn可进入 CUDA 的安装目录查看文件 cudnn.h

通过这种方式检查cuda 11.2
cudnn 8.2.1

**Comment by Wu-Jiayang** [comment]
> @Wu-Jiayang 检查一下本地CUDA环境及CUDNN正常吗？ 可以通过下面指令看下版本：
> 
> ```shell
> nvcc --version
> ```
> 
> cudnn可进入 CUDA 的安装目录查看文件 cudnn.h

@yghstill 通过这种方式检查cuda 11.2
cudnn 8.2.1

**Comment by Wu-Jiayang** [comment]
解决了，在cuda安装目录下找到他所说的cublas64_11.dll文件，复制到C:\Windows\System32，重启ide即可。别问，问就是玄学

**Comment by FirokOtaku** [comment]
> @Wu-Jiayang 解决了，在cuda安装目录下找到他所说的cublas64_11.dll文件，复制到C:\Windows\System32，重启ide即可。别问，问就是玄学

给后来的人补充一下, 至少我这边是把从其它地方找到的 `cublas64_12.dll` + `cublasLt64_12.dll` + `nvblas64_12.dll` 一共 3 个 dll 文件都复制到 `C:/Windows/System32` 才行的. (只复制一个 `cublas64_12.dll` 还是报错)

![image](https://github.com/PaddlePaddle/Paddle/assets/13001378/f39947a4-18b1-43f0-bd94-82da23475187)

**Comment by dolphinlife** [comment]
解决了。跑手写字识别教程又出现这问题，新手也太不友好了。

`
Download finished
W0630 08:53:52.190831 27604 gpu_resources.cc:119] Please NOTE: device: 0, GPU Compute Capability: 8.9, Driver API Version: 12.1, Runtime API Version: 12.0
W0630 08:53:52.194856 27604 gpu_resources.cc:149] device: 0, cuDNN Version: 8.9.
The loss value printed in the log is the current step, and the metric is the average value of previous steps.
Epoch 1/5
Error: C:\home\workspace\Paddle\paddle\phi\kernels\gpu\cross_entropy_kernel.cu:1010 Assertion `false` failed. The value of label expected >= 0 and < 10, or == -100, but got 84374049. Please check label value.
Error: C:\home\workspace\Paddle\paddle\phi\kernels\gpu\cross_entropy_kernel.cu:1010 Assertion `false` failed. The value of label expected >= 0 and < 10, or == -100, but got 84374049. Please check label value.
Error: C:\home\workspace\Paddle\paddle\phi\kernels\gpu\cross_entropy_kernel.cu:1010 Assertion `false` failed. The value of label expected >= 0 and < 10, or == -100, but got 84374049. Please check label value.
Error: C:\home\workspace\Paddle\paddle\phi\kernels\gpu\cross_entropy_kernel.cu:1010 Assertion `false` failed. The value of label expected >= 0 and < 10, or == -100, but got 84374049. Please check label value.
Error: C:\home\workspace\Paddle\paddle\phi\kernels\gpu\cross_entropy_kernel.cu:1010 Assertion `false` failed. The value of label expected >= 0 and < 10, or == -100, but got 84374049. Please check label value.
Error: C:\home\workspace\Paddle\paddle\phi\kernels\gpu\cross_entropy_kernel.cu:1010 Assertion `false` failed. The value of label expected >= 0 and < 10, or == -100, but got 84374049. Please check label value.
Error: C:\home\workspace\Paddle\paddle\phi\kernels\gpu\cross_entropy_kernel.cu:1010 Assertion `false` failed. The value of label expected >= 0 and < 10, or == -100, but got 84374049. Please check label value.
Error: C:\home\workspace\Paddle\paddle\phi\kernels\gpu\cross_entropy_kernel.cu:1010 Assertion `false` failed. The value of label expected >= 0 and < 10, or == -100, but got 84374049. Please check label value.
Error: C:\home\workspace\Paddle\paddle\phi\kernels\gpu\cross_entropy_kernel.cu:1010 Assertion `false` failed. The value of label expected >= 0 and < 10, or == -100, but got 84374049. Please check label value.
Error: C:\home\workspace\Paddle\paddle\phi\kernels\gpu\cross_entropy_kernel.cu:1010 Assertion `false` failed. The value of label expected >= 0 and < 10, or == -100, but got 84374049. Please check label value.
Error: C:\home\workspace\Paddle\paddle\phi\kernels\gpu\cross_entropy_kernel.cu:1010 Assertion `false` failed. The value of label expected >= 0 and < 10, or == -100, but got 358681. Please check label value.
`

**Comment by dolphinlife** [comment]
解决了。跑手写字识别教程又出现这问题，新手也太不友好了。

`
Download finished
W0630 08:53:52.190831 27604 gpu_resources.cc:119] Please NOTE: device: 0, GPU Compute Capability: 8.9, Driver API Version: 12.1, Runtime API Version: 12.0
W0630 08:53:52.194856 27604 gpu_resources.cc:149] device: 0, cuDNN Version: 8.9.
The loss value printed in the log is the current step, and the metric is the average value of previous steps.
Epoch 1/5
Error: C:\home\workspace\Paddle\paddle\phi\kernels\gpu\cross_entropy_kernel.cu:1010 Assertion `false` failed. The value of label expected >= 0 and < 10, or == -100, but got 84374049. Please check label value.
Error: C:\home\workspace\Paddle\paddle\phi\kernels\gpu\cross_entropy_kernel.cu:1010 Assertion `false` failed. The value of label expected >= 0 and < 10, or == -100, but got 84374049. Please check label value.
Error: C:\home\workspace\Paddle\paddle\phi\kernels\gpu\cross_entropy_kernel.cu:1010 Assertion `false` failed. The value of label expected >= 0 and < 10, or == -100, but got 84374049. Please check label value.
Error: C:\home\workspace\Paddle\paddle\phi\kernels\gpu\cross_entropy_kernel.cu:1010 Assertion `false` failed. The value of label expected >= 0 and < 10, or == -100, but got 84374049. Please check label value.
Error: C:\home\workspace\Paddle\paddle\phi\kernels\gpu\cross_entropy_kernel.cu:1010 Assertion `false` failed. The value of label expected >= 0 and < 10, or == -100, but got 84374049. Please check label value.
Error: C:\home\workspace\Paddle\paddle\phi\kernels\gpu\cross_entropy_kernel.cu:1010 Assertion `false` failed. The value of label expected >= 0 and < 10, or == -100, but got 84374049. Please check label value.
Error: C:\home\workspace\Paddle\paddle\phi\kernels\gpu\cross_entropy_kernel.cu:1010 Assertion `false` failed. The value of label expected >= 0 and < 10, or == -100, but got 84374049. Please check label value.
Error: C:\home\workspace\Paddle\paddle\phi\kernels\gpu\cross_entropy_kernel.cu:1010 Assertion `false` failed. The value of label expected >= 0 and < 10, or == -100, but got 84374049. Please check label value.
Error: C:\home\workspace\Paddle\paddle\phi\kernels\gpu\cross_entropy_kernel.cu:1010 Assertion `false` failed. The value of label expected >= 0 and < 10, or == -100, but got 84374049. Please check label value.
Error: C:\home\workspace\Paddle\paddle\phi\kernels\gpu\cross_entropy_kernel.cu:1010 Assertion `false` failed. The value of label expected >= 0 and < 10, or == -100, but got 84374049. Please check label value.
Error: C:\home\workspace\Paddle\paddle\phi\kernels\gpu\cross_entropy_kernel.cu:1010 Assertion `false` failed. The value of label expected >= 0 and < 10, or == -100, but got 358681. Please check label value.
`

**Comment by dairuidark** [comment]
> > @Wu-Jiayang 解决了，在cuda安装目录下找到他所说的cublas64_11.dll文件，复制到C:\Windows\System32，重启ide即可。别问，问就是玄学
> 
> 给后来的人补充一下, 至少我这边是把从其它地方找到的 `cublas64_12.dll` + `cublasLt64_12.dll` + `nvblas64_12.dll` 一共 3 个 dll 文件都复制到 `C:/Windows/System32` 才行的. (只复制一个 `cublas64_12.dll` 还是报错)
> 
> ![image](https://private-user-images.githubusercontent.com/13001378/294803737-f39947a4-18b1-43f0-bd94-82da23475187.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcxNzQ2NjEsIm5iZiI6MTcyNzE3NDM2MSwicGF0aCI6Ii8xMzAwMTM3OC8yOTQ4MDM3MzctZjM5OTQ3YTQtMThiMS00M2YwLWJkOTQtODJkYTIzNDc1MTg3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI0VDEwMzkyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMyYWEyOThiOGI3ZjlkMjM2Zjg4NjRkYmI4OWYyYTEyODYyMjU2ZWE2MDE5ZjkzNTQzNTNiM2EzYzU1NjI2NDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.0A9yTcfJBSO7y2zkyPDpij2y1U6E5xUF0UcgI9n48Zw)

真牛
