### ISSUE TITLE
请问安装cuda11.2的时候报cudnn不是8.2的。但是nvidia官网8.2的cudnn对应着的是11.3的cuda。

### ISSUE THREAD

**Issue by yangrisheng** [PaddlePaddle/Paddle#38668]
![Uploading 28729E3C-D1E8-409A-98D0-3E861C7D5C7F.jpeg…]()

**Comment by cuicheng01** [comment]
您好，图片我这里看不到，可以重新贴一下图片吗？

**Comment by yangrisheng** [comment]
Running verify PaddlePaddle program ...
W0104 09:58:23.099630 7912 device_context.cc:447] Please NOTE: device: 0, GPU Compute Capability: 7.5, Driver API Version: 11.2, Runtime API Version: 11.2
W0104 09:58:23.109603 7912 device_context.cc:465] device: 0, cuDNN Version: 8.1.
W0104 09:58:24.399132 7912 device_context.h:397] WARNING: device: 0. The installed Paddle is compiled with CUDNN 8.2, but CUDNN version in your machine is 8.1, which may cause serious incompatible bug. Please recompile or reinstall Paddle with compatible CUDNN version.
PaddlePaddle works well on 1 GPU.
PaddlePaddle works well on 1 GPUs.
PaddlePaddle is installed successfully! Let's start deep learning with PaddlePaddle now.

**Comment by yangrisheng** [comment]
> 您好，图片我这里看不到，可以重新贴一下图片吗？

Running verify PaddlePaddle program ...
W0104 09:58:23.099630 7912 device_context.cc:447] Please NOTE: device: 0, GPU Compute Capability: 7.5, Driver API Version: 11.2, Runtime API Version: 11.2
W0104 09:58:23.109603 7912 device_context.cc:465] device: 0, cuDNN Version: 8.1.
W0104 09:58:24.399132 7912 device_context.h:397] WARNING: device: 0. The installed Paddle is compiled with CUDNN 8.2, but CUDNN version in your machine is 8.1, which may cause serious incompatible bug. Please recompile or reinstall Paddle with compatible CUDNN version.
PaddlePaddle works well on 1 GPU.
PaddlePaddle works well on 1 GPUs.
PaddlePaddle is installed successfully! Let's start deep learning with PaddlePaddle now.

**Comment by cuicheng01** [comment]
麻烦您贴一下您安装的命令吧~谢谢

**Comment by yangrisheng** [comment]
> 麻烦您贴一下您安装的命令吧~谢谢

官网的命令安装的。python -m pip install paddlepaddle-gpu==2.2.1.post112 -f https://www.paddlepaddle.org.cn/whl/windows/mkl/avx/stable.html

**Comment by yangrisheng** [comment]
> 麻烦您贴一下您安装的命令吧~谢谢

这个warning  不影响使用。但是为啥会这样呀？不是说搭配8.1使用吗？又弹出一个这个warning？没搞懂

**Comment by cuicheng01** [comment]
好的，我们跟进下这个问题，感谢反馈~

**Comment by zhwesky2010** [comment]
@yangrisheng 你好，因为官方发布的cudnn是8.2.1的，与你本机不匹配。所以打出了warning，如果需要消除warning 需要安装CUDNN 8.2.1+CUDA11.2

**Comment by yangrisheng** [comment]
> @yangrisheng 你好，因为官方发布的cudnn是8.2.1的，与你本机不匹配。所以打出了warning，如果需要消除warning 需要安装CUDNN 8.2.1+CUDA11.2

你好。我专门去下载过8.2.1.上面写的是cudnn-11.3-windows-x64-v8.2.1.32.zip  这样的包。官网写的是给11.x的。但是下载的包上面写的是11.3.没影响是吗？

**Comment by yangrisheng** [comment]
> @yangrisheng 你好，因为官方发布的cudnn是8.2.1的，与你本机不匹配。所以打出了warning，如果需要消除warning 需要安装CUDNN 8.2.1+CUDA11.2

如果是这样的话。官网上的话是不是改一改好一点。

CUDA 工具包10.1/10.2 配合 cuDNN 7 (cuDNN版本>=7.6.5）

CUDA 工具包11.0配合cuDNN v8.0.4

CUDA 工具包11.1配合cuDNN v8.1.1

CUDA 工具包11.2配合cuDNN v8.1.1

**Comment by zhwesky2010** [comment]
@yangrisheng 下载这一个  https://developer.nvidia.com/compute/machine-learning/cudnn/secure/8.2.1.32/11.3_06072021/cudnn-11.3-windows-x64-v8.2.1.32.zip 
![infoflow 2022-01-10 13-04-02](https://user-images.githubusercontent.com/52485244/148720417-3dffe76f-a954-434d-bf13-2f855f1462ce.png)

**Comment by yangrisheng** [comment]
> @yangrisheng 下载这一个 ![infoflow 2022-01-10 13-04-02](https://user-images.githubusercontent.com/52485244/148720417-3dffe76f-a954-434d-bf13-2f855f1462ce.png)

是的是的。下载的是这一个。但是下载下来的包名字是cudnn-11.3-windows-x64-v8.2.1.32.zip这样子。所以来咨询下
