### ISSUE TITLE
请问  那个root info是在哪里打印的？py文件是在哪里呀？

### ISSUE THREAD

**Issue by yangrisheng** [PaddlePaddle/Paddle#38673]
就是root INFO信息，这个py文件在哪？以及在哪调用的呢？我不太找得到。。。

**Comment by cuicheng01** [comment]
您好，您具体想看到哪个root INFO信息呢？方便贴个图片吗？

**Comment by yangrisheng** [comment]
> 您好，您具体想看到哪个root INFO信息呢？方便贴个图片吗？

**Comment by yangrisheng** [comment]
![1](https://user-images.githubusercontent.com/39787375/148021690-1c0e0c82-072a-457f-a5b0-4cb3432acad2.png)
比如这个日志信息，在哪里能看到呢？想看这个文件在哪。不是输出文件。 @cuicheng01

**Comment by cuicheng01** [comment]
您好，这个每一个repo实现的位置可能不一样，比如PaddleClas，打印时间的info信息在：https://github.com/PaddlePaddle/PaddleClas/blob/release/2.3/ppcls/utils/logger.py#L45

**Comment by yangrisheng** [comment]
> 您好，这个每一个repo实现的位置可能不一样，比如PaddleClas，打印时间的info信息在：https://github.com/PaddlePaddle/PaddleClas/blob/release/2.3/ppcls/utils/logger.py#L45

明白了。在logger.py里面。感谢
