### ISSUE TITLE
【论文复现】paddle的affine_grid如何实现三维功能

### ISSUE THREAD

**Issue by Lieberk** [PaddlePaddle/Paddle#38670]
paddle的affine_grid只针对2维的图像，对于三维的有没有好的办法实现affine_grid功能，急需要解决！

**Comment by cuicheng01** [comment]
您好，这个目前pytorch的代码是什么样子的呢？我帮忙看下~

**Comment by Lieberk** [comment]
这是pytorch的代码:
grid = nn.functional.affine_grid(theta, size, align_corners)
sample = nn.functional.grid_sample(
            input,
            grid,
            mode,
            padding_mode,
            align_corners,
        )
affine_grid()和grid_sample()是配套使用的，这里我拿affine_grid()说明一下问题。
pytorch的affine_grid()官方解释如下：
<img width="537" alt="05b7cd7d5835413b399228462bd1734" src="https://user-images.githubusercontent.com/57614716/148079012-22571563-8a7d-45bb-b3e9-04d5dab3c2c8.png">

paddle的affine_grid官方解释如下：
<img width="674" alt="f95a6c98a141f3a8468ec29aefa12cd" src="https://user-images.githubusercontent.com/57614716/148079240-aa2349bc-b192-446c-a54d-cb2095c7e8b9.png">

可以看到pytorch的affine_grid()可以实现形状为 [N, C, D, H, W]三维的图像处理，而paddle目前只能处理形状为 [N, C, H, W]的二维图像。我想请教的是如何用Paddle的api实现affine_grid()对于三维图像的处理，或者怎么组合来实现这个功能。

**Comment by Lieberk** [comment]
> 您好，这个目前pytorch的代码是什么样子的呢？我帮忙看下~

您好，pytorch的代码我已贴出并说明，希望能得到解决，非常急需要。如果都不行，只能自己重新写一个支持三维的api，但这会很麻烦。

**Comment by cuicheng01** [comment]
您的问题已收到，确认了下目前paddle的affine_grid不支持3D。您的反馈对产品非常有价值，我们内部会安排评估，未来有计划尽快回复。

**Comment by Lieberk** [comment]
> 您的问题已收到，确认了下目前paddle的affine_grid不支持3D。您的反馈对产品非常有价值，我们内部会安排评估，未来有计划尽快回复。

因为论文复现必须用到这个三维处理的功能，能不能尽快评估完善，这边急需要使用，谢谢老师。

**Comment by wanghaoshuang** [comment]
您好，`affine_grrid` 目前不支持3D-Input.
您可以将affine_grid的out_shape设置为`[N, C*D, H, W]`, 然后将grid_sample的input reshpe为`[N, C*D, H, W]`, 最后将grid_sample的output reshape为`[N, C, D, H, W]`.

**Comment by Lieberk** [comment]
> 您好，`affine_grrid` 目前不支持3D-Input. 您可以将affine_grid的out_shape设置为`[N, C*D, H, W]`, 然后将grid_sample的input reshpe为`[N, C*D, H, W]`, 最后将grid_sample的output reshape为`[N, C, D, H, W]`.

老师，对于affine_grid(theta, size, align_corners)，如果按照您说的这样的处理方式，那么theta对于2维的形状为(N, 2, 3)，那么按照上述方式使用paddle的话，3维的theta是不是不用调整，直接是(N, 3, 4)输入进去就行吗？

**Comment by cuicheng01** [comment]
我们内部会安排评估，未来有计划尽快回复。另外问下，你是在复现哪篇文章用到这个API呢？

**Comment by Lieberk** [comment]
我准备复现序号33的UNETR: Transformers for 3D Medical Image这篇论文，能否加急解决一下。是否可以按照上一位老师说的将affine_grid的out_shape设置为[N, C*D, H, W], 然后将grid_sample的input reshpe为[N, C*D, H, W], 最后将grid_sample的output reshape为[N, C, D, H, W]这样的方法，如果可以这样转换，那theta形状可以直接是(N, 3, 4)输入吗？
| |
陈立志
|
|
***@***.***
|
签名由网易邮箱大师定制
在2022年1月5日 ***@***.***> 写道：

我们内部会安排评估，未来有计划尽快回复。另外问下，你是在复现哪篇文章用到这个API呢？

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Lieberk** [comment]
> 我们内部会安排评估，未来有计划尽快回复。另外问下，你是在复现哪篇文章用到这个API呢？

我准备复现序号33的UNETR: Transformers for 3D Medical Image这篇论文，能否加急解决一下。是否可以按照上一位老师说的将affine_grid的out_shape设置为[N, C*D, H, W], 然后将grid_sample的input reshpe为[N, C*D, H, W], 最后将grid_sample的output reshape为[N, C, D, H, W]这样的方法，如果可以这样转换，那theta形状可以直接是(N, 3, 4)输入吗？

**Comment by cuicheng01** [comment]
我理解theta的形状应该是不变的，你这边也可以试下

**Comment by luotao1** [comment]
#45012 实现了affine_grid_op支持5D的功能
