### ISSUE TITLE
There is a quantize op error when turning on mkldnn bf16 in inference mode.

### ISSUE THREAD

**Issue by baoachun** [PaddlePaddle/Paddle#38687]
The bf16 related pass will insert quantize op to graph when turning on mkldnn bf16, but there is no int quantize kernel when the input data type of original op is int.
![图片](https://user-images.githubusercontent.com/22114318/148032848-91e10d22-61d4-4f7b-af23-96330b386692.png)

<img width="904" alt="图片" src="https://user-images.githubusercontent.com/22114318/148032894-2c2ab505-cf02-4d71-a72d-5993af96b833.png">

Steps to reproduce:
1. `git clone https://github.com/PaddlePaddle/PaddleOCR`
2. `cd PaddleOCR`
3. `git checkout dygraph`
4.  `cd inference && wget https://paddleocr.bj.bcebos.com/dygraph_v2.0/en/det_r50_vd_sast_icdar15_v2.0_train.tar && tar –xvf det_r50_vd_sast_icdar15_v2.0_train.tar`
5. `python3 tools/export_model.py -c configs/det/det_r50_vd_sast_icdar15.yml -o Global.checkpoints=./inference/det_r50_vd_sast_icdar15_v2.0_train/best_accuracy Global.save_inference_dir=./inference/det_r50_vd_sast_icdar15_v2.0_train/`
6. `python3 tools/infer/predict_det.py --det_model_dir=./inference/det_r50_vd_sast_icdar15_v2.0_train   --use_gpu=False  --det_algorithm=SAST --image_dir=./doc/imgs/12.jpg --enable_mkldnn=True --precision=fp16`

**Comment by baoachun** [comment]
@lidanqing-intel

**Comment by wozna** [comment]
@baoachun  The bfloat16 system supports conversion only from float32 to bfloat16, that is why this error occurred. I added checking input data type in cpu_bfloat16_placement_pass here https://github.com/PaddlePaddle/Paddle/pull/38702 and this resolves the error you have found.

**Comment by wozna** [comment]
@baoachun Was the error fixed thanks to PR https://github.com/PaddlePaddle/Paddle/pull/38702? Can this issue be considered as resolved?

**Comment by baoachun** [comment]
Hi @wozna , the problem has been solved, thanks a lot.
