### ISSUE TITLE
Shall we import cub library to make writing cuda kernels more simple?

### ISSUE THREAD

**Issue by typhoonzero** [PaddlePaddle/Paddle#3868]
Saw that caffe2 uses an external cuda library "CUB" to simplify the development of cuda kernels, like `cub::BlockReduce`.  Shall we import this library to simplify the cuda kernel development, and if there's need to write cuda kernels by hand and gain some performance, we can do it later.

CUB: https://nvlabs.github.io/cub/

**Comment by hedaoyuan** [comment]
I think it is ok. Actually, paddle has used some of the code in the Thrust library.

**Comment by typhoonzero** [comment]
Cool, I'll try to make it into our build system.
