### ISSUE TITLE
能否提供一个，windows C++ 支持tensorrt8的版本，目前的tensorrt8需要cudnn8.2，而最高版本cuda11.0，只支持trt7,再以上就没有了

### ISSUE THREAD

**Issue by xinsuinizhuan** [PaddlePaddle/Paddle#38691]
欢迎您对PaddlePaddle提出建议，非常感谢您对PaddlePaddle的贡献！
在留下您的建议时，辛苦您同步提供如下信息：
- 版本、环境信息
1）PaddlePaddle版本：请提供您的PaddlePaddle版本号，例如1.1
2）CPU/GPU：您是否使用GPU进行训练，如是，请提供您的CUDA和cuDNN版本号
3）系统环境：请您描述系统类型、版本，例如Mac OS 10.14
注：您可以通过执行[summary_env.py](https://github.com/PaddlePaddle/Paddle/blob/develop/tools/summary_env.py)获取以上信息。
- 复现信息：如为报错，请给出复现环境、复现步骤
- 建议描述：请您详细描述，您认为需优化的功能

Thank you for contributing to PaddlePaddle.
Before submitting the issue, you could search issue in the github in case that there was a similar issue submitted or resolved before.
Please make sure that this is a feature request. 
**System information**
-PaddlePaddle version （eg.1.1）or CommitID
-CPU: including CPUMKL/OpenBlas/MKLDNN version
-GPU: including CUDA/CUDNN version
-OS Platform (eg.Mac OS 10.14)
Note: You can get most of the information by running [summary_env.py](https://github.com/PaddlePaddle/Paddle/blob/develop/tools/summary_env.py). 
**To Reproduce**
Steps to reproduce the behavior
**Describe the feature and the current behavior/state.**
**Any Other info.**

**Comment by cuicheng01** [comment]
您好，这里看一下有你需要的版本吗？https://paddleinference.paddlepaddle.org.cn/user_guides/download_lib.html#id2

**Comment by xinsuinizhuan** [comment]
> 您好，这里看一下有你需要的版本吗？https://paddleinference.paddlepaddle.org.cn/user_guides/download_lib.html#id2

我要用C++ windows版本的库，然后trt8，但是您自己看下：
![图片](https://user-images.githubusercontent.com/40679769/148144573-c9d24d8b-951c-4582-a1c2-a7ecbeb0b190.png)
目前最高提供的库是cuda11.0 匹配的是trt7,同时只能匹配cudnn 8.0的库

**Comment by cuicheng01** [comment]
您好，您的问题我们已收到，我们会尽快排期更新trt8的预测库，感谢您提出的宝贵意见，谢谢。

**Comment by xinsuinizhuan** [comment]
> 您好，您的问题我们已收到，我们会尽快排期更新trt8的预测库，感谢您提出的宝贵意见，谢谢。

嗯嗯。希望尽快哦，在等着用。希望最好是cudnn8.2以上的版本 trt8

**Comment by xinsuinizhuan** [comment]
> 您好，您的问题我们已收到，我们会尽快排期更新trt8的预测库，感谢您提出的宝贵意见，谢谢。

啥时候出啊？这都半个月了，依然没动静？

**Comment by xinsuinizhuan** [comment]
> 您好，您的问题我们已收到，我们会尽快排期更新trt8的预测库，感谢您提出的宝贵意见，谢谢。

安排更新了没？现在啥进展？

**Comment by leiqing1** [comment]
> > 您好，您的问题我们已收到，我们会尽快排期更新trt8的预测库，感谢您提出的宝贵意见，谢谢。
> 
> 安排更新了没？现在啥进展？

 你这边如果需要某个官方未提供的预编译包版本，建议可以按照这个编译方法，编译自己需要的cuda+cudnn+trt 版本的编译包：
https://paddleinference.paddlepaddle.org.cn/user_guides/source_compile.html#windows-10
trt8各平台版本预编译包排在研发排期中，但需要一定周期，请理解。
