### ISSUE TITLE
PaddleDetection预测的时候报错，我融入了两个模型

### ISSUE THREAD

**Issue by pussss** [PaddlePaddle/Paddle#38706]
ExternalError:  Cuda error(719), unspecified launch failure.
      [Advise: Please search for the error code(719) on website( https://docs.nvidia.com/cuda/archive/10.0/cuda-runtime-api/group__CUDART__TYPES.html#group__CUDART__TYPES_1g3f51e3575c2178246db0a94a430e0038 ) to get Nvidia's official solution about CUDA Error.] (at C:\home\workspace\Paddle_release3\paddle\fluid\platform\stream\cuda_stream.cc:95)
      [operator < multiclass_nms > error]
![image](https://user-images.githubusercontent.com/86936794/148150172-63a04f9e-2413-4719-bdf5-bd62cdcd9661.png)

**Comment by cxxly** [comment]
您好，请提供下复现该问题软硬环境信息和最小代码，方便我们定位问题。

**Comment by pussss** [comment]
> 



> 您好，请提供下复现该问题软硬环境信息和最小代码，方便我们定位问题。

好的，cuda版本为10.2，paddlepaddle-gpu 为2.1.2，paddlex 为2.0.0rc4，
![image](https://user-images.githubusercontent.com/86936794/148154177-1ea8d7ba-3008-4aa5-97e6-89ff198196ef.png)
![image](https://user-images.githubusercontent.com/86936794/148154265-1ac9e1ef-a8da-43d5-873b-7e2e00ca2b45.png)
![image](https://user-images.githubusercontent.com/86936794/148154273-50773259-1069-4682-888a-cf89b0626530.png)
![image](https://user-images.githubusercontent.com/86936794/148154335-2223a2ed-6daa-4164-8ea7-dcedc95b2548.png)

**Comment by heavengate** [comment]
看报错信息是CUDA launch报错，你是不是使用了多进程做预测部署，使用多进程的话需要每个子进程创建自己单独的Predictor

**Comment by pussss** [comment]
> 看报错信息是CUDA launch报错，你是不是使用了多进程做预测部署，使用多进程的话需要每个子进程创建自己单独的Predictor
我确实是使用了多进程，“每个子进程创建自己单独的Predictor” 这个能详细点吗，我不太理解具体的
