### ISSUE TITLE
C++编译库的预测问题

### ISSUE THREAD

**Issue by blackhitomi** [PaddlePaddle/Paddle#38700]
- 版本、环境信息：
    1）PaddlePaddle版本：paddle 2.0
    2）CPU：\
    3）GPU：1080ti、k40c
    4）系统环境：ubuntu 18.04

请问，我在1080ti上编译好的.so文件为什么没法用在k40c上，除了显卡和驱动不一样，cuda版本都是10.1的，cudnn7.6.5以及NVCC版本全部一样。
在1080ti上编译好了，可以正确执行paddleocr的预测，而k40c上预测出一堆乱码。（不启用GPU则可以正确检测）

此外，jetson nano上编译的也只能用在nano上，没法用在jetson nx上，是否也是一样的原因？

**Comment by cuicheng01** [comment]
您好，可以在详细描述下问题吗？编译的什么so文件呢？编译流程是按照哪个文档走的呢？

**Comment by blackhitomi** [comment]
> 您好，可以在详细描述下问题吗？编译的什么so文件呢？编译流程是按照哪个文档走的呢？



> 您好，可以在详细描述下问题吗？编译的什么so文件呢？编译流程是按照哪个文档走的呢？

您好，编译的2.0版本的paddle，c++库，libpaddle_inference.so文件。编译流程按照官方文档走的，编译好的库文件用来跑2.0-rc1版本的paddleocr的，用在编译的机器上没问题，用在另外一台不同显卡的机器上ocr识别有问题

**Comment by blackhitomi** [comment]
> 您好，可以在详细描述下问题吗？编译的什么so文件呢？编译流程是按照哪个文档走的呢？



> 您好，可以在详细描述下问题吗？编译的什么so文件呢？编译流程是按照哪个文档走的呢？

您好，编译的2.0版本的paddle，c++库，libpaddle_inference.so文件。编译流程按照官方文档走的，编译好的库文件用来跑2.0-rc1版本的paddleocr的，用在编译的机器上没问题，用在另外一台不同显卡的机器上ocr识别有问题

**Comment by cuicheng01** [comment]
您好，这两台其他硬件环境是否一致呢？编译时的选项是不是只适合第一台机器呢？

**Comment by blackhitomi** [comment]
硬件显卡不一样，但是cuda和cudnn版本一样，编译的架构默认的all

**Comment by cuicheng01** [comment]
您把两台机器具体的硬件信息、cuda、cudnn版本、编译命令贴一下吧，方便我们定位问题~以及再确认下，目前是只编译预测库的问题还是编译整个Paddle的问题呢？

**Comment by Wangzheee** [comment]
编译预测库的时候有个命令是-DCUDA_ARCH_NAME 默认是Auto，会根据硬件架构自动检测。您的1080ti是图灵架构、k40c是特斯拉架构，所以编译的产出不能通用。可以编译的时候加上-DCUDA_ARCH_NAME = All 就可以编译所有架构的产出

**Comment by blackhitomi** [comment]
> 

感觉，确实是这样，已经可以用了！太感谢了
不过他们文档上怎么写的默认是All呢
