### ISSUE TITLE
【论文复现】self.apply()和初始化实现问题

### ISSUE THREAD

**Issue by Lieberk** [PaddlePaddle/Paddle#38701]
以下是pytorch代码
<img width="372" alt="0e0b5c5a07aeff79c2e7ca189500346" src="https://user-images.githubusercontent.com/57614716/148085233-f2dfcdf7-5b91-42a6-a02d-11e3472ce6f9.png">

我这里有两个问题麻烦老师解决一下：
1. 我想问一下pytorch的self.apply()功能在paddle有没有对应的实现方式？
2. 上述pytorch的nn.init.constant_功能用paddle如何实现？上述的_init_weights(）用paddle应该怎么实现？

**Comment by cuicheng01** [comment]
您好，您可以参考[SwinTransformer](https://github.com/PaddlePaddle/PaddleClas/blob/release/2.3/ppcls/arch/backbone/model_zoo/swin_transformer.py#L699)
来实现`self.apply()`和`_init_weights()`，pytorch中的的`nn.init.constant_`可以参考[Constant初始化](https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/nn/initializer/Constant_cn.html#constant)。

**Comment by Lieberk** [comment]
> 您好，您可以参考[SwinTransformer](https://github.com/PaddlePaddle/PaddleClas/blob/release/2.3/ppcls/arch/backbone/model_zoo/swin_transformer.py#L699) 来实现`self.apply()`和`_init_weights()`，pytorch中的的`nn.init.constant_`可以参考[Constant初始化](https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/nn/initializer/Constant_cn.html#constant)。
 
已解决，感谢老师~
