### ISSUE TITLE
训练时完成一个epoch后总会崩溃停止训练

### ISSUE THREAD

**Issue by panicwq** [PaddlePaddle/Paddle#38711]
- 标题：在尝试官方提供的蔬菜分类和工业指针表计读数案例时，都出现了训练了一个epoch后崩溃停止训练
- 版本、环境信息：
    1）PaddlePaddle版本：PaddlePaddle-gpu 2.2.1  paddlex 2.0.0
     2）GPU：GTX 1650Ti CUDA10.3 cudnn8.2.2
    4）系统环境：win0 python3.8
- 训练信息
    1）单机，单卡
    2）4G显存
    3）蔬菜分类训练参数都是默认值，工业表计读数batchsize为1
- 具体问题：
1、spyder运行：
![image](https://user-images.githubusercontent.com/43361466/148156469-9fece1e0-58e3-4c8e-8efe-39287c70185a.png)
2、终端运行
![image](https://user-images.githubusercontent.com/43361466/148156614-e168c4a1-1fc4-4003-aca0-10de23117f21.png)

**Comment by cxxly** [comment]
您好，案例链接和复现代码辛苦提供下，我们本地复现下。

**Comment by cxxly** [comment]
看到你在另一个issue https://github.com/PaddlePaddle/Paddle/issues/38704 提了，是同一个问题吧

**Comment by panicwq** [comment]
> 发现你在另一个问题#38704提了，是同一个问题吧

不是同一个问题

**Comment by cxxly** [comment]
@FlyingQianMM

**Comment by FlyingQianMM** [comment]
1、PaddleX请升级至2.1.0
2、请使用PaddleX动态图训练脚本，https://github.com/PaddlePaddle/PaddleX/tree/develop/tutorials/train
3、如果安装的paddlepaddle_gpu是针对cuda10.2，例如：
![image](https://user-images.githubusercontent.com/22235422/148176015-52c26510-3bc1-479f-ab18-a85c15c44b5e.png)
试下降cuda版本至10.2，降cudnn版本至7.6.5
![image](https://user-images.githubusercontent.com/22235422/148176107-5d4f07ec-46b6-4962-8778-f337b3cfb954.png)

**Comment by FlyingQianMM** [comment]
该问题用户已在PaddleX github提了相同的issue，PaddlePaddle/PaddleX#1333 。
问题解答将直接至PaddlePaddle/PaddleX#1333 进行
