### ISSUE TITLE
paddlepaddle分布式环境部署和超大规模稀疏特征embedding的训练？

### ISSUE THREAD

**Issue by stevekd** [PaddlePaddle/Paddle#38727]
1 我自己的集群如何分布式环境部署？
2 我现在是个简单模型，但是要训练出上亿节点的稀疏ID-embedding，采用paddlepaddle的哪种分布式的训练方法

之前https://www.paddlepaddle.org.cn/documentation/docs/zh/api_guides/low_level/distributed/large_scale_sparse_feature_training.html
说的是Fluid支持千亿量级超大规模稀疏特征embedding的训练，embedding参数只会保存在parameter server上，通过 参数prefetch和梯度稀疏更新的方法，大大减少通信量，提高通信速度。

fluid可以支持，那么现在fleetx如何使用呢？

**Comment by sandyhouse** [comment]
https://fleet-x.readthedocs.io/en/latest/paddle_fleet_rst/parameter_server/index.html ps使用可以参考这个文档。
