### ISSUE TITLE
Cmake warning on develop branch

### ISSUE THREAD

**Issue by typhoonzero** [PaddlePaddle/Paddle#3872]
On current develop branch, when run `cmake` it prints the following warning message:

```
CMake Warning at paddle/operators/CMakeLists.txt:35 (message):
  The op library net_op not support GPU!
Call Stack (most recent call first):
  paddle/operators/CMakeLists.txt:56 (op_library)
```

~~Maybe related with: https://github.com/PaddlePaddle/Paddle/pull/3801~~

**Comment by luotao1** [comment]
I think this warning message can be removed. Or using a not-warning message to instead it.
#3801 doesn't change these lines.
