### ISSUE TITLE
在编译paddlepaddle的c++版本中使用make指令时候报错

### ISSUE THREAD

**Issue by wumuyu9** [PaddlePaddle/Paddle#38722]
在编译paddlepaddle的c++cpu版本中使用make指令时候报错，最开始是git无法clone thirty_party，修改了https:/...为git://...之后仍然报如下错误，不管是使用docker安装还是普通虚拟机安装。

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

HEAD is now at 9f75c5aa8 Merge pull request #2337 from sergiocampama/deprecation
Submodule 'third_party/benchmark' (https://github.com/google/benchmark.git) registered for path 'third_party/benchmark'
Cloning into '/paddle/Paddle/build/third_party/protobuf/src/extern_protobuf/third_party/benchmark'...
fatal: unable to access 'https://github.com/google/benchmark.git/': gnutls_handshake() failed: Error in the pull function.
fatal: clone of 'https://github.com/google/benchmark.git' into submodule path '/paddle/Paddle/build/third_party/protobuf/src/extern_protobuf/third_party/benchmark' failed
Failed to clone 'third_party/benchmark'. Retry scheduled
Cloning into '/paddle/Paddle/build/third_party/protobuf/src/extern_protobuf/third_party/benchmark'...
fatal: unable to access 'https://github.com/google/benchmark.git/': Failed to connect to github.com port 443: Connection refused
fatal: clone of 'https://github.com/google/benchmark.git' into submodule path '/paddle/Paddle/build/third_party/protobuf/src/extern_protobuf/third_party/benchmark' failed
Failed to clone 'third_party/benchmark' a second time, aborting
CMake Error at /paddle/Paddle/build/third_party/protobuf/tmp/extern_protobuf-gitclone.cmake:52 (message):
  Failed to update submodules in:
  '/paddle/Paddle/build/third_party/protobuf/src/extern_protobuf'

CMakeFiles/extern_protobuf.dir/build.make:90: recipe for target 'third_party/protobuf/src/extern_protobuf-stamp/extern_protobuf-download' failed
make[2]: *** [third_party/protobuf/src/extern_protobuf-stamp/extern_protobuf-download] Error 1
CMakeFiles/Makefile2:3003: recipe for target 'CMakeFiles/extern_protobuf.dir/all' failed
make[1]: *** [CMakeFiles/extern_protobuf.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2

其中/thirty/protobuf/tmp/extern_protobuf-gitclone.cmake内容如下

if(NOT "/paddle/Paddle/build/third_party/protobuf/src/extern_protobuf-stamp/extern_protobuf-gitinfo.txt" IS_NEWER_THAN "/paddle/Paddle/build/third_party/protobuf/src/extern_protobuf-stamp/extern_protobuf-gitclone-lastrun.txt")
  message(STATUS "Avoiding repeated git clone, stamp file is up to date: '/paddle/Paddle/build/third_party/protobuf/src/extern_protobuf-stamp/extern_protobuf-gitclone-lastrun.txt'")
  return()
endif()

execute_process(
  COMMAND ${CMAKE_COMMAND} -E remove_directory "/paddle/Paddle/build/third_party/protobuf/src/extern_protobuf"
  RESULT_VARIABLE error_code
  )
if(error_code)
  message(FATAL_ERROR "Failed to remove directory: '/paddle/Paddle/build/third_party/protobuf/src/extern_protobuf'")
endif()

# try the clone 3 times in case there is an odd git clone issue
set(error_code 1)
set(number_of_tries 0)
while(error_code AND number_of_tries LESS 3)
  execute_process(
    COMMAND "/usr/bin/git"  clone --no-checkout "git://github.com/protocolbuffers/protobuf.git" "extern_protobuf"
    WORKING_DIRECTORY "/paddle/Paddle/build/third_party/protobuf/src"
    RESULT_VARIABLE error_code
    )
  math(EXPR number_of_tries "${number_of_tries} + 1")
endwhile()
if(number_of_tries GREATER 1)
  message(STATUS "Had to git clone more than once:
          ${number_of_tries} times.")
endif()
if(error_code)
  message(FATAL_ERROR "Failed to clone repository: 'https://github.com/protocolbuffers/protobuf.git'")
endif()

execute_process(
  COMMAND "/usr/bin/git"  checkout 9f75c5aa851cd877fb0d93ccc31b8567a6706546 --
  WORKING_DIRECTORY "/paddle/Paddle/build/third_party/protobuf/src/extern_protobuf"
  RESULT_VARIABLE error_code
  )
if(error_code)
  message(FATAL_ERROR "Failed to checkout tag: '9f75c5aa851cd877fb0d93ccc31b8567a6706546'")
endif()

set(init_submodules TRUE)
if(init_submodules)
  execute_process(
    COMMAND "/usr/bin/git"  submodule update --recursive --init 
    WORKING_DIRECTORY "/paddle/Paddle/build/third_party/protobuf/src/extern_protobuf"
    RESULT_VARIABLE error_code
    )
endif()
if(error_code)
  message(FATAL_ERROR "Failed to update submodules in: '/paddle/Paddle/build/third_party/protobuf/src/extern_protobuf'")
endif()

# Complete success, update the script-last-run stamp file:
#
execute_process(
  COMMAND ${CMAKE_COMMAND} -E copy
    "/paddle/Paddle/build/third_party/protobuf/src/extern_protobuf-stamp/extern_protobuf-gitinfo.txt"
    "/paddle/Paddle/build/third_party/protobuf/src/extern_protobuf-stamp/extern_protobuf-gitclone-lastrun.txt"
  RESULT_VARIABLE error_code
  )
if(error_code)
  message(FATAL_ERROR "Failed to copy script-last-run stamp file: '/paddle/Paddle/build/third_party/protobuf/src/extern_protobuf-stamp/extern_protobuf-gitclone-lastrun.txt'")
endif()

**Comment by cxxly** [comment]
从报错信息看到是下载第三方依赖失败，Paddle编译需要从Github上下载一些第三方依赖，需要配置个代理
```python
fatal: unable to access 'https://github.com/google/benchmark.git/': gnutls_handshake() failed: Error in the pull function.
fatal: clone of 'https://github.com/google/benchmark.git' into submodule path '/paddle/Paddle/build/third_party/protobuf/src/extern_protobuf/third_party/benchmark' failed
Failed to clone 'third_party/benchmark'. Retry scheduled
Cloning into '/paddle/Paddle/build/third_party/protobuf/src/extern_protobuf/third_party/benchmark'...
fatal: unable to access 'https://github.com/google/benchmark.git/': Failed to connect to github.com port 443: Connection refused
fatal: clone of 'https://github.com/google/benchmark.git' into submodule path
```

**Comment by wumuyu9** [comment]
这有没有调整源的方法，比如gitee，或者将https://***.git改成git://***.git，通常我使用这种方法都可以下载github中的库，但是在这个third_party下我没有找到benchmark文件夹，但是有像protobuf文件夹，这些文件夹中有src文件夹，文件夹中存在.cmake文件，可以修改源

**Comment by wumuyu9** [comment]
> 从报错信息看到是下载第三方依赖失败，Paddle编译需要从Github上下载一些第三方依赖，需要配置个代理
> 
> ```python
> fatal: unable to access 'https://github.com/google/benchmark.git/': gnutls_handshake() failed: Error in the pull function.
> fatal: clone of 'https://github.com/google/benchmark.git' into submodule path '/paddle/Paddle/build/third_party/protobuf/src/extern_protobuf/third_party/benchmark' failed
> Failed to clone 'third_party/benchmark'. Retry scheduled
> Cloning into '/paddle/Paddle/build/third_party/protobuf/src/extern_protobuf/third_party/benchmark'...
> fatal: unable to access 'https://github.com/google/benchmark.git/': Failed to connect to github.com port 443: Connection refused
> fatal: clone of 'https://github.com/google/benchmark.git' into submodule path
> ```

这有没有调整源的方法，比如gitee，或者将https://***.git改成git://***.git，通常我使用这种方法都可以下载github中的库，但是在这个third_party下我没有找到benchmark文件夹，但是有像protobuf文件夹，这些文件夹中有src文件夹，文件夹中存在.cmake文件，可以修改源
