### ISSUE TITLE
Lod Tensor使用Embedding时出现 Expected ids_dim.size() == 2, but received ids_dim.size():3

### ISSUE THREAD

**Issue by Li-Jiajie** [PaddlePaddle/Paddle#38721]
版本2.2.1
sparse部分定义的主要代码如下
sparse_input_ids = [
            paddle.paddle.static.data(name="C" + str(i), shape=[None, 10], lod_level=1, dtype="int64")
            for i in range(1, self.sparse_inputs_slot)
        ]
sparse_var = paddle.unsqueeze(sparse_var, axis=2)
            embedding_out = paddle.paddle.static.nn.sparse_embedding(input=sparse_var, size=[self.sparse_feature_number, self.sparse_feature_dim])
但会出现以下错误：
![image](https://user-images.githubusercontent.com/35255760/148189057-3b02d198-6f23-4c47-90f4-afce1a2bebed.png)

不用LoD时，就可以正常训练，请问是我哪里的用法有问题吗？
因为样本里一个Slot下会有多个且不定数量的key，希望通过LoD来做Embedding，得到Embedding后将变长的进行sum得到一致的shape再进入后续的网络

**Comment by cxxly** [comment]
您好，提供下环境信息和最小复现代码集，方便我们复现问题。

**Comment by Li-Jiajie** [comment]
> 

这个问题可能是哪个方向有错误呢，Ids是指啥？（我是ps CPU模式，paddle 2.2.1）
先想请教下我这样的用法对不对：样本里一个Slot会有多个key，这些key都需要look up出embedding结果，然后把同一slot id下多个key的embedding结果sum得到一个tensor，再做后续操作
这种需求是应该用lod吗
lod应该如下定义吗，lod_level=1? 
paddle.paddle.static.data(name="C" + str(i), shape=[None, 10], lod_level=1, dtype="int64")

每个lod对应一个Slot下的多个key，使用前会增加一维得到[BatchSize, KeyNums, 1]
经sparse_embedding后得到[batchsize, KeyNums, dim]
sum后得到[batchsize, dim]
然后做后面的处理，其中KeyNums对于每个样本都是不一样的

**Comment by cxxly** [comment]
> 

1）从上述代码示例看不出问题，ids没有上下文，不太清楚，上述代码是你参考的一些示例？ 2）你的第二个问题可以参考下https://www.paddlepaddle.org.cn/documentation/docs/zh/faq/2.0.html 3) padde2.x LodTensor会逐步废弃，替代方案可以参考 https://www.paddlepaddle.org.cn/documentation/docs/zh/faq/2.0.html padding/bucketing
