### ISSUE TITLE
LSTM  使用 delattr 删除属性，会生成一个其他的属性

### ISSUE THREAD

**Issue by FightingFrogg** [PaddlePaddle/Paddle#38735]
class MyLayer(paddle.nn.Layer):
        def __init__(self):
            super(MyLayer, self).__init__()
            self.lstm1 = paddle.nn.LSTM(400, 200)
            self.lstm2 = paddle.nn.LSTM(600, 300)
            delattr(self.lstm1, 'bias_hh_l0')
    
        def forward(self, input):
            pass
    
    mylayer = MyLayer()
    for name, param in mylayer.named_parameters():
        print(name)
结果删除了'bias_hh_l0'属性，但是却生成一个’lstm1.0.cell.bias_hh ‘

    lstm1.weight_ih_l0
    lstm1.weight_hh_l0
    lstm1.bias_ih_l0
    lstm1.0.cell.bias_hh
    lstm2.weight_ih_l0
    lstm2.weight_hh_l0
    lstm2.bias_ih_l0
    lstm2.bias_hh_l0

**Comment by tianxin1860** [comment]
您好，请问具体需求是什么？为什么需要删除 `bias_hh_l0` 这个属性？如果强行删除的话，会自动再生成 1 个 bias 属性。
