### ISSUE TITLE
同一份输入数据（两种产出方式）在相同上下文中运行paddle executor.run() 耗时差一倍

### ISSUE THREAD

**Issue by HC-2016** [PaddlePaddle/Paddle#38742]
问题的背景：
基于profiler进行paddle模型算子性能分析时，发现profile统计的模型耗时总时长远小于time.start 统计的耗时
<img width="900" alt="0669c69776147d4318e080aa8996bde8" src="https://user-images.githubusercontent.com/22096916/148321587-42cddd66-a82a-4e88-8f5b-28ffa8f15234.png">

<img width="933" alt="aac6048f3f5a73a985df444a5feefe01" src="https://user-images.githubusercontent.com/22096916/148321606-46bc39eb-357d-4621-a998-d9c0008df1e6.png">

进一步分析。通过将输入数据存储为json文件读取（fake data）和正常数据输入流（index_data）作为输入进行比较，发现输入数据值相同的情况下，耗时差异巨大。另外，fake data情况下profile统计耗时和time.start 统计的耗时基本一致。
![10a3299dbe8a6d65f1e321c28ec625bb](https://user-images.githubusercontent.com/22096916/148321986-a36b7a3c-b7ad-45f1-b597-0befbcaabeb2.jpg)

**Comment by tianxin1860** [comment]
请问两种产出方式有什么区别？2 中方式产出后的数据有什么区别？
