### ISSUE TITLE
F.pad 不支持 2D Tensor

### ISSUE THREAD

**Issue by yt605155624** [PaddlePaddle/Paddle#38758]
torch 在 mode == "constant"（默认模式）其实是可以支持 2D Tensor 的，如下所示
https://github.com/pytorch/pytorch/blob/b0fdca885547efedddc4e9cfe78a5e0d7838e9f0/torch/nn/functional.py#L4339
希望修一下，因为在模型里面随便引入 numpy pad 之后再 to_tensor 的话，动转静可能是会有问题的
增加一个维度再 pad 再 squeeze 未免过于丑陋

**Comment by tianxin1860** [comment]
您好，建议使用 paddle.nn.functional.pad api 直接对 2d tensor 进行 pad 操作
