### ISSUE TITLE
sparse_tensor 问题

### ISSUE THREAD

**Issue by Andy1314Chen** [PaddlePaddle/Paddle#38768]
请问, PaddlePaddle 现在有支持 sparse tensor 吗?  类似 pytorch 的 torch.sparse_coo_tensor 和 tensorflow 的 SparseTensor?

API 文档中没有找到类似描述及说明。

**Comment by tianxin1860** [comment]
您好，这个功能我们正在开发，预计 3 月份在 develop 分支支持该功能，欢迎持续关注~

**Comment by Andy1314Chen** [comment]
好的,  支持国产深度学习框架
