### ISSUE TITLE
Paddle Inference python能推理，像使用mkldnn功能，但是报错

### ISSUE THREAD

**Issue by leiqing1** [PaddlePaddle/Paddle#38778]
使用python接口进行推理，通过config.enable_mkldnn()配置
报如下错误：

python3 python_demo.py --model_file ./resnet50/inference.pdmodel --params_file ./resnet50/inference.pdiparams --batch_size 2
E0106 23:22:01.993271 338939392 analysis_config.cc:306] Please compile with MKLDNN first to use MKLDNN
False
Traceback (most recent call last):
  File "python_demo.py", line 72, in <module>
    main()
  File "python_demo.py", line 19, in main
    config.set_mkldnn_cache_capacity(1)
AttributeError: 'paddle.fluid.core_avx.AnalysisConfig' object has no attribute 'set_mkldnn_cache_capacity'

我理解安装了飞桨框架，不是就能跑飞桨推理吗？
我电脑环境：
Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz

<img width="311" alt="图片" src="https://user-images.githubusercontent.com/54695910/148408774-801635cf-b958-409b-81ea-6bb0876b2c72.png">

**Comment by tianxin1860** [comment]
您好，请问使用的 Paddle 版本是? 能否提供最小可复现环境？

**Comment by fengxiaoshuai** [comment]
你需要安装推理框架：https://paddleinference.paddlepaddle.org.cn/user_guides/download_lib.html

**Comment by fengxiaoshuai** [comment]
不过目前没有mac支持mkl的库

**Comment by LoadingBFX** [comment]
我已在 jetson xavier NX 上安装推理框架Jetpack4.4(4.5): nv_jetson-cuda10.2-trt7-xavier, (paddle v2.2.1) 但是依旧获得AttributeError: 'paddle.fluid.core_noavx.AnalysisConfig' object has no attribute 'set_mkldnn_cache_capacity'. 请问这是什么原因?

**Comment by LarchLiu** [comment]
我也遇到同样的问题，版本`paddle v2.3.1`
我是用的 [PaddleRs](https://github.com/PaddlePaddle/PaddleRS) 官方教程 `classification/resnet50_vd` 训练后推理出现 Warning 。

```
2022-07-23 18:20:44 [WARNING]   The current environment does not support MKL-DNN, MKL-DNN is disabled.
```

https://github.com/PaddlePaddle/PaddleRS/blob/05e1eeee6eb7a31ef5e1299f32f09b067e2f7e85/paddlers/deploy/predictor.py#L129-L138

@tianxin1860 
> 您好，请问使用的 Paddle 版本是? 能否提供最小可复现环境？

安装 [EISeg](https://github.com/PaddlePaddle/PaddleSeg/tree/release/2.6/EISeg) 启动时就会报错

```
E0723 18:25:37.643397 204861440 analysis_config.cc:389] Please compile with MKLDNN first to use MKLDNN
--- Running analysis [ir_graph_build_pass]
--- Running analysis [ir_graph_clean_pass]
--- Running analysis [ir_analysis_pass]
```

https://github.com/PaddlePaddle/Paddle/blob/6b6f7a217b442acaec97f3fccaa04baaa6de2b45/paddle/fluid/inference/api/analysis_config.cc#L426-L435

是不是 mac 版本编译的时候就没开启 `PADDLE_WITH_MKLDNN` ，不支持 mkldnn ?

![WX20220723-184538](https://user-images.githubusercontent.com/4410452/180601891-edcb2679-02ba-4310-ab6f-f2619058a538.png)

**Comment by yaoyi2008** [comment]
同问，我也是MacOS，也是报类似的错，用的还是官方的例子。

用的paddlenlp版本为2.5.0，Python版本3.10.9，macOS版本12.6.2

<img width="654" alt="image" src="https://user-images.githubusercontent.com/5906825/212360148-133e1cd0-7615-4cbc-ac5b-a328beb03daf.png">


执行代码
```
from pprint import pprint
from paddlenlp import Taskflow

schema = ['时间', '人物', '赛事名称']
ie = Taskflow('information_extraction', schema=schema)
pprint(ie('2月8日上午北京冬奥会自由式滑雪女子大跳台决赛中中国选手谷爱凌以188.25分获得金牌！'))
```

输出结果
```
/Users/xxx/PycharmProjects/pp_nlp/venv/lib/python3.10/site-packages/_distutils_hack/__init__.py:36: UserWarning: Setuptools is replacing distutils.
  warnings.warn("Setuptools is replacing distutils.")
E0113 23:34:58.039547 211301888 analysis_config.cc:563] Please compile with MKLDNN first to use MKLDNN
[2023-01-13 23:34:59,445] [    INFO] - We are using <class 'paddlenlp.transformers.ernie.tokenizer.ErnieTokenizer'> to load '/Users/xxx/.paddlenlp/taskflow/information_extraction/uie-base'.
[{'时间': [{'end': 6,
          'probability': 0.9857378532924486,
          'start': 0,
          'text': '2月8日上午'}],
  '赛事名称': [{'end': 23,
            'probability': 0.8503083913824838,
            'start': 6,
            'text': '北京冬奥会自由式滑雪女子大跳台决赛'}],
  '选手': [{'end': 31,
          'probability': 0.8981546274821781,
          'start': 28,
          'text': '谷爱凌'}]}]
```

报错中的关键信息
`E0113 23:34:58.039547 211301888 analysis_config.cc:563] Please compile with MKLDNN first to use MKLDNN
`

**Comment by UnbeatableYun** [comment]
用的paddlenlp版本为2.8.0.post0，Python版本3.8.10，win10
执行代码
`from pprint import pprint
from paddlenlp import Taskflow
docprompt = Taskflow("document_intelligence")
pprint(docprompt([{"doc": "https://bj.bcebos.com/paddlenlp/taskflow/document_intelligence/images/invoice.jpg", "prompt": ["发票号码是多少?", "校验码是多少?"]}]))`


输出结果
mypath\venv\lib\site-packages\_distutils_hack\__init__.py:26: UserWarning: Setuptools is replacing distutils.
  warnings.warn("Setuptools is replacing distutils.")
E0618 14:35:57.260792 24888 analysis_config.cc:653] Please compile with MKLDNN first to use MKLDNN
Traceback (most recent call last):
  File "mypath/utils/document_intelligence_test.py", line 4, in <module>
    docprompt = Taskflow("document_intelligence")
  File "mypath\venv\lib\site-packages\paddlenlp\taskflow\taskflow.py", line 804, in __init__
    self.task_instance = task_class(
  File "mypath\venv\lib\site-packages\paddlenlp\taskflow\document_intelligence.py", line 68, in __init__
    self._get_inference_model()
  File "mypath\venv\lib\site-packages\paddlenlp\taskflow\task.py", line 372, in _get_inference_model
    self._prepare_static_mode()
  File "mypath\venv\lib\site-packages\paddlenlp\taskflow\task.py", line 227, in _prepare_static_mode
    self.predictor = paddle.inference.create_predictor(self._config)
RuntimeError: (NotFound) Operator (one_hot) is not registered.
  [Hint: op_info_ptr should not be null.] (at ..\paddle/fluid/framework/op_info.h:152)


Process finished with exit code 1
