### ISSUE TITLE
可视化卷积结果，类似 torch 的 make_grid()

### ISSUE THREAD

**Issue by 670133189** [PaddlePaddle/Paddle#38773]
请问 paddle 如何可视化卷积结果，类似 torch 的 make_grid()

![conv1_1](https://user-images.githubusercontent.com/18096556/148384027-d1021019-d580-41e0-a94f-bd17bfa7a267.jpg)

**Comment by tianxin1860** [comment]
您好，这个高层 API 暂未支持，我们会内部发起评估进行排期支持，欢迎关注。

**Comment by qingqing01** [comment]
@670133189 目前没有这种API，也可以参考 下面连接，直接用plt 画图时拼接下~

https://aistudio.baidu.com/aistudio/projectdetail/1086168?channelType=0&channel=0
