### ISSUE TITLE
请问paddle fluid是否支持cpu：inter Pentium G5400T

### ISSUE THREAD

**Issue by onecatcn** [PaddlePaddle/Paddle#38784]

**Comment by esythan** [comment]
安装所需的环境请参考https://www.paddlepaddle.org.cn/install/quick?docurl=/documentation/docs/zh/install/pip/linux-pip.html

**Comment by adaxiadaxi** [comment]
@onecatcn 同学您好，应该是在支持范围的，Intel的CPU大部分都在支持范围，但是您说的这款我们没有验证过。同学您这边可以基于上方的安装文档，尝试安装paddle，如果有问题可以在该issue下继续贴图提问。
