### ISSUE TITLE
docker中直接pip install paddlepaddle安装error的问题

### ISSUE THREAD

**Issue by AlisaChen98** [PaddlePaddle/Paddle#38780]
- 版本、环境信息：
    1）PaddlePaddle版本：paddlepaddle 2.2.1
    2）CPU：非必要
    3）GPU：非必要
- 安装方式信息：
1）编写本地基于python的paddlepaddle应用
2）将1）中的应用打包进docker，dockerfile如下
```
# 基础镜像，配置python版本
FROM python:3.7
# FROM paddlepaddle/paddle:2.2.1
# 维护者
MAINTAINER alisachen alisachen0214@163.com

# 指定工作目录
WORKDIR /

# 拷贝应用文件到容器中
COPY . /

# 需要的参数给一个初始值
# example: --monitor_path={docker_mount_volume_Path}

ENV PARAMS=""

# 安装应用所需要的依赖,-i https://pypi.tuna.tsinghua.edu.cn/simple
RUN pip install --upgrade pip
RUN pip install -r requirements.txt -i https://pypi.tuna.tsinghua.edu.cn/simple

# 暴露docker image的端口
EXPOSE 4040

CMD python3 local.py $PARAMS
```
3）上述dockerfiler用到的requirements.txt为
```
paddlepaddle
numpy>=1.19.2
scipy==1.6.1
tqdm==4.59.0
librosa==0.8.0
python-Levenshtein==0.12.2
visualdl>=2.1.1
SoundFile~=0.10
resampy==0.2.2
python_speech_features==0.6
zhconv==1.4.2
lac
flask
flask_cors
cn2an
audioread
pydub
webrtcvad
watchdog
moviepy
```
4）生成dockerimage时报错，找不到对应版本的paddlepaddle
![image](https://user-images.githubusercontent.com/45112983/148482790-804783fc-4ab2-4092-a45b-a208d6945fa1.png)

**Comment by esythan** [comment]
建议更换一下pip的源，使用python -m pip install paddlepaddle==2.2.1 -i https://mirror.baidu.com/pypi/simple进行安装

**Comment by AlisaChen98** [comment]
> 建议更换一下pip的源，使用python -m pip install paddlepaddle==2.2.1 -i [https://mirror.baidu.com/pypi/simple进行安装](https://mirror.baidu.com/pypi/simple%E8%BF%9B%E8%A1%8C%E5%AE%89%E8%A3%85)

您好，还是不可以呢
![image](https://user-images.githubusercontent.com/45112983/148672711-3ff2c64f-3d75-4d4e-919f-dc7000d3aecf.png)

**Comment by esythan** [comment]
看下pip的版本，要求pip 或 pip3 版本 20.2.2或更高版本 (64 bit)

**Comment by AlisaChen98** [comment]
在安装前先升级了pip版本的～


| |
AlisaChen
|
|
***@***.***
|
签名由网易邮箱大师定制


在2022年01月10日 ***@***.***> 写道：

看下pip的版本，要求pip 或 pip3 版本 20.2.2或更高版本 (64 bit)

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by dingjiaweiww** [comment]
您换用python3 试试：python3 -m pip install paddlepaddle==2.2.1 -i https://mirror.baidu.com/pypi/simple

**Comment by AlisaChen98** [comment]
> 您换用python3 试试：python3 -m pip install paddlepaddle==2.2.1 -i https://mirror.baidu.com/pypi/simple

您好还是不行诶
![image](https://user-images.githubusercontent.com/45112983/148729744-0ec7c425-6192-4584-ab26-97834241f784.png)

**Comment by esythan** [comment]
可能是requirements.txt中的某些包和paddle发生了冲突
建议排查方式：直接拉取base镜像升级pip后单独安装paddle尝试一下，或者修改一下dockerfile，不要用requirements.txt，直接单独安装paddle
