### ISSUE TITLE
论文复现】 将pytorch 换成 paddle 后显存不够，调小batch_size仍不够

### ISSUE THREAD

**Issue by xinyu12138** [PaddlePaddle/Paddle#38781]
PaddlePaddle版本：2.2.1  GPU：cuda 11.2  ubuntu 20
- 训练信息
    1）单机，单卡
    2）显存信息 显卡共24G内存

复现的过程中仅将pytorch中的相应的函数替换成了paddle，且在cpu上能运行成功，但在gpu上报错显存不够。
![微信截图_20220107105706](https://user-images.githubusercontent.com/45567402/148484400-2d4f7a3b-2f81-40e9-ad12-8369bb9b9ca3.png)
在训练文件train.py中仅仅将 
model  = model.cuda() 【pytorch】  -> model.to('gpu') 【paddle】
其它的都没变， 将batch_size 调整为1 也显示显存不够

**Comment by esythan** [comment]
建议提供完整代码方便排查
