### ISSUE TITLE
模型参数保存，损失函数不断上升。

### ISSUE THREAD

**Issue by CPones** [PaddlePaddle/Paddle#38791]
paddle.save保存结果文件时，训练过程中的loss曲线是正常下降的。

paddle.jit.save保存结果文件，训练过程中的loss曲线却是不断上升。

为什么会这样？

如果要使用paddle.jit.save保存参数，

同时保证训练过程中损失函数下降，

有什么建议吗？

训练曲线如图[https://aistudio.baidu.com/paddle/forum/topic/show/993187](url)

**Comment by esythan** [comment]
建议提供更详细的代码方便排查，理论上模型保存不会影响训练的损失

**Comment by CPones** [comment]
已解决，在网络模型构建时，所有的forward前都应该添加@paddle.jit.to_static。
