### ISSUE TITLE
pytoch转paddle，重构covn2D遇到的问题

### ISSUE THREAD

**Issue by d2623587501** [PaddlePaddle/Paddle#38790]
重构covn2D遇到的问题：
self.weight = self.weight * self.mask
无法更改self.weight
报错：TypeError: assignment to parameter 'weight' should be of type Parameter or None, but got 'Tensor'
源码如下：
`class MaskedConv2d(nn.Conv2D):
    def __init__(self, in_channels, out_channels, kernel_size, stride=1, padding=0, dilation=1,
     groups=1, padding_mode='zeros', weight_attr=None, bias_attr=None, data_format='NCHW'):
        super(MaskedConv2d, self).__init__(in_channels, out_channels, 
            kernel_size, stride, padding, dilation, groups, padding_mode, weight_attr, bias_attr, data_format)
        self.mask_flag = False
    
    def set_mask(self, mask):
        self.mask = mask
        self.weight = self.weight * self.mask
        self.mask_flag = True
    
    def get_mask(self):
        print(self.mask_flag)
        return self.mask
    
    def forward(self, x):
        if self.mask_flag == True:
            weight = self.weight * self.mask
            return F.conv2d(x, weight, self.bias, self._stride,
                        self._updated_padding, self._dilation, self._groups)
        else:
            return F.conv2d(x, self.weight, self.bias, self._stride,
                        self._updated_padding, self._dilation, self._groups)`

**Comment by d2623587501** [comment]
完整重构代码
`class MaskedConv2d(nn.Conv2D):
    def __init__(self, in_channels, out_channels, kernel_size, stride=1, padding=0, dilation=1,
     groups=1, padding_mode='zeros', weight_attr=None, bias_attr=None, data_format='NCHW'):
        super(MaskedConv2d, self).__init__(in_channels, out_channels, 
            kernel_size, stride, padding, dilation, groups, padding_mode, weight_attr, bias_attr, data_format)
        self.mask_flag = False
    
    def set_mask(self, mask):
        self.mask = mask
        self.weight = self.weight * self.mask
        self.mask_flag = True
    
    def get_mask(self):
        print(self.mask_flag)
        return self.mask
    
    def forward(self, x):
        if self.mask_flag == True:
            weight = self.weight * self.mask
            return F.conv2d(x, weight, self.bias, self._stride,
                        self._updated_padding, self._dilation, self._groups)
        else:
            return F.conv2d(x, self.weight, self.bias, self._stride,
                        self._updated_padding, self._dilation, self._groups)`

**Comment by esythan** [comment]
赋值weight时需要parameter类型，需要确认=右边的变量类型

**Comment by d2623587501** [comment]
感谢大佬的回复，请问咱这边有啥方法转为parameter类型吗，我查官网的API没找到这方面的文档

**Comment by esythan** [comment]
是否可以更换一下思路，比如说对conv2d的输入或者输出tensor做mask，不知道是否能够满足你的需求

**Comment by d2623587501** [comment]
回大佬，我打算实现剪枝的功能，好像只能对卷积的weight操作

**Comment by esythan** [comment]
一般使用create_parameter()创建参数，可以参考一下

**Comment by d2623587501** [comment]
回大佬，create_parameter()这个创建参数是否可以自定义初始化，我打算把mask的数值传入这个新添的参数，我查了api只有初始化shape的

**Comment by d2623587501** [comment]
回大佬，我找到解决办法了
将self.weight = self.weight * self.mask
替换成self.weight.set_value(self.weight * self.mask)
就可以修改weight了，感谢大佬这几天的解答
