### ISSUE TITLE
Tensor.shape 可否作为inference模型中的一个节点

### ISSUE THREAD

**Issue by chiaitian** [PaddlePaddle/Paddle#38802]
我的模型中有节点的输入参数是模型输入tensor.shape，当模型转换到inference时，该节点的输入参数变为了常数，为模型转换时指定的输入size（[1,3, 32, -1])。我想要的效果是模型输入tensor的shape作为一个可变输入参数给到这个节点。这个问题该怎么解决？

**System information**
-PaddlePaddle version 2.2.0

**Comment by esythan** [comment]
麻烦更具体的描述一下问题，给出具体代码或者例子，目前暂时没有看懂你的需求
