### ISSUE TITLE
请问paddle是否有einops 相关的库

### ISSUE THREAD

**Issue by huilin16** [PaddlePaddle/Paddle#38808]
复现时代码遇到einops相关操作，请问paddle是否有相关库

**Comment by zhaocaibei123** [comment]
请问是想问paddle支持这种用法吗，paddle目前应该是不支持
![image](https://user-images.githubusercontent.com/48509226/148643297-2ce2fa76-676d-4567-8eaf-1066845cc62c.png)

**Comment by huilin16** [comment]
是的，请问有吗




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/Paddle"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年1月8日(星期六) 晚上7:58
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PaddlePaddle/Paddle] 请问paddle是否有einops 相关的库 (Issue #38808)





 
请问是想问paddle支持这种用法吗
 
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by JunnYu** [comment]
感觉你可以暂时用一下，我这里面改的`einops`  https://github.com/JunnYu/x-transformers-paddle/tree/main/einops 。

**Comment by huilin16** [comment]
多谢大佬，有时间实验下




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/Paddle"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年1月11日(星期二) 中午12:44
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PaddlePaddle/Paddle] 请问paddle是否有einops 相关的库 (Issue #38808)





 
感觉你可以暂时用一下，我这里面改的einops  https://github.com/JunnYu/x-transformers-paddle/tree/main/einops 。
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
