### ISSUE TITLE
无法对PPTOLOTiny敏感度分析的model.sensi.data进行可视化

### ISSUE THREAD

**Issue by AdobeDW** [PaddlePaddle/Paddle#38809]
问题：没有找到能够可视化敏感度分析结果的方法
出现的报错信息及相关log：
2022-01-07 16:15:11 [INFO] Model[PPYOLOTiny] loaded.
Traceback (most recent call last):
File "slim_visualize.py", line 3, in
pdx.slim.visualize(model, 'PaddleX/output/fined-ppyolotiny/prune/model.sensi.data', save_dir='./')
AttributeError: module 'paddlex' has no attribute 'slim'
使用的操作系统Linux、使用的Python版本3.6、使用的CUDA/cuDNN的版本号是10.2
我没有找到在PaddleX2.0、develop或是2.1版本、paddlepaddle2.0、2.1、2.2版本中能够实现对PPYOLOTiny敏感度分析得到的model.sensi.data进行可视化的代码，它总是提示我module 'paddlex' has no attribute 'slim'，另外，由于ppyolotiny模型在PaddleX2.0之前的版本中并不被包含，所以我也无法使用之前版本的程序。
![148569308-4ccb778a-fac8-4f47-a9ef-b4b211e03e1b](https://user-images.githubusercontent.com/30259085/148632344-bb9642b9-a659-4978-98db-e79762ef8bab.png)

**Comment by FlyingQianMM** [comment]
该问题与PaddleX Issue https://github.com/PaddlePaddle/PaddleX/issues/1344 相同，后续答疑直接至PaddleX进行，故先关闭该issue。
