### ISSUE TITLE
【论文复现】add_module()用法问题

### ISSUE THREAD

**Issue by Lieberk** [PaddlePaddle/Paddle#38801]
pytorch代码：
conv = conv_type(
    in_channels,
    out_channels,
    kernel_size=kernel_size,
    stride=strides,
    padding=padding,
    dilation=dilation,
    groups=groups,
    bias_attr=bias,
)
self.add_module("conv", conv)

paddle好像没有pytorch这样add_module()的用法，那paddle该如何实现上述类似这样添加conv到网络中的方式？

**Comment by esythan** [comment]
add_sublayer是否能满足需求？

**Comment by Lieberk** [comment]
> add_sublayer是否能满足需求？

已解决，谢谢老师。
