### ISSUE TITLE
paddle V2 在提交任务的时候怎么关闭掉大部分的info log日志

### ISSUE THREAD

**Issue by youan1** [PaddlePaddle/Paddle#3884]
RT,
日志太多了，想关闭掉info log，请问如何在提交任务的时候设置关闭info级别日志，只保留error日志的方法

**Comment by lcy-seso** [comment]
试试
```python
logger = logging.getLogger("paddle")
logger.setLevel(logging.ERROR)
```
提高 logging 等级能不能过滤一部分输出。

**Comment by youan1** [comment]
这个直接加在脚本里，编译过不去，错误为：
  File "dnn_experiment_fmhigh_updated4.py", line 32, in <module>
    logger = logging.getLogger("paddle")
NameError: name 'logging' is not defined

但是我已经
from paddle.trainer.config_parser import logger

请问logging是在哪里定义的

**Comment by typhoonzero** [comment]
```python
import logging
```
