### ISSUE TITLE
关于c++扩展算子的一些问题

### ISSUE THREAD

**Issue by WhiteFireFox** [PaddlePaddle/Paddle#38845]
例如我在使用torch写扩展算子的时候（以ncrelu为例），可以这样写：
torch::Tensor ncrelu_forward(torch::Tensor input) {
    auto pos = input.clamp_min(0);
    auto neg = input.clamp_max(0);
    return torch::cat({pos, neg}, 1);
}
也就是说我有用到torch::cat，这种math_op的复用使得代码简洁且开发高效

在paddle中是否有类似的用法呢，我之前看文档用std::会比较多（比如std::clamp之类的），想问下是否有paddle::之类可以复用paddle里面的op使得开发效率更高呢

**Comment by kuizhiqing** [comment]
感谢你的问题，由于底层设计的不同，目前 paddle op 复用和 torch 确实不太一致。我们在后续可能的升级中将会考虑你的建议。

**Comment by GT-ZhangAcer** [comment]
是目前就没有吗？那有其他的临时解决方案吗？

**Comment by kuizhiqing** [comment]
> 是目前就没有吗？那有其他的临时解决方案吗？

你指的没有是具体什么操作无法实现吗？目前差异的是开发的方式确实不太一样，具体的算子如果暂时未实现的也可以提出需求纳入我们的开发计划中。

**Comment by WhiteFireFox** [comment]
> 感谢你的问题，由于底层设计的不同，目前 paddle op 复用和 torch 确实不太一致。我们在后续可能的升级中将会考虑你的建议。

那想问下，例如在paddle中复用concat这个api，在c++里面应该怎么写呢

**Comment by kuizhiqing** [comment]
> 

可以使用 functor，参考 https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/fluid/operators/unique_op.h#L293-L302
