### ISSUE TITLE
JetsonNano使用paddleinferce预测时无法开启TensorRT进行加速，开启Cuadn后推理结果错误

### ISSUE THREAD

**Issue by MiShiDeHaiLuo** [PaddlePaddle/Paddle#38841]
- 版本、环境信息：
    1）PaddlePaddle版本：2.1
    2）GPU：PaddleNano
    3）GPU：预测若用GPU，请提供GPU型号、CUDA和CUDNN版本号
    4）系统环境：Jetpack4.6  系统18.04
-预测信息
    1）C++预测库（paddleinferce）：https://paddle-inference-lib.bj.bcebos.com/2.2.1/cxx_c/Jetson/jetpack4.6_gcc7.5/nano/paddle_inference_install_dir.tgz
    4）预测库来源：官网下载
- 复现信息：随时可以复现
- 问题描述：在C++环境下，使用CPU和GPU能够正常预测，且预测结果正确。
                    1，开启CUDNN加速之后。预测结果不准确。
                    2,   同时也无法开启TensorRT进行预测加速。报错如下
I0110 18:47:54.538808  8702 tensorrt_subgraph_pass.cc:138] ---  detect a sub-graph with 117 nodes
I0110 18:47:54.691968  8702 tensorrt_subgraph_pass.cc:395] Prepare TRT engine (Optimize model structure, Select OP kernel etc). This process may cost a lot of time.
terminate called after throwing an instance of 'paddle::platform::EnforceNotMet'
  what():  
![1](https://user-images.githubusercontent.com/97105652/148754498-63acb538-23ea-4b63-9df2-868b75509565.jpg)
![2](https://user-images.githubusercontent.com/97105652/148754517-82836350-46ab-4f8d-b694-621f231f3859.png)
![3](https://user-images.githubusercontent.com/97105652/148754535-df8128e6-cf77-44ef-a21d-6f931d65546f.png)

图一是预测结果，图二是开启CPU和GPU的代码。图三是开启TensorRT加速的报错。

**Comment by MiShiDeHaiLuo** [comment]
问题第一次没编辑好，已修改。

**Comment by Wangzheee** [comment]
这个报错信息有些缺失，可以在执行命令前加上 GLOG_v=5 ，会打出更多log，请将完整log附上，方便定位，谢谢~

**Comment by MiShiDeHaiLuo** [comment]
I0110 20:55:32.825292 11106 fuse_pass_base.cc:57] ---  detected 1 subgraphs
--- Running IR pass [conv_elementwise_add_fuse_pass]
--- Running IR pass [tensorrt_subgraph_pass]
I0110 20:55:32.902678 11106 tensorrt_subgraph_pass.cc:138] ---  detect a sub-graph with 117 nodes
I0110 20:55:33.191356 11106 tensorrt_subgraph_pass.cc:395] Prepare TRT engine (Optimize model structure, Select OP kernel etc). This process may cost a lot of time.
terminate called after throwing an instance of 'paddle::platform::EnforceNotMet'
  what():  

--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
0   paddle_infer::CreatePredictor(paddle::AnalysisConfig const&)
1   paddle_infer::Predictor::Predictor(paddle::AnalysisConfig const&)
2   std::unique_ptr<paddle::PaddlePredictor, std::default_delete<paddle::PaddlePredictor> > paddle::CreatePaddlePredictor<paddle::AnalysisConfig, (paddle::PaddleEngineKind)2>(paddle::AnalysisConfig const&)
3   paddle::AnalysisPredictor::Init(std::shared_ptr<paddle::framework::Scope> const&, std::shared_ptr<paddle::framework::ProgramDesc> const&)
4   paddle::AnalysisPredictor::PrepareProgram(std::shared_ptr<paddle::framework::ProgramDesc> const&)
5   paddle::AnalysisPredictor::OptimizeInferenceProgram()
6   paddle::inference::analysis::Analyzer::RunAnalysis(paddle::inference::analysis::Argument*)
7   paddle::inference::analysis::IrAnalysisPass::RunImpl(paddle::inference::analysis::Argument*)
8   paddle::inference::analysis::IRPassManager::Apply(std::unique_ptr<paddle::framework::ir::Graph, std::default_delete<paddle::framework::ir::Graph> >)
9   paddle::framework::ir::Pass::Apply(paddle::framework::ir::Graph*) const
10  paddle::inference::analysis::TensorRtSubgraphPass::ApplyImpl(paddle::framework::ir::Graph*) const
11  paddle::inference::analysis::TensorRtSubgraphPass::CreateTensorRTOp(paddle::framework::ir::Node*, paddle::framework::ir::Graph*, std::vector<std::string, std::allocator<std::string > > const&, std::vector<std::string, std::allocator<std::string > >*) const
12  paddle::inference::tensorrt::OpConverter::ConvertBlockToTRTEngine(paddle::framework::BlockDesc*, paddle::framework::Scope const&, std::vector<std::string, std::allocator<std::string > > const&, std::unordered_set<std::string, std::hash<std::string >, std::equal_to<std::string >, std::allocator<std::string > > const&, std::vector<std::string, std::allocator<std::string > > const&, paddle::inference::tensorrt::TensorRTEngine*)
13  paddle::platform::EnforceNotMet::EnforceNotMet(paddle::platform::ErrorSummary const&, char const*, int)
14  paddle::platform::GetCurrentTraceBackString[abi:cxx11](bool)

----------------------
Error Message Summary:
----------------------
InvalidArgumentError: The input [image] shape of trt subgraph is [-1,3,-1,-1], please enable trt dynamic_shape mode by SetTRTDynamicShapeInfo. (at /home/paddle/data/wangye19/tag_release/remove_paddle/Paddle/paddle/fluid/inference/tensorrt/engine.h:100)

按 <RETURN> 来关闭窗口...

你好最新报错信息如下，看信息是图像维度的问题，但是C++的预测输入只有一个vector<float>,只有一个维度。
还有关于GPU预测开启和不开启CUDNN加速结果差距比较大是为何？

**Comment by MiShiDeHaiLuo** [comment]
I0110 20:55:32.825292 11106 fuse_pass_base.cc:57] ---  detected 1 subgraphs
--- Running IR pass [conv_elementwise_add_fuse_pass]
--- Running IR pass [tensorrt_subgraph_pass]
I0110 20:55:32.902678 11106 tensorrt_subgraph_pass.cc:138] ---  detect a sub-graph with 117 nodes
I0110 20:55:33.191356 11106 tensorrt_subgraph_pass.cc:395] Prepare TRT engine (Optimize model structure, Select OP kernel etc). This process may cost a lot of time.
terminate called after throwing an instance of 'paddle::platform::EnforceNotMet'
  what():  

--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
0   paddle_infer::CreatePredictor(paddle::AnalysisConfig const&)
1   paddle_infer::Predictor::Predictor(paddle::AnalysisConfig const&)
2   std::unique_ptr<paddle::PaddlePredictor, std::default_delete<paddle::PaddlePredictor> > paddle::CreatePaddlePredictor<paddle::AnalysisConfig, (paddle::PaddleEngineKind)2>(paddle::AnalysisConfig const&)
3   paddle::AnalysisPredictor::Init(std::shared_ptr<paddle::framework::Scope> const&, std::shared_ptr<paddle::framework::ProgramDesc> const&)
4   paddle::AnalysisPredictor::PrepareProgram(std::shared_ptr<paddle::framework::ProgramDesc> const&)
5   paddle::AnalysisPredictor::OptimizeInferenceProgram()
6   paddle::inference::analysis::Analyzer::RunAnalysis(paddle::inference::analysis::Argument*)
7   paddle::inference::analysis::IrAnalysisPass::RunImpl(paddle::inference::analysis::Argument*)
8   paddle::inference::analysis::IRPassManager::Apply(std::unique_ptr<paddle::framework::ir::Graph, std::default_delete<paddle::framework::ir::Graph> >)
9   paddle::framework::ir::Pass::Apply(paddle::framework::ir::Graph*) const
10  paddle::inference::analysis::TensorRtSubgraphPass::ApplyImpl(paddle::framework::ir::Graph*) const
11  paddle::inference::analysis::TensorRtSubgraphPass::CreateTensorRTOp(paddle::framework::ir::Node*, paddle::framework::ir::Graph*, std::vector<std::string, std::allocator<std::string > > const&, std::vector<std::string, std::allocator<std::string > >*) const
12  paddle::inference::tensorrt::OpConverter::ConvertBlockToTRTEngine(paddle::framework::BlockDesc*, paddle::framework::Scope const&, std::vector<std::string, std::allocator<std::string > > const&, std::unordered_set<std::string, std::hash<std::string >, std::equal_to<std::string >, std::allocator<std::string > > const&, std::vector<std::string, std::allocator<std::string > > const&, paddle::inference::tensorrt::TensorRTEngine*)
13  paddle::platform::EnforceNotMet::EnforceNotMet(paddle::platform::ErrorSummary const&, char const*, int)
14  paddle::platform::GetCurrentTraceBackString[abi:cxx11](bool)

----------------------
Error Message Summary:
----------------------
InvalidArgumentError: The input [image] shape of trt subgraph is [-1,3,-1,-1], please enable trt dynamic_shape mode by SetTRTDynamicShapeInfo. (at /home/paddle/data/wangye19/tag_release/remove_paddle/Paddle/paddle/fluid/inference/tensorrt/engine.h:100)

按 <RETURN> 来关闭窗口...

你好最新报错信息如下，看信息是图像维度的问题，但是C++的预测输入只有一个vector，只有一个维度。
还有关于GPU预测开启和不开启CUDNN加速结果差距比较大是为何？

**Comment by MiShiDeHaiLuo** [comment]
> 这个报错信息有些缺失，可以在执行命令前加上 GLOG_v=5 ，会打出更多log，请将完整log附上，方便定位，谢谢~

I0110 20:55:32.825292 11106 fuse_pass_base.cc:57] --- detected 1 subgraphs
--- Running IR pass [conv_elementwise_add_fuse_pass]
--- Running IR pass [tensorrt_subgraph_pass]
I0110 20:55:32.902678 11106 tensorrt_subgraph_pass.cc:138] --- detect a sub-graph with 117 nodes
I0110 20:55:33.191356 11106 tensorrt_subgraph_pass.cc:395] Prepare TRT engine (Optimize model structure, Select OP kernel etc). This process may cost a lot of time.
terminate called after throwing an instance of 'paddle::platform::EnforceNotMet'
what():

C++ Traceback (most recent call last):
0 paddle_infer::CreatePredictor(paddle::AnalysisConfig const&)
1 paddle_infer::Predictor::Predictor(paddle::AnalysisConfig const&)
2 std::unique_ptr<paddle::PaddlePredictor, std::default_deletepaddle::PaddlePredictor > paddle::CreatePaddlePredictor<paddle::AnalysisConfig, (paddle::PaddleEngineKind)2>(paddle::AnalysisConfig const&)
3 paddle::AnalysisPredictor::Init(std::shared_ptrpaddle::framework::Scope const&, std::shared_ptrpaddle::framework::ProgramDesc const&)
4 paddle::AnalysisPredictor::PrepareProgram(std::shared_ptrpaddle::framework::ProgramDesc const&)
5 paddle::AnalysisPredictor::OptimizeInferenceProgram()
6 paddle::inference::analysis::Analyzer::RunAnalysis(paddle::inference::analysis::Argument*)
7 paddle::inference::analysis::IrAnalysisPass::RunImpl(paddle::inference::analysis::Argument*)
8 paddle::inference::analysis::IRPassManager::Apply(std::unique_ptr<paddle::framework::ir::Graph, std::default_deletepaddle::framework::ir::Graph >)
9 paddle::framework::ir::Pass::Apply(paddle::framework::ir::Graph*) const
10 paddle::inference::analysis::TensorRtSubgraphPass::ApplyImpl(paddle::framework::ir::Graph*) const
11 paddle::inference::analysis::TensorRtSubgraphPass::CreateTensorRTOp(paddle::framework::ir::Node*, paddle::framework::ir::Graph*, std::vector<std::string, std::allocator<std::string > > const&, std::vector<std::string, std::allocator<std::string > >) const
12 paddle::inference::tensorrt::OpConverter::ConvertBlockToTRTEngine(paddle::framework::BlockDesc, paddle::framework::Scope const&, std::vector<std::string, std::allocator<std::string > > const&, std::unordered_set<std::string, std::hash<std::string >, std::equal_to<std::string >, std::allocator<std::string > > const&, std::vector<std::string, std::allocator<std::string > > const&, paddle::inference::tensorrt::TensorRTEngine*)
13 paddle::platform::EnforceNotMet::EnforceNotMet(paddle::platform::ErrorSummary const&, char const*, int)
14 paddle::platform::GetCurrentTraceBackStringabi:cxx11

Error Message Summary:
InvalidArgumentError: The input [image] shape of trt subgraph is [-1,3,-1,-1], please enable trt dynamic_shape mode by SetTRTDynamicShapeInfo. (at /home/paddle/data/wangye19/tag_release/remove_paddle/Paddle/paddle/fluid/inference/tensorrt/engine.h:100)

按 来关闭窗口...

你好最新报错信息如下，看信息是图像维度的问题，但是C++的预测输入只有一个vector，只有一个维度。
还有关于GPU预测开启和不开启CUDNN加速结果差距比较大是为何？

**Comment by Wangzheee** [comment]
这个错误信息是因为网络的输入是动态的，需要设置动态shape，可以参照paddle的demo设置一下https://github.com/PaddlePaddle/Paddle-Inference-Demo/blob/master/c%2B%2B/paddle-trt/trt_dynamic_shape_test.cc
需要设置输入的一个范围，再开启动态shape（config.SetTRTDynamicShapeInfo）

**Comment by MiShiDeHaiLuo** [comment]
好的，麻烦您了，还有咨询一下开启CUDNN和不开启的预测结果差异比较大是为什么？




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/Paddle"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年1月11日(星期二) 上午10:55
***@***.***&gt;;
***@***.***&gt;;"State ***@***.***&gt;;
主题:&nbsp;Re: [PaddlePaddle/Paddle] JetsonNano使用paddleinferce预测时无法开启TensorRT进行加速，开启Cuadn后推理结果错误 (Issue #38841)





 
这个错误信息是因为网络的输入是动态的，需要设置动态shape，可以参照paddle的demo设置一下https://github.com/PaddlePaddle/Paddle-Inference-Demo/blob/master/c%2B%2B/paddle-trt/trt_dynamic_shape_test.cc
 需要设置输入的一个范围，再开启动态shape（config.SetTRTDynamicShapeInfo）
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Wangzheee** [comment]
建议不使用EnableCUDNN()这个接口，目前它有些问题会导致一些未知错误。使用EnableUseGpu()就足够了，它会默认使用cudnn的加速库。另外还是建议开启trt来推理，性能是最优的

**Comment by MiShiDeHaiLuo** [comment]
收到，麻烦您了！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/Paddle"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年1月11日(星期二) 中午11:06
***@***.***&gt;;
***@***.***&gt;;"State ***@***.***&gt;;
主题:&nbsp;Re: [PaddlePaddle/Paddle] JetsonNano使用paddleinferce预测时无法开启TensorRT进行加速，开启Cuadn后推理结果错误 (Issue #38841)





 
建议不使用EnableCUDNN()这个接口，目前它有些问题会导致一些未知错误。使用EnableUseGpu()就足够了，它会默认使用cudnn的加速库。另外还是建议开启trt来推理，性能是最优的
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Wangzheee** [comment]
感谢提出的问题~ 
另外nano这个硬件自身资源比较少，在gpu的底层计算上会比服务端要多很多bug，这个我们和NV一直在解决，欢迎继续提出问题
