### ISSUE TITLE
paddlepaddle有没有ernie +crf的demo例子， 不要paddleNlp和paddlehub的

### ISSUE THREAD

**Issue by dickobe** [PaddlePaddle/Paddle#38852]
不要paddleNlp和paddlehub的

**Comment by kuizhiqing** [comment]
你好，经过确认，paddleapddle 暂时没有这样的开源 demo，感谢你的关注。

**Comment by ZeyuChen** [comment]
@dickobe 能了解下是为了更好的学习组网结构吗？还是有其他目的不用paddlenlp和paddlehub的？
