### ISSUE TITLE
[Feature] Add passes that add mkldnn related attributes instead of changing native ops

### ISSUE THREAD

**Issue by lidanqing-vv** [PaddlePaddle/Paddle#38856]
Use passes to add mkldnn related attributes instead of changing native ops
@tsocha

**Comment by jakpiase** [comment]
Is there any example on how can we add attributes in inference stage?

**Comment by lidanqing-vv** [comment]
@tsocha is working on the design you can discuss with him. We need to get more info from Baidu about compatibility requirements.

**Comment by lidanqing-vv** [comment]
Meeting notes
1. Not removing any attributes that already exist in native op
2. Serilizartion: If you follow register_op steps, it will be serilizaed
3. About naming conv_oneDNN_op.cc

Question1: GPU training. CPU mkldnn training is working now. If adding this new mkldnn custom op, will it work on GPU training.This custom op is through passes, and training doesn't have such passes, so it should not affect. Is it callable from python. If it is callable it will influence training. Tomasz answer is no such plan for this.

Question2: How does this mkldnn custom op support eager mode which is most popular.

**Comment by lidanqing-vv** [comment]
related to #36541
