### ISSUE TITLE
CUDA 11.4，什么时候才支持？

### ISSUE THREAD

**Issue by alao556** [PaddlePaddle/Paddle#38857]
CUDA 11.2 的 Paddle 在 CUDA11.4 环境下运行会报错。

**Comment by sdcb** [comment]
最好不用支持了，因为现在已经11.5了

**Comment by alao556** [comment]
那也不见得有 CUDA 11.5 的包放出来

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by kuizhiqing** [comment]
你好，飞桨集成cuda新版本需要根据NV 发布新版本的roadmap以及外部用户使用量等情况综合考虑，并综合各版本新特性来决定支持的cuda新版本。

具体发布时间还没有确定，你可以持续关注飞桨的新版本发布，感谢对飞桨的支持！

**Comment by Muttermal** [comment]
> 你好，飞桨集成cuda新版本需要根据NV 发布新版本的roadmap以及外部用户使用量等情况综合考虑，并综合各版本新特性来决定支持的cuda新版本。
> 
> 具体发布时间还没有确定，你可以持续关注飞桨的新版本发布，感谢对飞桨的支持！


你好，请问什么时候出支持cuda11.4的版本啊

**Comment by zhaoyangbu** [comment]
同上

**Comment by Xreki** [comment]
> CUDA 11.2 的 Paddle 在 CUDA11.4 环境下运行会报错。

请问报什么错啊？

**Comment by Muttermal** [comment]
> > CUDA 11.2 的 Paddle 在 CUDA11.4 环境下运行会报错。
> 
> 请问报什么错啊？


![屏幕截图 2022-07-07 113320](https://user-images.githubusercontent.com/50070283/177685341-a05ca309-3cda-4613-b018-7d78bbcc80cc.png)

**Comment by Xreki** [comment]
<img width="1431" alt="image" src="https://user-images.githubusercontent.com/12538138/177706205-046a21e9-cefa-4721-88d1-9929b8b33910.png">

如报错信息显示，运行出错是在默认目录下找不到libcudnn.so。请补充和确认一下以下信息：

1. 使用的docker镜像是哪个？
2. 请确认下是否存在`/usr/local/cuda/lib64`目录、以及该目录下是否存在libcudnn.so库。若没有，请确认下机器上是否存在libcudnn.so库，可将其路径加入`LD_LIBRARY_PATH`中。
