### ISSUE TITLE
ernie训练出错

### ISSUE THREAD

**Issue by dickobe** [PaddlePaddle/Paddle#38879]
为使您的问题得到快速解决，在建立Issue前，请您先通过如下方式搜索是否有相似问题:【搜索issue关键字】【使用labels筛选】【官方文档】

建立issue时，为快速解决问题，请您根据使用情况给出如下信息：
- 标题：简洁、精准描述您的问题，例如“ssd 模型前置lstm报错  ”
- 版本、环境信息：
    1）PaddlePaddle版本：1.8.1
    2）CPU：请提供CPU型号，MKL/OpenBlas/MKLDNN/等数学库的使用情况
    3）GPU：请提供GPU型号，CUDA和CUDNN版本号
    4）系统环境：请说明系统类型、版本（例如Mac OS 10.14），Python版本
 注：您可以通过执行[summary_env.py](https://github.com/PaddlePaddle/Paddle/blob/develop/tools/summary_env.py)获取以上信息。
- 模型信息
    1）模型名称 2）使用数据集名称 3）使用算法名称 4）模型链接
- 复现信息：如为报错，请给出复现环境、复现步骤
- 问题描述：请详细描述您的问题，同步贴出报错信息、日志/代码关键片段

构建ernie+crf序列标注模型，训练时出错，麻烦帮看下问题，执行到 F.layers.crf_decoding报错

**报错提示： ValueError: var crfw not in this block**

@add_docstring(ErnieModel.forward.__doc__)
    def forward(self, *args, **kwargs):
        """
        Args:
            labels (optional, `Variable` of shape [batch_size, seq_len]):
                ground truth label id for each token
        Returns:
            loss (`Variable` of shape []):
                Cross entropy loss mean over batch and time, ignore positions where label == -100
                if labels not set, returns None
            logits (`Variable` of shape [batch_size, seq_len, hidden_size]):
                output logits of classifier
            loss_weights (`Variable` of shape [batch_size, seq_len]):
                weigths of loss for each tokens.
            ignore_index (int):
                when label == `ignore_index`, this token will not contribute to loss
        """
        ignore_index = kwargs.pop('ignore_index', -100)
        labels = kwargs.pop('labels', None)
        loss_weights = kwargs.pop('loss_weights', None)
        pooled, encoded = super(ErnieCrfForTokenClassification, self).forward(*args, **kwargs)
        # hidden = self.dropout(encoded) # maybe not?
        # logits = self.classifier(hidden)
        self.emission = F.layers.fc(
            input=encoded,
            size=len(cfg_define.label_map),
            param_attr=F.ParamAttr(
                initializer=F.initializer.Uniform(
                    low=-0.1, high=0.1),
                regularizer=F.regularizer.L2DecayRegularizer(
                    regularization_coeff=1e-4)),
            num_flatten_dims=2)
        print("emission shape", self.emission.shape)
        size = self.emission.shape[1]
        F.layers.create_parameter(
            shape=[size + 2, size], dtype=self.emission.dtype, name='crfw')

        self.crf_decode = F.layers.crf_decoding(
            input=self.emission,
            param_attr=F.ParamAttr(name='crfw'), length=64)
        ret_infers = F.layers.assign(self.crf_decode)

        if labels is not None:
            if len(labels.shape) == 2:
                labels = L.unsqueeze(labels, axes=[-1])
            loss = F.layers.linear_chain_crf(
                input=emission,
                label=labels,
                param_attr=F.ParamAttr(
                    name='crfw', learning_rate=0.2),
                length=cfg_define.max_seqlen)
            loss = F.layers.mean(x=loss)
            # loss = L.softmax_with_cross_entropy(logits, labels, ignore_index=ignore_index)
            if loss_weights is not None:
                loss = L.squeeze(loss, [-1]) * loss_weights
            loss = F.layers.mean(x=loss)
            # loss = L.reduce_mean(loss)
        else:
            loss = None
            return ret_infers
        return loss, ret_infers

**Comment by Baibaifan** [comment]
从报错信息看是var crfw 并没有在当前block中声明，方便贴一下相关的全量报错信息。

**Comment by dickobe** [comment]
> 从报错信息看是var crfw 并没有在当前block中声明，方便贴一下相关的全量报错信息。
@Baibaifan  麻烦帮看下，训练的时候报错
loss, logits = model(ids, sids, labels=aligned_label, loss_weights=L.cast(ids > self.tokenizer.mask_id,
                                                                                              'float32'))  # [MASK] is the largest special token
                   
![image](https://user-images.githubusercontent.com/9254170/149075630-12a8150d-36fd-40ec-9e5d-9f3d45f048f7.png)

**Comment by Baibaifan** [comment]
从已上报错截图看，还是crfw没有在main_program中创建，引发的问题，可以确定下组网是否正确。

**Comment by dickobe** [comment]
> main_program



> 从已上报错截图看，还是crfw没有在main_program中创建，引发的问题，可以确定下组网是否正确。

怎么确认是在同一个main_program里呢？ @Baibaifan

**Comment by Baibaifan** [comment]
是这样，从你的报错看你应该是调用了crf_decoding这个api，这个api会调用helper.get_parameter(param_attr.name)方法，动态图有一个全局的program，这时候发现这里有一个parameter并不在这个program里边。

**Comment by dickobe** [comment]
> 是这样，从你的报错看你应该是调用了crf_decoding这个api，这个api会调用helper.get_parameter(param_attr.name)方法，动态图有一个全局的program，这时候发现这里有一个parameter并不在这个program里边。

那如何解决这个呢？ @Baibaifan

**Comment by Baibaifan** [comment]
你需要检查下报错的crfw 有没有这个parameter，换句话说你用了一个没有声明或者初始化的parameter。
