### ISSUE TITLE
模型保存及其不便

### ISSUE THREAD

**Issue by livehl** [PaddlePaddle/Paddle#38894]
PaddlePaddle版本  2.2

曾经用过keras。
如今想换成paddle，快速文档看完之后，一切都很赞，除了模型保存/加载。

在keras中，模型可以整体保存，连带模型、参数、优化器等等一起打包。
只需要把文件传输走，再另外一个地方加载后直接就可以用(训练)。

paddle 没法保存模型，保存加载必须要保证模型代码先写好。

期望：希望能有和keras类似的模型保存加载方式。而不是模型参数保存，恢复的时候还要写一大堆的配置、拷贝原来的模型代码。

**Comment by sljlp** [comment]
你好，非常感谢你的宝贵意见。我们会尽力让paddle框架更加完美。期待您继续支持国产框架，支持飞桨。

**Comment by chenwhql** [comment]
之前用keras的话，不知道您有没有了解下paddle的high level api，麻烦您看下这里Model的save load能否满足您的需求呢？https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/Model_cn.html#save-path-training-true

**Comment by chenwhql** [comment]
另外，还有一个区别是，目前paddle主推的是动态图模式，这一点和keras有区别：动态图和静态图不同，是即时执行的，没有模型描述，所以没有提供模型的存储，推荐仅存储参数。

使用静态图的话，是可以存储模型的，但是静态图训练不方便调试，所以目前我们并不主要推荐。
