### ISSUE TITLE
编译paddle出错

### ISSUE THREAD

**Issue by dcckAyou** [PaddlePaddle/Paddle#38892]
Paddle版本2.0，CPU为I7-11800H， 显卡RTX3060 Laptop,系统为windows10，Python3.9， cuda版本为10.2，cudnn版本7.6，cmake版本3.20.6，使用vs2019编译debug版，在尝试编译profiler工程时报错：
 10>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\BuildCustomizations\CUDA 10.2.targets(764,9): error MSB3721: 命令“"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.2\bin\nvcc.exe" -gencode=arch=compute_35,code=\"sm_35,compute_35\" -gencode=arch=compute_50,code=\"sm_50,compute_50\" -gencode=arch=compute_52,code=\"sm_52,compute_52\" -gencode=arch=compute_60,code=\"sm_60,compute_60\" -gencode=arch=compute_61,code=\"sm_61,compute_61\" -gencode=arch=compute_70,code=\"sm_70,compute_70\" -gencode=arch=compute_75,code=\"sm_75,compute_75\" --use-local-env --cl-version 2019 -ccbin "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\bin\HostX64\x64" -x cu  -ID:\libs\paddlePaddle\build -ID:\libs\paddlePaddle\paddle\fluid\framework\io -ID:\libs\paddlePaddle\build\third_party\install\zlib\include -ID:\libs\paddlePaddle\build\third_party\install -ID:\libs\paddlePaddle\build\third_party\install\gflags\include -ID:\libs\paddlePaddle\build\third_party\install\glog\include -ID:\libs\paddlePaddle\build\third_party\boost\src\extern_boost -ID:\libs\paddlePaddle\build\third_party\eigen3\src\extern_eigen3 -ID:\libs\paddlePaddle\build\third_party\threadpool\src\extern_threadpool -ID:\libs\paddlePaddle\build\third_party\dlpack\src\extern_dlpack\include -ID:\libs\paddlePaddle\build\third_party\install\xxhash\include -ID:\libs\paddlePaddle\build\third_party\install\warpctc\include -ID:\libs\paddlePaddle\build\third_party\install\mklml\include -ID:\libs\paddlePaddle\build\third_party\install\mkldnn\include -ID:\libs\paddlePaddle\build\third_party\install\protobuf\include -ID:\libs\paddlePaddle\build\third_party\cub\src\extern_cub -ID:\libs\paddlePaddle\build\third_party\install\cryptopp\include -I"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.2\include" -ID:\libs\paddlePaddle -I"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.2\include"     --keep-dir x64\Debug -maxrregcount=0  --machine 64 --compile -cudart static -w --expt-relaxed-constexpr --expt-extended-lambda -std=c++14 -Xcompiler="/EHsc /wd4244 /wd4267 /wd4819 /bigobj /arch:AVX" -g   -D_WINDOWS -D_MWAITXINTRIN_H_INCLUDED -D__STRICT_ANSI__ -DNDEBUG -DTRT_PLUGIN_FP16_AVALIABLE -D"CUDA_VERSION_MAJOR=\"10\"" -D"CUDA_VERSION_MINOR=\"2\"" -D"CUDA_TOOLKIT_ROOT_DIR=\"C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.2\"" -D"CUDNN_MAJOR_VERSION=\"7\"" -DGOOGLE_GLOG_DLL_DECL= -DBOOST_HAS_STATIC_ASSERT -DPADDLE_WITH_MKLML -DLAPACK_FOUND -DPADDLE_WITH_MKLDNN -DPADDLE_WITH_CRYPTO -DPADDLE_VERSION=0.0.0 -DPADDLE_VERSION_INTEGER=0 -DPADDLE_NO_PYTHON -DPADDLE_DISABLE_PROFILER -DPADDLE_WITH_AVX -DPADDLE_WITH_SSE3 -D_XKEYCHECK_H -DPADDLE_DLL_INFERENCE -DPADDLE_WITH_CUDA -DEIGEN_USE_GPU -DPADDLE_DLL_EXPORT -D"CMAKE_INTDIR=\"Debug\"" -DWIN32 -D_WINDOWS -DTRT_PLUGIN_FP16_AVALIABLE -D"CUDA_VERSION_MAJOR=\"10\"" -D"CUDA_VERSION_MINOR=\"2\"" -D"CUDA_TOOLKIT_ROOT_DIR=\"C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.2\"" -D"CUDNN_MAJOR_VERSION=\"7\"" -DGOOGLE_GLOG_DLL_DECL= -DBOOST_HAS_STATIC_ASSERT -DPADDLE_WITH_MKLML -DLAPACK_FOUND -DPADDLE_WITH_MKLDNN -DPADDLE_WITH_CRYPTO -DPADDLE_VERSION=0.0.0 -DPADDLE_VERSION_INTEGER=0 -DPADDLE_NO_PYTHON -DPADDLE_DISABLE_PROFILER -DPADDLE_WITH_AVX -DPADDLE_WITH_SSE3 -D_XKEYCHECK_H -DPADDLE_DLL_INFERENCE -DPADDLE_WITH_CUDA -DEIGEN_USE_GPU -DPADDLE_DLL_EXPORT -D"CMAKE_INTDIR=\"Debug\"" -D_MBCS -Xcompiler "/EHsc /W0 /nologo /Od /FS /RTC1 /MT /GR" -o profiler.dir\Debug\/profiler.cu.obj "D:\libs\paddlePaddle\paddle\fluid\platform\profiler.cu"”已退出，返回代码为 1。

之后尝试编译其它工程，例如cudnn_lstm_op,会报同样的错误。

**Comment by zhwesky2010** [comment]
@dcckAyou 您好，请问是否有其他的报错内容，这里的信息 只有执行编译命令时退出，另外目前debug编译没有维护，可能存在问题，可以改成release x64配置试下

**Comment by dcckAyou** [comment]
> @dcckAyou 您好，请问是否有其他的报错内容，这里的信息 只有执行编译命令时退出，另外目前debug编译没有维护，可能存在问题，可以改成release x64配置试下

抱歉，我忘记记录其它信息了。我记得是nvcc.exe不认"2019"这个符号。 nvcc fatal   : Value '2019' is not defined for option 'cl-version'

**Comment by zhwesky2010** [comment]
@dcckAyou 可以拉下最新的paddle包，最近改了些VS2019的编译bug，在我们本机上测试编译是没问题的
