### ISSUE TITLE
建议paddle添加对bool张量的索引切片、赋值等操作

### ISSUE THREAD

**Issue by Spratumn** [PaddlePaddle/Paddle#38913]
欢迎您对PaddlePaddle提出建议，非常感谢您对PaddlePaddle的贡献！
在留下您的建议时，辛苦您同步提供如下信息：
- 版本、环境信息
1）PaddlePaddle版本：2.2
2）CPU/GPU：Driver API Version: 11.4, Runtime API Version: 10.2, cuDNN Version: 7.6.
3）系统环境：ubuntu20.04

- 复现信息：
   yolox-yolo_head.py 中dynamic_k_matching()处报错
 `fg_mask[fg_mask.clone()] = fg_mask_inboxes`

   报错提示：TypeError: Only support float and double tensor for bool index, but received paddle.bool.

- 建议描述：添加对bool张量的索引切片、赋值等操作

**Comment by FeixLiu** [comment]
您好，您的反馈对产品非常有价值，我们内部会安排评估，未来有计划尽快回复。

**Comment by zyfncg** [comment]
感谢您的反馈~这里的问题我们在最新的develop代码分支里已经支持[PR37761](https://github.com/PaddlePaddle/Paddle/pull/37761)，预计在后续的正式版本中发布。
如果赶时间的话可以直接拉取最新的develop分支代码编译进行使用，编译流程可以参考这里https://www.paddlepaddle.org.cn/documentation/docs/zh/install/compile/linux-compile.html
