### ISSUE TITLE
Drop of inference performance of model demark

### ISSUE THREAD

**Issue by pmajchrzak** [PaddlePaddle/Paddle#38923]
After commit: https://github.com/PaddlePaddle/Paddle/commit/ac6969412c07a32e7ab5e6a48f66844f4e7b9d43 big drop of inference performance of model demark was observed

---
### CLX 
```
            Turbo: OFF
             Name: Intel(R) Xeon(R) Gold 6248 CPU @ 2.50GHz
            Model: 85
           Family: 6
          Sockets: 2
 Cores per socket: 20
 Threads per core: 2
```
![image](https://user-images.githubusercontent.com/10847947/149290751-820c30cc-940b-43a9-9f13-db0e56ab7685.png)
---
### SKX 
```
           Turbo: OFF
            Name: Intel(R) Xeon(R) Platinum 8180 CPU @ 2.50GHz
           Model: 85
          Family: 6
         Sockets: 2
Cores per socket: 28
Threads per core: 2
```
![image](https://user-images.githubusercontent.com/10847947/149290870-dfff956e-890f-41c7-aea1-958a0a9c1927.png)
---
### CPX 
```
 Turbo: OFF
            Name: Intel(R) d on(R) Gold 6348H CPU @ 2.30GHz
           Model: 85
          Family: 6
         Sockets: 4
Cores per socket: 24
Threads per core: 2
```
![image](https://user-images.githubusercontent.com/10847947/149291034-6575ab63-e95e-4fc0-9495-18f309a6f1b2.png)

---
### Run command:
``
/repos/paddle_paddle/build/paddle/fluid/inference/tests/api/test_analyzer_image_classification --gtest_filter=*profile_mkldnn --repeat=1000  --batch_size=1    --infer_model=/data/PaddlePaddle/models/demark
``
### CMAKE Flags:
``
-DCMAKE_BUILD_TYPE=Release -DWITH_GPU=OFF -DWITH_MKLDNN=ON -DWITH_TESTING=ON -DWITH_PROFILER=OFF -DWITH_STYLE_CHECK=OFF -DON_INFER=ON -DWITH_INFERENCE_API_TEST=ON -DINFERENCE_DEMO_INSTALL_DIR=/data/PaddlePaddle/pp_models -DPY_VERSION=3.6
``
### Environment
```
            OS: Ubuntu18.04 with mkldnn 
 cmake version: 3.10.2
      Compiler: GCC 8
```

For the attention of: @jczaja

**Comment by baoachun** [comment]
Got it, I'm working on it.

**Comment by baoachun** [comment]
Hi @pmajchrzak, according to the reproduction steps you gave, I didn't find the demark folder in the model directory. Could you please give me some advice?
![图片](https://user-images.githubusercontent.com/22114318/150296937-6ea983cd-48ac-40c6-bd39-d2ad6f352401.png)

**Comment by pmajchrzak** [comment]
We are using our internal trained model. @jczaja is the owner.

**Comment by jczaja** [comment]
@baoachun This demark model was also referenced as Face model (https://github.com/PaddlePaddle/Paddle/issues/17535) and we got it from our colleagues from Baidu. So you should have it . If you for some reason do not have it then please advice how can we send it to you.

**Comment by lidanqing-vv** [comment]
It is fixed
