### ISSUE TITLE
安装Paddle2.2.1-gpu自测时一直无法通过？

### ISSUE THREAD

**Issue by HongShiKuan** [PaddlePaddle/Paddle#38934]
系统版本：Ubuntu **18.04.5 LTS**
显卡版本：**NVIDIA-SMI 470.57.02    Driver Version: 470.57.02    CUDA Version: 11.4** 
显卡：**RTX3090**
安装Paddle-gpu通过anaconda安装：
![image](https://user-images.githubusercontent.com/45912889/149334146-2d279339-78f2-4ed2-9a5e-6f003b88a095.png)
但是在运行paddle.utils.run_check()自测时，一直卡住，如下图所示，而且显存一直在涨，请问这是什么问题呀？
![image](https://user-images.githubusercontent.com/45912889/149334363-e295309a-f2f2-417d-a3ba-b3e4cb50590d.png)

**Comment by FeixLiu** [comment]
这个运行大概需要一分钟左右～您可以稍微再等一会～

**Comment by HongShiKuan** [comment]
> 这个运行大概需要一分钟左右～您可以稍微再等一会～

目前测试等了10min左右，还是在卡住。是我的显卡驱动版本 或者 paddle版本不适配3090显卡吗？
还有就是这个机器有多卡，还没有安装nccl，是更这个有关系吗？

**Comment by HongShiKuan** [comment]
更新一下，换到**conda install paddlepaddle-gpu==2.2.1 cudatoolkit=11.2 -c https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/Paddle/ -c conda-forge**此指令，可以通过自测！！！

**Comment by HongShiKuan** [comment]
> 更新一下，换到**conda install paddlepaddle-gpu==2.2.1 cudatoolkit=11.2 -c https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/Paddle/ -c conda-forge**此指令，可以通过自测！！！

发现最终问题了，30系列的显卡不支持CUDA10了，以后xdm有这种情况注意一下啦！！！

**Comment by FeixLiu** [comment]
感谢您的反馈，也感谢您对paddle的支持。
