### ISSUE TITLE
请问哪里有离线的安装包whl文件？

### ISSUE THREAD

**Issue by ZZHHogan** [PaddlePaddle/Paddle#38949]
请问哪里有离线的安装包whl文件？
在线安装一直无法连接：
Looking in indexes: https://mirrors.aliyun.com/pypi/simple/
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7f0fa2f3dc40>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /pypi/simple/paddlepaddle-gpu/
WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7f0fa2f3de50>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /pypi/simple/paddlepaddle-gpu/
WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7f0fa2fad7c0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /pypi/simple/paddlepaddle-gpu/
WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7f0fa2fad910>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /pypi/simple/paddlepaddle-gpu/
WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7f0fa2fadeb0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /pypi/simple/paddlepaddle-gpu/
ERROR: Could not find a version that satisfies the requirement paddlepaddle-gpu==2.2.1.post111 (from versions: none)
ERROR: No matching distribution found for paddlepaddle-gpu==2.2.1.post111
所以想直接用离线的安装包直接安装，请问哪里可以提供呢？

**Comment by WorgenZhang** [comment]
您好，linux: https://www.paddlepaddle.org.cn/whl/linux/mkl/avx/stable.html   windows: https://www.paddlepaddle.org.cn/whl/windows/mkl/avx/stable.html
