### ISSUE TITLE
tile 输入的 repeat_times 列表的长度为什么不能大于 6？

### ISSUE THREAD

**Issue by yt605155624** [PaddlePaddle/Paddle#38958]
参照 https://github.com/PaddlePaddle/Paddle/issues/37227 实现 repeat_interleave 的过程中用到了 paddle.tile, 但是遇到如下错误：
```text
ValueError: (InvalidArgument) The size of the shape of input 'repeat_times' for tile op must not be greater than 6, but the value received is 53.
  [Hint: Expected repeat_times.size() <= 6, but received repeat_times.size():53 > 6:6.] (at /paddle/paddle/fluid/operators/tile_op.cc:50)
  [operator < tile > error]
```
https://www.paddlepaddle.org.cn/documentation/docs/en/api/paddle/tile_en.html#tile
想知道为啥 tile 输入的 repeat_times 列表的长度为什么不能大于 6？可以取消这个限制不

**Comment by WorgenZhang** [comment]
您好，已找负责此api的同事看这个问题，麻烦稍等

**Comment by yt605155624** [comment]
框架  develop 已经实现了 repeat_interleave https://github.com/PaddlePaddle/Paddle/pull/37981/files ，不需要用 tile 去实现 repeat_interleave 了，谢谢
