### ISSUE TITLE
动态图正常训练，转静态图报错 

### ISSUE THREAD

**Issue by johnyanccer** [PaddlePaddle/Paddle#38963]
动态图正常训练，forward @paddle.jit.to_static后出现如下错误，查询文档无相关内容，怀疑是否与paddlenlp有关
UnboundLocalError: In transformed code:

    File "/tmp/ipykernel_101/3422880272.py", line 15, in forward
        inputs = [[1]+x+[2] for x in input_i]
        inputs = paddlenlp.data.Pad()(inputs)
        ~~~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE
        # inputs = paddle.to_tensor(inputs,dtype='int32')
        inputs = paddle.assign(inputs,dtype='int32')


    UnboundLocalError: local variable 'paddle' referenced before assignment

**Comment by WorgenZhang** [comment]
您好，请您提供更完整的代码及描述，并提供paddle版本与系统信息，谢谢

**Comment by wawltor** [comment]
> 动态图正常训练，forward @paddle.jit.to_static后出现如下错误，查询文档无相关内容，怀疑是否与paddlenlp有关 UnboundLocalError: In transformed code:
> 
> ```
> File "/tmp/ipykernel_101/3422880272.py", line 15, in forward
>     inputs = [[1]+x+[2] for x in input_i]
>     inputs = paddlenlp.data.Pad()(inputs)
>     ~~~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE
>     # inputs = paddle.to_tensor(inputs,dtype='int32')
>     inputs = paddle.assign(inputs,dtype='int32')
> 
> 
> UnboundLocalError: local variable 'paddle' referenced before assignment
> ```

您好，目前框架的动转静的能力是基于PaddlePaddle Op层面的，paddlenlp.data.Pad()这个API是基于Numpy操作的，所以没有办法进行动转静的操作。目前PaddleNLP部分的模型的Tokenizer部分(文本处理，Pad、组batch功能)在最新的版本可以直接导入到模型中进行训推一体，具体的功能可以查看 https://github.com/PaddlePaddle/PaddleNLP/tree/develop/examples/faster

**Comment by johnyanccer** [comment]
修改程序流程后，动转静出现warning提示，目测能正常运行，关闭此issuse
感谢回复各位
