### ISSUE TITLE
Type required for Tensor

### ISSUE THREAD

**Issue by zchen0211** [PaddlePaddle/Paddle#3896]
In our current design, our tensor hides types and assumes that the OP works on it knows its type. However, in RNN op and dynamic-if-else op, the inputs and outputs can be of different types, and just passing a <typename T> can't solve it.

Example, in an RNN/if else op, if the subnet or step-net looks like:
```python
with stepnet.block():
  of type float
  logits = pd.fc(x) 

  of type int
  label = pd.data(y) 

  of type float
  loss = pd.softmaxloss(logits, label)
```
We actually need something like Tensor.type(). Currently, my dynamic if/else and Chunwei's dynamic Rnn CAN ONLY PRODUCE FLOAT, which doesn't make sense.

**Comment by Superjom** [comment]
good idea.  tensor is not just a set of memory, it is a typed data structure, so it should know its type for usage or type check, or it is not self-contained. 

to get a float Tensor, `GetMutable<int>()` and `GetMutable<float>()` both compiles fine and runs normally, but the data elements are wrong (float data may be used as int).

**Comment by jacquesqiao** [comment]
currently, in  TensorDesc I have already added DataType
```proto
enum DataType {
  BOOL = 0;
  INT16 = 1;
  INT32 = 2;
  INT64 = 3;
  FP16 = 4;
  FP32 = 5;
  FP64 = 6;
}
```
seems we need to add this info into the cpp tensor.

**Comment by reyoung** [comment]
In Cpp, Tensor's type has been already recorded in `holder_`. To use `holder_->type()` can get the `Type` of `Tensor` stores.

See [code](https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/framework/tensor.h#L144) here.

However, method `type()` has not been exposed in `Tensor`.  So do we need `Tensor::type()` method?

**Comment by dzhwinter** [comment]
@reyoung the return type of  `type()` is`type_index`. Which is not a complete/real type. => I mean it can not be used as a tensor type, still can not solve the problem.

**Comment by dzhwinter** [comment]
The core problem is that we really need sth like `TypeMeta` to store tensor type inside,  which we can convert/revert type from tensor.
