### ISSUE TITLE
如何裁剪C++预测库？

### ISSUE THREAD

**Issue by wzyforgit** [PaddlePaddle/Paddle#38978]
- 标题：如何裁剪C++预测库？
- 版本、环境信息：
    1）PaddlePaddle版本：2.0以后任意版本
    2）CPU：任意CPU，使用OpenBLAS
    3）GPU：不使用GPU
    4）系统环境：UOS 1041
本地编译：只打开ON_INFER，其余option全部OFF

现象：C++预测库的动态库体积在Release模式下达到111MB，即便使用工具去除符号表并用UPX进行压缩，依然有超过90MB的体积
期望：能尽可能地裁剪预测库，因为我只在桌面环境进行部署然后只使用CPU进行预测，并不需要其它各种牛逼的高级功能，就是希望能在这种比较特殊的定制化环境下能最大化裁剪这个预测库，能省一点空间是一点
PS：我知道隔壁Paddle Lite的体积小，但有些国产平台它不支持，比如龙芯什么的。而且x86下它还强依赖MKL，导致我们直接放弃使用
PPS：使用系统自带的OpenBLAS是可以减少大约20MB的体积，但是有些系统，比如我司用的UOS，源里面的OpenBLAS版本太老，跑点简单的模型都一堆BUG，根本不可控，还是得用脚本里面检出的版本

**Comment by wzyforgit** [comment]
好了，加了一坨编译参数，还有70.8MB......还是有点大

**Comment by jiweibo** [comment]
您好，如果只是预测部署场景还可以试下反向op的裁剪。

```
cd ${PADDLE_ROOT}
python tools/remove_grad_op_and_kernel.py

# 重新编译
```

**Comment by wzyforgit** [comment]
> 您好，如果只是预测部署场景还可以试下反向op的裁剪。
> 
> ```
> cd ${PADDLE_ROOT}
> python tools/remove_grad_op_and_kernel.py
> 
> # 重新编译
> ```

非常感谢指导！虽然只是少了10MB左右，但也算是个很大的进步吧（捂脸
这调试了几天，我感觉还是只能尽量把没用到的OP删了，能少1MB是1MB，实在是没有裁主框架的实力233333333
