### ISSUE TITLE
Paddle Release2.2  VS2017 编译报错 LINK : fatal error LNK1248

### ISSUE THREAD

**Issue by friendan** [PaddlePaddle/Paddle#38987]
我的环境： WIN7 X64 + VS2017
编译 Paddle Release2.2 解决方案中的预测库：
项目：paddle_inference_shared 选择的是release版本，报错如下：
LINK : fatal error LNK1248: 映像大小(8085D000)超过允许的最大大小(80000000)
怎么解决呢？

**Comment by VantastyChen** [comment]
同样遇到这个问题

**Comment by zhwesky2010** [comment]
@friendan  你好，develop的体积小一些，可以用develop版本编

**Comment by hibean** [comment]
@friendan 请问，该问题解决了没？如果解决的话，可否详细说一下
