### ISSUE TITLE
为了提高混合精度训练的效率，如何配置模型结构？

### ISSUE THREAD

**Issue by wxzylforever** [PaddlePaddle/Paddle#38994]
paddle大佬您们好，求帮助。我搭建了一个卷积网络，想例如 混合精度训练（float32和float16）提高训练速度，我应该如何配置模型的结构，比如 输入输出feature map的形状什么的，还有激活函数什么的，请问有这方面的资料吗？

**Comment by youth123** [comment]
可以看这个文档https://www.paddlepaddle.org.cn/documentation/docs/zh/guides/01_paddle2.0_introduction/basic_concept/amp_cn.html#amp

**Comment by wxzylforever** [comment]
> 可以看这个文档https://www.paddlepaddle.org.cn/documentation/docs/zh/guides/01_paddle2.0_introduction/basic_concept/amp_cn.html#amp

感谢大佬。是这样，我写了一个amp的模型（只有卷积、BN、激活函数，最后有一个Linear），但是训练速度反而比正常的还慢，我怀疑是不是卷积的in_channels,out_channels,kernel size等一些参数对速度有影响。我想配置一些参数尽可能发挥amp的速度优势，这方面有可以借鉴的资料吗？

**Comment by youth123** [comment]
速度变慢的原因可能是模型太小，amp主要就是将一些输入cast成fp16，如果模型过小，cast带来的开销可能会造成训练变慢。你可以试试将模型变大，或者先按照文档的示例来操作看看是否在自己的模型amp的操作有误。

**Comment by wxzylforever** [comment]
不知道你们的amp是不是完全调的nvidia的接口实现的，如果是的话我自己去看NVIDIA的文档就好了
