### ISSUE TITLE
使用gpu内存暴涨

### ISSUE THREAD

**Issue by luomusky** [PaddlePaddle/Paddle#39000]
用的是Nvidia Jetson Nano
CUDA 10.2
cuDNN 8.2
Paddle 2.2 

这边就是当开启gpu检测识别的时候，内存直接暴涨有多少用多少

**Comment by youth123** [comment]
能不能提供具体最小用例和现象呢

**Comment by kouhinn** [comment]
遇到同样的问题。
我的环境是：
Jetpack4.6-nv-jetson-cuda10.2-cudnn8.2-trt8.0_xavier
Jetson AGX Xavier
paddle2_2 inference 对应预编译包

同样的代码在服务器上面跑就比在盒子上占用小。
注：使用trt预测也一样。
