### ISSUE TITLE
百度2021多形态事件抽取基线之前代码没问题，过了一个月自己就报错了？？难道是paddlepaddle-gpu版本自动不适配了？而且官方给的aistudio版本也报错

### ISSUE THREAD

**Issue by lujiang001108** [PaddlePaddle/Paddle#39003]
(py36env) lj@tesla-server:/data/newspace/jiang/DUEE$ bash run_duee_fin.sh trigger_train
check and create directory
dir ./ckpt exist
dir ./ckpt/DuEE-Fin exist
dir ./submit exist

start DuEE-Fin trigger train
-----------  Configuration Arguments -----------
backend: auto
elastic_server: None
force: False
gpus: 1
heter_worker_num: None
heter_workers: 
host: None
http_port: None
ips: 127.0.0.1
job_id: None
log_dir: log
np: None
nproc_per_node: None
run_mode: None
scale: 0
server_num: None
servers: 
training_script: sequence_labeling.py
training_script_args: ['--num_epoch', '9', '--learning_rate', '5e-5', '--tag_path', './conf/DuEE-Fin/trigger_tag.dict', '--train_data', './data/DuEE-Fin/trigger/train.tsv', '--dev_data', './data/DuEE-Fin/trigger/dev.tsv', '--test_data', './data/DuEE-Fin/trigger/test.tsv', '--predict_data', './data/DuEE-Fin/sentence/test.json', '--do_train', 'True', '--do_predict', 'False', '--max_seq_len', '300', '--batch_size', '4', '--skip_step', '10', '--valid_step', '50', '--checkpoints', './ckpt/DuEE-Fin/trigger', '--init_ckpt', './ckpt/DuEE-Fin/trigger/best.pdparams', '--predict_save_path', './ckpt/DuEE-Fin/trigger/test_pred.json', '--device', 'gpu']
worker_num: None
workers: 
------------------------------------------------
WARNING 2022-01-17 20:00:06,964 launch.py:416] Not found distinct arguments and compiled with cuda or xpu. Default use collective mode
launch train in GPU mode!
INFO 2022-01-17 20:00:06,965 launch_utils.py:528] Local start 1 processes. First process distributed environment info (Only For Debug): 
    +=======================================================================================+
    |                        Distributed Envs                      Value                    |
    +---------------------------------------------------------------------------------------+
    |                       PADDLE_TRAINER_ID                        0                      |
    |                 PADDLE_CURRENT_ENDPOINT                 127.0.0.1:53621               |
    |                     PADDLE_TRAINERS_NUM                        1                      |
    |                PADDLE_TRAINER_ENDPOINTS                 127.0.0.1:53621               |
    |                     PADDLE_RANK_IN_NODE                        0                      |
    |                 PADDLE_LOCAL_DEVICE_IDS                        1                      |
    |                 PADDLE_WORLD_DEVICE_IDS                        1                      |
    |                     FLAGS_selected_gpus                        1                      |
    |             FLAGS_selected_accelerators                        1                      |
    +=======================================================================================+

INFO 2022-01-17 20:00:06,965 launch_utils.py:531] details abouts PADDLE_TRAINER_ENDPOINTS can be found in log/endpoints.log, and detail running logs maybe found in log/workerlog.0
launch proc_id:14028 idx:0
[2022-01-17 20:00:08,112] [    INFO] - Already cached /home/lj/.paddlenlp/models/ernie-1.0/vocab.txt
[2022-01-17 20:00:08,125] [    INFO] - Already cached /home/lj/.paddlenlp/models/ernie-1.0/ernie_v1_chn_base.pdparams
W0117 20:00:08.126423 14028 device_context.cc:447] Please NOTE: device: 1, GPU Compute Capability: 6.0, Driver API Version: 11.4, Runtime API Version: 11.0
W0117 20:00:08.126626 14028 dynamic_loader.cc:287] The third-party dynamic library (libcudnn.so) that Paddle depends on is not configured correctly. (error code is /usr/local/cuda/lib64/libcudnn.so: cannot open shared object file: No such file or directory)
  Suggestions:
  1. Check if the third-party dynamic library (e.g. CUDA, CUDNN) is installed correctly and its version is matched with paddlepaddle you installed.
  2. Configure third-party dynamic library environment variables as follows:
  - Linux: set LD_LIBRARY_PATH by `export LD_LIBRARY_PATH=...`
  - Windows: set PATH by `set PATH=XXX;
Traceback (most recent call last):
  File "sequence_labeling.py", line 294, in <module>
    do_train()
  File "sequence_labeling.py", line 148, in do_train
    model = ErnieForTokenClassification.from_pretrained("ernie-1.0", num_classes=len(label_map))
  File "/data/anaconda3/envs/py36env/lib/python3.6/site-packages/paddlenlp/transformers/model_utils.py", line 307, in from_pretrained
    base_model = cls.base_model_class(*base_args, **base_kwargs)
  File "/data/anaconda3/envs/py36env/lib/python3.6/site-packages/paddlenlp/transformers/utils.py", line 83, in __impl__
    init_func(self, *args, **kwargs)
  File "/data/anaconda3/envs/py36env/lib/python3.6/site-packages/paddlenlp/transformers/ernie/modeling.py", line 270, in __init__
    max_position_embeddings, type_vocab_size, pad_token_id)
  File "/data/anaconda3/envs/py36env/lib/python3.6/site-packages/paddlenlp/transformers/ernie/modeling.py", line 43, in __init__
    vocab_size, hidden_size, padding_idx=pad_token_id)
  File "/data/anaconda3/envs/py36env/lib/python3.6/site-packages/paddle/nn/layer/common.py", line 1390, in __init__
    is_bias=False)
  File "/data/anaconda3/envs/py36env/lib/python3.6/site-packages/paddle/fluid/dygraph/layers.py", line 424, in create_parameter
    default_initializer)
  File "/data/anaconda3/envs/py36env/lib/python3.6/site-packages/paddle/fluid/layer_helper_base.py", line 378, in create_parameter
    **attr._to_kwargs(with_initializer=True))
  File "/data/anaconda3/envs/py36env/lib/python3.6/site-packages/paddle/fluid/framework.py", line 3137, in create_parameter
    initializer(param, self)
  File "/data/anaconda3/envs/py36env/lib/python3.6/site-packages/paddle/fluid/initializer.py", line 572, in __call__
    stop_gradient=True)
  File "/data/anaconda3/envs/py36env/lib/python3.6/site-packages/paddle/fluid/framework.py", line 3167, in append_op
    kwargs.get("stop_gradient", False))
  File "/data/anaconda3/envs/py36env/lib/python3.6/site-packages/paddle/fluid/dygraph/tracer.py", line 45, in trace_op
    not stop_gradient)
RuntimeError: (PreconditionNotMet) Cannot load cudnn shared library. Cannot invoke method cudnnGetVersion.
  [Hint: cudnn_dso_handle should not be null.] (at /paddle/paddle/fluid/platform/dynload/cudnn.cc:59)
  [operator < uniform_random > error]
INFO 2022-01-17 20:00:13,991 launch_utils.py:340] terminate all the procs
ERROR 2022-01-17 20:00:13,992 launch_utils.py:603] ABORT!!! Out of all 1 trainers, the trainer process with rank=[0] was aborted. Please check its log.
INFO 2022-01-17 20:00:17,996 launch_utils.py:340] terminate all the procs
INFO 2022-01-17 20:00:17,996 launch.py:304] Local processes completed.
end DuEE-Fin trigger train

**Comment by youth123** [comment]
我们会安排具体人查看

**Comment by youth123** [comment]
那个请问是ai studio的哪一个用例呢
