### ISSUE TITLE
同样结构的模型加载两次出错，如何解决

### ISSUE THREAD

**Issue by wezard1995** [PaddlePaddle/Paddle#39027]
paddle版本:2.3
GPU:Tesla v100, cuda11.0 
系统环境：Linux python版本3.7

用不同的数据训了两版相同结构的动态图模型，在动态图模式下inferance时出现以下情况：
model1 = net()
model2 = net()

if a:
    model1.infer_img(img)
else:
    model2.infer_img(img)

Traceback (most recent call last):
  File "lanetest.py", line 200, in <module>
    r = lanerec.infer_img_file('./1_000183_0_bi0_i78,i74,i75.jpg')
  File "lanetest.py", line 127, in infer_img_file
    pred = self.infer_img(img)
  File "lanetest.py", line 145, in infer_img
    paddle.to_tensor(encoder_word_pos_list),
  File "<decorator-gen-127>", line 2, in to_tensor
  File "/home/.local/lib/python3.6/site-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl_
    return wrapped_func(*args, **kwargs)
  File "/home.local/lib/python3.6/site-packages/paddle/fluid/framework.py", line 226, in __impl__
    ), "We only support '%s()' in dynamic graph mode, please call 'paddle.disable_static()' to enter dynamic graph mode." % func.__name__
AssertionError: We only support 'to_tensor()' in dynamic graph mode, please call 'paddle.disable_static()' to enter dynamic graph mode.

**Comment by GuoxiaWang** [comment]
@wezard1995 

在 import paddle 后添加

paddle.disable_static()

**Comment by wezard1995** [comment]
@GuoxiaWang 试过了不行，用的是paddleocr的basemodel, build srn的时候create_parameter 没给name参数

**Comment by wezard1995** [comment]
@GuoxiaWang 主要是这个问题
ValueError: parameter name [loc_conv0_weights] have be been used. In dygraph mode, the name of parameter can't be same.Please check the parameter attr value passed to self.create_parameter or constructor of dygraph Layers

**Comment by wezard1995** [comment]
enable_static后出现的是这个信息
 File "lanetest.py", line 145, in infer_img
    paddle.to_tensor(encoder_word_pos_list),
  File "<decorator-gen-127>", line 2, in to_tensor
  File "/home/hll_root/.local/lib/python3.6/site-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
    return wrapped_func(*args, **kwargs)
 "We only support '%s()' in dynamic graph mode, please call 'paddle.disable_static()' to enter dynamic graph mode." % func.__name__
AssertionError: We only support 'to_tensor()' in dynamic graph mode, please call 'paddle.disable_static()' to enter dynamic graph mode.

**Comment by GuoxiaWang** [comment]
@wezard1995 以前你有做过类似的推理？两个模型一模一样，然后，就是参数不一样，就像你这样加载？

**Comment by wezard1995** [comment]
@GuoxiaWang backbone可以改啊，有name参数，换掉就行了，比如两个resnet是ok的，但是transfomer embedding 和 self-attention的部分没给name 参数，只能用默认的name，所以报错了

**Comment by GuoxiaWang** [comment]
@wezard1995 给整个模型加个前缀呢？
例如
```
model1 = net('model1')
model2 = net('model2')
```

参考 https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/fluid/dygraph/layers.py#L101

**Comment by wezard1995** [comment]
@GuoxiaWang 两个model分别是两个class，model1 = class1(), model2 = class2()，内部结构是相同的，另外都是基于paddleocr的base model 构建的，有点难改。。

**Comment by GuoxiaWang** [comment]
@wezard1995 能提供一个最小的测试代码吗？我复现一下，用于排查问题

**Comment by wezard1995** [comment]
@GuoxiaWang 可以的，需要ppocr
``
from ppocr.modeling.transforms import tps, tps_ocr
from ppocr.modeling.backbones import rec_resnet_fpn
from ppocr.modeling.heads import  rec_srn_head, self_attention
import paddle
import paddle.nn as nn
class basemodelarrow(nn.Layer):
    def __init__(self):
        super(basemodelarrow, self).__init__(name_scope='bbb')
        self.transform = tps.TPS(in_channels=1, num_fiducial=10, loc_lr=0.01, model_name='small')
        self.backbone = rec_resnet_fpn.ResNetFPN()
        self.head = rec_srn_head.SRNHead(in_channels=512, out_channels=17, max_text_length=25, num_heads=8,
                 num_encoder_TUs=2, num_decoder_TUs=4, hidden_dims=512)

    def forward(self, x, `data=None):`
            x = self.transform(x)
            x = self.backbone(x)
            x = self.head(x, targets=data)
            return x

class basemodelocr(nn.Layer):
    def __init__(self):
        super(basemodelocr, self).__init__(name_scope=
                                           'aaa')
        self.transform = tps.TPS(in_channels=1, num_fiducial=10, loc_lr=0.01, model_name='small')
        self.backbone = rec_resnet_fpn.ResNetFPN()
        self.head = rec_srn_head.SRNHead(in_channels=512, out_channels=17, max_text_length=25, num_heads=8,
                 num_encoder_TUs=2, num_decoder_TUs=4, hidden_dims=512)

    def forward(self, x, data=None):
            x = self.transform(x)
            x = self.backbone(x)
            x = self.head(x, targets=data)
            return x
if __name__ == '__main__':
    net1 = basemodelarrow()
    #
    #net3 = basemodelocr()
    print(net1.state_dict())#net2.state_dict())
    net2 = basemodelocr()
    print(net2.state_dict())
``

**Comment by GuoxiaWang** [comment]
@wezard1995 麻烦再用代码模式编辑一下代码吧？我复制过来就可以跑了

**Comment by wezard1995** [comment]
`from ppocr.modeling.transforms import tps, tps_ocr
from ppocr.modeling.backbones import rec_resnet_fpn
from ppocr.modeling.heads import  rec_srn_head, self_attention
import paddle
import paddle.nn as nn
class basemodelarrow(nn.Layer):
    def __init__(self):
        super(basemodelarrow, self).__init__(name_scope='bbb')
        self.transform = tps.TPS(in_channels=1, num_fiducial=10, loc_lr=0.01, model_name='small')
        self.backbone = rec_resnet_fpn.ResNetFPN()
        self.head = rec_srn_head.SRNHead(in_channels=512, out_channels=17, max_text_length=25, num_heads=8,
                 num_encoder_TUs=2, num_decoder_TUs=4, hidden_dims=512)

    def forward(self, x, data=None):
            # x = self.transform(x)
            # x = self.backbone(x)
            x = self.head(x, targets=data)
            return x

class basemodelocr(nn.Layer):
    def __init__(self):
        super(basemodelocr, self).__init__(name_scope=
                                           'aaa')
        self.transform = tps.TPSocr(in_channels=1, num_fiducial=10, loc_lr=0.01, model_name='small')
        self.backbone = rec_resnet_fpn.ResNetFPN()
        self.head = rec_srn_head.SRNHead(in_channels=512, out_channels=17, max_text_length=25, num_heads=8,
                 num_encoder_TUs=2, num_decoder_TUs=4, hidden_dims=512)

    def forward(self, x, data=None):
            # x = self.transform(x)
            # x = self.backbone(x)
            x = self.head(x, targets=data)
            return x
if __name__ == '__main__':
    net1 = basemodelarrow()
    #
    #net3 = basemodelocr()
    print(net1.state_dict())#net2.state_dict())
    net2 = basemodelocr()
    print(net2.state_dict())
    #net1 = basemodelarrow()
    #
    # net3 = basemodelocr()
    print(net1.state_dict())`

**Comment by wezard1995** [comment]
`
from ppocr.modeling.transforms import tps, tps_ocr
from ppocr.modeling.backbones import rec_resnet_fpn
from ppocr.modeling.heads import  rec_srn_head, self_attention
import paddle
import paddle.nn as nn
class basemodelarrow(nn.Layer):
    def __init__(self):
        super(basemodelarrow, self).__init__(name_scope='bbb')
        self.transform = tps.TPS(in_channels=1, num_fiducial=10, loc_lr=0.01, model_name='small')
        self.backbone = rec_resnet_fpn.ResNetFPN()
        self.head = rec_srn_head.SRNHead(in_channels=512, out_channels=17, max_text_length=25, num_heads=8,
                 num_encoder_TUs=2, num_decoder_TUs=4, hidden_dims=512)

    def forward(self, x, data=None):
            # x = self.transform(x)
            # x = self.backbone(x)
            x = self.head(x, targets=data)
            return x

class basemodelocr(nn.Layer):
    def __init__(self):
        super(basemodelocr, self).__init__(name_scope=
                                           'aaa')
        self.transform = tps.TPSocr(in_channels=1, num_fiducial=10, loc_lr=0.01, model_name='small')
        self.backbone = rec_resnet_fpn.ResNetFPN()
        self.head = rec_srn_head.SRNHead(in_channels=512, out_channels=17, max_text_length=25, num_heads=8,
                 num_encoder_TUs=2, num_decoder_TUs=4, hidden_dims=512)

    def forward(self, x, data=None):
            # x = self.transform(x)
            # x = self.backbone(x)
            x = self.head(x, targets=data)
            return x
if __name__ == '__main__':
    net1 = basemodelarrow()
    #
    #net3 = basemodelocr()
    print(net1.state_dict())#net2.state_dict())
    net2 = basemodelocr()
    print(net2.state_dict())
    #net1 = basemodelarrow()
    #
    # net3 = basemodelocr()
    print(net1.state_dict())
`

**Comment by wezard1995** [comment]
``

from ppocr.modeling.transforms import tps, tps_ocr
from ppocr.modeling.backbones import rec_resnet_fpn
from ppocr.modeling.heads import  rec_srn_head, self_attention
import paddle
import paddle.nn as nn
class basemodelarrow(nn.Layer):
    def __init__(self):
        super(basemodelarrow, self).__init__(name_scope='bbb')
        self.transform = tps.TPS(in_channels=1, num_fiducial=10, loc_lr=0.01, model_name='small')
        self.backbone = rec_resnet_fpn.ResNetFPN()
        self.head = rec_srn_head.SRNHead(in_channels=512, out_channels=17, max_text_length=25, num_heads=8,
                 num_encoder_TUs=2, num_decoder_TUs=4, hidden_dims=512)

    def forward(self, x, data=None):
            # x = self.transform(x)
            # x = self.backbone(x)
            x = self.head(x, targets=data)
            return x

class basemodelocr(nn.Layer):
    def __init__(self):
        super(basemodelocr, self).__init__(name_scope=
                                           'aaa')
        self.transform = tps.TPSocr(in_channels=1, num_fiducial=10, loc_lr=0.01, model_name='small')
        self.backbone = rec_resnet_fpn.ResNetFPN()
        self.head = rec_srn_head.SRNHead(in_channels=512, out_channels=17, max_text_length=25, num_heads=8,
                 num_encoder_TUs=2, num_decoder_TUs=4, hidden_dims=512)

    def forward(self, x, data=None):
            # x = self.transform(x)
            # x = self.backbone(x)
            x = self.head(x, targets=data)
            return x
if __name__ == '__main__':
    net1 = basemodelarrow()
    #
    #net3 = basemodelocr()
    print(net1.state_dict())#net2.state_dict())
    net2 = basemodelocr()
    print(net2.state_dict())
    #net1 = basemodelarrow()
    #
    # net3 = basemodelocr()
    print(net1.state_dict())

``

**Comment by wezard1995** [comment]
```
from ppocr.modeling.transforms import tps
from ppocr.modeling.backbones import rec_resnet_fpn
from ppocr.modeling.heads import  rec_srn_head, self_attention
import paddle
import paddle.nn as nn
class basemodelarrow(nn.Layer):
    def __init__(self):
        super(basemodelarrow, self).__init__(name_scope='bbb')
        self.transform = tps.TPS(in_channels=1, num_fiducial=10, loc_lr=0.01, model_name='small')
        self.backbone = rec_resnet_fpn.ResNetFPN()
        self.head = rec_srn_head.SRNHead(in_channels=512, out_channels=17, max_text_length=25, num_heads=8,
                 num_encoder_TUs=2, num_decoder_TUs=4, hidden_dims=512)

    def forward(self, x, data=None):
            x = self.transform(x)
            x = self.backbone(x)
            x = self.head(x, targets=data)
            return x

class basemodelocr(nn.Layer):
    def __init__(self):
        super(basemodelocr, self).__init__(name_scope=
                                           'aaa')
        self.transform = tps.TPS(in_channels=1, num_fiducial=10, loc_lr=0.01, model_name='small')
        self.backbone = rec_resnet_fpn.ResNetFPN()
        self.head = rec_srn_head.SRNHead(in_channels=512, out_channels=17, max_text_length=25, num_heads=8,
                 num_encoder_TUs=2, num_decoder_TUs=4, hidden_dims=512)

    def forward(self, x, data=None):
            x = self.transform(x)
            x = self.backbone(x)
            x = self.head(x, targets=data)
            return x
if __name__ == '__main__':
    net1 = basemodelarrow()
    #
    #net3 = basemodelocr()
    print(net1.state_dict())#net2.state_dict())
    net2 = basemodelocr()
    print(net2.state_dict())
    #net1 = basemodelarrow()
    #
    # net3 = basemodelocr()
    print(net1.state_dict())
```

**Comment by GuoxiaWang** [comment]
@wezard1995 ppocr 就是 paddleorc? 

我通过 `pip install "paddleocr>=2.0.1"` 安装也找不到 `No module named 'ppocr'`

**Comment by wezard1995** [comment]
@GuoxiaWang 是的，paddleocr里面的一个包（文件夹），我是直接git clone在paddleocr的root下运行的

**Comment by GuoxiaWang** [comment]
@wezard1995 我已经下载下来了，我放在 `PaddleOCR` 目录下，然后 python test.py 报 `ImportError: cannot import name 'tps_ocr' from 'ppocr.modeling.transforms'`

为了快速定位关心的问题，你是否能告知我如何跑起你的代码

**Comment by wezard1995** [comment]
@GuoxiaWang 你重新复制一下，我已经修改了。。tps_ocr是我自己后加的

**Comment by GuoxiaWang** [comment]
@wezard1995 因为 paddlleorc 定义模型的时候，把名字固定死了 [L47](https://github.com/PaddlePaddle/PaddleOCR/blob/22b1fb3181a2e8e1a86776ab9aa10fb6abe1c896/ppocr/modeling/transforms/tps.py#L47)，所以冲突了，如果不固定会自动命名

你可以修改命名规则来达到你的需求，例如 [L79](https://github.com/PaddlePaddle/PaddleOCR/blob/22b1fb3181a2e8e1a86776ab9aa10fb6abe1c896/ppocr/modeling/transforms/tps.py#L79)

```
name = model_name + "loc_conv%d" % fno
```

**Comment by wezard1995** [comment]
@GuoxiaWang 实例化之后可以了，谢谢指导！

**Comment by GuoxiaWang** [comment]
@wezard1995 好的，客气。
