### ISSUE TITLE
如何根据修改已有inference模型的输入为“动态shape”

### ISSUE THREAD

**Issue by zzcgithub** [PaddlePaddle/Paddle#39031]
目前已有一些导出的模型参数（__model__/__params）, 可以通过paddle框架进行正常的推理，但是因为输入的shape已经固定，导致无法进行动态推理/无法使用tensorrt。具体问题如下，模型的输入输出截图截图均由netron可视化得出。

**问题1**
通过x2paddle将onnx模型转为paddle的模型参数，paddle版本2.1。

 如何将输入的shape从1x3x224x224，修改为？x3x224x224  ， 将输出(1x69)改为shape ？x69。

![image](https://user-images.githubusercontent.com/13117136/149948892-046d5b99-b74e-4b63-9277-dc17961c6176.png)

**问题2**
 使用paddledetection导出的faster-rcnn检测模型，paddle版本1.8.4，只有model和params参数。

 如何将输入的shape从（[?,3,?,?]）转化为（?x3x512x512)， 以便支持tensorrt的推理加速

![image](https://user-images.githubusercontent.com/13117136/149950444-24793e7e-6f5a-479e-b900-f9c1eeaf0dd7.png)

**问题3**
使用paddledetection导出ppyolo的检测模型paddle版本2.1， 能否将matrix nms的输出改成动态形式？
即从[3840,6] -> [?,3840,6]

![image](https://user-images.githubusercontent.com/13117136/149951179-94cd2284-f109-4534-b880-8ad8fcda47e4.png)

**Comment by shangzhizhou** [comment]
您好，
1. 问题一，看描述是只用修改batchsize，修改这个可以通过推理开启TensorRT的配置时指定max_batch_size
` config.EnableTensorRtEngine(1 << 30, max_batch_size, 5,
                              PrecisionType::kFloat32, false, false);`
2.问题二，如果模型组网时使用了动态shape([?,3,?,?])，使用tensorRT推理也需要开启动态shape，示例如下(文档链接：https://paddleinference.paddlepaddle.org.cn/api_reference/cxx_api_doc/Config/GPUConfig.html#tensorrt)：
``` 
std::map<std::string, std::vector<int>> min_input_shape = {
    {"input1", {1, 3, 112, 112}},
    {"input2", {1, 3, 112, 112}}
};
std::map<std::string, std::vector<int>> max_input_shape = {
    {"input1", {max_batch_size, 3, 448, 448}},
    {"input2", {max_batch_size, 3, 448, 448}}
};
std::map<std::string, std::vector<int>> opt_input_shape = {
    {"input1", {opt_batch_size, 3, 224, 224}},
    {"input2", {opt_batch_size, 3, 224, 224}}
};
config.SetTRTDynamicShapeInfo(min_input_shape, max_input_shape,
                                opt_input_shape);
```
参考如上示例设置TensorRT子图的每个输入变量的动态变化范围，如果不确定输入变量名，可以根据启动的日志提示确定。要求运行时的shape在max和min之间，opt用来作为优化策略选择的参考shape。

**Comment by zzcgithub** [comment]
内部使用版本so不支持tensorrt的动态shape。

问题1: x2paddle已解决

问题2:  能否加载model/params，进行input/output的修改，重新生成新的model/params，使得输入的shape从（[?,3,?,?]）转化为（?x3x512x512)

**Comment by shangzhizhou** [comment]
> 问题2: 能否加载model/params，进行input/output的修改，重新生成新的model/params，使得输入的shape从（[?,3,?,?]）转化为（?x3x512x512)

如果有组网代码，可以尝试将输入变量的shape中的-1改为具体的数值
