### ISSUE TITLE
paddle cluster predict fail

### ISSUE THREAD

**Issue by shenshuijing** [PaddlePaddle/Paddle#3904]
我产出了一个模型， 由于要预测的量较大， 所以希望通过集群来预测， 几个问题：
1. 是否支持cluster 的predict
2. 如果支持的话， 应该如何配置实现， 我在本机上跑local的predict的时候是可以的（train_list设置成了None），配置项为：
![image](https://user-images.githubusercontent.com/24400858/30096648-3ee051e8-930c-11e7-8e20-1953b98b1b01.png)
但是在集群去跑的时候， 提交的时候不支持说--job=test的设置， 所以我的设置是这样的：
![image](https://user-images.githubusercontent.com/24400858/30096766-de08da4c-930c-11e7-87cb-1ccf9f581c68.png)

结果老是出错，我看错误信息中有 （因为是预测， 我已经在trainer_config.conf中如果是predict的情况下， 吧train.list设置成None了）
 check_return 'mpirun download.py download train data failed'
以及：
Tue Sep  5 15:44:01 2017[1,0]<stderr>:*** Aborted at 1504597441 (unix time) try "date -d @1504597441" if you are using GNU date ***
Tue Sep  5 15:44:01 2017[1,0]<stderr>:PC: @                0x0 (unknown)
Tue Sep  5 15:44:01 2017[1,0]<stderr>:*** SIGSEGV (@0xd8) received by PID 21377 (TID 0x7fa75bf88780) from PID 216; stack trace: ***
Tue Sep  5 15:44:01 2017[1,0]<stderr>:    @     0x7fa75b743160 (unknown)
Tue Sep  5 15:44:01 2017[1,0]<stderr>:    @           0x6f4fab paddle::DataProvider::getNextBatch()
Tue Sep  5 15:44:01 2017[1,0]<stderr>:    @           0x749a83 paddle::Trainer::trainOnePass()
Tue Sep  5 15:44:01 2017[1,0]<stderr>:    @           0x74a375 paddle::Trainer::train()
Tue Sep  5 15:44:01 2017[1,0]<stderr>:    @           0x5a3d70 main
Tue Sep  5 15:44:01 2017[1,0]<stderr>:    @     0x7fa75a987bd5 __libc_start_main
Tue Sep  5 15:44:01 2017[1,0]<stderr>:    @           0x5b2169 (unknown)
Tue Sep  5 15:44:01 2017[1,0]<stderr>:    @                0x0 (unknown)
Tue Sep  5 15:44:02 2017[1,0]<stderr>:./train.sh: line 207: 21377 Segmentation fault      PYTHONPATH=./paddle:$PYTHONPATH GLOG_logtostderr=0 GLOG_log_dir="./log" ./paddle_trainer --num_gradient_servers=${OMPI_COMM_WORLD_SIZE} --trainer_id=${OMPI_COMM_WORLD_RANK} --pservers=$ipstring --rdma_tcp=${rdma_tcp} --nics=${nics} ${train_arg} --config=conf/trainer_config.conf --save_dir=./${save_dir} ${extern_arg}
Tue Sep  5 15:44:02 2017[1,0]<stderr>:+ '[' 139 -ne 0 ']'
Tue Sep  5 15:44:02 2017[1,0]<stderr>:+ kill_pserver2_exit
Tue Sep  5 15:44:02 2017[1,0]<stderr>:+ ps aux
Tue Sep  5 15:44:02 2017[1,0]<stderr>:+ grep paddle_pserver2
Tue Sep  5 15:44:02 2017[1,0]<stderr>:+ grep paddle_cluster_job
Tue Sep  5 15:44:02 2017[1,0]<stderr>:+ grep -v grep
Tue Sep  5 15:44:02 2017[1,0]<stderr>:+ cut -c10-14
Tue Sep  5 15:44:02 2017[1,0]<stderr>:+ xargs kill -9
Tue Sep  5 15:44:02 2017[1,0]<stderr>:+ log_fatal 'paddle_trainer failed kill paddle_pserver2 and exit'
Tue Sep  5 15:44:02 2017[1,0]<stderr>:+ echo '[./common.sh : 399] [kill_pserver2_exit]'
Tue Sep  5 15:44:02 2017[1,0]<stderr>:[./common.sh : 399] [kill_pserver2_exit]
Tue Sep  5 15:44:02 2017[1,0]<stderr>:+ echo '[FATAL]: paddle_trainer failed kill paddle_pserver2 and exit'
Tue Sep  5 15:44:02 2017[1,0]<stderr>:[FATAL]: paddle_trainer failed kill paddle_pserver2 and exit
Tue Sep  5 15:44:02 2017[1,0]<stderr>:+ get_stack
Tue Sep  5 15:44:02 2017[1,0]<stderr>:+ set +x
Tue Sep  5 15:44:02 2017[1,0]<stderr>:
Tue Sep  5 15:44:02 2017[1,0]<stderr>:*********************Shell Script Stack Trace********************
Tue Sep  5 15:44:02 2017[1,0]<stderr>: @: [./log.sh: 41] log_fatal
Tue Sep  5 15:44:02 2017[1,0]<stderr>: @: [./common.sh: 399] kill_pserver2_exit
Tue Sep  5 15:44:02 2017[1,0]<stderr>: @: [./train.sh: 210] main
Tue Sep  5 15:44:02 2017[1,0]<stderr>:
Tue Sep  5 15:44:02 2017[1,0]<stderr>:+ exit 1

**Comment by luotao1** [comment]
1. 是支持集群的预测功能。
2. 是用`--job=test`模式

> 提交的时候不支持说--job=test的设置

有具体的错误么？

**Comment by shenshuijing** [comment]
我加上--job=test以后有以下提示：
usage: submit.py [-h] [-w WHERE] [-n NUM_NODES] [-j JOB_NAME] [-s SUBMITTER]
                 [-l TIME_LIMIT] [-p JOB_PRIORITY] [-t USE_GPU] [-f CONFIG]
                 [-i THIRDPARTY] [-c SHELL]
submit.py: error: ambiguous option: --job=test could match --job_priority, --job_name

**Comment by luotao1** [comment]
请问是v2还是v1的，v2的如果只是跑预测，cluster_train可以不用指定这个--job=test参数，指定执行infer.py里只跑预测就行了。

**Comment by shenshuijing** [comment]
我的是v1的

**Comment by typhoonzero** [comment]
前面报错中的：
```
Tue Sep 5 15:44:01 2017[1,0]: @ 0x6f4fab paddle::DataProvider::getNextBatch()
```
可能和dataprovider相关的错误，请检查下dataprovider是否有错误。

> v1支持集群的predict吗？

可以支持集群预测，是需要指定`--job=test`的

**Comment by shenshuijing** [comment]
我一加--job=test，就报错， 提示如上：
usage: submit.py [-h] [-w WHERE] [-n NUM_NODES] [-j JOB_NAME] [-s SUBMITTER]
[-l TIME_LIMIT] [-p JOB_PRIORITY] [-t USE_GPU] [-f CONFIG]
[-i THIRDPARTY] [-c SHELL]
submit.py: error: ambiguous option: --job=test could match --job_priority, --job_name

**Comment by typhoonzero** [comment]
你可以试下不用`--job=test`，在配置训练数据时，train.list配置成None。

**Comment by shenshuijing** [comment]
还是一直报这个错误， 我觉得不是provider的问题， 我看错误堆栈是：
Wed Sep  6 16:24:20 2017[1,0]<stderr>:*** Aborted at 1504686260 (unix time) try "date -d @1504686260" if you are using GNU date ***
Wed Sep  6 16:24:20 2017[1,0]<stderr>:PC: @                0x0 (unknown)
Wed Sep  6 16:24:20 2017[1,0]<stderr>:*** SIGSEGV (@0xd8) received by PID 39107 (TID 0x7fe587218780) from PID 216; stack trace: ***
Wed Sep  6 16:24:20 2017[1,0]<stderr>:    @     0x7fe5869d3160 (unknown)
Wed Sep  6 16:24:20 2017[1,0]<stderr>:    @           0x6f4fab paddle::DataProvider::getNextBatch()
Wed Sep  6 16:24:20 2017[1,0]<stderr>:    @           0x749a83 paddle::Trainer::trainOnePass()
Wed Sep  6 16:24:20 2017[1,0]<stderr>:    @           0x74a375 paddle::Trainer::train()
Wed Sep  6 16:24:20 2017[1,0]<stderr>:    @           0x5a3d70 main
Wed Sep  6 16:24:20 2017[1,0]<stderr>:    @     0x7fe585c17bd5 __libc_start_main
Wed Sep  6 16:24:20 2017[1,0]<stderr>:    @           0x5b2169 (unknown)
Wed Sep  6 16:24:20 2017[1,0]<stderr>:    @                0x0 (unknown)

因为我已经设置了train list为None了， 但是看日志还是在trainOnePass， 获取训练数据失败？

**Comment by HugoLian** [comment]
我也是同样的问题，说cluster_train不支持job=test这个参数。如果不加这个，后面不管是不是把train.list设置为None，都会在读取init_model_path得时候出错，可能和这个参数有关系。

**Comment by Yancey1989** [comment]
Hi @HugoLian @shenshuijing 

问题已修复，请下载wiki中最新的客户端，并在提交时指定`--job=test`。
