### ISSUE TITLE
ubuntu18.04下编译报错

### ISSUE THREAD

**Issue by simuler** [PaddlePaddle/Paddle#39042]
- 版本、环境信息：
    1）PaddlePaddle版本：paddle/release2.2
    2）CPU：AMD
    3）GPU：请提供GPU型号，CUDA和CUDNN版本号
    4）系统环境：ubuntu18.04

- 安装方式信息：
1）pip安装
2）本地编译：make -j4
使用make编译报如下错误
simuler@ubuntu:~/Paddle/build_cuda$ make -j4
[ 24%] copy_if_different /home/simuler/Paddle/build_cuda/paddle/fluid/operators/jit/kernels.h
[ 24%] copy_if_different /home/simuler/Paddle/build_cuda/paddle/fluid/inference/api/paddle_inference_pass.h
[ 24%] Built target extern_zlib
[ 24%] Built target extern_gflags
[ 24%] Built target copy_kernels_command
[ 24%] Built target copy_paddle_inference_pass_command
[ 24%] copy_if_different /home/simuler/Paddle/build_cuda/paddle/fluid/pybind/pybind.h
[ 24%] Built target extern_boost
[ 24%] Built target copy_pybind_command
[ 24%] Built target extern_eigen3
[ 24%] Built target extern_xbyak
[ 24%] Built target extern_threadpool
[ 24%] Built target extern_dlpack
[ 24%] Built target extern_pocketfft
[ 24%] Built target extern_openblas
[ 24%] Built target extern_cryptopp
[ 24%] Built target extern_warpctc
[ 24%] Built target extern_lapack
[ 24%] Built target extern_utf8proc
[ 24%] Built target extern_pybind
paddle/fluid/platform/CMakeFiles/profiler_py_proto_init.dir/build.make:57: recipe for target 'paddle/fluid/platform/CMakeFiles/profiler_py_proto_init' failed
make[2]: *** [paddle/fluid/platform/CMakeFiles/profiler_py_proto_init] Error 1
CMakeFiles/Makefile2:2885: recipe for target 'paddle/fluid/platform/CMakeFiles/profiler_py_proto_init.dir/all' failed
make[1]: *** [paddle/fluid/platform/CMakeFiles/profiler_py_proto_init.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 24%] Built target extern_gloo
paddle/fluid/framework/CMakeFiles/framework_py_proto_init.dir/build.make:57: recipe for target 'paddle/fluid/framework/CMakeFiles/framework_py_proto_init' failed
make[2]: *** [paddle/fluid/framework/CMakeFiles/framework_py_proto_init] Error 1
CMakeFiles/Makefile2:5017: recipe for target 'paddle/fluid/framework/CMakeFiles/framework_py_proto_init.dir/all' failed
make[1]: *** [paddle/fluid/framework/CMakeFiles/framework_py_proto_init.dir/all] Error 2
paddle/fluid/framework/CMakeFiles/fleet_proto_init.dir/build.make:57: recipe for target 'paddle/fluid/framework/CMakeFiles/fleet_proto_init' failed
make[2]: *** [paddle/fluid/framework/CMakeFiles/fleet_proto_init] Error 1
CMakeFiles/Makefile2:5054: recipe for target 'paddle/fluid/framework/CMakeFiles/fleet_proto_init.dir/all' failed
make[1]: *** [paddle/fluid/framework/CMakeFiles/fleet_proto_init.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by liutiexing** [comment]
您好，您这个报错信息没有error关键字，只显示了CMAKE在编译proto文件的python版本时fail了，现有信息我无法判断发生了什么。
请您重试一下，或者详细完整描述一下你的过程。比如时docker还是源代码编译，什么操作系统等信息。如果可稳定复现，我们会自己复现一下。谢谢

**Comment by simuler** [comment]
您好，我使用的是ubuntu18.04的系统，没有GPU，gcc版本是7.5，Paddle切换到了release2.2分支，下载的是manylinux_cpu_noavx_openblas_gcc8.2版本的Paddle Inference C++预测库，按照这个网址https://paddleinference.paddlepaddle.org.cn/user_guides/source_compile.html#ubuntu-18-04步骤进行编译的
按照步骤进行编译，并做了如下修改：
1、cmake .. -DPY_VERSION=3 \
        -DWITH_TESTING=OFF \
        -DWITH_MKL=OFF \
        -DWITH_GPU=OFF\
        -DON_INFER=ON \
        ..
2、把third-party/*/tmp/*.gitclone.cmake中的下载地址从https下载修改为了git，
然后使用make -j4进行编译，就报上面的错误了

**Comment by liutiexing** [comment]
您好，Paddle使用的是GCC8.2，建议您使用这个版本。
<img width="709" alt="image" src="https://user-images.githubusercontent.com/74819124/150462723-0d69357b-1534-475b-ba24-5bfa1897c470.png">

另外，能否考虑使用docker环境，因为依赖软件众多，docker有利于解决环境问题

**Comment by tongxin** [comment]
请问问题是否已经解决？
