### ISSUE TITLE
paddle.fluid.layers.fc算子出现部分值为nan问题

### ISSUE THREAD

**Issue by bofang98** [PaddlePaddle/Paddle#39059]
在训练网络（有梯度回传）和测试网络（无梯度）时，我们定位到其中一层的fluid.layers.fc的输出的前600维值为nan，导致后面的所有计算值包括loss都为nan，但是其输出的维度没有问题。
请问该算子会存在这样的bug吗，出现nan值是由于什么情况导致的呢？如果不使用fluid.layers.fc，有什么类似于torch中的1dConv来替代fluid.layers.fc的呢？
![image](https://user-images.githubusercontent.com/42595629/150244773-d6dfae14-1389-4bd7-901f-74445af128a6.png)

**Comment by tongxin** [comment]
你好，请问paddle用的哪个版本？
