### ISSUE TITLE
静态图AMP O2策略load checkpoint有bug

### ISSUE THREAD

**Issue by sneaxiy** [PaddlePaddle/Paddle#39050]
为使您的问题得到快速解决，在建立Issues前，请您先通过如下方式搜索是否有相似问题:【搜索issue关键字】【使用labels筛选】【官方文档】

如果您没有查询到相似问题，为快速解决您的提问，建立issue时请提供如下细节信息：
- 标题：简洁、精准概括您的问题，例如“Insufficient Memory xxx" ”
- 版本、环境信息：
    1）PaddlePaddle版本：develop
    2）CPU：无
    3）GPU：无
    4）系统环境：无
 注：您可以通过执行[summary_env.py](https://github.com/PaddlePaddle/Paddle/blob/develop/tools/summary_env.py)获取以上信息。
- 训练信息
    1）单机/多机，单卡/多卡
    2）显存信息
    3）Operator信息
- 复现信息：无
- 问题描述：

在静态图AMP O2策略中，startup program里会插入一个`cast` op来把param转成FP32的master param。假如我现在有个checkpoint想加载到模型里，无论在`amp_init`前还是后load checkpoint，都会有bug：

- 如果`amp_init`在load checkpoint之前：
```
exe.run(startup_program) # 此时，param和master param都是FP32
load_checkpoint(...) # 此时，param会被覆盖成checkpoint的值。但master param没改，跟param不同步
optimizer.amp_init() # 此时，param会被cast成FP16，master param和param的值不同步
```

- 如果`amp_init`在load checkpoint之后
```
exe.run(startup_program) # 此时，param和master param都是FP32
optimizer.amp_init() # 此时，param会被cast成FP16，master param和param的值是同步的
load_checkpoint(...) # 此时，param会被覆盖成checkpoint的值。但master param没改，跟param不同步
```

由此可见，无论load checkpoint放在什么位置，都是错的，无法正常加载checkpoint。

**Comment by zhiqiu** [comment]
paddle静态图AMP O2训练产生的checkpoint，目前已支持save master weight，可以使用如下方法：
```
loss = net()
optimizer = paddle.static.amp.decorate(opt)
optimizer.minimize(loss)
exe.run(start_program)
optimizer.amp_init()
for i in range(10):
    exe.run(main_program)
paddle.save(main_program.state_dict())
state_dict_load = paddle.load(path)
main_program.set_state_dict(state_dict_load)
```
动态图目前尚未支持save master weight，已有计划支持。https://github.com/PaddlePaddle/Paddle/pull/39121
