### ISSUE TITLE
PaddleClas export model -> deploy

### ISSUE THREAD

**Issue by syyxtl** [PaddlePaddle/Paddle#39107]
<img width="919" alt="image" src="https://user-images.githubusercontent.com/66545456/150477865-8e476a16-87ee-4a8f-b09f-65f887921ad9.png">
直接下载paddleClas预训练模型，看导出的模型有很多broadcast，然后直接运行deploy报错

**Comment by jim19930609** [comment]
您好，请问能否提供较小的可以复现问题的代码，以及复现的操作方法，方便同事进行排查？感谢！
