### ISSUE TITLE
[Feature] request for deformable_conv+batch_norm fuse for cpu inference

### ISSUE THREAD

**Issue by sfraczek** [PaddlePaddle/Paddle#39125]
Hi,
For forward inference PaddlePaddle has conv+batch_norm fuse.
**Could you add deformable_conv+batch_norm fuse?**
I saw deformable_convolution->batch_norm in ppyolov2_resnet50_vd_dcn.

**Comment by jim19930609** [comment]
Reported this feature request to the developers in charge. Implementations expected in future Paddle releases.
