### ISSUE TITLE
dist_hapi_mnist_static fails with newest develop

### ISSUE THREAD

**Issue by arlesniak** [PaddlePaddle/Paddle#39133]
为使您的问题得到快速解决，在建立Issues前，请您先通过如下方式搜索是否有相似问题:【搜索issue关键字】【使用labels筛选】【官方文档】

如果您没有查询到相似问题，为快速解决您的提问，建立issue时请提供如下细节信息：
- 标题：简洁、精准概括您的问题
- 版本、环境信息：
    1）PaddlePaddle版本：请提供您的PaddlePaddle版本号，例如1.1或CommitID
    2）CPU/GPU：如果您使用GPU训练，请提供GPU驱动版本、CUDA和cuDNN版本号
    3）系统环境：请您描述系统类型、版本，例如Mac OS 10.14
    4）Python版本号
    5）显存信息
 注：您可以通过执行[summary_env.py](https://github.com/PaddlePaddle/Paddle/blob/develop/tools/summary_env.py)获取以上信息。
- 复现信息：如为报错，请给出复现环境、复现步骤
- 问题描述：请详细描述您的问题，同步贴出报错信息、日志/代码关键片段

Thank you for contributing to PaddlePaddle.
Before submitting the issue, you could search issue in the github in case that there was a similar issue submitted or resolved before.
If there is no solution,please provide us with the following details :
**System information**
-PaddlePaddle version （eg.1.1）or CommitID 814e5ab4e837a1c1270f67c6ca491da68b281a11 (Date:   Fri Jan 21 16:36:50 2022 +0800)
-CPU: including CPUMKL/OpenBlas/MKLDNN version
-GPU: including CUDA/cuDNN version None
-OS Platform and Distribution(eg.Mac OS 10.14)  Ubuntu 18.04
-Python version 3.6.13
Note: You can get most of the information by running [summary_env.py](https://github.com/PaddlePaddle/Paddle/blob/develop/tools/summary_env.py). 
**To Reproduce**
Steps to reproduce the behavior
`cd build`
`cmake -DPY_VERSION=3.6 -DCMAKE_BUILD_TYPE=Release -DWITH_TESTING=OFF -DWITH_INFERENCE_API_TEST=ON -DWITH_PYTHON=ON -DWITH_MKL=ON -DWITH_GPU=OFF -DON_INFER=ON ..`
`make`
`python ../../Paddle/python/paddle/tests/dist_hapi_mnist_static.py`
**Describe your current behavior**
ValueError: Operator "scale" has not been registered.
**Code to reproduce the issue**
**Other info / logs**
running the test dist_hapi_mnist_static.py fails with the error:
`ValueError: Operator "scale" has not been registered.`

**Comment by zhangbo9674** [comment]
Hello, please follow the following prompts to check whether the paddle is successfully installed：
```
import paddle
paddle.utils.run_check()
```
If the installation is successful, the following prompt will appear：
`PaddlePaddle is installed successfully! Let's start deep learning with PaddlePaddle now.`

**Comment by arlesniak** [comment]
Hi, the run_check() is successful, however I'm compiling Paddle from source and run specific tests i.e. `dist_hapi_mnist_static.py` , I did it a couple of days before and it was working, now it does not.

**Comment by Aganlengzi** [comment]
@arlesniak hi, I cannot reproduce it with both CommitID 814e5ab4e83 and the newest develop branch CommitID 0fee00442a on my environment, would you please check this with newest commit in develop branch?

**Comment by arlesniak** [comment]
The issue is not present in my workloads in current develop, so I'm closing it. Thank you.
