### ISSUE TITLE
CosineAnnealingDecayWarmRestart API 缺失

### ISSUE THREAD

**Issue by zhijiejia** [PaddlePaddle/Paddle#39139]
PaddlePaddle 的 余弦退火API中没有T_mul 参数，没法像Pytorch的CosineAnnealingDecayWarmRestart API那样？ 有计划加吗？？？
![image](https://user-images.githubusercontent.com/43838913/150630357-90e73d41-9cf5-4491-b17f-430fa574d163.png)

**Comment by zhangbo9674** [comment]
您好，您的反馈的问题对产品非常有价值，我们内部会安排评估，并尽快给您回复，感谢！

**Comment by zhangbo9674** [comment]
您好，感谢您的反馈，目前Paddle尚未支持CosineAnnealingDecayWarmRestart，辛苦您在如下链接中填写您的需求，我们会尽快排期支持：https://docs.qq.com/sheet/DWnhZS3N1WUhMUW5Z?tab=BB08J2

**Comment by Ligoml** [comment]
你好，该api已在开发计划中，敬请关注
