### ISSUE TITLE
paddle::framework::Tensor need a method to calculate elements count 

### ISSUE THREAD

**Issue by wanghaoshuang** [PaddlePaddle/Paddle#3914]
[paddle::framework::Tensor](https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/framework/tensor.h#L38) need a method to calculate elements count like [blob::count()](https://github.com/BVLC/caffe/blob/master/include/caffe/blob.hpp#L85) in caffe.

**Comment by zchen0211** [comment]
I strongly support Haoshuang's

**Comment by Canpio** [comment]
Why not use `product()` ?
