### ISSUE TITLE
paddle实现交叉验证

### ISSUE THREAD

**Issue by liddalidd** [PaddlePaddle/Paddle#39147]
您好，请问如何使用paddle实现交叉验证呢？我在文档里好像没有找到对应的API

**Comment by zhangbo9674** [comment]
您好，这里指的是如何实现用于交叉验证的数据集还是模型层面如何实现交叉验证？如果是数据集，目前应该是还为提供对应API，您可以在如下链接中填写您所需API的需求信息：https://docs.qq.com/sheet/DWnhZS3N1WUhMUW5Z
