### ISSUE TITLE
Paddle 运行卡死

### ISSUE THREAD

**Issue by zhuangh7** [PaddlePaddle/Paddle#39154]
机器学习萌新，
照着这个在学习 https://www.paddlepaddle.org.cn/tutorials/projectdetail/2223654

系统 windows10， gpu 3060ti
在本地安装了paddle 2.2 cuda 10.2 cudnn 7.6之后
运行样例代码。
发现程序在
```python
        self.fc = Linear(in_features=13, out_features=1)
```
这行卡死
,观察任务管理器，发现python占用30%左右cpu，但未调用gpu。
然后跑python的terminal毫无反应。

求解。

By the way，作为一个机器学习的萌新，想靠着国产paddle 学习机器学习（主要发现paddle提供了丰富的教程），
但是在过程中遇到了非常多的困难，资料放置不合理，ui不合理，等等。
希望Paddle越做越好吧

**Comment by zhuangh7** [comment]
![image](https://user-images.githubusercontent.com/16149477/150686643-b66ecea8-74f5-46be-ba6c-38c03f5df8ec.png)
运行安装验证程序paddle.utils.run_check()
卡在这里。

**Comment by AnnaTrainingG** [comment]
你好非常感谢您的反馈，后续会不断进行优化的，感谢您对paddle的支持。关于您提供的该问题可以通过升级cuda版本解决：更新一下，换到conda install paddlepaddle-gpu==2.2.1 cudatoolkit=11.2 -c https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/Paddle/ -c conda-forge此指令，可以通过自测。（原因是30系列的显卡不支持CUDA10了）

**Comment by zhuangh7** [comment]
> 

感谢，但是我查了3060ti好像不是安倍架构。跟着安装指南将cuda退回到了10.2，没想到居然不行啊。

**Comment by AnnaTrainingG** [comment]
非常感谢您的反馈，后续我们会不断更新安装指南的。
