### ISSUE TITLE
新手问题，如何设置可编译出自动适应avx的python包呢？像2.0.0版本那样

### ISSUE THREAD

**Issue by Gmgge** [PaddlePaddle/Paddle#39161]
你好，请问下，如何设置可以从源码编译出像2.0.0版本一样可以自动切换是否支持avx的python版本呢，想使用更新的版本，但是存在缺失avx指令集的机器。

**Comment by Gmgge** [comment]
如何同时生成paddle/fluid/core_noavx.so与paddle/fluid/core_avx.so呢？

**Comment by xingfeng01** [comment]
WITH_AVX 环境变量用来控制是否使用 AVX
https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/install/Tables.html#Compile

**Comment by Gmgge** [comment]
是否可以编译两次，通过开启与关闭获取两个paddle/fluid/core_noavx.so与paddle/fluid/core_avx.so，然后放在一个安装后的包中，达到2.0.0一样的效果？

**Comment by pangyoki** [comment]
你好，可以参考这个脚本：https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/scripts/paddle_build.sh
其中`combine_avx_noavx`脚本是把avx和noavx包合并到一起编包的。

**Comment by Gmgge** [comment]
@pangyoki  好的，非常感谢

**Comment by yangy996** [comment]
> @pangyoki 好的，非常感谢

你好，请问这个脚本combine_avx_noavx在哪呢？没有找到
