### ISSUE TITLE
output_tensor.copy_to_cpu()  ValueError: (InvalidArgument) The Variable type must be N6paddle9framework9LoDTensorE, but the type it holds is St6vectorIN6paddle9framework9LoDTensorESaIS2_EE.

### ISSUE THREAD

**Issue by XYZ-916** [PaddlePaddle/Paddle#39195]
Paddle版本2.2.1
利用静态图模型进行推理的时候，在output_tensor.copy_to_cpu()时出现了错误：
ValueError: (InvalidArgument) The Variable type must be N6paddle9framework9LoDTensorE, but the type it holds is St6vectorIN6paddle9framework9LoDTensorESaIS2_EE.
  [Hint: Expected holder_->Type() == VarTypeTrait<T>::kId, but received holder_->Type():13 != VarTypeTrait<T>::kId:7.] (at /paddle/paddle/fluid/framework/variable.h:54)

请问有什么解决思路吗？

谢谢～

**Comment by ronny1996** [comment]
请问是使用的paddle inference吗？

**Comment by XYZ-916** [comment]
> 请问是使用的paddle inference吗？

是的。之前是可以的，后来不行了。我不清楚我的什么改动引起了这个错误。

**Comment by KyleWang-Hunter** [comment]
> > 请问是使用的paddle inference吗？
> 
> 是的。之前是可以的，后来不行了。我不清楚我的什么改动引起了这个错误。

请求接口的参数错误
