### ISSUE TITLE
遍历 paddle.nn.Sequential()时候有bug

### ISSUE THREAD

**Issue by anliyuan** [PaddlePaddle/Paddle#39220]
import paddle
layers = paddle.nn.Sequential()
for i in range(10):
    layers.add_sublayer('block'+str(i), paddle.nn.Linear(10, 10))
for layer in layers:
    print(layer)

这里会报一个KeyError，但是如果add_sublayer时候不写'block'就不会报错。bug

**Comment by ronny1996** [comment]
您好，验证确实存在这个问题，正在进行反馈，如果需要遍历的话，可以先不加'block'
