### ISSUE TITLE
怎么创建一个xpu的tensor?

### ISSUE THREAD

**Issue by jacobunderlinebenseal** [PaddlePaddle/Paddle#39325]
使用to_tensor创建，place只能是cpuplace和cudaplace，xpuplace就抱错。
paddlepaddle 2.1.1
python3.7.10
使用的kunlun的卡

**Comment by thisjiang** [comment]
您好！XPU是有专属Place的：`paddle.device.XPUPlace`， 参考https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/device/XPUPlace_cn.html#xpuplace

**Comment by thisjiang** [comment]
您可以使用`pd.to_tensor(x, dtype='float32', place=pd.device.XPUPlace(0))`来创建新tensor

**Comment by jacobunderlinebenseal** [comment]
> 您可以使用`pd.to_tensor(x, dtype='float32', place=pd.device.XPUPlace(0))`来创建新tensor

您好，这样会报错，提示place只能是cpuplace和cudaplace或cudpinnedplace

**Comment by thisjiang** [comment]
那请问您是否有安装XPU版本的Paddle呢？如若没有，您可以尝试通过` pip install paddlepaddle-xpu`命令来进行安装，或参考如下教程：https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/guides/09_hardware_support/xpu_docs/paddle_install_cn.html
