### ISSUE TITLE
No allocator found for the place, CUDAPlace(0)

### ISSUE THREAD

**Issue by Akhilesh64** [PaddlePaddle/Paddle#39345]
Hi, I am trying to perform text detection using the DB model present in the paddleOCR repo as shown [here](https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.4/doc/doc_en/inference_ppocr_en.md#text-detection-model-inference). The inference runs fine locally but when i try to run it as a service in a docker container it throws the traceback shown in the image below. I am using the predict_det.py script provided [here](https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.4/tools/infer/predict_det.py) for the inference.
Following are the specifications of the container:
PaddlePaddle v2.2.2 (CPU)
OS : Debian (Linux)
Python : 3.8
CPU : Intel Xeon
GPU : None
![Capture](https://user-images.githubusercontent.com/36566307/152210784-588ca148-d5d8-4ce7-92c2-d56192d2e9bf.PNG)

A quick reply would be appreciated.

**Comment by ceci3** [comment]
you install paddlepaddle with cpu version，but use gpu to predict

**Comment by Akhilesh64** [comment]
@ceci3  I am using use_gpu=False argument in the script. Can you tell me what to do.

**Comment by Akhilesh64** [comment]
I had to build the library from source on python3.7 to make this work. There seems to be some problem with the CPU version of the current release as I wasn't able to run any paddle module on an AWS EC2 instance(c5) container. For anyone in the future with this problem build the library from source by following [this](https://www.paddlepaddle.org.cn/documentation/docs/en/1.6/beginners_guide/install/compile/compile_Ubuntu_en.html) article. make sure you follow all the steps. The arguments I used with cmake are as follows : 
`cmake .. -DPY_VERSION=3.7 -DWITH_GPU=OFF -DWITH_TESTING=OFF -DCMAKE_BUILD_TYPE=Release -DWITH_DSO=OFF  -DWITH_MKL=OFF DWITH_AVX=OFF`
