### ISSUE TITLE
LSTM运行报错

### ISSUE THREAD

**Issue by xu-peng-7** [PaddlePaddle/Paddle#39348]
AISTUDIO32G 至尊版在线环境
paddle2.2

运行rnn时，第二个iter报错

rnn = paddle.nn.LSTM(input_size=embedding_dim,
                                hidden_size=hidden_size,
                                num_layers=num_layers)

OSError: (External) CUDNN error(3), CUDNN_STATUS_BAD_PARAM. 
  [Hint: 'CUDNN_STATUS_BAD_PARAM'.  An incorrect value or parameter was passed to the function. To correct, ensure that all the parameters being passed have valid values.  ] (at /paddle/paddle/fluid/platform/cudnn_helper.h:293)
  [operator < rnn > error]

**Comment by LielinJiang** [comment]
能否公开一下可复现的ai studio项目链接？

**Comment by xu-peng-7** [comment]
项目“『IMAGE-CAPTION』基于CNN-RNN的医疗文本生成”共享链接(有效期三天)：https://aistudio.baidu.com/studio/project/partial/verify/3388563/ad5b1c0978eb4a54a1c6680deb5fa398

您一键运行就可以了

**Comment by xu-peng-7** [comment]
应该是数据的格式错误，但是不知道怎么定位是shape还是type错误，麻烦您帮忙看一下

**Comment by xu-peng-7** [comment]
定位到了：paddle.nn.LSTM使用的时候有个sequence_length参数，用于控制输入的有效数据长度，该参数必须小于输入数据长度。 在进行文本任务时，经常需要对数据进行截断，加上start和end后，会超出预设的长度。因此要特别关注这个参数的取值。
