### ISSUE TITLE
不支持多进程读取数据

### ISSUE THREAD

**Issue by graczhual** [PaddlePaddle/Paddle#39367]
- “自定义数据集，设置num_workers后警告不支持多进程”
- 版本、环境信息：
    1）PaddlePaddle版本：2.2.2
    2）芯片：M1
    3）系统环境：macOS 12.1，Python 3.9.4

- 问题描述：随意自定义数据集，定义dataloader时设置num_workers>0，运行警告且不起作用。是不支持该功能吗，但文档中没有任何地方提示了该功能暂时无法使用。
<img width="749" alt="image" src="https://user-images.githubusercontent.com/87636820/152751922-52a9f68b-6dc7-4bd3-a4c5-42cee8f6a9d7.png">

**Comment by danleifeng** [comment]
您好，目前多进程是只支持linux环境，暂不支持mac和windows。我们将会在文档中补充说明，非常感谢~

**Comment by graczhual** [comment]
> 您好，目前多进程是只支持linux环境，暂不支持mac和windows。我们将会在文档中补充说明，非常感谢~

好的，感谢回复
