### ISSUE TITLE
ImageNet的分类模型，剪枝后的re-train相关问题.

### ISSUE THREAD

**Issue by Water2style** [PaddlePaddle/Paddle#39373]
分类模型剪枝后，需要re-train.
我是准备做基于ImageNet数据集的剪枝后评估,我想问一下, 是否需要在140GB版本的完整训练集上re-train?

自己有一个小的ImageNet-train数据集,就100张图片，re-train很快能恢复acc.（基于PaddleClas的预训练模型）
但是使用大一些的ImageNet-train数据集(1000类，每类100个图) , loss就降低得很慢，acc很低很低.
并且存在一个问题，剪枝后，eval一下，acc1还有一些数，大概30%，到了re-train，这acc1直接降低到1%，然后更小....这为什么会直接降低到1%....

所以想问一下，是否需要在140GB版本的完整训练集上re-train? 或者开发人员是否有相关的建议呢~谢谢！

**Comment by wanghaoshuang** [comment]
>并且存在一个问题，剪枝后，eval一下，acc1还有一些数，大概30%，

剪枝是优先剪掉l1norm比较小的通道，所以能保留部分精度(acc)；

>到了re-train，这acc1直接降低到1%，然后更小....这为什么会直接降低到1%....

应该是初始学习率比较大，相当于重新初始化了剪枝后的模型权重；这种情况下，剪枝所起的作用本质上是“模型结构搜索”。
可以降低re-train的初始学习率，观察下精度(acc)损失情况。

>是否需要在140GB版本的完整训练集上re-train?

需要在完整的训练集上re-train.

另外，也可以尝试用蒸馏方法提升剪枝之后的模型acc。

**Comment by Water2style** [comment]
> > 并且存在一个问题，剪枝后，eval一下，acc1还有一些数，大概30%，
> 
> 剪枝是优先剪掉l1norm比较小的通道，所以能保留部分精度(acc)；
> 
> > 到了re-train，这acc1直接降低到1%，然后更小....这为什么会直接降低到1%....
> 
> 应该是初始学习率比较大，相当于重新初始化了剪枝后的模型权重；这种情况下，剪枝所起的作用本质上是“模型结构搜索”。 可以降低re-train的初始学习率，观察下精度(acc)损失情况。
> 
> > 是否需要在140GB版本的完整训练集上re-train?
> 
> 需要在完整的训练集上re-train.
> 
> 另外，也可以尝试用蒸馏方法提升剪枝之后的模型acc。

谢谢haoshuang大佬!  
我们准备对多个模型剪枝，多个剪枝比例...然后多个re-train, 现在看起来，在imagenet上的话，可能花的时间有点多了 2333333
