### ISSUE TITLE
如何使用CPU多線程進行預測

### ISSUE THREAD

**Issue by NatLee** [PaddlePaddle/Paddle#39398]
Paddle 官方您好

我使用ERNIE模型在CPU上對中文情緒進行預測，發現預測只用了單線程

想請問Paddle是否能夠使用多線程預測？

像是Tensorflow的CPU版本可以透過Config來設定使用的線程數量，Paddle是否也有類似的設定？

謝謝！

```
Python version: 3.8.5
Package:        paddlenlp==2.2.3
                paddlepaddle==2.2.1
```

**Comment by 154912369** [comment]
感觉你应该写清楚paddle版本，预测的语言等等信息。

**Comment by NatLee** [comment]
> 感觉你应该写清楚paddle版本，预测的语言等等信息。

感謝，我已補上！

**Comment by baoachun** [comment]
@NatLee 您好
您可以参考该C++多线程例子进行改写：https://github.com/PaddlePaddle/Paddle-Inference-Demo/blob/master/c%2B%2B/test/shrink_memory/multi_thread_test.cc 。

Python接口的具体用法可参考：https://paddleinference.paddlepaddle.org.cn/api_reference/python_api_doc/Predictor.html 或 https://paddleinference.paddlepaddle.org.cn/api_reference/python_api_doc/PredictorPool.html 。
