### ISSUE TITLE
paddlepaddle使用pip安装没有报错  但是也没正常安装

### ISSUE THREAD

**Issue by Hi-mawari** [PaddlePaddle/Paddle#39399]
$ python -m pip install --no-index --find-links=/opt/paddle/ paddlepaddle
Looking in links: /opt/paddle/
Processing ./paddlepaddle-2.2.2-cp36-cp36m-manylinux1_x86_64.whl
Processing ./decorator-5.1.0-py3-none-any.whl
Processing ./Pillow-8.2.0-cp36-cp36m-manylinux1_x86_64.whl
Processing ./astor-0.8.1-py2.py3-none-any.whl
Processing ./requests-2.24.0-py2.py3-none-any.whl
Processing ./six-1.16.0-py2.py3-none-any.whl
Processing ./protobuf-3.19.1-py2.py3-none-any.whl
Processing ./numpy-1.19.5-cp36-cp36m-manylinux2010_x86_64.whl
Processing ./certifi-2021.10.8-py2.py3-none-any.whl
Processing ./idna-2.10-py2.py3-none-any.whl
Processing ./chardet-3.0.4-py2.py3-none-any.whl
Processing ./urllib3-1.25.11-py2.py3-none-any.whl
Installing collected packages: urllib3, idna, chardet, certifi, six, requests, protobuf, Pillow, numpy, decorator, astor, paddlepaddle
Successfully installed Pillow-8.2.0 astor-0.8.1 certifi-2021.10.8 chardet-3.0.4 decorator-5.1.0 idna-2.10 numpy-1.19.5 paddlepaddle-2.2.2 protobuf-3.19.1 requests-2.24.0 six-1.16.0 urllib3-1.25.11

上面打印的包已经通过下载的方式保存在本地文件夹中了  使用离线安装，一般来说包之间的依赖有问题的话也会报错，但是现在的情况是不报错也不正常安装了  实在无法找到相似的例子去解决遇到的问题。能否解答一下

**Comment by ForFishes** [comment]
您好，请问这个不正常安装是指什么想象？直接安装报了什么错误？

**Comment by Hi-mawari** [comment]
> 您好，请问这个不正常安装是指什么想象？直接安装报了什么错误？

无报错。pip安装命令输入以后第一个打印不应该是collecting paddlepaddle嘛?我是Looking in links:/opt/paddle/。而且打印结束以后应该有个successfully installed paddlepaddle-版本号输出，我也没有。我输入打印命令以及接下来控制台日志都在上面。
包括最后去python执行import也是不行。

**Comment by Hi-mawari** [comment]
> 
已解决  非常感谢

**Comment by Hi-mawari** [comment]
> 

另外有个问题希望能回答一下，非常感谢
在我本地下载好模型后 hub命令有离线安装的功能吗？

**Comment by ForFishes** [comment]
您好，请问说的是paddlehub吗？如果是paddlehub的问题，麻烦移步到paddlehub的repo下提issue，thx。

**Comment by Hi-mawari** [comment]
> 您好，请问说的是paddlehub吗？如果是paddlehub的问题，麻烦移步到paddlehub的repo下提issue，thx。

确实   那这串就关闭了   感谢
