### ISSUE TITLE
Mac下载成功 导入失败

### ISSUE THREAD

**Issue by 0xC4FED6C7CCCE** [PaddlePaddle/Paddle#39407]
- 版本、环境信息：
    1）PaddlePaddle版本: 2.2
    4）系统环境：Mac OS 10.15.7、Python3.8

- 安装方式信息：
1）pip安装           
- 复现信息：
![截屏2022-02-08 下午11 19 07](https://user-images.githubusercontent.com/49481572/153017603-09b0b161-a1ae-4dc6-8795-866e177783e9.png)

- 问题描述：

**Comment by pangyoki** [comment]
你好，麻烦加上sudo权限安装试一下
