### ISSUE TITLE
有关模型参数加载和设置的API

### ISSUE THREAD

**Issue by lnc007lnc** [PaddlePaddle/Paddle#39410]
我尝试对于模型存储参数文件进行压缩优化时候遇到了一些问题。
1. 如果我同时加载.pdmodel和.pdiparam文件，对于得到的program进行set_program_state()是可以成功设置的。但是如果我对只加载.pdmodel文件得到的program进行相同的set_program_state()时却无法设置成功，提示scope找不到对应名称的变量。
所以是我的api用错了吗？如果我想只载入一个空的模型框架program，然后手动设置该program的每层参数我该怎么办？用什么API？

2. 另一个问题是如果当我只加载一个.pdmodel获得program时，我怎样通过layer名称找到里面的信息？
例如，如果我直接print program时，我可以看到如下信息：
...
persist var conv3_weights : LOD_TENSOR.shape(384, 192, 3, 3).dtype(float32).stop_gradient(False)
persist var conv1_offset : LOD_TENSOR.shape(64,).dtype(float32).stop_gradient(False)
var conv2d_8.tmp_0.dequantized : LOD_TENSOR.shape(-1, 256, 13, 13).dtype(float32).stop_gradient(False)
persist var conv2_weights : LOD_TENSOR.shape(192, 64, 5, 5).dtype(float32).stop_gradient(False)
...

那么当我想知道‘conv3_weights’ 的信息时该怎么做？比如‘conv3_weights’ 的shape是(384, 192, 3, 3)。

**Comment by yaoxuefeng6** [comment]
你好，根据API的设计，set_program_state需要加载完整的program 包括网络描述(.pdmodel)和模型参数(.pdparams)文件，目前不支持仅加载.pdmodel文件后配置参数。 可以参考这个文档：https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/static/Program_cn.html#program 来获取program内参数等操作

**Comment by lnc007lnc** [comment]
但是如果我想仅加载.pdmodel文件后配置参数，有这样的api吗？

**Comment by yaoxuefeng6** [comment]
暂时没有

**Comment by lnc007lnc** [comment]
那我如果想自己开发的话，大概提前需要设置哪些东西？

我看源码似乎是因为单独加载.pdmodel文件没有给scope赋值，导致scope中没有对应的layer名称的变量，所以设置失败。或许我可以先生成对应名称的变量加载到scope中，然后set_program_state？

**Comment by YuanRisheng** [comment]
您好，可以使用set_state_dict来给一个Program赋值参数，可参考：https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/static/Program_cn.html#set-state-dict-state-dict-scope-none
