### ISSUE TITLE
path_prefix参数不允许加最后一个/

### ISSUE THREAD

**Issue by wang-kangkang** [PaddlePaddle/Paddle#39412]
https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/static/io.py#L74   这个设定好鸡肋啊，既然是路径前缀，加不加最后一个/有什么区别呢。
def _normalize_path_prefix(path_prefix):
    """
    convert path_prefix to absolute path.
    """
    if not isinstance(path_prefix, six.string_types):
        raise ValueError("'path_prefix' should be a string.")
    if path_prefix.endswith("/"):
        raise ValueError("'path_prefix' should not be a directory")
    path_prefix = os.path.normpath(path_prefix)
    path_prefix = os.path.abspath(path_prefix)
    return path_prefix

**Comment by yaoxuefeng6** [comment]
多谢反馈。
