### ISSUE TITLE
test_eigh_op, test_eigvalsh_op tolerance

### ISSUE THREAD

**Issue by zlsh80826** [PaddlePaddle/Paddle#39446]
- 标题：test_eigh_op, test_eigvalsh_op 單測問題 
- 版本、环境信息：
    1）PaddlePaddle版本：develop
    2）CPU/GPU：GPU, CUDA 11.6
    3）系统环境：Ubuntu20.04
    4）Python版本号: python3.8
- 复现信息:
```
ctest -R test_eigh_op
ctest -R test_eigvalsh_op
```
- 问题描述：请详细描述您的问题，同步贴出报错信息、日志/代码关键片段
1. 在 CUDA 11.6 後 cusolver 改進了 Ssyevd 的性能, 但同時和 numpy 的差異會略微放大 [test_eigh_op](https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/fluid/tests/unittests/test_eigh_op.py#L85-L86), [test_eigvalsh_op](https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/fluid/tests/unittests/test_eigvalsh_op.py#L81-L82) tolerance 需要修改至 2e-6 之上
2. Complex 單測需求 Hermitian matrix (對角元素 imag 的部分需要為 0), [參考文件](https://docs.nvidia.com/cuda/cusolver/index.html), [test_eigh_op]( https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/fluid/tests/unittests/test_eigh_op.py#L91-92), [test_eigvalsh_op](https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/fluid/tests/unittests/test_eigvalsh_op.py#L87-L88)

**Comment by Zjq9409** [comment]
正在修改复数随机数生成方式

**Comment by Zjq9409** [comment]
eigh 算子修改PR链接为：https://github.com/PaddlePaddle/Paddle/pull/39568

**Comment by zlsh80826** [comment]
Thank @Zjq9409. I am running the unit test on our environment to ensure the PR works well. 
Hi @huangjun12, `test_eigvalsh_op` has same the issue with `test_eigh_op`. Could you help to update the `test_eigval_sh_op.py`? Thanks

**Comment by zlsh80826** [comment]
@Zjq9409 I have tested https://github.com/PaddlePaddle/Paddle/pull/39568, but it seems I had wrong conclusion in the past. The tolerance needs to be more higher. Following is the error message in our environment.
I investaged the reason and found that 2e-6 is for [5, 5] [input](https://github.com/PaddlePaddle/Paddle/blob/4a9a243a0341425d387ee5ba1bec8aeafd10c579/python/paddle/fluid/tests/unittests/test_eigh_op.py#L99)(the case I investigated before). The [32, 32] [input](https://github.com/PaddlePaddle/Paddle/blob/4a9a243a0341425d387ee5ba1bec8aeafd10c579/python/paddle/fluid/tests/unittests/test_eigh_op.py#L58) needs a higher tolerance (atol=6e-5, rtol=5e-6)


```
test_eigh_op failed
 .......F....
======================================================================
FAIL: test_check_output_gpu (test_eigh_op.TestEighGPUCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/paddle/paddle/build/python/paddle/fluid/tests/unittests/test_eigh_op.py", line 75, in test_check_output_gpu
    np.testing.assert_allclose(
  File "/usr/local/lib/python3.8/dist-packages/numpy/testing/_private/utils.py", line 1530, in assert_allclose
    assert_array_compare(compare, actual, desired, err_msg=str(err_msg),
  File "/usr/local/lib/python3.8/dist-packages/numpy/testing/_private/utils.py", line 844, in assert_array_compare
    raise AssertionError(msg)
AssertionError: 
Not equal to tolerance rtol=2e-06, atol=2e-06

Mismatched elements: 10 / 32 (31.2%)
Max absolute difference: 5.054474e-05
Max relative difference: 4.041603e-06
 x: array([-2.78129 , -2.573316, -2.460475, -2.090341, -1.802978, -1.725366,
       -1.633694, -1.468698, -1.250094, -0.896905, -0.634157, -0.491122,
       -0.47392 , -0.3968  , -0.152721, -0.108726, -0.039511,  0.275858,...
 y: array([-2.781283, -2.573307, -2.460468, -2.090336, -1.802972, -1.72536 ,
       -1.633688, -1.468692, -1.250091, -0.896903, -0.634154, -0.49112 ,
       -0.473918, -0.396798, -0.15272 , -0.108726, -0.039511,  0.275857,...

----------------------------------------------------------------------
Ran 12 tests in 2.927s

FAILED (failures=1)
```

**Comment by Zjq9409** [comment]
> @Zjq9409 I have tested #39568, but it seems I had wrong conclusion in the past. The tolerance needs to be more higher. Following is the error message in our environment. I investaged the reason and found that 2e-6 is for [5, 5] [input](https://github.com/PaddlePaddle/Paddle/blob/4a9a243a0341425d387ee5ba1bec8aeafd10c579/python/paddle/fluid/tests/unittests/test_eigh_op.py#L99)(the case I investigated before). The [32, 32] [input](https://github.com/PaddlePaddle/Paddle/blob/4a9a243a0341425d387ee5ba1bec8aeafd10c579/python/paddle/fluid/tests/unittests/test_eigh_op.py#L58) needs a higher tolerance (atol=6e-5, rtol=5e-6)
> 
> ```
> test_eigh_op failed
>  .......F....
> ======================================================================
> FAIL: test_check_output_gpu (test_eigh_op.TestEighGPUCase)
> ----------------------------------------------------------------------
> Traceback (most recent call last):
>   File "/opt/paddle/paddle/build/python/paddle/fluid/tests/unittests/test_eigh_op.py", line 75, in test_check_output_gpu
>     np.testing.assert_allclose(
>   File "/usr/local/lib/python3.8/dist-packages/numpy/testing/_private/utils.py", line 1530, in assert_allclose
>     assert_array_compare(compare, actual, desired, err_msg=str(err_msg),
>   File "/usr/local/lib/python3.8/dist-packages/numpy/testing/_private/utils.py", line 844, in assert_array_compare
>     raise AssertionError(msg)
> AssertionError: 
> Not equal to tolerance rtol=2e-06, atol=2e-06
> 
> Mismatched elements: 10 / 32 (31.2%)
> Max absolute difference: 5.054474e-05
> Max relative difference: 4.041603e-06
>  x: array([-2.78129 , -2.573316, -2.460475, -2.090341, -1.802978, -1.725366,
>        -1.633694, -1.468698, -1.250094, -0.896905, -0.634157, -0.491122,
>        -0.47392 , -0.3968  , -0.152721, -0.108726, -0.039511,  0.275858,...
>  y: array([-2.781283, -2.573307, -2.460468, -2.090336, -1.802972, -1.72536 ,
>        -1.633688, -1.468692, -1.250091, -0.896903, -0.634154, -0.49112 ,
>        -0.473918, -0.396798, -0.15272 , -0.108726, -0.039511,  0.275857,...
> 
> ----------------------------------------------------------------------
> Ran 12 tests in 2.927s
> 
> FAILED (failures=1)
> ```

已经更新rtol和atol值

**Comment by huangjun12** [comment]
> Thank @Zjq9409. I am running the unit test on our environment to ensure the PR works well.
> Hi @huangjun12, `test_eigvalsh_op` has same the issue with `test_eigh_op`. Could you help to update the `test_eigval_sh_op.py`? Thanks

eigvalsh修复pr：https://github.com/PaddlePaddle/Paddle/pull/39841

**Comment by zlsh80826** [comment]
@huangjun12 
The atol needs to be `6e-5` and rtol needs to be `5e-6`. The reason is discussed at https://github.com/PaddlePaddle/Paddle/issues/39446#issuecomment-1043773985.
Reference: https://github.com/PaddlePaddle/Paddle/pull/39568

**Comment by huangjun12** [comment]
> @huangjun12
> The atol needs to be `6e-5` and rtol needs to be `5e-6`. The reason is discussed at [#39446 (comment)](https://github.com/PaddlePaddle/Paddle/issues/39446#issuecomment-1043773985).
> Reference: #39568

Done

**Comment by zlsh80826** [comment]
https://github.com/PaddlePaddle/Paddle/pull/40699

**Comment by zlsh80826** [comment]
This issue is blocked by https://github.com/PaddlePaddle/Paddle/pull/40699

**Comment by zlsh80826** [comment]
#40699 merged. Close this issue
