### ISSUE TITLE
 Check failed: offset >= 0 (-1 vs. 0) 

### ISSUE THREAD

**Issue by zhangyong15** [PaddlePaddle/Paddle#3945]
Pserver报错，MPI任务，之前的任务一直运行正常。
F0906 22:43:48.153187  5283 ParameterServer2.cpp:751] Check failed: offset >= 0 (-1 vs. 0) Only existing parameter block is allowed:  id=7 block id=9

**Comment by zhangyong15** [comment]
Wed Sep  6 22:43:40 2017[1,165]<stderr>:  File "./http_server.py", line 41, in <module>
Wed Sep  6 22:43:40 2017[1,165]<stderr>:    server = ThreadingSimpleServer(('', port), SimpleHTTPRequestHandler)
Wed Sep  6 22:43:40 2017[1,165]<stderr>:  File "/home/disk1/normandy/maybach/6200/workspace/python27-gcc482/lib/python2.7/SocketServer.py", line 420, in __init__
Wed Sep  6 22:43:40 2017[1,165]<stderr>:    self.server_bind()
Wed Sep  6 22:43:40 2017[1,165]<stderr>:  File "/home/disk1/normandy/maybach/6200/workspace/python27-gcc482/lib/python2.7/BaseHTTPServer.py", line 108, in server_bind
Wed Sep  6 22:43:40 2017[1,165]<stderr>:    SocketServer.TCPServer.server_bind(self)
Wed Sep  6 22:43:40 2017[1,165]<stderr>:  File "/home/disk1/normandy/maybach/6200/workspace/python27-gcc482/lib/python2.7/SocketServer.py", line 434, in server_bind
Wed Sep  6 22:43:40 2017[1,165]<stderr>:    self.socket.bind(self.server_address)
Wed Sep  6 22:43:40 2017[1,165]<stderr>:  File "/home/disk1/normandy/maybach/6200/workspace/python27-gcc482/lib/python2.7/socket.py", line 228, in meth
Wed Sep  6 22:43:40 2017[1,165]<stderr>:    return getattr(self._sock,name)(*args)
Wed Sep  6 22:43:40 2017[1,165]<stderr>:socket.error: [Errno 98] Address already in use
Wed Sep  6 22:43:40 2017[1,165]<stderr>:[INFO 2017-09-06 22:43:40,496 networks.py:1482] The input order is [ad_layer, user_layer, media_layer, label]
Wed Sep  6 22:43:40 2017[1,165]<stderr>:[INFO 2017-09-06 22:43:40,496 networks.py:1488] The output order is [__mse_cost_0__]
Wed Sep  6 22:43:48 2017[1,72]<stderr>:*** Aborted at 1504709028 (unix time) try "date -d @1504709028" if you are using GNU date ***
Wed Sep  6 22:43:48 2017[1,72]<stderr>:PC: @                0x0 (unknown)
Wed Sep  6 22:43:48 2017[1,72]<stderr>:*** SIGSEGV (@0x8) received by PID 36797 (TID 0x7f88361fc700) from PID 8; stack trace: ***
Wed Sep  6 22:43:48 2017[1,72]<stderr>:    @     0x7f8c45c0b160 (unknown)
Wed Sep  6 22:43:48 2017[1,72]<stderr>:    @           0x76b112 paddle::ProtoClient::recv()
Wed Sep  6 22:43:48 2017[1,72]<stderr>:    @           0xf0ad76 paddle::ParameterClient2::sendParallel()
Wed Sep  6 22:43:48 2017[1,72]<stderr>:    @           0x734534 _ZNSt6thread5_ImplISt12_Bind_simpleIFZN6paddle14SyncThreadPool5startEvEUliE_mEEE6_M_runEv
Wed Sep  6 22:43:48 2017[1,195]<stderr>:F0906 22:43:48.201270 35218 LightNetwork.cpp:397] Check failed: error >= 0 ERROR connecting to 10.87.118.42: Connection refused [111]
Wed Sep  6 22:43:48 2017[1,195]<stderr>:*** Check failure stack trace: ***
Wed Sep  6 22:43:48 2017[1,195]<stderr>:F0906 22:43:48.201272 35219 LightNetwork.cpp:397] Check failed: error >= 0 ERROR connecting to 10.87.118.42: Connection refused [111]
Wed Sep  6 22:43:48 2017[1,195]<stderr>:*** Check failure stack trace: ***
Wed Sep  6 22:43:48 2017[1,195]<stderr>:    @           0x91316d  google::LogMessage::Fail()
Wed Sep  6 22:43:48 2017[1,195]<stderr>:    @           0x91316d  google::LogMessage::Fail()
Wed Sep  6 22:43:48 2017[1,72]<stderr>:    @     0x7f8c457a48a0 execute_native_thread_routine
Wed Sep  6 22:43:48 2017[1,195]<stderr>:    @           0x916c1c  google::LogMessage::SendToLog()
Wed Sep  6 22:43:48 2017[1,195]<stderr>:    @           0x916c1c  google::LogMessage::SendToLog()
Wed Sep  6 22:43:48 2017[1,195]<stderr>:    @           0x912c93  google::LogMessage::Flush()
Wed Sep  6 22:43:48 2017[1,195]<stderr>:    @           0x912c93  google::LogMessage::Flush()
Wed Sep  6 22:43:48 2017[1,72]<stderr>:    @     0x7f8c45c031c3 start_thread
Wed Sep  6 22:43:48 2017[1,195]<stderr>:    @           0x912e99  google::LogMessage::~LogMessage()
Wed Sep  6 22:43:48 2017[1,195]<stderr>:    @           0x912e99  google::LogMessage::~LogMessage()
Wed Sep  6 22:43:48 2017[1,195]<stderr>:    @           0x916147  google::ErrnoLogMessage::~ErrnoLogMessage()
Wed Sep  6 22:43:48 2017[1,195]<stderr>:    @           0x916147  google::ErrnoLogMessage::~ErrnoLogMessage()
Wed Sep  6 22:43:48 2017[1,72]<stderr>:    @     0x7f8c44f1512d __clone
Wed Sep  6 22:43:48 2017[1,195]<stderr>:    @           0x768fa1  paddle::SocketClient::TcpClient()
Wed Sep  6 22:43:48 2017[1,195]<stderr>:    @           0x768fa1  paddle::SocketClient::TcpClient()
Wed Sep  6 22:43:48 2017[1,195]<stderr>:    @           0x7691a1  paddle::SocketClient::SocketClient()
Wed Sep  6 22:43:48 2017[1,72]<stderr>:    @                0x0 (unknown)
Wed Sep  6 22:43:48 2017[1,195]<stderr>:    @           0xf06e50  paddle::ParameterClient2::init()
Wed Sep  6 22:43:48 2017[1,195]<stderr>:    @           0x76052d  paddle::RemoteParameterUpdater::init()
Wed Sep  6 22:43:48 2017[1,195]<stderr>:    @           0x7691a1  paddle::SocketClient::SocketClient()
Wed Sep  6 22:43:48 2017[1,195]<stderr>:    @           0x74ebd6  paddle::SyncThreadPool::execPlusOwner()
Wed Sep  6 22:43:48 2017[1,195]<stderr>:    @           0xf06e50  paddle::ParameterClient2::init()
Wed Sep  6 22:43:48 2017[1,195]<stderr>:    @           0x75ca3e  paddle::SparseRemoteParameterUpdaterComposite::init()
Wed Sep  6 22:43:48 2017[1,195]<stderr>:    @           0x75c619  paddle::SparseRemoteParameterUpdater::init()
Wed Sep  6 22:43:48 2017[1,195]<stderr>:    @           0x748a04  paddle::Trainer::init()
Wed Sep  6 22:43:48 2017[1,195]<stderr>:    @           0x734534  _ZNSt6thread5_ImplISt12_Bind_simpleIFZN6paddle14SyncThreadPool5startEvEUliE_mEEE6_M_runEv
Wed Sep  6 22:43:48 2017[1,195]<stderr>:    @           0x5a3cbc  main
Wed Sep  6 22:43:48 2017[1,195]<stderr>:    @     0x7f5fbe2f6bd5  __libc_start_main
Wed Sep  6 22:43:48 2017[1,195]<stderr>:    @     0x7f5fbec4b8a0  execute_native_thread_routine
Wed Sep  6 22:43:48 2017[1,195]<stderr>:    @     0x7f5fbf0aa1c3  start_thread
Wed Sep  6 22:43:48 2017[1,195]<stderr>:    @           0x5b2169  (unknown)
Wed Sep  6 22:43:48 2017[1,195]<stderr>:    @              (nil)  (unknown)
Wed Sep  6 22:43:48 2017[1,158]<stderr>:F0906 22:43:48.226722  3251 LightNetwork.cpp:397] Check failed: error >= 0 ERROR connecting to 10.87.118.42: Connection refused [111]
Wed Sep  6 22:43:48 2017[1,158]<stderr>:*** Check failure stack trace: ***

**Comment by zhangyong15** [comment]
还是端口冲突？为什么会报offset这个错误啊，第一次出现

**Comment by typhoonzero** [comment]
可能是两个paddle的job 跑在同一个节点上了？pserver收到了其他的trainer传入的数据。这个一般也是：

**Comment by typhoonzero** [comment]
先关闭了，此issue本质原因还是在集群调度问题上。
