### ISSUE TITLE
训练被中断

### ISSUE THREAD

**Issue by Zhangts98** [PaddlePaddle/Paddle#39451]
- 版本、环境信息：
    1）PaddlePaddle版本：1.8.5
    2）CPU：Intel(R) Xeon(R) CPU E5-2680 v4 @ 2.40GHz
    3）GPU：4 张 GTX-1080 ， cuda-10.0, cudnn 7.6.5
    4）系统环境：centos7, python3.7

- 训练信息
    1）多卡训练

- 问题描述：训练突然被中断了（非手动中断），下面是中断时出现的信息
![企业微信截图_16444776033969](https://user-images.githubusercontent.com/61573829/153358758-8ef5beda-d120-4011-ad5c-803d0dbf45cb.png)
我看上面的报错信息有关于date，因为这台机器每次开机时，时间都不准确，需要校准，所以我在开机时执行了 sudo ntpdate pool.ntp.org 来获取准确时间，之后开始的训练。
之前出现过这个错误，我是直接重启的，然后就没再出现这个错误了。
训练被中断后，我查看了显存使用情况和进程情况, 如下：
![企业微信截图_16444783505676](https://user-images.githubusercontent.com/61573829/153359041-993d0f9c-27c4-4478-9270-37660838a8c4.png)

![企业微信截图_1644478385431](https://user-images.githubusercontent.com/61573829/153359071-7d7ca546-ea0c-4728-8b36-c837c6458ede.png)

请问该如何解决？
感谢大佬。

**Comment by Zhangts98** [comment]
通过 执行 fuser -v /dev/nvidia* 可以看到确实有进程在占用显卡，
![企业微信截图_1644479373338](https://user-images.githubusercontent.com/61573829/153362131-085ffcec-2eec-4f22-b12e-5fef04bf6409.png)

通过 使用  kill -9 进程号 杀死这些进程后， 重新执行 nvidia-smi 和ps -aux | grep python,结果如下
![企业微信截图_1644479506373](https://user-images.githubusercontent.com/61573829/153362162-4bcd308e-671e-4d9d-a22a-08c36e413cac.png)
![image](https://user-images.githubusercontent.com/61573829/153362860-cb650240-79b3-4b67-8944-a101d9431006.png)

请问是gpu出现了什么问题么？比如过热之类的。

**Comment by sandyhouse** [comment]
从上述问题无法判断具体原因，中断后存在显存占用是因为存在残留进程，手动kill后可解决。另外，如果通过重启即可解决上面的程序中断问题的话，大概率是系统或者硬件原因。

**Comment by Zhangts98** [comment]
> 

好的， 感谢。
