### ISSUE TITLE
aistudio脚本任务4卡训练与单卡训练同样epoch，4卡的性能远低于单卡的问题

### ISSUE THREAD

**Issue by YellowLight021** [PaddlePaddle/Paddle#39456]
单机多卡训练问题。同样的代码在提交任务时候分别使用单卡、多卡进行训练，（4卡训练的时候学习率根据官方文档也乘以了4）。但是4卡训练的效果远低于单卡
![image](https://user-images.githubusercontent.com/45915150/153368004-3164d244-1a42-42f5-9341-6b091f034d16.png)
![image](https://user-images.githubusercontent.com/45915150/153368085-e36b533a-940c-4b8a-bf47-d6836131e11e.png)
如图，分布式训练效果反而没有单卡训练效果好了。这个是我公开的项目位置https://aistudio.baidu.com/aistudio/clusterprojectdetail/3467470

**Comment by sandyhouse** [comment]
具体配置什么样的，比如单卡batch size是多少，分布式运行时单卡batch size是多少？4卡是几台机器？需要判断下aistudio网络配置什么样子的，之前发现过当多台机器时，如果网络配置比较差，可能出现多卡性能不如单卡的情况。
