### ISSUE TITLE
如何获取模型中间某层的梯度

### ISSUE THREAD

**Issue by wzy-99** [PaddlePaddle/Paddle#39476]
请问反向传播时如何获取模型中间某一层的loss？

**Comment by wzy-99** [comment]
根据https://www.paddlepaddle.org.cn/documentation/docs/zh/guides/01_paddle2.0_introduction/basic_concept/autograd_cn.html 大致了解了
先调用loss.backward()
再获得tensor.grad

**Comment by iclementine** [comment]
torch 需要额外的 retain_grad() 
paddle 并不需要。
