### ISSUE TITLE
AttributeError: module 'paddle' has no attribute 'uint16'

### ISSUE THREAD

**Issue by tangzhiyi11** [PaddlePaddle/Paddle#39473]
为使您的问题得到快速解决，在建立Issues前，请您先通过如下方式搜索是否有相似问题:【搜索issue关键字】【使用labels筛选】【官方文档】

如果您没有查询到相似问题，为快速解决您的提问，建立issue时请提供如下细节信息：
- 标题：简洁、精准概括您的问题
- 版本、环境信息：
    1）PaddlePaddle版本：develop分支

paddle c++接口返回 ::paddle::platform::bfloat16 这种类型，但是在python测返回的是 paddle.uint16，而 paddle.uint16 这种类型又报不存在，请问这里的显示的类型的转换是在哪里做的呢？

<img width="814" alt="image" src="https://user-images.githubusercontent.com/5955111/153549472-2ed87f40-a6b4-4027-ac36-045e8bf632ec.png">

**Comment by iclementine** [comment]
python/paddle/fluid/dygraph/varbase_patch_methods.py
<img width="927" alt="图片" src="https://user-images.githubusercontent.com/16222986/153573207-adb13c51-7918-4189-b061-4ebdd32f3c5a.png">


里面有把 paddle::framework::proto::VarType::Type 打印出来的方法。里面把 bf16 对应到了 uint16. （至于这么做的原因是它一开始是用于和 Numpy 类型对应的，而 numpy 里没有 bfloat16）


而 paddle.float32 之类的是把 C++ 端的 paddle::framework::proto::VarType::FLOAT32 import 出来的 alias。参考 python/paddle/framework/dtype.py

**Comment by tangzhiyi11** [comment]
> python/paddle/fluid/dygraph/varbase_patch_methods.py <img alt="图片" width="927" src="https://user-images.githubusercontent.com/16222986/153573207-adb13c51-7918-4189-b061-4ebdd32f3c5a.png">
> 
> 里面有把 paddle::framework::proto::VarType::Type 打印出来的方法。里面把 bf16 对应到了 uint16. （至于这么做的原因是它一开始是用于和 Numpy 类型对应的，而 numpy 里没有 bfloat16）
> 
> 而 paddle.float32 之类的是把 C++ 端的 paddle::framework::proto::VarType::FLOAT32 import 出来的 alias。参考 python/paddle/framework/dtype.py

多谢~

**Comment by Aganlengzi** [comment]
@lidanqing-intel hi danqing, this issue is related to uint16 and bfloat16, will we re-import paddle-bfloat package to Paddle to support bfloat16?

**Comment by lidanqing-vv** [comment]
@Aganlengzi Last time the PR https://github.com/PaddlePaddle/Paddle/pull/38703 is merged but later reverted cause windows CI and mac CI failed etc. But later we do no steps to reproduce these errors on windows, hence don't know how to reproduct and fix. Could you please help modify the PR or, provide reproduction steps so that we can reproduce and fix?

**Comment by Aganlengzi** [comment]
@lidanqing-intel hi, danqing, It's not about the PR, it is about the package. Do you remember I have sent you a picture about how we suggested to fix? The package can be pre-built and uploaded, in this way, it is unnecessary to compile  the package in local environment and will not have errors.

**Comment by lidanqing-vv** [comment]
Hi, the package has been uploaded and PR merged. Now we will change in Paddle to use bfloat16

**Comment by jakpiase** [comment]
Just a quick update FYI:
A PR introducing proper BF16 support inside PaddlePaddle's pybind conversions between Python and C++ is currently being implemented by me in: #40323 which is dependent on #42865. It's goal is to stop using uint16 datatype as a placeholder for BF16 and start using a standalone BF16 datatype which is introduced in paddle_bfloat package, after all these changes PaddlePaddle will handle BF16 in a similar way that Tensorflow has handled it's BF16 datatype usage. If everything will go smoothly then all this work should be finished in the first half of June 2022.

**Comment by onecatcn** [comment]
Intel suggests to close the issue.
