### ISSUE TITLE
Whether the loss Op need to consider weights in the Op porting work?

### ISSUE THREAD

**Issue by qingqing01** [PaddlePaddle/Paddle#3947]
损失函数Op可以带权重，这个权重可以是Scalar(标量)、可以是Tensor，Paddle Layer API可带权重, 举例：

```python
@wrap_name_default()
@layer_support()
def cross_entropy(input,
                  label,
                  name=None,
                  coeff=1.0,  # 权重系数，作为属性
                  weight=None,  # 权重矩阵，作为输入
                  layer_attr=None):
# ...
```

   - coeff： 可作为Attr，当前在Paddle里只作用于backward，https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/gserver/layers/CostLayer.cpp#L78
   - weight: 作为Input, 作用于forward和backward

 ---
- 问题：

 1. 新移植的loss Op是否需要带权重？
 2. 可否不带，loss Op后再接scale Op 或 elementwise-mul Op?
 3. 后续兼容问题：在Python解决？
 4. 大家有没有其他建议？

**Comment by reyoung** [comment]
> 新移植的loss Op是否需要带权重？
不需要带

> 可否不带，loss Op后再接scale Op 或 elementwise-mul Op?
是

> 后续兼容问题：在Python解决？
是

**Comment by lcy-seso** [comment]
我觉得不带权重后续用点乘和scale实现可以接受。但是，作为一种在训练中常用的机制，希望Paddle自己能实现这个wrap，而不是留给用户来做。
