### ISSUE TITLE
torch.tensor.view用什么替换

### ISSUE THREAD

**Issue by ZiJINII** [PaddlePaddle/Paddle#39491]
![image](https://user-images.githubusercontent.com/92594026/153645080-928586e0-0d40-459f-b2c0-11c9e19de09b.png)
**### 在全连接层需要用到view函数，在paddle中找不到对应函数**###

**Comment by huangjun12** [comment]
可以使用 paddle.reshape，文档参考 https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/reshape_cn.html#reshape

**Comment by ZiJINII** [comment]
> 可以使用 paddle.reshape，文档参考 https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/reshape_cn.html#reshape

![image](https://user-images.githubusercontent.com/92594026/153833844-6c1fedb2-e00e-45d9-83d9-e1dc56c45d83.png)
出现了‘numpy.int64’ object is not callable 的错误，无法解决

**Comment by huangjun12** [comment]
能定位到具体报错在哪行嘛

**Comment by ZiJINII** [comment]
> 能定位到具体报错在哪行嘛
在最后的全连接层
 def forward(self, x):
        # ResConv
        x = x.numpy()
        x = x.astype("float32")
        x  =paddle.to_tensor(x)
        x = self.preprocessing(x)
        x = self.norm1(x)
        x = self.TLU(x)

        # Conv1 
        x = self.block2(x)

        # Conv2 
        x = self.block3(x)

        # Multiscale residual convolution block
        x = self.block_netB(x)

        # Conv3
        x = self.block4(x)
        # AvgPool1
        x = self.pool1(x)
        
        # Steganalysis residual block
        x = self.block5(x)
        # AvgPool2
        x = self.pool2(x)

        # Conv4
        x = self.block6(x)
        # AvgPool3
        x = self.pool3(x)

        # Conv5 
        x = self.block7(x)
        print(x.size)

        # Full Connection
        x = x.reshape(x,shape=[x.size(0), -1])
        x = self.ip1(x)
        return x

**Comment by ZiJINII** [comment]
问题已经解决了，发现是x.size的问题，感谢
