### ISSUE TITLE
安装失败

### ISSUE THREAD

**Issue by breakerqq** [PaddlePaddle/Paddle#39536]
PS D:\paddlepaddle> python --version
Python 3.10.0
PS D:\paddlepaddle> python -m ensurepip
Looking in links: c:\Users\CN0086~1\AppData\Local\Temp\tmpl74dylmk
Requirement already satisfied: setuptools in d:\programs\python\python310\lib\site-packages (57.4.0)
Requirement already satisfied: pip in d:\programs\python\python310\lib\site-packages (22.0.3)       
PS D:\paddlepaddle> python -m pip --version
pip 22.0.3 from D:\Programs\Python\Python310\lib\site-packages\pip (python 3.10)
PS D:\paddlepaddle> python -c "import platform;print(platform.architecture()[0]);print(platform.machine())"
>>
64bit
AMD64
PS D:\paddlepaddle> python -m pip install paddlepaddle-gpu==2.2.2 -i https://mirror.baidu.com/pypi/simple
Looking in indexes: https://mirror.baidu.com/pypi/simple
ERROR: Could not find a version that satisfies the requirement paddlepaddle-gpu==2.2.2 (from versions: none)
ERROR: No matching distribution found for paddlepaddle-gpu==2.2.2

**Comment by wangxicoding** [comment]
<img width="304" alt="image" src="https://user-images.githubusercontent.com/10208305/153854363-b7c55b7b-c293-4d4b-b4df-6459a99aad53.png">
https://www.paddlepaddle.org.cn/install/quick?docurl=/documentation/docs/zh/install/pip/linux-pip.html
抱歉paddle这边还不支持python3.10，您可以先切换一下python版本

**Comment by breakerqq** [comment]
> <img alt="image" width="304" src="https://user-images.githubusercontent.com/10208305/153854363-b7c55b7b-c293-4d4b-b4df-6459a99aad53.png">
> 
> https://www.paddlepaddle.org.cn/install/quick?docurl=/documentation/docs/zh/install/pip/linux-pip.html 抱歉paddle这边还不支持python3.10，您可以先切换一下python版本

好的，谢谢。

**Comment by liudonghua123** [comment]
@breakerqq @wangxicoding 那 python 3.10 支持什么时候可以完成呢，python 3.10 已经发布很长时间了，社区里面的很多库，例如 tensorflow pytorch 等都已经支持了

**Comment by sekauqnoom** [comment]
我的python是3.7版本的，一开始也这样，弄了好久都不行。刚刚关了vpn马上可以了！

**Comment by liudonghua123** [comment]
> 我的python是3.7版本的，一开始也这样，弄了好久都不行。刚刚关了vpn马上可以了！

可以参考一下我前段时间做的python3.10下安装使用的总结🙃

https://github.com/PaddlePaddle/Paddle/issues/40212#issuecomment-1061713823
