### ISSUE TITLE
编译mkl+noavx版本，在推理时开启mkldnn报错could not create a primitive

### ISSUE THREAD

**Issue by Gmgge** [PaddlePaddle/Paddle#39546]
- 版本、环境信息：
    1）PaddlePaddle版本：2.2.2
    2）CPU：Inter T7700
    3）GPU：无
    4）系统环境：centos7.8 
- 模型信息
    1）paddleOCR
- 复现信息：在编译的服务器上根据教程，设定-DWITH_AVX=OFF，编译出core_noavx，之后设定参数NOAVX_CORE_FILE，并-DWITH_AVX=ON，编译出whl包后，安装到无avx指令的英特尔cpu上，运行paddleOCR2.3
- 问题描述：关闭mkldnn时正常运行，开启mkl时报错could not create a primitive，

1.退回版本2.0.0时，则一切正常。
2.根据教程的参数编译出来的core_avx.so与pip中whl包中core_avx的依赖库不同，缺少对libz.so.1的依赖。
3.运行目标检测网络ppyolo正常。

想问下是否有cmake的参数未正常指定，我使用的是：
cmake .. -DPYTHON_EXECUTABLE:FILEPATH=[您可执行的Python3的路径] -DPYTHON_INCLUDE_DIR:PATH=[之前的PYTHON_INCLUDE_DIRS] -DPYTHON_LIBRARY:FILEPATH=[之前的PYTHON_LIBRARY] -DWITH_GPU=OFF -DWITH_TESTING=OFF -DCMAKE_BUILD_TYPE=Release -DWITH_AVX=OFF -DWITH_MKL=ON

**Comment by baoachun** [comment]
你好，请问描述中说的开启mkl和关闭mkl是怎么设置的呢？我看报错信息是mkldnn的报错呢，mkl是普通的矩阵加速库，mkldnn是ai加速库，对于矩阵加速库paddle支持mkl和openBLAS

**Comment by Gmgge** [comment]
你好，是描述出错，是开启mkldnn，paddleOCR中通过配置参数开启mklnn服务,具体说
[if args.enable_mkldnn:...](https://github.com/PaddlePaddle/PaddleOCR/blob/beb08cac2241300d280c0fdfdb14151317b7e5b2/tools/infer/utility.py#L286 )

**Comment by baoachun** [comment]
你好，请问关闭mkldnn是否能推理成功呢？如果CPU都无法跑通可能是配置问题，如果只是开启mkldnn报错，那麻烦提供下可复现的脚本、模型和复现步骤，感谢~~

**Comment by Gmgge** [comment]
关闭的话正常运行，打开mkldnn部分网络无法推理，例如paddleocr2.3。
复现环境
1 cenos7.8，官方编译教程，如上所示的cmake参数设置
2 关闭avx编译，打开avx编译并设置链接noavx
3 将编译后的whl安装包安装到没有avx的T7700机器上
4 下载paddleocr官方2.3版本，并安装所需依赖与模型文件
5 运行ocr，开启mkldnn，关闭mkldnn测试。

**Comment by baoachun** [comment]
你好，请问具体是哪个模型？执行的命令是什么？

**Comment by Gmgge** [comment]
你好，下载[字符检测模型](https://paddleocr.bj.bcebos.com/PP-OCRv2/chinese/ch_PP-OCRv2_det_infer.tar)，下载[字符识别模型](https://paddleocr.bj.bcebos.com/PP-OCRv2/chinese/ch_PP-OCRv2_rec_infer.tar)，下载[字符方向分类模型](https://paddleocr.bj.bcebos.com/dygraph_v2.0/ch/ch_ppocr_mobile_v2.0_cls_infer.tar)
进入paddleocr目录
使用脚本python tools/infer/predict_system.py --image_dir="图像文件夹路径" --det_model_dir="字符检测模型文件夹路径" --cls_model_dir="字符方向分类模型文件夹路径"  --rec_model_dir="字符识别模型文件夹路径" --use_angle_cls=true --use_gpu=False  --enable_mkldnn True

**Comment by baoachun** [comment]
你好，我使用develop分支和2.2分支的paddle没有复现该问题，能提供下执行日志吗？ 
`export GLOG_v=4`
然后保存打屏日志

**Comment by xinye01234** [comment]
我也是很幸福的碰到了，不知道如何解决

PaddlePaddle版本：2.3.0
   2）CPU：Inter Pentium E5400
   3）GPU：无

Traceback (most recent call last):
  File "F:/bak/wzu_pic_det/wzu_pic_det.py", line 41, in <module>
    result = ocr.ocr(np.array(Image.open('./target/' + path).convert('RGB')), -1)
  File "F:\bak\wzu_pic_det\venv\lib\site-packages\paddleocr\paddleocr.py", line 474, in ocr
    dt_boxes, rec_res = self.__call__(img, cls)
  File "F:\bak\wzu_pic_det\venv\lib\site-packages\paddleocr\tools\infer\predict_system.py", line 69, in __call__
    dt_boxes, elapse = self.text_detector(img)
  File "F:\bak\wzu_pic_det\venv\lib\site-packages\paddleocr\tools\infer\predict_det.py", line 216, in __call__
    self.predictor.run()
RuntimeError: could not create a primitive

ocr = PaddleOCR(enable_mkldnn=False 就正常，就速度难以忍受

**Comment by Gmgge** [comment]
@xinye01234  你好，方便按照上面所说，提供执行日志分析嘛，我因为后续没在搞这个点，所以没提供到日志。
