### ISSUE TITLE
关于  运行resnet50 想得到实际运行的算子信息，计算图结构

### ISSUE THREAD

**Issue by zcuuu** [PaddlePaddle/Paddle#39569]
你好  我想了解设备运行resnet50,实际被执行的算子是什么，是用什么方法呀

**Comment by JZ-LIANG** [comment]
有两个方法：
1、如果是静态图，可以打印所执行的计算图，可以参考https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/static/Program_cn.html#program

2、动态图可以尝试使用 export GLOG_vmodule=operator=5 在log 中打印所有被执行的 operators

**Comment by zcuuu** [comment]
多谢分享这两个方案 
但是我在应用的时候遇到一些问题   动态图 方案、
——————————————————————————————————————————————
python 代码 
import paddle
from paddle.vision.models import resnet50

model = resnet50(pretrained=True)

x = paddle.rand([1, 3, 224, 224])
out = model(x)

print(out.shape)

——————————
但是我添加 export 后还是没有反应
![image](https://user-images.githubusercontent.com/44340519/154786767-aa723acd-7936-48ac-a3c5-de821aae9ac9.png)


(linenet) Product-Name:~/Downloads/zc/paddlepaddle_op/rn_50_op$ python3 run-rn50.py                      /home/ms001/anaconda3/envs/linenet/lib/python3.6/site-packages/paddle/nn/layer/norm.py:653: UserWarning: When training, we now always track global mean and variance.
  "When training, we now always track global mean and variance.")
[1, 1000]

(linenet) -System-Product-Name:~/Downloads/zc/paddlepaddle_op/**rn_50_op$ export GLOG_vmodule=operator=5**           (linenet) ms001@ms001-System-Product-Name:~/Downloads/zc/paddlepaddle_op/rn_50_op$ python3 run-rn50.py
/home/ms001/anaconda3/envs/linenet/lib/python3.6/site-packages/paddle/nn/layer/norm.py:653: UserWarning: When training, we now always track global mean and variance.
  "When training, we now always track global mean and variance.")
[1, 1000]

我想知道该怎末调整，谢谢
