### ISSUE TITLE
Remove the output number limit in gradient checker.

### ISSUE THREAD

**Issue by qingqing01** [PaddlePaddle/Paddle#3956]
Now there is a limit in gradient checker: https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/v2/framework/tests/gradient_checker.py#L281

This limit will fail for multi-outputs. It should be removed and handled correctly.

**Comment by Yancey1989** [comment]
The link is failed. Maybe it already moves to https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/v2/framework/tests/op_test.py#L226. And for the multi-outputs, I think we need to calculate the sum for all the outputs, is that right?

**Comment by QiJune** [comment]
I think that if we have multi-output, we should check them just one by one. 
We have implemented multi-input checking, but actually, it's checked one by one too.

**Comment by Yancey1989** [comment]
Checking the outputs one by one works fine in most cases but in `Split Op`, if we execute +/- delta for an element, only one output of the output set will be changed, the others will be kept the same as before.
