### ISSUE TITLE
PaddleInferce使用PaddleX分类模型成功，目标检测模型测试失败？(C++语言)

### ISSUE THREAD

**Issue by MiShiDeHaiLuo** [PaddlePaddle/Paddle#39607]
系统环境：JetsonNano
在JeosonNano上通过C++调用模型测试。
使用推理引擎PaddleInference调用PaddleX模型报错。在官网PaddleInference的Demo中测试resnet50模型测试成功。后续测试PaddleX导出的分类模型也测试成功，但是使用导出的目标检测模型时报错。
首先报错.py的相关信息
terminate called after throwing an instance of 'paddle::platform::EnforceNotMet'
what():
Compile Traceback (most recent call last):
File "paddlexui\PaddleX.py", line 18, in
然后报错如下
C++ Traceback (most recent call last):
0 paddle::AnalysisPredictor::ZeroCopyRun()
1 paddle::framework::NaiveExecutor::Run()
2 paddle::framework::OperatorBase::Run(paddle::framework::Scope const&, paddle::platform::Place const&)
3 paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, paddle::platform::Place const&) const
4 paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, paddle::platform::Place const&, paddle::framework::RuntimeContext*) const
5 paddle::framework::OperatorWithKernel::ChooseKernel(paddle::framework::RuntimeContext const&, paddle::framework::Scope const&, paddle::platform::Place const&) const
6 paddle::operators::ConvOp::GetExpectedKernelType(paddle::framework::ExecutionContext const&) const
7 paddle::framework::OperatorWithKernel::IndicateVarDataType(paddle::framework::ExecutionContext const&, std::string const&) const
8 paddle::framework::OperatorWithKernel::ParseInputDataType(paddle::framework::ExecutionContext const&, std::string const&, paddle::framework::proto::VarType_Type*) const
9 paddle::platform::EnforceNotMet::EnforceNotMet(paddle::platform::ErrorSummary const&, char const*, int)
10 paddle::platform::GetCurrentTraceBackString[abi:cxx11](https://github.com/PaddlePaddle/PaddleX/issues/bool)

Error Message Summary:
InvalidArgumentError: The Tensor in the conv2d_fusion Op's Input Variable Input(image) is not initialized.
[Hint: Expected t->IsInitialized() == true, but received t->IsInitialized():0 != true:1.] (at /home/paddle/data/wangye19/tag_release/remove_paddle/Paddle/paddle/fluid/framework/operator.cc:1595)
[operator < conv2d_fusion > error]

分类模型测试没问题，测试目标检测就出问题？

**Comment by pangyoki** [comment]
你好，报错信息是输入image没有初始化，麻烦检查下是不是输入数据不够？

**Comment by MiShiDeHaiLuo** [comment]
你好，图像方面我做了两个尝试：
1.图像采用之前分类的预处理：此预处理是我自己写的，因为demo中没有，代码如下：
       /**
   * @brief Mattovector 将mat图像转为vector类型进行深度学习识别
   * @param img         mat图像
   * @param imgput      vector数据
   * @param channels    通道数
   * @param w           宽度
   * @param h           高度
   * @param clip        是否裁剪
   */
  void Mattovector(Mat img,vector<float> & imgput, int channels, int w,int h,bool clip)
  {
      if (img.rows==img.cols || !clip) //原图宽高相等或者 不裁剪 直接缩放
      {
        cv::resize(img, img, cv::Size(w, h));
      }
      else //中心点裁剪
      {
         float sc = (double)w/min(img.rows,img.cols);
         int scwidth=int(round(img.cols * sc));
         int scheight=int(round(img.rows * sc));
         cv::resize(img, img, cv::Size(scwidth, scheight));
         img = img(Rect(int((img.cols-w)/2), int((img.rows-h)/2), w, h));
      }
  
      cv::cvtColor(img,img,CV_RGB2BGR);
      vector<cv::Mat> bgrChannels(channels);
      cv::split(img, bgrChannels);
      vector<float> mean{0.485,0.456,0.406};
      vector<float> stdval{0.229,0.224,0.225};
      for (auto i = 0; i < bgrChannels.size(); i++)
        {
             bgrChannels[i].convertTo(bgrChannels[i],CV_32FC1,(1/255.0)/stdval[i],-mean[i]/stdval[i]);
             std::vector<float> data = std::vector<float>(bgrChannels[i].reshape(1, 1));
             imgput.insert(imgput.end(), data.begin(), data.end());
        }
  
  }
此方法在分类测试中成功，但是目标检测报错。
2.直接采用Demo中的方法，定义空的图像数据
     std::vector<int> INPUT_SHAPE = {1, 3, 256, 256};

    std::vector<float> input_data1(1 * 3 * 256 * 256);
    input_data1[1] = 1 % 255 * 0.1;
    input_tensor->Reshape(INPUT_SHAPE);

    input_tensor->CopyFromCpu(input_data1.data());
也是报错。

对于模型的验证，再用paddleX-qt测试模型检测成功。图像维度也输出没有问题。

**Comment by MiShiDeHaiLuo** [comment]
你好，我这边重新测试了下确定是PaddleX导出的模型问题。
![image](https://user-images.githubusercontent.com/97105652/154600924-03fbfc40-35e0-41d4-bb3b-5727194e1070.png)
这个模型就会报错最开始的错误内容。但是采用Demo中的模型Rest-50模型就能运行成功。
![image](https://user-images.githubusercontent.com/97105652/154601121-83090cf5-1a87-4dc8-9b1a-182e1a323dfd.png)

PaddelX导出的分类模型没有问题。目标检测就会出现上述问题

**Comment by MiShiDeHaiLuo** [comment]
已解决，Demo选择错误，之前以为所有模型调用是基于一个流程。。。

**Comment by MiShiDeHaiLuo** [comment]
你好，我用的C++Inferce的Demo中YoloV3进行目标检测测试，返回的结果存在问题，如下：

结果中存在很多0位数据。文件地址在：
https://github.com/PaddlePaddle/Paddle-Inference-Demo/tree/master/c%2B%2B/yolov3



麻烦您试下。
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/Paddle"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年2月17日(星期四) 中午11:29
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PaddlePaddle/Paddle] PaddleInferce使用PaddleX分类模型成功，目标检测模型测试失败？(C++语言) (Issue #39607)





 
你好，请问下，报错的模型是静态图还是动态图啊？加上paddle.enable_static()切换为静态图能解决问题吗？
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by coolxv** [comment]
我也有类似的问题用paddlex转换yolov3训练的模型后去推理报错，而使用[resnet50](https://paddle-inference-dist.bj.bcebos.com/Paddle-Inference-Demo/resnet50.tgz)却不报错


```python
import os
import cv2
import numpy as np
from paddle.inference import Config
from paddle.inference import create_predictor


def resize_short(img, target_size):
    """ resize_short """
    percent = float(target_size) / min(img.shape[0], img.shape[1])
    resized_width = int(round(img.shape[1] * percent))
    resized_height = int(round(img.shape[0] * percent))
    resized = cv2.resize(img, (resized_width, resized_height))
    return resized


def crop_image(img, target_size, center):
    """ crop_image """
    height, width = img.shape[:2]
    size = target_size
    if center == True:
        w_start = (width - size) / 2
        h_start = (height - size) / 2
    else:
        w_start = np.random.randint(0, width - size + 1)
        h_start = np.random.randint(0, height - size + 1)
    w_end = w_start + size
    h_end = h_start + size
    img = img[int(h_start):int(h_end), int(w_start):int(w_end), :]
    return img


def preprocess(img):
    mean = [0.485, 0.456, 0.406]
    std = [0.229, 0.224, 0.225]
    img = resize_short(img, 480)
    img = crop_image(img, 480, True)
    # bgr-> rgb && hwc->chw
    img = img[:, :, ::-1].astype('float32').transpose((2, 0, 1)) / 255
    img_mean = np.array(mean).reshape((3, 1, 1))
    img_std = np.array(std).reshape((3, 1, 1))
    img -= img_mean
    img /= img_std
    return img[np.newaxis, :]



def parse_args():
    params = {
        "model_dir" : "",
        "model_file" : "output/fix_yolov3_inference_model/inference_model/model.pdmodel",
        "params_file" : "output/fix_yolov3_inference_model/inference_model/model.pdiparams",
        "img_path" : "test/1.jpg",
        "threads" : 1 
        }
    # params = {
    #     "model_dir" : "",
    #     "model_file" : "/home/aistudio/output/resnet50/inference.pdmodel",
    #     "params_file" : "/home/aistudio/output/resnet50/inference.pdiparams",
    #     "img_path" : "test/1.jpg",
    #     "threads" : 1 
    #     }
    return params


args = parse_args()
print(args)
assert (args["model_dir"] != "") or \
        (args["model_file"] != "" and args["params_file"] != ""), \
        "Set model path error."
assert args["img_path"] != "", "Set img_path error."

# Init config
if args["model_dir"] == "":
    config = Config(args["model_file"], args["params_file"])
else:
    config = Config(args["model_dir"])
config.enable_mkldnn()
config.set_cpu_math_library_num_threads(args["threads"])
# config.enable_use_gpu(1000, 0)
config.switch_ir_optim()
config.enable_memory_optim()

# Create predictor
predictor = create_predictor(config)

# Set input
img = cv2.imread(args["img_path"])
img = preprocess(img)
print(img.shape)
input_names = predictor.get_input_names()
print(input_names)
input_tensor = predictor.get_input_handle(input_names[0])
input_tensor.reshape(img.shape)
print(input_tensor.shape)
# fake_input = np.random.randn(1, 3, 480, 480).astype("float32")
# input_tensor.copy_from_cpu(fake_input)
input_tensor.copy_from_cpu(img.copy())

# Run
predictor.run()

# Set output
output_names = predictor.get_output_names()
output_tensor = predictor.get_output_handle(output_names[0])
output_data = output_tensor.copy_to_cpu()

print("Predict class index: ", np.argmax(output_data))
print(output_data)
```

```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
/tmp/ipykernel_15017/589362391.py in <module>
    100 
    101 # Run
--> 102 predictor.run()
    103 
    104 # Set output

ValueError: In user code:

    File "/opt/conda/envs/python35-paddle120-env/bin/paddlex", line 8, in <module>
      sys.exit(main())
    File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlex/command.py", line 158, in main
      model._export_inference_model(args.save_dir, fixed_input_shape)
    File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlex/cv/models/base.py", line 606, in _export_inference_model
      paddle.jit.save(static_net, osp.join(save_dir, 'model'))
    File "<decorator-gen-101>", line 2, in save
      
    File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
      return wrapped_func(*args, **kwargs)
    File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/base.py", line 51, in __impl__
      return func(*args, **kwargs)
    File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/jit.py", line 744, in save
      inner_input_spec)
    File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 517, in concrete_program_specify_input_spec
      *desired_input_spec)
    File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 427, in get_concrete_program
      concrete_program, partial_program_layer = self._program_cache[cache_key]
    File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 723, in __getitem__
      self._caches[item] = self._build_once(item)
    File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 714, in _build_once
      **cache_key.kwargs)
    File "<decorator-gen-99>", line 2, in from_func_spec
      
    File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
      return wrapped_func(*args, **kwargs)
    File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/base.py", line 51, in __impl__
      return func(*args, **kwargs)
    File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 662, in from_func_spec
      outputs = static_func(*inputs)
    File "/tmp/tmp81b41655.py", line 86, in forward
      false_fn_4, (), (inputs, self), (out,))
    File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/convert_operators.py", line 211, in convert_ifelse
      out = _run_py_ifelse(pred, true_fn, false_fn, true_args, false_args)
    File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/convert_operators.py", line 257, in _run_py_ifelse
      return true_fn(*true_args) if pred else false_fn(*false_args)
    File "/tmp/tmp81b41655.py", line 69, in false_fn_4
      for_loop_body_0, [inputs_list, __for_loop_var_index_0])
    File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/convert_operators.py", line 45, in convert_while_loop
      loop_vars = _run_py_while(cond, body, loop_vars)
    File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/convert_operators.py", line 59, in _run_py_while
      loop_vars = body(*loop_vars)
    File "/tmp/tmp81b41655.py", line 64, in for_loop_body_0
      dy2static.convert_call(self.get_pred)())
    File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlex/ppdet/modeling/architectures/yolo.py", line 124, in get_pred
      return self._forward()
    File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlex/ppdet/modeling/architectures/yolo.py", line 79, in _forward
      body_feats = self.backbone(self.inputs)
    File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 917, in __call__
      return self._dygraph_call_func(*inputs, **kwargs)
    File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 907, in _dygraph_call_func
      outputs = self.forward(*inputs, **kwargs)
    File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlex/ppdet/modeling/backbones/darknet.py", line 325, in forward
      out = self.conv0(x)
    File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 917, in __call__
      return self._dygraph_call_func(*inputs, **kwargs)
    File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 907, in _dygraph_call_func
      outputs = self.forward(*inputs, **kwargs)
    File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlex/ppdet/modeling/backbones/darknet.py", line 76, in forward
      out = self.conv(inputs)
    File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 917, in __call__
      return self._dygraph_call_func(*inputs, **kwargs)
    File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 907, in _dygraph_call_func
      outputs = self.forward(*inputs, **kwargs)
    File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/nn/layer/conv.py", line 677, in forward
      use_cudnn=self._use_cudnn)
    File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/nn/functional/conv.py", line 148, in _conv_nd
      type=op_type, inputs=inputs, outputs=outputs, attrs=attrs)
    File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/layer_helper.py", line 43, in append_op
      return self.main_program.current_block().append_op(*args, **kwargs)
    File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/framework.py", line 3184, in append_op
      attrs=kwargs.get("attrs", None))
    File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/framework.py", line 2224, in __init__
      for frame in traceback.extract_stack():

    InvalidArgumentError: The Tensor in the conv2d Op's Input Variable Input(image) is not initialized.
      [Hint: Expected t->IsInitialized() == true, but received t->IsInitialized():0 != true:1.] (at /paddle/paddle/fluid/framework/operator.cc:1595)
      [operator < conv2d > error]
```

**Comment by MiShiDeHaiLuo** [comment]
我用的C++. 1.yolov3分类的代码不能直接拿来跑目标检测的模型，目标检测有专门的测试Demo代码。 2.C++目标检测的官方demo也存在问题，需要修改。 你可能遇到第一种问题



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年3月26日(星期六) 下午4:11
收件人: "PaddlePaddle/Paddle";
抄送: "State&nbsp;change";
主题: Re: [PaddlePaddle/Paddle] PaddleInferce使用PaddleX分类模型成功，目标检测模型测试失败？(C++语言) (Issue #39607)





 
我也有类似的问题用paddlex转换yolov3训练的模型后去推理报错，而使用resnet50却不报错
 import os import cv2 import numpy as np from paddle.inference import Config from paddle.inference import create_predictor def resize_short(img, target_size):     """ resize_short """     percent = float(target_size) / min(img.shape[0], img.shape[1])     resized_width = int(round(img.shape[1] * percent))     resized_height = int(round(img.shape[0] * percent))     resized = cv2.resize(img, (resized_width, resized_height))     return resized def crop_image(img, target_size, center):     """ crop_image """     height, width = img.shape[:2]     size = target_size     if center == True:         w_start = (width - size) / 2         h_start = (height - size) / 2     else:         w_start = np.random.randint(0, width - size + 1)         h_start = np.random.randint(0, height - size + 1)     w_end = w_start + size     h_end = h_start + size     img = img[int(h_start):int(h_end), int(w_start):int(w_end), :]     return img def preprocess(img):     mean = [0.485, 0.456, 0.406]     std = [0.229, 0.224, 0.225]     img = resize_short(img, 480)     img = crop_image(img, 480, True)     # bgr-&gt; rgb &amp;&amp; hwc-&gt;chw     img = img[:, :, ::-1].astype('float32').transpose((2, 0, 1)) / 255     img_mean = np.array(mean).reshape((3, 1, 1))     img_std = np.array(std).reshape((3, 1, 1))     img -= img_mean     img /= img_std     return img[np.newaxis, :] def parse_args():     params = {         "model_dir" : "",         "model_file" : "output/fix_yolov3_inference_model/inference_model/model.pdmodel",         "params_file" : "output/fix_yolov3_inference_model/inference_model/model.pdiparams",         "img_path" : "test/1.jpg",         "threads" : 1          }     # params = {     #     "model_dir" : "",     #     "model_file" : "/home/aistudio/output/resnet50/inference.pdmodel",     #     "params_file" : "/home/aistudio/output/resnet50/inference.pdiparams",     #     "img_path" : "test/1.jpg",     #     "threads" : 1      #     }     return params args = parse_args() print(args) assert (args["model_dir"] != "") or \         (args["model_file"] != "" and args["params_file"] != ""), \         "Set model path error." assert args["img_path"] != "", "Set img_path error." # Init config if args["model_dir"] == "":     config = Config(args["model_file"], args["params_file"]) else:     config = Config(args["model_dir"]) config.enable_mkldnn() config.set_cpu_math_library_num_threads(args["threads"]) # config.enable_use_gpu(1000, 0) config.switch_ir_optim() config.enable_memory_optim() # Create predictor predictor = create_predictor(config) # Set input img = cv2.imread(args["img_path"]) img = preprocess(img) print(img.shape) input_names = predictor.get_input_names() print(input_names) input_tensor = predictor.get_input_handle(input_names[0]) input_tensor.reshape(img.shape) print(input_tensor.shape) # fake_input = np.random.randn(1, 3, 480, 480).astype("float32") # input_tensor.copy_from_cpu(fake_input) input_tensor.copy_from_cpu(img.copy()) # Run predictor.run() # Set output output_names = predictor.get_output_names() output_tensor = predictor.get_output_handle(output_names[0]) output_data = output_tensor.copy_to_cpu() print("Predict class index: ", np.argmax(output_data)) print(output_data)
 --------------------------------------------------------------------------- ValueError                                Traceback (most recent call last) /tmp/ipykernel_15017/589362391.py in <module&gt;     100      101 # Run --&gt; 102 predictor.run()     103      104 # Set output ValueError: In user code:     File "/opt/conda/envs/python35-paddle120-env/bin/paddlex", line 8, in <module&gt;       sys.exit(main())     File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlex/command.py", line 158, in main       model._export_inference_model(args.save_dir, fixed_input_shape)     File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlex/cv/models/base.py", line 606, in _export_inference_model       paddle.jit.save(static_net, osp.join(save_dir, 'model'))     File "<decorator-gen-101&gt;", line 2, in save            File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__       return wrapped_func(*args, **kwargs)     File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/base.py", line 51, in __impl__       return func(*args, **kwargs)     File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/jit.py", line 744, in save       inner_input_spec)     File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 517, in concrete_program_specify_input_spec       *desired_input_spec)     File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 427, in get_concrete_program       concrete_program, partial_program_layer = self._program_cache[cache_key]     File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 723, in __getitem__       self._caches[item] = self._build_once(item)     File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 714, in _build_once       **cache_key.kwargs)     File "<decorator-gen-99&gt;", line 2, in from_func_spec            File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__       return wrapped_func(*args, **kwargs)     File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/base.py", line 51, in __impl__       return func(*args, **kwargs)     File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 662, in from_func_spec       outputs = static_func(*inputs)     File "/tmp/tmp81b41655.py", line 86, in forward       false_fn_4, (), (inputs, self), (out,))     File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/convert_operators.py", line 211, in convert_ifelse       out = _run_py_ifelse(pred, true_fn, false_fn, true_args, false_args)     File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/convert_operators.py", line 257, in _run_py_ifelse       return true_fn(*true_args) if pred else false_fn(*false_args)     File "/tmp/tmp81b41655.py", line 69, in false_fn_4       for_loop_body_0, [inputs_list, __for_loop_var_index_0])     File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/convert_operators.py", line 45, in convert_while_loop       loop_vars = _run_py_while(cond, body, loop_vars)     File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/convert_operators.py", line 59, in _run_py_while       loop_vars = body(*loop_vars)     File "/tmp/tmp81b41655.py", line 64, in for_loop_body_0       dy2static.convert_call(self.get_pred)())     File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlex/ppdet/modeling/architectures/yolo.py", line 124, in get_pred       return self._forward()     File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlex/ppdet/modeling/architectures/yolo.py", line 79, in _forward       body_feats = self.backbone(self.inputs)     File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 917, in __call__       return self._dygraph_call_func(*inputs, **kwargs)     File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 907, in _dygraph_call_func       outputs = self.forward(*inputs, **kwargs)     File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlex/ppdet/modeling/backbones/darknet.py", line 325, in forward       out = self.conv0(x)     File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 917, in __call__       return self._dygraph_call_func(*inputs, **kwargs)     File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 907, in _dygraph_call_func       outputs = self.forward(*inputs, **kwargs)     File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlex/ppdet/modeling/backbones/darknet.py", line 76, in forward       out = self.conv(inputs)     File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 917, in __call__       return self._dygraph_call_func(*inputs, **kwargs)     File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 907, in _dygraph_call_func       outputs = self.forward(*inputs, **kwargs)     File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/nn/layer/conv.py", line 677, in forward       use_cudnn=self._use_cudnn)     File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/nn/functional/conv.py", line 148, in _conv_nd       type=op_type, inputs=inputs, outputs=outputs, attrs=attrs)     File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/layer_helper.py", line 43, in append_op       return self.main_program.current_block().append_op(*args, **kwargs)     File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/framework.py", line 3184, in append_op       attrs=kwargs.get("attrs", None))     File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/framework.py", line 2224, in __init__       for frame in traceback.extract_stack():     InvalidArgumentError: The Tensor in the conv2d Op's Input Variable Input(image) is not initialized.       [Hint: Expected t-&gt;IsInitialized() == true, but received t-&gt;IsInitialized():0 != true:1.] (at /paddle/paddle/fluid/framework/operator.cc:1595)       [operator < conv2d &gt; error]  
&mdash;

**Comment by coolxv** [comment]
参考这个例子好用了：https://github.com/PaddlePaddle/Paddle-Inference-Demo/blob/master/python/yolov3/infer_yolov3.py
