### ISSUE TITLE
QAT量化训练后的inference模型相关问题.

### ISSUE THREAD

**Issue by Water2style** [PaddlePaddle/Paddle#39652]
你好，我想请教一下QAT相关问题.

1.动态图QAT完成后，存为inference模型. 用netron打开，为什么看不到整数的参数值呢.（静态图QAT完成后,在conv2d的op里是可以看到存为FP32格式的整数的）

2.QAT的模型在推理的时候，INT8的计算体现在哪些op上呢？是否有相关原理或者文章可以学习？(写论文会用上,paddleslim文档没有找到相关论文链接)

3.在用Paddle-Inference在NV-GPU上部署QAT模型时，TRT-FP32模型测的精度和在动态图训完时测的精度相差不大,但是TRT-INT8模式精度存在掉点情况(MobileNetV1). [paddleslim文档提到过 QAT-PACT可能会掉点，但是我这里普通QAT也掉了]

4.同一个模型，用QAT模型推理的速度，比PTQ模型的推理速度稍微快一些. 这是什么原因呢 ？

**Comment by itminner** [comment]
1. QAT动态图保存权重为量化前的，预测时会根据量化scale转换成int8参数。静态图量化模型权重是量化后的，只是保存成了float32格式。
2. 量化模型推理加速主要体现在conv、conv-depthwise、mul op上，推理时通过使用SIMD指令（如ARM neon）加速，int8数据相比float数据可以获得更大的吞吐量。相关原理可以自行搜索，官方文档暂无相关说明
3. 部署时精度波动是正常的，因为平台端计算会有一些差别，相差不会很大。
4. QAT和PTQ产出模型结构一致，不会有速度差异，可以测多次，求平均值。由于运行资源调度原因，速度会有波动

**Comment by Water2style** [comment]
> 1. QAT动态图保存权重为量化前的，预测时会根据量化scale转换成int8参数。静态图量化模型权重是量化后的，只是保存成了float32格式。
> 2. 量化模型推理加速主要体现在conv、conv-depthwise、mul op上，推理时通过使用SIMD指令（如ARM neon）加速，int8数据相比float数据可以获得更大的吞吐量。相关原理可以自行搜索，官方文档暂无相关说明
> 3. 部署时精度波动是正常的，因为平台端计算会有一些差别，相差不会很大。
> 4. QAT和PTQ产出模型结构一致，不会有速度差异，可以测多次，求平均值。由于运行资源调度原因，速度会有波动

好的，谢谢！
关于1，那为什么动态图的QAT, 保存成inference模型后，权重不是像静态图那样的，反而是要在预测的时候再scale成INT8计算呢？这岂不是相当于在预测阶段增加了计算量？

**Comment by itminner** [comment]
在模型转换的时候，权重就会转换int8，不会影响推理速度

**Comment by Water2style** [comment]
那如果用NVGPU推理，这一步应该就是生成TRT引擎的时候了
那是不是就没机会像静态图那样，在本地用Netron看到INT8的数据了~?

**Comment by Water2style** [comment]
> 在模型转换的时候，权重就会转换int8，不会影响推理速度

那如果用NVGPU推理，这一步应该就是生成TRT引擎的时候了
那是不是就没机会像静态图那样，在本地用Netron看到INT8的数据了~?

**Comment by itminner** [comment]
是的，量化效果及调试可以先在python-paddle端确认好。paddle产出的量化预测模型，可以像float预测模型一样在Python-paddle端加载并预测，区别是使用float类型进行int8计算，不会有加速效果，但是可以确认量化精度。
