### ISSUE TITLE
关于paddle.nn.LSTM文档双向参数的补充建议

### ISSUE THREAD

**Issue by xu-peng-7** [PaddlePaddle/Paddle#39655]
- 文档版本信息：2.22版本

#### 示例代码是否有效？
示例代码中缺少对direction 参数的示例，导致出现对该参数的使用混淆。
即，当同时初始化定义（prev_h ，prev_c），并传入 direction = 'bidirect' 时，若prev_h ，prev_c为单向LSTM参数，则传出的参数也为单向参数，但output依然为双向的输出，此时双向的数据是如何合并成为单向的？

此外：建议补充direction = 'bidirect'的示例代码

# 复现代码如下：

import paddle

rnn = paddle.nn.LSTM(16, 32, 4, direction = 'bidirect' )

x = paddle.randn((4, 23, 16))
prev_h = paddle.randn((2, 4, 32))
prev_c = paddle.randn((2, 4, 32))

y, (h, c) = rnn(x, (prev_h, prev_c))

print(y.shape)
print(h.shape)

**Comment by wanghuancoder** [comment]
感谢您的问题反馈，请@joey12300看一下该问题，并给予回复。

**Comment by joey12300** [comment]
@xu-peng-7 感谢反馈问题。后面会计划增加关于'bidirect'的示例代码，提高文档可读性

**Comment by xu-peng-7** [comment]
还有就是关于lstm的隐变量H,C的预定义问题，y, (h, c) = rnn(x, (prev_h, prev_c))

- 1：当direction = 'bidirect' 时，按照文档，输出 h，c第一个维度应为num_layers * 2，但此时若prev_h, prev_c为单向预定义时，网络并没有报错，而是输出h，c第一个维度为num_layers。

- 2：按照示例文档给两层的lstm进行了赋值，即rnn = paddle.nn.LSTM(16, 32, 2 )。但是如果修改层数，如 paddle.nn.LSTM(16, 32, 8 )，prev_h, prev_c 继续按照两层单向进行预定义赋值（即与现文档示例相同），此时网络仍然不报错。而是输出和prev_h, prev_c维度相同的h，c。

**根据以上实验结果**，我可以认为，最终LSTM的输出的隐变量（h，c）不与预定义的模型层数或direction 参数相关。这可能是一个BUG，或者应该在文档里具体说明这种不同层数预定义是如何赋值的。

**Comment by luotao1** [comment]
@xu-peng-7 欢迎提PR进行完善！
