### ISSUE TITLE
运行ctest没办法通过所有测试用例，7个test failed

### ISSUE THREAD

**Issue by QingshuChen** [PaddlePaddle/Paddle#3967]
在进行开发之前，我从develop分支下载源码进行编译（本地编译，没有使用docker，WITH_GPU设置为OFF），编译完成后在build目录下运行ctest，结果如下：
<img width="726" alt="fa6eddc5193e57c5d6b3c996da0ecb1d" src="https://user-images.githubusercontent.com/2002279/30192353-b5d48904-9479-11e7-8a1d-45e8647af909.png">
具体编译不同过其他人也有提issue，但是没有人回复，如#3864，#3935 等。

还有一个疑问，对于ctest无法通过，且确认自己修改的代码不是引起test failed的原因，是否可以提交PR。

**Comment by luotao1** [comment]
> 对于ctest无法通过，且确认自己修改的代码不是引起test failed的原因，是否可以提交PR

可以提交PR，只要github上的Teamcity和Travis ci过了即可。

**Comment by reyoung** [comment]
请用`ctest --log-on-failure`看一下具体错在哪里。
