### ISSUE TITLE
A10显卡比P40显卡速度慢，且占用显存大

### ISSUE THREAD

**Issue by basaltzhang** [PaddlePaddle/Paddle#39687]
测试PaddleOCR命令：
```
python3 tools/infer/predict_system.py \
    --image_dir="./doc/imgs/" \
    --det_model_dir="./inference/ch_ppocr_server_v2.0_det_infer/" \
    --rec_model_dir="./inference/ch_ppocr_server_v2.0_rec_infer/" \
    --cls_model_dir="./inference/ch_ppocr_mobile_v2.0_cls_infer/" \
    --use_angle_cls=true --use_mp=True --total_process_num=6
```
P40单图大概3秒多，A10显卡要4秒多。
P40单进程大约1.3G显存，A10要2.x G显存。
怀疑是编译问题，我在A10上重新编译了paddle，还是有这种问题。
编译命令：
```
cmake .. -DPY_VERSION=3 \
        -DWITH_TESTING=OFF \
        -DWITH_MKL=ON \
        -DWITH_GPU=ON \
        -DON_INFER=ON \
        -DCUDA_ARCH_NAME=Auto
```
使用v2.2.2和v2.1.0版本paddle均存在此现象，求帮忙看下是哪里有问题。

**Comment by wanghuancoder** [comment]
感谢您的问题反馈，我们复现一下问题，有结论以后给您反馈。

**Comment by liyancas** [comment]
您好，可以提供下复现问题的环境（OS/cuda/cudnn/tensorrt）吗？

**Comment by basaltzhang** [comment]
@liyancas centos7.5 cuda11.2.2 cudnn8.2.1 没有用tensorrt

**Comment by liyancas** [comment]
你好，请问这个具体模型可以明确下吗？

**Comment by basaltzhang** [comment]
@liyancas 参考的[pdserving readme](https://github.com/PaddlePaddle/PaddleOCR/tree/release/2.4/deploy/pdserving#model-conversion)，下载[paddleocr 首页模型](https://github.com/PaddlePaddle/PaddleOCR#pp-ocr-series-model-listupdate-on-september-8th)，server这一行的三个infer_model

**Comment by liyancas** [comment]
好的，我们这边分析下，尽快反馈，谢谢！

**Comment by basaltzhang** [comment]
@liyancas 显存增长、耗时变长的现象可以复现吗？

**Comment by xiaoxiaohehe001** [comment]
@[basaltzhang](https://github.com/basaltzhang)  感谢您提供的问题，问题可以复现，具体原因在定位中。

**Comment by basaltzhang** [comment]
@xiaoxiaohehe001 hi，请问定位到原因了吗？

**Comment by basaltzhang** [comment]
@xiaoxiaohehe001 hi，请问定位到原因了吗？

**Comment by xiaoxiaohehe001** [comment]
@[basaltzhang](https://github.com/basaltzhang) 经过定位后发现模型首次运行，A10时间要略长，所以在运行前打开warmup，速度会提升，并且在predict_system.py 中加入 os.environ["FLAGS_cudnn_exhaustive_search"] = '1' 可以进一步加速GPU计算速度。

**Comment by basaltzhang** [comment]
> @[basaltzhang](https://github.com/basaltzhang) 经过定位后发现模型首次运行，A10时间要略长，所以在运行前打开warmup，速度会提升，

我并不是只计算第一次运行速度，我计算的是多次运行后的速度。

>并且在predict_system.py 中加入 os.environ["FLAGS_cudnn_exhaustive_search"] = '1' 可以进一步加速GPU计算速度。

FLAGS_cudnn_exhaustive_search这个是只对A10生效吗，会不会打开后P40和A10都会变快。

**Comment by xiaoxiaohehe001** [comment]
@[basaltzhang](https://github.com/basaltzhang) FLAGS_cudnn_exhaustive_search 这个都生效的，您可以测试一下，速度上A10要快于P40的，目前的耗时主要问题在cpu上较多，我们最近也在处理这方面的问题。

**Comment by basaltzhang** [comment]
> @[basaltzhang](https://github.com/basaltzhang) FLAGS_cudnn_exhaustive_search 这个都生效的，您可以测试一下，速度上A10要快于P40的，目前的耗时主要问题在cpu上较多，我们最近也在处理这方面的问题。

好的，我试一下这个flag
