### ISSUE TITLE
PaddlePaddle中使用GBDT、FM的疑问

### ISSUE THREAD

**Issue by buptwds** [PaddlePaddle/Paddle#3971]
在ctr预估中，现在使用的是LR，然后尝试了Wide&Deep，效果并没有提升。现在想做一些特征的组合，网上查阅资料说GBDT、FM的效果比较好，想问一下在PaddlePaddle中应该如何使用，或者PaddlePaddle中是否有可替代的模型？或者对于ctr预估还有其他什么建议吗？注：目前的训练集是01稀疏矩阵

**Comment by lcy-seso** [comment]
GBDT 完全是树模型那一套。和神经网络不是一套方法。
FM paddle 现在不支持，没有完成FM运算的层。

**Comment by buptwds** [comment]
那像我现在这种情况（01稀疏矩阵的ctr预估），有什么好的建议吗

**Comment by lcy-seso** [comment]
其它用户也提出过关于 FM 层的问题 https://github.com/PaddlePaddle/Paddle/issues/3664 ， Paddle暂时不支持，我们会考虑添加，计划待定。

**Comment by jacquesqiao** [comment]
FM is supported, and GBDT will not be supported by PaddlePaddle.
