### ISSUE TITLE
docker版本paddledev/paddle:0.10.0rc3-noavx，运行机器翻译的例子出现'Floating point exception'

### ISSUE THREAD

**Issue by baozhi** [PaddlePaddle/Paddle#3972]
![cfa0fae9507e742d9e788674cb41fb29](https://user-images.githubusercontent.com/4001686/30195955-a856d172-948f-11e7-9c96-81dc7871927b.jpg)

**Comment by chengduoZH** [comment]
用户使用的话，一般用https://hub.docker.com/r/paddlepaddle/paddle/tags/这里面的docker，https://hub.docker.com/r/paddledev/paddle/tags/中列的是开发版的。
同时，paddle paddle也提供了paddle book的镜像https://hub.docker.com/r/paddlepaddle/book/，最新的paddlebook是没有问题的
