### ISSUE TITLE
基于C++的目标检测返回结果一位数组怎么看？

### ISSUE THREAD

**Issue by MiShiDeHaiLuo** [PaddlePaddle/Paddle#39722]
用C++调用目标检测模型，返回的数据是一维数据但是按照6个长度步长截取存在问题？
![image](https://user-images.githubusercontent.com/97105652/154639804-e0592d9d-50a7-4ee8-93da-b5fe528667af.png)
这个返回数据应该按照什么规律去看？

**Comment by zhwesky2010** [comment]
@MiShiDeHaiLuo 请问跑的是什么代码呢

**Comment by MiShiDeHaiLuo** [comment]
跑的是Demo中的目标检测Yolo v3
![image](https://user-images.githubusercontent.com/97105652/154643440-84d93bba-d290-457a-aab1-a3b360c1db01.png)

图像也是加载的Demo中的海滩图像

**Comment by zhwesky2010** [comment]
@MiShiDeHaiLuo 有仓库或文件github地址吗

**Comment by MiShiDeHaiLuo** [comment]
https://github.com/MiShiDeHaiLuo/paddle
你好，临时上传了一份。方便给邮箱的话可以发您邮箱中。模型文件太大无法上传，以下是百度云链接。模型是Demo中的Yolo-v3模型，也可以直接在网上下载。
链接：https://pan.baidu.com/s/1abPUEZU61CqlOvCIoa2WqQ 
提取码：1234

**Comment by jiweibo** [comment]
您好，yolo模型一般最后一层是nms，输出应该是nms算子的输出，格式一般为[N, 6] （标签label，置信度confidence，xmin，ymin，xmax，ymax）

您可查阅nms算子文档 https://www.paddlepaddle.org.cn/documentation/docs/zh/1.8/api_cn/layers_cn/multiclass_nms_cn.html#multiclass-nms

**Comment by MiShiDeHaiLuo** [comment]
我知道我用的C++输出只是一维的Vector<float>,单数里面数据比较奇怪。6个一组只有3个数据 其余都是0
![image](https://user-images.githubusercontent.com/97105652/154871757-e620339d-e230-462e-a4a3-92469cf1db89.png)

**Comment by MiShiDeHaiLuo** [comment]
> @MiShiDeHaiLuo 有仓库或文件github地址吗
![image](https://user-images.githubusercontent.com/97105652/154894777-eb32a1eb-78fe-48dc-8bf1-35add59ff7a5.png)
就是官方的infercen  Demo中  Yolov3也是返回的数据存在多位0数据，你可以直接调用官方Demo

**Comment by MiShiDeHaiLuo** [comment]
> 您好，yolo模型一般最后一层是nms，输出应该是nms算子的输出，格式一般为[N, 6] （标签label，置信度confidence，xmin，ymin，xmax，ymax）
> 
> 您可查阅nms算子文档 https://www.paddlepaddle.org.cn/documentation/docs/zh/1.8/api_cn/layers_cn/multiclass_nms_cn.html#multiclass-nms

![image](https://user-images.githubusercontent.com/97105652/154894903-98cd6750-0964-4ff7-bd1c-edc0f0cf6dc4.png)
就是官方的infercen Demo中 Yolov3也是返回的数据存在多位0数据，你可以直接调用官方Demo测试下

**Comment by zhwesky2010** [comment]
> 

请问这个yolov3_test的文件位置？

**Comment by MiShiDeHaiLuo** [comment]
> > 
> 
> 请问这个yolov3_test的文件位置？
这是github上的位置
https://github.com/PaddlePaddle/Paddle-Inference-Demo/tree/master/c%2B%2B/yolov3
![image](https://user-images.githubusercontent.com/97105652/154902690-83bfd4f7-0470-4f42-b37d-e1b7e90c390a.png)

**Comment by MiShiDeHaiLuo** [comment]
> > 
> 
> 请问这个yolov3_test的文件位置？

您好，麻烦问一下测试效果怎么样？成功了吗？

**Comment by MiShiDeHaiLuo** [comment]
您好，这是github上的位置
https://github.com/PaddlePaddle/Paddle-Inference-Demo/tree/master/c%2B%2B/yolov3



------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/Paddle"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年2月21日(星期一) 下午2:40
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PaddlePaddle/Paddle] 基于C++的目标检测返回结果一位数组怎么看？ (Issue #39722)





   
请问这个yolov3_test的文件位置？
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by MiShiDeHaiLuo** [comment]
@zhouwei25 @jiweibo 您好,,有结果了吗？

**Comment by MiShiDeHaiLuo** [comment]
问题解决了，c++提供的Demo存在很大问题，还需要照着python的Demo来排错。太不应该了

**Comment by zhwesky2010** [comment]
> 问题解决了，c++提供的Demo存在很大问题，还需要照着python的Demo来排错。太不应该了

您好，我们后面会进行修复，感谢提出问题
