### ISSUE TITLE
关于 动态图 查看op 信息   使用 export glog——vmodule=operator=5  无反应的求解

### ISSUE THREAD

**Issue by zcuuu** [PaddlePaddle/Paddle#39741]
但是我在应用的时候遇到一些问题 动态图 方案、

python 代码
——————————————————————————————————————————————
python 代码
import paddle
from paddle.vision.models import resnet50

model = resnet50(pretrained=True)

x = paddle.rand([1, 3, 224, 224])
out = model(x)

print(out.shape)

——————————
但是我添加 export 后还是没有反应
image

(linenet) Product-Name:~/Downloads/zc/paddlepaddle_op/rn_50_op$ python3 run-rn50.py /home/ms001/anaconda3/envs/linenet/lib/python3.6/site-packages/paddle/nn/layer/norm.py:653: UserWarning: When training, we now always track global mean and variance.
"When training, we now always track global mean and variance.")
[1, 1000]

(linenet) -System-Product-Name:/Downloads/zc/paddlepaddle_op/rn_50_op$ export GLOG_vmodule=operator=5 
ms001@ms001-System-Product-Name:/Downloads/zc/paddlepaddle_op/rn_50_op$ python3 run-rn50.py
/home/ms001/anaconda3/envs/linenet/lib/python3.6/site-packages/paddle/nn/layer/norm.py:653: UserWarning: When training, we now always track global mean and variance.
"When training, we now always track global mean and variance.")
[1, 1000]

我想知道该怎末调整，谢谢

**Comment by haozech** [comment]
你好，如果想输出更多debug信息，可以用`export GLOG_v=4`。`export GLOG_vmodule=operator=5` 这个命令是出自文档吗？能否附上来源，谢谢~

**Comment by zcuuu** [comment]
哈喽 感谢您的解答，您提供的export GLOG_v=4 是可以显示更多信息的，至于export GLOG_vmodule=operator=5 是来自issue
#39569 
您好其实我想了解的是 类似于 resnet 中conv bn relu 这样的算子，有可能是会融合成 一个算子的，我是想了解在运行resnet 50 中所运行的 fuse op
但是我在 cpu 以及gpu 执行打印出来的 算子信息 还是
单独的 conv2d
           batch_norm
          relu

看起来并不是我想看到的融合后的算子

所以我想问问，我该怎末调整  谢谢

**Comment by haozech** [comment]
> 

您好，从代码上看您使用的是训练端搭建的网络结构，然后运行了前向计算。这时一般不会进行算子融合。您可以通过save_inference_model将其转化为推理模型，然后参考此文档 https://paddleinference.paddlepaddle.org.cn/api_reference/cxx_api_doc/Config/OptimConfig.html#ir 通过SwitchIrDebug接口输出图优化之后的图整体结构，通过GraphVis查看dot文件来查看优化后图结构。

**Comment by zcuuu** [comment]
非常感谢您的回复， 您给的链接会进行学习
此外：
确实，这是训练端搭建网络的前向，那么如果这是一个完整的训练过程，请问他会进行算子融合嘛

**Comment by haozech** [comment]
> 非常感谢您的回复， 您给的链接会进行学习 此外： 确实，这是训练端搭建网络的前向，那么如果这是一个完整的训练过程，请问他会进行算子融合嘛

默认情况下，训练端一般不会进行算子融合
