### ISSUE TITLE
PaddleDetection训练时开启了Eval，发现特别慢，并定位到问题在matrix_nms函数特别慢

### ISSUE THREAD

**Issue by icedream2linxi** [PaddlePaddle/Paddle#39742]
PaddlePaddle版本：2.2.2
CPU: i7-6850K
GPU: GeForce 1080 Ti
系统：Ubuntu 20.04
Python: 3.8.12
Numpy: 1.21.2

执行一次 matrix_nms，耗时30秒，这时间太长了。
``` Python
import paddle
import paddle.fluid as fluid
import pickle
import numpy as np
from pathlib import Path
import time
paddle.enable_static()


root_dir = Path(__file__).parent.absolute()
with open(root_dir / 'bboxes.dat', 'rb') as f:
    bboxes_data = pickle.load(f)
with open(root_dir / 'scores.dat', 'rb') as f:
    scores_data = pickle.load(f)

bboxes = fluid.data(name='bboxes', shape=bboxes_data.shape,
                        dtype='float32', lod_level=1)
scores = fluid.data(name='scores', shape=scores_data.shape,
                        dtype='float32', lod_level=1)

background_label = -1
score_threshold = 0.01
post_threshold = 0.01
nms_top_k = -1
gaussian_sigma = 2.0
use_gaussian = False
keep_top_k = 100
normalized = False

res = fluid.layers.matrix_nms(bboxes=bboxes,
                              scores=scores,
                              background_label=background_label,
                              score_threshold=score_threshold,
                              post_threshold=post_threshold,
                              nms_top_k=nms_top_k,
                              gaussian_sigma=gaussian_sigma,
                              use_gaussian=use_gaussian,
                              keep_top_k=keep_top_k,
                              normalized=normalized)

exe = fluid.Executor(fluid.CPUPlace())
st = time.time()
out = exe.run(fluid.default_main_program(),
            feed={
                'bboxes': bboxes_data,
                'scores': scores_data
            },
            fetch_list=[res.name],
            return_numpy=False)
et = time.time()
print('time = {}'.format(et - st))

out = np.array(out)

print(out)
```

[test.zip](https://github.com/PaddlePaddle/Paddle/files/8101468/test.zip)

**Comment by wangxinxin08** [comment]
你好，matrix_nms在训练结果比较差的时候会导致运行时间非常长，这个是由于算法的实现本身导致的，所以，你可以选择将sanepshot_epoch改大，或者使用multiclass_nms替换matrix_nms，通过调整参数，multicalss nms基本能达到和matrix_nms接近的精度

**Comment by icedream2linxi** [comment]
> 这个是由于算法的实现本身导致的

你们定义这个问题是BUG呢？还是不是BUG，现在的结果就是预期的！
你们会改matrix_nms的实现解决这个问题吗？

**Comment by wangxinxin08** [comment]
> > 这个是由于算法的实现本身导致的
> 
> 你们定义这个问题是BUG呢？还是不是BUG，现在的结果就是预期的！ 你们会改matrix_nms的实现解决这个问题吗？

不是bug，应该是算法的原理导致的

**Comment by icedream2linxi** [comment]
https://github.com/PaddlePaddle/Paddle/blob/2bb5aae8fd6a521183565ade69dfc72ec8a83ce0/paddle/fluid/operators/detection/matrix_nms_op.cc#L112-L115
应该是BUG吧？！
看这代码，是把置信度小于阀值的剔除掉；我的数据里有很多置信度为nan的值，应该属于要剔除掉的。
我把114行改成`return isnan(score_ptr[idx]) || score_ptr[idx] <= score_threshold;`就很快了。

**Comment by wangxinxin08** [comment]
> https://github.com/PaddlePaddle/Paddle/blob/2bb5aae8fd6a521183565ade69dfc72ec8a83ce0/paddle/fluid/operators/detection/matrix_nms_op.cc#L112-L115
> 
> 
> 应该是BUG吧？！
> 看这代码，是把置信度小于阀值的剔除掉；我的数据里有很多置信度为nan的值，应该属于要剔除掉的。
> 我把114行改成`return isnan(score_ptr[idx]) || score_ptr[idx] <= score_threshold;`就很快了。

置信度为什么会为nan？不是sigmoid或者softmax之后的吗？

**Comment by icedream2linxi** [comment]
> 置信度为什么会为nan？不是sigmoid或者softmax之后的吗？

https://github.com/PaddlePaddle/PaddleDetection/blob/4cff569cbf3a2120e97ea69a5a0902fe6c4fb78a/ppdet/modeling/post_process.py#L66-L68
这里的decode对应的是YOLOBox。所以是YOLOBox之后调用的matrix_nms。
再往前捋一捋。顺序是 sigmoid -> _de_sigmoid -> YOLOBox -> matrix_nms。

**Comment by wangxinxin08** [comment]
> > 置信度为什么会为nan？不是sigmoid或者softmax之后的吗？
> 
> https://github.com/PaddlePaddle/PaddleDetection/blob/4cff569cbf3a2120e97ea69a5a0902fe6c4fb78a/ppdet/modeling/post_process.py#L66-L68 这里的decode对应的是YOLOBox。所以是YOLOBox之后调用的matrix_nms。 再往前捋一捋。顺序是 sigmoid -> _de_sigmoid -> YOLOBox -> matrix_nms。

YOLOBox里面是有对conf做sigmoid的， https://github.com/PaddlePaddle/Paddle/blob/2bb5aae8fd6a521183565ade69dfc72ec8a83ce0/paddle/fluid/operators/detection/yolo_box_op.cu#L49

**Comment by icedream2linxi** [comment]
训练结果被我不小心删掉了，无法往前调，看前面出来的是什么数据。
重新训练没有重现。PaddleDetection的代码我也没有改过。
不过从逻辑上，不是应该要剔除掉nan的数据吗？

**Comment by wangxinxin08** [comment]
nms的输入是score和box的坐标，score是经过softmax或者sigmoid的
