### ISSUE TITLE
离线部署飞桨的文档？

### ISSUE THREAD

**Issue by marderary** [PaddlePaddle/Paddle#39745]
由于客观网络条件，需要离线部署飞桨环境，找了很多方法都不成功，请问有没有官方的离线部署指导文档？

**Comment by haozech** [comment]
你好，目前没有官方的离线部署文档。如果需要离线部署，那么建议方式是在在线环境先下好paddle whl安装包( https://www.paddlepaddle.org.cn/whl/linux/mkl/avx/stable.html )，以及paddle依赖的第三方库( https://github.com/PaddlePaddle/Paddle/blob/develop/python/requirements.txt )，具体通过`pip install --download`命令来下载。然后在离线环境下通过这些whl包进行安装。注意paddle whl安装包下载是要按照离线环境的软硬件环境下载对应的安装包。

**Comment by haozech** [comment]
另外标题可以修改下，应该是「飞桨」~
然后离线的其他办法还可以将docker中我们飞桨官方的image registry.baidubce.com/paddlepaddle/paddle:2.2.2-gpu-cuda10.2-cudnn7 下载下来，到离线环境中创建container然后在docker环境中使用。
如果方便的话，可以提供更具体的离线环境信息，方便我们进一步支持~

**Comment by GT-ZhangAcer** [comment]
https://www.jianshu.com/p/964e3badb8e2
很久之前写过一篇，离线不难的，熟悉pip这个就是很轻松的事情
