### ISSUE TITLE
(NotFound) Operator elementwise_div does not have kernel for data_type[bool]

### ISSUE THREAD

**Issue by Xingyu-Romantic** [PaddlePaddle/Paddle#39757]
**To Reproduce**
```python
import torch

y1 = torch.Tensor([1, 2, 3, -1])
y2 = torch.Tensor([2, 1, 2, 3])
print((y1> 0) / y2)
```
Result: tensor([0.5000, 1.0000, 0.5000, 0.0000])

```python
import paddle
import numpy as np
y1 = paddle.to_tensor(np.array([1, 2, 3, -1]))
y2 = paddle.to_tensor(np.array([2, 1, 2, 3]))
print((y1 > 0) / y2)
```
Error: (NotFound) Operator elementwise_div does not have kernel for data_type[bool]:data_layout[ANY_LAYOUT]:place[CPUPlace]:library_type[PLAIN].
  [Hint: Expected kernel_iter != kernels.end(), but received kernel_iter == kernels.end().] (at /paddle/paddle/fluid/imperative/prepared_operator.cc:159)
  [operator < elementwise_div > error]

希望能适应Bool型 Div的计算
**Describe the feature and the current behavior/state.**
**Any Other info.**

**Comment by yinhaofeng** [comment]
这里elementwise_div在2.0之后的版本中为paddle.divide算子。逐元素相除如果使用bool型会导致除零错误。我理解这里错误的发生是因为paddlepaddle和pytorch的用法存在差异。您可以参考这里的办法解决问题：
https://github.com/PaddlePaddle/X2Paddle/blob/develop/docs/pytorch_project_convertor/API_docs/ops/torch.div.md
https://github.com/PaddlePaddle/X2Paddle/blob/develop/docs/pytorch_project_convertor/API_docs/ops/torch.divide.md
