### ISSUE TITLE
pytorch 可以用Parameter.data 修改数据，paddle里该怎么修改

### ISSUE THREAD

**Issue by ZiJINII** [PaddlePaddle/Paddle#39752]
#残差网络卷积2D卷积
class Res_conv2d(nn.Layer):
    def __init__(self):
        super(Res_conv2d, self).__init__()
        self.weight = paddle.create_parameter(shape=[30,1,5,5],dtype = "float32")
        self.bias = paddle.create_parameter(shape=[30],dtype = "float32")
        self.reset_parameters()
        
    def reset_parameters(self):
        self.weight.numpy()[:] = SRM_npy
       -->self.bias.data.zero_()#报错
    def forward(self, input):
        return F.conv2d(input, self.weight, self.bias)

![image](https://user-images.githubusercontent.com/92594026/154840741-a7e4c32b-8a73-441b-b05f-e12d229b99e8.png)

**Comment by qili93** [comment]
hi @ZiJINII ,

Paddle的Parameter对象不支持直接通过data访问，建议使用这个API在reset_parameters方法中修改Parameter的值：

https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/nn/utils/vector_to_parameters_cn.html#vector-to-parameters

如果你只需要把parameter在初始化的时候设置为0，也可以在调用create_parameter是输入initializer为initializer.Constant(0.0)来设置初始值。
