### ISSUE TITLE
对paddle内置数据集WMT16内置数据集的补充建议

### ISSUE THREAD

**Issue by xu-peng-7** [PaddlePaddle/Paddle#39754]
class paddle.text.datasets.WMT16 中对WMT16的介绍过于简单，示例程序运行显示方块，返回值无介绍，数据集无介绍，无使用案例。建议补充。

**Comment by xu-peng-7** [comment]
trg_ids返回值怎么几乎全是2啊？还有读取数据集的参数也没文档说明

**Comment by qili93** [comment]
感谢您的反馈，会尽快补充关于WMT16内置数据集的相关文档，谢谢！
