### ISSUE TITLE
paddle.where函数x, y不支持float，而numpy.where和torch.where均支持，希望函数功能与两者相同

### ISSUE THREAD

**Issue by phoenixsfly** [PaddlePaddle/Paddle#39821]
- 版本、环境信息：
    1）PaddlePaddle版本：paddle2.2-gpu
    2）CPU/GPU：CUDA11.3 
    3）系统环境：Windows11
    4）Python3.8

在paddle中报错：
```
> a = paddle.to_tensor([1.0, 2.0, 3.0, 4.0])
> paddle.where(a > 2, 1.0, 0.0)

AttributeError: 'float' object has no attribute 'shape'
```

在numpy中可以运行：
```
> a = np.array([1.0, 2.0, 3.0, 4.0])
> np.where(a > 2, 1.0, 0.0)

array([0., 0., 1., 1.])
```

在pytorch中：
```
>a = torch.tensor([1.0, 2.0, 3.0, 4.0])
>torch.where(a > 2, 1.0, 0.0)

tensor([0., 0., 1., 1.])
```
原因在于``paddle.where(condition, x, y, name=None)`` 要求参数x, y必须是具有shape的tensor，而numpy和pytorch若x, y不是tensor会在内部自动转为tensor 
在paddle中实现相同功能的代码需要这样写：
```
> a = paddle.to_tensor([1.0, 2.0, 3.0, 4.0])
> paddle.where(a > 2, paddle.to_tensor(1.0), paddle.to_tensor(0.0))
```
但是写法很复杂，丧失了可读性。
希望paddle.where函数能与numpy和pytorch功能上保持一致。

**Comment by littletomatodonkey** [comment]
你好，感谢反馈，我们记录下这个需求~

**Comment by onecatcn** [comment]
非常感谢您的宝贵建议，我们将在PaddlePaddle2.3中加入这一功能，敬请关注

**Comment by luotao1** [comment]
2.4 版本的 paddle.where 函数 x,y 已经支持float了：https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/where_cn.html#where 
<img width="689" alt="image" src="https://user-images.githubusercontent.com/6836917/212261268-2f3a937c-35bd-4a24-833d-ca455f9a57b1.png">
