### ISSUE TITLE
docker不能配置是否使用MKLDNN

### ISSUE THREAD

**Issue by shijiaxin** [PaddlePaddle/Paddle#3983]
paddle/scripts/docker/build.sh里面，没有设置DWITH_MKLDNN以及DWITH_MKLML，MKLDNN和MKLML默认被使用且无法配置。

**Comment by typhoonzero** [comment]
这个可以在build.sh中加下，不过在使用的时候完全可以进入latest-dev容器中，然后修改buil.sh再build。
