### ISSUE TITLE
中标麒麟v10系统下使用xpu部署时报错

### ISSUE THREAD

**Issue by LuoyesK** [PaddlePaddle/Paddle#39835]
系统：中标麒麟v10
cpu架构：aarch64
python版本：3.7
paddlelite版本：v2.10
paddlelite编译命令：./build_linux.sh --arch=armv8 --with_python=ON --with_baidu_xpu=ON --with_extra=ON --with_cv=ON
具体问题：在将训练好的模型转为xpu后，使用python进行xpu部署时报错，具体出错代码为predictor = create_predictor(model_dir)
报错信息：[F 2/13 10:4:53.764 ...Lite/lite/model_parser/flatbuffers/io.cc:66 FillTensor] Check failed: dst: 已放弃（核心已转储）
另外尝试使用opt将同一模型转为arm后再执行程序，之后程序顺利执行

**Comment by zhupengyang** [comment]
xpu不支持opt转换的模型，请参考[文档](https://paddle-lite.readthedocs.io/zh/latest/demo_guides/baidu_xpu.html)Demo部分直接加载原始模型

**Comment by LuoyesK** [comment]
所以xpu只能使用C++以及paddle训练出来的原始模型吗？

**Comment by zhupengyang** [comment]
> 所以xpu只能使用C++以及paddle训练出来的原始模型吗？

- 不限定语言。不过目前推荐c++，部分Python接口还不完善。
- 仅支持paddle原始模型

**Comment by LuoyesK** [comment]
但是我看python api的相关文档有写：
TargetType 为目标设备硬件类型，用户可以根据应用场景选择硬件平台类型。枚举型变量 TargetType 的取值包括 {X86, CUDA, ARM, OpenCL, FPGA, NPU} 等。
我具体看了下里边没有XPU，这是不是意味着要在xpu上部署只能使用C++的api？

**Comment by zhupengyang** [comment]
> 但是我看python api的相关文档有写： TargetType 为目标设备硬件类型，用户可以根据应用场景选择硬件平台类型。枚举型变量 TargetType 的取值包括 {X86, CUDA, ARM, OpenCL, FPGA, NPU} 等。 我具体看了下里边没有XPU，这是不是意味着要在xpu上部署只能使用C++的api？

是的，2.10没有。下个版本会有。
