### ISSUE TITLE
unexpected keyword argument 'error_clipping_threshold'

### ISSUE THREAD

**Issue by youan1** [PaddlePaddle/Paddle#3985]
如题：

在fc全连接层里使用layer_attr的时候报错说，error_clipping_threshold这个关键词找不到
emb1_29 = paddle.layer.fc(name="emb1_29",input=data29, size=64,
                          act=paddle.activation.Linear(),
                          param_attr=paddle.attr.Param(initial_std=emb_layer_init_std[1])，
                         layer_attr=paddle.attr.ExtraAttr(error_clipping_threshold=10.0))

但是在embedding层里同样使用的时候就能通过：
emb1_7 = paddle.layer.embedding(name="emb1_7",input=data7, size=16, param_attr=paddle.attr.Param(
                                 initial_std=emb_layer_init_std[3]),
                                layer_attr=paddle.attr.ExtraAttr(error_clipping_threshold=10.0))

请问该如何解决

**Comment by NHZlX** [comment]
在我的机器上是ok的，请确保你的paddle版本是最新的

**Comment by youan1** [comment]
谢谢，在paddle群里问的时候，caoyin说是刚fix，原来是有这个问题，另外本地升级我可以自己做，MPI 集群升级怎么做
