### ISSUE TITLE
启动pserver失败，请问是什么原因

### ISSUE THREAD

**Issue by thomaslwang** [PaddlePaddle/Paddle#3986]
start_pserver.sh脚本如下：
#!/bin/sh
set -e
source /home/paddle/enter.sh
cd /home/paddle/train_cluster/
if [ ! -d "workspace/log" ]; then
  mkdir -p workspace/log
fi
GLOG_logtostderr=0 GLOG_log_dir="./workspace/log"
paddle pserver \
  --num_gradient_servers=2 \
  --nics="eth0" \
  --port=7164 \
  --ports_num=2 \
  --ports_num_for_sparse=2 \
  --comment=paddle_process_by_paddle \
  2>&1 | tee ./workspace/log/server.log

错误信息如下：
I0909 14:42:51.582460 15056 Util.cpp:166] commandline: /home/paddle/usr/local/bin/../opt/paddle/bin/paddle_pserver_main --num_gradient_servers=2 --nics=eth0 --port=7164 --ports_num=2 --ports_num_for_sparse=2 --comment=paddle_process_by_paddle
F0909 14:42:51.584151 15056 LightNetwork.cpp:71] Check failed: ioctl(sock, 0x8915, &ifr) >= 0 (-1 vs. 0)
*** Check failure stack trace: ***
    @           0x8e9a5d  google::LogMessage::Fail()
    @           0x8ed50c  google::LogMessage::SendToLog()
    @           0x8e9583  google::LogMessage::Flush()
    @           0x8eea1e  google::LogMessageFatal::~LogMessageFatal()
    @           0x782b2f  paddle::getIpAddr()
    @           0x76415b  paddle::ParameterServerController::ParameterServerController()
    @           0x7645f2  paddle::ParameterServerController::create()
    @           0x7646a2  paddle::ParameterServerController::createFromGflags()
    @           0x5cf0c1  main
    @     0x7f2838e12bd5  __libc_start_main
    @           0x5dc715  (unknown)
    @              (nil)  (unknown)
/home/paddle/usr/local/bin/paddle: line 113: 15056 Aborted                 ${DEBUGGER} $MYDIR/../opt/paddle/bin/paddle_pserver_main ${@:2}

**Comment by typhoonzero** [comment]
可能的原因：
1. `--nics=eth0` 去掉引号
1. 网卡设备名称是否的确是`eth0`?

**Comment by thomaslwang** [comment]
多谢，确实是这个问题。
