### ISSUE TITLE
GRU 文档问题

### ISSUE THREAD

**Issue by tz28** [PaddlePaddle/Paddle#39865]
- 文档版本信息：2.2

### 文档问题描述：
文档链接：https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/nn/GRU_cn.html#gru
关于GRU这个OP的文档，在描述输出 outputs 和 final_states 时，都用到了time_steps，但通篇没有关于time_steps是什么的介绍，虽然这对搞NLP的同学来说能够大体猜出来是句子长度，但是对于一般小白来说，甚至不搞NLP的人来说，根本不太知道time_steps是指什么？这对理解outputs 和 final_states的shape极为不利，建议增加解释time_steps的含义
![image](https://user-images.githubusercontent.com/9672354/155315880-dfe3a146-0e6f-4618-9ef8-3697d8c1f799.png)

#### API文档描述是否清晰？
文档描述看不懂，不知道time_steps指什么

#### 返回/形状说明是否清晰
API返回值、数据的形状描述不清楚，不知道time_steps指什么

**Comment by luotao1** [comment]
@tz28 欢迎提PR进行完善！
