### ISSUE TITLE
Cluster train一直停在，不进行训练也不退出，可能是什么问题

### ISSUE THREAD

**Issue by thomaslwang** [PaddlePaddle/Paddle#3990]
paddle train的log如下：
I0909 22:39:28.636253 30607 Util.cpp:166] commandline: /home/paddle/usr/local/bin/../opt/paddle/bin/paddle_trainer --num_gradient_servers=2 --nics=xgbe0 --port=7164 --ports_num=2 --comment=paddle_process_by_paddle --pservers=10.103.205.28,10.103.205.29 --trainer_id=2 --dot_period=10 --ports_num_for_sparse=2 --log_period=100 --num_passes=10 --trainer_count=4 --saving_period=1 --local=0 --config=./trainer_config.py --save_dir=./job_dir/output --use_gpu=0
[INFO 2017-09-09 22:39:28,878 networks.py:1459] The input order is [spa, cont, opidseq, label]
[INFO 2017-09-09 22:39:28,878 networks.py:1465] The output order is [__cross_entropy_0__]
I0909 22:39:28.881898 30607 Trainer.cpp:165] trainer mode: Normal
I0909 22:39:29.027751 30607 PyDataProvider2.cpp:243] loading dataprovider data_provider::process
I0909 22:39:29.036746 30607 PyDataProvider2.cpp:243] loading dataprovider data_provider::process
I0909 22:39:29.036993 30607 GradientMachine.cpp:85] Initing parameters..
I0909 22:39:29.279141 30607 GradientMachine.cpp:92] Init parameters done.
I0909 22:39:29.286741 30607 ParameterClient2.cpp:114] pserver 0 10.103.205.28:7164
I0909 22:39:29.286900 30607 ParameterClient2.cpp:114] pserver 1 10.103.205.28:7165
I0909 22:39:29.286965 30607 ParameterClient2.cpp:114] pserver 2 10.103.205.29:7164
I0909 22:39:29.287005 30607 ParameterClient2.cpp:114] pserver 3 10.103.205.29:7165
I0909 22:39:31.287415 31305 ParameterClient2.cpp:367] send thread 0 started
I0909 22:39:31.287449 31306 ParameterClient2.cpp:397] recv thread 0 started
I0909 22:39:31.287572 31307 ParameterClient2.cpp:367] send thread 1 started
I0909 22:39:31.287590 31308 ParameterClient2.cpp:397] recv thread 1 started
I0909 22:39:31.287629 31309 ParameterClient2.cpp:367] send thread 2 started
I0909 22:39:31.287657 31310 ParameterClient2.cpp:397] recv thread 2 started
I0909 22:39:31.287708 31311 ParameterClient2.cpp:367] send thread 3 started
I0909 22:39:31.287747 31312 ParameterClient2.cpp:397] recv thread 3 started

同机上pserver的log如下：
I0909 22:28:05.182811 25152 Util.cpp:166] commandline: /home/paddle/usr/local/bin/../opt/paddle/bin/paddle_pserver_main --num_gradient_servers=2 --nics=xgbe0 --port=7164 --ports_num=2 --ports_num_for_sparse=2 --comment=paddle_process_by_paddle
I0909 22:28:05.183393 25152 ParameterServerController.cpp:83] number of parameterServer instances: 4
I0909 22:28:05.183408 25152 ParameterServerController.cpp:87] Starting parameterServer[0]
I0909 22:28:05.183456 25152 ParameterServerController.cpp:87] Starting parameterServer[1]
I0909 22:28:05.183487 25152 ParameterServerController.cpp:87] Starting parameterServer[2]
I0909 22:28:05.183519 25153 LightNetwork.cpp:269] tcp server start
I0909 22:28:05.183547 25152 ParameterServerController.cpp:87] Starting parameterServer[3]
I0909 22:28:05.183548 25154 LightNetwork.cpp:269] tcp server start
I0909 22:28:05.183574 25155 LightNetwork.cpp:269] tcp server start
I0909 22:28:05.183596 25152 ParameterServerController.cpp:96] Waiting parameterServer[0]
I0909 22:28:05.183641 25156 LightNetwork.cpp:269] tcp server start
I0909 22:33:00.767719 21214 LightNetwork.cpp:322] worker started, peer = 10.103.205.29
I0909 22:33:00.767720 21215 LightNetwork.cpp:322] worker started, peer = 10.103.205.29
I0909 22:39:25.705513 21214 LightNetwork.cpp:339] worker begin to finish, peer = 10.103.205.29
I0909 22:39:25.705513 21215 LightNetwork.cpp:339] worker begin to finish, peer = 10.103.205.29
I0909 22:39:25.705566 21214 SocketChannel.cpp:42] destory connection in socket channel, peer = 10.103.205.29
I0909 22:39:25.705569 21215 SocketChannel.cpp:42] destory connection in socket channel, peer = 10.103.205.29
I0909 22:39:29.287078 30718 LightNetwork.cpp:322] worker started, peer = 10.103.205.29
I0909 22:39:29.287088 30719 LightNetwork.cpp:322] worker started, peer = 10.103.205.29

**Comment by typhoonzero** [comment]
Maybe you specified `--num_gradient_servers=2` but you start only one trainer.
