### ISSUE TITLE
集群训练的时候，每台机器上的训练数据是不同的么？

### ISSUE THREAD

**Issue by thomaslwang** [PaddlePaddle/Paddle#3992]
集群训练的时候，每台机器上的训练数据是不同的么？
比如两台机器参加集群训练，训练数据总共有1000条，测试数据总共有100条。
那在每台机器上放置500条训练数据和50条测试数据，对么？

**Comment by thomaslwang** [comment]
1. Paddle有没有自动分发数据的机制？
比如，全部1000条训练数据和100条测试数据都在trainer_id=0的机器上，启动trainer后，自动分出500条训练数据和50条测试数据到另一台训练机器上。
2. 测试数据需要分发到集群每台机器上么？

**Comment by thomaslwang** [comment]
还有一个问题，
3. 训练完成（所有pass都训练完了）之后，pserver虽然还在后台运行，但是已经不能再次训练是吧？我再次训练的时候，总是报错，需要把pserver都kill掉重启，才能开始新的训练。我想知道这是不是正常的。

**Comment by NHZlX** [comment]
一二问题可以参照https://github.com/PaddlePaddle/Paddle/issues/788  ， 第三个问题， 麻烦@Yancey1989  回复一下

**Comment by Yancey1989** [comment]
Hi @thomaslwang 是自己启动的集群训练吗? 
训练完成之后是要停掉所有Parameter Server的进程的，因为要清空Parameter Server上的参数数据。

**Comment by thomaslwang** [comment]
是自己起的。明白，多谢
