### ISSUE TITLE
paddle 0.10安装包

### ISSUE THREAD

**Issue by supermanhuyu** [PaddlePaddle/Paddle#3994]
0.10  这个版本没有Ubuntu的安装包了吗，还是只能源码编译？ 当然用docker是好的，但是我现在是想要把paddle做到 一个容器中，而这个容器中只是一个Ubuntu系统，有安装包就可以直接安装了。

**Comment by luotao1** [comment]
0.10.0版本没有Ubuntu的安装包。可以用docker安装编译或者源码安装编译。
