### ISSUE TITLE
国外机器安装paddlepaddle-gpu==2.2.2缓慢

### ISSUE THREAD

**Issue by surfola** [PaddlePaddle/Paddle#39998]
- 标题：国外机器paddlepaddle-gpu安装缓慢 容易超时
- 版本、环境信息：

PaddlePaddle版本：paddlepaddle-gpu==2.2.2

- 安装方式信息：
conda安装，采用以下命令

`conda install paddlepaddle-gpu==2.2.2 cudatoolkit=10.2 --channel https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/Paddle/`

如果取消清华镜像源会显示无法找到对应包：
PackagesNotFoundError: The following packages are not available from current channels:
-paddlepaddle-gpu==2.2.2

**Comment by nemonameless** [comment]
您好，可以尝试获取conda install 后显示的下载链接，复制链接用其他方式去下载到whl包，再conda install whl包。

**Comment by surfola** [comment]
感谢回复！在这里找到了，记录一下：https://anaconda.org/Paddle/paddlepaddle-gpu/files

**Comment by nemonameless** [comment]
https://paddleinference.paddlepaddle.org.cn/user_guides/download_lib.html 这里也有~
