### ISSUE TITLE
采用docker安装paddle，dockerhub内找不到该镜像

### ISSUE THREAD

**Issue by caiwd** [PaddlePaddle/Paddle#40006]
- [](我按照官方教程“https://www.paddlepaddle.org.cn/install/quick?docurl=/documentation/docs/zh/install/docker/linux-docker.html”使用docker安装paddle的时候，执行“docker) pull registry.baidubce.com/paddlepaddle/paddle:2.2.2”命令无反应，在dockerhub“https://hub.docker.com/r/paddlepaddle/paddle”上搜索不到paddle镜像，不知什么原
![Snipaste_2022-02-28_21-58-21](https://user-images.githubusercontent.com/24253858/155998462-3900065f-e111-42ac-bcd2-d0ef5abd0475.png)
因[](我按照官方教程“https://www.paddlepaddle.org.cn/install/quick?docurl=/documentation/docs/zh/install/docker/linux-docker.html”使用docker安装paddle的时候，执行“docker) pull registry.baidubce.com/paddlepaddle/paddle:2.2.2”命令无反应，在dockerhub“https://hub.docker.com/r/paddlepaddle/paddle”上搜索不到paddle镜像，不知什么原因

**Comment by nemonameless** [comment]
您好，请搜索paddlepaddle。 https://hub.docker.com/r/paddlepaddle/paddle 是这个页面，看你需要具体拉取某个Tag，比如 ```docker pull paddlepaddle/paddle:2.2.2``` 。

**Comment by caiwd** [comment]
> 您好，请搜索paddlepaddle。 https://hub.docker.com/r/paddlepaddle/paddle 是这个页面，看你需要具体拉取某个Tag，比如 `docker pull paddlepaddle/paddle:2.2.2` 。

非常感谢您的建议，目前已经顺利解决该问题。

**Comment by caiwd** [comment]
补充一下解决方案，供后来者参考：
由于我的linux系统中的docker不是在root用户下操作，导致pull无反应，需要将当前用户添加到docker组，并重启系统。参考该连接：https://zhuanlan.zhihu.com/p/387937931
