### ISSUE TITLE
RuntimeError: (PreconditionNotMet) Cannot load cudnn shared library. Cannot invoke method cudnnGetVersion.

### ISSUE THREAD

**Issue by JacksonH333** [PaddlePaddle/Paddle#40009]
![Uploading QQ图片20220301093200.png…](
为使您的问题得到快速解决，在建立Issue前，请您先通过如下方式搜索是否有相似问题:【搜索issue关键字】【使用labels筛选】【官方文档】

建立issue时，为快速解决问题，请您根据使用情况给出如下信息：
- 标题：请包含关键词“安装错误”/“编译错误”，例如“Mac编译错误”
- 版本、环境信息：
    1）PaddlePaddle版本：请提供您的PaddlePaddle版本号（如1.1）或CommitID
    2）CPU：请提供CPU型号，MKL/OpenBlas/MKLDNN/等数学库的使用情况
    3）GPU：请提供GPU型号，CUDA和CUDNN版本号
    4）系统环境：请说明系统类型、版本（如Mac OS 10.14）、Python版本
注：您可以通过执行[summary_env.py](https://github.com/PaddlePaddle/Paddle/blob/develop/tools/summary_env.py)获取以上信息。
- 安装方式信息：
1）pip安装/docker安装
2）本地编译：请提供cmake命令，编译命令
3）docker编译：请提供docker镜像，编译命令            
  特殊环境请注明：如离线安装等
- 复现信息：如为报错，请给出复现环境、复现步骤
- 问题描述：请详细描述您的问题，同步贴出报错信息、日志/代码关键片段

Thank you for contributing to PaddlePaddle.
Before submitting the issue, you could search issue in Github in case that there was a similar issue submitted or resolved before.
If there is no solution,please make sure that this is an installation issue including the following details:
**System information**
-PaddlePaddle version （eg.1.1）or CommitID
-CPU: including CPUMKL/OpenBlas/MKLDNN version
-GPU: including CUDA/CUDNN version
-OS Platform (eg. Mac OS 10.14)
-Python version
- Install method: pip install/install with docker/build from source(without docker)/build within docker
- Other special cases that you think may be related to this problem, eg. offline install, special internet condition 
Note: You can get most of the information by running [summary_env.py](https://github.com/PaddlePaddle/Paddle/blob/develop/tools/summary_env.py).   

**To Reproduce**
Steps to reproduce the behavior
**Describe your current behavior**
**Code to reproduce the issue**
**Other info / logs**

- 版本、环境信息：
    1）PaddlePaddle版本：PaddlePaddle2.2.0
    2）CPU：请提供CPU型号，MKL/OpenBlas/MKLDNN/等数学库的使用情况
    3）GPU：GeForce RTX 2080Ti，CUDA 11.5 和CUDNN 8.3.1.22
    4）系统环境：window 专业版 20H2 、Python3.7.3
- 安装方式信息：
1）pip安装

- 复现信息：
- RuntimeError: (PreconditionNotMet) Cannot load cudnn shared library. Cannot invoke method cudnnGetVersion.
  [Hint: cudnn_dso_handle should not be null.] (at /paddle/paddle/fluid/platform/dynload/cudnn.cc:59)
  [operator < uniform_random > error]
INFO 2022-02-28 08:45:19,011 launch_utils.py:341] terminate all the procs
ERROR 2022-02-28 08:45:19,012 launch_utils.py:604] ABORT!!! Out of all 1 trainers, the trainer process with rank=[0] was aborted. Please check its log.
INFO 2022-02-28 08:45:23,014 launch_utils.py:341] terminate all the procs
INFO 2022-02-28 08:45:23,015 launch.py:311] Local processes completed.
(base) yons@xhu-6a525-253:~$ tar -xvf cudnn-linux-x86_64-8.3.1.22_cuda11.5-archive.tar
tar: cudnn-linux-x86_64-8.3.1.22_cuda11.5-archive.tar: Cannot open: No such file or directory
tar: Error is not recoverable: exiting now
(base) yons@xhu-6a525-253:~$ tar -xvf cudnn-11.5-linux-x86-v8.3.1.22.tgz
tar: cudnn-11.5-linux-x86-v8.3.1.22.tgz: Cannot open: No such file or directory
tar: Error is not recoverable: exiting now

**Comment by weisy11** [comment]
你好，请检查一下cudnn库。

**Comment by weisy11** [comment]
由于长时间未回复，卡片关闭。如果问题没有解决，可以重新打开卡片。

**Comment by yysirs** [comment]
> 你好，请检查一下cudnn库。

请问怎么检查？

**Comment by WangShengguang** [comment]
> 你好，请检查一下cudnn库。

遇到同样的问题。使用pytorch可以正常使用，但是paddle不可以

**Comment by frensher** [comment]
> > 你好，请检查一下cudnn库。
> 
> 遇到同样的问题。使用pytorch可以正常使用，但是paddle不可以

你好,解决了吗   我也遇到了  torch可以,paddle不可以

**Comment by axuu** [comment]
> 你好，请检查一下cudnn库。

检查什么啊，怎么检查，你们就是这样做开源的吗。几千个 issue 没人解决，按照文档上所有步骤都检查了也跑步起来。大厂 KPI 的产物还是省省吧。

**Comment by axuu** [comment]
> 你好，请检查一下cudnn库。

检查什么啊，怎么检查，你们就是这样做开源的吗。几千个 issue 没人解决，按照文档上每个步骤都试了，跑了就是一堆错误。大厂 KPI 的产物还是省省吧。
