### ISSUE TITLE
RTX3090 预测慢

### ISSUE THREAD

**Issue by fujunhao411** [PaddlePaddle/Paddle#40021]
RTX3090显卡在视频预测时fps过低。
（1）Paddle版本为2.2.2
（2）GPU：RTX 3090，CUDA11.2 CUDNN 8.2，完全对应的官方版本，24G显存
（3）系统环境：W10，Python版本：3.8
（4）CPU：I9-10920X
（5）模型：PP-Tracking中的行人检测模型，MOT17.官方预训练模型，并非自己训练的模型。出问题了以后使用的官方模型进行的实测。
（6）预测视频：实时视频流，输入fps为25，模型预测输出fps为8
（7）同样代码、同样模型情况下，2070显卡搭配CUDA10.2，模型预测输出为30+

已调整过的CUDA版本：11.0、11.1、11.2，三者fps分别为：8.05、8.55、8.89
依据官方CUDA版本要求，只支持至11.2，则未进行11.4等更新的版本测试。

预测过程中：GPU使用2.2G，CPU使用8%，并未出现爆内存的情况。
麻烦各位大佬帮忙分析下，具体问题出在了哪里，8fps无法应对实时视频流传输需求。而且相同条件下，2070的预测速率比3090的要快4倍，感觉有问题。

**Comment by fujunhao411** [comment]
问题补充：
同样代码、同样模型，在1660Ti搭配CUDA10.2上，fps达到22-25。
代码采用的均为官方实例代码，并未进行改动。
需要专业人士讲解是否是 Paddle对30系显卡的支持性有些许的问题。
后续将进行CUDA11.3、11.4等高版本测试，按官方说明Paddle最高支持版本为11.2，所以不清楚是否能够顺利运行。

**Comment by weisy11** [comment]
你好，PP-Tracking系列模型使用的问题请在PaddleDetection咨询，会有专门负责同学解答，谢谢。
https://github.com/PaddlePaddle/PaddleDetection

**Comment by fujunhao411** [comment]
那请问，Paddle对CUDA11.4的支持性如何？是否支持11.2以上高版本CUDA

**Comment by fujunhao411** [comment]
> 你好，PP-Tracking系列模型使用的问题请在PaddleDetection咨询，会有专门负责同学解答，谢谢。 https://github.com/PaddlePaddle/PaddleDetection
那请问，Paddle对CUDA11.4的支持性如何？是否支持11.2以上高版本CUDA

**Comment by weisy11** [comment]
> > 你好，PP-Tracking系列模型使用的问题请在PaddleDetection咨询，会有专门负责同学解答，谢谢。 https://github.com/PaddlePaddle/PaddleDetection
> > 那请问，Paddle对CUDA11.4的支持性如何？是否支持11.2以上高版本CUDA

目前暂没有官方支持的发布版本。

**Comment by fujunhao411** [comment]
> > > 你好，PP-Tracking系列模型使用的问题请在PaddleDetection咨询，会有专门负责同学解答，谢谢。 https://github.com/PaddlePaddle/PaddleDetection
> > > 那请问，Paddle对CUDA11.4的支持性如何？是否支持11.2以上高版本CUDA
> 
> 目前暂没有官方支持的发布版本。

自行编译的版本是否支持？

**Comment by weisy11** [comment]
> > > > 你好，PP-Tracking系列模型使用的问题请在PaddleDetection咨询，会有专门负责同学解答，谢谢。 https://github.com/PaddlePaddle/PaddleDetection
> > > > 那请问，Paddle对CUDA11.4的支持性如何？是否支持11.2以上高版本CUDA
> > 
> > 
> > 目前暂没有官方支持的发布版本。
> 
> 自行编译的版本是否支持？

我们没有测试过。

**Comment by jim19930609** [comment]
你好，我们这边目前怀疑是GPU架构的问题。

Paddle目前CUDA11.x的发布包，里面编译的GPU架构为sm_80，而RTX3090对应的是sm_86。虽然CUDA的架构兼容性允许我们拿80架构的代码在86上跑，但是性能会有问题。

我们应该月底会发布2.3rc版本的发布包，里面会编入sm_86架构，应该可以解决你的问题。如果到时候性能提升依然不能满足要求，我们会进一步往里分析。

**Comment by fujunhao411** [comment]
> 你好，我们这边目前怀疑是GPU架构的问题。
> 
> Paddle目前CUDA11.x的发布包，里面编译的GPU架构为sm_80，而RTX3090对应的是sm_86。虽然CUDA的架构兼容性允许我们拿80架构的代码在86上跑，但是性能会有问题。
> 
> 我们应该月底会发布2.3rc版本的发布包，里面会编入sm_86架构，应该可以解决你的问题。如果到时候性能提升依然不能满足要求，我们会进一步往里分析。

您好，那能麻烦问下RTX3060对应的sm值是多少么

**Comment by galigaygaywa** [comment]
> 我们应该月底会发布2.3rc版本的发布包，里面会编入sm_86架构，应该可以解决你的问题。如果到时候性能提升依然不能满足要求，我们会进一步往里分析。

请问发布了吗？

**Comment by Ligoml** [comment]
> > 我们应该月底会发布2.3rc版本的发布包，里面会编入sm_86架构，应该可以解决你的问题。如果到时候性能提升依然不能满足要求，我们会进一步往里分析。
> 
> 请问发布了吗？

v2.3 已经在5月底正式发布，可以试一下哈

**Comment by Rhett98** [comment]
这是来自QQ邮箱的自动回复邮件。你好，我已收到你的邮件，我查看后会尽快给你回复。
