### ISSUE TITLE
How to debug prediction error when using capi interface.

### ISSUE THREAD

**Issue by Jarlonyan** [PaddlePaddle/Paddle#4003]
```c++
paddle_gradient_machine_forward(machine, in_args, out_args, false);
paddle_matrix prob=paddle_matrix_create_none();
paddle_arguments_get_value(out_args, 0, prob);
paddle_real* array;
int code=paddle_matrix_get_row(prob, 0, &array);
```
模型加载成功，输入类型也OK，但是 paddle_matrix_get_row 返回错误码:1。这个1代表什么意思？有哪些可能的原因导致的呢？

**Comment by hedaoyuan** [comment]
> 这个1代表什么意思？

错误码的定义在这里，https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/capi/error.h#L23，
返回1表示`prob`包含一个空指针数据，prob不正确的原因可能是`paddle_gradient_machine_forward`或`paddle_arguments_get_value`执行已经失败了，所以可以check上面两句的返回值。

**Comment by Jarlonyan** [comment]
```
paddle_arguments_set_value, return_code=0
paddle_gradient_machine_forward, return_code=1
paddle_arguments_get_value, return code=2
paddle_matrix_get_row, return_code=1
```
为啥报错说我paddle_gradient_machine_forward是用了空指针？？

**Comment by hedaoyuan** [comment]
> 为啥报错说我paddle_gradient_machine_forward是用了空指针？？

paddle_gradient_machine_forward return 1的问题可以看源码中的逻辑，
https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/capi/gradient_machine.cpp#L104 。
check一下machine, in_args, out_args这几个参数。

**Comment by Jarlonyan** [comment]
```c++
455     long size;
456     void* buf = read_config(CONFIG_BIN, &size);
457     std::cout<<"read dnn_config.bin ok"<<std::endl;
458
459     // Create a gradient machine for inference.
460     paddle_gradient_machine machine;
461     paddle_gradient_machine_create_for_inference(&machine, buf, (int)size);
```
machine创建失败。返回空指针。。

**Comment by hedaoyuan** [comment]
`paddle_gradient_machine_create_for_inference`接口返回是正确（0）还是失败？至少可以看一下是哪个分支导致的machine创建失败
https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/capi/gradient_machine.cpp#L41
