### ISSUE TITLE
paddle.v2.event.TestResult(evaluator, cost)中的 cost 的含义是什么？

### ISSUE THREAD

**Issue by lk1ngaa7** [PaddlePaddle/Paddle#4004]
class paddle.v2.event.TestResult(evaluator, cost)
![image](https://user-images.githubusercontent.com/5397716/30260300-1fba9f44-96f9-11e7-973e-5b8733f9d1a0.png)
cost 的含义是什么？

**Comment by hedaoyuan** [comment]
这里的cost就是每个batch结束，paddle中的cost function计算结果。
比如这一章中的cost就是最那层classification_cost计算的结果
https://github.com/PaddlePaddle/book/blob/21b503bc96c447aa05d1904513f874511290940c/02.recognize_digits/train.py#L83

**Comment by lk1ngaa7** [comment]
@hedaoyuan 非常感谢，问题解决了，我再多看看 book 的内容
