### ISSUE TITLE
IVector_create错误

### ISSUE THREAD

**Issue by zhoulingyun2017** [PaddlePaddle/Paddle#4006]
NotImplementedError: Wrong number or type of arguments for overloaded function 'IVector_create'.
  Possible C/C++ prototypes are:
    IVector::create(std::vector< int,std::allocator< int > > const &,bool)
    IVector::create(std::vector< int,std::allocator< int > > const &)

[utils.txt](https://github.com/PaddlePaddle/Paddle/files/1291562/utils.txt)
[train.txt](https://github.com/PaddlePaddle/Paddle/files/1291564/train.txt)
[reader.txt](https://github.com/PaddlePaddle/Paddle/files/1291563/reader.txt)
[network_conf.txt](https://github.com/PaddlePaddle/Paddle/files/1291565/network_conf.txt)

我的input_data是：每行以\t分割的数据，intention相当于文本分类例子中的label，wordseg相当于文本分类例子中的word
intention	wordseg
寻找候选	大众 丰田 车型 大全 图片 
寻找候选	福特 汽车 报价 大全 8 万 
寻找候选	和 哈弗 h2 同 级别 的 车型 推荐 
寻找候选	丰田 越野 车 大全 价格 图片 
如何执行	本田 自动 驻 车 好 用 吗

**Comment by zhoulingyun2017** [comment]
wordseg列是按空格分割的

**Comment by hedaoyuan** [comment]
可以check `reader=reader.train_reader(train_data_dir, word_dict, lbl_dict)`和`reader=lambda: paddle.dataset.imdb.test(word_dict)`时，`reader()`调用返回的内容格式。

**Comment by zhoulingyun2017** [comment]
找到问题了，在找词在词典中位置时候没有记录unknown的情况，默认返回的是None，这里会导致报错！需改成：word_dict.get(w.decode('utf-8'), UNK_ID)
