### ISSUE TITLE
NameError: name 'GLOG_logtostderr' is not defined

### ISSUE THREAD

**Issue by zjgtan** [PaddlePaddle/Paddle#401]
when i try run.sh in recommendation demo, the exception of "NameError: name 'GLOG_logtostderr' is not defined" is occured. The exception is raised in ( File "<string>", line 11, in <module> ). 

thank you

**Comment by gangliao** [comment]
Please post the detail error information in here, thanks.

**Comment by reyoung** [comment]
Are you running a shell script by `python`?? @zjgtan
