### ISSUE TITLE
paddle Tensor高级索引访问出错

### ISSUE THREAD

**Issue by phoenixsfly** [PaddlePaddle/Paddle#40106]
欢迎您对PaddlePaddle提出建议，非常感谢您对PaddlePaddle的贡献！
在留下您的建议时，辛苦您同步提供如下信息：
- 版本、环境信息
1）PaddlePaddle版本：2.2
2）CPU/GPU：ALL
3）系统环境：Linux/Windows

---
- 问题1：
例如我需要访问tensor中第3行和第0行中第1至3列的数据，在numpy/pytorch中可以这么写：
```python
x=torch.rand(4,5)
x[[3,0],1:4]
```
但是在paddle中会出错：
```python
x=paddle.rand([4,5])
x[[3,0],1:4]

ValueError: (InvalidArgument) When index contains a list, its length is excepted to 1, but received 2
  [Hint: Expected size == 1, but received size:2 != 1:1.] (at ..\paddle\fluid\pybind\imperative.cc:599)
```
换句话说paddle不支持列表索引和切片索引的混合使用进行访问/赋值，但这在numpy和pytorch中都是支持的，

- 建议描述：
  该需求非常常见，希望能够得到支持

**Comment by minghaoBD** [comment]
谢谢您的反馈！

我们已经记录下您的建议，后续会及时更新进展到这里～

**Comment by Ss-shuang123** [comment]
蹲 有无解决
