### ISSUE TITLE
ValueError: label should not out of bound, but gotTensor(shape=[1], dtype=int64, place=CUDAPlace(0), stop_gradient=True,        [29]

### ISSUE THREAD

**Issue by AceGuoX** [PaddlePaddle/Paddle#40103]
- 版本、环境信息：
    1）PaddlePaddle版本：2.2.2.post101
    4）系统环境：aistudio
 注：您可以通过执行[summary_env.py](https://github.com/PaddlePaddle/Paddle/blob/develop/tools/summary_env.py)获取以上信息。
- 训练信息
    1）单机，单卡
    2）15.8

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
/tmp/ipykernel_653/2397052834.py in <module>
     33             save_freq=300,       #保存模型的频率，多少个 epoch 保存一次模型
     34             log_freq=20,     #日志打印的频率，多少个 step 打印一次日志
---> 35             shuffle=True)

/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/hapi/model.py in fit(self, train_data, eval_data, batch_size, epochs, eval_freq, log_freq, save_dir, save_freq, verbose, drop_last, shuffle, num_workers, callbacks, accumulate_grad_batches, num_iters)
   1730         for epoch in range(epochs):
   1731             cbks.on_epoch_begin(epoch)
-> 1732             logs = self._run_one_epoch(train_loader, cbks, 'train')
   1733             cbks.on_epoch_end(epoch, logs)
   1734 

/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/hapi/model.py in _run_one_epoch(self, data_loader, callbacks, mode, logs)
   2060                                    step + 1 == len(data_loader))
   2061 
-> 2062                 outs = getattr(self, mode + '_batch')(*_inputs)
   2063 
   2064                 if self._metrics and self._loss:

/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/hapi/model.py in train_batch(self, inputs, labels, update)
   1059               print(loss)
   1060         """
-> 1061         loss = self._adapter.train_batch(inputs, labels, update)
   1062         if fluid.in_dygraph_mode() and self._input_info is None:
   1063             self._update_inputs()

/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/hapi/model.py in train_batch(self, inputs, labels, update)
    714                     *[to_variable(x) for x in inputs])
    715 
--> 716             losses = self.model._loss(*(to_list(outputs) + labels))
    717             losses = to_list(losses)
    718             final_loss = fluid.layers.sum(losses)

/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py in __call__(self, *inputs, **kwargs)
    915 
    916     def __call__(self, *inputs, **kwargs):
--> 917         return self._dygraph_call_func(*inputs, **kwargs)
    918 
    919     def forward(self, *inputs, **kwargs):

/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py in _dygraph_call_func(self, *inputs, **kwargs)
    905             self._built = True
    906 
--> 907         outputs = self.forward(*inputs, **kwargs)
    908 
    909         for forward_post_hook in self._forward_post_hooks.values():

/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/nn/layer/loss.py in forward(self, input, label)
    404             axis=self.axis,
    405             use_softmax=self.use_softmax,
--> 406             name=self.name)
    407 
    408         return ret

/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/nn/functional/loss.py in cross_entropy(input, label, weight, ignore_index, reduction, soft_label, axis, use_softmax, name)
   1660             if label_max >= input.shape[axis]:
   1661                 raise ValueError("label should not out of bound, but got{}".
-> 1662                                  format(label_max))
   1663 
   1664         _, out = _C_ops.softmax_with_cross_entropy(

ValueError: label should not out of bound, but gotTensor(shape=[1], dtype=int64, place=CUDAPlace(0), stop_gradient=True,
       [29])

![图片](https://user-images.githubusercontent.com/38156085/156483695-a86d05e1-1759-4e02-aed3-0d3f4a3d5984.png)

**Comment by gongel** [comment]
check下 构建数据集时的标签范围

**Comment by AceGuoX** [comment]
def&nbsp;get_data(dirpath):
&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;获取所有文件并进行标记
&nbsp;&nbsp;&nbsp;&nbsp;all_list&nbsp;=&nbsp;[]
&nbsp;&nbsp;&nbsp;&nbsp;val_list&nbsp;=&nbsp;[]
&nbsp;&nbsp;&nbsp;&nbsp;num_data_lenth&nbsp;=&nbsp;0&nbsp;&nbsp;#&nbsp;标记总文件数量
&nbsp;&nbsp;&nbsp;&nbsp;all_list_lenth&nbsp;=&nbsp;0&nbsp;&nbsp;#&nbsp;标记文件类别
&nbsp;&nbsp;&nbsp;&nbsp;val_list_lenth&nbsp;=&nbsp;0
&nbsp;&nbsp;&nbsp;&nbsp;for&nbsp;root,&nbsp;dirs,&nbsp;files&nbsp;in&nbsp;os.walk(dirpath):&nbsp;&nbsp;#&nbsp;分别代表根目录、文件夹、文件
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;for&nbsp;file&nbsp;in&nbsp;files:
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;num_data_lenth&nbsp;=&nbsp;num_data_lenth&nbsp;+&nbsp;1
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;local_id&nbsp;=&nbsp;int(re.search('''_.*_''',&nbsp;str(file)).group()[1:-1])
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;if&nbsp;local_id&nbsp;!=&nbsp;6:
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;label_id&nbsp;=&nbsp;re.search('''^[0-9]+''',&nbsp;str(file)).group()
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;imgpath&nbsp;=&nbsp;os.path.join(root,&nbsp;file)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;all_list.append(imgpath&nbsp;+&nbsp;"&nbsp;"&nbsp;+&nbsp;str(label_id)&nbsp;+&nbsp;"\n")
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;all_list_lenth&nbsp;=&nbsp;all_list_lenth&nbsp;+&nbsp;1
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;else:
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;label_id&nbsp;=&nbsp;re.search('''^[1-9]+''',&nbsp;str(file)).group()
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;imgpath&nbsp;=&nbsp;os.path.join(root,&nbsp;file)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;val_list.append(imgpath&nbsp;+&nbsp;"&nbsp;"&nbsp;+&nbsp;str(label_id)&nbsp;+&nbsp;"\n")
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;val_list_lenth&nbsp;=&nbsp;val_list_lenth&nbsp;+&nbsp;1

&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;all_list,val_list,num_data_lenth,all_list_lenth,

def&nbsp;get_dataset(dirpath):
&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;获取训练集、测试集
&nbsp;&nbsp;&nbsp;&nbsp;random.seed(8)
&nbsp;&nbsp;&nbsp;&nbsp;all_list,val_list,num_data_lenth,all_list_lenth=&nbsp;get_data(dirpath)
&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;打乱数据
&nbsp;&nbsp;&nbsp;&nbsp;random.shuffle(all_list)

&nbsp;&nbsp;&nbsp;&nbsp;train_size&nbsp;=&nbsp;int(all_list_lenth&nbsp;*&nbsp;0.8)
&nbsp;&nbsp;&nbsp;&nbsp;train_list&nbsp;=&nbsp;all_list[:train_size]
&nbsp;&nbsp;&nbsp;&nbsp;text_list&nbsp;=&nbsp;all_list[train_size:]
&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;生成训练集txt
&nbsp;&nbsp;&nbsp;&nbsp;train_txt&nbsp;=&nbsp;''.join(train_list)
&nbsp;&nbsp;&nbsp;&nbsp;f_train&nbsp;=&nbsp;open('{}train_list.txt'.format(dirpath),'w',encoding='utf-8')
&nbsp;&nbsp;&nbsp;&nbsp;f_train.write(train_txt)
&nbsp;&nbsp;&nbsp;&nbsp;f_train.close()
&nbsp;&nbsp;&nbsp;&nbsp;print("train_list.txt&nbsp;生成成功！")

&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;生成测试集txt
&nbsp;&nbsp;&nbsp;&nbsp;text_txt&nbsp;=&nbsp;''.join(text_list)
&nbsp;&nbsp;&nbsp;&nbsp;f_val&nbsp;=&nbsp;open('{}text_list.txt'.format(dirpath),'w',encoding='utf-8')
&nbsp;&nbsp;&nbsp;&nbsp;f_val.write(text_txt)
&nbsp;&nbsp;&nbsp;&nbsp;f_val.close()
&nbsp;&nbsp;&nbsp;&nbsp;print("text_list.txt&nbsp;生成成功！")

&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;#生成验证集
&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;val_txt&nbsp;=&nbsp;''.join(val_list)
&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;f_val&nbsp;=&nbsp;open('{}val_list.txt'.format(dirpath),'w',encoding='utf-8')
&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;f_val.write(val_txt)
&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;f_val.close()
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;train_list,&nbsp;text_list

def&nbsp;get_all_dataset(dirpath1,dirpath2):
&nbsp;&nbsp;&nbsp;&nbsp;altrain_list,altext_list=get_dataset(dirpath1)
&nbsp;&nbsp;&nbsp;&nbsp;aptrain_list,aptext_list=get_dataset(dirpath2)
&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;合并数据集
&nbsp;&nbsp;&nbsp;&nbsp;altrain_list.extend(altext_list)
&nbsp;&nbsp;&nbsp;&nbsp;aptrain_list.extend(aptext_list)


&nbsp;&nbsp;&nbsp;&nbsp;train_list=[]
&nbsp;&nbsp;&nbsp;&nbsp;text_list&nbsp;=[]
&nbsp;&nbsp;&nbsp;&nbsp;ppp&nbsp;=[]

&nbsp;&nbsp;&nbsp;&nbsp;for&nbsp;i&nbsp;in&nbsp;range(1,30):
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;lall_list=[]
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;pall_list=[]
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;for&nbsp;j&nbsp;in&nbsp;altrain_list:
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(int(j.strip().split("&nbsp;")[1])==&nbsp;i):
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;lall_list.append(j)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;for&nbsp;j&nbsp;in&nbsp;aptrain_list:
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;int(j.strip().split("&nbsp;")[1])&nbsp;==&nbsp;i:
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;pall_list.append(j)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;temp_ltrain_size&nbsp;=&nbsp;int(len(lall_list)&nbsp;*0.8)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;temp_ltrain_list&nbsp;=&nbsp;lall_list[:temp_ltrain_size]
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;temp_ltext_list&nbsp;=&nbsp;lall_list[temp_ltrain_size:]

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;temp_ptrain_size&nbsp;=&nbsp;int(len(pall_list)&nbsp;*0.8)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;temp_ptrain_list&nbsp;=&nbsp;pall_list[:temp_ptrain_size]
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;temp_ptext_list&nbsp;=&nbsp;pall_list[temp_ptrain_size:]

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;for&nbsp;j&nbsp;in&nbsp;range(len(temp_ptrain_list)):
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;train_list.append("{}&nbsp;{}&nbsp;{}\n".format(temp_ptrain_list[j].strip().split("&nbsp;")[0],&nbsp;temp_ltrain_list[j%len(temp_ltrain_list)].strip().split("&nbsp;")[0],&nbsp;temp_ptrain_list[j].strip().split("&nbsp;")[1]))
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;for&nbsp;j&nbsp;in&nbsp;range(len(temp_ptext_list)):
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;text_list.append("{}&nbsp;{}&nbsp;{}\n".format(temp_ptext_list[j].strip().split("&nbsp;")[0],&nbsp;temp_ltext_list[j%len(temp_ltrain_list)].strip().split("&nbsp;")[0],&nbsp;temp_ptext_list[j].strip().split("&nbsp;")[1]))

&nbsp;&nbsp;&nbsp;&nbsp;print(len(train_list),len(text_list))
&nbsp;&nbsp;&nbsp;&nbsp;random.shuffle(train_list)
&nbsp;&nbsp;&nbsp;&nbsp;random.shuffle(text_list)

&nbsp;&nbsp;&nbsp;&nbsp;#生成训练集
&nbsp;&nbsp;&nbsp;&nbsp;train_txt&nbsp;=&nbsp;''.join(train_list)
&nbsp;&nbsp;&nbsp;&nbsp;f_train&nbsp;=&nbsp;open('train_list.txt','w',encoding='utf-8')
&nbsp;&nbsp;&nbsp;&nbsp;f_train.write(train_txt)
&nbsp;&nbsp;&nbsp;&nbsp;f_train.close()
&nbsp;&nbsp;&nbsp;&nbsp;print("train_list.txt&nbsp;生成成功！")

&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;生成测试集txt
&nbsp;&nbsp;&nbsp;&nbsp;text_txt&nbsp;=&nbsp;''.join(text_list)
&nbsp;&nbsp;&nbsp;&nbsp;f_val&nbsp;=&nbsp;open('text_list.txt','w',encoding='utf-8')
&nbsp;&nbsp;&nbsp;&nbsp;f_val.write(text_txt)
&nbsp;&nbsp;&nbsp;&nbsp;f_val.close()
&nbsp;&nbsp;&nbsp;&nbsp;print("text_list.txt&nbsp;生成成功！")
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;train_list,text_list



class&nbsp;MyDataset(Dataset):
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;__init__(self,&nbsp;data,&nbsp;mode='train'):
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;super(MyDataset,&nbsp;self).__init__()
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self.data&nbsp;=&nbsp;data
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self.mode&nbsp;=&nbsp;mode
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self.transform&nbsp;=&nbsp;Compose([
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;T.RandomResizedCrop(224,scale=(0.8,&nbsp;1),ratio=(1,&nbsp;1)),
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;T.RandomHorizontalFlip(),
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;T.RandomVerticalFlip(),
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;T.Normalize(mean=[127.5,&nbsp;127.5,&nbsp;127.5],&nbsp;std=[127.5,&nbsp;127.5,&nbsp;127.5],&nbsp;data_format='HWC'),
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;T.ToTensor()
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;])

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self.transform1&nbsp;=&nbsp;Compose([
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;T.Resize(size=(224,&nbsp;224)),
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;T.Normalize(mean=[127.5,&nbsp;127.5,&nbsp;127.5],&nbsp;std=[127.5,&nbsp;127.5,&nbsp;127.5],&nbsp;data_format='HWC'),
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;T.ToTensor()
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;])
&nbsp;&nbsp;&nbsp;&nbsp;
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;__getitem__(self,&nbsp;index):
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;limg_path&nbsp;=&nbsp;self.data[index][0]
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;pimg_path&nbsp;=&nbsp;self.data[index][1]
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;img_l&nbsp;=&nbsp;Image.open(limg_path)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;img_p&nbsp;=&nbsp;Image.open(pimg_path)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;img_l.mode&nbsp;!=&nbsp;'RGB':
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;img_l&nbsp;=&nbsp;img_l.convert('RGB')
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;img_p.mode&nbsp;!=&nbsp;'RGB':
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;img_p&nbsp;=&nbsp;img_p.convert('RGB')
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;self.mode&nbsp;==&nbsp;'train':
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;img_1&nbsp;=&nbsp;self.transform(img_l)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;img_2&nbsp;=&nbsp;self.transform(img_p)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;else:
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;img_1&nbsp;=&nbsp;self.transform1(img_l)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;img_2&nbsp;=&nbsp;self.transform1(img_p)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;label&nbsp;=&nbsp;self.data[index][2]
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;label&nbsp;=&nbsp;np.array([label],&nbsp;dtype="int64")
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;img_1,&nbsp;img_2,&nbsp;label

&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;__len__(self):
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;len(self.data)


这个是我的数据集构建的代码



共有29个种类，标签有29个，分别1~29



------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/Paddle"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年3月3日(星期四) 上午10:29
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PaddlePaddle/Paddle] ValueError: label should not out of bound, but gotTensor(shape=[1], dtype=int64, place=CUDAPlace(0), stop_gradient=True,        [29] (Issue #40103)





 
check下 构建数据集时的标签范围
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by AceGuoX** [comment]
共有29个种类，标签有29个，分别1~29
没找到问题在哪





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/Paddle"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年3月3日(星期四) 上午10:29
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PaddlePaddle/Paddle] ValueError: label should not out of bound, but gotTensor(shape=[1], dtype=int64, place=CUDAPlace(0), stop_gradient=True,        [29] (Issue #40103)





 
check下 构建数据集时的标签范围
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by minghaoBD** [comment]
听起来感觉把[1, 29]改成[0, 28]即可，不然这个判断不能满足（https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/nn/functional/loss.py#L1672 ）。

如果还有问题，麻烦提供一个复现代码，谢谢～

**Comment by AceGuoX** [comment]
> 听起来感觉把[1, 29]改成[0, 28]即可，不然这个判断不能满足（https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/nn/functional/loss.py#L1672 ）。
> 
> 如果还有问题，麻烦提供一个复现代码，谢谢～

已解决，谢谢

**Comment by sk8boi** [comment]
你好，我在使用 paddle.nn.functional.cross_entropy遇到同样问题。
因为labels的index序列和标签本身设定是要相同的，所以我在使用四位数字的Id作为标签类名时，会出现同样的错误，只好将四位数的Id映射到序列上面避免这个错误，请问这部分还有更好的优化方法吗？如果我还想继续使用四位数的标签的话。

**Comment by minghaoBD** [comment]
你好 @sk8boi 

1. 关于label使用范围的问题，文档中要求
![image](https://user-images.githubusercontent.com/79566150/157614749-227de388-9e51-4b73-9cb5-88c1ccc89be3.png)
且代码中是有强判断：https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/nn/functional/loss.py#L1672
2. 这么做是考虑到更通用的场景，例如：string类型的类别等。建议1）写一个简单的映射函数 2）调用sklearn.preprocessing.LabelEncoder一键转换与反转换。
