### ISSUE TITLE
Dataloader报错后会卡死

### ISSUE THREAD

**Issue by x54-729** [PaddlePaddle/Paddle#40127]
您好，我今天在使用PaddlePaddle进行初步的训练的时候有两个问题：
1. 第一个是对于教程中给出的MNIST训练样例，使用paddle.vision.datasets.MNIST(mode='train')获取数据集后执行如下代码：
```python
import paddle
from paddle.io import DataLoader
train_dataset = paddle.vision.datasets.MNIST(mode='train')
dataloader = DataLoader(train_dataset, batch_size=100, shuffle=True)
for img, label in dataloader:
    pass
```
因为是错误的用法，因此程序会因为数据类型不对报错，但之后程序会卡死，按ctrl C也无法退出，只能强行kill掉；请问这个问题应该怎么解决？
2. 第二个问题是针对PaddlePaddle对反向传播处理的情况，请问PaddlePaddle是只有在张量进行了计算的情况话才会计算梯度吗？比如下面的代码，单独对张量x进行反向传播，其梯度为None，而进行计算后其梯度则是存在的；这一点因为和pytorch不太一样，所以想询问一下张量梯度为None的条件
```python
import paddle
x = paddle.to_tensor([2.0], stop_gradient=False)
x.backward()
print(x.grad)
# None
x = paddle.to_tensor([2.0], stop_gradient=False) + 1
x.backward()
print(x.grad)
# Tensor(shape=[1], dtype=float32, place=CUDAPlace(0), stop_gradient=False,[1.])
```
麻烦各位老师了！

**Comment by minghaoBD** [comment]
您好：

问题1正确的做法是可以终止的，加一个backend='cv2'即可，我试过了中间ctrl-C可以立刻终止。

关于问题2，请问您是有什么需求吗？
1. 一个tensor不经过计算，直接拿出他的梯度，这种场景不是特别多的常见呢。
2. 如果有具体的需求，可以描述一下，我们跟进解决下哈～

**Comment by minghaoBD** [comment]
@x54-729 请问关于iterabledataset您还有什么建议吗？
