### ISSUE TITLE
昆仑R200在ubuntu1804操作系统下，可以安装paddle环境吗？

### ISSUE THREAD

**Issue by yqsoooo** [PaddlePaddle/Paddle#40123]
RT ，
![image](https://user-images.githubusercontent.com/15975613/156522302-1076569c-eb18-4b02-bc62-004edd7d3740.png)

**Comment by minghaoBD** [comment]
您好，看官网是没有ubuntu环境的whl包的，具体原因我们内部查一下，有进展及时反馈～

**Comment by yqsoooo** [comment]
在线等  挺急的

**Comment by adaxiadaxi** [comment]
@yqsoooo 请问您的python版本是多少呢，我们有x86+linux+kl的whl包

**Comment by yqsoooo** [comment]
> @yqsoooo 请问您的python版本是多少呢，我们有x86+linux+kl的whl包

python 版本我可以根据需要修改 我会安装一个2.6 和3.7

**Comment by adaxiadaxi** [comment]
@yqsoooo 您好，我是飞桨和kl2适配的负责产品经理，目前我们有ubuntu+x86+昆仑k100上的whl包，针对r200和飞桨的适配工作还在进行，预计3月底会在2.3rc版本发包。如果有需要您可以加我微信：15704308458 我们详细对对您的诉求，以及看看我们怎么支持您这边
