### ISSUE TITLE
paddlepaddle2.2.2检测安装是否成功paddle.utils.run_check()的时候一直卡住(超过20分钟)

### ISSUE THREAD

**Issue by xiulianzw** [PaddlePaddle/Paddle#40120]
为使您的问题得到快速解决，在建立Issue前，请您先通过如下方式搜索是否有相似问题:【搜索issue关键字】【使用labels筛选】【官方文档】

建立issue时，为快速解决问题，请您根据使用情况给出如下信息：
- 标题：请包含关键词“安装错误”/“编译错误”，例如“Mac编译错误”
- 版本、环境信息：
    1）PaddlePaddle版本：paddlepaddle-gpu          2.2.2.post112
    2）CPU：请提供CPU型号，MKL/OpenBlas/MKLDNN/等数学库的使用情况
    3）GPU：请提供GPU型号，CUDA11.2和CUDNN8.1.1
    4）系统环境：Ubuntu16.04

- 安装方式信息：
1）pip安装
     
  特殊环境请注明：如离线安装等
- 复现信息：如为报错，请给出复现环境、复现步骤
- 问题描述：paddle.utils.run_check()一直卡住
>>> import paddle
>>> paddle.utils.run_check()
Running verify PaddlePaddle program ... 
W0303 15:43:16.388672 10956 device_context.cc:362] Please NOTE: device: 0, GPU Compute Capability: 8.6, Driver API Version: 11.2, Runtime API Version: 11.0
W0303 15:43:16.415441 10956 device_context.cc:372] device: 0, cuDNN Version: 7.6.
W0303 15:43:32.404167 10956 device_context.h:245] WARNING: device: 0. The installed Paddle is compiled with CUDNN 8.0, but CUDNN version in your machine is 7.6, which may cause serious incompatible bug. Please recompile or reinstall Paddle with compatible CUDNN version.

很奇怪我安装的cudnn明明是8.1.1，因为系统中有多个cuda的版本，环境变量如下:
echo $CUDA_HOME
/usr/local/cuda-11.2

echo $LD_LIBRARY_PATH
/usr/local/cuda-11.2/lib64:/usr/local/lib:/root/anaconda3/lib

echo $PATH
/root/anaconda3/bin:/usr/local/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/usr/local/cuda-11.2/bin

**Comment by minghaoBD** [comment]
可以参照相似问题尝试一下：
https://github.com/PaddlePaddle/Paddle/issues/39256
https://github.com/PaddlePaddle/Paddle/issues/39154
https://github.com/PaddlePaddle/Paddle/issues/38934

**Comment by xiulianzw** [comment]
发现问题，因为我的服务器上有两张显卡，GPU0是RTX 3090，GPU1是RTX 2070 super，如果我在终端使用export CUDA_VISIBLE_DEVICES=1，然后再去检查很快就能出结果，如果使用的是0的话就会一直卡住。RTX 3090在cuda11以上应该是可以使用的？

**Comment by xiulianzw** [comment]
解决了，安装cuda11.1的，别安装cuda11.2
