### ISSUE TITLE
TypeError: can't pickle paddle.fluid.core_avx.PaddleInferPredictor objects

### ISSUE THREAD

**Issue by BeyondYourself** [PaddlePaddle/Paddle#40135]
在本地多进程预测服务的时候出现：
`TypeError: can't pickle paddle.fluid.core_avx.PaddleInferPredictor objects`

paddle版本为2.2.1版本
windows环境。
使用的是multiprocess进行预测
求助大家解决一下问题

**Comment by AceGuoX** [comment]
已解决，问题出在数据集的标签上，我的29分类数据集标签是1~29，将标签改为0~28，问题就解决了

**Comment by AceGuoX** [comment]
已解决，问题出在数据集的标签上，我的29分类数据集标签是1到29，将标签改为0到28，问题就解决了

**Comment by b3602sss** [comment]
请提供一下单测代码谢谢

**Comment by hengshan123** [comment]
我也遇到这个问题了，楼主解决了吗

**Comment by lmw0320** [comment]
> 在本地多进程预测服务的时候出现： `TypeError: can't pickle paddle.fluid.core_avx.PaddleInferPredictor objects`
> 
> paddle版本为2.2.1版本 windows环境。 使用的是multiprocess进行预测 求助大家解决一下问题

请教下，我也遇到相同问题了，楼主解决了么？？
我用threading,Thread是可以用的，但是感觉没有提速。。所以想用多进程看看是否可以提速。。结果报错。。。头大。。

**Comment by BeyondYourself** [comment]
> 也遇到相同问题了，楼主解决了么？？
> 我用threading,Thread是可以用的，但是感觉没有提速。。所以想用多进程看看是否可以提速。。结果报错。。。头大。。

还没 有解决

**Comment by simon-sxx** [comment]
@lmw0320 @BeyondYourself 请问解决了吗

**Comment by ooyuanyuan** [comment]
我也遇到了这个问题，请问现在有解决方案了吗？
paddleocr.__version__
Out[3]: '2.5.0.3'

**Comment by weirman** [comment]
paddlepaddle version ： 2.3.1 
未解决

**Comment by singo27** [comment]
> 

我遇到了相同的问题， 但排查后发现是我自己的错误。
大概是这样的：

**Comment by singo27** [comment]
我遇见了同样的问题，但排查代码后发现是我的基础知识出现了遗忘， 导致使用方法出现了错误。
```python
import argparse
import signal
from multiprocessing import Event, Process, Queue
from multiprocessing.synchronize import Event as EVT
import PaddleOCR
def str2bool(v):
    return v.lower() in ("true", "t", "1")
class PpOcr:
    STATUS = False
    event: EVT
    queue: Queue
    def __init__(self, event, queue) -> None:
        self.event = event
        self.queue = queue
        parser = argparse.ArgumentParser()
        self.ppocr = PaddleOCR(**parser.parse_args().__dict__)
        signal.signal(signal.SIGABRT, self.__close__)
    def __close__(self) -> None:
        self.STATUS = False
    def run(self) -> None:
        return self.__call__()
    def __call__(self) -> None:
        pass
if __name__ == "__main__":
    event = Event
    queue = Queue(maxsize=10)
    ppocr = PpOcr(event, queue)
    pid = Process(target=ppocr.run, args=())
    pid.start()
```

当我修改为这样

```python
if __name__ == "__main__":
    event = Event
    queue = Queue(maxsize=10)
    pid = Process(target=PpOcr, args=(event, queue))
    pid.start()
```
代码可以正常运行, 希望对你有帮助

**Comment by hin7141** [comment]
not solved yet

**Comment by hin7141** [comment]
> 

@singo27  how can you target a class

**Comment by singo27** [comment]
> > 
> 
> @singo27 how can you target a class
You need implement class.__call__

**Comment by wangqiang9** [comment]
python多进程使用pickle在子进程之间串行化和传输数据。
Pickle无法序列化本地（内部）函数。可以尝试将目标设置为从文件的命名空间可见的函数。
https://stackoverflow.com/questions/70422581/python-multiprocessing-basic-cant-pickle-local-object-and-ran-out-of-input

**Comment by leeway28** [comment]
使用from concurrent import futures，paddle taskflow对应功能的初始化要在提交的函数里面进行，就不会报错

**Comment by Irfan-S-1** [comment]
Is this issue resolve i am getting same issue as 

TypeError: cannot pickle 'paddle.fluid.core_avx.PaddleInferPredictor' object
