### ISSUE TITLE
paddlepaddle所要的numpy版本与imageio所要的numpy版本冲突了怎么办？

### ISSUE THREAD

**Issue by Rookie619** [PaddlePaddle/Paddle#40142]
paddlepaddle 2.2.0 requires numpy<=1.19.3,>=1.13;
imageio 2.4.0需要numpy大于1.20.0;
该怎么办？
安装顺序都试过了，还不行。

**Comment by minghaoBD** [comment]
您好

如果一定要用imageio==2.4.0版本要求numpy>1.20.0的话，可以用develop版本的paddle，已经去掉了numpy版本上限的约束（https://github.com/PaddlePaddle/Paddle/blob/develop/python/requirements.txt#L2 ）

对应安装教程：https://www.paddlepaddle.org.cn/install/quick?docurl=/documentation/docs/zh/develop/install/pip/windows-pip.html
