### ISSUE TITLE
ubuntu源码编译paddle报错：”Unsupported gpu architecture 'compute_86“

### ISSUE THREAD

**Issue by Nepths** [PaddlePaddle/Paddle#40155]
采用的是docker编译
docker镜像为：paddlepaddle/paddle:latest-dev-cuda11.0-cudnn8-gcc82
paddle版本为：release 2.2
主机上的cuda版本为11.6
GPU型号为：RTX3070
设置了环境变量：export CUDA_ARCH_NAME=Ampere
cmake命令为： cmake .. -DPY_VERSION=3.7 -DWITH_GPU=ON -DWITH_TESTING=OFF -DCMAKE_BUILD_TYPE=Release -DWITH_MKL=OFF
make命令为： make TARGET=NEHALEM -j$(nproc)  (加TARGET=NEHALEM是为了解决OpenBlas的问题)

报错信息：
![image](https://user-images.githubusercontent.com/29809006/156707268-ee2f129d-bdf9-4b56-8514-3d6642d5d4f1.png)

**Comment by lyuwenyu** [comment]
看错误是nvcc的问题 ，  你使用的的cuda的版本是多少，建议使用11+以上的

> https://forums.developer.nvidia.com/t/nvcc-fatal-unsupported-gpu-architecture-compute-86/161424
