### ISSUE TITLE
paddle V2如何关闭掉大部分的info日志，只保留错误日志

### ISSUE THREAD

**Issue by youan1** [PaddlePaddle/Paddle#4015]
RT:
paddle v2的train.log中有大量的下载文件等日志，如何关闭，是改配置文件py，还是在提交任务时关闭，谢谢！

**Comment by hedaoyuan** [comment]
> 大量的下载文件等日志

下载文件的日志是python中的代码吧？修改一下python？

**Comment by youan1** [comment]
不是python中的代码， python中的代码没有任何答应下载日志的

**Comment by hedaoyuan** [comment]
看起来也不像是paddle的log。可能是某个工具打印的，需要再check一下。

**Comment by typhoonzero** [comment]
这个日志是receiver的脚本中打印的，还有一些是hadoop client打印的，你如果是用package提交，可以直接改下这些脚本就行。如果是receiver提交就先保持现状吧，有时候也需要debug下载时的错误。如果要过滤某些日志可以把日志文件下载之后本地grep下。

**Comment by youan1** [comment]
我是用receiver提交，所以现在没有办法去掉这些信息，是吧，另外日志文件太大，一个多G，下载非常慢

**Comment by typhoonzero** [comment]
我可以线下发你一个package使用。先close此issue了。
