### ISSUE TITLE
paddle inference gpu版本设置成cpu运行会出错

### ISSUE THREAD

**Issue by zgq91** [PaddlePaddle/Paddle#40157]
paddle inference版本windows: cuda11.0_cudnn8.0_avx_mkl_trt7；跑gpu时没问题但在跑cpu时 predict->run()会报以下错误。

WARNING: Logging before InitGoogleLogging() is written to STDERR
I0304 14:11:58.563257 28276 analysis_predictor.cc:644] MKLDNN is enabled
e[1me[35m--- Running analysis [ir_graph_build_pass]e[0m
e[1me[35m--- Running analysis [ir_graph_clean_pass]e[0m
e[1me[35m--- Running analysis [ir_analysis_pass]e[0m
e[32m--- Running IR pass [mkldnn_placement_pass]e[0m
e[32m--- Running IR pass [simplify_with_basic_ops_pass]e[0m
e[32m--- Running IR pass [layer_norm_fuse_pass]e[0m
e[37m---    Fused 0 subgraphs into layer_norm op.e[0m
e[32m--- Running IR pass [attention_lstm_fuse_pass]e[0m
e[32m--- Running IR pass [seqconv_eltadd_relu_fuse_pass]e[0m
e[32m--- Running IR pass [seqpool_cvm_concat_fuse_pass]e[0m
e[32m--- Running IR pass [mul_lstm_fuse_pass]e[0m
e[32m--- Running IR pass [fc_gru_fuse_pass]e[0m
e[37m---    fused 0 pairs of fc gru patternse[0m
e[32m--- Running IR pass [mul_gru_fuse_pass]e[0m
e[32m--- Running IR pass [seq_concat_fc_fuse_pass]e[0m
e[32m--- Running IR pass [squeeze2_matmul_fuse_pass]e[0m
e[32m--- Running IR pass [reshape2_matmul_fuse_pass]e[0m
e[32m--- Running IR pass [flatten2_matmul_fuse_pass]e[0m
e[32m--- Running IR pass [map_matmul_v2_to_mul_pass]e[0m
e[32m--- Running IR pass [map_matmul_v2_to_matmul_pass]e[0m
e[32m--- Running IR pass [map_matmul_to_mul_pass]e[0m
e[32m--- Running IR pass [fc_fuse_pass]e[0m
e[32m--- Running IR pass [repeated_fc_relu_fuse_pass]e[0m
e[32m--- Running IR pass [squared_mat_sub_fuse_pass]e[0m
e[32m--- Running IR pass [conv_bn_fuse_pass]e[0m
I0304 14:11:58.647657 28276 fuse_pass_base.cc:57] ---  detected 24 subgraphs
e[32m--- Running IR pass [conv_eltwiseadd_bn_fuse_pass]e[0m
e[32m--- Running IR pass [conv_transpose_bn_fuse_pass]e[0m
e[32m--- Running IR pass [conv_transpose_eltwiseadd_bn_fuse_pass]e[0m
I0304 14:11:58.654875 28276 fuse_pass_base.cc:57] ---  detected 1 subgraphs
e[32m--- Running IR pass [is_test_pass]e[0m
e[32m--- Running IR pass [runtime_context_cache_pass]e[0m
e[32m--- Running IR pass [depthwise_conv_mkldnn_pass]e[0m
e[32m--- Running IR pass [conv_bn_fuse_pass]e[0m
e[32m--- Running IR pass [conv_eltwiseadd_bn_fuse_pass]e[0m
e[32m--- Running IR pass [conv_affine_channel_fuse_pass]e[0m
e[32m--- Running IR pass [conv_eltwiseadd_affine_channel_fuse_pass]e[0m
e[32m--- Running IR pass [conv_transpose_bn_fuse_pass]e[0m
e[32m--- Running IR pass [conv_transpose_eltwiseadd_bn_fuse_pass]e[0m
e[32m--- Running IR pass [conv_bias_mkldnn_fuse_pass]e[0m
e[32m--- Running IR pass [conv_transpose_bias_mkldnn_fuse_pass]e[0m
I0304 14:11:58.671098 28276 fuse_pass_base.cc:57] ---  detected 2 subgraphs
e[32m--- Running IR pass [conv3d_bias_mkldnn_fuse_pass]e[0m
e[32m--- Running IR pass [conv_elementwise_add_mkldnn_fuse_pass]e[0m
I0304 14:11:58.692750 28276 conv_elementwise_add_mkldnn_fuse_pass.cc:408] Fused graph 5
I0304 14:11:58.692750 28276 fuse_pass_base.cc:57] ---  detected 5 subgraphs
e[32m--- Running IR pass [conv_concat_relu_mkldnn_fuse_pass]e[0m
e[32m--- Running IR pass [conv_relu_mkldnn_fuse_pass]e[0m
I0304 14:11:58.700984 28276 fuse_pass_base.cc:57] ---  detected 17 subgraphs
e[32m--- Running IR pass [conv_leaky_relu_mkldnn_fuse_pass]e[0m
e[32m--- Running IR pass [conv_relu6_mkldnn_fuse_pass]e[0m
e[32m--- Running IR pass [conv_swish_mkldnn_fuse_pass]e[0m
e[32m--- Running IR pass [conv_hard_swish_mkldnn_fuse_pass]e[0m
e[32m--- Running IR pass [scale_matmul_fuse_pass]e[0m
e[37m---    fused 0 scale with matmule[0m
e[32m--- Running IR pass [reshape_transpose_matmul_mkldnn_fuse_pass]e[0m
e[37m---    Fused 0 ReshapeTransposeMatmulMkldnn patternse[0m
e[37m---    Fused 0 ReshapeTransposeMatmulMkldnn patterns with transpose's xshapee[0m
e[37m---    Fused 0 ReshapeTransposeMatmulMkldnn patterns with reshape's xshapee[0m
e[37m---    Fused 0 ReshapeTransposeMatmulMkldnn patterns with reshape's xshape with transpose's xshapee[0m
e[32m--- Running IR pass [matmul_transpose_reshape_fuse_pass]e[0m
e[37m---    Fused 0 MatmulTransposeReshape patternse[0m
e[32m--- Running IR pass [batch_norm_act_fuse_pass]e[0m
e[37m---    fused 0 batch norm with relu activatione[0m
e[1me[35m--- Running analysis [ir_params_sync_among_devices_pass]e[0m
e[1me[35m--- Running analysis [adjust_cudnn_workspace_size_pass]e[0m
e[1me[35m--- Running analysis [inference_op_replace_pass]e[0m
e[1me[35m--- Running analysis [ir_graph_to_program_pass]e[0m
I0304 14:11:58.755321 28276 analysis_predictor.cc:714] ======= optimize end =======
I0304 14:11:58.755321 28276 naive_executor.cc:98] ---  skip [feed], feed -> x
I0304 14:11:58.758320 28276 naive_executor.cc:98] ---  skip [sigmoid_0.tmp_0], fetch -> fetch
I0304 14:11:58.760871 28276 device_context.cc:641] oneDNN v2.3.2

--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
Not support stack backtrace yet.

----------------------
Error Message Summary:
----------------------
InvalidArgumentError: out_d, out_h, out_w of Op(interpolate) should be greater than 0.
  [Hint: Expected std::all_of(out_dims.begin(), out_dims.end(), [](int i) { return i > 0; }) > 0, but received std::all_of(out_dims.begin(), out_dims.end(), [](int i) { return i > 0; }):0 <= 0:0.] (at ..\paddle/fluid/operators/mkldnn/interpolate_mkldnn_op.cc:126)

**Comment by baoachun** [comment]
您好，已收到问题，请问可以共享下你的模型吗？

**Comment by zgq91** [comment]
> 您好，已收到问题，请问可以共享下你的模型吗？

链接: https://pan.baidu.com/s/1gbJ-qILqQLCWKWXtjR4T0g 提取码: ckty 复制这段内容后打开百度网盘手机App，操作更方便哦 
--来自百度网盘超级会员v1的分享

已经放在百度网盘中了
