### ISSUE TITLE
求aarch64的paddlepaddle的python3.7版本的whl安装包，官方的自己编译的方法试了几次都失败了，求一个现成的安装包，安装在jetson系列的板子上

### ISSUE THREAD

**Issue by yanglilongss** [PaddlePaddle/Paddle#40189]

**Comment by lzzyzlbb** [comment]
https://paddleinference.paddlepaddle.org.cn/master/user_guides/download_lib.html#python 这个看一下呢

**Comment by yanglilongss** [comment]
> https://paddleinference.paddlepaddle.org.cn/master/user_guides/download_lib.html#python 这个看一下呢

谢谢，不过，这个里边只有3.6版本的，我需要3.7版本的

**Comment by wangye707** [comment]
@yanglilongss  37的暂时没有发布计划，你自己编译遇到什么问题了？

**Comment by Wei-JL** [comment]
> @yanglilongss 37的暂时没有发布计划，你自己编译遇到什么问题了？

不好意思，没看见我的问题被合并了，目前安装完成nano的系统后，自带的python版本是3.7.1，安装conda之后新建环境py3.6.9，pip导入一直显示非法指令(已转核心储存)，但新建3.7以上的环境就可以正常导入py的依赖包。但是安装3.7以上的py之后，又不能安装飞桨2.2.2 cp3.6的whl了，报错不支持导入。望能够快速解答 谢谢

**Comment by Wei-JL** [comment]
> https://paddleinference.paddlepaddle.org.cn/master/user_guides/download_lib.html#python 这个看一下呢


不好意思，没看见我的问题被合并了，目前安装完成nano的系统后，自带的python版本是3.7.1，安装conda之后新建环境py3.6.9，pip导入一直显示非法指令(已转核心储存)，但新建3.7以上的环境就可以正常导入py的依赖包。但是安装3.7以上的py之后，又不能安装飞桨2.2.2 cp3.6的whl了，报错不支持导入。望能够快速解答 谢谢

**Comment by wangye707** [comment]
@Wei-JL  最新的jetpack4.6.1+python3.7开始部署了，争取本次新版本中推出

**Comment by jiguanglu** [comment]
现在已经是最新的**jetpack5.0.2**了。。。
