### ISSUE TITLE
AIstudio使用GPU报错？？

### ISSUE THREAD

**Issue by LD826578513** [PaddlePaddle/Paddle#40190]
在使用AIstudio训练时报错，求解答

**Comment by LD826578513** [comment]
![MWBX84 OSM0(M9HV 04X_ O](https://user-images.githubusercontent.com/61733463/156888088-17c023a1-d062-4a92-8c22-7c1517881946.png)

**Comment by lzzyzlbb** [comment]
您好，您把aistudio重启一下试试呢
