### ISSUE TITLE
如何将cpu的模型放到GPU上运行，即：model.cuda() 

### ISSUE THREAD

**Issue by xu-peng-7** [PaddlePaddle/Paddle#40194]
paddle.vision.models  调用的模型，默认是在cpu上运行，速度很慢

**Comment by zh794390558** [comment]
运行程序前调用 paddle.set_device('gpu')来设置默认使用GPU。

https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/device/set_device_cn.html#set-device
