### ISSUE TITLE
如何实现基于梯度的二次求导

### ISSUE THREAD

**Issue by zhangyimi** [PaddlePaddle/Paddle#40203]
![image](https://user-images.githubusercontent.com/20926735/156958879-615ff8d4-a3b2-4526-a03c-4c250cc4431c.png)
请问loss公式中项2的right reasons该如何实现？（公式中项1为正常分类loss）
说明：N表示batch大小， D表示输入的维度，K表示输出的维度。A表示mask矩阵，值为0或1。
**即基于输出对输入求导，然后对梯度求和，并将结果加入到loss中二次求导。**

**Comment by zhiboniu** [comment]
你好，如果求导部分是公式可推导的话可以自己推一下加上，基于导数再次进行自动求导目前应该是支持不了的。
请问一下该应用具体来源是哪里？我们会慎重考虑的
