### ISSUE TITLE
check array dimension before calculating loss

### ISSUE THREAD

**Issue by HeQinWill** [PaddlePaddle/Paddle#40211]
第二组实验中 a 多了一个维度，在计算 MSE 时 paddle.substract 会启动广播机制，从而 a、b 维度都会变为 (2, 2, 2)  再做后续计算，建议计算 loss 前增加数组维度的检查并给出提醒

- 正常情况 （output 和 label 的维度一致）
```py
import numpy as np
import paddle
from sklearn.metrics import mean_squared_error
loss_fn = paddle.nn.MSELoss()

a = np.array([2.0, 4.2, 3.2, 4.7]).reshape([2, 2])
b = np.array([2.1, 4.1, 3.5, 4.9]).reshape([2, 2])
print(loss_fn(paddle.to_tensor(a), paddle.to_tensor(b)))  # 0.03750000
print(mean_squared_error(a, b))  #0.03750000
```
- 若 label 多了一个维度，程序又不报 warning，可能用户没注意会让 loss 无法正确 backward
```py
a = np.array([2.0, 4.2, 3.2, 4.7]).reshape([2, 1, 2])
b = np.array([2.1, 4.1, 3.5, 4.9]).reshape([2, 2])
print(loss_fn(paddle.to_tensor(a), paddle.to_tensor(b)))  # 0.55750000
print(mean_squared_error(a, b))  # ValueError: Found array with dim 3. Estimator expected <= 2.
```
- PyTorch 中解决方案
```py
import torch
loss_fn = torch.nn.MSELoss()
print(loss_fn(torch.from_numpy(a), torch.from_numpy(b)))  # 0.5575
# UserWarning: Using a target size (torch.Size([2, 1, 2])) that is different to the input size (torch.Size([2, 2])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.
```

**Comment by zhiboniu** [comment]
感谢反馈，经内部讨论，我们认为在 label 多了一个维度的情况下报 error 是合理的，且 paddle 的提示更简洁易懂~
欢迎后续继续为我们报体验上的问题和bug，我们也会及时同步讨论结果

**Comment by HeQinWill** [comment]
> 感谢反馈，经内部讨论，我们认为在 label 多了一个维度的情况下报 error 是合理的，且 paddle 的提示更简洁易懂~ 欢迎后续继续为我们报体验上的问题和bug，我们也会及时同步讨论结果

拜托，是 paddle 没有报 error 或 warning 啊  
从您的回复来看也应该觉得需要给用户提示吧
测试 paddle 2.3 仍然是直接给出了计算结果而已

**Comment by HeQinWill** [comment]
@zhiboniu @Ligoml 

您指的**简洁**的是 **scikit-learn** 的吧？
print(mean_squared_error(a, b))  _**# ValueError: Found array with dim 3. Estimator expected <= 2.**_

注意看下面**完全没提示的**才是 **paddlepaddle** ！
print(loss_fn(paddle.to_tensor(a), paddle.to_tensor(b)))  _**# 0.55750000**_
