### ISSUE TITLE
已将third_party全部改为国内源编译paddle,解决编译时无法访问github的问题

### ISSUE THREAD

**Issue by JiaoPaner** [PaddlePaddle/Paddle#40210]
镜像地址: git clone -b build_cn https://gitee.com/jiaopan/Paddle.git
update 2022-05-19:
https://www.zhihu.com/question/533388365 gitee也不润了. 
**目前的方案**
无法访问的仓库 手动下载 push到自建仓库 cmake/external里的.cmake改为自建仓库的地址

**Comment by zhiboniu** [comment]
很优秀的工作，非常感谢为Paddle做出的贡献，也期待能够持续合作！谢谢！

**Comment by Disciple7** [comment]
我遇到了相同问题，现在需要编译develop版本的Paddle，请问我应该怎么修改？

**Comment by JiaoPaner** [comment]
@Disciple7 将cmake/external下的文件替换成 ```https://gitee.com/jiaopan/Paddle.git```下的build_cn分支下的

**Comment by kingwpf** [comment]
好像有个包代码需要权限才能拉
fatal: Authentication failed for 'https://gitee.com/wjakob/clang-cindex-python3/'

**Comment by JiaoPaner** [comment]
@kingwpf 你编译的哪个版本？Mac ? linux? 我gitee仓库里并没有这个库

**Comment by xiaoranchenwai** [comment]
> 好像有个包代码需要权限才能拉 fatal: Authentication failed for 'https://gitee.com/wjakob/clang-cindex-python3/'

我也遇到了这个问题，你解决了么

**Comment by JiaoPaner** [comment]
本仓库https://gitee.com/jiaopan/Paddle.git 只修改了对于linux平台的paddlepaddle编译  对于mac,部分针对mac系统的包 有遇到仓库访问问题 需要自行修改三方仓库为国内的地址

**Comment by jiguanglu** [comment]
@JiaoPaner 首先非常感谢您提供此源，我用的Ubuntu18.04的版本，也遇到了 @xiaoranchenwai 他们的问题，不知道能否检查一下啊，非常感谢了。

**Comment by JiaoPaner** [comment]
@jiguanglu 编译时 是否打开了DWITH_PYTHON=ON 编译选项 先关掉试试 感觉是这个引起的 clang-cindex-python3是个python包 可否提供下编译时的详细报错信息 方便快速定位

**Comment by jiguanglu** [comment]
> @jiguanglu 编译时 是否打开了DWITH_PYTHON=ON 编译选项 先关掉试试 感觉是这个引起的 clang-cindex-python3是个python包 可否提供下编译时的详细报错信息 方便快速定位

这个倒是打开了，而且我也指定了版本3.7，好的谢谢回复，我在试试，其实我更想知道你那从哪里修改的下载源从github 换成gitee？

**Comment by JiaoPaner** [comment]
@jiguanglu 修改cmake/external下的.cmake文件

**Comment by JiaoPaner** [comment]
另外,上述问题的出现 也和这个相关 https://www.zhihu.com/question/533388365 gitee也不润了. 目前的方案:无法访问的仓库 手动下载 push到自建仓库 cmake/external里的.cmake改为自建仓库的地址

**Comment by kingwpf** [comment]
> 

我是在Mac下编译的，这个应该不是你直接依赖的包，是依赖的依赖

**Comment by kingwpf** [comment]
> @kingwpf 你编译的哪个版本？Mac ? linux? 我gitee仓库里并没有这个库


我是在Mac下编译的，这个应该不是你直接依赖的包，是依赖的依赖

**Comment by GreenHandZhu** [comment]
> > @kingwpf 你编译的哪个版本？Mac ? linux? 我gitee仓库里并没有这个库
> 
> 我是在Mac下编译的，这个应该不是你直接依赖的包，是依赖的依赖

请问这个clang-cindex-python3怎么修改下资源呀

**Comment by FlickerMi** [comment]
> > > @kingwpf 你编译的哪个版本？Mac ? linux? 我gitee仓库里并没有这个库
> > 
> > 
> > 我是在Mac下编译的，这个应该不是你直接依赖的包，是依赖的依赖
> 
> 请问这个clang-cindex-python3怎么修改下资源呀

拉这个库的build_cn分支代码：https://gitee.com/FlickerMi/Paddle
我基于 @JiaoPaner 的项目，修改了clang-cindex-python3的源为gitee了。
