### ISSUE TITLE
建议补充预训练模型

### ISSUE THREAD

**Issue by xu-peng-7** [PaddlePaddle/Paddle#40219]
paddle2.2.2 中 from paddle.vision.models 可以直接调用的模型（非模型类）包括 5个resnet模型，4个vgg模型，2个 mobileNet模型 
其中，vgg11，vgg13 没有预训练模型，建议补充。

**Comment by zhiboniu** [comment]
谢谢您的反馈，我们会找相关同学及时补充的。
