### ISSUE TITLE
A bug in module for GPU

### ISSUE THREAD

**Issue by rose-jinyang** [PaddlePaddle/Paddle#40217]
Hello
How are you?
Thanks for contributing to this project.
I found a bug in module for GPU.

The script that I ran is the  following:

import paddle
import paddle.nn.functional as F

a = paddle.randint(0, 10, (4, 4))
b = F.one_hot(a, 5)
print(a)
print(b)

The above script does NOT yield any issue when running on GPU.
But when running on CPU it yields an issue.
![image](https://user-images.githubusercontent.com/47862419/156988976-a86f7db5-3dfa-4dca-bce8-22284a3e7522.png)

**Comment by zhiboniu** [comment]
The input Tensor's element(0<x<10 here) should not bigger than class_num in API one_hot（which is 5 here）。
For more details please refer to: 
https://www.paddlepaddle.org.cn/documentation/docs/en/api/paddle/nn/functional/one_hot_en.html

**Comment by rose-jinyang** [comment]
That's right.
However, the problem is that the above script does NOT yield any issue on GPU.

**Comment by zhiboniu** [comment]
O, that is not right action on GPU, thanks for your information, we will fix this bug soonly.
