### ISSUE TITLE
In AMP training, eval prog use FP32 instead of FP16

### ISSUE THREAD

**Issue by Wong4j** [PaddlePaddle/Paddle#40216]
Thank you for contributing to PaddlePaddle.
Before submitting the issue, you could search issue in the github in case that there was a similar issue submitted or resolved before.
If there is no solution,please make sure that this is a training issue including the following details:
**System information**
-PaddlePaddle version: v2.2
-CPU: None
-GPU: V100 CUDA11.4
-OS Platform: Ubuntu 20.04
-Other imformation: None
Note: You can get most of the information by running [summary_env.py](https://github.com/PaddlePaddle/Paddle/blob/develop/tools/summary_env.py).    

**To Reproduce**
Run [RN50-static-train](https://github.com/PaddlePaddle/PaddleClas/tree/develop/ppcls/static) with [AMP-O1](https://github.com/PaddlePaddle/PaddleClas/blob/develop/ppcls/configs/ImageNet/ResNet/ResNet50_amp_O1.yaml) configuration.
Print "eval_prog" and check the log.    

**Describe your current behavior**
When testing RN50 AMP training, I found that eval program use FP32 instead of FP16, and the throughput of evaluation is much lower than training.   
This may be due to some operations being pruned during `eval_prog.clone(for_test=True)`.   
As a workaround, I can manually call [rewrite_program](https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/fluid/contrib/mixed_precision/fp16_utils.py#L545) to cast ops  to FP16 in eval prog.    
logically, train prog and eval prog are both supposed to use mixed precision in AMP training. And this issue would not only appear in RN50, but also in all AMP training with eval(test) program.     
So I think this may be a design bug.     

**Code to reproduce the issue**
Clone PaddleClas and prepare relevant training environment.
```shell
git clone https://github.com/PaddlePaddle/PaddleClas.git
```
Insert code to [train.py#L167](https://github.com/PaddlePaddle/PaddleClas/blob/develop/ppcls/static/train.py#L167)  to print program:
```python
print(train_prog)
print(eval_prog)
```
Then run training with [AMP-O1](https://github.com/PaddlePaddle/PaddleClas/blob/develop/ppcls/configs/ImageNet/ResNet/ResNet50_amp_O1.yaml) config:   
```shell
bash ./ppcls/static/run_dali.sh
```
Then check the log. In train prog, some variables are casted to "float16". But in eval prog, all variables are "float32". And the throughput of evaluation is much lower than training, which is unreasonable.

Manually call [rewrite_program](https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/fluid/contrib/mixed_precision/fp16_utils.py#L545)  here [train.py#L167](https://github.com/PaddlePaddle/PaddleClas/blob/develop/ppcls/static/train.py#L167) to cast ops  to FP16 in eval prog.  
```python
from paddle.fluid.contrib.mixed_precision.fp16_utils import rewrite_program
from paddle.fluid.contrib.mixed_precision.fp16_lists import AutoMixedPrecisionLists
rewrite_program(eval_prog, amp_lists=AutoMixedPrecisionLists())
```
Then print the eval prog and check the log. Some variables are casted to FP16 and the throughput of evaluation becomes higher than training.  This is more like the result I expected.

**Other info / logs**
In eval prog, all variables are "float32".:
![image](https://user-images.githubusercontent.com/21985950/156984636-3ad22322-1327-463c-992d-1f5b8a0082ca.png)
After rewrite eval prog, some variables are casted to "float16" according to white/black list.
![image](https://user-images.githubusercontent.com/21985950/156984658-4e216c03-9fae-4a98-82e1-309ddc3ef685.png)
![image](https://user-images.githubusercontent.com/21985950/156986571-f8d57805-0af6-4551-b9a6-8c3070649d93.png)

**Comment by zhiboniu** [comment]
Thanks for your work, it‘s important for us. We will check on that bug and fix it. Please keep attention.

**Comment by weisy11** [comment]
That's right, AMP is used to accelerate training, which has no effect in eval mode.
AMP is a lossy acceleration method, however the loss should be very slight.
**supplement**: AMP is a training accelerate method. In training phase, some operators use FP16. After training, Paddle will still save fp32 params to the model. 
If you use amp in eval phase, the inference result will be different. To avoid the accuracy difference, we still use fp32 in eval phase.

**Comment by lanxianghit** [comment]
@zhiqiu 请帮忙看一下这个问题的解决方案

**Comment by Wong4j** [comment]
This issue may cause some troubles to users.     
For example, in QAT training, we need to add some temporary variables to the program according to OPs. The added variables would be float16 type in QAT train program, and float32 type in QAT eval program. If the datatype is different, error will be reported during execution. We have to modify the name of variables and manually insert cast OP to run.

**Comment by Wong4j** [comment]
`optimizer.amp_init(..., use_fp16_test=True)`  can solve this problem.
Close this issue.

**Comment by mahesh11T** [comment]
File "C:\Users\Fstech\anaconda3\envs\aivision\lib\site-packages\paddle\fluid\dygraph\tensor_patch_methods.py", line 207, in set_value
    assert (
AssertionError: Variable dtype not match, Variable [ conv2d_0.scale_0 ] need tensor with dtype paddle.float16  but load tensor with dtype paddle.float32   

     # build optimizer in train mode
        if self.mode == 'train':
            steps_per_epoch = len(self.loader)
            if steps_per_epoch < 1:
                logger.warning(
                    "Samples in dataset are less than batch_size, please set smaller batch_size in TrainReader."
                )
            self.lr = create('LearningRate')(steps_per_epoch)
            self.optimizer = create('OptimizerBuilder')(self.lr, self.model)
            #self.optimizer.amp_init(..., use_fp16_test=True)
            #self.model.optimizer.amp_init(self.place)

whats the proper way to add it in trainer.py?

**Comment by Wong4j** [comment]
> File "C:\Users\Fstech\anaconda3\envs\aivision\lib\site-packages\paddle\fluid\dygraph\tensor_patch_methods.py", line 207, in set_value assert ( AssertionError: Variable dtype not match, Variable [ conv2d_0.scale_0 ] need tensor with dtype paddle.float16 but load tensor with dtype paddle.float32
> 
> ```
>  # build optimizer in train mode
>     if self.mode == 'train':
>         steps_per_epoch = len(self.loader)
>         if steps_per_epoch < 1:
>             logger.warning(
>                 "Samples in dataset are less than batch_size, please set smaller batch_size in TrainReader."
>             )
>         self.lr = create('LearningRate')(steps_per_epoch)
>         self.optimizer = create('OptimizerBuilder')(self.lr, self.model)
>         #self.optimizer.amp_init(..., use_fp16_test=True)
>         #self.model.optimizer.amp_init(self.place)
> ```
> 
> whats the proper way to add it in trainer.py?

Not sure if it's the same problem. Here is my code [RN50v1.5/train.py#L139](https://github.com/NVIDIA/DeepLearningExamples/blob/38934f9f26d76e9d53a456d0a2ea532e86213d66/PaddlePaddle/Classification/RN50v1.5/train.py#L139).
