### ISSUE TITLE
Require inference python API to use LodTensor GPU data as inputs

### ISSUE THREAD

**Issue by zlsh80826** [PaddlePaddle/Paddle#40250]
需求:
目前 Paddle-inference 僅支援從 CPU 拷貝, 這個限制會導致實際端到端推理不能達到最高性能
例如使用 DALI 對 raw image 做完處理後, 資料會放置在 GPU 上, 而因為 Paddle-inference 僅支援從 CPU 拷貝, 會引入多餘的 H2D, D2H 拷貝, 需要 Paddle-inference 在 python 端口支援直接從 LoDTensor 傳入或是分享輸入資料

**Comment by xingjing1** [comment]
this was solved and will publish in 2.3 rc   @JZZ-NOTE @zlsh80826

**Comment by zlsh80826** [comment]
@xingjing1 Could you share the solved PR?

**Comment by xingjing1** [comment]
https://github.com/PaddlePaddle/Paddle/pull/40513  @zlsh80826

**Comment by zlsh80826** [comment]
@xingjing1 OK, I will close this issue after #40513 merged.

**Comment by zlsh80826** [comment]
https://github.com/PaddlePaddle/Paddle/pull/41626 merged. Close this issue.

**Comment by JZZ-NOTE** [comment]
https://github.com/PaddlePaddle/Paddle/pull/41626 
pr已合入develop与2.3分支
