### ISSUE TITLE
Performance drop of retinanet_r50_fpn_1x model

### ISSUE THREAD

**Issue by pmajchrzak** [PaddlePaddle/Paddle#40269]
After commit: https://github.com/PaddlePaddle/Paddle/commit/fc06be9dbd82da832c8eed8cac8573d0166638ba
the drop of inference performance of model retinanet_r50_fpn_1x was observed.
This performance drop case is connected with a significant rising in memory consumption.
Measurements were performed using the application: 
``` 
/models/PaddleDetection/static/deploy/python/infer.py
``` 
with and without parameter "--run_benchmark=True" 

---
### CLX 
```
            Turbo: OFF
             Name: Intel(R) Xeon(R) Gold 6248 CPU @ 2.50GHz
            Model: 85
           Family: 6
          Sockets: 2
 Cores per socket: 20
 Threads per core: 2
```
![image](https://user-images.githubusercontent.com/10847947/157239048-836a819d-f439-4f9f-9a06-2519aeea1c48.png)
---
### SKX 
```
           Turbo: OFF
            Name: Intel(R) Xeon(R) Platinum 8180 CPU @ 2.50GHz
           Model: 85
          Family: 6
         Sockets: 2
Cores per socket: 28
Threads per core: 2
```
![image](https://user-images.githubusercontent.com/10847947/157239146-fafd5e53-41e7-4968-851e-61c26fd593c8.png)
---
### CPX 
```
 Turbo: OFF
            Name: Intel(R) d on(R) Gold 6348H CPU @ 2.30GHz
           Model: 85
          Family: 6
         Sockets: 4
Cores per socket: 24
Threads per core: 2
```
![image](https://user-images.githubusercontent.com/10847947/157239236-add52554-d097-48d9-a278-c241004750eb.png)

---
#### NoBenchmark
``
python /models/PaddleDetection/static/deploy/python/infer.py --model_dir=/data/PaddlePaddle/pp_models/retinanet_r50_fpn_1x --image_file=/root/models/PaddleDetection/demo/000000014439.jpg --enable_mkldnn=True
``
#### with Benchmark
``
python /models/PaddleDetection/static/deploy/python/infer.py --model_dir=/data/PaddlePaddle/pp_models/retinanet_r50_fpn_1x --image_file=/root/models/PaddleDetection/demo/000000014439.jpg --enable_mkldnn=True --run_benchmark=True
``
### CMAKE Flags:
``
-DCMAKE_BUILD_TYPE=Release -DWITH_GPU=OFF -DWITH_MKLDNN=ON -DWITH_TESTING=ON -DWITH_PROFILER=OFF -DWITH_STYLE_CHECK=OFF -DON_INFER=ON -DWITH_INFERENCE_API_TEST=ON -DINFERENCE_DEMO_INSTALL_DIR=/data/PaddlePaddle/pp_models -DPY_VERSION=3.6
``
### Environment
```
            OS: Ubuntu18.04 with mkldnn 
 cmake version: 3.10.2
      Compiler: GCC 8
```

For the attention of @jczaja @wozna

**Comment by lidanqing-vv** [comment]
@jakpiase  Hi, you will add mkldnn affine_channel later right? and it should solve this problem.

**Comment by lidanqing-vv** [comment]
Hi, this issue will be investigated starting from next quarter.

**Comment by lidanqing-vv** [comment]
@jakpiase 
This issue is casued cause Baidu deleted conv_affine_channel_pass. But we can add it into mkldnn pass. Then it should not be deleted anymore. Just like your PR, is it ?
https://github.com/PaddlePaddle/Paddle/pull/39756

**Comment by lidanqing-vv** [comment]
@piotrekobi said he will work on this issue in the following week. Thanks.

**Comment by lidanqing-vv** [comment]
#41998 is merged.
