### ISSUE TITLE
【PaddlePaddle Hackathon 2】54、在 Paddle 中实现 Common Subexpression Elimination（公共子表达式删除）的图优化 pass

### ISSUE THREAD

**Issue by TCChenlong** [PaddlePaddle/Paddle#40278]
（此 ISSUE 为 PaddlePaddle Hackathon 第二期活动的任务 ISSUE，更多详见 [【PaddlePaddle Hackathon 第二期】任务总览](https://github.com/PaddlePaddle/Paddle/issues/40234)）

【任务说明】

- 任务标题：在 Paddle 中实现 Common Subexpression Elimination（公共子表达式删除）的图优化 pass
- 技术标签：深度学习框架，C++，图优化
- 任务难度：困难
- 详细描述： 在深度学习相关的计算图中，会存在一些公共的子串，例如 h = a + b + c，f = b + a+ e，那么在整个计算图中，根据加法算子的交换律，a + b = b + a，那么我们可以将上面公式化简为 n = a + b, h = n + c ，f = n + e，这样可以减少一次 kernel 的运算，进而提升整体的执行效率。

【提交内容】

- 设计文档，并提 PR 至 [PaddlePaddle/community](https://github.com/PaddlePaddle/community) 的 rfcs/Framework 目录
- 任务 PR 到 [Paddle](https://github.com/PaddlePaddle/Paddle)
- 相关技术文档
- 任务单测文件

【技术要求】

- 熟练掌握 C++
- 熟悉图操作
- 了解 Paddle pass相关的技术背景

【答疑交流】

- 如果在开发中对于上述任务有任何问题，欢迎在本 ISSUE 下留言交流。
- 对于开发中的共性问题，在活动过程中，会定期组织答疑，请大家关注官网&QQ群的通知，及时参与。

**Comment by gsq7474741** [comment]
@chenwhql 您好，请问这个任务有在phi下对应的开发路径嘛，目前运行时的计算框架是基于fluid的还是phi呀
