### ISSUE TITLE
【PaddlePaddle Hackathon 2】50、在 Paddle 中实现1-bit Lamb 优化器

### ISSUE THREAD

**Issue by TCChenlong** [PaddlePaddle/Paddle#40282]
（此 ISSUE 为 PaddlePaddle Hackathon 第二期活动的任务 ISSUE，更多详见 [【PaddlePaddle Hackathon 第二期】任务总览](https://github.com/PaddlePaddle/Paddle/issues/40234)）

【任务说明】

- 任务标题：在 Paddle 中实现1-bit Lamb 优化器
- 技术标签：深度学习框架，C++，优化算法
- 任务难度：困难
- 详细描述： LAMB 是NLP 任务中常用的大 batch 训练优化器，目前Paddle 中已经 有 LAMB的实现。 论文 [1-bit LAMB: Communication Efficient Large-Scale Large-Batch Training with LAMB's Convergence Speed ](https://arxiv.org/abs/2104.06069)提出了对已有LAMB 优化器的改进，减少 LAMB 优化器在大规模分布式训练下时的通信量。此任务的目标是实现Paddle 中的 1-bit LAMB 优化器，并在通信量、收敛最大bathc szie、收敛精度三个指标上和论文对齐。调用路径：paddle.optimizer.OneBitLamb。

【提交内容】

- API 的设计文档，并提 PR 至 [PaddlePaddle/community](https://github.com/PaddlePaddle/community) 的 rfcs/APIs 目录
- C ++ 实现代码，在 Paddle repo 的 [paddle/fluid/operators/optimizers](https://github.com/PaddlePaddle/Paddle/tree/develop/paddle/fluid/operators/optimizers) 目录
- Python 实现代码 & 英文 API 文档，在 Paddle repo 的 [python/paddle/optimizer](https://github.com/PaddlePaddle/Paddle/tree/develop/python/paddle/optimizer) 目录
- 单测代码，在 Paddle repo 的 [python/paddle/fluid/tests/unittests](https://github.com/PaddlePaddle/Paddle/tree/develop/python/paddle/fluid/tests/unittests) 目录
- 中文API文档，在 docs repo 的 [docs/api/paddle/optimizer](https://github.com/PaddlePaddle/docs/tree/develop/docs/api/paddle/optimizer) 目录

【参考内容】

- PR: [#28772](https://github.com/PaddlePaddle/Paddle/pull/28772)
- [文档：API 贡献指南](https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/dev_guides/api_contributing_guides/api_contributing_guides_cn.html)

【技术要求】

- 了解 Paddle 动静态图下 Optimize pass过程
- 熟练掌握 C++ 、Python
- 熟悉 LAMB 优化器算法原理
- 了解论文中的Compression 原理

【答疑交流】

- 如果在开发中对于上述任务有任何问题，欢迎在本 ISSUE 下留言交流。
- 对于开发中的共性问题，在活动过程中，会定期组织答疑，请大家关注官网&QQ群的通知，及时参与。

**Comment by wanzhiqiang0812** [comment]
队名：小鸟伏特加
选定任务为：50
状态：报名
链接：https://github.com/wanzhiqiang0812/Paddle
