### ISSUE TITLE
【PaddlePaddle Hackathon 2】23、为 Paddle 新增 Softmax2D 组网API

### ISSUE THREAD

**Issue by TCChenlong** [PaddlePaddle/Paddle#40310]
（此 ISSUE 为 PaddlePaddle Hackathon 第二期活动的任务 ISSUE，更多详见 [【PaddlePaddle Hackathon 第二期】任务总览](https://github.com/PaddlePaddle/Paddle/issues/40234)）

【任务说明】

任务标题：为 Paddle 新增 Softmax2D 组网API

技术标签：深度学习框架，Python

任务难度：简单

详细描述： paddle.nn.Softmax2D 是 [paddle.nn.Softmax](https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/nn/Softmax_cn.html#softmax) 的变体，其针对 3D 或者 4D 的 tensor 在空间维度计算softmax，从而输出 tensor 在每个空间维度（channels, hj, wj）的 tensor 求和为1。此任务的目标是在 paddle 框架中新增 Softmax2D API，调用路径为：paddle.nn.Softmax2D。

【提交流程】

请按 [新增API 开发&提交流程](https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/dev_guides/api_contributing_guides/api_contributing_guides_cn.html)中的描述，完成任务提交过程中的相关步骤。

【提交内容】

- API 的设计文档，并提 PR 至 [PaddlePaddle/community](https://github.com/PaddlePaddle/community) 的 rfcs/APIs 目录。
- Python 实现代码 & 英文 API 文档，在 Paddle repo 的 [python/paddle/nn/layer/activation.py](https://github.com/PaddlePaddle/Paddle/blob/release/2.2/python/paddle/nn/layer/activation.py#L1051) 文件，新增接口初始化在[python/paddle/nn/layer/\_\_init\_\_.py](https://github.com/PaddlePaddle/Paddle/blob/release%2F2.2/python/paddle/nn/layer/__init__.py) 和 [python/paddle/nn/\_\_init\_\_.py](https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/nn/__init__.py) 。
- 单测代码，在 Paddle repo 的 [python/paddle/fluid/tests/unittests](https://github.com/PaddlePaddle/Paddle/tree/develop/python/paddle/fluid/tests/unittests) 目录。
- 中文API文档，在 docs repo 的 [docs/api/paddle](https://github.com/PaddlePaddle/docs/tree/develop/docs/api/paddle)[/nn](https://github.com/PaddlePaddle/docs/tree/develop/docs/api/paddle/nn) 目录下新建Softmax2D_cn.rst ，并修改文件[docs/api/paddle/nn/Overview_cn.rst](https://github.com/PaddlePaddle/docs/blob/develop/docs/api/paddle/nn/Overview_cn.rst)。

【合入标准】

- 1、按 [API 设计规范](https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/dev_guides/api_contributing_guides/api_design_guidelines_standard_cn.html) 完成 API设计文档；
- 2、按[API 验收标准](https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/dev_guides/api_contributing_guides/api_accpetance_criteria_cn.html)完成 API功能实现、单测、API文档；

【技术要求】

- 熟悉 Softmax2D 算法原理和适用场景；
- 熟悉 Paddle 动静态图下数学计算过程；
- 熟练掌握 Python。

【参考内容】

- PR：[#26431](https://github.com/PaddlePaddle/Paddle/pull/26431)
- [文档：API 贡献指南](https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/dev_guides/api_contributing_guides/api_contributing_guides_cn.html)

【答疑交流】

- 如果在开发中对于上述任务有任何问题，欢迎在本 ISSUE 下留言交流。
- 对于开发中的共性问题，在活动过程中，会定期组织答疑，请大家关注官网&QQ群的通知，及时参与。

**Comment by Yep1908** [comment]
【队名】：飞桨飞桨fff
【序号】：23
【状态】：报名
【链接】：https://github.com/Yep1908/Paddle

**Comment by hangchen-lab** [comment]
【队名】：xuetu_1001
【序号】：23
【状态】：报名
【链接】：https://github.com/hangchen-lab/Paddle

**Comment by yueguang1001** [comment]
【队名】：xuetu_1001
【序号】：23
【状态】：报名
【链接】：https://github.com/yueguang1001/Paddle
