### ISSUE TITLE
【PaddlePaddle Hackathon 2】8、为 Paddle 新增 nanmean API

### ISSUE THREAD

**Issue by TCChenlong** [PaddlePaddle/Paddle#40327]
（此 ISSUE 为 PaddlePaddle Hackathon 第二期活动的任务 ISSUE，更多详见 [【PaddlePaddle Hackathon 第二期】任务总览](https://github.com/PaddlePaddle/Paddle/issues/40234)）

【任务说明】

任务标题：为 Paddle 新增 nanmean API

技术标签：深度学习框架，Python

任务难度：简单

详细描述：paddle.nanmean 扩展了 paddle.mean API 的功能，如果输入Tensor中有nan值， paddle.mean在计算中会将涉及nan值的结果都置为nan，而 paddle.nanmean 会跳过nan值。比如输入数据 x = [[nan, 1. , 2. ], [3. , 4. , 5. ]]，x.mean() 得到 [nan]，x.mean(0) 得到 [nan, 2.5, 3.5]，x.nanmean() 得到 [3.]，x.nanmean(0) 得到 [3., 2.5, 3.5]。此API需支持的调用路径为：paddle.nanmean 和 Tensor.nanmean 。

【提交流程】

请按 [新增API 开发&提交流程](https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/dev_guides/api_contributing_guides/api_contributing_guides_cn.html)中的描述，完成任务提交过程中的相关步骤。

【提交内容】

- API 的设计文档，并提 PR 至 [PaddlePaddle/community](https://github.com/PaddlePaddle/community) 的 rfcs/APIs 目录
- Python 实现代码 & 英文 API 文档，在 Paddle repo 的 [python/paddle/tensor/math.py](https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/tensor/math.py) 目录，并在 python/paddle/tensor/\_\_init\_\_.py 中，添加 nanmean API，以支持 Tensor.nanmean 的调用方式；
- 单测代码，在 Paddle repo 的 [python/paddle/fluid/tests/unittests](https://github.com/PaddlePaddle/Paddle/tree/develop/python/paddle/fluid/tests/unittests) 目录
- 中文API文档，在 docs repo 的 [docs/api/paddle/](https://github.com/PaddlePaddle/docs/tree/develop/docs/api/paddle/) 目录

【合入标准】

- 1、按 [API 设计规范](https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/dev_guides/api_contributing_guides/api_design_guidelines_standard_cn.html) 完成 API设计文档；
- 2、按[API 验收标准](https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/dev_guides/api_contributing_guides/api_accpetance_criteria_cn.html)完成 API功能实现、单测、API文档；

【技术要求】

- 熟悉 paddle.nansum，paddle.isnan，paddle.logical_not，paddle.sum 这4个APi的计算逻辑
- 熟练掌握  Python

【参考内容】

- [文档：API 贡献指南](https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/dev_guides/api_contributing_guides/api_contributing_guides_cn.html)

【答疑交流】

- 如果在开发中对于上述任务有任何问题，欢迎在本 ISSUE 下留言交流。
- 对于开发中的共性问题，在活动过程中，会定期组织答疑，请大家关注官网&QQ群的通知，及时参与。

**Comment by Li-fAngyU** [comment]
要和paddle.mean()一样兼容dygraph_mode吗？
paddle.mean源码： https://github.com/PaddlePaddle/Paddle/blob/release/2.2/python/paddle/tensor/stat.py#L30

**Comment by livingbody** [comment]
> * paddle.nansum

paddle.nansum这个函数没找到啊

**Comment by TCChenlong** [comment]
> 要和paddle.mean()一样兼容dygraph_mode吗？ paddle.mean源码： https://github.com/PaddlePaddle/Paddle/blob/release/2.2/python/paddle/tensor/stat.py#L30

是的

**Comment by TCChenlong** [comment]
> > * paddle.nansum
> 
> paddle.nansum这个函数没找到啊

develop 分支下就有
