### ISSUE TITLE
【PaddlePaddle Hackathon 2】1、为 Paddle 新增 finfo API

### ISSUE THREAD

**Issue by TCChenlong** [PaddlePaddle/Paddle#40334]
（此 ISSUE 为 PaddlePaddle Hackathon 第二期活动的任务 ISSUE，更多详见 [【PaddlePaddle Hackathon 第二期】任务总览](https://github.com/PaddlePaddle/Paddle/issues/40234)）

【任务说明】

任务标题：为 Paddle 新增 finfo API

技术标签：深度学习框架，Python，C++

任务难度：中等

详细描述： finfo计算浮点数类型的数值限制，输入参数为Paddle浮点数类型(paddle.float16/paddle.float32/paddle.float64/paddle.complex64/paddle.complex128)，返回包含如下属性对象:

| 属性         | 类型    | 描述                                                                                                           |
|:---------- |:----- |:------------------------------------------------------------------------------------------------------------ |
| bits       | int   | 该类型占用的bit数                                                                                                   |
| eps        | float | 该类型所能表示的epsilon值，即满足1.0 + eps != 1.0的最小值，参考https://numpy.org/doc/stable/reference/generated/numpy.finfo.html |
| min        | float | 该类型能表示的最小值                                                                                                   |
| max        | float | 该类型能表示最大值                                                                                                    |
| tiny       | float | 该类型所能表示的最小正数                                                                                                 |
| resolution | float | 该类型十进制形式精度 `10**-precision`. 其中precision为IEEE754标准中该类型有效数字位数                                                 |

此任务目标是为Paddle新增finfo API，调用路径为paddle.finfo 。更详细内容可以参考numpy.finfo https://numpy.org/doc/stable/reference/generated/numpy.finfo.html

【提交流程】

请按 [新增API 开发&提交流程](https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/dev_guides/api_contributing_guides/api_contributing_guides_cn.html)中的描述，完成任务提交过程中的相关步骤。

【提交内容】

- API 的设计文档，并提 PR 至 [PaddlePaddle/community](https://github.com/PaddlePaddle/community) 的 rfcs/APIs 目录
- Python 实现代码 & 英文 API 文档，在 Paddle repo 的 python/paddle目录
- C ++ 实现代码，在 Paddle repo 的 paddle/phi/kernels 目录
- 单测代码，在 Paddle repo 的 [python/paddle/fluid/tests/unittests](https://github.com/PaddlePaddle/Paddle/tree/develop/python/paddle/fluid/tests/unittests) 目录
- 中文API文档，在 docs repo 的 [docs/api/paddle/](https://github.com/PaddlePaddle/docs/tree/develop/docs/api/paddle/linalg.py) 目录

【合入标准】

- 1、按 [API 设计规范](https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/dev_guides/api_contributing_guides/api_design_guidelines_standard_cn.html) 完成 API设计文档；
- 2、按[API 验收标准](https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/dev_guides/api_contributing_guides/api_accpetance_criteria_cn.html)完成 API功能实现、单测、API文档；

【技术要求】

- 熟悉 IEEE754浮点数标准
- 熟练掌握 C++ 、Python
- 熟悉C++标准库 std::numeric_limits

【参考内容】

- [文档：API 贡献指南](https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/dev_guides/api_contributing_guides/api_contributing_guides_cn.html)

【答疑交流】

- 如果在开发中对于上述任务有任何问题，欢迎在本 ISSUE 下留言交流。
- 对于开发中的共性问题，在活动过程中，会定期组织答疑，请大家关注官网&QQ群的通知，及时参与

**Comment by peter5232** [comment]
您好，我正在参加PaddlePaddle Hackathon 4，我报名了这个API实现，我参照这个文档https://github.com/PaddlePaddle/community/blob/master/rfcs/APIs/20220330_api_design_for_finfo.md,
**API实现方案**中的**在paddle/fluid/framework/Info.h与Info.cc下新增实现函数 定义class为Tinfo(借鉴Torch的结构设计，将finfo与iinfo合并为一个类进行实现)** ，这个Info.h和Info.c我都没有找到，我在https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/fluid/pybind/pybind.cc 找到了关于IInfo的定义，这句话的意思是要新建这个Info.h和Info.cc吗？

**Comment by luotao1** [comment]
close due to the following PR is merged:
- https://github.com/PaddlePaddle/Paddle/pull/50987
