### ISSUE TITLE
用fsaster_rcnn网络进行目标检测的时候，评估阶段出现了这个问题。

### ISSUE THREAD

**Issue by hellochengyan** [PaddlePaddle/Paddle#40343]
![QQ20220309-0](https://user-images.githubusercontent.com/63338183/157363485-44af7ddc-458d-4fe8-8105-69964e3372e1.png)
在调用评估接口的时候，出现了空值的问题。
具体错误如下：
          raceback (most recent call last)/tmp/ipykernel_101/1524296844.py in <module> 6 epoch_id=1, 7 metric='VOC', ----> 8 return_details=False) /opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlex/cv/models/faster_rcnn.py in evaluate(self, eval_dataset, batch_size, epoch_id, metric, return_details) 446 self.test_prog, 447 feed=[feed_data], --> 448 fetch_list=list(self.test_outputs.values()), 449 return_numpy=False) 450 res = { AttributeError: 'NoneType' object has no attribute 'values'

**Comment by Intsigstephon** [comment]
您好，麻烦提供下具体的使用环境和代码，我们后先复现下问题~
