### ISSUE TITLE
模型训练后使用visualdl保存日志进行可视化找不到对应网址

### ISSUE THREAD

**Issue by ZiJINII** [PaddlePaddle/Paddle#40348]
在终端输入visualdl --logdir ./log --port 8080后显示
Running VisualDL at http://localhost:8080/ (Press CTRL+C to quit)
Serving VisualDL on localhost; to expose to the network, use a proxy or pass --host 0.0.0.0
这个localhost是哪个ip地址，本机的还是服务器的

**Comment by Intsigstephon** [comment]
您好，按照您的操作，只需要在浏览器里面打开http://localhost:8080/ 这个地址就可以看到./log日志下保存的东西；这儿的localhost是您本机的地址

**Comment by ZiJINII** [comment]
现在是localhost:8080打不开
![image](https://user-images.githubusercontent.com/92594026/157626859-0c0be52e-0fc2-45a5-9492-90e8d738b799.png)
![image](https://user-images.githubusercontent.com/92594026/157626965-f5b0d4c2-4388-467d-b340-e1c18ed167c4.png)

**Comment by ZiJINII** [comment]
> 您好，按照您的操作，只需要在浏览器里面打开http://localhost:8080/ 这个地址就可以看到./log日志下保存的东西；这儿的localhost是您本机的地址
网址打不开

**Comment by Intsigstephon** [comment]
在你的命令后面，加上  --host 0.0.0.0 试试

**Comment by RDXiaoLu** [comment]
visualdl service upload --logdir ./output 
用这个命令就可以
