### ISSUE TITLE
集群预测任务失败

### ISSUE THREAD

**Issue by jcqu** [PaddlePaddle/Paddle#4035]
集群预测任务失败,查看log日志没有进入预测阶段，模型加载出错。
![image](https://user-images.githubusercontent.com/15798143/30310435-1e56e85e-97c3-11e7-8a03-c736526df1d0.png)
配置文件如下：
```bash
 18 key=`date -d "0 hour" +%Y%m%d%H%M%S`
 19 test_data_path="*/daily/${now_day}/testdata"
 20 model_path="*/model_file/infer_params.tar.gz"
 21 output_path="*/daily/${now_day}/output"
 22 hadoop fs -rmr $output_path
 23 hadoop fs -mkdir $output_path
 24
 25 paddle cluster_train \
 26   --config ltr_infer_online.py \
 27   --use_remote_sparse 0 \
 28   --use_gpu cpu \
 29   --port 8306 \
 30   --ports_num 8 \
 31   --time_limit 512:00:00 \
 32   --submitter ＊＊＊ \
 33   --config_args is_predict=1 \
 34   --num_nodes 20 \
 35   --job_priority normal \
 36   --fs_name *** \
 37   --fs_ugi *** \
 38   --init_model_path ${model_path} \
 39   --test_data_path ${test_data_path} \
 40   --output_path ${output_path} \
 41   --where *** \
 42   --job_name paddle_cluster_ranknet_$key
```
查看运行代码init_model_path 似乎应该是一个目录，而不是具体文件？
```python
if [ -n "${init_model_path}" ]; then
  hadoop_get_file ${HADOOP_HOME} ${fs_name} ${fs_ugi} \
                  ${init_model_path} ./init_model_path/pass-00000
  check_return "download init_model_path failed"
  mv ./init_model_path/pass-00000/* ./init_model_path/
```
请问
 conf文件中init_model_path要指定到tar.gz文件还是它的上级目录呢？ 
在python文件中，infer函数倒入模型的路径又该如何定义呢？
谢谢

**Comment by kuke** [comment]
init_model_path需要指定到tar.gz文件，infer的时候同样用的是指向tar.gz文件的模型路径

**Comment by luotao1** [comment]
预测的时候要用`--job test`。不然默认是train。

**Comment by jcqu** [comment]
@luotao1 添加--job test 参数后无法成功提交任务,    paddle为V2版本
```bash
connect to receiver:  yq01-idl-gpu-offline14.yq01.baidu.com:8090
finished to pack request
starting to submit to server
None
```
请问该如何修改
```bash
paddle cluster_train \
 27   --config ltr_infer_online.py \
 28   --use_remote_sparse 0 \
 29   --use_gpu cpu \
 30   --port 8306 \
 31   --ports_num 8 \
 32   --time_limit 512:00:00 \
 33   --submitter ### \
 34   --job test \
 35   --config_args is_predict=1 \
 36   --num_nodes 2 \
 37   --job_priority high \
 38   --fs_name ### \
 39   --fs_ugi ### \
 40   --init_model_path ${model_path} \
 41   --test_data_path ${test_data_path} \
 42   --output_path ${output_path} \
 43   --where ### \
 44   --job_name paddle_cluster_ranknet_$key
```

**Comment by luotao1** [comment]
v2 版本的不需要`--job test`，不好意思没看清楚。
指定`train_data_path`为预测数据的HDFS路径（内部wiki已更新）

**Comment by jcqu** [comment]
@kuke infer的模型路径要从具体到哪一级呢？
比如说init_model_path ＝ */pairwise/model_file/infer_params.tar.gz
那infer 打开的模型路径应该是infer_params.tar.gz 还是model_file/infer_params.tar.gz？
谢谢

**Comment by kuke** [comment]
@jcqu ```init_model_path```指向的是模型**文件**, 通过这个相对或者绝对路径能够找到文件才行

**Comment by jcqu** [comment]
@kuke 我知道啊，init_model_path ＝ */pairwise/model_file/infer_params.tar.gz 这个是hdfs路径，我想知道在python文件里头gzip.open(model_path) ,这个model_path该怎么写

**Comment by jcqu** [comment]
@luotao1 我同时提交两个任务的话，两个任务的配置文件会相互混淆？训练任务被加入了预测任务的init_model_path,预测任务的目录被覆盖了。想知道配置文件和任务是如何匹配的，为什么会出现这样的问题，该如何解决。谢谢

**Comment by typhoonzero** [comment]
@jcqu 前面您已经看到了对应下载`init_model`的脚本，其中包含：
```bash
mv ./init_model_path/pass-00000/* ./init_model_path/
```

这样每个节点的`./init_model_path/`目录就会存在指定下载的文件，在v2 程序中指定这个路径读取即可。

**Comment by jcqu** [comment]
@typhoonzero  所以在conf脚本中应当写到tar的上一级目录，而在python脚本中读取./init_model_path/my_inferparm进行预测对吗？我之前这样提交过并未成功，我先重试一遍，谢谢。

**Comment by typhoonzero** [comment]
@jcqu 对。另外如果是MPI job失败了，可以在workspace下，看下具体下载的模型是否已经存在，存在的路径，根据这个路径来修改模型读取的路径也可以。

**Comment by jcqu** [comment]
@typhoonzero 我自己现在尝试的解决办法是用hadoop命令把参数拉到节点上，然后读取，应该也可以吧。
```bash
os.system("hadoop fs -Dfs.default.name=hdfs://*:54310 -Dhadoop.job.ugi=*,* -get */model_file/infer_params.tar.gz  ./test_infer_params.tar.gz")
```

**Comment by typhoonzero** [comment]
可以的。要确保`hadoop`命令的位置是集群node的workspace下存在的路径。集群默认是不会安装hadoop客户端的。

**Comment by jcqu** [comment]
@typhoonzero  已经按后面的方法运行成功了，谢谢。咱们这些任务的文档还是该完善一下，挺简单的一件事总是要折腾很久，嘻嘻。辛苦了，祝好！
