### ISSUE TITLE
paddle.linalg文档问题module 'paddle.linalg' has no attribute 'cov'

### ISSUE THREAD

**Issue by liqitong-a** [PaddlePaddle/Paddle#40350]
在使用paddle的时候 没有这个算子

**Comment by Intsigstephon** [comment]
您好，具体是指哪个算子呢？ paddle.linalg 下没有cov 这个算子。您是指inv这个API吗

**Comment by Tongfengyu** [comment]
paddle.linalg 下没有cov这个算子吗？我看官方文档有介绍[https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/linalg/cov_cn.html#cov]，
我现在跑了一下也报错了
![1](https://user-images.githubusercontent.com/82866148/175028486-2b4e9eff-42b3-4d86-86c6-f2a5b729af69.PNG)

**Comment by SigureMo** [comment]
在这个 issue 的时候 2.3 还没有发布，2.2 应该确实是没有这个 API 的（至少 2.2 文档里是没有的）

我试了下，2.3 是有这个 API 的：

```
>>> import paddle
>>> xt = paddle.rand((3,4))
>>> paddle.linalg.cov(xt)
Tensor(shape=[3, 3], dtype=float32, place=Place(cpu), stop_gradient=True,
       [[ 0.05517013,  0.05285026, -0.01018489],
        [ 0.05285031,  0.10418469,  0.00555162],
        [-0.01018483,  0.00555162,  0.04496013]])
>>> 

```

> 我现在跑了一下也报错了

也许你用的是 2.2？

**Comment by Tongfengyu** [comment]
用的paddledetecion 2.4

**Comment by Tongfengyu** [comment]
对 我的问题，我拉取的镜像是2.2的

**Comment by Tongfengyu** [comment]
![image](https://user-images.githubusercontent.com/82866148/175228739-9fdfba8c-8885-493f-8fe2-3699c09408a5.png)
现在cov算子可以了，但是在求逆paddle.linalg.pinv这里，我的win是可以跑通的，linux报错如上
