### ISSUE TITLE
paddle的place设置问题

### ISSUE THREAD

**Issue by x54-729** [PaddlePaddle/Paddle#40380]
您好，我注意到paddle在创建张量时，其place的设置会有些许不同。
在创建张量的时候（如`to_tensor`函数），如果其`place`参数为`None`，那么该张量的Place类型是`paddle.fluid.core_avx.Place`，但这一类型和`paddle.CUDAPlace`和`paddle.CPUPlace`是不同的类型；因此我有时会因为两个张量的place成员类型不同而使程序的判断复杂化，比如我想要判断某个张量所在设备的id，我需要额外加一个if才能判断应该调用`gpu_device_id`还是`get_device_id`函数。请问这一差异有解决的可能吗？还是说在paddle中尽可能不要手动设置place参数

**Comment by Intsigstephon** [comment]
您好，paddle有一个全局的device设置函数 paddle.device.set_device()，可以指定OP运行的设备;  详情可以参考https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/device/set_device_cn.html#set-device。
