### ISSUE TITLE
The BERT model testing application is disabled. What is the current status of this model?

### ISSUE THREAD

**Issue by pmajchrzak** [PaddlePaddle/Paddle#40381]
In commit: https://github.com/PaddlePaddle/Paddle/commit/4fe465cbf27609ef1c2bdc563207f3c3f6e875fb the application for running BERT model was switched off for CPU. 
Following application stops to build:
``
/repos/paddle_paddle/build/paddle/fluid/inference/tests/api/test_analyzer_bert
``
Previously, there were reports of major drops in model performance:
https://github.com/PaddlePaddle/Paddle/issues/37075
https://github.com/PaddlePaddle/Paddle/issues/40339

More or less from the middle of last year, a slow and sometimes abrupt drop in the performance of this model can be observed. For sure, the results obtained at this time are below the performance recorded for the Release 2.2 version.
### Question
In this regard, I have a question as to whether **this model has permanently dropped out of attention or was it turned off inadvertently?**

Mentioned decrease is visible in the chart:

![image](https://user-images.githubusercontent.com/10847947/157440040-4397aa70-6818-41ad-9bfe-dcc73dbee09d.png)

Ultimately, we went down to the following results: 
![image](https://user-images.githubusercontent.com/10847947/157440141-0dfddd4f-97c5-4617-b05c-bcd137e94adb.png)

The above data was recorded with the following parameters:

### CLX processor:
```           Turbo: OFF
            Name: Intel(R) Xeon(R) Gold 6248 CPU @ 2.50GHz
           Model: 85
          Family: 6
         Sockets: 2
Cores per socket: 20
Threads per core: 2
     CPU MHx min: 1000.0000
     CPU MHx max: 3900.0000
       cache L1d: 32K
       cache L1i: 32K
        cache L2: 1024K
        cache L3: 28160K
```
### CPX processor:
```
Turbo: OFF
            Name: Intel(R) d on(R) Gold 6348H CPU @ 2.30GHz
           Model: 85
          Family: 6
         Sockets: 4
Cores per socket: 24
Threads per core: 2
     CPU MHx min: 1000.0000
     CPU MHx max: 4200.0000
       cache L1d: 32K
       cache L1i: 32K
        cache L2: 1024K
        cache L3: 33792K
```
### SKX processor
```
Turbo: OFF
            Name: Intel(R) Xeon(R) Platinum 8180 CPU @ 2.50GHz
           Model: 85
          Family: 6
         Sockets: 2
Cores per socket: 28
Threads per core: 2
     CPU MHx min: 1000.0000
     CPU MHx max: 3800.0000
       cache L1d: 32K
       cache L1i: 32K
        cache L2: 1024K
        cache L3: 39424K
```
### CMAKE parameters:
```
-DCMAKE_BUILD_TYPE=Release -DWITH_GPU=OFF -DWITH_MKLDNN=ON -DWITH_TESTING=ON -DWITH_PROFILER=OFF -DWITH_STYLE_CHECK=OFF -DON_INFER=ON -DWITH_INFERENCE_API_TEST=ON -DPY_VERSION=3.6
```
### Test run command:
```
/repos/paddle_paddle/build/paddle/fluid/inference/tests/api/test_analyzer_bert --gtest_filter=Analyzer_bert.profile --cpu_num_threads=1 --repeat=1000 -use_mkldnn=true --infer_data=/repos/paddle_paddle/build/third_party/inference_demo/bert_emb128/data.txt  --batch_size=1    --infer_model=/repos/paddle_paddle/build/third_party/inference_demo/bert_emb128/model
```
For the attention of @jczaja @wozna

**Comment by lidanqing-vv** [comment]
@piotrekobi Please investigate this initially

**Comment by piotrekobi** [comment]
@pmajchrzak
I've ran the test locally after 4 different commits and saved the results:

SHA: 704e454f1091ac355cebda09a1f23b6bfd24a99c (before the issue was first reported)
```
I0322 11:54:53.541553 4188387 helper.h:383] ====== threads: 1, thread id: 0 ======
I0322 11:54:53.541574 4188387 helper.h:385] ====== batch size: 1, iterations: 4962, repetitions: 10 ======
I0322 11:54:53.541576 4188387 helper.h:387] ====== batch latency: 2.05787ms, number of samples: 4962, sample latency: 2.05787ms, fps: 485.94, data type: float ======
[       OK ] Analyzer_bert.profile (102730 ms)
[----------] 1 test from Analyzer_bert (102730 ms total)

[----------] Global test environment tear-down
[==========] 1 test from 1 test case ran. (102730 ms total)
[  PASSED  ] 1 test.
```

SHA: b9fdd3bc0f4f22af17a81bb8a50a337b563c876b (after first report)
```
I0322 12:47:45.961434 73679 helper.h:383] ====== threads: 1, thread id: 0 ======
I0322 12:47:45.961459 73679 helper.h:385] ====== batch size: 1, iterations: 4962, repetitions: 10 ======
I0322 12:47:45.961462 73679 helper.h:387] ====== batch latency: 2.16585ms, number of samples: 4962, sample latency: 2.16585ms, fps: 461.712, data type: float ======
[       OK ] Analyzer_bert.profile (108118 ms)
[----------] 1 test from Analyzer_bert (108118 ms total)

[----------] Global test environment tear-down
[==========] 1 test from 1 test case ran. (108118 ms total)
[  PASSED  ] 1 test.
```
SHA: 45dd4a5f3b6632eea8a12dc7102c98405c7a00d9 (after second report)
```
I0322 13:41:13.233213 152355 helper.h:383] ====== threads: 1, thread id: 0 ======
I0322 13:41:13.233237 152355 helper.h:385] ====== batch size: 1, iterations: 4962, repetitions: 10 ======
I0322 13:41:13.233242 152355 helper.h:387] ====== batch latency: 2.55262ms, number of samples: 4962, sample latency: 2.55262ms, fps: 391.755, data type: float ======
[       OK ] Analyzer_bert.profile (127322 ms)
[----------] 1 test from Analyzer_bert (127322 ms total)

[----------] Global test environment tear-down
[==========] 1 test from 1 test case ran. (127322 ms total)
[  PASSED  ] 1 test.
```

SHA: 71b813f0a63d6d439d50e019482b81edde530676 (current develop after re-enabling bert on CPU)
```
I0322 14:47:38.232980 272084 helper.h:383] ====== threads: 1, thread id: 0 ======
I0322 14:47:38.233006 272084 helper.h:385] ====== batch size: 1, iterations: 4962, repetitions: 10 ======
I0322 14:47:38.233009 272084 helper.h:387] ====== batch latency: 2.48439ms, number of samples: 4962, sample latency: 2.48439ms, fps: 402.514, data type: float ======
[       OK ] Analyzer_bert.profile (123938 ms)
[----------] 1 test from Analyzer_bert (123938 ms total)

[----------] Global test environment tear-down
[==========] 1 test from 1 test case ran. (123938 ms total)
[  PASSED  ] 1 test.
```

The biggest drop in performance seems to be caused by the second reported commit - 45dd4a5f3b6632eea8a12dc7102c98405c7a00d9.
The changes made by it seem to be relatively manageable in size, so I'll try to identify why they caused the drop.

To run the test, I used the following command:
```
paddle/fluid/inference/tests/api/test_analyzer_bert --gtest_filter=Analyzer_bert.profile --cpu_num_threads=1 --repeat=10 -test_all_data -use_mkldnn=true --infer_data=third_party/inference_demo/bert_emb128/data.txt  --batch_size=1    --infer_model=third_party/inference_demo/bert_emb128/model
```

It differs from the command that you used because it uses the -test_all_data parameter. This ensures that all the data from the dataset is used. It also makes the test run much slower, so I decreased the repeat amount to 10. It still takes about 2 minutes on my machine, so this value can be lowered further. I made a PR that adds this parameter to the test command in our validation repo: https://github.com/intel-innersource/frameworks.ai.paddlepaddle.validation/pull/95

**Comment by yaomichael** [comment]
notes from 5/20 meeting

BERT may have been disabled accidently during a restructure. @jiangjiajun is confirming this and bring BERT back accordingly.
