### ISSUE TITLE
转静态图时报错 No Input(Y) found for ElementwiseOp operator

### ISSUE THREAD

**Issue by thunder95** [PaddlePaddle/Paddle#40413]
测试过paddle.slice以及切换操作，在转静态图时没有真实输入，就会报各种错。

paddle.slice(y, axes=[-1], starts=[0], ends=[2]
y[:,:,:,:, 0:2]

**Comment by Aurelius84** [comment]
您好，标题是报错在 ElementwiseOp 算子上，可否贴一下具体的报错信息，和代码上下问题，以方便定位问题？
