### ISSUE TITLE
无法在pypy下安装

### ISSUE THREAD

**Issue by cx9208** [PaddlePaddle/Paddle#40433]
在pypy3.8下运行pypy -m pip install paddlepaddle -i https://mirror.baidu.com/pypi/simple 无法直接安装，想问下是否可以支持？

**Comment by RainFrost1** [comment]
请参考安装文档：https://www.paddlepaddle.org.cn/install/quick?docurl=/documentation/docs/zh/install/pip/linux-pip.html。
如安装gpu版本，请确认cuda版本，目前pip 安装paddle2.2.2，cuda版本支持10.1、10.2、11.0、11.1、11.2。如不匹配请升级cuda版本或者使用低版本paddle
