### ISSUE TITLE
Tensor类数据是按行还是按列

### ISSUE THREAD

**Issue by zgq91** [PaddlePaddle/Paddle#40432]
您好 我想请问一下 预测获取到的Tensor类的数据假设维度1x21x40x80。数据按行还是按列读取

for(int n=0; n<21; n++)
{
     for(int i=0; i<40; i++)
     {
            for(int j=0; j<80; j++)
             {
                 int index = n*40*80 + i*80 +j;
                 float data = output_data[index];
              }
     }
}

这样索引读取对嘛

**Comment by RainFrost1** [comment]
具体指使用Paddle inference时，Tensor的数据维度吗？

**Comment by zgq91** [comment]
> 具体指使用Paddle inference时，Tensor的数据维度吗？

使用Paddle inference时
