### ISSUE TITLE
相同输入数据在paddle1.6.1预测中运行耗时不稳定，差异较大

### ISSUE THREAD

**Issue by shawnmei1880** [PaddlePaddle/Paddle#40452]
为使您的问题得到快速解决，在建立Issue前，请您先通过如下方式搜索是否有相似问题:【搜索issue关键字】【使用labels筛选】【官方文档】

如果您没有查询到相似问题，为快速解决您的提问，建立issue时请提供如下细节信息：
- 标题：简洁、精准描述您的问题，例如“最新预测库的API文档在哪儿 ”
- 版本、环境信息：
    1）PaddlePaddle版本：1.6.1
    2）CPU：预测若用CPU，请提供CPU型号，MKL/OpenBlas/MKLDNN/等数学库使用情况
                processor	: 1
               vendor_id	: GenuineIntel
              cpu family	: 6
              model		: 85
              model name	: Intel(R) Xeon(R) Gold 5117 CPU @ 2.00GHz
              stepping	: 4
              microcode	: 0x1
             cpu MHz		: 1999.742
             cache size	: 4096 KB

    3）GPU：预测若用GPU，请提供GPU型号、CUDA和CUDNN版本号
    4）系统环境：
                        Linux version 3.10.0_3-0-0-15 (root@cp01-base-for-kernel-15-6u3.epc.baidu.com) (gcc version 4.8.2 (GCC) ) #1 SMP Fri Jan 12 18:18:11 CST 2018
                        Python： 2.7.16
  
-预测信息
    1）C++预测：请您提供预测库安装包的版本信息，及其中的version.txt文件
    2）CMake包含路径的完整命令
    3）API信息（如调用请提供）
    4）预测库来源：官网下载/特殊环境（如BCLOUD编译）
- 复现信息：如为报错，请给出复现环境、复现步骤
- 问题描述：
      同一份输入数据，在上述环境上进行预测，耗时不稳定，相差几十倍，从40ms到1000ms
    具体耗时统计代码：
         s1 = time.time()
        result = self.exe.run(program=self.infer_program,
                              return_numpy=False, feed=feed_dict, fetch_list=self.target_var)
        s2 = time.time()
        print "paddle模型耗时:\t", s2-s1

Thank you for contributing to PaddlePaddle.
Before submitting the issue, you could search issue in the github in case that th
If there is no solution,please make sure that this is an inference issue including the following details :
**System information**
-PaddlePaddle version （eg.1.1）or CommitID
-CPU: including CPUMKL/OpenBlas/MKLDNN version
-GPU: including CUDA/CUDNN version
-OS Platform (eg.Mac OS 10.14)
-Python version
-Cmake orders
-C++version.txt
-API information
Note: You can get most of the information by running [summary_env.py](https://github.com/PaddlePaddle/Paddle/blob/develop/tools/summary_env.py). 
**To Reproduce**
Steps to reproduce the behavior
**Describe your current behavior**
**Code to reproduce the issue**
**Other info / logs**

**Comment by RainFrost1** [comment]
老版本已经不会进行更新，建议使用最新版本

**Comment by shawnmei1880** [comment]
请问是这个版本就会存在这个问题么

**Comment by RainFrost1** [comment]
这个不太确定，不过老版本确实可能存在一些未知的bug
