### ISSUE TITLE
paddle/fluid/core.py", line 256, in <module>     from .core_avx import * ImportError: /home/xx/anaconda3/lib/python3.8/site-packages/paddle/fluid/core_avx.so: undefined symbol: _dl_sym, version GLIBC_PRIVATE

### ISSUE THREAD

**Issue by lucasjinreal** [PaddlePaddle/Paddle#40455]
paddle/fluid/core.py", line 256, in <module>
    from .core_avx import *
ImportError: /home/xx/anaconda3/lib/python3.8/site-packages/paddle/fluid/core_avx.so: undefined symbol: _dl_sym, version GLIBC_PRIVATE

**Comment by RainFrost1** [comment]
应该是glib版本不匹配，建议使用官方镜像，请参考 https://www.paddlepaddle.org.cn/install/quick?docurl=/documentation/docs/zh/install/docker/linux-docker.html

**Comment by lucasjinreal** [comment]
I don't want using docker, any option to solve this issue?

**Comment by RainFrost1** [comment]
According to the error report, it may be a glib library problem. Upgrading glib may solve the problem. Environmental problems are difficult to locate，but using docker can easily  solve the problem.

**Comment by lucasjinreal** [comment]
@RainFrost1  what's the exactly glib version requires? I think it might because of conda.

**Comment by RainFrost1** [comment]
@jinfagang because of different version of os, it's hard to confirm the exactly glib version. According to the [doc](https://www.paddlepaddle.org.cn/install/quick?docurl=/documentation/docs/zh/develop/install/pip/linux-pip.html), centos7 and unbunt16.04 is ok to install.

**Comment by lucasjinreal** [comment]
@RainFrost1 please add a support on ubuntu21.04 and centos8. It's 2022 now.
