### ISSUE TITLE
【安装错误】执行安装验证paddle.utils.run_check()报错

### ISSUE THREAD

**Issue by myzhuang** [PaddlePaddle/Paddle#40463]
- 标题：【安装错误】执行安装验证paddle.utils.run_check()报错
- 版本、环境信息：
    1）PaddlePaddle版本： paddlepaddle-gpu==2.1.1
    2）CPU：Intel(R) Xeon(R) Gold 6240 CPU @ 2.60GHz
    3）GPU：Tesla V100-DGX，CUDA10.2 和CUDNN7.6.5
    4）系统环境：linux CentOS7，python3.8，anaconda环境
- 安装方式信息：
1）conda安装
conda install paddlepaddle-gpu==2.1.1 cudatoolkit=10.2 --channel https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/Paddle/
2）本地编译：无
3）docker编译：无       
- 问题描述：
- 按照教程安装，import paddle没问题，然后执行paddle.utils.run_check()报错
- 窗口执行内容如下：
- (paddle) [zmy@EDA-151 PaddleDetection]$ cat /etc/redhat-release
CentOS Linux release 7.4.1708 (Core) 

(paddle) [zmy@EDA-151 PaddleDetection]$ nvcc -V
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2019 NVIDIA Corporation
Built on Wed_Oct_23_19:24:38_PDT_2019
Cuda compilation tools, release 10.2, V10.2.89

(paddle) [zmy@EDA-151 PaddleDetection]$ cat /usr/local/cuda/include/cudnn.h | grep CUDNN_MAJOR -A 2
#define CUDNN_MAJOR 7
#define CUDNN_MINOR 6
#define CUDNN_PATCHLEVEL 5
--
#define CUDNN_VERSION (CUDNN_MAJOR * 1000 + CUDNN_MINOR * 100 + CUDNN_PATCHLEVEL)
#include "driver_types.h"

(paddle) [zmy@EDA-151 PaddleDetection]$ python -m ensurepip
Looking in links: /tmp/tmpjhcuo46y
Requirement already satisfied: setuptools in /data/home2/zmy/anaconda3/envs/paddle/lib/python3.8/site-packages (58.0.4)
Requirement already satisfied: pip in /data/home2/zmy/anaconda3/envs/paddle/lib/python3.8/site-packages (21.2.4)

(paddle) [zmy@EDA-151 PaddleDetection]$ python -m pip --version
pip 21.2.4 from /home2/zmy/anaconda3/envs/paddle/lib/python3.8/site-packages/pip (python 3.8)

(paddle) [zmy@EDA-151 PaddleDetection]$ python -c "import platform;print(platform.architecture()[0]);print(platform.machine())"
64bit
x86_64

(paddle) [zmy@EDA-151 PaddleDetection]$ python
Python 3.8.12 (default, Oct 12 2021, 13:49:34) 
[GCC 7.5.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import paddle
>>> paddle.utils.run_check()
Running verify PaddlePaddle program ... 
W0311 19:10:17.713793 173009 device_context.cc:404] Please NOTE: device: 0, GPU Compute Capability: 7.0, Driver API Version: 10.2, Runtime API Version: 10.2

--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
0   paddle::framework::Executor::Run(paddle::framework::ProgramDesc const&, paddle::framework::Scope*, int, bool, bool, std::vector<std::string, std::allocator<std::string > > const&, bool, bool)
1   paddle::framework::Executor::RunPreparedContext(paddle::framework::ExecutorPrepareContext*, paddle::framework::Scope*, bool, bool, bool)
2   paddle::framework::Executor::RunPartialPreparedContext(paddle::framework::ExecutorPrepareContext*, paddle::framework::Scope*, long, long, bool, bool, bool)
3   paddle::framework::UnsafeFastGPUGarbageCollector::UnsafeFastGPUGarbageCollector(paddle::platform::CUDAPlace const&, unsigned long)
4   paddle::framework::GarbageCollector::GarbageCollector(paddle::platform::Place const&, unsigned long)
5   paddle::platform::DeviceContextPool::Get(paddle::platform::Place const&)
6   std::__future_base::_Deferred_state<std::thread::_Invoker<std::tuple<paddle::platform::EmplaceDeviceContext<paddle::platform::CUDADeviceContext, paddle::platform::CUDAPlace>(std::map<paddle::platform::Place, std::shared_future<std::unique_ptr<paddle::platform::DeviceContext, std::default_delete<paddle::platform::DeviceContext> > >, std::less<paddle::platform::Place>, std::allocator<std::pair<paddle::platform::Place const, std::shared_future<std::unique_ptr<paddle::platform::DeviceContext, std::default_delete<paddle::platform::DeviceContext> > > > > >*, paddle::platform::Place)::{lambda()#1}> >, std::unique_ptr<paddle::platform::DeviceContext, std::default_delete<paddle::platform::DeviceContext> > >::_M_complete_async()
7   std::__future_base::_State_baseV2::_M_do_set(std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> ()>*, bool*)
8   std::_Function_handler<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> (), std::__future_base::_Task_setter<std::unique_ptr<std::__future_base::_Result<std::unique_ptr<paddle::platform::DeviceContext, std::default_delete<paddle::platform::DeviceContext> > >, std::__future_base::_Result_base::_Deleter>, std::thread::_Invoker<std::tuple<paddle::platform::EmplaceDeviceContext<paddle::platform::CUDADeviceContext, paddle::platform::CUDAPlace>(std::map<paddle::platform::Place, std::shared_future<std::unique_ptr<paddle::platform::DeviceContext, std::default_delete<paddle::platform::DeviceContext> > >, std::less<paddle::platform::Place>, std::allocator<std::pair<paddle::platform::Place const, std::shared_future<std::unique_ptr<paddle::platform::DeviceContext, std::default_delete<paddle::platform::DeviceContext> > > > > >*, paddle::platform::Place)::{lambda()#1}> >, std::unique_ptr<paddle::platform::DeviceContext, std::default_delete<paddle::platform::DeviceContext> > > >::_M_invoke(std::_Any_data const&)
9   paddle::platform::CUDADeviceContext::CUDADeviceContext(paddle::platform::CUDAPlace)
10  std::call_once<paddle::platform::dynload::DynLoad__cudnnGetVersion::operator()<>()::{lambda()#1}>(std::once_flag&, paddle::platform::dynload::DynLoad__cudnnGetVersion::operator()<>()::{lambda()#1}&&)::{lambda()#2}::_FUN()
11  paddle::platform::dynload::GetCUDNNDsoHandle()
12  paddle::framework::SignalHandle(char const*, int)
13  paddle::platform::GetCurrentTraceBackString[abi:cxx11]()

----------------------
Error Message Summary:
----------------------
FatalError: `Segmentation fault` is detected by the operating system.
  [TimeInfo: *** Aborted at 1646997017 (unix time) try "date -d @1646997017" if you are using GNU date ***]
  [SignalInfo: *** SIGSEGV (@0x8) received by PID 173009 (TID 0x7f758353a740) from PID 8 ***]

Segmentation fault (core dumped)

**Comment by RainFrost1** [comment]
其他操作报错吗？建议使用官方docker环境

**Comment by myzhuang** [comment]
> 

会报错，跑paddleDetection的例子，也是报了一样的错

**Comment by RainFrost1** [comment]
看着像是CUDA环境配置的有问题，环境问题有时间确实难以定位，建议使用docker镜像吧
