### ISSUE TITLE
Replace Tensor by LoDTensor in each operator.

### ISSUE THREAD

**Issue by qingqing01** [PaddlePaddle/Paddle#4047]
The following comments are addressing three problems:

- Necessary change to LoDTensor
- Replace uses of Tensor into LoDTensor in operators who don't need LoD
- How to pass LoD from operators' inputs to outputs

### LoDTensor

The definition of LoDTensor is as follows:

```cpp
class LodTensor {
 public:
  LoDTensor() {}
  void set_tensor(Tensor* tensor) { tensor_ = tensor; }
 private
  Tensor* tensor_;
  Lod lod_;
};
```

The code snippet shows how we use it in operators:

```cpp
void InferShape(const framework::InferShapeContext &ctx) const override {
    auto tensor_x = ctx.Input<LoDTensor>("X")->tensor();
    auto tensor_y = ctx.Input<LoDTensor>("Y")->tensor();
    PADDLE_ENFORCE_EQ(tensor_x.dims(),
                      tensor_y.dims(),
                      "Two inputs of Add Op's dimension must be same.");
    auto* lod_tensor_out =   ctx.Output<LodTensor>("Out");
    Tensor* out = new Tensor();
    out->Resize(tensor_x->dims());
    lod_tensor_out->set_tensor(out);
  }
};
```

We see that `LoDTensor::set_tensor` is kind of ugly because the caller needs to destruct the tensor at right time.

A solution is to make LoDTensor owns the tensor and delete it at destruction time:

```cpp
class LodTensor {
 public:
  LoDTensor() : tensor_(new Tensor()) {}
  ~LoDTensor() { delete tensor_; }
  //  删掉set_tensor接口。
  // void set_tensor(Tensor* tensor) { tensor_ = tensor; } 
 private
  Tensor* tensor_;
  Lod lod_;
};
```

---

**Comment by qingqing01** [comment]
### 替换非Sequence Operator里Tensor

对于fc、mul、elementwise-mul/add等operators在写OpKernel时只需要用Tensor，而不需要LoDTensor，为了使得这些operators不感知LoDTensor，替换方法步骤：

1.  Variable的`Get<T>`接口可以从LoDTensor里获取到Tensor，对Get接口特化Tensor模板：

```cpp
class Variable {
  template <>
  const Tensor& Get<Tensor>() const {
    if (IsType<LoDTensor>()) {
      auto lod_t = static_cast<const LoDTensor*>(holder_->Ptr());
      return *lod_t->tensor();
    } else {
      PADDLE_ENFORCE(IsType<Tensor>(),
                     "Variable must be type LoDTensor or Tensor");
      return *static_cast<const Tensor*>(holder_->Ptr());
    }
    return;
  }
}
```

2. 在Operator InferShape里input、output不同方式获取Tensor

```
class MulOp : public framework::OperatorWithKernel {
 protected:
  void InferShape(const framework::InferShapeContext &ctx) const override {
    // input通过 Input<Tensor>
    auto x_dims = ctx.Input<Tensor>("X")->dims();
    auto y_dims = ctx.Input<Tensor>("Y")->dims();
    // ...
    // output依然Output<LoDTensor>调用，在variable里创建LoDTensor.
    ctx.Output<LoDTensor>("Out")->tensor()->Resize(
        {x_mat_dims[0], y_mat_dims[1]});
  }
};
```

3.  在class ExecutionContext里重写Output<T>函数, 使得OpKernel的计算里不用感知LoDTensor，依然保持和原来的代码一致。

```cpp
template <typename Place, typename T>
class MulKernel : public framework::OpKernel {
 public:
  void Compute(const framework::ExecutionContext& context) const override {
    const Tensor* x = context.Input<Tensor>("X");
    const Tensor* y = context.Input<Tensor>("Y");
    Tensor* z = context.Output<Tensor>("Out");
    // ...
  }
};
```

---

###  如何在Operator里传递LoD

1.  LoD传递原因

用下面连接方式来举例，op1、op3是sequence计算op, op2是非sequence计算op。op2得传递输入的LoD信息到输出，否则op3获取不到LoD信息。

```
op1(sequence) -> op2(non_sequence) -> op3(sequence)
```

2. 如何传递

需要解决问题：

-  forward op需要传递LoD, backward op一般来说不需要传递LoD。
-  由于Operator可能存在多个输入、多个输出，需要每个Op来决定传递哪个输入的LoD到哪个输出。
-  在哪里传递。

由于前两个问题，比较难把LoD的传递隐藏起来，不让非sequence op感知。下面方法通过**显示的operator InferShape来传递**，需要每个Op显示调用传递函数。

首先在`class InferShapeContext`里定义传递函数：

```cpp
class InferShapeContext {
  void CopyLoD(const std::string& in_name, const std::string& out_name) {
    PADDLE_ENFORCE(InputVar(in_name)->IsType<LoDTensor>(),
                   "The Input(%s) must be LoDTensor.", in_name);
    PADDLE_ENFORCE(OutputVar(out_name)->IsType<LoDTensor>(),
                   "The Output(%s) must be LoDTensor.", out_name);
    Output<LoDTensor>(out_name)->set_lod(Input<LoDTensor>(in_name)->lod());
  }
}
```

然后在operator InferShape里调用：

```cpp
class MulOp : public framework::OperatorWithKernel {
 protected:
  void InferShape(const framework::InferShapeContext &ctx) const override {
    auto x_dims = ctx.Input<Tensor>("X")->dims();
    auto y_dims = ctx.Input<Tensor>("Y")->dims();
    // ...
    ctx.Output<LoDTensor>("Out")->tensor()->Resize(
        {x_mat_dims[0], y_mat_dims[1]});
   // 将输入X的LoD传递给输出Out
    ctx.CopyLoD(/*in = */ "X", /* out = */ "Out");
  }
};
```

**Comment by qingqing01** [comment]
###  如何在Operator里传递LoD

1.  LoD传递原因

用下面连接方式来举例，op1、op3是sequence计算op, op2是非sequence计算op。op2得传递输入的LoD信息到输出，否则op3获取不到LoD信息。

```
op1(sequence) -> op2(non_sequence) -> op3(sequence)
```

2. 如何传递

需要解决问题：

-  forward op需要传递LoD, backward op一般来说不需要传递LoD。
-  由于Operator可能存在多个输入、多个输出，需要每个Op来决定传递哪个输入的LoD到哪个输出。
-  在哪里传递。

由于前两个问题，比较难把LoD的传递隐藏起来，不让非sequence op感知。下面方法通过**显示的operator InferShape来传递**，需要每个Op显示调用传递函数。

首先在`class InferShapeContext`里定义传递函数：

```cpp
class InferShapeContext {
  void CopyLoD(const std::string& in_name, const std::string& out_name) {
    PADDLE_ENFORCE(InputVar(in_name)->IsType<LoDTensor>(),
                   "The Input(%s) must be LoDTensor.", in_name);
    PADDLE_ENFORCE(OutputVar(out_name)->IsType<LoDTensor>(),
                   "The Output(%s) must be LoDTensor.", out_name);
    Output<LoDTensor>(out_name)->set_lod(Input<LoDTensor>(in_name)->lod());
  }
}
```

然后在operator InferShape里调用：

```cpp
class MulOp : public framework::OperatorWithKernel {
 protected:
  void InferShape(const framework::InferShapeContext &ctx) const override {
    auto x_dims = ctx.Input<Tensor>("X")->dims();
    auto y_dims = ctx.Input<Tensor>("Y")->dims();
    // ...
    ctx.Output<LoDTensor>("Out")->tensor()->Resize(
        {x_mat_dims[0], y_mat_dims[1]});
   // 将输入X的LoD传递给输出Out
    ctx.CopyLoD(/*in = */ "X", /* out = */ "Out");
  }
};
```

**Comment by qingqing01** [comment]
related to #3717

**Comment by wangkuiyi** [comment]
Two cents from my side:

### Derivation solves the first two problems

```c++
class LoDTensor {
 private:
   LoD* lod_;
   Tensor* tensor_;
};
```

into 

```c++
class LoDTensor : public Tensor {
 private:
  LoD* lod_;
};
```

In this way, we can save the deletion of `tensor_` in the destructor of `LoDTensor`.

Also, we can use the return value of `context.Input<LoDTensor>("X")` as a `Tensor` pointer.

### I was wrong before

I chose the embedding over the inheritance in the definition of `LoDTensor` for a reason. But that reason is wrong.

I thought that we will have multiple types of Tensors in the future -- SparseTensor, DenseTensor, RowSparseTensor, etc. If we derive LoDTensor from them, we will have LoDSparseTensor, LoDDenseTensor, LoDRowSparseTensor, etc. But I was wrong, because embedding doesn't save us from this.  By embedding LoD and Tensor, we still need a type Tensor, which should be the parent class of SparseTensor, DenseTensor, etc. As long as we have such a base class, we can have only on LoDTensor -- the one derived from this base class Tensor.  So embedding and inheritance are basically the same.  The only difference is that in C++, inheritance allows us to access methods of Tensor from LoDTensor. This is the solution to two of three problems addressed in this PR.

**Comment by qingqing01** [comment]
Need to handle how to pass LoD from operators' inputs to outputs, so reopen this issue.

**Comment by Superjom** [comment]
This works fine, and the `CopyLoD` can't be hidden from users, because which output copy which input's LoD should be specified by op developer, even the FC op.

**Comment by luotao1** [comment]
CopyLoD对大多数op可以隐藏，对FC op来说，output的LoD信息和input的完全一样。只有seq相关的op才会做修改。

**Comment by Superjom** [comment]
那是只有一个 input, 一个 output 的时候的情况吧， 如果有多个 input 或者多个 output， 那对应关系总需要指定吧。

**Comment by luotao1** [comment]
对于目前的非seq Op来说，input的LoD信息都是一样的。目前还未碰到过不同input的LoD信息不一样的情况，除了Recurrent_op。所以只需要在Recurrent Op中特别指明即可。对大多数op来说，不需要感知这块。

**Comment by Superjom** [comment]
add_two 接入两个 input, 有不同的LoD， output 复制哪个呢？

**Comment by luotao1** [comment]
> add_two 接入两个 input, 有不同的LoD， output 复制哪个呢

这种情况目前在实际应用中未碰到过。这种情况应该出现么 @lcy-seso

且对于Recurrent op来说：
- 如果要拆循环，那么不同input的lod信息必须严格一样。因为如果不一样，那么也不能保证sample的数目一样，这样后续就没法接着做计算了。

**Comment by lcy-seso** [comment]
- Op 分为依赖序列信息和不依赖序列信息两类。
- 通常所说的“依赖序列信息的Op”，关心的都是Op完成的运算对元素在序列中的顺序是敏感的。
    - FC 可以接受序列输入，但每个时间步进行的运算完全独立，这个Op 对序列信息不敏感
    - FC 虽然接受多个输入，但是输出只有一个。他的多个输入 LoD 信息必须一致，否则在实际中没有实际的意义。

- 多输入单输出的Op，输入的LoD一样。
- 多输入多输出（除了recurrent_group 这类特殊的RNN，我知道的不多。不清楚是不是存在 Split 之类的运行），每个输出的LoD信息，以这个输出对应的输入为准。

**Comment by lcy-seso** [comment]
@Superjom 多输入单输出情况下，如果多个输入LoD 信息不一致，这种运算通常都是无意义的。

FC 会将多个输入求和，如果多个输入长度不一样，求和运算本身是无法进行的。

而多输入多输出的Op比较少见，可以具体情况具体分析。

**Comment by lcy-seso** [comment]
add_to 不可能有两个LoD 不一样的input，否则求和运算无法进行。

**Comment by lcy-seso** [comment]
现在Op会有多输入？值的是这个？

**Comment by luotao1** [comment]
我理解CopyLoD不能放在InferShape的基类中做，主要是这个原因把：
- forward op需要传递LoD, backward op一般来说不需要传递LoD。Infershape不知道哪个是前向，哪个是后向。

**Comment by Superjom** [comment]
LoD (变长序列)信息不一致，但底层的 tensor shape 一致，这个 add_two 应该是可以跑的。

但如果两个相同shape 但 LoD 不一致，作为 add_two 的输入应该是可以的，但output 需要拷贝哪个的 LoD 是需要确定的，框架可以默认说copy第一个，但如果是 op developer 忽略掉这点会带来隐含的问题。
