### ISSUE TITLE
Does paddle have plans to support the second derivative of sin and cos?

### ISSUE THREAD

**Issue by AndPuQing** [PaddlePaddle/Paddle#40489]

**Comment by WenmuZhou** [comment]
Hello, according to your new requirements, we would like to further communicate with you about the background of requirements and usage scenarios. My email address is zjwenmu@gmail.com. If it is convenient, I can communicate with you one-on-one, thank you

**Comment by WenmuZhou** [comment]
Hi, no plans for now
