### ISSUE TITLE
请问有办法获取GPU的实际使用显存吗？

### ISSUE THREAD

**Issue by TXacs** [PaddlePaddle/Paddle#40498]
- 版本、环境信息：
    1）PaddlePaddle版本：2.2.2
    2）CPU/GPU：3090
    3）系统环境：ubuntu18.04
    4）3.6
    5）24GB

类似pytorch的torch.cuda.memory_allocated()和torch.cuda.max_memory_reserved()

**Comment by wenming2014** [comment]
您好，暂时没有对应的接口，可以通过nvidia-smi获取相关信息，比如
nvidia-smi --id=$CUDA_VISIBLE_DEVICES --query-compute-apps=used_memory --format=csv -lms 100 > "$mem_usage.log" 2>&1 &

**Comment by TXacs** [comment]
> 您好，暂时没有对应的接口，可以通过nvidia-smi获取相关信息，比如 nvidia-smi --id=$CUDA_VISIBLE_DEVICES --query-compute-apps=used_memory --format=csv -lms 100 > "$mem_usage.log" 2>&1 &

多谢
