### ISSUE TITLE
【docker paddle】ssh连接paddle容器后运行不了python

### ISSUE THREAD

**Issue by jiaohuix** [PaddlePaddle/Paddle#40493]
- 标题：python: error while loading shared libraries: libpython3.7m.so.1.0: cannot open shared object file: No such file or directory
- 版本、环境信息：
    1）PaddlePaddle版本：2.2
    2）CPU：请提供CPU型号，MKL/OpenBlas/MKLDNN/等数学库的使用情况
    3）GPU：GPU型号3090，CUDA 11.2 和CUDNN版本号8
    4）系统环境：请说明系统类型、版本（如Mac OS 10.14）、Python版本
注：您可以通过执行[summary_env.py](https://github.com/PaddlePaddle/Paddle/blob/develop/tools/summary_env.py)获取以上信息。
- 安装方式信息：
1）docker安装
3）docker编译：请提供docker镜像，编译命令            
docker pull registry.baidubce.com/paddlepaddle/paddle:2.2.2-gpu-cuda11.2-cudnn8
nvidia-docker run --name paddle -it -v $PWD:/paddle -p 9000:22 registry.baidubce.com/paddlepaddle/paddle:2.2.2-gpu-cuda11.2-cudnn8 /bin/bash
passwd root
service ssh restart
在本地ssh root@ip -p 9000
进去后python用不了

![image](https://user-images.githubusercontent.com/68314259/158088466-861c6282-f448-456e-bfdd-3c9530e83fd2.png)

**Comment by wenming2014** [comment]
您好，python报错找不到libpython3.7m.so.1.0，找到这个so包所在的文件夹，然后复制so包到/usr/local/lib，然后export LD_LIBRARY_PATH=/usr/local/lib。实在不行就重装python吧

**Comment by XieYunshen** [comment]
确认一下是不是镜像的问题吧，如果直接进入镜像使用是没有问题的，
![image](https://user-images.githubusercontent.com/32428676/159222249-767cb9fc-efb6-43a6-b178-8afc811720d0.png)
