### ISSUE TITLE
When I use bi-lstm with attention for classification, it raises this error.

### ISSUE THREAD

**Issue by tonyhu20116543** [PaddlePaddle/Paddle#4049]
![image](https://user-images.githubusercontent.com/6749361/30333020-75aac7a6-980e-11e7-852c-ecac25d2d21a.png)

![image](https://user-images.githubusercontent.com/6749361/30333061-9e0e8ea8-980e-11e7-8882-42392ef60a61.png)

**Comment by kuke** [comment]
从报错信息来看与双向LSTM无关，像是GPU设备的问题。请检查一下GPU的驱动是否正常、是否正确设置了可见设备等可能存在的问题。

**Comment by tonyhu20116543** [comment]
会不会是一个bug，如果这里的 attention 加的没错的话

**Comment by leyiwang** [comment]
@tonyhu20116543 你好，你最后找到解决方案了吗？
