### ISSUE TITLE
 'Tensor' object has no attribute 'retain_grad'

### ISSUE THREAD

**Issue by tsijeodhsjsh** [PaddlePaddle/Paddle#40503]
代码：
def forward(self, x, noise):
        x = x - noise
        x = self._models[0](x)

        if len(self._models) > 1:
            x_list = [x]
            for layer in self._models[1:]:
                x = layer(paddle.concat(x_list, axis=1))
                x_list.append(x)
        x.retain_grad()
        
        return x
问题：
 x.retain_grad()
AttributeError: 'Tensor' object has no attribute 'retain_grad'

**Comment by wenming2014** [comment]
您好，暂时没有对应的接口，可以通过nvidia-smi获取相关信息，比如
nvidia-smi --id=$CUDA_VISIBLE_DEVICES --query-compute-apps=used_memory --format=csv -lms 100 > "$mem_usage.log" 2>&1 &

**Comment by wenming2014** [comment]
您好，tensor的用法见https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/Tensor_cn.html#tensor
