### ISSUE TITLE
Advice on model that stopped to work

### ISSUE THREAD

**Issue by jczaja** [PaddlePaddle/Paddle#40540]
After commit 975f99ab012310e97cbdee44bb25a05ad7bad012 model https://github.com/PaddlePaddle/Paddle/issues/38126#issuecomment-1003277884 that We use to track our NHWC work, stopped to work (only for oneDNN).

Problem is that in mentioned model there is a check for "sin" operator 
https://github.com/PaddlePaddle/Paddle/blob/e157f2afb78a9183d71bf03ffd67379040173056/paddle/fluid/framework/operator.cc#L1116

which is not present in OperatorWithKernel::AllOpKernels().

Please advice how to proceed.

**Comment by lidanqing-vv** [comment]
@jczaja  Hi How is it now? I saw all your CIs passed

**Comment by jczaja** [comment]
@lidanqing-intel Model from #38126 is tested only internally by us. It is not part of CI.

**Comment by jczaja** [comment]
@baoachun any progress on this one?

**Comment by jczaja** [comment]
@baoachun We just noticed that it works.
