### ISSUE TITLE
验证结果不变

### ISSUE THREAD

**Issue by Ruri-94** [PaddlePaddle/Paddle#40554]
模型训练过程中损失变化，但在验证集上的验证结果不变。可能的原因都有哪些？

**Comment by LiuChiachi** [comment]
您好，您是想问训练到后期loss一直下降可是验证集的指标一直不再提升吗？可否详细描述您的问题呢～

如果是到后面发生的如上现象，可以考虑是过拟合的情况。

**Comment by Ruri-94** [comment]
> 您好，您是想问训练到后期loss一直下降可是验证集的指标一直不再提升吗？可否详细描述您的问题呢～
> 
> 如果是到后面发生的如上现象，可以考虑是过拟合的情况。

您好，我的问题是在从模型训练开始 验证集的指标就不变

**Comment by LiuChiachi** [comment]
loss下降吗，可以排查下网络有没有bug，比如用训练集的数据看看评估指标。如果没有bug的话，建议调整超参数。
