### ISSUE TITLE
Conversational-Recommendation-BASELINE

### ISSUE THREAD

**Issue by xiao-ming-code** [PaddlePaddle/Paddle#40562]
使用的环境：
paddlepaddle-gpu==1.6.1.post97
python ==2.7
cuda==11.4
模型对应github链接：https://github.com/cstghitpku/Research/tree/master/NLP/Conversational-Recommendation-BASELINE
环境要求是按照README.ME安装，执行步骤也安装流程一步步执行，但是在执行 python data_generator.py 出现一下的错误
![} K $()BK%2)K@RJ`VWU{BX](https://user-images.githubusercontent.com/73177290/158324047-58965494-f41f-430d-bf9f-4e77087ec141.png)
代码出错的位置
![}0W254B{6YZBZWXB~F@$XNI](https://user-images.githubusercontent.com/73177290/158324119-e1306bac-1e26-4cfe-9c2c-bfd0652816df.png)
通过代码的规则之后得到是一个空值，所以希望更新修改下代码

**Comment by LiuChiachi** [comment]
您好，从报错信息来还看不出是PaddlePaddle框架的问题，建议您去您参考的项目的仓库提issue，排除一下是否是模型代码的原因，感谢关注～
看原仓库是，https://github.com/PaddlePaddle/Research/issues
