### ISSUE TITLE
PaddleCheckError

### ISSUE THREAD

**Issue by xiao-ming-code** [PaddlePaddle/Paddle#40578]
使用的环境：
paddlepaddle-gpu==1.6.1.post97
python ==2.7
cuda==11.4
模型对应github链接：https://github.com/cstghitpku/Research/tree/master/NLP/Conversational-Recommendation-BASELINE
在训练retrieval_model  bash run_train.sh出现以下的错误
![97{H{JG9USL(5`U8LTVYU)C](https://user-images.githubusercontent.com/73177290/158342048-63022024-e30e-4c3b-a0ba-f2e669acf476.png)

**Comment by LiuChiachi** [comment]
您好，您参考的模型readme里推荐的环境如下：
系统：CentOS 6.3, cuda 9.0, CuDNN 7.0
python 2.7
PaddlePaddle 1.6.1

我猜测是您机器上的cuda版本太新，Paddle版本还是1.6版本，两者不匹配导致的。建议让环境和文档描述的保持一致，也可以尝试下安装最新的Paddle，看是否可以跑通。但前者可能更保险一些，可能可以更快把模型跑起来。

**Comment by xiao-ming-code** [comment]
我通过paddle官网安装，cuda10.2 👍 conda install paddlepaddle-gpu==2.2.2 cudatoolkit=10.2 --channel https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/Paddle/
成功安装了 2.27
然后出现了下面的错误
![R)IAP1WT)$YTZ$ MSJR3 JI](https://user-images.githubusercontent.com/73177290/158507069-b6756ed5-c6b8-4535-8152-3d5e47670fd6.png)

但是我又使用 pip install paddlepaddle-gpu这个命令安装，显示都已经满足了要求
再次训练，还是出现上面的问题
麻烦再看看 。谢谢

**Comment by LiuChiachi** [comment]
把CPU版本的先卸载，再使用 pip install paddlepaddle-gpu这个命令安装一下试试呢。如果不行的话把安装完paddlepaddle-gpu的日志发出来一起看下吧。

**Comment by xiao-ming-code** [comment]
我卸载 pip uninstall paddlepaddle ,然后重新通过官网安装了 2.27版本的，
![}E9XD08GD3PNJ228EN`7B`P](https://user-images.githubusercontent.com/73177290/158531846-0062c29d-26ae-4db1-a0e0-716cb63e7295.png)
![`R@(K7G})(WDTHO1JO0O_0M](https://user-images.githubusercontent.com/73177290/158531859-3b525a33-f97e-4285-a5ef-d361a71bbb90.png)
![G8B5G5XLESUGGG)7`B83@{R](https://user-images.githubusercontent.com/73177290/158531882-a4bb365b-0d91-47a3-8859-a59246dc0c0d.png)

然后出现下面这个。
![}@HC(URF5PDDX_3_A 6XYF6](https://user-images.githubusercontent.com/73177290/158530372-e87ef173-097e-43ec-9c52-2b1f594eea20.png)
我通过 pip install paddle ,conda install paddle ,还是无法解决
我创建一个新环境，使用项目推荐的的requirement，可以还是会出现cuda的问题
![U 2 WWXBCKZ)7I4OM~`ZF6K](https://user-images.githubusercontent.com/73177290/158531126-fa464ec5-0a3d-4d40-97ea-bde67f18c534.png)
好像和这个问题相同，https://github.com/PaddlePaddle/Paddle/issues/22467
但是他的解决方法我看不懂，麻烦了

**Comment by LiuChiachi** [comment]
您的Paddle安装失败了。
Python2.7我们现在不支持了，建议升级Python版本，比如3.6，3.7，3.8都可以。
你的cuda环境和安装的包10.2匹配吗？

**Comment by xiao-ming-code** [comment]
我使用了python3.6  安装了cuda11.2对应的paddle  cuda还是有问题，官网最新的就是cuda11.2
![RI}@ %@@%FD7U`}E}YPAA`9](https://user-images.githubusercontent.com/73177290/158545810-6ba8b106-bf0a-4951-9686-8ded653b036a.png)

**Comment by LiuChiachi** [comment]
import paddle，paddle正常安装了吗。CUDA_VISIBLE_DEVICES环境变量正常吗

**Comment by xiao-ming-code** [comment]
import paddle没问题，paddle正常安装了，cuda环境设置 使用的 place=fluid.CUDAPlace(0),使用id=0的，

**Comment by xiao-ming-code** [comment]
非常感谢，最后运行成功了
