### ISSUE TITLE
Usecase: 一个专业程序员查找API文档的经历

### ISSUE THREAD

**Issue by fanruinet** [PaddlePaddle/Paddle#40628]
大F是一名具有十余年编程经验的专业程序员，他擅长服务器领域的编程，可以熟练使用C++、Java、C#等编程语言，但对Python、机器学习与飞桨这些技术来说则是刚刚入门。现在大F正在AI Studio中尝试根据教程训练一个波士顿房价预测的线性模型。整个教程的代码运行很顺利，但是大F试图理解这个训练好的模型中都有什么属性与方法。这个模型是如下定义的：
```python
model = paddle.nn.Sequential(
    paddle.nn.Linear(13, 1)
)
```
第1次尝试：根据以往使用IDE编写代码的经验，大F尝试了编辑器是否有智能提示，但遗憾的是输入“model.”之后编辑器没有任何反应。然后大F尝试右键单击“Sequential”这个类名，试图找到“Go go definition/declaration”之类的功能，但仍然很遗憾，弹出的菜单是浏览器的普通上下文菜单，没有任何有价值的功能。
第2次尝试：大F只好去官方文档中查找，这对大F来说是经常做的事情。很快大F就找到了[Sequential的官方文档](https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/nn/Sequential_cn.html)，但是令他吃惊的是，这个页面上除了构造函数以外，什么也没有，甚至连教程中出现过的`model.state_dict()`、`model.parameters()`这些方法都没有找到。
第3次尝试：上面的API文档中在页面底部提到了“使用本API的教程文档”，大F尝试在这里面找到关于Sequential model的详细说明，但很不幸，这些链接里只有关于Sequential的实例代码。
第4次尝试：大F根据他所掌握的知识进一步猜想，可能.parameters()这个方法不是Sequential本身定义的，而是从它的父类继承过来的，那么在Sequential的父类中可能会有对应的说明。那么Sequential类的父类是谁呢？这在大多数类库的文档中通常会有一节专门用来说明类的继承层次，例如：[HashMap的文档](https://docs.oracle.com/javase/8/docs/api/java/util/HashMap.html)，但大F在[Sequential的文档](https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/nn/Sequential_cn.html)中没有找到有帮助的信息。
第5次尝试：大F明白，如果文档中找不到，几乎只能在源代码中搜索了。好在文档中有直接跳转到[Sequential源代码的链接](https://github.com/PaddlePaddle/Paddle/blob/release/2.2/python/paddle/fluid/dygraph/container.py#L27)。打开这个链接后，大F终于知道Sequential类继承自Layer。借助于GitHub的功能，大F可以在源代码页面上直接点击“Layer”，然后跳转到了Layer的源代码。在这里大F终于找到了久违的“def parameters(self, include_sublayers=True):”。

总结：这次查找文档的体验对大F来说及其糟糕，对于这次查找文档的目标来说，官方的文档没有提供任何有价值的信息。大F在之前编写Java和C#的过程中从来没有遇到过像这样的挫折感。在谈用户体验的时候，每增加一个步骤，转化率就会打一定的折扣。如果其中有一个步骤没有明确说明，而是需要借助用户的专业知识才能找到答案，那么能坚持用下去的用户一定是靠信念支撑下来的。

改进建议：
1. 在一个类的文档中，例如：[Sequential的官方文档](https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/nn/Sequential_cn.html)，应当有类的继承层次，包括这个类的所有父类、所有子类，并可以点击类名直接跳转到对应类的文档。
2. 缺少类的综述、版本兼容性（在哪个版本之后才有了这个API）。
3. 要列出所有从父类继承过来的方法，哪怕只是有个跳转到父类文档的链接。

优秀API文档的参考：
* https://docs.oracle.com/javase/8/docs/api/java/util/HashMap.html
* https://docs.microsoft.com/en-us/dotnet/api/system.collections.generic.dictionary-2?view=net-6.0

**Comment by TCChenlong** [comment]
开发者你好，目前飞桨API文档在此类场景下的使用体验确实有待提升，我们会参考你的建议，尽快给出优化方案。也欢迎你提出更多的想法，非常感谢你的宝贵建议~

**Comment by wadefelix** [comment]
> 开发者你好，目前飞桨API文档在此类场景下的使用体验确实有待提升，我们会参考你的建议，尽快给出优化方案。也欢迎你提出更多的想法，非常感谢你的宝贵建议~

https://zhuanlan.zhihu.com/p/478547185#h_478547185_8
MindSpore刚刚开发发布了IDE插件
