### ISSUE TITLE
nn.layer的training属性是如何影响模型的反向传播的

### ISSUE THREAD

**Issue by wzy-99** [PaddlePaddle/Paddle#40620]
本人想通过调用模型中的某一层的eval()方法来冻结这一层。

通过查看源码发现，eval()将该层及子层的training属性设置为False。

但是我不知道在模型的反向传播中，training是如何阻断梯度的。

因此不知道通过这种方法**能否真正实现冻结的效果**。

**Comment by yghstill** [comment]
@wzy-99 如果想阻止梯度更新，可以设置这一层stop_gradient=True： https://www.paddlepaddle.org.cn/documentation/docs/zh/faq/train_cn.html#stop-gradient-true
