### ISSUE TITLE
Document Issue: Incorrect description of weight_attr parameter of Linear() constructor

### ISSUE THREAD

**Issue by fanruinet** [PaddlePaddle/Paddle#40644]
The document says:
> weight_attr (ParamAttr, optional) – The attribute for the learnable weight of this layer. The default value is None and the weight will be initialized to zero.

However, the following code prints different parameter values for every execution instead of zeroes:
```python
import paddle
model = paddle.nn.Sequential(
    paddle.nn.Linear(13, 1)
)
print(model.parameters())
```
```
[Parameter containing:
Tensor(shape=[13, 1], dtype=float32, place=CPUPlace, stop_gradient=False,
       [[-0.10559809],
        [ 0.24627006],
        [ 0.11579365],
        [ 0.32065874],
        [-0.04503900],
        [-0.57152677],
        [ 0.21997571],
        [-0.00493658],
        [ 0.63323462],
        [-0.36588839],
        [-0.29162914],
        [ 0.31002057],
        [-0.21488908]]), Parameter containing:
Tensor(shape=[1], dtype=float32, place=CPUPlace, stop_gradient=False,
       [0.])]
```

The code and document don't match. I'm not sure which behavior is the correct design.

This error occurs in the following pages:
https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/nn/Linear_cn.html
https://www.paddlepaddle.org.cn/documentation/docs/en/api/paddle/nn/Linear_en.html
https://github.com/PaddlePaddle/Paddle/blob/6849d33b62cacccb27797375a212e37a47ca9484/python/paddle/nn/layer/common.py#L99

**Comment by cuicheng01** [comment]
Hi, the default parameter initialization method here is Xavier, and only the bias parameter is initialized to 0. The documentation here is not very appropriate, we will fix it soon, thanks for the feedback.

**Comment by luotao1** [comment]
> the default parameter initialization method here is Xavier, and only the bias parameter is initialized to 0.

@fanruinet You can create a PR to fix it： If the Initializer of the param_attr is not set, the parameter is initialized with Xavier. Default: None.

**Comment by enkilee** [comment]
chinese docs: https://github.com/PaddlePaddle/docs/pull/5559
english docs: https://github.com/PaddlePaddle/Paddle/pull/49532
