### ISSUE TITLE
基于`local_response_norm`API搭建网络，保存为推理模型时报错

### ISSUE THREAD

**Issue by LiKangyuLKY** [PaddlePaddle/Paddle#40673]
- 标题：简洁、精准概括您的问题，例如“Insufficient Memory xxx" ”
- 版本、环境信息：
    1）PaddlePaddle版本：paddlepaddle-gpu 2.2.2.post112
    3）GPU：CUDA11.2  cuDNN 8.2.1
    4）系统环境：ubuntu 18.04和Windows10均测试，python3.7.0

- 训练信息
    1）单机与多卡均已测试
    2）基础API和高阶API（Model）均测试

- 问题描述：
  基于paddle搭建了神经网络，其中采用了local_response_norm进行正则化。模型训练完成后，在保存至推理模型（`.pdmodel`, `.pdiparams.info`, `.pdiparams`）时，出现报错信息：`ValueError: Expected every dim's size to be larger than 0, but the size of the 0-th dim is -1`
  以高阶API进行训练时，指定了模型的输入和输出如下：
  ```
  input = InputSpec([None, 3, 120, 160], 'float32', 'x')
  label = InputSpec([None, 3648], 'float32', 'label')
  ...
  model = paddle.Model(network, input, label)
  ...
  # save for inference
  model.save('inference/ae_infer_model', False) 
  ```
    在以基础API进行训练时，基于动态图训练+模型保存，在使用了如下代码保存推理模型，也指定了`input_spec`：
  ```
  paddle.paddle.jit.save(
          layer=net,
          path=save_dir + '/inference/infer_model' ,
          input_spec=[InputSpec(shape=[None, 3, 120, 160], dtype='float32')]
      )
  ```

  整个训练过程是正常的，并且保存checkpoint模型（`.pdopt`, `.pdparams`）也是正常的。

  测试发现，主要原因是在指定input的尺寸为`[None, 3, 120, 160]`，用`None`和`-1`均会报错，指定具体的数字如`[1, 3, 120, 160]`则不会报错。

- 相关信息截图：
![image](https://user-images.githubusercontent.com/42792466/158766807-60ce96b2-86d0-4ebe-9c60-ef462ca80276.png)

**Comment by cuicheng01** [comment]
您好，这个是我们的一个bug，我们回尽快修复，感谢反馈。

**Comment by Ligoml** [comment]
感谢指出，目前已经提PR修复https://github.com/PaddlePaddle/Paddle/pull/40714 ，预计会随paddle2.3rc正式发布，敬请关注~
