### ISSUE TITLE
编译Wheel太慢

### ISSUE THREAD

**Issue by pkuyym** [PaddlePaddle/Paddle#4069]
Porting operator过程中需要反复make，大量时间卡在编译wheel上面

**Comment by typhoonzero** [comment]
我现在的做法是：https://github.com/PaddlePaddle/Paddle/issues/4068#issuecomment-329121817

```bash
make copy_paddle_pybind
cp ../python/paddle/v2/framework/core.so /paddle/build/python/build/lib-python/paddle/v2/framework/
ctest -R xxx
```

这样第一次编译之后，后续的更新会很快。

**Comment by gongweibao** [comment]
Feel free to reopen it!
