### ISSUE TITLE
关于日志保存的问题

### ISSUE THREAD

**Issue by GeYuYao-hub** [PaddlePaddle/Paddle#40725]
在aistudio上使用fit进行训练时，如何将日志保存至txt文档中？aistudio只支持打印3000行日志，3000行以后的数据无法查看，我若想将日志保存至一个txt文件中该如何操作？

**Comment by tianxin1860** [comment]
AIStudio Notebook 内支持 Shell 命令, 可以直接把输出重定向到本地文件即可。
