### ISSUE TITLE
关于Sort中NaN后不排序

### ISSUE THREAD

**Issue by Asthestarsfalll** [PaddlePaddle/Paddle#40739]
在使用develop版本中发现paddle.sort对NaN之后的数据就不会再进行排序，在[官方中文文档](https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/sort_cn.html#sort)中也没有提及。是否要加入输入tensor中含有NaN的提醒，或者使用某些处理将Nan置于最后（类似于pytorch）
另外某些调用sort的API也会造成结果上的错误，比如`quantile`等，加入NaN的提醒或许对用户debug更友好。

**Comment by esythan** [comment]
感谢反馈，我们正在调研修复这个问题，后续会加入相关的提醒。

**Comment by Ligoml** [comment]
开发者你好，这个API调用了一些cuda上的接口，接口目前有些问题已经反馈到nvidia，待nvidia修复后，我们会及时提pr修复paddle框架的问题~

**Comment by Ligoml** [comment]
该问题在2.3版本已完成修复https://github.com/PaddlePaddle/Paddle/pull/41070
