### ISSUE TITLE
使用tqdm包装dataloader显示训练进度，出现内存泄漏oom

### ISSUE THREAD

**Issue by stunback** [PaddlePaddle/Paddle#40734]
PaddlePaddle版本：2.2.2, gpu版
系统环境：在自己的笔记本和aistudio的notebook gpu版都试过
- 训练信息
    1）单机单卡
    2）tesla V100 16G
- 复现信息：在aistudio的CPU，GPU环境都可以复现该问题
- 问题描述：
         
使用paddle.io.Dataset自定义数据集的读取和预处理，使用paddle.io.Dataloader加载批数据，使用tqdm包装Dataloader显示批读取进度时，可能出现内存泄漏的问题，测试代码如下
```python
# 数据集加载，没有问题
vs_train_dataset = VSDataset(vs_basic, mode='train')
vs_train_loader = paddle.io.DataLoader(vs_train_dataset, batch_size=32, num_workers=0)
epochs = 10
# 训练过程
for epoch in range(epochs):
    # 如果使用tqdm封装vs_train_loader()，训练中的内存会不断增加
    train_loop = tqdm.tqdm(iterable=vs_train_loader(),
                           total=(len(vs_train_loader())))
    for batch_id, data in enumerate(train_loop):
        x = data[0]
        y = data[1]
        train_loop.set_description('train batch: {}'.format(batch_id))
```
通过memory_profiler，我记录了内存使用随时间的增长：
![Figure_1](https://user-images.githubusercontent.com/54929971/159145684-4ca03148-34ea-4446-9816-49baeb1cac6e.png)
迭代中内存从6G增长到了10G，很明显出现了内存泄漏的问题。

在官方文档中，Dataloader在训练迭代时都添加了()，如`for batch_id, data in enumerate(train_loader()):`，这应该是调用了父类的`self.__call__()`方法。但是我发现如果去掉()，则使用tqdm包装Dataloader时不会出现内存泄漏：
```python
vs_train_dataset = VSDataset(vs_basic, mode='train')
vs_train_loader = paddle.io.DataLoader(vs_train_dataset, batch_size=32, num_workers=0)
epochs = 10
# 训练过程
for epoch in range(epochs):
    # 如果使用tqdm封装vs_train_loader，则不会出现内存泄漏
    train_loop = tqdm.tqdm(iterable=vs_train_loader,
                           total=(len(vs_train_loader)))
    for batch_id, data in enumerate(train_loop):
        x = data[0]
        y = data[1]
        train_loop.set_description('train batch: {}'.format(batch_id))
```
![Figure_2](https://user-images.githubusercontent.com/54929971/159145847-9a2f5a1d-11c5-43da-af7e-e56457342447.png)
内存保持在6G，没有出现内存泄漏

因此我想确定一下出现该内存泄漏的根本原因，以及为什么在使用dataloader迭代时需要添加()，是否能够去掉该()。
并且能否把该问题放到官方文档的常见问题中，我感觉tqdm还是挺常用的，我在debug时发现pytorch+tqdm也会有类似问题。

**Comment by esythan** [comment]
感谢反馈，我们正在排查相关问题，有进展会同步给你

**Comment by developWmark** [comment]
我之前遇到过这个问题，不加tqdm也会内存增加，原因是vs_train_loader加了（）

**Comment by geekhch** [comment]
> 感谢反馈，我们正在排查相关问题，有进展会同步给你

我这两天也遇到了内存泄漏，调了好久的bug，发现Dataloader就算不调用__call__， 使用多进程num_workers>0的时候就会出现内存泄漏。但是使用单进程num_workers=0的时候似乎不会（未经严格测试）

**Comment by geekhch** [comment]
> 感谢反馈，我们正在排查相关问题，有进展会同步给你

我这两天也遇到了内存泄漏，调了好久的bug，发现Dataloader就算不调用__call__， 使用多进程num_workers>0的时候就会出现内存泄漏。
