### ISSUE TITLE
Error: Can not import noavx core while this file exists: 

### ISSUE THREAD

**Issue by CuberrChen** [PaddlePaddle/Paddle#40730]
>>> import paddle
```
Error: Can not import noavx core while this file exists: /home//paddle_2_2/lib/python3.8/site-packages/paddle/fluid/core_noavx.so
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/paddle_2_2/lib/python3.8/site-packages/paddle/__init__.py", line 25, in <module>
    from .fluid import monkey_patch_variable
  File "/home/paddle_2_2/lib/python3.8/site-packages/paddle/fluid/__init__.py", line 36, in <module>
    from . import framework
  File "/home/paddle_2_2/lib/python3.8/site-packages/paddle/fluid/framework.py", line 37, in <module>
    from . import core
  File "/home/paddle_2_2/lib/python3.8/site-packages/paddle/fluid/core.py", line 357, in <module>
    raise e
  File "/home/paddle_2_2/lib/python3.8/site-packages/paddle/fluid/core.py", line 309, in <module>
    from .core_noavx import *
ImportError: /home/paddle_2_2/lib/python3.8/site-packages/paddle/fluid/core_noavx.so: cannot open shared object file: No such file or directory
```
请问这个怎么解决？

**Comment by CuberrChen** [comment]
补充：架构为ppc64le。

**Comment by tianxin1860** [comment]
你好，请提供一下具体操作系统、版本及安装的 Paddle 版本

**Comment by CuberrChen** [comment]
> 你好，请提供一下具体操作系统、版本及安装的 Paddle 版本

****************************************
Paddle version: None
Paddle With CUDA: None
OS: Red Hat Enterprise Linux Server 7.6
Python version: 3.8.3
NVIDIA-SMI 440.118.02   Driver Version: 440.118.02   CUDA Version: 10.2
Nvidia driver version: 440.118.02
****************************************

paddle装的是paddlepaddle_gpu-2.2.2.post101-cp38-cp38-linux_x86_64。

**Comment by CuberrChen** [comment]
ppc64le
NAME="Red Hat Enterprise Linux Server"
VERSION="7.6 (Maipo)"
ID="rhel"
ID_LIKE="fedora"
VARIANT="Server"
VARIANT_ID="server"
VERSION_ID="7.6"
PRETTY_NAME="Red Hat Enterprise Linux Server 7.6 (Maipo)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:7.6:GA:server"
HOME_URL="https://www.redhat.com/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 7"
REDHAT_BUGZILLA_PRODUCT_VERSION=7.6
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="7.6"
Red Hat Enterprise Linux Server release 7.6 (Maipo)
Red Hat Enterprise Linux Server release 7.6 (Maipo)

**Comment by tianxin1860** [comment]
从报错信息看，可以参考这个方法定位原因: https://ai.baidu.com/forum/topic/show/983545

**Comment by baoachun** [comment]
您好，可以试试清理下paddle安装目录再重新安装看看能否解决问题

**Comment by CuberrChen** [comment]
没有解决。

**Comment by hzane** [comment]
我也遇到了这个问题，操作系统是 fedora 36. 有些人说，glibc 的版本太高，paddle不支持。所以，我自己编译了一个glibc-2.27，然后指定 python 的ld 后，上面的错误就消失了，只是GPU不能用。

这么修改 glibc 的版本：

`patchelf --set-interpreter /opt/glibc/lib/ld-linux-x86-64.so.2 bin/python3.9`
