### ISSUE TITLE
是否可以直接将AIStudio里已有的项目进行部署

### ISSUE THREAD

**Issue by htlbayytq** [PaddlePaddle/Paddle#40740]
您好，在AIStudio里发现一个很好的项目，fork了一下想直接用飞桨部署一下，练一练部署，请问这样是可以的吧？

**Comment by esythan** [comment]
可以

**Comment by htlbayytq** [comment]
> 可以

感谢答复！   可以辛苦具体说一下怎样可以部署已有项目嘛？   因为从来没有部署过AIStudio里的项目，感谢！！

**Comment by esythan** [comment]
可以具体说下想要部署的项目吗？我们看下是需要什么样的部署环境，然后给你相应的部署文档

**Comment by htlbayytq** [comment]
> 

好嘞！

是这个项目：https://aistudio.baidu.com/aistudio/projectdetail/2204966?channelType=0&channel=0

**Comment by htlbayytq** [comment]
> 可以具体说下想要部署的项目吗？我们看下是需要什么样的部署环境，然后给你相应的部署文档

好嘞！

是这个项目：https://aistudio.baidu.com/aistudio/projectdetail/2204966?channelType=0&channel=0

基于飞桨的糖尿病视网膜病变检测系统

**Comment by esythan** [comment]
请问是想要在自己的开发机上部署还是直接在aiStudio上部署，部署训练还是推理？

**Comment by htlbayytq** [comment]
> 请问是想要在自己的开发机上部署还是直接在aiStudio上部署，部署训练还是推理？

想先练一下Paddle Inference和Paddle Serving，部署推理

**Comment by esythan** [comment]
可以参考以下两个git repo：
1、paddle serving：https://github.com/PaddlePaddle/Serving
2、paddle inference：https://github.com/PaddlePaddle/Paddle-Inference-Demo
里面有具体的安装流程，还有些demo示例
