### ISSUE TITLE
Paddle复现stylegan2-ada和stylegan3，paddle.grad()求出了错误的梯度！

### ISSUE THREAD

**Issue by miemie2013** [PaddlePaddle/Paddle#40741]
代码地址：https://github.com/miemie2013/ppgan

环境：Python3.9、paddlepaddle-gpu==2.2.0

stylegan2-ada和stylegan3的modulated_conv2d()方法中，会包含以下代码：
```
    w = weight.unsqueeze(0) # [1, out_C, in_C, kH, kW]
    w = w * styles.reshape(batch_size, 1, -1, 1, 1) # [N, out_C, in_C, kH, kW]
    dcoefs = w.sum(dim=[2,3,4])  # [N, out_C]
    w = w * dcoefs.reshape((batch_size, -1, 1, 1, 1))  # [N, out_C, in_C, kH, kW]
```
问题出在最后一行代码。即最后一行代码右边的式子中，w和dcoefs都是包含有styles的。用paddle.grad()求styles的梯度，会求出错误的梯度！
问题复现：
代码地址：https://github.com/miemie2013/ppgan
进入test_grad文件夹。首先运行test2_16_elementwise_grad.py，跑8次前向，保存输入、输出、损失对styles的梯度等为文件16_grad.npz；
接着，跑test2_16_elementwise_grad_paddle.py，上面的语句用Paddle实现一遍，读取16_grad.npz中保存的输入作为输入，跑8次前向。即此时paddle版与pytorch版有相同的输入，我们期望paddle与pytorch有相同的输出、相同的梯度。但是跑8次前向的结果发现，out_pytorch与out_paddle是一样的，dloss_dstyles_pytorch与dloss_dstyles_paddle差异巨大。

stylegan3的modulated_conv2d()也会有上述代码。若不修复paddle.grad()的错误，stylegan3将难以复现。

**Comment by GT-ZhangAcer** [comment]
mark

**Comment by esythan** [comment]
你好，感谢你的反馈，这个问题的修复已经在排期中
另外，如果问题本身不需要求高阶导数，可以看下backward api是否能够先暂时满足你的需求
