### ISSUE TITLE
提交paddle 集群任务运行出core

### ISSUE THREAD

**Issue by zhouksh** [PaddlePaddle/Paddle#4075]
以下是堆栈信息，：
Wed Sep 13 18:19:44 2017[1,16]<stderr>:*** Check failure stack trace: ***
Wed Sep 13 18:19:44 2017[1,16]<stderr>:    @     0x7f18d985227d  google::LogMessage::Fail()
Wed Sep 13 18:19:44 2017[1,16]<stderr>:    @     0x7f18d9855d2c  google::LogMessage::SendToLog()
Wed Sep 13 18:19:44 2017[1,16]<stderr>:    @     0x7f18d9851da3  google::LogMessage::Flush()
Wed Sep 13 18:19:44 2017[1,16]<stderr>:    @     0x7f18d985723e  google::LogMessageFatal::~LogMessageFatal()
Wed Sep 13 18:19:44 2017[1,16]<stderr>:    @     0x7f18d985add3  google::glog_internal_namespace_::InitGoogleLoggingUtilities()
Wed Sep 13 18:19:44 2017[1,16]<stderr>:    @     0x7f18d97b0aee  paddle::initMain()
Wed Sep 13 18:19:44 2017[1,16]<stderr>:    @     0x7f18d9839e01  initPaddle()
Wed Sep 13 18:19:44 2017[1,16]<stderr>:    @     0x7f18d94c26a9  _wrap_initPaddle
Wed Sep 13 18:19:44 2017[1,16]<stderr>:    @           0x4b4cb9  PyEval_EvalFrameEx
Wed Sep 13 18:19:44 2017[1,16]<stderr>:    @           0x4b6b28  PyEval_EvalCodeEx
Wed Sep 13 18:19:44 2017[1,16]<stderr>:    @           0x4b5d10  PyEval_EvalFrameEx
Wed Sep 13 18:19:44 2017[1,16]<stderr>:    @           0x4b6b28  PyEval_EvalCodeEx
Wed Sep 13 18:19:44 2017[1,16]<stderr>:    @           0x529340  function_call
Wed Sep 13 18:19:44 2017[1,16]<stderr>:    @           0x422cba  PyObject_Call
Wed Sep 13 18:19:44 2017[1,16]<stderr>:    @           0x4b1bd0  PyEval_EvalFrameEx
Wed Sep 13 18:19:44 2017[1,16]<stderr>:    @           0x4b6b28  PyEval_EvalCodeEx
Wed Sep 13 18:19:44 2017[1,16]<stderr>:    @           0x4b5d10  PyEval_EvalFrameEx
Wed Sep 13 18:19:44 2017[1,16]<stderr>:    @           0x4b6b28  PyEval_EvalCodeEx
Wed Sep 13 18:19:44 2017[1,16]<stderr>:    @           0x4b5d10  PyEval_EvalFrameEx
Wed Sep 13 18:19:44 2017[1,16]<stderr>:    @           0x4b6b28  PyEval_EvalCodeEx
Wed Sep 13 18:19:44 2017[1,16]<stderr>:    @           0x4b6c52  PyEval_EvalCode
Wed Sep 13 18:19:44 2017[1,16]<stderr>:    @           0x4e1c7d  PyRun_FileExFlags
Wed Sep 13 18:19:44 2017[1,16]<stderr>:    @           0x4e3501  PyRun_SimpleFileExFlags
Wed Sep 13 18:19:44 2017[1,16]<stderr>:    @           0x4159dd  Py_Main
Wed Sep 13 18:19:44 2017[1,16]<stderr>:    @     0x7f18dfa44bd5  __libc_start_main
Wed Sep 13 18:19:44 2017[1,16]<stderr>:    @           0x414b71  (unknown)
Wed Sep 13 18:19:44 2017[1,16]<stderr>:    @              (nil)  (unknown)
Wed Sep 13 18:19:44 2017[1,16]<stderr>:./train.sh: line 239: 17563 Aborted                 python27-gcc482/bin/python conf/trainer_config.conf
Wed Sep 13 18:19:44 2017[1,16]<stderr>:+ '[' 134 -ne 0 ']'
Wed Sep 13 18:19:44 2017[1,16]<stderr>:+ kill_pserver2_exit
Wed Sep 13 18:19:44 2017[1,16]<stderr>:+ ps aux
Wed Sep 13 18:19:44 2017[1,16]<stderr>:+ grep paddle_pserver2
Wed Sep 13 18:19:44 2017[1,16]<stderr>:+ grep paddle_cluster_job
Wed Sep 13 18:19:44 2017[1,16]<stderr>:+ grep -v grep
Wed Sep 13 18:19:44 2017[1,16]<stderr>:+ cut -c10-14
Wed Sep 13 18:19:44 2017[1,16]<stderr>:+ xargs kill -9
Wed Sep 13 18:19:44 2017[1,16]<stderr>:+ log_fatal 'paddle_trainer failed kill paddle_pserver2 and exit'
Wed Sep 13 18:19:44 2017[1,16]<stderr>:+ echo '[./common.sh : 399] [kill_pserver2_exit]'
Wed Sep 13 18:19:44 2017[1,16]<stderr>:[./common.sh : 399] [kill_pserver2_exit]
Wed Sep 13 18:19:44 2017[1,16]<stderr>:+ echo '[FATAL]: paddle_trainer failed kill paddle_pserver2 and exit'
Wed Sep 13 18:19:44 2017[1,16]<stderr>:[FATAL]: paddle_trainer failed kill paddle_pserver2 and exit
Wed Sep 13 18:19:44 2017[1,16]<stderr>:+ get_stack
Wed Sep 13 18:19:44 2017[1,16]<stderr>:+ set +x
Wed Sep 13 18:19:44 2017[1,16]<stderr>:

**Comment by pkuyym** [comment]
请确保模型可以在local执行
> Wed Sep 13 18:24:04 2017[1,6]<stderr>:+ python27-gcc482/bin/python conf/trainer_config.conf
> Wed Sep 13 18:24:07 2017[1,6]<stderr>:F0913 18:24:07.315513  3631 utilities.cc:324] Check failed: !IsGoogleLoggingInitialized() You called InitGoogleLogging() twice!

**Comment by zhouksh** [comment]
确实init 了两次，谢谢帮忙！
