### ISSUE TITLE
How to set the default value of a std::vector<int> attribute

### ISSUE THREAD

**Issue by Xreki** [PaddlePaddle/Paddle#4077]
In some operators, we may need `attributes` of which the type is `std::vector<int>`. We can define them in C++ code as follows:
```cpp
    AddAttr<std::vector<int>>("xNumColDims", "Some comments");
    AddAttr<std::vector<int>>( "wNumColDims", "Some comments");
```

So, the problem is: we don't know the length in advance, **"how to set the default value"**.

**Comment by Yancey1989** [comment]
Maybe we can just set an empty vector as the default value: 
```C++
AddAttr<std::vector<int>>("xNumColDims", "Some comments").SetDefault(std::vector<int>{})
```
And call `vector::reserve()` in Kernel Code.

**Comment by Xreki** [comment]
@Yancey1989 It works. Thanks.
