### ISSUE TITLE
编译v2.2.2 with TensorRT 出错

### ISSUE THREAD

**Issue by erikguo** [PaddlePaddle/Paddle#40797]
编译v2.2.2 with TensorRT 出错

环境：
CUDA 11.5.0
TensorRT 8.2.1.8
gcc 8.4

结果：
In file included from /workspace/Paddle/paddle/fluid/platform/stream/cuda_stream.cc:17:
/workspace/Paddle/paddle/fluid/platform/device_context.h:64:10: fatal error: unsupported/Eigen/CXX11/Tensor: No such file or directory
 #include "unsupported/Eigen/CXX11/Tensor"
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [paddle/fluid/platform/stream/CMakeFiles/cuda_stream.dir/build.make:76: paddle/fluid/platform/stream/CMakeFiles/cuda_stream.dir/cuda_stream.cc.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:5754: paddle/fluid/platform/stream/CMakeFiles/cuda_stream.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....

**Comment by JZZ-NOTE** [comment]
看 log 可能是编译的时候下载 Eigen 没有成功，可以重新编译试试。

**Comment by yang131313** [comment]
你好，现在Paddle已经有编译好的安装包了，请问你在什么任务场景下需要编译Paddle呀？比如是需要新增算子、还是需要修改飞桨源代码，或者有什么其他的用途呢？
