### ISSUE TITLE
"+=, -=" 等运算符号与torch表现不一致

### ISSUE THREAD

**Issue by ZHUI** [PaddlePaddle/Paddle#40825]
如图所示：

![image](https://user-images.githubusercontent.com/16911935/159441637-35289b08-d6df-49ca-8470-78a8b6e514c6.png)

torch默认是 inplace 操作。

**Comment by seemingwang** [comment]
inplace的操作目前我们还在进一步完善，但问题里的功能目前还不支持。
对您的问题，暂时这样处理一下，能让2者一致。
```python
import paddle
import torch
l = paddle.to_tensor(1.0)
r = torch.tensor(1.0)

def f(x):
    x -=x
    return x
l = f(l)
r = f(r)
print(l)
print(r)
```
