### ISSUE TITLE
安装结束出现这些结果，正常吗？

### ISSUE THREAD

**Issue by ZZHHogan** [PaddlePaddle/Paddle#40839]
安装结束出现这些结果，正常吗？

![image](https://user-images.githubusercontent.com/40531744/159615074-4fad786f-ade6-4cc6-b308-31c403ef8833.png)

    1）PaddlePaddle版本：paddlepaddle-gpu   2.2.2.post111

    2）CPU：请提供CPU型号，MKL/OpenBlas/MKLDNN/等数学库的使用情况
    3）GPU：3090   cuda 11.1 cudnn 8.0
    4）系统环境：Linux version 5.4.0-104-generic (buildd@ubuntu) (gcc version 7.5.0 (Ubuntu 7.5.0-3ubuntu1~18.04)) #118~18.04.1-Ubuntu SMP Thu Mar 3 13:53:15 UTC 2022

- 安装方式信息：
1）直接使用pip安装

**Comment by kuizhiqing** [comment]
你好，这个提示不影响使用。如在后续使用过程中发现问题欢迎再次提交issue。
