### ISSUE TITLE
训练运行paddelpaddel-gpu时报错

### ISSUE THREAD

**Issue by ghost** [PaddlePaddle/Paddle#40837]
- 版本、环境信息：
    1）PaddlePaddle版本：paddlepaddle-gpu==1.6.3.post107
    2）GPU：预测若用GPU，RTX2080ti、CUDA 10.2和CUDNN  7.6
    4）系统环境：windows  Python3.6
 
- 训练信息
    1）单机  单卡 
    2）显存信息
    3）Operator信息
 

![7ZY 66~ XI~{BJH~NDHWGVL](https://user-images.githubusercontent.com/57668414/159606874-a1429866-7154-4784-a628-954faee4e024.png)

**Comment by ghost** [comment]
求求了，csdn上也查不到

**Comment by kuizhiqing** [comment]
目前1.6.3版本已不再维护，请安装新版本 paddle 使用。

https://www.paddlepaddle.org.cn/install/quick?docurl=/documentation/docs/zh/install/docker/linux-docker.html
