### ISSUE TITLE
cross_entropy_op output 的shape 设置是不是有问题？

### ISSUE THREAD

**Issue by lcy-seso** [PaddlePaddle/Paddle#4084]
https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/operators/cross_entropy_op.cc#L32

下面这一行：
```cpp
ctx.Output<Tensor>("Y")->Resize({X->dims()[0]});
```
是否应该设置为：
```cpp
ctx.Output<Tensor>("Y")->Resize({X->dims()[0],1});
```

**Comment by Canpio** [comment]
同意。即使是一条直线，也应该写成两维的形式，从而明确到底是“1个n维的sample”还是“n个1维的sample”
