### ISSUE TITLE
Paddle.sum 在进行反向梯度计算的时候通过改变参数keepdim导致结果不一致

### ISSUE THREAD

**Issue by Li-fAngyU** [PaddlePaddle/Paddle#40850]
在AI Studio的BML上进行测试的时候发现问题。当令y = paddle.sum(x, keepdim=True)， dx = paddle.grad(y, x) 结果不固定，且大多数时候是错误的。

设备:CPU (AMD 5600G)
paddle版本为:2.2.2
python版本为:3.7
测试代码：
import paddle 
import numpy as np

x_shape = [2, 3, 4, 5]
x = np.random.uniform(-1, 1, x_shape).astype(np.float32)
x = paddle.to_tensor(x, stop_gradient=False)
y = paddle.sum(x, keepdim=True)
dx = paddle.grad(y, x)[0].numpy()
y1 = paddle.sum(x, keepdim=False)
dx1 = paddle.grad(y1, x)[0].numpy()
print(dx.sum(), dx1.sum())

输出结果经常是 2.0 120.0(错误结果)  有时候又是 120.0 120.0(正确结果)。

**Comment by kuizhiqing** [comment]
你好，经过多次实验，无法复现该问题。希望能提供更多信息以排查。

**Comment by Li-fAngyU** [comment]
谢谢你的回复，运行代码在这个[BML项目](https://aistudio.baidu.com/aistudio/projectdetail/3673782?channelType=0&channel=0)里。

**Comment by Li-fAngyU** [comment]
我发现只有在设备为cpu的情况下才会出现这个问题，如果BML启动环境是GPU的话输出结果就都是120 120

**Comment by TCChenlong** [comment]
目前测试 develop 是没有问题的；可以试试在 BML 中手动安装一下 develop 包~

**Comment by Li-fAngyU** [comment]
好的

**Comment by Li-fAngyU** [comment]
@TCChenlong 是的, 当我在BML里安装develop版本的paddle结果就正常了，但如果是默认的2.2.2的paddle还是会出现这个问题。
当我在本地进行测试的时候，即使我安装的是develop版本还是会出现上述的错误结果(AMD平台)。
![无标题](https://user-images.githubusercontent.com/56572498/160047759-c12e9650-8488-42a8-b707-4e10e44645a5.png)

**Comment by TCChenlong** [comment]
可以提供一下 CPU 型号么？方便我们复现问题

**Comment by Li-fAngyU** [comment]
AMD 5600G

**Comment by jiweibo** [comment]
您好，目前在最新的develop上编译测试(noavx版本的包，模拟AMD机器运行环境)仍无法复现，最新的develop应该已经修复了这个问题哈！

**Comment by Li-fAngyU** [comment]
好的
