### ISSUE TITLE
求使用飞桨ai studio复现神经网络相关书籍代码

### ISSUE THREAD

**Issue by yuwoyizhan** [PaddlePaddle/Paddle#40877]
我在京东搜索神经网络时,发现很多相关书籍.飞桨相关的书籍只有2本,而且都是几年前的书籍了,肯定使用静态图编程,听说5月份有飞桨书籍出版,适配动态图,这个有进一步消息吗?
神经网络那么多书籍,我想现在很多人都是靠看书入门神经网络,甚至深入学习神经网络的.我虽然不知道神经网络书籍的作者都用什么深度学习框架编写书籍中的代码,但我猜测,绝大多数书籍不是用飞桨框架编写代码的.我认为,多数书籍虽然会提供代码,但是不会提供飞桨框架的代码.
我希望你们可以使用飞桨框架,在ai studio实现神经网络相关书籍的代码,如果代码能加点注释就更好了,没有也无所谓.https://aistudio.baidu.com/aistudio/projectdetail/231146,可以参考这个链接,一本书籍作为一个合集,合集标题就叫做某某书籍的项目合集,这样搞几十个合集就把几十本书的代码都编写出来了.我相信,复现那些书籍的代码,对你们飞桨的开发者来说,轻轻松松,一个开发者15天就可以创建一本书籍的代码合集,这对于我们入门飞桨有着很大的好处.这对于推广飞桨框架也有着巨大好处.
市面上神经网络相关书籍非常多,或许你们可以调研一下,选择最热门的10本书左右,在ai studio编写代码合集.
你们搞黑客马拉松,或者开发飞桨API,很多我都是看中文简介都看不懂,更不用说读这些东西的代码了.我相信,编写书籍代码对你们来说,能力上绝对是轻轻松松,至于时间和精力上,我认为肯定比做视频快多了,毕竟视频需要准备很多工作,而复现书籍代码只要准备那本书,打开ai studio,而且做视频教学,需要很多剪辑,文字上屏幕等工作,复现书籍代码只需要编写代码.那些书籍代码的复现,对你们来说,应该不要太简单,哈哈哈哈.

**Comment by Baibaifan** [comment]
好的，建议我会反馈，谢谢

**Comment by yuwoyizhan** [comment]
@Baibaifan 我还在强化学习parl提了issue,但是工作人员告诉我,是否复现书籍代码,是由飞桨paddle决定的,让我在这里提issue.我知道飞桨有很多开发套件,但我认为,神经网络书籍和强化学习书籍是最应该复现的,神经网络是其他所有套件的基础.至于强化学习,目前飞桨无论是项目,开发文档,还是视频教学,书籍,都是非常少的,相比其他套件来说.举个例子,ai studio上面的强化学习有多少项目?排名第一的是一个股票项目,将近一年前的事情了.
很多人入门某个行业,都是靠一本书籍的,所以我希望你们可以选择2本神经网络的书籍,还有2个强化学习的书籍,在ai studio复现代码,谢谢.这应该对于你们飞桨提供开发者人数很有帮助,毕竟现在框架太多了,很多书籍作者都不是使用飞桨框架.而且这事情对你们来说,难度不大,谢谢.
一本书籍在身边,看懂了,做些标注,代码也有,以后我需要使用书籍相关代码,就看飞桨相关项目就行了,需要书籍的内容,身边那本书拿来看看就搞定了,谢谢.

**Comment by yuwoyizhan** [comment]
@Baibaifan 最后再说一句,如果你们实在不愿意由百度飞桨官方复现书籍代码,可以考虑学习黑客马拉松,出点钱找人做啊,哈哈哈哈.

**Comment by yuwoyizhan** [comment]
那些优秀的书籍,有很多人购买,这你们应该有所了解,复现神经网络书籍和强化学习书籍的代码,对于推广飞桨和parl,很有帮助.还有一点想说,我认为,复现书籍代码,绝不是作者的责任,而是深度学习平台的责任,比如飞桨,pytorch,tensorflow等.毕竟作者使用一个开源平台复现代码就行了,可是其他平台的开发者呢?又该怎么办?为了一本书籍,转换平台?还是多学习一个平台的代码?深度学习平台很多东西是相通的,甚至很多理论,算法都相似,耗费巨大力气学习多个平台,不好吧?还不如专心学习一个平台,跟某个平台荣辱与共.

**Comment by yuwoyizhan** [comment]
@[kuizhiqing](https://github.com/kuizhiqing)

**Comment by yuwoyizhan** [comment]
@[seemingwang](https://github.com/seemingwang)

**Comment by yuwoyizhan** [comment]
@[esythan](https://github.com/esythan)

**Comment by wulei123456789** [comment]
@yuwoyizhan 同学您好，感谢您对飞桨的支持，从您的提问中，我们已经感受到了您迫切想学习好飞桨的热情，感谢感谢。
我猜想您可能是在学习飞桨的时候，遇到了一些小困难，我分别回复一下，希望能帮助到您。

1）关于《零基础实践深度学习》书籍：目前已经在清华出版社出版中，适配飞桨2.0版本，代码使用动态图，计划5月底上市，但是可能会根据出版社的时间微调，电子书会考虑同步上市，在此之前，您也可以先关注AI Studio在线课程。
2） 关于复现市面上神经网络书籍：复现书籍代码可能比咱们想象中复杂，需要作者授权，但是飞桨已经了解到开发者需求，并积极推进中。目前飞桨已经在与多名知名学者合作，开发体系化的案例与实践课程和书籍，预计5月底会陆续发布。在课程中会包含您关注的：经典的神经网络、强化学习经典算法的Paddle实现。
3）在此之前，您可以学习已经在AI Stuido上开源的《人工智能导论：案例与实践》课程，这套课程是浙江大学吴飞老师的著作《人工智能导论：模型与算法》的配套实验课程，您可以结合书籍中的理论和课程中的实践一同学习，我想一定会事半功倍。课程链接：https://aistudio.baidu.com/aistudio/education/group/info/25224

再次感谢您的建议和对飞桨的支持：）
