### ISSUE TITLE
零基础实践深度学习

### ISSUE THREAD

**Issue by yuwoyizhan** [PaddlePaddle/Paddle#40889]
https://www.paddlepaddle.org.cn/tutorials/projectdetail/3465990
这个链接里面有提到,《零基础实践深度学习》再版书籍（适配飞桨2.0版本）已经在出版社审核中，预计2022年5月底上市。
请问有进一步消息吗?确定5月会上市吗?
还有一个问题,你们打算出一本强化学习的书籍吗?纸质书,电子书都行,现在很多人只开发电子书,不出纸质书了,毕竟时间精力有限.
https://zh-v2.d2l.ai/
这个链接就是个电子书,纸质书还没出版,一个电子书,30.9k个star,你们可以学习学习,牛啊,电子书也很吃香的,制作一个电子书,肯定比纸质书容易多了,花费的时间精力少的多.维护代码或者项目,或者勘误表,都容易得多.

**Comment by Baibaifan** [comment]
请以官网消息为准，您的意见已经记录，感谢您的反馈。

**Comment by yuwoyizhan** [comment]
@Baibaifan 大佬,你好,感谢你的回答.我提一句,我建议出版书籍,还有复现别的作者的书籍的代码,这是两个不同的建议,别搞成一个建议啊.希望你们可以考虑考虑,如果复现多个作者书籍,很多开发者,特别是刚入门的开发者,都将掌握在飞桨手里了,哈哈哈哈.

**Comment by wulei123456789** [comment]
@yuwoyizhan 同学您好，非常感谢您对飞桨的关注和支持，关于您提到的几个问题，我具体回复下：

1）《零基础实践深度学习》课程配套的书籍出版工作正在进行中，具体上市时间可能要根据清华社那边的进度稍有调整，待上市前，我们会第一时间在AI Studio知会到大家，您也可以在5月份后关注；
2）电子书的确是目前比较符合开发者需求的一种形式，我们也会和这本书的作者（毕然老师）商量下，同步上线《零基础实践深度学习》电子书，方便大家下载或在线阅读。
3）飞桨目前正在和李沐老师合作，开发《动手学深度学习》Paddle版，计划5月份左右在AI Studio和D2L repo同步上线，您可以提前关注。

再次感谢您对飞桨的支持，以及对飞桨教育产品的建议，欢迎多多沟通交流：）
