### ISSUE TITLE
tinypose找不到tinypose的训练代码paddle python实现！

### ISSUE THREAD

**Issue by 2050airobert** [PaddlePaddle/Paddle#40903]
hi，

    我只看到github上有tinypose的 yml文件，但是如果想要用自己的数据，训练模型，是否可以提供下原始训练代码？

BR

**Comment by Baibaifan** [comment]
关注下 这个仓哈https://github.com/PaddlePaddle/PaddleDetection 
![image](https://user-images.githubusercontent.com/39549453/159900839-60521f5b-91da-4ad1-8afe-8e367134c4c4.png)
