### ISSUE TITLE
pip无法下载paddlepaddle

### ISSUE THREAD

**Issue by terrancraft** [PaddlePaddle/Paddle#40996]
从官网给的下载源无法下载paddle
- 版本、环境信息：
    1）PaddlePaddle版本：2.2
    2）CPU：intel core i7
    3）GPU：rtx2080 | cuda 11.2
    4）系统环境：ubuntu 18.04

- 安装方式信息：
 pip安装提示失败
 指令: python -m pip install paddlepaddle-gpu==2.2.2.post112 -f https://www.paddlepaddle.org.cn/whl/linux/mkl/avx/stable.html  
 返回: Could not find a version that satisfies the requirement paddlepaddle-gpu==2.2.2.post112 (from versions: none)

望解答～谢谢！

**Comment by wuhuachaocoding** [comment]
您好，根据您提供的安装指令，我这边使用python3.7可以正常下载。请检查你的python版本和网络环境。也可以直接浏览器点开https://www.paddlepaddle.org.cn/whl/linux/mkl/avx/stable.html链接，直接下载你需要的paddle whl包，直接安装。

**Comment by terrancraft** [comment]
python 3.9下载不了，37可以下载 问题解决

**Comment by wuhuachaocoding** [comment]
你好，经测试，python3.9可以正常安装。
