### ISSUE TITLE
执行set_device后，模型会报OSError: (External) CUBLAS error(13).    [Hint: 'CUBLAS_STATUS_EXECUTION_FAILED'

### ISSUE THREAD

**Issue by zhangyimi** [PaddlePaddle/Paddle#41019]
```
import paddle
model = Model()
paddle.get_device() # gpu:0
paddle.set_device("gpu:1")
model.forward(xx)
```
执行上面的代码会报：
OSError: (External) CUBLAS error(13). 
  [Hint: 'CUBLAS_STATUS_EXECUTION_FAILED'. 

但是如果在第一行执行`paddle.set_deivce("gpu:1")` 就不会报错。
或者将第四行改为`paddle.set_deivce("gpu:0")`或`paddle.set_deivce("cpu")`也不会报错。

看起来是因为先初始化的模型在gpu:0，又将device设置为gpu:1导致的，想要请教下这个问题该如何解决，或者怎样将model拷贝到gpu:1让代码不报错。

**Comment by wuhuachaocoding** [comment]
使用model.to("gpu:1")接口

import paddle
model = paddle.nn.Linear(10,2)
paddle.get_device()
model.to("gpu:1")
paddle.set_device("gpu:1")
x = paddle.rand([8,10])
model(x)

**Comment by zhangyimi** [comment]
调用model.to后，会打印in ParamBase copy_to func很多次。
![a826eb27fb4fb3672a7aa27777d4ed47](https://user-images.githubusercontent.com/20926735/160361732-f2c40856-7621-4810-b197-11649a6798b4.png)
