### ISSUE TITLE
关于PaddlePaddle1.6中模型使用动态图中存在使用numpy的片段，转换静态图无法使用的问题。

### ISSUE THREAD

**Issue by iiot-tbb** [PaddlePaddle/Paddle#41034]
我通过动态图的模型进行训练，其中存在一些numpy的操作，在转换成静态图的过程中报错无法在静态图中使用numpy，但是1.6中如果使用tensor没有办法进行像numpy一样的赋值 索引操作，所以这个问题有办法解决吗？

肯定有人问我为什么要做这样的事情，因为我想把动态图转换为静态图后用paddle server进行部署。

**Comment by wuhuachaocoding** [comment]
您好，听你的描述，是静态图的用法不对，"tensor没有办法进行像numpy一样的赋值 索引操作" ，静态图需要修改program完成相应的操作,通常是插入相应的op完成相应的操作，与动态图有区别。比如插入index_select op完成索引操作。

**Comment by iiot-tbb** [comment]
> 

嗯嗯，但是我的模型是用动态图搭的，因为我看大片在1.6的文档中关于动态图部分写到可以直接用动态图的代码进行操作。
那我如何用这个动态图训练好的模型部署成为静态图呢。
<img width="469" alt="image" src="https://user-images.githubusercontent.com/51875523/160388478-17bacec7-8e0d-4864-b08f-381ff72fd61c.png">


https://www.paddlepaddle.org.cn/documentation/docs/zh/1.6/user_guides/howto/dygraph/DyGraph.html

**Comment by wuhuachaocoding** [comment]
参考官网说明文档完成动转静：https://www.paddlepaddle.org.cn/documentation/docs/zh/guides/04_dygraph_to_static/index_cn.html
