### ISSUE TITLE
怎样在自己搭建的网络中添加batch normalize layer

### ISSUE THREAD

**Issue by dockiHan** [PaddlePaddle/Paddle#4104]
最近刚刚了解batch normalize, 关于batch norm layer 的使用有一点疑惑：
1.如果在自建网络的第一个fc层之后加入batch normalize layer 是否还需要对数据进行归一化预处理？
2.我做了问题1的尝试之后发现加不加batch norm layer的效果好像差别不大，cost值都特别大，在10W水平（损失函数mse）

**Comment by yeyupiaoling** [comment]
这里有个例子用到了BN层:[https://github.com/PaddlePaddle/book/blob/develop/03.image_classification/vgg.py#L42](https://github.com/PaddlePaddle/book/blob/develop/03.image_classification/vgg.py#L42)
我在使用的时候,加上BN层反而没办法收敛,我还是去掉了

**Comment by gongweibao** [comment]
Feel free to reopen it.
