### ISSUE TITLE
是否有torch那样的.to接口，可以把tensor从GPU转到CPU的接口

### ISSUE THREAD

**Issue by lidingke** [PaddlePaddle/Paddle#41050]
这是torch的操作可以将tensor在cpu和gpu之间转换。
>>> cuda0 = torch.device('cuda:0')
>>> tensor.to(cuda0)
不知道paddle是否有类似的操作，我的目的是希望将部分特征图转到CPU内存上存下来做其他操作。

**Comment by firestonelib** [comment]
您好，paddle 通过设置 place 将 tensor 在不同的设备间转换，具体用法入下：
`cpu = paddle.CPUPlace()
 paddle.to_tensor(x, dtype='int32', place=cpu)`
to_tensor 文档中有详细介绍：https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/to_tensor_cn.html#to-tensor
