### ISSUE TITLE
[Pickle can't dump Tensor] TypeError: can't pickle Tensor objects

### ISSUE THREAD

**Issue by Theheavens** [PaddlePaddle/Paddle#41107]
我又看到类似的问题，但是不太相关：#34451, #34688
- 版本、环境信息：
    1）PaddlePaddle版本：2.2.2
    2）CPU：Intel(R) Xeon(R) CPU E5-2686 v4 @ 2.30GHz
    3）GPU：V100
    4）系统环境：Linux
- 训练信息
    1）单机，单卡

The code snippet
> import pickle
> import paddle
> x = paddle.to_tensor([1,2,3])
> with open('./test.txt', 'wb') as f:
> 	pickle.dump(x, f)

The Error info:
> /home/ubuntu/anaconda3/envs/ggl/lib/python3.7/site-packages/paddle/tensor/creation.py:130: DeprecationWarning: `np.object` is a deprecated alias for the builtin `object`. To silence this warning, use `object` by itself. Doing this will not modify any behavior and is safe. 
> Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
>   if data.dtype == np.object:
> Traceback (most recent call last):
>   File "/home/ubuntu/openi/GammaGL/tests/data/test_dataset.py", line 6, in <module>
>     pickle.dump(x, f)
> TypeError: can't pickle Tensor objects

**Comment by firestonelib** [comment]
可以试下
```
import pickle
import paddle
x = paddle.to_tensor([1,2,3]).numpy()
with open('./test.txt', 'wb') as f:
    pickle.dump(x, f)
```

**Comment by firestonelib** [comment]
您好，paddle 目前不支持将 tensor 直接 dump，可以把 paddle tensor 转为 numpy 再 dump：
`
import pickle
import paddle
x = paddle.to_tensor([1,2,3])
with open('./test.txt', 'wb') as f:
    pickle.dump(x.numpy(), f)`

**Comment by Theheavens** [comment]
感谢回复，另外我也注意到可以使用paddle.save & load来保存Tensor。
我也关注到一些保存机制：
https://www.paddlepaddle.org.cn/documentation/docs/zh/faq/save_cn.html#paddle-save-state-dict-layer-tensortensorlisttupledict
我们定义了一个类，其实例中包含动态的Tensor，经过save 和load以后。Tensor变成了(str, numpy.array)。我希望load出来后还是Tensor，请问应该怎么做？ @firestonelib

**Comment by firestonelib** [comment]
如果 save 保存的是纯 paddle Tensor 而没有转 numpy，那 load 加载得到的数据经过 paddle.to_tensor 转换后会得到相应的 Tensor。
