### ISSUE TITLE
Need to use input of large size to test CUDA kernel

### ISSUE THREAD

**Issue by Xreki** [PaddlePaddle/Paddle#4111]
In current unit tests, all the inputs are set to some small size, because the `grad_check` process is too slow, and large size will also fail the `grad_check`. 
But in CUDA kernel, the block size is often set to 512, or even large. With small input size, all the computation may be done on one block. Thus, we need inputs of large size to test CUDA kernels.

**Comment by lcy-seso** [comment]
I also found a large layer size is easy to break the gradient check.
