### ISSUE TITLE
Nano开发板，安装系统后py3.7.1 与官方的最低3.6不匹配？ 一直安装不了推理库

### ISSUE THREAD

**Issue by Wei-JL** [PaddlePaddle/Paddle#41113]
Nano开发板，安装系统后py3.7.1 与官方的 https://paddleinference.paddlepaddle.org.cn/user_guides/download_lib.html#python 
最低3.6不匹配，安装conda后指定安装py版本3.6.9同样不匹配，球球了，官方大大出一个py3.7的Nanogpu推理库吧

**Comment by Wei-JL** [comment]
目前安装完成nano的系统后，自带的python版本是3.7.1，安装conda之后新建环境py3.6.9，pip导入一直显示非法指令(已转核心储存)，但新建3.7以上的环境就可以正常导入py的依赖包。但是安装3.7以上的py之后，又不能安装飞桨2.2.2 cp3.6的whl了，报错不支持导入。尝试过卸载系统自带的python版本是3.7.1，但是整个linux系统直接崩了，在conda里面又不能下载py3.6.9用pip指令或者conda指令卡主好几天了。  望能够快速解答 谢谢

**Comment by wangye707** [comment]
@Wei-JL 最新的jetpack4.6.1+python3.7开始部署了，争取本次新版本中推出
