### ISSUE TITLE
不允许一个文件中包含多个Op的限制

### ISSUE THREAD

**Issue by guoshengCS** [PaddlePaddle/Paddle#4113]
[OP编写注意事项](https://github.com/PaddlePaddle/Paddle/blob/develop/doc/howto/dev/new_op_cn.md#注意事项)中 `不允许一个文件中包含多个Op` 这个限制能否放宽下，感觉类似Activation这种放在一个文件里好些，在其他一些框架中也是会在一个文件中包含多个Op的。

**Comment by luotao1** [comment]
可以的，Activatin那个PR #4071 修改了operator/CMakeLists，等它合入后会对应修改文档的。
