### ISSUE TITLE
PaddlePaddle 2.2.2版本将MultiHeadedAttention转换成inference格式时出错

### ISSUE THREAD

**Issue by NYF-BRICK** [PaddlePaddle/Paddle#41142]
**Describe the bug**
在运行paddlespeech/s2t/exps/u2/bin/export.py脚本将Transformer模型转换成inference格式时出错。
是否PaddlePaddle 2.2.2版本不支持将MultiHeadedAttention转换成inference格式？

**Screenshots**
<img width="1200" alt="截屏2022-03-30 下午3 34 18" src="https://user-images.githubusercontent.com/30340135/160780382-16ac843f-00c4-4fc0-bf0b-e3f822be3aaf.png">

**Environment :**
- OS: macOS 12.2.1
- Python Version 3.9.11
- PaddlePaddle Version 2.2.2
- PaddleSpeech Version r0.1.1

**Additional context**
是否是PaddlePaddle版本过高的问题？

**Comment by GuoxiaWang** [comment]
@NYF-BRICK 好像 paddle 的 tensor 没有  .view  这个 API呢，是不是可以到 paddlespeech issue中问问？

**Comment by NYF-BRICK** [comment]
> @NYF-BRICK 好像 paddle 的 tensor 没有 .view 这个 API呢，是不是可以到 paddlespeech issue中问问？

对，我看了是paddlespeech中的`paddlespeech/s2t/modules/attention.py`中自己写了一个`MultiHeadedAttention`，其中用到的`view`的是`numpy`实现的，而`paddle.nn.MultiHeadAttention`则没有问题。与这个情况类似的还有`paddlespeech/s2t/models/u2/u2.py`中的`U2BaseModel.ctc_greedy_search`。

现在paddlepaddle的静态图转换对`numpy`的支持如何？

**Comment by GuoxiaWang** [comment]
@NYF-BRICK 内部反馈， paddlespeech issue 那边已经在跟踪该问题了 [1625](https://github.com/PaddlePaddle/PaddleSpeech/issues/1625)

**Comment by NYF-BRICK** [comment]
> @NYF-BRICK 内部反馈， paddlespeech issue 那边已经在跟踪该问题了 [1625](https://github.com/PaddlePaddle/PaddleSpeech/issues/1625)

嗯，那我把paddlepaddle这边的issue关掉。
