### ISSUE TITLE
在win7 64位系统下，使用Paddle_inference预测时，出现电脑卡死的情况

### ISSUE THREAD

**Issue by Sidney-Chow** [PaddlePaddle/Paddle#41155]
PaddlePaddle版本：CommitID：4ccd9a0a86ad550a861c954d70e28ef15741b310
CPU：Inter Core i5-4310U，使用MKL、MKLDNN库
 系统环境：win7 专业版 64位

程序执行到下图位置的时候就卡死了
![image](https://user-images.githubusercontent.com/85594963/160799745-766fb650-4ae7-4b5f-9415-a3e6f00aafa1.png)

**Comment by GuoxiaWang** [comment]
@Sidney-Chow 这是要做一件什么事？不太熟悉看不出来。

**Comment by Sidney-Chow** [comment]
这是PaddleSeg的c++版本，里面用到了Paddle_inference进行预测

**Comment by b3602sss** [comment]
> 这是PaddleSeg的c++版本，里面用到了Paddle_inference进行预测

请先试下最新2.2版本的paddle。如果还有问题 请提交一个复现问题的单测

**Comment by Sidney-Chow** [comment]
我尝试了官网下载的2.2版本 c++预测库，问题仍然存在。
预测库是在如下图中下载的：
![image](https://user-images.githubusercontent.com/85594963/161014494-6593f645-f147-4996-9e1b-a430c897a2f8.png)

另外，我定位到问题是在执行predictor_->Run()这个方法就会出现。
Predictor 类的Run()方法

**Comment by b3602sss** [comment]
> 我尝试了官网下载的2.2版本 c++预测库，问题仍然存在。 预测库是在如下图中下载的： ![image](https://user-images.githubusercontent.com/85594963/161014494-6593f645-f147-4996-9e1b-a430c897a2f8.png)
> 
> 另外，我定位到问题是在执行predictor_->Run()这个方法就会出现。 Predictor 类的Run()方法

请提交一个复现问题的单元测试 我们这边看下是什么问题
