### ISSUE TITLE
如何实现torch.Tensor.unfold

### ISSUE THREAD

**Issue by jerryuhoo** [PaddlePaddle/Paddle#41154]
paddle没有对应的API，虽然有nn.functional.unfold，但是这个的输入格式只支持[N, C, H, W]，请问是否有会有tensor.unfold的算子开发的计划？或者说应该怎么实现呢？

**Comment by GuoxiaWang** [comment]
@jerryuhoo 非常感谢反馈，计划方面我先咨询一下反馈到这

**Comment by GuoxiaWang** [comment]
@jerryuhoo  已经内部反馈

> （1）是否有会有tensor.unfold的算子开发的计划？

已经内部反馈了，这个会列入下一个版本开发计划，请关注新版本发布

> （2）应该怎么实现呢？

当前从API层没有很好的绕过方法

最后非常感谢给予使用反馈，谢谢

**Comment by jerryuhoo** [comment]
好的，感谢。目前暂时用nn.functional.unfold加各种reshape和transpose做了一个比较粗略的tensor.unfold，对维度的支持还是不够灵活，期待有paddle原生的tensor.unfold！

**Comment by GuoxiaWang** [comment]
> 好的，感谢。目前暂时用 nn.functional.unfold 加各种reshape和transpose做了一个比较粗略的tensor.unfold，对维度的支持还是不够灵活，期待有paddle原生的tensor.unfold！

好的，这种速度会受一定影响。确实可以先 reshape 成 4D，然后做操作。
你的目的就是分块是吗？

**Comment by jerryuhoo** [comment]
嗯对的，目前我只是需要对tensor里最后面的一个维度进行unfold。现在感觉速度还可以，之前试了下split和concat速度就非常慢了。

**Comment by westfish** [comment]
可以自定义一个基于paddle的unfold函数来实现torch.Tensor.unfold相同的功能
```
import paddle

def unfold(tensor, dimension, size, step=1):
    assert dimension < len(tensor.shape), 'dimension must be less than tensor dimensions'
    assert tensor.shape[dimension] >= size, 'size should not be greater than the dimension of tensor'
    
    slices = []
    for i in range(0, tensor.shape[dimension] - size + 1, step):
        start = [0] * len(tensor.shape)
        end = list(tensor.shape)
        start[dimension] = i
        end[dimension] = i + size
        axes = list(range(len(start)))
        slice = paddle.slice(tensor, axes, start, end)
        slices.append(slice)

    unfolded_tensor = paddle.stack(slices, axis=dimension)

    return unfolded_tensor
```

**Comment by kongdebug** [comment]
> 可以自定义一个基于paddle的unfold函数来实现torch.Tensor.unfold相同的功能
> 
> ```
> import paddle
> 
> def unfold(tensor, dimension, size, step=1):
>     assert dimension < len(tensor.shape), 'dimension must be less than tensor dimensions'
>     assert tensor.shape[dimension] >= size, 'size should not be greater than the dimension of tensor'
>     
>     slices = []
>     for i in range(0, tensor.shape[dimension] - size + 1, step):
>         start = [0] * len(tensor.shape)
>         end = list(tensor.shape)
>         start[dimension] = i
>         end[dimension] = i + size
>         axes = list(range(len(start)))
>         slice = paddle.slice(tensor, axes, start, end)
>         slices.append(slice)
> 
>     unfolded_tensor = paddle.stack(slices, axis=dimension)
> 
>     return unfolded_tensor
> ```

您好，这个函数在有些时候输出并不和torch一致，只在特定的时候一样
