### ISSUE TITLE
fuse_elewise_add_act_ops 不好使

### ISSUE THREAD

**Issue by sunvina** [PaddlePaddle/Paddle#41187]
- 版本、环境信息：
    1）PaddlePaddle版本：2.2
    2）CPU：![image](https://user-images.githubusercontent.com/51695603/160963637-c22b84cb-94a2-442f-8e5f-86f5862ab687.png)

    3）GPU：无
    4）系统环境：win10 ，py3.7

训练的模型转pb，想要融合elewise_add，没有成功

 paddle.enable_static()
        build_strategy = paddle.static.BuildStrategy()
        build_strategy.fuse_elewise_add_act_ops = True
        build_strategy.fuse_relu_depthwise_conv = True
        model = to_static(
            model,
            input_spec=[
                paddle.static.InputSpec(
                    shape=[None] + infer_shape, dtype="float32")
            ],build_strategy=build_strategy)

    paddle.jit.save(model, save_path)

**Comment by liutiexing** [comment]
您好，报错信息是啥？或者提供一个完整可复现环境，贴出的代码没有模型的

**Comment by sunvina** [comment]
![image](https://user-images.githubusercontent.com/51695603/160973086-cda2cc4e-9c76-46b6-87c8-e3789cd9fc28.png)
请问这三个节点可以融合在一起吗

**Comment by liutiexing** [comment]
后两个可以融合

**Comment by liutiexing** [comment]
fuse_elewise_add_act_ops 和 fuse_relu_depthwise_conv 二者之一生效，图就变了，另一个就无法生效了，我理解

**Comment by sunvina** [comment]
您好，我单独设置这两个也不生效，也不报错，就是不融合

**Comment by liutiexing** [comment]
您好，对应的开发人员已经不在了，如果必要，只能您把复现的python代码贴出来，然后我研究一下源代码分析咋回事了
