### ISSUE TITLE
Need to handle non-differentiable value in gradient check process.

### ISSUE THREAD

**Issue by QiJune** [PaddlePaddle/Paddle#4120]
Let's take abs(x) = |x| as an example. 0 is a non-differentiable point in abs function. So if our random value is very close to 0, it will cause error in gradient check.
```python
class TestAbs(OpTest):
    def setUp(self):
        self.op_type = "abs"
        x = np.random.uniform(-1, 1, [4, 4]).astype("float32")
        # Because we set delta = 0.005 in caculating numeric gradient,
        # if x is too small, such as 0.002, x_neg will be -0.003
        # x_pos will be 0.007, so the numeric gradient is unaccurate.
        # we should avoid this
        x[np.abs(x) < 0.005] = 0.02
        self.inputs = {'X': x}
        self.outputs = {'Y': np.abs(self.inputs['X'])}

    def test_check_output(self):
        self.check_output()

    def test_check_grad(self):
        self.check_grad(['X'], 'Y', max_relative_error=0.007)
```

**Comment by guoshengCS** [comment]
在caffe2的reduce_op的单测中max和min貌似是没有添加梯度检测的https://github.com/caffe2/caffe2/blob/81b1bf7fedb91b659511d82ddce1b103b0746c98/caffe2/python/operator_test/reduction_ops_test.py#L130

**Comment by wangkuiyi** [comment]
I think we must not use random number generator in unit tests.  This would cause some weird observation like a PR happens to pass the CI, but after merging other PRs fail.

Let us use some meaningful test cases in this case.  For example:

- 0
- + min_float32
- - min_float32
- + max_float32
- - max_float32

**Comment by lcy-seso** [comment]
max 和 min 没有数值梯度，不加梯度检测是非常合理的。

**Comment by QiJune** [comment]
@wangkuiyi 
- Case 1, operator has some non-differentiable point (abs/relu/etc): Our gradient check unit test does not support get the gradient of non-differentiable point. After we generate random input test data, we should make a filter to clear point which is very close to non-differentiable point. 

- Case 2, operator has no numeric gradient (max/min): We just do not add gradient checker unit tests.
