### ISSUE TITLE
paddle 是否支持对embedding layer 进行sparse 更新

### ISSUE THREAD

**Issue by zhouksh** [PaddlePaddle/Paddle#4123]
在paddle local 版本性能测试中，对embedding layer 的宽度调整为原来1/2，性能有将近一半的提升。所以我猜测在我的网络配置中，embedding layer 使用了dense 更新。请问paddle是否支持对embedding layer 的sparse 更新，如果支持的话，请提供demo，谢谢！

**Comment by guoshengCS** [comment]
应该是支持的，这里是示例 https://github.com/PaddlePaddle/Paddle/blob/b0c6331cde727f2e3097c89dcfe07b74325451af/doc/faq/src/word2vec_config.py#L5

**Comment by HynUx** [comment]
求科普, 请问哪里有关于embeding的sparse update具体实现的文档?
同时求问, 我在将embeding层参数attr设为sparse_update=True时,  optimizer迭代时却报错?(用Adam和Momentum都是这样)
F1127 15:06:49.893347  9412 FirstOrderOptimizer.cpp:268] Check failed: sparseId == -1UL Sparse update is not supported
*** Check failure stack trace: ***
    @     0x7faa546f727d  google::LogMessage::Fail()
    @     0x7faa546fad2c  google::LogMessage::SendToLog()
    @     0x7faa546f6da3  google::LogMessage::Flush()
    @     0x7faa546fc23e  google::LogMessageFatal::~LogMessageFatal()
    @     0x7faa54d87b17  paddle::AdamParameterOptimizer::update()
    @     0x7faa54d761d8  paddle::SgdThreadUpdater::threadUpdateSparse()
    @     0x7faa54d76aa4  _ZNSt17_Function_handlerIFvimEZN6paddle16SgdThreadUpdater11finishBatchEfEUlimE_E9_M_invokeERKSt9_Any_dataim
    @     0x7faa546570ec  _ZNSt6thread5_ImplISt12_Bind_simpleIFZN6paddle14SyncThreadPool5startEvEUliE_mEEE6_M_runEv
    @     0x7faa5bcb38a0  execute_native_thread_routine
    @     0x7faae70f71c3  start_thread
    @     0x7faae671f12d  __clone
    @              (nil)  (unknown)
