### ISSUE TITLE
CPU支持AVX，怎么编译报building AVX version without NOAVX core

### ISSUE THREAD

**Issue by llooper-dev** [PaddlePaddle/Paddle#41246]
1）PaddlePaddle版本
git clone -b v2.2.2 https://github.com/PaddlePaddle/Paddle.git

2）本地编译：
cmake  .. \
	-DCMAKE_INSTALL_PREFIX=/opt/lib/Paddle \
    -DWITH_CONTRIB=OFF \
    -DWITH_MKL=ON \
    -DWITH_MKLDNN=ON  \
    -DWITH_GPU=OFF  \
    -DWITH_NCCL=OFF  \
    -DWITH_RCCL=OFF  \
    -DWITH_TESTING=OFF \
    -DCMAKE_BUILD_TYPE=Release \
    -DWITH_INFERENCE_API_TEST=OFF \
    -DON_INFER=ON \
    -DWITH_PYTHON=ON

3）CPU：
Intel(R) Xeon(R) Gold 5220R CPU @ 2.20GHz

flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon rep_good nopl eagerfpu pni pclmulqdq ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch invpcid_single fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm mpx avx512f rdseed adx smap clflushopt clwb avx512cd xsaveopt xsavec xgetbv1 arat

- 问题描述:

-- Paddle version is 2.2.2
-- Enable Intel OpenMP with /home/aifer/.cppbuild/Paddle/build/third_party/install/mklml/lib/libiomp5.so
-- On inference mode, will take place some specific optimization.
-- commit: b031c38
-- branch: HEAD
WITH_DLNNE:
-- MESSAGE: This is just a message for publishing release.
      You are building AVX version without NOAVX core.
      So the wheel package may fail on NOAVX machine.
      You can add -DNOAVX_CORE_FILE=/path/to/your/core_noavx.* in cmake command
      to get a full wheel package to resolve this warning.
      While, this version will still work on local machine.
CMake Error at python/CMakeLists.txt:126 (message):
  patchelf not found, please install it.

  For Ubuntu, the command is: apt-get install -y patchelf.

-- Configuring incomplete, errors occurred!

CPU明明是支持AVX，怎么编译报building AVX version without NOAVX core

**Comment by llooper-dev** [comment]
POCKETFFT_INCLUDE_DIR is /home/aifer/.cppbuild/Paddle/build/third_party/pocketfft/src
-- Paddle version is 2.2.2
-- Enable Intel OpenMP with /home/aifer/.cppbuild/Paddle/build/third_party/install/mklml/lib/libiomp5.so
-- On inference mode, will take place some specific optimization.
-- commit: b031c38
-- branch: HEAD
WITH_DLNNE:
-- MESSAGE: This is just a message for publishing release.
      You are building AVX version without NOAVX core.
      So the wheel package may fail on NOAVX machine.
      You can add -DNOAVX_CORE_FILE=/path/to/your/core_noavx.* in cmake command
      to get a full wheel package to resolve this warning.
      While, this version will still work on local machine.
-- Configuring done
-- Generating done
-- Build files have been written to: /home/aifer/.cppbuild/Paddle/build

**Comment by llooper-dev** [comment]
> POCKETFFT_INCLUDE_DIR is /home/aifer/.cppbuild/Paddle/build/third_party/pocketfft/src -- Paddle version is 2.2.2 -- Enable Intel OpenMP with /home/aifer/.cppbuild/Paddle/build/third_party/install/mklml/lib/libiomp5.so -- On inference mode, will take place some specific optimization. -- commit: [b031c38](https://github.com/PaddlePaddle/Paddle/commit/b031c389938bfa15e15bb20494c76f86289d77b0) -- branch: HEAD WITH_DLNNE: -- MESSAGE: This is just a message for publishing release. You are building AVX version without NOAVX core. So the wheel package may fail on NOAVX machine. You can add -DNOAVX_CORE_FILE=/path/to/your/core_noavx.* in cmake command to get a full wheel package to resolve this warning. While, this version will still work on local machine. -- Configuring done -- Generating done -- Build files have been written to: /home/aifer/.cppbuild/Paddle/build

这样是编译成功了吧？

**Comment by jim19930609** [comment]
你好，这个编译提示没问题。你的CPU如果支持AVX指令集，那么cmake选项“WITH_AVX” 是默认打开的，因此编译出的机器码里是含有AVX指令的。

这个提示只是警告说：假如你把编出来的AVX wheel包安装到了没有AVX的机器上（比如另一台特别老的电脑），会跑不了。

**Comment by llooper-dev** [comment]
好的，谢谢

**Comment by zhangguotai** [comment]
@jim19930609 but this warning cause Makefile is created, i do not solve it

**Comment by zhangguotai** [comment]
@jim19930609 but this warning cause Makefile is not created, i do not solve it, make -j that is not executed
