### ISSUE TITLE
自定义外部gather算子报错

### ISSUE THREAD

**Issue by miemie2013** [PaddlePaddle/Paddle#41248]
- 版本、环境信息：
    1）PaddlePaddle版本：develop
    2）GPU：AIStudio V100

地址： https://aistudio.baidu.com/aistudio/projectdetail/3724521

写了个自定义外部算子gather，是根据2.0版本飞桨的gather实现的，实现了gather的二阶导数（还是gather）。依次点击上面的项目给出的4条命令，最后会报错：
```
======================== batch_000 ========================
ddd=0.000000
ddd=0.000000
ddd=0.000000
ddd=0.000000


--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
0   paddle::imperative::BasicEngine::Execute()
1   paddle::imperative::PreparedOp::Run(paddle::imperative::NameVariableWrapperMap const&, paddle::imperative::NameVariableWrapperMap const&, paddle::framework::AttributeMap const&, paddle::framework::AttributeMap const&)
2   phi::KernelImpl<void (*)(phi::GPUContext const&, phi::DenseTensor const&, phi::DenseTensor const&, phi::DenseTensor const&, paddle::optional<phi::DenseTensor const&>, paddle::optional<phi::DenseTensor const&>, int, phi::DenseTensor*, phi::DenseTensor*, phi::DenseTensor*), &(void phi::MultiplyDoubleGradKernel<float, phi::GPUContext>(phi::GPUContext const&, phi::DenseTensor const&, phi::DenseTensor const&, phi::DenseTensor const&, paddle::optional<phi::DenseTensor const&>, paddle::optional<phi::DenseTensor const&>, int, phi::DenseTensor*, phi::DenseTensor*, phi::DenseTensor*))>::Compute(phi::KernelContext*)
3   void phi::MultiplyDoubleGradKernel<float, phi::GPUContext>(phi::GPUContext const&, phi::DenseTensor const&, phi::DenseTensor const&, phi::DenseTensor const&, paddle::optional<phi::DenseTensor const&>, paddle::optional<phi::DenseTensor const&>, int, phi::DenseTensor*, phi::DenseTensor*, phi::DenseTensor*)

----------------------
Error Message Summary:
----------------------
FatalError: `Segmentation fault` is detected by the operating system.
  [TimeInfo: *** Aborted at 1648784043 (unix time) try "date -d @1648784043" if you are using GNU date ***]
  [SignalInfo: *** SIGSEGV (@0x0) received by PID 1089 (TID 0x7fa8276ee700) from PID 0 ***]

/bin/bash: line 1:  1089 Segmentation fault      (core dumped) python test2_54_Discriminator_grad_paddle.py
```
首先ddd是0，证明实现的gather代码逻辑应该没有错。请问为什么会报这个错（自定义算子源码位于~/work/custom_ops/gather）？谢谢解答！

**Comment by chenwhql** [comment]
aistudio无法打开cu文件？要不还是来个github链接，我复现一下。。。这几天赶发版，事情太多，回复不太及时，见谅

**Comment by miemie2013** [comment]
> aistudio无法打开cu文件？要不还是来个github链接，我复现一下。。。这几天赶发版，事情太多，回复不太及时，见谅

大佬，文件下载下来看，哈哈，等你好久了！

**Comment by miemie2013** [comment]
> aistudio无法打开cu文件？要不还是来个github链接，我复现一下。。。这几天赶发版，事情太多，回复不太及时，见谅

https://github.com/miemie2013/ppgan/tree/develop

develop分支

**Comment by miemie2013** [comment]
@chenwhql 大佬，有空看看嘛

**Comment by chenwhql** [comment]
抱歉哈，最晚明天看一下！我们这两周、包括清明节都在加班赶2.3发布的工作，实在是腾不出手

**Comment by chenwhql** [comment]
<img width="1367" alt="image" src="https://user-images.githubusercontent.com/22561442/162393605-6217637d-f332-4fb8-af8b-4b600826fdde.png">

您好，按照您给的操作步骤，好像缺失文件，求告知前序操作步骤

**Comment by miemie2013** [comment]
> <img alt="image" width="1367" src="https://user-images.githubusercontent.com/22561442/162393605-6217637d-f332-4fb8-af8b-4b600826fdde.png">
> 
> 您好，按照您给的操作步骤，好像缺失文件，求告知前序操作步骤
在https://aistudio.baidu.com/aistudio/projectdetail/3724521   的~/work/test_grad目录下，54.npz和54.pdparams都在

**Comment by chenwhql** [comment]
用最新的develop做了下实验，发现跟您报错的现象不太一样，比较奇怪，我还在分析
<img width="1686" alt="image" src="https://user-images.githubusercontent.com/22561442/162973240-c2c787cf-10a7-49d0-b06d-020188530da9.png">

**Comment by miemie2013** [comment]
> 用最新的develop做了下实验，发现跟您报错的现象不太一样，比较奇怪，我还在分析 <img alt="image" width="1686" src="https://user-images.githubusercontent.com/22561442/162973240-c2c787cf-10a7-49d0-b06d-020188530da9.png">

辛苦了！

**Comment by miemie2013** [comment]
> 用最新的develop做了下实验，发现跟您报错的现象不太一样，比较奇怪，我还在分析 <img alt="image" width="1686" src="https://user-images.githubusercontent.com/22561442/162973240-c2c787cf-10a7-49d0-b06d-020188530da9.png">

大佬，或者直接给原生gather算子加一个二阶导吧，实现起来对你来说应该也不难，二阶导还是gather。像什么F.grid_sample()，只要gather能支持二阶导，也能凑出它们的二阶导。

**Comment by chenwhql** [comment]
这个需求我会跟相关同学报一下的，我们还在2.3发版攻坚期，近期很难安排。。。而且这个bug看起来是框架的问题，该查还是得接着查的，因为这个报错是在transpose_grad执行的时候，直接跳到了meshgrid，这着实不应该

**Comment by miemie2013** [comment]
> 这个需求我会跟相关同学报一下的，我们还在2.3发版攻坚期，近期很难安排。。。而且这个bug看起来是框架的问题，该查还是得接着查的，因为这个报错是在transpose_grad执行的时候，直接跳到了meshgrid，这着实不应该

辛苦大佬了！

**Comment by zyfncg** [comment]
您好，使用 https://github.com/miemie2013/ppgan/tree/develop 的最新代码，运行`python test2_54_Discriminator_grad_paddle.py`出现如下报错：
<img width="1127" alt="image" src="https://user-images.githubusercontent.com/13048366/163326011-3cddd275-8ed4-4de7-a467-ad57ac8aeeb6.png">
之前自定义算子的错误复现不出来了，请问是代码的更新导致的吗？

**Comment by miemie2013** [comment]
> 您好，使用 https://github.com/miemie2013/ppgan/tree/develop 的最新代码，运行`python test2_54_Discriminator_grad_paddle.py`出现如下报错： <img alt="image" width="1127" src="https://user-images.githubusercontent.com/13048366/163326011-3cddd275-8ed4-4de7-a467-ad57ac8aeeb6.png"> 之前自定义算子的错误复现不出来了，请问是代码的更新导致的吗？

对，我一直在写。你用 https://aistudio.baidu.com/aistudio/projectdetail/3724521 的代码吧

**Comment by chenwhql** [comment]
> 这个需求我会跟相关同学报一下的，我们还在2.3发版攻坚期，近期很难安排。。。而且这个bug看起来是框架的问题，该查还是得接着查的，因为这个报错是在transpose_grad执行的时候，直接跳到了meshgrid，这着实不应该

<img width="693" alt="image" src="https://user-images.githubusercontent.com/22561442/163574635-fda4c508-60f1-4ca5-ad16-846f6781b2f9.png">
我本地复现那个问题，经过一番分析，是这里导致的，自定义算子需要在文件头部import，不能在执行过程中加，否则会导致全局算子信息的指针发生偏移，之前也没暴露过这个坑

这里改到最上面import之后，可以复现您最初那个错误了，绕了个大弯，回到原点继续分析

**Comment by miemie2013** [comment]
> > 这个需求我会跟相关同学报一下的，我们还在2.3发版攻坚期，近期很难安排。。。而且这个bug看起来是框架的问题，该查还是得接着查的，因为这个报错是在transpose_grad执行的时候，直接跳到了meshgrid，这着实不应该
> 
> <img alt="image" width="693" src="https://user-images.githubusercontent.com/22561442/163574635-fda4c508-60f1-4ca5-ad16-846f6781b2f9.png">
> 
> 我本地复现那个问题，经过一番分析，是这里导致的，自定义算子需要在文件头部import，不能在执行过程中加，否则会导致全局算子信息的指针发生偏移，之前也没暴露过这个坑
> 这里改到最上面import之后，可以复现您最初那个错误了，绕了个大弯，回到原点继续分析

大佬，按照你的改了，from custom_gather import gather_op放在了ppgan/models/generators/generator_styleganv2ada.py的首行，代码为 https://aistudio.baidu.com/aistudio/projectdetail/3724521 的0.2版本。依次点击这个项目的4条命令，还是会报错，请您再看看！另外请问一下，develop版本的飞桨是不是不支持分布式训练呀？编译时没有加相关参数？

**Comment by zyfncg** [comment]
```
--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
0   paddle::imperative::BasicEngine::Execute()
1   paddle::imperative::PreparedOp::Run(paddle::imperative::NameVariableWrapperMap const&, paddle::imperative::NameVariableWrapperMap const&, paddle::framework::AttributeMap const&, paddle::framework::AttributeMap const&)
2   phi::KernelImpl<void (*)(phi::GPUContext const&, phi::DenseTensor const&, phi::DenseTensor const&, phi::DenseTensor const&, paddle::optional<phi::DenseTensor const&>, paddle::optional<phi::DenseTensor const&>, int, phi::DenseTensor*, phi::DenseTensor*, phi::DenseTensor*), &(void phi::MultiplyDoubleGradKernel<float, phi::GPUContext>(phi::GPUContext const&, phi::DenseTensor const&, phi::DenseTensor const&, phi::DenseTensor const&, paddle::optional<phi::DenseTensor const&>, paddle::optional<phi::DenseTensor const&>, int, phi::DenseTensor*, phi::DenseTensor*, phi::DenseTensor*))>::Compute(phi::KernelContext*)
3   void phi::MultiplyDoubleGradKernel<float, phi::GPUContext>(phi::GPUContext const&, phi::DenseTensor const&, phi::DenseTensor const&, phi::DenseTensor const&, paddle::optional<phi::DenseTensor const&>, paddle::optional<phi::DenseTensor const&>, int, phi::DenseTensor*, phi::DenseTensor*, phi::DenseTensor*)

----------------------
Error Message Summary:
----------------------
FatalError: `Segmentation fault` is detected by the operating system.
  [TimeInfo: *** Aborted at 1648784043 (unix time) try "date -d @1648784043" if you are using GNU date ***]
  [SignalInfo: *** SIGSEGV (@0x0) received by PID 1089 (TID 0x7fa8276ee700) from PID 0 ***]

/bin/bash: line 1:  1089 Segmentation fault      (core dumped) python test2_54_Discriminator_grad_paddle.py
```

上面错误的原因是这里`w1`,`w2`,`w3`,`w4`的`stop_gradient`属性为True，结果在计算二阶导时需要的输入在一阶反向中没有进行计算，导致了以上错误。把这几个变量的`stop_gradient`属性设置为False就可以通过了。

<img width="948" alt="image" src="https://user-images.githubusercontent.com/13048366/163775893-e72e0cef-9d45-4fc8-af12-fb32941f3456.png">

**Comment by zyfncg** [comment]
> > > 这个需求我会跟相关同学报一下的，我们还在2.3发版攻坚期，近期很难安排。。。而且这个bug看起来是框架的问题，该查还是得接着查的，因为这个报错是在transpose_grad执行的时候，直接跳到了meshgrid，这着实不应该
> > 
> > 
> > <img alt="image" width="693" src="https://user-images.githubusercontent.com/22561442/163574635-fda4c508-60f1-4ca5-ad16-846f6781b2f9.png">
> > 我本地复现那个问题，经过一番分析，是这里导致的，自定义算子需要在文件头部import，不能在执行过程中加，否则会导致全局算子信息的指针发生偏移，之前也没暴露过这个坑
> > 这里改到最上面import之后，可以复现您最初那个错误了，绕了个大弯，回到原点继续分析
> 
> 大佬，按照你的改了，from custom_gather import gather_op放在了ppgan/models/generators/generator_styleganv2ada.py的首行，代码为 https://aistudio.baidu.com/aistudio/projectdetail/3724521 的0.2版本。依次点击这个项目的4条命令，还是会报错，请您再看看！另外请问一下，develop版本的飞桨是不是不支持分布式训练呀？编译时没有加相关参数？

开启分布式的功能需要在cmake配置中加上`-DWITH_DISTRIBUTE=ON`，然后再重新编译

**Comment by miemie2013** [comment]
> ```
> --------------------------------------
> C++ Traceback (most recent call last):
> --------------------------------------
> 0   paddle::imperative::BasicEngine::Execute()
> 1   paddle::imperative::PreparedOp::Run(paddle::imperative::NameVariableWrapperMap const&, paddle::imperative::NameVariableWrapperMap const&, paddle::framework::AttributeMap const&, paddle::framework::AttributeMap const&)
> 2   phi::KernelImpl<void (*)(phi::GPUContext const&, phi::DenseTensor const&, phi::DenseTensor const&, phi::DenseTensor const&, paddle::optional<phi::DenseTensor const&>, paddle::optional<phi::DenseTensor const&>, int, phi::DenseTensor*, phi::DenseTensor*, phi::DenseTensor*), &(void phi::MultiplyDoubleGradKernel<float, phi::GPUContext>(phi::GPUContext const&, phi::DenseTensor const&, phi::DenseTensor const&, phi::DenseTensor const&, paddle::optional<phi::DenseTensor const&>, paddle::optional<phi::DenseTensor const&>, int, phi::DenseTensor*, phi::DenseTensor*, phi::DenseTensor*))>::Compute(phi::KernelContext*)
> 3   void phi::MultiplyDoubleGradKernel<float, phi::GPUContext>(phi::GPUContext const&, phi::DenseTensor const&, phi::DenseTensor const&, phi::DenseTensor const&, paddle::optional<phi::DenseTensor const&>, paddle::optional<phi::DenseTensor const&>, int, phi::DenseTensor*, phi::DenseTensor*, phi::DenseTensor*)
> 
> ----------------------
> Error Message Summary:
> ----------------------
> FatalError: `Segmentation fault` is detected by the operating system.
>   [TimeInfo: *** Aborted at 1648784043 (unix time) try "date -d @1648784043" if you are using GNU date ***]
>   [SignalInfo: *** SIGSEGV (@0x0) received by PID 1089 (TID 0x7fa8276ee700) from PID 0 ***]
> 
> /bin/bash: line 1:  1089 Segmentation fault      (core dumped) python test2_54_Discriminator_grad_paddle.py
> ```
> 
> 上面错误的原因是这里`w1`,`w2`,`w3`,`w4`的`stop_gradient`属性为True，结果在计算二阶导时需要的输入在一阶反向中没有进行计算，导致了以上错误。把这几个变量的`stop_gradient`属性设置为False就可以通过了。
> 
> <img alt="image" width="948" src="https://user-images.githubusercontent.com/13048366/163775893-e72e0cef-9d45-4fc8-af12-fb32941f3456.png">

成功了，感谢大佬！

**Comment by miemie2013** [comment]
> > > > 这个需求我会跟相关同学报一下的，我们还在2.3发版攻坚期，近期很难安排。。。而且这个bug看起来是框架的问题，该查还是得接着查的，因为这个报错是在transpose_grad执行的时候，直接跳到了meshgrid，这着实不应该
> > > 
> > > 
> > > <img alt="image" width="693" src="https://user-images.githubusercontent.com/22561442/163574635-fda4c508-60f1-4ca5-ad16-846f6781b2f9.png">
> > > 我本地复现那个问题，经过一番分析，是这里导致的，自定义算子需要在文件头部import，不能在执行过程中加，否则会导致全局算子信息的指针发生偏移，之前也没暴露过这个坑
> > > 这里改到最上面import之后，可以复现您最初那个错误了，绕了个大弯，回到原点继续分析
> > 
> > 
> > 大佬，按照你的改了，from custom_gather import gather_op放在了ppgan/models/generators/generator_styleganv2ada.py的首行，代码为 https://aistudio.baidu.com/aistudio/projectdetail/3724521 的0.2版本。依次点击这个项目的4条命令，还是会报错，请您再看看！另外请问一下，develop版本的飞桨是不是不支持分布式训练呀？编译时没有加相关参数？
> 
> 开启分布式的功能需要在cmake配置中加上`-DWITH_DISTRIBUTE=ON`，然后再重新编译



> > > > 这个需求我会跟相关同学报一下的，我们还在2.3发版攻坚期，近期很难安排。。。而且这个bug看起来是框架的问题，该查还是得接着查的，因为这个报错是在transpose_grad执行的时候，直接跳到了meshgrid，这着实不应该
> > > 
> > > 
> > > <img alt="image" width="693" src="https://user-images.githubusercontent.com/22561442/163574635-fda4c508-60f1-4ca5-ad16-846f6781b2f9.png">
> > > 我本地复现那个问题，经过一番分析，是这里导致的，自定义算子需要在文件头部import，不能在执行过程中加，否则会导致全局算子信息的指针发生偏移，之前也没暴露过这个坑
> > > 这里改到最上面import之后，可以复现您最初那个错误了，绕了个大弯，回到原点继续分析
> > 
> > 
> > 大佬，按照你的改了，from custom_gather import gather_op放在了ppgan/models/generators/generator_styleganv2ada.py的首行，代码为 https://aistudio.baidu.com/aistudio/projectdetail/3724521 的0.2版本。依次点击这个项目的4条命令，还是会报错，请您再看看！另外请问一下，develop版本的飞桨是不是不支持分布式训练呀？编译时没有加相关参数？
> 
> 开启分布式的功能需要在cmake配置中加上`-DWITH_DISTRIBUTE=ON`，然后再重新编译

2.3啥时候发布呀？自己编译的话一大推第三方依赖下载失败

**Comment by miemie2013** [comment]
> > > > 这个需求我会跟相关同学报一下的，我们还在2.3发版攻坚期，近期很难安排。。。而且这个bug看起来是框架的问题，该查还是得接着查的，因为这个报错是在transpose_grad执行的时候，直接跳到了meshgrid，这着实不应该
> > > 
> > > 
> > > <img alt="image" width="693" src="https://user-images.githubusercontent.com/22561442/163574635-fda4c508-60f1-4ca5-ad16-846f6781b2f9.png">
> > > 我本地复现那个问题，经过一番分析，是这里导致的，自定义算子需要在文件头部import，不能在执行过程中加，否则会导致全局算子信息的指针发生偏移，之前也没暴露过这个坑
> > > 这里改到最上面import之后，可以复现您最初那个错误了，绕了个大弯，回到原点继续分析
> > 
> > 
> > 大佬，按照你的改了，from custom_gather import gather_op放在了ppgan/models/generators/generator_styleganv2ada.py的首行，代码为 https://aistudio.baidu.com/aistudio/projectdetail/3724521 的0.2版本。依次点击这个项目的4条命令，还是会报错，请您再看看！另外请问一下，develop版本的飞桨是不是不支持分布式训练呀？编译时没有加相关参数？
> 
> 开启分布式的功能需要在cmake配置中加上`-DWITH_DISTRIBUTE=ON`，然后再重新编译

2.3啥时候发布呀？自己编译的话一大推第三方依赖下载失败

**Comment by zyfncg** [comment]
2.3RC版在最近这几天会发布。或者也可以直接用Paddle官网提供的用develop分支编译的安装包
<img width="858" alt="image" src="https://user-images.githubusercontent.com/13048366/164145095-c39a1933-c97c-4de3-a70b-a1d4702290cd.png">
