### ISSUE TITLE
分布式训练下fleet和非fleet两种初始化的区别是啥？

### ISSUE THREAD

**Issue by ghostxsl** [PaddlePaddle/Paddle#41279]
请教一下，paddle里分布式训练的paddle.distributed.init_parallel_env()和paddle.distributed.fleet.init()这两种初始化有啥区别？
fleet和非fleet对于训练模型是否有所不同？

**Comment by liuTINA0907** [comment]
您好，paddle.distributed.init_parallel_env()是支持动态图训练，详情见文档：https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/distributed/init_parallel_env_cn.html#cn-api-distributed-init-parallel-env
paddle.distributed.fleet.init() 这个动、静都支持。

**Comment by ghostxsl** [comment]
意思是说在动态图下，这两个没有任何区别？

**Comment by liuTINA0907** [comment]
是的，建议用fleet.init，适用 collective 和 PS 多种模式。
