### ISSUE TITLE
用转好的二进制pre-train embedding初始化embedding_layer出错

### ISSUE THREAD

**Issue by tonyhu20116543** [PaddlePaddle/Paddle#4127]
词典的 vocab_size = 180258, emb_size = 256，并且按照https://github.com/WoNiuHu/Paddle/blob/develop/v1_api_demo/model_zoo/embedding/paraconvert.py 转成了二进制embedding

读取二进制embedding的脚本如下：
![image](https://user-images.githubusercontent.com/6749361/30474719-2b31b600-9a37-11e7-9723-a0a1e03b0aac.png)

然后运行的时候就报了 cannot reshape 的错误
![image](https://user-images.githubusercontent.com/6749361/30474997-f39c20c6-9a37-11e7-8f4b-de6e1b250406.png)

**Comment by guoshengCS** [comment]
请参照这里 https://github.com/PaddlePaddle/Paddle/issues/2927 的方法进行初始化，https://github.com/WoNiuHu/Paddle/blob/develop/v1_api_demo/model_zoo/embedding/paraconvert.py 这个脚本是配合 https://github.com/PaddlePaddle/Paddle/issues/2927 使用的，代码里的`load_parameter`需要的数据处理方式不一样。
