### ISSUE TITLE
Ubuntu 14 编译安装错误

### ISSUE THREAD

**Issue by supermanhuyu** [PaddlePaddle/Paddle#4132]
Ubuntu 14 编译安装的时候 报如下错误，release 分支
`[100%] Linking CXX executable paddle_merge_model
Done processing MergeModel.cpp
Total errors found: 0
../../../../paddle/gserver/libpaddle_gserver.a(ProtoDataProvider.cpp.o): In function `paddle::ProtoReader::ProtoReader(std::istream*, bool)':
/root/paddle/paddle/gserver/dataproviders/ProtoReader.h:37: undefined reference to `google::protobuf::io::GzipInputStream::GzipInputStream(google::protobuf::io::ZeroCopyInputStream*, google::protobuf::io::GzipInputStream::Format, int)'
../../../../../third_party/install/openblas/lib/libopenblas.a(lapacke_dgetri_work.o): In function `LAPACKE_dgetri_work':
lapacke_dgetri_work.c:(.text+0xe5): undefined reference to `dgetri_'
lapacke_dgetri_work.c:(.text+0x15a): undefined reference to `dgetri_'
../../../../../third_party/install/openblas/lib/libopenblas.a(lapacke_sgetri_work.o): In function `LAPACKE_sgetri_work':
lapacke_sgetri_work.c:(.text+0xe5): undefined reference to `sgetri_'
lapacke_sgetri_work.c:(.text+0x15a): undefined reference to `sgetri_'
collect2: error: ld returned 1 exit status
make[2]: *** [python/paddle/trainer_config_helpers/tests/protobuf_equal] Error 1
make[1]: *** [python/paddle/trainer_config_helpers/tests/CMakeFiles/protobuf_equal.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
...
collect2: error: ld returned 1 exit status
make[2]: *** [paddle/trainer/paddle_merge_model] Error 1
make[1]: *** [paddle/trainer/CMakeFiles/paddle_merge_model.dir/all] Error 2
make: *** [all] Error 2
`

**Comment by typhoonzero** [comment]
请参考文档：http://doc.paddlepaddle.org/develop/doc/howto/dev/build_en.html 推荐使用docker环境编译，避免依赖环境带来的各种问题。

**Comment by supermanhuyu** [comment]
@typhoonzero 能用docker当然是可以，但我不是简单的在Ubuntu 14 系统里面运行，我要把paddle做到 一个Ubuntu系统的容器里面，所以才会走到编译运行的这个环节。我不是简单的用在一个单机上，是要用在集群上。还望你能帮忙看看这个问题是否可以解决，谢谢。

**Comment by typhoonzero** [comment]
@supermanhuyu 不知道你具体要做什么事情，但：

> 我要把paddle做到 一个Ubuntu系统的容器里面

paddle本身已经提供开发环境docker镜像和运行环境docker镜像，而且运行环境已经是基于ubuntu 16.04build的

> 我不是简单的用在一个单机上，是要用在集群上

如果是集群训练，可以参考：http://doc.paddlepaddle.org/doc_cn/howto/usage/k8s/k8s_distributed_cn.html， 这个是paddle官方提供的集群方案。
