### ISSUE TITLE
官网导航显示错误，浏览器兼容问题？

### ISSUE THREAD

**Issue by 4luojing** [PaddlePaddle/Paddle#4133]
![2017-09-15 21-45-57](https://user-images.githubusercontent.com/31199131/30485241-5fab8096-9a5f-11e7-8972-8ecc520c0c93.png)
浏览器：Mozilla Firefox for Ubuntu
版本：55.0.2 (64 位)

**Comment by llxxxll** [comment]
https://github.com/PaddlePaddle/portal/pull/4
