### ISSUE TITLE
能否支持推理时每一层layer/模块module/(backbone\head\neck)的时间延迟计算

### ISSUE THREAD

**Issue by sdreamforchen** [PaddlePaddle/Paddle#41336]
### 需求描述 Feature Description

任务目标（请描述你正在做的项目是什么，如模型、论文、项目是什么？）; <br /> 需求场景（请描述你的项目中为什么需要用此功能）;  <br /> 功能描述（请简单描述或设计这个功能）
您好，我们目前基于百度的paddle框架以及ppyolo/picodet等模型做很多尝试和工程化。
目前遇到的问题是，这几年的关于head的优秀的论文极多，backbone优秀的论文也较多，在评估或自行优化过程中，精度和延迟是重要评估因素。
如此多的论文和有限的资源，我们可能同时对backbone和neck进行修改。
我们希望paddle能提供通用的api进行backbone/neck/head/layer的推理延迟计算savefile。方便我们在优化过程中的获得更加准确的延迟数据。特别是使用eval或者部署推理的时候。
PS：我们发现最新的PPYOLOE的without trt和with trt的推理时间，在s,m,l,x下的两者比值范围较大（1.6~2.02），而PPYOLO的情况，变化要小一些。我们希望能准确定位是哪里引起了这个差别（初步判断应该就是neck部分，因为l和x比值就很接近了，且和PPYOLO情况相近）

**Comment by zhangbo9674** [comment]
您好，我们已经收到您对与api的需求及ppyolo在推理时间上差异的疑问，会尽快给您答复。

**Comment by wangxinxin08** [comment]
PP-YOLO只有一个模型，测速度是不同输入分辨率(320~608)的模型速度，PP-YOLOE是4个模型，测的是s/m/l/x四个模型的速度，不知道这个是否解答了你的疑惑。关于分开测速的问题，这个我们评估下
