### ISSUE TITLE
关于avg-pooling 是exclusive还是inclusive

### ISSUE THREAD

**Issue by tensor-tang** [PaddlePaddle/Paddle#4136]
这里只考虑avg-pooling。
1. 根据Paddle最新code，对于如下pooling设置：
batchsize: 1
channel: 1
input image size: 3
output image size: 2
kernel size: 3
padding size: 1
stride size: 2
加上Padding后**输入**图片的数据为：

0 | 0 | 0 | 0 | 0
-- | -- | -- | -- | --
0 | 0.33958 | 0.320544 | 0.173373 | 0
0 | 0.050157 | 0.025043 | 0.671224 | 0
0 | 0.556442 | 0.787041 | 0.218098 | 0
0 | 0 | 0 | 0 | 0

forward的**输出**结果为：

0.081703 | 0.132243
-- | --
0.157632 | 0.189045

可以看出来每个数都是除以的9，所以这个结果是属于**inclusive**的，也就是平均的时候包含了padding的0.

2. 另外一个case，相比之前的例子把input image size改为4，padding size为0，其他不变
得到一个**输入**：

0.458402 | 0.949747 | 0.165358 | 0.327871
-- | -- | -- | --
0.844729 | 0.449376 | 0.000869 | 0.774723
0.326577 | 0.323052 | 0.444988 | 0.277968
0.622502 | 0.119946 | 0.636519 | 0.091483

此时Forward的**输出**为：

0.440344 | 0.331963
-- | --
0.412264 | 0.36274

显然这个最右下角的结果0.36274，是需要在输入数据的右面和下面加padding才能凑满size 为3的kernel ，也就是说逻辑上的输入是这样的：（假设自动padding 0）

0.458402 | 0.949747 | 0.165358 | 0.327871 | 0
-- | -- | -- | -- | --
0.844729 | 0.449376 | 0.000869 | 0.774723 | 0
0.326577 | 0.323052 | 0.444988 | 0.277968 | 0
0.622502 | 0.119946 | 0.636519 | 0.091483 | 0
0 | 0 | 0 | 0 | 0

如果按照inclusive的逻辑，那个值是这个矩阵的avg：

0.444988 | 0.277968 | 0
-- | -- | --
0.636519 | 0.091483 | 0
0 | 0 | 0

那么结果应该是`1.450958 / 9 = 0.161218`, 而显然，paddle的结果并不是这个，而是`1.450958 / 4 = 0.36274`，这是属于exclusive的pooling。

所以我就有点疑惑了，或者说对于设计者来说，他可能并不能知道这件事情，但是这个对于model的设计应该是重要的。

或者说，我的问题是这里avg pooling的设计是遵从的什么准则，个人觉得不应该是两者的混合。

PS：这些值都是在现在paddle中加log打印出来的。

**Comment by luotao1** [comment]
可能与[CpuMatrix::avgPoolForward](https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/math/Matrix.cpp#L2137)这段代码有关:
```
int hstart = ph * strideH - paddingH;
int wstart = pw * strideW - paddingW;
int hend = std::min(hstart + sizeY, inHeight + paddingH);
int wend = std::min(wstart + sizeX, inWidth + paddingW);
int poolSize = (hend - hstart) * (wend - wstart);
```

**Comment by tensor-tang** [comment]
是与这段代码有关，但是，我觉得这里算出来的poolSize不能准确区分inclusive或者exclusive。或者说有的时候算出来的值是混合这两者的，个人觉得这样设计是不是不太好

**Comment by luotao1** [comment]
对于case 1: 0.081703=(0+0+0+0+0.33958+0.320544+0+0.05015+0.025043)/9
对于case 2: 0.36274是怎么算的呢？

**Comment by tensor-tang** [comment]
case 2: 0.36274 = (0.444988 + 0.277968  +0.636519 +0.091483 ) / 4 = 1.450958 / 4
如果按照inclusive，应该是除以9

> 那么结果应该是1.450958 / 9 = 0.161218, 而显然，paddle的结果并不是这个，而是1.450958 / 4 = 0.36274，这是属于exclusive的pooling。

**Comment by luotao1** [comment]
case 2: 左上角的第一个值0.444988=(0.458402+0.949747+0.165358+0.844729+0.449376+0.000869+0.326577+0.323052+0.444988)/9。同一个case中，有的按照poolSize=9来算，有的按照poolSize=4来算。

**Comment by tensor-tang** [comment]
是的，所以我觉得这样不太合理。
要么，就都按照VALID的方式，只除以有效值的size；要么，就都除以包含padding的size。

**Comment by luotao1** [comment]
```
int hend = std::min(hstart + sizeY, inHeight + paddingH);
```
应该改成：
```
int hend = std::min(hstart + sizeY, inHeight);
```
同时，对应修改wend即可。我来fix一下。

https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/math/Matrix.cpp#L2086

maxPool的代码是完全正确的。
