### ISSUE TITLE
飞浆现在是否支持cudnn_8呢，本地使用gpu，找不到cudnn_7动态库的问题

### ISSUE THREAD

**Issue by wzy123456wzy** [PaddlePaddle/Paddle#41384]
### 请提出你的问题 Please ask your question

![image](https://user-images.githubusercontent.com/44393339/161440129-13abb245-446d-47b3-b6a4-db168d5c9fbf.png)
飞浆现在是否支持cudnn_8呢，本地使用gpu，找不到cudnn_7动态库，我可以肯定gpu环境是可用的，对于动态库的寻址路径没有问题，我同时也在用paddlex和PaddleDetection

**Comment by AnnaTrainingG** [comment]
你好，Paddle支持8.0。需要安装CUDA11的whl包。官网中选择选CUDA11的安装包，执行安装命令。参考文档https://www.paddlepaddle.org.cn/install/quick?docurl=/documentation/docs/zh/install/pip/linux-pip.html

**Comment by ronny1996** [comment]
飞桨支持cudnn8，请参考 https://www.paddlepaddle.org.cn/install/quick?docurl=/documentation/docs/zh/develop/install/pip/windows-pip.html

![image](https://user-images.githubusercontent.com/25691046/161476858-50d2c721-d392-40bd-90f0-2ed350936b42.png)
