### ISSUE TITLE
曙光本地编译Paddle环境要求有哪些？

### ISSUE THREAD

**Issue by yoreG123** [PaddlePaddle/Paddle#41399]
使用paddlepaddle/paddle:latest-dev-rocm4.0-miopen2.11镜像，本地编译Paddle一直通不过，想问以下本地编译的要求有哪些，必须要有gpu吗，对cpu有没有要求？
本地环境为云服务器（网络环境便于使用github），1核cpu，2g内存，无gpu

**Comment by ronny1996** [comment]
你好，当前 Paddle 只支持 CentOS 7.8 & ROCm 4.0.1 编译环境，且根据 ROCm 4.0.1 的需求，支持的编译器为 devtoolset-7。可以参考https://www.paddlepaddle.org.cn/documentation/docs/zh/guides/09_hardware_support/rocm_docs/paddle_install_cn.html#anzhuangfangshier-tongguoyuanmabianyianzhuang

**Comment by yoreG123** [comment]
你好，由于曙光智算环境下网路受限，直接编译飞桨源码会遇到第三方依赖库下载失败从而导致编译失败的问题。因此在曙光智算环境下进行飞桨源码编译与单测需要首先在本地编译，但是本地不存在CentOS 7.8 & ROCm 4.0.1 编译环境的（不存在相关硬件）。

**Comment by ronny1996** [comment]
你好，编译只需要cpu使用docker镜像即可，请问具体是什么错误

**Comment by yoreG123** [comment]
![图片](https://user-images.githubusercontent.com/50627048/161694641-7b0becc6-cba5-4105-82b0-e80e4cd436f5.png)
您好，具体错误是这样的。

**Comment by ronny1996** [comment]
是在paddlepaddle/paddle:latest-dev-rocm4.0-miopen2.11镜像下编译报这个错误吗？能说明一下使用的机器cpu型号，os，paddle版本（或commit号）

**Comment by yoreG123** [comment]
就是这一个镜像，cpu：Intel(R) Xeon(R) CPU E5-2680 v2 @ 2.80GHz，os：Ubuntu 20.04，paddle拉取的是最新的develop分支，commit号显示为630f5b8917，cmake的命令是：cmake .. -DPY_VERSION=3.7 -DWITH_GPU=OFF -DWITH_TESTING=ON -DWITH_DISTRIBUTE=ON -DWITH_MKL=ON，cmake出现了提示：
![图片](https://user-images.githubusercontent.com/50627048/161698237-dda31952-6477-42d5-b9f5-f3e19dfd115e.png)
，cmake过程显示如下：
![图片](https://user-images.githubusercontent.com/50627048/161698518-fcc7d6d0-1055-4dc9-abe2-56b4227ed7fe.png)

**Comment by ronny1996** [comment]
cmake命令可以使用官方文档中的尝试一下
```
cmake .. -DPY_VERSION=3.7 -DWITH_ROCM=ON -DWITH_TESTING=ON -DWITH_DISTRIBUTE=ON \
         -DWITH_MKL=ON -DCMAKE_BUILD_TYPE=Release -DCMAKE_EXPORT_COMPILE_COMMANDS=ON
```

**Comment by yoreG123** [comment]
你好，还是mathfunction的编译有问题，我先不用这个环境了。

**Comment by ronny1996** [comment]
好的，这个issue我先关了，有问题可以重新打开
