### ISSUE TITLE
paddle在预测时，如果返回值是LoDTensorArray类型该如何获取？官方提供的copy_to_cpu()似乎只支持将LoDTensor拷贝到cpu上

### ISSUE THREAD

**Issue by Macus1995** [PaddlePaddle/Paddle#41395]
在导出预测模型时，有一个返回值是list(Tensor)类型，因为是在依赖Tensor的控制流中生成所以被转换成了LoDTensorArray类型返回，这种情况下如何在外部获取这个返回值？提供的接口copy_to_cpu似乎只支持将LoDTensor拷贝到cpu上。
<img width="1310" alt="图片" src="https://user-images.githubusercontent.com/41893133/161489098-5fe4d22e-8b9f-4388-88ba-39d8e5f32909.png">

**Comment by ronny1996** [comment]
你好，请问是paddleinference吗？

**Comment by Macus1995** [comment]
> 你好，请问是paddleinference吗？

你好，这个问题已经解决，目前改成将TensorArray中的Tensor全部concat成一个Tensor返回就没有问题了。不过不清楚如果直接返回TensorArray类型该如何在外部接收？

**Comment by ronny1996** [comment]
需要先转成Tensor，使用paddle.concat, paddle.stack, paddle.fluid.layers.tensor_array_to_tensor之类的api都可以完成

**Comment by Macus1995** [comment]
> 需要先转成Tensor，使用paddle.concat, paddle.stack, paddle.fluid.layers.tensor_array_to_tensor之类的api都可以完成

好的  谢谢~
