### ISSUE TITLE
core_noavx.so: ELF load command alignment not page-aligned

### ISSUE THREAD

**Issue by Lionelpang** [PaddlePaddle/Paddle#41392]
今日准备在使用该框架在华为鲲鹏主机上运行。由于内网与外网不同，因此特意在华为云上购买鲲鹏云主机进行编译whl文件，并制作成为镜像编译。但是镜像在内网主机上启动时报出：core_noavx.so: ELF load command alignment not page-aligned错误。也采用关闭avx的方式构建，依然还是错误。事情着急，肯定各位大神给予指点。难道必须在内网的鲲鹏主机上进行编译么？两者的差距在哪里呢？

两者CPU信息如下：
![image](https://user-images.githubusercontent.com/1059281/161472575-9cfd8309-c62b-483d-a313-ffb444c97c38.png)

尝试两种编译命令进行编译，分别如下所示：
GPU编译：
cmake .. -DPY_VERSION=3 -DPYTHON_EXECUTABLE=`which python3` -DWITH_ARM=ON -DWITH_TESTING=OFF -DCMAKE_BUILD_TYPE=Release -DON_INFER=ON -DWITH_XBYAK=OFF
make TARGET=ARMV8 -j$(nproc)

NoGPU编译：
cmake .. -DPY_VERSION=3 -DPYTHON_EXECUTABLE=`which python3` -DWITH_ARM=ON -DWITH_TESTING=OFF -DCMAKE_BUILD_TYPE=Release -DON_INFER=ON -DWITH_XBYAK=OFF -DWITH_GPU=OFF -DWITH_AVX=OFF
make TARGET=ARMV8 -j$(nproc)

报错错误：
Error: Can not import noavx core while this file exists: /usr/local/lib/python3.7/site-packages/paddle/fluid/core_noavx.so
Traceback (most recent call last):
  File "text_correction.py", line 4, in <module>
    import paddle
  File "/usr/local/lib/python3.7/site-packages/paddle/__init__.py", line 25, in <module>
    from .framework import monkey_patch_variable
  File "/usr/local/lib/python3.7/site-packages/paddle/framework/__init__.py", line 17, in <module>
    from . import random  # noqa: F401
  File "/usr/local/lib/python3.7/site-packages/paddle/framework/random.py", line 16, in <module>
    import paddle.fluid as fluid
  File "/usr/local/lib/python3.7/site-packages/paddle/fluid/__init__.py", line 36, in <module>
    from . import framework
  File "/usr/local/lib/python3.7/site-packages/paddle/fluid/framework.py", line 37, in <module>
    from . import core
  File "/usr/local/lib/python3.7/site-packages/paddle/fluid/core.py", line 365, in <module>
    raise e
  File "/usr/local/lib/python3.7/site-packages/paddle/fluid/core.py", line 313, in <module>
    from . import core_noavx
ImportError: /usr/local/lib/python3.7/site-packages/paddle/fluid/core_noavx.so: ELF load command alignment not page-aligned

**Comment by ronny1996** [comment]
你好，请问是在内网编译有什么困难吗？
可以看下pagesize的大小吗？

**Comment by Lionelpang** [comment]
> 你好，请问是在内网编译有什么困难吗？ 可以看下pagesize的大小吗？
内网不通外网，导致无法下载到依赖包。两个pagesize确实不一样，这个需要指定一致么？
内网
<img width="283" alt="image" src="https://user-images.githubusercontent.com/1059281/161650299-614c1e03-f8c1-4844-9d72-b1562e6374ff.png">

华为云：
<img width="413" alt="image" src="https://user-images.githubusercontent.com/1059281/161650412-9cfb0587-5e0d-4785-b494-70af7720419d.png">

**Comment by ronny1996** [comment]
请问是在官方的镜像下编译的吗？

**Comment by Lionelpang** [comment]
> 请问是在官方的镜像下编译的吗？

用的是官方提供的镜像进行构建的。构建采用的[飞桨框架昇腾NPU版安装说明](https://www.paddlepaddle.org.cn/documentation/docs/zh/install/compile/arm-compile.html)中的镜像，再采用官方提供的[飞腾/鲲鹏下从源码编译](https://www.paddlepaddle.org.cn/documentation/docs/zh/install/compile/arm-compile.html)进行编译。
构建镜像启动命令：
`docker run -it --name paddle-npu-dev -v /root:/workspace  \
            --pids-limit 409600 --network=host --shm-size=128G \
            -v /usr/local/Ascend/driver:/usr/local/Ascend/driver \
            -v /usr/local/bin/npu-smi:/usr/local/bin/npu-smi \
            -v /usr/local/dcmi:/usr/local/dcmi \
            paddlepaddle/paddle:latest-dev-cann5.0.2.alpha005-gcc82-aarch64 /bin/bash`

**Comment by ronny1996** [comment]
你好，能在CMakeLists中加上
```
add_definitions(-Wl,-z,max-page-size=65536)
add_definitions(-Wl,-z,common-page-size=65536)
```
再尝试下吗？

或者使用 patchelf --pagesize=65536 修改下core_noavx.so

**Comment by Lionelpang** [comment]
还是不行，纠结了。

**Comment by ronny1996** [comment]
使用 patchelf --pagesize=65536 修改下core_noavx.so也是不行吗？

**Comment by ronny1996** [comment]
你好，这个issue我先关了，有问题可以重新打开

**Comment by sgfCrazy** [comment]
这个问题有解决么？我遇到和他一样的问题。

**Comment by sgfCrazy** [comment]
能否说一下 在CMakeList的什么位置加
add_definitions(-Wl,-z,max-page-size=65536)
add_definitions(-Wl,-z,common-page-size=65536)
感谢。

**Comment by hbo-lambda** [comment]
最后怎么解决的，我也遇到了，折腾了一下午

**Comment by yangy996** [comment]
怎么解决的？我也遇到了

**Comment by imwang77** [comment]
1. 在国产系统麒麟V10 鲲鹏920系统，在官方构建镜像中：paddlepaddle/paddle:latest-dev-cann5.0.2.alpha005-gcc82-aarch64
![image](https://github.com/user-attachments/assets/3cc43707-a55b-4a02-817d-bd6f00fc300d)

将：patchelf升级到0.12版本
添加翻墙代理：
	export http_proxy=http://x.x.x.x:40150
	export https_proxy=http://x.x.x.x:40150
编译文件中添加内存页配置：（通过getconf PAGESIZE 查看系统当前内存页配置）
	CMakeLists.txt
	592行：add_definitions(-Wl,-z,max-page-size=65536)
	593行：add_definitions(-Wl,-z,common-page-size=65536)
编译命令添加内存页配置：
```
	cmake .. -DCMAKE_EXE_LINKER_FLAGS="-Wl,-z,max-page-size=65536" -DCMAKE_SHARED_LINKER_FLAGS="-Wl,-z,max-page-size=65536"  -DCMAKE_INSTALL_PREFIX=/home/Paddle-2.4.2/install_dir/  -DPY_VERSION=3  -DPYTHON_LIBRARY=/usr/local/lib/python3.9/config-3.9-aarch64-linux-gnu/libpython3.9.a -DPY_PIP=/usr/local/bin/pip3.9 -DPYTHON_EXECUTABLE=/usr/local/bin/python3.9  -DWITH_ARM=ON -DWITH_TESTING=OFF -DCMAKE_BUILD_TYPE=Release -DON_INFER=ON -DWITH_XBYAK=OFF -DWITH_AVX=OFF     -DCMAKE_BUILD_TYPE=Release     -DWITH_GPU=OFF

	make TARGET=ARMV8 -j8
```
编译完，安装后解决了此报错
