### ISSUE TITLE
If csutom op support optional attr

### ISSUE THREAD

**Issue by gglin001** [PaddlePaddle/Paddle#41436]
### 请问对于定义的 custom-op 是否支持 optional 的 属性?

例如

```
PD_BUILD_OP(custom_leaky_relu)
    .Inputs({"X"})
    .Outputs({"Out"})
    .Attrs({"alpha: float"})
    .SetKernelFn(PD_KERNEL(LeakyReluCPUForward))
    .SetInferShapeFn(PD_INFER_SHAPE(LeakyReluInferShape))
    .SetInferDtypeFn(PD_INFER_DTYPE(LeakyReluInferDtype));

```

上面的 `.Attrs({"alpha: float"})` 可以是 optional 的吗?

**Comment by chenwhql** [comment]
不支持，自定义算子所使用的Python API也是编译时生成的，生成的Python API现在不支持指定默认值，如果需要在调用时是optional的行为，需要自己实现Python API，并给对应参数设置默认值

生成的API见文档：https://www.paddlepaddle.org.cn/documentation/docs/zh/guides/07_new_op/new_custom_op_cn.html#zidingyisuanzibianyiyushiyong

<img width="873" alt="image" src="https://user-images.githubusercontent.com/22561442/161935429-ab39930e-b3f3-40c7-a35a-d0dcedf9f892.png">

**Comment by chenwhql** [comment]
现阶段，可以先按步骤实现完，然后按照文档找到生成的python API，自己拷贝出来进行增强

**Comment by gglin001** [comment]
ok, 感谢回复
