### ISSUE TITLE
CUBLAS_STATUS_NOT_INITIALIZED ！！急急急！！ need help

### ISSUE THREAD

**Issue by henuliulei** [PaddlePaddle/Paddle#41458]
### bug描述 Describe the Bug

[Hint: 'CUBLAS_STATUS_NOT_INITIALIZED'.  The cuBLAS library was not initialized. This is usually caused by the lack of a prior cublasCreate() call, an error in the CUDA Runtime API called by the cuBLAS routine, or an error in the hardware setup.  To correct: call cublasCreate() prior to the function call; and check that the hardware, an appropriate version of the driver, and the cuBLAS library are correctly installed.  ] (at /paddle/paddle/fluid/platform/cuda_helper.h:98)

**Comment by henuliulei** [comment]
W0406 17:28:01.046226 15631 device_context.cc:447] Please NOTE: device: 0, GPU Compute Capability: 7.5, Driver API Version: 10.1, Runtime API Version: 10.1
W0406 17:28:01.052846 15631 device_context.cc:465] device: 0, cuDNN Version: 7.6.

**Comment by henuliulei** [comment]
安装10.1版本的paddlepaddle_gpu验证paddle.fluid.install_check.run_check()
报了上面的错误，试了很多办法没解决。

**Comment by ZzSean** [comment]
您好，根据报错信息来看，是cuBLAS库没有安装成功，建议您：
1. 检查下cuda是否安装正确，将cuda相关动态库添加到`LD_LIBRARY_PATH`中；
2. 匹配CUDA版本与paddle的CUDA版本，使用nvcc -V查看cuda版本
3. 如果还是不行，可以尝试使用paddle的docker

**Comment by henuliulei** [comment]
最终换成cuda11.2对应的驱动,cudnn,cuda,paddlepaddle_gpu程序成功运行起来,10.1问题放弃解决。
