### ISSUE TITLE
回归类的Metric实现

### ISSUE THREAD

**Issue by fly2008begin** [PaddlePaddle/Paddle#41454]
### 需求描述 Feature Description

任务目标（请描述你正在做的项目是什么，如模型、论文、项目是什么？）; <br /> 需求场景（请描述你的项目中为什么需要用此功能）;  <br /> 功能描述（请简单描述或设计这个功能）

### 替代实现 Alternatives

为什么paddle.metric中没有最基本的关于回归问题的评估器，有可能在后期添加到官方版本里吗？

**Comment by ZzSean** [comment]
您好，针对回归问题的评估器实现，您可以查阅https://www.paddlepaddle.org.cn/documentation/docs/zh/guides/02_paddle2.0_develop/07_customize_cn.html#metric，来实现自定义的评估器。
对于是否后续会添加官方版本，需要依赖后续发版计划，目前无法给您明确的答复。后续若有相关开发计划，会及时回复您。谢谢！

**Comment by Ligoml** [comment]
你好，为了准确评估你提交的需求，请提供更详细的信息，如 你会在何种场景下用到此能力？是否有其他替代方案？你对该需求的期望是什么？是否有对标竞品实现了该能力？
