### ISSUE TITLE
可以在一个框架下同时训练两个NLP模型吗？

### ISSUE THREAD

**Issue by lblytz23** [PaddlePaddle/Paddle#41488]
### 请提出你的问题 Please ask your question

目前利用paddlepaddle搭建了一个内部训练平台。假设工程师A调用了训练接口开始训练一个NLP模型，这时工程师B在上一个模型训练任务没有完成之前也调用了同一个训练接口，结果两个训练都挂掉了。
这里想问的问题就是，这种操作是合理的吗？同时训练两个模型 (这里应该不属于分布式训练？)

**Comment by JamesLim-sy** [comment]
`同时训练`的意思在同一张Device设备(例GPU\CPU)上，利用PaddlePaddle同时训练2个NLP模型吗？

**Comment by JamesLim-sy** [comment]
> `同时训练`的意思在同一张Device设备(例GPU\CPU)上，利用PaddlePaddle同时训练2个NLP模型吗？

如果是这种情况的下暂时是不行的，因为设备资源在单个任务训练过程中被尽可能占满了.

**Comment by lblytz23** [comment]
> `同时训练`的意思在同一张Device设备(例GPU\CPU)上，利用PaddlePaddle同时训练2个NLP模型吗？

是的，同一个设备。

**Comment by lblytz23** [comment]
> 

所以paddle没有安排资源的功能，比如给任务排队来做并行训练之类的？
