### ISSUE TITLE
飞桨框架v2.3的发布计划(Paddle framework v2.3 release plan)

### ISSUE THREAD

**Issue by jzhang533** [PaddlePaddle/Paddle#41514]
我们已经于4月6日创建了[v2.3.0 release 分支](https://github.com/PaddlePaddle/Paddle/tree/release/2.3)，并基于该分支启动了集成测试、稳定性测试、性能测试。我们会逐步的从develop分支中通过cherry-pick PRs的方式让该分支稳定。该过程可能会持续1~2个月的时间，这期间我们会发布一到多个的v2.3.0 release candidate版本。待该分支稳定后，我们会发布v2.3.0正式版本。

We have created a release branch for [the v2.3.0 release](https://github.com/PaddlePaddle/Paddle/tree/release/2.3) on 4/6, and have started performing integration test, stability test and performance test based on this branch. To stabilize the release branch , we will cherry-pick PRs from develop branch progressively, this process may take 1~2 months, and we will create one or more v2.3.0 release candidates during this process. We will release v2.3.0 version after this branch is stabilized. 

update:
2.3.0-rc0 release note: https://github.com/PaddlePaddle/Paddle/releases/tag/v2.3.0-rc0

update:
2.3.0 binary package is now available at PyPi: https://pypi.org/project/paddlepaddle/2.3.0/#files and https://pypi.org/project/paddlepaddle-gpu/2.3.0/#files

update:
2.3.0 release note: https://github.com/PaddlePaddle/Paddle/releases/tag/v2.3.0

**Comment by GT-ZhangAcer** [comment]
非常期待

**Comment by renmada** [comment]
pip能安装v2.3.0 release candidate吗

**Comment by Ligoml** [comment]
现在还不行，等v2.3rc版正式发布后就可以了

**Comment by ltto** [comment]
加油加油加油加油
