### ISSUE TITLE
LoDTensor in operators.

### ISSUE THREAD

**Issue by qingqing01** [PaddlePaddle/Paddle#4151]
关于`LoDTensor`在operator里的用法，合入https://github.com/PaddlePaddle/Paddle/pull/4083 之后， 对于非sequence operators使用，需要注意：
1. 只需要在`InferShape`里对输出用: `Output<framework::LoDTensor>`
2. Input以及operator kernel里还可继续用`Tensor`。

用`SigmoidOp`举例：

```cpp
class SigmoidOp : public framework::OperatorWithKernel {
 public:
  using framework::OperatorWithKernel::OperatorWithKernel;

 protected:
  void InferShape(const framework::InferShapeContext &ctx) const override {
    PADDLE_ENFORCE_NOT_NULL(ctx.InputVar("X"),
                            "Input(X) of SigmoidOp should not be null.");
    PADDLE_ENFORCE_NOT_NULL(ctx.OutputVar("Y"),
                            "Output(Y) of SigmoidOp should not be null.");

    ctx.Output<framework::LoDTensor>("Y")->Resize(
        ctx.Input<Tensor>("X")->dims());
  }
};
```

SigmoidKernel:

```cpp
template <typename Place, typename T>
class SigmoidKernel : public framework::OpKernel {
 public:
  void Compute(const framework::ExecutionContext& context) const override {
    auto input = context.Input<Tensor>("X");
    auto output = context.Output<Tensor>("Y");
    output->mutable_data<T>(context.GetPlace());

    // The clipping is used in Paddle's raw implenmention
    auto X = EigenVector<T>::Flatten(*input);
    auto Y = EigenVector<T>::Flatten(*output);
    auto place = context.GetEigenDevice<Place>();

    Y.device(place) = 1. / (1. + (-X).exp());
  }
};
```
 
有同学觉得一些地方使用`LoDTensor`, 一些地方用`Tensor`，这样有点晕，大家怎么看？

如果要改的话，有两种方式： 
1. 所有operator的任何地方都用`LoDTenor`，（王益老师也强调，`LoDTensor`是我们的一个特点）
     - 会导致所有operators，即使非sequence operators，任何地方都感知`LoDTensor`.

2. [`InferShapeContext::Output<T>(const std::string& name)`](https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/framework/operator.h#L299)函数对Tensor特化，`GetMutable<LoDTensor>`始终使用`LoDTensor`:
     - 会导致通过`InferShapeContext::Output<Tensor>()`永远无法在scope里创造出`Tensor`.

```cpp
  template <>
  Tensor* ExecutionContext::Output<Tensor>(const std::string& name) const {
    auto* var = OutputVar(name);
    return var == nullptr ? nullptr : var->GetMutable<LoDTensor>();
  }
```

大家有什么建议吗？

**Comment by jacquesqiao** [comment]
```cpp
Output<framework::LoDTensor>
```
请教下Output为什么一定要是 `LodTensor`

**Comment by qingqing01** [comment]
@jacquesqiao  [`InferShapeContext::Output<T>(const std::string& name)`](https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/framework/operator.h#L299) 函数如下：

```cpp
  template <typename T>
  T* Output(const std::string& name) const {
    auto var = OutputVar(name);
    return var == nullptr ? nullptr : var->GetMutable<T>();
  }
```

这里调用`Variable::GetMutable<T>()`函数:

```cpp
  template <typename T>
  T* GetMutable() {
    if (!IsType<T>()) {
      holder_.reset(new PlaceholderImpl<T>(new T()));
    }
    return static_cast<T*>(holder_->Ptr());
  }
```

第一次调用`InferShape`函数时，输出var里还没有创建任何类型，var里的`holder_`为空，`GetMutable`会给`var`里创建T类型，现在约定我们operators输入输出都是`LoDTensor`，所以必需调用`Output<framework::LoDTensor>`.

**Comment by hedaoyuan** [comment]
我倾向于：
1. 对于不用感知LoDTenor类型的Op里面不需要出现LoDTenor（包括在Op，Op.InferShape，OpKernel的实现中），比如矩阵乘法Op，elementwise Op等；
将非`sequence operators`的Op输入输出构造成LoDTensor的主要目的是为了传递sequence信息，但这些Op的计算都是不需要感知LoDTensor类型的，所以，对于使用variable，可以考虑在这些Op的InferShape, Kernel中按照Tensor类型从`context`中去获取输入输出（上面SigmoidKernel例子中就是在使用variable时用Tensro类型来get的例子）。
2. 而对于variable的创建逻辑，比如上述SigmoidOp.InferShape例子中的output Y的创建。这里可以考虑在InferShapeContext中实例化`Output<framework::Tensor>`的实现，对`T=Tensor`时也是在variable中构造一个LoDTensor，这样就可以避免在非`sequence operators`中出现LoDTensor了。

**Comment by jacquesqiao** [comment]
### 现状理解：
1. 隐含约束是所有Tensor必须初始化成 LodTensor，如果已经初始化成LodTensor：
1. 后面可以用 Get<Tensor> 拿到一个Tensor类型，但实际上底层依然是LodTensor(因为是继承关系)

### 问题：
1. 我印象中LodTensor和Tensor后面会用组合的方式来实现，这个继承关系后面会不存在？
1. 我支持道远的说法，Variable在初始化的时候，如果发现还没有类型，并且要求的type是tensor，则自动创建LodTensor类型，用户无需感知。

**Comment by Superjom** [comment]
很久之前就有临时方案和中间方案：
- 临时方案： output->copy(input), 顺带连 LOD 信息也copy了 (一个月前大家一起和wangshu讨论的结果）
- 中间方案 [在variable中添加clone接口](https://github.com/Superjom/Paddle/blob/a33e4b79e944108ea3360e88a8824585dce00e1a/paddle/framework/tensor_as_interface_design.md#在variable中添加clone接口)
- [最早的变长RNN 设计](https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/operators/rnn_design.md#框架支持)
- [关于类型推导](https://github.com/PaddlePaddle/Paddle/issues/3396)

只是无法确定是否符合 first principle，如果设计是实现与现状的妥协，无法把握这个妥协的点

在我的理解，一个模块确定好了自己的接口，内部实现应该是有自己的自由度的；模块接口不变，实现可以自由优化，只要这个模块做好了自己的职责；而非强制把一个比较完善的实现硬改成很非常简陋的版本（不考虑性能和完善）。

**Comment by Superjom** [comment]
我跟王叔讨论下，尽快给出最终的实际方案吧。

**Comment by hedaoyuan** [comment]
@Superjom 我看了一下你上面comment中的三个链接，好像只有第一个链接中的`现有代码迁移`一节是跟这个issue相关的，不过没看明白你的倾向是什么？这个issue主要讨论的就是 @qingqing01 第一个comment中的1,2两点，你可以给出自己的看法，倾向于哪一种实现。

**Comment by Superjom** [comment]
不是LoD 传递相关的吗?  fc(lodtensor as tensor) -> lodtensor ? 

如果不是这个问题或者只是选择题请忽略。
@hedaoyuan
