### ISSUE TITLE
复现信息： yolox-yolo_head.py 中dynamic_k_matching()处报错 fg_mask[fg_mask.clone()] = fg_mask_inboxes  报错提示：TypeError: Only support float and double tensor for bool index, but received paddle.bool.  建议描述：添加对bool张量的索引切片、赋值等操作

### ISSUE THREAD

**Issue by Wei-JL** [PaddlePaddle/Paddle#41551]
### 请提出你的问题 Please ask your question

在复现yolox的时候dynamic_k_matching这个函数
代码: fg_mask[fg_mask.clone()] = fg_mask_inboxes报错

TypeError: Only support float and double tensor for bool index, but received paddle.bool.

之前看见这个这个issue的网址在如下:
https://github.com/PaddlePaddle/Paddle/pull/37761/commits/d20a99f4a21eedaee993c0d25143caca02191c28

注释后还是不行，报错

**Comment by thisjiang** [comment]
您好！在Paddle最新的develop版本中已添加对int类型的支持，对bool类型的支持也已经在内部排期中。短期内您可以选择安装develop版本包并在赋值前后添加`int <-> bool`转换来绕过此问题，谢谢。

**Comment by Wei-JL** [comment]
可以看一下develop 里面的代码是怎么修改的吗   我换int还是报错

**Comment by thisjiang** [comment]
非常抱歉！我询问了相关负责人，并查找了相关源码，未能确定相关代码修改点。这边仍是建议您安装最新的develop版本代码，或等待最近的[稳定版v2.3发布](https://github.com/PaddlePaddle/Paddle/issues/41514)。

**Comment by Wei-JL** [comment]
我找到了paddle的develop  这一块的代码就删除了第一块代码 ，就是判断是不是float类型

https://github.com/PaddlePaddle/Paddle/blob/eb6d7da947a9ec9151503d069d6329750e5a764c/python/paddle/fluid/variable_index.py#L709

![image](https://user-images.githubusercontent.com/71386288/162429691-2ac9befd-14cc-44d3-a043-0c516b2b1066.png)

但是我改成develop还是报错啊~~~ 可以帮忙解决一下吗

**Comment by thisjiang** [comment]
改成develop后是报什么错呢？我本地跑是支持int类型的，bool类型的确是会报错

**Comment by Wei-JL** [comment]
File "D:\Anaconda3\envs\paddle2-2-2g\lib\site-packages\paddle\fluid\variable_index.py", line 604, in _setitem_impl_
    return slice_info.set_item(var, value)
  File "D:\Anaconda3\envs\paddle2-2-2g\lib\site-packages\paddle\fluid\variable_index.py", line 169, in set_item
    value.shape, gather_tensor_shape))
ValueError: [222] can not broadcast into [8400]

fg_mask[fg_mask.clone()] 这个还是8400

**Comment by thisjiang** [comment]
对于`fg_mask[fg_mask.clone()] = fg_mask_inboxes`而言，`fg_mask_inboxes`的shape应该是`fg_mask`中的true的数目

**Comment by Wei-JL** [comment]
> File "D:\Anaconda3\envs\paddle2-2-2g\lib\site-packages\paddle\fluid\variable_index.py", line 604, in _setitem_impl_ return slice_info.set_item(var, value) File "D:\Anaconda3\envs\paddle2-2-2g\lib\site-packages\paddle\fluid\variable_index.py", line 169, in set_item value.shape, gather_tensor_shape)) ValueError: [222] can not broadcast into [8400]
> 
> fg_mask[fg_mask.clone()] 这个还是8400

对的 fg_mask_inboxes就是  [222]  按道理来说fg_mask[fg_mask.clone()]也应该是222 但是他还是原来的8400

**Comment by thisjiang** [comment]
不应该啊，试试`print(paddle.masked_select(fg_mask, fg_mask).shape)`看看是否的确是222？

**Comment by Wei-JL** [comment]
您好~  似乎报错了  我跟您一起看吧
  File "D:\PyCharm\YOLO\paddle_fuxian\yolox_paddle\nets\yolo_training.py", line 509, in dynamic_k_matching
    print(paddle.masked_select(fg_mask, fg_mask).shape)
  File "D:\Anaconda3\envs\paddle2-2-2g\lib\site-packages\paddle\tensor\search.py", line 665, in masked_select
    return _C_ops.masked_select(x, mask)
ValueError: (InvalidArgument) Tensor holds the wrong type, it holds int, but desires to be bool.
  [Hint: Expected valid == true, but received valid:0 != true:1.] (at ..\paddle/fluid/framework/tensor_impl.h:33)
  [operator < masked_select > error]

**Comment by Wei-JL** [comment]
print(paddle.masked_select(fg_mask, fg_mask).shape)
  File "D:\Anaconda3\envs\paddle2-2-2g\lib\site-packages\paddle\tensor\search.py", line 665, in masked_select
    return _C_ops.masked_select(x, mask)
RuntimeError: (NotFound) Operator masked_select does not have kernel for data_type[bool]:data_layout[ANY_LAYOUT]:place[CUDAPlace(0)]:library_type[PLAIN].
  [Hint: Expected kernel_iter != kernels.end(), but received kernel_iter == kernels.end().] (at ..\paddle\fluid\imperative\prepared_operator.cc:159)
  [operator < masked_select > error]
第一个错误需要改bool类型 这是改之后的

**Comment by thisjiang** [comment]
`mask_select`要求第一个参数是int或者float类型，第二个参数是bool类型：
https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/masked_select_cn.html#masked-select

**Comment by Wei-JL** [comment]
对的，print正常输出222，接下来呢。

**Comment by thisjiang** [comment]
那不应该啊...确定`fg_mask_inboxes`的shape大小为[222]？我在本地测试是没问题的。。。
```
import paddle

x = paddle.to_tensor([0, 1, 2, 3], dtype='int32')
index = paddle.to_tensor([0, 1, 1, 0], dtype='bool')
y = paddle.to_tensor([5, 6], dtype='int32')

print(paddle.masked_select(x, index))
print(x[index])

x[index] = y

print(x)
```
结果是：
```
Tensor(shape=[2], dtype=int32, place=Place(gpu:0), stop_gradient=True,
       [1, 2])
Tensor(shape=[2], dtype=int32, place=Place(gpu:0), stop_gradient=True,
       [1, 2])
Tensor(shape=[4], dtype=int32, place=Place(gpu:0), stop_gradient=True,
       [0, 5, 6, 3])
```

**Comment by Wei-JL** [comment]
十分感谢 ，问题已经解决，上午忙别的去了  没来得及回复消息 

```
fg_mask_tem = fg_mask.clone().astype(paddle.bool)
        fg_mask = fg_mask.astype("int")
        fg_mask[fg_mask_tem] = fg_mask_inboxes.astype("int")
```
等价于
`fg_mask[fg_mask.clone()] = fg_mask_inboxes`

**Comment by Wei-JL** [comment]
十分感谢 ，问题已经解决，上午忙别的去了 没来得及回复消息

```
fg_mask_tem = fg_mask.clone().astype(paddle.bool)
fg_mask = fg_mask.astype("int")
fg_mask[fg_mask_tem] = fg_mask_inboxes.astype("int")
```
等价于
`fg_mask[fg_mask.clone()] = fg_mask_inboxes`

**Comment by Wei-JL** [comment]
等价于2行就行
```
fg_mask = fg_mask.astype("int")
fg_mask[fg_mask.clone().astype(paddle.bool)] = fg_mask_inboxes.astype("int")
```

**Comment by thisjiang** [comment]
Hi~请问对您而言，该问题已经解决了么？可以关闭该issue么？

**Comment by Wei-JL** [comment]
可以可以了  已解决   非常感谢~  
这边的似乎一直没回复诶，可以麻烦看看吗
https://github.com/PaddlePaddle/PaddleDetection/issues/5647

**Comment by nemonameless** [comment]
PaddleDetection中已经发布[YOLOX](https://github.com/PaddlePaddle/PaddleDetection/tree/release/2.4/configs/yolox)，欢迎使用。
