### ISSUE TITLE
自定义的原生算子在调用的时候报错"incompatible function arguments. The following argument types are supported:"该如何解决？

### ISSUE THREAD

**Issue by Macus1995** [PaddlePaddle/Paddle#41558]
算子在定义的时候在OpMaker中部分输入参数希望接收多个Tensor因此在对应的AddInput后添加了AsDuplicable()，但是在python端调用这个op的时候会报以下错误
<img width="1392" alt="图片" src="https://user-images.githubusercontent.com/41893133/162405034-73e2c5b1-626a-417c-9b42-8266b6797b93.png">
不清楚其中的handle类型是指什么。。

**Comment by thisjiang** [comment]
您好，您可以尝试使用自定义外部算子（推荐）而非自定义原生算子的方式解决该问题，如未能解决还请继续反馈，谢谢！

**Comment by thisjiang** [comment]
经确认，paddle自定义原生算子的方式是支持输入参数为多个Tensor的，非bug。
