### ISSUE TITLE
paddle 训练效率问题

### ISSUE THREAD

**Issue by zhouksh** [PaddlePaddle/Paddle#4156]
背景：
单机训练ctr预估的模型，设置train_count=6，batch_size=2000， buffer_size=20000，发现cpu的占用率在600%与100%之间来回切换。

问题：
请问paddle是否是采取单进程的准备数据，然后使用该匹数据训练这样的模式？是否考虑支持准备数据，训练分开两个线程（或者子进程），又或者是根据train_count每一个训练线程有单独的数据准备的过程，来加速训练。 谢谢！

**Comment by qingqing01** [comment]
> 请问paddle是否是采取单进程的准备数据，然后使用该匹数据训练这样的模式？

@zhouksh  请问是使用的V2 API吗？ 默认数据处理和训练是串行的。 如果是V2 API，可以使用`xmap_reader`函数处理数据，这个使用多线程处理数据，用法可参考[示例](https://github.com/PaddlePaddle/models/blob/develop/image_classification/reader.py#L35)。

**Comment by zhouksh** [comment]
@qingqing01 是用的V2版本的api。我的模型里面包含了比较多的field，每个field 都是categorical 类型的，直接split 完成之后就可以输入模型，不需要太复杂的数据预处理。看了一下xmap_readers的代码，似乎比较适合image类型的任务，在ctr预估这种情况不太适合的样子。我跟@wanghaoshuang请教过，是不是可以考虑一下支持数据处理、训练并行这种方式？

**Comment by qingqing01** [comment]
@zhouksh 这个[issues#3675](https://github.com/PaddlePaddle/Paddle/issues/3675)关联，目前V2 API的reader确实效率不高，待优化~

**Comment by zhouksh** [comment]
有大概的时间表么 ？

**Comment by helinwang** [comment]
我认为目前并不能得出V2 API reader效率不高的结论（详见[这里](https://github.com/PaddlePaddle/Paddle/issues/3675#issuecomment-332996642))。可以尝试一下V2 API的prefetch data的功能，详见[这里](https://github.com/PaddlePaddle/Paddle/pull/4394/files#r141765889)的第一条。
