### ISSUE TITLE
sparse update 报warning

### ISSUE THREAD

**Issue by zhouksh** [PaddlePaddle/Paddle#4157]
数据类型使用paddle.data_type.integer_value_sequence， embedding 设置sparse_update，优化算法使用adagrad，报以下warning，请问是否正常？

``` bash
W0918 17:31:01.996536 10063 SparseRowMatrix.h:184] There are more than 0.5*height (6) rows are used for sparse update, which is not efficient. Considering not use sparse_update.
```

**Comment by qingqing01** [comment]
这个warning的意思是输入数据不足够稀疏，你的embedding词典大小，以及每个输入的稀疏情况怎么样呢？

**Comment by zhouksh** [comment]
模型中使用到了多个field，包括定长的和不定长的两种field。有些field 字典有十几万，一个example可能出现二三十个id，有些field字典小于10，一个example只有一个id。请问有办法关掉这个warning 么？

**Comment by qingqing01** [comment]
warning在这里报出：https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/math/SparseRowMatrix.h#L184

关掉warning，就得关`LOG(WARNING)`，但是关掉并没有什么意义。

>  有些field字典小于10，一个example只有一个id

这些field的embedding层，觉得可以不用`sparse_update`.

>  有些field 字典有十几万，一个example可能出现二三十个id

这些field的embedding层，可以设置`sparse_update`，对比下速度吧。

**Comment by zhouksh** [comment]
好的，谢谢
