### ISSUE TITLE
小蛇吃青蛙哇

### ISSUE THREAD

**Issue by jiangyichen19** [PaddlePaddle/Paddle#41587]
### 问题描述 Please describe your issue

【队名】：小蛇吃青蛙哇

【序号】：20

【论文】：[Anchor DETR: Query Design for Transformer-Based Object Detection](https://arxiv.org/abs/2109.07107)

【状态】：报名

【repo链接】：https://github.com/jiangyichen19/Anchor-DETR-Query-Design-for-Transformer-Based-Object-Detection

**Comment by Ligoml** [comment]
报名需要在指定issue里回复哦，不是新建issue~
