### ISSUE TITLE
自定义损失函数问题

### ISSUE THREAD

**Issue by lguowang** [PaddlePaddle/Paddle#41602]
### 请提出你的问题 Please ask your question

我参考paddled定义 L1loss 的方法，写了L1loss_f1和L1loss_f2，两者输出的结果是一致的，但用L1loss_f1 训练会收敛，用L1loss_f2 不收敛，请问应如何改L1loss_f2

说明：我用paddle训练自己的模型，需要自定义损失函数，损失函数比较复杂，paddle现有方法写起来比较麻烦，我把tensor 转换成numpy 然后再计算损失函数，发现不收敛。请问numpy 计算后的 损失函数如何才能转成可用于训练的tensor，或者说L1loss_f2如何修改？谢谢

#用以下损失函数，训练是收敛的
def L1loss_f1(y_pred,labels):
    cost = paddle.mean(paddle.abs(paddle.subtract(y_pred,labels)))
    return cost

#用以下损失函数，训练不收敛的
def L1loss_f2(y_pred,labels):
    e = y_pred.numpy() -labels.numpy()
    cost = np.abs(e).mean()
    cost = paddle.to_tensor(cost,stop_gradient=False)
    return cost

**Comment by frankwhzhang** [comment]
应该需要用paddle的算子组成Loss，numpy的结果更新没办法返回梯度
