### ISSUE TITLE
训练出core

### ISSUE THREAD

**Issue by RuijieHou** [PaddlePaddle/Paddle#4161]
```bash
I0918 19:15:18.984148  5404 Util.cpp:166] commandline:  --use_gpu=False 
I0918 19:15:18.989181  5404 GradientMachine.cpp:85] Initing parameters..
I0918 19:15:18.989519  5404 GradientMachine.cpp:92] Init parameters done.
Thread [139932974356224] Forwarding __mse_cost_0__, 
*** Aborted at 1505733318 (unix time) try "date -d @1505733318" if you are using GNU date ***
PC: @                0x0 (unknown)
*** SIGSEGV (@0x29) received by PID 5404 (TID 0x7f44af3a9700) from PID 41; stack trace: ***
    @     0x7f44aef80160 (unknown)
    @     0x7f44aa02cb12 paddle::CpuMatrix::sumOfSquares()
    @     0x7f44a9e89b65 paddle::CostLayer::forward()
    @     0x7f44a9f3e9d0 paddle::NeuralNetwork::forward()
    @     0x7f44a9f1b0f3 paddle::GradientMachine::forwardBackward()
    @     0x7f44aa0b2b7b GradientMachine::forwardBackward()
    @     0x7f44a9daf76e _wrap_GradientMachine_forwardBackward
    @           0x4a9e33 PyEval_EvalFrameEx
    @           0x4ad70d PyEval_EvalCodeEx
    @           0x4aa88c PyEval_EvalFrameEx
    @           0x4ad70d PyEval_EvalCodeEx
    @           0x4aa88c PyEval_EvalFrameEx
    @           0x4ad70d PyEval_EvalCodeEx
    @           0x4aa88c PyEval_EvalFrameEx
    @           0x4ad70d PyEval_EvalCodeEx
    @           0x4ad842 PyEval_EvalCode
    @           0x4d64c2 PyRun_FileExFlags
    @           0x4d7839 PyRun_SimpleFileExFlags
    @           0x416edd Py_Main
    @     0x7f44ae4dabd5 __libc_start_main
    @           0x415f91 (unknown)
    @                0x0 (unknown)
Segmentation fault (core dumped)
```
-------------------------------------------------------------------
input： 16796910092836471487 1 0 0:-0.0980023 1:-0.0508415 2:-0.313378 3:-0.331837...

```python
x = paddle.layer.data(name='x', type=paddle.data_type.dense_vector(3660))
y_predict = paddle.layer.fc(input=x, size=1, act=paddle.activation.Linear())
y = paddle.layer.data(name='y', type=paddle.data_type.integer_value(1))

# define training dataset reader
def train_reader(train_list):
    def reader():
        with open(train_list, 'r') as f:
            for line in f:
                items = line.strip().split('\t')[0].split(' ')
                fea = []
                for item in items[3:]:
                    fea.append(float(item.split(':')[1]))
                yield fea, int(items[1])

    return reader
```

**Comment by qingqing01** [comment]
@RuijieHou [`mse_cost`](http://doc.paddlepaddle.org/develop/doc/api/v2/config/layer.html#square-error-cost)的输入label的是`dense_vector` 或者 `sparse_vector`, `sparse_binary_vector`，请检查下mse_cost的使用方式。

**Comment by RuijieHou** [comment]
多谢，已调通，我发现这部分的文档不太完备，我在api里没有对label的格式要求，这种会core的应该要特别注意吧，如下：

square_error_cost
class paddle.v2.layer.square_error_cost
sum of square error cost:

cost=∑i=1N(ti−yi)2
cost=∑i=1N(ti−yi)2
Parameters:	
name (basestring) – layer name.
input (paddle.v2.config_base.Layer) – Network prediction.
label (paddle.v2.config_base.Layer) – Data label.
weight (paddle.v2.config_base.Layer) – The weight affects the cost, namely the scale of cost. It is an optional argument.
coeff (float) – The coefficient affects the gradient in the backward.
layer_attr (paddle.v2.attr.ExtraAttribute) – layer’s extra attribute.
Returns:	
paddle.v2.config_base.Layer object.

Return type:	
paddle.v2.config_base.Layer

**Comment by RuijieHou** [comment]
另外在自定义read的时候也没找到官方详细的api接口或者wiki说明

**Comment by qingqing01** [comment]
@RuijieHou Thanks！

- reader的设计文档： https://github.com/PaddlePaddle/Paddle/tree/develop/doc/design/reader
- 写作示例： https://github.com/PaddlePaddle/Paddle/tree/develop/doc/design/reader#how-to-create-custom-data-reader-creator
- API接口文档：http://doc.paddlepaddle.org/develop/doc/api/v2/model_configs.html

文档确实不细致，我们还在努力增加中，Thanks!
