### ISSUE TITLE
【PFCC】op开发提示没有注册kernel

### ISSUE THREAD

**Issue by thunder95** [PaddlePaddle/Paddle#41621]
### 请提出你的问题 Please ask your question

1141: RuntimeError: (NotFound) There are no kernels which are registered in the rrelu operator.
1141:   [Hint: Expected kernels_iter != all_op_kernels.end(), but received kernels_iter == all_op_kernels.end().] (at /paddle/paddle/fluid/imperative/prepared_operator.cc:237)
1141:   [operator < rrelu > error]

检查了PD_REGISTER_KERNEL， op_register这些文件, cpu和gpu注册都是有的，一般还会有什么原因造成这个错误？

**Comment by sandyhouse** [comment]
可以参考Paddle源码里面其他op写写法，确认REGISTER_OP_xxx_KERNEL,REGISTER_OPERATOR这些宏是否调用，另外可以确认下对应的OP是否编译，建议清空编译目录，从头编译。（备注：一般不需要特殊处理，有些比较特殊的情况需要修改CMakeFile才会编译）

**Comment by thunder95** [comment]
@sandyhouse 谢谢大佬解惑。REGISTER_OPERATOR确认已经调用， 已经参考其他OP写法，  PD_REGISTER_KERNEL有用， REGISTER_OP_xxx_KERNEL没有使用， 感觉PD_REGISTER_KERNEL就够了吧

**Comment by thunder95** [comment]
@sandyhouse 调用_C_ops.rrelu时出现问题，LayerHelper方式可以的

**Comment by sandyhouse** [comment]
方便提个pr看下吗？

**Comment by thunder95** [comment]
@sandyhouse Built target 里面出现了这个kernel， 我再试着解决一下吧，实在不行就只有提pr辛苦你们了。

**Comment by thunder95** [comment]
经过几天的代码研究和排查，仍旧没找到问题， 打印了一些日志，op和kernel确实是被注册的，但是最终的allopkernels确实打印出来没有我注册的op， 已经提交pr, 辛苦帮忙看一下  https://github.com/PaddlePaddle/Paddle/pull/41823

**Comment by thunder95** [comment]
已解决

**Comment by northeastsquare** [comment]
> 已解决

怎么解决的
