### ISSUE TITLE
有关新增api：MultiplicativeDecay的问题

### ISSUE THREAD

**Issue by guguguzi** [PaddlePaddle/Paddle#41637]
之前新增的api：MultiplicativeDecay在发版测试时测出来一个bug（第一步执行时计算问题，下图所示）。
<img width="392" alt="image" src="https://user-images.githubusercontent.com/48168743/162692519-d85d3f57-9bfa-4118-8f6b-60de6426a2cc.png">
Debug时发现是因为该学习率策略在get_lr时需要使用last_lr进行计算，但last_lr本身也计算了一遍，因此last_lr和get_lr的结果存在差异。同时也对torch对应的api也进行了测试，测试代码为
```
import torch
import torch.optim as opt
import torch.optim.lr_scheduler as lrs

lambda1 = lambda epoch: 0.1
linear = torch.nn.Linear(10, 10)
optimizer = opt.Adam(linear.parameters(), lr = 1)
scheduler = lrs.MultiplicativeLR(optimizer, lr_lambda=lambda1)
for epoch in range(3):
    last_lr = scheduler.get_last_lr()
    lr = scheduler.get_lr()
    print('last_lr: {}, lr: {}, epoch: {}'.format(last_lr, lr, epoch))
    scheduler.step()
```
发现torch也存在同样的问题。
<img width="567" alt="image" src="https://user-images.githubusercontent.com/48168743/162694124-362985eb-1bd7-43f4-84b0-54bc17cb1029.png">

**Comment by Ligoml** [comment]
你好，经过飞桨团队内部讨论，我们认为API的行为应当与文档描述一致，不能因为pytorch存在相同的问题而不去修复，因此我们将该问题定位为是API bug，十分欢迎你来修复这个问题~可以参考类似功能的API [paddle.optimizer.lr.ExponentialDecay](https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/optimizer/lr/ExponentialDecay_cn.html#exponentialdecay)
