### ISSUE TITLE
使用amp梯度会爆炸

### ISSUE THREAD

**Issue by jiaohuix** [PaddlePaddle/Paddle#41642]
### 请提出你的问题 Please ask your question

再使用amp时候发现训练的梯度特别大，而且一直会上涨，最后到inf基本上就发散了。而不适用amp梯度稳定在10以内，这是什么原因，影响训练嘛？
这是没使用amp的gnorm
![image](https://user-images.githubusercontent.com/68314259/162702254-ac562a66-7b2e-41b5-a977-69eb2cb6ccff.png)

这是使用amp的梯度范数gnorm
![image](https://user-images.githubusercontent.com/68314259/162702110-08a93055-5341-4e31-bc85-7d2010acded5.png)
这是使用amp训练到后期发散的结果：
![image](https://user-images.githubusercontent.com/68314259/162702390-f5ecc4c0-0183-489f-82ca-9b411a1cccb0.png)

**Comment by sandyhouse** [comment]
使用amp时，若使用了dynamic_loss_scaling，那么梯度会乘以一个loss_scaling的值。loss_scaling会一直增加，直到梯度出现nan/inf，然后降低loss_scaling。所以出现nan/inf是正常现象，需要看一下是否对模型精度之类的有影响。如果无影响，可以忽略。

**Comment by jiaohuix** [comment]
根据我的实验没有影响到精度，略微增长了点。有一点很奇怪，以前我训了convs2s用amp速度是加快的，而训练transformer速度反而慢了些，这是怎么回事呢？
这是默认乘了dynamic_loss_scaling嘛
![1649670937(1)](https://user-images.githubusercontent.com/68314259/162714449-ad11b64f-cb2f-4b7a-a0bf-b04b67ea2452.png)

**Comment by sandyhouse** [comment]
是的，默认使用了dynamic_loss_scaling。一般来讲使用amp都是加速的。当然实际情况和使用的硬件等等都有关系（比如有些硬件下不支持amp加速，如P40等等）

**Comment by jiaohuix** [comment]
好的，感谢！发自我的荣耀手机-------- 原始邮件 --------发件人： lilong12 ***@***.***>日期： 2022年4月12日周二 09:33收件人： PaddlePaddle/Paddle ***@***.***>抄送： MiuGod0126 ***@***.***>, Author ***@***.***>主    题： Re: [PaddlePaddle/Paddle] 使用amp梯度会爆炸 (Issue #41642)

是的，默认使用了dynamic_loss_scaling。一般来讲使用amp都是加速的。当然实际情况和使用的硬件等等都有关系（比如有些硬件下不支持amp加速，如P40等等）
