### ISSUE TITLE
关于多卡训练过程中，中途停止训练，显卡显存无法释放的问题

### ISSUE THREAD

**Issue by yjhtc007** [PaddlePaddle/Paddle#41667]
### bug描述 Describe the Bug

各位大佬好，我在使用PaddleDetection训练模型的时候遇到了一个bug，就是用多卡训练模型，如果中途出现错误的话，会出现训练进程无法结束的情况，人为用kill -9 命令杀死后显卡占据的显存仍不会释放。我用PaddleOCR进行多卡训练，中途报错或停止的话不会报这个错误。之前用PaddleClas进行多卡训练也出现过和PaddleDetection一样的错误，就是显存没法释放的问题，请问我该如何解决呢？
![1649727078(1)](https://user-images.githubusercontent.com/52524345/162862268-c1d93d06-3ffc-4dcc-bd23-25e68397853d.png)

**Comment by yjhtc007** [comment]
![1649729640(1)](https://user-images.githubusercontent.com/52524345/162865604-895e16da-c348-4bf1-a92d-50f88fe9562c.png)

**Comment by LDOUBLEV** [comment]
python进程经常会出现退出异常的问题；
用指令看下哪些进程没有释放：
ps -ef |grep python 
可以用如下指令kill 所有运行train.py的残留进程，实测有效
ps -axu | grep train.py | awk '{print $2}' | xargs kill -9
