### ISSUE TITLE
import paddle出现warning

### ISSUE THREAD

**Issue by paopjian** [PaddlePaddle/Paddle#41674]
### 请提出你的问题 Please ask your question

纯净venv环境,安装paddlepaddle 2.2.2,import paddle后出现大量warning
![image](https://user-images.githubusercontent.com/20377352/162872400-ca4eda37-67a7-42cc-b88e-79f55e51faca.png)

D:\conda\envs\test\lib\site-packages\paddle\vision\transforms\functional_pil.py:36: DeprecationWarning: NEAREST is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.NEAREST or Dither.NONE instead.
  'nearest': Image.NEAREST,

D:\conda\envs\test\lib\site-packages\paddle\vision\transforms\functional_pil.py:37: DeprecationWarning: BILINEAR is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.BILINEAR instead.
  'bilinear': Image.BILINEAR,

D:\conda\envs\test\lib\site-packages\paddle\vision\transforms\functional_pil.py:38: DeprecationWarning: BICUBIC is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.BICUBIC instead.
  'bicubic': Image.BICUBIC,

D:\conda\envs\test\lib\site-packages\paddle\vision\transforms\functional_pil.py:39: DeprecationWarning: BOX is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.BOX instead.
  'box': Image.BOX,

D:\conda\envs\test\lib\site-packages\paddle\vision\transforms\functional_pil.py:40: DeprecationWarning: LANCZOS is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.LANCZOS instead.
  'lanczos': Image.LANCZOS,

D:\conda\envs\test\lib\site-packages\paddle\vision\transforms\functional_pil.py:41: DeprecationWarning: HAMMING is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.HAMMING instead.
  'hamming': Image.HAMMING

**Comment by aptx1231** [comment]
我也遇到了这个问题，请问解决了吗

**Comment by SigureMo** [comment]
应该是前段时间 Pillow 发布的 7.1.0 弃用了一系列 API 导致的，看样子 #42307 已经修复了该问题，估计过几天发布的 2.3.0 应该就没这个问题了～
