### ISSUE TITLE
(InvalidArgument) concat(): argument 'X' (position 0) must be list of Tensors, but got empty list

### ISSUE THREAD

**Issue by Wei-JL** [PaddlePaddle/Paddle#41688]
### bug描述 Describe the Bug

```
cls_targets = paddle.concat(cls_targets, 0)
       cls_targets为list , 里面只有一个为0的tensor -->Tensor(shape=[0, 4], dtype=float32, place=CUDAPlace(0), stop_gradient=True, [])
   
```
  报错日志 : File "D:\PyCharm\YOLO\paddle_fuxian\yolox_paddle\nets\yolo_training.py", line 210, in get_losses
    cls_targets = paddle.concat(cls_targets, 0)
  File "D:\Anaconda3\envs\paddle2-2-2g\lib\site-packages\paddle\tensor\manipulation.py", line 345, in concat
    return paddle.fluid.layers.concat(input=x, axis=axis, name=name)

**Comment by Wei-JL** [comment]
您好，有什么解决方法吗？ 这边无法对Tensor(shape=[0, 4], dtype=float32, place=CUDAPlace(0), stop_gradient=True, []) concat

**Comment by ceci3** [comment]
shape设置成[0，4]应该不行，换成[1,4]呢

**Comment by Wei-JL** [comment]
您好~ 我是在复现中遇见的torch里面也会有这样的情况初夏 shape=[0, 4]  tensor 还是会加到cls_targets里面  如果我去掉这个空的 会有什么影响吗？

**Comment by ceci3** [comment]
可以去掉看下结果是不是正确的

**Comment by Bradly-s** [comment]
请问这个问题咋解决的？
