### ISSUE TITLE
关于cuda不兼容问题

### ISSUE THREAD

**Issue by terrancraft** [PaddlePaddle/Paddle#41686]
### 问题描述 Please describe your issue

描述问题/Describe the bug

我把训练好的模型部署到一台win10系统的机器中，执行eval或者inference推断时都会报错：

cudaErrorNoKernelImageDevice: no kernel image is available for execution on the device.

个人感觉是cuda driver 版本、cudatoolkit版本和paddle版本出现了不兼容的问题，但我不太确定，

想把具体情况复述给大佬们，能否帮我看一下如何解决这个问题？ 谢谢！
复现/Reproduction

python tools/eval.py -c *** -o weights=***
使用模型:
picodet_l_640
环境/Environment

虚拟环境:
python: 3.7
paddle-gpu: 2.2.2(cudatoolkit 10.2)
paddledet : release-2.4

硬件信息:
win10
cpu i9
RTX 3060ti单卡
CUDA版本:
cuda driver: 512.15 cuda versionj: 11.6(driver API version: 11.6)
cudatoolkit: 10.2(runtime API version: 10.2)
cudnn: 7.6.5

简要地说, 考虑到cudatoolkit 10.2版本在win10上更稳定，所以我选择了10.2版本，同时下载了对应cudatoolkit 10.2版本的paddle。
最新的cuda driver对应的cuda version是11.6，理论上来说driver API version >= runtime API version就可以启动程序。
但是现在还是出现了不兼容的问题，我就不明白了。
望解答， 多谢！

**Comment by zlsh80826** [comment]
安培架構顯示卡 (30系列) 需求 cuda 11 以上才能支援

**Comment by terrancraft** [comment]
> 



> 安培架構顯示卡 (30系列) 需求 cuda 11 以上才能支援

您的意思我把paddle和cudatoolkit都换成11.2?

**Comment by zlsh80826** [comment]
> 您的意思我把paddle和cudatoolkit都换成11.2?

是的, paddle10.2的包不包含ampere架構的kernels[原代碼參考](https://github.com/PaddlePaddle/Paddle/blob/develop/cmake/cuda.cmake#L193), 同時 cudatoolkit 也需要升級到 11.2 之上
