### ISSUE TITLE
The registered buffer should be a core.VarBase, but received Variable. 

### ISSUE THREAD

**Issue by janelu9** [PaddlePaddle/Paddle#41682]
### bug描述 Describe the Bug

```
paddle.enable_static()
place = "gpu"
place = paddle.set_device(place)

test_program = paddle.static.Program()
startup_program = paddle.static.Program()
with paddle.static.program_guard(test_program, startup_program):
    img = paddle.static.data(
        name="img", shape=[None, 3,224,224], dtype="float32")
    model= SwinTransformerEncoder(embed_dim=48,depths=[2, 2, 6, 2],num_heads=[3, 6, 12, 24],window_size=7,drop_path_rate=0.2)

```

**Comment by janelu9** [comment]
paddlepaddle-gpu                   2.2.2.post112

**Comment by janelu9** [comment]
> ### bug描述 Describe the Bug
> ```
> paddle.enable_static()
> place = "gpu"
> place = paddle.set_device(place)
> 
> test_program = paddle.static.Program()
> startup_program = paddle.static.Program()
> with paddle.static.program_guard(test_program, startup_program):
>     img = paddle.static.data(
>         name="img", shape=[None, 3,224,224], dtype="float32")
>     model= SwinTransformerEncoder(embed_dim=48,depths=[2, 2, 6, 2],num_heads=[3, 6, 12, 24],window_size=7,drop_path_rate=0.2)
> ```
> 
> ### 其他补充信息 Additional Supplementary Information
> _No response_

```
/mnt/e/OCR/zh_TrOCR/swin_transformer.py in __init__(self, dim, window_size, num_heads, qkv_bias, qk_scale, attn_drop, proj_drop)
    157         relative_position_index = relative_coords.sum(-1)  # Wh*Ww, Wh*Ww
    158         self.register_buffer("relative_position_index",
--> 159                              relative_position_index)
    160 
    161         self.qkv = nn.Linear(dim, dim * 3, bias_attr=qkv_bias)

~/anaconda3/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py in register_buffer(self, name, tensor, persistable)
    764             raise TypeError(
    765                 "The registered buffer should be a core.VarBase, but received {}.".
--> 766                 format(type(tensor).__name__))
    767         else:
    768             self._buffers[name] = tensor

TypeError: The registered buffer should be a core.VarBase, but received Variable.
```

**Comment by ceci3** [comment]
可能是动静态图混用了，麻烦贴一下可复现的代码哈

**Comment by janelu9** [comment]
> 可能是动静态图混用了，麻烦贴一下可复现的代码哈
这个是 swin transformer的代码是动态图 我现在就是要把它转成静态图 然后就报错了
https://gitee.com/janelu9/TrOCR/blob/main/swin_transformer.py

**Comment by janelu9** [comment]
> > 可能是动静态图混用了，麻烦贴一下可复现的代码哈
> > 这个是 swin transformer的代码是动态图 我现在就是要把它转成静态图 然后就报错了
> > https://gitee.com/paddlepaddle/PaddleClas/blob/release/2.3/ppcls/arch/backbone/model_zoo/swin_transformer.py

**Comment by janelu9** [comment]
> 可能是动静态图混用了，麻烦贴一下可复现的代码哈

这个是 swin transformer的代码是动态图 我现在就是要把它转成静态图 然后就报错了
https://gitee.com/paddlepaddle/PaddleClas/blob/release/2.3/ppcls/arch/backbone/model_zoo/swin_transformer.py

**Comment by jiluojiluo** [comment]
我也遇到相同的问题，

**Comment by jiluojiluo** [comment]
> 我也遇到相同的问题，

我后来发现，我的系统用了两个paddlepaddle的模型，一个是ernie，一个是layout，两个不能同时在一台服务器上，分两个服务器部署后，问题解决。不知道啥原因。
