### ISSUE TITLE
DeviceContext should not be `const T&` in `Operator::Run(...)`

### ISSUE THREAD

**Issue by reyoung** [PaddlePaddle/Paddle#4169]
Some method of `DeviceContext` is not const, such as

```cpp
class GPUDeviceContext: public DeviceContext {
  cuda_stream_t Stream();
  cunn_handle_t CudnnHandle();
};
```

The code is [here](https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/platform/device_context.h#L72). It because the handlers and stream are initialized lazily, i.e., they will not be initialized only until they are used. So `DeviceContext` is a mutable object, not const object.

But in `Operator::Run`, we use `DeviceContext` like `Operator::Run(..., const DeviceContext& context);`. So if we want to use `cudaStream` or `cudnnHandle`, we must `const_cast(context)` to drop `const` qualifier. The code like

```cpp
auto cudnn_handle = const_cast<DeviceContext&>(context).cudnnHandle();
```

However, `const_cast` is very harmful and should be forbidden in our code.

**Comment by dzhwinter** [comment]
We have discussed it one month ago. In our current implementation, we almost use the `cuda_stream_t` in nowhere. The agreement we achieved last time is **When it needs to cast const, go ahead**.

**Comment by reyoung** [comment]
@dzhwinter 
I found the issue and the PR before.

The issue is #3468. the PR is #3475.

But I think there is no agreement and the status of the issue is still open.

**Comment by wangkuiyi** [comment]
It seems that we have [three handles](https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/platform/device_context.h#L88) that are lazy-initialized:

```cpp
  cudaStream_t       stream_{nullptr};
  cudnnHandle_t      cudnn_handle_{nullptr};
  cublasHandle_t     cublas_handle_{nullptr};
```

Let us remove the lazy-initialization, and create them all, in spite of if they are used later, in the constructor of class `CUDADeviceContext`.
