### ISSUE TITLE
使用cosine_similarity需要提前对数据归一化吗？

### ISSUE THREAD

**Issue by yeyupiaoling** [PaddlePaddle/Paddle#41698]
### 请提出你的问题 Please ask your question

 - PaddlePaddle 2.2.2

我是用[paddle.nn.functional.cosine_similarity](https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/nn/functional/cosine_similarity_cn.html#cosine-similarity) 这个接口，需要对输入数据做归一化吗？

**Comment by ceci3** [comment]
这个接口里没有归一化操作，您如果需要可以在外面归一化哈
