### ISSUE TITLE
Need to keep consistency between GPU and CPU implementation for conv layer.

### ISSUE THREAD

**Issue by qingqing01** [PaddlePaddle/Paddle#417]
Now the `ExpandConvLayer` implementation for CPU is not consistency with GPU implementation by cuDNN.

This issue is also related to #379

**Comment by wangyang59** [comment]
Hi @gangliao 
Have you started working on this issue? If not, I was just wondering if I could contribute to this one since I recently worked on the convolution codes and one of my co-worker needs this feature soon. 
thanks

**Comment by gangliao** [comment]
@wangyang59  Actually, I did not start this work immediately, because some other docs and bugs need me to fix soon. So if you want to contribute to this one, I am very appreciated it.

Thanks.

**Comment by wangyang59** [comment]
@gangliao 
Ok, I will take it over then.

**Comment by wangyang59** [comment]
@qingqing01 @reyoung 
I have fixed this bug and made the pull #636 
Please help review my code, thanks.
