### ISSUE TITLE
paddle lstm画出的模型结构图

### ISSUE THREAD

**Issue by daiwk** [PaddlePaddle/Paddle#4170]
![image](https://user-images.githubusercontent.com/4243530/30556371-34e87122-9cdd-11e7-8547-c778a416cf93.png)
为何画出的模型结构图有fc_3和fc_4两个全连接层呢？我理解应该是不是只要一个就够了呢？
![image](https://user-images.githubusercontent.com/4243530/30556461-7dea085e-9cdd-11e7-96ff-793b359c64f2.png)

**Comment by qingqing01** [comment]
```python
    output = paddle.layer.fc(
        input=[fc_last, lstm_last],
        size=class_dim,
        act=paddle.activation.Softmax(),
        bias_attr=bias_attr,
        param_attr=para_attr)
```
这层fc，实际是对`fc_last`, `lstm_last`各自做fc，有两个weight，然后结果相加，再做`softmax`激活。

但是我觉得图也不应该画出 `__fc_layer_4__`这层。

能问下具体是怎么画的吗？

**Comment by daiwk** [comment]
使用集群版的paddle
```
paddle make_diagram ./cluter_scripts/network_for_dot.py $dot_name.dot
dot $dot_name.dot -Tjpeg -o $dot_name.jpeg
```

**Comment by daiwk** [comment]
![image](https://user-images.githubusercontent.com/4243530/30577969-0afb8b1c-9d44-11e7-8fdd-5adbf665fcae.png)
抱歉，画出这个图的代码是这个……我看错文件了之前

**Comment by xiaolv3366** [comment]
paddle make_diagram network_for_dot.py $dot_name.dot
dot $dot_name.dot -Tpng -o $image_name.png
这个network_for_dot.py是网络配置吗？

**Comment by typhoonzero** [comment]
是的

**Comment by xiaolv3366** [comment]
我的怎么生成不了，空的。能给一个文件吗？
