### ISSUE TITLE
hook函数

### ISSUE THREAD

**Issue by tricksterANDthug** [PaddlePaddle/Paddle#41723]
### 需求描述 Feature Description

任务目标（请描述你正在做的项目是什么，如模型、论文、项目是什么？）; <br /> 需求场景（请描述你的项目中为什么需要用此功能）;  <br /> 功能描述（请简单描述或设计这个功能）
pytorch中有register_full_backward_hook，这个在梯度激活映射中比较好用，paddle这块目前没有对应的功能

### 替代实现 Alternatives

tensor中有对应的注册hook功能(register_hook)

**Comment by Ligoml** [comment]
相同issue https://github.com/PaddlePaddle/Paddle/issues/41724 ，在此issue中讨论该需求

**Comment by tricksterANDthug** [comment]
这个反向传播的hook函数，你们会在下个版本中添加吗？这个在GradCAM LayerCAM等论文中都有使用到

**Comment by Ligoml** [comment]
你是指 [paddle.Tensor.register_hook](https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/Tensor_cn.html#register-hook-hook) 吗？这个是已经有的

<img width="869" alt="image" src="https://user-images.githubusercontent.com/39876205/167059013-736727fa-c297-4359-ac54-deeb710752e8.png">

**Comment by tricksterANDthug** [comment]
register_full_backward_hook 我想要的是这个hook函数，和你上面那个不太一样，都是和梯度相关，但是register_full_backward_hook 可以在模型训练完成之后取得相应的梯度，register_hook在模型训练完成之后就取不到相应的hook了

**Comment by 15554710621** [comment]
torch.nn.Module.register_backward_hook(module, grad_in, grad_out)
