### ISSUE TITLE
运行paddle安装验证代码报错/警告paddle.utils.run_check()

### ISSUE THREAD

**Issue by Senwei-Huang** [PaddlePaddle/Paddle#41744]
### bug描述 Describe the Bug

代码：
import paddle
paddle.utils.run_check()

输出：
Running verify PaddlePaddle program ... 
PaddlePaddle works well on 1 CPU.
**W0412 23:16:06.400868 38450 fuse_all_reduce_op_pass.cc:76] Find all_reduce operators: 2. To make the speed faster, some all_reduce ops are fused during training, after fusion, the number of all_reduce ops is 2.**
PaddlePaddle works well on 2 CPUs.
PaddlePaddle is installed successfully! Let's start deep learning with PaddlePaddle now.

环境：
Ubuntu 18.04
python 3.9.7
paddle 2.2.2

**Comment by LielinJiang** [comment]
seems everything works fine?
