### ISSUE TITLE
paddle2.2.2创建张量时遇到NumPy弃用警告：DeprecationWarning

### ISSUE THREAD

**Issue by Senwei-Huang** [PaddlePaddle/Paddle#41745]
### bug描述 Describe the Bug

代码：
import paddle
print(paddle.to_tensor([0,1]))

输出：
/home/senweihuang/anaconda3/lib/python3.9/site-packages/paddle/tensor/creation.py:130: **DeprecationWarning: `np.object` is a deprecated alias for the builtin `object`. To silence this warning, use `object` by itself. Doing this will not modify any behavior and is safe. 
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  if data.dtype == np.object:**
Tensor(shape=[2], dtype=int64, place=CPUPlace, stop_gradient=True,
       [0, 1])

环境：
Ubuntu 18.04
python 3.9.7
paddle 2.2.2

**Comment by SigureMo** [comment]
应当已经于 #42929 解决了，升级到 2.3.1 应该就没这个 warning 啦～

<img width="694" alt="image" src="https://user-images.githubusercontent.com/38436475/178715530-bb0ce821-474a-4506-9109-7e6b3cd36393.png">

<img width="573" alt="image" src="https://user-images.githubusercontent.com/38436475/178715558-d57063ed-86f4-4584-a069-3c333bd5c347.png">
