### ISSUE TITLE
多卡获取模型的某一层输出

### ISSUE THREAD

**Issue by yeyupiaoling** [PaddlePaddle/Paddle#41767]
### 请提出你的问题 Please ask your question

单卡的时候，我可以`model.backbone(data)`模型模型指定层的输出

多卡的时候，model是DataParallel对象了。`model.backbone(data)`会报错，应该要这么写才能获取指定层的输出？
```
model = paddle.DataParallel(model)
```

**Comment by LielinJiang** [comment]
先判断一下model是不是DataParallel的实例，isinstance(model, paddle.Dataparallel)。
是的话就用model._layers.backbone(data)
