### ISSUE TITLE
【脚本任务】脚本任务没有错误日志，直接失败了，请问这是怎么回事？

### ISSUE THREAD

**Issue by jiaohuix** [PaddlePaddle/Paddle#41779]
### 请提出你的问题 Please ask your question

如题，没有错误日志，直接失败了。。。
![image](https://user-images.githubusercontent.com/68314259/163290007-248254c1-26ed-467e-985d-865ec563c209.png)
![image](https://user-images.githubusercontent.com/68314259/163290028-f8153c6d-390f-4adb-8ce0-ab013055c226.png)

**Comment by FrostML** [comment]
请问这是什么的界面？有网址什么的么？

**Comment by jiaohuix** [comment]
> 请问这是什么的界面？有网址什么的么？

您好，这是脚本任务的界面。

**Comment by jiaohuix** [comment]
> 请问这是什么的界面？有网址什么的么？
比如这个：https://aistudio.baidu.com/aistudio/clusterprojectdetail/2262178

**Comment by FrostML** [comment]
使用的 AI Studio？我转给 AI Studio 值班看下

**Comment by jiaohuix** [comment]
> 值班

是的，aistudio的脚本任务，没有报错。

**Comment by hohdiy** [comment]
内存溢出了。界面上应该能看到这个提示。

**Comment by jiaohuix** [comment]
没有这个提示额，我在notebook调试下看看



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年4月14日(星期四) 上午10:19
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [PaddlePaddle/Paddle] 【脚本任务】脚本任务没有错误日志，直接失败了，请问这是怎么回事？ (Issue #41779)





 
内存溢出了。界面上应该能看到这个提示。

**Comment by hohdiy** [comment]
是的，数据库里记录了，但是没有反应到界面上，这个已经提交改进卡片，多谢反馈。

**Comment by jiaohuix** [comment]
非常感谢，祝越来越好



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年4月14日(星期四) 上午10:32
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [PaddlePaddle/Paddle] 【脚本任务】脚本任务没有错误日志，直接失败了，请问这是怎么回事？ (Issue #41779)





 
是的，数据库里记录了，但是没有反应到界面上，这个已经提交改进卡片，多谢反馈。
