### ISSUE TITLE
混合精度训练在多卡服务器上训练报错：cudaErrorIllegalAddress

### ISSUE THREAD

**Issue by geekhch** [PaddlePaddle/Paddle#41785]
### bug描述 Describe the Bug

训练报错：OSError: (External) transform: failed to synchronize: cudaErrorIllegalAddress: an illegal memory access was encountered (at /paddle/paddle/fluid/imperative/basic_engine.cc:578)。报错代码：
```py
scaler = paddle.amp.GradScaler(init_loss_scaling=1024)
########其他无关代码#########

# 半精度训练
with paddle.amp.auto_cast():
    loss = model.compute_loss(model_inputs, labels)

scaled = scaler.scale(loss)
scaled.backward()  # 此行报错
scaler.minimize(optimizer, scaled)
optimizer.clear_grad()
```

经过调试发现是GradScaler()对象的状态信息默认存储在GPU:0，并且无法设置自定义place， 但是模型参数使用GPU:1计算，导致上述错误。

### 其他补充信息 Additional Supplementary Information
除了无法使用其他gpu，在单机多卡并行的时候使用这个api也会出错

**Comment by FrostML** [comment]
多卡训练启动方式以及 Python API 使用可以参考 [单机多卡训练文档](https://www.paddlepaddle.org.cn/documentation/docs/zh/guides/02_paddle2.0_develop/06_device_cn.html#launch)
使用 `paddle.DataParallel()` 且放在 `paddle.amp.GradScaler()` 之后执行。
device 设置可以直接用 `paddle.set_device("gpu")` 无需指定 `gpu:0`。

**Comment by geekhch** [comment]
> 

我指问题的不是多卡训练，而是服务器上有多张显卡，但gpu:0被其他进程占用，我需要使用gpu:1训练。另外，即使单机多卡并行训练，DataParallel对模型结构的局限性较大，例如无法使用in-batch对比loss，我需要使用spawn启动并行。

**Comment by geekhch** [comment]
> 多卡训练启动方式以及 Python API 使用可以参考 [单机多卡训练文档](https://www.paddlepaddle.org.cn/documentation/docs/zh/guides/02_paddle2.0_develop/06_device_cn.html#launch) 使用 `paddle.DataParallel()` 且放在 `paddle.amp.GradScaler()` 之后执行。 device 设置可以直接用 `paddle.set_device("gpu")` 无需指定 `gpu:0`。

我指问题的不是多卡训练，而是服务器上有多张显卡，但gpu:0被其他进程占用，我需要使用gpu:1训练。另外，即使单机多卡并行训练，DataParallel对模型结构的局限性较大，例如不便使用in-batch对比loss，我需要使用spawn启动并行。

**Comment by FrostML** [comment]
export CUDA_VISIBLE_DEVICES=1
