### ISSUE TITLE
树形结构的数据，如何作为特征输入paddle

### ISSUE THREAD

**Issue by thomaslwang** [PaddlePaddle/Paddle#4179]
我需要训练树形结构数据，尤其是对数的结构信息进行训练。比如这棵树有一个根节点，三个子节点。
有没有好的方案可以对树的结构提取特征？

**Comment by lcy-seso** [comment]
- 现有的NN模型中，能够直接学习结构化数据的只有Recursive NN这一枝；在结构化数据上运行 BBTS （Backpropagation through Structure）算法。
- 但是现在对 Recursive 类的方法，各个框架实现起来都比较麻烦，需要框架能够具有一定的动态性。

- 替代方法，将结构化数据以某种便利方式转化为序列进行处理。
- 需要考虑的一个设计因素是，序列的时间步之间是否需要有依赖关系。

**Comment by thomaslwang** [comment]
感谢回复。
能不能把树的结构转成稀疏矩阵类型的特征加入训练？
比如这棵树有一个根节点，三个子节点。转成两行三列的矩阵，矩阵四个元素(0,1),(1,0),(1,1),(1,2)的值置1

**Comment by lcy-seso** [comment]
- 我觉得没啥绝对的不可以，这个属于机器学习中特征如何表示的问题。
- 计算机中所有的非线性数据结构最终都会转化成线性的。上面你举的例子是一样的道理。唯一需要考虑的是，在转化后的特征表示下是否有表达能力的损失，是否能够表现出原先结构化数据中呈现出的统计显著性规律。

**Comment by thomaslwang** [comment]
太赞了，多谢回复。
