### ISSUE TITLE
Difference between NumElements and offset of LoDTensor

### ISSUE THREAD

**Issue by wanghaoshuang** [PaddlePaddle/Paddle#4181]
[LoDTensor::NumElements()](https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/framework/lod_tensor.h#L84)返回的是指定level的最后一个`element`的`offset`, 但是名字看起来像求指定level `element`数量。
而且，[LoDTensor::NumLevels()](https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/framework/lod_tensor.h#L80)确实是返回level的数量，是命名没统一，还是我对LoDTensor::lod_存储内容理解有误？

**Comment by QiJune** [comment]
NumElements(size_t level) 返回的是指定层级上的offset的个数
NumLevels() 返回的是sequence的层级有几个

**Comment by wanghaoshuang** [comment]
明白了，是我对LoDTensor::lod_存储内容理解有误。
