### ISSUE TITLE
ExternalError: CUBLAS error(1). gpu下運行一段時間，程序崩潰退出

### ISSUE THREAD

**Issue by najsword** [PaddlePaddle/Paddle#41835]
### bug描述 Describe the Bug

cuda:10.2
cudnn:8.3
tensortRT:7.2.3.4
paddle預測庫：manylinux_cuda10.2_cudnn8.1_avx_mkl_trt7_gcc5.4
系統：unbuntu16

問題描述：運行一段時間，檢測幾張圖片後，程序就退出崩潰。
崩潰信息：

--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
0   PaddleOCR::DBDetector::Run(cv::Mat&, std::vector<std::vector<std::vector<int, std::allocator<int> >, std::allocator<std::vector<int, std::allocator<int> > > >, std::allocator<std::vector<std::vector<int, std::allocator<int> >, std::allocator<std::vector<int, std::allocator<int> > > > > >&, std::vector<double, std::allocator<double> >*)
1   void paddle_infer::Tensor::CopyFromCpu<float>(float const*)
2   paddle::platform::DeviceContextPool::Get(paddle::platform::Place const&)
3   std::__future_base::_Deferred_state<std::_Bind_simple<void paddle::platform::EmplaceDeviceContext<paddle::platform::CUDADeviceContext, paddle::platform::CUDAPlace>(std::map<paddle::platform::Place, std::shared_future<std::unique_ptr<paddle::platform::DeviceContext, std::default_delete<paddle::platform::DeviceContext> > >, std::less<paddle::platform::Place>, std::allocator<std::pair<paddle::platform::Place const, std::shared_future<std::unique_ptr<paddle::platform::DeviceContext, std::default_delete<paddle::platform::DeviceContext> > > > > >*, paddle::platform::Place)::{lambda()#1} ()>, std::unique_ptr<paddle::platform::DeviceContext, std::default_delete<paddle::platform::DeviceContext> > >::_M_complete_async()
4   std::_Function_handler<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> (), std::__future_base::_Task_setter<std::unique_ptr<std::__future_base::_Result<std::unique_ptr<paddle::platform::DeviceContext, std::default_delete<paddle::platform::DeviceContext> > >, std::__future_base::_Result_base::_Deleter>, std::_Bind_simple<void paddle::platform::EmplaceDeviceContext<paddle::platform::CUDADeviceContext, paddle::platform::CUDAPlace>(std::map<paddle::platform::Place, std::shared_future<std::unique_ptr<paddle::platform::DeviceContext, std::default_delete<paddle::platform::DeviceContext> > >, std::less<paddle::platform::Place>, std::allocator<std::pair<paddle::platform::Place const, std::shared_future<std::unique_ptr<paddle::platform::DeviceContext, std::default_delete<paddle::platform::DeviceContext> > > > > >*, paddle::platform::Place)::{lambda()#1} ()>, std::unique_ptr<paddle::platform::DeviceContext, std::default_delete<paddle::platform::DeviceContext> > > >::_M_invoke(std::_Any_data const&)
5   paddle::platform::CUDADeviceContext::CUDADeviceContext(paddle::platform::CUDAPlace)
6   paddle::platform::CUDAContext::CUDAContext(paddle::platform::CUDAPlace const&, paddle::platform::stream::Priority const&, paddle::platform::stream::StreamFlag const&)
7   paddle::platform::CublasHandleHolder::CublasHandleHolder(CUstream_st*, cublasMath_t)
8   paddle::platform::EnforceNotMet::EnforceNotMet(paddle::platform::ErrorSummary const&, char const*, int)
9   paddle::platform::GetCurrentTraceBackString[abi:cxx11](bool)

----------------------
Error Message Summary:
----------------------
ExternalError: CUBLAS error(1). 
  [Hint: Please search for the error code(1) on website (https://docs.nvidia.com/cuda/cublas/index.html#cublasstatus_t) to get Nvidia's official solution and advice about CUBLAS Error.] (at /paddle/paddle/fluid/platform/cuda_helper.h:98)

**Comment by TeslaZhao** [comment]
您好，请补充一下Paddle的版本和模型信息

**Comment by TeslaZhao** [comment]
很可能是 cudnn:8.3 的版本不匹配，https://www.paddlepaddle.org.cn/documentation/docs/zh/install/compile/linux-compile.html#cpu-gpu

<img width="846" alt="image" src="https://user-images.githubusercontent.com/6309021/163530639-62415db6-87a6-4819-8561-debae17d5296.png">

**Comment by najsword** [comment]
> 您好，请补充一下Paddle的版本和模型信息

paddle预测库版本version信息：
GIT COMMIT ID: a5cf2e305b744e3ebd2f2210341f88d349d4ec5e
WITH_MKL: ON
WITH_MKLDNN: ON
WITH_GPU: ON
WITH_ROCM: OFF
CUDA version: 10.2
CUDNN version: v8.1
CXX compiler version: 5.4.0
WITH_TENSORRT: ON
TensorRT version: v7.2.3.4

模型版本：2.4

**Comment by najsword** [comment]
> 很可能是 cudnn:8.3 的版本不匹配，https://www.paddlepaddle.org.cn/documentation/docs/zh/install/compile/linux-compile.html#cpu-gpu
> 
> <img alt="image" width="846" src="https://user-images.githubusercontent.com/6309021/163530639-62415db6-87a6-4819-8561-debae17d5296.png">

尝试cudnn版本从8.3替换为8.1后，问题仍然存在

**Comment by TeslaZhao** [comment]
CUDA 工具包10.1/10.2配合cuDNN 7
