### ISSUE TITLE
能否使用PaddlePaddle训练出来的模型能转换为pb文件，使用opt 只能转换为nb文件

### ISSUE THREAD

**Issue by SuperCJC** [PaddlePaddle/Paddle#41867]
### 需求描述 Feature Description

任务目标（请描述你正在做的项目是什么，如模型、论文、项目是什么？）; <br /> 需求场景（请描述你的项目中为什么需要用此功能）;  <br /> 功能描述（请简单描述或设计这个功能）

**Comment by zhangting2020** [comment]
opt只能转换为Paddle Lite模型（.nb格式）
