### ISSUE TITLE
PaddleDetection初次安装后，输入“识别图片”，报错FileNotFoundError和infer.py的程序问题

### ISSUE THREAD

**Issue by yuguoyu123456** [PaddlePaddle/Paddle#41866]
### 请提出你的问题 Please ask your question

PaddleDetection初次安装后，输入“识别图片”，报错FileNotFoundError和infer.py的程序问题

以下是powershell的所有文字报告：

PS D:\paddlepaddle\PaddleDetection>
>> python tools/infer.py -c configs/ppyolo/ppyolo.yml -o use_gpu=true weights=https://paddlemodels.bj.bcebos.com/object_detection/ppyolo.pdparams --infer_img=demo/000000014439_640x640.jpg
C:\Users\Lenovo\AppData\Roaming\Python\Python39\site-packages\paddle\vision\transforms\functional_pil.py:36: DeprecationWarning: NEAREST is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.NEAREST or Dither.NONE instead.
  'nearest': Image.NEAREST,
C:\Users\Lenovo\AppData\Roaming\Python\Python39\site-packages\paddle\vision\transforms\functional_pil.py:37: DeprecationWarning: BILINEAR is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.BILINEAR instead.
  'bilinear': Image.BILINEAR,
C:\Users\Lenovo\AppData\Roaming\Python\Python39\site-packages\paddle\vision\transforms\functional_pil.py:38: DeprecationWarning: BICUBIC is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.BICUBIC instead.
  'bicubic': Image.BICUBIC,
C:\Users\Lenovo\AppData\Roaming\Python\Python39\site-packages\paddle\vision\transforms\functional_pil.py:39: DeprecationWarning: BOX is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.BOX instead.
  'box': Image.BOX,
C:\Users\Lenovo\AppData\Roaming\Python\Python39\site-packages\paddle\vision\transforms\functional_pil.py:40: DeprecationWarning: LANCZOS is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.LANCZOS instead.
  'lanczos': Image.LANCZOS,
C:\Users\Lenovo\AppData\Roaming\Python\Python39\site-packages\paddle\vision\transforms\functional_pil.py:41: DeprecationWarning: HAMMING is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.HAMMING instead.
  'hamming': Image.HAMMING
Traceback (most recent call last):
  File "D:\paddlepaddle\PaddleDetection\tools\infer.py", line 177, in <module>
    main()
  File "D:\paddlepaddle\PaddleDetection\tools\infer.py", line 139, in main
    cfg = load_config(FLAGS.config)
  File "D:\paddlepaddle\PaddleDetection\ppdet\core\workspace.py", line 114, in load_config
    cfg = _load_config_with_base(file_path)
  File "D:\paddlepaddle\PaddleDetection\ppdet\core\workspace.py", line 78, in _load_config_with_base
    with open(file_path) as f:
FileNotFoundError: [Errno 2] No such file or directory: 'configs/ppyolo/ppyolo.yml'
PS D:\paddlepaddle\PaddleDetection>

**Comment by yuguoyu123456** [comment]
![666](https://user-images.githubusercontent.com/52940163/163581446-6084f5e7-d572-4961-a10e-420c150e0ecd.jpg)

**Comment by zhangting2020** [comment]
请问使用的是哪个版本的PaddleDetection呢？可以自己先查看下configs/ppyolo目录下面是否有你指定的yml文件。我看目前release2.4是没有你指定的这个yml文件的

**Comment by zhangting2020** [comment]
@yuguoyu123456 请问按照上面的方法，你的问题得到解决了吗

**Comment by zhangting2020** [comment]
如无问题，此issue将关闭。PaddleDetection使用上的疑问，可以直接在PaddleDetection 下提issue，相关同学会跟进。
