### ISSUE TITLE
【iterdataset如何组batch】paddlenlp的iterdataset如何组batch，加速数据的读取，防止内存溢出

### ISSUE THREAD

**Issue by jiaohuix** [PaddlePaddle/Paddle#41870]
### 请提出你的问题 Please ask your question

我正在做机器翻译的比赛，英西的数据有20m，直接用mapdataset读取在aistudio上会内存溢出，我想要iterdataset然后按照tokens数动态组batch，不知道可不可以。目前已经将fairseq的数据二值化处理和读取完成，在读取一行行的idx后转为iterdataset后组batch错误，请问有没有interdataset组batch的demo？
![image](https://user-images.githubusercontent.com/68314259/163655899-ab68bfee-722b-41fb-800e-416d3df0206e.png)

**Comment by jiaohuix** [comment]
已经解决了，我用迭代器收集一个buffer的data，然后动态组batch用生成器逐个返回，可以实现快速加载并占少量内存了。
![image](https://user-images.githubusercontent.com/68314259/163695385-18854708-c82e-4e9f-aaf7-5a6fb86991c0.png)

**Comment by danleifeng** [comment]
好的，后续有什么问题欢迎提问
