### ISSUE TITLE
手写数字识别，这个语句怎么理解的

### ISSUE THREAD

**Issue by leechenggg** [PaddlePaddle/Paddle#41871]
### 请提出你的问题 Please ask your question

![O`6QH 32UTA_7HLUGZ80`{S](https://user-images.githubusercontent.com/100515681/163657837-149f262b-fb00-49c6-a5c1-45f7c2213869.png)

**Comment by danleifeng** [comment]
您好，可以看下paddlepaddle官网文档和教程，里面包含LeNet网络在MNIST数据集下的训练，供参考。https://www.paddlepaddle.org.cn/documentation/docs/zh/practices/cv/image_classification.html#id1

**Comment by LatinaDaisuki** [comment]
model是mnist的一个实例对象，父类是paddle.nn，model.train()实际上是调用父类里面的train函数
