### ISSUE TITLE
 Compiling paddle with VS2019, error smallVector statis assert failed

### ISSUE THREAD

**Issue by SpaceView** [PaddlePaddle/Paddle#41874]
### 问题描述 Issue Description

严重性	代码	说明	项目	路径	文件	行	禁止显示状态
错误(活动)	E1574	静态断言失败，原因是 "wasted space in SmallVector size 0"	prepared_operator	E:\vPaddle\paddledev\paddle\utils	E:\vPaddle\paddledev\paddle\utils\small_vector.h	1355	
严重性	代码	说明	项目	路径	文件	行	禁止显示状态
错误(活动)	E1574	静态断言失败，原因是 "wrong alignment for 32-byte aligned T"	prepared_operator	E:\vPaddle\paddledev\paddle\utils	E:\vPaddle\paddledev\paddle\utils\small_vector.h	1360	

### 版本&环境信息 Version & Environment Information

Paddle version: develop
CPU: 11th Gen Intel(R) Core(TM) i5-11400H @ 2.70GHz   2.69 GHz
GPU: cuda RTX3050 laptop GPU
Windows 10
Python: 3.8.12

**Comment by SpaceView** [comment]
I'm sorry but this is weird, I deleted all the build file, and rebuild the paddle program, the 2 errors disappeared.
It seems this is from the VS2019 intellisense bug， not from paddle project.
Current I've finished the debug mode compilation.

**Comment by danleifeng** [comment]
感谢提问，以后有任务问题欢迎咨询~
