### ISSUE TITLE
Windows下从源码编译 paddle_inference.lib 无法链接

### ISSUE THREAD

**Issue by GreatV** [PaddlePaddle/Paddle#41875]
### 问题描述 Issue Description

编译命令：

```bash
cmake .. -GNinja -DCMAKE_BUILD_TYPE=Release
ninja
```

输出：

```
[3772/3775] Linking CXX shared library paddle\fluid\inference\paddle_inference.dll
FAILED: paddle/fluid/inference/paddle_inference.dll paddle/fluid/inference/paddle_inference.lib
cmd.exe /C "cd . && "C:\Program Files\CMake\bin\cmake.exe" -E vs_link_dll --intdir=paddle\fluid\inference\CMakeFiles\paddle_inference_shared.dir --rc=C:\PROGRA~2\WI3CF2~1\10\bin\100177~1.0\x64\rc.exe --mt=C:\PROGRA~2\WI3CF2~1\10\bin\100177~1.0\x64\mt.exe --manifests  -- C:\PROGRA~2\MICROS~1\2017\COMMUN~1\VC\Tools\MSVC\1416~1.270\bin\Hostx64\x64\link.exe /nologo @CMakeFiles\paddle_inference_shared.rsp  /out:paddle\fluid\inference\paddle_inference.dll /implib:paddle\fluid\inference\paddle_inference.lib /pdb:paddle\fluid\inference\paddle_inference.pdb /dll /version:0.0 /machine:x64 /ignore:4049 /ignore:4217 /ignore:4006 /ignore:4221 /NODEFAULTLIB:MSVCRT.LIB /INCREMENTAL:NO  && cd ."
LINK: command "C:\PROGRA~2\MICROS~1\2017\COMMUN~1\VC\Tools\MSVC\1416~1.270\bin\Hostx64\x64\link.exe /nologo @CMakeFiles\paddle_inference_shared.rsp /out:paddle\fluid\inference\paddle_inference.dll /implib:paddle\fluid\inference\paddle_inference.lib /pdb:paddle\fluid\inference\paddle_inference.pdb /dll /version:0.0 /machine:x64 /ignore:4049 /ignore:4217 /ignore:4006 /ignore:4221 /NODEFAULTLIB:MSVCRT.LIB /INCREMENTAL:NO /MANIFEST /MANIFESTFILE:paddle\fluid\inference\paddle_inference.dll.manifest" failed (exit code 1170) with the following output:
Microsoft (R) Incremental Linker Version 14.16.27047.0
Copyright (C) Microsoft Corporation.  All rights reserved.

CMakeFiles\paddle_inference_shared.rsp : fatal error LNK1170: 命令文件中的行包含 131071 个或更多字符
[3773/3775] Linking CXX shared library paddle\fluid\pybind\paddle_pybind.dll
ninja: build stopped: subcommand failed.
```

### 版本&环境信息 Version & Environment Information

****************************************
Paddle version: None
Paddle With CUDA: None

OS: Windows 10
Python version: 3.9.6

CUDA version: 11.3.109
Build cuda_11.3.r11.3/compiler.29920130_0
cuDNN version: None.None.None
Nvidia driver version: None
****************************************

**Comment by zhwesky2010** [comment]
@GreatV 你好，请问使用最新的paddle代码编译的吗

**Comment by GreatV** [comment]
> @GreatV 你好，请问使用最新的paddle代码编译的吗

是的，develop 和release 2.2 都试过，都是一样的报错。

**Comment by betterpig** [comment]
一种情况是Paddle所在路径较长，导致命令行中的行字符数超限。如果是这种情况，请将Paddle放到较浅目录编译，如D:\Paddle。

**Comment by GreatV** [comment]
> 一种情况是Paddle所在路径较长，导致命令行中的行字符数超限。如果是这种情况，请将Paddle放到较浅目录编译，如D:\Paddle。

好的，我试一试。

**Comment by GreatV** [comment]
> 一种情况是Paddle所在路径较长，导致命令行中的行字符数超限。如果是这种情况，请将Paddle放到较浅目录编译，如D:\Paddle。



> > 一种情况是Paddle所在路径较长，导致命令行中的行字符数超限。如果是这种情况，请将Paddle放到较浅目录编译，如D:\Paddle。
> 
> 好的，我试一试。

我放在E:\Paddle下也是报这个错。

**Comment by betterpig** [comment]
> > 一种情况是Paddle所在路径较长，导致命令行中的行字符数超限。如果是这种情况，请将Paddle放到较浅目录编译，如D:\Paddle。
> 
> > > 一种情况是Paddle所在路径较长，导致命令行中的行字符数超限。如果是这种情况，请将Paddle放到较浅目录编译，如D:\Paddle。
> > 
> > 
> > 好的，我试一试。
> 
> 我放在E:\Paddle下也是报这个错。

之前碰到相同的问题是因为paddle的target数量太多，但是最新的develop已经把target数量降低了有三分之一。你再试试cmake加上联合编译 -DWITH_UNITY_BUILD=ON

**Comment by GreatV** [comment]
> > > 一种情况是Paddle所在路径较长，导致命令行中的行字符数超限。如果是这种情况，请将Paddle放到较浅目录编译，如D:\Paddle。
> > 
> > 
> > > > 一种情况是Paddle所在路径较长，导致命令行中的行字符数超限。如果是这种情况，请将Paddle放到较浅目录编译，如D:\Paddle。
> > > 
> > > 
> > > 好的，我试一试。
> > 
> > 
> > 我放在E:\Paddle下也是报这个错。
> 
> 之前碰到相同的问题是因为paddle的target数量太多，但是最新的develop已经把target数量降低了有三分之一。你再试试cmake加上联合编译 -DWITH_UNITY_BUILD=ON

谢谢，使用 ` -DWITH_UNITY_BUILD=ON`可以生成。

```bash
cmake .. -GNinja -DWITH_UNITY_BUILD=ON
```

**Comment by yang131313** [comment]
你好，现在Paddle已经有编译好的安装包了，请问你在什么任务场景下需要编译Paddle呀？比如是需要新增算子、还是需要修改飞桨源代码，或者有什么其他的用途呢？

**Comment by GreatV** [comment]
> 你好，现在Paddle已经有编译好的安装包了，请问你在什么任务场景下需要编译Paddle呀？比如是需要新增算子、还是需要修改飞桨源代码，或者有什么其他的用途呢？

新增算子
