### ISSUE TITLE
载入模型之后用paddle.DataParallel加速报错

### ISSUE THREAD

**Issue by Wei-JL** [PaddlePaddle/Paddle#41880]
### bug描述 Describe the Bug

File "D:\PyCharm\YOLO\paddle_fuxian\yolox_paddle\yolo.py", line 100, in generate
    self.net = paddle.DataParallel(self.net)
  File "D:\Tool\Anaconda3\envs\paddleANDtorch\lib\site-packages\paddle\fluid\dygraph\parallel.py", line 560, in __init__
    self).__init__(layers.full_name() + "_data_parallel")
AttributeError: 'NoneType' object has no attribute 'full_name'
报错日志

**Comment by Wei-JL** [comment]
您好，请问这个是什么问题呢

**Comment by danleifeng** [comment]
请问下能提供下可复现的代码 吗，另外能补充下 paddle使用的版本和环境吗？

**Comment by Wei-JL** [comment]
win11+ CUDA11.3 +CUDNN8.2.1 + paddle 2.2.2
复现YOLOx  模型可以正常训练，这是为了predict写的 
  
```
self.net = YoloBody(self.num_classes, self.phi)
device = 'gpu' if paddle.device.is_compiled_with_cuda() else 'cpu'
model_dict = paddle.load(self.model_path)
self.net.set_state_dict(model_dict)
# self.net.load_state_dict(paddle.load(self.model_path, map_location=device))
self.net = self.net.eval()
print('{} model, and classes loaded.'.format(self.model_path))

if self.cuda:
    self.net = paddle.DataParallel(self.net)  #次行报错 日志如标题描述
    paddle.device.set_device(device) 

```

**Comment by Wei-JL** [comment]
谢谢 我知道问题所在了~

**Comment by danleifeng** [comment]
嗯嗯，好的

**Comment by Wei-JL** [comment]
> 嗯嗯，好的

代码这样改就没问题 ，
```
self.net = YoloBody(self.num_classes, self.phi)
device = 'gpu' if paddle.device.is_compiled_with_cuda() else 'cpu'
model_dict = paddle.load(self.model_path)
self.net.set_state_dict(model_dict)
# self.net.load_state_dict(paddle.load(self.model_path, map_location=device))
# self.net = self.net.eval()    此行注释， 就不会报错。
print('{} model, and classes loaded.'.format(self.model_path))
# self.net = self.net.eval()

if self.cuda:
  self.net = paddle.DataParallel(self.net)
  paddle.device.set_device(device)
```
如上代码，self.net = self.net.eval() 如果注释这行，不切换为eval模式，后面预测会导致反向传播更新梯度吗？
因为我切换eval模式使用paddle.DataParallel就会报AttributeError: 'NoneType' object has no attribute 'full_name'

**Comment by danleifeng** [comment]
DataParallel 传入的参数是 第一行的 self.net， eval()你看看返回值是什么

**Comment by Wei-JL** [comment]
self.net = paddle.DataParallel(self.net, eval())
TypeError: eval expected at least 1 arguments, got 0

**Comment by Wei-JL** [comment]
> Contributor
> ### [<img alt="@danleifeng" width="20" height="20" src="https://avatars.githubusercontent.com/u/52735331?s=60&amp;v=4">](/danleifeng) ** [danleifeng](/danleifeng) ** commented [2小时前](#issuecomment-1101956873)


    self.net = paddle.DataParallel(self.net, eval())
TypeError: eval expected at least 1 arguments, got 0
报错

**Comment by danleifeng** [comment]
我的意思是 
DataParallel 传入的参数是 第一行的 self.net类型 ，附上DataParallel 的文档：https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/DataParallel_cn.html#dataparallel 

另外 你可以看下 self.net.eval()返回值是什么
