### ISSUE TITLE
TypeError: beam_search() takes at least 6 arguments (7 given)

### ISSUE THREAD

**Issue by 13488862011** [PaddlePaddle/Paddle#419]
seq2seq 模型训练出来，但gen.sh 时出现以下错误，请帮忙分析
sh gen.sh 
I1110 12:13:26.304188 5461 Util.cpp:144] commandline: /home//.jumbo/bin/../opt/paddle/bin/paddle_trainer --job=test --config=translation/gen.conf --save_dir=translation/model --use_gpu=false --num_passes=3 --test_pass=2 --trainer_count=1 
I1110 12:13:26.304491  5461 Util.cpp:113] Calling runInitFunctions
I1110 12:13:26.304864  5461 Util.cpp:126] Call runInitFunctions done.
Traceback (most recent call last):
  File "/home//.jumbo/lib/python2.7/site-packages/paddle-0.8.0b0-py2.7.egg/paddle/trainer/config_parser.py", line 3113, in parse_config_and_serialize
    config = parse_config(config_file, config_arg_str)
  File "/home//.jumbo/lib/python2.7/site-packages/paddle-0.8.0b0-py2.7.egg/paddle/trainer/config_parser.py", line 3089, in parse_config
    execfile(config_file, make_config_environment(config_file, config_args))
  File "translation/gen.conf", line 36, in <module>
    gru_encoder_decoder(gen_conf, is_generating)
  File "/home//paddlepaddle/baidu/idl/paddle/demo/seqToseq/seqToseq_net.py", line 177, in gru_encoder_decoder
    max_length=max_length)
  File "/home//.jumbo/lib/python2.7/site-packages/paddle-0.8.0b0-py2.7.egg/paddle/trainer_config_helpers/default_decorators.py", line 45, in __wrapper__
    return func(*args, **kwargs)
TypeError: beam_search() takes at least 6 arguments (7 given)
F1110 12:13:26.575796  5461 PythonUtil.cpp:130] Check failed: (ret) != nullptr Python Error: <type 'exceptions.TypeError'> : beam_search() takes at least 6 arguments (7 given)

**Comment by luotao1** [comment]
请问是完全跑的demo，还是自己改过配置了呢？是用什么版本跑的，源码编译的，还是别的？

**Comment by 13488862011** [comment]
是用新的数据跑的，是jumbo 安装的，paddle_main 0.8.0b0-1 [installed 0.8.0b0-1]

**Comment by luotao1** [comment]
可以采用github上的master源码编译试试

**Comment by 13488862011** [comment]
编译的成本挺高的，能从代码角度帮忙分析下吗，看是数据的问题还是版本的问题？

**Comment by luotao1** [comment]
能贴一下`seqToseq_net.py`使用beam search的那段，和`python/paddle/trainer_config_helpers/layers.py`里def beam_search的那段么

**Comment by 13488862011** [comment]
好的 多谢了
seqToseq_net.py使用beam search
        # In generation, the decoder predicts a next target word based on
        # the encoded source sequence and the last generated target word.

        # The encoded source sequence (encoder's output) must be specified by
        # StaticInput, which is a read-only memory.
        # Embedding of the last generated word is automatically gotten by
        # GeneratedInputs, which is initialized by a start mark, such as <s>,
        # and must be included in generation.

        trg_embedding = GeneratedInput(
            size=target_dict_dim,
            embedding_name='_target_language_embedding',
            embedding_size=word_vector_dim)
        group_inputs.append(trg_embedding)

        beam_gen = beam_search(name=decoder_group_name,
                               step=gru_decoder_with_attention,
                               input=group_inputs,
                               bos_id=0,
                               eos_id=1,
                               beam_size=beam_size,
                               max_length=max_length)

        seqtext_printer_evaluator(input=beam_gen,
                                  id_input=data_layer(name="sent_id", size=1),
                                  dict_file=trg_dict_path,
                                  result_file=gen_trans_file)
        outputs(beam_gen)

python/paddle/trainer_config_helpers/layers.py里def beam_search:
@wrap_name_default()
def beam_search(step, input, bos_id, eos_id, beam_size,
                result_file, dict_file="", id_input=None,
                max_length=500, name=None,
                num_results_per_sample=None):
    """ 注释太长去掉了""
 if num_results_per_sample is None:
        num_results_per_sample = beam_size
    if num_results_per_sample > beam_size:
        logger.warning("num_results_per_sample should be less than beam_size")

    if isinstance(input, StaticInput) or isinstance(input,
                                                    BaseGeneratedInput):
        input = [input]

    generated_input_index = -1

    real_input = []
    for i, each_input in enumerate(input):
        # print type(each_input)
        assert isinstance(each_input, StaticInput) or isinstance(each_input,
                                                          BaseGeneratedInput)
        if isinstance(each_input, BaseGeneratedInput):
            assert generated_input_index == -1
            generated_input_index = i
        else:
            real_input.append(each_input)

    assert generated_input_index != -1

    gipt = input[generated_input_index]
    assert isinstance(gipt, BaseGeneratedInput)

    gipt.bos_id = bos_id
    gipt.eos_id = eos_id

    def __real_step__(*args):
        eos_name = "__%s_eos_layer__" % name
        RecurrentLayerGroupSetGenerator(Generator(
            eos_layer_name=eos_name,
            max_num_frames=max_length,
            beam_size=beam_size,
            num_results_per_sample=num_results_per_sample))

        args = list(args)
        args.insert(generated_input_index, gipt.before_real_step())

        predict = gipt.after_real_step(step(*args))

        eos_layer(input=predict, eos_id=eos_id, name=eos_name)

        return predict

    tmp = recurrent_group(step=__real_step__, input=real_input, reverse=False,
                          name=name)
 if id_input is None:
        inputs = [tmp.name]
    else:
        assert isinstance(id_input, LayerOutput)
        inputs = [id_input.name, tmp.name]
        tmp.parents.append(id_input)

    Evaluator(name='target_printer',
              type='seq_text_printer',
              dict_file=dict_file,
              result_file=result_file,
              inputs=inputs
              )
    return tmp

**Comment by luotao1** [comment]
你的demo是新的，layers.py是老的。你看beam search接口中的result_file, dict_file, id_input，现在全在seqtext_printer_evaluator中。所以你得把layers.py中关于beam search和seqtext_printer_evaluator给更新了。

**Comment by 13488862011** [comment]
发现更新layers.py整个文件后，又有新的错误;
paddle的最新版本是要以https://github.com/baidu/Paddle 最新的为准吗；

**Comment by luotao1** [comment]
是的，所以你用github上的版本把

**Comment by 13488862011** [comment]
0
0>---0.0362176>- 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 >    国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰     国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰     国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰     国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰     国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰     国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰     国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰     国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰     国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰     国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰     国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰     国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰     国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰     国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰
  3 1>---11.5025>--- 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 >    国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰     国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰     国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰     国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰     国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰     国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰     国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰     国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰     国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰     国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰     国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰     国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰     国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰     国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 关银屏无惨
  4 2>---11.5451>--- 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 >    国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰     国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰     国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰     国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰     国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰     国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰     国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰     国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰     国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰     国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰     国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰     国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰     国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰     国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 国际米兰 关银屏无惨 关银屏无惨

**Comment by lcy-seso** [comment]
有几个问题，想再详细了解一下：（1）这个模型训练了多久呢？训练数据多少，上面重复生成的模型，对训练集的拟合效果目前是什么水平呢？生成模型一般在前期没有充分训练时，会出现重复生成的问题。（2）如果已经训练了足够的时间，看上去像是某些细节的bug，比如输入数据id 序列的转换都变成<unk>（举个例子），可以在一些输入数据细节上再查一下。

**Comment by 13488862011** [comment]
好的，现在在词典里加了<s> <e> <unk>等之类的重新训练后，问题解决了；
我的训练数据是100w，训练了4轮，大概对了下对训练集的拟合还较好，准确率为90%以上，但在测试集合上的效果较差，准确率仅为10%-20%左右，这个有什么办法吗？

**Comment by reyoung** [comment]
如何训练模型请开新的issue提问，之前的问题已经解决了。
