### ISSUE TITLE
multi cost layer

### ISSUE THREAD

**Issue by ckarying** [PaddlePaddle/Paddle#4191]
paddle如何才能实现以multi cost作为目标进行优化，例如这样
```python
cost = paddle.layer.square_error_cost(input=y_predict, label=y1) + 
       paddle.layer.square_error_cost(input=y_predict, label=y2) 
```

**Comment by Xreki** [comment]
在Paddle中，实现两个Layer计算结果的求和，可以使用`paddle.layer.addto`，但是`addto`不能作为cost layer。在Paddle中，只有cost layer可以作为网络的最后一层，不需要接收来自其他层的梯度作为输入。

Paddle可以支持使用多个损失函数进行多目标学习，只需要定义多个cost layer，并将其放在一个list里面即可：如https://github.com/PaddlePaddle/models/blob/develop/image_classification/train.py#L48 。
```python
loss1 = paddle.layer.cross_entropy_cost(
            input=out1, label=lbl, coeff=0.3)
        paddle.evaluator.classification_error(input=out1, label=lbl)
        loss2 = paddle.layer.cross_entropy_cost(
            input=out2, label=lbl, coeff=0.3)
        paddle.evaluator.classification_error(input=out2, label=lbl)
        extra_layers = [loss1, loss2]
...
# Create trainer
trainer = paddle.trainer.SGD(
        cost=cost,
        parameters=parameters,
        update_equation=optimizer,
        extra_layers=extra_layers)
```
- 当cost指定为一个list时，Paddle会对list里面的所有cost自动求和。
- 如果训练只需要关注其中一个loss的输出，就将其他的loss放在extra_layers里面。

多谢 @lcy-seso 提供了非常仔细的解答。

**Comment by ckarying** [comment]
谢谢回复。
不过还是有一个问题，
`
trainer = paddle.trainer.SGD(
        cost=cost,
        parameters=parameters,
        update_equation=optimizer,
        extra_layers=extra_layers)
`
那么计算gradient的cost是cost + extra_layers，还是只有extra_layers。换言之，cost需要也在extra_layers的list中吗？

**Comment by windy444** [comment]
@JiayiFeng 我也有上面同学的疑问

**Comment by JiayiFeng** [comment]
cost和extra_layer都用来放置网络的终端节点，区别是，cost里面的会产生梯度并反传，但extra_layers里面的不会。

**Comment by Yukizzz** [comment]
所以是这样配置才会对cost进行加和实现多目标，是吗？
```
loss1 = paddle.layer.cross_entropy_cost(
            input=out1, label=lbl, coeff=0.3)
paddle.evaluator.classification_error(input=out1, label=lbl)
loss2 = paddle.layer.cross_entropy_cost(
            input=out2, label=lbl, coeff=0.3)
paddle.evaluator.classification_error(input=out2, label=lbl)
extra_layers = [loss1, loss2]
...
# Create trainer
trainer = paddle.trainer.SGD(
        cost=extra_layers,
        parameters=parameters,
        update_equation=optimizer,
        extra_layers=extra_layers)
```
