### ISSUE TITLE
PaddleInference C++: too many time costed on EnableTensorRTEngine()

### ISSUE THREAD

**Issue by peanut1028** [PaddlePaddle/Paddle#41977]
### 请提出你的问题 Please ask your question

PaddlePaddle版本：2.2 C++inference预测库
CPU: i9
GPU: GeForce RTX3070
系统：win11
TensorRT：7.2.2.3
CUDA：11.1

问题：C++推理项目各功能正常运行。开tensorrt推理提速明显。但是在loadmodel enableTensorRTEngine()时普遍需要花费五到十分钟的时间，同一个模型每次运行就都会卡在loadmodel这里。想请问是否支持保存转化的TRT engine对象直接加载，或者有什么其他建议可以缩减这部分的time cost么？

**Comment by ShiningZhang** [comment]
可以使用TensorRT的序列化功能，在EnableTensorRtEngine时设置use_static=True，这样会在第一次运行后将TRT优化信息保存到磁盘，而后运行时直接加载。具体可参考：https://www.paddlepaddle.org.cn/inference/v2.2/api_reference/cxx_api_doc/Config/GPUConfig.html#tensorrt

**Comment by peanut1028** [comment]
> 感谢回复！我置为了true，但多次运行似乎没有变化。这个接口不需要另指定保存的磁盘位置吗/也不需要另外添加加载engine的代码吗？我想问除了置use_static=True，是否需要其他位置的修改？

**Comment by peanut1028** [comment]
> 可以使用TensorRT的序列化功能，在EnableTensorRtEngine时设置use_static=True，这样会在第一次运行后将TRT优化信息保存到磁盘，而后运行时直接加载。具体可参考：https://www.paddlepaddle.org.cn/inference/v2.2/api_reference/cxx_api_doc/Config/GPUConfig.html#tensorrt

感谢回复！
我置为true后，确实看到了保存下来的序列化文件。但是多次运行时，加载速度仅有一次有明显提升，其他时候依然耗时5 minutes+ 。
我想问，是否仅需要设置use_static=True，其他地方不必改动？是否有直接从序列化文件加载的接口呢？

**Comment by mingren8888** [comment]
遇见了一样的问题
