### ISSUE TITLE
【PFCC】新算子开发过程中C++层面调用已有api的方法以及如何debug算子注册的问题点？

### ISSUE THREAD

**Issue by jinyouzhi** [PaddlePaddle/Paddle#41979]
### 请提出你的问题 Please ask your question

1. 新算子开发中有需要在C++后端的kernel中调用库里已有的api，希望能给出方法或者范例。
- PFCC的Panel环节，飞桨的高工提及需要区分迁移到phi的新架构和未迁移的api
- 这里举一个需要调用phi算子的例子：[Hackathon2 No.20 Cummax](https://github.com/PaddlePaddle/Paddle/issues/40313) 希望调用scatter算子来实现，初步代码如下：
```cpp
#include "paddle/phi/kernels/cummax_grad_kernel.h"
#include "paddle/phi/backends/cpu/cpu_context.h"
#include "paddle/phi/core/kernel_registry.h"
#include "paddle/phi/kernels/funcs/scatter.h"

namespace phi {

template <typename T, typename Context>
void CumsumGradKernel(const Context& dev_ctx,
                      const DenseTensor& x,
                      const DenseTensor& indices,
                      const DenseTensor& out_grad,
                      DenseTensor* x_grad) {
  dev_ctx.template Alloc<T>(x_grad);
//  phi::ScatterKernel(dev_ctx, x, indices, out_grad, true, x_grad);
  phi::funcs::ScatterAssignAdd<T, int64_t>(dev_ctx, out_grad, indices, x_grad);
  
}
}  // namespace phi

PD_REGISTER_KERNEL(cummax_grad,
                   CPU,
                   ALL_LAYOUT,
                   phi::CumsumGradKernel,
                   float,
                   double,
                   int,
                   int64_t) {}
```
2. 调试算子时，遇到算子注册失败的问题，希望分享一些新算子开发中的debug经验。
- `RuntimeError: (NotFound) There are no kernels which are registered in the cummax operator.`
- 希望给出一些check的思路，比如先屏蔽反向部分？

**Comment by chenwhql** [comment]
1. 复用已有Kernel，include对应的kernel头文件即可，比如复用ScatterKernel，`#include "paddle/phi/kernels/scatter_kernel.h"`，复用时需要加模板，`ScatterKernel<T, Context>`
2. 这个报错是说cummax没注册，那这个实际注册了吗？cummax_kernel.cc等文件是如何实现的呢
