### ISSUE TITLE
RNN: High gpu memory usage for recurrent_group + simple_attention

### ISSUE THREAD

**Issue by byzhang** [PaddlePaddle/Paddle#420]
We observed significant more gpu memory usage when using recurrent_group + simple_attention as compared with the standard gru or lstm. 
@lyxm added some logging in https://github.com/lyxm/Paddle/commit/9ce03727c273542492d63db9bb16088153d1edc4 with some analysis on the logging results. It seems some gpu memory copied in mixed_layer may be eliminated. @emailweixu commented, "大概是在RecurrentGrsdientMachine里// connect in_links 那里修改，把rnn 每个frame和static input相连".
It's kind of a blocking issue to learn a meaningful sized model with long sequences. It's highly appreciated if you can triage this issue. 
cc @xliux

**Comment by luotao1** [comment]
We will have a look and reproduce it ASAP.

**Comment by byzhang** [comment]
thanks!

Thanks,
-B

**Comment by lcy-seso** [comment]
- RecurrentLayerGroup 中的Attention 模型确实会非常耗费内存，我大致解释一下内存消耗最大的地方有那些：

1. 计算attention 时，有一个源语言与目标语言叉乘的过程，涉及的Layer包括：expand_layer的输出，attention_vector（也就计算attention weights之前得到的隐层输出），weighted_encoder_vecotrs，也就是 scale layer的输出； 这三个层的内存消耗会是：源语言长度×目标语言长度×隐层大小。可以计算出，如果源语言和目标语言非常长是，仅仅这三个层，每个都会消耗非常大的内存（可以达到几G的量级）；
2. StaticInput 这里在内部实现时候，实际上会多出来一份内存拷贝。也就是这里将StaticInput指向的那个输入的内存复制了一份。这部分内存可以省掉，但需要修改源码，相对比较麻烦。
3. Paddle目前的内存分配策略是遇到长序列就扩容分配内存，随着训练的进行，最大的内存消耗会和源语言长度×目标语言长呈正比。

----
之前为了训练非常长的源语序列和目标语言序列，当整个LayerGroup中的layer一次前向计算完之后，把attention模型中最消耗内存的几个层内存释放掉，反向需要时重新计算。

**Comment by lcy-seso** [comment]
由于长时间未更新，我先关闭此issue，如果大家有新的信息请随时再次open 此issue。
