### ISSUE TITLE
MKLDNN activation 如何更好的与Paddle原有的activation 剥离开

### ISSUE THREAD

**Issue by tensor-tang** [PaddlePaddle/Paddle#4200]
现有Paddle的activation的实现主要放在`paddle/gserver/activations/ActivationFunction.cpp`

在ActivationFunction.cpp中使用了一个static的全局变量[gActivationRegistrar](https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/gserver/activations/ActivationFunction.cpp#L30)

每实现一个新的激活函数，会在这个变量中加入新的active type， [END_DEFINE_ACTIVATION(ACTIVATION_NAME)](https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/gserver/activations/ActivationFunction.cpp#L53)

这个变量会在静态函数[create](https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/gserver/activations/ActivationFunction.cpp#L458)函数中用于创建激活函数。

最终Layer.cpp中会调用这个静态函数[create](https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/gserver/layers/Layer.cpp#L98) 

现在的问题是，由于最终调用的是`activation_.reset(ActivationFunction::create(action_type));`

如果想要实现mkldnn的激活函数，并且不改变这个接口的话，就需要按照#4199 中加[宏定义的方式](https://github.com/PaddlePaddle/Paddle/pull/4199/commits/9d692e3bccc712dd6b9410c7e931ab37eb484435#diff-f8abd6637b6f0c0c6bc1036795c536d3R462)方式实现。

但是宏定义的方式并不推荐，大家有没有比较好的方式可以解决 @luotao1

**Comment by luotao1** [comment]
和 @Xreki 讨论后，先按照加宏定义的方式实现吧，不影响编译出一个非mkldnn的版本即可。这块正在重构，等重构完后可以方便地进行剥离。
