### ISSUE TITLE
build with VS2019 + windows 10, ERROR  MSB8066

### ISSUE THREAD

**Issue by SpaceView** [PaddlePaddle/Paddle#42002]
### 问题描述 Issue Description

I'm trying to build paddle inference c++ development version;  with cuda11.5 + cudnn8.3 + tensorrt8.4.0.6 + python3.8.12, and I got the following errors,

严重性	代码	说明	项目	路径	文件	行	禁止显示状态
错误	MSB8066	“E:\vPaddle\padev\dev\CMakeFiles\b802349b2821104e8980f75d0f052323\libiomp5md.dll.rule;E:\vPaddle\padev\dev\CMakeFiles\b802349b2821104e8980f75d0f052323\mkldnn.dll.rule;E:\vPaddle\padev\dev\CMakeFiles\d84096b87e79030487813b74da23da09\op_function_impl.h.rule;E:\vPaddle\padev\dev\CMakeFiles\993afb1fbb76b6969aa182aeecc21612\op_function_generator_cmd.rule”的自定义生成已退出，代码为 1。	op_function_generator_cmd	C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160	C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets	241	
错误	MSB8066	“E:\vPaddle\padev\dev\CMakeFiles\9289f437afcb5293a45310d0c83eddf2\core_avx.pyd.rule;E:\vPaddle\padev\dev\CMakeFiles\83b51f14ace9d788cd4d6cd9b3b6eccb\copy_paddle_pybind.rule”的自定义生成已退出，代码为 9009。	copy_paddle_pybind	C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160	C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets	241	
错误	MSB8066	“E:\vPaddle\padev\dev\CMakeFiles\30e4056dd74406704a084b8b92a53e32\libiomp5md.dll.rule;E:\vPaddle\padev\dev\CMakeFiles\30e4056dd74406704a084b8b92a53e32\mkldnn.dll.rule;E:\vPaddle\padev\dev\CMakeFiles\d67dd0e29268d28cc5f25c0b0d351067\eager_codegen.rule”的自定义生成已退出，代码为 9009。	eager_codegen	C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160	C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets	241	
错误	MSB8066	“E:\vPaddle\padev\dev\CMakeFiles\b802349b2821104e8980f75d0f052323\libiomp5md.dll.rule;E:\vPaddle\padev\dev\CMakeFiles\b802349b2821104e8980f75d0f052323\mkldnn.dll.rule;E:\vPaddle\padev\dev\CMakeFiles\d84096b87e79030487813b74da23da09\eager_op_function_impl.h.rule;E:\vPaddle\padev\dev\CMakeFiles\993afb1fbb76b6969aa182aeecc21612\eager_op_function_generator_cmd.rule”的自定义生成已退出，代码为 1。	eager_op_function_generator_cmd	C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160	C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets	241	

### 版本&环境信息 Version & Environment Information

Info is given above.

**Comment by zhwesky2010** [comment]
@SpaceView 请问是根据这个 https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/install/compile/windows-compile.html ，使用Ninja编译的吗
