### ISSUE TITLE
在tornado服务框架下使用paddleocr推理报错cudaErrorInitializationError 

### ISSUE THREAD

**Issue by hengshan123** [PaddlePaddle/Paddle#42016]
- 系统环境/System Environment：ubuntu 18.04  nvidia-docker 
- 版本号/Version：Paddle：2.2.1-gpu-cuda11.2-cudnn8  PaddleOCR： paddleocr==2.3.0.2

- 完整报错/Complete Error Message：
File "/app/modules/paddle_ocr.py", line 72, in process_single_image
    result = self.ocr.ocr(image, cls=True)
  File "/usr/local/lib/python3.7/dist-packages/paddleocr/paddleocr.py", line 379, in ocr
    dt_boxes, rec_res = self.__call__(img, cls)
  File "/usr/local/lib/python3.7/dist-packages/paddleocr/tools/infer/predict_system.py", line 60, in __call__
    dt_boxes, elapse = self.text_detector(img)
  File "/usr/local/lib/python3.7/dist-packages/paddleocr/tools/infer/predict_det.py", line 212, in __call__
    self.input_tensor.copy_from_cpu(img)
  File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/inference/wrapper.py", line 35, in tensor_copy_from_cpu
    self.copy_from_cpu_bind(data)
OSError: (External) CUDA error(3), initialization error.
  [Hint: 'cudaErrorInitializationError'. The API call failed because the CUDA driver and runtime could not be initialized. ] (at /paddle/paddle/fluid/platform/gpu_info.cc:284)

在docker里单独执行paddleocr没有异常，但是在tornado里执行ocr会报错，比较奇怪。

**Comment by iclementine** [comment]
我联系 paddle ocr 的同学回复一下。也可以直接在 paddle ocr repo 提问。

**Comment by tink2123** [comment]
在tornado里的paddle版本可能有误，可以验证cpu下能否正确运行，如果cpu能跑通的话可以再check下paddle安装版本。

**Comment by hengshan123** [comment]
cpu环境下正确运行，gpu上的paddle版本和cpu一样。又尝试了一下发现tornado单进程模式paddleocr运行正常，多进程报错。

**Comment by tink2123** [comment]
方便提供一个最小可复现单元吗？包括tornado环境信息

**Comment by xucncn** [comment]
借楼问一下，我在tornado用paddle inference也遇到了类似的cudaErrorInitializationErro问题，同样是单进程正常，多进程报错。

**Comment by Jeffrey98-AI** [comment]
> 方便提供一个最小可复现单元吗？包括tornado环境信息

你们也可以用paddle server来测试，只用一个检测模型就可以复现这个问题，模型使用inference 模式在GPU预测，不要转 server 模型，也会出现这个问题
`OSError: (External) CUDA error(3), initialization error. 
  [Hint: 'cudaErrorInitializationError'. The API call failed because the CUDA driver and runtime could not be initialized. ] (at /paddle/paddle/fluid/platform/gpu_info.cc:283)
`

**Comment by Costwen** [comment]
这个问题我在python 的celery多个进程同时加载一个模型的时候也遇到了

**Comment by Dimensionzw** [comment]
我使用seldon core部署paddleocr也出现了这个问题
`CUDA error(3), initialization error. \n  [Hint: 'cudaErrorInitializationError'. The API call failed because the CUDA driver and runtime could not be initialized.`
在CPU模式下运行是正常的，在GPU下出现了上述问题，paddlehub和paddleocr的predict_system都存在类似问题
