### ISSUE TITLE
Win10Pip安装PaddlePaddle-gpu 2.2.2+Cuda10.2+cuDNN 7.6.5+python3.7.9 ，Compiled with WITH_GPU, but no GPU found in runtime.You are using GPU version Paddle, but your CUDA device is not set properly. CPU device will be used by default.

### ISSUE THREAD

**Issue by 123456bfb** [PaddlePaddle/Paddle#42026]
### 问题描述 Issue Description

在本地运行paddlehub的pyramidbox_lite_mobile_mask使用GPU预测，进行人脸口罩检测，运行报错，说没有找到GPU，但CUDA安装正确，与NVIDIA 驱动器版本也符合，paddlepaddle-gpu验证安装成功，也设置了环境变量。网上找了各种办法都试过了。重装过Cuda和paddlepaddle还是不行，也尝试过conda安装也失败了。
有哪位大哥知道怎么解决吗？孩子卡在这个问题好几天了，觉都睡不着。
![image](https://user-images.githubusercontent.com/68626928/164176972-2c48d784-07bd-4d51-a1da-7ae6608f7d24.png)
![image](https://user-images.githubusercontent.com/68626928/164178823-abf06538-3993-4ef8-bb9d-6ace92305659.png)
![image](https://user-images.githubusercontent.com/68626928/164177965-771bc1cd-2943-4f7b-a3a5-2f0d55c40181.png)

1、确认cuda以及cudnn是安装成功
![image](https://user-images.githubusercontent.com/68626928/164171999-f65f1137-1d3f-4daa-990a-3a9956cdc04e.png)
2、检查cuda与NVIDIA 驱动器版本是符合
![image](https://user-images.githubusercontent.com/68626928/164173359-f2ae4279-fe68-4c7d-ad6f-5e5e13d82238.png)
![image](https://user-images.githubusercontent.com/68626928/164172123-f8d89885-f43b-4399-b67a-67f292540ff5.png)
![image](https://user-images.githubusercontent.com/68626928/164173451-1e022a9e-7221-4e43-9bc1-6b5cbc2790fd.png)
3、paddlepaddle-gpu验证安装成功
![image](https://user-images.githubusercontent.com/68626928/164172370-12dec094-ca2a-41c9-bea7-9396b23c1ca6.png)
4、环境变量
系统变量：
![image](https://user-images.githubusercontent.com/68626928/164173708-7153727d-7db3-4d17-a6ca-1f69003de92a.png)
path：
![image](https://user-images.githubusercontent.com/68626928/164173901-9b63c8cc-6f8b-45c9-8e8a-6349e124a1c0.png)
5、笔记本显卡：一个集显，一个Nvidia Geforce MX150
![image](https://user-images.githubusercontent.com/68626928/164175159-8ac2381e-b33c-47cf-8191-dae9b3fc870a.png)

### 版本&环境信息 Version & Environment Information

PaddlePaddle版本：PaddlePaddle-gpu 2.2.2
GPU：Nvidia Geforce MX150，CUDA10.2和CUDNN7.6.5
系统环境：windows10 64位
Python版本：3.7.9

**Comment by GT-ZhangAcer** [comment]
MX150显卡在深度学习方面支持的不好，不是很推荐折腾，即使可以使用该GPU也很难带动常见的深度学习模型训练。  
有条件的话可以换个能玩3A的GPU，那种的基本上不会在深度学习方面有什么问题。

**Comment by 123456bfb** [comment]
报错显示找不到GPU是什么问题，版本驱动这些都更新了。我这个只是简单的跑一下程序，想用GPU加速一下，因为CPU运行太慢了

**Comment by 123456bfb** [comment]
> MX150显卡在深度学习方面支持的不好，不是很推荐折腾，即使可以使用该GPU也很难带动常见的深度学习模型训练。 有条件的话可以换个能玩3A的GPU，那种的基本上不会在深度学习方面有什么问题。

报错显示找不到GPU是什么问题，版本驱动这些都更新了。我这个只是简单的跑一下程序，想用GPU加速一下，因为CPU运行太慢了

**Comment by 123456bfb** [comment]
> > MX150显卡在深度学习方面支持的不好，不是很推荐折腾，即使可以使用该GPU也很难带动常见的深度学习模型训练。 有条件的话可以换个能玩3A的GPU，那种的基本上不会在深度学习方面有什么问题。
> 
> 报错显示找不到GPU是什么问题，版本驱动这些都更新了。我这个只是简单的跑一下程序，想用GPU加速一下，因为CPU运行太慢了



> MX150显卡在深度学习方面支持的不好，不是很推荐折腾，即使可以使用该GPU也很难带动常见的深度学习模型训练。 有条件的话可以换个能玩3A的GPU，那种的基本上不会在深度学习方面有什么问题。

主要是耗了好几天在这里了，感觉就快要成功了，不想就这么放弃

**Comment by GT-ZhangAcer** [comment]
1. 这个卡以它的算力与显存资源的情况，未必有CPU跑得快。
2. MX系列的卡对深度学习支持不好而且有一定年头了，可以换个GTX1050以上的卡去尝试。

**Comment by 123456bfb** [comment]
> MX150显卡在深度学习方面支持的不好，不是很推荐折腾，即使可以使用该GPU也很难带动常见的深度学习模型训练。 有条件的话可以换个能玩3A的GPU，那种的基本上不会在深度学习方面有什么问题。

我现在环境变量指定的是GPU 1,它就会报错。但指定GPU 0集显时它又可以运行，但感觉集显GPU0也没怎么用上来

**Comment by GT-ZhangAcer** [comment]
集显不支持CUDA，故GPU0就是你的独显，index是默认按支持CUDA的设备排序的

**Comment by 123456bfb** [comment]
> 集显不支持CUDA，故GPU0就是你的独显

所以指定GPU 0的时候，用的还是CPU对吗

**Comment by iclementine** [comment]
看起来 cuda 是正常安装了的。paddle 也能正常在 gpu 上运行。

可以先尝试把 log 级别开高。

export GLOG_v=2

然后运行看看输出的 log 

你没有设定环境变量 `CUDA_VISIBLE_DEVICES` 之类的吧？

**Comment by iclementine** [comment]
你可以试试运行 

`paddle.device.cuda.device_count()` 看看输出是多少，这里表明了可用的 GPU 数，
然后可以运行一些简单的 code, 比如说用 `paddle.randn(p2, 3])` 创建一个 Tensor, 看看它的 device 是否在 GPU 上。
如果正常，那么可能是其他的问题。

**Comment by 123456bfb** [comment]
已解决，谢谢以上朋友！
