### ISSUE TITLE
希望官方吧ai studio的cuda版本提升一下，在本地能跑通，复制上传BML就会报各种错误

### ISSUE THREAD

**Issue by Wei-JL** [PaddlePaddle/Paddle#42052]
### bug描述 Describe the Bug

BML上的报错 日志
```
/home/aistudio/yolox_paddle
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/matplotlib/__init__.py:107: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
  from collections import MutableMapping
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/matplotlib/rcsetup.py:20: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
  from collections import Iterable, Mapping
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/matplotlib/colors.py:53: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
  from collections import Sized
W0420 20:35:21.704994  8622 device_context.cc:447] Please NOTE: device: 0, GPU Compute Capability: 7.0, Driver API Version: 11.0, Runtime API Version: 10.1
W0420 20:35:21.710289  8622 device_context.cc:465] device: 0, cuDNN Version: 7.6.
initialize network with normal astype
Load weights pretrain_models/pre.pdparams.
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/parallel.py:596: UserWarning: The program will return to single-card operation. Please check 1, whether you use spawn or fleetrun to start the program. 2, Whether it is a multi-card program. 3, Is the current environment multi-card.
  warnings.warn("The program will return to single-card operation. "
Start Train
Epoch 1/35:   0%|                         | 0/715 [00:00<?, ?it/s<class 'dict'>]/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/nn/layer/norm.py:653: UserWarning: When training, we now always track global mean and variance.
  "When training, we now always track global mean and variance.")
Epoch 1/35:  36%|██▌    | 257/715 [02:24<04:18,  1.77it/s, loss=10.2, lr=0.0003]
Traceback (most recent call last):
  File "train.py", line 208, in <module>
    epoch_step, epoch_step_val, gen, gen_val, end_epoch, Cuda)
  File "/home/aistudio/yolox_paddle/utils/utils_fit.py", line 39, in fit_one_epoch
    loss_value = yolo_loss(outputs, targets)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 917, in __call__
    return self._dygraph_call_func(*inputs, **kwargs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 907, in _dygraph_call_func
    outputs = self.forward(*inputs, **kwargs)
  File "/home/aistudio/yolox_paddle/nets/yolo_training.py", line 145, in forward
    return self.get_losses(x_shifts, y_shifts, expanded_strides, labels, paddle.concat(outputs, 1))
  File "/home/aistudio/yolox_paddle/nets/yolo_training.py", line 222, in get_losses
    expanded_strides, x_shifts, y_shifts,
  File "<decorator-gen-287>", line 2, in get_assignments
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/base.py", line 351, in _decorate_function
    return func(*args, **kwargs)
  File "/home/aistudio/yolox_paddle/nets/yolo_training.py", line 282, in get_assignments
    y_shifts, total_num_anchors, num_gt)
  File "/home/aistudio/yolox_paddle/nets/yolo_training.py", line 529, in get_in_boxes_info
    is_in_boxes.astype("int").gather(idx, axis=1).astype("bool").logical_and(
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/math_op_patch.py", line 106, in astype
    return _C_ops.cast(self, 'in_dtype', self.dtype, 'out_dtype', dtype)
ValueError: (InvalidArgument) element count should be greater than 0, but received value is: 0.
  [Hint: Expected element_count > 0, but received element_count:0 <= 0:0.] (at /paddle/paddle/fluid/platform/gpu_launch_config.h:68)
  [operator < cast > error]
```

### 其他补充信息 Additional Supplementary Information

在本地跑可以跑通  接近40多轮 没问题，放到BML上就不行了
代码我已经开源，https://aistudio.baidu.com/studio/project/partial/verify/3801194/f77f8745755c41c896c77961a7545637
大神我已经卡了4天多了，求解~  谢谢
![image](https://user-images.githubusercontent.com/71386288/164232374-67d6f8e7-c946-4439-984b-28adb0db6d79.png)

**Comment by Wei-JL** [comment]
你好~ 其实这个报错我知道原因是什么，`is_in_boxes.astype("int").gather(idx, axis=1).astype("bool").logical_and(.. `中的idx为0， idx是`idx = is_in_boxes_anchor.nonzero()` 也就是说is_in_boxes_anchor这个里面一个框都没有，所以报错了。就算我加判断idx长度为0不做.gather 后面的concat也会报错，主要如https://github.com/PaddlePaddle/Paddle/issues/41855 这个所说
```
 File "/home/aistudio/yolox_paddle/nets/yolo_training.py", line 529, in get_in_boxes_info
    is_in_boxes.astype("int").gather(idx, axis=1).astype("bool").logical_and(
```

**Comment by Wei-JL** [comment]
大佬我已经开源了，全部运行到train的时候就看见报错。 我不太明白为什么本地跑没问题，一样的数据，程序。版本paddle2.2.2  除了CUDA与cudnn版本不同
 我的win11本地是CUDA ：11.3--cudnn ：8.2.1 paddle2.2.2
BML是CUDA ：10.1--cudnn ：7.6  paddle2.2.2

https://aistudio.baidu.com/studio/project/partial/verify/3801194/f77f8745755c41c896c77961a7545637

![image](https://user-images.githubusercontent.com/71386288/164234006-7ccd9352-f6b2-4776-b16d-1cdd3a7f870b.png)

**Comment by iclementine** [comment]
从报错信息看起来是 cast op 里的元素个数是0

```
ValueError: (InvalidArgument) element count should be greater than 0, but received value is: 0.
  [Hint: Expected element_count > 0, but received element_count:0 <= 0:0.] (at /paddle/paddle/fluid/platform/gpu_launch_config.h:68)
  [operator < cast > error]
```

但是从你的描述来看，是因为运行结果导致没有一个框。所以 element 个数是 0。那么一个框也没有是一个可能出现的结果，和模型的训练结果有关？

**Comment by Wei-JL** [comment]
> 从报错信息看起来是 cast op 里的元素个数是0
> 
> ```
> ValueError: (InvalidArgument) element count should be greater than 0, but received value is: 0.
>   [Hint: Expected element_count > 0, but received element_count:0 <= 0:0.] (at /paddle/paddle/fluid/platform/gpu_launch_config.h:68)
>   [operator < cast > error]
> ```
> 
> 但是从你的描述来看，是因为运行结果导致没有一个框。所以 element 个数是 0。那么一个框也没有是一个可能出现的结果，和模型的训练结果有关？

对的,可是这个是在我训练的过程中，我也怀疑过本地是不是没出现过0框的存在，所以我试了40多轮，发现真的没有0的出现。而在BML上训练每次第一轮就有了

**Comment by Ligoml** [comment]
这个问题确实很奇怪，飞桨团队已经联系aistudio的研发在核查环境问题，同时分配了算力复现你的问题，需要再等一段时间哈~此外，YOLOX模型在第五期论文复现赛中已经实现，欢迎参考：https://github.com/GuoQuanhao/YOLOX-Paddle

**Comment by Wei-JL** [comment]
> 这个问题确实很奇怪，飞桨团队已经联系aistudio的研发在核查环境问题，同时分配了算力复现你的问题，需要再等一段时间哈~此外，YOLOX模型在第五期论文复现赛中已经实现，欢迎参考：https://github.com/GuoQuanhao/YOLOX-Paddle

谢谢， 我卡太久了。 我先参考复现成功的吧  谢谢大佬们了  麻烦了  为飞桨团队点赞

**Comment by iclementine** [comment]
我运行的结果是不确定的，会出现问题但是步骤不确定，有时能运行20步，有时能运行 60步以上，有时甚至能跑完一个 epoch 以上，感觉就是随机的，这种情况下，模型就是预测了 0 个框。

如果你希望了解是具体什么原因，可以把模型的随机性固定住（参数初始化，数据迭代，模型内的 dropout 等随机性操作），然后在不同环境下运行，在相同的位置处查看网络的中间变量计算结果是否一致。

**Comment by lxk767363331** [comment]
> > 这个问题确实很奇怪，飞桨团队已经联系aistudio的研发在核查环境问题，同时分配了算力复现你的问题，需要再等一段时间哈~此外，YOLOX模型在第五期论文复现赛中已经实现，欢迎参考：https://github.com/GuoQuanhao/YOLOX-Paddle
> 
> 谢谢， 我卡太久了。 我先参考复现成功的吧 谢谢大佬们了 麻烦了 为飞桨团队点赞

AI Studio 后续后 cuda 升级计划。但此问题无法判定为 cuda 或 AI Studio导致的，具体问题解决可以继续与下面的同学对接。

**Comment by lxk767363331** [comment]
AI Studio 后续有 cuda 升级计划。但此问题无法判定为 cuda 或 AI Studio导致的，具体问题解决可以继续与下面的同学对接。

**Comment by Wei-JL** [comment]
> AI Studio 后续有 cuda 升级计划。但此问题无法判定为 cuda 或 AI Studio导致的，具体问题解决可以继续与下面的同学对接。

谢谢~ 了解  因为我本机和BML上最明显的区别 就是CUDA和cudnn版本不同  当然这么说欠妥~  抱歉

**Comment by lxk767363331** [comment]
很高兴您对AI Studio 的支持。关于报错的问题，还是需要框架的同学跟您讨论解决方案，如您在排查问题时需要算力支持，可通过邮件联系我们。
***@***.***
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/Paddle"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年4月21日(星期四) 晚上7:33
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PaddlePaddle/Paddle] 希望官方吧ai studio的cuda版本提升一下，在本地能跑通，复制上传BML就会报各种错误 (Issue #42052)





  
AI Studio 后续有 cuda 升级计划。但此问题无法判定为 cuda 或 AI Studio导致的，具体问题解决可以继续与下面的同学对接。
  
谢谢~ 了解  因为我本机和BML上最明显的区别 就是CUDA和cudnn版本不同  当然这么说欠妥~  抱歉
