### ISSUE TITLE
paddlehub有多模型融合的接口吗？

### ISSUE THREAD

**Issue by GDUTHeZexi** [PaddlePaddle/Paddle#42094]
### 请提出你的问题 Please ask your question

单一模型的效果不够理想，我想使用多模型融合。请问paddlehub有多模型融合的接口吗？我没有找到相关的文档，所以来这里提问一下。

**Comment by KPatr1ck** [comment]
你好，目前PaddleHub里没有提供多模型融合的接口。
因为多模型融合是一个策略，而不是一个固化的操作，你可以通过投票/加权等方式去达到融合的效果。
