### ISSUE TITLE
报名

### ISSUE THREAD

**Issue by Dalaoyuan2020** [PaddlePaddle/Paddle#42096]
### 问题描述 Please describe your issue

【队名】：远少是也的团队

【序号】：飞桨特色模型挑战赛 3

【论文】：nnU-Net: Self-adapting Framework for 
U-Net-Based Medical Image Segmentation 

【状态】：提交

【repo链接】：https://github.com/PaddlePaddle/Paddle

**Comment by Ligoml** [comment]
报名需要在这里https://github.com/PaddlePaddle/Paddle/issues/41482 回复哦
