### ISSUE TITLE
[hackathon] GPU版本源码编译Unable to establish SSL connection出错

### ISSUE THREAD

**Issue by xiaoguoguo626807** [PaddlePaddle/Paddle#42112]
### 问题描述 Issue Description

报错信息：
Unable to establish SSL connection.
paddle/fluid/framework/new_executor/CMakeFiles/download_program.dir/build.make:57: recipe for target 'paddle/fluid/framework/new_executor/CMakeFiles/download_program' failed
make[2]: *** [paddle/fluid/framework/new_executor/CMakeFiles/download_program] Error 4
CMakeFiles/Makefile2:288074: recipe for target 'paddle/fluid/framework/new_executor/CMakeFiles/download_program.dir/all' failed
make[1]: *** [paddle/fluid/framework/new_executor/CMakeFiles/download_program.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....

尝试安装libssl解决：无效
apt-get update 
apt-get install openssl
apt-get install libssl-dev 

麻烦提示可能出错的原因

### 版本&环境信息 Version & Environment Information

docker :registry.baidubce.com/paddlepaddle/paddle:2.2.2-gpu-cuda11.2-cudnn8
机器：Tesla  P4  .CUDA version 11.4

**Comment by LDOUBLEV** [comment]
像是因为网络问题导致某些包下载失败，有代理就加上代理试试

**Comment by xiaoguoguo626807** [comment]
这个是下载github的包吗，之前加过github的，相关包可以clone

**Comment by LDOUBLEV** [comment]
编译的时候会自动下载一些依赖，然后编译这些依赖库
或者你看下最开始报错的地方是不是某个库下载失败了，可以尝试手动下载下来去编译

**Comment by xiaoguoguo626807** [comment]
> 像是因为网络问题导致某些包下载失败，有代理就加上代理试试

我我查看了一下文件，是连接不到这个地址，wget -nc https://paddle-ci.gz.bcebos.com/new_exec/lm_main_program ，但是在docker 外面是可以的，会不会是docker里缺什么

**Comment by LDOUBLEV** [comment]
在docker里试试下面的代理是否可以：
wget -nc https://paddle-ci.gz.bcebos.com/new_exec/lm_main_program --no-check-certificate

如果不行，大概确定是docker里网络访问不了bcebos.com，你是否有代理？尝试加上代理下载试试

**Comment by xiaoguoguo626807** [comment]
这个不管用，我没有代理，我发现docker外wget的地址是106.12.1.25，docker内是182.61.62.20，为什么会有这种差别呢

**Comment by xiaoguoguo626807** [comment]
除了代理还有别的方法配置网络吗

**Comment by LDOUBLEV** [comment]
试试在启动容器的时候加上--net=host 
```
Host：容器使用宿主机的网卡是IP端口，不会虚拟自己的网卡，也不会配置自己的IP；设置命令如下：
docker run --net=host
```

**Comment by xiaoguoguo626807** [comment]
> --net=host

我试着拷贝了下载后的文件到指定目录里，目前编译还没有报错，如果不行按您这个命令重启一个docker再运行，谢谢您的帮助！

**Comment by yang131313** [comment]
你好，现在Paddle已经有编译好的安装包了，请问你在什么任务场景下需要编译Paddle呀？比如是需要新增算子、还是需要修改飞桨源代码，或者有什么其他的用途呢？
