### ISSUE TITLE
请求给个learn to rank任务listwise方式 lambda_cost的使用示例

### ISSUE THREAD

**Issue by lisupro** [PaddlePaddle/Paddle#4211]
#查到https://github.com/PaddlePaddle/Paddle/blob/v0.10.0/paddle/gserver/layers/CostLayer.h  paddle已可以支持ltr任务listwise方式 LambdaCost 损失函数进行训练，哪位大神给否给个使用方法说明
@zhouxiao-coder

**Comment by zhouxiao-coder** [comment]
刚才看了下，paddlepaddle/models 这个repo下面有一个folder是专门针对ltr任务的，pairwise和listwise都有示例，你可以参考这里： https://github.com/PaddlePaddle/models/blob/develop/ltr/lambda_rank.py

如果有问题的话，欢迎reopen issue。
