### ISSUE TITLE
Compile Issue

### ISSUE THREAD

**Issue by SnowleopardXI** [PaddlePaddle/Paddle#42144]
### bug描述 Describe the Bug

Compile error on Raspberry pi 4b Ubuntu22.04

Logs :
[ 53%] Building CXX object CMakeFiles/libprotoc.dir/home/SEAdam/Documents/Paddle/build/third_party/protobuf/src/extern_protobuf/src/google/protobuf/compiler/java/java_helpers.cc.o
CMake Error at /home/SEAdam/Documents/Paddle/build/third_party/cryptopp/src/extern_cryptopp-stamp/extern_cryptopp-update-Release.cmake:49 (message):
  Command failed: 1

   '/usr/local/lib/python3.10/dist-packages/cmake/data/bin/cmake' '-P' '/home/SEAdam/Documents/Paddle/build/third_party/cryptopp/tmp/extern_cryptopp-gitupdate.cmake'

  See also

    /home/SEAdam/Documents/Paddle/build/third_party/cryptopp/src/extern_cryptopp-stamp/extern_cryptopp-update-*.log

make[2]: *** [CMakeFiles/extern_cryptopp.dir/build.make:128: third_party/cryptopp/src/extern_cryptopp-stamp/extern_cryptopp-update] Error 1
make[1]: *** [CMakeFiles/Makefile2:2660: CMakeFiles/extern_cryptopp.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 54%] Building CXX object CMakeFiles/libprotoc.dir/home/SEAdam/Documents/Paddle/build/third_party/protobuf/src/extern_protobuf/src/google/protobuf/compiler/java/java_lazy_message_field.cc.o
[ 55%] Building CXX object CMakeFiles/libprotoc.dir/home/SEAdam/Documents/Paddle/build/third_party/protobuf/src/extern_protobuf/src/google/protobuf/compiler/java/java_lazy_message_field_lite.cc.o
In file included from /usr/include/c++/11/set:60,
                 from /home/SEAdam/Documents/Paddle/build/third_party/protobuf/src/extern_protobuf/src/google/protobuf/compiler/java/java_file.cc:41:
/usr/include/c++/11/bits/stl_tree.h: In instantiation of ‘static const _Key& std::_Rb_tree<_Key, _Val, _KeyOfValue, _Compare, _Alloc>::_S_key(std::_Rb_tree<_Key, _Val, _KeyOfValue, _Compare, _Alloc>::_Const_Link_type) [with _Key = const google::protobuf::FieldDescriptor*; _Val = const google::protobuf::FieldDescriptor*; _KeyOfValue = std::_Identity<const google::protobuf::FieldDescriptor*>; _Compare = google::protobuf::compiler::java::{anonymous}::FieldDescriptorCompare; _Alloc = std::allocator<const google::protobuf::FieldDescriptor*>; std::_Rb_tree<_Key, _Val, _KeyOfValue, _Compare, _Alloc>::_Const_Link_type = const std::_Rb_tree_node<const google::protobuf::FieldDescriptor*>*]’:
/usr/include/c++/11/bits/stl_tree.h:2071:47:   required from ‘std::pair<std::_Rb_tree_node_base*, std::_Rb_tree_node_base*> std::_Rb_tree<_Key, _Val, _KeyOfValue, _Compare, _Alloc>::_M_get_insert_unique_pos(const key_type&) [with _Key = const google::protobuf::FieldDescriptor*; _Val = const google::protobuf::FieldDescriptor*; _KeyOfValue = std::_Identity<const google::protobuf::FieldDescriptor*>; _Compare = google::protobuf::compiler::java::{anonymous}::FieldDescriptorCompare; _Alloc = std::allocator<const google::protobuf::FieldDescriptor*>; std::_Rb_tree<_Key, _Val, _KeyOfValue, _Compare, _Alloc>::key_type = const google::protobuf::FieldDescriptor*]’
/usr/include/c++/11/bits/stl_tree.h:2124:4:   required from ‘std::pair<std::_Rb_tree_iterator<_Val>, bool> std::_Rb_tree<_Key, _Val, _KeyOfValue, _Compare, _Alloc>::_M_insert_unique(_Arg&&) [with _Arg = const google::protobuf::FieldDescriptor* const&; _Key = const google::protobuf::FieldDescriptor*; _Val = const google::protobuf::FieldDescriptor*; _KeyOfValue = std::_Identity<const google::protobuf::FieldDescriptor*>; _Compare = google::protobuf::compiler::java::{anonymous}::FieldDescriptorCompare; _Alloc = std::allocator<const google::protobuf::FieldDescriptor*>]’
/usr/include/c++/11/bits/stl_set.h:512:25:   required from ‘std::pair<typename std::_Rb_tree<_Key, _Key, std::_Identity<_Tp>, _Compare, typename __gnu_cxx::__alloc_traits<_Allocator>::rebind<_Key>::other>::const_iterator, bool> std::set<_Key, _Compare, _Alloc>::insert(const value_type&) [with _Key = const google::protobuf::FieldDescriptor*; _Compare = google::protobuf::compiler::java::{anonymous}::FieldDescriptorCompare; _Alloc = std::allocator<const google::protobuf::FieldDescriptor*>; typename std::_Rb_tree<_Key, _Key, std::_Identity<_Tp>, _Compare, typename __gnu_cxx::__alloc_traits<_Allocator>::rebind<_Key>::other>::const_iterator = std::_Rb_tree<const google::protobuf::FieldDescriptor*, const google::protobuf::FieldDescriptor*, std::_Identity<const google::protobuf::FieldDescriptor*>, google::protobuf::compiler::java::{anonymous}::FieldDescriptorCompare, std::allocator<const google::protobuf::FieldDescriptor*> >::const_iterator; typename __gnu_cxx::__alloc_traits<_Allocator>::rebind<_Key>::other = std::allocator<const google::protobuf::FieldDescriptor*>; typename __gnu_cxx::__alloc_traits<_Allocator>::rebind<_Key> = __gnu_cxx::__alloc_traits<std::allocator<const google::protobuf::FieldDescriptor*>, const google::protobuf::FieldDescriptor*>::rebind<const google::protobuf::FieldDescriptor*>; typename _Allocator::value_type = const google::protobuf::FieldDescriptor*; std::set<_Key, _Compare, _Alloc>::value_type = const google::protobuf::FieldDescriptor*]’
/home/SEAdam/Documents/Paddle/build/third_party/protobuf/src/extern_protobuf/src/google/protobuf/compiler/java/java_file.cc:97:54:   required from here
/usr/include/c++/11/bits/stl_tree.h:770:15: error: static assertion failed: comparison object must be invocable as const
  770 |               is_invocable_v<const _Compare&, const _Key&, const _Key&>,
      |               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/include/c++/11/bits/stl_tree.h:770:15: note: ‘std::is_invocable_v<const google::protobuf::compiler::java::{anonymous}::FieldDescriptorCompare&, const google::protobuf::FieldDescriptor* const&, const google::protobuf::FieldDescriptor* const&>’ evaluates to false
make[5]: *** [CMakeFiles/libprotoc.dir/build.make:636: CMakeFiles/libprotoc.dir/home/SEAdam/Documents/Paddle/build/third_party/protobuf/src/extern_protobuf/src/google/protobuf/compiler/java/java_file.cc.o] Error 1
make[5]: *** Waiting for unfinished jobs....
make[4]: *** [CMakeFiles/Makefile2:141: CMakeFiles/libprotoc.dir/all] Error 2
make[3]: *** [Makefile:136: all] Error 2
make[2]: *** [CMakeFiles/extern_protobuf.dir/build.make:86: third_party/protobuf/src/extern_protobuf-stamp/extern_protobuf-build] Error 2
make[1]: *** [CMakeFiles/Makefile2:2582: CMakeFiles/extern_protobuf.dir/all] Error 2
make: *** [Makefile:136: all] Error 2

**Comment by wangxicoding** [comment]
GCC的版本是多少，试下这个issue里的方法用gcc8，https://github.com/NVIDIA/TensorRT/issues/1783

**Comment by SnowleopardXI** [comment]
感谢,gcc8实测有效

**Comment by SnowleopardXI** [comment]
> 

ggcc 11,gcc8实测有效

**Comment by gsq7474741** [comment]
I found a solution.
In file build/third_party/protobuf/src/extern_protobuf/src/google/protobuf/compiler/java/java_file.cc:68
add ```const``` behind the operator like
```  bool operator ()(const FieldDescriptor* f1, const FieldDescriptor* f2){```
```  bool operator ()(const FieldDescriptor* f1, const FieldDescriptor* f2)const {```
it seems like a feature in cpp17

ref [C++ set容器重写比较运算符报错：static assertion failed: comparison object must be invocable as const](https://blog.csdn.net/shenzhenyancheng/article/details/125912622)
