### ISSUE TITLE
paddle2.0静态图，网络参数不优化

### ISSUE THREAD

**Issue by HarryUP-rhy** [PaddlePaddle/Paddle#42146]
### bug描述 Describe the Bug

paddle版本2.0
使用股票环境中的收盘价作为输入，利用LSTM网络产生交易动作(0,1)，在执行交易动作之后产生买卖
的收益(reward),再由reward来计算两次交易之间的微分夏普率。将微分夏普率当作目标函数去优化
LSTM网络。
``` python
import gym
import gym_anytrading
from gym_anytrading.envs import TradingEnv, ForexEnv,StocksEnv,Actions,Positions
from gym_anytrading.datasets import FOREX_EURUSD_1H_ASK,STOCKS_GOOGL
import matplotlib.pyplot as plt
import numpy as np
from copy import deepcopy
import warnings
with warnings.catch_warnings():
    warnings.filterwarnings("ignore",category=DeprecationWarning)
    import paddle.fluid as fluid
    import paddle
    import math
try:
    paddle.enable_static()
except:
    pass
WINDOWS_SIZE = 10
def doubleNet(ipt):
    # hidden = fluid.layers.fc(input=ipt,size=100*4,
    #                          #param_attr = ParamAttr(name='{}_fc1'.format(variable_field)),
    #                          bias_attr = ParamAttr(name='{}_fc1_b'.format(variable_field)))
    hidden = fluid.layers.fc(input=ipt, size=100 * 4)

    lstm_h, c= fluid.layers.dynamic_lstm(input=hidden,size=100*4,is_reverse=False)
    lstm_max = fluid.layers.sequence_pool(input=lstm_h, pool_type='max')
    lstm_max_tanh = fluid.layers.tanh(lstm_max)
    predict_act = fluid.layers.fc(input=lstm_max_tanh, size=2, act='softmax')
    return predict_act

obs = fluid.data(name='obs', shape=[None,1], dtype='float32', lod_level=1)
dsr = fluid.data(name='dsr', shape=[None,1], dtype='float32', lod_level=1)

hidden = fluid.layers.fc(input=obs, size=100 * 4)
lstm_h, c = fluid.layers.dynamic_lstm(input=hidden, size=100 * 4, is_reverse=False)
lstm_max = fluid.layers.sequence_pool(input=lstm_h, pool_type='max')
lstm_max_tanh = fluid.layers.tanh(lstm_max)
predict_act = fluid.layers.fc(input=lstm_max_tanh, size=2, act='softmax')

infer_act_program = fluid.default_main_program().clone(for_test = False)
# 定义损失函数
avg_cost = fluid.layers.reduce_mean(dsr)
optimizer = fluid.optimizer.AdamOptimizer(learning_rate=1e-3,
                               epsilon=1e-3)
opt = optimizer.minimize(avg_cost)

#创建CPU执行器
place = fluid.CPUPlace()
exe = fluid.Executor(place)
exe.run(fluid.default_startup_program())

feed_list = [obs]
feeder = fluid.DataFeeder(place=place,feed_list=feed_list)

feed_list2 = [obs,dsr]
feeder2 = fluid.DataFeeder(place=place, feed_list=feed_list2)

env = gym.make('stocks-v1',window_size = WINDOWS_SIZE)
env.reset()
get_close = np.array(env.df.loc[:,'Close']).astype('float32').reshape(-1,1)
#print('获取的收盘价的格式:',get_close.shape)

def Diff_SR(reward):#传入的参数是reward的list
    n = len(reward)
    _reward = reward[n-1]#reward列表中的最后一个值
    if n<=1:
        Dt = 0
        return Dt
    elif np.mean(reward[:n-1]) == 0:
        Dt = 0
        return Dt
    else:
        At_1 = np.mean(reward[:n-1])
        Bt_1 = np.var(reward[:n-1])
        _At = _reward - At_1
        _Bt = _reward * _reward - Bt_1
        Dt_fz = Bt_1 * _At - At_1 * _Bt / 2
        Dt_fm = math.pow(math.fabs(Bt_1 - At_1 * At_1), 3 / 2)
        Dt = Dt_fz / Dt_fm
        return Dt
    # At = At_1+ETA*(reward-At_1)
    # Bt = Bt_1+ETA*(reward*reward-Bt_1)
    return Dt
close = []
for i in range(len(get_close)-WINDOWS_SIZE):
    close.append(get_close[i:i+WINDOWS_SIZE])
close = np.array(close).astype('float32')
def my_train_reader():
    def reader():
        for temp in close:
            yield temp[:] ,
    return reader

def my_dsr_reader():
    def reader(x,y):
        for temp in x:
            yield temp ,y
    return reader

train_reader = paddle.batch(
    my_train_reader(),
    batch_size=20)

#训练200个episode
for episode_id in range(200):
    env.reset()
    reward_list = []
    act_list = []
    obs = my_train_reader()()
    for index, obs in enumerate(obs):

        dsr_list = []
        # 调用预测网络输出预测动作，一次输出一个动作
        x = []
        x.append(np.array(obs))
        act_prob = exe.run(program=infer_act_program,
                           feed=feeder.feed(x),
                           fetch_list=[predict_act])[0]
        act_list.append(act_prob)
        action = np.squeeze(act_prob, axis=0)
        action = np.argmax(action)
        #print(index, action)
        # 执行动作获取动作对应的reward
        _obs, reward, done, info = env.step(action)
        reward_list.append(reward)
        # 根据reward求出微分夏普率
        if np.mean(reward_list) == reward_list[-1]:
            dsr = -100
            dsr_list.append(dsr)
        else:
            dsr = Diff_SR(reward_list)
            dsr_list.append(dsr)

        dsr = np.array(dsr_list).astype('float32')
        dsr = np.expand_dims(dsr, axis=-1).astype('float32')
        data = my_dsr_reader()(obs, dsr)
        # 执行主程序训练
        exe.run(program=fluid.default_main_program(),
                feed=feeder2.feed(data))
    print('act_lsit:',act_list[0:5])
    print('episode ',episode_id,',total reward=',np.sum(reward_list))
```

输出信息：
'''
E:\RhyAnaconda\envs\paddle2.0\python.exe E:/LearnPad/learn_pad_pycharm/test_trading/test_422.py
act_lsit: [array([[0.58450395, 0.41549602]], dtype=float32), array([[0.5843861 , 0.41561386]], dtype=float32), array([[0.58628076, 0.4137192 ]], dtype=float32), array([[0.58795905, 0.41204092]], dtype=float32), array([[0.58707297, 0.41292706]], dtype=float32)]
episode  0 ,total reward= 0
act_lsit: [array([[0.58450395, 0.41549602]], dtype=float32), array([[0.5843861 , 0.41561386]], dtype=float32), array([[0.58628076, 0.4137192 ]], dtype=float32), array([[0.58795905, 0.41204092]], dtype=float32), array([[0.58707297, 0.41292706]], dtype=float32)]
episode  1 ,total reward= 0
act_lsit: [array([[0.58450395, 0.41549602]], dtype=float32), array([[0.5843861 , 0.41561386]], dtype=float32), array([[0.58628076, 0.4137192 ]], dtype=float32), array([[0.58795905, 0.41204092]], dtype=float32), array([[0.58707297, 0.41292706]], dtype=float32)]
episode  2 ,total reward= 0

进程已结束，退出代码为 -1
'''
输出的动作概率都是一样的，网络参数没有改变。

**Comment by wangxicoding** [comment]
<img width="566" alt="image" src="https://user-images.githubusercontent.com/10208305/164909372-99e5b8c0-8ccb-4c25-9431-8dccf195db3b.png">
loss函数写的有问题，没有用到predict_act，只用到了结果dsr

**Comment by RenHyz** [comment]
> <img alt="image" width="566" src="https://user-images.githubusercontent.com/10208305/164909372-99e5b8c0-8ccb-4c25-9431-8dccf195db3b.png">
> 
> loss函数写的有问题，没有用到predict_act，只用到了结果dsr

import gym
import gym_anytrading
from gym_anytrading.envs import TradingEnv, ForexEnv,StocksEnv,Actions,Positions
from gym_anytrading.datasets import FOREX_EURUSD_1H_ASK,STOCKS_GOOGL
import matplotlib.pyplot as plt
import numpy as np
from copy import deepcopy
import warnings
with warnings.catch_warnings():
    warnings.filterwarnings("ignore",category=DeprecationWarning)
    import paddle.fluid as fluid
    import paddle
    import math
    import os
os.environ["KMP_DUPLICATE_LIB_OK"] = "TRUE"
try:
    paddle.enable_static()
except:
    pass
WINDOWS_SIZE = 10
#获取交易收盘价数据
env = gym.make('stocks-v1',window_size = WINDOWS_SIZE)
env.reset()
get_close = np.array(env.df.loc[:,'Close']).astype('float32').reshape(-1,1)
close = []
for i in range(len(get_close)-WINDOWS_SIZE):
    close.append(get_close[i:i+WINDOWS_SIZE])
close = np.array(close).astype('float32')
def my_train_reader():
    def reader():
        for temp in close:
            yield temp[:] ,
    return reader
def my_dsr_reader():
    def reader(x):
        for temp in close:
            yield temp ,x
    return reader


def Diff_SR(reward):#传入的参数是reward的list
    n = len(reward)
    _reward = reward[n-1]#reward列表中的最后一个值
    if n<=1:
        Dt = 0
        return Dt
    elif np.mean(reward[:n-1]):
        Dt = 0
        return Dt
    else:
        At_1 = np.mean(reward[:n-1])
        Bt_1 = np.var(reward[:n-1])
        _At = _reward - At_1
        _Bt = _reward * _reward - Bt_1
        Dt_fz = Bt_1 * _At - At_1 * _Bt / 2
        Dt_fm = math.pow(math.fabs(Bt_1 - At_1 * At_1), 3 / 2)
        Dt = Dt_fz / Dt_fm
        return Dt
    # At = At_1+ETA*(reward-At_1)
    # Bt = Bt_1+ETA*(reward*reward-Bt_1)
    return Dt

#定义神经网络及输入输出
def doubleNet(ipt):
    hidden = fluid.layers.fc(input=ipt, size=100 * 4)
    lstm_h, c= fluid.layers.dynamic_lstm(input=hidden,size=100*4,is_reverse=False)
    lstm_max = fluid.layers.sequence_pool(input=lstm_h, pool_type='max')
    lstm_max_tanh = fluid.layers.tanh(lstm_max)
    predict_act = fluid.layers.fc(input=lstm_max_tanh, size=2, act='softmax')
    return predict_act

obs = fluid.data(name='obs', shape=[None,1], dtype='float32', lod_level=1)
dsr = fluid.data(name='dsr', shape=[None,1], dtype='float32', lod_level=1)
actionNet = doubleNet(obs)
infer_act_program = fluid.default_main_program().clone(for_test = False)

#构建损失函数
tensor_act = paddle.argmax(actionNet[0])
add_1 = paddle.ones_like(tensor_act)
tensor_act_1 = paddle.add(tensor_act,add_1).astype('float32')
cost = paddle.multiply(tensor_act_1,dsr).astype('float32')
print("Tensor's stop_gradient: ", cost.stop_gradient)#输出False，说明cost会计算并传播梯度
#dsr = np.array(Dt_list)
#fluid.layers.mean(传入变量)
avg_cost = paddle.mean(cost)
optimizer = fluid.optimizer.AdamOptimizer(learning_rate=1e-3,
                                          epsilon=1e-3)
opt = optimizer.minimize(avg_cost)
#创建CPU执行器
place = fluid.CPUPlace()
exe = fluid.Executor(place)
exe.run(fluid.default_startup_program())
feed_list = [obs]
feeder = fluid.DataFeeder(place=place,feed_list=feed_list)
feed_list2 = [obs,dsr]
feeder2 = fluid.DataFeeder(place=place, feed_list=feed_list2)

#输入收盘价输出所有的预测动作
def predict():
    obs = my_train_reader()()
    act_prob_list = []
    prob_list = []
    for index, obs in enumerate(obs):
        obs = np.array(obs)
        data = []
        data.append(obs)
        act_prob = exe.run(program=infer_act_program,
                           feed=feeder.feed(data),
                           fetch_list=[actionNet])[0]
        act = np.squeeze(act_prob)
        prob_list.append(act)
        action = np.argmax(act)
        act_prob_list.append(action)
    print(prob_list[0:5])
    return act_prob_list
def run_episode():
    reward_list = []
    dsr_list = []
    #获取预测动作
    act_list = predict()
    #执行动作
    for act_i in act_list:
        obs, reward, done, info = env.step(act_i)
        #当reward不等于0时计算微分夏普率
        if reward != 0 :
            reward_list.append(reward)
            Dt = Diff_SR(reward_list)
            dsr_list.append(Dt)
            dsr = np.array(Dt).astype('float32')
            dsr = np.expand_dims(dsr,axis=-1)
            data = my_dsr_reader()(dsr)
            exe.run(
                program=fluid.default_main_program(),
                feed=feeder2.feed(data)
            )
    return reward_list,dsr_list
for i in range(5):
    env.reset()
    reward_list, dsr_list = run_episode()
    print('episode',i,'total reward=%.5f'%np.sum(reward_list),'total dsr=%.5f'%np.sum(dsr_list))

在loss函数中加入predict_act之后还是一样不能优化，是什么问题呢？
输出结果：
E:\RhyAnaconda\envs\paddle2.2\python.exe E:/LearnPad/learn_pad_pycharm/test_trading/test_oneEXE.py
Tensor's stop_gradient:  False
[array([0.6579416 , 0.34205842], dtype=float32), array([0.6580735 , 0.34192654], dtype=float32), array([0.65913564, 0.34086433], dtype=float32), array([0.6601127, 0.3398873], dtype=float32), array([0.6596957, 0.3403043], dtype=float32)]
episode 0 total reward=0.00000 total dsr=0.00000
[array([0.6579416 , 0.34205842], dtype=float32), array([0.6580735 , 0.34192654], dtype=float32), array([0.65913564, 0.34086433], dtype=float32), array([0.6601127, 0.3398873], dtype=float32), array([0.6596957, 0.3403043], dtype=float32)]
episode 1 total reward=0.00000 total dsr=0.00000
[array([0.6579416 , 0.34205842], dtype=float32), array([0.6580735 , 0.34192654], dtype=float32), array([0.65913564, 0.34086433], dtype=float32), array([0.6601127, 0.3398873], dtype=float32), array([0.6596957, 0.3403043], dtype=float32)]
episode 2 total reward=0.00000 total dsr=0.00000
[array([0.6579416 , 0.34205842], dtype=float32), array([0.6580735 , 0.34192654], dtype=float32), array([0.65913564, 0.34086433], dtype=float32), array([0.6601127, 0.3398873], dtype=float32), array([0.6596957, 0.3403043], dtype=float32)]
episode 3 total reward=0.00000 total dsr=0.00000
[array([0.6579416 , 0.34205842], dtype=float32), array([0.6580735 , 0.34192654], dtype=float32), array([0.65913564, 0.34086433], dtype=float32), array([0.6601127, 0.3398873], dtype=float32), array([0.6596957, 0.3403043], dtype=float32)]
episode 4 total reward=0.00000 total dsr=0.00000

进程已结束，退出代码为 0

**Comment by HarryUP-rhy** [comment]
> <img alt="image" width="566" src="https://user-images.githubusercontent.com/10208305/164909372-99e5b8c0-8ccb-4c25-9431-8dccf195db3b.png">
> 
> loss函数写的有问题，没有用到predict_act，只用到了结果dsr
@wangxicoding 
`import gym
import gym_anytrading
from gym_anytrading.envs import TradingEnv, ForexEnv,StocksEnv,Actions,Positions
from gym_anytrading.datasets import FOREX_EURUSD_1H_ASK,STOCKS_GOOGL
import matplotlib.pyplot as plt
import numpy as np
from copy import deepcopy
import warnings
with warnings.catch_warnings():
warnings.filterwarnings("ignore",category=DeprecationWarning)
import paddle.fluid as fluid
import paddle
import math
import os
os.environ["KMP_DUPLICATE_LIB_OK"] = "TRUE"
try:
paddle.enable_static()
except:
pass
WINDOWS_SIZE = 10
#获取交易收盘价数据
env = gym.make('stocks-v1',window_size = WINDOWS_SIZE)
env.reset()
get_close = np.array(env.df.loc[:,'Close']).astype('float32').reshape(-1,1)
close = []
for i in range(len(get_close)-WINDOWS_SIZE):
close.append(get_close[i:i+WINDOWS_SIZE])
close = np.array(close).astype('float32')
def my_train_reader():
def reader():
for temp in close:
yield temp[:] ,
return reader
def my_dsr_reader():
def reader(x):
for temp in close:
yield temp ,x
return reader

def Diff_SR(reward):#传入的参数是reward的list
n = len(reward)
_reward = reward[n-1]#reward列表中的最后一个值
if n<=1:
Dt = 0
return Dt
elif np.mean(reward[:n-1]):
Dt = 0
return Dt
else:
At_1 = np.mean(reward[:n-1])
Bt_1 = np.var(reward[:n-1])
_At = _reward - At_1
_Bt = _reward * _reward - Bt_1
Dt_fz = Bt_1 * _At - At_1 * _Bt / 2
Dt_fm = math.pow(math.fabs(Bt_1 - At_1 * At_1), 3 / 2)
Dt = Dt_fz / Dt_fm
return Dt
# At = At_1+ETA*(reward-At_1)
# Bt = Bt_1+ETA*(reward*reward-Bt_1)
return Dt

#定义神经网络及输入输出
def doubleNet(ipt):
hidden = fluid.layers.fc(input=ipt, size=100 * 4)
lstm_h, c= fluid.layers.dynamic_lstm(input=hidden,size=100*4,is_reverse=False)
lstm_max = fluid.layers.sequence_pool(input=lstm_h, pool_type='max')
lstm_max_tanh = fluid.layers.tanh(lstm_max)
predict_act = fluid.layers.fc(input=lstm_max_tanh, size=2, act='softmax')
return predict_act

obs = fluid.data(name='obs', shape=[None,1], dtype='float32', lod_level=1)
dsr = fluid.data(name='dsr', shape=[None,1], dtype='float32', lod_level=1)
actionNet = doubleNet(obs)
infer_act_program = fluid.default_main_program().clone(for_test = False)

#构建损失函数
tensor_act = paddle.argmax(actionNet[0])
add_1 = paddle.ones_like(tensor_act)
tensor_act_1 = paddle.add(tensor_act,add_1).astype('float32')
cost = paddle.multiply(tensor_act_1,dsr).astype('float32')
print("Tensor's stop_gradient: ", cost.stop_gradient)#输出False，说明cost会计算并传播梯度
#dsr = np.array(Dt_list)
#fluid.layers.mean(传入变量)
avg_cost = paddle.mean(cost)
optimizer = fluid.optimizer.AdamOptimizer(learning_rate=1e-3,
epsilon=1e-3)
opt = optimizer.minimize(avg_cost)
#创建CPU执行器
place = fluid.CPUPlace()
exe = fluid.Executor(place)
exe.run(fluid.default_startup_program())
feed_list = [obs]
feeder = fluid.DataFeeder(place=place,feed_list=feed_list)
feed_list2 = [obs,dsr]
feeder2 = fluid.DataFeeder(place=place, feed_list=feed_list2)

#输入收盘价输出所有的预测动作
def predict():
obs = my_train_reader()()
act_prob_list = []
prob_list = []
for index, obs in enumerate(obs):
obs = np.array(obs)
data = []
data.append(obs)
act_prob = exe.run(program=infer_act_program,
feed=feeder.feed(data),
fetch_list=[actionNet])[0]
act = np.squeeze(act_prob)
prob_list.append(act)
action = np.argmax(act)
act_prob_list.append(action)
print(prob_list[0:5])
return act_prob_list
def run_episode():
reward_list = []
dsr_list = []
#获取预测动作
act_list = predict()
#执行动作
for act_i in act_list:
obs, reward, done, info = env.step(act_i)
#当reward不等于0时计算微分夏普率
if reward != 0 :
reward_list.append(reward)
Dt = Diff_SR(reward_list)
dsr_list.append(Dt)
dsr = np.array(Dt).astype('float32')
dsr = np.expand_dims(dsr,axis=-1)
data = my_dsr_reader()(dsr)
exe.run(
program=fluid.default_main_program(),
feed=feeder2.feed(data)
)
return reward_list,dsr_list
for i in range(5):
env.reset()
reward_list, dsr_list = run_episode()
print('episode',i,'total reward=%.5f'%np.sum(reward_list),'total dsr=%.5f'%np.sum(dsr_list))`

在loss函数中加入predict_act之后还是一样不能优化，是什么问题呢？
输出结果：
E:\RhyAnaconda\envs\paddle2.2\python.exe E:/LearnPad/learn_pad_pycharm/test_trading/test_oneEXE.py
Tensor's stop_gradient: False
[array([0.6579416 , 0.34205842], dtype=float32), array([0.6580735 , 0.34192654], dtype=float32), array([0.65913564, 0.34086433], dtype=float32), array([0.6601127, 0.3398873], dtype=float32), array([0.6596957, 0.3403043], dtype=float32)]
episode 0 total reward=0.00000 total dsr=0.00000
[array([0.6579416 , 0.34205842], dtype=float32), array([0.6580735 , 0.34192654], dtype=float32), array([0.65913564, 0.34086433], dtype=float32), array([0.6601127, 0.3398873], dtype=float32), array([0.6596957, 0.3403043], dtype=float32)]
episode 1 total reward=0.00000 total dsr=0.00000

**Comment by wangxicoding** [comment]
<img width="397" alt="image" src="https://user-images.githubusercontent.com/10208305/167536823-26071cc5-0683-4621-8ab8-14b140b4b6f9.png">

1. 跑的是预测网络，只有前向，不会进行梯度计算参数更新。训练时需要跑 fluid.default_main_program()
3. cost = paddle.multiply(tensor_act_1,dsr).astype('float32')，这个loss函数设计的感觉也不太合理，相乘的话，会导致tensor_act_1训练一直往0趋近。
4. 另外可以把代码排一下版吗，按照markdown的格式😂
