### ISSUE TITLE
help  about  Build PaddlePaddle production image

### ISSUE THREAD

**Issue by 447zyg** [PaddlePaddle/Paddle#4214]
I'm new at Paddle or AI
I want jion it
but ...
when Build PaddlePaddle production image
use 
docker run -v $(pwd):/paddle -e "WITH_GPU=OFF" -e "WITH_AVX=OFF" -e "WITH_TEST=ON" paddle:dev

I got the Error at 
```
[WARN]	Unable to checkout golang.org/x/net
[ERROR]	Update failed for golang.org/x/net: Cannot detect VCS
```
and
```
[WARN]	Unable to checkout google.golang.org/grpc
[ERROR]	Update failed for google.golang.org/grpc: Cannot detect VCS
[ERROR]	Failed to install: Cannot detect VCS
```

and final . 
```
[ 19%] Built target extern_mkldnn
make: *** [all] Error 2
Makefile:160: recipe for target 'all' failed
 build over..
``` 

I don't know how to slove...

I use command 
 go install google.golang.org/grpc
without return

and go env has no problem

(在制作PaddlePaddle生产镜像的第一步的时候。遇到了一些问题
我确认我的go的环境变量是没有问题的。并且因为墙的原因  我手动安装了google.golang.org/grpc 
但是仍然没有任何帮助。仍然提示我  
```
[WARN]	Unable to checkout golang.org/x/net
[ERROR]	Update failed for golang.org/x/net: Cannot detect VCS
```
and
```
[WARN]	Unable to checkout google.golang.org/grpc
[ERROR]	Update failed for google.golang.org/grpc: Cannot detect VCS
[ERROR]	Failed to install: Cannot detect VCS
```
我不知道该怎么处理了。谢谢！ )

**Comment by Xreki** [comment]
> [ 19%] Built target extern_mkldnn
make: *** [all] Error 2
Makefile:160: recipe for target 'all' failed
 build over..

可以贴下详细一点的编译错误信息吗？确定真正出错的地方。

**Comment by Yancey1989** [comment]
Hi @447zyg ，
制作开发环境镜像需要在golang.org下载Go的开发环境
制作生产环境镜像需要依赖Go的开发环境安装对应的Go依赖库

所以看你的报错是下载Go的依赖库报错了，还是墙的问题。。

**Comment by 447zyg** [comment]
@Xreki 
有时候会出现这样的错误   
Done processing /paddle/paddle/framework/attribute.h
Total errors found: 0
[ 22%] Built target attribute
Scanning dependencies of target op_info
[ 22%] Building CXX object paddle/framework/CMakeFiles/op_info.dir/op_info.cc.o
[ 22%] Linking CXX static library libop_info.a
cpplint: Checking source code style
Done processing op_info.cc
Done processing /paddle/paddle/framework/op_info.h
Total errors found: 0
[ 22%] Built target op_info
Scanning dependencies of target operator
[ 22%] Building CXX object paddle/framework/CMakeFiles/operator.dir/operator.cc.o
[ 22%] Linking CXX static library liboperator.a
cpplint: Checking source code style
Done processing operator.cc
Done processing /paddle/paddle/framework/operator.h
Total errors found: 0
[ 22%] Built target operator
Scanning dependencies of target grad_op_builder
[ 22%] Building CXX object paddle/framework/CMakeFiles/grad_op_builder.dir/grad_op_builder.cc.o
[ 22%] Linking CXX static library libgrad_op_builder.a
cpplint: Checking source code style
Done processing grad_op_builder.cc
Done processing /paddle/paddle/framework/grad_op_builder.h
Total errors found: 0
[ 22%] Built target grad_op_builder
Scanning dependencies of target op_registry
[ 23%] Building CXX object paddle/framework/CMakeFiles/op_registry.dir/op_registry.cc.o
[ 23%] Linking CXX static library libop_registry.a
cpplint: Checking source code style
Done processing op_registry.cc
Done processing /paddle/paddle/framework/op_registry.h
Total errors found: 0
[ 23%] Built target op_registry
[ERROR]	Failed to install: Cannot detect VCS
Cannot detect VCS
make[2]: *** [glide] Error 1
CMakeFiles/go_vendor.dir/build.make:60: recipe for target 'glide' failed
make[1]: *** [CMakeFiles/go_vendor.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
CMakeFiles/Makefile2:508: recipe for target 'CMakeFiles/go_vendor.dir/all' failed
就卡在这里了。。这个和我之前说的不太一样。。有时候是这个  有的时候是之前提到的。
我试着重现下。如果可以的话

**Comment by 447zyg** [comment]
@Yancey1989 
谢谢你。但是我的Go的开发环境没有问题 
应该是go的依赖库  出现了问题 但是我并不知道哪里出现了问题。
build中只有

[WARN]	Unable to checkout golang.org/x/net
[ERROR]	Update failed for golang.org/x/net: Cannot detect VCS
[WARN]	Unable to checkout google.golang.org/grpc
[ERROR]	Update failed for google.golang.org/grpc: Cannot detect VCS
[ERROR]	Failed to install: Cannot detect VCS
这2个地方 提示错误

**Comment by 447zyg** [comment]
@Xreki @Yancey1989   我需要把build过程全部贴出来吗

**Comment by 447zyg** [comment]
[log.txt](https://github.com/PaddlePaddle/Paddle/files/1316931/log.txt)

**Comment by 447zyg** [comment]
[log.txt](https://github.com/PaddlePaddle/Paddle/files/1317119/log.txt)

**Comment by 447zyg** [comment]
@Yancey1989 
好吧 我知道了。。虽然我设置了全局变量 
但是终端似乎并不能ping通google之类的。
我再试试 
谢谢两位

**Comment by Yancey1989** [comment]
用代理的话可以尝试下这个issue里的方法：https://github.com/Masterminds/glide/issues/449

**Comment by 447zyg** [comment]
@Yancey1989   似乎和代理没有什么关系。
当我使用curl ip.cn显示的ip来自美国或者日本的时候 
一样的错误  我现在把2次完整的log贴上来   
不胜感激。。
[log 2.txt](https://github.com/PaddlePaddle/Paddle/files/1319566/log.2.txt)
[log.txt](https://github.com/PaddlePaddle/Paddle/files/1319565/log.txt)

**Comment by 447zyg** [comment]
我找到了。在https://github.com/PaddlePaddle/Paddle/issues/2791
