### ISSUE TITLE
深度可分离卷积层的实现问题

### ISSUE THREAD

**Issue by crazyxiaoj** [PaddlePaddle/Paddle#42159]
### 请提出你的问题 Please ask your question

我在`paddle.nn.Conv2D`中找到一个参数：`groups`，我能使用类似于这样的语句达到keras中`SeparableConv2D`的效果吗？
```PY
Conv2D(128, 256, 3, padding='SAME', bias_attr=False, groups=128)
```

**Comment by wangxicoding** [comment]
我在paddle官网文档，以及PaddleClas中找到有相关的SeparableConv实现，你看下是否符合你这边的需求？
https://www.paddlepaddle.org.cn/documentation/docs/zh/practices/cv/image_segmentation.html#separableconv2d
https://github.com/PaddlePaddle/PaddleClas/blob/v2.3.1/ppcls/arch/backbone/model_zoo/xception.py#L60-L77

**Comment by crazyxiaoj** [comment]
> 我在paddle官网文档，以及PaddleClas中找到有相关的SeparableConv实现，你看下是否符合你这边的需求？ https://www.paddlepaddle.org.cn/documentation/docs/zh/practices/cv/image_segmentation.html#separableconv2d https://github.com/PaddlePaddle/PaddleClas/blob/v2.3.1/ppcls/arch/backbone/model_zoo/xception.py#L60-L77

非常感谢您！

**Comment by crazyxiaoj** [comment]
我注意到PaddleClas中使用了`ConvBN`层对`SeparableConv`进行实现，但是我查看了keras的源码，发现并没有出现归一化层

**Comment by littletomatodonkey** [comment]
SeparableConv的核心思想是depthwise和pointwise的结合，bn的话确保和参考代码对齐即可
