### ISSUE TITLE
Add bool type for paddle::framework::Attribute

### ISSUE THREAD

**Issue by qingqing01** [PaddlePaddle/Paddle#4215]
Even though we can use `int` type to express `bool` type. But if use `int` type, some checking code in operators is as follow:

```cpp
    PADDLE_ENFORCE(ctx.Attr<int>("is_training") == 0 ||
                   ctx.Attr<int>("is_training") == 1);
```

And the bool type attributes are used frequently in operators.  So, I think it's necessary to add bool type.

**Comment by reyoung** [comment]
I do not think we need that `PADDLE_ENFORCE` and `bool` as an attribute type.

It because `True` and `False` can be implicitly cast to `int`. Using `Attr<int>` will give the same user API to Python and C++.
