### ISSUE TITLE
paddle 性能问题与torch相比  残差层数支持不好。

### ISSUE THREAD

**Issue by studyplacefor** [PaddlePaddle/Paddle#42152]
### bug描述 Describe the Bug

小弟，想用paddle 复现 torch项目的复型。能够用paddle跑了，但是相较torch速度太慢了,达不到预期！ 不知是不是我漏了什么环境Flag 设置，或是我写的复现代码有大问题，然而我不知怎么查找这方面的问题了，特此提个issue.

先给个代码输出paddle: ---------------测试环境-----------------------------------------
  paddle 2.1
 torch_version 1.9.0
  cuda 10.2

Please NOTE: device: 0, GPU Compute Capability: 6.1,
Driver API Version: 11.1, Runtime API Version: 10.2
device: 0, cuDNN Version: 7.6.

![tp0](https://user-images.githubusercontent.com/50259160/164889334-bca854ae-e12b-4387-a303-0343bcac22bb.png)
![tp1](https://user-images.githubusercontent.com/50259160/164889368-7edc3f3b-7ae5-4e54-b9c0-5a4a9649bd52.png)

[testpd.py.txt      paddle](https://github.com/PaddlePaddle/Paddle/files/8546639/testpd.py.txt)
[testth.py.txt     torch](https://github.com/PaddlePaddle/Paddle/files/8546640/testth.py.txt)

**Comment by studyplacefor** [comment]
![tp0](https://user-images.githubusercontent.com/50259160/164889334-bca854ae-e12b-4387-a303-0343bcac22bb.png)
![tp1](https://user-images.githubusercontent.com/50259160/164889368-7edc3f3b-7ae5-4e54-b9c0-5a4a9649bd52.png)

**Comment by studyplacefor** [comment]
占坑

**Comment by wangxicoding** [comment]
什么型号的GPU，看模型以及性能数据，感觉应该是paddle动态图调度比较慢的原因，不过也可能是kernel没有优化好。
具体排查性能可以使用nvidia的nsys工具进行profile可视化的分析下性能瓶颈，可以参考下这个issue https://github.com/PaddlePaddle/Paddle/issues/36022
另外还有其它方法验证是否调度慢的原因，比如把模型大小调大，深度宽度都加大，这样GPU计算时间会增加，调度占比减少；比如可以使用静态图运行，减少python和c++相互切换的调度开销。
另外paddle这边也一直在优化动态图的调度开销，可以切换一下最新的版本看看是否有性能提升。近期可能会发布2.3版本，调度开销会减少很多。

**Comment by studyplacefor** [comment]
-----
多谢你的信息， 静态图我没有试过，想到静态图，要先定义好图再feed，头就痛！

-----------------------------------------------------------------------------------------
paddle 2.1
torch_version 1.9.0
cuda 10.2

Please NOTE: device: 0, GPU Compute Capability: 6.1,
Driver API Version: 11.1, Runtime API Version: 10.2
device: 0, cuDNN Version: 7.6.

        win10   
一块 **gtx1070ti**     
在conda 虚拟环境下跑的代码

我用kaggle  < paddle 2.2 cuda 11.0> GPU的p100跑过 

这两个复现代码,paddle 的训练耗时相比torch 是很多的.

我用aistudio V100 *16G   跑过 [testpd.py.txt paddle](https://github.com/PaddlePaddle/Paddle/files/8546639/testpd.py.txt)代码。
并且打开这些Flag ,
#paddle.set_flags({'FLAGS_conv_workspace_size_limit':1024})    
#paddle.set_flags({'FLAGS_fuse_parameter_memory_size':512})    
#paddle.set_flags({'FLAGS_fuse_parameter_groups_size': 1})     
似乎并没有提升。

**Comment by wangxicoding** [comment]
嗯静态图用起来是比动态图麻烦。。 p100、v100算力太高，你那小模型应该全是调度瓶颈。
#paddle.set_flags({'FLAGS_conv_workspace_size_limit':1024})  这个flag是用于cudnn卷积算法调优的，计算不是瓶颈下，基本不影响。https://www.paddlepaddle.org.cn/documentation/docs/zh/guides/flags/cudnn_cn.html#flags-conv-workspace-size-limit
#paddle.set_flags({'FLAGS_fuse_parameter_memory_size':512})
#paddle.set_flags({'FLAGS_fuse_parameter_groups_size': 1})
这两个是设置数据并行梯度聚合通信的fuse相关大小，和fuse个数用的，对于单卡训练没有影响。https://www.paddlepaddle.org.cn/documentation/docs/zh/guides/flags/memory_cn.html#flags-fuse-parameter-memory-size
https://www.paddlepaddle.org.cn/documentation/docs/zh/guides/flags/memory_cn.html#flags-fuse-parameter-groups-size

**Comment by studyplacefor** [comment]
虽然是有   瓶颈 ！  在面对16小时v100时，正向运算 ，loss 计算瓶颈相比torch差距  我还能接受！
但是  后向运算计算梯度，就是backward()   实在差太多了，不能接受啊！

nsys 的cpu与gpu时序图看不懂啊 |(前图是paddle 3step  后图是torch 3step)

![image](https://user-images.githubusercontent.com/50259160/164956311-980d0b80-ae25-4833-8f38-5bff2e6b3c48.png)
![image](https://user-images.githubusercontent.com/50259160/164956350-99ac0ef2-0420-4ffe-bc71-d186611ebd04.png)

似乎在 50-120 s这时段内， torch 用几个cpu-core切换上下文，而paddle就只有2个核切换！ 就在这时段paddle 占用gpu的密度很大，是不是理解有瓶颈？


那是不是换静态图  试试？

**Comment by studyplacefor** [comment]
report 文件太大了，上传不了

**Comment by wangxicoding** [comment]
<img width="961" alt="image" src="https://user-images.githubusercontent.com/10208305/164960891-d9b34bbe-ce0f-49a7-b3bd-ee262ece6c01.png">
看Processes里，CUDA HW里面是cuda kernel实际计算的timeline，下面是cuda api调度kernel的timeline。主要看kernel实际的执行时间，然后可以再结合调度看。

<img width="857" alt="image" src="https://user-images.githubusercontent.com/10208305/164961422-57947ba1-cf40-4d40-a0ec-85304fee1d7d.png">
一般一个step内应该很少有大段的gap，step与step间可能存在一些。

**Comment by studyplacefor** [comment]
![image](https://user-images.githubusercontent.com/50259160/164961813-d5e4b56c-5e6e-48fa-aa88-d05f62c45183.png)

我用 @to_static 动转静 测试了下，   对比如图！ 性能就比torch好了，  不知这样有什么深坑？

感谢百度的工作人员辛苦付出！ ^_^  @[wangxicoding](https://github.com/wangxicoding)

**Comment by wangxicoding** [comment]
动转静，如果网络里面没有非常复杂的控制语句或python端的自定义算子，应该不会有啥坑。当然最保险的方式还是直接写原生静态图

**Comment by studyplacefor** [comment]
@wangxicoding    paddle 是真的对残差层数 支持不好！ 无关**动静图写程式**！
昨天我用paddle.jit.to_static注解  动转静测试 时代码上把模型搞混了，所以得到了误导的结果！
今天改正了，重新测试。  
如图：
![th-pd](https://user-images.githubusercontent.com/50259160/164999951-51c83444-09c3-4bc7-9864-084796da18a3.png)

代码(参数选项 --rb    使能  是否加入RB 网络）：
[paddle 动图程式             python xtestpd.py     和     python xtestpd.py   --rb        ]

(https://github.com/PaddlePaddle/Paddle/files/8550665/xtestpd.py.txt)


[ paddle.jit_static程式       python xtestpd_dymic.py    和  python xtestpd_dymic.py      --rb   ]

(https://github.com/PaddlePaddle/Paddle/files/8550666/xtestpd_dymic.py.txt)


[                     paddle     静态图程式 python xtestpd_static .py 和  xtestpd_static .py     --rb   ]

(https://github.com/PaddlePaddle/Paddle/files/8550668/xtestpd_static.py.txt)

[                         torch程式   python xtestth .py  和  python  xtestth .py  --rb       ]

(https://github.com/PaddlePaddle/Paddle/files/8550669/xtestth.py.txt)


其中用  to_static 把代码转静态的话，
     python xtestpd_dymic.py           可以转换成功且能跑训练
     python xtestpd_dymic.py  --rb   可以转换成功且只能跑训练1epoch ,**但是第二轮会出错**。如图所示！

能向研发部提下这个问题吗，盼将来能改进，这模型是论文里用到的conditioned wannet 上抠出来的，它虽小但太慢了无法在paddle下跑啊！

**Comment by studyplacefor** [comment]
昨天，我在aistudio的 paddle 2.3.0rc  版本上，我用的是V100   GPU.测试了这几个程序。
可喜的是  性能达到了  Yes RB take **14.394443988800049 s        /100it**   ！且动转静也不报错了。 动态图 与 动转静 时间相当的。 静态图反而慢了1-1.5s/100it ,可能这个模型太小了，并不能说明什么的。


虽然比torch 的耗时差些，但是差距不大了！《我没有 v100 的torch测试环境就没有测试torch版的程式,kaggle 上p100  我也懒得测试了)   

到这里该close issue ! @Ligoml  @wanglun  @jzhang533   辛苦了！ ^_^

**Comment by qtz980805** [comment]
兄弟，还可以试着提升一下cudnn版本，会有惊喜哦
