### ISSUE TITLE
官方文档的感觉有点问题

### ISSUE THREAD

**Issue by leoaaaaa** [PaddlePaddle/Paddle#42157]
### 问题描述 Issue Description

我在ai sudio上找了个车号识别的项目怎么部署到liunx paddleServing？
我看官方安装文档 https://www.paddlepaddle.org.cn/tutorials/projectdetail/2538249
这个git clone https://hub.fastgit.org/PaddlePaddle/Serving -b v0.7.0 clone就出错，
不知道什么原因，有没有一个实例性的文档教我怎么具体操作部署 paddleServing？

### 版本&环境信息 Version & Environment Information

liunx部署paddleServing

**Comment by wangxicoding** [comment]
hub.fastgit应该是用于加速clone代码的。可以试下直接 git clone https://github.com/PaddlePaddle/Serving.git 行不行
