### ISSUE TITLE
pytorch_dispatcher like function for paddle ?

### ISSUE THREAD

**Issue by gglin001** [PaddlePaddle/Paddle#42156]
### 请提出你的问题 Please ask your question

请问 paddle 未来有 计划 开发 类似于 pytorch_dispatcher 类似的功能吗?

ref
https://pytorch.org/tutorials/advanced/extend_dispatcher.html
https://pytorch.org/tutorials/advanced/dispatcher.html
http://blog.ezyang.com/2020/09/lets-talk-about-the-pytorch-dispatcher/

**Comment by wangxicoding** [comment]
您好，感谢您这边的提问，我这边会和PM反馈，之后给您答复。另外想问下您这边使用dispatcher是背景需求是什么，自定义算子或者是添加第三方硬件，或者其它功能扩展？

**Comment by gglin001** [comment]
> 您好，感谢您这边的提问，我这边会和PM反馈，之后给您答复。另外想问下您这边使用dispatcher是背景需求是什么，自定义算子或者是添加第三方硬件，或者其它功能扩展？

感谢回复, 主要是考虑到第三方硬件.  我们在做 paddle 在 Graphcore IPU 上运行的支持, 我们希望能够更好的支持paddle 的 API,  如果 paddle 有类似于 dispatcher 的设计, 或许是一个很好的方向

**Comment by wangxicoding** [comment]
了解，目前paddle里面有一个自定义硬件的接入，另外我看paddle已经在接入IPU了。https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/dev_guides/custom_device_docs/index_cn.html
想要dispatcher类似设计主要还是因为目前paddle接入新硬件比较复杂，难以快速开发吧

**Comment by gglin001** [comment]
> 了解，目前paddle里面有一个自定义硬件的接入，另外我看paddle已经在接入IPU了。https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/dev_guides/custom_device_docs/index_cn.html 想要dispatcher类似设计主要还是因为目前paddle接入新硬件比较复杂，难以快速开发吧

好的, 我会看一下这个新的接口!

目前 paddle 接入 IPU 的设计是通过 rewrite program_desc 逐步 lower 到 ipu 的软件栈上, 对比 pytorch/tensorflow(XLA) 等框架接入第三方设备的方案, 很不灵活, 也很难和 paddle 的主体部分解耦合

**Comment by zhao-han** [comment]
我们看了一下Paddle新硬件注册的接口定义文档，主要包括两部分，新硬件runtime注册，和kernel注册。对Graphcore的IPU这种高度依赖JIT编译的后端，不太友好。希望能有类似于pytorch/xla中[lazytensor](https://arxiv.org/pdf/2102.13267.pdf)的设计。
