### ISSUE TITLE
paddlx

### ISSUE THREAD

**Issue by leoaaaaa** [PaddlePaddle/Paddle#42161]
### 请提出你的问题 Please ask your question

![image](https://user-images.githubusercontent.com/90248905/164912995-fb8c7e6a-5a68-4f1b-97ed-6d53351957ce.png)
我这么配置的预测模型地址，但是命令行说找不到model？
![image](https://user-images.githubusercontent.com/90248905/164913037-3fa4b5fb-4d43-441d-8698-ec6a90e3dfe2.png)
我配置的有什么问题吗

**Comment by wangxicoding** [comment]
看报错信息是inference_model目录下面没有`__model__`这个文件，你看下你目录下面有没有这个文件。

**Comment by leoaaaaa** [comment]
没有这个文件，我是用的你们的paddleX 客户端训练完直接生成的模型，但是没有这个文件
![image](https://user-images.githubusercontent.com/90248905/165299343-d210c13d-fc8b-451c-b758-bb7fbedf30b9.png)

**Comment by FlyingQianMM** [comment]
请问预测代码是使用的PaddleX >=2.0的吗？但报错信息提示应该使用的是1.x版本的预测代码。

看您是用GUI >=2.0训练出来的模型，请使用PaddleX >=2.0的预测代码。

**Comment by leoaaaaa** [comment]
paddlex >=2.0的预测代码是什么意思？？？我直接python predict.py 有问题？
![image](https://user-images.githubusercontent.com/90248905/165519354-9c4a806b-4b6a-4589-a06d-dca03f1cb9c2.png)

**Comment by leoaaaaa** [comment]
能回复一下吗 谢谢了

**Comment by FlyingQianMM** [comment]
- 未导出的模型加载预测参考文档：https://github.com/PaddlePaddle/PaddleX/blob/develop/docs/apis/prediction.md
- 已导出的模型推理推测，python参考：https://github.com/PaddlePaddle/PaddleX/blob/develop/docs/python_deploy.md
