### ISSUE TITLE
并发问题！！！！！！！！！

### ISSUE THREAD

**Issue by henuliulei** [PaddlePaddle/Paddle#42177]
### 请提出你的问题 Please ask your question

目前把模型推理放在一个接口里面进行调用，设置了多线程，可是实际调用的时候发现模型仍然是串行执行，是当前模型不支持多线程吗

**Comment by JZ-LIANG** [comment]
请提供复现当前问题的最小代码示例。 另外请详细描述你的多线程是指什么？ 大部分模型结构layer-layer 间是顺序执行的（resnet， transformer）这个模型本身因素决定了这行模型的layer(kernel) 也是必须顺序执行的。
