### ISSUE TITLE
ValueError: (InvalidArgument) Leaf Tensor (auto_492_) that doesn't stop gradient can't use inplace strategy.

### ISSUE THREAD

**Issue by yt605155624** [PaddlePaddle/Paddle#42190]
### 请提出你的问题 Please ask your question

ValueError: (InvalidArgument) Leaf Tensor (auto_492_) that doesn't stop gradient can't use inplace strategy.
  [Hint: Expected self->IsLeaf() && !self->OverridedStopGradient() == false, but received self->IsLeaf() && !self->OverridedStopGradient():1 != false:0.] (at /paddle/paddle/fluid/pybind/imperative.cc:791)

请问可能的原因是什么？

**Comment by JZ-LIANG** [comment]
paddle 框架中 叶子节点 如参数，如果是需要计算梯度的，不支持 inplace 操作，如 add_(xxx) 等。
如果你需要手动修改参数的值，可以将参数 设置成不需要梯度: p.stop_gradient = True， 并在 with no_grad 上下文里对 参数值做修改。 可以参考：https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/no_grad_cn.html#no-grad

**Comment by yt605155624** [comment]
谢谢，我这边也定位了问题，是 zeros_like() 对梯度的行为和 pytorch 的不一致，zeros_like pytorch 的梯度是断掉的，但是我们没有断
```python
import numpy as np
import paddle
import torch

input_np = np.array([[1,2,3],[4,5,6]]).astype("float32")
input_pd = paddle.to_tensor(input_np)
input_pd.stop_gradient = False
input_torch = torch.tensor(input_np)
input_torch.requires_grad = True
output_pd = paddle.zeros_like(input_pd)
output_torch = torch.zeros_like(input_torch)

# output_pd.stop_gradient: False
# output_torch.requires_grad: False
print("output_pd.stop_gradient:",output_pd.stop_gradient)
print("output_torch.requires_grad:",output_torch.requires_grad)
```
已经反馈给 api 负责人了

**Comment by shanqiu24** [comment]
> paddle 框架中 叶子节点 如参数，如果是需要计算梯度的，不支持 inplace 操作，如 add_(xxx) 等。 如果你需要手动修改参数的值，可以将参数 设置成不需要梯度: p.stop_gradient = True， 并在 with no_grad 上下文里对 参数值做修改。 可以参考：https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/no_grad_cn.html#no-grad



> paddle 框架中 叶子节点 如参数，如果是需要计算梯度的，不支持 inplace 操作，如 add_(xxx) 等。 如果你需要手动修改参数的值，可以将参数 设置成不需要梯度: p.stop_gradient = True， 并在 with no_grad 上下文里对 参数值做修改。 可以参考：https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/no_grad_cn.html#no-grad

在pytorch项目转为paddle的过程中，我也遇到同样的问题，无法解决，请求帮助呀~
