### ISSUE TITLE
paddle serving

### ISSUE THREAD

**Issue by leoaaaaa** [PaddlePaddle/Paddle#42206]
### 问题描述 Issue Description

根据官网文档部署paddle serving 后，另一个终端无法访问？
![image](https://user-images.githubusercontent.com/90248905/164983443-a37be7f5-ecd9-449c-9bd4-f013e3e928ce.png)
![image](https://user-images.githubusercontent.com/90248905/164983464-a53551d0-7d90-49fe-9e98-d7a0725b58f3.png)
根据官方文档如下操作：
https://www.paddlepaddle.org.cn/tutorials/projectdetail/2538249
![image](https://user-images.githubusercontent.com/90248905/164983525-ce75d77b-60a5-46af-958d-18f9acc7451e.png)

### 版本&环境信息 Version & Environment Information

![image](https://user-images.githubusercontent.com/90248905/164983553-85f51031-4cb2-49f0-a608-d5a8d73c5c8a.png)
gpu版本

**Comment by TeslaZhao** [comment]
您使用的环境是AI Studio？Docerker环境还是物理机？再另一个 Teminal 中是同一台机器的相同环境吗？

**Comment by leoaaaaa** [comment]
我是通过ssh远程在阿里云上面安装的docker环境，然后开了2个链接一个启动了服务，一个做调用。

**Comment by leoaaaaa** [comment]
能回复一下吗？谢谢
