### ISSUE TITLE
在反向传播时出现FatalError: `Segmentation fault` is detected by the operating system.

### ISSUE THREAD

**Issue by simonsLiang** [PaddlePaddle/Paddle#42229]
### 请提出你的问题 Please ask your question

在losses.backward()时出现
--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
0   paddle::imperative::BasicEngine::Execute()
1   paddle::imperative::PreparedOp::Run(paddle::imperative::NameVariableWrapperMap const&, paddle::imperative::NameVariableWrapperMap const&, paddle::framework::AttributeMap const&, paddle::framework::AttributeMap const&)
2   std::_Function_handler<void (paddle::framework::ExecutionContext const&), paddle::framework::OpKernelRegistrarFunctor<paddle::platform::CUDAPlace, false, 0ul, paddle::operators::ElementwiseMulDoubleGradKernel<paddle::platform::CUDADeviceContext, float>, paddle::operators::ElementwiseMulDoubleGradKernel<paddle::platform::CUDADeviceContext, double>, paddle::operators::ElementwiseMulDoubleGradKernel<paddle::platform::CUDADeviceContext, int>, paddle::operators::ElementwiseMulDoubleGradKernel<paddle::platform::CUDADeviceContext, long>, paddle::operators::ElementwiseMulDoubleGradKernel<paddle::platform::CUDADeviceContext, bool>, paddle::operators::ElementwiseMulDoubleGradKernel<paddle::platform::CUDADeviceContext, paddle::platform::float16>, paddle::operators::ElementwiseMulDoubleGradKernel<paddle::platform::CUDADeviceContext, paddle::platform::complex<float> >, paddle::operators::ElementwiseMulDoubleGradKernel<paddle::platform::CUDADeviceContext, paddle::platform::complex<double> > >::operator()(char const*, char const*, int) const::{lambda(paddle::framework::ExecutionContext const&)#1}>::_M_invoke(std::_Any_data const&, paddle::framework::ExecutionContext const&)
3   paddle::operators::ElementwiseMulDoubleGradKernel<paddle::platform::CUDADeviceContext, float>::Compute(paddle::framework::ExecutionContext const&) const
4   paddle::framework::product(paddle::framework::DDim const&)

----------------------
Error Message Summary:
----------------------
FatalError: `Segmentation fault` is detected by the operating system.
  [TimeInfo: *** Aborted at 1650865519 (unix time) try "date -d @1650865519" if you are using GNU date ***]
  [SignalInfo: *** SIGSEGV (@0x68) received by PID 5276 (TID 0x7f515373c700) from PID 104 ***]

这会是什么原因啊，基本一致的代码pytorch是能跑通的

**Comment by pangyoki** [comment]
你好，麻烦提供下可复现代码。报错看是ElementwiseMul这个kernel有问题。
