### ISSUE TITLE
No module named core_avx

### ISSUE THREAD

**Issue by zhYua** [PaddlePaddle/Paddle#42225]
### 问题描述 Issue Description

在docker的虚拟镜像中运行时，出现WARNING: AVX is supported on local machine, but you have installed paddlepaddle without avx core. Hence, no_avx core which has worse preformance will be imported.
You could reinstall paddlepaddle by 'python -m pip install -U paddlepaddle-gpu[==version]' or rebuild paddlepaddle WITH_AVX=ON to get better performance.
The original error is: No module named core_avx
Error: AVX is not support on your machine, but you have installed paddlepaddle with avx core, you should reinstall paddlepaddle by 'python -m pip install -U paddlepaddle-gpu[==version] -f https://paddlepaddle.org.cn/whl/stable_noavx.html'
请问该怎么解决

### 版本&环境信息 Version & Environment Information

paddlepaddle_gpu：paddlepaddle_gpu-2.0.0-cp27-cp27mu-manylinux1_x86_64.whl
cuda：11.0
os：centos
python：2.7

**Comment by pangyoki** [comment]
你好，你的安装命令是什么？报错信息有点矛盾，我理解你应该装的是avx的包，但是你的机器是noavx的。

建议你按paddle官网命令安装noavx包试试：
https://www.paddlepaddle.org.cn/install/quick?docurl=/documentation/docs/zh/install/pip/linux-pip.html

![图片](https://user-images.githubusercontent.com/26408901/165101992-7011441f-afc4-4483-977b-71e3a79c231d.png)
