### ISSUE TITLE
[论文复现问题]RMSProp优化器相关问题

### ISSUE THREAD

**Issue by Mr-SGXXX** [PaddlePaddle/Paddle#42234]
### Paddle的RMSProp和Torch的RMSProp有什么不一样吗

我使用Paddle的Momentum优化器和torch的SGD优化器对模型进行反向传播测试，能够实现对齐，但换成参考代码所使用的RMSProp优化器时，我的模型反向传播测试却无法对齐，请问可能是哪里存在问题呢

**Comment by pangyoki** [comment]
你好，请问查看的是哪里的参考代码呢？

**Comment by Mr-SGXXX** [comment]
参考代码是这个[Cream](https://github.com/microsoft/Cream)，他用的是RMSPropTF，我实验是想先试试两个都用RMSProp试试能不能对齐，结果出现这个问题

**Comment by Mr-SGXXX** [comment]
我刚才又实验用Adam优化器，发现两个模型都用Adam的时候也能对齐，只有用RMSProp的时候不行，所以我就怀疑会不会是优化器的问题，如果不是，什么因素可能导致这种情况
另外，通过在前向传播、反向传播的时候打印模型参数，我发现使用RMSProp时，在第一次反向传播并更新权值之后，BN层的weight和bias会出现偏差，部分BN层的bias会出现严重偏差

**Comment by pangyoki** [comment]
> 我刚才又实验用Adam优化器，发现两个模型都用Adam的时候也能对齐，只有用RMSProp的时候不行，所以我就怀疑会不会是优化器的问题，如果不是，什么因素可能导致这种情况 另外，通过在前向传播、反向传播的时候打印模型参数，我发现使用RMSProp时，在第一次反向传播并更新权值之后，BN层的weight和bias会出现偏差，部分BN层的bias会出现严重偏差

你好，感谢反馈。麻烦提供下最小可复现代码集。我找这个优化器的负责人帮忙看下。
包括描述中提到的“使用RMSProp时，在第一次反向传播并更新权值之后，BN层的weight和bias会出现偏差，部分BN层的bias会出现严重偏差”，麻烦提高下复现代码和数据。

**Comment by Mr-SGXXX** [comment]
你是指模型的组网部分吗，还有我该怎么发给你呢，总不能直接用回复发吧

**Comment by pangyoki** [comment]
> 你是指模型的组网部分吗，还有我该怎么发给你呢，总不能直接用回复发吧

可以提取出简单的可复现代码吗？只用把RMSProp的问题暴露出来就好。

**Comment by Mr-SGXXX** [comment]
[代码](https://github.com/PaddlePaddle/Paddle/files/8561681/test.zip)发出来了，在我的电脑上是可以暴露问题的

**Comment by Mr-SGXXX** [comment]
请问这个问题是否正在被解决呢

**Comment by Mr-SGXXX** [comment]
可以给个回复吗，我现在都不知道是我的代码错了还是Paddle的问题

**Comment by pangyoki** [comment]
你好，运行了一下你给的demo，按demo的输出，确实如你所说，Adam检查通过，RMSProp失败。我找RMSProp负责人看下原因。
