### ISSUE TITLE
采用precision_recall_evaluator()进行性能评估，输出的eval是否有错

### ISSUE THREAD

**Issue by dreamfantacy** [PaddlePaddle/Paddle#4223]
在gpu机器上运行sequence模型，采用的precision_recall_evaluator，其中输出的eval如下所示：
```bash
Test samples=346666 cost=0.121776 Eval: positive_label=-1 precision=1.2732e-313 recall=6.93541e-310 F1-score=1.19593e-316 macro-average-precision=0.900901 macro-average-recall=0.787111.....
```
precision和recall的值这么小，快逼近0了，但 macro-average-precision的值感觉也是合理的，这样的模型训练结果是否合理？

**Comment by Yancey1989** [comment]
根据
https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/gserver/evaluators/Evaluator.cpp#L824 ,看起来是没有设置`positive_label`引起的，日志里的`precision, recall `看起来是初始化内存时的默认值。麻烦贴下网络配置？

**Comment by dreamfantacy** [comment]
嗯，用的时候没有设置`positive_label`，一开始的网络配置是这样写的：
`cost = classification_cost(input=score, label=label, evaluator=precision_recall_evaluator)`
我是不是可以改成下面的配置语句：
`cost = classification_cost(input=score, label=label)
 evaluator=precision_recall_evaluator(input=score, label=label, postive_label=1)`

**Comment by typhoonzero** [comment]
Closing this outdated issue, feel free to reopen.
