### ISSUE TITLE
飞腾cup 麒麟系统 docker 下源码编译失败

### ISSUE THREAD

**Issue by lvweitao92** [PaddlePaddle/Paddle#42258]
### 请提出你的问题 Please ask your question

我看飞腾安装指南里说 python 是支持3.6 的，但是安装python 依赖的时候，安装paddle_bfloat==0.1.2  异常说是 python 需要 >=3.8 这是怎么回事
![H7RZD}C(7ME 2H)ZM8XU)A0](https://user-images.githubusercontent.com/104407428/165210800-c4e9e638-e1c5-48c2-8637-ab0f7ade1850.png)
![K4}0ZH6FXRFSP1F ( J{KT](https://user-images.githubusercontent.com/104407428/165210807-a1315b9c-cd38-4f7b-8c5b-fe1cc4932817.png)
还有我之前使用ubuntu20.04 来做源码编译的时候也一直失败，我看了一下我使用的gcc 是9.4 版本的，是不是只能使用8.2以下的gcc 
如果可能的话，有没有直接可用的飞腾的 docker 镜像，没有gpu

**Comment by adaxiadaxi** [comment]
官网上飞腾编译是在裸机环境下编译：https://www.paddlepaddle.org.cn/documentation/docs/zh/install/compile/arm-compile.html#anchor-0 。
当时需要的依赖版本：
1.cmake >= 3.16
2.git
3.python 2.7、3.5、3.6、 3.7（有任一版本的python即可）
4.OpenBlas（在无网环境下，需提前手动编译好适配运行设备的 blas 库，也可以直接调用运行设备上已有的高性能 blas）
5.protobuf
6.gcc >= 5.4

咱们现在还没有在飞腾环境下编译问题嘛？ @lvweitao92

**Comment by yang131313** [comment]
你好，现在Paddle已经有编译好的安装包了，请问你在什么任务场景下需要编译Paddle呀？比如是需要新增算子、还是需要修改飞桨源代码，或者有什么其他的用途呢？

**Comment by yang131313** [comment]
你好，现在Paddle已经有编译好的安装包了，请问你在什么任务场景下需要编译Paddle呀？比如是需要新增算子、还是需要修改飞桨源代码，或者有什么其他的用途呢？

**Comment by lvweitao92** [comment]
> 你好，现在Paddle已经有编译好的安装包了，请问你在什么任务场景下需要编译Paddle呀？比如是需要新增算子、还是需要修改飞桨源代码，或者有什么其他的用途呢？

有docker 的包了吗，在哪里，我这边主要是用PaddleOCR 做通用识别，然后做二次开发，优化准确率和对应的标签匹配
