### ISSUE TITLE
【论文复现赛】Paddle3D套件在哪

### ISSUE THREAD

**Issue by renmada** [PaddlePaddle/Paddle#42257]
### 请提出你的问题 Please ask your question

rt

**Comment by wanghuancoder** [comment]
你好，请看看这里是不是你要找的
https://github.com/PaddlePaddle/models/tree/develop/PaddleCV

**Comment by YixinKristy** [comment]
您好，目前飞桨3D视觉套件正在开发建设中，预计6月底会发布第一版本，支持单目、点云检测与分割，敬请期待~
目前支持的3D模型：
PointNet++：https://github.com/PaddlePaddle/models/blob/develop/PaddleCV/3d_vision/PointNet++
PointRCNN：https://github.com/PaddlePaddle/models/blob/develop/PaddleCV/3d_vision/PointRCNN
