### ISSUE TITLE
AIStudio脚本任务，双机四卡如何指定paddle.distributed.launch的ips参数

### ISSUE THREAD

**Issue by qtz980805** [PaddlePaddle/Paddle#42269]
### 请提出你的问题 Please ask your question

AIStudio脚本任务，双机四卡如何指定paddle.distributed.launch的ips参数？
不指定ips好像是两台机器自己跑自己的？
下面的log显示PADDLE_WORLD_DEVICE_IDS只有0,1
   +=======================================================================================+
    |                        Distributed Envs                      Value                    |
    +---------------------------------------------------------------------------------------+
    |                       PADDLE_TRAINER_ID                        0                      |
    |                 PADDLE_CURRENT_ENDPOINT                 127.0.0.1:39697               |
    |                     PADDLE_TRAINERS_NUM                        2                      |
    |                PADDLE_TRAINER_ENDPOINTS         127.0.0.1:39697,127.0.0.1:44601       |
    |                     PADDLE_RANK_IN_NODE                        0                      |
    |                 PADDLE_LOCAL_DEVICE_IDS                        0                      |
    |                 PADDLE_WORLD_DEVICE_IDS                       0,1                     |
    |                     FLAGS_selected_gpus                        0                      |
    |             FLAGS_selected_accelerators                        0                      |

**Comment by wanghuancoder** [comment]
请 @frankwhzhang 同学帮忙回答一下，感谢！

**Comment by frankwhzhang** [comment]
https://aistudio.baidu.com/aistudio/clusterprojectdetail/2326380/trainTask 可以参考这个示例

**Comment by qtz980805** [comment]
就是参考这个示例写的，但log显示
| Distributed Envs Value |
+---------------------------------------------------------------------------------------+
| PADDLE_TRAINER_ID 0 |
| PADDLE_CURRENT_ENDPOINT 127.0.0.1:39697 |
| PADDLE_TRAINERS_NUM 2 |
| PADDLE_TRAINER_ENDPOINTS 127.0.0.1:39697,127.0.0.1:44601 |
| PADDLE_RANK_IN_NODE 0 |
| PADDLE_LOCAL_DEVICE_IDS 0 |
| PADDLE_WORLD_DEVICE_IDS 0,1 |
| FLAGS_selected_gpus 0 |
| FLAGS_selected_accelerators 0 |

PADDLE_WORLD_DEVICE_IDS 0,1 说明只识别了自己机器上的两块卡，两台机器之间没有通信。

**Comment by xymyeah** [comment]
run.sh中只增加python -m paddle.distributed.launch --gpus="0,1" run.py 这样一句话就可以运行，不需要额外指定ips（aistudio会自动设置这个参数，因为实际的ip列表是动态分配的，额外指定该参数会有问题，请不要设置ips参数）

**Comment by qtz980805** [comment]
> run.sh中只增加python -m paddle.distributed.launch --gpus="0,1" run.py 这样一句话就可以运行，不需要额外指定ips（aistudio会自动设置这个参数，因为实际的ip列表是动态分配的，额外指定该参数会有问题，请不要设置ips参数）

我按照您说得的这样运行后，有两个问题想请教：
1. log中PADDLE_WORLD_DEVICE_IDS只显示0,1，但是按我的理解这个不应该是0,1,2,3（四块卡）吗？
2. 我使用distributedsampler加载数据，按道理在一个epoch内两台机器会平分数据集啊，但为什么两台机器分别加载了所有的数据呢？

期望得到您的回答（实在是因为找不到官方比较详细的文档了）

**Comment by xymyeah** [comment]
抱歉，平台问题，给您带来不便

**Comment by xymyeah** [comment]
sorry，给您带来了不便和困惑，经验证aistudio上是有些问题

可以先采用如下方法，先绕过去，稍后相关同学会修复该问题

在run.sh中按如下方式使用：

export PADDLE_TRAINERS=${VC_TRAINER_HOSTS}
export TRAINER_PORTS_NUM=1

python -m paddle.distributed.launch --gpus="0,1" run.py

**Comment by qtz980805** [comment]
好的辛苦了，谢谢~
