### ISSUE TITLE
[论文复现赛] 调用paddle.grad报错

### ISSUE THREAD

**Issue by simuler** [PaddlePaddle/Paddle#42262]
### bug描述 Describe the Bug

W0426 12:58:07.575986 13462 device_context.cc:447] Please NOTE: device: 0, GPU Compute Capability: 7.0, Driver API Version: 10.1, Runtime API Version: 10.1
W0426 12:58:07.581058 13462 device_context.cc:465] device: 0, cuDNN Version: 7.6.
Traceback (most recent call last):
  File "test.py", line 55, in <module>
    grad = paddle.grad(loss, fast_parameters, create_graph=False, allow_unused=True)
  File "<decorator-gen-45>", line 2, in grad
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
    return wrapped_func(*args, **kwargs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/framework.py", line 229, in __impl__
    return func(*args, **kwargs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/base.py", line 628, in grad
    retain_graph, allow_unused, only_inputs)
RuntimeError: (PermissionDenied) Reference count must be 0 when ready var auto_7_@GRAD is set
  [Hint: Expected ready_var.cur_ref_cnt == 0, but received ready_var.cur_ref_cnt:1 != 0:0.] (at /paddle/paddle/fluid/imperative/partial_grad_engine.cc:500)

最小可复现代码
“”“
import paddle
import paddle.nn.functional as F
import paddle.nn as nn

class WideAndDeepModel(nn.Layer):
    def __init__(self,num_output = 5,  num_expert = 8):
        super().__init__()   
        self.embed_output_dim = 896
        self.mlp_dims = [64]

        expert = []
        for i in range(num_expert):
            expert.append(nn.Linear(self.embed_output_dim,self.mlp_dims[-1]))
        self.mlp = nn.LayerList(expert)

        output_layer = []
        for i in range(num_output):
            output_layer.append(nn.Linear(self.mlp_dims[-1], 1))
        self.output_layer = nn.LayerList(output_layer)

      
    def forward(self, emb):

        fea = 0
        for i in range(len(self.mlp)):
            fea += self.mlp[i](paddle.reshape(emb,[-1,self.embed_output_dim]))
        
        result = 0
        for i in range(len(self.output_layer)):
            result += F.sigmoid(self.output_layer[i](fea))
        
        result = F.sigmoid(result)
        return result

if __name__=="__main__":
    num_output = 3
    num_expert = 1
    model = WideAndDeepModel(num_output, num_expert)

    fast_parameters = model.parameters()
    for weight in fast_parameters:
        weight.fast = None

    emb = paddle.rand(shape = [32,14,64])

    label = paddle.randint(1,2,shape=[32,1]).astype('float32')

    result = model(emb)

    criterion = paddle.nn.BCELoss()
    loss = criterion(result, label)

    model.clear_gradients()

    grad = paddle.grad(loss, fast_parameters, create_graph=False, allow_unused=True)
    print(grad)
”“”

### 其他补充信息 Additional Supplementary Information

当组网的参数num_output=2时，grad函数不会报错，num_output大于2时会报上述错误

**Comment by wanghuancoder** [comment]
非常感谢您的反馈，我们将复现并尽快解决该bug！

**Comment by wanghuancoder** [comment]
请负责同学 @wzzju 跟进一下该问题，感谢！

**Comment by wangzhen38** [comment]
选手接口用法不对，已私聊，issue关了就行

**Comment by Ren-Xin** [comment]
你好，我也遇到了相同问题，请问是哪里错了呢
