### ISSUE TITLE
Add Sequence Concat Operator.

### ISSUE THREAD

**Issue by Yancey1989** [PaddlePaddle/Paddle#4226]
## Case1
输入的Lod信息相同，Element的维度不同，按axis进行拼接
### 属性

`level = 1`:  按sentence进行拼接
`axis = 2`: 对输入的LodTensor按Level做Level Slice，对Level Slice后的Tensor按第`2`维进行拼接

### 输入

Input(x0),  Lod={{0,2,5,11},{0,2,3,5,6,8,11}}, element dims=<2,3,4>
```bash
3 (batch size = 3)     
1    2        3                 
2    1   2    1  2  3        
||   |   ||   |  || |||
```
- Tensor[0].dims = <2,2,3,4>
- Tensor[1].dims = <3,2,3,4>
- Tensor[2].dims = <6,2,3,4>

Input(x1), Lod={{0,2,5,11},{0,2,3,5,6,8,11}}, element dims=<2,2,4>
```bash
3 (batch size = 3)     
1    2        3                 
2    1   2    1  2  3        
||   |   ||   |  || |||
```
- Tensor[0].dims = <2,2,2,4>
- Tensor[1].dims = <3,2,2,4>
- Tensor[2].dims = <6,2,3,4>

### 输出

Output(Out), Lod={{0,2,5,11},{0,2,3,5,6,8,11}}, element dims=<2,5,4>
```bash
3 (batch size = 3)     
1    2        3                 
2    1   2    1  2  3        
||   |   ||   |  || |||
```
- Tensor[0].dims = <2,2,5,4>
- Tensor[1].dims = <3,2,5,4>
- Tensor[2].dims = <6,2,5,4>

## Case 2
Lod信息不同，Element的维度相同，拼接后输出的Lod信息**改变**

### 参数

`level=1`:按sentence拼接
`axis=0`: 对输入的LodTensor做Level Slice，对Level Slice后的Tensor按第**0**维进行拼接
### 输入

Input(x0),  Lod={{0,2,5,11},{0,2,3,5,6,8,11}}, element dims=<2,3,4>
```bash
3 (batch size = 3)     
1    2        3                 
2    1   2    1  2  3        
||   |   ||   |  || |||
```
- Tensor[0].dims = <2,2,3,4>
- Tensor[1].dims = <3,2,3,4>
- Tensor[2].dims = <5,2,3,4>

Input(x1),  Lod={{0,6,9,10},{0,1,3,6,7,9,10}}, element dims=<2,3,4>
```bash
3 (batch size = 3)     
3           2        1                 
1  2   3    1   2    1         
| ||   |||  |   ||   |
```
- Tensor[0].dims = <6,2,3,4>
- Tensor[1].dims = <3,2,3,4>
- Tensor[2].dims = <1,2,3,4>

### 输出

Output(Out), Lod={{0,8,14, 21},{0,2,3,5,8,9,11,12,14,15,17,20,21}}, element dims=<2,3,4>
```bash
3(batch size = 3)
4           4         4
2  1 2  3   1 2  1 2  1 2  3   1
|| | || ||| | || | || | || ||| |
```
- Tensor[0].dims = <8,2,3,4>
- Tensor[1].dims = <6,2,3,4>
- Tensor[2].dims = <7,2,3,4>

**Comment by qingqing01** [comment]
- 咱们规定下Level粒度的表示吧： 
   - level 0: 最小粒度 (char/word 级别)
   - 举例：2层(sentence, word)：level 0表示word级别，level 1表示sentence级别

**Comment by luotao1** [comment]
希望以后注释中能写明白是怎么concat的。只给个输入和输出，看不大明白计算过程。

```
* Input: two sequences each containing the same number of instances
 *        seq1 = [a1, a2, ..., an]
 *        seq2 = [b1, b2, ..., bn]
 * Output: a concatenated sequence of the two input sequences
 *        out = [a1, b1, a2, b2, ..., an, bn]
```
paddle原来的注释，虽然简陋，这里写的还是比较清楚的。

**Comment by Yancey1989** [comment]
Hi @lcy-seso ,之前Paddle的seqconcat layer也只支持单层的concat，是否有场景需要实现双层的支持呢？

**Comment by lcy-seso** [comment]
- concat 之前并没有支持过双层序列，但是由于重构之后数据结构统一，这个拼接的逻辑也可以非常方便的应用于双层。

大致总结与一下我关于 LoD Tensor的理解（可以帮我check）：
- 所有输入数据都以 Tensor 组织 。Tensor 的第0维总是 `batch_size`，因此 ，LoD 可以理解为是附加于第0维之上对整个输入Tensor的划分信息。
- 首先，按照LoD中的信息去做Slice，会从整个原始的Tensor中切出来一个小的Tensor；
---
- concat 的逻辑分为两种情况，也就是最初issue中提到的 case1 和 case2
    - 情况1.  对输入的Tnesor 沿 axis = 0 拼接（case2）
        - 这时需要重新计算 LoD 信息。
        - 等价于paddle 原有的 seq_concat_layer。
    - 情况2. 对输入的Tensor 沿 axis > 0 拼接 （case1）
        - 这时不需要重新计算LoD信息，但要求输入Tensor的LoD 信息必须完全一致。

- 不论是对 情况1（对应了case2）还是情况2（对应了 case1） ，拼接时都有一个要求必须满足：
    - 除了拼接指定的那个轴（ axis），输入Tensor 在这个轴上的维度（代码里面的dimension）可以不同，其它轴的维度都必须严格一致。
-  情况1 不改变输出 Tensor 各个轴上的维度（dimension）；
-  情况2 ：
    1. 会改变输出Tensor 在指定拼接轴上的维度，就等于要拼接的所有输入在拼接这个轴上维度之和；
    2. 不改变拼接轴之外各个轴的维度。
