### ISSUE TITLE
关于hdfs数据读取的时候，是否有重试机制

### ISSUE THREAD

**Issue by sddi** [PaddlePaddle/Paddle#42279]
### 请提出你的问题 Please ask your question

近期碰到一个问题，就是采用pipe的方式读取hdfs的数据，在并发度很大的时候，类似的hdfs dfs -text等命令会出错，导致任务失败。
看了下fs_open_internal 这个函数的代码，是调用里面的shell_popen的方法。

想问下，是否支持读取错误重试，而不是直接失败呢？

**Comment by Thunderbrook** [comment]
可以尝试使用SlotRecord，支持重试，使用方式如下：
dataset.set_feed_type("SlotRecordInMemoryDataFeed")
