### ISSUE TITLE
paddle 多线程预测异常

### ISSUE THREAD

**Issue by VamWolf** [PaddlePaddle/Paddle#4227]
如题，现在线上多线程，丢数据，只能单线程，性能堪忧.

**Comment by QiJune** [comment]
请详细描述问题背景，capi的多线程预测请参考https://github.com/PaddlePaddle/Paddle/tree/develop/paddle/capi/examples/model_inference/multi_thread

**Comment by VamWolf** [comment]
swig_paddle.initPaddle("--trainer_count=1") , 是这个参数，如果trainer_count 设置大于1 ，就会丢数据
