### ISSUE TITLE
编译paddle源码是报错

### ISSUE THREAD

**Issue by thomaslwang** [PaddlePaddle/Paddle#4229]
Done processing prelu_op.cc
/home/tom/workspace/paddle/paddle/operators/prelu_op.h:99:  Missing username in TODO; it should look like "// TODO(my_username): Stuff."  [readability/todo] [2]
Done processing /home/tom/workspace/paddle/paddle/operators/prelu_op.h
Total errors found: 1
make[2]: *** [paddle/operators/libprelu_op.a] Error 1
make[2]: *** Deleting file `paddle/operators/libprelu_op.a'
make[1]: *** [paddle/operators/CMakeFiles/prelu_op.dir/all] Error 2
make: *** [all] Error 2

编译系统：Ubuntu 14.04.3 amd64

**Comment by typhoonzero** [comment]
Please check out the latest code in develop branch and retry.

**Comment by luotao1** [comment]
Fixed by #4192
