### ISSUE TITLE
PaddleInferece上推理量化模型的速度问题. 

### ISSUE THREAD

**Issue by Water2style** [PaddlePaddle/Paddle#42303]
您好, 我在使用PPinfer推理模型, 计算推理时间的过程中,遇到一系列问题. 代码如下:

autolog.times.start()
input_handle.copy_from_cpu(img_np)   #CPU_TO_GPU 
autolog.times.stamp()

predictor.run()                                        #Inference 

autolog.times.stamp()
output_data = output_handle.copy_to_cpu()   #GPU_TO_CPU
autolog.times.end(stamp=True)

在上面测试了3段时间. 遇到如下问题:

1. 在带有INT8 ALU的桌面GPU上推理. 没有做量化的MobileNetV1的 GPU_TO_CPU时间是 0.4155 ms, 做了INT8量化后的GPU_TO_CPU时间是 0.0454. 其中为什么会存在10倍的差距? 换用ResNet50后， 发现优化的时间仍然是在GPU_TO_CPU这段. 增加batch_size后，增加的推理时间也是出现在GPU_TO_CPU这段.

2. 在NV的Jetson Nano上, 开启FP16模式推理MobileNetV1, 当BS=1时, 中间这段纯粹的 inference时间3ms左右,而FP32模式是2ms左右 . 但是GPU_TO_CPU这段时间是缩小了.

3.从上面两个问题看出， 真正的inferce时间段是否应该去计算  predictor.run()   加上 output_data = output_handle.copy_to_cpu() ?

谢谢!

**Comment by zhwesky2010** [comment]
@TeslaZhao 可以帮忙回答下这个推理问题吗

**Comment by liyancas** [comment]
同学你好，copy_from_cpu和predictor.run是异步执行（CPU调用GPU函数立即返回），因此统计的时间不代表相应的GPU计算已经完成，copy_to_cpu内部有同步操作，因此，统计Inference的执行时间应该从copy_from_cpu之前到copy_to_cpu之后。

**Comment by Water2style** [comment]
> 同学你好，copy_from_cpu和predictor.run是异步执行（CPU调用GPU函数立即返回），因此统计的时间不代表相应的GPU计算已经完成，copy_to_cpu内部有同步操作，因此，统计Inference的执行时间应该从copy_from_cpu之前到copy_to_cpu之后。

好的谢谢
