### ISSUE TITLE
paddle训练的时候，怎么设置一个初始化参数

### ISSUE THREAD

**Issue by lguowang** [PaddlePaddle/Paddle#42316]
### 请提出你的问题 Please ask your question

我们的目的是为了分析不同损失对机器学习的影响，想设定一个固定的初始化参数。如在“使用线性回归预测波士顿房价”案例中，我想对线性回归的参数做一个初始化，我应该如何设置？
能给我帖几段参数代码吗？

参考：
https://www.paddlepaddle.org.cn/documentation/docs/zh/practices/quick_start/linear_regression.html

**Comment by zhwesky2010** [comment]
@lguowang 使用 `paddle.nn.Linear(13, 1, weight_attr=paddle.nn.initializer.Uniform(-1, 1))`  来设置，这个 paddle.nn.initialzier 下面的目录都是初始化方式
 https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/nn/initializer/Uniform_cn.html#uniform
