### ISSUE TITLE
Newly added `desc` makes DenseTensor grow too big in volume

### ISSUE THREAD

**Issue by Aganlengzi** [PaddlePaddle/Paddle#42322]
DenseTensor grows big in volume because newly added `desc`(696+4 vs. 4) which needs to be optimized：
<img width="625" alt="image" src="https://user-images.githubusercontent.com/5997715/165473646-e7333058-d8d2-4b03-9899-c6f903771476.png">
<img width="418" alt="image" src="https://user-images.githubusercontent.com/5997715/165473594-3c8126e4-3d6f-4f73-afd6-9664af4ef666.png">

related：https://github.com/PaddlePaddle/Paddle/pull/41303

**Comment by zhwesky2010** [comment]
@Aganlengzi Is the question about optimizing `DenseTensor`  or what?

**Comment by Aganlengzi** [comment]
> @Aganlengzi Is the question about optimizing `denseTensor` or what?

@zhouwei25 hi，it is about `desc` in DenseTensor, I have added label `Intel` and @lidanqing-intel will follow up.

**Comment by lidanqing-vv** [comment]
@jakpiase Could you please consider change this to pointer ?

**Comment by lidanqing-vv** [comment]
@Aganlengzi Hi the memory comparison before and after is done here
https://github.com/PaddlePaddle/Paddle/pull/41303#issuecomment-1088070248

**Comment by lidanqing-vv** [comment]
Hi, @Aganlengzi this memory consumption comparison is only done on CPU and with MKLDNN and it showed not obvious memory increase, there will more benchmark follows, thanks.

**Comment by yaomichael** [comment]
the planned changes to keep up with ondDNN evolution are outline in https://github.com/PaddlePaddle/Paddle/issues/43525

**Comment by Aganlengzi** [comment]
@yaomichael , Thank you! I will close this issue since we will discuss a better way in https://github.com/PaddlePaddle/Paddle/issues/43525
