### ISSUE TITLE
 paddle-lwfx

### ISSUE THREAD

**Issue by sled100** [PaddlePaddle/Paddle#42323]
### 问题描述 Please describe your issue

【队名】：sled100

【序号】：31

【论文】：PSANet: Point-wise Spatial Attention Network for Scene Parsing

【状态】：报名

【repo链接】：https://github.com/sled100/PSANet_paddle

**Comment by TCChenlong** [comment]
你好，报名论文复现，请回复这个 ISSUE：https://github.com/PaddlePaddle/Paddle/issues/41482
