### ISSUE TITLE
[PFCC]clang-format 版本过低

### ISSUE THREAD

**Issue by gsq7474741** [PaddlePaddle/Paddle#42349]
### bug描述 Describe the Bug

在 [clang_format.hook](https://github.com/PaddlePaddle/Paddle/blob/develop/tools/codestyle/clang_format.hook)中

<img width="892" alt="image" src="https://user-images.githubusercontent.com/38883252/165687939-e2f1a97f-973f-4a4f-8942-1c16b46c20ac.png">

paddle使用的clang-format版本为3.8，但是实际在一些开发环境中很难找到3.8版本的，因为太旧了。希望paddle可以考虑更换版本，或设定版本大于多少。

**Comment by haozech** [comment]
您好，您的意见已收到，我们会尽快分析回复！

**Comment by gsq7474741** [comment]
> 您好，您的意见已收到，我们会尽快分析回复！

可能还需要对齐不同版本的clang-format，或者对所有代码重新format

**Comment by jzhang533** [comment]
duplicate: #42111

**Comment by gsq7474741** [comment]
> duplicate: #42111

ok
