### ISSUE TITLE
Out of memory error on GPU，然而可用内存足够 ！

### ISSUE THREAD

**Issue by 2050airobert** [PaddlePaddle/Paddle#42341]
### bug描述 Describe the Bug

Hi，
我这边按照文档跑picodet量化训练的时候遇到个奇怪的问题，不管我怎么修改batchsize总是说gpu内存不够，我是双卡，而且可用内存明显都是10GB以上，每个卡都是，而且跑其他的任务都很正常。我还更改 leos.environ[‘FLAGS_eager_delete_tensor_gb’] = “0.9” 都没什么用。具体log如下：
SystemError: (Fatal) Operator elementwise_add raises an paddle::memory::allocation::BadAlloc exception.
The exception content is
:ResourceExhaustedError:

Out of memory error on GPU 0. Cannot allocate 126.562744MB memory on GPU 0, 23.683105GB memory has been allocated and available memory is only 16.812500MB.

Please check whether there is any other process using GPU 0.

If yes, please stop them, or start PaddlePaddle on another GPU.
If no, please decrease the batch size of your model.
(at /paddle/paddle/fluid/memory/allocation/cuda_allocator.cc:79)
. (at /paddle/paddle/fluid/imperative/tracer.cc:221)

INFO 2022-04-28 02:08:11,083 launch_utils.py:320] terminate process group gid:13002
INFO 2022-04-28 02:08:15,086 launch_utils.py:341] terminate all the procs
ERROR 2022-04-28 02:08:15,086 launch_utils.py:602] ABORT!!! Out of all 2 trainers, the trainer process with rank=[1] was aborted. Please check its log.
INFO 2022-04-28 02:08:19,090 launch_utils.py:341] terminate all the procs
INFO 2022-04-28 02:08:19,090 launch.py:311] Local processes completed.
我理解是不是paddle训练的时候尤其是多gpu，需要独占gpu呢？实际上其他训练任务都可以同时跑几个模型呢。
我就是用的原始代码，按照你的指示，没有任何改动，除了上面提到的。
另外我的环境是 ubuntu20.04 gpu3090双卡，cuda11.4 我采用的paddle-gpu是paddle官方推荐的 ubuntu cuda11.2以上的那个最新的版本安装的。 其他的如下：
paddledet 2.4.0
paddlepaddle-gpu 2.2.2.post112
paddleslim 2.1.1

BR

**Comment by haozech** [comment]
Out of memory error on GPU 0. Cannot allocate 126.562744MB memory on GPU 0, 23.683105GB memory has been allocated and available memory is only 16.812500MB.
从报错信息上看是没法分配足够显存，建议先停掉其他占用显存的进程，用nvidia-smi确认下，然后再跑量化训练试试？

**Comment by 2050airobert** [comment]
hi，haozech

事实上并不是，你说的我都检查过了，而且上面我也提到过了 “”“我是双卡，而且可用内存明显都是10GB以上”
我的环境也写得清清楚楚
另外我的环境是 ubuntu20.04 gpu3090双卡，cuda11.4 我采用的paddle-gpu是paddle官方推荐的 ubuntu cuda11.2以上的那个最新的版本安装的。 其他的如下：
paddledet 2.4.0
paddlepaddle-gpu 2.2.2.post112
paddleslim 2.1.1
您是还需要什么其他的信息来辅助吗？ 麻烦您再帮忙看下呗？
备注：您有什么需要的跟我提就好，您说的这些我上面提到过了，没问题的。而且我相信paddle不可能强制要求独占gpu吧？
BR

**Comment by haozech** [comment]
> 

感谢回复，我没理解错的话，同样环境下用paddle跑其他模型训练都正常，只是picodet量化训练会报这个错，是么？能否提供下『按照文档跑picodet量化训练』这里说的文档链接

**Comment by 2050airobert** [comment]
1 请参考PaddleDetection中的demo进行量化训练：https://github.com/PaddlePaddle/PaddleDetection/tree/release/2.4/configs/slim
可以参考quant/picodet_s_416_lcnet_quant.yml 修改后跑tinypose的量化训练
2 当然如果您觉得paddle-gpu版本环境不一定出问题，您可以给我个链接 用一个最简单的，数据依赖比较少或者coco数据集的模型，而且最可靠很容易训练起来的参考链接给我下，我一步步看下行不行？ 您看行吗？

**Comment by haozech** [comment]
> 1 请参考PaddleDetection中的demo进行量化训练：https://github.com/PaddlePaddle/PaddleDetection/tree/release/2.4/configs/slim 可以参考quant/picodet_s_416_lcnet_quant.yml 修改后跑tinypose的量化训练 2 当然如果您觉得paddle-gpu版本环境不一定出问题，您可以给我个链接 用一个最简单的，数据依赖比较少或者coco数据集的模型，而且最可靠很容易训练起来的参考链接给我下，我一步步看下行不行？ 您看行吗？

目前首先需要定位下问题，要确认下在您的环境下运行其他训练任务是否报错（最简单的训练任务请参考https://www.paddlepaddle.org.cn/documentation/docs/zh/guides/02_paddle2.0_develop/01_quick_start_cn.html ） 如果报错，则证明应该是环境配置问题，如果不报错，则应该是这个PaddleDetection中的demo量化模型训练的问题，这样定位后方便我找对应的同学为您解决问题。

**Comment by 2050airobert** [comment]
hi，
如下图，环境是ok，gpu能训练起来，而且还有10多GB，batchsize那么小，足够啦！还是麻烦您帮忙看下，哪里的问题吧，多谢！
![image](https://user-images.githubusercontent.com/8407513/165792154-08fe76b1-2fd3-4bdb-a555-69600fa1b377.png)

**Comment by yghstill** [comment]
@2050airobert 确保GPU空闲时，将slim_config中batch_size调成1试下
https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.4/configs/slim/quant/picodet_s_416_lcnet_quant.yml#L13

**Comment by 2050airobert** [comment]
hi，
    我把batch_size设置为1之后，gpu确实训练起来了。我把batch_size设置为2的时候也可以，但是设置为24就崩了。。。
    感觉大概每个batch_size用了1GB的gpu内存。。。 这会不会太高了！！！
    如果我要开到64的话 那A100也不够啊。。。
    麻烦帮忙check下，这合理吗？是否还是哪里有问题，能帮忙查下吗？ 多谢

BR

**Comment by yghstill** [comment]
@2050airobert 经验证，picodet_s_416_lcnet的量化训练batch_size=48时占用大约20G显存。确认下空闲显存是否足够。

**Comment by 2050airobert** [comment]
tks，另外请问下 tinypose完整版本的量化，什么时候可以发布呢？下周几大概？

**Comment by 2050airobert** [comment]
Hi,
   1、 I run  the cmd "python tools/train.py -c configs/picodet/picodet_s_416_coco_lcnet.yml  --slim_config configs/slim/quant/picodet_s_416_lcnet_quant.yml" with gpu 3090,yet two days past the log was still like this as following.
![image](https://user-images.githubusercontent.com/8407513/168199579-e8c3ce42-ddd1-4794-aa51-c7f05f9e9f09.png)
   2 Is this all right ?  Any problem could you see? If any, please let me know ,tks
   3 Could you share with me 1000 to 5000 images of  tinypose training dataset at the web " https://github.com/PaddlePaddle/PaddleDetection/tree/release/2.3/configs/keypoint/tiny_pose. tks". If so ,please send a tar package to me ,tks  


BR

**Comment by 2050airobert** [comment]
hi，
1 这次我又尝试了下  最简单的训练任务请参考https://www.paddlepaddle.org.cn/documentation/docs/zh/guides/02_paddle2.0_develop/01_quick_start_cn.html  这个没有问题

2 但是跑 python tools/train.py -c configs/picodet/picodet_s_416_coco_lcnet.yml --slim_config configs/slim/quant/picodet_s_416_lcnet_quant.yml  with batchsize =1 还是有问题，具体log如下
![image](https://user-images.githubusercontent.com/8407513/168934266-8b95b38d-ada9-4068-8826-15b27a68587d.png)

3 跑  python  -m paddle.distributed.launch --selected_gpus='1,0'  -c configs/picodet/picodet_s_416_coco_lcnet.yml --slim_config configs/slim/quant/picodet_s_416_lcnet_quant.yml 会出现下面的log
![image](https://user-images.githubusercontent.com/8407513/168934578-a6d8017c-dd9f-42f3-a254-1eeee4f13a88.png)

麻烦帮忙看下，哪里的问题？ 多谢
BR

**Comment by 2050airobert** [comment]
hi，
按照您的指示https://github.com/PaddlePaddle/PaddleDetection/tree/release/2.4/configs/slim ，我已经在线训练量化好了一个生成文件  picodet_s_416_lcnet_quant ，只生成了这一个文件，应该是权重文件吧？ 是否可以直接加上扩展名pdigrams，但是还有一个对应的pdmodel 我就直接用原始的模型文件吧？
于是，使用这两个文件 进行opt 转换到paddle lite ，结果failed   [F 5/23 9:52:17.895 ...e-Lite/lite/model_parser/pb/tensor_io.cc:105 ForwardRead] The version of tensor 60097664 is not supported. 
![image](https://user-images.githubusercontent.com/8407513/169808284-cbb1eef5-192c-4199-86ba-c1185957489c.png)
能帮忙看下这个bug吗？

**Comment by jadehh** [comment]
最新的Paddle2.3只支持cuda11.2 ，在30系列的显卡上测试发现显存增加，速度也变慢

**Comment by wenziheng777** [comment]
我这边也有类似的问题，麻烦官方帮忙看下：

报错信息：
terminate called after throwing an instance of 'paddle::memory::allocation::BadAlloc'
  what():

--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
0   scale_ad_func(paddle::experimental::Tensor const&, paddle::experimental::ScalarBase<paddle::experimental::Tensor>, float, bool)
1   paddle::experimental::scale(paddle::experimental::Tensor const&, paddle::experimental::ScalarBase<paddle::experimental::Tensor> const&, float, bool)
2   void phi::ScaleKernel<float, phi::GPUContext>(phi::GPUContext const&, phi::DenseTensor const&, paddle::experimental::ScalarBase<phi::DenseTensor> const&, float, bool, phi::DenseTensor*)
3   float* phi::DeviceContext::Alloc<float>(phi::TensorBase*, unsigned long, bool) const
4   phi::DeviceContext::Impl::Alloc(phi::TensorBase*, phi::Place const&, paddle::experimental::DataType, unsigned long, bool) const
5   phi::DenseTensor::AllocateFrom(phi::Allocator*, paddle::experimental::DataType, unsigned long)
6   paddle::memory::allocation::StatAllocator::AllocateImpl(unsigned long)
7   paddle::memory::allocation::Allocator::Allocate(unsigned long)
8   paddle::memory::allocation::Allocator::Allocate(unsigned long)
9   paddle::memory::allocation::Allocator::Allocate(unsigned long)
10  paddle::memory::allocation::CUDAAllocator::AllocateImpl(unsigned long)
11  std::string phi::enforce::GetCompleteTraceBackString<std::string >(std::string&&, char const*, int)
12  phi::enforce::GetCurrentTraceBackString[abi:cxx11](bool)

----------------------
Error Message Summary:
----------------------
ResourceExhaustedError:

Out of memory error on GPU 0. Cannot allocate 3.164062GB memory on GPU 0, 9.309570GB memory has been allocated and available memory is only 1.451721GB.

Please check whether there is any other process using GPU 0.
1. If yes, please stop them, or start PaddlePaddle on another GPU.
2. If no, please decrease the batch size of your model.
If the above ways do not solve the out of memory problem, you can try to use CUDA managed memory. The command is `export FLAGS_use_cuda_managed_memory=false`.
 (at /paddle/paddle/fluid/memory/allocation/cuda_allocator.cc:95)

显卡信息（并没有被占用）：
nvidia-smi
Fri Mar 10 10:16:18 2023
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 520.61.05    Driver Version: 520.61.05    CUDA Version: 11.8     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ...  Off  | 00000000:1A:00.0 Off |                  N/A |
| 26%   37C    P0    46W / 250W |      0MiB / 11264MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   1  NVIDIA GeForce ...  Off  | 00000000:1B:00.0 Off |                  N/A |
| 25%   37C    P0    51W / 250W |      0MiB / 11264MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   2  NVIDIA GeForce ...  Off  | 00000000:3D:00.0 Off |                  N/A |
| 28%   34C    P0    53W / 250W |      0MiB / 11264MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   3  NVIDIA GeForce ...  Off  | 00000000:3E:00.0 Off |                  N/A |
| 28%   38C    P0    48W / 250W |      0MiB / 11264MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   4  NVIDIA GeForce ...  Off  | 00000000:88:00.0 Off |                  N/A |
| 30%   31C    P0    65W / 250W |      0MiB / 11264MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   5  NVIDIA GeForce ...  Off  | 00000000:89:00.0 Off |                  N/A |
| 24%   34C    P0    57W / 250W |      0MiB / 11264MiB |      1%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   6  NVIDIA GeForce ...  Off  | 00000000:B1:00.0 Off |                  N/A |
| 30%   34C    P0    63W / 250W |      0MiB / 11264MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   7  NVIDIA GeForce ...  Off  | 00000000:B2:00.0 Off |                  N/A |
| 35%   33C    P0    32W / 250W |      0MiB / 11264MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+


求解答

**Comment by wenziheng777** [comment]
> 
补充一下
这是直接运行官方文生图例子中遇到的问题，代码如下

import paddle
from ppdiffusers import StableDiffusionPipeline

pipe = StableDiffusionPipeline.from_pretrained("stabilityai/stable-diffusion-2")

paddle.seed(5232132133)
prompt = "a portrait of shiba inu with a red cap growing on its head. intricate. lifelike. soft light. sony a 7 r iv 5 5 mm. cinematic post - processing "
image = pipe(prompt, guidance_scale=7.5, height=768, width=768).images[0]

image.save("./outputs/shiba_dog_with_a_red_cap.png")
