### ISSUE TITLE
Fatal Python error: Segmentation fault ; python/lib/python2.7/site-packages/paddle/fluid/executor.py", line 894 in infer_from_dataset

### ISSUE THREAD

**Issue by haileewu** [PaddlePaddle/Paddle#42342]
### 问题描述 Additional Supplementary Information

train的时候完全没问题，infer的时候core掉
copy_program = main_program.clone()
pruned_program = copy_program._prune([],targets=target_vars)
inference_program = pruned_program._inference_optimize()
infer用的dataset没有问题，用同样dataset去train没有问题，只有在infer的时候core

**Comment by haozech** [comment]
你好，能否提供下paddle版本信息，硬件信息，最好能够有业务无关的可复现代码
