### ISSUE TITLE
大词表下，softmax op显存占用过高

### ISSUE THREAD

**Issue by cyk1337** [PaddlePaddle/Paddle#42346]
### 需求描述 Feature Description

任务目标：预训练语言模型; <br /> 需求场景：词表较大情况(250k+);  <br /> 功能描述 base模型的batch size无法开大。

**Comment by haozech** [comment]
您好，能详细描述下问题么？例如paddle版本，硬件信息，具体报错信息，最好再提供下业务无关的可复现代码
