### ISSUE TITLE
SIGABRT 训练时抛出SIGABRT任务

### ISSUE THREAD

**Issue by youan1** [PaddlePaddle/Paddle#4235]
RT, 在paddle训练时报错，错误日志如下，请paddle同学看看

20 22:15:07 2017[1,58]<stderr>:+ export PADDLE_TRAINER_ID=58
Wed Sep 20 22:15:07 2017[1,58]<stderr>:+ PADDLE_TRAINER_ID=58
Wed Sep 20 22:15:07 2017[1,58]<stderr>:+ export PADDLE_PSERVERS=10.86.100.34,10.86.100.21,10.86.100.23,10.86.100.25,10.86.100.26,10.86.100.27,10.86.100.28,10.86.100.29,10.86.100.30,10.86.100.31,10.86.100.32,10.86.100.33,10.86.100.19,10.86.100.35,10.86.100.36,10.86.100.38,10.86.100.39,10.86.100.41,10.86.100.42,10.86.100.43,10.86.101.11,10.86.101.20,10.86.101.22,10.86.101.24,10.86.101.25,10.86.101.29,10.86.101.32,10.86.101.33,10.86.101.37,10.86.101.43,10.86.102.12,10.86.102.13,10.86.102.14,10.86.102.15,10.86.102.16,10.86.102.17,10.86.102.18,10.86.102.20,10.86.102.21,10.86.102.22,10.86.102.23,10.86.102.24,10.86.102.26,10.86.102.27,10.86.102.29,10.86.102.30,10.86.102.33,10.86.102.36,10.86.102.39,10.86.102.43,10.86.103.14,10.86.103.15,10.86.103.16,10.86.103.17,10.86.103.18,10.86.103.19,10.86.103.21,10.86.103.23,10.86.103.24,10.86.103.25,10.86.103.27,10.86.103.30,10.86.103.31,10.86.103.32,10.86.103.34,10.86.103.35,10.86.103.36,10.86.103.37,10.86.103.38,10.86.103.39,10.86.103.40,10.86.103.41,10.86.103.42,10.86.103.43,10.86.104.11,10.86.104.12,10.86.104.13,10.86.104.14,10.86.104.15,10.86.104.18,10.86.104.19,10.86.104.20,10.86.104.21,10.86.104.22,10.86.104.23,10.86.104.25,10.86.104.26,10.86.104.28,10.86.104.30,10.86.104.31,10.86.104.32,10.86.104.33,10.86.104.35,10.86.104.36,10.86.104.37,10.86.104.39,10.86.104.40,10.86.104.42,10.86.104.43,10.86.105.11
Wed Sep 20 22:15:07 2017[1,58]<stderr>:+ PADDLE_PSERVERS=10.86.100.34,10.86.100.21,10.86.100.23,10.86.100.25,10.86.100.26,10.86.100.27,10.86.100.28,10.86.100.29,10.86.100.30,10.86.100.31,10.86.100.32,10.86.100.33,10.86.100.19,10.86.100.35,10.86.100.36,10.86.100.38,10.86.100.39,10.86.100.41,10.86.100.42,10.86.100.43,10.86.101.11,10.86.101.20,10.86.101.22,10.86.101.24,10.86.101.25,10.86.101.29,10.86.101.32,10.86.101.33,10.86.101.37,10.86.101.43,10.86.102.12,10.86.102.13,10.86.102.14,10.86.102.15,10.86.102.16,10.86.102.17,10.86.102.18,10.86.102.20,10.86.102.21,10.86.102.22,10.86.102.23,10.86.102.24,10.86.102.26,10.86.102.27,10.86.102.29,10.86.102.30,10.86.102.33,10.86.102.36,10.86.102.39,10.86.102.43,10.86.103.14,10.86.103.15,10.86.103.16,10.86.103.17,10.86.103.18,10.86.103.19,10.86.103.21,10.86.103.23,10.86.103.24,10.86.103.25,10.86.103.27,10.86.103.30,10.86.103.31,10.86.103.32,10.86.103.34,10.86.103.35,10.86.103.36,10.86.103.37,10.86.103.38,10.86.103.39,10.86.103.40,10.86.103.41,10.86.103.42,10.86.103.43,10.86.104.11,10.86.104.12,10.86.104.13,10.86.104.14,10.86.104.15,10.86.104.18,10.86.104.19,10.86.104.20,10.86.104.21,10.86.104.22,10.86.104.23,10.86.104.25,10.86.104.26,10.86.104.28,10.86.104.30,10.86.104.31,10.86.104.32,10.86.104.33,10.86.104.35,10.86.104.36,10.86.104.37,10.86.104.39,10.86.104.40,10.86.104.42,10.86.104.43,10.86.105.11
Wed Sep 20 22:15:07 2017[1,58]<stderr>:+ python27-gcc482/bin/python conf/trainer_config.conf
Wed Sep 20 22:18:46 2017[1,68]<stderr>:terminate called after throwing an instance of 'std::system_error'
Wed Sep 20 22:18:46 2017[1,68]<stderr>:  what():  Resource temporarily unavailable
Wed Sep 20 22:18:46 2017[1,68]<stderr>:*** Aborted at 1505917126 (unix time) try "date -d @1505917126" if you are using GNU date ***
Wed Sep 20 22:18:46 2017[1,68]<stderr>:PC: @                0x0 (unknown)
Wed Sep 20 22:18:46 2017[1,68]<stderr>:*** SIGABRT (@0x1fb0000ed16) received by PID 60694 (TID 0x7ffb49fc8700) from PID 60694; stack trace: ***
Wed Sep 20 22:18:46 2017[1,68]<stderr>:    @     0x7ffb49b9f160 (unknown)
Wed Sep 20 22:18:46 2017[1,68]<stderr>:    @     0x7ffb4910d3f7 __GI_raise
Wed Sep 20 22:18:46 2017[1,68]<stderr>:    @     0x7ffb4910e7d8 __GI_abort
Wed Sep 20 22:18:46 2017[1,68]<stderr>:    @     0x7ffb42766c65 __gnu_cxx::__verbose_terminate_handler()
Wed Sep 20 22:18:46 2017[1,68]<stderr>:    @     0x7ffb42764e06 __cxxabiv1::__terminate()
Wed Sep 20 22:18:46 2017[1,68]<stderr>:    @     0x7ffb42764e33 std::terminate()
Wed Sep 20 22:18:46 2017[1,68]<stderr>:    @     0x7ffb42765052 __cxa_throw
Wed Sep 20 22:18:46 2017[1,68]<stderr>:    @     0x7ffb427b6640 std::__throw_system_error()
Wed Sep 20 22:18:46 2017[1,68]<stderr>:    @     0x7ffb427b7ba8 std::thread::_M_start_thread()
Wed Sep 20 22:18:46 2017[1,68]<stderr>:    @     0x7ffb442e0bbf paddle::ParameterClient2::initThreads()
Wed Sep 20 22:18:46 2017[1,68]<stderr>:    @     0x7ffb442e1a5f paddle::ParameterClient2::init()
Wed Sep 20 22:18:46 2017[1,68]<stderr>:    @     0x7ffb43e6e09d paddle::RemoteParameterUpdater::init()
Wed Sep 20 22:18:46 2017[1,68]<stderr>:    @     0x7ffb437e11ea ParameterUpdater::init()
Wed Sep 20 22:18:46 2017[1,68]<stderr>:    @     0x7ffb4348af7b _wrap_ParameterUpdater_init
Wed Sep 20 22:18:46 2017[1,68]<stderr>:    @           0x4b4cb9 PyEval_EvalFrameEx
Wed Sep 20 22:18:46 2017[1,68]<stderr>:    @           0x4b6b28 PyEval_EvalCodeEx
Wed Sep 20 22:18:46 2017[1,68]<stderr>:    @           0x4b5d10 PyEval_EvalFrameEx
Wed Sep 20 22:18:46 2017[1,68]<stderr>:    @           0x4b6b28 PyEval_EvalCodeEx
Wed Sep 20 22:18:46 2017[1,68]<stderr>:    @           0x4b5d10 PyEval_EvalFrameEx
Wed Sep 20 22:18:46 2017[1,68]<stderr>:    @           0x4b6b28 PyEval_EvalCodeEx
Wed Sep 20 22:18:46 2017[1,68]<stderr>:    @           0x4b5d10 PyEval_EvalFrameEx
Wed Sep 20 22:18:46 2017[1,68]<stderr>:    @           0x4b6b28 PyEval_EvalCodeEx
Wed Sep 20 22:18:46 2017[1,68]<stderr>:    @           0x4b6c52 PyEval_EvalCode
Wed Sep 20 22:18:46 2017[1,68]<stderr>:    @           0x4e1c7d PyRun_FileExFlags
Wed Sep 20 22:18:46 2017[1,68]<stderr>:    @           0x4e3501 PyRun_SimpleFileExFlags
Wed Sep 20 22:18:46 2017[1,68]<stderr>:    @           0x4159dd Py_Main
Wed Sep 20 22:18:46 2017[1,68]<stderr>:    @     0x7ffb490f9bd5 __libc_start_main
Wed Sep 20 22:18:46 2017[1,68]<stderr>:    @           0x414b71 (unknown)
Wed Sep 20 22:18:46 2017[1,68]<stderr>:    @                0x0 (unknown)
Wed Sep 20 22:18:48 2017[1,68]<stderr>:./train.sh: line 239: 60694 Aborted                 python27-gcc482/bin/python conf/trainer_config.conf
Wed Sep 20 22:18:48 2017[1,68]<stderr>:+ '[' 134 -ne 0 ']'
Wed Sep 20 22:18:48 2017[1,68]<stderr>:+ kill_pserver2_exit
Wed Sep 20 22:18:48 2017[1,68]<stderr>:+ ps aux
Wed Sep 20 22:18:48 2017[1,68]<stderr>:+ grep paddle_pserver2
Wed Sep 20 22:18:48 2017[1,68]<stderr>:+ grep paddle_cluster_job
Wed Sep 20 22:18:48 2017[1,68]<stderr>:+ grep -v grep
Wed Sep 20 22:18:48 2017[1,68]<stderr>:+ cut -c10-14
Wed Sep 20 22:18:48 2017[1,68]<stderr>:+ xargs kill -9
Wed Sep 20 22:18:48 2017[1,68]<stderr>:+ log_fatal 'paddle_trainer failed kill paddle_pserver2 and exit'
Wed Sep 20 22:18:48 2017[1,68]<stderr>:+ echo '[./common.sh : 399] [kill_pserver2_exit]'
Wed Sep 20 22:18:48 2017[1,68]<stderr>:[./common.sh : 399] [kill_pserver2_exit]
Wed Sep 20 22:18:48 2017[1,68]<stderr>:+ echo '[FATAL]: paddle_trainer failed kill paddle_pserver2 and exit'
Wed Sep 20 22:18:48 2017[1,68]<stderr>:[FATAL]: paddle_trainer failed kill paddle_pserver2 and exit
Wed Sep 20 22:18:48 2017[1,68]<stderr>:+ get_stack
Wed Sep 20 22:18:48 2017[1,68]<stderr>:+ set +x

**Comment by youan1** [comment]
Wed Sep 20 23:55:19 2017[1,68]<stderr>:terminate called after throwing an instance of 'std::system_error'
Wed Sep 20 23:55:19 2017[1,68]<stderr>:  what():  Resource temporarily unavailable
Wed Sep 20 23:55:19 2017[1,68]<stderr>:
Wed Sep 20 23:55:19 2017[1,68]<stderr>:*** Aborted at 1505922919 (unix time) try "date -d @1505922919" if you are using GNU date ***
Wed Sep 20 23:55:19 2017[1,68]<stderr>:PC: @                0x0 (unknown)
Wed Sep 20 23:55:19 2017[1,68]<stderr>:*** SIGABRT (@0x1fb00005371) received by PID 21361 (TID 0x7fc457a4c700) from PID 21361; stack trace: ***
Wed Sep 20 23:55:19 2017[1,68]<stderr>:    @     0x7fc457623160 (unknown)

**Comment by youan1** [comment]
补充日志，看起来像资源不够了

**Comment by luotao1** [comment]
mpi集群是否独占，是取决于那个集群的配置。如果不是独占集群，由于机器共享，运行时有可能出现资源不够的情况。
