### ISSUE TITLE
paddle-lwfx

### ISSUE THREAD

**Issue by sled100** [PaddlePaddle/Paddle#42352]
### 问题描述 Please describe your issue

【队名】：sled100

【序号】：31

【论文】：PSANet: Point-wise Spatial Attention Network for Scene Parsing

【状态】：报名

【repo链接】：https://github.com/sled100/PSANet_paddle

**Comment by Ligoml** [comment]
报名在这里哈：https://github.com/PaddlePaddle/Paddle/issues/41482
