### ISSUE TITLE
aarch64源码编译paddle报错

### ISSUE THREAD

**Issue by BerryRB** [PaddlePaddle/Paddle#42358]
### 问题描述 Issue Description

在 https://hub.docker.com/r/paddlepaddle/paddle/tags?page=1&name=aarch docker镜像包中编译paddle，服务器架构为aarch64，编译部分log如下：

**
[ 95%] Built target final_dygraph_node
[ 95%] Built target final_dygraph_function
[ 95%] Built target parallel_ssa_graph_executor
[ 95%] Built target eager_reducer
[ 95%] Built target async_ssa_graph_executor
[ 95%] Built target parallel_executor
[ 95%] Built target executor_cache
[ 95%] Built target run_program_op
[ 95%] Built target paddle_inference_io
[ 95%] Built target eager_generator
[ 95%] Built target eager_op_function_generator
[ 96%] Built target op_function_generator
[ 96%] copy_if_different /home/Paddle/paddle/fluid/eager/api/generated/fluid_generated/nodes/nodes.tmp.cc to /home/Paddle/paddle/fluid/eager/api/generated/fluid_generated/nodes/nodes.cc
[ 96%] Built target eager_op_function_generator_cmd
[ 96%] Built target kernel_signature_generator
[ 96%] Built target op_function_generator_cmd
[ 96%] Built target analysis_helper
[ 96%] Built target ir_pass_manager
[ 96%] Built target ir_analysis_pass
[ 96%] Built target ir_params_sync_among_devices_pass
[ 96%] Built target ir_graph_build_pass
[ 96%] Built target analysis_passes
[ 96%] Built target analysis
[ 96%] Built target eager_codegen
[ 97%] Built target dygraph_node
[ 97%] Built target dygraph_function
[ 97%] Built target analysis_predictor
[ 97%] Built target performance_benchmark_utils
[ 97%] Built target op_function_common
[ 98%] Built target paddle_eager
[ 98%] Built target paddle_inference
[ 98%] Built target paddle_inference_c
[ 98%] Built target paddle_inference_c_shared
[ 99%] Built target paddle_inference_shared
[ 99%] Generating .check_symbol
copying /home/Paddle/build/third_party/threadpool/src/extern_threadpool/ThreadPool.h -> /home/Paddle/build/paddle_inference_install_dir/third_party/threadpool
copying /home/Paddle/build/CMakeCache.txt -> /home/Paddle/build/paddle_inference_install_dir
copying /home/Paddle/build/third_party/install/openblas/lib -> /home/Paddle/build/paddle_inference_install_dir/third_party/install/openblas
copying /home/Paddle/build/third_party/install/openblas/include -> /home/Paddle/build/paddle_inference_install_dir/third_party/install/openblas
copying /home/Paddle/build/third_party/install/gflags/include -> /home/Paddle/build/paddle_inference_install_dir/third_party/install/gflags
copying /home/Paddle/build/third_party/install/gflags/lib/libgflags.a -> /home/Paddle/build/paddle_inference_install_dir/third_party/install/gflags/lib
copying /home/Paddle/build/third_party/install/glog/include -> /home/Paddle/build/paddle_inference_install_dir/third_party/install/glog
copying /home/Paddle/build/third_party/install/glog/lib/libglog.a -> /home/Paddle/build/paddle_inference_install_dir/third_party/install/glog/lib
[ 99%] Linking CXX shared library libpaddle_pybind.so
copying /home/Paddle/build/third_party/install/utf8proc/include -> /home/Paddle/build/paddle_inference_install_dir/third_party/install/utf8proc
copying /home/Paddle/build/third_party/install/utf8proc/lib/libutf8proc.a -> /home/Paddle/build/paddle_inference_install_dir/third_party/install/utf8proc/lib
copying /home/Paddle/build/third_party/install/cryptopp/include -> /home/Paddle/build/paddle_inference_install_dir/third_party/install/cryptopp
copying /home/Paddle/build/third_party/install/cryptopp/lib/libcryptopp.a -> /home/Paddle/build/paddle_inference_install_dir/third_party/install/cryptopp/lib
copying /home/Paddle/build/third_party/install/xxhash/include -> /home/Paddle/build/paddle_inference_install_dir/third_party/install/xxhash
copying /home/Paddle/build/third_party/install/xxhash/lib/libxxhash.a -> /home/Paddle/build/paddle_inference_install_dir/third_party/install/xxhash/lib
copying /home/Paddle/build/third_party/install/protobuf/include -> /home/Paddle/build/paddle_inference_install_dir/third_party/install/protobuf
copying /home/Paddle/build/third_party/install/protobuf/lib/libprotobuf.a -> /home/Paddle/build/paddle_inference_install_dir/third_party/install/protobuf/lib
copying /home/Paddle/paddle/fluid/inference/api/paddle_*.h -> /home/Paddle/build/paddle_inference_install_dir/paddle/include
copying /home/Paddle/build/paddle/fluid/inference/libpaddle_inference.* -> /home/Paddle/build/paddle_inference_install_dir/paddle/lib
[ 99%] Built target check_symbol
copying /home/Paddle/build/paddle/fluid/framework/framework.pb.h -> /home/Paddle/build/paddle_inference_install_dir/paddle/include/internal
copying /home/Paddle/paddle/fluid/framework/io/crypto/cipher.h -> /home/Paddle/build/paddle_inference_install_dir/paddle/include/crypto/
copying /home/Paddle/paddle/phi/api/ext/*.h -> /home/Paddle/build/paddle_inference_install_dir/paddle/include/experimental/phi/api/ext/
copying /home/Paddle/paddle/phi/api/include/*.h -> /home/Paddle/build/paddle_inference_install_dir/paddle/include/experimental/phi/api/include/
copying /home/Paddle/paddle/phi/api/all.h -> /home/Paddle/build/paddle_inference_install_dir/paddle/include/experimental/phi/api/
copying /home/Paddle/paddle/phi/common/*.h -> /home/Paddle/build/paddle_inference_install_dir/paddle/include/experimental/phi/common/
copying /home/Paddle/paddle/phi/core/macros.h -> /home/Paddle/build/paddle_inference_install_dir/paddle/include/experimental/phi/core/
copying /home/Paddle/paddle/phi/core/visit_type.h -> /home/Paddle/build/paddle_inference_install_dir/paddle/include/experimental/phi/core/
copying /home/Paddle/paddle/utils/any.h -> /home/Paddle/build/paddle_inference_install_dir/paddle/include/experimental/utils/
copying /home/Paddle/paddle/utils/optional.h -> /home/Paddle/build/paddle_inference_install_dir/paddle/include/experimental/utils/
copying /home/Paddle/paddle/utils/none.h -> /home/Paddle/build/paddle_inference_install_dir/paddle/include/experimental/utils/
copying /home/Paddle/paddle/utils/flat_hash_map.h -> /home/Paddle/build/paddle_inference_install_dir/paddle/include/experimental/utils/
copying /home/Paddle/paddle/extension.h -> /home/Paddle/build/paddle_inference_install_dir/paddle/include/experimental/
Change phi header include path to adapt to inference api path
-- phi header path compat processing: /home/Paddle/build/paddle_inference_install_dir/paddle/include/experimental
-- phi header path compat processing complete: /home/Paddle/build/paddle_inference_install_dir/paddle/include/experimental/ext_all.h
-- phi header path compat processing complete: /home/Paddle/build/paddle_inference_install_dir/paddle/include/experimental/extension.h
-- phi header path compat processing: /home/Paddle/build/paddle_inference_install_dir/paddle/include/experimental/phi/api
-- phi header path compat processing complete: /home/Paddle/build/paddle_inference_install_dir/paddle/include/experimental/phi/api/all.h
-- phi header path compat processing: /home/Paddle/build/paddle_inference_install_dir/paddle/include/experimental/phi/api/ext
-- phi header path compat processing complete: /home/Paddle/build/paddle_inference_install_dir/paddle/include/experimental/phi/api/ext/dispatch.h
-- phi header path compat processing complete: /home/Paddle/build/paddle_inference_install_dir/paddle/include/experimental/phi/api/ext/exception.h
-- phi header path compat processing complete: /home/Paddle/build/paddle_inference_install_dir/paddle/include/experimental/phi/api/ext/op_meta_info.h
-- phi header path compat processing complete: /home/Paddle/build/paddle_inference_install_dir/paddle/include/experimental/phi/api/ext/tensor_compat.h
-- phi header path compat processing: /home/Paddle/build/paddle_inference_install_dir/paddle/include/experimental/phi/api/include
-- phi header path compat processing complete: /home/Paddle/build/paddle_inference_install_dir/paddle/include/experimental/phi/api/include/api.h
-- phi header path compat processing complete: /home/Paddle/build/paddle_inference_install_dir/paddle/include/experimental/phi/api/include/context_pool.h
-- phi header path compat processing complete: /home/Paddle/build/paddle_inference_install_dir/paddle/include/experimental/phi/api/include/dll_decl.h
-- phi header path compat processing complete: /home/Paddle/build/paddle_inference_install_dir/paddle/include/experimental/phi/api/include/sparse_api.h
-- phi header path compat processing complete: /home/Paddle/build/paddle_inference_install_dir/paddle/include/experimental/phi/api/include/strings_api.h
-- phi header path compat processing complete: /home/Paddle/build/paddle_inference_install_dir/paddle/include/experimental/phi/api/include/tensor.h
-- phi header path compat processing: /home/Paddle/build/paddle_inference_install_dir/paddle/include/experimental/phi/common
-- phi header path compat processing complete: /home/Paddle/build/paddle_inference_install_dir/paddle/include/experimental/phi/common/amp_type_traits.h
-- phi header path compat processing complete: /home/Paddle/build/paddle_inference_install_dir/paddle/include/experimental/phi/common/backend.h
-- phi header path compat processing complete: /home/Paddle/build/paddle_inference_install_dir/paddle/include/experimental/phi/common/bfloat16.h
-- phi header path compat processing complete: /home/Paddle/build/paddle_inference_install_dir/paddle/include/experimental/phi/common/complex.h
-- phi header path compat processing complete: /home/Paddle/build/paddle_inference_install_dir/paddle/include/experimental/phi/common/cpstring_impl.h
-- phi header path compat processing complete: /home/Paddle/build/paddle_inference_install_dir/paddle/include/experimental/phi/common/data_type.h
-- phi header path compat processing complete: /home/Paddle/build/paddle_inference_install_dir/paddle/include/experimental/phi/common/float16.h
-- phi header path compat processing complete: /home/Paddle/build/paddle_inference_install_dir/paddle/include/experimental/phi/common/int_array.h
-- phi header path compat processing complete: /home/Paddle/build/paddle_inference_install_dir/paddle/include/experimental/phi/common/layout.h
-- phi header path compat processing complete: /home/Paddle/build/paddle_inference_install_dir/paddle/include/experimental/phi/common/place.h
-- phi header path compat processing complete: /home/Paddle/build/paddle_inference_install_dir/paddle/include/experimental/phi/common/pstring.h
-- phi header path compat processing complete: /home/Paddle/build/paddle_inference_install_dir/paddle/include/experimental/phi/common/scalar.h
-- phi header path compat processing complete: /home/Paddle/build/paddle_inference_install_dir/paddle/include/experimental/phi/common/type_traits.h
-- phi header path compat processing: /home/Paddle/build/paddle_inference_install_dir/paddle/include/experimental/phi/core
-- phi header path compat processing complete: /home/Paddle/build/paddle_inference_install_dir/paddle/include/experimental/phi/core/macros.h
-- phi header path compat processing complete: /home/Paddle/build/paddle_inference_install_dir/paddle/include/experimental/phi/core/visit_type.h
copying /home/Paddle/build/third_party/install/openblas/lib -> /home/Paddle/build/paddle_inference_c_install_dir/third_party/install/openblas
copying /home/Paddle/build/third_party/install/openblas/include -> /home/Paddle/build/paddle_inference_c_install_dir/third_party/install/openblas
copying /home/Paddle/build/third_party/install/gflags/include -> /home/Paddle/build/paddle_inference_c_install_dir/third_party/install/gflags
copying /home/Paddle/build/third_party/install/gflags/lib/libgflags.a -> /home/Paddle/build/paddle_inference_c_install_dir/third_party/install/gflags/lib
copying /home/Paddle/build/third_party/install/glog/include -> /home/Paddle/build/paddle_inference_c_install_dir/third_party/install/glog
copying /home/Paddle/build/third_party/install/glog/lib/libglog.a -> /home/Paddle/build/paddle_inference_c_install_dir/third_party/install/glog/lib
copying /home/Paddle/build/third_party/install/utf8proc/include -> /home/Paddle/build/paddle_inference_c_install_dir/third_party/install/utf8proc
copying /home/Paddle/build/third_party/install/utf8proc/lib/libutf8proc.a -> /home/Paddle/build/paddle_inference_c_install_dir/third_party/install/utf8proc/lib
copying /home/Paddle/build/third_party/install/cryptopp/include -> /home/Paddle/build/paddle_inference_c_install_dir/third_party/install/cryptopp
copying /home/Paddle/build/third_party/install/cryptopp/lib/libcryptopp.a -> /home/Paddle/build/paddle_inference_c_install_dir/third_party/install/cryptopp/lib
copying /home/Paddle/build/third_party/install/xxhash/include -> /home/Paddle/build/paddle_inference_c_install_dir/third_party/install/xxhash
copying /home/Paddle/build/third_party/install/xxhash/lib/libxxhash.a -> /home/Paddle/build/paddle_inference_c_install_dir/third_party/install/xxhash/lib
copying /home/Paddle/build/third_party/install/protobuf/include -> /home/Paddle/build/paddle_inference_c_install_dir/third_party/install/protobuf
copying /home/Paddle/build/third_party/install/protobuf/lib/libprotobuf.a -> /home/Paddle/build/paddle_inference_c_install_dir/third_party/install/protobuf/lib
copying /home/Paddle/paddle/fluid/inference/capi_exp/pd_*.h -> /home/Paddle/build/paddle_inference_c_install_dir/paddle/include
copying /home/Paddle/build/paddle/fluid/inference/capi_exp/libpaddle_inference_c.* -> /home/Paddle/build/paddle_inference_c_install_dir/paddle/lib
copying /home/Paddle/build/third_party/eigen3/src/extern_eigen3/Eigen/Core -> /home/Paddle/build/paddle_install_dir/third_party/eigen3/Eigen
copying /home/Paddle/build/third_party/eigen3/src/extern_eigen3/Eigen/src -> /home/Paddle/build/paddle_install_dir/third_party/eigen3/Eigen
copying /home/Paddle/build/third_party/eigen3/src/extern_eigen3/unsupported/Eigen -> /home/Paddle/build/paddle_install_dir/third_party/eigen3/unsupported
copying /home/Paddle/build/third_party/boost/src/extern_boost/boost -> /home/Paddle/build/paddle_install_dir/third_party/boost
paddle/fluid/pybind/CMakeFiles/paddle_pybind.dir/build.make:2027: recipe for target 'paddle/fluid/pybind/libpaddle_pybind.so' failed
CMakeFiles/Makefile2:232003: recipe for target 'paddle/fluid/pybind/CMakeFiles/paddle_pybind.dir/all' failed
copying /home/Paddle/build/third_party/dlpack/src/extern_dlpack/include/dlpack -> /home/Paddle/build/paddle_install_dir/third_party/dlpack
copying /home/Paddle/build/third_party/install/zlib/include -> /home/Paddle/build/paddle_install_dir/third_party/install/zlib
copying /home/Paddle/build/third_party/install/zlib/lib/libz.a -> /home/Paddle/build/paddle_install_dir/third_party/install/zlib/lib
[ 99%] Built target inference_lib_dist
Makefile:148: recipe for target 'all' failed
**

### 版本&环境信息 Version & Environment Information

在 https://hub.docker.com/r/paddlepaddle/paddle/tags?page=1&name=aarch docker镜像包中编译

**Comment by BerryRB** [comment]
编译命令：
1、cmake .. -DPY_VERSION=3.7 -DWITH_ASCEND=OFF -DWITH_ARM=ON -DWITH_ASCEND_CL=OFF          -DWITH_ASCEND_INT64=ON -DWITH_TESTING=OFF -DON_INFER=ON -DWITH_GPU=OFF          -DCMAKE_BUILD_TYPE=Release -DCMAKE_EXPORT_COMPILE_COMMANDS=ON
2、make TARGET=ARMV8 -j$(nproc)

编译最后错误截图如下：
![image](https://user-images.githubusercontent.com/34699510/165700645-2d11ebf3-8c3d-4a3a-adfc-d06750c50833.png)

**Comment by haozech** [comment]
您好！从报错信息上看，是pybind部分出错，可以尝试检查下python相关的版本，是否是用最新的paddle develop分支下编译的？如果是的话可以切换到上一个稳定版本2.2试试。另外源码编译流程可以参考这个文档 https://www.paddlepaddle.org.cn/documentation/docs/zh/install/compile/arm-compile.html

**Comment by yang131313** [comment]
你好，现在Paddle已经有编译好的安装包了，请问你在什么任务场景下需要编译Paddle呀？比如是需要新增算子、还是需要修改飞桨源代码，或者有什么其他的用途呢？

**Comment by cole-dda** [comment]
哪里有编译好的linux下的，arm64，aarch64的包？

**Comment by april211** [comment]
Jetson nano 需要编译吧？

**Comment by jiguanglu** [comment]
现在最新的 **jertson AGX  orin** 只能使用 **jetpack5.0**以上的版本，希望飞桨的朋友，能尽快的编译出相符合的版本啊。

**Comment by cailuyu** [comment]
> 现在最新的 **jertson AGX orin** 只能使用 **jetpack5.0**以上的版本，希望飞桨的朋友，能尽快的编译出相符合的版本啊。

需求完全一样,在尝试自己编译!
有线索记得分享下!

**Comment by ccLemonTree** [comment]
> > 现在最新的**jertson AGX orin**只能使用**jetpack5.0**以上的版本，希望飞表的朋友，能尽快的编译出符合条件的版本啊。
> 
> 需要完全一样，在试自己编译！ 有线索记得到分享下！
请问一下编译成功了嘛？

**Comment by jiguanglu** [comment]
已经编译成功，而且官方也编译好了。
https://www.paddlepaddle.org.cn/inference/v2.4/guides/install/download_lib.html#c

**Comment by kankanjiuzou123** [comment]
> 已经编译成功，而且官方也编译好了。 https://www.paddlepaddle.org.cn/inference/v2.4/guides/install/download_lib.html#c
您好，这个是直接pip 安装就好了么，我想安装fastdeploy不知道怎么操作。。。

**Comment by jiguanglu** [comment]
> > 已经编译成功，而且官方也编译好了。 https://www.paddlepaddle.org.cn/inference/v2.4/guides/install/download_lib.html#c
> > 您好，这个是直接pip 安装就好了么，我想安装fastdeploy不知道怎么操作。。。

自己搜一下，如何安装这种文件吧。。。

**Comment by aixuedegege** [comment]
> > 已经编译成功，而且官方也编译好了。 https://www.paddlepaddle.org.cn/inference/v2.4/guides/install/download_lib.html#c
> > 您好，这个是直接pip 安装就好了么，我想安装fastdeploy不知道怎么操作。。。

兄弟 成功了吗
