### ISSUE TITLE
paddle2.2源码编译报错

### ISSUE THREAD

**Issue by jiaerwang0328** [PaddlePaddle/Paddle#42372]
### 请提出你的问题 Please ask your question

ubuntu18.04,cuda10.2,gcc7.5 编译报错
`/usr/lib/gcc/x86_64-linux-gnu/7/include/avx512fintrin.h(1761): error: identifier "__builtin_ia32_sqrtsd_round" is undefined`

**Comment by haozech** [comment]
你好，这里建议参考文档，在docker环境中进行编译 https://www.paddlepaddle.org.cn/documentation/docs/zh/install/compile/linux-compile.html  请注意编译选项设置正确

**Comment by yang131313** [comment]
你好，现在Paddle已经有编译好的安装包了，请问你在什么任务场景下需要编译Paddle呀？比如是需要新增算子、还是需要修改飞桨源代码，或者有什么其他的用途呢？
