### ISSUE TITLE
Paddle Hackthon Grad Operators

### ISSUE THREAD

**Issue by yangguohao** [PaddlePaddle/Paddle#42383]
### 请提出你的问题 Please ask your question

在[C++OP开发](https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/dev_guides/api_contributing_guides/new_cpp_op_cn.html)中提到反向算子

> 反向Kernel参数映射函数添加

> 现阶段，反向Kernel除了实现外，还需要添加一个参数映射函数。

> 仍然以trace op为例，首先在paddle/phi/ops/compat目录下新建trace_sig.cc文件，用于放置这里的映射函数。

注册GradOp始终不成功 [PR地址](https://github.com/PaddlePaddle/Paddle/pull/42364)

**Comment by chenwhql** [comment]
看CI的报错，好像是计算结果数值有问题，不是注册没成功，留了个评论

**Comment by yangguohao** [comment]
> 看CI的报错，好像是计算结果数值有问题，不是注册没成功，留了个评论

谢谢，问题已经解决了。我反向传播算子的参数映射函数的文件放错位置了。应该和inplace无关，我将文件放置之后结果就正确了。
