### ISSUE TITLE
paddleX部署paddleServing

### ISSUE THREAD

**Issue by leoaaaaa** [PaddlePaddle/Paddle#42386]
### 请提出你的问题 Please ask your question

paddleX训练的模型怎么用paddleServing的方式进行部署？
![image](https://user-images.githubusercontent.com/90248905/165787042-dbd28ffb-23a2-42e6-a44f-2c0b6764094e.png)

![image](https://user-images.githubusercontent.com/90248905/165787123-5e81b053-4f15-4ae7-a572-fe3c8f9c99d9.png)

**Comment by TeslaZhao** [comment]
训练生成模型后，先安装paddle_serving_client
然后，运行命令保存运行模型必备的参数。然后启动模型。
`python -m paddle_serving_client.convert --dirname . --model_filename dygraph_model.pdmodel --params_filename dygraph_model.pdiparams --serving_server serving_server --serving_client serving_client`

链接：https://github.com/PaddlePaddle/Serving/blob/v0.8.3/doc/Save_CN.md
