### ISSUE TITLE
liunx访问内部docker paddle serving

### ISSUE THREAD

**Issue by leoaaaaa** [PaddlePaddle/Paddle#42381]
### 问题描述 Issue Description

liunx中安装了docker，并且部署了paddleserving，docker内可以进行调用模型预测，
但是想问在liunx上怎么访问内部docker paddle serving 模型进行预测？
![image](https://user-images.githubusercontent.com/90248905/165764580-d47ea372-02a9-44b7-9182-9c58935ff361.png)

### 版本&环境信息 Version & Environment Information

Ubuntu16.04
docker

**Comment by TeslaZhao** [comment]
使用paddle Serving的版本是？
启动docker的时候是否有--network=host ?

**Comment by leoaaaaa** [comment]
版本：
![图片](https://user-images.githubusercontent.com/90248905/165884196-6844a0e9-0b09-4f00-b1c8-0af91fcceb00.png)
进入docker过程：
![图片](https://user-images.githubusercontent.com/90248905/165884207-fcb72364-7537-456c-b260-f61f4f8a74be.png)
