### ISSUE TITLE
BMLcodelab中gym数据集更换

### ISSUE THREAD

**Issue by HarryUP-rhy** [PaddlePaddle/Paddle#42389]
### 请提出你的问题 Please ask your question

在BML codelab中安装了gym-anytrading股票交易环境，如何更换自己想用的数据集呢？
在pycharm中可以找到虚拟环境中gym-anytrading的安装路径，在data文件夹下添加自己的数据集，修改__init__文件注册自己的环境名就可以了。
请问BML中如何更换？

**Comment by qili93** [comment]
抱歉，Paddle issue仅回答Paddle框架相关问题，BML的使用问题，请联系BML的技术支持，谢谢！
