### ISSUE TITLE
DYGRAPH Resnet training runtime fail

### ISSUE THREAD

**Issue by pmajchrzak** [PaddlePaddle/Paddle#42401]
### A case report:
From the beginning of April'22 2022 (it is difficult to determine the exact date and exact commit) Dygraph train.py script for the dygraph/resnet model from the https://github.com/PaddlePaddle/models/tree/develop repository (branch develop) has stopped working.

It was verified that the model resnet worked properly for an earlier version of PaddlePaddle (commit: 589709954ce73c064c638ee1df7cd92f6bc46efd (3/23/2022)).
Since the commit: c15e3823346e323d2d84f1fc7c174ae09790ccec (3/23/2022) all python scripts stopped running and few days after that there were commits that didn't build at all. Finally commit: e9e68c365801a2663b0332a9f050d844a81b0dea (4/6/2022) restored the python scripts, but at this point the paddle_models/dygraph/resnet/train.py script (from paddle models repository) was not working properly.

All of the above situations were tested on different commits of the Paddle/paddle repository and for one commit (https://github.com/PaddlePaddle/models/commit/0173b12c3974de44b0bdeb06802d6f27cb66dc65) from the Paddle/models repository. The case study shows that the problem is with the Paddle/paddle repository

It is worth noting that at the same time paddle_models/dygraph/mobilenet/train.py works correctly.

### Application run command:
```
OMP_NUM_THREADS=28 FLAGS_use_mkldnn=True  python /root/models/paddle_models_github/dygraph/resnet/train.py --use_gpu=False --ce --max_iter=200  -b=32
```
### ERROR:
```
Traceback (most recent call last):
  File "/root/models/paddle_models_github/dygraph/resnet/train.py", line 527, in <module>
    train_resnet()
  File "/root/models/paddle_models_github/dygraph/resnet/train.py", line 400, in train_resnet
    optimizer = optimizer_setting(parameter_list=resnet.parameters())
  File "/root/models/paddle_models_github/dygraph/resnet/train.py", line 188, in optimizer_setting
    regularization=fluid.regularizer.L2Decay(l2_decay))
  File "/usr/local/lib/python3.6/dist-packages/paddle/fluid/optimizer.py", line 1491, in __init__
    name=name)
  File "/usr/local/lib/python3.6/dist-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/usr/local/lib/python3.6/dist-packages/paddle/fluid/dygraph/base.py", line 299, in __impl__
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/paddle/fluid/optimizer.py", line 95, in __init__
    "parameter_list argument given to the Optimizer should not be None in dygraph mode."
AttributeError: parameter_list argument given to the Optimizer should not be None in dygraph mode.
```
### PaddlePaddle CMAKE parameters:
```
-DCMAKE_BUILD_TYPE=Release -DWITH_GPU=OFF -DWITH_MKLDNN=ON -DWITH_TESTING=ON -DWITH_PROFILER=OFF -DWITH_STYLE_CHECK=OFF -DON_INFER=ON -DWITH_INFERENCE_API_TEST=ON -DPY_VERSION=3.6
```

### Environment
```
            OS: Ubuntu18.04 with mkldnn 
 cmake version: 3.10.2
      Compiler: GCC 8
```

for information: @baoachun @jczaja @jiachen

**Comment by qili93** [comment]
Hi, @pmajchrzak 

The Paddle/models repo has been out of date, and all classification models has been migrated to [PaddlePaddle/PaddleClas](https://github.com/PaddlePaddle/PaddleClas/). And you can find the training script and run command of DYGRAPH ResNet50 here: https://github.com/PaddlePaddle/PaddleClas/blob/release/2.3/docs/en/models_training/classification_en.md

**Comment by qili93** [comment]
BTW, please note paddle/models also noted the migration here:
https://github.com/PaddlePaddle/models/blob/develop/PaddleCV/image_classification/README_en.md

<img width="1033" alt="image" src="https://user-images.githubusercontent.com/16605440/166904559-70b62e92-2bfa-458d-8bce-80ea452f8527.png">
