### ISSUE TITLE
2.3.0-rc0 macbook  M1Pro 源码编译失败

### ISSUE THREAD

**Issue by ltto** [PaddlePaddle/Paddle#42402]
### 请提出你的问题 Please ask your question

环境 
💻:macbook pro 14寸 M1Pro芯片
OS: MacOS 12.3.1
CPU:apple M1 pro
Python: 官网下载的 Python 3.10.4
```
➜  ~ python3 -c "import platform;print(platform.architecture()[0]);print(platform.machine())"
64bit
arm64
```
Paddlepaddle源码下载地址:   https://github.com/PaddlePaddle/Paddle/releases/tag/v2.3.0-rc0
源码编译教程参考:                   https://www.paddlepaddle.org.cn/documentation/docs/zh/install/compile/macos-compile.html
环境变量
``` shell
export PYTHON_INCLUDE_DIRS=/Library/Frameworks/Python.framework/Versions/3.10/include
export PYTHON_LIBRARY=/Library/Frameworks/Python.framework/Versions/3.10/lib
export PATH=/Library/Frameworks/Python.framework/Versions/3.10/bin:$PATH
export LD_LIBRARY_PATH=/Library/Frameworks/Python.framework/Versions/3.10
export DYLD_LIBRARY_PATH=/Library/Frameworks/Python.framework/Versions/3.10
export PY_WHEEL=/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/wheel
export PY_GOOGLE.PROTOBUF=/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/google/protobuf
export PYTHON_NUMPY_INCLUDE_DIR=/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/numpy/core/include
export PY_PIP=/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pip
export SWIG_BINARY_PATH=/opt/homebrew/bin/swig
```
运行命令
```
mkdir build && cd build
cmake .. -DPY_VERSION=3.10 -DPYTHON_INCLUDE_DIR=${PYTHON_INCLUDE_DIRS} \
    -DPYTHON_LIBRARY=${PYTHON_LIBRARY} -DWITH_GPU=OFF -DWITH_TESTING=OFF  -DCMAKE_BUILD_TYPE=Release
-- cmake 运行成功
make -j4
 报错
```
错误信息如下
![image](https://user-images.githubusercontent.com/24884691/165919842-78bfd2e3-8770-4297-aa85-922988f3d18a.png)
是我哪里操作不当吗?
希望我能为新版本出一份力
extern_protobuf-stamp.zip如下
[extern_protobuf-stamp.zip](https://github.com/PaddlePaddle/Paddle/files/8589806/extern_protobuf-stamp.zip)

**Comment by ltto** [comment]
我上翻控制台 看到这里出现了 2处warning 和1处error
![image](https://user-images.githubusercontent.com/24884691/165920513-6d82b4bd-4131-4b10-ba81-1db3de5023a4.png)
![image](https://user-images.githubusercontent.com/24884691/165920572-33f722b0-e816-4123-a843-54c5fdd23efa.png)
![image](https://user-images.githubusercontent.com/24884691/165920612-21ee4a44-9df5-4b61-bc4f-40088704cd91.png)

**Comment by ltto** [comment]
再次运行 
```
make -j4
```
![image](https://user-images.githubusercontent.com/24884691/165922597-25c018cc-8d89-4b15-b3e5-b4cbc5a69a86.png)

**Comment by pangyoki** [comment]
看你用的python3.10，可以在cmake编译选项里把-DWITH_ARM=ON打开，Mac m1设置 -DWITH_AVX=OFF。
另外，make时应该指定arm架构：`make TARGET=ARMV8 -j4`。

你编译的报错很可能有网络问题，建议先看下你的机器能不能正常从github下载包。

**Comment by dingjiaweiww** [comment]
你好，飞桨2.3 正式版会发布Mac m1 原生支持arm64架构的安装包

**Comment by yang131313** [comment]
你好，现在Paddle已经有编译好的安装包了，请问你在什么任务场景下需要编译Paddle呀？比如是需要新增算子、还是需要修改飞桨源代码，或者有什么其他的用途呢？

**Comment by ltto** [comment]
> 你好，现在Paddle已经有编译好的安装包了，请问你在什么任务场景下需要编译Paddle呀？比如是需要新增算子、还是需要修改飞桨源代码，或者有什么其他的用途呢？

谢谢 我提出这个issues 时候 还没有2.3.0 的包  我只是想尽快使用M1的飞桨, 既然现在已经有这个包了 我就关闭这个问题了
