### ISSUE TITLE
Ubuntu 22.04  CUDA11.6 如何安装 Paddle

### ISSUE THREAD

**Issue by monkeycc** [PaddlePaddle/Paddle#42419]
### 问题描述 Please describe your issue

Ubuntu 22.04  
GCC 11
CUDA11.6

在cuda11.6下
CUDNN 要什么版本

GCC-11 怎么办
我看最低只能GCC-9

**Comment by yinhaofeng** [comment]
可以先安装一下稍微低一点的版本，比如CUDA11.0，GCC8.2。 11.6版本还得过段时间支持。

**Comment by Ligoml** [comment]
你好，paddle2.3正式版会支持到CUDA11.2，11.6未来或许会有支持计划，目前还是建议使用稍低版本来使用paddle~

**Comment by jeffzhengye** [comment]
还是不支持ubuntu22.04 啊

**Comment by JJY0710** [comment]
都多少天了，还不支持22.04？

**Comment by dingjiaweiww** [comment]
> 都多少天了，还不支持22.04？

develop 版本已经支持22.04，2.4 版本会发版支持
