### ISSUE TITLE
跪求百度开发数据挖掘仓库

### ISSUE THREAD

**Issue by yuwoyizhan** [PaddlePaddle/Paddle#42417]
### 需求描述 Feature Description

机器学习在几十年前就成为研究对象了,深度学习10年前开始进入研究人员的视野,今时今日,百度有了非常非常多机器学习相关的仓库,基本上都跟深度学习相关.很多人都知道,数据挖掘是个非常重要的机器学习的课题,百度目前好像还没有数据挖掘的仓库,为什么不建一个呢?这个领域,应该每年都有很多顶级论文,有很多学者研究,也是非常非常多百度飞桨的应用者需要的东西.我认为,很多人需要百度飞桨弄个数据挖掘的仓库,复现那些最牛逼哄哄的论文,SOTA论文,然后让我们这些不是特别厉害的飞桨应用者而不是开发者可以使用百度提供的数据挖掘模型,进行训练,评估和预测.
我也看了一些数据挖掘的图书和视频,有机器学习的算法,比如线性回归,逻辑回归,adaboost等,也有使用神经网络的.
https://aistudio.baidu.com/aistudio/projectdetail/3754643?channelType=0&channel=0
这个项目,使用3层神经网络,就可以达到不错的成绩.根据多维特征,训练某个值,无论是回归还是分类,都属于数据挖掘的范畴,我认为使用神经网络比起传统的机器学习算法好多了.
但我认为,肯定有更好的数据挖掘的算法或者模型,这需要百度开仓库,并且复现数据挖掘顶级论文.
上面说到的数据挖掘,指的是时间无关的.还有一种时间相关的数据挖掘预测,有一篇相关的论文,好像还得了2021年的最佳论文奖.
还有一点,我想知道,我上面这个吃鸡的例子,如果把3层全连接神经网络,换成ResNet51,代码应该怎么写,我不会,跪求ResNet51代码,用于回归而不是分类,谢谢.

**Comment by qili93** [comment]
收到，非常感谢您的建议。

请问您这里能帮忙提供一下相关的论文，我们内部调研评估一下，多谢！

**Comment by yuwoyizhan** [comment]
@qili93 @Ligoml 最近2个希望百度飞桨提供数据挖掘的仓库的issue,都是我提的,哈哈哈哈.https://aistudio.baidu.com/aistudio/projectdetail/3754643?channelType=0&channel=0这个项目,作者使用3层全连接神经网络,做到了91分,我改善了一下,也是3层全连接神经网络,改了超参数,94分,但是使用20层,梯度爆炸了,无法训练,哈哈哈哈.据我所知,ResNet最重要的一个思想,就是防止梯度爆炸和消失,可以很好的组建非常多层的神经网络.而卷积网络与全连接神经网络本质区别,在于卷积神经网络对于图像很有效,对于别的数据就未必会比全连接神经网络有效.
数据挖掘,对我来说,有3种情形最重要.1.我有一个数据集,N维x和一维y,需要一个模型进行训练,评估,预测.上面说的这个项目,就是典型的N维x和一维y,定义一个模型,进行训练,评估,预测.我使用3层全连接神经网络,取得了不错的效果,但我不知道,使用ResNet的思想,或者VIT,SWINT,如何组建网络,用于这种数据挖掘模型.说白了,我不会组建梯度不会爆炸并且不会为0的很多层的神经网络,无论是全连接,还是卷积,还是TRANS,这得靠你们,我使用paddle.vision.resnet18之类的神经网络,需要输入4维数据,数据挖掘只能输入2维数据,唉,不知道怎么办?我只能看着代码报错而无能为力.
2.短时间序列预测.这个我认为也是数据挖掘的重中之重,我以前跟视觉负责人聊过,希望可以开设一个时间序列预测.后来百度飞桨弄了一个paddlespatial仓库,我还跟仓库的一个工作人员聊过,看过这个仓库的B站视频,给我的感觉就是,这个仓库的精力和时间,就是做地理位置相关的工作,不是做时间序列预测,不管是长时间序列预测,还是短时间序列预测.我个人认为,时间序列预测比起搞地理位置相关的工作,重要太多了.比如某个地点到某个地点乘车需要多少分钟?在百度公司,除了百度地图,还有哪个产品会用到这个?指望我一个飞桨应用者关心乘车用时?这是让我一个小小的飞桨应用者去打败百度地图,高德地图?这不扯淡吗?这个仓库的工作人员说了,主要精力确实是做地理位置工作,不是时间序列预测,而且我跟他聊了一会,他从没说过,有兴趣做短时间序列预测的工作.
3.长时间序列预测,paddlespatial的人弄了一篇SOTA的论文,还在百度第六期论文复现中,叫人去复现.反正我觉得这个仓库志不在此,只为了地理位置的神经网络,还是希望有个专门用于数据挖掘的神经网络仓库,让我们这些开发者可以非常简单的应用最牛逼的SOTA模型和算法,哈哈哈哈.
现实世界中,有很多时候都是可以得到大量数据,但是需要有算法或模型可以学习这些数据.我使用ResNet151,这么多层数据,训练猫狗数据集这种小数据集也好,训练imagenet这种大数据集也好,都不会梯度爆炸的,可以很好的拟合数据,学习数据.但我用20层全连接神经网络去拟合数据,看我上面说的那个项目,立马爆炸,哈哈哈哈.希望你们提供模型吧,其实,可能把用于图像分类的ResNet或者VIT,SWINT等模型,改变一下输入的数据格式,可能就是一个很不错的,可以用于数据挖掘的模型了.图像分类需要输入4维或者5维,改改输入格式变成2维,说白了,就是多维特征的x+一维y,改几个模型,对你们百度飞桨开发者来说,不要太简单了.一天功夫,可以改上百个模型吧,哈哈哈哈.
多维x预测一维y,目前我希望百度飞桨可以提供好的模型,我认为改改现有的ResNet,VIT,SWINT等模型,我或许就可以用了,哈哈哈哈.
你们要是可以提供SOTA的论文复现,那当然最好了,甚至弄个仓库专门做数据挖掘的工作,那我更高兴,但如果不愿意的话,那就按照路是一步一步走的原则,先提供一些可以用于数据挖掘的比较深层的模型给我们这些飞桨应用者使用.毕竟很多人根本不会组网.你们得先试试,会不会发生梯度爆炸或者梯度为0的情况啊.
短时间序列预测和长时间序列预测,指望我提供论文,让你们去调研研究是否复现论文,这种想法纯属想当然.我不懂英文,又不会机器学习.你们要是有兴趣复现论文,得你们自己找SOTA论文,整个过程都得由你们去做了.我觉得,调研看看哪些论文值得复现,对于你们这些飞桨开发者来说,太简单了,毕竟你们写的飞桨2.3rc0更新内容,我基本看不懂,而很多论文的中文解读,我还能看得懂,这说明,你们百度飞桨的开发者的能力,太牛逼了,小弟五体投地.
最后来个重点,我当然希望你们可以开个仓库,复现我说的这三个情形的SOTA论文啊.但如果你们不愿意这样做的话,跪求各位百度飞桨大佬,弄几个深层的,可以在数据挖掘领域正常训练的网络,不会梯度爆炸或者梯度为0的网络,给我用用,谢谢大佬.好心有好报,祝你们工作顺利,福如东海,寿比南山.你们提供的这几个模型,使用全连接神经网络也好,卷积也好,Trans注意力机制的也好,跪求几个模型了,大佬们.弄几个可以用于数据挖掘的深层网络模型,对你们来说,一天的工作量而已,哈哈哈哈.

**Comment by yuwoyizhan** [comment]
3种数据挖掘情形,我觉得都很有应用场景的.银行放贷前,判断是否欺诈,也是根据多维x和1维y进行模型的训练,评估和部署预测.但是飞桨目前应该没有比较好用的,深层的,不会梯度爆炸和为0的模型,比如vision下的ResNet,VIT等模型都要求输入是4维或者5维,根本不可能是2维,我也不知道如何改模型.
反正我觉得,我说的这三种数据挖掘情形,都有着极其广阔的应用场景.希望你们可以考虑弄个相关的仓库,哈哈哈哈.

**Comment by yuwoyizhan** [comment]
据我所知,pytorch的resnet模型,根本不会限制输入的格式必须是4维或者5维,也不会限制只能用于视觉领域.很多人把这个模型用于其他领域,取得巨大成功,因为这个模型,算是世界上第一个可以组建深层神经网络的模型,很多人只会这个模型,而不会那些更加复杂的模型了.举个例子,谷歌用ResNet研究围棋,超越世界冠军.还有人把ResNet用于所有棋类,比如围棋,五子棋,六子棋等,2060训练一天,世界冠军,哪里会限制ResNet只能用于4维或者5维的输入数据,哪里限制只能用于视觉领域呢?百度飞桨的ResNet却是vision下的接口,摆明了百度认为,这个模型只能用于视觉领域.

**Comment by Ligoml** [comment]
你好，
首先解答一下api的问题，paddle封装api是为了方便用户直接拿过来用，这不代表paddle限制了用户的灵活使用，对于灵活性有要求的用户可以通过组网的方式自定义模型结构，PaddleClas中提供的[ResNet网络](https://github.com/PaddlePaddle/PaddleClas/blob/1358e3f647e12b9ee6c5d6450291983b2d5ac382/docs/en/models/ResNet_and_vd_en.md)也是基于这样的方式而不是直接去调api，你可以参考这些组网方式来定义你自己想要的模型结构。

其次，paddle框架是基础工具，上层应用场景可能会更偏套件和生态方向，你所提到的数据挖掘仓库的学术和产业价值我们不好评估，可能需要更多的数据或第三方声音的支持。如果你可以提供一些高价值模型或学术论文，我们可以内部讨论是否可以借助生态的力量复现，这也是 @qili93 回复的意思。

**Comment by yuwoyizhan** [comment]
@qili93 @Ligoml 两位大佬,你们内部有没有讨论?打算增加数据挖掘的仓库吗?我记得2021年一个最佳论文就是长时间序列预测.而且数据挖掘也属于机器学习的范畴吧.
退一步讲,即使你们不愿意开设数据挖掘的仓库,提供一个比较大的模型,让我们可以正常训练数据挖掘,这总可以吧?这对于你们来说,也就是一天,甚至2小时的事情.提供这个模型,对于我们这些飞桨应用者来说,非常重要,因为很多飞桨使用者,只会使用飞桨模型,并不会读飞桨源代码,甚至复现SOTA论文或者模型.你们不能指望我会组建复杂网络吧,兄弟.
提供这个模型,数据挖掘的使用者就可以一步到位,非常轻松的使用飞桨模型,哈哈哈哈,而不是自己花费1个月时间,学习组网等一堆知识,再去自己进行组建网络等步骤.
据我所知,数据挖掘,也是机器学习的一个重要领域,拜托你们了,大佬们.

**Comment by Ligoml** [comment]
我们的讨论结论其实之前已经说了~数据挖掘仓库的学术和产业价值我们不好评估，可能需要更多的数据或第三方声音的支持。如果你可以提供一些高价值模型或学术论文，我们可以内部讨论是否可以借助生态的力量复现。
