### ISSUE TITLE
🤩飞桨社区活动总览

### ISSUE THREAD

**Issue by Ligoml** [PaddlePaddle/Paddle#42410]
大家好，这里用于展示飞桨社区的热门活动，飞桨团队会按照时间倒序增加活动 issue 的介绍与详情链接，你可以依据自己的兴趣与能力参加正在进行中的社区活动并获得奖励，活动结束后我们会及时 close 活动 issue。have fun~

### LearnDL框架学习计划  
- [ ] https://github.com/sunzhongkai588/LearnDL
- 活动时间：2023/02/22-2023/05/31（暂定）
- 活动介绍：深度学习框架开发有较高的门槛，很多人只能是望而却步。因此这门课程面向广大初学者开设，帮助开发者们提升技术水平。并以该课程为契机，为大家提供一个相互学习、交流的平台。在我们的课程里，你能学习到深度学习原理和编程知识，也能接触到深度学习的前沿信息，还能和业内资深开发者实时互动！！

### 飞桨快乐开源活动
- [ ] https://github.com/PaddlePaddle/Paddle/issues/48019
- 活动时间：2022/11/15—2023/1/15
- 活动介绍：飞桨快乐开源活动旨在鼓励更多的开发者参与到飞桨社区的开源建设中，帮助社区修复 bug 或贡献 feature，加入开源、共建飞桨。为了帮助大家循序渐进地了解、建议、开发飞桨开源项目，我们提供了三种类型的贡献任务，并为完成任务的贡献者准备了礼品表示感谢！快来提PR，领取新年礼物🎁啦~

### 飞桨黑客马拉松（第四期）
- [x] https://github.com/PaddlePaddle/Paddle/issues/51281
- 活动时间：2023/02/20—2023/5/20
- 活动介绍：深度学习技术及应用国家工程研究中心与飞桨携手硬件合作伙伴共同出品，上线200+开发任务，从框架开发、模型套件开发、模型复现、硬件项目开发到产业落地方案应有尽有，你可以依据自己的兴趣与能力选择认领，在规定时间内完成作品提交。

### 飞桨体验评测任务（第七期）
- [x] https://github.com/PaddlePaddle/Paddle/issues/47480
- 活动时间：2022/10/27—2022/11/6
- 活动介绍：要求开发者在指定时间内参与飞桨使用指南的文档评测、Pytorch模型动转静验证，按照任务分配和评测要求，完成评测问卷和摸底表格，与我们一起共建飞桨框架。

### 飞桨体验评测任务（第六期）
- [x] https://github.com/PaddlePaddle/Paddle/issues/45962
- 活动时间：2022/09/09—2022/09/16
- 活动介绍：要求用户在指定时间内参与飞桨API文档评测、飞桨参数服务器文档的全流程打卡，按照任务分配和评测要求，完成评测问卷、全流程打卡任务，与我们一起共建飞桨框架文档。

### 飞桨论文复现挑战赛（第七期）

- [x] https://github.com/PaddlePaddle/Paddle/issues/44501
- 活动时间：2022/07/21 - 2022/09/30
- 活动简介：要求选手在指定时间内使用飞桨完成论文复现，考察复现模型的精度。

### 飞桨黑客马拉松（第三期）

- [x] https://github.com/PaddlePaddle/Paddle/issues/43938
- 活动时间：2022/07/04 - 2022/09/29
- 活动简介：要求开发者在指定时间内完成飞桨框架开发任务，为飞桨框架做贡献。
- NEWS： 本次黑客松活动，线上部分已结束，欢迎大家继续认领&完成感兴趣的任务，可以@Ligoml review相关PR

### CCF GitLink 编程夏令营（GLCC） & PaddlePaddle

- [x] https://github.com/PaddlePaddle/Paddle/issues/42843
- 活动时间：2022/04/15 - 2022/11/11
- 活动简介：要求开发者在指定时间内完成飞桨框架开发任务，为飞桨框架做贡献。

### 开源之夏 2022 & PaddlePaddle

- [x] https://github.com/PaddlePaddle/Paddle/issues/42565
- 活动时间：2022/04/21 - 2022/10/31
- 活动简介：要求开发者在指定时间内完成飞桨框架开发任务，为飞桨框架做贡献。

### 飞桨体验评测任务（第五期）
- [x] https://github.com/PaddlePaddle/Paddle/issues/45400
- 活动时间：2022/08/24—2022/08/31
- 活动介绍：要求用户在指定时间内参与飞桨安装软硬件环境调研、飞桨动转静文档评估任务，按照任务分配和评测要求，完成调研问卷，输出体验评估报告，与我们一起共建飞桨框架文档。

###  飞桨体验评测任务（第四期）
- [x] https://github.com/PaddlePaddle/Paddle/issues/43485
- 活动时间：2022/06/15—2022/07/31
- 活动介绍：要求用户在指定时间内参与飞桨训练框架API文档评估、Paddle Lite 文档评估和Paddle Inference文档评估，按照任务分配和评测要求，输出体验评估报告，与我们一起共建飞桨框架文档。

###  飞桨体验评测任务（第三期）

- [x] https://github.com/PaddlePaddle/Paddle/issues/42938
- 活动时间：2022/05/18—2022/06/15
- 活动介绍：要求用户在指定时间内参与飞桨分布式文档全流程打卡任务与硬件接入文档评测工作，按照任务分配和评测要求，输出体验评估报告，与我们一起共建飞桨框架文档。

### 飞桨论文复现挑战赛（第六期）

- [x] https://github.com/PaddlePaddle/Paddle/issues/41482
- 活动时间：2022/04/07 - 2022/06/06
- 活动简介：要求选手在指定时间内使用飞桨完成论文复现，考察复现模型的精度。

###  PaddlePaddle + Gradio Blocks

- [x] https://github.com/PaddlePaddle/Paddle/issues/42918
- 活动时间：2022/05/17—2022/05/31
- 活动介绍：使用飞桨及Gradio Blocks来创建在线的AI Demo，详情请见：https://huggingface.co/Gradio-Blocks 。

### 飞桨黑客马拉松（第二期）

- [x] https://github.com/PaddlePaddle/Paddle/issues/40234
- 活动时间：2022/03/08 - 2022/05/20
- 活动简介：要求开发者在指定时间内完成飞桨框架开发任务，为飞桨框架做贡献。
- NEWS： 本次黑客松活动，线上部分已结束，欢迎大家继续认领&完成感兴趣的任务，可以@Ligoml review相关PR

### 飞桨体验评测任务（第二期）

- [x] https://github.com/PaddlePaddle/Paddle/issues/40109
- 活动时间：2022/03/03 - 2022/03/30
- 活动简介：要求用户在指定时间内参与飞桨训练框架文档评估与 Paddle Lite 的文档评估工作，按照任务分配和评测要求，输出体验评估报告，与我们一起共建飞桨框架文档。

### 飞桨体验评测任务（第一期）

- [x] https://github.com/PaddlePaddle/Paddle/issues/38865
- 活动时间：2022/01/11 - 2022/02/30
- 活动简介：要求用户在指定时间内参与飞桨API文档及目录、安装模块的体验评测工作，按照任务分配和评测要求，输出体验评估报告，与我们一起共建飞桨框架产品。

### 飞桨论文复现挑战赛（第五期）

- [x] https://github.com/PaddlePaddle/Paddle/issues/37401
- 活动时间：2021/11/22 - 2022/02/15
- 活动简介：要求选手在指定时间内使用飞桨完成论文复现，考察复现模型的精度。

### 飞桨黑客马拉松（第一期）

- [x] https://github.com/PaddlePaddle/Paddle/issues/35940
- 活动时间：2021/09/23-2021/12/12
- 活动简介：要求开发者在指定时间内完成飞桨框架开发任务，为飞桨框架做贡献。
- NEWS： 本次黑客松活动，线上部分已结束，欢迎大家继续认领&完成感兴趣的任务，可以@Ligoml review相关PR

### 飞桨论文复现挑战赛（第四期）

- [x] https://github.com/PaddlePaddle/Paddle/issues/34526
- 活动时间：2021/08/02 - 2021/09/30
- 活动简介：要求选手在指定时间内使用飞桨完成论文复现，考察复现模型的精度。

如果没有找到感兴趣的活动，你可以关注飞桨 [RoadMap](https://github.com/PaddlePaddle/Paddle/issues/42571)、[good first issue](https://github.com/PaddlePaddle/Paddle/labels/good%20first%20issue) 等其他议题，参与飞桨社区的日常讨论与框架建设。如果你有新的活动想法或形式，欢迎在此 issue 下留言~

**Comment by D-DanielYang** [comment]
nice, up up！

**Comment by HusterYXPeng** [comment]
【队名】：未来CTO

【序号】：48

【状态】：提交作品

【链接】：https://github.com/HusterYXPeng/Paddle

**Comment by HusterYXPeng** [comment]
【队名】：未来CTO

【序号】：48

【状态】：报名

【链接】：https://github.com/HusterYXPeng/Paddle
