### ISSUE TITLE
Musl docker build error

### ISSUE THREAD

**Issue by ravirathore** [PaddlePaddle/Paddle#42416]
### 问题描述 Issue Description

Hi,
Trying to do musl build using instructions from here : https://github.com/PaddlePaddle/Paddle/tree/develop/paddle/scripts/musl_build

But, after executing this step (on an aarch64 machine), receiving this error. Its related to some command line option '-m64'.  Please let know whether this works on an aarch64 machine.

Errors are here (last few lines):
-- extracting... [tar xfz]
-- extracting... [analysis]
-- extracting... [rename]
-- extracting... [clean up]
-- extracting... done
[  2%] No patch step for 'extern_lapack'
[  2%] No update step for 'extern_lapack'
[  2%] No configure step for 'extern_lapack'
[  2%] No build step for 'extern_lapack'
[  2%] Performing install step for 'extern_lapack'
[  2%] Completed 'extern_lapack'
[  2%] Built target extern_lapack
[  2%] Running C++ protocol buffer compiler on shape_range_info.proto
Scanning dependencies of target shape_range_info_proto
[  2%] Building CXX object paddle/fluid/inference/utils/CMakeFiles/shape_range_i                                                       nfo_proto.dir/shape_range_info.pb.cc.o
c++: error: unrecognized command line option '-m64'
make[2]: *** [paddle/fluid/inference/utils/CMakeFiles/shape_range_info_proto.dir                                                       /build.make:71: paddle/fluid/inference/utils/CMakeFiles/shape_range_info_proto.d                                                       ir/shape_range_info.pb.cc.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:261219: paddle/fluid/inference/utils/CMakeFil                                                       es/shape_range_info_proto.dir/all] Error 2
make: *** [Makefile:130: all] Error 2
~/build #
[  0%] No install step for 'extern_pybind'
[  1%] No test step for 'extern_pybind'
[  1%] Completed 'extern_pybind'
[  1%] Built target extern_pybind
Scanning dependencies of target extern_lapack
[  2%] Creating directories for 'extern_lapack'
[  2%] Performing download step (download, verify and extract) for 'extern_lapack'
-- Downloading...
   dst='/root/build/third_party/lapack/src/lapack_lnx_v3.10.0.20210628.tar.gz'
   timeout='none'
-- Using src='https://paddlepaddledeps.bj.bcebos.com/lapack_lnx_v3.10.0.20210628.tar.gz'
-- verifying file...
       file='/root/build/third_party/lapack/src/lapack_lnx_v3.10.0.20210628.tar.gz'
-- Downloading... done
-- extracting...
     src='/root/build/third_party/lapack/src/lapack_lnx_v3.10.0.20210628.tar.gz'
     dst='/root/build/third_party/lapack/src/extern_lapack'
-- extracting... [tar xfz]
-- extracting... [analysis]
-- extracting... [rename]
-- extracting... [clean up]
-- extracting... done
[  2%] No patch step for 'extern_lapack'
[  2%] No update step for 'extern_lapack'
[  2%] No configure step for 'extern_lapack'
[  2%] No build step for 'extern_lapack'
[  2%] Performing install step for 'extern_lapack'
[  2%] Completed 'extern_lapack'
[  2%] Built target extern_lapack
[  2%] Running C++ protocol buffer compiler on shape_range_info.proto
Scanning dependencies of target shape_range_info_proto
[  2%] Building CXX object paddle/fluid/inference/utils/CMakeFiles/shape_range_info_proto.dir/shape_range_info.pb.cc.o
c++: error: unrecognized 
make[2]: *** [paddle/fluid/inference/utils/CMakeFiles/shape_range_info_proto.dir/build.make:71: paddle/fluid/inference/utils/CMakeFiles/shape_range_info_proto.dir/shape_range_info.pb.cc.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:261219: paddle/fluid/inference/utils/CMakeFiles/shape_range_info_proto.dir/all] Error 2
make: *** [Makefile:130: all] Error 2

Please help.

thanks,

### 版本&环境信息 Version & Environment Information

summary_env.py:51: DeprecationWarning: distro.linux_distribution() is deprecated. It should only be used as a compatibility shim with Python's platform.linux_distribution(). Please use distro.id(), distro.version() and distro.name() instead.
  plat = distro.linux_distribution()[0]
summary_env.py:52: DeprecationWarning: distro.linux_distribution() is deprecated. It should only be used as a compatibility shim with Python's platform.linux_distribution(). Please use distro.id(), distro.version() and distro.name() instead.
  ver = distro.linux_distribution()[1]
****************************************
Paddle version: None
Paddle With CUDA: None

OS: Alpine Linux 3.11.7
Python version: 3.7.9

CUDA version: None
cuDNN version: None
Nvidia driver version: None

**Comment by qili93** [comment]
hi @ravirathore ,

The `build_inside.sh` is for X86_64, and if you would like to build on an aarch64 machine. Please try to modify the script as following:

1. CMAKE command need to add `-DWITH_ARM=ON` here https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/scripts/musl_build/build_inside.sh#L72
2. MAKE command need to change to `make TARGET=ARMV8 -j8` here https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/scripts/musl_build/build_inside.sh#L80

**Comment by ravirathore** [comment]
Thanks for the reply.

Its showing this error now (last few lines). Please help.

Generated Forward Input Position Map:  {'x': ['Tensor', 0]}
Generated Forward Output Position Map:  {'out': ['Tensor', 0]}
Generated Forward Input Position Map:  {'x': ['Tensor', 0]}
Generated Forward Output Position Map:  {'out': ['Tensor', 0]}
Generated Forward Input Position Map:  {'x': ['Tensor', 0]}
Generated Forward Output Position Map:  {'out': ['Tensor', 0], 'rulebook': ['Tensor', 1]}
Generated Forward Input Position Map:  {'x': ['Tensor', 0]}
Generated Forward Output Position Map:  {'out': ['Tensor', 0], 'rulebook': ['Tensor', 1]}
[ 96%] Built target eager_final_state_codegen
[ 96%] Built target grad_tensor_holder
[ 96%] Built target backward
[ 96%] Built target eager_generator
[ 96%] copy_if_different /paddle/paddle/fluid/eager/api/generated/fluid_generated/nodes/nodes.tmp.cc to /paddle/paddle/fluid/eager/api/generated/fluid_generated/nodes/nodes.cc
[ 96%] Built target eager_codegen
[ 96%] Built target custom_operator_node
[ 96%] Built target final_dygraph_node
[ 96%] Built target final_dygraph_function
[ 96%] Built target dygraph_function
[ 96%] Built target dygraph_node
[ 96%] Built target py_layer_node
[ 97%] Built target paddle_eager
[ 98%] Built target paddle_pybind
[ 98%] Built target performance_benchmark_utils
[ 98%] Built target subgraph_util
[ 98%] Built target benchmark
[ 98%] Linking CXX static library libpaddle_inference.a
Merge and generate static lib: libpaddle_inference.a
/usr/bin/ranlib: /root/build/paddle/fluid/inference/libpaddle_inference.a: file format not recognized
make[2]: *** [paddle/fluid/inference/CMakeFiles/paddle_inference.dir/build.make:1359: paddle/fluid/inference/libpaddle_inference.a] Error 1
make[2]: *** Deleting file 'paddle/fluid/inference/libpaddle_inference.a'
make[1]: *** [CMakeFiles/Makefile2:248743: paddle/fluid/inference/CMakeFiles/paddle_inference.dir/all] Error 2
make: *** [Makefile:130: all] Error 2
Regards,

**Comment by ravirathore** [comment]
I did manual build. Will also try automatic build. Will reply.

regards,

**Comment by ravirathore** [comment]
Thanks, it worked with auto build. It generated paddlepaddle-0.0.0-cp37-cp37m-linux_aarch64 - to be used with python3.7.
I  installed it(in alpine 3.10), and then tried to install paddleocr, but, it tried to compile opencv and it couldn't (however, it could generate wheels of other dependencies.) Pls let know, if, is it possible to extract opencv wheel from docker image?

thanks,

**Comment by qili93** [comment]
hi, @ravirathore 

Please help to confirm if the opencv is required by PaddleOCR from  https://github.com/PaddlePaddle/PaddleOCR/blob/develop/requirements.txt with `opencv-python==4.2.0.32`?

As opencv-python starts to support `manylinux2014_aarch64.whl` from version 4.5.2.54. And you will fail to install [4.2.0.32](https://pypi.org/project/opencv-python/4.5.2.54/#files) in aarch64. The workaround is to install 4.5.2.54+ version and try if PaddleOCR works or not. 

If it NOT works, please let me know and I will confirm with PaddleOCR team whether it's possible to upgrade opencv-python version to 4.5.2.54+.

**Comment by ravirathore** [comment]
Hi,
PaddleOCR tried to compile opencv-contrib version 4.4.0.46.
I also tried separately. But couldn't do it. Not sure how to do it.
Also, alpine has musl library - not sure whether manylinux will work with it.
 Please see.

Thanks,

**Comment by qili93** [comment]
hi, @ravirathore 

If you are sure that your environment has  opencv-python installed, then you just need to remove "opencv-python" requirement from https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.4/requirements.txt, then go ahead with PaddleOCR installation.

In case you have problem to install opencv-python in your environment, propose to open issue in opencv community to resolve.

Thanks

**Comment by ravirathore** [comment]
Hi,
Thanks.
I was able to compile opencv-python, but only in a system with python3.10.
Pls let know if its possible to generate the Paddle wheel for Python-3.10 from the docker. Currently, it provides python3.7 version wheel (paddlepaddle-0.0.0-cp37-cp37m-linux_aarch64.whl).

Thanks and regards,

**Comment by qili93** [comment]
Hi @ravirathore ,

If you are able to install Python3.10 in your docker container, then you just need to modify the scrips as following:

1. https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/scripts/musl_build/build_inside.sh#L23 to change `PYTHON_VERSION=3.10`
2. https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/scripts/musl_build/build_inside.sh#L80 to add CMAKE args of `-DPY_VERSION=3.10 -DPYTHON_EXECUTABLE=path_to_python3.10`

Then compile Paddle from source code again, it will generate python 3.10 whl package.

**Comment by ravirathore** [comment]
Thanks!
