### ISSUE TITLE
gpu版本2.2.2 在训练的时候偶尔会出现dataload 错误,此时需要重启训练容器或者训练服务器才可以

### ISSUE THREAD

**Issue by apexg** [PaddlePaddle/Paddle#42427]
### bug描述 Describe the Bug

gpu版本2.2.2 在训练的时候偶尔会出现dataload 错误,此时需要重启训练容器或者训练服务器才可以

### 其他补充信息 Additional Supplementary Information

无

**Comment by windstamp** [comment]
您好，此问题属于产品技术BUG，我们会尽快改进，感谢您提出的宝贵意见，谢谢。

请问您是单卡训练还是多卡训练。

**Comment by windstamp** [comment]
您好，能否提供一下具体的报错信息，以及一份最小的可复现代码，以帮助我们来详细排查这个问题。
