### ISSUE TITLE
追踪paddle.grad在模型复现中的bug(Tracking paddle.grad bugs in model reproduction)

### ISSUE THREAD

**Issue by Ligoml** [PaddlePaddle/Paddle#42420]
### bug描述 Describe the Bug

飞桨团队近期收到一些关于 `paddle.grad` 精度上不符合预期的issue，初步判断是底层存在bug，但由于 `paddle.grad` 比较复杂，研发团队难以快速定位问题与修复，因此希望借助社区的力量。

- 如果你现在或曾经遇到过 `paddle.grad` 相关的问题，希望你可以在评论区留下你的经历与解决方案；
- 如果你有热心有能力参与排查，希望你可以在评论区留下自己的分析和判断，和飞桨研发团队共同解决~

-----

Recently we received some issues about the accuracy of `paddle.grad` not meeting expectations. The initial judgment is that there is a bug in the bottom layer. However, due to the complexity of `paddle.grad`, it is difficult for the RD team to quickly locate the problem and fix it. Therefore, we hope Leverage the power of community.

- If you have encountered `paddle.grad` related problems, we hope you can leave your experience and solutions in the comment area;
- If you are enthusiastic and able to participate in the investigation, we hope you can leave your analysis and judgment in the comment area, and solve it together with the Paddle RD team~

### 其他补充信息 Additional Supplementary Information

相关issue：

- https://github.com/PaddlePaddle/Paddle/issues/39759
- https://github.com/PaddlePaddle/PaddleGAN/issues/601

评论区留言建议参考格式：
- 项目名称：（论文题目或模型名称）
- 问题描述：（尽可能详细，代码如果过长建议附上repo链接与截图，或issue链接）

**Comment by bitcjm** [comment]
模型：GPEN
问题描述：我用到paddle.grad的函数如下：
def d_r1_loss(real_pred, real_img):
    grad_real, = paddle.grad(outputs=real_pred.sum(), inputs=real_img, create_graph=True)
    grad_penalty = grad_real.pow(2).reshape([grad_real.shape[0], -1]).sum(1).mean()
    return grad_penalty

其中outputs参数的输入是对抗网络鉴别器的鉴别图片real_img的输出real_pred的和，real_pred的shape为[-1, 1]， real_img的shape为[-1, 3，256,256]。
input的输入是real_img，在与pytorch的grad输入相同的情况下，输出的值差了两个数量级，以下列举了几个grad_real相同位置的对应值：

第一组：
paddle：
Tensor(shape=[5], dtype=float32, place=CUDAPlace(1), stop_gradient=False,
       [-0.00000006, -0.00000006, -0.00000013, -0.00000006, -0.00000013])
torch：
tensor([1.1805e-06, 1.0896e-06, 1.5397e-06, 1.4202e-06, 1.3959e-06],
       device='cuda:0', grad_fn=<SliceBackward0>)

第二组：
paddle：
Tensor(shape=[5], dtype=float32, place=CUDAPlace(1), stop_gradient=False,
       [-0.00000040, -0.00000034, -0.00000042, -0.00000036, -0.00000045])
torch:
tensor([1.3870e-06, 1.0469e-06, 8.8018e-07, 5.9865e-07, 9.4373e-07],
       device='cuda:0', grad_fn=<SliceBackward0>)

**Comment by miemie2013** [comment]
模型：StyleGan2系列

问题复现：

代码地址：https://github.com/miemie2013/ppgan

环境：Python3.9、paddlepaddle-gpu==2.2.0

进入test_grad文件夹。首先运行test2_18_elementwise_grad.py，用了pytorch实现了上面的语句（精简了一下）
```
    style = styles.reshape((batch_size, 1, in_C, 1, 1))
    weight_pytorch = scale * weight * style
    demod = (weight_pytorch.square().sum(axis=[2, 3, 4]) + 1e-8).rsqrt()
    weight_pytorch = weight_pytorch * demod.reshape((batch_size, out_C, 1, 1, 1))
```
，跑8次前向，保存输入、输出、损失对styles的梯度等为文件18_grad.npz；
接着，跑test2_18_elementwise_grad_paddle.py，用了paddle实现了上面的语句（精简了一下），
```
    style = styles.reshape((batch_size, 1, in_C, 1, 1))
    weight = scale * weight * style
    demod = paddle.rsqrt((weight * weight).sum([2, 3, 4]) + 1e-8)
    weight = weight * demod.reshape((batch_size, out_C, 1, 1, 1))
```
读取18_grad.npz中保存的输入作为输入，跑8次前向。即此时paddle版与pytorch版有相同的输入，我们期望paddle与pytorch有相同的输出、相同的梯度。但是跑8次前向的结果发现，out_pytorch与out_paddle是一样的，dloss_dstyles_pytorch与dloss_dstyles_paddle差异巨大。

系paddle.grad()这个api求出了错误的梯度。但是我发现develop版本似乎已经解决这个bug了，输出全0了。

**Comment by simonsLiang** [comment]
我也发现了这个问题，2.2.2的paddle.grad与pytorch输出差别很大，但2.1.2和2.3.0的与pytorch输出一致，  不过在2.1.2和2.3.0版本中，如果前向含有paddle.sin操作，paddle.grad又设置create_graph=True时  会报错  问题复现可参考https://aistudio.baidu.com/aistudio/projectdetail/3969839?contributionType=1&shared=1

**Comment by hhjGHub** [comment]
模型：StyleGAN V2
paddle版本：paddlepaddle-gpu==2.2.2
参考文档：https://github.com/PaddlePaddle/PaddleGAN/blob/develop/docs/zh_CN/tutorials/styleganv2.md
问题描述：近期，复现StyleGAN V2模型训练时，训练过程中没有报错信息，训练完成后的随机采样结果效果很差
![5d95e073451caa354c184a3961ba773](https://user-images.githubusercontent.com/49189504/167349772-3a5423e7-a9df-4527-ae87-9b91bfb5d3b9.jpg)
初步定位StyleGAN V2中的梯度可能有错误，paddle.grad()这个api求出了错误的梯度

**Comment by lujx1024** [comment]
> 模型：StyleGAN V2 paddle版本：paddlepaddle-gpu==2.2.2 参考文档：https://github.com/PaddlePaddle/PaddleGAN/blob/develop/docs/zh_CN/tutorials/styleganv2.md 问题描述：近期，复现StyleGAN V2模型训练时，训练过程中没有报错信息，训练完成后的随机采样结果效果很差 ![5d95e073451caa354c184a3961ba773](https://user-images.githubusercontent.com/49189504/167349772-3a5423e7-a9df-4527-ae87-9b91bfb5d3b9.jpg) 初步定位StyleGAN V2中的梯度可能有错误，paddle.grad()这个api求出了错误的梯度

我们在训练的时候出现了类似的问题，尝试使用512*512像素的训练数据，训练不成功

**Comment by bitcjm** [comment]
模型：GPEN 
paddle版本：linux CUDA10.1 develop版本
项目地址：https://github.com/bitcjm/GPEN_REPO
我在对进行测试时发现，与上面提到的类似，设置create_gragh=True使用时会报错：报错如下：
(AlreadyExists) Accumulators with grad_node as the key are not empty before preparing it for backward network execution.
  [Hint: Expected accumulators_with_grad_node_.empty() == true, but received accumulators_with_grad_node_.empty():0 != true:1.] (at /paddle/paddle/fluid/imperative/basic_engine.cc:61)

如果设置为False，那报错如下：

NotFound) Inputs and outputs of elementwise_add_grad do not exist. This may be because:
1. You use some output variables of the previous batch as the inputs of the current batch. Please try to call "stop_gradient = True" or "detach()" for these variables.
2. You calculate backward twice for the same subgraph without setting retain_graph=True. Please set retain_graph=True in the first backward call.

  [Hint: Expected ins_.empty() && outs_.empty() != true, but received ins_.empty() && outs_.empty():1 == true:1.] (at /paddle/paddle/fluid/imperative/op_base.h:166)

如果再接着改那跟原来要求的就差的很远了，没继续求证。
如果使用2.2.2的稳定版本，相同的代码能跑通，但是结果相差很大。

**Comment by jzhang533** [comment]
cc: @chenwhql @JiabinYang

**Comment by JiabinYang** [comment]
> 

麻烦提供下当时develop的commit号和具体的执行case，看报错的话 这个报错应该不是paddle.grad的错误 看起来是backward()的问题

**Comment by chenwhql** [comment]
看了下，这里有三个问题：

1. GPEN 2.2版本梯度数值错误，develop在accumulate阶段报错 @bitcjm ，这个麻烦您提供下相关信息，我们高优看下！
2. StyleGan2 2.2版本梯度数据错误，2.3或develop已修复？这个能麻烦用2.3.0-rc或者nightly build版本确认一下吗？中间不断在迭代开发，我们以最新的版本为准，马上2.3正式版也要发布了 @miemie2013 @hhjGHub @lujx1024 
3. test中使用paddle.sin，但sin找不到没有二阶导实现 @simonsLiang，这个我们会列需求开发下，在下个版本添加。现在paddle每个二阶反向算子是单独开发的，所以这里是个局部问题，是sin还没有支持二阶反向算子，并不是执行机制问题，如果这个不是模型必须的话，您也可以不必单独关注这个算子，感谢！

**Comment by bitcjm** [comment]
@chenwhql 请问要提供怎样的信息，我好去弄一下

**Comment by chenwhql** [comment]
> @chenwhql 请问要提供怎样的信息，我好去弄一下

麻烦参考上一条 @JiabinYang 的回复

**Comment by bitcjm** [comment]
develop的commit号我不清楚在哪找，当时安装指令如下：
python -m pip install paddlepaddle-gpu==0.0.0.post101 -f https://www.paddlepaddle.org.cn/whl/linux/gpu/develop.html
最开始发现错误是在2.2.2稳定版。

执行的操作如下：
'''
def d_r1_loss(real_pred, real_img):
    grad_real, = autograd.grad(
        outputs=real_pred.sum(), inputs=real_img, create_graph=True
    )
    grad_penalty = grad_real.pow(2).reshape([grad_real.shape[0], -1]).sum(1).mean()
    return grad_penalty

real_img.stop_gradient=False
real_pred = discriminator(real_img)
r1_loss = d_r1_loss(real_pred, real_img)
'''

经过查证，d_r1_loss函数里第一步求出的grad_real就是错的，进而求出的r1_loss也错了。所以应该是是paddle.grad的错误，而不是backward的错误。

项目在以下链接：https://aistudio.baidu.com/aistudio/projectdetail/3894820?contributionType=1
相关代码在第20个执行kernel和第42个执行kernel中。

**Comment by bitcjm** [comment]
经过测试在上面给的aistudio链接中，选择2.1.2版本的paddle可以复现出develop版本遇到的错误。选择2.2.2版本可以复现出能跑同，但是求出错误的值的情况。

**Comment by JiabinYang** [comment]
> 经过查证，d_r1_loss函数里第一步求出的grad_real就是错的，进而求出的r1_loss也错了。所以应该是是paddle.grad的错误，而不是backward的错误

我的意思是您上面提供的报错看起来是backward的错误不是grad的错误，但是精度不一致的问题我认为应该是和 @chenwhql 提到的是在后续版本中修复了，因此我觉得我们先基于develop来看具体的问题吧

**Comment by JiabinYang** [comment]
麻烦提供下 上述代码的执行方式 我来看看

**Comment by bitcjm** [comment]
@JiabinYang 请参考以下链接中的项目的paddle.grad测试版本。选取2.1.2版本的paddle
可以复现错误，也可以取消注释，运行notebook中的第一个kernel卸载并重新安装develop版本的paddle，然后进行测试。
项目链接：https://aistudio.baidu.com/aistudio/projectdetail/3894820?contributionType=1

顺序执行整个notebook即可出现错误。相关代码我已调整至notebook最下方。在train()函数的46-54和81-94行，和train函数下面的kernel中.

**Comment by JiabinYang** [comment]
好的 我试试哈

**Comment by veyron95** [comment]
@bitcjm 您好，所提供的项目链接：https://aistudio.baidu.com/aistudio/projectdetail/3894820?contributionType=1,   顺序执行并不能复现问题（会报ModuleNotFoundError: No module named 'training', ModuleNotFoundError: No module named 'metrics.fid' 等问题），麻烦提供一份可执行可复现的最小项目链接，方便调试和复现问题。

**Comment by bitcjm** [comment]
@veyron95 您好，链接中的项目已修复问题。请参考草稿版本或使用paddle.grad测试修正版版本并注释第一个kernel的第一行顺序执行。这两个版本默认的notebook的最下方也有我顺讯执行过程中的报错，可供参考。

**Comment by veyron95** [comment]
@bitcjm 好的，多谢，我试试。

**Comment by veyron95** [comment]
@bitcjm 我顺序执行了你所提供的项目链接，复现所看到的情况：
![image](https://user-images.githubusercontent.com/87417304/168231297-dce94986-60ed-49fd-841f-59e7f9c96160.png)
意思是 elementwise_pow_grad 没有对应的反向OP（Paddle中暂未实现elementwise_pow的二阶算子）。另外，autograd.grad 接口里面的 create_graph 参数为 True 的话，表明计算当前反向过程的同时将对应的更高一阶的反向图创建出来。看到代码中有两处使用了 autograd.grad 接口，create_graph参数都为 True, 请问当前的实现中是确定需要设置为 True 吗？

**Comment by bitcjm** [comment]
@veyron95 确定要

**Comment by bitcjm** [comment]
复现对象设置的就是True，而且经过验证，这项损失值非常重要，缺少或者错误会很影响训练的结果。

**Comment by bitcjm** [comment]
但是我也没试过这是为False训练的效果会咋样，我可以花两天时间跑以下看看结果

**Comment by veyron95** [comment]
@bitcjm 通过分析项目链接中的代码发现不少地方使用了** 运算符（底层为elementwise_pow算子），这在该网络的反向和 autograd.grad 运算的过程需要使用到 elementwise_pow 算子的一阶反向和二阶反向算子，目前 paddle 暂未支持 elementwise_pow 的二阶算子，这个我们会列需求开发下。如果 ** 运算形式不是必须的，也可以改用其他方式来实现相同的功能。

**Comment by bitcjm** [comment]
可能改不了，应该是必须的。
