### ISSUE TITLE
怎么通过curl调用训练好的paddle serving 的模型

### ISSUE THREAD

**Issue by leoaaaaa** [PaddlePaddle/Paddle#42423]
### 请提出你的问题 Please ask your question

怎么通过curl调用已经在paddle serving上部署的模型？

通过curl的方式传入图片路径这个是传统python中的实现脚本：
![image](https://user-images.githubusercontent.com/90248905/166118099-d796ff2b-1ef5-47f0-a114-58865a3a4f14.png)
paddle serving 部署如下：
![image](https://user-images.githubusercontent.com/90248905/166118155-efd275fe-ebf6-4589-906e-69e800ec0c3f.png)

能不能把调用的命令告诉我下 ？

**Comment by windstamp** [comment]
请参考文档 https://www.paddlepaddle.org.cn/tutorials/projectdetail/2538249 看看是否可以帮您解决这个问题。
