### ISSUE TITLE
【论文复现赛】混合精度训练速度没有提高，GPU内存占用也没有降低

### ISSUE THREAD

**Issue by justld** [PaddlePaddle/Paddle#42436]
### bug描述 Describe the Bug

AISTUDIO GPU至尊Teslav100，使用AMP O1混合精度训练，混合精度训练和float32训练速度差不多（甚至稍微慢一些），且GPU占用率相同。

AISTUDIO连接：https://aistudio.baidu.com/aistudio/projectdetail/3927255?contributionType=1

具体内容：
1、不使用混合精度训练：250 iters耗时约81.29s（见aistudio小节7日志）；
2、使用混合精度训练(O1): 250 iters耗时约87.15s （见aistudio小节9日志）；

此外，使用混合精度和不使用，GPU占用内存都为4.6G左右。

**Comment by littletomatodonkey** [comment]
你好，这个无法访问，麻烦提供一个可访问的aistudio教程吧

**Comment by justld** [comment]
不好意思，刚刚没公开，现在ok了

**Comment by littletomatodonkey** [comment]
你好，看了下这个dataloader的share memory参数为false，建议设置为true，同时尽量调大num worker，减少reader耗时，这样的话可以更直观的看出混合精度的速度收益

**Comment by justld** [comment]
您好，已经修改share memory为true，num worker增大为8，但是混合精度和不适用混合精度速度依然几乎相同，且gpu显存也无明显降低（aistudio下面的gpu显存在无混合精度训练时4.7G左右，混合精度训练时5.8G左右，反而变大了？）。已更新aistudio版本，可以查看速度日志。

**Comment by littletomatodonkey** [comment]
你提供的fp32和fp16训练的代码似乎没有完全一致，我改了下（保持完全相同的forward、backward与minimize逻辑顺序），测试结果如下（32G的机器上测试的）

* 为了避免dataloader的影响，只用第一个batch的数据做forward
* 即使不考虑dataloader的影响，gpu利用率也只有不到50%，这个网络结构应该并非计算密集型的网络，所以几乎没有加速效果

```
fp32 ( GPU 5549MB)
time: 8.35334, iter: 50/40000, lr: 0.00998, loss: 0.35988, city loss: 0.10216, ade_loss: 0.25771
time: 16.34013, iter: 100/40000, lr: 0.00997, loss: 0.23954, city loss: 0.07235, ade_loss: 0.16718
time: 24.25429, iter: 150/40000, lr: 0.00996, loss: 0.18910, city loss: 0.05916, ade_loss: 0.12994
time: 32.20320, iter: 200/40000, lr: 0.00995, loss: 0.15915, city loss: 0.05100, ade_loss: 0.10815
time: 40.19052, iter: 250/40000, lr: 0.00994, loss: 0.13887, city loss: 0.04530, ade_loss: 0.09357


fp16 O1 (4919MB)

time: 8.00249, iter: 50/40000, lr: 0.00998, loss: 0.23394, city loss: 0.05704, ade_loss: 0.17690
time: 15.84159, iter: 100/40000, lr: 0.00997, loss: 0.14131, city loss: 0.03661, ade_loss: 0.10470
time: 23.63921, iter: 150/40000, lr: 0.00996, loss: 0.10705, city loss: 0.02870, ade_loss: 0.07835
time: 31.45239, iter: 200/40000, lr: 0.00995, loss: 0.08800, city loss: 0.02417, ade_loss: 0.06382
time: 39.31045, iter: 250/40000, lr: 0.00994, loss: 0.07568, city loss: 0.02118, ade_loss: 0.05450
time: 47.26301, iter: 300/40000, lr: 0.00993, loss: 0.06706, city loss: 0.01904, ade_loss: 0.04801
time: 55.11358, iter: 350/40000, lr: 0.00992, loss: 0.06067, city loss: 0.01741, ade_loss: 0.04326
time: 62.91418, iter: 400/40000, lr: 0.00990, loss: 0.05572, city loss: 0.01612, ade_loss: 0.03959
```

下面是我测试的脚本，可以看下

[train.zip](https://github.com/PaddlePaddle/Paddle/files/8608955/train.zip)
