### ISSUE TITLE
What is the difference of "imperative" mode and "eager" mode ?

### ISSUE THREAD

**Issue by gglin001** [PaddlePaddle/Paddle#42433]
### 请提出你的问题 Please ask your question

我注意到 paddle 有两个目录和动态图相关

https://github.com/PaddlePaddle/Paddle/tree/develop/paddle/fluid/imperative
和
https://github.com/PaddlePaddle/Paddle/tree/develop/paddle/fluid/eager

请问有相关的文档介绍这两部分的差别/架构吗?

**Comment by littletomatodonkey** [comment]
你好，目前eager目录下的动态图尚在开发中，目前还没有文档，感谢你的关注~

**Comment by gglin001** [comment]
2.3 release note

新动态图执行机制:
https://github.com/PaddlePaddle/Paddle/wiki/PaddlePaddle-2.3.0-Release-Note-CN#%E6%96%B0%E5%8A%A8%E6%80%81%E5%9B%BE%E6%89%A7%E8%A1%8C%E6%9C%BA%E5%88%B6

**Comment by gglin001** [comment]
问题: 
观察到 https://github.com/PaddlePaddle/Paddle/tree/develop/paddle/fluid/eager
同样会生成使用 `Tracer` 的调用, 我的理解这将会和 
https://github.com/PaddlePaddle/Paddle/tree/develop/paddle/fluid/imperative
的实现存在重复? 请问长期来说会抛弃 imperative 目录的部分吗?

**Comment by JiabinYang** [comment]
> 问题: 观察到 https://github.com/PaddlePaddle/Paddle/tree/develop/paddle/fluid/eager 同样会生成使用 `Tracer` 的调用, 我的理解这将会和 https://github.com/PaddlePaddle/Paddle/tree/develop/paddle/fluid/imperative 的实现存在重复? 请问长期来说会抛弃 imperative 目录的部分吗?

原则上Eager是不支持使用Tracer的，目前的情况只是一个兼容形态，后期会逐步抛弃imperative的内容

**Comment by gglin001** [comment]
> > 问题: 观察到 https://github.com/PaddlePaddle/Paddle/tree/develop/paddle/fluid/eager 同样会生成使用 `Tracer` 的调用, 我的理解这将会和 https://github.com/PaddlePaddle/Paddle/tree/develop/paddle/fluid/imperative 的实现存在重复? 请问长期来说会抛弃 imperative 目录的部分吗?
> 
> 原则上Eager是不支持使用Tracer的，目前的情况只是一个兼容形态，后期会逐步抛弃imperative的内容

got it, thx
