### ISSUE TITLE
请问torch.autograd.Variable在paddle中对应的是哪个api

### ISSUE THREAD

**Issue by huilin16** [PaddlePaddle/Paddle#42435]
### 请提出你的问题 Please ask your question

请问torch.autograd.Variable在paddle中对应的是哪个api呢，在算子映射文档中没有找到

**Comment by littletomatodonkey** [comment]
你好，可以设置tensor的stop gradient=false，让tensor的梯度可传递

**Comment by huilin16** [comment]
好的，多谢！






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/Paddle"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月2日(星期一) 下午5:45
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PaddlePaddle/Paddle] 请问torch.autograd.Variable在paddle中对应的是哪个api (Issue #42435)





 
你好，可以设置tensor的stop gradient=false，让tensor的梯度可传递
