### ISSUE TITLE
paddle_serving_server_gpu

### ISSUE THREAD

**Issue by leoaaaaa** [PaddlePaddle/Paddle#42430]
### 请提出你的问题 Please ask your question

我已经安装了paddle_serving_server_gpu 为什么说找不到模块？

1.官方文档：
![image](https://user-images.githubusercontent.com/90248905/166156661-a44cdc4d-517f-492a-91a1-3b31b4aa1600.png)
2.程勋报错：
![image](https://user-images.githubusercontent.com/90248905/166156681-cf621ef2-b1b3-4ee2-8b5b-7ae97b75008d.png)
3.vim 文件：
![image](https://user-images.githubusercontent.com/90248905/166156711-f91c1624-85ee-486d-b746-15bb6f669bd6.png)

我就想测试一下 并且返回结果实验部署

**Comment by littletomatodonkey** [comment]
你好，可以按照这个教程操作，安装下serving的相关whl包：https://github.com/PaddlePaddle/PaddleOCR/blob/release%2F2.4/deploy/pdserving/README_CN.md

**Comment by littletomatodonkey** [comment]
你好，需要将import的内容从`paddle_serving_server_gpu`修改为`paddle_serving_server`，我尝试了下，gpu和cpu版本的目录应该是统一了，我们也更新下文档~感谢反馈
