### ISSUE TITLE
Documentation about how to transfer learning by loading pre-trained model

### ISSUE THREAD

**Issue by reyoung** [PaddlePaddle/Paddle#4243]
The users want to get result asap. So `transfer learning` and related documentation is needed, since there are many pre-trained models we provided, but we did not show how to use the pre-trained models to bootstrap their model.

**Comment by NorthStar** [comment]
Question: By `transfer learning`, do you mean fine-tuning the pre-trained model on some new data?

**Comment by NorthStar** [comment]
Some of the steps are outlined here: https://github.com/PaddlePaddle/Paddle/issues/3288
