### ISSUE TITLE
关于PaddlePaddle中Tensor的严重bug

### ISSUE THREAD

**Issue by Victory8858** [PaddlePaddle/Paddle#42442]
### bug描述 Describe the Bug

Tensor中利用掩膜，当掩膜元素个数为一个时就会产生报错

```python
import paddle

# Step1: 原始数据
# bbox_annotation=[[538.53656006 , 1254.68884277, 730.73168945 , 1316.31591797, 39.02329636  , 8.],
#                  [343.41464233 , 1513.71520996, 502.43902588 , 1544.52880859, 40.67919540  , 8.]]  # 正常
bbox_annotation = [[538.53656006 , 1254.68884277, 730.73168945 , 1316.31591797, 39.02329636  , 8.]]  # 出现严重bug

# Step2: 转换成Tensor
bbox_annotation = paddle.to_tensor(bbox_annotation)

# Step3: 生成mask: bbox_annotation 最后一列为-1时为False, 其余值时为True, 对于上述给出的两个数据, 应分别为[True, True], [True]
mask = bbox_annotation[:, -1] != -1
print(mask)

# Step4: 根据掩膜得到输出, 由于bbox_annotation最后一列都不是-1, 所以正常应该原样输出
# mask = [True, True] 时正常输出结果, mask = [True] 时就报错, 即mask需要大于1个元素, 否则报错
bbox_annotation = bbox_annotation[mask]
print(bbox_annotation)


###### 报错信息 ######
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
~\AppData\Local\Temp/ipykernel_23320/3071330236.py in <module>
     15 # Step4: 根据掩膜得到输出, 由于bbox_annotation最后一列都不是-1, 所以正常应该原样输出
     16 # mask = [True, True] 时正常输出结果, mask = [True] 时就报错, 即mask需要大于1个元素, 否则报错
---> 17 bbox_annotation = bbox_annotation[mask]
     18 print(bbox_annotation)

D:\anaconda3\envs\paddle2-2\lib\site-packages\paddle\fluid\dygraph\varbase_patch_methods.py in __getitem__(self, item)
    592             # 1. Call _getitem_impl_ when item contains tensor.
    593             # Why not call a c++ function ? Because item can't be parsed when it contains tensor.
--> 594             return _getitem_impl_(self, item)
    595 
    596         else:

D:\anaconda3\envs\paddle2-2\lib\site-packages\paddle\fluid\variable_index.py in _getitem_impl_(var, item)
    457                                                          op_type),
    458             dtype=var.dtype)
--> 459         target_block.append_op(
    460             type=op_type,
    461             inputs=inputs,

D:\anaconda3\envs\paddle2-2\lib\site-packages\paddle\fluid\framework.py in append_op(self, *args, **kwargs)
   3161             # currently, we only support stop_gradient in dygraph mode.
   3162 
-> 3163             _dygraph_tracer().trace_op(type,
   3164                                        kwargs.get("inputs", {}),
   3165                                        kwargs.get("outputs", {}), attrs

D:\anaconda3\envs\paddle2-2\lib\site-packages\paddle\fluid\dygraph\tracer.py in trace_op(self, type, inputs, outputs, attrs, stop_gradient)
     41 
     42     def trace_op(self, type, inputs, outputs, attrs, stop_gradient=False):
---> 43         self.trace(type, inputs, outputs, attrs,
     44                    framework._current_expected_place(), self._has_grad and
     45                    not stop_gradient)

ValueError: (InvalidArgument) The dtype of Tensor in list must be int32 or int64, but received: 0 (at ..\paddle/fluid/operators/utils.h:85)
  [operator < slice > error]


### 其他补充信息 Additional Supplementary Information

_No response_

**Comment by littletomatodonkey** [comment]
你好，试下2.3.0rc0呢？我这边没有出现报错哈

![image](https://user-images.githubusercontent.com/14270174/166247953-173a42a8-c4f4-40ff-873d-2ffc114658f7.png)

**Comment by Victory8858** [comment]
你好，看到你这边数据是在CPU，GPU会报错的呢




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/Paddle"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月2日(星期一) 晚上10:19
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PaddlePaddle/Paddle] 关于PaddlePaddle中Tensor的严重bug (Issue #42442)





 
你好，试下2.3.0rc0呢？我这边没有出现报错哈

**Comment by littletomatodonkey** [comment]
你好，我测试了下，gpu没问题呀

![image](https://user-images.githubusercontent.com/14270174/166252652-ccf4c0f2-2f91-4c9a-8c14-c668ec27490b.png)

**Comment by Victory8858** [comment]
您好，请问这个bug有解决吗，遇到了很多问题，都是由于这一块引起，总之就是当元素个数为1就不行，其余就可以
我的解决办法是先把tensor转化成numpy，然后处理完再转化回paddle的tensor，但这样十分麻烦，需要修改很多程序，请问一下是什么原因呢，是paddle的bug还是什么？




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/Paddle"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月2日(星期一) 晚上10:36
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PaddlePaddle/Paddle] 关于PaddlePaddle中Tensor的严重bug (Issue #42442)





 
你好，我测试了下，gpu没问题呀

**Comment by littletomatodonkey** [comment]
你上面提供的复现代码，我这边使用2.3.0rc0，在gpu和cpu下都没有问题，你使用paddle2.3.0rc0看下呢？

**Comment by Victory8858** [comment]
您好，已切换到paddle2.3.0rc，确实没问题了，不过这确实是2.2.2中的一个bug




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/Paddle"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月4日(星期三) 中午11:17
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PaddlePaddle/Paddle] 关于PaddlePaddle中Tensor的严重bug (Issue #42442)





 
你上面提供的复现代码，我这边使用2.3.0rc0，在gpu和cpu下都没有问题，你使用paddle2.3.0rc0看下呢？

**Comment by littletomatodonkey** [comment]
嗯嗯，感谢反馈，我们也在持续优化~

**Comment by Victory8858** [comment]
你好，我在AI Studio以及本地环境都有试过，同样的报错，paddlepaddle版本=2.2.2




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/Paddle"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月2日(星期一) 晚上10:36
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PaddlePaddle/Paddle] 关于PaddlePaddle中Tensor的严重bug (Issue #42442)





 
你好，我测试了下，gpu没问题呀
