### ISSUE TITLE
paddle有专注于知识图谱和多模态的模块吗？

### ISSUE THREAD

**Issue by bbbxixixixi** [PaddlePaddle/Paddle#42444]
### 请提出你的问题 Please ask your question

比如paddleocr、paddleseg一类的

**Comment by littletomatodonkey** [comment]
你好，多模态的话可以参考：https://github.com/njustkmg/PaddleMM
知识图谱相关的内容可以参考paddlenlp: https://www.paddlepaddle.org.cn/textToKnowledge
