### ISSUE TITLE
多卡如何保存模型？

### ISSUE THREAD

**Issue by 670133189** [PaddlePaddle/Paddle#42449]
### 请提出你的问题 Please ask your question

请教：多卡如何保存模型？能训练，一旦保存模型则提示显存不足。

save_mode_prefix = f"{save_mode_dir}/{epo}"

model_static = paddle.jit.to_static(
     model_original,
     input_spec=[InputSpec(shape=input_spec_img.shape, dtype="float32")]
)

paddle.jit.save(layer=model_static, path=save_mode_prefix)

错误提示：
Out of memory error on GPU 2. Cannot allocate 28.125244MB memory on GPU 2, 31.694946GB memory has been allocated and available memory is only 24.875000MB.

**Comment by tink2123** [comment]
如果希望保存训练参数，建议使用 paddle.static.save 接口，可以参考：
https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/static/save_cn.html#save
