### ISSUE TITLE
【飞桨论文复现挑战赛】论文复现所需的GPU资源较多，Paddle会在跑通参考代码之后提供这些资源吗？ 

### ISSUE THREAD

**Issue by wa008** [PaddlePaddle/Paddle#42457]
### 请提出你的问题 Please ask your question

已经报名了[DEBERTA](https://arxiv.org/pdf/2006.03654.pdf) 论文复现，但原paper中说训练需要 96 块 V100 卡，训练20天的时间。。。
这些资源Paddle会在后期提供的么？

**Comment by ZHUI** [comment]
> ### 请提出你的问题 Please ask your question
> 已经报名了[DEBERTA](https://arxiv.org/pdf/2006.03654.pdf) 论文复现，但原paper中说训练需要 96 块 V100 卡，训练20天的时间。。。 这些资源Paddle会在后期提供的么？

可以先模型对齐，跑通finetune。预训练耗时较多，可以放着。

**Comment by wa008** [comment]
> > ### 请提出你的问题 Please ask your question
> > 已经报名了[DEBERTA](https://arxiv.org/pdf/2006.03654.pdf) 论文复现，但原paper中说训练需要 96 块 V100 卡，训练20天的时间。。。 这些资源Paddle会在后期提供的么？
> 
> 可以先模型对齐，跑通finetune。预训练耗时较多，可以放着。

了解了，多谢

**Comment by Ligoml** [comment]
你好，根据复现赛的流程说明，你可以在跑通参考代码后申请加入vip群，答疑和算力申请都可以在群中进行：https://aistudio.baidu.com/aistudio/competition/detail/205/0/introduction
<img width="554" alt="image" src="https://user-images.githubusercontent.com/39876205/166912446-86535076-7511-460a-ad18-71f777cb175b.png">
