### ISSUE TITLE
DeepSpeech2 thown error "File contains data in an unimplemented format"

### ISSUE THREAD

**Issue by jacquesqiao** [PaddlePaddle/Paddle#4247]
We downloaded the librespeech model for speech recognition, but soundfile does not seem to be working with the code provided. We have pip installed soundfile and it seems to import just fine, but the methods do not seem to be working. Is there any light that could be shed on our problem?Specifically, https://github.com/PaddlePaddle/models/blob/develop/deep_speech_2/data/librispeech/librispeech.py gives error "File contains data in an unimplemented format." in line 103

**Comment by jacquesqiao** [comment]
> what is the format of your sound file? is it can be convert to a `.flac` format?
use the tool like https://audio.online-convert.com/convert-to-flac

**Comment by ganzhong007** [comment]
the same problem I meet.
anyone can tell me how to resolve it ?

**Comment by zhxfl** [comment]
the same problem I meet.
anyone can tell me how to resolve it ?

**Comment by muntasir2000** [comment]
I had the same issue. I solved it by installing libsndfile.
http://www.mega-nerd.com/libsndfile/files/libsndfile-1.0.28.tar.gz

To install - 
```
tar -zxvf libsndfile-1.0.28.tar.gz
cd libsndfile-1.0.28
./configure > /dev/null && make > /dev/null && make install > /dev/null
```

**Comment by PasaOpasen** [comment]
@ganzhong007
> the same problem I meet.
> anyone can tell me how to resolve it ?

have u solved this problem?

**Comment by Always-prog** [comment]
Hmm. I have a similar problem

**Comment by llllaaapp** [comment]
have u solved this problem?

**Comment by Always-prog** [comment]
@llllaaapp  I've already forgotten 🙂

**Comment by Always-prog** [comment]
But as I see @muntasir2000 solved it by installing http://www.mega-nerd.com/libsndfile/files/libsndfile-1.0.28.tar.gz
