### ISSUE TITLE
这里面conv2搭建中padding＝0是same还是valid

### ISSUE THREAD

**Issue by hellochengyan** [PaddlePaddle/Paddle#42482]
### 文档链接&描述 Document Links & Description

这里面conv2搭建中padding＝0是same还是valid
![Uploading image.png…]()

**Comment by joey12300** [comment]
@hellochengyan 直接使用该公式进行pad。padding_height = padding_width = padding（整数）
![image](https://user-images.githubusercontent.com/10826371/166944526-8ed3cbf1-ee0f-48c1-945c-bc33ab5c4540.png)

**Comment by wangxinxin08** [comment]
padding=0表示"VALID"，可以从公式中看出
