### ISSUE TITLE
搞一个像样的python教程吧，看了官网好几个不是太旧就是不太行

### ISSUE THREAD

**Issue by ghost** [PaddlePaddle/Paddle#42487]
### 需求描述 Feature Description

任务目标（请描述你正在做的项目是什么，如模型、论文、项目是什么？）; <br /> 需求场景（请描述你的项目中为什么需要用此功能）;  <br /> 功能描述（请简单描述或设计这个功能）

**Comment by joey12300** [comment]
您好，请问可以举几个例子吗？试一下选择2.2版本，文档会更新一些
![image](https://user-images.githubusercontent.com/10826371/166886204-90d68deb-755c-4485-a786-7cfdaa536e88.png)

**Comment by Ligoml** [comment]
可以贴几个链接给我们看看吗？develop的文档应该是最新的

**Comment by ghost** [comment]
> 

2.2的文档里应该没有python教程吧

**Comment by ghost** [comment]
> 可以贴几个链接给我们看看吗？develop的文档应该是最新的

文档里应该没有python教程，之前在官网看过应该是两个，一个应该是僵硬的机翻，一个感觉就很难学

**Comment by Ligoml** [comment]
> > 可以贴几个链接给我们看看吗？develop的文档应该是最新的
> 
> 文档里应该没有python教程，之前在官网看过应该是两个，一个应该是僵硬的机翻，一个感觉就很难学

嗯？抱歉我没有理解什么意思，你是指官网文档里没有python教程希望增加呢，还是对现有的python教程不满意呢？如果是后者，可以贴一下链接吗？我也好确认是哪些内容需要新增或更新~

**Comment by Ligoml** [comment]
python教程我们更推荐在aistudio上学习哈：https://aistudio.baidu.com/aistudio/course/introduce/25763
