### ISSUE TITLE
Transfer Learning for DS2

### ISSUE THREAD

**Issue by reyoung** [PaddlePaddle/Paddle#4248]
Users want to use deep speech 2 model for transfer learning. Users want to extract the speech features by `DS2` model, just like they extract image features by VGGNet.

And then, many interesting things could be done, for example.

* We can compare the similarity of two speakers. The difference will show how clear the input speech was, thus allowing us to determine how clear or unclear one's pronunciation of a phoneme may be.

**Comment by NorthStar** [comment]
If we have a general enough guide on `transfer learning`, this should be a duplicate of #4243 .

**Comment by NorthStar** [comment]
Duplicate of #4243
