### ISSUE TITLE
这里面conv2搭建问题。

### ISSUE THREAD

**Issue by hellochengyan** [PaddlePaddle/Paddle#42481]
### 文档链接&描述 Document Links & Description

这里面conv2搭建中padding＝0是same还是valid

**Comment by joey12300** [comment]
@hellochengyan 直接使用该公式进行pad。padding_height = padding_width = padding（整数）
![image](https://user-images.githubusercontent.com/10826371/166944526-8ed3cbf1-ee0f-48c1-945c-bc33ab5c4540.png)

**Comment by joey12300** [comment]
@hellochengyan 直接使用该公式进行pad。padding_height = padding_width = padding（整数）
![image](https://user-images.githubusercontent.com/10826371/166944746-83c90951-6433-4020-b2da-0f71d2daacee.png)
