### ISSUE TITLE
SystemError: (Fatal) Blocking queue is killed because the data reader raises an exception.

### ISSUE THREAD

**Issue by 875052544** [PaddlePaddle/Paddle#42514]
### 请提出你的问题 Please ask your question

RuntimeError: DataLoader 1 workers exit unexpectedly, pids: 12711
    return next(self.loader)
  File "/root/miniconda3/lib/python3.8/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 697, in __next__
    data = self._reader.read_next_var_list()
SystemError: (Fatal) Blocking queue is killed because the data reader raises an exception.
  [Hint: Expected killed_ != true, but received killed_:1 == true:1.] (at /paddle/paddle/fluid/operators/reader/blocking_queue.h:166)
  这是什么问题 我使用的数据集格式是coco 已经在别的torch版本模型正确运行 格式应该是没有错误

**Comment by joey12300** [comment]
@875052544 请问你的paddle版本是多少？方便提供一个最小可复现代码吗？

**Comment by 875052544** [comment]
我已经解决这个问题了，现在有一个新的问题，ppyoloe能输入比640大的图片吗？如3840*5760吗？我尝试输入网络，但是没有成功




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/Paddle"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月5日(星期四) 晚上10:15
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PaddlePaddle/Paddle] SystemError: (Fatal) Blocking queue is killed because the data reader raises an exception. (Issue #42514)





 
@875052544 请问你的paddle版本是多少？方便提供一个最小可复现代码吗？

**Comment by 875052544** [comment]
我的paddle是2.2.2，再次出现了这个问题，好像图片的尺寸过大就会出现这个情况，我同时尝试了640X640，还有3840X3840的图片尺寸，在图片数量少的时候3840X3840也能成功运行，是不是因为内存泄露的原因




------------------ 原始邮件 ------------------
发件人:                                                                                                                        "PaddlePaddle/Paddle"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月5日(星期四) 晚上10:15
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PaddlePaddle/Paddle] SystemError: (Fatal) Blocking queue is killed because the data reader raises an exception. (Issue #42514)





 
@875052544 请问你的paddle版本是多少？方便提供一个最小可复现代码吗？

**Comment by joey12300** [comment]
> 我的paddle是2.2.2，再次出现了这个问题，好像图片的尺寸过大就会出现这个情况，我同时尝试了640X640，还有3840X3840的图片尺寸，在图片数量少的时候3840X3840也能成功运行，是不是因为内存泄露的原因

不成功是指显存不足了？一般图片放到模型里都需要resize到模型指定的输入大小

**Comment by 875052544** [comment]
我原图太大了 现在我先resize再训练变可以了
现在我想尝试复现一些模型剪枝和蒸馏的论文，有一些大致的流程文档可以提供吗？如有还有你们模型敏感度的原理文档就更好了，我没找到，可否提供，万分感谢





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/Paddle"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月10日(星期二) 下午5:08
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PaddlePaddle/Paddle] SystemError: (Fatal) Blocking queue is killed because the data reader raises an exception. (Issue #42514)





  
我的paddle是2.2.2，再次出现了这个问题，好像图片的尺寸过大就会出现这个情况，我同时尝试了640X640，还有3840X3840的图片尺寸，在图片数量少的时候3840X3840也能成功运行，是不是因为内存泄露的原因
  
不成功是指显存不足了？一般图片放到模型里都需要resize到模型指定的输入大小

**Comment by Phoenix8215** [comment]
> 

怎么解决的？
