### ISSUE TITLE
paddle自定义cuda算子问题？

### ISSUE THREAD

**Issue by Sakura176** [PaddlePaddle/Paddle#42525]
### 请提出你的问题 Please ask your question

我将倒角距离的torch算子改成paddle版本，但是出现下列错误：
`File "unit_test.py", line 2, in 
    import dist_chamfer_3D
  File "/home/aistudio/work/PointCloudCompletion/extentions/chamfer_dist/dist_chamfer_3D.py", line 23, in 
    import chamfer
ImportError: /home/aistudio/work/PointCloudCompletion/extentions/chamfer_dist/chamfer.so: undefined symbol: _Z20chamfer_cuda_forwardN6paddle6TensorES0_`
pytorch出现这个错误通常是版本不对应导致，我尝试了两种环境：

- 自己的电脑 paddle 2.2.2 cuda 11.2

- AI studio paddle 2.2.2 cuda 10.1
两种环境都会出现该错误，算子编译过程没有出现错误，为什么会这样？

**Comment by TCChenlong** [comment]
可以提供一下 AIStudio 项目么？或者是哪段代码报错？目前的信息无法判断

**Comment by Sakura176** [comment]
代码在这个项目里 [chamfer_cuda](https://aistudio.baidu.com/aistudio/projectdetail/3977265?shared=1) notebook上有运行的命令

**Comment by hjlllll** [comment]
我看.cc 文件中没有定义 PD_BUILD_OP,所以没法调用?
