### ISSUE TITLE
如何提高SSD的剪枝度？

### ISSUE THREAD

**Issue by malcolm-wang** [PaddlePaddle/Paddle#42524]
### 请提出你的问题 Please ask your question

![123](https://user-images.githubusercontent.com/104298741/167049579-6136b49e-19b9-4ac4-9779-bce3de2a5010.png)
为什么这个的pruned ratio 只有0.045左右啊，yolov3的这个都可以达到30%几。这个配置文件该怎么改呢？按照yolo的数据，最后的pruned ratio只有0.005，而改变参数和层数最多只有0.045，请问如何更改此配置文件使得在训练ssd时的pruned ratio达到0.1以上？

**Comment by ghostxsl** [comment]
可以参考一下PaddleSlim的文档：https://github.com/PaddlePaddle/PaddleSlim/blob/develop/docs/zh_cn/api_cn/overview.md#%E5%89%AA%E6%9E%9D

**Comment by malcolm-wang** [comment]
> 可以参考一下PaddleSlim的文档：https://github.com/PaddlePaddle/PaddleSlim/blob/develop/docs/zh_cn/api_cn/overview.md#%E5%89%AA%E6%9E%9D

 你好，文档里面没有说明PaddleDetection里面应该如何修改如上图所示的配置文件以达到较合适的剪枝率。如果修改配置文件中的比例的话，为什么在yolov3里面可以达到30%+的剪枝率，而在ssd里面就特别低呢？
![image](https://user-images.githubusercontent.com/104298741/167069608-86d7a5cd-85e3-4e64-9c49-a35f7d082b50.png)

**Comment by ghostxsl** [comment]
建议到 https://github.com/PaddlePaddle/PaddleDetection/issues 下提issue
