### ISSUE TITLE
Paddle C++推理库是否支持动态图算子？ Does Paddle support dynamic graph operators in C++ inference API

### ISSUE THREAD

**Issue by lanking520** [PaddlePaddle/Paddle#42523]
### Description

From the Paddle 2.3.0-rc0, it seemed the dynamic graph operators are supported for training in C++. We are wondering if inference API also can call these operators? If so, is there any code reference.

This feature is going to be helpful for us to standardize the pre/postprocessing for model inference.

Paddle目前可以用C++推理库来调用动态图算子么？

**Comment by ghostxsl** [comment]
可以

**Comment by lanking520** [comment]
> 可以

那想问一下具体应该使用哪个头文件来调用呢？

**Comment by ghostxsl** [comment]
可以参考官方文档：https://www.paddlepaddle.org.cn/inference/v2.3/quick_start/workflow.html

**Comment by lanking520** [comment]
> 可以参考官方文档：https://www.paddlepaddle.org.cn/inference/v2.3/quick_start/workflow.html

文档里并没有任何与Tensor算子有关的操作、，除了基本的复制，reshape等。想问具体到Tensor.add 等操作应该如何做呢？

**Comment by ghostxsl** [comment]
你直接在组网的时候调用就可以了

**Comment by lanking520** [comment]
> 你直接在组网的时候调用就可以了

这个不是静态图算子么？所以动态图算子是没有办法直接拿来用的对不对？如果用户有自己前后处理的逻辑，应该怎么做呢

**Comment by ghostxsl** [comment]
前后处理你可以融进网络内部做，直接在模型导出的时候就附带进模型里。如果不行，请在C++端单独编写，单独编写前后处理跟框架无关

**Comment by lanking520** [comment]
> 前后处理你可以融进网络内部做，直接在模型导出的时候就附带进模型里。如果不行，请在C++端单独编写，单独编写前后处理跟框架无关

感谢！明白了，结论就是2.3.1带的C++动态图算子是没办法在推理库中调用的。目前依然是只支持静态图输入输出。

**Comment by TCChenlong** [comment]
@Shixiaowei02 麻烦看下这个问题，目前是否是支持的，以及支持的情况
