### ISSUE TITLE
paddle2.3.0-rc0的paddle.sin操作不支持求梯度吗  paddle 2.2.2是支持的

### ISSUE THREAD

**Issue by simonsLiang** [PaddlePaddle/Paddle#42528]
### bug描述 Describe the Bug

复现代码
import paddle
#2.3.0-rc0
x = paddle.to_tensor([1.1,2.2],dtype='float32',stop_gradient=False)
y = paddle.sin(x)
out = paddle.grad(y,x,grad_outputs=paddle.ones_like(y),create_graph=True)[0]

可否尽快修复一下

### 其他补充信息 Additional Supplementary Information

错误输出：
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
/tmp/ipykernel_233/3995367064.py in <module>
      2 x = paddle.to_tensor([1.1,2.2],dtype='float32',stop_gradient=False)
      3 y = paddle.sin(x)
----> 4 out = paddle.grad(y,x,grad_outputs=paddle.ones_like(y),create_graph=True)[0]

<decorator-gen-165> in grad(outputs, inputs, grad_outputs, retain_graph, create_graph, only_inputs, allow_unused, no_grad_vars)

/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/wrapped_decorator.py in __impl__(func, *args, **kwargs)
     23     def __impl__(func, *args, **kwargs):
     24         wrapped_func = decorator_func(func)
---> 25         return wrapped_func(*args, **kwargs)
     26 
     27     return __impl__

/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/framework.py in __impl__(*args, **kwargs)
    393         assert _non_static_mode(
    394         ), "We only support '%s()' in dynamic graph mode, please call 'paddle.disable_static()' to enter dynamic graph mode." % func.__name__
--> 395         return func(*args, **kwargs)
    396 
    397     return __impl__

/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/base.py in grad(outputs, inputs, grad_outputs, retain_graph, create_graph, only_inputs, allow_unused, no_grad_vars)
    661         return core.dygraph_partial_grad(
    662             inputs, outputs, grad_outputs, no_grad_vars, place, create_graph,
--> 663             retain_graph, allow_unused, only_inputs)
    664 
    665 

RuntimeError: (NotFound) The Op sin_grad doesn't have any grad op. If you don't intend calculating higher order derivatives, please set `create_graph` to False.
  [Hint: double_grad_node should not be null.] (at /paddle/paddle/fluid/imperative/partial_grad_engine.cc:923)

**Comment by simonsLiang** [comment]
2.1.2的也不支持paddle.sin求梯度  2.2.2的支持 不过2.2.2的paddle.grad不正确  2.2.2的paddle.grad计算结果和2.1.2以及2.3.0的差别很大

**Comment by simonsLiang** [comment]
补充：我需要计算高阶梯度

**Comment by TCChenlong** [comment]
目前暂时不支持，请问下你需要支持的几阶？以及具体的使用场景？方便我们内部评估，以高优支持

**Comment by levi131** [comment]
目前sin还没有支持高阶导数，相关工作已经在我们的计划上，欢迎保持关注。
