### ISSUE TITLE
paddle与Ascend910的适配问题

### ISSUE THREAD

**Issue by leelinglin** [PaddlePaddle/Paddle#42539]
### 请提出你的问题 Please ask your question

请问paddle(非paddle-lite)里哪些函数能够运行在NPU上？之前运行在GPU上的程序按照官方说明编译paddle，paddle.utils.run_check() 也正常，但是程序里的place修改成NPU后，运行速度特别慢，感觉不正常，在官方文档中没有找到任务相关说明

**Comment by Aganlengzi** [comment]
@leecuijiao 运行的时候可以使用npu-smi info关注下HBM显存占用和AICore利用率，或使用GLOG_v=4运行程序关注使用的算子是否已经支持NPU版本(如果不支持，日志中会出现missing fallback字样)。

**Comment by leelinglin** [comment]
根据您的提示，设置GLOG_v=4，在日志中发现paddle.fluid.layers.embedding函数运行在CPU上 missing NPU kernel: lookup_table, expected_kernel_key:data_type[float]:data_layout[Undefined(AnyLayout)]:place[Place(npu:0)]:library_type[PLAIN], fallbacking to CPU one!
missing NPU kernel: lookup_table_grad, expected_kernel_key:data_type[float]:data_layout[Undefined(AnyLayout)]:place[Place(npu:0)]:library_type[PLAIN], fallbacking to CPU
请问这种情况应该怎样处理呢？
@Aganlengzi

**Comment by Aganlengzi** [comment]
> paddle.fluid.layers.embedding

是否可以换成`paddle.nn.functional.embedding`，是新版本，npu算子支持。

**Comment by leelinglin** [comment]
请问paddle.nn.functional.embedding支持静态图吗，还是需要使用paddle.static.nn.embedding（是否支持NPU）

**Comment by Aganlengzi** [comment]
> 请问paddle.nn.functional.embedding支持静态图吗，还是需要使用paddle.static.nn.embedding（是否支持NPU）

paddle.static.nn.embedding 支持，可通过查看源码看对应的实现中是否为lookup_table_v2，v2版本支持npu

**Comment by leelinglin** [comment]
修改成paddle.static.nn.embedding后日志中未发现有missing fallback的算子，但是模型运行速度超级慢（比GPU慢几十倍），可能是什么原因呢，看AIcore 及HBM显存均有占用

**Comment by Aganlengzi** [comment]
> 修改成paddle.static.nn.embedding后日志中未发现有missing fallback的算子，但是模型运行速度超级慢（比GPU慢几十倍），可能是什么原因呢，看AIcore 及HBM显存均有占用

可以运行一段时间看下，目前算子接入方式有冷启动编译阶段，另外不清楚您使用的模型是否可以发挥AICore性能。
也可以尝试混合精度。

**Comment by leelinglin** [comment]
观测日志应该还是有一些算子运行在CPU上，能帮忙看下是哪个函数吗，是op_type：Fill ?
![image](https://user-images.githubusercontent.com/17920817/167761975-2674815b-6984-48da-997c-fe659da5d8f6.png)
@Aganlengzi

**Comment by yang131313** [comment]
你好，我想咨询一下关于在Ascend 硬件上编译paddle的问题，您方便联系我一下嘛：qq：928472889

**Comment by Aganlengzi** [comment]
> op_type：Fill 

@leecuijiao
你截图里圈出来的应该是正常的HOST与Device的交互，没有missing和fallback字样的话是算子跑在昇腾910卡了。
