### ISSUE TITLE
AttributeError: module 'paddle' has no attribute 'batch'

### ISSUE THREAD

**Issue by BrunaFortunato-eng** [PaddlePaddle/Paddle#42551]
### bug描述 Describe the Bug

import paddle
from paddleocr import PaddleOCR
ocr = PaddleOCR(use_angle_cls=True,lang='en') # need to run only once to load model into memory
img_path = 'https://4ww1y37tl91gmoej12r01u1c-wpengine.netdna-ssl.com/wp-content/uploads/2019/08/TextDocument.png'
result = ocr.ocr(img_path, cls=True)
for line in result:
    print(line)

### 其他补充信息 Additional Supplementary Information

---------------------------------------------------------------------------
      1 import paddle
----> 2 from paddleocr import PaddleOCR

~\Anaconda3\lib\site-packages\paddleocr\paddleocr.py in <module>
     32 ppstructure = importlib.import_module('.', 'ppstructure')
     33 
---> 34 from tools.infer import predict_system
     35 from ppocr.utils.logging import get_logger
     36 

~\Anaconda3\lib\site-packages\paddleocr\tools\infer\predict_system.py in <module>
     29 import logging
     30 from PIL import Image
---> 31 import tools.infer.utility as utility
     32 import tools.infer.predict_rec as predict_rec
     33 import tools.infer.predict_det as predict_det

~\Anaconda3\lib\site-packages\paddleocr\tools\infer\utility.py in <module>
     22 from PIL import Image, ImageDraw, ImageFont
     23 import math
---> 24 from paddle import inference
     25 import time
     26 from ppocr.utils.logging import get_logger

~\Anaconda3\lib\site-packages\paddle\inference\__init__.py in <module>
     13 # limitations under the License.
     14 
---> 15 from ..fluid.inference import Config  # noqa: F401
     16 from ..fluid.inference import DataType  # noqa: F401
     17 from ..fluid.inference import PlaceType  # noqa: F401

~\Anaconda3\lib\site-packages\paddle\fluid\__init__.py in <module>
     50 from . import trainer_desc
     51 
---> 52 from . import io
     53 from . import evaluator
     54 from . import initializer

~\Anaconda3\lib\site-packages\paddle\fluid\io.py in <module>
     49 from paddle.fluid.framework import static_only
     50 
---> 51 batch = paddle.batch
     52 
     53 __all__ = [

AttributeError: module 'paddle' has no attribute 'batch'

**Comment by nemonameless** [comment]
您好，从报错信息上看，错误可能是由于您本地安装的PaddlePaddle版本过低，建议升级下，测试过2.2.2版本是可以的。具体用法可以参照官网[batch](https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/batch_cn.html#batch)的API文档，如未能解决还请继续反馈，谢谢。
