### ISSUE TITLE
如何使paddle载入一个keras的预训练模型？

### ISSUE THREAD

**Issue by crazyxiaoj** [PaddlePaddle/Paddle#42550]
### 请提出你的问题 Please ask your question

我现在下载了keras的预训练模型h5文件，通过`h5py`包，可以取得我需要的权重信息。
我该怎么做才能将这些权重信息，写入paddle中的layer中呢？

**Comment by nemonameless** [comment]
您好，可以尝试做key-value映射转成pdparams格式的权重。
预训练权重本质上是一个字典dict，有key和value，key就是模型的模块的名字。将keras的预训练模型权重的key和shape打印下，将paddle的同模型的key和shape打印下，可以根据shape做下匹配得到一份weights map的权重对应表格之类的，比如两列权重key的名字，左边一列是keras模型权重的key，右边一列是paddle模型的key，然后根据这份weights map将预训练权重字典dict换个key存下来，存的时候用paddle.save就能保存成pdparams。
