### ISSUE TITLE
【PFCC-Roadmap】总览

### ISSUE THREAD

**Issue by luotao1** [PaddlePaddle/Paddle#42571]
飞桨成立了 [PFCC(Paddle Framework Contributor Club)](https://github.com/PaddlePaddle/community/tree/master/pfcc)，是一个有兴趣、正在、或者已经为飞桨开源框架做开源贡献的贡献者而成立的虚拟组织，在这里，飞桨开源框架的贡献者进行讨论、交流和分享，并为飞桨框架做出持续的贡献。欢迎你持续关注并加入（我们会定向邀请 Paddle repo 提交PR的开发者加入）。

为了让大家能深入地了解飞桨、在飞桨收获更多成长、解决更有挑战性的问题，飞桨团队计划将正在开展的重点工作和技术方向陆续发布。每个技术方向都会有工程师支持，和该方向中的同学一起确定目标、规划和分工，希望PFCC的成员能逐渐成为方向骨干甚至是带头人，带领更多人一起开发。

以下是目前开放的技术方向，如果有想开发的方向不在这几个范围，可以在 PFCC 中反馈。

- https://github.com/PaddlePaddle/Paddle/issues/42620 ：
  - 飞桨框架自开源以来，就提供了高质量的中英文文档。目前，飞桨框架文档包含使用指南、应用实践、API文档等多种类型的文档。但是，文档工作细致又宏大，有许多地方，飞桨框架文档做的还不够好。因此我们希望能进一步提升文档质量，在这个方向中，你可以完成文档的评估，找出文档中存在的种种问题，并提ISSUE反馈；也可以自己提PR，修复已知的各类问题；还可以新增应用实践文档，给其他的开发者参考学习。
- https://github.com/PaddlePaddle/Paddle/issues/42532 ：
  - 在飞桨开发早期，API 的测试规范没有目前完备，因此存在有些 API 单测缺失的问题。本方向主要面向：增强单测case，补齐  API  缺失的某些类型的单测 case。在补全单测的过程中，如果发现有 API 有 bug（由于缺失单测而没有发现的bug），可以提 ISSUE 报 BUG，反馈这个问题；如果愿意修复，可以再提 PR 修复该问题。
- https://github.com/PaddlePaddle/Paddle/issues/42286 ：
  - Op性能是飞桨框架重要功能之一；通过Op Benchmark，我们发现有些 Op 性能不够好，没有充分利用硬件算力；我们内部在不断地进行优化。本方向主要开发：C++ 算子在CPU/GPU 的性能优化，过程中需要和飞桨高性能专家/Intel CPU 专家/NV GPU专家共同交流和探讨。
- https://github.com/PaddlePaddle/Paddle/issues/42490 ： 
  - 飞桨已经在多款AI 训练硬件上全面支持训练和推理任务，并适配了80+模型在曙光 C86加速卡上的运行，以及 30+ 模型在昇腾910芯片上的运行，我们希望进一步扩大这些硬件支持的算子范围以便在这些硬件上支持更多模型训练和推理。本方向主要开发：昇腾910算子适配、海光DCU算子适配等。如果对飞桨框架+AI 硬件适配感兴趣，可以加入这个方向，深入了解飞桨的硬件适配方案，开发飞桨算子在不同硬件上的实现，并尝试进行算子和模型的性能优化，全面提升端到端的软硬结合领域的实战经验。  
- https://github.com/PaddlePaddle/Paddle/issues/42699 ：
  - 飞桨现有算子已经能较完整地支持float32、float64、int32、int64、bool等常用数据类型，同时部分算子也支持 complex64、complex128、fp16、bf16、int8 等数据类型，我们希望进一步扩大支持后面这些数据类型的算子范围，让飞桨能支持更多应用场景的需求。本方向主要开发：和飞桨专家一起扩展现有算子的功能，开发支持complex64、complex128、fp16、bf16、int8 等数据类型，并解决制约这些数据类型支持的基础问题。

**Comment by sunzhongkai588** [comment]
刚教授宣传完paddle就出这活动了！！冲了xdm
