### ISSUE TITLE
visualdl可视化数据失败

### ISSUE THREAD

**Issue by MrYuzzzz** [PaddlePaddle/Paddle#42585]
### 请提出你的问题 Please ask your question

想用visualdl可视化参数，但是打不开网页是为何？用的是chrome浏览器
![image](https://user-images.githubusercontent.com/101876020/167307029-ae632bb5-b353-4c3c-adc6-4387eb533f01.png)
![image](https://user-images.githubusercontent.com/101876020/167307052-47fd5be2-7c38-465f-923a-dac4b3582093.png)

**Comment by MrYuzzzz** [comment]
保存的路径也检查过
![image](https://user-images.githubusercontent.com/101876020/167307148-079cccc8-9979-4346-9b02-3b5d8b8b86d8.png)
bao'cun

**Comment by gongel** [comment]
你好，尝试换端口和换浏览器。

**Comment by gongel** [comment]
你好，`logdir`给个绝对路径吧

**Comment by gongel** [comment]
你好，暂时关闭issue，有问题随时重开。
