### ISSUE TITLE
用paddlepaddel-gpu安装后，程序报错

### ISSUE THREAD

**Issue by leoaaaaa** [PaddlePaddle/Paddle#42583]
### 问题描述 Issue Description

用paddlepaddel-gpu安装后，调用模型出错
安装成功 cuda-11.2 的 paddlepaddel-gpu
![image](https://user-images.githubusercontent.com/90248905/167298597-4f0fb351-0ef8-4ea1-be6d-2ff265cbe2d8.png)
报错：
![image](https://user-images.githubusercontent.com/90248905/167298615-ffcf654a-a238-4915-9865-77c704789092.png)
显卡：
![image](https://user-images.githubusercontent.com/90248905/167298623-efa9d252-d64d-42eb-b47d-e76a7badcfb7.png)
user/local 下倒是没找到cuda，是没安装成功？
![image](https://user-images.githubusercontent.com/90248905/167298728-759a1372-f803-46d1-965c-62d691bca662.png)
nvcc如下：
![image](https://user-images.githubusercontent.com/90248905/167298747-dbcb84c1-6545-4d35-8574-0f971ffab0c5.png)

### 版本&环境信息 Version & Environment Information

paddle 11.2

**Comment by RainFrost1** [comment]
根据nvcc， 安装的cuda版本是9.1，而安装的是cuda11.2 版本的Paddle，所以可能会报错。建议升级cuda后，再安装合适版本的paddle
