### ISSUE TITLE
使用PaddleOCR进行训练时使用相应的命令结果得到

### ISSUE THREAD

**Issue by annabergite** [PaddlePaddle/Paddle#42581]
### 请提出你的问题 Please ask your question

![image](https://user-images.githubusercontent.com/50126267/167296588-d99db2e2-e691-454b-82a7-3f25d1547365.png)
使用csdn链接https://blog.csdn.net/u013171226/article/details/115179480 进行2.5开始训练时（没有使用python3而是python命令）出现了如上问题，属性错误，没有相应的属性"_device_id"，并且发现了本人的电脑没有gpu的一些监控数据，电脑帧数也无法检测（使用GeForce experience进行测试使用）
个人的电脑配置为：paddlepaddle版本是2.2.2，python版本是3.8.13，cuda版本是11.2，开发平台是Windows anaconda虚拟环境，标注工具是ppocrLabel，显卡版本是gtx 3060 laptop

**Comment by RainFrost1** [comment]
可以先咨询一下[PaddleOCR](https://github.com/PaddlePaddle/PaddleOCR)同学，看一下训练命令是否正确，是否是安装了paddle cpu版本或者paddle-gpu版本是否没有安装正确

**Comment by annabergite** [comment]
> 可以先咨询一下[PaddleOCR](https://github.com/PaddlePaddle/PaddleOCR)同学，看一下训练命令是否正确，是否是安装了paddle cpu版本或者paddle-gpu版本是否没有安装正确

好的，谢谢大佬
