### ISSUE TITLE
How to extend the word dictionary from a pre-trained model and fine-tune it.

### ISSUE THREAD

**Issue by reyoung** [PaddlePaddle/Paddle#4258]
Users want to transfer learning from a pre-trained model, or fine tune the pre-trained model on their own dataset. Need a documentation about `How to extend the word dictionary from a pre-trained model`.

* https://hackmit-baidu.slack.com/archives/C727D998C/p1505606882000032

**Comment by NorthStar** [comment]
Dups into #4243
