### ISSUE TITLE
paddlepaddl安装失败（gpu版）

### ISSUE THREAD

**Issue by Vincent630** [PaddlePaddle/Paddle#42589]
### bug描述 Describe the Bug

当前环境是ubuntu1604,cuda10.1，cudnn7.6.5，然后安装完成后验证的时候报这个错，已经反复检查过环境了应该是按照官方要求来的，跪求大佬指教（cpu版安装后可以正常使用。。。。）
W0509 11:41:50.199869  7322 device_context.cc:447] Please NOTE: device: 0, GPU Compute Capability: 7.5, Driver API Version: 10.1, Runtime API Version: 10.1
W0509 11:41:50.203352  7322 device_context.cc:465] device: 0, cuDNN Version: 7.6.

--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
No stack trace in paddle, may be caused by external reasons.

----------------------
Error Message Summary:
----------------------
FatalError: `Segmentation fault` is detected by the operating system.
  [TimeInfo: *** Aborted at 1652067710 (unix time) try "date -d @1652067710" if you are using GNU date ***]
  [SignalInfo: *** SIGSEGV (@0x0) received by PID 7322 (TID 0x7f9ed1e04700) from PID 0 ***]

Segmentation fault (core dumped)

**Comment by gongel** [comment]
你好，这个看上去不是paddle的错误，请问你是怎么check的呢？

**Comment by Vincent630** [comment]
这个报错是安装完paddlepaddle后用这行命令验证安装情况的时候报的错：paddle.utils.run_check()然后本地环境，包括系统，python版本以及cuda和cudnn的版本型号都是按照paddle官方的安装文档配置安装的










------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/Paddle"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月9日(星期一) 中午12:28
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PaddlePaddle/Paddle] paddlepaddl安装失败（gpu版） (Issue #42589)





 
你好，这个看上去不是paddle的错误，请问你是怎么check的呢？

**Comment by gongel** [comment]
应该还是cuda和cudnn的环境问题，不是很好定位，尝试使用[docker](https://www.paddlepaddle.org.cn/install/quick?docurl=/documentation/docs/zh/install/docker/linux-docker.html)来解决吧

**Comment by pangyoki** [comment]
你好，麻烦提供下安装命令。
以及执行`nvidia-smi`和`nvcc -V`的截图，谢谢。

**Comment by Vincent630** [comment]
1.cuda版本和驱动


2.安装命令





感谢感谢，第一步就被挡在门外了有点难受😂


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/Paddle"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月9日(星期一) 下午3:40
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PaddlePaddle/Paddle] paddlepaddl安装失败（gpu版） (Issue #42589)





 
你好，麻烦提供下安装命令。
 以及执行nvidia-smi和nvcc -V的截图，谢谢。

**Comment by Vincent630** [comment]
额，刚用conda安装试了下看起来是成功了，感性帮忙哈，这个问题pip的坑我就不踩了😂稍后关闭这个问题，万分感谢







------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/Paddle"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月9日(星期一) 下午3:40
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PaddlePaddle/Paddle] paddlepaddl安装失败（gpu版） (Issue #42589)





 
你好，麻烦提供下安装命令。
 以及执行nvidia-smi和nvcc -V的截图，谢谢。

**Comment by Vincent630** [comment]
i have not solve this issues ,but install sucessfully in another way(use conda install paddle and almost in the same  system enviroment,so i am not sure what's make this happen...)
