### ISSUE TITLE
Paddle Pyodide support

### ISSUE THREAD

**Issue by ravirathore** [PaddlePaddle/Paddle#42592]
### 需求描述 Feature Description

任务目标（请描述你正在做的项目是什么，如模型、论文、项目是什么？）; <br /> 需求场景（请描述你的项目中为什么需要用此功能）;  <br /> 功能描述（请简单描述或设计这个功能）

Hi,

Is it possible to provide Paddle package for Pyodide, or add documentation on how to build it?
Pyodide is quite big now.

Thanks,

**Comment by gongel** [comment]
Thank you for your attention. We are evaluating it internally and please look forward to it.
