### ISSUE TITLE
paddleocr训练模型命令后The length of ratio_list should be the same as the file_list怎么解决

### ISSUE THREAD

**Issue by annabergite** [PaddlePaddle/Paddle#42594]
### 请提出你的问题 Please ask your question

gpu：3060laptop cudnn：8.1 paddlepaddle版本：2.2.2 cuda版本11.2 
Windows anaconda虚拟环境中python版本是3.8.13
使用https://blog.csdn.net/u013171226/article/details/115179480 中2.5训练模型中的步骤时候，python3 tools/train.py -c configs/det/det_mv3_db.yml -o Global.pretrain_weights=./pretrain_models/MobileNetV3_large_x0_5_pretrained/该命令（因为本电脑没有python3命令只有python命令所以命令里替换成了python）运行的时候出现了这个问题
![image](https://user-images.githubusercontent.com/50126267/167350676-dc96f83c-f685-4fdd-9f11-dd7778d48f96.png)

![image](https://user-images.githubusercontent.com/50126267/167350659-9fa6a93d-c704-4383-8e6d-2b12272ce6ad.png)

**Comment by gongel** [comment]
你好，麻烦去[PaddleOCR](https://github.com/PaddlePaddle/PaddleOCR/issues)提个issue哈

**Comment by locusbear** [comment]
这是因为label_file_list 前面有个 - 号没打上
