### ISSUE TITLE
(this issue is just for my personal self-learning ) imcomplete features  of  paddle.nn.initializer.TruncatedNormal   (compared to torch.nn.init.trunc_normal_() )

### ISSUE THREAD

**Issue by OccupyMars2030** [PaddlePaddle/Paddle#42609]
### 需求描述 Feature Description

objectives: complete the features of paddle.nn.initializer.TruncatedNormal 
(compared to torch.nn.init.trunc_normal_() )

requirement scenarios:
in pytorch, If I want to create a parameter, I will do the following:
`     
self.pos_embed = nn.Parameter(torch.zeros(1, num_patches, embed_dim))
trunc_normal_(self.pos_embed, std=.02)
`
while in paddlepaddle, if I want to do the same thing, I will do the following:
`
  self.pos_embed = self.create_parameter(shape=[1, num_patches, embed_dim],
                                         is_bias=False,
                                         default_initializer=paddle.nn.initializer.TruncatedNormal(std=0.02))

`
but I found that paddle.nn.initializer.TruncatedNormal  doesn't have lower and upper cutoff values 
in  its init method

**Comment by gongel** [comment]
Thank you for your attention. We are evaluating it internally and please look forward to it. At the same time, you can also implement it yourself through hacking.

**Comment by SmirnovKol** [comment]
I think it indeed  has  imcomplete  features.  When  I  have  time,  I  will  implement it myself.
