### ISSUE TITLE
can I use  paddle.nn.initializer.Constant   and   paddle.nn.initializer.TruncatedNormal  independently ?

### ISSUE THREAD

**Issue by OccupyMars2030** [PaddlePaddle/Paddle#42617]
### 请提出你的问题 Please ask your question

In pytorch,   in a  layer class,  after I  created a parameter, if I want to re-initialize its value,  then I can do the following :  
` trunc_normal_(m.weight, std=.02)    
`

but in paddlepaddle,  if I want to do the same thing,  the following code seems to  work:  
`paddle.nn.initializer.TruncatedNormal(std=.02)(m.weight)   
`

It   seems  that   paddle.nn.initializer.TruncatedNormal()   can  be used  independently to  change the parameter values   **in place** ,   but  this kind of  usage  is  unfamiliar  to me.   I  want to  ask  if  this kind of  usage is  
 ok  and  if  there  are  other  better  implementation methods.  

(I  know  I  can    do  it   in  the  creation  of  the parameter,  but  I  just want to  know how  to  re-initialize  the  parameter.)

**Comment by gongel** [comment]
You can initialize weight when `create_parameter` by setting argument `default_initializer`. Please refer to [here](https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/static/create_parameter_cn.html#create-parameter).

**Comment by gongel** [comment]
Please reopen if you'd like to work on this further.
