### ISSUE TITLE
sentiment analysis result are bad

### ISSUE THREAD

**Issue by jacquesqiao** [PaddlePaddle/Paddle#4261]
hi sorry again, we have been retraining the sentiment analysis model for a while on some new text and our results are always extremely bad, the classification accuracy stagnants around 20% and never gets better or worse after around 5 passes

**Comment by jacquesqiao** [comment]
> @ Changming Xu
so even if you run the pretrained model and use the already runnning server, its really not too good, like the phrase "i think its good" and "i think its bad" both give the same result, i guess we should have tried a different technique

**Comment by NorthStar** [comment]
At least two teams re-trained the sentiment analysis models. There is one for Wikipedia, another for Twitter. Let me contact the teams to see if they care to share/merge.
