### ISSUE TITLE
add new API  paddle.erfinv()

### ISSUE THREAD

**Issue by OccupyMars2030** [PaddlePaddle/Paddle#42614]
### 需求描述 Feature Description

mission objectives:  
add new API  paddle.erfinv()

requirement scenarios:  
I found   tensor.erfinv_()   in the source  code of   torch.nn.init.trunc_normal_().

**Comment by gongel** [comment]
Hi, PaddlePaddle has `paddle.erfinv` api in develop branch.

**Comment by OccupyMars2030** [comment]
That's good, But in  version  2.2.2,   it doesn't  have this api.
