### ISSUE TITLE
关于Paddle静态连接libcudart的问题

### ISSUE THREAD

**Issue by lycheenice** [PaddlePaddle/Paddle#42632]
### 请提出你的问题 Please ask your question

目前paddle的默认编译方式以及官方能下载的安装包都是静态连接了libcudart这个库。
请问，如果想编译动态连接的版本，应该如何操作呢？或者有编译好的安装包可供使用么？

**Comment by minghaoBD** [comment]
暂时不支持动态链接的方式，我们会评估下这个需求，有update会反馈出来～

**Comment by lycheenice** [comment]
> 暂时不支持动态链接的方式，我们会评估下这个需求，有update会反馈出来～

paddle默认静态连接的原因是什么？设计上有什么考虑么？

**Comment by minghaoBD** [comment]
目前默认是静态链接，Paddle框架没有对这些有设置操作，cmake自动加上了-lcudart_static
