### ISSUE TITLE
 自定义参数并更新

### ISSUE THREAD

**Issue by cpz19952007** [PaddlePaddle/Paddle#42635]
### 请提出你的问题 Please ask your question

请问下，这块如何自定参数？
想做的是手动设置参数矩阵为全1，shape为[batch_size,2]，然后每轮训练手动更新这个参数。目前问题是参数更新完之后，第二轮又变成了初始值。

class Model(object):

    def __init__(self, args):
        self.mat = np.ones((self.args.batch_size, 2), dtype=np.float32)
        w_param = fluid.ParamAttr(name="w1", initializer=fluid.initializer.NumpyArrayInitializer(self.mat))
        self.pesudo_label = flayers.create_parameter(shape=[self.args.batch_size, 2], 
                            dtype='float32', 
                            attr=w_param)

    def train(self, data):
        ...
        # update self.pesudo_label
        alpha = 0.1
        self.pesudo_label = self.pesudo_label * (1-alpha)

        ...

**Comment by minghaoBD** [comment]
@cpz19952007 你这么做应该没有更改tensor的数值。可以参考paddle.assign() 接口：https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/assign_cn.html#assign
