### ISSUE TITLE
计算图的绘制

### ISSUE THREAD

**Issue by Amm-W** [PaddlePaddle/Paddle#42649]
### 请提出你的问题 Please ask your question

PaddlePaddle《API文档》中提到，在动态图转静态图时，类“BuildStrategy”中有一个“debug_graphviz_path"可以绘制模型的计算图，便于调试，并给出以下示例：
import paddle
import paddle.static as static

paddle.enable_static()

build_strategy = static.BuildStrategy()
build_strategy.debug_graphviz_path = "./graph"
经实测无法直接使用，请问其具体的实现方式是什么？

**Comment by minghaoBD** [comment]
请问【无法直接使用】具体指遇到了什么问题呢？

这里有一个unittest用到了debug_graphviz_path属性，可以参考下：https://github.com/PaddlePaddle/Paddle/blob/2479664aa9892a69fb18dfac657b013ea8a07dc0/python/paddle/fluid/tests/unittests/test_parallel_executor_run_cinn.py#L94

**Comment by Amm-W** [comment]
感谢回答！
我是在PaddleDetection中动态图转静态图的函数中遇到 "build_strategy = static.BuildStrategy()" 这句代码的，查询BuildStrategy()后发现它有个绘制计算图的debug示例，想着照着API文档直接在其后面加上”build_strategy.debug_graphviz_path = "./graph" “看试试，确实无事发生，也不明白它的具体使用方法或者实现方式。
这个unittest测试中”debug_graphiv_path"用的也不是很明白，是创建一个临时文件，在模型中进行几次前向传播就可以自动创建计算图吗？不是的话具体的实现过程应该是什么。

**Comment by minghaoBD** [comment]
> 感谢回答！ 我是在PaddleDetection中动态图转静态图的函数中遇到 "build_strategy = static.BuildStrategy()" 这句代码的，查询BuildStrategy()后发现它有个绘制计算图的debug示例，想着照着API文档直接在其后面加上”build_strategy.debug_graphviz_path = "./graph" “看试试，确实无事发生，也不明白它的具体使用方法或者实现方式。 这个unittest测试中”debug_graphiv_path"用的也不是很明白，是创建一个临时文件，在模型中进行几次前向传播就可以自动创建计算图吗？不是的话具体的实现过程应该是什么。

看文档描述，应该会在 $debug_graphviz_path 位置生成一个代表graph的文件，然后可以可视化打开。
方便提供下你的【最小可复现】代码吗？我这边分析下。

**Comment by minghaoBD** [comment]
这是一段demo：

``` python
import os
import paddle
import paddle.static as static
import numpy as np

paddle.enable_static()

os.environ['CPU_NUM'] = str(1)
places = static.cpu_places()

data = static.data(name="x", shape=[None, 1], dtype="float32")
hidden = static.nn.fc(x=data, size=10)
loss = paddle.mean(hidden)

build_strategy = static.BuildStrategy()
build_strategy.enable_inplace = True
build_strategy.memory_optimize = True
build_strategy.reduce_strategy = static.BuildStrategy.ReduceStrategy.Reduce
build_strategy.debug_graphviz_path = "./graph"
program = static.CompiledProgram(static.default_main_program())
program = program.with_data_parallel(loss_name=loss.name,
                                    build_strategy=build_strategy,
                                    places=places)
place = places[0]
exe = paddle.static.Executor(place)
paddle.optimizer.SGD(learning_rate=0.01).minimize(loss)
exe.run(paddle.static.default_startup_program())
for i in range(1):
    exe.run(program,
                feed={"x": np.random.normal(size=(10,1)).astype(np.float32)},
                fetch_list=[loss.name])
```

运行后可以看到graph文件，然后借助graphviz工具打开哈。我测试了下，只是compileProgram不会生成graph，需要运行至少一次前向和反向。

**Comment by Amm-W** [comment]
> 

感谢，我这就试一下
