### ISSUE TITLE
PaddleGAN套件用ppgan.metircs.fid.py 对多张图求fid存在问题

### ISSUE THREAD

**Issue by bitcjm** [PaddlePaddle/Paddle#42656]
### bug描述 Describe the Bug

如果把多组数据都update后，再accumulate，得出的结果和对每一组数据都update后直接accumulate再对所有得到的数求平均得到的结果不一样，且前者明显要小。后者与pytorch模块算出的值一致，应该是正确的。

比如我对每一组图都求fid，可以算出fid的均值大概是120，但是如果对2000组图都update后再accumulate，得出的结果只有20左右。添加的图的组数越多，最后accumulate得到的值越小。如果把多组数据都update后，再accumulate，得出的结果和对每一组数据都update后直接accumulate再对所有得到的数求平均得到的结果不一样，且前者明显要小。后者与pytorch模块算出的值一致，应该是正确的。

比如我对每一组图都求fid，可以算出fid的均值大概是120，但是如果对2000组图都update后再accumulate，得出的结果只有20左右。添加的图的组数越多，最后accumulate得到的值越小。

**Comment by lzzyzlbb** [comment]
![image](https://user-images.githubusercontent.com/17897185/167635931-0d632cf8-023b-48dd-9040-e1232455e95c.png)
这里顺序不一样的话，concatenate会不一样哈
