### ISSUE TITLE
安装费avx的paddle包能否支持python3.6

### ISSUE THREAD

**Issue by FuyuanChen** [PaddlePaddle/Paddle#42651]
### 问题描述 Issue Description

目前机器不支持avx，需要安装noavx的Paddle包，可以通过以下命令安装，仅支持python3.8

### 版本&环境信息 Version & Environment Information

PaddlePaddle:2.3.0
GPU:CUDA10.2、cudnn7.6.5
系统：CentOS release 6.3
Python版本：Python 3.6.5

**Comment by minghaoBD** [comment]
抱歉～ 看起来只支持python3.8下的的no-avx版本的paddle安装：
![image](https://user-images.githubusercontent.com/79566150/167615163-8b0850f1-5aae-4af4-a11e-ebb05356a50a.png)
