### ISSUE TITLE
IndexError

### ISSUE THREAD

**Issue by huaibovip** [PaddlePaddle/Paddle#42660]
### 请提出你的问题 Please ask your question

【论文复现】加载数据时，训练3个batch后就会出现IndexError

> [2022/05/10 20:09:50] ppcls INFO: train with paddle 2.2.2 and device CUDAPlace(0)
> W0510 20:11:15.992267  9786 device_context.cc:447] Please NOTE: device: 0, GPU Compute Capability: 6.1, Driver API Version: 10.2, Runtime API Version: 10.2
> W0510 20:11:17.556282  9786 device_context.cc:465] device: 0, cuDNN Version: 7.6.
> [2022/05/10 20:11:23] ppcls WARNING: The training strategy in config files provided by PaddleClas is based on 4 gpus. But the number of gpus is 1 in current training. Please modify the stategy (learning rate, batch size and so on) if use config files in PaddleClas to train.
> /public/home/hb/.conda/envs/paddle22/lib/python3.7/site-packages/paddle/nn/layer/norm.py:653: UserWarning: When training, we now always track global mean and variance.
>   "When training, we now always track global mean and variance.")
> [2022/05/10 20:11:34] ppcls INFO: [Train][Epoch 1/300][Iter: 0/41]lr: 0.00005, CELoss: 6.97463, loss: 6.97463, batch_cost: 10.85498s, reader_cost: 10.08720, ips: 5.89591 images/sec, eta: 1 day, 13:05:16
> [2022/05/10 20:11:48] ppcls INFO: [Train][Epoch 1/300][Iter: 10/41]lr: 0.00054, CELoss: 6.98263, loss: 6.98263, batch_cost: 1.75605s, reader_cost: 1.17269, ips: 36.44546 images/sec, eta: 5:59:41
> [2022/05/10 20:11:54] ppcls INFO: [Train][Epoch 1/300][Iter: 20/41]lr: 0.00103, CELoss: 6.98085, loss: 6.98085, batch_cost: 1.03407s, reader_cost: 0.45092, ips: 61.89144 images/sec, eta: 3:31:38
> Exception in thread Thread-1:
> Traceback (most recent call last):
>   File "/public/home/hb/.conda/envs/paddle22/lib/python3.7/threading.py", line 926, in _bootstrap_inner
>     self.run()
>   File "/public/home/hb/.conda/envs/paddle22/lib/python3.7/threading.py", line 870, in run
>     self._target(*self._args, **self._kwargs)
>   File "/public/home/hb/.conda/envs/paddle22/lib/python3.7/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 505, in _thread_loop
>     batch = self._get_data()
>   File "/public/home/hb/.conda/envs/paddle22/lib/python3.7/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 634, in _get_data
>     batch.reraise()
>   File "/public/home/hb/.conda/envs/paddle22/lib/python3.7/site-packages/paddle/fluid/dataloader/worker.py", line 169, in reraise
>     raise self.exc_type(msg)
> IndexError: DataLoader worker(2) caught IndexError with message:
> Traceback (most recent call last):
>   File "/public/home/hb/.conda/envs/paddle22/lib/python3.7/site-packages/paddle/fluid/dataloader/worker.py", line 329, in _worker_loop
>     batch = fetcher.fetch(indices)
>   File "/public/home/hb/.conda/envs/paddle22/lib/python3.7/site-packages/paddle/fluid/dataloader/fetcher.py", line 134, in fetch
>     data = self.collate_fn(data)
>   File "/public/home/hb/paddle-proj/submit/paddle-CvT/ppcls/data/__init__.py", line 100, in mix_collate_fn
>     batch = transform(batch, batch_ops)
>   File "/public/home/hb/paddle-proj/submit/paddle-CvT/ppcls/data/preprocess/__init__.py", line 42, in transform
>     data = op(data)
>   File "/public/home/hb/paddle-proj/submit/paddle-CvT/ppcls/data/preprocess/batch_ops/batch_operators.py", line 231, in __call__
>     return op(batch) if op else batch
>   File "/public/home/hb/paddle-proj/submit/paddle-CvT/ppcls/data/preprocess/batch_ops/batch_operators.py", line 91, in __call__
>     targets = self._mix_target(labels, labels[idx], lam)
>   File "/public/home/hb/paddle-proj/submit/paddle-CvT/ppcls/data/preprocess/batch_ops/batch_operators.py", line 51, in _mix_target
>     one_hots0 = self._one_hot(targets0)
>   File "/public/home/hb/paddle-proj/submit/paddle-CvT/ppcls/data/preprocess/batch_ops/batch_operators.py", line 48, in _one_hot
>     return np.eye(self.class_num, dtype="float32")[targets]
> IndexError: index 1000 is out of bounds for axis 0 with size 1000
> 
> 
> Traceback (most recent call last):
>   File "tools/train.py", line 32, in <module>
>     engine.train()
>   File "/public/home/hb/paddle-proj/submit/paddle-CvT/ppcls/engine/engine.py", line 295, in train
>     self.train_epoch_func(self, epoch_id, print_batch_step)
>   File "/public/home/hb/paddle-proj/submit/paddle-CvT/ppcls/engine/train/train.py", line 24, in train_epoch
>     for iter_id, batch in enumerate(engine.train_dataloader):
>   File "/public/home/hb/.conda/envs/paddle22/lib/python3.7/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 697, in __next__
>     data = self._reader.read_next_var_list()
> SystemError: (Fatal) Blocking queue is killed because the data reader raises an exception.
>   [Hint: Expected killed_ != true, but received killed_:1 == true:1.] (at /paddle/paddle/fluid/operators/reader/blocking_queue.h:166)
> 
> INFO 2022-05-10 20:12:07,878 launch_utils.py:341] terminate all the procs
> ERROR 2022-05-10 20:12:07,879 launch_utils.py:604] ABORT!!! Out of all 1 trainers, the trainer process with rank=[0] was aborted. Please check its log.
> INFO 2022-05-10 20:12:11,883 launch_utils.py:341] terminate all the procs
> INFO 2022-05-10 20:12:11,883 launch.py:311] Local processes completed.

**Comment by minghaoBD** [comment]
![image](https://user-images.githubusercontent.com/79566150/167632160-ff55207e-15e9-4764-935a-bf96207929ec.png)
看报错信息的话，是index越界了，建议检查下label的预处理阶段，是否存在 label_index >= class_num的情况
