### ISSUE TITLE
编译 X86CPU + 华为昇腾NPU 版 Paddle

### ISSUE THREAD

**Issue by chenglong-do** [PaddlePaddle/Paddle#42667]
### 问题描述 Issue Description

编译教程只有ARM 版https://www.paddlepaddle.org.cn/documentation/docs/zh/guides/09_hardware_support/npu_docs/paddle_install_cn.html

按照教程我把镜像换成了 paddlepaddle/paddle:latest-dev-cann5.0.2.alpha005-gcc82-x86_64

编译命令

cmake .. -DPY_VERSION=3.7 -DWITH_ASCEND=OFF -DWITH_ARM=OFF -DWITH_ASCEND_CL=ON \
         -DWITH_ASCEND_INT64=ON -DWITH_DISTRIBUTE=ON -DWITH_TESTING=ON -DON_INFER=ON \
         -DCMAKE_BUILD_TYPE=Release -DCMAKE_EXPORT_COMPILE_COMMANDS=ON

make -j$(nproc)

编译完成后安装运行 python -c "import paddle; paddle.utils.run_check()"，没有输出 NPU 相关信息

Running verify PaddlePaddle program ... 
PaddlePaddle works well on 1 CPU.
W0511 11:09:50.414922 25728 fuse_all_reduce_op_pass.cc:76] Find all_reduce operators: 2. To make the speed faster, some all_reduce ops are fused during training, after fusion, the number of all_reduce ops is 2.
I0511 11:09:50.415657 25728 parallel_executor.cc:484] Cross op memory reuse strategy is enabled, when build_strategy.memory_optimize = True or garbage collection strategy is disabled, which is not recommended
PaddlePaddle works well on 2 CPUs.
PaddlePaddle is installed successfully! Let's start deep learning with PaddlePaddle now.

### 版本&环境信息 Version & Environment Information

****************************************
Paddle version: None
Paddle With CUDA: None

OS: EulerOS 2.0
Python version: 3.9.7

CUDA version: None
cuDNN version: None.None.None
Nvidia driver version: None
****************************************

**Comment by yang131313** [comment]
你好，现在Paddle已经有编译好的安装包了，请问你在什么任务场景下需要编译Paddle呀？比如是需要新增算子、还是需要修改飞桨源代码，或者有什么其他的用途呢？

**Comment by chenglong-do** [comment]
> 

你好，我是要在 X86的 CPU + 华为昇腾NPU 推理卡的环境下运行 paddle serving pipeline，预编译好的并没有华为昇腾版哦

**Comment by chenglong-do** [comment]
请问是只支持昇腾910么？用的是310，拿了一台 AT500 PRO，也是昇腾310，编译完也无法调用 NPU

**Comment by aviciiiii** [comment]
@chenglong-do 你好请问你昇腾310后面重新编译成功了么，我目前按照手册编译成功了，但是使用时一直在报显存错误
