### ISSUE TITLE
利用PPOCRLabel点击表格识别按钮会出现闪退的问题 

### ISSUE THREAD

**Issue by liu1073811240** [PaddlePaddle/Paddle#42679]
### bug描述 Describe the Bug

利用PPOCRLabel点击表格识别按钮会出现闪退的问题， 并且这过程中出现 两个多G的 python.exe.15484.dmp文件

**Comment by lyuwenyu** [comment]
https://github.com/PaddlePaddle/PaddleOCR/issues  ocr相关问题可以在这里提问
