### ISSUE TITLE
Use tempfile for storing temporary checkpoints/params/models

### ISSUE THREAD

**Issue by zlsh80826** [PaddlePaddle/Paddle#42681]
### 需求描述 Feature Description

目前 Paddle 實現的多個單測中, 會有儲存 checkpoints 或 inference model 後再讀取的測試, 這類型的測試會將模型儲存, 並在完成單測後刪除。但是多個單測會有暫存檔案同名的問題, 會導致單測同時運行時互相覆蓋掉其他單測的暫存檔案, 導致單測會出現隨機性的失敗。例如: [test_dataset](https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/fluid/tests/unittests/test_dataset.py#L85) 和 [test_dataset_consistency_inspection](https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/fluid/tests/unittests/test_dataset_consistency_inspection.py) 會使用相同 `test_run_with_dump_a.txt` 作為暫存檔案，又比如 [test_resnet](https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/fluid/tests/unittests/dygraph_to_static/test_resnet.py#L269) 和 [test_build_strategy](https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/fluid/tests/unittests/dygraph_to_static/test_build_strategy.py#L21) 都使用相同的 `resnet.dygraph.params` 作為模型暫存檔。

在撰寫單測時應該注重單測的孤立性, 單測前後系統的狀態需要盡量保持相同, 最大限度地減少生成檔案或是測試之間的依賴關係, 如果有需要使用暫存檔案, 可以使用 `mktemp` 或是 python 模塊的 `tempfile`, 並在單測的 `tearDown` 函式中釋放從系統中取得的資源。

### 替代实现 Alternatives

有用到暫存檔案的單測應該參考類似 [test_pass_builder.py](https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/fluid/tests/unittests/test_pass_builder.py#L102) 的寫法, 使用 [tempfile](https://docs.python.org/3/library/tempfile.html) 模塊底下的函式, 照單測的需求使用對應建立暫存檔案或目錄的 API 來減少單測間的影響。

**Comment by zlsh80826** [comment]
https://github.com/PaddlePaddle/Paddle/pull/42626 fixes part of the unit tests, but there are still many unit tests should be refactored.

**Comment by jzhang533** [comment]
cc: @kolinwei

**Comment by Aurelius84** [comment]
dygraph_to_static目录下的所有单测均已替换为`tmpfile`来管理，已cherry-pick到 2.3 分支，见：https://github.com/PaddlePaddle/Paddle/pull/42860

**Comment by zlsh80826** [comment]
Thank @Aurelius84, we will check it ASAP.

**Comment by luotao1** [comment]
> we will check it ASAP.

@zlsh80826 How about the check result, could we close this issue?

**Comment by zlsh80826** [comment]
Hi @luotao1,
https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/fluid/tests/unittests/ir/test_convert_to_mixed_precision.py this ut doesn't use tempfile for temporary models/params.

**Comment by luotao1** [comment]
@jiweibo Could you fix the `test_convert_to_mixed_precision.py`?

**Comment by jiweibo** [comment]
> @jiweibo Could you fix the `test_convert_to_mixed_precision.py`?

https://github.com/PaddlePaddle/Paddle/pull/48819 will fix the problem.

**Comment by zlsh80826** [comment]
Hi @luotao1,
[dist_pass_test_base.py](https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/fluid/tests/unittests/distributed_passes/dist_pass_test_base.py#L193) doesn't use tempfile for temporary files, too. Besides, there is a flaw in [dist_pass_test_base.py#L193](https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/fluid/tests/unittests/distributed_passes/dist_pass_test_base.py#L193), the `mode` argument of `os.makedirs` should be represent as oct format ([reference](https://docs.python.org/3/library/os.html#os.mkdir)), which should be `0o777` instead of `777`. The incorrect `mode=777` will be interpreted as `0o1411` and it will cause permission denied for non-root user. Thanks

**Comment by sneaxiy** [comment]
> Hi @luotao1, [dist_pass_test_base.py](https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/fluid/tests/unittests/distributed_passes/dist_pass_test_base.py#L193) doesn't use tempfile for temporary files, too. Besides, there is a flaw in [dist_pass_test_base.py#L193](https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/fluid/tests/unittests/distributed_passes/dist_pass_test_base.py#L193), the `mode` argument of `os.makedirs` should be represent as oct format ([reference](https://docs.python.org/3/library/os.html#os.mkdir)), which should be `0o777` instead of `777`. The incorrect `mode=777` will be interpreted as `0o1411` and it will cause permission denied for non-root user. Thanks

@zlsh80826 Thanks for pointing out. We would fix this issue.

**Comment by zlsh80826** [comment]
Thank all of you,
Once `test_dist_pass_test_base` and `test_convert_to_mixed_precision` are solved, I will close the issue.

**Comment by sneaxiy** [comment]
> > Hi @luotao1, [dist_pass_test_base.py](https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/fluid/tests/unittests/distributed_passes/dist_pass_test_base.py#L193) doesn't use tempfile for temporary files, too. Besides, there is a flaw in [dist_pass_test_base.py#L193](https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/fluid/tests/unittests/distributed_passes/dist_pass_test_base.py#L193), the `mode` argument of `os.makedirs` should be represent as oct format ([reference](https://docs.python.org/3/library/os.html#os.mkdir)), which should be `0o777` instead of `777`. The incorrect `mode=777` will be interpreted as `0o1411` and it will cause permission denied for non-root user. Thanks
> 
> @zlsh80826 Thanks for pointing out. We would fix this issue.

@zlsh80826 This is fixed by https://github.com/PaddlePaddle/Paddle/pull/48863 .

**Comment by zlsh80826** [comment]
@sneaxiy appreciate your help!

**Comment by luotao1** [comment]
> Once test_dist_pass_test_base and test_convert_to_mixed_precision are solved, I will close the issue.

- #48819 and - #48863 are both merged, could you close this issue? @zlsh80826

**Comment by zlsh80826** [comment]
Sure, thanks!
