### ISSUE TITLE
Paddle2.2.2版本明显比Paddle2.0.0上的CPU推理性能降低

### ISSUE THREAD

**Issue by caidou05** [PaddlePaddle/Paddle#42694]
### bug描述 Describe the Bug

Paddle2.2.2版本明显比Paddle2.0.0上的CPU推理性能降低，除了Paddle2.2.2版本不一致，其他全部一样，模型是Paddle2.2.0训的，但是2.0.0推理速度比2.2.2高了好几倍，所有测试代码一模一样，环境一样

**Comment by jiangjiajun** [comment]
> 

@caidou05 Hi， 你好。 能提供一下模型和预测代码吗。 如果较大，可通过百度网盘上传。 同时给一下你的CPU信息
