### ISSUE TITLE
paddle.einsum运算速度相对来说很慢，使用gpu速度上更是负提升

### ISSUE THREAD

**Issue by simonsLiang** [PaddlePaddle/Paddle#42710]
### 请提出你的问题 Please ask your question

复现代码：
import paddle
import torch
import numpy as np
import time
xnp = np.random.rand(27,3)
ynp = np.random.rand(27,80,80,80)
e = 'qd,q...->d...'

print('运行时间:')
s = time.time()
res = np.einsum(e,xnp,ynp)
print("numpy:",time.time()-s)

paddle.set_device('cpu')
xp = paddle.to_tensor(xnp)
yp = paddle.to_tensor(ynp)
s = time.time()
res = paddle.einsum(e,xp,yp)
print("paddle(cpu):",time.time()-s)

paddle.set_device('gpu')
xp = paddle.to_tensor(xnp)
yp = paddle.to_tensor(ynp)
s = time.time()
res = paddle.einsum(e,xp,yp)
print("paddle(gpu):",time.time()-s)

xt = torch.tensor(xnp)
yt = torch.tensor(ynp)

s = time.time()
res = torch.einsum(e,[xt,yt])
print("torch(cpu):",time.time()-s)

dev = torch.device('cuda:0')
xt = xt.to(dev)
yt = yt.to(dev)
s = time.time()
res = torch.einsum(e,[xt,yt])
print("torch(gpu):",time.time()-s)

在paddle 2.2.2版本运行结果：
运行时间:
numpy: 0.033910274505615234
paddle(cpu): 0.07882046699523926
paddle(gpu): 1.4361622333526611
torch(cpu): 0.014960289001464844
torch(gpu): 0.0009615421295166016

**Comment by lzzyzlbb** [comment]
您好，我这边测试确实有这个问题，已经反馈给了相关API负责同学。请等待进一步确认及回复~

**Comment by tongxin** [comment]
这个比较不是对等的，paddle在第一次调用以 numpy 导入数据为输入时进行类似 xt = xt.to(dev) 的操作，所以测量gpu性能时应该除去第一次调用的时间，看第二次的。

**Comment by simonsLiang** [comment]
那请问怎样才是对等的，下面这样对等吗，
import paddle
import torch
import numpy as np
import time
xnp = np.random.rand(27,3)
ynp = np.random.rand(27,80,80,80)
e = 'qd,q...->d...'

print('运行时间:')
s = time.time()
res = np.einsum(e,xnp,ynp)
print("numpy:",time.time()-s)

paddle.set_device('cpu')
xp = paddle.to_tensor(xnp)
yp = paddle.to_tensor(ynp)
res = paddle.einsum(e,xp,yp)
s = time.time()
res = paddle.einsum(e,xp,yp)
print("paddle(cpu):",time.time()-s)


paddle.set_device('gpu')
xp = paddle.to_tensor(xnp)
yp = paddle.to_tensor(ynp)
res = paddle.einsum(e,xp,yp)
s = time.time()
res = paddle.einsum(e,xp,yp)
print("paddle(gpu):",time.time()-s)

xt = torch.tensor(xnp)
yt = torch.tensor(ynp)

s = time.time()
res = torch.einsum(e,[xt,yt])
print("torch(cpu):",time.time()-s)

dev = torch.device('cuda:0')
xt = xt.to(dev)
yt = yt.to(dev)
s = time.time()
res = torch.einsum(e,[xt,yt])
print("torch(gpu):",time.time()-s)

运行时间:
numpy: 0.04185962677001953
paddle(cpu): 0.045877933502197266
W0512 23:17:49.580324  3880 device_context.cc:465] device: 0, cuDNN Version: 7.6.
paddle(gpu): 0.0917823314666748
torch(cpu): 0.017830610275268555
torch(gpu): 0.001995086669921875

速度确实快了 不过比torch（gpu的）慢很多  而且 gpu好像还是负提升

**Comment by lzzyzlbb** [comment]
您好，torch调度跟我们不一样，需要加 paddle.device.cuda.synchronize() 和 torch.cuda.synchronize() 哈
比如：
torch.cuda.synchronize()
time_t = time.time()
res = torch.einsum('bc...,bc...->b...', [x_t, y_t])
torch.cuda.synchronize()

paddle.device.cuda.synchronize()
time_p = time.time()
res = paddle.einsum('bc...,bc...->b...',x_p, y_p)
paddle.device.cuda.synchronize()

**Comment by simonsLiang** [comment]
您好，可以测一下
xnp = np.random.rand(27,3)
ynp = np.random.rand(27,80,80,80)
e = 'qd,q...->d...'
的时候paddle和pytorch的速度差距吗，另外我想问我平时应该如何使用才能达到paddle.einsum的最快速度呢   直接用的话会很慢（相比pytorch）

**Comment by tongxin** [comment]
你好，是这样的，如果是benchmark API的准确耗时，建议用 paddle.rand() 生成的Tensor为输入，排除numpy导入导出的开销，另外执行相同的调用一定数量，比如1000次，取平均值，这样的到的结果比较可信。如果作为一个端到端的程序，当然可以用numpy生成数据咯，不过这个时候你关心的是整个程序的训练或推理性能，仅比较API的单次调用意义不是很大。如果你的目的的确在于比较 一次数据生成+einsum调用，我们在2.3中新开发一个基于C++的einsum算子，减少了小数据的Python开销，可以尝试一下，看看效果。
谢谢。
