### ISSUE TITLE
Is  this  a  bug in  the implementation of  IntArrayBase in  the file   paddle/phi/common/int_array.h

### ISSUE THREAD

**Issue by OccupyMars2030** [PaddlePaddle/Paddle#42713]
### 请提出你的问题 Please ask your question

In  the implementation of  IntArrayBase in  the file   paddle/phi/common/int_array.h,   I  think   it  may  be  a  bug:
In the line 107,   it  may  should  be:
`   if (value_data && n > 0) {`
![Screenshot from 2022-05-12 16-15-44](https://user-images.githubusercontent.com/31559413/168024691-05119896-7c48-4ba3-bd89-b93afc864d5b.png)

**Comment by OccupyMars2030** [comment]
The location of this file:

https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/phi/common/int_array.h

**Comment by lzzyzlbb** [comment]
您好，已经反馈给了相关的负责同学。请等待进一步确认及回复~

**Comment by zyfncg** [comment]
您好，感谢反馈，写成`value_data || n == 0`是为了支持有些场景下维度数据为0的情况。
这里建议改为`value_data && n > 0`是有遇到什么问题吗？

**Comment by OccupyMars2030** [comment]
感谢解答，没有遇到什么问题，只是看这源代码的时候有点疑惑
