### ISSUE TITLE
paddle.rand(x)文档出错？

### ISSUE THREAD

**Issue by 875052544** [PaddlePaddle/Paddle#42726]
### bug描述 Describe the Bug

rank = paddle.rank(input)
input (Tensor) — 输入input是shape为 [N1,N2,...,Nk] 的多维Tensor，数据类型可以任意类型。这是文档原话

当我输入float多维矩阵后，报了该错误ValueError: (InvalidArgument) uniform_random(): argument (position 1) must be list of int, but got list at pos 0

**Comment by lzzyzlbb** [comment]
![image](https://user-images.githubusercontent.com/17897185/168201828-41ffe813-625e-4aa9-971f-7626ea1dbe90.png)
nin ha您好，我这边测试是没有问题的哈，麻烦提供一下具体的代码
