### ISSUE TITLE
 grade essays with machine learning

### ISSUE THREAD

**Issue by reyoung** [PaddlePaddle/Paddle#4273]
* https://hackmit-baidu.slack.com/archives/G75B4F98F/p1505600508000051

**Comment by luotao1** [comment]
I could not open this url, since it needs email address and password.

**Comment by NorthStar** [comment]
I think the link is broken somehow. I am guessing the easiest way to utilize ML for grading essays is to automatically judge the grammar: http://www.deepgrammar.com/ , and summarize the content for human evaluation (maybe with confidence to see if their logic is clearly laid out): https://en.wikipedia.org/wiki/Automatic_summarization
