### ISSUE TITLE
【PFCC】新增算子报错AttributeError: module 'paddle.fluid.core_avx.ops' has no attribute 'index_fill_tensor'

### ISSUE THREAD

**Issue by thunder95** [PaddlePaddle/Paddle#42730]
### 请提出你的问题 Please ask your question

新写一个算子，检查了很久，也不知道错在哪里：
AttributeError: module 'paddle.fluid.core_avx.ops' has no attribute 'index_fill_tensor'

已做过尝试：
重命名
删除build目录重新cmake、make

在生成的文件中并没有找到该算子：
 dygraph_forward_functions
eager_op_function
op_function_impl

已提交PR： https://github.com/PaddlePaddle/Paddle/pull/42454

**Comment by zh794390558** [comment]
已有同学在跟该问题。

**Comment by chenwhql** [comment]
index_fill可以找到，但index_fill_tensor没有生成是嘛

**Comment by JiabinYang** [comment]
这一行报错在哪里报出来的可以有个完整的报错截图嘛

**Comment by thunder95** [comment]
> index_fill可以找到，但index_fill_tensor没有生成是嘛

是的

**Comment by thunder95** [comment]
@zh794390558 @JiabinYang @chenwhql 谢谢各位老师跟进， 我重新创建docker镜像并清空build之后，能找到注册算子了。
