### ISSUE TITLE
Distill加载teacher和student模型时报错In dygraph mode, the name of parameter can't be same.Please check the parameter attr value passed to self.create_parameter or constructor of dygraph Layers

### ISSUE THREAD

**Issue by liushanshan07** [PaddlePaddle/Paddle#42746]
### 请提出你的问题 Please ask your question

ValueError: parameter name [vis_encoder_pos_embed] have be been used. In dygraph mode, the name of parameter can't be same.Please check the parameter attr value passed to self.create_parameter or constructor of dygraph Layers

由于模型结构类似，只是层数不一致，如何加载两个相似结构的模型？

**Comment by zh794390558** [comment]
看上面是 vis_encoder_pos_embed key重复了。

主要关注下model中的key,val和model的paramseters是否相同。不同给的话，修改下key即可。

**Comment by liushanshan07** [comment]
> 看上面是 vis_encoder_pos_embed key重复了。
> 
> 主要关注下model中的key,val和model的paramseters是否相同。不同给的话，修改下key即可。

怎么修改key，还能把原模型的参数加载进来？

**Comment by zh794390558** [comment]
已线下回复。
