### ISSUE TITLE
Paddle官方wheel包并没有集成TensorRT，而是单独给出了Paddle预测库，请问这么做的原因是什么？

### ISSUE THREAD

**Issue by firedent** [PaddlePaddle/Paddle#42759]
### 请提出你的问题 Please ask your question

[Paddlepaddle快速安装](https://www.paddlepaddle.org.cn/install/quick?docurl=/documentation/docs/zh/install/pip/linux-pip.html)页面提供的[Paddle官方源](https://www.paddlepaddle.org.cn/whl/linux/mkl/avx/stable.html)所列出的whl安装包是没有集成TensorRT的，如果调用`enable_tensorrt_engine`会返回`Please use the paddle inference library compiled with tensorrt or disable the tensorrt engine in inference configurarion!`。因此，需要安装[Paddle Inference Python预测库](https://www.paddlepaddle.org.cn/inference/v2.3/user_guides/download_lib.html#python)和TensorRT依赖才能使用TensorRT子图功能。为什么Paddle官方默认的whl包没有集成TensorRT？这样，对于需要使用TensorRT预测功能的人来说，可以避免重新下载安装。

另，[不带trt的安装包](https://paddle-wheel.bj.bcebos.com/2.2.2/linux/linux-gpu-cuda11.2-cudnn8-mkl-gcc8.2-avx/paddlepaddle_gpu-2.2.2.post112-cp36-cp36m-linux_x86_64.whl)与[带trt的安装包](https://paddle-inference-lib.bj.bcebos.com/2.2.2/python/Linux/GPU/x86-64_gcc8.2_avx_mkl_cuda11.2_cudnn8.2.1_trt8.0.3.4/paddlepaddle_gpu-2.2.2.post112-cp36-cp36m-linux_x86_64.whl)命名完全一样，会使用户产生误解。

**Comment by dingjiaweiww** [comment]
你好，你对训练框架和Tensorrt 的预测功能都分别有需求是吗？你可以安装预测包，预测包是包含了训练功能的

**Comment by firedent** [comment]
@dingjiaweiww 是的，我现在的开发场景需要用到paddle的训练功能和TensorRT的预测功能。只是处出于好奇，希望官方可以说明一下，是出于怎样的考量才将TersorRT的预测功能和Paddle的训练功能分开的？（或者说，为什么要单独提供一个Paddle预测包，而不是将TensorRT功能加入到Paddlepaddle GPU版默认的安装包内？）

**Comment by jzhang533** [comment]
现在主要是从不同的产品定位上来做的拆分成两个package的决定。

Paddle Inference定位是高性能的预测库，所以把从Paddle的计算图中的子图交给TensorRT执行的功能放到了Paddle Inference中，同时，还在进展中的是，Paddle Inference也会集成ONNX Runtime作为推理的后端。Paddle主package的主要定位是做模型的开发和训练。我们是希望这样构成的围绕Paddle的Stack能够让用户灵活选用。

另外一些是技术性的问题上的考虑，比如引入TensorRT（及其他推理后端）到Paddle主package会对主package的体积产生影响，以及对用户环境的额外要求等。

**Comment by firedent** [comment]
@jzhang533 感谢您的详细解答。关于“Paddle Inference也会集成ONNX Runtime作为推理的后端”，不知您是否方便透露，以后Paddle Inference会使用ONNX Runtime作为唯一推理后端？以及，将ONNX Runtime集成进预测库大概会在今后哪个版本出现？

另，个人感觉需要编写文档的“同学”在较为明显的位置说明一下主package和预测库的区别，通过上面的[issue#5971](https://github.com/PaddlePaddle/PaddleDetection/issues/5971)您也看到了，确实有人将两者混淆了。

**Comment by jzhang533** [comment]
Paddle Inference会集成多个推理后端，包括TensorRT和ONNX Runtime。
在2.3版本中，已经完成了集成ONNX Runtime的部分工作。

- related PR： #39988
- API文档：https://www.paddlepaddle.org.cn/inference/api_reference/python_api_doc/Config/ORTConfig.html
- Tutorial：https://github.com/PaddlePaddle/Paddle-Inference-Demo/tree/master/c%2B%2B/paddle-onnxruntime
