### ISSUE TITLE
HOST_NAME_MAX in gloo is undefined

### ISSUE THREAD

**Issue by bulvara** [PaddlePaddle/Paddle#42769]
### 问题描述 Issue Description

```
./paddlepaddle/src/build/third_party/gloo/src/extern_gloo/gloo/transport/tcp/device.cc: In Funktion »std::shared_ptr<gloo::transport::Device> gloo::transport::tcp::CreateDevice(const attr&)«:
./paddlepaddle/src/build/third_party/gloo/src/extern_gloo/gloo/transport/tcp/device.cc:152:39: Fehler: Aggregat »std::array<char, 64> hostname« hat unvollständigen Typ und kann nicht definiert werden
  152 |       std::array<char, HOST_NAME_MAX> hostname;
      |                                       ^~~~~~~~

```

### 版本&环境信息 Version & Environment Information

****************************************
Paddle version: None
Paddle With CUDA: None

OS: Arch Linux rolling (GCC 12)
Python version: 3.10.4

CUDA version: None
cuDNN version: None.None.None
Nvidia driver version: None
****************************************

**Comment by zhiboniu** [comment]
你好，可以尝试使用paddle docker环境，避免环境依赖的问题

**Comment by lsrami** [comment]
> ### 问题描述 Issue Description
> ```
> ./paddlepaddle/src/build/third_party/gloo/src/extern_gloo/gloo/transport/tcp/device.cc: In Funktion »std::shared_ptr<gloo::transport::Device> gloo::transport::tcp::CreateDevice(const attr&)«:
> ./paddlepaddle/src/build/third_party/gloo/src/extern_gloo/gloo/transport/tcp/device.cc:152:39: Fehler: Aggregat »std::array<char, 64> hostname« hat unvollständigen Typ und kann nicht definiert werden
>   152 |       std::array<char, HOST_NAME_MAX> hostname;
>       |                                       ^~~~~~~~
> ```
> 
> ### 版本&环境信息 Version & Environment Information
> Paddle version: None Paddle With CUDA: None
> 
> OS: Arch Linux rolling (GCC 12) Python version: 3.10.4
> 
> CUDA version: None cuDNN version: None.None.None Nvidia driver version: None

please try adding #include <array> to gloo/gloo/transport/tcp/device.cc
It seems that he is similar to the problem.  [pytorch:issues/77614](https://github.com/pytorch/pytorch/issues/77614)
