### ISSUE TITLE
如何在centos6上使用paddle

### ISSUE THREAD

**Issue by Daymeow** [PaddlePaddle/Paddle#42780]
### 请提出你的问题 Please ask your question

如何在centos6上使用paddle2.2.2

**Comment by Intsigstephon** [comment]
您好，可以拉取paddlepaddle官方镜像, 并构建进入到Docker容器里面去使用对应的paddle版本；详细的安装教程可以参考：
https://www.paddlepaddle.org.cn/install/quick?docurl=/documentation/docs/zh/install/docker/linux-docker.html
