### ISSUE TITLE
Paddle-TRT fp16模式比int8模式要快，模型是OCR QAT得到的模型INT8模式与TRT FP32速度差不多

### ISSUE THREAD

**Issue by marsbzp** [PaddlePaddle/Paddle#42792]
### 请提出你的问题 Please ask your question

是不是内部bn与relu没融合以fp32运行的
![image](https://user-images.githubusercontent.com/20138766/168588554-e6840e3a-863d-45f2-ab2a-a53002029c43.png)

**Comment by Intsigstephon** [comment]
您好，麻烦描述下具体使用的是OCR哪个模型、Paddle版本，显卡型号、CUDA版本等信息，我们好针对您的问题复现下~

**Comment by marsbzp** [comment]
> 您好，麻烦描述下具体使用的是OCR哪个模型、Paddle版本，显卡型号、CUDA版本等信息，我们好针对您的问题复现下~

可以使用这个开源模型ch_ppocr_mobile_v2.0_rec_slim_infer和他未量化前的模型测试，T4 cuda10.2 tensorrt7.2

**Comment by Intsigstephon** [comment]
将use_calib_mode 设为False，int8测速应该就没问题了
