### ISSUE TITLE
visual studio 2022编译paddleInference报错，error : expected a "("

### ISSUE THREAD

**Issue by yhz5256** [PaddlePaddle/Paddle#42830]
### 问题描述 Please describe your issue

42>D:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.32.31326\include\xutility(1274): error : expected a "("
42>          detected during:
42>            instantiation of "decltype(auto) std::_Get_unwrapped(_Iter &&) [with _Iter=__wchar_t *&]"
42>D:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.32.31326\include\xstring(2585): here
42>            instantiation of "std::basic_string<_Elem, _Traits, _Alloc>::basic_string(_Iter, _Iter, const _Alloc &) [with _Elem=__wchar_t, _Traits=std::char_traits<__wchar_t>, _Alloc=std::allocator<__wchar_t>, _Iter=__wchar_t *, <unnamed>=0]"
42>D:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.32.31326\include\string(494): here
42>            instantiation of "std::basic_string<_Elem, std::char_traits<_Elem>, std::allocator<_Elem>> std::_Integral_to_string<_Elem,_Ty>(_Ty) [with _Elem=__wchar_t, _Ty=int]"
42>D:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.32.31326\include\string(548): here
42>
42>            instantiation of "void std::_Destroy_in_place(_Ty &) [with _Ty=char *]"
42>            instantiation of "std::basic_string<_Elem, _Traits, _Alloc>::basic_string(std::basic_string<_Elem, _Traits, _Alloc> &&) [with _Elem=char, _Traits=std::char_traits<char>, _Alloc=std::allocator<char>]"
42>            instantiation of "std::basic_string<_Elem, _Traits, _Alloc>::~basic_string() [with _Elem=char, _Traits=std::char_traits<char>, _Alloc=std::allocator<char>]"
42>            instantiation of "void std::_Destroy_in_place(_Ty &) [with _Ty=char *]"
42>(954): here
42>            instantiation of "void std::_Construct_in_place(_Ty &, _Types &&...) [with _Ty=__wchar_t *, _Types=<__wchar_t *const &>]"
42>D:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.32.31326\include\xstring(3000): here
42>            instantiation of "_Integral std::_Atomic_reinterpret_as<_Integral,_Ty>(const _Ty &) [with _Integral=long, _Ty=std::remove_reference_t<long>]"
42>D:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.32.31326\include\system_error(431): here
42>D:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.32.31326\include\xstring(4635): here
42>            instantiation of "void std::_Destroy_range(_NoThrowFwdIt, _NoThrowSentinel) [with _NoThrowFwdIt=char *, _NoThrowSentinel=char *]"
42>D:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.32.31326\include\xstring(4635): here
42>D:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.32.31326\include\system_error(432): here
42>D:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.32.31326\include\xstring(4545): here
42>            instantiation of "std::basic_string<_Elem, _Traits, _Alloc>::~basic_string() [with _Elem=char, _Traits=std::char_traits<char>, _Alloc=std::allocator<char>]"
42>(876): here
42>D:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.32.31326\include\xutility(1275): error : expression must have class type
42>          detected during:
42>            instantiation of "decltype(auto) std::_Get_unwrapped(_Iter &&) [with _Iter=__wchar_t *&]"
42>D:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.32.31326\include\xstring(2585): here
42>            instantiation of "std::basic_string<_Elem, _Traits, _Alloc>::basic_string(_Iter, _Iter, const _Alloc &) [with _Elem=__wchar_t, _Traits=std::char_traits<__wchar_t>, _Alloc=std::allocator<__wchar_t>, _Iter=__wchar_t *, <unnamed>=0]"
42>D:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.32.31326\include\string(494): here
42>            instantiation of "std::basic_string<_Elem, std::char_traits<_Elem>, std::allocator<_Elem>> std::_Integral_to_string<_Elem,_Ty>(_Ty) [with _Elem=__wchar_t, _Ty=int]"
42>D:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.32.31326\include\string(548): here
42>
42>D:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.32.31326\include\string(494): here
42>D:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.32.31326\include\string(494): here
42>            instantiation of "std::basic_string<_Elem, std::char_traits<_Elem>, std::allocator<_Elem>> std::_Integral_to_string<_Elem,_Ty>(_Ty) [with _Elem=char, _Ty=int]"
42>            instantiation of "std::basic_string<_Elem, std::char_traits<_Elem>, std::allocator<_Elem>> std::_Integral_to_string<_Elem,_Ty>(_Ty) [with _Elem=char, _Ty=int]"
42>            instantiation of "void std::basic_string<_Elem, _Traits, _Alloc>::_Tidy_deallocate() [with _Elem=char, _Traits=std::char_traits<char>, _Alloc=std::allocator<char>]"
42>(296): here
42>            instantiation of "void std::basic_string<_Elem, _Traits, _Alloc>::_Tidy_deallocate() [with _Elem=char, _Traits=std::char_traits<char>, _Alloc=std::allocator<char>]"
42>
42>            instantiation of "std::basic_string<_Elem, _Traits, _Alloc> &std::basic_string<_Elem, _Traits, _Alloc>::_Reallocate_for(std::basic_string<_Elem, _Traits, _Alloc>::size_type, _Fty, _ArgTys...) [with _Elem=__wchar_t, _Traits=std::char_traits<__wchar_t>, _Alloc=std::allocator<__wchar_t>, _Fty=lambda [](__wchar_t *, size_t, const __wchar_t *)->void, _ArgTys=<const __wchar_t *>]"
42>
42>D:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.32.31326\include\system_error(431): here
42>            instantiation of "void std::_Atomic_storage<_Ty, 4ULL>::store(std::_Atomic_storage<_Ty, 4ULL>::_TVal) [with _Ty=long]"
42>D:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.32.31326\include\xstring(2588): error : expected a "("
42>          detected during:
42>            instantiation of "std::basic_string<_Elem, _Traits, _Alloc>::basic_string(_Iter, _Iter, const _Alloc &) [with _Elem=__wchar_t, _Traits=std::char_traits<__wchar_t>, _Alloc=std::allocator<__wchar_t>, _Iter=__wchar_t *, <unnamed>=0]"
42>D:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.32.31326\include\string(494): here
42>            instantiation of "std::basic_string<_Elem, std::char_traits<_Elem>, std::allocator<_Elem>> std::_Integral_to_string<_Elem,_Ty>(_Ty) [with _Elem=__wchar_t, _Ty=int]"
42>D:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.32.31326\include\string(548): here
42>
42>D:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.32.31326\include\string(509): here
42>D:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.32.31326\include\string(509): here
42>D:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.32.31326\include\xstring(3000): here
42>            instantiation of "void std::_Destroy_in_place(_Ty &) [with _Ty=char *]"
42>D:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.32.31326\include\xmemory(952): error : expected a "("
42>D:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.32.31326\include\xstring(3254): here
42>D:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.32.31326\include\xstring(3000): here
42>
42>(898): here
42>D:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.32.31326\include\xmemory(295): error : expected a "("
42>D:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.32.31326\include\xstring(4635): here
42>            instantiation of "std::basic_string<_Elem, _Traits, _Alloc>::~basic_string() [with _Elem=char, _Traits=std::char_traits<char>, _Alloc=std::allocator<char>]"
42>          detected during:
42>            instantiation of "std::basic_string<_Elem, _Traits, _Alloc> &std::basic_string<_Elem, _Traits, _Alloc>::assign(const _Elem *, std::basic_string<_Elem, _Traits, _Alloc>::size_type) [with _Elem=__wchar_t, _Traits=std::char_traits<__wchar_t>, _Alloc=std::allocator<__wchar_t>]"
42>D:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.32.31326\include\xmemory(295): error : expected a "("
42>            instantiation of "std::basic_string<_Elem, _Traits, _Alloc>::~basic_string() [with _Elem=char, _Traits=std::char_traits<char>, _Alloc=std::allocator<char>]"
42>            instantiation of "void std::_Atomic_storage<_Ty, 4ULL>::store(std::_Atomic_storage<_Ty, 4ULL>::_TVal, std::memory_order) [with _Ty=long]"
42>          detected during:
42>D:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.32.31326\include\xstring(2593): error : expected a "("
42>          detected during:
42>            instantiation of "std::basic_string<_Elem, _Traits, _Alloc>::basic_string(_Iter, _Iter, const _Alloc &) [with _Elem=__wchar_t, _Traits=std::char_traits<__wchar_t>, _Alloc=std::allocator<__wchar_t>, _Iter=__wchar_t *, <unnamed>=0]"
42>D:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.32.31326\include\string(494): here
42>            instantiation of "std::basic_string<_Elem, std::char_traits<_Elem>, std::allocator<_Elem>> std::_Integral_to_string<_Elem,_Ty>(_Ty) [with _Elem=__wchar_t, _Ty=int]"
42>D:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.32.31326\include\string(548): here

**Comment by wangxinxin08** [comment]
你可以参考https://stackoverflow.com/questions/67732065/why-does-vs2019-pro-have-compile-errors-with-xutility-xmemory-and-atomic-when 试下，把https://github.com/PaddlePaddle/Paddle/blob/develop/cmake/flags.cmake#L33 和 https://github.com/PaddlePaddle/Paddle/blob/develop/cmake/flags.cmake#L34 删掉试试

**Comment by yhz5256** [comment]
> 你可以参考https://stackoverflow.com/questions/67732065/why-does-vs2019-pro-have-compile-errors-with-xutility-xmemory-and-atomic-when 试下，把https://github.com/PaddlePaddle/Paddle/blob/develop/cmake/flags.cmake#L33 和 https://github.com/PaddlePaddle/Paddle/blob/develop/cmake/flags.cmake#L34 删掉试试

删掉还是不行 是不是不支持visual studio 2022？

**Comment by wangxinxin08** [comment]
> > 你可以参考https://stackoverflow.com/questions/67732065/why-does-vs2019-pro-have-compile-errors-with-xutility-xmemory-and-atomic-when 试下，把https://github.com/PaddlePaddle/Paddle/blob/develop/cmake/flags.cmake#L33 和 https://github.com/PaddlePaddle/Paddle/blob/develop/cmake/flags.cmake#L34 删掉试试
> 
> 删掉还是不行 是不是不支持visual studio 2022？

建议回退下visual studio的版本到2017
