### ISSUE TITLE
paddle模型，推理时候提高GPU的使用效率

### ISSUE THREAD

**Issue by persistone** [PaddlePaddle/Paddle#42839]
### 请提出你的问题 Please ask your question

您好：最近用paddle的asr模型部署服务，想最大限度提高GPU使用效率，有哪些手段？当前想开多个子进程，并行处理语音推理，出现如下报错？
![image](https://user-images.githubusercontent.com/105772566/168971869-389951db-7bd9-4246-bfd5-e67580ba1ad2.png)
cpu 的 tensor通过_share_memory()可以多进程处理，gpu tensor不行，如何解决？

**Comment by wangxinxin08** [comment]
你是通过什么方式部署的呢？可以提供下可复现的代码吗？
