### ISSUE TITLE
【Paddle Hackthon】

### ISSUE THREAD

**Issue by yangguohao** [PaddlePaddle/Paddle#42834]
### 问题描述 Please describe your issue

Paddle C++ 算子开发的时候如何增加输入参数支持的数据类型。

在该 [PR](https://github.com/PaddlePaddle/Paddle/pull/42364), 我想要支持不同的 label 数据类型，在 Kernel 注册算子时添加不同的数据类型，
`
PD_REGISTER_KERNEL(
    soft_margin_loss,
    CPU,
    ALL_LAYOUT,
    phi::SoftMarginLossKernel,
    float,
    double,
    int,
    int64_t) {}
`

但是对于 int32，int64的数据类型会出现以下错误。

> InvalidArgumentError: The type of data we are trying to retrieve does not match the type of data currently contained in the container.
[Hint: Expected dtype() == paddle::experimental::CppTypeToDataType<T>::Type(), but received dtype():7 != paddle::experimental::CppTypeToDataType<T>::Type():13.] (at /workspace/Paddle/paddle/phi/core/dense_tensor.cc:143)

想请教一下正确的方式应该是什么。

**Comment by chenwhql** [comment]
是不是可以参考这个 https://github.com/PaddlePaddle/Paddle/blob/bebaee37e3978251a4567f7688204df585abc21d/paddle/phi/kernels/cpu/cross_entropy_grad_kernel.cc#L201
这里kernel注册的类型应该是x的类型，label的类型需要在kernel内再分发一次

**Comment by yangguohao** [comment]
> 是不是可以参考这个
> 
> https://github.com/PaddlePaddle/Paddle/blob/bebaee37e3978251a4567f7688204df585abc21d/paddle/phi/kernels/cpu/cross_entropy_grad_kernel.cc#L201
> 
> 
> 这里kernel注册的类型应该是x的类型，label的类型需要在kernel内再分发一次

这样的话我可以参考这个内容在 grad kernel 里添加吗？对于 GPU 的grad kernel 也可以同样参考该方法吗？

**Comment by yangguohao** [comment]
OK 我尝试一下看看

**Comment by chenwhql** [comment]
可以的，其实就是对第二输入需要区分不同类型的实现，在kernel内做了个二次分发，PD_VISIT_INTEGRAL_TYPES这个展开就是个switch-case语句

**Comment by yangguohao** [comment]
我尝试了一下好像编译通过不了

> #include "paddle/phi/kernels/soft_margin_loss_kernel.h"
#include <algorithm>
#include "paddle/phi/backends/cpu/cpu_context.h"
#include "paddle/phi/core/kernel_registry.h"
#include "paddle/phi/core/visit_type.h"
namespace phi {
template <typename T, typename LabelT>
void SoftMarginLossCPUKernel(const CPUContext& dev_ctx,
                   const DenseTensor& input,
                   const DenseTensor& label,
                   DenseTensor* out) {
  auto x_data = input.data<T>();
  auto label_data = label.data<T>();
  auto out_data = dev_ctx.template Alloc<T>(out);
  auto x_numel = input.numel();
  for (int64_t i = 0; i < x_numel; ++i) {
    out_data[i] =std::log(static_cast<T>(1) + std::exp(-label_data[i]* x_data[i]));
  }
}
template <typename T, typename Context>
void SoftMarginLossKernel(const Context& dev_ctx,
                          const DenseTensor& input,
                          const DenseTensor& label,
                          DenseTensor* out) {
  auto dtype = label.dtype();
  PD_VISIT_INTEGRAL_TYPES(
        dtype, "SoftMarginLossCPUKernel", ([&] {
          SoftMarginLossCPUKernel<T, data_t>(dev_ctx,
                                             input,
                                             label,
                                             out);
        }));
}
}  // namespace phi
PD_REGISTER_KERNEL(
    soft_margin_loss,
    CPU,
    ALL_LAYOUT,
    phi::SoftMarginLossKernel,
    float,
    double,) {}

我照着 cross entropy 写的，不清楚是哪里弄错了

**Comment by yangguohao** [comment]
> 可以的，其实就是对第二输入需要区分不同类型的实现，在kernel内做了个二次分发，PD_VISIT_INTEGRAL_TYPES这个展开就是个switch-case语句

这个过程不仅仅是对 GradOp，对于前向计算也同样适用

**Comment by yangguohao** [comment]
```#include "paddle/phi/kernels/soft_margin_loss_grad_kernel.h" 
#include <algorithm>
#include "paddle/phi/backends/cpu/cpu_context.h"
#include "paddle/phi/core/kernel_registry.h"
#include "paddle/phi/core/visit_type.h"

namespace phi {

template <typename T, typename LabelT>
void SoftMarginLossGradCPUKernel(const CPUContext& dev_ctx,
                                 const DenseTensor& input,
                                 const DenseTensor& label,
                                 const DenseTensor& out_grad,
                                 DenseTensor* input_grad) {
  auto dx_data = dev_ctx.template Alloc<T>(input_grad);
  auto dout_data = out_grad.data<T>();
  auto x_data = input.data<T>();
  auto label_data = label.data<LabelT>();

  int x_numel = input.numel();

  // dx = dout * (-label * exp(-label * x))/(1 + exp(-label * x ))
  for (int i = 0; i < x_numel; ++i) {
    dx_data[i] =
        dout_data[i] * ((- label_data[i]* std::exp(-label_data[i]*x_data[i] )) /
                        (static_cast<T>(1) + std::exp(-label_data[i]*x_data[i])));
  }
}

template <typename T, typename Context>
void SoftMarginLossGradKernel(const Context& dev_ctx,
                              const DenseTensor& input,
                              const DenseTensor& label,
                              const DenseTensor& out_grad,
                              DenseTensor* input_grad) {
  auto dtype = label.dtype();
  PD_VISIT_FLOATING_AND_INTEGRAL_TYPES(
    dtype, "SoftMarginLossGradCPUKernel", ([&] {
      SoftMarginLossGradCPUKernel<T, data_t>(dev_ctx,
                                             input,
                                             label,
                                             out_grad,
                                             input_grad);
    }));
}
  
}  // namespace phi

PD_REGISTER_KERNEL(
    soft_margin_loss_grad,
    CPU,
    ALL_LAYOUT,
    phi::SoftMarginLossGradKernel,
    float,
    double,) {}
```

您好能不能再麻烦帮忙看看我这里哪里出现问题了， 我的编译没办法通过
