### ISSUE TITLE
从源码编译包含TensorRT的whl文件，出现CMake Warning:   

### ISSUE THREAD

**Issue by jiguanglu** [PaddlePaddle/Paddle#42841]
### 问题描述 Issue Description

1. 首先在ubuntu18.04 中 运行git clone https://github.com/PaddlePaddle/Paddle.git  
2. 进入Paddle目录下：cd Paddle
3. 然后docker拉取的 registry.baidubce.com/paddlepaddle/paddle:2.2.2-gpu-cuda11.2-cudnn8 镜像；
4. 在Paddle目录下创建并进入镜像：nvidia-docker run --name cmake_trt -v $PWD:/paddle --network=host -it registry.baidubce.com/paddlepaddle/paddle:2.2.2-gpu-cuda11.2-cudnn8 /bin/bash。
5. 在Nvidia网站下载TensorRT-8.4.0.6, 解压放在 镜像的/paddle目录下，并写入到～/.bashrc文件中；
6. 在/paddle目录中   git checkout release/2.3；
7.  mkdir -p /paddle/build && cd /paddle/build
8. cmake .. -DPY_VERSION=3.7 -DWITH_GPU=ON -DWITH_TESTING=OFF -DCMAKE_BUILD_TYPE=Release -DWITH_ROCM=OFF -DWITH_AVX=ON -DWITH_PYTHON=ON -DWITH_MKL=OFF -DWITH_SYSTEM_BLAS=OFF -DWITH_DISTRIBUTE=OFF -DWITH_BRPC_RDMA=OFF -DON_INFER=OFF -DCUDA_ARCH_NAME=Auto -DTENSORRT_ROOT=/paddle/TensorRT-8.4.0.6/

发现下面的错误
![企业微信截图_3fdc051a-09df-4293-94c3-7079d58cd442](https://user-images.githubusercontent.com/16578290/168976122-5050d8d3-1688-46c8-84f8-00e7c022d946.png)

### 版本&环境信息 Version & Environment Information

1. paddle:2.2.2-gpu
2. ubuntu18.04
3. py3.7
4. 使用官方提供的docker镜像  registry.baidubce.com/paddlepaddle/paddle:2.2.2-gpu-cuda11.2-cudnn8
使用命令启动并进入docker：
nvidia-docker run --name cmake_trt -v $PWD:/paddle --network=host -it registry.baidubce.com/paddlepaddle/paddle:2.2.2-gpu-cuda11.2-cudnn8 /bin/bash

**Comment by wangxinxin08** [comment]
`-DWITH_TENSORRT=ON` 这个编译选项打开下试试

**Comment by jiguanglu** [comment]
@wangxinxin08 非常感谢，已经解决。
