### ISSUE TITLE
paddle v2训练有CTC层时 输入数据类别的设置

### ISSUE THREAD

**Issue by xieshufu** [PaddlePaddle/Paddle#4289]
在PADDLE v2上做一个OCR模型的训练，
字符数是95类，由于用到了CTC层，在设置类别的时候会设置为96类(95+1).
输入数据类别数目该如何设置？是设置为classdim还是classdim+1?
```
 lbl = paddle.layer.data(
        name="label", type=paddle.data_type.integer_value_sequence(classdim)) 
```

相关设置如下：
```python
classdim = 95
output = ocr_4conv_net(image, classdim+1)
  lbl = paddle.layer.data(
        name="label", type=paddle.data_type.integer_value_sequence(classdim)) 
    cost = paddle.layer.warp_ctc(input=output,
        label=lbl,
        size=classdim+1,
        blank=classdim,
        norm_by_times=True)
    ctc_eval = paddle.evaluator.ctc_error(input=output, label=lbl)
```

**Comment by luotao1** [comment]
参考 http://doc.paddlepaddle.org/develop/doc_cn/api/v2/config/layer.html#ctc 
是需要使用classdim+1的

**Comment by xieshufu** [comment]
我这里是指输入数据的类别数目？ 不是CTC那里的设置，CTC那里的设置已经进行加1操作了。

**Comment by lcy-seso** [comment]
- 输入时候类别可以随便设置。
- `type=paddle.data_type.integer_value_sequence(classdim)`中设置的类别数目没有实际的功能（仅有integer_value系列如此，其它类别请正确设置）。

**Comment by xieshufu** [comment]
lbl = paddle.layer.data(
        name="label", type=paddle.data_type.integer_value_sequence(classdim))
    cost = paddle.layer.warp_ctc(input=output, 
        label=lbl, 
        size=classdim+1,
        blank=classdim,
        norm_by_times=True)
@lcy-seso 在配合CTC层进行设置的时候， label的维数也不应该是随便设，需要设置为实际的类别数目。
CTC层里面会根据输入大小和CTC层的size大小进行检查
5281     if label.size is not None:
5282         if size is not None:
5283             assert size == label.size + 1
5284         else:
5285             size = label.size + 1

**Comment by lcy-seso** [comment]
好的，明白了。
