### ISSUE TITLE
Paddle 能否在Arm64平台支持分布式训练

### ISSUE THREAD

**Issue by liddk** [PaddlePaddle/Paddle#42893]
### 需求描述 Feature Description

任务目标：使用Paddle在Arm64上编译运行分布式训练；
;需求场景：飞腾CPU;  
功能描述：使用
cmake .. -DPY_VERSION=3 -DPYTHON_EXECUTABLE=`which python3` -DWITH_ARM=ON -DWITH_TESTING=OFF -DCMAKE_BUILD_TYPE=Release -DON_INFER=ON -DWITH_XBYAK=OFF -DWITH_DISTRIBUTE=ON -DWITH_NCCL=ON
make TARGET=ARMV8 -j$(nproc)进行编译会报错；
在编译brpc的时候显示：
error: unrecognized command line option '-msse4'
能否官方支持Arm64编译Paddle with distribution？

**Comment by wenming2014** [comment]
您好，arm cpu是不是不支持sse指令？建议您check下编译选项

**Comment by onecatcn** [comment]
您好，我们团队也希望研究一下这个问题，请问能够提供具体的硬件和环境信息吗？

**Comment by adaxiadaxi** [comment]
@liddk 您好，我们在看arm平台下支持分布式训练的编译工作，可以加我的微信我们一起对下看看，微信号：zxy8811666

**Comment by liddk** [comment]
环境信息：
CPU: Phytium,S2500/64
gcc (GCC) 9.3.1 20200408
编译选项参考issue描述

**Comment by sun-ruijiang** [comment]
请问是否已经解决了呢，我现在遇到了相同的问题
