### ISSUE TITLE
cuda算子编译成功, 运行失败,报错无法解决,求助!

### ISSUE THREAD

**Issue by hjlllll** [PaddlePaddle/Paddle#42905]
### 请提出你的问题 Please ask your question

报错信息:

File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/tracer.py", line 45, in trace_op
    not stop_gradient)
ValueError: vector::reserve

看起来是建立动态图时出现问题

**Comment by hjlllll** [comment]
加载算子时使用即时编译方式, from paddle.utils.cpp_extension import load

**Comment by hjlllll** [comment]
项目“paconv_paddle”共享链接(有效期三天)：https://aistudio.baidu.com/studio/project/partial/verify/3866290/0744ddd048cd47599ee61106ddce753d

项目“paconv_paddle”共享链接(有效期三天)：https://aistudio.baidu.com/studio/project/partial/verify/3866290/971b068151e44b3a9922b90210663afa
运行 
cd work/obj_cls 
python main_paddle.py --config config/dgcnn_paconv_train_paddle.yaml

**Comment by JunnYu** [comment]
我看你参数传递的顺序不对，应该是先传tensor然后才是传那些int类型的属性。这样改完后还是运行错误，估计算子里面写错了
（PS：我是热心群众）
