### ISSUE TITLE
Gloo not disabled by WITH_DISTRIBUTE=OFF

### ISSUE THREAD

**Issue by bulvara** [PaddlePaddle/Paddle#42907]
### 问题描述 Issue Description

Gloo is not disabled by the CMake build option `-DWITH_DISTRIBUTE=OFF`

`PADDLE_WITH_GLOO` is just a runtime and not a build time option.

Please supply an option to compile PaddlePaddle without Gloo (on par with PyTorch's `USE_GLOO=OFF`) when the build shall just run locally.

### 版本&环境信息 Version & Environment Information

Paddle version: None
Paddle With CUDA: None

OS: Arch Linux rolling
Python version: 3.10.4

CUDA version: None
cuDNN version: None.None.None
Nvidia driver version: None

**Comment by LiuChiachi** [comment]
您好，感谢反馈:)我们已经联系了分布式的同学帮忙解决

**Comment by wangxicoding** [comment]
-DWITH_GLOO=OFF
可以参考这个 https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/scripts/paddle_build.sh#L207-L208
