### ISSUE TITLE
百度飞桨书籍

### ISSUE THREAD

**Issue by yuwoyizhan** [PaddlePaddle/Paddle#42911]
### 请提出你的问题 Please ask your question

1.昨天20号,飞桨开了一个发布会,发布会上提到2本书,我不太明白什么意思.这两本书都出版2年左右了,现在飞桨是打算对这两本书出第二版吗?《人工智能导论：案例与实践》和《神经网络与深度学习：案例与实践》,就是这两本书.如果是打算出第二版,能给个大概出版日期吗?
2.我在京东搜索飞桨,搜索到3本图书,其中有一本是《零基础实践深度学习》书籍,之前提issue,你们说估计5月底出版第二版,适配动态图,现在21号了,还没出版吗?有具体出版日期吗?京东搜索到的另外两本飞桨书籍,打算出第二版吗?

**Comment by LiuChiachi** [comment]
@wulei123456789 是否可以帮忙回答一下呢，谢谢

**Comment by wulei123456789** [comment]
> 
亲爱的开发者朋友，
您好！
感谢您参加WAVE SUMMIT峰会，并持续关注和支持飞桨各项特性的发布。

关于您提出的问题回复如下：

1）《人工智能导论：案例与实践》是《人工智能导论：模型和算法》的配套实践书籍，由飞桨教材编写组与浙大吴飞老师、朱强老师合作开发。在《人工智能导论：模型和算法》理论解读的基础上，配套设计了一系列的实践案例。目前书稿已经进入高教社审校中，预计Q3上市。当前实践部分的线上课程已经开源，您可以登录AI Studio学习：https://aistudio.baidu.com/aistudio/education/group/info/25224，并持续关注课程公告中书籍上市信息。

2）《神经网络与深度学习：案例与实践》是《神经网络与深度学习》（蒲公英书）的配套实践书籍，由飞桨与复旦邱锡鹏老师合作开发，帮助读者在动手实践中更好的掌握模型和算法，并掌握从零开始搭建自己的算子库的方法。本书预计6月份上市，当前实践部分的线上课程已经开源，您可以登录AI Studio学习：当前实践部分的线上课程已经开源，您可以登录AI Studio学习：https://aistudio.baidu.com/aistudio/education/group/info/25224，并持续关注课程公告中书籍上市信息。

3）《零基础实践深度学习》第二版目前在清华社审校中，具体上市时间可以关注课程公告。目前在线课程已经适配飞桨框架V2.3版本，欢迎您在线学习。

再次感谢您对飞桨教育产品的支持，祝好！
