### ISSUE TITLE
PaddlePaddle + Gradio Blocks

### ISSUE THREAD

**Issue by AK391** [PaddlePaddle/Paddle#42918]
### 问题描述 Please describe your issue

Hi, PaddleHub models are on Hugging Face https://huggingface.co/PaddlePaddle using Gradio, it would be great if paddlepaddle developers can join the Gradio Blocks hackathon this month to build demos with paddlepaddle using Gradio Blocks or share with others who might be interested, thanks, link to hackathon: https://huggingface.co/Gradio-Blocks

**Comment by jzhang533** [comment]
Hi, we have included this issue into our pinned community events navigation page: #42410 .
