### ISSUE TITLE
paddle2.0 ，静态图网络参数不优化

### ISSUE THREAD

**Issue by HarryUP-rhy** [PaddlePaddle/Paddle#42913]
### bug描述 Describe the Bug

在paddle2.0静态图中，LSTM网络，向网络输入收盘价及其他特征预测交易动作，根据动作获取每轮交易的夏普率，并将夏普率当作目标函数来优化，使夏普率最大。
代码以及输出信息在连接中
https://aistudio.baidu.com/ibdcpu1/user/683708/2605402/notebooks/2605402.ipynb

**Comment by LiuChiachi** [comment]
您好，您的代码可能没有公开，我这里好像看不到，可以公开一下项目或者贴出核心代码吗，谢谢:)

**Comment by HarryUP-rhy** [comment]
> 您好，您的代码可能没有公开，我这里好像看不到，可以公开一下项目或者贴出核心代码吗，谢谢:)

https://aistudio.baidu.com/aistudio/projectoverview/public?kw=teiaoshi
公开了呀，试试这个链接吧！

**Comment by LiuChiachi** [comment]
Hello，我找到一个版本相近API 写的的示例代码，https://github.com/PaddlePaddle/models/blob/08316fb833602f26d718defe2f40b81c1b8bc27a/PaddleNLP/seq2seq/seq2seq/train.py#L77 ，会不会是program这里定义的时候没有加 with guard

**Comment by RenHyz** [comment]
意思是在我写的infer_act_program之后再把网络定义和损失函数定义写在with fluid.program_guard(train_program, startup_program)里面，然后在训练的时候再调用train_program吗？

**Comment by HarryUP-rhy** [comment]
> Hello，我找到一个版本相近API 写的的示例代码，[https://github.com/PaddlePaddle/models/blob/08316fb833602f26d718defe2f40b81c1b8bc27a/PaddleNLP/seq2seq/seq2seq/train.py#L77，会不会是program这里定义的时候没有加](https://github.com/PaddlePaddle/models/blob/08316fb833602f26d718defe2f40b81c1b8bc27a/PaddleNLP/seq2seq/seq2seq/train.py#L77%EF%BC%8C%E4%BC%9A%E4%B8%8D%E4%BC%9A%E6%98%AFprogram%E8%BF%99%E9%87%8C%E5%AE%9A%E4%B9%89%E7%9A%84%E6%97%B6%E5%80%99%E6%B2%A1%E6%9C%89%E5%8A%A0) with guard

意思是在我写的infer_act_program之后再把网络定义和损失函数定义写在with fluid.program_guard(train_program, startup_program)里面，然后在训练的时候再调用train_program吗？

**Comment by LiuChiachi** [comment]
我不确定现在的写法训练用的program是哪一部分，train调用的train_program需要包括损失函数的计算，梯度计算、参数更新那部分，而inference_program则不需要参数更新的那部分代码。看起来是你的参数没有更新，可能需要检查下train_program这部分的代码。你在debug的时候也可以把网络中间变量的梯度加到fetch_list里打印出来看看是不是正常的
