### ISSUE TITLE
Hint: 'cudaErrorUnknown'. This indicates that an unknown internal error has occurred. 

### ISSUE THREAD

**Issue by KangChou** [PaddlePaddle/Paddle#42924]
### bug描述 Describe the Bug

```
for i in range(core.get_cuda_device_count()):
OSError: (External) CUDA error(999), unknown error. 
  [Hint: 'cudaErrorUnknown'. This indicates that an unknown internal error has occurred. ] (at /paddle/paddle/phi/backends/gpu/cuda/cuda_info.cc:66)


```

### 其他补充信息 Additional Supplementary Information

paddlepaddle-gpu-2.3.0

https://github.com/baidu/DDParser

DDParser/ddparser# bash run_predict.sh

**Comment by cuicheng01** [comment]
hi，请问paddlepaddle-gpu是如何安装的呢？是否和cuda版本相匹配呢？

**Comment by KangChou** [comment]
> hi，请问paddlepaddle-gpu是如何安装的呢？是否和cuda版本相匹配呢？

是的，已经正确安装，版本是2.3

env:

python3.6+anaconda3+ubuntu16.04+docker

@cuicheng01 @paddle-bot

**Comment by cuicheng01** [comment]
请问paddlepaddle-gpu是如何安装的呢？可以贴一下对应的安装命令吗

**Comment by GodfatherPacino** [comment]
请问解决了吗？我也遇到了相同的问题

**Comment by KangChou** [comment]
> paddlepaddle

https://blog.csdn.net/weixin_41194129/article/details/120102509

**Comment by KangChou** [comment]
> 请询问paddlepaddle-gpu是如何安装的呢？可以贴一下对应的安装命令吗

https://blog.csdn.net/weixin_41194129/article/details/120102509

**Comment by KangChou** [comment]
> hi，请问paddlepaddle-gpu是怎么安装的呢？是不是和cuda版本相配呢？

https://blog.csdn.net/weixin_41194129/article/details/120102509

**Comment by hbo-lambda** [comment]
真是绝了，我也报了这个错，然后就有个僵尸进程挂在那儿了，也kill不掉，还得重启

**Comment by pys0126** [comment]
> 真是绝了，我也报了这个错，然后就有个僵尸进程挂在那儿了，也kill不掉，还得重启

我也是这样，请问一下目前解决了吗
