### ISSUE TITLE
动转静态图，不支持to_tensor()

### ISSUE THREAD

**Issue by jiuwuxiaohun** [PaddlePaddle/Paddle#42920]
### bug描述 Describe the Bug

```
# paddlepaddle <= 2.2.2
# paddlenlp <= 2.3.1

import paddle
from paddlenlp.transformers import *

model = T5ForConditionalGeneration.from_pretrained("t5-small")
jit_model = paddle.jit.to_static(model, 
input_spec=[
    paddle.static.InputSpec(shape=[None, 512], dtype='int64'), 
    paddle.static.InputSpec(shape=[None, 512], dtype='int64'),
    ])
paddle.jit.save(jit_model, "./export")
```

T5系列的模型均不可以转换，比如 Langboat/mengzi-t5-base  t5-small  t5-large

报错为：
We only support 'to_tensor()' in dynamic graph mode, please call 'paddle.disable_static()' to enter dynamic graph mode.

这是需要模型修改，还是需要paddle修改呢？还是paddleNlp团队修改呢？

**Comment by yghstill** [comment]
@jiuwuxiaohun 感谢反馈，我们联系PaddleNLP同学看下这个问题~

**Comment by yingyibiao** [comment]
您好，我们目前还没有支持 T5 模型动转静，这个功能后续会由 PaddleNLP 进行支持。
