### ISSUE TITLE
PaddleInference C API should support PaddlePassBuilder class in C++ API

### ISSUE THREAD

**Issue by sdcb** [PaddlePaddle/Paddle#42937]
### bug描述 Describe the Bug

Here is the C++ API: 
https://paddle-inference.readthedocs.io/en/latest/api_reference/cxx_api_doc/PaddlePassBuilder.html

This one was not provided in C API, please also add it in C.

### 其他补充信息 Additional Supplementary Information

In latest PaddleOCR v3, it calls `pass_builder()` to adjust some parameters, this ability should able to migrate into C API so that it can be further been used with .NET: 
* https://github.com/PaddlePaddle/PaddleOCR/commit/369889b6e009e2a8f85253abe5d03c652056c514#diff-864f746abc45f2521026f4166ef3f797d9a2aa7bc00d225ef6d0d42acd9da838R169-R172
* https://github.com/sdcb/PaddleSharp (my port of PaddleOCR/Paddle)

**Comment by zhangjun** [comment]
@sdcb 你好。我们内部评估下，C API 是否暴露这个接口。

**Comment by sdcb** [comment]
> @sdcb 你好。我们内部评估下，C API 是否暴露这个接口。

@zhangjun 我的意见，供你们参考：
C API必须暴露这个接口，因为C++的[示例](https://github.com/PaddlePaddle/PaddleOCR/commit/369889b6e009e2a8f85253abe5d03c652056c514#diff-864f746abc45f2521026f4166ef3f797d9a2aa7bc00d225ef6d0d42acd9da838R169-R172)中使用了这个API，且使用C API没办法规避。

**Comment by zhangjun** [comment]
> > @sdcb 你好。我们内部评估下，C API 是否暴露这个接口。
> 
> @zhangjun 我的意见，供你们参考： C API必须暴露这个接口，因为C++的[示例](https://github.com/PaddlePaddle/PaddleOCR/commit/369889b6e009e2a8f85253abe5d03c652056c514#diff-864f746abc45f2521026f4166ef3f797d9a2aa7bc00d225ef6d0d42acd9da838R169-R172)中使用了这个API，且使用C API没办法规避。

@sdcb 这个接口是有暴露的，参见https://github.com/PaddlePaddle/Paddle/blob/f87fa3c0e5d0ebf89b336cf16c4d1eb0b8767b25/paddle/fluid/inference/capi/pd_config.cc#L431。 C API文档没有更新这部分，我们会安排对文档进行更新。

非常抱歉给您带来困扰，感谢您指出的不足和建议，我们将持续改进来提供较好的用户体验。
