### ISSUE TITLE
reshape 比如[24,768] reshape [8,3,768] 8代表batch size，但是有时候batch size是不满的，【24，768】就有可能是【18，768】，怎么动态调整reshape的第一维

### ISSUE THREAD

**Issue by yangyan1227** [PaddlePaddle/Paddle#42948]
### 需求描述 Feature Description

任务目标（请描述你正在做的项目是什么，如模型、论文、项目是什么？）; <br /> 需求场景（请描述你的项目中为什么需要用此功能）;  <br /> 功能描述（请简单描述或设计这个功能）

**Comment by cxxly** [comment]
需求描述的不太清楚，不太能明白您的意思。

reshape前后元素个数必须保持一致，如果reshape后某一个轴的形状不确定，可以-1表示

**Comment by yangyan1227** [comment]
明白 谢谢您的回复
