### ISSUE TITLE
和谷歌原生的Camera以及UVCCameraTextureView相结合

### ISSUE THREAD

**Issue by jeekMic** [PaddlePaddle/Paddle#42954]
### 需求描述 Feature Description

现在的demo上是基于OpenGL来渲染绘制的，但是最好能在uvc和普通的相机上能有结果就比如谷歌自带相机打开的那样

**Comment by cxxly** [comment]
您好，没太明白您的需求，能具体描述下吗？
是对PaddlePaddle主框架功能的需求，还是对计算机视觉套件需求？

**Comment by jeekMic** [comment]
> 
    public boolean process(int inTextureId, int outTextureId, int textureWidth, int textureHeight, String savedImagePath) {
        if (ctx == 0) {
            return false;
        }
        return nativeProcess(ctx, inTextureId, outTextureId, textureWidth, textureHeight, savedImagePath);
    }
是这样的 我看到这个接口是处理纹理的接口，有直接对camera相机的那种byte[] 数据处理的吗

**Comment by jeekMic** [comment]
我这边现在用的是UVC相机，没办法拿到这个纹理inTextureId，这个接口用不起来

**Comment by jeekMic** [comment]
mFaceSurfaceView.setSurfaceTextureListener(new TextureView.SurfaceTextureListener() {
            @Override
            public void onSurfaceTextureAvailable(SurfaceTexture surfaceTexture, int i, int i1) {

            }

            @Override
            public void onSurfaceTextureSizeChanged(SurfaceTexture surfaceTexture, int i, int i1) {

            }

            @Override
            public boolean onSurfaceTextureDestroyed(SurfaceTexture surfaceTexture) {
                return false;
            }

            @Override
            public void onSurfaceTextureUpdated(SurfaceTexture surfaceTexture) {

            }
        });
怎么在这种回调下使用呢

**Comment by cxxly** [comment]
> > 
> 
> ```
> public boolean process(int inTextureId, int outTextureId, int textureWidth, int textureHeight, String savedImagePath) {
>     if (ctx == 0) {
>         return false;
>     }
>     return nativeProcess(ctx, inTextureId, outTextureId, textureWidth, textureHeight, savedImagePath);
> }
> ```
> 
> 是这样的 我看到这个接口是处理纹理的接口，有直接对camera相机的那种byte[] 数据处理的吗

这个接口实在哪地方看到的，方便发给我个链接吗？我好引导您到正确地方提问。
这个repo的issue主要跟进PaddlePaddle框架本身的一些问题，没有类似接口。

**Comment by jeekMic** [comment]
https://github.com/PaddlePaddle/Paddle-Lite-Demo  是在这里提问吗？就是这里面的demo的接口

**Comment by jeekMic** [comment]
> 

可能是我问错了地方 我那个接口是PaddleLite 部署到安装Android上的那个接口

**Comment by cxxly** [comment]
好的，可以去这个repo下https://github.com/PaddlePaddle/Paddle-Lite 提下issue .
