### ISSUE TITLE
Jetson Nano用FP16模式推理MobileNetV1, 在BS=1的情况下性能不如FP32模式.

### ISSUE THREAD

**Issue by Water2style** [PaddlePaddle/Paddle#42966]
### 请提出你的问题 Please ask your question

Jetson Nano用FP16模式推理MobileNetV1, 在BS=1的情况下性能不如FP32模式.

当BS设置为2或者更高的时候, 才能看到FP16模式带来的受益. 这个原因可能是计算更密集了, 所以带来一定收益. (比如ResNet50的FP16在BS=1下, 是比FP32快的)

但是M为什么MobileNetV1在BS=1的时候, FP16跑的反而比FP32慢呢? 按理说FP16的引擎准备是在推理之前就完成了.
那难道推理中,FP16模式还会有其他的开销? 

谢谢

**Comment by heliqi** [comment]
1. 并不是所有op都是用FP16运行。 如果计算量太小，FP16的加速效果还抵不上数据格式转换带来的开销。
2. nano没有fp16的tensor core，所有加速效果也不会特别大。 带FP16的tensor core硬件可以看这个文档： https://docs.nvidia.com/deeplearning/tensorrt/support-matrix/index.html

<img width="1021" alt="d79b41557c6e892b469ffb5455ba49e6" src="https://user-images.githubusercontent.com/34152981/170210114-e6851005-9a33-46c8-abb3-ad7b5e2e3c94.png">

**Comment by Water2style** [comment]
> 1. 并不是所有op都是用FP16运行。 如果计算量太小，FP16的加速效果还抵不上数据格式转换带来的开销。
> 2. nano没有fp16的tensor core，所有加速效果也不会特别大。 带FP16的tensor core硬件可以看这个文档： https://docs.nvidia.com/deeplearning/tensorrt/support-matrix/index.html
> 
> <img alt="d79b41557c6e892b469ffb5455ba49e6" width="1021" src="https://user-images.githubusercontent.com/34152981/170210114-e6851005-9a33-46c8-abb3-ad7b5e2e3c94.png">

感谢回复.
对于问题1, 那是在inference的时候也会存在数据格式的转换吗?比如在运行时会有FP32-FP16-FP32的转换.  我之前以为是在编译engine的时候就转换好了.

**Comment by heliqi** [comment]
1. 如果是FP16节点的权重，会在初始化时转换好
2. 如果FP16节点的输入是计算产出的Tensor，必须要在运行时等上一个op计算完才会转换数据格式
