### ISSUE TITLE
咨询一下关于paddle resnet50模型动态图concat reduce_mean、reduce_mean_grad、c_broadcast 的作用

### ISSUE THREAD

**Issue by daming5432** [PaddlePaddle/Paddle#42973]
### 请提出你的问题 Please ask your question

你好，在打印模型训练log时发现resnet50会执行到concat、reduce_mean、reduce_mean_grad、c_braodcast这些op。我用
netron打开保存的模型并没有发现这些op。能帮忙解释一下为什么会用到这些op，以及这些op在训练过程中的作用吗？非常感谢~

**Comment by tianxin1860** [comment]
都是一些常规的对 Tensor 进行常规操作的 OP， 如果要关注每个 op 的具体说明，可以查询 paddle API 说明文档。

**Comment by tianxin1860** [comment]
用 netron 打开的模型是 inference_model 吧？在保存 inference_model 的时候会裁剪掉一部分在预测阶段不会使用到的 OP.
