### ISSUE TITLE
使用场景：listwise训练方式下，输入，query+ para1+para2+para3.... 0 1 2, 但是每个query下的para数量不同，每个query+[seq]+para 输入transformer，所以在transformer之后CLS维度是[batch size, para_num, hiddien size]]，因为每个query下的para数量不同，所以需要做padding处理，请问怎么做padding处理？

### ISSUE THREAD

**Issue by yangyan1227** [PaddlePaddle/Paddle#42975]
### 请提出你的问题 Please ask your question

使用场景：listwise训练方式下，输入，query+ para1+para2+para3.... 0 1 2, 但是每个query下的para数量不同，每个query+[seq]+para 输入transformer，所以在transformer之后CLS维度是[batch size, para_num, hiddien size]]，因为每个query下的para数量不同，所以需要做padding处理，请问怎么做padding处理？

**Comment by tianxin1860** [comment]
如线下沟通，在数据组 batch 阶段通过动态 batch 即可。
