### ISSUE TITLE
Low performance while inference speech model with mkldnn under dynamic shape

### ISSUE THREAD

**Issue by jiangjiajun** [PaddlePaddle/Paddle#42980]
### 需求描述 Feature Description

任务目标（请描述你正在做的项目是什么，如模型、论文、项目是什么？）; <br /> 需求场景（请描述你的项目中为什么需要用此功能）;  <br /> 功能描述（请简单描述或设计这个功能）

### 替代实现 Alternatives

PaddleSpeech requires dynamic shape while inference, but while `enable_mkldnn`, it shows low performance compare with `disable_mkldnn`

Here is the steps to run speech model, include two models `fast_speech` and `hifigan`
```
1. git clone https://github.com/PaddlePaddle/PaddleSpeech.git
2. cd PaddleSpeech && pip install . （Do not use `python setup.py install`, it will not install all the requirements automatically）
3. sudo apt-get install libsndfile1
4. cd examples/csmsc/tts3
5. wget https://paddlespeech.bj.bcebos.com/Parakeet/released_models/fastspeech2/fastspeech2_csmsc_static_0.2.0.zip
6. wget https://paddlespeech.bj.bcebos.com/Parakeet/released_models/hifigan/hifigan_csmsc_static_0.1.1.zip
7. unzip fastspeech2_csmsc_static_0.2.0.zip
8. unzip hifigan_csmsc_static_0.1.1.zip
9. vim local/inference.sh , `stage=2` and `stop_stage=2`, it means the decoder will use hifigan model
10. mkdir -p exp/default/inference
11. cp fastspeech2_csmsc_static_0.2.0/fastspeech2_csmsc.* exp/default/inference
12. cp hifigan_csmsc_static_0.1.1/hifigan_csmsc.* exp/default/inference
13. mkdir dump
14. cp fastspeech2_csmsc_static_0.2.0/phone_id_map.txt dump
15. ./run.sh --stage 4 --stop-stage 4
16. The generated voices saved in exp/default/pd_infer_out
```
@yaomichael

**Comment by jczaja** [comment]
@jiangjiajun Hi, I have run experiments according to provided instructions and I did not observe lower performance of oneDNN solution relatively to CPU . Here are results:

**CPU(disabled mkldnn):**         generation speed: 19445.28208386203Hz, RTF: 1.2342325452772942
**oneDNN(enabled mkldnn):** generation speed: 25044.155138941118Hz, RTF: 0.9583074320875148 

### Details:
**PaddlePaddle:** commit d828ca460a89c2ce88be15bb5cdb76c676decf91 (recent develop)
**Processor:**  Intel(R) Xeon(R) Gold 6248 CPU @ 2.50GHz 
**OS:**  CentOS Linux release 8.5.2111
**Python:** 3.9
**Command:**  ./run.sh --stage 4 --stop-stage 4 
**Enabling oneDNN:** Added config.enable_mkldnn() here:  https://github.com/PaddlePaddle/PaddleSpeech/blob/45426846942f68cf43a23677d8d55f6d4ab93ab1/paddlespeech/t2s/exps/syn_utils.py#L379

Please retest using commit I used and if problem is still there then please post more details: processor, OS, python, cmake commandline used and results you have (generation speed)

**Comment by jczaja** [comment]
@jiangjiajun 
From oneDNN point of view , to have extra speedup it would be good to get rid of  excessive operations of squeeze and unsqueeze e.g.  squeeze->leaky_relu->unsqueeze     should be turned into leaky_relu (see red box on picture)
![42980](https://user-images.githubusercontent.com/15085062/203810467-2373aad8-1e74-4755-821d-b079274aad6b.png)
