### ISSUE TITLE
安装paddle深度学习GPU版本报错

### ISSUE THREAD

**Issue by lh170826** [PaddlePaddle/Paddle#42988]
### 请提出你的问题 Please ask your question

安装paddle的时候，需要提前安装cuda和cudnn吗？  我直接使用命令conda install paddlepaddle-gpu==2.3.0 cudatoolkit=11.2 -c https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/Paddle/ -c conda-forge
然后安装完，验证失败了。
报错：
CondaHTTPError: HTTP 000 CONNECTION FAILED for url <https://conda.anaconda.org/conda-forge/win-64/xz-5.2.5-h62dcd97_1.tar.bz2>
Elapsed: -

An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.

CondaHTTPError: HTTP 000 CONNECTION FAILED for url <https://conda.anaconda.org/conda-forge/win-64/m2w64-gcc-libs-5.3.0-7.tar.bz2>
Elapsed: -

An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.

CondaHTTPError: HTTP 000 CONNECTION FAILED for url <https://conda.anaconda.org/conda-forge/win-64/libpng-1.6.37-h1d00b33_2.tar.bz2>
Elapsed: -

An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.

CondaError: Downloaded bytes did not match Content-Length
  url: https://conda.anaconda.org/conda-forge/win-64/mkl-2022.0.0-h0e2418a_796.tar.bz2
  target_path: E:\programData\Anaconda3\pkgs\mkl-2022.0.0-h0e2418a_796.tar.bz2
  Content-Length: 190689873
  downloaded bytes: 176388538

**Comment by lh170826** [comment]
然后我去anaconda下载了一个mkl的mkl-2022.0.0-haa95532_115.tar包，然后在我的(paddle_env) C:\Users\Administrator>conda install mkl-2022.0.0-haa95532_115.tar报错：
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.

PackagesNotFoundError: The following packages are not available from current channels:

  - mkl-2022.0.0-haa95532_115.tar

Current channels:

  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/win-64
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/noarch
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/win-64
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/noarch
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch/win-64
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch/noarch
  - http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/win-64
  - http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/noarch
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/win-64
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/noarch
  - http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/msys2/win-64
  - http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/msys2/noarch
  - http://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/win-64
  - http://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/noarch
  - http://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/win-64
  - http://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/noarch
  - https://repo.anaconda.com/pkgs/main/win-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/win-64
  - https://repo.anaconda.com/pkgs/r/noarch
  - https://repo.anaconda.com/pkgs/msys2/win-64
  - https://repo.anaconda.com/pkgs/msys2/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.

**Comment by tianxin1860** [comment]
看报错信息是 http 网络代理有问题，可以先检查下网络代理。

**Comment by lh170826** [comment]
> 

谢谢，我想问的是，如果是GPU版本的，是不是需要在电脑上独立的安装一个CUDA？  还是说不需要额外安装，直接使用这一句conda install paddlepaddle-gpu==2.3.0 cudatoolkit=11.2 -c https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/Paddle/ -c conda-forge

就默认的安装带的就又cuda加速和cudnn计算的？

**Comment by XieYunshen** [comment]
> > 
> 
> 谢谢，我想问的是，如果是GPU版本的，是不是需要在电脑上独立的安装一个CUDA？ 还是说不需要额外安装，直接使用这一句conda install paddlepaddle-gpu==2.3.0 cudatoolkit=11.2 -c https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/Paddle/ -c conda-forge
> 
> 就默认的安装带的就又cuda加速和cudnn计算的？

有CUDA驱动就可以，不需要单独安装cuda和cudnn；
如果网络不好，可以下载到本地安装，下载链接：https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/Paddle/win-64/
安装命令：
`conda install -c local xxx.tar.bz2; conda install -c local paddlepaddle-gpu`

**Comment by tianxin1860** [comment]
conda install paddlepaddle-gpu==2.3.0 cudatoolkit=11.2  之后，不需要再额外安装一个独立的 CUDA。
