### ISSUE TITLE
如何解决跨层的L2目标函数的问题？

### ISSUE THREAD

**Issue by joseph-chan** [PaddlePaddle/Paddle#4299]
我需要实现一个autoencoder，是一个包含一个隐藏层的autoencoder网络，如下：

![1](https://user-images.githubusercontent.com/11705586/30687984-837e28fe-9eef-11e7-98ec-6b32d74ada77.png)

目标函数既包含第一层的权重L2，又包含第二层的权重L2，跨层的L2
![2](https://user-images.githubusercontent.com/11705586/30687991-8a10a0d4-9eef-11e7-8368-e780ffd39545.png)

如何实现这样的目标函数？有对应的demo吗？

**Comment by lcy-seso** [comment]
- 同学，你提到的 L2 是指 L2 正则，而在神经网络中，正则和损失函数是分开的两个部分。并不需要显示的将正则定义在损失函数里面。

- 设置方法如下：
https://github.com/PaddlePaddle/models/blob/develop/mt_with_external_memory/train.py#L73
