### ISSUE TITLE
paddle gpu 环境配置失败

### ISSUE THREAD

**Issue by DoctorAwe** [PaddlePaddle/Paddle#43000]
### 请提出你的问题 Please ask your question

硬件：rtx3050ti
采用anaconda配置环境，尝试过多个版本的pp框架和对应的多种cuda版本，通过run_check（）检验环境配置，运行到此处
![409F39B1-499D-462D-81C6-795EB3A4CD72](https://user-images.githubusercontent.com/61052186/170401933-0d7c8655-4ddd-43f4-92c7-5747986b9efe.png)
就会卡运行。
求解决方案
![F86E6E2B-B547-48FA-859D-2CA96972557D](https://user-images.githubusercontent.com/61052186/170402106-0ba1480d-7e79-40c4-8270-88f173f9938c.png)
![B063E60B-7917-4898-9EF1-D6BBD11E1F38](https://user-images.githubusercontent.com/61052186/170402110-83d617bb-c9ea-40c0-aab4-99b0d297f109.png)

**Comment by esythan** [comment]
麻烦给一个可以复现的环境和pp版本
