### ISSUE TITLE
如何指定算子输入输出类型

### ISSUE THREAD

**Issue by leelinglin** [PaddlePaddle/Paddle#43018]
如何指定一个算子的输入输出的dtype？例如layers.matmul（）我想指定输入为float16，输出为float32

**Comment by esythan** [comment]
算子输入的dtype由算子的input tensor决定，不需要手动指定，输出tensor的dtype通常与输入tensor相同，如果想要改变tensor的dtype，可使用paddle.cast进行类型转换
