### ISSUE TITLE
编译c-api源码出错

### ISSUE THREAD

**Issue by thomaslwang** [PaddlePaddle/Paddle#4302]
running build_scripts
error: file '/home/tom/workspace/paddle/build/paddle/trainer/paddle_trainer' does not exist
make[2]: *** [python/build/.timestamp] Error 1
make[1]: *** [python/CMakeFiles/paddle_python.dir/all] Error 2
make: *** [all] Error 2

**Comment by typhoonzero** [comment]
请补充：
1. paddle版本

**Comment by thomaslwang** [comment]
Ubuntu 14.04.3 amd64
paddle develop 最新
cmake -DWITH_C_API=ON -DWITH_SWIG_PY=OFF -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/home/paddle ..

**Comment by Xreki** [comment]
- 设置`WITH_PYTHON=OFF`
- 错误信息不全，请贴出执行`make`命令时最早出错的地方

**Comment by thomaslwang** [comment]
就是这个问题，加了WITH_PYTHON=OFF之后就解决了。

**Comment by gongweibao** [comment]
不是很清楚为什么要自己编译？

**Comment by thomaslwang** [comment]
需要个在ubuntu上用的binary
