### ISSUE TITLE
paddle.grid_sample反向传播错误

### ISSUE THREAD

**Issue by bitcjm** [PaddlePaddle/Paddle#43022]
### bug描述 Describe the Bug

对模型的输出用paddle.grid_sample进行处理，用grid_sample处理结果计算损失函数的话，将该损失函数反向传播就会出现以下错误：

'''

  File "trainer_640.py", line 291, in process_batch
    loss_test.backward()
  File "<decorator-gen-133>", line 2, in backward
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
    return wrapped_func(*args, **kwargs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/framework.py", line 434, in __impl__
    return func(*args, **kwargs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/varbase_patch_methods.py", line 292, in backward
    framework._dygraph_tracer())
ValueError: (InvalidArgument) Required tensor shall not be nullptr, but received nullptr.
  [Hint: tensor should not be null.] (at /paddle/paddle/phi/core/device_context.cc:100)

'''

项目链接：
我提供了可复现错误的aistudio项目，并在项目中对如何得出报错进行了详细说明。请参考下面链接中的“报错提issue版本”：
https://aistudio.baidu.com/aistudio/projectdetail/4097726?contributionType=1

**Comment by bitcjm** [comment]
在尝试提取最小可复现代码的过程中，我提取了一组grid_sample的输入并保存。之后用test_simple.py测试，发现可以正常反传无问题。所以可能该问题比较复杂，也和模型或者计算损失函数的一些过程有关系。运行下面kernel即可用test_simple.py做测试。

新增代码可以查看上面项目链接的草稿版本。由于aistudio出现错误我无法保存正式版本，所以这部分内容只能暂时存放在草稿版本中，后续如果可以报错我会命名为《报错提issue——2》

**Comment by esythan** [comment]
单从aistudio上的报错来看，目前代码中使用的是静态图，但输入方面使用了只有动态图才能使用的to_tensor api导致输入tensor为空。

**Comment by GSHZhang** [comment]
ValueError: (InvalidArgument) Required tensor shall not be nullptr, but received nullptr.
  [Hint: tensor should not be null.] (at /paddle/paddle/phi/core/device_context.cc:100)

**Comment by GSHZhang** [comment]
ValueError: (InvalidArgument) Required tensor shall not be nullptr, but received nullptr.
  [Hint: tensor should not be null.] (at /paddle/paddle/phi/core/device_context.cc:100)

**Comment by Semonlkf** [comment]
我也同样遇到了这样的问题，当我运行这段代码时
for epoch in range(1,args.e+1):
        # print(f"-----Epoch {epoch} / {args.e}-----")
        train_epoch_loss = 0
        train_reg_loss = 0
        vis_batch = []
        model.train()
        for iteration in tqdm(range(1,args.i+1),desc=f"Train_Epoch {epoch}/{args.e}",ascii=True,total=args.i):
            optim.clear_grad()
            fixed,moving=next(iter(train_loader))
            # fixed_tensor=paddle.to_tensor(fixed)
            # moving=paddle.to_tensor(moving)
            warped, flows = model(fixed, moving)
            # warped_tensor=paddle.to_tensor(warped)
            # flows_tensor=paddle.to_tensor(flows)
            loss, reg = total_loss(fixed, warped[-1], flows)
            # loss=mse_loss(warped[-1],fixed)
            # loss = paddle.to_tensor(loss)
            loss.backward()

            optim.step()
            train_epoch_loss += loss.item()
            train_reg_loss += reg.item()
            if iteration == args.fixed_sample:
                vis_batch.append(fixed)
                vis_batch.append(moving)
                vis_batch.append(warped)
                vis_batch.append(flows)

        train_loss_log.append(train_epoch_loss / args.i)
        reg_loss_log.append(train_reg_loss / args.i)

        model.eval()
        val_epoch_loss = 0
loss.backward()会报出同样的错误，这很奇怪，我在这之前输出了loss,它确实是Tensor形式，Tensor(shape=[1], dtype=float32, place=Place(gpu:0), stop_gradient=False,
       [0.47685456])，但是更奇怪的是，当我使用loss=paddle.to_tensor(loss)时，它竟然恢复了运行。
