### ISSUE TITLE
test_analysis_predictor测试用例代码存在问题

### ISSUE THREAD

**Issue by liddk** [PaddlePaddle/Paddle#43023]
### bug描述 Describe the Bug

https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/fluid/inference/api/analysis_predictor_tester.cc#L529
`   float* out_data = nullptr;
  auto out_size = std::accumulate(out_shape.begin(), out_shape.end(), 1,
                                  std::multiplies<int>()) *
                  sizeof(float);
  cudaMalloc(reinterpret_cast<void**>(out_data), out_size * sizeof(float));`
out_data是否需要加&？

**Comment by zhangjun** [comment]
@liddk 感谢提醒，这个参数应该作为双指针传入，应该加上&。
