### ISSUE TITLE
c-api 如何处理双层序列作为输入数据进行预测？

### ISSUE THREAD

**Issue by peterzhang2029** [PaddlePaddle/Paddle#4303]
例如，一个样本数据可能是[ [4, 5, 2], [0, 1, 9], [8, 1, 4]]这种格式

**Comment by luotao1** [comment]
目前没有处理双层序列的例子，处理单层序列的例子请看https://github.com/PaddlePaddle/Paddle/tree/develop/paddle/capi/examples/model_inference/sequence

**Comment by peterzhang2029** [comment]
好的，单层序列例子已经了解了，那请问如果要处理这种类似的双层序列数据预测的话，需要参考capi源码中的哪些资料呢？
