### ISSUE TITLE
jetson nano GPU版本的C++推理文本识别模型结果不正常，这个问题前面有人遇到过，但未解决，paddleocr发帖也无人回复

### ISSUE THREAD

**Issue by blackhitomi** [PaddlePaddle/Paddle#43031]
### bug描述 Describe the Bug

本文将paddle库C++编译后部署到jetson上进行paddleocr识别推理。编译配置版本信息如下：
GIT COMMIT ID: 2a7c2cf8f32541f3c7691b852bd4a8fe48505294
WITH_MKL: OFF
WITH_MKLDNN: OFF
WITH_GPU: ON
CUDA version: 10.2
CUDNN version: v8.0
CXX compiler version: 7.5.0

系统：jetsonnano linux ARM c++编译

版本：paddle 2.0  、paddle ocr 2.0 

==========================================================
问题描述：
文本识别图片如下图所示：
![3d93676880a6d38dc898b8e2a8cf2c4](https://user-images.githubusercontent.com/20531040/170504706-0f217073-6aa0-44df-9a69-b35d66c9e7f1.jpg)
识别模型：ch_PP-OCRv2_rec_infer / ch_ppocr_mobile_v2.0_rec_infer
识别结果：
CPU结果：（ch_PP-OCRv2_rec_infer）
![image](https://user-images.githubusercontent.com/20531040/170505005-bd190eec-8fe6-4eab-8fbd-e09da961f155.png)
jetsonnano的GPU结果：（ch_PP-OCRv2_rec_infer）
![image](https://user-images.githubusercontent.com/20531040/170505113-c8273d62-3de3-4e87-828b-db74b7100950.png)

代码相同：两个推理代码完全相同，采用官方提供的cpp infer代码，直接对上述图片做推理。

结果不同：两个结果相差深远，以至于采用ch_ppocr_mobile_v2.0_rec_infer模型jetson的GPU版本完全无法获得正确结果。如下图所示：
![image](https://user-images.githubusercontent.com/20531040/170508312-8ecc0cde-ff4d-4212-a5d5-d6011393cdad.png)

编译库不同：两者一个是CPU编译的paddle库，一个是jetson编译的paddle库。本人水平有限，但通过对照试验基本确定问题就出在jetson的paddle库上。（linux下x86架构显卡GPU上运行同样正常）

望重视：jetson性能有限，大模型运行速度过慢，mobile/lite模型无法在GPU上获得正确结果，十分影响现场部署效果。还望官方相关人员能够重视广大开发人员的辛苦试错，拜托了！！！本人总体上还是觉得paddle优点很多，如技术支持能跟上还会一直用下去。

=====================================================
类似问题：https://github.com/PaddlePaddle/Paddle/issues/30064
但上面问题的跟帖也无后续反馈。难道2.0版本不做维护了吗？？

**Comment by esythan** [comment]
之前RD发现jetson设备上 block/thread数默认设置会导致在jetson上有随机的问题，已经修过了
建议升级到最新版本尝试一下

**Comment by blackhitomi** [comment]
> 之前RD发现jetson设备上 block/thread数默认设置会导致在jetson上有随机的问题，已经修过了 建议升级到最新版本尝试一下

多谢回复！也就是说2.0版本的这个问题还存在，最新版的已经修复了是嘛。
但是由于最新版的需要升级cmake，和现场的部署环境不一致，不知道可否告知具体问题在哪里我手动修复下2.0版本。

**Comment by esythan** [comment]
修复PR参考https://github.com/PaddlePaddle/Paddle/pull/34751/files

**Comment by blackhitomi** [comment]
> 修复PR参考https://github.com/PaddlePaddle/Paddle/pull/34751/files

十分感谢！ 我尝试一下
