### ISSUE TITLE
安装Paddle环境出现问题

### ISSUE THREAD

**Issue by QiDa-007** [PaddlePaddle/Paddle#43043]
### 问题描述 Issue Description

按照官方教程，安装Paddle环境出现问题，Python3.7,3.8,3.10都是报一样的错误

### 版本&环境信息 Version & Environment Information

系统环境：
![image](https://user-images.githubusercontent.com/11505520/170623632-9d7b103d-98a1-4c52-97b3-4c452ed2ab39.png)
安装命令：
python -m pip install paddlepaddle==2.3.0 -i [https://mirror.baidu.com/pypi/simple](https://gitee.com/link?target=https%3A%2F%2Fmirror.baidu.com%2Fpypi%2Fsimple)
测试结果：
![image](https://user-images.githubusercontent.com/11505520/170623720-febd4b8f-2bdc-4e18-a2a0-d7d788af0843.png)

**Comment by yt605155624** [comment]
参考 https://github.com/PaddlePaddle/PaddleSpeech/issues/1970

**Comment by Ligoml** [comment]
这个问题已在develop分支上修复，会随2.3.1版本发布，PR https://github.com/PaddlePaddle/Paddle/pull/43009
详细信息可见https://github.com/PaddlePaddle/Paddle/issues/43052
