### ISSUE TITLE
PaddlePaddle's official website defaults on language issues

### ISSUE THREAD

**Issue by shangguanyifeng** [PaddlePaddle/Paddle#4304]
Can PaddlePaddle differentiate users directly from IP addresses, from abroad or from China?. Then, according to the location of the user, it is decided that the English website or Chinese Web site will be displayed by default.

**Comment by luotao1** [comment]
Can you move this PR to https://github.com/PaddlePaddle/PaddlePaddle.org ?

**Comment by shangguanyifeng** [comment]
ok

**Comment by luotao1** [comment]
Thx, I close this issue.
