### ISSUE TITLE
按照paddle文档教程编写自定义算子时，报如下所示的错误，链接库无法找到。

### ISSUE THREAD

**Issue by runxi607** [PaddlePaddle/Paddle#43041]
RuntimeError: (PreconditionNotMet) The third-party dynamic library (/public/home/miaozhao/kazheng_fourpoint/card_crop_paddle_orgpaddle_fuzhi/ppdet/relu/build/custom_setup_ops/lib.linux-x86_64-3.8/custom_setup_ops.so) that Paddle depends on is not configured correctly. (error code is /public/home/miaozhao/kazheng_fourpoint/card_crop_paddle_orgpaddle_fuzhi/ppdet/relu/build/custom_setup_ops/lib.linux-x86_64-3.8/custom_setup_ops.so: undefined symbol: _ZN6paddle17OpMetaInfoBuilderC1EOSsm)
Suggestions:
1. Check if the third-party dynamic library (e.g. CUDA, CUDNN) is installed correctly and its version is matched with paddlepaddle you installed.
2. Configure third-party dynamic library environment variables as follows:
- Linux: set LD_LIBRARY_PATH by `export LD_LIBRARY_PATH=...`
- Windows: set PATH by `set PATH=XXX; (at /paddle/paddle/fluid/platform/dynload/dynamic_loader.cc:285)
linux-vdso.so.1 => (0x00007fff51f06000)
libpaddle_pybind.so => not found
libcudart.so.11.0 => /usr/local/cuda-11.0/lib64/libcudart.so.11.0 (0x00002b8e26139000)
libstdc++.so.6 => /public/home/miaozhao/anaconda3-torch1.0/envs/ICD/lib/libstdc++.so.6 (0x00002b8e25f7f000)
libm.so.6 => /lib64/libm.so.6 (0x00002b8e263b7000)
libgcc_s.so.1 => /public/home/miaozhao/anaconda3-torch1.0/envs/ICD/lib/libgcc_s.so.1 (0x00002b8e260f4000)
libpthread.so.0 => /lib64/libpthread.so.0 (0x00002b8e266b9000)
libc.so.6 => /lib64/libc.so.6 (0x00002b8e268d5000)
/lib64/ld-linux-x86-64.so.2 (0x00002b8e25f15000)
libdl.so.2 => /lib64/libdl.so.2 (0x00002b8e26ca3000)
librt.so.1 => /lib64/librt.so.1 (0x00002b8e26ea7000)

RuntimeError: (PreconditionNotMet) The third-party dynamic library (/public/home/miaozhao/kazheng_fourpoint/card_crop_paddle_orgpaddle_fuzhi/ppdet/relu/build/custom_setup_ops/lib.linux-x86_64-3.8/custom_setup_ops.so) that Paddle depends on is not configured correctly. (error code is /public/home/miaozhao/kazheng_fourpoint/card_crop_paddle_orgpaddle_fuzhi/ppdet/relu/build/custom_setup_ops/lib.linux-x86_64-3.8/custom_setup_ops.so: undefined symbol: _ZN6paddle17OpM

**Comment by zhaocaibei123** [comment]
这个问题看起来是cuda版本不匹配，请先根据suggestion确认下环境

**Comment by chenwhql** [comment]
这个是由于ABI兼容性导致的问题，之前做过一次修复，几个信息麻烦您提供一下：
1. 您使用的是什么环境？centos还是ubuntu？具体是哪个版本？gcc是什么版本？
2. 您使用的哪个版本的paddle？
3. 能否可以在extra_cxx_cflags中加个参数试试？-D_GLIBCXX_USE_CXX11_ABI=1

**Comment by runxi607** [comment]
> 这个是由于ABI兼容性导致的问题，之前做过一次修复，几个信息麻烦您提供一下：
> 
> 1. 您使用的是什么环境？centos还是ubuntu？具体是哪个版本？gcc是什么版本？
> 2. 您使用的哪个版本的paddle？
> 3. 能否可以在extra_cxx_cflags中加个参数试试？-D_GLIBCXX_USE_CXX11_ABI=1

您好，谢谢您的回复。我们换了别的方法做，可以行得通。如果有问题再来请教您，非常感谢！

**Comment by chenwhql** [comment]
> > 这个是由于ABI兼容性导致的问题，之前做过一次修复，几个信息麻烦您提供一下：
> > 
> > 1. 您使用的是什么环境？centos还是ubuntu？具体是哪个版本？gcc是什么版本？
> > 2. 您使用的哪个版本的paddle？
> > 3. 能否可以在extra_cxx_cflags中加个参数试试？-D_GLIBCXX_USE_CXX11_ABI=1
> 
> 您好，谢谢您的回复。我们换了别的方法做，可以行得通。如果有问题再来请教您，非常感谢！

好的，感谢支持
