### ISSUE TITLE
关于安装paddle 发行版本遇到protobuf 的报错问题

### ISSUE THREAD

**Issue by dingjiaweiww** [PaddlePaddle/Paddle#43052]
### 问题描述 Please describe your issue

问题原因：
protobuf 于 2022.05.26 发布了 4.21 版本，如果您环境中没有 protobuf 的话，默认安装 paddle 时会自动下载最高版本的protobuf 4.21，paddle能安装成功但是 import paddle 会报错，这是由于protobuf 4.21 为不兼容升级，目前 develop 版本的 paddle 已经修复了这个问题（ see https://github.com/PaddlePaddle/Paddle/pull/43009 ），但是发行版由于已经编包发布所以仍存在这个问题，飞桨会在下个版本2.3.1中解决。
参考:
- [https://developers.google.com/protocol-buffers/docs/news/2022-05-06#python-updates](https://developers.google.com/protocol-buffers/docs/news/2022-05-06#python-updates)
- [Streamlit run with protocbuf error](https://discuss.streamlit.io/t/streamlit-run-with-protocbuf-error/25632)
- [TypeError: Descriptors cannot not be created directly](https://discuss.streamlit.io/t/typeerror-descriptors-cannot-not-be-created-directly/25639)

解决办法：

手动降低 protobuf 为 3.x
pip install protobuf==3.20.1

完整报错:
![image](https://user-images.githubusercontent.com/23093488/170646504-445ec0a8-42ea-48ab-bbce-ba2aa4db9247.png)

(py39) C:\Users\Admin>hub install ge2e_fastspeech2_pwgan==1.0.0
Traceback (most recent call last):
  File "f:\anaconda3\envs\py39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "f:\anaconda3\envs\py39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "f:\anaconda3\envs\py39\Scripts\hub.exe\__main__.py", line 4, in <module>
  File "f:\anaconda3\envs\py39\lib\site-packages\paddlehub\__init__.py", line 18, in <module>
    import paddle
  File "f:\anaconda3\envs\py39\lib\site-packages\paddle\__init__.py", line 25, in <module>
    from .framework import monkey_patch_variable
  File "f:\anaconda3\envs\py39\lib\site-packages\paddle\framework\__init__.py", line 17, in <module>
    from . import random  # noqa: F401
  File "f:\anaconda3\envs\py39\lib\site-packages\paddle\framework\random.py", line 16, in <module>
    import paddle.fluid as fluid
  File "f:\anaconda3\envs\py39\lib\site-packages\paddle\fluid\__init__.py", line 36, in <module>
    from . import framework
  File "f:\anaconda3\envs\py39\lib\site-packages\paddle\fluid\framework.py", line 35, in <module>
    from .proto import framework_pb2
  File "f:\anaconda3\envs\py39\lib\site-packages\paddle\fluid\proto\framework_pb2.py", line 33, in <module>
    _descriptor.EnumValueDescriptor(
  File "f:\anaconda3\envs\py39\lib\site-packages\google\protobuf\descriptor.py", line 755, in __new__
    _message.Message._CheckCalledFromGeneratedFile()
TypeError: Descriptors cannot not be created directly.
If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
If you cannot immediately regenerate your protos, some other possible workarounds are:
 1. Downgrade the protobuf package to 3.20.x or lower.
 4. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).

More information: https://developers.google.com/protocol-buffers/docs/news/2022-05-06#python-updates

**Comment by zhaocaibei123** [comment]
可以参考：https://github.com/PaddlePaddle/PaddleSpeech/issues/1970
或者按照提示升级下protobuf包，或者export下这个环境变量
![image](https://user-images.githubusercontent.com/48509226/170661702-2ab74cac-ac65-41c3-855c-603610c574d9.png)

**Comment by dingjiaweiww** [comment]
protobuf 已经撤销了4.21 版本在pypi源上的发布（ https://pypi.org/project/protobuf/4.21.0/ ） ，如果你使用pip install paddlepaddle 默认从pypi源下载依赖的话不会再遇到import paddle 报错，但是你从国内源下载（清华源、百度源等），则依然会下载protobuf 4.x，需要手动降低版本再使用paddle

**Comment by shixnjs** [comment]
我也遇到了这一问题，但是当我手动降低版本后会出现
requests.exceptions.SSLError: HTTPSConnectionPool(host='paddleocr.bj.bcebos.com', port=443): Max retries exceeded with url: /PP-OCRv3/chinese/ch_PP-OCRv3_det_infer.tar (Caused by SSLError("Can't connect to HTTPS URL because the SSL module is not available."))

**Comment by SigureMo** [comment]
> 如果你使用pip install paddlepaddle 默认从pypi源下载依赖的话不会再遇到import paddle 报错

yank 的第二天就发布了 4.21.1，所以还会有这个问题

另外，降级是有效的（如 3.20.1），不会出现其他问题

**Comment by SigureMo** [comment]
> 我也遇到了这一问题，但是当我手动降低版本后会出现
> requests.exceptions.SSLError: HTTPSConnectionPool(host='paddleocr.bj.bcebos.com', port=443): Max retries exceeded with url: /PP-OCRv3/chinese/ch_PP-OCRv3_det_infer.tar (Caused by SSLError("Can't connect to HTTPS URL because the SSL module is not available."))

这问题与此无关吧，建议另开 issue 详述问题

**Comment by 2954456878** [comment]
pip install protobuf==3.20.1 -i https://pypi.tuna.tsinghua.edu.cn/simple
