### ISSUE TITLE
no-avx core

### ISSUE THREAD

**Issue by WhiteSymmetry** [PaddlePaddle/Paddle#43067]
### 问题描述 Issue Description

Error: Your machine doesn't support AVX, but the installed PaddlePaddle is avx core, you should reinstall paddlepaddle with no-avx core.
https://www.paddlepaddle.org.cn/whl/windows/cpu-mkl-noavx/develop.html
It does not have python 3.10.

### 版本&环境信息 Version & Environment Information

Paddle version: None
Paddle With CUDA: None

OS: Windows 10
Python version: 3.10.4

CUDA version: 11.5.50

Build cuda_11.5.r11.5/compiler.30411180_0
cuDNN version: None
Nvidia driver version: None

**Comment by pangyoki** [comment]
Hi, the noavx machine does not support python3.10 in temporary, please reduce the python version.
