### ISSUE TITLE
Paddle inference demo的名为resnet50的demo 编译/执行 出错

### ISSUE THREAD

**Issue by spencergotowork** [PaddlePaddle/Paddle#43066]
### Paddle inference demo的名为resnet50的demo 编译/执行 出错

**设备类型为**： AMD Ryzen 7 5800H
**compile.sh设置**为
![image](https://user-images.githubusercontent.com/42672437/170830793-048d4fdb-b0ee-48e6-a459-7bb8e22b0de0.png)

推理预测库为 *_avx_openblas_gcc8.2.tgz 时
![image](https://user-images.githubusercontent.com/42672437/170830734-5be13bff-8dff-4363-85c6-2797b9a5bad3.png)
但是CMakeList文件中已经设置了正确的路径

推理预测库为 *_noavx_openblas_gcc8.2.tgz时
![image](https://user-images.githubusercontent.com/42672437/170830633-256b9690-3ea6-4405-8e16-ba3fb98f389a.png)

dmesg查看后的信息为
![image](https://user-images.githubusercontent.com/42672437/170830674-72190c9a-f7e2-43df-a814-408ceec397eb.png)

**Comment by jiweibo** [comment]
您好，问题应该是CMakeLists.txt中没有引入ONNXRuntime的头文件和库文件，请确认您目前使用的是最新版本的demo，可比较下CMakeLists.txt是否一致
https://github.com/PaddlePaddle/Paddle-Inference-Demo/blob/master/c%2B%2B/lib/CMakeLists.txt#L51


如果版本一致的话， 可能onnxruntime和noavx有冲突，需要修复， 请 @heliqi 确认

**Comment by heliqi** [comment]
@spencergotowork  看第一张图的报错是没有链接onnxruntime， 可以参考这个[demo](https://github.com/PaddlePaddle/Paddle-Inference-Demo/tree/master/c%2B%2B/paddle-onnxruntime) 在compile.sh里增加 WITH_ONNXRUNTIME=ON 和  -DWITH_ONNXRUNTIME=${WITH_ONNXRUNTIME}

**Comment by spencergotowork** [comment]
> @spencergotowork 看第一张图的报错是没有链接onnxruntime， 可以参考这个[demo](https://github.com/PaddlePaddle/Paddle-Inference-Demo/tree/master/c%2B%2B/paddle-onnxruntime) 在compile.sh里增加 WITH_ONNXRUNTIME=ON 和 -DWITH_ONNXRUNTIME=${WITH_ONNXRUNTIME}

我的demo是最新的，按照您的说法，依旧是有这个问题，即使是我运行了 paddle-onnxruntime 这个demo，仍然会报没有链接
![image](https://user-images.githubusercontent.com/42672437/170912000-4712c6d4-0ca6-4394-a5e9-8a078cddff7f.png)
我对此不是很了解，因为即使是我手动在compile里加上export这个so文件的路径到LIB path，也会出现没有其他so文件的报错。

**Comment by heliqi** [comment]
你下载的是2.3版本预测库？ 如果是2.3以下版本是不带onnxruntime的预测库，需要把WITH_ONNXRUNTIME=OFF

你截图下预测库 third_party/install 目录下的文件，里边带onnxruntime才需要开启WITH_ONNXRUNTIME。 还有openblas的预测库需要把 WITH_MKLDNN设置成OFF。
如果是2.3带onnxruntime的库，链接onnxruntime还有问题，可能是openblas问题，我这边复现修复下这个问题

**Comment by spencergotowork** [comment]
> 

并不是这样，我上面的截图和说明提到过已经添加了路径，并且路径是有这个so文件存在的。 我后面的解决办法是换了低版本的gcc并且使用你们gcc5的那个预测库，可以使用，还没有看两个库版本的具体区别是什么
