### ISSUE TITLE
BML_CodeLab使用logging.info不会打印信息

### ISSUE THREAD

**Issue by xiaotingyun** [PaddlePaddle/Paddle#43065]
### bug描述 Describe the Bug

import logging
logging.info(111)

**Comment by wangna11BD** [comment]
加一行
logging.basicConfig(level=logging.INFO)

**Comment by xiaotingyun** [comment]
![image](https://user-images.githubusercontent.com/51204375/170832524-f6c5e9e8-0370-4c83-b55d-c3f35f953bb7.png)
加一行也打印不出

**Comment by wangna11BD** [comment]
import logging
logging.basicConfig(level=logging.INFO)
logging.info(111)
