### ISSUE TITLE
mean函数有问题

### ISSUE THREAD

**Issue by xiaotingyun** [PaddlePaddle/Paddle#43064]
### bug描述 Describe the Bug

mean函数有问题
temp = paddle.to_tensor([1,2])
temp.mean()

### 其他补充信息 Additional Supplementary Information

![image](https://user-images.githubusercontent.com/51204375/170826795-e9193bae-ab2c-43fb-9456-d71fcf238eee.png)

**Comment by wangna11BD** [comment]
已经反馈给了相关API负责同学。请等待进一步确认及回复～
也可以先用 temp = paddle.to_tensor([1.,2.]) 绕过去～

**Comment by shangzhizhou** [comment]
您好，Tensor.mean（paddle.mean）API只支持float32和float64的输入类型。具体请见paddle.mean的API 文档说明
https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/mean_cn.html#cn-api-tensor-cn-mean

**Comment by Ligoml** [comment]
你好，mean算子需要输入是float类型，所以这应该是用法错误，而非bug，你可以参考 @wangna11BD 的建议，修改为：
`temp = paddle.to_tensor([1.,2.])`
