### ISSUE TITLE
paddle.vision.ops.nms()函数返回值描述错误

### ISSUE THREAD

**Issue by diaoa1900** [PaddlePaddle/Paddle#43069]
### 文档链接&描述 Document Links & Description

文档链接：
[paddle.vision.ops.nms()](https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/vision/ops/nms_cn.html#nms)
存在问题：
函数的返回值描述是 **Tensor - 被NMS保留的检测边界框的索引，它应当是一个形状为[num_boxes]的1-D Tensor。**
但其实际的返回值是 **Tensor - 被NMS保留的检测边界框（按score降序排序后）的索引**
代码验证：
paddle版本：2.3.0
![验证](https://user-images.githubusercontent.com/65444591/170851950-ed3be4cb-9763-4e78-80f3-949d3af8d1bd.png)

### 请提出你的建议 Please give your suggestion

将函数实现为**返回经NMS保留的原boxes的索引**，同时**将结果进行去重**

**Comment by RichardWooSJTU** [comment]
首先十分感谢你对paddle的支持，同时也对我们的疏忽给你造成的不便表示十分抱歉。经排查，paddle.vision.ops.nms()在加入scores参数之后的返回值的确不符合预期。这里的预期逻辑是：
1. boxes按照scores排序
2. 使用nms处理排序后的boxes
3. 返回经nms保留的排序之前的boxes索引
但是返回的时候缺少了第三步。目前可以在你自己的代码中加入第3步，例如
sorted_scores_index = scores.argsort(descending=True)
wrong_index = paddle.vision.ops.nms(boxes, 0.4, scores)
origin_index = sorted_scores_index[wrong_index]

该问题我们会尽快修复并提交PR，未去重的问题也会一并解决并在下个版本可见。如果有紧急需求也可以在PR合入后使用develop分支自行编译。

另外，去重可以直接使用paddle API paddle.unique()
