### ISSUE TITLE
paddle2.3 cumsum api 在用gpu计算时会出现随机错误结果

### ISSUE THREAD

**Issue by bitcjm** [PaddlePaddle/Paddle#43068]
### bug描述 Describe the Bug

问题描述：paddle2.3 cumsum api 在用gpu计算时会出现随机错误结果

最小可复现代码可参考以下[aistudio项目链接](https://aistudio.baidu.com/aistudio/projectdetail/4133589?contributionType=1)
顺序运行项目代码即可看到错误。paddle2.2.2版本似乎不会出现该错误。

**Comment by shjNT** [comment]
您好，我这里没有项目链接权限，还麻烦给一下复现代码

**Comment by bitcjm** [comment]
已修改权限，可以查看了 @shjNT

**Comment by wawltor** [comment]
嗯嗯 这个是一个Op bug，目前正在修复

**Comment by wawltor** [comment]
您好，该问题已经通过该PR修复https://github.com/PaddlePaddle/Paddle/pull/43101 ，谢谢帮我们提出该问题！
