### ISSUE TITLE
【新需求】将data_ptr()暴露给python

### ISSUE THREAD

**Issue by hiyyg** [PaddlePaddle/Paddle#43074]
### 需求描述 Feature Description

任务目标（请描述你正在做的项目是什么，如模型、论文、项目是什么？）; <br /> 需求场景（请描述你的项目中为什么需要用此功能）;  <br /> 功能描述（请简单描述或设计这个功能）

pytorch中通过python端获取的data_ptr()可以直接对cuda的内容进行操作，这可以用于与其他cuda程序交互，例如https://github.com/NVlabs/DeepIM-PyTorch/blob/master/ycb_render/ycb_renderer.py#L506

然而paddle不支持这个，很多功能无法实现。

### 替代实现 Alternatives

无

**Comment by hiyyg** [comment]
```
In [7]: a=torch.tensor([1.])

In [8]: b=paddle.to_tensor([2.])

In [9]: a.data_ptr()
Out[9]: 140551224734848

In [10]: b.data_ptr()
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-10-cb364ee64c04> in <module>
----> 1 b.data_ptr()

AttributeError: 'Tensor' object has no attribute 'data_ptr'
```

**Comment by Ligoml** [comment]
需求已收到，这个问题飞桨内部之前讨论过，结论是：直接操作内存是一个危险行为，不太建议新增为api暴露出来。且这个api通常不会影响框架的正常使用。如果你有一些特殊的用法和场景，我们可以在issue中沟通。
此外，如果你短期内需要使用该能力，可以参考这个pr https://github.com/taichi-dev/taichi/pull/4886   用 `paddle_tensor.value().get_tensor()._ptr()`

**Comment by hiyyg** [comment]
> 需求已收到，这个问题飞桨内部之前讨论过，结论是：直接操作内存是一个危险行为，不太建议新增为api暴露出来。且这个api通常不会影响框架的正常使用。如果你有一些特殊的用法和场景，我们可以在issue中沟通。 此外，如果你短期内需要使用该能力，可以参考这个pr [taichi-dev/taichi#4886](https://github.com/taichi-dev/taichi/pull/4886) 用 `paddle_tensor.value().get_tensor()._ptr()`

pytorch支持，paddle不支持，导致很多工作无法用paddle复现。。。

**Comment by Ligoml** [comment]
比如呢？

**Comment by hiyyg** [comment]
请看本issue最开头。

> 比如呢？



另外，这不是危险的行为，既然pytorch支持了，并且有场景有这种强需求，这肯定是合理的，危不危险应该给开发者自己判断，而不是框架开发者拍脑袋就认为不应该提供这个功能。
> 需求已收到，这个问题飞桨内部之前讨论过，结论是：直接操作内存是一个危险行为，不太建议新增为api暴露出来。且这个api通常不会影响框架的正常使用。如果你有一些特殊的用法和场景，我们可以在issue中沟通。 此外，如果你短期内需要使用该能力，可以参考这个pr [taichi-dev/taichi#4886](https://github.com/taichi-dev/taichi/pull/4886) 用 `paddle_tensor.value().get_tensor()._ptr()`

**Comment by hiyyg** [comment]
请看本issue最开头。

> 比如呢？



另外，这不是危险的行为，既然pytorch支持了，并且有场景有这种强需求，这肯定是合理的，危不危险应该给开发者自己判断，而不是框架开发者拍脑袋就认为不应该提供这个功能。
> 需求已收到，这个问题飞桨内部之前讨论过，结论是：直接操作内存是一个危险行为，不太建议新增为api暴露出来。且这个api通常不会影响框架的正常使用。如果你有一些特殊的用法和场景，我们可以在issue中沟通。 此外，如果你短期内需要使用该能力，可以参考这个pr [taichi-dev/taichi#4886](https://github.com/taichi-dev/taichi/pull/4886) 用 `paddle_tensor.value().get_tensor()._ptr()`

**Comment by dingjiaweiww** [comment]
@hiyyg 你好，你提出的问题对于paddle 来说是一个new feature，你愿意为paddle 贡献这个新功能吗？如果你需要协助，我们会随时支持你

**Comment by phlrain** [comment]
我们内部讨论下，后续会评估下增加这种基础的接口给大家使用

**Comment by hiyyg** [comment]
...
