### ISSUE TITLE
PaddleDetection已经导出的模型，如何测试模型mAP？

### ISSUE THREAD

**Issue by Disciple7** [PaddlePaddle/Paddle#43075]
### 请提出你的问题 Please ask your question

我正在使用PaddleDetection框架进行模型量化、剪枝等slim工作。目前导出了一些模型，包括使用tools/export_model.py导出的无slim模型、用tools/post_quant.py导出的PTQ量化模型，其他人提供的剪枝模型，以及在剪枝模型上用tools/post_quant.py导出的剪枝+PTQ量化模型。这些模型均为infer_cfg.yml、model.pdmodel、model.pdiparams、model.pdiparams.info格式。
现在我需要对这些模型进行推理结果mAP的测试，但是tools/eval.py不支持读取.pdiparams的文件，benchmark.sh也不能测试推理结果mAP。请问官方是否有提供其他测试套件？还是得自己手写流程？

**Comment by zhiboniu** [comment]
你好，PaddleDetection模型导出后没有提供相关eval评估脚本，建议在导出前进行eval评估。
如果确实需要对导出后的模型进行评估，需要自己写一下评估代码了。
另外tools/post_quant.py导出会导致精度下降比较多，建议采用量化训练的方式，可以参考：https://github.com/PaddlePaddle/PaddleDetection/tree/release/2.4/configs/slim
