### ISSUE TITLE
开启tensorrt推理反复创建销毁会显存泄漏

### ISSUE THREAD

**Issue by marsbzp** [PaddlePaddle/Paddle#43086]
### 请提出你的问题 Please ask your question

paddleocr 创建推理模型 推理一张图片 释放模型 创建推理模型 推理一张图片 释放模型 。。。。。。
会显存泄漏
![image](https://user-images.githubusercontent.com/20138766/170924857-a9df0ed0-e944-4a88-b2cf-dc2b1308d96c.png)

**Comment by LDOUBLEV** [comment]
创建推理模型后释放模型是怎么做的，如果程序没有退出，创建的推理模型依然占据着显存

**Comment by marsbzp** [comment]
> 创建推理模型后释放模型是怎么做的，如果程序没有退出，创建的推理模型依然占据着显存

不开启tensorrt完全没问题的，开启推理几次会OOM

**Comment by LDOUBLEV** [comment]
根据释放模型后显存是否释放来判断是否释放成功

**Comment by marsbzp** [comment]
> 根据释放模型后显存是否释放来判断是否释放成功
paddleocr cpp_infer demo改下就可以测试，或者你用其他检测模型也可以测，函数里面创建模型推理

![image](https://user-images.githubusercontent.com/20138766/171071685-c3ab27fe-c1be-4adb-84ed-e4c82d7f762c.png)

**Comment by LDOUBLEV** [comment]
main_det里会先创建predictor再运行，创建predictor后可以一直使用，不需要重复创建，如果需要测试一个文件夹下的图像，image_dir赋值为文件夹路径就行；
而且看你的截图里，也没释放predictor啊，显存肯定会一直增加

**Comment by mingren8888** [comment]
怎么手动释放predictor呢？析构函数调用了也没有见显存释放，只有关闭程序后才释放了
