### ISSUE TITLE
老版本的wheel下载

### ISSUE THREAD

**Issue by Yelrose** [PaddlePaddle/Paddle#43106]
### 问题描述 Issue Description

想下载过往版本的paddlepaddle-gpu=2.2.2.post112版本想问一下怎么下载，按照官网看https://paddlepaddle.org.cn/whl/mkl/stable.html 这个地址里面查看，最新的wheel好像只有2.2.0rc版。

### 版本&环境信息 Version & Environment Information

Empty

**Comment by dingjiaweiww** [comment]
https://www.paddlepaddle.org.cn/whl/linux/mkl/avx/stable.html 在这个链接里
![image](https://user-images.githubusercontent.com/23093488/171075641-bdaa8007-0099-4d04-8b48-96c615450f04.png)
