### ISSUE TITLE
paddle2.0,策略梯度网络参数不更新

### ISSUE THREAD

**Issue by HarryUP-rhy** [PaddlePaddle/Paddle#43121]
### bug描述 Describe the Bug

[<script src="https://gist.github.com/RenHyz/c98ab29f3bb783fe0fdf1d718318c6b6.js"></script>](https://gist.github.com/RenHyz/c98ab29f3bb783fe0fdf1d718318c6b6)
代码如上。
输出信息如下：(act_prob是输出的预测概率，每轮结束预测概率都相同，说明网络参数没有更新)

E:\RhyAnaconda\envs\paddle2.2\python.exe E:/LearnPad/learn_pad_pycharm/Trading_2/trading_1.py
price (6732, 10, 7)
E:\RhyAnaconda\envs\paddle2.2\lib\site-packages\paddle\fluid\layers\math_op_patch.py:341: UserWarning: E:/LearnPad/learn_pad_pycharm/Trading_2/trading_1.py:87
The behavior of expression A * B has been unified with elementwise_mul(X, Y, axis=-1) from Paddle 2.0. If your code works well in the older versions but crashes in this version, try to use elementwise_mul(X, Y, axis=0) instead of A * B. This transitional warning will be dropped in the future.
  op_type, op_type, EXPRESSION_MAP[method_name]))
len(act_list) 6732
len(obs_list) 6732
batch_obs (6732, 1, 10, 7)
batch_action (6732,)
batch_gt (6732,)
cost [56.294224]
act_prob [array([[0.5102877 , 0.48971227]], dtype=float32), array([[0.50991267, 0.49008733]], dtype=float32), array([[0.5093808 , 0.49061918]], dtype=float32), array([[0.50884414, 0.49115583]], dtype=float32), array([[0.50842255, 0.4915774 ]], dtype=float32)]
len(act_list) 6732
len(obs_list) 6732
batch_obs (6732, 1, 10, 7)
batch_action (6732,)
batch_gt (6732,)
cost [230.39868]
act_prob [array([[0.5102877 , 0.48971227]], dtype=float32), array([[0.50991267, 0.49008733]], dtype=float32), array([[0.5093808 , 0.49061918]], dtype=float32), array([[0.50884414, 0.49115583]], dtype=float32), array([[0.50842255, 0.4915774 ]], dtype=float32)]
len(act_list) 6732
len(obs_list) 6732
batch_obs (6732, 1, 10, 7)
batch_action (6732,)
batch_gt (6732,)
cost [-284.36664]
act_prob [array([[0.5102877 , 0.48971227]], dtype=float32), array([[0.50991267, 0.49008733]], dtype=float32), array([[0.5093808 , 0.49061918]], dtype=float32), array([[0.50884414, 0.49115583]], dtype=float32), array([[0.50842255, 0.4915774 ]], dtype=float32)]
len(act_list) 6732
len(obs_list) 6732
batch_obs (6732, 1, 10, 7)
batch_action (6732,)
batch_gt (6732,)
cost [-94.096016]
act_prob [array([[0.5102877 , 0.48971227]], dtype=float32), array([[0.50991267, 0.49008733]], dtype=float32), array([[0.5093808 , 0.49061918]], dtype=float32), array([[0.50884414, 0.49115583]], dtype=float32), array([[0.50842255, 0.4915774 ]], dtype=float32)]

**Comment by LemonNoel** [comment]
您好，请提供更具体的paddle版本信息和相关的依赖，以及尽可能小的可复现代码，以便更快地定位问题。我们复现后会尽快回复您～

**Comment by HarryUP-rhy** [comment]
> 您好，请提供更具体的paddle版本信息和相关的依赖，以及尽可能小的可复现代码，以便更快地定位问题。我们复现后会尽快回复您～


paddlepaddle版本2.2.2，代码在问题中的链接里
<html>
<body>


absl-py | 1.0.0 | 0.15.0
-- | -- | --
astor | 0.8.1 | 0.8.1
blas | 1.0 | 1.0
brotlipy | 0.7.0 | 0.7.0
ca-certificates | 2022.3.29 | 2022.4.26
certifi | 2021.10.8 | 2022.5.18.1
cffi | 1.15.0 | 1.15.0
charset-normalizer | 2.0.4 | 2.0.4
click | 8.1.2 | 8.0.4
cloudpickle | 1.2.1 | 2.0.0
colorama | 0.4.4 | 0.4.4
cryptography | 36.0.0 | 37.0.1
cycler | 0.11.0 | 0.11.0
decorator | 5.1.1 | 5.1.1
docker-pycreds | 0.4.0 | 0.4.0
flask | 1.0.4 | 2.0.3
flask-cors | 3.0.10 | 3.0.10
fonttools | 4.32.0 | 4.25.0
freetype | 2.10.4 | 2.10.4
gast | 0.3.3 | 0.5.3
gitdb | 4.0.9 | 4.0.7
gitpython | 3.1.27 | 3.1.18
grpcio | 1.44.0 | 1.42.0
gym | 0.23.1 |  
gym-anytrading | 1.2.0 |  
gym-notices | 0.0.6 |  
idna | 3.3 | 3.3
importlib-metadata | 4.11.3 | 4.11.3
intel-openmp | 2021.4.0 | 2022.0.0
itsdangerous | 2.1.2 | 2.0.1
jinja2 | 3.1.1 | 3.0.3
jpeg | 9d | 9e
kiwisolver | 1.4.2 | 1.4.2
libpng | 1.6.37 | 1.6.37
libprotobuf | 3.19.1 | 3.20.1
libtiff | 4.2.0 | 4.2.0
libwebp | 1.2.2 | 1.2.2
lz4-c | 1.9.3 | 1.9.3
markdown | 3.3.6 | 3.3.4
markupsafe | 2.1.1 | 2.0.1
matplotlib | 3.5.1 | 3.5.1
mkl | 2021.4.0 | 2022.0.0
mkl-service | 2.4.0 | 2.4.0
mkl_fft | 1.3.1 | 1.3.1
mkl_random | 1.2.2 | 1.2.2
numpy | 1.21.5 | 1.22.3
numpy-base | 1.21.5 | 1.22.3
openssl | 1.1.1n | 1.1.1o
packaging | 21.3 | 21.3
paddlepaddle | 2.2.2 |  
pandas | 1.3.5 | 1.4.2
parl | 1.3 |  
pathtools | 0.1.2 | 0.1.2
pillow | 9.0.1 | 9.0.1
pip | 21.2.4 | 21.2.4
promise | 2.3 | 2.3
protobuf | 3.19.1 | 3.20.1
psutil | 5.9.0 | 5.8.0
pycparser | 2.21 | 2.21
pygame | 2.1.2 |  
pyopenssl | 22.0.0 | 22.0.0
pyparsing | 3.0.8 | 3.0.4
pysocks | 1.7.1 | 1.7.1
python | 3.7.13 | 3.10.4
python-dateutil | 2.8.2 | 2.8.2
pytz | 2022.1 | 2021.3
pyyaml | 6.0 | 6.0
pyzmq | 18.0.1 | 22.3.0
requests | 2.27.1 | 2.27.1
scipy | 1.7.3 | 1.7.3
sentry-sdk | 1.5.12 |  
setproctitle | 1.2.3 | 1.2.2
setuptools | 61.2.0 | 61.2.0
shortuuid | 1.0.9 |  
six | 1.16.0 | 1.16.0
smmap | 5.0.0 | 4.0.0
sqlite | 3.38.2 | 3.38.3
ta-lib | 0.4.24 |  
tb-nightly | 1.15.0a20190801 |  
tensorboardx | 1.8 | 2.2
termcolor | 1.1.0 | 1.1.0
tk | 8.6.11 | 8.6.11
typing-extensions | 4.1.1 | 4.1.1
urllib3 | 1.26.8 | 1.26.9
vc | 14.2 | 14.2
vs2015_runtime | 14.27.29016 | 14.27.29016
wandb | 0.12.16 |  
werkzeug | 2.1.1 | 2.0.3
wheel | 0.37.1 | 0.37.1
win_inet_pton | 1.1.0 | 1.1.0
wincertstore | 0.2 | 0.2
xz | 5.2.5 | 5.2.5
zipp | 3.8.0 | 3.8.0
zlib | 1.2.12 | 1.2.12
zstd | 1.4.9 | 1.5.2


</body>
</html>

**Comment by LemonNoel** [comment]
你好，根据提供的安装版本和代码，在执行`gym`的代码时会出现报错：```gym.error.VersionNotFound: Environment version `v2` for `stocks` could not be found. `stocks` provides the versioned environments: [ `v0` ].```。

麻烦再次确认下代码，以及通过梯度打印定位下梯度不回传的代码行数，方便快速查找问题。另外，当前2.x版本已经切换到动态图，推荐使用动态图的用法哈。

**Comment by HarryUP-rhy** [comment]
> 你好，根据提供的安装版本和代码，在执行`gym`的代码时会出现报错：`` gym.error.VersionNotFound: Environment version `v2` for `stocks` could not be found. `stocks` provides the versioned environments: [ `v0` ]. ``。
> 
> 麻烦再次确认下代码，以及通过梯度打印定位下梯度不回传的代码行数，方便快速查找问题。另外，当前2.x版本已经切换到动态图，推荐使用动态图的用法哈。

你好，gym版本的v2是我自己下载的数据，自带的是v0，不过问题应该不大。现在这个问题基本解决了。
