### ISSUE TITLE
Is swapping kernels from oneDNN to PHI in runtime possible?

### ISSUE THREAD

**Issue by piotrekobi** [PaddlePaddle/Paddle#43131]
The framework::OpKernelType GetExpectedKernelType function is executed only at the beginning of models and if the choice of kernel is dependent on runtime data, using it to change the kernel is not possible.

For example, the oneDNN kernel for the pool operator does not support adaptive pooling when additional padding needs to be added to the current input. This is checked in PoolOp::GetExpectedKernelType by an additional function: CanMKLDNNSupportPool, but it can only check the current input dimensions. If input dimensions in the next model images are not supported by the oneDNN implementation an error will be raised. The only way to prevent this error without changing the kernel in runtime is to disable the oneDNN kernel for adaptive pooling.

Forcing GetExpectedKernelType to be executed for each operation can be achieved by removing this if condition in operator.cc:1490
```CPP
if (kernel_type_.get() == nullptr || kernel_func_.get() == nullptr) {
      ChooseKernel(exe_ctx);
      dev_ctx = pool.Get(kernel_type_->place_);
    }
````
But this results in the following error, which is caused by PHI kernels being initialized differently than other kernels:
```
NotFoundError: Operator (pool2d) does not have kernel for {data_type[float]; data_layout[Undefined(AnyLayout)]; place[Place(cpu)]; library_type[PLAIN]}.
  [Hint: Expected kernel_iter != kernels.end(), but received kernel_iter == kernels.end().] (at /home/ppaturej/Paddle/paddle/fluid/framework/operator.cc:1792)
  [operator < pool2d > error]
```
Is there a way to change the kernel from oneDNN to PHI during runtime?

**Comment by jiangjiajun** [comment]
For the current framework, I think we cannot change the kernel type once we have made all the initialization.

**Comment by piotrekobi** [comment]
What would you propose to do if a oneDNN kernel supports over 90% of the functionality of a PHI kernel, but can't be used for some shapes when dynamic shapes are enabled? Currently we have to disable the use of the kernel, even though it doesn't work only for a few cases that can easily be checked in runtime.

**Comment by chenwhql** [comment]
@piotrekobi 

> Forcing GetExpectedKernelType to be executed for each operation can be achieved by removing this if condition in operator.cc:1490
> 
> ```c++
> if (kernel_type_.get() == nullptr || kernel_func_.get() == nullptr) {
>       ChooseKernel(exe_ctx);
>       dev_ctx = pool.Get(kernel_type_->place_);
>     }
> ```

If you want forcing choose kernel in runtime, except this if condition, also need remove another if condition, if we remove all xpu marco impl, we can see the logic here clearly, focus the comment:

```c++
  phi::KernelKey phi_kernel_key;
  std::string phi_kernel_name;
  // Here we judge whether the base CPU kernel exists in PHI, for pool2d, it is true
  if (phi::KernelFactory::Instance().HasCompatiblePhiKernel(type_)) {
    if (kernel_signature_ == nullptr || phi_kernel_ == nullptr) { // also need remove this if cond
      kernel_signature_.reset(new phi::KernelSignature(
          std::move(GetExpectedPhiKernelArgs(exe_ctx))));
      kernel_type_.reset(
          new OpKernelType(std::move(InnerGetExpectedKernelType(exe_ctx))));  // call the GetExpectedKernelType for pool2d
      dev_ctx = pool.Get(kernel_type_->place_);

      phi_kernel_name = kernel_signature_->name;
      // if CanMKLDNNSupportPool return false, here the kernel key is CPU kernel key
      phi_kernel_key = TransOpKernelTypeToPhiKernelKey(*kernel_type_.get());
      // it will found CPU pool2d kernel here in runtime, if not found, it will get a null phi_kernel, it is invalid
      phi_kernel_.reset(
          new phi::Kernel(phi::KernelFactory::Instance().SelectKernel(
              phi_kernel_name, phi_kernel_key)));
    } else {
      phi_kernel_name = kernel_signature_->name;
      phi_kernel_key = TransOpKernelTypeToPhiKernelKey(*kernel_type_.get());
    }

    if (phi_kernel_->IsValid()) {
      run_phi_kernel_ = true;
    } else {
      auto& all_op_kernels = AllOpKernels();
      // if CanMKLDNNSupportPool return true, it will found mkldnn pool2d kernel here
      auto kernels_iter = all_op_kernels.find(type_);
      if (kernels_iter == all_op_kernels.end() ||
          kernels_iter->second.find(*kernel_type_.get()) ==
              kernels_iter->second.end()) {
        auto phi_cpu_kernel_key =
            FallBackToCpu(*kernel_type_.get(), phi_kernel_key, *this);
        phi_kernel_.reset(
            new phi::Kernel(phi::KernelFactory::Instance().SelectKernel(
                phi_kernel_name, phi_cpu_kernel_key)));

        dev_ctx = pool.Get(platform::CPUPlace());
        if (phi_kernel_->IsValid()) {
          run_phi_kernel_ = true;
        }
      }
    }
  }
  if (!run_phi_kernel_) {
    if (kernel_type_.get() == nullptr || kernel_func_.get() == nullptr) {
      ChooseKernel(exe_ctx);
      dev_ctx = pool.Get(kernel_type_->place_);
    }
  }
```

we can see the PHI kernel has higher priority than fluid kernel, but they can replace each other in runtime, we also can change the kernel from oneDNN to PHI during runtime  if we remove the follow if condition:

```c++
if (kernel_signature_ == nullptr || phi_kernel_ == nullptr) { ...
```

PHI kernel will unify all kernel type in the future, so the logic here will be simplified
