### ISSUE TITLE
scatter函数的index参数什么时候能够支持二维tensor

### ISSUE THREAD

**Issue by nuaaceieyty** [PaddlePaddle/Paddle#43157]
### 需求描述 Feature Description

目前scatter函数的index参数只能传入一维tensor，所以在需要传入二维tensor时只能将结合其他API做很复杂的转换来实现，非常影响程序运行速度。所以，希望飞桨团队能够解决下这个问题，满足我们开发者一年多来的愿望。谢谢！

**Comment by TingquanGao** [comment]
hi，你好，可以看一下这个api是否能满足需求。
https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/put_along_axis_cn.html#put-along-axis
