### ISSUE TITLE
动态图backward执行完成后，print loss报错：(External) CUDA error(700), an illegal memory access was encountered

### ISSUE THREAD

**Issue by jesiws** [PaddlePaddle/Paddle#43170]
paddle版本：2.2.0
现象：动态图backward执行完成后，print loss报错：(External) CUDA error(700), an illegal memory access was encountered
![image](https://user-images.githubusercontent.com/23470771/171551818-96a683d8-dfea-4504-bc28-881dcdaed12a.png)

该错误的出现具有一定的随机性，数据检查过没有问题，调整batch_size和lr都有可能出现该错误，也不是显存不足，想咨询一下还能从哪块入手来查问题呢？

**Comment by DesmonDay** [comment]
可以尝试使用cuda-memcheck来定位问题。使用方法：cuda-memcheck python xxx.py。另外注意到CUDA执行存在异步性，因此可以先`export FLAGS_benchmak=1` 设置op执行同步后，再用cuda-memcheck。

**Comment by jesiws** [comment]
发现是显存不足的问题，通过调小batchsize能将这个问题的出现推迟，通过nvidia-smi观察模型训练过程中显存占用大概为8G，显卡是20G的，请问中间变量能占到这么多显存吗？能怎么优化一下吗？
尝试了![image](https://user-images.githubusercontent.com/23470771/173512643-7c4a1353-2947-4353-af8b-a8b1c2051736.png)没什么作用
 @DesmonDay

**Comment by DesmonDay** [comment]
如果实在不确定哪一块显存占用多，可以采用二分法对代码依次进行定位，看看哪块地方在执行时突然显存增长。（我自己的建议是可以考虑用pdb调试一步步执行，顺便记录代码执行时显存的增长，确定具体位置。
