### ISSUE TITLE
pr没有被review

### ISSUE THREAD

**Issue by yechenzhi** [PaddlePaddle/Paddle#43190]
### 问题描述 Please describe your issue

paddleRec里面MIND模型有个简单的bug，想蹭个pr，https://github.com/PaddlePaddle/PaddleRec/pull/789

**Comment by wuyefeilin** [comment]
同学您好， 您这是关于PaddleRec的相关需求，建议到PaddleRec套件下提出相应问题。 @seemingwang 麻烦帮忙看一下哈

**Comment by yinhaofeng** [comment]
已在pr中回复，相关问题已有修复pr：https://github.com/PaddlePaddle/PaddleRec/pull/779
再次感谢这位用户的参与~
