### ISSUE TITLE
飞桨支持C++吗?

### ISSUE THREAD

**Issue by yuwoyizhan** [PaddlePaddle/Paddle#43199]
### 需求描述 Feature Description

pytorch在一年多以前,就非常完善的支持C++编程了,比如图像分类这个任务,可以从头到尾,不使用一行python代码完成数据集下载,加载,训练,预测等步骤.知乎和CSDN也有很多pytorch的C++编程代码,可以让我们学习和参考.目前我都没看到一个项目使用C++完成飞桨任务的,无论是图像分类clas等开发套件,还是飞桨paddlepaddle,我想请问,飞桨是否打算支持C++编程呢?
我不敢说pytorch支持C++20,C++23这些很新的标准,但是用VS2022编写pytorch代码,完全没有问题.对于飞桨框架来说,目前C++似乎只能用于预测,而且一个预测的代码,比如图像分类clas的C++预测代码,超级多代码,无语,能否封装一下,像python一样,实现一行C++代码预测呢?如果目前C++已经能用于飞桨的话,麻烦你们多提供项目案例,让我知道如何写代码,谢谢,比如可以一个开发套件做一个C++案例.

我还想请问下,我现在使用windows,C++,5600gCPU,飞桨.对于图像分类clas和目标检测dec这两个开发套件来说,预测时使用的是多核心多线程还是单核心单线程CPU?另外,预测是否可以让客户自主选择使用多少个CPU线程?
我有一个预测任务,单开任务的话,我希望,CPU的6核心12线程都可以参与预测.但是如果双开任务,我就希望为每个预测任务分配3核心6线程.

**Comment by spencergotowork** [comment]
同问，还有一个问题就是，paddle的C++版本对opencv的支持是怎样的，目前我尝试利用paddle inference对resnet模型推理，输入模型是将opencv的mat转化为一维的vector<float> 作为输入，因为看demo上是这样的，但是这样处理好麻烦，请问有更简洁的方法或者可以借鉴的demo吗（不是官方文档提到的那些）

**Comment by juncaipeng** [comment]
@yuwoyizhan 
你好，目前飞桨不支持外部同学使用c++进行训练，推荐使用python进行训练，使用python cpp c等进行部署。
c++预测，实质上不复杂，套件是为了兼容多个模型，所以内容有点多吧。建议参考[文档](https://www.paddlepaddle.org.cn/inference/product_introduction/inference_intro.html)熟悉paddle inference预测的方法。
关于cpu上多核心多线程的问题，我找相关同学来解答一下。据我所知，目前不支持你说的这么灵活。

**Comment by juncaipeng** [comment]
> 同问，还有一个问题就是，paddle的C++版本对opencv的支持是怎样的，目前我尝试利用paddle inference对resnet模型推理，输入模型是将opencv的mat转化为一维的vector 作为输入，因为看demo上是这样的，但是这样处理好麻烦，请问有更简洁的方法或者可以借鉴的demo吗（不是官方文档提到的那些）

飞桨c++预测，直接链接opencv即可。比如：https://github.com/PaddlePaddle/PaddleClas/blob/release/2.3/docs/zh_CN/inference_deployment/cpp_deploy.md

**Comment by jiangjiajun** [comment]
关于`cpu上多核心多线程`这个问题，我咨询了下英特尔的同事，

一般而言，每个核是两个线程，设置的线程数大的话，自然就用到了多核
