### ISSUE TITLE
想问一下paddle模型部署在atlas300上是否有样例，服务器不是在移动端而是在工控机

### ISSUE THREAD

**Issue by jiejiangd** [PaddlePaddle/Paddle#43203]
### 需求描述 Feature Description

任务目标（请描述你正在做的项目是什么，如模型、论文、项目是什么？）; <br /> 需求场景（请描述你的项目中为什么需要用此功能）;  <br /> 功能描述（请简单描述或设计这个功能）

**Comment by juncaipeng** [comment]
新硬件都是paddlelite进行接入，所有硬件部署示例在：https://www.paddlepaddle.org.cn/lite/v2.10/demo_guides/android_app_demo.html
我找相关同学再问下是否支持atlas300。

**Comment by hong19860320** [comment]
目前 PaddleLite 已经支持 atlas 系列的推理，具体可以查看文档 https://paddle-lite.readthedocs.io/zh/latest/demo_guides/huawei_ascend_npu.html 或 https://www.paddlepaddle.org.cn/lite/develop/demo_guides/huawei_ascend_npu.html ，在配置好环境后（即安装指定版本的驱动、CANN 并创建 docker 容器），可以使用文档中的 paddlelite-generic-demo 一键测试。
