### ISSUE TITLE
ModuleNotFoundError: No module named 'paddle.utils'

### ISSUE THREAD

**Issue by DeqianBai** [PaddlePaddle/Paddle#43207]
### bug描述 Describe the Bug

Linux环境

>>> import paddle
>>> from paddle.utils.download import get_path_from_url
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'paddle.utils'

版本信息：
Name: paddlepaddle-gpu
Version: 2.2.2

已安装
paddle==1.0.2 和 paddlehub==2.0.0b1/2.2.0
依然报同样的错误

**Comment by juncaipeng** [comment]
> paddle==1.0.2 和 paddlehub==2.0.0b1/2.2.0

paddle版本太老，建议进行升级。

**Comment by juncaipeng** [comment]
如果有任何问题 请进行repon issue 进行更新
