### ISSUE TITLE
OSError: (External) CUDA error(2), out of memory.    [Hint: 'cudaErrorMemoryAllocation'. The API call failed because it was unable to allocate enough memory to perform the requested operation. ] (at /paddle/paddle/phi/backends/gpu/gpu_context.cc:359)

### ISSUE THREAD

**Issue by HWH-2000** [PaddlePaddle/Paddle#43211]
### 请提出你的问题 Please ask your question
Traceback (most recent call last):
  File "train_8.py", line 125, in <module>
    paddle.device.cuda.empty_cache()
  File "/root/anaconda3/envs/deeplearning3.7/lib/python3.7/site-packages/paddle/device/cuda/__init__.py", line 153, in empty_cache
    core.cuda_empty_cache()
OSError: (External) CUDA error(2), out of memory. 
  [Hint: 'cudaErrorMemoryAllocation'. The API call failed because it was unable to allocate enough memory to perform the requested operation. ] (at /paddle/paddle/phi/backends/gpu/gpu_context.cc:359)

I put a very small model on the GPU, but this error occurred. My GPU is 24GB, and the model is only about 3GB. Obviously, there is still a lot of memory space, but this error is still reported, I don’t know. Why?
I tried to reduce the batch size, but still reported this error

**Comment by David-19940718** [comment]
The same issue for me? Who can address this problem, thank u very much!

**Comment by Yosiiiiiiiiiiiiiiii** [comment]
I have the same issue.

**Comment by Xavier-W** [comment]
I have the same issue. 
When I run `paddle.utils.run_check()`, it prints

> Running verify PaddlePaddle program ...
> W0517 15:58:21.471099  9653 device_context.cc:447] Please NOTE: device: 0, GPU Compute Capability: 8.6, Driver API Version: 11.2, Runtime API Version: 11.2
> W0517 15:58:21.472824  9653 device_context.cc:465] device: 0, cuDNN Version: 8.2.
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/home/maoyc/anaconda3/envs/paddle/lib/python3.6/site-packages/paddle/utils/install_check.py", line 196, in run_check
>     _run_static_single(use_cuda)
>   File "/home/maoyc/anaconda3/envs/paddle/lib/python3.6/site-packages/paddle/utils/install_check.py", line 124, in _run_static_single
>     exe.run(startup_prog)
>   File "/home/maoyc/anaconda3/envs/paddle/lib/python3.6/site-packages/paddle/fluid/executor.py", line 1262, in run
>     six.reraise(*sys.exc_info())
>   File "/home/maoyc/anaconda3/envs/paddle/lib/python3.6/site-packages/six.py", line 719, in reraise
>     raise value
>   File "/home/maoyc/anaconda3/envs/paddle/lib/python3.6/site-packages/paddle/fluid/executor.py", line 1260, in run
>     return_merged=return_merged)
>   File "/home/maoyc/anaconda3/envs/paddle/lib/python3.6/site-packages/paddle/fluid/executor.py", line 1402, in _run_impl
>     use_program_cache=use_program_cache)
>   File "/home/maoyc/anaconda3/envs/paddle/lib/python3.6/site-packages/paddle/fluid/executor.py", line 1492, in _run_program
>     [fetch_var_name])
> 
> 
> OSError: (External) CUDA error(2), out of memory.
>   [Hint: 'cudaErrorMemoryAllocation'. The API call failed because it was unable to allocate enough memory to perform the requested operation. ] (at /paddle/paddle/fluid/platform/stream/cuda_stream.cc:45)
