### ISSUE TITLE
[code format] 去除代码里面多余的空格?

### ISSUE THREAD

**Issue by gglin001** [PaddlePaddle/Paddle#43212]
### 请提出你的问题 Please ask your question

hi, 看到最近一些 PR做了很多 code format 的优化, 请问有添加去除代码多余空格的计划吗

比如使用 pre-commit 的 

```
      - id: trailing-whitespace

```
or 其他的方法

一些多余空格的example:

<img width="1529" alt="Screen Shot 2022-06-06 at 11 21 20 AM" src="https://user-images.githubusercontent.com/13805221/172089073-4478ec0e-fa88-4a9d-b505-164a6a643e40.png">

**Comment by gglin001** [comment]
@betterpig 麻烦问下有此计划吗

**Comment by betterpig** [comment]
> @betterpig 麻烦问下有此计划吗

你好，cmake-format的引入能够将你举的例子中的尾随空格去掉。该文件目前还存在多余空格是因为之前全量格式化时漏掉了根目录下的cmake文件，后续会提PR将其格式化。

**Comment by gglin001** [comment]
> > @betterpig 麻烦问下有此计划吗
> 
> 你好，cmake-format的引入能够将你举的例子中的尾随空格去掉。该文件目前还存在多余空格是因为之前全量格式化时漏掉了根目录下的cmake文件，后续会提PR将其格式化。

感谢回复.
另外, 目前的代码对于 cpp 的代码 使用 pre-commit 会清理空格, 对 python 代码的空格似乎还是没有检查?

**Comment by Shixiaowei02** [comment]
您好，@betterpig 正在进行代码格式检查的升级，请将需求后续提到此 issue 下，我们跟进。谢谢！

**Comment by betterpig** [comment]
> > > @betterpig 麻烦问下有此计划吗
> > 
> > 
> > 你好，cmake-format的引入能够将你举的例子中的尾随空格去掉。该文件目前还存在多余空格是因为之前全量格式化时漏掉了根目录下的cmake文件，后续会提PR将其格式化。
> 
> 感谢回复. 另外, 目前的代码对于 cpp 的代码 使用 pre-commit 会清理空格, 对 python 代码的空格似乎还是没有检查?

最近已将Paddle使用的python格式化工具yapf升级到0.32.0（PR #42944 ），经本地测试该工具能够去除python代码的尾随空格。

**Comment by gglin001** [comment]
> > > > @betterpig 麻烦问下有此计划吗
> > > 
> > > 
> > > 你好，cmake-format的引入能够将你举的例子中的尾随空格去掉。该文件目前还存在多余空格是因为之前全量格式化时漏掉了根目录下的cmake文件，后续会提PR将其格式化。
> > 
> > 
> > 感谢回复. 另外, 目前的代码对于 cpp 的代码 使用 pre-commit 会清理空格, 对 python 代码的空格似乎还是没有检查?
> 
> 最近已将Paddle使用的python格式化工具yapf升级到0.32.0（PR #42944 ），经本地测试该工具能够去除python代码的尾随空格。

👍🏼
是这样子, 应该是我之前的环境不是最新的
