### ISSUE TITLE
 (this issue is just for my personal  self-learning) incomplete  feature:   paddle.optimizer.lr.CosineAnnealingDecay 

### ISSUE THREAD

**Issue by OccupyMars2030** [PaddlePaddle/Paddle#43217]
### 问题描述 Please describe your issue

  paddle.optimizer.lr.CosineAnnealingDecay    only implements the cosine annealing part of SGDR, and not the restarts.

TODO:  try  to  implement  "the  restarts" part

reference:    "class CosineLRScheduler(Scheduler):"  in  timm\scheduler\cosine_lr.py  (you need  to  install  timm  module)

**Comment by Shixiaowei02** [comment]
We will judge and fix this issue. Thanks for your cooperation!

**Comment by zhwesky2010** [comment]
@SmirnovKol 请问是需要实现什么功能呢

**Comment by OccupyMars2030** [comment]
没有。我看到paddle.optimizer.lr.CosineAnnealingDecay 的注释里面说“only implements the cosine annealing part of SGDR, and not the restarts.”，所以我想尝试自己实现“ restarts”部分，以后我会自己尝试实现后提交PR。我提交这个issue，更多的是为了记录自己的学习过程，你们可以忽略或者直接关闭这个issue

**Comment by OccupyMars2030** [comment]
this issue is just for my personal  self-learning
