### ISSUE TITLE
应该如何使用sparse_vector? 有demo吗？

### ISSUE THREAD

**Issue by joseph-chan** [PaddlePaddle/Paddle#4322]
sparse_vector如何初始化，貌似没有demo，有谁可以提供一些demo,或者完善一下接口文档吗？

**Comment by lcy-seso** [comment]
请参考paddle models 下CTR 预估的例子。

更多数据格式说明请参考此文档：
http://doc.paddlepaddle.org/doc_cn/getstarted/concepts/use_concepts_cn.html
