### ISSUE TITLE
集群训练batch_size的疑问

### ISSUE THREAD

**Issue by alanse7en** [PaddlePaddle/Paddle#4323]
RT.
paddle v2中，在使用MPI集群训练时，两种设置，（1）100个节点，batch_size=128和（2）10个节点，batch_size=1280，两种方案整体的batch_size都是12800吧？理论上训练结果应该没有太大差别吧？

**Comment by lcy-seso** [comment]
- 多机训练时，实际的batch size = 配置中的batch size * 结点数目。
- 理论上没有太大差别。
