### ISSUE TITLE
执行01.fit_a_line时出现的问题，麻烦请解答，请见下图

### ISSUE THREAD

**Issue by jiaodayuan** [PaddlePaddle/Paddle#4324]
[图片]

**Comment by WalterShe** [comment]
兄弟,你的图呢?

**Comment by jiaodayuan** [comment]
![2f7768f655dbc225d3879c6e3d64aa60](https://user-images.githubusercontent.com/32194127/30795884-47b4b66a-a202-11e7-80b1-b61ae65a2e89.JPG)

**Comment by Canpio** [comment]
See  https://github.com/PaddlePaddle/Paddle/issues/2669

**Comment by Yancey1989** [comment]
请拷贝使用jumbo安装的Python环境下的sqlite3的so到paddle环境下，并执行`source env.sh`，具体步骤参见内网wiki。

我先关闭这个issue了，如有问题请再打开。
