### ISSUE TITLE
paddle 是不支持 c 扩展了么

### ISSUE THREAD

**Issue by HaozhengAN** [PaddlePaddle/Paddle#43240]
### 请提出你的问题 Please ask your question

现在有一个python 脚本，其中调用了 如下的函数：
    model = paddle.jit.to_static(model, input_spec=inputs)
    paddle.jit.save(model, global_config['best_model_dir'] + '/infer_model')

在未使用 cython 对 py 脚本进行编译前，可以正常执行，但是使用了 cython 将 py 脚本编译成 so 文件后，就会报如下的错误：
![cfee1c450012e7a126e48cb18091c35a](https://user-images.githubusercontent.com/34512369/172137762-2f90cea1-81e4-46d4-ac99-3f00c675e00f.png)

**Comment by Shixiaowei02** [comment]
您好，这看起来是一个 bug，我们跟进下，谢谢

**Comment by jluhuangj** [comment]
请问现在解决了吗？
