### ISSUE TITLE
官方docker镜像安装好后不让ssh登录

### ISSUE THREAD

**Issue by WalterShe** [PaddlePaddle/Paddle#4325]
官方文档 http://doc.paddlepaddle.org/doc_cn/getstarted/build_and_install/docker_install_cn.html 里面提到
> docker run -d -p 2202:22 -p 8888:8888 paddledev/paddle:<version>-dev
然后用密码 root SSH进入容器：ssh -p 2202 root@localhost

但是 我使用ssh -p 2202 root@localhost 不让登录,被拒绝了(ssh: connect to host localhost port 2202: Connection refused),是不是docker镜像里面没有开放ssh登录.能解决一下吗.我用的是sudo docker run -d -p 2202:22 -p 8888:8888 docker.paddlepaddle.org/paddle:0.10.0-dev 命令安装的docker镜像

**Comment by baidu-fpga** [comment]
试试
docker run -d -p 2202:22 -p 8888:8888 paddledev/paddle:XXX-dev  /usr/sbin/sshd -D

**Comment by shijiaxin** [comment]
试试
docker run -d -p 2202:22 -p 8888:8888 paddledev/paddle:XXX-dev  /usr/sbin/sshd -D

**Comment by WalterShe** [comment]
@shijiaxin 问题解决了!你是大帅哥!!!!!

**Comment by luotao1** [comment]
@WalterShe 在develop的文档中有写新的命令：
http://doc.paddlepaddle.org/develop/doc_cn/getstarted/build_and_install/docker_install_cn.html
