### ISSUE TITLE
aistudio运行报错(lwfx)

### ISSUE THREAD

**Issue by jyjfjyjf** [PaddlePaddle/Paddle#43259]
### bug描述 Describe the Bug

W0607 04:40:40.849649  1186 gpu_context.cc:278] Please NOTE: device: 0, GPU Compute Capability: 7.0, Driver API Version: 11.2, Runtime API Version: 10.2
W0607 04:40:40.855998  1186 gpu_context.cc:306] device: 0, cuDNN Version: 7.6.
W0607 04:40:45.300216  1186 dynamic_loader.cc:305] The third-party dynamic library (libcuda.so) that Paddle depends on is not configured correctly. (error code is /usr/lib/x86_64-linux-gnu/libcuda.so: file too short)
  Suggestions:
  1. Check if the third-party dynamic library (e.g. CUDA, CUDNN) is installed correctly and its version is matched with paddlepaddle you installed.
  2. Configure third-party dynamic library environment variables as follows:
  - Linux: set LD_LIBRARY_PATH by `export LD_LIBRARY_PATH=...`
  - Windows: set PATH by `set PATH=XXX;
段错误 (核心已转储)

**Comment by SunNy820828449** [comment]
建议按照建议检查一下你的libcuda.so文件是否完好。

**Comment by jyjfjyjf** [comment]
这是aistudio上遇到的问题，我没事去动aistudio上面的这个玩意干嘛，我本地跑没事

**Comment by SunNy820828449** [comment]
能提供项目链接么 我去复现一下

**Comment by jyjfjyjf** [comment]
应该是更新了paddlepaddle-gpu到2.3的原因1，不更新就没事了

**Comment by SunNy820828449** [comment]
没问题就close了吧，谢谢
