### ISSUE TITLE
【队名】：双子吹雪酱

### ISSUE THREAD

**Issue by tpder** [PaddlePaddle/Paddle#43256]
【队名】：双子吹雪酱

【序号】：142

【论文】：[Few-Shot Learning with Graph Neural Networks](https://openreview.net/pdf?id=BJj6qGbRW)

【状态】：报名

【repo链接】：https://github.com/tpder/Few-Shot_paddle

**Comment by SunNy820828449** [comment]
收到，已经通知相关同事。

**Comment by Ligoml** [comment]
报名需要在这里按格式回复：https://github.com/PaddlePaddle/Paddle/issues/41482 不是提新的issue哦~
