### ISSUE TITLE
(this issue is just for my personal  self-learning )incomplete feature:   Tensor.add_(3)  throw error "AttributeError: 'int' object has no attribute 'shape'"

### ISSUE THREAD

**Issue by OccupyMars2030** [PaddlePaddle/Paddle#43261]
### 问题描述 Please describe your issue

`
import paddle   
x = paddle.to_tensor([1, 2, 3])    
x.add_(3)    
`
The above code will throw an error, but the following code works
`
import paddle    
x = paddle.to_tensor([1, 2, 3])    
x.add_(paddle.to_tensor(3))    
`

TODO:  make  a  python  float  or  int  value  to  be  a  legal  argument  in  add_()  .
A  Tensor has attribute   add_,  subtract_  ,  but  doesn't  have  multiply_  or   divide_,   this  is  a  little  strange ???

**Comment by SunNy820828449** [comment]
If tensor is a matrix, we can't just add attributes  'multiply_'  and 'divide_' like 'add_'.

**Comment by OccupyMars2030** [comment]
I  don't  quite understand  what  you mean.
`import torch

x = torch.arange(6).reshape([2, 3]).type(torch.float)
print(x)
x.mul_(2)
print(x)
x.div_(2)
print(x)`

In pytorch,  the above code can  work,  but  in  paddlepaddle,   there seems  to  be  no such  thing

**Comment by OccupyMars2030** [comment]
I may  understand  what you mean.   Do you mean  when  a  tensor  is  a  matrix,  it  may  perform  matrix  multiplication?  But  here  I am  talking  about  elementwise operation.  As  long as  Paddle  has  paddle.multiply(x, y),  why  Paddle  cannot  have  in-place  version  of   "paddle.multiply" ???

**Comment by SunNy820828449** [comment]
you can do it like this:
import paddle
x = paddle.to_tensor([1,2,3])
y = x + 1
print(y)
z = y * 3
print(z)

https://www.paddlepaddle.org.cn/documentation/docs/zh/guides/beginner/tensor_cn.html#shuxueyunsuan

**Comment by OccupyMars2030** [comment]
Emm..  I know  your  code.  But what I  want  is  in-place operation.  Because I  don't quite understand the mechanism  of  in-place operation   and  those matrix  stuff,   so  I  don't  know what  to say.  You  can  just  ignore or  close this issue.   Thank you  for  your  answer.
