### ISSUE TITLE
Add "serving" features in paddle cloud

### ISSUE THREAD

**Issue by typhoonzero** [PaddlePaddle/Paddle#4326]
Add ability to "serve" a trained model, providing HTTP endpoint to fetch inference result.

For ease of using, people only need provide the model graph(or topology) and model parameters. Paddle Cloud will generate a unique URL for current "serving" instance, and this URL can be accessed from the internet.

The resource for the "serving" instance will be restricted under user's quota.

**Comment by helinwang** [comment]
I think https://github.com/PaddlePaddle/book/tree/develop/serve satisfy the inference requirement. Maybe we can start from there. We can add a reverse proxy on top of it to map the user's URL to the correct backend.
