### ISSUE TITLE
(this issue is just for my personal self-learning ) not  flexible  enough:  paddle.scatter()

### ISSUE THREAD

**Issue by OccupyMars2030** [PaddlePaddle/Paddle#43260]
### 问题描述 Please describe your issue

"torch code,  can  be  replaced  with  torch.nn.functional.one_hot"
def one_hot_torch(x, num_classes, on_value=1., off_value=0., device='cuda'):   
    x = x.long().view(-1, 1)    
    return torch.full((x.size()[0], num_classes), off_value, device=device).scatter_(1, x, on_value)

“paddle version”
def one_hot(x, num_classes, on_value=1., off_value=0., device='cuda'):
    x = x.astype("int64").reshape([-1])
    out = paddle.nn.functional.one_hot(x, num_classes=num_classes)
    out = paddle.where(out > 0.5, on_value, off_value)
    out = paddle.to_tensor(out, place=paddle.CUDAPlace(0) if paddle.is_compiled_with_cuda() else paddle.CPUPlace())
    return out

TODO:  When  I  study  the above code,  I  find out that  compared to  torch.scatter(),  paddle.scatter() is not  flexible  enough.  The  key  problems are  how to  "index"  and  how to handle the case  when  there  are  repeated numbers  in "index"  especially  in  GPU  mode ( simultaneous  running  threads that  work   on  the  same  element  in  a   tensor may  have  conflicts ???)

The  following  two  PRs  may  have  the  same  problems:
[paddle.index_add](https://github.com/PaddlePaddle/Paddle/pull/42475)
[paddle.index_fill](https://github.com/PaddlePaddle/Paddle/pull/42454)

**Comment by SunNy820828449** [comment]
Thanks for your issue. We will feedback this issue to our developer.

**Comment by Ligoml** [comment]
In fact, [paddle.put_along_axis](https://www.paddlepaddle.org.cn/documentation/docs/en/develop/api/paddle/put_along_axis_en.html) and `torch.scatter` are corresponding, we suggest you try `paddle.put_along_axis` to solve this issue. We will add clarification later in the documentation.

**Comment by OccupyMars2030** [comment]
Thank you  for  your  answer.
