### ISSUE TITLE
相同代码 linux无法正常运行， windows可以正常运行

### ISSUE THREAD

**Issue by ljl86092297** [PaddlePaddle/Paddle#43285]
### bug描述 Describe the Bug

![image](https://user-images.githubusercontent.com/59467994/172346504-47f38cb8-96e1-4705-b2b6-98a5ca843509.png)
![image](https://user-images.githubusercontent.com/59467994/172346593-50d1f13f-70bf-40b6-b6c4-ea29021a9ac5.png)
上述是windows 情况下 python3.8 paddle2.3.0 可以正常读取模型推理
以下是linux下，python3.7 paddle2.3.0 读取报错
![image](https://user-images.githubusercontent.com/59467994/172346967-bef6ae87-ed33-4082-8b57-30d8c4e904b2.png)

**Comment by ccrrong** [comment]
你好，可以先确认一下模型文件是否正确呢
