### ISSUE TITLE
Linux下使用Docker编译，执行make时报错

### ISSUE THREAD

**Issue by umiswing** [PaddlePaddle/Paddle#43287]
### 问题描述 Issue Description

按照[官方文档](https://www.paddlepaddle.org.cn/documentation/docs/zh/install/compile/linux-compile.html)在Linux下使用Docker从源码编译。在/paddle/build下执行make -j$(nproc)，编译过程中报错：

[ 19%] Building CUDA object paddle/phi/kernels/CMakeFiles/tile_grad_kernel.dir/gpu/tile_grad_kernel.cu.o
Killed
paddle/phi/kernels/CMakeFiles/strided_slice_grad_kernel_base.dir/build.make:75: recipe for target 'paddle/phi/kernels/CMakeFiles/strided_slice_grad_kernel_base.dir/gpu/strided_slice_grad_kernel.cu.o' failed
make[2]: *** [paddle/phi/kernels/CMakeFiles/strided_slice_grad_kernel_base.dir/gpu/strided_slice_grad_kernel.cu.o] Error 137
CMakeFiles/Makefile2:17334: recipe for target 'paddle/phi/kernels/CMakeFiles/strided_slice_grad_kernel_base.dir/all' failed
make[1]: *** [paddle/phi/kernels/CMakeFiles/strided_slice_grad_kernel_base.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....

### 版本&环境信息 Version & Environment Information

****************************************
Paddle version: 2.3.0
Paddle With CUDA: True

OS: Ubuntu 18.04
Python version: 3.7.13

CUDA version: 11.2.142
Build cuda_11.2.r11.2/compiler.29558016_0
cuDNN version: None.None.None
Nvidia driver version: 510.73.05
****************************************

**Comment by umiswing** [comment]
使用https://github.com/baidu/AnyQ/issues/61 的方法，修改线程数为8，依然无法编译通过。

**Comment by SunNy820828449** [comment]
确认已经安装cuda，并使用更少的线程编译，可以贴出更多的报错信息。

**Comment by umiswing** [comment]
@SunNy820828449
> 确认已经安装cuda，并使用更少的线程编译，可以贴出更多的报错信息。

使用4个线程可以编译。但是请问container的内存要分配多少才够？我分配到了8G编译过程中还是会因为内存占满卡住。

**Comment by umiswing** [comment]
使用4个线程，container分配10G内存后，完成了编译。
