### ISSUE TITLE
cuda9.0  python=3.7.3 安装paddlepaddle-gpu==1.7.0 检查是否安装成功时输入paddle.fluid.install_check.run_check()报如下错误

### ISSUE THREAD

**Issue by huahuabai** [PaddlePaddle/Paddle#43298]
Thank you for contributing to PaddlePaddle. Submitting an issue is a great help for us.
Both Chinese and English issues are welcome.

It's hard to solve a problem when important details are missing.
Before submitting the issue, look over the following criteria before handing your request in.

- [ ] Was there a similar issue submitted or resolved before ? You could search issue in the github.
- [ ] Did you retrieve your issue from widespread search engines ?
- [ ] Is my description of the issue clear enough to reproduce this problem?
   * If some errors occurred, we need details about `how do you run your code?`, `what system do you use?`, `Are you using GPU or not?`, etc.
   * If you use an recording [asciinema](https://asciinema.org/) to show what you are doing to make it happen, that's awesome! We could help you solve the problem more quickly.
- [ ] Is my description of the issue use the github markdown correctly?
   * Please use the proper markdown syntaxes for styling all forms of writing, e.g, source code, error information, etc.
   * Check out [this page](https://guides.github.com/features/mastering-markdown/) to find out much more about markdown.

**Comment by huahuabai** [comment]
![image](https://user-images.githubusercontent.com/55180640/172412834-b9a7b86a-965a-4b84-8c9d-40f64c04ea87.png)
![image](https://user-images.githubusercontent.com/55180640/172412883-1e268eca-0930-44f3-afa6-86b1f58c50e7.png)
![image](https://user-images.githubusercontent.com/55180640/172412947-1b3864c3-f868-4022-ab71-964e1cd6fd02.png)
![image](https://user-images.githubusercontent.com/55180640/172412996-ae4ed895-67c8-4ec0-8fd2-bad73476acb9.png)

**Comment by SunNy820828449** [comment]
你试试升级cuda到11.0以后的版本，然后重新安装新版本paddle试试，目前paddle已经更新到了2.3。
