### ISSUE TITLE
slowfast_fasterrcnn的推理出现OSError: (External) CUDA error(2), out of memory.

### ISSUE THREAD

**Issue by MintonLee** [PaddlePaddle/Paddle#43308]
### bug描述 Describe the Bug

出现的错误：
slowfast_fasterrcnn的推理出现OSError: (External) CUDA error(2), out of memory.

再复现项目：  基于SlowFast+FasterRCNN的动作识别  出现的以上错误

显卡12gb，占用不足20%出现以上的问题，请问如何解决呢？

**Comment by MintonLee** [comment]
> 您好，我们已经收到了您的问题，会安排技术人员尽快解答您的问题，请耐心等待。请您再次检查是否提供了清晰的问题描述、复现代码、环境&版本、报错信息等。同时，您也可以通过查看[官网API文档](https://www.paddlepaddle.org.cn/documentation/docs/zh/api_cn/index_cn.html)、[常见问题](https://www.paddlepaddle.org.cn/documentation/docs/zh/faq/index_cn.html)、[历史Issue](https://github.com/PaddlePaddle/Paddle/issues)、[AI社区](https://ai.baidu.com/forum/topic/list/168)来寻求解答。祝您生活愉快～
> 
> Hi! We've received your issue and please be patient to get responded. We will arrange technicians to answer your questions as soon as possible. Please make sure that you have posted enough message to demo your request. You may also check out the [API](https://www.paddlepaddle.org.cn/documentation/docs/zh/api_cn/index_cn.html)，[FAQ](https://www.paddlepaddle.org.cn/documentation/docs/zh/faq/index_cn.html)，[Github Issue](https://github.com/PaddlePaddle/Paddle/issues) and [AI community](https://ai.baidu.com/forum/topic/list/168) to get the answer.Have a nice d

> 您好，我们已经收到了您的问题，会安排技术人员尽快解答您的问题，请耐心等待。请您再次检查是否提供了清晰的问题描述、复现代码、环境&版本、报错信息等。同时，您也可以通过查看[官网API文档](https://www.paddlepaddle.org.cn/documentation/docs/zh/api_cn/index_cn.html)、[常见问题](https://www.paddlepaddle.org.cn/documentation/docs/zh/faq/index_cn.html)、[历史Issue](https://github.com/PaddlePaddle/Paddle/issues)、[AI社区](https://ai.baidu.com/forum/topic/list/168)来寻求解答。祝您生活愉快～
> 
> Hi! We've received your issue and please be patient to get responded. We will arrange technicians to answer your questions as soon as possible. Please make sure that you have posted enough message to demo your request. You may also check out the [API](https://www.paddlepaddle.org.cn/documentation/docs/zh/api_cn/index_cn.html)，[FAQ](https://www.paddlepaddle.org.cn/documentation/docs/zh/faq/index_cn.html)，[Github Issue](https://github.com/PaddlePaddle/Paddle/issues) and [AI community](https://ai.baidu.com/forum/topic/list/168) to get the answer.Have a nice day!

啥玩意都解决不了，还在这华丽花哨！哎，paddle发展不起都怪你，太懒了！

**Comment by 2742195759** [comment]
你好，请问具体报错的截图有吗，通常显存不足会有当前已分配 + 期望分配的显存。还有就是能定位到哪一行代码申请显存出问题的吗？

**Comment by MintonLee** [comment]
非常感谢您的来信这个问题是在复现官方案例：基于SlowFast+FasterRCNN的动作识别出现的问题
在aistudio（不同显卡都切换还是不行）和本地的双系统ubuntu和win10都是这个问题
问题如下：（paddle_slowfast即为官方的案例根目录）
finish object detection
Traceback (most recent call last):
&nbsp; File "tools/predict.py", line 267, in <module&gt;
&nbsp; &nbsp; main()
&nbsp; File "tools/predict.py", line 173, in main
&nbsp; &nbsp; inputs = InferenceHelper.preprocess(file)
&nbsp; File "D:\code\paddle_slowfast\work\PaddleVideo-develop\tools\utils.py", line 769, in preprocess
&nbsp; &nbsp; data = [paddle.to_tensor(img_slow,dtype='float32'),paddle.to_tensor(img_fast,dtype='float32'),paddle.to_tensor(proposals,dtype='float32'),paddle.to_tensor(img_shape,dtype='int32')]
&nbsp; File "D:\software\Anaconda3\envs\paddle\lib\site-packages\decorator.py", line 232, in fun
&nbsp; &nbsp; return caller(func, *(extras + args), **kw)
&nbsp; File "D:\software\Anaconda3\envs\paddle\lib\site-packages\paddle\fluid\wrapped_decorator.py", line 25, in __impl__
&nbsp; &nbsp; return wrapped_func(*args, **kwargs)
&nbsp; File "D:\software\Anaconda3\envs\paddle\lib\site-packages\paddle\fluid\framework.py", line 229, in __impl__
&nbsp; &nbsp; return func(*args, **kwargs)
&nbsp; File "D:\software\Anaconda3\envs\paddle\lib\site-packages\paddle\tensor\creation.py", line 172, in to_tensor
&nbsp; &nbsp; stop_gradient=stop_gradient)
OSError: (External) CUDA error(2), out of memory.
&nbsp; [Hint: 'cudaErrorMemoryAllocation'. The API call failed because it was unable to allocate enough memory to perform the requested operation. ] (at ..\paddle\fluid\platform\gpu_info.cc
:441)







------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/Paddle"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年6月9日(星期四) 下午2:22
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PaddlePaddle/Paddle] slowfast_fasterrcnn的推理出现OSError: (External) CUDA error(2), out of memory. (Issue #43308)





 
你好，请问具体报错的截图有吗，通常显存不足会有当前已分配 + 期望分配的显存。还有就是能定位到哪一行代码申请显存出问题的吗？

**Comment by 2742195759** [comment]
> 非常感谢您的来信这个问题是在复现官方案例：基于SlowFast+FasterRCNN的动作识别出现的问题 在aistudio（不同显卡都切换还是不行）和本地的双系统ubuntu和win10都是这个问题 问题如下：（paddle_slowfast即为官方的案例根目录） finish object detection Traceback (most recent call last): &nbsp; File "tools/predict.py", line 267, in <module&gt; &nbsp; &nbsp; main() &nbsp; File "tools/predict.py", line 173, in main &nbsp; &nbsp; inputs = InferenceHelper.preprocess(file) &nbsp; File "D:\code\paddle_slowfast\work\PaddleVideo-develop\tools\utils.py", line 769, in preprocess &nbsp; &nbsp; data = [paddle.to_tensor(img_slow,dtype='float32'),paddle.to_tensor(img_fast,dtype='float32'),paddle.to_tensor(proposals,dtype='float32'),paddle.to_tensor(img_shape,dtype='int32')] &nbsp; File "D:\software\Anaconda3\envs\paddle\lib\site-packages\decorator.py", line 232, in fun &nbsp; &nbsp; return caller(func, *(extras + args), **kw) &nbsp; File "D:\software\Anaconda3\envs\paddle\lib\site-packages\paddle\fluid\wrapped_decorator.py", line 25, in __impl__ &nbsp; &nbsp; return wrapped_func(*args, **kwargs) &nbsp; File "D:\software\Anaconda3\envs\paddle\lib\site-packages\paddle\fluid\framework.py", line 229, in __impl__ &nbsp; &nbsp; return func(*args, **kwargs) &nbsp; File "D:\software\Anaconda3\envs\paddle\lib\site-packages\paddle\tensor\creation.py", line 172, in to_tensor &nbsp; &nbsp; stop_gradient=stop_gradient) OSError: (External) CUDA error(2), out of memory. &nbsp; [Hint: 'cudaErrorMemoryAllocation'. The API call failed because it was unable to allocate enough memory to perform the requested operation. ] (at ..\paddle\fluid\platform\gpu_info.cc :441)
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "PaddlePaddle/Paddle" ***@***.***&gt;; 发送时间:&nbsp;2022年6月9日(星期四) 下午2:22 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [PaddlePaddle/Paddle] slowfast_fasterrcnn的推理出现OSError: (External) CUDA error(2), out of memory. (Issue #43308) 你好，请问具体报错的截图有吗，通常显存不足会有当前已分配 + 期望分配的显存。还有就是能定位到哪一行代码申请显存出问题的吗？ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

我看报错也没有非常具体的cuda显存信息，我这边复现一下，看看什么问题。是这个链接的复现步骤吗：https://github.com/PaddlePaddle/PaddleVideo/blob/develop/docs/zh-CN/model_zoo/detection/SlowFast_FasterRCNN.md。你本地没有什么修改吧。

**Comment by MintonLee** [comment]
好的，我复现的是这个链接的，把里边所有文件压缩后打包下载了。
https://aistudio.baidu.com/aistudio/projectdetail/3427778?channelType=0&amp;channel=0
我复现的时候，没有进行数据集的下载，只是用提供的一个小视频demo进行训练的，其他都没变。
我最多改变成了本地的绝对路径。不知道这样对不对。
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/Paddle"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年6月9日(星期四) 下午2:48
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PaddlePaddle/Paddle] slowfast_fasterrcnn的推理出现OSError: (External) CUDA error(2), out of memory. (Issue #43308)





  
非常感谢您的来信这个问题是在复现官方案例：基于SlowFast+FasterRCNN的动作识别出现的问题 在aistudio（不同显卡都切换还是不行）和本地的双系统ubuntu和win10都是这个问题 问题如下：（paddle_slowfast即为官方的案例根目录） finish object detection Traceback (most recent call last): &nbsp; File "tools/predict.py", line 267, in <module&gt; &nbsp; &nbsp; main() &nbsp; File "tools/predict.py", line 173, in main &nbsp; &nbsp; inputs = InferenceHelper.preprocess(file) &nbsp; File "D:\code\paddle_slowfast\work\PaddleVideo-develop\tools\utils.py", line 769, in preprocess &nbsp; &nbsp; data = [paddle.to_tensor(img_slow,dtype='float32'),paddle.to_tensor(img_fast,dtype='float32'),paddle.to_tensor(proposals,dtype='float32'),paddle.to_tensor(img_shape,dtype='int32')] &nbsp; File "D:\software\Anaconda3\envs\paddle\lib\site-packages\decorator.py", line 232, in fun &nbsp; &nbsp; return caller(func, (extras + args), kw) &nbsp; File "D:\software\Anaconda3\envs\paddle\lib\site-packages\paddle\fluid\wrapped_decorator.py", line 25, in impl &nbsp; &nbsp; return wrapped_func(args, kwargs) &nbsp; File "D:\software\Anaconda3\envs\paddle\lib\site-packages\paddle\fluid\framework.py", line 229, in impl &nbsp; &nbsp; return func(args, kwargs) &nbsp; File "D:\software\Anaconda3\envs\paddle\lib\site-packages\paddle\tensor\creation.py", line 172, in to_tensor &nbsp; &nbsp; stop_gradient=stop_gradient) OSError: (External) CUDA error(2), out of memory. &nbsp; [Hint: 'cudaErrorMemoryAllocation'. The API call failed because it was unable to allocate enough memory to perform the requested operation. ] (at ..\paddle\fluid\platform\gpu_info.cc :441)
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "PaddlePaddle/Paddle" @.&gt;; 发送时间:&nbsp;2022年6月9日(星期四) 下午2:22 @.&gt;; @.@.&gt;; 主题:&nbsp;Re: [PaddlePaddle/Paddle] slowfast_fasterrcnn的推理出现OSError: (External) CUDA error(2), out of memory. (Issue #43308) 你好，请问具体报错的截图有吗，通常显存不足会有当前已分配 + 期望分配的显存。还有就是能定位到哪一行代码申请显存出问题的吗？ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.&gt;
  
我看报错也没有非常具体的cuda显存信息，我这边复现一下，看看什么问题。是这个链接的复现步骤吗：https://github.com/PaddlePaddle/PaddleVideo/blob/develop/docs/zh-CN/model_zoo/detection/SlowFast_FasterRCNN.md。你本地没有什么修改吧。

**Comment by 2742195759** [comment]
我这边给你看了一下，显存溢出框架没有问题，这个模型我放在 16G 的显卡上跑还是会溢出。而且监控显存可以知道他就是需要消耗这么多显存。
<img width="767" alt="截屏2022-06-09 17 39 05" src="https://user-images.githubusercontent.com/16025309/172817728-cc1ed43c-b7fc-4a43-8410-853a528d133b.png">

这边给你的建议是将 /home/data/issue/work/ava_one.yaml 的 batch size 调小。我本地测试的是设置为2，最后的显存消耗是 5G，就可以跑起来这个模型了。
![image](https://user-images.githubusercontent.com/16025309/172817982-08de4526-a8f8-4893-b6cb-14837f27ef2a.png)

**Comment by MintonLee** [comment]
你好，这个训练我也能跑起来，现在的问题是不是训练步骤，是aistudio这个项目的最后一步的模型推理，就是相当于拿模型跑一段视频，然后要输出照片和视频，出现的这个问题。
下面命令出现的问题，请问，你也是这个命令吗？修改ava_one.yaml的batch_size,然后就可以推理了吗？
%cd /home/aistudio/work/PaddleVideo-develop/ !python tools/predict.py \     -c /home/aistudio/work/ava_one.yaml \     --input_file "/home/aistudio/work/data/room1.mp4" \     --model_file "/home/aistudio/work/PaddleVideo-develop/inference_output/AVA_SlowFast_FastRcnn.pdmodel" \     --params_file "/home/aistudio/work/PaddleVideo-develop/inference_output/AVA_SlowFast_FastRcnn.pdiparams" \     --use_gpu=True \     --use_tensorrt=False
还是这个命令，不输出视频，只输出照片？




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年6月9日(星期四) 下午5:43
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [PaddlePaddle/Paddle] slowfast_fasterrcnn的推理出现OSError: (External) CUDA error(2), out of memory. (Issue #43308)





 
我这边给你看了一下，显存溢出框架没有问题，这个模型我放在 16G 的显卡上跑还是会溢出。而且监控显存可以知道他就是需要消耗这么多显存。
 
 
这边给你的建议是将 /home/data/issue/work/ava_one.yaml 的 batch size 调小。我本地测试的是设置为5，最后的显存消耗是 5G，就可以跑起来这个模型了。

**Comment by 2742195759** [comment]
修复了batchsize之后也没啥问题：
<img width="952" alt="截屏2022-06-09 20 26 57" src="https://user-images.githubusercontent.com/16025309/172846707-29d4d746-399a-49ec-8071-2bf289178471.png">

**Comment by MintonLee** [comment]
是的，我也出现这个了，但是问题在于，保存完照片后，报的错，我看了看程序，大概好像会输出一个mp4的视频，可能是在输出视频的时候出的错吧。因为我想最终的结果是先切割照片并保存，最后保存识别的视频文件。请问输出保存之后，Finshed ...之后
没有报错吗？

---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年6月9日(周四) 晚上8:27
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [PaddlePaddle/Paddle] slowfast_fasterrcnn的推理出现OSError: (External) CUDA error(2), out of memory. (Issue #43308)




 
修复了batchsize之后也没啥问题：

**Comment by 2742195759** [comment]
我定位到原因了，目前已经可以成功完成infer了：
![image](https://user-images.githubusercontent.com/16025309/172988883-692049f2-11b8-4a82-bbb2-a5c83ad0ad22.png)

主要的原因是这个模型的实现。在 tools/uilts.py:769 行的 tensor 代码添加一个 .cpu() 即可，否则默认这些都创建在 cuda 上，显存就溢出了。
<img width="1156" alt="截屏2022-06-10 12 14 40" src="https://user-images.githubusercontent.com/16025309/172989099-19dd2407-2ba4-444e-a312-345ea2387b83.png">

**Comment by MintonLee** [comment]
非常感谢，我试一试



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年6月10日(周五) 中午12:14
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [PaddlePaddle/Paddle] slowfast_fasterrcnn的推理出现OSError: (External) CUDA error(2), out of memory. (Issue #43308)




 
我定位到原因了，目前已经可以成功完成infer了：
 
 
主要的原因是这个模型的实现。在 tools/uilts.py:769 行的 tensor 代码添加一个 .cpu() 即可，否则默认这些都创建在 cuda 上，显存就溢出了。
