### ISSUE TITLE
使用profiler打印出来的日志很简略，需要如何入手查问题？

### ISSUE THREAD

**Issue by jesiws** [PaddlePaddle/Paddle#43306]
![image](https://user-images.githubusercontent.com/23470771/172526628-a05c8e65-2cc9-4a54-8f4d-765d4e521146.png)
使用profiler打印出来的分析日志如图，因为无法搜索到详细的说明文档导致无法下手进行优化，希望提供一下性能优化的思路或者相关详细的说明文档🙏🏻 谢谢~ 

比如，其中thread0::GpuMemcpySync:GPU->CPU占了很大一块时间，想优化这里但是没法定位到触发GpuMemcpySync的具体op，代码中显式使用.numpy()的部分全部去掉后GpuMemcpySync:GPU->CPU也会触发2000多次，如果这块是调用的一些函数内部调用了.numpy()，那么要如何去定位到具体的位置呢？

**Comment by TCChenlong** [comment]
可以参考一下这篇文档：[模型性能分析-使用文档-PaddlePaddle深度学习平台](https://www.paddlepaddle.org.cn/documentation/docs/zh/guides/performance_improving/profiling_model.html)
