### ISSUE TITLE
paddlespeech asr 使用问题

### ISSUE THREAD

**Issue by wangxinrugithub** [PaddlePaddle/Paddle#43300]
### 请提出你的问题 Please ask your question

![image](https://user-images.githubusercontent.com/72679116/172511191-656514e3-0cc9-4de5-9a65-4ebf3eeed86d.png)
无法输出结果

**Comment by 2742195759** [comment]
你这边的信息有限，但是我看似乎都没有运行Paddle呀。你可以在关键路劲print打印一下，看下程序是否进入了你的主要逻辑里面。还有这个paddlespeech是哪个程序。paddlespeech.py 吗？
