### ISSUE TITLE
打开training生成的log文件时出现乱码，可以用visualdl可视化查看，但是请问如何通过log文件查看自己训练过程时的信息：如batch_size；optimizer；iters等等

### ISSUE THREAD

**Issue by ly27253** [PaddlePaddle/Paddle#43303]
### 请提出你的问题 Please ask your question

您打开的文件含有无效字符。如果您强行编辑该文件，可能会造成文件损坏。 您可以另选一种字符编码并重试。 

\00\00\00\00\00\00\00

meta_data_tag\F6񾆔0R\00\00\00\00\00\00\00\00


Train/loss\A7\80\BF\86\940%(\F0\F2@\00\00\00\00\00\00\00

Train/loss_0\A7\80\BF\86\940%
................

**Comment by 2742195759** [comment]
同学你好，请问你的log是自己打印的还是visualdl输出的。
