### ISSUE TITLE
go api demo can't work

### ISSUE THREAD

**Issue by lcy1317** [PaddlePaddle/Paddle#43342]
### 请提出你的问题 Please ask your question

I download go inference demo but it can't work because of the error below:

github.com/paddlepaddle/paddle/paddle/fluid/inference/goapi
/root/go/pkg/mod/github.com/paddlepaddle/paddle/paddle/fluid/inference/goapi@v0.0.0-20220608131618-cab0f2f503b0/config.go:504:2: could not determine kind of name for C.PD_ConfigEnableVarseqlen

I don't know where to get C.PD_ConfigEnableVarseqlen.

**Comment by zhenzi0322** [comment]
> ### 请提出你的问题 Please ask your question
> I download go inference demo but it can't work because of the error below:
> 
> github.com/paddlepaddle/paddle/paddle/fluid/inference/goapi /root/go/pkg/mod/github.com/paddlepaddle/paddle/paddle/fluid/inference/goapi@v0.0.0-20220608131618-cab0f2f503b0/config.go:504:2: could not determine kind of name for C.PD_ConfigEnableVarseqlen
> 
> I don't know where to get C.PD_ConfigEnableVarseqlen.

我在单测时也是这个问题，请问您是如何解决的呢？
