### ISSUE TITLE
paddle.model.fit log_freq 参数不起作用

### ISSUE THREAD

**Issue by Li-4** [PaddlePaddle/Paddle#43343]
我的理解是如果设5的话，会每5个epoch输出一次log，但是实际使用的时候每个epoch还是会输出log。

> https://github.com/PaddlePaddle/Paddle/blob/release/2.3/python/paddle/hapi/model.py#L1784-L1784

`cbks​.​on_end​(​'train'​, ​logs​)`

怀疑是因为这个，在每次`on_train_end`时候，都会输出log

**Comment by Li-4** [comment]
```
if epoch % log_freq == 0:
    cbks.on_end('train', logs)
```

应该这么改吗？我没有做测试，如果我的理解有错误的话，很抱歉

**Comment by SigureMo** [comment]
> https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/Model_cn.html#fit-train-data-none-eval-data-none-batch-size-1-epochs-1-eval-freq-1-log-freq-10-save-dir-none-save-freq-1-verbose-2-drop-last-false-shuffle-true-num-workers-0-callbacks-none

> 我的理解是如果设5的话，会每5个epoch输出一次log，但是实际使用的时候每个epoch还是会输出log。

根据文档，是 5 个 step，而不是 5 个 epoch……别根据理解啊，看文档啊

**Comment by Li-4** [comment]
我的错，对不起

**Comment by Li-4** [comment]
> https://github.com/PaddlePaddle/Paddle/blob/release/2.3/python/paddle/hapi/model.py#L1593-L1594

文档的默认值是1，实际上是10吗？

**Comment by SigureMo** [comment]
> 文档的默认值是1，实际上是10吗？

emmm，那倒确实是文档的问题

**Comment by Ligoml** [comment]
感谢指出，我们会及时修改API文档中的描述错误，也非常欢迎二位直接提pr做修改 @Li-4 @SigureMo
