### ISSUE TITLE
The quantized model reports an error when inference with MKLDNN

### ISSUE THREAD

**Issue by yeliang2258** [PaddlePaddle/Paddle#43364]
### bug描述 Describe the Bug

When I use Paddle2.3 or develop version to deploy the quantized model on the CPU, I get an error, the error is as follows：
![image](https://user-images.githubusercontent.com/30516196/172802333-2a9c48f9-9841-4bc1-92d5-ef22230d7af6.png)

Steps to reproduce:
```
# 1. Use save_quant_model.py to convert quantized model
python save_quant_model.py --quant_model_path ad_quant_1.045e-05_bulk/ --int8_model_save_path saved_model
# 2. Use MKLDNN to inference
python test.py
```

My model and test script are here:
[modelAscript.tar.gz](https://github.com/PaddlePaddle/Paddle/files/8868548/modelAscript.tar.gz)

**Comment by wozna** [comment]
For now, we have found that `elementwise_mul` in this model is not quantized correctly. Hot fix is to save model without quantization of elementwise_mul. To do this please use save_quant_model.py with argument `--ops_to_quantize="concat,fc"`. 
We will continue to work to fix the issue.

**Comment by wozna** [comment]
Together with @zuzg, we fixed elementise_mul quantization in this PR https://github.com/PaddlePaddle/Paddle/pull/43693 and it should fix the error.
@yeliang2258  Please check on your side if the model is working correctly.

**Comment by lidanqing-vv** [comment]
```
I0621 05:02:52.482789 158389 analysis_predictor.cc:1161] ======= optimize end =======
I0621 05:02:52.483402 158389 naive_executor.cc:104] ---  skip [feed], feed -> concat_0.tmp_0
I0621 05:02:52.483995 158389 naive_executor.cc:104] ---  skip [save_infer_model/scale_0], fetch -> fetch
I0621 05:02:52.501178 158389 device_context.cc:805] oneDNN v2.6.0
time cost: 0.21811223030090332 s
[[0.32479262]]
```
@yeliang2258  I just merge that PR casue I have tested this issue with that PR and it is fixed.
I need to merge the PR as soon as possible because I need to cherry-pick for 2.3.1

**Comment by yeliang2258** [comment]
![image](https://user-images.githubusercontent.com/30516196/174730341-c8c7c284-4958-45b4-805d-22c857c7a740.png)
I verified here, it is indeed fixed
