### ISSUE TITLE
Strided_slice 的异常行为

### ISSUE THREAD

**Issue by Kevin-XiongC** [PaddlePaddle/Paddle#43375]
### bug描述 Describe the Bug

<img width="517" alt="image" src="https://user-images.githubusercontent.com/22584786/172830896-d27c0db9-5363-499f-9f30-275b82eb7e8b.png">

上图结果由以下script得到，其中出现了OoTA值0，而且对于shape为(2,)的tensor可以传入大于2的start end，请问各个参数的合理范围是多少？或者是在三者有-1时，Strided_slice行为是怎样？

``` python
print(paddle.strided_slice(paddle.to_tensor([28,29]),axes=[0],starts=[-1],ends=[9],strides=[1]))
print(paddle.strided_slice(paddle.to_tensor([28,29]),axes=[0],starts=[-1],ends=[-9],strides=[-1]))
print(paddle.strided_slice(paddle.to_tensor([28,29]),axes=[0],starts=[321312],ends=[-1],strides=[-1]))

```
### 其他补充信息 Additional Supplementary Information

paddle 2.2 or 2.3 
mac x86
python3.7

**Comment by zyfncg** [comment]
你好，感谢反馈！经过排查[stride_slice](https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/strided_slice_cn.html#strided-slice)的参数为负数时确实存在一些问题。starts和ends参数的合理范围应该在[-shape_size, shape_size]，在这个范围内设置参数值应该是没有问题的，这也是我们推荐的用法。但为了写起来更简单stride_slice也允许输入的参数超过这个范围：如果start和end的值大于对应维度的size，在处理时会将其设置为维度的size值；如果start和end的值小于0，会先加上shape_size，如果加完之后仍小于0则按0处理（stride小于0并且end为-1时除外，此时由于要从后往前选择到第0个元素，所以end需要为-1）。
所以脚本中的第一和第三个示例等价于：
```
print(paddle.strided_slice(paddle.to_tensor([28,29]),axes=[0],starts=[1],ends=[2],strides=[1]))
print(paddle.strided_slice(paddle.to_tensor([28,29]),axes=[0],starts=[1],ends=[-1],strides=[-1]))
```
第二个示例由于end值-9+2=-7仍小于0，所以需要按0处理，因此正确的结果应该是等价于：
```
print(paddle.strided_slice(paddle.to_tensor([28,29]),axes=[0],starts=[1],ends=[0],strides=[-1]))
#Tensor(shape=[1], dtype=int64, place=Place(gpu:0), stop_gradient=True,
#            [29])
```

**Comment by Kevin-XiongC** [comment]
strided_slice和set_value 这两个我理解索引逻辑应该一样的op，貌似实际处理时也不一样？如下图所示，同一个slice参数，strided_slice读了三个entry，但是set_value改写了四个entry，按照『如果start和end的值小于0，会先加上shape_size』这个逻辑ends+4会变成0，因为是左闭右开区间[3,0)，所以被修改的应该只有3,2,1三个索引？

看起来set_value的逻辑像是在stride小于0时和end<0时，就是取到0的闭区间？
![image](https://user-images.githubusercontent.com/22584786/174289540-65aead86-9901-41fd-a1a9-887bc0b8a250.png)
