### ISSUE TITLE
昆仑K100芯片梯度回传报错

### ISSUE THREAD

**Issue by xinsidao** [PaddlePaddle/Paddle#43399]
### bug描述 Describe the Bug

问题：在cpu、gpu中运行正常，在昆仑K100中运行异常
简要代码(依赖paddleclas)
import paddle
from ppcls.arch.backbone.model_zoo import inception_v4

place = paddle.device.XPUPlace(0)
paddle.device.set_device("xpu:0")
image = imread(image_path, pilmode='RGB')
x = ResizeImage(resize_short=320)(image)
x = CropImage(size=299)(x)
x = NormalizeImage(scale=1.0 / 255.0, mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225], order='')(x)
x = ToCHWImage()(x)
batch_data.append(x)
tensor_img = paddle.to_tensor(batch_data)
model = inception_v4.InceptionV4()
predict = self.model(tensor_img)
criterion=paddle.nn.functional.nll_loss
loss = criterion(predict, tensor_label)
loss.backward(retain_graph=True)
异常：
  File "attack_interface.py", line 177, in attack
    loss.backward(retain_graph=True)
  File "/usr/local/lib/python3.7/dist-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
    return wrapped_func(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/framework.py", line 229, in __impl__
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/varbase_patch_methods.py", line 246, in backward
    framework._dygraph_tracer())
RuntimeError:

--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
0   paddle::imperative::BasicEngine::Execute()
1   paddle::imperative::PreparedOp::Run(paddle::imperative::NameVariableWrapperMap const&, paddle::imperative::NameVariableWrapperMap const&, paddle::framework::AttributeMap const&, paddle::framework::AttributeMap const&)
2   float const* paddle::framework::Tensor::data<float>() const
3   paddle::framework::Tensor::check_memory_size() const
4   paddle::platform::EnforceNotMet::EnforceNotMet(paddle::platform::ErrorSummary const&, char const*, int)
5   paddle::platform::GetCurrentTraceBackString[abi:cxx11](bool)

----------------------
Error Message Summary:
----------------------
PreconditionNotMetError: Tensor holds no memory. Call Tensor::mutable_data firstly.
  [Hint: holder_ should not be null.] (at /home/bml/Paddle/paddle/fluid/framework/tensor.cc:31)

### 其他补充信息 Additional Supplementary Information

昆仑K100,ubuntu18.04,paddle2.2,paddleclas2.4

**Comment by adaxiadaxi** [comment]
您好， 我们在k100上做过验证的clas模型是：vgg、resnet，mb3、hrnet。目前k100属于比较旧的产品型号，我们在昆仑2代r200上验证过inceptionv4模型，看看咱们是否更换模型或者是更换款型昆仑卡。如有需要可以微信沟通：zxy8811666 @xinsidao

**Comment by adaxiadaxi** [comment]
这个是k100上验证过支持的模型列表：https://www.paddlepaddle.org.cn/documentation/docs/zh/2.2/guides/09_hardware_support/xpu_docs/paddle_2.0_xpu_cn.html
