### ISSUE TITLE
WarpCTC Integration

### ISSUE THREAD

**Issue by reyoung** [PaddlePaddle/Paddle#434]
We plan to integrate [WarpCTC](https://github.com/baidu-research/warp-ctc) for potential ASR applications.

**Comment by Xreki** [comment]
# 编译warp-ctc
```bash
cd ~/
git clone https://github.com/baidu-research/warp-ctc
cd warp-ctc
mkdir build
cd build
cmake CMAKE_INSTALL_PREFIX=/home/xxx/warpctc ..
make
make install
```
默认生成`libwarp-ctc.so`，需要设置`LD_LIBRARY_PATH=/home/xxx/warpctc:$LD_LIBRARY_PATH`

# PaddlePaddle中调用warp-ctc
- 以layer的形式，作为一个plugin集成到PaddlePaddle中。
- 编译配置方式
    - cmake命令行设置`WARPCTC_DIR`
    - 设置环境变量`WARPCTC_ROOT`
    - cmake查找是否存在warpctc库，存在才编译plugin/warpctc下的源码
- 用户接口类似于ctc_layer
```python
warp_ctc_layer(input,
               label,
               name=None,
               size=None,
               norm_by_times=False,
               layer_attr=None
               )
```

# 可能存在的问题
- layer接口warp_ctc_layer是否统一配置在`python/paddle/trainer_config_helpers/layers.py`以及`config_parser.py`中：
   - 若是，怎么在没有warp-ctc库时将其disable掉；
   - 若不是，该怎么配置。
- 单测方式：
   - 当前PaddlePaddle中ctc_layer设置的blank为`num_classes-1`，warp-ctc中设置的blank为`0`。
   - warp-ctc中自带了一个softmax操作，warp-ctc的前向相当于paddle的softmax + ctc，layerGrad检查不通过。

# MXNet
- 集成方案：https://github.com/dmlc/mxnet/tree/master/plugin/warpctc
- 使用文档：https://github.com/dmlc/mxnet/tree/master/example/warpctc

**Comment by reyoung** [comment]
> layer接口warp_ctc_layer是否统一配置在python/paddle/trainer_config_helpers/layers.py以及config_parser.py中

我觉得应该集成在一起。如果没有enable掉的话，paddle那边也会报错的。
至于so的加载，我比较推荐运行时加载这个so，而不是在编译器把符号依赖编译进去。否则的话，Paddle就会多了一个WITH_CTC版本和WITHOUT_CTC版本。这会让我们的版本变得比较混乱。

我看CTC只有三个函数嘛，那么我们可以在C++这边实现这三个函数的stub，比如

```cpp
extern "C" int get_warpctc_version() { return -1; }
```

而在Paddle真正使用这个ctc的时候，使用LD_PRELOAD来率先加载wrap-ctc的so即可。

**Comment by reyoung** [comment]
另外，wrap-ctc的.h我们可以使用submodule引入到paddle中。

**Comment by Xreki** [comment]
> 当前PaddlePaddle中ctc_layer设置的blank为num_classes-1，warp-ctc中设置的blank为0。

更新一下，当前的warp-ctc版本的blank可以手动配置。

**Comment by Xreki** [comment]
根据@reyoung 的建议，修订方案如下。

## PaddlePaddle中调用warp-ctc
- 作为一个layer（WarpCTCLayer）集成到PaddlePaddle中
    - 将warp-ctc这个repo以submodule引入到paddle中
    - 库中动态装载`cpu+gpu`版或`cpu-only`版`libwarpctc.so`
- layer接口类似于ctc_layer，统一配置在`python/paddle/trainer_config_helpers/layers.py`以及`config_parser.py`中，添加blank的配置接口
```python
warp_ctc_layer(input,
               label,
               name=None,
               size=None,
               blank=-1,
               norm_by_times=False,
               layer_attr=None
               )
``` 
- 单测方式
   > 当前PaddlePaddle中ctc_layer设置的blank为`num_classes-1`。
   warp-ctc中自带了一个softmax操作，warp-ctc的前向相当于paddle的`softmax + ctc`，layerGrad检查不通过。
   
   - 考虑将warp_ctc_layer的blank设置成`num_classes-1`，计算结果和ctc_layer进行比对
