### ISSUE TITLE
Define level=0 for LoDTensor

### ISSUE THREAD

**Issue by wangkuiyi** [PaddlePaddle/Paddle#4340]
`level=0` means the LoDTensor is nothing with instances nor sequences; instead, it means the LoDTensor is a single piece, e.g., a parameter.

**Comment by wangkuiyi** [comment]
I am going to update the design doc https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/framework/lod_tensor.md

**Comment by Superjom** [comment]
RNNOp will segment the first level of LoDTensor, so should make sure that the first level should be the info of top level sequences.

**Comment by luotao1** [comment]
@Superjom What is the "top level"? lod[0] stores the word-level, and lod[1] stores the sequence-level?
