### ISSUE TITLE
FatalError: `Segmentation fault` is detected by the operating system.

### ISSUE THREAD

**Issue by ZTurboX** [PaddlePaddle/Paddle#43411]
### bug描述 Describe the Bug

paddlepaddle==2.2.2

--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
No stack trace in paddle, may be caused by external reasons.

----------------------
Error Message Summary:
----------------------
FatalError: `Segmentation fault` is detected by the operating system.
  [TimeInfo: *** Aborted at 1654855735 (unix time) try "date -d @1654855735" if you are using GNU date ***]
  [SignalInfo: *** SIGSEGV (@0x7) received by PID 3247505 (TID 0x7f73c7e65340) from PID 7 ***]

**Comment by limin2021** [comment]
你好，segment fault通常是内存相关问题。可否贴一下您的代码，并告知运行方法，方便我们复现找到问题所在？

**Comment by renoyuan** [comment]
我也遇到了，运行就会报错，但是是偶发的，有时候会报错有时候不会

**Comment by fmscole** [comment]
运行paddle.utils.run_check()就是这个错误了
wsl2+cuda11.7

**Comment by Giszy** [comment]
@fmscole 
问题分析：
paddle.utils.run_check()运行的时候会搜索libcuda.so，但在WSL2下，该文件是Windows的路径"C:\Windows\System32\lxss\lib\libcuda.so"。所以，出现FatalError: Segmentation fault is detected by the operating system，就是因为在WSL2的Ubuntu系统中缺少libcuda.so所致。

解决方案：将libcuda.so拷贝到/usr/local/cuda/lib64/下即可。测试通过。
