### ISSUE TITLE
paddle c++ make error

### ISSUE THREAD

**Issue by zhangguotai** [PaddlePaddle/Paddle#43410]
### bug描述 Describe the Bug

In file included from /home/zhangguotai/code/Paddle/paddle/fluid/operators/math/softmax.cc:17:
/home/zhangguotai/code/Paddle/paddle/fluid/operators/math/softmax_impl.h: In member function ‘void paddle::operators::math::SoftmaxGradFunctor<DeviceContext, T, typename std::enable_if<std::is_same<DeviceContext, paddle::platform::CPUDeviceContext>::value>::type>::operator()(const DeviceContext&, int, const Tensor*, const Tensor*, paddle::framework::Tensor*) [with DeviceContext = paddle::platform::CPUDeviceContext; T = float]’:
/home/zhangguotai/code/Paddle/paddle/fluid/operators/math/softmax_impl.h:393:15: error: ‘*((void*)& out_dims +8)’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
  393 |     const int num_classes = out_dims[kClassDim];
      |               ^~~~~~~~~~~
/home/zhangguotai/code/Paddle/paddle/fluid/operators/math/softmax_impl.h:394:15: error: ‘out_dims’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
  394 |     const int batch_size = out_dims[kBatchDim];
      |               ^~~~~~~~~~
/home/zhangguotai/code/Paddle/paddle/fluid/operators/math/softmax_impl.h: In member function ‘void paddle::operators::math::SoftmaxGradFunctor<DeviceContext, T, typename std::enable_if<std::is_same<DeviceContext, paddle::platform::CPUDeviceContext>::value>::type>::operator()(const DeviceContext&, int, const Tensor*, const Tensor*, paddle::framework::Tensor*) [with DeviceContext = paddle::platform::CPUDeviceContext; T = double]’:
/home/zhangguotai/code/Paddle/paddle/fluid/operators/math/softmax_impl.h:393:15: error: ‘*((void*)& out_dims +8)’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
  393 |     const int num_classes = out_dims[kClassDim];
      |               ^~~~~~~~~~~
/home/zhangguotai/code/Paddle/paddle/fluid/operators/math/softmax_impl.h:394:15: error: ‘out_dims’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
  394 |     const int batch_size = out_dims[kBatchDim];
      |               ^~~~~~~~~~
/home/zhangguotai/code/Paddle/paddle/fluid/operators/math/softmax_impl.h: In member function ‘void paddle::operators::math::SoftmaxFunctor<DeviceContext, float, true, typename std::enable_if<std::is_same<DeviceContext, paddle::platform::CPUDeviceContext>::value>::type>::operator()(const DeviceContext&, int, const Tensor*, paddle::framework::Tensor*) [with DeviceContext = paddle::platform::CPUDeviceContext]’:
/home/zhangguotai/code/Paddle/paddle/fluid/operators/math/softmax_impl.h:273:16: error: ‘*((void*)& in_dims +8)’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
  272 |         jit::KernelFuncs<jit::SoftmaxTuple<float>, platform::CPUPlace>::Cache()
      |         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  273 |             .At(in_dims[kClassDim]);
      |             ~~~^~~~~~~~~~~~~~~~~~~~
/home/zhangguotai/code/Paddle/paddle/fluid/operators/math/softmax_impl.h:274:20: error: ‘in_dims’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
  274 |     compute_softmax(in_data, out_data, in_dims[kClassDim], in_dims[kBatchDim],
      |     ~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  275 |                     in_dims[kClassDim] / axis_dim);
      |                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cc1plus: all warnings being treated as errors
make[2]: *** [paddle/fluid/operators/math/CMakeFiles/softmax.dir/build.make:76: paddle/fluid/operators/math/CMakeFiles/softmax.dir/softmax.cc.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:210812: paddle/fluid/operators/math/CMakeFiles/softmax.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....

**Comment by pmajchrzak** [comment]
Raised that bug a few days ago here:
https://github.com/PaddlePaddle/Paddle/issues/43156

**Comment by limin2021** [comment]
你好，请问你的gcc版本是什么？如果是ubuntu20版本，或者gcc版本太高，可能有些警告会当成错误导致编译出错。
