### ISSUE TITLE
pphuman可以实时预测吗

### ISSUE THREAD

**Issue by cherishat** [PaddlePaddle/Paddle#43418]
### 请提出你的问题 Please ask your question

请问STGCN是支持实时预测的吗，PPHUMAN里用到了STGCN，也是可以实时预测的吗。是否有部署或者文档呢

**Comment by zoooo0820** [comment]
@cherishat 
你好，关于PPhuman中STGCN的部分，请参考[文档](https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.4/deploy/pphuman/docs/action.md)。 关于速度，因为与视频中的人数有关，具体情况可参考文档中我们在nvidia T4设备上测试的数据。总体而言，STGCN在PPHuman整体中的时间占比并不高。

**Comment by cherishat** [comment]
是否可以直接用在实时的监控视频上，实时显示动作类别呢。 还是说只能输入一段视频，属于视频分类过程呢，看到描述是根据50帧内的变化判断动作，那下一个50帧是继续判断吗，stgcn的输入帧数是有限制的，源码是设置了300帧，这样的话pphuman是怎样完成帧数的保存和清空的呢？谢谢解答

**Comment by zoooo0820** [comment]
- PPHuman基于关键点的行为识别逻辑大致是：1.对于视频中的每一帧，检测跟踪行人目标并获取对应的关键点坐标；2.基于跟踪的id将关键点坐标累计成该id对应人物的关键点时序序列；3.使用STGCN模型预测这个时序序列对应的动作类别。 所以这里的50帧指的是每个id的人物会累计长度50帧的关键点序列来判断这50帧中该人物的动作类型。可以理解成每个id每隔50帧会有一个动作的结果。
- 关于在实时监控视频的使用，目前PPHuman已经放出的代码是使用视频文件进行预测的，速度上我们在nvidia T4, FP16预测下是可以实时的，当然具体情况也由您的场景和设备决定。后续我们也在逐步考虑增加对视频流的支持。
