### ISSUE TITLE
碰到报错：RuntimeError: (PermissionDenied) Cannot set target var auto_2227_@GRAD twice

### ISSUE THREAD

**Issue by skywalk163** [PaddlePaddle/Paddle#43417]
### 请提出你的问题 Please ask your question

在复现PaddleMD（论文原作TorchMD）项目时，在运行测试程序时，碰到报错：
```python
test_replicas (__main__._TestPaddleMD) ... ERROR

======================================================================
ERROR: test_replicas (__main__._TestPaddleMD)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests/test_paddlemd_water.py", line 518, in test_replicas
    explicit_forces=False,
  File "/code/6paper/PaddleMD/paddlemd/forces.py", line 430, in compute
    [enesum], [pos], only_inputs=True, retain_graph=False
  File "</opt/conda/lib/python3.6/site-packages/decorator.py:decorator-gen-49>", line 2, in grad
  File "/opt/conda/lib/python3.6/site-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
    return wrapped_func(*args, **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/paddle/fluid/framework.py", line 434, in __impl__
    return func(*args, **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/paddle/fluid/dygraph/base.py", line 663, in grad
    retain_graph, allow_unused, only_inputs)
RuntimeError: (PermissionDenied) Cannot set target var auto_2227_@GRAD twice
  [Hint: Expected ready_var.var == nullptr, but received ready_var.var != nullptr.] (at /paddle/paddle/fluid/imperative/partial_grad_engine.cc:508)
```
相关代码：
```python
if not explicit_forces:
            enesum = paddle.zeros([1], dtype=pos.dtype)
            for i in range(nsystems):
                for ene in pot[i]:
                    if not pot[i][ene].stop_gradient:
                        enesum += pot[i][ene]
            forces[:] = -paddle.grad(
                [enesum], [pos], only_inputs=True, retain_graph=False
            )[0]
```
报错的信息，意思是不能两次设置目标变量auto_2227_@GRAD ？ 
我的理解，paddle.grad这里，就送入一个输入，一个输出，不应该报错啊。 希望能提示、帮助一下，指导一下问题的突破口。

**Comment by JiabinYang** [comment]
应该不是这个问题 请问有最小的复现环境嘛 我们来看看

**Comment by skywalk163** [comment]
项目已经公开：https://aistudio.baidu.com/aistudio/projectdetail/3863645?contributionType=1

进入项目后，执行文件路径目录为：INFINITY/examples/PaddleMD/3集成测试.ipynb

到“专门处理集成测试中失败的例子” 这个cell，下面的“!python tests/test_paddlemd_water.py” 就能复现这个报错。 报错在forces.py文件的438行。

也可以下载这个项目：https://github.com/skywalk163/INFINITY
还是使用这个文件测试：“INFINITY/examples/PaddleMD/3集成测试.ipynb” 。

**Comment by veyron95** [comment]
@skywalk163 我 Fork 你所提供的项目，在 INFINITY/examples/PaddleMD/3集成测试.ipynb 内，到“专门处理集成测试中失败的例子” 这个cell，执行 !python tests/test_paddlemd_water.py 会报如下错误：`python: can't open file 'tests/test_paddlemd_water.py': [Errno 2] No such file or directory`，经检查，tests 文件夹下并无该 test_paddlemd_water.py 文件，请检查一下所公开的项目并提供可复现问题的最小实现。

**Comment by skywalk163** [comment]
现在更新了版本了，那个文件test_paddlemd_water.py加进去了。 

另外在AIStudio环境下，所需的几个库安装可能有点坎坷。可以尝试使用conda或者源码安装。

**Comment by veyron95** [comment]
@skywalk163 好的，我们看看能否复现问题

**Comment by skywalk163** [comment]
复现出问题了吗？ 有新的思路吗？

**Comment by veyron95** [comment]
@skywalk163 已经复现了，还在跟踪。目前进展是定位在 forces.py 里面 `if self.require_distances and len(self.ava_idx):` 分支下` if v == "lj":` 子分支内的计算过程有些问题，在这个分支内调用 paddle.grad([pot[i][v]]],[pos], only_inputs=True, retain_graph=False)[0] 就能复现。这个情况比较特殊，还在分析。

**Comment by veyron95** [comment]
@skywalk163 目前 develop 分支已经修复该问题，可以下载安装最新的 develop(Nightly build) 版本进行使用https://www.paddlepaddle.org.cn/install/quick?docurl=/documentation/docs/zh/develop/install/pip/linux-pip.html

**Comment by skywalk163** [comment]
ok！
