### ISSUE TITLE
单机多卡训练，按照官网文档操作了，但是数据没有分片【即平均分配到每个GPU】（？？）

### ISSUE THREAD

**Issue by dowdyboy** [PaddlePaddle/Paddle#43426]
### 请提出你的问题 Please ask your question

我根据官方文档操作，用两卡训练mnist数据集，batch设置为100，也就是在单卡训练一个epoch需要600次迭代；
但是用两卡训练，进度条也显示需要600次迭代（我用Pytorch的单机多卡，这个就会变成300，也就是数据均分到了两个GPU）；
并且我每一次迭代会记录loss，在一个epoch结束后，用all_gather方法，收集到了1200个值，也就是说，两个GPU分别完整了进行了一个epoch的数据，而没有将数据分成2份；

这个是个BUG吗？还是说有其他分割数据到每个GPU的API？

**Comment by lvjian0706** [comment]
您好，请问具体是怎么操作的呢？

**Comment by dowdyboy** [comment]
> 您好，请问具体是怎么操作的呢？

这个我后面查到，需要用DistributedBatchSampler来加载数据，但是这个官网文档没有提及

**Comment by Ligoml** [comment]
可以贴一下文档的链接和截图吗？我们会联系负责人及时更新文档，感谢~

**Comment by dowdyboy** [comment]
> 

https://www.paddlepaddle.org.cn/tutorials/projectdetail/3618852

![图片](https://user-images.githubusercontent.com/39474100/173722571-f93155a2-5c3e-4654-8c5f-7394067ad63c.png)

**Comment by XYZ-916** [comment]
https://www.paddlepaddle.org.cn/tutorials/projectdetail/3618852 中是通过手动方式构造训练数据的，没有用封装好的Dataset和DataLoader，如果用多卡启动训练，因为没有进行数据划分，会在每个卡上进行一次全量数据的训练，打印的log也是我们自己定义的。你用多卡启动训练时会发展生成对应卡数的log文件。你可以基于Paddle Dataset和DataLoader API实验一下，看看效果。

**Comment by XYZ-916** [comment]
> ### 请提出你的问题 Please ask your question
> 我根据官方文档操作，用两卡训练mnist数据集，batch设置为100，也就是在单卡训练一个epoch需要600次迭代； 但是用两卡训练，进度条也显示需要600次迭代（我用Pytorch的单机多卡，这个就会变成300，也就是数据均分到了两个GPU）； 并且我每一次迭代会记录loss，在一个epoch结束后，用all_gather方法，收集到了1200个值，也就是说，两个GPU分别完整了进行了一个epoch的数据，而没有将数据分成2份；
> 
> 这个是个BUG吗？还是说有其他分割数据到每个GPU的API？

非常感谢您能针对分布式训练问题提issue，我们会及时更新文档，让您和后续学者学习飞桨框架更轻松。
