### ISSUE TITLE
请问官方是想一直坚守gcc8和centos7吗

### ISSUE THREAD

**Issue by FlyInWind1** [PaddlePaddle/Paddle#43422]
### 请提出你的问题 Please ask your question

对比其他拥有10k以上星的开源项目，这绝对是逆天行为

**Comment by zoooo0820** [comment]
您好，关于更多环境的支持，我们内部会尽快安排评估，未来有计划尽快回复。也想了解下您这边期望支持的环境和系统情况是什么样的呢？

**Comment by FlyInWind1** [comment]
tensorflow 和 pytorch 是可以直接进入 archlinux 这种所有软件包都过于新的官方仓库的。我希望飞桨也可以做到

**Comment by FlyInWind1** [comment]
可以进入主流发行版的官方仓库，我想这对于扩大用户群体，降低入门门槛有着巨大的好处

**Comment by zoooo0820** [comment]
感谢建议，我们会尽快反馈这个问题并安排相关评估。

**Comment by pangyoki** [comment]
> tensorflow 和 pytorch 是可以直接进入 archlinux 这种所有软件包都过于新的官方仓库的。我希望飞桨也可以做到

你好，请问这里tf和pytorch进入archlinux仓库是什么形式？有链接吗？

**Comment by FlyInWind1** [comment]
> > tensorflow 和 pytorch 是可以直接进入 archlinux 这种所有软件包都过于新的官方仓库的。我希望飞桨也可以做到
> 
> 你好，请问这里tf和pytorch进入archlinux仓库是什么形式？有链接吗？

在 archlinux 上输入命令 sudo pacman -S python-tensorflow-opt-cuda ，回车后，tensorflow，以及他的依赖 python3，cuda，cudnn 等都会直接安装，这是一键完成的。而且由于有国内镜像，也不担心网速

**Comment by FlyInWind1** [comment]
当然这是安装在系统级别，不是 pipenv 或者 conda

**Comment by FlyInWind1** [comment]
如果进不了官方仓库影响也不大，我提这个这是想说明，tf和ytorch对于最新版本的操作系统和python版本，适配速度是非常快的

**Comment by pangyoki** [comment]
> 如果进不了官方仓库影响也不大，我提这个这是想说明，tf和ytorch对于最新版本的操作系统和python版本，适配速度是非常快的

了解了，感谢反馈。

**Comment by pangyoki** [comment]
你好，试了下tf和pytorch在高版本gcc下安装后使用没问题，paddle会有glibc版本太高导致报错的问题，这个是已知问题在分析中，谢谢。

**Comment by hubutui** [comment]
> tensorflow 和 pytorch 是可以直接进入 archlinux 这种所有软件包都过于新的官方仓库的。我希望飞桨也可以做到

那也不是直接就能进去的，打包的人还是自己打了 patch 的，可以看 https://github.com/archlinux/svntogit-community/tree/packages/python-pytorch/trunk 和 https://github.com/archlinux/svntogit-community/tree/packages/tensorflow/trunk.
不过，能够主动与编译器版本，cuda等保持同步更新，的确是很不错的，也很不容易．
