### ISSUE TITLE
c++版本推理开启mkldnn加速报错could not execute a primitive

### ISSUE THREAD

**Issue by onair1314** [PaddlePaddle/Paddle#43425]
使用环境：
paddlepaddle 2.3.0
paddleClas 2.4.0
采用镜像为paddle提供的官方镜像：docker pull registry.baidubce.com/paddlepaddle/paddle:latest-dev
采用paddleClas的c++版本推理，采用的模型为ResNet50导出的inference model，配置文件inference_cls.yaml中默认enable_mkldnn: True，即默认开启mkldnn加速
单进程依次对一万张图片进行图片分类，每次运行若干张图片后（每次报错时的图片均不相同）均会报错：
terminate called after throwing an instance of 'dnnl::error'
what(): could not execute a primitive
通过查看源码，认为该报错来源为：https://oneapi-src.github.io/oneDNN/v2/getting_started_cpp.html

同时查看paddle的issue，有同样的报错：https://github.com/PaddlePaddle/Paddle/issues/34492

因此尝试设置enable_mkldnn: False，测试发现不再有报错
因此认为该报错是由于mkldnn引起，但无法确定是由于paddleClas的代码导致还是由于paddle代码未修复成功导致，亦或由于paddle的mkldnn加速不支持ResNet50导致
恳请各位大神协助解决 @baoachun  @will-jl944 @FlyingQianMM

**Comment by jiangjiajun** [comment]
你这个问题是，Resnet50跑多次后出现的问题吗？ 也就是指刚开始跑都可以正常，但到了某一次的时候，会出现上面的报错。

请问下最后报错的时候，这个输入数据的shape(也就是batch)跟前面跑的时候是一样的吗？

**Comment by onair1314** [comment]
> 你这个问题是，Resnet50跑多次后出现的问题吗？ 也就是指刚开始跑都可以正常，但到了某一次的时候，会出现上面的报错。
> 
> 请问下最后报错的时候，这个输入数据的shape(也就是batch)跟前面跑的时候是一样的吗？

只开启一个进程，针对一个文件夹中的1万张图片进行推理，刚开始可以正常跑，运行到某一张图片时，就会报错；
报错后重新执行命令，仍然跑这1万张图片，仍然是刚开始正常出结果，运行到某一张图片报错，但不是上面那一张，报错的图片很随机 @jiangjiajun

**Comment by jiangjiajun** [comment]
这1万张图片，你在跑的时候，设置的batch是多少。 是for循环每次读一张的吗

**Comment by onair1314** [comment]
> 这1万张图片，你在跑的时候，设置的batch是多少。 是for循环每次读一张的吗

batch是1，for循环每次只读一张，这一万张图片的格式都是一致的；
我也测试过同一张图片for循环一万次的情况，开始可以正常推理出结果，但仍然会在运行到某些次的时候报错

**Comment by jiangjiajun** [comment]
能提供下你的测试代码吗，我想我们在测试时需要尽量只保留paddle相关的代码，避免是与其它库的相互作用影响。

**Comment by onair1314** [comment]
https://github.com/PaddlePaddle/PaddleClas/blob/develop/deploy/cpp/src/main.cpp
是使用PaddleClas图片分类的c++ demo进行测试的
PS：已添加您QQ，方便及时沟通 @jiangjiajun

**Comment by jiangjiajun** [comment]
Hi, @onair1314  现在还有问题吗

**Comment by jiangjiajun** [comment]
由于此issue长时间没更新，当前被关闭。

如有问题，可随时重新打开。
