### ISSUE TITLE
paddle.summary 显示错误，漏掉了层

### ISSUE THREAD

**Issue by ouyangshixiong** [PaddlePaddle/Paddle#43421]
### bug描述 Describe the Bug

使用paddle.summary复现算法的时候发现跟Keras显示的不同，经过检查参数量统计正确但是summary显示漏掉了两个 ReLU和MaxPool2D。请看下面的截图：
![image](https://user-images.githubusercontent.com/2086862/173167726-0e7b7345-2532-461b-87ce-5a829e11f4d6.png)
只是轻微的bug，麻烦有空修一下。

### 其他补充信息 Additional Supplementary Information

无

**Comment by SigureMo** [comment]
> 发现跟Keras显示的不同

能提供下 keras 的代码及输出吗？另外 paddle 的最好以**文本形式**提供**完整的代码**

另外，建议提供**最小可复现代码**

**Comment by ouyangshixiong** [comment]
> > 发现跟Keras显示的不同
> 
> 能提供下 keras 的代码及输出吗？另外 paddle 的最好以**文本形式**提供**完整的代码**
> 
> 另外，建议提供**最小可复现代码**

你好，Keras的模型在[这里](https://github.com/microsoft/AutonomousDrivingCookbook/blob/master/DistributedRL/ExploreAlgorithm.ipynb)

我模仿它写的paddle版本的模型完整代码如下：
```
import numpy as np
import paddle
import paddle.nn as nn

class CarBaselineModel(nn.Layer):

    def __init__(self):
        super(CarBaselineModel, self).__init__()
        self.conv1 = nn.Conv2D(
            in_channels=3,
            out_channels=16,
            kernel_size=3,
            stride=1,
            padding="SAME")
        self.conv2 = nn.Conv2D(
            in_channels=16,
            out_channels=32,
            kernel_size=3,
            stride=1,
            padding="SAME")
        self.conv3 = nn.Conv2D(
            in_channels=32,
            out_channels=32,
            kernel_size=3,
            stride=1,
            padding="SAME")
        self.relu = nn.ReLU()
        self.dropout = nn.Dropout(p=0.2)
        self.max_pool = nn.MaxPool2D(kernel_size=2, stride=2)
        self.flatten = nn.Flatten()


        self.linear_1 = nn.Linear(
            in_features=6948,
            out_features=64)
        self.linear_2 = nn.Linear(
            in_features=64, 
            out_features=10)
        self.linear_3 = nn.Linear(
            in_features=10,
            out_features=1)


    def forward(self, img, states):
        img = paddle.divide(img, paddle.to_tensor(255).astype('float32'))
        img_stack = self.max_pool(self.relu(self.conv1(img)))
        img_stack = self.max_pool(self.relu(self.conv2(img_stack)))
        img_stack = self.max_pool(self.relu(self.conv3(img_stack)))
        img_stack = self.flatten(img_stack)
        img_stack = self.dropout(img_stack)

        merged = paddle.concat(x=[img_stack, states], axis=1)

        merged = self.relu(self.linear_1(merged))
        merged = self.dropout(merged)
        merged = self.relu(self.linear_2(merged))
        merged = self.dropout(merged)
        merged = self.relu(self.linear_3(merged))

        return merged
```
麻烦看看，谢谢

**Comment by SigureMo** [comment]
首先，你并没有按照 keras 代码进行复现，keras 代码每个 ReLU、MaxPooling2D 都是一个新的实例，而你共用了同一个实例，因此你说的「Keras显示的不同」问题不存在，问题只是你的复现方式有问题

Paddle 的行为和 TensorFlow keras 的行为一致，一个 Layer（也就是一个实例）只会输出一次，但 keras 里代码明明有多个实例，而你只使用了一个实例，这并不是一个等价的对比

另外既然你不能做最小可复现代码，我这里用最小可复现的方式来详细说明问题吧

首先是 TensorFlow keras 的，这里只以 ReLU 说明问题

```python
import tensorflow as tf


class ModelTf(tf.keras.Model):
    def __init__(self):
        super().__init__()
        self.relu1 = tf.keras.layers.ReLU()
        self.relu2 = tf.keras.layers.ReLU()
        self.linear = tf.keras.layers.Dense(1)

    def call(self, inputs):
        x = self.relu1(inputs)
        x = self.linear(x)
        x = self.relu2(x)
        return x


class ModelTfLayerReuse(tf.keras.Model):
    def __init__(self):
        super().__init__()
        self.relu = tf.keras.layers.ReLU()
        self.linear = tf.keras.layers.Dense(1)

    def call(self, inputs):
        x = self.relu(inputs)
        x = self.linear(x)
        x = self.relu(x)
        return x


print("TensorFlow")
model1 = ModelTf()
model1.build(input_shape=(1, 10))
model1.summary()

print("TensorFlow Layer Reuse")
model2 = ModelTfLayerReuse()
model2.build(input_shape=(1, 10))
model2.summary()
```

输出结果如下：

```text
TensorFlow
Model: "model_tf"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
=================================================================
 re_lu (ReLU)                multiple                  0         
                                                                 
 re_lu_1 (ReLU)              multiple                  0         
                                                                 
 dense (Dense)               multiple                  11        
                                                                 
=================================================================
Total params: 11
Trainable params: 11
Non-trainable params: 0
_________________________________________________________________
TensorFlow Layer Reuse
Model: "model_tf_layer_reuse"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
=================================================================
 re_lu_2 (ReLU)              multiple                  0         
                                                                 
 dense_1 (Dense)             multiple                  11        
                                                                 
=================================================================
Total params: 11
Trainable params: 11
Non-trainable params: 0
_________________________________________________________________

```

可以看到，即便是 TensorFlow keras，同一个实例也不会输出两次

再看看 Paddle

```python
import paddle
from paddle import nn


class ModelPd(nn.Layer):
    def __init__(self):
        super().__init__()
        self.relu1 = nn.ReLU()
        self.relu2 = nn.ReLU()
        self.linear = nn.Linear(10, 1)

    def forward(self, inputs):
        x = self.relu1(inputs)
        x = self.linear(x)
        x = self.relu2(x)
        return x


class ModelPdLayerReuse(nn.Layer):
    def __init__(self):
        super().__init__()
        self.relu = nn.ReLU()
        self.linear = nn.Linear(10, 1)

    def forward(self, inputs):
        x = self.relu(inputs)
        x = self.linear(x)
        x = self.relu(x)
        return x


print("Paddle")
model3 = ModelPd()
paddle.summary(model3, (1, 10))

print("Paddle Layer Reuse")
model4 = ModelPdLayerReuse()
paddle.summary(model4, (1, 10))

```

输出

```text
Paddle
---------------------------------------------------------------------------
 Layer (type)       Input Shape          Output Shape         Param #    
===========================================================================
    ReLU-1           [[1, 10]]             [1, 10]               0       
   Linear-1          [[1, 10]]              [1, 1]              11       
    ReLU-2            [[1, 1]]              [1, 1]               0       
===========================================================================
Total params: 11
Trainable params: 11
Non-trainable params: 0
---------------------------------------------------------------------------
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00
---------------------------------------------------------------------------

Paddle Layer Reuse
---------------------------------------------------------------------------
 Layer (type)       Input Shape          Output Shape         Param #    
===========================================================================
    ReLU-3            [[1, 1]]              [1, 1]               0       
   Linear-2          [[1, 10]]              [1, 1]              11       
===========================================================================
Total params: 11
Trainable params: 11
Non-trainable params: 0
---------------------------------------------------------------------------
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00
---------------------------------------------------------------------------
```

Paddle 也是完全一致的行为

在我看来，你的对比是将 keras 的 model1 和 paddle 的 model4 进行对比，这当然会出现差异……

**Comment by ouyangshixiong** [comment]
> 首先，你并没有按照 keras 代码进行复现，keras 代码每个 ReLU、MaxPooling2D 都是一个新的实例，而你共用了同一个实例，因此你说的「Keras显示的不同」问题不存在，问题只是你的复现方式有问题
> 
> Paddle 的行为和 TensorFlow keras 的行为一致，一个 Layer（也就是一个实例）只会输出一次，但 keras 里代码明明有多个实例，而你只使用了一个实例，这并不是一个等价的对比
> 
> 另外既然你不能做最小可复现代码，我这里用最小可复现的方式来详细说明问题吧
> 
> 首先是 TensorFlow keras 的，这里只以 ReLU 说明问题
> 
> ```python
> import tensorflow as tf
> 
> 
> class ModelTf(tf.keras.Model):
>     def __init__(self):
>         super().__init__()
>         self.relu1 = tf.keras.layers.ReLU()
>         self.relu2 = tf.keras.layers.ReLU()
>         self.linear = tf.keras.layers.Dense(1)
> 
>     def call(self, inputs):
>         x = self.relu1(inputs)
>         x = self.linear(x)
>         x = self.relu2(x)
>         return x
> 
> 
> class ModelTfLayerReuse(tf.keras.Model):
>     def __init__(self):
>         super().__init__()
>         self.relu = tf.keras.layers.ReLU()
>         self.linear = tf.keras.layers.Dense(1)
> 
>     def call(self, inputs):
>         x = self.relu(inputs)
>         x = self.linear(x)
>         x = self.relu(x)
>         return x
> 
> 
> print("TensorFlow")
> model1 = ModelTf()
> model1.build(input_shape=(1, 10))
> model1.summary()
> 
> print("TensorFlow Layer Reuse")
> model2 = ModelTfLayerReuse()
> model2.build(input_shape=(1, 10))
> model2.summary()
> ```
> 
> 输出结果如下：
> 
> ```
> TensorFlow
> Model: "model_tf"
> _________________________________________________________________
>  Layer (type)                Output Shape              Param #   
> =================================================================
>  re_lu (ReLU)                multiple                  0         
>                                                                  
>  re_lu_1 (ReLU)              multiple                  0         
>                                                                  
>  dense (Dense)               multiple                  11        
>                                                                  
> =================================================================
> Total params: 11
> Trainable params: 11
> Non-trainable params: 0
> _________________________________________________________________
> TensorFlow Layer Reuse
> Model: "model_tf_layer_reuse"
> _________________________________________________________________
>  Layer (type)                Output Shape              Param #   
> =================================================================
>  re_lu_2 (ReLU)              multiple                  0         
>                                                                  
>  dense_1 (Dense)             multiple                  11        
>                                                                  
> =================================================================
> Total params: 11
> Trainable params: 11
> Non-trainable params: 0
> _________________________________________________________________
> ```
> 
> 可以看到，即便是 TensorFlow keras，同一个实例也不会输出两次
> 
> 再看看 Paddle
> 
> ```python
> import paddle
> from paddle import nn
> 
> 
> class ModelPd(nn.Layer):
>     def __init__(self):
>         super().__init__()
>         self.relu1 = nn.ReLU()
>         self.relu2 = nn.ReLU()
>         self.linear = nn.Linear(10, 1)
> 
>     def forward(self, inputs):
>         x = self.relu1(inputs)
>         x = self.linear(x)
>         x = self.relu2(x)
>         return x
> 
> 
> class ModelPdLayerReuse(nn.Layer):
>     def __init__(self):
>         super().__init__()
>         self.relu = nn.ReLU()
>         self.linear = nn.Linear(10, 1)
> 
>     def forward(self, inputs):
>         x = self.relu(inputs)
>         x = self.linear(x)
>         x = self.relu(x)
>         return x
> 
> 
> print("Paddle")
> model3 = ModelPd()
> paddle.summary(model3, (1, 10))
> 
> print("Paddle Layer Reuse")
> model4 = ModelPdLayerReuse()
> paddle.summary(model4, (1, 10))
> ```
> 
> 输出
> 
> ```
> Paddle
> ---------------------------------------------------------------------------
>  Layer (type)       Input Shape          Output Shape         Param #    
> ===========================================================================
>     ReLU-1           [[1, 10]]             [1, 10]               0       
>    Linear-1          [[1, 10]]              [1, 1]              11       
>     ReLU-2            [[1, 1]]              [1, 1]               0       
> ===========================================================================
> Total params: 11
> Trainable params: 11
> Non-trainable params: 0
> ---------------------------------------------------------------------------
> Input size (MB): 0.00
> Forward/backward pass size (MB): 0.00
> Params size (MB): 0.00
> Estimated Total Size (MB): 0.00
> ---------------------------------------------------------------------------
> 
> Paddle Layer Reuse
> ---------------------------------------------------------------------------
>  Layer (type)       Input Shape          Output Shape         Param #    
> ===========================================================================
>     ReLU-3            [[1, 1]]              [1, 1]               0       
>    Linear-2          [[1, 10]]              [1, 1]              11       
> ===========================================================================
> Total params: 11
> Trainable params: 11
> Non-trainable params: 0
> ---------------------------------------------------------------------------
> Input size (MB): 0.00
> Forward/backward pass size (MB): 0.00
> Params size (MB): 0.00
> Estimated Total Size (MB): 0.00
> ---------------------------------------------------------------------------
> ```
> 
> Paddle 也是完全一致的行为
> 
> 在我看来，你的对比是将 keras 的 model1 和 paddle 的 model4 进行对比，这当然会出现差异……

非常感谢你的回复。我本地修改代码后重新测试验证，正如你所讲。应该要实例化各个Layer。
