### ISSUE TITLE
ppocr INFO: In PP-OCRv3, rec_image_shape parameter defaults to '3, 48, 320', if you are using recognition model with PP-OCRv2 or an older version, please set --rec_image_shape='3,32,320

### ISSUE THREAD

**Issue by shadowfienders** [PaddlePaddle/Paddle#43427]
### 请提出你的问题 Please ask your question

![image](https://user-images.githubusercontent.com/47406487/173227908-66dbd501-62a6-4b18-ad82-2bae5b70d385.png)
中间没结果，但是也没报错，我修改对应位置他还是这么提示，不知道怎么办了

**Comment by lvjian0706** [comment]
您好，相关问题建议去PaddleOCR repo中提下issue：https://github.com/PaddlePaddle/PaddleOCR/issues
