### ISSUE TITLE
paddle inference，GPU推理开启switch_ir_optim出错

### ISSUE THREAD

**Issue by gzsvip** [PaddlePaddle/Paddle#43433]
### 请提出你的问题 Please ask your question

硬件：i5 12400+gtx3060
系统：ubuntu 22.04 ，显卡驱动 515 , cuda 11.7，
docker tag：2.3.0-gpu-cuda11.2-cudnn8
paddle inference推理：

使用trt，
开启switch_ir_optim，就会出现：ValueError: (InvalidArgument) Pass preln_embedding_eltwise_layernorm_fuse_pass has not been registered.
  [Hint: Expected Has(pass_type) == true, but received Has(pass_type):0 != true:1.] (at /paddle/paddle/fluid/framework/ir/pass.h:242)
这个错误是什么原因啊？

config.switch_ir_optim(False) 则正常

**Comment by wjj19950828** [comment]
@gzhss 您好，可以检查一下：
- TRT版本是否与cuda以及cudnn版本匹配
- 版本匹配的话，环境变量是否已经设置trt的路径
