### ISSUE TITLE
win7下运行YOLO Paddle Serving 部署出错

### ISSUE THREAD

**Issue by d2fans** [PaddlePaddle/Paddle#43434]
### 请提出你的问题 Please ask your question

启动服务 ： python -m paddle_serving_server.serve --model serving_server --port 9393 --gpu_ids 0

提示找不到 workdir_9393/GeneralInferOp_0/general_model.prototxt

FileNotFoundError: [Errno 2] No such file or directory: 'workdir_9393/GeneralInferOp_0/general_model.prototxt'

- [ ]

**Comment by d2fans** [comment]
按照官方教程执行 https://gitee.com/paddlepaddle/PaddleDetection/tree/release/2.4/deploy/serving#5-%E6%B5%8B%E8%AF%95%E9%83%A8%E7%BD%B2%E7%9A%84%E6%9C%8D%E5%8A%A1

**Comment by TeslaZhao** [comment]
https://gitee.com/paddlepaddle/PaddleDetection/tree/release/2.4/deploy/serving#3-%E5%AF%BC%E5%87%BA%E6%A8%A1%E5%9E%8B
需要先导出参数，并且设置导出后的serving_server路径作为模型路径
