### ISSUE TITLE
【BUG】Paddle2.3 tensor乘法存在BUG

### ISSUE THREAD

**Issue by LDOUBLEV** [PaddlePaddle/Paddle#43436]
### bug描述 Describe the Bug

Paddle2.3 int类型tensor * float类型tensor 得到的结果是int类型tensor，理论上结果应该是float类型的tensor

<img width="553" alt="image" src="https://user-images.githubusercontent.com/26592129/173276388-58bae9fd-e129-4262-a76a-ae821cf997f7.png">

**Comment by FlyingQianMM** [comment]
问题收到，我们会尽快修复。可以暂时先对左边tensor转成float后再相乘，来避免这个问题。
```
a.astype(b.dtype) * b
```

**Comment by luotao1** [comment]
duplicated with
- https://github.com/PaddlePaddle/Paddle/issues/48916
