### ISSUE TITLE
paddle静态图如何输出中间某层的tensor

### ISSUE THREAD

**Issue by pooruss** [PaddlePaddle/Paddle#43472]
### 请提出你的问题 Please ask your question

我在调试paddle1.6版本静态图的模型代码，请问如何获取网络中间某层的tensor呢？

是通过fluid.ParallelExecutor里的run函数的fetch_list吗，但是fetch_list里的name如何获取呢？

**Comment by wjj19950828** [comment]
@pooruss 可以通过visualdl或者netron查看中间层op的name，然后获取tensor
