### ISSUE TITLE
使用PaddleX TensorRT加速时，第一次运行正常，第二次报Input[X] dimension 为0

### ISSUE THREAD

**Issue by Alana123Liu** [PaddlePaddle/Paddle#43480]
### bug描述 Describe the Bug

在使用PaddleX进行部署推理后，model_infer.dll在qt界面运行正常。在配置过tensorrt_infer.dll后，可以实现加速，但是在qt界面，第一次可以正常运行，第二次模型推理时，就会报Input(X) dimension must be 3, 4 or 5, but got dimension = 0 . (at C:/home/workspace/Paddle_release5/paddle/fluid/operators/interpolate_v2_op.cc:348)。
已在tensorrt_infer.cpp中设置dynamic_input的值，例如下：		
engine_config.min_input_shape["inputs"] = { 1, 3, 224, 224 };
engine_config.max_input_shape["inputs"] = { 1, 3, 224, 224 };
engine_config.optim_input_shape["inputs"] = { 1, 3, 224, 224 };

CUDA: 10.2 
cudnn: 7.6
tensorrt: 7.0.0.11

附件为tensorrt_infer.cpp和报错信息

[tensorrt_infer_cpp.txt](https://github.com/PaddlePaddle/Paddle/files/8895798/tensorrt_infer_cpp.txt)
[error.txt](https://github.com/PaddlePaddle/Paddle/files/8895815/error.txt)

**Comment by linjieccc** [comment]
辛苦 @FlyingQianMM 同学帮忙看下这个问题，非常感谢~

**Comment by FlyingQianMM** [comment]
如果用c++推理可以正常使用trt加速的话，需要排查下是否是生成dll的代码和qt调用的问题。

**Comment by Alana123Liu** [comment]
> 如果用c++推理可以正常使用trt加速的话，需要排查下是否是生成dll的代码和qt调用的问题。

好的！感谢！我试一试！

**Comment by Alana123Liu** [comment]
> 如果用c++推理可以正常使用trt加速的话，需要排查下是否是生成dll的代码和qt调用的问题。

观察图片输入维度都是正确的，感觉很像是动态输入的时候没有再次经过initialize的原因。
想问下报错的这个代码位置在哪儿呀？想去看下报错的前后原因C:/home/workspace/Paddle_release5/paddle/fluid/operators/interpolate_v2_op.cc:348

**Comment by Alana123Liu** [comment]
> 如果用c++推理可以正常使用trt加速的话，需要排查下是否是生成dll的代码和qt调用的问题。

第一次经过init的时候是都设置好的min_dimension, max_dimension, 但是第二次推理的时候，应当是没有把tensorrt优化过的参数模型保存，所以第二次没有引用到优化过的模型，我这边尝试利用with_static保存模型，但是保存tensorrt模型的默认路径是model/model.pdmodel，而不是一个文件夹地址，这样是无法在这个路径下添加文件的。麻烦 @FlyingQianMM 看看我这边是否找到的问题是否正确？
报错是：
PreconditionNotMetError: Can not create optimize cache directory: C://Users//HID-LIU//Documents//model_all//1_paddle_det_modle//packages//inference_model//model.pdmodel/_opt_cache/, Make sure you have permission to write
  [Hint: Expected _mkdir(opt_cache_dir.c_str()) != -1, but received _mkdir(opt_cache_dir.c_str()):-1 == -1:-1.] (at C:\home\workspace\Paddle_release\paddle/fluid/inference/analysis/helper.h:206)

**Comment by Shrinco** [comment]
> > 如果用c++推理可以正常使用trt加速的话，需要排查下是否是生成dll的代码和qt调用的问题。
> 
> 第一次经过init的时候是都设置好的min_dimension, max_dimension, 但是第二次推理的时候，应当是没有把tensorrt优化过的参数模型保存，所以第二次没有引用到优化过的模型，我这边尝试利用with_static保存模型，但是保存tensorrt模型的默认路径是model/model.pdmodel，而不是一个文件夹地址，这样是无法在这个路径下添加文件的。麻烦 @FlyingQianMM 看看我这边是否找到的问题是否正确？ 报错是： PreconditionNotMetError: Can not create optimize cache directory: C://Users//HID-LIU//Documents//model_all//1_paddle_det_modle//packages//inference_model//model.pdmodel/_opt_cache/, Make sure you have permission to write [Hint: Expected _mkdir(opt_cache_dir.c_str()) != -1, but received _mkdir(opt_cache_dir.c_str()):-1 == -1:-1.] (at C:\home\workspace\Paddle_release\paddle/fluid/inference/analysis/helper.h:206)

请问您的问题解决了吗？我也遇到了多线程推理的问题

**Comment by Alana123Liu** [comment]
> > > 如果用c++推理可以正常使用trt加速的话，需要排查下是否是生成dll的代码和qt调用的问题。
> > 
> > 
> > 第一次经过init的时候是都设置好的min_dimension, max_dimension, 但是第二次推理的时候，应当是没有把tensorrt优化过的参数模型保存，所以第二次没有引用到优化过的模型，我这边尝试利用with_static保存模型，但是保存tensorrt模型的默认路径是model/model.pdmodel，而不是一个文件夹地址，这样是无法在这个路径下添加文件的。麻烦 @FlyingQianMM 看看我这边是否找到的问题是否正确？ 报错是： PreconditionNotMetError: Can not create optimize cache directory: C://Users//HID-LIU//Documents//model_all//1_paddle_det_modle//packages//inference_model//model.pdmodel/_opt_cache/, Make sure you have permission to write [Hint: Expected _mkdir(opt_cache_dir.c_str()) != -1, but received _mkdir(opt_cache_dir.c_str()):-1 == -1:-1.] (at C:\home\workspace\Paddle_release\paddle/fluid/inference/analysis/helper.h:206)
> 
> 请问您的问题解决了吗？我也遇到了多线程推理的问题

没有.....这边定位是tensorRT在子线程里终止再继续推理会出现问题，即使在子线程中加入初始化信息，依然会报错。只能初始化一次后一直跑，只要停下来，下一次就报错了......

**Comment by Shrinco** [comment]
> 没有.....这边定位是tensorRT在子线程里终止再继续推理会出现问题，即使在子线程中加入初始化信息，依然会报错。只能初始化一次后一直跑，只要停下来，下一次就报错了......

我刚刚排查出来是子线程没有优化信息的原因导致。加入也会报错吗？您是如何将优化信息添加到子线程中的呢？我也是只要跑起来不停就可以，一旦停下来在推理就会错。是paddle的bug吗？

**Comment by Shrinco** [comment]
> 没有.....这边定位是tensorRT在子线程里终止再继续推理会出现问题，即使在子线程中加入初始化信息，依然会报错。只能初始化一次后一直跑，只要停下来，下一次就报错了......

你好，我通过别的方法解决了这个bug。报错的信息大致是说trt找不到优化信息导致的，而找不到优化信息的原因大致是一个trt的优化信息对应cuda的一个上下文，每一个线程都有自己独立的上下文。所以在 qt thread 的 run 之后再次执行就会出现这个bug。而解决的办法就是建立一个工作对象，将主线程和工作对象通过 signal 和 slot连接起来，然后把这个工作对象移到线程中，这样停止再推理就不会出现这个错误了。
线程+GPU，用继承QThread的方式是完全没有问题的，只有一个线程+Trt也是没有问题的，所以这也是paddle的一个bug。
