### ISSUE TITLE
在PaddleServing的docker镜像中安装paddlepaddle-gpu失败

### ISSUE THREAD

**Issue by bittergourd1224** [PaddlePaddle/Paddle#43481]
### 问题描述 Issue Description

执行指令包括：
sudo docker pull registry.baidubce.com/paddlepaddle/serving:0.9.0-cuda10.2-cudnn7-devel
sudo nvidia-docker run -p 9292:9292 --name test_gpu -dit registry.baidubce.com/paddlepaddle/serving:0.9.0-cuda10.2-cudnn7-devel bash
sudo nvidia-docker exec -it test_gpu bash
pip3 install paddlepaddle-gpu==2.3.0 -i https://pypi.tuna.tsinghua.edu.cn/simple

然后在python中执行：
import paddle
paddle.utils.run_check()
就会一直卡死，不出结果

### 版本&环境信息 Version & Environment Information

PaddlePaddle: 2.3.0
GPU: NVIDIA GeForce RTX 3090, cuda10.2, cudnn7
系统环境：Ubuntu18.04
Python版本：python3.6

**Comment by TeslaZhao** [comment]
有报错信息吗？我用上面的docker环境和命令运行结果如下：

#尝试加载paddle
python3.7
import paddle

#等待时间长一些，会有xi信息。
![image](https://user-images.githubusercontent.com/6309021/173510880-c6c1451c-5325-4d33-8da3-7b696f486658.png)

**Comment by bittergourd1224** [comment]
@TeslaZhao 感谢回复。我等待了十多分钟，一直卡在如下界面：
![2022-06-14 15-09-23 的屏幕截图](https://user-images.githubusercontent.com/26888350/173516458-4be364aa-2184-4822-9ce6-b10ea2e51b99.png)
并且CTRL-C也无法终止，只能强制关闭终端

此外我看你是装在了python3.7的环境中，而我是装在python3的环境中，即python3.6.0
能帮忙试下如果装在python3.6.0中是否也有类似问题呢？

**Comment by TeslaZhao** [comment]
从报错信息驱动版本是11.4，运行版本是10.2,cuDNN版本是8.6，可能是本机驱动版本和docker内版本不一致导致的，建议您安装安装cuda11.2的docker

**Comment by bittergourd1224** [comment]
11.2版本docker中，paddlepaddle环境检查没有问题了
并且经过多次尝试，如果需要通过serving环境检查，paddlepaddle-gpu的安装必须为：
pip3 install https://paddle-inference-lib.bj.bcebos.com/2.3.0/python/Linux/GPU/x86-64_gcc8.2_avx_mkl_cuda11.2_cudnn8.2.1_trt8.0.3.4/paddlepaddle_gpu-2.3.0.post112-cp36-cp36m-linux_x86_64.whl
