### ISSUE TITLE
[code format] add include-what-you-use for headers including

### ISSUE THREAD

**Issue by gglin001** [PaddlePaddle/Paddle#43482]
### 问题描述 Please describe your issue

hi, is there a plan to add `include-what-you-use` tool to reduce include headers for cpp src?

ref
https://include-what-you-use.org/
https://github.com/include-what-you-use/include-what-you-use

**Comment by gglin001** [comment]
@betterpig hi, could you help with it

**Comment by betterpig** [comment]
> @betterpig hi, could you help with it

According to PR #30924, we did some cleaning work before to remove headers not needed. Enabling `include-what-you-use ` in cpplint will demand to add them again, that's not what we want. So we disabled it.

**Comment by gglin001** [comment]
> > @betterpig hi, could you help with it
> 
> According to PR #30924, we did some cleaning work before to remove headers not needed. Enabling `include-what-you-use ` in cpplint will demand to add them again, that's not what we want. So we disabled it.

[`include-what-you-use`](https://include-what-you-use.org/
) tool will do static analysis for cpp src, I think it is different from the  `build/include_what_you_use` from `cpplint` (https://google.github.io/styleguide/cppguide.html#Include_What_You_Use)

**Comment by gglin001** [comment]
> we did some cleaning work before to remove headers not needed. Enabling include-what-you-use in cpplint will demand to add them again

这种情况是否可以通过单独的配置实现, 我的意思是对代码整体有一个 include 规范的普遍约束似乎是比较好的选择

**Comment by betterpig** [comment]
> > we did some cleaning work before to remove headers not needed. Enabling include-what-you-use in cpplint will demand to add them again
>
> 这种情况是否可以通过单独的配置实现, 我的意思是对代码整体有一个 include 规范的普遍约束似乎是比较好的选择

代码风格检查工具升级一期已经基本完成，在二期会调研 该工具的 收益和影响，决定是否引入。感谢你的建议！

**Comment by gglin001** [comment]
I think to supoort `include-what-you-use`, needs to support building with clang(for Linux) first
another issue
- https://github.com/PaddlePaddle/Paddle/issues/44978
