### ISSUE TITLE
【单机多卡】用单机多卡训练，精度反而不如单卡

### ISSUE THREAD

**Issue by dowdyboy** [PaddlePaddle/Paddle#43493]
### 请提出你的问题 Please ask your question

我在mnist数据集上分别用单卡和8卡进行训练，单卡第一个epoch完成后准确度大约94，8卡第一个epoch完成后准确度大约86。
其他配置完全一样。
为什么会差这么多？是不是框架的反向传播那块在多卡上有问题？

**Comment by linjieccc** [comment]
感谢关注，是否可以请 @yaoxuefeng6 同学帮忙看下这个问题，非常感谢~
