### ISSUE TITLE
部署PaddleServing，有CPU版本的吗？

### ISSUE THREAD

**Issue by xaviNo4** [PaddlePaddle/Paddle#43494]
### 问题描述 Issue Description

官网如上，是描述如何安装GPU版本的 。我的服务器是X86的，请问应该下哪个WHL文件？

```
# 安装serving，用于启动服务
wget https://paddle-serving.bj.bcebos.com/test-dev/whl/paddle_serving_server_gpu-0.8.3.post102-py3-none-any.whl
pip3 install paddle_serving_server_gpu-0.8.3.post102-py3-none-any.whl
# 如果是cuda10.1环境，可以使用下面的命令安装paddle-serving-server
# wget https://paddle-serving.bj.bcebos.com/test-dev/whl/paddle_serving_server_gpu-0.8.3.post101-py3-none-any.whl
# pip3 install paddle_serving_server_gpu-0.8.3.post101-py3-none-any.whl

```

### 版本&环境信息 Version & Environment Information

****************************************
Paddle version: 2.3.0
Paddle With CUDA: False

OS: Ubuntu 16.04
Python version: 3.7.0

CUDA version: 10.2.89
cuDNN version: 7.6.5
Nvidia driver version: None

**Comment by TeslaZhao** [comment]
https://github.com/PaddlePaddle/Serving/blob/v0.9.0/doc/Latest_Packages_CN.md#paddle-serving-server-x86-cpugpu

这里是所有的python whl包

安装方式：
https://github.com/PaddlePaddle/Serving/blob/v0.9.0/doc/Install_CN.md#21-%E5%9C%A8%E7%BA%BF%E5%AE%89%E8%A3%85
