### ISSUE TITLE
paddle.summary多输入问题

### ISSUE THREAD

**Issue by yeyupiaoling** [PaddlePaddle/Paddle#43499]
### 需求描述 Feature Description

原来的paddle.summary无法通过input指定多输入，例如这样的输入`def forward(self, audio, audio_len)`，如果这样输出出错
```
        input_data = [paddle.rand([1, 161, 900], dtype=paddle.float32),
                      paddle.to_tensor(200, dtype=paddle.int64)]
        paddle.summary(net=model, input=input_data)
```

如果源码这这样修改，就能正常使用。
https://github.com/PaddlePaddle/Paddle/blob/2106f668ce55f90816192da4ab93455b86298357/python/paddle/hapi/model_summary.py#L355

改成：
```python
model(*x) 
```

或者有其他解决办法吗？不能用`input_size `参数指定，因为会生成为0的数据，导致模型错误。

**Comment by SigureMo** [comment]
> 如果源码这这样修改，就能正常使用。

emmmm，看不到改的是啥啊……

按我的理解，参考 build_input，可以对这几行修改成这样：

https://github.com/PaddlePaddle/Paddle/blob/2106f668ce55f90816192da4ab93455b86298357/python/paddle/hapi/model_summary.py#L353-L359

修改后

```python
    if input is not None:
        x = input
        if not (isinstance(input, (list, tuple)) and _all_is_tensor(input_size)):
            x = [x]
    else:
        x = build_input(input_size, dtypes)
    
    # make a forward pass
    model(*x)
```

当然需要额外实现下 _all_is_tensor，或者不校验是否全部是 Tensor，直接看到 list 和 tuple 直接认为是多输入（貌似非 Tensor 也不是合法的输入）

另外好像代码里的 _all_is_numper 是想写 _all_is_number 吧 :joy:

**Comment by yeyupiaoling** [comment]
>emmmm，看不到改的是啥啊……

漏了，已经补上。

做法跟你的差不多。

**Comment by SigureMo** [comment]
emmm，虽说这样也可以，但我觉得有些不安全，我刚刚才发现 paddle 目前对 Tensor 进行解构（`*` 操作）后居然是本身，但无论从逻辑上（Python 语言本身）还是其他框架（PyTorch、Numpy），这都不符合预期，也许未来 paddle 会向这些框架对齐……因此我认为根据情况包裹一层是更为安全的行为

刚刚我试了下，在不考虑 `_all_is_tensor` 是可以正常运行的，或者说我个人认为确实不需要考虑 `_all_is_tensor`

**Comment by SigureMo** [comment]
我又仔细看了下 [paddle.summary 的例子](https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/summary_cn.html#summary)，发现其中有这样的一个例子：

```python
# list input demo
class LeNetListInput(LeNet):

    def forward(self, inputs):
        x = self.features(inputs[0])

        if self.num_classes > 0:
            x = paddle.flatten(x, 1)
            x = self.fc(x + inputs[1])
        return x

lenet_list_input = LeNetListInput()
input_data = [paddle.rand([1, 1, 28, 28]), paddle.rand([1, 400])]
params_info = paddle.summary(lenet_list_input, input=input_data)
print(params_info)
```

也就是说 paddle 是支持输入 list 的 input 的，因此直接解构会破坏这种用例，目前我没有想到一种既兼容现有用例又能够支持多输入的改法……不过我个人认为多输入确实是一个应该考虑的问题……

所以你的用例的话，个人暂时建议改下模型……使其 inputs 接收一个 list 就好了，如果不方便改原来的模型的话，自己新建个模型 wrap 下就好了……

**Comment by yeyupiaoling** [comment]
改模型实在不方便，我是把这个代码复制到我的项目中，修改使用。在我项目能正常使用就好。
https://github.com/PaddlePaddle/Paddle/blob/2106f668ce55f90816192da4ab93455b86298357/python/paddle/hapi/model_summary.py
