### ISSUE TITLE
current LoD's format can't support sort by length

### ISSUE THREAD

**Issue by Superjom** [PaddlePaddle/Paddle#4349]
Current LoD stores end offsets of each sentence, that design might save space (a little).

In dynamic-batch RNN (that take variant length sentences as input) need to sort the elements in one level according to number of elements in lower level, in that case, the LoD may be reordered, that need a begin offset in addition to end offset.

So a pair of begin and end offsets should be introduced to LoD's implementation.

**Comment by qingqing01** [comment]
假如Input: Lod={{0,2,3,5,6,8,11}, {0,2,5,11}}

```txt
3 (batch size = 3)     
1    2        3                 
2    1   2    1  2  3        
||   |   ||   |  || |||
```

- level-0粒度的长度获取： Lod[0]相邻两个元素之差，即可获取到
- level-1粒度的长度获取： 依据Lod[1]在Lod[0]中的位置，比如：
   - Lod[0]中index(0) = 0, index(2)=1, 得到level-1中第0个sample的长度为 2- 1 = 1
   - Lod[0]中index(2) = 1, index(5)=3, 得到level-1中第1个sample的长度为 3- 1 = 2
   - Lod[0]中index(5) = 3, index(11)=6, 得到level-1中第2个sample的长度为 6- 3 = 3

这样level-1获取长度相对麻烦一些，但是可以做到排序~

**Comment by lcy-seso** [comment]
我记得现在RecurrentLayerGroup中按照qingqing描述的这样做。
