### ISSUE TITLE
Can you please put Docker images with no-avx to Dockerhub?

### ISSUE THREAD

**Issue by quents** [PaddlePaddle/Paddle#43512]
### 问题描述 Issue Description

Hi,

I use M1 Macbook and cannot pull Docker images to my local machine becasue M1 Macbooks don't support AVX. The error message is:

"Error: Your machine doesn't support AVX, but the installed PaddlePaddle is avx core, you should reinstall paddlepaddle with no-avx core."

### 版本&环境信息 Version & Environment Information

****************************************
Paddle version: 2.3.0
Paddle With CUDA: 2.3.0

OS: macOs 11.6.3
Python version: 3.7

CUDA version: 10.2
cuDNN version: 7
Nvidia driver version: 470.57.02
****************************************

**Comment by linjieccc** [comment]
Hi, please refer to here to install the CPU version of PaddlePaddle via Docker
https://www.paddlepaddle.org.cn/documentation/docs/en/install/docker/macos-docker_en.html#install-on-macos-via-docker

**Comment by quents** [comment]
Hi, The CPU version of MacOS unfortunately doesn't work with the following error:

`Error: Your machine doesn't support AVX, but the installed PaddlePaddle is avx core, you should reinstall paddlepaddle with no-avx core.
Traceback (most recent call last):
  File "/usr/local/bin/uvicorn", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/uvicorn/main.py", line 362, in main
    run(**kwargs)
  File "/usr/local/lib/python3.7/dist-packages/uvicorn/main.py", line 386, in run
    server.run()
  File "/usr/local/lib/python3.7/dist-packages/uvicorn/server.py", line 48, in run
    loop.run_until_complete(self.serve(sockets=sockets))
  File "uvloop/loop.pyx", line 1501, in uvloop.loop.Loop.run_until_complete
  File "/usr/local/lib/python3.7/dist-packages/uvicorn/server.py", line 55, in serve
    config.load()
  File "/usr/local/lib/python3.7/dist-packages/uvicorn/config.py", line 308, in load
    self.loaded_app = import_from_string(self.app)
  File "/usr/local/lib/python3.7/dist-packages/uvicorn/importer.py", line 23, in import_from_string
    raise exc from None
  File "/usr/local/lib/python3.7/dist-packages/uvicorn/importer.py", line 20, in import_from_string
    module = importlib.import_module(module_str)
  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "./main.py", line 24, in <module>
    from core.functions import execute
  File "./core/functions.py", line 12, in <module>
    from paddleocr import PaddleOCR, draw_ocr
  File "/PaddleOCR/paddleocr.py", line 21, in <module>
    import paddle
  File "/usr/local/lib/python3.7/dist-packages/paddle/__init__.py", line 25, in <module>
    from .framework import monkey_patch_variable
  File "/usr/local/lib/python3.7/dist-packages/paddle/framework/__init__.py", line 17, in <module>
    from . import random  # noqa: F401
  File "/usr/local/lib/python3.7/dist-packages/paddle/framework/random.py", line 16, in <module>
    import paddle.fluid as fluid
  File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/__init__.py", line 36, in <module>
    from . import framework
  File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/framework.py", line 37, in <module>
    from . import core
  File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/core.py", line 365, in <module>
    raise e
  File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/core.py", line 313, in <module>
    from . import core_noavx
ImportError: cannot import name 'core_noavx' from 'paddle.fluid' (/usr/local/lib/python3.7/dist-packages/paddle/fluid/__init__.py)`

**Comment by hydra1983** [comment]
+1

```
WARNING: AVX is not support on your machine. Hence, no_avx core will be imported, It has much worse preformance than avx core.
Error: AVX is not support on your machine, but you have installed paddlepaddle with avx core, you should reinstall paddlepaddle by 'python -m pip install -U paddlepaddle-gpu[==version] -f https://paddlepaddle.org.cn/whl/stable_noavx.html'
Traceback (most recent call last):
  File "/usr/local/bin/hub", line 5, in <module>
    from paddlehub.commands.utils import execute
  File "/usr/local/lib/python3.7/site-packages/paddlehub/__init__.py", line 18, in <module>
    import paddle
  File "/usr/local/lib/python3.7/site-packages/paddle/__init__.py", line 29, in <module>
    from .fluid import monkey_patch_variable
  File "/usr/local/lib/python3.7/site-packages/paddle/fluid/__init__.py", line 35, in <module>
    from . import framework
  File "/usr/local/lib/python3.7/site-packages/paddle/fluid/framework.py", line 36, in <module>
    from . import core
  File "/usr/local/lib/python3.7/site-packages/paddle/fluid/core.py", line 349, in <module>
    raise e
  File "/usr/local/lib/python3.7/site-packages/paddle/fluid/core.py", line 308, in <module>
    from .core_noavx import *
ModuleNotFoundError: No module named 'paddle.fluid.core_noavx'
```

**Comment by JimVincentW** [comment]
Same here, general Instructions on M1 Mac machines or which alternatives to set these repositories up would be highly appreciated
