### ISSUE TITLE
获得层对象和参数对象的api

### ISSUE THREAD

**Issue by MARKLIN1000** [PaddlePaddle/Paddle#43527]
### 请提出你的问题 Please ask your question

如何获得特定层对象和参数对象，如怎么获得BERT的embedding层

**Comment by ZhangHandi** [comment]
获取BERT的embedding层，可通过两种方式找到。

**Comment by ZhangHandi** [comment]
获取BERT的embedding层可通过两种方式找到。
1. BertModel类的代码里面去找，链接：https://github.com/PaddlePaddle/PaddleNLP/blob/a93bdffb4769cf5d08789b04125573a73ab0e950/paddlenlp/transformers/bert/modeling.py#L506，发现embedding层可通过bert.embeddings获得
2. 直接打印bert，可以看到对象名称，通过'.'连接获得对应层，比如获得word embedding就是bert.embeddings.word_embeddings
