### ISSUE TITLE
模型初始化后，能不能再外部对特定模块初始化参数

### ISSUE THREAD

**Issue by MARKLIN1000** [PaddlePaddle/Paddle#43524]
### 请提出你的问题 Please ask your question

比如说我已经初始化模型：
self.bert = BertModel.from_pretrained(args.bert_dir)

现在我想对BertEmbedding layer 进行参数的初始化，将另一个Embedding与BERT的Embedding融合后再传给encoder。有没有类似torch.nn.init的API呢？

**Comment by linjieccc** [comment]
@MARKLIN1000 可以参考下这里初始化相关的api paddle.nn.initializer
https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/nn/Overview_cn.html

**Comment by luckyyangrun** [comment]
+1 想知道有没有解决办法
