### ISSUE TITLE
有没有方法判断CPU是否支持mkldnn加速，推理库内部会判断吗

### ISSUE THREAD

**Issue by marsbzp** [PaddlePaddle/Paddle#43528]
### 请提出你的问题 Please ask your question

有没有方法判断CPU是否支持mkldnn加速，推理库内部会判断吗

**Comment by ZhangHandi** [comment]
可以参考mkldnn文档判断cpu是否支持mkldnn加速：https://github.com/oneapi-src/oneDNN#system-requirements
