### ISSUE TITLE
Multiple GPUS： low performance and scalability 

### ISSUE THREAD

**Issue by Sampson1107** [PaddlePaddle/Paddle#4352]
你好，
我用的模型是：https://github.com/PaddlePaddle/models/tree/develop/image_classification
我在该模型下：测试了如下三个模型：Alexnet\Googlenet\Resnet，但是单卡的绝对性能比较差，而且弱扩展性也不好。具体数据如下（images/s）：
GPU                1            2          4
alexnet	       638	    851	1082
googlenet	277      441	662
resnet      	75	    134	241

是否是因为cudnn没有调用过的问题导致？
我在alexnet.py中加入了layer_type='cudnn_conv'性能没有什么变化。
是否还有其他地方需要修改呢？
表格如下：其中分别表示GPU卡数在1、2、4时，网络模型每秒训练的图片数目，我用的卡是Tesla P40，
alexnet每个卡我用的batch_size是1024，googlenet设置的batch_size为每个卡128，resnet是32

| GPU | 1 | 2 |4 |
| :------| ------: | :------: | :------: |
| alexnet | 638 | 851 | 1082 |
| googlenet | 277 | 441 | 662 |
| resnet | 75 | 134 | 241 |

**Comment by lcy-seso** [comment]
能否使用markdown绘制表格，将上述实验数据放在表格中，同时解释一下这些数据的含义？

**Comment by Sampson1107** [comment]
表格如下：其中分别表示GPU卡数在1、2、4时，网络模型每秒训练的图片数目，我用的卡是Tesla P40，
alexnet每个卡我用的batch_size是1024，googlenet设置的batch_size为每个卡128，resnet是32

| GPU | 1 | 2 |4 |
| :------| ------: | :------: | :------: |
| alexnet | 638 | 851 | 1082 |
| googlenet | 277 | 441 | 662 |
| resnet | 75 | 134 | 241 |

**Comment by Sampson1107** [comment]
？？@lcy-seso

**Comment by Sampson1107** [comment]
？？
