### ISSUE TITLE
Jetxon Xavier NX paddle installation g++ segmentation fault on paddle/phi/kernels/funcs/CMakeFiles/math_function.dir/math_function.cc.o

### ISSUE THREAD

**Issue by lmdnyo** [PaddlePaddle/Paddle#43535]
### 问题描述 Issue Description

I am trying to build paddlepaddle on the Jetxon Xavier NX 16 GB using given instructions. The necessary packages and per-requisites are installed. But it is getting stuck in make TARGET=ARMV8 -j$(nproc). Here is the errror.

[  6%] Building CXX object paddle/phi/kernels/funcs/CMakeFiles/math_function.dir/math_function.cc.o
g++: internal compiler error: Segmentation fault signal terminated program cc1plus
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-8/README.Bugs> for instructions.
paddle/phi/kernels/funcs/CMakeFiles/math_function.dir/build.make:75: recipe for target 'paddle/phi/kernels/funcs/CMakeFiles/math_function.dir/math_function.cc.o' failed
make[2]: *** [paddle/phi/kernels/funcs/CMakeFiles/math_function.dir/math_function.cc.o] Error 4
CMakeFiles/Makefile2:57196: recipe for target 'paddle/phi/kernels/funcs/CMakeFiles/math_function.dir/all' failed
make[1]: *** [paddle/phi/kernels/funcs/CMakeFiles/math_function.dir/all] Error 2
Makefile:135: recipe for target 'all' failed
make: *** [all] Error 2

I am using following configuration.
Ubuntu 18.04 
uname -a = Linux tegra-ubuntu 4.9.253-tegra #4 SMP PREEMPT Wed Mar 9 19:40:11 CST 2022 aarch64 aarch64 aarch64 GNU/Linux
Jetpack = 4.6
Cuda = 10.2
Cudnn = 8
gcc = gcc-7 (tried gcc-8 as well)
paddle version = 2.3.0

I also tried to install 2.1.3 and 2.0.2 but same error. Tried to install ready packages of NVIDIA JETSON NANO paddlepaddle-gpu-2.0.0 wheel from QEngineering, tried gpu-1.6 and 1.83 wheels but no luck. Got errors in fluid.install_check.run_check().

After that I even tried with make TARGET=ARMV8 and -j1 with following cmake configuration.

cmake .. -DWITH_MKL=OFF -DWITH_MKLDNN=OFF -DWITH_AVX=OFF -DWITH_GPU=ON -DON_INFER=ON -DWITH_TESTING=OFF -DCMAKE_BUILD_TYPE=Release -DCUDA_ARCH_NAME=All -DWITH_ARM=ON -DWITH_NV_JETSON=ON -DWITH_PYTHON=ON -DPY_VERSION=3.6 -DPYTHON_INCLUDE_DIR:PATH=/usr/include/python3.6 -DPYTHON_EXECUTABLE:FILEPATH=/usr/bin/python3.6 -DPYTHON_LIBRARY:FILEPATH=/usr/lib/aarch64-linux-gnu/libpython3.6m.so -DWITH_XBYAK=OFF -DWITH_RCCL=OFF -DWITH_ROCM=OFF -DCMAKE_CUDA_COMPILER=/usr/local/cuda-10.2/bin/nvcc

But still the same error every time. Please help since I am not able to compile the same on Xavier NX.

### 版本&环境信息 Version & Environment Information

****************************************
Paddle version: 2.0.0
Paddle With CUDA: True

OS: Ubuntu 18.04
Python version: 3.6.9

CUDA version: 10.2.300
Build cuda_10.2_r440.TC440_70.29663091_0
cuDNN version: None.None.None
Nvidia driver version: None
****************************************

**Comment by lmdnyo** [comment]
I was wondering why cudnn was not shown by the above script. So I checked and found it is already there. Here are the details

nvidia@tegra-ubuntu:~$ find /usr -name  "cudnn*.h"
/usr/include/aarch64-linux-gnu/cudnn_v8.h
/usr/include/aarch64-linux-gnu/cudnn_cnn_train_v8.h
/usr/include/aarch64-linux-gnu/cudnn_adv_infer_v8.h
/usr/include/aarch64-linux-gnu/cudnn_adv_train_v8.h
/usr/include/aarch64-linux-gnu/cudnn_cnn_infer_v8.h
/usr/include/aarch64-linux-gnu/cudnn_ops_train_v8.h
/usr/include/aarch64-linux-gnu/cudnn_backend_v8.h
/usr/include/aarch64-linux-gnu/cudnn_ops_infer_v8.h
/usr/include/aarch64-linux-gnu/cudnn_version_v8.h
/usr/include/cudnn.h
/usr/include/cudnn_cnn_infer.h
/usr/include/cudnn_adv_infer.h
/usr/include/cudnn_ops_train.h
/usr/include/cudnn_version.h
/usr/include/cudnn_cnn_train.h
/usr/include/cudnn_backend.h
/usr/include/cudnn_adv_train.h
/usr/include/cudnn_ops_infer.h

**Comment by ZhangHandi** [comment]
Hi, try to build in a single-threaded environment instead of multi-threaded
