### ISSUE TITLE
FAQ问题分类

### ISSUE THREAD

**Issue by luotao1** [PaddlePaddle/Paddle#4354]
目前的[FAQ](http://doc.paddlepaddle.org/develop/doc_cn/faq/index_cn.html)，已经有25个问题。这些问题需要分一下类，以便读者更好地查阅。

从目前的问题来看，可以分成以下几类：
- 编译安装与单元测试：
  - 9 运行Docker GPU镜像出现 “CUDA driver version is insufficient”
  - 10 CMake源码编译, 找到的PythonLibs和PythonInterp版本不一致
  - 11 CMake源码编译，Paddle版本号为0.0.0
  - 7 paddlepaddle*.whl is not a supported wheel on this platform.
  - 15 编译安装后执行 import paddle.v2 as paddle 报ImportError: No module named v2
  - 3 遇到“非法指令”或者是“illegal instruction”
  - 8 python相关的单元测试都过不了
- 模型配置：
  - 19 PaddlePaddle如何输出多个层
  - 20 paddle.layer.memory 的参数 name 如何使用
  - 21 dropout 使用
  - 24 PaddlePaddle V2 API中，调用infer接口时输出多个层的计算结果
  - 25 PaddlePaddle 中不同的 recurrent layer 之间的差异
- 参数设置：
   - 4 如何选择SGD算法的学习率
   - 22 如何设置学习率退火（learning rate annealing）
   - 5 如何初始化参数
   - 6 如何共享参数
   - 17 如何加载预训练参数
   - 16 参数存储格式是什么，如何和明文进行相互转化
   - 12 A protocol message was rejected because it was too big
- 本地训练与预测：
  - 1 如何减少内存占用
  - 2 如何加速训练速度
  - 13 如何指定GPU设备
- 集群训练与预测：
  - 18 集群多节点训练，日志中保存均为网络通信类错误

**Comment by lcy-seso** [comment]
1. 训练加速 --> 训练与预测
2. 参数、学习率相关 --> 参数设置
3. 编译、安装、单测等 --> 编译安装与单元测试
4. 集群 --> 集群训练
