### ISSUE TITLE
paddle.amp.GradScaler文档中unscale_()的作用描述有点问题

### ISSUE THREAD

**Issue by OccupyMars2030** [PaddlePaddle/Paddle#43544]
### 文档链接&描述 Document Links & Description

https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/amp/GradScaler_cn.html#unscale-optimizer

![屏幕截图 2022-06-15 165754](https://user-images.githubusercontent.com/31559413/173787319-e80445d9-ecd4-41ef-8221-817aaa4a6794.jpg)

文档中写"unscale_() 用于让loss除去一个缩放的比例。"。按照我的理解，这里unscale_()的作用描述是错的

### 请提出你的建议 Please give your suggestion

应该改为 “unscale_() 用于让gradients除去一个缩放的比例。”

**Comment by OccupyMars2030** [comment]
我参考了https://pytorch.org/docs/stable/amp.html#gradient-scaling

**Comment by OccupyMars2030** [comment]
另外我想请问：像这种文档错误，我可以直接提交PR来修改吗？应该修改哪个文件？应该同时有中文文件和英文文件吧

**Comment by wzzju** [comment]
您好！我的理解：文档说明是没有问题的，loss除去一个缩放比例，根据链式法则gradients也会对应除去一个缩放比例。

**Comment by Ligoml** [comment]
> 另外我想请问：像这种文档错误，我可以直接提交PR来修改吗？应该修改哪个文件？应该同时有中文文件和英文文件吧

文档错误，如果可以完全确认是可以提pr改的，英文文档写在API源码的注释里，中文文档写在https://github.com/PaddlePaddle/docs 里
以这个case来看，负责人认为文档是没有问题的，所以可以不做修改~

拿不准的问题建议还是提issue确认一下，感谢你对开源贡献的热情！
