### ISSUE TITLE
registry.baidubce.com/paddlepaddle/paddle:2.3.0-gpu-cuda10.1-cudnn7的镜像能否提供？

### ISSUE THREAD

**Issue by AI-Mart** [PaddlePaddle/Paddle#43548]
### 需求描述 Feature Description

registry.baidubce.com/paddlepaddle/paddle:2.3.0-gpu-cuda10.1-cudnn7的镜像能否提供？

### 替代实现 Alternatives

registry.baidubce.com/paddlepaddle/paddle:2.3.0-gpu-cuda10.1-cudnn7的镜像能否提供？

**Comment by AI-Mart** [comment]
目前只看到registry.baidubce.com/paddlepaddle/paddle:2.3.0-gpu-cuda10.2-cudnn7的镜像，没看到10.1的

**Comment by XieYunshen** [comment]
目前发版镜像中没有cuda10.1的版本，不过可以使用paddle的开发镜像，手动安装2.3.0版本的PaddlePaddle即可；
`
docker pull paddlepaddle/paddle:latest-gpu-cuda10.1-cudnn7-gcc54-dev
python -m pip install paddlepaddle-gpu==2.3.0.post101 -f https://www.paddlepaddle.org.cn/whl/linux/mkl/avx/stable.html
`

**Comment by AI-Mart** [comment]
感谢回复，我目前用的就是这个方案，只是镜像挂载在这里下载速度有点慢，挂载在registry.baidubce.com就挺快的了，如果方便的话，建议增加一个

**Comment by XieYunshen** [comment]
`registry.baidubce.com/paddlepaddle/paddle:latest-gpu-cuda10.1-cudnn7-gcc54-dev`和`paddlepaddle/paddle:latest-gpu-cuda10.1-cudnn7-gcc54-dev`是一样的，可以拉取`registry.baidubce.com/paddlepaddle/paddle:latest-gpu-cuda10.1-cudnn7-gcc54-dev`,速度会快一些

**Comment by AI-Mart** [comment]
好的，谢谢，这个是gcc54的版本，gcc82的版本会不会更好些？

**Comment by AI-Mart** [comment]
另外registry.baidubce.com/paddlepaddle/paddle下的镜像都有哪些，有没有一个文档列表说明，或者说可以登陆进去查看吗？类似dockerhub

**Comment by XieYunshen** [comment]
cuda10.1默认的安装包是gcc54的，如果想用gcc82的镜像可以使用下面这个，
`docker pull registry.baidubce.com/paddlepaddle/paddle:latest-gpu-cuda10.1-cudnn7-gcc82-dev`
另：
`registry.baidubce.com/paddlepaddle/paddle`下的镜像和docker hub中`paddlepaddle/paddle`镜像基本一致，可以在docker hub中查找镜像，然后加上`registry.baidubce.com`前缀使用
