### ISSUE TITLE
paddle中类似BertConfig的类？

### ISSUE THREAD

**Issue by MARKLIN1000** [PaddlePaddle/Paddle#43557]
### 请提出你的问题 Please ask your question

paddle中类似BertConfig的类？形成BERT模型配置文件对象

**Comment by ZhangHandi** [comment]
没有类，直接集成在BertPretrainedModel中。参考：https://github.com/PaddlePaddle/PaddleNLP/blob/d95cfc314f3407db9e126a380c5c8598ec401a63/paddlenlp/transformers/bert/modeling.py#L96
需要这个类是有什么需求呢，NLP相关问题欢迎去PaddleNLP repo下提issue，具体链接：https://github.com/PaddlePaddle/PaddleNLP/issues

**Comment by MARKLIN1000** [comment]
我想这一个BERT的继承类，但不知道怎么讲参数传递进去？原先都是这一个json然后BertConfig实例化，再穿进去。



------------------ 原始邮件 ------------------
发件人: handiz ***@***.***&gt;
发送时间: 2022年6月15日 20:52
收件人: PaddlePaddle/Paddle ***@***.***&gt;
抄送: MARKLIN1000 ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [PaddlePaddle/Paddle] paddle中类似BertConfig的类？ (Issue #43557)





 
没有类，直接集成在BertPretrainedModel中。参考：https://github.com/PaddlePaddle/PaddleNLP/blob/d95cfc314f3407db9e126a380c5c8598ec401a63/paddlenlp/transformers/bert/modeling.py#L96
 需要这个类是有什么需求呢，NLP相关问题欢迎去PaddleNLP repo下提issue，具体链接：https://github.com/PaddlePaddle/PaddleNLP/issues
