### ISSUE TITLE
'ParamBase'下没有 'requires_grad'吗？

### ISSUE THREAD

**Issue by MARKLIN1000** [PaddlePaddle/Paddle#43568]
### 请提出你的问题 Please ask your question

![image](https://user-images.githubusercontent.com/82072274/173974171-21cc7c57-34b3-4e8e-8a68-e9f8a5bcec50.png)
为了在对抗训练中获得对应的梯度信息，这应该改成什么参数啊

**Comment by an1018** [comment]
param.grad，对抗训练可以参考这个issue： #37006
