### ISSUE TITLE
主机cuda版本是11.7，docker 里面的cuda 是10.2，GPU推理时出错，请问是否CUDA的版本需要主机和DOCKER都一致？

### ISSUE THREAD

**Issue by gzsvip** [PaddlePaddle/Paddle#43560]
### 请提出你的问题 Please ask your question

硬件：i7 12700F+GTX3060+16G
系统：ubuntu 20.04，已装好nvidia驱动515.48.07，cuda版本 11.7，nvidia-smi检查正常
docker：官网pull下来的 registry.baidubce.com/paddlepaddle/paddle   2.3.0-gpu-cuda11.2-cudnn8 ，已安装nvidia-docker

上传测试代码，cpu运行模型正常,mkldnn运行挺快，
gpu模式，关闭ir_optim可以跑，但打开ir_optim优化时，出现以下错误：
 predictor = paddle.inference.create_predictor(config)
ValueError: (InvalidArgument) Pass preln_embedding_eltwise_layernorm_fuse_pass has not been registered.
  [Hint: Expected Has(pass_type) == true, but received Has(pass_type):0 != true:1.] (at /paddle/paddle/fluid/framework/ir/pass.h:242)

请问如何检查解决？关闭ir_optim对速度影响应该较大。

**Comment by jiweibo** [comment]
您好，可以先规避该问题：
config.delete_pass('preln_embedding_eltwise_layernorm_fuse_pass')


请确认下该pass 是否存在注册问题 @Wangzheee

**Comment by Wangzheee** [comment]
使用没有编trt的paddle包，换一个带trt的包
https://paddle-inference.readthedocs.io/en/latest/user_guides/download_lib.html

**Comment by leiqing1** [comment]
Paddle训练框架在安装的时候，默认不带TensorRT（因为考虑很多开发者只是训练）所以如果要使用Paddle Inference的TensorRT功能，需要开发者重新下载带TensorRT的包。

**Comment by gzsvip** [comment]
> Paddle训练框架在安装的时候，默认不带TensorRT（因为考虑很多开发者只是训练）所以如果要使用Paddle Inference的TensorRT功能，需要开发者重新下载带TensorRT的包。

的确是这样，直接pip paddle是不带trt的版本，要下载专门编好带trt的预测库，或自己编译，明白 了
