### ISSUE TITLE
paddle是否有transfomers库中BertEncoder的替代api

### ISSUE THREAD

**Issue by MARKLIN1000** [PaddlePaddle/Paddle#43566]
### 请提出你的问题 Please ask your question

paddle是否有transfomers库中BertEncoder的替代api
例如 self.encoder = BertEncoder(config)

**Comment by an1018** [comment]
可以看看BertModel是否满足使用
https://github.com/PaddlePaddle/PaddleNLP/blob/07bafdc688f9da239e3c18ab4e5f48b7cbe78b94/paddlenlp/transformers/bert/modeling.py#L420
