### ISSUE TITLE
基于飞桨框架复现《动手学深度学习》书籍时出现非常多的log日志，影响美观度。

### ISSUE THREAD

**Issue by tngt** [PaddlePaddle/Paddle#43573]
### 需求描述 Feature Description

任务目标（《动手学深度学习》飞桨版 教辅项目）; <br /> 需求场景（将原书中MXNet替换为Paddle实现）;  <br /> 功能描述（如何屏蔽打印出的日志？复现李沐老师《动手学深度学习》书籍，打印出太多的log日志，对比其他框架实现，影响美观度，PR后生成的网页预览书籍详见（1-8章任意内容查看）：http://preview.d2l.ai/d2l-zh/PR-1157/chapter_preliminaries/ndarray.html）

## Paddle版本：
<img width="865" alt="image" src="https://user-images.githubusercontent.com/64118875/173988767-d86b88ee-9db4-4cd6-9c34-14ff234c03f0.png">

## Tensorflow版本：
<img width="878" alt="image" src="https://user-images.githubusercontent.com/64118875/173988796-d266b78a-95e3-4637-979e-38a323c80935.png">

## PyTorch版本：
<img width="887" alt="image" src="https://user-images.githubusercontent.com/64118875/173988830-481773e5-7cac-4fcb-a062-9eac86babb8e.png">

## MXNet版本：
<img width="873" alt="image" src="https://user-images.githubusercontent.com/64118875/173988895-7f6cfdc0-f46c-4141-8f51-3d11e0babea8.png">

## 日志内容：
/home/d2l-worker/miniconda3/envs/d2l-zh-paddle-1/lib/python3.8/site-packages/paddle/vision/transforms/functional_pil.py:36: DeprecationWarning: NEAREST is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.NEAREST or Dither.NONE instead.
  'nearest': Image.NEAREST,
/home/d2l-worker/miniconda3/envs/d2l-zh-paddle-1/lib/python3.8/site-packages/paddle/vision/transforms/functional_pil.py:37: DeprecationWarning: BILINEAR is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.BILINEAR instead.
  'bilinear': Image.BILINEAR,
/home/d2l-worker/miniconda3/envs/d2l-zh-paddle-1/lib/python3.8/site-packages/paddle/vision/transforms/functional_pil.py:38: DeprecationWarning: BICUBIC is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.BICUBIC instead.
  'bicubic': Image.BICUBIC,
/home/d2l-worker/miniconda3/envs/d2l-zh-paddle-1/lib/python3.8/site-packages/paddle/vision/transforms/functional_pil.py:39: DeprecationWarning: BOX is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.BOX instead.
  'box': Image.BOX,
/home/d2l-worker/miniconda3/envs/d2l-zh-paddle-1/lib/python3.8/site-packages/paddle/vision/transforms/functional_pil.py:40: DeprecationWarning: LANCZOS is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.LANCZOS instead.
  'lanczos': Image.LANCZOS,
/home/d2l-worker/miniconda3/envs/d2l-zh-paddle-1/lib/python3.8/site-packages/paddle/vision/transforms/functional_pil.py:41: DeprecationWarning: HAMMING is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.HAMMING instead.
  'hamming': Image.HAMMING
/home/d2l-worker/miniconda3/envs/d2l-zh-paddle-1/lib/python3.8/site-packages/paddle/fluid/framework.py:311: UserWarning: You are using GPU version Paddle, but your CUDA device is not set properly. CPU device will be used by default.
  warnings.warn(

**Comment by an1018** [comment]
和#43572 问题相同，已在#43572 issue答复
