### ISSUE TITLE
Paddle的warning日志信息太多

### ISSUE THREAD

**Issue by w5688414** [PaddlePaddle/Paddle#43572]
### bug描述 Describe the Bug

jupyter notebook运行paddle的代码，总是输出很多warning日志，怎么进行隐藏，有隐藏开关的API吗？

见pr： https://github.com/d2l-ai/d2l-zh/pull/1158

### 其他补充信息 Additional Supplementary Information

https://github.com/d2l-ai/d2l-zh/pull/1158

**Comment by an1018** [comment]
<img width="575" alt="image" src="https://user-images.githubusercontent.com/19808900/174025582-121f04c2-7267-4c74-b18f-429cad0d742d.png">
运行了 #43573 代码没有输出warning，可以查看是不是from d2l import paddle as d2l的原因

**Comment by tngt** [comment]
> 

这个只`import paddle`也出现了很多的log日志
![image](https://user-images.githubusercontent.com/64118875/174038233-fbf16014-6ff7-43b4-81f9-84c1f72152e0.png)

@an1018 @w5688414 李沐老师那边的运行情况是安装GPU的paddle，针对不需要GPU运行的程序，会自动跑在CPU上。

**Comment by SigureMo** [comment]
paddle 版本是 2.3.0-rc0 及更低版本嘛？这个 PIL 的 deprecated warning 问题在 #42307 已经解决了，并在 #42451 cherry-pick 到了 2.3.0 正式版，因此 2.3.0 不会遇到这个问题呀，如果在 2.3.0-rc0 及之下遇到问题可以试试将 Pillow 降级到 9.1.0 之下（不含 9.1.0）

另外关于隐藏的 API 的话，应该没有吧，这些 warning 是 Pillow 9.1.0 自己的 warning，Paddle 无法控制吧……也许可以找找 Pillow 的 warning 隐藏 API

**Comment by tngt** [comment]
> paddle 版本是 2.3.0-rc0 及更低版本嘛？这个 PIL 的 deprecated warning 问题在 #42307 已经解决了，并在 #42451 cherry-pick 到了 2.3.0 正式版，因此 2.3.0 不会遇到这个问题呀，如果在 2.3.0-rc0 及之下遇到问题可以试试将 Pillow 降级到 9.1.0 之下（不含 9.1.0）
> 
> 另外关于隐藏的 API 的话，应该没有吧，这些 warning 是 Pillow 9.1.0 自己的 warning，Paddle 无法控制吧……也许可以找找 Pillow 的 warning 隐藏 API

非常感谢， 升级到2.3后，PIL的日志已经解决。现在的遗留问题是：
## GPU版本的Paddle跑在CPU上打印出来的log是否可以隐藏：
<img width="773" alt="image" src="https://user-images.githubusercontent.com/64118875/174242162-e8ac5460-21fe-475d-99f9-c179f5c348da.png">

## GPU和CUDA版本的日志是否可以隐藏：
![6d9fabf27b278f3f1b3b75e6fe768fc9](https://user-images.githubusercontent.com/64118875/174242223-4037502b-1536-437b-a0ac-3b461d9e90ee.png)
@SigureMo @an1018
