### ISSUE TITLE
Paddledetection2.4 读取权重错误，其它层参数替代该层参数，set_dict 出错

### ISSUE THREAD

**Issue by a1056632260** [PaddlePaddle/Paddle#43582]
### 请提出你的问题 Please ask your question

 param_state_dict = paddle.load(weights_path)
  param_state_dict = match_state_dict(model_dict, param_state_dict)#此处参数匹配正确
  model.set_dict(param_state_dict)#此层后，模型未能正确导入参数
错误参数层：
bbox_head.0.attention.q_proj.weight
,bbox_head.1.attention.q_proj.weight,
bbox_head.2.attention.q_proj.weight
,bbox_head.3.attention.q_proj.weight,
bbox_head.4.attention.q_proj.weight
最终参数层：
bbox_head.5.attention.q_proj.weight
问题描述：model_dict与param_state_dict 是匹配的，但在set_dict之后，错误参数层的参数被最终参数层覆盖，请问这是什么问题？

**Comment by an1018** [comment]
是用的PaddleDetection DETR模型吗

**Comment by a1056632260** [comment]
> 

不是，是复现inst_query中的自注意力模块
写了个脚本把权重的键名称和模型中的统一了，但是没有正确读取，我单步调试之后，发现就是set_dict的问题

**Comment by an1018** [comment]
可以参考这个代码核对下脚本，再试试
https://aistudio.baidu.com/aistudio/projectdetail/2290729?channelType=0&channel=0
![image](https://user-images.githubusercontent.com/19808900/174029577-9e7d1e57-eb6f-4a42-8bec-1c1dc8de5c76.png)

**Comment by a1056632260** [comment]
![屏幕截图 2022-06-16 084506](https://user-images.githubusercontent.com/71133184/174031537-ca4fe52a-72aa-4ff2-807d-b6690d6f7ad1.png)
我调试过这条代码，匹配成功了，但是set_dict就出问题了

**Comment by a1056632260** [comment]
![image](https://user-images.githubusercontent.com/71133184/174055109-1d0a3ba7-43c1-4553-951c-208d75d9c1ee.png)
具体原因找到了，是因为我直接append从from_config 函数创建的head，导致我读取后面层参数时会覆盖前面层的参数，也就是说这是一层网络复制了6次。
请问要怎么创建出独立的6层head的bbox_head和mask_head？

**Comment by an1018** [comment]
如果有待解决，可以先尝试在PaddleDetection套件下提一下issue，链接：https://github.com/PaddlePaddle/PaddleDetection/issues
