### ISSUE TITLE
Paddle下如何实现SWA随机权重平均？

### ISSUE THREAD

**Issue by MARKLIN1000** [PaddlePaddle/Paddle#43583]
### 请提出你的问题 Please ask your question

这里有没有SWA相关的API，比如说AveragedModel和SWALR等，如何实现SWA

**Comment by an1018** [comment]
[ModelAverage](https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/incubate/ModelAverage_cn.html#modelaverage)可以实现在预测时使用平均后的 Parameters，通常可以提高预测的精度
