### ISSUE TITLE
关于在anaconda非base环境下安装paddlepaddle报错

### ISSUE THREAD

**Issue by scyyh11** [PaddlePaddle/Paddle#43590]
### 请提出你的问题 Please ask your question

我在anaconda非base环境下执行了官网上的安装指令
得到了如下结果
![image](https://user-images.githubusercontent.com/98971614/174043098-3d672ee4-400e-4704-beaa-1850c0385231.png)
请问我应该如何解决这一问题

**Comment by an1018** [comment]
安装命令截图看一下吧

**Comment by scyyh11** [comment]
输入的是官网上的命令
![ebc6cb0f47f7ed7acab039b82649880](https://user-images.githubusercontent.com/98971614/174218288-9d99223e-6c5d-4b26-8c56-8e7ff556708c.png)
![af025685efa769bcf1c4062c2a8c9a3](https://user-images.githubusercontent.com/98971614/174218346-3e715d33-8d44-4be7-9a04-88c805ec2641.png)

**Comment by an1018** [comment]
可以使用pip安装试试，或者再看下这个教程，更换个cuda版本试试
<img width="1288" alt="image" src="https://user-images.githubusercontent.com/19808900/174219615-ba220b0f-86eb-4949-9750-c30d47ebf329.png">
<img width="660" alt="3be40b3cdebd2f23fd15537d488cafca" src="https://user-images.githubusercontent.com/19808900/174219756-bd1be9da-3684-4382-bbab-b318615f09d5.png">
