### ISSUE TITLE
fileds numbers not same among samples in batch

### ISSUE THREAD

**Issue by Chucy2020** [PaddlePaddle/Paddle#43602]
### bug描述 Describe the Bug

![image](https://user-images.githubusercontent.com/73978694/174087156-171ab73e-4ede-49e8-a0f5-a31ed923f605.png)
为什么我这里的batch_size只能设置为1，设置其他的就会报错。

**Comment by Chucy2020** [comment]
> ### bug描述 Describe the Bug
> ![image](https://user-images.githubusercontent.com/73978694/174087156-171ab73e-4ede-49e8-a0f5-a31ed923f605.png) 为什么我这里的batch_size只能设置为1，设置其他的就会报错。
> 
> ### 其他补充信息 Additional Supplementary Information
> _No response_
上述代码是这个，请问哪里出问题了？
![image](https://user-images.githubusercontent.com/73978694/174087728-46496562-34f5-4c69-b8e3-64ede22f5a4f.png)

**Comment by Chucy2020** [comment]
> 您好，我们已经收到了您的问题，会安排技术人员尽快解答您的问题，请耐心等待。请您再次检查是否提供了清晰的问题描述、复现代码、环境&版本、报错信息等。同时，您也可以通过查看[官网API文档](https://www.paddlepaddle.org.cn/documentation/docs/zh/api_cn/index_cn.html)、[常见问题](https://www.paddlepaddle.org.cn/documentation/docs/zh/faq/index_cn.html)、[历史Issue](https://github.com/PaddlePaddle/Paddle/issues)、[AI社区](https://ai.baidu.com/forum/topic/list/168)来寻求解答。祝您生活愉快～
> 
> Hi! We've received your issue and please be patient to get responded. We will arrange technicians to answer your questions as soon as possible. Please make sure that you have posted enough message to demo your request. You may also check out the [API](https://www.paddlepaddle.org.cn/documentation/docs/zh/api_cn/index_cn.html)，[FAQ](https://www.paddlepaddle.org.cn/documentation/docs/zh/faq/index_cn.html)，[Github Issue](https://github.com/PaddlePaddle/Paddle/issues) and [AI community](https://ai.baidu.com/forum/topic/list/168) to get the answer.Have a nice day!

请问这是什么问题？

**Comment by an1018** [comment]
可以查看一下标注文件，每个样本是否相同

**Comment by Chucy2020** [comment]
> 可以查看一下标注文件，每个样本是否相同

请问我的样本每个都是一个字典，里面包括5对键值，每个键对应的值长度都不同，那么我该怎么比较方便的pad将他们处理成同一个长度？另外，我是把每个样本都append到了一个list中，请问对于这个list我要不要把他转换成mapdataset？感谢

**Comment by an1018** [comment]
请问是什么任务字典，如果方便，可以展示个截图

**Comment by Chucy2020** [comment]
> 请问是什么任务字典，如果方便，可以展示个截图

![image](https://user-images.githubusercontent.com/73978694/174266365-27070898-8f06-40ad-bed5-48a9bc3e9ebc.png)
![A~IEJL208B QW8RI7V`%RYE](https://user-images.githubusercontent.com/73978694/174266392-41ec848d-2dcd-420a-b9bd-11f1cad9f698.jpg)

第一张图是每个样本的字典，图二是n个样本。

**Comment by Chucy2020** [comment]
> 请问是什么任务字典，如果方便，可以展示个截图

![image](https://user-images.githubusercontent.com/73978694/174267133-823b21e8-dc6c-4183-a524-e4886f1de44d.png)
![image](https://user-images.githubusercontent.com/73978694/174267197-5589ab6e-172b-4d1b-bab1-803d0e5beb67.png)
下面是我的代码，运行后报错，而且无法ctrl+c暂停。

![Uploading VW6@K7QW[KS{3_97)428[VW.png…]()

**Comment by w5688414** [comment]
请提供一下示例代码和demo数据。或者使用https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/io/TensorDataset_cn.html#tensordataset
