### ISSUE TITLE
混合精度训练 Layout AutoTuning is not available问题

### ISSUE THREAD

**Issue by dlkht** [PaddlePaddle/Paddle#43627]
### 请提出你的问题 Please ask your question

混合精度训练 时出现Layout AutoTuning is not available警告，怎么样屏蔽掉

**Comment by yt605155624** [comment]
可以尝试在 python 代码开头增加如下代码
```python
import warnings
warnings.filterwarnings("ignore")
```

**Comment by dlkht** [comment]
> 可以尝试在 python 代码开头增加如下代码
> 
> ```python
> import warnings
> warnings.filterwarnings("ignore")
> ```

好像不行，那个warning是layout_autotune.cc发出的

**Comment by yt605155624** [comment]
如果一定要屏蔽 c++ 的警告，或许可以修改 c++ 代码屏蔽警告，参考 https://blog.csdn.net/leesoul_tylee/article/details/7024540 再重新编译 paddle

**Comment by dlkht** [comment]
> 如果一定要屏蔽 c++ 的警告，或许可以修改 c++ 代码屏蔽警告，参考 https://blog.csdn.net/leesoul_tylee/article/details/7024540 再重新编译 paddle

好的，谢谢！

**Comment by zhangting2020** [comment]
> > 如果一定要屏蔽 c++ 的警告，或许可以修改 c++ 代码屏蔽警告，参考 https://blog.csdn.net/leesoul_tylee/article/details/7024540 再重新编译 paddle
> 
> 好的，谢谢！

我们在该功能的日志等级上设置存在问题，后面会修复。目前可以通过环境变量，避免日志的输出
```
export GLOG_minloglevel=2
```

**Comment by thgpddl** [comment]
> > > 如果一定要屏蔽 c++ 的警告，或许可以修改 c++ 代码屏蔽警告，参考 https://blog.csdn.net/leesoul_tylee/article/details/7024540 再重新编译 paddle
> > 
> > 
> > 好的，谢谢！
> 
> 我们在该功能的日志等级上设置存在问题，后面会修复。目前可以通过环境变量，避免日志的输出
> 
> ```
> export GLOG_minloglevel=2
> ```

我在win10下使用代码：
```python
import os
os.environ['GLOG_minloglevel']='2'
```
仍然不能屏蔽
