### ISSUE TITLE
average_window_rate这个参数怎么设置啊？

### ISSUE THREAD

**Issue by MARKLIN1000** [PaddlePaddle/Paddle#43637]
### 请提出你的问题 Please ask your question

class paddle.incubate.ModelAverage(average_window_rate, parameters=None, min_average_window=10000, max_average_window=10000, name=None)

API文档没写清楚啊

**Comment by yt605155624** [comment]
可以看一下源码的 docstring https://github.com/PaddlePaddle/Paddle/blob/a072fca8229b26042fe24bff42989533e1d2050a/python/paddle/incubate/optimizer/modelaverage.py#L28
