### ISSUE TITLE
AI Studio中lightgbm使用gpu报错

### ISSUE THREAD

**Issue by xiaotingyun** [PaddlePaddle/Paddle#43647]
### 请提出你的问题 Please ask your question

x = np.random.randn(3,10)
y = np.random.randint(0,2,size=[3])
lightgbm = LGBMClassifier(device= 'gpu', gpu_platform_id=0, gpu_device_id=0)
lightgbm.fit(x,y)
![image](https://user-images.githubusercontent.com/51204375/174430092-98e53974-5f06-4a7d-9fb0-26794685da06.png)

**Comment by w5688414** [comment]
谢谢您的反馈，LGBMClassifier不属于paddle的API，是第三方的API，aistudio相关的问题请联系aistudio的相关开发人员
