### ISSUE TITLE
由mask[batch_siza,seq.length]怎么获得embeding对应的attention_mask值，并没有get_extended_attention_mask这个方法啊，请问有没有对应的API

### ISSUE THREAD

**Issue by MARKLIN1000** [PaddlePaddle/Paddle#43644]

**Comment by w5688414** [comment]
谢谢您的反馈，t5模型支持，可以参考这个来实现： https://github.com/PaddlePaddle/PaddleNLP/blob/develop/paddlenlp/transformers/t5/modeling.py

相关功能正在开发中
