### ISSUE TITLE
在AIstudio保存训练好的模型，停止项目后面重新启动项目再载入模型，发现预测效果跟之前比差得离谱

### ISSUE THREAD

**Issue by errorplayer** [PaddlePaddle/Paddle#43655]
### 请提出你的问题 Please ask your question

我训练好的模型保存好，后面载入的模型跟之前训练好的模型预测效果存在肉眼可见的离谱差别。   

模型保存代码：
`paddle.save(intent_model.state_dict(), "checkpoint/intent_model.pdparams")`           
`paddle.save(slot_model.state_dict(), "checkpoint/slot_model.pdparams")`               
`hidden_intent_model.save('checkpoint/hidden_intent_model')`
模型加载代码：
`intent_state_dict = paddle.load("checkpoint/intent_model.pdparams")`                
`slot_state_dict = paddle.load("checkpoint/slot_model.pdparams")`                    
`intent_model.set_state_dict(intent_state_dict)`                  
`slot_model.set_state_dict(slot_state_dict)`                  
`hidden_intent_model.load('checkpoint/hidden_intent_model')`                 

intent_model、slot_model用到预训练ernie和dropout层；      
hidden_intent_model用了训练好的词向量vocab_embeddings，使用
`pretrained_attr = paddle.ParamAttr(initializer=paddle.nn.initializer.Assign(vocab_embeddings),trainable=False)`   
`embedding_layer = paddle.nn.Embedding( ... ,  weight_attr=pretrained_attr)`
`sim_model = paddle.nn.Sequential(embedding_layer, ... )`
`hidden_intent_model = paddle.Model(sim_model, input_form, label_form)`     

保存和加载都没有报错，连warning都没有，但是加载之后的模型，就跟没训练过一样，预测同一个输入，结果都不一样。然后拿来继续训练，Acc那些感觉就是重头再来了。
请问有没有大佬能帮忙解答一下？是我忘记加什么参数了吗？ 

我这个是在AIStudio里面运行的ipynb, 如有需要可提供这个项目所有代码去运行复现。我每次进入项目都得重新训练一遍，好痛苦。

**Comment by Liu-xiandong** [comment]
你好，你的问题可以尝试两个思路解决。一、将优化器的参数进行保存和加载；二、再仔细看看加载的参数和保存的参数是否是一致的，可以将某一层的参数打印出来对比看是否该过程出现问题，具体的参数打印方式可以参考：
![image](https://user-images.githubusercontent.com/85323580/174609011-98d70b15-8105-4268-b527-a7bf0f4ac6ee.png)

此外，目前给出的代码较少，难以准确地判断错误。可以将最小的可复现的代码公开出来，以更好地解决问题。感谢你的提问~
