### ISSUE TITLE
CI ENV "grep: warning: GREP_OPTIONS is deprecated; please use an alias or script"

### ISSUE THREAD

**Issue by gglin001** [PaddlePaddle/Paddle#43658]
### 问题描述 Please describe your issue

使用 构建的 docker 环境, terminal 会出现

> grep: warning: GREP_OPTIONS is deprecated; please use an alias or script

来自于

https://github.com/PaddlePaddle/Paddle/blob/cf0d6027f9a2a10cdeb0eb43d863bd409a19ba2c/paddle/scripts/docker/root/.bashrc#L28

请问可以fix一下吗?

ref
https://stackoverflow.com/questions/31156517/how-to-get-rid-of-grep-warning-grep-options-is-deprecated-please-use-an-alia

**Comment by Liu-xiandong** [comment]
你好，目前这一行的打印提示是为了说明grep命令输出高亮字，并不影响程序的运行。你给出的链接已经说明了如何将其关闭。目前paddle并没有将其关闭的计划。感谢你的提问~
