### ISSUE TITLE
paddle的sparse vector相关问题

### ISSUE THREAD

**Issue by joseph-chan** [PaddlePaddle/Paddle#4365]
1.square_error_cost（其他的方法也类似）使用的input和label类型必须相同吗？可以一个为sparse_vector，一个为dense_vecotr吗？

```python
cost = paddle.layer.square_error_cost(input=predict, label=layer1)
```
2.要对一个sparse vector或者dense vector的预测结果进行排序，应当如何操作？

```python
 predict = paddle.layer.fc(input = hiddenlayer, size = input_dim, param_attr = hidden_attr,-
      bias_attr = hidden_bias, act = paddle.activation.Softmax())
```

例如要对predict的softmax结果进行排序，应该怎么操作？

**Comment by NHZlX** [comment]
第一个问题， 这里的fc predict 是dense vector， 所以label 也应该也是dense vector，第二个问题，predict 为网络输出，是一个dense vector， 排序实现应该和排序规则一致， 这个应该自己实现。
