### ISSUE TITLE
vedio编码器如何可以用与文本共享的同空间emb来处理呢？

### ISSUE THREAD

**Issue by MARKLIN1000** [PaddlePaddle/Paddle#43654]
### 请提出你的问题 Please ask your question
![image](https://user-images.githubusercontent.com/82072274/174509315-ee3bd46f-531a-4687-baaf-624868017010.png)
![image](https://user-images.githubusercontent.com/82072274/174509339-1b855486-bd2c-4482-bfa5-dd18b1874087.png)

问题一：视频特征抓取后是浮点数的特征tensor，位于[0,1]之间。如何能够映射呈int64型的tensor呢？就像经过tokenizer处理过一样，要符合BERT的输入呢？或者符合别的预训练好的embedding层模型的输入呢？
我的意愿呢是想让视频和文本这两个特征经过一样的embedding层，让 video embedding 可以或者和 text embedding一样的特征分布。或者说有哪些Embedding（vedio）可以接受浮点型的tensor？
问题二：vedio编码器如何可以用与文本共享的同空间emb来处理呢？

**Comment by Liu-xiandong** [comment]
你好，我看你这边主要是具体的算法应用问题，而不是框架运行中所产生的错误。请问你是从paddle套件中复现相关代码所产生的问题吗？
