### ISSUE TITLE
pytorch的gather算子paddle实现

### ISSUE THREAD

**Issue by jianjia93** [PaddlePaddle/Paddle#43669]
### 需求描述 Feature Description

对三维tensor在dim=3维度上进行torch.gather操作，无法直接用paddle.gather或者paddle.gather_nd实现，自己实现的替代版本速度过慢，有没有速度与pytorch一致的paddle实现版本呢？
torch.gather的功能如下：
<img width="513" alt="image" src="https://user-images.githubusercontent.com/11729328/174544570-bb8c6bf1-cfdb-4fcb-9b5f-b8e3a7e28bcd.png">

**Comment by Liu-xiandong** [comment]
你好，可以使用一下take_along_axis这个API，具体链接见：https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/take_along_axis_cn.html#take-along-axis 。
目前issue上有一个类似的问题，可以参考一下 https://github.com/PaddlePaddle/Paddle/issues/39637
