### ISSUE TITLE
cublasLt workspace size error?

### ISSUE THREAD

**Issue by MARD1NO** [PaddlePaddle/Paddle#43665]
### 请提出你的问题 Please ask your question

[size_t workspace_size = static_cast<size_t>(4) * 1024 * 1024 * 1024;](https://github.com/PaddlePaddle/Paddle/blob/a3730dc87bc61593514b830727e36e5d19e753cd/paddle/fluid/operators/fused/fused_gemm_epilogue_op.cu#L137)

maybe it is 4 * 1024 * 1024?

**Comment by Liu-xiandong** [comment]
你好，感谢你的提醒，这个地方的设置确实有误。已经通知了相关研发人员。
