### ISSUE TITLE
Set_value与Strided_slice的索引逻辑不一致

### ISSUE THREAD

**Issue by Kevin-XiongC** [PaddlePaddle/Paddle#43663]
### bug描述 Describe the Bug

Related to #43375

strided_slice和set_value这两个我理解索引逻辑应该一样的op，貌似实际处理时也不一样？如下图所示，同一个slice参数，strided_slice读了三个entry，但是set_value改写了四个entry，按照上述issue中回答的『如果start和end的值小于0，会先加上shape_size』这个逻辑ends+4会变成0，因为是左闭右开区间[3,0)，所以被修改的应该只有3,2,1三个索引？

看起来set_value的逻辑像是在stride小于0时和end<0时，就是取到0的闭区间？

![image](https://user-images.githubusercontent.com/22584786/174521481-310a089f-702e-4a11-b6d0-190211360af0.png)

**Comment by zyfncg** [comment]
经定位这是set_value的一个bug，已在[PR43694](https://github.com/PaddlePaddle/Paddle/pull/43694)中修复
