### ISSUE TITLE
class paddle.nn.Transformer中memory_mask参数怎么获得？

### ISSUE THREAD

**Issue by MARKLIN1000** [PaddlePaddle/Paddle#43707]
### 请提出你的问题 Please ask your question

class paddle.nn.Transformer中memory_mask参数怎么获得？

**Comment by wangzhen38** [comment]
可参考 https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/nn/Transformer_cn.html#forward-self-src-tgt-src-mask-none-tgt-mask-none-memory-mask-none
