### ISSUE TITLE
paddleX Linux桌面版，选择多卡，但是实际未使用多张显卡

### ISSUE THREAD

**Issue by lx1054331851** [PaddlePaddle/Paddle#43705]
### 问题描述 Please describe your issue

![image](https://user-images.githubusercontent.com/12423206/174727037-785bfe43-ecdc-4259-8bb3-f53fc9d1931a.png)

# 已经选择了4张显卡
![image](https://user-images.githubusercontent.com/12423206/174727164-45b0763d-5c30-4b72-8b3b-08cf32d04fbd.png)

# 但是实际只用了1张显卡
![image](https://user-images.githubusercontent.com/12423206/174727192-d61a4b0e-5b84-4ab2-a820-e87ff4cb787f.png)

**Comment by rightpeach** [comment]
请去paddleX github下提issue
