### ISSUE TITLE
[Feature Request] 在 OpTest 基类中自动 enable_static

### ISSUE THREAD

**Issue by tiancaishaonvjituizi** [PaddlePaddle/Paddle#43700]
### 需求描述 Feature Description

原始链接：https://github.com/PaddlePaddle/Paddle/issues/42469#issuecomment-1159341459

用户在 OpTest 测试用例里是不会调用任何 paddle op 的，paddle op 是由 OpTest 内部代码调用的，而且如上面交流里所说，这些 OpTest 内部代码又只能在静态图模式下工作。所以这样一来唯一合法的选择是在 OpTest 运行前 enable_static()、在 OpTest 运行结束后恢复原始的模式。那为什么不把这一逻辑写在 OpTest 内部呢

**Comment by Ligoml** [comment]
感谢指出，我们会考虑加入研发排期，早日解决这个问题~欢迎你持续关注
