### ISSUE TITLE
The inplace clip_ operator triggers ValueError

### ISSUE THREAD

**Issue by minogame** [PaddlePaddle/Paddle#43710]
### bug描述 Describe the Bug

如下代码所示，inplace的clip_算子叶子节点无法使用，而无下划线的版本不会影响叶子节点内的数值

```python
""" The code to represent the problem """

import paddle
print(paddle.__version__)

class Tester(paddle.nn.Layer):
    """ Operator Tester """

    def __init__(self):
        super().__init__()

        self.param_a = self.create_parameter(shape=(1,), default_initializer=paddle.nn.initializer.Constant(value=10.))
        self.add_parameter('param_a', self.param_a)
        self.param_b = self.create_parameter(shape=(1,), default_initializer=paddle.nn.initializer.Constant(value=10.))
        self.add_parameter('param_b', self.param_b)

if __name__ == '__main__':

    tester = Tester()
    sgd = paddle.optimizer.SGD(learning_rate=1.0, parameters=tester.parameters(), weight_decay=0.)
    loss = 10000.0 - tester.param_a * tester.param_b

    sgd.clear_grad()
    loss.backward()
    sgd.step()

    # Should be 20. and 20.
    print(tester.param_a.item(), tester.param_b.item())

    tester.param_a.clip(-10.0, 10.0)
    tester.param_b.clip(-10.0, 10.0)
    loss = 10000.0 - tester.param_a * tester.param_b

    sgd.clear_grad()
    loss.backward()
    sgd.step()

    # Should be 20. and 20. as well, since both a and b are cliped
    print(tester.param_a.item(), tester.param_b.item())

    tester.param_a.clip_(-10.0, 10.0) # Value error
    tester.param_b.clip_(-10.0, 10.0)
    loss = 10000.0 - tester.param_a * tester.param_b

    sgd.clear_grad()
    loss.backward()
    sgd.step()

    print(tester.param_a.item(), tester.param_b.item())
```

此段代码输出为

```
2.3.0
20.0 20.0
40.0 40.0
Traceback (most recent call last):
  File "test_clip.py", line 41, in <module>
    tester.param_a.clip_(-10.0, 10.0) # Value error
  File "/home/sunzhun/anaconda3/lib/python3.8/site-packages/decorator.py", line 231, in fun
    return caller(func, *(extras + args), **kw)
  File "/home/sunzhun/.local/lib/python3.8/site-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
    return wrapped_func(*args, **kwargs)
  File "/home/sunzhun/.local/lib/python3.8/site-packages/paddle/fluid/dygraph/inplace_utils.py", line 34, in __impl__
    return func(*args, **kwargs)
  File "/home/sunzhun/.local/lib/python3.8/site-packages/paddle/tensor/math.py", line 2430, in clip_
    return _C_ops.clip_(x, "min", min, "max", max)
ValueError: (InvalidArgument) Leaf Var (tester_0.w_0) that doesn't stop gradient can't use inplace strategy.
  [Hint: Expected X->IsLeaf() && !X->OverridedStopGradient() == false, but received X->IsLeaf() && !X->OverridedStopGradient():1 != false:0.] (at /paddle/paddle/fluid/pybind/op_function_impl.h:15865)
```

### 其他补充信息 Additional Supplementary Information

参考此处代码，不能按照预设逻辑工作
https://github.com/PaddlePaddle/PASSL/blob/main/passl/modeling/backbones/clip.py#L316-L337

**Comment by wangzhen38** [comment]
感谢反馈，稍等我复现下问题

**Comment by wangzhen38** [comment]
> ### bug描述 Describe the Bug
> 如下代码所示，inplace的clip_算子叶子节点无法使用，而无下划线的版本不会影响叶子节点内的数值
> 
> ```python
> """ The code to represent the problem """
> 
> import paddle
> print(paddle.__version__)
> 
> class Tester(paddle.nn.Layer):
>     """ Operator Tester """
> 
>     def __init__(self):
>         super().__init__()
> 
>         self.param_a = self.create_parameter(shape=(1,), default_initializer=paddle.nn.initializer.Constant(value=10.))
>         self.add_parameter('param_a', self.param_a)
>         self.param_b = self.create_parameter(shape=(1,), default_initializer=paddle.nn.initializer.Constant(value=10.))
>         self.add_parameter('param_b', self.param_b)
> 
> if __name__ == '__main__':
> 
>     tester = Tester()
>     sgd = paddle.optimizer.SGD(learning_rate=1.0, parameters=tester.parameters(), weight_decay=0.)
>     loss = 10000.0 - tester.param_a * tester.param_b
> 
>     sgd.clear_grad()
>     loss.backward()
>     sgd.step()
> 
>     # Should be 20. and 20.
>     print(tester.param_a.item(), tester.param_b.item())
> 
>     tester.param_a.clip(-10.0, 10.0)
>     tester.param_b.clip(-10.0, 10.0)
>     loss = 10000.0 - tester.param_a * tester.param_b
> 
>     sgd.clear_grad()
>     loss.backward()
>     sgd.step()
> 
>     # Should be 20. and 20. as well, since both a and b are cliped
>     print(tester.param_a.item(), tester.param_b.item())
> 
>     tester.param_a.clip_(-10.0, 10.0) # Value error
>     tester.param_b.clip_(-10.0, 10.0)
>     loss = 10000.0 - tester.param_a * tester.param_b
> 
>     sgd.clear_grad()
>     loss.backward()
>     sgd.step()
> 
>     print(tester.param_a.item(), tester.param_b.item())
> ```
> 
> 此段代码输出为
> 
> ```
> 2.3.0
> 20.0 20.0
> 40.0 40.0
> Traceback (most recent call last):
>   File "test_clip.py", line 41, in <module>
>     tester.param_a.clip_(-10.0, 10.0) # Value error
>   File "/home/sunzhun/anaconda3/lib/python3.8/site-packages/decorator.py", line 231, in fun
>     return caller(func, *(extras + args), **kw)
>   File "/home/sunzhun/.local/lib/python3.8/site-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
>     return wrapped_func(*args, **kwargs)
>   File "/home/sunzhun/.local/lib/python3.8/site-packages/paddle/fluid/dygraph/inplace_utils.py", line 34, in __impl__
>     return func(*args, **kwargs)
>   File "/home/sunzhun/.local/lib/python3.8/site-packages/paddle/tensor/math.py", line 2430, in clip_
>     return _C_ops.clip_(x, "min", min, "max", max)
> ValueError: (InvalidArgument) Leaf Var (tester_0.w_0) that doesn't stop gradient can't use inplace strategy.
>   [Hint: Expected X->IsLeaf() && !X->OverridedStopGradient() == false, but received X->IsLeaf() && !X->OverridedStopGradient():1 != false:0.] (at /paddle/paddle/fluid/pybind/op_function_impl.h:15865)
> ```
> 
> ### 其他补充信息 Additional Supplementary Information
> 参考此处代码，不能按照预设逻辑工作 https://github.com/PaddlePaddle/PASSL/blob/main/passl/modeling/backbones/clip.py#L316-L337

使用inplace不能有梯度，需要把tester.param_a和tester.param_b的stop_gradient设置为True

**Comment by minogame** [comment]
@wangzhen38 @Ligoml 二位有认真看我的问题描述吗？

请参考贵司发布的PASSL框架的此处代码，没有按照预设逻辑工作，
logit_scale是一个可以接受梯度用以训练的参数，但是其在超过一个范围之内要被clip，
stop_gradient设置为True要如何去训练这个参数？

https://github.com/PaddlePaddle/PASSL/blob/main/passl/modeling/backbones/clip.py#L316-L337
