### ISSUE TITLE
paddle里LBFGS的使用问题

### ISSUE THREAD

**Issue by whaleprince** [PaddlePaddle/Paddle#43718]
### 请提出你的问题 Please ask your question

采用paddle.incubate.optimizer.functional.minimize_lbfgs进行网络训练时，需要提供一个函数func和参数，采用二阶优化方式进行训练的时候，看文档的意思是，损失函数得定义成网络参数的表达式，这怎么实现？

我这里采用闭包定义了一个损失函数，但是训练的时候会报错，请问这个具体该怎么实现？

def train_batch(x, model, loss, weight, optimizer, log_loss, lambda_Re, lambda_Im,):
    optimizer.clear_grad()
    def clouser():
        h = model.feature_transform(x)
        w = model(h)
        f, t = model.output_transform(x, w)
        res = model.pde_(x, h, w, t, f)
        opt = model.optim_func(f[:4800], f[:4800])
        eqs_loss1 = loss(res[4800:, :1], paddle.zeros_like(res[4800:, :1], dtype='float32'))
        eqs_loss2 = loss(res[4800:, 1:], paddle.zeros_like(res[4800:, 1:], dtype='float32'))
        lag_loss1 = paddle.mean(res[4800:, :1] * lambda_Re)
        lag_loss2 = paddle.mean(res[4800:, 1:] * lambda_Im)
        opt_loss = loss(opt, paddle.zeros_like(opt, dtype='float32'))
        loss_batch = weight[0] * eqs_loss1 + weight[1] * eqs_loss2 + weight[2] * lag_loss1 + weight[3] * lag_loss2 + weight[4] * opt_loss
        log_loss.append([eqs_loss1.item(), eqs_loss2.item(), lag_loss1.item(), lag_loss2.item(), opt_loss.item(),
                         loss_batch.item()])
        return loss_batch
    loss_batch =clouser()
    loss_batch.backward()
    paddle.incubate.optimizer.functional.minimize_lbfgs(clouser, model.parameters())

报错为：
paddle.incubate.optimizer.functional.minimize_lbfgs(clouser, model.parameters()[0][0])
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 3444, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-3-73698d2b5baa>", line 1, in <module>
    paddle.incubate.optimizer.functional.minimize_lbfgs(clouser, model.parameters()[0][0])
  File "C:\ProgramData\Anaconda3\lib\site-packages\paddle\incubate\optimizer\functional\lbfgs.py", line 110, in minimize_lbfgs
    value, g1 = _value_and_gradient(objective_func, xk)
  File "C:\ProgramData\Anaconda3\lib\site-packages\paddle\incubate\optimizer\functional\utils.py", line 92, in _value_and_gradient
    value = f(x)
TypeError: clouser() takes 0 positional arguments but 1 was given

**Comment by wangzhen38** [comment]
请稍等，已联系该接口负责同学

**Comment by rightpeach** [comment]
请去PaddleScience github 下提issue
