### ISSUE TITLE
FLAGS_use_system_allocator not working in an int8 test

### ISSUE THREAD

**Issue by sfraczek** [PaddlePaddle/Paddle#43731]
FLAGS_use_system_allocator doesn't work in a test below:
```bash
export FLAGS_use_system_allocator=true
/mnt/drive/PaddlePaddle/Paddle/build/paddle/fluid/inference/tests/api/test_analyzer_int8_image_classification \
        "--infer_model=/mnt/drive/PaddlePaddle/Paddle/build/third_party/inference_demo/int8v2/resnet50/model" \
        "--infer_data=/mnt/drive/PaddlePaddle/Paddle/build/third_party/inference_demo/imagenet/data.bin" "--warmup_batch_size=1" \
        "--warmup_iters=1" "--batch_size=1" "--enable_int8=true" "--cpu_num_threads=1" "--iterations=1"
```
I have also tried to pass this gflag as --use_system_allocator=true, --use_system_allocator=1, and FLAGS_use_system_allocator=1
Is this a bug or is this expected?

**Comment by yeliang2258** [comment]
The source code corresponding to test_analyzer_int8_image_classification is https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/fluid/inference/tests/api/analyzer_int8_image_classification_tester.cc，the use_system_allocator configuration is not used in the source code, so it does not take effect.

**Comment by yeliang2258** [comment]
What is this configuration used for? Where did you see this configuration?

**Comment by yeliang2258** [comment]
Also, what are the results you expect? and what is the actual result?
