### ISSUE TITLE
华为云的鲲鹏arm服务器编译报错

### ISSUE THREAD

**Issue by yangy996** [PaddlePaddle/Paddle#43737]
### bug描述 Describe the Bug

华为云的鲲鹏arm服务器，编译PaddlePaddle到一半报错：

[ 47%] Linking CXX static library libunsqueeze_op.a
[ 47%] Built target unsqueeze_op
Scanning dependencies of target lu_unpack_op
[ 47%] Building CXX object paddle/fluid/operators/CMakeFiles/lu_unpack_op.dir/lu_unpack_op.cc.o
In file included from /root/OCR/paddlepaddle/Paddle/paddle/fluid/operators/memcpy_h2d_op.cc:12:0:
/root/OCR/paddlepaddle/Paddle/paddle/fluid/operators/memcpy_h2d_op.h: In member function ‘void paddle::operators::MemcpyH2DFunctor::operator()(const LoDTensor&) const’:
/root/OCR/paddlepaddle/Paddle/paddle/fluid/operators/memcpy_h2d_op.h:46:10: error: variable ‘stream’ set but not used [-Werror=unused-but-set-variable]
     auto stream = nullptr;
          ^~~~~~
cc1plus: all warnings being treated as errors
make[2]: *** [paddle/fluid/operators/CMakeFiles/memcpy_h2d_op.dir/build.make:66: paddle/fluid/operators/CMakeFiles/memcpy_h2d_op.dir/memcpy_h2d_op.cc.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:237961: paddle/fluid/operators/CMakeFiles/memcpy_h2d_op.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 47%] Linking CXX static library libsample_logits_op.a
[ 47%] Built target sample_logits_op
[ 47%] Linking CXX static library liblabel_smooth_op.a
[ 47%] Built target label_smooth_op
[ 47%] Linking CXX static library liblu_unpack_op.a
[ 47%] Built target lu_unpack_op
make: *** [Makefile:133: all] Error 2

**Comment by yangy996** [comment]
版本是release/2.3的分支

**Comment by yangy996** [comment]
编译release/2.2的分支版本正常，但是release/2.3的分支就报上面的错误

**Comment by wangzhen38** [comment]
感谢反馈，请发一下编包命令，及描述下编包环境，我这边先复现下

**Comment by yangy996** [comment]
编译命令就是官网提供的
https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/install/compile/arm-compile.html
系统环境
![image](https://user-images.githubusercontent.com/15188456/174934118-77385e48-75d2-49bd-99bb-b591f5c030bf.png)

**Comment by qili93** [comment]
请参考这个文档进行编译，CMAKE的时候加上 `-DCMAKE_CXX_FLAGS="-Wno-error -w"` 的编译选项

https://github.com/PaddlePaddle/Paddle-Inference-Demo/blob/master/docs-official/guides/hardware_support/cpu_phytium_cn.md
