### ISSUE TITLE
预训练的词向量模型能否往里面添加词

### ISSUE THREAD

**Issue by HaoRan98** [PaddlePaddle/Paddle#43755]
### 请提出你的问题 Please ask your question

词向量模型 w2v.baidu_encyclopedia.target.word-word.dim300 可以自己再往里面添加数据么，如果可以，有没有实例可以参考下

**Comment by 1649759610** [comment]
训练时可以加载额外的词表，通过extended_vocab_path进行指定：
self.embedder = TokenEmbedding(args.embedding_name, extended_vocab_path=vocab_path)

可参考以下例子：
https://github.com/PaddlePaddle/PaddleNLP/tree/develop/examples/word_embedding
