### ISSUE TITLE
怎么把静态图的权重参数转成动态图的权重参数？

### ISSUE THREAD

**Issue by IamMegatron2025** [PaddlePaddle/Paddle#43759]
### 请提出你的问题 Please ask your question

您好， 我有个权重参数，是用老版本paddle（可能是1.6）的静态图训练的，现在想用转成新版本paddle动态图的权重参数，有相关文档吗？期待回复。

**Comment by haohongxiang** [comment]
@IvyGongoogle 可以参考下PaddleNLP的模型转换脚本，主要是参数名称的映射。

https://github.com/PaddlePaddle/PaddleNLP/blob/develop/paddlenlp/transformers/ernie/static_to_dygraph_params/match_static_to_dygraph.py
