### ISSUE TITLE
macOS通过pip安装paddlepaddle，在用import测试时报错

### ISSUE THREAD

**Issue by yz-tang** [PaddlePaddle/Paddle#43773]
### 问题描述 Issue Description

pip安装完成之后，进行import测试时，报下面的错误
![image](https://user-images.githubusercontent.com/62792991/175045093-5a6d540f-1ae6-4bf2-8e36-d698254acd9f.png)

在执行summary_env.py程序时，也报同样的错误

### 版本&环境信息 Version & Environment Information

1.PaddlePaddle版本：2.3.0
2.CPU：mac M1 
4.系统环境：Mac OS 12.4

**Comment by XYZ-916** [comment]
你好，貌似是gflags反复安装的问题。请尝试删除gflags再安装paddle。

**Comment by yz-tang** [comment]
请您仔细看下截图里报的gflags冲突的两个路径。  
/Users/paddle/work/**_pengyuqi_**/Paddle/build_py39/third_party/gflags/src/extern_gflags/src/gflags.cc 和   
/tmp/gflags-20211021-3963-1mi18ai/gflags-2.2.2/src/gflags.cc 。  
这两个路径在我电脑上根本不存在  
我加粗的那个用户名：pengyuqi，这个好像是个人名吧？  
在我自己电脑上安装，怎么报错路径里有别人的名字呢？

**Comment by XYZ-916** [comment]
> 请您仔细看下截图里报的gflags冲突的两个路径。 /Users/paddle/work/**_pengyuqi_**/Paddle/build_py39/third_party/gflags/src/extern_gflags/src/gflags.cc 和 /tmp/gflags-20211021-3963-1mi18ai/gflags-2.2.2/src/gflags.cc 。 这两个路径在我电脑上根本不存在 我加粗的那个用户名：pengyuqi，这个好像是个人名吧？ 在我自己电脑上安装，怎么报错路径里有别人的名字呢？

试下卸载gflags和glog，看看还有没有问题。

**Comment by ProfFan** [comment]
这个显然是打包的问题啊，你们 macOS 打包有没有 QA 啊。。。

**Comment by haohongxiang** [comment]
@ProfFan QA在非编包机器上验证过是没问题的，应该是您的环境额外安装了gflags的原因，gflags冲突是会把编译路径打出来，您这里显示的路径是编译路径。请尝试卸载gflags再安装

**Comment by ProfFan** [comment]
这个就是打包的问题啊，你们 gflags 怎么会来找我环境里面的 gflags 呢。。。 visibility 不对吧

**Comment by ltto** [comment]
我靠 这问题1年了没有解决吗

**Comment by ltto** [comment]
ERROR: flag 'flagfile' was defined more than once (in files '/Users/paddle/xly/workspace/94c89ea5-dd6a-4076-a2b5-377691fe0b69/Paddle/build/third_party/gflags/src/extern_gflags/src/gflags.cc' and '/tmp/gflags-20211021-3963-1mi18ai/gflags-2.2.2/src/gflags.cc').吐了

**Comment by ltto** [comment]
![image](https://user-images.githubusercontent.com/24884691/222648415-3fe43d4d-db00-4ef8-bbf2-ef371e3341db.png)

**Comment by ProfFan** [comment]
> 我靠 这问题1年了没有解决吗

LOL 悲

**Comment by ltto** [comment]
还没有解决吐了

**Comment by kalixim** [comment]
MACOS，python3.8安装paddlepaddle==2.3.0，paddlehub==2.3.0，导入 paddle时无任何问题，但导入paddlehub时出错：
ERROR: flag 'help' was defined more than once (in files '/home/Paddle/build.noavx/third_party/gflags/src/extern_gflags/src/gflags_reporting.cc' and '/opt/concourse/worker/volumes/live/5ce6f7d8-5bf2-4e48-7a02-c2331fea922e/volume/gflags_1542388463840/work/src/gflags_reporting.cc').

**Comment by yz-tang** [comment]
拥抱pytorch去了，暂时关闭该问题。
