### ISSUE TITLE
可以通过paddle.save把句向量tensor保存到txt文件中吗？

### ISSUE THREAD

**Issue by wjddd** [PaddlePaddle/Paddle#43786]
### 请提出你的问题 Please ask your question

例如保存为{sentence: tensor}的形式？

**Comment by XYZ-916** [comment]
您好，paddle.save可以保存Tensor，具体保存了它的名字和数值，没有保存stop_gradient等属性。paddle.save 的输入参数 path 将直接作为存储结果的文件名而非前缀，所以是可以保存成txt文件的。具体API见https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/save_cn.html#save。

**Comment by wjddd** [comment]
> 您好，paddle.save可以保存Tensor，具体保存了它的名字和数值，没有保存stop_gradient等属性。paddle.save 的输入参数 path 将直接作为存储结果的文件名而非前缀，所以是可以保存成txt文件的。具体API见[https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/save_cn.html#save。](https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/save_cn.html#save%E3%80%82)

可以在保存Tensor的同时保存对应的句子吗？

**Comment by XYZ-916** [comment]
> 

你可以保存完Tensor后读取对应的txt文件，再把对应的句子写入文件即可。

**Comment by wjddd** [comment]
> > 
> 
> 你可以保存完Tensor后读取对应的txt文件，再把对应的句子写入文件即可。

这是个方法，但读写操作会增加推理时间……

**Comment by XYZ-916** [comment]
> > > 
> > 
> > 
> > 你可以保存完Tensor后读取对应的txt文件，再把对应的句子写入文件即可。
> 
> 这是个方法，但读写操作会增加推理时间……

那可能就没有其他办法在保存Tensor的同时保存对应的句子了，因为Tensor保存不支持自定义。

**Comment by wjddd** [comment]
> > > > 
> > > 
> > > 
> > > 你可以保存完Tensor后读取对应的txt文件，再把对应的句子写入文件即可。
> > 
> > 
> > 这是个方法，但读写操作会增加推理时间……
> 
> 那可能就没有其他办法在保存Tensor的同时保存对应的句子了，因为Tensor保存不支持自定义。

感谢感谢，问题已经解决了，这种情况下直接转换为list保存可能更符合我的需求~
