### ISSUE TITLE
动转静模型i保存nference模型用于部署

### ISSUE THREAD

**Issue by fan-min-97** [PaddlePaddle/Paddle#43795]
### 请提出你的问题 Please ask your question

```python
# save inference model
from paddle.static import InputSpec
# 加载训练好的模型参数
state_dict = paddle.load("./mnist.pdparams")
# 将训练好的参数读取到网络中
model.set_state_dict(state_dict)
# 设置模型为评估模式
model.eval()

# 保存inference模型
paddle.jit.save(
    layer=model,
    path="inference/mnist",
    input_spec=[InputSpec(shape=[None, 784], dtype='float32')])

print("==>Inference model saved in inference/mnist.")
```

在动态转静态时， input_spec=[InputSpec(shape=[None, 784], dtype='float32')]) ，总是报错，写成这样的报错是需要4-5个dimension写成 input_spec=[InputSpec(shape=[None, 3,60,640], dtype='float32')])，显示float需要的的是str或者number，而不是list。请问这个地方怎么写呢？

**Comment by Aurelius84** [comment]
可否提供下你的model.forward 函数签名？

**Comment by fan-min-97** [comment]
class&nbsp;Model(nn.Layer):
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;__init__(self,&nbsp;cfg='yolov5s.yaml',&nbsp;ch=3,&nbsp;nc=None,&nbsp;anchors=None,&nbsp;mode='training'):&nbsp;&nbsp;#&nbsp;model,&nbsp;input&nbsp;channels,&nbsp;number&nbsp;of&nbsp;classes
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;super().__init__()
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;isinstance(cfg,&nbsp;dict):
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self.yaml&nbsp;=&nbsp;cfg&nbsp;&nbsp;#&nbsp;model&nbsp;dict
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;else:&nbsp;&nbsp;#&nbsp;is&nbsp;*.yaml
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;import&nbsp;yaml&nbsp;&nbsp;#&nbsp;for&nbsp;paddle&nbsp;hub
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self.yaml_file&nbsp;=&nbsp;Path(cfg).name
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;with&nbsp;open(cfg,&nbsp;errors='ignore')&nbsp;as&nbsp;f:
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self.yaml&nbsp;=&nbsp;yaml.safe_load(f)&nbsp;&nbsp;#&nbsp;model&nbsp;dict

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;Define&nbsp;model
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;ch&nbsp;=&nbsp;self.yaml['ch']&nbsp;=&nbsp;self.yaml.get('ch',&nbsp;ch)&nbsp;&nbsp;#&nbsp;input&nbsp;channels
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;nc&nbsp;and&nbsp;nc&nbsp;!=&nbsp;self.yaml['nc']:
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;print(f"Overriding&nbsp;model.yaml&nbsp;nc={self.yaml['nc']}&nbsp;with&nbsp;nc={nc}")
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self.yaml['nc']&nbsp;=&nbsp;nc&nbsp;&nbsp;#&nbsp;override&nbsp;yaml&nbsp;value
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;anchors:
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;print(f'Overriding&nbsp;model.yaml&nbsp;anchors&nbsp;with&nbsp;anchors={anchors}')
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self.yaml['anchors']&nbsp;=&nbsp;round(anchors)&nbsp;&nbsp;#&nbsp;override&nbsp;yaml&nbsp;value
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self.model,&nbsp;self.save&nbsp;=&nbsp;parse_model(deepcopy(self.yaml),&nbsp;ch=[ch],&nbsp;mode=mode)&nbsp;&nbsp;#&nbsp;model,&nbsp;savelist
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self.names&nbsp;=&nbsp;[str(i)&nbsp;for&nbsp;i&nbsp;in&nbsp;range(self.yaml['nc'])]&nbsp;&nbsp;#&nbsp;default&nbsp;names
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self.inplace&nbsp;=&nbsp;self.yaml.get('inplace',&nbsp;True)

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;Build&nbsp;strides,&nbsp;anchors
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;m&nbsp;=&nbsp;self.model[-1]&nbsp;&nbsp;#&nbsp;Detect()
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;isinstance(m,&nbsp;Detect):
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;s&nbsp;=&nbsp;256&nbsp;&nbsp;#&nbsp;2x&nbsp;min&nbsp;stride
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;m.inplace&nbsp;=&nbsp;self.inplace
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;m.stride&nbsp;=&nbsp;paddle.to_tensor([s&nbsp;/&nbsp;x.shape[-2]&nbsp;for&nbsp;x&nbsp;in&nbsp;self.forward(paddle.zeros([1,&nbsp;ch,&nbsp;s,&nbsp;s]))])&nbsp;&nbsp;#&nbsp;forward
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;m.anchors&nbsp;/=&nbsp;m.stride.reshape([-1,&nbsp;1,&nbsp;1])
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;check_anchor_order(m)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self.stride&nbsp;=&nbsp;m.stride
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self._initialize_biases()&nbsp;&nbsp;#&nbsp;only&nbsp;run&nbsp;once

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;Init&nbsp;weights,&nbsp;biases
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;initialize_weights(self)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self.info()
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;print('')


def&nbsp;forward(self,&nbsp;x,&nbsp;augment=False,&nbsp;profile=False,&nbsp;visualize=False):
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;augment:
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;self._forward_augment(x)&nbsp;&nbsp;#&nbsp;augmented&nbsp;inference,&nbsp;None
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;self._forward_once(x,&nbsp;profile,&nbsp;visualize)&nbsp;&nbsp;#&nbsp;single-scale&nbsp;inference,&nbsp;train

&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;_forward_augment(self,&nbsp;x):
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;img_size&nbsp;=&nbsp;x.shape[-2:]&nbsp;&nbsp;#&nbsp;height,&nbsp;width
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;s&nbsp;=&nbsp;[1,&nbsp;0.83,&nbsp;0.67]&nbsp;&nbsp;#&nbsp;scales
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;f&nbsp;=&nbsp;[None,&nbsp;3,&nbsp;None]&nbsp;&nbsp;#&nbsp;flips&nbsp;(2-ud,&nbsp;3-lr)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;y&nbsp;=&nbsp;[]&nbsp;&nbsp;#&nbsp;outputs
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;for&nbsp;si,&nbsp;fi&nbsp;in&nbsp;zip(s,&nbsp;f):
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;xi&nbsp;=&nbsp;scale_img(x.flip(fi)&nbsp;if&nbsp;fi&nbsp;else&nbsp;x,&nbsp;si,&nbsp;gs=int(self.stride.max()))
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;yi&nbsp;=&nbsp;self._forward_once(xi)[0]&nbsp;&nbsp;#&nbsp;forward
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;cv2.imwrite(f'img_{si}.jpg',&nbsp;255&nbsp;*&nbsp;xi[0].cpu().numpy().transpose((1,&nbsp;2,&nbsp;0))[:,&nbsp;:,&nbsp;::-1])&nbsp;&nbsp;#&nbsp;save
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;yi&nbsp;=&nbsp;self._descale_pred(yi,&nbsp;fi,&nbsp;si,&nbsp;img_size)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;y.append(yi)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;y&nbsp;=&nbsp;self._clip_augmented(y)&nbsp;&nbsp;#&nbsp;clip&nbsp;augmented&nbsp;tails
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;paddle.concat(y,&nbsp;1),&nbsp;None&nbsp;&nbsp;#&nbsp;augmented&nbsp;inference,&nbsp;train

&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;_forward_once(self,&nbsp;x,&nbsp;profile=False,&nbsp;visualize=False):
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;y,&nbsp;dt&nbsp;=&nbsp;[],&nbsp;[]&nbsp;&nbsp;#&nbsp;outputs
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;for&nbsp;m&nbsp;in&nbsp;self.model:
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;m.f&nbsp;!=&nbsp;-1:&nbsp;&nbsp;#&nbsp;if&nbsp;not&nbsp;from&nbsp;previous&nbsp;layer
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;x&nbsp;=&nbsp;y[m.f]&nbsp;if&nbsp;isinstance(m.f,&nbsp;int)&nbsp;else&nbsp;[x&nbsp;if&nbsp;j&nbsp;==&nbsp;-1&nbsp;else&nbsp;y[j]&nbsp;for&nbsp;j&nbsp;in&nbsp;m.f]&nbsp;&nbsp;#&nbsp;from&nbsp;earlier&nbsp;layers
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;profile:
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self._profile_one_layer(m,&nbsp;x,&nbsp;dt)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;x&nbsp;=&nbsp;m(x)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;y.append(x&nbsp;if&nbsp;m.i&nbsp;in&nbsp;self.save&nbsp;else&nbsp;None)&nbsp;&nbsp;#&nbsp;save&nbsp;output
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;visualize:
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;feature_visualization(x,&nbsp;m.type,&nbsp;m.i,&nbsp;save_dir=visualize)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;x










-------------------------------------
以上是class Model中的函数，动态转静态paddle.jit.save
input_spec=([InputSpec(shape=[None,3,608,608],&nbsp;dtype='float32',name='input')])

paddle.jit.save(
&nbsp;&nbsp;&nbsp;&nbsp;layer=model,
&nbsp;&nbsp;&nbsp;&nbsp;path="inference",
&nbsp;&nbsp;&nbsp;&nbsp;input_spec=[input])

总是报错，求回复咋改哦



------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/Paddle"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年6月24日(星期五) 上午10:14
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PaddlePaddle/Paddle] 动转静模型i保存nference模型用于部署 (Issue #43795)





 
可否提供下你的model.forward 函数签名？

**Comment by Aurelius84** [comment]
抱歉，上面的代码似乎是乱码的，可否重贴一下？另外，请问你在训练时输入的Tensor的shape是什么样的？
