### ISSUE TITLE
Difference between paddle layernorm and pytorch layernorm

### ISSUE THREAD

**Issue by Kunlun-Zhu** [PaddlePaddle/Paddle#43790]
### 请提出你的问题 Please ask your question

Hi, we tried using this layernorm in this[ file](https://github.com/PaddlePaddle/Research/blob/master/KG/CoKE/bin/model/transformer_encoder.py)

and we didn't get the same results as the layernorm function in pytorch.

Could you have a brief look on this, thanks a lot.

**Comment by XYZ-916** [comment]
您好。paddle实现的layernorm和pytorch实现是有些区别的，但是精度可以对齐到1e-5级别。您这边如果结果相差很多的话，能否提供下测试用例，我们这边详细看下，谢谢～

**Comment by XYZ-916** [comment]
https://github.com/PaddlePaddle/Research/blob/master/KG/CoKE/bin/model/transformer_encoder.py这个文件里面的layer_norm实现不是Paddle框架里的实现，而且是19年比较老的版本了。Paddle框架实现请参考：https://github.com/PaddlePaddle/Paddle/blob/release/2.3/python/paddle/nn/layer/norm.py#L439

**Comment by Kunlun-Zhu** [comment]
Thanks for the responding. I need to remake this research with pytorch and this is the part where I meet problem. The layer_norm in this project is very different which leads to this question.
