### ISSUE TITLE
pip安装paddlepaddle失败

### ISSUE THREAD

**Issue by EchoCX** [PaddlePaddle/Paddle#4380]
执行命令：`pip install paddlepaddle`
python version : 2.7
报错如下：

```bash
Collecting paddlepaddle
  Could not find a version that satisfies the requirement paddlepaddle (from versions: )
No matching distribution found for paddlepaddle
```

**Comment by Yancey1989** [comment]
Please execute `python -c "import pip; print(pip.pep425tags.get_supported())"` to check the pip supports for your Python environment.

**Comment by wangzhenhui1991** [comment]
[('cp27', 'cp27m', 'win_amd64'), ('cp27', 'none', 'win_amd64'), ('py2', 'none', 'win_amd64'), ('cp27', 'none', 'any'), ('cp2', 'none', 'any'), ('py27', 'none', 'any'), ('py2', 'none', 'any'), ('py26', 'none', 'any'), ('py25', 'none', 'any'), ('py24', 'none', 'any'), ('py23', 'none', 'any'), ('py22', 'none', 'any'), ('py21', 'none', 'any'), ('py20', 'none', 'any')]

**Comment by wangzhenhui1991** [comment]
and ?

**Comment by Yancey1989** [comment]
Hi, PaddlePaddle cannot be installed on Win for now, Linux and Mac OSX are suitable. If you want to run PaddlePaddle on Win, Docker is a good choice.

referance linkes:
- pip install PaddlePaddle: http://paddlepaddle.org/docs/develop/documentation/zh/getstarted/build_and_install/pip_install_cn.html#pip-dependency
 - Docker run PaddlePaddle: http://paddlepaddle.org/docs/develop/documentation/zh/getstarted/build_and_install/docker_install_cn.html

**Comment by Yancey1989** [comment]
Close the inactivate issue.
