### ISSUE TITLE
Enable MKLDNN is slower than native cpu

### ISSUE THREAD

**Issue by heliqi** [PaddlePaddle/Paddle#43817]
### bug描述 Describe the Bug

When vivo model use inference，  enable mkldnn is slower than native cpu.

**Comment by heliqi** [comment]
@lidanqing-intel  @yaomichael

**Comment by jakpiase** [comment]
Hi, the oneDNN's performance of this model should be fixed after merging #43803

**Comment by yaomichael** [comment]
@jakpiase surprisingly, @heliqi found with another input dataset, even with #43803, performance is same as native.

**Comment by heliqi** [comment]
The results of the previous tests:
<img width="681" alt="image" src="https://user-images.githubusercontent.com/34152981/182062916-6e708ac6-3464-4ad7-bb44-b6d61d1753f1.png">

another input dataset(smaller):

Native Paddle | OneDNN after 43803 PR
-- | --
33ms | 33ms

**Comment by jakpiase** [comment]
Hi, VIVO performance for the new dataset should be better after #45091 and after appending these two lines inside "demo.cpp" file right before creating predictor from config:
```
  config.pass_builder()->AppendPass("fc_mkldnn_pass");
  config.pass_builder()->AppendPass("fc_act_mkldnn_fuse_pass");
```

**Comment by yaomichael** [comment]
@jakpiase thanks! is #44863 still needed for best result?

**Comment by heliqi** [comment]
@jakpiase  thanks! I'll test your PR and get back to you.

**Comment by jakpiase** [comment]
@yaomichael, from what I have tested, performance with and without #44863 should be the same

**Comment by heliqi** [comment]
@yaomichael  @jakpiase 
older input dataset
Native Paddle | OneDNN after 43803 PR | OneDNN after 45091  PR
-- | -- | -- 
130ms | 73ms | 67ms 

new input dataset(smaller):

Native Paddle | OneDNN after 43803 PR | OneDNN after 45091  PR
-- | -- | -- 
33ms | 33ms | 19ms

**Comment by yaomichael** [comment]
@heliqi can you close this issue? we are not following up on this.
@onecatcn @qingqing01
