### ISSUE TITLE
RuntimeError: could not create a primitive descriptor for a reorder primitive when inference with MKLDNN

### ISSUE THREAD

**Issue by yeliang2258** [PaddlePaddle/Paddle#43811]
### bug描述 Describe the Bug

When inference with MKLDNN on CPU, report the following error:
RuntimeError: could not create a primitive descriptor for a reorder primitive when inference with MKLDNN.
![image](https://user-images.githubusercontent.com/30516196/175459243-296c5f35-b2d0-4a07-a5c7-33a78c060bbb.png)

My model and script: 
[bug_report.tar.gz](https://github.com/PaddlePaddle/Paddle/files/8973024/bug_report.tar.gz)

Run the following command to reproduce the problem：
python test.py

**Comment by lidanqing-vv** [comment]
Update: Co-work with @yeliang2258 and found it is because conv+residual, the residual add did not support broadcast. Now Yeliang is referring to elementwise_add wth broadcast in `elementwise_mkldnn_kernel.h` to add conv+residual_add broadcast support.

**Comment by yaomichael** [comment]
@yeliang2258 are you going to implement broadcast support for conv+residual fuse?

**Comment by yeliang2258** [comment]
> e you going to implement broadcast support for conv+residual fuse?

Yes. I will try to fix this

**Comment by yeliang2258** [comment]
https://github.com/PaddlePaddle/Paddle/pull/44867

**Comment by yaomichael** [comment]
@yeliang2258 can you close it out?
@onecatcn

**Comment by whutbd** [comment]
Has it been fixed ?
@yeliang2258
