### ISSUE TITLE
Update paddle installation documents, make installation more simpler

### ISSUE THREAD

**Issue by typhoonzero** [PaddlePaddle/Paddle#4382]
Update `doc/getstarted/build_and_install` to make installation steps more simple and clear, refined document structure is:

1. install using pip(supports linux and mac)
1. run with docker (supports linux, mac and windows)
    1. run book image
    1. run production image
    1. run docker with GPU
    1. run under windows under docker
1. build from source(supports linux and mac)
    1. build under docker
    1. build under differnet linux distributions
    1. build under mac OS
1. common build and install FAQs

**Comment by llxxxll** [comment]
Are you considering supporting windows?

**Comment by typhoonzero** [comment]
@llxxxll windows users can only run under docker, and may not be able to use GPU. Will add some tips for windows users also.

**Comment by llxxxll** [comment]
@typhoonzero ok~
and  PaddlePaddle Mobile build&install ,do you want to add?

**Comment by typhoonzero** [comment]
Add to upper level of document index? Like:

1. getting started
    1. build and install
    1. run a demo
    1. run inference demo
1. paddle versions
1. training
1. inference
1. run on mobile
1. contributing
...

**Comment by luotao1** [comment]
As FAQ will make a document index (#4354), how about move "common build and install FAQs" into FAQ?

**Comment by typhoonzero** [comment]
@luotao1 Sure, definitely.

**Comment by NorthStar** [comment]
@abhinavarora can perhaps take on 3.iii, tagging him.
