### ISSUE TITLE
solov2运行时返回对象result为空

### ISSUE THREAD

**Issue by Zedd66** [PaddlePaddle/Paddle#43821]
### 请提出你的问题 Please ask your question

在使用paddle中solov2模型时，上传图片请求数据返回时的json对象中的result是空值导致无法继续进行，并且服务端没有报错，请问是什么原因还有如何解决

![QQ图片20220624153059](https://user-images.githubusercontent.com/86654889/175485992-99b23981-50e2-4737-bbd5-8b3f45cc8e91.png)

**Comment by zhaoyinglia** [comment]
@Zedd66  你好，请问可以提供复现代码或更详细的报错信息和环境信息吗？目前看报错是类型错误，如未能解决还请继续反馈，谢谢。

**Comment by Zedd66** [comment]
> @Zedd66 你好，请问可以提供复现代码或更详细的报错信息和环境信息吗？目前看报错是类型错误，如未能解决还请继续反馈，谢谢。

`import requests
import json
import cv2
import base64

import numpy as np


def cv2_to_base64(image):

    data = cv2.imencode('.jpg', image)[1]
    return base64.b64encode(data.tostring()).decode('utf8')

def base64_to_cv2(b64str):
    data = base64.b64decode(b64str.encode('utf8'))
    data = np.fromstring(data, np.uint8)
    data = cv2.imdecode(data, cv2.IMREAD_COLOR)
    return data

# 发送HTTP请求

org_im = cv2.imread('2.png')
org_im=cv2.resize(org_im,(50,50))
h, w, c = org_im.shape
data = {'images':[cv2_to_base64(org_im)]}
headers = {"Content-type": "application/json"}
url = "http://127.0.0.1:8866/predict/solov2"
r = requests.post(url=url, headers=headers, data=json.dumps(data))
print(r.json())
print("result:",r.json()["results"])
seg = base64.b64decode(r.json()["results"]['segm'].encode('utf8'))
seg = np.fromstring(seg, dtype=np.int32).reshape((-1, h, w))

label = base64.b64decode(r.json()["results"]['label'].encode('utf8'))
label = np.fromstring(label, dtype=np.int64)

score = base64.b64decode(r.json()["results"]['score'].encode('utf8'))
score = np.fromstring(score, dtype=np.float32)

print('seg', seg)
print('label', label)
print('score', score)`
这是具体代码是官方文档的，报错原因可能是因为返回对象中为空值无法转换，但是不知为什么是空值。然后服务端好像也没问题
![QQ图片20220624163923](https://user-images.githubusercontent.com/86654889/175498001-017517fc-d637-4d61-9846-8e01ad38a49f.png)

**Comment by zhaoyinglia** [comment]
> > @Zedd66 你好，请问可以提供复现代码或更详细的报错信息和环境信息吗？目前看报错是类型错误，如未能解决还请继续反馈，谢谢。
> 
> `import requests import json import cv2 import base64
> 
> import numpy as np
> 
> def cv2_to_base64(image):
> 
> ```
> data = cv2.imencode('.jpg', image)[1]
> return base64.b64encode(data.tostring()).decode('utf8')
> ```
> 
> def base64_to_cv2(b64str): data = base64.b64decode(b64str.encode('utf8')) data = np.fromstring(data, np.uint8) data = cv2.imdecode(data, cv2.IMREAD_COLOR) return data
> 
> # 发送HTTP请求
> org_im = cv2.imread('2.png') org_im=cv2.resize(org_im,(50,50)) h, w, c = org_im.shape data = {'images':[cv2_to_base64(org_im)]} headers = {"Content-type": "application/json"} url = "http://127.0.0.1:8866/predict/solov2" r = requests.post(url=url, headers=headers, data=json.dumps(data)) print(r.json()) print("result:",r.json()["results"]) seg = base64.b64decode(r.json()["results"]['segm'].encode('utf8')) seg = np.fromstring(seg, dtype=np.int32).reshape((-1, h, w))
> 
> label = base64.b64decode(r.json()["results"]['label'].encode('utf8')) label = np.fromstring(label, dtype=np.int64)
> 
> score = base64.b64decode(r.json()["results"]['score'].encode('utf8')) score = np.fromstring(score, dtype=np.float32)
> 
> print('seg', seg) print('label', label) print('score', score)` 这是具体代码是官方文档的，报错原因可能是因为返回对象中为空值无法转换，但是不知为什么是空值。然后服务端好像也没问题 ![QQ图片20220624163923](https://user-images.githubusercontent.com/86654889/175498001-017517fc-d637-4d61-9846-8e01ad38a49f.png)

你好，该问题已反馈给 PaddleDetection 相关人员，可在 https://github.com/PaddlePaddle/PaddleDetection/issues 重新提一个issue，会有相关技术人员帮忙解答。谢谢。

**Comment by Zedd66** [comment]
> > > @Zedd66你好，请问还可以提供其他详细的报错信息和环境信息吗？
> > 
> > 
> > `导入请求导入json导入cv2导入base64
> > 将 numpy 导入为 np
> > def cv2_to_base64（图像）：
> > ```
> > data = cv2.imencode('.jpg', image)[1]
> > return base64.b64encode(data.tostring()).decode('utf8')
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > def base64_to_cv2(b64str): data = base64.b64decode(b64str.encode('utf8')) data = np.fromstring(data, np.uint8) data = cv2.imdecode(data, cv2.IMREAD_COLOR) 返回数据
> > # 发送HTTP请求
> > org_im = cv2.imread('2.png') org_im=cv2.resize(org_im,(50,50)) h, w, c = org_im.shape data = {'images':[cv2_to_base64(org_im)]} 标头= {"Content-type": "application/json"} url = " http://127.0.0.1:8866/predict/solov2 " r = requests.post(url=url, headers=headers, data=json.dumps (数据)) print(r.json()) print("result:",r.json()["results"]) seg = base64.b64decode(r.json()["results"]['segm' ].encode('utf8')) seg = np.fromstring(seg, dtype=np.int32).reshape((-1, h, w))
> > label = base64.b64decode(r.json()["results"]['label'].encode('utf8')) label = np.fromstring(label, dtype=np.int64)
> > score = base64.b64decode(r.json()["results"]['score'].encode('utf8')) score = np.fromstring(score, dtype=np.float32)
> > print('seg', seg) print('label', label) print('score', score)`这是具体代码是官方文档的，报错原因可能是因为返回对象中为空值无法转换，但不知是空值。然后服务端好像没有什么问题![QQ图片20220624163923](https://user-images.githubusercontent.com/86654889/175498001-017517fc-d637-4d61-9846-8e01ad38a49f.png)
> 
> 你好，该问题已反馈给PaddleDetection相关人员，可在https://github.com/PaddlePaddle/PaddleDetection/issues重新提一个issue，如有相关技术人员帮忙解

> > > @Zedd66你好，请问还可以提供其他详细的错误信息和环境吗？
> > 
> > 
> > `导入请求导入json导入cv2导入base64
> > 将 numpy 导入为 np
> > def cv2_to_base64（图像）：
> > ```
> > data = cv2.imencode('.jpg', image)[1]
> > return base64.b64encode(data.tostring()).decode('utf8')
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > def base64_to_cv2(b64str): data = base64.b64decode(b64str.encode('utf8')) data = np.fromstring(data, np.uint8) data = cv2.imdecode(data, cv2.IMREAD_COLOR) 返回数据
> > # 发送HTTP请求
> > org_im = cv2.imread('2.png') org_im=cv2.resize(org_im,(50,50)) h, w, c = org_im.shape data = {'images':[cv2_to_base64(org_im)]} 标头= {"Content-type": "application/json"} url = " http://127.0.0.1:8866/predict/solov2 " r = requests.post(url=url, headers=headers, data=json. dumps (数据)) print(r.json()) print("result:",r.json()["results"]) seg = base64.b64decode(r.json()["results"]['segm ' ].encode('utf8')) seg = np.fromstring(seg, dtype=np.int32).reshape((-1, h, w))
> > label = base64.b64decode(r.json()["results"]['label'].encode('utf8')) label = np.fromstring(label, dtype=np.int64)
> > score = base64.b64decode(r.json()["results"]['score'].encode('utf8')) score = np.fromstring(score, dtype=np.float32)
> > print('seg', seg) print('label', label) print('score', score)`这是具体代码是官方文档的，报错原因可能是因为返回对象中为空值无法转换，但不知是空值。然后服务端没有什么问题![QQ图片20220624163923](https://user-images.githubusercontent.com/86654889/175498001-017517fc-d637-4d61-9846-8e01ad38a49f.png)
> 
> 你好，该已反馈给PaddleDetection相关人员，可在https://github.com/PaddlePaddle/PaddleDetection/issues重新提一个issue，如有相关技术问题人员帮忙解答。谢谢。

请问能再反馈一下吗，问题还是没有解决
