### ISSUE TITLE
求助关于PPOCRLabel的不规则文本标注、关键信息标注训练的方法

### ISSUE THREAD

**Issue by wuyunlai** [PaddlePaddle/Paddle#43844]
### 请提出你的问题 Please ask your question

我在用PaddleOCR自建数据级训练，想使用PPOCRLabel的不规则标注训练，来做印章定位和印章文字识别；想使用PPOCRLabel的关键信息标注训练，来做业务表单的关键信息定位和识别，但是不知道应该怎么做，请问有人知道是怎么做吗？

**Comment by andyjpaddle** [comment]
您好，可以参考 https://github.com/PaddlePaddle/PaddleOCR/blob/dygraph/PPOCRLabel/README_ch.md 使用文档，PPOCRLabel目前还不支持不规则的多点标注，但是已经支持关键信息kie标注了，如有使用问题，可以到PaddleOCR的repo下面进行提问~

**Comment by Evezerest** [comment]
你好，PPOCRLabel目前支持多点标注，升级到最新版本即可，如有后续问题可以到PaddleOCR的issue下提问
