### ISSUE TITLE
\ERNIE\applications\tasks\text_matching\run_infer.py预测示例数据data\predict_data\infer.txt，比较文本相似度时，两个文本长度有限制吗？现在文本9K，也能输出相似度得分0.997043

### ISSUE THREAD

**Issue by lbz0920** [PaddlePaddle/Paddle#43847]
### 请提出你的问题 Please ask your question

\ERNIE\applications\tasks\text_matching\run_infer.py预测示例数据data\predict_data\infer.txt，比较文本相似度时，两个文本长度有限制吗？现在文本9K，也能输出相似度得分0.997043

**Comment by tianxin1860** [comment]
你好，目前文本长度限制不超过 512。对于超长文本可以考虑采用切分成多段进行匹配。

**Comment by lbz0920** [comment]
请问怎么切分，使用什么工具，还是人工把文本拆分成<=512的N段文本string

**Comment by andyjiang1116** [comment]
可以手动加一些切分处理代码

**Comment by lbz0920** [comment]
文本长度限制不超过 512，是512字节吗？中文文本限制512*2=1024字节还是512字节?

**Comment by andyjiang1116** [comment]
512个字
