### ISSUE TITLE
runtime API 与nvcc版本不一致，导致运行出错

### ISSUE THREAD

**Issue by topxxuki** [PaddlePaddle/Paddle#43854]
### bug描述 Describe the Bug

执行命令
nvcc -V
import paddle.fluid as fluid;fluid.install_check.run_check()
![C345C81C0F026B1C3E14BB4E33CC5E92](https://user-images.githubusercontent.com/18697846/175862694-4353d954-5b65-46e4-bef7-e00a82ffe8d0.jpg)

GPU信息
![2D1D61FAF54862895861EDB158325769](https://user-images.githubusercontent.com/18697846/175862955-84cc408c-fb4a-4cc2-9dd9-8db82fde172b.jpg)

出错信息
![D7AB579AF122CA5186D0285CCC3C928D](https://user-images.githubusercontent.com/18697846/175862715-3f8811cb-0552-4b3c-a833-b6e460e6833b.jpg)
执行成功
![24887D52AD6B5C71DF555E0244984EB5](https://user-images.githubusercontent.com/18697846/175863008-ae2c0d47-b26e-4fe4-8d11-4a210592211c.jpg)

目前看起来当nvcc版本为11.4时，基于registry.baidubce.com/paddlepaddle/paddle:2.1.3-gpu-cuda11.2-cudnn8实现的镜像会运行出错，想请教一下原因

**Comment by andyjiang1116** [comment]
nvcc显示的是支持的最高CUDA版本，runtime是实际使用的CUDA版本，可以使用最新版paddle，推荐使用2.3

**Comment by topxxuki** [comment]
在docker中执行时使用的应该是镜像中的CUDA版本，镜像中只装了11.2的cuda环境，为何paddle会去找10.2 cuda呢

**Comment by topxxuki** [comment]
> nvcc显示的是支持的最高CUDA版本，runtime是实际使用的CUDA版本，可以使用最新版paddle，推荐使用2.3
在docker中执行时使用的应该是镜像中的CUDA版本，镜像中只装了11.2的cuda环境，为何paddle会去找10.2 cuda呢

**Comment by andyjiang1116** [comment]
这边检验paddle安装成功与否，使用 python 进入python解释器，输入`import paddle` ，再输入 `paddle.utils.run_check()`，另外建议使用paddle2.3

**Comment by andyjiang1116** [comment]
你好，这边验证还有问题吗？

**Comment by topxxuki** [comment]
> 你好，这边验证还有问题吗？

没有了，谢谢
