### ISSUE TITLE
paddlepaddle 安装

### ISSUE THREAD

**Issue by sweetsky0901** [PaddlePaddle/Paddle#4386]
1、在安装文档指引中，关于源码安装，目前只有找到了编译选项，建议可以加上关键的编译依赖的安装步骤。
2、我在阿里云的机器上执行pip install paddlepaddle，目前是不成功的。是还没有对外网开放吗？

**Comment by yeyupiaoling** [comment]
是可以安装的,可以看这个文档:[http://paddlepaddle.org/docs/develop/documentation/zh/getstarted/build_and_install/pip_install_cn.html](http://paddlepaddle.org/docs/develop/documentation/zh/getstarted/build_and_install/pip_install_cn.html),要保证你的pip是9.0.0以上的

**Comment by peterzhang2029** [comment]
Closing due to low activity. Feel free to reopen it.
