### ISSUE TITLE
 Nvidia V100运行正常A100运行出bug

### ISSUE THREAD

**Issue by Chucy2020** [PaddlePaddle/Paddle#43879]
### bug描述 Describe the Bug

![image](https://user-images.githubusercontent.com/73978694/176076856-54685931-1d6d-4651-a276-fba81e309a1b.png)

paddle version --> 2.2.2
cuda 11.2

**Comment by shiyutang** [comment]
报错信息在 log/worklog.0 和 log/worklog.1 下，需要打开查看详细信息从而明确问题，并在本条issue中回复。

**Comment by Chucy2020** [comment]
> 报错信息在 log/worklog.0 和 log/worklog.1 下，需要打开查看详细信息从而明确问题，并在本条issue中回复。
您好，这是log/worklog.0 和 log/worklog.1 下的报错信息：
worklog.0
![image](https://user-images.githubusercontent.com/73978694/176102094-3d317c3d-9ac9-436a-ba9a-9e150398ac85.png)
worklog.1
![image](https://user-images.githubusercontent.com/73978694/176102159-312ce906-9177-42d3-aabf-884486bd65c6.png)

**Comment by shiyutang** [comment]
你好，该问题可能是cuda版本和paddle不匹配导致，建议使用nvidia-smi查看版本，并安装对应版本的paddle 2.3。

**Comment by Chucy2020** [comment]
> 
您好，我的cuda是11.2
![image](https://user-images.githubusercontent.com/73978694/176107741-b5c8c585-a8bf-46cf-93d5-6326bdabd4dc.png)

但是使用命令安装paddle时出现这个问题，请问这个情况该怎么处理？无法添加.post112 
conda安装无法 添加cudatoolkit=11.2，请问是服务器无法连接网络的原因还是?
![image](https://user-images.githubusercontent.com/73978694/176107516-25e76952-6c6a-46da-b207-53cbe2cd714d.png)

**Comment by Chucy2020** [comment]
> 你好，该问题可能是cuda版本和paddle不匹配导致，建议使用nvidia-smi查看版本，并安装对应版本的paddle 2.3。

正如你所说，问题已解决，感谢大佬的耐心解答。
