### ISSUE TITLE
建议增加对英特尔集显加速的支持

### ISSUE THREAD

**Issue by amocken** [PaddlePaddle/Paddle#43870]
### 需求描述 Feature Description

建议增加对英特尔集显加速的支持，这样就可以在没有独显的电脑里跑得更快了

**Comment by andyjiang1116** [comment]
你好，感谢反馈，我们这边记录下需求

**Comment by Ligoml** [comment]
开发者你好，目前飞桨暂无此类开发计划，如果你有算力需求，可以体验[aistudio](https://aistudio.baidu.com/aistudio/index)，每天会赠送免费算力~
如果你有余力，我们非常欢迎你通过提pr来为飞桨增加此类能力，可以在pr中@我，我们会进行后续跟进
