### ISSUE TITLE
建议给GPU推理库瘦身

### ISSUE THREAD

**Issue by sdcb** [PaddlePaddle/Paddle#43874]
### 需求描述 Feature Description

现在支持GPU的推理库越来越大了，2.2.1的GPU版本只有700多MB，现在2.3.0最小的GPU版本也有1.5GB，简直离谱，你见过1.5GB一个的dll吗？这会让打包和发布遇到很大的困难。
![image](https://user-images.githubusercontent.com/1317141/175941760-a744b042-a1b9-447c-b35f-75455270a9b2.png)

建议给GPU的推理库瘦身，最好不要超过1GB——如果能拆成两个或多个dll更好。

**Comment by andyjiang1116** [comment]
好的，感谢反馈，该需求我们已经记录

**Comment by sdcb** [comment]
这个问题并未解决，请注意，请重新打开这个单。
