### ISSUE TITLE
paddle现在有通用的多机多卡并行运算的公共/收费服务吗？

### ISSUE THREAD

**Issue by lanfeng103** [PaddlePaddle/Paddle#4387]
你好，在利用深度学习技术解决现有业务需求中，我们遇到以下困难：
现在单卡训练约需要10多个工作日， 希望通过通过paddle的公共平台缩短单次训练所耗时间，最好能够将单次训练的时间缩短到1天内。请问，现在paddle存在这种通用的运算服务吗？ 最好是收费服务，可以定期稳定的申请运算资源

主要有一下需求
1、单次训练所需的资源可能较多，如8-20个GPU资源。
2、多机多卡并行运算的成熟解决方案
3、单次训练可能所需资源较多，希望能够按需付费或者预约等

**Comment by typhoonzero** [comment]
您好，paddle目前公开的集群可以参考：http://cloud.dlnel.org ，可以申请资源并开放使用。

注，此集群资源有限工程实验室学生任务使用，非合作实验室的任务可能出现中断或获取不到资源。
