### ISSUE TITLE
请教想c++调用paddle inference推理库，实现两个文本相似度比较，如何把文本转化为input tensor数据？

### ISSUE THREAD

**Issue by lbz0920** [PaddlePaddle/Paddle#43885]
### 请提出你的问题 Please ask your question

大概流程是？有c++示例吗

**Comment by shiyutang** [comment]
可以参考inference 的c++示例第（4）部分： https://www.paddlepaddle.org.cn/inference/quick_start/cpp_demo.html

**Comment by lbz0920** [comment]
// 获取输入 Tensor
auto input_names = predictor->GetInputNames();
auto input_tensor = predictor->GetInputHandle(input_names[0]);
// 设置输入 Tensor 的维度信息
std::vector<int> INPUT_SHAPE = {1, 3, 224, 224};
input_tensor->Reshape(INPUT_SHAPE);
// 准备输入数据
int input_size = 1 * 3 * 224 * 224;
std::vector<float> input_data(input_size, 1);
// 设置输入 Tensor 数据
input_tensor->CopyFromCpu(input_data.data());

我想请教：两个文本string,怎么才能转化变成input_tensor数据？需要哪些过程？这示例是float vector，不是想比较的两个string

**Comment by JZZ-NOTE** [comment]
你好，请问你的模型输入数据是什么格式呢？我理解应该需要你做一个预处理，把 string 转为模型的输入格式。可以使用 https://netron.app/ 工具，看一下模型的输入。

**Comment by lbz0920** [comment]
从两个文档读取内容，作为两个长文本进行相似度比较，两个string,我想先拆分为<512的N段文本string，比较短文本string的相似度，ERNIE\applications\tasks\text_matching\run_infer.py示例程序是python代码，c++调用paddle inference时不知道怎么把string转化为input tensor，需要哪些过程转化，网上示例是std::vector<float>:
(4) 设置模型输入 Tensor
// 获取输入 Tensor
auto input_names = predictor->GetInputNames();
auto input_tensor = predictor->GetInputHandle(input_names[0]);
// 设置输入 Tensor 的维度信息
std::vector<int> INPUT_SHAPE = {1, 3, 224, 224};
input_tensor->Reshape(INPUT_SHAPE);
// 准备输入数据
int input_size = 1 * 3 * 224 * 224;
std::vector<float> input_data(input_size, 1);
// 设置输入 Tensor 数据
input_tensor->CopyFromCpu(input_data.data());

**Comment by shiyutang** [comment]
请问是否可以提供训练部分代码，帮助我们查看输入模型的数据是否是string？

**Comment by lbz0920** [comment]
ernie官网的代码https://github.com/PaddlePaddle/ERNIE.git，python版本的，ERNIE\applications\tasks\text_matching，这个示例调用的是data\predict_data\infer.txt，比较两个文本相似度，但是是python代码，我在c++加paddle inference库中怎么对两个string文本，进行一系列处理，变成paddle inference可以用的input tensor，有没有c++示例代码，把输入的string转换成input tensor？

**Comment by shiyutang** [comment]
建议查看ernie中dataset的代码，里面应该有对文本到tensor的处理https://github.com/PaddlePaddle/ERNIE/blob/94a2367ba7f0f83b48330233450ea095d8dc9382/applications/tasks/text_matching/run_infer.py#L20

**Comment by joey12300** [comment]
@lbz0920 您好，目前PaddleNLP正在开发C++版本的文本预处理模块[faster_tokenizer](https://github.com/PaddlePaddle/PaddleNLP/tree/develop/faster_tokenizer)，可以支持在Python、C++端完成 String -> ID的操作，再结合Inference 库提供的接口完成从文本到Tensor的处理。该工作还在开发中，将在不久后发布，请关注PaddleNLP的Repo获取最新进展哈：https://github.com/PaddlePaddle/PaddleNLP/tree/develop/faster_tokenizer
