### ISSUE TITLE
paddle/fluid/framework.py:3623: DeprecationWarning: Op `norm` is executed through `append_op` under the dynamic mode, the corresponding API implementation needs to be upgraded to using `_C_ops` method.   "using `_C_ops` method." % type, DeprecationWarning)

### ISSUE THREAD

**Issue by yt605155624** [PaddlePaddle/Paddle#43899]
### 需求描述 Feature Description

api 遇到了这个 warning
如 warning 所说，动态图模式下，用的这个 api 没有走 _C_ops.xxx 实现的版本。那他会走静态图那个分支，会比较慢。修复方式就是加上这个实现
![9c913d86edcb7ac915844adf1be007ed](https://user-images.githubusercontent.com/24568452/176118927-9b7a8bb3-b1f4-432f-a218-5ecd1dba3a06.png)
参考：https://github.com/PaddlePaddle/Paddle/pull/43309

**Comment by shiyutang** [comment]
你的需求我们已经收到，正在进行需求评审中

**Comment by shiyutang** [comment]
通过查看框架代码，norm中inf_norm和p_matrix_norm暂时不满足该掉用方式需要跟进修改：https://github.com/PaddlePaddle/Paddle/blob/release%2F2.3/python/paddle/tensor/linalg.py
