### ISSUE TITLE
paddle/fluid/framework.py:3623: DeprecationWarning: Op `slice` is executed through `append_op` under the dynamic mode, the corresponding API implementation needs to be upgraded to using `_C_ops` method.

### ISSUE THREAD

**Issue by yt605155624** [PaddlePaddle/Paddle#43900]
### 需求描述 Feature Description

api 遇到了这个 warning
如 warning 所说，动态图模式下，用的这个 api 没有走 _C_ops.xxx 实现的版本。那他会走静态图那个分支，会比较慢。修复方式就是加上这个实现
![9c913d86edcb7ac915844adf1be007ed](https://user-images.githubusercontent.com/24568452/176118927-9b7a8bb3-b1f4-432f-a218-5ecd1dba3a06.png)
参考：https://github.com/PaddlePaddle/Paddle/pull/43309

与 https://github.com/PaddlePaddle/Paddle/issues/43899 类似，但是不是同一个 api

**Comment by shiyutang** [comment]
你的需求我们已经收到，正在进行需求评审中

**Comment by shiyutang** [comment]
请参见：https://github.com/PaddlePaddle/Paddle/blob/26187c27776e4c094228f5c573f19dba2d55e6a3/python/paddle/fluid/layers/nn.py#L11365  slice op在_in_legacy_dygraph已经掉用了Cops，因此本warning可能是版本没有更新导致，本需求也已经满足

**Comment by yt605155624** [comment]
收到
