### ISSUE TITLE
自定义COCO数据集的标签可以使用.txt嘛

### ISSUE THREAD

**Issue by Cuzny** [PaddlePaddle/Paddle#43902]
在coco数据集的基础上新增了两个类，然后创建的是 class, x, y, weight, height类型的.txt标签文件，可以不使用.json而使用.txt进行训练吗

**Comment by shiyutang** [comment]
该问题为Paddle Detection方向问题，建议前往PaddleDetection提问，同时本条issue下会有进一步跟进。https://github.com/PaddlePaddle/PaddleDetection/issues
