### ISSUE TITLE
关于device_guard新增设备类型支持的问题

### ISSUE THREAD

**Issue by houj04** [PaddlePaddle/Paddle#43913]
### 请提出你的问题 Please ask your question

目前的[`device_guard`](https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/fluid/framework.py#L7016)只能支持cpu、npu和gpu。
我需要给它增加xpu的支持，粗看起来只需要把7068行的
``` python
if device not in ['cpu', 'gpu', 'npu', '', None]:
```
这个数组里面加一个`'xpu'`就好了（当然7070行的注释也要对应改）。
想问的是，确实只需要改这些就够了么？

**Comment by shiyutang** [comment]
查看[代码](https://github.com/PaddlePaddle/Paddle/blob/bceca47a03edb322d02931207b168e2c56d5c262/python/paddle/fluid/framework.py#L2729)之后初步判断是不可行的，因为从代码可以看出，需要operator kernel支持 xpu 才可以，目前已经有一系列算子支持xpu了，对于这些operator是可以支持的。

**Comment by houj04** [comment]
看了上面的代码，发现即使某些operator不支持xpu，也只是报一个warning而不会挂掉对吧？那这些op会继续在cpu上跑，而能够支持的则会跑到xpu上。
如果是这样的话，我理解可以在7068行的那个数组里面把xpu加上，没有副作用。现在我遇到的问题是，有一些代码用了`device_guard`之后会直接在7068行附近挂掉。
现在的实现中有npu，但是npu也不可能支持所有的op吧？所以我感觉既然npu能放进去，那xpu应该也行……？
不知道是否我理解对了。

**Comment by shiyutang** [comment]
你可以尝试修改下这部分代码，并重新编译进行尝试。

**Comment by shiyutang** [comment]
同时可以参考device_guard下npu支持的代码进行同步实现.

**Comment by houj04** [comment]
这个函数的函数体，除掉注释之外，实际代码一共只有十几行，没啥特殊处理……
``` python
def device_guard(device=None):
```
