### ISSUE TITLE
faild building infrt

### ISSUE THREAD

**Issue by gglin001** [PaddlePaddle/Paddle#43912]
### bug描述 Describe the Bug

compile command

```
cd paddle/scripts/
bash infrt_build.sh build_only
```

error message

```
Scanning dependencies of target dense_tensor_IncGen
[ 14%] Building infrt_opsDialect.cpp.inc...
[ 14%] Building infrt_opsDialect.h.inc...
[ 14%] Building infrt_opsTypes.cpp.inc...
make[3]: *** No rule to make target '../paddle/infrt/dialect/pd/ir/pd_ops.td', needed by 'paddle/infrt/dialect/pd/ir/pd_ops.h.inc'.  Stop.
```

**Comment by gglin001** [comment]
## append question: 可以在不 enable tensorrt 完成编译吗?

**Comment by jiweibo** [comment]
> append question: 可以在不 enable tensorrt 完成编译吗?

您好，cmake可通过 -DINFRT_WITH_TRT=OFF 禁用 trt。



> ### bug描述 Describe the Bug
> compile command
> 
> ```
> cd paddle/scripts/
> bash infrt_build.sh build_only
> ```
> 
> error message
> 
> ```
> Scanning dependencies of target dense_tensor_IncGen
> [ 14%] Building infrt_opsDialect.cpp.inc...
> [ 14%] Building infrt_opsDialect.h.inc...
> [ 14%] Building infrt_opsTypes.cpp.inc...
> make[3]: *** No rule to make target '../paddle/infrt/dialect/pd/ir/pd_ops.td', needed by 'paddle/infrt/dialect/pd/ir/pd_ops.h.inc'.  Stop.
> ```
> 
> ### 其他补充信息 Additional Supplementary Information
> _No response_

该项目因人力问题已暂停开发，现阶段不保证能编过。
