### ISSUE TITLE
运行dssm跑任务失败

### ISSUE THREAD

**Issue by github-zj** [PaddlePaddle/Paddle#4391]
http://10.90.150.31:8920/fileview.html?path=/home/disk1/normandy/maybach/78108/
server.log显示失败，迭代5个pass后 server 出错，这个跟配置相关吗？
Sun Sep 24 03:04:24 2017[1,0]<stderr>:F0924 03:04:24.372612   685 SocketChannel.cpp:197] Check failed: len == sizeof(header) : Success [0]
Sun Sep 24 03:04:24 2017[1,0]<stderr>:*** Check failure stack trace: ***
Sun Sep 24 03:04:24 2017[1,0]<stderr>:    @           0x8d19fd  google::LogMessage::Fail()
Sun Sep 24 03:04:24 2017[1,0]<stderr>:    @           0x8d54ac  google::LogMessage::SendToLog()
Sun Sep 24 03:04:24 2017[1,0]<stderr>:    @           0x8d1523  google::LogMessage::Flush()
Sun Sep 24 03:04:24 2017[1,0]<stderr>:terminate called after throwing an instance of 'std::bad_alloc'

理论上不迭代应该不涉及到新的大块内存申请吧

**Comment by gongweibao** [comment]
这个集群的内存限定是多大？

**Comment by Yancey1989** [comment]
I'll close the inactive issue, please feel free to reopen it.
