### ISSUE TITLE
Tensor赋值无效

### ISSUE THREAD

**Issue by hfy-only** [PaddlePaddle/Paddle#43926]
### bug描述 Describe the Bug

import paddle
import numpy as np

batch, sentence_length, embedding_dim = 1, 5, 10

x_data = np.random.random(size=(batch, sentence_length, embedding_dim)).astype('int32')
# print("x_data",x_data)
# input = torch.randn(batch, sentence_length, embedding_dim)

# input[0] = torch.ones_like(input[0])
x_data = paddle.to_tensor(x_data)

x_data[0] = paddle.ones_like(x_data[0])
x_data[0][1] = paddle.to_tensor([1, 2, 2, 2, 2, 2, 2, 2, 2, 2])
print("x_data",x_data)
# x_data Tensor(shape=[1, 5, 10], dtype=int32, place=CUDAPlace(0), stop_gradient=True,
#        [[[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
#          [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
#          [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
#          [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
#          [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]]])
# 输出为如上，x_data[0][1] 并没有发生改变，飞桨版本为gpu的2.2.1

**Comment by hfy-only** [comment]
import paddle
import numpy as np

batch, sentence_length, embedding_dim = 1, 5, 10

x_data = np.random.random(size=(batch, sentence_length, embedding_dim)).astype('int32')
x_data = paddle.to_tensor(x_data)

x_data[0] = paddle.ones_like(x_data[0])
x_data[0][1] = paddle.to_tensor([1, 2, 2, 2, 2, 2, 2, 2, 2, 2])
print("x_data",x_data)
##  x_data Tensor(shape=[1, 5, 10], dtype=int32, place=CUDAPlace(0), stop_gradient=True,
##         [[[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
##           [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
##           [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
##           [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
##           [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]]])
##  输出为如上，x_data[0][1] 并没有发生改变，飞桨版本是2.2.1

**Comment by zyfncg** [comment]
你好，感谢反馈，多级索引不能赋值属于从静态图转向动态图时功能上的一个遗留问题，同[Issue#37733](https://github.com/PaddlePaddle/Paddle/issues/37733#issuecomment-984552202)。
这个问题我们正在跟进并尝试解决，预计会在后续的版本中对此项功能进行支持。

**Comment by hfy-only** [comment]
所以现在这个要怎么赋值呢

**Comment by zyfncg** [comment]
`x_data[0][1]` 可以换成`x_data[0, 1]`的写法

**Comment by aixuedegege** [comment]
x_data[0, 1]与x_data[0][1]有什么区别么
