### ISSUE TITLE
请问如何加入到 PFCC 组织中?

### ISSUE THREAD

**Issue by gglin001** [PaddlePaddle/Paddle#43929]
### 请提出你的问题 Please ask your question

hi, 我们 team 在做 paddlepaddle 和 Graphcore IPU 芯片的集成, 看到 这里 https://github.com/PaddlePaddle/Paddle/issues/42490 有关于 AI硬件接入 的部分, 请问如何加入到到 PFCC 组织中, 我们期待能够和 paddlepaddle 框架的开发者有更多的交流!

**Comment by gglin001** [comment]
append:

> 如果你想加入 PFCC，可以提交 PR 至 [Paddle](https://github.com/PaddlePaddle/Paddle)，代码合入后，会有相关的同学邀请你加入 PFCC。你可以选择你感兴趣的内容提交 PR，也可以根据上方中 Roadmap 提供的方向进行开发并提交 PR，我们非常欢迎你参与到飞桨框架的开发中。

from
https://github.com/PaddlePaddle/community/tree/master/pfcc

我们已经有提交一些 PR, 见 https://github.com/PaddlePaddle/Paddle/pulls?q=is%3Apr+%5Bipu%5D+is%3Aclosed

**Comment by SigureMo** [comment]
@TCChenlong 召唤龙哥～

**Comment by Ligoml** [comment]
欢迎加入PFCC，已加微信发送邀请~

**Comment by yiakwy** [comment]
@Ligoml @SigureMo 好像一直没有收到邮件，可以拉我下么
