### ISSUE TITLE
security@paddlepaddle.org邮箱无法递送

### ISSUE THREAD

**Issue by 360AIVul** [PaddlePaddle/Paddle#43928]
### 请提出你的问题 Please ask your question

我们在使用Paddle的过程中，发现存在一些安全漏洞，按照官方的readme，发邮件到security@paddlepaddle.org这个邮箱，但是邮件显示无法递送，请问一下是什么原因？

**Comment by Ligoml** [comment]
你好，邮件已收到，正在联系安全部门的同事检查情况，后续进展会同步在这里，感谢提出~

**Comment by Ligoml** [comment]
可以再试一下，这个邮箱现在应该没有问题了

**Comment by 360AIVul** [comment]
您好，
***@***.***，邮件已经发送到该邮箱。
***@***.***这个？

祝好！

Ligoml ***@***.***> 于2022年6月30日周四 19:13写道：

**Comment by VigiZhang** [comment]
已修改policy中邮箱地址为 paddle-security@baidu.com
