### ISSUE TITLE
Triplet Loss，三元组损失

### ISSUE THREAD

**Issue by 999lengfeng** [PaddlePaddle/Paddle#43921]
### 需求描述 Feature Description

在学习度量学习的时候，认识到了Triplet Loss，上手后loss不收敛，模型输出固定值， pytorch的代码又看不懂，paddle的代码没发现能用得，希望能出教程 在AIstudio上

**Comment by shiyutang** [comment]
你好，paddle已经有支持triplet loss，欢迎试用：https://github.com/PaddlePaddle/Paddle/pull/40487

**Comment by 999lengfeng** [comment]
找到了，models/PaddleCV/metric_learning/losses/tripletloss.py，在这
