### ISSUE TITLE
多机使用docker运行分布式任务如何获知ips的端口

### ISSUE THREAD

**Issue by huweikkk** [PaddlePaddle/Paddle#43944]
### 文档链接&描述 Document Links & Description

https://fleet-x.readthedocs.io/en/latest/paddle_fleet_rst/launch.html

### 请提出你的建议 Please give your suggestion

从单机到多机分布式任务，只需额外指定ips参数即可
多机使用docker默认的方式启动，请问分布式任务默认启动端口是多少，这样docker可以使用端口映射的方式，映射出分布式任务运行的端口。

**Comment by kuizhiqing** [comment]
分布式训练建议使用 launch 自动配置可用端口的方式，参考最新文档 https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/distributed/launch_cn.html

docker 部署建议使用 network host 以保证训练性能。

如果确需固定端口方式，请使用 DISTRIBUTED_TRAINER_ENDPOINTS 环境变量配置所有卡的ip和port列表。

**Comment by huweikkk** [comment]
done
