### ISSUE TITLE
kylin V10 编译paddle报错

### ISSUE THREAD

**Issue by 1chang37** [PaddlePaddle/Paddle#43951]
### 问题描述 Issue Description

Performing C SOURCE FILE Test CMAKE_HAVE_LIBC_PTHREAD failed with the following output:
Change Dir: /home/kunlun/tuili/xiazai/Paddle/build/CMakeFiles/CMakeTmp

Run Build Command(s):/usr/bin/gmake cmTC_5568b/fast && /usr/bin/gmake  -f CMakeFiles/cmTC_5568b.dir/build.make CMakeFiles/cmTC_5568b.dir/build
gmake[1]: 进入目录“/home/kunlun/tuili/xiazai/Paddle/build/CMakeFiles/CMakeTmp”
Building C object CMakeFiles/cmTC_5568b.dir/src.c.o
/usr/bin/cc   -fPIC -DCMAKE_HAVE_LIBC_PTHREAD   -o CMakeFiles/cmTC_5568b.dir/src.c.o   -c /home/kunlun/tuili/xiazai/Paddle/build/CMakeFiles/CMakeTmp/src.c
Linking C executable cmTC_5568b
/usr/local/bin/cmake -E cmake_link_script CMakeFiles/cmTC_5568b.dir/link.txt --verbose=1
/usr/bin/cc -fPIC -DCMAKE_HAVE_LIBC_PTHREAD    CMakeFiles/cmTC_5568b.dir/src.c.o  -o cmTC_5568b 
/usr/bin/ld: CMakeFiles/cmTC_5568b.dir/src.c.o: in function `main':
src.c:(.text+0x34): undefined reference to `pthread_create'
/usr/bin/ld: src.c:(.text+0x3c): undefined reference to `pthread_detach'
/usr/bin/ld: src.c:(.text+0x48): undefined reference to `pthread_join'
collect2: 错误：ld 返回 1
gmake[1]: *** [CMakeFiles/cmTC_5568b.dir/build.make:90：cmTC_5568b] 错误 1
gmake[1]: 离开目录“/home/kunlun/tuili/xiazai/Paddle/build/CMakeFiles/CMakeTmp”
gmake: *** [Makefile:124：cmTC_5568b/fast] 错误 2

Source file was:
#include <pthread.h>

void* test_func(void* data)
{
  return data;
}

int main(void)
{
  pthread_t thread;
  pthread_create(&thread, NULL, test_func, NULL);
  pthread_detach(thread);
  pthread_join(thread, NULL);
  pthread_atfork(NULL, NULL, NULL);
  pthread_exit(NULL);

  return 0;
}

Determining if the function pthread_create exists in the pthreads failed with the following output:
Change Dir: /home/kunlun/tuili/xiazai/Paddle/build/CMakeFiles/CMakeTmp

Run Build Command(s):/usr/bin/gmake cmTC_4b55c/fast && /usr/bin/gmake  -f CMakeFiles/cmTC_4b55c.dir/build.make CMakeFiles/cmTC_4b55c.dir/build
gmake[1]: 进入目录“/home/kunlun/tuili/xiazai/Paddle/build/CMakeFiles/CMakeTmp”
Building C object CMakeFiles/cmTC_4b55c.dir/CheckFunctionExists.c.o
/usr/bin/cc   -fPIC -DCHECK_FUNCTION_EXISTS=pthread_create   -o CMakeFiles/cmTC_4b55c.dir/CheckFunctionExists.c.o   -c /usr/local/share/cmake-3.16/Modules/CheckFunctionExists.c
Linking C executable cmTC_4b55c
/usr/local/bin/cmake -E cmake_link_script CMakeFiles/cmTC_4b55c.dir/link.txt --verbose=1
/usr/bin/cc -fPIC -DCHECK_FUNCTION_EXISTS=pthread_create    CMakeFiles/cmTC_4b55c.dir/CheckFunctionExists.c.o  -o cmTC_4b55c  -lpthreads 
/usr/bin/ld: 找不到 -lpthreads
collect2: 错误：ld 返回 1
gmake[1]: *** [CMakeFiles/cmTC_4b55c.dir/build.make:90：cmTC_4b55c] 错误 1
gmake[1]: 离开目录“/home/kunlun/tuili/xiazai/Paddle/build/CMakeFiles/CMakeTmp”
gmake: *** [Makefile:124：cmTC_4b55c/fast] 错误 2

Performing C++ SOURCE FILE Test MMX_FOUND failed with the following output:
Change Dir: /home/kunlun/tuili/xiazai/Paddle/build/CMakeFiles/CMakeTmp

Run Build Command(s):/usr/bin/gmake cmTC_282a9/fast && /usr/bin/gmake  -f CMakeFiles/cmTC_282a9.dir/build.make CMakeFiles/cmTC_282a9.dir/build
gmake[1]: 进入目录“/home/kunlun/tuili/xiazai/Paddle/build/CMakeFiles/CMakeTmp”
Building CXX object CMakeFiles/cmTC_282a9.dir/src.cxx.o
/usr/bin/c++    -Wno-error=deprecated-declarations -Wno-deprecated-declarations -DMMX_FOUND -mmmx   -o CMakeFiles/cmTC_282a9.dir/src.cxx.o -c /home/kunlun/tuili/xiazai/Paddle/build/CMakeFiles/CMakeTmp/src.cxx
c++: 错误：unrecognized command line option ‘-mmmx’
gmake[1]: *** [CMakeFiles/cmTC_282a9.dir/build.make:69：CMakeFiles/cmTC_282a9.dir/src.cxx.o] 错误 1
gmake[1]: 离开目录“/home/kunlun/tuili/xiazai/Paddle/build/CMakeFiles/CMakeTmp”
gmake: *** [Makefile:124：cmTC_282a9/fast] 错误 2

...and run output:

Return value: 1
Source file was:

#include <mmintrin.h>
int main()
{
    _mm_setzero_si64();
    return 0;
}
Performing C++ SOURCE FILE Test SSE2_FOUND failed with the following output:
Change Dir: /home/kunlun/tuili/xiazai/Paddle/build/CMakeFiles/CMakeTmp

Run Build Command(s):/usr/bin/gmake cmTC_e34f2/fast && /usr/bin/gmake  -f CMakeFiles/cmTC_e34f2.dir/build.make CMakeFiles/cmTC_e34f2.dir/build
gmake[1]: 进入目录“/home/kunlun/tuili/xiazai/Paddle/build/CMakeFiles/CMakeTmp”
Building CXX object CMakeFiles/cmTC_e34f2.dir/src.cxx.o
/usr/bin/c++    -Wno-error=deprecated-declarations -Wno-deprecated-declarations -DSSE2_FOUND -msse2   -o CMakeFiles/cmTC_e34f2.dir/src.cxx.o -c /home/kunlun/tuili/xiazai/Paddle/build/CMakeFiles/CMakeTmp/src.cxx
c++: 错误：unrecognized command line option ‘-msse2’
gmake[1]: *** [CMakeFiles/cmTC_e34f2.dir/build.make:69：CMakeFiles/cmTC_e34f2.dir/src.cxx.o] 错误 1
gmake[1]: 离开目录“/home/kunlun/tuili/xiazai/Paddle/build/CMakeFiles/CMakeTmp”
gmake: *** [Makefile:124：cmTC_e34f2/fast] 错误 2

...and run output:

Return value: 1
Source file was:

#include <emmintrin.h>
int main()
{
    _mm_setzero_si128();
    return 0;
}
Performing C++ SOURCE FILE Test SSE3_FOUND failed with the following output:
Change Dir: /home/kunlun/tuili/xiazai/Paddle/build/CMakeFiles/CMakeTmp

Run Build Command(s):/usr/bin/gmake cmTC_988f2/fast && /usr/bin/gmake  -f CMakeFiles/cmTC_988f2.dir/build.make CMakeFiles/cmTC_988f2.dir/build
gmake[1]: 进入目录“/home/kunlun/tuili/xiazai/Paddle/build/CMakeFiles/CMakeTmp”
Building CXX object CMakeFiles/cmTC_988f2.dir/src.cxx.o
/usr/bin/c++    -Wno-error=deprecated-declarations -Wno-deprecated-declarations -DSSE3_FOUND -msse3   -o CMakeFiles/cmTC_988f2.dir/src.cxx.o -c /home/kunlun/tuili/xiazai/Paddle/build/CMakeFiles/CMakeTmp/src.cxx
c++: 错误：unrecognized command line option ‘-msse3’
gmake[1]: *** [CMakeFiles/cmTC_988f2.dir/build.make:69：CMakeFiles/cmTC_988f2.dir/src.cxx.o] 错误 1
gmake[1]: 离开目录“/home/kunlun/tuili/xiazai/Paddle/build/CMakeFiles/CMakeTmp”
gmake: *** [Makefile:124：cmTC_988f2/fast] 错误 2

...and run output:

Return value: 1
Source file was:

#include <pmmintrin.h>
int main()
{
    __m128d a = _mm_set1_pd(6.28);
    __m128d b = _mm_set1_pd(3.14);
    __m128d result = _mm_addsub_pd(a, b);
    result = _mm_movedup_pd(result);
    return 0;
}
Performing C++ SOURCE FILE Test AVX_FOUND failed with the following output:
Change Dir: /home/kunlun/tuili/xiazai/Paddle/build/CMakeFiles/CMakeTmp

Run Build Command(s):/usr/bin/gmake cmTC_4d1fe/fast && /usr/bin/gmake  -f CMakeFiles/cmTC_4d1fe.dir/build.make CMakeFiles/cmTC_4d1fe.dir/build
gmake[1]: 进入目录“/home/kunlun/tuili/xiazai/Paddle/build/CMakeFiles/CMakeTmp”
Building CXX object CMakeFiles/cmTC_4d1fe.dir/src.cxx.o
/usr/bin/c++    -Wno-error=deprecated-declarations -Wno-deprecated-declarations -DAVX_FOUND -mavx   -o CMakeFiles/cmTC_4d1fe.dir/src.cxx.o -c /home/kunlun/tuili/xiazai/Paddle/build/CMakeFiles/CMakeTmp/src.cxx
c++: 错误：unrecognized command line option ‘-mavx’
gmake[1]: *** [CMakeFiles/cmTC_4d1fe.dir/build.make:69：CMakeFiles/cmTC_4d1fe.dir/src.cxx.o] 错误 1
gmake[1]: 离开目录“/home/kunlun/tuili/xiazai/Paddle/build/CMakeFiles/CMakeTmp”
gmake: *** [Makefile:124：cmTC_4d1fe/fast] 错误 2

...and run output:

Return value: 1
Source file was:

#include <immintrin.h>
int main()
{
    __m256 a = _mm256_set_ps (-1.0f, 2.0f, -3.0f, 4.0f, -1.0f, 2.0f, -3.0f, 4.0f);
    __m256 b = _mm256_set_ps (1.0f, 2.0f, 3.0f, 4.0f, 1.0f, 2.0f, 3.0f, 4.0f);
    __m256 result = _mm256_add_ps (a, b);
    return 0;
}
Performing C++ SOURCE FILE Test AVX2_FOUND failed with the following output:
Change Dir: /home/kunlun/tuili/xiazai/Paddle/build/CMakeFiles/CMakeTmp

Run Build Command(s):/usr/bin/gmake cmTC_cd723/fast && /usr/bin/gmake  -f CMakeFiles/cmTC_cd723.dir/build.make CMakeFiles/cmTC_cd723.dir/build
gmake[1]: 进入目录“/home/kunlun/tuili/xiazai/Paddle/build/CMakeFiles/CMakeTmp”
Building CXX object CMakeFiles/cmTC_cd723.dir/src.cxx.o
/usr/bin/c++    -Wno-error=deprecated-declarations -Wno-deprecated-declarations -DAVX2_FOUND -mavx2   -o CMakeFiles/cmTC_cd723.dir/src.cxx.o -c /home/kunlun/tuili/xiazai/Paddle/build/CMakeFiles/CMakeTmp/src.cxx
c++: 错误：unrecognized command line option ‘-mavx2’
gmake[1]: *** [CMakeFiles/cmTC_cd723.dir/build.make:69：CMakeFiles/cmTC_cd723.dir/src.cxx.o] 错误 1
gmake[1]: 离开目录“/home/kunlun/tuili/xiazai/Paddle/build/CMakeFiles/CMakeTmp”
gmake: *** [Makefile:124：cmTC_cd723/fast] 错误 2

...and run output:

Return value: 1
Source file was:

#include <immintrin.h>
int main()
{
    __m256i a = _mm256_set_epi32 (-1, 2, -3, 4, -1, 2, -3, 4);
    __m256i result = _mm256_abs_epi32 (a);
    return 0;
}
Performing C++ SOURCE FILE Test AVX512F_FOUND failed with the following output:
Change Dir: /home/kunlun/tuili/xiazai/Paddle/build/CMakeFiles/CMakeTmp

Run Build Command(s):/usr/bin/gmake cmTC_12bd9/fast && /usr/bin/gmake  -f CMakeFiles/cmTC_12bd9.dir/build.make CMakeFiles/cmTC_12bd9.dir/build
gmake[1]: 进入目录“/home/kunlun/tuili/xiazai/Paddle/build/CMakeFiles/CMakeTmp”
Building CXX object CMakeFiles/cmTC_12bd9.dir/src.cxx.o
/usr/bin/c++    -Wno-error=deprecated-declarations -Wno-deprecated-declarations -DAVX512F_FOUND -mavx512f   -o CMakeFiles/cmTC_12bd9.dir/src.cxx.o -c /home/kunlun/tuili/xiazai/Paddle/build/CMakeFiles/CMakeTmp/src.cxx
c++: 错误：unrecognized command line option ‘-mavx512f’
gmake[1]: *** [CMakeFiles/cmTC_12bd9.dir/build.make:69：CMakeFiles/cmTC_12bd9.dir/src.cxx.o] 错误 1
gmake[1]: 离开目录“/home/kunlun/tuili/xiazai/Paddle/build/CMakeFiles/CMakeTmp”
gmake: *** [Makefile:124：cmTC_12bd9/fast] 错误 2

...and run output:

Return value: 1
Source file was:

#include <immintrin.h>
int main()
{
    __m512i a = _mm512_set_epi32 (-1, 2, -3, 4, -1, 2, -3, 4,
                                  13, -5, 6, -7, 9, 2, -6, 3);
    __m512i result = _mm512_abs_epi32 (a);
    return 0;
}

### 版本&环境信息 Version & Environment Information

Paddle：2.3.0
CPU：ft2000+ 不支持avx 、mkl
GPU：telsa P4  
cuda：11.4
cudnn：8.4.1
系统：kylin V10
python：3.7

**Comment by adaxiadaxi** [comment]
@1chang37 您好，我看目录环境下是xpu的环境，咱们这里的AI加速卡是P4还是K200嘞。因为看到飞腾cpu，可能是需要国产的还款，加速卡也是英伟达的嘛

**Comment by 1chang37** [comment]
加速卡是p4,之前用过k200，当前去掉了



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2022年06月29日 19:28 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.******@***.***> |
| 主题 | Re: [PaddlePaddle/Paddle] kylin V10 编译paddle报错 (Issue #43951) |

@1chang37 您好，我看目录环境下是xpu的环境，咱们这里的AI加速卡是P4还是K200嘞。因为看到飞腾cpu，可能是需要国产的还款，加速卡也是英伟达的嘛

**Comment by qili93** [comment]
hi, @adaxiadaxi 

请发一下你的 CMAKE 命令，根据错误提示，你是在飞腾的 CPU 上开了WITH_MKL的编译选项，MKL 是只有 Intel CPU才有的功能。建议编译的时候把 WITH_MKL 和 WITH_AVX 都设置成 OFF，然后把 WITH_ARM 设置成 ON，make 命令改为 `make TARGET=ARMV8 -j$(nproc)`。

纯飞腾 CPU 的推理库编译可以参考这个文档，https://github.com/PaddlePaddle/Paddle-Inference-Demo/blob/master/docs-official/guides/hardware_support/cpu_phytium_cn.md , 如果是训练 WHL 包编译且是带 GPU 的版本，建议加上  WITH_GPU=ON 以及多卡需要加上 WITH_DISTRIBUTED=ON，然后把 ON_INFER 改成 OFF。

**Comment by 1chang37** [comment]
是要编译可以训练 带单个GPU的版本
cmake .. -DPY_VERSION=3.7 \
         -DWITH_ARM=ON \
         -DWITH_AARCH64=ON \
         -DWITH_TESTING=OFF \
         -DCMAKE_BUILD_TYPE=Release \
         -DON_INFER=OFF \
         -DWITH_XBYAK=OFF \ 
         -DWITH_GPU=ON \
         -DWITH_AMD_GPU=OFF \
         -DWITH_AVX=OFF \     
         -DWITH_NCCL=ON \ 
         -DWITH_RCCL=OFF \
         -DWITH_MKL=OFF \  
         -DWITH_MKLDNN=OFF \
         -DCUDA_ARCH_NAME=All \
         -DWITH_PYTHON=ON \
         -DWITH_TESTING=OFF \
         -DWITH_GOLANG=OFF

**Comment by 1chang37** [comment]
需要paddlepaddle带GPU训练

cmake .. -DPY_VERSION=3.7 \
         -DWITH_ARM=ON \
         -DWITH_AARCH64=ON \
         -DWITH_TESTING=OFF \
         -DCMAKE_BUILD_TYPE=Release \
         -DON_INFER=OFF \
         -DWITH_XBYAK=OFF \ 
         -DWITH_GPU=ON \
         -DWITH_AMD_GPU=OFF \
         -DWITH_AVX=OFF \     
         -DWITH_NCCL=ON \ 
         -DWITH_RCCL=OFF \
         -DWITH_MKL=OFF \  
         -DWITH_MKLDNN=OFF \
         -DCUDA_ARCH_NAME=All \
         -DWITH_PYTHON=ON \
         -DWITH_TESTING=OFF \
         -DWITH_GOLANG=OFF
