### ISSUE TITLE
WITH_DLNNE参数没有默认值，且是否需要在cmake过程中输出“WITH_DLNNE”存疑

### ISSUE THREAD

**Issue by firedent** [PaddlePaddle/Paddle#43980]
### 问题描述 Please describe your issue

绝大多数用户都不会使用到登临加速卡，而且CMake文件也没有对`WITH_DLNEE`设置默认值，导致运行`cmake`的时候会出现不明所以的输出：

```
-- commit: 590b4dbcdd
-- branch: HEAD
Performing Eager Dygraph Auto Code Generation
Final State Eager CodeGen
Generate dygraph file structure at path: /Paddle/paddle/fluid/eager/generated
# 冒号后面无输出，容易产生歧义
WITH_DLNNE:
-- Configuring done
-- Generating done
-- Build files have been written to: /Paddle/build
```

个人认为，输出日志应该本着精简和实用的原则。同一文件下，WITH_LITE 和WITH_GPU 时均没有输出message。因此，在cmake过程中是否输出WITH_DLNNE的值，需要开发者斟酌。
https://github.com/PaddlePaddle/Paddle/blob/73f957cf56e9ee7fea5bb338adc91bc224daf1ce/paddle/fluid/inference/analysis/ir_passes/CMakeLists.txt#L46

**Comment by 0x45f** [comment]
您好，收到您的反馈我们内部会安排评估，未来有计划修复的话会尽快回复

**Comment by luotao1** [comment]
@firedent 可以提一个PR进行修复
