### ISSUE TITLE
在使用Paddle Inference预测时，使用ONNXRuntime推理后端有什么好处？

### ISSUE THREAD

**Issue by firedent** [PaddlePaddle/Paddle#43991]
Paddle开发者你好，最近在编译Paddle Inference库和使用Paddle Inference预测功能时遇到了几个问题，希望能得到解答。

1. ONNXRuntime推理后端是只支持CPU预测吗？
2. 上一个问题如果是肯定回答，ONNXRuntime推理后端相比较原有的CPU预测推荐在什么情况下使用？上一个问题如果是否定回答，ONNXRuntime又该如何开启GPU预测？
3. “通过Paddle Inference调用ONNXRuntime推理后端”与“通过Paddle2X将Paddle产出模型转换成onnx格式，然后使用ONNXRuntime库预测”相比有什么区别？

**Comment by heliqi** [comment]
1. 目前inference只集成了CPU版本的ONNXRuntime后端。GPU下TensorRT性能收益更大，暂时没支持
2. 什么情况下使用得具体例子看， 可以根据模型自己实测，哪个好就用哪个。 
    Paddle这边测试了一大批模型，有些模型开启onnxruntime更快，有些开启mkldnn更快，有些什么都不开用原生cpu更快。
3. 使用inference好处有很多： 支持的模型更多、多个模型不同场景下部署也可以使用一套代码(只是config配置不同)，走paddle2onnx那你的系统需要集成多套推理引擎、使用inference成本更低，不用自己去实现onnxruntime的各种接口
