### ISSUE TITLE
飞桨 API 文档中的前端问题汇总

### ISSUE THREAD

**Issue by BrilliantYuKaimin** [PaddlePaddle/Paddle#44009]
飞桨文档评估工作小组在工作时发现了大量需要由前端工程师才能解决的问题，本 issue 将作为这些问题的汇总。大家在报告问题时请尽可能详细地附上问题示例。

**Comment by SigureMo** [comment]
咳，前端想打人系列 [doge]

## 问题发生区域

- [x] 英文文档
- [ ] 中文文档

## 问题详情

英文文档中 `Examples` 未被渲染为标题的样式

## 示例链接及截图

https://www.paddlepaddle.org.cn/documentation/docs/en/develop/api/paddle/nn/AdaptiveMaxPool1D_en.html

<img width="912" alt="image" src="https://user-images.githubusercontent.com/38436475/176851323-9d5ad096-cc2a-4540-b9ef-97ae72770aec.png">

**Comment by SigureMo** [comment]
## 问题发生区域

- [x] 英文文档
- [ ] 中文文档

## 问题详情

英文文档中 `Shape` 渲染为标题后包含仍包含冒号（`:`）

## 示例链接及截图

https://www.paddlepaddle.org.cn/documentation/docs/en/develop/api/paddle/nn/AdaptiveMaxPool1D_en.html

<img width="983" alt="image" src="https://user-images.githubusercontent.com/38436475/176851657-58eca937-5c58-412a-b4e3-f460a324d15c.png">

**Comment by SigureMo** [comment]
## 问题发生区域

- [x] 英文文档
- [ ] 中文文档

## 问题详情

中英文二级标题渲染不一致，中文二级标题渲染为 `h2` 标签，而英文二级标题则渲染为 `dt` 标签（感觉这是大多数人认为英文文档格式相对混乱的根本原因，这样的缩进不明显的嵌套结构并不易于阅读）

## 示例链接及截图

https://www.paddlepaddle.org.cn/documentation/docs/en/develop/api/paddle/nn/AdaptiveMaxPool1D_en.html

<img width="874" alt="image" src="https://user-images.githubusercontent.com/38436475/176852223-c32e87b8-cec9-4f9b-8fb4-baf77ef21e53.png">

https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/nn/AdaptiveMaxPool1D_cn.html

<img width="761" alt="image" src="https://user-images.githubusercontent.com/38436475/176852417-ff1f6c45-a545-4cf6-b2c8-1912a60bd062.png">

## 推荐解决方案

其实和前两个一样，根本是英文文档从 docstring 解析得到的 rst 与中文的 rst 格式不一致导致的，如果中文的格式是预期的话，那么可以重写这个 docstring -> rst 的解析器（ https://github.com/sphinx-contrib/napoleon ）

当然，另一方面我们甚至可以利用 sphinx 的 [i18n 特性](https://www.sphinx-doc.org/en/master/usage/advanced/intl.html)来直接完成中文文档的编写（有点类似上次 PFCC 会议上说的那种表格式的翻译），但这一项工程量可能巨大，应该是后话了……

**Comment by SigureMo** [comment]
## 问题发生区域

- [x] 英文文档
- [x] 中文文档

## 问题详情

原 https://github.com/PaddlePaddle/docs/issues/4935 ，现已 close

除大小写外同名 API 在侧边栏排序不稳定

打开 API 文档 [paddle.vision.models 页面](https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/vision/models/AlexNet_cn.html)，观察 alexnet 和 AlexNet 以及 googlenet 和 GoogLeNet，随意点击侧边栏进行跳转，可以发现 alexnet 和 AlexNet 的相对位置（googlenet 那俩一样）是不稳定的，经常调换，因此猜测前端 sidebar 运行时排序没有考虑除大小写外同名的情况

当然，Resize、resize 等等这些同名的 API 也会有这样的问题。虽然不会有太大影响，但稍微有点影响用户体验。

## 示例链接及截图

https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/vision/models/AlexNet_cn.html

https://user-images.githubusercontent.com/38436475/174034725-ee5566c0-bfe7-4e93-9937-76f31cc7ff3f.mp4

**Comment by BrilliantYuKaimin** [comment]
## 公式编号问题
据观察，飞桨文档中的数学公式是由 MathJax 渲染的，而 MathJax 对于 equation 环境下的公式是可以自动编号的。经测试（ https://github.com/PaddlePaddle/docs/pull/4955 ），飞桨文档中没有自动启用公式编号的功能。希望前端工程师对这个功能予以支持。提出这个需求是因为引用公式会使有些参数的解释更加简单、明确，如：
![WechatIMG861](https://user-images.githubusercontent.com/91609464/176872391-8be8ac2d-fa46-4578-9011-560bcc812df0.jpeg)

**Comment by Ligoml** [comment]
# 英文文档问题

## 前端关键字渲染问题

- Return 与 Return type 的问题：对英文API文档，会将源码中 returns 的值渲染为这两部分，冒号前是 Return，冒号后是 Return type，这一方面导致了中英文文档的不一致（中文文档是纯rst），另一方面也使阅读英文文档体验稍差，建议统一一下，可以选择 a)去掉这种渲染形式；b)为所有中文文档增加 Return type。建议方案a
- 关键字值为 None 时的逻辑错误：参考示例：[paddle.get_cuda_rng_state](https://www.paddlepaddle.org.cn/documentation/docs/en/api/paddle/get_cuda_rng_state_en.html) 因为特殊样式的渲染，当值为 None 时，会将 None 当做参数，然后在后面增加一个连接符 `-`，很奇怪，建议增加：值为 None 时的逻辑判断
- shape 样式缺失：官网对API英文文档中的关键字：如 args、examples 会触发特定的样式，但是 shape 似乎没有加入，导致 nn 下的class 类 API 在文档写作中会遇到一些尴尬，参考示例：[paddle.nn.AdaptiveAvgPool1D](https://www.paddlepaddle.org.cn/documentation/docs/en/api/paddle/nn/AdaptiveAvgPool1D_en.html)
args 与 shape 在源码中的写法是一致的，但实际效果有差距，如果要在格式上保持一致，可以选择 a)在源码中修改；b)为shape增加特殊样式。建议方案b

## 关键字目录层级不明确的问题
@SigureMo 已经在上文说的比较清楚了，建议修改

## 超链接失效的问题（红线）
中文文档使用标签互相索引，问题不大，英文文档索引方式不明确，大部分索引都是失效状态，如 broadcast、inplace API等，都没有被有效索引起来。TODO：增加英文文档互相索引的文档

## 前端错误（红线）
with_quant_attr (BOOLEAN) 多个API文档中都出现了这个多余的参数，参考示例：[paddle.multiply](https://www.paddlepaddle.org.cn/documentation/docs/en/api/paddle/multiply_en.html)、[paddle.floor](https://www.paddlepaddle.org.cn/documentation/docs/en/develop/api/paddle/floor_en.html)
<img width="193" alt="image" src="https://user-images.githubusercontent.com/39876205/185895769-03855618-9e72-48f6-8553-786a30163b7c.png">
[特殊 API ](https://github.com/PaddlePaddle/docs/wiki/%E9%A3%9E%E6%A1%A8API%E7%89%B9%E6%AE%8A%E5%AE%9E%E7%8E%B0)均存在上述问题

# API名称渲染问题

<img width="90" alt="image" src="https://user-images.githubusercontent.com/39876205/185919567-9169c33a-0f47-408a-b339-cc26c4782009.png">

多出来一个空格，参考样例：[paddle.static.Print](https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/static/Print_cn.html#print)

**Comment by enkilee** [comment]
https://www.paddlepaddle.org.cn/documentation/docs/en/develop/api/paddle/profiler/Profiler_en.html
文档中，例子1和2的代码颜色高亮正确，代码3就不正确了。
![Snipaste_2022-09-05_08-54-37](https://user-images.githubusercontent.com/16059379/188341052-aecec3df-8833-43ee-a75a-fda9c0e87107.png)
查看前段，是CSS的问题，但估计是应该是解释器的问题了。
例子2的css:
![Snipaste_2022-09-05_08-55-01](https://user-images.githubusercontent.com/16059379/188341092-ee88d5a4-90ae-4653-8810-4079ec69551f.png)
例子3的css:
![Snipaste_2022-09-05_08-55-17](https://user-images.githubusercontent.com/16059379/188341108-bf900de4-af6e-4df2-b953-466a1526d83b.png)
可是在文档中，2段代码的开头解释是一样的：
![Snipaste_2022-09-05_08-58-21](https://user-images.githubusercontent.com/16059379/188341167-745aaa86-cc01-41d7-8c63-6692ae986a63.png)

**Comment by enkilee** [comment]
中英文文档前端显示的问题：
英文文档，类里面显示了方法的使用，中文没有，但是py文件里没有文档说明，想在方法前面加一行  Methods， 告诉读者这后面是类里面的方法。
![微信图片_20220915105103](https://user-images.githubusercontent.com/16059379/190302623-12e853e6-f652-4389-bc53-eabcbde55716.png)
![微信图片_20220915105109](https://user-images.githubusercontent.com/16059379/190302673-63fe64a5-5599-41ce-8165-3b3609285fa6.png)
![微信图片_20220915105112](https://user-images.githubusercontent.com/16059379/190302672-ea9dd2e2-20d7-4d5a-a496-1e2619ba703c.png)
