### ISSUE TITLE
scatter_nd_add and put_along_axis 

### ISSUE THREAD

**Issue by lsyysl9711** [PaddlePaddle/Paddle#44018]
### 请提出你的问题 Please ask your question

请问一下，pytorch中的scatter_add对应的是scatter_nd_add 还是 put_along_axis？

**Comment by Ligoml** [comment]
put_along_axis，具体信息可以看下[API 文档](https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/put_along_axis_cn.html#put-along-axis)
