### ISSUE TITLE
在Mac M1 pro平台使用Debian:stable (stable-20220622) 编译arm版Paddlepaddle成功，但是ctest未能完全通过。

### ISSUE THREAD

**Issue by firedent** [PaddlePaddle/Paddle#44032]
### 问题描述 Issue Description

ctest日志：[LastTest.log](https://github.com/PaddlePaddle/Paddle/files/9034266/LastTest.log)

- Paddlepaddle源码版本: `git checkout v2.3.1`
- 使用的CMake命令: `cmake .. -DPY_VERSION=3.9 -DWITH_TESTING=ON -DON_INFER=ON -DWITH_ARM=ON -DCMAKE_BUILD_TYPE=Release`
- Docker Engine: `v20.10.16`
- 容器内核: `Linux 9093ee9c043a 5.10.104-linuxkit #1 SMP PREEMPT Thu Mar 17 17:05:54 UTC 2022 aarch64 GNU/Linux`

### 版本&环境信息 Version & Environment Information

****************************************
Paddle version: 2.3.1
Paddle With CUDA: False

OS: Debian GNU/Linux 11
Python version: 3.9.2

CUDA version: None
cuDNN version: None.None.None
Nvidia driver version: None
****************************************
python3 -m pip list
Package            Version
------------------ ---------
astor              0.8.1
attrs              21.4.0
Babel              2.10.3
bce-python-sdk     0.8.73
certifi            2022.6.15
charset-normalizer 2.1.0
click              8.1.3
cloudpickle        2.1.0
cycler             0.11.0
decorator          5.1.1
distro             1.7.0
exceptiongroup     1.0.0rc8
Flask              2.1.2
Flask-Babel        2.0.0
fonttools          4.33.3
future             0.18.2
gym                0.24.1
gym-notices        0.0.7
hypothesis         6.48.2
idna               3.3
importlib-metadata 4.12.0
itsdangerous       2.1.2
Jinja2             3.1.2
kiwisolver         1.4.3
MarkupSafe         2.1.1
matplotlib         3.5.2
numpy              1.23.0
onnx               1.12.0
opencv-python      4.6.0.66
opt-einsum         3.3.0
packaging          21.3
paddle-bfloat      0.1.7
paddle2onnx        0.9.9
paddlepaddle       2.3.1
pandas             1.4.3
Pillow             9.2.0
pip                20.3.4
protobuf           3.20.0
pycryptodome       3.15.0
pyparsing          3.0.9
python-dateutil    2.8.2
pytz               2022.1
PyYAML             6.0
requests           2.28.1
scipy              1.8.1
setuptools         52.0.0
six                1.16.0
sortedcontainers   2.4.0
typing-extensions  4.3.0
urllib3            1.26.9
visualdl           2.3.0
Werkzeug           2.1.2
wheel              0.34.2
zipp               3.8.0
****************************************

**Comment by zmxdream** [comment]
你好，感谢你的反馈，我们会尽快验证
