### ISSUE TITLE
paddle.nonzero()不返回0所在位置

### ISSUE THREAD

**Issue by jyjfjyjf** [PaddlePaddle/Paddle#44031]
### bug描述 Describe the Bug

    paddle.nonzero(paddle.to_tensor([0, 1, 0, 2]))
    Tensor(shape=[2, 1], dtype=int64, place=Place(gpu:0), stop_gradient=True,
           [[0],
            [2]])
    paddle.nonzero(paddle.to_tensor([0, 1, 0, 2, 0]))
    Tensor(shape=[2, 1], dtype=int64, place=Place(gpu:0), stop_gradient=True,
           [[0],
            [0]])

### 其他补充信息 Additional Supplementary Information

paddlepaddle 2.3

**Comment by zmxdream** [comment]
![image](https://user-images.githubusercontent.com/17705473/177021890-16a25578-a3ae-4528-a12a-ce2dc52204fa.png)
python -m pip install paddlepaddle-gpu==2.3.0.post112 -f https://www.paddlepaddle.org.cn/whl/linux/mkl/avx/stable.html
你好，用上面命令安装的paddle-gpu 2.3版本,经过实际测试，能够返回正确的非零元素位置信息
![image](https://user-images.githubusercontent.com/17705473/177021989-efdca62f-4a71-49ef-8f3d-6e4b14053ff6.png)
请确认下你的安装版本，以及你的问题描述应该是paddle.nonzero()不返回非0所在位置？

**Comment by jyjfjyjf** [comment]
paddlepaddle版本就是2.3
![image](https://user-images.githubusercontent.com/34862504/177026911-7b36d690-f3b3-4379-869e-6f8d53f4395c.png)
我是用这条命令安装的paddle.nonzero()不会返回非0位置
![image](https://user-images.githubusercontent.com/34862504/177026938-d223abee-96b4-4460-ba24-661d81536fc7.png)

**Comment by jyjfjyjf** [comment]
显卡rtx3090
python 3.8

**Comment by jyjfjyjf** [comment]
python换成3.7还是这样

**Comment by jyjfjyjf** [comment]
![image](https://user-images.githubusercontent.com/34862504/177030695-7145e2f6-b1d2-4643-bca6-8dd9cdbbbdd3.png)
![image](https://user-images.githubusercontent.com/34862504/177030744-64dd87bc-112f-47dd-9ed5-e66f04a01c35.png)

**Comment by jyjfjyjf** [comment]
在aistudio上就没问题
![image](https://user-images.githubusercontent.com/34862504/177030780-fbb86510-94d7-4ca5-8f40-87aa2be2e5f1.png)

**Comment by jyjfjyjf** [comment]
在aistudio上训练的模型比本地训练的模型准确率高1个十分点，paddlepaddle-gpu在我本地想正常使用该怎么办

**Comment by jyjfjyjf** [comment]
![image](https://user-images.githubusercontent.com/34862504/177033778-a5712deb-d22b-4481-8357-ac044d5202f6.png)

**Comment by jyjfjyjf** [comment]
![image](https://user-images.githubusercontent.com/34862504/177037057-f2bad11a-4db0-4df8-aa92-69deabd58724.png)
![image](https://user-images.githubusercontent.com/34862504/177037060-8cf31a91-6c42-46d3-bd00-a508bd5cb36b.png)
代码一样的参数一样的，种子也一样的，就epoch不一样，本地跟aistudio为什么差这么大

**Comment by jyjfjyjf** [comment]
本地重新配的环境 python3.7 paddlepaddle-gpu2.3，paddle.nonzero()还是不对

**Comment by zmxdream** [comment]
你好，本地cuda是什么版本

**Comment by zmxdream** [comment]
你好请确认下conda 环境里的cuda版本，以及本地尝试安装下CPU版本Paddle，验证下结果正确性

**Comment by jyjfjyjf** [comment]
![image](https://user-images.githubusercontent.com/34862504/177053328-d5c15157-3fd4-4ee1-ab56-5e49778cd554.png)
![image](https://user-images.githubusercontent.com/34862504/177053602-1cfe8200-9a83-403e-bdef-61fa127e901a.png)
conda 里面cuda是11.2
cpu没有问题

**Comment by jyjfjyjf** [comment]
![image](https://user-images.githubusercontent.com/34862504/177053946-09a1891a-df27-4bf3-8a76-f7a58e043d57.png)
可我一样的代码，为啥cpu就没有问题

**Comment by jyjfjyjf** [comment]
![image](https://user-images.githubusercontent.com/34862504/177210661-2471c2ad-fe7f-4edc-910f-b8eec0c44b33.png)
![image](https://user-images.githubusercontent.com/34862504/177210687-dcf65289-5b95-4f9c-93ca-7732281b9a98.png)
nonzero()返回的东西

**Comment by haohongxiang** [comment]
@jyjfjyjf 我们这边已复现问题，正在排查修复中

**Comment by haohongxiang** [comment]
@jyjfjyjf Hi，paddle.nonzero API 在windows+cuda 11.2环境下精度异常的问题，我们已修复，[PR](https://github.com/PaddlePaddle/Paddle/pull/44181)合入了develop分支。您这边如果不想编译paddle的话，可以使用[nightly安装包](https://www.paddlepaddle.org.cn/install/quick?docurl=/documentation/docs/zh/develop/install/pip/windows-pip.html)，今天合入的PR会在明天开始的nightly包中生效。

**Comment by jyjfjyjf** [comment]
好的

**Comment by w5688414** [comment]
I meet the same problem here. 

<img width="1025" alt="image" src="https://user-images.githubusercontent.com/12107462/189887887-416bf551-b3dc-4f52-8fdc-fec465d00268.png">

**Comment by sunzhongkai588** [comment]
确认一下版本，最新版应该已经解决该问题
