### ISSUE TITLE
[libprotobuf FATAL /Paddle/build4/third_party/protobuf/src/extern_protobuf/src/google/protobuf/generated_message_reflection.cc:2329] CHECK failed: file != NULL: 

### ISSUE THREAD

**Issue by elvindp** [PaddlePaddle/Paddle#44048]
### /Paddle/build4/third_party/protobuf/src/extern_protobuf/src/google/protobuf/generated_message_reflection.cc:2329] CHECK failed: file != NULL

需要使用lac分词，因为protobuf版本问题，需要自己编译paddle
编译paddle最新的develop版本，编译通过，但在inference的时候出bug，提示check fialed：
系统centos7
修改了protobuf的版本，从3.1.0改成3.5.2，其它cmake设置没有改动。

[libprotobuf FATAL /Paddle/build4/third_party/protobuf/src/extern_protobuf/src/google/protobuf/generated_message_reflection.cc:2329] CHECK failed: file != NULL: 

Traceback (most recent call last):
  File "/Root/request_video_quality_flow.py", line 10, in <module>
    lac = LAC(mode='lac')
  File "/home/python3.7/site-packages/LAC/lac.py", line 65, in __init__
    model = LacModel(model_path, mode, use_cuda)
  File "/home/python3.7/site-packages/LAC/models.py", line 233, in __init__
    super(LacModel, self).__init__(model_path, mode, use_cuda) 
  File "/home/python3.7/site-packages/LAC/models.py", line 66, in __init__
    self.predictor = create_paddle_predictor(config)
RuntimeError: CHECK failed: file != NULL: 
`

**Comment by From00** [comment]
你好，请问protobuf版本具体遇到了什么问题？

目前飞桨源码编译使用protobuf 3.1.0，python环境中安装的protobuf版本在3.1.0~3.20.0均能正常使用，如果是因python环境中安装的protobuf版本有问题，重新安装符合要求的protobuf版本即可，不需要自己在源码中升级protobuf版本并重新编译。相关问题见issue https://github.com/PaddlePaddle/Paddle/issues/43052
