### ISSUE TITLE
typo in paddle doc

### ISSUE THREAD

**Issue by czr-gc** [PaddlePaddle/Paddle#44042]
### bug描述 Describe the Bug

https://www.paddlepaddle.org.cn/documentation/docs/zh/guides/model_convert/pytorch_api_mapping_cn.html#pytorch-1-8-paddle-2-0-api

PyTroch --> PyTorch

![image](https://user-images.githubusercontent.com/96037699/177068081-bc221a1c-6414-4231-90c5-75a5ac446a0a.png)

**Comment by Ligoml** [comment]
感谢反馈，目前已在修改~

**Comment by wjj19950828** [comment]
@czr-gc 您好，感谢反馈～

目前问题已经修复，明天的官网API映射表应该就可以看到
