### ISSUE TITLE
使用to_sparse_coo()报错

### ISSUE THREAD

**Issue by jyjfjyjf** [PaddlePaddle/Paddle#44041]
### 请提出你的问题 Please ask your question

win11
paddlepaddle 2.3 
cuda 11.2 
rrtx3090
python 3.7
![image](https://user-images.githubusercontent.com/34862504/177052865-755c62a4-2323-4802-a008-bae4009be2cb.png)
![image](https://user-images.githubusercontent.com/34862504/177052874-99021782-e62a-4ada-98e7-79df5f844372.png)
怎么样才能正确使用to_sparse_coo()

**Comment by zkh2016** [comment]
你好，目前使用sparse的api需要加`with _test_eager_guard()'，使用例子：

```
import paddle
from paddle.fluid.framework import _test_eager_guard
with _test_eager_guard():
    dense = paddle.randn((3,3))
    sparse = dense.to_sparse_coo(2)
    print(sparse)
```
