### ISSUE TITLE
Transformer的实现是否可以考虑输出attention_weights？

### ISSUE THREAD

**Issue by holyseven** [PaddlePaddle/Paddle#44056]
### 需求描述

对于高阶开发者，有获取Transformers中间层的attention weights（即shape=`[batch_size, num_heads, query_length, key_length]`）来进行模型设计和分析实验的需求。

### 具体场景

- EHealth中SPO任务需要获取Electra中间层结果来计算loss
- 使用Transformer-based模型时需要中间层attention和结果来进行分析和蒸馏
- 解释Transformer模型时，attention weights和其对应的梯度，都是非常重要的中间结果

### 目前Paddle的实现

目前是在`MultiHeadAttention`的`forward()`函数中，调用`paddle.nn.functional`的方法。

https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/nn/layer/transformer.py#L420

因为使用了`paddle.nn.functional`的方法（不确定是否会减少内存消耗？），用`hook`的方法也无法得到中间变量的结果。

虽然在`MultiHeadAttention`中，可以修改`need_weights`参数，输出weights。但是对于所有已经构建好的模型（尤其是Ernie模型），改变这个参数，需要重新调整模型每一层的输入输出，较为繁琐。

该需求在PaddleNLP的[issue](https://github.com/PaddlePaddle/PaddleNLP/issues/1746)里面也有提到过，但感觉这和`paddle.nn.layer.transformer`更相关。

### 替代实现 Alternatives

一个简单的方法，就是不使用`paddle.nn.functional`的方法，而是使用`Layer`的模块。这样，通过hook的方法，在后期也能很快地得到。而且也完全兼容已有代码和模型。

**Comment by guoshengCS** [comment]
你好，我们已经开始在 PaddleNLP 的层面做了，这个是我们重点解决的问题  https://github.com/PaddlePaddle/PaddleNLP/pull/2665 。因为里面会引入ModelOutput这样一些特殊的数据结构，和框架中其他layer的规范会不太一样，所以先行在PaddleNLP中解决
