### ISSUE TITLE
Have no paddle symbols check_symbol.sh: 23: exit: Illegal number: -1 Check symbol failed.

### ISSUE THREAD

**Issue by lmdnyo** [PaddlePaddle/Paddle#44050]
### 问题描述 Issue Description

I am compiling 2.3.1 tag with ARMV8 Nvidia Xavier NX 16 GB with following CMAKE.

cmake .. -G 'Unix Makefiles' -DWITH_MKL=OFF -DWITH_MKLDNN=OFF -DWITH_AVX=OFF -DWITH_GPU=ON -DON_INFER=ON -DWITH_TESTING=OFF -DCMAKE_BUILD_TYPE=Release -DCUDA_ARCH_NAME=All -DWITH_ARM=ON -DWITH_NV_JETSON=ON -DWITH_PYTHON=ON -DPY_VERSION=3.6 -DPYTHON_INCLUDE_DIR:PATH=/usr/include/python3.6 -DPYTHON_EXECUTABLE:FILEPATH=/usr/bin/python3.6 -DPYTHON_LIBRARY:FILEPATH=/usr/lib/aarch64-linux-gnu/libpython3.6m.so -DWITH_XBYAK=OFF -DWITH_RCCL=OFF -DWITH_ROCM=OFF -DCMAKE_CUDA_COMPILER:PATH=/usr/local/cuda-10.2/bin/nvcc -DCUDA_ARCHITECTURES=all

make TARGET=ARMV8 -j$(nproc)

I am getting following error

[ 99%] Generating .check_symbol
Have no paddle symbols
/mnt/Paddle-2.3.1/paddle/fluid/inference/check_symbol.sh: 23: exit: Illegal number: -1
CMake Error at check_symbol.cmake:3 (message):
  Check symbol failed.

paddle/fluid/inference/CMakeFiles/check_symbol.dir/build.make:72: recipe for target 'paddle/fluid/inference/.check_symbol' failed

I checked but not found any solution yet. Pl guide.

### 版本&环境信息 Version & Environment Information

****************************************
Paddle version: None
Paddle With CUDA: None

OS: Ubuntu 18.04
Python version: 3.6.9

CUDA version: 10.2.300
Build cuda_10.2_r440.TC440_70.29663091_0
cuDNN version: None.None.None
Nvidia driver version: None
****************************************

**Comment by jiangjiajun** [comment]
Hi，你可以试下使用下面的方式来编译吗
```
cmake .. -DCMAKE_CXX_FLAGS='-Wno-error -w'  -DWITH_CONTRIB=OFF   -DWITH_MKL=OFF    -DWITH_MKLDNN=OFF   -DWITH_TESTING=ON   -DCMAKE_BUILD_TYPE=Release   -DON_INFER=ON   -DWITH_PYTHON=ON -DPY_VERSION=3.6  -DWITH_XBYAK=OFF  -DWITH_NV_JETSON=ON -DWITH_TENSORRT=ON -DTENSORRT_ROOT=/usr -DCMAKE_CUDA_COMPILER=/usr/local/cuda-10.2/bin/nvcc  -DWITH_NCCL=OFF -DCUDA_ARCH_NAME=All

make -j2
```
我们的同事使用这个指令编译是没问题的
