### ISSUE TITLE
模型训练问题

### ISSUE THREAD

**Issue by 6w6w** [PaddlePaddle/Paddle#44079]
### 问题描述 Please describe your issue

我的账号在使用ai studio在线平台训练CNN模型时，第二次迭代时训练误差就降到了非常非常小，但是使用别人的账号，相同设置情况下，误差能够正常下降！

**Comment by Aganlengzi** [comment]
> 但是使用别人的账号，相同设置情况下，误差能够正常下降！

谢谢您的反馈，账号差异造成的问题请联系aistudio的相关开发人员帮忙分析。

**Comment by Ligoml** [comment]
<img width="150" alt="image" src="https://user-images.githubusercontent.com/39876205/177525729-a28ee5e8-ee71-4e77-adf2-4c57d3bd24c5.png">
aistudio的使用问题可以通过这个[渠道](https://aistudio.baidu.com/aistudio/index)反馈哈~
