### ISSUE TITLE
显卡是 RTX-3060的  系统是win11  cuda使用10.2（只能下win10版本）。。。  paddle.utils.run_check()执行后一直无反应

### ISSUE THREAD

**Issue by LmonZero** [PaddlePaddle/Paddle#44077]
### 请提出你的问题 Please ask your question

![image](https://user-images.githubusercontent.com/56548943/177195512-bdfac87a-35f3-49f3-8969-bc47eebdf047.png)
界面如图

**Comment by Aganlengzi** [comment]
你好非常感谢您的反馈，感谢您对paddle的支持。
关于您提供的该问题之前issue有过反馈，可以通过升级cuda版本解决，原因是30系列的显卡不支持CUDA10了，
具体可以参考：https://github.com/PaddlePaddle/Paddle/issues/39154 https://github.com/PaddlePaddle/Paddle/issues/39256  https://github.com/PaddlePaddle/Paddle/issues/38934

**Comment by Aganlengzi** [comment]
@LmonZero 请问是否已经解决？

**Comment by LmonZero** [comment]
问题已解决


| |
林喜钦
|
|
***@***.***
|
在2022年7月6日 ***@***.***> 写道：

@LmonZero 请问是否已经解决？

**Comment by Aganlengzi** [comment]
好的，那issue我close了，有问题欢迎再open~
