### ISSUE TITLE
有没有现成编译好的带TRT的whl包？

### ISSUE THREAD

**Issue by MLrookie** [PaddlePaddle/Paddle#44088]
### 需求描述 Feature Description

任务目标（请描述你正在做的项目是什么，如模型、论文、项目是什么？）
目前正在尝试部署paddle的tts项目，想尝试下trt的加速效果，但是自己编译总是会出现一堆错误。; 
<br /> 需求场景（请描述你的项目中为什么需要用此功能）
有没有现成编译好的带TRT的whl包？paddle版本要求2.2及以上，我试过2.1的了，会报错;  

### 替代实现 Alternatives

没有whl包的话docker镜像也可以。

**Comment by Aganlengzi** [comment]
你好，请参考这个页面：
https://www.paddlepaddle.org.cn/inference/optimize/paddle_trt.html#yi-huanjingzhunbei

**Comment by MLrookie** [comment]
> 你好，请参考这个页面： https://www.paddlepaddle.org.cn/inference/optimize/paddle_trt.html#yi-huanjingzhunbei

你好，我看了一下，这里面好像没有带trt的whl包，或者你看看哪个标签是带trt的，谢谢！

**Comment by Aganlengzi** [comment]
@MLrookie 抱歉，文档链接似乎有问题，我找了下 ，看是否满足您的需要：
https://paddleinference.paddlepaddle.org.cn/user_guides/download_lib.html#python

**Comment by MLrookie** [comment]
> @MLrookie 抱歉，文档链接似乎有问题，我找了下 ，看是否满足您的需要： https://paddleinference.paddlepaddle.org.cn/user_guides/download_lib.html#python

这里面就有了，我先下载看看，感谢感谢！

**Comment by Aganlengzi** [comment]
@MLrookie 请问是否已经解决？

**Comment by MLrookie** [comment]
> @MLrookie 请问是否已经解决？

可以了，多谢！

**Comment by Ligoml** [comment]
@Wilber 请及时修复文档问题~
