### ISSUE TITLE
Multiple GPUS: low performance

### ISSUE THREAD

**Issue by Sampson1107** [PaddlePaddle/Paddle#4408]
你好，
我用的模型是：https://github.com/PaddlePaddle/models/tree/develop/image_classification
我在该模型下：测试了如下三个模型：Alexnet\Googlenet\Resnet，但是单卡的绝对性能比较差，而且弱扩展性也不好.

是否是因为cudnn没有调用过的问题导致？
我在alexnet.py中加入了layer_type='cudnn_conv'性能没有什么变化。
是否还有其他地方需要修改呢？
表格如下：其中分别表示GPU卡数在1、2、4时，网络模型每秒训练的图片数目，我用的卡是Tesla P40，
alexnet每个卡我用的batch_size是1024，googlenet设置的batch_size为每个卡128，resnet是32

| GPU | 1 | 2 |4 |
| :------| ------: | :------: | :------: |
| alexnet | 638 | 851 | 1082 |
| googlenet | 277 | 441 | 662 |
| resnet | 75 | 134 | 241 |

**Comment by kuke** [comment]
从测试结果来看，多卡有加速但非线性加速，应该算是较为正常的情况

**Comment by Sampson1107** [comment]
@kuke 
但是单卡的性能相比其他框架来说，性能低很多，所以我在想，是不是cudnn没有利用好导致的？因为用的gpu卡是P40卡，是比较先进的卡了。

**Comment by kuke** [comment]
@Sampson1107 可有相同的网络结构在不同的框架中的测试结果？如果没有对比，就不能说paddle性能低很多。

**Comment by Sampson1107** [comment]
@kuke 
Kuke，
你好！
我测试了很多框架，说这个性能低的原因是因为我是与其他框架对比了的。
最近我发现，其中影响比较大的是数据读取部分导致，我直接用你们提供的benchmark下的image例子来测试alexnet，4卡可以达到每秒处理4000张图片左右的性能，但是这个数据读取是随机生成的图片，如上我测试的数据是通过PIL方式读取实际图片（Imagenet 2012 dataset）测试出来的性能。
