### ISSUE TITLE
默认capi 的demo 是编译不过的么

### ISSUE THREAD

**Issue by VamWolf** [PaddlePaddle/Paddle#4409]
默认capi 的demo 是编译不过的么. 少了include 的路径吧

/home/work/paddle_new/trunk/paddle/capi/examples/model_inference/multi_thread/main.c:1:25: 
paddle/capi.h: No such file or directory
/home/work/paddle_new/trunk/paddle/capi/examples/model_inference/multi_thread/main.c: In function `thread_main':
/home/work/paddle_new/trunk/paddle/capi/examples/model_inference/multi_thread/main.c:13: error: `paddle_gradient_machine' undeclared (first use in this function)
/home/work/paddle_new/trunk/paddle/capi/examples/model_inference/multi_thread/main.c:13: error: (Each undeclared identifier is reported only once

**Comment by gongweibao** [comment]
你的makefile里边没有设置include的path吧？

**Comment by VamWolf** [comment]
已经搞定了，不过觉得，这种默认的东西，demo 发布的时候，可以把include ，lib 路径都默认放进去.

**Comment by Xreki** [comment]
c-api demo默认Paddle的C-API库安装在系统的标准路径下，另外，不同用户安装Paddle的路径不一样，也很难在`CMakeLists.txt`里面指定。

**Comment by veridone** [comment]
可以详细说一下怎么改能编译过吗？

**Comment by veridone** [comment]
运行直接core
./dense 
I0224 13:47:08.581594  3647 Util.cpp:166] commandline:  --use_gpu=False 
I0224 13:47:08.582569  3647 GradientMachine.cpp:83] Loading parameters from models/pass_4
I0224 13:47:08.582612  3647 Parameter.cpp:327] missing parameters [models/pass_4/___fc_layer_0__.w0] while loading model.
F0224 13:47:08.582621  3647 Parameter.cpp:329] ___fc_layer_0__.w0 missing, not allowed.
*** Check failure stack trace: ***
    @     0x7fb156d2372d  google::LogMessage::Fail()
    @     0x7fb156d271dc  google::LogMessage::SendToLog()
    @     0x7fb156d23253  google::LogMessage::Flush()
    @     0x7fb156d286ee  google::LogMessageFatal::~LogMessageFatal()
    @     0x7fb157015e4a  paddle::Parameter::load()
    @     0x7fb156d6180c  paddle::GradientMachine::loadParameters()
    @     0x7fb156d1f505  paddle_gradient_machine_load_parameter_from_disk
    @           0x40125a  main
    @     0x7fb1568ebb45  __libc_start_main
    @           0x401009  (unknown)
    @              (nil)  (unknown)
Aborted (core dumped)
