### ISSUE TITLE
使用aistudio时文件出现‘xxx  is not UTF-8 encoded’

### ISSUE THREAD

**Issue by lzzzzj** [PaddlePaddle/Paddle#44105]
### bug描述 Describe the Bug

双击文件时显示‘xxx  is not UTF-8 encoded’，并且是同时有很多文件出现。
这些文件我没有动过，上一次关闭环境之前还能正常运行，再次打开环境后运行就报错了。
![adc895d3bcb7bd40433a55a31828422](https://user-images.githubusercontent.com/57863550/177317596-06cf2a8c-4149-493f-b8b5-b048251f5958.png)

包括一些模型文件也损坏了，大小由几百M变成了几百k，还有一些代码文件等。
将这些文件下载下来后打开显示乱码，改变编码格式后仍然为乱码。
请问是什么原因引起的？已损坏的文件可以找回吗？谢谢。

**Comment by Aganlengzi** [comment]
> 使用aistudio时文件出现‘xxx is not UTF-8 encoded’

谢谢您的反馈，该问题非Paddle框架问题，请联系aistudio的相关开发人员帮忙分析。
