### ISSUE TITLE
paddle.crop shape使用默认参数None报错

### ISSUE THREAD

**Issue by liyongchao911** [PaddlePaddle/Paddle#44117]
### bug描述 Describe the Bug

“”“
code block: : python

import paddle
print(paddle.__version__)

demo = paddle.to_tensor([[1,2,3],[4,5,6],[7,8,9]])
res = paddle.crop(demo)

___
result:
2.3.0
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
~\AppData\Local\Temp\ipykernel_12388\599254282.py in <module>
      3 
      4 demo = paddle.to_tensor([[1,2,3],[4,5,6],[7,8,9]])
----> 5 res = paddle.crop(demo)

~\anaconda3\envs\paddle2.3\lib\site-packages\paddle\fluid\layers\nn.py in crop_tensor(x, shape, offsets, name)
   9456         shape.stop_gradient = True
   9457         ipts['Shape'] = shape
-> 9458     elif utils._contain_var(shape):
   9459         new_shape_tensor = []
   9460         shape_attr = []

~\anaconda3\envs\paddle2.3\lib\site-packages\paddle\fluid\layers\utils.py in _contain_var(list_or_tuple)
    290     Check whether list or tuple contains variable.
    291     """
--> 292     for item in list_or_tuple:
    293         if isinstance(item, Variable):
    294             return True

TypeError: 'NoneType' object is not iterable
”“”

### 其他补充信息 Additional Supplementary Information

API定义中： paddle.crop(x, shape=None, offsets=None, name=None)
意味着shape是一个默认参数，默认为None, 但是执行过程中不传入shape会报“'NoneType' object is not iterable”的错误。
说明代码中需要加入 if shape is None: shape = x.shape的业务逻辑判断

**Comment by luotao1** [comment]
close by #46813
