### ISSUE TITLE
pool2d层的计算量

### ISSUE THREAD

**Issue by fanxiaochen456** [PaddlePaddle/Paddle#44112]
### 请提出你的问题 Please ask your question

您好，我将Tensorflow的固化模型.pb通过x2paddle的方式转化为paddle的模型，使用paddle.flops打印每层的计算量时发现pool2d也会产生计算量，参考官网文档有关网络层参数量和计算量的计算公式，发现使用的池化层并没有产生计算量，请问这里的pool2d为什么会产生计算量呢？他的计算公式又是什么呢？
![image](https://user-images.githubusercontent.com/101849755/177457161-f5870e64-c58a-424b-8553-e53a6dc6f65c.png)

**Comment by yingyibiao** [comment]
请问您这边使用的具体是什么池化操作以及可以提供一下参考的文档链接吗？

**Comment by fanxiaochen456** [comment]
@yingyibiao 您好，我的参考链接是这个，https://paddlepedia.readthedocs.io/en/latest/tutorials/CNN/ParamsCounter.html#:~:text=2.1%20%E5%BD%92%E4%B8%80%E5%8C%96%E5%B1%82%E5%8F%82%E6%95%B0%E9%87%8F%E8%AE%A1%E7%AE%97%20%E7%94%B1%E4%BA%8E%E5%BD%92%E4%B8%80%E5%8C%96%E5%B1%82%E8%BE%83%E4%B8%BA%E7%AE%80%E5%8D%95%EF%BC%8C%E8%BF%99%E9%87%8C%E7%9B%B4%E6%8E%A5%E5%86%99%E5%87%BA%E5%85%AC%E5%BC%8F%EF%BC%9A%20%24%20P%20a%20r%20a,4%20%E2%88%97%20C%20o%20u%20t%20%24%20%E5%85%B6%E4%B8%AD4%E8%A1%A8%E7%A4%BA%E5%9B%9B%E4%B8%AA%E5%8F%82%E6%95%B0%E5%80%BC%EF%BC%8C%E6%AF%8F%E4%B8%AA%E7%89%B9%E5%BE%81%E5%9B%BE%E5%AF%B9%E5%BA%94%E4%B8%80%E7%BB%84%E5%9B%9B%E4%B8%AA%E5%85%83%E7%B4%A0%E7%9A%84%E5%8F%82%E6%95%B0%E7%BB%84%E5%90%88%EF%BC%9B
具体的池化操作在原模型中使用的是Keras底层的上采样函数UpSampling2D，

**Comment by yingyibiao** [comment]
我看了一下文档，里面没有提到 UpSampling2D 的 flops 为 0 啊。
Keras 的 UpSampling2D 在 Paddle 对应的 API 为 UpsamplingNearest2D 或者 UpsamplingBilinear2D。
具体的计算公式可以参考：https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/hapi/static_flops.py#L158
