### ISSUE TITLE
安装paddle gpu run_check()测试卡死

### ISSUE THREAD

**Issue by Shrinco** [PaddlePaddle/Paddle#44140]
### 问题描述 Issue Description

我电脑是win11，自带的cuda是11.6，我安装了cuda10.2和配套的cudnn7.6.5。然后在anaconda 
python3.7的环境里pip 安装了paddle gpu 2.3.0，在使用 paddle.utils.run_check()时，程序卡在了如下图的位置 一直没有反应，等待了大约十几分钟后才出现结果。请问是什么原因？
![image](https://user-images.githubusercontent.com/50402380/177675542-de2ff7a2-9b89-4358-a390-799efa9cd629.png)
![image](https://user-images.githubusercontent.com/50402380/177675598-02faa0f7-eea2-418a-9c3c-7225dbb59a3e.png)

### 版本&环境信息 Version & Environment Information

paddle version: 2.3.0
paddle with cuda: 10.2

python version: 3.7

cuda ver: 10.2
cudnn ver: 7.6.5
nvidiv driver version:512.74

**Comment by rainyfly** [comment]
你好，看截图应该是安装成功的，你再次import paddle会需要很久么？可以看看直接使用它训练程序会不会报错

**Comment by Shrinco** [comment]
你好，import paddle很快。但我试了一个训练程序，用gpu训练mnist模型，结果确实一样，程序卡在这里无法执行下去
![image](https://user-images.githubusercontent.com/50402380/177697685-6e57c086-052f-42d7-b508-920ab4282698.png)
          ###########


> 你好，看截图应该是安装成功的，你再次import paddle会需要很久么？可以看看直接使用它训练程序会不会报错

**Comment by rainyfly** [comment]
请问你用的GPU卡是哪个型号的呢

**Comment by Shrinco** [comment]
> 请问你用的GPU卡是哪个型号的呢

你好，我的是NVIDIA GeForce RTX 3050 Laptop GPU，是因为30系列显卡和cuda版本不兼容导致的吗？需要换成11.2的cuda吗？

**Comment by rainyfly** [comment]
你要不直接试一下11.2的版本试试

**Comment by Shrinco** [comment]
> 你要不直接试一下11.2的版本试试

好的，我去试一下。谢谢

**Comment by Shrinco** [comment]
> 你要不直接试一下11.2的版本试试

问题解决了，谢谢！我装了cuda11.2 cudnn8.2，再用paddle run_check()测试时没有卡死了，我也用了一个小例程来训练也没有卡住了，很快就出了结果。
![image](https://user-images.githubusercontent.com/50402380/177898452-e84c2b94-d0b8-4586-bc86-9f8367f7a919.png)
