### ISSUE TITLE
PR-CI-Coverage fails - no space left on device

### ISSUE THREAD

**Issue by zuzg** [PaddlePaddle/Paddle#44162]
### 问题描述 Issue Description

All required CIs pass, but running PR-CI-Coverage fails and the log shows `No space left on device`. I re-runed the pipeline twice and the problem persists. Please resolve the issue as it blocks my work. <br>
See the mentioned PR: [#44124](https://github.com/PaddlePaddle/Paddle/pull/44124)

### 版本&环境信息 Version & Environment Information

https://xly.bce.baidu.com/paddlepaddle/paddle/newipipe/detail/6048453/job/16427973

**Comment by wozna** [comment]
Already fixed
