### ISSUE TITLE
模型可视化

### ISSUE THREAD

**Issue by Lilengli** [PaddlePaddle/Paddle#44167]
### 请提出你的问题 Please ask your question

我在使用ssd模型时，直接使用print(model)打印出来的只有卷积层，没有相关的relu，以及box等节点的信息，请问我需要怎样操作才能把模型全部的层打印出来呢，我希望可以像利用paddle.summary和paddle.flops那样打印出模型的机构和各个层的名称等信息

**Comment by zkh2016** [comment]
你好，请问可以提供下使用的paddle版本和相关代码吗？

**Comment by zkh2016** [comment]
你好，我看这个问题和#44165中提到的是一个问题，在[#44165](https://github.com/PaddlePaddle/Paddle/issues/44165)中讨论吧。
