### ISSUE TITLE
飞腾kylinv10 cpu版本编译失败

### ISSUE THREAD

**Issue by tantailong** [PaddlePaddle/Paddle#44166]
### bug描述 Describe the Bug

In file included from /root/githubcode/Paddle/paddle/fluid/operators/memcpy_h2d_op.cc:12:0:
/root/githubcode/Paddle/paddle/fluid/operators/memcpy_h2d_op.h: In member function ‘void paddle::operators::MemcpyH2DFunctor::operator()(const LoDTensor&) const’:
/root/githubcode/Paddle/paddle/fluid/operators/memcpy_h2d_op.h:46:10: error: variable ‘stream’ set but not used [-Werror=unused-but-set-variable]
     auto stream = nullptr;
          ^~~~~~

### 其他补充信息 Additional Supplementary Information

In file included from /root/githubcode/Paddle/paddle/fluid/operators/memcpy_h2d_op.cc:12:0:
/root/githubcode/Paddle/paddle/fluid/operators/memcpy_h2d_op.h: In member function ‘void paddle::operators::MemcpyH2DFunctor::operator()(const LoDTensor&) const’:
/root/githubcode/Paddle/paddle/fluid/operators/memcpy_h2d_op.h:46:10: error: variable ‘stream’ set but not used [-Werror=unused-but-set-variable]
     auto stream = nullptr;
          ^~~~~~

**Comment by qili93** [comment]
hi, 这错误是 CMAKE 命令修改一下就可以避免这个问题，可以参考以下文档中的 cmake 命令

https://github.com/PaddlePaddle/Paddle-Inference-Demo/blob/master/docs-official/guides/hardware_support/cpu_phytium_cn.md

注意这里需要添加 `-DCMAKE_CXX_FLAGS="-Wno-error -w"` 来避免上述编译错误的出现。
