### ISSUE TITLE
post_hook对于特定层的操作

### ISSUE THREAD

**Issue by Lilengli** [PaddlePaddle/Paddle#44165]
### 请提出你的问题 Please ask your question

我想利用post_hook函数对于我的模型结构中的一些特定层的输出进行处理，请问paddle是否支持这样的操作，是否有具体的实现样例，谢谢！

**Comment by zkh2016** [comment]
你好，这里有个类似的方法看下是否满足你的需求：[添加额外的执行逻辑](https://www.paddlepaddle.org.cn/documentation/docs/zh/guides/advanced/layer_and_model_cn.html#tianjiaewaidezhixingluoji)

**Comment by Lilengli** [comment]
> 你好，这里有个类似的方法看下是否满足你的需求：[添加额外的执行逻辑](https://www.paddlepaddle.org.cn/documentation/docs/zh/guides/advanced/layer_and_model_cn.html#tianjiaewaidezhixingluoji)

你好，这个样例我之前看过，但是我不知道的是如何对于特定层操作，比如说我要对于某一个卷积层conv2d对他的输出，对于relu的输出进行操作，但是样例好像并没有

**Comment by zkh2016** [comment]
哈喽，我写了个简单的例子，看下是否是你想要的：
```
import paddle
import paddle.nn as nn

def post_hook(layer, input, output):
    print('call post_hook')
    return output*2

class SimpleNet(nn.Layer):
    def __init__(self):
        super(SimpleNet, self).__init__()
        self.conv1 = nn.Conv2D(4,6,3)
        self.relu1 = nn.ReLU()
        self.conv2 = nn.Conv2D(6,6,3)
        self.relu2 = nn.ReLU()

        self.conv1.register_forward_post_hook(post_hook)

    def forward(self, x):
        out = self.conv1(x)
        out = self.relu1(out)
        out = self.conv2(out)
        out = self.relu2(out)
        return out


model = SimpleNet()
x = paddle.uniform((2, 4, 8, 8), dtype='float32', min=-1., max=1.)
model(x)
```

**Comment by Lilengli** [comment]
非常感谢您的回复，我的目的大致就是这样，但是是针对于像yolo_mobilenet,ssd_mobilenet这样的模型，利用了paddledetection的模型配置文件，所以可能没有具体的层构建过程，我这里只有这个层的名称（通过可视化得到），请问还可以用post_hook对于特定层操作嘛，就像您写的代码一样

**Comment by zkh2016** [comment]
这样操作也是可以的，通过print(model)可以知道里面有conv1这个layer，然后model.conv1.register_forward_post_hook：
```
#self.conv1.register_forward_post_hook(post_hook)
model = SimpleNet()
model.conv1.register_forward_post_hook(post_hook)
```

**Comment by Lilengli** [comment]
您好，为什么我在print(model)之后，print出来的模型结构和我在netron中看到的不一样呢，而且print出来的只有相关的卷积层和量化单元，并没有relu激活层。
![image](https://user-images.githubusercontent.com/93658838/177927641-2f01534f-820f-4563-a1e8-8df39ddb3e54.png)
![image](https://user-images.githubusercontent.com/93658838/177927694-912a20dc-fc51-4782-ab11-60cc180c3fee.png)
这是我的代码
![image](https://user-images.githubusercontent.com/93658838/177927764-0427a3f7-23d7-46ca-8a47-77309fd60f6b.png)

**Comment by wangxinxin08** [comment]
relu不是以layer的形式定义的，是使用function的形式定义的，所以print(model）看不到

**Comment by Lilengli** [comment]
那请问应该怎么样看到整体的结构呢

**Comment by wangxinxin08** [comment]
> 那请问应该怎么样看到整体的结构呢

在PaddleDetection issue中回复了

**Comment by Lilengli** [comment]
好的，感谢您
