### ISSUE TITLE
paddle.Model高级API训练模型，如何导出nb供paddle lite推理使用？

### ISSUE THREAD

**Issue by fengyanWang** [PaddlePaddle/Paddle#44160]
### 请提出你的问题 Please ask your question

model = paddle.Model(PoseNet(pose_num=3,pretrained=True))
optim = paddle.optimizer.Adam(learning_rate=1e-4,parameters=model.parameters())
model.prepare(optim, paddle.nn.MSELoss())
model.fit(train_dataset, validation_dataset, save_dir="../checkpoints/pd_hudu",save_freq=2,epochs=60, batch_size=512)

类似于上述代码，使用paddle.Model等高级API训练模型，请问应该调用哪些函数生成NB模型供paddle lite部署使用？(找了很久文档，很懵)

**Comment by rainyfly** [comment]
https://paddle-lite.readthedocs.io/zh/latest/user_guides/python_demo.html ，可以看一下这个文档，另外，NB模型？
