### ISSUE TITLE
build failed about atomic

### ISSUE THREAD

**Issue by tensor-tang** [PaddlePaddle/Paddle#4417]
hi 
just encounter an issue with latest commit 6f9a9a93b6d8355f97f3073b31006119faf81f21

> paddle/framework/operator.cc: In member function ‘void paddle::framework::OperatorBase::GenerateTemporaryNames()’:
> paddle/framework/operator.cc:194:10: error: ‘atomic’ in namespace ‘std’ does not name a type
>    static std::atomic<size_t> gUniqId(0UL);

CentOS Linux release 7.3.1611 (Core)

gcc version
> g++ (GCC) 4.8.5 20150623 (Red Hat 4.8.5-11)
> Copyright (C) 2015 Free Software Foundation, Inc.

It works after added `#include <atomic>`

**Comment by luotao1** [comment]
Both @xieyk and me couldn't reappear this problem. 
What's your cmake option?

**Comment by tensor-tang** [comment]
My cmake options:
`cmake .. -DWITH_GPU=OFF -DWITH_STYLE_CHECK=OFF -DWITH_TESTING=ON -DWITH_TIMER=OFF -DWITH_SWIG_PY=ON -DWITH_DSO=OFF -DWITH_MKLDNN=ON -DWITH_MKLML=ON`

**Comment by luotao1** [comment]
Maybe the reason of CentOS 7.3, but it's no harm to add `#include <atomic>`. Could you create a PR to fix it ?

**Comment by tensor-tang** [comment]
OK, sure,  will update soon.

**Comment by luotao1** [comment]
I reappear this compiler problem in `ONLYCPU` mode. Should our teamcity check `ONLYCPU` mode? @helinwang

**Comment by helinwang** [comment]
@luotao1 Currently we have CPU nightly build, which build with `WITH_GPU=OFF`. Curious why we have another flag `ONLYCPU`, feels like it duplicate with `WITH_GPU=OFF`.

**Comment by luotao1** [comment]
@helinwang  Oh, the `ONLYCPU` mode means `WITH_GPU=OFF`. And how do think #4476 as @emailweixu suggests?

**Comment by helinwang** [comment]
That's a good idea (replied details in that issue).
