### ISSUE TITLE
paddle inference 预测时显存溢出

### ISSUE THREAD

**Issue by whjdark** [PaddlePaddle/Paddle#44172]
### bug描述 Describe the Bug

将动态图模型动转静后使用paddle inference在GPU上预测失败，提示显存溢出。
（注：动态图下训练和预测是正常的）
paddle版本：paddlepaddle2.3.0
环境：aistudio高级版（V100 32G） 和 本地Linux RTX3080 CUDA 11.2均失败

```shell
------------------------------------------------ [1, 3, 640, 640]
W0708 13:25:16.334091 15927 operator.cc:284] unsqueeze2 raises an exception paddle::memory::allocation::BadAlloc, ResourceExhaustedError: 

Out of memory error on GPU 0. Cannot allocate 100.000000MB memory on GPU 0, 31.684326GB memory has been allocated and available memory is only 65.750000MB.

Please check whether there is any other process using GPU 0.
1. If yes, please stop them, or start PaddlePaddle on another GPU.
2. If no, please decrease the batch size of your model. 
If the above ways do not solve the out of memory problem, you can try to use CUDA managed memory. The command is `export FLAGS_use_cuda_managed_memory=false`.
 (at /paddle/paddle/fluid/memory/allocation/cuda_allocator.cc:87)
Traceback (most recent call last):
  File "predict.py", line 183, in <module>
    process(src_image_dir, save_dir)
  File "predict.py", line 158, in process
    predictor.run()
RuntimeError: ResourceExhaustedError: 

Out of memory error on GPU 0. Cannot allocate 100.000000MB memory on GPU 0, 31.684326GB memory has been allocated and available memory is only 65.750000MB.

Please check whether there is any other process using GPU 0.
1. If yes, please stop them, or start PaddlePaddle on another GPU.
2. If no, please decrease the batch size of your model. 
If the above ways do not solve the out of memory problem, you can try to use CUDA managed memory. The command is `export FLAGS_use_cuda_managed_memory=false`.
 (at /paddle/paddle/fluid/memory/allocation/cuda_allocator.cc:87)
```

可以加下技术人员地联系方式吗，把代码和模型发给你们。

**Comment by zkh2016** [comment]
你好，可以先排查下当前使用的卡是否显存已经不足？可以使用CUDA_VISIBLE_DEVICES=1 换张卡试试。

**Comment by whjdark** [comment]
> CUDA_VISIBLE_DEVICES=1
在Aistudio上启动之前显存占用为0（没有其他程序占用CUDA），启动后突然占用满31.7G，然后报错。
（注：动态图下训练和预测是正常的）

**Comment by zkh2016** [comment]
哈喽，确认下测试动态图和静态图预测的输入数据的shape都是一样的是吗？

**Comment by whjdark** [comment]
> 哈喽，确认下测试动态图和静态图预测的输入数据的shape都是一样的是吗？

是一样的

**Comment by zkh2016** [comment]
你那边可以先试试使用[excutor](https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/static/Executor_cn.html#executor)和[load_inference_model](https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/static/load_inference_model_cn.html)这两个API加载执行下看是否正常吗？

**Comment by whjdark** [comment]
> 你那边可以先试试使用[excutor](https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/static/Executor_cn.html#executor)和[load_inference_model](https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/static/load_inference_model_cn.html)这两个API加载执行下看是否正常吗？
我看看问题的好像是输入图像分辨率太大了导致显存溢出，但是同样的分辨率在使用paddle动态图训练推理都没有显存溢出的情况。而且还观察到inference速度（开启TRT）比paddle动态图推理还慢。

**Comment by Wangzheee** [comment]
您好，可以提供一下模型吗？我们这边复现一下

**Comment by Wangzheee** [comment]
另外针对unsqueeze2等一系列op Paddle Inference develop版本最近两个星期做了更新，可以启用tensorrt再试一下（develop版本需要本地源码编译一下https://paddle-inference.readthedocs.io/en/latest/guides/install/compile/compile_basic.html ）

**Comment by whjdark** [comment]
> 您好，可以提供一下模型吗？我们这边复现一下
我用的别人的模型测试
https://aistudio.baidu.com/aistudio/projectdetail/4136063?channelType=0&channel=0

**Comment by Wangzheee** [comment]
您好，看样子您已经动转静成功了。https://www.paddlepaddle.org.cn/documentation/docs/zh/guides/beginner/model_save_load_cn.html
可以提供下保存后的静态图模型吗？我们这边可以让PM联系您～

**Comment by Wangzheee** [comment]
可以用百度网盘上传 静态图模型的链接～
