### ISSUE TITLE
量化反量化的实现

### ISSUE THREAD

**Issue by Lilengli** [PaddlePaddle/Paddle#44189]
### 请提出你的问题 Please ask your question

1. 我在使用apu作为硬件导出时，看到opt导出的nb模型中加入了一个calib节点，这个calib节点的作用是int8-float32，但是在我导出静态图模型时，并没有在这个路径上加入反量化方法，请问这个是什么问题呢，
![image](https://user-images.githubusercontent.com/93658838/178096509-277d22bf-e4b2-44ff-9815-10bdb039b71c.png)
![image](https://user-images.githubusercontent.com/93658838/178096527-7f747953-7e1e-4f05-b650-543926dac9e9.png)

2. paddle支持反量化吗，有什么反量化方法吗？

**Comment by yghstill** [comment]
@Lilengli 可以检查下subgraph里有没有conv、fc等量化op，一般量化后会将数据类型cast成fp32

**Comment by Lilengli** [comment]
> @Lilengli 可以检查下subgraph里有没有conv、fc等量化op，一般量化后会将数据类型cast成fp32
感谢您的回复，但是我已经确认了subgraph里面是有conv卷积层的，prior_box节点接受的是relu的输出，但是从这个多输出conv卷积层的relu输出到prior_box节点之间没有量化op

**Comment by yghstill** [comment]
@Lilengli conv+relu会融合，都会跑在int8的kernel里，之后需要cast成fp32，所以有calib算子。
