### ISSUE TITLE
关于MAOutputScaleLayer的使用问题

### ISSUE THREAD

**Issue by Lilengli** [PaddlePaddle/Paddle#44193]
### 请提出你的问题 Please ask your question

我注意到模型的每一层都加入了MAoutputScaleLayer，请问添加这一层的目的和作用是什么呢

**Comment by yghstill** [comment]
@Lilengli MAoutputScaleLayer主要是为了统计每一层激活的scale值，实际部署时需要获取conv、fc后的scale值，所以大部分激活层的前面都会插入MAoutputScaleLayer节点。
