### ISSUE TITLE
paddleocr预训练模型微调

### ISSUE THREAD

**Issue by stupidrocket** [PaddlePaddle/Paddle#44199]
### 请提出你的问题 Please ask your question

使用paddleocr预训练模型微调，训练时训练集正确率从0.1开始上升，但我直接使用预训练模型预测的正确率在0.9以上，如何在微调的时候让训练初始正确率从0.9开始变化？

**Comment by tink2123** [comment]
python3  tools/train.py -c xxx.yml -o Global.pretrained_model={model_path}/best_accuracy

使用上述命令，在训练时加载预训练模型

**Comment by stupidrocket** [comment]
> python3 tools/train.py -c xxx.yml -o Global.pretrained_model={model_path}/best_accuracy
> 
> 使用上述命令，在训练时加载预训练模型

我在config文件里已经设置了pretrained_model，训练时显示加载成功

**Comment by tink2123** [comment]
预测准确率0.9以上，不代表在训练集上也可以达到0.9。数据分布不同，模型准确率变化会比较大。
