### ISSUE TITLE
请问一下paddle是否可以脱离python环境使用?

### ISSUE THREAD

**Issue by Salitanr** [PaddlePaddle/Paddle#44196]
### 请提出你的问题 Please ask your question

请问一下paddle是否可以脱离python环境使用?比如仅依赖c++环境做训练与预测，我不太了解python

**Comment by skywalk163** [comment]
只使用c++环境预测是可以的。
但是训练，建议用python环境，否则编码效率太低。

**Comment by qljsky** [comment]
感谢您的回复，这代表着使用c++训练也可以是吧，pytorch能查到前端组网训练的c++接口，paddle相关的接口在哪里？
如果我想基于paddle或者paddlex做一个类似paddlex gui的前端工具，您有什么建议吗？paddlex gui是如何实现将组网训练集成到前端的，是直接使用c++接口？还是将pytohon解释器集成进来执行python脚本？或者其他方式

**Comment by Salitanr** [comment]
> 只使用c++环境预测是可以的。 但是训练，建议用python环境，否则编码效率太低。

感谢您的回复，这代表着使用c++训练也可以是吧，pytorch能查到前端组网训练的c++接口，paddle相关的接口在哪里？
如果我想基于paddle或者paddlex做一个类似paddlex gui的前端工具，您有什么建议吗？paddlex gui是如何实现将组网训练集成到前端的，是直接使用c++接口？还是将pytohon解释器集成进来执行python脚本？或者其他方式

**Comment by ziyoujiyi** [comment]
> 

可以看下 pybind.cc、fleet_py.cc  等绑定 python 和 c++ 接口的文件

**Comment by skywalk163** [comment]
具体细节我没有了解这么清楚。 我知道和理解的是，飞桨底层是C++代码，然后再用python调用。比如参考这个文档：https://www.paddlepaddle.org.cn/documentation/docs/zh/guides/custom_op/new_cpp_op_cn.html
我们常规写了自定义算子还要python注册一下，理论上你可以省掉python注册那块，直接c++调用算子。

paddlex那块，重写多累，跟官方一块吧，反正也是开源的。

**Comment by ziyoujiyi** [comment]
纯 C++ 端训练暂不支持

**Comment by qljsky** [comment]
> 纯 C++ 端训练暂不支持

如果借助boost.python呢?
