### ISSUE TITLE
分布式训练失败   SocketChannel.cpp:101] Check failed: len > 0......

### ISSUE THREAD

**Issue by Sampson1107** [PaddlePaddle/Paddle#4419]
老师，
你好!
我在按照http://doc.paddlepaddle.org/doc_cn/howto/usage/cluster/cluster_train_cn.html 说明做分布式训练的时候总是遇到如下错误。我使用的脚本是：
paddle/benchmark/paddle/image/alexnet.py作为config模型文件
conf.py内容如下：
HOSTS = [
    "root@192.168.100.67",
    "root@192.168.100.68",
]
'''
workspace configuration
'''
#root dir for workspace, can be set as any director with real user account
ROOT_DIR = "/home/users/AI/paddle/benchmark/paddle/image"
'''
network configuration
'''
#pserver nics
PADDLE_NIC = "eno1"
#pserver port
PADDLE_PORT = 12345
#pserver ports num
PADDLE_PORTS_NUM = 8
#pserver sparse ports num
PADDLE_PORTS_NUM_FOR_SPARSE = 2

#environments setting for all processes in cluster job
LD_LIBRARY_PATH = "/usr/local/cuda/lib64:/usr/lib64:/home/users/cudnn/cudnn6.0/lib64:/home/users/openmpi/lib"

run.sh如下：
python paddle2.py \
  --job_dispatch_package="/home/users/AI/paddle/benchmark/paddle/image" \
  --dot_period=10 \
  --ports_num_for_sparse=2 \
  --log_period=50 \
  --num_passes=10 \
  --trainer_count=4 \
  --saving_period=1 \
  --local=0 \
  --config=/home/users/AI/paddle/benchmark/paddle/image/alexnet.py \
  --save_dir=./output \
  --use_gpu=1

报错信息如下：
I0927 10:21:46.176991 43449 ParameterClient2.cpp:379] send thread 10 started
I0927 10:21:46.177026 43450 ParameterClient2.cpp:409] recv thread 10 started
I0927 10:21:46.177057 43451 ParameterClient2.cpp:379] send thread 11 started
I0927 10:21:46.177083 43452 ParameterClient2.cpp:409] recv thread 11 started
I0927 10:21:46.177114 43453 ParameterClient2.cpp:379] send thread 12 started
I0927 10:21:46.177139 43454 ParameterClient2.cpp:409] recv thread 12 started
I0927 10:21:46.177166 43455 ParameterClient2.cpp:379] send thread 13 started
I0927 10:21:46.177192 43456 ParameterClient2.cpp:409] recv thread 13 started
I0927 10:21:46.177227 43457 ParameterClient2.cpp:379] send thread 14 started
I0927 10:21:46.177253 43458 ParameterClient2.cpp:409] recv thread 14 started
I0927 10:21:46.177284 43459 ParameterClient2.cpp:379] send thread 15 started
I0927 10:21:46.177309 43460 ParameterClient2.cpp:409] recv thread 15 started
F0927 10:21:46.177381 43306 SocketChannel.cpp:101] Check failed: len > 0  peer=192.168.100.67 curIov=0 iovCnt=4 iovs[curIov].base=0x7fff55ff7d40 iovs[curIov].iov_len=16

**Comment by typhoonzero** [comment]
Please check out the FAQ, and then check out if pserver process and trainer process are correctly started after starting the job.

**Comment by Sampson1107** [comment]
@typhoonzero 

这两个节点是我个人在使用的节点，没有其他用户，FAQ中的描述可能无法解决我的问题，另外就是我用的都是本地相同目录，也没有用到共享目录。启动起来后，启动节点没有问题
|=============================================================================|
|    0       731    C   /usr/local/bin/paddle_pserver_main             297MiB |
|    0       849    C   /usr/local/bin/paddle_trainer                  863MiB |
|    1       731    C   /usr/local/bin/paddle_pserver_main             297MiB |
|    1       849    C   /usr/local/bin/paddle_trainer                  791MiB |
|    2       731    C   /usr/local/bin/paddle_pserver_main             297MiB |
|    2       849    C   /usr/local/bin/paddle_trainer                  961MiB |
|    3       731    C   /usr/local/bin/paddle_pserver_main             297MiB |
|    3       849    C   /usr/local/bin/paddle_trainer                  791MiB |
+-----------------------------------------------------------------------------+
2号节点下
只有ps进程，如下：
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID  Type  Process name                               Usage      |
|=============================================================================|
|    0     49128    C   /usr/local/bin/paddle_pserver_main             297MiB |
|    1     49128    C   /usr/local/bin/paddle_pserver_main             297MiB |
|    2     49128    C   /usr/local/bin/paddle_pserver_main             297MiB |
|    3     49128    C   /usr/local/bin/paddle_pserver_main             297MiB |
+-----------------------------------------------------------------------------+
1号节点一直处在等待状态，2号节点开始会有trainer进程，一会儿就没有了，只剩下如上的ps进程，我有几个问题：
1.工作目录是否可以用共享目录？（我开始设置的共享目录，后来又改成了本地目录，共享目录的时候会出现两个节点的日志与Error文件，本地目录的时候只有1号节点的日志文件，1号节点没有出错信息）
2.修改成本地目录后，只是2号节点的paddle_trainer进程出现后消失，2号节点工作目录下不再出现日志目录，也不再出现1楼提出的错误信息。但是作业不能运行下去，因为只有1号节点有paddle_trainer，且一直处于等待状态。

**Comment by typhoonzero** [comment]
建议：
1. 查看每个节点的pserver和trainer的日志，看最早报错的地方是否有有用的信息
1. `PADDLE_PORTS_NUM `设置成1， `PADDLE_PORTS_NUM_FOR_SPARSE`设置成1

> 工作目录是否可以用共享目录？

可以，找到方法使每个节点使用不同的output目录可以避免目录冲突，或者只让一个trainer输出模型，因为每个trainer的参数是一致的。

> 修改成本地目录后，只是2号节点的paddle_trainer进程出现后消失，2号节点工作目录下不再出现日志目录，也不再出现1楼提出的错误信息。但是作业不能运行下去，因为只有1号节点有paddle_trainer，且一直处于等待状态。

只有所有trainer都正常运行才会开始集群训练。先check下是否有有用的错误日志。

**Comment by Sampson1107** [comment]
@typhoonzero 

老师，很抱歉，我今天早上来了按照您的指导，运行一下，发现在2号机器上会出现如下目录：
paddle_trainer.node2.root.log.ERROR.20170928-044608.3880
paddle_trainer.ERROR
paddle_trainer.FATAL
paddle_trainer.WARNING
paddle_trainer.node2.root.log.FATAL.20170928-044608.3880
node2的paddle_trainer.INFO内容如下(以上文件提示的都是如下错误)：
Log file created at: 2017/09/28 04:45:55
Running on machine: dl4
Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
I0928 04:45:55.098786  3880 Util.cpp:166] commandline: /usr/local/bin/paddle_trainer --num_gradient_servers=2 --nics=eno1 --port=7167 --ports_num=1 --comment=paddle_process_by_paddle --pservers=192.168.100.67,192.168.100.68 --ports_num_for_sparse=2 --config=/home/image/alexnet.py --trainer_count=4 --use_gpu=1 --num_passes=10 --save_dir=./output --log_period=50 --dot_period=10 --saving_period=1 --local=0 --trainer_id=1
I0928 04:46:01.006924  3880 Trainer.cpp:165] trainer mode: Normal
I0928 04:46:01.007405  3880 MultiGradientMachine.cpp:99] numLogicalDevices=1 numThreads=4 numDevices=4
I0928 04:46:01.210110  3880 PyDataProvider2.cpp:243] loading dataprovider provider::process
I0928 04:46:01.687975  3880 GradientMachine.cpp:85] Initing parameters..
I0928 04:46:06.191083  3880 GradientMachine.cpp:92] Init parameters done.
I0928 04:46:06.519521  3880 ParameterClient2.cpp:113] pserver 0 192.168.100.67:7167
I0928 04:46:06.519992  3880 ParameterClient2.cpp:113] pserver 1 192.168.100.68:7167
I0928 04:46:08.520457  3964 ParameterClient2.cpp:379] send thread 0 started
I0928 04:46:08.520500  3965 ParameterClient2.cpp:409] recv thread 0 started
I0928 04:46:08.520539  3966 ParameterClient2.cpp:379] send thread 1 started
I0928 04:46:08.520568  3967 ParameterClient2.cpp:409] recv thread 1 started
F0928 04:46:08.520623  3880 SocketChannel.cpp:101] Check failed: len > 0  peer=192.168.100.67 curIov=0 iovCnt=4 iovs[curIov].base=0x7fffbc3d9900 iovs[curIov].iov_len=16
PADDLE_PORT 我设置的7167，每次提交我都会修改这个端口号，请老师帮我看下如上的command line是否有参数错误？PADDLE_PORTS_NUM设置的1， PADDLE_PORTS_NUM_FOR_SPARSE设置的1

**Comment by typhoonzero** [comment]
请double check下pserver的日志是否有有用信息，比如是否有端口无法分配。从日志：
```
/usr/local/bin/paddle_trainer --num_gradient_servers=2 --nics=eno1 --port=7167 --ports_num=1 --comment=paddle_process_by_paddle --pservers=192.168.100.67,192.168.100.68 --ports_num_for_sparse=2 --config=/home/image/alexnet.py --trainer_count=4 --use_gpu=1 --num_passes=10 --save_dir=./output --log_period=50 --dot_period=10 --saving_period=1 --local=0 --trainer_id=1
```
其中`ports_num_for_sparse`还是2。其他的命令参数都是正确的。

另外也请check两台服务器是否有防火墙filter掉了通信的端口。

**Comment by Sampson1107** [comment]
@typhoonzero 
老师psserver日志分别如下：
文件paddle_pserver_main.node2.root.log.INFO.20170928-053838.8964：

Log file created at: 2017/09/28 05:38:38
Running on machine: node2
Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
I0928 05:38:38.576982  8964 Util.cpp:166] commandline: /usr/local/bin/paddle_pserver_main --num_gradient_servers=2 --nics=eno1 --port=7169 --ports_num=1 --ports_num_for_sparse=1 --comment=paddle_process_by_paddle

文件： paddle_pserver_main.INFO
Log file created at: 2017/09/28 05:38:38
Running on machine: node2
Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
I0928 05:38:38.576982  8964 Util.cpp:166] commandline: /usr/local/bin/paddle_pserver_main --num_gradient_servers=2 --nics=eno1 --port=7169 --ports_num=1 --ports_num_for_sparse=1 --comment=paddle_process_by_paddle

文件：server.log 
内容为空

没有什么提示信息
我重新修改了还是一样的错误：
Log file created at: 2017/09/28 05:38:43
Running on machine: dl4
Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
I0928 05:38:43.889294  9053 Util.cpp:166] commandline: /usr/local/bin/paddle_trainer --num_gradient_servers=2 --nics=eno1 --port=7169 --ports_num=1 --comment=paddle_process_by_paddle --pservers=192.168.100.67,192.168.100.68 --ports_num_for_sparse=1 --config=/home/image/alexnet.py --trainer_count=1 --use_gpu=1 --num_passes=10 --save_dir=./output --log_period=50 --dot_period=10 --saving_period=1 --local=0 --trainer_id=1
I0928 05:38:49.592561  9053 Trainer.cpp:165] trainer mode: Normal
I0928 05:38:49.747264  9053 PyDataProvider2.cpp:243] loading dataprovider provider::process
I0928 05:38:50.217455  9053 GradientMachine.cpp:85] Initing parameters..
I0928 05:38:54.715682  9053 GradientMachine.cpp:92] Init parameters done.
I0928 05:38:55.027038  9053 ParameterClient2.cpp:113] pserver 0 192.168.100.67:7169
I0928 05:38:55.027521  9053 ParameterClient2.cpp:113] pserver 1 192.168.100.68:7169
I0928 05:38:57.027951  9117 ParameterClient2.cpp:409] recv thread 0 started
I0928 05:38:57.029408  9116 ParameterClient2.cpp:379] send thread 0 started
I0928 05:38:57.029495  9118 ParameterClient2.cpp:379] send thread 1 started
I0928 05:38:57.029527  9119 ParameterClient2.cpp:409] recv thread 1 started
F0928 05:38:57.029549  9053 SocketChannel.cpp:101] Check failed: len > 0  peer=192.168.100.67 curIov=0 iovCnt=4 iovs[curIov].base=0x7fff91e80850 iovs[curIov].iov_len=16

**Comment by Sampson1107** [comment]
@typhoonzero 

老师，是否有测试网络是否正常的demo，或者是分布式的demo？

**Comment by Sampson1107** [comment]
@typhoonzero 
换了一个节点，可以跑成功了，是1号节点的问题，具体的我再排查一下！

**Comment by Sampson1107** [comment]
@typhoonzero 
非常感谢老师的解答，对我有非常大的帮助！再请教下老师一个问题：
我想把这个demo用到https://github.com/PaddlePaddle/models/tree/develop/image_classification
这个脚本中，是否可行呢？这里面是通过打batch的方式实现数据读取的，能够替换我如上demo中的provider吗？

**Comment by chengduoZH** [comment]
一个issue最好只讨论一个问题，如果还有问题，并且问题与该issue无关，请另外发issue @Sampson1107
