### ISSUE TITLE
all inputs arrays must have the same shape!

### ISSUE THREAD

**Issue by Jeremy-lf** [PaddlePaddle/Paddle#44209]
### bug描述 Describe the Bug

![image](https://user-images.githubusercontent.com/45171399/178185843-6308d42d-45b2-4e0b-b3d5-c50c36489b7d.png)

paddle2.3的环境，基于paddledetection 2.3 rb 训练，抱这个错是什么问题呢？

**Comment by haoyuying** [comment]
训练过程图片只有相同的shape才能组装成一个batch，该报错显示的是np.stack由于shape不一致导致的报错，建议排查数据处理模块，看输入图片是否统一成相同的shape。

**Comment by Jeremy-lf** [comment]
> 

好的，我再排查一下
