### ISSUE TITLE
paddle.fluid.io.save_inference_model()报错：ValueError: var read_file_0.tmp_0 not in this block

### ISSUE THREAD

**Issue by March35** [PaddlePaddle/Paddle#44232]
### 请提出你的问题 Please ask your question

paddle.fluid.io.save_inference_model()报错：ValueError: var read_file_0.tmp_0 not in this block

**Comment by haoyuying** [comment]
您好，根据报错信息原因是保存模型时存在临时变量，请检查组网代码中是否存在临时变量或非法变量被保存的情况。
