### ISSUE TITLE
paddlespeech跑语音合成样例的时候出现paddle _non_static_mode错误

### ISSUE THREAD

**Issue by RRRRRayyyyy** [PaddlePaddle/Paddle#44234]
### 请提出你的问题 Please ask your question

在按照paddleSpeech的安装模式进行paddlepaddle和paddlespeech安装后，测试语音合成样例的时候在paddle/distribution/distribution,py 中抛出 cannot import name '_non_static_mode' from 'paddle.fluid.framework'的问题，参考了issue有remove '_non_static_mode' 的问题，请问这个模块是被remove了还是什么其他问题呢？

**Comment by yt605155624** [comment]
solved in  https://github.com/PaddlePaddle/PaddleSpeech/discussions/1195#discussioncomment-3168521
