### ISSUE TITLE
量化节点使用问题

### ISSUE THREAD

**Issue by Lilengli** [PaddlePaddle/Paddle#44265]
### 请提出你的问题 Please ask your question

为什么我在调用一个class时，我只是调用了class的__init__，并没有调用里面的forward，比如想这个QuantizedConv2d。
![image](https://user-images.githubusercontent.com/93658838/178446190-7fc01c76-e56a-4d1e-998e-e9dd3bae11e6.png)

**Comment by seemingwang** [comment]
你好，方便提供一下具体的调用代码吗

**Comment by Lilengli** [comment]
你好，我就是调用的Paddle-develop\python\paddle\fluid\contrib\slim\quantization\imperative\qat.py这个文件，我用QAT来量化模型。

**Comment by wanghaoshuang** [comment]
动态图量化训练请参考这个教程：https://paddleslim.readthedocs.io/zh_CN/latest/quick_start/dygraph/dygraph_quant_aware_training_tutorial.html

不建议您直接调用paddle.nn.quant.QuantizedConv2D
