### ISSUE TITLE
动态选择在哪块卡运行模型时报错

### ISSUE THREAD

**Issue by mrbeann** [PaddlePaddle/Paddle#44272]
### 请提出你的问题 Please ask your question

您好，我在使用paddle的过程中遇到了一个错误，我搭建了一个简单的web服务，然后需要动态选择在哪块卡上运行代码，但是执行过程出现了CUDA memory error。
代码逻辑非常简单，相关部分如下：
```
# 函数开始，先设置device
paddle.set_device(device_str)
# 数据处理tokenize等
model = AutoModelForSequenceClassification.from_pretrained(
        model_name_or_path, num_classes=num_classes)
```

![6196e09e69e68d5dd397b65e1dd1b15](https://user-images.githubusercontent.com/9161747/178469759-8865bc9d-8c23-48c7-b8b0-f28be92dd856.png)

**Comment by seemingwang** [comment]
你好，请问是动态图还是静态图，以及是否可以提供一下跑网络前向的代码。
