### ISSUE TITLE
序列标注问题FATAL

### ISSUE THREAD

**Issue by xuezhong** [PaddlePaddle/Paddle#4428]
Thank you for contributing to PaddlePaddle. Submitting an issue is a great help for us.
Both Chinese and English issues are welcome.

It's hard to solve a problem when important details are missing.
Before submitting the issue, look over the following criteria before handing your request in.

- [ ] Was there a similar issue submitted or resolved before ? You could search issue in the github.
- [ ] Did you retrieve your issue from widespread search engines ?
- [ ] Is my description of the issue clear enough to reproduce this problem?
   * If some errors occurred, we need details about `how do you run your code?`, `what system do you use?`, `Are you using GPU or not?`, etc.
   * If you use an recording [asciinema](https://asciinema.org/) to show what you are doing to make it happen, that's awesome! We could help you solve the problem more quickly.
- [ ] Is my description of the issue use the github markdown correctly?
   * Please use the proper markdown syntaxes for styling all forms of writing, e.g, source code, error information, etc.
   * Check out [this page](https://guides.github.com/features/mastering-markdown/) to find out much more about markdown.

**Comment by xuezhong** [comment]
root@9e03c8ad4498:/home/qxz/model_qxz/sequence_tagging_for_ner# python train.py
I0927 08:40:48.760462    19 Util.cpp:166] commandline:  --use_gpu=False --trainer_count=1
[INFO 2017-09-27 08:40:48,773 networks.py:1482] The input order is [word, mark, target]
[INFO 2017-09-27 08:40:48,773 networks.py:1488] The output order is [__crf_layer_0__]
[INFO 2017-09-27 08:40:48,788 networks.py:1482] The input order is [word, mark, target]
[INFO 2017-09-27 08:40:48,791 networks.py:1488] The output order is [__crf_layer_0__]
I0927 08:40:48.800027    19 GradientMachine.cpp:86] Initing parameters..
I0927 08:40:48.920850    19 GradientMachine.cpp:93] Init parameters done.
F0927 08:40:49.048017    19 ChunkEvaluator.cpp:196] Check failed: label[i] <= numChunkTypes_ * numTagTypes_ (7 vs. 6)
*** Check failure stack trace: ***
    @     0x7fb5618814cd  google::LogMessage::Fail()
    @     0x7fb561885015  google::LogMessage::SendToLog()
    @     0x7fb561880ff3  google::LogMessage::Flush()
    @     0x7fb56188652e  google::LogMessageFatal::~LogMessageFatal()
    @     0x7fb561693575  paddle::ChunkEvaluator::evalImp()
    @     0x7fb561683990  paddle::Evaluator::eval()
    @     0x7fb56166f0a8  paddle::CombinedEvaluator::eval()
    @     0x7fb56154e2ad  _wrap_GradientMachine_eval
    @           0x52714b  PyEval_EvalFrameEx
    @           0x555551  PyEval_EvalCodeEx
    @           0x525560  PyEval_EvalFrameEx
    @           0x555551  PyEval_EvalCodeEx
    @           0x524338  PyEval_EvalFrameEx
    @           0x555551  PyEval_EvalCodeEx
    @           0x524338  PyEval_EvalFrameEx
    @           0x567d14  (unknown)
    @           0x465bf4  PyRun_FileExFlags
    @           0x46612d  PyRun_SimpleFileExFlags
    @           0x466d92  Py_Main
    @     0x7fb57003ff45  __libc_start_main
    @           0x577c2e  (unknown)
    @              (nil)  (unknown)
Aborted

我自己的数据处理上 将mark全部置为0

**Comment by guoshengCS** [comment]
感觉这里应该是label有误，能否说明下采用的lable_dict，另外scheme是IOB还是其他这里支持的某种https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/trainer_config_helpers/evaluators.py#L438
