### ISSUE TITLE
skip_quant在哪里执行

### ISSUE THREAD

**Issue by Lilengli** [PaddlePaddle/Paddle#44291]
### 请提出你的问题 Please ask your question

我注意到在QAT里面的一个注释：如果skip_quant=true则不添加量化放量化逻辑，我想知道这个skip_quant在那里实现的呢，谢谢您的回复
![image](https://user-images.githubusercontent.com/93658838/178648991-c526e9b4-75b1-4a5f-9ebb-c8284b5dce9b.png)

**Comment by wanghaoshuang** [comment]
在这里实现的：https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/fluid/contrib/slim/quantization/imperative/qat.py#L368-L372

**Comment by wangqiang9** [comment]
> 在这里实现的：https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/fluid/contrib/slim/quantization/imperative/qat.py#L368-L372

这个链接失效了
