### ISSUE TITLE
运行python create_list.py 生成的trainval.txt 和test.txt 里面是空白的，为什么，但是我的ImageSets/Main里面是有trainval.txt里面也有内容的

### ISSUE THREAD

**Issue by paddle2022** [PaddlePaddle/Paddle#44299]
### 请提出你的问题 Please ask your question

paddle版本2.2.2 paddleDetection release 2.4参照官方文档操作（https://paddledetection.readthedocs.io/tutorials/Custom_DataSet.html#1%E5%87%86%E5%A4%87%E6%95%B0%E6%8D%AE）
![image](https://user-images.githubusercontent.com/109204750/178674093-bfc3b668-8961-4b2a-974c-18c5922b979e.png)
label_list.txt种类也换了，运行python create_list.py 生成的trainval.txt 和test.txt 里面是空白的。

**Comment by zoooo0820** [comment]
@paddle2022 
你好，可以参考下[目标检测数据准备](https://github.com/PaddlePaddle/PaddleDetection/blob/develop/docs/tutorials/data/PrepareDetDataSet.md#%E7%9B%AE%E6%A0%87%E6%A3%80%E6%B5%8B%E6%95%B0%E6%8D%AE%E8%AF%B4%E6%98%8E)这个文档，核对一下数据路径等内容的组织是否正确
