### ISSUE TITLE
咨询device guard的问题

### ISSUE THREAD

**Issue by houj04** [PaddlePaddle/Paddle#44308]
### 请提出你的问题 Please ask your question

请问一个device guard的问题：
https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/fluid/tests/unittests/test_device_guard.py#L86
这里写的是`gpu:1`，所以是不是按照设计，需要至少有2个gpu才能跑？
但是我自己跑单测的时候，只有1个gpu卡，也不报错，这样跑的：

``` shell
export CUDA_VISIBLE_DEVICES=1
cd build
ctest -R test_device_guard --verbose --extra-verbose --output-on-failure
```

想问一下是否符合预期，谢谢~

**Comment by kuizhiqing** [comment]
按照目前的设计 device_guard 只做声明，使用时是否符合预期需要进一步分析。
