### ISSUE TITLE
按照教程使用PaddleServing部署PP-OCRv3后，显存和内存溢出

### ISSUE THREAD

**Issue by LitterQ** [PaddlePaddle/Paddle#44305]
### bug描述 Describe the Bug

按照教程使用PaddleServing部署PP-OCRv3后，运行web服务后进行测试显存和内存都会一直增加不会减少。

环境为win11下的WSL2，根据Paddle官网，使用docker 
拉取环境 nvidia-docker pull registry.baidubce.com/paddlepaddle/paddle:2.3.1-gpu-cuda11.2-cudnn8

进入环境后python web_service.py  &>log.txt & 后
![image](https://user-images.githubusercontent.com/11575234/178687752-c16c4858-04cd-41d5-83e9-fde99808af5b.png)
内存占用5G，内存24G

此时运行 python pipeline_http_client.py后
![image](https://user-images.githubusercontent.com/11575234/178688248-690fee48-cc59-4ae9-8a0b-94d8c8028d2b.png)
显存增加到10.1G，内存增加到24.9G

多次运行python pipeline_http_client.py后
显存依然增加，没有减少。WSL有几率崩溃退出。

**Comment by heavengate** [comment]
你好，PaddleOCR服务化部署可以参考这个文档，现在在做全链条部署方案检测，这里面的部署方式是每天监控的
https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.5/deploy/pdserving/README_CN.md#部署

**Comment by LitterQ** [comment]
您好，我又重新重头按照您给的文档部署了一遍，但是显存还是不释放。
docker镜像使用的是[2.3.1-gpu-cuda11.2-cudnn8](https://hub.docker.com/layers/paddle/paddlepaddle/paddle/2.3.1-gpu-cuda11.2-cudnn8/images/sha256-4bef1dfb215daf7153fb8cd0ce14121136ace3130dfca392b5c252c049d8b276?context=explore)

部分重要的pip3 list如下
![image](https://user-images.githubusercontent.com/11575234/178707624-004240f6-9090-4707-83ce-69aa6d29dd58.png)

**Comment by HexToString** [comment]
> 您好，我又重新重头按照您给的文档部署了一遍，但是显存还是不释放。 docker镜像使用的是[2.3.1-gpu-cuda11.2-cudnn8](https://hub.docker.com/layers/paddle/paddlepaddle/paddle/2.3.1-gpu-cuda11.2-cudnn8/images/sha256-4bef1dfb215daf7153fb8cd0ce14121136ace3130dfca392b5c252c049d8b276?context=explore)
> 
> 部分重要的pip3 list如下 ![image](https://user-images.githubusercontent.com/11575234/178707624-004240f6-9090-4707-83ce-69aa6d29dd58.png)

推荐你使用C++ 版本的Paddle Serving
