### ISSUE TITLE
安装Paddlenlp后Paddle无法调用GPU

### ISSUE THREAD

**Issue by lcneyc** [PaddlePaddle/Paddle#44324]
### 请提出你的问题 Please ask your question

PaddleNLP和PaddlePaddle版本：paddlepaddle-gpu==2.3.0.post112 paddlenlp==2.3.4
系统环境：python==3.8.13 CentOS==7.9.2009
安装PaddleNLP后Paddle无法调用GPU 
>>> paddle.fluid.install_check.run_check()
Running Verify Fluid Program ... 
W0714 12:08:50.509186 112295 gpu_context.cc:278] Please NOTE: device: 0, GPU Compute Capability: 8.6, Driver API Version: 11.2, Runtime API Version: 11.2
W0714 12:08:50.518731 112295 gpu_context.cc:306] device: 0, cuDNN Version: 8.1.
后服务器无任何输出

**Comment by lcneyc** [comment]
我之前使用paddleocr能正常调用gpu，在安装paddlenlp后无法调用了，但在我重新安装环境后，paddle仍无法调用gpu，在新环境中出现了一样的问题。
>>> paddle.fluid.install_check.run_check()
Running Verify Fluid Program ... 
W0714 13:03:57.545765  2700 gpu_resources.cc:61] Please NOTE: device: 0, GPU Compute Capability: 8.6, Driver API Version: 11.2, Runtime API Version: 11.2
W0714 13:03:57.886097  2700 gpu_resources.cc:91] device: 0, cuDNN Version: 8.1.
服务器无响应

**Comment by sljlp** [comment]
可能是在安装paddlenlp之后影响了环境，建议使用paddle官方提供的docker镜像启动docker容器
docker使用可参考文档https://www.paddlepaddle.org.cn/documentation/docs/zh/install/docker/linux-docker.html#linuxdocker

**Comment by lcneyc** [comment]
谢谢，今天上午解决了，您说的对，确实是paddlenlp影响了环境
解决方法：重新create了环境，但conda install后存在一样的问题，卸载后，pip install解决了
