### ISSUE TITLE
PaddlePaddle是有与wandb结合案例

### ISSUE THREAD

**Issue by syw2014** [PaddlePaddle/Paddle#44320]
### 需求描述 Feature Description

任务目标（请描述你正在做的项目是什么，如模型、论文、项目是什么？）; <br /> 需求场景（请描述你的项目中为什么需要用此功能）;  <br /> 功能描述（请简单描述或设计这个功能）

### 替代实现 Alternatives

wandb是一个用来记录训练过程的超参数和数据指标的package，PaddlePaddle是有与wandb结合案例？

**Comment by manangoel99** [comment]
Hi @reyoung @jacquesqiao ! I'm an engineer at W&B and I would love to make this contribution.
I wasn't able to find documentation on how to set up a development environment for an addition to just the python package. Can you please direct me to the right place?

**Comment by luotao1** [comment]
close due to https://github.com/PaddlePaddle/Paddle/pull/46918
