### ISSUE TITLE
Add HasInputs/HasOutputs in shape interface

### ISSUE THREAD

**Issue by Yancey1989** [PaddlePaddle/Paddle#4434]
Maybe we need to add interfaces `HasInputs/HasOutputs` in `InferShapeContextBase`

**Comment by typhoonzero** [comment]
More details please?

Can this be done by

```
PADDLE_ENFORCE_NOT_NULL(ctx.InputVar("Input"),
                            "some error.");
```

**Comment by Yancey1989** [comment]
Maybe there is no `InputVar` in [InferShapeContextBase](https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/framework/shape_inference.h#L22). After [Refactoring InferShape](https://github.com/PaddlePaddle/Paddle/pull/3946), the inferface name in Infershape context become more clearly, but there is only `HasInput/HasOutput` to check single Input/Output, so I want to add `HasInputs/HasOutputs` to check `MultiInput/MultiOutput`.
