### ISSUE TITLE
load_inference_model报错

### ISSUE THREAD

**Issue by March35** [PaddlePaddle/Paddle#44352]
### 请提出你的问题 Please ask your question

![image](https://user-images.githubusercontent.com/48037392/179133227-4fd46a78-dee5-46fc-a88b-08876b533b59.png)

**Comment by March35** [comment]
paddle1.6

**Comment by FeixLiu** [comment]
您好，感谢您的提问。看上去是这个Ids的tensor shape出了问题，建议您检查一下这个tensor的初始化是否正确。另外，建议您升级到最新的paddle 2.3版本来使用paddle。

**Comment by March35** [comment]
您好，检查了存储的模型参数之后，发现一个输入没有链接上，请问这个一般是哪里出了问题呢？需要排查哪部分呢？谢谢
在save_inference_model的时候并没有报错

**Comment by FeixLiu** [comment]
可能是在保存的时候，这个输入在保存的时候被框架判断为没有被用到（与输出无关）的输入了，就被prune掉了。不过还是建议您升级到paddle 2.3再试一下。
