### ISSUE TITLE
_DataLoaderIterSingleProcess' object has no attribute '_shutdown

### ISSUE THREAD

**Issue by bb67ao** [PaddlePaddle/Paddle#44374]
### bug描述 Describe the Bug

Traceback (most recent call last):
  File "test.py", line 95, in <module>
    train()
  File "test.py", line 25, in train
    for i ,(item)in enumerate(data_loader()):
  File "E:\Anaconda\Anaconda\envs\pypaddle\lib\site-packages\paddle\fluid\reader.py", line 569, in __call__
    return self.__iter__()
  File "E:\Anaconda\Anaconda\envs\pypaddle\lib\site-packages\paddle\fluid\reader.py", line 558, in __iter__
    return _DataLoaderIterSingleProcess(self)
  File "E:\Anaconda\Anaconda\envs\pypaddle\lib\site-packages\paddle\fluid\dataloader\dataloader_iter.py", line 175, in __init__
    self._init_thread()
  File "E:\Anaconda\Anaconda\envs\pypaddle\lib\site-packages\paddle\fluid\dataloader\dataloader_iter.py", line 182, in _init_thread
    self._var_names = [v.name for v in self._feed_list]
TypeError: 'int' object is not iterable
Exception ignored in: <function _DataLoaderIterSingleProcess.__del__ at 0x0000024494FA54C8>
Traceback (most recent call last):
  File "E:\Anaconda\Anaconda\envs\pypaddle\lib\site-packages\paddle\fluid\dataloader\dataloader_iter.py", line 339, in __del__
    self._try_shutdown_all()
  File "E:\Anaconda\Anaconda\envs\pypaddle\lib\site-packages\paddle\fluid\dataloader\dataloader_iter.py", line 324, in _try_shutdown_all
    if not self._shutdown:
AttributeError: '_DataLoaderIterSingleProcess' object has no attribute '_shutdown'

### 其他补充信息 Additional Supplementary Information

```
class DataSet(Dataset):
    def __init__(self,traj):
        self.traj = traj
    def __getitem__(self, idx):
        return  self.traj[idx]
    def __len__(self):
        return len(self.traj)
def train():
    traj = np.load('../data/' + 'NYC' + '.npy')
    dataset = DataSet(traj)
#test1:不指定batch_size=batch_size，会报以上错误
    batch_size = 10
    data_loader = DataLoader(dataset,batch_size)
#test2：指定batch_size=x，则不再报错
    # data_loader = DataLoader(dataset,
    #                 batch_size=10)
    for i ,(item)in enumerate(data_loader()):
        print(item)
        break
```

**Comment by FeixLiu** [comment]
感谢您的反馈，可以排查一下是不是数据dataloader。看看dataloader get出来的数据是否有问题。
<img width="384" alt="image" src="https://user-images.githubusercontent.com/25279174/179231025-8301ac55-f5de-4d37-81a7-02ecd20e112c.png">

**Comment by bb67ao** [comment]
``> <img alt="image" width="390" src="https://user-images.githubusercontent.com/25279174/179230366-b54734fb-d287-4b40-8e04-4f31a269d684.png">
> 
> 是不是这个 feed_list传的有问题？
> emmm，我不知道你说的这个是什么问题。不过我用官方测试代码也试了，不加等号就会报这样的错误
```
import numpy as np

import paddle
import paddle.nn as nn
import paddle.nn.functional as F
from paddle.io import Dataset, BatchSampler, DataLoader

BATCH_NUM = 20
BATCH_SIZE = 16
EPOCH_NUM = 4

IMAGE_SIZE = 784
CLASS_NUM = 10

USE_GPU = False # whether use GPU to run model

# define a random dataset
class RandomDataset(Dataset):
    def __init__(self, num_samples):
        self.num_samples = num_samples

    def __getitem__(self, idx):
        image = np.random.random([IMAGE_SIZE]).astype('float32')
        label = np.random.randint(0, CLASS_NUM - 1, (1, )).astype('int64')
        return image, label

    def __len__(self):
        return self.num_samples



class SimpleNet(nn.Layer):
    def __init__(self):
        super(SimpleNet, self).__init__()
        self.fc = nn.Linear(IMAGE_SIZE, CLASS_NUM)

    def forward(self, image, label=None):
        return self.fc(image)
def train_2():
    dataset = RandomDataset(BATCH_NUM * BATCH_SIZE)
    simple_net = SimpleNet()
    opt = paddle.optimizer.SGD(learning_rate=1e-3,
                            parameters=simple_net.parameters())

    loader = DataLoader(dataset,
                        BATCH_SIZE,
                        shuffle=True,
                        drop_last=True,
                        num_workers=2)

    for e in range(EPOCH_NUM):
        for i, (image, label) in enumerate(loader()):
            print(label)
            break
            # out = simple_net(image)
            # loss = F.cross_entropy(out, label)
            # avg_loss = paddle.mean(loss)
            # avg_loss.backward()
            # opt.minimize(avg_loss)
            # simple_net.clear_gradients()
            # print("Epoch {} batch {}: loss = {}".format(e, i, np.mean(loss.numpy())))

```

**Comment by FeixLiu** [comment]
您说的等号是哪句话的等号？

**Comment by bb67ao** [comment]
> 您说的等号是哪句话的等号？
啊，应该是我自己的问题，这里应该必须指定参数对吗
`batch_size = BATCH_SIZE `
如果只填参数 BATCH_SIZE 这里就会报错，指定参数就不会了

**Comment by FeixLiu** [comment]
是的，因为底层默认参数有很多，所以需要指定参数。https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/io/DataLoader_cn.html#dataloader 第二个参数是feed_list，所以报了图中feed list是int的问题
