### ISSUE TITLE
编译昇腾310版本之后，运行提示Not enough available NPU memory

### ISSUE THREAD

**Issue by listeng** [PaddlePaddle/Paddle#44407]
### bug描述 Describe the Bug

编译昇腾310 NPU版本之后，运行run_check或其他任何代码，都提示Not enough available NPU memory，如 #34802。看了代码 `paddle/fluid/platform/device/npu/npu_info.cc`中的`aclrtGetMemInfo`传了`ACL_HBM_MEM`参数，但是310卡没有HBM内存（910卡才有），会始终返回0可用内存。改成`ACL_DDR_MEM`，获取内存就正常了，是否加个判断。
谢谢！

**Comment by Tiehr2000** [comment]
您好！paddlepaddle是否支持昇腾310呢？我现在也使用昇腾310 NPU，运行任何代码都出现Not enough available NPU memory错误。
我已经在npu_info.cc中改了ACL_DDR_MEM，但还是报同样的错误。请问是改了.cc文件后需要进行其他操作吗？或者这个还有其他解决方法吗？非常感谢！
