### ISSUE TITLE
 cudaSuccess == err (0 vs. 8) [hl_gpu_apply_unary_op failed]

### ISSUE THREAD

**Issue by zhangyuepeng** [PaddlePaddle/Paddle#4440]
I get the error as follows, when I run a demo with gpu, and my env is (cuda-8.0、cudnn5、centos6.3、Tesla P40、 paddlepaddle-0.10.0） 。

 PaddlePaddle wasn't compiled to use avx instructions, but these are available on your machine and could speed up CPU computations via CMAKE .. -DWITH_AVX=ON
F0927 21:45:50.391185 50006 hl_gpu_matrix_kernel.cuh:181] Check failed: cudaSuccess == err (0 vs. 8) [hl_gpu_apply_unary_op failed] CUDA error: invalid device function
*** Check failure stack trace: ***
    @     0x7f41dac9ba1d  google::LogMessage::Fail()
    @     0x7f41dac9f4cc  google::LogMessage::SendToLog()
    @     0x7f41dac9b513  google::LogMessage::Flush()
    @     0x7f41daca09de  google::LogMessageFatal::~LogMessageFatal()
    @     0x7f41dab262f4  hl_gpu_apply_unary_op<>()
    @     0x7f41dab26635  paddle::BaseMatrixT<>::applyUnary<>()
    @     0x7f41dab26863  paddle::BaseMatrixT<>::zero()
    @     0x7f41da9c1c51  paddle::Parameter::enableType()
    @     0x7f41da9bd4dc  paddle::parameterInitNN()
    @     0x7f41da9bfc2a  paddle::NeuralNetwork::init()
    @     0x7f41da9e87a1  paddle::GradientMachine::create()
    @     0x7f41dac787e3  GradientMachine::createFromPaddleModelPtr()
    @     0x7f41dac789bf  GradientMachine::createByConfigProtoStr()
    @     0x7f41da88849d  _wrap_GradientMachine_createByConfigProtoStr
    @           0x4b4cb9  PyEval_EvalFrameEx
    @           0x4b6b28  PyEval_EvalCodeEx
    @           0x4b5d10  PyEval_EvalFrameEx
    @           0x4b6b28  PyEval_EvalCodeEx
    @           0x4b5d10  PyEval_EvalFrameEx
    @           0x4b6b28  PyEval_EvalCodeEx
    @           0x52940f  function_call
    @           0x422cba  PyObject_Call
    @           0x4271ad  instancemethod_call
    @           0x422cba  PyObject_Call
    @           0x48121f  slot_tp_init
    @           0x47eb1a  type_call
    @           0x422cba  PyObject_Call
    @           0x4b31dd  PyEval_EvalFrameEx
    @           0x4b6b28  PyEval_EvalCodeEx
    @           0x4b5d10  PyEval_EvalFrameEx
    @           0x4b6b28  PyEval_EvalCodeEx
    @           0x4b6c52  PyEval_EvalCode

**Comment by typhoonzero** [comment]
Same to https://github.com/PaddlePaddle/Paddle/issues/4439
