### ISSUE TITLE
clang-cindex-python3 如何修改下载源

### ISSUE THREAD

**Issue by GreenHandZhu** [PaddlePaddle/Paddle#44429]
编译paddle源码时，将third_party修改为了国内下载源，但是编译过程中一直卡在 Built target analysis_predictor 这一步。使用make -j1查看后发现需要从  https://gitee.com/wjakob/clang-cindex-python3 下载 clang-cindex-python3。由于权限问题无法正常下载。怎么修改clang-cindex-python3下载源呢？

**Comment by pangyoki** [comment]
请问你修改的是Paddle哪个第三方库的下载源？怎么修改的？
本地可以下载clang-cindex-python3吗？

**Comment by GreenHandZhu** [comment]
> 请问你修改的是Paddle哪个第三方库的下载源？怎么修改的？ 本地可以下载clang-cindex-python3吗？

是用 git clone -b build_cn https://gitee.com/jiaopan/Paddle.git 中的cmake/external的文件全量替换了同目录下的文件。本地可以使用其他源来下载clang-cindex-python3。但是默认使用的 https://gitee.com/wjakob/clang-cindex-python3 这个源就无法下载

**Comment by pangyoki** [comment]
你好，我看https://gitee.com/jiaopan/Paddle.git这个库中cmake/external下的文件跟paddle官方库的第三方库文件都不一样，这些确定是Paddle编译依赖的文件吗？
另外，我也没搜到Paddle需要依赖clang-cindex-python3这个库的文件，你现在使用这个第三方库，可以找下编译这个库的文件，里面应该有相应的下载repo的链接地址，可以试试修改成你能下载的地址。

**Comment by GreenHandZhu** [comment]
> 你好，我看[https://gitee.com/jiaopan/Paddle.git这个库中cmake/external下的文件跟paddle官方库的第三方库文件都不一样，这些确定是Paddle编译依赖的文件吗？](https://gitee.com/jiaopan/Paddle.git%E8%BF%99%E4%B8%AA%E5%BA%93%E4%B8%ADcmake/external%E4%B8%8B%E7%9A%84%E6%96%87%E4%BB%B6%E8%B7%9Fpaddle%E5%AE%98%E6%96%B9%E5%BA%93%E7%9A%84%E7%AC%AC%E4%B8%89%E6%96%B9%E5%BA%93%E6%96%87%E4%BB%B6%E9%83%BD%E4%B8%8D%E4%B8%80%E6%A0%B7%EF%BC%8C%E8%BF%99%E4%BA%9B%E7%A1%AE%E5%AE%9A%E6%98%AFPaddle%E7%BC%96%E8%AF%91%E4%BE%9D%E8%B5%96%E7%9A%84%E6%96%87%E4%BB%B6%E5%90%97%EF%BC%9F) 另外，我也没搜到Paddle需要依赖clang-cindex-python3这个库的文件，你现在使用这个第三方库，可以找下编译这个库的文件，里面应该有相应的下载repo的链接地址，可以试试修改成你能下载的地址。

paddle 依赖的是pybind11, clang-cindex-python3是pybind11的submodules。 我尝试自己镜像pybind11，并修改pybind11的submodues的URL. 虽然最后没有编译成功，但是应该是个解决方向。只是这样的方式非常繁琐，个人认为百度的产品没有国内镜像支持三方库的下载，就有点不太合理。毕竟国内很多公司都很难访问github

**Comment by pangyoki** [comment]
好的，大概了解你的意思了。我们会评估下，把第三方库的下载地址从github迁移到国内源，方便编译时下载的问题。

**Comment by Vector-Cross** [comment]
这个问题有了解决方法了吗，我编译了两天到96%了，卡在这个库没拉下来，不知道怎么解决

**Comment by FlickerMi** [comment]
> 这个问题有了解决方法了吗，我编译了两天到96%了，卡在这个库没拉下来，不知道怎么解决

拉这个库的 build_cn 分支代码：https://gitee.com/FlickerMi/Paddle
我修改了clang-cindex-python3的源为gitee了。

**Comment by Vector-Cross** [comment]
> > 这个问题有了解决方法了吗，我编译了两天到96%了，卡在这个库没拉下来，不知道怎么解决
> 
> 拉这个库的 build_cn 分支代码：https://gitee.com/FlickerMi/Paddle 我修改了clang-cindex-python3的源为gitee了。

感谢回复，之前以同样的方式解决好了，还有一个需要注意的是pybind11库也会拉不下来，我自己建了一个gitee库修改一下代码里的路径就好了。
https://gitee.com/vectorcross/pybind11
