### ISSUE TITLE
麒麟v10源码编译安装 cmake报错 gcc版本9.3.0

### ISSUE THREAD

**Issue by LangJiHuangSha** [PaddlePaddle/Paddle#44427]
### 问题描述 Issue Description

所需环境都已经装好了，包括python依赖和gcc、cmake、patchELF、python等且都符合版本要求
版本如下
astor                  0.8.1 
decorator           4.4.2
numpy                1.23.1
opt-einsum             3.3.0
paddle-bfloat          0.1.7
Pillow                 7.0.0 
protobuf             3.17.0rc1
requests             2.22.0
six                      1.14.0
wheel                  0.34.2

gcc version 9.3.0 (Ubuntu 9.3.0-10kylin2)
cmake-3.16.8
python --version     Python 2.7.18rc1
python3 --version   Python 3.8.2
wget 
python3-pip           (20.0.2-5kylin1.5)(没有其他版本)
swig                      (4.0.1-5build1)。
unrar                    (1:5.6.6-2build1)

执行命令如下
cmake .. -DPY_VERSION=3 -DPYTHON_EXECUTABLE=`which python3` -DWITH_ARM=ON -DWITH_TESTING=OFF -DCMAKE_BUILD_TYPE=Release -DON_INFER=ON -DWITH_XBYAK=OFF -WITH_GPU=OFF

错误日志的所有的报错信息如下
/usr/bin/ld: src.c:(.text+0x50): undefined reference to `pthread_detach'
/usr/bin/ld: src.c:(.text+0x5c): undefined reference to `pthread_join'

/usr/bin/ld: 找不到 -lpthreads

c++: error: unrecognized command line option ‘-mmmx’
c++: error: unrecognized command line option ‘-msse2’
c++: error: unrecognized command line option ‘-msse3’
c++: error: unrecognized command line option ‘-mavx’
c++: error: unrecognized command line option ‘-mavx2’
c++: error: unrecognized command line option ‘-mavx512f’

### 版本&环境信息 Version & Environment Information

****************************************
Paddle version: None
Paddle With CUDA: None

OS: Kylin v10
Python version: 3.8.2

CUDA version: None
cuDNN version: None.None.None
Nvidia driver version: aa
****************************************
#此处由于电脑有显卡驱动但是没装显卡 执行.py脚本时会报错，所以关于显卡的信息是随便填的，准备安装cpu版本的

**Comment by qili93** [comment]
@LangJiHuangSha 

1. 确认下在 ARM 环境下跑 make 命令要改成 `make TARGET=ARMV8 -j$(nproc)`

2. `undefined reference to pthread_join'`可能还是环境问题，建议参考这个文档使用飞桨的镜像编译运行
https://www.paddlepaddle.org.cn/inference/master/guides/hardware_support/cpu_phytium_cn.html，另外想要确认下你的 CPU 是飞腾还是鲲鹏的 CPU，2个 CPU 都可以尝试使用以上镜像，如果无法使用镜像，那请检查一下 /lib 和 /lib64 环境下存在 libpthread，也可以参考 https://stackoverflow.com/questions/31948521/building-error-using-cmake-cannot-find-lpthreads 里面的回答定位一下真正的 cmake error 是发生在哪里。

3. `c++: error: unrecognized command line option ‘-mmmx’` 这错误的发生可能是 PSCORE 引入的，可以尝试在 CMAKE 的时候加上 WITH_PSCORE=OFF 或者是 WITH_DISTRIBUTE=OFF 试试看

建议以上三个方法都可以尝试看看
