### ISSUE TITLE
save_inference_model

### ISSUE THREAD

**Issue by March35** [PaddlePaddle/Paddle#44443]
paddle 1.6
多次save_inference_model保存下来的参数会有问题，问题类似 https://github.com/PaddlePaddle/Paddle/issues/20299 这个issue中的情况，看到了回复的有两种解决办法，但是不是很清楚具体怎么做，可以给个例子吗？

**Comment by xiaoxiaohehe001** [comment]
升级下 paddle 试一试，看是否出现相同的问题。

**Comment by March35** [comment]
不太方便升级paddle...  升级的话需要重新配置环境和重构一些业务代码

**Comment by March35** [comment]
辛苦看看怎么从代码上解决这个问题吧

**Comment by GuoxiaWang** [comment]
@March35 
就是在调用 save inference model 前加一个 program.clone

静态图的 program api 文档参照 https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/static/Program_cn.html#clone-for-test-false
