### ISSUE TITLE
"from x2paddle import models"会导致原本正常的代码报错

### ISSUE THREAD

**Issue by rev564** [PaddlePaddle/Paddle#44455]
### bug描述 Describe the Bug

环境就是在aistudio上跑代码时的环境，项目框架PaddlePaddle 2.3.0，项目环境python 3.7。在终端里"pip install x2paddle“安装了x2paddle。以下代码是在notebook里面运行的
然后，正常代码是
```
import paddle.vision
from PIL import Image
tmp = Image.open('../mydata/images/000ab24a75c9a867b1c7438bbb8258e7.jpg')
tmp2 = paddle.vision.to_tensor(tmp)
tmp2
```
图片是正在用的数据集里面随便挑的一张。然后加一句"from x2paddle import models"就会出错
```
import paddle.vision
from PIL import Image
from x2paddle import models
tmp = Image.open('../mydata/images/000ab24a75c9a867b1c7438bbb8258e7.jpg')
tmp2 = paddle.vision.to_tensor(tmp)
tmp2
```
这样子运行就会报错。

**Comment by GuoxiaWang** [comment]
@Orzst 报错截图可以贴一下吗？

**Comment by rev564** [comment]
> @Orzst 报错截图可以贴一下吗？

![截图1](https://user-images.githubusercontent.com/31810331/179745018-db23d086-236b-43cc-9136-f0854f0ebfd7.png)
![截图2](https://user-images.githubusercontent.com/31810331/179745047-b83b3203-6da5-4826-9dd8-507c93e13b9e.png)
![截图3](https://user-images.githubusercontent.com/31810331/179745054-7197852d-f533-43c6-8a68-7078a133b52c.png)
![截图4](https://user-images.githubusercontent.com/31810331/179745067-19cd38be-64cd-498d-83c0-49e4929c2f34.png)
![截图5](https://user-images.githubusercontent.com/31810331/179745076-47c21852-10cc-4838-a869-3bd1af9af897.png)

**Comment by GuoxiaWang** [comment]
@Orzst 

先试试把 tmp 的shape打一下

```
tmp = Image.open('../mydata/images/000ab24a75c9a867b1c7438bbb8258e7.jpg')
print(np.array(tmp).shape)
tmp2 = paddle.vision.to_tensor(tmp)
```

**Comment by rev564** [comment]
@GuoxiaWang 
![image](https://user-images.githubusercontent.com/31810331/179750161-1cd80168-421f-4a8a-8d8c-c4f628949538.png)
(792, 612, 3)

**Comment by LielinJiang** [comment]
import numpy as np
from PIL import Image
import paddle
from x2paddle import models

tmp = paddle.to_tensor((np.random.rand(512, 512, 3) * 255).astype('uint8'))
tmp2 = tmp.reshape([512, 512, 3])
tmp2

写了个单测，应该是x2paddle引入的问题。 @GuoxiaWang

**Comment by GuoxiaWang** [comment]
@LielinJiang  好的，是冲突了吗？

**Comment by LielinJiang** [comment]
应该是reshape op调用成了x2paddle里面的一个op吧，实际上想要调用的paddle.reshape

**Comment by wjj19950828** [comment]
@Orzst 是有模型转换需求吗，为什么要from x2paddle import models呢

**Comment by rev564** [comment]
> @Orzst 是有模型转换需求吗，为什么要from x2paddle import models呢

@wjj19950828 是的，把一个PyTorch实现的模型改成paddle实现的。它用了个预训练好的VGG-16，本来是用的torchvision。AiStudio给的环境不能用torch，所以就想到用x2paddle。

**Comment by GuoxiaWang** [comment]
@LielinJiang @Orzst @wjj19950828 看了一些调用栈，是 x2paddle 可能引入的问题。

`/usr/local/lib/python3.7/dist-packages/paddle/fluid/layers/nn.py`

```
            if isinstance(shape, (list, tuple)):
                shape = [
                    item.numpy().item(0) if isinstance(item, Variable) else item
                    for item in shape
                ]
                out, _ = _C_ops.reshape2(x, None, 'shape', shape)
```
走进了这个分支。

`shape` 本身是 tuple `([112, 112, 3],)`, 去遍历的时候第一个元素就已经是 `<class 'list'> [112, 112, 3]`，再在外面嵌套了一层 list，会得到 `[[112, 112, 3]]` 导致报错。

问题本质出现在
`/usr/local/lib/python3.7/dist-packages/x2paddle/project_convertor/pytorch/torch2paddle/tensor.py`
```
@add_tensor_function
def reshape(self, *shape):
    return pd_reshape(self, shape)
```
这里的输入参数用的是 `*shape`，所以会包装成一个 tuple，因为传入进来是一个 `<class 'list'> [112, 112, 3]`， 所以包装成了 tuple `([112, 112, 3],)`。

可能的修改方法是
（1）将 `def reshape(self, *shape):` 改成 `def reshape(self, *shape):` 可以解决问题。
但是为了要兼容非 list，比如 torch 的方式，那么可能就
（2）需要保留 `def reshape(self, *shape):`，然后在 `return pd_reshape(self, shape)` 前加一些判断处理。

**Comment by wjj19950828** [comment]
@Orzst 您好，相关问题已经在X2Paddle中修复，pip install最新版本(1.3.8)，即可解决～

**Comment by rev564** [comment]
> @Orzst 您好，相关问题已经在X2Paddle中修复，pip install最新版本(1.3.8)，即可解决～

哦好的
