### ISSUE TITLE
支持 optional<float> 作为 kernel 参数

### ISSUE THREAD

**Issue by tiancaishaonvjituizi** [PaddlePaddle/Paddle#44467]
### 需求描述 Feature Description

Reference：https://github.com/PaddlePaddle/Paddle/pull/42469#discussion_r908001237

根据目前的框架新 API 开发要求，Python API 与 C++ API 参数需保持一致。但这个要求是没办法 100% 做到的。因为 Python 的类型是 nullable 的，而 C++ 的类型不是，而且 Paddle Kernel 不支持使用 `optional<float>`、`optional<int>` 作为参数，所以如果 Python API 的参数类型为 Optional[int] 或者 Optional[float]，就没办法做到 Python 和 C++ 参数一致。

所以建议尽快支持 `optional<float>` 参数，并在这之前放松这个 API 开发要求。

### 替代实现 Alternatives

无

**Comment by zhangbo9674** [comment]
感谢您的需求，我们会尽快对此需求进行评估！
