### ISSUE TITLE
macOS 使用预编译Paddle Inference C++库无法启动

### ISSUE THREAD

**Issue by daviyang35** [PaddlePaddle/Paddle#44470]
### bug描述 Describe the Bug

Paddle Inference macOS 预编译包不能使用
验证发现 在 macOS 平台使用 paddle_inference_install_dir 2.2.2 与 2.3.0 两个版本

只要链接了 libpaddle_inference.dylib ，即使是空的 main 函数，启动就会报错：
```text
ERROR: flag 'flagfile' was defined more than once (in files '/Users/paddle/buildAgent/work/b751e1a81fc4a6c8/Paddle/build/third_party/gflags/src/extern_gflags/src/gflags.cc' and '/tmp/gflags-20211022-34906-1r13f7a/gflags-2.2.2/src/gflags.cc').
```

<img width="841" alt="image" src="https://user-images.githubusercontent.com/4261582/179915659-738f5165-22c1-42ab-8608-65c4fe64a58b.png">

<img width="796" alt="image" src="https://user-images.githubusercontent.com/4261582/179915707-d7b952ef-e76d-49d1-a3da-b60f13a7036a.png">

<img width="542" alt="image" src="https://user-images.githubusercontent.com/4261582/179915840-cb4c6ea1-c853-46c6-825a-cdfa0b0a2eb8.png">

**Comment by zhangbo9674** [comment]
您好，看起来是gflag 版本有冲突，是否能只依赖一个gflag？

**Comment by daviyang35** [comment]
默认是链接 预编译包内的 paddle_inference_install_dir/third_party/install/gflags/lib/libgflags.a
我尝试过这几总组合，都会报这个错误：
-     链接 third_party/install/gflags/lib/libgflags.a
- 不链接 third_party/install/gflags/lib/libgflags.a
- 不链接 third_party/install/gflags/lib/libgflags.a；链接 自己编译的 gflags

报错的错误输出路径，应该是来自打包CI的路径，冲突的 gflags 很可能是在打包阶段就发生了，
gflags 运行时才会输出这个错误，不会导致编译失败。

‘/Users/paddle/buildAgent/work/b751e1a81fc4a6c8/Paddle/build/third_party/gflags/src/extern_gflags/src/gflags.cc' and '/tmp/gflags-20211022-34906-1r13f7a/gflags-2.2.2/src/gflags.cc

**Comment by daviyang35** [comment]
已经处理了，是自己编译的问题。
预编译的 paddle_inference 动态库内部已经链接了 gflags，我本地使用brew安装的OpenCV 3 链接了一个外部的gflags动态库。

修改脚本更改为使用 paddle_inference 静态库链接，可执行文件不用链接 预编译安装包中的 libgflags.a ，直接使用本地已经安装的gflags 动态库即可。

感谢

**Comment by BrilliantYuKaimin** [comment]
我遇到了相同的问题，能否详细说说这一步是如何做的？
> 修改脚本更改为使用 paddle_inference 静态库链接，可执行文件不用链接 预编译安装包中的 libgflags.a ，直接使用本地已经安装的gflags 动态库即可。

**Comment by wa-na-sa** [comment]
我在重新编译 Paddle 和 OpenCV 后问题得到解决。

**Comment by BrilliantYuKaimin** [comment]
我在重新编译 Paddle 和 OpenCV 后问题得到解决。
