### ISSUE TITLE
Undocumented parameter in dataloader

### ISSUE THREAD

**Issue by czr-gc** [PaddlePaddle/Paddle#44522]
### 文档链接&描述 Document Links & Description

input param `persistent_workers` is not documented in doc: 
https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/io/DataLoader_cn.html#dataloader

source code:
https://github.com/PaddlePaddle/Paddle/blob/a224019056b9767e827a48c72b2e8a9270e04d79/python/paddle/fluid/reader.py#L459

**Comment by AnnaTrainingG** [comment]
Sorry, it's our mistake. Thank you very much for your feedback. We will add it as soon as possible.
