### ISSUE TITLE
nvidia-smi -L found gpu count: 1

### ISSUE THREAD

**Issue by Senwei-Huang** [PaddlePaddle/Paddle#44531]
### bug描述 Describe the Bug

E0721 22:36:11.350354 24760 pybind.cc:2342] Cannot use GPU because you have installed CPU version PaddlePaddle.
If you want to use GPU, please try to install GPU version PaddlePaddle by: pip install paddlepaddle-gpu
If you only have CPU, please change CUDAPlace(0) to be CPUPlace().

请问这个怎么改：If you only have CPU, please change CUDAPlace(0) to be CPUPlace().
电脑没有GPU ，安装的也是CPU版本的paddle，但是程序运行的时候提示我Cannot use GPU because you have installed CPU version PaddlePaddle.

@jzhang533 @wanglun @lileding @Superjomn @

**Comment by AnnaTrainingG** [comment]
你好 非常感谢你的反馈，paddle可以通过set_device的形式选择运行的平台：
import paddle
paddle.device.set_device("cpu")
API : https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/device/set_device_cn.html#set-device

也可以在创建tensor的设置设置place 具体使用方法请参考：
https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/to_tensor_cn.html#to-tensor

**Comment by Senwei-Huang** [comment]
您好，谢谢提供的解决方案。但是我按照您的方法并没有解决问题，还是一样的报错：
```
[07-22 16:34:54 MainThread @machine_info.py:88] nvidia-smi -L found gpu count: 1
E0722 16:34:54.516928 15256 pybind.cc:2342] Cannot use GPU because you have installed CPU version PaddlePaddle.
If you want to use GPU, please try to install GPU version PaddlePaddle by: pip install paddlepaddle-gpu
If you only have CPU, please change CUDAPlace(0) to be CPUPlace().
```
下面是我按照您提供的两个方法做的修改：
**方法1：**
我在所有.py文件开头都添加了`paddle.device.set_device("cpu")`，总共5个.py文件。如下：
① main_train.py：
```
import hopper_env
import argparse
import numpy as np
from parl.utils import logger, summary, ReplayMemory
from parl.env.continuous_wrappers import ActionMappingWrapper
from mujoco_model import MujocoModel
from mujoco_agent import MujocoAgent
from algorithm import DDPG
import paddle
paddle.device.set_device("cpu")
```
② mujoco_agent.py
```
import parl
import paddle
import numpy as np
paddle.device.set_device("cpu")
```
③ algorithm.py
```
import parl
import paddle
import paddle.nn.functional as F
from copy import deepcopy
# from parl.utils.utils import check_model_method
paddle.device.set_device("cpu")
```
④ mujoco_model.py
```
import parl
import paddle
import paddle.nn as nn
import paddle.nn.functional as F
paddle.device.set_device("cpu")
```
⑤ hopper_env.py
```
import numpy as np
import gym
from gym import spaces
import pybullet as p
import pybullet_data as pd
from stable_baselines3.common.env_checker import check_env
import paddle
paddle.device.set_device("cpu")
```

**方法2：**
创建tensor的地方只有② mujoco_agent.py这个文件，然后我对用到paddle.to_tensor的6个地方都添加了place=paddle.CPUPlace()，如下所示：
```
    def predict(self, obs):
        obs = paddle.to_tensor(obs.reshape(1, -1), dtype='float32', place=paddle.CPUPlace())
        action = self.alg.predict(obs)
        action_numpy = action.cpu().numpy()[0]
        return action_numpy

    def learn(self, obs, action, reward, next_obs, terminal):
        terminal = np.expand_dims(terminal, -1)  # 转变成二阶张量,且最内层加括号，变成列向量
        reward = np.expand_dims(reward, -1)
        obs = paddle.to_tensor(obs, dtype='float32', place=paddle.CPUPlace())
        action = paddle.to_tensor(action, dtype='float32', place=paddle.CPUPlace())
        reward = paddle.to_tensor(reward, dtype='float32', place=paddle.CPUPlace())
        next_obs = paddle.to_tensor(next_obs, dtype='float32', place=paddle.CPUPlace())
        terminal = paddle.to_tensor(terminal, dtype='float32', place=paddle.CPUPlace())
        critic_loss, actor_loss = self.alg.learn(obs, action, reward, next_obs, terminal)
        return critic_loss, actor_loss
```
**设备环境信息：**
window 10
pycharm 2020
paddle 2.31
parl 1.4
python 3.9

@niuliling123

**Comment by AnnaTrainingG** [comment]
你好，我们会根据你的问题尝试复现一下的 复现后将及时反馈给你
可以尝试一下方法解决：修改python 安装包中的machine_info.py:88
https://blog.csdn.net/weixin_43938942/article/details/107032548
https://blog.csdn.net/zhaomengszu/article/details/79401043

**Comment by AnnaTrainingG** [comment]
基于paddle2.3.1并未复现 
<img width="652" alt="image" src="https://user-images.githubusercontent.com/51102941/180422882-78d68a11-821a-4a8a-8705-fa0984f753b2.png">

cpu 安装包 设置device为gpu 会直接提示错误
<img width="783" alt="image" src="https://user-images.githubusercontent.com/51102941/180423337-667fec1c-79a3-4340-b8dd-a7e353b577bd.png">

总结应该是与你的python 版本有关 建议尝试上一条评论中的方法

**Comment by Senwei-Huang** [comment]
感谢您的帮助，我已经解决了。是parl版本问题，但是到底是parl哪部分造成的未知。之前安装的是parl 1.4，现在升级到2.0.5，已经可以正常运行了。
@niuliling123

**Comment by AnnaTrainingG** [comment]
好的那太棒了 那我就将issue关闭了
