### ISSUE TITLE
报名 飞桨黑客马拉松第三期

### ISSUE THREAD

**Issue by yunbattle1994** [PaddlePaddle/Paddle#44533]
### 问题描述 Please describe your issue

【队名】：PinnCylPro

【序号】：65

【状态】：报名

【repo链接】：https://github.com/yunbattle1994/PaddleScience_PINN_cylinder_probe

**Comment by AnnaTrainingG** [comment]
你好，可以在原issue下评论报名，便于进行项目统计，谢谢。https://github.com/PaddlePaddle/Paddle/issues/43938
