### ISSUE TITLE
官方文档的《数据集定义与加载》章节示例示代码缺失

### ISSUE THREAD

**Issue by Yumerain** [PaddlePaddle/Paddle#44532]
### 文档链接&描述 Document Links & Description

问题所在链接：
https://www.paddlepaddle.org.cn/documentation/docs/zh/guides/beginner/data_load_cn.html

问题位置：
1.2 使用 paddle.io.Dataset 自定义数据集
“用 paddle.io.Dataset 定义数据集的代码示例”

问题描述：
transform = Normalize(mean=[127.5], std=[127.5], data_format='CHW')
这行代码调用的Normalize函数没有导入

### 请提出你的建议 Please give your suggestion

解决方法：
参考1.1章节，添加导入：
from paddle.vision.transforms import Normalize

**Comment by AnnaTrainingG** [comment]
非常感谢您的反馈，我们将及时修复该问题

**Comment by luotao1** [comment]
@Yumerain 
- 欢迎提一个PR来修复下问题：https://github.com/PaddlePaddle/docs/blob/develop/docs/guides/beginner/data_load_cn.ipynb 
- 飞桨正在举行迎新年快乐开源活动，有兴趣可以参加下：https://aistudio.baidu.com/aistudio/activitydetail/1503019026

**Comment by Yumerain** [comment]
提交错子项目了，已经在paddle对应的项目docs里提了PR
