### ISSUE TITLE
paddle有没有计划提供c++接口

### ISSUE THREAD

**Issue by Salitanr** [PaddlePaddle/Paddle#44541]
### 需求描述 Feature Description

paddle有没有计划像pytorch 那样提供c++接口用来组建与训练模型，这样可以给现有c++应用提供接入深度学习功能提供支撑

**Comment by ronny1996** [comment]
你好，Paddle现在正在做C++和Python接口的统一，有计划提供C++接口

**Comment by Salitanr** [comment]
> 这是个好消息，计划会在什么时间段发布呢

**Comment by ronny1996** [comment]
你好，目前只是进了paddle2.4的研发计划，但是什么时候能用还不好说
