### ISSUE TITLE
遇到一个来自比较深层次的，文档没有覆盖到的警告，看起来是关于DataLoader。

### ISSUE THREAD

**Issue by wykkyle** [PaddlePaddle/Paddle#44555]
### 请提出你的问题 Please ask your question

报错截图，但是能顺利训练。
![tmp](https://user-images.githubusercontent.com/20754685/180414934-2e58c44c-f451-4a23-baed-47cb78da3394.png)

错误来源
在训练的时候，有些数据是需要送给gpu的，有些数据是需要留在gpu的。但是目前DataLoader不支持指定数据流向。
如，在ppdet项目中就有如下代码：因为图片路径不能送入gpu，故不能通过DataLoader返回（后一个箭头），所以需要准备一个数组，通过enumerate的序数，从数组中取图片路径（前一个箭头）
![tmp2](https://user-images.githubusercontent.com/20754685/180420857-f28b7c9c-0a6f-4c6d-afff-4bcf48a187b4.png)

所以我试着在原来的dataloader上改了一下。主要是想增加标志位，指示数据该送往cpu还是gpu。然后就出来这个警告。
大概是这样。
![tmp3](https://user-images.githubusercontent.com/20754685/180418350-98210a3e-ef7d-425d-b2c3-2d3528101744.png)

太深了，翻不动代码了，问问。

**Comment by ronny1996** [comment]
![image](https://user-images.githubusercontent.com/25691046/180428896-137b8633-fb31-4a94-b973-0e8316c6006d.png)


你好请问是这部分警告吗？这部分警告是不是paddleslim报的？

**Comment by wykkyle** [comment]
> 

确实是paddleslim。用的ppdet的train.py改的代码，有一个预估模型计算量的步骤，没有注意到。（但是最近我只动了DataLoader）。
虽然还没看明白什么问题（print传入变量确实是tensor，不是numpy），不过不是主体训练和预测的问题就放心了。还没看paddleslim的文档。暂时忽略，到时候再处理。thx。
![image](https://user-images.githubusercontent.com/20754685/180673715-6b30d73e-fdd0-400b-906a-a2286748bb3f.png)
