### ISSUE TITLE
如何杀死进程

### ISSUE THREAD

**Issue by METGALALA** [PaddlePaddle/Paddle#44566]
### 请提出你的问题 Please ask your question

(Fatal) Operator conv2d raises an paddle::memory::allocation::BadAlloc exception.
The exception content is
:ResourceExhaustedError: 

Out of memory error on GPU 0. Cannot allocate 69.629150MB memory on GPU 0, 39.525391GB memory has been allocated and available memory is only 62.187500MB.

Please check whether there is any other process using GPU 0.
1. If yes, please stop them, or start PaddlePaddle on another GPU.
2. If no, please decrease the batch size of your model. 

 (at /paddle/paddle/fluid/memory/allocation/cuda_allocator.cc:79)
. (at /paddle/paddle/fluid/imperative/tracer.cc:221)

我并没有进行其他的操作，但是显示显存不够

**Comment by CtfGo** [comment]
您好，请问您使用的paddle哪个版本，能否贴下关键代码片段？如果batch size过大是有可能报错显存不足的
