### ISSUE TITLE
本人在麒麟v10,cpu为Kunpeng 920 源码编译遇到卡住不动的情况，编译cpu版本

### ISSUE THREAD

**Issue by wulei-sudo** [PaddlePaddle/Paddle#44587]
### 问题描述 Issue Description

[ 24%] Built target variable_visitor
[ 24%] Built target variable_helper
[ 24%] Built target lod_rank_table
[ 24%] Built target sampler
[ 24%] Built target collective_helper
[ 24%] Built target feed_fetch_method
[ 24%] Built target var_helper
[ 24%] Built target analysis_config
[ 25%] Built target cuda_graph_with_memory_pool
[ 25%] Built target box_wrapper
[ 24%] Built target sequence2batch
[ 25%] Built target reader
[ 25%] Built target scope_buffered_monitor
[ 25%] Built target fc_functor
[ 25%] Built target heter_wrapper
[ 25%] Built target infermeta_utils
[ 25%] Built target cos_sim_functor
[ 25%] Built target mask_util
[ 25%] Built target concat_and_split
[ 27%] Built target device_code
[ 27%] Built target scope_pool
[ 27%] Built target sample_prob
[ 26%] Built target unpooling
[ 27%] Built target dlpack_tensor
[ 27%] Built target custom_kernel
[ 27%] Built target jit_serializer
[ 27%] Built target zero_copy_tensor
[ 27%] Built target device_worker
[ 27%] Built target jit_kernel_benchmark
[ 27%] Built target op_info
[ 27%] Built target math_function
[ 27%] Built target phi_api_utils
[ 27%] Built target matrix_inverse
[ 27%] Built target unused_var_check
[ 27%] Built target string_infermeta
[ 27%] Built target gloo_wrapper
[ 27%] Built target lodtensor_pr
[ 27%] Built target ps_gpu_wrapper
[ 27%] Built target metrics
[ 27%] Built target interpretercore_event_garbage_collector
[ 27%] Built target context_pool
[ 27%] Built target data_transform
[ 28%] Built target phi_tensor_raw
[ 28%] Built target api_gen_utils
[ 28%] Built target op_meta_info
[ 28%] Built target kernel_dispatch
[ 28%] Built target eager_final_state_codegen
[ 43%] Built target phi_cpu
[ 43%] Built target api_int_array
[ 43%] Built target api_scalar
[ 43%] Built target tensor_copy
[ 43%] Built target phi_static_1
[ 43%] Built target phi
[ 43%] copy_if_different /data/OCR/Paddle/Paddle/paddle/phi/api/include/strings_api.h 
[ 43%] Built target wrapped_infermeta
[ 43%] Built target print_pten_kernels
[ 43%] Built target infershape_utils
[ 43%] Built target phi_utils
[ 43%] Built target phi_data_transform
[ 43%] Built target api_custom_impl
[ 43%] Built target sparse_api_custom_impl
[ 43%] Built target operator
[ 43%] copy_if_different /data/OCR/Paddle/Paddle/paddle/phi/api/include/sparse_api.h 
[ 43%] copy_if_different /data/OCR/Paddle/Paddle/paddle/phi/api/include/api.h /data/OCR/Paddle/Paddle/paddle/phi/api/lib/api.cc
[ 43%] Built target dependency_utils
[ 43%] Built target common_infer_shape_functions
[ 43%] Built target proto_desc
[ 43%] copy_if_different /data/OCR/Paddle/Paddle/paddle/phi/api/include/strings_api.h 
[ 43%] Built target node
[ 43%] Built target argument
[ 43%] Built target op_compatible_info
[ 43%] Built target analysis_pass
[ 43%] Built target jit_serializer_utils
[ 43%] Built target program_processing
[ 43%] Built target operator
[ 43%] copy_if_different /data/OCR/Paddle/Paddle/paddle/phi/api/include/sparse_api.h 
[ 43%] copy_if_different /data/OCR/Paddle/Paddle/paddle/phi/api/include/api.h /data/OCR/Paddle/Paddle/paddle/phi/api/lib/api.cc
[ 43%] Built target dependency_utils
[ 43%] Built target common_infer_shape_functions
[ 43%] Built target proto_desc
[ 43%] copy_if_different /data/OCR/Paddle/Paddle/paddle/phi/api/include/strings_api.h 
[ 43%] Built target node
[ 43%] Built target argument
[ 43%] Built target op_compatible_info
[ 43%] Built target analysis_pass
[ 43%] Built target jit_serializer_utils
[ 43%] Built target program_processing
[ 43%] Built target model_utils
[ 43%] Built target op_registry
[ 43%] Built target op_variant
[ 43%] Built target prepared_operator
[ 43%] Built target jit_function_utils
[ 43%] Built target var_handle
[ 43%] Built target graph
[ 43%] Built target gpc
[ 43%] Built target ir_graph_clean_pass
[ 44%] Built target rpc_op_handle
[ 44%] Built target share_tensor_buffer_functor
[ 44%] Built target fetch_barrier_op_handle
[ 44%] Built target memory_optim_pass
[ 44%] Built target computation_op_handle
[ 44%] Built target layer
[ 44%] Built target while_op_helper
[ 45%] Built target device_event_base
[ 45%] Built target reader_op_registry
[ 45%] Built target jit_function_schema
[ 45%] Built target op_handle_base
[ 45%] Built target graph_traits
[ 45%] Built target graph_helper
[ 45%] Built target strings_api
[ 45%] Built target op_desc_meta
[ 45%] Built target op_desc_meta
[ 45%] Built target amp
[ 45%] Built target reference_count_pass_helper
[ 45%] Built target load_combine_op
[ 46%] Built target warpctc_op
[ 46%] Built target quantize_linear_op
[ 47%] Built target roi_perspective_transform_op
[ 47%] Built target collect_fpn_proposals_op
[ 47%] Built target generate_proposals_v2_op
[ 47%] Built target box_decoder_and_assign_op
[ 47%] Built target distribute_fpn_proposals_op
[ 47%] Built target nms_op
[ 47%] Built target yolo_box_op
[ 47%] Built target generate_mask_labels_op
[ 47%] Built target retinanet_detection_output_op
[ 47%] Built target save_combine_op
[ 47%] Built target multiclass_nms_op
[ 47%] Built target generate_proposals_op
[ 47%] Built target prior_box_op
[ 47%] Built target mine_hard_examples_op
[ 47%] Built target generate_proposal_labels_op
[ 48%] Built target anchor_generator_op
[ 48%] Built target box_coder_op
[ 48%] Built target density_prior_box_op
[ 48%] Built target iou_similarity_op
[ 48%] Built target polygon_box_transform_op
[ 48%] Built target sigmoid_focal_loss_op
[ 48%] copy_if_different /data/OCR/Paddle/Paddle/paddle/phi/api/include/sparse_api.h 
[ 48%] Built target locality_aware_nms_op
[ 48%] Built target rpn_target_assign_op
[ 48%] Built target bipartite_match_op
[ 48%] Built target matrix_nms_op
[ 48%] Built target target_assign_op
[ 48%] Built target yolov3_loss_op
[ 48%] Built target box_clip_op
[ 48%] Built target elementwise_add_op
[ 48%] Built target fusion_repeated_f
[ 48%] Built target iou_similarity_op
[ 48%] Built target polygon_box_transform_op
[ 48%] Built target sigmoid_focal_loss_op
[ 48%] copy_if_different /data/OCR/Paddle/Paddle/paddle/phi/api/include/sparse_api.h 
[ 48%] Built target locality_aware_nms_op
[ 48%] Built target rpn_target_assign_op
[ 48%] Built target bipartite_match_op
[ 48%] Built target matrix_nms_op
[ 48%] Built target target_assign_op
[ 48%] Built target yolov3_loss_op
[ 48%] Built target box_clip_op
[ 48%] Built target elementwise_add_op
[ 48%] Built target fusion_repeated_fc_relu_op
[ 48%] Built target elementwise_div_op
[ 48%] Built target elementwise_mod_op
[ 48%] Built target elementwise_pow_op
[ 48%] Built target elementwise_max_op
[ 48%] Built target fusion_seqconv_eltadd_relu_op
[ 49%] Built target elementwise_floordiv_op
[ 49%] Built target elementwise_sub_op
[ 49%] Built target fused_embedding_seq_pool_op
[ 49%] Built target elementwise_mul_op
[ 49%] Built target fused_seqpool_cvm_op
[ 49%] Built target fusion_seqpool_concat_op
[ 49%] Built target fusion_seqpool_cvm_concat_op
[ 49%] Built target fusion_seqexpand_concat_fc_op
[ 49%] Built target elementwise_min_op
[ 49%] Built target elementwise_heaviside_op
[ 49%] Built target fusion_lstm_op
[ 49%] Built target fusion_squared_mat_sub_op
[ 49%] Built target fused_elemwise_activation_op
[ 49%] Built target fused_embedding_fc_lstm_op
[ 50%] Built target multi_gru_op
[ 51%] Built target fusion_gru_op
[ 51%] Built target auc_op
[ 51%] Built target accuracy_op
[ 51%] Built target precisio
[ 51%] Built target precision_recall_op
[ 51%] Built target sparse_momentum_op
[ 51%] Built target rmsprop_op
[ 52%] Built target sgd_op
[ 52%] Built target proximal_gd_op
[ 52%] Built target proximal_adagrad_op
[ 52%] Built target pow2_decay_with_linear_warmup_op
[ 52%] Built target decayed_adagrad_op
[ 52%] Built target adadelta_op
[ 52%] Built target adamax_op
[ 52%] Built target adam_op
[ 52%] Built target distributed_fused_lamb_op
[ 52%] Built target lars_momentum_op
[ 52%] Built target dgc_momentum_op
[ 52%] Built target merged_adam_op
[ 52%] Built target adagrad_op
[ 52%] Built target momentum_op
[ 52%] Built target ftrl_op
[ 52%] Built target dpsgd_op
[ 52%] Built target distributed_fused_lamb_init_op
[ 52%] Built target adamw_op
[ 52%] Built target merged_momentum_op
[ 52%] Built target lamb_op
[ 52%] Built target reduce_any_op
[ 52%] Built target frobenius_norm_op
[ 52%] Built target reduce_all_op
[ 52%] Built target reduce_amax_op
[ 52%] Built target logsumexp_op
[ 53%] Built target reduce_sum_op
[ 53%] Built target reduce_max_op
[ 53%] Built target reduce_min_op
[ 53%] Built target reduce_mean_op
[ 53%] Built target sequence_reshape_op
[ 53%] Built target sequence_slice_op
[ 53%] Built target sequence_expand_op
[ 53%] Built target sequence_expand_as_op
[ 53%] Built target reduce_
 54%] Built target reshape_p_op
[ 54%] Built target slice_select_p_op
[ 54%] Built target mul_p_op
[ 54%] Built target scatter_add_p_op
[ 54%] Built target slice_assign_p_op
[ 54%] Built target split_p_op
[ 54%] Built target add_p_op
[ 54%] Built target sqrt_p_op
[ 54%] Built target clear_float_status_op
[ 54%] Built target sub_p_op
[ 54%] Built target alloc_float_status_op
[ 54%] Built target check_finite_and_unscale_op
[ 54%] Built target get_float_status_op
[ 54%] Built target update_loss_scaling_op
[ 54%] Built target read_op
[ 54%] Built target create_py_reader_op
[ 54%] Built target gather_op_handle
[ 54%] Built target create_double_buffer_reader_op
[ 54%] Built target save_load_util
[ 54%] Built target pass
[ 54%] Built target fetch_op_handle
[ 54%] Built target all_reduce_op_handle
[ 54%] Built target graph_pattern_detector
[ 54%] Built target sparse_api
[ 54%] Built target fused_all_reduce_op_handle
[ 54%] Built target share_tensor_buffer_op_handle
[ 54%] Built target multi_devices_helper
[ 54%] Built target reduce_op_handle
[ 54%] Built target scale_loss_grad_op_handle
[ 54%] Built target op_compat_sensible_pass
[ 54%] Built target op_graph_view
[ 54%] Built target sequential_execution_pass
[ 55%] Built target add_reader_dependency_pass
[ 55%] Built target pass_builder
[ 55%] Built target coalesce_grad_tensor_pass
[ 55%] Built target program_desc_tracer
[ 55%] Built target fetch_async_op_h
[ 55%] Built target fuse_adam_op_pass
[ 55%] Built target fuse_sgd_op_pass
[ 56%] Built target fuse_momentum_op_pass
[ 56%] Built target is_test_pass
[ 56%] Built target graph_to_program_pass
[ 56%] Built target inplace_addto_op_pass
[ 56%] Built target fuse_all_reduce_op_pass
[ 56%] Built target simplify_with_basic_ops_pass
[ 56%] Built target buffer_shared_cross_op_memory_reuse_pass
[ 56%] Built target delete_weight_dequant_linear_op_pass
[ 56%] Built target delete_quant_dequant_filter_op_pass
[ 56%] Built target conv_elementwise_add_fuse_pass
[ 56%] Built target yolo_box_fuse_pass
[ 56%] Built target adaptive_pool2d_convert_global_pass
[ 56%] Built target identity_scale_op_clean_pass
[ 57%] Built target seq_concat_fc_fuse_pass
[ 57%] Built target multihead_matmul_fuse_pass
[ 57%] Built target embedding_fc_lstm_fuse_pass
[ 57%] Built target conv_bn_fuse_pass
[ 57%] Built target delete_fill_constant_op_pass
[ 57%] Built target fc_lstm_fuse_pass
[ 57%] Built target shuffle_channel_detect_pass
[ 58%] Built target preln_residual_bias_fuse_pass
[ 58%] Built target conv_elementwise_add_act_fuse_pass
[ 58%] Built target delete_dropout_op_pass
[ 59%] Built target dense_fc_to_sparse_pass
[ 59%] Built target seqpool_concat_fuse_pass
[ 59%] Built target unsqueeze2_eltwise_fuse_pass
[ 59%] Built target dense_multihead_matmul_to_sparse_pass
[ 59%] Built target fc_elementwise_layernorm_fuse_pass
[ 59%] Built target gpu_cpu_map_matmul_to_mul_pass
[ 59%] Built target matmul_scale_fuse_pass
[ 59%] Built target sync_batch_norm_pass
[ 59%] Built target lock_free_optimize_pass
[ 59%] Built target naive_executor
[ 59%] Built target layer_norm_fuse_pass
[ 59%] Built target seqpool_cvm_conca
[ 59%] Built target generate_pass
[ 59%] Built target seqconv_eltadd_relu_fuse_pass
[ 59%] Built target graph_viz_pass
[ 59%] Built target conv_elementwise_add2_act_fuse_pass
[ 60%] Built target fc_fuse_pass
[ 60%] Built target delete_c_identity_op_pass
[ 60%] Built target delete_quant_dequant_linear_op_pass
[ 60%] Built target skip_layernorm_fuse_pass
[ 60%] Built target add_support_int8_pass
[ 60%] Built target delete_quant_dequant_op_pass
[ 60%] Built target fc_gru_fuse_pass
[ 60%] Built target attention_lstm_fuse_pass
[ 60%] Built target quant_conv2d_dequant_fuse_pass
[ 60%] Built target inference_op_replace_pass
[ 60%] Built target ir_graph_to_program_pass
[ 60%] Built target adjust_cudnn_workspace_size_pass
[ 60%] Built target recurrent_op_helper
[ 60%] Built target multi_devices_graph_pass
[ 60%] Built target fetch_v2_op
[ 60%] Built target compare_op
[ 60%] Built target compare_all_op
[ 60%] Built target bitwise_op
[ 60%] Built target depend_op
[ 60%] Built target logical_op
[ 60%] Built target get_places_op
[ 60%] Built target while_op
[ 60%] Built target tensor_array_read_write_op
[ 60%] Built target fetch_op
[ 60%] Built target feed_op
Requirement already satisfied: pyyaml in /root/anaconda3/lib/python3.8/site-packages (6.0)
[ 60%] Built target standalone_executor
[ 60%] Built target conditional_block_op
[ 60%] copy_if_different /data/OCR/Paddle/Paddle/paddle/phi/api/backward/sparse_bw_api.h 
[ 60%] Built target set_reader_device_info_utils
[ 60%] Built target build_strategy
[ 60%] Built target conditional_block_op_helper
[ 60%] Built target recurrent_op
[ 62%] Built target histogram_op
[ 62%] Built target unstack_op
[ 62%] Built target buffer_shared_inplace_op_pass
[ 62%] Built target recurrent_op_eager_deletion_pass
[ 62%] Built target channel_shuffle_op
[ 62%] Built target read_file_op
[ 62%] Built target interpolate_v2_op
[ 62%] Built target rank_attention_op
[ 62%] Built target scale_op
[ 63%] Built target eigvals_op
[ 63%] Built target index_sample_op
[ 63%] Built target cast_op
[ 63%] Built target conditional_block_op_eager_deletion_pass
[ 63%] Built target fused_token_prune_op
[ 63%] Built target norm_op
[ 63%] Built target margin_rank_loss_op
[ 63%] Built target fill_zeros_like_op
[ 63%] Built target lgamma_op
[ 63%] Built target dropout_op
[ 63%] Built target prune_gate_by_capacity_op
[ 64%] Built target clip_op
[ 64%] Built target logspace_op
[ 64%] Built target cross_entropy_op
[ 64%] Built target fused_softmax_mask_upper_triangle_op
[ 64%] Built target row_conv_op
[ 64%] Built target deformable_conv_v1_op
[ 64%] Built target eye_op
[ 64%] Built target fill_diagonal_tensor_op
[ 64%] Built target bpr_loss_op
[ 64%] Built target maxout_op
[ 64%] Built target group_norm_op
[ 64%] Built target gaussian_random_op
[ 64%] Built target matmul_op
[ 64%] Built target fill_constant_batch_size_like_op
[ 64%] Built target instance_norm_op
[ 64%] Built target filter_by_instag_op
[ 64%] Built target fill_any_like_op
[ 67%] Built target lookup_table_dequant_op
[ 67%] Built target ctc_align_op
[ 67%] Built target flip_op
[ 67%] Built target kron_op
[ 67%] Built target randperm_op
[ 67%] Built target transpose_op
[ 67%] Built target exponential_op
[ 67%] Built target get_tensor_from_selected_rows_op
[ 67%] Built target fold_op
[ 67%] Built target huber_loss_op
[ 67%] Built target hash_op
[ 67%] Built target graph_reindex_op
[ 67%] Built target hinge_loss_op
[ 67%] Built target multi_dot_op
[ 67%] Built target gelu_op
[ 68%] Built target gather_tree_op
[ 68%] Built target teacher_student_sigmoid_loss_op
[ 69%] Built target deformable_psroi_pooling_op
[ 69%] Built target erfinv_op
[ 69%] Built target lod_tensor_to_array_op
[ 70%] Built target share_buffer_op
[ 70%] Built target temporal_shift_op
[ 71%] Built target crf_decoding_op
[ 71%] Built target limit_by_capacity_op
[ 71%] Built target assign_pos_op
[ 71%] Built target bmm_op
[ 71%] Built target deformable_conv_op
[ 71%] Built target spectral_norm_op
[ 71%] Built target complex_op
[ 71%] Built target conv_transpose_op
[ 71%] Built target data_norm_op
[ 71%] Built target copy_cross_scope_op
[ 71%] Built target addmm_op
[ 71%] Built target attention_lstm_op
[ 71%] Built target rank_loss_op
[ 71%] Built target scatter_op
[ 82%] Built target tdm_sampler_op
[ 82%] Built target isfinite_op
[ 82%] Built target dequeue_op
[ 82%] Built target shard_index_op
[ 82%] Built target overlap_add_op
[ 82%] Built target flatten_op
[ 82%] Built target graph_khop_sampler_op
[ 82%] Built target max_sequence_len_op
[ 82%] Built target diag_embed_op
[ 82%] Built target fsp_op
[ 82%] Built target randint_op
[ 82%] Built target eigh_op
[ 82%] Built target unique_with_counts_op
[ 82%] Built target lrn_op
[ 82%] Built target memcpy_op
[ 82%] Built target inplace_abn_op
[ 82%] Built target merge_selected_rows_op
[ 82%] Built target marker_op
[ 82%] Built target masked_select_op
[ 82%] Built target correlation_op
[ 82%] Built target multiplex_op
[ 83%] Built target fake_quantize_op
[ 83%] Built target real_op
[ 83%] Built target mean_iou_op
[ 83%] Built target memcpy_d2h_op
[ 83%] Built target unique_op
[ 83%] Built target mean_op
[ 83%] Built target matmul_v2_op
[ 84%] Built target mode_op
[ 84%] Built target merge_lod_tensor_op
[ 84%] Built target fill_op
[ 84%] Built target coalesce_tensor_op
[ 84%] Built target slice_op
[ 84%] Built target lstmp_op
[ 84%] Built target modified_huber_loss_op
[ 84%] Built target nanmedian_op
[ 84%] Built target linear_chain_crf
[ 93%] Built target conditional_block_infer_op
[ 93%] Built target cost_model
[ 93%] Built target eager_deletion_pass
[ 93%] Built target ssa_graph_executor
[ 93%] Built target scope_buffered_ssa_graph_executor
[ 93%] Built target bind_threaded_ssa_graph_executor
[ 93%] Built target threaded_ssa_graph_executor
[ 93%] Built target fast_threaded_ssa_graph_executor
[ 93%] Built target parallel_ssa_graph_executor
[ 93%] Built target async_ssa_graph_executor
[ 93%] Built target parallel_executor
[ 93%] Built target executor_cache
[ 93%] Built target jit_compilation_unit
[ 93%] Built target run_program_op
[ 93%] Built target jit_layer
[ 93%] copy_if_different /data/OCR/Paddle/Paddle/paddle/phi/api/include/api.h /data/OCR/Paddle/Paddle/paddle/phi/api/lib/api.cc
Requirement already satisfied: pyyaml in /root/anaconda3/lib/python3.8/site-packages (6.0)
[ 93%] Built target phi_function_api
[ 93%] Generating ../../../../../paddle/phi/api/lib/dygraph_api.h, ../../../../../paddle/phi/api/lib/dygraph_api.cc
[ 93%] Built target phi_tensor
[ 93%] Built target eager_nan_inf_utils
[ 93%] Built target gradient_accumulator
[ 93%] Built target basic_engine
[ 93%] Built target engine
[ 93%] Built target tracer
[ 94%] Built target global_utils
[ 94%] copy_if_different /data/OCR/Paddle/Paddle/paddle/phi/api/backward/backward_api.h /data/OCR/Paddle/Paddle/paddle/phi/api/lib/backward_api.c
c
[ 94%] Generating ../../../../../paddle/phi/api/lib/dygraph_api.h, ../../../../../paddle/phi/api/lib/dygraph_api.cc
[ 94%] copy_if_different /data/OCR/Paddle/Paddle/paddle/phi/api/backward/backward_api.h /data/OCR/Paddle/Paddle/paddle/phi/api/lib/backward_api.c
c
[ 94%] Built target phi_dygraph_api
[ 94%] Built target phi_bw_function_api
[ 94%] Built target phi_api
[ 94%] Built target grad_node_info
[ 95%] Built target custom_operator
[ 95%] Built target autograd_meta
[ 93%] Built target jit_compilation_unit
[ 93%] Built target run_program_op
[ 93%] Built target jit_layer
[ 93%] copy_if_different /data/OCR/Paddle/Paddle/paddle/phi/api/include/api.h /data/OCR/Paddle/Paddle/paddle/phi/api/lib/api.cc
Requirement already satisfied: pyyaml in /root/anaconda3/lib/python3.8/site-packages (6.0)
[ 93%] Built target phi_function_api
[ 93%] Generating ../../../../../paddle/phi/api/lib/dygraph_api.h, ../../../../../paddle/phi/api/lib/dygraph_api.cc
[ 93%] Built target phi_tensor
[ 93%] Built target eager_nan_inf_utils
[ 93%] Built target gradient_accumulator
[ 93%] Built target basic_engine
[ 93%] Built target engine
[ 93%] Built target tracer
[ 94%] Built target global_utils
[ 94%] copy_if_different /data/OCR/Paddle/Paddle/paddle/phi/api/backward/backward_api.h /data/OCR/Paddle/Paddle/paddle/phi/api/lib/backward_api.c
c
[ 94%] Generating ../../../../../paddle/phi/api/lib/dygraph_api.h, ../../../../../paddle/phi/api/lib/dygraph_api.cc
[ 94%] copy_if_different /data/OCR/Paddle/Paddle/paddle/phi/api/backward/backward_api.h /data/OCR/Paddle/Paddle/paddle/phi/api/lib/backward_api.c
c
[ 94%] Built target phi_dygraph_api
[ 94%] Built target phi_bw_function_api
[ 94%] Built target phi_api
[ 94%] Built target grad_node_info
[ 95%] Built target custom_operator
[ 95%] Built target autograd_meta
[ 95%] Built target accumulation_node
[ 95%] Built target scale_node
[ 95%] Built target custom_operator_node
[ 95%] Built target grad_tensor_holder
[ 95%] Built target paddle_inference_api
[ 95%] Built target paddle_framework
[ 95%] Built target tensor_utils
[ 95%] Built target eager_scale
[ 95%] Built target infer_io_utils
[ 95%] Built target hook_utils
[ 95%] Built target utils
[ 95%] Built target eager_api
[ 93%] Built target tracer
[ 94%] Built target global_utils
[ 94%] copy_if_different /data/OCR/Paddle/Paddle/paddle/phi/api/backward/backward_api.h /data/OCR/Paddle/Paddle/paddle/phi/api/lib/backward_api.c
c
[ 94%] Generating ../../../../../paddle/phi/api/lib/dygraph_api.h, ../../../../../paddle/phi/api/lib/dygraph_api.cc
[ 94%] copy_if_different /data/OCR/Paddle/Paddle/paddle/phi/api/backward/backward_api.h /data/OCR/Paddle/Paddle/paddle/phi/api/lib/backward_api.c
c
[ 94%] Built target phi_dygraph_api
[ 94%] Built target phi_bw_function_api
[ 94%] Built target phi_api
[ 94%] Built target grad_node_info
[ 95%] Built target custom_operator
[ 95%] Built target autograd_meta
[ 95%] Built target accumulation_node
[ 95%] Built target scale_node
[ 95%] Built target custom_operator_node
[ 95%] Built target grad_tensor_holder
[ 95%] Built target paddle_inference_api
[ 95%] Built target paddle_framework
[ 95%] Built target tensor_utils
[ 95%] Built target eager_scale
[ 95%] Built target infer_io_utils
[ 95%] Built target hook_utils
[ 95%] Built target utils
[ 95%] Built target eager_api
[ 95%] Built target backward
[ 95%] Built target processgroup
[ 95%] Built target final_dygraph_node
[ 95%] Built target final_dygraph_function
[ 95%] Built target eager_reducer
In file included from /data/OCR/Paddle/Paddle/paddle/fluid/operators/memcpy_h2d_op.cc:12:0:
/data/OCR/Paddle/Paddle/paddle/fluid/operators/memcpy_h2d_op.h: In member function ‘void paddle::operators::MemcpyH2DFunctor::operator()(const Lo
DTensor&) const’:
/data/OCR/Paddle/Paddle/paddle/fluid/operators/memcpy_h2d_op.h:46:10: error: variable ‘stream’ set but not used [-Werror=unused-but-set-variable]
     auto stream = nullptr;
          ^~~~~~
Note: switching to 'v2.4.3'.
[ 95%] Built target processgroup
[ 95%] Built target final_dygraph_node
[ 95%] Built target final_dygraph_function
[ 95%] Built target eager_reducer
In file included from /data/OCR/Paddle/Paddle/paddle/fluid/operators/memcpy_h2d_op.cc:12:0:
/data/OCR/Paddle/Paddle/paddle/fluid/operators/memcpy_h2d_op.h: In member function ‘void paddle::operators::MemcpyH2DFunctor::operator()(const Lo
DTensor&) const’:
/data/OCR/Paddle/Paddle/paddle/fluid/operators/memcpy_h2d_op.h:46:10: error: variable ‘stream’ set but not used [-Werror=unused-but-set-variable]
     auto stream = nullptr;
          ^~~~~~
Note: switching to 'v2.4.3'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by switching back to a branch.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -c with the switch command. Example:

  git switch -c <new-branch-name>

Or undo this operation with:

  git switch -

Turn off this advice by setting config variable advice.detachedHead to false

HEAD is now at 80d45248 v2.4.3 release
Submodule 'tools/clang' (https://gitee.com/wjakob/clang-cindex-python3) registered for path 'tools/clang'
Cloning into '/data/OCR/Paddle/Paddle/build/third_party/pybind/src/extern_pybind/tools/clang'...
Username for 'https://gitee.com': cc1plus: all warnings being treated as errors
make[2]: *** [paddle/fluid/operators/CMakeFiles/memcpy_h2d_op.dir/build.make:66: paddle/fluid/operators/CMakeFiles/memcpy_h2d_op.dir/memcpy_h2d_o
p.cc.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:72216: paddle/fluid/operators/CMakeFiles/memcpy_h2d_op.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....

[ 24%] Built target variable_visitor

### 版本&环境信息 Version & Environment Information

paddlepaddle 2.3,在develop下编译
cpu Kunpeng 920
系统麒麟v10
python 3.8.8
详细信息为：
(base) [root@localhost build]# uname -a
Linux localhost.localdomain 4.19.90-23.8.v2101.ky10.aarch64 #1 SMP Mon May 17 17:07:38 CST 2021 aarch64 aarch64 aarch64 GNU/Linux
(base) [root@localhost build]# lscpu
Architecture:                    aarch64
CPU op-mode(s):                  64-bit
Byte Order:                      Little Endian
CPU(s):                          32
On-line CPU(s) list:             0-31
Thread(s) per core:              1
Core(s) per socket:              16
Socket(s):                       2
NUMA node(s):                    1
Vendor ID:                       HiSilicon
Model:                           0
Model name:                      Kunpeng-920
Stepping:                        0x1
BogoMIPS:                        200.00
NUMA node0 CPU(s):               0-31
Vulnerability Itlb multihit:     Not affected
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Not affected
Vulnerability Spec store bypass: Not affected
Vulnerability Spectre v1:        Mitigation; __user pointer sanitization
Vulnerability Spectre v2:        Not affected
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected
Flags:                           fp asimd evtstrm aes pmull sha1 sha2 crc32 atomics fphp asimdhp cpuid asimdrdm jscvt fcma dcpop asimddp asimdfhm
(base) [root@localhost build]# 
[ 47%] Built target mine_hard_example

**Comment by qili93** [comment]
hi，请问您这里使用的不是飞桨标准的GCC8.2的编译器版本对不？之前在 GCC 7.x 版本上会遇到这个问题，需要在 CMAKE 命令中加上 ` -DCMAKE_CXX_FLAGS="-Wno-error -w"` 来解决这个编译错误。

完整的 cmake 编译命令可以参考这个文档 https://www.paddlepaddle.org.cn/inference/v2.4/guides/hardware_support/cpu_phytium_cn.html
