### ISSUE TITLE
python 分布式训练时使用到的 python/paddle/distributed/fleet/launch_utils.py 中的方法 watch_local_trainers的异常处理问题

### ISSUE THREAD

**Issue by 535205856** [PaddlePaddle/Paddle#44583]
### bug描述 Describe the Bug

start_local_trainers方法的创建的训练进程的异常退出，但是lanch进程却是正常退出，

def watch_local_trainers(procs, nranks):
...
      if error:
                terminate_local_procs(procs)
                exit(1)
  ...
 except SystemExit:
        logger.error(
            "ABORT!!! Out of all {} trainers, the trainer process with rank={} was aborted. Please check its log."
            .format(nranks, error_rank))
        terminate_local_procs(procs)
        return

训练进程异常的 ret = p.proc.poll()  返回的是1，error为True, 会执行exit(1) 代码，抛出的异常被SystemExit捕获，然后直接return了，lanch的进程是正常退出了 推出码是0，训练进程的异常没有办法反映到lanch进程中
          

### 其他补充信息 Additional Supplementary Information

版本为 paddle 2.2.2
手动添加日志信息
![image](https://user-images.githubusercontent.com/9717930/180727492-ae9e9503-d249-45f7-bdc9-d9d7394a4b9a.png)

对应的日志

INFO 2022-07-25 07:21:16,457 launch_utils.py:585] p proc poll p [<paddle.distributed.fleet.launch_utils.TrainerProc object at 0x7f47f9465bd0>], proc [<subprocess.Popen object at 0x7f47f9465b90>]
INFO 2022-07-25 07:21:16,457 launch_utils.py:587] p.proc.poll ret [1], proc [<subprocess.Popen object at 0x7f47f9465b90>]
INFO 2022-07-25 07:21:16,457 launch_utils.py:594] before error [True]
INFO 2022-07-25 07:21:16,457 launch_utils.py:596] error [True]
INFO 2022-07-25 07:21:20,461 launch_utils.py:341] terminate all the procs
ERROR 2022-07-25 07:21:20,461 launch_utils.py:607] ABORT!!! Out of all 1 trainers, the trainer process with rank=[0] was aborted. Please check its log.
INFO 2022-07-25 07:21:24,465 launch_utils.py:341] terminate all the procs
INFO 2022-07-25 07:21:24,465 launch.py:311] Local processes completed.

**Comment by luotao1** [comment]
close by #44807
