### ISSUE TITLE
libcuda.so: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by ririya** [PaddlePaddle/Paddle#44599]
### 问题描述 Issue Description

Hi all, I've been using paddlepaddle-gpu=2.2.2.post112 for cuda 11.2 on ubuntu 20.04. I'm trying to switch to paddle 2.3.0 or 2.3.1, however after installing paddlepaddle-gpu=2.3.1.post112 I'm getting the above error. 

### 版本&环境信息 Version & Environment Information

paddlepaddle-gpu=2.3.1.post112

Python Python 3.8.13

Cuda 11.2

Cudnn v8.1.1.33

Nivida driver 516.40

**Comment by thisjiang** [comment]
Just to verify,  Did you install CUDA toolkit in the same environment? Or did you install other CUDA version in the same environment?Thanks.

**Comment by ririya** [comment]
> Just to verify, Did you install CUDA toolkit in the same environment? Or did you install other CUDA version in the same environment?Thanks.

It’s possible, I had an earlier installation of Cuda with a different version. But I’m running paddle 2.2.2 fine with cuda 11.2 in this environment

**Comment by thisjiang** [comment]
Could you check the cuda version by `nvcc --version`? If the cuda version not 11.2, maybe you should add the cuda11.2 directory into `PATH`.

**Comment by thisjiang** [comment]
Hi @ririya  did you solved this problem?

**Comment by ririya** [comment]
> Could you check the cuda version by `nvcc --version`? If the cuda version not 11.2, maybe you should add the cuda11.2 directory into `PATH`.

@thisjiang thanks for the reply. 

I don't have nvcc installed, because I had a hard time getting cuda installed when installing it... 

I added /usr/local/cuda-11.2/bin to PATH and /usr/local/cuda-11.2/lib-64 to LD_LIBRARY_PATH. Still getting the error....

**Comment by ririya** [comment]
Alright I was able to figure it out... my libcuda.so was located under /usr/lib/wsl/lib, so I added it to LD_LIBRARY_PATH and things work now! Thank you very much for the help, we can close this thread!
