### ISSUE TITLE
k8s GPU资源分割后运行的时候 会无报错信息 直接kill

### ISSUE THREAD

**Issue by ChenjieXu** [PaddlePaddle/Paddle#44608]
### bug描述 Describe the Bug

使用灵雀云进行部署的时候，当分配的显核小于100的时候（vcuda-core:95）运行 python3 -c "import paddle;paddle.utils.run_check()"，会直接killed，没有报错。但是奇怪的是，很早之前安装2.0.0rc1的镜像就可以运行，但是我把该版本卸载再重装之后，就会报相同的错误。如果分配的显核等于100（相当于一整块卡），就没有问题了。请问为何会有这比较奇怪的表现？

**Comment by thisjiang** [comment]
Hi~Could you give me more information about your environment? Like gcc version, cuda version, gpu type, paddle version and etc. Thanks.

**Comment by ChenjieXu** [comment]
cuda driver版本试过11.4和10.2，镜像runtime版本试过11.2和10.2，paddle版本试过2.3.0，2.2.2和2.0.0rc1。
其他的环境信息我正在联系运维工程师，稍后会提供给您。

**Comment by thisjiang** [comment]
请问您是在哪一步被kill的呢？有没有打印出来`Running verify PaddlePaddle program`这一步呢？
![image](https://user-images.githubusercontent.com/31386411/181213014-1011605e-0573-4d0e-86a8-06ccd043b090.png)

此外，执行` python3 -c "import paddle;print(paddle.__version__)"`会有问题么？

**Comment by ChenjieXu** [comment]
`WARNING: Logging before InitGoogleLogging() is written to STDERR
I0728 01:47:49.621431    44 dynamic_loader.cc:196] Set paddle lib path : /usr/local/lib/python3.6/dist-packages/paddle/libs
I0728 01:47:50.311025    44 init.cc:105] Before Parse: argc is 2, Init commandline: dummy --tryfromenv=fuse_parameter_memory_size,sync_nccl_allreduce,print_sub_graph_dir,gpu_memory_limit_mb,dist_threadpool_size,max_inplace_grad_add,check_nan_inf,use_pinned_memory,use_fast_math,tracer_mkldnn_ops_off,new_executor_use_inplace,reader_queue_speed_test_mode,communicator_is_sgd_optimizer,init_allocated_mem,host_trace_level,get_host_by_name_time,conv_workspace_size_limit,new_executor_sequential_run,reallocate_gpu_memory_in_mb,convert_all_blocks,fast_eager_deletion_mode,cudnn_exhaustive_search,selected_gpus,eager_delete_tensor_gb,pe_profile_fname,rpc_send_thread_num,inner_op_parallelism,fuse_parameter_groups_size,cudnn_exhaustive_search_times,apply_pass_to_program,nccl_blocking_wait,free_idle_chunk,gpu_allocator_retry_time,use_mkldnn,eager_delete_scope,fraction_of_cpu_memory_to_use,initial_gpu_memory_in_mb,tracer_profile_fname,memory_fraction_of_eager_deletion,communicator_send_queue_size,local_exe_sub_scope_limit,use_system_allocator,enable_parallel_graph,new_executor_use_local_scope,use_curand,check_kernel_launch,cpu_deterministic,run_kp_kernel,call_stack_level,multiple_of_cupti_buffer_size,cudnn_batchnorm_spatial_persistent,fraction_of_cuda_pinned_memory_to_use,allreduce_record_one_event,tracer_mkldnn_ops_on,use_stream_safe_cuda_allocator,enable_unused_var_check,cudnn_deterministic,conv2d_disable_cudnn,benchmark,sort_sum_gradient,retain_grad_for_all_tensor,communicator_max_merge_var_num,paddle_num_threads,use_autotune,enable_rpc_profiler,enable_cublas_tensor_op_math,dygraph_debug,free_when_no_cache_hit,use_virtual_memory_auto_growth,use_cuda_managed_memory,allocator_strategy,fraction_of_gpu_memory_to_use,initial_cpu_memory_in_mb 
I0728 01:47:50.311472    44 init.cc:112] After Parse: argc is 1
I0728 01:47:50.381526    44 init.cc:272] ENV [CUSTOM_DEVICE_ROOT] is empty.
Running verify PaddlePaddle program ... 
I0728 01:47:50.782088    44 op_desc.cc:795] CompileTime infer shape on fill_constant
I0728 01:47:50.782745    44 op_desc.cc:795] CompileTime infer shape on uniform_random
I0728 01:47:50.782783    44 infershape_utils.cc:416] BuildInferMetaContext: op kernel signature - Kernel Signature - name: uniform_random; inputs: ; attributes: shape, dtype, min, max, seed; outputs: Out
I0728 01:47:50.805527    44 op_desc.cc:795] CompileTime infer shape on matmul_v2
I0728 01:47:50.806427    44 op_desc.cc:795] CompileTime infer shape on elementwise_add
I0728 01:47:50.809016    44 op_desc.cc:795] CompileTime infer shape on reduce_sum
I0728 01:47:50.809068    44 infershape_utils.cc:416] BuildInferMetaContext: op kernel signature - Kernel Signature - name: sum_raw; inputs: X; attributes: dim, keep_dim, reduce_all, out_dtype; outputs: Out
I0728 01:47:50.810591    44 op_desc.cc:795] CompileTime infer shape on fill_constant
I0728 01:47:50.810665    44 op_desc.cc:795] CompileTime infer shape on reduce_sum_grad
I0728 01:47:50.810727    44 op_desc.cc:795] CompileTime infer shape on elementwise_add_grad
I0728 01:47:50.810787    44 op_desc.cc:795] CompileTime infer shape on matmul_v2_grad
I0728 01:47:50.810797    44 infershape_utils.cc:416] BuildInferMetaContext: op kernel signature - Kernel Signature - name: matmul_grad; inputs: X, Y, Out@GRAD; attributes: trans_x, trans_y; outputs: X@GRAD, Y@GRAD
I0728 01:47:50.811823    44 executor.cc:92] Creating Variables for block 0
I0728 01:47:50.811844    44 scope.cc:228] Create variable fetch
I0728 01:47:50.811851    44 executor.cc:107] Initialize Variable fetch
I0728 01:47:50.811856    44 executor.cc:109] Create Variable fetch global, which pointer is 0x54f4d60 type is 10
I0728 01:47:50.811861    44 scope.cc:228] Create variable feed
I0728 01:47:50.811864    44 executor.cc:107] Initialize Variable feed
I0728 01:47:50.811867    44 executor.cc:109] Create Variable feed global, which pointer is 0x28f13f0 type is 9
I0728 01:47:50.811872    44 scope.cc:228] Create variable create_parameter_1.w_0
I0728 01:47:50.811873    44 executor.cc:107] Initialize Variable create_parameter_1.w_0
I0728 01:47:50.811880    44 executor.cc:109] Create Variable create_parameter_1.w_0 global, which pointer is 0x5500790 type is 7
I0728 01:47:50.811884    44 scope.cc:228] Create variable create_parameter_0.w_0
I0728 01:47:50.811887    44 executor.cc:107] Initialize Variable create_parameter_0.w_0
I0728 01:47:50.811890    44 executor.cc:109] Create Variable create_parameter_0.w_0 global, which pointer is 0x4b09bf0 type is 7
W0728 01:47:50.811941    44 gpu_context.cc:278] Please NOTE: device: 0, GPU Compute Capability: 7.5, Driver API Version: 11.4, Runtime API Version: 11.2
I0728 01:47:50.812135    44 dynamic_loader.cc:218] Try to find library: libcudnn.so from default system path.
W0728 01:47:50.816195    44 gpu_context.cc:306] device: 0, cuDNN Version: 8.1.
I0728 01:47:52.192385    44 dynamic_loader.cc:218] Try to find library: libcublas.so from default system path.
I0728 01:47:53.185099    44 dynamic_loader.cc:218] Try to find library: libcusolver.so from default system path.
I0728 01:47:53.565583    44 dynamic_loader.cc:218] Try to find library: libcusparse.so from default system path.
I0728 01:47:53.866787    44 dynamic_loader.cc:218] Try to find library: libcuda.so from default system path.


--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
No stack trace in paddle, may be caused by external reasons.

----------------------
Error Message Summary:
----------------------
FatalError: `Segmentation fault` is detected by the operating system.
  [TimeInfo: *** Aborted at 1658972873 (unix time) try "date -d @1658972873" if you are using GNU date ***]
  [SignalInfo: *** SIGSEGV (@0x0) received by PID 44 (TID 0x7f20b0259740) from PID 0 ***]

段错误 (核心已转储)`

version输出

python3 -c "import paddle;print(paddle.__version__)"
WARNING: Logging before InitGoogleLogging() is written to STDERR
I0728 01:49:00.218741    73 dynamic_loader.cc:196] Set paddle lib path : /usr/local/lib/python3.6/dist-packages/paddle/libs
I0728 01:49:00.833371    73 init.cc:105] Before Parse: argc is 2, Init commandline: dummy --tryfromenv=dist_threadpool_size,tracer_mkldnn_ops_on,enable_rpc_profiler,run_kp_kernel,print_sub_graph_dir,communicator_is_sgd_optimizer,allreduce_record_one_event,sync_nccl_allreduce,check_nan_inf,initial_gpu_memory_in_mb,gpu_allocator_retry_time,use_system_allocator,enable_parallel_graph,fuse_parameter_memory_size,rpc_send_thread_num,nccl_blocking_wait,cudnn_exhaustive_search,convert_all_blocks,fraction_of_cpu_memory_to_use,selected_gpus,use_pinned_memory,memory_fraction_of_eager_deletion,gpu_memory_limit_mb,tracer_mkldnn_ops_off,cudnn_exhaustive_search_times,use_fast_math,fraction_of_cuda_pinned_memory_to_use,fraction_of_gpu_memory_to_use,cudnn_batchnorm_spatial_persistent,check_kernel_launch,use_virtual_memory_auto_growth,sort_sum_gradient,multiple_of_cupti_buffer_size,enable_cublas_tensor_op_math,eager_delete_scope,communicator_send_queue_size,retain_grad_for_all_tensor,conv_workspace_size_limit,reader_queue_speed_test_mode,free_idle_chunk,init_allocated_mem,fast_eager_deletion_mode,conv2d_disable_cudnn,initial_cpu_memory_in_mb,inner_op_parallelism,paddle_num_threads,host_trace_level,tracer_profile_fname,apply_pass_to_program,use_stream_safe_cuda_allocator,use_cuda_managed_memory,max_inplace_grad_add,pe_profile_fname,free_when_no_cache_hit,fuse_parameter_groups_size,use_mkldnn,use_autotune,cpu_deterministic,use_curand,call_stack_level,eager_delete_tensor_gb,dygraph_debug,reallocate_gpu_memory_in_mb,new_executor_sequential_run,benchmark,new_executor_use_inplace,cudnn_deterministic,new_executor_use_local_scope,enable_unused_var_check,get_host_by_name_time,communicator_max_merge_var_num,local_exe_sub_scope_limit,allocator_strategy 
I0728 01:49:00.833822    73 init.cc:112] After Parse: argc is 1
I0728 01:49:00.934823    73 init.cc:272] ENV [CUSTOM_DEVICE_ROOT] is empty.
2.3.0
I0728 01:49:01.298182    73 mmap_allocator.cc:273] PID: 73, MemoryMapFdSet: set size - 0
I0728 01:49:01.486713    73 mmap_allocator.cc:273] PID: 73, MemoryMapFdSet: set size - 0

**Comment by ChenjieXu** [comment]
用最新打包的镜像是这个输出，之前的镜像输出会在cuDNN Version: 8.1.后面killed，同样的version是能正确输出的

**Comment by thisjiang** [comment]
@ChenjieXu  这几天调研了一下，不知道灵雀云是不是用的自己维护的GPUManager(https://github.com/tkestack/gpu-manager ，从commit上看这项目很久没维护了)来管理GPU资源的：

> GPUManager支持共享和独占两种模式，当负载里tencent.com/vcuda-core request 值在0~100情况下，采用共享模式调度，优先将碎片资源集中到一张卡上，当负载里的tencent.com/vcuda-core request为100的倍数时，采用独占模式调度，gpu-manager-daemonset会根据GPU拓扑结构生成GPU卡的拓扑树，选择最优的结构（距离最短的叶子节点）进行调度分配。
> Ref from: [GPUManager虚拟化方案](https://cloud.tencent.com/developer/article/1685122)

这样看，小于100时用的是碎片化调度，这种情况下可能触发了CUDA的某个bug。 可以单独写个cuda kernel看看能不能跑，如果不能，那应该就是GPUManager的问题。

BTW：Nvidia最近推出了官方维护的[vGPU](https://www.nvidia.com/en-us/data-center/virtual-solutions/)和[MIG](https://docs.nvidia.com/datacenter/tesla/mig-user-guide/)技术，可惜的是，当前只支持CUDA11 + Ampere及以上架构的GPU。

**Comment by ChenjieXu** [comment]
@thisjiang  十分感谢您的回复。CUDA11 + Ampere架构是符合我们场景的，我们可以研究一下，我们也在同步了解道客的产品。

**Comment by jjjjok** [comment]
我也遇到了同样的问题，最后排查应该是显存分配策略的原因，导入一下环境变量export FLAGS_allocator_strategy=naive_best_fit
