### ISSUE TITLE
When/Will optimizers move to PHI API?

### ISSUE THREAD

**Issue by gglin001** [PaddlePaddle/Paddle#44602]
### 请提出你的问题 Please ask your question

hi, 我看到目前 optimizer 相关的 op 依然是使用 `TraceOp` 的方式.

请问这部分将来会切换到类似目前的 `eager_final_state_api_XXX` API 吗?  比如一个 `eager_final_state_api_lamb()` 这种

如果有此计划, 请问有大概的发布时间吗?

**Comment by gglin001** [comment]
update: 已经有了
```
final_state_adamax
final_state_adamw
final_state_adam_
final_state_adadelta

...
```

似乎 python 层还没有完全切换

**Comment by thisjiang** [comment]
Hi~我看您似乎已经找到了问题的答案，请问您还有其它问题么？

**Comment by gglin001** [comment]
> Hi~我看您似乎已经找到了问题的答案，请问您还有其它问题么？


请问大概什么时候会完成所有op的迁移工作(包含 python 层的切换)?

**Comment by thisjiang** [comment]
您好，大部分cpu/gpu的算子迁移会在这一两个月内完成，剩下的目前还不确定
