### ISSUE TITLE
提交PR没有触发paddle-bot

### ISSUE THREAD

**Issue by TUDelftHao** [PaddlePaddle/Paddle#44610]
### 请提出你的问题 Please ask your question

提交PR没有触发paddle-bot自动回复，这是咋回事？ #44579

**Comment by tianshuo78520a** [comment]
有可能服务在升级，或者网络不稳定，导致没有回复，不影响你合入代码

**Comment by TUDelftHao** [comment]
> 有可能服务在升级，或者重启过程中，导致没有回复，不影响你合入代码

好的谢谢
