### ISSUE TITLE
paddle模型直转tensorflow pb或者tflite

### ISSUE THREAD

**Issue by zhly0** [PaddlePaddle/Paddle#44627]
### 需求描述 Feature Description

任务目标：当前正在一些mtk apu平台上开发模型，该平台为AI加速引擎，当前只支持tensorflow模型，需要开发的任务，包含检测，分类，回归等; 

需求场景：如果能够提供paddle模型直接转tflite或者pb的功能，那么很多paddle中提供的算法就可以直接使用，基于当前的paddle模型转onnx，再转tflite或者pb模型的转换流程，还存在很多问题，不能一步到位，且一旦有问题，就无法解决，这些问题将极大的限制paddle的使用，如果官方能够解决，将极大的拓展paddle的使用边界;

功能描述：基于op级的paddle模型转tensorflow模型

**Comment by thisjiang** [comment]
您好，您的反馈对产品非常有价值，我们内部会安排评估，未来有计划尽快回复。

**Comment by hong19860320** [comment]
目前 Paddle Lite 支持 MTK APU，且提供了两种支持方式：
1）一种是 MTK NeuronAdapter （这种需要依赖 MTK 较新的固件支持，需要问 MTK 要，否则会报库找不到的问题）https://www.paddlepaddle.org.cn/lite/develop/demo_guides/mediatek_apu.html
2）另一种是 Android NNAPI https://www.paddlepaddle.org.cn/lite/develop/demo_guides/android_nnapi.html 但对 Android 版本有一定的要求。

我们一般推荐 android nnapi 方式，因为 MTK 对 Android NNAPI 的支持相对完善，特别是对 float32 和 int8 全量化模型均有加速效果。

**Comment by zhly0** [comment]
@hong19860320 您好，您提供的固然是在某些硬件下可用的方式，但有些带算力的mtk sdk只支持tflite格式，所以能够提供直转pb，然后再通过mtk自带的后量化工具转量化tflite的方式是最合适的

**Comment by thisjiang** [comment]
您好！经评估，飞浆没有paddle模型转其它框架的计划。请问您使用的只支持tflite格式的mtk sdk是哪种型号呢？我们可以联系mtk一起添加对该型号的支持。

**Comment by zhly0** [comment]
@thisjiang 您好，您的评估结果，能理解，但远水解不了近渴，如果要使用paddle的话可能还是很麻烦，谢谢
