### ISSUE TITLE
PaddleClas标签文件格式问题

### ISSUE THREAD

**Issue by fan-min-97** [PaddlePaddle/Paddle#44629]
### 请提出你的问题 Please ask your question

在paddleClas中的PaddleClas/ppcls/configs/quick_start/professional/MobileNetV1_multilabel.yaml ：

Metric:
  Train:
    - HammingDistance:
    - AccuracyScore:
  Eval:
    - HammingDistance:
    - AccuracyScore:
    - mAP: {}

在最后添加map:{}这行时，训练验证部分会报错
TypeError: forward() missing 2 required positional arguments: 'gallery_img_id' and 'keep_mask'
，如果想查看map该怎么写呢

**Comment by thisjiang** [comment]
您好！PaddleClas的相关问题欢迎前往[PaddleClas repo](https://github.com/PaddlePaddle/PaddleClas)提issue~
