### ISSUE TITLE
ValueError: Operator "gen_nccl_id" has not been registered. 

### ISSUE THREAD

**Issue by wawltor** [PaddlePaddle/Paddle#44633]
### 请提出你的问题 Please ask your question

在执行的Paddle的执行过程中，会出现下面的问题

https://user-images.githubusercontent.com/66577364/180216202-a1331c83-ab6e-42db-92b0-b4205a5fcd46.jpg

**Comment by thisjiang** [comment]
请问您能给出更多环境信息么？比如系统版本、gcc版本、cuda版本、nccl版本、paddle版本等等，谢谢！

**Comment by wawltor** [comment]
> 请问您能给出更多环境信息么？比如系统版本、gcc版本、cuda版本、nccl版本、paddle版本等等，谢谢！
操作系统：windows
paddle版本：paddlepaddle 2.3.0
cuda版本：11.2

**Comment by thisjiang** [comment]
您好！非常抱歉，Windows暂不支持NCCL，分布式等相关功能，详见[Windows下的PIP安装](https://www.paddlepaddle.org.cn/documentation/docs/zh/install/pip/windows-pip.html)

**Comment by sifuhr** [comment]
那windows 怎么用呢？document_intelligence 文档检索， File "D:\anaconda\envs\llm\lib\site-packages\paddle\fluid\framework.py", line 2713, in get_op_proto
    raise ValueError("Operator \"%s\" has not been registered." % type)
ValueError: Operator "gen_nccl_id" has not been registered.
LAUNCH INFO 2023-05-30 10:42:54,298 Exit code 1
