### ISSUE TITLE
paddle_arguments_set_sequence_start_pos 作用是什么？

### ISSUE THREAD

**Issue by VamWolf** [PaddlePaddle/Paddle#4464]
尝试写一下paddle 的capi...确实挺麻烦. 每个api ，都得查源码才稍微了解,

**Comment by lcy-seso** [comment]
@ranqiu92 @peterzhang2029 请帮忙回答一下关于 CAPI 相关的问题吧，谢谢了。

**Comment by peterzhang2029** [comment]
C-API提供了```paddle_arguments_set_sequence_start_pos```接口来标记每个样本里序列的起始位置，有四个参数：
1.  输入的paddle_arguments; 
2. 输入paddle_arguments的index; 
3. nestedLevel(如果用来控制双层序列中的sub_sequence需要设置为1); 
4. 用来指示每个样本的起始位置的paddle_ivector变量；

示例代码如下：
 ```
 int seq_pos_array[] = {0, 1, 3, 6};
 paddle_ivector seq_pos = paddle_ivector_create(
     seq_pos_array, sizeof(seq_pos_array) / sizeof(int), false, false);
 CHECK(paddle_arguments_set_sequence_start_pos(in_args, 0, 0, seq_pos));
 ```
 
 其中，``` seq_pos_arry ``` 的前3个元素表示对应位置的样本中序列开始的位置，而最后一个元素表示输入数据中所有的dense vector的数量。通过调用```paddle_arguments_set_sequence_start_pos```接口，示例代码将输入数据转化为3个dense vector sequece类型的样本数据:
 
 ```
 [[[1 2 3 4 5]],
 
 [[6 7 8 9 10],
 [11 12 13 14 15]],
 
 [[16 17 18 19 20],
 [21 22 23 24 25],
 [26 27 28 29 30]]]
 ```
类似的issue https://github.com/PaddlePaddle/Paddle/issues/3969
