### ISSUE TITLE
paddle2.4 是否会推出统一的C++  API

### ISSUE THREAD

**Issue by CZMmin** [PaddlePaddle/Paddle#44644]
### 请提出你的问题 Please ask your question

hello，paddle新版本是否会推出统一的C++ API可用于训练，测试，类似libtorch？

**Comment by zyfncg** [comment]
你好，在即将发布的2.4新版本中暂不会对现有的C++ API进行重大更新。
相关的需求和规划我们正在整理中，如果您这边有具体的需求欢迎在issue下交流~

**Comment by yuwoyizhan** [comment]
@zyfncg 我觉得,对于paddlepaddle,强化学习parl,图神经网络来说,C++训练和推理是非常有必要的,因为不是每个人都是python大神,每个人都精通python语法和python库的语法.有不少人擅长的是C++.对于这3个来说,每个项目的训练和推理,代码都是大不相同,对于一个非python大神来说,指望他用python写一个训练或者推理,太强人所难了.所以支持C++语言是非常有必要的.
对于clas,det,seg,ocr等框架来说,无论是训练还是推理,python代码都是大同小异,这时我就没看出来C++的用处了.飞桨有文档说了,C++推理比python推理快,这点很重要.训练是否也更快呢?当然了,对于这些框架来说,C++有时也是很有用的,比如复现论文时,代码确实大不相同.
关于C++,我最大的需求,就是在VS2022企业版的最新版本中,可以使用C++最新版本C++latest进行编程,哈哈哈哈.如果能在AI STUDIO也支持C++编程,那就更好了.

**Comment by yuwoyizhan** [comment]
据我了解,libtorch的很多用户,使用C++编程.我想知道,如果飞桨支持C++编程的话,libtorch转换为飞桨模型是否更简单呢?
学术界论文超过80%的论文使用pytorch或者libtorch,飞桨有没有想过哪里不如他呢?飞桨除了有中文文档这点百分比比libtorch强之外,还有什么方面肯定比pytorch强的吗?
我认为,飞桨总体上做的非常好,非常非常多的功能都可以找到.目前来说,我觉得有几点飞桨还没有的.
1,除了推理部分,其他部分完全不能用C++.请问强化学习parl,图神经网络这两个套件的推理部分能用C++吗?
2.我认为,对于任何跟深度学习或者机器学习相关的项目,飞桨都应该至少提供一个解决方案,不要求达到学术界或者工业界SOTA的地步,至少达到很牛逼,一般人编程无法超过的地步.这就好比C++的string类型,随便在知乎查一下,就可以看到一堆人不满意string,说出了string的一大堆缺点,有些人还另外编写一个字符串类型,试图在自己的C++项目中替换string类型.估计string最大缺点就是编码问题吧.但不可否认的是,对于大多数C++使用者来说,标准库的string确实比const char*类型,或者比多数人能编写出来的字符串类型要好用的多.
文字生成图像,图像生成文字,这两个多模态的功能,目前没能在飞桨框架中找到任何可用的模块.这两种功能,最近2年被各大公司所研究,比如谷歌等.
飞桨没有任何数据归纳总结的可用套件.考虑波士顿房价预测这个问题,我在实践中找到了非常多数据,包括状态和结果,但是我没有模型可以训练这些数据,我得自己组建模型,这对于飞桨入门者要求太高了.
飞桨目前没有任何时间序列预测的模块,无论是短时间序列预测,还是长时间序列预测.这两个功能不重要吗?据我所知,2021年的最佳论文奖就是关于长时间序列预测吧.AAAI 2021 最佳论文.之前反馈过,飞桨无动于衷,现在论文贴出来了,总可以做点改进吧.
我还是那句话,飞桨至少应该提供一个模型,满足多数用户,多数情况,而不是让客户遇到问题,就自己想方设法组建模型.
Hub本来是提供模型的好套件,实现一行代码训练和推理.但我看了一下,Hub提供的模型,基本都是其他套件的模型,换句话说,如果其他套件没有的模型,Hub基本也没有的.

**Comment by yuwoyizhan** [comment]
还有一点建议,现在市面上有非常多的框架,无论是国内还是国外,框架是越来越多,功能和模块也是越来越多,更关键的是,多数代码是开源的.我认为,飞桨应该找两个高手,去研究别人的框架和功能,把那些别人的好功能,无论是算法还是模型,只要是飞桨没有的,就搬到飞桨来.这就是开源的最终奥义.飞桨一个框架学习起来就非常费力了,你不能要求用户精通所有框架的所有模型和代码.应该想尽一切办法,把飞桨客户都留在飞桨里.
除了深度学习框架,还有各种各样的python库.python库应该有不少是数据相关的,比如我上面说的归纳总结数据的功能.完全可以搬过来,哈哈哈哈.
我还是那句话,飞桨应该对于每个功能都提供一个模型.不能要求达到SOTA,至少超过多数人手写的模型,满足多数情况,就像C++的string类型一样,不会最好,但可以满足了.
@zyfncg @Ligoml @ZzSean @jzhang533 @thisjiang

**Comment by dingjiaweiww** [comment]
你好，飞桨强化学习parl,图神经网络这两个套件的推理部分都能用C++

**Comment by Ligoml** [comment]
@yuwoyizhan hi，关于这个问题，因为涉及范围很广，所以内部讨论后认为可以先发起一次全面的产品调研再下结论。如果你对这个问题很有兴趣，欢迎发邮件到 ext_paddle_oss@baidu.com 联系我们~

**Comment by yuwoyizhan** [comment]
@Ligoml 兄弟,在哪个帖子都能看到你,这个飞桨不会是你负责吧?哈哈哈哈.你说的关于这个问题很广,我也不知道你说的这个问题,指的是提供C++接口问题,还是提供大量模型的问题,比如时间序列预测.我觉得,时间序列预测是一个重要科研课题,实践中也有不少非科研人员需要用到,这个课题,不吹不黑,难度大,你们弄几个牛逼哄哄的模型让我们训练,比起我们自己组网的效果好多了的.听说AAAI2021的最佳论文就是长时间序列预测,能在几千几万篇论文中脱颖而出,获得最佳论文奖,我想,这就充分说明该论文的进步性,也充分说明长时间序列预测的重要性.翻遍飞桨整个平台,竟然找不到一个套件,找不到一个模型可以跑时间序列预测,无论是长时间序列预测还是短时间序列预测,要用什么模型,都必须自己组建网络,哈哈哈哈.ai studio上有不少时间序列预测的项目,说白了都是自己组网的,根本不是顶尖研究人员的模型,更不是那种有重大改进的论文的模型.一个LSTM吹上天,笑死.

估计每年都有不少序列预测的论文,希望你们可以选几篇重要的,性能SOTA的复现一下,没地方放就放在Hub也行,我相信,绝大多数飞桨使用者根本无法复现这些论文,比如AAAI2021最佳论文,几个人有实力复现.市面上肯定有pytorch的版本,看看github,但不能要求我因为一个论文,去掌握一个深度学习框架啊.拜托了,大佬.而且我只想用飞桨,不能因为今天一点问题学习另一个框架,明天因为一点问题又学习一个新的框架,哪个框架都肯定有一点自己的优势,同时学习几个框架,我是神仙吗?这要求太高了.

给N维数据,时间无关,组建模型,训练,这个我觉得也有很大应用,但我觉得这个模型估计都不知道如何找论文,你们如果要以论文为本,那就别复现了,组建这个模型,肯定比时间序列预测的模型容易得多,我倒是可以自己组建.

说到C++接口,我不久前才明白,如果我不能精通python,我根本就用不了parl为我做实际上有用的事情,有点可笑.pytorch推出C++接口好几年了,现在好像都有java接口了.如果让我选择的话,我会尽全力推出一个可用的C++接口的版本,后来再想方设法逐步改善,提供好用的版本.比如先推出一个性能不高的,再慢慢优化性能.或者是接口少点的.

最后说句,能否加个QQ或者微信,方便聊聊.issue几天答复一次,速度比起QQ几秒答复慢多了.
QQ:1226194560   微信:18820785964

**Comment by Ligoml** [comment]
@yuwoyizhan 有没有一种可能，我是paddle的pm~ 你的诉求已经转交给相关团队，可以等他们联系你进行更多沟通哈

**Comment by CZMmin** [comment]
希望paddle更注重底层生态，硬件环境兼容、性能挖掘、语言支持等。不缺乏应用型人才及各行业的相关产品，缺乏一片统一的土壤。

**Comment by yuwoyizhan** [comment]
如果飞桨只注重底层,不提供任何模型,所有模型都要自己组网的话,我保证,全世界没人用飞桨.clas,det,seg,ocr,等等,哪个套件没有提供模型,甚至对于多数套件来说,主要功能就是提供模型.只提供函数,让飞桨使用者去组建模型,100个人都未必有一个人有本事组建牛逼哄哄的模型.举个例子,以前高层卷积网络性能比低层还差劲,试问有几个人能解决?有专家提出ResNet才解决了问题.指望每个飞桨使用者组建模型时,都能解决遇到的所有问题,无异于痴人说梦.
飞桨如果能在每个问题上,都推出一个好用的模型,不要求天下无敌,不要求SOTA,就能满足绝大多数飞桨使用者的需求了.在每个问题上,都提供一个模型,估计飞桨也做不到.但是在很多重要问题上,提供一个好用的模型,这绝对是飞桨的义务.

**Comment by sunzhongkai588** [comment]
> ### 请提出你的问题 Please ask your question
> hello，paddle新版本是否会推出统一的C++ API可用于训练，测试，类似libtorch？

你好，我是飞桨的框架pm，可以留一下联系方式给我吗？我邮箱sunzhongkai@baidu

**Comment by engineer1109** [comment]
非常需要
