### ISSUE TITLE
使用paddle进行训练，很慢。初步推理为paddle与numpy转换效率低。

### ISSUE THREAD

**Issue by shuzizihemu** [PaddlePaddle/Paddle#44675]
##
最近把一个torch模型改为paddle，参加一下比赛。发现训练速度要比torch慢了很多。
两个模型的差别不大，主要就是把一些用torch的运算改为paddle的了。
##
训练的时候，发现，程序能跑。但是，相比于torch慢了很多（两者的所有超参数都是保持一致的，数据集什么的都一致）。
于是我认为可能是数据加载的时候有拉胯了。
这是torch运行速度以及占用
![image](https://user-images.githubusercontent.com/48058763/181244518-3380dae9-1096-41e2-9c5a-d231a1ffda28.png)
![image](https://user-images.githubusercontent.com/48058763/181248825-1ee3f1cf-4d2c-4360-8551-8088007e44aa.png)

这是paddle运行速度以及占用
![image](https://user-images.githubusercontent.com/48058763/181244907-ca68cb4f-8e79-4369-9583-4faaf8422c7b.png)

我把模型训练以及验证的部分全部注释掉。发现确实慢。
当我使用paddle.set_device("cpu")时，发现没有任何提升。
## 

于是我认为可能是paddle处理的就慢，
于是把数据处理中的paddle操作。
![image](https://user-images.githubusercontent.com/48058763/181246026-c1ea7226-fbdf-4a4a-aba6-a55764d46519.png)
类似上图的，中间都用np进行处理了。
![image](https://user-images.githubusercontent.com/48058763/181247072-bf45804c-08f5-4754-9881-cb6d775c4388.png)
右侧用paddle框架的加载速度直接速度提升了3倍。运来只有100it/s多的迭代速度

但是再次进行训练时，速度仍然没有得到改善。
于是我认为，是模型里面存在大量的paddle计算操作，所以很慢。
后来发现了这个帖子https://gitee.com/paddlepaddle/Paddle/issues/I3S49J
跟我想的基本一致，paddle跟numpy之间的转换效率低。而torch这点做的挺不错。

希望你们能快点进行优化，这已经是2.3版本的了，你们说会解决，还没解决。

同样的数据集。网络torch一轮训练5小时，paddle得训练13个小时，即使用V100来训练，也会很大程度上的浪费资源。这可不是开玩笑的效率低。希望你们可以重视并优化。

**Comment by frankwhzhang** [comment]
你好 已收到反馈

**Comment by frankwhzhang** [comment]
你好 这个会在2.4解决。2.4的动态图调度性能会大福提升

**Comment by shuzizihemu** [comment]
>好吧， 辛苦你们了，那2.4版本大概什么时候上线呢，想体验一波

**Comment by Ligoml** [comment]
感谢指出，我们希望重点跟进一下这个问题，希望你提供一些关键信息：
1. 方便提供一下你写的paddle代码和参考的torch代码吗？可以给一个repo链接哈~
2. 我们希望确认你写的paddle模型在精度上是否和参考模型已经对齐，如最终的精度、中间过程的精度是否对齐？
3. 数据加载过程中，可以试一下调大dataloader的num_workers，看看会不会有改善

cc @heavengate
