### ISSUE TITLE
自建问答模型的数据集

### ISSUE THREAD

**Issue by hanfu** [PaddlePaddle/Paddle#44694]
### 请提出你的问题 Please ask your question

你好 我试图在问答模型中使用自建数据集
数据集训练集为`(context, question, start, end)`, 测试集为`(context, question)`
我尝试了`paddle.io.Dataset`和`paddlenlp.datasets.MapDataset`, 都会在传入`paddle.io.DataLoader`的时候失败
可以提供一个案例么， 从`[(context,question,start,end)...]`列表对开始 步步建立数据集

我找到的教程要么是内置dataset 要么就是其他任务的，主要是视觉任务 我水平有限参考不出来
感谢

**Comment by ceci3** [comment]
https://github.com/PaddlePaddle/PaddleNLP/issues/2913
可以参考这个哈~
