### ISSUE TITLE
some suggestions about the issue format of paddle

### ISSUE THREAD

**Issue by jiangfeng** [PaddlePaddle/Paddle#4470]
For better experience ， scikit-learn  is a good reference

**Comment by llxxxll** [comment]
#### Description


#### Steps/Code to Reproduce


#### Expected Results


#### Actual Results


#### Versions






FYI URL？https://github.com/scikit-learn/scikit-learn/issues/new

**Comment by jiangfeng** [comment]
yes, a very clear description of a problem

**Comment by pkuyym** [comment]
Closed due to inactivity.
