### ISSUE TITLE
关于DPIN数据集以及任务的问题

### ISSUE THREAD

**Issue by AlbusWei** [PaddlePaddle/Paddle#44709]
DPIN（https://arxiv.org/abs/2106.05482 ）并没有开源数据集和代码，在比赛任务页面也并没有提供相关资料，而任务要求为“按照论文数据，预计以DIN模型作为对比，AUC获得性能提升复现后合入PaddleRec套件，并添加TIPC”，请问在哪里获取相关数据集？或者使用什么公共数据集（因为引入了位置信息，一般的公共数据集并不适用这个任务）。

**Comment by wangzhen38** [comment]
您好，DPIN的验收标准暂时还没确定，我们也正在筛选其他推荐赛题，预计近期会放出来～
