### ISSUE TITLE
ERROR: paddlepaddle-2.3.1-cp310-cp310-manylinux1_x86_64.whl is not a supported wheel on this platform.

### ISSUE THREAD

**Issue by Flora-0707** [PaddlePaddle/Paddle#44713]
Hi, I tried to use command line "python -m pip install /home/florawang/Downloads/paddlepaddle-2.3.1-cp310-cp310-manylinux1_x86_64.whl" to install on raspberry pi, it showed this error, my raspberry pi is aarch64. How can I solve this issue?

**Comment by Tlntin** [comment]
x86 and raspberry pi's arm64 are not the same architecture.
you may need to compile it for yourself.

how to compile? you can see like this.[link](https://github.com/PaddlePaddle/Paddle/issues/44668)
