### ISSUE TITLE
Paddle2.3.1 CUDA11.3/11.6 GPU:RTX3070索引有误

### ISSUE THREAD

**Issue by Victory8858** [PaddlePaddle/Paddle#44721]
### bug描述 Describe the Bug

```python
import paddle

label = paddle.to_tensor([0, 8, 9])
mask = paddle.to_tensor([False, True, True], dtype='bool')
print(label[mask])                     # Paddle2.3.1运行后输出[0, 0]，在Paddle2.2下运行是[8, 9]正常的
```
![image](https://user-images.githubusercontent.com/47514961/181691065-85c07540-722e-4cfe-a192-b57ec1f4f402.png)

**Comment by Tlntin** [comment]
试了一下，windows系统和楼主一样。
ubuntu 22.04输出正常。
![image](https://user-images.githubusercontent.com/28218658/181699497-3540b06c-f6d8-4eb0-9f3d-62f0901ea599.png)
![image](https://user-images.githubusercontent.com/28218658/181699532-3ae21967-9245-42b6-ae0e-6761fab0a944.png)

**Comment by Victory8858** [comment]
> 试了一下，windows系统和楼主一样。 ubuntu 22.04输出正常。 ![image](https://user-images.githubusercontent.com/28218658/181699497-3540b06c-f6d8-4eb0-9f3d-62f0901ea599.png) ![image](https://user-images.githubusercontent.com/28218658/181699532-3ae21967-9245-42b6-ae0e-6761fab0a944.png)

输出正常吗，明显有错误，不应该是【8，9】吗

**Comment by Tlntin** [comment]
> > 试了一下，windows系统和楼主一样。 ubuntu 22.04输出正常。 ![image](https://user-images.githubusercontent.com/28218658/181699497-3540b06c-f6d8-4eb0-9f3d-62f0901ea599.png) ![image](https://user-images.githubusercontent.com/28218658/181699532-3ae21967-9245-42b6-ae0e-6761fab0a944.png)
> 
> 输出正常吗，明显有错误，不应该是【8，9】吗

windows不正常，ubuntu正常的。同一个版本2.3.1

**Comment by Victory8858** [comment]
> > > 试了一下，windows系统和楼主一样。 ubuntu 22.04输出正常。 ![image](https://user-images.githubusercontent.com/28218658/181699497-3540b06c-f6d8-4eb0-9f3d-62f0901ea599.png) ![image](https://user-images.githubusercontent.com/28218658/181699532-3ae21967-9245-42b6-ae0e-6761fab0a944.png)
> > 
> > 
> > 输出正常吗，明显有错误，不应该是【8，9】吗
> 
> windows不正常，ubuntu正常的。同一个版本2.3.1

OK，get

**Comment by wgq18** [comment]
请问ubuntu22.04如何安装paddle？需要降级gcc版本吗？@Tlntin

**Comment by Tlntin** [comment]
> 请问ubuntu22.04如何安装paddle？需要降级gcc版本吗？@Tlntin
参考此贴：
https://github.com/PaddlePaddle/Paddle/issues/44668
