### ISSUE TITLE
能否推出pytorch的API到飞桨的API的转换函数

### ISSUE THREAD

**Issue by yuwoyizhan** [PaddlePaddle/Paddle#44746]
### 需求描述 Feature Description

学术界超过80%的论文使用pytorch,也有非常非常多的开源项目使用pytorch,飞桨的太少了.我得到一个牛逼的pytorch模型,我也不知道如何转换成飞桨模型.目前希望飞桨可以推出一个C++函数,这个函数的功能就是,我传入pytorch的某个API的名称,C++函数把pytorch的API的名称转换为飞桨的API.
我觉得只要飞桨安排两个熟悉pytorch和飞桨的API的高手,这件事就可以做好了吧.
有了这个API转换函数,我应该可以把很多pytorch项目转换成飞桨项目了吧.哈哈哈哈,至少有希望.
有一个issue说,目前飞桨在做python和C++的接口统一,我是否可以理解为,把python和C++的函数名称变得一样,形参个数和类型也变得一样,返回类型也变得一样?

**Comment by FrostML** [comment]
可以参考下官网文档 [PyTorch 1.8 与 Paddle 2.0 API映射表](https://www.paddlepaddle.org.cn/documentation/docs/zh/guides/model_convert/pytorch_api_mapping_cn.html#pytorch-1-8-paddle-2-0-api)
