### ISSUE TITLE
报名

### ISSUE THREAD

**Issue by Caoxuheng** [PaddlePaddle/Paddle#44750]
### 问题描述 Please describe your issue

【队名】：Fusion_King

【序号】：54

【论文】：Unsupervised deep learning for super-resolution reconstruction of turbulence

【状态】：报名

【repo链接】：https://github.com/Caoxuheng/Unsupervised-deep-learning-for-super-resolution-reconstruction-of-turbulence

**Comment by zhangting2020** [comment]
请在黑客松第3期任务总览的issue下报名，https://github.com/PaddlePaddle/Paddle/issues/43938
