### ISSUE TITLE
test WITH_GPU=OFF on travis

### ISSUE THREAD

**Issue by luotao1** [PaddlePaddle/Paddle#4476]
We need to add ONLYCPU test on travis, in order to avoid  compiler error like https://github.com/PaddlePaddle/Paddle/issues/4417  .

**Comment by helinwang** [comment]
The TeamCity CI seems not having a overwhelming amount of load. I added a extra step of WITH_GPU=OFF into the TeamCity PR CI. Please let me know if you think it's ok.

**Comment by luotao1** [comment]
> the build time I tested increased from 15min to 17 min

That's reasonable. I think it's OK, thx very much! @helinwang

**Comment by pkuyym** [comment]
Close it due to solved. Please fail free to reopen it if necessary.
