### ISSUE TITLE
debug 时会卡一下报 "no module named cv2" 

### ISSUE THREAD

**Issue by gglin001** [PaddlePaddle/Paddle#44760]
## 复现代码

demo.py
```python
import paddle
import paddle.dataset.image

print(paddle.__version__)
```

## 如何复现

debug 上面的代码

## 复现结果

<img width="1623" alt="Screen Shot 2022-08-01 at 11 18 56 AM" src="https://user-images.githubusercontent.com/13805221/182065479-36a321fe-713c-4932-9265-8547291710f6.png">

## 原因

问题来自于这里
https://github.com/PaddlePaddle/Paddle/blob/3a3017801b7dfc017d5e70ae4db876db294f8a17/python/paddle/dataset/image.py#L48

**Comment by danleifeng** [comment]
请问使用的是paddle 什么版本呢？在什么环境下使用呢？

**Comment by gglin001** [comment]
debug 分支, 手动编译的版本

**Comment by danleifeng** [comment]
debug分支 是基于那个tag 或者branch呢？

**Comment by danleifeng** [comment]
代码里 按理说对cv2做了一次判断，若返回值不为0，就不会import
<img width="783" alt="image" src="https://user-images.githubusercontent.com/52735331/182118649-c8cd0540-9c32-4dab-9dd7-34547e814b71.png">

**Comment by gglin001** [comment]
> debug分支 是基于那个tag 或者branch呢？

用 2.3.1 relasae 的 wheel 似乎没有这个问题, ~请问如何安装 nightly 的 wheel?~ 

> 如何安装 nightly 的 wheel 

见:
https://www.paddlepaddle.org.cn/

**Comment by gglin001** [comment]
可能和构建选项有关,  应该不是通常的问题,  会关闭这个 issue

**Comment by lichade-son** [comment]
> 可能和构建选项有关, 应该不是通常的问题, 会关闭这个 issue

我也遇到了，请问怎么解决啊

**Comment by iamqiz** [comment]
@danleifeng @gglin001 这是个大问题 ,虽然直接运行没问题, 但是debug时 那个 `subprocess.Popen([interpreter, "-c", "import cv2"],` 的错误会被debugger捕获到  , pycharm 和vscode 里debug都能复现 , 在pycharm里出现这个错误时,显示如下, 不仅很影响debug体验,而且小白很容易就以为是pycharm出了问题! (比如我,我搜了一下午百度google/jetbrains Youtrack找这个问题的解决方法,) 墙裂建议修复这个问题!
![Snipaste_2022-12-09_21-22-00](https://user-images.githubusercontent.com/48077521/206711788-fcd1219c-97e0-4b45-8c48-748227b0deb2.png)
