### ISSUE TITLE
使用paddleslime的Inference 模型复训

### ISSUE THREAD

**Issue by moonlightian** [PaddlePaddle/Paddle#44771]
### 请提出你的问题 Please ask your question

请问，paddleslim下的recover_inference_program貌似提供了将推理模型转为训练模型的途径，请问能否给出一个demo来演示一下使用方法？

**Comment by wanghaoshuang** [comment]
可以参考这里：https://github.com/PaddlePaddle/PaddleSlim/tree/develop/example/auto_compression
