### ISSUE TITLE
paddle inference: can the input already be on GPU, is there any interface provided

### ISSUE THREAD

**Issue by guojinrong-nn** [PaddlePaddle/Paddle#44819]
### 请提出你的问题 Please ask your question

I have put my input on GPU and wanna do inference, but only found `input_tensor.copy_from_cpu()`, is there any interface to read input data on GPU directly? 

Greatly appreciate!

**Comment by RichardWooSJTU** [comment]
Sorry, due to many considerations, we don't have such an interface for the time being. Please describe the usage scenario in detail for us to discuss. Thank you!

**Comment by guojinrong-nn** [comment]
I have several preprocess ops executed by GPU, after that, I wanna do inference directly, a pass by GPU address is preferred.

**Comment by guojinrong-nn** [comment]
More specifically, a pass by **GPU address** of **Tensor** is preferred. Other than where the input is, on CPU or GPU, the type of input should not be limited to np.array. 

Hope to have support in the future.

**Comment by RichardWooSJTU** [comment]
Thank you for your reply, we will discuss seriously.
