### ISSUE TITLE
Error: Variable value (input) of OP(fluid.layers.embedding) expected >= 0 and < 12800, but got 4916593788014559232.

### ISSUE THREAD

**Issue by March35** [PaddlePaddle/Paddle#44817]
### 请提出你的问题 Please ask your question

![image](https://user-images.githubusercontent.com/48037392/182343249-2865440d-1a8e-4971-8831-6f0b7a69190e.png)
但是打印了src_ids, 没有超过12800的数:
![image](https://user-images.githubusercontent.com/48037392/182343494-b96882cd-e72e-4e61-891c-2860a7e0665f.png)

**Comment by ForFishes** [comment]
您好，这里input的tensor中，有的数值超过了12800，导致访问越界。可以打印一下embedding的输入的值，看是否有错误的值。

**Comment by chuong-phung** [comment]
Is there any update?
