### ISSUE TITLE
什么时候支持Mac M1/M2 GPU?

### ISSUE THREAD

**Issue by Lawyer-ray** [PaddlePaddle/Paddle#44830]
### 需求描述 Feature Description

任务目标（请描述你正在做的项目是什么，如模型、论文、项目是什么？）正在使用Mac M1 Pro作为生产机型，具体使用了PaddleOCR与PaddleNLP，目前Paddle在Mac下仅支持CPU模式，PaddleOCR与PaddleNLP运行效率并不出色; 
需求场景（请描述你的项目中为什么需要用此功能）加快解决问题，提高生产效率；
;  <br /> 功能描述（请简单描述或设计这个功能）

**Comment by dingjiaweiww** [comment]
感谢你的反馈，对于飞桨支持mac M1 上的GPU，我们内部正在评估调研，请问你需要在mac m1 上运行什么模型呢，使用GPU是想测试一下，还是有特殊项目需要运行呢？ @Lawyer-ray

**Comment by James4Ever0** [comment]
运行模型可以使用gpu或者neural engine 训练模型使用gpu

可以用coreml createml 进行训练和运行 用metal 3进行训练

目前tensorflow和pytorch都已经支持了metal 3

**Comment by James4Ever0** [comment]
search for 'gpu' 'opencl' in codebase to find legacy implementations, which are useful for reimplementation in metal 3. existing implementations in tensorflow-metal and torch (mps) might also be helpful. needless to say the metal 3 documentation.

**Comment by gudh** [comment]
[mac m1 怎么安装兼容? ](https://github.com/PaddlePaddle/PaddleSpeech/issues/1714)
> paddle 不支持这个架构，所以 paddlespeech 也不能支持，抱歉

Wish to use `paddlespeech` for my new project, but because `paddle` doesn't support mac M1 platform, as a result, `paddlespeech` fail to run on mac m1

Wonder if mac m1 will be supported in the near future, any updates?

Anyway, thanks for building this framework!

**Comment by James4Ever0** [comment]
now `paddle` supports m1 CPU but not GPU

[install paddle for mac m1 cpu](https://www.paddlepaddle.org.cn/documentation/docs/zh/install/pip/macos-pip.html)

**Comment by ioiogoo** [comment]
> now `paddle` supports m1 CPU but not GPU
> 
> [install paddle for mac m1 cpu](https://www.paddlepaddle.org.cn/documentation/docs/zh/install/pip/macos-pip.html)

Has any solution for m2 CPU or GPU?
I can success installed the package with  this command `pip install paddlepaddle`, but when I import paddle, it's return `ERROR: flag 'flagfile' was defined more than once (in files '/Users/paddle/xly/workspace/f2bafd01-b80e-4ac8-972c-1652775b2e51/Paddle/build/third_party/gflags/src/extern_gflags/src/gflags.cc' and '/tmp/gflags-20211021-3963-1mi18ai/gflags-2.2.2/src/gflags.cc')`

**Comment by axuu** [comment]
> > now `paddle` supports m1 CPU but not GPU
> > [install paddle for mac m1 cpu](https://www.paddlepaddle.org.cn/documentation/docs/zh/install/pip/macos-pip.html)
> 
> Has any solution for m2 CPU or GPU? I can success installed the package with this command `pip install paddlepaddle`, but when I import paddle, it's return `ERROR: flag 'flagfile' was defined more than once (in files '/Users/paddle/xly/workspace/f2bafd01-b80e-4ac8-972c-1652775b2e51/Paddle/build/third_party/gflags/src/extern_gflags/src/gflags.cc' and '/tmp/gflags-20211021-3963-1mi18ai/gflags-2.2.2/src/gflags.cc')`

same error.

**Comment by ltto** [comment]
> 

mee too

**Comment by yaowt05** [comment]
> > now `paddle` supports m1 CPU but not GPU
> > [install paddle for mac m1 cpu](https://www.paddlepaddle.org.cn/documentation/docs/zh/install/pip/macos-pip.html)
> 
> Has any solution for m2 CPU or GPU? I can success installed the package with this command `pip install paddlepaddle`, but when I import paddle, it's return `ERROR: flag 'flagfile' was defined more than once (in files '/Users/paddle/xly/workspace/f2bafd01-b80e-4ac8-972c-1652775b2e51/Paddle/build/third_party/gflags/src/extern_gflags/src/gflags.cc' and '/tmp/gflags-20211021-3963-1mi18ai/gflags-2.2.2/src/gflags.cc')`

downgrade your opencv-python to 4.6.0.66

**Comment by ajayghiyad** [comment]
guys I was able to run paddlepaddle CPU version on macbook in docker
using this config
https://github.com/PaddlePaddle/Paddle/issues/54531#issuecomment-1619601905
