### ISSUE TITLE
后台任务解压缩文件

### ISSUE THREAD

**Issue by aixuxian** [PaddlePaddle/Paddle#44846]
### 请提出你的问题 Please ask your question

尝试一些比赛项目时候，遇到的问题。
有些比赛的数据集较大，是以zip压缩包的形式存在的。
想要运行后台任务，构建版本的时候只能在Notebook里面写好解压缩数据的命令。但是却遇到似乎是权限问题，无法解压。
如下命令
!unzip -q /home/aistudio/data/data151025/Calibration.zip -d /home/aistudio/data/data151025/val
会报出checkdir:  cannot create extraction directory: val
Input/output error
的问题。
而如下命令
!unzip -q /home/aistudio/data/data151025/Calibration.zip -d /home/aistudio/work/val
可以正常执行，但是解压缩过程太慢了，根本完成不了。怀疑是不是把work目录当做了项目输出结果，太大导致任务失败，但是却不显示任务失败，一直执行。
这种情况有没有解决方案，感谢~~~

**Comment by chenxiaozeng** [comment]
建议在AI Studio社区咨询下，可以邮件联系 aistudio@baidu.com，或者加入其官方QQ群交流: 580959619

**Comment by aixuxian** [comment]
@chenxiaozeng 感谢感谢！！
