### ISSUE TITLE
paddle_infer.create_predictor(config)  预测报错

### ISSUE THREAD

**Issue by freecui** [PaddlePaddle/Paddle#44889]
### bug描述 Describe the Bug

环境：版本 python3.8.0   cuda10.1.105; cudnn 7.6.5 ； paddlepaddle  2.3.1 用了gpu和cpu版本； 跑的是https://github.com/PaddlePaddle/ERNIE 项目中的task有 text_generation 和text_matching, 这两个task 训练的时候都是可以正常运行的，但是infer的时候就出错了，代码段是在erniekit/controller/inference.py 中的predictor = paddle_infer.create_predictor(config) 这段代码就会出现错：不管用cpu还是gpu都会报同样的问题
![Uploading image.png…]()

**Comment by freecui** [comment]
INFO: 08-04 16:25:25: inference.py:53 * 140495399245632 init env, build inference....
INFO: 08-04 16:25:25: inference.py:94 * 140495399245632 cpu inference....
E0804 16:25:25.154521 20984 analysis_config.cc:610] EnableMKLDNN() only works when IR optimization is enabled.
E0804 16:25:25.154595 20984 analysis_config.cc:610] EnableMKLDNN() only works when IR optimization is enabled.


--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
0   paddle_infer::Predictor::Predictor(paddle::AnalysisConfig const&)
1   std::unique_ptr<paddle::PaddlePredictor, std::default_delete<paddle::PaddlePredictor> > paddle::CreatePaddlePredictor<paddle::AnalysisConfig, (paddle::PaddleEngineKind)2>(paddle::AnalysisConfig const&)
2   paddle::AnalysisPredictor::Init(std::shared_ptr<paddle::framework::Scope> const&, std::shared_ptr<paddle::framework::ProgramDesc> const&)
3   paddle::AnalysisPredictor::PrepareProgram(std::shared_ptr<paddle::framework::ProgramDesc> const&)
4   paddle::framework::NaiveExecutor::CreateVariables(paddle::framework::ProgramDesc const&, int, bool, paddle::framework::Scope*)

----------------------
Error Message Summary:
----------------------
FatalError: `Segmentation fault` is detected by the operating system.
  [TimeInfo: *** Aborted at 1659601525 (unix time) try "date -d @1659601525" if you are using GNU date ***]
  [SignalInfo: *** SIGSEGV (@0x0) received by PID 20984 (TID 0x7fc7a25d5740) from PID 0 ***]

Segmentation fault (core dumped)

**Comment by freecui** [comment]
补充环境： ubuntu 18.04

**Comment by freecui** [comment]
代码分支拉取的是：ernie-open-v1.0
![Uploading image.png…]()

**Comment by freecui** [comment]
为啥没人回复呢？

**Comment by xiaoxiaohehe001** [comment]
可以将config.switch_ir_optim(False) 修改为 config.switch_ir_optim(True)进行测试，https://github.com/PaddlePaddle/ERNIE/blob/94a2367ba7f0f83b48330233450ea095d8dc9382/erniekit/controller/inference.py#L71

**Comment by freecui** [comment]
已经更改了为 config.switch_ir_optim(True)进行测试，但是没有什么帮助，依然报之前的错误

**Comment by freecui** [comment]
又没回复了

**Comment by bitszhang** [comment]
在 predictor = paddle_infer.create_predictor(config) 前面加上代码
```
config.switch_ir_optim(False)
config.enable_use_gpu(100, 0)
```

**Comment by asafberreby** [comment]
not working for me, suffering from the same issue.
