### ISSUE TITLE
cuda 10.0 可以安装版本的paddle? 可以安装cuda 10.1对应版本的paddle?

### ISSUE THREAD

**Issue by cqray1990** [PaddlePaddle/Paddle#44896]
### 问题描述 Issue Description

cuda 10.0 可以安装版本的paddle? 可以安装cuda 10.1对应版本的paddle?

### 版本&环境信息 Version & Environment Information

cuda 10.0
paddlepaddle:2.3

**Comment by yaoxuefeng6** [comment]
你好 现在paddle可支持的cuda最低版本是10.1 可以在这个链接按需安装哈 https://www.paddlepaddle.org.cn/install/quick?docurl=/documentation/docs/zh/install/pip/linux-pip.html
