### ISSUE TITLE
paddlepaddle2.3.1训练wide&deep速度慢

### ISSUE THREAD

**Issue by veridone** [PaddlePaddle/Paddle#44905]
### 请提出你的问题 Please ask your question

paddlepaddle2.3.1训练wide&deep速度K40 比 V100慢了10倍
具体的速度对比
K40
![image](https://user-images.githubusercontent.com/6941942/182832513-4ebed7ec-52ad-48b2-9468-16da6f900f45.png)
V100
![image](https://user-images.githubusercontent.com/6941942/182832394-12c3e2fb-b573-4370-bc69-6ce7488c70d4.png)
可能是哪些问题导致的

**Comment by veridone** [comment]
K40  paddlepaddle-gpu Version: 2.3.1.post101
V100 paddlepaddle-gpu： 2.3.1 driver ：CUDA Version: 11.2

**Comment by yaoxuefeng6** [comment]
不同硬件训练性能确实有可能有所不同
