### ISSUE TITLE
官方教程2.3中错误

### ISSUE THREAD

**Issue by Initial01LingXu** [PaddlePaddle/Paddle#44916]
### 文档链接&描述 Document Links & Description

教程：https://www.paddlepaddle.org.cn/tutorials/projectdetail/3907095，2.1.4和2.1.5封装前后不一致：
2.1.4对每个特征进行归一化处理，使得每个特征的取值缩放到0~1之间，是线性函数归一化(Min-Max Scaling)。在该过程中也没有用到平均值avgs，是没有必要求取的数值。
### 计算train数据集的最大值，最小值，平均值
    maximums, minimums, avgs = \
                     training_data.max(axis=0), \
                     training_data.min(axis=0), \
     training_data.sum(axis=0) / training_data.shape[0]
### 对数据进行归一化处理
    for i in range(feature_num):
    #print(maximums[i], minimums[i], avgs[i])
    data[:, i] = (data[:, i] - minimums[i]) / (maximums[i] - minimums[i])

2.15封装中用到了平均值avgs，但公式得到的结果不是0~1，与上面零散的代码也不一致，应该改为减去最小值minimus而不是平均值avgs。
### 计算训练集的最大值，最小值，平均值
    maximums, minimums, avgs = training_data.max(axis=0), training_data.min(axis=0), \
                                 training_data.sum(axis=0) / training_data.shape[0]

### 对数据进行归一化处理
    for i in range(feature_num):
        #print(maximums[i], minimums[i], avgs[i])
        data[:, i] = (data[:, i] - avgs[i]) / (maximums[i] - minimums[i])

### 请提出你的建议 Please give your suggestion

2.1.5avgs，改成minimums和2.1.4一致，两个代码删除avgs的求取

**Comment by iclementine** [comment]
合理。
min-max normalization 是不需要求平均值的。
(x-sigma)/mu 这种是 z-score 标准化。

**Comment by iclementine** [comment]
我们稍后修改一下教程。

**Comment by Initial01LingXu** [comment]
> 合理。 min-max normalization 是不需要求平均值的。 (x-sigma)/mu 这种是 z-score 标准化。

z-score 标准化公式应该是(x-mu)/sigma，要用z-score 标准化公式分母也应改为sigma公式，而不是简单的最大值减最小值。

**Comment by XYZ-916** [comment]
你好，非常感谢能够指出教程中的错误。归一化确实是减去最小值而非均值。相关部分内容已经进行了修改。再次对您的细心发现表示感谢。
