### ISSUE TITLE
Linux下Conda安装后如何使用飞桨进行python程序的编写

### ISSUE THREAD

**Issue by stvlllll** [PaddlePaddle/Paddle#44927]
### 请提出你的问题 Please ask your question

Linux下Conda安装后，是自己再安装一个jupyter或者pychram，在上面直接写就行了吗

**Comment by iclementine** [comment]
IDE 或者 编辑器，或者 jupyter 之类的 notebook(literal programming 工具) 都是根据个人习惯选择，都可以的。
