### ISSUE TITLE
windows develop分支从源码编译 cmake报错

### ISSUE THREAD

**Issue by xiaohemaikoo** [PaddlePaddle/Paddle#44942]
### bug描述 Describe the Bug

按照官网步骤，在windows develop分支下：
执行到
cmake .. -GNinja -DWITH_GPU=ON
报错。
release/2.3 cmake 正常。

![QQ图片20220805155829](https://user-images.githubusercontent.com/35183089/183116149-96085a19-0bd7-45a0-9d67-74a1161e047b.png)

**Comment by betterpig** [comment]
你好，我在本地拉取最新develop分支无法复现这个问题。你能再试试吗

**Comment by Ligoml** [comment]
请提供更多环境信息，我们看下

**Comment by luotao1** [comment]
请提供下commit信息，便于复现

**Comment by xiaohemaikoo** [comment]
我找到原因了。这是jinja2的bug，在3.1.0版本以上的jinja2已经修复了。 以前版本jinja2如果传入FileSystemLoader参数是Path类型会触发问题。如果传入路径参数是string类型可以兼容低版本jinja2的这个bug。
