### ISSUE TITLE
Paddle2.2.0编译后找不到libpaddle_fluid.so文件

### ISSUE THREAD

**Issue by chensuo2048** [PaddlePaddle/Paddle#44961]
问题描述 Issue Description

ubuntu18.04、gcc7.5.0、cmake3.16.0、paddle2.2.0

使用cmake构建：

cmake -DCMAKE_BUILD_TYPE=Release -DWITH_PYTHON=OFF -DWITH_MKL=ON -DWITH_MKLDNN=OFF -DWITH_GPU=OFF -DWITH_FLUID_ONLY=ON ..

make -j$(nproc)

编译成功后，build文件夹内存在paddle_inference_install_dir，但是找不到任何包含libpaddle_fluid.so或libpaddle_fluid.a的库文件。

我需要使用lac分词工具，编译lac的时候指定了paddle_inference_install_dir为PADDLE_ROOT，但是编译报错找不到libpaddle_fluid.a文件

### 版本&环境信息 Version & Environment Information

****************************************
Paddle version: None
Paddle With CUDA: None

OS: Ubuntu 18.04
Python version: 3.6.9

CUDA version: None
cuDNN version: None.None.None
Nvidia driver version: None
****************************************

**Comment by JZ-LIANG** [comment]
请参考这个链接配置编译环境

https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/fluid/inference/api/high_level_api.md

**Comment by chensuo2048** [comment]
> 请参考这个链接配置编译环境
> 
> https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/fluid/inference/api/high_level_api.md

**Comment by chensuo2048** [comment]
> 请参考这个链接配置编译环境
> 
> https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/fluid/inference/api/high_level_api.md

你好，这个链接跟我的问题好像不太相关。我遇到的问题是lac编译失败了

**Comment by JZ-LIANG** [comment]
2.0之后预测库的名字变了。现在是 libpaddle_inference.so
