### ISSUE TITLE
paddle inference TensorRT加速推理报错

### ISSUE THREAD

**Issue by Shrinco** [PaddlePaddle/Paddle#44960]
### 请提出你的问题 Please ask your question

我在使用paddle inference推理时出现了下图中的错误，使用GPU推理时不会报错使用TensorRT加速时就会出现下图中的错误，没有查到相关资料，请问该如何解决呢？
![image](https://user-images.githubusercontent.com/50402380/183319436-d23c8d9a-00aa-478b-9543-3acc8220ea9f.png)

**Comment by JZ-LIANG** [comment]
算子维度不匹配，请查看slice 算子 的输入输出是否满足 tensorRT 的要求

**Comment by Shrinco** [comment]
> 算子维度不匹配，请查看slice 算子 的输入输出是否满足 tensorRT 的要求

这个bug是在线程推理的时候出现的错误，第一次推理是可以正常执行并得到结果的，第二次开启线程就会报这个错误
