### ISSUE TITLE
paddlepaddle-gpu==1.2.0post97设置为cpu预测无效，安裝1.2.0的包无法找到资源

### ISSUE THREAD

**Issue by weiyang-1** [PaddlePaddle/Paddle#44974]
### 问题描述 Issue Description

![image](https://user-images.githubusercontent.com/34814137/183347746-cf91ba50-e42b-4c72-87f7-566a6ea989c1.png)

### 版本&环境信息 Version & Environment Information

paddle version: 1.2.0gpu-post97
系统环境Centos7
python2.7.5

**Comment by weiyang-1** [comment]
I0808 13:51:41.251214 22374 Util.cpp:166] commandline:  --use_gpu=False --trainer_count=1 
Init Predict Network
F0808 13:51:41.569115 22374 hl_cuda_device.cc:569] Check failed: cudaSuccess == cudaStat (0 vs. 35) Cuda Error: CUDA driver version is insufficient for CUDA runtime version
*** Check failure stack trace: ***
    @     0x7f36157624ad  google::LogMessage::Fail()
    @     0x7f3615765f5c  google::LogMessage::SendToLog()
    @     0x7f3615761fd3  google::LogMessage::Flush()
    @     0x7f361576746e  google::LogMessageFatal::~LogMessageFatal()
    @     0x7f361571c9d3  hl_stream_synchronize()
    @     0x7f36154afb5e  paddle::LstmLayer::forwardBatch()
    @     0x7f36154b12b2  paddle::LstmLayer::forward()
    @     0x7f361533e9bd  paddle::NeuralNetwork::forward()
    @     0x7f36152dce3d  _wrap_GradientMachine_forward
    @     0x7f363db1225a  PyEval_EvalFrameEx
    @     0x7f363db1408d  PyEval_EvalCodeEx
    @     0x7f363db1158c  PyEval_EvalFrameEx
    @     0x7f363db1408d  PyEval_EvalCodeEx
    @     0x7f363db1158c  PyEval_EvalFrameEx
    @     0x7f363da93308  (unknown)
    @     0x7f363db0cc91  PyEval_EvalFrameEx
    @     0x7f363da93308  (unknown)
    @     0x7f363db0cc91  PyEval_EvalFrameEx
    @     0x7f363db1408d  PyEval_EvalCodeEx
    @     0x7f363db1158c  PyEval_EvalFrameEx
    @     0x7f363db1408d  PyEval_EvalCodeEx
    @     0x7f363db1158c  PyEval_EvalFrameEx
    @     0x7f363db1170d  PyEval_EvalFrameEx
    @     0x7f363db1408d  PyEval_EvalCodeEx
    @     0x7f363da9dabd  (unknown)
    @     0x7f363da78ab3  PyObject_Call
    @     0x7f363da87aa5  (unknown)
    @     0x7f363da78ab3  PyObject_Call
    @     0x7f363db0a947  PyEval_CallObjectWithKeywords
    @     0x7f363da8877c  PyInstance_New
    @     0x7f363da78ab3  PyObject_Call
    @     0x7f363db0d286  PyEval_EvalFrameEx
已放弃(吐核)

**Comment by JZ-LIANG** [comment]
老版本 paddle 可以通过 checkout 到对应版本 release 分支上 源码编译获得。 请参考https://www.paddlepaddle.org.cn/documentation/docs/zh/install/compile/linux-compile.html

**Comment by dingjiaweiww** [comment]
paddle 1.2 是非常老的版本了，无法从pip源下载了，推荐你使用飞桨最新版本的安装包，可以从官网获取：https://www.paddlepaddle.org.cn/install/quick?docurl=/documentation/docs/zh/install/pip/linux-pip.html
