### ISSUE TITLE
Can Paddle build with clang on Linux?

### ISSUE THREAD

**Issue by gglin001** [PaddlePaddle/Paddle#44978]
### 请提出你的问题 Please ask your question

在 Linux 尝试了使用 clang-6 构建 paddle 遇到很多编译器报错, 尝试临时修复也失败, 请问在 Linux 上支持使用 clang 构建吗? 对 clang 版本有要求吗?

**Comment by jzhang533** [comment]
也许可以试试更高版本的clang。
我在Mac上用clang 13是可以编译成功的。

`Apple clang version 13.0.0 (clang-1300.0.27.3)`

**Comment by gglin001** [comment]
mac os上我这边也是ok的, 是 Linux 上 使用 clang 会遇到问题, 在去除了

```
      -Werror
      -Wall
```

https://github.com/PaddlePaddle/Paddle/blob/develop/cmake/flags.cmake#L144-L145

后, 在 ubuntu18.04 上 使用 clang-10 是可以编译的,(也许其他版本也是ok的, 未测试)


另外添加了 

```
if(CMAKE_CXX_COMPILER_ID STREQUAL "Clang" AND LINUX)
  # only tested for calng-10 on ubuntu18.04
  set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -fPIC")
  set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -fPIC")
endif()
``` 

to `CMakeLists.txt`

**Comment by gglin001** [comment]
希望官方能够添加对 Linux 上 使用 clang 构建的支持

**Comment by jzhang533** [comment]
嗯， @pangyoki 在看这个呢。
多问一句，为啥要在linux下用clang，不用gcc呢？

**Comment by gglin001** [comment]
> 嗯， @pangyoki 在看这个呢。 多问一句，为啥要在linux下用clang，不用gcc呢？

1. 我觉得支持 clang 构建是一个十分合理且必要的 feature
2. 支持 clang 构建后 未来又可能结合使用 llvm 相关的工具提高代码质量(tbd)
3. 目前实际的需要是由于 使用使用 gdb 单步调试非常慢(使用 vscode 插件时), 使用 lldb 会好很多, 需要使用 clang 构建生成 debug 符号

与 3 相关的一个问题, 请问有 单步 debug paddle c++ 代码 的最佳实践吗? 直接编译 debug 版本的库会非常慢(来源于糟糕的 cmake 配置, 当然现在有人在做改进)

**Comment by gglin001** [comment]
a temporary method to do this(just for develop)
https://github.com/gglin001/Paddle-fork/commit/9638c20d37eeab7fa11de806620422efd05abf08
