### ISSUE TITLE
Need to support CUDA11.3 version

### ISSUE THREAD

**Issue by liyongkang123** [PaddlePaddle/Paddle#44980]
### 需求描述 Feature Description

您好，想问下可以支持CUDA11.3 版本吗，11.3作为cuda系列里面一个比较重要的版本，如果我们飞桨可以支持的话就更好了，现在我在使用中也比较急需，感谢了！！！

**Comment by JZ-LIANG** [comment]
paddle 是支持 cuda11.3 的。
但你是指官方 的 pip 版本吗？ 

如果急需 cuda11.3 支持可以先在 对应环境下源码编译，请参考 https://www.paddlepaddle.org.cn/documentation/docs/zh/install/pip/linux-pip.html

**Comment by dingjiaweiww** [comment]
你可以使用飞桨官网提供的pip cuda11.2 的安装包，是可以在您cuda11.3 环境中使用的，CUDA 版本是向下兼容的；

**Comment by liyongkang123** [comment]
谢谢大家，问题已解决，感恩，我将把该问题关闭哈~
