### ISSUE TITLE
调用capi，编译通过，启动失败

### ISSUE THREAD

**Issue by EchoCX** [PaddlePaddle/Paddle#4499]
报错如下：
```bash
[libprotobuf ERROR google/protobuf/message_lite.cc:119] Can't parse message of type "paddle.ModelConfig" because it is missing required fields: type
Invoke paddle error 3 
paddle_gradient_machine_create_for_inference(&this->_machine, this->_buf, (int)this->_size)
```

**Comment by gongweibao** [comment]
给一下capi的下载地址和用来训练的paddle的版本

**Comment by EchoCX** [comment]
capi的下载地址: CONFIGS('baidu/third-party/paddle-capi@master@git_branch',NeedOutput())
paddle的版本：PaddlePaddle 0.9.0

**Comment by EchoCX** [comment]
https://github.com/PaddlePaddle/Paddle/issues/4413 
我的问题和这里是一样的，调用 convert_protobin.sh 并没有生成pb的bin。

**Comment by fingthinking** [comment]
@EchoCX 你的这个CONFIGS('baidu/third-party/paddle-capi@master@git_branch',NeedOutput())是我建的，不是paddle官方的，我进行了一些升级，里面有两个版本，请参考项目中的README.md文件
