### ISSUE TITLE
使用gpu版本的paddlepaddle infer多张图片时候提示显存不足

### ISSUE THREAD

**Issue by PMPBinZhang** [PaddlePaddle/Paddle#45014]
### bug描述 Describe the Bug

imag_vin是一张(155, 1355, 3)维度的图片
使用gpu 3090

rec_client = pdx.deploy.Predictor('./model_rec', use_gpu=True)
s1 = time.perf_counter()
# results = rec_client.predict(image_vin)
results = rec_client.predict([image_vin, image_vin, image_vin, image_vin, image_vin, image_vin, image_vin, image_vin, image_vin, image_vin])
e1 = time.perf_counter()
print("gpu: ", (e1 - s1))

**Comment by pangyoki** [comment]
你好，尝试减小batch size或者图片数量可以成功运行吗？
