### ISSUE TITLE
[论文复现]如何创建复数的parameter

### ISSUE THREAD

**Issue by renmada** [PaddlePaddle/Paddle#45020]
### 问题描述 Please describe your issue
1. paddle.create_parameter不能创建complex64的类型
2. set value 报错
``` python
 self.weight = paddle.create_parameter([self.num_freqs, in_channels, out_channels], dtype=paddle.float32)
 self.weight.set_value(paddle.as_complex(paddle.randn([self.num_freqs, in_channels, out_channels, 2])))
```
```
need tensor with dtype paddle.float32  but load tensor with dtype paddle.complex64
```

**Comment by pangyoki** [comment]
你好，目前不支持复数类型的参数，请问是在什么场景下需要使用呢？

**Comment by renmada** [comment]
论文复现赛,torch代码
```
        self.weight = nn.Parameter(torch.empty((self.num_freqs, in_channels, out_channels), dtype=torch.cfloat))

```

**Comment by ZhangCheng2332** [comment]
> 你好，目前不支持复数类型的参数，请问是在什么场景下需要使用呢？

您好，我论文中需要计算很多含有虚数的张量，其中有一个要求就是计算paddle.exp(L)，其中L为tensor，dtype为paddle.complex64。但是paddle.exp()只允许输入数据类型为float32、float64的tensor。请问有没有什么解决办法，让我计算dtype为paddle.complex64的tensor时不损失虚部。

**Comment by Ligoml** [comment]
复数创建是支持的，但是API还未做到全量支持，你可以梳理一下需要复数计算的API有哪些，我们综合看下~
另外论文复现组委会需要看下这个题目 @Evezerest

**Comment by littletomatodonkey** [comment]
你好，这篇论文的编号是多少呢？

**Comment by aptx1231** [comment]
> 你好，这篇论文的编号是多少呢？

我在复现论文57，CoST: Contrastive Learning of Disentangled Seasonal-Trend Representations for Time Series Forecasting。也遇到了这个问题，无法创建复数类型的参数。

【repo链接】：https://github.com/aptx1231/CoST_Paddle

**Comment by littletomatodonkey** [comment]
好的，我们再评估下这篇论文哈，你可以先看看其他的论文~感谢你的反馈
