### ISSUE TITLE
在训练过程中出现malloc_consolidate(): invalid chunk size

### ISSUE THREAD

**Issue by yeyupiaoling** [PaddlePaddle/Paddle#45026]
### 请提出你的问题 Please ask your question

 - PaddlePaddle 2.3.1
 - Ubuntu 18.04
 - 双卡1080ti
 - CUDA 10.2

在训练过程中出现以下错误，前面已经正常训练了10多轮了。
```
malloc_consolidate(): invalid chunk size
ERROR: Unexpected segmentation fault encountered in DataLoader workers.
ERROR: Unexpected segmentation fault encountered in DataLoader workers.
```

**Comment by wanghuancoder** [comment]
你好，你提供的信息太少了。我没有办法通过以上信息做什么怀疑或者建议。
你可以使用GDB进行调试：
1. 如果有core dump，可以 gdb python coreXXX
2. 如果没有core dump，可以 gdb -ex r --args python <programname>.py <arguments>

**Comment by yeyupiaoling** [comment]
@wanghuancoder 它输出的就这三行。我试试你几个命令

**Comment by yeyupiaoling** [comment]
设置`drop_last=True`就没再出现这个问题了。
