### ISSUE TITLE
paddle.jit.to_static修饰下，函数返回张量的梯度标记

### ISSUE THREAD

**Issue by wykkyle** [PaddlePaddle/Paddle#45039]
### 请提出你的问题 Please ask your question

![image](https://user-images.githubusercontent.com/20754685/183834856-c7609a9a-383c-4948-91f4-6a4f56b19cab.png)

用to_static转静态图时，报错说某操作仅支持stop_gradient为true的情况。
检查发现一些函数，如paddle.meshgrid：
在to_static修饰下，返回的tensor变量的stop_gradient值为False，
没有to_static修时，返回的tensor变量的stop_gradient值为True。

这种程序行为应该如何理解。
希望不要求导，是应该手工设置stop_gradient值为True吗。

paddle版本：2.3.1

**Comment by 0x45f** [comment]
你好，代码中`x, y = rpn()`拿到的x, y的stop_gradient=True就表示**不需要求导**了。如果forward中某些操作说仅支持stop_gradient=True，那么就需要在forward函数中手动设置tensor.stop_gradient=True

**Comment by wykkyle** [comment]
> 

好的，多谢。在多问一句，没有要求stop_gradient=True的地方，忽略stop_gradient的区别不会引起额外运算吧。

**Comment by 0x45f** [comment]
> > 
> 
> 好的，多谢。在多问一句，没有要求stop_gradient=True的地方，忽略stop_gradient的区别不会引起额外运算吧。

因为x, y = rpn()拿到的x, y的stop_gradient=True，paddle.jit.to_static修饰下的forward中的逻辑不会计算反向，所以忽略stop_gradient也不会引起额外的运算

**Comment by wykkyle** [comment]
明白了。
