### ISSUE TITLE
paddle和pytorch对pow(0,0)的梯度结果有diff

### ISSUE THREAD

**Issue by betterpig** [PaddlePaddle/Paddle#45054]
### bug描述 Describe the Bug

Paddle和pytorch在求pow(0, 0)的梯度时结果diff。
Paddle结果：
<img width="583" alt="image" src="https://user-images.githubusercontent.com/51314274/183904449-0d86b677-aa91-459b-8137-6c4bea0a7301.png">

pytorch结果：
<img width="384" alt="image" src="https://user-images.githubusercontent.com/51314274/183904554-fe1f667e-e36b-4c90-ba8a-f6782740f086.png">

复现代码：
Paddle-develop版本

> import paddle
> x = paddle.to_tensor([0.], stop_gradient=False)
> y = paddle.to_tensor([0.], stop_gradient=False)
> z = paddle.pow(x, y)
> z.backward()
> print(x.grad)
> print(y.grad)

pytorch-1.12.1

> import torch 
> x = torch.tensor(0.0,requires_grad=True)
> y = torch.tensor(0.0,requires_grad=True)
> z = torch.pow(x, y)
> z.backward()
> print(x.grad)
> print(y.grad)

**Comment by wanghuancoder** [comment]
感谢您的反馈！@Bobholamovic 请复现以下，并判定是否合理。感谢。

**Comment by Bobholamovic** [comment]
该问题可以复现，但我认为该行为无需改变，原因如下：

1. `pow(0, 0)`的值[在微积分中没有定义](https://en.wikipedia.org/wiki/Zero_to_the_power_of_zero)，因为极限$lim_{(x,y)->(0,0)}{x^y}$不存在。由于上述原因，`pow(x,y)`在`(0,0)`处不可微分，只能计算次微分，因此我认为`paddle.power(0, 0)`给出的梯度在数学上是合理的。
2. 在工程上，真正需要用到`pow(0, 0)`的场合较少，如果`paddle.power(0, 0)`给出正常数值的梯度，可能导致代码中某些隐藏的bug难以及时暴露出来。
