### ISSUE TITLE
关于tensor的dtype为complex的问题

### ISSUE THREAD

**Issue by ZhangCheng2332** [PaddlePaddle/Paddle#45063]
### 请提出你的问题 Please ask your question

我论文中需要计算很多含有虚数的张量，其中有一个要求就是计算paddle.exp(L)，其中L为tensor，dtype为paddle.complex64。但是paddle.exp()只允许输入数据类型为float32、float64的tensor。请问有没有什么解决办法，让我计算dtype为paddle.complex64的tensor时不损失虚部。

源代码：

import paddle
from math import floor
import math

def forward_radon_freq(m,dt,h,p,N,flow,fhigh):
    nt = paddle.to_tensor((m.shape[-2]), dtype=paddle.float32)
    nq = paddle.to_tensor((m.shape[-1]), dtype=paddle.float32)

    nh = h.shape[0]
    h = paddle.to_tensor(h, dtype=paddle.float32)
    h = h / paddle.max(paddle.abs(h))

    def nextpow2(n) -> int:
        n = paddle.to_tensor(n, dtype=paddle.float32)
        n__ = paddle.ceil(paddle.log2(paddle.abs(n)))
        return n__

    nfft = 2 * (2 ** nextpow2(nt))
    M = paddle.fft.fft(m, nfft, axis=0)
    D = paddle.zeros((nfft, nh))
    i = paddle.complex(real=paddle.to_tensor((0.0), dtype=paddle.float32), imag=paddle.to_tensor((1.0), dtype=paddle.float32))

    ilow = floor(flow * dt * nfft) + 1
    if ilow < 1:
        ilow = 1

    ihigh = floor(fhigh * dt * nfft) + 1
    if ihigh > floor(nfft / 2) + 1:
        ihigh = floor(nfft / 2) + 1

    for ifreq in range(ilow, (ihigh + 1)):
        f = 2. * math.pi * (ifreq - 1) / nfft / dt
        L = paddle.exp(i * f * ((paddle.pow(h, N)).reshape(-1, 1).mm((-1)*p.reshape(1, -1))))
        x = M[ifreq-1,:].T
        y = L.mm(x.unsqueeze(1))
        D[ifreq-1,:] = y.T
        D[nfft+2-ifreq-1,:]  = paddle.conj(y).T
    D[nfft//2-1,:] = paddle.zeros((1,nh))
    d = (paddle.real(paddle.fft.ifft(D, axis=0)))
    nt = int(nt)
    d = d[0:nt,:]
    return d

**Comment by zhwesky2010** [comment]
@ZhangCheng2332 你好，复数的支持我们正在开展工作。@iclementine 可以帮忙看下这个`paddle.exp`在计划范围内吗

**Comment by ZhangCheng2332** [comment]
> @ZhangCheng2332 你好，复数的支持我们正在开展工作。@iclementine 可以帮忙看下这个`paddle.exp`在计划范围内吗

您好，我打算接下来科研逐步由pytorch转移到paddle，我们的课题是利用神经网络处理一些inverse problem，需要处理频域数据。目前pytorch是支持复数的，希望paddle后续也能够实现。

**Comment by iclementine** [comment]
这个也在计划范围内的。

**Comment by ZhangCheng2332** [comment]
> 这个也在计划范围内的。

您好，大约什么时间能够发布能够这一支持复数的版本

**Comment by iclementine** [comment]
> 大约什么时间能够发布能够这一支持复数的版本

可能在 2.4 版本会包含这个。
