### ISSUE TITLE
2.1版本训练权重转1.8版本权重问题

### ISSUE THREAD

**Issue by zzm422** [PaddlePaddle/Paddle#45070]
### 请提出你的问题 Please ask your question

2.1版本训练的权重model.pdparams文件转成1.8版本权重, 文件为__model__和model_params,用于推理?没有找到方法,求助!!!!!!!

**Comment by zhwesky2010** [comment]
@zzm422 你好，是说2.3的save_inference_model保存的参数能通过1.8的load_inference_model来加载吗

**Comment by zhwesky2010** [comment]
@zzm422 你试下直接在load_inference_model时指定下文件全名

**Comment by zzm422** [comment]
> 

1、训练保存模型参数使用：（paddle2.1）
paddle.save(model.state_dict(), os.path.join(config.model_save_dir, "model.pdparams"))
paddle.save(optimizer.state_dict(), os.path.join(config.model_save_dir, "optimizer.pdopt"))
训练保存的模型参数文件为model.pdparams

2、推理使用：（paddle1.8）
[inference_program, feed_target_names, fetch_targets] = fluid.io.load_inference_model(dirname=model_dir, executor=exe, params_filename=model_name)
results = exe.run(inference_program, feed={feed_target_names[0]: images}, fetch_list=fetch_targets)
加载需要的模型和参数为：__model__和model_params两个文件

3、问题：如何由model.pdparams转成__model__和model_params，用于推理。

**Comment by zhwesky2010** [comment]
paddle.save保存的只有动态图参数，如果需要动态图模型+参数，需要使用paddle.jit.save，然后使用paddle.jit.load或者paddle.static.load_inference_model加载。
1.8的这个fluid.io.load_inference_model可以试试，应该是支持不了paddle.jit.save的产出

**Comment by ggbond3** [comment]
同问，在使用K210部署paddle时，AIstudio案例是paddle1.8的模型转化成kdmodel,现已经使用paddle2.3和paddleslim生成模型，但无法转换，想要将其转化成1.8下fluid.io生成的模型该怎么转。
