### ISSUE TITLE
多机多卡训练速度会变慢

### ISSUE THREAD

**Issue by yeyupiaoling** [PaddlePaddle/Paddle#45092]
### 请提出你的问题 Please ask your question

 - PaddlePaddle 2.3.1
 - NCCL 2.8.4
 - CUDA 10.2

启动命令
```
python -m paddle.distributed.launch --ips="192.168.4.17,192.168.4.7" --gpus=0,1 train.py
```

如果是单机多卡，每台的训练时间差不多在6到7个小时，
但是双机多卡之后，就变成了1天6个小时左右，慢很多，这是什么原因。

**Comment by haozech** [comment]
您好 能提供下具体硬件信息么

**Comment by yeyupiaoling** [comment]
一台是：双2080ti
另一台是：双1080ti

@haozech

**Comment by gongweibao** [comment]
机器之间的带宽是多少？是不是机器间通信时间长导致的？

**Comment by yeyupiaoling** [comment]
内网是千兆的，实测传输文件有100M/s，通信应该没有问题。

**Comment by gongweibao** [comment]
没注意名字，原来是夜雨飘零呀，好久不见^_^。最近忙啥那？

**Comment by gongweibao** [comment]
1. 这个是不是得看模型大小，预估传输时间？根据计算时间和网络通信时间来看是否慢了？
2. 两台机器是不是负载均衡的？慢的机器和快的机器速度比怎么样？
3. 用的是fp16还是fp32？
如果方便用NV insight，可以试试这个工具，看看timeline。问题出在哪个阶段。
也可以用https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/profiler/Profiler_cn.html#cn-api-profiler-profiler 来看一下timeline。

**Comment by gongweibao** [comment]
有时间帮忙提一些易用性的问题，paddle的同学会跟进解决的。感谢呀！

**Comment by yeyupiaoling** [comment]
>没注意名字，原来是夜雨飘零呀，好久不见^_^。最近忙啥那？

看名字记不清你是谁了，^_^

**Comment by yeyupiaoling** [comment]
>这个是不是得看模型大小，预估传输时间？根据计算时间和网络通信时间来看是否慢了？

模型是有点大，模型参数文件和优化方法参数文件共有300多M呢？

>两台机器是不是负载均衡的？慢的机器和快的机器速度比怎么样？

两台服务器性能差不了多少，单机多卡训练时间分别是6h和7h左右这样子。

>用的是fp16还是fp32？

用的是float32

**Comment by gongweibao** [comment]
`模型是有点大，模型参数文件和优化方法参数文件共有300多M呢？`
你可以算一下通信时间和计算时间，然后算一下理论的加速比。

**Comment by gongweibao** [comment]
> > 没注意名字，原来是夜雨飘零呀，好久不见^_^。最近忙啥那？
> 
> 看名字记不清你是谁了，^_^

相互没见过。搞fluid的时候看过你的ISSUE。

**Comment by yeyupiaoling** [comment]
>你可以算一下通信时间和计算时间，然后算一下理论的加速比。

有空的时候用下面的例子试试Profiler计算官方的例子。
https://www.paddlepaddle.org.cn/documentation/docs/zh/guides/06_distributed_training/cluster_quick_start_cn.html

**Comment by yeyupiaoling** [comment]
>相互没见过。搞fluid的时候看过你的ISSUE。

哈哈
