### ISSUE TITLE
[pdmodel][shape]dynamic_shape转换static_shape

### ISSUE THREAD

**Issue by alanzhai219** [PaddlePaddle/Paddle#45104]
### 请提出你的问题 Please ask your question

有一个pdmodel，通过netron发现其输入是[?,3,640,640]。是否有办法将其转换为[1,3,640,640]
谢谢

**Comment by haozech** [comment]
对于导出的inference model，不建议直接修改其输入batchsize。如果您有组网代码可以在动态图转静态图的InputSpec设置shape   https://www.paddlepaddle.org.cn/documentation/docs/zh/guides/jit/principle_cn.html
