### ISSUE TITLE
cuda11.6,cudnn8.4,提示Could not load library cudnn_cnn_infer64_8.dll. Error code 193

### ISSUE THREAD

**Issue by monkeycc** [PaddlePaddle/Paddle#45112]
### 问题描述 Please describe your issue

cuda_11.6.2_511.65_windows
cudnn-windows-x86_64-8.4.0.27_cuda11.6-archive
报错
Could not load library cudnn_cnn_infer64_8.dll. Error code 193

换成cudnn8.2 不会

**Comment by Liyulingyue** [comment]
我遇到了相同的问题，8.3也不行

W0814 15:01:53.073433 31504 gpu_resources.cc:61] Please NOTE: device: 0, GPU Compute Capability: 8.6, Driver API Version: 11.6, Runtime API Version: 11.6
W0814 15:01:53.080451 31504 gpu_resources.cc:91] device: 0, cuDNN Version: 8.3.
W0814 15:01:53.702119 31504 gpu_resources.cc:201] WARNING: device: . The installed Paddle is compiled with CUDNN 8.4, but CUDNN version in your machine is 8.3, which may cause serious incompatible bug. Please recompile or reinstall Paddle with compatible CUDNN version.
Could not load library cudnn_cnn_infer64_8.dll. Error code 193

**Comment by haozech** [comment]
您需要根据机器上的cuda/cudnn版本选择对应版本的paddle进行安装  paddle安装包列表在这里 https://www.paddlepaddle.org.cn/documentation/docs/zh/install/Tables.html#whl-release

**Comment by monkeycc** [comment]
`python -m pip install paddlepaddle-gpu==2.3.1.post116 -f https://www.paddlepaddle.org.cn/whl/windows/mkl/avx/stable.html`

那这个 有何意义 ？

我都是按照要求 cuda 11.6   cudnn 8.4

还要我再去手动对应 安装一次 ？

**Comment by monkeycc** [comment]
您需要根据机器上的cuda/cudnn版本选择对应版本的paddle进行安装 paddle安装包列表在这里 https://www.paddlepaddle.org.cn/documentation/docs/zh/install/Tables.html#whl-release`

`pip install https://paddle-wheel.bj.bcebos.com/2.3.1/windows/windows-gpu-cuda11.6-cudnn8-mkl-avx/paddlepaddle_gpu-2.3.1.post116-cp38-cp38-win_amd64.whl`

python3.8  cuda11.6   cudnn  8.4

在win环境

重新安装对应的版本  解决可用 

@Liyulingyue

**Comment by monkeycc** [comment]
问题一样的

我在paddleX训练
提示
cudnn_cnn_infer64_8.dll 有问题

需要cuda11.2的cudnn_cnn_infer64_8.dll  覆盖上去 才正常
@haozech

**Comment by shuzizihemu** [comment]
2.3.2的也有这问题。
W0829 18:23:39.251986 11820 gpu_resources.cc:61] Please NOTE: device: 0, GPU Compute Capability: 8.6, Driver API Version: 11.6, Runtime API Version: 11.6
W0829 18:23:39.253978 11820 gpu_resources.cc:91] device: 0, cuDNN Version: 8.4.
Could not load library cudnn_cnn_infer64_8.dll. Error code 193
太辣鸡了。

**Comment by JiaPai12138** [comment]
> 2.3.2的也有这问题。 W0829 18:23:39.251986 11820 gpu_resources.cc:61] Please NOTE: device: 0, GPU Compute Capability: 8.6, Driver API Version: 11.6, Runtime API Version: 11.6 W0829 18:23:39.253978 11820 gpu_resources.cc:91] device: 0, cuDNN Version: 8.4. Could not load library cudnn_cnn_infer64_8.dll. Error code 193 太辣鸡了。


> ### 问题描述 Please describe your issue
> cuda_11.6.2_511.65_windows cudnn-windows-x86_64-8.4.0.27_cuda11.6-archive 报错 Could not load library cudnn_cnn_infer64_8.dll. Error code 193
> 
> 换成cudnn8.2 不会


> 我遇到了相同的问题，8.3也不行
> 
> W0814 15:01:53.073433 31504 gpu_resources.cc:61] Please NOTE: device: 0, GPU Compute Capability: 8.6, Driver API Version: 11.6, Runtime API Version: 11.6 W0814 15:01:53.080451 31504 gpu_resources.cc:91] device: 0, cuDNN Version: 8.3. W0814 15:01:53.702119 31504 gpu_resources.cc:201] WARNING: device: . The installed Paddle is compiled with CUDNN 8.4, but CUDNN version in your machine is 8.3, which may cause serious incompatible bug. Please recompile or reinstall Paddle with compatible CUDNN version. Could not load library cudnn_cnn_infer64_8.dll. Error code 193


原因：
![image](https://user-images.githubusercontent.com/72233260/202045495-3ec364e4-81c2-4dc2-b943-f833dea5f01f.png)
解决办法：
![image](https://user-images.githubusercontent.com/72233260/202045528-e5c29ce2-90fd-4e4c-8199-81e3ecd975f2.png)
[文件](http://www.winimage.com/zLibDll/zlib123dllx64.zip)

不谢
