### ISSUE TITLE
Links in Paddle/READ.ME is broken 

### ISSUE THREAD

**Issue by QShiX** [PaddlePaddle/Paddle#45117]
### 文档链接&描述 Document Links & Description

The paddle inferenc link in paddle intro page (https://github.com/PaddlePaddle/Paddle) markdown is broken:
https://paddle-inference.readthedocs.io/en/latest/product_introduction/summary.html

### 请提出你的建议 Please give your suggestion

https://paddle-inference.readthedocs.io/en/master/guides/index_guides.html

**Comment by qili93** [comment]
Thanks for your reminder. The Paddle Inference has been migrated to https://www.paddlepaddle.org.cn/inference/product_introduction/inference_intro.html, and we will fix the document link issue.

**Comment by luotao1** [comment]
@QShiX 已经修复链接，感谢您的建议
