### ISSUE TITLE
数据集图片尺寸变化导致训练效果变差

### ISSUE THREAD

**Issue by leechenggg** [PaddlePaddle/Paddle#45121]
### 请提出你的问题 Please ask your question

我用paddlex-ppyolov2用自制的数据集训练目标检测模型，当图像尺寸为3042  *2048时，模型训练效果很好，迭代100轮Bbox-map为90，但是输入608*   608尺寸数据集时，MAP仅为0.5，并且随着迭代轮数的提升，map还在下降，有的loss-xy为0，想问一下这是什么原因导致的呢？下面是我图像处理的代码，因为是刚入门，对图像处理这块不是很懂，方便的话详细解释一下。或者给个参考链接，谢谢！

train_transforms = T.Compose([
    T.RandomCrop(cover_all_box=True),
    T.BatchRandomResize(
        target_sizes=[
            320, 352, 384, 416, 448, 480, 512, 544, 576, 608, 640, 672, 704,
            736, 768
        ],
        interp='RANDOM'), 
    T.Normalize(
            mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])
])

eval_transforms = T.Compose([
    T.Resize(
        target_size=640, interp='CUBIC'), T.Normalize(
            mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])
])

**Comment by qili93** [comment]
您好，

可能的原因是 PP-YOLOv2 的模型，需要的标准尺寸输入为640，608的输入resize并通过RANDOM的方式差值后的精度可能无法达到训练要求。可参考这里对于模型的介绍 https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.4/configs/ppyolo/README_cn.md 

具体原因请您这里能否提供完整的训练代码以及训练的图片数据样例用于分析，谢谢！

**Comment by leechenggg** [comment]
> 具体原因请您这里能否提供完整的训练代码以及训练的图片数据样例用于分析，谢谢！

感谢回复，项目“paddlex-ppyolov2裂纹检测”共享链接(有效期三天)：https://aistudio.baidu.com/studio/project/partial/verify/4425877/e2a119a884d84a3fa94d287252d929d5
上边是项目链接，有以上两种不同图片尺寸大小的数据集您可以看一下

**Comment by leechenggg** [comment]
我看您fork了项目，涉及数据集不方便公开，有结果的话给我回复一下，谢谢

**Comment by qili93** [comment]
hi @leechenggg 

这里已经请飞桨 PPYOLOV2 的同学帮您分析问题，请问您这里能否再发一下您的训练原始代码链接，如果数据集不方便公开，给出1-2个sample数据就可以，谢谢！

**Comment by leechenggg** [comment]
您好，链接和数据集我单独发您邮箱可以吗



---原始邮件---
发件人: "Qi ***@***.***&gt;
发送时间: 2022年8月15日(周一) 上午9:57
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [PaddlePaddle/Paddle] 数据集图片尺寸变化导致训练效果变差 (Issue #45121)




 
hi @leechenggg
 
这里已经请飞桨 PPYOLOV2 的同学帮您分析问题，请问您这里能否再发一下您的训练原始代码链接，如果数据集不方便公开，给出1-2个sample数据就可以，谢谢！

**Comment by leechenggg** [comment]
paddlex-ppyolov2训练自制数据集：https://aistudio.baidu.com/aistudio/projectdetail/4431442?sUid=1016341&shared=1&ts=1660531499673
以上是项目链接，里面有几张sample数据.

**Comment by wangxinxin08** [comment]
你的图片比较大，要检测的数据比较小，需要使用更大的尺寸进行训练和预测
