### ISSUE TITLE
运行paddle.utils.run_check()报错，但能正常使用

### ISSUE THREAD

**Issue by thgpddl** [PaddlePaddle/Paddle#45122]
### 请提出你的问题 Please ask your question

我在ubuntu20.04的conda环境中安装了paddle-gpu2.3.0+cuda10.2版本，我尝试运行paddle.utils.run_check()但是报错了：
![image](https://user-images.githubusercontent.com/48787805/184494281-ffb952a6-a30f-4426-aa49-e4f40b1fc32d.png)

但是我尝试操作tensor时，发现似乎能正常使用：
![image](https://user-images.githubusercontent.com/48787805/184494314-00a5f3ab-fd79-4676-8f2b-60c3c7b4fbcd.png)

请问paddle.utils.run_check()和直接使用之间有什么区别吗？

**Comment by qili93** [comment]
您好，

根据您这里截图提供的信息是由于您的环境中没有正确配置cudnn库导致的，Paddle对cudnn的库是通过动态加载的方式进行调用的，所以如果您在使用Paddle的过程中没有用到需要调用cudnn的算子，仍旧可以正常使用。如果您的模型或者接口调用到了需要cudnn的算子，则通过会抛出类似第一章截图中的错误。`paddle.utils.run_check()` 命令会对飞桨的一系列基础功能进行检查，所以能检查出来环境中的cudnn配置不正确的问题。

修复此问题的办法是请参考Nvidia的官网配置您环境中的cudnn库，或者直接使用飞桨的docker镜像，镜像中有正确的cuda与cudnn的配置，见 https://www.paddlepaddle.org.cn/install/quick?docurl=/documentation/docs/zh/install/docker/linux-docker.html
