### ISSUE TITLE
AttributeError: 'Ernie' object has no attribute 'context'

### ISSUE THREAD

**Issue by fagey123** [PaddlePaddle/Paddle#45125]
### 请提出你的问题 Please ask your question

出现AttributeError: 'Ernie' object has no attribute 'context'，请问是不是版本问题
![image](https://user-images.githubusercontent.com/52851872/184520787-c489db32-f9c4-4d3c-89e0-f917968b2b8c.png)

**Comment by littletomatodonkey** [comment]
你好，关于ernie的使用，建议参考这里：https://github.com/PaddlePaddle/PaddleHub/tree/release/v2.1/demo/text_matching
