### ISSUE TITLE
多机多卡运行失败请求解决

### ISSUE THREAD

**Issue by scuyjzh** [PaddlePaddle/Paddle#45129]
运行脚本：
https://github.com/PaddlePaddle/PaddleNLP/blob/develop/model_zoo/bert/run_pretrain.py

首先脚本在各自机器执行单机多卡时都正常运行，训练迭代一切正常，但是使用多机多卡就会报错。

主机执行命令：
python -m paddle.distributed.launch --ips="100.71.36.11,100.73.36.1" --gpus "1" run_pretrain.py ...
从机执行命令：
python -m paddle.distributed.launch --ips="100.71.36.11,100.73.36.1" --gpus "1" run_pretrain.py ...

两台机器都可以互ping通：
![image](https://user-images.githubusercontent.com/12816241/184562837-9e5cb82d-2ef9-4d82-a6c6-3767c7d343be.png)
![image](https://user-images.githubusercontent.com/12816241/184562879-8519b6c5-cccf-4083-a9b9-1f83e6f16cf2.png)

操作步骤：先运行从机命令，再运行主机命令
从机显示报错信息：
![image](https://user-images.githubusercontent.com/12816241/184563099-34b15e16-582e-46e5-beec-d2af1607f6d6.png)

主机一直卡在这里不动：
![image](https://user-images.githubusercontent.com/12816241/184563086-df5d715c-bb49-405a-9fe7-b042fbd64300.png)

两台机器的NCCL版本都是2.8.4，CUDA版本主机是11.2，从机11.1

**Comment by scuyjzh** [comment]
贴一下从机的log
![image](https://user-images.githubusercontent.com/12816241/184563551-8bf6e831-d8d5-4c90-b1bf-70c2aaf58f93.png)

**Comment by scuyjzh** [comment]
@tink2123

**Comment by tink2123** [comment]
与 https://github.com/PaddlePaddle/PaddleNLP/issues/3051 问题一致，已有同学跟进
