### ISSUE TITLE
训练好的模型无法下载

### ISSUE THREAD

**Issue by leechenggg** [PaddlePaddle/Paddle#45124]
### 请提出你的问题 Please ask your question

在aistudio-BML环境下训练好的一个大小为400M的模型文件，下载到一半报网络问题下载失败，但是我的网络没有问题

**Comment by qili93** [comment]
您好，很抱歉，AIStudio 或 BML 网络相关问题需要联系 AIStudio 或 BML 的技术支持协助解决，Paddle社区仅能回答飞桨使用相关问题。
