### ISSUE TITLE
关于paddle.Model的问题

### ISSUE THREAD

**Issue by psychocosine** [PaddlePaddle/Paddle#45120]
model.fit中可以传入一个DataLoader作为训练数据，但是在哪里定义了模型输入与DataLoader返回数据的关系呢，模型中的forward可能有多个参数

**Comment by qili93** [comment]
Hi,

如果您这里是使用 DataLoader 加载 `paddle.vision` 的数据集和模型，模型和数据集的输入输出都是按照`image, label`的顺序定义和使用的。

更详细的代码可参考如下信息，首先可以通过以下方法定位数据集的返回数据：

`paddle.vision` 中定义的数据集的DataLoader返回的数据有固定顺序，例如 MNIST 数据集定义可以从 `__getitem__` 的返回中找到每次返回的是 `return image.astype(self.dtype), label.astype('int64')` 两个数据，代码见 https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/vision/datasets/mnist.py#L206，同时 `paddle.vision`的数据集返回的都是 image, label

`paddle.vision` 的模型的输入也是`inputs, labels`对应数据集的`image, label`可。例如你将模型定义为`model = paddle.Model(lenet, inputs, labels)`，class Model 这里训练时调用 train_batch 
 获取 inputs 和 labels 的输入，代码见 https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/hapi/model.py#L1055。如果是动态图，则会自动调用 DynamicGraphAdapter 中的 train_batch 方法进行处理，代码见 https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/hapi/model.py#L704

如果您这里是使用自己定义的 DataLoader 和 模型，请提供相应的模型代码以便协助您定位DataLoader和模型的对应关系。
