### ISSUE TITLE
Paddle安装后无法调用GPU

### ISSUE THREAD

**Issue by sherwin-silin-chen** [PaddlePaddle/Paddle#45137]
### 问题描述 Issue Description

Conda虚拟环境一直可以使用PaddlePaddle，但是突然不能调用GPU了
程序运行后 只调用CPU
查看安装包：
![image](https://user-images.githubusercontent.com/30338877/184588817-d7886561-41bd-465c-807e-c4feeea5cb24.png)
是GPU版本；
cuda可以正常调用：
![image](https://user-images.githubusercontent.com/30338877/184588888-763376f7-f03d-48b5-ad4c-46aef2db35f6.png)
Nvidia-smi可以查看GPU使用情况
重新安装PaddlePaddle后依旧不可以调用GPU：
![image](https://user-images.githubusercontent.com/30338877/184588990-95991294-2cfa-49f1-b229-1a6703037055.png)
![image](https://user-images.githubusercontent.com/30338877/184589021-41b921ff-ee3d-401f-ab0a-adc168d42153.png)

### 版本&环境信息 Version & Environment Information

Paddle版本：2.3.1
python版本：3.7.0
cuda版本：10.2
GPU: V100

**Comment by dingjiaweiww** [comment]
你用的安装命令是？

**Comment by sherwin-silin-chen** [comment]
conda install paddlepaddle-gpu==2.3.1 cudatoolkit=10.2 --channel https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/Paddle/


> 你用的安装命令是？

conda install paddlepaddle-gpu==2.3.1 cudatoolkit=10.2 --channel https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/Paddle/

**Comment by dingjiaweiww** [comment]
你环境中可能有多个安装包
你这里打印的paddlepaddle-gpu是pypi源的，而且是2.3.0
![image](https://user-images.githubusercontent.com/23093488/184636057-2ec491d4-d120-470c-a489-00d7e9decb62.png)
但是你说用的是conda虚拟环境里的paddle，是2.3.1，你conda 里面的会不会是cpu的包呢

**Comment by sherwin-silin-chen** [comment]
> 你环境中可能有多个安装包
> 你这里打印的paddlepaddle-gpu是pypi源的，而且是2.3.0
> ![image](https://user-images.githubusercontent.com/23093488/184636057-2ec491d4-d120-470c-a489-00d7e9decb62.png)
> 但是你说用的是conda虚拟环境里的paddle，是2.3.1，你conda 里面的会不会是cpu的包呢

不好意思 这个是我之前的env 后来我新建的env用的2.3.1的命令 我之前的env没有多个paddlepaddle-gpu：
conda list 结果：
_libgcc_mutex             0.1                        main    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
_openmp_mutex             5.1                       1_gnu    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
astor                     0.8.1            py37h06a4308_0    defaults
blas                      1.0                         mkl    defaults
brotlipy                  0.7.0           py37h27cfd23_1003    defaults
ca-certificates           2022.4.26            h06a4308_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
certifi                   2022.5.18.1      py37h06a4308_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
cffi                      1.15.0           py37h7f8727e_0    defaults
charset-normalizer        2.0.4              pyhd3eb1b0_0    defaults
cryptography              37.0.1           py37h9ce1e76_0    defaults
cudatoolkit               10.2.89              hfd86e86_1    defaults
cudnn                     7.6.5                cuda10.2_0    defaults
decorator                 5.1.1              pyhd3eb1b0_0    defaults
freetype                  2.11.0               h70c0345_0    defaults
gast                      0.3.3                      py_0    defaults
giflib                    5.2.1                h7b6447c_0    defaults
idna                      3.3                pyhd3eb1b0_0    defaults
intel-openmp              2021.4.0          h06a4308_3561    defaults
jpeg                      9e                   h7f8727e_0    defaults
lcms2                     2.12                 h3be6417_0    defaults
libedit                   3.1.20210910         h7f8727e_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
libffi                    3.2.1             hf484d3e_1007    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
libgcc-ng                 11.2.0               h1234567_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
libgomp                   11.2.0               h1234567_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
libpng                    1.6.37               hbc83047_0    defaults
libprotobuf               3.20.1               h4ff587b_0    defaults
libstdcxx-ng              11.2.0               h1234567_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
libtiff                   4.2.0                h2818925_1    defaults
libwebp                   1.2.2                h55f646e_0    defaults
libwebp-base              1.2.2                h7f8727e_0    defaults
lz4-c                     1.9.3                h295c915_1    defaults
mkl                       2021.4.0           h06a4308_640    defaults
mkl-service               2.4.0            py37h7f8727e_0    defaults
mkl_fft                   1.3.1            py37hd3c417c_0    defaults
mkl_random                1.2.2            py37h51133e4_0    defaults
ncurses                   6.3                  h7f8727e_2    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
numpy                     1.21.5           py37h6c91a56_3    defaults
numpy-base                1.21.5           py37ha15fc14_3    defaults
openssl                   1.0.2u               h7b6447c_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
opt_einsum                3.3.0              pyhd3eb1b0_1    defaults
paddlepaddle-gpu          2.3.0                    pypi_0    pypi
pillow                    9.0.1            py37h22f2fdc_0    defaults
pip                       21.2.2           py37h06a4308_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
protobuf                  3.20.1           py37h295c915_0    defaults
pycparser                 2.21               pyhd3eb1b0_0    defaults
pyopenssl                 22.0.0             pyhd3eb1b0_0    defaults
pysocks                   1.7.1                    py37_1    defaults
python                    3.7.0                h6e4f718_3    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
readline                  7.0                  h7b6447c_5    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
requests                  2.27.1             pyhd3eb1b0_0    defaults
setuptools                61.2.0           py37h06a4308_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
six                       1.16.0             pyhd3eb1b0_1    defaults
sqlite                    3.33.0               h62c20be_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
tk                        8.6.12               h1ccaba5_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
urllib3                   1.26.9           py37h06a4308_0    defaults
wheel                     0.37.1             pyhd3eb1b0_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
xz                        5.2.5                h7f8727e_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
zlib                      1.2.12               h7f8727e_2    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
zstd                      1.5.2                ha4553b6_0    defaults


我后来新建的env 用conda install装paddle2.3.1 依然是如上的结果

**Comment by Tlntin** [comment]
系统？GCC版本？

**Comment by sherwin-silin-chen** [comment]
> 系统？GCC版本？

gcc version 4.8.5 20150623 (Red Hat 4.8.5-44) (GCC)

**Comment by sherwin-silin-chen** [comment]
> 系统？GCC版本？

Linux version 4.14.0_1-0-0-44 (****************) (gcc version 4.8.2 20140120 (Red Hat 4.8.2-16) (GCC)) #1 SMP Tue Sep 14 17:12:22 CST 2021

**Comment by Tlntin** [comment]
> > 系统？GCC版本？
> 
> gcc version 4.8.5 20150623 (Red Hat 4.8.5-44) (GCC)

有点老了，官方推荐是8.2。最大9.x。
可以用conda安装一下gcc8试试，这样不影响系统环境。
```bash
conda install -c conda-forge gcc=8 gxx=8 sysroot_linux-64=2.17
```

**Comment by sherwin-silin-chen** [comment]
> > > 系统？GCC版本？
> > 
> > 
> > gcc version 4.8.5 20150623 (Red Hat 4.8.5-44) (GCC)
> 
> 有点老了，官方推荐是8.2。最大9.x。 可以用conda安装一下gcc8试试，这样不影响系统环境。
> 
> ```shell
> conda install -c conda-forge gcc=8 gxx=8 sysroot_linux-64=2.17
> ```

我这台开发机其他用户的paddle都是正常的 都是gcc4.8.5的 而且我之前一直都是正常使用的。。。

**Comment by tink2123** [comment]
可以尝试清理当前环境下所有的paddle，或创建一个新的干净环境重新安装。

**Comment by sherwin-silin-chen** [comment]
清理所有env
清理anoconda
重新安装paddlepaddle
重新编译paddleseg
修复
