### ISSUE TITLE
问下inference 的多线程. 

### ISSUE THREAD

**Issue by VamWolf** [PaddlePaddle/Paddle#4513]
关于多线程预估的实现方式
1.  把demo 中dense 的预估代码，丢到多个线程里面.  
2. 按照demo 中multi_thread 的实现方法实现. 

1. 的结果，和单线程没啥区别？paddle 的某些变量是一个gradient machine 共享的导致的？
只有2 才是真的多线程？

**Comment by VamWolf** [comment]
paddle_matrix mat = paddle_matrix_create(/* sample_num */ 1,
                                           /* size */ 784,
                                           /* useGPU */ false); 

  多线程版本里面的这个意思是，把所有输入都放到一个matrix 里面？ 

  如果query1 ，query2 的pair预估.   
 CHECK(paddle_arguments_set_value(in_args, 0, mat));

 建两个mat ？

正常只要作为inarg 的两个index 的输入就好了. 还是晕了

**Comment by typhoonzero** [comment]
Closing this outdated issue, feel free to reopen.
