### ISSUE TITLE
编译好的推理界面在新环境下无法加载训练好的模型

### ISSUE THREAD

**Issue by xiaoxiangch** [PaddlePaddle/Paddle#45133]
### 请提出你的问题 Please ask your question

我按照此链接 https://github.com/PaddlePaddle/PaddleX/tree/release/2.0.0/examples/C%23_deploy ，通过调用paddle_inference.dll 和model_infer.dll ，来进行可视化推理，在我的电脑上是可以正常运行的，但是如果将生成的exe以及配套的dll重新放到一个新电脑上，是无法正常加载预训练模型的，
会提示
![2fefb7f98b8a0d86b57d1b43764ae56](https://user-images.githubusercontent.com/37433925/184582948-d7503860-e5a4-40e1-bc0c-c4d3ac4cbd63.jpg)

这种情乱是因为缺乏paddle的其他依赖吗？dll能正常在新环境下迁移使用还需要加载其他依赖吗？

**Comment by Shrinco** [comment]
> ### 请提出你的问题 Please ask your question
> 我按照此链接 https://github.com/PaddlePaddle/PaddleX/tree/release/2.0.0/examples/C%23_deploy ，通过调用paddle_inference.dll 和model_infer.dll ，来进行可视化推理，在我的电脑上是可以正常运行的，但是如果将生成的exe以及配套的dll重新放到一个新电脑上，是无法正常加载预训练模型的， 会提示 ![2fefb7f98b8a0d86b57d1b43764ae56](https://user-images.githubusercontent.com/37433925/184582948-d7503860-e5a4-40e1-bc0c-c4d3ac4cbd63.jpg)
> 
> 这种情乱是因为缺乏paddle的其他依赖吗？dll能正常在新环境下迁移使用还需要加载其他依赖吗？

应该主要就是缺依赖导致的，需要把paddle inference的dll都添加到环境变量里或者项目工程里（model_infer.dll
不会把推理需要的依赖给装进去，只是把自己的代码封装成了dll）。或者就是按照错误提示检查一下各个文件是不是都在。
