### ISSUE TITLE
import paddle Error: Can not import avx core while this file exists: ...

### ISSUE THREAD

**Issue by Firestick-Xia** [PaddlePaddle/Paddle#45146]
### 问题描述 Issue Description

根据官网教程conda安装paddle，命令行如下：conda install paddlepaddle-gpu==2.3.1 cudatoolkit=10.2 --channel https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/Paddle/
安装好后：>>> import paddle
Error: Can not import avx core while this file exists...

### 版本&环境信息 Version & Environment Information

paddlepaddle-gpu==2.3.1 cudatoolkit=10.2 python==3.9

**Comment by tink2123** [comment]
上述命令默认安装avx的包。
需要先确认是否支持avx，如果你的机器不支持avx，需要安装noavx的Paddle包，可以通过以下命令安装，仅支持python3.8。
gpu版本cuda10.1 noavx机器安装：
python -m pip download paddlepaddle-gpu==2.3.1.post101 -f https://www.paddlepaddle.org.cn/whl/linux/mkl/noavx/stable.html --no-index --no-deps

详细说明文档可参考：https://www.paddlepaddle.org.cn/documentation/docs/zh/install/pip/linux-pip.html#ruhechakannindehuanjing

**Comment by Firestick-Xia** [comment]
sudo apt install libgomp1
已解决
