### ISSUE TITLE
关闭random后，PP-TSM CPU 和 GPU loss仍不一致

### ISSUE THREAD

**Issue by HarperCy** [PaddlePaddle/Paddle#45167]
### bug描述 Describe the Bug

首先说结论，某个算子，或者多个，CPU实现与GPU实现略有不同，导致计算上有误差，而XPU算子实现时延续了这个计算，导致XPU与CPU行为一致，与GPU差很多。目前已排除momentum不同的地方的影响，请指出那些算子在CPU上与GPU上有差别。
首先，关闭random （多次执行获得同样结果，确实关闭了random）
1. dropout添加如下代码，位置如图，注释部分的代码（记得取消注释）
![image](https://user-images.githubusercontent.com/47998305/184764887-a6804629-f2c9-40cd-bd63-fc1896ec3d94.png)
2. main.py中固定seed
![image](https://user-images.githubusercontent.com/47998305/184766543-d1111e32-700c-4974-bbcc-5918ca1f22c7.png)

然后运行pptsm模型的训练，算子全跑在XPU上，精度 最终差10%，一开始的loss完全对不上，这是第一个epoch
<img width="418" alt="image" src="https://user-images.githubusercontent.com/47998305/184769396-fb859cfb-9100-4c8b-bbc2-cfd9d654b847.png">

而XPU上多次运行，loss一致，无变化，
CPU上多次运行，loss、精度一致，且loss、精度与XPU一致

<img width="900" alt="image" src="https://user-images.githubusercontent.com/47998305/184768979-a1859c6b-288f-4829-b44c-ca4ca6a5094c.png">

<img width="910" alt="image" src="https://user-images.githubusercontent.com/47998305/184768820-d5258b40-502e-46c2-af8b-2fcd185366d4.png">

**Comment by ZHUI** [comment]
您好，建议您先固定参数，单个step，对齐前向、反向精度。

**Comment by jzhang533** [comment]
固定随机种子只是会消除随机性的影响，但，GPU上的算子实现，并不是所有的算子都有 **确定性(deterministic)** 的算法实现。
只是，对于使用了CUDNN实现的算子，可以用`export FLAGS_cudnn_deterministic=True`来让CUDNN采用确定性的算法。（但会运行很慢）。
