### ISSUE TITLE
MinGW编译Paddle框架需求

### ISSUE THREAD

**Issue by yuyangup** [PaddlePaddle/Paddle#45187]
### 需求描述 Feature Description

任务目标（请描述你正在做的项目是什么，如模型、论文、项目是什么？）; <br /> 需求场景（请描述你的项目中为什么需要用此功能）;  <br /> 功能描述（请简单描述或设计这个功能）
目前由于在国产化平台上进行视觉方面的项目开发，国产系统主流开发语言是c++，开发工具是qt，微软vs那一套在国产化系统上用不了，考虑到后期咱们飞桨平台在国产化系统上的应用，强烈建议官方提供一套基于mingw编译的教程，方便国产化开发。

### 替代实现 Alternatives

本来准备用pyqt的，但是在国产化系统上，python版本比较低，而且主流应用用python的特别少，因此基本行不通

**Comment by yuyangup** [comment]
没有价值的建议

**Comment by ZHUI** [comment]
国产化系统 指的是? 是否基于类似 linux 的工具链编译会好一些？

**Comment by lifw555** [comment]
建议基于mingw-64w，使用gcc编译器，在windows上编译，方便跨平台编译。

我自行尝试使用mingw-64w，编译报错。
-- Looking for UINT64_MAX
-- Looking for UINT64_MAX - not found
-- Looking for UINT64_MAX
-- Looking for UINT64_MAX - not found
CMake Error at cmake/flags.cmake:102 (message):
Cannot find symbol UINT64_MAX
Call Stack (most recent call first):
CMakeLists.txt:233 (include)
