### ISSUE TITLE
重新编译paddleInference

### ISSUE THREAD

**Issue by SiChuanJay** [PaddlePaddle/Paddle#45182]
### 需求描述 Feature Description

任务目标（请描述你正在做的项目是什么，如模型、论文、项目是什么？）; <br /> 需求场景（请描述你的项目中为什么需要用此功能）;  <br /> 功能描述（请简单描述或设计这个功能）

你好，目前你们提供的带trt版本的paddleInference没有满足我环境要求的，我需要重新编译一下，但是我不太清楚各种参数怎么写，你们方便写一下windows下 使用vs2019编译带trt的paddleInference的命令吗？
![图片](https://user-images.githubusercontent.com/52130681/184840524-71567379-bf20-471c-b50e-b73038f9b135.png)

**Comment by yeliang2258** [comment]
可以参考这个文档：https://www.paddlepaddle.org.cn/inference/master/guides/install/compile/source_compile_under_Windows.html

**Comment by SiChuanJay** [comment]
@yeliang2258 非常感谢。

**Comment by SiChuanJay** [comment]
你好，我在使用paddleInference时，当模式为paddle-gpu的时候没问题，当模型为trt-32的时候，出现如下问题。我查找了一些资料，有可能是安装的paddle没有带trt。但是在我下载了如下的包后，仍然出现上述问题，我觉的可能是我的trt没有用起来，但是我不知道如何设置。
![图片](https://user-images.githubusercontent.com/52130681/185055180-8ca94eb9-7efb-49fe-a34b-2d9fcdd26f3e.png)
![图片](https://user-images.githubusercontent.com/52130681/185055424-049162f9-2cec-4e46-b1fc-bfdae2b14bfc.png)
