### ISSUE TITLE
使用paddle_serving_client时，无法Clinet()实例

### ISSUE THREAD

**Issue by ionescofung** [PaddlePaddle/Paddle#45197]
### 请提出你的问题 Please ask your question

使用paddle_serving_client的Client时，实例出现错误
请问如何解决？
![image](https://user-images.githubusercontent.com/55121158/184909973-61a62922-682f-4d4d-82f5-399197ff3b19.png)

![image](https://user-images.githubusercontent.com/55121158/184910063-528ae0fc-21fb-4dab-965d-4c12e1a7e6cd.png)

**Comment by HexToString** [comment]
请贴出你的完整的调用代码

**Comment by HexToString** [comment]
请检查一下，pip3.8 list 下有没有安装paddle-serving-client，大概率猜测你这个是python pip 版本安装导致的问题。
