### ISSUE TITLE
Construct backward pass in Program/BlockDesc

### ISSUE THREAD

**Issue by reyoung** [PaddlePaddle/Paddle#4521]
Currently, we have a function named `Backward` which creates C++ operator instances that compose the backward pass.  However, as we decided to separate compilation from execution, we need to make `Backward` operate the ProgramDesc, BlockDesc, and OpDesc, instead of creating the runtime representation of the backward pass.

Related PR:

* https://github.com/PaddlePaddle/Paddle/pull/4517

**Comment by wangkuiyi** [comment]
@reyoung is implementing #4517 

@Canpio port backward-pass generation algorithm from runtime to compile time.

**Comment by reyoung** [comment]
Done.
