### ISSUE TITLE
打包运行错误，paddle_infer.create_predictor(model_config)失败

### ISSUE THREAD

**Issue by Dawn-bin** [PaddlePaddle/Paddle#45228]
### 请提出你的问题 Please ask your question

用pyinstaller打包推理代码遇到的问题，打包前一切正常。

`paddle.utiles.run_check()` 显示成功。
运行到
`predictor = paddle_infer.create_predictor(model_config)`
显存发生了一点波动就抛出错误。

```
Running verify PaddlePaddle program ...
W0817 22:45:49.735289 18123 gpu_resources.cc:61] Please NOTE: device: 0, GPU Compute Capability: 7.5, Driver API Version: 11.2, Runtime API Version: 11.1
W0817 22:45:49.741020 18123 gpu_resources.cc:91] device: 0, cuDNN Version: 8.1.
PaddlePaddle works well on 1 GPU.
PaddlePaddle works well on 1 GPUs.
PaddlePaddle is installed successfully! Let's start deep learning with PaddlePaddle now.

W0817 22:45:51.311663 18123 analysis_predictor.cc:1118] The one-time configuration of analysis predictor failed, which may be due to native predictor called first and its configurations taken effect.


--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
0   paddle_infer::Predictor::Predictor(paddle::AnalysisConfig const&)
1   paddle::AnalysisPredictor::~AnalysisPredictor()
2   paddle::AnalysisPredictor::~AnalysisPredictor()
3   paddle::memory::allocation::AllocatorFacade::Release(phi::Place const&)
4   paddle::memory::allocation::AllocatorFacadePrivate::GetAllocator(phi::Place const&, unsigned long)

----------------------
Error Message Summary:
----------------------
FatalError: `Process abort signal` is detected by the operating system.
  [TimeInfo: *** Aborted at 1660747551 (unix time) try "date -d @1660747551" if you are using GNU date ***]
  [SignalInfo: *** SIGABRT (@0x3fe000046cb) received by PID 18123 (TID 0x7fe439197b80) from PID 18123 ***]
```

**Comment by joey12300** [comment]
请问您是在什么平台运行呢？有最小可复现代码吗？

**Comment by Dawn-bin** [comment]
> 请问您是在什么平台运行呢？有最小可复现代码吗？

Linux平台，代码运行正常，但pyinstaller打包后运行报错

**Comment by joey12300** [comment]
> > 请问您是在什么平台运行呢？有最小可复现代码吗？
> 
> Linux平台，代码运行正常，但pyinstaller打包后运行报错

可以尝试检查一下是否缺少某些动态链接库。也有可能是多进程环境下出现运行报错，尝试在main函数添加以下代码：

```python
import multiprocessing as mp
   
if __name__ == '__main__':
    mp.set_start_method('spawn')
```

**Comment by Dawn-bin** [comment]
> > > 请问您是在什么平台运行呢？有最小可复现代码吗？
> > 
> > 
> > Linux平台，代码运行正常，但pyinstaller打包后运行报错
> 
> 可以尝试检查一下是否缺少某些动态链接库。也有可能是多进程环境下出现运行报错，尝试在main函数添加以下代码：
> 
> ```python
> import multiprocessing as mp
>    
> if __name__ == '__main__':
>     mp.set_start_method('spawn')
> ```

多线程阻塞问题已经通过修改paddle源码解决了，动态库export到原先的conda环境也解决不了，所有这是paddle的bug吗？

**Comment by joey12300** [comment]
Paddle的动态库吗？因为耦合了pyinstaller，所以不好定位是哪里的问题

**Comment by Dawn-bin** [comment]
> Paddle的动态库吗？因为耦合了pyinstaller，所以不好定位是哪里的问题

看报错就是运行到`predictor = paddle_infer.create_predictor(model_config)`
前面的run_check() 正常，说明依赖环境应该也都正常

**Comment by Dawn-bin** [comment]
请问，paddle推理时导出的静态图，依赖于paddle库吗？也就是说如果我修改了模型结构，重新导出的文件和onnx文件一样是与代码无关的吗？

**Comment by joey12300** [comment]
还是依赖paddle的inference库的，但是与模型代码无关的

**Comment by Dawn-bin** [comment]
> 还是依赖paddle的inference库的，但是与模型代码无关的

paddle有单独打包的inference库吗？整体有点臃肿

**Comment by joey12300** [comment]
@Dawn-bin 可以在这里选择合适的包进行安装：https://www.paddlepaddle.org.cn/inference/user_guides/download_lib.html

**Comment by ZhangLe-fighting** [comment]
> > > > 请问您是在什么平台运行呢？有最小可复现代码吗？
> > > 
> > > 
> > > Linux平台，代码运行正常，但pyinstaller打包后运行报错
> > 
> > 
> > 可以尝试检查一下是否缺少某些动态链接库。也有可能是多进程环境下出现运行报错，尝试在main函数添加以下代码：
> > ```python
> > import multiprocessing as mp
> >    
> > if __name__ == '__main__':
> >     mp.set_start_method('spawn')
> > ```
> 
> 多线程阻塞问题已经通过修改paddle源码解决了，动态库export到原先的conda环境也解决不了，所有这是paddle的bug吗




我现在也遇到这个问题，请问您是怎么解决的呢？

**Comment by ZhangLe-fighting** [comment]
> @Dawn-bin 可以在这里选择合适的包进行安装：https://www.paddlepaddle.org.cn/inference/user_guides/download_lib.html

使用这个预测库，打包的时候会有同样的问题嘛

**Comment by Dawn-bin** [comment]
hi，没有解决这个问题，可以尝试其他部署方式，我最后采用了静态图推理的方式，如果需要可以把推理框架分享给你

**Comment by ZhangLe-fighting** [comment]
我需要，十分感谢！

**Comment by David-dotcom666** [comment]
> hi，没有解决这个问题，可以尝试其他部署方式，我最后采用了静态图推理的方式，如果需要可以把推理框架分享给你

你好，我现在用paddle2.4.2打包后也遇到这个问题，能请问下具体怎么解决的吗
@Dawn-bin
