### ISSUE TITLE
如何配置feed参数？

### ISSUE THREAD

**Issue by ionescofung** [PaddlePaddle/Paddle#45231]
### 请提出你的问题 Please ask your question

我使用paddleDetection export了model并且serving_client conver成能够能够部署的模型
但是该如何填写我的feed来predict？
<img width="1527" alt="image" src="https://user-images.githubusercontent.com/55121158/185286834-b8ff5f4f-33b2-42bf-9bd0-404c615a45da.png">

**Comment by ghostxsl** [comment]
可以参考文档：https://github.com/PaddlePaddle/PaddleDetection/tree/develop/deploy/serving/python
