### ISSUE TITLE
Add Executor

### ISSUE THREAD

**Issue by wangkuiyi** [PaddlePaddle/Paddle#4524]
Executor is a C++ class that takes a `ProgramDesc` and run all blocks inside or a specific block.

```C++
class Executor {
 public:
  Executor(const ProgramDesc& program, int block_id);
  void Run() = 0;
 ...
};
```

Here we need a single-thread executor that uses a specified GPU only.

**Comment by tonyyang-svail** [comment]
Original Session Design Doc: #3993
Qi Jun's prototyping: #4537

**Comment by QiJune** [comment]
There may be some points we can discuss:

- We can save our topology to `ProgramDesc`. But how the parameters are loaded and saved, or how we do checkpoint in our new framework. 
- `Executor` should run concurrently in inference with only one copy of parameters in memory. How can we implement this feature?  The Run method of `Executor` is thread-safe? or we can create several `Executor`.
- Do we need `Session`  at now? And what's the relationship of `Executor` and `Session`.

**Comment by helinwang** [comment]
Executor discussion during meeting: https://github.com/PaddlePaddle/Paddle/issues/4557

**Comment by helinwang** [comment]
> Do we need Session at now? And what's the relationship of Executor and Session.

We don't need session now, can just implement `paddle.train` and `paddle.inference`. Later we can switch the implementation into `session`.

**Comment by tonyyang-svail** [comment]
The single threaded executor has been implemented.
