### ISSUE TITLE
aarch64 如何安装paddle？

### ISSUE THREAD

**Issue by htlbayytq** [PaddlePaddle/Paddle#45245]
### 问题描述 Issue Description

尊敬的领导您好，

    我专门买了一个Nvidia Jetson NX，但安装时发现paddle官网的描述是：“安装环境需要处理器架构是x86_64。“ 

    但Nvidia Jetson NX的架构是aarch64。。。

    请问在这种情况下，我应当如何才能顺利完成paddle的安装呢？

致敬

### 版本&环境信息 Version & Environment Information

尊敬的领导您好，

    我专门买了一个Nvidia Jetson NX，但安装时发现paddle官网的描述是：“安装环境需要处理器架构是x86_64。“ 

    但Nvidia Jetson NX的架构是aarch64。。。

    请问在这种情况下，我应当如何才能顺利完成paddle的安装呢？

致敬

**Comment by ghostxsl** [comment]
可以参考这个链接下载对应的安装包：https://paddleinference.paddlepaddle.org.cn/user_guides/download_lib.html#python

**Comment by jiguanglu** [comment]
> 可以参考这个链接下载对应的安装包：https://paddleinference.paddlepaddle.org.cn/user_guides/download_lib.html#python

你好，链接已经失效。

**Comment by cailuyu** [comment]
> ### 问题描述 Issue Description
> 
> 尊敬的领导您好，
> 
> ```
> 我专门买了一个Nvidia Jetson NX，但安装时发现paddle官网的描述是：“安装环境需要处理器架构是x86_64。“ 
> 
> 但Nvidia Jetson NX的架构是aarch64。。。
> 
> 请问在这种情况下，我应当如何才能顺利完成paddle的安装呢？
> ```
> 
> 致敬
> ### 版本&环境信息 Version & Environment Information
> 
> 尊敬的领导您好，
> 
> ```
> 我专门买了一个Nvidia Jetson NX，但安装时发现paddle官网的描述是：“安装环境需要处理器架构是x86_64。“ 
> 
> 但Nvidia Jetson NX的架构是aarch64。。。
> 
> 请问在这种情况下，我应当如何才能顺利完成paddle的安装呢？
> ```
> 
> 致敬

我的Orin也正在尝试,肯定是要自己编译的,官方的包jetpack支持都太低了,:
https://paddleinference.paddlepaddle.org.cn/v2.1/user_guides/source_compile.html
官方的这个安装都能过,但默认没有python,加上python,安装都正常,但python引入paddle包的时候加载so文件失败 

https://github.com/mingquanyuan/PaddlePaddle-Jetson
这个还在试,其实步骤都一样,编译参数有些区别

**Comment by rap8** [comment]
楼主好，请问加载so文件失败解决了吗，我也遇到了相同的问题。
