### ISSUE TITLE
arm环境安装paddlepaddle，参考官网，在make编译中一直4%

### ISSUE THREAD

**Issue by leelucky666666888** [PaddlePaddle/Paddle#45242]
### 问题描述 Issue Description

源码编译安装参考网址：https://www.paddlepaddle.org.cn/documentation/docs/zh/install/compile/arm-compile.html#yuanmabianyi
卡在下边这一步：make TARGET=ARMV8 -j$(nproc)

### 版本&环境信息 Version & Environment Information

源码编译安装参考网址：https://www.paddlepaddle.org.cn/documentation/docs/zh/install/compile/arm-compile.html#yuanmabianyi
卡在下边这一步：make TARGET=ARMV8 -j$(nproc)

**Comment by ghostxsl** [comment]
猜测可能是因为在make的时候会下载一些依赖包，可能是网络不顺畅导致的，建议可以加一下代理试试呢
