### ISSUE TITLE
paddleX预训练模型怎么使用

### ISSUE THREAD

**Issue by leechenggg** [PaddlePaddle/Paddle#45267]
### 请提出你的问题 Please ask your question

您好，我在进行用paddlex进行模型训练时，总会报警告，yolo_head.yolo_output.0.weight is not in pretrained model...
然后在output文件夹里有一个pretrain文件夹，里面有模型权重文件，我想问一下这个警告的意思是什么？这个权重文件的意义是什么？还有paddlex如何使用预训练模型？
这是我的项目链接：https://aistudio.baidu.com/aistudio/projectdetail/4441826

**Comment by nemonameless** [comment]
yolo_head.yolo_output.0.weight is not in pretrained model 表明这层权重在你加载的预训练权重里没有。
pretrain文件里放的是下载的预训练模型参数。
paddlex使用预训练模型，在train()函数的接口里面指定pretrain_weights=本地下载好的权重路径或下载链接 即可，具体可以看下 https://github.com/PaddlePaddle/PaddleX/blob/develop/docs/apis/models/detection.md#train 
代码在：https://github.com/PaddlePaddle/PaddleX/blob/develop/paddlex/cv/models/detector.py#L196
