### ISSUE TITLE
 could not determine kind of name for C.PD_ConfigEnableVarseqlen

### ISSUE THREAD

**Issue by zhenzi0322** [PaddlePaddle/Paddle#45272]
### bug描述 Describe the Bug

我在单测时出现` could not determine kind of name for C.PD_ConfigEnableVarseqlen`的问题。

https://paddle-inference.readthedocs.io/en/latest/guides/quick_start/go_demo.html#id1

### 其他补充信息 Additional Supplementary Information

https://paddle-inference.readthedocs.io/en/latest/guides/quick_start/go_demo.html#id1

```
root@c6251668451d:/go/pkg/mod/github.com/paddlepaddle/paddle/paddle/fluid/inference/goapi@v0.0.0-20220819062145-b68f1120fcbd# bash test.sh 
# github.com/paddlepaddle/paddle/paddle/fluid/inference/goapi
./config.go:504:2: could not determine kind of name for C.PD_ConfigEnableVarseqlen
FAIL    github.com/paddlepaddle/paddle/paddle/fluid/inference/goapi [build failed]
FAIL
```

**Comment by nemonameless** [comment]
https://github.com/PaddlePaddle/Paddle/issues/45271  同一问题

**Comment by jiweibo** [comment]
您好，看起来问题是该接口目前尽在develop可用，但库的版本是2.3，导致该问题。
https://github.com/PaddlePaddle/Paddle/blob/v2.3.2/paddle/fluid/inference/capi_exp/pd_config.h#L37

您将代码切换到2.3分支，重新测试应该就可以了

**Comment by zhenzi0322** [comment]
> 您好，看起来问题是该接口目前尽在develop可用，但库的版本是2.3，导致该问题。 https://github.com/PaddlePaddle/Paddle/blob/v2.3.2/paddle/fluid/inference/capi_exp/pd_config.h#L37
> 
> 您将代码切换到2.3分支，重新测试应该就可以了

好的
