### ISSUE TITLE
能否直接调用检测或分割模型？

### ISSUE THREAD

**Issue by lao-xu** [PaddlePaddle/Paddle#45295]
### 请提出你的问题 Please ask your question

飞桨能否像pytorch一样直接调用各种应用模型，这样更加方便，而不是必须使用套件。比如像
model = torchvision.models.detection.fasterrcnn_resnet50_
model = torchvision.models.segmentation.fcn_

**Comment by minghaoBD** [comment]
> ### 请提出你的问题 Please ask your question
> 飞桨能否像pytorch一样直接调用各种应用模型，这样更加方便，而不是必须使用套件。比如像 model = torchvision.models.detection.fasterrcnn_resnet50_ model = torchvision.models.segmentation.fcn_

有的，对应torchvision的话，可以参考paddle.visions.models.${model_name} 查看
${model_name}列表查看方式：

```python
import paddle
dir(paddle.vision.models)
```

**Comment by minghaoBD** [comment]
> ### 请提出你的问题 Please ask your question
> 飞桨能否像pytorch一样直接调用各种应用模型，这样更加方便，而不是必须使用套件。比如像 model = torchvision.models.detection.fasterrcnn_resnet50_ model = torchvision.models.segmentation.fcn_

有的，可以通过调用paddle.vision.models.${model_name} 使用。

${model_name}列表：
```python
import paddle
dir(paddle.vision.models)
```

**Comment by minghaoBD** [comment]
看了下，里面以分类模型为主。直接调用检测模型的话还是需要依赖于套件。

**Comment by lao-xu** [comment]
> ```python
> import paddle
> dir(paddle.vision.models)
> ```
建议把尽量多模型都加进去，方便使用、学习以及教学，否则学习门槛太高，不利于推广使用。
比如现有的pytorch参考书都有分割、检测、机器翻译等章节，直接调用模型就行，但飞桨参考书就不太方便列进去

**Comment by lao-xu** [comment]
> 

建议把尽量多模型都加进去，方便使用、学习以及教学，否则学习门槛太高，不利于推广使用。
比如现有的pytorch参考书都有分割、检测、机器翻译等章节，直接调用模型就行，但飞桨参考书就不太方便列进去

**Comment by lao-xu** [comment]
> 看了下，里面以分类模型为主。直接调用检测模型的话还是需要依赖于套件。

建议把尽量多模型都加进去，方便使用、学习以及教学，否则学习门槛太高，不利于推广使用。
比如现有的pytorch参考书都有分割、检测、机器翻译等章节，直接调用模型就行，但飞桨参考书就不太方便列进去

**Comment by minghaoBD** [comment]
好的，谢谢您的宝贵建议。

**Comment by jzhang533** [comment]
you can try [paddle.hub](https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/hub/Overview_cn.html)
