### ISSUE TITLE
KeyError: 'token_type_ids'

### ISSUE THREAD

**Issue by zhangCollab** [PaddlePaddle/Paddle#45294]
### 请提出你的问题 Please ask your question

![捕获](https://user-images.githubusercontent.com/111550104/185832514-7cf1ee85-572d-4dbf-a63f-808ef158ee54.PNG)
在ubuntu18.4下，cuda11.6，运行python tools/infer_vqa_token_ser.py -c configs/vqa/ser/layoutxlm.yml -o Architecture.Backbone.checkpoints=inference/ser_LayoutXLM_xfun_zh/ Global.infer_img=images/images_0.png
报错，是怎么回事啊

**Comment by minghaoBD** [comment]
您好，请问这是哪个模型套件的repo呢？

**Comment by zhangCollab** [comment]
![捕获](https://user-images.githubusercontent.com/111550104/185833586-1ba30e5e-cae0-458a-af6d-259ae2c6c174.PNG)
我是使用VQA文档视觉问答的ser

**Comment by minghaoBD** [comment]
> ![捕获](https://user-images.githubusercontent.com/111550104/185833586-1ba30e5e-cae0-458a-af6d-259ae2c6c174.PNG) 我是使用VQA文档视觉问答的ser

可以分享一个文档链接吗？我联系对应的负责人来帮忙看下。

**Comment by zhangCollab** [comment]
好的，https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.5/ppstructure/vqa/README.md

**Comment by minghaoBD** [comment]
哦哦，ocr的问题推荐去ocr的repo直接问哈～ https://github.com/PaddlePaddle/PaddleOCR/issues

**Comment by zhangCollab** [comment]
好的
