### ISSUE TITLE
where is this  API   "set_num_threads" used?  

### ISSUE THREAD

**Issue by OccupyMars2030** [PaddlePaddle/Paddle#45298]
### 请提出你的问题 Please ask your question

In this  file  Paddle\paddle\fluid\pybind\pybind.cc,   the  python  module  core_avx or  core_noavx is  created   and  the  python  function  "set_num_threads"  is  bound  to  this  module  as  the  following   code  shows:
<img width="960" alt="image" src="https://user-images.githubusercontent.com/31559413/185848914-138eb786-dc74-410e-9236-0aedd4b56ce6.png">
but  I   cannot  find  where  this  function  is  used.  In  my  opinion,   this function  will   be  used  like  the following:
paddle.fluid.core_avx.set_num_threads(3)

So,  where is this  API  "set_num_threads"   used ???

**Comment by minghaoBD** [comment]
Please follow this way for reference. 

>>> paddle.fluid.core.set_num_threads
<built-in method set_num_threads of PyCapsule object at 0x7f86f9f1b7b0>

**Comment by OccupyMars2030** [comment]
Thank you!
