### ISSUE TITLE
【aistudio脚本任务 日志打印、下载输出】

### ISSUE THREAD

**Issue by jiaohuix** [PaddlePaddle/Paddle#45297]
### 问题描述 Please describe your issue

最近跑aistudio的脚本任务时，发现日志信息不能实时输出，基本上等到运行结束才显示，这是bug嘛？  还有就是下载输出20g，实际上我两三个g也保存失败了，为什么呢？
求大佬解惑。
![138f95ef815db236e323fc9dede6b28](https://user-images.githubusercontent.com/68314259/185840469-ca90e5a5-e629-4663-b630-db2dc912390e.png)
![SKL0ICH)_GZ@BC4U24MQ~T2](https://user-images.githubusercontent.com/68314259/185840470-7682dc68-77df-4f1f-9229-fdf08d8c6861.png)
一共是5个ckpt，每个只有400m，还是下载失败了orz。。。
![AY9%5)D0N`U~A(1WETEYN(V](https://user-images.githubusercontent.com/68314259/185840494-b00dcf32-fc9c-44e6-b908-add0a5d0e158.png)

**Comment by minghaoBD** [comment]
您好，方便提供一个可复现的ai-studio链接吗？

**Comment by MiuGod0126** [comment]
> 您好，方便提供一个可复现的ai-studio链接吗？
大佬好，方便私发您邮箱吗？

**Comment by jiaohuix** [comment]
> 您好，方便提供一个可复现的ai-studio链接吗？

我再整理下

**Comment by jiaohuix** [comment]
> 您好，方便提供一个可复现的ai-studio链接吗？

https://aistudio.baidu.com/studio/project/partial/verify/4453654/833599e27735431290ddcf172189e134

您好，这个demo大概run下8分钟，50轮保存6个ckpt，每个是1.1g，最后查看了下output目录也是6个。但是最后结果是19g，多加一个就满了。
![5TP$CM24J10F{%7VKX S6BW](https://user-images.githubusercontent.com/68314259/185862609-4331cfe1-46ec-4e9b-afbf-0d9adbf81e91.png)
![~ U$M}Z4CQK5@_ME$)P4A}B](https://user-images.githubusercontent.com/68314259/185864106-b36e2b49-c25a-4a4a-bec4-821ffaf90e99.png)

 我在训练时会保留5个最好的权重，超过5个会用shutile.rmtree删除最差的，之前单卡或多卡都没出现过问题，现在虽然也保留了5个，但貌似没有清理干净？？（在utils里）
![`I@RT5JXZL503RKK~AZBC`W](https://user-images.githubusercontent.com/68314259/185863054-a6c43b06-17a7-4963-a681-e7560a134dba.png)
训练时处理每一轮无论是不是验证bleu最高，我都会先保存下来，然后淘汰最低分数的ckpt，因为demo数据较少，所以分数加上了step_id，这样每轮都有分数更高的ckpt。（train.py里）
![85 R4@}_CR`@0NH{`CB(O69](https://user-images.githubusercontent.com/68314259/185863889-d64bee70-76af-44c8-a0a7-a0e7075ce6c4.png)

**Comment by jiaohuix** [comment]
![52751335434e949c55abe7236a066c3](https://user-images.githubusercontent.com/68314259/185864594-9ba449e4-4a9e-48f7-82ee-36f1c106f9ac.png)
每个ckpt文件夹大小

**Comment by jiaohuix** [comment]
> 您好，方便提供一个可复现的ai-studio链接吗？

您好，有时间帮我看下嘛？确实想不到啥问题orz，除了脚本任务，其他时候都挺正常的。 workspace/output下每写入一个文件都会被拷贝到什么地方么？ 否则我最后下载的输出怎么是所有的model_best额。
![{}%3Z85ILPKT8QWE3P(E$X](https://user-images.githubusercontent.com/68314259/185878249-7ad9d2ef-f031-41ec-b7c3-db8232372bf3.png)
.

**Comment by minghaoBD** [comment]
> > 您好，方便提供一个可复现的ai-studio链接吗？
> 
> 您好，有时间帮我看下嘛？确实想不到啥问题orz，除了脚本任务，其他时候都挺正常的。 workspace/output下每写入一个文件都会被拷贝到什么地方么？ 否则我最后下载的输出怎么是所有的model_best额。 ![{}%3Z85ILPKT8QWE3P(E$X](https://user-images.githubusercontent.com/68314259/185878249-7ad9d2ef-f031-41ec-b7c3-db8232372bf3.png) .

看了下save-model方法，逻辑上应该没有问题。
1. 可以加入print那行debug确认下是否那些被删除的model真的都被删除了吗？
2. 我这边ai-studio没算力了，给你拉下相关负责同学看下是否是删除失败的问题。
3. 不过我比较奇怪，如果每个文件夹都是1.1G的话，那应该保存了51个，已经远大于20GB了，确定每个文件夹中都有文件么？

```python
        if len(best_names)>nbest:
            print("removing: {}".format(os.path.join(base_dir, best_names[0])))
            shutil.rmtree(os.path.join(base_dir,best_names[0]))
            print(os.path.exists(os.path.join(base_dir,best_names[0])))
```

**Comment by jiaohuix** [comment]
> > 您好，方便提供一个可复现的ai-studio链接吗？
> 
> https://aistudio.baidu.com/studio/project/partial/verify/4453654/833599e27735431290ddcf172189e134
> 
> 您好，这个demo大概run下8分钟，50轮保存6个ckpt，每个是1.1g，最后查看了下output目录也是6个。但是最后结果是19g，多加一个就满了。 ![5TP$CM24J10F{%7VKX S6BW](https://user-images.githubusercontent.com/68314259/185862609-4331cfe1-46ec-4e9b-afbf-0d9adbf81e91.png) ![~ U$M}Z4CQK5@_ME$)P4A}B](https://user-images.githubusercontent.com/68314259/185864106-b36e2b49-c25a-4a4a-bec4-821ffaf90e99.png)
> 
> 我在训练时会保留5个最好的权重，超过5个会用shutile.rmtree删除最差的，之前单卡或多卡都没出现过问题，现在虽然也保留了5个，但貌似没有清理干净？？（在utils里） ![I@RT5JXZL503RKK~AZBCW](https://user-images.githubusercontent.com/68314259/185863054-a6c43b06-17a7-4963-a681-e7560a134dba.png) 训练时处理每一轮无论是不是验证bleu最高，我都会先保存下来，然后淘汰最低分数的ckpt，因为demo数据较少，所以分数加上了step_id，这样每轮都有分数更高的ckpt。（train.py里） ![85 R4@}_CR@0NH{CB(O69](https://user-images.githubusercontent.com/68314259/185863889-d64bee70-76af-44c8-a0a7-a0e7075ce6c4.png)

###### 目前 #####
√1事实上的确是workspace/output目录的保存规则出现了变化，我先把文件输出到临时目录code/x/output，在临时目录增删，最后再统一拷贝到workspace/output就解决了。。。（以前workspace/output是等到最后才打包里面内容）
![J~9MOCZAR~G3MSJI}1QJ4MS](https://user-images.githubusercontent.com/68314259/185885857-cbfcd31b-7b8a-44fc-b4d1-f0648dba7a17.png)

![image](https://user-images.githubusercontent.com/68314259/185884615-dac0f8c3-0da9-4a0a-afd8-3e03d6e77e54.png)

？2.日志问题还是在训练时不显示，这样只能通过估计了解进度，对于训练几天的模型有些不友好额orz

**Comment by minghaoBD** [comment]
好的，那看来是aistudio这边对于output目录的保存规则有问题。麻烦先这样绕过吧，我这边拉对应的同学修复下。

**Comment by jiaohuix** [comment]
> ```python
> path
> ```

ckpt里的优化器的参数（699m）似乎没有完整保存下来。。
![LG$N42(D_GFBX{ N_H8_ BA](https://user-images.githubusercontent.com/68314259/185887477-2529ad8b-9bdb-4a3a-b42f-9b7a8a021659.png)

**Comment by jiaohuix** [comment]
> 的

大佬，还有日志！训练时候加载不出了现在，除非报错或结束才显示出来。虽然不看日志能节省很多时间，但少了很大的乐趣阿。
![138f95ef815db236e323fc9dede6b28](https://user-images.githubusercontent.com/68314259/185887807-bc7b5f5f-4b75-4b8c-a8c9-14c736f31b2b.png)

**Comment by minghaoBD** [comment]
看起来现在的问题都和aistudio平台相关。建议去aistudio的官方渠道反馈下哈，他们比较在行。

流程：https://aistudio.baidu.com/aistudio/index
![image](https://user-images.githubusercontent.com/79566150/185889381-85809728-2bb3-4e58-9f99-28f74f45ade5.png)

**Comment by jiaohuix** [comment]
> 看起来现在的问题都和aistudio平台相关。建议去aistudio的官方渠道反馈下哈，他们比较在行。
> 
> 流程：https://aistudio.baidu.com/aistudio/index ![image](https://user-images.githubusercontent.com/79566150/185889381-85809728-2bb3-4e58-9f99-28f74f45ade5.png)

哦哦好的,谢谢！
