### ISSUE TITLE
 numpy.ndarray has the wrong size, try recompiling. Expected 80, got 96

### ISSUE THREAD

**Issue by LLsmile** [PaddlePaddle/Paddle#45302]
### 问题描述 Issue Description

安装paddlepaddle2.2.2的时候，运行报错：
 numpy.ndarray has the wrong size, try recompiling. Expected 80, got 96
查阅资料发现是numpy编译版本和使用版本不一致，但是安装的是paddle支持的1.19.3，应该没啥问题吧，其他低版本安装一直不成功。

之所以使用2.2.2版本是因为2.3.2版本使用paddledetection的时候报[cuda错误](https://github.com/PaddlePaddle/PaddleDetection/issues/6673)，然后有人说用2.2.2版本没有这个问题，就尝试了一下，结果还是有问题。

### 版本&环境信息 Version & Environment Information

paddle version: 2.2.2 with cuda
cuda: 11.6
cudnn: 8.4
os: win10

**Comment by minghaoBD** [comment]
pip install --upgrade numpy
可以尝试更新下版本吗？

**Comment by LLsmile** [comment]
> pip install --upgrade numpy 可以尝试更新下版本吗？

强制升级到1.21可以了，谢谢

**Comment by LLsmile** [comment]
那我这边跑的结果就是2.3.2有bug，2.2.2版本没问题了

**Comment by nemonameless** [comment]
这个问题就是numpy版本太低，换到numpy 1.21.6就行。和paddle版本没关系，paddle2.3.2也能顺利训练运行。
