### ISSUE TITLE
python，inference不进行重新编译是否可以正常输出结果。

### ISSUE THREAD

**Issue by tengtengzhou** [PaddlePaddle/Paddle#45301]
### 请提出你的问题 Please ask your question

python3.7.0 paddlepaddle-gpu2.0.0.rc1 使用该版本是因为wenxin模型要求该版本号。
部署好inference_server后，一进行post操作，log中就会打出
```
W0822 15:17:56.048350 127379 api_impl.cc:140] The NaiveExecutor can not work properly if the cmake flag ON_INFER is not set.
W0822 15:17:56.048424 127379 api_impl.cc:142] Unlike the training phase, all the scopes and variables will be reused to save the allocation overhead.
W0822 15:17:56.048436 127379 api_impl.cc:145] Please re-compile the inference library by setting the cmake flag ON_INFER=ON if you are running Paddle Inference
```
这样是否会影响预测结果？
如果会影响的话，
在[paddle](https://paddleinference.paddlepaddle.org.cn/v2.0/user_guides/source_compile.html)中看到inference库需要重新编译，未看到针对python的版本。想问下是需要改python中的inference库嘛？

**Comment by minghaoBD** [comment]
您好，这个报错说明当前paddle不是用作推理的。直接pip安装可以参考这里（v2.3）：https://www.paddlepaddle.org.cn/inference/v2.3/user_guides/download_lib.html#python

哪个ERNIE模型需要2.0版本的paddle呢？最新版本的paddle也都是支持ERNIE的，性能也更优秀。

**Comment by tengtengzhou** [comment]
> 您好，这个报错说明当前paddle不是用作推理的。直接pip安装可以参考这里（v2.3）：https://www.paddlepaddle.org.cn/inference/v2.3/user_guides/download_lib.html#python
> 
> 哪个ERNIE模型需要2.0版本的paddle呢？最新版本的paddle也都是支持ERNIE的，性能也更优秀。

因为之前有团队做了某个英文的模型，然后是基于wenxin1.8做的，我们想复用直接上线，所以只能用了paddlepaddle-gpu2.0.0rc1。模型我看config文件就是简单的text_classification 0-1模型。
paddlepaddle-gpu2.0.0rc1是没法进行推断的嘛？有没有相关的推断方法？
或者，是不是能将这个旧的模型文件用新版paddlepaddle-gpu读取？

**Comment by minghaoBD** [comment]
哦哦，可以参考以下链接，寻找适合的paddle-infer推理库。
2.0版本：https://www.paddlepaddle.org.cn/inference/v2.0/user_guides/download_lib.html
1.8版本：https://www.paddlepaddle.org.cn/inference/v1.8/user_guides/download_lib.html

也可以尝试下最新版本的推理库（https://www.paddlepaddle.org.cn/inference/v2.3/user_guides/download_lib.html#python），可能会由于保存推理模型的paddle版本（1.8）和推理库的paddle版本（2.3）相差较大，遇到错误。

**Comment by minghaoBD** [comment]
哦哦，可以参考以下链接，寻找适合的paddle-infer推理库。
2.0版本：https://www.paddlepaddle.org.cn/inference/v2.0/user_guides/download_lib.html
1.8版本：https://www.paddlepaddle.org.cn/inference/v1.8/user_guides/download_lib.html

也可以尝试下最新版本的推理库（ https://www.paddlepaddle.org.cn/inference/v2.3/user_guides/download_lib.html#python ）。但是优先建议1.8和2.0版本

**Comment by tengtengzhou** [comment]
> 哦哦，可以参考以下链接，寻找适合的paddle-infer推理库。 2.0版本：https://www.paddlepaddle.org.cn/inference/v2.0/user_guides/download_lib.html 1.8版本：https://www.paddlepaddle.org.cn/inference/v1.8/user_guides/download_lib.html
> 
> 也可以尝试下最新版本的推理库（ https://www.paddlepaddle.org.cn/inference/v2.3/user_guides/download_lib.html#python ）。但是优先建议1.8和2.0版本

这个paddleinfer库我下过了，完全不清楚应该怎么放到Python里。他是解压后直接放到site-packages里嘛？还是要放到paddlepaddle-gpu和paddle的文件夹里？

**Comment by minghaoBD** [comment]
> > 哦哦，可以参考以下链接，寻找适合的paddle-infer推理库。 2.0版本：https://www.paddlepaddle.org.cn/inference/v2.0/user_guides/download_lib.html 1.8版本：https://www.paddlepaddle.org.cn/inference/v1.8/user_guides/download_lib.html
> > 也可以尝试下最新版本的推理库（ https://www.paddlepaddle.org.cn/inference/v2.3/user_guides/download_lib.html#python ）。但是优先建议1.8和2.0版本
> 
> 这个paddleinfer库我下过了，完全不清楚应该怎么放到Python里。他是解压后直接放到site-packages里嘛？还是要放到paddlepaddle-gpu和paddle的文件夹里？

如何使用（ https://www.paddlepaddle.org.cn/inference/v1.8/quick_start/workflow.html ）：
![image](https://user-images.githubusercontent.com/79566150/185878553-51646933-a574-44da-b9d0-3e8e07140a97.png)

现状：2.0的paddle没有找到python用的whl包。

办法：可以尝试1.8和2.1版本的whl包：
1.8: https://www.paddlepaddle.org.cn/inference/v1.8/user_guides/download_lib.html#python
2.1: https://www.paddlepaddle.org.cn/inference/v2.1/user_guides/download_lib.html#python

**Comment by tengtengzhou** [comment]
> > > 哦哦，可以参考以下链接，寻找适合的paddle-infer推理库。 2.0版本：https://www.paddlepaddle.org.cn/inference/v2.0/user_guides/download_lib.html 1.8版本：https://www.paddlepaddle.org.cn/inference/v1.8/user_guides/download_lib.html
> > > 也可以尝试下最新版本的推理库（ https://www.paddlepaddle.org.cn/inference/v2.3/user_guides/download_lib.html#python ）。但是优先建议1.8和2.0版本
> > 
> > 
> > 这个paddleinfer库我下过了，完全不清楚应该怎么放到Python里。他是解压后直接放到site-packages里嘛？还是要放到paddlepaddle-gpu和paddle的文件夹里？
> 
> 如何使用（ https://www.paddlepaddle.org.cn/inference/v1.8/quick_start/workflow.html ）： ![image](https://user-images.githubusercontent.com/79566150/185878553-51646933-a574-44da-b9d0-3e8e07140a97.png)
> 
> 现状：2.0的paddle没有找到python用的whl包。
> 
> 办法：可以尝试1.8和2.1版本的whl包： 1.8: https://www.paddlepaddle.org.cn/inference/v1.8/user_guides/download_lib.html#python 2.1: https://www.paddlepaddle.org.cn/inference/v2.1/user_guides/download_lib.html#python

感谢，已用2.1的whl包完成部署
