### ISSUE TITLE
paddle.jit.to_static，如何保持numpy数组参数。

### ISSUE THREAD

**Issue by wykkyle** [PaddlePaddle/Paddle#45311]
### 请提出你的问题 Please ask your question

paddle.jit.to_static修饰会自动将numpy数组参数转化为variable参数。

**Comment by wykkyle** [comment]
但是该参数需要在cpu上使用（就是mask-rcnn里的多边形轮廓），怎样指示参数保持数组形式。
具体现象：
![image](https://user-images.githubusercontent.com/20754685/185916734-05049f8d-39c9-40f1-bb6a-1b3bfd1c7490.png)

**Comment by minghaoBD** [comment]
您好，我没有充分理解您的问题。
请问转成variable，对于在 mask-rcnn 里面的使用有什么具体问题吗？

**Comment by wykkyle** [comment]
大概在这个位置。
![image](https://user-images.githubusercontent.com/20754685/186043582-5dc8d865-af6f-42ea-b3d5-8d1d8f4ebbdf.png)
计算掩码损失的时候，需要将标注从多边形转换为掩码。

**Comment by wykkyle** [comment]
这个步骤需要在cpu上运算。所以希望不要将数据送入cpu。（paddledetection里的做法是将numpy数组解开为二级python列表......有没什么办法保持numpy数组)。
（上一张截图链接：https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.4/ppdet/modeling/proposal_generator/target.py）
（以python列表的形式传参：https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.4/ppdet/data/source/coco.py）

**Comment by minghaoBD** [comment]
了解。暂时没想到其他方式，可以先根据ppdet的做法来。
如果有什么问题欢迎再讨论～

**Comment by wykkyle** [comment]
好的，多谢。
