### ISSUE TITLE
cosine_similarity，OSError: (External) CUDA error(700), an illegal memory access was encountered

### ISSUE THREAD

**Issue by zhangyimi** [PaddlePaddle/Paddle#45324]
### bug描述 Describe the Bug

调用cosine_similarity发现会报`CUDA error(700), an illegal memory access was encountered`。
分析后发现，当输入维度过大时会稳定复现。
<img width="1283" alt="image" src="https://user-images.githubusercontent.com/20926735/186057884-8fd20f90-3757-4196-b58e-001067af2f0c.png">

**Comment by littletomatodonkey** [comment]
你好，看着是计算过程中显存不足了，可以提供下inputs_a与inputs_b的npy文件吗？我这边测试下
