### ISSUE TITLE
assign op

### ISSUE THREAD

**Issue by peiwenYe** [PaddlePaddle/Paddle#45345]
### 请提出你的问题 Please ask your question

请问为啥assign这个op可以没有输入？

**Comment by lyuwenyu** [comment]
API层面是不可以的吧  参考这个文档https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/assign_cn.html#assign

**Comment by peiwenYe** [comment]
> API层面是不可以的吧 参考这个文档https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/assign_cn.html#assign

是的，我使用api无输入时会报错，想请问无输入且不报错的写法应该是这样的
