### ISSUE TITLE
请问什么时候推出支持 cuda11.6 相关的 paddle inference 推理库？ 

### ISSUE THREAD

**Issue by Shrinco** [PaddlePaddle/Paddle#45369]
### 请提出你的问题 Please ask your question

请问什么时候推出支持 cuda11.6 相关的 paddle inference 推理库？ 好像目前最高只支持 cuda11.2
![image](https://user-images.githubusercontent.com/50402380/186323077-4a60d181-8145-44dd-80a6-bf04d5dfa40a.png)

**Comment by xiaoxiaohehe001** [comment]
cuda11.6的推理库已经在编译阶段了，近期就会发布

**Comment by Shrinco** [comment]
> cuda11.6的推理库已经在编译阶段了，近期就会发布

好的 谢谢

**Comment by zly19540609** [comment]
![image](https://user-images.githubusercontent.com/31341706/186352154-60a1f995-ba17-4aa2-a8f2-e0b1eae88a03.png)
https://paddleinference.paddlepaddle.org.cn/user_guides/download_lib.html#windows
已经有cuda11.6的推理库了

**Comment by Shrinco** [comment]
@zly19540609 好的 谢谢
