### ISSUE TITLE
【动态图转静态图】对__init__函数中创造的tensor进行slice的时候不报错退出。

### ISSUE THREAD

**Issue by wykkyle** [PaddlePaddle/Paddle#45374]
### 请提出你的问题 Please ask your question

![image](https://user-images.githubusercontent.com/20754685/186328335-6f0ea928-4317-4e5e-a732-09199acbde7b.png)
在__init__函数中生成一个tensor。
在forward函数中进行slice操作。
不报错退出了。（windows下不报错，linux下报内存访问违规）。

**Comment by wykkyle** [comment]
猜测是tensor放在list中的问题。但是确实需要多个张量（mrcnn中的锚框）。有什么好办法吗。

**Comment by zh794390558** [comment]
可以用 tensorarray 试试。正常对一个tensor做slice是可以的。
也可以试试https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/nn/LayerList_cn.html#layerlist
或者 tensor([20, 10, 10]) 这种的做slice

**Comment by wykkyle** [comment]
> 可以用 tensorarray 试试。正常对一个tensor做slice是可以的。 也可以试试https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/nn/LayerList_cn.html#layerlist 或者 tensor([20, 10, 10]) 这种的做slice

好方法。用一个nnLayer包裹tensor。本来是Tensor的List，包裹后变成nnLayer的List，就可以通过动静转换了。
![image](https://user-images.githubusercontent.com/20754685/186383290-708ef3ef-2e1e-4b7d-bab0-d9ac7421c8f6.png)
多谢。

总归有点别扭...又试了下register_buffer，不起作用。
