### ISSUE TITLE
Unreachable url in the official user manual

### ISSUE THREAD

**Issue by KevinFTD** [PaddlePaddle/Paddle#4540]
on the page 'HOW TO >  Run Distributed Training', there is one url unreachable.

It is in the 'Prepare Job Workspace' section:
Following steps are based on demo/recommendation demo in demo directory.

the 'demo/recommendation' links to 'https://github.com/PaddlePaddle/Paddle/tree/develop/demo/recommendation' which is already unreachable.

could someone fix it?

**Comment by luotao1** [comment]
This file has been rewritten already, the newest one is in http://www.paddlepaddle.org/docs/develop/documentation/en/howto/cluster/preparations_en.html.
