### ISSUE TITLE
paddle1.6安装检查ok但运行报错cudnn问题

### ISSUE THREAD

**Issue by topxxuki** [PaddlePaddle/Paddle#45405]
### 请提出你的问题 Please ask your question

paddle版本
<img width="411" alt="image" src="https://user-images.githubusercontent.com/18697846/186571761-2eaedc97-a9ea-4055-a3c5-c9e992a1abc4.png">
安装检查
![53ede6f2f48eb4ba55a1d338b87fcbf3](https://user-images.githubusercontent.com/18697846/186571776-e1e0ab5f-ee61-4230-9990-9043485a6b0a.jpg)
报错信息
![e4181de6325470566eacec039ddea346](https://user-images.githubusercontent.com/18697846/186571795-ef130cdb-6d7b-45da-86b5-6eaea434e787.jpg)
![0c66319c723929913954da026996b022](https://user-images.githubusercontent.com/18697846/186571804-911bb172-99a4-4f35-9dcc-a0c6d7fcdb8b.jpg)

机器信息 V100 32G
![c94a9e0df3c1719c12b3b790d2a726de](https://user-images.githubusercontent.com/18697846/186571828-09191d42-8c43-4985-aa54-efa8c39b5b3b.jpg)

**Comment by topxxuki** [comment]
补充：
成功的日志
![image](https://user-images.githubusercontent.com/18697846/186605436-c5c02488-2085-455f-83e5-749e9ff270bf.png)

![image](https://user-images.githubusercontent.com/18697846/186605156-91a46ead-fdf7-4710-91e5-535f0b1d2727.png)
失败的日志
![image](https://user-images.githubusercontent.com/18697846/186605414-acbf61a7-fa8f-4295-87de-0ecb93bd9472.png)

![image](https://user-images.githubusercontent.com/18697846/186605254-46fbc31e-c1c3-426e-893a-ce1c9dad486d.png)
cuda版本和GPU卡均一致

**Comment by zhiboniu** [comment]
如在群里沟通，问题是因为pinmemory资源不够用了。且以前可以跑，后来跑过其他程序后就跑不通了，需要先确认其他程序的资源是否已经归还了。

**Comment by topxxuki** [comment]
重新执行报错如下：
![image](https://user-images.githubusercontent.com/18697846/186625497-e1c50b53-68bd-4281-b696-d3ad418956a8.png)
![image](https://user-images.githubusercontent.com/18697846/186625974-9302f484-74ef-49d5-9118-61e4468efd66.png)
