### ISSUE TITLE
两个相同的数相除结果不为1

### ISSUE THREAD

**Issue by Zth9730** [PaddlePaddle/Paddle#45422]
### bug描述 Describe the Bug

```python3
import paddle
test = paddle.to_tensor(259280)
print(test / 259280)  # 结果为0.99999994

```
如果换成259281，结果为1
是什么原因导致？

**Comment by zhiboniu** [comment]
应该是1/259280计算时有精度损失的原因。

**Comment by zhiboniu** [comment]
看起来是1./259280.做数据转换时导致了精度损失，numpy也有这个问题，可以看看下面的示例

np.float32(259280.)*np.float32(1/259280.)

 float(np.float32(1./259280.))==1./259280

**Comment by Zth9730** [comment]
但是pytorch/numpy直接做 259280/259280结果为1
而paddle结果却不对

**Comment by zhiboniu** [comment]
有具体的测试代码吗？

**Comment by Zth9730** [comment]
```python3
import paddle
test = paddle.to_tensor(259280)
print(test / 259280)  # 结果为0.99999994

import torch
test = torch.Tensor([259280])
print(test / 259280) ##结果为1

import numpy as np
test = np.float32(259280)
print(test / 259280) ##结果为1
```

**Comment by zhiboniu** [comment]
好的，我们安排专人来看一下，请关注后续升级内容。

**Comment by ZHUI** [comment]
可能添加了 epsilon 防止发生 除 0 错误？

**Comment by yuwoyizhan** [comment]
整数除法我不懂,如果是浮点数除法,那电脑程序的结果大概率无法跟数学计算结果相同的.举个简单例子,0.2+0.5-0.7跟0比较,结果是false.不要对计算机的浮点数的运算要求太高,否则可能导致性能大幅度下降.飞桨升级浮点数相关内容的话,也得测试性能会不会下降.
