### ISSUE TITLE
How is paddle.jit.to_static  implemented ?

### ISSUE THREAD

**Issue by OccupyMars2030** [PaddlePaddle/Paddle#45485]
### 请提出你的问题 Please ask your question

[The document  of paddle.jit.save  on official  PaddlePaddle  website](https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/jit/to_static_cn.html#to-static) tells 
 me  that  its source code is  located  at  [python\paddle\fluid\dygraph\jit.py](https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/fluid/dygraph/jit.py),  but  I  cannot  find  it.

I  find  paddle.jit.not_to_static  in the file,  but  I cannot  find  paddle.jit.to_static

**Comment by OccupyMars2030** [comment]
<img width="836" alt="image" src="https://user-images.githubusercontent.com/31559413/187020840-bf256962-1928-4955-a82f-6aa830de54f1.png">

**Comment by wangxinxin08** [comment]
The concrete implementation of jit is in the c-plus-plus code, you may refer to relative classes in the c-plus-plus source code
