### ISSUE TITLE
try to put all the inference logic into a model's forward method

### ISSUE THREAD

**Issue by OccupyMars2030** [PaddlePaddle/Paddle#45484]
### 请提出你的问题 Please ask your question

![952753f157907e073063bfaed394b7f](https://user-images.githubusercontent.com/31559413/187006309-9c0d7eb7-12e8-4167-b33e-543ecf0fa47f.jpg)

https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/guides/jit/case_analysis_cn.html#inputspec

When I read the above blue part  on the official  documentation,  I'm not quite clear about what it means.  Can the PaddlePaddle experts  give  a  concrete  code  example  to  clarify it  and  add  the  code  example  to  the  official  documentation ???

**Comment by wangxinxin08** [comment]
I think the description is clear. It mainly says two things:
1. you need write your code about inference in `forward` function
2. About the training code which may be wrote in `forward` function, you should write them in the `self.training` branch

For example,
``` python
class Model(nn.Layer):
    def __init__(self, *args, **kwargs):
        # do something for intialization
    def forward(self, x):
        if self.training:
            # get loss
        else:
            # inference and get prediction
```
