### ISSUE TITLE
AI studio后台训练无法保存模型

### ISSUE THREAD

**Issue by Agino-ltp** [PaddlePaddle/Paddle#45487]
### 请提出你的问题 Please ask your question

模型在AI studio中的notebook训练可以保存模型，
但是一旦使用后台训练，下载输出文件后压根没有保存的模型。无论是代码中使用相对路径还是绝对路径保存模型，下载输出文件之后啥都没有，只有之前上传的版本文件

**Comment by wangxinxin08** [comment]
AI studio需要保存模型到特定的文件夹才可以下载

**Comment by Agino-ltp** [comment]
> AI studio需要保存模型到特定的文件夹才可以下载

感谢回复！我之前用的话是脚本任务才需要保存到特定的文件夹，后台任务不需要。前段时间用后台任务的话也是可以保存的，现在后台任务是改了吗？也要和脚本任务一样吗

**Comment by wangxinxin08** [comment]
你可以先试下

**Comment by Dai-jl** [comment]
> 

请问这个问题解决了吗，要保存到什么文件夹才可以？

**Comment by Agino-ltp** [comment]
> > 
> 
> 请问这个问题解决了吗，要保存到什么文件夹才可以？

没有，我也不知道要保存到什么文件夹

**Comment by wangxinxin08** [comment]
@Dai-jl @Agino-ltp 看下脚本任务的介绍

**Comment by DesenbergChina** [comment]
你好，我也遇到相同的问题，请问脚本任务是在官方文档看吗？具体在那一部分呢？

**Comment by DesenbergChina** [comment]
> > AI studio需要保存模型到特定的文件夹才可以下载
> 
> 感谢回复！我之前用的话是脚本任务才需要保存到特定的文件夹，后台任务不需要。前段时间用后台任务的话也是可以保存的，现在后台任务是改了吗？也要和脚本任务一样吗

我觉得会不会是bug？原来一直都可以

**Comment by DesenbergChina** [comment]
> 您好，我们已经收到了您的问题，会安排技术人员尽快解答您的问题，请耐心等待。请您再次检查是否提供了清晰的问题描述、复现代码、环境&版本、报错信息等。同时，您也可以通过查看[官网API文档](https://www.paddlepaddle.org.cn/documentation/docs/zh/api_cn/index_cn.html)、[常见问题](https://www.paddlepaddle.org.cn/documentation/docs/zh/faq/index_cn.html)、[历史Issue](https://github.com/PaddlePaddle/Paddle/issues)、[AI社区](https://ai.baidu.com/forum/topic/list/168)来寻求解答。祝您生活愉快～
> 
> Hi! We've received your issue and please be patient to get responded. We will arrange technicians to answer your questions as soon as possible. Please make sure that you have posted enough message to demo your request. You may also check out the [API](https://www.paddlepaddle.org.cn/documentation/docs/zh/api_cn/index_cn.html)，[FAQ](https://www.paddlepaddle.org.cn/documentation/docs/zh/faq/index_cn.html)，[Github Issue](https://github.com/PaddlePaddle/Paddle/issues) and [AI community](https://ai.baidu.com/forum/topic/list/168) to get the answer.Have a nice day!

九天了，也没动静，官方好慢TT

**Comment by Agino-ltp** [comment]
> > > AI studio需要保存模型到特定的文件夹才可以下载
> > 
> > 
> > 感谢回复！我之前用的话是脚本任务才需要保存到特定的文件夹，后台任务不需要。前段时间用后台任务的话也是可以保存的，现在后台任务是改了吗？也要和脚本任务一样吗
> 
> 我觉得会不会是bug？原来一直都可以

之前确实能保存，现在保存不了。我现在都不用后台任务了，直接改用脚本任务

**Comment by DesenbergChina** [comment]
> > > > AI studio需要保存模型到特定的文件夹才可以下载
> > > 
> > > 
> > > 感谢回复！我之前用的话是脚本任务才需要保存到特定的文件夹，后台任务不需要。前段时间用后台任务的话也是可以保存的，现在后台任务是改了吗？也要和脚本任务一样吗
> > 
> > 
> > 我觉得会不会是bug？原来一直都可以
> 
> 之前确实能保存，现在保存不了。我现在都不用后台任务了，直接改用脚本任务

请问脚本任务会不会比较麻烦呀？而且他保存的uotput文件夹可以直接看到吗？

**Comment by Agino-ltp** [comment]
> > > > > AI studio需要保存模型到特定的文件夹才可以下载
> > > > 
> > > > 
> > > > 感谢回复！我之前用的话是脚本任务才需要保存到特定的文件夹，后台任务不需要。前段时间用后台任务的话也是可以保存的，现在后台任务是改了吗？也要和脚本任务一样吗
> > > 
> > > 
> > > 我觉得会不会是bug？原来一直都可以
> > 
> > 
> > 之前确实能保存，现在保存不了。我现在都不用后台任务了，直接改用脚本任务
> 
> 请问脚本任务会不会比较麻烦呀？而且他保存的uotput文件夹可以直接看到吗？

比后台任务麻烦，保存的output文件看不到，运行完下载后才能看到，而且output文件必须保存到指定的目录里面才能下载

**Comment by DesenbergChina** [comment]
> > > > > > AI studio需要保存模型到特定的文件夹才可以下载
> > > > > 
> > > > > 
> > > > > 感谢回复！我之前用的话是脚本任务才需要保存到特定的文件夹，后台任务不需要。前段时间用后台任务的话也是可以保存的，现在后台任务是改了吗？也要和脚本任务一样吗
> > > > 
> > > > 
> > > > 我觉得会不会是bug？原来一直都可以
> > > 
> > > 
> > > 之前确实能保存，现在保存不了。我现在都不用后台任务了，直接改用脚本任务
> > 
> > 
> > 请问脚本任务会不会比较麻烦呀？而且他保存的uotput文件夹可以直接看到吗？
> 
> 比后台任务麻烦，保存的output文件看不到，运行完下载后才能看到，而且output文件必须保存到指定的目录里面才能下载

好吧TT

**Comment by wangxinxin08** [comment]
@Desenber @Agino-ltp 可以发一下你们的项目id

**Comment by DesenbergChina** [comment]
> @Desenber @Agino-ltp 可以发一下你们的项目id

等我整理一波吧
