### ISSUE TITLE
windows develop分支编译不过。

### ISSUE THREAD

**Issue by xiaohemaikoo** [PaddlePaddle/Paddle#45483]
### 问题描述 Issue Description

![QQ图片20220826195809](https://user-images.githubusercontent.com/35183089/186964669-cb0f41df-8e6d-495d-a98e-69eb8098d83c.png)

编译选项：
cmake .. -GNinja -DWITH_GPU=ON -DWITH_UNITY_BUILD=ON -DWITH_TESTING=ON

编译基线commit：
commit bba13e219f9586ab52ef26d630c65144b2dfcf85
Author: wanghuancoder <wanghuan29@baidu.com>
Date:   Sat Aug 20 20:39:51 2022 +0800

    [Eager] pylayer detach output tensor if it is equal with input (#45065)

    * pylayer detach output tensor if it is equal with input

    * pylayer detach output tensor if it is equal with input

问题：
编译无法找到文件： auto_parallel.pb.h

### 版本&环境信息 Version & Environment Information

****************************************
Paddle version: 0.0.0
Paddle With CUDA: True

OS: Windows 10
Python version: 3.7.3

CUDA version: 11.3.109
Build cuda_11.3.r11.3/compiler.29920130_0
cuDNN version: None.None.None
Nvidia driver version: 465.89
****************************************

**Comment by OccupyMars2030** [comment]
-DWITH_UNITY_BUILD=ON 的作用似乎是加速编译，请问如果你完全用飞桨官网上的编译命令，能否编译通过？我只是个围观群众，不是飞桨员工。

**Comment by xiaohemaikoo** [comment]
不加-DWITH_UNITY_BUILD=ON，我本地不能编译通过。加了-DWITH_UNITY_BUILD=ON才编过了。


> -DWITH_UNITY_BUILD=ON 的作用似乎是加速编译，请问如果你完全用飞桨官网上的编译命令，能否编译通过？我只是个围观群众，不是飞桨员工。

**Comment by wangxinxin08** [comment]
你现在能编译通过吗？develop分支不稳定，可以拉取最新分支编译。另外，报错信息是说缺少了一个文件，auto_parallell.pb.h，这个文件是由auto_parallell.proto经过protobuf编译而成的，可能你中间存在一些过程没有编译通过而报错了，可能是由于网络或者一些包没有安装导致的

**Comment by zhwesky2010** [comment]
@xiaohemaikoo 你好 这个是随机挂，是因为有些头文件是生成的，由于文件编译顺序是随机的，就有可能出现头文件缺失问题。可以先 ninja third_party，再 ninja paddle；一般就比较稳定

**Comment by xiaohemaikoo** [comment]
非常感谢，按照指导，拉取最新代码，编译通过了。
