### ISSUE TITLE
conflicts about  the description of "input_spec" argument of  paddle.jit.to_static()  on official documentation

### ISSUE THREAD

**Issue by OccupyMars2030** [PaddlePaddle/Paddle#45486]
### 文档链接&描述 Document Links & Description

[（4）方式四：指定非 Tensor 参数类型](https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/guides/jit/basic_usage_cn.html#jibenyongfa)
says:
net = to_static(input_spec=[InputSpec(shape=[None, 10], name='x'), True])

which has a conflict with  [目前仅支持指定 Tensor 类型信息，非 Tensor 类型信息均使用 函数定义的默认值](https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/guides/jit/case_analysis_cn.html#morencanshu) 

### 请提出你的建议 Please give your suggestion

I don't know the implementation of  paddle.jit.to_static ,  so  I  don't known what to suggest.
Please refer to this :
https://github.com/PaddlePaddle/Paddle/issues/45485

**Comment by OccupyMars2030** [comment]
```python
import paddle
from paddle.jit import to_static
from paddle.nn import Layer
from paddle.static import InputSpec

class SimpleNet(Layer):
    def __init__(self, ):
        super(SimpleNet, self).__init__()
        self.linear = paddle.nn.Linear(10, 3)
        self.relu = paddle.nn.ReLU()

    def forward(self, x, use_act=False):
        out = self.linear(x)
        if use_act:
            out = self.relu(out)
        return out

net = SimpleNet()
# 方式一：save inference model with use_act=False
net = to_static(net, input_spec=[InputSpec(shape=[None, 10], name='x')])
paddle.jit.save(net, path='./simple_net')

# 方式二：save inference model with use_act=True
net = to_static(net, input_spec=[InputSpec(shape=[None, 10], name='x'), True])
paddle.jit.save(net, path='./simple_net')
```

**Comment by OccupyMars2030** [comment]
The above code can work, thus  shows  that  input_spec can be used to  specify  non-Tensor arguments in  the forward method.

**Comment by wangxinxin08** [comment]
收到你的反馈，我们更新一下
