### ISSUE TITLE
让昆仑xpu cast kernel支持 fp32 to uint8，但是mutable_data 过不去approval

### ISSUE THREAD

**Issue by HarperCy** [PaddlePaddle/Paddle#45559]
### 需求描述 Feature Description

任务目标（请描述你正在做的项目是什么，如模型、论文、项目是什么？）; <br /> 需求场景（请描述你的项目中为什么需要用此功能）;  <br /> 功能描述（请简单描述或设计这个功能）

![image](https://user-images.githubusercontent.com/47998305/187376458-4dc55386-2569-4d94-aa59-367b8b3fe49e.png)

cast 这个kernel，按照上面格式的话，都是用的mutable data，但是这样的话

paddle CI APPROVAL过不去

<img width="856" alt="image" src="https://user-images.githubusercontent.com/47998305/187376468-f0ab648a-fb11-4677-9fc0-6f0d9cce8ac4.png">

**Comment by LiuChiachi** [comment]
需要改成alloc，不能豁免，已入库的也需要修改
