### ISSUE TITLE
关于基础API: paddle.shape()的疑问

### ISSUE THREAD

**Issue by math-yyj** [PaddlePaddle/Paddle#45556]
### 请提出你的问题 Please ask your question

看了下paddle.shape(x)返回的是Tensor类型的NCHW，并且带梯度标志

但是一般不都是直接用x.shape获取Tensor尺寸么？

而且我实在想不出有什么地方是需要N C H W"带着梯度"参与计算的，就算静态图也不至于这样吧？

有没有官方开发人员给个例子表明，有这种类似于“x.shape不行，就得用paddle.shape(x)”的场景？谢谢

**Comment by LiuChiachi** [comment]
HI，
可以参考官网文档，https://www.paddlepaddle.org.cn/documentation/docs/zh/guides/jit/case_analysis_cn.html
我的理解，一个比较常用的场景是，模型动转静的时候，paddle.shape()是支持的，但是x.shape()可能会报错。
