### ISSUE TITLE
”兴智杯“全国人工智能创新应用大赛：论文复现赛

### ISSUE THREAD

**Issue by paddle-lwfx** [PaddlePaddle/Paddle#45566]
hi，大家好，非常高兴的告诉大家，兴智杯——前沿模型复现赛已经开始了，本次复现赛共将有15篇的经典&前沿论文供大家复现。详细信息可以参考[兴智杯官网链接](http://www.aiinnovation.com.cn/#/trackDetail?id=20)，或[AI Studio 链接](https://aistudio.baidu.com/aistudio/competition/detail/406/0/introduction)，大家是否已经迫不及待了呢~

为了帮助大家更好的了解每篇论文的复现进度，本次复现赛将在本帖中汇总信息。如果你报名/提交结果，需要按格式在进行回复，我们每天会汇总所有的信息，并更新在下表中，你可以通过下面的表格中，了解到每一篇论文的相关信息。

回复的格式为：

【队名】：在兴智杯官网报名时使用的团队名称（请注意一致性，如不一致视为无效作品）

【序号】：你队伍想要复现的论文序号

【论文】：你队伍想要复现的论文名称

【状态】：报名/提交

【repo链接】：repo的链接

如：

【队名】：百度飞桨

【序号】：兴1

【论文】：Paper 1

【状态】：提交

【repo链接】：https://github.com/PaddlePaddle/Paddle

## 兴智杯 全国人工智能创新应用大赛        
[兴智杯报名入口](http://www.aiinnovation.com.cn/#/trackDetail?id=20)
| 序号 | 论文信息  |  复现等级 | 报名队伍 | 完成队伍 |
| ---- | ---------- | ------ | ---- | ---- |
| ~~兴1~~ |  ~~[Rethinking Bottleneck Structure for Efficient Mobile Network Design](https://arxiv.org/abs/2007.02269)~~ |  ⭐️ | 那拒绝了(报名)([rethinking_bottleneck_design_paddlepaddle](https://github.com/duyongqi/rethinking_bottleneck_design_paddlepaddle)) </br>拼手速(报名&提交)([MobileNeXt-paddle](https://github.com/flytocc/MobileNeXt-paddle))     |   拼手速       |
| 兴2 |  [Augmented Geometric Distillation for Data-Free Incremental Person ReID ](https://openaccess.thecvf.com/content/CVPR2022/html/Lu_Augmented_Geometric_Distillation_for_Data-Free_Incremental_Person_ReID_CVPR_2022_paper.html)|  ⭐️ | SOTAFinder(报名)([Augmented-Geometric-Distillation-PaddlePaddle](https://github.com/oliverck/Augmented-Geometric-Distillation-PaddlePaddle))</br>just try it(报名)([Augmented-Geometric-Distillation-PaddlePaddle](https://github.com/Cloud-Rambler/Augmented-Geometric-Distillation-PaddlePaddle))      |          |
| ~~兴3~~ |  ~~[Swin-Unet: Unet-like Pure Transformer for Medical Image Segmentation](https://arxiv.org/abs/2105.05537)~~ |  ⭐️ |  AIEX(报名)([Swin-Unet-PaddlePaddle](https://github.com/AIEXTeam/Swin-Unet-PaddlePaddle)) </br>在校菜鸟(报名)([xingzhibei](https://github.com/pfqiu9/xingzhibei)) </br>科创生活-吉大小队(报名&提交)([SwinUNet](https://github.com/yuanfengliyuanfengli/UCTrans_paddle_try/))</br>老1.5(报名&提交)([SwinUNet](https://github.com/marshall-dteach/SwinUNet))   |     老1.5     |
| 兴4 |  [KiU-Net: Overcomplete Convolutional Architectures for Biomedical Image and Volumetric Segmentation](https://arxiv.org/pdf/2010.01663v2.pdf)  |  ⭐️ |三傻大闹(报名 & 提交)([sanshadanao](https://github.com/Dufferent/sanshadanao))  </br>SaltyFish(报名)([KiU-Net_PaddlePaddle](https://github.com/Ifjmww/KiU-Net_PaddlePaddle))     |          |
| 兴5 |  [A Late Fusion CNN for Digital Matting](https://openaccess.thecvf.com/content_CVPR_2019/papers/Zhang_A_Late_Fusion_CNN_for_Digital_Matting_CVPR_2019_paper.pdf)  |  ⭐️ | TeamYang(报名)([Late-Fusion-CNN](https://github.com/YJGitHubaccount/Late-Fusion-CNN))      |          |
| ~~兴6~~ |  ~~[FastFlow: Unsupervised Anomaly Detection and Localization via 2D Normalizing Flows](https://arxiv.org/pdf/2111.07677.pdf)~~ |  ⭐️ | EMA(报名&提交)([fastflow_paddle](https://github.com/lelexx/fastflow_paddle))        |  EMA        |
| ~~兴7~~ |  ~~[Aggregated Contextual Transformations for High-Resolution Image Inpainting](https://paperswithcode.com/paper/aggregated-contextual-transformations-for)~~ |  ⭐️ | FutureSI(报名&提交)([README.md](https://github.com/ctkindle/AOT_GAN_Paddle/blob/main/README.md))     |   FutureSI       |
| 兴8 |  [Simple Baselines for Image Restoration](https://arxiv.org/pdf/2204.04676) |  ⭐️ | low-level(报名)([NAFNet-Paddle.git](https://github.com/AlexZou14/NAFNet-Paddle.git))</br>不爱做科研(报名&提交)([NAFNet-pd](https://github.com/kongdebug/NAFNet-pd))     |          |
|兴 9 |  [FCFR-Net: Feature Fusion based Coarse-to-Fine Residual Learning forDepth Completion](https://arxiv.org/abs/2012.08270) |  ⭐️ | Inspiration(报名)([Paddle_FCFR_Net](https://github.com/inspiration12138/Paddle_FCFR_Net))      |          |
| ~~兴10~~ |  ~~[CoST: Contrastive Learning of Disentangled Seasonal-Trend Representations for Time Series Forecasting](https://openreview.net/forum?id=PilZY3omXV2)~~ |  ⭐️ |aptx1231(报名&提交)([CoST_Paddle](https://github.com/aptx1231/CoST_Paddle))      |        |
| 兴 11 |  [TS2Vec: Towards Universal Representation of Time Series](https://arxiv.org/abs/2106.10466) |  ⭐️ |  aptx1231(报名)([ts2vec_Paddle](https://github.com/aptx1231/ts2vec_Paddle))           |     |
| 兴12 |  [Is Pseudo-Lidar needed for Monocular 3D Object detection?](https://paperswithcode.com/paper/is-pseudo-lidar-needed-for-monocular-3d) |  ⭐️ |      |          |
| ~~兴13~~ |  ~~[PAConv: Position Adaptive Convolution with Dynamic Kernel Assembling on Point Clouds](https://paperswithcode.com/paper/paconv-position-adaptive-convolution-with)~~ |  ⭐️ |  txyugood(报名 & 提交)([PaddlePAConv](https://github.com/txyugood/PaddlePAConv))      |   txyugood        |
| 兴14 |  [From Two to One: A New Scene Text Recognizer with Visual Language Modeling Network](https://openaccess.thecvf.com/content/ICCV2021/papers/Wang_From_Two_to_One_A_New_Scene_Text_Recognizer_With_ICCV_2021_paper.pdf)  |  ⭐️ | 外阜在京劳动力(报名)([FromTwotToOne](https://github.com/vax521/FromTwotToOne)) </br>超级码立(报名&提交)([FromTwotToOne](https://github.com/Lieberk/Paddle-VisionLAN))        |          |
| ~~兴15~~ |  ~~[Scene Text Telescope: Text-Focused Scene Image Super-Resolution](https://openaccess.thecvf.com/content/CVPR2021/papers/Chen_Scene_Text_Telescope_Text-Focused_Scene_Image_Super-Resolution_CVPR_2021_paper.pdf)~~ |  ⭐️|  lfy(报名)([scene-text-telescope](https://github.com/Li-fAngyU/scene-text-telescope))  </br>小星(报名)([SmallStar](https://github.com/yongzheJIN/SmallStar)) </br>超级码立(报名&提交)([scene-text-telescope](https://github.com/Lieberk/Paddle-TextSR-STT))      | 超级码立         |

**Comment by Bluessea** [comment]
【队名】：从容应队

【序号】：兴1

【论文】：Rethinking Bottleneck Structure for Efficient Mobile Network Design

【状态】：报名

【repo链接】：https://github.com/Bluessea/MobileNeXt-Class.git

**Comment by Dufferent** [comment]
【队名】：三傻大闹

【序号】：兴4

【论文】：[KiU-Net: Overcomplete Convolutional Architectures for Biomedical Image and Volumetric Segmentation]

【状态】：报名 & 提交

【repo链接】：https://github.com/Dufferent/sanshadanao

**Comment by Ifjmww** [comment]
【队名】：SaltyFish

【序号】：兴4

【论文】：[KiU-Net: Overcomplete Convolutional Architectures for Biomedical Image and Volumetric Segmentation](https://arxiv.org/pdf/2010.01663v2.pdf)

【状态】：报名

【repo链接】：https://github.com/Ifjmww/KiU-Net_PaddlePaddle

**Comment by yongzheJIN** [comment]
【队名】小星
【序号】兴15
【论文】[Scene Text Telescope: Text-Focused Scene Image Super-Resolution](https://openaccess.thecvf.com/content/CVPR2021/papers/Chen_Scene_Text_Telescope_Text-Focused_Scene_Image_Super-Resolution_CVPR_2021_paper.pdf)
【状态】报名
【repo链接】：https://github.com/yongzheJIN/SmallStar

**Comment by txyugood** [comment]
【队名】：txyugood

【序号】：兴13

【论文】：PAConv: Position Adaptive Convolution with Dynamic Kernel Assembling on Point Clouds

【状态】：报名 & 提交

【repo链接】：https://github.com/txyugood/PaddlePAConv
【大赛官网团队名称】：txyugood

**Comment by yuanfengliyuanfengli** [comment]
【队名】：科创生活-吉大小队
【序号】：兴3
【论文】：Swin-Unet: Unet-like Pure Transformer for Medical Image Segmentation https://arxiv.org/abs/2105.05537
【状态】：报名&提交
【repo链接】：https://github.com/yuanfengliyuanfengli/UCTrans_paddle_try/

**Comment by marshall-dteach** [comment]
【队名】：调查乌度卡
【序号】：兴3
【论文】：Swin-Unet: Unet-like Pure Transformer for Medical Image Segmentation https://arxiv.org/abs/2105.05537
【状态】：报名&提交
【repo链接】：https://github.com/marshall-dteach/SwinUNet

**Comment by kongdebug** [comment]
【队名】：不爱做科研

【序号】：兴8

【论文】：[Simple Baselines for Image Restoration](https://arxiv.org/pdf/2204.04676)

【状态】：提交

【repo链接】：https://github.com/kongdebug/NAFNet-pd

**Comment by ctkindle** [comment]
【队名】：FutureSI

【序号】：兴7

【论文】：[Aggregated Contextual Transformations for High-Resolution Image Inpainting](https://paperswithcode.com/paper/aggregated-contextual-transformations-for)

【状态】：提交

【repo链接】：https://github.com/ctkindle/AOT_GAN_Paddle/blob/main/README.md

**Comment by Lieberk** [comment]
【队名】：超级码立

【序号】：兴14

【论文】：[From Two to One: A New Scene Text Recognizer with Visual Language Modeling Network](https://openaccess.thecvf.com/content/ICCV2021/papers/Wang_From_Two_to_One_A_New_Scene_Text_Recognizer_With_ICCV_2021_paper.pdf)

【状态】：报名 & 提交

【repo链接】：https://github.com/Lieberk/Paddle-VisionLAN

**Comment by marshall-dteach** [comment]
* 由于兴智杯官网队伍名为：老1.5，因此将调查乌度卡改名为老1.5*
【队名】：老1.5
【序号】：兴3
【论文】：Swin-Unet: Unet-like Pure Transformer for Medical Image Segmentation https://arxiv.org/abs/2105.05537
【状态】：报名&提交
【repo链接】：https://github.com/marshall-dteach/SwinUNet

**Comment by Lieberk** [comment]
【队名】：超级码立

【序号】：兴15

【论文】：[Scene Text Telescope: Text-Focused Scene Image Super-Resolution](https://openaccess.thecvf.com/content/CVPR2021/papers/Chen_Scene_Text_Telescope_Text-Focused_Scene_Image_Super-Resolution_CVPR_2021_paper.pdf)

【状态】：报名 & 提交

【repo链接】：https://github.com/Lieberk/Paddle-TextSR-STT

**Comment by boly0110** [comment]
【队名】：boly

【序号】：兴11

【论文】：[TS2Vec: Towards Universal Representation of Time Series](https://arxiv.org/abs/2106.10466)

【状态】：报名 & 提交

【repo链接】：https://github.com/boly0110/ts2vec_pp.git

**Comment by Li-fAngyU** [comment]
【队名】：lfy

【序号】：兴15

【论文】：[Scene Text Telescope: Text-Focused Scene Image Super-Resolution](https://openaccess.thecvf.com/content/CVPR2021/papers/Chen_Scene_Text_Telescope_Text-Focused_Scene_Image_Super-Resolution_CVPR_2021_paper.pdf)

【状态】：提交

【repo链接】：https://github.com/Li-fAngyU/scene-text-telescope

**Comment by renmada** [comment]
【队名】：scv

【序号】：兴5

【论文】：A Late Fusion CNN for Digital Matting 

【状态】：提交

【repo链接】：https://github.com/renmada/FusionMatting-paddle

**Comment by duyongqi** [comment]
【队名】：存在

【序号】：兴1

【论文】：[Rethinking Bottleneck Structure for Efficient Mobile Network Design](https://arxiv.org/abs/2007.02269)

【状态】：报名&提交

【repo链接】：https://github.com/duyongqi/MobileNeXt

**Comment by aptx1231** [comment]
【队名】：aptx1231

【序号】：兴10

【论文】：CoST: Contrastive Learning of Disentangled Seasonal-Trend Representations for Time Series Forecasting

【状态】：报名&提交

【repo链接】：https://github.com/aptx1231/CoST_Paddle

**Comment by GuoQuanhao** [comment]
【队名】：HaoHao

【序号】：兴5

【论文】：A Late Fusion CNN for Digital Matting

【状态】：报名

【repo链接】：https://github.com/GuoQuanhao/FusionMatting-Paddle

**Comment by GuoQuanhao** [comment]
【队名】：HaoHao

【序号】：兴5

【论文】：A Late Fusion CNN for Digital Matting

【状态】：报名&提交

【repo链接】：https://github.com/GuoQuanhao/FusionMatting-Paddle

**Comment by Wolkenwandler** [comment]
【队名】：just try it

【序号】：兴2

【论文】：[Augmented Geometric Distillation for Data-Free Incremental Person ReID](https://openaccess.thecvf.com/content/CVPR2022/html/Lu_Augmented_Geometric_Distillation_for_Data-Free_Incremental_Person_ReID_CVPR_2022_paper.html)

【状态】：报名 & 提交

【repo链接】：https://github.com/Cloud-Rambler/Augmented-Geometric-Distillation-PaddlePaddle
