### ISSUE TITLE
Executor TODO

### ISSUE THREAD

**Issue by helinwang** [PaddlePaddle/Paddle#4557]
- `VarDesc` add persistable field
- Executor will be only created once
- Executor(devices)
- `vector<Tensor> Run(ProgramDesc, Scope)`
- `Run` must support concurrent run.
- Every target will create a `fetch OP`, stored in `ProgramDesc`, `fetch OP` is: `(OP, OP output offset)` or `Var`.

**Comment by wangkuiyi** [comment]
Record @jacquesqiao  and @reyoung 's comment here.

Given a PaddlePaddle program like the following

```python
x = add(...)
cost = cross_entropy(x)
opts = optimize(cost)
```

Users can call

1. `Run(x)` to evaluate till x.
1. `Run(cost)` for the foward pass.
1. `Run(opts)` for the backward passing, including optimization.

**Comment by wangkuiyi** [comment]
The Python `Eval` function calls a C++ `Prunner` class, which takes 

1. a ProgramDesc, and
1. some targets, that could be
   1. variables
   1. operators

and outputs a pruned ProgramDesc, which, once executed, computes the specified targets.

**Comment by helinwang** [comment]
Eval targets will be changed to `fetch OP` so executor know what to return.

**Comment by helinwang** [comment]
Executor will create a local scope when `Run`.

**Comment by helinwang** [comment]
This issue is out-of-date, closing.
