### ISSUE TITLE
Einops doesn't support  the  PaddlePaddle  framework  currently 

### ISSUE THREAD

**Issue by OccupyMars2030** [PaddlePaddle/Paddle#45627]
### 需求描述 Feature Description
related issue: https://github.com/PaddlePaddle/Paddle/issues/34220
related PR: https://github.com/arogozhnikov/einops/pull/122
## I just want tu use einops with  paddlepaddle,   just  like  the following :

```python
import paddle
import torch
import numpy as np
from einops import rearrange


x_np = np.random.randn(1, 2, 3)
print(rearrange(x_np, "a s d -> s a d"))

x_torch = torch.randn([1, 2, 3])
print(rearrange(x_torch, "a s d -> s a d"))

x_pd = paddle.randn([1, 2, 3])
rearrange(x_pd, "a s d -> s a d")
```
The last line of code reports an error as follows: 
RuntimeError                              Traceback (most recent call last)
[<ipython-input-11-a635fd9208f2>](https://localhost:8080/#) in <module>
     12 
     13 x_pd = paddle.randn([1, 2, 3])
---> 14 rearrange(x_pd, "a s d -> s a d")

3 frames
[/usr/local/lib/python3.7/dist-packages/einops/_backends.py](https://localhost:8080/#) in get_backend(tensor)
     50                     return backend
     51 
---> 52     raise RuntimeError('Tensor type unknown to einops {}'.format(type(tensor)))
     53 
     54 

RuntimeError: Tensor type unknown to einops <class 'paddle.Tensor'>

## [The official website of  einops](https://github.com/arogozhnikov/einops) says:  
<img width="245" alt="image" src="https://user-images.githubusercontent.com/31559413/187803789-56c58abe-9a8d-416b-a89a-11f9f5e6b033.png">
It seems that  Einops  doesn't work  with the PaddlePaddle framework  now.

### 替代实现 Alternatives

you  can  transform  a  paddle  Tensor  to  a  numpy array  to  work  with  einops

**Comment by OccupyMars2030** [comment]
If the PaddlePaddle team doesn't have time to do it,  I will  try  to  implement the requirement  before   2022/10/15 when I  have  time.

**Comment by jzhang533** [comment]
related issue: #34220

**Comment by OccupyMars2030** [comment]
Now, I understand it is not an easy problem to solve.

**Comment by luotao1** [comment]
@zhouwei25 is doing zero-dimensional tensor related work now. 
 - In #34220, the author of einops said: Support for zero-dimensional tensor is a hard requirement for inclusion for [einops](https://github.com/arogozhnikov/einops) support.
- Could you help update the progress of zero-dimensional work?

**Comment by zhwesky2010** [comment]
@luotao1 This is still under discussion and pending review. It may cause incompatibility. It is not recommended to modify the output 0D at present, and Modifications PR must be compatible with before.

**Comment by zhwesky2010** [comment]
@OccupyMars2025  Thanks for asking questions. Plan 0D tensor has passed the internal review and is under development. We will support transpose and reshape 0D before 10/20. In that time, The work of Einops supporting Paddle will not be blocked.

**Comment by zhwesky2010** [comment]
@OccupyMars2025  Thanks, Are you interested in supporting paddle as the backend for Einops?
we have fixed the prolem mentioned above in https://github.com/PaddlePaddle/Paddle/pull/46555.  And are there any other problem?

**Comment by zhwesky2010** [comment]
This PR support it: https://github.com/arogozhnikov/einops/pull/242
EinOps support Paddle Now, thank to pay attention~

**Comment by nemonameless** [comment]
`pip install git+https://github.com/arogozhnikov/einops.git`
