### ISSUE TITLE
paddle竞赛提交异常：W0901 11:15:55.087069 70 gpu_resources.cc:61] Please NOTE: device

### ISSUE THREAD

**Issue by HereNowL** [PaddlePaddle/Paddle#45664]
GPU异常

提交预测文件后，显示异常：W0901 11:15:55.087069 70 gpu_resources.cc:61] Please NOTE: device。在本地可正常运行

**Comment by HereNowL** [comment]
无论有没有设置GPU id“paddle.device.set_device('gpu:0')”都会报错

**Comment by cxxly** [comment]
您好，具体竞赛背景、问题准确描述、复现方法请补充下，或者如果有群的话，去具体竞赛群咨询下
