### ISSUE TITLE
test_adam_op_multi_thread random failure (Segmentation fault)

### ISSUE THREAD

**Issue by Wong4j** [PaddlePaddle/Paddle#45669]
### bug描述 Describe the Bug

test_adam_op_multi_thread failed randomly.
Environment:
A100 GPU with NGC PaddlePaddle 22.08 container
```
$ python tools/summary_env.py
****************************************
Paddle version: 2.3.0
Paddle With CUDA: True

OS: Ubuntu 20.04
Python version: 3.8.10

CUDA version: 11.7.99
Build cuda_11.7.r11.7/compiler.31442593_0
cuDNN version: None.None.None
Nvidia driver version: 515.65.01
****************************************
```
To reproduce:
```
$ cat Dockerfile
FROM nvcr.io/nvidia/paddlepaddle:22.08-py3

RUN pip install --upgrade pip && \
    pip install -r /opt/paddle/paddle/python/requirements.txt

RUN cd /opt/paddle/paddle && \
    mkdir -p build && \
    cd build && \
    cmake .. \
    -DCMAKE_EXPORT_COMPILE_COMMANDS=ON \
    -DCMAKE_CXX_FLAGS="-Wno-error=deprecated-copy -Wno-error=pessimizing-move -Wno-error=init-list-lifetime" \
    -DCMAKE_BUILD_TYPE=Release \
    -DCMAKE_CUDA_FLAGS="-t0" \
    -DCUDA_ARCH_NAME=Manual \
    -DCUDA_ARCH_BIN="80" \
    -DWITH_INCREMENTAL_COVERAGE=OFF \
    -DWITH_INFERENCE_API_TEST=OFF \
    -DWITH_DISTRIBUTE=ON \
    -DWITH_COVERAGE=OFF \
    -DWITH_TENSORRT=OFF \
    -DWITH_TESTING=ON \
    -DWITH_CONTRIB=ON \
    -DWITH_ROCM=OFF \
    -DWITH_RCCL=OFF \
    -DWITH_STRIP=ON \
    -DWITH_MKL=OFF \
    -DWITH_AVX=ON \
    -DWITH_GPU=ON \
    -DWITH_PYTHON=ON \
    -DPY_VERSION=3.8 \
    -Wno-dev

RUN cd /opt/paddle/paddle/build && make -j `nproc`
```
Run the test repeatedly for hundreds times. 
```
cd /opt/paddle/paddle/build
```
```shell
$ cat test.sh
set -ex
for ((i=1;i<=500;i++))
do
    echo $i
    ctest -R ^test_adam_op_multi_thread$ -V
done
```

Error log:
```
1349: --------------------------------------
1349: C++ Traceback (most recent call last):
1349: --------------------------------------
1349: 0   paddle::framework::ThreadPoolTempl<paddle::framework::StlThreadEnvironment>::WorkerLoop(int)
1349: 1   paddle::framework::InterpreterCore::RunInstructionAsync(unsigned long, std::vector<std::atomic<unsigned long>, std::allocator<std::atomic<unsigned long> > >*, std::vector<std::atomic<unsigned long>, std::allocator<std::atomic<unsigned long> > >*)
1349: 2   paddle::framework::InterpreterCore::CheckGC(paddle::framework::Instruction const&, std::vector<std::atomic<unsigned 
long>, std::allocator<std::atomic<unsigned long> > >*)
1349: 3   paddle::framework::InterpreterCoreFastGarbageCollector::Add(paddle::framework::Variable*)
1349: 4   std::_Sp_counted_base<(__gnu_cxx::_Lock_policy)2>::_M_release()
1349: 5   std::_Sp_counted_deleter<phi::Allocation*, std::function<void (phi::Allocation*)>, std::allocator<void>, (__gnu_cxx::_Lock_policy)2>::_M_dispose()
1349: 6   paddle::memory::allocation::CUDAAllocator::FreeImpl(phi::Allocation*)
1349: 7   paddle::platform::RecordedGpuMallocHelper::Free(void*, unsigned long)
1349: 8   std::_Rb_tree<void*, void*, std::_Identity<void*>, std::less<void*>, std::allocator<void*> >::erase(void* const&)   
1349:
1349: ----------------------
1349: Error Message Summary:
1349: ----------------------
1349: FatalError: `Segmentation fault` is detected by the operating system.
1349:   [TimeInfo: *** Aborted at 1662035991 (unix time) try "date -d @1662035991" if you are using GNU date ***]
1349:   [SignalInfo: *** SIGSEGV (@0x18) received by PID 109241 (TID 0x7f0fdf749700) from PID 24 ***]
1349:
1349: Segmentation fault
1/1 Test #1349: test_adam_op_multi_thread ........***Failed  139.82 sec
```

### 其他补充信息 Additional Supplementary Information

According to the error message, I think the bug is most likely caused by multi-thread race condition here. [gpu_info.cc#L303](https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/fluid/platform/device/gpu/gpu_info.cc#L303).  Multiple threads simultaneously `erase` elements in `std::set`.

**Comment by cxxly** [comment]
您好，这个测试用例文件`test_adam_op_multi_thread`是你新增的吗，我在develop最新版本及2.3.0版本均找不到这个文件

**Comment by Wong4j** [comment]
> 您好，这个测试用例文件`test_adam_op_multi_thread`是你新增的吗，我在develop最新版本及2.3.0版本均找不到这个文件

在这里，其实就是test_adam_op + FLAGS_inner_op_parallelism=4，开启4线程计算。
https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/fluid/tests/unittests/CMakeLists.txt#L544

**Comment by cxxly** [comment]
@frankwhzhang

**Comment by Wong4j** [comment]
> @frankwhzhang @cxxly 

更新一下信息，2.3.0版本的对应的代码在这里https://github.com/PaddlePaddle/Paddle/blob/v2.3.0/paddle/fluid/operators/optimizers/adam_op.h#L627
代码检查到FLAGS_inner_op_parallelism=4，就会开启4线程来计算。

在2.3.0版本下，CPU和GPU的测试都会开启multi-thread，根据报错信息，应该是GPU的部分出的bug。

develop分支下，adam_op的CPU和GPU实现分别放到了paddle/phi/kernels/selected_rows/cpu/adam_kernel.cc和paddle/phi/kernels/selected_rows/gpu/adam_kernel.cu中。其中只有cpu的代码会检查FLAGS_inner_op_parallelism=4，而gpu的代码不会检查这个FLAG，也就不会开启multi-thread。所以也请你们帮忙确认一下develop的代码是否避开了这个BUG?

**Comment by Wong4j** [comment]
> > @frankwhzhang @cxxly
> 
> 更新一下信息，2.3.0版本的对应的代码在这里https://github.com/PaddlePaddle/Paddle/blob/v2.3.0/paddle/fluid/operators/optimizers/adam_op.h#L627 代码检查到FLAGS_inner_op_parallelism=4，就会开启4线程来计算。
> 
> 在2.3.0版本下，CPU和GPU的测试都会开启multi-thread，根据报错信息，应该是GPU的部分出的bug。
> 
> develop分支下，adam_op的CPU和GPU实现分别放到了paddle/phi/kernels/selected_rows/cpu/adam_kernel.cc和paddle/phi/kernels/selected_rows/gpu/adam_kernel.cu中。其中只有cpu的代码会检查FLAGS_inner_op_parallelism=4，而gpu的代码不会检查这个FLAG，也就不会开启multi-thread。所以也请你们帮忙确认一下develop的代码是否避开了这个BUG?

cc @qili93

**Comment by zhiqiu** [comment]
hi，我本地develop跑了下 test_adam_op_multi_thread ，没有复现出该问题，另外也未发现 adam_kernel.cc中的 FLAGS_inner_op_parallelism 相关log。你们在develop还能复现问题吗？

**Comment by Wong4j** [comment]
> hi，我本地develop跑了下 test_adam_op_multi_thread ，没有复现出该问题，另外也未发现 adam_kernel.cc中的 FLAGS_inner_op_parallelism 相关log。你们在develop还能复现问题吗？

看起来develop已经没有这个问题了。那这个issue暂时先放着吧，等v2.4.0版本正式发布我再测试一次，如果没问题我会关掉这个issue

**Comment by Wong4j** [comment]
2.4.0已经解决。关掉这个issue
