### ISSUE TITLE
paddle.utils.run_check()报错，但是系统中有cuda driver

### ISSUE THREAD

**Issue by Sqhttwl** [PaddlePaddle/Paddle#45681]
能输出显卡型号
![mmexport1662101369384.png](https://user-images.githubusercontent.com/61459740/188075965-0f7b73a9-0132-432a-bcb4-f6d2f671ec96.png)
device也设置gpu卡号
![mmexport1662101416222.png](https://user-images.githubusercontent.com/61459740/188076079-2ece2656-fe78-4fdc-ba25-0f3c0a0e7d27.png)
但是运行paddle.utils.run_check()报错
![mmexport1662101428698.png](https://user-images.githubusercontent.com/61459740/188076172-b2f7934f-a019-4fd8-8779-df38d2423eff.png)

**Comment by tianxin1860** [comment]
您好，请检查是否正确配置了 CUDA 动态库的环境变量 `export LD_LIBRARY_PATH=${YOUR_CUDA_LIB_PATH}:${LD_LIBRARY_PATH}`

**Comment by Sqhttwl** [comment]
环境变量配置了，还是不行

**Comment by Sqhttwl** [comment]
我大概知道原因了，是因为paddlepaddle不支持WSL吗

**Comment by Tlntin** [comment]
> 我大概知道原因了，是因为paddlepaddle不支持WSL吗

支持，可以参考该链接，需要小小的配置一下。https://aistudio.baidu.com/aistudio/projectdetail/4440986
