### ISSUE TITLE
 cannot import name 'FC'

### ISSUE THREAD

**Issue by misonsky** [PaddlePaddle/Paddle#45697]
### bug描述 Describe the Bug

from paddle.fluid.dygraph.nn import FC 
ImportError: cannot import name 'FC'

**Comment by misonsky** [comment]
same question
from paddle.fluid.dygraph import FC 
ImportError: cannot import name 'FC'

**Comment by tianxin1860** [comment]
FC 建议通过 Linear op 来实现，具体用法请参考: https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/nn/Linear_cn.html#linear
