### ISSUE TITLE
API文档例子代码错误

### ISSUE THREAD

**Issue by enkilee** [PaddlePaddle/Paddle#45693]
### bug描述 Describe the Bug

https://www.paddlepaddle.org.cn/documentation/docs/en/develop/api/paddle/profiler/Profiler_en.html
中例子1、2、的p.step()执行。第一次可以有log文件，第二次就报错：
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
/tmp/ipykernel_168/153734649.py in <module>
      8         #train()
----> 9         p.step()

/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/profiler/profiler.py in step(self, num_samples)
    575         self.current_state = self.scheduler(self.step_num)
--> 576         self._trigger_action()
    577         self.record_event = RecordEvent(

/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/profiler/profiler.py in _trigger_action(self)
    631             if self.current_state == ProfilerState.READY:  # CLOSED -> READY
--> 632                 self.profiler.prepare()
    633             if self.current_state == ProfilerState.RECORD:  # CLOSED -> RECORD

AttributeError: 'NoneType' object has no attribute 'prepare'

During handling of the above exception, another exception occurred:

AttributeError                            Traceback (most recent call last)
/tmp/ipykernel_168/153734649.py in <module>
      7     for iter in range(10):
      8         #train()
----> 9         p.step()

/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/profiler/profiler.py in __exit__(self, exc_type, exc_val, exc_tb)
    455 
    456     def __exit__(self, exc_type, exc_val, exc_tb):
--> 457         self.stop()
    458 
    459     def start(self):

/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/profiler/profiler.py in stop(self)
    531                 "Inproper Profiler state transform: READY->CLOSED, profiler will start and stop without saving data"
    532             )
--> 533             self.profiler.start()
    534             self.profiler.stop()
    535         if self.current_state == ProfilerState.RECORD or self.current_state == ProfilerState.RECORD_AND_RETURN:

AttributeError: 'NoneType' object has no attribute 'start'

**Comment by tianxin1860** [comment]
请提供具体的 Paddle 版本号及运行环境。
