### ISSUE TITLE
Speed up the image reading for large-scale image classification.

### ISSUE THREAD

**Issue by qingqing01** [PaddlePaddle/Paddle#457]
1. Using a library with OpenCV to process image including data argumentations. 
2. This library also use multi-thread to speed up. 
3. Then loads this library in the DataProvider.

**Comment by reyoung** [comment]
In Paddle repository, we just use Python to speed up Image reading. The experimental optimization of Image reading and processing will be host in a [separate repository](https://github.com/PaddlePaddle/Image)currently. Please tracking that repository for the progress of this issue.
